### ISSUE TITLE
How to get "Market Cap" ?

### ISSUE THREAD

**Issue by deewalkman** [ccxt/ccxt#10008]
I tried with fetch_ticker and look at info. but it was not there.

Can you tell me where to find it ? 
Thanks.

**Comment by ttodua** [comment]
Can you describe the story in full? 
which exchange you tried, or which token you wanted to get, and what code (example) you used?

in most cases, exchanges doesn't contain that info. only CoinMarketCap might give that, and moreover, not for 'ticker' but for specific 'currency' (coin). So, if you still want to try with any specific exchange, try like this:

```
const ex = new binance(..apikeys...);
console.log ( ex.fetchCurrencies() );
```
and under 'info' property of the currency, find out if that exchange gives any info about marketcap (but i doubt any exchange had correct infos there, I recommend CoinMarketCap api)
