### ISSUE TITLE
Good News! Ascendex Now Has API Withdraw Support

### ISSUE THREAD

**Issue by drsavant-pub** [ccxt/ccxt#10005]
Ascendex [API Docs say they now have API Withdraw support](https://ascendex.github.io/ascendex-pro-api/#wallet-withdrawal), however, it's still not public.  One has to contact support@ascendex.com to obtain the docs and/or whatever else is required.  

Since they're already **CCXT Certified** perhaps you could contact their management, get the documentation, and add this functionality to ccxt.

I have emailed Ascendex support for the documentation (which they have yet to provide), but the functionality will still need to be added to CCXT to utilize it.

- OS: Win 8.1
- Programming Language version: Node v14.15.4
- CCXT version: 1.56.52

**Code:**
```
let ccxt = require('ccxt')
let exName = 'ascendex'
let exchange = new ccxt[exName]()
exchange.verbose
let type =  'withdraw' 

if (exchange.has[type]){
    console.log  (`Yes! ${exchange.name} has a ${type} function.`)
} else {
    console.log  (`No! ${exchange.name} has NO ${type} function.`)
}
```

**Output:**
```
No! AscendEX has NO withdraw function.
```

**Comment by drsavant-pub** [comment]
@kroitor 
I've been trying to track down the API docs for withdrawal, and I got this from Ascendex support on Telegram (@AscendEX_Official):

______________
AscendEX Support:
"At present, the API withdrawal permission is temporarily not open to ordinary users. If you are an institutional user, you can apply by email institution@ascendex.com"

Rex:
When will it be open to "ordinary users"?

AscendEX Support:
sorry ,we do not have the exactlr time
______________

It looks like it might be too early to add this feature.  I'll keep you informed on my progress.

**Comment by kroitor** [comment]
@drsavant-pub thx for your feedback!

**Comment by ttodua** [comment]
Seems it is still not available. As the functionality is not available in API, I think for now we can close the issue and re-open this issue, whenever it will be actually doable from API (if ever).

**Comment by drsavant-pub** [comment]
I agree with you.

I emailed them recently and it's still not available.

Rex

**Comment by ttodua** [comment]
@drsavant-pub thanks for input!
