### ISSUE TITLE
Cloudflare anti-bot bypass

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#1001]
It would be nice if ccxt could optionally wrap requests in https://github.com/Anorov/cloudflare-scrape to show cloudflare that we're a hard-working bot instead of a DDoS'er. It works quite nice, I've tested it without ccxt and am very happy with it.

Can imagine that this isn't very easy to implement cross-platform though.

**Comment by kroitor** [comment]
If you're using Python 2, you can override the `.session` and `.headers = {'Cookie': 'YOUR_CFSCRAPED_COOKIE'}` right away (already supported in ccxt). Let me know, if it helps.

**Comment by gaardiolor** [comment]
Ok great! I'll test it soon and reopen another issue if necessary.

**Comment by makelinux** [comment]
need to set **cf_clearance** and **User-Agent**, example:
```
import ccxt
e = ccxt.bit2c()
e.headers = { "Cookie": "cf_clearance=" + cf_clearance, "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0" }
e.fetch_ticker('BTC/NIS')
```

**Comment by love2kite** [comment]
how can the CF clearance can be done in Node.js?

**Comment by kroitor** [comment]
@love2kite https://github.com/codemanki/cloudscraper

**Comment by phips28** [comment]
Have you tried https://www.npmjs.com/package/cloudflare-scraper ?
