### ISSUE TITLE
[fetch_ohlcv] Question on closing price

### ISSUE THREAD

**Issue by NicolasWent** [ccxt/ccxt#10017]
Hello,

I have a question:

When I do fetch_ohlcv("BTC/USDT", "1d"), I get a timestamp for example 1588896000000. Which is Fri May 08 2020 00:00:00. The closing price correspond to the last price of the day which occurs at Fri May 08 2020 23:59:59 or Fri May 08 2020 00:00:00 ?

Because if that is Fri May 08 2020 23:59:59 why does the closing price of the day is not equal to the opening price of the next day?

**Comment by NicolasWent** [comment]
I think I got it:

When we work in days, the opening price is the first transaction of the day, and the closing price is the last. So it gets the price at May 08 2020 23:59:59 or even later but right before Sat 09 2020 00:00:00

Since the opening price is the first transaction of the day, then it can be slightly different from the last transaction of the last day.

Am I right, or I miss a concept? Because in my backtests, I was using the closing price for a certain hour, but it was looking in the future I guess...

**Comment by kroitor** [comment]
> When we work in days, the opening price is the first transaction of the day, and the closing price is the last. So it gets the price at May 08 2020 23:59:59 or even later but right before Sat 09 2020 00:00:00

Yes, that is correct.

> Since the opening price is the first transaction of the day, then it can be slightly different from the last transaction of the last day.

Yep, that is true.

> Am I right, or I miss a concept?

You got it right.
