### ISSUE TITLE
Kraken fetchOrder with ClientOrderId is not working

### ISSUE THREAD

**Issue by robbielitebit** [ccxt/ccxt#10021]
The ccxt implementation currently is:

```js
        let query = params;
        if (clientOrderId !== undefined) {
            request['userref'] = clientOrderId;
            query = this.omit (params, [ 'userref', 'clientOrderId' ]);
        } else {
            request['txid'] = id;
        }
```

But Kraken requires a txid even with an `userref` https://docs.kraken.com/rest/#operation/getOrdersInfo

**Comment by ungaratto93** [comment]
Hi,

On https://github.com/ccxt/ccxt/blob/master/js/kraken.js#L1217 has a comment speaking about fetch orders by id.

And on the kraken docs, for requests order they are pass as argument on request nonce, txid and trades

```
resp = kraken_request('/0/private/QueryOrders', {
    "nonce": str(int(1000*time.time())),
    "txid": "OBCMZD-JIEE7-77TH3F,OMMDB2-FSB6Z-7W3HPO",
    "trades": True
}, api_key, api_sec)
```

**Comment by robbielitebit** [comment]
Hi,

Checked the Kraken docs and you can fetch open/closed order by `userref`. Created a new PR https://github.com/ccxt/ccxt/pull/10030

But still with `QueryOrders` a txid is required, so that ccxt implementation won't work.

**Comment by kroitor** [comment]
@robbielitebit thank you very much! Merged it!
