### ISSUE TITLE
Delisted market trades are breaking for Poloniex

### ISSUE THREAD

**Issue by 1hakr** [ccxt/ccxt#1002]
Delisted market Trades are breaking for Poliniex. So the reason seems SJCX has been delisted and i happen to have a trade for it.

- OS: OSX
- Programming Language: JavaScript
- CCXT version: 1.10.503
- Exchange:Poloniex
- Method:fetchMyTrades

```
  var exchangeClient = new ccxt["poloniex"]({
    'apiKey': apiKey,
    'secret': secret,
    enableRateLimit: true,
    verbose: false,
    timeout: 30000
  });

await exchangeClient.fetchMyTrades(null, 1); // passing empty doesnt return any result in my case so giving a since value
```

```
TypeError: Cannot read property 'symbol' of undefined
```

The is the line https://github.com/ccxt/ccxt/blob/master/js/poloniex.js#L444 .

**Comment by kroitor** [comment]
This is fixed in v. 1.10.519. Thx!

**Comment by 1hakr** [comment]
👍
