### ISSUE TITLE
ccxt use fetch or request is the problem?

### ISSUE THREAD

**Issue by Smilestate** [ccxt/ccxt#10049]
When I use new ccxt.binance().request, the specific usage is as follows: 
```javascript
exchange.request(`order`, "fapiPrivate", "get", {orderId,symbol}, "", "")
Error: Request with GET/HEAD method cannot have body.
```
the result is out of As expected, Request with GET/HEAD method cannot have body.

When I use fetch to directly call the Huobi official interface, the signature verification fails, 403.
for eg：
```javascript
exchange.fetch("https://api.huobi.pro/v2/account/transfer", "post", {}, {
    from,
    to,
    "amount": amount,
    "currency": currency,
    "margin-account": marginAccount
})
Error: 403
```
Please check it out, maybe I am using the wrong way. Please provide an example, let me learn from it. Finally, thank you very much for answering my question.

**Comment by frosty00** [comment]
https://ccxt.readthedocs.io/en/latest/manual.html#implicit-api

**Comment by Smilestate** [comment]
> https://ccxt.readthedocs.io/en/latest/manual.html#implicit-api

I don't think you can solve my problem.

**Comment by Smilestate** [comment]
Because there is no mention of the use of fetch and request in the document, it gives me a headache!

**Comment by Matoran** [comment]
Why do you want to use fetch or request ? Implicit api is easier to use

```js
this.v2PrivatePostAccountTransfer({
    from,
    to,
    "amount": amount,
    "currency": currency,
    "margin-account": marginAccount
})
```

**Comment by ttodua** [comment]
I think @Matoran's answer is the answer we could have answered. Users don't ever need (unless very very rare cases). Implicit API is the best way to use. @frosty00 advised you correctly, but probably you  might have not read through the examples/implementations.  To get more success in your goals, I do advise to read & find out what is the implicit API in ccxt. 
as @Matoran answered, that is the easiest way to achieve what you wanted. 
Feel free to re-open issue  if you have something other issue.
