### ISSUE TITLE
[Kraken] Missing Orders

### ISSUE THREAD

**Issue by ong4mes** [ccxt/ccxt#10048]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:Windows 10
- Programming Language version:Node
- CCXT version:1.56.86

```
export async function createOrdersFromExchange(
	ccxt: kraken | undefined,
	userId: string,
) {
	if (ccxt === undefined) return;
	let since = ccxt.parse8601('2021-07-01T00:00:00Z');
	let allOrders: Order[] = [];
	let now = ccxt.milliseconds();

	while (since < now) {
		try {
			console.log('Fetching', 'since', ccxt.iso8601(since));
			const orders = await ccxt.fetchClosedOrders(undefined, since);
			console.log('Fetched', orders.length, 'orders, orders[0]');

			allOrders = allOrders.concat(orders);

			if (orders.length) {
				const lastOrder = orders[orders.length - 1];
				since = lastOrder['timestamp'] + 1;
			} else {
				break; // no more orders left for this symbol, move to next one
			}
		} catch (e) {
			console.log(e);
		}
	}
```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

When using any of the functions fetchClosedOrder or fetchMyTrades with kraken I´m missing some orders. F.eg I have some orders on 13,14 and 15 of August but I only get them from 22 August and up. 
Am I missing something?

**Comment by kroitor** [comment]
This could explain it: https://support.kraken.com/hc/en-us/articles/360001185486-How-to-view-your-older-account-history

Very few exchanges will actually store the entire history of orders from the beginning of time.
You can fetch the alternative ledger history from Kraken with fetchLedger.
Also, I would suggest reaching out to Kraken's tech support for a confirmation of the above limitations on the API.
Let us know if that does not help.

**Comment by imaxiking** [comment]
Strangely I get an even later first order with fetchLedger. But I contacted kraken support

**Comment by kroitor** [comment]
@imaxiking we would appreciate if you could report back here when you hear from them.
