### ISSUE TITLE
API missing from Huobi documentation!

### ISSUE THREAD

**Issue by Smilestate** [ccxt/ccxt#10043]
In the latest version of ccxt, api--v2private--post--account/transfer is commented out in huobi.js. How can I transfer currency assets to usdt perpetual contract without using this api? ?
So why comment out the api?
Huobi official document usdt standard perpetual contract exists https://api.huobi.pro/v2/account/transfer!
Can I support this api in the follow-up?

**Comment by Smilestate** [comment]
How do you sign when you request the exchange's api? This is convenient for me to directly use your signature method to directly request the exchange's api! Thank you very much for your offer.

**Comment by kroitor** [comment]
@Smilestate 

Huobi's v2 swap/futures endpoints are not supported yet, we are working on adding those right now.

> How do you sign when you request the exchange's api? This is convenient for me to directly use your signature method to directly request the exchange's api! Thank you very much for your offer.

You can use the `fetch()` method to issue a v2-specific call.

- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L528
