### ISSUE TITLE
Bitmex rate limit fetch_order_book

### ISSUE THREAD

**Issue by ShieldTrade** [ccxt/ccxt#10045]
Hi @Kroitor,

- CCXT pro latest version ( the subscription expired last week, I reached your support when the subscription was still valid but I 
did not get any answer. does not matter. When You read my mail I was probably already expired)
- Python 3.9
- Exchange: Bitmex
- Method: exchange.fetch_order_book

from https://www.bitmex.com/app/wsAPI#Rate-Limits 
"BitMEX allows subscribing to real-time data. This access is not rate-limited once connected and is the best way to get the most up-to-date data to your programs."

I get this error after 30 updates
ccxt.base.errors.DDoSProtection: bitmex {"error":{"message":"Rate limit exceeded, retry in 2 seconds.","name":"RateLimitError"}}

As far as I understand there should be no rate limit using websocket.
I read [5565](https://github.com/ccxt/ccxt/issues/5565) but it s not related to websocket book streaming as far as I understand

I tried the same code with kraken and It works fine. no error

I also tried on bitmex testnet with authentication. In this case enable rate limit true or false does not change the outcome. I always get 2 sec delay and obviously no error. I can provide you with the code in case.

Can You please tell me if I am doing something wrong?

I am running this code:
  
import asyncio
import ccxtpro
import random
import numpy
import copy
import time
print("Fast")

class GetBook():
        
    def __init__(self, simbol):
        #super().__init__(value=0)
        self.__stopped = False
        self.simbol = simbol
       
    async def connect(self):
        limit = 10
        since = None
        counter = 0 
        print("async_Connect")
        self.exchangeBitmex = ccxtpro.bitmex({'enableRateLimit': False})
        while not self.__stopped:
            #  using real time mode
            counter = counter + 1                                   
            Start = get_epoch_ms()            
            ##     GET OrderBook Bitmex
            orderbookBitmex = await self.exchangeBitmex.fetch_order_book(self.simbol, limit)                
            Finish = get_epoch_ms()
            print("counter :", counter, " Total Mill: ", Finish-Start)                                                 
    async def disconnect(self):
        self.exchange.close()
        self.__stopped = True
     def __init__(self, simbol):
        self.__stopped = False
        self.simbol = simbol
         
def get_epoch_ms():
    return int(time.time() * 1000.0)
      
async def main():
    p1 = GetBook("BTC/EUR")
    await p1.connect()
asyncio.run(main())

**Comment by kroitor** [comment]
@ShieldTrade you're violating this rule by creating the exchange instance over and over instead of reusing it:

- https://ccxt.readthedocs.io/en/latest/manual.html#notes-on-rate-limiter

Try this:

```
# -*- coding: utf-8 -*-

from asyncio import get_event_loop
import ccxtpro


print('CCXT Pro Version:', ccxtpro.__version__)


async def main():
    exchange = ccxtpro.bitmex()
    symbol = 'BTC/EUR'
    limit = 10
    markets = await exchange.load_markets()
    while True:
        try:
            orderbook = await exchange.fetch_order_book(symbol, limit)
            timestamp = exchange.milliseconds()
            print(exchange.iso8601(timestamp), exchange.id, symbol, orderbook['asks'][0], orderbook['bids'][0])
        except Exception as e:
            print(type(e).__name__, str(e))
    await exchange.close()

loop = get_event_loop()
loop.run_until_complete(main())
```

Let us know if that does not answer your question.

**Comment by ShieldTrade** [comment]
I tried this code and I get 2 sec delay

CCXT Pro Version: 0.8.13
2021-09-23T15:31:19.710Z bitmex BTC/EUR [37406.0, 100.0] [37337.0, 7600.0]
2021-09-23T15:31:21.769Z bitmex BTC/EUR [37393.0, 100.0] [37337.0, 13000.0]
2021-09-23T15:31:23.815Z bitmex BTC/EUR [37393.0, 100.0] [37337.0, 13000.0]

**Comment by kroitor** [comment]
@ShieldTrade try this one:

```Python
# -*- coding: utf-8 -*-

from asyncio import get_event_loop
import ccxtpro


print('CCXT Pro Version:', ccxtpro.__version__)


async def main():
    exchange = ccxtpro.bitmex()
    symbol = 'BTC/EUR'
    markets = await exchange.load_markets()
    #  exchange.verbose = True
    while True:
        try:
            orderbook = await exchange.watch_order_book(symbol)
            timestamp = exchange.milliseconds()
            print(exchange.iso8601(timestamp), exchange.id, symbol, orderbook['asks'][0], orderbook['bids'][0])
        except Exception as e:
            print(type(e).__name__, str(e))
    await exchange.close()

loop = get_event_loop()
loop.run_until_complete(main())
```

**Comment by ShieldTrade** [comment]
I get the verbose answer but it s still 2 sec delayed

**Comment by kroitor** [comment]
@ShieldTrade only the first request is delayed, and the reason is covered in the Manual here: 

- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
- https://ccxt.readthedocs.io/en/latest/manual.html#notes-on-rate-limiter

**Comment by ShieldTrade** [comment]
You are right. I was still using the fetch_order_book command. you changed it to watch_order_book.

I have to study your answer but **now I get the real time bitmex book as expected.**
 
I am still confused on when to use the different above command. 
Can you tell me where I can find some info about fetch_order_book and watch_order_book difference?
I think I will have the same result for the testnet. I will try tomorrow and i will let you know. Please let the question open until tomorrow.

Thank you . the answer was as fast as superman can be :-)

**Comment by kroitor** [comment]
@ShieldTrade `fetch_order_book` is a RESTful API (not a WebSocket API), while `watch_order_book` is a WebSocket API (and works faster in general). The difference is covered here:

- https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual#prerequisites
