### ISSUE TITLE
Error: binanceus {"code":-4019,"msg":"The current currency is not open for withdrawal"} with binance withdraw

### ISSUE THREAD

**Issue by soumyadeeproy12** [ccxt/ccxt#10047]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: MacOs 10.13.6
- Programming Language version: JS
- CCXT version: 1.56.86

Withdrawal with binanceus throwing this error 
```

    let exchange = new ccxt.binanceus  ({
        "apiKey": "my api key",
        "secret": "my secret key",
        "enableRateLimit": true,
        'options': {
            'defaultType': 'spot',
        },

    })

    
        // withdraw
  let withdraw = await exchange.withdraw ('USDC', 40, 'my metamask wallet', tag = undefined, {"name": "BEP20" ,'network': 'BSC'})

        // // output the result
  ///log (exchange.name.green, 'withdraw', withdraw)
        ///

    } 

}) ()```

```
Error: binanceus {"code":-4019,"msg":"The current currency is not open for withdrawal"}
```

**Comment by kroitor** [comment]
@soumyadeeproy12 do you have withdrawal address whitelisting enabled? Make sure that your whitelisted addresses correspond to the currencies and networks selected.

> {"code":-4019,"msg":"The current currency is not open for withdrawal"}

This message is coming from Binance directly. If the above does not help I would suggest asking their tech support or in this Binance API group: https://t.me/binance_api_english
