### ISSUE TITLE
There is a bug in Okex Fetch_position()

### ISSUE THREAD

**Issue by Ali-moradi-dev** [ccxt/ccxt#10051]
- OS: Ubuntu 20.04.2 LTS
- Programming Language version: Python 3.9
- CCXT version: 1.55.9

```
data = exchange.fetch_position(symbol)
```
in  fetch_position() , this line has a problem 

```
data = [ ]
return self.parse_position(self.safe_value(data, 0))

```
I face this error
```
Traceback (most recent call last):
  File "/snap/pycharm-professional/256/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/ali/migrate/new_crypto_connector/venv/lib/python3.8/site-packages/ccxt/okex.py", line 2569, in parse_position
    if market['inverse']:
KeyError: 'inverse'
```

it happen when data = [ ] it means we don't have any open position on okex

**Comment by kroitor** [comment]
@Ali-moradi-dev hi! Please, paste your request+response with verbose mode enabled:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by Ali-moradi-dev** [comment]
hi @kroitor,

my request :

**Comment by kroitor** [comment]
@Ali-moradi-dev we would suggest returning an `undefined` response from there if OKEX replies with an empty response, what do you say?

**Comment by Ali-moradi-dev** [comment]
@kroitor what do you mean `undefined` response? give me a sample

**Comment by kroitor** [comment]
@Ali-moradi-dev i mean `None` in Python:

```Python
symbol = 'XLM-USDT-SWAP'
data = exchange.fetch_position(symbol)
if data is None:
    print('No', symbol, 'position found')
```
