### ISSUE TITLE
Coinex historical data download

### ISSUE THREAD

**Issue by mablue** [ccxt/ccxt#10055]
Any help for that?
https://github.com/freqtrade/freqtrade/issues/5610#issuecomment-926808632

**Comment by xmatthias** [comment]
I think i was clear in that issue ... so i don't understand what you try to accomplish with this issue.
open an issue with ccxt _once the API of coinex supports this_.

Ccxt will not be able to invent historic data their API is not providing.

**Comment by kroitor** [comment]
@mablue the CoinEx's API does not support historical klines: https://github.com/coinexcom/coinex_exchange_api/wiki/024kline

Hope that answers your question.

**Comment by mablue** [comment]
> I think i was clear in that issue ... so i don't understand what you try to accomplish with this issue.
> open an issue with ccxt _once the API of coinex supports this_.
> 
> Ccxt will not be able to invent historic data their API is not providing.

Yes i tried to find if other way is possible. but yes if there is no the possibility in api than no one can do anything...thanks and sorry for my Unreasonable issue

**Comment by mablue** [comment]
> @mablue the CoinEx's API does not support historical klines: https://github.com/coinexcom/coinex_exchange_api/wiki/024kline
> 
> Hope that answers your question.

Ok Thanks for fast support.i need to talk with coinex first

**Comment by Cinorid** [comment]
they support time-based data with this format:
[coinex_exchange_api issues](https://github.com/coinexcom/coinex_exchange_api/issues/72#issuecomment-922367592)

**Comment by mablue** [comment]
khob alan daghighan ba kodum sarafi mese binance rahat mituni freqtrade kar koni dowdowsh?
manzooram ba chize iran bud az dakhele iran

**Comment by Cinorid** [comment]
@mablue 
Vala man taze kar ba freqtrade ro shroo kardam va hanooz sarafi dorost hesabi ke api support kone peyda nakardam. Vali goftam shaiad ba in format dade beshe ye harekati zad ya inke khodam ino fix konam baad pr bezanam.

**Comment by mablue** [comment]
Thank you come to our page in telegram we need programmers like you on our projects:
https://t.me/addlist/KYBnlh_rCCljNTVk
