### ISSUE TITLE
Should I enable rate limit if I use only watch_ticker method?

### ISSUE THREAD

**Issue by nzahar** [ccxt/ccxt#10058]
Hello!

As far as I understand, there are no requests to the exchange if I use only the watch_ticker method. So there is no need to enable the rate limit, am I correct?

**Comment by kroitor** [comment]
@nzahar hi! Yes, that is correct, although, the rate limiting also takes place not only between the HTTP requests, but also between the WS subscription requests and WS connections. If your connection is lengthy in time and stable (you don't reconnect over and over) that should be fine. Other aspects of rate-limiting are explained here: https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter. The built-in rate limiter is now enabled by default. You can switch it off via the constructor params or later after instantiation. Hope that answers your question. Let us know if not.
