### ISSUE TITLE
How to create order with BTC instead of Contracts in Binance COIN-M ?

### ISSUE THREAD

**Issue by SreekanthAvala** [ccxt/ccxt#10066]
Hi ,
I would l like to create order with my available BTC
let say if i have 3 BTC in my account, How can i create limit order with 3 BTC instead of  contracts ( Binance Delivery Type -COIN_M ) ?

**Comment by kroitor** [comment]
Binance COIN-margined futures and perpetuals API does not support that, you should specify the amount of contracts.

- https://binance-docs.github.io/apidocs/delivery/en/#new-order-trade

Let us know if that does not answer your question.
