### ISSUE TITLE
The result of function amount_to_pricision is not as expected?

### ISSUE THREAD

**Issue by wkamer** [ccxt/ccxt#10065]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: MacOS
- Programming Language version: Python 3.9.2
- CCXT version: 1.57.3

```
exchange = ccxt.binance({
    'apiKey': api_key,
    'secret': secret_key,
})

markets = exchange.load_markets()

# Symbol BTC/USDT
quote_asset_price = 27777.78 # USDT
quote_asset_amount = 10 # USDT
# Calculate base asset amount
print(quote_asset_amount / quote_asset_price) # =0.0003599999712000023
# Get precision amount
base_asset_amount = exchange.amount_to_precision("BTC/USDT", quote_asset_amount / quote_asset_price)
print(base_asset_amount) # =0.00035 -> Expected 0.00036
```
Is the default behaviour of the function to TRUNCATE? If so, how to set is to ROUND? As far as I can see is the documentation only about decimal_to_precision.

**Comment by ttodua** [comment]
Before sending the amount/price as parameter, you will need to use `decimal_to_precision` (as described [here](https://github.com/ccxt/ccxt/wiki/Manual#formatting-to-precision))
Let us know if further issues.
