### ISSUE TITLE
Binance OCO order for margin?

### ISSUE THREAD

**Issue by Utha-Tymbrimi** [ccxt/ccxt#10078]
Hi,

Does anyone know the correct syntax for posting an OCO cross-margin order on Binance?

If I attempt the following with sufficient BTC in my cross-margin account:

    result = exchange.private_post_order_oco({
        'symbol': 'BTCUSDT',
        'side': 'sell',
        'quantity': '0.0003',
        'price': '45000',
        'stopPrice': '40000',
        'stopLimitPrice': '39000',
        'stopLimitTimeInForce': "GTC"
        })

I get:

ccxt.base.errors.InsufficientFunds: binance Account has insufficient balance for requested action.

For a normal stop-limit order, I can just add the "type": "margin" parameter, and the order will execute against the cross-margin account instead of spot, but this doesn't seem to be allowed for OCO orders.  Attempting this:

    result = exchange.private_post_order_oco({
        'symbol': 'BTCUSDT',
        'side': 'sell',
        'quantity': '0.0003',
        'price': '45000',
        'stopPrice': '40000',
        'stopLimitPrice': '39000',
        'stopLimitTimeInForce': "GTC",
        'type': 'margin'
        })

Yields this:

ccxt.base.errors.BadRequest: binance {"code":-1104,"msg":"Not all sent parameters were read; read '10' parameter(s) but was sent '11'."}

Any ideas?  OCO orders for cross-margin are definitely valid, I've successfully placed an identical order to the above on my cross-margin using the Binance website.

**Comment by Utha-Tymbrimi** [comment]
OK it looks like I need an Implicit API call to do this.  How should I format it?  The API call I'm trying to execute is (from the Binance API documentation):

POST /sapi/v1/margin/order/oco (HMAC SHA256)

As far as I can tell, it should be formatted like this:

result = exchange.sapi_post_margin_order_oco({
    'symbol': 'BTCUSDT',
    'side': 'sell',
    'quantity': '0.0003',
    'price': '45000',
    'stopPrice': '40000',
    'stopLimitPrice': '39000',
    'stopLimitTimeInForce': "GTC"
    })

But I get:

AttributeError: 'binance' object has no attribute 'sapi_post_margin_order_oco'

**Comment by kroitor** [comment]
@Utha-Tymbrimi make sure that your version of CCXT is up to date, sapi_post_margin_order_oco should work:

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance()
pprint([method for method in list(dir(exchange)) if 'oco' in method])
```

```
~/ccxt/python $ python3
Python 3.8.2 (default, Apr  8 2021, 23:19:18)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> from pprint import pprint
>>> print('CCXT Version:', ccxt.__version__)
CCXT Version: 1.57.13
>>> exchange = ccxt.binance()
>>> pprint([method for method in list(dir(exchange)) if 'oco' in method])
['private_post_order_oco', 'sapi_post_margin_order_oco']
```

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/blob/master/examples/py/binance-create-oco-order-with-implicit-methods.py

**Comment by Utha-Tymbrimi** [comment]
Dammit, of course!  I'm running this in a VM, freshly cloned from a template that hasn't been updated in months...

Yep, I was using 1.52

And of course Binance is undergoing maintenance, so now I have to wait a couple of hours to test it!

Forest for the trees... thanks kroitor, much appreciated!

**Comment by kroitor** [comment]
> And of course Binance is undergoing maintenance, so now I have to wait a couple of hours to test it!

Let us know if you don't get it working when they're back online.
