### ISSUE TITLE
Bitcoin.com rebranding to FMFW.io

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#10081]
https://support.bitcoin.com/en/articles/5556195-rebranding-faq

> Please note our API root URL will be changed on 29th September too (ONLY root URL, all commands and parameters will remain the same). For example, if you previously used: https://api.exchange.bitcoin.com/api/3/public/symbol/ETHBTC after the migration, you will have to use https://api.fmfw.io/api/3/public/symbol/ETHBTC instead.

**Comment by ndubel** [comment]
Should we rename this exchange in CCXT?

**Comment by kroitor** [comment]
@ndubel yep, i think so.

**Comment by ndubel** [comment]
https://github.com/ccxt/ccxt/pull/11256
