### ISSUE TITLE
FTX   default timeInForce is None, cannot set by users

### ISSUE THREAD

**Issue by gochendong** [ccxt/ccxt#10080]
'timeInForce': None,

Users should be able to set this manually.

**Comment by kroitor** [comment]
You are already able to set this and this is covered in the Manual: 

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
- https://docs.ftx.com/#place-order

```Python
exchange.create_order (symbol, type, side, amount, price, {'ioc': true})
```
