### ISSUE TITLE
Support fetchDepositAddress for Gemini

### ISSUE THREAD

**Issue by srisi** [ccxt/ccxt#10090]
Gemini on ccxt currently does not support `fetchDepositAddress`: https://github.com/ccxt/ccxt/blob/master/python/ccxt/gemini.py#L50

However, Gemini has an endpoint to fetch deposit addresses (`POST https://api.gemini.com/v1/addresses/:network`, https://docs.gemini.com/rest-api/#get-deposit-addresses) in addition to the endpoint to create deposit addresses.

Is it possible to either support `fetchDepositAddress` or add `v1/addresses/{currency}` to the gemini private post endpoints? I might try to create an MR from there, modeled after `create_deposit_address`.

**Comment by DoctorSlimm** [comment]
#10534
