### ISSUE TITLE
All exchanges.has['fetchTickers'] set to False ?

### ISSUE THREAD

**Issue by eanism** [ccxt/ccxt#10109]
Apologies for what is probably a dumb question. I'm just starting to get familiar with ccxt (amazing project btw, thank you) and when attempting to call the fetchTickers method, I notice that there don't appear to be any exchanges that support it (at least by default). Is this by design? Is there something that is intended to be overridden or modified? Looking through issues on the repo, there are no shortage of exchange-specific and general questions about fetchTickers, so I assume that either I am doing something wrong, or a very recent commit has caused this value to be set False for all exchanges. Sorry again for what may be a frivolous question, but any help would be very appreciated!

- OS: Ubuntu
- Programming Language version: Python 3.8.10
- CCXT version: 1.57.35

```
>>> import ccxt
>>> count = 0
>>> for exchange in ccxt.exchanges:
...  if eval(f'ccxt.{exchange}').has['fetchTicker']:
...   count += 1
...
>>> count
112
>>> count = 0
>>> for exchange in ccxt.exchanges:
...  if eval(f'ccxt.{exchange}').has['fetchTickers']:
...   count += 1
...
>>> count
0
>>>
```

**Comment by kroitor** [comment]
You are missing the exchange constructor call in your code.

Let us know if this does not answer your question:

```Python
import ccxt
count = 0
for exchange in ccxt.exchanges:
    if eval(f'ccxt.{exchange}()').has['fetchTicker']:
        count += 1

print(count)
```

```
~/ccxt/python $ python3
Python 3.8.2 (default, Apr  8 2021, 23:19:18)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> count = 0
>>> for exchange in ccxt.exchanges:
...     if eval(f'ccxt.{exchange}()').has['fetchTicker']:
...         count += 1
...
>>> print(count)
109
```

<img width="5306" alt="Screenshot 2021-10-03 at 14 13 09" src="https://user-images.githubusercontent.com/1294454/135751138-876997f6-dda4-44a4-9b30-523ec1a04520.png">
