### ISSUE TITLE
Poloniex - InvalidNonce error

### ISSUE THREAD

**Issue by LukasUlrych** [ccxt/ccxt#10107]
Hi,

my ccxt version is 1.57.34, My Python version is 3.9.5.

There is an issue with Poloniex nonce function. For some reason standard API calls (fetch_balance, fetch_open_orders etc .. ) return InvalidNonce error specifying that provided nonce is too small. Changing self.nonce function inside poloniex.py to return microseconds (instead of current milliseconds) solves the problem.

I am however not sure if that is an optimal solution. The official Poloniex API docs says that milliseconds should be used (but it clearly doesn't work).

**Comment by kroitor** [comment]
@LukasUlrych have you tried with a fresh new API keypair? Your nonce may be screwed if you have used this key with some other software before.

- https://github.com/ccxt/ccxt/wiki/Manual#authentication
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by kroitor** [comment]
Let us know if the above does not help.

**Comment by LukasUlrych** [comment]
Hi @kroitor, thanks for the advice, it did help.
