### ISSUE TITLE
kraken fetchTrades

### ISSUE THREAD

**Issue by BHruska** [ccxt/ccxt#10102]
I can't seem to get KRAKEN to return all my trades for a position.  The first trade was 10 months ago, and there are about 60 buys since.  So nowhere near the 1000 with page limitations I saw some comments about.  

Their app shows all of my trades, so I know the data exists.

Can't seem to get them all to be return  no matter what I attempt to pass in for the SINCE parameter, or none at all.

Frustrated with this one.  Any help appreciated!

- OS:  WIndows
- Programming Language version:  PYTHON
- CCXT version: CCXT

```
fetchMyTrades()
```

```

```

**Comment by BHruska** [comment]
Any sample code on how to get all Trades from Kraken?  What I've got works for all other exchanges.

**Comment by lmsvr** [comment]
That would be extremely helpful as I'm currently dealing with the same issue.  Thanks! 

Only getting 50 trades and can't seem to pull any history further back.  
I'm using PHP with CCXT v.1.60.66 installed via Composer on Linux

**Comment by ttodua** [comment]
the issue has been stale. as I checked the current codebase, the issue should have been fixed. 
if anyone has any problem, let us know
