### ISSUE TITLE
Cancel bulk order on bitmex

### ISSUE THREAD

**Issue by ShieldTrade** [ccxt/ccxt#10101]
- OS:Windows 10
- Programming Language version: Python 3.7
- CCXT version: CCXT version: CCXT Pro Version: 0.8.13

reading bitmex api:
Cancel order(s). Send multiple order IDs to cancel in bulk.

from CCXT:
the only private method supported for bitmex are:
privatePostOrder
privatePutOrder

if I want to accomplish a bulk cancel how can I add multiple IDs to 
cancel_order(self, id, symbol=None, params={})   ?

In [7086](https://github.com/ccxt/ccxt/issues/7086) you provide an example on how to Cancel Order based on clientOrderID parameter. but again you pass only 1 clientOrderID  I think I have to use parameters too but I am kind of lost.

can you please give me some advise and possibly provide a code snippet

Tx

**Comment by ShieldTrade** [comment]
Got it.  just make a list with your order Id 

for other learning as myself
if you have 2  open orders with: 

> Id 1 = 'afb58c10-595d-41ae-94c5-5e2703458375'
> Id 2 = 'ef2b4642-570d-4b3b-b9d0-3163ce4ef67c'

exchange = ccxtpro.bitmex
exchange.cancel_order(['afb58c10-595d-41ae-94c5-5e2703458375', 'ef2b4642-570d-4b3b-b9d0-3163ce4ef67c']) is a bulk cancel order

If Kroitor confirms the above we can consider this question closed.

**Comment by ShieldTrade** [comment]
Hi, 
I understand you are very busy upgrading this very good library but this question was opened 45 days ago.

I also understand bulk orders might not be used by most of ccxt clients. Nevertheless  bulk orders are essential if you want to keep your rare limit low. this is a CCXT problem, no websocket is involved. We are still in beta test and we have not upgraded our subscription to PRO as we did in the past.. .. would that make any difference? 

thankyou

**Comment by ShieldTrade** [comment]
[https://blog.bitmex.com/site_announcement/reminder-removal-of-bulk-order-rest-api-endpoints/](url)

Bulk order are dead on Bitmex and I have to rewrite a big deal of my code. shit happens.  :-) The question can be closed

thx anyway

**Comment by kroitor** [comment]
@ShieldTrade thanks for letting us know! Pardon for the delays with my replies, please, don't hesitate if anything.

**Comment by ShieldTrade** [comment]
jus in case you missed

[https://blog.bitmex.com/site_announcement/reminder-change-of-websocket-endpoint-by-1-november/](url)

**Comment by kroitor** [comment]
@ShieldTrade will get that handled shortly, thank you so much!
