### ISSUE TITLE
Is there a way to get a trade cost with fetchLedger?

### ISSUE THREAD

**Issue by steebchen** [ccxt/ccxt#10103]
It seems that fetching trades using `fetchLedger` (which is required for some exchanges) won't return cost information, just the amount. This is unfortunate as it seems there is no way to figure out at what cost the amount was bought or sold. Am I missing something?

Couldn't the `cost` field just be added to ledger results of `type: 'trade'` in addition to `amount`, as the exchanges usually return that information as well?

e.g. Coinbase returns this native info

![image](https://user-images.githubusercontent.com/5013932/135660768-ea01795a-0bbb-48c6-8647-19eb44fa2e48.png)

but there's no unified `cost` field:

![image](https://user-images.githubusercontent.com/5013932/135660793-777b1ae6-8370-447f-8973-6935ef7e2fad.png)

The same goes for other trade specific fields as well, such as symbol, order, side, etc.

I'd be happy to send some PRs for some exchanges to also return that information as I think that'd be valuable.

**Comment by steebchen** [comment]
I'd love to have this feature, and would be happy to send PRs to actually implement this for some exchanges. Would be great to get an approval for this feature before I start implementing this!

**Comment by ttodua** [comment]
@steebchen for sure, you are always welcome to make PR, and it will get implemented (unless some objective reasons)

**Comment by ttodua** [comment]
@steebchen 
I have to add , that you should be using `fetchMyTrades` to obtain detailed trade information, as `fetchLedger` is not best for that goal.
Let me know if you have submitted PR, so we can review it.
At this moment, I'll close this issue.
