### ISSUE TITLE
cancel bulk order using clOrdID on bitmex

### ISSUE THREAD

**Issue by ShieldTrade** [ccxt/ccxt#10112]
- OS:Windows 10
- Programming Language version: Python 3.7
- CCXT version: CCXT version: CCXT Pro Version: 0.8.13
- Exchange bitmex

reading bitmex [api](https://www.bitmex.com/api/explorer/#!/Order/Order_cancel):
Cancel order(s). Send multiple order IDs to cancel in bulk.
Implementation Notes
Either an orderID or a clOrdID must be provided.

In [7086 ](https://github.com/ccxt/ccxt/issues/7086)you provide an example on how to Cancel Order based on clientOrderID parameter but  you pass only 1 clientOrderID
I want to pass more then one clientOrderID.

assuming I have 2 orders on same instrument "XBTEUR" and clientOrderID are:
MyId1 = 'buyXX000000'
MyId2 = 'sellXX000000'

as in 7086
params = {'clientOrderId': MyId1 }
exchange.cancel_order(id, "XBTEUR", params)
works fine

I tried
params = [{"clientOrderId":'MyId1 }, {"clientOrderId": MyId2 }]
exchange.cancel_order(id, XBTEUR", params)

ValueError: dictionary update sequence element #0 has length 1; 2 is required

can you please give me some advise and possibly provide a code snippet

Tx

**Comment by ttodua** [comment]
comma-separated list of orderIds should work with Bitmex if I am not wrong:

`exchange.cancel_order( "a123.. , b123..",  "XBTEUR")`

or if you want through params:
`exchange.cancel_order( ..,  "XBTEUR", {"clientOrderId": [MyId1,MyId2].join(',') } )`

let us know if you have issues still.

**Comment by carlosmiei** [comment]
Hello @ShieldTrade , 

You can cancel multiple orders using the clientOrderId, doing something like this:
```Python
exchange = ccxt.bitmex({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
})
clientOrderid1 = "order0001"
clientOrderid2 = "order0002"
# cancel both orders at the same time
cancelboth = exchange.cancel_orders(None, None, {'clientOrderId': [clientOrderid1,clientOrderid2]})
print(cancelboth)
```
Please check out a complete example here: https://github.com/ccxt/ccxt/blob/master/examples/py/bitmex-cancel-orders.py#L30
