### ISSUE TITLE
Gate.io ratelimit seems to be wrongly applied

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#10111]
- OS: linux
- Programming Language version: python
- CCXT version: 1.57.3

something seems off with gateio's ratelimiting.

With the code below (rateLimit of 500ms), i'd expect ~2 calls per second - so the below code (doing 4 requests) should take roughly 2 seconds.

This code however runs for more than 2 minutes (i got bored by then and aborted ...).

```
import ccxt
exchange = ccxt.gateio({"enableRateLimit": True, "rateLimit": 500})
lm = exchange.load_markets()

-- Time starting from here - i used a different Jupyter sell with %%time ... 
for pair in range(4):
    _ = exchange.fetch_ohlcv('BTC/USDT', "5m", limit=500)
```

Running the same  code against binance, i get a response in roughly 2 seconds. 

``` python
import ccxt
exchange = ccxt.binance({"enableRateLimit": True, "rateLimit": 500})
lm = exchange.load_markets()

for pair in range(4):
    _ = exchange.fetch_ohlcv('BTC/USDT', "5m", limit=500)
```

Now i know that the limits above are "over the top" for gate.io (which can go down to 3ms) - but using a high enough value will expose this odd, misaligned behaviour (which honestly, from looking at the JS sources, i'm unable to grasp).

**Comment by kroitor** [comment]
@xmatthias we have started adding the burst support to the built-in rate limiter, which is why the rate limit for gate.io (and a few other exchanges) is defined as: https://github.com/ccxt/ccxt/blob/master/js/gateio.js#L15

**Comment by xmatthias** [comment]
@kroitor does this in term mean that the unit of `rateLimit` changed to "requests per second", instead of the "ms" that was used before?
I'm not agianst such a change - but i think this should use a different attribute ("rateLimitBurst"?) to avoid breaking existing behaviour...

**Comment by kroitor** [comment]
@xmatthias it is supposed to work in a non-breaking manner, investigating...

**Comment by kroitor** [comment]
Will fix this shortly.

**Comment by xmatthias** [comment]
Can confirm, new version fixes this :+1: Thanks a lot for the prompt response

**Comment by kroitor** [comment]
@xmatthias thx for reporting!

**Comment by frosty00** [comment]
Please revert this

**Comment by frosty00** [comment]
please test code before merging it also

**Comment by frosty00** [comment]
@xmatthias this is normal behaviour for exchanges with defined costs, now @kroitor has broken gateio

**Comment by xmatthias** [comment]
@frosty00 so inconsistent behaviour within ccxt is expected behaviour?

Which exchanges use which unit for rateLimit? Where is the documentation part for this?
please reopen this issue - as it's now no longer closed.

**Comment by frosty00** [comment]
@xmatthias basically we now have costs for the rateLimits, which means you cannot change the `rateLimit` property for exchanges which have this implemented such as binance, huobi, okex etc, since the rateLimit will not be applied directly, instead the cost * rateLimit will be applied which is very your script for gateio stalled.

I've made a PR to fix this issue

**Comment by frosty00** [comment]
the trouble is the @kroitor did a stupid fix, which wasn't a fix at all since he didn't test the code

**Comment by xmatthias** [comment]
The fix works for the provided sample, which is aligned to the documentation as far as i can see (which states that rateLimit is in ms).
It's intransparent which exchanges are using ms as unit, and which "something" else (which is not documented) at the moment.

**Comment by frosty00** [comment]
@xmatthias yeah I'm testing it and it seems to be working. I'm pretty sure when I wrote it before it was giving me DDoSProtection errors when using the public api with super fast ratelimits. Maybe they changed it...

**Comment by frosty00** [comment]
although there still remains the issue of letting users change the ratelimit while not breaking with the costs  which is why your original code breaks

```
import ccxt
exchange = ccxt.binance({"enableRateLimit": True, "rateLimit": 500})
lm = exchange.load_markets()

for pair in range(4):
    _ = exchange.fetch_ohlcv('BTC/USDT', "5m", limit=500)
```

currently at least this functionality is undefined if you change the rateLimit. i've submitted a PR to try to solve this

**Comment by xmatthias** [comment]
having accurate rateLimits defined by ccxt would be great, so the cost-based ratelimit will for sure be great (assuming set limits are accurate).

Previous rate-limits were sometimes too high (sometimes too low like for Kraken) - so setting them manually was our only option (and was also suggested in some older issues).

As mentioned above - if you introduce a new option (`rateLimitcosts`?) to define this, which is in a different unit (like "calls per second") might be a better option than overloading `rateLimit` with a now different unit - which becomes confusing, as the meaning differs per exchange.

**Comment by frosty00** [comment]
@xmatthias I've already fixed it in #10113 which basically says

* if the rateLimiter is defined by ccxt then apply the costs
* otherwise apply a constant rateLimit as defined by the user

unfortunately we didn't consider what would happen for the users who modified the rateLimit in their code when we added support for dynamic rateLimits

**Comment by kroitor** [comment]
@xmatthias we have discussed this within the team and, as was mentioned above, the rateLimit property still operates in terms of milliseconds and will behave very close to the way it worked before, as explained in the documented Manual. In other words, there is (there will be) no inconsistency in regard of that. Most of the exchanges in the current master are not directly affected by this change, even if you redefine the rateLimit and set it higher to a less efficient value than the default. There are 3 exchanges that may affected (apart from gate.io that is now fixed): OKEX, Bitmart and Btcturk, we will push a new revision shortly for those exchanges – that will should them back in line with the Manual. Thx for pointing it out!

**Comment by xmatthias** [comment]
Seeing the approach you're taking now (#10113 , ...) seems to be a good way :+1: 

I must admit, i've completely missed the change on how you handle rateLimits now - it seems to work just great (currently testing for binance, but i assume it'll work similarily great for other pairs).

**Comment by kroitor** [comment]
@xmatthias thx for your feedback!

**Comment by xmatthias** [comment]
@kroitor @frosty00 maybe a stupid question - but has the rate-limit for gate.io been rolled back properly? 

without setting a ratelimit myself, i'm currently getting torched by it after about 1-2 seconds ...

**Comment by frosty00** [comment]
> @kroitor @frosty00 maybe a stupid question - but has the rate-limit for gate.io been rolled back properly?
> 
> without setting a ratelimit myself, i'm currently getting torched by it after about 1-2 seconds ...

it might be broken, cause i've made some changes that were then re-editted out

**Comment by frosty00** [comment]
the public endpoints are too fast i think

**Comment by frosty00** [comment]
> without setting a ratelimit myself, i'm currently getting torched by it after about 1-2 seconds ...

that's strange, what code are you using to replicate it

**Comment by xmatthias** [comment]
You're right - i was misled - i'll open a new issue for that - as it's not rate-limit related.
