### ISSUE TITLE
I think a description of the bounce delivery stop loss should be added.

### ISSUE THREAD

**Issue by givinkwon** [ccxt/ccxt#10120]
binance는 futures 선물이 delivery / futures로 분류되어 있다. 그러나, 코드 주석에는 futures에 대한 내용만 설명되어 있다. delivery에 속한 xxx/coin (ex) EOS/USD)는 STOP/LOSS 명령을 걸 때 에러 메세지를 결과로 내보냅니다

![image](https://user-images.githubusercontent.com/22470975/135804409-654066c9-8dee-46f1-b5cb-5bc77390a5f1.png)

**Comment by givinkwon** [comment]
If you look at the binance documentation, the order_type of coin market classified as delivery is
LIMIT
MARKET
STOP
STOP_MARKET
TAKE_PROFIT
TAKE_PROFIT_MARKET
TRAILING_STOP_MARKET
It seems that.

**Comment by givinkwon** [comment]
I used this codes

params = {'stopPrice' : round(float(price) * 1.2, 3)}
    order = binance.createOrder('EOS/USD', 'TAKE_PROFIT', 'sell', 2, round(float(price) * 1.1, 3), params)

**Comment by kroitor** [comment]
@givinkwon you should upgrade to the most recent version of CCXT 1.57.40+ and use `ccxt.binancecoinm()` instead of `ccxt.binance()`. Also, you are missing the price argument for the create_order call.

- https://github.com/ccxt/ccxt/blob/master/examples/py/binance-coin-margined-take-profit.py

```Python
# -*- coding: utf-8 -*-

from pprint import pprint
import ccxt


print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binancecoinm({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

markets = exchange.load_markets()

exchange.verbose = True  # uncomment for debugging purposes if necessary

symbol = 'EOS/USD'
order_type = 'TAKE_PROFIT'
side = 'sell'
amount = YOUR_AMOUNT_HERE  # <---------- edit for your values
price = YOUR_LIMIT_PRICE_HERE  # <------ edit for your values
stopPrice = 25000
params = {'stopPrice': stopPrice}

try:
    order = exchange.create_order(symbol, order_type, side, amount, price, params)
    print(order)
except Exception as e:
    print(type(e).__name__, str(e))

```

Let us know if that does not answer your question.
