### ISSUE TITLE
deprecated endpoint: transition from Wapi to Sapi

### ISSUE THREAD

**Issue by leebh12** [ccxt/ccxt#10121]
- OS:Windows 10 Pro
- Programming Language version: Python 3.8
- CCXT version: 1.46.35

ExchangeNotAvailable: binance POST https://api.binance.com/wapi/v3/withdraw.html?timestamp=1633328084000&recvWindow=5000&asset=BTT&address=TDYciuoDpJ8M6bh1TmVWqehG2WRcFYda4Y&amount=457943.832&name=TDYciuoDpJ8M6bh1TmVW&addressTag=&signature=ca2a15ab3cbbb7b96d97b6df0a69be0422c86e3e9c3f37ec0f65b109903af804 503 This endpoint has been deprecated, please integrate with “POST@/sapi/v1/capital/withdraw/apply”. See details in the announcement: https://www.binance.com/en/support/announcement/f45dde7da58b473aa885349946bed269

As of August 1st, Wapi is deprecated.
I've been using ccxt's withdraw function before, so using that function now produces the above message. I need to change it to sapi. What can I do to switch to sapi?

**Comment by kroitor** [comment]
Please, upgrade to the most recent version 1.57.40+ and use the unified withdraw method: 

- https://github.com/ccxt/ccxt/wiki/Manual#withdraw
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Let us know if the above does not answer your question.
