### ISSUE TITLE
Bithumb create_order contains typo, doesn't work

### ISSUE THREAD

**Issue by Philx0** [ccxt/ccxt#1012]
- OS:Win
- Programming Language:php/all
- CCXT version:1.10.528
- Exchange:Bithumb
- Method:create_order 

There's a typo inside bithumb.php, create_order still doesn't work after fixing this.

```
//bithumb.php:create_order:
$method .= 'Market' . $this->capitalise ($side);  //should be "capitalize "

//output after fixing typo, following returns: "privatePostMarketSell not found"
$bithumb     = new \ccxt\bithumb    (array (
    'apiKey' => 'xxx',
    'secret' => 'xxx',
    'verbose' => true
));
$bithumb_markets = $bithumb->load_markets ();

$bithumb->create_order ('XRP/KRW', 'market', 'sell', 10);
```
I suppose there's something wrong with the construction of the method name in this method.
The request method works just fine.

**Comment by Philx0** [comment]
Why was this closed? "privatePostMarketSell not found" is still returned after fixing the typo.

**Comment by kroitor** [comment]
@Philx0 GitHub closes them automatically, if there's a word "fix" in the commit message. No worries, the privatePostMarketSell will be fixed as well.
