### ISSUE TITLE
HitBTC "Price is not a valid number"

### ISSUE THREAD

**Issue by articobandurini** [ccxt/ccxt#10131]
I'm trying to create a Stop Limit order with HitBTC and get this error for some reason: "Price is not a valid number".

- OS: OSX 11.6
- Programming Language version: Node.js v14.15.3
- CCXT version: 1.54.72

First of all, this is my amount, price and params object that are passed to createOrder call:

```
amount = 0.00078
price = 0.06
params = { time_in_force: 'GTC', stop_price: '0.059', type: 'stopLimit' }
```

Verbose output:

```
fetch:
 hitbtc POST https://api.hitbtc.com/api/2/order 
Request:
 {
  Authorization: 'Basic ...xxx...',
  'Content-Type': 'application/json'
} 
 {"clientOrderId":"839d52f8d4cc4506b15f1a1fc1638012","symbol":"ETHBTC","side":"buy","quantity":"0.0007","type":"stopLimit","timeInForce":"FOK","time_in_force":"GTC","stop_price":"0.059"} 

handleRestResponse:
 hitbtc POST https://api.hitbtc.com/api/2/order 400 Bad Request 
Response:
 {
  Connection: 'keep-alive',
  'Content-Length': '60',
  'Content-Type': 'application/json; charset=UTF-8',
  Date: 'Tue, 05 Oct 2021 02:39:09 GMT',
  Server: 'nginx'
} 
 {"error":{"code":2020,"message":"Price not a valid number"}} 
```

I see that there is no `price` parameter in the request, it's missing and I guess this causes the issue.

Apart from that I've noticed that there is an extra param included into the request: `"timeInForce":"FOK"`
However according to HitBTC docs it should look like `time_in_force`, as I set in params.

**Comment by kroitor** [comment]
@articobandurini does this snippet work for you (with `type` = `'limit'`)?

```Python
amount = 0.00078
price = 0.06
params = { time_in_force: 'GTC', stop_price: '0.059', type: 'stopLimit' }
order = exchange.create_order(symbol, 'limit', 'buy', amount, price, params);
```
```

**Comment by kroitor** [comment]
> Apart from that I've noticed that there is an extra param included into the request: "timeInForce":"FOK"
> However according to HitBTC docs it should look like time_in_force, as I set in params.

HitBTC has upgraded the API to v3. the integration in CCXT is for v2.
We will add the support for HitBTC v3 as soon as we can.

**Comment by articobandurini** [comment]
When I set type to `limit`, I get the following:

```
fetch:
 hitbtc POST https://api.hitbtc.com/api/2/order 
Request:
 {
  Authorization: 'Basic TnZZeU9XY2RYTHl3MWxpN0tvdlZxVU1ZUmY0ZVNJTEE6MTVmbHo4cFJhdHJha0R3eEQ2Qm10SHpkdm5obmViX3c=',
  'Content-Type': 'application/json'
} 
 {"clientOrderId":"483dc4e3630642eeb72e617ea704b947","symbol":"ETHBTC","side":"buy","quantity":"0.0007","type":"stopLimit","price":"0.06","time_in_force":"GTC","stop_price":"0.059"} 

handleRestResponse:
 hitbtc POST https://api.hitbtc.com/api/2/order 400 Bad Request 
Response:
 {
  Connection: 'keep-alive',
  'Content-Length': '95',
  'Content-Type': 'application/json; charset=UTF-8',
  Date: 'Tue, 05 Oct 2021 03:03:44 GMT',
  Server: 'nginx'
} 
 {"error":{"code":10001,"message":"Validation error","description":"\"stopPrice\" is required"}} 
```

Params seem to be passed ccorrectly, but their names are for v2 probably...
What can be done right now to make it work before you push an upgrade?

**Comment by kroitor** [comment]
> What can be done right now to make it work before you push an upgrade?

Replace your params with camelCase:

```Python
amount = 0.00078
price = 0.06
params = { timeInForce: 'GTC', stopPrice: '0.059', type: 'stopLimit' }
order = await exchange.createOrder(symbol, 'limit', 'buy', amount, price, params);
```

Let us know if it works for you.

**Comment by articobandurini** [comment]
The thing is that I have to retain original order type, so I try to replace it with a `type: limit` property inside params, but it doesn't work. Is that correct behaviour?

**Comment by kroitor** [comment]
@articobandurini it should be the other way around, the `type` argument must be set to `limit` and the `type` param must be `stopLimit`.

**Comment by articobandurini** [comment]
Yes it works! Thank you for such a quick help!
Could you please send a note to this thread when you push update for v3.

**Comment by kroitor** [comment]
@articobandurini yes, will do, as soon as it arrives.
