### ISSUE TITLE
reduce_fees_by_currency() missing 1 required positional argument: 'string'

### ISSUE THREAD

**Issue by yohaieival** [ccxt/ccxt#10146]
Hello,
When I use the function:

     exchange.create_limit_sell_order (symbol, amount = coin_balance, price = price)

In Gate.io and OKex I get the following error message:

"reduce_fees_by_currency () missing 1 required positional argument: 'string' "

**Comment by frosty00** [comment]
thanks for reporting, i've uploaded the fix

**Comment by frosty00** [comment]
it should arrive within an hour or so

**Comment by kroitor** [comment]
This bug is fixed in CCXT 1.57.57+ (the new build will arrive in 20 minutes). Thanks for reporting!

**Comment by Shuhari-Zap** [comment]
Thanks for reporting. Must have slipped in just recently? Had the same issue suddenly in production. I quickly worked around it by setting "reduceFees": False when I create my Exchange object. I tried looking for the parameter in the documentation, but could not find anything. 
@kroitor can you let us know what this setting actually does? Thanks!
