### ISSUE TITLE
Historical Klines CCXT Binance

### ISSUE THREAD

**Issue by lsheynova** [ccxt/ccxt#10148]
- OS: Windows 10
- Programming Language version: Python
- CCXT version: 1.57.43

In the Binanace API I can use the function 
``` klines = client.get_historical_klines("ETHBTC", Client.KLINE_INTERVAL_30MINUTE, "1 Dec, 2017", "1 Jan, 2018")```
to get klines from a specific time frame, so how would I implement this in CCXT.

This is my code, it can currently fetch 500 candles, but I have no way of setting which time frame the data comes in
```
def getdata(symbol, timeframe):

    exchange_id = 'binance'
    exchange_class = getattr(ccxt, exchange_id)
    exchange = exchange_class({
        'apiKey': config.BINANCE_APIKEY,
        'secret': config.BINANCE_APISECRET,
        'enableRateLimit': True,
    })

    candles = exchange.fetch_ohlcv(symbol, timeframe)
    return candles

print(getdata('BTC/USDT', '1d'))
```

**Comment by kroitor** [comment]
Let us know if this does not answer your question:

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance()
ohlcvs = exchange.fetch_ohlcv('BTC/USDT', '1d')
for ohlcv in ohlcvs:
    print(exchange.iso8601(ohlcv[0]), ohlcv[1:])
```

```
~/ccxt/python $ python3
Python 3.8.2 (default, Apr  8 2021, 23:19:18)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> exchange = ccxt.binance()
>>> ohlcvs = exchange.fetch_ohlcv('BTC/USDT', '1d')
for ohlcv in ohlcvs:
    print(exchange.iso8601(ohlcv[0]), ohlcv[1:])

>>> for ohlcv in ohlcvs:
...     print(exchange.iso8601(ohlcv[0]), ohlcv[1:])
...

YOUR SELECTED TIMEFRAME

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

2020-05-24T00:00:00.000Z [9179.01, 9298.0, 8700.0, 8720.34, 70379.86645]
2020-05-25T00:00:00.000Z [8718.14, 8979.66, 8642.72, 8900.35, 62833.910949]
2020-05-26T00:00:00.000Z [8900.35, 9017.67, 8700.0, 8841.18, 58299.770138]
2020-05-27T00:00:00.000Z [8841.0, 9225.0, 8811.73, 9204.07, 68910.355514]
2020-05-28T00:00:00.000Z [9204.07, 9625.47, 9110.0, 9575.89, 74110.787662]
2020-05-29T00:00:00.000Z [9575.87, 9605.26, 9330.0, 9427.07, 57374.362961]
2020-05-30T00:00:00.000Z [9426.6, 9740.0, 9331.23, 9697.72, 55665.27254]
...
```

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/blob/master/wiki/Manual.md#ohlcv-candlestick-charts
- https://github.com/ccxt/ccxt/wiki/Manual#pagination

**Comment by lsheynova** [comment]
I am not sure if this answer my question, I was hoping to pull historical data like I can with the Binance API, It means I have to use both the Binance API and the CCTX API to pull historical data. I can pull datafrom 1 day ago using CCTX but I want to get data from inception, or 2018.

**Comment by kroitor** [comment]
@lsheynova you should apply some pagination as explained in the Manual and shown in the examples:

- https://github.com/ccxt/ccxt/wiki/Manual#pagination
- https://github.com/ccxt/ccxt/tree/master/examples/py
