### ISSUE TITLE
[bitmex] watch_order_book general question

### ISSUE THREAD

**Issue by ShieldTrade** [ccxt/ccxt#10155]
- OS: windows 10
- Programming Language version: Python 3.9
- CCXT version: CCXT Pro Version 0.8.13
- exchange: bitmex

Reading bitmex api:
"If you wish to get real-time order book data, we recommend you use the orderBookL2_25 subscription. orderBook10 pushes the top 10 levels on every tick, but transmits much more data. orderBookL2 pushes the full L2 order book, but the payload can get very large. orderbookL2_25 provides a subset of the full L2 orderbook, but is throttled. In the future, orderBook10 may be throttled, so use orderBookL2 in any latency-sensitive application. "

When i use watch_order_book  which subscription am I using ?

If I use watch_order_book ( simbol , limit = 25 ) am I using orderBookL2_25 subscription?

does watch_order_book  get updated even if something change above my limit ( ie watch_order_book ( simbol , limit = 25 ), bid 35 changes. Do I get updated?)

my impression is watch_order_book  always subscribe orderBookL2, Ccxt filters it according to limit, and it gets update every time something change regardless of limit. and if I want a different subscription I have to use private API method.

**Comment by ShieldTrade** [comment]
I see this question is still open

from CCXT Pro Version 0.8.13

```
def describe(self):
      ...........
     'options': {
    'watchOrderBookLevel': 'orderBookL2',  # 'orderBookL2' = L2 full order book, 'orderBookL2_25' = L2 top 25, 'orderBook10' L3 top 10
    'tradesLimit': 1000,
    'OHLCVLimit': 1000,

async def watch_order_book(self, symbol, limit=None, params={}):
    table = None
    if limit is None:
        table = self.safe_string(self.options, 'watchOrderBookLevel', 'orderBookL2')
    elif limit == 25:
        table = 'orderBookL2_25'
    elif limit == 10:
        table = 'orderBookL10'
    else:
        raise ExchangeError(self.id + ' watchOrderBook limit argument must be None(L2), 25(L2) or 10(L3)')

```
If i do not specify a limit i get the order BookL2 which pushes the full L2 order book and it is not throttled by the exchange.

am i correct?

**Comment by ttodua** [comment]
issue has been stale, closing for now.
if answer matters at this moment, yes, the code shows that if no limit passed, it defaults to `orderBookL2`
