### ISSUE TITLE
Best way to substitute missing information (bid/ask or volume) from Bittrex and Lbank? (missing from fetch_tickers()))

### ISSUE THREAD

**Issue by MrMechanical** [ccxt/ccxt#10150]
I am really enjoying the ccxt library, it is definitely one of the most useful libraries in the crypto space and I really appreciate its existence. 

I am curious what is the best way to substitute missing ask/bid from Lbank ticker or quoteVolume/baseVolume (either would suffice) from Bittrex ticker (using fetch_tickers()).

Thank you greatly for your help,

MrMechanical

- OS: macOS 10.15.4
- Programming Language version: Python 3.9.4
- CCXT version: 1.57.58

```
bittrex = ccxt.bittrex({'enableRateLimit': True, })
markets = bittrex.load_markets()
symbols = list(markets.keys())
tickers = bittrex.fetch_tickers()
for symbol in symbols:
      if symbol not in tickers:
            continue
      print(tickers[symbol])
lbank = ccxt.lbank({'enableRateLimit': True, })
markets = lbank.load_markets()
symbols = list(markets.keys())
tickers = lbank.fetch_tickers()
for symbol in symbols:
      if symbol not in tickers:
            continue
      print(tickers[symbol])
```

```
Bittrex symbol example missing baseVolume or quoteVolume from fetch_tickers():
{'symbol': '1INCH/BTC', 'timestamp': None, 'datetime': None, 'high': None, 'low': None, 'bid': 6.369e-05, 'bidVolume': None, 'ask': 6.414e-05, 'askVolume': None, 'vwap': None, 'open': None, 'close': 6.4e-05, 'last': 6.4e-05, 'previousClose': None, 'change': None, 'percentage': None, 'average': None, 'baseVolume': None, 'quoteVolume': None, 'info': {'symbol': '1INCH-BTC', 'lastTradeRate': '0.00006400', 'bidRate': '0.00006369', 'askRate': '0.00006414'}}
Lbank symbol example missing ask/bid: 
{'symbol': 'MOVR/USDT', 'timestamp': 1633481171387, 'datetime': '2021-10-06T00:46:11.387Z', 'high': 330.6586, 'low': 287.0861, 'bid': None, 'bidVolume': None, 'ask': None, 'askVolume': None, 'vwap': None, 'open': None, 'close': 314.1679, 'last': 314.1679, 'previousClose': None, 'change': 153.61602959934584, 'percentage': -4.32, 'average': 237.35988520032706, 'baseVolume': 47.194, 'quoteVolume': 14963.3806, 'info': {'symbol': 'movr_usdt', 'ticker': {'high': '330.6586', 'vol': '47.194', 'low': '287.0861', 'change': '-4.32', 'turnover': '14963.3806', 'latest': '314.1679'}, 'timestamp': '1633481171387'}}
```

**Comment by kroitor** [comment]
```Python
import ccxt
bittrex = ccxt.bittrex({
    'options': {
        'fetchTickers': {
            'method': 'publicGetMarketsSummaries',
        },
    },
})
tickers = bittrex.fetch_tickers()
for symbol, ticker in tickers.items():
      print(tickers[symbol])
```

Lbank does not have it, use fetch_order_book() to obtain bids and asks from there.

- https://github.com/ccxt/ccxt/wiki/Manual#order-book
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/

**Comment by MrMechanical** [comment]
@kroitor Thank you greatly for the quick response.

If I want both bid/ask and volume from Bittrex tickers should I have 2 instances of Bittrex exchange (one set for bid/ask and another set for qouteVolume/baseVolume with publicGetMarketsSummaries) since publicGetMarketsSummaries doesn't have bid/ask? What is the best method to get both bid/ask and qouteVolume/baseVolume while still being protected by the rate limiter?

Thank you so much for your help.
Kind regards,
MrMechanical

**Comment by MrMechanical** [comment]
I found it is possible to call fetch_tickers() with publicGetMarketsSummaries enabled and again with publicGetMarketsTickers enabled and then combining the information using the same bittrex exchange instance.

`bittrex.options['fetchTickers']['method'] = 'publicGetMarketsSummaries'

bittrex.options['fetchTickers']['method'] = 'publicGetMarketsTickers'`

**Comment by ttodua** [comment]
@MrMechanical I think you might get misleaded with what you were doing. 
The `publicGetMarketsSummaries` doesn't return bid/ask volumes (base/quote volumes), instead they return last 24-hour base/quote volume in sum. So, be careful with that.

**Comment by MrMechanical** [comment]
I was not aware of this, thanks for letting me know.
