### ISSUE TITLE
function params is not known

### ISSUE THREAD

**Issue by fengyeall111** [ccxt/ccxt#10162]
this project is so powerful,but there are some spots.
when I use function ,such as fetchOLHCV,the api is no explains about its inputs and outputs..especilly function params.
so I must use "debug debug debug"  to find how it works and decide function argument.   
swagger is prefect to it.

**Comment by kroitor** [comment]
@fengyeall111 the arguments of fetchOHLCV are documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts

The fields inside the `params` argument are exchange-specific and this is also noted in the Manual here:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

So, if you are wondering which exchange-specific params are supported for this or that exchange, then either open the source code for the exchange in question from the CCXT repository, or read the API documentation for the exchange of your interest. 

Let us know if that does not answer your question.
