### ISSUE TITLE
Using accountsByType in general..

### ISSUE THREAD

**Issue by christophe-hall** [ccxt/ccxt#10165]
I'm trying to automate balance queries for every available account type of any given exchange. It seemed like a good idea to use exchange.options.accountsByType to get a list of the exchange account types but the application of this property seems to vary between different exchange classes.

Is there a recommended approach to achieve my goal?

TIA.

**Comment by ttodua** [comment]
There is no other possible way that, as only whatever CCXT has unified, it is available. In other cases, all exchanges have their own endpoints to return accounts/subaccount types, and CCXT doesn't have an unified  balance fetching methods to return balances for all accounts/subaccounts in same way. In future, it might ever be unified in CCXT.
( @kroitor lmk if anything wrong.)

**Comment by kroitor** [comment]
I would add that you can still do whatever you want to do as long as it is supported by the underlying exchange APIs, cause CCXT allows you to talk to exchange-specific endpoints directly with the Implicit API:

- https://docs.ccxt.com/en/latest/manual.html#implicit-api

We just don't have this aspect finished in the Unified API yet (https://docs.ccxt.com/en/latest/manual.html#unified-api), but we will cover it eventually.

**Comment by christophe-hall** [comment]
Ok guys thanks for the replies.
