### ISSUE TITLE
okex update fetchClosedOrders()

### ISSUE THREAD

**Issue by cabanossi** [ccxt/ccxt#10179]
Hello!

At the moment, the fetchClosedOrders function in the okex.js take the method ``privateGetTradeOrdersHistory`` (Line 1806).

Can this change to the ``privateGetTradeOrdersHistoryArchive`` method?

The costs a little bit higher, but you become the records for 3 months and not only for 7 days. :-)

https://www.okex.com/docs-v5/en/?java#rest-api-trade-get-order-history-last-7-days
Rate Limit: 40 requests per 2 seconds

https://www.okex.com/docs-v5/en/?java#rest-api-trade-get-order-history-last-3-months
Rate Limit: 20 requests per 2 seconds

The Response is the same.

The ``privateGetTradeOrdersHistoryArchive`` is already available in the okex.js (trade/orders-history-archive - Line 144)

Old Line 1806
```
const method = this.safeString (options, 'method', 'privateGetTradeOrdersHistory');
```

New Line 1806
```
const method = this.safeString (options, 'method', 'privateGetTradeOrdersHistoryArchive');
```

Alternatively, one could also make the method configurable via the params ?!

e.g.
params { archiv: true }
```
let defaultMethod = 'privateGetTradeOrdersHistory';
const archiv = this.safeString (params, 'archiv');
params = this.omit (params, 'archiv');
if (archiv) {
    defaultMethod = 'privateGetTradeOrdersHistoryArchive';
}
const method = this.safeString (options, 'method', defaultMethod);
```

If desired, I can also create a pull request! (but must know for which variant) ;-)

**Comment by kroitor** [comment]
It is already supported, just instantiate the exchange like this:

```JavaScript
const exchange = new ccxt.okex({
    'options': {
        'fetchClosedOrders': {
            'method': 'privateGetTradeOrdersHistoryArchive',
        },
    }
})
```

Or set that option in runtime before the call to `fetchClosedOrders`:

```JavaScript
exchange.options['fetchClosedOrders'] = { 'method': 'privateGetTradeOrdersHistoryArchive' }
```

Let us know if that does not answer your question.

**Comment by cabanossi** [comment]
just tried. Unfortunately does not work.

In the Line 1780 ``const options = this.safeString (this.options, 'fetchClosedOrders', {});`` i can see the variable in the safeString-function:
![image](https://user-images.githubusercontent.com/16591195/136573080-42fcdc18-6069-49f5-b229-be37cf502b5e.png)

but in Line 1806 ``const method = this.safeString (options, 'method', 'privateGetTradeOrdersHistory');`` the result is the default and not the new value!
