### ISSUE TITLE
How Can I Use The OKEX Demo Trading,Now it 

### ISSUE THREAD

**Issue by homily** [ccxt/ccxt#10196]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- OS:win10
- Programming Language version: Python 3.9 
- CCXT version:    ccxt-1.57.94

Hi,

Now i want to change okex V3 to okex V5 api,
but ,some code wants debug. when i try it.
i see the v5 Demo Trading not change rest url

Demo Trading  use  the Rest Url "https://www.okex.com" too,
but just  added  "x-simulated-trading:1"  to the header of the Demo Trading request.
so ,I'm not find how to change testmode in ccxt。

Thank for your job 。

**Comment by ttodua** [comment]
I can't understand what site is `https://www.ouyi.run/` (even thought it seems OKEX homepage, I don't consider it as valid website and would advise to stay away).
Okex has V5 api already implemented.

To use simulated trading with Okex Exchange, refer to this: https://github.com/ccxt/ccxt/issues/7088
