### ISSUE TITLE
When to use fetchDepositAddress or createDepositAddress? (question)

### ISSUE THREAD

**Issue by MrMechanical** [ccxt/ccxt#10191]
Hello I have a question:

When should I use fetchDepositAddress or createDepositAddress? How do I know if the address is already created or not?

Thank you so much for your help,
I am really enjoying ccxt.
MrMechanical

**Comment by kroitor** [comment]
> When should I use fetchDepositAddress or createDepositAddress? How do I know if the address is already created or not?

If `fetchDepositAddress` throws an `InvalidAddress` exception at you or returns an empty/None response – that might indicate that you have to call `createDepositAddress` first or create your addresses for your wallet on the exchange website.

Let us know if that does not answer your question.
