### ISSUE TITLE
Create subaccount support kucoin python

### ISSUE THREAD

**Issue by art1313** [ccxt/ccxt#10195]
Hi, 

It appears that python library for Kucoin do not support creation of subaccounts. Is this something that is going to be added in the near future? 

Thanks.

**Comment by ttodua** [comment]
Seems sub-accounts can't be created from API : https://support.kucoin.plus/hc/en-us/articles/900002862643-Sub-Account
'account' on kucoin seems itself to be an isolated entity, which can generate API keys only for itself (account-scope), and can't create other accounts with its API key.

**Comment by adamrg73** [comment]
kucoin api supports this Ive seen it in the api

**Comment by ttodua** [comment]
> kucoin api supports this Ive seen it in the api

the last time i've commented above , there I couldn't find. if they added recently, i dont know. please drop me the link if you saw it.

**Comment by fniko** [comment]
[Create Sub-Account](https://docs.kucoin.com/#create-sub-account)
[Create Spot APIs for Sub-Account](https://docs.kucoin.com/#create-spot-apis-for-sub-account)

**Comment by ttodua** [comment]
the endponts were added already in the past, as implicit endpoints (https://docs.ccxt.com/#/README?id=implicit-api)

you can use 
```
params = {
  password: 123,
  # and any other params listed at https://www.kucoin.com/docs/rest/account/sub-account/create-sub-account
}
result = await ex.privatePostSubUserCreated(params)
```

let us know if anyone sees any issue in ccxt
