### ISSUE TITLE
The initial value of properties of `has` should be false in base/Exchange.js

### ISSUE THREAD

**Issue by Cinux-Chosan** [ccxt/ccxt#10194]
Gate.io Does not implement method `createMarketOrder`, nor, rewrite it's `has.createMarketOrder` property to `false`. But the result of `Gate.io#has.createMarketOrder` is true due to the deep extension from `base/Exchange`. This may be a mistake of Gate.io, but I think it's better that properties of `base/Exchange.has` should be false, any exchange who implement it can rewirte its own to true.

**Comment by kroitor** [comment]
@Cinux-Chosan most of the missing methods are either `undefined` (if we don't know for use if a corresponding endpoint is available from the exchange, or it is not implemented yet) or `false` (if we know for sure that the exchange does not have it).

This is covered here:

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata

I've pushed a fix for gateio: https://github.com/ccxt/ccxt/commit/8b02400156260f752fbaaa511f7cfd9b5435e575

**Comment by Cinux-Chosan** [comment]
Very efficient!
