### ISSUE TITLE
Timestamp for this request was 1000ms ahead of the server's time

### ISSUE THREAD

**Issue by MelbourneDeveloper** [ccxt/ccxt#1022]
Sorry for repeating a problem that has already been reported but this bug has not been fixed. At first I thought it was just because my clock was not synced but I've gone as far as getting the time from the Binance server first, and then sending the request but it still does not work. 

Previous issues here and here:
https://github.com/ccxt/ccxt/issues/773
https://github.com/ccxt/ccxt/issues/850

- OS: Windows
- Programming Language: C#
- CCXT version: 3 ?
- Exchange: Binance
- Method: GET

```
↑↑↑ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE

            var binanceTime = await RESTClient.GetAsync<BinanceTime>("/api/v1/time");
            var currentDateTimeUTC = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc).AddMilliseconds(binanceTime.serverTime);
            System.Diagnostics.Debug.WriteLine("binance" + currentDateTimeUTC);
            var queryString = $"api/v3/account?recvWindow=10000000&timestamp={currentDateTimeUTC.Ticks}";
            var uri = new Uri($"{RESTClient.BaseUri}{queryString}");
            var encryptor = new HMACSHA256(Encoding.UTF8.GetBytes(ApiSecret));
            queryString += $"&signature={ByteToString(encryptor.ComputeHash(Encoding.UTF8.GetBytes(uri.Query.Replace("?", ""))))}";
            RESTClient.Headers.Add("X-MBX-APIKEY", ApiKey);
            var retVal = await RESTClient.GetAsync<string>(queryString);


{"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}'

↓↓↓ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE
```

**Comment by kroitor** [comment]
Do you have system clock syncrhonization enabled in Windows and do you have set it up to synchronize time over the internet once in 10 minutes or less?

**Comment by kroitor** [comment]
@MelbourneDeveloper I suggest to move this discussion to #850 after you check 1, 2 and 3. Closing this as a duplicate for now.
