### ISSUE TITLE
watchOHLCV doesnt work without await

### ISSUE THREAD

**Issue by dnld23** [ccxt/ccxt#10229]
The purpose i want to achieve is to be subscribed to many markets [right now at binance] at once and have current OHLCV data without need to fetchOHLCV each time and for each pair. Understand lets say 200 or 300 markets within 1 websocket application instance.

But we are getting into issue with watchOHLCV. If used without await, it will show warning and data will never load. If we use await, it will probably wait until next update, which can take minutes. But we cannot wait minutes for each single pair, while whole daemon has to watch other 200 or 300 markets, if data is not yet available, it needs to move further. But it seems like CCXT.pro is not able to work this way.

The same issue we ran into on watch_orderbook, where we just had to put await for the first time, if used without await, data never get updated. This is also very frustrating,  because when you just run the script, it will take 15 minutes just to await through all orderbooks. Not good, but at least after initial load it works. But all examples and youtube video i saw regarding watchOHLCV count on using await, which is basically completely defying purpose to build asynchronnous application.

**Comment by janeCMD** [comment]
@kroitor Thank you very much ! I will rework my code completely and try to do it according to given examples.
