### ISSUE TITLE
watchOrders returns data for different Binance APIs from one account

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#10223]
On the Binance Spot on one account we have two APIs.
When `watchOrder` is starting for first API, both (first and second API) receives updates. 

Is it possible to receive updates only for one API which is subscribed via `watchOrder` 

- OS: Debian (Docker)
- Programming Language version: JavaScript
- CCXT version: ccxt.pro 0.6.82

This code reproduce that updates for order created on one of APIs, will be received on both exchange instances configured with different APIs.

```
const ccxt = require ('ccxt.pro');

let binance1 = new ccxt.binance({
    'apiKey' : 'my-api-1',
    'secret' : 'my-secret-1'
});

let binance2 = new ccxt.binance({
    'apiKey' : 'my-api-2',
    'secret' : 'my-secret-2'
});

async function watch1() {
    while (true) {

        const orders = await binance1.watchOrders();

        let order = orders.shift();

        if (order.status === 'open') {
            console.log("//////////////// watch1 ////////////////////");
            console.log(order);
        }

    }
}

async function watch2() {
    while (true) {

        const orders = await binance2.watchOrders();

        let order = orders.shift();

        if (order.status === 'open') {
            console.log("//////////////// watch2 ////////////////////");
            console.log(order);
        }

    }
}

watch1();
watch2();
```

**Comment by kroitor** [comment]
@wunderb1t you can use one exchange instance per keypair and run them in parallel, as shown in the examples:
- https://github.com/ccxt/ccxt/tree/master/examples
Let us know if that does not answer your question.

**Comment by kroitor** [comment]
@wunderb1t do you create those API keys using the same account? Cause then both of them will be mirroring each other. All API keys and all WS updates belong to the same account.
