### ISSUE TITLE
Would it be possible to fetch aggregated liquidation data for cryptocurrencies from Binance?

### ISSUE THREAD

**Issue by avatar-lavventura** [ccxt/ccxt#10234]
- OS: linux
- Programming Language version: Python 3.7
- CCXT version: `ccxt==1.57.52`

---------

On these sites (https://coinalyze.net/ethereum-classic/liquidations/, [BTC/USDT][1]), I am able to add following indications into grpah [`Liquidations`, `Long Liquidations`, `Short Liquidations`, `Aggregated Liquidations COIN-margined Contracts`, `Aggregated Liquidations STABLECOIN-margined Contracts`].

> Aggregated liquidations = liquidations of coin-margined contracts +
> liquidations of stablecoin-margined contracts converted to USD. For
> the moment only BTC/USD and BTC/USDT contracts are included. See the
> indicator options, you can select/deselect individual contracts.

-----

I have tried https://github.com/ccxt/ccxt/issues/7173#issuecomment-875802958 but it only fetchs liquadation data of my own not the other users.

=> Is it possible to obtain data for liquidations in cryptocurrencies from `Binance` using `ccxt`? 

  [1]: https://coinalyze.net/bitcoin/liquidations/

**Comment by kroitor** [comment]
@avatar-lavventura thanks for the feedback!
