### ISSUE TITLE
zb account can't be accessed with correct apiKey and secret

### ISSUE THREAD

**Issue by tandazhi** [ccxt/ccxt#1024]
PASTE_YOUR_TEXT_DESCRIPTION_HERE

- OS: ubuntu 16
- Programming Language: python
- CCXT version: 1.10.357
- Exchange: zb
- Method: fetchBalance()

```
↑↑↑ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE

MUST_READ_THIS https://github.com/kroitor/ccxt/wiki/Manual#troubleshooting

REPLACE_WITH_YOUR_CODE_TO_REPRODUCE_THE_BUG_HERE

p=ccxt.zb()
p.apiKey=''
p.secret=''
p.fetchBalance()

REPLACE_WITH_YOUR_VERBOSE_OUTPUT_HERE

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\ccxt\zb.py", line 130, in fetch_balance
    response = self.privatePostGetAccountInfo()
  File "C:\Python36\lib\site-packages\ccxt\zb.py", line 286, in request
    raise ExchangeError(self.id + ' ' + self.json(response))
ccxt.base.errors.ExchangeError: zb {"code":1003,"message":"\u9a8c\u8bc1\u4e0d\u901a\u8fc7"}

↓↓↓ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE
```

**Comment by kroitor** [comment]
@tandazhi thanks for reporting, I will look into it and will fix it asap.

**Comment by TJett** [comment]
I'm having the same issue with GDAX when filling in the key/secret/password in some of the examples.

**Comment by kroitor** [comment]
@TJett you should be using the passphrase used for creating the keys, not the user password. More about it here: https://github.com/ccxt/ccxt/issues/24#issuecomment-355785724

**Comment by TJett** [comment]
I’m using the generated passphrase. My api key works with gdax’s example python code, but not with the example/py code from ccxt.
I getting an invalid api key error, not the exact same error @tandazhi is reporting (but similar, because his error roughly translates to "Verification does not pass")
Since my issue is with gdax, should I open a different issue/question? I don't want to hijack an issue.

**Comment by kroitor** [comment]
@TJett yes, if you can, please open a new one, but make sure to include your code (so that I could copypaste it) and verbose output, as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by TJett** [comment]
I apologize, I didn't realize I needed to create a separate sandbox account/keys to be able to use the api similarly to the examples. Everything works fine on the main platform.

**Comment by kroitor** [comment]
@TJett ok, no worries, glad you figured it out. Thx for reporting back!

**Comment by lechengyu** [comment]
Using nodejs and facing the same issue,  I checked the code in ZB.js, found that something wrong with the code in it , I will try to fix it and make a pull request later.

**Comment by kroitor** [comment]
@lechengyu thx! make sure to read this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

**Comment by jjhesk** [comment]
@kroitor @Deathamns please consider the new update implementations from the official guide https://github.com/zb2017/api

**Comment by kroitor** [comment]
Moved to #1269
