### ISSUE TITLE
[okex] incorrect error mapping

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#10256]
`BadSymbol: okex5 {"code":"1","data":[{"clOrdId":"ddd","ordId":"","sCode":"51030","sMsg":"Funding fee is being settled.","tag":""}],"msg":""}`

When placing a futures order during the settlement period I see the following error.  I don't think BadSymbol is quite right, though I'm sure sure exactly what the error should be.  Perhaps a subclass of OnMaintennance?

**Comment by samgermain** [comment]
@kroitor I'm thinking either `OnMaintenance`, `InvalidOrder`, `OrderNotFillable`, `BadResponse` or `ExchangeError`
