### ISSUE TITLE
Some none on kucoin ticker

### ISSUE THREAD

**Issue by mablue** [ccxt/ccxt#10265]
`
 {'symbol': 'CTSI/USDT', 'timestamp': 1634659886833, 'datetime': '2021-10-19T16:11:26.833Z', 'high': 0.7686, 'low': 0.6552, 'bid': 0.7107, 'bidVolume': None, 'ask': 0.7122, 'askVolume': None, 'vwap': 0.7359226141198828, 'open': None, 'close': 0.7121, 'last': 0.7121, 'previousClose': None, 'change': -0.0075, 'percentage': -1.04, 'average': 0.73590243, 'baseVolume': 566536.76398785, 'quoteVolume': 416927.2163489577, 'info': {'time': 1634659886833, 'symbol': 'CTSI-USDT', 'buy': '0.7107', 'sell': '0.7122', 'changeRate': '-0.0104', 'changePrice': '-0.0075', 'high': '0.7686', 'low': '0.6552', 'vol': '566536.76398785', 'volValue': '416927.216348957651', 'last': '0.7121', 'averagePrice': '0.73590243', 'takerFeeRate': '0.001', 'makerFeeRate': '0.001', 'takerCoefficient': '1', 'makerCoefficient': '1'}}
`

**Comment by kroitor** [comment]
@mablue which specific fields do you mean?

**Comment by kroitor** [comment]
@mablue 

> the important one is open field! also some others like :

Will add that, thanks for pointing it out!

> bidVolume , askVolume , previousClose

Those are missing in the exchange's API response, as you see in the `info`. When the exchange does not provide that info, we cannot invent out of this air.
