### ISSUE TITLE
How to get Kucoin Sub-accounts list and balances?

### ISSUE THREAD

**Issue by dompaks10** [ccxt/ccxt#10276]
Hi, I use ccxt to fetch balance on kucoin, but the one showing is only for the main account, how can I fetch sub-accounts list and balances?

**Comment by ttodua** [comment]
You can try:
for main account:
`await exchange.fetchBalance({'type':'main'})`

for trading account:
`await exchange.fetchBalance({'type':'trade'})` //however, this is default
