### ISSUE TITLE
Huobi - currencies info missing

### ISSUE THREAD

**Issue by krychla1** [ccxt/ccxt#10278]
- OS: linux
- Programming Language version: nodejs
- CCXT version: 1.58.75 (guilty 1.58.20)

Fetch currencies got wrong for huobi in 1.58.20 and later:

expected:
![image](https://user-images.githubusercontent.com/33096727/138242158-b52d1b9a-cee1-4665-ae85-06f8fdbe80f4.png)

actual:
![image](https://user-images.githubusercontent.com/33096727/138242388-cf953a14-5e3b-4cfd-8830-e5786b3a6555.png)

Please take a look, thanks

**Comment by kroitor** [comment]
@krychla1 hi! Sorry, can you specify what exactly is wrong with the new update?

**Comment by frosty00** [comment]
I think for cases where there is just one network we will also duplicate some info into the top level for users
