### ISSUE TITLE
[ftx] timeout error mapping?

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#10289]
I'm using a slightly old version so not sure if this is a real issue - apologies if not.

I got a timeout from FTX today, but the error wasn't `RequestTimeout`, instead I got:

`ExchangeNotAvailable: ftx POST https://ftx.com/api/orders request-timeout network timeout at: https://ftx.com/api/orders`

**Comment by npomfret** [comment]
FTX said that's not one of their errors

**Comment by npomfret** [comment]
They did ask why the HTTP status code was.  Can we get ccxt to always report this in the error?

**Comment by kroitor** [comment]
@npomfret it is usually printed in verbose mode.

The question is, which part of _"request-timeout network timeout"_ comes from your own code, and which part of it comes from the underlying networking library? Search it on the internet, there are no other mentions of the exact same wording literally, except your own issue here (this issue): https://www.google.com/search?q=%22request-timeout+network+timeout%22

**Comment by npomfret** [comment]
It would be great to have the status code returned in the standard error (or as a property on the standard error)

issues like this I can't use verbose mode as they happen too infrequently in real life and I've no idea how to generate them artificially.

**Comment by kroitor** [comment]
@npomfret we have a branch that covers exactly that, however, it's not fully tested yet: https://github.com/ccxt/ccxt/pull/5348/files Will get back to it asap.

**Comment by ttodua** [comment]
@frosty00 Has you ever been able to make the another PR  (which you mentioned in #5348) ?

**Comment by samgermain** [comment]
closing as ftx is delisted now
