### ISSUE TITLE
watchTicker hangs on at non-existed pair

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#10283]
When `watchTicker` is called passing non-existed pair it hangs on. Is it possible to set timeout for `watchTicker` or interrupt subscribing attempt?

- OS: Debian (Docker)
- Programming Language version: JavaScript
- CCXT version: ccxt.pro 0.6.82

```
const binance = new ccxt.binance({
   apiKey: 'my api',
   secret: 'my secret'
});

async subscribe() {
   // hangs on here ...
   await watchTicker("DOTDOWN/USDT");
}

subscribe();
```

**Comment by ttodua** [comment]
This issue is no longer reproducible, seems it was fixed in the past. Inexistent markets throw `BadSymbol` exception
