### ISSUE TITLE
New Exchange: Negociecoins

### ISSUE THREAD

**Issue by Felipe-Mangueira** [ccxt/ccxt#1029]
Thank you very much for keeping this amazing library updated.

I would like to make a suggestion of a new exchange: Negociecoins. It's a brazilian exchange.

This is the main site: https://www.negociecoins.com.br/

This is the public API documentation site: https://www.negociecoins.com.br/documentacao-api
This is the private API documentation site: https://www.negociecoins.com.br/documentacao-tradeapi

Thank you!!

**Comment by jjhesk** [comment]
do you allow to make pull request? @kroitor. what is the steps needed to be taken in order to pass thru all the test cases? are there any documentation about this?

**Comment by Deathamns** [comment]
@jjhesk Have already started working on it? Because I kind of did, public API is mostly implemented.

**Comment by kroitor** [comment]
@jjhesk https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

**Comment by jjhesk** [comment]
@Deathamns no i have not touched any code for implementing this exchange api.

**Comment by brunocvcunha** [comment]
@Deathamns is it working for you? getting 403 all the time.

**Comment by Deathamns** [comment]
No, I was getting the same error when I was testing a while back. I even tried their PHP and Python examples from [here](https://www.negociecoins.com.br/documentacao-tradeapi), added the API key/secret and got the same problem.

**Comment by brunocvcunha** [comment]
Thanks @Deathamns.

Right, I contacted their support and they said the APIs are off for some reason.
