### ISSUE TITLE
Bitmex. Remaining is different from leavesQty for partially filled order

### ISSUE THREAD

**Issue by ShieldTrade** [ccxt/ccxt#10301]
OS:Windows 10
Programming Language version: Python 3.7
CCXT version: CCXT version: CCXT Pro Version: 0.8.13

Reading on ccxt documents:
'remaining':          // remaining amount to fill
reading on bitmex API:
"leavesQty":  // The quantity remaining to be filled in the order associated with this execution.  leavesQty = orderQty - cumQty

I expect the 2 values to be the same.
This is what I get with exchange.watch_order ( 'newUpdates': True in markets properties) after a partial fill

[{'info': {'orderID': '47f574cd-d1e9-47b3-a41e-3fa918034e2f', **'leavesQty': 200,** 'cumQty': 300, 'avgPx': 52516.0437, 'timestamp': '2021-10-22T15:54:01.003Z', 'clOrdID': '', 'account': 376818, 'symbol': 'XBTEUR'},
 
'id': '47f574cd-d1e9-47b3-a41e-3fa918034e2f', 'clientOrderId': '', 'timestamp': 1634918041003, 'datetime': '2021-10-22T15:54:01.003Z', 'lastTradeTimestamp': None, 'symbol': 'BTC/EUR', 'type': None, 'timeInForce': None, 'postOnly': False, 'side': None, 'price': None, 'stopPrice': None, 'amount': None, 'cost': 15754813.110000001, 'average': 52516.0437, 'filled': 300.0, **'remaining': None,** 'status': None, 'fee': None, 'trades': None, 'fees': []}]

I did many experiments and it looks like remains values  for limited orders are:
0 when an order is closed (as expected)
same as amount when an order is open (as expected) 
same as amount  when Quantity is amended ( does not consider previous partial fill not as expected)
"None" when an order is canceled (as expected)
"None" when price is amended (as expected)
"None" when a limit order on book is partially filled as in the example above (not as expected)

But if the limit order crosses the book and it is partially filled and partially remains on book I get the correct remaining field as expected

[{'info': {'orderID': '2f4685e6-07a2-42a1-bb94-98cca419d09b', 'clOrdID': '', 'clOrdLinkID': '', 'account': 376818, 'symbol': 'XBTEUR', 'side': 'Buy', 'simpleOrderQty': None, 'orderQty': 200, 'price': 54662.5, 'displayQty': None, 'stopPx': None, 'pegOffsetValue': None, 'pegPriceType': '', 'currency': 'EUR', 'settlCurrency': 'XBt', 'ordType': 'Limit', 'timeInForce': 'GoodTillCancel', 'execInst': '', 'contingencyType': '', 'exDestination': 'XBME', 'ordStatus': 'PartiallyFilled', 'triggered': '', 'workingIndicator': True, 'ordRejReason': '', 'simpleLeavesQty': None, **'leavesQty': 100,** 'simpleCumQty': None, 'cumQty': 100, 'avgPx': 54662.5, 'multiLegReportingType': 'SingleSecurity', 'text': 'Submission from testnet.bitmex.com', 'transactTime': '2021-10-22T09:26:55.447Z', 'timestamp': '2021-10-22T09:26:55.447Z'},
 'id': '2f4685e6-07a2-42a1-bb94-98cca419d09b', 'clientOrderId': '', 'timestamp': 1634894815447, 'datetime': '2021-10-22T09:26:55.447Z', 'lastTradeTimestamp': 1634894815447, 'symbol': 'BTC/EUR', 'type': 'limit', 'timeInForce': 'GTC', 'postOnly': False, 'side': 'buy', 'price': 54662.5, 'stopPrice': None, 'amount': 200.0, 'cost': 5466250.0, 'average': 54662.5, 'filled': 100.0, **'remaining': 100.0, '**status': 'open', 'fee': None, 'trades': None, 'fees': []}]

is this the correct behavior?

**Comment by sgtroy88** [comment]
> OS:Windows 10
> Programming Language version: Python 3.7
> CCXT version: CCXT version: CCXT Pro Version: 0.8.13
> 
> Reading on ccxt documents:
> 'remaining':          // remaining amount to fill
> reading on bitmex API:
> "leavesQty":  // The quantity remaining to be filled in the order associated with this execution.  leavesQty = orderQty - cumQty
> 
> I expect the 2 values to be the same.
> This is what I get with exchange.watch_order ( 'newUpdates': True in markets properties) after a partial fill
> 
> [{'info': {'orderID': '47f574cd-d1e9-47b3-a41e-3fa918034e2f', **'leavesQty': 200,** 'cumQty': 300, 'avgPx': 52516.0437, 'timestamp': '2021-10-22T15:54:01.003Z', 'clOrdID': '', 'account': 376818, 'symbol': 'XBTEUR'},
>  
> 'id': '47f574cd-d1e9-47b3-a41e-3fa918034e2f', 'clientOrderId': '', 'timestamp': 1634918041003, 'datetime': '2021-10-22T15:54:01.003Z', 'lastTradeTimestamp': None, 'symbol': 'BTC/EUR', 'type': None, 'timeInForce': None, 'postOnly': False, 'side': None, 'price': None, 'stopPrice': None, 'amount': None, 'cost': 15754813.110000001, 'average': 52516.0437, 'filled': 300.0, **'remaining': None,** 'status': None, 'fee': None, 'trades': None, 'fees': []}]
> 
> I did many experiments and it looks like remains values  for limited orders are:
> 0 when an order is closed (as expected)
> same as amount when an order is open (as expected) 
> same as amount  when Quantity is amended ( does not consider previous partial fill not as expected)
> "None" when an order is canceled (as expected)
> "None" when price is amended (as expected)
> "None" when a limit order on book is partially filled as in the example above (not as expected)
> 
> But if the limit order crosses the book and it is partially filled and partially remains on book I get the correct remaining field as expected
> 
> [{'info': {'orderID': '2f4685e6-07a2-42a1-bb94-98cca419d09b', 'clOrdID': '', 'clOrdLinkID': '', 'account': 376818, 'symbol': 'XBTEUR', 'side': 'Buy', 'simpleOrderQty': None, 'orderQty': 200, 'price': 54662.5, 'displayQty': None, 'stopPx': None, 'pegOffsetValue': None, 'pegPriceType': '', 'currency': 'EUR', 'settlCurrency': 'XBt', 'ordType': 'Limit', 'timeInForce': 'GoodTillCancel', 'execInst': '', 'contingencyType': '', 'exDestination': 'XBME', 'ordStatus': 'PartiallyFilled', 'triggered': '', 'workingIndicator': True, 'ordRejReason': '', 'simpleLeavesQty': None, **'leavesQty': 100,** 'simpleCumQty': None, 'cumQty': 100, 'avgPx': 54662.5, 'multiLegReportingType': 'SingleSecurity', 'text': 'Submission from testnet.bitmex.com', 'transactTime': '2021-10-22T09:26:55.447Z', 'timestamp': '2021-10-22T09:26:55.447Z'},
>  'id': '2f4685e6-07a2-42a1-bb94-98cca419d09b', 'clientOrderId': '', 'timestamp': 1634894815447, 'datetime': '2021-10-22T09:26:55.447Z', 'lastTradeTimestamp': 1634894815447, 'symbol': 'BTC/EUR', 'type': 'limit', 'timeInForce': 'GTC', 'postOnly': False, 'side': 'buy', 'price': 54662.5, 'stopPrice': None, 'amount': 200.0, 'cost': 5466250.0, 'average': 54662.5, 'filled': 100.0, **'remaining': 100.0, '**status': 'open', 'fee': None, 'trades': None, 'fees': []}]
> 
> is this the correct behavior?
> 
> 
> 
> 
>  

http://www.w3.org/TR/1999/REC-html401-19991224/win/dtd

**Comment by ttodua** [comment]
the late reply, but i have tested this thoroughly myself, made sample trades and then partiall fills one by one, exactly as described by OP, and I see that issue is no longer reproducable. so, it seems to have been fixed in the past.
closing this issue, if anyone still experiences issues with ccxt, let us know
