### ISSUE TITLE
priceToPrecision returns String

### ISSUE THREAD

**Issue by Pmant** [ccxt/ccxt#1034]
Function priceToPrecision returns String-Type, should be Float.

- OS: Windows 10
- Programming Language: Node.js 8.9.3
- CCXT version: 1.1.544
- Exchange: Bittrex (all?)
- Method: priceToPrecision 

```
const ccxt = require ('ccxt');
const bittrex    = new ccxt.bittrex({});

(async () => {
    await bittrex.loadMarkets();
    console.log(typeof bittrex.priceToPrecision('DGB/BTC', 0.00000509))
})();
```
output: 'string'

**Comment by kroitor** [comment]
> should be Float

No, it shouldn't ) We never said that. 

Instead, it should return a value that is accepted by the exchange. That can be a float or a string, depending on the exchange. And because Bittrex accepts POST-params in `x-www-form-urlencoded` style, those string-values work well internally (as well as with many other exchanges).

If you want a float, you need to simply to this:

```JavaScript
(async () => {
    await bittrex.loadMarkets();
    const heyYourPriceIsAFloatAlready = 0.00000509
    console.log(typeof heyYourPriceIsAFloatAlready) // ← "cool hack" ))
})();
```

I'd close this issue for now if you don't mind. Let me know if you still have questions on this.

**Comment by Pmant** [comment]
In Javascript most of the times you can use floats are automatically converted to strings if necessary, which is not true the other way around. Internally I'm calculating trade price and amount in float precision but eventually I have to convert them to the precision of the exchange. Before actually executing the trade I'm doing some more calculations and checks where I use the values returned by priceToPrecision and amountToPrecision (which acutally return a number).

**Comment by kroitor** [comment]
```JavaScript
(async () => {
    await bittrex.loadMarkets();
    console.log(typeof parseFloat (bittrex.priceToPrecision('DGB/BTC', 0.00000509)))
})();
```

↑ If you want it ;)

**Comment by Pmant** [comment]
Yes that's what I'm doing in my code, I just suggested that it would be more intuitive if the values which are returned by priceToPrecision und amountToPrecision had the same type. 
If it is actually intended the way it is you can close this issue.

**Comment by kroitor** [comment]
@Pmant 

> If it is actually intended the way it is you can close this issue.

Currently, it is, but we are going to make it more convenient very soon, we are working on a much better support for arbitrary precision: https://github.com/ccxt/ccxt/issues/522.
Will keep you updated on our progress. Thx!
