### ISSUE TITLE
Websocketssupport 

### ISSUE THREAD

**Issue by love2kite** [ccxt/ccxt#1035]
Great library, I'm new to it but exploring the JS code.

I'm interested in the WebSocket market data capabilities of some exchanges. I read that it was suggested before and was answered that the support will be ready on September 17.
Any update on the matter?

Thanks for every thing!

**Comment by kroitor** [comment]
Hi! The work on it going on here: https://github.com/ccxt/ccxt/issues/56#issuecomment-353688827 and there were some major improvements in that direction, but we don't have an ETA on that other than ASAP. I'm closing this as a duplicate if you don't mind. I suggest moving this discussion to the linked issue. Thx!
