### ISSUE TITLE
Get active_price and callback_rate from Binance

### ISSUE THREAD

**Issue by andrewklau** [ccxt/ccxt#10368]
When retrieving orders from Binance active_price and  callback_rate are missing from CCXT's data

This is used for Binance for trailing stop orders. Is there any way to get this data included in the order query?

- OS: Linux
- Programming Language version: Javascript/NodeJS
- CCXT version: CCXT Pro v0.9.9

**Comment by ttodua** [comment]
Please post the test snippet you use (omit any sensitive info).
