### ISSUE TITLE
Indodax create order issue

### ISSUE THREAD

**Issue by codemonkeyno1** [ccxt/ccxt#10365]
I am trying to send buy order for "SHIB/USDT" using ccxt for Indodax.  I get error:

`ccxt.base.errors.InvalidOrder: indodax {"success":0,"error":"Minimum price 0.00000001 USDT"}`

The price I am trying to send is over that amount:
`exchange.create_order(symbol='SHIB/USDT',type='limit',side='buy',amount=50000, price=7e-05)`

What explains the error?

**Comment by DoctorSlimm** [comment]
@codemonkeyno1 it works if you just input float 0.00007 instead of scientific decimal notation (7e-5), hope this helps

**Comment by codemonkeyno1** [comment]
@DoctorSlimm I tried, but same result.
exchange.create_order(symbol='SHIB/USDT',type='limit',side='buy',amount=50000, price=0.00007)

I think ccxt converts the float into string format before sending anyway.
