### ISSUE TITLE
FTX watchOrders returns only 'closed' orders 

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#10366]
Why FTX `watchOrders` returns only orders with status `closed`, skipping `open` orders? For Binance work fine.

- OS: Debian (Docker)
- Programming Language version: JS
- CCXT version: Pro 0.7.25

```
async watch() {
   while (true) {
    try {
        const exchange = new ccxt.ftx({apiKey: '...', secret: '...'});
        const orders = await exchange.watchOrders();
        let order = orders.shift();
  
        console.log(order.status); // always 'closed' in FTX case.

    }
    catch (e) {
      console.error(e);
    }
 }
}

watch();
```

**Comment by pietrodn** [comment]
Try specifying `newUpdates: true` in the client initialization options, or alternatively check the whole returned array, not just the first element.
If you don't use `newUpdates`, `watchOrders()` will return the whole cached list of orders every time. See the [manual](https://ccxt.readthedocs.io/en/latest/ccxt.pro.manual.html#newupdates-mode) for details.

On our systems, with `newUpdates`, `watchOrders()` is working fine in production and catches open orders as well. We use Python however.

**Comment by wunderb1t** [comment]
@pietrodn Thank you for your contribution! Unfortunately solution with `newUpdates` not working for us. It is very strange that  it works for you.  Inside of `ftx.js` code I have put  log in `handleMessage` (from socket) method and there is no still  order with status `open` - only `closed`. 

Additionally, in FTX docs there are no examples with status `open`. You  for sure receive that status?

**Comment by pietrodn** [comment]
Yes, we have an integration test specifically to test `watch_orders()` and we receive confirmations of `OPEN` limit orders when trading in production.

**Comment by pietrodn** [comment]
I just tried this script:
```js
"use strict";

const ccxtpro      = require ('../../ccxt.pro.js');

async function main () {
    const ftx         = new ccxtpro.ftx ({
        'apiKey': apiKey,
        'secret': apiSecret,
        "headers": {"FTX-SUBACCOUNT": subaccount},
        'enableRateLimit': true,
    });

    while(true) {
        var orders = await ftx.watchOrders();
        console.log(orders);
    }
}

main ();
```

And tried opening and canceling a limit order. This is the output

```
ArrayCacheBySymbolById(1) [
  {
    info: {
      id: 92683589654,
      clientId: null,
      market: 'BTC-PERP',
      type: 'limit',
      side: 'buy',
      price: 50000,
      size: 0.001,
      status: 'new',
      filledSize: 0,
      remainingSize: 0.001,
      reduceOnly: false,
      liquidation: false,
      avgFillPrice: null,
      postOnly: true,
      ioc: false,
      createdAt: '2021-11-02T16:26:29.158690+00:00'
    },
    id: '92683589654',
    clientOrderId: undefined,
    timestamp: 1635870389158,
    datetime: '2021-11-02T16:26:29.158Z',
    lastTradeTimestamp: undefined,
    symbol: 'BTC-PERP',
    type: 'limit',
    timeInForce: undefined,
    postOnly: true,
    side: 'buy',
    price: 50000,
    stopPrice: undefined,
    amount: 0.001,
    cost: 0,
    average: undefined,
    filled: 0,
    remaining: 0.001,
    status: 'open',
    fee: undefined,
    trades: [],
    fees: []
  }
]
ArrayCacheBySymbolById(1) [
  {
    info: {
      id: 92683589654,
      clientId: null,
      market: 'BTC-PERP',
      type: 'limit',
      side: 'buy',
      price: 50000,
      size: 0.001,
      status: 'closed',
      filledSize: 0,
      remainingSize: 0,
      reduceOnly: false,
      liquidation: false,
      avgFillPrice: null,
      postOnly: true,
      ioc: false,
      createdAt: '2021-11-02T16:26:29.158690+00:00'
    },
    id: '92683589654',
    clientOrderId: undefined,
    timestamp: 1635870389158,
    datetime: '2021-11-02T16:26:29.158Z',
    lastTradeTimestamp: undefined,
    symbol: 'BTC-PERP',
    type: 'limit',
    timeInForce: undefined,
    postOnly: true,
    side: 'buy',
    price: 50000,
    stopPrice: undefined,
    amount: 0.001,
    cost: 0,
    average: undefined,
    filled: 0,
    remaining: 0.001,
    status: 'canceled',
    fee: undefined,
    trades: [],
    fees: []
  }
]
```

**Comment by wunderb1t** [comment]
The situation is cleared up, FTX returns the last order status in it's system, i.e. for the market and the limit order, which is instantly executed, the last status will be `closed`. 

Binance for example always returns `open` status even on market order.
