### ISSUE TITLE
[okex] Support `watchMyTrades()` in OKEx client

### ISSUE THREAD

**Issue by pietrodn** [ccxt/ccxt#10367]
This is a feature request to implement the `watchMyTrades()` API in CCXT Pro for the `okex` client.

OKEx API v5 exposes trade data via WebSocket in the [order channel](https://www.okex.com/docs-v5/en/#websocket-api-private-channel-order-channel) (the same already listened to by `watchOrders`).

A possible implementation idea would be to do exactly how it's done in CCXT Pro for `binance`: on every order update on the order channel, call `handleMyTrade()` and parse any fills, returning them to `watchMyTrades()`.
A large part of the `parseTrade()` logic can be re-used.

**Comment by ttodua** [comment]
late reply, this was implemented in the past. topic closed.
