### ISSUE TITLE
Symbols data not available for Binance Exchange

### ISSUE THREAD

**Issue by neothegod75** [ccxt/ccxt#10387]
Below symbols are not available from Binance. These are perpetual future contracts. Please add support for them. 

DEFIUSDT
SANDUSDT
1000SHIBUSDT
BTCDOMUSDT
1000XECUSDT

- OS: Windows 10
- Programming Language version: Python 3.9.6. 64 bit
- CCXT version: 1.59.61

```

**Comment by kroitor** [comment]
```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binanceusdm()
markets = exchange.load_markets()
print(exchange.market('DEFI/USDT'))
print(exchange.market('SAND/USDT'))
print(exchange.market('1000SHIB/USDT'))
print(exchange.market('BTCDOM/USDT'))
print(exchange.market('1000XEC/USDT'))
```

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

Hope that answers your question. Let us know if not.
