### ISSUE TITLE
out of the box error about ololog missing

### ISSUE THREAD

**Issue by goleary91** [ccxt/ccxt#1038]
![image](https://user-images.githubusercontent.com/2343700/34508843-e3408a7a-eff8-11e7-90a3-1caaa258db98.png)

- OS: windows 10
- Programming Language: JS
- CCXT version: 1.10.545

```
var ccxt = require('ccxt');

console.log(ccxt.exchanges);
```

**Comment by kroitor** [comment]
@goleary91 that's a debug leftover, will be fixed in 5-10 minutes in the upcoming version 1.10.546. Thx for reporting.
