### ISSUE TITLE
Deribit

### ISSUE THREAD

**Issue by michaelmmw** [ccxt/ccxt#10392]
Hey, 

It seems that there is no way to switch the deribit API to testnet.
Did I miss something and there is a way to switch to the testnet? 

Thanks a lot.

**Comment by kroitor** [comment]
@michaelmmw hi! What have you tried to this point?

- https://github.com/ccxt/ccxt/wiki/Manual#testnets-and-sandbox-environments

**Comment by kroitor** [comment]
@michaelmmw you can do that with the `set_sandbox_mode(True)` method, as described in the CCXT Manual:

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.deribit({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
})
exchange.set_sandbox_mode(True)

# your code here...
```

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/Manual#testnets-and-sandbox-environments

We would highly recommend reading the entire Manual from top to bottom – it will save your time.

Hope that helps, let us know if not.

**Comment by michaelmmw** [comment]
> @michaelmmw you can do that with the `set_sandbox_mode(True)` method, as described in the CCXT Manual:
> 
> ```python
> import ccxt
> print('CCXT Version:', ccxt.__version__)
> exchange = ccxt.deribit({
>     'apiKey': 'YOUR_API_KEY',
>     'secret': 'YOUR_API_SECRET',
> })
> exchange.set_sandbox_mode(True)
> 
> # your code here...
> ```
> 
>  * https://github.com/ccxt/ccxt/wiki/
> * https://github.com/ccxt/ccxt/wiki/Manual
> * https://github.com/ccxt/ccxt/wiki/Manual#testnets-and-sandbox-environments
> 
> We would highly recommend reading the entire Manual from top to bottom – it will save your time.
> 
> Hope that helps, let us know if not.

Thanks a lot, really appreciate it. I was looking at the source code instead of reading the manual. I will read it.
