### ISSUE TITLE
Poloniex fetch_ohlcv does not work when you set a period 

### ISSUE THREAD

**Issue by drixie** [ccxt/ccxt#10415]
Works fine for the other exchanges I tried (Binance and Kucoin) 

- OS: MacOS Big Sur 
- Programming Language version: Python 3
- CCXT version:     print (ccxt.version)
AttributeError: module 'ccxt' has no attribute 'version'

```
response = poloniex.fetch_ohlcv("BTC/USDT", "1h")

print(response)
```

```
Traceback (most recent call last):
  File "/Volumes/Backup/Drive/devprojects/screens/test.py", line 7, in <module>
    response = poloniex.fetch_ohlcv("BTC/USDT", "1h")
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/ccxt/poloniex.py", line 272, in fetch_ohlcv
    'period': self.timeframes[timeframe],
KeyError: '1h'
```

**Comment by kroitor** [comment]
Poloniex API docs don't have the `1h` timeframe. The have this:

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/poloniex.py#L65

You can see the list of available timeframes here:

- https://docs.poloniex.com/#returnchartdata

```Python
import ccxt
from pprint import pprint
exchange = ccxt.poloniex()
pprint(exchange.timeframes)
```

Hope that answers your question.
