### ISSUE TITLE
gateio fetchOHLCV edit style

### ISSUE THREAD

**Issue by frosty00** [ccxt/ccxt#10428]
i would refactor this code:

instead of 

```
if (isMark || isIndex)
```

you can do

```
if (isMark) {
    prefix = '_mark';
} else if (isIndex)
    prefix = '_index';
}
```

_Originally posted by @frosty00 in https://github.com/ccxt/ccxt/pull/10407#discussion_r740052464_

**Comment by kroitor** [comment]
I refactored it before merging.
