### ISSUE TITLE
withdraw() method for Kucoin

### ISSUE THREAD

**Issue by wangbill66** [ccxt/ccxt#1042]
Hi, was wondering if it's possible for the withdraw() function to be implemented in the Kucoin.py file?

I was also looking at perhaps implementing a withdraw function myself from the examples of other exchanges, however I couldn't find some of the methods that are used in the withdraw functions of other exchanges. For instance, for Binance, in the withdraw function we have the method:

self.wapiPostWithdraw

However I tried looking for the entire repo for the exact same function but couldn't find it implemented anywhere.

Thanks!

**Comment by kroitor** [comment]
Hi! )

> was wondering if it's possible for the withdraw() function to be implemented

Yes)

> in the Kucoin.py file?

No ) It should be implemented in kucoin.js file, according to this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

> However I tried looking for the entire repo for the exact same function but couldn't find it implemented anywhere.

It is created in runtime when you instantiate the exchange, explained here:
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#implicit-api-methods

I'm closing this for now as a duplicate, if you don't mind mind. Let us know if you have any other questions.

**Comment by wangbill66** [comment]
Thanks for the swift response!

So I see that withdraw is one of the private POST methods, but I'm not exactly sure how to call it.. (from the .js file?)

I'm playing around ccxt folder on my local machine and I tried adding a withdraw function with 

response = self.privatePostAccountCoinWithdrawApply(self.extend({
            'coin': currency,
            'amount': amount,
            'address': address,
        }, params))

but I'm getting a verification error, as outlined below:

Traceback (most recent call last):
  File "/Users/Bill/anaconda3/lib/python3.5/site-packages/ccxt-1.10.508-py3.5.egg/ccxt/base/exchange.py", line 345, in fetch_requests
  File "/Users/Bill/anaconda3/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error:  for url: https://api.kucoin.com/v1/account/LTC/withdraw/apply

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 74, in <module>
    ku_client.withdraw('LTC', 0.00999, gdax_ltc_address)
  File "/Users/Bill/anaconda3/lib/python3.5/site-packages/ccxt-1.10.508-py3.5.egg/ccxt/kucoin.py", line 479, in withdraw
  File "/Users/Bill/anaconda3/lib/python3.5/site-packages/ccxt-1.10.508-py3.5.egg/ccxt/kucoin.py", line 471, in request
  File "/Users/Bill/anaconda3/lib/python3.5/site-packages/ccxt-1.10.508-py3.5.egg/ccxt/base/exchange.py", line 290, in fetch2
  File "/Users/Bill/anaconda3/lib/python3.5/site-packages/ccxt-1.10.508-py3.5.egg/ccxt/base/exchange.py", line 357, in fetch_requests
  File "/Users/Bill/anaconda3/lib/python3.5/site-packages/ccxt-1.10.508-py3.5.egg/ccxt/kucoin.py", line 465, in handle_errors
ccxt.base.errors.AuthenticationError: kucoin {"msg":"Signature verification failed","success":false,"timestamp":1514971086778,"code":"UNAUTH"}

Any help would be greatly appreciated!

**Comment by kroitor** [comment]
@wangbill66 can you update ccxt to most recent version 1.10.552 and retry the same call to `privatePostAccountCoinWithdrawApply` once again?

**Comment by wangbill66** [comment]
Ok, that seemed to have worked! Thanks so much for your help! :) 

Just one quick question: sometimes when I get an error, the error msg is in hex form. Just wondering how to decode that?

Traceback (most recent call last):
  File "bot.py", line 76, in <module>
    ku_client.withdraw('BTC', 0.001, gdax_btc_address)
  File "/Users/Bill/anaconda3/lib/python3.5/site-packages/ccxt-1.10.552-py3.5.egg/ccxt/kucoin.py", line 487, in withdraw
    }
  File "/Users/Bill/anaconda3/lib/python3.5/site-packages/ccxt-1.10.552-py3.5.egg/ccxt/kucoin.py", line 478, in request
    'amount': amount,
  File "/Users/Bill/anaconda3/lib/python3.5/site-packages/ccxt-1.10.552-py3.5.egg/ccxt/kucoin.py", line 467, in throw_exception_or_error_code
    else:
ccxt.base.errors.ExchangeError: kucoin {"data":null,"msg":"\u6700\u5c0f\u8f6c\u51fa\u6570\u91cf\u4e3a:0.002","timestamp":1514975512839,"code":"ERROR","success":false}

**Comment by kroitor** [comment]
> Just wondering how to decode that?

```Python
>>> print('\u6700\u5c0f\u8f6c\u51fa\u6570\u91cf\u4e3a:0.002'.decode('unicode-escape'))
最小转出数量为:0.002
>>> 
```

**Comment by wangbill66** [comment]
Cool thanks! :)

**Comment by MiguelCurado** [comment]
Why does withdraw() works for binance but not for kucoin? 
    
    code = 'ADA'
    amount = 100
    deposit = binance.fetchDepositAddress(code)
    withdrawal = kucoin.withdraw(code, amount, deposit['address'],deposit['network'])

**Comment by kroitor** [comment]
> Why does withdraw() works for binance but not for kucoin? 
> 
> code = 'ADA'
> amount = 100
> deposit = binance.fetchDepositAddress(code)
> withdrawal = kucoin.withdraw(code, amount, deposit['address'],deposit['network'])

the last parameter in your code is not the network, it’s a withdraw tag, the network is sent via the params-overrides, see the signature of the withdraw method here:

https://github.com/ccxt/ccxt/blob/master/python/ccxt/kucoin.py#L2085

**Comment by MiguelCurado** [comment]
Hey Igor @kroitor! Many thanks for the super fast response!
I am not being able to understand how to solve it. If you could give me the exemple to withdraw ADA from Kucoin (trading account) to binance would be perfect. 
1) What should I put in "self" ?
2) There is no "Tag" for ADA for exemple, should I leave it like "Tag=none"?
3) Should I put the 'Network' inside the params? (params = {'network':deposit['network'}])?

def withdraw(self, code, amount, address, tag=None, params={}):
:param dict params: extra parameters specific to the kucoin api endpoint

**Comment by kroitor** [comment]
@MiguelCurado hey! 
Yep, everything correct, in Python you skip the self argument by Python conventions, and supply tag=None with params={‘network’:deposit[‘network’]}. In fact, the network param override is not always necessary. If that does not work, please enable verbose mode after loading the markets and paste your verbose output:

```Python

Why does withdraw() works for binance but not for kucoin? 

code = 'ADA'
amount = 100
deposit = binance.fetchDepositAddress(code)
kucoin.load_markets()
kucoin.verbose = True # enable verbose mode after loading the markets
tag = None

# then try
withdrawal = kucoin.withdraw(code, amount, deposit['address'],tag,{‘network’:deposit['network']})

# or

withdrawal = kucoin.withdraw(code, amount, deposit['address'])
```

**Comment by MiguelCurado** [comment]
Thanks again!  It is working now. Without remembering, I had enabled "withdraw to API address book". Since this address was not on my white list, it was not working. My bad. Thanks Igor! More people like you in this world, please.

**Comment by kroitor** [comment]
@MiguelCurado good to know you figured it out, thanks for your feedback!
