### ISSUE TITLE
livecoin: currency issues

### ISSUE THREAD

**Issue by Deathamns** [ccxt/ccxt#1043]
1.) `USD`, `EUR`, `RUR` fiat currencies are not listed in [coinInfo](https://github.com/ccxt/ccxt/blob/master/js/livecoin.js#L131), so `exchange.currency(code)` will always throw, however `livecoin` has markets for these currencies.

2.) `livecoin` has both `BCH` (Bitcoin Cash) and `BCC` (BitConnect), but `BCC` is lost because of [commonCurrencyCode](https://github.com/ccxt/ccxt/blob/master/js/livecoin.js#L140).

```js
await exchange.loadMarkets();
console.log(exchange.currency('USD'));
// console.log(exchange.currency('EUR'));
// console.log(exchange.currency('RUR'));
// console.log(exchange.currency('BCC'));
```

**Comment by kroitor** [comment]
Thanks for reporting, will fix shortly.
