### ISSUE TITLE
ByBit Close Position

### ISSUE THREAD

**Issue by mhd-adam** [ccxt/ccxt#10439]
- OS: MacOs
- Programming Language version: Python 3.9.4
- CCXT version: 1.60.9

```
symbol = 'SOLUSDT'
trade_res = exchange.create_order(symbol, amount=1, type='Market', side='Buy')
```

The above snippet buys 1 SOL against USDT. When I try to close the position by placing a sell order, I see that ByBit placed another Short position on SOL without closing the Long one (2 positions appear in the console)

How do I close a current open position on ByBit using ccxt?

**Comment by elitwilliams** [comment]
You need to set the `reduce_only` param to `True` to place a closing order on Bybit. To my knowledge there is unfortunately no way to set this as the default behavior on Bybit, and you will need to track your position on your end or use a try/except to catch and re-place an order as opening if a closing order attempt fails, but of course this will count as 2 API requests.

```
symbol = 'SOLUSDT'
trade_res = exchange.create_order(symbol, amount=1, type='Market', side='Buy', params={"reduce_only": True})
```

**Comment by mhd-adam** [comment]
It worked for me! Thank you!
