### ISSUE TITLE
exchange.parseNumber rounding problem

### ISSUE THREAD

**Issue by krychla1** [ccxt/ccxt#10459]
Dear @kroitor,
exchange.parseNumber has problem with decimals. Is there any possibility to bypass the parseNumber method in fetchBalances? Or correct it internally? It is very very important to be precise in this context.
Thanks.

- OS: linux/windows
- Programming Language version: nodejs
- CCXT version: latest

```
console.log(exchange.parseNumber("284578000.00000004"));
```

```
284578000.00000006
```

**Comment by frosty00** [comment]
```
parseFloat ("284578000.00000004")
```

this is just a side effect of floating point arithmetic

if you would like to parse numbers as strings in your code you can do the following

```
exchange.number = String
```

**Comment by kroitor** [comment]
@krychla1 hi! You change the `exchange.number` property to `String` as noted by @frosty00.  Let us know if the above does not help. 

I'd also recommend checking this link: https://0.30000000000000004.com

We are moving towards string-based precise number representations throughout the lib, actually made quite some progress on that over the past weeks.

Feel free to reopen this issue or just ask further questions if any.

Related:

- https://github.com/ccxt/ccxt/issues/522
- https://github.com/ccxt/ccxt/pulls?q=safeOrder2+is%3Apr+is%3Aclosed

**Comment by krychla1** [comment]
@frosty00 thank you.
It helps.. a bit until next problem arrise. Is it possible to bypass parseFloat problems accross other parts of ccxt as well? e.g. I am not able to perform a withdrawal because of this part of ccxt withdraw function, which messes up the amount.
```
const request = {
            'currency': currency['id'],
            'amount': parseFloat (amount),
            'address': address,
        };
```

> We are moving towards string-based precise number representations throughout the lib, actually made quite some progress on that over the past weeks.

When? From my experience it is essential to use kind of safeMath or BigNumber libs in sensitive mathematical operations

**Comment by kroitor** [comment]
@krychla1 

>  Is it possible to bypass parseFloat problems accross other parts of ccxt as well?

Some exchanges will require decimal numbers in JSON. An override to this would be to preformat your amount first, depending on which exchange it is:

```JavaScript
const amount = exchange.currencyToPrecision (code, '284578000.00000004')
console.log (parseFloat (amount))
const response = await exchange.withdraw (code, amount, address, tag, params)
```

**Comment by krychla1** [comment]
I see. I will take care of that in my code then.  Most probably by comparing parseFloat with valid number and create kind of rounding logic if it doesn't equal.
Thank  you.

**Comment by kroitor** [comment]
@krychla1 a quick question – which exchange is it?

**Comment by krychla1** [comment]
hitbtc
