### ISSUE TITLE
`Api Signature check failed (unknown).` when placing new order on Huobipro

### ISSUE THREAD

**Issue by mattiaz9** [ccxt/ccxt#10476]
I get the following response when I try to create a new order on Huobipro: 
```
{
  "status": "error",
  "err-code": "api-signature-check-failed",
  "err-msg": "Api Signature check failed (unknown).",
  "data": null
}
```

- OS: macOS 12
- Programming Language version: Javascript
- CCXT version: 1.60.36

Code example:
```
client.createOrder('BOX/BTC', 'limit', 'sell', 1000, 0.000000039)
```

The request data is the following:
```
{
"account-id":"xxxxxxxxxx",
"symbol":"boxbtc",
"type":"sell-limit",
"client-order-id":"xxxxxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxxxxxxx",
"amount":"1000",
"price":"0.000000039"
}
```

Am I doing something wrong?

**Comment by kroitor** [comment]
@mattiaz9 does fetchBalance work for you?

**Comment by mattiaz9** [comment]
@kroitor yes it works

**Comment by mattiaz9** [comment]
I also get the same error when I set `fetchOpenOrdersMethod` to `fetch_open_orders_v2`.

The reason I set the v2 is because the lib throws an error if the symbol is missing, but it shouldn't I think.
According the huobi documentation the symbol in the v1 method is optional:
https://huobiapi.github.io/docs/spot/v1/en/#get-all-open-orders

**Comment by kroitor** [comment]
@mattiaz9 will get this resolved asap, thx!

**Comment by mattiaz9** [comment]
@kroitor any update about this?

**Comment by kroitor** [comment]
@mattiaz9 do you have this issue with the most recent version of Huobi ?

**Comment by mattiaz9** [comment]
Ok now it's working, thank you!
