### ISSUE TITLE
[HitBTC3] FetchOrderbook doesn't use "limit" parameter

### ISSUE THREAD

**Issue by krychla1** [ccxt/ccxt#10480]
Hi again :)
According to https://api.hitbtc.com/  hitbtc v3 doesn't use the "limit" parameter for its orderbooks. It uses depth instead.

e.g. hitbtc3.js line 912:
```
request['limit'] = limit;
```
should be 
```
request['depth'] = limit;
```

This is just an example, there might be more.
Please take a look.

**Comment by frosty00** [comment]
thx will submit a fix
