### ISSUE TITLE
FTX 30m timeframe (Python)

### ISSUE THREAD

**Issue by assa79** [ccxt/ccxt#10488]
The api for ftx does not contain a 30m timeframe . Is it possible to add it? (CCXT version 1.59.75)

**Comment by kroitor** [comment]
> The api for ftx does not contain a 30m timeframe . Is it possible to add it? (CCXT version 1.59.75)

No, because the exchange API does not support 30m timeframes:

- https://docs.ftx.com/#get-trades
- https://github.com/ccxt/ccxt/issues/9135#issuecomment-832393218
