### ISSUE TITLE
Binance Futures Invalid API-key, IP, or permissions for action

### ISSUE THREAD

**Issue by israel-gonzalezmedina** [ccxt/ccxt#10487]
Hi I can not connect to the binance's testnet. 

- OS: Ubuntu 20.04
- Programming Language version: Javascript Node js
- CCXT version: 1.60.10

```
'use strict';
const ccxt = require('ccxt');

(async function () {
    console.log(ccxt.version)
    const exchange = new ccxt.binance({
        apiKey: "XXXXXXXXXXXXXXXXXXX",
        secret: "XXXXXXXXXXXXXXXXXXXXXXXX",
        verbose: true,
        defaultType: 'future'
    })
    exchange.setSandboxMode(true)
    console.log(exchange.requiredCredentials) // prints required credentials
    try {
        exchange.checkRequiredCredentials() // throw AuthenticationError
        console.log(exchange.id)
        console.log(exchange.id, await exchange.fetchBalance())
    } catch (error) {
        console.log(error)
    }
})();

```

```
{"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
```

**Comment by kroitor** [comment]
@israel-gonzalezmedina Binance futures require a standalone keypair for the testnet: 

- https://testnet.binancefuture.com/

<img width="1680" alt="Screenshot 2021-11-05 at 19 27 27" src="https://user-images.githubusercontent.com/1294454/140544908-9d48eebe-ef3a-4510-b6f1-687c0d1827ad.png">

Let us know if that does not answer your question.

**Comment by israel-gonzalezmedina** [comment]
yes... I was only misusing the api. Thanks
