### ISSUE TITLE
kucoin Error on line 851 AuthenticationError kucoin KC-API-KEY not exist

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#10498]
I tried older version of ccxt which i have installed on another server, same API key doesnt work. But fetch_positions doesnt work.

so I tried new version of ccxt now i get this no matter what API key I try:

Error on line 851 AuthenticationError kucoin KC-API-KEY not exist

whats going on?

**Comment by adamrg73** [comment]
with verbose on I am noticing its trying to use the futures endpoint..dont understand why.


Response: GET https://api-futures.kucoin.com/api/v1/positions 401 {'Date': 'Sat, 06 Nov 2021 03:45:34 GMT', 'Content-Type': 'application/json', 'Content-Length': '47', 'Connection': 'keep-alive', 'Set-Cookie': 'AWSALB=AzpN4P/tfYargje1ARlk/uPqIXbWiIZaBU1lccZC31VoEeLLOZe88UWycwPBomm9xbM9Z3wUuCVBfEyUIc+s/YfZEfms0RUX2QrHQ3VSmI2VTvxip3YYYrJm4CRj; Expires=Sat, 13 Nov 2021 03:45:34 GMT; Path=/, AWSALBCORS=AzpN4P/tfYargje1ARlk/uPqIXbWiIZaBU1lccZC31VoEeLLOZe88UWycwPBomm9xbM9Z3wUuCVBfEyUIc+s/YfZEfms0RUX2QrHQ3VSmI2VTvxip3YYYrJm4CRj; Expires=Sat, 13 Nov 2021 03:45:34 GMT; Path=/; SameSite=None; Secure, __cfruid=4a2e6a54c61d6375d7f28329c4a7d53d1f1d1400-1636170334; path=/; domain=.kucoin.com; HttpOnly; Secure; SameSite=None', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '6a9b5467dcdb1967-EWR'} {"code":"400003","msg":"KC-API-KEY not exists"}
Error on line 855 AuthenticationError kucoin KC-API-KEY n

**Comment by kroitor** [comment]
@adamrg73 kucoin's fetchPositions works with futures, and you need a standalone key for it.

**Comment by kroitor** [comment]
Let us know if the above does not answer your question. Feel free to reopen this issue or just ask further questions if any.
