### ISSUE TITLE
Min_Size inconsistencies

### ISSUE THREAD

**Issue by mattou78400** [ccxt/ccxt#10503]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

```
handler = ccxt.ftx(keys)
handler.create_limit_buy_order('BTC-PERP', 0.00048, 60000, {"postOnly": True, 'reduceOnly' : True})

```

```
returns {"success":false,"error":"Size too small for provide"}
```

The minimum size on FTX is 0.0001 btc for BTC-PERP

It happens to me on many pairs...

![image](https://user-images.githubusercontent.com/39678117/140603672-c5756def-9b68-4c36-82ac-e06d8ab76a86.png)

How could I work around this limitation?

Thanks!

**Comment by kroitor** [comment]
Check market precision and limits:

- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

```Python
import ccxt
exchange = ccxt.ftx()
markets = exchange.load_markets()
market = exchange.market('BTC-PERP')
pprint(market)
print('-----------------------------------------')
pprint(market['limits'])
print('-----------------------------------------')
pprint(market['precision'])
print('-----------------------------------------')
```

Let us know if the above does not answer your question.

**Comment by mattou78400** [comment]
I checked already, and it's correctly reported 

![image](https://user-images.githubusercontent.com/39678117/140604381-5fd1eb53-268a-42c9-98ed-d8b0f4a729d2.png)

But the check within the create_order method doesn't seem to check..

**Comment by kroitor** [comment]
@mattou78400 please, paste your verbose log:

```Python
handler = ccxt.ftx(keys)
handler.load_markets()
handler.verbose = True
handler.create_limit_buy_order('BTC-PERP', 0.00048, 60000, {"postOnly": True, 'reduceOnly' : True})
```

**Comment by mattou78400** [comment]
Request: POST https://ftx.com/api/orders {'Content-Type': 'application/json', 'FTX-KEY': 'XXX', 'FTX-TS': '1636199017543', 'FTX-SIGN': 'XXX', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} {"market":"BTC-PERP","side":"buy","type":"limit","size":0.0004,"price":60036.0,"postOnly":true,"reduceOnly":false}

Response: POST https://ftx.com/api/orders 400 {'Date': 'Sat, 06 Nov 2021 11:43:38 GMT', 'Content-Type': 'application/json', 'Content-Length': '55', 'Connection': 'keep-alive', 'Cache-Control': 'private, max-age=0, no-cache', 'account-id': '3587515', 'Vary': 'Origin', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '6a9e10b46f0a4d84-FRA', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400'} {"success":false,"error":"Size too small for provide"}

FTX order ftx {"success":false,"error":"Size too small for provide"}

**Comment by kroitor** [comment]
@mattou78400 check FTX's return in `market['info']`:

```
~/ccxt $ node examples/js/cli ftx market BTC-PERP
2021-11-06T11:46:55.227Z
Node.js: v14.15.4
CCXT v1.60.53
ftx.market (BTC-PERP)
{     limits: {   amount: { min: 0.0001, max: undefined },
                   price: { min: 1, max: undefined },
                    cost: { min: undefined, max: undefined },
                leverage: { max: 20 }                         },
   precision: { amount: 0.0001, price: 1 },
   tierBased:    true,
  percentage:    true,
       taker:    0.0007,
       maker:    0.0002,
       tiers: { taker: [ [0, 0.0007],
                         [2000000, 0.0006],
                         [5000000, 0.00055],
                         [10000000, 0.0005],
                         [25000000, 0.045],
                         [50000000, 0.0004]  ],
                maker: [ [0, 0.0002],
                         [2000000, 0.00015],
                         [5000000, 0.0001],
                         [10000000, 0.00005],
                         [25000000, 0],
                         [50000000, 0]        ] },
          id:   "BTC-PERP",
      symbol:   "BTC-PERP",
        base:   "BTC",
       quote:   "USD",
      baseId:   "BTC",
     quoteId:   "USD",
        type:   "future",
      future:    true,
        spot:    false,
      active:    true,
        info: {                  name: "BTC-PERP",
                              enabled:  true,
                             postOnly:  false,
                       priceIncrement: "1.0",
                        sizeIncrement: "0.0001",
                       minProvideSize: "0.001", <<<--------------------- HERE
                                 last: "60397.0",
                                  bid: "60387.0",
                                  ask: "60388.0",
                                price: "60388.0",
                                 type: "future",
                         baseCurrency:  null,
                        quoteCurrency:  null,
                           underlying: "BTC",
                           restricted:  false,
                highLeverageFeeExempt:  true,
                             change1h: "-0.0036463231533270636",
                            change24h: "-0.01844838515677064",
                            changeBod: "-0.010130151132675475",
                       quoteVolume24h: "2892083192.6099",
                         volumeUsd24h: "2892083192.6099"         } }
```

I've added that to reflect the minimum in CCXT 1.60.55+. The new build will arrive in ~20 minutes. Thanks for reporting!

**Comment by mattou78400** [comment]
By the way
I'm working with python (that's where I'm having the bug), and seems to happen on binance as well for example

Thanks for the quick fix! :)

**Comment by kroitor** [comment]
> I'm working with python (that's where I'm having the bug)

It's the same in all languages.

> and seems to happen on binance as well for example

Please, print out the market and the verbose output – it usually becomes obvious from there.

**Comment by kroitor** [comment]
> Also, the minProvideSize should be 0.0001 not 0.001, right?

Wrong, 0.001 – is what FTX says.

**Comment by mattou78400** [comment]
I'm seeing minProvideSize : 0.001

But on FTX, the actual min is 0.0001

Am I missunderstanding something?

**Comment by kroitor** [comment]
@mattou78400 depends on what exactly you mean under the actual min on FTX. The `info` substructure above is the FTX's info as is, untouched.

**Comment by mattou78400** [comment]
So the fact that I can only push orders >0.001 through the API and 0.0001 through the ftx front is an api limitation from their side?

thanks!

**Comment by kroitor** [comment]
@mattou78400 check this: page https://docs.ftx.com/#get-markets

<img width="1680" alt="Screenshot 2021-11-06 at 15 08 01" src="https://user-images.githubusercontent.com/1294454/140609027-1a73ce16-db3d-4a78-813a-7a911061619b.png">

**Comment by mattou78400** [comment]
Ah thank you, I missed this part

Minimum maker order size (if >10 orders per hour fall below this size)

Is there any plan to manage that by ccxt?

Thanks for your help!

**Comment by kroitor** [comment]
@mattou78400 we are investigating into it, figuring a good way of handling this aspect.

**Comment by rapmd73** [comment]
> > Also, the minProvideSize should be 0.0001 not 0.001, right?
> 
> Wrong, 0.001 – is what FTX API says.

I have run to this a few times with finance where the API and their website differ on values.

With respect to FTX, in using their application I have gotten different values for testing than what their API reports. My experience has been that the API reports slightly higher than what the actual application wants. My guess is this is probably some sort of a defensive hedge against a rapid market slips since the variance between what the API reports any application is extremely minimal.

**Comment by rapmd73** [comment]
> So the fact that I can only push orders >0.001 through the API and 0.0001 through the ftx front is an api limitation from their side?
> 
> thanks!

I believe this would seem to be the case, not just with ftx, but many exchanges. The only rationale that I can see in terms of the differences that I have actually seen through testing, is that the API has a slower channel of communication compared to what the application may use as a direct channel. I personally believe it is not something out of the ordinary that they would prioritize Communications with their own applications over third party API requests.

This type of practice is common within the market and does help promote usage of the application.

I believe a clear visual example of this is the Kraken app versus the Kraken API. The API has some very strong rate limits on it, whereas the app does not.
