### ISSUE TITLE
Check exchanges' API support for withdraw/deposit functionality

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#10508]
is there way to loop through all supported exchanges that support withdraw and deposit support through the each exchanges api?

**Comment by kroitor** [comment]
@adamrg73 yes, you use exchange meta info for that:

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
for exchange_id in ccxt.exchanges:
    try:
        exchange = getattr(ccxt, exchange_id)()
        if exchange.has['withdraw'] and exchange.has['fetchDepositAddress']:
            print(exchange.id, 'supports withdrawing and depositing')
    except Exception as e:
        print(type(e).__name__, str(e))
```

P.S. For the future, please, always include the following information:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help (which version, which programming language, code you have tried, etc – as much as possible).
