### ISSUE TITLE
Install ccxt.pro to DigitalOcean Apps

### ISSUE THREAD

**Issue by KonstantinVlasov** [ccxt/ccxt#10504]
Hi! I want to use ccxt.pro with DigigtalOcean App.  As I understand I should use .npmrc for this. But I can't figure out how to achieve this.

- OS: Ubuntu
- Programming Language version: Javascript
- CCXT version: pro

**Comment by Vibhaa5** [comment]
using digitalocean command line doctl and configuring settings to creating resource and adding ccxt.pro
