### ISSUE TITLE
x rate limit on bitMEX

### ISSUE THREAD

**Issue by ShieldTrade** [ccxt/ccxt#10509]
- OS: windows 10
- Programming Language version: Python 3.9
- CCXT version: CCXT Pro Version 0.8.13
- exchange: bitmex

According to BitMex Api documents:

" Viewing Your Request Rate Limit
On each request to the API, these headers are returned:

"x-ratelimit-limit": 120
"x-ratelimit-remaining": 118
"x-ratelimit-reset": 1489791662 "

is there a way to return those value with CCXT pro?

tx
```

**Comment by kroitor** [comment]
Hi @ShieldTrade ! Yes, you can check the value of `exchange.last_response_headers` after any request to get the last received headers. 

```Python
import ccxt

exchange = ccxt.bitmex()
markets = exchange.load_markets()
while True:
    try:
        orderbook = exchange.fetch_order_book('BTC/USD')
        print(exchange.iso8601(exchange.milliseconds()), orderbook['bids'][0], orderbook['asks'][0], {
            'x-ratelimit-limit': exchange.last_response_headers.get('x-ratelimit-limit'),
            'x-ratelimit-remaining': exchange.last_response_headers.get('x-ratelimit-remaining'),
            'x-ratelimit-reset': exchange.last_response_headers.get('x-ratelimit-reset'),
        })
    except Exception as e:
        print(type(e).__name__, str(e))
```

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

**Comment by kroitor** [comment]
@ShieldTrade we are actually in the process of switching from regular rate limiting towards weight-based rate limiting everywhere throughout all exchanges. That should make it work faster and support bursts of requests in short periods of time. Hope the above answers your question, let us know if not.

**Comment by ShieldTrade** [comment]
It might do the job 
Nevertheless when you post an order the original response you get from bitMEX is
```
Response: GET https://testnet.bitmex.com/api/v1/order?symbol=XBTEUR&filter=%7B%22open%22%3Atrue%7D 200 {'Date': 'Sun, 07 Nov 2021 13:09:19 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': 

'AWSALBTG=LXRwva+jsphajtDqhBiE+RMf5o1fPMg/v3swJAweEE9bHHopSIV8FbdKzUMN3pgzDdiXNORhJIUrI0NkmFHiMLbn7bJh2BItFE5lD/g7Xr7ntoJOYgcs1lyh8mbST2Z+crgr4o3it33YqbJQz2AsoCb7nqWHKaabuVyqSRlZDOEe; Expires=Sun, 14 Nov 2021 13:09:19 GMT; Path=/, 

AWSALBTG=LXRwva+jsphajtDqhBiE+RMf5o1fPMg/v3swJAweEE9bHHopSIV8FbdKzUMN3pgzDdiXNORhJIUrI0NkmFHiMLbn7bJh2BItFE5lD/g7Xr7ntoJOYgcs1lyh8mbST2Z+crgr4o3it33YqbJQz2AsoCb7nqWHKaabuVyqSRlZDOEe; Expires=Sun, 14 Nov 2021 13:09:19 GMT; Path=/',
 'x-ratelimit-limit': '120', 
'x-ratelimit-remaining': '119', 
'x-ratelimit-reset': '1636290560', 'X-Powered-By': 'Profit'.......,.........

{"orderID":"a06face8-a0f6-449a-a347-75194e2992a4","clOrdID":"","clOrdLinkID":"","account":376818,"symbol":"XBTEUR","side":"Buy","simpleOrderQty":null,"orderQty":100,"price":52000,"displayQty":null,"stopPx":null,"pegOffsetValue":null,"pegPriceType":"","currency":"EUR","settlCurrency":"XBt","ordType":"Limit","timeInForce":"GoodTillCancel","execInst":"","contingencyType":"","exDestination":"XBME","ordStatus":"New","triggered":"","........,"transactTime":"2021-11-07T13:09:17.839Z","timestamp":"2021-11-07T13:09:17.839Z"}]

```
and CCXT gives us the important part regarding the order starting at .`{"orderID":"a06face8-a0f6-449a-a347-`

is there a way to retrive the` x-ratelimit` from the above Response without fetching the orderbook which is expensive in terms of rate limit?

Thanks

**Comment by kroitor** [comment]
@ShieldTrade the `exchange.last_response_headers` property is populated after **every** request, not just fetchOrderBook, but also createOrder, and all other HTTP requests. You don't have to call `fetch_order_book`, if you're calling `create_order`.

**Comment by ShieldTrade** [comment]
thank you. Very fast answer as usual.
I will study this property which I missed and I will let you know if I am able to get what I need

Please let the question for a couple of days

**Comment by kroitor** [comment]
@ShieldTrade feel free to reopen it if necessary, or just ask further questions if any.
