### ISSUE TITLE
gateio fetch_order: the average is incorrect

### ISSUE THREAD

**Issue by chxxpeng** [ccxt/ccxt#10518]
- OS: macos
- Programming Language version: Python
- CCXT version: 1.60.71

```
 
```

```
Actually the (average) is equal to (cost), which is wrong.
```

**Comment by chxxpeng** [comment]
I just upgrade from 1.59.72 to 1.60.71, while version 1.59.72 seems still good.

**Comment by frosty00** [comment]
can you provide a verbose request and response of the bug

**Comment by frosty00** [comment]
#10521
