### ISSUE TITLE
How to trade BTC-Margin on Phemex Exchange

### ISSUE THREAD

**Issue by bongkook** [ccxt/ccxt#10531]
Hello.
I have a question about using the Phemex exchange.
Prior to October, if you placed an order in BTCUSD, it was placed in BTC-Margin (Inverse).
However, since USD-Margin was added in October,
When you place an order in BTCUSD, it becomes an order in USD-Margin.
How to order BTCUSD trading with BTC-Margin?

**Comment by qmata55** [comment]
try BTC/USD:BTC
