### ISSUE TITLE
How to handle exceptions in CCXT Pro?

### ISSUE THREAD

**Issue by krychla1** [ccxt/ccxt#10533]
Hi fellows!
Is there any best practice, how to handle exceptions thrown inside ccxt.pro?

I've got occasionally exception on the orderbook.cache.push (message), that I would like to dig deeper into, however I am not able to catch it.

```
TypeError: Cannot read property 'push' of undefined
    at bittrex.handleOrderBook (.../node_modules/ccxt.pro/js/bittrex.js:683:29)
    at bittrex.handleMessage (.../node_modules/ccxt.pro/js/bittrex.js:829:32)
    at WsClient.onMessage (.../node_modules/ccxt.pro/js/base/Client.js:277:14)
    at WebSocket.onMessage (.../node_modules/ccxt.pro/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (.../node_modules/ccxt.pro/node_modules/ws/lib/websocket.js:983:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (.../node_modules/ccxt.pro/node_modules/ws/lib/receiver.js:517:14)
    at Receiver.getData (.../node_modules/ccxt.pro/node_modules/ws/lib/receiver.js:435:17)
    at Receiver.startLoop (.../node_modules/ccxt.pro/node_modules/ws/lib/receiver.js:143:22)
```

My code:
I create subscription
```
    async createSubscription(market) {
        try {
            this.logger.debug(`${this.exchangeName} | createSubscription | ${market}`);
            return await this.exchange.watchOrderBook(market, this.fetchOrderBookLimit);
        } catch (e) {
            this.logger.error(`${this.exchangeName} | createSubscription | ${market} | ${e.stack}`);
        }
    }
```
I don't run endless loops, rather I leave the ccxt.pro update orderbooks on their websocket feeds in "background" and I get to the actual orderbook only if needed by:

```
return resolve(this.exchange.orderbooks[market].limit(orderBookLength));
```

Any suggestions on how to handle errors in this setup?

**Comment by kroitor** [comment]
@krychla1 hi! If possible, please paste a complete short snippet to reproduce it (remove irrelevant bits from it) – we will investigate and will fix it.

**Comment by kroitor** [comment]
@krychla1 Do you have this issue with any of these examples: https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro/js (if you put `bittrex` in there) ?

**Comment by krychla1** [comment]
Hi,
it happens 1-2 times per day on more than 100 pairs, its hard to reproduce with a snippet. 
But I will try, I need to test bittrex a lot (the connection is very unstable, it dies every 1-2hour)

**Comment by ttodua** [comment]
with promise-based functions, maybe you try `...this.exchange.watchOrderBook(market, this.fetchOrderBookLimit).catch( (err)=>{ console.log(err) });` 
Let us know if that solves your problem, or if you have any observation to share with us.

**Comment by krychla1** [comment]
Unfortunately that works only for the initial watchOrderBook function. The promise is resolved with orderBook from watchOrderBook function, however the orderBook is "live in the background" - its getting updated by its subscription. If there happens anything wrong, it isn't catched by users exception handling. I can't figure a way how to handle it, maybe it is not even possible/desired, unless trying really hard with something like this

```Javascript
process.on('uncaughtException', err => {
    logger.error(`UncaughtException: ` + err.stack)
})
```
(not advised) 

I am running several hundreds of subscriptions on several exchanges, however I face only one type of uncaught exception regularly.  The above mentioned of bittrex. Maybe we can focus rather on that. Should I create a new issue for it?

**Comment by ttodua** [comment]
I think this issue is enough as it's mostly around bittrex already. Moreover,the exception handling problem related to this issue, might be of global scope, which will need to be addresses from base I think.  I'd wait for @kroitor 's thoughts about that, as this might not be straightforward atm, and will label this issue with 'todo'.

**Comment by ttodua** [comment]
@krychla1 I will look into this issue in the upcoming days.
