### ISSUE TITLE
[Kucoin] ccxt.pro - way to check watched orderBooks

### ISSUE THREAD

**Issue by krychla1** [ccxt/ccxt#10539]
Hi fellows!

In discord I already mentioned problems with kucoins watchOrderBooks, which time to time ends with invalid orders despite the nonce being correct. It occurs again and again (only on kucoin, I haven't found discrepancies on other exchanges so far)

To debug/handle it further I would like to create kind of a checker with fetchOrderbook by rest request to compare it with the watched orderbook. How to do that? I find it quite impossible to get same nonce from rest to match actual orderbook nonce.

Thanks.

**Comment by kroitor** [comment]
@krychla1 hi!

Good question! It's tricky, but I think it can be done to a certain extent:

The first approach is to keep a configurable length of history of watched nonce/timestamp-values and trigger a reconnect when the fetched nonce/timestamp-values don't intersect with history. It will require some experiments to determine the nonce/timestamp-invalidation period.

The second approach is to introduce a checksum of the orderbook and analyze the frequencies of trades, this is even harder, cause it requires watching trades along with the orderbook.

We will think about ways of adding this feature to the base code of CCXT Pro...

**Comment by krychla1** [comment]
The second approach would be very difficult I agree. Even impossible, the trades are only a part of actions that change the orderbooks. Creation and cancelation are not part of trade feeds and can't be checked by other subscription than orderbook.

However the first one seems feasible. 
What about to keep a cache of incoming feeds with configurable length and create a function that would be the reverse of "handleOrderBookMessage" - could apply selected depth of the cached feeds to rollback the orderbook? Of course not changing the orderbook itself, rather just returning the "rollbacked" result.
This can be used as a comparison if the fetched nonce is greater than the watched nonce.

**Comment by krychla1** [comment]
Hi fellows!
Has this become completely dead, or do you intend to work this out?

**Comment by krychla1** [comment]
@kroitor

**Comment by ttodua** [comment]
late reply here, but i'll leave a note for future readers, if it'll be helpful to anyone:
- you can directly access orderbook caches with `exchange.orderbooks[symbol]`
- you can override `handleOrderBook` of any exchange, so you can create your dictionary  e.g. `myD`, where nonces will be keys, so on each trigger of `handleOrderBook` you store the orderbook object in `myD` and then use `fetchOrderBook`, which would give you fetched orderbook (with nonce)  you might be able to locate the saved orderbook in `myD` by that nonce

if there are still any issues, let us know
