### ISSUE TITLE
Can not create buy or sell order using coinex exchange

### ISSUE THREAD

**Issue by Abdulhadi77** [ccxt/ccxt#10551]
When trying to run this code 
exchange = ccxt.coinex({
    "apiKey": COINEX_API_KEY,
    "secret": COINEX_SECRET_KEY
})

exchange.create_market_buy_order('IOTX/USDT', 0.3) 
or
exchange.create_market_sell_order('IOTX/USDT', 0.3)

I get this error:

createOrder() requires the price argument with market buy orders to calculate total order cost(amount to spend), where cost = amount * price. Supply a price argument to createOrder() call if you want the cost to be calculated for you from price and amount, or, alternatively, add .options['createMarketBuyOrderRequiresPrice'] = False to supply the cost in the amount argument(the exchange-specific behaviour)")
ccxt.base.errors.InvalidOrder: coinex createOrder() requires the price argument with market buy orders to calculate total order cost(amount to spend), where cost = amount * price. Supply a price argument to createOrder() call if you want the cost to be calculated for you from price and amount, or, alternatively, add .options['createMarketBuyOrderRequiresPrice'] = False to supply the cost in the amount argument(the exchange-specific behaviour)

**Comment by Abdulhadi77** [comment]
Please note that this code works well
exchange.fetch_balance()

**Comment by kroitor** [comment]
@Abdulhadi77 please, read this section of the Manual: https://github.com/ccxt/ccxt/wiki/Manual#market-buys. Let us know if that does not answer your question.
