### ISSUE TITLE
Can trading on 400 accounts asynchronously ban my IP?

### ISSUE THREAD

**Issue by Salz0** [ccxt/ccxt#10566]
Hello!
I have read the documentation, where it is written that there may be problems with reinitiating exchange instances.

My case is such that I am developing a bot that would **trade on hundreds of accounts simultaneously**, creating a h_uge amount of exchange instances_ of different Binance accounts.

My question is, **what could go wrong**, and would the bots IP be _banned_ from such an amount of exchanges and requests?
(RateLimit enabled)

Thank you for responding!)

**Comment by frosty00** [comment]
yes, binance rate limits by ip, but they probably won't ban you but you won't be able to trade very fast

**Comment by kroitor** [comment]
@Salz0 when dealing with hundreds of pairs you will have to think scaling from the very start, spread the load across a cloud of machines to avoid bans. Hope that helps. In general, the exchanges will track your IP + apiKey for rate limits. 

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter

Let us know if the above does not answer your question.
