### ISSUE TITLE
What does edit order do

### ISSUE THREAD

**Issue by hunsnowboarder** [ccxt/ccxt#1056]
Can someone please explain what does edit order do? And how does it work (an example)?

I did not find any information about it in the manual. 

Thank you so much for this awesome tool!

**Comment by kroitor** [comment]
Some exchanges support *canceling+placing a new order* in one call (poloniex). For other exchanges that don't support that, the editOrder call will emulate it in two separate calls (cancel, then place new), effectively replacing or *editing* the order. Let me know if this answers your question.

**Comment by hunsnowboarder** [comment]
Wow, this is megacool! 
Could you please just give an example because I am having hard time to understand what args*  mean? I am not sure about the order of the arguments, and also about the exact name of the arguments? (i mean something like "new_price" and "new_volume" or just "price" and "volume"?)
Thank you in advance.

**Comment by kroitor** [comment]
This is the default implementation:

```Python
    def edit_order(self, id, symbol, *args):
        if not self.enableRateLimit:
            raise ExchangeError(self.id + ' edit_order() requires enableRateLimit = true')
        self.cancel_order(id, symbol)
        return self.create_order(symbol, *args)
```

As you can see, it accepts the id + all params from `create_order()` in the same order: 
```
def create_order(self, symbol, type, side, amount, price=None, params={}):
```

So the full ordered set of **positional** arguments for `edit_order()` is:
- id
- symbol
- type
- side
- amount
- price
- params

Does this help?

**Comment by hunsnowboarder** [comment]
Thank you so much! Of course it does. :)
Just a question out of curiosity. Why is the symbol a required parameter? The order id should definitely identify the order. I suppose this is an expectation from the exchange just for double checking the command.
Anyway thank you so much for you help! You can close this thread now!

**Comment by kroitor** [comment]
> Just a question out of curiosity. Why is the symbol a required parameter? 

Because they have separate databases with unsynchronized ids between the databases, so you can't mix one id with the other database, if you don't know the symbol.

> The order id should definitely identify the order. 

Only if all your orders in the engine use the same linear id space. But this is often not the case. 

> I suppose this is an expectation from the exchange just for double checking the command.

If you think in terms of scalability, this can make sense. Separate clusters for separate pairs and unrelated orders = no accidental interference = more reliable exchange.

**Comment by hunsnowboarder** [comment]
Thank you so much! Of course it does. :)
Just a question out of curiosity. Why is the symbol a required parameter? The order id should definitely identify the order. I suppose this is an expectation from the exchange just for double checking the command.
Anyway thank you so much for you help! You can close this thread now!

**Comment by hunsnowboarder** [comment]
Yes it does make sense! Thank you so much! Proud to become one of your backers!
