### ISSUE TITLE
Possible addition of FTX.US support?

### ISSUE THREAD

**Issue by bonetjoshua** [ccxt/ccxt#10563]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

This is NOT an issue but a suggestion:
Is it possible to extend CCXT support to FTX.US? 
```

```
Thank you
```

**Comment by kroitor** [comment]
Duplicate, FTX.us is already supported:

- https://github.com/ccxt/ccxt/issues/9941#issuecomment-913788923
- https://github.com/ccxt/ccxt/issues/7461#issuecomment-673535274
- https://github.com/ccxt/ccxt/search?q=ftx.us&type=issues
