### ISSUE TITLE
Indicate whether unified methods require a symbol or not

### ISSUE THREAD

**Issue by shnhrrsn** [ccxt/ccxt#1058]
It’d be super helpful if there was a way to tell ahead of time of `fetchOrders`, `fetchMyTrades`, etc… require a symbol parameter or not.

Some exchanges seem to have hard coded errors thrown when it’s missing, while others throw an API error.

**Comment by kroitor** [comment]
@shnhrrsn we are working on adding that feature, as well as other flags for exchange capabilities. However, it might be much safer to design you logic in a way that would always pass a symbol. Have you considered this?

**Comment by shnhrrsn** [comment]
Unfortunately, I'm actually trying to do the opposite, get full trade history in a reliable way across multiple exchanges for any symbol traded.

In my case, if I don't need a symbol it's much faster since an exchange like GDAX will happily give the full history, where as when it's required I have to loop through the pairs one by one

**Comment by kroitor** [comment]
Got it, hope to add this feature very soon.

**Comment by gbkwiatt** [comment]
That seems pretty valid still. 
Just came up across same problem, basically, I am pulling balances from binance, and at this point I don't even know what pairs someone was trading with, which means I don't even have valid symbol trade, I could loop through all possible pairs and try to get all orders user made. But that seems really wrong. 

Would be nice If can just pull all trades that were made regardless of the symbol

**Comment by kroitor** [comment]
@gbkwiatt afaik, Binance API requires a symbol for the personal trades endpoint: https://binance-docs.github.io/apidocs/spot/en/#account-trade-list-user_data

**Comment by gbkwiatt** [comment]
Yeah only just checked that, and you are right. bummer. I started making my own app so I can have better portfolio track, but seems like it can't be done better than the current apps.

**Comment by ttodua** [comment]
The reference issue for the development of that functionality is [here](https://github.com/ccxt/ccxt/issues/6772), please monitor/subscribe to that issue if you are interested in the topic.

**Comment by samgermain** [comment]
@shnhrrsn Currently you can do this by checking the docstring. If the type is `str|undefined` then the symbol is optional, if it's just `str` then the symbol is required
