### ISSUE TITLE
loadMarkets is not returning USDC/USDT pair at waves.exchange

### ISSUE THREAD

**Issue by hexdump2002** [ccxt/ccxt#10580]
- OS: MACOS
- Programming Language version: js
- CCXT version: "1.60.41"

When using ccxt with waves exchange:

`let exchange = new ccxt.wavesexchange({
            'options':{
                'defaultType': 'spot',       
            }, 
            apiKey: 'XXXX',
            secret: 'XXXX',
        });`

and trying to retrieve all markets using:

`exchange.loadMarkets();`

A bunch of markets are retrieved but USDC/USDC isn't. This pair can be found in the waves.exchange if you get in the markets tab and search it. Here the prove:

![imagen](https://user-images.githubusercontent.com/7756851/141703177-701f1e4c-3b4a-4d4d-a448-afdf4c40f6bd.png)

**Comment by ttodua** [comment]
As [WE doc](https://docs.waves.exchange/en/ccxt/) says in the 6th line of page, CCXT supports only [these tickers ](https://marketdata.wavesplatform.com/api/v1/tickers) and there is not the pair-in-question.

@kroitor  what should happen in such case?

**Comment by kroitor** [comment]
We've reached out to Wavesexchange's team on this question and the answer is:

> Good day! We do not allow any pair to be selected due to the fact that it erodes liquidity. Thanks for your feedback, maybe we will add this pair in the near future.

<img width="1248" alt="Screenshot 2021-12-11 at 01 13 01" src="https://user-images.githubusercontent.com/1294454/145648093-e3c2f532-0bd0-4aa1-a7ad-7e14b917e0c5.png">

**Comment by kroitor** [comment]
I guess, from the above it follows that we should ignore USDC/USDT for wavesexchange, since we don't have any information about it from the API.
