### ISSUE TITLE
Allow to pass TraceConfigs to aiohttp ClientSession

### ISSUE THREAD

**Issue by pietrodn** [ccxt/ccxt#10585]
In the Python client, it would be nice to let users pass [`TraceConfig` objects](https://docs.aiohttp.org/en/stable/client_advanced.html#aiohttp-client-tracing) to the `aiohttp.ClientSession` object where it is initialized (in the `BaseExchange.open()`) method.

We currently use two trace configurations to:
1. Monitor all CCXT's HTTP calls with Prometheus and display them in a Grafana dashboard
2. Log every request and response to external storage for future analyses.

Our current workaround is to override the `open()` method and pass the trace config objects in there, but we found this to be quite fragile.

An implementation idea is to introduce a new client configuration attribute (e.g., `self.options["aiohttp_trace_configs"]`), defaulting to an empty list, that can be passed at client initialization time.

**Comment by ttodua** [comment]
Have you seen something like this:


```
import ccxt.async_support as ccxt
import aiohttp
import aiohttp_socks

async def test():

    connector = aiohttp_socks.ProxyConnector.from_url('socks5://user:password@127.0.0.1:1080')
    session = aiohttp.ClientSession(connector=connector)

    exchange = ccxt.binance({
        'session': session,
        # ...
    })
     ...
    await session.close()  # don't forget to close the session
     ...
```

or it doesn't meet your expectations?

**Comment by pietrodn** [comment]
@ttodua thanks, it is working 🙂
