### ISSUE TITLE
[PHP] Timestamp for this request is outside of the recvWindow.

### ISSUE THREAD

**Issue by Franjey** [ccxt/ccxt#1059]
Hi everyone.

I am trying to run the following (PHP):
`$orders = $bac->getOpenOrders(['symbol' => 'XVGETH', 'timestamp' => time()]);`

getOpenOrders is a method of this class: https://larislackers.github.io/php-binance/class-Larislackers.BinanceApi.BinanceApiContainer.html

My internet is sync (I believe, using windows 10) with the server: time.nist.gov

![image](https://user-images.githubusercontent.com/11093607/34545136-89d035f4-f0c9-11e7-96ff-8ab8a3e23c6e.png)

Edit: This is the full error message 

> Fatal error: Uncaught Larislackers\BinanceApi\Exception\BinanceApiException: [-1021]: Timestamp for this request is outside of the recvWindow. thrown in C:\Users\Francisco\vendor\larislackers\php-binance\src\BinanceApiContainer.php on line 568

If anyone can assist me, I will really appreciate it. Thank you.

**Comment by kroitor** [comment]
@Franjey which version of ccxt? Please update to most recent version of it and retry. I'd suggest to move this discussion here: https://github.com/ccxt/ccxt/issues/936. Closing this as a duplicate for now, if you don't mind.
