### ISSUE TITLE
middleman?Agent?Broker？

### ISSUE THREAD

**Issue by monk-after-90s** [ccxt/ccxt#10608]
Hello, may you set your account to be the middleman or agent or broker of the account of a ccxt user, to gain commission?

**Comment by kroitor** [comment]
@monk-after-90s hi! CCXT itself does not act as an intermediary, it is a software that you use to talk to the exchanges directly. You can configure it how you want, and it will depend on your referral links and on your partnerships with each specific exchange. Hope that answers your question, let us know if not.
