### ISSUE TITLE
insufficent margin issue when creating order

### ISSUE THREAD

**Issue by websharp950223** [ccxt/ccxt#10602]
Hello. Everyone
Thanks for making ccxt lib.
it is good to use in crypto.
--------------------------------------
I got some issues while making trading bot using  your library
My ccxt version is 1.59.30
I have 0.00785811 BTC in my COIN-Ⓜ futures account.
I am trying to create order BTC->USDT
These are my codes.
Part1.
config exchange
exchange = getattr(ccxt, exchange_id)({
  'apiKey': api_key,
  'secret': secret,
  'timeout': 10000,
  'enableRateLimit': True,
  'hedgeMode': True,
  'options': {
    "defaultMode": "future",
    "defaultType": "future", #margin, future, delivery
    "adjustForTimeDifference": True, 
    "recvWindow": 10000,
    "warnOnFetchOpenOrdersWithoutSymbol": False,
    "createMarketBuyOrderRequiresPrice": False
  }
})

Part2.
get balances
balances  = exchange.dapiPrivate_get_balance()

Part3.
Place limit Sell Order
symbol = "BTC/USDT"
order = exchange.create_limit_sell_order(
         symbol=symbol,
         amount=0.001,
         price=63000
 )

This is verbose when trying to order
Request: GET https://fapi.binance.com/fapi/v1/time {'User-Agent': 'python-requests/2.26.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://fapi.binance.com/fapi/v1/time 200 {'Content-Type': 'application/json', 'Content-Length': '28', 'Connection': 'keep-alive', 'Date': 'Tue, 16 Nov 2021 10:31:32 GMT', 'Server': 'Tengine', 'X-MBX-USED-WEIGHT-1M': '1', 'x-response-time': '0ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': '*', 'Content-Security-Policy': "default-src 'self'", 'cache-control': 'no-cache, no-store, must-revalidate', 'expires': '0', 'pragma': 'no-cache', 'strict-transport-security': 'max-age=31536000; includeSubdomains', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 f268a165a18929fd0a24a3189fbd16b3.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'SEA19-C3', 'X-Amz-Cf-Id': 'SS3UiAHiFyZ3SgMjXSv3xNpPLCM6AzB3IowcJMUyPk1tyP5yDLR__w=='} {"serverTime":1637058692114}

Request: POST https://fapi.binance.com/fapi/v1/order {'X-MBX-APIKEY': 'ddddddddddddddddddddddddddddddddddddddddddd', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.26.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1637058692137&recvWindow=10000&symbol=BTCUSDT&type=LIMIT&side=SELL&newClientOrderId=x-xcKtGhcu342c64fa0a0922bec619e2&newOrderRespType=RESULT&quantity=0.001&price=63000&timeInForce=GTC&signature=a011ef7555ad92c526dc444e076ef32d9fb80f6056009c4e12c8bb679a7113e6

Response: POST https://fapi.binance.com/fapi/v1/order 400 {'Content-Type': 'application/json', 'Content-Length': '46', 'Connection': 'keep-alive', 'Date': 'Tue, 16 Nov 2021 10:31:33 GMT', 'Server': 'Tengine', 
'X-MBX-USED-WEIGHT-1M': '1', 'X-MBX-ORDER-COUNT-10S': '0', 'X-MBX-ORDER-COUNT-1M': '1', 'x-response-time': '6ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 f268a165a18929fd0a24a3189fbd16b3.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'SEA19-C3', 'X-Amz-Cf-Id': 'V-fUxMmHVQvWpbSXm5bNmZw30jkslhf4HZKIThY4ogAlFuhdKnWONQ=='} {"code":-2019,"msg":"Margin is insufficient."}
![balances](https://user-images.githubusercontent.com/93001796/141969283-01f05c31-ede3-44da-af71-7df833bf7e7b.png)
![insufficientMargin](https://user-images.githubusercontent.com/93001796/141969332-6220f5b7-6016-4686-896a-0575d8843cb6.png)

**Comment by sunshinelancer828** [comment]
this is good question.
I have too same question.
please anser.

**Comment by websharp950223** [comment]
Please let me know about the solution

**Comment by samgermain** [comment]
@websharp950223 

It looks like you're using Binance, and you mentioned the balance is in your coin-m account but you initialize your exchange object with

```
exchange = getattr(ccxt, exchange_id)({
    ...
    'options': {
        "defaultType": "future", #margin, future, delivery
         ...
    }
})
```

For binance Coin-m futures, you need to set `defaultType: "delivery"`

```
exchange = getattr(ccxt, exchange_id)({
    ...
    'options': {
        "defaultType": "delivery",
         ...
    }
})
```

-------------------------------

Also, if you set exchange_id to `binancecoinm`, then there's no need to include `"defaultType": "delivery",`, it will be set automatically

**Comment by websharp950223** [comment]
Thanks, Samgermain
But I already set defaultType to delivery as you can see in my code
But it says insufficent margent.
Is it necessary for me to set other options?
Please let me know
Thanks

**Comment by samgermain** [comment]
> Thanks, Samgermain But I already set defaultType to delivery as you can see in my code But it says insufficent margent. Is it necessary for me to set other options? Please let me know Thanks
From your code I can see `defaultType: future`

```
config exchange
exchange = getattr(ccxt, exchange_id)({
    'apiKey': api_key,
    'secret': secret,
    'timeout': 10000,
    'enableRateLimit': True,
    'hedgeMode': True,
    'options': {
        "defaultMode": "future",
        "defaultType": "future", #margin, future, delivery
        "adjustForTimeDifference": True,
        "recvWindow": 10000,
        "warnOnFetchOpenOrdersWithoutSymbol": False,
        "createMarketBuyOrderRequiresPrice": False
    }
})
```

I also see you accessing the `dapi` endpoints for `balances = exchange.dapiPrivate_get_balance()` but your orders are against the `fapi` endpoints

```
Request: POST https://fapi.binance.com/fapi/v1/order {'X-MBX-APIKEY': 'ddddddddddddddddddddddddddddddddddddddddddd', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.26.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1637058692137&recvWindow=10000&symbol=BTCUSDT&type=LIMIT&side=SELL&newClientOrderId=x-xcKtGhcu342c64fa0a0922bec619e2&newOrderRespType=RESULT&quantity=0.001&price=63000&timeInForce=GTC&signature=a011ef7555ad92c526dc444e076ef32d9fb80f6056009c4e12c8bb679a7113e6
```

`fapi` is for usdm-futures while `dapi` is for coinm-futures

It kinda looks like you're mismatching endpoints between usdm and coinm

**Comment by websharp950223** [comment]
I've matched endpoints to dapi: coinm-futures
But I got issues yet.

This is the code to create market order

```
# configure exchange
exchange_id = "binancecoinm"
exchange = getattr(ccxt, exchange_id)({
  'apiKey': api_key,
  'secret': secret,
  'timeout': 10000,
  'enableRateLimit': True,
  'options': {
    # "defaultType": "delivery", #margin, future, delivery
    "adjustForTimeDifference": True, 
    "recvWindow": 10000,
    "warnOnFetchOpenOrdersWithoutSymbol": False,
    "createMarketBuyOrderRequiresPrice": False
  }
})

```
```
symbol = 'BTC/USD'
price = 60000
amount = 0.001
type = 'limit'  # or market
params = {
    'positionSide': 'LONG',
}
order = await exchange.create_market_sell_order(symbol, amount)
```
Below shows the errors when running above code
`{"code":-4003,"msg":"Quantity less than zero."}`
![order_issue](https://user-images.githubusercontent.com/93001796/144090338-20e7a05b-882f-4e23-9a18-379789a75bdb.png)

It seems I have no more than the amount, but I have balance in my coinm-future.
This shows it has
I've 0.0078 BTC
![balance](https://user-images.githubusercontent.com/93001796/144090788-23dbb72f-2cba-40c2-b17f-26bfd13f9ce1.png)

**Comment by kroitor** [comment]
@websharp950223 the amount for `createOrder` must be a whole integer number (the number of contracts you want to buy or sell). In general, when trading contracts, you're not trading BTC or USDT, you're actually buying and selling whole contracts, where each contract worth some fractional amount of BTC or USDT.

**Comment by websharp950223** [comment]
I am always happy to use your ccxt
You are great
I have only 0.0078BTC in my coinm-futures
Then is it impossible to create order with this?

**Comment by kroitor** [comment]
@websharp950223 

> I have only 0.0078BTC in my coinm-futures

That should be enough.

> Then is it impossible to create order with this?

The amount for your order is not in BTC, it's in contracts.

```Python
import ccxt
from pprint import pprint
exchange = ccxt.binancecoinm()
markets = exchange.load_markets()
market = exchange.market('BTC/USD')
pprint(market)
```

↑ The contract size for BTC/USD is 100 USD, so one contract is wort 100 USD and 0.0078BTC is around 58USD which is not enough to place the smallest order, I think.

**Comment by websharp950223** [comment]
it is not 58usd
it is over 400usd
0.00785811 * 56,815.60 = 446.46
I think it is sufficient to place a order

**Comment by kroitor** [comment]
@websharp950223 yes, you're right, that should be sufficient.

**Comment by websharp950223** [comment]
Thanks for your support.
I thought amount means the BTC, I realized it is just contract size, not BTC amount.
You made me to understand
Thanks about that
As I told you before, my coinm-future has 0.0078 BTC, so it should be sufficient to place an order with amount 1.
But I got another issue
code
```
amount = 1
order = await exchange.create_market_sell_order(symbol, amount)
```

`error: binancecoinm {"code":-4061,"msg":"Order's position side does not match user's setting."}`
![order_issue_1](https://user-images.githubusercontent.com/93001796/144173947-4284329d-d046-4f21-b880-87cf26dec91d.png)

Could you possible assist me to resolve this issue?
Thanks

**Comment by kroitor** [comment]
@websharp950223 it looks like you have switched to isolated margin mode?
if that is the case, you should specify the `positionSide` param to your order or switch to cross-margin mode.

```Python
amount = 1
params = {'positionSide': 'SHORT'}
order = await exchange.create_market_sell_order(symbol, amount, params)
```

**Comment by ttodua** [comment]
@websharp950223 any updates - was the issue fixed?

**Comment by websharp950223** [comment]
Thanks @kroitor 
It works fine, it seems to place order successfully but my future account has same amount still
I am not sure what it does mean
Could you possible assist me?

**Comment by kroitor** [comment]
> but my future account has same amount still

Sometimes Binance users can confuse COIN-M futures balances with USD-M futures balances, could that be the case?

**Comment by websharp950223** [comment]
Thanks for your quick response
Let me check again and inform you

**Comment by websharp950223** [comment]
Hello, Kroitor
It works fine on my end
Thanks for your support
Btw, I have another issue
I got issue when making withdraw
These are my code

check withdraw ability
```
code = "BTC"
exchange.load_markets()
currency = exchange.currencies[code]
active = 'active' in currency and currency['active']
print(code + ' is ' + 'active' if active else 'inactive')
```
output:
![image](https://user-images.githubusercontent.com/93001796/145245006-9660a947-14e0-40b9-b148-9988d47437a6.png)

These are code to get balances

   ```
 def get_positive_accounts(balance):
        result = {}
        currencies = list(balance.keys())
        for currency in currencies:
            if balance[currency] and balance[currency] > 0:
                result[currency] = balance[currency]
        return result


    trading_balance = exchange.fetch_balance()
    account_balance = exchange.fetch_balance({'type': 'account'})
    pprint('Trading balance:')
    pprint(get_positive_accounts(trading_balance['total']))
    pprint('Account balance:')
    pprint(get_positive_accounts(account_balance['total']))

```

output:
![image](https://user-images.githubusercontent.com/93001796/145245529-0809f4de-58df-44d1-826a-d41525e29c1f.png)

code to withdraw BTC
    ```
withdraw = exchange.withdraw('BTC', 0.00886162, 'bc1qht8lxulr8udtgnw9rckamzap0gmd4gjhtagsj3')
    pprint('Withdraw:')
    pprint(withdraw)

```
getting this error
![image](https://user-images.githubusercontent.com/93001796/145245815-f9466628-62e2-4124-9b3a-9d20c28e7824.png)

Could you please assist me how to resolve that?

**Comment by ttodua** [comment]
@websharp950223 does your API keys have permission enabled for 'withdraw' ? when creating the API keys, there is a checkbox which permits specifically withdrawals, and maybe you havent had that checked?

**Comment by ttodua** [comment]
@websharp950223  this topic became too lengthy. To avoid a mixup of different issues, I suggest you take your last comment and open a new issue (if you feel my above comment doesn't solve that situation), where we can discuss the issue in separate topic.
