### ISSUE TITLE
MARKET_ORDERS_DISABLED bittrex

### ISSUE THREAD

**Issue by ironexmaiden** [ccxt/ccxt#1060]
- OS: Windows
- Programming Language: Python
- CCXT version: 
- Exchange: Bittrex
- Method: create_market_sell_order

Hello everyone I try to execute the folowing command but I got an error

ccxt.base.errors.ExchangeError: bittrex {"success":false,"message":"MARKET_ORDERS_DISABLED","result":null}

I checked my api key and i have the trades on!
```
bittrex = ccxt.bittrex({
        'apiKey': 'MyApiKey',
        'secret': 'Secret',
    })
bittrex.create_market_sell_order('ETH/BTC', 0.00193088, {'leverage': 3})

```
Has anyone any tip on this?

**Comment by kroitor** [comment]
Hi! Bittrex has disabled all market orders, they accept limit orders only for now. Does this answer your question?

**Comment by ironexmaiden** [comment]
Is there a corresponding ccxt function which I can use for limit sell order?

**Comment by kroitor** [comment]
@ironexmaiden:
- https://github.com/kroitor/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders
- https://github.com/ccxt/ccxt/wiki/Manual#limit-orders
