### ISSUE TITLE
[wavesexchange.py] Fetch Balance - KeyError: '3DW15KPOOEGEZZJX2MRLFZGWHSHTQVKI4SQHJ4XSMTWK'

### ISSUE THREAD

**Issue by Maxximiliann** [ccxt/ccxt#10613]
- OS: Ubuntu 20.04.3 LTS
- Programming Language version: Python 3.9.6
- CCXT version: ccxt 1.61.37

```
  File "/home/app/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/ccxt/wavesexchange.py", line 1450, in fetch_balance
    result[code]['used'] = self.currency_from_precision(code, amount)
    │      │               │    │                       │     └ '1702018281938'
    │      │               │    │                       └ '3DW15KPOOEGEZZJX2MRLFZGWHSHTQVKI4SQHJ4XSMTWK'
    │      │               │    └ <function wavesexchange.currency_from_precision at 0x7f8556c81b80>
    │      │               └ ccxt.wavesexchange()
    │      └ '3DW15KPOOEGEZZJX2MRLFZGWHSHTQVKI4SQHJ4XSMTWK'
    └ {'CRV': {'free': None, 'used': None, 'total': '0.00000001'}, 'ETH': {'free': None, 'used': None, 'total': '0.00000007'}, 'WES...
  File "/home/app/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/ccxt/wavesexchange.py", line 907, in currency_from_precision
    scale = self.currencies[currency]['precision']
            │    │          └ '3DW15KPOOEGEZZJX2MRLFZGWHSHTQVKI4SQHJ4XSMTWK'
            │    └ {'BCH': {'id': 'zMFqXuoyrn5w17PFurTqxB7GsS71fp9dfk6XFwxbPCy', 'numericId': None, 'code': 'BCH', 'precision': 8}, 'BTC': {'id'...
            └ ccxt.wavesexchange()

KeyError: '3DW15KPOOEGEZZJX2MRLFZGWHSHTQVKI4SQHJ4XSMTWK'
```

**Comment by ttodua** [comment]
As we see in the provided output, the function itself `currency_from_precision(code, amount)`  was called with weird `code` value which was `3DW15KPOOEGEZZJX2MRLFZGWHSHTQVKI4SQHJ4XSMTWK`.   There should be the currency-slug (code) i.e. 'ETH' or whatever.  Can you please post the full response you are getting `{'CRV':.....` (of course, omit the exact amount numbers, just I want to see all listed coin-names.

**Comment by ttodua** [comment]
As I've found out, CCXT only supports the tokens/coins listed [here](https://marketdata.wavesplatform.com/api/v1/tickers) and bug was caused by the fact that coin is not in supported list.
I've amended that part and after fix is submitted, I'll comment here.

**Comment by ttodua** [comment]
This issue was fixed in [PR](https://github.com/ccxt/ccxt/pull/10800)
