### ISSUE TITLE
How could I create a % slide bar using contract in Binance COIN M Futures?

### ISSUE THREAD

**Issue by criptoice** [ccxt/ccxt#10618]
I have a bot connected with CCXT & Binance
When I trade with usdt /btc (USD-M Futures) I can set a  % slide bar that takes me % of the amount that I have been setting. For example, If I have 1000 usdt and I set the 50% of the balance my bot set a 500usdt order. So this is OK

Now I try to create a new % slide bar in COIN M Futures to select % of contracts. For example, if I´m total contract balance is 10 contracts,that is all my balance, I would like to set 50% in my slide bar to  order of my total contract balance. So it will be 5 contracts. Could I do this in COIN M Futures and be working with contracts?

Also please let me ask..Could I do the same % slide bar COIN M Futures using the balance of BTC?

 Could you help me please with that? Regards

**Comment by criptoice** [comment]
I´m not sure to get an answer. Did you write something?

**Comment by kroitor** [comment]
@criptoice hi! CCXT does not cover the user interfacing side, it is a programmatic API. If you want to set a percentage of any value – calculate it with a simple multiplication using your programming language and pass that to CCXT's unified API. Let us know if that does not answer your question.
