### ISSUE TITLE
[F.R.] DataProvider Mode with catching on pickle and/or csv

### ISSUE THREAD

**Issue by mablue** [ccxt/ccxt#10615]
Since and limit needs to bunch of calculations and etc to get all time olhcv files with catching old data and get just updates from api, and after that I will use other bunch of codes to find where I will add or how will I catch data for latter usage.
But if we can do this it will be amazing and will reduce download time speed and etc:

```python
# lazy code 
while true:
    olhcv = fetch_olhcv(market,tf)
```

```python
# Intelligently code
while true:
   csv_file.load(exchange,market,tf)
   gap = csv_file.last_candle_time - time.now()
   olhcv = fetch_olhcv(exchange, market, tf, gap)
   csvfile.append(exchange, market, tf, olhcv)
```
It can make things faster,
Yes I know I can use ticker to do that but when the while loop time gap growing up ( cuz I download all exchanges all markets all tfs!) Its not usable for me I need every timeframe splited but with low internet usage and faster way 

It will be very usefull for who like me that try to save and work with data and provide this data to bunch of other users.I need to download data just one time when needed and if there is a catched csv that I will use this to provide to the other users it will be good!

If we know that the only thing that important is the last candle status in fetching olhcv and also all older candles are stable data,why we should redownload all this data?!
We can simply do that:
```python
fetch_olhcv(market,tf, since, limit, use_catched_data=True, catched_data_size="1GB",catched_data_dir="./tmp",....)
```

**Comment by ttodua** [comment]
It might be useful enhancement, but has some tricky parts which will need to be solved and atm not built inside CCXT.
You can either internally (in runtime) save the last request timestamp in variable, like:
```
since = lastTimestamp - tf_to_milliseconds;
fetch_ohlcv(market, tf, since , ...)
lastTimestamp = now..;
```
So, you will not either need internal caching.
But (I am not well-versed in python, i can give you just an idea)  if you are not running uninterupted loop (like nodejs) but instead do re-running script from time to time, then just write & read that variable into 'session-like' variable or even in file. 

If that doesn't help, feel free to re-open the issue.

**Comment by mablue** [comment]
Thanks for help. I really worked on this but I cant write the code...
Im confused 🤔
I need to load all timeframes at first and just use a 1min timeframe to update all my charts.(I have many charts with defferent timeframes that them will update each minute.
And also I have many users and I need to save all progress in a csv file and just download the unavailable data.
Please write me a code for btc I really I pass mind blowing and hurt attacks while solving this problem(kidding) :(
