### ISSUE TITLE
Difference between fetchMyTrades and fetchClosedOrders and cloudflare errors?

### ISSUE THREAD

**Issue by hippylover** [ccxt/ccxt#1061]
Some exchanges support fetchmytrades, other fetchclosedorders and some support fetchmytrades but only with a symbol but what is the difference?

I am also getting a bunch of cloudflare issues on liqui, kraken, etc but this is a separate issue. I wanted to suggest using cloudflare scraper which may help(im on  python).

I want to support a lot of exchanges but every other command doesn't work making it difficult to support with a unified api. But i suppose i can trust fetchOrder to always work? Then i can track closed orders and open orders locally and ping the server to see if an open order closed. What do you think about this approach?

**Comment by hippylover** [comment]
Hmm. I see now it is possible to send through proxy but im wondering how safe it is to send to for example herokuapp my api key and secret or am i misunderstanding something?

Anyway, i still wonder what is the difference between the two calls.

**Comment by mkutny** [comment]
Trade is an effect of order execution so these are completely different entities.

A placed order not necessary leads to a trade.

At the same time it could be that your order had been executed several times before it got fulfilled ('closed' in ccxt terms), in this case you'll get several trades. Or it might be that your order was only partially executed, in this case, there is a trade but no closed order (yet).

In case of market orders (as opposed to limit orders), they don't have the price, while trades do.
In case of limit orders, the time between order placement and order execution will usually be different.

**Comment by hippylover** [comment]
Ok, i see. What happens if i put an order in order book but then remove it before it is filled? Will i get an entry in "closedOrders" then?

**Comment by mkutny** [comment]
First things first:

* ccxt classifies order statuses by 'open', 'closed' (e.g. fulfilled) and 'canceled' (mind american's single 'l')

* ccxt unified API provides `fetchOpenOrders` and `fetchClosedOrders` but not `fetchCanceledOrders`

(as a result, you may find classification is a bit misleading as one would expect 'closed' to mean both fulfilled and cancelled)

Given above you now might guess that you won't find your canceled order in closedOrders. Nevertheless, you still can get your cancelled order using `fetchOrder(id)`.

Keep in mind, that you may find your order to be partially filled before you cancel it. In this case, you should see a trade and most probably your order will get 'canceled' status, although don't get surprised if some exchanges set it to fulfilled ('closed').

**Comment by kroitor** [comment]
@mkutny thank you for explaining this!

@hippylover do you still have questions or difficulties with the above methods?

**Comment by hippylover** [comment]
No, i think i understand. It seems that fetchOrder is the one most supported in exchanges and i will use that one when i buy/sell through my program to check orderstatus and fetchmytrades(and fetchclosedorders when it is not supported) to get a history of stuff not bought/sold through my program.

I am still wondering if using cloudscraper is an idea. I think this is a way to avoid sending through a proxy and maybe it is safer.

**Comment by hippylover** [comment]
Well i tried setting up cors-anywhere on localhost, and passing exchanges['kraken'].proxy = 'https://0.0.0.0:8080/' but it fails with: ccxt.base.errors.ExchangeNotAvailable: kraken GET https://0.0.0.0:8080/https://api.kraken.com/0/public/AssetPairs <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:777)>

When i tried setting proxy to http i got a cloudflare error.

Well there's a problem with this.
1. I barely know what im doing. Maybe my computer is wide open to the world now i have no idea.
2. I don't like sending through heroku because it seems my apikeys would be sent to them and then to server so i don't want to do that.
3. Cannot this be solved with cfscrape? Maybe i am completely wrong. I fear looking into your code because i think itll be complex X) (cfscrape is regularly updated though to work with new cloudflare pages and it's usually just a one-line change atleast if you are using requests)
4. Wouldnt that be a lot easier than require user to set up own cors-anywhere node server?

**Comment by kroitor** [comment]
> I am still wondering if using cloudscraper is an idea. I think this is a way to avoid sending through a proxy and maybe it is safer & faster.

Yes it is. We are working on it. But you can already use it right away if you can set the tunneling agent properly: https://github.com/ccxt/ccxt/pull/599. But this is a completely different issue that is not related to fetchMyTrades.

> Well i tried setting up cors-anywhere on localhost

Why do you need it? It won't help you bypass the cloudflare protection. The CORS-proxy is only needed if you're using the JavaScript code in the browser. It won't work with SOCKS or HTTP proxies. 

- In Javascript you need to use the tunneling agent and your own implementation of node-fetch.
- To use proxies in python refer to this: use the https://github.com/ccxt/ccxt/issues/906 (it is as flexible as the underlying `python-requests`, so you can configure proxies, CORS, cloudflare scrapers, whatever you want with the current version of CCXT, this functionality is already there).

> When i tried setting proxy to http i got a cloudflare error.

Right, same answer. A local CORS-proxy won't help bypass cloudflare – you're still accessing the exchange from your computer, even if you do it through a local CORS-proxy (set up on your computer).

> I barely know what im doing. Maybe my computer is wide open to the world now i have no idea.

This is unlikely.

> I don't like sending through heroku because it seems my apikeys would be sent to them and then to server so i don't want to do that.

Not really, most exchanges don't require any keys, they need a signature, which is cryptographically strong, therefore intercepting a signature won't help a middleman obtain your keys in any way. But some exchanges don't use the signing mechanism and use the key only – for those you would not want to use a public proxy.

> Cannot this be solved with cfscrape? 

Yes, it can, as explained above.

Let me know, if the above answers your question or not. I'd close this issue, if you don't mind. Thx!

**Comment by hippylover** [comment]
Ok. Cool that you are working on it. I still think it is strange though and am forced to conclude you are doing something in your script that forces these cloudflare issues. The reason i am saying that is because i have made scripts for about 6 exchanges to work with their api's before trying this library both in python and bash(of all things -- this was before i learnt python) and i don't recall ever getting these cloudflare issues with them. I am not doing anything fancy in my scripts, just using requests to send the data neccesary -- but i works. I can send you the scripts but as iv'e said im not doing anything fancy. Let me know if you want me to post them. They are for bittrex, poloniex, bitfinex, yobit, ccex, tidex and i can't remember maybe some more. In both python and bash versions :p 

I just tried with my yobit python script(don't want to mess up any other exchanges nonces!) now and i got no cloudflare issues when getting balances, but with ccxt i got cloudflare issue. same key & secret.

**Comment by hippylover** [comment]
Here's the error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 325, in fetch
    response = opener.open(request, timeout=int(self.timeout / 1000))
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kris/exchangescripts/ccex_examples/instantiate-all-at-once.py", line 33, in <module>
    buyresp = exchanges['yobit'].fetchBalance()
  File "/usr/lib/python3.6/site-packages/ccxt/yobit.py", line 106, in fetch_balance
    self.load_markets()
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 792, in load_markets
    markets = self.fetch_markets()
  File "/usr/lib/python3.6/site-packages/ccxt/liqui.py", line 121, in fetch_markets
    response = self.publicGetInfo()
  File "/usr/lib/python3.6/site-packages/ccxt/yobit.py", line 171, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 283, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 341, in fetch
    self.handle_rest_errors(e, e.code, message if message else text, url, method)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 369, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 265, in raise_error
    details,
ccxt.base.errors.DDoSProtection: yobit GET https://yobit.net/api/3/info 403 Forbidden  <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Access denied | yobit.net used Cloudflare to restrict access</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>
<!--[if lte IE 9]><script type="text/javascript" src="/cdn-cgi/scripts/jquery.min.js"></script><![endif]-->
<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script><!--<![endif]-->
<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>

</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1>
          <span class="cf-error-type" data-translate="error">Error</span>
          <span class="cf-error-code">1010</span>
          <small class="heading-ray-id">Ray ID: 3d8c29201d43427f &bull; 2018-01-06 05:08:39 UTC</small>
        </h1>
        <h2 class="cf-subheadline" data-translate="error_desc">Access denied</h2>
      </div><!-- /.header -->

      <section></section><!-- spacer -->

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="what_happened">What happened?</h2>
            <p>The owner of this website (yobit.net) has banned your access based on your browser's signature (3d8c29201d43427f-ua48).</p>
          </div>

          
        </div>
      </div><!-- /.section -->

      <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>3d8c29201d43427f</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span data-translate="your_ip">Your IP</span>: 80.212.154.178</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span data-translate="performance_security_by">Performance &amp; security by</span> <a data-orig-proto="https" data-orig-ref="www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div><!-- /.error-footer -->


    </div><!-- /#cf-error-details -->
  </div><!-- /#cf-wrapper -->

  <script type="text/javascript">
  window._cf_translation = {};
  
  
</script>

</body>
</html>
```

**Comment by kroitor** [comment]
@hippylover ok, a few questions:

1. is it repeating upon the next call?
2. if it is, can you set .userAgent = 'your_arbitrary_string' on the exchange instance, then retry and report here if the error is persistent?

**Comment by hippylover** [comment]
1. Yes i get the same error on next try.
2. I sat .userAgent to the literal 'your_arbitrary_string' and it worked. I don't think this kind of thing should be necessary though. As iv'e said, i don't do any such thing in my scripts and it still works, also it is tedious to do these things if the point is to support multiple exchanges with one script which is the reason i want to use this script.
3. I'm not rate limiting through script but using my own mechanism.
4. Ok, this is the code i used to test:
```
import ccxt
exchanges = {}

for id in ccxt.exchanges:
    exchange = getattr(ccxt, id)
    exchanges[id] = exchange()

exchanges['yobit'].apiKey = ''
exchanges['yobit'].secret = ''

exchanges['yobit'].userAgent = 'your_arbitrary_string' # well i added this now per your comment
resp = exchanges['yobit'].fetchBalance()

print(resp)

```
5. No, i don't understand how to do that...

I uploaded my scripts if anyone wants to take a look. There's also bash support there if you ever want to add that :P(please don't prioritise this). Some of the more obscure exchanges might not work, i can't remember and can't be arsed, also full api support is not guaranteed or even that it works at all as it's been a while since i looked at this code and i coded it when i was fresh in python so it's probably not very pretty:

[exchangesupport_bash_python_its_a_mess.tar.gz](https://github.com/ccxt/ccxt/files/1608519/exchangesupport_bash_python_its_a_mess.tar.gz)

**Comment by kroitor** [comment]
> i don't do any such thing in my scripts and it still works

I checked your scripts and you use command-line curl. Now, back to your answer:

> I don't think this kind of thing should be necessary though.

cURL sets its own userAgent, and even if you think it is not necessary, curl does that for you. If you run it with `--verbose` flag added, you'll see it within your scripts:

```shell
curl --verbose 'http://www.google.com/'
> GET / HTTP/1.1
> User-Agent: curl/7.37.0 ←-------- here it is
> Host: www.google.com
> Accept: */*
```

Next, we used to set our own default user-agent, but this can actually lead to more significant problems, like identifying and throttling your requests (which is a security threat) therefore we are leaving it up to the user. We now don't set it in the library by default for that reason. The user has to set that, so, you can literally set it to 'curl/your.curl.version' or whatever string you want, like, pretend to be a popular browser.

So, in some cases, setting the userAgent is still necessary. But you're right, that should not be necessary after all, and we are working on a solution for the user-agent string (hope to upload it soon, will update you, of course). But this is a completely different issue, not related to the subject of fetchMyTrades. 

Let me know if the above answers your question and if I can close it for now.

**Comment by hippylover** [comment]
I don't use curl in my python scripts.

**Comment by kroitor** [comment]
@hippylover then you can print out the request headers from your python scripts to see the default user-agent that is sent there and compare it to verbose output of ccxt to see if there's a difference.

**Comment by hippylover** [comment]
I don't know how to print out the request headers, but this is how i create it(atleast on yobit script):

signature = hmac.new(self.secret.encode(), data.encode(), digestmod=hashlib.sha512)
            headers = {
                'Key' : self.key,
                'Sign': signature.hexdigest(),
                'Content-Type': 'application/x-www-form-urlencoded'
            }

and this i how output looks from ccxt:
Request: {'Accept-Encoding': 'gzip, deflate'} None

So im just taking a wild guess but maybe it works with my script because i set  'Content-Type': 'application/x-www-form-urlencoded' ?

**Comment by kroitor** [comment]
@hippylover this may be the case, I suggest to try setting the 'Content-Type' with ccxt like so:

```Python
import ccxt
exchange = ccxt.yobit({
    'headers': {
        'Content-Type': 'application/x-www-form-urlencoded',
    },
    # your other params, keys, whatever...
})

# ... your call to the exchange ...
```

↑ Does it work like that? If it does, we will add that header to yobit implementation and elsewhere, if necessary.

**Comment by hippylover** [comment]
Nope. Can you tell me how to check what request headers im sending and i will test it.

**Comment by hippylover** [comment]
Hmm. i think it is just .headers. Anyway, this is the response i got with my script:

{'Date': 'Sat, 06 Jan 2018 07:25:53 GMT', 'Content-Type': 'text/html; charset=utf8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=ichangedthisbecausecookiescanbeusedforstuffithink:); expires=Sun, 06-Jan-19 07:25:53 GMT; path=/; domain=.yobit.net; HttpOnly; Secure, locale=en; expires=Thu, 06-Jan-2028 07:25:53 GMT; path=/', 'Vary': 'Accept-Encoding', 'X-Frame-Options': 'SAMEORIGIN', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block;', 'x-download-options': 'noopen', 'Server': 'cloudflare-nginx', 'CF-RAY': '3d8cf227dbe54285-OSL', 'Content-Encoding': 'gzip'}

**Comment by hippylover** [comment]
Ok, got it working through logging(https://stackoverflow.com/questions/10588644/how-can-i-see-the-entire-http-request-thats-being-sent-by-my-python-application):

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): yobit.net
send: b'POST /tapi/ HTTP/1.1\r\nHost: yobit.net\r\nUser-Agent: python-requests/2.18.4\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nKey: FAKE\r\nSign: 82fba8aa0315e9c4c1679189930630deda9f8b62e97bfa7978b5cd6e1fe4c044f81d50e01b6fd5be4d0d01f5c9f30dc457154ce345fb6d40ddcbeab2a8f074b2\r\nContent-Type: application/x-www-form-urlencoded\r\nContent-Length: 31\r\n\r\n'
send: b'method=getInfo&nonce=1515225964'
reply: 'HTTP/1.1 200 OK\r\n'
DEBUG:urllib3.connectionpool:https://yobit.net:443 "POST /tapi/ HTTP/1.1" 200 None
header: Date header: Content-Type header: Transfer-Encoding header: Connection header: Set-Cookie header: Set-Cookie header: Vary header: X-Frame-Options header: X-Content-Type-Options header: X-XSS-Protection header: x-download-options header: Server header: CF-RAY header: Content-Encoding
```

This is output with fake key and secret with content type sat. If i remove Content-Type': 'application/x-www-form-urlencoded' from my script i get: {'success': 0, 'error': 'invalid key, sign, method or nonce'} even with correct keys. So iv'e tried and it works with real key & secret but not if i remove Content-Type': 'application/x-www-form-urlencoded'

**Comment by kroitor** [comment]
Ok, I was about to post that snippet from stackoverflow for you here... Now, let's do the same with ccxt (add .verbose = True on the exchange) what do you see in request headers and what is the difference in there? Can you post it here the verbose output (headers should be there)?

**Comment by hippylover** [comment]
```
exchange = ccxt.yobit({
    'headers': {
        'Content-Type': 'application/x-www-form-urlencoded',
    }
})
exchange.verbose = True
exchange.apiKey = "FAKE"
exchange.secret = "FAKE"
resp = exchange.fetchBalance()
print(resp)
```

resp:
```
https://yobit.net/api/3/info GET https://yobit.net/api/3/info 
Request: {'Content-Type': 'application/x-www-form-urlencoded', 'Accept-Encoding': 'gzip, deflate'} None
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 325, in fetch
    response = opener.open(request, timeout=int(self.timeout / 1000))
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kris/exchangescripts/ccex_examples/instantiate-all-at-once.py", line 43, in <module>
    resp = exchange.fetchBalance()
  File "/usr/lib/python3.6/site-packages/ccxt/yobit.py", line 106, in fetch_balance
    self.load_markets()
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 792, in load_markets
    markets = self.fetch_markets()
  File "/usr/lib/python3.6/site-packages/ccxt/liqui.py", line 121, in fetch_markets
    response = self.publicGetInfo()
  File "/usr/lib/python3.6/site-packages/ccxt/yobit.py", line 171, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 283, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 341, in fetch
    self.handle_rest_errors(e, e.code, message if message else text, url, method)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 369, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 265, in raise_error
    details,
ccxt.base.errors.DDoSProtection: yobit GET https://yobit.net/api/3/info 403 Forbidden  <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Access denied | yobit.net used Cloudflare to restrict access</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>
<!--[if lte IE 9]><script type="text/javascript" src="/cdn-cgi/scripts/jquery.min.js"></script><![endif]-->
<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script><!--<![endif]-->
<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>

</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1>
          <span class="cf-error-type" data-translate="error">Error</span>
          <span class="cf-error-code">1010</span>
          <small class="heading-ray-id">Ray ID: 3d8d3f7648814291 &bull; 2018-01-06 08:18:39 UTC</small>
        </h1>
        <h2 class="cf-subheadline" data-translate="error_desc">Access denied</h2>
      </div><!-- /.header -->

      <section></section><!-- spacer -->

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="what_happened">What happened?</h2>
            <p>The owner of this website (yobit.net) has banned your access based on your browser's signature (3d8d3f7648814291-ua48).</p>
          </div>

          
        </div>
      </div><!-- /.section -->

      <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>3d8d3f7648814291</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span data-translate="your_ip">Your IP</span>: 80.212.154.178</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span data-translate="performance_security_by">Performance &amp; security by</span> <a data-orig-proto="https" data-orig-ref="www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div><!-- /.error-footer -->


    </div><!-- /#cf-error-details -->
  </div><!-- /#cf-wrapper -->

  <script type="text/javascript">
  window._cf_translation = {};
  
  
</script>

</body>
</html>

```

**Comment by kroitor** [comment]
@hippylover can you request this particular URL: https://yobit.net/api/3/info with your python script and again post the request headers here, as you did in one of the messages above? The problem is with the public endpoint, not the trading api... So we need to compare headers for that URL.

**Comment by hippylover** [comment]
```
>>> import yobitpyapi
>>> y = yobitpyapi.yobit()
>>> resp = y.gimme("info")
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): yobit.net
send: b'GET /api/3/info HTTP/1.1\r\nHost: yobit.net\r\nUser-Agent: python-requests/2.18.4\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
DEBUG:urllib3.connectionpool:https://yobit.net:443 "GET /api/3/info HTTP/1.1" 200 None
header: Date header: Content-Type header: Transfer-Encoding header: Connection header: Set-Cookie header: Set-Cookie header: Vary header: X-Frame-Options header: X-Content-Type-Options header: X-XSS-Protection header: x-download-options header: Server header: CF-RAY header: Content-Encoding
```

**Comment by hippylover** [comment]
Hmm. It seems no matter which call i make through ccxt it wants to talk to: https://yobit.net/api/3/info ... Even if i make private api calls...

**Comment by kroitor** [comment]
> It seems no matter which call i make through ccxt it wants to talk to https://yobit.net/api/3/info

That is because it will try to preload markets first (it does that once and then caches them, but that particular request fails). Preloading markets is [explained in the Manual](https://github.com/ccxt/ccxt/wiki/Manual#loading-markets).

Back to your previous post – again, we see `User-Agent: python-requests/2.18.4` there...

Now, does this snippet work for you?

```Python
import ccxt
exchange = ccxt.yobit({'verbose': True})
exchange.public_get_info({'foobar': 'blabla123456'})  #  a test of their cloudflare protection
```

**Comment by hippylover** [comment]
Nope.

```
https://yobit.net/api/3/info?foobar=blabla123456 GET https://yobit.net/api/3/info?foobar=blabla123456 
Request: {'Accept-Encoding': 'gzip, deflate'} None
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 325, in fetch
    response = opener.open(request, timeout=int(self.timeout / 1000))
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kris/exchangescripts/ccex_examples/instantiate-all-at-once.py", line 46, in <module>
    print(exchange.public_get_info({'foobar': 'blabla123456'}) )
  File "/usr/lib/python3.6/site-packages/ccxt/yobit.py", line 171, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 283, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 341, in fetch
    self.handle_rest_errors(e, e.code, message if message else text, url, method)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 369, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File "/usr/lib/python3.6/site-packages/ccxt/base/exchange.py", line 265, in raise_error
    details,
ccxt.base.errors.DDoSProtection: yobit GET https://yobit.net/api/3/info?foobar=blabla123456 403 Forbidden  <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Access denied | yobit.net used Cloudflare to restrict access</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>
<!--[if lte IE 9]><script type="text/javascript" src="/cdn-cgi/scripts/jquery.min.js"></script><![endif]-->
<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script><!--<![endif]-->
<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>

</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1>
          <span class="cf-error-type" data-translate="error">Error</span>
          <span class="cf-error-code">1010</span>
          <small class="heading-ray-id">Ray ID: 3d8d7004aaa04285 &bull; 2018-01-06 08:51:48 UTC</small>
        </h1>
        <h2 class="cf-subheadline" data-translate="error_desc">Access denied</h2>
      </div><!-- /.header -->

      <section></section><!-- spacer -->

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="what_happened">What happened?</h2>
            <p>The owner of this website (yobit.net) has banned your access based on your browser's signature (3d8d7004aaa04285-ua48).</p>
          </div>

          
        </div>
      </div><!-- /.section -->

      <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>3d8d7004aaa04285</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span data-translate="your_ip">Your IP</span>: 80.212.154.178</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span data-translate="performance_security_by">Performance &amp; security by</span> <a data-orig-proto="https" data-orig-ref="www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div><!-- /.error-footer -->


    </div><!-- /#cf-error-details -->
  </div><!-- /#cf-wrapper -->

  <script type="text/javascript">
  window._cf_translation = {};
  
  
</script>

</body>
</html>
```

**Comment by hippylover** [comment]
Well this works:

exchange = ccxt.yobit({
    'headers': {
        #'Content-Type': 'application/x-www-form-urlencoded',
        'User-Agent': 'random'
    },
})

exchange.apiKey = "sdfsdf"
exchange.secret = "dsfdsd"

exchange.verbose = True

resp = exchange.fetchBalance() # both work
resp = exchange.public_get_info({'foobar': 'blabla123456'})  #both work
But it's strange that my own script needs Content-Type sat. I remember this was the case with other exchanges too. Maybe you can use that for something.

If we can set useragent globally that will also be cool. I don't see this "security problem" as a big one...

**Comment by hippylover** [comment]
Ah, ok. I see the commit. Does this mean that it will "just werk" now? I have installed ccxt from pip. How can i install the latest version?

**Comment by kroitor** [comment]
Can you please update ccxt to version 1.10.577 with `pip install ccxt --upgrade`  and try this code, without headers, without user-agent and without verbose mode:

```Python
import ccxt
exchange = ccxt.yobit({'apiKey': 'YOUR_KEY', 'secret': 'YOUR_SECRET'})
print(exchange.fetch_balance())
```

or

```Python
import ccxt
exchange = ccxt.yobit()
exchange.apiKey = 'YOUR_KEY',
exchange.secret = 'YOUR_SECRET'
print(exchange.fetch_balance())
```

It should work normally now. We will be happy if you report back.

**Comment by hippylover** [comment]
Working! Great stuff man! Thanks!

I will keep my eyes open and see if it works with other exchanges too.

**Comment by kroitor** [comment]
Ok, feel free to reopen this, or just ask questions if you have any other difficulties with it.
