### ISSUE TITLE
How to watch event "ACCOUNT_UPDATE" for binance futures?

### ISSUE THREAD

**Issue by yyyyaaa** [ccxt/ccxt#10619]
- OS: MacOS 12.0.1
- Programming Language version: Node 14
- CCXT version: Pro latest

As stated in the question above, how do I watch my currently open positions with websocket? I do see a public method
`handleMessage(client, message)` but I couldn't figure out how to use it, there's no docs for it.

I tried this with no luck

```
const binance = new ccxt.binanceusdm({
  apiKey,
  secret: apiSecret,
  enableRateLimit: true
});

const res = await binance.handleMessage(binance, 'ACCOUNT_UPDATE');
// Will fail with error: TypeError: client.resolve is not a function
```

**Comment by gmalca** [comment]
```
const binance = new ccxt.binanceusdm({
  apiKey,
  secret: apiSecret,
  enableRateLimit: true
});
while (true) {
  let balance = await binance.watchBalance({type:'future'});
  if (balance.info.e == 'ACCOUNT_UPDATE') {
     console.log(balance.info.a.P);
  }
}
```

**Comment by kroitor** [comment]
@gmalca thanks for posting the solution, appreciate your help!

**Comment by yyyyaaa** [comment]
@gmalca thanks for the help! I'm not sure if this is something I wanted. I need to get currently open positions update including unrealized PNL, when I ran the code in your example it didn't send back any event when I'm pretty sure my uPNL has changed. Do you know of a way for me to achieve what I want? Thank you.
