### ISSUE TITLE
I can't seem to fix the process of my identity problem

### ISSUE THREAD

**Issue by DUK3135** [ccxt/ccxt#10627]
I'm having hellof an issue with well probably way 2 much but I can't seem to fix the process of my identity problem with so e of these trading platforms so I've never been able to trade   and I've spent so much into stuff I didn't understand but anyhow what could I do now it's a valid government issued form of identification unfortunately because of my mom dying my birthplace being in a different state I can't get my social and because it's my prison id they won't accept it

**Comment by kroitor** [comment]
Unfortunately, we can't consult you on your docs, hope for your understanding. We are software developers, not lawyers. Check this guy: https://twitter.com/Raindropactual/status/1336820474999955461

**Comment by DUK3135** [comment]
My deepest apologies I meant for like trading crypto webul for instance
some identification platforms accepted my id the verification for
identification that's what I was asking for not consulting a lawyer it's
just the only form of I'd I have and was looking for a solution for it you
don't have to be a Richard thanks for the knowledge still learning

Joshua Rindfuss
