### ISSUE TITLE
Object not callable, for a few exchanges to query with API

### ISSUE THREAD

**Issue by dschigt** [ccxt/ccxt#10621]
Hi everybody,

To start this message, see next programs/versions I use:

- OS: Ubuntu 20.04.3 LTS (ARM)
- Programming Language version: Python 3.8.10
- CCXT version: 1.61.40

Last few days I have attempted to get my API call working to Gate.IO and a few others (e.g. Kraken/Poloniex).
The odd thing is that making an API call to Binance and Coinbase works fine. For all others, I get error:

"TypeError: 'dict' object is not callable"

The code I use is next:

import ccxt
exchange = ccxt.gateio({'apiKey':'textstring',
                         'secretKey':'textstring',
})
balance = exchange.fetch_balance()

The error thrown is:

/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 565, in on_json_response
    return json.loads(response_body, parse_float=str, parse_int=str)
TypeError: 'dict' object is not callable

Actually, I have no idea what is happening and it drives me crazy. I have read and investigated huge amount of help documents, websites and enabed the debugger. Nothing in particular which helped and I really have no clue what is happening.
Also I tried to set up a connection via another Python module (gate-api). This works fine, hence it does not seems to be the issue with the generated key pair.
As mentioned, this error also exactly happens for other exchanges I would like to query too. Each time the object not callable is shown...

Thanks for any help!

Best regards,
Detlev

**Comment by kroitor** [comment]
Hi! Please paste your runtime version of the lib:

```
import ccxt
print('CCXT Version:', ccxt.__version__)
```

**Comment by dschigt** [comment]
Hi kroiter,

Thanks for stepping in to help resolve my issue.
Here is the output you requested:

Python 3.8.10 (/usr/bin/python3)
%Run 'R&D/CCXT_Version.py'
CCXT Version: 1.61.40

**Comment by kroitor** [comment]
@dschigt in your code above you initialize the exchange with `apiKey` and `secretKey`, but the proper field names for your keys are `apiKey` and **`secret`**:

```Python
import ccxt
exchange = ccxt.gateio({
    'apiKey': 'YOUR_API_KEY_HERE',
    'secret': 'YOUR_SECRET_HERE',
})
markets = exchange.load_markets()
exchange.verbose = True 
balance = exchange.fetch_balance()
```

If that does not help, please, paste your verbose request+response here.
Please, use markdown for readability: https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax. Surround your output with triple backticks (\`\`\`), do not confuse backticks with quotes (\'\'\').

\`\`\`

YOUR OUTPUT HERE

\`\`\`

**Comment by dschigt** [comment]
Hi kroiter,

Thanks for your swift and clear response. Truly appreciated!
With regard to your respose, I exactly copied/paste the suggestion. However, there is no verbose output because the code execution breaks after markets = exchange.load_markets()

Same error:

TypeError: 'dict' object is not callable

Be informed, I tested it with 2 differrent API keys and I set my API permissions to allow all but withdraw money.
Hope this information helps to guide me further.

Best regards,

Detlev Schigt

**Comment by kroitor** [comment]
@dschigt try this:

```Python
import ccxt
exchange = ccxt.gateio()
exchange.verbose = True 
markets = exchange.load_markets()
```

Does that work for you?

**Comment by dschigt** [comment]
Hi kroiter,

Yes, that seems to work:

Response: GET https://api.gateio.ws/api/v4/spot/currency_pairs 200 {'Date': 'Sat, 20 Nov 2021 09:12:15 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'openresty', 'X-Request-Id': '[f53558c7-2375572294]', 'Access-Control-Allow-Methods': 'GET,POST,OPTIONS,DELETE,PUT', 'Access-Control-Allow-Headers': 'DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type', 'Access-Control-Max-Age': '1728000', 'Vary': 'Origin', 'Content-Encoding': 'gzip'} 

Generates als next output:
[{"id":"IHT_ETH","base":"IHT","quote":"ETH","fee":"0.2","min_quote_amount":"0.001","amount_precision":1,"precision":9,"trade_status":"tradable","sell_start":0,"buy_start":0},{"id":"AME_ETH","base":........etc.

What's then the next step to take to resolve the matter further?

Best regards,

Detlev

**Comment by kroitor** [comment]
@dschigt please, paste your complete verbose output with this snippet:

```Python
import ccxt
exchange = ccxt.gateio({
    'apiKey': 'YOUR_API_KEY_HERE',
    'secret': 'YOUR_SECRET_HERE',
})
exchange.verbose = True 
markets = exchange.load_markets()
```

**Comment by dschigt** [comment]
This is what is being displayed:

Response: GET https://api.gateio.ws/api/v4/spot/currency_pairs 200 {'Date': 'Sat, 20 Nov 2021 09:36:27 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'openresty', 'X-Request-Id': '[697532b4-2384034045]', 'Access-Control-Allow-Methods': 'GET,POST,OPTIONS,DELETE,PUT', 'Access-Control-Allow-Headers': 'DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type', 'Access-Control-Max-Age': '1728000', 'Vary': 'Origin', 'Content-Encoding': 'gzip'}

[{"id":"IHT_ETH","base":"IHT","quote":"ETH","fee":"0.2","min_quote_amount":"0.001","amount_precision":1,"precision":9,"trade_status":"tradable","sell_start":0,"buy_start":0},{"id":"AME_ETH","base":"AME","qu

**Comment by kroitor** [comment]
@dschigt is that all you see? That looks as if the output was cut or was not copied entirely.

**Comment by dschigt** [comment]
The about was showing way much more, though, I stopped pasting the data after "AME","qu". Apologies for not clearing that better.
However, if I have difficulties pasting it. It seems enormous bunch of info return from the API call... 
Does this help?

**Comment by kroitor** [comment]
@dschigt i'm mostly interested in the last part of it, if it's too long, please, paste it here: https://gist.github.com

**Comment by dschigt** [comment]
This is the final part:

{"id":"ALPHR_USDT","base":"ALPHR","quote":"USDT","fee":"0.2","min_quote_amount":"1","amount_precision":4,"precision":4,"trade_status":"tradable","sell_start":0,"buy_start":0}]

Enitre message is pasted at https://gist.github.com

**Comment by kroitor** [comment]
> This is the final part:
> 
> {"id":"ALPHR_USDT","base":"ALPHR","quote":"USDT","fee":"0.2","min_quote_amount":"1","amount_precision":4,"precision":4,"trade_status":"tradable","sell_start":0,"buy_start":0}]
> 
> Enitre message is pasted at https://gist.github.com

@dschigt please, paste the link to your gist.

**Comment by dschigt** [comment]
https://gist.github.com/dschigt/f926fe2fed9ca8b0d9aa61db46040cde

**Comment by kroitor** [comment]
@dschigt that output says that the snippet pasted above works:

```Python
import ccxt
exchange = ccxt.gateio({
    'apiKey': 'YOUR_API_KEY_HERE',
    'secret': 'YOUR_SECRET_HERE',
})
exchange.verbose = True 
markets = exchange.load_markets()
```

If that works without an issue, that means that your `load_markets()` call also works.

If the above works, then use this snippet and paste your verbose output here:

```Python
import ccxt
exchange = ccxt.gateio({
    'apiKey': 'YOUR_API_KEY_HERE',
    'secret': 'YOUR_SECRET_HERE',
})
markets = exchange.load_markets()
exchange.verbose = True 
response = exchange.fetch_balance()
```

**Comment by dschigt** [comment]
@kroitor,
Honestly, I do not know what the issue was, however, it works all fine now....
Meaning: I have copied your suggested snippet and BOOM there my balance appeared!
Backtesting this with my other code, still an issue. Nevertheless, I have tested also few other accounts, all working fine!

Thanks a million, truly!!
PS: I made a financial donation for your support ;-)

Best regards,
Detlev Schigt

**Comment by kroitor** [comment]
@dschigt thanks for reporting back! Good to know you have it resolved.
