### ISSUE TITLE
Invalid Api-Key ID error for Binance watchOrders

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#10620]
For Binance `watchOrders` for some users we receive error:
`AuthenticationError: binance {"code":-2008,"msg":"Invalid Api-Key ID."}`

Despite that, API and Secret keys are valid.

Also interesting that socket connection error handler is not triggered exactly on that error:
```
 // On socket connection error.
  const ccxtOnError = exchange.onError;
  exchange.onError = (client, error) => {
      console.log('NOT TRIGGERED');

      ccxtOnError.call(exchange, client, error);
  }
```

- OS: Debian (Ubuntu)
- Programming Language version: JavaScript
- CCXT version: Pro 0.7.25

**Comment by kroitor** [comment]
@wunderb1t hi! Can you post the code you use to reproduce it? Do you have this issue with CCXT Pro 0.9.30+?

**Comment by kroitor** [comment]
Please, feel free to reopen this issue if you still have it or just ask further questions if any.

**Comment by wunderb1t** [comment]
We keep experiencing this issue on Binance and Binance Futures all the time. We noticed that it occurs more often after a Nodejs restart. Are there any problems with signature or timing?

The error occurs in all methods where API and Secret key are used, for example, `createOrder`, `fetchBalances`.

Maybe we can somehow add a log to console what directly comes from Binance? We can't find error with code '-2008'  in Binance docs and what it means.

From Binance there is no any answer. 

Current CCXT pro version: `0.9.35`
