### ISSUE TITLE
[wavesexchange.py] Fetch Balance - Asset name issue: C1iWsKGqLwjHUndiQ7iXpdmPum9PeCDFfyXBdJJosDRS

### ISSUE THREAD

**Issue by Maxximiliann** [ccxt/ccxt#10636]
- OS: Ubuntu 20.04.3 LTS
- Programming Language version: Python 3.9.6
- CCXT version: ccxt 1.61.37

```
# waves_exchange_config.py
import os
import ccxt


def connection():
    wallet_id = os.environ.get('WALLET_ID')
    wallet_key = os.environ.get('WALLET_KEY')

    waves_exch = ccxt.wavesexchange({
        'apiKey': wallet_id,
        'secret': wallet_key,
    })
    return waves_exch


if __name__ == '__connection__':
    connection()


# wallet_balances.py
import sys
import simplejson as json
from loguru import logger
import waves_exchange_config as we
from erlport.erlterms import Atom
from requests.exceptions import HTTPError, ConnectTimeout
from urllib3.exceptions import MaxRetryError, ConnectTimeoutError, NewConnectionError
from ccxt.base.errors import RequestTimeout, NetworkError, AuthenticationError


logger.add('Logs/wallet_balances.py_log_{time}.log',
           format="{time:HH:mm:ss!UTC} {message}",
           rotation="100 MB", delay=True, filter='wallet_balances')



@logger.catch
def atomize(string):
    return Atom(bytes(string, encoding='utf8'))


@logger.catch
def submit_report(success_status, report):
    report_json = json.dumps(report)
    success_status_atom = atomize(success_status)
    try:
        return (success_status_atom, report_json)
    except (BrokenPipeError) as error:
        logger.exception(error)
        sys.exit()


@logger.catch
def get_balances():
    waves_exch = we.connection()

    try:
        balances = waves_exch.fetchBalance()
    except (MaxRetryError, ConnectTimeoutError, RequestTimeout, NewConnectionError,
            NetworkError, HTTPError, AuthenticationError, ConnectTimeout) as error:
        return submit_report('error', {'error': str(error)})
    except Exception as crash_report:
        logger.exception(crash_report)
        return submit_report('fatal_error', {'fatal_error': str(crash_report)})
    else:
        return submit_report('ok', balances)


@logger.catch
def main(_):
    return get_balances()


if __name__ == '__main__':
    main()

```

According to [https://api.wavesplatform.com/v0/assets/C1iWsKGqLwjHUndiQ7iXpdmPum9PeCDFfyXBdJJosDRS](https://api.wavesplatform.com/v0/assets/C1iWsKGqLwjHUndiQ7iXpdmPum9PeCDFfyXBdJJosDRS)  the ticker for this asset is "EGG" and it's designated as "Duck Egg." It seems, however, that CCXT refers to it as "Waves Ducks." Why the discrepancy?

**Comment by kroitor** [comment]
> Why the discrepancy?

Let us know if the following info does not answer your question:

- https://github.com/ccxt/ccxt/wiki/Manual#notes-on-naming-consistency
- https://github.com/ccxt/ccxt/pull/10422
- https://www.google.com/search?q=EGG+Duck+Egg+cryptocurrency

<img width="880" alt="Screenshot 2021-11-19 at 01 31 42" src="https://user-images.githubusercontent.com/1294454/142507246-bae66ded-45b8-4a0a-93eb-f86eda6d7926.png">

**Comment by ttodua** [comment]
Seems same problem as answered here - https://github.com/ccxt/ccxt/issues/10613#issuecomment-987881770

**Comment by Maxximiliann** [comment]
> Seems same problem as answered here - [#10613 (comment)](https://github.com/ccxt/ccxt/issues/10613#issuecomment-987881770)

What impact, if any, does this have on [#10674](https://github.com/ccxt/ccxt/issues/10674#issue-1060773485)?
