### ISSUE TITLE
Minimize number of requests to an exchange

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#10639]
What is the correct place for defining variable CCXT in a NODEJS website project:

1) bin/www.js 
2) routes/index.js
3) services/index.js
4) app.js

How to correctly define it if a user during a session can change exchange many times.

The questions in context- how to minimize the number of requests to exchange and maximize the use of a cache?

**Comment by YuriyTigiev** [comment]
I had put defining of variable in the services/index.js 
I'm not sure if is it optimal.
Does fetchOHLCV cache data?

```
"use strict"

var ccxt = require('ccxt');
var exchanges = {};
var markets = {};


async function loadMarkets(exchange_id){
    
    let exchange;

    if(!(exchange_id in exchanges)){
        
        exchange = new ccxt[exchange_id](); 
        exchanges[exchange_id] = exchange;
    
    }
    
    if(!(exchange_id in markets)){
        
        exchange = exchanges[exchange_id];
        let market = await exchange.loadMarkets();
        markets[exchange_id] = market;
    
    }

}


async function fetchOHLCV(exchange_id, symbol, timeframe){

    await loadMarkets(exchange_id);

    let since = undefined;
    let limit = 300;

    let response = await exchanges[exchange_id].fetchOHLCV(symbol, timeframe = timeframe, since = since, limit = limit);
    return response;
};

```

**Comment by ttodua** [comment]
The website structure you seem to have, it up to you to decide where/what files you want to have in project, and it's up to your experience/practice how you develop project. 
However, in terms of CCXT re-usability and minimizing odd repeated calls, you'd better to use different approaches: global-scope variable or file-scope variable.  You are doing the latter-one, and seems you have a correct concept chosen in your example (to call already initiated object, instead of re-creating exchange object on every loadMarkets (or other) methods. 
Also, I don't think this part is needed:

```
    if(!(exchange_id in markets)){
        
        exchange = exchanges[exchange_id];
        let market = await exchange.loadMarkets();
        markets[exchange_id] = market;
    
    }
```

as `loadMarkets()` method will be called inside exchange object by itself whenever it decides on its own, if that is needed or not. For example, `exchange.fetchOHLCV` itself calls `loadMarkets()` if it sees that method hasn't been yet fired at least once.

**Comment by kroitor** [comment]
@YuriyTigiev let us know if the above answer does not help. Feel free to reopen it if necessary.

**Comment by YuriyTigiev** [comment]
@ttodua 

I can't understand how the "ccxt" rate limit will work for multiuser sessions.  Can you share a simple project that shows how to better use "ccxt" variable?

**Comment by kroitor** [comment]
@YuriyTigiev in general, you should be making one exchange instance per user and sharing the loaded market info as shown, for example, here: https://github.com/ccxt/ccxt/blob/master/examples/js/shared-load-markets.js

**Comment by kroitor** [comment]
@YuriyTigiev in the snippet above, it is shown how to reuse the already-existing exchange instances for consequent calls, but if you are using different keypairs, then we'd recommend creating one instance per keypair, and sharing the market info across the instances after loading it once.

**Comment by YuriyTigiev** [comment]
@kroitor  thank you for your attention and support. 

The provided code should I merge with existing app.js (+express) or should I write this code on the service logic level?

**Comment by kroitor** [comment]
@YuriyTigiev it depends on how you structure the API. Most of the time the exchange instances will exist on your backend.

**Comment by YuriyTigiev** [comment]
@kroitor  

async function loadExchange (id) {
    try {
        const exchange = new ccxt[id] ({
            'enableRateLimit': true,
        })
        await exchange.loadMarkets ()
        globalExchanges[id] = exchange
    } catch (e) {
        // throw e // uncomment to break the entire program on any error
        // console.log (e) // print the exception and ignore this exchange
    }
}

https://stackabuse.com/using-global-variables-in-node-js/
Now, you might be thinking to yourself that you want to go off and create global variables now that you know more about them. I am going to strongly caution against creating global variables for a few very important reasons..... 
:( :( :( 

https://stackoverflow.com/questions/9765215/global-variable-in-app-js-accessible-in-routes

I'm trying to understand what is the right solution for defining variable "exchanges" considering all aspects.

**Comment by kroitor** [comment]
@YuriyTigiev it depends on the design of your application. We're missing too many details, and we would have to dive into working on your project to tell how to design it exactly. The design questions of your app and your business logic is up to you, assuming you've read the entire Manual and understand the usage and the implications of doing this or that with the lib.
First and foremost, you have to decide where you want to run the above code – on client-side or on your backend. Depending on that, you will have to arrange different kinds of multiuser interactions in your infrastructure.

**Comment by YuriyTigiev** [comment]
@kroitor 

Happy New Year! Best wishes for peace and prosperity in 2022.


I develop an API for sharing public data from any Crypto exchange. Some information I will cache using a Redis and it will reduce loads on the Exchange API. But I don't know how to avoid a case when different users will try to fetch "not cached" data from the exchange API.  From my point of view, I should use a centralized mechanism for rateLimit to access an exchange API. I thought about using a global variable for this, but as I see it is not recommended. I'm looking for another solution for that.

**Comment by ttodua** [comment]
@YuriyTigiev 
Happy New Year, and best wishes ;;

To add my thoughts here, I don't think that is something we could give a perfect direction, as the specific is the place where the developer itself knows ins & outs and has to decide the whole structure himself/herself. What i can say, is that, if you want a common place where users can just request public data, then you might use backend for ccxt , where you initialize the exchange class in Node.js or wherever and have it running uninterruptly.  and to front-end users, it might get requests using AJAX or WS [preferred]. That is all i could suggest.

**Comment by YuriyTigiev** [comment]
> and to front-end users, it might get requests using AJAX or WS [preferred]. That is all i could suggest.

I also think about ccxt.pro version.  If ccxt.pro library could detect missing data in WS source and automate try to fetch it through an exchange API request it could be solution for me. In my understanding, I can set up automatic loading of the OHLCV into the database, and then, as it is ready, take the necessary data from the database and cache it. In this case load on the Exchange API will be minimal.

**Comment by ttodua** [comment]
I thought you already had WS. Yes, in case of WS you might achieve what you want in easier way, as they will send you the last OHLCV (single) object on further updates (however, not all exchanges have WS and moreover ohlcv's).
