### ISSUE TITLE
Meteor Issue: invalid for/in left-hand side in older Firefox and Safari versions

### ISSUE THREAD

**Issue by PolybitSol** [ccxt/ccxt#1065]
Hey,

This may not be a wholly CCXT issue, but I am developing a Meteor application that uses the CCXT library. Everything works perfectly fine on Chrome, but when I load it on Firefox or Safari, I get the following error:

```SyntaxError: invalid for/in left-hand side```

``` 
//merge to this                                     
for (const [property, value] of Object.entries (config))  
    this[property] = deepExtend (this[property], value)
```

- OS: Linux, Firefox & Safari
- Programming Language: JS
- CCXT version: 1.10.521
- Exchange: N/A
- Method: N/A

I've double checked ECMA script is installed, as recommended through research on the issue. Any help would be appreciated! ***Edit: it appears to be older versions of Firefox & Safari only, so it's not a critical issue, but still curious***

**Comment by kroitor** [comment]
Hi! Thank you for reporting this issue! We will add a fix for the issue. I hope to get to it as soon as possible.

**Comment by ttodua** [comment]
Issue is too much old and not reproduceable. Closing this issue for now, but if anyone has any more input on this, feel free to open issue.
