### ISSUE TITLE
OverflowError when I tried to get OHLCV data from buda exchange

### ISSUE THREAD

**Issue by luispsa** [ccxt/ccxt#10659]
Hi, I have this problem when I try to get the OHLC data from the exchange buda, I don't know how to solve it

regards 

- OS: Windows 10
- Programming Language version: Python 3.8.12
- CCXT version: 1.59.69

```
import ccxt

buda= ccxt.buda()
df=buda.fetchOHLCV('LTC/CLP','1d',limit=200)
```

```
OverflowError: cannot convert float infinity to integer
```

**Comment by kroitor** [comment]
@luispsa hi!

Do you have this issue with the most recent version of CCXT (1.61.85+) using this snippet? ↓

```Python
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.buda()
markets = exchange.load_markets()
# exchange.verbose = True  # uncomment for debugging purposes if necessary
ohlcv = exchange.fetchOHLCV('LTC/CLP', '1d', limit=200)
pprint(ohlcv)
```

**Comment by luispsa** [comment]
> @luispsa hi!
> 
> Do you have this issue with the most recent version of CCXT (1.61.85+) using this snippet? ↓
> 
> ```python
> import ccxt
> from pprint import pprint
> 
> print('CCXT Version:', ccxt.__version__)
> 
> exchange = ccxt.buda()
> markets = exchange.load_markets()
> # exchange.verbose = True  # uncomment for debugging purposes if necessary
> ohlcv = exchange.fetchOHLCV('LTC/CLP', '1d', limit=200)
> pprint(ohlcv)
> ```
> 
> If that does not work, please, uncomment the verbose line and paste your verbose request+response here:
> 
> * https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

Hi @kroitor , sorry for not repley before, I just upgraded ccxt to the lastest version and now it's working fine, thanks
