### ISSUE TITLE
Relist BTC-Alpha

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#10654]
Looks like exchange recovered after hacking. I've tried to withdraw some funds and it was withdrawed almost instantly. I think ccxt should relist this exchange

**Comment by frosty00** [comment]
> Looks like exchange recovered after hacking. I've tried to withdraw some funds and it was withdrawed almost instantly. I think ccxt should relist this exchange

yeah they went on maintenance for a month and we weren't sure if they were going to come back, but I agree that we can relist them
