### ISSUE TITLE
A question about initial response from balance endpoint

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#10663]
We used the WS example code for `watchBalance`:

```
const balance = await this.exchange.watchBalance (params);
console.log (new Date (), balance);
```
A specific exchange (let's say gate.io) does return response only when there is change in wallet. Otherwise, when we first start that WS method, we don't get any info of current (initial) balance. Is there any way, to force the ccxt to "get the initial" response to know "how much is the balance now" (after that initial response, then it's ok to get further updates only when there is change in balance).
If there is no way for that, it means that we are forced to use just polling `fetch..` method once to find out the initial balance?

**Comment by kroitor** [comment]
Hi!

Please, check these examples:

- https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/js/binance-fetch-balance-snapshot-watch-balance-updates.js
- https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/binance-fetch-balance-snapshot-watch-balance-updates.py

Let us know if that does not answer your question.
