### ISSUE TITLE
[wavesexchange.py] - waves_exch.createOrder - KeyError: 'EGG/WAVES'

### ISSUE THREAD

**Issue by Maxximiliann** [ccxt/ccxt#10674]
- OS: Ubuntu 20.04.3 LTS
- Programming Language version: Python 3.9.6
- CCXT version: 1.61.98

```
Request: POST http://matcher.waves.exchange/matcher/orderbook {'content-type': 'application/json', 'User-Agent': 'python-requests/2.26.0', 'Accept-Encoding': 'gzip, deflate'} {"senderPublicKey":"**************************","matcherPublicKey":"**************************","assetPair":{"amountAsset":"C1iWsKGqLwjHUndiQ7iXpdmPum9PeCDFfyXBdJJosDRS","priceAsset":""},"orderType":"buy","price":3900000017,"amount":106062997,"timestamp":1637633628162,"expiration":1640052828162,"matcherFee":300000,"signature":"48ZLKzsu1PaJXvyXtAVqi3kvEQpe8t8bJVyXKdF4yJHVNgXvEers2U3NoMQGk6kSRP5efQ9GiF67dVH7fggaJj6X","version":3}

Response: POST http://matcher.waves.exchange/matcher/orderbook 200 {'Server': 'nginx', 'Date': 'Tue, 23 Nov 2021 02:13:52 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'x-span-id': 'fba9e7eec44593be', 'x-trace-id': 'a5c5c5f49a3f9c77', 'matcher-http-server': 'matcher-1', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS, PUT, DELETE', 'Access-Control-Allow-Headers': 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,signature,timestamp', 'Access-Control-Expose-Headers': 'Content-Length,Content-Range', 'Backend': 'unknown', 'Content-Encoding': 'gzip'} {"success":true,"message":{"version":3,"id":"**************************","sender":"**************************","senderPublicKey":"**************************","matcherPublicKey":"**************************","assetPair":{"amountAsset":"C1iWsKGqLwjHUndiQ7iXpdmPum9PeCDFfyXBdJJosDRS","priceAsset":"WAVES"},"orderType":"buy","amount":106062997,"price":3900000017,"timestamp":1637633628162,"expiration":1640052828162,"matcherFee":300000,"matcherFeeAssetId":null,"signature":"48ZLKzsu1PaJXvyXtAVqi3kvEQpe8t8bJVyXKdF4yJHVNgXvEers2U3NoMQGk6kSRP5efQ9GiF67dVH7fggaJj6X","proofs":["48ZLKzsu1PaJXvyXtAVqi3kvEQpe8t8bJVyXKdF4yJHVNgXvEers2U3NoMQGk6kSRP5efQ9GiF67dVH7fggaJj6X"]},"status":"OrderAccepted"}


Traceback (most recent call last):

  File "/home/system/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/ccxt/wavesexchange.py", line 1076, in create_order
    return self.parse_order(value, market)
           │    │           │      └ {'percentage': True, 'precision': {'amount': 8, 'price': 8}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min'...
           │    │           └ {'version': '3', 'id': '**************************', 'sender': '**************************', 'send...
           │    └ <function wavesexchange.parse_order at 0x7f84f84a3790>
           └ ccxt.wavesexchange()
  File "/home/system/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/ccxt/wavesexchange.py", line 1287, in parse_order
    price = self.price_from_precision(symbol, priceString)
            │    │                    │       └ '3900000017'
            │    │                    └ 'EGG/WAVES'
            │    └ <function wavesexchange.price_from_precision at 0x7f84f84a3310>
            └ ccxt.wavesexchange()
  File "/home/system/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/ccxt/wavesexchange.py", line 911, in price_from_precision
    market = self.markets[symbol]
             │    │       └ 'EGG/WAVES'
             │    └ {'WAVES/BTC': {'percentage': True, 'precision': {'amount': 8, 'price': 8}, 'limits': {'amount': {'min': None, 'max': None}, '...
             └ ccxt.wavesexchange()

KeyError: 'EGG/WAVES'

```

**Comment by frosty00** [comment]
have you tried doing `DUCK/WAVES` instead?

**Comment by frosty00** [comment]
https://github.com/ccxt/ccxt/issues/10636

**Comment by Maxximiliann** [comment]
> have you tried doing `Waves Ducks/WAVES` instead?

`Response: POST http://matcher.waves.exchange/matcher/orderbook 200 {'Server': 'nginx', 'Date': 'Tue, 23 Nov 2021 02:13:52 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'x-span-id': 'fba9e7eec44593be', 'x-trace-id': 'a5c5c5f49a3f9c77', 'matcher-http-server': 'matcher-1', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS, PUT, DELETE', 'Access-Control-Allow-Headers': 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,signature,timestamp', 'Access-Control-Expose-Headers': 'Content-Length,Content-Range', 'Backend': 'unknown', 'Content-Encoding': 'gzip'} {"success":true,"message":{"version":3,"id":"**************************","sender":"**************************","senderPublicKey":"**************************","matcherPublicKey":"**************************","assetPair":{"amountAsset":"C1iWsKGqLwjHUndiQ7iXpdmPum9PeCDFfyXBdJJosDRS","priceAsset":"WAVES"},"orderType":"buy","amount":106062997,"price":3900000017,"timestamp":1637633628162,"expiration":1640052828162,"matcherFee":300000,"matcherFeeAssetId":null,"signature":"48ZLKzsu1PaJXvyXtAVqi3kvEQpe8t8bJVyXKdF4yJHVNgXvEers2U3NoMQGk6kSRP5efQ9GiF67dVH7fggaJj6X","proofs":["48ZLKzsu1PaJXvyXtAVqi3kvEQpe8t8bJVyXKdF4yJHVNgXvEers2U3NoMQGk6kSRP5efQ9GiF67dVH7fggaJj6X"]},"status":"OrderAccepted"}`


This confirmation message suggests the EGG/WAVES order was successfully placed.

**Comment by Maxximiliann** [comment]
> have you tried doing `Waves Ducks/WAVES` instead?

What's causing the key error if the order for EGG/WAVES was successfully placed?

**Comment by frosty00** [comment]
`Waves Ducks/WAVES = EGG/WAVES` 

`Waves Ducks = EGG`

same thing

**Comment by Maxximiliann** [comment]
> `Waves Ducks/WAVES = EGG/WAVES`

Right, so if the order was accepted by the exchange, why was there a key error?

**Comment by Maxximiliann** [comment]
@kroitor 

Thank you for taking another look at this issue. Is there a way to get notified when a solution is pushed?

**Comment by kroitor** [comment]
@Maxximiliann as the author, you're already subscribed to this issue, and you will get notified automatically when the issue is closed (that means it's solved).

**Comment by ttodua** [comment]
Seem this was fixed (related : https://github.com/ccxt/ccxt/pull/10800) and you can no longer place order with 'EGG/WAVES' from CCXT. (before making request, it will throw 'market not found' error). You will need to use that pair name as @frosty00 has mentioned.

Re-open the issue if you face further issues with latest versions of ccxt.
