### ISSUE TITLE
Any suggestion for 502 Server Errors?

### ISSUE THREAD

**Issue by allenfrostline** [ccxt/ccxt#1067]
It happens rarely but indeed it is an issue that needs to be considered when wrapping this package into a trading bot. I'm thinking about delayed recursions in error handling but apparently that's quite brute a solution.

**Comment by kroitor** [comment]
A suggestion would be to recover from a NetworkError with a delayed retry with backoff, or to crash on ExchangeError. The retry mechanism is not built into the library, but we are working on it as well, [here](https://github.com/ccxt/ccxt/issues/961). Does this answer your question?

**Comment by allenfrostline** [comment]
Thanks that's exactly what I was thinking about :)

**Comment by kroitor** [comment]
Ok, cool. The error hierarchy is outlined here: https://github.com/ccxt/ccxt/wiki/Manual#error-handling. I would close this for now, if you don't mind. Let us know if you have more questions, feel free to reopen it if needed.
