### ISSUE TITLE
Get a list of coins presented on the exchange.

### ISSUE THREAD

**Issue by leonid-varygin** [ccxt/ccxt#10679]
Hello.  How can i get all the coins that are currently traded on the exchange?  I just need a list of coins

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
- https://github.com/ccxt/ccxt/wiki/Manual#currency-structure
- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/
- https://readthedocs.org/projects/ccxt/
