### ISSUE TITLE
Gate.io does only load one market type

### ISSUE THREAD

**Issue by ChristianCoenen** [ccxt/ccxt#10680]
- CCXT version: 1.62.5

I observed that the Gate.io implementation just fetches the spot markets by default while other market types have to be loaded via the ```params``` parameter. This is opposed to other implementations like OKEx, where all pairs for ALL market types are fetched and combined from multiple endpoints:

OKEx
```python
async def fetch_markets(self, params={}):
    types = self.safe_value(self.options, 'fetchMarkets')
    result = []
    for i in range(0, len(types)):
        markets = await self.fetch_markets_by_type(types[i], params)
        result = self.array_concat(result, markets)
    return result
```

Gate.io
```python
async def fetch_markets(self, params={}):
    # :param params['type']: 'spot', 'margin', 'futures' or 'delivery'
    # :param params['settle']: The quote currency
    defaultType = self.safe_string_2(self.options, 'fetchMarkets', 'defaultType', 'spot')
    .
    .
    .
    method = self.get_supported_mapping(type, {
        'spot': 'publicSpotGetCurrencyPairs',
        'margin': 'publicMarginGetCurrencyPairs',
        'swap': 'publicFuturesGetSettleContracts',
        'futures': 'publicDeliveryGetSettleContracts',
    })
    .
    .
    .
```

The current implementation for Gate.io results in the problem that oscillating between different markets results in constant market reloads instead of loading all markets once and then using the locally saved data.

**Comment by kroitor** [comment]
Gate.io's API serves conflicting market ids between spot, and perpetual swaps. That makes it impossible to preload and recognize both types of markets at the same time. This is the same as with Binance, Huobi and many other exchanges. The usual recommended workaround is to instantiate one exchange instance per type, using the `exchange.options['defaultType']`: 

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/gateio.py#L320

```Python
import ccxt
spot = ccxt.gateio({'options':{'defaultType':'spot'}})
futures = ccxt.gateio({'options':{'defaultType':'futures'}})
swap = ccxt.gateio({'options':{'defaultType':'swap'}})

# ...
```

Let us know if that does not answer your question.
