### ISSUE TITLE
Any way to add "synthetic" timestamp?

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#10689]
Let's say we have:
```
for (i=0; i<5; i++)
   ex.fetchOrderBook('btc/usdt').then(myParseOB);
   phseudo_sleep(100); 
}

function myParseOB(resp){
   this.OB = resp;
}
```

in our app, we reply OB to be the latest, and for that, we depend on `.timestamp` property of response. However, with some exchanges, (i.e. gate.io) it is 'undefined' and thus, returned 5 calls are in not chronological orders sometimes. (i.e. the 5th sent request might return response earlier then 3rd request)

What is your advise to make their responses chronologically sorted? I've been thinking if there is any internal property in ccxt (or maybe somewhere in headers), like  `exchange.Request_Start_Time_Of_Last_Received_Response` would have been very useful, for many different ccxt methods, to make them datestamped, when exchange doesn't give any timestamp.

**Comment by frosty00** [comment]
I think maybe we should try to parse the info from the response headers

**Comment by frosty00** [comment]
```
{
  'Access-Control-Allow-Headers': 'DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type',
  'Access-Control-Allow-Methods': 'GET,POST,OPTIONS,DELETE,PUT',
  'Access-Control-Max-Age': '1728000',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json',
  Date: 'Wed, 24 Nov 2021 00:47:01 GMT',
  Server: 'openresty',
  'Transfer-Encoding': 'chunked',
  Vary: 'Origin',
  'X-Request-Id': '[3eaf6b34-4236365582]'
}
```

cause gateio does provide the timestamp in the `fetchOrderBook` response in the headers technically, it's just that we currently only parse the response body, I'll have a think but it shouldn't be impossible to solve

**Comment by frosty00** [comment]
basically instead of returning a json string from the unified api we should return an object that has the json response as well as the headers

**Comment by kroitor** [comment]
@frosty00 i don't think that we should use the HTTP response timestamp as the orderbook timestamp – they have different semantics. The question is whether we can set the orderbook timestamp to `exchange.milliseconds()` conditionally (depending on a user-supplied option).

**Comment by frosty00** [comment]
@kroitor I think it is ok if we do it were it is undefined, cause at the end of the day that is the timestamp of the response coming from the http server, it may be less precise than the backend timestamp but it is better than nothing imo

**Comment by kroitor** [comment]
@frosty00 i think, we should not mix the order book timestamps with the http timestamps – that might unintentionally propagate a wrong impression to the user. If the orderbook has not been updated for long, and the http timestamp changes, the user will still think that the orderbook is changing – that is not what we want and it's not what the user really wants. Mixing the two unrelated timestamps is just plain wrong semantically.

**Comment by frosty00** [comment]
i think the timestamp coming from the exchange has nothing to do with when it was last updated but rather when the exchange processed the request, there's actually a lot of data in the headers including relevant rate limiting data

see https://github.com/ccxt/ccxt/pull/10693

**Comment by frosty00** [comment]
if the exchange replies with a stale orderbook then that is a wtf from the exchange

**Comment by frosty00** [comment]
but i believe that parsing the http header is better than leaving it undefined

**Comment by kroitor** [comment]
> i think the timestamp coming from the exchange has nothing to do with when it was last updated

Exactly! And if you follow this logic: 

1. the meaning of the orderbook timestamp is _"when it was last updated"_
2. the meaning of the http timestamp is _"when the exchange generated the response"_

Which is why we return both, and don't mix them. If (1) is undefined – (2) is still available to the user through `last_response_headers`. We provide both timestamps, but don't treat one as the other.
> if the exchange replies with a stale orderbook then that is a wtf from the exchange

If we put the HTTP timestamp into the orderbook['timestamp'] - that is a wtf from us.

**Comment by frosty00** [comment]
>>  if the exchange replies with a stale orderbook then that is a wtf from the exchange

> If we put the HTTP timestamp into the orderbook['timestamp'] - that is a wtf from us.

not really, cause if you think about it, would you rather receive some data with no timestamp in an async context, wtf is this data coming in? or would you rather have the timestamp of the http server?

> If (1) is undefined – we should tell the user the real truth.

it's not the real truth, the http server timestamp is a valid timestamp that exists

**Comment by kroitor** [comment]
> not really, cause if you think about it, would you rather receive some data with no timestamp in an async context, wtf is this data coming in? or would you rather have the timestamp of the http server?

I'd let the user decide.

>> If (1) is undefined – we should tell the user the real truth.

> it's not the real truth, the http server timestamp is a valid timestamp that exists

It's invalid in terms of the meaning of (1).

**Comment by frosty00** [comment]
anyway the http server should call the backend so the timestamp is pretty accurate

**Comment by frosty00** [comment]
> the meaning of the orderbook timestamp is "when it was last updated" – served in orderbook['timestamp'] if known

it's not the case for all exchanges, it can also mean "current server time"

**Comment by kroitor** [comment]
> anyway the http server should call the backend so the timestamp is pretty accurate

It becomes inaccurate if the orderbook was not updated for long (if trades are rare or if volumes are low),

**Comment by frosty00** [comment]
> it can also mean "current server time"

**Comment by frosty00** [comment]
in fact i think this usage is probably more common that lastUpdated timestamp

**Comment by kroitor** [comment]
@frosty00 let's first agree on the first fact that defines everything else in this discussion: the `orderbook['timestamp']` is not the response time, it's the timestamp when the orderbook was actually updated (if defined by the exchange). That timestamp may be in the past, and that information may be missing. From there it follows that we should not put anything there, if the exchange does not provide an orderbook['timestamp']. Some users might want to put the http response timestamp into the orderbook['timestamp'] – and we can support that, but that must be optional, and should not be the default behavior for 100%.

**Comment by frosty00** [comment]
> @frosty00 let's first agree on the first fact that defines everything else in this discussion: the `orderbook['timestamp']` is not the response time, it's the timestamp when the orderbook was actually updated (if defined by the exchange). That timestamp may be in the past, and that information may be missing. From there it follows that we should not put anything there, if the exchange does not provide an orderbook['timestamp']. Some users might want to put the http response timestamp into the orderbook['timestamp'] – and we can support that, but that must be optional, and should not be the default behavior for 100%.

it depends on the exchange, it might be the last updated time or the current server time depending on each specific exchange, there is examples of both in the code

**Comment by kroitor** [comment]
> it depends on the exchange, it might be the last updated time or the current server time depending on each specific exchange, there is examples of both in the code

**If provided** by the exchange – that is out of the question, cause that should be ok and should be put in `orderbook['timestamp']` – that is what the exchange reports after all. What i'm trying to say is that we should not put it there **if it is not provided**.

**Comment by frosty00** [comment]
if the http server provides it then we can put it there imo, cause we can assume the http server and backend are in sync

**Comment by kroitor** [comment]
> cause we can assume the http server and backend are in sync

I think assuming that would be wrong.

**Comment by frosty00** [comment]
it's better than generating the timestamp on the client side, cause that's nonsense imo

**Comment by kroitor** [comment]
@frosty00 it must be optional and switched off by default.

**Comment by frosty00** [comment]
i don't think that it is a bad thing though, i'd rather have the http server time that nothing

**Comment by frosty00** [comment]
how is leave the timestamp undefined better than falling back to the date header

**Comment by kroitor** [comment]
@frosty00 

> how is leaving the timestamp undefined better than falling back to the date header

I've explained above. Serving the old orderbook with a falsy new timestamp – is wrong for synchronization purposes. We won't do that.

**Comment by frosty00** [comment]
ok that's fair enough, i guess it is possible for the http server and backend to be out of sync if the server is caching stuff

**Comment by kroitor** [comment]
@frosty00 yes, we can make this feature optional, if the user really wants falsy timestamps but that should be switched off by default. I'm not sure why would one want that feature tho, cause if you think of it, it will be less informative when it comes to the actual true state of the orderbook.

**Comment by kroitor** [comment]
@frosty00 we could add the optional feature for ws-purposes, and that would be the timestamp when the last updated was received (if the update itself didn't contain a timestamp inside it).

**Comment by ttodua** [comment]
Sorry for kicking in. I definitely agree with Kroitor, there is jot doubt
in with what kroitor says, and no probably no need for further discussion.
Data of any event shouldnt be ever treated to be 'better than nothing' by
default.  The default behavior of data should be to show whatever it is
meant to do.  by default, when I ask X exchange  about Y data, ccxt should
provide whatever server responses and whatever balues should have been
provided if i called different API client too.
default behavior of API CLIENT shouldnt be to add any data on its own.
That is solely the user-decision to change that behavior consiously, and
thus, there should be a 'setting' to be turned on, which would change that
behavior and set timestamp to server request. or you can add extra
parameter named 'serverTime' in response. So, user needs to have a
solution.  but dont change 'timestamp' property by default.

**Comment by kroitor** [comment]
@ttodua thx for your input! We appreciate your feedback!

**Comment by ttodua** [comment]
so, what you've decided? will there be added any additional property in ccxt's orderBook object, like 'responseTimestamp' or not?
if this idea is under "wont-fix" status, then can you tell how to parse response header manually? i.e. `this.last_response_headers.Date` ?  (but it doesnt have milliseconds part, which is important in this case)

**Comment by ttodua** [comment]
@frosty00 @kroitor 
Have you decided anything for this topic, or not yet? will there be added any additional property in ccxt's response objects, like 'responseTimestamp' or not?
if this idea is under "wont-fix" status, then can you tell how to parse response header manually? i.e. `this.last_response_headers.Date` ?  (but it doesnt have milliseconds part, which is important in this case)

**Comment by frosty00** [comment]
closing this issue for now as it seems we will not add more timestamps
