### ISSUE TITLE
Binance privatePostUserDataStream returns 404

### ISSUE THREAD

**Issue by rasmustaarnby** [ccxt/ccxt#1068]
Hi, 

It seems that Binance has yet to move their user data stream api to v3. 

When posting to `https://api.binance.com/api/v3/userDataStream` using the method `privatePostUserDataStream` it returns a 404. 

When posting to `https://api.binance.com/api/v1/userDataStream` I get a a different error, which I'm unsure is a ccxt or binance bug. 

Error:
```
{"code":-1101,"msg":"Too many parameters; expected '0' and received '3'."}
```

- Programming Language: PHP
- CCXT version: 1.10.561
- Exchange: Binance
- Method: privatePostUserDataStream

**Comment by kroitor** [comment]
Hi! Thanks for reporting! I will take a look into it and will get back to you shortly.
