### ISSUE TITLE
dynamic watch ticker solution?

### ISSUE THREAD

**Issue by ghost** [ccxt/ccxt#10686]
Hello, 

I was thinking to create little bit more complex solution to watch ticks, where I would be able to create something like a dynamic tick watcher. With dynamic I mean to define which exchange + symbol I want to watch while the loop is already running.

I created script where I am watching ticks from multiple exchanges and symbols based on this example
https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/many-exchanges-many-different-streams.py

But I would like to have an option to add or remove tick watchers for different symbols in different exchanges while the loop is already running. I would really appreciate any idea of a solution but my main focus is to have this solution in python. 

Thank you for answer

**Comment by mvazny** [comment]
Hello @kroitor , I know you have a lot on your mind but did you came with any idea?

**Comment by ttodua** [comment]
The abortion of already running loop is not yet documented. _(however, this is related: https://github.com/ccxt/ccxt/issues/10786 )_

**Comment by kroitor** [comment]
@mvazny pardon for the long wait, I'll post an example on how to add watchTicker loops in runtime here.

**Comment by avmarko** [comment]
Are there regarding or similar to this thread ?
Is there any example on how to add/remove watchTicker loops in runtime?

**Comment by ttodua** [comment]
late reply here, but for context, after that period in ccxt we added `watchTickers` for many exchanges, so you can use that method.
some notes when using `watchTickers`:
- some exchanges might be able to watch all tickers, so you can just skip the symbol which you don't want
- if exchange requires list of symbols, then you can easily amend the symbols during runtime, smth like this example:
```
const ex = new ccxt.pro.binance();
let mySymbols = ['BTC/USDT', 'ETH/USDT'];

async function myWatch () {
    while(true) {
        const result = await ex.watchTickers (mySymbols);
        console.log(result);
    }
}
   
function modifyFunc () {
  mySymbols = ['SOL/USDT']; // etc... modified in another place during runtime
} 

async main() {
    myWatch ();
    await ex.sleep(5000);
    modifyFunc ();
}

main();
```
