### ISSUE TITLE
gateio kline.subscribe invalid argument

### ISSUE THREAD

**Issue by yanking** [ccxt/ccxt#10683]
- OS: MacBook Pro
- Programming Language version: node v14.17.3
- CCXT Pro version: 0.9.15
- error
```
const candles = await this.exchangeWatch.watchOHLCV('BTC/USDT','1m');
```
```
2021-11-23T11:31:00.434Z onMessage {
  error: { code: 1, message: 'invalid argument' },
  result: null,
  id: 1637667059
}
```

**Comment by ttodua** [comment]
Please try latest ccxt.pro version `0.9.41`.
if still any issue, can you provide more details, i.e. if you are running other watch functions in your code? To ensure that is coming exactly from that function

**Comment by ttodua** [comment]
I've reproduced the issue. Will submit fix soon.
