### ISSUE TITLE
Issue with timeout

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#10706]
I am getting the timeout exception, without having a way to catch it, and it exits whole application.
...
setInterval(  myWalletFetch, 1000);
...
isInsideWalletFetch : false,
myWalletFetch(){
		try{
			if (this.isInsideWalletFetch) return;
			this.isInsideWalletFetch = true;
			let prom = exchange.fetchBalance(); 
			c("Wallet Requestedd");
			prom.then(this.Wallet_received); 
		}
		catch(ex){
			c(ex);
		}
}

	Wallet_received(response){ 
		console.log("Wallet  received");
		...self....isInsideWalletFetch = false;
	}, 

however, after around 5-10th cycle, it exits whole application with exception `RequestTimeout: kucoin GET https://openapi-v2.kucoin.com/api/v1/accounts?type=trade request timed out (10000 ms)
    at ..node_modules\ccxt\js\base\Exchange.js:438:27`

My concern is why i cant (or how to) catch that exception, so avoided it breaking whole running application.

**Comment by kroitor** [comment]
You are not catching the exception.
There's two styles of async syntax – promise-based `.then()` and `.catch()` and `async/await` wrapped in a try-catch block.

```JavaScript
...
setInterval(  myWalletFetch, 1000);
...
isInsideWalletFetch : false,
myWalletFetch(){
		try{
			if (this.isInsideWalletFetch) return;
			this.isInsideWalletFetch = true;
			let prom = exchange.fetchBalance(); 
			c("Wallet Requestedd");
			
			//
			// you are launching a promise-based async call here without catching the exception
			//          ↓
			prom.then(this.Wallet_received);  
		}
		catch(ex){
			c(ex);
		}
}

	Wallet_received(response){ 
		console.log("Wallet  received");
		...self....isInsideWalletFetch = false;
	}, 
```

In order to fix the above, you should rewrite the above snippet in one of the following ways:

```JavaScript
prom.then(this.Wallet_received).catch(error => {
    // YOUR ERROR REACTION HERE
})
```

or

```JavaScript
try {
    const response = await prom
    this.Wallet_received(response)
} catch (e) {
    // YOUR ERROR REACTION HERE
}
```

Hope that answers your question, let us know if not.

**Comment by ttodua** [comment]
ouch, thanks!!! (btw, sorry for formatting, i've only seen at this moment that i havent had used code-block properly.)

**Comment by ttodua** [comment]
@kroitor I am seeing the obvious issue. Even though I've solved that problem and exceptions are being catched, specifically kucoin has issue in ccxt (i dont know where problem arises).
for example, if you run even 2000ms interval to get balance, after around 10 or 15th call, (or earlier even) the 'await fetchBalance()` enters in hanged state (and later returning `request timeout...` message, mentioning 10000ms). the Rate-limit is not such strict to forbid getting balance once in every 2 seconds. So, there is somewhat I couldnt solve.

**Comment by kroitor** [comment]
@ttodua this is a known issue with kucoin: #10273 (it's on the exchange side).
