### ISSUE TITLE
New Exchange: Etherdelta

### ISSUE THREAD

**Issue by Yayap13** [ccxt/ccxt#1071]
Thank you very much for this amazing library.

I would like to make a suggestion of a new exchange: Etherdelta. It's a decentralized trading platform for Ether and Ethereum-based tokens.

This is the website: https://etherdelta.com/

This is the API documentation site: https://github.com/etherdelta/etherdelta.github.io/blob/master/docs/API.md

Thank you!!

**Comment by kroitor** [comment]
Duplicate:
- https://github.com/ccxt/ccxt/issues/715
- https://github.com/ccxt/ccxt/issues/404
