### ISSUE TITLE
Invalid Parameter error ccxt coinex

### ISSUE THREAD

**Issue by Abdulhadi77** [ccxt/ccxt#10729]
self.exchange  = ccxt.coinex({
                'apiKey': "",
                'secret': "",
                })

side = 'buy'
self.market = 'CERE/USDT'
price = 1.838391
self.amount = 5
self.exchange.create_order(symbol=self.market,type='limit',side=side,amount=self.amount,price=price)["id"]

What is wrong with this code?

The error exactly is in this line 
response = getattr(self, method)(self.extend(request, params))
from the coinex.py file in ccxt library

**Comment by kroitor** [comment]
@Abdulhadi77 what is your version of CCXT? Can you please enable the verbose mode and paste your verbose log output? We need the following info to be able to help:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by Abdulhadi77** [comment]
Thank you for your comment, I enabled the verbose mode and I am debugging it.

**Comment by Abdulhadi77** [comment]
I enabled the verbose mode and the problem is that the price was negative so I got the Invalid Parameter error.

**Comment by Abdulhadi77** [comment]
Just faced another problem that 'coinex' object has no attribute 'cancel_all_orders
How can I cancel all orders using ccxt?
