### ISSUE TITLE
How to fetch available contracts balance from Binance Coin-M (Delivery type)

### ISSUE THREAD

**Issue by SreekanthAvala** [ccxt/ccxt#10724]
Hi Team, Greetings of the day!

- OS: Windows and Linux
- Programming Language version: Python 3.9.6
- CCXT version: 1.55.15

I have been trying to fetch the available contracts balance from Binance Coin-M (Delivery type), It will be great if you provide with api information if any available or any manual calculations information to achieve this.

Thanks.

**Comment by kroitor** [comment]
Make sure to upgrade your version of CCXT to the latest (1.62.42+)

- https://github.com/ccxt/ccxt/wiki/Manual#account-balance

```Python
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binancecoinm({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
markets = exchange.load_markets()
# exchange.verbose = True  # uncomment for debugging purposes if necessary
balance = exchange.fetch_balance()
pprint(balance)
```

**Comment by SreekanthAvala** [comment]
Hi @kroitor , Thankyou for quick response, I have implemented the above code into our logic and when we fetched the above url was returning the actual available balance based on asserts.

With this balance how can get the number of contracts ? 
For ex: From the above url we got to know 9.x btc balance available, How can we get equivalent number of contracts in BTCUSD

**Comment by kroitor** [comment]
@SreekanthAvala you can multiple and divide that by the contract size that you can obtain by loading the markets. In general, I would highly recommend reading the entire Manual from top to bottom, it will really save your time:

- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/
