### ISSUE TITLE
binance STOP_LOSS_LIMIT / STOP_LOSS throws ExchangeNotAvailable

### ISSUE THREAD

**Issue by phrazer** [ccxt/ccxt#1073]
when you try to make order on binance with 'STOP_LOSS_LIMIT' OR 'STOP_LOSS' it gives you this error back:

timestamp=1515116484446&symbol=SUBBTC&quantity=10&type=STOP_LOSS_LIMIT&side=SELL&price=0.00019000&timeInForce=GTC&stopPrice=0.0001900&recvWindow=10000000&signature=3a.......

PHP Fatal error:  Uncaught ccxt\ExchangeNotAvailable: binance POST https://api.binance.com/api/v3/order **400 not accessible from this location at the moment in** /home/work/wildcard/crypto.lab/ccxt/php/Exchange.php:665

- OS: Linux/PHP
- Programming Language:PHP
- CCXT version: Version 1.10.1 2017-11-06
- Exchange: binance
- Method:

```
↑↑↑ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE

MUST_READ_THIS https://github.com/kroitor/ccxt/wiki/Manual#troubleshooting

REPLACE_WITH_YOUR_CODE_TO_REPRODUCE_THE_BUG_HERE

example 1: ccxt.poloniex ({'verbose': True}).fetchTicker ('ETH/BTC')

example 2: exchange = ccxt.bittrex ()
           exchange.verbose = True
           exchange.fetchOrderBook ('ETH/BTC')

REPLACE_WITH_YOUR_VERBOSE_OUTPUT_HERE

↓↓↓ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE
```

**Comment by phrazer** [comment]
strangly other variants are working. like TAKE_PROFIT_LIMIT and TAKE_PROFIT

**Comment by kroitor** [comment]
Can you post your code to reproduce the problem (the minimal executable script) ? Thx!

**Comment by phrazer** [comment]
ofcourse...

is this enough?
  //$sell = array('type' => 'STOP_LOSS_LIMIT', 'stopPrice' => '0.0001900');
  //$binance->create_order('SUB/BTC', 'limit', 'sell', 10, 0.0001900, $sell);

this twostrangly work:
  //$buy = array('type' => 'TAKE_PROFIT_LIMIT', 'stopPrice' => '0.0000900');
  //$binance->create_order('SUB/BTC', 'limit', 'buy', 20, 0.0000800, $buy);
    
  //$sell = array('type' => 'TAKE_PROFIT_LIMIT', 'stopPrice' => '0.0001900');
  //$binance->create_order('SUB/BTC', 'limit', 'sell', 10, 0.0001890, $sell);

dont know if its temp binance thing, or something else?

**Comment by kroitor** [comment]
@phrazer can you please update to most recent version of ccxt and show your verbose output with the same code (set `array('verbose' => true)` in constructor params)?

**Comment by frosty00** [comment]
@kroitor pls close
