### ISSUE TITLE
Trying to pull data at a specific time for library users.

### ISSUE THREAD

**Issue by usai-dns** [ccxt/ccxt#10737]
I'm building an alert bot for a finance server. I'm recently changing from Crypto Compare over to CCXT, and I see there are a lot of robust features for historical data - but I can't find helpful documentation on this specific use:

Users enter an asset, a time interval, and a percentage over which they want to get alerted. I have all the logic developed, but switching the CCXT, I need to know how to get an asset close price on an exchange, say 4 hours ago, or 48 hours ago. I see I can pull the whole series of data, but I literally just need the close price X hours or X days ago. The function pulls current and historical price, for all assets in the portfolio and flags triggers for assets over their threshold percentage. 

Can anyone help me with that? Much appreciated.

- OS: Pop OS
- Programming Language version: Python 3.9.6
- CCXT version: 1.62.56

**Comment by kroitor** [comment]
You will have to use the OHLCV candlestick charts (https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts) and you will also have to apply date-based `pagination` (https://github.com/ccxt/ccxt/wiki/Manual#pagination to obtain the statistical results around the datetime of your interest, and then filter those results for your specific datetime using standard means of your programming langue to shuffle the data according to your needs. So, it's a cascading process. You can find a lot of examples here: 

- https://github.com/ccxt/ccxt/tree/master/examples
- https://github.com/ccxt/ccxt/tree/master/examples/py
- https://github.com/ccxt/ccxt/tree/master/examples/#see-also

All the docs are here:

- https://docs.ccxt.com/

Let us know if that does not answer your question.

**Comment by usai-dns** [comment]
so use Cryptocompare?
