### ISSUE TITLE
ccxt.pro  Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'prototype')  

### ISSUE THREAD

**Issue by minm2015** [ccxt/ccxt#10748]
环境  react + node.js 
使用 import ccxtpro from 'ccxt.pro'
提示 Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'prototype')

**Comment by minm2015** [comment]
Can the author provide react examples

**Comment by kroitor** [comment]
@minm2015 hi! Does it work for you outside of TypeScript in pure JS? Have you installed it properly: https://github.com/ccxt/ccxt/wiki/ccxt.pro.install ?

Run this snippet in node:

```JavaScript
const ccxtpro = require('ccxt.pro')
console.log (ccxtpro.version)
```

**Comment by minm2015** [comment]
install  suceess 
![image](https://user-images.githubusercontent.com/19508192/144251241-71715a95-a8b7-4965-bd23-c20ffc13ed3d.png)

// import ccxt from 'ccxt';
It worked when I introduced it this way

// import ccxtpro  from 'ccxt.pro';
It failed when I introduced it this way


My English is poor, I hope you know what I mean

**Comment by minm2015** [comment]
![image](https://user-images.githubusercontent.com/19508192/144252355-504bc9e5-8349-4cc2-8701-984b37431483.png)

**Comment by minm2015** [comment]
![image](https://user-images.githubusercontent.com/19508192/144252513-3f07d8ba-9fed-48ac-9169-b46770d60174.png)

**Comment by kroitor** [comment]
@minm2015 

This issue might be related and might be the answer to your question:

- https://github.com/ccxt/ccxt/issues/9208

The support for TypeScript is currently rudimentary in both CCXT and CCXT Pro. Your URL to the repository does not look correct: https://github.com/ccxt/ccxt/wiki/ccxt.pro.install#javascript-dependency

Having it installed, you should be able to use CCXT Pro as shown in the examples: https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro/js

What is your output from the snippet posted here: https://github.com/ccxt/ccxt/issues/10748#issuecomment-983565757 ?

P.S. Please, don't paste text as images, always paste text as text. Use GitHub markdown for readability, surround your copypasted output with triple backticks (\`\`\`). Don't confuse backticks (\`) with quotes (\').

\`\`\`
YOUR OUTPUT
\`\`\`

**Comment by kroitor** [comment]
Also related: 

- https://github.com/ccxt/ccxt/issues/9623

**Comment by ttodua** [comment]
@minm2015 Feel free to reopen the issue if you think you question is still unanswered.
