### ISSUE TITLE
Symbol in CCXT Okex

### ISSUE THREAD

**Issue by clem921** [ccxt/ccxt#10740]
A change was introduced in okex version 1.60.75 changing how the symbol is comptued and leads to inconsistencies. For example, the symbol for a future is now "LINK/USDT:USDT-211231" instead of LINK-USDT-211231 in the version 1.60.71 and before.

This new symbol format is inconsistent when we launch request to other endpoint. The format to send is the LINK-USDT-211231.

Problem seems to be located here :
 
symbol = base + '/' + quote
expiry = None
        if contract:
            symbol = symbol + ':' + settle
            expiry = self.safe_integer(market, 'expTime')
            if expiry is not None:
                ymd = self.yymmdd(expiry)
                symbol = symbol + '-' + ymd
            if option:
                strikePrice = self.safe_string(market, 'stk')
                optionType = self.safe_string(market, 'optType')
                symbol = symbol + '-' + strikePrice + '-' + optionType

Regards

**Comment by kroitor** [comment]
Hi!

Please, check this link: https://github.com/ccxt/ccxt/wiki/Manual#contract-naming-conventions

Let us know if that does not answer your question.

In any case, it should work with exchange-specific market ids and with CCXT unified symbols as well:

```Python
import ccxt
from pprint import pprint
exchange = ccxt.okex()
markets = exchange.load_markets()
unified = exchange.market('LINK/USDT:USDT-211231')  # unified symbol
pprint(unified)
specific = exchange.market('LINK-USDT-211231')  # exchange-specific market id
pprint(specific)
```

This is covered in the Manual here:

- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
- https://github.com/ccxt/ccxt/wiki/Manual#methods-for-markets-and-currencies

In general, we highly recommend reading the entire Manual from top to bottom – it will really save your time.

**Comment by frosty00** [comment]
@clem921 actually both symbol formats are supported. `LINK-USDT-211231` is the market id, whereas `LINK/USDT:USDT-211231` is the unified market. You may call either:

```
okex.fetchTicker ('LINK-USDT-211231')

okex.fetchTicker ('LINK/USDT:USDT-211231')
```

and they will both have the same result. We believe including the settlement currency in the symbol makes for easier distinction between linear and inverse futures. Check out https://docs.ccxt.com/en/latest/manual.html#contract-naming-conventions
