### ISSUE TITLE
Okex fees

### ISSUE THREAD

**Issue by clem921** [ccxt/ccxt#10741]
In okex.py, fees are set constant at the beginning for each product class :
                'futures': {
                    'taker': self.parse_number('0.0005'),
                    'maker': self.parse_number('0.0002'),

But the fees depends also on the currency. For example, ADA, DOT , FIL, LINK have lower fees (https://www.okex.com/fr/fees.html)
->                'futures': {
                    'taker': self.parse_number('0.0003'),
                    'maker': self.parse_number('0.00015'),

Is it possible to distinguish between currency to get the real fees ?

**Comment by ttodua** [comment]
The endpoint seems to exist in official API to call  :
https://www.okex.com/docs-v5/en/#rest-api-account-get-fee-rates

at this exact moment, you are able to call and get fees structure:

`console.log ( await exch.privateGetAccountTradeFee (instType:"FUTURES",category:1}) ) `  //or category:2  or whatever, as DOC says.
However, at this moment CCXT doesn't have inner handling of fees for okex exchange.
