### ISSUE TITLE
[okex] Networks indexed improperly

### ISSUE THREAD

**Issue by krychla1** [ccxt/ccxt#10751]
Dear fellows,
okex.js -> options

```                
'networks': {
    'ETH': 'ERC20',
    'TRX': 'TRC20',
    'OMNI': 'Omni',
},
```
are indexed wrongly, the networks in other parts of ccxt (exchange.currencies.networks for example) are indexed by ERC20, TRC20, etc.
I suggest to unify it (e.g. binance, kucoin, etc):
```javascript
binance: 
                'networks': {
                    'ERC20': 'ETH',
                    'TRC20': 'TRX',
                    'BEP2': 'BNB',
                    'BEP20': 'BSC',
                    'OMNI': 'OMNI',
                    'EOS': 'EOS',
                    'SPL': 'SOL',
                },
kucoin:

                'networks': {
                    'ETH': 'eth',
                    'ERC20': 'eth',
                    'TRX': 'trx',
                    'TRC20': 'trx',
                    'KCC': 'kcc',
                    'TERRA': 'luna',
                },
```

There is also issue with default value in withdraw function, which allows invalid network ID to get into withdrawal requests:
```javascript
        network = this.safeString (networks, network, network); // handle ETH>ERC20 alias
```

EDIT: the options might just need to by extended with ERC20, TRC20, etc.

**Comment by kroitor** [comment]
That is actually a correct mapping:

```JavaScript
'networks': {
    'ETH': 'ERC20',
    'TRX': 'TRC20',
    'OMNI': 'Omni',
},
```

↑ That will work with all mappings ERC20, TRC20, OMNI, ETH, TRX, Omni due to how safeMethods are used with `networks`. That is done on purpose, so that all the following usages work:

```
fetchDepositAddress ('USDT', {'network':'ETH'})
fetchDepositAddress ('USDT', {'network':'ERC20'})
```


Hope that answers your question, let us know if not.

**Comment by krychla1** [comment]
FetchDepositAddress handles it completely differently, because the network isn't part of the request, it is just filtered from the response (from a quick look).

However check the withdrawal function:
```javascript
        const networks = this.safeValue (this.options, 'networks', {});
        let network = this.safeStringUpper (params, 'network'); // this line allows the user to specify either ERC20 or ETH
        network = this.safeString (networks, network, network); // handle ETH>ERC20 alias
        if (network !== undefined) {
            request['chain'] = currency['id'] + '-' + network;
            params = this.omit (params, 'network');
        }
        const query = this.omit (params, [ 'fee', 'password', 'pwd' ]);
        if (!('pwd' in request)) {
            throw new ExchangeError (this.id + ' withdraw() requires a password parameter or a pwd parameter, it must be the funding password, not the API passphrase');
        }
        const response = await this.privatePostAssetWithdrawal (this.extend (request, query));
```
This allows you to use ERC20 as a network only because it allows everything to be used as networks.

**Comment by kroitor** [comment]
> This allows you to use ERC20 as a network only because it allows everything to be used as networks.

Yes, that is correct. We will not reject params-overrides, if the user intentionally supplies an identifier for some new blockchain that is not listed out in `networks`. The user will get the exception from the exchange, if the supplied network is incorrect.

The unified identifier for ERC20 is `ERC20`, for TRC20 it is `TRC20`.
CCXT will allow the user to supply unified networks as well as exchange-specific networks by design.

**Comment by krychla1** [comment]
I thought you would want to sanitize the inputs. I've got your point, thanks for clarification.

**Comment by kroitor** [comment]
> I thought you would want to sanitize the inputs.

Yes, in general, we do sanitize it, but not in this specific case since the exchanges announce new listings every day, and if we hardcode that, it will be much harder to maintain. We do have some hardcode in the lib, but we would like to eventually get rid of it. Thanks for your understanding.
