### ISSUE TITLE
Options trading question

### ISSUE THREAD

**Issue by mariuszbyczek** [ccxt/ccxt#10759]
Does CCXT support option trading? Particularly on: Binance, FTX, Delta or Deribit?

**Comment by samgermain** [comment]
Currently no. It's a functionality we plan to add, but there's no expected date for when this will happen.

**Comment by kroitor** [comment]
@mariuszbyczek you can use that functionality from CCXT using the implicit API, but the options trading is not completely unified across the exchanges yet. It's a work in progress.
