### ISSUE TITLE
KuCoin Volume is in pair units, not base currency (USDT)

### ISSUE THREAD

**Issue by dnuno89** [ccxt/ccxt#10767]
- OS: Windows 10
- Programming Language version: Python
- CCXT version: 1.61.92

I am using the freqtrade project from github, which uses CCXT to connect to exchanges. I have noticed that the volume in the KuCoin exchange is given in units of coin, instead of base currency, at least for all USDT markets. I have opened an issue in the freqtrade github and think that this is a CCXT issue.

The freqtrade issue link: https://github.com/freqtrade/freqtrade/issues/6015

Captures of the OCHLV plots for ETH received with CCXT from gate.io and kucoin, both with 5 min candles, showing in the inset the volume at an specific moment. While it is expected to be different, the difference is very high.

Kucoin with volume in ETH:
![image](https://user-images.githubusercontent.com/11979371/144499288-bd26c086-c2c7-41f8-a03a-86ef2f9d7814.png)

Gate.io with volume in base currency (USDT):
![image](https://user-images.githubusercontent.com/11979371/144499390-13441bd6-f8eb-4cc9-baed-893df69c6053.png)

I have checked this with many more pairs, manually checking the volume shown in the web and the value received by CCXT is clearly not in base currency as it is in all other exchanges and the CCXT documentation states. I multiply the received volume with the pair price and obtain correct volume values.

I hope this helps to solve the issue, thanks for this awesome project.

**Comment by xmatthias** [comment]
And here comes the fun part:
if you look at the gate.io page for the same pair - it's showing a volume of 700(ish) for the candle in question, which is pretty clearly in ETH, and quite different than what the API returns (in gate.io's case - the [documentation](https://www.gate.io/docs/apiv4/en/#market-candlesticks) doesn't even state what currency the volume is in).

![Screenshot_20211203_062906](https://user-images.githubusercontent.com/5024695/144550505-ae3b0fac-0f30-4ad0-b772-8fff282d2c1d.png)


Kucoin is slightly different, as the ccxt documentation states that it should be in base currency (so USDT) - HOWEVER - changing this to USDT (basically using the "next" field in the [response](https://docs.kucoin.com/#get-trade-histories)).

[ccxt documentation reference](https://docs.ccxt.com/en/latest/manual.html#ohlcv-structure)

> // (V)olume (in terms of the base currency), float


Now i'm quite interested in the outcome of this issue - as a change to this will mean that all kucoin users will have to redownload their backtesting history, which is something we'll have to clearly communicate

**Comment by frosty00** [comment]
> Kucoin is slightly different, as the ccxt documentation states that it should be in base currency (so USDT) - HOWEVER - changing this to USDT (basically using the "next" field in the response).

The base currency of the market `BTC/USDT` is `BTC` not `USDT`. I've checked kucoin and the code is working as expected. Can you post the code that you are having trouble with?

**Comment by frosty00** [comment]
I can see that the volume for gateio is in the quote currency which is wrong...

**Comment by xmatthias** [comment]
You're right, my bad.

i've just found that on FTX, it's also in USD, not in BTC (on BTC/USD pair) (at least i doubt they traded over 100Million BTC within 1 hour, or 2M BTC in 1 minute).

It's obviously not CCXT's fault - ccxt can't / shouldn't invent data the exchange isn't providing.

Maybe it would be appropriate to update the ccxt documentation to state that it's in base currency _where possible_ - and in quote currency otherwise?

an alternative idea (would probably have to be checked on a wider range / for more exchanges) would be to try to have it aligned to how the exchange website displays it - so if the exchanges shows volume in USD - ccxt should as well (usually the API is aligned / used by the exchange's own webpage too, anyway).

**Comment by iiosenov** [comment]
I came across a similar issue with FTX. `fetch_ohlcv()` returns volume in quote units, while the `watch_trades()` + `build_ohlcvc()` combo returns volume in base units.

@kroitor @frosty00 Perhaps an idea would be to have a user-defined param as in `build_ohlcvc(volume_currency = base or quote)`? The build_ohlcvc() already takes `trades` as input, so should be a straightforward change to calculate volume in either currency.

**Comment by frosty00** [comment]
we'll look into emulating it!

**Comment by ttodua** [comment]
@kroitor @frosty00 I do see the point and agree, actually, when user gets 1min/1hr (or even, say, daily) bars from different exchanges using fetch_ohlvc, it might be more meaningful that user does expect to get somehow same structure of data (as well described in case of 3rd party programs, which rely on CCXT, and even small custom apps made by regular people) where they switch from one exchange to another, and seeing USDT volume for one Exch and Coin volume on another, doesn't follow the consistency routine. Even though exchanges provide them differently, CCXT might (as it's the vision of CCXT) make some unified (even a reasonably 'simulated') version of volume in both properties  : base & quote vol. :

I.E.  when using `fetch_ohlvc( "BTC/USDT", ...., volumeType: 'quote')` should always return the USDT volume nevertheless the used exchange. by inputing that `volumeType` parameter, users "agrees" to get simulated volume too, and I don't think it's a bad idea. When I get 1min/1hr bar and API says  i.e. 100BTC, it might not much matter a few % fluctuation of price within this bar, and say, just multiply `100` by the median of (High and Low) price:
`quote_volume = base_volume * (high+low)/2` 

So, the structure of OHLCV response might be of two kind

A) if user doesn't need the really exact exchange-returned value, but cares more of the general data, then  `fetch_ohlvc( ...., volumeType: 'quote')` will override `volume` property :
```
[
    {
        o: ...
        h: ...
        l: ...
        c: ...
        v: ...   //depending what user has chosen, it might remain same (if exchange response contains that type) or becomes simulated value by ccxt
    }
]
```
B) if user need the source (unchanged) volume very critically, but also would like to have consistent properties for B/Q volume, then call function with params  `fetch_ohlvc( ...., volumeType:"all" )` :
```
[
    {
        o: ...
        h: ...
        l: ...
        c: ...
        v: ...   //would be the left as is - response of exchange volume param.
        qv: ... //would be quote-volume : if exchange provided volume was already quote-volume, then will be same as 'v', otherwise simulated
        bv: ... //would be base-volume : if exchange provided volume was already base-volume, then will be same as 'v', otherwise simulated
    }
]
```
So, the consistency/accuracy will be retained and everyone will be happy. (yeah, the response data might be increased by 10-20% at max, but I don't see it as a problem, compared to the user-experience).

**Comment by ttodua** [comment]
@kroitor  let me know your thoughts later on this .

**Comment by ttodua** [comment]
late update, but closing this issue, as both kucoin and gate seem to return base-currency, which is expected.
