### ISSUE TITLE
getting error "TimeoutOverflowWarning"

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#10761]
I used Kucoin API to submit a few orders. I also had watchOrderbook WS enabled at that moment. 
Shortly after, I get:
```

 (node:13408) TimeoutOverflowWarning: 162206566290365 does not fit into a 32-bit signed integer.  
Timeout duration was set to 1.
(node:13408) TimeoutOverflowWarning: 162206566290363 does not fit into a 32-bit signed integer.  
Timeout duration was set to 1.
```

this happened before too, and now consistently happens. What could be an issue? it doesn't have any Exception/trace to find out from where it comes. Any thoughts?

**Comment by ttodua** [comment]
found [this](https://stackoverflow.com/questions/60474110/why-is-my-console-logging-timeoutoverflowwarning-4294967296000-does-not-fit-i), but dont know in which library that might be. I assume it might be in CCXT's 'sleep' function or somewhere, I cant say. but this spoilt our trading several times already.

**Comment by frosty00** [comment]
#19701
