### ISSUE TITLE
Exchange: Independent Reserve, Error: "AttributeError: 'independentreserve' object has no attribute 'PlaceLimitOrder'"

### ISSUE THREAD

**Issue by mpainenz** [ccxt/ccxt#1076]
Unfortunately, it appears that the Independent Reserver API is broken in some way. I cannot place a limit buy order.

- OS: Windows 10
- Programming Language: Python 3.6.4
- CCXT version: 1.10.566
- Exchange: Independent Reserve
- Method: create_limit_buy_order()

```
ireserve = ccxt.independentreserve()
ireserve.apiKey = KEY
ireserve.secret = SECRET
ireserve.load_markets()

ireserve.verbose = True
ireserve.create_limit_buy_order('BTC/NZD', 0.001, 21000)
```

The traceback is as follows:
```
Traceback (most recent call last):
  File "C:/Solus/Projects/CoinTrader/main.py", line 2, in <module>
    import tradebook
  File "C:\Solus\Projects\CoinTrader\tradebook.py", line 2, in <module>
    from misc import common, general
  File "C:\Solus\Projects\CoinTrader\misc\general.py", line 8, in <module>
    from api import api_bittrex, api_ireserve
  File "C:\Solus\Projects\CoinTrader\api\api_ireserve.py", line 43, in <module>
    ireserve.create_limit_buy_order('BTC/NZD', 0.001, 21000)
  File "C:\Python\Python364\lib\site-packages\ccxt\base\exchange.py", line 1009, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', *args)
  File "C:\Python\Python364\lib\site-packages\ccxt\independentreserve.py", line 192, in create_order
    response = getattr(self, method)(self.extend(order, params))
AttributeError: 'independentreserve' object has no attribute 'PlaceLimitOrder'
```

Thanks,
Mark

**Comment by kroitor** [comment]
This is fixed in version 1.10.567. Thanks for your feedback! We will be happy if you report back whether it works for you normally or not.

**Comment by mpainenz** [comment]
Hi there,

Thank you very much, especially for your prompt response, but also for this library in general. Are you the lead dev?

I have managed to get a successful limit buy order working. Once thing I notice is that the function call required my values as Strings, or it fails. For another exchange in CCXT (Bittrex), I can pass floating point values. What 'should' I be passing?

The code which excepts upon supplying a sfloating point value is as follows:

ccxt/python/ccxt/independentreserve.py

```
    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        url = self.urls['api'][api] + '/' + path
        if api == 'public':
            if params:
                url += '?' + self.urlencode(params)
        else:
            self.check_required_credentials()
            nonce = self.nonce()
            auth = [
                url,
                'apiKey=' + self.apiKey,
                'nonce=' + str(nonce),
            ]
            keysorted = self.keysort(params)
            keys = list(keysorted.keys())
            for i in range(0, len(keys)):
                key = keys[i]
                auth.append(key + '=' + params[key])
            message = ','.join(auth)
            signature = self.hmac(self.encode(message), self.encode(self.secret))
            query = self.keysort(self.extend({
                'apiKey': self.apiKey,
                'nonce': nonce,
                'signature': signature,
            }, params))
            body = self.json(query)
            headers = {'Content-Type': 'application/json'}
        return {'url': url, 'method': method, 'body': body, 'headers': headers}
```


The line `auth.append(key + '=' + params[key])` creates an exception if you were to call `ireserve.create_limit_buy_order('BTC/NZD', 0.001, 21000)`

The exception would be:

`  File "C:\Program Files (x86)\Python364\lib\site-packages\ccxt\independentreserve.py", line 219, in sign
    auth.append(key + '=' + params[key])
TypeError: must be str, not int`


Thanks again,
Mark

**Comment by kroitor** [comment]
@mpainenz hi!

> Are you the lead dev?

Yes, I am on of the developers of this library. I'm a member of a very small CCXT Dev Team. That counts 3 people, including myself. But we have not leads in the team. Moreover, a lot of the work on the library is done by the community of users like you.

> I have managed to get a successful limit buy order working. Once thing I notice is that the function call required my values as Strings, or it fails. For another exchange in CCXT (Bittrex), I can pass floating point values. 

This is a bug that needs a workaround in the Independent Reserve implementation. We are going to fix it soon as well. As you may know, we are still under active development, so there may be some issues here and there – not that easy to unify it all at once.

> What 'should' I be passing?

Until we fix the above quirk you should be passing strings. But in general, it should be made agnostic of the input type (should work with both floats and strings). In most cases floats will work normally.

Thanks for reporting!

**Comment by mpainenz** [comment]
Thanks @kroitor,

Well this library will save me a lot of time, I'm very thankful for you all to be making this public. I was half way through writing a few custom API clients before I came across it. I hope Markets will become more forthcoming linking to this Library in their Documentation pages. 

 The implementation is great, the unified API idea is solid.

Hopefully I get to spend a bit of time working with this API, in which case I'm more than happy to help where I can (modestly probably, my Python is still very much a learning experience)

Cheers,
Mark

**Comment by mpainenz** [comment]
While I'm here @kroitor, could I please ask, do any Cryptocurrencies use precision other than 8?

Thanks,
Mark

**Comment by kroitor** [comment]
@mpainenz yes, you should check for `.markets['BTC/USD'].precision` and `.currencies['BTC'].precision`, however, this aspect is also a work in progress, so those properties may be missing with some exchanges, but we are making progress unifying them all.
This is documented briefly, here: https://github.com/ccxt/ccxt/wiki/Manual#market-structure

**Comment by mpainenz** [comment]
Is the difference in precision per market, or per currency?

Also, do the developers have a chat channel or other place to communicate I might be able to participate in? I notice for example Independent reserve does not have fetch_order() implemented in the unified API yet, and I was looking to add it. A little guidance might be a time saver for me, as some of the Python syntax is unfamiliar to me.

Thanks,
Mark

**Comment by kroitor** [comment]
> Is the difference in precision per market, or per currency? 

Can be both in general.

> For example is it that each market might use different precision for a particular currency? IE using 6 decimal places for BTC which supports 8? 

Yes ([example](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#filters))

> Or is it that some currencies have a different precision than 8, or 2 for fiat.

Also possible.

> Also, do the developers have a chat channel or other place to communicate I might be able to participate in? 

Sure, here: 

[![Gitter](https://badges.gitter.im/ccxt-dev/ccxt.svg)](https://gitter.im/ccxt-dev/ccxt?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

I don't promise to answer right away, but I hope to respond asap. You can ask library-related questions in the main chatroom.

> I notice for example Independent reserve does not have fetch_order() implemented in the unified API yet, and I was looking to add it. 

That would be awesome!

> A little guidance might be a time saver for me, as some of the Python syntax is unfamiliar to me.

Just make sure to read this and follow the rules for derived classed literally, you won't need to know any python then: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

Thank you!

**Comment by mpainenz** [comment]
Thanks again @kroitor, that was really helpful.
