### ISSUE TITLE
[okex] ether network id different than erc20 network id

### ISSUE THREAD

**Issue by krychla1** [ccxt/ccxt#10766]
Dear fellows,
Why do you use different network id for ether ("ETH") and different for tokens("ERC20") on the ethereum network? I know that ether isn't erc20 token, however it is the same network.

By purpose in fetchCurrencies:
```javascript
if (mainNet && !(chainPart in layerTwo)) {
                        // BTC lighting and liquid are both mainnet but not the same as BTC-Bitcoin
                        network = code;
                    }
```
You and also your users have to take into consideration this "duplicity" in the implementation, causing errors. 
E.g. your fetchDepositAddress doesn't work for ether because it is not "ERC20" network.
```javascript
    async fetchDepositAddress (code, params = {}) {
        const rawNetwork = this.safeStringUpper (params, 'network');
        const networks = this.safeValue (this.options, 'networks', {});
        const network = this.safeString (networks, rawNetwork, rawNetwork);
        params = this.omit (params, 'network');
        const response = await this.fetchDepositAddressesByNetwork (code, params);
        let result = undefined;
        if (network === undefined) {
            result = this.safeValue (response, code);
            if (result === undefined) {
                const alias = this.safeString (networks, code, code);
                result = this.safeValue (response, alias);
                if (result === undefined) {
                    const defaultNetwork = this.safeString (this.options, 'defaultNetwork', 'ERC20');
                    result = this.safeValue (response, defaultNetwork);
                    if (result === undefined) {
                        const values = Object.values (response);
                        result = this.safeValue (values, 0);
                        if (result === undefined) {
                            throw new InvalidAddress (this.id + ' fetchDepositAddress() cannot find deposit address for ' + code);
                        }
                    }
                }
            }
            return result;
        }
        result = this.safeValue (response, network);
        if (result === undefined) {
            throw new InvalidAddress (this.id + ' fetchDepositAddress() cannot find ' + network + ' deposit address for ' + code);
        }
        return result;
    }
```
Please take a look, thanks.

**Comment by kroitor** [comment]
This works for me:

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.okex({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'password': 'YOUR_API_PASSWORD',
})
markets = exchange.load_markets()
exchange.verbose = True
response = exchange.fetch_deposit_address('ETH')
print(response)
```

Let us know if you have issues with that.

**Comment by frosty00** [comment]
ether isn't an erc20 token tho...

**Comment by krychla1** [comment]
The NETWORK attribute is not about whether it is or is not erc20 token. If you want to differentiate between mainnet currency, erc20, erc721, etc. please create another attribute, don't mess it with networks.

This network attribute should be consistent among all the exchanges for all tokens. 

I want to deposit eth to network1, I will use ```exchange.fetch_deposit_address('ETH', {network: network1})```
I want to deposit eth to network2, I will use ```exchange.fetch_deposit_address('ETH', {network: network2})```
I want to deposit avax to network1, I will use ```exchange.fetch_deposit_address('AVAX', {network: network1})```

Currently your users have to think whether it is mainnet currency, token, or whether they have to or cannot use the network parameter at all. 
```javascript
exchange.fetch_deposit_address('ETH', {network: 'ETH'})  //throws
exchange.fetch_deposit_address('ETH', {network: 'ERC20'})  //throws
exchange.fetch_deposit_address('ETH')  //passes
```
You are not going the right way, if you want to keep things simple & clear.

**Comment by kroitor** [comment]
@krychla1 the `network` option is not meant to be the final way of unifying this aspect, it is just a mapping of one network to another for currencies that require a network. There's no generally unified networks in the lib yet, this is still exchange-specific. We have just started working towards the unification.

**Comment by krychla1** [comment]
Sorry, didn't know the networks are just in their early stage, it is a good start. Please take my critics as inputs for your future design, it would be fine to have generic networks working the same across all exchanges.
