### ISSUE TITLE
fetchMyTrades is returning empty list on GateIO

### ISSUE THREAD

**Issue by kadiemq** [ccxt/ccxt#10765]
I'm using CCXT version 1.62.86 and when I call `fetchMyTrades` function on GateIO API I get an empty list no matter what the symbol is, I also tried binance API but it's working fine with no issues.

**Comment by kroitor** [comment]
@kadiemq please, paste your code and your verbose request+response (enable verbose mode before the failing call):

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by kadiemq** [comment]
Oh sorry forgot it here is the code and verbose:

`exchange.fetch_my_trades('BTM/USDT')`

`Request: GET https://api.gateio.ws/api/v4/spot/my_trades?currency_pair=BTM_USDT {'KEY': 'MY_PUBLIC_KEY', 'Timestamp': '1638468198', 'SIGN': '51f956ba626eee50cfbb5af6c23352300e8c11bd022089a67e08eaf6807f962656a4afcb18bb24f864dde9d06b4f0d88e22a964678618988e9c39ac4aa13ba24', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.26.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.gateio.ws/api/v4/spot/my_trades?currency_pair=BTM_USDT 200 {'Date': 'Thu, 02 Dec 2021 18:03:22 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'openresty', 'X-Request-Id': '[7704c014-8775789007]', 'Access-Control-Allow-Methods': 'GET,POST,OPTIONS,DELETE,PUT', 'Access-Control-Allow-Headers': 'DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type', 'Access-Control-Max-Age': '1728000', 'Vary': 'Origin', 'Content-Encoding': 'gzip'} []`

**Comment by kroitor** [comment]
@kadiemq thanks! Will investigate and will be back to you asap!

**Comment by samgermain** [comment]
@kadiemq 

Did you try using a new key pair? The only way I'm able to replicate your results (getting an empty array) is by using an api key and secret that I had deleted

You can also try doing this

- Python people can turn on DEBUG logging level with a standard pythonic logger, by adding these two lines to the beginning of their code: 
```
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by kadiemq** [comment]
> exchange.fetch_my_trades('BTM/USDT')

**Comment by kadiemq** [comment]
> @kadiemq
> 
> Did you try using a new key pair? The only way I'm able to replicate your results (getting an empty array) is by using an api key and secret that I had deleted. When I use a new api key pair, I get my trade history fine
> 
> You can also try doing this
> 
> * Python people can turn on DEBUG logging level with a standard pythonic logger, by adding these two lines to the beginning of their code:
> 
> ```
> import logging
> logging.basicConfig(level=logging.DEBUG)
> ```

I created a new API pair and that did not solve the issue the API is working because `exchange.fetchBalance()` is working

**Comment by samgermain** [comment]
> > @kadiemq
> > Did you try using a new key pair? The only way I'm able to replicate your results (getting an empty array) is by using an api key and secret that I had deleted. When I use a new api key pair, I get my trade history fine
> > You can also try doing this
> > 
> > * Python people can turn on DEBUG logging level with a standard pythonic logger, by adding these two lines to the beginning of their code:
> > 
> > ```
> > import logging
> > logging.basicConfig(level=logging.DEBUG)
> > ```
> 
> I created a new API pair and that did not solve the issue the API is working because `exchange.fetchBalance()` is working

Ok, could you paste a more complete version of your code in a comment?

```
import ccxt
from pprint import pprint
import logging
logging.basicConfig(level=logging.DEBUG)

gateio = ccxt.gateio({
    'enableRateLimit': True,
    "apiKey": ...,
    "secret": ...,
})
gateio.verbose = True
response = gateio.fetchMyTrades('BTC/USDT')
pprint(response)
```

I receive my trades from gateio, so It would be helpful to see more of your code

```
DEBUG:ccxt.base.exchange:GET https://api.gateio.ws/api/v4/spot/currencies, Request: {'User-Agent': 'python-requests/2.26.0', 'Accept-Encoding': 'gzip, deflate'} None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.gateio.ws:443
DEBUG:urllib3.connectionpool:https://api.gateio.ws:443 "GET /api/v4/spot/currencies HTTP/1.1" 200 None

python: 3.9.5 (default, Nov 10 2021, 22:49:50) 
[Clang 12.0.5 (clang-1205.0.22.9)]
CCXT Version: 1.62.38

...

DEBUG:ccxt.base.exchange:GET https://api.gateio.ws/api/v4/spot/my_trades?currency_pair=BTC_USDT, Request: {'KEY': '...', 'Timestamp': '1638507404', 'SIGN': '...', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.26.0', 'Accept-Encoding': 'gzip, deflate'} None
DEBUG:urllib3.connectionpool:https://api.gateio.ws:443 "GET /api/v4/spot/my_trades?currency_pair=BTC_USDT HTTP/1.1" 200 None
DEBUG:ccxt.base.exchange:GET https://api.gateio.ws/api/v4/spot/my_trades?currency_pair=BTC_USDT, Response: 200 {'Date': 'Fri, 03 Dec 2021 04:56:45 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'openresty', 'X-Request-Id': '[0085617e-9026516900]', 'Access-Control-Allow-Methods': 'GET,POST,OPTIONS,DELETE,PUT', 'Access-Control-Allow-Headers': 'DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type', 'Access-Control-Max-Age': '1728000', 'Vary': 'Origin', 'Content-Encoding': 'gzip'} [{"id":"2294824514","create_time":"1638399172","create_time_ms":"1638399172654.958000","currency_pair":"BTC_USDT","side":"sell","role":"taker","amount":"0.0001","price":"57084.89","order_id":"99396047994","fee":"0.01113155355","fee_currency":"USDT","point_fee":"0","gt_fee":"0"},{"id":"2294808945","create_time":"1638399011","create_time_ms":"1638399011673.907000","currency_pair":"BTC_USDT","side":"buy","role":"taker","amount":"0.0001","price":"56997.22","order_id":"99395456382","fee":"1.95e-07","fee_currency":"BTC","point_fee":"0","gt_fee":"0"},{"id":"2276908199","create_time":"1638244288","create_time_ms":"1638244288925.342000","currency_pair":"BTC_USDT","side":"sell","role":"taker","amount":"0.0004","price":"57051.28","order_id":"98763776657","fee":"0.045641024","fee_currency":"USDT","point_fee":"0","gt_fee":"0"},{"id":"2276878097","create_time":"1638244022","create_time_ms":"1638244022378.751000","currency_pair":"BTC_USDT","side":"sell","role":"taker","amount":"0.0001","price":"56892.19","order_id":"98762647471","fee":"0.011378438","fee_currency":"USDT","point_fee":"0","gt_fee":"0"},{"id":"2247535513","create_time":"1637974300","create_time_ms":"1637974300969.338900","currency_pair":"BTC_USDT","side":"sell","role":"taker","amount":"0.0002","price":"54143.29","order_id":"97698196162","fee":"0.021657316","fee_currency":"USDT","point_fee":"0","gt_fee":"0"}]


Request: GET https://api.gateio.ws/api/v4/spot/my_trades?currency_pair=BTC_USDT {'KEY': '...', 'Timestamp': '1638507404', 'SIGN': '0e0c4fa8d693103a9be1b167ddc6a051ac6702cf1484621e32099360bcd7cf9ff84727810a9a50557473541ee80e8fd1439b321df57f65899705e6e8bde0f9a5', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.26.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.gateio.ws/api/v4/spot/my_trades?currency_pair=BTC_USDT 200 {'Date': 'Fri, 03 Dec 2021 04:56:45 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'openresty', 'X-Request-Id': '[0085617e-9026516900]', 'Access-Control-Allow-Methods': 'GET,POST,OPTIONS,DELETE,PUT', 'Access-Control-Allow-Headers': 'DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type', 'Access-Control-Max-Age': '1728000', 'Vary': 'Origin', 'Content-Encoding': 'gzip'} [{"id":"2294824514","create_time":"1638399172","create_time_ms":"1638399172654.958000","currency_pair":"BTC_USDT","side":"sell","role":"taker","amount":"0.0001","price":"57084.89","order_id":"99396047994","fee":"0.01113155355","fee_currency":"USDT","point_fee":"0","gt_fee":"0"},{"id":"2294808945","create_time":"1638399011","create_time_ms":"1638399011673.907000","currency_pair":"BTC_USDT","side":"buy","role":"taker","amount":"0.0001","price":"56997.22","order_id":"99395456382","fee":"1.95e-07","fee_currency":"BTC","point_fee":"0","gt_fee":"0"},{"id":"2276908199","create_time":"1638244288","create_time_ms":"1638244288925.342000","currency_pair":"BTC_USDT","side":"sell","role":"taker","amount":"0.0004","price":"57051.28","order_id":"98763776657","fee":"0.045641024","fee_currency":"USDT","point_fee":"0","gt_fee":"0"},{"id":"2276878097","create_time":"1638244022","create_time_ms":"1638244022378.751000","currency_pair":"BTC_USDT","side":"sell","role":"taker","amount":"0.0001","price":"56892.19","order_id":"98762647471","fee":"0.011378438","fee_currency":"USDT","point_fee":"0","gt_fee":"0"},{"id":"2247535513","create_time":"1637974300","create_time_ms":"1637974300969.338900","currency_pair":"BTC_USDT","side":"sell","role":"taker","amount":"0.0002","price":"54143.29","order_id":"97698196162","fee":"0.021657316","fee_currency":"USDT","point_fee":"0","gt_fee":"0"}]
[{'amount': 0.0002,
  'cost': 10.828658,
  'datetime': '2021-11-27T00:51:40.969Z',
  'fee': {'cost': 0.021657316, 'currency': 'USDT'},
  'id': '2247535513',
  'info': {'amount': '0.0002',
           'create_time': '1637974300',
           'create_time_ms': '1637974300969.338900',
           'currency_pair': 'BTC_USDT',
           'fee': '0.021657316',
           'fee_currency': 'USDT',
           'gt_fee': '0',
           'id': '2247535513',
           'order_id': '97698196162',
           'point_fee': '0',
           'price': '54143.29',
           'role': 'taker',
           'side': 'sell'},
  'order': '97698196162',
  'price': 54143.29,
  'side': 'sell',
  'symbol': 'BTC/USDT',
  'takerOrMaker': 'taker',
  'timestamp': 1637974300969,
  'type': None},
  ...
  {'amount': 0.0001,
  'cost': 5.708489,
  'datetime': '2021-12-01T22:52:52.654Z',
  'fee': {'cost': 0.01113155355, 'currency': 'USDT'},
  'id': '2294824514',
  'info': {'amount': '0.0001',
           'create_time': '1638399172',
           'create_time_ms': '1638399172654.958000',
           'currency_pair': 'BTC_USDT',
           'fee': '0.01113155355',
           'fee_currency': 'USDT',
           'gt_fee': '0',
           'id': '2294824514',
           'order_id': '99396047994',
           'point_fee': '0',
           'price': '57084.89',
           'role': 'taker',
           'side': 'sell'},
  'order': '99396047994',
  'price': 57084.89,
  'side': 'sell',
  'symbol': 'BTC/USDT',
  'takerOrMaker': 'taker',
  'timestamp': 1638399172654,
  'type': None}]
```

**Comment by samgermain** [comment]
@kadiemq Does you apiKey have the [right permissions?](https://i.imgur.com/RxP2vis.png)

**Comment by ttodua** [comment]
Please consider doing the following:
1) Update ccxt to latest version
2) use new V4 api keys (which have correct permissions while generating it on Gateio website)
3) ensure, you are not confused with trades-history functionality: by default fetchMyTrades function returns last 7 days (as seen in gate's implementation code), so you should consider that.  If you want to change the default 7 day period, consider:

`fetchMyTrades (symbol,  since )`  where `since` parameter is epoch timestamp (milliseconds, i.e.  `16xxxxxxxxxxxx`, also take in to GATEIO docs not to put the timestamp which is not too long-ago compared to whatever does GATEIO api allows).

Feel free to reopen topic whenever you feel the issue is really coming from CCXT, along with your demonstrational code (omit the sensitive params).

**Comment by ttodua** [comment]
I've been checking this issue further (have met some discrepancy between GATE UI and API results) and finally found, the API seems not to return the items which didn't have an execution (even thought they seem to show up under "[My Trades](https://www.gate.io/myaccount/myorders/order_history)" in Gate UI.   As my test shows, the API only shows the [filled historical trades ](https://www.gate.io/myaccount/myorders/order_history).

Hope this clarifies the issue.
