### ISSUE TITLE
AttributeError: 'coinbasepro' object has no attribute 'createOrder'

### ISSUE THREAD

**Issue by JohnSmithyy** [ccxt/ccxt#10777]
I have this weird error where sometimes I get an attribute error when running this piece of code. 

Any ideas why this could be happening?

OS: Ubuntu WSL
Programming Language version: Python3.8
CCXT version: 1.62.38

```
import ccxt
exchange_id = "coinbasepro"
trading_pair = "BTC/USD
amount = 20
exchange_class = getattr(ccxt, exchange_id)
exchange_class_set = exchange_class(
            {'apiKey': api_key, 'secret': api_secret, 'password': api_pass ,
            'enableRateLimit': True,
             'options': {
                 'createMarketBuyOrderRequiresPrice': False,
            },
             })
exchange_class_set.set_sandbox_mode(True)
if exchange_class_set.has['createMarketOrder']:
            order = exchange_class_set.createOrder(trading_pair, 'market', 'buy', 1, amount)
            print("Made Market Order", order)
```

```
AttributeError: 'coinbasepro' object has no attribute 'createOrder'
```

**Comment by kroitor** [comment]
Hi! Try with lowercase syntax: `create_order` instead of `createOrder`. Let us know if that works for you. In the meantime, we will look into the cause of the issue.

**Comment by JohnSmithyy** [comment]
Tried that and had no luck. I do think it has to do with the fact I'm using celery and something is going wrong with the multiple workers not communicating the API details between each other. 

Thank you for the help regardless!
