### ISSUE TITLE
I could not pass the authorization form bybit apikey ,How could I pass the authorization?

### ISSUE THREAD

**Issue by shfe2004** [ccxt/ccxt#10779]
- OS: windows 10 
- Programming Language version: python 3.8
- CCXT version: 1.62.86

```
import ccxt
from pprint import pprint
exchange = ccxt.bybit({
    'apiKey': my_API_key,
    'secret': my_secret_key,
    'enableRateLimit': True,
})
balance = exchange.fetch_free_balance()
pprint(balance)
```

```
C:\ProgramData\Anaconda3\envs\pythonProject\python.exe C:\Users\Administrator\PycharmProjects\pythonProject\bybit_2_test.py
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\pythonProject\bybit_2_test.py", line 58, in <module>
    balance = exchange.fetch_free_balance()
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\ccxt\base\exchange.py", line 1650, in fetch_free_balance
    return self.fetch_partial_balance('free', params)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\ccxt\base\exchange.py", line 1646, in fetch_partial_balance
    balance = self.fetch_balance(params)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\ccxt\bybit.py", line 1114, in fetch_balance
    response = self.v2PrivateGetWalletBalance(self.extend(request, params))
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\ccxt\base\exchange.py", line 461, in inner
    return entry(_self, **inner_kwargs)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\ccxt\base\exchange.py", line 510, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\ccxt\base\exchange.py", line 506, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\ccxt\base\exchange.py", line 658, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\ccxt\bybit.py", line 2445, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\site-packages\ccxt\base\exchange.py", line 524, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.PermissionDenied: bybit {"ret_code":10005,"ret_msg":"Permission denied!","ext_code":"","ext_info":"","result":null,"time_now":"1638599168.525105"}

```

**Comment by kroitor** [comment]
@shfe2004 enable verbose mode and make sure that your keys are correct:

```Python
import ccxt
from pprint import pprint
exchange = ccxt.bybit({
    'apiKey': my_API_key,
    'secret': my_secret_key,
})
markets = exchange.load_markets()
exchange.verbose = True
balance = exchange.fetch_free_balance()
pprint(balance)
```

**Comment by ttodua** [comment]
I do confirm, there seems to be no issue. One possible user-side mistake might be happening, if you have restricted you bybit API to specific IP. Have you double checked it? maybe you try to re-generate api keys and try again, as in CCXT everything seems to be working well on my side too.

**Comment by aamustapha** [comment]
I'm also experiencing this same issue. I've regenerated the API keys

**Comment by DexSniping** [comment]
Same issue here (same error):

![image](https://user-images.githubusercontent.com/102369376/175792679-5b05e823-7cf3-4b8d-91e1-10eb57851034.png)

**Comment by kroitor** [comment]
@aamustapha @DexSniping try enabling all permissions and then disable them one by one to find which one is breaking it and hence is required.

**Comment by DexSniping** [comment]
> @aamustapha @DexSniping try enabling all permissions and then disable them one by one to find which one is breaking it and hence is required.

Found! For a trade spot, we also need "Contract permissions", I do not really understand why but it's working if I check Contract-Orders and Contract-Positions

**Comment by DexSniping** [comment]
> > @aamustapha @DexSniping try enabling all permissions and then disable them one by one to find which one is breaking it and hence is required.
> 
> Found! For a trade spot, we also need "Contract permissions", I do not really understand why but it's working if I check Contract-Orders and Contract-Positions
> 
> EDIT : Ok! By default, with CCXT, Bybit works in DERIVATIVES, not in the SPOT account, that's why

Like I said: Default team from ByBit exchange is Future (DERIVATIVES), so you can fix it by specifing DefaultType when you instantiate your exchange;

```
exchange = new ccxt.bybit({
    apiKey: dca.apiKey,
    secret: dca.secret,
    options: { "defaultType": "spot" }
});
```

Your permissions will works @aamustapha

**Comment by Paulito123** [comment]
I've got permission denied messages for quite a while in the beginning, even though all permission where open (except withdraw). I had no clue why, and I still don't, but I managed to work around it by generating a new API key-secret pair. Maybe Bybit doesn't manage updating permissions very well...

**Comment by kaveendhya** [comment]
I am getting permission errors from multiple Bybit P2P endpoints even with fresh API keys (P2P/Fiat enabled) and after trying multiple accounts/IP whitelist settings.

Repro (quick):

client.getP2POnlineAds({ tokenId:'USDT', currencyId:'LKR', side:'0', page:'1' })
→ { "ret_code": 912000014, "ret_msg":"permission denied", "result":{}, "time_now": "..." }
client.getP2PAccountCoinsBalance({ accountType:'UNIFIED', coin:'USDT' })
→ { "retCode": 10005, "retMsg":"Permission denied, please check your API key permissions.", "result":{}, "time": ... }
client.getP2PPersonalAds({ page:'1', size:'10', tokenId:'USDT', currencyId:'LKR', side:'0' })
→ { "ret_code": 912000014, "ret_msg":"permission denied", "result":{}, "time_now": "..." }

Please confirm what account/API-level permissions or flags are required to access these P2P endpoints (especially /v5/p2p/item/online and related P2P APIs).
