### ISSUE TITLE
New Exchange: Crypto.Com Derivatives

### ISSUE THREAD

**Issue by ChenLi0830** [ccxt/ccxt#10782]
There is [one MR](https://github.com/ccxt/ccxt/pull/9610) for Crypto.com. However, it seems to be SPOT only. 

It would be great if we could add support for the Crypto.com derivatives market. Please find the API doc here
https://exchange-docs.crypto.com/derivatives/index.html#change-logs

**Comment by kroitor** [comment]
The initial support for Crypto.com derivatives was added in CCXT 1.66.16+.
