### ISSUE TITLE
Fetch Balance at Point in Time / Performance

### ISSUE THREAD

**Issue by mnm7** [ccxt/ccxt#10788]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

Hi,

I am trying to analyse historical performance from my orders using CCXT on Binance. To do that, I wanted to fetch or obtain the account balance at certain points in time. I was trying to override the fetch_balance method with the params as such: `exchange.fetch_balance(params={'updateTime':'...'}) or exchange.fetch_balance(params={'timestamp':'...'})` however, the former returns the current balance, whilst the latter returns the following error:

`InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}`

Therefore, I assume there is no simple way to return the balance at a specific point on time. 

I have attempted to add all the commission fees and the realisedPnL from all the executed orders and almost reached my previous balance. All this was missing was the funding fees. 

**I now have two questions which I'd appreciate your assistance with @kroitor:**

1) Is there a way to find the total funding fees or the history of funding fees paid? (Seen in Transaction History on Binance Testnet)

For context, I have attempted the following:
`transactions = exchange.fetch_transactions() ` (The manual also mentions that this section of the unified CCXT api is under development)

but I got the below error:

`NotSupported: fetch_transactions() is not supported yet`

This code:
`transactions = exchange.fetchFundingFees()`

returns this error:
`NotSupported: binance does not have a testnet/sandbox URL for sapi endpoints`

2) Is there a simpler way of obtaining the account wallet balance at a specific point in time?
3) Is there a better way of obtaining performance or historical information for the account? 

Thank you very much in advance.

**Comment by ttodua** [comment]
Before @kroitor replies, I will kick in:
1) fetch_balance doesn't do that job. There is [ready-made endpoint](https://binance-docs.github.io/apidocs/spot/en/#daily-account-snapshot-user_data) for account snapshots, and try that:
```
let params = { ... };
await exchange.sapiGetAccountSnapshot (params);
```
in params, include the desired properties/values you read in API doc.
2) I think #1 answers your second question.
3) same.

If this doesn't help, feel free to re-open ticket and wait for @kroitor.

**Comment by mnm7** [comment]
Hi @kroitor @ttodua,

Thanks for the response. 

I tried the following code:
`exchange.sapiGetAccountSnapshot(params = {'type': 'margin',
                  'timestamp': 1634338800000})`
                  
But this is the error I obtain:
`NotSupported: binance does not have a testnet/sandbox URL for sapi endpoints`

Can you advise how I can fix this please? Thanks.
