### ISSUE TITLE
Fetching all users' private trades

### ISSUE THREAD

**Issue by znat** [ccxt/ccxt#10781]
- OS: MacOS
- Programming Language version: js
- CCXT version: 1.50

Hi team, I was wondering if there's a way to fetch a user's trades without specifying a symbol. IIUC, with `fetchMyTrades` I have to call it for every symbol which creates hundreds of useless API calls. Wondering if there's a way around it. Thanks a lot for all the great work

**Comment by kroitor** [comment]
@znat hi! In many cases a symbol is required by the exchanges' APIs, not by CCXT, therefore you have to loop over all symbols. If the exchange requires a symbol, then CCXT will let you know. And you have to specify the symbol then. Also, the exchanges will have a limit on how far back in time you can go. This is all covered here:

- https://github.com/ccxt/ccxt/wiki/Manual#personal-trades
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/

Also, see examples here:

- https://github.com/ccxt/ccxt/tree/master/examples
- https://github.com/ccxt/ccxt/tree/master/examples/js
- https://github.com/ccxt/ccxt/tree/master/examples#see-also

**Comment by kroitor** [comment]
P.S. One of the approaches is to filter the relevant symbols from the list of all symbols by looking at non-zero balances as well as transactions (withdrawals and deposits).

**Comment by znat** [comment]
Thanks @kroitor , that all makes sense.
