### ISSUE TITLE
Huobi fetch_balance is only looking on first account

### ISSUE THREAD

**Issue by andrelcgt** [ccxt/ccxt#10790]
Huobi fetch_balance is only looking on first account.
My first account is 'point', the second is 'spot'. With the code the way it is I never get the spot balance. There is no params to select the second account.

https://github.com/ccxt/ccxt/blob/5017e129a2426b1611dd39c75fef1ccf4a285d38/python/ccxt/huobi.py#L1827

**Comment by kroitor** [comment]
@andrelcgt will add an user-controlled option and a simple auto-detection feature there shortly, thx for reporting.

**Comment by andrelcgt** [comment]
Just for my planing when is it happening?

**Comment by kroitor** [comment]
@andrelcgt in less than 12h.

**Comment by andrelcgt** [comment]
Cool. Thanks.

**Comment by kroitor** [comment]
In the meantime, as a temporary workaround you can still override it like this:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

```Python
exchange.fetch_balance({'account-id': 'YOUR_ACCOUNT_ID_HERE'})
```
