### ISSUE TITLE
FTX Only have permissions for subaccount

### ISSUE THREAD

**Issue by serteikas** [ccxt/ccxt#10794]
Hi

1 Created sub account for FTX
2 Created API key for that subaccount with trading permissions
3 When calling `fetch_balance`, getting error:

`"Only have permissions for subaccount trading2"`

How is this possible? The API key and Secret are created for that specific account

ccxt = 1.63.10

**Comment by ttodua** [comment]
Can you mention the reason of closure? thanks.

**Comment by serteikas** [comment]
> Can you mention the reason of closure? I suppose you've sorted out (i.e. was something mechanical mistake on your end) right?

I contacted FTX directly and solved the issue.

Apparently, even if your API keys are created for specific sub account, you still need to explicitly define sub account name in headers. Which is redundant as sub account keys by default only have access to that specific sub account and nothing else.

**Comment by ttodua** [comment]
@serteikas thanks for input. Do you think it was something that CCXT should have amended in code (or make any functionality that could solve that problem for other users too)?

**Comment by kroitor** [comment]
CCXT already supports overriding the headers for FTX subaccounts as shown in these related duplicate issues:

- https://github.com/ccxt/ccxt/search?q=ftx+subaccount&type=issues
- https://github.com/ccxt/ccxt/issues/10794
- https://github.com/ccxt/ccxt/issues/9805

**Comment by kroitor** [comment]
P.S. There is no way to automatically determine if the api keypair is a subaccount api keypair or a master account keypair, so the user has to specify that.

**Comment by ttodua** [comment]
Update: from now, you can add the parameter in any method, like:

`createOrder/FerchBalance( ..., ...,  params:{ "FTXUS-SUBACCOUNT":"mySubAcc"} ) `
