### ISSUE TITLE
FTX: fetch_ticker error when using exchange.number = str

### ISSUE THREAD

**Issue by stalkr57** [ccxt/ccxt#10799]
- OS: Ubuntu 20.04
- Programming Language version: Python 3.8.10 
- CCXT version: 1.63.10 (latest)

I create exchange as:
        **exchange = getattr('ftx')({
            'apiKey': api_key,
            'secret': api_secret,
            'options': {'defaultType': 'future'}
        })**

Parse numbers as strings (as I use decimal.Decimal for prices):
        **exchange.number = str**

Calling:  **exchange.fetch_ticker('BTC-PERP')**

Gives an error 

_File "/python3.8_env/lib/python3.8/site-packages/ccxt/ftx.py", line 641, in fetch_ticker
    return self.parse_ticker(result, market)
  File "/python3.8_env/lib/python3.8/site-packages/ccxt/ftx.py", line 586, in parse_ticker
    return self.safe_ticker({
  File "/python3.8_env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1828, in safe_ticker
    change = percentage / 100 * last
TypeError: unsupported operand type(s) for /: 'str' and 'int'_

**Comment by ttodua** [comment]
If I am correct, you'd better to subscribe to this [issue](https://github.com/ccxt/ccxt/issues/522) to see the update whenever this problem will be fixed in ccxt. For now, I'd better to close this topic and suggest you subscribed the mentioned topic for major update about the problem.
