### ISSUE TITLE
Best practice to watch huge number of tickers

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#10814]
Is it good practice,  in Node.js case,  to create one infinite `while` cycle for each symbol like this:

```
// !!! Can contain 700+ symbols.
const symbols = [
    '1INCH-PERP',
    'ADA-PERP'
];
```

```
// Solution 1
const exchange = new ccxt.ftx();

function start() {
    for (let symbol of symbols) {
        watchTicker(symbol);
    }
}

// One infinite while for each symbol will be created, so 700+ 'while' cycles.
// All processed in async way.
async function watchTicker(symbol) {
    while (true) {
        try {
            let ticker = await exchange.watchTicker(symbol);

           // do magic with ticker ...
        }
        catch (e) {
            console.log(e);
        }
    }
}

start();
```
Currently, we process all tickets in one while cycle, but considering switching to above solution. Current solution:

```
// Solution 2
const exchange = new ccxt.ftx();

function subscribeAll() {
    for (let symbol of symbols) {
        subscribe(symbol);
    }
}

async function subscribe(symbol) {
    try {
        await exchange.watchTicker(symbol);
    }
    catch (e) {
        console.log(e);
    }
}

// Contains only one infinite while for all subscribed symbols,
// but each ticker is processed synchronously one by one.
async function process() {
    while(true) {
        for (let symbol in exchange.tickers) {
            let ticker = exchange.tickers[symbol];

            // do magic with ticker ...
        }

        await delay(1000);
    }
}

function delay(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

subscribeAll();
process();
```

- OS: Debian (Docker)
- Programming Language version: JavaScript (Node.js)
- CCXT version: pro 0.9.35

**Comment by ttodua** [comment]
I think this is absolute overkill if you just need bid/ask or such simple data, which is available in "all-tickers" endpoints. Most of exchanges support getting all tickers in one call.  In CCXT that is `fetchTickers()` which you can set on interval every 1000ms or alike. 
In CCXT PRO there  is `watchTickers` (note the last `s` for plural), but unfortunately not implemented for part of exchanges. So, depending on your needs, if you need specific exchange, you might have mentioned that exchange in your post, or you can yourself check CCXT PRO supported exchange's  `.js` file if it has `watchTickers: true`

**Comment by kroitor** [comment]
> In CCXT PRO there is `watchTickers` (note the last `s` for plural), but unfortunately not implemented for part of exchanges. So, depending on your needs, if you need specific exchange, you might have mentioned that exchange in your post, or you can yourself check CCXT PRO supported exchange's `.js` file if it has `watchTickers: true`

Unfortunately, the watchTickers functionality is not touched yet in CCXT Pro, it has been in plans for a long time, will hopefully get to it soon.

**Comment by wunderb1t** [comment]
So, currently, for watching of huge number of tickets the best solution will be use just REST API? Or 'Solution 2' from my example is also ok?

**Comment by kroitor** [comment]
The problem is that you're trying to watch 700+ symbols from a single machine. Very few exchanges will tolerate more than a few dozens of subscriptions simultaneously. When talking hundreds of subscriptions – you have to scale the application over a cloud of machines in order to properly balance the load on the exchange. Most of the exchanges will not work for 700+ symbols simultaneously in the same app on one single channel/machine.

**Comment by kroitor** [comment]
@wunderb1t it also depends on the purpose of your application. If you want to just store historical tickers – i would rather recommend switching to trades or orderbooks, cause tickers are secondary data derived from trades and orderbooks. There's very little use for WS-based tickers in the real-world trading apps. Most of them will not use OHLCV or ticker streams and subscriptions, but will use trades and orderbooks instead.

**Comment by wunderb1t** [comment]
> @wunderb1t both usages should work, actually. Usage 1 is slightly better imo.

You mean REST is better, yes?  

> it also depends on the purpose of your application

We need to watch  ticker prices to place enter/exit orders of our users, so speed of fresh prices receiving is important.

**Comment by ttodua** [comment]
@kroitor can you mention also 2 words, whether 'fetchTickers' is/isn't suitable in such cases? if ping is not high, in every 500ms they might be obtainable.

**Comment by kroitor** [comment]
> @kroitor can you mention also 2 words, whether 'fetchTickers' is/isn't suitable in such cases? if latency is not high, in every 500ms they might be obtainable, while seems to be quite enough for OP. (as he makes 'process' function to run after every 1000 ms delay, and I don't see the app is that much untold-critical dependant on 500ms diapason).

Some of the bots I've worked with were much closer to real-time, dealing with milliseconds and sub-ms time precision. However, if +/- 500ms is not critical for this specific use-case, then fetchTickers should be ok. Mind, however, that some exchanges (especially, Binance, the biggest one) will impose higher rate limits on fetchTickers, so you won't be able to call it with Binance once or twice a second – they will ban you temporarily to cool off.

**Comment by ttodua** [comment]
@kroitor About binance - maybe you mean 'ExchangeInfo' or 'tickers/24hr' endpoints - yes, they do have higher weights, and they will not allow much requests for those endpoints, but there is probably perfect use-case for binance 'all-tickers' :
https://binance-docs.github.io/apidocs/spot/en/#symbol-order-book-ticker  
which returns   bid&ask (with volumes)  for all tickers and weights just 2. 
So, user can be able to request that every 500 ms, and probably all other exchange's "all-tickers" endpoints too , which might be the  best solution in such cases (compared to subscribing more than 100+WS connections, not to mention 1000+WS connections), unless the entity is not a multi-millionaire market-maker or such and cant tolerate the few MS delay.

**Comment by kroitor** [comment]
> @kroitor About binance - maybe you mean 'ExchangeInfo' or 'tickers/24hr' endpoints - yes, they do have higher weights, and they will not allow much requests for those endpoints, but there is probably perfect use-case for binance 'all-tickers' : https://binance-docs.github.io/apidocs/spot/en/#symbol-order-book-ticker which returns bid&ask (with volumes) for all tickers and weights just 2.

We have it as `fetchBidsAsks` here: https://github.com/ccxt/ccxt/blob/master/js/binance.js#L1822

**Comment by ttodua** [comment]
btw, maybe we can even add that as another 'method' for fetchticker/s ? ([here ](https://github.com/ccxt/ccxt/blob/master/js/binance.js#L1808) and [here](https://github.com/ccxt/ccxt/blob/master/js/binance.js#L1850))  [Not sure atm, how the parameter should be set, but actually, may apps/use-cases might just want bid/ask data for 'all-tickers' and this method will be useful for many users ?

**Comment by kroitor** [comment]
> btw, maybe we can even add that as another 'method' type variable in fetchticker/s ? ([here ](https://github.com/ccxt/ccxt/blob/master/js/binance.js#L1808) and [here](https://github.com/ccxt/ccxt/blob/master/js/binance.js#L1850)) [Not sure atm, how the parameter should be set, but actually, may apps/use-cases might just want bid/ask data for 'all-tickers' and this method will be useful for many users ?

Yeah, we can think of how to better merge the two methods.

**Comment by wunderb1t** [comment]
@kroitor Do I correctly understand that multiple  calling  of `watchTicker(symbol) ` method for different symbols and the same exchange instance will use single socket connection for symbol subscription? And if socket  connection is interrupted, all subscriptions will be lost?

**Comment by wunderb1t** [comment]
I need a little more info to close the issue. 

1. Is there necessity of limit controlling during  subscription on symbols via `watchTicker(symbol)`?

```
const exchange = new ccxt.ftx();

// symbols - can contain many symbols.
async function subscribe() {
    for (let symbol of symbols) {
        // Should await be used here to control limits? 
        exchange.watchTicker(symbol);
    }
}
```

2. When `watchTicker` is called with the same symbol repeatedly, there is no repeated subscription request if symbol is already subscribed, right?

```
async function watchTicker() {
    while (true) {
        try {
            // Only single subscription request?
            let ticker = await exchange.watchTicker('ADA-PERP');
        }
        catch (e) {
            console.log(e);
            break;
        }
    }
}
```

**Comment by kroitor** [comment]
@wunderb1t 

1. It should be handled for you, but this aspect is not entirely unified yet, you might run into some limitations on the exchange side, namely, the number of subscriptions per hour/24h, the number of connections, the frequency of subscriptions. Let us know if you run into issues with that, we will address them asap.

2. Yes, that is correct, the same connection will be reused, and also the same subscription will be reused if you reference an already-subscribed symbol.

**Comment by ttodua** [comment]
@wunderb1t Just as a comment, I might advise, that  when you do without `await` in your 1st example (i.e. `ex.watchTicker(symbol);` and then you quickly start another loop where you use `await ex.watchTicker(symbol)` then theoretically you might get collision of same subscirptions, because while you had fired without await a second ago (lets say symbol 'BTC/USDT') and as it was not awaited, the subscription command is in the transmit yet, and then you again do that with `await` now (`await ex.watchTicker('BTC/USDT')) so you might end up doing 2 subscriptions for same symbol/s.  

To avoid them, then you might do 'await' from the first 'watchTicker' function too, or for your first cycle do the following:
```
async function subscribe() {
    let allPromises = [];
    for (let symbol of symbols) {
        // Should await be used here to control limits? 
        allPromises.push( exchange.watchTicker(symbol) );
    }
   await allPromises;
}
```

and then you are ready to go with your 2nd example.
