### ISSUE TITLE
Fetch Balance at Point in Time / Performance

### ISSUE THREAD

**Issue by mnm7** [ccxt/ccxt#10820]
Hi @kroitor @ttodua,

I am referencing the previous issue before and opening a new ticket as I still have issues: 
Link to previous issue and comments (https://github.com/ccxt/ccxt/issues/10788#issuecomment-987796748)

Thanks for the response. 

I tried the following code:
`exchange.sapiGetAccountSnapshot(params = {'type': 'margin',
                  'timestamp': 1634338800000})`
                  
But this is the error I obtain:
`NotSupported: binance does not have a testnet/sandbox URL for sapi endpoints`

Can you advise how I can fix this please? Thanks.

_Originally posted by @mnm7 in https://github.com/ccxt/ccxt/issues/10788#issuecomment-988080303_

**Comment by kroitor** [comment]
> NotSupported: binance does not have a testnet/sandbox URL for sapi endpoints

That call will work for the production environment, but will not work if you're using the sandbox mode (binance testnet does not have it). The only workaround at this time is to use their productions servers instead of using the sandbox. Hope that answers your question, let us know if not.

**Comment by kroitor** [comment]
P.S. Feel free to reopen this issue or just ask further questions if any.
