### ISSUE TITLE
hitbtc incorrectly identifies quote symbol as USD

### ISSUE THREAD

**Issue by kaysond** [ccxt/ccxt#1083]
It looks like hitbtc trades in USDT: https://hitbtc.com/BTC-to-USD

However, the API symbol comes back as "XXX/USD". This is probably because their API returns the quote currency as USD: https://api.hitbtc.com/api/2/public/symbol

In the interested of having a "unified" API, I think ccxt should convert it to the proper "USDT".

That way something like this can work on multiple exchanges that use USDT:
```
for (exchange of exchanges) {
exchange.fetchTicker("ETH/USDT")
}
```
Right now this breaks on hitbtc

**Comment by kroitor** [comment]
Fixed in 1.10.573. Thanks for reporting!
