### ISSUE TITLE
bithumb coin matching error

### ISSUE THREAD

**Issue by jskorlol** [ccxt/ccxt#10836]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version: 1.62.93

```
            'commonCurrencies' => array(
                'FTC' => 'FTC2',
                'MIR' => 'MIR',
                'SOC' => 'SOC',
            ),
```

The API names of MIR and SOC have been changed.

**Comment by kroitor** [comment]
> The API names of MIR and SOC have been changed.

@jskorlol please, elaborate a bit, what exactly is wrong, how do you reproduce the issue?

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by jskorlol** [comment]
![image](https://user-images.githubusercontent.com/12728472/145671630-5c6b0dc6-237e-4cf7-9f7c-646330ef074f.png)

![image](https://user-images.githubusercontent.com/12728472/145671641-a19871fc-7b11-4d9e-b309-ce9d98f9cfc4.png)

Sorry for the late reply.
The coin's name does not match the corresponding exchange coin.
marked as null.
All three should change like this:
I checked all three yesterday.

It comes out when you balance it out.

```php
$client->fetchBalance()
```;

**Comment by criadoperez** [comment]
@jskorlol , the code in bithumb.php you state as:

            'commonCurrencies' => array(
                'FTC' => 'FTC2',
                'MIR' => 'MIR',
                'SOC' => 'SOC',
            ),

Is no longer this way. It is now:

            'commonCurrencies' => array(
                'FTC' => 'FTC2',
                'MIR' => 'MIR COIN',
                'SOC' => 'Soda Coin',
            ),

Could you please update to the latest version and confirm if the problem has been solved or not?

**Comment by kroitor** [comment]
@jskorlol let us know if upgrading your version of CCXT does not help.

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Feel free to reopen this issue or just ask further questions if any.
