### ISSUE TITLE
How to know the real amount bought in OKEX?

### ISSUE THREAD

**Issue by gerardo15** [ccxt/ccxt#1084]
Hello, i know this is not related to a bug or anything in ccxt, but was wondering if you have a solution for this.

when i buy an order and then fetch it i get the following

```
{ info:
   { amount: 379.36267071,
     avg_price: 0.00001318,
     create_date: 1515189823000,
     deal_amount: 379.36267071,
     order_id: 15348,
     orders_id: 15348,
     price: 0.00001318,
     status: 2,
     symbol: 'read_btc',
     type: 'buy' },
  id: 15348,
  timestamp: 1515189823000,
  datetime: '2018-01-05T22:03:43.000Z',
  symbol: 'READ/BTC',
  type: 'limit',
  side: 'buy',
  price: 0.00001318,
  average: 0.00001318,
  cost: 0.0049999999999577995,
  amount: 379.36267071,
  filled: 379.36267071,
  remaining: 0,
  status: 'closed',
  fee: undefined }
```

But in OKEX the balance is -> READ balance : 379.34768099

Even if the fee is 0.1% as a taker.. i have no way to find out the real balance... how did 0.004% comission came in place?

**Comment by kroitor** [comment]
It's hard to tell without seeing your READ/BTC balance before and READ/BTC balance after. Can you show those values in verbose mode? This seems like rounding effects coming from the OKEX themselves...

**Comment by kroitor** [comment]
Also, what does their website history say?

**Comment by gerardo15** [comment]
Hello.

In verbose it returns the same amount, and also in the website shows the same as the api, but it does not match the balance. keep in mind that is just a fresh opened acount with only 1 trade

https://imgur.com/lTc0G33

**Comment by kroitor** [comment]
@gerardo15 yeah, but if you look at average price, on their website it somehow differs from the value reported by their API...

![screen-shot-2018-01-06-at-13 37 22](https://user-images.githubusercontent.com/1294454/34638948-559eb8d0-f2e7-11e7-8686-7c2bd6c51b2b.jpg)

↑ This might be worth submitting in a ticket to their support.

**Comment by rannirabadi** [comment]
Hi, 

Did you work this out? I was about to start trading with okex.
