### ISSUE TITLE
bitMEX error: This request has expired

### ISSUE THREAD

**Issue by ShieldTrade** [ccxt/ccxt#10859]
OS:Windows 10
Programming Language version: Python 3.7
CCXT version: CCXT version: CCXT Pro Version: 0.8.13
Exchange bitmex

I am having a lot of  problem with this error I get from bitmex when trying to post an order ( cancel/amendprice/create_order)
`message":"This request has expired - `expires` is in the past. Current time: 1639253060","name":"HTTPError"`

bitMEX support suggested
`the error relates to a time sync issue. How are you setting your api-expires?`

is this a market property I have to set when I instantiate the exchange?
do you have a suggestion for me?

Thankyou

**Comment by ShieldTrade** [comment]
I am sorry I did not look with the due attention to your documents

`timeout: A timeout in milliseconds for a request-response roundtrip (default timeout is 10000 ms = 10 seconds). You should always set it to a reasonable value, hanging forever with no timeout is not your option, for sure`

```
bitmex_test = ccxtpro.bitmex({'verbose': False,
                                      'enableRateLimit': False,
                                      'apiKey': '5TsTyxxxxxxxxAMo79jwTiw',
                                      # always write your credentials in single quotes, not double quotes
                                      'secret': 'o-Q2LEHJgTxxxxxxwST82GJyKROc7yMKvVZnv10Gj6',
                                      'newUpdates': True,
                                      'timeout': 20000,       # 20 sec
                                      'options': {
                                          'tradesLimit': 1000,
                                          'OHLCVLimit': 1000,
                                          'ordersLimit': 1000,
                                      },
                                      })
```
is this the correct way to change the default 10 sec?

**Comment by kroitor** [comment]
> is this a market property I have to set when I instantiate the exchange?

You can override the default expiry time. That is done by overriding the `exchange.options['expires']` exchange-specific option here: https://github.com/ccxt/ccxt/blob/master/python/ccxt/bitmex.py#L191 like described in the manual here: https://docs.ccxt.com/en/latest/manual.html#instantiation

```Python
exchange = ccxtpro.bitmex({
    'apiKey': '...',
    'secret': '...',
    'options': {
        'api-expires': 10, # in seconds
    }
})
```

However, that in itself would be hiding the real issue which is your system clock. Make sure it is aligned with the UTC against the time server, cause it can fluctuate a lot. Most of the configuring a system-wide timesync every 10 seconds would be enough to mitigate this issue.

Hope that answers your questions, let us know if not.

**Comment by ShieldTrade** [comment]
Very good and fast answer as usual. Thankyou

How does this expiry time  works? I guess my system time is written on the request to the market and if they are not able to respond within  `'api-expires': 10, # in seconds` they send me the error message.  

I will follow your advice thankyou again
