### ISSUE TITLE
Install ccxt pro second time not work, says repo not found

### ISSUE THREAD

**Issue by beersoup** [ccxt/ccxt#10865]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```
Hi, I've been using ccxt pro for a few day with my Nodejs project, and I had to delete node_modules for some reason. After I delete it and I couldn't install ccxt pro again, I don't know why I have everything correct SSR in Github is connected well. Please help.

**Comment by kroitor** [comment]
Hello!

- Please check your GitHub credentials when installing it.
- Check if you can access this link: https://github.com/kroitor/ccxt.pro
- Also, check if you can git-clone it using your GitHub account.
- Check if your account still has access here: 
  - https://ccxt.pro/account
  - https://ccxt.pro/orders
- If the above things work, that means something is wrong with your GitHub authentication config on your local machine.
Make sure you use the correct account for it, and your subscription has not expired (you should receive emails to your primary GitHub email if it does).

Let us know if the above does not help.

**Comment by beersoup** [comment]
I check everything again and it fine, but still getting the same return that repo is not found.

**Comment by kroitor** [comment]
@beersoup please, paste your full install log, including the commands you've tried, here. If `git-clone` works for you and you have the access to the repository, then it means something wrong with your credentials config.

**Comment by beersoup** [comment]
No, git-clone didn't work but I can assess to all links and successfully connected SSH. Here the install log :

npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/kroitor/ccxt.pro.git
npm ERR!
npm ERR! remote: Repository not found.
npm ERR! fatal: repository 'https://github.com/kroitor/ccxt.pro.git/' not found
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\beers\AppData\Roaming\npm-cache\_logs\2021-12-13T15_43_12_706Z-debug.log

**Comment by kroitor** [comment]
@beersoup try specifying your personal access key as your username and password with a colon, using this command:

```
git clone https://USERNAME:PASSWORD@github.com/kroitor/ccxt.pro.git
```

You can generate the access token here: https://github.com/settings/tokens

Let us know if that does not help.

**Comment by beersoup** [comment]
It seems work now, I use npm install https://USERNAME:PASSWORD@github.com/kroitor/ccxt.pro.git with token as the PASSWORD, now I'm happy thanks for helping :)
