### ISSUE TITLE
New Exchange: Coinbase

### ISSUE THREAD

**Issue by ydkishore30** [ccxt/ccxt#1086]

**Comment by kroitor** [comment]
Related to:
https://github.com/ccxt/ccxt/issues/466

**Comment by danricho** [comment]
+1

**Comment by thiagodl** [comment]
Thanks a lot.

**Comment by Bomper** [comment]
This issue should be closed as a dupe of #466, which has [better information](https://github.com/ccxt/ccxt/issues/466#issuecomment-353149953) and should be reopened. I'm interested in implementing `fetchBalance()` on Coinbase.
