### ISSUE TITLE
Is there a master page of all the links to get APIs for each exchange?

### ISSUE THREAD

**Issue by JohnSmithyy** [ccxt/ccxt#10870]
As the title states, just wondering if there is some master page where I can find how to get the API information for each exchange.

**Comment by kroitor** [comment]
You can find links to all exchanges here: https://github.com/ccxt/ccxt/#supported-cryptocurrency-exchange-markets
We don't recommend hardcoding the signup links, cause the exchanges can redesign their websites from time to time. Hope that answers your question.
