### ISSUE TITLE
A way to check if you can withdraw a coin from an exchange

### ISSUE THREAD

**Issue by kingofclubstroy** [ccxt/ccxt#1087]
I was wondering if there is anyway to check to see if a coin is able to be withdrawn from an exchange. 
There has been quite a few instances where a coin is bought but is prevented from transferring exchanges for whatever reason, and so is left waiting till the issue is resolved, so it would be helpful to know this before a coin is bought 

- Programming Language: Python

**Comment by kroitor** [comment]
You should check the `.currencies` property of the exchange in question. If a currency has `['active'] = False`, it means it is not withdrawable. You should check for that like shown below:

```Python
import ccxt
kraken = ccxt.kraken()
exchange.load_markets()
# after loading the markets (!)
code = 'BTC'
active = 'active' in exchange.currencies[code] and exchange.currencies[code]['active']
print(code + ' is ' + 'active' if active else 'inactive')
```

 However, be aware, that this library is still a work in progress and not everything has been unified yet, therefore those flags may be missing on some exchanges. We will be happy if you contribute to those. 

Let us know if it answers your question or not.

**Comment by kingofclubstroy** [comment]
Thank you for answering, I believe you are answering my question correctly but what gets returned when i call .currencies doesn't have a active key for any of the currencies. I have tried with binance, bittrex and hitbtc and they all return something like this:
{u'SKIN': {'code': u'SKIN', 'id': u'SKIN'}, u'GNO': {'code': u'GNO', 'id': u'GNO'}
, u'STX': {'code': u'STX', 'id': u'STX'}, u'SMART': {'code': u'SMART', 'id': u'SMART'}, u'BTC':{'code':u'BTC', 'id':u'BTC}}
I don't know if there is an "active" key for other exchanges, but doesn't seem to work for the ones im currently running, would there be any correlation with a coin not showing up on that list as being unable to be withdrawn?

**Comment by kingofclubstroy** [comment]
I have noticed when calling .fetch_markets() there is a "active" key and i had assumed that was what I wanted, but I wasn't sure as it was referring to a market so i think that just refers to whether that market is trading right?

**Comment by kroitor** [comment]
@kingofclubstroy 

> that just refers to whether that market is trading right?

Right.

For the exchanges from your list we don't have the `fetchCurrencies()` method unified yet (more about it here: https://github.com/ccxt/ccxt/search?q=fetchCurrencies&type=Issues), but we are working on it, and, btw, you can help us by submitting a pull-request ;) More on how to contribute: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md. We hope to add it asap.

Until we unify that aspect, you can still use the custom APIs for all of those exchanges that offer methods to check for currency/asset statuses with their API. CCXT supports all their endpoints, literally, but we don't have all of them unified yet. For HitBTC you can use the custom API from CCXT like so:

```Python
import ccxt
from pprint import pprint
exchange = ccxt.hitbtc2()
pprint(exchange.public_get_currency()) # custom non-unified API returns exchange-specific format
```
↑ This way you can check for that info yourself. All of that is documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual. To get a list of all supported methods with `print(dir(exchange))`. 

Does this help?

**Comment by kingofclubstroy** [comment]
It helps tremendously, have managed to find the info I need for all but binance so far, it would be appreciated if you could point me in the right direction there, but as always you gone above and beyond to help and is very appreciated!

**Comment by kroitor** [comment]
@kingofclubstroy unfortunately they don't serve that info from their [REST](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md) API nor from their Withdraw [WAPI](https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md). The only thing they serve is the [status of a trading pair](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#enum-definitions):
> Symbol status:
> - PRE_TRADING
> - TRADING
> - POST_TRADING
> - END_OF_DAY
> - HALT
> - AUCTION_MATCH
> - BREAK

You can get that status from `.markets` after loading them:

```Python
import ccxt
exchange = ccxt.binance()
exchange.load_markets()
exchange.markets['ETH/BTC']['info']['status']
```

Let me know if this answers your question.

**Comment by jamallucas** [comment]
Hi @kingofclubstroy, I'm also trying to find a solution for the same problem. I was wondering which approach you took for those exchanges

**Comment by bruceharrod** [comment]
Are you able to check if you can withdraw from huobi? I've looked through their docs but can't seem to find anything relating to this.

**Comment by kroitor** [comment]
@bruceharrod this is so common among exchanges, even the major ones...

**Comment by kroitor** [comment]
@JamieDimonCrypto that's a possible way of testing it, however, the exchanges themselves aren't consistent with their returned values and thrown exceptions, so the actual error may be exchange-specific.

**Comment by corbinchase** [comment]
@kroitor @kingofclubstroy  not sure if this is helpful, but here is a URL for Binance that lists all assets and has a variable for "enableWithdraw", by each coin. At this time I don't have the availability to make a pull request integrating this URL but figure I would pass it along and hope to see it in the next update: https://www.binance.com/assetWithdraw/getAllAsset.html

**Comment by kroitor** [comment]
@corbinchase thanks so much! We will try to use it in the lib as well, Unfortunately, this is not a part of their API, as they don't give any guarantees on the future work of that web url (can change it anytime). But, not having any other options, we will use what's available.

**Comment by phuaky** [comment]
im trying 
`(async () => {
  let exchange = new ccxt.bithumb()

  await exchange.loadMarkets()

  Object.keys(exchange.markets).map((key, value) => {
    console.log(key, exchange.markets[key]['active']);
  })

})()`

it is returning me 'true' for STEEM/KRW, but when i log in to the online portal and check, i am not able to deposit or withdraw. 

any other ways i can do this?

**Comment by kroitor** [comment]
@phuaky unfortunately, Bithumb API does not provide that info from any of their endpoints, so, it's true by default, but it may actually be false, like in your case. In other words that is due to limitations of the underlying API, but we'll see if we can add any workarounds with web scraping or something like that...

**Comment by kivo360** [comment]
Does this work with checking if the account has withdrawal access? I want to make sure the account doesnt.

**Comment by gloomydumber** [comment]
@kroitor 
sry for questioning closed issue.
still doesn't support withdrawable / deposable status by exchanges like binance, bithumbs ?
thx for your api, sir

**Comment by kroitor** [comment]
@gloomydumber you can do that by using private implicit endpoints, neither Binance nor Bithumb have a public endpoint for that.

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

**Comment by gloomydumber** [comment]
@kroitor 
thx sir,
i used web_get_assetwithdraw_getallasset_html()
but i have error like this

AttributeError: 'binance' object has no attribute 'web_get_assetwithdraw_getallasset_html'

it worked well before but error for now..

**Comment by kroitor** [comment]
@gensixdigital Hi!

It was a part of the webapi, that has been removed since then and replaced with a proper api endpoint.

You can see the list of all available endpoints as described in the Manual here:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
