### ISSUE TITLE
[hitbtc] - Insufficient funds

### ISSUE THREAD

**Issue by foozzi** [ccxt/ccxt#10894]
- OS: Arch linux
- Programming Language version: Python 3.9
- CCXT version: ccxt 1.63.80 

balance in my wallet is 0.4 ETH

```python
hitbtc = ccxt.hitbtc({
    'apiKey': '***',
    'secret': '***'
})
hitbtc.withdraw("ETH", '0.1', "***")
```

i'm getting error:

`{"error":{"code":20001,"message":"Insufficient funds","description":"Check that the funds are sufficient, given commissions"}}`

tell me pls why and how to fix this?

**Comment by carlosmiei** [comment]
Hello @foozzi , I've checked and the amount and address fields are correctly being sent to Hitbtc. Are you sure you have that balance available to be withdrawn?

**Comment by kroitor** [comment]
@foozzi hitbtc has "trading" balance and "main" balance, you must have the funds on your "main" balance to withdraw. Users can sometimes confuse the two balances. Let us know if that does not answer your question. Feel free to reopen this issue or just ask further questions if any.
