### ISSUE TITLE
watchOrders No Updates on Partial Fills 

### ISSUE THREAD

**Issue by mkapuza** [ccxt/ccxt#10915]
- OS: macOS 11.6
- Programming Language version: Python 3.7.4
- CCXT version: 1.57.28

Using the `ccxtpro` method `watchOrders` with `"newUpdates": True` we get updates when the order status changes, e.g. when it opens, is canceled or is closed, but we don't get updates when the order is partially filled... Not sure if this is the intended functionality. In the meantime we plan on using `watchMyTrades` as a workaround

**Comment by kroitor** [comment]
@mkapuza do you see the partial fill updates with verbose mode on? Which exchange is it? Do you have this version with the most recent versions of CCXT and CCXT Pro? Can you please paste the code you use to reproduce it?

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by ttodua** [comment]
@mkapuza for the sake of the completeness, if you can please reply to this issue, so we have more clues about the issue. thanks
