### ISSUE TITLE
ftx.fetch_my_trades only returning last 5000 trades

### ISSUE THREAD

**Issue by adamxyzxyz** [ccxt/ccxt#10923]
Hi everyone, I am attempting to fetch historical trades on FTX via the fetch_my_trades endpoint, but I am only able to fetch the last 5000 trades. I have pasted my code below:

```
async def get_fills():
    ftx_data = pd.DataFrame([])
    start_time=1637103919000
    while True:
        if start_time < ftx.milliseconds():
            fill_data = pd.DataFrame(ftx.fetchMyTrades(symbol='SOL-PERP', limit=1000, since=start_time),
                    columns=['datetime','symbol','side','price','amount','cost'])
            print(fill_data)
            ftx_data = ftx_data.append(fill_data, ignore_index=True, sort=False)
            start_time += 86400000
            ftx_data.to_csv('sol_perp_fills.csv')
            time.sleep(5)
        else:   
            break
```

**Comment by nhymxu** [comment]
Hmm, I think problem is `start_time += 86400000` and `limit=1000`

Eg: this timeframe have **3000** trades. But you can get only `limit=1000` and jump to next timeframe.
So you skip **4000** trades

I think you can replace `start_time += 86400000` with `start_time` = **last timestamp** in your `fill_data`

**Comment by adamxyzxyz** [comment]
hey guys I was able to resolve this, so going to close it!
