### ISSUE TITLE
Can we make orders for multiple accounts from single IP for same exchange without throttling?

### ISSUE THREAD

**Issue by AlphaNumeric99** [ccxt/ccxt#10928]
- OS: Ubuntu 20.04
- Programming Language version: Python 3.8
- CCXT version: 1.64.13

I am trying to make a for loop asynchronous using the given [example](https://github.com/ccxt/ccxt/blob/master/examples/py/async-multiple-parallel-calls.py) but I read that too many calls from one IP address might get it throttled due to [rate limits](https://github.com/ccxt/ccxt/wiki/Manual#rate-limit) 

I am using Coinbase Pro for this and only using create_market_order or create_limit_order functionality.

My question is will I be throttled if I am replicating orders asynchronously in multiple accounts (About 20 but may increase) from a single IP for a single exchange (Coinbase in this case) and if yes, what would be the best way to achieve this using this library?

My understanding is throttling only works for accounts, not IP.

Thanks, and please ask if you have any follow-up questions.

**Comment by DoctorSlimm** [comment]
https://docs.cloud.coinbase.com/exchange/docs/rate-limits

It seems like coinbasepro throttles public endpoints by IP address, and private endpoints by profile ID (the page doesnt say pro but you arrive at it by following the link in https://developers.coinbase.com/docs/exchange/ which speaks about coinbasepro)

So the answer to your question depends on the distributions of types of requests in your asynchronous loop.

**Comment by AlphaNumeric99** [comment]
@DoctorSlimm Thanks for the detailed information. 

My loop only contains create order requests nothing else referencing the API except the object creation for exchange so I think they count as Private APIs only and that answers my question.
