### ISSUE TITLE
Gemini sandbox URLs

### ISSUE THREAD

**Issue by tauren** [ccxt/ccxt#1092]
- Programming Language: JS
- CCXT version: 1.10.394
- Exchange: gemini
- Method: urls

Would be nice to add a *gemini* test URL. The following urls are in the [gemini API docs](https://docs.gemini.com/rest-api/#sandbox-urls):

Website 
https://exchange.sandbox.gemini.com

REST API 
https://api.sandbox.gemini.com

WebSocket Feed 
wss://api.sandbox.gemini.com

Documentation 
https://docs.sandbox.gemini.com

**Comment by kroitor** [comment]
Added in 1.10.578. Thx!
