### ISSUE TITLE
Will fetchOrder in ccxt be added on Waves exchange?

### ISSUE THREAD

**Issue by kleninmaxim** [ccxt/ccxt#10929]
Currently, ccxt does not have the ability to find out information about the order by id
`[fetchOrder] => false`

But according to the api of the matcher , it can be found as follows:
`https://matcher.waves.exchange/matcher/orderbook/{base_asset}/{quote_asset}/{order_id}`

Are you planning to add a fetch order to find out information about any orders in ccxt?

**Comment by kroitor** [comment]
Added by @ttodua in CCXT 1.65.29+, the new build will arrive in ~20 minutes.
