### ISSUE TITLE
php bibox error on load_markets

### ISSUE THREAD

**Issue by Phantom1412** [ccxt/ccxt#10927]
- OS: Window 10
- Programming Language version: php
- CCXT version: 1.64.8
- Exchange: bibox
- Method: load_markets

There is an error because options array has only method described in camelCase, but method in underscore notation only exists.

```
ccxt\ExchangeError: fetchCurrenciesPrivate method not found, try underscore_notation instead of camelCase for the method being called
```

**Comment by carlosmiei** [comment]
@Phantom1412 Yup I was able to reproduce it, I'll take a look and I'll let you know as soon as I have more information
![image](https://user-images.githubusercontent.com/43336371/146518502-b81c5ba1-2c8f-4069-81db-9eb0e4e21da8.png)
