### ISSUE TITLE
Unified contract naming conventions

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#10931]
Hi everyone!

In order to unify the contract trading aspects CCXT is going to alter the way it handles symbols for derivatives, including:

- _futures_
- _perpetual swaps_ (aka _perpetual futures_)
- _options_

Previously, CCXT unified just the spot _symbols_ (as pairs of _base_ and _quote_ currencies). All contracts had exchange-specific _ids_.

The new unified contract naming rules are outlined here:

- https://docs.ccxt.com/en/latest/manual.html#contract-naming-conventions

From now on, all new code for all exchange integrations has to conform to the above contract naming conventions.
The old exchange-specific _ids_ for contracts will still work for backward-compatibility.
All existing exchanges will be migrated to the new contract naming schema through Q1 2022.

Thanks for using CCXT!

**Comment by daviidarr** [comment]
hi, is there a way to fetch all futures, including expired ? I think fetch_markets leaves expired out.

**Comment by kroitor** [comment]
> hi, is there a way to fetch all futures, including expired ? I think fetch_markets leaves expired out.

CCXT does not filter them out, it returns all the information from the exchange first-hand. If the exchange API endpoint does not list expired futures – CCXT can't invent that info out of thin air. But CCXT will never filter the exchange response in that manner, so you get what the exchange replies with.

**Comment by daviidarr** [comment]
Imrpovement suggestion:
Ftx has a PublicGetExpiredFutures
Do many exchange have this?
It could be an optionnal paramfor a existing fetch.

Cheers.

**Comment by kroitor** [comment]
> Imrpovement suggestion: 
> Ftx has a PublicGetExpiredFutures

Yep. We will add that in one way or another.

> Do many exchange have this? 

Not really, afaik.

> It could be an optionnal paramfor a existing fetch.

We will think on what would be the best mode for it, maybe with a standalone unified method like fetchExpiredMarkets.

**Comment by daviidarr** [comment]
Thanks.
NB: i dived into this when i realized ftx public GetFutures returned a non
existent "btt-perp" symbol, which crashed my code. This is an ftx issue not
a ccxt issue.

**Comment by ttodua** [comment]
_[ Related issue: https://github.com/ccxt/ccxt/issues/11121 ]_

**Comment by samgermain** [comment]
Every exchange uses the unified swap and future symbols now, except Binance, which uses the same symbols for swap as it does for spot

**Comment by kroitor** [comment]
I'm working on Binance rn to close this issue.
