### ISSUE TITLE
confronting with "ftx GET https://ftx.com/api/markets request timed out (10000 ms)" in live environment

### ISSUE THREAD

**Issue by recepdoganp** [ccxt/ccxt#10938]

**Comment by kroitor** [comment]
Make sure you don't violate these rules: https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter

**Comment by recepdoganp** [comment]
Now, I have adjusted my code accordingly, defining the "exchange" only once as the beginning and passing it as a params to the functions to run for the operations in line with the documentation. I'd say, the performance is better but during entire day I have done dozens of calls, there are still cases I get the same error.

At this point, I really don't know what to do. because I literally try 4-5 times sequentially, it works all; and then suddenly on the 6th (or later) eventually it breaks. Based on the documentation, if I were to get an error due to "ratelimit" I believe it would have failed for all tries not for only one.

**Comment by kroitor** [comment]
@recepdoganp could you please format the above code to make it readable? Use github markdown rules: 

- https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

Ideally, if you can paste a complete snippet (don't tear it apart), without your keys ofc, that would help resolve this issue quicker.

**Comment by recepdoganp** [comment]
Thanks for your feedback, I have revised the reply accordingly, hope this will help for the resolution.
To be honest, I have started to think that maybe there are exceptional FTX API related issues that my orders coincide.
I have let the BOT run last 8 hours interval. Only errors occurred at the beginning 3 times in a row (after redeployment) and afterwards, there are no issues, all orders are correctly placed. However the issue is, with this kind of errors I lose the trade opportunities which might result in a win. And it is not so much likely that API errors coincide with my trades as my trades are not triggered that often. (maybe once in 10 mins - just for testing I use 1M time frame; and even if so it's not only me using the API, everyone should have the same issue). My real intention is to use 5M interval, however, yesterday, when I was using it and had these errors I switched to 1M again just to see where the problem is and still couldn't figure it out yet. 

**DEFINITION OF THE EXCHANGE FTX**


```
const ccxt = require("ccxt");
const dotenv = require("dotenv");
dotenv.config({ path: "config/config.env" });

const ftx = new ccxt.ftx({
  apiKey: process.env.APIKEY,
  secret: process.env.APISECRET,
  enableRateLimit: true,
  headers: { "FTX-SUBACCOUNT": "DoganSUB" },
});

module.exports = { ftx };
```


**DEFINITION OF HANDLER FUNCTION WHERE EXCHANGE TO BE PASSED ON**

```
const makeOrder = async (exchange, ochl) => {
  try {
    let { side, orderPrice, takeProfit, stopLoss } =
      parseTradeViewInputIntoOrderInfo(ochl);
    console.log(
      `${side} Order Price: ${orderPrice}, Take Profit Price: ${takeProfit} Stop Loss Price: ${stopLoss}`
    );

    const balances = await fetchBalance(exchange);

    if (balances.USD.used === 0) {
      // cancel all open orders on the same MARKET
      await exchange.cancelAllOrders(process.env.MARKET, {
        conditionalOrdersOnly: true,
      });

      // fetch available free balance in USD

      // let amount = availableBalance / orderPrice;
      // console.log(amount);
      let amount = 0.001;
      let orderResult, stopLossOrder, takeProfitOrder;
      if (side === "buy") {
        orderResult = await exchange.createOrder(
          process.env.MARKET,
          "limit",
          side,
          amount,
          orderPrice
        );

        stopLossOrder = await exchange.createOrder(
          process.env.MARKET,
          "stop",
          "sell",
          amount,
          (price = undefined),
          (params = {
            triggerPrice: stopLoss,
            reduceOnly: true,
          })
        );
        takeProfitOrder = await exchange.createOrder(
          process.env.MARKET,
          "takeProfit",
          "sell",
          amount,
          (price = undefined),
          (params = {
            triggerPrice: takeProfit,
            reduceOnly: true,
          })
        );
      } else {
        orderResult = await exchange.createOrder(
          process.env.MARKET,
          "limit",
          side,
          amount,
          orderPrice
        );
        stopLossOrder = await exchange.createOrder(
          process.env.MARKET,
          "stop",
          "buy",
          amount,
          (price = undefined),
          (params = {
            type: "stop",
            triggerPrice: stopLoss,
            reduceOnly: true,
          })
        );

        takeProfitOrder = await exchange.createOrder(
          process.env.MARKET,
          "takeProfit",
          "buy",
          amount,
          (price = undefined),
          (params = {
            triggerPrice: takeProfit,
            reduceOnly: true,
          })
        );
      }
      console.log(`ORDER for ${side} created for price @$${orderPrice}`);
    } else {
      throw new Error("There is already an open POSITION");
    }
  } catch (err) {
    console.error(err.message);
  }
};

module.exports = { makeOrder };
```

**CALL OF THE FUNCTION AND USE OF FTX**


```
const { ftx } = require("../utils/exchange");
const { makeOrder } = require("../utils/operations");

exports.buyOrder = async (req, res) => {
  try {
    console.log(req.body.text);
    await makeOrder(ftx, req.body.text);

    return res.send(req.body.text);
  } catch (err) {
    console.error(err);
  }
};

exports.sellOrder = async (req, res) => {
  try {
    console.log(req.body.text);
    await makeOrder(ftx, req.body.text);
    return res.send(req.body.text);
  } catch (err) {
    console.error(err);
  }
};
```

**FOR THE SAKE OF ALIGNMENT, THE ERROR RESULT ON CONSOLE**

```
Function execution started
SHORT Opportunity for ETHPERP @2021-12-18T23:47:03Z Open:3968 Close:3965.8 High:3969.2 Low:3965.4
sell Order Price: 3965.8, Take Profit Price: 3959 Stop Loss Price: 3969.2
ftx GET https://ftx.com/api/markets request timed out (10000 ms)
Cannot read property 'USD' of undefined
Function execution took 11 ms, finished with status code: 200
```

**Comment by recepdoganp** [comment]
I guess I am not going to get any feedback on that, and I keeping having the same problem

Only solution that I could come up with:

1. Contact FTX to understand if I am subject to DDoS Protection By Cloudflare / Incapsula
2. Try a workaround leveraging on [RequestTimeout Error Handling](https://docs.ccxt.com/en/latest/manual.html#requesttimeout) changing the timeout property of the exchange manually from 10000ms to 4000ms in order to avoid further delays that can result in losing a trade.

**Comment by recepdoganp** [comment]
no feedback received

**Comment by kroitor** [comment]
@recepdoganp plz read this post carefully: https://github.com/ccxt/ccxt/issues/10938#issuecomment-997358229
