### ISSUE TITLE
Kraken - Market - Limit Cost Min set at zero when that's not true

### ISSUE THREAD

**Issue by bonetjoshua** [ccxt/ccxt#10944]
- OS: Microsoft
- Programming Language version: Python
- CCXT version: 1.63.14

So I retrieve that market data for Kraken and when I ask for the minimum cost, all of the values come to zero. I was reading the Kraken support and they have that the minimum for all USD is $10. Now the current limit minimum is 0.0001 for BTC/USD = $4 at current value which is clearly less than $10. So if you program it with CCXT, it will think that the conditions are met, when in fact I get an insufficient funds error. Is it possible to fix the limit cost min depending on their currencies? 

I know I can do that in my end but I would prefer that it gets officialized with Kraken's API , I do believe your team is capable of this because of the strong influence you have on the crypto community.

```
InsufficientFunds: kraken {"error":["EOrder:Insufficient funds"]}
```
https://support.kraken.com/hc/en-us/articles/205893708-Minimum-order-size-volume-for-trading

**Comment by bonetjoshua** [comment]
Did it get fixed?

**Comment by kroitor** [comment]
@bonetjoshua the new build will arrive in ~20 minutes, should be fixed there. We had to set it `undefined/None/null` there, cause we already take as much as Kraken API provides:

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/kraken.py#L386
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/kraken.py#L463
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/kraken.py#L483
- ...

**Comment by bonetjoshua** [comment]
Ok then, I'll do it in my end, thank you
