### ISSUE TITLE
Can not disable exchangeInfo() call on binance

### ISSUE THREAD

**Issue by fridary** [ccxt/ccxt#10949]
- OS: Mac OS 11.6.1
- Programming Language version: Python 3.8.12
- CCXT version: 1.61.92

I am trying to disable `exchangeInfo` from binance, because it takes 10 API weight just to get info, but anyway `ccxt` make request. How to fix?

```
import asyncio
import ccxt.async_support as ccxt

async def test():
	exchange = ccxt.binance({
		'verbose': True,
		'enableRateLimit': False,
		'rateLimit': 0.5 * 1000,
	})
	try:
		book = await exchange.fetch_l2_order_book('BTC/USDT', 5)
	except ccxt.BaseError as e:
		print(type(e).__name__, str(e), str(e.args))

	await exchange.close()

if __name__ == '__main__':
	asyncio.get_event_loop().run_until_complete(test())
```
	
```
Request: GET https://api.binance.com/api/v3/exchangeInfo None None
Response: GET https://api.binance.com/api/v3/exchangeInfo 200 ...
Request: GET https://api.binance.com/api/v3/depth?symbol=BTCUSDT&limit=5 None None
Response: GET https://api.binance.com/api/v3/depth?symbol=BTCUSDT&limit=5 200 ...
```

**Comment by kroitor** [comment]
@fridary if you don't load the exchange info, you will not be able to use the unified API, as explained here:

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

If general, we highly recommend reading the entire Manual from top to bottom - it will really save your time:

- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/


If you don't load the markets, your usage will be reduced to just the implicit API:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api

Also, you should not create the exchange and destroy it all the time, instead, create it once, and run your actions reusing the same exchange instance, until you're done with it. This is specifically noted in the Manual here:

- https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter

If you're instantiating it over and over, you will run into rate limiting problems. Just don't destroy it to reuse it to avoid reinstantiation. That will load your markets just once.

Also, see this snippet jfyi: https://github.com/ccxt/ccxt/blob/master/examples/js/shared-load-markets.js

Hope that answers your question, let us know if not.
