### ISSUE TITLE
About EndPoint errors in Bybit Spot API

### ISSUE THREAD

**Issue by bongkook** [ccxt/ccxt#10946]
Hello.
There is an error in Bybit's Spot EndPoint below.

--- bybit.js---
'private': {
     'get': [
         'order',
         'open-orders',
         'history-orders',
         'myTrades',
         'account',
         'time',
     ],
     'post': [
         'order',
     ],
     'delete': [
         'order',
         'order/fast',
     ],
}
For example, if spotPrivateGetAccount() is executed, the following error occurs.
ExchangeNotAvailable: bybit GET https://api.bybit.com/spot/private/v1/account 404 Not Found

If you look at the Bybit API, you don't need private.
All of the above endpoints are applicable.

Please fix update.
thank you.

**Comment by kroitor** [comment]
I'm rewriting Bybit right now, will get it finished in the coming days.

**Comment by bongkook** [comment]
thank you so much.

**Comment by kroitor** [comment]
@bongkook Will update you when it arrives. Closing it for now.
