### ISSUE TITLE
Getting error NetworkError: connection closed by remote server, closing code 1006 when running watchOrderBook

### ISSUE THREAD

**Issue by beersoup** [ccxt/ccxt#10955]
I'm getting 'NetworkError: connection closed by remote server, closing code 1006' when running watchOrderBook with multiple symbols everytime. Is there a way to fix this? I'm using NodeJs wih code example from the repo.

Thank you in advance.

**Comment by kroitor** [comment]
@beersoup which exchange is it? What is your version of CCXT? Can you please paste your code?

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

Binance has recently tightened their limitations on the WS API, it may be related. We will investigate and will fix this, but we need more info from you.

**Comment by beersoup** [comment]
It's Gateio. I'm using CCXTPRO for this code I'm not sure which version but thinking the last one because I just installed it last week. For CCXT, "ccxt": "^1.63.23" in my package.json

`const ccxtpro = require ('ccxt.pro');


(async function watchOrderBookGate () {

    const exchangeGateio = new ccxtpro.gateio ({
        enableRateLimit: true
    })


    let symbols = [
    'ALEPH/USDT',
    'POOL/USDT',
    'KGC/USDT',
    'MCO2/USDT',
    'FINE/USDT',
    'SBR/USDT',
    'ALICE3L/USDT',
    'BAO/USDT',
    'VIDYX/USDT',
    'HERO/USDT',
    'SHARE/USDT',
    'FIN/USDT',
    'MTV/USDT',
    'MOO/USDT',
    'SMTY/USDT',
    'ORAO/USDT',
    'MAN/USDT',
    'LYXE/USDT',
    'SPS/USDT',
    'WSIENNA/USDT',
    'NFTX/USDT',
    'OPUL/USDT',
    'ICP3L/USDT',
    'CTT/USDT',
    'BSV3L/USDT',
    'VELO/USDT',
    'BACON/USDT',
    'C983L/USDT',
    'CZZ/USDT',
    'RACA3S/USDT',
    'DMLG/USDT',
    'ASM/USDT',
    'ONC/USDT',
    'NIF/USDT',
    'BNC/USDT',
    'MATIC3S/USDT',
    'AMPL3S/USDT',
    'WEX/USDT',
    'RACA3L/USDT',
    'OPA/USDT',
    'VEGA/USDT',
    'FSN/USDT',
    'KYL/USDT',
    'DYDX3S/USDT',
    'MANA3S/USDT',
    'ALICE3S/USDT',
    'PCX/USDT',
    'ICP3S/USDT',
    'MLT/USDT',
    'RBN/USDT',
    'AMPL3L/USDT',
    'TAI/USDT',
    'HERA/USDT',
    'XAVA/USDT',
    'LSS/USDT',
    'SNX3S/USDT',
    'PBR/USDT',
    'PRQ/USDT',
    'MATIC3L/USDT',
    'LPOOL/USDT',
    'PSP/USDT',
    'BXC/USDT',
    'CBK/USDT',
    'MANA3L/USDT',
    'OCT/USDT',
    'L3P/USDT',
    'NEO3L/USDT',
    'FROG/USDT',
    'CHAMP/USDT',
    'XNFT/USDT',
    'BCH3S/USDT',
    'CRPT/USDT',
    'ROUTE/USDT',
    'VRA/USDT',
    'ONS/USDT',
    'ZEC3L/USDT',
    'FRA/USDT',
    'BLANK/USDT',
    'IOST3L/USDT',
    'DDD/USDT',
    'UNQ/USDT',
    'GITCOIN/USDT',
    'THG/USDT',
    'FLY/USDT',
    'CREDIT/USDT',
    'RENA/USDT',
    'NBOT/USDT',
    'HT3L/USDT',
    'ASD/USDT',
    'PIG/USDT',
    'THN/USDT',
    'BCUG/USDT',
    'HOTCROSS/USDT',
    'SKYRIM/USDT',
    'POT/USDT',
    'CS/USDT',
    'A5T/USDT',
    'YIN/USDT',
    'PEOPLE/USDT',
    'POLC/USDT',
    'BZZ3L/USDT',
    'UNO/USDT',
    'CELL/USDT',
    'FODL/USDT',
    'WAG/USDT',
    'VENT/USDT',
    'WND/USDT',
    'ZEC3S/USDT',
    'DOS/USDT',
    'HT3S/USDT',
    'LAND/USDT',
    'RING/USDT',
    'KUMA/USDT',
    'CRBN/USDT',
    'XMARK/USDT',
    'SAKE/USDT',
    'FTM3L/USDT',
    'RFUEL/USDT',
    'NEO3S/USDT',
    'C983S/USDT',
    'DOGE3S/USDT',
    'BZZ3S/USDT',
    'FTM3S/USDT',
    'MNW/USDT',
    'WAGYU/USDT',
    'ANGLE/USDT',
    'JFI/USDT',
    'USDG/USDT',
    'DMTR/USDT',
    'GOLDMINER/USDT',
    'WIT/USDT',
    'DOGE3L/USDT',
    'FORM/USDT',
    'DMS/USDT',
    'ONX/USDT',
    'TXT/USDT',
    'NIIFI/USDT',
    'VRX/USDT',
    'KEEP3L/USDT',
    'ORBS/USDT',
    'RAM/USDT',
    'AME/USDT',
    'ENV/USDT',
    'COTI3S/USDT',
    'ACH3S/USDT',
    'IHT/USDT',
    'CTRC/USDT',
    'SFUND/USDT',
    'NFT/USDT',
    'TSHP/USDT',
    'VLXPAD/USDT',
    'GAN/USDT',
    'O3/USDT',
    'TULIP/USDT',
    'TT/USDT',
    'SHILL/USDT',
    'PSB/USDT',
    'XDC/USDT',
    'LON3L/USDT',
    'HE/USDT',
    'SKU/USDT',
    'IDEA/USDT',
    'ACH3L/USDT',
    'BLIN/USDT',
    'VRT/USDT',
    'DOT5S/USDT',
    'XLM3L/USDT',
    'LIQ/USDT',
    'EPK/USDT',
    'ZCN/USDT',
    'CVC3L/USDT',
    'KEEP3S/USDT',
    'MNY/USDT',
    'CSTR/USDT',
    'FRAX/USDT',
    'BAGS/USDT',
    'WOO/USDT',
    'SNX3L/USDT',
    'OKB3L/USDT',
    'SAFEMOON/USDT',
    'IOI/USDT',
    'LAMB/USDT',
    'OKB3S/USDT',
    'EOS3S/USDT',
    'DBC/USDT',
    'EMON/USDT',
    'SIDUS/USDT',
    'CVC3S/USDT',
    'LON3S/USDT',
    'MAHA/USDT',
    'IOST3S/USDT',
    'EQX/USDT',
    'WHALE/USDT',
    'GRAP/USDT',
    'AVAX3S/USDT',
    'VET3S/USDT',
    'KPAD/USDT',
    'CRO/USDT',
    'LEMD/USDT',
    'UMB/USDT',
    'NUM/USDT',
    'SHOE/USDT',
    'SDN/USDT',
    'BRKL/USDT',
    'ELEC/USDT',
    'SFG/USDT',
    'COFIX/USDT',
    'CWAR/USDT',
    'WILD/USDT',
    'ADAPAD/USDT',
    'PPS/USDT',
    'SHIB3S/USDT',
    'ZCX/USDT',
    'DYDX3L/USDT',
    'ASTRO/USDT',
    'GLQ/USDT',
    'PROPS/USDT',
    'KFT/USDT',
    'EOS3L/USDT',
    'API3/USDT',
    'LOON/USDT',
    'AVAX3L/USDT',
    'VET3L/USDT',
    'LYM/USDT',
    'LBK/USDT',
    'LAVA/USDT',
    'RSV/USDT',
    'KIF/USDT',
    'TOTM/USDT',
    'TITA/USDT',
    'COTI3L/USDT',
    'DOT5L/USDT',
    'TRADE/USDT',
    'MTA/USDT',
    'YIELD/USDT',
    'KART/USDT',
    'SYLO/USDT',
    'BASE/USDT',
    'PET/USDT',
    'GZONE/USDT',
    'Super Bitcoin/USDT',
    'NAFT/USDT',
    'Game.com/USDT',
    'TIME/USDT',
    'QASH/USDT',
    'FAST/USDT',
    'KNIGHT/USDT',
    'CEEK/USDT',
    'AR3L/USDT',
    'AAVE3S/USDT',
    'TARA/USDT',
    'SPO/USDT',
    'DSLA/USDT',
    'CFX3S/USDT',
    'XPNET/USDT',
    'WSG/USDT',
    'DASH3L/USDT',
    'BTL/USDT',
    'CPOOL/USDT',
    'ALPHA3S/USDT',
    'BLOK/USDT',
    'WIKEN/USDT',
    'OMG3S/USDT',
    'BCH5S/USDT',
    'MED/USDT',
    'CGG/USDT',
    'CRE/USDT',
    'SOURCE/USDT',
    'ABT/USDT',
    'DPET/USDT',
    'WOM/USDT',
    'BENQI/USDT',
    'LAT/USDT',
    'ITGR/USDT',
    'DLTA/USDT',
    'SMT/USDT',
    'APYS/USDT',
    'STOX/USDT',
    'GMAT/USDT',
    'RAZOR/USDT',
    'RAGE/USDT',
    'MTR/USDT',
    'SWASH/USDT',
    'FX/USDT',
    'DERI/USDT',
    'DFND/USDT',
    'BLES/USDT',
    'BTC3S/USDT',
    'BKC/USDT',
    'THETA3L/USDT',
    'ETH3L/USDT',
    'DOGEDASH/USDT',
    'PNL/USDT',
    'HMT/USDT',
    'STND/USDT',
    'LTC3L/USDT',
    'TOKAU/USDT',
    'CWS/USDT',
    'SWOP/USDT',
    'AGS/USDT',
    'CATGIRL/USDT',
    'GDAO/USDT',
    'PMON/USDT',
    'MNGO/USDT',
    'MSOL/USDT',
    'UOS/USDT',
    'SLICE/USDT',
    'NSBT/USDT',
    'BEAM3L/USDT',
    'MM/USDT',
    'FTT3L/USDT',
    'OMI/USDT',
    'TIPS/USDT',
    'SQUID/USDT',
    'FEI/USDT',
    'GEM/USDT',
    'PVU/USDT',
    'LION/USDT',
    'BLACK/USDT',
    'CUDOS/USDT',
    'PCNT/USDT',
    'OVR/USDT',
    'ETC3S/USDT',
    'MER/USDT',
    'BOBA/USDT',
    'BAC/USDT',
    'ONE3S/USDT',
    'OPIUM/USDT',
    'JST3L/USDT',
    'BONDLY/USDT',
    'RAZE/USDT',
    'LDO/USDT',
    'ORO/USDT',
    'LITH/USDT',
    'RLY/USDT',
    'NEAR3S/USDT',
    'XLM3S/USDT',
    'AKT/USDT',
    'HCT/USDT',
    'BZZ/USDT',
    'SRM3L/USDT',
    'EWT/USDT',
    'CORN/USDT',
    'HYDRA/USDT',
    'STEP/USDT',
    'MATTER/USDT',
    'LIKE/USDT',
    'HitChain/USDT',
    'LEO/USDT',
    'AQT/USDT',
    'LINK3S/USDT',
    'IMX/USDT',
    'EFI/USDT',
    'TAUR/USDT',
    'MOOV/USDT',
    'TCP/USDT',
    'SCLP/USDT',
    'RBC/USDT',
    'SPI/USDT',
    'XEC3L/USDT',
    'XCV/USDT',
    'KISHU/USDT',
    'LIEN/USDT',
    'ATOM3S/USDT',
    'ACE/USDT',
    'CIR/USDT',
    'TRIBE3S/USDT',
    'EVA/USDT',
    'BBANK/USDT',
    'BLANKV2/USDT',
    'BAL3S/USDT',
    'SAFEMARS/USDT',
    'TIP/USDT',
    'NWC/USDT',
    'VALUE/USDT',
    'JOE/USDT',
    'BIT/USDT',
    'MSU/USDT',
    'CRV3L/USDT',
    'SHFT/USDT',
    'BP/USDT',
    'KBOX/USDT',
    'SAO/USDT',
    'DUCK2/USDT',
    'DEFILAND/USDT',
    'CARDS/USDT',
    'RAY3S/USDT',
    'KAVA3L/USDT',
    'GARD/USDT',
    'GRT3L/USDT',
    'BFC/USDT',
    'NIFT/USDT',
    'ORION/USDT',
    'CERE/USDT',
    'MGA/USDT',
    'SKL3L/USDT',
    'SFIL/USDT',
    'TEER/USDT',
    'KLV/USDT',
    'MKR3L/USDT',
    'UST/USDT',
    'OIN/USDT',
    'YCT/USDT',
    'SHR/USDT',
    'NFTD/USDT',
    'MATH/USDT',
    'DERC/USDT',
    'FEG/USDT',
    'KMON/USDT',
    'ORC/USDT',
    'LIME/USDT',
    'BSCS/USDT',
    'VAIOT/USDT',
    'RVC/USDT',
    'PEARL/USDT',
    'COMP3S/USDT',
    'PHTR/USDT',
    'ALGO3L/USDT',
    'BFT/USDT',
    'SOUL/USDT',
    'DOE/USDT',
    'POOLZ/USDT',
    'DG/USDT',
    'MPH/USDT',
    'LOCG/USDT',
    'CATE/USDT',
    'DPY/USDT',
    'EGAME/USDT',
    'GRIN3L/USDT',
    'UNI3S/USDT',
    'SXP3L/USDT',
    'GSE/USDT',
    'WEST/USDT',
    'BTM3S/USDT',
    'ARRR/USDT',
    'KST/USDT',
    'ALY/USDT',
    'WAVES3L/USDT',
    'RUNE3S/USDT',
    'LIFE/USDT',
    'OCC/USDT',
    'BMON/USDT',
    'KINE/USDT',
    'COOK/USDT',
    'BDT/USDT',
    'XAUT/USDT',
    'MIST/USDT',
    'ANC/USDT',
    'HBAR3S/USDT',
    'KTN/USDT',
    'STAR/USDT',
    'BMI/USDT',
    'LOWB/USDT',
    'ENJ3S/USDT',
    'DILI/USDT',
    'UNN/USDT',
    'MMM/USDT',
    'EDEN/USDT',
    'MUSE/USDT',
    'KLAY3S/USDT',
    'CIRUS/USDT',
    'YFDAI/USDT',
    'SAND3L/USDT',
    'SENC/USDT',
    'MTL3L/USDT',
    'FIRE/USDT',
    'NEST/USDT',
    'XRP3S/USDT',
    'VSO/USDT',
    'NIFTSY/USDT',
    'OCN/USDT',
    'GOFX/USDT',
    'CYS/USDT',
    'VEMP/USDT',
    'SOL3L/USDT',
    'LTC5L/USDT',
    'MIMIR/USDT',
    '1INCH3S/USDT',
    'XRP5S/USDT',
    'DOGGY/USDT',
    'IOEN/USDT',
    'FOX/USDT',
    'ETERNAL/USDT',
    'CSPR3L/USDT',
    'BLOCK/USDT',
    'SFI/USDT',
    'DEVT/USDT',
    'LEASH/USDT',
    'BAKED/USDT',
    'PNG/USDT',
    'NBP/USDT',
    'PRARE/USDT',
    'LFW/USDT',
    'PARA/USDT',
    'DES/USDT',
    'XCH3L/USDT',
    'OKT/USDT',
    'HOGE/USDT',
    'SUSHI3L/USDT',
    'CAPS/USDT',
    'HSC/USDT',
    'STBU/USDT',
    'OLT/USDT',
    'ACH/USDT',
    'EMPIRE/USDT',
    'GTH/USDT',
    'MEPAD/USDT',
    'WNCG/USDT',
    'MARS/USDT',
    'BOO/USDT',
    'YFII3L/USDT',
    'WICC/USDT',
    'METIS/USDT',
    'ROSE3S/USDT',
    'FEAR/USDT',
    'APN/USDT',
    'QANX/USDT',
    'CONV/USDT',
    'QTUM3S/USDT',
    'LRC3S/USDT',
    'TRX3S/USDT',
    'ROOK/USDT',
    'WAR/USDT',
    'VIDY/USDT',
    'LUNA3S/USDT',
    'DARK/USDT',
    'CFG/USDT',
    'TRVL/USDT',
    'XCAD/USDT',
    'RIN/USDT',
    'BNB3L/USDT',
    'BTO/USDT',
    'ROSN/USDT',
    'STR/USDT',
    'MINT/USDT',
    'XTAG/USDT',
    'GM/USDT',
    'DHV/USDT',
    'SPA/USDT',
    'STARL/USDT',
    'BCDN/USDT',
    'BCMC/USDT',
    'LIQUIDUS/USDT',
    'ALN/USDT',
    'K21/USDT',
    'MAPS/USDT',
    'BSV5L/USDT',
    'XMR3L/USDT',
    'KTON/USDT',
    'ATK/USDT',
    'VEE/USDT',
    'SASHIMI/USDT',
    'HYVE/USDT',
    'OXY/USDT',
    'BOA/USDT',
    'SERO3S/USDT',
    'MARSH/USDT',
    'GALA3S/USDT',
    'KINGSHIB/USDT',
    'WHITE/USDT',
    'SENATE/USDT',
    'EGLD3S/USDT',
    'STRP/USDT',
    'MIX/USDT',
    'KMA/USDT',
    'CHAIN/USDT',
    'ONT3S/USDT',
    'GGG/USDT',
    'CSPR/USDT',
    'POLI/USDT',
    'QRDO/USDT',
    'GALA3L/USDT',
    'OPEN/USDT',
    'PAF/USDT',
    'POG/USDT',
    'ADEL/USDT',
    'XYM/USDT',
    'TSL/USDT',
    'RMRK/USDT',
    'MCASH/USDT',
    'TOOLS/USDT',
    'FAR/USDT',
    'BLT/USDT',
    'DIS/USDT',
    'MOBI/USDT',
    'DDOS/USDT',
    'ETH5S/USDT',
    'XDEFI/USDT',
    'OLYMPUS/USDT',
    'FEVR/USDT',
    'NRV/USDT',
    'KIN/USDT',
    'ETH5L/USDT',
    'KALM/USDT',
    'DX/USDT',
    'SHI/USDT',
    'FXF/USDT',
    'NOIA/USDT',
    'DOSE/USDT',
    'VLX/USDT',
    'BATH/USDT',
    'CORAL/USDT',
    '1ART/USDT',
    'BTC5L/USDT',
    'POLYDOGE/USDT',
    'CRP/USDT',
    'SRP/USDT',
    'DFA/USDT',
    'DDIM/USDT',
    'ZIL3L/USDT',
    'NYZO/USDT',
    'CORE/USDT',
    'INSUR/USDT',
    'LRN/USDT',
    'JGN/USDT',
    'NEXT/USDT',
    'METAX/USDT',
    'DRGN/USDT',
    'WAVES3S/USDT',
    'ZSC/USDT',
    'NUX/USDT',
    'ZOON/USDT',
    'MTRG/USDT',
    'MINA3L/USDT',
    'MRCH/USDT',
    'FST/USDT',
    'BTC5S/USDT',
    'GAIA/USDT',
    'COMBO/USDT',
    'NFTY/USDT',
    'FIL3S/USDT',
    'ELON/USDT',
    'LUFFY/USDT',
    'SNOW/USDT',
    'UNCX/USDT',
    'TABOO/USDT',
    'UMX/USDT',
    'ZIL3S/USDT',
    'ARMOR/USDT',
    'KONO/USDT',
    'KSM3L/USDT',
    'MINI/USDT',
    'MINA3S/USDT',
    'NU3L/USDT',
    'ARPA3L/USDT',
    'ORAI/USDT',
    'STOS/USDT',
    'SERO3L/USDT',
    'SKRT/USDT',
    'OKB/USDT',
    'ATD/USDT',
    'MTN/USDT',
    'COMP3L/USDT',
    'PWAR/USDT',
    'CVX/USDT',
    'SNFT/USDT',
    'FILDA/USDT',
    'BORING/USDT',
    'FLOKI/USDT',
    'EGLD3L/USDT',
    'BU/USDT',
    'STETH/USDT',
    'DEK/USDT',
    'KSM3S/USDT',
    'ARPA3S/USDT',
    'CART/USDT',
    'NU3S/USDT',
    'ZEN3S/USDT',
    'GS/USDT',
    'ZEN3L/USDT',
    'LIBRE/USDT',
    'MELI/USDT',
    'XRUNE/USDT',
    'SERO/USDT',
    'XCH/USDT',
    'EOS5S/USDT',
    'FOREX/USDT',
    'ZAM/USDT',
    'HGET/USDT',
    'LKR/USDT',
    'AXS3L/USDT',
    'ADA3S/USDT',
    'NAX/USDT',
    'NORD/USDT',
    'MONS/USDT',
    'BOSON/USDT',
    'DVP/USDT',
    'Morpher/USDT',
    'BETU/USDT',
    'DOP/USDT',
    'SMG/USDT',
    'BURP/USDT',
    'GOD/USDT',
    'GUM/USDT',
    'DORA/USDT',
    'DIVER/USDT',
    '100X/USDT',
    'DV/USDT',
    'ARNX/USDT',
    'IPAD/USDT',
    'AXS3S/USDT',
    'SKM/USDT',
    'EOS5L/USDT',
    'ADA3L/USDT',
    'STC/USDT',
    'MDS/USDT',
    'STZ/USDT',
    'CRU/USDT',
    'MAT/USDT',
    'CNNS/USDT',
    'BTF/USDT',
    'ZPT/USDT',
    'LGCY/USDT',
    'SOLR/USDT',
    'ETHA/USDT',
    'ALPA/USDT',
    'FIL3L/USDT',
    'SWAP/USDT',
    'XTZ3S/USDT',
    'DYP/USDT',
]


    await Promise.all (symbols.map (symbol =>
        (async () => {
            while (true) {

                try {
                        let orderbook = await exchangeGateio.watchOrderBook (symbol)
                        if(orderbook['asks'][0] != undefined && orderbook['bids'][0] != undefined) {

                            let ts = Math.round((new Date()).getTime() / 1000)

                            let askPriceWithTime = {}
                            askPriceWithTime.price = orderbook['asks'][0].slice(0)[0]
                            askPriceWithTime.quantity = orderbook['asks'][0].slice(-1)[0]
                            askPriceWithTime.time = ts

                            console.log('ORDER', askPriceWithTime)

                        }

                } catch (e) {
                    console.log (symbol, e)
                }
            }
        }) ())
    )

}) ()`

**Comment by beersoup** [comment]
Here is some part of the error, it happens after running code 2-3 minutes and after start running again it's more frequently.

GEM/USDT NetworkError: connection closed by remote server, closing code 1006
    at WsClient.onClose (c:\Projects\twitter-search\node_modules\ccxt.pro\js\base\Client.js:227:25)
    at WebSocket.onClose (c:\Projects\twitter-search\node_modules\ws\lib\event-target.js:136:16)
    at WebSocket.emit (events.js:314:20)
    at WebSocket.emitClose (c:\Projects\twitter-search\node_modules\ws\lib\websocket.js:246:10)
    at Receiver.receiverOnFinish (c:\Projects\twitter-search\node_modules\ws\lib\websocket.js:998:20)
    at Receiver.emit (events.js:314:20)
    at finish (_stream_writable.js:645:10)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  constructor: [class NetworkError extends BaseError]
}
PVU/USDT NetworkError: connection closed by remote server, closing code 1006
    at WsClient.onClose (c:\Projects\twitter-search\node_modules\ccxt.pro\js\base\Client.js:227:25)
    at WebSocket.onClose (c:\Projects\twitter-search\node_modules\ws\lib\event-target.js:136:16)
    at WebSocket.emit (events.js:314:20)
    at WebSocket.emitClose (c:\Projects\twitter-search\node_modules\ws\lib\websocket.js:246:10)
    at Receiver.receiverOnFinish (c:\Projects\twitter-search\node_modules\ws\lib\websocket.js:998:20)
    at Receiver.emit (events.js:314:20)
    at finish (_stream_writable.js:645:10)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  constructor: [class NetworkError extends BaseError]
}

**Comment by beersoup** [comment]
More info : 

**Programming language and language version number** : NodeJs version 14.9.0

 **CCXT / CCXT Pro library version number** : 6.14.8

**Exchange** : Gateio

**Comment by kroitor** [comment]
@beersoup thank you! We will investigate and will be back to you shortly!

**Comment by kroitor** [comment]
@beersoup i think you're trying to subscribe for too many pairs. The exchanges will accept 30-50-100 subscriptions on average, but not 700+. You should split the execution across multiple machines/IPs. To prove this point I'd recommend subscribing to 5-10 pairs and see if it works, then increase the number of subscriptions gradually until it stops working. Hope it helps, let us know if not.

**Comment by beersoup** [comment]
Thank you for answering. Ok, I will test it.

**Comment by beersoup** [comment]
I remember it works quiet well with 50 - 100 subscriptions. Thanks!

**Comment by gnsawant** [comment]
connection closed by remote server with error code 1006 for many exchanges while requesting watch_ticker for symbols from exchnage... cryptocom, kraken, kucoin, bitfinex, bitfinex2, okx, coinbasepro, and many others....its running only for few exchanges like mexc, gateio, whitebit, binanceus.... I checked for api from exchnage.urls but those fail to reach to page

**Comment by gnsawant** [comment]
is there any way to resolve this issue??
I have used exchnage.streaming['keepAlive'] property but still within few minutes it raises error
