### ISSUE TITLE
Move exchange specific logic into parseBalance

### ISSUE THREAD

**Issue by fernandocalsa** [ccxt/ccxt#10960]
- OS: all
- Programming Language version: JS
- CCXT version: 1.63.10

Hi all! first of all, thanks for this library, it is very useful!

I am checking the code base and I see some code that is not following the structure of similar methods. For example, any `fetch` method follows this structure
```js
async fetchSomething (params) {
  // 1. prepare the request
  const request = {}
  // 2. execute the request
  const response = await this[method] (request)
  // 3. call to parse with raw response
  return this.parseSomething(response)
}

parseSomething (response) {
  // Exchange specific parse
  return super.parseSomething(response)
}
```

This is very cool as we split fetching from parsing. But for `fetchBalance` method is something like this
```js
async fetchBalance (params) {
  // 1. prepare the request
  const request = {}
  // 2. execute the request
  const response = await this[method] (request)
  // 3. preparse the balance
  const result = { info: response }
  // 4. call to parse with pre parsed data
  return this.parseBalance(result)
}
```

Is there any reason why this is done in this way? I think `fetchBalance` should follow the same rules than other `fetch` methods, and should pass to the `parseBalance` method the raw response from the exchange, so the exchange specific parse logic is done in the `parse` method and not in the `fetchBalance`.

I've been working on it and it works fine for Binance, so I could create a quick PR and start moving the logic for every exchange.

**Comment by frosty00** [comment]
`parseBalance` is in the base class and it populates the fields `['free', 'used', 'total']` so that `balance['free']['USDT']` and `balance['USDT']['free']` are equivalent. I don't really think it is critical to move the parsing out of `fetchBalance` at this stage.

**Comment by kroitor** [comment]
We will detach the parsing logic from fetchBalance's implementations from all exchanges, however, since `parseBalance` is already used for a different purpose, we will come up with a better name for the parser.

**Comment by kroitor** [comment]
Closing this for now, if you don't mind. Feel free to reopen it or just ask further questions if any.
