### ISSUE TITLE
Kraken fetchOrderTrades() Error

### ISSUE THREAD

**Issue by JohnSmithyy** [ccxt/ccxt#10969]
OS: Ubuntu WSL
Programming Language version: Python3.8
CCXT version: 1.62.38

Here is the minimal code:
```
exchange_id = "Kraken"
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class(
            {'apiKey': api_key, 'secret': api_secret,
            'enableRateLimit': True,})

orderId = "ABCD-1234" #just an example
orderDetails = exchange.fetch_order_trades(orderId)
print(orderDetails)
```

Here is the error. What is the trades param or an array of trade id strings? I thought have order id would be enough to get details on the order.
```
ccxt.base.errors.ArgumentsRequired: kraken fetchOrderTrades() requires a unified order structure in the params argument or a 'trades' param(an array of trade id strings)
```

**Comment by kroitor** [comment]
@JohnSmithyy as the error message says, the Kraken API requires you to specify the exact trade ids in `params` for this method, check the code here: https://github.com/ccxt/ccxt/blob/master/python/ccxt/kraken.py#L1324
Let us know if that does not answer your question.

**Comment by kroitor** [comment]
Feel free to reopen it if necessary.

**Comment by JohnSmithyy** [comment]
Is trade id the same as order id in this case? How would we generalize this snippet for all exchanges? Or in other words, how would I check whether additional params are needed for each exchange?

**Comment by JohnSmithyy** [comment]
Another question I had is what is the difference between the `fetchOrder` and `fetchOrderTrades` ?

**Comment by JohnSmithyy** [comment]
> Another question I had is what is the difference between the `fetchOrder` and `fetchOrderTrades` ?

After reading the docs a bit more, I understand that `fetchOrder` is relating to the order in general and `fetchOrderTrades` relates to "fills" aka orders/trades that were filled. Is my understanding correct?

**Comment by kroitor** [comment]
> After reading the docs a bit more, I understand that `fetchOrder` is relating to the order in general and `fetchOrderTrades` relates to "fills" aka orders/trades that were filled. Is my understanding correct?

Yes, that is correct.

**Comment by JohnSmithyy** [comment]
> > After reading the docs a bit more, I understand that `fetchOrder` is relating to the order in general and `fetchOrderTrades` relates to "fills" aka orders/trades that were filled. Is my understanding correct?
> 
> Yes, that is correct.

Thank you for clearing that up.

> @kroitor Is trade id the same as order id in this case? How would we generalize this snippet for all exchanges? Or in other words, how would I check whether additional params are needed for each exchange?

How would I go about handling this? Seems every exchange will have its own additional params needed to perform `fetchOrderTrades`.

**Comment by kroitor** [comment]
> How would I go about handling this? Seems every exchange will have its own additional params needed to perform `fetchOrderTrades`.

Not all, but this one does, yes. Kraken is not very standard in regard of order trades, unfortunately. I will look into adding a workaround. In the meantime, you have to handle it in a special-case like `if (exchange.id === 'kraken') { }`.

**Comment by JohnSmithyy** [comment]
> > How would I go about handling this? Seems every exchange will have its own additional params needed to perform `fetchOrderTrades`.
> 
> Not all, but this one does, yes. Kraken is not very standard in regard of order trades, unfortunately. I will look into adding a workaround. In the meantime, you have to handle it in a special-case like `if (exchange.id === 'kraken') { }`.

Ah shoot. I will do a special case for now, I'd love to see what the workaround is when it's released! 

Thank you for taking the time to answer my questions! Keep up the good work you and your team does for ccxt :)
