### ISSUE TITLE
FTX: 'canceled' ccxt status for Partially Filled & Cancelled order  

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#10966]
We have received 'canceled' ccxt status in order response but in the 'info' parameters there is a 'closed' status and 
actual status on FTX is "Partially Filled & Cancelled".
Is this behavior is OK?

- OS: Debian (Docker)
- Programming Language version: JavaScript
- CCXT version: CCXT PRO: 0.9.35

Received order data: 
```
{"info":
{
	"id":"**************",
	"clientId":"**************",
	"market":"BTC/USD",
	"type":"market",
	"side":"buy",
	"price":null,
	"size":"0.988",
	"status":"closed",
	"filledSize":"0.9851",
	"remainingSize":"0.0",
	"reduceOnly":false,
	"liquidation":false,
	"avgFillPrice":"48064.121002943866",
	"postOnly":false,
	"ioc":true,
	"createdAt":"2021-12-21T04:00:25.397410+00:00",
	"future":null
},
"id":"**************",
"clientOrderId":"**************",
"timestamp":1640059225397,
"datetime":"2021-12-21T04:00:25.397Z",
"symbol":"BTC/USD",
"type":"market",
"postOnly":false,
"side":"buy",
"price":48064.121002943866,
"amount":0.988,
"cost":47347.9656,
"average":48064.121002943866,
"filled":0.9851,
"remaining":0.0029,
"status":"canceled",
"trades":[],
"fees":[]
}
```

**Comment by kroitor** [comment]
> We have received 'canceled' ccxt status in order response but in the 'info' parameters there is a 'closed' status and actual status on FTX is "Partially Filled & Cancelled". Is this behavior is OK?

Yes, that is by design. A partially-filled-then-canceled order will have status `canceled` and `amount = filled + remaining`. Remaining will be > 0. All of that is logical. Let us know if that does not answer your question.
