### ISSUE TITLE
How to determine if bittrex's specific wallet is offline or under maintainance

### ISSUE THREAD

**Issue by ironexmaiden** [ccxt/ccxt#1097]
Hello,
Is there a way to check if a wallet on bittrex is offline or under maintainance etc?

I used cctx.bittrex.load_markets() for ['FCT/BTC'] and returns "active":true even though the wallet is currently offline

**Comment by kroitor** [comment]
Hi!

```Python
import ccxt
import pprint
exchange = ccxt.bittrex ()
exchange.load_markets()
pprint(exchange.currencies['FCT'])
pprint(exchange.currencies['FCT']['active'])
```

**Comment by ironexmaiden** [comment]
Thank you ! But why ['FCT/BTC'] active returns true?

**Comment by kroitor** [comment]
@ironexmaiden because it is allowed to trade.

**Comment by ironexmaiden** [comment]
ok my fault! sorry for the inconvience

**Comment by kroitor** [comment]
no worries)

**Comment by ironexmaiden** [comment]
are you the main developer of ccxt?
