### ISSUE TITLE
Network Request Failed

### ISSUE THREAD

**Issue by chastel** [ccxt/ccxt#1098]
I just wanted to start using ccxt. I read the manual and wanted to test the provided code snippets.

When I try to get the list of markets, I get an issue. But the funny thing is that the request was successful. I don't get why this happens.

I used 'create-react-app' to start with this project and added the snippet - that was all.

- OS: macOS 10.12.6
- Programming Language: JavaScript
- CCXT version: 1.10.579
- Exchange: all
- Method: loadMarkets

```
(async () => {
    let kraken = new ccxt.kraken();
    let markets = await kraken.loadMarkets();
    console.log(kraken.id, markets);
}) ()
```
output:
```
Failed to load https://api.kraken.com/0/public/AssetPairs: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

Uncaught (in promise) TypeError: Network request failed
    at XMLHttpRequest.xhr.onerror (fetch-browser.js:452)
```

**Comment by kroitor** [comment]
Hi! 

This is documented here: https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin

I'd recommend to read the [Manual](https://github.com/ccxt/ccxt/wiki/Manual) first, and then check out the [examples](https://github.com/ccxt/ccxt/tree/master/examples)... Also search for CORS to find more answers on your issue in this repository. Closing this as a duplicate if you don't mind. Thx!

**Comment by chastel** [comment]
Oh, I didn't fully read the install section. Thank you for your quick response.
