### ISSUE TITLE
CEX.IO fees

### ISSUE THREAD

**Issue by evgen-y2k** [ccxt/ccxt#1099]
Method fetch_open_orders(symbol) not return fees in the "cost" field.
- OS: Linux
- Programming Language: Python 2.7
- CCXT version: 1.10.579
- Exchange: cex.io
- Method: fetch_open_orders(symbol)

Below example of returned order

```
cex.fetch_open_orders('XRP/USD')

{'status': 'open', 
'timestamp': 1515293900980, 
'price': 2.0, 
'datetime': '2018-01-07T02:58:20.980Z', 
'cost': 0.0, 
'id': u'5364304510', 
'remaining': 10.0, 
'info': {
  'status': 'open', 
  u'amount': u'10.000000', 
  u'time': u'1515293900980', 
  u'price': u'2', 
  u'type': u'buy', 
  u'id': u'5364304510',  
  u'pending': u'10.000000'
},
 'fee': None, 
'trades': None, 
'side': u'buy', 
'amount': 10.0, 
'type': None, 
'symbol': u'XRP/USD', 
'filled': 0.0}
```

**Comment by kroitor** [comment]
@evgen-y2k:
1. `cost` = order cost (filled * price)
2. order['fee']['cost'] = fee cost (undefined in the above case)
3. as you can see from the unparsed `info` (it contains the untouched reply from CEX) – they don't return any fee for a yet-unfilled order.

Hope this answers your issue. Let us know if you have any more questions with it.

**Comment by evgen-y2k** [comment]
Hello.
Yes, you right. No more questions.
Thank you for the replay.
