### ISSUE TITLE
Add Binance Vanilla Options

### ISSUE THREAD

**Issue by diwenshi61** [ccxt/ccxt#11008]
Documentation here:
https://binance-docs.github.io/apidocs/voptions/en/

Important to note:
For Websocket Streams:
-"Data is compressed as a GZIP file by default. After successful connection, send {"method":"BINARY", "params":["false"], "id":1} to convert to text data."
(https://binance-docs.github.io/apidocs/voptions/en/#push-websocket-account-info)

**Comment by kroitor** [comment]
@diwenshi61 hi! Please, elaborate a bit on your request, which specific functionality do you want us to add?

**Comment by diwenshi61** [comment]
Essentially it is just new exchange.

Add VAPI in Binance and associated unified methods:
```
            'api': {
                'vapi': {
                    'get': {
                        'ping': 1,
                        'time': 1,
                        'optionInfo': 1,
                        'exchangeInfo': 1, # fetch_markets
                        'index': 1,
                        'ticker': 1, # fetch_ticker
                        'mark': 1,
                        'depth': 1, # fetch_order_book
                        'klines': 1,
                        'trades': 1, # fetch_trades
                        'historicalTrades': 1,
                        'account': 1, # fetch_balance
                        'position': 1, # fetch_positions
                        'order': 1, # fetch_order
                        'openOrders': 1, # fetch_open_orders
                        'historyOrders': 1,
                        'userTrades': 1
                    },
                    'post': {
                        'transfer': 1,
                        'bill': 1,
                        'order': 1, # create_order
                        'batchOrders': 1
                    },
                    'delete': {
                        'order': 1, # cancel_order
                        'batchOrders': 1,
                        'allOpenOrders': 1 # cancel_all_orders
                    }
                }
            }
```
Websocket endpoints:
https://binance-docs.github.io/apidocs/voptions/en/#payload-account-data for watch_balance
https://binance-docs.github.io/apidocs/voptions/en/#payload-order-data for watch_orders
https://binance-docs.github.io/apidocs/voptions/en/#payload-candle for watch_ohlcv
https://binance-docs.github.io/apidocs/voptions/en/#payload-latest-completed-trades for watch_trades
https://binance-docs.github.io/apidocs/voptions/en/#payload-depth for watch_order_book

Note that this may not be 100% accurate summary of exchange API and features.

**Comment by kroitor** [comment]
@diwenshi61 got it, thanks for clarifying. Will get on to it.

**Comment by Alexmj18** [comment]
> Documentation here: https://binance-docs.github.io/apidocs/voptions/en/
> 
> Important to note: For Websocket Streams: -"Data is compressed as a GZIP file by default. After successful connection, send {"method":"BINARY", "params":["false"], "id":1} to convert to text data." (https://binance-docs.github.io/apidocs/voptions/en/#push-websocket-account-info)

**Comment by Alexmj18** [comment]
Get back to me soon

**Comment by carlosmiei** [comment]
> Just checking if there's any update on adding `option` as a `defaultType` so that we can use the ccxt unified API?

@amin-nejad Hello yes, if you add options to the `fetchMarkets` array you can even use most unified methods now
