### ISSUE TITLE
TypeError: safe_string() takes from 2 to 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by andrelcgt** [ccxt/ccxt#11007]
This line of code is calling a method sending 4 parameters when it should send only 2 or 3.

Error: TypeError: safe_string() takes from 2 to 3 positional arguments but 4 were given
This breaks Huobi

https://github.com/ccxt/ccxt/blob/c64cfdb0c364f4b965ef588bf67d1bdedad410a5/python/ccxt/base/exchange.py#L2721

**Comment by kroitor** [comment]
@andrelcgt thank you very much for reporting!

**Comment by kroitor** [comment]
The new fixed build 1.64.85 will arrive in ~20 minutes.
