### ISSUE TITLE
ccxt triangular arbitrage (using 1 exchange)

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#11029]
Anybody can lead me in the best direction for a triangular arbitrage sample script using ccxt preferably using one exchange and preferably kucoin.

I have a great script but is not using ccxt, uses binance direct, but I wana use ccxt for the orders, and so my code works for multiple exchanges.

thanks

**Comment by TrishamBP** [comment]
Did you find the solution for your problem, currently facing the same issue

**Comment by ttodua** [comment]
late reply here, but everything (examples) we have, are under [`/examples` ](https://github.com/ccxt/ccxt/tree/master/examples) directory
