### ISSUE TITLE
Huobi fetch_open_orders returns some None:s

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#11032]
- OS: Ubuntu
- Programming Language version: Python 3.6.9
- CCXT version: 1.65.26

Method fetch_open_orders returns None for example for 'filled' and 'remaining'. It looks like parse_order method is currently reading wrong dictionary values. There are suspicious lines (2602-2608 in huobi.py) where some variables are overwritten in the very next line. Those changes were made in version 1.65.24

```
        filled = self.safe_string_2(order, 'filled-amount', 'field-amount')  # typo in their API, filled amount
        filled = self.safe_string(order, 'trade_volume')
        price = self.safe_string(order, 'price')
        cost = self.safe_string_2(order, 'filled-cash-amount', 'field-cash-amount')  # same typo
        cost = self.safe_string(order, 'trade_turnover')
        feeCost = self.safe_string_2(order, 'filled-fees', 'field-fees')  # typo in their API, filled feeSide
        feeCost = self.safe_string(order, 'fee', feeCost)
```

Keys 'trade_volume', 'trade_turnover' or 'fee' do not, at least at this very moment, exist in the json returned by Huobi.

**Comment by kroitor** [comment]
@JovianMoon thanks for reporting, fixed in CCXT 1.65.27+, the new build will arrive in ~20 minutes.
