### ISSUE TITLE
Gate IO ccxt pro connection issue

### ISSUE THREAD

**Issue by pickmone** [ccxt/ccxt#11038]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows
- Programming Language version: Python
- CCXT version: Latest version (just updated)

Hi - I am recently trying to start trading on gateio, but I can't seem to get off the first step, no matter what call I make, either public or private, I get similar error thrown:

```
gate_exchange = ccxtpro.gateio()

markets = gate_exchange.load_markets()

```
exception thrown: gateio GET https://api.gateio.ws/api/v4/spot/currencies
Request: GET https://api.gateio.ws/api/v4/spot/currencies None None
raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host api.gateio.ws:443 ssl:default [[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)]
```

**Comment by kroitor** [comment]
@pickmone you should upgrade your version of SSL and aiohttp, as the error says. Let us know if that does not help. Feel free to reopen this issue or just ask further questions if any.
