### ISSUE TITLE
binance client.get_orderbook_tickers() vs 

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#11030]
#how come:
from binance.client import Client
import ccxt

#using binance api
prices = client.get_orderbook_tickers()
print(prices)

#is way faster than:
exchange = ccxt.binance({})
markets = exchange.load_markets()
print(markets)

orderbooks=[]
for symbols in markets:
        orderbooks.append(exchange.fetch_order_book(symbols))
        symbol=symbols.split('/')
        secondary=symbol[0]
        primary=symbol[1]
        print('.')

#???

**Comment by JavierPascual** [comment]
Moreover, using watch_order_book($symbol), binance is stopping the connection after 5 SUBSCRIBE messages, one per each symbol of the final loop (for symbols in markets:). @adamrg73 Have you test it in Python and CCXTPRO?

**Comment by ttodua** [comment]
@adamrg73  please use 'code' formatting button when posting code here. Formatting is broken as you just pasted it in plain. 
Lastly, there are multiple factors:
1) using native binance client, you are not limited by default (with rate-limited) and your code is exposed to get banned , because you are sending several hundred requests in one loop without pauses. (please get familiar with https://github.com/ccxt/ccxt/wiki/Manual#rate-limit ).

If you just want to get bid/ask, I advise to use 'fetchTickers' (or even fetchBidAsks for binance) which will take only 1 request

2) second, ccxt's `loadMarkets()` call is an obligatory for ccxt to handle it's internal planned functionalities correctly. However, that takes a second or two (or so, depending different factors). Only after that other `fetch` functions become possible to be called. However, your script should just load exchange once and have it open afterwards , during several minutes or hours as long as your logic implies.

**Comment by kroitor** [comment]
@adamrg73 you are comparing tickers from binance client to orderbooks from ccxt client. Proper code is: 

```Python
from binance.client import Client
import ccxt
exchange = ccxt.binance()
markets = exchange.load_markets()

start = exchange.milliseconds()
prices = client.get_orderbook_tickers()
print('Binance client:', exchange.milliseconds() - start, 'ms')
print(prices)

start = exchange.milliseconds()
prices = exchange.fetch_bids_asks()
print('CCXT client:', exchange.milliseconds() - start, 'ms')
print(prices)
```

**Comment by adamrg73** [comment]
> @adamrg73 please use 'code' formatting button when posting code here. Formatting is broken as you just pasted it in plain. Lastly, there are multiple factors:
> 
> 1. using native binance client, you are not limited by default (with rate-limited) and your code is exposed to get banned , because you are sending several hundred requests in one loop without pauses. (please get familiar with https://github.com/ccxt/ccxt/wiki/Manual#rate-limit ).
> 
> If you just want to get bid/ask, I advise to use 'fetchTickers' (or even fetchBidAsks for binance) which will take only 1 request
> 
> 2. second, ccxt's `loadMarkets()` call is an obligatory for ccxt to handle it's internal planned functionalities correctly. However, that takes a second or two (or so, depending different factors). Only after that other `fetch` functions become possible to be called. However, your script should just load exchange once and have it open afterwards , during several minutes or hours as long as your logic implies.

i tried to use code formatting but wasn't formatting correctly

**Comment by adamrg73** [comment]
> @adamrg73 you are comparing tickers from binance client to orderbooks from ccxt client. Proper code is:
> 
> ```python
> from binance.client import Client
> import ccxt
> exchange = ccxt.binance()
> markets = exchange.load_markets()
> 
> start = exchange.milliseconds()
> prices = client.get_orderbook_tickers()
> print('Binance client:', exchange.milliseconds() - start, 'ms')
> print(prices)
> 
> start = exchange.milliseconds()
> prices = exchange.fetch_bids_asks()
> print('CCXT client:', exchange.milliseconds() - start, 'ms')
> print(prices)
> ```

I want to use kucoin but was using binance as test until I moved my code to my vps IP for apikey to work. Can't make these calls on public like binance. Im going to try the code above, will work with kucoin?  What I want is ALL the bid/asks for every symbol on the 1 exchange, and very fast.  Thanks for all the replies! Much appreciated!

**Comment by adamrg73** [comment]
with kucoin exchange got this error:

Traceback (most recent call last):
  File "customArbitrage_test.py", line 23, in <module>
    prices = exchange.fetch_bids_asks()
  File "/Users/juliapagnotta/anaconda3/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1545, in fetch_bids_asks
    raise NotSupported('API does not allow to fetch all prices at once with a single call to fetch_bids_asks() for now')
ccxt.base.errors.NotSupported: API does not allow to fetch all prices at once with a single call to fetch_bids_asks() for now

**Comment by kroitor** [comment]
@adamrg73 kucoin does not have that method, but they have `fetch_tickers`. Please, read the Manual from top to bottom, it will save your time:

- https://docs.ccxt.com/en/latest/manual.html
- https://docs.ccxt.com/en/latest/manual.html#exchange-properties
- https://docs.ccxt.com/en/latest/manual.html#exchange-metadata

**Comment by adamrg73** [comment]
> @adamrg73 kucoin does not have that method, but they have `fetch_tickers`. Please, read the Manual from top to bottom, it will save your time:
> 
> * https://docs.ccxt.com/en/latest/manual.html
> * https://docs.ccxt.com/en/latest/manual.html#exchange-properties
> * https://docs.ccxt.com/en/latest/manual.html#exchange-metadata

looks like fetch_tickers will do the trick since I want all the latest bid and ask for each symbol on the exchange..
Anything else I should be aware considering my application here, I'm all ears.
thanks again!

**Comment by adamrg73** [comment]
says to only use fetch_tickers every minute depending in exchange, what do I do if I want all bid/asks every second, preferably right now on kucoin?
