### ISSUE TITLE
re-open: Gate IO ccxt pro connection issue

### ISSUE THREAD

**Issue by pickmone** [ccxt/ccxt#11039]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows
- Programming Language version: Python 3.10
- CCXT version: Latest
- 
Hi - just reopening the issue. my aiohttp is the latest version. But I am wondering if it is a compatibility issue with Python 3.10? I am recently trying to start trading on gateio, but I can't seem to get off the first step, no matter what call I make, either public or private, I get similar error thrown:

```
gate_exchange = ccxtpro.gateio()

markets = gate_exchange.load_markets()
```

```
exception thrown: gateio GET https://api.gateio.ws/api/v4/spot/currencies
Request: GET https://api.gateio.ws/api/v4/spot/currencies None None
raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host api.gateio.ws:443 ssl:default [[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)]
```

**Comment by kroitor** [comment]
@pickmone what is your version of urllib3 ?

**Comment by pickmone** [comment]
1.26.7

**Comment by kroitor** [comment]
@pickmone does it solve the issue if you downgrade it to 1.26.2 ?

**Comment by pickmone** [comment]
just tried. still same exception thrown :(

**Comment by kroitor** [comment]
@pickmone do you use any kind of proxies? Or do you have proxy settings on your environment variables?

**Comment by pickmone** [comment]
nope, I don't use any of that

**Comment by pickmone** [comment]
seems to be only gate io. all others I tried are fine (ftx, binance, okex, kucoin, bitfinex). I m quite stumped.

**Comment by pickmone** [comment]
found the issue. apparently an issue with my IP address.

thanks

**Comment by as-poldo** [comment]
> found the issue. apparently an issue with my IP address.
> 
> thanks

Hi pickmone,

I'm having the same problem only with gateio. can you tell me how you solved it? Thank you

**Comment by pickmone** [comment]
Hey - I had to use VPN. so now I just use VPN when accessing gate.

**Comment by Kinzowa** [comment]
I'm facing the same issue when listening to host fx-ws.gateio.ws on port 443 from my local machine : `unknown error (_ssl.c:1007)`

Python 3.10.12
urllib3==2.0.6
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

```
$ openssl s_client -connect fx-ws.gateio.ws:443 -servername fx-ws.gateio.ws
CONNECTED(00000003)
40B78B3E827F0000:error:0A0003E8:SSL routines:ssl3_read_bytes:reason(1000):../ssl/record/rec_layer_s3.c:1584:SSL alert number 0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 317 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---

```
