### ISSUE TITLE
gate io get perpetual positions

### ISSUE THREAD

**Issue by pickmone** [ccxt/ccxt#11048]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

```
Hello, how would I get all open perpetual positions. For other exchange it would be in the fetch_balance['info'] dictionary, but I do not see it here for Gate io. 


Thank you

**Comment by frosty00** [comment]
you can do `gateio.fetchPositions`

**Comment by pickmone** [comment]
I tried to use it with:

await gate.fetch_positions()

but get the error :gateio {"label":"NOT_FOUND"}

I am now using privateFuturesGetSettlePositions, but it's not as easy to use. Appreciate it if you could advise how to use the fetch_positions.

thank you

**Comment by frosty00** [comment]
@pickmone will investigate this bug

**Comment by tensorboy** [comment]
> I tried to use it with:
> 
> await gate.fetch_positions()
> 
> but get the error :gateio {"label":"NOT_FOUND"}
> 
> I am now using privateFuturesGetSettlePositions, but it's not as easy to use. Appreciate it if you could advise how to use the fetch_positions.
> 
> thank you

Same bug with @pickmone
