### ISSUE TITLE
Invalid Api-Key ID error for Binance

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#11045]
We often catch an error: `AuthenticationError: binance {"code":-2008,"msg":"Invalid Api-Key ID."}` on Binance and Binance Futures. 
It is noticed that it occurs more often after a Nodejs restart. Are there any problems with signature or timing?

The error occurs in all methods where API and Secret key are used, for example, `createOrder`, `fetchBalances.`

We can't find error with code `'-2008' ` in Binance docs and what it means.

From Binance there is no any answer.

APIs that we use are 100%  working. The same API can work in our staging server or locally, but in prod not.

- OS: Debian (Ubuntu)
- Programming Language version: JavaScript
- CCXT version: Pro 0.9.35

Related issue: https://github.com/ccxt/ccxt/issues/10620

**Comment by kroitor** [comment]
We had this issue a couple of years ago, when they returned `{"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}`. The actual meaning of that message is that Binance has banned this IP for a few minutes (usually, ten minutes to one hour). It could also be a permanent ban on the IP.
We had this workaround for that matter: https://github.com/ccxt/ccxt/blob/master/js/binance.js#L4888
I think, your issue may be of a similar nature.
Do you have these issues with the most recent versions of CCXT and CCXT Pro ?

**Comment by kroitor** [comment]
On more thing to note – do you switch the keys on the same instance on the fly? If that is the case, then i'd recommend making one exchange instance per keypair and sharing the loaded market info between them:

- https://github.com/ccxt/ccxt/blob/master/examples/js/shared-load-markets.js

**Comment by wunderb1t** [comment]
Yes, we use the same exchange instance for all requests and then just clean `apiKey`, `secret` and `headers` fields after each request, i.e. 

```
exchange.fetchBalance(),

exchange['apiKey'] = null;
exchange['secret'] = null;
exchange['headers'] = [];
```

We decided to use such method related to this issue https://github.com/ccxt/ccxt/issues/7552, when frequent ByBit instance recreation leads to memory leak.

**Comment by kroitor** [comment]
@wunderb1t i would suggest making one instance per keypair and sharing the loaded markets info among them, this way you won't have the extra memory load. If you shuffle your keys on the fly, then by the time it gets sent, the key may have changed already. Hope that helps. Let us know if not. Feel free to reopen this issue or just ask further questions if any.
