### ISSUE TITLE
create_limit_buy_order amount in USDT always

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#11057]
is there any way to always be able to just use USDT as the amount without converting the prices?
seems like its gona be a next hassle for me to convert prices when I want to use certain amount of USDT all the time.

exchange.create_limit_buy_order(coin1['symbol'], 1, coin1['ask'])

**Comment by kroitor** [comment]
@adamrg73 it is impossible for limit orders, although some exchanges support/require the amounts in quote currency for market buys, as documented here: https://github.com/ccxt/ccxt/wiki/Manual#market-buys
Hope that answers your question, let us know if not.

**Comment by adamrg73** [comment]
> https://github.com/ccxt/ccxt/wiki/Manual#market-buys

you got a line of code to fetch the price and convert to USDT?

**Comment by kroitor** [comment]
@adamrg73 here:

- https://github.com/ccxt/ccxt/blob/master/examples/py/fetch-balance-asset-valuation.py#L31
- https://docs.ccxt.com/en/latest/manual.html#price-tickers
