### ISSUE TITLE
ReferenceError: Can't find variable: BigInt

### ISSUE THREAD

**Issue by gz89** [ccxt/ccxt#11054]
- OS: Mac 10.15.5
- Programming Language version:
- CCXT version: 1.57.58

CCXT occurs error in Safari - Version 13.1.1 (15609.2.9.1.2).

https://github.com/ccxt/ccxt/blob/d90b971769e1afdd7c57d6ff8ee3f8154dbd4b5b/js/base/Precise.js#L3

```
ReferenceError: Can't find variable: BigInt
```

**Comment by kroitor** [comment]
@gz89 how do you link ccxt into the html page? you should use this: https://github.com/ccxt/ccxt/blob/master/dist/ccxt.browser.js

**Comment by gz89** [comment]
I am using it in React app and followed this installation step.
https://github.com/ccxt/ccxt/wiki/ccxt.pro.install#javascript-installation-from-a-cloned-source-code-repository

**Comment by kroitor** [comment]
@gz89 how do you webpack and browserify it in your react configs?

- https://github.com/ccxt/ccxt/search?q=react&type=issues
- https://github.com/ccxt/ccxt/issues?q=react+is%3Aissue+is%3Aopen+

**Comment by kroitor** [comment]
Please, feel free to reopen this issue or just ask further questions if any.
