### ISSUE TITLE
USD<->USDC conversions not supported by coinbasepro

### ISSUE THREAD

**Issue by Bomper** [ccxt/ccxt#11059]
- OS: Linux
- Programming Language version: Node 16.13.1
- CCXT version: 1.64.8

```
const markets = await coinbasepro.loadMarkets();
console.log(markets['USDC/USD'], markets['USD/USDC']);  // undefined undefined
await cbpro.fetchMyTrades('USD/USDC');  // coinbasepro does not have market symbol USD/USDC
await cbpro.fetchMyTrades('USDC/USD');  // coinbasepro does not have market symbol USDC/USD

```

Related: #4419

**Comment by ttodua** [comment]
Unfortunately, there is nothing much about it to do, as coinbase API docs states for "conversions", the only endpoint seems to be [`getConversion` by id](https://docs.cloud.coinbase.com/exchange/reference/exchangerestapi_getconversion). So, you can try like this:

```
const conversionResponse =await cbpro.privateGetConversionsConversionId ({'conversion_id': 'c5aaf125-d99e-41fe-82ea-ad068038b278' });
```
So, it seems user needs to store those ID's (which are returned 'conversion' action like https://github.com/ccxt/ccxt/issues/4419#issuecomment-450874161 ) and then fetch the information at any time back with those ID's.  (yeah, that sounds like a very poor endpoint design, so, as a customer, I'd suggest you send them support ticket/requests, to add the endpoint where you can obtain conversions in bulk (without need of individual 'id'). after that, we might be able to add that endpoint for functionality like `fetchMyTrades/fetchOrders/etc` ).

Feel free to reopen the topic if you have further issues with CCXT.
