### ISSUE TITLE
MEXC error 

### ISSUE THREAD

**Issue by Abdulhadi77** [ccxt/ccxt#11051]
Hi,
I have faced this error when I create a buy order
[<class 'decimal.ConversionSyntax'>]

import ccxt
import config
exchange = ccxt.mexc({
    "apiKey": config.MEXC_API_KEY,
    "secret": config.MEXC_SECRET_KEY
})
order = exchange.create_market_order(symbol='BUSD/USDT', side='buy', amount=5)    

This works well: balance = exchange.fetch_balance().get('free')['USDT']
Thanks

**Comment by kroitor** [comment]
@Abdulhadi77 mexc does not support market orders, only limit orders are supported:

- https://mxcdevelop.github.io/APIDoc/

<img width="1098" alt="Screenshot 2021-12-28 at 23 23 40" src="https://user-images.githubusercontent.com/1294454/147604422-26fceb0c-f3ec-4463-8b50-3e45b65a590d.png">




Hope that answers your question.

**Comment by Abdulhadi77** [comment]
What is the difference between all of the order types?
I need a function that buys without limit or determines the price

**Comment by kroitor** [comment]
@Abdulhadi77 that is covered in the Manual here: https://github.com/ccxt/ccxt/wiki/Manual#placing-orders
This exchange does not support calculating the price for you, most of the time the users have to fetch the price from the exchange or calculate their price prior to placing the order. IMMEDIATE_OR_CANCEL will not help in this case, it just means that your order must be either filled immediately at your requested price (which you must specify anyway) or it will be canceled.
