### ISSUE TITLE
Bugs in Exchange.php

### ISSUE THREAD

**Issue by ngdekhai** [ccxt/ccxt#11061]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version: php 7.4
- CCXT version: 1.65.41

in public function handle_market_type_and_params, I meet 2 problems.
1) $market_type = isset($market) ? market['type'] : $method_type;
- I not sure, but  market['type']  should have $ beside it? 

2) I using fetchOrder and createOrder function but it stuck at $method_type. Error Message:
PHP Notice:  Undefined variable: method_type in /vendor/ccxt/ccxt/php/Exchange.php on line 3494
huobipro cancelOrder() requires a $symbol for  orders

$method_type and $method_options are both empty value because fetchOrder and createOrder does not exists in $this->options.

how to fix this?

**Comment by kroitor** [comment]
> 1. $market_type = isset($market) ? market['type'] : $method_type;

Pushed a fix for it just now, it will arrive in ~20 minutes.

Will fix the second issue shortly.

Thanks for reporting!

**Comment by ngdekhai** [comment]
thanks, can you tell me when you fix the 2nd issue?

**Comment by kroitor** [comment]
@ngdekhai it should be fixed in CCXT 1.65.56+

**Comment by ngdekhai** [comment]
Hi, sorry 2 bugs again....

Exchange.php
1) createSpotOrder method not found, try underscore_notation instead of camelCase for the method being called

I think this is missed:
'createSpotOrder' => 'create_spot_order',

2) huobipro cancelOrder() does not support  markets
this happen when I use fetchOrder, because of $method_options in  handle_market_type_and_params function. $method_options is empty again. If I change "spot" as default type then it is fine, can you check is it okay?

I changed
$this->safe_value($this->options, $method_name, array());
to
$this->safe_value($this->options, $method_name, 'spot');

**Comment by kroitor** [comment]
@ngdekhai 

> createSpotOrder method not found, try underscore_notation instead of camelCase for the method being called

yes, will fix that as well.

> huobipro cancelOrder() does not support markets
> this happen when I use fetchOrder, because of $method_options in handle_market_type_and_params function.
> $method_options is empty again. If I change "spot" as default type then it is fine, can you check is it okay?

Which defaultType causes the problem? huobi's futures are currently a work in progress.

**Comment by ngdekhai** [comment]
> Which defaultType causes the problem? huobi's futures are currently a work in progress.

I am using spot trading, not future. but since you put $default_value as empty array in 
$method_options = $this->safe_value($this->options, $method_name, array());

, it will return empty value to $method_options. And this will make fetchOrder for huobi spot trade to have error; it will throw
throw new NotSupported($this->id . ' cancelOrder() does not support ' . $methodType . ' markets');

because $methodType = $method_options, so $methodType is empty as well

**Comment by kroitor** [comment]
@ngdekhai let me know if you still have issues with version 1.65.57+. Thanks for reporting!
