### ISSUE TITLE
Kucoin fetchOHLCV results into 'TypeError: Cannot convert undefined or null to object'

### ISSUE THREAD

**Issue by miriti** [ccxt/ccxt#1106]
Trying to get the OHLCV data from Kucoin results to 

```
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at kucoin.parseOHLCVs (/home/michael/nodebot/node_modules/ccxt/js/base/Exchange.js:777:25)
    at kucoin.fetchOHLCV (/home/michael/nodebot/node_modules/ccxt/js/kucoin.js:505:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

- OS: Arch Linux
- Programming Language: JavaScript
- CCXT version: 1.10.579
- Exchange: Kucoin
- Method: fetchOHLCV

```
const ccxt = require('ccxt');

const kucoin = new ccxt.kucoin({ 'verbose': true });

async function main() {
  try{
    let ohlcv = await kucoin.fetchOHLCV('KCS/BTC', '5m');
    console.log(ohlcv);
  } catch(error) {
    console.log(error);
  }
}

main();
```
Raw programm output is here https://pastebin.com/raw/88PAPYDq (I hope linking pastebin is apropriate because the output is too long to past it into the message)

**Comment by kroitor** [comment]
Hi! Unfortunately, Kucoin does not have a working OHLCV endpoints, even though it's documented, we've been trying it in various ways and it does not work. They only offer TradeView format, which is not supported in ccxt yet (your contributions are welcome). More about it here: https://github.com/ccxt/ccxt/issues/602#issuecomment-351777727.

**Comment by miriti** [comment]
Oh I see. kucoin.hasFetchOHLCV is actually set to `false`. I should have checked this first...

I'll look into this TradingView format issue and PR you if I'll have any success :)

**Comment by kroitor** [comment]
> I'll look into this TradingView format issue and PR you if I'll have any success :)

That would be awesome! Make sure to read this: 
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

Thank you!

**Comment by kroitor** [comment]
@miriti would you mind if I close this for now, as this is somewhat duplicate to that issue?

**Comment by miriti** [comment]
Sure! It was me too fast to create an issues :)
