### ISSUE TITLE
Feature Request: Staking Support

### ISSUE THREAD

**Issue by JohnSmithyy** [ccxt/ccxt#11069]
Hello CCXT Team,

Just wanted to know if there are any plans to support staking through the CCXT API. It would be awesome if there was a unified way to stake funds on an exchange.

Thank you!

**Comment by kroitor** [comment]
Hi! CCXT already allows staking with the implicit APIs: https://docs.ccxt.com/en/latest/manual.html#implicit-api
However, the aspect of staking is not unified yet, we will get cracking it as soon as we can.

**Comment by JohnSmithyy** [comment]
I was having a look at the link you posted. I could not find the staking api endpoints for kraken when I tried:

`print(dir(ccxt.kraken()))`

Kraken: https://docs.kraken.com/rest/#tag/User-Staking

**Comment by kroitor** [comment]
@JohnSmithyy will the missing staking endpoints to kraken shortly, thx for pointing it out!

**Comment by JohnSmithyy** [comment]
@kroitor Awesome, please keep me posted which release version will contain the staking endpoints for kraken :)

**Comment by JohnSmithyy** [comment]
> @JohnSmithyy will add the missing staking endpoints to kraken shortly, thx for pointing it out!

Just wanted to check in on this update :)

**Comment by kroitor** [comment]
@JohnSmithyy added Kraken's staking endpoints in CCXT 1.66.32+, the new build will arrive in 20 minutes. Thanks for your feedback!

**Comment by CloudTrauma** [comment]
I cant find the function to stake for kraken. Where do I find this?

**Comment by kroitor** [comment]
@CloudTrauma you can find it in the Manual: 

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://docs.ccxt.com/en/latest/manual.html#implicit-api

```Python
```
