### ISSUE TITLE
kucoin order response

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#11074]
filled says None, but it did fill.. ??

side='buy'
amount=0.0027472
price=3636.44
params = {
                    #'timeInForce': 'FillOrKill',
                    'timeInForce': 'FOK',
                    }

r1=exchange.create_order(symbol, 'limit', side, amount, price, params)
print(r1)

{'id': '61cd183ce5edc9000136e759', 'clientOrderId': '55a7a667-d945-4299-856a-18fcb5829d8d', 'info': {'orderId': '61cd183ce5edc9000136e759'}, 'timestamp': 1640831036506, 'datetime': '2021-12-30T02:23:56.506Z', 'lastTradeTimestamp': None, 'symbol': 'ETH/USDT', 'type': 'limit', 'side': 'buy', 'price': 3636.44, 'amount': 0.0027472, 'cost': None, 'average': None, 'filled': None, 'remaining': None, 'status': None, 'fee': None, 'trades': None}

**Comment by kroitor** [comment]
@adamrg73 most of the exchanges will only return the order id from `create_order`. When you place an order, even a FOK order, the order is not matched instantly, it is matched quickly, but not immediately. You want to `fetch_order` afterwards to find the status of the order by order['id'], whether it was filled or not. This is documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders
- https://docs.ccxt.com/en/latest/manual.html#order-structure

I would highly recommend reading the entire Manual from top to bottom at least once – it will really save your time.
