### ISSUE TITLE
add handleMarketTagAndParams everywhere

### ISSUE THREAD

**Issue by frosty00** [ccxt/ccxt#11078]
https://github.com/ccxt/ccxt/blob/28d37308fa1969f5511f20b2f3c352b8cfde1e24/js/base/Exchange.js#L2011

see how it is used here:

https://github.com/ccxt/ccxt/blob/28d37308fa1969f5511f20b2f3c352b8cfde1e24/js/ascendex.js#L1136

**Comment by kroitor** [comment]
Let's use this:
```JavaScript
const [ marketType, query ] = this.handleMarketTypeAndParams ('createOrder', market, params); 
```

**Comment by kroitor** [comment]
@frosty00 what is the correct title of this issue?

**Comment by frosty00** [comment]
> @frosty00 what is the correct title of this issue? Is it about `handleTagAndParams` or about `handleMarketTypeAndParams` ?

yep have update it

**Comment by ttodua** [comment]
@frosty00  May I ask - from now, we will do them that way. But should we also change in existing implementations too? I wanted to know, if one person is assigned to do for 'existing' exchanges or all of us should do here or there (to avoid multiple persons working on same thing).

**Comment by kroitor** [comment]
@ttodua most often, if you're working with this or that exchange that involves multiple market types loaded separately and configured with defaultType, and the exchange does not have handleMarketTypeAndParams, then you edit the exchange accordingly if you have the time and a chance to fix it. So, it's "fix on first encounter".

> I wanted to know, if one person is assigned to do for 'existing' exchanges or all of us should do here or there (to avoid multiple persons working on same thing).

I think this information is for all devs involved in the development of the lib.

**Comment by ttodua** [comment]
@frosty00 is the title of this issue correct? shouldnt it be `handleMarketType**andParams` instead of `Tag**`

**Comment by ttodua** [comment]
This issue is no longer actual, so we can mark it as outdated/closed.
