### ISSUE TITLE
List of "Trading Fees " or "Deposit/Withdrawal" Fees of each exchange 

### ISSUE THREAD

**Issue by sunset1234321** [ccxt/ccxt#11075]
Are those fees provided in this package?

**Comment by kroitor** [comment]
> Are those fees provided in this package?

Yes.

Please, check the exchange.currencies after loading the market infos. Some exchanges also have fetchTradingFees and fetchFundingFees. We highly recommend reading the entire Manual and checking the examples:

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://docs.ccxt.com/en/latest/
- https://github.com/ccxt/ccxt/tree/master/examples
- https://github.com/ccxt/ccxt/tree/master/examples#see-also
