### ISSUE TITLE
add safeTicker everywhere

### ISSUE THREAD

**Issue by frosty00** [ccxt/ccxt#11079]
https://github.com/ccxt/ccxt/blob/28d37308fa1969f5511f20b2f3c352b8cfde1e24/js/base/Exchange.js#L1214

see how it is used here:

https://github.com/ccxt/ccxt/blob/28d37308fa1969f5511f20b2f3c352b8cfde1e24/js/binance.js#L1775

eventually we will move to safeTicker2 (that will parse strings), however it will be much faster and easier to migrate if we already have support for a floating point safeTicker implementation

**Comment by kroitor** [comment]
> eventually we will move to safeTicker2

In this case, I think we can solve it with a `legacy = true` argument without introducing safeTicker2.

**Comment by frosty00** [comment]
i think probably the easiest way to do it is to have safeTicker2 and safeTicker just like we did with safeOrder

**Comment by ttodua** [comment]
I think there should be a naming consistency :
safeOrder <> safeOrder2
safeTicker <> safeTicker2

however, when you say that eventually we will move to 'safeTicker2', in contrary of this, a few days ago, the `safeOrder2` was eliminated and removed the `2` suffix. I think the same concept should be case with all other `safeX` funcs, to avoid use of `safeX` functions on several places, and `safeY2` functions over other places.

**Comment by kroitor** [comment]
In case of safeTicker we can avoid safeTicker2 entirely, and in general we can avoid safeXXX2 entirely.

**Comment by kroitor** [comment]
The goal is to make every fetchXXX-method have a matching unified (one and only) parseXXX method. No safeXXX2, no safeXXX3, etc.

**Comment by frosty00** [comment]
> In case of safeTicker we can avoid safeTicker2 entirely, and in general we can avoid safeXXX2 entirely. I think that would be the best way of doing it.

it's not so simple, safeTicker in it's currently form only accepts floats. so the point is to keep that and implement it everywhere and then later transition to safeTicker2 that accepts strings and once we are done with that we can delete the function safeTicker1. I think this way is the cleanest way with the least bugs.

> No safeXXX2, no safeXXX3, etc – that is poor naming.

it's just a temporary function like how safeOrder2 was temporary.

**Comment by frosty00** [comment]
> I think there should be a naming consistency : safeOrder <> safeOrder2 safeTicker <> safeTicker2
> 
> however, when you say that eventually we will move to 'safeTicker2', in contrary of this, a few days ago, the `safeOrder2` was eliminated and removed the `2` suffix. I think the same concept should be case with all other `safeX` funcs, to avoid use of `safeX` functions on several places, and `safeY2` functions over other places.

safeOrder2 and safeOrder did different things tho. safeOrder1 and 2 were both written by me and safeOrder2 was just the second iteration with more advanced features

**Comment by frosty00** [comment]
in order words we should initially use the existing `safeTicker` then I will write a pure string math function called `safeTicker2` and will port all the code over

**Comment by kroitor** [comment]
@frosty00 I would suggest to refrain from naming like safeXXX2 even for temporary functions. Cause that kind of naming makes the code harder to understand for other devs. I would go with a _"legacy"_ flag that would pretty much do the same job as safeTicker2 would, but without safeTicker2.

**Comment by frosty00** [comment]
we can use a legacy flag also, the effect is the same
