### ISSUE TITLE
Full list of working APIs

### ISSUE THREAD

**Issue by SAMOKILLER** [ccxt/ccxt#1108]
Could you create a list of fully working APIs to understand which exchanges are already fully supported, and which ones are still in the process of work?

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/blob/master/examples/js/exchange-capabilities.js

<img width="1634" alt="screen shot 2018-01-07 at 18 29 28" src="https://user-images.githubusercontent.com/1294454/34650857-c316061a-f3d8-11e7-98e5-7682ef79c3d9.png">

More about it here: https://github.com/ccxt/ccxt/issues/71
