### ISSUE TITLE
Issue getting current positions from FTX.com

### ISSUE THREAD

**Issue by birk151** [ccxt/ccxt#11096]
- OS: Windows 10
- Programming Language version: 3.10.1
- CCXT version: 1.65.92

```
def get_positions():
    open_positions = {}
    all_positions = ftx.fetchPositions(None, {"showAvgPrice": True})
    for x in all_positions:
        future = (x["future"])
        size = (x["size"])
        side = (x["side"])
        cost = (x["cost"])
        recentAverageOpenPrice = (x["recentAverageOpenPrice"])
        if size != '0.0':
            open_positions[future] = size, side, cost, recentAverageOpenPrice
    return open_positions```

```
Traceback (most recent call last):
  File "C:\Users\christopherburk\Desktop\Py3c_triggers.py", line 348, in <module>
    all_open_positions = get_positions()
  File "C:\Users\christopherburk\Desktop\Py3c_triggers.py", line 207, in get_positions
    future = (x["future"])
KeyError: 'future'

```

**Comment by kroitor** [comment]
@birk151 you have an error in your code: a position does not have ` future` property. 

See the position structure definition here: https://github.com/ccxt/ccxt/wiki/Manual#position-structure

We highly recommend reading the entire Manual from top to bottom.

What you really want is to get a symbol from that position, and then get the market from that symbol to find if it's a future market or a different kind.

```Python
    all_positions = ftx.fetchPositions(None, {"showAvgPrice": True})
    for x in all_positions:
        symbol = x['symbol']
        # market = ftx.market(symbol)  # use the market structure if necessary
        size = (x["size"])
        side = (x["side"])
        cost = (x["cost"])
        recentAverageOpenPrice = (x["recentAverageOpenPrice"])
        if size != '0.0':
            open_positions[symbol] = size, side, cost, recentAverageOpenPrice
    return open_positions
```

**Comment by birk151** [comment]
Traceback (most recent call last):
  File "C:\Users\christopherburk\Desktop\Py3c_triggers.py", line 349, in <module>
    all_open_positions = get_positions()
  File "C:\Users\christopherburk\Desktop\Py3c_triggers.py", line 209, in get_positions
    size = (x["size"])
KeyError: 'size'

**Comment by kroitor** [comment]
@birk151 there's no such thing as 'size' either – please, fix your code according to the description of the position structure: https://github.com/ccxt/ccxt/wiki/Manual#position-structure

If you want to use the FTX-specific raw non-unified structure of positions, do this:

```Python
    all_positions = ftx.fetchPositions(None, {"showAvgPrice": True})
    for x in all_positions:
        info = x['info']
        future = info['future']
        size = (info["size"])
        side = (info["side"])
        cost = (info["cost"])
        recentAverageOpenPrice = (info["recentAverageOpenPrice"])
        if size != '0.0':
            open_positions[future] = size, side, cost, recentAverageOpenPrice
    return open_positions
```

This is not a recommended usage, though, we recommend reading the Manual and using the unified API.
