### ISSUE TITLE
no matter whether it has been traded or not, it always displays "status: open". 

### ISSUE THREAD

**Issue by qwe231cvb** [ccxt/ccxt#11104]
When I place an order, no matter whether it has been traded or not, it always displays "status: open". How can I tell whether the trade has been completed?
The code as follows:

    eth_price = ftx.fetch_ticker("ETH/USDT")['bid']
    create_order = ftx.create_order('ETH/USDT', 'limit', 'buy', 0.006, eth_price)
    print("status:", create_order['status'])

**Comment by kroitor** [comment]
@qwe231cvb create_order is used for placing orders, and if you want to fetch the order status after it was placed, use `fetch_order` as documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#querying-orders
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/

```Python
symbol = 'ETH/USDT'
ticker = ftx.fetch_ticker(symbol)
price = ['bid']
order = ftx.create_order(symbol, 'limit', 'buy', 0.006, price)
print("status:", order['status'])
order = ftx.fetch_order(order['id'], order['symbol'])
print("status:", order['status'])
```

Your `limit` order has to be actually filled to show a status other than `open`.
If you want it to be filled immediately, then use `market` orders.
