### ISSUE TITLE
dust conversion on binance?

### ISSUE THREAD

**Issue by gnedoy** [ccxt/ccxt#11117]
hi @kroitor 
How to convert dust (small balance) to bnb on binance with ccxt?

**Comment by sc0Vu** [comment]
Hi @gnedoy,

There is api for this, here I use javascript as an example:

```JS
// create ccxt exchange instance
const client = new ccxt.binance({
  apiKey,
  secret,
})

// you can also call client.sapiPostAssetDust
let res = await client.sapi_post_asset_dust({
  asset: [ 'DAI' ] // assets you want to convert, remember to use uppercase
})
```

You can also find examples with php/python in manual: https://github.com/ccxt/ccxt/wiki/Manual.

**Comment by macanudo527** [comment]
hi @kroitor,
Is there going to be a 'has' tag for dusting? That way we can check if a particular exchange has the ability to dust or not. It would also be useful to have a tag for 'fetchMyDust' or something similar. I could make a PR for it.

**Comment by engrhasanrizvi** [comment]
> Hi @gnedoy,
> 
> There is api for this, here I use javascript as an example:
> 
> ```js
> // create ccxt exchange instance
> const client = new ccxt.binance({
>   apiKey,
>   secret,
> })
> 
> // you can also call client.sapiPostAssetDust
> let res = await client.sapi_post_asset_dust({
>   asset: [ 'DAI' ] // assets you want to convert, remember to use uppercase
> })
> ```
> 
> You can also find examples with php/python in manual: https://github.com/ccxt/ccxt/wiki/Manual.

I am trying to find out how to implement binance convert using ccxt, I see there is sapi post convert getQuote and acceptQuote but I am not sure how to use it. Can you please help.
