### ISSUE TITLE
Can .parse8601 assume 00:00:00 if only a date is specified?

### ISSUE THREAD

**Issue by Bomper** [ccxt/ccxt#11118]
I was following the [Binance deposits example](https://github.com/ccxt/ccxt/issues/7388) and noticed that `startTime` was initialized with this date, `exchange.parse8601 ('2018-01-01T00:00:00')`.

I wanted to omit the `00:00:00` timestamp because `new Date()` also works with only the date, but `exchange.parse8601 ('2018-01-01')` silently returns `undefined`.

Would it help if `exchange.parse8601 ('2018-01-01')` returns the same timestamp as `exchange.parse8601 ('2018-01-01T00:00:00')`?

**Comment by kroitor** [comment]
Inside the response parsing code in the lib we can solve the above with string-concatenation, like `exchange.parse8601 ('2018-01-01' + 'T' + '00:00:00Z')`. Or did i misunderstand the question?

**Comment by kroitor** [comment]
Feel free to reopen it if necessary.
