### ISSUE TITLE
Bybit cannot cancel or fetch conditional orders using order_link_id

### ISSUE THREAD

**Issue by furryboffin** [ccxt/ccxt#11113]
https://github.com/ccxt/ccxt/blob/37784b26c907b7aa821b43d2912b508385fd0ef4/js/bybit.js#L1764

The logic in cancelOrder (and fetchOrder) prevents one from cancelling (and fetching) conditional orders using only the order_link_id. One should set the method correctly when using only order_link_id. Currently the method is set to standard endpoint, which does not work for conditional orders.

**Comment by furryboffin** [comment]
I changed the code to the following and it seems to work.
```
        if (stopOrderId === undefined) {
            const orderLinkId = this.safeString (params, 'order_link_id');
            if (orderLinkId === undefined) {
                request['order_id'] = id;
            }
        }
        if (!('order_id' in request)) {
            if (market['swap']) {
                if (market['linear']) {
                    method = 'privateLinearPostStopOrderCancel';
                } else if (market['inverse']) {
                    method = 'v2PrivatePostStopOrderCancel';
                }
            } else if (market['futures']) {
                method = 'futuresPrivatePostStopOrderCancel';
            }
        }

```

**Comment by furryboffin** [comment]
note the same bug exists in fetchOrder

also note that I'm checking this inside bybit.js

**Comment by kroitor** [comment]
I am currently reworking the Bybit integration, the update will solve for the above, thank you!

**Comment by furryboffin** [comment]
Note also that editOrder would also need changing to allow editing of conditional orders.

**Comment by kroitor** [comment]
@furryboffin sure, will do! In the meantime, you can still cancel the conditional orders with order_link_id using the implicit API, as shown here:

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/bybit.py#L1678

```Python
        market = exchange.market(symbol)
        request = {
            'symbol': market['id'],
            'order_link_id': 'YOUR_ORDER_LINK_ID_HERE',
        }
        if market['swap']:
            if market['linear']:
                method = 'privateLinearPostStopOrderCancel'
            elif market['inverse']:
                method = 'v2PrivatePostStopOrderCancel'
        elif market['futures']:
            method = 'futuresPrivatePostStopOrderCancel'
        response = getattr(exchange, method)(exchange.extend(request, params))
        result = exchange.safe_value(response, 'result', {})
        return exchange.parse_order(result, market)
```

**Comment by furryboffin** [comment]
I’m not sure i understand. This is python, im using js. And this code appears to contain the same problem.

**Comment by kroitor** [comment]
> This is python, im using js.

It's the same code in JS:

- https://github.com/ccxt/ccxt/blob/master/js/bybit.js#L1739

```JavaScript
        await exchange.loadMarkets ();
        // exchange.verbose = true // uncomment for debugging purposes if necessary
        const market = exchange.market (symbol);
        const request = {
            'symbol': market['id'],
            'order_link_id': 'YOUR_ORDER_LINK_ID_HERE',
        };
        let method = undefined;
        if (market['swap']) {
            if (market['linear']) {
                method = 'privateLinearPostStopOrderCancel';
            } else if (market['inverse']) {
                method = 'v2PrivatePostStopOrderCancel';
            }
        } else if (market['futures']) {
            method = 'futuresPrivatePostStopOrderCancel';
        }
        const response = await exchange[method] (exchange.extend (request, params));
        const result = exchange.safeValue (response, 'result', {});
        const order = exchange.parseOrder (result, market);
```

> And this code appears to contain the same problem.

Have you tried? If you have, and it doesn't work, please, paste your verbose output (enable verbose mode)

**Comment by furryboffin** [comment]
no this does not work, did you look at my temporary hack solution?

the problem is in this code 
```
        if (stopOrderId === undefined) {
            const orderLinkId = this.safeString (params, 'order_link_id');
            if (orderLinkId === undefined) {
                request['order_id'] = id;
            }
        } else {
            if (market['swap']) {
                if (market['linear']) {
                    method = 'privateLinearPostStopOrderCancel';
                } else if (market['inverse']) {
                    method = 'v2PrivatePostStopOrderCancel';
                }
            } else if (market['futures']) {
                method = 'futuresPrivatePostStopOrderCancel';
            }
        }
```

whereas my fix looks like this:
```
        if (stopOrderId === undefined) {
            const orderLinkId = this.safeString (params, 'order_link_id');
            if (orderLinkId === undefined) {
                request['order_id'] = id;
            }
        }
        if (!('order_id' in request)) {
            if (market['swap']) {
                if (market['linear']) {
                    method = 'privateLinearPostStopOrderCancel';
                } else if (market['inverse']) {
                    method = 'v2PrivatePostStopOrderCancel';
                }
            } else if (market['futures']) {
                method = 'futuresPrivatePostStopOrderCancel';
            }
        }
```

The problem with the original code is that if you set only the `order_link_id`, the resulting method is not updated to use the `Stop` version.

**Comment by furryboffin** [comment]
while you're looking at this I refer you to another issue I just posted: https://github.com/ccxt/ccxt/issues/11159

**Comment by kroitor** [comment]
@furryboffin i mean, have you tried my code instead of cancelOrder ? That code does not have a mention of stopOrderId at all, it just cancels a stop order by order_link_id. https://github.com/ccxt/ccxt/issues/11113#issuecomment-1007260971

**Comment by furryboffin** [comment]
Stop orders have a different end point in the api. If you try to post a cancel using the link id to the normal end point it does not cancel stop orders.

**Comment by kroitor** [comment]
@furryboffin if you look carefully at my code above, it uses a stop-order-specific endpoint to cancel a stop order.

**Comment by furryboffin** [comment]
i see. sorry I didn't understand what you were referring to.  I'm just trying to get the bug fixed :-)

**Comment by kroitor** [comment]
@furryboffin you will get it fixed, if you replace your call to cancelOrder with the code i've posted above – that will work for canceling stop orders on your side, in your code.

**Comment by furryboffin** [comment]
I looked again at the link you sent. I am still a bit lost. I don't know which method you are referring to.

**Comment by furryboffin** [comment]
I think I don't know what "using the implicit API" means.

**Comment by kroitor** [comment]
@furryboffin i mean, you don't even have to edit the source code of the library to make it work. You just replace `cancelOrder` in your code with the snippet above.

> I think I don't know what "using the implicit API" means.

It is documented in the Manual here:

- https://docs.ccxt.com/en/latest/manual.html#implicit-api
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

**Comment by furryboffin** [comment]
if I look at the code for cancelOrder() in https://github.com/ccxt/ccxt/blob/master/js/bybit.js#L1739

I cannot see why you think this will work.

**Comment by kroitor** [comment]
> if I look at the code for cancelOrder() in https://github.com/ccxt/ccxt/blob/master/js/bybit.js#L1739

That was just a link for reference, cause you said you use JS, but you don't even have to look there at all.

> I cannot see why you think this will work.

Cause i've tried it and it works.

If you can paste a snippet of **your client-code** that you use to cancel orders (not a snippet of code from the library), it would look something like this:

```JavaScript
const canceledOrder = await exchange.cancelOrder (...);
```

I suggest that you replace the above line **IN YOUR CODE** with this (without touching the lib itself):

```JavaScript
        await exchange.loadMarkets ();
        // exchange.verbose = true // uncomment for debugging purposes if necessary
        const market = exchange.market (symbol);
        const request = {
            'symbol': market['id'],
            'order_link_id': 'YOUR_ORDER_LINK_ID_HERE',
        };
        let method = undefined;
        if (market['swap']) {
            if (market['linear']) {
                method = 'privateLinearPostStopOrderCancel';
            } else if (market['inverse']) {
                method = 'v2PrivatePostStopOrderCancel';
            }
        } else if (market['futures']) {
            method = 'futuresPrivatePostStopOrderCancel';
        }
        const response = await exchange[method] (exchange.extend (request, params));
        const result = exchange.safeValue (response, 'result', {});
        const canceledOrder = exchange.parseOrder (result, market);
```

**Comment by kroitor** [comment]
@furryboffin i mean, you're trying to edit the source code of the library to fix it, but you don't have to.

**Comment by kroitor** [comment]
P.S. we will get that added to the master version of Bybit, when the ongoing rewrite of the bybit integration is complete (this month).

**Comment by furryboffin** [comment]
thanks for all your time Sorry I had to pick up my daughter from school and then it was dinner time then bedtime etc... I think I follow you now. I'm happy to just use my hack and wait for the new version to come out... :-)

**Comment by furryboffin** [comment]
of course I understand that I could just write code to do what ccxt does, as you suggest... but that sort of defeats the object of using ccxt. :-)

**Comment by furryboffin** [comment]
I also noticed that there are a couple more places where you cannot provide clientOrderId in params. You are obliged to pass order_link_id. It would be nice if we could also just provide clientOrderId in these cases.

**Comment by kroitor** [comment]
@furryboffin will do!

**Comment by furryboffin** [comment]
let me know if I can be of any help.. happy to lend a hand.

**Comment by furryboffin** [comment]
do you have a branch on github you're working on?

**Comment by furryboffin** [comment]
Hi. How are things going? I just pulled the latest version after the small bug fix for the fees in limit orders that I found. I noticed that the bug reported in this issue is still there.

**Comment by kroitor** [comment]
@furryboffin do you mean this bug: https://github.com/ccxt/ccxt/issues/11813 ?

**Comment by furryboffin** [comment]
> @furryboffin do you mean this bug: #11813 ?

This bug is now fixed in the latest version. What I mean is that the issue reported in this thread. i.e. the business of not using the right endpoint for conditional orders, is still in the code. I pulled the latest version and reapplied my hack. So I'm ok for the time being. Thanks for your response.

**Comment by furryboffin** [comment]
did anyone take a moment to look at applying a fix for this?

**Comment by fconsani** [comment]
I'm having trouble fetching conditional orders (tp and sl) is the problem still ongoing ?

**Comment by emorling** [comment]
> ```js
> cancelStopOrder
> ```

Has this been added? I looked at cancelOrder for ByBit, and it still doesn't accept order_by_link?

**Comment by danieltorscho** [comment]
I still have an issue to successfully cancel the order, I've tried multiple combinations.

Bybit:
```
let cancelOrder = null
try {
  if (config.EXCHANGE_ID === 'bybit') {
    cancelOrder = await exchange.cancelOrder(Number(orderPending.id), orderPending.info.symbol, {
      'order_link_id': Number(orderPending.info.orderLinkId)
    })
  } else {
    cancelOrder = await exchange.cancelOrder(null, orderPending.info.symbol, {
      'origClientOrderId': Number(orderPending.clientOrderId)
    })
  }
} catch (error) {
  console.log(`🐞 Order cancelation failed: ${error.message}`)
}
```

Error:
```
Exception has occurred: InvalidOrder: bybit {"ret_code":-2013,"ret_msg":"Order does not exist.","result":{},"ext_code":"","ext_info":null,"time_now":"1664970797.122968"}
```

Do anyone know how to fix it ?

**Comment by danieltorscho** [comment]
> > ```js
> > cancelStopOrder
> > ```
> 
> Has this been added? I looked at cancelOrder for ByBit, and it still doesn't accept order_by_link?

I came up with this solution, I had to replace `order_link_id` with `orderLinkId`:

```
cancelOrder = await exchange.cancelOrder(orderPending.id, orderPending.info.symbol, {
  'orderLinkId': orderPending.info.orderLinkId
})
```

**Comment by ttodua** [comment]
after [this PR](https://github.com/ccxt/ccxt/pull/15402) is merged, you will be able to retriever conditional SL/TP orders with adding `orderCategory:1` in `params` (however, it will work only for TP/SL, and not typical conditional order)

**Comment by Tvax** [comment]
It now works for me on `reduceOnly` orders by adding `'orderType': 'conditional'` to params like so:

```
bybit.fetch_order(order['id'], symbol, {'orderType': 'conditional'})
bybit.cancel_order(order['id'], symbol, {'orderType': 'conditional'})
```

**Comment by Dan-krm** [comment]
Closing this issue because bybit has been updated to v5 with some different functionality explained below:

You can use the exchange specific params `orderLinkId` and `orderFilter` you can also use the unified CCXT boolean flag `stop` for specifying conditional orders.

```python
bybit.fetch_order(order['id'], symbol, {'orderLinkId': orderLinkId,'stop':true})
bybit.cancel_order(order['id'], symbol, {'orderLinkId': orderLinkId,'stop':true})
```
Here are the endpoints used for these methods with their available exchange specific params:
fetchOrder: https://bybit-exchange.github.io/docs/v5/order/order-list
cancelOrder: https://bybit-exchange.github.io/docs/v5/order/cancel-order
