### ISSUE TITLE
fetch_trades for cryptopia since parameter

### ISSUE THREAD

**Issue by upggr** [ccxt/ccxt#1111]
I am unable to set the variable $since in php for the fetch_trades for cryptopia. whatever I enter, just defaults to 24 hours.

- OS:
- Programming Language: PHP
- CCXT version: Latest
- Exchange: cryptopia
- Method: fetch_trades

**Comment by kroitor** [comment]
They don't support filtering based on dates on their server-side. We can't really workaround it. Or do you mean filtering within 24 hours?

**Comment by upggr** [comment]
they support filtering based on the last X hours, can we not add a calculation there to find how many hours are since the timestamp to produce the correct api call?

**Comment by kroitor** [comment]
@upggr can you show that in their docs?

**Comment by upggr** [comment]
https://www.cryptopia.co.nz/api/GetMarketHistory/400/48

https://www.cryptopia.co.nz/api/GetMarketHistory/400/72

**Comment by upggr** [comment]
I am really sorry, i meant fetch trades

**Comment by upggr** [comment]
sorry, php too? :)

**Comment by kroitor** [comment]
@upggr yes

**Comment by kroitor** [comment]
@upggr update to 1.10.588

**Comment by upggr** [comment]
excuse me if I am wrong, but you changed the js file in the commit, i still get the same error when i try to do a fetch_trades() in php for cryptopia. 
Can you confirm if the since parameter is in unix timestamp milliseconds or something else?
for example fetch_trades('DOT/DOGE',1515181037) or fetch_trades('DOT/DOGE',1515181037000) or something else?

**Comment by kroitor** [comment]
@upggr i changed the JS file and if you have updated to most recent version 1.10.588, that change should be propagated to your PHP source, because we transpile from JS to Python and PHP upon building. More about it here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

> Can you confirm if the since parameter is in unix timestamp milliseconds or something else?

If you read [the Manual](https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts) carefully all unified methods accept milliseconds timestamps. That is a unix timestamp * 1000.

**Comment by upggr** [comment]
thank you and sorry for all those comments

**Comment by kroitor** [comment]
no worries!

**Comment by kroitor** [comment]
@upggr sorry, the build has not arrived yet. The correct version is 1.10.589. Will be there in 5-10 minutes. My bad.

**Comment by upggr** [comment]
:) thank you :) I have been looking since, too embarrassed to ask again :)

**Comment by upggr** [comment]
I can confirm it works perfect now in php

**Comment by kroitor** [comment]
@upggr ok, it's there, please update and retry again. `$since` should work now in 1.10.589. Sorry for the inconvenience and thx for reporting!
