### ISSUE TITLE
FTX: symbol ID clash between delivery futures and MOVE contracts

### ISSUE THREAD

**Issue by pietrodn** [ccxt/ccxt#11129]
With the latest FTX symbol naming change, it is impossible to get some delivery futures by symbol if their expiry date is the same of a `MOVE` contract.

For example, the symbol `BTC/USD:USD-220325` in CCXT corresponds to the [BTC-MOVE-2022Q1](https://ftx.com/trade/BTC-MOVE-2022Q1) future in FTX.
The [BTC-0325](https://ftx.com/trade/BTC-0325) future, which should be exposed under the same symbol, is not accessible by symbol indexing.

However, it is accessible like this: `client.markets_by_id["BTC-0325"]`. Indeed, the two markets have the same symbol.

According to [the documentation](https://docs.ccxt.com/en/latest/manual.html#futures-contracts), the symbol should be reserved for the delivery future. MOVE futures names are not standardized: maybe we should keep their original market ID?

- OS: macOS
- Programming Language version: Python 3.9.9
- CCXT version: 1.66.21

```python
import asyncio

from ccxt.async_support import ftx


async def main() -> None:
    client = ftx()
    await client.load_markets()
    print(client.market("BTC/USD:USD-220325")["id"])

    await client.close()


if __name__ == "__main__":
    asyncio.run(main())

```

```
BTC-MOVE-2022Q1
```

**Comment by frosty00** [comment]
Yeah we probably need to make an exception for the move futures in this case, will add some code to handle it

**Comment by pietrodn** [comment]
Thank you!

A simple workaround from userland is to override `ftx.fetch_markets()` like this:

```python
 async def fetch_markets(self, params):
    # FIXME: workaround for CCXT bug https://github.com/ccxt/ccxt/issues/11129
    response = await super().fetch_markets(params)
    # Exclude MOVE contract because they clash with delivery futures
    return [market for market in response if "-MOVE-" not in market["id"]]
```

**Comment by kroitor** [comment]
Fixed in the most recent version of CCXT.
