### ISSUE TITLE
How to make the amount of ETH used to place an order more accurate?

### ISSUE THREAD

**Issue by qwe231cvb** [ccxt/ccxt#11122]
The ETH amount I set is "13/eth_price", and the printed value is 0.0033698836094045678.
But in fact, the amount of ETH used to place an order is 0.003, which is inaccurate.
How to make the amount of ETH used to place an order more accurate?

     real_amount = 13/eth_price
     print("real_amount：", real_amount)
     create_order = ftx.create_order('ETH/USDT', 'market', 'buy', eth_order_amount)
     order = ftx.fetch_order(create_order['id'], create_order['symbol'])
     print("order_amount：", order['amount'])

The print result of this code is:
real_amount：0.0033698836094045678
order_amount：0.003

**Comment by DoctorSlimm** [comment]
if you look closely at the ETH/USDT market object returned by the FTX exchange class

`print ( ftx.markets['ETH/USDT'] )`

you will see the following returned
`{
  limits: {
    leverage: { min: 1, max: 20 },
    amount: { min: 0.001, max: undefined },
    price: { min: 0.1, max: undefined },
    cost: { min: undefined, max: undefined }
  },
  precision: { amount: 0.001, price: 0.1 } ... ... ... ` 

this means that the maximum precision of the base currency (ETH in this case) to which you can trade on FTX for this specific market is 0.001 

this precision is exchange-specific and will be different between exchanges, you cannot make your trade amounts and prices more precise than the precision limits of the exchange 

- hope this helps

**Comment by kroitor** [comment]
More info here:

- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits
- https://github.com/ccxt/ccxt/wiki/Manual#markets
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/
