### ISSUE TITLE
bitvavo - calculate_fee crashes for bitvavo

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#11124]
- OS: linux
- Programming Language version: python
- CCXT version: 1.66.23

``` python
import ccxt
exchange = ccxt.bitvavo()
lm = exchange.load_markets()

# The below crashes 
fee = exchange.calculate_fee('XRP/EUR', 'limit', 'buy', 1, 1)
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_2556423/214659024.py in <module>
----> 1 exchange.calculate_fee('XRP/EUR', 'limit', 'buy', 1, 1)

~/.pyenv/versions/3.9.7/envs/trade_397/lib/python3.9/site-packages/ccxt/base/exchange.py in calculate_fee(self, symbol, type, side, amount, price, takerOrMaker, params)
   2099         rate = market[takerOrMaker]
   2100         if cost is not None:
-> 2101             cost *= rate
   2102         return {
   2103             'type': takerOrMaker,

TypeError: unsupported operand type(s) for *=: 'int' and 'NoneType'
```

The same code used to work in 1.61.92 (and also in 1.64.1).

It's unclear to me what caused this - as the affected method in the exchange class does not seem to have been changed lately

**edit** seems to have been introduced in https://github.com/ccxt/ccxt/pull/10958 - without this, the fee was falling back to the configured values of:
```
 'taker': 0.0025,
 'maker': 0.002,
```

As this seems to be one in a series of "fetch_markets unifying" PR's this makes me slightly concerned - which other exchanges would we expect to suffer from such unintended side-effects (assuming we don't expect this to crash)?

i understand that this will use the hardcoded exchange values - but i prefer having hardcoded (per exchange) defaults over having no value or a crash. 
it's clear that these values are only defaults, only maybe the values that are applied once a real trade happens - but it still gives a good estimate on the fees to expect.

**Comment by NFTgiveaway** [comment]
Trust Wallet

 Airdrop starts 2022-01-03

 Airdrop ends 2022-01-23

 Airdrop Link: http://cryptobridge.link/wallet/

 Total value: 10,000,000 TWT

 Platform: Binance chain

**Comment by samgermain** [comment]
Fixed in https://github.com/ccxt/ccxt/pull/11145
