### ISSUE TITLE
Uniform `market["type"]` field semantics

### ISSUE THREAD

**Issue by pietrodn** [ccxt/ccxt#11121]
The `market["type"]` field returned by `Exchange.fetch_markets()` seems to have different semantics across exchanges.

Here is a comparison of the market type literals across 4 exchanges:

| Exchange | Spot   | Margin   | Delivery futures | Perpetual swaps | Options  |
|----------|--------|----------|------------------|-----------------|----------|
| **Binance**  | 'spot' | 'margin' | 'delivery'       | 'future'        | -        |
| **FTX**      | 'spot' | -        | 'future'         | 'swap'          | -        |
| **OKEx**     | 'spot' | -        | 'futures'        | 'swap'          | 'option' |
| **Gate.io**  | 'spot' | 'margin' | 'future'         | 'swap'          | 'option  |

Is there a plan to make the market type part of the public API?
Is there an exchange-independent way to determine if a symbol is a delivery future or a swap?

Thanks!

**Comment by kroitor** [comment]
> Is there a plan to make the market type part of the public API?

Yes, working on that now: https://github.com/ccxt/ccxt/issues/10931

> Is there an exchange-independent way to determine if a symbol is a delivery future or a swap?

We will unify the `type` values and will that to the docs.

**Comment by frosty00** [comment]
I'd suggest we call expiring contracts `future` and swaps `swap` everywhere

**Comment by frosty00** [comment]
btw this is a separate issue from `defaultType`, we won't be able to change that so easily

**Comment by ttodua** [comment]
as sidenote, we might aim to change `type` key with other (i.e. `exchangeType` or 'floor'  whatever) to have a failsafe stable key to avoid conflicting. If 'type' is widely used at this moment, then it might stay as an alias for 1 year or so, while everywhere in docs/examples, `exchangeType` should be used to make users to forget about `type` slowly (while for 1 year, still supporting it as alias)

**Comment by mattepozz** [comment]
Hello!
I noticed another issue related to this bug.

On Binance USDⓈ-M perpetual swaps and delivery futures have the same type: `future`.

Steps to reproduce:

```python
exchange = ccxt.binanceusdm()
markets = exchange.load_markets()
print(f"BTC/USDT type       = {markets['BTC/USDT']['type']}")
print(f"BTCUSDT_220325 type = {markets['BTCUSDT_220325']['type']}")

# BTC/USDT type       = future
# BTCUSDT_220325 type = future
```

**Comment by kroitor** [comment]
@mattepozz yep, that is a known issue that we are in the process of solving, it is there for historical reasons, cause Binance named their API sections that way before, and changed that naming since then.

**Comment by mattepozz** [comment]
@kroitor Thanks for the info!

**Comment by samgermain** [comment]
> 

That's a spot market, `linear` and `inverse` refer to the settle currency. A linear market means that the trades are settled in the quote currency, and an inverse market means that the trades are settled in the base currency. Settle currencies only exist for `contract` or `derivative` markets. In a derivative market, you exchange the settle currency for contracts; if you aren't receiving contracts, then you receive the settle currency, and linear/inverse refers to what currency you receive. A spot market exchanges one currency for another, there is not settle currency, if you are selling the base, you receive the quote, if you are selling the quote, you receive the base, so the concept of linear/inverse doesn't apply.

**Comment by samgermain** [comment]
> Also in this example, delivery is ture, no swap field exists. It's not consistent with document.
> 
> ```
>     'spot':     true,         // whether the market is a spot market
>     'margin':   true,         // whether the market is a margin market
>     'future':   false,        // whether the market is a expiring future
>     'swap':     false,        // whether the market is a perpetual swap
>     'option':   false,        // whether the market is an option contract
> ```
> 
> ```json
> {
>   "active": true,
>   "base": "BTC",
>   "baseId": "BTC",
>   "contractSize": 100,
>   "delivery": true,
>   "exchange": "binance",
>   "expiry": null,
>   "expiryDatetime": null,
>   "future": false,
>   "id": "BTCUSD_PERP",
>   "info": {
>     "baseAsset": "BTC",
>     "baseAssetPrecision": "8",
>     "contractSize": "100",
>     "contractStatus": "TRADING",
>     "contractType": "PERPETUAL",
>     "deliveryDate": "4133404800000",
>     "equalQtyPrecision": "4",
>     "filters": [
>       {
>         "filterType": "PRICE_FILTER",
>         "maxPrice": "4520958",
>         "minPrice": "1000",
>         "tickSize": "0.1"
>       },
>       {
>         "filterType": "LOT_SIZE",
>         "maxQty": "1000000",
>         "minQty": "1",
>         "stepSize": "1"
>       },
>       {
>         "filterType": "MARKET_LOT_SIZE",
>         "maxQty": "60000",
>         "minQty": "1",
>         "stepSize": "1"
>       },
>       {
>         "filterType": "MAX_NUM_ORDERS",
>         "limit": "200"
>       },
>       {
>         "filterType": "MAX_NUM_ALGO_ORDERS",
>         "limit": "100"
>       },
>       {
>         "filterType": "PERCENT_PRICE",
>         "multiplierDecimal": "4",
>         "multiplierDown": "0.9500",
>         "multiplierUp": "1.0500"
>       }
>     ],
>     "liquidationFee": "0.015000",
>     "maintMarginPercent": "2.5000",
>     "marginAsset": "BTC",
>     "marketTakeBound": "0.05",
>     "maxMoveOrderLimit": "10000",
>     "onboardDate": "1597042800000",
>     "orderTypes": [
>       "LIMIT",
>       "MARKET",
>       "STOP",
>       "STOP_MARKET",
>       "TAKE_PROFIT",
>       "TAKE_PROFIT_MARKET",
>       "TRAILING_STOP_MARKET"
>     ],
>     "pair": "BTCUSD",
>     "pricePrecision": "1",
>     "quantityPrecision": "0",
>     "quoteAsset": "USD",
>     "quotePrecision": "8",
>     "requiredMarginPercent": "5.0000",
>     "symbol": "BTCUSD_PERP",
>     "timeInForce": [
>       "GTC",
>       "IOC",
>       "FOK",
>       "GTX"
>     ],
>     "triggerProtect": "0.0500",
>     "underlyingSubType": [],
>     "underlyingType": "COIN"
>   },
>   "inverse": true,
>   "limits": {
>     "amount": {
>       "max": 1000000,
>       "min": 1
>     },
>     "cost": {
>       "max": null,
>       "min": null
>     },
>     "market": {
>       "max": 60000,
>       "min": 1
>     },
>     "price": {
>       "max": 4520958,
>       "min": 1000
>     }
>   },
>   "linear": false,
>   "lowercaseId": "btcusd_perp",
>   "maker": 0.0001,
>   "margin": false,
>   "precision": {
>     "amount": 0,
>     "base": 8,
>     "price": 1,
>     "quote": 8
>   },
>   "quote": "USD",
>   "quoteId": "USD",
>   "settle": "BTC",
>   "settleId": "BTC",
>   "spot": false,
>   "symbol": "BTC/USD",
>   "taker": 0.0005,
>   "type": "delivery"
> }
> ```

Is that a binance market? Binance is one of 3 exchanges that we still have to unify regarding types, the other 2 are Okex and Bybit

**Comment by qiujiangkun** [comment]
> 

Yes, this is from binance.

**Comment by kroitor** [comment]
@qiujiangkun binance is still not unified we had to keep it backward-compatible for historical reasons, but will unify it soon.

**Comment by qiujiangkun** [comment]
> > 
> 
> That's a spot market, `linear` and `inverse` refer to the settle currency. A linear market means that the trades are settled in the quote currency, and an inverse market means that the trades are settled in the base currency. Settle currencies only exist for `contract` or `derivative` markets. In a derivative market, you exchange the settle currency for contracts; if you aren't receiving contracts, then you receive the settle currency, and linear/inverse refers to what currency you receive. A spot market exchanges one currency for another, there is not settle currency, if you are selling the base, you receive the quote, if you are selling the quote, you receive the base, so the concept of linear/inverse doesn't apply.

In some exchanges, both linear and inverse are false instead of null for spot markets. Should they be null or false in this case?

**Comment by kroitor** [comment]
> In some exchanges, both linear and inverse are false instead of null for spot markets. Should they be null or false in this case?

They should be `undefined / None / null` for markets where they don't apply. We will fix for that as well, thanks for pointing it out.

**Comment by samgermain** [comment]
> 



> > > 
> > 
> > 
> > That's a spot market, `linear` and `inverse` refer to the settle currency. A linear market means that the trades are settled in the quote currency, and an inverse market means that the trades are settled in the base currency. Settle currencies only exist for `contract` or `derivative` markets. In a derivative market, you exchange the settle currency for contracts; if you aren't receiving contracts, then you receive the settle currency, and linear/inverse refers to what currency you receive. A spot market exchanges one currency for another, there is not settle currency, if you are selling the base, you receive the quote, if you are selling the quote, you receive the base, so the concept of linear/inverse doesn't apply.
> 
> In some exchanges, both linear and inverse are false instead of null for spot markets. Should they be null or false in this case?

The should be yeah, which exchanges are you referring to? I noticed it on `Okex`, and created a [PR](https://github.com/ccxt/ccxt/pull/11583), but couldn't find any others

**Comment by qiujiangkun** [comment]
> > 
> 
> > > > 
> > > 
> > > 
> > > That's a spot market, `linear` and `inverse` refer to the settle currency. A linear market means that the trades are settled in the quote currency, and an inverse market means that the trades are settled in the base currency. Settle currencies only exist for `contract` or `derivative` markets. In a derivative market, you exchange the settle currency for contracts; if you aren't receiving contracts, then you receive the settle currency, and linear/inverse refers to what currency you receive. A spot market exchanges one currency for another, there is not settle currency, if you are selling the base, you receive the quote, if you are selling the quote, you receive the base, so the concept of linear/inverse doesn't apply.
> > 
> > 
> > In some exchanges, both linear and inverse are false instead of null for spot markets. Should they be null or false in this case?
> 
> The should be yeah, which exchanges are you referring to? I noticed it on `Okex`, and created a [PR](https://github.com/ccxt/ccxt/pull/11583), but couldn't find any others

Within my knowledge, binance is another one.

**Comment by samgermain** [comment]
All exchange markets should have a unified type now except Binance 

Exchange | Spot | Margin | Delivery futures | Perpetual swaps | Options
-- | -- | -- | -- | -- | --
Binance | 'spot' | 'margin' | 'delivery' | 'future' | 'option'
Everything else | 'spot' | 'margin' | 'future' | 'swap' | 'option'
