### ISSUE TITLE
Issue on withdraw on coinex

### ISSUE THREAD

**Issue by alexandrechaudet** [ccxt/ccxt#11136]
Hello,

I've got a problem on the withdraw func with coinex. Everything is ok with kucoin, binance or gate.io.  I found the issue #8137 but it not solve my problem. It looks like ccxt try to check my adress destination and say me it's wrong but i am sure of this.

I was a line in this file : https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/coinex.py : "self.check_address(address)" - line 840. Is the problem here ? I don't really know where ... I think all my vars are ok. 

You can see my sample below with crypto WIN. The problem is the same with USDT. I tried too to add the destination adress in my whitelist (saved adress) on coinex. It's ok to do the withdraw on the coinex website.

Hope a solution. Thank you so much.

- OS: Windows
- Programming Language version: npm = 7.0.6 / node = 15.0.1
- CCXT version: 1.66.24

```
return await exchange.withdraw(coin, amount, adressDestination, tag = undefined, params = { smart_contract_name: networkOfWithdraw, transfer_method: 'onchain' });

coin = 'WIN'
amount = double value
adressDestination = my wallet adress of WIN on TRC20
networkOfWithdraw = 'TRC20'
```

```
Error : erreur inconnue : Invalid Withdrawal Address.
```

**Comment by alexandrechaudet** [comment]
Result in verbose = true :

```
RequestBody:
 {"access_id":"myaccessid(maskedfortheissue)","actual_amount":10,"coin_address":"myadress(maskedfortheissue)","coin_type":"USDT","smart_contract_name":"TRC20","tonce":"1641422060323","transfer_method":"onchain"}

handleRestResponse:
 coinex POST https://api.coinex.com/v1/balance/coin/withdraw 200 OK
ResponseHeaders:
 {
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '6c902c654be739bd-CDG',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json',
  Date: 'Wed, 05 Jan 2022 22:34:20 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Transfer-Encoding': 'chunked'
}
ResponseBody:
 {"code": 310, "data": {}, "message": "Invalid Withdrawal Address."}
```

**Comment by frosty00** [comment]
is there a space in your withdrawal address, is it undefined?

**Comment by alexandrechaudet** [comment]
I've got a good address : TMVsDyL44xxxxxxxxxxxxx9Nn9h6SFR697

**Comment by frosty00** [comment]
> "self.check_address(address)" - line 840. Is the problem here ?

The problem is not there, the exchange is replying with this message

>  {"code": 310, "data": {}, "message": "Invalid Withdrawal Address."}

perhaps you need to add the address to the withdrawal whitelist on the web ui

**Comment by frosty00** [comment]
from the docs:

```coin_address: Withdrawal address, which must be authorized (Must add one record in Withdrawal Whitelist (under Api management)). ```

**Comment by masaya10** [comment]
Hi 
Is there any way to add address with api or withdrawal without add in whitelist in web ui?

**Comment by oak-world** [comment]
I understand that this is a security measure, but it is pointless to use the API if it is for the whitelist to take effect. For people like me who receive hundreds or even thousands of new users daily. Am I supposed to whitelist all their emails manually? It does not make sense to me.

**Comment by jwngma** [comment]
> 

Did you get any solution for this sir?
