### ISSUE TITLE
Bitmex USDT balance shows incorrectly

### ISSUE THREAD

**Issue by janeCMD** [ccxt/ccxt#11147]
I tested with newest CCXT version (yesterday), USDT balance shows incorrectly. Account from example picture has 1.25 BTC and only 10 USDT as far as i know. I think CCXT is not dividing the amount.

Is this some bug or do i do something incorrectly ?

![obrázok](https://user-images.githubusercontent.com/16187940/148397110-b90ea4b6-1949-40af-a136-d9c40517259b.png)

**Comment by frosty00** [comment]
what's the code you used for this?

**Comment by janeCMD** [comment]
> what's the code you used for this?

``
$balance = $exchange->fetch_balance();
print_r($balance);
``
Please ignore part starting with 'Ticker...' Its already not related to this issue.

Response from CCXT always contains parsed data + original response from exchange, where you can see, also BTC balance is returned as a whole number and need to be divided to get the correct balance. That works, but USDT will just return balance same as received from exchange.

**Comment by wunderb1t** [comment]
We've noticed same issue in `fetchBalance` result for Bitmex for USDT and BMEX balances, here is an example:

Balance on Bitmex:

![image](https://user-images.githubusercontent.com/48133876/177287191-5b2f873f-3fa6-4e50-b4cb-029965e15f1d.png)

Received balance via ccxt:

![image](https://user-images.githubusercontent.com/48133876/177287316-96b9b31f-6269-4c09-bf44-055f4f0015d8.png)

- OS: Debian (Docker)
- Programming Language version: NodeJS, JavaScript
- CCXT version: PRO 1.1.82
