### ISSUE TITLE
How to cancel an open order STOP LIMIT in Binance

### ISSUE THREAD

**Issue by criptoice** [ccxt/ccxt#11153]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

**Comment by criptoice** [comment]
Hello, I am coding an automatic trading bot with the Binance API in CCXT
I need to know how I can cancel a Stop Limit order (Buy or Sell) that has been activated (stop price) but that has NOT opened the position (price), yet. What kind of order should I send with CCXT to be able to cancel a stop limit when a time has passed?

Regards

**Comment by carlosmiei** [comment]
Hello @criptoice 
To cancel an active order, regardless of its type (limit, stop-limit, etc) you need to issue a cancel order request, specifying the order id and the market of the order.

Please check out this (python) snippet where an order is being created and canceled:

```Python
import ccxt

exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

markets = exchange.load_markets()

symbol = 'ETH/BTC'
type = 'stop-limit'
side = 'sell'
amount = 1.0
price = 0.060154
order = exchange.create_order(symbol, type, side, amount, price, {"stopPrice": 0.05})
canceled = exchange.cancel_order(order['id'], order['symbol'])
```

You can also see the complete example here:  https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/binance-create-order-cancel-order.py

Please re-open it if it is still not clear

**Comment by cardesatanaz** [comment]
,2

**Comment by cardesatanaz** [comment]
,?,  z,_w _,zgt

**Comment by cardesatanaz** [comment]
,?,  z,_w _,zgtr
