### ISSUE TITLE
Feature Request: Bitmex - conversion function for position amounts

### ISSUE THREAD

**Issue by janeCMD** [ccxt/ccxt#11151]
Bitmex has very unorderly ways to denominate amounts ($amount when posting order) for different markets (It has special 'PositionCurrency' besides base and quote). in BTC/USD, you use amount in USD, in BTC/USDT, amount is in BTC and in ETH/USD, you have to use amount of contracts (where each contract has certain value in BTC). 

It would be nice to see the function, which could bring some order into this - for example 'calculate_amount_from_total_cost($cost_in_quote)'. I was bit studying ccxt code as well as bitmex API, but i am struggling to find good solution. Especially such, which would be abstract enough and work for ETH/USD or other crazy combinations.

The comment in code snippet bellow in fetch_markets method caught my attention, since its about positionCurrency. Empty string  means position is denominated in contracts amount (at least its like that in ETHUSD). I suspect the ccxt code will use quoteCurrency instead, which is incorrect.
```
$base = $this->safe_currency_code($baseId);
$quote = $this->safe_currency_code($quoteId);
$swap = ($id === $basequote);
// 'positionCurrency' may be empty ("", as Bitmex currently returns for ETHUSD)
// so let's take the $quote currency first and then adjust if needed
$positionId = $this->safe_string_2($market, 'positionCurrency', 'quoteCurrency');
```

**Comment by Dan-krm** [comment]
I've opened a PR to use the settlement currency instead of quote currency in the case that you highlighted because I believe ETH/USD and other USD or EUR pairs use BTC as the position currency. I've also previously created a convertValue helper method on Bitmex to convert Bitmex's returned values to the correct decimal place based on the specific trading pair. Please provide more details following this format https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help if this doesn't answer your feature request completely.

**Comment by janeCMD** [comment]
I already solved it in my project nasty non-abstract way like this: 
```
...
else if($pair=="ETH/USD"){
			$cvalue_per_usd=0.001/1000;
			$c_value=$price*$cvalue_per_usd;
			$result=$capital_to_invest/$c_value;
}else if($pair=="XRP/USD"){
			$cvalue_per_usd=0.0002;
			$c_value=$price*$cvalue_per_usd;
			$result=$capital_to_invest/$c_value;
}else if($pair=="DOGE/USD"){
			$cvalue_per_usd=0.001;
			$c_value=$price*$cvalue_per_usd;
			$result=$capital_to_invest/$c_value;
}else if($pair=="SOL/USD"){
			$cvalue_per_usd=0.001/1000;
			$c_value=$price*$cvalue_per_usd;
			$result=$capital_to_invest/$c_value;
}else if($pair=="ADA/USD"){
			$cvalue_per_usd=0.0001;
			$c_value=$price*$cvalue_per_usd;
			$result=$capital_to_invest/$c_value;
}else{
			$result=1;
}
return $result;
```
contract value per usd ($cvalue_per_usd) is what is needed to get from bitmex api for abstract solution, but they don't provide it anywhere (at least i didnt find it).

The purpose of this is to control exactly, how much money (or collateral or whatever else) does trader put into the opened trade. Without this conversion, its impossible to control it. Put into simple question: Trader wants to buy perpetual ADA/USD contracts for total value of 0.5 BTC. How many contracts does he need to buy ? Simply setting position currency unfortunately doesnt solve this problem.
