### ISSUE TITLE
Order Amount sending in BaseCurreny not in QuoteCurrency

### ISSUE THREAD

**Issue by Ahmed089** [ccxt/ccxt#11163]
I'm unable to send amount in USDT in Futures, If I'm using amount as 6.0 so It is taking as the Base Currency not as Quote Currency, I want to use 6 as USDT not as XRP in Futures, I tried to alot of things but unfortunately no success yet, like we see on the exchange that If we just type the value in Size as USDT it simply take that value as USDT position not XRP contracts so I want to use it like that but right now It's sending 6.0 as 6 XRP.

- OS: Win 10
- Programming Language version: Python 3.10
- CCXT version: 1.66.38

```
import config
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
"apiKey": config.apiKey,
"secret": config.secretKey,
'options': {'defaultType': 'future'}, 'createMarketBuyOrderRequiresPrice': 'false', 'enableRateLimit': True})

symbol = 'XRP/USDT'
type = 'market'
side = 'buy'
amount = float(6.0) # in quote currency, how much USDT you want to spend for buying XRP
price = None

order = exchange.create_order(symbol, type, side, amount, price)
pprint(order)

```

**Comment by kroitor** [comment]
Please, use the search. 

Binance futures will always expect the amount in contracts: 

- https://github.com/ccxt/ccxt/issues/10282
- https://github.com/ccxt/ccxt/issues/9785
- https://github.com/ccxt/ccxt/issues/7853
- https://github.com/ccxt/ccxt/issues?q=binance+quoteOrderQty+futures+
