### ISSUE TITLE
How to pass sub account argument to Binance exchange instantiation

### ISSUE THREAD

**Issue by bsauvage1** [ccxt/ccxt#11176]
I can't find anywhere the syntax to tell Binance to load data (.fetchBalance(), .fetch_positions()) only on a subaccount?
On FTX, I would add the below to the parameters dict:
'headers': {'FTX-SUBACCOUNT': 'YOURSUBACCOUNTNAME'}

**Comment by kroitor** [comment]
@bsauvage1 with Binance the API keypair identifies the subaccount, i think, so if you pass the subaccount API key to it, it should fetch the subaccount balance. Let us know if that does not help.

**Comment by bsauvage1** [comment]
ha - it was an issue with my key! it's indeed working fine and directly pings the subaccount. Thank you!
