### ISSUE TITLE
[bitbay] bad url?

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#11178]
Is Bitbay working for anyone?  I'm using 1.66.52, and I'm sure my api keys are valid (but I will generate new ones to check).  I'm just getting:

`ExchangeNotAvailable: bitbay GET https://api.zondaglobal.com/rest/balances/BITBAY/balance system request to https://api.zondaglobal.com/rest/balances/BITBAY/balance failed, reason: getaddrinfo ENOTFOUND api.zondaglobal.com
`

**Comment by kroitor** [comment]
@npomfret please, try this:

```
exchange = new ccxt.bitbay({
    'hostname': 'zonda.exchange',
    // ...
})
```

↑ does it work for you this way? If it does, I will update their URLs shortly.

**Comment by kroitor** [comment]
Nevermind, looks like they changed their API.

**Comment by carlosmiei** [comment]
Hello @npomfret,
I've checked and everything seems to be working fine, so I'm going to close this issue. Probably was a momentary failure, but if you see this again, please reopen it. 
Thanks.
