### ISSUE TITLE
New exchange : BlockFi

### ISSUE THREAD

**Issue by cdcv** [ccxt/ccxt#11177]
- OS: Mac
- Programming Language version: js
- CCXT version: v1.66.32

Is anyone up for adding BlockFi exchange to CCXT?

Thank you!!  ;-)

**Comment by peeeeeter** [comment]
I'd live to vote for BlockFi as well.  Since they offer interest on many coins, I'd like to hold coins via BlockFi when not actively trading.  I know some other exchanges offer interest as well, but BlockFi is getting a lot of buzz as they also have a Credit Card that earns rewards in Crypto..

**Comment by frosty00** [comment]
RIP blockfi
