### ISSUE TITLE
deribit.fetchPositions return []

### ISSUE THREAD

**Issue by rainssong** [ccxt/ccxt#11181]
CCXT version:'1.66.54'

```
<script type="text/javascript" src="https://unpkg.com/ccxt"></script>
<script>
deribit=new ccxt.deribit()
//set API key
deribit.fetchPositions()
//return []
</script>
```

**Comment by kroitor** [comment]
@rainssong do you actually have any open positions with BTC options?

**Comment by rainssong** [comment]
> @rainssong do you actually have any open positions with BTC options?

Sure, and deribit.privateGetGetPositions() works.

**Comment by kroitor** [comment]
@rainssong please, paste your verbose output and your actual runtime version number:

```HTML
<script type="text/javascript" src="https://unpkg.com/ccxt"></script>
<script>
'use strict';
async function main () {
    const exchange = new ccxt.deribit({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET',
    })
    await exchange.loadMarkets ()
    exchange.verbose = true
    const positions = await deribit.fetchPositions()
}

document.addEventListener ("DOMContentLoaded", main)
</script>
```

**Comment by rainssong** [comment]
this bug happens in line 67806

the response is in different strcture

![image](https://user-images.githubusercontent.com/2149915/148666870-13e22f17-f19e-45a1-a66c-875fc5740169.png)

maybe change line 67852
        `const result = this.parsePositions (response);`
to
`const result = this.parsePositions (response.result);`

will fix this

**Comment by kroitor** [comment]
@rainssong thanks, i've pushed a fix to it. The new build will arrive in CCXT 1.66.57+ in ~20 minutes. Please, let us know here if that solves the issue for you or not. Thx again!

**Comment by rainssong** [comment]
it works and looks proper now

in version 1.6610, the result is like:
```
[
    {
        "vega": "0.0",
        "total_profit_loss": "0.0",
        "theta": "0.0",
        "size": "0.0",
        "settlement_price": "0.00832017",
        "realized_profit_loss": "0.000064034",
        "open_orders_margin": "0.0",
        "mark_price": "0.00718766",
        "maintenance_margin": "0.0",
        "kind": "option",
        "instrument_name": "BTC-14JAN22-45000-C",
        "initial_margin": "0.0",
        "index_price": "41999.38",
        "gamma": "0.0",
        "floating_profit_loss_usd": "0.0",
        "floating_profit_loss": "0.0",
        "direction": "zero",
        "delta": "0.0",
        "average_price_usd": "0.0",
        "average_price": "0.0"
    }
]
```

and now 1.66.57
`[
    {
        "info": {
            "vega": "0.0",
            "total_profit_loss": "0.0",
            "theta": "0.0",
            "size": "0.0",
            "settlement_price": "0.00832017",
            "realized_profit_loss": "0.000064034",
            "open_orders_margin": "0.0",
            "mark_price": "0.00706313",
            "maintenance_margin": "0.0",
            "kind": "option",
            "instrument_name": "BTC-14JAN22-45000-C",
            "initial_margin": "0.0",
            "index_price": "41964.66",
            "gamma": "0.0",
            "floating_profit_loss_usd": "0.0",
            "floating_profit_loss": "0.0",
            "direction": "zero",
            "delta": "0.0",
            "average_price_usd": "0.0",
            "average_price": "0.0"
        },
        "symbol": "BTC/BTC:BTC-220114:45000:call",
        "timestamp": 1641698051502,
        "datetime": "2022-01-09T03:14:11.502Z",
        "initialMargin": 0,
        "maintenanceMargin": 0,
        "maintenanceMarginPercentage": 0,
        "entryPrice": "0.0",
        "notional": 0,
        "unrealizedPnl": 0,
        "contracts": 0,
        "contractSize": 1,
        "markPrice": "0.00706313",
        "side": "zero"
    }
]`
