### ISSUE TITLE
[Bybit] Fetch markets don't load spot symbols

### ISSUE THREAD

**Issue by fasenderos** [ccxt/ccxt#11182]
As per title the `fetchMarkets` method load symbols only from the endpoint `GET /v2/public/symbols` (https://bybit-exchange.github.io/docs/inverse/#t-querysymbol) that return symbols from `Inverse Perpetual`, `USDT Perpetual` and `Future Perpetual`, not from `Spot`.

For the Spot market the endpoint is `GET /spot/v1/symbols` (https://bybit-exchange.github.io/docs/spot/#t-querysymbol), it would be great to let passing the market type in the params of the `fetchMarkets` function.

Open for PR

Thanks.

**Comment by kroitor** [comment]
I'm reworking the Bybit integration, it will be available this month:

- https://github.com/ccxt/ccxt/issues/9803
