### ISSUE TITLE
mexc 1w timeframes not exists

### ISSUE THREAD

**Issue by a5601564** [ccxt/ccxt#11220]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: windows
- Programming Language version: python 3.8
- CCXT version: '1.66.93'

![image](https://user-images.githubusercontent.com/17686185/148858681-c966669d-db6b-482f-a5ae-eb65b214ceb7.png)

![image](https://user-images.githubusercontent.com/17686185/148859616-48f6b4d5-d5f6-45cb-b33e-385fe79427f0.png)

**Comment by kroitor** [comment]
They don't have the 1w timeframe for spot markets: https://mxcdevelop.github.io/APIDoc/

**Comment by a5601564** [comment]
thanks for your reading , i read the official api document, '1w' that is actually not exist .
 
in this situation ,  what's  your recommend?

**Comment by kroitor** [comment]
> in this situation , what's your recommend?

You can build the higher-order timeframe from a lower-order timeframe, see, for example, how OHLCVs are generated from trades tick data: https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L1791

**Comment by a5601564** [comment]
thanks for your answer.
