### ISSUE TITLE
How to code the Break Even Orders in Binance

### ISSUE THREAD

**Issue by criptoice** [ccxt/ccxt#11224]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

**Comment by criptoice** [comment]
We need to place Break-Even orders on Binance. We are building an automatic bot
I would like to know how it is encoded in CCXT, and if you have any examples or guides for the code. We would like to know which is the best way for this type of BE order
Any advice? Could you help us with this?

Thanks

**Comment by DoctorSlimm** [comment]
@criptoice can you clarify a little more by what you mean by break-even orders, do you mean break-even orders with regards to options trading or regular spot markets?

**Comment by ttodua** [comment]
There is no built-in functionality in CCXT to make fire break-even orders. You have to build your logic where you can trigger any order (entry/exit) per your defined targets (be it breakeven or whatever).
There are two ways to achieve that:
1) if you are submitting a market order, then after submitting it, immediately fetch the order details, to find-out the entry-price & cost:
```
let order = exch.createOrder ('BTC/USDT', 'market', 'buy',  amount, undefined);
// if exchange in question only returns the 'id' of the order, then you further need to fetch order details like:
// order = exch.fetchOrder (order_id, 'BTC/USDT');
2) according to [order structure](https://docs.ccxt.com/en/latest/manual.html#order-structure) access entry-price:
```
const entryPrice = order['average']; // or order['price']
```
and fire another limit order to lock your breakeven, like:
```
let order_be = exch.createOrder ('BTC/USDT', 'market', 'buy',  amount, entryPrice , params );
```

Note: `params` can be empty for spot market, however if you trade on future/swap, you should you `params = { 'reduceOnly': true }` to tell the API that your order is 'exit' order (instead of re-opening the opposite position, thus having double-sided position, a.k.a. "hedged" positions)

Let us know if you have any further issue with CCXT.
