### ISSUE TITLE
Format of FTX symbols are changed in new versions

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#11225]
We have noticed that FTX symbol format is changed, e.g. from `1INCH-PERP` to `1INCH/USD:USD` in `watchTicker` and `fetchTickers` methods.

Why this decision was made? Now we need to make time-consuming migration process. And how we can transform now 
`1INCH/USD:USD` format to `1INCH-PERP` and back?       

- OS:  Debian (Docker)
- Programming Language version: NodeJS, JavaScript
- CCXT version: PRO 0.9.35

**Comment by kroitor** [comment]
@wunderb1t 

> We have noticed that FTX symbol format is changed, e.g. from `1INCH-PERP` to `1INCH/USD:USD` in `watchTicker` and `fetchTickers` methods. Why this decision was made?

That is to unify the contract trading across the exchanges. It was announced here: https://github.com/ccxt/ccxt/issues/10931.

> And how we can transform now 1INCH/USD:USD format to 1INCH-PERP and back?

You can easily map market ids to unified symbols and back:

- https://github.com/ccxt/ccxt/wiki/Manual#methods-for-markets-and-currencies

```Python
exchange = ccxt.ftx()
markets = exchange.load_markets()
for symbol in exchange.symbols:
    market = exchange.market(symbol)
    print(market['id'], market['symbol'])
    
market_id = 'BTC-PERP'
symbol = exchange.safe_symbol(market_id)
print(market_id, symbol)
```

Let us know if that does not answer your question. Feel free to reopen it if necessary.

**Comment by frosty00** [comment]
also the old symbols should continue to work
