### ISSUE TITLE
Bitfinex returns negative balance

### ISSUE THREAD

**Issue by nmiculinic** [ccxt/ccxt#1123]
Biftinex returns negative balance.

- OS: Linux protagonist 4.14.5-1-ARCH #1 SMP PREEMPT Sun Dec 10 14:50:30 UTC 2017 x86_64 GNU/Linux
- Programming Language: python 
- CCXT version: 1.10.593
- Exchange: Bitfinex
- Method: fetch_balance

Reproduction requires private API keys.

From info field:
```
{'type': 'exchange', 'currency': 'eos', 'amount': '-0.00000032', 'available': '0.0'}
```

which goes to 
```
{'free': 0.0, 'used': -3.2e-07, 'total': -3.2e-07}
```

after ccxt mangling.

This is definitely a bug on Bitfinex side...I'm not sure what to think of it. 

I'd suggest ```max(0, amount)``` though am not sure if this the right call (since this error shall fall silently). Comments?

**Comment by kroitor** [comment]
> Comments?

More questions than comments ) Do you margin-trade there?

**Comment by nmiculinic** [comment]
Nope

**Comment by kroitor** [comment]
@nmiculinic is here any chance to check if the tradelog sums to a negative total on that asset? Or it would be too hard at this point?

**Comment by nmiculinic** [comment]
It's a bit too hard since there was a lot of trades, and ccxt doesn't do history pagination yet (plus bitfinex is stingy with limits).

**Comment by kroitor** [comment]
@nmiculinic ok, we will investigate into this as far as we can, will try to get a negative on our balance ))

**Comment by mkutny** [comment]
Some time ago I've got a similar issue. I saw a negative amount via their UI but haven't come up with an idea to check what would ccxt return.

I'm not sure we need to `max(0, amount)` though. The balance *is* negative. We need to reflect the reality to users even if we don't like it.

**Comment by kroitor** [comment]
I would agree with @mkutny here, it's obviously coming from their API, and we would not want to change values implicitly. I would suggest to account for that in logic, as we most likely cannot workaround this in the lib, better leave it for the user to decide. Closing this for now, until we have some followup on this. Feel free to reopen it if needed, or just continue posting here, we will be happy to answer.
