### ISSUE TITLE
Paper Trading: How are paper trading execution prices selected?

### ISSUE THREAD

**Issue by cdcv** [ccxt/ccxt#11237]
- OS: Mac
- Programming Language version: Node v14.16.1
- CCXT version: 1.66.32

In using paper trading, for example on binance, how are execution prices selected for limit orders and for market orders?  
For example, for market orders, is the execution price of the next transaction executed on the exchange used as the order price for the paper trade (regardless of the next transaction size compared to the paper trade transaction size), is the current order book taken into considerable based on the size of the paper trade order, or is there some other approach?  
For limit orders, how is it decided whether the order executes?  Again, based on the order book depth, or some other approach?
Are maker/taker fees handled correctly?
Does ccxt unify this across exchanges somehow, or will the results be processed differently by different exchanges paper trading api calls?
Is there a way to request info regarding this from the exchange API? 

Thank you.

**Comment by kroitor** [comment]
CCXT does not decide your prices, it's not a bot. It's a programmatic library of codes for developers that you can use to make and program the bot for yourself. CCXT lets you talk to the exchanges directly. What to say – is up to you (your business logic and your code). 

The usage of CCXT is documented in the Manual: https://docs.ccxt.com

That said, CCXT does not include any trading strategies per se. If you're looking for a bot based on CCXT, i'd recommend taking a look at https://www.freqtrade.io/en/stable/

On paper trading – CCXT allows you to connect to the exchanges sandboxes and testnets to trade paper money, but what to trade for what – is up to you.

Does that answer your question?

**Comment by kroitor** [comment]
Feel free to reopen this issue or just ask further questions if any.

**Comment by ttodua** [comment]
If you want to find out how they do internal handling of testnet, I think we can't answer that, because binance doesn't have a functional testnet site for spot, however, for futures, you can see it as they do have a 'fully featured' immitation of markets & orderbooks in live, i.e. : https://testnet.binancefuture.com/

**Comment by kroitor** [comment]
More or testnets and sandboxes in the Manual here: https://github.com/ccxt/ccxt/wiki/Manual#testnets-and-sandbox-environments

**Comment by cdcv** [comment]
Thanks for your quick reply.  However, I still have the same question.  I was aware that ccxt is not a bot and that prices are probably selected by the testnet of the exchange. I haven't been able to find  documentation on how the exchanges actually implement paper trading and especially how they select execution prices and determine slippage.  Does anyone have experience with this, or links to more detailed documentation?  Thanks again.

**Comment by kroitor** [comment]
@cdcv i'd recommend googling for `matching engine` and checking github for open source matching engines to answer how exactly the orders are executed:

- https://en.wikipedia.org/wiki/Order_matching_system
- https://www.google.com/search?q=exchange+matching+engine
- https://www.google.com/search?q=maching+engine+site%3Agithub.com
