### ISSUE TITLE
Why is Binance placing wrong order quantity?

### ISSUE THREAD

**Issue by Smilestate** [ccxt/ccxt#11251]
When I used the Binance ordering interface today, I suddenly found that the number of market orders did not meet my expectations. I then looked at the source code and found that when calling the Binance market ordering interface, you chose quoteOrderQty instead of quantity. This confused me and caused my order quantity to be inaccurate!
```javascript
if (uppercaseType === 'MARKET') {
            const quoteOrderQty = this.safeValue (this.options, 'quoteOrderQty', false);
            if (quoteOrderQty) {
                const quoteOrderQty = this.safeNumber (params, 'quoteOrderQty');
                const precision = market['precision']['price'];
                if (quoteOrderQty !== undefined) {
                    request['quoteOrderQty'] = this.decimalToPrecision (quoteOrderQty, TRUNCATE, precision, this.precisionMode);
                    params = this.omit (params, 'quoteOrderQty');
                } else if (price !== undefined) {
                    request['quoteOrderQty'] = this.decimalToPrecision (amount * price, TRUNCATE, precision, this.precisionMode);
                } else {
                    quantityIsRequired = true;
                }
            } else {
                quantityIsRequired = true;
            }
```
This caused my order quantity to be inaccurate. I hope you can improve it or reopen a new interface!

**Comment by kroitor** [comment]
@Smilestate if you supply a price for your market order, CCXT will use quoteOrderQty. Do not supply a price for the market orders if you want to the amount in base currency.

**Comment by Smilestate** [comment]
Thank you very much for solving my doubts!

> @Smilestate normally, market orders should not include a price argument. If you supply a price for your market order, CCXT will use quoteOrderQty. Do not supply a price for the market orders if you want to use the amount in base currency.

Thank you very much for solving my doubts!

**Comment by Smilestate** [comment]
> @Smilestate通常，市场订单不应包含价格参数。如果您为您的市场订单提供价格，CCXT 将使用 quoteOrderQty。如果您想使用基础货币金额，请不要为市价单提供价格。
```javascript
 let order = await exchange.createOrder(symbol, type, side, amount, type == 'market' ? null : price, params);
This looks fine, but Binance returns the following error message:
binance {"code":-1013,"msg":"Invalid quantity."}
```

**Comment by kroitor** [comment]
@Smilestate https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
