### ISSUE TITLE
Krake symbol for BTC/USD perpetual future

### ISSUE THREAD

**Issue by ShieldTrade** [ccxt/ccxt#11287]
OS:Windows 10
Programming Language version: Python 3.7
CCXT version: CCXT version: CCXT Pro Version: 0.8.13
Exchange Kraken

I am trying to get the symbol for BTC/USD perpetual future on Kraken using CCXT command

`exchange.symbols`

this is the list I get

`['1INCH/EUR', '1INCH/USD', 'AAVE/AUD', 'AAVE/BTC', 'AAVE/ETH', 'AAVE/EUR', 'AAVE/GBP', 'AAVE/USD', 'ADA/AUD', 'ADA/BTC', 'ADA/ETH', 'ADA/EUR', 'ADA/GBP', 'ADA/USD', 'ADA/USDT', 'ALGO/BTC', 'ALGO/ETH', 'ALGO/EUR', 'ALGO/GBP', 'ALGO/USD', 'ANKR/BTC', 'ANKR/EUR', 'ANKR/GBP', 'ANKR/USD', 'ANT/BTC', 'ANT/ETH', 'ANT/EUR', 'ANT/USD', 'ATOM/AUD', 'ATOM/BTC', 'ATOM/ETH', 'ATOM/EUR', 'ATOM/GBP', 'ATOM/USD', 'AUD/JPY', 'AUD/USD', 'AVAX/EUR', 'AVAX/USD', 'AXS/EUR', 'AXS/USD', 'BADGER/EUR', 'BADGER/USD', 'BAL/BTC', 'BAL/ETH', 'BAL/EUR', 'BAL/USD', 'BAND/EUR', 'BAND/USD', 'BAT/BTC', 'BAT/ETH', 'BAT/EUR', 'BAT/JPY', 'BAT/USD', 'BCH/AUD', 'BCH/BTC', 'BCH/ETH', 'BCH/EUR', 'BCH/GBP', 'BCH/JPY', 'BCH/USD', 'BCH/USDT', 'BNC/EUR', 'BNC/USD', 'BNT/BTC', 'BNT/EUR', 'BNT/GBP', 'BNT/USD', 'BTC/AUD', 'BTC/CAD', 'BTC/CHF', 'BTC/DAI', 'BTC/EUR', 'BTC/GBP', 'BTC/JPY', 'BTC/USD', 'BTC/USDC', 'BTC/USDT', 'CHZ/EUR', 'CHZ/USD', 'COMP/BTC', 'COMP/ETH', 'COMP/EUR', 'COMP/USD', 'CQT/EUR', 'CQT/USD', 'CRV/BTC', 'CRV/ETH', 'CRV/EUR', 'CRV/USD', 'CTSI/EUR', 'CTSI/USD', 'DAI/EUR', 'DAI/USD', 'DAI/USDT', 'DASH/BTC', 'DASH/EUR', 'DASH/USD', 'DOGE/BTC', 'DOGE/EUR', 'DOGE/USD', 'DOGE/USDT', 'DOT/AUD', 'DOT/BTC', 'DOT/ETH', 'DOT/EUR', 'DOT/GBP', 'DOT/USD', 'DOT/USDT', 'DYDX/EUR', 'DYDX/USD', 'ENJ/BTC', 'ENJ/EUR', 'ENJ/GBP', 'ENJ/USD', 'EOS/BTC', 'EOS/ETH', 'EOS/EUR', 'EOS/USD', 'EOS/USDT', 'ETC/BTC', 'ETC/ETH', 'ETC/EUR', 'ETC/USD', 'ETH/AUD', 'ETH/BTC', 'ETH/CAD', 'ETH/CHF', 'ETH/DAI', 'ETH/EUR', 'ETH/GBP', 'ETH/JPY', 'ETH/USD', 'ETH/USDC', 'ETH/USDT', 'ETH2.S/ETH', 'EUR/AUD', 'EUR/CAD', 'EUR/CHF', 'EUR/GBP', 'EUR/JPY', 'EUR/USD', 'EWT/BTC', 'EWT/EUR', 'EWT/GBP', 'EWT/USD', 'FIL/AUD', 'FIL/BTC', 'FIL/ETH', 'FIL/EUR', 'FIL/GBP', 'FIL/USD', 'FLOW/BTC', 'FLOW/ETH', 'FLOW/EUR', 'FLOW/GBP', 'FLOW/USD', 'GBP/USD', 'GHST/BTC', 'GHST/EUR', 'GHST/GBP', 'GHST/USD', 'GLMR/EUR', 'GLMR/USD', 'GNO/BTC', 'GNO/ETH', 'GNO/EUR', 'GNO/USD', 'GRT/AUD', 'GRT/BTC', 'GRT/ETH', 'GRT/EUR', 'GRT/GBP', 'GRT/USD', 'ICX/BTC', 'ICX/ETH', 'ICX/EUR', 'ICX/USD', 'INJ/EUR', 'INJ/USD', 'KAR/EUR', 'KAR/USD', 'KAVA/BTC', 'KAVA/ETH', 'KAVA/EUR', 'KAVA/USD', 'KEEP/BTC', 'KEEP/ETH', 'KEEP/EUR', 'KEEP/USD', 'KILT/EUR', 'KILT/USD', 'KINT/EUR', 'KINT/USD', 'KNC/BTC', 'KNC/ETH', 'KNC/EUR', 'KNC/USD', 'KSM/AUD', 'KSM/BTC', 'KSM/DOT', 'KSM/ETH', 'KSM/EUR', 'KSM/GBP', 'KSM/USD', 'LINK/AUD', 'LINK/BTC', 'LINK/ETH', 'LINK/EUR', 'LINK/GBP', 'LINK/JPY', 'LINK/USD', 'LINK/USDT', 'LPT/BTC', 'LPT/EUR', 'LPT/GBP', 'LPT/USD', 'LRC/EUR', 'LRC/USD', 'LSK/BTC', 'LSK/ETH', 'LSK/EUR', 'LSK/USD', 'LTC/AUD', 'LTC/BTC', 'LTC/ETH', 'LTC/EUR', 'LTC/GBP', 'LTC/JPY', 'LTC/USD', 'LTC/USDT', 'LUNA/EUR', 'LUNA/USD', 'MANA/BTC', 'MANA/ETH', 'MANA/EUR', 'MANA/USD', 'MATIC/BTC', 'MATIC/EUR', 'MATIC/GBP', 'MATIC/USD', 'MINA/BTC', 'MINA/EUR', 'MINA/GBP', 'MINA/USD', 'MIR/EUR', 'MIR/USD', 'MKR/BTC', 'MKR/EUR', 'MKR/GBP', 'MKR/USD', 'MLN/BTC', 'MLN/ETH', 'MLN/EUR', 'MLN/USD', 'MOVR/EUR', 'MOVR/USD', 'NANO/BTC', 'NANO/ETH', 'NANO/EUR', 'NANO/USD', 'OCEAN/BTC', 'OCEAN/EUR', 'OCEAN/GBP', 'OCEAN/USD', 'OGN/EUR', 'OGN/USD', 'OMG/BTC', 'OMG/ETH', 'OMG/EUR', 'OMG/JPY', 'OMG/USD', 'OXT/BTC', 'OXT/ETH', 'OXT/EUR', 'OXT/USD', 'OXY/EUR', 'OXY/USD', 'PAXG/BTC', 'PAXG/ETH', 'PAXG/EUR', 'PAXG/USD', 'PERP/EUR', 'PERP/USD', 'PHA/EUR', 'PHA/USD', 'QTUM/BTC', 'QTUM/ETH', 'QTUM/EUR', 'QTUM/USD', 'RARI/BTC', 'RARI/EUR', 'RARI/GBP', 'RARI/USD', 'RAY/EUR', 'RAY/USD', 'REN/BTC', 'REN/EUR', 'REN/GBP', 'REN/USD', 'REP/BTC', 'REP/ETH', 'REP/EUR', 'REP/USD', 'REPV1/BTC', 'REPV1/ETH', 'REPV1/EUR', 'REPV1/USD', 'SAND/BTC', 'SAND/EUR', 'SAND/GBP', 'SAND/USD', 'SC/BTC', 'SC/ETH', 'SC/EUR', 'SC/USD', 'SDN/EUR', 'SDN/USD', 'SHIB/EUR', 'SHIB/USD', 'SNX/AUD', 'SNX/BTC', 'SNX/ETH', 'SNX/EUR', 'SNX/GBP', 'SNX/USD', 'SOL/BTC', 'SOL/EUR', 'SOL/GBP', 'SOL/USD', 'SRM/BTC', 'SRM/EUR', 'SRM/GBP', 'SRM/USD', 'STORJ/BTC', 'STORJ/ETH', 'STORJ/EUR', 'STORJ/USD', 'SUSHI/BTC', 'SUSHI/EUR', 'SUSHI/GBP', 'SUSHI/USD', 'TBTC/BTC', 'TBTC/ETH', 'TBTC/EUR', 'TBTC/USD', 'TRX/BTC', 'TRX/ETH', 'TRX/EUR', 'TRX/USD', 'UNI/BTC', 'UNI/ETH', 'UNI/EUR', 'UNI/USD', 'USD/CAD', 'USD/CHF', 'USD/JPY', 'USDC/AUD', 'USDC/EUR', 'USDC/GBP', 'USDC/USD', 'USDC/USDT', 'USDT/AUD', 'USDT/CAD', 'USDT/CHF', 'USDT/EUR', 'USDT/GBP', 'USDT/JPY', 'USDT/USD', 'WAVES/BTC', 'WAVES/ETH', 'WAVES/EUR', 'WAVES/USD', 'WBTC/BTC', 'WBTC/EUR', 'WBTC/USD', 'XLM/AUD', 'XLM/BTC', 'XLM/EUR', 'XLM/GBP', 'XLM/USD', 'XMR/BTC', 'XMR/EUR', 'XMR/USD', 'XRP/AUD', 'XRP/BTC', 'XRP/CAD', 'XRP/ETH', 'XRP/EUR', 'XRP/GBP', 'XRP/JPY', 'XRP/USD', 'XRP/USDT', 'XTZ/AUD', 'XTZ/BTC', 'XTZ/ETH', 'XTZ/EUR', 'XTZ/GBP', 'XTZ/USD', 'YFI/AUD', 'YFI/BTC', 'YFI/ETH', 'YFI/EUR', 'YFI/GBP', 'YFI/USD', 'ZEC/BTC', 'ZEC/EUR', 'ZEC/USD', 'ZRX/BTC', 'ZRX/EUR', 'ZRX/GBP', 'ZRX/USD']`

I asked Kraken help desk and they told me for them the symbol is `pi_xbtusd` which is not listed. 

can you please help me ?

**Comment by kroitor** [comment]
Kraken futures is not integrated with CCXT yet, it's basically a separate exchange API, you can download and test it here: 

- https://github.com/ccxt/ccxt/pull/6870

Hope that answers your question, let us know if not.

**Comment by ShieldTrade** [comment]
thank you. Very fast answer as usual. I will test it
