### ISSUE TITLE
3 new exchanges (Yobit, coinexchange, bibox)

### ISSUE THREAD

**Issue by serul** [ccxt/ccxt#1128]
Amazing project guys!!!
Please consider the following (very hot and upcoming, but also established) exchanges:

https://github.com/Biboxcom/api_reference/wiki/home_en
http://coinexchangeio.github.io/slate/
https://www.yobit.net/en/api/

**Comment by kroitor** [comment]
Hi, @serul!

- yobit is already supported )
- coinexchangeio is also almost there: https://github.com/ccxt/ccxt/pull/1125
- will look at biboxcom, but it does not look like an exchange at all

Thx!

**Comment by slideup-benni** [comment]
BiBox is an Exchange: https://www.bibox.com on CMC https://coinmarketcap.com/exchanges/bibox/

**Comment by kroitor** [comment]
@slideup-benni it was added to ccxt today ;)

**Comment by slideup-benni** [comment]
Sorry :smile: I knew you are fast :+1:

**Comment by kroitor** [comment]
@slideup-benni it wasn't me, thank @kornrunner for it, he did a very good job integrating it, here: https://github.com/ccxt/ccxt/pull/1221 )

**Comment by serul** [comment]
Awesome, thanks guys!

Norman Dilthey
M: +49 175 1082 487
E: ndilthey@gmail.com

2018-01-13 21:56 GMT+01:00 Igor Kroitor <notifications@github.com>:
