### ISSUE TITLE
Binance USD-M futures fetchPositions() raises KeyError: 'contractSize'

### ISSUE THREAD

**Issue by kasimsuzen** [ccxt/ccxt#11296]
fetchPositions() on Binance USD-M futures raises KeyError: 'contractSize', could not reproduce this error with a fresh application but an older running instance produce this error always. Issue might be related to the changes for #11123  . 
 
- OS: Ubuntu 20.04.3
- Programming Language version: Python 3.8.10
- CCXT version: 1.66.23

```
exchange_id = 'binance'
exchange_class = getattr(ccxt, exchange_id)
options['defaultType'] = 'future'

exchange = exchange_class({
    'apiKey': 'apikey',
    'secret': 'secret',
    'enableRateLimit': True
    'options': options,
})

position = exchange.fetchPositions()
```

```
Exception happened during processing of request from ('myip', myport)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "server.py", line 67, in do_POST
    strategist.webhook_signal_analyzer(request_data)
  File "/home/ubuntu/Bot/strategist.py", line 34, in webhook_signal_analyzer
    orders.future_close_pos_on_symbol(config.exchanges[i],request['symbol'],request['signal'])
  File "/home/ubuntu/Bot/orders.py", line 41, in future_close_pos_on_symbol
    position = exchange.fetchPositions()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxt/binance.py", line 4486, in fetch_positions
    return self.fetch_positions_risk(symbols, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxt/binance.py", line 4587, in fetch_positions_risk
    parsed = self.parse_position_risk(response[i])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxt/binance.py", line 4397, in parse_position_risk
    leftSide = Precise.string_mul(contractsAbs, market['contractSize'])
KeyError: 'contractSize'
```

**Comment by samgermain** [comment]
> fetchPositions() on Binance USD-M futures raises KeyError: 'contractSize', could not reproduce this error with a fresh application but an older running instance produce this error always. Issue might be related to the changes for #11123 .
> 
>     * OS: Ubuntu 20.04.3
> 
>     * Programming Language version: Python 3.8.10
> 
>     * CCXT version: 1.66.23
> 
> 
> ```
> exchange_id = 'binance'
> exchange_class = getattr(ccxt, exchange_id)
> options['defaultType'] = 'future'
> 
> exchange = exchange_class({
>     'apiKey': 'apikey',
>     'secret': 'secret',
>     'enableRateLimit': True
>     'options': options,
> })
> 
> position = exchange.fetchPositions()
> ```
> 
> ```
> Exception happened during processing of request from ('myip', myport)
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
>     self.finish_request(request, client_address)
>   File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
>     self.handle()
>   File "/usr/lib/python3.8/http/server.py", line 427, in handle
>     self.handle_one_request()
>   File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
>     method()
>   File "server.py", line 67, in do_POST
>     strategist.webhook_signal_analyzer(request_data)
>   File "/home/ubuntu/Bot/strategist.py", line 34, in webhook_signal_analyzer
>     orders.future_close_pos_on_symbol(config.exchanges[i],request['symbol'],request['signal'])
>   File "/home/ubuntu/Bot/orders.py", line 41, in future_close_pos_on_symbol
>     position = exchange.fetchPositions()
>   File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxt/binance.py", line 4486, in fetch_positions
>     return self.fetch_positions_risk(symbols, params)
>   File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxt/binance.py", line 4587, in fetch_positions_risk
>     parsed = self.parse_position_risk(response[i])
>   File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxt/binance.py", line 4397, in parse_position_risk
>     leftSide = Precise.string_mul(contractsAbs, market['contractSize'])
> KeyError: 'contractSize'
> ```

I couldn't get the same error output in my console, but [this PR](https://github.com/ccxt/ccxt/pull/11582) should fix the issue, so if you try it again I believe it should work
