### ISSUE TITLE
fundingRate, previousFundingRate and nextFundingRate

### ISSUE THREAD

**Issue by zsyh** [ccxt/ccxt#11298]
related: PR #10512 #10225
I think in the return data structure of fetchFundingRate api, should contain `fundingRate` and `nextFundingRate`, but not `previousFundingRate`.

`previousFundingRate` means the fundingRate that already been charged, this field should not be included in fetchFundingRate api.
`fundingRate` means the fundingRate that will be charged in the next 1-8hours(or according to the exchange settings). fundingRate should never be None.
`nextFundingRate` means the fundingRate that will be charged next time, after fundingRate being charged. Some exchanges don't have this field, like ftx.

In the current ccxt implementation, `previousFundingRate` is confused with `fundingRate`.  In the most exchanges' ccxt implementation, `previousFundingRate` should rename to `fundingRate`. In ftx, `nextFundingRate` should rename to `fundingRate`. In okex, `nextFundingRate` should rename to `fundingRate`, and in okex, `nextFundingRate`  itself should be reimplemented.

**Comment by zsyh** [comment]
@kroitor If you agree with my opinion, I'm glad to make a PR to solve this.

**Comment by frosty00** [comment]
@zsyh we cannot calculate the fundingRate that far in advance. Any exchange that provides the nextFundingRate that you speak of is just using an estimation for the indexPrice of the next period however the number is meaningless since the price can change before the next funding period starts so it has no bearing on the actual funding rate charged

**Comment by zsyh** [comment]
@frosty00 That is true, but the meaning of fundingRate you understand is different from me, and different from most of exchanges.  All exchanges provide fundingRate (you called nextFundingRate) via fetchFundingRate api.  Although it is predicted, and it can change over time, it can guide users to trade.  Actually, no exchange provides previousFundingRate via fetchFundingRate api. If you want to fetch the fundingRate you have been charged, you need to call fetchFundingRateHistory api, rather than fetchFundingRate api.

**Comment by frosty00** [comment]
> Actually, no exchange provides previousFundingRate via fetchFundingRate api. If you want to fetch the fundingRate you have been charged, you need to call fetchFundingRateHistory api, rather than fetchFundingRate api.

That is not true, huobi, gateio, aax all provide the previousFundingRate as well as the current rate in the same response

**Comment by kroitor** [comment]
@zsyh we will look into changing this naming for less confusion.

**Comment by zsyh** [comment]
@kroitor Thank you very much!


> That is not true, huobi, gateio, aax all provide the previousFundingRate as well as the current rate in the same response

@frosty00 Actually, you called  huobi, gateio, aax's `previousFundingRate`, in my definition, it is `fundingRate`. We distinguish `fundingRate` and `previousFundingRate` by if user has been charged.  In the current ccxt implementation, the meaning of huobi, gateio, aax's `previousFundingRate` and ftx's `nextFundingRate` is the same, representing the fundingRate that will be charged in the next 1-8hours.
> `fundingRate` means the fundingRate that will be charged in the next 1-8hours(or according to the exchange settings). fundingRate should never be None.

**Comment by zsyh** [comment]
I made a graph to explain this.  Suppose that the exchange charges the funding rate every 8 hours.
```
previousFundingRate                     fundingRate                      nextFundingRate
----------------------------current------------------- UTC00:00-------------------------------UTC08:00
```
