### ISSUE TITLE
how to get the historical data : futures : OpenInterest

### ISSUE THREAD

**Issue by lukaspistelak** [ccxt/ccxt#11309]
- OS: UBUNTU 18
- Programming Language version: Python 3.6.9
- CCXT version:

Hello 
I Would like to get the historical data of futures : OpenInterest
I tried this code :+1:  But I can get only actual data, is there way how to get historical data_?

```
exchange = ccxt.ftx({
    'enableRateLimit': True,  # required by the Manual https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    'apiKey': '',
    'secret': '',
    'options': {  # exchange-specific options
        'defaultType': 'future',  # switch to a futures API/account
    },
})

# print(dir(publicGetFuturesFutureNameStats))
print(exchange.fetch_funding_rate(symbol ='SOL-PERP',
                                  params = {'datetime'
                                            : '2022-01-05T16:00:00+00:00'})  )   # or fapiPrivate_get_positionrisk()
```

`{'info': {'volume': '2664893.06', 'nextFundingRate': '1e-6', 'nextFundingTime': '2022-01-13T17:00:00+00:00', 'openInterest': '2928044.18'}, 'symbol': 'SOL-PERP', 'markPrice': None, 'indexPrice': None, 'interestRate': 0.0, 'estimatedSettlePrice': None, 'timestamp': None, 'datetime': None, 'previousFundingRate': None, 'nextFundingRate': 1e-06, 'previousFundingTimestamp': 1642089600000, 'nextFundingTimestamp': 1642093200000, 'previousFundingDatetime': '2022-01-13T16:00:00.000Z', 'nextFundingDatetime': '2022-01-13T17:00:00.000Z'}`

**Comment by samgermain** [comment]
I checked the FTX API, and couldn't find an endpoint which would get the open interest history, so it looks like there's no way to get the open interest on FTX

It looks like binance has an open interest history method, so you can use the implicit api like

```
import ccxt
import sys
import json
from pprint import pprint

print('python', sys.version)
print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    "apiKey": '...',
    "secret": '...',
})

response = exchange.fapiDataGetOpenInterestHist({
    'period': '1h',
    'symbol': 'BTCUSDT',
})

pprint(response)
```

With a response that looks like 

```
 [
 {
 'sumOpenInterest': '75043.16800000',
  'sumOpenInterestValue': '3230165247.44480600',
  'symbol': 'BTCUSDT',
  'timestamp': '1642186800000'
  },
 {
 'sumOpenInterest': '74836.44900000',
  'sumOpenInterestValue': '3223139566.18335900',
  'symbol': 'BTCUSDT',
  'timestamp': '1642190400000'
  }
  ...
  ]
  ```

---------------------

I have also opened a PR for a unified open interest history method https://github.com/ccxt/ccxt/pull/11344 , but the output of it could change before it get's merged and as we look at adding this method to more exchanges as well. I would check back in a few weeks to see how this method is.
