### ISSUE TITLE
Bithumb 'easy trade' feature (specify amounts in quote currency)

### ISSUE THREAD

**Issue by Kamtsa** [ccxt/ccxt#1130]
This is not a bug, but either an enhancement request, or soliciting ideas for a work-around with current code. Some of the technical information should come from the exchange (Bithumb), but I hope someone here already knows. I could possibly ask Bithumb support for a minimal working example (like a curl snippet) if that would help, but unsure they'll understand.

The current function _create_market_buy_order_ takes two mandatory arguments, currency pair and amount. If no overriding, additional parameters are given the amount is the foreign currency (the one I receive in buy order), e.g. BTC in BTC/KRW. In the manual GUI Bithumb allows to specify either of BTC or KRW amount in _market order_, so that the _exact_ amount of KRW is being used. I can't achieve the same with a market order + BTC_notional, nor a limit_order + BTC_notional (at some higher limit price).

How can I replicate this GUI behaviour using ccxt, by specifying additional parameters (note, I don't know what these parameters should be for Bithumb, not the handing over of parameters in cxxt).

At the moment it is semi-automatic, where one step in the process is not done via API but manually in web GUI. Any help or ideas would be greatly appreciated!

- OS: linux
- Programming Language: Python 3.6 (through Anaconda & Jupyter notebook)
- CCXT version: 1.10.579 (from PyPI)
- Exchange: Bithumb
- Method: create_market_buy_order 

```
# example 1 (working market order) :
bithumb = ccxt.bithumb({"apiKey": XXX, "secret": XXX})
BTC_notional=0.01
bithumb.create_market_buy_order('BTC/KRW',BTC_notional)

# example 2 (what I would like to do - specify amount in domestic/base currency):
bithumb = ccxt.bithumb({"apiKey": XXX, "secret": XXX})
KRW_notional=5000
bithumb.create_market_buy_order('BTC/KRW',KRW_notional,{'payment_currency':'KRW'} ) # not working - idea only
```

**Comment by Kamtsa** [comment]
To give some more background on this: I'm using a poor work around by 'predicting' the amount in BTC to buy, in order to end up (close to) the amount of KRW originally intended. This is much less accurate than the manual web interface, that allows to enter the desired amount up to the Won (1 KRW ca 0.001 USD!). 

The problem in using ccxt to access Bithumb' API is the rounding applied to the BTC notional by the exchange. It appears to be 3 decimals. The rounding therefore introduces 'noise' on the order of 20000 KRW (@ 1BTC ~ 20 mio KRW). Is there a way around I'm not getting?

Running hundreds of trades over the day - the reasons I'm using the API - ends up with significant drift, and I need to construct additional 'even-up' trades further messing with my accounting. Anyone having any idea or tricks, I would love to hear!

**Comment by kroitor** [comment]
Hi! 

Unfortunately, this is only possible with their website. Their API is too restrictive on markets orders and does not allow to specify the total amount to spend in quote currency for market orders. Sorry for that, but we cannot workaround it, it's a limitation of the exchange API. 

You can still override all order params, including the amount, the price and other fields, to override precision-specific behaviour, etc...

Links:
- https://www.bithumb.com/u1/US127
- https://github.com/ccxt/ccxt/wiki/Manual#custom-order-params

Let us know if this does not answer your question. Feel free to reopen this id needed, or just ask questions, if any.
