### ISSUE TITLE
Hitbtc getDepositAddress and createDepositAddress in python error & fix

### ISSUE THREAD

**Issue by speggos** [ccxt/ccxt#1131]
In your python library, file hitbtc2.py, in methods fetch_deposit_address and create_deposit_address you called a function that doesn't exist.

You wanted to call this function:
currencyId = self.common_currency_code(currency)

Instead you called:
currencyId = self.currencyId(currency)

Very small fix, don't know how to fix this myself (except locally) but it's a 2 line fix. Works fine once you change that function call.

Thanks for all you've done here mate!

Here is your full code:

def create_deposit_address(self, currency, params={}):
        currencyId = self.currencyId(currency)
        response = self.privatePostAccountCryptoAddressCurrency({
            'currency': currencyId,
        })
        address = response['address']
        return {
            'currency': currency,
            'address': address,
            'status': 'ok',
            'info': response,
        }

    def fetch_deposit_address(self, currency, params={}):
        currencyId = self.currencyId(currency)
        response = self.privateGetAccountCryptoAddressCurrency({
            'currency': currencyId,
        })
        address = response['address']
        return {
            'currency': currency,
            'address': address,
            'status': 'ok',
            'info': response,
        }

**Comment by kroitor** [comment]
Fixed in 1.10.599, thank you!
