### ISSUE TITLE
Missing method fetch_order in huobipro

### ISSUE THREAD

**Issue by cointime** [ccxt/ccxt#1132]
fetch_order() is not implemented yet for exchange huobipro. We need this method to track the order status. huobipro exchange does support this method: GET /v1/order/orders/{order-id}.
Can you implement this method in the next release?

- OS: Win10
- Programming Language: python
- CCXT version: 1.10.599
- Exchange: huobipro
- Method: fetch_order

```
↑↑↑ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE

hb = ccxt.huobipro()
hb.fetch_order('123456')

ccxt.base.errors.NotSupported: huobipro fetch_order() is not implemented yet

↓↓↓ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE
```

**Comment by kroitor** [comment]
> Can you implement this method in the next release?

Yes, we can, however, we've got a lot of tasks already, so, your contributions are welcome!
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

**Comment by kroitor** [comment]
@cointime in the meantime you can use the Huobi's custom API which is implemented in ccxt, by doing this:

```Python
import ccxt
exchange = ccxt.echange({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
exchange.private_get_order_orders_id({ 'id': 'YOUR_ORDER_ID' })
```

Hope it helps.

**Comment by cointime** [comment]
Thanks!
