### ISSUE TITLE
lykke ohclv 1m timeframe 2 hours behind??

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#11326]
I don't understand why my ohclv request is 1 hours behind using lykke exchange. But fetch_ticker() looks current..

?

**Comment by ttodua** [comment]
Hi.
I think you made a mistake in exchange name when you posted, because they don't have a method to get OHLCV data at all:
https://github.com/ccxt/ccxt/blob/master/js/lykke.js#L27
neither 'api' links written in the file are valid anymore (those pages are now 404).

@kroitor Any thoughts?
on https://lykke.com/wallet/api/ page, they have other 'updated' links:
- https://lykkecity.github.io/Trading-API/#lykke-high-frequency-trading-api (HFT v2)
- https://public-api.lykke.com/swagger/ui/ (public api, just as it, without any version title, but link suggest 'v1')

**Comment by kroitor** [comment]
@ttodua when the exchange does not have a OHLCV history, then OHLCV emulation takes place: https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L815
SInce the emulated OHLCVs are built from trades, that should explain why certain OHLCVs are lagging in time – cause they're built from historical trades that might not happen very often with this or that exchange.

**Comment by kroitor** [comment]
@adamrg73 let us know if the above does not answer your question, feel free to reopen it if necessary, or just ask further questions if any.

**Comment by ttodua** [comment]
@kroitor what about the links I've posted above? I am working for lykke js atm, and should I replace the API links, and also, implement the candles endpoint from the another api destination?

**Comment by ttodua** [comment]
oh, that PR mentions another link: https://hft-apiv2.lykke.com/swagger/ui/index.html which is not found on lykke homepage/pages at all.  so, they have 3 API docs atm?

**Comment by kroitor** [comment]
We will have to check for their announcements and posts to figure which of the APIs is the most recent set, or implement all of them. I'm not sure if they have a v3 API yet – that has to be investigated.

**Comment by kroitor** [comment]
@ttodua most often we need the API version that is linked from the main website of the exchange.

**Comment by ttodua** [comment]
I mean not v3, but multiple different pages for their api (some are on swagger, some on github). ok, so, I'll leave this topic atm, and if we decide to integrate lykke new one, lmk.

**Comment by adamrg73** [comment]
how do i get ohlcv data with lykke?
I think theyre using v2 mainly, but there's gota be a way to get it with v1.
I just need easiest method if anyone has a good method here.
thanks

**Comment by ttodua** [comment]
@adamrg73 please look in CCXT's [ImplicitApi approach](https://docs.ccxt.com/en/latest/manual.html#implicit-api) , and you can use any endpoint that Lykke (or any exchange) has , using that approach:
```
    let ex = new ccxt.lykke({..});
    await ex.loadMarkets();
    const params = {
        market: 'spot',
        assetPair: ex.marketId('BTC/USD'),
        period: ex.timeframes['5m'],
        type: 'Trades',
        from: ex.iso8601( 1640000000000 ),
        to: ex.iso8601( 1641000000000 )
    }
    console.log( await ex.mobileGetCandlesHistoryMarketAssetPairPeriodTypeFromTo(params) );
```

**Comment by adamrg73** [comment]
how come when i insert code with insert code function here it never comes out right

**Comment by adamrg73** [comment]
will that function work ex.mobileGetCandlesHistoryMarketAssetPairPeriodTypeFromTo(params)
if i rewrite in python, i need it in python otherwise gota install node js on this server.

**Comment by adamrg73** [comment]
`import ccxt
ex = ccxt.lykke({})

ex.load_markets()

params = {
        'market': 'spot',
        'assetPair': ex.marketId('BTC/USD'),
        'period': ex.timeframes['1m'],
        'type': 'Trades',
        'from': ex.iso8601( 1640000000000 ),
        'to': ex.iso8601( 1645000000000 )
    }
print(ex.mobileGetCandlesHistoryMarketAssetPairPeriodTypeFromTo(params))`

ccxt.base.errors.ExchangeNotAvailable: GET https://public-api.lykke.com/api/Candles/history/spot/BTCUSD/Minute/Trades/2021-12-20T11:33:20.000Z/2022-02-16T08:26:40.000Z 400 Bad Request {"code":1,"msg":"The value 'Minute' is not valid."}

**Comment by kroitor** [comment]
> how come when i insert code with insert code function here it never comes out right

Use github markdown: 

- https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

Wrap a word in a single backtick (\`) to highlight it within a sentence, like `this`.
Wrap your code and text output with triple backticks (\`\`\`). 
Don't confuse three backticks (\`\`\`) with three quotes (\'\'\').

\`\`\`Python

YOUR PYTHON CODE HERE

\`\`\`


\`\`\`

YOUR TEXT HERE

\`\`\`

**Comment by adamrg73** [comment]
how come yours has color coding mine doesnt I just did it above.

**Comment by kroitor** [comment]
@adamrg73 that is because I added the language `Python` after the first three opening backticks in my snippet.

\`\`\`Python

YOUR PYTHON CODE

\`\`\`

**Comment by adamrg73** [comment]
> @adamrg73 that is because I added the language `Python` after the first three opening backticks in my snippet.
> 
> ```Python
> 
> YOUR PYTHON CODE
> 
> ```

cool
nice 
thx

**Comment by adamrg73** [comment]
I had to use my own custom get ticker convert to dataframe and resample method for this lykke project btw.. as the above code ttodua supplied in js, I converted to python irrelevant but 1 minute doesnt work, his 5minute works..
dont know why

**Comment by ttodua** [comment]
@adamrg73 1 minute is not supported interval on lykke,that should be problem. have you tried your code with `Min5` param instead of `Minute`? it should have worked. (To see available/supported timeframes, once again, look into `lykke.py` class, under `timeframes` values)
