### ISSUE TITLE
CCXTPRO is just going FREE all the sudden?

### ISSUE THREAD

**Issue by eL-Squaz** [ccxt/ccxt#11325]
WHY is PRO going free in Q3??

I'm not sure exactly when I paid for 12 months annual, but if it was to end after the beginning for Q3, will I be getting refunded (prorate)? 

not that the money is the issue.. Is ccxt/ccxtpro just going to stop being maintained? just completely Open-source?

**Comment by kroitor** [comment]
> WHY is PRO going free in Q3??

We don't have to fund the work on it with paid licenses anymore.

> I'm not sure exactly when I paid for 12 months annual, but if it was to end after the beginning for Q3, will I be getting refunded (prorate)?

Yes, please, contact info@ccxt.trade with your order id.

> not that the money is the issue.. Is ccxt/ccxtpro just going to stop being maintained? 

Nope, it's the opposite – it will become even better maintained. We've expanded the team of developers recently.

> just completely Open-source?

Yes, but that doesn't mean it will less maintained, in fact, it will be improved faster and will remain well-maintained and supported as a part of CCXT.

Hope that answers your questions, let us know if not.

**Comment by eL-Squaz** [comment]
it does.. i guess it's more just that its not exclusive anymore is what seems to be the down side.. a lot more competition..

**Comment by frosty00** [comment]
@eL-Squaz btw we don't have any release date so it could take a year to go public, we might also restrict all new subscriptions to ccxtpro beyond a certain date soon

**Comment by frosty00** [comment]
we're working on fixing and optimizing some of ccxtpro before we make a public release

**Comment by eL-Squaz** [comment]
i see.. thank you.. will there be a possible new version or new project
dedicated towards a DeFi Version? I would like to help, if so.
