### ISSUE TITLE
Binance wrong prices watchTicker

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#11331]
We have noticed that on watchTicker method after long socket connection and on high volatility period on Binance (Spot, USDT-M, COIN-M), there is a problem that `ask, bid and last` prices values received like from the past. 

In example DOGE/USDT (Binance Futures USDT-M) pair on high volatility period we receive from the sockets incorrect data:

ask: 0.19361
bid: 0.19361
last: 0.19361
timestamp:"1642149272431"

ask: 0.19584
bid: 0.19584
last: 0.19584
timestamp:"1642146769928"

ask: 0.19582
bid: 0.19582
last: 0.19582
timestamp:"1642146775418"

By this example you can see that data received from the past and in chaotic sequence because we logging that example data approximately from the 9:45 to 9:52 (UTC+0) and upper example is the first one that we logged.

But if we use REST fetchTickers method or if we recreate `binance` ccxt.pro instance then all prices is correct.

In our case we take prices from `tickers` collection maybe that is the case.

Schematically we have two methods running asynchronous - one for tickers watching and reconnect `watchTickers`
and another for tickers processing `processTickers`.

```
const ccxt = require ('ccxt.pro');
const exchange = new ccxt['binance'] (
    {
        'options': {
            'defaultType': "future"
        }
    }
);

async function watchTickers(symbols) {
    while (true) {
        for (let symbol of symbols) {
            try {
                var res = await exchange.watchTicker(symbol);
            }
            catch (err) {
                console.log(err);
            }
        }

        await sleep(1000);
    }
}

async function processTickers(symbols) {
    while(true) {
        for (let symbol of symbols) {
            let ticker = exchange.tickers[symbol];

            if (!ticker) {
                continue;
            }

            console.log(`------ ${symbol} -------`);

            console.log('bid: ' + ticker.bid);
            console.log('ask: ' + ticker.ask);
            console.log('last: ' + ticker.last);
            console.log('timestamp: ' + ticker.timestamp);

            // Do app specific logic ...
        }

        await sleep(1000);
    }
}

watchTickers(['DOGE/USDT']);
processTickers(['DOGE/USDT']);

function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}
```

- OS: Debian (Docker)
- Programming Language version: NodeJS, JavaScript
- CCXT version: PRO 0.9.35

**Comment by kroitor** [comment]
@wunderb1t thanks for reporting, I will try to reproduce and will investigate. In the meantime, if you could enable verbose mode and check if the verbose output contains something suspicious – that would really help resolve it faster. Thx again!
