### ISSUE TITLE
[BUDA] ccxt fetching wrong ohlcv values in daily candles

### ISSUE THREAD

**Issue by luispsa** [ccxt/ccxt#11333]
Hi, I have the following issue, when I try to get daily candles from this exchange, ccxt fetch candles with random minutes of difference instead of 24 hours of difference.

- OS: Windows 10 x64
- Programming Language version: Python 3.9.7
- CCXT version: 1.67.71

```
import ccxt
import pandas as pd
import numpy as np
import keys
from datetime import datetime as dt

try:
    buda_ex= ccxt.buda({
    'apiKey': keys.api_key_buda,
    'secret': keys.api_secret_buda,
    'password' : keys.buda_pw,
    'enableRateLimit': True
    })
except Exception as e: 
    print("No se puede cargar el exchange buda, un error ha ocurrido - {}".format(e))

print(buda_ex.timeframes)

btc_clp=buda_ex.fetch_ohlcv(symbol="BTC/CLP", timeframe="1d", limit=10)

df = pd.DataFrame(btc_clp, columns = ['OPEN TIME', 'OPEN', 'HIGH', 'LOW', 'CLOSE', 'VOLUME'])
df['OPEN TIME'] = pd.to_datetime(df['OPEN TIME'], unit='ms')
df["OPEN TIME"]=df["OPEN TIME"].apply(lambda x: dt.strftime(x,'%d-%m-%y %H:%M'))
df['OPEN'] = df['OPEN'].astype(np.float64)
df['HIGH'] = df['HIGH'].astype(np.float64)
df['LOW'] = df['LOW'].astype(np.float64)
df['CLOSE'] = df['CLOSE'].astype(np.float64)
df['VOLUME'] = df['VOLUME'].astype(np.float64)
df.set_index('OPEN TIME', inplace=True)

print(df.head())
```

```
{'1m': '1', '5m': '5', '30m': '30', '1h': '60', '2h': '120', '1d': 'D', '1w': 'W'}

                     OPEN        HIGH         LOW       CLOSE    VOLUME
OPEN TIME                                                               
13-01-22 13:38  36626148.0  36626148.0  36381357.0  36381357.0  0.051374
13-01-22 13:41  36383854.0  36611000.0  36383854.0  36611000.0  0.002366
13-01-22 13:45  36597909.0  36597909.0  36597909.0  36597909.0  0.000473
13-01-22 13:46  36386350.0  36386350.0  36385998.0  36386350.0  0.052687
13-01-22 13:48  36589881.0  36589881.0  36387083.0  36387083.0  0.055930
```

**Comment by ttodua** [comment]
I am unable to test the exchange, it sits behind cloudflare and all my requests are denied (DDoS protection by cloudflare). I don't know if it's related to location, but I'll try with other locations and post update here.

**Comment by luispsa** [comment]
> I am unable to test the exchange, it sits behind cloudflare and all my requests are denied (DDoS protection by cloudflare). I don't know if it's related to location, but I'll try with other locations and post update here.

Hi @ttodua, this exchange is located in chile, but it works in others latam countries like peru and argentina, I didn't know it has regional blocking, maybe using a latam ip it should allow access to api, yesterday I sent a message to buda's TI support , but they couldn't help me...

regards

**Comment by ttodua** [comment]
After some research, we found that the exchange doesn't have a consistent API endpoint for candles, and has an unplanned behavior- depending on different timespan between from-to (nevertheless the requested timeframe) the responses are different. 
It will need a serious rework of that implementation, to achieve a normal-functional method. 
This will be marked as 'todo' however, in the meanwhile, I'd also suggest you wrote their support (as a customer) and requested that they implemented endpoint for fetching Candles.

**Comment by luispsa** [comment]
> 

thanks for the valuable info @ttodua , I will reach this to their IT support about the behavior of the api's responses, in my personal case, with other time frames I didn't have problems fetching the candles (2h,1h), the daily candles have this random behavior.

regards

**Comment by ttodua** [comment]
@luispsa yes, it has not correct implementation at this moment. To give a few examples:
```
To name example, the timeframe(resolution) parameter doesnt make sense sometimes, but sometimes has:
- https://www.buda.com/api/v2/tv/history?symbol=BTC-CLP&from=1642523025&to=1642524325&resolution=1 //utilizes
- https://www.buda.com/api/v2/tv/history?symbol=BTC-CLP&from=1642523025&to=1642524325&resolution=2 //utilizes
- https://www.buda.com/api/v2/tv/history?symbol=BTC-CLP&from=1642523025&to=1642524325&resolution=D // ignored, returns to default
- https://www.buda.com/api/v2/tv/history?symbol=BTC-CLP&from=1642523025&to=1642524325&resolution=BLABLA //ignored, returns to default

however, if you just change the from parameter to i.e. 0, then the timeframe parameters still doesn't make sense:
- https://www.buda.com/api/v2/tv/history?symbol=BTC-CLP&from=0&to=1642524325&resolution=1  // ignored
- https://www.buda.com/api/v2/tv/history?symbol=BTC-CLP&from=0&to=1642524325&resolution=2   // ignored
- https://www.buda.com/api/v2/tv/history?symbol=BTC-CLP&from=0&to=1642524325&resolution=D   //  ??
- https://www.buda.com/api/v2/tv/history?symbol=BTC-CLP&from=0&to=1642524325&resolution=BLABLA   //  ignored, returns to default
```
So, they need to implement the working api endpoint for candles, which will react on parameters correctly, and not in a broken-way.

**Comment by ttodua** [comment]
buda had been delisted from ccxt in the past.
