### ISSUE TITLE
New Exchange: Bisq

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1134]
api doc: https://markets.bisq.network/api/

address: N/A
company: bisq foundation
type: decentralised ex

note: I think sooner or later. this platform will coming more popular as people tend to use decentralize exchange platforms. Currently working with the api and its doc followed by [this conversations](https://bisq.community/t/is-there-a-any-restful-api/4350/3). This project is under beta testing with alot of roadmap development and it will take at least in my estimation of 6 months to go into town, here its a [java implementation](https://github.com/mrosseel/bisq-api) found from the research. Its the OTC platforms help fiat banks to crypto

**Comment by kroitor** [comment]
> Will you consider this as one of the api access option?

Yes, we will integrate it.

**Comment by jjhesk** [comment]
yes, so this is the answer. I think bisq itself should have a new struct or an interface for it because more poeple will run its own on their machine.

**Comment by jjhesk** [comment]
other notes and examples: 
https://mrosseel.github.io/bisq-api-examples/, https://github.com/mrosseel/bisq-proposals/blob/api-proposal/http-api.adoc, https://github.com/bisq-network/docs/blob/master/dao/specification.adoc

**Comment by jjhesk** [comment]
the api is finally released.

**Comment by electic** [comment]
Hi everyone, is there any updates on this? This exchange has become quite popular.

**Comment by fredfortier** [comment]
Is anyone currently working on this integration?

**Comment by frosty00** [comment]
not being worked on

**Comment by rafa-br34** [comment]
Are there any plans to reopen the issue?
