### ISSUE TITLE
Bybit - closing futures position not working - reduce_only not being sent/set/ignored by exchange

### ISSUE THREAD

**Issue by websa24** [ccxt/ccxt#11360]
- Programming Language version: PHP 7.2
- CCXT version: 1.66.44

Im trying to CLOSE a futures trade on Bybit, in the parameters array, I have set reduce_only => true, but it seems Bybit exchange is ignoring it or its not being sent. returned result open a short position instead of closing the long position, also in the result, reduce_only == false, while I have set it as true.

code to close a long position :

           $result = $exchange->create_order ($pair, 'market', 'sell', 10, array ('reduce_only' => true));
           dd($result);

$result :

array:22 [▼
  "info" => array:23 [▼
    "order_id" => "xxxxxxxx"
    "user_id" => "xxxxxxx"
    "symbol" => "EOSUSDT"
    "side" => "Sell"
    "order_type" => "Market"
    "price" => "2.78"
    "qty" => "10"
    "time_in_force" => "ImmediateOrCancel"
    "order_status" => "Created"
    "last_exec_price" => "0"
    "cum_exec_qty" => "0"
    "cum_exec_value" => "0"
    "cum_exec_fee" => "0"
    **"reduce_only" => false**
    "close_on_trigger" => false
    "order_link_id" => ""
    "created_time" => "2022-01-15T21:16:51Z"
    "updated_time" => "2022-01-15T21:16:51Z"
    "take_profit" => "0"
    "stop_loss" => "0"
    "tp_trigger_by" => "UNKNOWN"
    "sl_trigger_by" => "UNKNOWN"
    "position_idx" => "2"
  ]
  "id" => "xxxxxxxxxxx"
  "clientOrderId" => null
  "timestamp" => null
  "datetime" => null
  "lastTradeTimestamp" => null
  "symbol" => "EOS/USDT"
  "type" => "market"
  "timeInForce" => "IOC"
  "postOnly" => false
  "side" => "sell"
  "price" => 2.78
  "stopPrice" => null
  "amount" => 10.0
  "cost" => 0.0
  "average" => null
  "filled" => 0.0
  "remaining" => 10.0
  "status" => "open"
  "fee" => array:2 [▼
    "cost" => "0"
    "currency" => "USDT"
  ]
  "trades" => []
  "fees" => array:1 [▼
    0 => array:2 [▼
      "cost" => 0.0
      "currency" => "USDT"
    ]
  ]
]

**Comment by kroitor** [comment]
You are missing the argument count of create_order.
Your `params` overrides with `reduce_only` should be the 6th argument, not the 5th argument.
The 5th argument is the price and you should leave it `null` for market orders:

- https://github.com/ccxt/ccxt/blob/master/php/bybit.php#L1676

```PHP
       $result = $exchange->create_order ($pair, 'market', 'sell', 10, null, array ('reduce_only' => true));
       dd($result);
```
