### ISSUE TITLE
method for simple summary of the market

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1138]
is there a simple method call for the current BTC/USD price averaging from all platforms? i think it is quite important.

**Comment by kroitor** [comment]
> is there a simple method call for the current BTC/USD price averaging from all platforms?

Currently, there is no such method. All methods are described here: https://github.com/kroitor/ccxt/wiki/Manual

> i think it is quite important.

It is, but implementing it would require a trading platform + db + a serious infrastructure. This is beyond the scope of this library and we let the user decide on that. Hope it answers your question. Thx!

**Comment by jjhesk** [comment]
ok. its a fair answer.
