### ISSUE TITLE
How to transfer all of one token to another at market price using API?

### ISSUE THREAD

**Issue by cdcv** [ccxt/ccxt#11383]
What is the best way to transfer 100% of the holdings in an account in one currency (eg BTC) to another (eg ETH), using the exchange api (currently using Gemini, but it's a general question).
Running into many problems in trying to accomplish this:
1) Exchange seems to want amount to be in the currency that the transfer is being made TO, rather than the currency the transfer is being made from.  Given that it's not clear what price will be received, how do you transfer the entire amount?  In trying to compute the correct amount, both the current price, spread, and fees all need to be take into consideration?
2) Exchange doesn't allow market orders, only limit, making it challenging to know what price to use, esp if prices are moving rapidly.
2a) When setting a price outside the current spread to try to get it to execute immediately, the order was cancelled immediatelyget an error from the exchange that the order can't be placed "ExceedsPriceLimits'
3) Is it possible to issue a change order, eg to change the price, or only to first cancel the existing order and then place a separate new order?

Thank you for your help.

**Comment by kroitor** [comment]
> What is the best way to transfer 100% of the holdings in an account in one currency (eg BTC) to another (eg ETH), using the exchange api (currently using Gemini, but it's a general question). Running into many problems in trying to accomplish this:

> 1. Exchange seems to want amount to be in the currency that the transfer is being made TO, rather than the currency the transfer is being made from.  Given that it's not clear what price will be received, how do you transfer the entire amount?  In trying to compute the correct amount, both the current price, spread, and fees all need to be take into consideration?

I would suggest reading the CCXT Manual from top to bottom and sticking to the terms suggested there:

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://docs.ccxt.com/en/latest/manual.html#consistecy-of-base-and-quote

Spot market amounts are always in base currency. Prices are always in quote currency. Order costs are also in quote currency. So, `cost = amount * price`.

In general, with spot markets you have two types of orders:

1. market orders
2. limit orders

Market orders require an amount in base currency (supported with most of the exchanges). If you're selling or buying BTC for USDT with a BTC/USDT spot market, then you have to specify the base amount of BTC you want buy or sell.

Limit orders will require an amount in base currency (BTC) and a price in quote currency (USDT per BTC).

Sometimes, the exchanges have a specific rule for market-buys, that requires an amount in quote currency USDT or a total cost of the order in USDT (how much USDT to spend for buying or selling BTC). That is handled with the `createMarketBuyRequiresPrice` option, as described in the Manual here: https://github.com/ccxt/ccxt/wiki/Manual#market-buys

Some exchanges, don't support market orders, accepting limit orders only. In that case a market order can often be emulated by adjusting the `price` of a limit order as described here: https://github.com/ccxt/ccxt/wiki/Manual#emulating-market-orders-with-limit-orders

> 2. Exchange doesn't allow market orders, only limit, making it challenging to know what price to use, esp if prices are moving rapidly.

Welcome to the global trading competition ) Prices do fluctuate, so you have to be specific.

>    2a) When setting a price outside the current spread to try to get it to execute immediately, the order was cancelled immediatelyget an error from the exchange that the order can't be placed "ExceedsPriceLimits'

Fetch the current market information (orderbook depth with prices and volumes) to calculate the price and immediately place the order to avoid price fluctuations as much as possible. Read the Manual on the rate limiting and control it:

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://docs.ccxt.com/en/latest/manual.html#notes-on-rate-limiter

> 3. Is it possible to issue a change order, eg to change the price, or only to first cancel the existing order and then place a separate new order?

Some exchanges will have a `exchange.has['editOrder'] === true`. Other exchanges will have `exchange.has['editOrder'] === emulated`. If the exchange does not have a true API endpoint for editing live orders, then CCXT emulates the order editing by canceling one order and placing another order. Some exchanges actually replace the orders inside their engines, so after editing an order, a new order might have a new order id.

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata
- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L1530
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L2177
- https://github.com/ccxt/ccxt/blob/master/php/Exchange.php#L2566

Hope that answers your question, let us know if not.

**Comment by cdcv** [comment]
Thank you very much for your very detailed, thorough, and quick reply.  Very, very helpful.  One clarification that I think might be helpful, and perhaps for others in the future as well.  You comment that "Prices are always in quote currency."  Prices, by their nature, are the ratio of two values, eg five lemons for one Euro, 50k USD / 1 BTC, etc.  Is the correct nomenclature within ccxt that a price is typically in units of quote currency / base currency (is this what you meant?), or base currency / quote currency, or does it vary by exchange?  Read the docs carefully on this point, but am still not clear.  Thanks again.

**Comment by kroitor** [comment]
@cdcv with the majority of the exchanges the spot symbol is `BTC/USDT` or `BTC/USD` = base/quote = amount/price. It is not a ratio of 1BTC/50k USD, though. It is a symbolic representation of a trading pair, not an arithmetic formula. What it actually means is _"50k USD (quote) per 1 BTC (base)"_.
