### ISSUE TITLE
Unable to fetch perpetual futures from ftx through load_markets()

### ISSUE THREAD

**Issue by helpme1** [ccxt/ccxt#11392]
I am not able to fetch perpetual futures from ftx exchange through load_markets(). There wasn't any problem last month but this problem started to happen a few weeks ago.

```
exchange_id = "ftx"
exchange = getattr(ccxt, exchange_id)({
    'enableRateLimit': True,  # required by the Manual
})
markets_dict = exchange.load_markets()
symbol_list = list(markets_dict.keys())
```
No perpetual contracts can be found in `symbol_list`.

I am using Windows 10, python v3.9 and ccxt 1.68.25.

**Comment by kroitor** [comment]
@helpme1 read this: https://github.com/ccxt/ccxt/issues/10931

```Python
import ccxt
exchange = ccxt.ftx()
markets = exchange.load_markets()
for symbol in exchange.symbols:
    market = exchange.market(symbol)
    print(market['id'], symbol, market['type'])
```
