### ISSUE TITLE
New Exchange Request: Trade Ogre

### ISSUE THREAD

**Issue by Shazman96** [ccxt/ccxt#11412]
Trade Ogre is apparently super popular among some users in the crypto space. It would be neat to integrate them into CCXT.

They have API docs located here: https://tradeogre.com/help/api

**Comment by kroitor** [comment]
Duplicate: 

- https://github.com/ccxt/ccxt/issues/2150

You can build and test it here:

- https://github.com/ccxt/ccxt/pull/3774

**Comment by ttodua** [comment]
was added in ccxt
