### ISSUE TITLE
Having execution price issue in bybitfutures

### ISSUE THREAD

**Issue by vishalsahu2501** [ccxt/ccxt#11446]
- OS: **Local Environment**
- Programming Language version: **NodeJs v14.0.0**
- CCXT version:  **1.68.53**

Derivatives: **USDT Perpetual**
Exchange: **bybit**
defaultType: **futures**

**(Too much price difference while closing an open position)**
**Request Sent:**
**========================================**

fetch Request:
 bybit POST https://api.bybit.com/private/linear/order/create 

RequestHeaders:
{Content-Type: "application/json"}
 
RequestBody:
{"side":"Sell","symbol":"FLOWUSDT","order_type":"Market","qty":6.8,"time_in_force":"GoodTillCancel","reduce_only":true,"close_on_trigger":false,"api_key":"XXXXXXXXXXXXXXX","recv_window":5000,"timestamp":1642592265335,"sign":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"} 

### Important: **At this time Price(current) for FLOWUSDT at bybit exchange is 7.26**

**Response received:**
**========================================**
ResponseBody:
{"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":{"order_id":"XXXXXXXXXXXXXXXX","user_id":XXXXXX,"symbol":"FLOWUSDT","side":"Sell","order_type":"Market","price":6.87,"qty":6.8,"time_in_force":"ImmediateOrCancel","order_status":"Created","last_exec_price":0,"cum_exec_qty":0,"cum_exec_value":0,"cum_exec_fee":0,"reduce_only":true,"close_on_trigger":true,"order_link_id":"","created_time":"2022-01-19T11:37:44Z","updated_time":"2022-01-19T11:37:44Z","take_profit":0,"stop_loss":0,"tp_trigger_by":"UNKNOWN","sl_trigger_by":"UNKNOWN","position_idx":1},"time_now":"1642592264.745885","rate_limit_status":99,"rate_limit_reset_ms":1642592264740,"rate_limit":100}

**Comment by vishalsahu2501** [comment]
**Inshort the closeprice we are getting in response while closing position is not correct**

I have highlighted close price in the response **(open position)**
**======================================**

![image](https://user-images.githubusercontent.com/45059136/150318638-21ec358f-7ba3-44d0-8fde-d769d34913d9.png)





**(Close Position)**
**======================================**

![image](https://user-images.githubusercontent.com/45059136/150318847-a674b265-798a-4f1d-bb41-e7fb6e5fdc5f.png)

**Comment by kroitor** [comment]
@vishalsahu2501 you can see from your screenshot, that the price is taken from `order['info']` which contains the exchange response as is, untouched. So if that value is incorrect, you might want to ask the exchange about it. CCXT does not adjust that price. If you see 1.2285 there – that is the value coming from the exchange directly. Let us know if that does not answer your question. Feel free to reopen it or just ask further questions if any.
