### ISSUE TITLE
load markets for poloniex returns the base BTM as bitmark

### ISSUE THREAD

**Issue by MarkLuds** [ccxt/ccxt#1147]
Hi,

This is a really well put together library. I love it. So first of all thanks for that, will definitely be doing some sort of supporting/backing this. 
So...
This method is currently returning bitmark as the name not the code i.e:
[Bitmark/BTC] 
the base is also returned as Bitmark

- OS:
- Programming Language: PHP
- CCXT version:  Not sure where to find this. downloaded around 01/01/2018
- Exchange: poloniex
- Method: load_markets 

```

$apis['poloniex'] = new \ccxt\poloniex (array ('verbose' => true)); // log HTTP requests
$markets = $apis['poloniex']->load_markets ();
print_r($markets);

```

**Comment by kroitor** [comment]
Hi!

BTM is the code for Bytom (HitBTC and coinmarketcap). Poloniex has a different token under that same standard code. BTM on Poloniex is Bitmark.

- https://github.com/ccxt/ccxt/issues/348 ← explained here
- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
- https://github.com/ccxt/ccxt/wiki/Manual#naming-consistency

Hope it helps.
