### ISSUE TITLE
bitstamp: rather use v2/xrp_withdrawal for XRP withdrawal

### ISSUE THREAD

**Issue by agroszer** [ccxt/ccxt#1150]
ripple_withdrawal craps out with 
```
response: 
	{'error': u'Missing amount and/or address and/or currency POST parameters'}
```
```
request is {'amount': 1, 'destination_tag': 'xxx', 'address': u'xxx'}
```

- OS: ubuntu
- Programming Language: python 2.7
- CCXT version: 1.10.621
- Exchange: bitstamp
- Method: withdraw

**Comment by kroitor** [comment]
It's is fixed in one of the pull-requests, and we are going to merge it soon: https://github.com/ccxt/ccxt/pull/1041

**Comment by agroszer** [comment]
thanks!
