### ISSUE TITLE
mexc candles data dosen't have 1w data , please remove the key from options

### ISSUE THREAD

**Issue by a5601564** [ccxt/ccxt#11519]
mexc dosen't have 1w data , please remove the key from options ,or it wills cause a mistake.

![image](https://user-images.githubusercontent.com/17686185/150294399-20ab059c-9012-4451-8313-8af73a0ad833.png)

**Comment by a5601564** [comment]
in the   'timeframes': {
                '1m': '1m',
                '5m': '5m',
                '15m': '15m',
                '30m': '30m',
                '1h': '1h',
                '1d': '1d',
                '1w': '1w',
                '1M': '1M',
            },

**Comment by a5601564** [comment]
At last, i don't  solve it out . i think ,after exchange inited itself and it know it's type. timeframes should switch to it's relative timeframes.

**Comment by kroitor** [comment]
We have removed the 1w timeframe from MEXC in CCXT 1.68.78+, the new build will arrive in ~20 minutes.

**Comment by a5601564** [comment]
![image](https://user-images.githubusercontent.com/17686185/150297588-1d5651c1-3ebf-44e2-b84b-03a163e48f17.png)

i read the code , init's timeframes  is a result from two trye.
so simply delete '1w' , it maybe  not the best way.

should it ,after inited itself , switch  it's timeframes to the right type ?

**Comment by kroitor** [comment]
> should it ,after inited itself , switch it's timeframes to the right type ?

Unfortunately, there's no "right" type, both spot and contracts must be supported which is why I will probably restore 1w there.

**Comment by a5601564** [comment]
fbinance.options['defaultType'] = 'future' 
such like this . 
when it is  a contracts , it need to set to   'future' .
maybe it can be done  in load_market function or  after load_market function  .
