### ISSUE TITLE
UUID_INVALID (PHP & Bittrex)

### ISSUE THREAD

**Issue by mohammadwillwin** [ccxt/ccxt#1152]
Trying to get my orders from Bittrex. Tried creating a fresh new API key with the required permissions enabled, but I still get UUIID_INVALID. Tried even changing the symbols to none, ETH/BTC and BTC/ETH but still no luck.

I hid my secret key from the code, by the way.

- OS: Windows 10
- Programming Language: PHP
- CCXT version: 1.10.621
- Exchange: Bittrex
- Method: fetch_order

```
<?php 

include "assets/import/ccxt/ccxt.php";
$bittrex = new \ccxt\bittrex (array ('apiKey' => '636b6210a3e8472b80820ccaf76967ec','secret' => 'XXX'));

echo '<pre>';


print_r($bittrex->fetch_order('bittrex','ETH/BTC'));


echo '</pre>';

?>


Fatal error:  Uncaught exception 'ccxt\ExchangeError' with message 'bittrex {"success":false,"message":"UUID_INVALID","result":null}' in C:\xampp\htdocs\assets\import\ccxt\php\bittrex.php:687
Stack trace:
#0 [internal function]: ccxt\bittrex->request('order', 'account', 'GET', Array)
#1 C:\xampp\htdocs\assets\import\ccxt\php\Exchange.php(644): call_user_func(Array, 'order', 'account', 'GET', Array)
#2 [internal function]: ccxt\Exchange->ccxt\{closure}(Array)
#3 C:\xampp\htdocs\assets\import\ccxt\php\Exchange.php(1460): call_user_func_array(Object(Closure), Array)
#4 C:\xampp\htdocs\assets\import\ccxt\php\bittrex.php(536): ccxt\Exchange->__call('accountGetOrder', Array)
#5 C:\xampp\htdocs\assets\import\ccxt\php\bittrex.php(536): ccxt\bittrex->accountGetOrder(Array)
#6 C:\xampp\htdocs\test.php(9): ccxt\bittrex->fetch_order('bittrex', 'ETH/BTC')
#7 {main}
  thrown in C:\xampp\htdocs\assets\import\ccxt\php\bittrex.php on line 687


```

**Comment by kroitor** [comment]
> Trying to get my orders from Bittrex.

Use fetchOpenOrders, fetchClosedOrders instead of fetchOrder. The fetchOrder method, that you are calling is for fetching a single order by id.

https://github.com/ccxt/ccxt/wiki/Manual#querying-orders

**Comment by mohammadwillwin** [comment]
Thank you.

For some reason, it doesn't get my full order for a coin?

This is my code:
`print_r($bittrex->fetchClosedOrders('ADA/BTC'));`

result:
`Array
(
)
`

Bittrex order history of that coin:
https://i.imgur.com/vynjMr2.png

**Comment by mohammadwillwin** [comment]
It did get my current open order on that coin with fetchOpenOrders though, nothing else.

**Comment by kroitor** [comment]
> it doesn't get my full order for a coin?

`fetchOpenOrders()` does not return a single order it returns multiple order**s**, all of your currently open orders (many of them). There is no such thing as "full order" there.

**Comment by mohammadwillwin** [comment]
Yes but fetchClosedOrders doesn't return anything, why?

**Comment by kroitor** [comment]
@mohammadwillwin because you don't have closed orders?

**Comment by mohammadwillwin** [comment]
Hmm, what about finished orders?

**Comment by kroitor** [comment]
@mohammadwillwin closed == filled == finished. Just read the Manual first in order to understand it.

**Comment by mohammadwillwin** [comment]
uh alright. I'll re-read it, thank you.
