### ISSUE TITLE
[FTX] Fetch markets fails when it encounters a Future with no expiration date

### ISSUE THREAD

**Issue by mattepozz** [ccxt/ccxt#11544]
- OS: MacOS
- Programming Language version: Python 3.9
- CCXT version: 1.68.20

When loading markets on FTX, it can happen that a future has no expiration date set, so the following line of `ccxt/async_support/ftx.py` in `fetch_markets`  fails:

```python
symbol = base + '/' + quote + ':' + settle + '-' + self.yymmdd(expiry, '')
```

because `expiry` is `None` and `yymmdd` raises `TypeError`.

Unfortunately I don't have details about the symbol, I can only tell that it happened at Jan 20, 2022 12:00:09 AM UTC.

**Comment by kroitor** [comment]
@mattepozz do you have this issue with the most recent version of the lib? (1.68.79+)

**Comment by mattepozz** [comment]
We encountered this problem again with version `1.72.58`

**Comment by kroitor** [comment]
@mattepozz i cannot really reproduce it with this code (it's working for me):

```Python
import ccxt.async_support as ccxt
from asyncio import run

async def main():
    exchange = ccxt.ftx()
    try:
        await exchange.load_markets()
        print(exchange.symbols)
    except Exception as e:
        print(type(e).__name__, str(e))
    await exchange.close()


run(main())
```

**Comment by mattepozz** [comment]
@kroitor Thanks for checking! It does not happen all the time, only seldom.

Would you mind adding an assertion in `fetch_markets` before calling `yymmdd`? This could help to identify for which futures this happens.

Something like:

```python
assert expiry, f"Expiry not set for future {id}"
symbol = base + '/' + quote + ':' + settle + '-' + self.yymmdd(expiry, '')
```

**Comment by kroitor** [comment]
@pietrodn @mattepozz yep, where that error happens is clear, but it's not entirely clear why – a verbose output would help resolve it. I'll try to reproduce it on my side.

**Comment by pietrodn** [comment]
@kroitor I tried to improve the reporting of such errors in this PR: https://github.com/ccxt/ccxt/pull/12017
