### ISSUE TITLE
How to enable 2FA for connection for FTX api? (Python)

### ISSUE THREAD

**Issue by riemanncode** [ccxt/ccxt#11579]
I would like to have the option to connect/login to my account using 2FA to enable all the measures available for safety. Unfortunately I didn't find an answer/guide that refers to this problem.

To take 2FA into account I've changed in the file /base/exchange.py:
at line 172
`twofa = ' '`

and at line 249
`'twofa': True`

So now when I try to run a basic code it's asked to me to add/include the 'twofa' variable in the `ccxt.ft({ ...})` initialization process, otherwise I won't perform any task.

But, now if I add a completely random `'twofa'=123456` it will connect to my account and perform normally. In this case to me twofa is completely secondary to `apiKey` and `secret`. It's like the important thing is to add `'twofa'` to the initialization process `ccxt.ft({ ...})` but it doesn't care if it's a correct or completely wrong 2FA

I would like to establish a connection with my account with `'apiKey'`, `'secret'` and `'twofa'` all togheter.

this is the code that I'm running with a completely random(WRONG) 2FA and it works completely fine like it's a correct 2FA code:

```
import ccxt
import pandas as pd

my_APIKEY = 'mypswd0'
my_SECRETKEY = 'mypswd1'
twofact = 123456   ##random wrong code

ftx = ccxt.ftx({
    'apiKey': my_APIKEY,
    'secret': my_SECRETKEY,
    'twofa': twofact,
    "hostname": "ftx.com",
    'options': {
        'defaultType': 'future',
                 },
})

```

How can I perform this? thank you in advance.

**Comment by kroitor** [comment]
FTX API does not need a twofa setting. The 2fa code is only mentioned once in the withdraw() call.

You should use it like this:

```Python
exchange = ccxt.ftx({
    'apiKey': my_APIKEY,
    'secret': my_SECRETKEY,
})

exchange.load_markets()

params = {
    
    'code': exchange.totp ('YOUR_2FA_SECRET_HERE')  # will yield a 6-digit timebased 2fa code
    # 'password': 'YOUR_WITHDRAWAL_PASSWORD_IF_ANY',
    
    # other overrides if necessary
}
response = exchange.withdraw (code, amount, address, tag, params)
```

Hope that answers your question. Let us know if not. Feel free to reopen this issue or just ask further questions if any.

**Comment by kroitor** [comment]
Alternatively, you can also do it like this:

```Python
exchange = ccxt.ftx({
    'apiKey': my_APIKEY,
    'secret': my_SECRETKEY,
    'twofa': 'YOUR_2FA_SECRET_CODE_HERE'
})

exchange.load_markets()

params = {
    
    'code': exchange.oath (),  # will yield a 6-digit timebased 2fa code
    # 'password': 'YOUR_WITHDRAWAL_PASSWORD_IF_ANY',
    
    # other overrides if necessary
}
response = exchange.withdraw (code, amount, address, tag, params)
```
