### ISSUE TITLE
How to fetch Binance deductions?

### ISSUE THREAD

**Issue by tredondo** [ccxt/ccxt#11575]
Is it possible somehow to fetch Binance "Auto deduction"s? A few months after it delists a token, Binance will deduct all those tokens from a user's portfolio.

https://binance-docs.github.io/apidocs/spot/en/ doesn't have anything about "deduction" and deductions aren't returned by `fetchMyTrades` or `fetchWithdrawals`.

**Comment by samgermain** [comment]
Hello, there is no way to get this data from the api right now, but I spoke with Binance, and the person I spoke with told me they would forward my request as a suggestion to be made.

You can manually receive the data at https://www.binance.com/en/my/wallet/history/deduction-crypto
