### ISSUE TITLE
Retrieving Data from CoinMarketCap

### ISSUE THREAD

**Issue by kaijun40640** [ccxt/ccxt#11589]
- OS: Edition	
Windows 11 Home
Version	21H2
OS build	22000.434

- Programming Language version: Python 3.7.0
- CCXT version: CCXT Version: 1.68.95

Trying to access the coinmarketcap class using the following code snippet on Google Colab but getting an error that ccxt has no attribute coinmarketcap 

CODE (running on Google Colab):
```
!pip3 install ccxt
import ccxt
cmc = ccxt.coinmarketcap()
cmc.fetch_tickers()
```

OUTPUT:
```
AttributeError: module 'ccxt' has no attribute 'coinmarketcap'
```

Also, is it possible to get the historical market cap data from coinmarketcap by specifying a date as a parameter?

**Comment by kroitor** [comment]
Coinmarketcap has been delisted since they changed their API for private paid access. Hope that answers your question.
