### ISSUE TITLE
binance fetchDeposits for BTC is empty

### ISSUE THREAD

**Issue by iBobb** [ccxt/ccxt#11580]
Am I doing something wrong or is there a bug, when I call fetchDeposits and i pass 'BTC' as the currency, I get an empty array, no error. I'm passing a "since" like that, and my deposit is late 2020 (i tried passing a limit of 20 as well):

I get EUR deposits fine. What I want to achieve is to see the transfer of BTC from a wallet/coinbase into Binance.

- OS: Windows 10, latest updates
- Programming Language version: TypeScript 4.3.5 with NestJS 8
- CCXT version: 1.68.84 latest

```
let since = this.binanceClient.parse8601('2019-01-01T00:00:00Z');

const deposits: void | Transaction[] = await client.fetchTransactions('BTC', since).catch(e => {
            console.log("API ERROR: " + e);
        }); 

```

**Comment by frosty00** [comment]
have you tried to use `fetchDeposits` instead of `fetchTransactions` for binance?

**Comment by iBobb** [comment]
Oh, forgot to change that, yes indeed I tried fetchDeposits, i only tried fetchTransactions now because fetchDeposits didn't work, I meant to write fetchDeposits in the example.

**Comment by frosty00** [comment]
I believe the api only returns up to 30 days after since, so you can only get a 30 day window of transactions

**Comment by iBobb** [comment]
Wow yes that was it! I updated "since" to be closer to the deposit date and now I got it. I don't think I saw that in the docs. Thanks a ton for the quick help!

**Comment by iBobb** [comment]
Btw to conclude the topic,

**Comment by kroitor** [comment]
> Should I basically loop the deposits into 30 day windows to get more deposits?

Yes, you should paginate over your deposits: https://docs.ccxt.com/en/latest/manual.html#pagination

However, most of the exchanges will not let you query history far in the past, they will limit your history to the most recent N months, binance limits that to 3 months afaik. Hope that answers your question, let us know if not.
