### ISSUE TITLE
Use Cached Data when them available

### ISSUE THREAD

**Issue by mablue** [ccxt/ccxt#11597]
- OS: Arch Linux
- Programming Language version: Python 3
- CCXT version: end version

I need to download 100 last candles but if i downloaded them before i need to decrease limit to just download unavailable new candles data.how can I do?
I mean something like this:
```
# load csv
...
# calculate how much unavailable candles are inside csv!
# maybe its easely possable with:
if df["close"] == np.nan: 
   ...
unavailable_size = ...
# fetch just unavailable data
df = config.exchange.fetch_ohlcv(symbol=market, timeframe=tf, limit=unavailable_size)
# save data inside csv
df.save ...
#load 100 candles of csv inside a df to use
...
```
Please help me.Thanks
also I want to know if Maybe ccxt have an option like that to do:
```
df = config.exchange.fetch_ohlcv(symbol=market, timeframe=tf, limit=100, use_cached_data=True)
```

**Comment by ttodua** [comment]
@mablue I think you already had the similar issue opened https://github.com/ccxt/ccxt/issues/10615, where I've replied. Please don't open the topic if the issue is same, and re-open that previous topic if the suggested solution doesnt work.
