### ISSUE TITLE
New Exchange: Big.one

### ISSUE THREAD

**Issue by haozi3156666** [ccxt/ccxt#1159]
big.one is a new cryptocurrency exchange created by li xiaolai who is the richest man in bitcoin, Its predecessor was the yunbi.com, can you add it to this library. here is the official link: [big.one](https://big.one/), and it's developer documentation is [documentation](https://developer.big.one/).

thanks

**Comment by Deathamns** [comment]
Anyone working on this?

**Comment by kroitor** [comment]
@Deathamns I'm mostly occupied with previous requests now.

**Comment by Deathamns** [comment]
OK, I'll engage with this one.
And probably the other ones too if no one will reply...

**Comment by kroitor** [comment]
@Deathamns thanks, man! This is really helpful! I'm merging the ones you've submitted earlier in the meantime.

**Comment by jjhesk** [comment]
api doc: https://developer.big.one/
url: https://big.one
fee: --
volume: --
address: --
company info: --
Registration: --
based country: British
whitepaper: --
priority: low
github group: --
note: ranked top : NA
type: centrailzed ex

**Comment by valentinbora** [comment]
Seems developer.big.one does not work, but I found docs at https://open.big.one/docs/api.html

**Comment by kroitor** [comment]
@valentinbora yep, thx, working on it: https://github.com/ccxt/ccxt/pull/1411
