### ISSUE TITLE
Cancelled Futures being recycled

### ISSUE THREAD

**Issue by mattepozz** [ccxt/ccxt#11598]
- OS: MacOS
- Programming Language version: Python 3.9
- CCXT version: 1.68.84
- CCXT-PRO version: 0.92.82

## Problem
We found out that using `asyncio.wait_for` on `watch_*` methods will make those methods unusable again with the same set of parameters.
The reason is that `wait_for` cancels the wrapped future; however, ccxtpro will try to use it again on subsequent invocations if the `message_hash` is the same.

### Why do we need `wait_for`
Web sockets could occasionally get stuck and we want to be able to _detect that_ and resubscribe. 

## How to reproduce

```python
import asyncio

import ccxtpro

SYMBOL = "DOGE/USDT"


async def main() -> None:
    binance_client = ccxtpro.binanceusdm()

    while True:
        try:
            await asyncio.wait_for(binance_client.watch_ticker(SYMBOL), 1)
        except asyncio.TimeoutError:
            print("✅ Timeout hit!")
            break
    try:
        await binance_client.watch_ticker(SYMBOL)
        print("All good!")
    except asyncio.CancelledError:
        print("⚠️ CancelledError raised!")
    finally:
        await binance_client.close()


if __name__ == "__main__":
    asyncio.run(main(), debug=True)
```

This will print:
```
✅ Timeout hit!
⚠️ CancelledError raised!
```

In the first `while` loop we set a short timeout in order to trigger the `TimeoutError`. In reality our time limit will be longer.

As expected `watch_ticker` hits the time limit and `wait_for` correctly raises `TimeoutError`. We then simply try to call the same coroutine again; this time, we don't set a timeout.

This time `watch_ticker` unexpectedly raises `CancelledError`, even though we just created this coroutine!

## Suggested solution

The `future(message_hash)` method of `ccxtpro/base/client.py` looks up the future in a dictionary:

```python
            if message_hash not in self.futures:
                self.futures[message_hash] = Future()
            return self.futures[message_hash]
```

A solution would be to create a new future if the existing one was cancelled already:

```python
            if message_hash not in self.futures or self.futures[message_hash].done():
                self.futures[message_hash] = Future()
            return self.futures[message_hash]
```

(The same needs to be done above, if `message_hash` is a `list`.)

**Comment by frosty00** [comment]
Thanks for the great bug report, the code you provided was really in depth and made it easy to close this issue

**Comment by frosty00** [comment]
btw can you email us at info@ccxt.trade we'd love to get in contact and know more about you
