### ISSUE TITLE
watchBalance promise never returns for some exchange

### ISSUE THREAD

**Issue by Rezan-vm** [ccxt/ccxt#11590]
- OS: Linux Ubuntu
- Programming Language version: NodeJs 12.19.0
- CCXT version: ccxt.pro 0.9.82

Code to reproduce:
```
const exchange = new ccxt.gateio({ apiKey: "xxxx", secret: "xxxx" });
const balance = await this.exchange.watchBalance(); // Never resolves 
```

I am using gateIO but we might have the same issue on other exchanges. The subscription works and we're getting the balance updates but the original promise never resolve. I would expect the promise the resolve with the balances once the balance snapshot was fetched.

**Comment by kroitor** [comment]
@Rezan-vm thanks for reporting! I've pushed a quickfix for it, please let us know if you have this issue with CCXT Pro 0.9.83+ (the new build will arrive in ~20 minutes).

**Comment by Rezan-vm** [comment]
That fixed my issue!
Awesome, thanks for the great work.
