### ISSUE TITLE
Huobi Futures in CCXT

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#11606]
Good news everyone!

[![huobi-futures-ccxt](https://user-images.githubusercontent.com/1294454/150618153-e818845e-ba2e-4d60-8b1d-4ff47e09270d.png)](https://www.huobi.com/en-us/topic/double-reward/?invite_code=6rmm2223)

We are happy to announce the support for the Huobi Futures API in CCXT as of version 1.68+.

Please, find the source code examples here:

- JavaScript:
  - https://github.com/ccxt/ccxt/blob/master/examples/js/huobi-futures.js
  - https://github.com/ccxt/ccxt/blob/master/examples/js/huobi-swaps.js
- Python:
  - https://github.com/ccxt/ccxt/blob/master/examples/py/huobi-futures.py
  - https://github.com/ccxt/ccxt/blob/master/examples/py/huobi-swaps.py
- PHP:
  - https://github.com/ccxt/ccxt/blob/master/examples/php/huobi-futures.php
  - https://github.com/ccxt/ccxt/blob/master/examples/php/huobi-swaps.php
  
Compare Huobi Futures to Huobi Spot in this Python example:

- https://github.com/ccxt/ccxt/blob/master/examples/py/huobi-spot.py

Your feedback and reports are very much appreciated!

Thanks for using CCXT!

**Comment by Mazon7** [comment]
Hello, @kroitor. Hope you are good and could possibly point me in right direction!

Just trying to implement trades for USDT-M huobi following this example https://github.com/ccxt/ccxt/blob/master/examples/js/huobi-swaps.js

Unfortunately, I always get error about bad symbol.

I tried to use `EOS/USDT:USDT` and `EOS/USD:EOS` pairs but always get `Bad symbol`  error.

`BadSymbol: huobi does not have market symbol EOS/USD:EOS`

This is the code that i am using:

```
const huobiFutures = new ccxt.huobi({
  apiKey: "apiKey",
  secret: "secret",
  options: {
    defaultType: "swap",
  },
  enableRateLimit: true,
  timeout: 60000,
});

function buyEOSHuobiUSD_M(symbol, amount) {
  "use strict";

  return new Promise((resolve) => {
    huobiFutures
      .createOrder(symbol, "limit", "buy", amount, 1, {
        offset: "open",
        lever_rate: 5,
        positionSide: "LONG",
      })
      .then((order) => {
        resolve(order);
      });
  });
}
```

Later this function is called: `buyEOSHuobiUSD_M("EOS/USDT:USDT", 1)`

I also looked up the tickers using t this method but didn't find those I need:
`huobiFutures.fetchTickers().then((order) => {
  resolve(order);
});`

**Comment by kroitor** [comment]
@Mazon7 hello!

If you want USDT-Margined symbols, then you should set `defaultType`: `swap` and `defaultSubType`: `linear`. Please, paste your verbose output:

```JavaScript
const ccxt = require ('ccxt')

console.log ('CCXT Version:', ccxt.version)

async function main () {
    exchange = ccxt.huobi({
        'apiKey': YOUR_API_KEY',
        'secret': 'YOUR_SECRET',
        'options': {
            'defaultType': 'swap',
            'defaultSubType': 'linear',
        },
    })
    await exchange.loadMarkets ()
    exchange.verbose = true
    const ticker = await exchange.fetchTicker ('EOS/USDT:USDT')
    console.log (ticker)
}

main()
```

**Comment by Mazon7** [comment]
Worked! Thanks a lot!
Should I also specify `defaultSubType` or something else additionally for trading Coin-M Futures and Coin-M Swaps?

**Comment by kroitor** [comment]
> Worked! Thanks a lot! Should I also specify `defaultSubType` or something else additionally for trading Coin-M Futures and Coin-M Swaps?

For Coin-M futures you would specify defaultType = future, defaultSubType = inverse
For Coin-M swaps you would specify defaultType = swap, defaultSubType = inverse
For USDT-M futures you would specify defaultType = future, defaultSubType = linear
For USDT-M swaps you would specify defaultType = swap, defaultSubType = linear

**Comment by Mazon7** [comment]
@kroitor Really appreciate it! Hopefully, this will be very helpful for others too!

**Comment by TayTech** [comment]
Hi, very greate job on this library, is not easy to manage all. (sorry for my english)
I'm using it for huobi and on spot trading is good, but for the features I'm not find it easy for those reasons:
- the fetchAccount method is calling only the spot account and not any futures
- in some methods mapping from isolated or cross management are missing
- in other there are linearSwap missing despite the fact that the methods to call are implemented

I get to knew that were missing after looking at these code:  https://github.com/ccxt/ccxt/blob/master/js/huobi.js

and going verbose mode otherwise I couldn't get how everything wasn't returning the right results.

**Comment by ttodua** [comment]
If anyone experiences any issue with Huobi, please open a separate issue (instead reporting directly under this announcement). thanks
