### ISSUE TITLE
precision defaults

### ISSUE THREAD

**Issue by Deathamns** [ccxt/ccxt#1160]
I run into exchanges that fail to execute `exchange.{price,amount,cost}ToPrecision` methods, because they don't have precision values set (bitbay, bitfinex2...). Would it be sensible to provide default values for the precision object in the base class (8 seems to be common), or maybe better, adding a new argument for these methods for default precision?

**Comment by mkutny** [comment]
A lot of people will appreciate if you submit PRs with explicit precisions for the exchanges you have issues with )

**Comment by Deathamns** [comment]
Well, I'm also a member of those "lot of people", so you're PRs are welcome as well.
But, I was doing something that didn't require precise calculations looping through all exchanges, and some defaults could have been saner option in that case, than going to every exchange and hunting precision numbers.

@kroitor 
Anyway, as a workaround, I filled the `precision` property for the exchanges which didn't have it. However, later calling `fetchMarkets`, my `precision` property was gone because [`deepExtend`](https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L486) kills it since my `fees` property is undefined.

```js
let arg1 = {hello: 1};
let arg2 = undefined;
let arg3 = {hello2: 2};
deepExtend(arg1, arg2, arg3);
```
It returns `undefined`, however I would expect `{hello: 1, hello2: 2}`.

**Comment by mkutny** [comment]
> Well, I'm also a member of those "lot of people", so you're PRs are welcome as well.

I've just seen you contributed to this library a lot, that's why my comment. Didn't want want to insult you in any way, sorry for that!

**Comment by Deathamns** [comment]
@mkutny Relax, I was smiling while writing my first sentence. I just don't use emoticons, so it may seem a bit raw.
