### ISSUE TITLE
ccxt GOLD/USD ticker/ohlcv works but create order says symbol not listed

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#11601]
GOLD/USD
ExchangeError phemex {"code":39999,"msg":"Symbol not listed","data":null}

**Comment by kroitor** [comment]
@adamrg73 please, paste your code to reproduce it.

**Comment by adamrg73** [comment]
```
params = {
        'timeInForce': 'PostOnly'
        }
placeOrder_result=exchange.create_order(symbol, 'limit', 'buy', qty, l_close-2, params)

                print('placeOrder_result: '+str(placeOrder_result))
```

CCXT Version: 1.60.43

this works:
Request: GET https://api.phemex.com/v1/md/ticker/24hr?symbol=GOLDUSD {'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.phemex.com/v1/md/ticker/24hr?symbol=GOLDUSD 200 {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Fri, 21 Jan 2022 21:35:13 GMT', 'Server': 'nginx', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Xss-Protection': '1; mode=block', 'X-Frame-Options': 'SAMEORIGIN', 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'origin-when-cross-origin', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'X-Cache': 'Hit from cloudfront', 'Via': '1.1 e04ec889239bf67ef206ad086add2d7a.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'IAD66-C2', 'X-Amz-Cf-Id': 'J-3MMtR9lGL2kh7jK10fmna_WsZNexbutXjyDE1xSyqyn6P9GiIgdw=='} {
  "error": null,
  "id": 0,
  "result": {
    "askEp": 18303000,
    "bidEp": 18302500,
    "fundingRateEr": 10000,
    "highEp": 18442000,
    "indexEp": 18337025,
    "lastEp": 18303000,
    "lowEp": 18278500,
    "markEp": 18337578,
    "openEp": 18399500,
    "openInterest": 1907222,
    "predFundingRateEr": 10000,
    "symbol": "GOLDUSD",
    "timestamp": 1642800912284810059,
    "turnoverEv": 105923347345,
    "volume": 5766338
  }
}

but order doesnt work:


Request: POST https://api.phemex.com/orders {'x-phemex-access-token': '4be0fdfb-c45b-43dc-80c0-2a8549680a21', 'x-phemex-request-expiry': '1642800919', 'Content-Type': 'application/json', 'x-phemex-request-signature': '3a05904628cbef2d4f461eaedb515a5e7ef00b3da5ad9f518855557887fd3f91', 'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} {"symbol":"GOLDUSD","side":"Buy","ordType":"Limit","orderQty":1,"priceEp":18283000,"timeInForce":"PostOnly"}

Response: POST https://api.phemex.com/orders 200 {'Content-Type': 'application/json', 'Content-Length': '52', 'Connection': 'keep-alive', 'Date': 'Fri, 21 Jan 2022 21:34:19 GMT', 'Server': 'nginx', 'x-phemex-request-tracing': '49f6656d-15be-4a6f-b2bd-1b197679b62d', 'X-RateLimit-Remaining-CONTRACT': '485', 'X-RateLimit-Capacity-CONTRACT': '500', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate, no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Content-Type-Options': 'nosniff, nosniff', 'X-Frame-Options': 'DENY, SAMEORIGIN', 'X-XSS-Protection': '1 ; mode=block, 1; mode=block', 'Referrer-Policy': 'no-referrer, origin-when-cross-origin', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 ff57be90471f9a747547dbdeaf42a3ea.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'IAD79-C3', 'X-Amz-Cf-Id': 'lokA53bR_jL48eEA04c-OH3MaSSfU4O6A8uhbq1DVrJWygl5BaWvgg=='} {"code":39999,"msg":"Symbol not listed","data":null}
Error on line 695 ExchangeError phemex {"code":39999,"msg":"Symbol not listed","data":null}

**Comment by carlosmiei** [comment]
Hello @adamrg73 

The problem here is that the pair "GOLD/USD" can only be traded as a contract (swap), not in the spot market. So to make it work you should follow the unified way CCXT has to represent swaps.

For this case, since the only available contract for this pair is an inverse swap, it should be defined as "GOLD/USD:USD"

Please check out here the docs about name consistency:
https://docs.ccxt.com/en/latest/manual.html#contract-naming-conventions
And here is an example of how to place a contract position:
https://github.com/ccxt/ccxt/blob/master/examples/py/phemex-open-cancel-close-positions.py

Thank you!

**Comment by adamrg73** [comment]
On newer ccxt version symbols are coming up as GOLD/USD:USD for example, but I test fetch ohlcv with that doesnt work, works for GOLD/USD.
I spoke with phemex api team about it, and how they shouldnt be breaking people's old code when theyre trading in any or these volatile markets.  Dont know if thats the case here, but kind of looks like it.

**Comment by adamrg73** [comment]
any update on the issue? sorry to bother.
thx again

**Comment by carlosmiei** [comment]
@adamrg73 Yes, I've reached out Phemex support and unfortunately, they don't support yet this pair trading using the API, therefore I'll close this issue since it's not CCXT related. 

![image](https://user-images.githubusercontent.com/43336371/150770955-6ccbf9bc-8d5b-4529-b07b-8b61cae888c1.png)

Thank you
