### ISSUE TITLE
[therock] Wrong POST call for fetchOrder function.

### ISSUE THREAD

**Issue by giubby84** [ccxt/ccxt#11635]
Hi. TheRockTrading exchange (therock.js) appers to have a bug on the fetchOrder function. A wrong POST call is done. To replicate this:

```
let orderId = '123' // A valid order id

let trt    = new ccxt.therock({
        'apiKey': 'yourkey',
        'secret': 'yoursecret'
})

await trt.fetchOrder(orderId, 'BTCEUR')
```

The error: **TypeError: this.privatePostFundsFundIdOrdersId is not a function.**

Replace the POST call privatePostFundsFundIdOrdersId with the correct GET call privateGetFundsFundIdOrdersId solves the problem.

I have provided a PR for that (#11634)

**Comment by kroitor** [comment]
@giubby84 thanks for pointing it out and for the PR!
