### ISSUE TITLE
Wrong parseTrade for GateIO on websocket

### ISSUE THREAD

**Issue by Rezan-vm** [ccxt/ccxt#11656]
- OS: Linux
- Programming Language version: JS
- CCXT version: ccxt@1.70.55 

```
const gateio = new ccxt.gateio({...})
const trades = await this.gateio.watchTrades("EHT/USDT");
```

The `parseTrade` function is incorrect for gateIO (At least when using it with `watchTrade`)

That's how an update look like from the websocket:
```
{
  id: 2693610448,
  time: 1643140805.151062,
  price: '0.000000024114',
  amount: '451085836',
  type: 'buy'
}
```

2 issues:
- The timestamp is in seconds, not ms. So I get dates like `1970-01-20T00:25:40.805Z`
- The `side` argument isn't considered. Instead, `parseTrade` seems to look at the sign of `amount` which isn't how it works.

**Comment by kroitor** [comment]
Will push a fix shortly.
