### ISSUE TITLE
Question about response structure from createOrder

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#11659]
OS: Windows Server 2019 Datacenter
Programming Language version: Node.js 15.3.0
CCXT version: 1.49.98
Exchange: Kucoin and All Exchanges
Method: exchange.createOrder()

Hello!

I have a question about when `createOrder` in general on exchanges and in this case the Kucoin exchange. The question is when an order gets Filled **INSTANTLY** when `createOrder`.

I red in the Manual the below and need to confirm this so I am very sure of this:
_**"Note, that some fields from the order structure returned from createOrder may be undefined / None / null if the underlying exchange API does not return that information in the response."**_

For example when sending the below order, I never got the information back in the order structure that 20 TRX were Filled. Also not info about: _**cost, remaining, status**_

Is it true that some exchanges will not return this information and some will? As I understand in this Kucoin case, we need to call for example: `fetchOpenOrders, fetchClosedOrders` afterwards to get this information?

_(Why I ask this is because an extra call will make the chain of code events _longer_ after `createOrder`, - which will make it a slower process to return how much has been filled)_

Thank you!

```
//Declare instance
const kucoin = new ccxt.kucoin({ enableRateLimit: true })
kucoin.verbose = true;

//Create Order
const params = {};
var response = await kucoin.createOrder("kucoin", "TRX/USDT", "limit", "buy", 20, 0.056, params);
console.log(response);
```

Verbose output:
```
fetch:
 kucoin POST https://openapi-v2.kucoin.com/api/v1/orders
Request:
 {
  'KC-API-KEY-VERSION': '2',
  'KC-API-KEY': 'removedbyOP',
  'KC-API-TIMESTAMP': '1643156467259',
  'Content-Type': 'application/json',
  'KC-API-PASSPHRASE': 'removedbyOP',
  'KC-API-SIGN': 'removedbyOP'
}
 {"clientOid":"9ac087a4-b046-4923-9685-718027aab342","side":"buy","symbol":"TRX-USDT","type":"limit","price":"0.056","size":"20"}

handleRestResponse:
 kucoin POST https://openapi-v2.kucoin.com/api/v1/orders 200 OK
Response:
 {
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '6d35944ffea40d3e-ARN',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json',
  Date: 'Wed, 26 Jan 2022 00:21:07 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Set-Cookie': 'AWSALB=sZUrnljARFhP66CrIkiwGzeITalo/pTaRaO/DqQ4rbQF9KdbPBnZQyab9Q+WRzq5NoKAEhEgwte2Fah1/RBtPkPUpSLAepi401kFdxX6MBLWAsvHWyq3VlrtpmRw; Expires=Wed, 02 Feb 2022 00:21:07 GMT; Path=/, AWSALBCORS=sZUrnljARFhP66CrIkiwGzeITalo/pTaRaO/DqQ4rbQF9KdbPBnZQyab9Q+WRzq5NoKAEhEgwte2Fah1/RBtPkPUpSLAepi401kFdxX6MBLWAsvHWyq3VlrtpmRw; Expires=Wed, 02 Feb 2022 00:21:07 GMT; Path=/; SameSite=None; Secure, __cfruid=df3d3129b0dc2b3871d71854e8c1015abe531319-1643156467; path=/; domain=.kucoin.com; HttpOnly; Secure; SameSite=None',
  'Strict-Transport-Security': 'max-age=9800; includeSubDomains; preload',
  'Transfer-Encoding': 'chunked'
}
 {"code":"200000","data":{"orderId":"61f093f37ee3b40001194dd4"}}

{
  id: '61f093f37ee3b40001194dd4',
  clientOrderId: '9ac087a4-b046-4923-9685-718027aab342',
  info: { orderId: '61f093f37ee3b40001194dd4' },
  timestamp: 1643156467583,
  datetime: '2022-01-26T00:21:07.583Z',
  lastTradeTimestamp: undefined,
  symbol: 'TRX/USDT',
  type: 'limit',
  side: 'buy',
  price: 0.056,
  amount: 20,
  cost: undefined,
  average: undefined,
  filled: undefined,
  remaining: undefined,
  status: undefined,
  fee: undefined,
  trades: undefined
}
```

**Comment by kroitor** [comment]
> Is it true that some exchanges will not return this information and some will? 

Yes, that is true.

> As I understand in this Kucoin case, we need to call for example: `fetchOpenOrders, fetchClosedOrders` afterwards to get this information?

Yes, that is correct. If you want to get the information about the order, even if it was filled almost immediately, you still have to fetchOrder / fetchOpenOrders / fetchClosedOrders.

Inside the `info` substructure in all unified response, including the createOrder response, you will see the exchange response as is, untouched. From your output above, you can see that KuCoin has only returned the order id in the `info`. So CCXT cannot guess the filling prices and the other info from that id. You have to query your order by that id again to find its current state.

Hope that answers your question.

**Comment by jackpotcityco** [comment]
Thank you for your answer, it helped alot to clarify to be sure.

Thank you!
