### ISSUE TITLE
Is there anyway to get transcation count for a period of time?

### ISSUE THREAD

**Issue by universewill** [ccxt/ccxt#11663]
ccxt can get candle data for coins.
Is there anyway to get transaction count and active addess count for 1min or 1hour or 1day?

**Comment by kroitor** [comment]
> ccxt can get candle data for coins. Is there anyway to get transaction count and active addess count for 1min or 1hour or 1day?

With CCXT you can fetch your personal transaction history from the exchanges (fetchTransactions, fetchDeposits, fetchWithdrawals, see the Manual on how to do that), but not from the blockchain/addresses.

Hope that answers your question, let us know if not.

**Comment by universewill** [comment]
> > ccxt can get candle data for coins. Is there anyway to get transaction count and active addess count for 1min or 1hour or 1day?
> 
> With CCXT you can fetch your personal transaction history from the exchanges (fetchTransactions, fetchDeposits, fetchWithdrawals, see the Manual on how to do that), but not from the blockchain/addresses.
> 
> Hope that answers your question, let us know if not.

I want to use some statistics of the digital coin market like transaction count for a period (1min/1hour/...), active address count and etc, to do quant strategy, is there any way to get these data?

I notice that the pulic api of ccxt contains fetchTrade() api, is it right to count trade numbers from the fetch result to get transaction count for a period of time?

**Comment by kroitor** [comment]
@universewill 
> is it right to count trade numbers from the fetch result to get transaction count for a period of time?

It depends on what exactly you call "transactions". In CCXT a transaction is something that goes on the blockchain (either a deposit or a withdrawal to a crypto exchange). Trades are not transactions, though, cause they happen on the exchange side, not on the blockchain. If you need the exchange trades, then fetchTrades will do the job for you. If you need the blockchain transactions, then I would suggest to take a look at web3.
