### ISSUE TITLE
[Python][Kucoin] Got an exception while calling fetch_balance of kucoin.

### ISSUE THREAD

**Issue by HiddenFox** [ccxt/ccxt#1167]
- OS: win7
- Programming Language: python
- CCXT version: 1.10.631
- Exchange: Kucoin
- Method: fetch_balance

```
kucoin = ccxt.kucoin()
kucoin.apiKey = KUCOIN_KEY
kucoin.secret = KUCOIN_SECRET
balance = kucoin.fetch_balance()
```
Traceback (most recent call last):
  File "E:/workspace/python/crypto-arbitrage/check_balance.py", line 15, in <module>
    balance = kucoin.fetch_balance()
  File "E:\workspace\python\envs\py2env\lib\site-packages\ccxt\kucoin.py", line 261, in fetch_balance
    }, params))
  File "E:\workspace\python\envs\py2env\lib\site-packages\ccxt\kucoin.py", line 562, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "E:\workspace\python\envs\py2env\lib\site-packages\ccxt\base\exchange.py", line 296, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "E:\workspace\python\envs\py2env\lib\site-packages\ccxt\base\exchange.py", line 361, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, None, self.last_http_response)
  File "E:\workspace\python\envs\py2env\lib\site-packages\ccxt\kucoin.py", line 557, in handle_errors
    self.throw_exception_or_error_code(response)
  File "E:\workspace\python\envs\py2env\lib\site-packages\ccxt\kucoin.py", line 547, in throw_exception_or_error_code
    raise InvalidNonce(self.id + ' ' + message)
ccxt.base.errors.InvalidNonce: kucoin Invalid nonce

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki#troubleshooting

**Comment by HiddenFox** [comment]
1. I tried binance.fetch_balance(). It works well.
2. I regenerated another kucoin API key pair. It does not work.
3. I run the python script on another win7 pc. It works well.
4. I tried ccxt 1.10.637 in both python 2.7 and python 3 environments. None of them work.
5. I debuged the program. When the program request the url "https://api.kucoin.com/v1/account/balance?limit=20&page=1 ", the response content is:
{"code":"UNAUTH","msg":"Invalid nonce","success":false,"timestamp":1515655237450}'

**Comment by kroitor** [comment]
I've created a new testing key and tried fetching the balance (which is zero on that account), report if it works for you or not with that key:

```Python
import ccxt
exchange = ccxt.kucoin({
    "apiKey": "5a5712a29e13a25bfb18e501",
    "secret": "b849b80e-db41-44f5-99de-fd400e1d0aac",
})
balance = exchange.fetch_balance()
print(balance)
```

Does this exact code work for you?

**Comment by HiddenFox** [comment]
Got the same error on both python 2.7 and 3.5

**Comment by kroitor** [comment]
@HiddenFox ok, this is most likely due to clock unsynchronization or a different timezone. Can you set your system clock to UTC and synchronize it with an online timeserver, then retry again?

**Comment by HiddenFox** [comment]
I realized it could be the time setting of my computer. Then I synced the system time. It works.
Thanks for your help kroitor!

**Comment by kroitor** [comment]
Yep, wrote that simultaneously )
