### ISSUE TITLE
'Market Structure'.. Actual vs. Manual vs. Typescript typedef

### ISSUE THREAD

**Issue by christophe-hall** [ccxt/ccxt#11687]
Foremost thanks for your efforts to support Typescript.

I'm battling slightly with the variations of 'Market Structure' between the [manual](https://docs.ccxt.com/en/latest/manual.html?#market-structure), [Typescript definition](https://github.com/ccxt/ccxt/blob/master/ccxt.d.ts) and the actual data in Exchange.markets.

This is obviously an awkward moving target but I'd be interested to know if/when you think the structure might be settled..?

**Comment by christophe-hall** [comment]
Great, thanks for the update.

I'm not sure if I'm misunderstanding things but it seems that the typedef has 'baseId' and 'quoteId' whereas the javascript object does not. Conversely the javascript object has 'base' and 'quote' whereas the typedef does not.

**Comment by kroitor** [comment]
They should both be there, in the typedef and in js. @carlosmiei if possible, please add those missing fields.

**Comment by christophe-hall** [comment]
I presume it's work in progress to sync these things up. I see that 'percentage' and 'tierBased' have just been removed from the typedef but still exist in the js object. I just wonder if that means they're to be removed from the JS too or have been removed from the typedef by accident. Happy enough to wait and see...

**Comment by kroitor** [comment]
> I just wonder if that means they're to be removed from the JS too or have been removed from the typedef by accident. 

@christophe-hall @carlosmiei `percentage` and `tierBased` are injected in the base classes, we should restore them in the typedefs.

**Comment by christophe-hall** [comment]
Sorry to add.. I'm sure you know; Market 'precision' in inconsistent insofar as variously denoting either tick size or number of decimal places. eg. Bitfinex price precision is given as 5 (ie. decimal places) whereas ByBit price precision is given as eg. 0.0001 (ie. tick size).
