### ISSUE TITLE
BitFlyer prints strange symbols

### ISSUE THREAD

**Issue by mmehrle** [ccxt/ccxt#1168]
PASTE_YOUR_TEXT_DESCRIPTION_HERE

- OS: iOS
- Programming Language: python
- CCXT version: 1.10.621
- Exchange: bitflyer
- Method:

```
exchange = getattr(ccxt, 'bitflyer')({
        # 'verbose': True,
    })
    if hasattr(exchange, 'symbols'):
        print("crosses: {}".format(", ".join(exchange.symbols)))

BCH/BTC, BTC/JPY, BTCJPY12JAN2018, BTCJPY19JAN2018, ETH/BTC, FX_BTC_JPY

**Comment by kroitor** [comment]
Nothing strange about them, some symbols can stand for futures and options. Hope it answers your question.
