### ISSUE TITLE
Get full orders history for Binance, Bittrex and Bitfinex

### ISSUE THREAD

**Issue by vtllr** [ccxt/ccxt#1169]
Hi guys,

I'm trying to get all past orders of my accounts on Binance, Bittrex and Bitfinex but I failed to have a clean and simple solution.
- Bittrex: I have only 10 trades from bittrex.accountGetOrderhistory but I have way more from my account. (fetchOrders gives me an infinite loop ...)
- Binance / Bitfinex: fetchOrders not working without a symbol but I want all of them. 

Am I doing something wrong or is that not implemented yet on theses different API?

Thanks for your help!

**Comment by kroitor** [comment]
> Bittrex: I have only 10 trades from bittrex.accountGetOrderhistory but I have way more from my account. (fetchOrders gives me an infinite loop ...)

Can you show a short but a complete snippet of code with fetchOrders that I can copypaste to reproduce your problem?

> Binance / Bitfinex: fetchOrders not working without a symbol but I want all of them.

- Bitfinex does not have fetchOrders. It has fetchClosedOrders and fetchOpenOrders, both should work if you omit the symbol argument.
- Binance won't allow to fetch them all at once, you have to iterate over your symbols

> Am I doing something wrong or is that not implemented yet on theses different API?

Without seeing your code it's hard to tell.

**Comment by vtllr** [comment]
Thanks for your reply @kroitor!

### Bittrex
```js
const orders = this.fetchExchangeOrders(apiKey, apiSecret);
console.log('orders', orders); // 10 on 19 trades return

private async fetchExchangeOrders(apiKey, apiSecret) {
  const bittrex = new ccxt.bittrex({
    'apiKey': apiKey,
    'secret': apiSecret
  });

  // return await bittrex.fetchOrders(); // Infinite loop
  return await bittrex.accountGetOrderhistory();
}
```

### Bittrex
I will check ```fetchClosedOrders``` today 

### Binance
> Binance won't allow to fetch them all at once, you have to iterate over your symbols

I will add symbols on my front end so. 

Thanks a lot for your help! You have already done an amazing job.
