### ISSUE TITLE
Binance : Signature for this request is not valid 

### ISSUE THREAD

**Issue by thakursachin467** [ccxt/ccxt#11692]
```
const ccxt = require("ccxt").binance
const client = new ccxt({
            apiKey: XXX,
            secret: YYY,
            enableRateLimit: true,
            timeout: 10000,
        });

const withdrawal = client.withdraw("HIVE",0.02,"deposite_address", '{ method: "buy", symbol: "DEC", to: "token" }',{network: "HIVE"})
```

If i try to pass addressTag as stringified Object in the Withdraw API i’m receiving AuthenticationError Signature for this request is not valid . Is there a way to pass addressTag as stringified object to binance withdraw API? 

If i call the API directly it's working as intended. After some investigation i found that the signature generated is using the url encoded version of the query string. Which is causing issues with the signature generated and validation of signature binance. Is there a way to pass object inside tag fields?

**Comment by kroitor** [comment]
> `'{ method: "buy", symbol: "DEC", to: "token" }'`

That tag looks very strange to me. The addressTag field corresponds to the MEMO field on the exchange website. It is a numeric string for HIVE, afaik. Am I missing something?

**Comment by thakursachin467** [comment]
@kroitor The tag i'm passing is valid and is being processed by binance. You can you the transaction details here. https://www.hiveblockexplorer.com/tx/0e6ed7dda4f8c7569be6308c1c42cb3268f1cac8

This is required when you want to do some conversion on blockchain side. Like in this case HIVE tokens are being converted to DEC and being sent to wallet.

**Comment by kroitor** [comment]
@thakursachin467 please paste your verbose output:

```Python
const ccxt = require("ccxt").binance
const client = new ccxt({
            apiKey: XXX,
            secret: YYY,
            enableRateLimit: true,
            timeout: 10000,
        });

client.load_markets()
client.verbose = True  # after loading the market info
const withdrawal = client.withdraw("HIVE",0.02,"deposite_address", '{ method: "buy", symbol: "DEC", to: "token" }',{network: "HIVE"})
```
