### ISSUE TITLE
Gate.io creating orders returns "Cannot read properties of undefined (reading 'toString')"

### ISSUE THREAD

**Issue by csidi90** [ccxt/ccxt#11690]
I have a weird error that I only get with instances for the exchange gatio. 

Whenever I use exchange.createOrder or createMarketBuyOrder I get this error I can not resolve.

"Cannot read properties of undefined (reading 'toString')"

` return this.exchange.createMarketBuyOrder(
        market.symbol,
        baseAmount
      )`

in this particular example I use ETH/USDT for the "market.symbol" and 0.02 for the baseAmount

**Comment by kroitor** [comment]
@csidi90 what is your version of CCXT?
What do you see when you run this with the most recent version of the lib:

```JavaScript
const ccxt = require ('ccxt')

async function main () {

    const exchange = new ccxt.gateio ({
       'apiKey': 'YOUR_API_KEY',
       'secret': 'YOUR_SECRET',
    })
    
    await exchange.loadMarkets ()
    
    exchange.verbose = true

    const response = await exchange.createMarketBuyOrder ('ETH/USDT', 0.02)
    
    console.log (response)
}

main ()
```

To me it shows this:

```
~/ccxt $ node examples/js/cli gateio createMarketBuyOrder ETH/USDT 0.02 --verbose
2022-01-27T19:51:04.734Z
Node.js: v14.15.4
CCXT v1.70.75
gateio.createMarketBuyOrder (ETH/USDT, 0.02)
InvalidOrder gateio createOrder() does not support market orders for spot markets
---------------------------------------------------
[InvalidOrder] gateio createOrder() does not support market orders for spot markets

    at createOrder                js/gateio.js:2193                   throw new InvalidOrder (this.id + ' createOrder() does not support ' + type + '…
    at processTicksAndRejections  internal/process/task_queues.js:93
    at async main                 examples/js/cli.js:261              const result = await exchange[methodName] (... args)

gateio createOrder() does not support market orders for spot markets
```

Please, always paste a complete short code snippet to reproduce it:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by csidi90** [comment]
Im using   "ccxt": "^1.55.61", I checked the "has" Property after posting this and saw its not support market buy so I changed to just createOrder but I get the same error.

**Comment by kroitor** [comment]
@csidi90 please, upgrade to the most recent version of CCXT first, your version is too old. Second, please note the output in my previous answer, and the comment below. Gate.io does not support market orders for spot markets. Changing the call to `createOrder` does not change the order type per se.

Please, always paste a complete short code snippet to reproduce it:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by csidi90** [comment]
already updated my response. Thank you for this fast feedback. Did not expect an answer already. Cheers

**Comment by kroitor** [comment]
> So I guess for everything spot related I have to use limit?

Yes, that is correct, with spot markets you have to use limit orders. Closing this for now. Feel free to reopen it or just ask further questions if any.
