### ISSUE TITLE
php nonce override - help

### ISSUE THREAD

**Issue by dpreilan** [ccxt/ccxt#1170]
Poloniex and nonce issues

- OS: centos
- Programming Language: php
- CCXT version: latest
- Exchange: poloniex
- Method: all

seeing issues with poloniex that i couldn't reproduce with other php library. I narrowed it down to nonce() and if I replace poloniex's nonce with something that uses usecs, the resolves the problem.

Now, how to fix w/o hacking ccxt code. My app uses exchanges generically.
````
$exchange = '\\ccxt\\' . $this->ccxtName;
        $this->exchange = new $exchange (array(
            'apiKey' => $this->apiKey,
            'secret' => $this->apiSecret,
        ));

```

So, I can't subclass, I believe. I cannot find a way to overwrite the nonce() method. I have tried several things, like:

```
        $this->exchange->nonce = function () { return self::usecs(); };

OR for debug:

        $this->exchange->nonce = function () { return 55; }; // for kicks

```

Any thoughts on how this can be done in php?

**Comment by kroitor** [comment]
Have you tried creating a new key and then call poloniex without a nonce override?

**Comment by bakman2** [comment]
@kroitor could you perhaps add an example for PHP in the manual ? I am confused how to call nonce defined in the extended class. I have the same issue for poloniex.

**Comment by kroitor** [comment]
@bakman2 it's already there: https://github.com/ccxt/ccxt/wiki/Manual#overriding-the-nonce

**Comment by bakman2** [comment]
I see you don't have to call it, just extend it, makes sense. (still didn't work though ;))

I previous used an PHP API example for Poloniex that did:
```
// generate a nonce to avoid problems with 32bit systems
			$mt = explode(' ', microtime());
			$req['nonce'] = $mt[1].substr($mt[0], 2, 6);
```
Which worked. I will try to get this in the extend.

**Comment by kroitor** [comment]
> I will try to get this in the extend.

I would not recommend this. I would recommend to create a new key and don't redefine the nonce at all.

**Comment by bakman2** [comment]
You are right, a new key works. This is weird. Poloniex remember the first API call or how does this work ?

**Comment by kroitor** [comment]
> how does this work ?
They remember the nonce.
- https://github.com/ccxt/ccxt/wiki/Manual#authentication
If you already used your key with a nonce, the next nonce should be greater than the previous. If you used your key with some other script, your nonce will be set by that script. With a new key you have the nonce reset. Therefore there is no conflict. In ccxt the nonce for poloniex is the UTC timestamp in milliseconds.
