### ISSUE TITLE
Bybit; cannot cancel-all stop-order

### ISSUE THREAD

**Issue by shungikuk** [ccxt/ccxt#11711]
- OS: Windows 11
- Programming Language version: Python 3.9.5
- CCXT version: 1.70.86

```
byb = ccxt.bybit(
    {
        "apiKey": ,
        "secret": ,
        "enableRateLimit": True,
        "options": {
            "adjustForTimeDifference": True,
            # "cancelAllOrders": {"method": ""}
        }
    }
)
byb.cancel_all_orders("BTC/USDT", params={})
```

```
fetch Response: bybit POST https://api.bybit.com/private/linear/order/cancel-all 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '178', ...
```
Hi. I need to POST "https://api.bybit.com/private/linear/stop-order/cancel-all" but I don't know how to specify the endpoint.
In bybit.py, row396, I see the endpoint registered.
And looking into row2064, it seems there are no way to specify the endpoint with options.
Should I wait for future updates or may I be missing something?

**Comment by kroitor** [comment]
@shungikuk i'm rewriting Bybit right now and will hopefully add the full support for spot orders in one of the upcoming versions of CCXT. In the meantime, you can do that using the implicit api:

- https://docs.ccxt.com/en/latest/manual.html#implicit-api 
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api

```Python
import ccxt
exchange = ccxt.bybit()
methods = list(dir(exchange))
for method in methods:
    if 'stop' in method:
        print(method)
```

**Comment by shungikuk** [comment]
@kroitor Thank you for the reply! I'll be using implicit api until it's done.
