### ISSUE TITLE
ccxt.base.errors.BadRequest: binance {"code":-1100,"msg":"Illegal characters found in parameter 'quantity'; legal range is '^([0-9].

### ISSUE THREAD

**Issue by MananGu** [ccxt/ccxt#11739]
Please Refer [#11667](https://github.com/ccxt/ccxt/issues/11667)

**Comment by kroitor** [comment]
I suggest to move this discussion in the original issue, to keep it in one place: https://github.com/ccxt/ccxt/issues/11667#issuecomment-1024286697

**Comment by MananGu** [comment]
Thanks.. Just For informing i made this issue... thanks
