### ISSUE TITLE
binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}

### ISSUE THREAD

**Issue by csidi90** [ccxt/ccxt#11738]
Sometimes, not always get this error message when starting my project.

The backend is hosted on AWS EC2 instance. I am wondering how I can prevent it from crashing due to this error. I am kind of clueless as it does not always accure. On starp up I create many exchange instances (kucoin, coinbasepro, gateio and binance) this error only occurs on binance somehow.

`constructor(ctx) {
    this.id = ctx.id;
    this.exchange = new ccxt[ctx.id]({ enableRateLimit: true });
    this.exchange.rateLimit = true;
    this.exchange.apiKey = ctx.key;
    this.exchange.secret = ctx.secret;
    this.exchange.password = ctx.password;
    this.balance = null;
    this.tickers = null;
    this.convertQuoteAssets = ctx.convertQuoteAssets;
    this.useAllFunds = ctx.useAllFunds;
    this.active = ctx.active;
    this.exchangeService = new ExchangeService();
  }`

**Comment by csidi90** [comment]
I changed code to this but still get the same error. Am I doing something wrong here?

`    if(this.id === "binance"){
      console.log("setting binance options")
      options["adjustForTimeDifference"] = true;
      console.log(options);
    }
    this.exchange = new ccxt[ctx.id]({ enableRateLimit: true, options });`

**Comment by kroitor** [comment]
```JavaScript
const ccxt = require('ccxt')

console.log('CCXT Version:', ccxt.version)

async function main() {
    const ccxt = new ccxt.binance({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET',
        'options': {
            'adjustForTimeDifferrence': true,
        },
    })

    await exchange.loadMarkets ();
    
    while (true) {
        try {
            const balance = await exchange.fetchBalance ();
            console.log(balance)
        } catch(e) {
            console.log(e.constructor.name, e.message)
        }
    }
}

main()
```

↑ That works for me, let me know if it does not work for you.

**Comment by csidi90** [comment]
Doesnt work, still get the same error
| (node:1) UnhandledPromiseRejectionWarning: InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}

**Comment by kroitor** [comment]
@csidi90 enable your verbose output and paste it here:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

```JavaScript
const ccxt = require('ccxt')

console.log('CCXT Version:', ccxt.version)

async function main() {
    const ccxt = new ccxt.binance({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET',
        'options': {
            'adjustForTimeDifference': true,
        },
    })

    exchange.verbose = true // <-------------------------------------- add this

    await exchange.loadMarkets ();
        
    while (true) {
        try {
            const balance = await exchange.fetchBalance ();
            console.log(balance)
        } catch(e) {
            console.log(e.constructor.name, e.message)
        }
    }
}

main()
```

**Comment by csidi90** [comment]
I found out that if I run this app locally I dont get the error anymore. Just when I run this inside a docker container. This is probably not related to this library but maybe you came across this issue already?

**Comment by kroitor** [comment]
> I found out that if I run this app locally I dont get the error anymore. Just when I run this inside a docker container. This is probably not related to this library but maybe you came across this issue already?

Configure system clock sync in the docker container as mentioned here: https://github.com/ccxt/ccxt/issues/850

**Comment by csidi90** [comment]
thank you
