### ISSUE TITLE
futures fetch_balance returns balances=0.0

### ISSUE THREAD

**Issue by pedruntu** [ccxt/ccxt#11741]
Hi, I'm working with ccxt version 1.62.29 in python.
I have a testnet futures account in binance, which has 100000 USDT as margin balance. I can see it at testnet.binancefuture.com plataform. But I would like to get that data with my python script, using ccxt.
Mi code is:

```
import sys
import numpy as np
import ccxt


from sandapi01 import *  #Sandbox futures
#from config_01 import *  #real futures

print('ccxt version:',ccxt.__version__ )

# from variable id
exchange_id = 'binance'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
   "apiKey": API[exchange_id],
    "secret": SECRET[exchange_id],
    "adjustForTimeDifference": True,
    "enableRateLimit": True,
    "options": {
        'defaultType': 'future',
    },
})

print('nombre:', exchange.name)
markets = exchange.load_markets()
print(exchange.requiredCredentials)  

balances= exchange.fetch_balance()
print(balances['USDT'])

```

And what I get is:

```
ccxt version: 1.62.29
nombre: Binance
{'apiKey': True, 'secret': True, 'uid': False, 'login': False, 'password': False, 'twofa': False, 'privateKey': False, 'walletAddress': False, 'token': False}
{'free': 0.0, 'used': 0.0, 'total': 0.0}
```
As you can see, the values are all zeros, and I don't know how to get the actual USDT balance.

**Comment by kroitor** [comment]
@pedruntu you must set sandbox mode and use the futures-testnet api keys:

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binanceusdm({
   "apiKey": 'YOUR_FUTURES_TESTNET_API_KEY',
    "secret": 'YOUR_FUTURES_TESTNET_API_SECRET',
})

exchanges.set_sandbox_mode(True)
markets = exchange.load_markets()

# exchange.verbose = True  # uncomment for debugging purposes

balances= exchange.fetch_balance()
print(balances['USDT'])
```

Let us know if the above helps or not.

**Comment by pedruntu** [comment]
Thank you kroitor.
I was already using testnet API keys. Now I added "exchanges.set_sandbox_mode(True)", but the result is the following:

`ccxt version: 1.62.29
nombre: Binance
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 615, in fetch
    response.raise_for_status()
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://testnet.binancefuture.com/fapi/v2/account?timestamp=1643488205060&recvWindow=5000&signature=c90c5e175a98ef11f99172f40b885c88e63b33c575cf3b8a31f3cf98bccae4cc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sand_pru03.py", line 31, in <module>
    balances= exchange.fetch_balance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\binance.py", line 1405, in fetch_balance
    response = getattr(self, method)(query)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 459, in inner
    return entry(_self, **inner_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\binance.py", line 4548, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 504, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 631, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\binance.py", line 4528, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 522, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action, request ip: 181.169.162.17"}`

**Comment by kroitor** [comment]
@pedruntu you have created those keys on the futures testnet website here: https://testnet.binancefuture.com/ , right ?

**Comment by pedruntu** [comment]
Yes kroitor,that's what I did, I generate the keys in testnet.binancefuture.com/, different from those I generated into https://www.binance.com/es/futures.
And both work ok with other sentences, for example:

`print('nombre:', exchange.name)
exchange.set_sandbox_mode(True)
markets = exchange.load_markets()

book = exchange.fetch_order_book('BTC/USDT')
print('BTC/USDT:',book['asks'][0][0])`

and I get
`nombre: Binance
BTC/USDT: 38608.7`

**Comment by kroitor** [comment]
@pedruntu does this snippet work for you (with my testnet keys):

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binanceusdm({
        "apiKey": "16db8b4176457d63fdc0fd8b2c9418f669237cc9620c8c04c3b8973c7e0c39b3",
        "secret": "a0d07130b34f3debfcfe29d9faf5d2fcf6bdc3b83566d03a0a973a6bc4ab90a4"
})

exchange.set_sandbox_mode(True)
markets = exchange.load_markets()

# exchange.verbose = True  # uncomment for debugging purposes

balances= exchange.fetch_balance()
print(balances['USDT'])
```

If it works with my keypair, then replace it with your keys. If it doesn't work with your keys, check your keys (make sure they're correct and you've set proper permissions on them, if necessary, recreate your keypair and try a fresh new keypair, see: https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting )

**Comment by pedruntu** [comment]
Thank you Kroitor, that code works. I will do later what you say.
Thanks again and best regards
