### ISSUE TITLE
New Exchange: wallex

### ISSUE THREAD

**Issue by knowledgecomputer2018** [ccxt/ccxt#11745]
hi 
how are you . thank you very much for "ccxt" library .please add  cryptocurrency exchange "wallex" in your ccxt library.
this is link exchange:

https://wallex.ir/app/

this is api cryptocurrency exchange:
https://api-docs.wallex.ir/#267d5dc5d0

the wallex exchange have four language support .

thank you very much for reply me .

good luck
god willing

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/10854

**Comment by knowledgecomputer2018** [comment]
hi mr @kroitor
what is result ?
are you add exchange in ccxt or no ?

thank you very much for reply me .

good luck 
god willing

**Comment by kroitor** [comment]
@knowledgecomputer2018 we will add the support for wallex as soon as we can: https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar
