### ISSUE TITLE
publicGetExchangeInfo() method not defined

### ISSUE THREAD

**Issue by jlheidecker** [ccxt/ccxt#1174]
I see "publicGetExchangeInfo()" called in several files, including binance.php. But I don't see that method defined anywhere...
how is this call supposed to work without it being defined anywhere?

```
public function fetch_markets () {
        $response = $this->publicGetExchangeInfo ();
```

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#implicit-api-methods
