### ISSUE TITLE
ccxt.base.errors.RequestTimeout: ftx GET https://ftx.com/api/markets/BNB/USD

### ISSUE THREAD

**Issue by AndDufresne** [ccxt/ccxt#11751]
I got this error message every time when the code had run for about an hour.

Error message "ccxt.base.errors.RequestTimeout: ftx GET https://ftx.com/api/markets/BNB/USD"

**Comment by AndDufresne** [comment]
The issue only occurs with BNB. There is no issue with any other coins.

**Comment by kroitor** [comment]
@AndDufresne intermittent timeouts can happen, add the error handling as described in the Manual and simple try-catch-retry logic as shown in the examples:

- https://github.com/ccxt/ccxt/wiki/Manual#error-handling
- https://docs.ccxt.com/en/latest/manual.html#error-handling
- https://github.com/ccxt/ccxt/tree/master/examples

Let us know if that does not answer your question. Feel free to reopen it if necessary, or just ask further questions if any. In general, we need the following info to be able to help: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by AndDufresne** [comment]
@kroitor Could you please show me how to add a 'simple try-catch-retry logic' to my code.
I kinda newbie for coding.
Thank you in advance.

`import ccxt
import pandas_ta as ta
import pandas as pd
import schedule
from datetime import datetime
import time
pd.set_option('display.max_rows', None)

exchange = ccxt.ftx({
    'apiKey': '',
    'secret': '',
})

# Calculating the position size
balances = exchange.fetch_balance()
# fetch the BNB/USD ticker for use in converting assets to price in USD
BNB_ticker = exchange.fetch_ticker('BNB/USD')
# calculate the ticker price of BNB in terms of USD by taking the midpoint of the best bid and ask
BNB_price_USD = (float(BNB_ticker['bid']) + float(BNB_ticker['ask'])) / 2


in_position = False
if balances['total']['BNB'] * BNB_price_USD >= 3.5:
    in_position = True


def check_buy_sell_signals(df):
    global in_position

    # Calculating the position size
    balances = exchange.fetch_balance()

    # fetch the BNB/USD ticker for use in converting assets to price in USD
    BNB_ticker = exchange.fetch_ticker('BNB/USD')
    # calculate the ticker price of BNB in terms of USD by taking the midpoint of the best bid and ask
    BNB_price_USD = (float(BNB_ticker['bid']) + float(BNB_ticker['ask'])) / 2

    order_size_buy = float(balances['total']['USD']) / float(BNB_price_USD)
    order_size_sell = balances['total']['BNB']
 
    print("checking for buy and sell signals")
    print(df.tail(3))
    last_row_index = len(df.index) - 1
    previous_row_index = last_row_index -1

    if df['SPT'][previous_row_index] == -1 and df['SPT'][last_row_index] == 1:
        print("BNB changed to uptrend, buy")
        if not in_position:
            order = exchange.create_market_buy_order('BNB/USD', order_size_buy)
            print(order)
            in_position = True
        else:
            print("already in position, nothing to do")

    if df['SPT'][previous_row_index] == 1 and df['SPT'][last_row_index] == 1:
        print("BNB currently in uptrend, buy")
        if not in_position:
            order = exchange.create_market_buy_order('BNB/USD', order_size_buy)
            print(order)
            in_position = True
        else:
            print("already in position, nothing to do")

    if df['SPT'][previous_row_index] == 1 and df['SPT'][last_row_index] == -1:
        print("BNB changed to downtrend, sell")
        if in_position:
            order = exchange.create_market_sell_order('BNB/USD', order_size_sell)
            print(order)
            in_position = False
        else:
            print("You aren't in position, nothing to sell")

    if df['SPT'][previous_row_index] == -1 and df['SPT'][last_row_index] == -1:
        print("BNB currently in downtrend, sell")
        if in_position:
            order = exchange.create_market_sell_order('BNB/USD', order_size_sell)
            print(order)
            in_position = False
        else:
            print("You aren't in position, nothing to sell")

def run_bot():
    print(f"Fetching data for {datetime.now().isoformat()}")
    bars = exchange.fetch_ohlcv('BNB/USD', timeframe='1m', limit=40)
    df = pd.DataFrame(bars[:-1], columns=['time', 'open', 'high', 'low', 'close', 'volume'])
    df['time'] = pd.to_datetime(df['time'], unit='ms')

    spt = df.ta.supertrend(high=df["high"], low=df["low"], close=df["close"], period=7, multiplier=3)

    df['SPT'] = spt['SUPERTd_7_3.0']

    check_buy_sell_signals(df)

schedule.every().minute.do(run_bot)

while True:
    schedule.run_pending()
    time.sleep(1)`

**Comment by AndDufresne** [comment]
Could you please show me how to add a 'simple try-catch-retry logic' to my code.
I kinda newbie for coding.
Thank you in advance.

`import ccxt
import pandas_ta as ta
import pandas as pd
import schedule
from datetime import datetime
import time
pd.set_option('display.max_rows', None)

exchange = ccxt.ftx({
    'apiKey': '',
    'secret': '',
})

balances = exchange.fetch_balance()
BNB_ticker = exchange.fetch_ticker('BNB/USD')
BNB_price_USD = (float(BNB_ticker['bid']) + float(BNB_ticker['ask'])) / 2

in_position = False
if balances['total']['BNB'] * BNB_price_USD >= 3.5:
    in_position = True

def check_buy_sell_signals(df):
    global in_position

    # Calculating the position size
    balances = exchange.fetch_balance()

    # fetch the BNB/USD ticker for use in converting assets to price in USD
    BNB_ticker = exchange.fetch_ticker('BNB/USD')
    # calculate the ticker price of BNB in terms of USD by taking the midpoint of the best bid and ask
    BNB_price_USD = (float(BNB_ticker['bid']) + float(BNB_ticker['ask'])) / 2

    order_size_buy = float(balances['total']['USD']) / float(BNB_price_USD)
    order_size_sell = balances['total']['BNB']
 
    print("checking for buy and sell signals")
    print(df.tail(3))
    last_row_index = len(df.index) - 1
    previous_row_index = last_row_index -1

    if df['SPT'][previous_row_index] == -1 and df['SPT'][last_row_index] == 1:
        print("BNB changed to uptrend, buy")
        if not in_position:
            order = exchange.create_market_buy_order('BNB/USD', order_size_buy)
            print(order)
            in_position = True
        else:
            print("already in position, nothing to do")

    if df['SPT'][previous_row_index] == 1 and df['SPT'][last_row_index] == 1:
        print("BNB currently in uptrend, buy")
        if not in_position:
            order = exchange.create_market_buy_order('BNB/USD', order_size_buy)
            print(order)
            in_position = True
        else:
            print("already in position, nothing to do")

    if df['SPT'][previous_row_index] == 1 and df['SPT'][last_row_index] == -1:
        print("BNB changed to downtrend, sell")
        if in_position:
            order = exchange.create_market_sell_order('BNB/USD', order_size_sell)
            print(order)
            in_position = False
        else:
            print("You aren't in position, nothing to sell")

    if df['SPT'][previous_row_index] == -1 and df['SPT'][last_row_index] == -1:
        print("BNB currently in downtrend, sell")
        if in_position:
            order = exchange.create_market_sell_order('BNB/USD', order_size_sell)
            print(order)
            in_position = False
        else:
            print("You aren't in position, nothing to sell")

def run_bot():
    print(f"Fetching data for {datetime.now().isoformat()}")
    bars = exchange.fetch_ohlcv('BNB/USD', timeframe='1m', limit=40)
    df = pd.DataFrame(bars[:-1], columns=['time', 'open', 'high', 'low', 'close', 'volume'])
    df['time'] = pd.to_datetime(df['time'], unit='ms')

    spt = df.ta.supertrend(high=df["high"], low=df["low"], close=df["close"], period=7, multiplier=3)

    df['SPT'] = spt['SUPERTd_7_3.0']

    check_buy_sell_signals(df)

schedule.every().minute.do(run_bot)

while True:
    schedule.run_pending()
    time.sleep(1)`

**Comment by kroitor** [comment]
@AndDufresne add it in `run_bot()`:

```Python
import ccxt
import pandas_ta as ta
import pandas as pd
import schedule
from datetime import datetime
import time
pd.set_option('display.max_rows', None)

exchange = ccxt.ftx({
    'apiKey': '',
    'secret': '',
})

balances = exchange.fetch_balance()
BNB_ticker = exchange.fetch_ticker('BNB/USD')
BNB_price_USD = (float(BNB_ticker['bid']) + float(BNB_ticker['ask'])) / 2

in_position = False
if balances['total']['BNB'] * BNB_price_USD >= 3.5:
    in_position = True

def check_buy_sell_signals(df):
    global in_position

    # Calculating the position size
    balances = exchange.fetch_balance()

    # fetch the BNB/USD ticker for use in converting assets to price in USD
    BNB_ticker = exchange.fetch_ticker('BNB/USD')
    # calculate the ticker price of BNB in terms of USD by taking the midpoint of the best bid and ask
    BNB_price_USD = (float(BNB_ticker['bid']) + float(BNB_ticker['ask'])) / 2

    order_size_buy = float(balances['total']['USD']) / float(BNB_price_USD)
    order_size_sell = balances['total']['BNB']
 
    print("checking for buy and sell signals")
    print(df.tail(3))
    last_row_index = len(df.index) - 1
    previous_row_index = last_row_index -1

    if df['SPT'][previous_row_index] == -1 and df['SPT'][last_row_index] == 1:
        print("BNB changed to uptrend, buy")
        if not in_position:
            order = exchange.create_market_buy_order('BNB/USD', order_size_buy)
            print(order)
            in_position = True
        else:
            print("already in position, nothing to do")

    if df['SPT'][previous_row_index] == 1 and df['SPT'][last_row_index] == 1:
        print("BNB currently in uptrend, buy")
        if not in_position:
            order = exchange.create_market_buy_order('BNB/USD', order_size_buy)
            print(order)
            in_position = True
        else:
            print("already in position, nothing to do")

    if df['SPT'][previous_row_index] == 1 and df['SPT'][last_row_index] == -1:
        print("BNB changed to downtrend, sell")
        if in_position:
            order = exchange.create_market_sell_order('BNB/USD', order_size_sell)
            print(order)
            in_position = False
        else:
            print("You aren't in position, nothing to sell")

    if df['SPT'][previous_row_index] == -1 and df['SPT'][last_row_index] == -1:
        print("BNB currently in downtrend, sell")
        if in_position:
            order = exchange.create_market_sell_order('BNB/USD', order_size_sell)
            print(order)
            in_position = False
        else:
            print("You aren't in position, nothing to sell")

def run_bot():
    
    try:

        print(f"Fetching data for {datetime.now().isoformat()}")
        bars = exchange.fetch_ohlcv('BNB/USD', timeframe='1m', limit=40)
        df = pd.DataFrame(bars[:-1], columns=['time', 'open', 'high', 'low', 'close', 'volume'])
        df['time'] = pd.to_datetime(df['time'], unit='ms')

        spt = df.ta.supertrend(high=df["high"], low=df["low"], close=df["close"], period=7, multiplier=3)

        df['SPT'] = spt['SUPERTd_7_3.0']
        check_buy_sell_signals(df)

    except Exception as e:

        print(type(e).__name__, str(e))

schedule.every().minute.do(run_bot)

while True:
    schedule.run_pending()
    time.sleep(1)
```

**Comment by AndDufresne** [comment]
@kroitor Appreciate your kind support. Your version of the code is running well.
But I also did run my version of the code (without try:) and did not face any issue after updating the CCXT from 1.5x.xx to 1.71.41 .
Hope this information is useful.
Thanks again.
