### ISSUE TITLE
Bybit spot wallet balance

### ISSUE THREAD

**Issue by Mikeardy** [ccxt/ccxt#11763]
Hi,

I'd like to use CCXT with Bybit spot market in Python,
but just starting I need to acquire spot wallet balance and apparently there is no method in CCXT to achieve this task.
According to Bybit documentation must be used a GET HTTP method with /spot/v1/account endpoint.
[https://bybit-exchange.github.io/docs/spot/?python--pybit#t-balance](url)

could someone clarify this?
Thank you

**Comment by kroitor** [comment]
See this issue:

- https://github.com/ccxt/ccxt/issues/9803

Assuming you have the most recent version of CCXT, you can do that using the implicit API:

- https://docs.ccxt.com/en/latest/manual.html#implicit-api
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)

exchange = ccxt.bybit({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

markets = exchange.load_markets()

# exchange.verbose = True  # uncomment for debugging purposes if necessary

response = exchange.private_get_spot_v1_account()
print(response)
```

We are working on the unification of Bybit right now.
