### ISSUE TITLE
Binance fetch_tickers now using /BookTicker

### ISSUE THREAD

**Issue by any1one** [ccxt/ccxt#1177]
Hi,
In this commit : 
https://github.com/ccxt/ccxt/commit/d16430ab452fe46cf3b4d1a8b2c13173d5bb52fa#diff-fca6a36dd2b907e9a5d03ff5598659b9

A change has been made to use /BookTicker instead of /24hr for fetching tickers.
Is there a specific reason ? Because /BookTicker returns a lot less informations, it doesn't even returns the last price.

So now if i wan't to fetch all the last prices for all tickers at once, i have to make a request per asset.

Thanks for the clarification !

Edit : Just saw the release changelog the reason seems to be the rate limiting. That's understandable, but the behaviour is not so unified with other apis now, having at leat the last price would be useful

**Comment by any1one** [comment]
After reading the binance docs, i get the reason.
but still, if we could have a way to force the use of /24hr in order to get all the data, it could be useful, at least it makes sense to me :)
Thx.

**Comment by kroitor** [comment]
Hi!

> So now if i wan't to fetch all the last prices for all tickers at once, i have to make a request per asset.

No you don't, all endpoints still work:

```Python
import ccxt
binance = ccxt.binance()
binance.load_markets()
prices = binance.public_get_ticker_price()
prices_by_id = binance.index_by(prices, 'symbol')
tickers = binance.public_get_ticker_24hr()
tickers_by_id = binance.index_by(tickers, 'symbol')
market = binance.markets['ETH/BTC']
print(prices_by_id[market['id']])
print(tickers_by_id[market['id']])
```

Let me know if this helps.

**Comment by any1one** [comment]
My comment wasn't clear i think. There's no problem fetching all the data, your sample is a good exemple.
What's bugging me is that my goal was to make a unified method to get all data from different exchanges with the same method, but with this change i have to make a specific logic for binance.

My suggestion would have been to introduce a parameter like forceFullData to fetch_tickers, would that make sense ?

**Comment by kroitor** [comment]
@any1one do you think adding that flag to the method signature would be necessary for all exchanges, even though this particular issue is specific to Binance? I would rather add an exchange-specific flag like `binance = ccxt.binance ({'fetchFullTickers': True})`. It would enable the other endpoint for Binance's fetchTickers, and for the rest of exchanges it would do nothing. How does that sound?

**Comment by any1one** [comment]
The exchange-specific flag is a good idea, but i don't know if this is specific to binance. The same issue could happen for another exchange. It's still a better option that mine :)

In my case, either the exchange-specific flag or the `fetchFullTickers` would work for me, as i can make it generic enough to reuse my code across all exchanges.

**Comment by mkutny** [comment]
My 2 cents, if you care )

From the unification perspective, I'd say it should be quite opposite. As binance has lighter and faster alternative for full-fledged ticker as we know it, I'd rather create `fetchLightTicker()` (or `fetchBidAsk()`) for it.

Also, as I understand them, tickers are not for real-time trading, they are for general market discovery, something similar to what coinmarketcap provides. 

If one needs a tool for real-time price discovery more appropriate would be fetching orderbooks with depth 1 (actually, we can provide such `fetchLightTicker()` emulation for the exchanges that support depth parameter).

That's my IMHO, I might be wrong, of course )

**Comment by kroitor** [comment]
@mkutny added fetchFullTickers() method in 1.10.641 %) We might add fetchPrices later as well, however, there's a slight difference between the `'last'` price of a ticker (last trade) and `'bid/ask'` prices. This seems very Binance-specific for now, but we can still consider changing it if we encounter more exchanges with those limitations in future. I would close this for now. Thanks! )

**Comment by mkutny** [comment]
> This seems very Binance-specific for now

That's true... Now see, how counter-intuitive this approach of handling this outlier.

- was (consistent naming): `fetchTickers` <=> `fetchTicker`(except binance)
- now (inconsistent naming): `fetchFullTickers` <=> `fetchTicker`

Now I have a logic like that in my code:
```
if (hasTickers)
  fetchTickers
else
 for (all symbols)
   fetchTicker(symbol)
```

Now I have to switch it to
```
if (hasFullTickers)
```
so it's a bit breaking change. Moreover, this change now requires adding `hasFullTickers` flag to **all** the exchanges.

Handling outlier this way we need to change almost all the exchanges.

If we had `fetchLightTicker` for binance that wouldn't require to change anything else at all.

**Comment by kroitor** [comment]
> Now I have to switch it to

Do you really have to? ) I mean, if you were ok with that code, you can still use it as is, the added change should not break it. It was not a replacement, more like an addition to the standard set if you like (the goal is to be as light on rate-limit as possible). 

However, if you prefer the full info, then in fact you have the point, but then this also boils down to a *break old fetchTickers for Binance* vs *add the fetchFullTickers + flags* tradeoff. Binance ML-based rate-limiter is overly sensitive now and if you try to do fetch(Full)Tickers (the full 24hr ticker info) twice subsequently if will ban the IP for some not very long time. This was the reason for switching to price-only tickers by default for Binance.
