### ISSUE TITLE
FTX: fetch_markets has no limits amount min value anymore since 1.71.42

### ISSUE THREAD

**Issue by marcoismobile** [ccxt/ccxt#11788]
In version **1.71.42**, the _fetch_markets_ code was changed for the FTX exchange.
This fixed the wrong usage of **sizeIncrement** for the '_limits amount min_' value:
https://github.com/ccxt/ccxt/blob/60b49e1f74d10ea42734ec9f0c7e20de07ac4585/python/ccxt/async_support/ftx.py#L644

Currently this value is hardcoded to **None**, but according to the FTX api documentation the **minProvideSize** variable can be used for this.
```
minProvideSize | number | 0.001 | Minimum maker order size (if >10 orders per hour fall below this size)
```
https://docs.ftx.com/#get-markets

Would it be possible to use above value for the '_limits amount min_' ?

**Comment by kroitor** [comment]
@marcoismobile i think `minProvideSize` is about maker-orders only ? It does not hold for market orders. So it would not be entirely correct to use it for the min amount limit. You can still get it from `market['info']['minProvideSize']`. Hope that answers the issue. Let us know if not. Feel free to reopen it or just ask further questions here if any.
