### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'isDustTrade' in <     at binance.parseTrade 

### ISSUE THREAD

**Issue by csidi90** [ccxt/ccxt#11789]
When trying to use the fetchMyTrades method I get this error back. Any way of dealing with this?

TypeError: Cannot use 'in' operator to search for 'isDustTrade' in <
    at binance.parseTrade (C:\Users\thehe\Documents\workspace\work\crypto-trade-api\node_modules\ccxt\js\binance.js:2225:27)
    
    
    ` if (market) {
                const tempTrades = await this.exchange.fetchMyTrades(symbol, fromDate, 10)
                
                if (tempTrades) {
                  trades = [...trades, ...tempTrades]
                }
              }`

**Comment by kroitor** [comment]
@csidi90 please, paste your complete verbose request+response:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by csidi90** [comment]
It is working for all other exchanges (besides Kucoin seems to be always empty no matter the "since". Anyhow, this error is only thrown for binance and comes from this line of the binance implementation. 

`parseTrade (trade, market = undefined) {
        if ('isDustTrade' in trade) {
            return this.parseDustTrade (trade, market);
        }
        //`

**Comment by kroitor** [comment]
@csidi90 can you please paste your request+response in verbose mode (enable verbose mode and paste it here) ? That would help resolve it faster. We don't need the code from the library, cause we already have it, we mostly need your code and, ideally, your verbose output: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by kroitor** [comment]
> if (!this.exchange.has["fetchMyTrades"]) return;
> try {
>   const balances = [];
>   let trades = [];
>   let fromDate = moment().subtract(7, "days");

@csidi90 your fromDate is wrong, the `since` argument must be an integer in milliseconds throughout CCXT. 

Check your value of `fromDate`:

```JavaScript
if (!this.exchange.has["fetchMyTrades"]) return;
try {
  const balances = [];
  let trades = [];
  let fromDate = moment().subtract(7, "days");
  console.log(fromDate, typeof fromDate) // must be an integer Number
```

**Comment by csidi90** [comment]
you are right I was missing .valueOf in that point. Now that I tried using it tho (1643129652798) I still get an empty result back even tho I did trades on that account.

**Comment by csidi90** [comment]
You are right. I missed the .valueOf() which I even had before but there I was messing up something else lol. All good now, thanks a bunch mate.
