### ISSUE TITLE
Bybit fetch_ledger not showing correct transfer direction

### ISSUE THREAD

**Issue by kennethyuenwc** [ccxt/ccxt#11805]
- OS: Windows 10
- Programming Language version: Python 3.7.3
- CCXT version: 1.17.83

Hi, I found that dictionary key "direction" is not returning the correct values when I am trying to fetch_ledger from my Bybit USDT perpetual account. 

![image](https://user-images.githubusercontent.com/58241056/152091400-64e1c4e7-814d-4b27-a7f0-717621f94ba1.png)

In my account history, it is showing a 4USDT transfer in, and 5USDT transfer out, but in the output, both are showing "in" for "direction".

Can this be solved in the back end? 
Or is there other way that I can fetch the "transfer in" & "transfer out" over a specfic period of time?

Thanks

```
bybit = ccxt.bybit({
    'apiKey': '',
    'secret': '',
    'enableRateLimit': True)})

bybit.fetch_ledger(params={"coin":'USDT'})[-2:]

```

```
[{'id': '',
  'currency': 'USDT',
  'account': '',
  'referenceAccount': None,
  'referenceId': 'selfTransfer_b8e002d5-587c-4d2c-8de1-cf846ba80b94',
  'status': None,
  'amount': 4.0,
  'before': 7148.03983616,
  'after': 7152.03983616,
  'fee': None,
  'direction': 'in',
  'timestamp': 1643772896000,
  'datetime': '2022-02-02T03:34:56.000Z',
  'type': 'AccountTransfer',
  'info': {'id': '',
   'user_id': '',
   'coin': 'USDT',
   'wallet_id': '',
   'type': 'AccountTransfer',
   'amount': '4',
   'tx_id': 'selfTransfer_b8e002d5-587c-4d2c-8de1-cf846ba80b94',
   'address': '',
   'wallet_balance': '7152.03983616',
   'exec_time': '2022-02-02T03:34:56Z',
   'cross_seq': '0'}},
 {'id': '',
  'currency': 'USDT',
  'account': '668485',
  'referenceAccount': None,
  'referenceId': 'selfTransfer_07c25215-817e-498b-8181-dd82fd078f2d',
  'status': None,
  'amount': 5.0,
  'before': 7142.03983616,
  'after': 7147.03983616,
  'fee': None,
  'direction': 'in',
  'timestamp': 1643772971000,
  'datetime': '2022-02-02T03:36:11.000Z',
  'type': 'AccountTransfer',
  'info': {'id': '',
   'user_id': '',
   'coin': 'USDT',
   'wallet_id': '',
   'type': 'AccountTransfer',
   'amount': '5',
   'tx_id': 'selfTransfer_07c25215-817e-498b-8181-dd82fd078f2d',
   'address': '',
   'wallet_balance': '7147.03983616',
   'exec_time': '2022-02-02T03:36:11Z',
   'cross_seq': '0'}}]
```

**Comment by kroitor** [comment]
@kennethyuenwc do they report empty values to you for the id/user_id/wallet_id/address ? Or have you removed them from the output? We need to find a way to distinguish the direction cause both transfers have positive amounts...

**Comment by kroitor** [comment]
@kennethyuenwc since there's no other info that would indicate the direction, we can only set it to `undefined` to reflect the actual truth. What do you think ?

**Comment by kennethyuenwc** [comment]
So it is the meta data issue? If so, is there a channel that we can reflect this to Bybit?

**Comment by kroitor** [comment]
@kennethyuenwc you can see the response from Bybit in the `info` subsection in your own output, and that is the info coming from Bybit's API and there's no indication of whether it's a transfer in or a transfer out. Bybit does have some telegram channels, it would help solve it if you report it there.
