### ISSUE TITLE
xena lastUpdateTime can be None

### ISSUE THREAD

**Issue by Matoran** [ccxt/ccxt#11809]
https://github.com/ccxt/ccxt/blob/847cfa1a51c7dd198099fc25e20101d34952a187/js/xena.js#L539

```
"ccxt/async_support/xena.py", line 500, in fetch_order_book
    timestamp = int(lastUpdateTime / 1000000)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

The program wasn't in verbose mode and can't reproduce. Maybe the API responded with no last update time once.

**Comment by carlosmiei** [comment]
Hello @Matoran,
I can't reproduce it either, but I'll protect the code nevertheless.

Thanks for reporting!
