### ISSUE TITLE
Binance - order by usdt amount instead of quantity

### ISSUE THREAD

**Issue by rekatop** [ccxt/ccxt#11816]
Hello friends, I am looking for a function that sends order by entering the usdt amount but I could not find any function related with this in the manual. So I have been thinking about how to find a way to send order by entering usdt amount. For example, lets say I have 1000$ in my futures account and I want to spend only 500$. We cannot create order like this. Is there any option to calculate manually how much USDT I want to spend or something like this? I open for any ideas. Thank you guys!

**Comment by kroitor** [comment]
@rekatop hi! Are you trading spot markets or futures markets? Binance does support that for the spot markets only, but not for futures yet.

Duplicate:

- https://github.com/ccxt/ccxt/issues/8539
- https://github.com/ccxt/ccxt/issues/7963
- https://github.com/ccxt/ccxt/issues/7853
- ...
- https://github.com/ccxt/ccxt/issues?q=binance+quoteOrderQty

**Comment by rekatop** [comment]
@kroitor futures. Thank you.
