### ISSUE TITLE
CCXT Pro renew issue

### ISSUE THREAD

**Issue by pickmone** [ccxt/ccxt#11814]
Hi, 

I am trying to renew my subscription. Before I have used both credit card option and stable coin option, but seeing that stable coin option no long there, I tried credit card. I live in HK, but for some reason it keep telling me "wrong address". 

thank you,

**Comment by kroitor** [comment]
@pickmone hi! We had to switch off stablecoins due to high ERC20 fees. I will investigate your report and will be back to you shortly.

**Comment by kroitor** [comment]
@pickmone please, contact info@ccxt.trade, we will get it resolved.
