### ISSUE TITLE
Market type.. 'future' or 'swap'?

### ISSUE THREAD

**Issue by christophe-hall** [ccxt/ccxt#11819]
I think the Bitfinex derivatives markets should be marked as type 'swap' instead of 'future'. They are non-expiring perps.

![image](https://user-images.githubusercontent.com/2957821/152247194-915b749e-b222-4b41-b727-024d76b00c2c.png)

I think the same may also apply to binanceusdm markets.

**Comment by christophe-hall** [comment]
Holy shit that was a quick response.

**Comment by kroitor** [comment]
@christophe-hall check these two issues, we're unifying that aspect right now:

- https://github.com/ccxt/ccxt/issues/10931
- https://github.com/ccxt/ccxt/issues/11121

I would suggest to move this discussion there ↑

We will fix bitfinex and binance as soon as we can.
