### ISSUE TITLE
Binance USD-m timeInForce is GTX instead of PO

### ISSUE THREAD

**Issue by mattepozz** [ccxt/ccxt#11830]
- OS: MacOs
- Programming Language version: Python 3.9
- CCXT version: 1.71.96

```python
credentials = ...
exchange = binanceusdm()
exchange.apiKey = credentials.api_key
exchange.secret = credentials.api_secret

order = exchange.create_limit_buy_order(
    symbol="BTC/USDT", amount=0.001, price=30000, params={"timeInForce": "GTX"}
)

# Expected timeInForce: PO
print(f"timeInForce={order['timeInForce']}")
# timeInForce=GTX

```

Post-only orders on Binance Futures have `timeInForce=GTX`. However, this is [not a valid](https://docs.ccxt.com/en/latest/manual.html#order-structure) CCXT value: it should be `PO`.

**Comment by frosty00** [comment]
why would it be PO if you set it to GTX?
