### ISSUE TITLE
FTX market()  min amount returns None

### ISSUE THREAD

**Issue by Princeton007** [ccxt/ccxt#11835]
- OS: Windows 1ß
- Programming Language version: Python
- CCXT version: 1.71.99

The latest version doesn't return the min amount, instead it returns None

```
exchange = ccxt.ftx({
    'enableRateLimit': True,
    'verbose': False,
    'apiKey': apikey,
    'secret': secret,
})
symbol = 'ETH-PERP'
exchange.load_markets()
market = exchange.market(symbol)
pprint(market)
```

CCXT version: 1.62.68		 

 'limits': {'amount': {'max': None, 'min': 0.001},
            'cost': {'max': None, 'min': None},
            'leverage': {'max': 20},
            'price': {'max': None, 'min': 0.1}},

CCXT version: 1.71.99

 'limits': {'amount': {'max': None, 'min': None},
            'cost': {'max': None, 'min': None},
            'leverage': {'max': 20.0, 'min': 1.0},
            'price': {'max': None, 'min': None}},

**Comment by kroitor** [comment]
Those limits were incorrect in 1.62.68+.
This is answered here: https://github.com/ccxt/ccxt/issues/11788

As you can see from the `info` substructure inside each market – that contains the exchange information as is, untouched, and there's no indication of min amount or min price there.

```Python
exchange = ccxt.ftx({
    'enableRateLimit': True,
    'verbose': False,
    'apiKey': apikey,
    'secret': secret,
})
symbol = 'ETH-PERP'
exchange.load_markets()
market = exchange.market(symbol)
pprint(market)
```

**Comment by Princeton007** [comment]
Indeed, I was assuming it'identical to sminProvideSize. 
Thanks!
