### ISSUE TITLE
fetchOrderBook is not giving me the correct length of values

### ISSUE THREAD

**Issue by bonetjoshua** [ccxt/ccxt#11838]
- OS: Microsoft
- Programming Language version: Python
- CCXT version: 1.7

``
exchange.enableRateLimit = True
exchange.fetchOrderBook('BTC/USD', 5)
```

```
![Screenshot 2022-02-03 151427](https://user-images.githubusercontent.com/51464032/152445137-49b341e2-ee18-465c-aa04-70ee9c9b7d5e.jpg)
I don't know if the image was able to upload so let me copy paste:
{'symbol': 'BTC/USD', 'bids': [[37041.67, 0.00247913], [37038.76, 0.09562471], [37038.75, 0.03829943], [37037.75, 0.030384], [37037.73, 0.03300677], [37036.97, 0.03576075], [37035.67, 0.23], [37035.66, 0.30396961], [37026.71, 0.06], [37026.7, 0.00652436], [37025.92, 0.19507156], [37025.91, 1.55187596], [37025.9, 0.00092286], [37024.69, 0.96936218], [37024.68, 0.69231471], [37024.67, 0.91156209], [37024.66, 0.002], [37023.62, 0.1], [37022.83, 0.1], [37022.82, 0.00651684], [37021.59, 0.18364303], [37020.87, 0.15], [37020.86, 0.02819902], [37020.76, 0.05639768], [37020.67, 1.8946], [37016.67, 0.09681308], [37012.42, 1.2979297], [37012.41, 0.13767028], [37012.4, 0.27206529], [37012.33, 0.001], [37011.3, 0.068], [37010.46, 0.05640326], [37010.33, 0.07050473], [37008.64, 0.01], [37008.63, 0.01408736], [37006.6, 0.05639113], [37005.44, 0.503], [37005.08, 0.2], [37004.57, 0.039], [37004.49, 0.15510896], [37003.92, 0.08287018], [37003.57, 0.1], [37003.23, 0.04981582], [37003.22, 0.05634942], [37002.21, 0.26208632], [37000.1, 0.676], [37000.0, 1.0], [36997.65, 0.05639336], [36996.37, 0.4], [36995.56, 0.02703027], [36993.35, 0.01421544], [36991.66, 0.0515344], [36991.45, 0.1], [36991.17, 0.08594578], [36989.94, 0.04022128], [36989.82, 0.01351723], [36988.96, 0.19749846], [36988.46, 0.093], [36987.97, 0.09779284], [36986.89, 0.20529697], [36986.39, 0.03867653], [36980.11, 0.001], [36979.68, 0.051216], [36979.67, 2.0], [36973.33, 0.04056978], [36973.04, 0.072], [36970.0, 0.00082868], [36968.04, 0.09096103], [36967.82, 0.19402247], [36966.38, 0.08077784], [36966.21, 0.15736305], [36964.53, 0.04414449], [36963.69, 0.41940512], [36962.34, 0.0512024], [36960.05, 0.00010282], [36960.0, 0.00082874], [36958.51, 0.20852414], [36957.35, 1.689], [36953.28, 0.07360438], [36953.22, 0.05368], [36953.15, 0.06387978], [36950.0, 0.00082899], [36949.31, 6.75064623], [36948.68, 0.00257183], [36947.94, 0.001], [36945.35, 0.08176286], [36940.0, 0.00082921], [36937.54, 0.03714839], [36932.72, 1.0], [36930.93, 0.10265737], [36930.0, 0.00082943], [36929.94, 0.27934676], [36929.21, 0.17115191], [36929.17, 0.0480344], [36925.6, 0.04839406], [36923.69, 0.36796709], [36920.0, 0.00082981], [36913.01, 0.06550761], [36911.72, 0.07301674], [36910.0, 0.00077558], [36909.99, 1.009], [36909.98, 1.351], [36905.33, 0.00184808], [36902.73, 2.988e-05], [36900.0, 0.02583079], [36898.06, 2.988e-05], [36893.39, 0.0008452], [36893.38, 2.988e-05], [36891.74, 0.83328533], [36890.73, 3.997], [36890.0, 0.00083101], [36888.7, 2.989e-05], [36884.02, 2.989e-05], [36884.0, 0.01354197], [36881.71, 0.00010282], [36880.91, 0.001], [36880.0, 0.00083117], [36879.33, 2.989e-05], [36874.64, 2.989e-05], [36871.52, 0.0540677], [36871.51, 10.558], [36870.0, 0.00083158], [36869.95, 2.989e-05], [36865.25, 2.989e-05], [36860.54, 2.99e-05], [36860.33, 0.0021677], [36860.0, 0.00083161], [36855.83, 2.99e-05], [36854.88, 0.83328533], [36851.12, 2.99e-05], [36850.02, 1.12155364], [36850.0, 0.00433247], [36847.4, 0.001], [36846.4, 2.99e-05], [36841.68, 2.99e-05], [36840.47, 0.000901], [36840.0, 0.00083205], [36836.95, 2.991e-05], [36832.22, 2.991e-05], [36830.0, 0.0008323], [36829.58, 0.001], [36827.48, 2.991e-05], [36825.0, 0.75998951], [36822.74, 2.991e-05], [36822.31, 0.00549167], [36820.0, 0.00071237], [36818.06, 0.83328533], [36817.99, 2.991e-05], [36813.24, 2.992e-05], [36810.0, 0.00083112], [36808.49, 2.992e-05], [36806.18, 29.165], 

I just want the last 5 not the entire dictionary

**Comment by kroitor** [comment]
If the underlying exchange does not support a limit parameter CCXT does not limit the bidasks:

- https://github.com/ccxt/ccxt/wiki/Manual#market-depth
- https://docs.ccxt.com/en/latest/manual.html#market-depth

We will add the support for limiting on the client side to the base code soon.

In the meantime, you can easily filter them in the userland with built-in language constructs:

```Python
limit = 5
orderbook = exchange.fetchOrderBook('BTC/USD', 5)
orderbook['bids'] = orderbook['bids'][0:limit]
orderbook['asks'] = orderbook['asks'][0:limit]
```

**Comment by bonetjoshua** [comment]
I appreciate the reply Mr. Kroitor
