### ISSUE TITLE
Gateio fetchMyTrades symbol currency is actually optional

### ISSUE THREAD

**Issue by ebarti** [ccxt/ccxt#11842]
From the documentation of Gateio - fetching the personal trade history does not require a currency_pair

https://www.gate.io/docs/apiv4/en/#list-personal-trading-history

Name | In | Type | Required | Description
-- | -- | -- | -- | --
currency_pair | query | string | true | Retrieve results with specified currency pair. It is required for open orders, but optional for finished ones.

**Comment by samgermain** [comment]
Fixed in https://github.com/ccxt/ccxt/pull/11846#event-6012100342
