### ISSUE TITLE
Okex sandbox problem with watch_orders

### ISSUE THREAD

**Issue by ShieldTrade** [ccxt/ccxt#11855]
OS:Windows 10
Programming Language version: Python 3.9
CCXT Pro Version 0.9.90 ( just subscribed it)
CCXT Version 1.71.96
Exchange Okex sandbox

```
okex_test = ccxtpro.okex({'verbose': True,
                                  'enableRateLimit': False,
                                  'apiKey': '',                                
                                  'secret': '1F,
                                  'password': 'P,
                                  'newUpdates': True,
'                                 'headers': {"x-simulated-trading": 1}, # https://github.com/ccxt/ccxt/pull/11108
                                 ​'options': {
                                     ​'tradesLimit': 1000,
                                     ​'OHLCVLimit': 1000,
                                     ​'ordersLimit': 1000,
                                 ​},
                                 ​})
  okex_test.set_sandbox_mode(True)
  markets = await okex_test.load_markets() 
```
Having instantiated the exchange like in the code above I can send order with no problems (symbol = 'BTC/USDT:USDT'. perpetual swap) but I cannot 

`order = await okex_test.watch_orders(symbol)`

this is the relevant part of the verbose output
```
2022-02-04T16:38:11.273Z sending {'op': 'login', 'args': [{'apiKey': 'xxxxx', 'passphrase': 'xxxxxx', 'timestamp': '1643992690', 'sign': 'BZm+GAl9fBvumwZSJDamHEwjL030NHQRqzoxKpkA7bY='}]}
2022-02-04T16:38:11.469Z message pong
2022-02-04T16:38:11.470Z message {"event":"error","msg":"Broker id of APIKey does not match current environment.","code":"50101"}
2022-02-04T16:38:11.470Z close False WSMessage(type=<WSMsgType.CLOSE: 8>, data=0, extra='')
2022-02-04T16:38:11.470Z on_close 0
Connection closed by remote server, closing code 0
```
It looks like an authentication problem but as I said can send orders to the sandbox with no problems. I read your ccxt pro code and okex api documentation. the watch_order method should work without params and the new V5 API is fully supported [8532](https://github.com/ccxt/ccxt/issues/8532). is it that correct?

Can you please help me

Tx

**Comment by kroitor** [comment]
@ShieldTrade at this time the okex sandbox urls for ws are not fully supported yet, will add that asap.

**Comment by kroitor** [comment]
@ShieldTrade please, upgrade your versions of CCXT to 1.73.35+ and your version of CCXT Pro to 0.9.97.
Let us know if that does not solve the issue for you. Thanks for reporting!

**Comment by ShieldTrade** [comment]
@kroitor now it works. Your assistance is top level. One of the best I found in my career. 

let me report this for for your reference.
After doing 
`pip3 install git+https://github.com/kroitor/ccxt.pro.git#subdirectory=python`

I got
```
Attempting uninstall: ccxt
    Found existing installation: ccxt 1.71.96
    Uninstalling ccxt-1.71.96:
      Successfully uninstalled ccxt-1.71.96
  Attempting uninstall: ccxtpro
    Found existing installation: ccxtpro 0.9.90
    Uninstalling ccxtpro-0.9.90:
      Successfully uninstalled ccxtpro-0.9.90
Successfully installed ccxt-1.72.37 ccxtpro-0.9.97
```
and  `pip install ccxt` did not change ccxt version. 

> upgrade your versions of CCXT to 1.73.35+ and your version of CCXT Pro to 0.9.97

Not the expected CCXT version. but it works fine.
