### ISSUE TITLE
Full (Order-by-order) feed

### ISSUE THREAD

**Issue by tryvalve** [ccxt/ccxt#11864]
Coinbase offers a full feed that includes every order, rather than just an L2 feed: https://docs.cloud.coinbase.com/exchange/docs/channels#the-full-channel

Is this accessible via ccxt or ccxt pro?

**Comment by ttodua** [comment]
the referred api docs not found anymore. also, coinbase-pro had been sunsetting and migrating to `coinbase` (a.k.a. coinbase advanced).
closing this issue
