### ISSUE TITLE
Can't get futures or perpetual swaps markets with gateio

### ISSUE THREAD

**Issue by backfirehzy** [ccxt/ccxt#11877]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10 Professional
- Programming Language version: Python
- CCXT version: 1.72.37

```
class Gateio:
    def __init__(self):
        self.exchange = ccxt.gateio()
        self.markets = self.exchange.load_markets()
        print(self.markets)
```

I can't get futures or perpetual swaps markets with gateio, there are only "spot" markets in self.markets

**Comment by kroitor** [comment]
Use the options-overrides:

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-exchange-properties-upon-instantiation

```Python
class Gateio:
    def __init__(self):
        self.exchange = ccxt.gateio({
            'options': {
                'defaultType': 'swap', // spot, future
            }
        })
        self.markets = self.exchange.load_markets()
        print(self.markets)
```
