### ISSUE TITLE
Gate.io fetchDeposits() and fetchWithdrawals() calculate to large 'to' date

### ISSUE THREAD

**Issue by DoDoSt** [ccxt/ccxt#11879]
- OS: Windows 10
- Programming Language version: NodeJs v16.8.0
- CCXT version: 1.72.37

Both methods contain following date calculation. The input is the since date in milliseconds. For the 'from' parameter it is divided by 1000 to get seconds, which Gate.io requires. But the 'to' calculation doesn't divided by 1000! 

From Gate.io documentation: 
- All time related fields are unix timestamp in seconds if no extra note, ...

```
if (since !== undefined) {
    request['from'] = parseInt (since / 1000);
    request['to'] = since + 30 * 24 * 60 * 60;
}
```

Obviously the requested timerange is far to big with an 'to' date in milliseconds:
```
BadRequest: gateio {"label":"INVALID_PARAM_VALUE","message":"Time span shall not exceed 30 days"}
```

**Comment by kroitor** [comment]
@DoDoSt thanks for reporting, will push a fix now.
