### ISSUE TITLE
What is the proper way to get the subaccounts balance in binance

### ISSUE THREAD

**Issue by israel-gonzalezmedina** [ccxt/ccxt#11895]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: linux
- Programming Language version: JavaScript
- CCXT version: lastest

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

**Comment by npomfret** [comment]
Maybe via this: https://binance-docs.github.io/apidocs/spot/en/#query-managed-sub-account-asset-details-for-investor-master-account

**Comment by kroitor** [comment]
@israel-gonzalezmedina you can do that using the implicit API as documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api
- https://docs.ccxt.com/en/latest/manual.html#implicit-api

Let us know if that does not answer your question. Feel free to reopen it or just ask further questions if any.

**Comment by israel-gonzalezmedina** [comment]
> @israel-gonzalezmedina you can do that using the implicit API as documented in the Manual:
> 
> * https://github.com/ccxt/ccxt/wiki/Manual#implicit-api
> * https://docs.ccxt.com/en/latest/manual.html#implicit-api
> 
> Let us know if that does not answer your question. Feel free to reopen it or just ask further questions if any.

I thank you all for the replay. I just have a doubt about the implicit api's call. It is related to the version. I checked the documentation before and while the implicit api document how make the call using the endpoint, there are no documentation about the version. Are the version taking into account for that?
among the binance subaccounts API endpoints there are call for /sapi/v1, /sapi/v2 e /sapi/v3.

**Comment by kroitor** [comment]
@israel-gonzalezmedina use this script to print out all `sapi` methods currently available in ccxt:

```JavaScript
const ccxt  = require ('./ccxt');
const exchange = new ccxt.binance();
for (const method of Object.keys (exchange)) {
    if (method.indexOf ('sapi') >= 0) {
        console.log (method);
    }
}
```
