### ISSUE TITLE
[bybit] market types (question)

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#11892]
It is correct that most markets in bybit are marked as `swap`?  For example:

```
{ symbol: 'BTC/USD', type: 'swap' }
...
{ symbol: 'BTC/USDT', type: 'swap' }. <-- should this be something else, like 'linear'?
...
{ symbol: 'BTCUSDM22', type: 'future' }
```

**Comment by kroitor** [comment]
Yes, that should be correct, see these related announcements:

- https://github.com/ccxt/ccxt/issues/10931
- https://github.com/ccxt/ccxt/issues/11121

**Comment by kroitor** [comment]
P.S. Please, don't hesitate if you find an inconsistency with it.
