### ISSUE TITLE
Checking open position

### ISSUE THREAD

**Issue by macgormain** [ccxt/ccxt#11899]
- OS: Mac Big Sur 11.2
- Programming Language version: Python 3.9
- CCXT version: 1.72.24

I am unable to ascertain a method to check if I am in an open postion. I have found fetch_closedorders() and fetchOpenorders() others within the documentation. However the language isn't clear whether they are simply showing fills or showing open positions. If fills are being returned, how can I return a True or False value to check if I am in an Open position? 

If anyone could shed some light on the subject I would appreciate it. 

Thanks

**Comment by samgermain** [comment]
@macgormain 

Could you share some of your code? Are you contract trading (Perpetual Swaps, Futures), and is there a specific exchange that you are trying to use?

**Comment by macgormain** [comment]
> @macgormain
> 
> Could you share some of your code? Are you contract trading (Perpetual Swaps, Futures), and is there a specific exchange that you are trying to use?

Don't have enough written to  justify posting. I'm using ftx and yes I'm going to be using Perpetual Swaps. I'm relatively new to coding so I may not be wording my question properly. 

I want to return a true or false value in python to the query of having an open position or trade. I don't think the fetch_ClosedOrders() method returns something quite so simple from what I understand.

**Comment by samgermain** [comment]
> Don't have enough written to justify posting

Just post what you have

**Comment by macgormain** [comment]
```
# import ccxt as ccxt
# import vectorbt as vbt
# import numpy as np
# import pandas as pd

#authentication
# ftx = ccxt.ftx({
#     'apiKey' : ''
#     'secret' : ''
#     'hostname' : 'ftx'
# })

#funciton for checking if in trade, if in trade go to exit
# make function to buy, sell, and exit(only if in trade)

y = "success"
n = "failure"


def in_position():
    return False
# def exit_check():

if in_position():
    print(y)
else:
    print(n)

# def buy_check():
#
# if status_check():
#     exit_check()
# else:
#     buy_check()


############# Graveyard #################

### bot object and method to check instantiation
#class Bot:
#     def __init__(self):
#         self.name = "Bot"
#         self.keys = (api_key, api_secret)
#         return Bot
#     def status(x):
#          print(x)
#print(Bot.status("Success"))

#### authentication checking
#exchange = ccxt.ftx()
#print(exchange.requiredCredentials)  # prints required credentials
#exchange.checkRequiredCredentials()  # raises AuthenticationError
```

**Comment by samgermain** [comment]
> 

Here's an example that checks if your in an open position on FTX, and then closes that position

https://github.com/ccxt/ccxt/blob/master/examples/py/ftx-close-position-reduceOnly.py

**Comment by samgermain** [comment]
I opened a PR ( https://github.com/ccxt/ccxt/pull/11949/files ) with a slightly more clear version of the example.

Feel free to open this issue back up if you have any more questions

**Comment by macgormain** [comment]
Thank you. Looking through the entire documentation helps huh?

**Comment by macgormain** [comment]
> > 
> 
> Here's an example that checks if your in an open position on FTX, and then closes that position
> 
> https://github.com/ccxt/ccxt/blob/master/examples/py/ftx-close-position-reduceOnly.py

where can I find an explanation on the 'ReduceOnly' parameter? I can't find anything in the documentation. I want to understand how it works so I can modify it and make sure it completely closes the position

**Comment by samgermain** [comment]
> > > 
> > 
> > 
> > Here's an example that checks if your in an open position on FTX, and then closes that position
> > https://github.com/ccxt/ccxt/blob/master/examples/py/ftx-close-position-reduceOnly.py
> 
> where can I find an explanation on the 'ReduceOnly' parameter? I can't find anything in the documentation. I want to understand how it works so I can modify it and make sure it completely closes the position

So right now there's not much unification of the parameter, most exchanges specify it in their documentation, which is why you can pass it through `params` and `gateio` can take `reduceOnly` in the `params` argument and then sends the exchange specific `reduce_only` to the `gateio` api. We plan to unify the argument though

**Comment by macgormain** [comment]
Alright that makes sense. It doesn't seem like there is a "CompleteClose" function in either ccxt's or ftx's documentation, I'll have to create a way to detect size and send the command for a 100% closure myself. 

Thank you for all your help

**Comment by samgermain** [comment]
> 

I'll add it sometime soon
