### ISSUE TITLE
(Question) Which API call does Bybit module use (Spot/Perpetual)?

### ISSUE THREAD

**Issue by aekramer** [ccxt/ccxt#11894]
I am trying to get the candles from their inverse perpetual API, but I can't seem to find out which version CCXT is fetching from?

Spot:
https://api.bybit.com/spot/quote/v1/kline 
Docs: https://bybit-exchange.github.io/docs/spot/#t-querykline

Inverse perpetual:
https://api.bybit.com/v2/public/kline/list 
Docs: https://bybit-exchange.github.io/docs/inverse/#t-querykline

**Comment by kroitor** [comment]
You can see that in `verbose` mode:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Add:

```
exchange.verbose = true
```

Before the call of your interest.

Hope that answers your question.

I would highly recommend reading the entire Manual from top to bottom, and, also checking the examples as well:

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://docs.ccxt.com
- https://github.com/ccxt/ccxt/tree/master/examples
