### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by g666nz** [ccxt/ccxt#1191]
So whenever i update to the latest ccxt i receive the following error below. But if i revert back to v 1.7.7, this error does not show then.

I'm currently using node v8.9.4.

<--- Last few GCs --->

[4564:0x25c2a60]   309756 ms: Mark-sweep 1412.6 (1816.7) -> 1412.6 (1794.2) MB, 1095.7 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1158 ms) last resort GC in old space requested
[4564:0x25c2a60]   310923 ms: Mark-sweep 1412.6 (1794.2) -> 1412.6 (1794.2) MB, 1166.1 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x17cc67aa5ee1 <JSObject>
    0: builtin exit frame: set __proto__(this=0x27ec665fa7d9 <Error map = 0x143796edb81>,0x348bf0998dc9 <ExchangeError map = 0x9679dac8249>)

    5: new constructor(aka ExchangeError) [/home/blocknomic/Desktop/CurryCoins-releases/pre-alpha/V0.7.3/engine/node_modules/ccxt/js/base/errors.js:15] [bytecode=0x3cf35ea76f21 offset=52](this=0x27ec665fa7d9 <Error map = 0x143796edb81>,message=0x27ec665fa7...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [total: engine]
 2: 0x121a2cc [total: engine]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [total: engine]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [total: engine]
 5: v8::internal::Factory::CopyFixedArrayAndGrow(v8::internal::Handle<v8::internal::FixedArray>, int, v8::internal::PretenureFlag) [total: engine]
 6: v8::internal::TransitionArray::PutPrototypeTransition(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Map>) [total: engine]
 7: v8::internal::Map::TransitionToPrototype(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Object>) [total: engine]
 8: v8::internal::JSObject::SetPrototype(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Object::ShouldThrow) [total: engine]
 9: v8::internal::JSReceiver::SetPrototype(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Object::ShouldThrow) [total: engine]
10: v8::internal::Builtin_ObjectPrototypeSetProto(int, v8::internal::Object**, v8::internal::Isolate*) [total: engine]
11: 0x1b300f48441d

<--- Last few GCs --->

[4565:0x3fc9a60]   321574 ms: Mark-sweep 1407.4 (1751.7) -> 1407.4 (1749.7) MB, 912.0 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 938 ms) last resort GC in old space requested
[4565:0x3fc9a60]   322518 ms: Mark-sweep 1407.4 (1749.7) -> 1407.4 (1749.7) MB, 942.6 / 0.0 ms  last resort GC in old space requested

**Comment by kroitor** [comment]
Update to most recent version 1.10.649. Your version 1.7.7 is several months old.

**Comment by kroitor** [comment]
@g666nz do you have the same symptoms with node 9+?

**Comment by g666nz** [comment]
haven't tried it with 9+

**Comment by kroitor** [comment]
@g666nz can you post a short but a complete snippet of code that I could copypaste to reproduce you problem?

**Comment by g666nz** [comment]
I'm simply calling the orderBook every three seconds.

**Comment by kroitor** [comment]
@g666nz right, but this can be done in a multitude of ways (rate-limiting, error handling, etc), so we still need to see your code + verbose output, otherwise we can't help. So, can you paste it?

**Comment by g666nz** [comment]
Yes you were right. Was a error handling issue. Cheers

**Comment by kroitor** [comment]
@g666nz thank for reporting back!
