### ISSUE TITLE
Error 'linear' while fetch_positon in ccxt on Binance exchange

### ISSUE THREAD

**Issue by dekreed783** [ccxt/ccxt#11929]
I converted code to .exe file and ran it on cloud computer for buy and sell future order and it can ran without problem ( more than 100 time trade ) then  program error while fetching postion ( exchange.fetch_positions() ) by error code that sent back was 'linear', while it error I use Pycharm to fetch position but it work, while program error 'linear' code ,

What is promblem and how to fix it ?

- CCXT version: 1.60.65
```
import ccxt
BotAPI = ccxt.binanceusdm({'apiKey': api_key, 'secret': secret_key, 'enableRatelimit': True})
..
..
async def fetch_contracts():
    global contracts, EntryPrice, side, er, po
    try:
       con = BotAPI.fetch_positions()
       time.sleep(2)
       po = [symbol_list in i['symbol'] for i in con].index(True)
       contracts = con[po]['contracts']
       EntryPrice = con[po]['entryPrice']
       side = con[po]['side']
  
   except Exception as e:
      print(strftime("##### %Y-%m-%d %H:%M:%S #####\n"))
      print("ERROR : fetch_contracts , PLS CHECK INTERNET OR CODE\n")
      print(e)
      er = e
      time.sleep(3)

await asyncio.create_task(fetch_contracts())      
```
     
Error code that print out was  'linear'
what is promblem and how to fix it ?

**Comment by kroitor** [comment]
> what is promblem and how to fix it ?

Please, upgrade your version of CCXT. Let us know if you have this issue with the most recent version of the library.

I suggest moving this discussion to this duplicate issue:

- https://github.com/ccxt/ccxt/issues/10862
