### ISSUE TITLE
why I get diffrent ohlcvs from ccxt and binance python against exchange

### ISSUE THREAD

**Issue by hossain93** [ccxt/ccxt#11921]
get ohlcvs with ccxt and i get below result for two days
![image](https://user-images.githubusercontent.com/77359545/153462029-6ac46903-c6a1-434a-9ff1-17bf19b44cb9.png)
 and also data from binance python with 'get_historical_klines' and i get below result for last day
![image](https://user-images.githubusercontent.com/77359545/153462374-c02a014d-8332-4684-9ddf-83db5c0b6813.png)
 and binance show diffrent ohlcvs than ccxt and  binance python
![Screenshot (1)](https://user-images.githubusercontent.com/77359545/153464024-1d07b2d7-0a0c-4737-b2f8-1e74257e029a.png)
![Screenshot (2)](https://user-images.githubusercontent.com/77359545/153464030-f3cae0ee-91ef-4bf8-ba04-42f26b67380c.png)

can you help me

**Comment by kroitor** [comment]
@hossain93 how do you initialize the Binance exchange instance in your code?
