### ISSUE TITLE
How to use testnet?

### ISSUE THREAD

**Issue by YusakuFujiii** [ccxt/ccxt#11953]
- OS: win11
- Programming Language version: python 3.10
- CCXT version: 1.72.84

Hi. I am trying to use ccxt to connect to testnet, but the error below occurs :

-------------
File "/usr/local/lib/python3.10/site-packages/ccxt/bybit.py", line 2883, in sign
    url = self.implode_hostname(self.urls['api'][api]) + '/' + path
TypeError: string indices must be integers
-------------

Would you mind telling me how to fix this issue please?

Thank you in advance. The code is below :

bb = ccxt.bybit({"apiKey":"", 
"secret":""
,'urls': {'api' :'https://api-testnet.bybit.com/' }} )

**Comment by carlosmiei** [comment]
Hello @YusakuFujiii,

You don't need to manually pass the testnet URL, you just need to set the sandbox mode to true. 

Example:
```Python
import ccxt  # noqa: E402

exchange = ccxt.bybit({
    "apiKey": "YOUR_API_KEY",
    "secret": "YOUR_API_SECRET",
})

exchange.set_sandbox_mode(True) # activates testnet mode

(...)
```
Feel free to reopen it if any other question arises 🙂
