### ISSUE TITLE
Bybit api fetch_order_book limit param not working

### ISSUE THREAD

**Issue by lamhochit** [ccxt/ccxt#11957]
will return full orderbook when passing limit=1

**Comment by carlosmiei** [comment]
Hello @lamhochit,
Unfortunately, the endpoint we're using from Bybit does not support limit filtering as you can see in the image.
![image](https://user-images.githubusercontent.com/43336371/154030830-f99b1d20-52dc-4a6b-abde-7878f7c297f8.png)


Thank you!
