### ISSUE TITLE
Yobit fetch_order_book bug

### ISSUE THREAD

**Issue by StnadardUsre** [ccxt/ccxt#1195]
- OS: Win 10
- Programming Language: Python 3.6
- CCXT version: last
- Exchange: Yobit
- Method: fetch_order_book

Hi, 
trying get order book from yobit:
`print(ccxt.yobit().fetch_order_book('BTC/USD', {'depth': 1}))`

but it returns full order book, disregarding depth parameter. I sniffed http request CCXT sends to yobit, it seems to be :
>  https://yobit.net/api/3/depth/btc_usd?depth=1
instead of:
> https://yobit.net/api/3/depth/btc_usd?limit=1

**Comment by kroitor** [comment]
Hi, have you tried: `print(ccxt.yobit().fetch_order_book('BTC/USD', {'limit': 1}))` instead?

**Comment by StnadardUsre** [comment]
Works like a charm, thanks )
