### ISSUE TITLE
binance rebate/taxQuery -> System abnormality

### ISSUE THREAD

**Issue by mirkoevo** [ccxt/ccxt#11950]
Hi,

do you know why I always get this 'System abnormality' error when I try to call the rebate/taxQuery endpoint?
I have tried with the additional startTime params with the same results.

I have used my tax or trading key/secret pairs.

Thank you.

- OS: macOS 11.6.3
- Programming Language version: python 3.9.10
- CCXT version: ccxt-1.72.84

tax = ccxt.binance({'apiKey': 'mykey', 'secret': 'mysecret', 'enableRateLimit': True})
tax.sapi_get_rebate_taxquery()

Traceback (most recent call last):
  File "/Users/mirko/src/crypto/mbot/.venv/lib/python3.9/site-packages/ccxt/base/exchange.py", line 658, in fetch
    response.raise_for_status()
  File "/Users/mirko/src/crypto/mbot/.venv/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.com/sapi/v1/rebate/taxQuery?timestamp=1644661291045&recvWindow=5000&signature=blabla

ccxt.base.errors.ExchangeError: binance System abnormality

**Comment by kroitor** [comment]
We had this issue as well, I would recommend reaching out to Binance on this matter. You might have to apply for their rebate program. Also check if your key works with the other endpoints. If it does work for fetching balance, but doesn't work with the taxquery-endpoint, then it might have something to do with your account permissions – i'd still recommend asking Binance directly. Hope that answers your question. Feel free to reopen this issue or just ask further questions if any.

**Comment by kroitor** [comment]
P.S. Also, I would try supplying the startTime and the endTime to it to see if it makes a difference: https://binance-docs.github.io/apidocs/spot/en/#get-spot-rebate-history-records-user_data
