### ISSUE TITLE
[bybit] error mapping for ratelimits

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#11969]
I'm calling `privatePostPrivateLinearPositionSwitchMode(...)` on all USDT futures markets and getting this after a few calls:

```
ExchangeError: bybit {"ret_code":30078,"ret_msg":"","ext_code":"","ext_info":"","result":null,"time_now":"1644853040.916000","rate_limit_status":73,"rate_limit_reset_ms":1644853040912,"rate_limit":75}
```

I think this indicates a rate limit problem

**Comment by npomfret** [comment]
sorry - that's not the cause - I don't know what the cause is but will find out

**Comment by npomfret** [comment]
I can't close the issue for some reason

**Comment by kroitor** [comment]
@npomfret it's already closed.

**Comment by Concept211** [comment]
> npomfret

Were you able to get this to work? Every time I make the same call, I get the an error from Bybit saying `bybit {"ret_code":10001,"ret_msg":"Request parameter error.","result":{}`

But I'm sending the exact same payload as in the Bybit API docs, but still errors out:
https://bybit-exchange.github.io/docs/v5/position/position-mode
