### ISSUE TITLE
Incorrect data from huobi for the create_order method

### ISSUE THREAD

**Issue by kleninmaxim** [ccxt/ccxt#11965]
My ccxt verison is: 1.72.98
OS: Linux Ubuntu 20.04
Programming language is: php8.0
Exchange is: huobi
Method is create_order gives a bad answer.

My code is:
```
<?php

require dirname(__DIR__) . "/vendor/autoload.php";

// создаем main класс
$exchange_class = "\\ccxt\\" . 'huobi';

$exchange = new $exchange_class ([
    "apiKey" => $api_public,
    "secret" => $api_secret,
    "timeout" => 10000,
    "enableRateLimit" => false
]);

// добавляем рынки для Main класса
$markets = $exchange->fetch_markets();

// созаем ордер
$order = $exchange->create_order(
    'BTC/USDT',
    'limit',
    'buy',
    0.0005,
    30000
);

print_r($order);
```
Ccxt output is:
```
Array
(
    [info] => Array
        (
            [status] => ok
            [data] => 472917275198035
        )

    [id] => 472917275198035
    [timestamp] =>
    [datetime] =>
    [lastTradeTimestamp] =>
    [status] =>
    [symbol] =>
    [type] =>
    [side] =>
    [price] =>
    [amount] =>
    [filled] =>
    [remaining] =>
    [cost] =>
    [trades] =>
    [fee] =>
    [clientOrderId] =>
    [average] =>
)
```

My question is: why this method gives only id? And other values null?

But other methods like fetch_open_orders() gives correct data.

**Comment by kroitor** [comment]
If you look into the order structure, it has the `info` substructure in it, and that contains the exchange response to `createOrder`, as is, untouched. In CCXT all response structures will have that `info` member field and you can see the exchanges' responses in it, and that is documented in the CCXT Manual. When you place an order, most of the exchanges will return just the new order id. CCXT will parse that and will return whatever data is available from the exchange response. CCXT will not fill up those values, if the underlying exchange does not specify them in the response. Hope that answers your question.
