### ISSUE TITLE
API Private Call Error : Angular 4

### ISSUE THREAD

**Issue by rhrahul** [ccxt/ccxt#1196]
Issue with Angular 4 Private API Methods of Binance and Gemini.

![ss](https://user-images.githubusercontent.com/35340981/34834181-56da29a8-f717-11e7-97f7-bbaed6ae5ffa.jpg)

Failed to load https://api.gemini.com/v1/balances: Response for preflight has invalid HTTP status code 405

- OS: Windows 10 (64)
- Programming Language: JS, Angular 4
- CCXT version: latest
- Exchange: Binance and Gemini
- Method: All Private Methods

```
this.exc = new ccxt['gemini'];
this.exc.apiKey = 'API_KEY';
this.exc.secret = 'SECRET_KEY';

(async() => {
    console.log(await (this.exc.fetchMarkets())); // Working
    console.log(await this.exc.fetchBalance()); // Not Working
})()

```

**Comment by rhrahul** [comment]
Thanks @kroitor , it did Work 👍

**Comment by kroitor** [comment]
@rhrahul if you are going to use it from the browser, I would recommend you to set up your own local CORS proxy, as written here: https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin. This would ensure that your keys are totally safe. Don't use public proxies with your actual money.

**Comment by rhrahul** [comment]
Ok, @kroitor , I'll take care of that.
Thanks
