### ISSUE TITLE
 Historical asset prices

### ISSUE THREAD

**Issue by BBX0001** [ccxt/ccxt#11973]
Hey guys!
can you help me?

I would like to extract BTC/USDT data from 01/01/2021 to daily 12/31/2021 in the chart by Exchange Binance.
How to put the script by CCXT?

**Comment by samgermain** [comment]
@BBX0001 What language are you using?

**Comment by BBX0001** [comment]
I'm using Python.
I couldn't find the script as per the description.
For example, I need to extract BTC/USDT prices between 01/01/2021 to 01/01/2022 on 1-day timeframe by Exchange Binance.

Which script can I use to fetch this information?

**Comment by BBX0001** [comment]
> @BBX0001 Qual idioma você está usando?


I'm using Python.
I couldn't find the script as per the description.
For example, I need to extract BTC/USDT prices between 01/01/2021 to 01/01/2022 on 1-day timeframe by Exchange Binance.

Which script can I use to fetch this information?

**Comment by samgermain** [comment]
```
from datetime import datetime
import ccxt

binance = ccxt.binance()

symbol = 'BTC/USDT'
ticker = '1d'
date1 = int(datetime(2021, 1, 1).timestamp()) * 1000
limit = 365 # days per year
print(date1)

binance.loadMarkets()
res = binance.fetch_ohlcv(symbol, ticker, date1, limit)
print(res)
```
