### ISSUE TITLE
Please add support for hotbit

### ISSUE THREAD

**Issue by OxfordGrid** [ccxt/ccxt#11988]
Could you add Hotbit to CCXT, please? The exchange has a lot of smaller coins to trade.

Exchange home: [hotbit.io](https://www.hotbit.io/)
Api implementation: https://github.com/hotbitex/hotbit.io-api-docs/blob/master/rest_api_en.md
Endpoint: https://api.hotbit.io/api/v1

Thank you.

**Comment by ryny24** [comment]
Also request for hotbit.io

**Comment by mapapuche** [comment]
Hello, any update about this ?

**Comment by ttodua** [comment]
Hotbit exchange is being closed https://hotbit.zendesk.com/hc/en-us/articles/14750194236823-It-s-time-to-take-a-bow
