### ISSUE TITLE
Known Exchange Data Inconsistencies

### ISSUE THREAD

**Issue by cdcv** [ccxt/ccxt#11982]
What are the known types of inconsistencies or errors in exchange data?
Is there a list somewhere, in ccxt or elsewhere, of know 'inconsistencies' in exchange data?  I'm sure there are quite a few.  Would save everyone a lot of time if they can read through the known ones instead of everyone having to discover them for themselves.  I'm sure that which ones you run into depend on what you are doing with the data.  I also imagine that if you put together a list of the top 5 or top 10, it might be a pretty good start, and others could add to it as they are discovered.  You already mention a few of them in the docs that relate to how to make calls for exchange data.

Missing OHLCV/candle data
I just found, as expected, that there are gaps in the OHLCV data pulled from the exchanges.  For example, in some cases there are hours of missing data between the 1m data points from heavily traded pairs where trades must certainly have been made. Re-downloading the data again produces the same result. Not sure what the origin of these is, eg whether trading was actually unavailable for that time or the data are just missing.

Thank you.

**Comment by ttodua** [comment]
late reply here, but i udnerstand the frustration, howeer, it's hard to collect a definitive description of exchanges' api bugs (as itself their bugs are sometimes undeterministic for us to precisely define).
anyway, we are adding a `.Features` metadata soon, which would give users more insights of what does exchange support or what params could be supproted.

**Comment by ttodua** [comment]
closing this for now, as we collect some of them in `skip-tests.json` and some of them would be exposed in `.features` ( https://github.com/ccxt/ccxt/pull/23629 ), other than that, the exchange specific documents can be read inside exchange method's code & comments there.
