### ISSUE TITLE
Helper: merge/sum balance objects

### ISSUE THREAD

**Issue by phips28** [ccxt/ccxt#11998]
As discussed in Discord, I leave our function to merge/sum balance objects here:

```
module.exports.mergeIntoBalance = (balanceObjectToMerge, intoBalance) => {
	if (!balanceObjectToMerge) {
		return intoBalance;
	}
	// copy object
	const tempIntoBalance = { ...intoBalance };

	// merge main COIN objects
	Object.keys(balanceObjectToMerge).forEach((balanceKey) => {
		const coinObject = balanceObjectToMerge[balanceKey];
		// console.log('mergeIntoBalance -> balanceKey', balanceKey, coinObject);

		// check if its a coin object: FIL { free: 0, used: 0, total: 0 }
		if (
			typeof coinObject === 'undefined' ||
			!Object.keys(coinObject).includes('free') ||
			!Object.keys(coinObject).includes('used') ||
			!Object.keys(coinObject).includes('total')
		) {
			// console.warn('ignoring key:', balanceKey);
			return;
		}
		// check if we have it in the main (spot) balance object
		if (!tempIntoBalance[balanceKey]) {
			// not in balance, just add it onto it
			tempIntoBalance[balanceKey] = coinObject;
		} else {
			// already in balance, merge it
			tempIntoBalance[balanceKey].free = tempIntoBalance[balanceKey].free + coinObject.free;
			tempIntoBalance[balanceKey].used = tempIntoBalance[balanceKey].used + coinObject.used;
			tempIntoBalance[balanceKey].total = tempIntoBalance[balanceKey].total + coinObject.total;
			// console.log('after merge', balanceKey, tempIntoBalance[balanceKey]);
		}
	});

	// merge free, used, total
	['free', 'used', 'total'].forEach((key) => {
		if (!balanceObjectToMerge[key]) {
			return;
		}
		// console.log('merge for key:', key);
		Object.keys(balanceObjectToMerge[key]).forEach((balanceKey) => {
			const coinValue = balanceObjectToMerge[key][balanceKey];
			// console.log('mergeIntoBalance -> free, balanceKey', balanceKey, coinValue);

			// check if we have it in the main (spot) balance object
			if (tempIntoBalance[key][balanceKey] === undefined) {
				// not in balance, just add it onto it
				tempIntoBalance[key][balanceKey] = coinValue;
			} else {
				// already in balance, merge it
				tempIntoBalance[key][balanceKey] = tempIntoBalance[key][balanceKey] + coinValue;
				// console.log('after merge', balanceKey, tempIntoBalance[key][balanceKey]);
			}
		});
	});

	return tempIntoBalance;
};
```

**Comment by ttodua** [comment]
can you please refer the discord link too of the discussion?

**Comment by ttodua** [comment]
@ccxt/developers Personally I, think that if this is going to be merged (and could be, is useful thing), it should be done the following way:

1) add a method `mergeIntoBalance (or whatever)` in base to do this 'deep-level' merging of balances

2) it will be also useful if we create another unified method named `fetchBalanceAll` which will do `promise.all` approach for fetching all balance types for the exchange, and return it. I think that will be another useful function to show 'whole account overview' balance, like we see in Exchange UI  'account overview' where all balances are shown in one place.

**Comment by phips28** [comment]
@ttodua be careful with the 2. `fetchBalanceAll` - `Promise.all` would fail on the first reject. 
There are exchanges where you have to activate margin or futures account first, to be able to fetch something. This results in errors, as you see in my example implementation, where I catch the `AccountNotEnabled` error (could also be an Auth error).

**Comment by ttodua** [comment]
> @ttodua be careful with the 2. `fetchBalanceAll` - `Promise.all` would fail on the first reject. There are exchanges where you have to activate margin or futures account first, to be able to fetch something. This results in errors, as you see in my example implementation, where I catch the `AccountNotEnabled` error (could also be an Auth error).

I think, that should be handled with try/catch from userland code. ccxt should throw error if it fails.

**Comment by phips28** [comment]
@ttodua yes, but then the `fetchBalanceAll` would never work in such cases, and the user needs to build it themselves like we do, merging multiple balance responses.

**Comment by ttodua** [comment]
I understand what you say, I mean, when the error is 'account_not_found' or something like which doesn't play any role in summing the balance, then the error can be muted inside ccxt's implementation. but if the error is other (like exchange error, network error, rate-limits or other issue, that might cause failure to correctly sum up the balance) in such cases the error should be thrown.

**Comment by ttodua** [comment]
late update on this, but as this was never merged (and neither seems to happen at this moment), i'll close this for now.
