### ISSUE TITLE
Order status = NONE on fully filled order after create_limit_buy_order with cryptocom

### ISSUE THREAD

**Issue by camstuart** [ccxt/ccxt#12007]
Hello,

I had an unexpected order status of `none` returned from creating an order on crypto.com which I believe was fully filled order.

- OS: Mac OS Monterey
- Programming Language version: Python 3.10
- CCXT version: 1.72.79

```python
ex_order: dict = self.exchanger.create_limit_buy_order('CRO/USDT', qty, price)
order_status = str(ex_order['status']).upper()
print(order_status) # NONE
```
In this situation I am not sure what this status actually means (not filled, partially filled, fully filled)?
Are you able to shed any light on this?

Thanks

**Comment by kroitor** [comment]
A successful call to create an order does not mean that the order is placed. It just means your request was accepted. Upon returning a response to you from create order call, the status of the order is unknown (the exchange does not report it). You can see the original response from the exchange in the `order['info']` field. You can query the order status later with `fetchOrder`, `fetchOrders`, `fetchClosedOrders` and with the other methods. 

This is actually common to many exchanges and it is covered in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#placing-orders

I would highly recommend reading the entire Manual from top to bottom, that will save your time:

- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/
- https://docs.ccxt/com
- https://github.com/ccxt/ccxt/tree/master/examples

Hope that answers your question.
