### ISSUE TITLE
Best practice for both watching orderbook and watching fills

### ISSUE THREAD

**Issue by dptashny1** [ccxt/ccxt#12003]
The ccxt pro manual shows an example of using asyncio and a forever while loop to watch the order book and print any changes in it. What's the best practice if I want to both watch the order book and also watch my fills. Something like this:
while True
   await exchange.watch_order_book('BTC/USD')
#react here to changes in order book
await exchange.watchClosedOrders ??? 
  #react here once I get a new fill

Thanks.

**Comment by kroitor** [comment]
Check this example: https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/many-exchanges-many-different-streams.py

Also check other examples here:

- https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/

Let us know if it does not answer your question.

**Comment by dptashny1** [comment]
With respect to this example, the most current version of Python gives this warning:
**DeprecationWarning: There is no current event loop**

Will you update your code to get rid of this warning?
Thanks

**Comment by dptashny1** [comment]
In the prior version, I was able to modify your example code to call binance with my keys like this:
    exchange = getattr(ccxtpro, exchange_id)({
        'enableRateLimit': True,
        'asyncio_loop': asyncio_loop,
        'newUpdates': True,
        'secret': config.BINANCE_SECRET,
        'apiKey': config.BINANCE_API_KEY
    })
However, when I change your line:
from: exchange = getattr(ccxtpro, exchange_id)() 
to:     exchange = getattr(ccxtpro, exchange_id)({
        'secret': config.BINANCE_SECRET,
        'apiKey': config.BINANCE_API_KEY
    })
I now get this error message:

binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001879F2617E0>
Traceback (most recent call last):
  File "C:\Users\david\anaconda3\envs\CryptoTrading\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\david\anaconda3\envs\CryptoTrading\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\david\anaconda3\envs\CryptoTrading\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\david\anaconda3\envs\CryptoTrading\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
