### ISSUE TITLE
Fetch Binance User ID?

### ISSUE THREAD

**Issue by Ahmed089** [ccxt/ccxt#12000]
Can anyone help me to Fetch Binance User ID from my API Key?
I tried to fetch it from exchange.uid but nothing is getting in return as response.

**Comment by kroitor** [comment]
The `exchange.uid` is an authentication property, not a method, and it's not used to determine the user id.
Unfortunately, there is no way of fetching the user id via the Binance API as far as I know.

**Comment by Ahmed089** [comment]
Do you think is there any way to retrieve User ID cause I need to make authentication on my site with User ID of Binance Account.
