### ISSUE TITLE
How to subscribe on trades (watch_ trades) on all pairs on an exchange if server have multiple public ip addresses? 

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#12004]
How to subscribe on trades (watch_ trades) on all pairs on an exchange if server have multiple public ip addresses? How to avoid connection restrictions ?

**Comment by kroitor** [comment]
Let us know if the following does not help: https://github.com/ccxt/ccxt/issues/3770#issuecomment-962034275
Feel free to reopen this issue or just ask further questions here if any.
