### ISSUE TITLE
I want to get an information about realtime PNL/ROE in binance

### ISSUE THREAD

**Issue by smartbh** [ccxt/ccxt#12015]
![image](https://user-images.githubusercontent.com/43138813/154697009-feba7511-93f8-4cbc-a818-aef438ff39a2.png)

like this image

I want to get my position's realtime PNL/ROE data

I tried find solution on internet even includ git.

I thought that I can find some function in ccxt api

but I couldn't find it.

where can I find that function which the information of PNL/ROE

or if there not

Am I have to def a fucntion for it?

then how can I?

- OS: Windows 10
- Programming Language version: python 3.7.0
- CCXT version:  1.72.74

**Comment by kroitor** [comment]
Use the `fetch_positions` method to obtain that info:

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L4608

I'd highly recommend reading the entire Manual from top to bottom: 

- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/
- https://docs.ccxt.com

Also check the examples here:

- https://github.com/ccxt/ccxt/tree/master/examples
- https://github.com/ccxt/ccxt/tree/master/examples#see-also

Hope that answers your questions, let us know if not. Feel free to reopen this issue or just ask further questions if any.
