### ISSUE TITLE
 Converter timestamp for data

### ISSUE THREAD

**Issue by BBX0001** [ccxt/ccxt#12016]
Hello guys, how do I convert the timestamp to date and time, my code is bringing the date of 1970. HOW do I correctly leave the date of the historical data?

from datetime import datetime
import ccxt

binance = ccxt.binance()

symbol = 'BTC/USDT'
ticker = '5m'
date1 = int(datetime(2021, 1, 1).timestamp()) * 1000
limit = 1000
print(date1)

binance.loadMarkets()
res = binance.fetch_ohlcv(symbol, ticker, date1, limit)
print(res)

import pandas as pd

res_df = pd.DataFrame(res, columns = ['date', 'open', 'high', 'low', 'close', 'volume'])

res_df.head()

	date	open	high	low	close	volume
0	1609459200000	28923.63	29017.50	28913.12	28975.65	182.889878
1	1609459500000	28975.65	28979.53	28846.28	28858.94	214.568104
2	1609459800000	28858.94	28883.20	28690.17	28752.80	442.619587
3	1609460100000	28752.80	28852.48	28720.91	28820.72	174.839779
4	1609460400000	28822.17	28846.46	28744.09	28846.46	161.316784

Script Python

**Comment by kroitor** [comment]
See line 24 in this example: 

- https://github.com/ccxt/ccxt/blob/master/examples/py/binance-ema.py#L24
- https://github.com/ccxt/ccxt/blob/master/examples/py/binance-ema.py

Also:

- https://www.google.com/search?q=pandas+milliseconds+to+datetime

**Comment by kroitor** [comment]
```Python
from datetime import datetime
import ccxt

binance = ccxt.binance()

symbol = 'BTC/USDT'
ticker = '5m'
since = binance.parse8601('2021-01-01T00:00:00Z')
limit = 1000

binance.loadMarkets()
res = binance.fetch_ohlcv(symbol, ticker, since, limit)
print(res)

import pandas as pd

res_df = pd.DataFrame(res, columns = ['datetime', 'open', 'high', 'low', 'close', 'volume'])
res_df['datetime'] = pd.to_datetime(res_df['datetime'], unit='ms')
res_df.head()
```
