### ISSUE TITLE
ccxt pro poetry installation 

### ISSUE THREAD

**Issue by muharremb** [ccxt/ccxt#12014]
hi there, 

I recently bought CCXT Pro. Is there anyway that I can install ccxt pro using poetry, dependence manager? Appreciated. Thank you.

**Comment by kroitor** [comment]
Hi! I'm not sure about poetry, but you can install ccxtpro with `pip` as you would do with other packages:

- https://github.com/ccxt/ccxt/wiki/ccxt.pro.install

Hope that answers your question, let us know if not.

**Comment by kroitor** [comment]
I think you can add a private ccxtpro repository to your poetry configs:

- https://python-poetry.org/docs/master/repositories/#install-dependencies-from-a-private-repository
- https://python-poetry.org/docs/master/repositories/
