### ISSUE TITLE
Validate trades data from different exchanges

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#12021]
How to validate trades data on data inconsistencies for case when id is not incremental integer? For example 'id': '62108d742e113d38dbd77080'

```
[{'info': {'symbol': 'ADA-USDT', 'side': 'buy', 'type': 'match', 'makerOrderId': '62108d597ee3b40001bdcd9b', 'sequence': '1620813227108', 'size': '271.5987', 'price': '1.009207', 'takerOrderId': '62108d74efab1800014e8490', 'time': '1645251956581730729', 'tradeId': '62108d742e113d38dbd77080'}, 'id': '62108d742e113d38dbd77080', 'order': None, 'timestamp': 1645251956581, 'datetime': '2022-02-19T06:25:56.581Z', 'symbol': 'ADA/USDT', 'type': None, 'takerOrMaker': None, 'side': 'buy', 'price': 1.009207, 'amount': 271.5987, 'cost': 274.0993092309, 'fee': None, 'fees': []}]
[{'info': {'symbol': 'ADA-USDT', 'side': 'buy', 'type': 'match', 'makerOrderId': '62108d597ee3b40001bdcd9b', 'sequence': '1620813227123', 'size': '271.5987', 'price': '1.009207', 'takerOrderId': '62108d7455756b0001502bbd', 'time': '1645251956614109596', 'tradeId': '62108d742e113d38dbd77081'}, 'id': '62108d742e113d38dbd77081', 'order': None, 'timestamp': 1645251956614, 'datetime': '2022-02-19T06:25:56.614Z', 'symbol': 'ADA/USDT', 'type': None, 'takerOrMaker': None, 'side': 'buy', 'price': 1.009207, 'amount': 271.5987, 'cost': 274.0993092309, 'fee': None, 'fees': []}, {'info': {'symbol': 'ADA-USDT', 'side': 'buy', 'type': 'match', 'makerOrderId': '62108d597ee3b40001bdcd9b', 'sequence': '1620813227129', 'size': '271.5987', 'price': '1.009207', 'takerOrderId': '62108d74f235a40001ba9c0a', 'time': '1645251956635220176', 'tradeId': '62108d742e113d38dbd77083'}, 'id': '62108d742e113d38dbd77083', 'order': None, 'timestamp': 1645251956635, 'datetime': '2022-02-19T06:25:56.635Z', 'symbol': 'ADA/USDT', 'type': None, 'takerOrMaker': None, 'side': 'buy', 'price': 1.009207, 'amount': 271.5987, 'cost': 274.0993092309, 'fee': None, 'fees': []}]
[{'info': {'symbol': 'ADA-USDT', 'side': 'buy', 'type': 'match', 'makerOrderId': '62108d597ee3b40001bdcd9b', 'sequence': '1620813227132', 'size': '271.5987', 'price': '1.009207', 'takerOrderId': '62108d74b061be0001c97443', 'time': '1645251956667442500', 'tradeId': '62108d742e113d38dbd77084'}, 'id': '62108d742e113d38dbd77084', 'order': None, 'timestamp': 1645251956667, 'datetime': '2022-02-19T06:25:56.667Z', 'symbol': 'ADA/USDT', 'type': None, 'takerOrMaker': None, 'side': 'buy', 'price': 1.009207, 'amount': 271.5987, 'cost': 274.0993092309, 'fee': None, 'fees': []}]
[{'info': {'symbol': 'ADA-USDT', 'side': 'buy', 'type': 'match', 'makerOrderId': '62108d597ee3b40001bdcd9b', 'sequence': '1620813227139', 'size': '271.5987', 'price': '1.009207', 'takerOrderId': '62108d749aecca0001a0e0cb', 'time': '1645251956700083632', 'tradeId': '62108d742e113d38dbd77085'}, 'id': '62108d742e113d38dbd77085', 'order': None, 'timestamp': 1645251956700, 'datetime': '2022-02-19T06:25:56.700Z', 'symbol': 'ADA/USDT', 'type': None, 'takerOrMaker': None, 'side': 'buy', 'price': 1.009207, 'amount': 271.5987, 'cost': 274.0993092309, 'fee': None, 'fees': []}]
[{'info': {'symbol': 'ADA-USDT', 'side': 'buy', 'type': 'match', 'makerOrderId': '62108d597ee3b40001bdcd9b', 'sequence': '1620813227148', 'size': '271.5987', 'price': '1.009207', 'takerOrderId': '62108d74152bd400010c949d', 'time': '1645251956731804143', 'tradeId': '62108d742e113d38dbd77086'}, 'id': '62108d742e113d38dbd77086', 'order': None, 'timestamp': 1645251956731, 'datetime': '2022-02-19T06:25:56.731Z', 'symbol': 'ADA/USDT', 'type': None, 'takerOrMaker': None, 'side': 'buy', 'price': 1.009207, 'amount': 271.5987, 'cost': 274.0993092309, 'fee': None, 'fees': []}, {'info': {'symbol': 'ADA-USDT', 'side': 'buy', 'type': 'match', 'makerOrderId': '62108d597ee3b40001bdcd9b', 'sequence': '1620813227153', 'size': '271.5987', 'price': '1.009207', 'takerOrderId': '62108d747ee3b40001be2440', 'time': '1645251956752651661', 'tradeId': '62108d742e113d38dbd77089'}, 'id': '62108d742e113d38dbd77089', 'order': None, 'timestamp': 1645251956752, 'datetime': '2022-02-19T06:25:56.752Z', 'symbol': 'ADA/USDT', 'type': None, 'takerOrMaker': None, 'side': 'buy', 'price': 1.009207, 'amount': 271.5987, 'cost': 274.0993092309, 'fee': None, 'fees': []}]
[{'info': {'symbol': 'ADA-USDT', 'side': 'buy', 'type': 'match', 'makerOrderId': '62108d597ee3b40001bdcd9b', 'sequence': '1620813227158', 'size': '271.5987', 'price': '1.009207', 'takerOrderId': '62108d744377fc0001a04d0e', 'time': '1645251956785136452', 'tradeId': '62108d742e113d38dbd7708a'}, 'id': '62108d742e113d38dbd7708a', 'order': None, 'timestamp': 1645251956785, 'datetime': '2022-02-19T06:25:56.785Z', 'symbol': 'ADA/USDT', 'type': None, 'takerOrMaker': None, 'side': 'buy', 'price': 1.009207, 'amount': 271.5987, 'cost': 274.0993092309, 'fee': None, 'fees': []}]
[{'info': {'symbol': 'ADA-USDT', 'side': 'buy', 'type': 'match', 'makerOrderId': '62108d723526430001a17aa0', 'sequence': '1620813227164', 'size': '271.5987', 'price': '1.009207', 'takerOrderId': '62108d74f938450001d556d2', 'time': '1645251956806578195', 'tradeId': '62108d742e113d38dbd7708c'}, 'id': '62108d742e113d38dbd7708c', 'order': None, 'timestamp': 1645251956806, 'datetime': '2022-02-19T06:25:56.806Z', 'symbol': 'ADA/USDT', 'type': None, 'takerOrMaker': None, 'side': 'buy', 'price': 1.009207, 'amount': 271.5987, 'cost': 274.0993092309, 'fee': None, 'fees': []}]

```

**Comment by kroitor** [comment]
I'd suggest reaching out to the exchange for the CSVs and verifying against the CSV. They might not provide the entire history though. I'm not sure if there is a way of validating the trades over the API, probably not.

**Comment by kroitor** [comment]
@YuriyTigiev one possible way of checking the data is to build OHLCVs from those trades and then match those OHLCVs against the exchange's OHLCVs: 

- https://github.com/ccxt/ccxt/blob/master/js/base/functions/misc.js#L43
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L1793
- https://github.com/ccxt/ccxt/blob/master/php/Exchange.php#L556

**Comment by YuriyTigiev** [comment]
I though to use trades data for building ohlcv. Now I'm not sure that trading data is good source for that. That means I should use ohlcv  data from each exchange. I'm not confident in Web Socket, because you always have a chance to lose some information and you can't validate it (online), because each Exchange has restrictions on number of API requests. Web Socket and API ohlcv data could delivery with delay from exchange. It's also is a bad news.

I found that only binance upload daily history information in csv format on a web public resources.

I'm trying to understand how other customers that use ccxt library for fetching historical data handles the problem with validating it.

**Comment by kroitor** [comment]
>  Now I'm not sure that trading data is good source for that. That means I should use ohlcv data from each exchange.

1. watch trades via the WS API and build OHLCVs on your end
2. fetch trades history continuously from the exchange via the REST API, use that to fill gaps in data on WS disconnects
3. fetch OHLCV history from the exchange (or track it continuously)

> I'm trying to understand how other customers that use ccxt library for fetching historical data handles the problem with validating it.

At this time we're not running a speculative strategy based on the past price, but we still collect all possible data that is required for our scripts, including personal and public data and we match that against whatever info we can obtain from the API and from the website in CSV.

**Comment by YuriyTigiev** [comment]
1) This was my plan
2) It also was my plan, but I need fetch data for all pairs, because I'm developing a crypto screener. I'm planning to provide user to make to filter data by criteria in online(near online). The each exchange has it's own restrictions on number of requests. It's no problem if you are working with a few pairs. But if you want collect data for all active pairs maybe you should use a pool public addresses to avoid problem with restrictions.  I don't know what a minimal number of addresses should I have for that.
3) Additional loads on exchange API and additional restrictions that I should avoid.

**Comment by kroitor** [comment]
> I need fetch data for all pairs

Then you will need a cloud of VPCs on your backend. You can't really watch all pairs from all exchanges with a single machine at once.

I've pushed some examples, jfyi: 

- https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/js/calculate-ohlcvs-from-trades.js
- https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/js/calculate-ohlcvs-from-trades-warmup.js

**Comment by YuriyTigiev** [comment]
Question - what is better from performance point of view - python or javascript for the described task?

**Comment by kroitor** [comment]
> Question - what is better from performance point of view - python or javascript for the described task?

They're comparable, it depends more on the architecture of the code, not so much the programming language.
