### ISSUE TITLE
Bybit fetch fundingRate fails to return correct funding datetime for contracts that pays hourly

### ISSUE THREAD

**Issue by lamhochit** [ccxt/ccxt#12024]
bybit fetch_funding next fundingRate is not correct, SLP is now paying funding hourly but it is quoting the next 8 hours (it fails for all contracts that pays funding every hour)

Issue raised in Discord group, raising here in case its missed

response:
{'SLPUSDT': {'info': {'symbol': 'SLPUSDT',
   'funding_rate': '0.0000125',
   'funding_rate_timestamp': '2022-02-18T15:00:00.000Z'},
  'symbol': 'SLPUSDT',
  'markPrice': None,
  'indexPrice': None,
  'interestRate': None,
  'estimatedSettlePrice': None,
  'timestamp': 1645197719990,
  'datetime': '2022-02-18T15:21:59.990Z',
  'fundingRate': 1.25e-05,
  'fundingTimestamp': 1645196400000,
  'fundingDatetime': '2022-02-18T15:00:00.000Z',
  'nextFundingRate': None,
  'nextFundingTimestamp': 1645225200000,
  'nextFundingDatetime': '2022-02-18T23:00:00.000Z',
  'previousFundingRate': None,
  'previousFundingTimestamp': None,
  'previousFundingDatetime': None}}

**Comment by lamhochit** [comment]
any update pls?

**Comment by samgermain** [comment]
Thanks for pointing this out, I removed the nextFundingTimestamp from Bybits response because it's not returned from the API

https://github.com/ccxt/ccxt/pull/12060

**Comment by lamhochit** [comment]
So how can I check whether the future pays hourly or every 8 hours using API?
