### ISSUE TITLE
watchMyTrades in binance seems to return nothing even after I manually execute a trade

### ISSUE THREAD

**Issue by dptashny1** [ccxt/ccxt#12035]
OS: Windows 11
Programming Language version: Python 3.9
CCXTPRO version: 0.9.45

Please note that my code works if I use ccxt and fetchMyTrades with the same parameters as below:
Also, I truncated the output because it seems too big to post here:

```

import ccxtpro
import asyncio
import logging
import datetime

order_params = {'type': 'margin', 'isIsolated': 'TRUE'}
day = '2022-02-20 06:00:00'
since = round(datetime.datetime.strptime(str(day), '%Y-%m-%d %H:%M:%S').timestamp()*1000)

async def getTickSize(exchange):
    markets = await exchange.loadMarkets()
    result = pow(10, -markets['ETH/BTC']['precision']['price'])
    return result


async def main(loop):
    order_placed = False
    #logging.basicConfig(filename='log.file', format='%(asctime)s %(message)s', level=logging.INFO)


    exchange = ccxtpro.binance({'enableRateLimit': True, 'asyncio_loop': loop, 'newUpdates': True,
                                'secret': '',
                                'apiKey': ''})

    exchange.verbose = True
    tickSize = await getTickSize(exchange)
    #logging.info(f"Tick Size is: " + str(tickSize))
    while True:
        #orderbook = await exchange.watch_order_book('ETH/BTC')
        trades = await exchange.watch_my_trades('ETH/BTC',  since=since, limit=5000, params = order_params)
        print(type(trades))
    await exchange.close()

loop = asyncio.new_event_loop()
loop.run_until_complete(main(loop))

```

```":"MIN_NOTIONAL","minNotional":"10.00000000","applyToMarket":true,"avgPriceMins":5},{"filterType":"ICEBERG_PARTS","limit":10},{"filterType":"MARKET_LOT_SIZE","minQty":"0.00000000","maxQty":"68.97711577","stepSize":"0.00000000"},{"filterType":"MAX_NUM_ORDERS","maxNumOrders":200}

fetch Request: binance POST https://api.binance.com/sapi/v1/userDataStream RequestHeaders: {'X-MBX-APIKEY': '#API KEY ERASED', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.26.0', 'Accept-Encoding': 'gzip, deflate'} RequestBody: 
fetch Response: binance POST https://api.binance.com/sapi/v1/userDataStream 200 ResponseHeaders: {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '76', 'Connection': 'keep-alive', 'Date': 'Sun, 20 Feb 2022 12:58:53 GMT', 'Server': 'nginx', 'X-S

2022-02-20T12:58:53.354Z connecting to wss://stream.binance.com:9443/ws/PENK9WaPAwAkY8vBL7kztpcOGhacH11gC3tb7A6zWnBIYLEtcKwMapVv8mEU with timeout 10000 ms
2022-02-20T12:58:54.329Z connected
2022-02-20T12:58:54.329Z ping loop
2022-02-20T12:58:54.553Z pong WSMessage(type=<WSMsgType.PONG: 10>, data=bytearray(b''), extra='')
2022-02-20T12:59:24.572Z pong WSMessage(type=<WSMsgType.PONG: 10>, data=bytearray(b''), extra='')

**Comment by dptashny1** [comment]
I just tested this code in the Cash account (as opposed to Isolated Margin) and it works there. So it's something about the iso margin which is messing up the watch_my_trades. Thanks.

**Comment by kroitor** [comment]
@dptashny1 you should remove those params from the `watch_my_trades` call:

```Python
        # order_params = {'type': 'margin', 'isIsolated': 'TRUE'} # no need for this
        # --------------------------------------------------------------------------------↓ here
        trades = await exchange.watch_my_trades('ETH/BTC',  since=since, limit=5000) #, params = order_params)
```

When you're margin trading on spot-markets, you're actually placing trades on those spot markets, so there's no need to change the type in params here. Let us know if that does not help resolve the issue.

**Comment by dptashny1** [comment]
I created 2 programs to demonstrate that watch_my_trades doesn't work properly with iso margin orders:
### Program 1 - Cash Account:

import ccxtpro
from asyncio import gather, get_event_loop
import configETH as config
import pandas as pd
import datetime

start_time = datetime.datetime.now()
since = round(start_time.timestamp() * 1000)
exchange = ccxtpro.binance()

async def symbol_loop(exchange, method, symbol):
    order_sent = False
    called_fetch_my_trades = False

    print('Starting', exchange.id, method, symbol)

    while True:
        difference = (datetime.datetime.now() - start_time)
        seconds_since_start = difference.total_seconds()
        try:
            response = await getattr(exchange, method)(symbol)
            if method == 'watchOrderBook':
                if seconds_since_start > 5 and not order_sent:
                    print("Creating Market cash order")
                    await exchange.createOrder('ETH/BTC', 'market', 'sell', 0.0015)
                    order_sent = True

                if seconds_since_start > 10 and not called_fetch_my_trades:
                    print("Calling fetch_my_trades:")
                    my_trades = await exchange.fetch_my_trades(symbol='ETH/BTC', since=since)
                    df = pd.DataFrame(my_trades)
                    print(df)
                    called_fetch_my_trades = True

            elif method == 'watchMyTrades':
                df = pd.DataFrame(response)
                print("Printing result of watchMyTrades")
                print(df)

        except Exception as e:
            print(str(e))
            # raise e  # uncomment to break all loops in case of an error in any one of them
            break  # you can break just this one loop if it fails


async def method_loop(exchange, method, symbols):
    print('Starting', exchange.id, method, symbols)
    loops = [symbol_loop(exchange, method, symbol) for symbol in symbols]
    await gather(*loops)


async def exchange_loop(asyncio_loop, exchange_id, methods):
    global exchange

    print('Starting', exchange_id, methods)

    exchange = getattr(ccxtpro, exchange_id)({
        'enableRateLimit': True,
        'asyncio_loop': asyncio_loop,
        'newUpdates': True,
        'secret': config.BINANCE_SECRET,
        'apiKey': config.BINANCE_API_KEY
    })
    loops = [method_loop(exchange, method, symbols) for method, symbols in methods.items()]

    await gather(*loops)
    await exchange.close()


async def main(asyncio_loop):
    exchanges = {
        'binance': {
            'watchOrderBook': ['ETH/BTC'],
            'watchMyTrades': [ 'ETH/BTC' ],
        }
    }

    loops = [exchange_loop(asyncio_loop, exchange_id, methods) for exchange_id, methods in exchanges.items()]
    await gather(*loops)


if __name__ == '__main__':
    asyncio_loop = get_event_loop()
    asyncio_loop.run_until_complete(main(asyncio_loop))
### Output 1:
Starting binance {'watchOrderBook': ['ETH/BTC'], 'watchMyTrades': ['ETH/BTC']}
Starting binance watchOrderBook ['ETH/BTC']
Starting binance watchMyTrades ['ETH/BTC']
Starting binance watchOrderBook ETH/BTC
Starting binance watchMyTrades ETH/BTC
Creating Market cash order
Printing result of watchMyTrades
                                                info  ...                                 fee
0  {'e': 'executionReport', 'E': 1645582189640, '...  ...  {'cost': 1e-07, 'currency': 'BTC'}

[1 rows x 13 columns]
Calling fetch_my_trades:
                                                info  ...                                  fees
0  {'symbol': 'ETHBTC', 'id': '326021047', 'order...  ...  [{'currency': 'BTC', 'cost': 1e-07}]

[1 rows x 14 columns]

### Program 2: Margin Account:

import ccxtpro
from asyncio import gather, get_event_loop
import configETH as config
import pandas as pd
import datetime

order_params = {'type': 'margin', 'isIsolated': 'TRUE'}

start_time = datetime.datetime.now()
since = round(start_time.timestamp() * 1000)
exchange = ccxtpro.binance()

async def symbol_loop(exchange, method, symbol):
    order_sent = False
    called_fetch_my_trades = False

    print('Starting', exchange.id, method, symbol)

    while True:
        difference = (datetime.datetime.now() - start_time)
        seconds_since_start = difference.total_seconds()
        try:
            response = await getattr(exchange, method)(symbol)
            if method == 'watchOrderBook':
                if seconds_since_start > 5 and not order_sent:
                    print("Creating Market cash order")
                    await exchange.createOrder('ETH/BTC', 'market', 'sell', 0.0015, params = order_params)
                    order_sent = True

                if seconds_since_start > 10 and not called_fetch_my_trades:
                    print("Calling fetch_my_trades:")
                    my_trades = await exchange.fetch_my_trades(symbol='ETH/BTC', since=since, params= order_params)
                    df = pd.DataFrame(my_trades)
                    print(df)
                    called_fetch_my_trades = True

            elif method == 'watchMyTrades':
                df = pd.DataFrame(response)
                print("Printing result of watchMyTrades")
                print(df)

        except Exception as e:
            print(str(e))
            # raise e  # uncomment to break all loops in case of an error in any one of them
            break  # you can break just this one loop if it fails


async def method_loop(exchange, method, symbols):
    print('Starting', exchange.id, method, symbols)
    loops = [symbol_loop(exchange, method, symbol) for symbol in symbols]
    await gather(*loops)


async def exchange_loop(asyncio_loop, exchange_id, methods):
    global exchange

    print('Starting', exchange_id, methods)

    exchange = getattr(ccxtpro, exchange_id)({
        'enableRateLimit': True,
        'asyncio_loop': asyncio_loop,
        'newUpdates': True,
        'secret': config.BINANCE_SECRET,
        'apiKey': config.BINANCE_API_KEY
    })
    loops = [method_loop(exchange, method, symbols) for method, symbols in methods.items()]

    await gather(*loops)
    await exchange.close()


async def main(asyncio_loop):
    exchanges = {
        'binance': {
            'watchOrderBook': ['ETH/BTC'],
            'watchMyTrades': [ 'ETH/BTC' ],
        }
    }

    loops = [exchange_loop(asyncio_loop, exchange_id, methods) for exchange_id, methods in exchanges.items()]
    await gather(*loops)


if __name__ == '__main__':
    asyncio_loop = get_event_loop()
    asyncio_loop.run_until_complete(main(asyncio_loop))

### Output 2:
Starting binance {'watchOrderBook': ['ETH/BTC'], 'watchMyTrades': ['ETH/BTC']}
Starting binance watchOrderBook ['ETH/BTC']
Starting binance watchMyTrades ['ETH/BTC']
Starting binance watchOrderBook ETH/BTC
Starting binance watchMyTrades ETH/BTC
Creating Market cash order
Calling fetch_my_trades:
                                                info  ...                                  fees
0  {'symbol': 'ETHBTC', 'id': '326022663', 'order...  ...  [{'currency': 'BTC', 'cost': 1e-07}]

[1 rows x 14 columns]

**Comment by ttodua** [comment]
old topic, but revised now and re-tested myself, and it works at this stage, so closing this. if any issue, let us know
