### ISSUE TITLE
How do I run the program?

### ISSUE THREAD

**Issue by mcintirejohn4** [ccxt/ccxt#1203]
Newbie question here.
How do I run the program? I've installed it and done pip install ccxt (using python) but don't know where to add my API keys or what to do to start the program. Is there a guide elsewhere? I've tried to figure it out in the manual but it wasn't much help.

**Comment by kroitor** [comment]
> How do I run the program?

This is not a standalone tool for end-user trading, it's a library that is used to code the trading, but it doesn't offer an end-user interface on its own, it only has programmatic and command-line interfaces for developers and coders. 

See end-user programs based on ccxt here: https://github.com/ccxt/ccxt/network/dependents

**Comment by mcintirejohn4** [comment]
Looked there and I don't see one for binance. In the issues however, I see a lot of questions about the exchange. Do you know where a dependency for it would be?

**Comment by kroitor** [comment]
@mcintirejohn4 sorry, I can't really consult you on 3rd-party end-user projects, we're only responsible for the library for programmers.

**Comment by mcintirejohn4** [comment]
Alright.
