### ISSUE TITLE
Question: precision of assets

### ISSUE THREAD

**Issue by dar7man** [ccxt/ccxt#12034]
Got a question regarding precision of assets.
It's not clear to me if precision of the same asset/currency if always the same all exchange markets. Or can it be different?
Can I use precision from Currency or should I always use precision from Market (base or quote depending where my currency is). 

For example, is it possible that BTC on WAVES/BTC (as quote) has precision 8 and on BTC/LTC (as base) has precision 7? 
Anyone? Thank you in advance!

**Comment by AnimusXCASH** [comment]
Yes, the precision can vary amongst exchanges. 

Brg

**Comment by dar7man** [comment]
Sorry, maybe I wasn't clear. 
I was asking if precision can very amongst markets on the same exchange?

**Comment by kroitor** [comment]
@dar7man hi! Yes, that is very common, an exchange can have varying precision with different markets (on the same exchange). Hope that answers your question, let us know if not.

**Comment by dar7man** [comment]
I'm not sure. I was asking if one asset (for example BTC), can have different precision on the **same exchange** but on **different markets**?

**Comment by kroitor** [comment]
@dar7man yes, that is possible, the same asset can have different precision within different market pairs on the same exchange.

**Comment by dar7man** [comment]
Thank you!

So, what's the point in CCTX of "precision" field in Currency structure?
How it corresponds to "precision" in Market structure?

**Comment by kroitor** [comment]
@dar7man withdrawal precision is not always the same as trading precision. 

> How it corresponds to "precision" in Market structure?

If the exchange does not specify a per-currency precision, then the highest precision from markets is taken for currencies.
If the exchange does define separate per-currency and per-market precision for BTC, then CCXT will use that where applicable.

**Comment by dar7man** [comment]
Got it! 
Thank you very much for detailed explanation.
