### ISSUE TITLE
Bulk orders not working on bybit 

### ISSUE THREAD

**Issue by Kalelv45** [ccxt/ccxt#12043]
- OS: os Mojave 
- Programming Language version: Python 
- CCXT version: 1.73.65

I cannot find a way to post multiple orders with just one api request, coming from bitmex, the call for bulkorders worked, 
it seems not to work on bybit, there is any method I can call to post multiple orders at once? 

kind regards.

**Comment by kroitor** [comment]
@Kalelv45 which code have you tried? Can you paste your code/verbose output to reproduce it? https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by Kalelv45** [comment]
It is something it is going to be implemented, or it is something that bybit don't allow? 
Checking on dir(bybit), it seems there is no method to do batch orders. (it seems strage, but it might be). 
@kroitor

**Comment by Kalelv45** [comment]
@kroitor son of the gods, do you know if there is a way to post bulk orders on bybit or is not allowed?

**Comment by kroitor** [comment]
@Kalelv45 pardon for the long wait, it is possible, i just didn't have the time to post an example here yet. Will provide the code asap!

**Comment by Kalelv45** [comment]
@kroitor you can just copy and paste the method, than I should be fine. Thanks for your endless patience.

**Comment by carlosmiei** [comment]
@Kalelv45 `createOrders` is now available.
