### ISSUE TITLE
Multiple trade best practices?

### ISSUE THREAD

**Issue by jlheidecker** [ccxt/ccxt#1204]
Does ccxt support chaining multiple trades? For example, converting USDT to BTC to ETH, but you need the second trade to happen after the first?

I'm currently inserting sleep() states between trades in PHP. Is there another recommendation?

**Comment by kroitor** [comment]
> I'm currently inserting sleep() states between trades in PHP.
> Is there another recommendation?

Yes, there is, check it here: https://github.com/ccxt/ccxt/blob/master/examples/php/built-in-rate-limiting-poller.php

Set `$exchange->enableRaeLimit = true;` on the exchange instance, after that you can call your methods sequentially and they should be properly rate-limited. Using the `sleep()` is not a very good idea as it makes the delays in between your requests uniform, but `sleep()` does not control the frequency and round-trip times of requests themselves, whereas the the built-in rate limiter accounts for that. Compare these two scenarios:

1. Send request A. Sleep 1 second. Send request B.
2. Send request A. Sleep 1 - elapsed time seconds. Send request B.

Scenario 2 is rate-limited well within exchange limits, but it does not wait for the entire second if it does not have to (some part of that delay has passed already).

**Comment by jlheidecker** [comment]
Yes thank you so much!
