### ISSUE TITLE
How to fetch FTX subaccount balance?

### ISSUE THREAD

**Issue by chanhw3** [ccxt/ccxt#12058]
- OS: windows 11
- Programming Language version: Python
- CCXT version:  1.73.79

The below code is not working, which can only fetch the Main account balance? 

 May I know if there is any documentation or way to fetch only subaccount balance?

exchange = ccxt.ftx({
    "apiKey": '...',
    "secret": '...',
})

exchange.fetch_balance(params={ 'FTX-SUBACCOUNT':'mySubAcc'})

Thanks for your help

**Comment by kroitor** [comment]
@chanhw3 please, paste your verbose output:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
exchange = ccxt.ftx({
    "apiKey": '...',
    "secret": '...',
})
markets = exchange.load_markets()
exchange.verbose = True
balance = exchange.fetch_balance(params={ 'FTX-SUBACCOUNT':'mySubAcc'})
print(balance)
```

**Comment by chanhw3** [comment]
it cannot correctly get balance from any of subaccount, below uses Sub3 as examaple

_ftx.fetch_balance(params={ 'FTX-SUBACCOUNT':'Sub3'})

verbose output:
fetch Request: ftx GET https://ftx.com/api/wallet/balances RequestHeaders: {'FTX-KEY': 'xxx', 'FTX-TS': 'xxx', 'FTX-SIGN': 'xxx', 'FTX-SUBACCOUNT': 'Sub8', 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate'} RequestBody: None



fetch Response: ftx GET https://ftx.com/api/wallet/balances 200 ResponseHeaders: {'Date': 'Tue, 22 Feb 2022 12:36:46 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding, Accept-Encoding, Origin', 'Cache-Control': 'private, max-age=0, no-cache', 'account-id': '89772228', 'ETag': 'W/"ac8eea414772b7f15a4aaeea28324869"', 'Content-Encoding': 'gzip', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Frame-Options': 'sameorigin', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': 'block-all-mixed-content', 'X-Cache-Status': 'MISS', 'CF-Cache-Status': 'MISS', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '6e18430f59d86e63-HKG', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'} ResponseBody: {"success":true,"result":[{"coin":"USDT","total":0.0,"free":0.0,"availableWithoutBorrow":0.0,"usdValue":0.0,"spotBorrow":0.0},{"coin":"BTC","total":0.0,"free":0.0,"availableWithoutBorrow":0.0,"usdValue":0.0,"spotBorrow":0.0}]}
{'info': {'success': True, 'result': [{'coin': 'USDT', 'total': '0.0', 'free': '0.0', 'availableWithoutBorrow': '0.0', 'usdValue': '0.0', 'spotBorrow': '0.0'}, {'coin': 'BTC', 'total': '0.0', 'free': '0.0', 'availableWithoutBorrow': '0.0', 'usdValue': '0.0', 'spotBorrow': '0.0'}]}, 'USDT': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'BTC': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'free': {'USDT': 0.0, 'BTC': 0.0}, 'used': {'USDT': 0.0, 'BTC': 0.0}, 'total': {'USDT': 0.0, 'BTC': 0.0}}

**Comment by kroitor** [comment]
@chanhw3 it looks like your `Sub8` balance is correctly returned, as expected:

```Python
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)
exchange = ccxt.ftx({
    "apiKey": '...',
    "secret": '...',
})
markets = exchange.load_markets()
exchange.verbose = True
balance = exchange.fetch_balance(params={ 'FTX-SUBACCOUNT':'Sub8'})
print('-----------------------------------------------')
print('\n\n\nYOUR SUCCESSFUL BALANCE RESPONSE:\n\n')
print(balance)
```

**Comment by kroitor** [comment]
Hope the above answers your question. Closing it for now, as there is no issue with the balance.

**Comment by chanhw3** [comment]
> Hope the above answers your question. Closing it for now, as there is no issue with the balance.

Thanks, it helps
