### ISSUE TITLE
Please add support for BKEX

### ISSUE THREAD

**Issue by OxfordGrid** [ccxt/ccxt#12057]
Could you add BKEX to CCXT, please? The exchange has a lot of smaller coins to trade.

Exchange home: [bkex.com](https://www.bkex.com/)
Api implementation: https://bkexapi.github.io/docs/api_en.htm
Endpoint: https://api.bkex.com/

Thank you.

**Comment by kroitor** [comment]
It has been submitted in a PR here: https://github.com/ccxt/ccxt/pull/8207
You can help download it and test it.
