### ISSUE TITLE
Support for wazirx 

### ISSUE THREAD

**Issue by rahuljauhari3** [ccxt/ccxt#12059]
Hi, @devs I am trying to place stop_limit order in wazirx using the following function:-

order=exchange.create_order(symbol,'stop_limit','buy',sell_amount,buyprice*1.1,params={"stopPrice":buyprice})

but it is showing me the following error:-

  File "----**----", line 109, in buy_order
    order=exchange.create_order(symbol,'stop_limit','buy',buy_amount,buyprice*1.1,params={"stopPrice":buyprice})
  File "---**--/opt/anaconda3/lib/python3.9/site-packages/ccxt/wazirx.py", line 590, in create_order
    raise ExchangeError(self.id + ' createOrder() supports limit and stop_limit orders only')
ccxt.base.errors.ExchangeError: wazirx createOrder() supports limit and stop_limit orders only

Pls let me know how to resolve this issue 

My ccxt version is '1.70.40'

**Comment by carlosmiei** [comment]
Hello @rahuljauhari3,
Thanks for reporting, this is indeed a bug in `createOrder` that will be fixed very shortly.


Thank you!
