### ISSUE TITLE
[Version 1.73.85] [Bitmart] Lesser known symbols report "Symbol not found" while popular symbols work fine

### ISSUE THREAD

**Issue by aFluxx** [ccxt/ccxt#12072]
- OS: Windows 11
- Programming Language version: PHP
- CCXT version: 1.73.85

I noticed that when using fetch_ticker on bitmart.php the lesser known symbols return "symbol not found".
For example when I call `fetch_ticker('BTSL/USDT')` I get "symbol not found", but when I call the same function on `"EOS/ETH"` I get the appropriate ticker data. This issue might be more bitmart API related but I wanted to ask your opinion.

```
$price = (new \ccxt\bitmart)->fetch_ticker($market->symbol_id); // "BTSL/USDT"

```

Bad results when called on `"BTSL/USDT"`
```
ccxt\BadSymbol: bitmart {"message":"Symbol not found","code":50001,"trace":"4a9bdc6d-2be6-4891-b408-591906dfa438","data":{}} in file /home/vagrant/code/vendor/ccxt/ccxt/php/Exchange.php on line 1536

#0 /home/vagrant/code/vendor/ccxt/ccxt/php/bitmart.php(2439): ccxt\Exchange->throw_exactly_matched_exception()
#1 /home/vagrant/code/vendor/ccxt/ccxt/php/Exchange.php(1771): ccxt\bitmart->handle_errors()
#2 /home/vagrant/code/vendor/ccxt/ccxt/php/Exchange.php(1527): ccxt\Exchange->fetch()
#3 /home/vagrant/code/vendor/ccxt/ccxt/php/Exchange.php(1531): ccxt\Exchange->fetch2()
#4 [internal function]: ccxt\Exchange->request()
#5 /home/vagrant/code/vendor/ccxt/ccxt/php/Exchange.php(2762): call_user_func_array()
#6 /home/vagrant/code/vendor/ccxt/ccxt/php/bitmart.php(755): ccxt\Exchange->__call()
#7 /home/vagrant/code/app/Http/Controllers/PriceFetchController.php(16): ccxt\bitmart->fetch_ticker()
```

Good result when called on `"EOS/ETH"`
```
{
    "symbol": "EOS/ETH",
    "timestamp": 1645561745812,
    "datetime": "2022-02-22T20:29:05.812Z",
    "high": 0.000837,
    "low": 0.000806,
    "bid": 0.00081834,
    "bidVolume": 209.81,
    "ask": 0.00082367,
    "askVolume": 1038.88,
    "vwap": 0.0008188186356184,
    "open": 0.00082853,
    "close": 0.000821,
    "last": 0.000821,
    "previousClose": null,
    "change": -0.00000753,
    "percentage": -0.91,
    "average": 0.000824765,
    "baseVolume": 11113.02,
    "quoteVolume": 9.099547874,
    "info": {
        "symbol": "EOS_ETH",
        "last_price": "0.00082100",
        "quote_volume_24h": "9.0995478740",
        "base_volume_24h": "11113.02",
        "high_24h": "0.00083700",
        "low_24h": "0.00080600",
        "open_24h": "0.00082853",
        "close_24h": "0.00082100",
        "best_ask": "0.00082367",
        "best_ask_size": "1038.88",
        "best_bid": "0.00081834",
        "best_bid_size": "209.81",
        "fluctuation": "-0.0091",
        "url": "https://www.bitmart.com/trade?symbol=EOS_ETH"
    }
}
```

**Comment by samgermain** [comment]
@kroitor I'm not sure what to do about this, the symbols not found on the actual api ( https://api-cloud.bitmart.com/spot/v1/ticker?symbol=BTSL_USDT ), If I just give a nonsense symbol though, it just returns an empty response ( https://api-cloud.bitmart.com/spot/v1/ticker?symbol=Bsaldfahf )

**Comment by aFluxx** [comment]
> @kroitor I'm not sure what to do about this, the symbols not found on the actual api ( https://api-cloud.bitmart.com/spot/v1/ticker?symbol=BTSL_USDT ), If I just give a nonsense symbol though, it just returns an empty response ( https://api-cloud.bitmart.com/spot/v1/ticker?symbol=Bsaldfahf )

Should I pass this through to the Bitmart Support telegram chat?

**Comment by samgermain** [comment]
> @samgermain
> 
> > @kroitor I'm not sure what to do about this, the symbols not found on the actual api ( https://api-cloud.bitmart.com/spot/v1/ticker?symbol=BTSL_USDT ), If I just give a nonsense symbol though, it just returns an empty response ( https://api-cloud.bitmart.com/spot/v1/ticker?symbol=Bsaldfahf )
> 
> Should I pass this through to the Bitmart Support telegram chat?

@kroitor What do you think?

**Comment by samgermain** [comment]
> @samgermain
> 
> > @kroitor I'm not sure what to do about this, the symbols not found on the actual api ( https://api-cloud.bitmart.com/spot/v1/ticker?symbol=BTSL_USDT ), If I just give a nonsense symbol though, it just returns an empty response ( https://api-cloud.bitmart.com/spot/v1/ticker?symbol=Bsaldfahf )
> 
> Should I pass this through to the Bitmart Support telegram chat?

That sounds like a good idea

**Comment by aFluxx** [comment]
> > @samgermain
> > > @kroitor I'm not sure what to do about this, the symbols not found on the actual api ( https://api-cloud.bitmart.com/spot/v1/ticker?symbol=BTSL_USDT ), If I just give a nonsense symbol though, it just returns an empty response ( https://api-cloud.bitmart.com/spot/v1/ticker?symbol=Bsaldfahf )
> > 
> > 
> > Should I pass this through to the Bitmart Support telegram chat?
> 
> That sounds like a good idea

@samgermain Alright, I will pass them to this github issue. I think this will be most clear.

**Comment by aFluxx** [comment]
I just had a conversation with John from Bitmart.

I quote:
"tickers for some pairs are not available because they have low liquidity"

Then I continued to ask how we can get bid/ask/current for these coins, and answer:

"ask/bid can be obtained in orderbook endpoint.   you can get price in trade history endpoint"

So I'll guess I have to make two calls :)

**Comment by samgermain** [comment]
> I just had a conversation with John from Bitmart.
> 
> I quote: "tickers for some pairs are not available because they have low liquidity"
> 
> Then I continued to ask how we can get bid/ask/current for these coins, and answer:
> 
> "ask/bid can be obtained in orderbook endpoint. you can get price in trade history endpoint"
> 
> So I'll guess I have to make two calls :)

Thanks for checking that, is this issue resolved then?
