### ISSUE TITLE
[Version 1.73.85] Error: Call to a member function split() on string in file /home/vagrant/code/vendor/ccxt/ccxt/php/bitmart.php on line 546

### ISSUE THREAD

**Issue by aFluxx** [ccxt/ccxt#12071]
- OS: Windows 11
- Programming Language version: PHP
- CCXT version: 1.73.85

There might be a php syntax error in the bitmart.php file on line 546.
It tries to call the function split on a string.  `$splitId = $id->split ($id, '_');` (copied from `bitmart.php`)
In this case `$id` is a string. f.e. `RAYUSDT` or `BTSLUSDT`

When I was using v1.70 this didn't give any errors, it is only when I update to v1.73 that the errors start.

I just called the fetch_ticker method with a symbol id of "BTSL/USDT"
```
$price = (new \ccxt\bitmart)->fetch_ticker($market->symbol_id);
```

```
Error: Call to a member function split() on string in file /home/vagrant/code/vendor/ccxt/ccxt/php/bitmart.php on line 546

#0 /home/vagrant/code/vendor/ccxt/ccxt/php/bitmart.php(626): ccxt\bitmart->fetch_contract_markets()
#1 /home/vagrant/code/vendor/ccxt/ccxt/php/Exchange.php(1890): ccxt\bitmart->fetch_markets()
#2 /home/vagrant/code/vendor/ccxt/ccxt/php/bitmart.php(734): ccxt\Exchange->load_markets()
#3 /home/vagrant/code/app/Http/Controllers/PriceFetchController.php(16): ccxt\bitmart->fetch_ticker()
```

**Comment by aFluxx** [comment]
I think `$id` should be replaced by `$this`, a small typo 🗡️

**Comment by aFluxx** [comment]
Hi @kroitor 

I'm not sure, but shouldn't the `bitmart.php` file also be changed?

`$splitId = $id->split($id, '_');` - to > `$splitId = $this->split($id, '_');`

Otherwise we'll keep getting `Call to member function split() on string`

**Comment by kroitor** [comment]
@aFluxx https://github.com/ccxt/ccxt/wiki/FAQ#hey-the-fix-youve-uploaded-is-in-js-would-you-fix-python--php-as-well-please

**Comment by aFluxx** [comment]
> @aFluxx https://github.com/ccxt/ccxt/wiki/FAQ#hey-the-fix-youve-uploaded-is-in-js-would-you-fix-python--php-as-well-please

Alright, great! Thanks for pointing that out. ;D
