### ISSUE TITLE
Documentation over the custom request?

### ISSUE THREAD

**Issue by RyanDelap** [ccxt/ccxt#1208]
The overview of this project claims to have several builtin functions to create Custom API calls (Custom Exchange API)
https://github.com/ccxt/ccxt/wiki/Manual#overview
However there doesn't seem to be any documentation over how to actually do it. I've looked through examples and the manual several times and I'm not seeing it.

I apologize in advance for my ignorance if I'm missing it. 😃

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://github.com/ccxt/ccxt/wiki/Manual#publicprivate-api
- https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods
- https://github.com/ccxt/ccxt/wiki/Manual#api-method-naming-conventions

```
console.log (new ccxt.kraken ())   // JavaScript
print (dir (ccxt.hitbtc ()))        # Python
var_dump (new \ccxt\okcoinusd ()); // PHP
```

```
bitso.publicGetTicker ({ book: 'eth_mxn' })                 // JavaScript
ccxt.zaif().public_get_ticker_pair ({ 'pair': 'btc_jpy' })  # Python
$luno->public_get_ticker (array ('pair' => 'XBTIDR'));      // PHP
```
