### ISSUE TITLE
Retrieving Rate Limit with CCXT

### ISSUE THREAD

**Issue by StefanBloemheuvel** [ccxt/ccxt#12097]
I came across CCXT while investigating the Bitvavo api, which is also a supported exchange in CCXT. 
Link to [bitvavo github](https://github.com/bitvavo/python-bitvavo-api)

Here, I can find the rate limit which is set to 1000 requests per minute, which helps not violating their usage rules.
It is as easy as: 
```
limit = bitvavo.getRemainingLimit()
```
However, where can I find this information when using CCXT to connect to their API? I cannot find any methods that retrieve that information.

Thanks in advance

**Comment by DoctorSlimm** [comment]
Each exchange object has a rateLimit property which is accessible in python and javascript like so 
`bitvavo.rateLimit`
this number reflects the milliseconds between requests on average for the cheapest endpoint, in the case of Bitvavo, we first divide 1000 requests by 60 seconds to get the number of requests to send per second which is 16.666, then we divide 1 second ie 1000ms by 16.666 to get a value of 60.1ms between consequent requests requests. 

Costs per endpoint can be found in the `bitvavo.api` property:
`
 'api': {
                'public': {
                    'get': {
                        'time': 1,
...
                        '{market}/trades': 5,
...
                        'ticker/24h': { 'cost': 1, 'noMarket': 25 },
`
Moreover, not all endpoints cost the same, the ones that adhere to the cheapest costing will have a weight of 1 in this case meaning 1000 requests per minute. Different endpoints often have different rate limits associated with them. For example the `{market}/trades` endpoint has a relative cost of 5, as can be seen from their documentation: 

![image](https://user-images.githubusercontent.com/87606888/155693491-1b2d22e5-0505-40f9-ad03-29312d5a82b8.png)
 
Some rate limits also depend on on the parameters passed, these will have a dictionary as a value for example in this case `ticker/24h` detailing the different costs for different ways of calling the endpoint. In this case it is more costly to retrieve information about all the tickers at once, and cheaper to specify s single symbol. 

![image](https://user-images.githubusercontent.com/87606888/155694474-e29dd59f-6481-4710-b339-faeea4230dcf.png)


Hope this helps!

**Comment by StefanBloemheuvel** [comment]
Thanks for the explanation, this really clears thing up!
So I found another function in the CCXT api that directly tells my the amount of requests I still have left:
```
exchange.last_response_headers.get('Bitvavo-Ratelimit-Remaining')
```
Which after calling a function with a cost of 1 will go 999,998,997.... and will reset every minute.

So the only thing I have to keep in mind is making a while True loop that checks if that remaining ratelimit is still bigger than 0, and then does something?

**Comment by kroitor** [comment]
> So the only thing I have to keep in mind is making a while True loop that checks if that remaining ratelimit is still bigger than 0, and then does something?

@StefanBloemheuvel technically, yes, but in CCXT that is already handled for you, so if you're using CCXT then you don't have to manage those delays in the userland.
