### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by BBX0001** [ccxt/ccxt#12099]
Hey guys.
I use python, I would like to know, how do I transform the timestamp to date and time without using pandas, to keep the date inside the table?

from datetime import datetime
import ccxt

binance = ccxt.binance()

symbol = 'BTC/USDT'
ticker = '5m'
since = binance.parse8601('2022-02-19T21:00:00Z')
limit = 1000

binance.loadMarkets()
res = binance.fetch_ohlcv(symbol, ticker, since, limit)

print(res)

**Comment by kroitor** [comment]
Use `exchange.iso8601`:

```Python
from datetime import datetime
import ccxt

binance = ccxt.binance()

symbol = 'BTC/USDT'
ticker = '5m'
since = binance.parse8601('2022-02-19T21:00:00Z')
limit = 1000

binance.loadMarkets()
ohlcvs = binance.fetch_ohlcv(symbol, ticker, since, limit)
result = [[exchange.iso8601(candle[0])] + candle[1:] for candle in ohlcvs)
print(result)
```

**Comment by BBX0001** [comment]
This script is showing this error message.

File ["<ipython-input-15-4413ac6da2e5>"](https://localhost:8080/#), line 12
    result = [[datetime.datetime.fromtimestamp(candle[0]/1000.0)] + candle[1:] for candle in ohlcvs)
                                                                                                   ^
SyntaxError: invalid syntax

**Comment by kroitor** [comment]
@BBX0001 pardon a small typo, change the last bracket to `]`:

```Python
result = [[datetime.datetime.fromtimestamp(candle[0]/1000.0)] + candle[1:] for candle in ohlcvs]
```

**Comment by BBX0001** [comment]
Sorry if I put something wrong, but the error still remains.

from datetime import datetime
import ccxt

binance = ccxt.binance()

symbol = 'BTC/USDT'
ticker = '5m'
since = binance.parse8601('2022-02-19T21:00:00Z')
limit = 1000

binance.loadMarkets()
ohlcvs = binance.fetch_ohlcv(symbol, ticker, since, limit)
result = [[exchange.iso8601(candle[0])] + candle[1:] for candle in ohlcvs]]
print(result)

File ["<ipython-input-25-c420e7eee45b>"](https://localhost:8080/#), line 13
    result = [[exchange.iso8601(candle[0])] + candle[1:] for candle in ohlcvs]]
                                                                              ^
SyntaxError: invalid syntax

**Comment by kroitor** [comment]
@BBX0001 you now have two square brackets at the end of that line but there should be just one ending square bracket.
