### ISSUE TITLE
New Exchange: CoinOne

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1209]
api doc: https://doc.coinone.co.kr/
url: https://coinone.co.kr
fee: https://coinone.co.kr/guide/
volume: https://coinmarketcap.com/exchanges/coinone/
address: 19F, Three IFC, 10 Gukjegeumyung-ro, Yeongdeungpo-gu, Seoul 
company info: Coinone Inc.  CEO Myunghun Cha | Business Registration 261-81-07437E-Commerce Registration 2016-서울영등포-1289호
based country: korea
priority: high
note:  ranked top : 6

**Comment by kroitor** [comment]
@jjhesk unfortunately, I don't have an implementation for CoinOne yet, not even the public one. Hope to make a quick draft of it asap.

**Comment by jjhesk** [comment]
@kroitor sorry i dont wanna rush you. I hope you can speed up the progress faster with some research info. many thanks

**Comment by jjhesk** [comment]
<img width="178" alt="2018-01-24 11 26 51" src="https://user-images.githubusercontent.com/629338/35319687-5ca529cc-00fa-11e8-863a-89f169a511e1.png">
added logo

**Comment by jjhesk** [comment]
sample:https://gist.github.com/jjhesk/d99ff2254f624330cf2bc25f391ea63d
