### ISSUE TITLE
ftx symbol 'BTC-MOVE-0224' is a future contract but with invalid expiry datetime: undefined:

### ISSUE THREAD

**Issue by bongkook** [ccxt/ccxt#12104]
Hello.
The following error occurs when using the FTX Exchange from two days ago.
Since the symbol name of BTC-MOVE-0224 changes every day, it seems that an error occurs when the day changes.
Please fix the error.
=====error=====
ftx symbol 'BTC-MOVE-0224' is a future contract but with invalid expiry datetime: undefined:
Thank you.

**Comment by bongkook** [comment]
Since the symbol name of BTC-MOVE-0224 changes every day, it seems that an error occurs when the day changes.

**Comment by kroitor** [comment]
@bongkook please, paste your code: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by bongkook** [comment]
@kroitor 
Thanks for your reply.
The current version used is 1.74.3.
An error occurred when executing the method below.
=========================
exchange.fetchTicker('ETH-PERP')
=========================
However, the error does not occur often.
When I debugged it, it seems to be happening in fetchMarkets.

**Comment by kroitor** [comment]
@bongkook can you elaborate a bit please? I'm not sure how a perpetual contract like ETH-PERP could cause an invalid expiry date, it does not have an expiration date. In your original message you mentioned BTC-MOVE-0224 – can you paste the code you use that causes a breakdown with an expiring symbol? Also, CCXT started unifying the contract symbols, we would recommend switching to the unified contract symbols as described here: https://github.com/ccxt/ccxt/issues/10931

**Comment by bongkook** [comment]
@kroitor 
The error seems to occur after the commit below.
please check.
https://github.com/ccxt/ccxt/commit/a21da148e64253ae0ff65c0fa197bf40b6d7a684

**Comment by kroitor** [comment]
@bongkook can you please paste **your** code to reproduce it ? A one-liner with ETH-PERP isn't enough to resolve it, unfortunately.

Try this please:

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.ftx()
markets = exchange.load_markets()
market = exchange.market('ETH/USD:USD')
pprint(market)
```

Please, paste your complete output.

**Comment by bongkook** [comment]
@kroitor 
There is no error now.
It seems to only happen when the market opens.

This is an example using javascript.
' =============sample=============
const ftx = new ccxt.ftx();
await ftx.loadMarkets();
let market = await ftx.fetchTicker('ETH-PERP');
console.log(ccxt.version);
console.log(market);
'=============result=============
>  1.74.11
>  {
>    symbol: 'ETH/USD:USD',
>    timestamp: 1645781276134,
>    datetime: '2022-02-25T09:27:56.134Z',
>    high: undefined,
>    low: undefined,
>    bid: 2575.1,
>    bidVolume: undefined,
>    ask: 2575.2,
>    askVolume: undefined,
>    vwap: undefined,
>    open: 2396.633016360767,
>    close: 2575.1,
>    last: 2575.1,
>    previousClose: undefined,
>    change: 178.46698363923264,
>    percentage: 6.93048750103812,
>    average: undefined,
>    baseVolume: undefined,
>    quoteVolume: 4515064998.5249,
>    info: {
>      name: 'ETH-PERP',
>      enabled: true,
>      postOnly: false,
>      priceIncrement: '0.1',
>      sizeIncrement: '0.001',
>      minProvideSize: '0.001',
>      last: '2575.1',
>      bid: '2575.1',
>      ask: '2575.2',
>      price: '2575.1',
>      type: 'future',
>      baseCurrency: null,
>      quoteCurrency: null,
>      underlying: 'ETH',
>      restricted: false,
>      highLeverageFeeExempt: true,
>      largeOrderThreshold: '5000.0',
>      change1h: '-0.008661841700030797',
>      change24h: '0.0693048750103812',
>      changeBod: '-0.008127262922733226',
>      quoteVolume24h: '4515064998.5249',
>      volumeUsd24h: '4515064998.5249'
>    }
>  }

**Comment by kroitor** [comment]
@bongkook we will try to reproduce it on our side, thanks!

**Comment by samgermain** [comment]
>  it seems that an error occurs when the day changes.

> It seems to only happen when the market opens.

What do you mean by those statements, can you be more precise?

**Comment by bongkook** [comment]
@samgermain thank you so much.
In BTC-MOVE-0224, the 0224 part changes daily.
When the daily candle is changed, 0224 is also changed, and an error seems to occur at this time.

**Comment by samgermain** [comment]
> @samgermain thank you so much. In BTC-MOVE-0224, the 0224 part changes daily. When the daily candle is changed, 0224 is also changed, and an error seems to occur at this time.

What time is that

**Comment by bongkook** [comment]
Sorry for the lack of explanation.
Occurs only at the open price of daily candles.

**Comment by samgermain** [comment]
> 

And how long does it last for? It sounds like at around 00:00 UTC the expiry is undefined for a bit. Is that correct?

**Comment by bongkook** [comment]
Yes.
It seems to last about 20 seconds.
After that it works normally.

**Comment by ttodua** [comment]
The problem might be happening really as I see, and it might affect not just FTX, but also other exchanges, where 'futures' and 'spot' markets are fetched in one (fetchMarkets) method together, and then spot pairs itterated through futures dictionary. The problem is that when it comes to the end of day (00:00), then the spot symbol which was available till that day i.e. `BTC-MOVE-0224` would be changed to i.e. `BTC-MOVE-0225` and then in next call right away that symbol is checked against futures dictionary [here](https://github.com/ccxt/ccxt/blob/master/js/ftx.js#L554), but at that moment `BTC-MOVE-0225` might not be present in fetched dictionary from futures endpoint.  (either lag from API engine, or lag between usercode requests `await this.publicGetFutures ()`)
this might be in reverse:  at 23:59 the `this.publicGetMarkets` might return `BTC-MOVE-0224` but the next call `this.publicGetFutures` (which might trigger at 00:00) might already contain `BTC-MOVE-0225` and not `BTC-MOVE-0224`.  Thus, in those cases, those issues will happen. needs fix.

**Comment by pietrodn** [comment]
I am experiencing this issue as well. It happens at 00:00 UTC on `MOVE` symbols. This night it happened to us on `BTC-MOVE-0407` on a production strategy.

I think that the correct policy is to emit the warning and not include the symbol in the markets. I'll be preparing a PR soon.
