### ISSUE TITLE
balance total should use marginBalance in bitmex

### ISSUE THREAD

**Issue by kevyu** [ccxt/ccxt#1210]
In bitmex, fetchBalance method should use marginBalance as total  rather than amount.

Margin Balance = Wallet Balance + Unrealised PnL,

--------------------
- OS: Windows
- Programming Language version: JS
- CCXT version: 1.10.634
- Exchange: Bitmex
- Method: fetchBalance

**Comment by kroitor** [comment]
Fixed in 1.10.665. Thank you!
