### ISSUE TITLE
OKX fetch_ticker volume wrong for futures

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#12128]
- OS:
- Programming Language version: python
- CCXT version:1.74.40

```
``` python
import ccxt
exchange = ccxt.okx({'options': {'defaultType': 'future'}})
res = exchange.fetch_ticker('BTC/USDT')
print(res)
res = exchange.fetch_ticker('BTC/USDT:USDT')
print(res)
```
```

The 24hvolume reported by the first call seems correct ... 
the problem happens with the futures/swap call - which returns a lower quote volume than base volume.
This is only possible with a pair < 1$ - but not with BTC which is at 38k$+ at the moment.

It's roughly correct to do `baseVolume * price = quote_volume` - however the value in `quoteVolume` appears oddly low. It might be a problem with the okx API too - or with how i'm interpreting results ... but it seems odd nonetheless to me at the moment.


```
{'symbol': 'BTC/USDT',
 'timestamp': 1645979284793,
 'datetime': '2022-02-27T16:28:04.793Z',
 'high': 39860.0,
 'low': 38196.3,
 'bid': 39158.2,
 'bidVolume': 0.76569936,
 'ask': 39158.3,
 'askVolume': 0.17322356,
 'vwap': 38998.868089938755,
 'open': 39170.1,
 'close': 39131.0,
 'last': 39131.0,
 'previousClose': None,
 'change': -39.1,
 'percentage': -0.0998210369644192,
 'average': 39150.55,
 'baseVolume': 6374.14859393,
 'quoteVolume': 248584580.20034465,
 'info': {'instType': 'SPOT',
  'instId': 'BTC-USDT',
  'last': '39131',
  'lastSz': '0.02088',
  'askPx': '39158.3',
  'askSz': '0.17322356',
  'bidPx': '39158.2',
  'bidSz': '0.76569936',
  'open24h': '39170.1',
  'high24h': '39860',
  'low24h': '38196.3',
  'volCcy24h': '248584580.20034464',
  'vol24h': '6374.14859393',
  'ts': '1645979284793',
  'sodUtc0': '39108.3',
  'sodUtc8': '39355.2'}}

{'symbol': 'BTC/USDT:USDT',
 'timestamp': 1645979287105,
 'datetime': '2022-02-27T16:28:07.105Z',
 'high': 39878.0,
 'low': 38182.6,
 'bid': 39123.7,
 'bidVolume': 125.0,
 'ask': 39123.8,
 'askVolume': 795.0,
 'vwap': 0.01,
 'open': 39166.5,
 'close': 39117.7,
 'last': 39117.7,
 'previousClose': None,
 'change': -48.8,
 'percentage': -0.1245962748777654,
 'average': 39142.1,
 'baseVolume': 8656891.0,
 'quoteVolume':   86568.91,   <<<< How can quote volume be lower than base volume? 
 'info': {'instType': 'SWAP',
  'instId': 'BTC-USDT-SWAP',
  'last': '39117.7',
  'lastSz': '2',
  'askPx': '39123.8',
  'askSz': '795',
  'bidPx': '39123.7',
  'bidSz': '125',
  'open24h': '39166.5',
  'high24h': '39878',
  'low24h': '38182.6',
  'volCcy24h': '86568.91',
  'vol24h': '8656891',
  'ts': '1645979287105',
  'sodUtc0': '39106.7',
  'sodUtc8': '39350'}}
```

**Comment by kroitor** [comment]
@xmatthias when trading contracts, you're not trading BTC or USDT. You're actually trading a contract, that is valued in a USDT equivalent. So, each contract has the equivalent contract size (how much USDT one contract costs). By multiplying the number of traded contracts by the contract size you get the total traded volume in USDT:

```JavaScript
~/ccxt $ node examples/js/cli okx market BTC/USDT:USDT
2022-02-27T17:20:20.879Z
Node.js: v16.13.2
CCXT v1.74.35
okx.market (BTC/USDT:USDT)
2022-02-27T17:20:23.503Z iteration 0 passed in 0 ms

{
  id: 'BTC-USDT-SWAP',
  symbol: 'BTC/USDT:USDT',
  base: 'BTC',
  quote: 'USDT',
  baseId: 'BTC',
  quoteId: 'USDT',
  active: true,
  type: 'swap',
  linear: true,
  inverse: false,
  spot: false,
  swap: true,
  future: false,
  option: false,
  margin: false,
  contract: true,
  contractSize: 0.01, // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< HERE
  expiry: 0,
  expiryDatetime: '1970-01-01T00:00:00.000Z',
  optionType: undefined,
  strike: undefined,
  settle: 'USDT',
  settleId: 'USDT',
  precision: { amount: 1, price: 0.1 },
  limits: {
    leverage: { min: 1, max: 125 },
    amount: { min: 1, max: undefined },
    price: { min: 0.1, max: undefined },
    cost: { min: undefined, max: undefined }
  },
  info: {
    alias: '',
    baseCcy: '',
    category: '1',
    ctMult: '1',
    ctType: 'linear',
    ctVal: '0.01',
    ctValCcy: 'BTC',
    expTime: '',
    instId: 'BTC-USDT-SWAP',
    instType: 'SWAP',
    lever: '125',
    listTime: '1611916828000',
    lotSz: '1',
    minSz: '1',
    optType: '',
    quoteCcy: '',
    settleCcy: 'USDT',
    state: 'live',
    stk: '',
    tickSz: '0.1',
    uly: 'BTC-USDT'
  },
  tierBased: undefined,
  percentage: undefined,
  taker: 0.0005,
  maker: 0.0002,
  futures: false
}
```

Hope that answers your question, let us know if not.

**Comment by xmatthias** [comment]
Hi @kroitor,

sorry for the late response - i've just gotten back to this.
Unfortunately, the logic doesn't really add up.

looking at the sample of BTC above with the following parameters - i can get from base to quote volume by multiplying base-volume with contractSize. (`baseVolume * contractSize = quoteVolume`).

```
'baseVolume': 8656891.0,
'quoteVolume': 86568.91,

...
contractSize: 0.01,
```

In the end, both are however values in in BTC - not in USDT (so it's not in "quoteCurrency" - but in base currency.
This is also supported by looking at the response model [from the docs](https://www.okx.com/docs-v5/en/#websocket-api-public-channel-tickers-channel) 

> volCcy24h | String | 24h trading volume, with a unit of currency.If it is a derivatives contract, the value is the number of base currency.If it is SPOT/MARGIN, the value is the number of quote currency.
> vol24h | String | 24h trading volume, with a unit of contact.If it is a derivatives contract, the value is the number of contracts.If it is SPOT/MARGIN, the value is the amount of base currency.

- as well as comparing how ccxt handles this:

https://github.com/ccxt/ccxt/blob/266ba43c00c0c1860f688ba66316d33496b62da1/js/okx.js#L1159-L1160


Based on the api documentation for a derivatives case:
"volCcy24h" is in base currency (so in BTC).
"vol24h" is the number of BTC contracts

So neither is in quote currency (also not after including contractSize).
This seems unique to okex (gateio/binance seems to work fine in this regards) - so i still think this is a problem with okx - where either `quoteVolume` should be left empty (it's not quote volume - so having it there is missleading!) - or should be emulated/converted to be in USDT (basically multiplied with "last").

**Comment by kroitor** [comment]
@xmatthias thx for your feedback, will look into it and will add fixes where appropriate.

**Comment by xmatthias** [comment]
I guess based on #12358, this can be closed ...
