### ISSUE TITLE
Feature : add 'updateTime' or 'updateDate' in common 'order data'

### ISSUE THREAD

**Issue by dawadam** [ccxt/ccxt#12137]
Hi,
In the 'order data', 'timestamp' and 'date' are present.
It would be handy if the 'update date' was also present.

**Comment by frosty00** [comment]
there is a field called `lastTradeTimestamp`, let us know if this does not solve your issue

**Comment by dawadam** [comment]
Sorry but `lastTradeTimestamp`is not defined for Binance orders.
Yet we can read the information: `info.updateTime`

```
{
  info: {
    symbol: 'BTCUSDT',
    orderId: 'xxx',
    orderListId: '-1',
    clientOrderId: 'xxx',
    price: '42353.64000000',
    origQty: '0.00024000',
    executedQty: '0.00024000',
    cummulativeQuoteQty: '10.16487360',
    status: 'FILLED',
    timeInForce: 'GTC',
    type: 'LIMIT',
    side: 'SELL',
    stopPrice: '0.00000000',
    icebergQty: '0.00000000',
    time: '1645121706511',
    updateTime: '1646087568645',
    isWorking: true,
    origQuoteOrderQty: '0.00000000'
  },
  id: 'xxx',
  clientOrderId: 'xxx',
  timestamp: 1645121706511,
  datetime: '2022-02-17T18:15:06.511Z',
  lastTradeTimestamp: undefined,
  symbol: 'BTC/USDT',
  type: 'limit',
  timeInForce: 'GTC',
  postOnly: false,
  side: 'sell',
  price: 42353.64,
  stopPrice: undefined,
  amount: 0.00024,
  cost: 10.1648736,
  average: 42353.64,
  filled: 0.00024,
  remaining: 0,
  status: 'closed',
  fee: undefined,
  trades: [],
  fees: []
}
```

**Comment by dawadam** [comment]
@frosty00 can you reopen ?

**Comment by dawadam** [comment]
@frosty00 can you warm up?

Maybe I should open a new topic?

Maybe @kroitor can watch?

**Comment by ttodua** [comment]
late reply, but i'll add note, that "updateTime" is not a consistent concept across exchanges. in some exchanges, it might have a meaning of 'lastTradeTimestamp' while in other exchanges it might mean 'last edit time' (as orders can be modified, without trade).
So, it's not yet unified, however we have already started thinking about it's unifications

**Comment by dawadam** [comment]
I'm uping this post.
If it is insoluble, the easiest way is to propose **several unified times**.
- lastTradeUpdate: time of last trade passed
- lastEdition: time of the last edition
- lastUpdate: time of the last transaction or the last edition.

**Comment by ttodua** [comment]
there had been implemented `lastUpdateTimestamp` unified field in the past. closing this issue.
