### ISSUE TITLE
Bybit fetch_markets do not support fetch spot symbol?

### ISSUE THREAD

**Issue by kissdish** [ccxt/ccxt#12133]
- OS:  centos
- Programming Language version: python3
- CCXT version: 1.74

bybit fetch_markets can only fetch swap and future, no spot support, can it be this ?

https://api.bybit.com/spot/v1/symbols

**Comment by kroitor** [comment]
We are working on that right now, you can already use Bybit spot markets via the implicit API from CCXT, the unified API will arrive soon.

- https://docs.ccxt.com/en/latest/manual.html#implicit-api

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/search?q=bybit+spot&type=issues
