### ISSUE TITLE
How people are running their bots over a long period of time? (VPS/DEDICATED SERVER)

### ISSUE THREAD

**Issue by ChrisLaha** [ccxt/ccxt#12142]
- OS: MacOS Monterey 12.1
- Programming Language version: Python 3.9
- CCXT version: Most up to date

```
I'm just curious on how people are deploying their bots.
I've been trying to connect my bot in an AWS lambda function but ccxt is too large for it to work. 

Has anyone found a solution to this or another way without running on my personal computer 24/7

Any advice is greatly appreciated. Thanks.
```

**Comment by frosty00** [comment]
mostly using vps's, you can get cheap e2's on google for less than $25 a month

**Comment by samgermain** [comment]
I made some [pdf instructions](https://github.com/samgermain/freqtrade-ec2-instructions) for how to get freqtrade (which is built on CCXT) running on an AWS t2.micro. Using clang as a compiler helped. You can try looking at the setup.sh script used in there if it helps.

----------

I never had any problems with CCXT, but TA-LIB didn't always work when I was using gcc as my compiler

**Comment by 9808us** [comment]
I use a raspberry pi4.
Low power consumption. Pi is perfect for 24/7

**Comment by samgermain** [comment]
> I use a raspberry pi4. Low power consumption. Pi is perfect for 24/7

That's another option, there's a [udemy course](https://www.udemy.com/course/run-your-trading-robot-on-a-vps-or-raspberry-pi/) on how to set up freqtrade on a raspberry pi as well, I've never taken it and it might be a waste of money, but it's there

**Comment by ChrisLaha** [comment]
Thanks everyone for all the advice!

**Comment by samgermain** [comment]
I've been told oracle arm cores are also good for more vCPUs and ram that the aws ec2s

**Comment by ttodua** [comment]
I would add that:
> AWS Lambda functions just won't work since ccxt is too big of a package.
If you clone the repository, it might be around 2GB or so, but I'd advise you just clone the bare repo with depth=1 (or just the ZIP and unpack it), so it will not be big, but under 100MB or so.

besise that, other above posts probably answered the topic.
Let us know if you have any more questions/issues with CCXT/
