### ISSUE TITLE
Bitmex Symbol Mapping

### ISSUE THREAD

**Issue by gocharting101** [ccxt/ccxt#12141]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```
My understanding is that we must send the standard CCXT symbol id like BTC/USD and it would internally send the correct symbol XBTUSD to the exchange.  But when I now try in Bitmex (test-net mode) to place an order, it successfully places an order when I pass the symbol XBTUSD but if I pas the symbol BTC/USD, it returns error message stating Bitmex does not support this symbol

orderQty: 1
orderType: "Limit"
price: 2731.55
side: "Buy"
size: 1
symbol: "ETHUSD"

Above params are successfully placed

orderQty: 1
orderType: "Limit"
price: 2731.55
side: "Buy"
size: 1
symbol: "ETH/USD"

Abode params are unsuccessful in placing the order because of the symbol

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

**Comment by samgermain** [comment]
`BTC/USD` is a spot market symbol, and bitmex only has `swap` and `future` markets.
Maybe you meant one of these?

```
BTC/USD:BTC
BTC/USDT:USDT
BTC/USD:BTC-220325
BTC/USDT:USDT-220325
BTC/USD:BTC-220624
```

---------------

You also don't ***need*** to use the CCXT symbols, you can use the exchange specific symbols, but the CCXT symbols will work on other exchanges

**Comment by gocharting101** [comment]
When you say
You also don't need to use the CCXT symbols, you can use the exchange specific symbols, but the CCXT symbols will work on other exchanges

Is this specific to Bitmex only?  Because for ll other exchanges I use the standard CCXT symbol as explained below

https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

So going by above docs, we should have used BTC/USD in Bitmex for placing an order on XBTUSD

**Comment by kroitor** [comment]
@gocharting101 

> So going by above docs, we should have used BTC/USD in Bitmex for placing an order on XBTUSD

Yes, that is correct. Let us know if that does not answer your question. Feel free to reopen this issue or just ask further questions here if necessary.

**Comment by gocharting101** [comment]
Hi @kroitor , thats is not what is happening.  In the Bitmex TestNet, I am sending symbol = BTC/USD to place an order on XBTUSD and the ccxt is sending back message stating Symbol does not exist

Request Parameters to place an order
exchange: "bitmex"
extra: {clOrdID: "tX1uhW_6n", timeInForce: "GoodTillCancel", displayQty: ""}
orderQty: 100
orderType: "Limit"
price: 41555.5
side: "Buy"
size: 100
symbol: "BTC/USD"

Response:
"bitmex does not have market symbol BTC/USD"

**Comment by samgermain** [comment]
> "bitmex does not have market symbol BTC/USD"

That's correct, use `BTC/USD:BTC `.

`BTC/USD` is a spot market symbol and bitmex doesn't have spot trading
