### ISSUE TITLE
Documentation missing for a number of methods

### ISSUE THREAD

**Issue by samgermain** [ccxt/ccxt#12140]
These are all the methods inside `base.exchange.has` that aren't mentioned in our documentation. We should either add documentation for them, or removed them from has if they are not a unified method. Please mark the box as complete after doing so.

- [x] addMargin
- [x] cancelOrders
- [x] createLimitOrder
- [x] deposit
- [x] editOrder
- [x] fetchAccounts
- [x] fetchBorrowRate
- [x] fetchBorrowRateHistory
- [x] fetchBorrowRatesPerSymbol
- [x] fetchBorrowRates
- [x] fetchCanceledOrders
- [x] fetchClosedOrder
- [x] fetchDeposit
- [x] fetchDepositAddressesByNetwork
- [x] fetchDeposits
- [x] fetchFundingFee
- [x] fetchFundingHistory
- [x] fetchLedgerEntry
- [x] fetchOpenOrder
- [x] fetchOrderBooks
- [x] fetchPosition
- [x] fetchPositionsRisk
- [x] fetchTradingFee
- [x] fetchTradingLimits
- [x] fetchTransfers
- [x] fetchWithdrawal
- [x] reduceMargin
- [x] setLeverage
- [x] setMarginMode
- [x] setPositionMode
- [x] signIn
- [x] withdraw

**Comment by samgermain** [comment]
@pcriadoperez Requested that we add the request and response parameters to the documentation in a table and I agree. [This PR](https://github.com/ccxt/ccxt/pull/12220) is an example

**Comment by ttodua** [comment]
I think that one person should take a few days and dedicate to the docs. It will be better, than one-by-one of us (unfamiliar with markdown) started to add this or that docs , while each of us' commits will be different with non-similar styling, formatting, syntax and etc. So, whoever is well-versed in writing the docs among us, should be assigned to this task imho.

**Comment by kroitor** [comment]
@ttodua i agree as well, will focus on writing the docs among other things.

**Comment by samgermain** [comment]
> @ttodua i agree as well, will focus on writing the docs among other things.

I almost have it done on that PR

**Comment by samgermain** [comment]
All done on this PR https://github.com/ccxt/ccxt/pull/12261
