### ISSUE TITLE
New Exchange: Coinegg

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1215]
api doc: https://www.coinegg.com/explain.api.html
fee: https://www.coinegg.com/fee.html?lang=en_US
url: https://www.coinegg.com
volume: https://coinmarketcap.com/exchanges/exx/
address: 英国 邮编B17 8TA,伯明翰市,亨斯坦顿大道38号 38 Hunstanton Avenue, Birmingham, B17 8TA, United Kingdom
company info: CoinEgg Limited, (HK)
priority: medium
note:

**Comment by Deathamns** [comment]
Anyone working on this?

**Comment by kroitor** [comment]
@Deathamns would be great if you can submit it )

**Comment by qiangxs** [comment]
How many days can we use coigegg api please?

**Comment by kroitor** [comment]
@qiangxs we will merge it within a few days.

**Comment by qiangxs** [comment]
When coinegg API can be used please?



发自我的 iPhone

**Comment by kroitor** [comment]
@qiangxs it's already merged, though, still may require some testing. Don't forget to update ccxt to version 1.10.1265.

**Comment by qiangxs** [comment]
Do you mean that I can use it after upgrading ccxt?

发自我的 iPhone

**Comment by kroitor** [comment]
@qiangxs yes, but be cautious, use it at your own risk. There may still be issues, as this library is under development. Let us know if you have any difficulties with it (if you do, please follow this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue).
