### ISSUE TITLE
question: fetch P2P / C2C price

### ISSUE THREAD

**Issue by liarclor** [ccxt/ccxt#12163]
Hello, 

Recently I came across trading fiat as well.

is there a way to fetch exchange's c2c / p2p their price?

for example, binance for buying USDT with USD: https://p2p.binance.com/en?fiat=USD&payment=ALL
and binance for selling USDT for VND: https://p2p.binance.com/en/trade/sell/USDT?fiat=VND&payment=ALL

or the better way will be just web scrape it?

**Comment by ttodua** [comment]
At this given moment, Binance API docs doesn't include p2p documentation, so it is not supported. (as @sc0Vu  mentioned, there is undocumented approach https://github.com/1412dev/binance-p2p-api/blob/main/src/BinanceApi/Binance.php which might stop working at any time, as it's not API ).

Let us know if you have any issues with CCXT.
