### ISSUE TITLE
hitbtc2 money transfer from main account to trading account

### ISSUE THREAD

**Issue by CopurOnur** [ccxt/ccxt#1216]
@kroitor 
Hello Igor,
I wonder how can i transfer my money from main account to trading account in hitbtc2. Is there a way to do it with ccxt.

- Programming Language version: python 3.6
- CCXT version:1.10.666
- Exchange:hitbtc2

**Comment by kroitor** [comment]
- #406 

```Python
hitbtc = ccxt.hitbtc2({'apiKey': 'YOUR_API_KEY', 'secret': 'YOUR_SECRET', 'enableRateLimit': True})

# balances (unified API)

hitbtc.fetch_balance({'type':'trading'})
hitbtc.fetch_balance({'type':'account'})

# transfers (custom private API)

hitbtc.private_post_account_transfer({'currency': 'BTC', 'amount': 1.0, 'type': 'bankToExchange'})
hitbtc.private_post_account_transfer({'currency': 'BTC', 'amount': 1.0, 'type': 'exchangeToBank'})
```

**Comment by CopurOnur** [comment]
thanks a lot

**Comment by pmizel** [comment]
Hi Igor, 

what do you think about an aggrigation of both types?

hitbtc.fetch_balance({'type':'trading'})
hitbtc.fetch_balance({'type':'account'})

when can ccxt call twice and aggrigate balances.
and transfer all to trading in the same step.

when you try to create a withdraw then you transfer to account.


when is not transparent you need to implement specials fot hitbtc :-( thats not nice.

**Comment by kroitor** [comment]
@pmizel Hi! Good to hear again from you! Unfortunately, we can't really do multiple requests per call, for rate-limiter reasons, partially explained in this comment: https://github.com/ccxt/ccxt/issues/1175#issuecomment-356831009. Hope it answers your question.
