### ISSUE TITLE
kucoin can't cancel_orders

### ISSUE THREAD

**Issue by qiangxs** [ccxt/ccxt#1217]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by qiangxs** [comment]
kucoin_sell_order=kucoin.create_limit_sell_order ('LTC/USDT', 0.1, 300)
kucoin_cancel_sellorder=kucoin.cancel_order (kucoin_sell_order['id'],'BTC/USDT',{"type": 'SELL'})

THE error is " raise ExchangeError(self.id + ' ' + self.json(response))
ccxt.base.errors.ExchangeError: kucoin {"code":"ERROR","msg":"Order has been was dealed","success":false,"data":null,"timestamp":1515754059945}"

How can i correct it ?
Thx.

**Comment by qiangxs** [comment]
i can not cancel orders.

**Comment by kroitor** [comment]
The order that you are trying to cancel was already filled (closed). You cannot cancel an order, after it was already traded. 

> "msg":"Order has been was dealed"

- You need to handle exceptions properly: https://github.com/ccxt/ccxt/wiki/Manual#error-handling
CCXT tells you that, but you're not caching the exception and do not react correctly.
- See the [examples](https://github.com/ccxt/ccxt/tree/master/examples) as well on how to handle those.

Hope it helps.

**Comment by qiangxs** [comment]
Thanks for your reply. but the order i made has not completed. I don't know  why i can't cancel it. It's different from other exchanges, when canceling  an order, a param is needed besides id and symbol. I don't  know  how to set it even try many times.  

Hoping your  reply. 
Thanks.

**Comment by kroitor** [comment]
1. You are creating an order for LTC/USDT:

```
kucoin_sell_order=kucoin.create_limit_sell_order ('LTC/USDT', 0.1, 300)
```

2. But then you're trying to cancel the order for BTC/USDT, which is a different symbol!

```
kucoin_cancel_sellorder=kucoin.cancel_order (kucoin_sell_order['id'],'BTC/USDT',{"type": 'SELL'})
```

Should be the same LTC/USDT there. Let us know if it helps or not.
