### ISSUE TITLE
BadRequest: ftx {"success":false,"error":"No such subaccount"} /How can i fixde it

### ISSUE THREAD

**Issue by KaitoKuraba** [ccxt/ccxt#12189]
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
~/opt/anaconda3/lib/python3.7/site-packages/ccxt/base/exchange.py in fetch(self, url, method, headers, body)
    612             self.logger.debug("%s %s, Response: %s %s %s", method, url, http_status_code, headers, http_response)
--> 613             response.raise_for_status()
    614 

~/opt/anaconda3/lib/python3.7/site-packages/requests/models.py in raise_for_status(self)
    942         if http_error_msg:
--> 943             raise HTTPError(http_error_msg, response=self)
    944 

HTTPError: 401 Client Error: Unauthorized for url: https://ftx.com/api/orders

During handling of the above exception, another exception occurred:

BadRequest                                Traceback (most recent call last)
<ipython-input-7-599d2cb64dba> in <module>
----> 1 util.execute_order_market('market', 'buy', 1)

~/Desktop/grid_vayamo/src/vayamolabs/ftxcryptogrid.py in execute_order_market(self, types, side, amount)
     81 
     82     def execute_order_market(self, types, side, amount):
---> 83         order = exchange.create_order(self.grid_asset, types, side, amount)
     84         return order
     85 

~/opt/anaconda3/lib/python3.7/site-packages/ccxt/ftx.py in create_order(self, symbol, type, side, amount, price, params)
   1275         else:
   1276             raise InvalidOrder(self.id + ' createOrder() does not support order type ' + type + ', only limit, market, stop, trailingStop, or takeProfit orders are supported')
-> 1277         response = getattr(self, method)(self.extend(request, params))
   1278         #
   1279         # orders

~/opt/anaconda3/lib/python3.7/site-packages/ccxt/base/exchange.py in inner(_self, params, context)
    455                 if context is not None:
    456                     inner_kwargs['context'] = params
--> 457                 return entry(_self, **inner_kwargs)
    458             return inner
    459         to_bind = partialer()

~/opt/anaconda3/lib/python3.7/site-packages/ccxt/base/exchange.py in request(self, path, api, method, params, headers, body, config, context)
    504     def request(self, path, api='public', method='GET', params={}, headers=None, body=None, config={}, context={}):
    505         """Exchange.request is the entry point for all generated methods"""
--> 506         return self.fetch2(path, api, method, params, headers, body, config, context)
    507 
    508     @staticmethod

~/opt/anaconda3/lib/python3.7/site-packages/ccxt/base/exchange.py in fetch2(self, path, api, method, params, headers, body, config, context)
    500         self.lastRestRequestTimestamp = self.milliseconds()
    501         request = self.sign(path, api, method, params, headers, body)
--> 502         return self.fetch(request['url'], request['method'], request['headers'], request['body'])
    503 
    504     def request(self, path, api='public', method='GET', params={}, headers=None, body=None, config={}, context={}):

~/opt/anaconda3/lib/python3.7/site-packages/ccxt/base/exchange.py in fetch(self, url, method, headers, body)
    627         except HTTPError as e:
    628             details = ' '.join([self.id, method, url])
--> 629             self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
    630             self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
    631             raise ExchangeError(details) from e

~/opt/anaconda3/lib/python3.7/site-packages/ccxt/ftx.py in handle_errors(self, code, reason, url, method, headers, body, response, requestHeaders, requestBody)
   2018             error = self.safe_string(response, 'error')
   2019             self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
-> 2020             self.throw_broadly_matched_exception(self.exceptions['broad'], error, feedback)
   2021             raise ExchangeError(feedback)  # unknown message
   2022 

~/opt/anaconda3/lib/python3.7/site-packages/ccxt/base/exchange.py in throw_broadly_matched_exception(self, broad, string, message)
    523         broad_key = self.find_broadly_matched_key(broad, string)
    524         if broad_key is not None:
--> 525             raise broad[broad_key](message)
    526 
    527     def find_broadly_matched_key(self, broad, string):

BadRequest: ftx {"success":false,"error":"No such subaccount"}

**Comment by kroitor** [comment]
Hi!

```
BadRequest: ftx {"success":false,"error":"No such subaccount"}
```

This message says that your subaccount or your API keypair is incorrect. Make sure that your subaccount header is correctly set: https://github.com/ccxt/ccxt/issues/9805#issuecomment-1047712524

Add the error handling as documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#error-handling

You can check the correctness of your keys in verbose mode: https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

I would highly recommend reading the entire Manual from top to bottom:

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://docs.ccxt.com

Hope that answers your question.
