### ISSUE TITLE
how i can get future and margin symbol with load_market in coinex

### ISSUE THREAD

**Issue by hossain93** [ccxt/ccxt#12199]
i get symbols for binance but when i want get symbols margin and future, it don't get any thing
this is my code for binance:

            `import pandas as pd
             import ccxt

             binance = ccxt.binance()
             pairs=pd.DataFrame(binance.load_markets())
             pairs=pairs.T

             pairs.drop(pairs.loc[pairs['margin']!=True].index, inplace=True)
             pairs.drop(pairs.loc[pairs['quote']!='USDT'].index, inplace=True)
             pairs=pairs['symbol']
             pairs=pd.DataFrame(pairs)
             pairs.reset_index(drop=True, inplace=True)
             pd.set_option('display.max_row', pairs.shape[0]+1)
             pairs`

**Comment by kroitor** [comment]
@hossain93 you are using the `binance` instance that defaults to spot markets, use `binanceusdm` for binance USDT-margined futures and swaps, and `binancecoinm` for coin-margined futures and swaps.

**Comment by hossain93** [comment]
> @hossain93 you are using the `binance` instance that defaults to spot markets, use `binanceusdm` for binance USDT-margined futures and swaps, and `binancecoinm` for coin-margined futures and swaps.

I want symbols for coinex
Binance is for example

**Comment by kroitor** [comment]
@hossain93 CCXT does not support the CoinEx futures symbols yet, but we will add that part as soon as we can in one of the coming versions.

**Comment by Behrouz-m** [comment]
> 

hi. have you implemented it yet?

**Comment by Behrouz-m** [comment]
> @hossain93 CCXT does not support the CoinEx futures symbols yet, but we will add that part as soon as we can in one of the coming versions.

hi. have you implemented it yet?
