### ISSUE TITLE
fetchTickers() properties undefined.

### ISSUE THREAD

**Issue by FritzH321** [ccxt/ccxt#1219]
- OS: Windows 7
- Programming Language version: Javascript (Node version 8.5.0 & 9)
- CCXT version: 1.10.668 
- Exchange: Binance
- Method: fetchTickers()

The fetchTickers() function returns numerous undefined properties. I've encountered this problem in the new version. Previous local version on my machine was 1.10.561

Result (v1.10.668):
`  'RLC/BNB': 
   { symbol: 'RLC/BNB',
     timestamp: 1515767474528,
     datetime: '2018-01-12T14:31:14.528Z',
     high: undefined,
     low: undefined,
     bid: 0.18003,
     ask: 0.18507,
     vwap: undefined,
     open: undefined,
     close: undefined,
     first: undefined,
     last: undefined,
     change: undefined,
     percentage: undefined,
     average: undefined,
     baseVolume: undefined,
     quoteVolume: undefined,
     info: 
      { symbol: 'RLCBNB',
        bidPrice: '0.18003000',
        bidQty: '2063.24000000',
        askPrice: '0.18507000',
        askQty: '36.23000000' } } }`

Expected result (1.10.561):
` 'RLC/BNB': 
   { symbol: 'RLC/BNB',
     timestamp: 1515767932973,
     datetime: '2018-01-12T14:38:52.973Z',
     high: 99,
     low: 0.1,
     bid: 0.18037,
     ask: 0.185,
     vwap: 0.26365468,
     open: 0.9,
     close: 0,
     first: undefined,
     last: 0.18034,
     change: -79.962,
     percentage: undefined,
     average: undefined,
     baseVolume: 343073.12,
     quoteVolume: 90452.8352876,
     info: 
      { symbol: 'RLCBNB',
        priceChange: '-0.71966000',
        priceChangePercent: '-79.962',
        weightedAvgPrice: '0.26365468',
        prevClosePrice: '0.00000000',
        lastPrice: '0.18034000',
        lastQty: '393.73000000',
        bidPrice: '0.18037000',
        bidQty: '2072.65000000',
        askPrice: '0.18500000',
        askQty: '10.44000000',
        openPrice: '0.90000000',
        highPrice: '99.00000000',
        lowPrice: '0.10000000',
        volume: '343073.12000000',
        quoteVolume: '90452.83528760',
        openTime: 1515681532973,
        closeTime: 1515767932973,
        firstId: 0,
        lastId: 4892,
        count: 4893 } } }`

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/issues/1177
