### ISSUE TITLE
Kucoin fetchMyTrades doesn't work

### ISSUE THREAD

**Issue by ludekvodicka** [ccxt/ccxt#12201]
- OS: Windows
- Programming Language version: NodeJS
- CCXT version: 1.75.4

Hello, I'm trying to download order history from Kucoin, but even after searching here in issues, I'm not able to do that.

When I run the command without any `option`,  the result is an empty array. I'm trying to download the history right before the order/trade happened but still without success.

I also found a new `fetchMyTradesMethod` option, but when I use it, I'm receiving `BadRequest: kucoin The interface has been deprecated`.

Can I ask for help, please?

```
  let kucoinMain = new ccxt.kucoin({
    name: 'KucoinMain',
    apiKey: '',
    secret: '',
    password : '',
    enableRateLimit: true,
    //verbose : true,
    //options: { fetchMyTradesMethod: 'private_get_hist_orders' }
  });

  let res = await kucoinMain.fetchMyTrades('LITH/USDT', new Date(2021, 9, 16, 0, 0, 0).getTime());
  console.log(res);
```

```
[]
```

Thanks

**Comment by ludekvodicka** [comment]
Few more info:

- `fetchClosedOrders` also doesn't work on Kucoin. but `fetchBalance` correctly displays current assets.

- The same code works ok for me with Binance/GateIo/FTX

**Comment by ludekvodicka** [comment]
![chrome_2022-03-07_14-04-27](https://user-images.githubusercontent.com/3900551/157039820-f7c996fd-e99e-4fb6-b3ee-6928197e2c20.png)

**Comment by carlosmiei** [comment]
@ludekvodicka Can you please enable the verbose mode and paste here the full request-response?

**Comment by ludekvodicka** [comment]
Sure, here it is: https://www.dropbox.com/s/sfabhqj3xlnt3m4/log.txt?dl=0

(it's 1.5MB and pastebin or github comment rejected it).

**Comment by ludekvodicka** [comment]
I tested it with the following fragment now:

```
  let kucoinMain = new ccxt.kucoin({
    name: 'KucoinMain',
    apiKey: 'x',
    secret: 'x',
    password : 'x',
    enableRateLimit: true,
    //verbose : true,
    //options: { fetchMyTradesMethod: 'private_get_hist_orders' }
  });

  let resOrders = await kucoinMain.fetchClosedOrders('LITH/USDT', 1631743200);
  console.log(resOrders);
```

and the same result

**Comment by ludekvodicka** [comment]
But you're right, that in there request is wrongly used current timestamp. This is current output:

```
fetch Request:
 kucoin GET https://openapi-v2.kucoin.com/api/v1/orders?status=done&symbol=LITH-USDT&startAt=1631743200 
RequestHeaders:
 {
  'KC-API-KEY-VERSION': '2',
  'KC-API-KEY': 'xxx',
  'KC-API-TIMESTAMP': '1646756176884',
  'KC-API-PASSPHRASE': 'xx',
  'KC-API-SIGN': 'xxx'
} 
RequestBody:
 undefined 

handleRestResponse:
 kucoin GET https://openapi-v2.kucoin.com/api/v1/orders?status=done&symbol=LITH-USDT&startAt=1631743200 200 OK 
ResponseHeaders:
 {
  'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '6e8cdfda0aa5f9de-PRG',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json',
  Date: 'Tue, 08 Mar 2022 16:16:17 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Expires: '0',
  Server: 'cloudflare',
  'Strict-Transport-Security': 'max-age=9800; includeSubDomains; preload',
  'Transfer-Encoding': 'chunked',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'X-Xss-Protection': '1; mode=block'
} 
ResponseBody:
 {"code":"200000","data":{"currentPage":1,"pageSize":50,"totalNum":0,"totalPage":0,"items":[]}} 

[]
```


I think there is some buge inside the kucoin timestamp handling

**Comment by carlosmiei** [comment]
@ludekvodicka Actually everything seems to be in place, you passed 1631743200 (Wed Sep 15 2021) and that is the timestamp in the request too, so probably something wrong with Kucoin's API engine or they allow only for a "since" less than a few months for example. Have you tried to contact them?

**Comment by ludekvodicka** [comment]
Oh, sorry, my bad. Not sure why I saw 163... and 161... :-). 

I didn't communicate with them yet. I will try the newest orders but I think it's the same. I will let you know.

**Comment by carlosmiei** [comment]
@ludekvodicka  Thanks!
