### ISSUE TITLE
get all position Liquidation value in hedge mode

### ISSUE THREAD

**Issue by boorsekala** [ccxt/ccxt#12208]
hi special thanks for nice project.
i used in binance php and worked ok in fetch all  active positions.
im using Hedge mode.
then when i used:
$trades = $exchange->fetch_account_positions();
in result  Liquid value is empty or null
the array key of liquidationPrice  is  empty.
how can i fetch each position in hedge mode ?

**Comment by ttodua** [comment]
you should use `$exchange->fetch_positions( [$symbol1, $symbol2])` to fetch positions and inside position item, there is `liquidationPrice` property. 
But you havent provided the required information to get help https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help and in next cases, please provide it.
If you have any issues with CCXT, let us know
