### ISSUE TITLE
It seems that the program cannot place an order.

### ISSUE THREAD

**Issue by qwe231cvb** [ccxt/ccxt#12200]
It looks like the program exits as soon as the order is placed.
The code as follows:
```
import ccxt
import time
from pprint import pprint
ftx = ccxt.ftx({
    'apiKey': 
    'secret': 
})
total_profit = 0
total_total_profit = 0
first_datetime = 0
a = True
while a:
    try:
        usd_balance = ftx.fetch_balance()['USD']['free']
        matic_balance = ftx.fetch_balance()['MATIC']['free']
        matic_price = ftx.fetch_ticker("MATIC/USD")['bid']
        print("usd_balance：", usd_balance, "    matic_balance：", matic_balance, "    matic_price：", matic_price)
        matic_order_amount = 10/matic_price
        print("matic_order_amount：", matic_order_amount)
        if total_profit >= 60:
            matic_order_amount = 10 / matic_price + total_profit / 21 / matic_price
            total_profit = 0
        total_matic_order_amount = 0
        total_order_price = 0
        buy_cost = 0
        profit = 0
        x = True
        while x:
            print("aaa")
            create_order = ftx.create_order('MATIC/USD', 'market', 'buy', matic_order_amount)
            print("bbb")
            time.sleep(10)
    except:
        print("timeout")
```

Its output is as follows:
usd_balance： 234.51777441     matic_balance： 0.0     matic_price： 1.486916
matic_order_amount： 6.725329473890926
aaa
timeout
usd_balance： 234.51777441     matic_balance： 0.0     matic_price： 1.486788
matic_order_amount： 6.725908468456835
aaa
timeout
usd_balance： 234.51777441     matic_balance： 0.0     matic_price： 1.486705
matic_order_amount： 6.726283963530088
aaa
timeout
usd_balance： 234.51777441     matic_balance： 0.0     matic_price： 1.486631
matic_order_amount： 6.726618777625382
aaa
timeout

Why?How to resolve?

**Comment by kroitor** [comment]
Paste your complete verbose output for this snippet: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.ftx({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
markets = exchange.load_markets()
exchange.verbose = True
balance = exchange.fetch_balance()
print('-----------------------------------------------------')
pprint(balance)
```

**Comment by qwe231cvb** [comment]
Its output is as follows:

CCXT Version: 1.75.4

fetch Request: ftx GET https://ftx.com/api/wallet/balances RequestHeaders: {'FTX                                             -KEY': 'tVPw-gp06559......', 'FTX-TS': '1646554749629', 'F                                             TX-SIGN': '2484fb7c23723f765ab9c52896666e53fcb9b223fbd22a8f059905d14e553e4c', 'U                                             ser-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate'} Reques                                             tBody: None

fetch Response: ftx GET https://ftx.com/api/wallet/balances 200 ResponseHeaders:                                              {'Date': 'Sun, 06 Mar 2022 08:19:09 GMT', 'Content-Type': 'application/json', '                                             Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encod                                             ing, Accept-Encoding, Origin', 'Cache-Control': 'private, max-age=0, no-cache',                                              'account-id': '28197837', 'ETag': 'W/"9f6adac13390f39f284e94a0ffe636fb"', 'Conte                                             nt-Encoding': 'gzip', 'Strict-Transport-Security': 'max-age=31536000; includeSub                                             Domains; preload', 'X-Frame-Options': 'sameorigin', 'X-Content-Type-Options': 'n                                             osniff', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': 'block-                                             all-mixed-content', 'X-Cache-Status': 'MISS', 'CF-Cache-Status': 'MISS', 'Expect                                             -CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/bea                                             con/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '6e79aa313aee4242-AMS', 'alt-                                             svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'} ResponseBody: {"success":tr                                             ue,"result":[{"coin":"LTC","total":0.0496998,"free":0.0496998,"availableWithoutB                                             orrow":0.0496998,"usdValue":5.141374826073403,"spotBorrow":0.0},{"coin":"USD","t                                             otal":234.51777441,"free":234.51777441,"availableWithoutBorrow":234.51777441,"us                                             dValue":234.51777441206966,"spotBorrow":0.0},{"coin":"MATIC","total":0.0,"free":                                             0.0,"availableWithoutBorrow":0.0,"usdValue":0.0,"spotBorrow":0.0},{"coin":"ETH",                                             "total":0.0,"free":0.0,"availableWithoutBorrow":0.0,"usdValue":0.0,"spotBorrow":                                             0.0},{"coin":"USDT","total":1e-8,"free":1e-8,"availableWithoutBorrow":1e-8,"usdV                                             alue":1.0106713369332436e-8,"spotBorrow":0.0},{"coin":"BTC","total":0.0,"free":0                                             .0,"availableWithoutBorrow":0.0,"usdValue":0.00015730062433792,"spotBorrow":0.0}                                             ,{"coin":"FTM","total":0.0,"free":0.0,"availableWithoutBorrow":0.0,"usdValue":0.                                             0,"spotBorrow":0.0},{"coin":"KIN","total":0.0,"free":0.0,"availableWithoutBorrow                                             ":0.0,"usdValue":0.0,"spotBorrow":0.0},{"coin":"AVAX","total":0.0,"free":0.0,"av                                             ailableWithoutBorrow":0.0,"usdValue":0.0,"spotBorrow":0.0},{"coin":"STEP","total                                             ":0.0,"free":0.0,"availableWithoutBorrow":0.0,"usdValue":0.0,"spotBorrow":0.0},{                                             "coin":"DOGE","total":0.0,"free":0.0,"availableWithoutBorrow":0.0,"usdValue":0.0                                             ,"spotBorrow":0.0},{"coin":"SOL","total":0.0,"free":0.0,"availableWithoutBorrow"                                             :0.0,"usdValue":0.0,"spotBorrow":0.0},{"coin":"FTT","total":0.0,"free":0.0,"avai                                             lableWithoutBorrow":0.0,"usdValue":0.0,"spotBorrow":0.0},{"coin":"SNX","total":0                                             .0,"free":0.0,"availableWithoutBorrow":0.0,"usdValue":0.0,"spotBorrow":0.0},{"co                                             in":"GRT","total":0.0,"free":0.0,"availableWithoutBorrow":0.0,"usdValue":0.0,"sp                                             otBorrow":0.0},{"coin":"SRM","total":0.0,"free":0.0,"availableWithoutBorrow":0.0                                             ,"usdValue":0.0,"spotBorrow":0.0},{"coin":"AXS","total":0.0,"free":0.0,"availabl                                             eWithoutBorrow":0.0,"usdValue":0.0,"spotBorrow":0.0},{"coin":"TRU","total":0.0,"                                             free":0.0,"availableWithoutBorrow":0.0,"usdValue":1.54896861623097e-9,"spotBorro                                             w":0.0},{"coin":"USDC","total":0.0,"free":0.0,"availableWithoutBorrow":0.0,"usdV                                             alue":0.0,"spotBorrow":0.0},{"coin":"COPE","total":0.0,"free":0.0,"availableWith                                             outBorrow":0.0,"usdValue":0.0,"spotBorrow":0.0},{"coin":"TRX","total":3e-6,"free                                             ":3e-6,"availableWithoutBorrow":3e-6,"usdValue":1.8102402e-7,"spotBorrow":0.0}]}
-----------------------------------------------------
{'AVAX': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'AXS': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'BTC': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'COPE': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'DOGE': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'ETH': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'FTM': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'FTT': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'GRT': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'KIN': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'LTC': {'free': 0.0496998, 'total': 0.0496998, 'used': 0.0},
 'MATIC': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'SNX': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'SOL': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'SRM': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'STEP': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'TRU': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'TRX': {'free': 3e-06, 'total': 3e-06, 'used': 0.0},
 'USD': {'free': 234.51777441, 'total': 234.51777441, 'used': 0.0},
 'USDC': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'USDT': {'free': 1e-08, 'total': 1e-08, 'used': 0.0},
 'free': {'AVAX': 0.0,
          'AXS': 0.0,
          'BTC': 0.0,
          'COPE': 0.0,
          'DOGE': 0.0,
          'ETH': 0.0,
          'FTM': 0.0,
          'FTT': 0.0,
          'GRT': 0.0,
          'KIN': 0.0,
          'LTC': 0.0496998,
          'MATIC': 0.0,
          'SNX': 0.0,
          'SOL': 0.0,
          'SRM': 0.0,
          'STEP': 0.0,
          'TRU': 0.0,
          'TRX': 3e-06,
          'USD': 234.51777441,
          'USDC': 0.0,
          'USDT': 1e-08},
 'info': {'result': [{'availableWithoutBorrow': '0.0496998',
                      'coin': 'LTC',
                      'free': '0.0496998',
                      'spotBorrow': '0.0',
                      'total': '0.0496998',
                      'usdValue': '5.141374826073403'},
                     {'availableWithoutBorrow': '234.51777441',
                      'coin': 'USD',
                      'free': '234.51777441',
                      'spotBorrow': '0.0',
                      'total': '234.51777441',
                      'usdValue': '234.51777441206966'},
                     {'availableWithoutBorrow': '0.0',
                      'coin': 'MATIC',
                      'free': '0.0',
                      'spotBorrow': '0.0',
                      'total': '0.0',
                      'usdValue': '0.0'},
                     {'availableWithoutBorrow': '0.0',
                      'coin': 'ETH',
                      'free': '0.0',
                      'spotBorrow': '0.0',
                      'total': '0.0',
                      'usdValue': '0.0'},
                     {'availableWithoutBorrow': '1e-8',
                      'coin': 'USDT',
                      'free': '1e-8',
                      'spotBorrow': '0.0',
                      'total': '1e-8',
                      'usdValue': '1.0106713369332436e-8'},
                     {'availableWithoutBorrow': '0.0',
                      'coin': 'BTC',
                      'free': '0.0',
                      'spotBorrow': '0.0',
                      'total': '0.0',
                      'usdValue': '0.00015730062433792'},
                     {'availableWithoutBorrow': '0.0',
                      'coin': 'FTM',
                      'free': '0.0',
                      'spotBorrow': '0.0',
                      'total': '0.0',
                      'usdValue': '0.0'},
                     {'availableWithoutBorrow': '0.0',
                      'coin': 'KIN',
                      'free': '0.0',
                      'spotBorrow': '0.0',
                      'total': '0.0',
                      'usdValue': '0.0'},
                     {'availableWithoutBorrow': '0.0',
                      'coin': 'AVAX',
                      'free': '0.0',
                      'spotBorrow': '0.0',
                      'total': '0.0',
                      'usdValue': '0.0'},
                     {'availableWithoutBorrow': '0.0',
                      'coin': 'STEP',
                      'free': '0.0',
                      'spotBorrow': '0.0',
                      'total': '0.0',
                      'usdValue': '0.0'},
                     {'availableWithoutBorrow': '0.0',
                      'coin': 'DOGE',
                      'free': '0.0',
                      'spotBorrow': '0.0',
                      'total': '0.0',
                      'usdValue': '0.0'},
                     {'availableWithoutBorrow': '0.0',
                      'coin': 'SOL',
                      'free': '0.0',
                      'spotBorrow': '0.0',
                      'total': '0.0',
                      'usdValue': '0.0'},
                     {'availableWithoutBorrow': '0.0',
                      'coin': 'FTT',
                      'free': '0.0',
                      'spotBorrow': '0.0',
                      'total': '0.0',
                      'usdValue': '0.0'},
                     {'availableWithoutBorrow': '0.0',
                      'coin': 'SNX',
                      'free': '0.0',
                      'spotBorrow': '0.0',
                      'total': '0.0',
                      'usdValue': '0.0'},
                     {'availableWithoutBorrow': '0.0',
                      'coin': 'GRT',
                      'free': '0.0',
                      'spotBorrow': '0.0',
                      'total': '0.0',
                      'usdValue': '0.0'},
                     {'availableWithoutBorrow': '0.0',
                      'coin': 'SRM',
                      'free': '0.0',
                      'spotBorrow': '0.0',
                      'total': '0.0',
                      'usdValue': '0.0'},
                     {'availableWithoutBorrow': '0.0',
                      'coin': 'AXS',
                      'free': '0.0',
                      'spotBorrow': '0.0',
                      'total': '0.0',
                      'usdValue': '0.0'},
                     {'availableWithoutBorrow': '0.0',
                      'coin': 'TRU',
                      'free': '0.0',
                      'spotBorrow': '0.0',
                      'total': '0.0',
                      'usdValue': '1.54896861623097e-9'},
                     {'availableWithoutBorrow': '0.0',
                      'coin': 'USDC',
                      'free': '0.0',
                      'spotBorrow': '0.0',
                      'total': '0.0',
                      'usdValue': '0.0'},
                     {'availableWithoutBorrow': '0.0',
                      'coin': 'COPE',
                      'free': '0.0',
                      'spotBorrow': '0.0',
                      'total': '0.0',
                      'usdValue': '0.0'},
                     {'availableWithoutBorrow': '3e-6',
                      'coin': 'TRX',
                      'free': '3e-6',
                      'spotBorrow': '0.0',
                      'total': '3e-6',
                      'usdValue': '1.8102402e-7'}],
          'success': True},
 'total': {'AVAX': 0.0,
           'AXS': 0.0,
           'BTC': 0.0,
           'COPE': 0.0,
           'DOGE': 0.0,
           'ETH': 0.0,
           'FTM': 0.0,
           'FTT': 0.0,
           'GRT': 0.0,
           'KIN': 0.0,
           'LTC': 0.0496998,
           'MATIC': 0.0,
           'SNX': 0.0,
           'SOL': 0.0,
           'SRM': 0.0,
           'STEP': 0.0,
           'TRU': 0.0,
           'TRX': 3e-06,
           'USD': 234.51777441,
           'USDC': 0.0,
           'USDT': 1e-08},
 'used': {'AVAX': 0.0,
          'AXS': 0.0,
          'BTC': 0.0,
          'COPE': 0.0,
          'DOGE': 0.0,
          'ETH': 0.0,
          'FTM': 0.0,
          'FTT': 0.0,
          'GRT': 0.0,
          'KIN': 0.0,
          'LTC': 0.0,
          'MATIC': 0.0,
          'SNX': 0.0,
          'SOL': 0.0,
          'SRM': 0.0,
          'STEP': 0.0,
          'TRU': 0.0,
          'TRX': 0.0,
          'USD': 0.0,
          'USDC': 0.0,
          'USDT': 0.0}}

**Comment by kroitor** [comment]
@qwe231cvb looks like that is working normally, now try placing the order:

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.ftx({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
markets = exchange.load_markets()
exchange.verbose = True
order = exchange.create_order('MATIC/USD', 'market', 'buy', 10)
print('---------------------------------------------------')
pprint(order)
```

Please, use GitHub markdown when pasting your code and your verbose output as text as well: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by qwe231cvb** [comment]
> @qwe231cvb looks like that is working normally, now try placing the order:
> 
> ```python
> import ccxt
> from pprint import pprint
> print('CCXT Version:', ccxt.__version__)
> exchange = ccxt.ftx({
>     'apiKey': 'YOUR_API_KEY',
>     'secret': 'YOUR_SECRET',
> })
> markets = exchange.load_markets()
> exchange.verbose = True
> order = exchange.create_order('MATIC/USD', 'market', 'buy', 10)
> print('---------------------------------------------------')
> pprint(order)
> ```
> 
> Please, use GitHub markdown when pasting your code and your verbose output as text as well: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by qwe231cvb** [comment]
If it is correct to change to this, the code is as follows:
```
matic_price = exchange.fetch_ticker("MATIC/USD")['bid']
matic_order_amount = 10/matic_price
order = exchange.create_order('MATIC/USD', 'market', 'buy', 10)
```

But if it is changed to this, it is wrong, the code is as follows:
```
matic_price = exchange.fetch_ticker("MATIC/USD")['bid']
matic_order_amount = 10/matic_price
order = exchange.create_order('MATIC/USD', 'market', 'buy', matic_order_amount)
```

The problem is with 'matic_order_amount',
So it may be caused by the line 'matic_price = exchange.fetch_ticker("MATIC/USD")['bid']'.
So how to get the price right?

**Comment by kroitor** [comment]
> So how to get the price right?

Your order must satisfy the exchange precision and limits: https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits (must be no less than 10 MATIC to buy or sell)

**Comment by qwe231cvb** [comment]
I have another question,
When I close the SSH window, the program runs on the VPS after a while.
Then the next time I open the SSH window, I want to view the print record, but I can't see the print record at this time.

How can I view the print record at any time?

**Comment by kroitor** [comment]
> I have another question, When I close the SSH window, the program runs on the VPS after a while. Then the next time I open the SSH window, I want to view the print record, but I can't see the print record at this time.
> 
> How can I view the print record at any time?

@qwe231cvb use screen or tmux to keep it working while you're not connected: 

- https://www.gnu.org/software/screen/
- https://github.com/tmux/tmux/wiki

**Comment by qwe231cvb** [comment]
> use screen or tmux to keep it working while you're not connected:
> 
> * https://www.gnu.org/software/screen/
> * https://github.com/tmux/tmux/wiki

Will the running of the screen program generate a lot of cache garbage?

If so, does it need to be cleaned regularly?

I only refer to the cache garbage generated by the running of the screen program, not the cache garbage generated by calling ccxt.
