### ISSUE TITLE
Update stoploss for running contract

### ISSUE THREAD

**Issue by StartingProgramming** [ccxt/ccxt#12212]
Hello,

I do a contract order and open a position with a stoploss. Now I want to update my stoploss in certain cases.
Can someone tell me how to do that in python?

Thanks!

Best regards

**Comment by samgermain** [comment]
What exchange are you using? Some exchanges have the method `editOrder`, but it might not work for stoploss orders on your exchange, you might need to use `cancelOrder` to cancel your stoploss, and then create a new stoploss order

**Comment by ttodua** [comment]
The above answer by @samgermain was probably sufficient in such case (where there were no more details provided). If anyone has any further issues with CCXT, let us know. Also, provide more specific details as mentioned above.

**Comment by ttodua** [comment]
I would just add, that some exchanges might need to add `{stop: true}` in params, to refer the order type to stop-kind orders.
