### ISSUE TITLE
fetchorderstatus not working

### ISSUE THREAD

**Issue by ankitsmart63** [ccxt/ccxt#12226]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```
console.log (wazirx.id, await wazirx.fetchOrderStatus('2536405467'))

its giving error

C:\Users\Dell\node_modules\ccxt\js\base\Exchange.js:922
        throw new NotSupported (this.id + ' fetchOrder not supported yet');
              ^

NotSupported: wazirx fetchOrder not supported yet
    at wazirx.fetchOrder (C:\Users\Dell\node_modules\ccxt\js\base\Exchange.js:922:15)
    at wazirx.fetchOrderStatus (C:\Users\Dell\node_modules\ccxt\js\base\Exchange.js:1000:34)
    at C:\Users\Dell\Desktop\PupzirxBot\ccxtbot.js:13:42
    at Object.<anonymous> (C:\Users\Dell\Desktop\PupzirxBot\ccxtbot.js:59:4)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  constructor: [class NotSupported extends ExchangeError]
}
```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

**Comment by carlosmiei** [comment]
Hello @ankitsmart63 

As you can see [here](https://github.com/ccxt/ccxt/blob/master/js%2Fwazirx.js), fetchOrderStatus is not a method supported so that's why you're getting that exception.

For this particular exchange these order fetching methods are supported:
- fetchOpenOrders
- fetchOrders 

Probably one of them suits your needs 🙂

**Comment by ankitsmart63** [comment]
But fetchopenorders and fetchorders give response of all open orders,i only
want one of them at a time with the specified orderid,Although i can grab
them from inside of that data but i have to go deeper in it and write more
codes,

It would have been a single line of code if fetchorderstatus would be
supported.

I am using ccxt only because it shortens the code,otherwise i can get those
directly from the exchange with same amount of code only then why will i
use ccxt.

I hope you understand or if there is another way in it to directly get
status of an order then kindly let me know
