### ISSUE TITLE
any chance to enable bl3p LTCEUR market?

### ISSUE THREAD

**Issue by agroszer** [ccxt/ccxt#1224]

**Comment by kroitor** [comment]
Last time I checked, it didn't work... have they enabled it already? Will check again and get back to you soon.

**Comment by agroszer** [comment]
public seems to work:

https://api.bl3p.eu/1/LTCEUR/ticker

https://api.bl3p.eu/1/LTCEUR/orderbook

https://api.bl3p.eu/1/LTCEUR/trades
