### ISSUE TITLE
Issue with updating Leverage in Cross mode, gateio 

### ISSUE THREAD

**Issue by fahad-here** [ccxt/ccxt#12257]
I am trying to update the leverage in cross mode, but it looks like the cross leverage stays the same.
Update the isolated leverage works fine though.

```
const exchange = new ccxt['gateio']({
  apiKey,
  secret,
});
exchange.options.defaultType = 'swap';
await exchange.setLeverage(0, sybmol, { cross_leverage_limit: 5 })
```

It looks like you have to include the 'cross_leverage_limit' in the query params. 

```
request['query'] = {
    'cross_leverage_limit': params['cross_leverage_limit'].toString (),
};
```

**Comment by kroitor** [comment]
@fahad-here please, paste your verbose output:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```JavaScript
const exchange = new ccxt['gateio']({
  apiKey,
  secret,
  options: { defaultType: 'swap' },
});
await exchange.loadMarkets()
exchange.verbose = true
await exchange.setLeverage(0, symbol, { cross_leverage_limit: 5 })
```

**Comment by samgermain** [comment]
@fahad-here Thanks for telling us!

This is a bug that will be fixed in https://github.com/ccxt/ccxt/pull/12354

Also, https://github.com/ccxt/ccxt/pull/12354 , gives the option of just setting `params` to `marginType: 'cross'`, and then setting the other parameters normally

e.g.

```
exchange.setLeverage(10, 'XRP/USDT:USDT', {'marginType': 'cross'}
```
