### ISSUE TITLE
[Python] Is ccxt type stub provided?

### ISSUE THREAD

**Issue by mirumirumi** [ccxt/ccxt#12255]
I have already looked for typeshed and PyPI type stubs. And issues in this repository.
But I couldn't find anything suitable.

Specifically, I want to address the issue that Pylance warns about: 
![2022-03-09_21h59_02](https://user-images.githubusercontent.com/88871226/157446501-72cd04ba-2482-445a-8db5-b250954547a4.png)

- OS: WSL2 (on Windows 11)
- Programming Language version: Python 3.9
- CCXT version: ccxt-1.75.39

I would like to thank all who participate in this repository!

**Comment by gshpychka** [comment]
There are multiple type checker errors all over ccxt code, unfortunately, and I don't think they can be solved without writing proper type hints.

**Comment by frosty00** [comment]
we've since added type hints in python and are continuing to develop it!
