### ISSUE TITLE
Kucoin watch order book for testnet not working

### ISSUE THREAD

**Issue by leastchaos** [ccxt/ccxt#12252]
Kucoin testnet not working for watch order book.
mainnet is working normal

- OS: linux
- Programming Language version: python 3.10
- CCXT version:

```
import asyncio
import ccxtpro

print(ccxtpro.__version__)
symbol = 'BTC/USDT'
exchange: ccxtpro.Exchange = getattr(ccxtpro, 'kucoin')({
    'enableRateLimit': True,
    'apiKey': 'testnet',
    'secret': 'testnet',
    'password': 'testnet',
})
exchange.verbose=True
exchange.set_sandbox_mode(True)

async def main():
    while True:
        result = await exchange.watch_order_book(symbol)
        print(result)
        
    await exchange.close()

asyncio.run(main())

```
[output.log](https://github.com/ccxt/ccxt/files/8213860/output.log)

```

**Comment by carlosmiei** [comment]
Hello @leastchaos 
I've checked and everything is being handled correctly on our end so I suspect it might be something on Kucoin's side.

Have you tried to reach their support?

**Comment by leastchaos** [comment]
I reach out to their support last week but there was no reply.
