### ISSUE TITLE
Clarifying Understanding of `baseVolume` and `quoteVolume`

### ISSUE THREAD

**Issue by mitchmindtree** [ccxt/ccxt#1229]
I've been reading through the manual and just wanted to check that my understanding of base/quote volumes is correct!

In a given market FOO/BAR, `baseVolume` indicates the total amount of FOO that has been bought and sold in this market in the past 24hrs, while `quoteVolume` is the total amount of BAR that has been bought and sold in this market in the past 24hrs. Is this correct?

If so, I have a follow-up question: Is it possible to get the volumes for the two different directions for a single market using ccxt? E.g. is it possible to distinguish between the amount of FOO that was bought  and  the amount of FOO that has been sold (rather than just the sum total of both)?

Thanks for your time and awesome work!

**Comment by kroitor** [comment]
> In a given market FOO/BAR, baseVolume indicates the total amount of FOO that has been bought and sold in this market in the past 24hrs, while quoteVolume is the total amount of BAR that has been bought and sold in this market in the past 24hrs. Is this correct?

Exactly!

> f so, I have a follow-up question: Is it possible to get the volumes for the two different directions for a single market using ccxt? E.g. is it possible to distinguish between the amount of FOO that was bought and the amount of FOO that has been sold (rather than just the sum total of both)?

No, unfortunately, most of exchanges will not return that info segregated. And you cannot deduce exact values of one from another. Most often exchanges will return just the baseVolume or just the quoteVolume.

One more note: when you buy FOO on the FOO/BAR market, you are buying it for BAR, right?  So, when you buy FOO for BAR, that means, you are actually selling BAR for FOO.

- buy FOO/BAR = sell BAR/FOO
- sell FOO/BAR = buy BAR/FOO

There's also a volume-weighed average price (vwap, present with some exchanges) – that is the average prices for those baseVolume and quoteVolume, from there:

- cost = amount * price
- equivalently quoteVolume (total 24h traded quote cost) = baseVolume * vwap (total 24h base cost * average price over last 24h)

Let me know if this answers your question.

**Comment by mitchmindtree** [comment]
Perfect, thank you for such a quick and detailed response!
