### ISSUE TITLE
Failed to get adlQuantile (issue #9811)

### ISSUE THREAD

**Issue by omalisson** [ccxt/ccxt#12318]
Hi!

I need to retrieve the information of my open positions as my app issues a new entry signal, but the only way I found it in the ccxt api is via "adlQuantile".

When trying to run my code I get the following error:
**ccxt.base.errors.BadSymbol: binanceusdm {"code":-1121,"msg":"Invalid symbol."}**

I've tried several symbol combinations but all without success.

> Code:
```
response = exchange.dapiPrivate_get_adlquantile({'symbol': 'BTC/USDT'})
print(response)
```

> CCXT Version: **1.75.65**
> Python Version: **3.8.2**

Note: I kept it here as 'BTC/USDT' but as I said before, I've already tried some combinations I've seen in use in ccxt like 'BTCUSDT', 'BTC-PERP' among others...

**Comment by kroitor** [comment]
Hi!

I would highly recommend reading the entire Manual from top to bottom, it will save your time:

- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/
- https://docs.ccxt.com

The `dapiPrivate_get_adlquantile` is an implicit method:

- https://docs.ccxt.com/en/latest/manual.html#implicit-api
- https://binance-docs.github.io/apidocs/delivery/en/#position-adl-quantile-estimation-user_data

You have to use exchange-specific market ids for implicit methods:

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

The correct code is:

```Python
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
markets = exchange.load_markets()
# exchange.verbose = True  # uncomment for debugging purposes

print('-------------------------------------------')

response = exchange.fapiPrivate_get_adlquantile({'symbol': 'BTCUSDT'})  # market id here

pprint(response)

print('-------------------------------------------')

response = exchange.dapiPrivate_get_adlquantile({'symbol': 'BTCUSD_220325'})  # market id here

pprint(response)
```

**P.S. you must have a corresponding position for it to work.**
