### ISSUE TITLE
kucoin precision

### ISSUE THREAD

**Issue by wannesdemaeght** [ccxt/ccxt#1232]
After fiddling around some more, 

I found a fault:

```
(async () => {
	let kucoin = new ccxt.kucoin()
    let pairs = await kucoin.fetchMarkets ()
    for (let i in pairs){
		console.log (pairs[i].symbol, pairs[i].precision)
	}
}) ()
```

This lists all kucoin pairs and the precision.

Output:

> KCS/BTC { amount: 8, price: 8 }
> KCS/ETH { amount: 8, price: 8 }
> RPX/NEO { amount: 8, price: 8 }
> KCS/USDT { amount: 8, price: 8 }
...
> PAY/ETH { amount: 8, price: 8 }
> CVC/BTC { amount: 8, price: 8 }
> CVC/ETH { amount: 8, price: 8 }
> PAY/BTC { amount: 8, price: 8 }
> SNT/BTC { amount: 8, price: 8 }
> SNT/ETH { amount: 8, price: 8 }
> CFD/BTC { amount: 8, price: 8 }
> BHC/BTC { amount: 8, price: 8 }

This is wrong, the amount is capped for some coins.
I really don't have a clue which, but it's in their API.

For instance: both LTC and ETH amounts are capped at 6 digits.

**Comment by kroitor** [comment]
Thanks for the info, but we are aware of this, and this is documented as a work in progress. Your contributions would be appreciated.

Does this work for you?

```JavaScript
(async () => {
    let kucoin = new ccxt.kucoin()
    await kucoin.loadMarkets ()
    Object.keys (kucoin.currencies).forEach (code => 
        console.log (code, kucoin.currencies[code].precision))
}) ()
```

**Comment by wannesdemaeght** [comment]
yes, the .currencies gives me the correct info.

question though: 
Will this work for all exchanges? 
I am trying to write a for loop, getting all the info from all the exchanges I am interested in.
A different call to only kucoin would ofcourse not work in that loop.

Also,
I only need precision info when posting an order.
Does ccxt automagically convert a number to the correct precision, or do I need to use .toFixed?

**Comment by kroitor** [comment]
> Will this work for all exchanges?

As I said, it is a work in progress, so this will work for all exchanges, but it may fail to with this or that exchange, we are still adding that info.

> A different call to only kucoin would ofcourse not work in that loop.

If you want to make money, you will have to be flexible, really.

> Does ccxt automagically convert a number to the correct precision, or do I need to use .toFixed?

The goal is to convert them automagically, and for major exchanges this should work, but, again, this is a work in progress, so some info might still be missing. I would not recommend to use .toFixed, though, because you can get all sorts of unexpected rounding with it. For amounts I would use the truncation function, not the rounding function. Hope it helps.

**Comment by wannesdemaeght** [comment]
Hi,

I'm sorry if I came over too forward, English is not my native tongue.

What I was trying to get at is the following:
I would like to have a dynamic list of exchanges to use, so that I can just update an array with exchange names, and all functions would work in accordance to said array.

This is working now, but in some cases ( eg this one), I can not get the correct info 100% of the time using the same call per exchange.

2 follow-up questions after reading your answers:

1) Is there a place where we can see what issues are already known to the devs, so that we know not to report the same issues over and over?

2) will the .currencies endpoint work for all exchanges?


Sorry for the questions, I'm converting my tradebot from multiple different libraries (1 per exchange) to a unified library, and it comes with some growing pains...

**Comment by kroitor** [comment]
> 1. Is there a place where we can see what issues are already known to the devs, so that we know not to report the same issues over and over?

You're are already there. This is such a place. So, all issues, are in the Issues section: https://github.com/ccxt/ccxt/issues

> will the .currencies endpoint work for all exchanges?

We hope, yes.

**Comment by wannesdemaeght** [comment]
Hi, I "fixed" this by making the fetcMarkets a double API call (since it's only called once anyway)

```
async fetchMarkets () {
        let response = await this.publicGetMarketOpenSymbols ();
		let response2 = await this.publicGetMarketOpenCoins ();
        let currencies = response2['data'];
        let markets = response['data'];
        let result = [];
        for (let i = 0; i < markets.length; i++) {
            let market = markets[i];
            let id = market['symbol'];
            let base = market['coinType'];
            let quote = market['coinTypePair'];
            base = this.commonCurrencyCode (base);
            quote = this.commonCurrencyCode (quote);
            let symbol = base + '/' + quote;
			let decAmnt = 8;
			for (let x = 0; x < currencies.length; x++) {
				let currency = currencies[x];
				if (currency['coin'] === base) decAmnt = currency['tradePrecision'];
			};
            let precision = {
				'amount': decAmnt,
				'price': 8,
            };
            let active = market['trading'];
            result.push (this.extend (this.fees['trading'], {
                'id': id,
                'symbol': symbol,
                'base': base,
                'quote': quote,
                'active': active,
                'info': market,
                'lot': Math.pow (10, -precision['amount']),
                'precision': precision,
                'limits': {
                    'amount': {
                        'min': Math.pow (10, -precision['amount']),
                        'max': undefined,
                    },
                    'price': {
                        'min': undefined,
                        'max': undefined,
                    },
                },
            }));
        }
        return result;
    }
```

If this is up to your standards, I could try to do a PR? (mind you, I've no idea how to do that yet, but I'm learning)
