### ISSUE TITLE
gateio load_markets() missing pairs

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#12321]
- OS: python
- Programming Language version: python
- CCXT version: 1.75.93
still working: 1.74.63

``` python
import ccxt
exchange = ccxt.gateio()
lm = exchange.load_markets()
print(len(lm))
print(lm['1INCH3L/USDT'])
```

Running this on 1.74.63 returns the pair just fine, but the latest version is no longer returning this pair (as well as a multitude of others).

The overall number of "reported USDT pairs" reduced from 2558 in 1.74.63 to 405 in 1.75.93.

`1INCH3L/USDT` seems to be a mostly "regular" pair (not futures) - although it is an ETF pair - but can be traded on regular spot markets 

Enabling verbose mode shows that the pair is still contained in the original response - but not in the ccxt "load markets" response.

```
fetch Request: gateio GET https://api.gateio.ws/api/v4/spot/currency_pairs RequestHeaders: {'X-Gate-Channel-Id': 'ccxt', 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate'} RequestBody: None 

fetch Response: gateio GET https://api.gateio.ws/api/v4/spot/currency_pairs 200 ResponseHeaders: {'Date': 'Sat, 12 Mar 2022 15:56:38 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'openresty', 'X-Request-Id': '[a5477c93-5535574923]', 'Access-Control-Allow-Methods': 'GET,POST,OPTIONS,DELETE,PUT', 'Access-Control-Allow-Headers': 'DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type', 'Access-Control-Max-Age': '1728000', 'Vary': 'Origin', 'Content-Encoding': 'gzip'} ResponseBody: [

...
{"id":"1
INCH3L_USDT","base":"1INCH3L","quote":"USDT","fee":"0.2","min_quote_amount":"1","amount_precision":3,"precision":6,"trade_status":"tradable","sell_start":0,"buy_start":0}
...

]
```

**Comment by carlosmiei** [comment]
Hello @xmatthias 
Thanks for reporting it was indeed a bug introduced recently on a refactor, will be fixed soon!
