### ISSUE TITLE
 TypeError: catching classes that do not inherit from BaseException is not allowed when I import flask

### ISSUE THREAD

**Issue by jamezun** [ccxt/ccxt#12327]
- OS: win 10
- Programming Language version: python3
- CCXT version: 1.56.23

When I import Flask, I have the following error, how could I solve this? I wonder it was caused by clashing with the library of ccxt? There will be another way to fix it by not using flask at all by substituting with another module like fastapi, but to make it simple, I want to know if there is any easy way to solve this first, thanks!

```
    import ccxt
    from flask import Flask
    
    exchange = ccxt.coinbase()
    markets = exchange.load_markets()
    
    for market in markets:
        print(market)

```

> Exception ignored in: <function Exchange.del at 0x000001D30B3B2D30> Traceback (most recent call last): File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 399, in del File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 747, in close File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 325, in close File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\poolmanager.py", line 222, in clear File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3_collections.py", line 100, in clear File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\poolmanager.py", line 173, in File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 494, in close TypeError: catching classes that do not inherit from BaseException is not allowed

**Comment by Hades2525** [comment]
I have the exact same issue :/

**Comment by kroitor** [comment]
@jamezun @Hades2525 I've pushed a workaround, please, let us know if you have this issue with CCXT Version 1.75.7+, the new build will arrive in ~20 minutes. Thanks!

**Comment by Hades2525** [comment]
@kroitor it is fixed for me ! Thank you.
