### ISSUE TITLE
ccxt.base.errors.InvalidOrder: mexc {"success":false,"code":1002,"message":"Contract not allow place order!"}

### ISSUE THREAD

**Issue by offy12321** [ccxt/ccxt#12332]
I have a problem with mexc.create_swap_order().
This is my code.

```
mc = ccxt.mexc({'apiKey': api_key, 'secret': secret_key})
mc.create_swap_order(symbol="BTC_USDT", type=5, side=1, amount=2, price=None, params={
  "symbol": "BTC_USDT",
  "side": 1,
  "openType": 1,
  "type": "5",
  "vol": 2,
  "positionMode": 2,
  "leverage": 20,
  "marketOrderLevel": "1"
})

```
And I got.

> ccxt.base.errors.InvalidOrder: mexc {"success":false,"code":1002,"message":"Contract not allow place order!"}

Thank you.

**Comment by kroitor** [comment]
You are sending `params` that it does not support: 

<img width="1115" alt="Screenshot 2022-03-14 at 03 29 58" src="https://user-images.githubusercontent.com/1294454/158086420-e69d5590-c167-4526-be0f-2b51bb691aa3.png">

It does not have a positionMode parameter, and it does not have a marketOrderLevel parameter. You should not put the params, that are not documented in the exchange API docs to your param-overrides.

```Python
mc = ccxt.mexc({'apiKey': api_key, 'secret': secret_key})
mc.create_swap_order(symbol="BTC_USDT", type=5, side=1, amount=2, price=None, params={
  "openType": 1,
  "leverage": 20,
})
```

**Comment by offy12321** [comment]
I still got this.

```
Traceback (most recent call last):
  File "/Users/romporatchanon/PycharmProjects/mexc/trya.py", line 43, in <module>
    mc.create_swap_order(symbol="BTC_USDT", type=5, side=1, amount=2, price=None, params={
  File "/Users/romporatchanon/miniforge3/envs/tensorflow/lib/python3.9/site-packages/ccxt/mexc.py", line 1703, in create_swap_order
    'price': float(self.price_to_precision(symbol, price)),
  File "/Users/romporatchanon/miniforge3/envs/tensorflow/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1435, in price_to_precision
    return self.decimal_to_precision(price, ROUND, market['precision']['price'], self.precisionMode, self.paddingMode)
  File "/Users/romporatchanon/miniforge3/envs/tensorflow/lib/python3.9/site-packages/ccxt/base/decimal_to_precision.py", line 54, in decimal_to_precision
    dec = decimal.Decimal(str(n))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

Thank you.

**Comment by offy12321** [comment]
> You are sending `params` that it does not support:
> 
> <img alt="Screenshot 2022-03-14 at 03 29 58" width="1115" src="https://user-images.githubusercontent.com/1294454/158086420-e69d5590-c167-4526-be0f-2b51bb691aa3.png">
> 
> It does not have a positionMode parameter, and it does not have a marketOrderLevel parameter. You should not put the params, that are not documented in the exchange API docs to your param-overrides.
> 
> ```python
> mc = ccxt.mexc({'apiKey': api_key, 'secret': secret_key})
> mc.create_swap_order(symbol="BTC_USDT", type=5, side=1, amount=2, price=None, params={
>   "openType": 1,
>   "leverage": 20,
> })
> ```

I still got this. 

`Traceback (most recent call last):
  File "/Users/romporatchanon/PycharmProjects/mexc/trya.py", line 43, in <module>
    mc.create_swap_order(symbol="BTC_USDT", type=5, side=1, amount=2, price=None, params={
  File "/Users/romporatchanon/miniforge3/envs/tensorflow/lib/python3.9/site-packages/ccxt/mexc.py", line 1703, in create_swap_order
    'price': float(self.price_to_precision(symbol, price)),
  File "/Users/romporatchanon/miniforge3/envs/tensorflow/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1435, in price_to_precision
    return self.decimal_to_precision(price, ROUND, market['precision']['price'], self.precisionMode, self.paddingMode)
  File "/Users/romporatchanon/miniforge3/envs/tensorflow/lib/python3.9/site-packages/ccxt/base/decimal_to_precision.py", line 54, in decimal_to_precision
    dec = decimal.Decimal(str(n))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]`

Thank you.

**Comment by kroitor** [comment]
@offy12321 what is your version of CCXT ? there's no price_to_precision call in the most recent version of mexc.py on line 1703: https://github.com/ccxt/ccxt/blob/master/python/ccxt/mexc.py#L1703 so your version of the lib is probably outdated. Please, upgrade it and let us know if you have this issue with CCXT 1.77.6+. 

Also, please use the correct unified symbol for the contract:

- https://github.com/ccxt/ccxt/issues/10931
- https://docs.ccxt.com/en/latest/manual.html#contract-naming-conventions

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.mexc({
    'apiKey': api_key,
    'secret': secret_key,
    'options': {
        'defaultType': 'swap'
    }
})
markets = exchange.load_markets()
exchange.verbose = True  # uncomment for debugging purposes if necessary
exchange.create_swap_order(symbol="BTC/USDT:USDT", type=5, side=1, amount=2, price=None, params={
  "openType": 1,
  "leverage": 20,
})
```

↑ If that does not work for you with CCXT 1.77.6+, please, paste your complete verbose output here.
