### ISSUE TITLE
refer to #12332

### ISSUE THREAD

**Issue by offy12321** [ccxt/ccxt#12345]
```
mc = ccxt.mexc({'apiKey': api_key, 'secret': secret_key})
mc.create_swap_order(symbol="BTC_USDT", type=5, side=1, amount=2, price=None, params={
  "openType": 1,
  "leverage": 20,
})
```
I still got this.
`Traceback (most recent call last): File "/Users/romporatchanon/PycharmProjects/mexc/trya.py", line 43, in <module> mc.create_swap_order(symbol="BTC_USDT", type=5, side=1, amount=2, price=None, params={ File "/Users/romporatchanon/miniforge3/envs/tensorflow/lib/python3.9/site-packages/ccxt/mexc.py", line 1703, in create_swap_order 'price': float(self.price_to_precision(symbol, price)), File "/Users/romporatchanon/miniforge3/envs/tensorflow/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1435, in price_to_precision return self.decimal_to_precision(price, ROUND, market['precision']['price'], self.precisionMode, self.paddingMode) File "/Users/romporatchanon/miniforge3/envs/tensorflow/lib/python3.9/site-packages/ccxt/base/decimal_to_precision.py", line 54, in decimal_to_precision dec = decimal.Decimal(str(n)) decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

`

Thank you.

**Comment by kroitor** [comment]
@offy12321 we've pushed a fix for it in CCXT 1.76.18, please, let us know if you still have this issue with the most recent version. Also, JFYI, according to the info from the MEXC team:

> BTC_USDT ETH_USDT LTC_USDT has not been opened yet

So you can try any other contract, except those three above.

Closing this issue for now, feel free to reopen it if necessary.
