### ISSUE TITLE
Inconsistent candle data returned when using fetch_ohlcv() at 1 minute granuality for Huobi.

### ISSUE THREAD

**Issue by yash19pro** [ccxt/ccxt#12341]
- OS: MacOS Montrey 12.2.1 
- Programming Language version: Python 3.8.8
- CCXT version: 1.74.6
- Exchange: Huobi
- Method: fetch_ohlcv()

Here, I am trying to fetch the complete historical OHLCV data about a trading pair from an exchange using `fetch_ohlcv()` at a 1-minute interval.

```python

import time

import ccxt
import pandas as pd

# set exchange
exchange = ccxt.huobi({
    'enableRateLimit': True,
    # 'verbose': True,
})

symbol = 'BTC/USDT'
tf = '1m'
from_datetime = '2018-06-24 00:00:00'
from_timestamp = exchange.parse8601(from_datetime)
# end time
now = exchange.milliseconds()

# set timeframe in msecs
tf_multi = 60 * 1000
hold = 30

# make list to hold data
data = []

candle_no = (int(now) - int(from_timestamp)) / tf_multi + 1
print('downloading...')
while from_timestamp < now:
    try:
        ohlcvs = exchange.fetch_ohlcv(symbol, tf, from_timestamp)
        from_timestamp += len(ohlcvs) * tf_multi
        print(from_timestamp)

        data += ohlcvs  # ←------------------------------- this particular line will mix them

        print(str(len(data)) + ' of ' + str(int(candle_no)) + ' candles loaded...')
    except (ccxt.ExchangeError, ccxt.AuthenticationError, ccxt.ExchangeNotAvailable, ccxt.RequestTimeout) as error:
        print('Got an error', type(error).__name__, error.args, ', retrying in', hold, 'seconds...')
        time.sleep(hold)

header = ['t', 'o', 'h', 'l', 'c', 'v']

#  ↓↓↓↓ added timestamp sorting of your mixed "data" to this line ↓↓↓↓

df = pd.DataFrame(sorted(data, key=lambda x: x[0]), columns=header)
```
The script seems to return the wrong data for `Huobi` with the trading_pair as `BTC/USDT`. For the first iteration, the query for the data is from 2018-06-24 but the data that is returned is from 2022-03-13. There is a lot of duplication of the rows if this script is executed for Huobi, while the same script executed for Binance, works completely fine.
```
>>> df = pd.read_csv('foo.csv')
>>> df
         Unnamed: 0              t         o         h         l         c         v
0                 0  1647210840000  38719.64  38720.56  38670.93  38670.93  3.840178
1                 1  1647210840000  38719.64  38720.56  38670.93  38670.93  3.840178
2                 2  1647210840000  38719.64  38720.56  38670.93  38670.93  3.840178
3                 3  1647210840000  38719.64  38720.56  38670.93  38670.93  3.840178
4                 4  1647210840000  38719.64  38720.56  38670.93  38670.93  3.840178
...             ...            ...       ...       ...       ...       ...       ...
1957878     1957878  1647271320000  39001.50  39029.00  38998.79  39021.37  6.081969
1957879     1957879  1647271320000  39001.50  39029.00  38998.79  39021.37  6.081969
1957880     1957880  1647271320000  39001.50  39029.00  38998.79  39017.19  6.082467
1957881     1957881  1647271320000  39001.50  39029.00  38998.79  39017.19  6.082467
1957882     1957882  1647271320000  39001.50  39029.00  38998.79  39017.19  6.117897

[1957883 rows x 7 columns]
>>> df['diff'] = df['t'].diff()
>>> df
         Unnamed: 0              t         o         h         l         c         v  diff
0                 0  1647210840000  38719.64  38720.56  38670.93  38670.93  3.840178   NaN
1                 1  1647210840000  38719.64  38720.56  38670.93  38670.93  3.840178   0.0
2                 2  1647210840000  38719.64  38720.56  38670.93  38670.93  3.840178   0.0
3                 3  1647210840000  38719.64  38720.56  38670.93  38670.93  3.840178   0.0
4                 4  1647210840000  38719.64  38720.56  38670.93  38670.93  3.840178   0.0
...             ...            ...       ...       ...       ...       ...       ...   ...
1957878     1957878  1647271320000  39001.50  39029.00  38998.79  39021.37  6.081969   0.0
1957879     1957879  1647271320000  39001.50  39029.00  38998.79  39021.37  6.081969   0.0
1957880     1957880  1647271320000  39001.50  39029.00  38998.79  39017.19  6.082467   0.0
1957881     1957881  1647271320000  39001.50  39029.00  38998.79  39017.19  6.082467   0.0
1957882     1957882  1647271320000  39001.50  39029.00  38998.79  39017.19  6.117897   0.0

[1957883 rows x 8 columns]
>>> df.value_counts('diff')
diff
0.0        1956874
60000.0       1008
dtype: int64
>>> 
```
Not sure what is causing this behavior or how to fix it? This error does not appear to occur when I use `binance` instead of `huobi`.

**Comment by ttodua** [comment]
I've tested it and couldnt reproduce. the first iteration returns the expected data for me (where the first candles timestamp is 1529798400000 ).  Try once again - after 'fetch_OHLCV' line, add the below code and check what it does print:
 ```
        print(str(from_timestamp) + " <--> " + str(ohlcvs[0][0])) 
```

**Comment by yash19pro** [comment]
I tried printing this statement, `print(str(from_timestamp) + " <--> " + str(ohlcvs[0][0]))` and as the output, I got the same thing that I got earlier. Here is the screenshot of that.
<img width="1552" alt="Screenshot 2022-03-15 at 8 36 26 PM" src="https://user-images.githubusercontent.com/65077864/158408704-1df8249a-8a41-4b73-8d5d-e7f71c84df7a.png">

Attaching the code as well,
```python

import time

import ccxt
import pandas as pd

# set exchange
exchange = ccxt.huobi({
    'enableRateLimit': True,
    # 'verbose': True,
})

symbol = 'BTC/USDT'
tf = '1m'
from_datetime = '2018-06-24 00:00:00'
from_timestamp = exchange.parse8601(from_datetime)
# end time
now = exchange.milliseconds()

# set timeframe in msecs
tf_multi = 60 * 1000
hold = 30

# make list to hold data
data = []

candle_no = (int(now) - int(from_timestamp)) / tf_multi + 1
print('downloading...')
while from_timestamp < now:
    try:
        ohlcvs = exchange.fetch_ohlcv(symbol, tf, from_timestamp)
        print(str(from_timestamp) + " <--> " + str(ohlcvs[0][0]))
        from_timestamp += len(ohlcvs) * tf_multi
        print(from_timestamp)

        df = pd.DataFrame(ohlcvs, columns=['t', 'o', 'h', 'l', 'c', 'v'])
        print(df)

        data += ohlcvs  # ←------------------------------- this particular line will mix them

        print(str(len(data)) + ' of ' + str(int(candle_no)) + ' candles loaded...')
    except (ccxt.ExchangeError, ccxt.AuthenticationError, ccxt.ExchangeNotAvailable, ccxt.RequestTimeout) as error:
        print('Got an error', type(error).__name__, error.args, ', retrying in', hold, 'seconds...')
        time.sleep(hold)
    break

header = ['t', 'o', 'h', 'l', 'c', 'v']
#  ↓↓↓↓ added timestamp sorting of your mixed "data" to this line ↓↓↓↓

df = pd.DataFrame(sorted(data, key=lambda x: x[0]), columns=header)
df.to_csv('huobi.csv', index=False)

```

Here as you can see that I am querying for the data from the year 2018 but am getting the latest data only.

Added the break statement to reduce the output size.

**Comment by yash19pro** [comment]
Ohh, now it works fine. I changed the python version, to python 3.10 and updated the libraries' version and their dependencies to the latest version and it works fine now.

But it doesn't work for kraken now.

Here is the the screenshot.
<img width="1552" alt="Screenshot 2022-03-16 at 1 03 26 AM" src="https://user-images.githubusercontent.com/65077864/158457064-4d917a76-1ec3-4c1b-bcf0-110c772d3d12.png">

Attaching the code as well,
```python
import time

import ccxt
import pandas as pd

# set exchange
exchange = ccxt.kraken({
    'enableRateLimit': True,
    # 'verbose': True,
})

symbol = 'BTC/USDT'
tf = '1m'
from_datetime = '2018-06-24 00:00:00'
from_timestamp = exchange.parse8601(from_datetime)
# end time
now = exchange.milliseconds()

# set timeframe in msecs
tf_multi = 60 * 1000
hold = 30

# make list to hold data
data = []

candle_no = (int(now) - int(from_timestamp)) / tf_multi + 1
print('downloading...')
while from_timestamp < now:
    try:
        ohlcvs = exchange.fetch_ohlcv(symbol, tf, from_timestamp)
        print(str(from_timestamp) + " <--> " + str(ohlcvs[0][0]))
        from_timestamp = ohlcvs[-1][0] + tf_multi
        print(from_timestamp)

        df = pd.DataFrame(ohlcvs, columns=['t', 'o', 'h', 'l', 'c', 'v'])
        print(df)

        data += ohlcvs  # ←------------------------------- this particular line will mix them

        print(str(len(data)) + ' of ' + str(int(candle_no)) + ' candles loaded...')
    except (ccxt.ExchangeError, ccxt.AuthenticationError, ccxt.ExchangeNotAvailable, ccxt.RequestTimeout) as error:
        print('Got an error', type(error).__name__, error.args, ', retrying in', hold, 'seconds...')
        time.sleep(hold)

header = ['t', 'o', 'h', 'l', 'c', 'v']
#  ↓↓↓↓ added timestamp sorting of your mixed "data" to this line ↓↓↓↓

df = pd.DataFrame(sorted(data, key=lambda x: x[0]), columns=header)
df.to_csv('kraken.csv', index=False)
```

**Comment by ttodua** [comment]
after testing, turns out that kraken api only returns last 720 (719) items from [OHLC ](https://docs.kraken.com/rest/#operation/getTickerInformation)endpoint, even if you set `since` in the past, it wont extend in the past (i.e. see [this ](https://api.kraken.com/0/public/OHLC?pair=XBTUSD&since=1644832000&interval=1)). so, the `since` parameter is actually useless there, unless you want to get granular (smaller) resource (i.e. last 20 bars or so), then you can set `since` to value which will be distanced from current time as much as there will fit only 20 bars.

**Comment by YuriyTigiev** [comment]
> after testing, turns out that kraken api only returns last 720 (719) items from [OHLC ](https://docs.kraken.com/rest/#operation/getTickerInformation)endpoint, even if you set `since` in the past, it wont extend in the past (i.e. see [this ](https://api.kraken.com/0/public/OHLC?pair=XBTUSD&since=1644832000&interval=1)). so, the `since` parameter is actually useless there, unless you want to get granular (smaller) resource (i.e. last 20 bars or so), then you can set `since` to value which will be distanced from current time as much as there will fit only 20 bars.
> 
> So, I assume this issue to be closed. but feel free to reopen, if there is still issue with regard to this matter.

I have the similar issue with the "FTX spot exchange".  Some times a method fetch_ohlcv returns correct number of candles and sometimes it return less on one candle. I would like to use a parameter "since" to avoid this problem. How to calculate a parameter "since" for selected "timeframe" and "candles"? For example for fetching a last 10 "3w" candles since current datetime.

**Comment by ttodua** [comment]
@YuriyTigiev I fear that the bug and inconsistency in FTX api (which they were unable to fix during all these years with a simple param switch) makes us unable to fix that. As I've mentioned earlier (and now confirmed by you too) it sometimes returns 1 candle less. So, you should make your snippet smth like this:
```
if (returned_bars.length == limit - 1) {
    //returned one bar less, let's re-fetch
    const new_since = since - ex.duration (timeframe)*1;
    const additional_bars = await ex.fetchOHLCV(symbol, timeframe, new_since);
    ... your logic here
}
```
or second alternative is to fetch more bars then your current limit bars (so if you are fetching 100 bars in your snippet, just set it to fetch 101 bars and just use 100 bars in calculations).

**Comment by YuriyTigiev** [comment]
> @YuriyTigiev I fear that the bug and inconsistency in FTX api (which they were unable to fix during all these years with a simple param switch) makes us unable to fix that. As I've mentioned earlier (and now confirmed by you too) it sometimes returns 1 candle less. So, you should make your snippet smth like this:
> 
> ```
> if (returned_bars.length == limit - 1) {
>     //returned one bar less, let's re-fetch
>     const new_since = since - ex.duration (timeframe)*1;
>     const additional_bars = await ex.fetchOHLCV(symbol, timeframe, new_since);
>     ... your logic here
> }
> ```
> 
> or second alternative is to fetch more bars then your current limit bars (so if you are fetching 100 bars in your snippet, just set it to fetch 101 bars and just use 100 bars in calculations).

Thank you. 
I use the second  approach. What I found that this problem appears with pairs which have small daily volume. I think that "current candle" creates only after a first deal and only in this case API return the correct number of candles.

**Comment by YuriyTigiev** [comment]
How CCXT library calc a parameter start_time for a "get trades"  for the FTX SPOT API?

https://docs.ftx.com/#get-trades 
https://ftx.com/api/markets/BTC/USD/candles?resolution=60

**Comment by ttodua** [comment]
@YuriyTigiev it's hard to verbally describe, maybe you can take a look here - https://github.com/ccxt/ccxt/blob/5b1adf0938f18ec4157164a1ef99b1557681856b/js/ftx.js#L944

**Comment by YuriyTigiev** [comment]
> @YuriyTigiev it's hard to verbally describe, maybe you can take a look here -
> 
> https://github.com/ccxt/ccxt/blob/5b1adf0938f18ec4157164a1ef99b1557681856b/js/ftx.js#L944

I have tested FTX API from the browser and found that for some symbols, 1m OHLCV data could sometimes come with 2 minutes delay. It is not the CCXT  library issue. I also planned to cache completed OHLCV data and use a combination of symbol+timeframe+since as a unique cache index, but in cases of 2 minutes delay, it will not work for me.

**Comment by ttodua** [comment]
@YuriyTigiev thanks for sharing useful bits of infos! I will keep note of it, as I didn't expect FTX returned delayed data and misbehaved at that level.
