### ISSUE TITLE
[Zipmex] watchTicker is not trustable

### ISSUE THREAD

**Issue by prinprem** [ccxt/ccxt#12355]
- OS: macOS Monterey 12.2.1
- Programming Language version: JS, Node 17.7.1
- CCXT version:1.77.18 & CCXT.Pro

Which exchange it is: Zipmex

Which method you're trying to call: watchTicker()

```
const data = await exchange.watchTicker('BTC/THB');
console.log(data);
```

I do not have any error but I do have problem with the responsed data which is not in realtime comparing to Zipmex exchange, when Zipmex's ticker changes the method watchTicker() send me nothing. It looks like watchTicker() method can only send data every 1 minute which is no longer watch the ticker at all.

I bought your CCXT Pro license in hopes that it will help me work more easily with Websocket not API. Hope you fix it asap.

**Comment by kroitor** [comment]
@prinprem in general, we don't limit the exchange updates, it depends on the underlying exchange how frequently they send the ticker updates. The ticker itself is not real-time, it's a secondary data, that is calculated from the orderbook and trades by 100% of the exchanges, so it will usually either take some delay to update the ticker, or it will be updated in regular intervals. If you want to be as close to realtime as possible, then you want watchOrderBook and watchTrades.

You can enable the verbose output and verify that on your end:

```JavaScript
const ccxtpro = require ('ccxt.pro')

async function main() {
    const exchange = new ccxt.zipmex()
    const markets = await exchange.loadMarkets ()
    exchange.verbose = true
    while (true) {
        try {
            ticker = await exchange.watchTicker ('BTC/THB')
            console.log (ticker)
        } catch (e) {
            console.log (e.constructor.name, e.message)
            break
        }
    }
}

main ()
```

Hope that answers your question, let us know if not. Feel free to reopen this issue or just ask further questions here if any.
