### ISSUE TITLE
Bybit new endpoints

### ISSUE THREAD

**Issue by 9808us** [ccxt/ccxt#12360]
Hi,I looked at the bybit.js code and found notes about new endpoints and
'defaultType': 'swap', // swap, spot, future, option

I saw an issue closed few days ago about spot trading in bybit that said you were working on it.

So quetion is if bybit is ready or not, see screenshot below

Thank you

![image](https://user-images.githubusercontent.com/38046064/158608572-f5685bff-10a7-4f98-bc60-bc0b6b2d4386.png)

**Comment by kroitor** [comment]
> So quetion is if bybit is ready or not, see screenshot below

Not yet, but it will be ready very soon! Will let you know: 

- https://github.com/ccxt/ccxt/issues?q=bybit+is%3Aopen
- https://github.com/ccxt/ccxt/issues/9803
