### ISSUE TITLE
Is this the correct way to place a trailing order in FTX? Can we set a trailling trigger price as well in FTX?

### ISSUE THREAD

**Issue by jamezun** [ccxt/ccxt#12379]
- OS: win10 
- Programming Language version: python latest
- CCXT version: latest (FTX)

I am using the FTX exchange, what is the correct way to place a trailing stop order? Is the following correct? **Should I leave price=None?** 
`order = exchange.create_order('ETH-PERP','trailingStop','sell', 0.001, price=None, params={'reduceOnly':True,'trailValue':-50,"retryUntilFilled": True})`

In the FTX CCXT python code, I notice that for create order, there are parameters "triggerPrice" and "triggeredAt", are they only made for stop price only? **Is it possible to send an trailing market order _with a trigger price_ as well?** (At least I know it is not possible to do so in the website and its app). If yes, how should I rewrite the above code? Thanks!

**Comment by DarKayserLeo** [comment]
Hi, I'm facing same issue. Did you manage to find the correct way to create a Trailing Stop order.

Documentation is really poor! =(

**Comment by jamezun** [comment]
> Hi, I'm facing same issue. Did you manage to find the correct way to create a Trailing Stop order.
> 
> Documentation is really poor! =(

As far as I remember that are no simple way to do that, I just have the program check if the price exceed the trigger price, and if that is the case, I will send out the trailing order...

**Comment by samgermain** [comment]
Closing because FTX is delisted now, and there is no unified way to set a trailing stop order
