### ISSUE TITLE
How to hide errors from my users?

### ISSUE THREAD

**Issue by mohammadwillwin** [ccxt/ccxt#1237]
On my website, I let my users import their orders. But some of them write the wrong API key, so then it shows ccxt's huge long error, including my website's system username in the directory of the PHP file that the error came from.

This is a security issue for my website. How can I hide these ccxt errors?

**Comment by kroitor** [comment]
Catch them?

**Comment by kroitor** [comment]
- https://www.youtube.com/watch?v=sPHuhQOxisg
- https://www.w3schools.com/php/php_exception.asp
- https://code.tutsplus.com/tutorials/php-exceptions--net-22274
- https://www.google.ru/search?q=php+exceptions+tutorial

Hope it helps.
