### ISSUE TITLE
How to return ALL networks and addresses for a currency using createDepositAddress()

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#12378]
OS: Windows Server 2019 Datacenter
Programming Language version: Node.js 15.3.0
CCXT version: 1.49.98
Exchange: Binance and All Exchanges
Method: exchange.createDepositAddress()

Hello!

I have a question about `createDepositAddress()`.  I have followed the code on this link and the manual:
https://github.com/ccxt/ccxt/issues/4562
https://github.com/ccxt/ccxt/wiki/Manual#funding-your-account

I wonder about the networks. For example Binance has both `ERC20` and `TRC20` for the currency `USDT`. I know I have 2 different addresses for those on the exchange.

The below code returns the `ERC20` address. I simply wonder, how/is there a way to return ALL networks and addresses for the currency in question?

Thank you!  
```
createDepositAddress();
async function createDepositAddress() {

    let response = undefined
    const currencyCode = 'USDT'
    const amount = 1.2345

    const Exchange = ccxt["binance"];
    const exchange = new Exchange({ enableRateLimit: true, 'timeout': 30000 }); //(Have Also set API keys)
    exchange.timeout = 30000;
    try {

        if (exchange.has['fetchDepositAddress']) {
            response = await exchange.fetchDepositAddress(currencyCode)
        } else if (exchange.has['createDepositAddress']) {
            response = await exchange.createDepositAddress(currencyCode)
        }
        console.log(
            'In order to deposit ' + amount.toString() + ' ' + currencyCode + ' to ' + exchange.id +
            ', please send your ' + amount.toString() + ' ' + currencyCode + ' to the address provided by ' +
            exchange.id + ' exchange for depositing: ' + response['address'] + (response['tag'] || '') + ' ' + "Network: " + response["network"] + ' ' + "Info: " + response["info"])

    } catch (e) { console.log(e.constructor.name, e.message) }
}
```

**Comment by kroitor** [comment]
Some exchanges have a method called `exchange.fetchDepositAddressesByNetwork`, that method allows fetching all networks at once, but in general it is rare, and very few exchanges will support it. You cannot return all networks at once from `exchange.createDepositAddress()` or from `exchange.fetchDepositAddress()`, but you can specify a `network` parameter to `exchange.createDepositAddress()` or to `exchange.fetchDepositAddress()` to override the default network returned from the exchange: 

```
await exchange.fetchDepositAddress(currencyCode, { 'network: 'TRC20' })
```

Also, if the exchange does not have `exchange.fetchDepositAddressesByNetwork()`, then also check `exchange.currencies[currencyCode]` for a `networks` property inside the currency in question. Some exchanges will provide the networks info inside the currencies-info. Note, that you have to `exchange.loadMarkets()` before accessing markets and currencies. Hope that answers your question, let us know if not.

**Comment by jackpotcityco** [comment]
`_also check exchange.currencies[currencyCode] for a networks property inside the currency in question. Some exchanges will provide the networks info inside the currencies-info._`

Thank you for that information. I will work with that information.

To take an example, if I were to withdraw `USDT` from `Kucoin` to `Binance` and want to do it on the `TRC20` network. I also need to check if `Kucoin` has the `TRC20` for `USDT`.

It is then possible to use the `exchange.currencies[currencyCode]` to determine that the exchange that I withdraw from also has the `TRC20` network. In order words. I have to search as you mentioned with the different approaches to return that both exchanges has the network?
If trying to withdraw from a network from example `Kucoin` and this network doesn't exist. I beleive would be impossible and result in an error, - instead of tokens be lost in a withdrawal which is not possible due to the network in the first place is not avaliable on `Kucoin` (and other exchanges ofcourse)?
