### ISSUE TITLE
Is it possible to fetch open order by orderid? [FTX]

### ISSUE THREAD

**Issue by jamezun** [ccxt/ccxt#12380]
- OS: Win10
- Programming Language version: python 3 Latest
- CCXT version: Latest

Is it possible to fetch the open order by symbol and id? or I just need to parse the result and check the id using my own code?

order = exchange.fetch_open_orders('ETH-PERP', since=None, limit=None, params={'method':'privateGetConditionalOrders','orderId': 123456
I notice that no matter what orderID i pass in, it just pops up all the ETH-PERP conditional open orders instead of just that order ID123456 order.

**Comment by kroitor** [comment]
The FTX API doc does not have an orderId parameter for conditional orders: https://docs.ftx.com/#get-open-trigger-orders
Just use the elementary programming for filtering the order by your id after fetching all orders:

```Python
orders = exchange.fetch_open_orders('ETH-PERP', since=None, limit=None, params={'method':'privateGetConditionalOrders'})
orders_by_id = exchange.index_by(orders, 'id')
order = exchange.safe_value(orders_by_id, '123456')
```
