### ISSUE TITLE
Close all stop orders at once

### ISSUE THREAD

**Issue by ExpensiveJok** [ccxt/ccxt#12381]
Hi, the first thing I want to thank you for all this work. You guys are doing great.

I want to see my pending stop limit orders but I can't. That's because I am working on **Kucoin futures** API and the only way I can figure out how to set it is I set up my order and the **stop-loss(SL)** and **take-profit(TP)** orders is sending 3 _"stop_limit"_ orders at once. 
The first one for my entry point and the others for TP and SL. I did that because Kucoin has some kind of protection that doesn't allow you to set up _"limit_orders"_ that are far of the current price.
It would be great if in the future you can add some TP and SL levels in the current `create_order`. And also the Kucoin guys could remove that silly limitation.

So, when my TradingView alert comes with the out strategy call I want to erase all my pending _"stop_limit"_ orders.
I tried `stop_orders = exchange.fetch_open_orders(tickers[data["ticker"]], params={"type" : "limit_stop", "status" : "active"})` but doesn't show me the _"stop_limit"_ pending orders. So If I use` exchange.cancel_all_orders(ticker,params={"type" : "limit_stop"})`  It doesn't eliminates the stop_limit orders, it only cleans the  **Open Orders** (don't be confused, these orders are the pending limit orders not the current **Positions**). 

I searched and tried other ways like `fetch_orders_by_status` but it was the same. IDK probably I am wrong but I think there is no way to see (and after clean it) the active _"stop_limit"_ order list.

Prob that is the key, but I don't know what to do with it. 
[https://docs.kucoin.com/futures/?lang=en_US#get-untriggered-stop-order-list]

**Comment by ttodua** [comment]
late reply here, but this would do the job what you needed, i.e.:
```
const canceledOrders = kucoin.cancelAllOrders('BTC/USDT', {'stop':true});
```
let us know if you have further issues with CCXT.
