### ISSUE TITLE
missing max borrowable in gateio

### ISSUE THREAD

**Issue by leastchaos** [ccxt/ccxt#12406]
![image](https://user-images.githubusercontent.com/64965782/159142881-3f0399fe-3935-461e-afba-9597f45d0a8b.png)

get borrowables api call seems to be missing for gateio and i cannot find the call for it

![image](https://user-images.githubusercontent.com/64965782/159142906-0ac02182-8494-48cc-9795-76b129bda409.png)

**Comment by samgermain** [comment]
@leastchaos I think the endpoint is new, I added all the new missing endpoints from gateio in https://github.com/ccxt/ccxt/pull/12425

**Comment by leastchaos** [comment]
@samgermain Thank you for the fast update!
