### ISSUE TITLE
Bybit php order example, question

### ISSUE THREAD

**Issue by mtokitt** [ccxt/ccxt#12403]
How should a bybit order using php look like, be called, ty.
```
$params = [
    'symbol' => 'BTCUSDT', 
    'side' => 'Buy', 
    'order_type' => 'Limit', 
    'qty' => '1', 
    'price' => '41000', 
    'time_in_force' => 'GoodTillCancel',
    'reduce_only' => false,
    'close_on_trigger' => false,
    'timestamp' => time() * 1000,
    'position_idx' => 0
];
``` 
This order should look how, for instance...
```
$order = $bybit ->futuresPrivatePostOrderCreate($params); 
```
ty.

**Comment by mtokitt** [comment]
$order = $bybit -> create_order("BTC/USDT", "limit", "buy", "0.001", 8100) ; // this will work

From "public function create_order($symbol, $type, $side, $amount, $price = null, $params = array ()) {" ...in bybit.php

Thanks for code project. My issue is finding php examples. Now I go to 'discover' the correct syntax to use to create a TP/SL order using php. Pls keep question open, so when I find I can post here.

**Comment by ttodua** [comment]
I was able to put Perpetual (swap) orders with embedded 'stop-loss' close orders with this:
```
$ex = new \ccxt\bybit(...);
$params = [
    'stop_loss' => 40000
];
var_dump( $ex->create_order("BTC/USDT", "limit", "buy", "0.001", 45000, $params) );
```
Let me know if you still have issues. if not, we can close this issue.
