### ISSUE TITLE
How to pass in key parameters to exchange function in code example

### ISSUE THREAD

**Issue by dptashny1** [ccxt/ccxt#12407]
With respect to this example: https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/many-exchanges-many-different-streams.py.

The code includes this line:
exchange = getattr(ccxtpro, exchange_id)()

I tried to change it to this:
 exchange = getattr(ccxtpro, exchange_id)({
'secret': config.BINANCE_SECRET,
'apiKey': config.BINANCE_API_KEY
})

Then I get the following error message:
binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
Exception ignored in: <function _ProactorBasePipeTransport.del at 0x000001879F2617E0>
Traceback (most recent call last):
File "C:\Users\david\anaconda3\envs\CryptoTrading\lib\asyncio\proactor_events.py", line 116, in del
self.close()
File "C:\Users\david\anaconda3\envs\CryptoTrading\lib\asyncio\proactor_events.py", line 108, in close
self._loop.call_soon(self._call_connection_lost, None)
File "C:\Users\david\anaconda3\envs\CryptoTrading\lib\asyncio\base_events.py", line 745, in call_soon
self._check_closed()
File "C:\Users\david\anaconda3\envs\CryptoTrading\lib\asyncio\base_events.py", line 510, in _check_closed
raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by kroitor** [comment]
Please, use the search:

- https://github.com/ccxt/ccxt/search?q=Timestamp+for+this+request+was+1000ms+ahead+of+the+server%27s+time&type=issues

Check this duplicate issue: https://github.com/ccxt/ccxt/issues/850

```Python
exchange = ccxtpro.binance({
    'secret': config.BINANCE_SECRET,
    'apiKey': config.BINANCE_API_KEY
    'options': {
        'adjustForTimeDifference': True,
    },
})
```

Hope that answers your question.

**Comment by dptashny1** [comment]
The warning is still there. Here's the full code I'm running:

Starting binance watchOrderBook ETH/BTC
Starting binance watchTrades ETH/BTC
**C:\Users\david\PycharmProjects\CryptoTrading\pro_test4.py:62: DeprecationWarning: There is no current event loop
  asyncio_loop = get_event_loop()**
------------------------------------
import ccxtpro
from asyncio import gather, run
import configETH as config


async def symbol_loop(exchange, method, symbol):
    print('Starting', exchange.id, method, symbol)
    while True:
        try:
            response = await getattr(exchange, method)(symbol)
            now = exchange.milliseconds()
            iso8601 = exchange.iso8601(now)
            if method == 'watchOrderBook':
                print(iso8601, exchange.id, method, symbol, response['asks'][0], response['bids'][0])
            elif method == 'watchTicker':
                print(iso8601, exchange.id, method, symbol, response['high'], response['low'], response['bid'], response['ask'])
            elif method == 'watchTrades':
                print(iso8601, exchange.id, method, symbol, len(response), 'trades')

        except Exception as e:
            print(str(e))
            # raise e  # uncomment to break all loops in case of an error in any one of them
            break  # you can break just this one loop if it fails


async def method_loop(exchange, method, symbols):
    print('Starting', exchange.id, method, symbols)
    loops = [symbol_loop(exchange, method, symbol) for symbol in symbols]
    await gather(*loops)


async def exchange_loop(exchange_id, methods):
    print('Starting', exchange_id, methods)
    exchange = getattr(ccxtpro, exchange_id)({
        'secret': config.BINANCE_SECRET,
        'apiKey': config.BINANCE_API_KEY,
        'options': {
            'adjustForTimeDifference': True
        }
    })
    loops = [method_loop(exchange, method, symbols) for method, symbols in methods.items()]
    await gather(*loops)
    await exchange.close()


async def main():
    exchanges = {
        'okex': {
            'watchOrderBook': ['BTC/USDT', 'ETH/BTC', 'ETH/USDT'],
            'watchTicker': ['BTC/USDT'],
        },
        'binance': {
            'watchOrderBook': ['BTC/USDT', 'ETH/BTC'],
            'watchTrades': [ 'ETH/BTC' ],
        },
    }
    loops = [exchange_loop(exchange_id, methods) for exchange_id, methods in exchanges.items()]
    await gather(*loops)

run(main())
