### ISSUE TITLE
problem on fetch Gate.io trade history

### ISSUE THREAD

**Issue by liarclor** [ccxt/ccxt#12412]
I could not fetch all my personal trade history on gate.io 
it suppose to have more than 3000 rows but the records only shows me partially records and starting time looks a bit weird.
it works when i put a specific symbol (pairs). 
what do I miss or am I wrong here? 
thanks a lot ...

Since I have asked Gate.io here.. I would also like to ask about Kucoin as well.... params = { "startAt": and "endAt": } could not fetch all as well..

the following is my code..

since = 1646064000000
now = gate.milliseconds()
all_trades = []

while since < now:
    print("------------------------------------------------------------------")
    symbol = None 
    limit = 1000 
    trades = gate.fetchMyTrades(symbol, since, limit)
    
    if len(trades):
        first_trade = trades[0]
        last_trade = trades[len(trades) - 1]
        print("Fetched", len(trades), "trades from", first_trade['datetime'], "till", last_trade['datetime'])
        since = trades[len(trades) - 1]['timestamp'] + 1
        all_trades += trades
    else:
        break

**Comment by samgermain** [comment]
>  it suppose to have more than 3000 rows but the records only shows me partially records and starting time looks a bit weird.

What does it look like?

**Comment by liarclor** [comment]
it's ok now. I fixed the code as following:

```
all_trades = []
page = 1

while True:
    print("------------------------------------------------------------------")
    symbol = None
    since = None
    limit = 1000
    params = {
        'from': int((gate.parse8601("2022-03-01T00:00:00Z"))/1000),
        'to': int((gate.parse8601("2022-03-10T23:59:59Z"))/1000),
        'page': page,
        'limit': 1000
    }
    trades = gate.fetchMyTrades(symbol, since, limit, params)
    all_trades.append(trades)
    
    if len(trades):
        
        first_trade = trades[0]
        last_trade = trades[len(trades) - 1]
        print("Fetch", len(trades), "trades from", first_trade['datetime'], "till", last_trade['datetime'])
        page += 1
        
    else:
        break

```

**Comment by liarclor** [comment]
however, kucoin trade history is another problem .. it can only generate 9pages (5000 rows)
