### ISSUE TITLE
fetch_ohlcv Coroutine Error

### ISSUE THREAD

**Issue by kursadaydin** [ccxt/ccxt#12429]
,
I created the following function. Actually it produces correct results but when running for a long time I get the following error

```
async def getOHLCV(exchange,coin):      
    response = await exchange.fetch_ohlcv(coin,config.TIME_FRAME.lower(),limit=25)
    await exchange.close()
    return response


asyncio_loop = asyncio.get_event_loop()
df = asyncio_loop.run_until_complete(Manager.getOHLCV(binance_exchange,symbols_USDT[i][0]))

```

binance requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add exchange.close() to 
your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session

**Comment by kroitor** [comment]
More info here:

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://docs.ccxt.com

**Comment by kursadaydin** [comment]
sorry, i don't know how to add question tag
