### ISSUE TITLE
Getting 123/456 in binance.symbols

### ISSUE THREAD

**Issue by hippylover** [ccxt/ccxt#1242]
Ok so this is a bit of a weird one. When im doing this: 
`exchanges['binance'].loadMarkets()
availMarkets = exchanges['binance'].symbols
print("symbols")
pprint.pprint(availMarkets)
`
Everything is cool, i get the right pairs. However when i do the exact same code in a qt prog that launches that code when you change a combobox it adds 123/456 ontop into the list.
I see something in the binance code about 123/456 in the comments so i figured you'd be able to figure out what it is or i can make an example and see if i can reproduce.

**Comment by hippylover** [comment]
eh. sorry for being lazy. here's an example:

`from PyQt5 import QtCore, QtGui, QtWidgets
import ccxt
import pprint

exchange = ccxt.binance()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        def lel():
            exchange.loadMarkets()
            availMarkets = exchange.symbols
            print("symbols")
            pprint.pprint(availMarkets)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(250, 160, 90, 32))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.activated.connect(lel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "bittrex"))
        self.comboBox.setItemText(1, _translate("MainWindow", "binance"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

`

**Comment by thijstriemstra** [comment]
I'm curious, what was this thing in binance, they have a 'special' market called `123/456`?

**Comment by hippylover** [comment]
I wonder that too :D I don't think you can trade it.

**Comment by kroitor** [comment]
@thijstriemstra , @hippylover yes, they have a special market 123/456, for testing, added filtering for it.

**Comment by hippylover** [comment]
cool!

**Comment by orkenstein** [comment]
Must be filtered out manually

**Comment by jjhesk** [comment]
should we hardcode the markets in the api file? @kroitor

**Comment by kroitor** [comment]
@jjhesk we would leave market caching on client side beyond the lib. I guess, the user can do `JSON.stringify()` (js), or `json.loads` (py) to/from a file or to his own in-memory cache. We can't rely on local storage files in the library, because it should work from browsers as well. So, all file-related stuff should be done in userland.
