### ISSUE TITLE
[bybit] the order is created in the contracts and not in the spot!? Why?

### ISSUE THREAD

**Issue by JefersonOC** [ccxt/ccxt#12427]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Linux Mint
- Programming Language version: Python
- CCXT version: 1.76.72

```
client = ccxt.bybit({
    'apiKey': api_key,
    'secret': api_secret,
    'enableRateLimit': True,
})
client.create_market_buy_order("GRT/USDT", 400)
```
the order is created in the contracts and not in the spot!? Why?

**Comment by ExpensiveJok** [comment]
Because you are creating a market type order, so you are buying at the current price.
You need to use a limit order to set up your target price.
`client.create_limit_buy_order("GRT/USDT", 400)` or `client.create_order()` and fill it with the ticker, type of order...

**Comment by kroitor** [comment]
@JefersonOC ByBit spot API is not unified yet: 

- https://github.com/ccxt/ccxt/issues?q=bybit+spot
- https://github.com/ccxt/ccxt/issues/11763
- https://github.com/ccxt/ccxt/issues/9578

It's in the process of unification right now, so the unified API for bybit won't work yet, but you can already use it via the implicit API edpoints. We hope to get it fully unified before the end of this month (including spot markets and perpetual swaps).

**Comment by kroitor** [comment]
@JefersonOC to clarify:

- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
- https://github.com/ccxt/ccxt/wiki/Manual#market-structure

```Python
import ccxt
exchange = ccxt.bybit()
markets = exchange.load_markets()
for symbol, market in markets.items():
    print(symbol, market['type'])
```
