### ISSUE TITLE
[Zipmex] withdraw function

### ISSUE THREAD

**Issue by prinprem** [ccxt/ccxt#12421]
OS: macOS Monterey 12.2.1
Programming Language version: JS, Node 17.7.1
CCXT version:1.77.18 & CCXT.Pro
Which exchange it is: Zipmex

Which method you're trying to call: withdraw()

...
const result = await exchange.withdraw(params.currency, params.amount, params.address, params.tag);
console.log(result);
...

When I call withdraw method I get this error "AuthenticationError: zipmex call signIn() method to obtain a session token". I already use authentication and it does work with other private API. How can I fix this?

**Comment by samgermain** [comment]
You need to call the `signIn` method before calling other private methods on zipmex, like

```
const exchange = ccxt.zipmex( ... )
exchange.signIn()
exchange.loadMarkets()
const result = await exchange.withdraw(params.currency, params.amount, params.address, params.tag);
console.log(result);
```
