### ISSUE TITLE
Cancel order causes all future commands to fail, for gdax and binance

### ISSUE THREAD

**Issue by hansvanzutphen** [ccxt/ccxt#1243]
For both gdax and binance, sending a limit buy/sell cancel causes all future calls (even non-API calls such as GetOrderBook) to fail.

I don't see this issue on hitbtc, yobit and wex. It's been a while since I tested Cryptopia but I didn't see it there either back then.

In both cases, the cancel itself succeeds, but after that every call fails.

In Binance, I get errors like this one:

> ccxt\ExchangeNotAvailable: binance GET https://api.binance.com/api/v1/depth?symbol=ETHBTC&limit=100 404 not accessible from this location at the moment in C:\winamp\COIN\ccxt2\ccxt\php\Exchange.php:682

Interestingly, the URL itself is fine (if you copy it to the browser it works).

In both cases, restarting the script fixes the issue (so it's not some blocking on the server side).

I'm using the latest ccxt (just did a git pull to update).

**Comment by kroitor** [comment]
Can you please paste a minimal but a complete snippet of code, for me to copypaste it and to reproduce the problem? We need to see it from initialization up to the point of failure. Also, please set `$exchange->verbose = true;` on the exchange instance for verbose logging.

**Comment by hansvanzutphen** [comment]
`<?php

  include "ccxt2/ccxt/ccxt.php";

  $sub = '\\ccxt\\binance';
  $exchange = new $sub();
  $exchange->apiKey = "KEY";
  $exchange->secret = "SECRET";
  $exchange->verbose = true;

  $raw_result = $exchange->fetch_order_book("NEO/BTC", array (($sub == "\\ccxt\\binance" ? 'limit' : 'count') => 100, ));
  var_dump($raw_result);
  sleep(1);
  
  $raw_result = $exchange->create_limit_buy_order("NEO/BTC", 10, .001);
  $orderid = $raw_result["id"];
  var_dump($raw_result);
  sleep(1);
  
  $raw_result = $exchange->cancelOrder($orderid, "NEO/BTC");
  var_dump($raw_result);
  sleep(1);

  $raw_result = $exchange->fetch_order_book("NEO/BTC", array (($sub == "\\ccxt\\binance" ? 'limit' : 'count') => 100, ));
  var_dump($raw_result);
  sleep(1);
    
?>
`

**Comment by hansvanzutphen** [comment]
And this is the output, with the var_dump()'s removed to keep it a bit shorter:

`\php\php test_binance_gdax.php

Request:
Array
(
    [0] => GET
    [1] => https://api.binance.com/api/v1/exchangeInfo
    [2] => Array
        (
        )

    [3] =>
)

Request:
Array
(
    [0] => GET
    [1] => https://api.binance.com/api/v1/depth?symbol=NEOBTC&limit=100
    [2] => Array
        (
        )

    [3] =>
)

Request:
Array
(
    [0] => POST
    [1] => https://api.binance.com/api/v3/order
    [2] => Array
        (
            [0] => X-MBX-APIKEY: KEY
            [1] => Content-Type: application/x-www-form-urlencoded
        )

    [3] => timestamp=1515956114771&recvWindow=100000&symbol=NEOBTC&quantity=10.0&type=LIMIT&side=BUY&price=0.001000&timeInForce=GTC&signature=SIG
)

Request:
Array
(
    [0] => DELETE
    [1] => https://api.binance.com/api/v3/order
    [2] => Array
        (
            [0] => X-MBX-APIKEY: KEY
            [1] => Content-Type: application/x-www-form-urlencoded
        )

    [3] => timestamp=1515956116029&recvWindow=100000&symbol=NEOBTC&orderId=21507816&signature=SIG
)

Request:
Array
(
    [0] => GET
    [1] => https://api.binance.com/api/v1/depth?symbol=NEOBTC&limit=100
    [2] => Array
        (
        )

    [3] =>
)
PHP Fatal error:  Uncaught ccxt\ExchangeNotAvailable: binance GET https://api.binance.com/api/v1/depth?symbol=NEOBTC&limit=100 404 not accessible from this location at the moment in C:\winamp\COIN\ccxt2\ccxt\php\Exchange.php:682
Stack trace:
#0 C:\winamp\COIN\ccxt2\ccxt\php\Exchange.php(861): ccxt\Exchange->raise_error('ExchangeNotAvai...', 'https://api.bin...', 'GET', 404, 'not accessible ...')
#1 C:\winamp\COIN\ccxt2\ccxt\php\Exchange.php(703): ccxt\Exchange->fetch('https://api.bin...', 'GET', Array, NULL)
#2 C:\winamp\COIN\ccxt2\ccxt\php\Exchange.php(707): ccxt\Exchange->fetch2('depth', 'public', 'GET', Array, NULL, NULL)
#3 [internal function]: ccxt\Exchange->request('depth', 'public', 'GET', Array)
#4 C:\winamp\COIN\ccxt2\ccxt\php\Exchange.php(646): call_user_func(Array, 'depth', 'public', 'GET', Array)
#5 [internal function]: ccxt\Exchange->ccxt\{closure}(Array)
#6 C:\winamp\COIN\ccxt2\ccxt\php\Exchange.php(1474): call_user_func_array(Object(Closure), Array)
#7 C:\winamp\COIN\ccxt2\ccxt\php\binance.php(414): ccxt\Exchang in C:\winamp\COIN\ccxt2\ccxt\php\Exchange.php on line 682

Fatal error: Uncaught ccxt\ExchangeNotAvailable: binance GET https://api.binance.com/api/v1/depth?symbol=NEOBTC&limit=100 404 not accessible from this location at the moment in C:\winamp\COIN\ccxt2\ccxt\php\Exchange.php:682
Stack trace:
#0 C:\winamp\COIN\ccxt2\ccxt\php\Exchange.php(861): ccxt\Exchange->raise_error('ExchangeNotAvai...', 'https://api.bin...', 'GET', 404, 'not accessible ...')
#1 C:\winamp\COIN\ccxt2\ccxt\php\Exchange.php(703): ccxt\Exchange->fetch('https://api.bin...', 'GET', Array, NULL)
#2 C:\winamp\COIN\ccxt2\ccxt\php\Exchange.php(707): ccxt\Exchange->fetch2('depth', 'public', 'GET', Array, NULL, NULL)
#3 [internal function]: ccxt\Exchange->request('depth', 'public', 'GET', Array)
#4 C:\winamp\COIN\ccxt2\ccxt\php\Exchange.php(646): call_user_func(Array, 'depth', 'public', 'GET', Array)
#5 [internal function]: ccxt\Exchange->ccxt\{closure}(Array)
#6 C:\winamp\COIN\ccxt2\ccxt\php\Exchange.php(1474): call_user_func_array(Object(Closure), Array)
#7 C:\winamp\COIN\ccxt2\ccxt\php\binance.php(414): ccxt\Exchang in C:\winamp\COIN\ccxt2\ccxt\php\Exchange.php on line 682
`

**Comment by hansvanzutphen** [comment]
By the way, if I create a new Exchange object after calling Cancel everything works fine. So I can do that as a workaround for the time being.

**Comment by kroitor** [comment]
To be honest, I don't really understand how you missed this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

I've tried to put a link to it is everywhere around... When someone submits an issue, it is in the body with a big **ATTENTION** word, and still you missed it somehow.

![screen-shot-2018-01-14-at-22 09 55](https://user-images.githubusercontent.com/1294454/34919628-3a3b61a0-f978-11e7-8c6b-56e669653e7f.jpg)

Your problem comes from a simple fact that you're not doing any rate-limiting at all. Therefore whatever the second request, it would fail.

To solve your problem:

1. Read this:
- https://github.com/ccxt-dev/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt-dev/ccxt/wiki/Manual#ddos-protection-by-cloudflare--incapsula
- https://github.com/ccxt-dev/ccxt/wiki/Manual#authentication
- https://github.com/ccxt/ccxt/blob/master/examples/php/built-in-rate-limiting-poller.php
- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

2. Add this:

```PHP
<?php

  include "ccxt2/ccxt/ccxt.php";

  $sub = '\\ccxt\\binance';
  $exchange = new $sub(array (

    'enableRateLimit' => true, // ←------------------------------- HERE

  ));
  $exchange->apiKey = "KEY";
  $exchange->secret = "SECRET";
  $exchange->verbose = true;

  $raw_result = $exchange->fetch_order_book("NEO/BTC", array (($sub == "\\ccxt\\binance" ? 'limit' : 'count') => 100, ));
  var_dump($raw_result);
  sleep(1);
  
  $raw_result = $exchange->create_limit_buy_order("NEO/BTC", 10, .001);
  $orderid = $raw_result["id"];
  var_dump($raw_result);
  sleep(1);
  
  $raw_result = $exchange->cancelOrder($orderid, "NEO/BTC");
  var_dump($raw_result);
  sleep(1);

  $raw_result = $exchange->fetch_order_book("NEO/BTC", array (($sub == "\\ccxt\\binance" ? 'limit' : 'count') => 100, ));
  var_dump($raw_result);
  sleep(1);
    
?>
```

3. To solve all your possible problems in future just read each symbol literally ;)

Hope it helps.

**Comment by hansvanzutphen** [comment]
Sorry about missing those things - it's the latest ccxt (I mentioned that somewhere) but I did indeed forget the rest:

- OS: Windows 10
- PHP 7.0 and 7.1 (I tried both)
- CCXT version: 1.10.709, but it also failed in older versions (I ran git pull 2 or 3 days ago to see if it would fix it, previous version was from late December).
- Exchange: Binance and GDAX

Anyway, adding rate limiting doesn't fix it. Beside that, I can send dozens of buy and sell orders without issues, it ONLY breaks as soon as I send a Cancel. And I've tried to pauze it for longer periods after the first error, that didn't help either. Creating a new Exchange instance (which shouldn't circumvent any rate limiting on the server end) does fix it though.

**Comment by kroitor** [comment]
Ok, I will look into it, sounds like we should clear some cache in curl... will get back to you with a fix, hopefully, soon.

**Comment by hansvanzutphen** [comment]
Great, No rush for me, I have it working now with creating a new exchange class after each cancel, so far it looks like it works without issues now.

**Comment by RuudBurger** [comment]
@hansvanzutphen check out my PR, it's an easy fix that should solve your issues
