### ISSUE TITLE
[kucoin] handleBalance messes trade and main accounts

### ISSUE THREAD

**Issue by krychla1** [ccxt/ccxt#12441]
Hi fellows!

WatchBalance -> HandleBalance of kucoin needs major fixing. The accounts in feeds have to be parsed (and stored?) by accountIds . Now everything gets mixed into trade accounts.

- CCXT.pro version: 1.0.33

e.g. this are 2 feeds for same coin, 1st is trading, 2nd is main account. Both ends up updating single trade account, resulting in invalid main and also trade account.

Trade balance = 1000MCT, move 2MCT to main balance:
```
2022-03-22T20:13:15.858Z onMessage {
  id: 'REDACTED',
  type: 'message',
  topic: '/account/balance',
  userId: 'REDACTED',
  channelType: 'private',
  subject: 'account.balance',
  data: {
    accountId: 'REDACTED..4221ed',  //TRADE ACCOUNT
    available: '998',
    availableChange: '-2',
    currency: 'MCT',
    hold: '0',
    holdChange: '0',
    relationContext: {},
    relationEvent: 'trade.transfer',
    relationEventId: 'REDACTED',
    time: '1647979995948',
    total: '998'
  }
}

2022-03-22T20:13:21.104Z onMessage {
  id: 'REDACTED',
  type: 'message',
  topic: '/account/balance',
  userId: 'REDACTED',
  channelType: 'private',
  subject: 'account.balance',
  data: {
    accountId: 'REDACTED..07c214e',   //MAIN ACCOUNT
    available: '2',
    availableChange: '2',
    currency: 'MCT',
    hold: '0',
    holdChange: '0',
    relationContext: {},
    relationEvent: 'main.transfer',
    relationEventId: 'REDACTED',
    time: '1647979995972',
    total: '2'
  }
}
```
Actual: main = undefined, trade = 2
Expected: main = 2, trade = 998

Check and rework please.
Thanks.

**Comment by carlosmiei** [comment]
Hello @krychla1 thanks for reporting it, there was indeed an issue resolving balance updates. A PR with the fix was already opened and will be merged soon.

Thank you!
