### ISSUE TITLE
Correct way to construct a request?

### ISSUE THREAD

**Issue by spliffli** [ccxt/ccxt#12440]
- OS: Manjaro Linux
- Programming Language version: Python 3.10.2
- CCXT version: 1.76.75

Hi there, I'm trying to extend the kucoin exchange, and I've made my own sub-class which succesfully inherits everything from `ccxt.kucoin`

```python
from ccxt.kucoin import kucoin


class kucoin_extended(kucoin):
    """
    - KuCoin doesn't have an API method for fetchBorrowRate.
    If it's possible to infer that from fetchMaxBorrowAmount (or any other way),
    then I will be able to implement this in a way that conforms to CCXT's standards.

    - fetchMaxBorrowAmount is a non-standard CCXT method that I made up. None of the other
    exchanges seem to have it, so any strategies which need it won't work on other exchanges
    (i.e. the N2SuperTrend strategy as it was written in the requirements).
        * It would also be possible to make another version of the strategy which doesn't
        rely on fetchMaxBorrowAmount, but I want to fulfil your requirements exactly as they
        were written, so I'm implementing it.
    """

    def describe(self):
        return self.deep_extend(super(kucoin_extended, self).describe(), {
            'id': 'kucoin_extended',
            'alias': True,
            'version': 'v0.0.1',
            'has': {
                # 'fetchBorrowRate': True,  # If/when this is implemented, I'll un-comment this line
                'fetchMaxBorrowAmount': True
            }
        })

    def fetch_max_borrow_amount(self, currency):
        """Fetches the maximum available borrow amount for a given currency"""
        self.load_markets()
        request = {
            # TODO: construct a request here
        }

        response = self.privateMarginAccount()
        pass

    def fetch_borrow_rate(self, currency):
        """Not working yet"""
        raise NotImplementedError("This isn't natively supported by KuCoin's API.\n"
                                  "It might be possible to implement this somehow")

```

Actually I just wanted to ask advice, and it's not about a particular re-producable error.

I have looked at kucoin and other exchange's source code and I see different ways that requests are made:

1.
```python
response = self.privateXYZ(self.extend(request, params))
```
2.
```python
response = getattr(self, method)(self.extend(request, params))
```
3.
```python
response = self.publicXYZ(params)
...
response = self.privateGetAccounts(params)
...
response = self.publicGetCurrencies(params)
```

At first I thought maybe only having the params was only for public API methods, but I can see it for private ones too.

Can someone explain the difference between these to me? As in, whether to supply only `params` as a param, or whether to use `self.extend`, or whether to use `getattr(self, method)(self.extend ...)`  I'm still learning programming and I couldn't really figure out what the appropriate way to form a request is. What's the criteria for deciding which way to use?

Thanks so much! I really love this project, and once I learn more about it I want to contribute to it.

I looked in the Exchange class at the definition of `extend` and I'm not really sure why this would need to be done? 
```python
    @staticmethod
    def extend(*args):
        if args is not None:
            result = None
            if type(args[0]) is collections.OrderedDict:
                result = collections.OrderedDict()
            else:
                result = {}
            for arg in args:
                result.update(arg)
            return result
        return {}
```

Sorry if this is a dumb question.

**Comment by pcriadoperez** [comment]
Hi @spliffli ,

We use self.extend to merge a request and params that may be passed in. This is regardless if the method called is private or public, that's why you see it can be used in both cases. (As your example 1 and 2)

In the cases there is no request object there is no need to use self.extend (As your example 3.)

For the question around when we use `getattr(self, method)` it is another way to call the same function.

 `self.privateXYZ(self.extend(request, params))` would be the same as `getattr(self, method)(self.extend(request, params))`  where `method = privateXYZ`
 
 I hope this helps! And feel fee to ask any more questions.

**Comment by kroitor** [comment]
Hi! First and foremost, the exchanges will have two kinds of the API:
- the implicit endpoints API (a list of all the endpoints for the exchange, and you can call any endpoint in an exchange-specific way)
- the unified API (a set of methods that call those implicit endpoints seamlessly for any exchange, if the exchange has this or that endpoint)

See these notes:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api
- https://github.com/ccxt/ccxt/wiki/Manual#unified-api

All implicit endpoints have just one `params` argument. The `extend` call is used to allow the user to override some or all the request params. Which is why all unified methods will have an extra `params` argument, that is fed to the implicit API as well.

In your case, the goal is to make a new unified method based on the implicit methods:

```Python
from ccxt.kucoin import kucoin


class kucoin_extended(kucoin):
    """
    - KuCoin doesn't have an API method for fetchBorrowRate.
    If it's possible to infer that from fetchMaxBorrowAmount (or any other way),
    then I will be able to implement this in a way that conforms to CCXT's standards.

    - fetchMaxBorrowAmount is a non-standard CCXT method that I made up. None of the other
    exchanges seem to have it, so any strategies which need it won't work on other exchanges
    (i.e. the N2SuperTrend strategy as it was written in the requirements).
        * It would also be possible to make another version of the strategy which doesn't
        rely on fetchMaxBorrowAmount, but I want to fulfil your requirements exactly as they
        were written, so I'm implementing it.
    """

    def describe(self):
        return self.deep_extend(super(kucoin_extended, self).describe(), {
            'id': 'kucoin_extended',
            'alias': True,
            'version': 'v0.0.1',
            'has': {
                # 'fetchBorrowRate': True,  # If/when this is implemented, I'll un-comment this line
                'fetchMaxBorrowAmount': True
            }
        })

    def fetch_max_borrow_amount(self, currency, params = {}):  # -------------------+
        """Fetches the maximum available borrow amount for a given currency"""    # ↓
        self.load_markets()                                                       # ↓
        request = {                                                               # ↓
            # TODO: construct a request here                                      # ↓
        }                                                                         # ↓
        response = self.privateMarginAccount(this.extend (request, params))  # ← ---+
        pass

    def fetch_borrow_rate(self, currency):
        """Not working yet"""
        raise NotImplementedError("This isn't natively supported by KuCoin's API.\n"
                                  "It might be possible to implement this somehow")
```

So a unified method takes the default request object, extends it with params-overrides (which are empty by default, but could be used to override a param by the user) and then the unified method passes the resulting extended params to the implicit method.

Hope that answers your question, let us know if not. Feel free to reopen it or just ask further questions if any.

**Comment by samgermain** [comment]
I don't understand what you're asking exactly, but I think on Kucoin the borrow and the lending interest rate are the same, and just referrred to as the "daily interest rate"

https://support.kucoin.plus/hc/en-us/articles/900002211683-The-descriptions-for-margin-trading
https://support.kucoin.plus/hc/en-us/articles/900002175423-How-to-Calculate-Pay-Interest-Automatically-Renewed-Rule

You can use the [implicit api](https://docs.ccxt.com/en/latest/manual.html#implicit-api) to get kucoins interest rates, they are a bit different from the other exchange `fetchBorrowRate` method becuase the rate isn't a static number, it depends on if someone is offering that currency for that rate

```
import ccxt

kucoin = ccxt.kucoin
coin = kucoin.currency('USDT')
response = kucoin.privateGetMarginMarket('{"currency": currency['id']}')
print(response)

{
  code: '200000',
  data: [
    { dailyIntRate: '0.00008', term: 7, size: '18488' },
    { dailyIntRate: '0.00009', term: 7, size: '36784' },
    ...
    { dailyIntRate: '0.02', term: 14, size: '34357' },
    { dailyIntRate: '0.02', term: 28, size: '34369' }
  ]
}
```

**Comment by spliffli** [comment]
Hi, thanks for your replies! I managed to actually figure it out anyway. KuCoin has two ways of doing this:
1. The first way is by querying the `margin/account` endpoint with a GET request. (https://docs.kucoin.com/#get-margin-account) and one of the responses is `maxBorrowSize`
2. The second way is by querying the `risk/limit/strategy` endpoint which requires a parameter `marginModel` that apparently only works when set to 'corss' (typo?) and not 'isolated' (https://docs.kucoin.com/#query-the-cross-isolated-margin-risk-limit) and one of the responses is `maxBorrowAmount`

Since KuCoin only has cross margin, I'm pretty sure maxBorrowSize & maxBorrowAmount are the same thing. Not sure why they are differently named.

I actually do have another question, and I can open a new issue if need be, which is: what are the conventions for actually borrowing?

I tried finding other exchanges which have margin trading and couldn't actually find anything like `privatePostBorrowOrder` which is I guess what the implicit method for KuCoin's 'POST /api/v1/margin/borrow' would be

**Comment by spliffli** [comment]
So, for the first endpoint margin/account, no params are required, and for the second one, `marginModel` is needed as a param. 

I still don't know what the purpose of `Exchange.extend` is though? Why would it make a difference if it's a normal dict or an OrderedDict?

**Comment by spliffli** [comment]
> Hi @spliffli ,
> 
> We use self.extend to merge a request and params that may be passed in. This is regardless if the method called is private or public, that's why you see it can be used in both cases. (As your example 1 and 2)
> 
> In the cases there is no request object there is no need to use self.extend (As your example 3.)
> 
> For the question around when we use `getattr(self, method)` it is another way to call the same function.
> 
> `self.privateXYZ(self.extend(request, params))` would be the same as `getattr(self, method)(self.extend(request, params))` where `method = privateXYZ`
> 
> I hope this helps! And feel fee to ask any more questions.

Yes, that helps a lot! thanks!
