### ISSUE TITLE
bittrex no market orders

### ISSUE THREAD

**Issue by scottie** [ccxt/ccxt#1244]
bittrex has no market orders anymore, only limit, make fix that uses limit as market or just remove it for its confusing to have the functionality still in CCXT when it dont exist,

**Comment by kroitor** [comment]
> make fix that uses limit as market or just remove it for its confusing to have the functionality still in CCXT when it dont exist

Bittrex disabled their market orders along ago, but we're not going to remove anything and we're not going to implicitly emulate market orders with limit orders. An unexpected implicit behaviour is much worse than an implicit exception. It will confuse the unaware users even more. We're now adding metainfo flags (`.has*`, `.has.*`) for detecting exchange capabilities programmatically. Hope it answers your question. Closing this for now if you don't mind, feel free to reopen it if needed, or jsut ask questions.

**Comment by scottie** [comment]
so just use useless code in there .....
the right thing to do would be emulate the market order and leave the call in.
just seems to me like you have no clue at all, thanks anyway ill make the required changes to local copy.

**Comment by scottie** [comment]
You have made it clear there is no point responding. I wont bother with merge request.

**Comment by jdimstrnate** [comment]
This may be outdated looking at previous tickets for this and twitter posts bittrex disabled it sometime ago however the documentation is back with market order and there is a flag under account -> api settings to enable it.  By default market orders are disabled.

https://bittrex.com/home/api
Trade Market - This allows the API key to place MARKET buy and sell orders - WARNING: Do no enable this unless you know what you're doing. Market buy/sells are extremely dangerous.

![bittrex_market_order](https://user-images.githubusercontent.com/5192578/36931315-47586a4e-1e68-11e8-9703-5e454b3833dc.PNG)

**Comment by kroitor** [comment]
@jdimstrnate this page: https://bittrex.com/Home/Api hasn't changed for a long time, and they still have just the "selllimit" and "buylimit" endpoints, no endpoints for market orders. You can emulate market orders with Bittrex as [described here](https://github.com/ccxt/ccxt/issues/1664#issuecomment-361933241), but they will not allow you to place a "market-type" order, even if you enable that permission (they will throw an API error saying that market orders are disabled).

**Comment by jdimstrnate** [comment]
Thanks for the feedback.  Will look into other post.
