### ISSUE TITLE
ccxt.base.errors.ExchangeError: binance {"code":-4061,"msg":"Order's position side does not match user's setting."}

### ISSUE THREAD

**Issue by flav1ooo** [ccxt/ccxt#12442]
account_binance = ccxt.binance({
    "apiKey": 'api',
    "secret": "Secret",
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future',  
        'hedgeMode': True
    }
})
params = {'positionSide': 'LONG'}
print("long order creating")
account_binance.create_order("XRP/USDT","market","buy",20,None,params)

account_binance.create_order("XRP/USDT","market","sell",20,None,params) # to closing long contract

And i got error that : ccxt.base.errors.ExchangeError: binance {"code":-4061,"msg":"Order's position side does not match user's setting."}

**Comment by kroitor** [comment]
@flav1ooo make sure to set your position mode to hedged before opening a hedged position. By default binance positions are one-way, use `set_position_mode` first:

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L4832

```Python
account_binance = ccxt.binance({
    "apiKey": 'api',
    "secret": "Secret",
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future',  
        'hedgeMode': True
    }
})
try:
    account_binance.set_position_mode('hedged=True, symbol="XRP/USDT')
except Exception as e:
    print(type(e).__name__, str(e))
params = {'positionSide': 'LONG'}
print("long order creating")
account_binance.create_order("XRP/USDT","market","buy",20,None,params)
```
Hope that answers your question, let us know if not.
