### ISSUE TITLE
KuCoin: {'code': '200000', 'msg': 'position internal error'} response when trying to place a margin order.

### ISSUE THREAD

**Issue by spliffli** [ccxt/ccxt#12457]
- Programming Language version: Python 3.10
- CCXT version: 1.76.75

Hi there, I'm trying to implement margin trading for KuCoin. So far, I've successfully managed to get borrowing to work, and with the borrowed currency I'm trying to open a margin trade but I'm getting 'position internal error' as a response.

```python
    def place_margin_order(self, side, symbol, size, type='market'):
        order_id = self.generate_order_id()

        if type == 'market':
            params = {
                "clientOid": order_id,
                "side": side,
                "symbol": symbol,
                "type": type,
                "size": size
            }
        elif type == 'limit':
            pass
        response = self.privatePostMarginOrder(params)

        pass
```

Here's what the response from KuCoin is:
```
{'code': '200000', 'msg': 'position internal error'}
```

For referenece, [this](https://docs.kucoin.com/#place-a-margin-order) is the part of their API which I\m trying to get to work.

This is how I'm calling it:

```python
self.sell_order = self.exchange.place_margin_order('sell', 'BTC/USDT', 4, 'market')
```
(It's the sandbox exchange btw, I **wish** I had 4 BTC to trade haha)

Any help would be much appreciated. I'm guessing from that message I'm providing the params incorrectly but I can't figure out how.

**Comment by spliffli** [comment]
I actually found one other example of this happening [here](https://github.com/Kucoin/kucoin-python-sdk/issues/50). It was just because I was passing the symbol as 'ETH/USDT' when in should instead be 'ETH-USDT'

The weird thing is that the code it returned, `200000` is ([supposed to mean success](https://github.com/Kucoin/kucoin-php-sdk/blob/4594f202a2082e55114574e96bbb879477d8f52a/src/ApiCode.php)). I accidentally did this before and the response from KuCoin said that was the case. So, maybe it's a bug on the kucoin side? If so, then I'll report it to them

**Comment by kroitor** [comment]
@spliffli thanks for your feedback!
