### ISSUE TITLE
Since timestamp exchange.iso8601() not syncing with actual trade timestamp

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#12452]
OS: Windows Server 2019 Datacenter
Programming Language version: Node.js 15.3.0
CCXT version: 1.49.98
Exchange: Kucoin
Method: exchange.iso8601()

Hello!

I noticed a problem that happens with the `exchange.iso8601()`. I will describe the steps. I am not sure the verbose output is needed or if this is a fundamental "problem" that has a solution. Otherwise I will create/add verbose if needed.

I have written comments in the code which tell the question:

```
    //First, I Declare the kucoin exchange
    const Exchange = ccxt["kucoin"];
    const exchange = new Exchange({ enableRateLimit: true, 'timeout': 30000 });

    //Second, I register the kucoin exchange iso8601 Date now which returned: 1647997843992
    var since = exchange.iso8601(Date.now()).toString(); 

    //Third, I now Create order that goes through instantly on kucoin
    var response = await exchange.createOrder("ETH/USDT", "limit", "buy", 0.002, 3000, {});

    //Now, I will try and return trades since: "1647997843992"
    var trades = await exchange.fetchClosedOrders("ETH/USDT", since, 10); //since: 1647997843992
```
However, no trades are returned but I tried to put 1 second back in time manually as since parameter instead `1647997842992`. Now I did return the trade on kucoin.

The thing is that the trade has registered this timestamp: `1647997843672`.
`1647997843672 `is `20 `milliseconds BEFORE `1647997843992` which I registered the moment before I created the trade.

Why does this happen. It seems that something is not syncing. Shouldn't I get the Absolute timestamp from the exchange?
Is there any safe approach to be sure to have the correct timestamp as the `since`?

Thank you!

**Comment by kroitor** [comment]
@jackpotcityco the `since` argument must be a number in milliseconds (not a string). Alternatively you should use `exchange.parse8601()` to parse an ISO8601 datetime string to a milliseconds-number, cause `exchange.iso8601` is used to convert from milliseconds to a string.

This should work, let us know if it does not help:

```JavaScript
    const Exchange = ccxt["kucoin"];
    const exchange = new Exchange({ enableRateLimit: true, 'timeout': 30000 });

    var since = exchange.milliseconds()

    var response = await exchange.createOrder("ETH/USDT", "limit", "buy", 0.002, 3000, {});

    var trades = await exchange.fetchClosedOrders("ETH/USDT", since, 10);
```

**Comment by jackpotcityco** [comment]
I understand, it has to be a number ofcourse in milliseconds and not a string. I will try to use the since as you put in like this instead and see how that works then. Thank you for pointing that out!

`const since = exchange.milliseconds()`
