### ISSUE TITLE
Market order in FTX exchange, how will fetch_my_trades() function behave? one trade per order ot could be multiple trades per order?

### ISSUE THREAD

**Issue by jamezun** [ccxt/ccxt#12464]
- OS:
- Programming Language version: python 3 latest
- CCXT version: latest

Let say if i place one single market order buy for 1 btc, and 0.5 trade at 39500 and 0.5 trade at 40000, for FTX exchange, when I use  def fetch_my_trades, will I fetch two trades(one for 39500, and one for 40000) or 1 trade at 39750(being the average trade price)?

**Comment by kroitor** [comment]
In general, each order can be filled with one or more trades, so your average order price will be the average of the trades' prices. Please, read this section of the Manual to understand the matching process better: https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades Hope that answers your question.
