### ISSUE TITLE
ftx load_markets can crash while raising exception 

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#12465]
- OS: linux
- Programming Language version: python
- CCXT version:1.73.70

We've received the following problem report for FTX lately (https://github.com/freqtrade/freqtrade/issues/6578)

Unfortunately, it doesn't reliably reproduce, therefore i can't really provide any/much code.
The problem itself also seemed to disappear after the bot restarted - so it's most likely a temporary error on the FTX side.

```
freqtrade_COM1d | Traceback (most recent call last):
freqtrade_COM1d |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
freqtrade_COM1d |     worker.run()
freqtrade_COM1d |   File "/freqtrade/freqtrade/worker.py", line 74, in run
freqtrade_COM1d |     state = self._worker(old_state=state)
freqtrade_COM1d |   File "/freqtrade/freqtrade/worker.py", line 114, in _worker
freqtrade_COM1d |     self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
freqtrade_COM1d |   File "/freqtrade/freqtrade/worker.py", line 139, in _throttle
freqtrade_COM1d |     result = func(*args, **kwargs)
freqtrade_COM1d |   File "/freqtrade/freqtrade/worker.py", line 152, in _process_running
freqtrade_COM1d |     self.freqtrade.process()
freqtrade_COM1d |   File "/freqtrade/freqtrade/freqtradebot.py", line 153, in process
freqtrade_COM1d |     self.exchange.reload_markets()
freqtrade_COM1d |   File "/freqtrade/freqtrade/exchange/exchange.py", line 360, in reload_markets
freqtrade_COM1d |     self._markets = self._api.load_markets(reload=True)
freqtrade_COM1d |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1516, in load_markets
freqtrade_COM1d |     markets = self.fetch_markets(params)
freqtrade_COM1d |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/ftx.py", line 597, in fetch_markets
freqtrade_COM1d |     raise BadResponse(self.id + " symbol '" + id + "' is a future contract but with invalid expiry datetime: " + expiryDatetime)
freqtrade_COM1d | TypeError: can only concatenate str (not "NoneType") to str
```

The proplem appears while raising the exception - so the returned exception is no longer a ccxt exception, but a TypeError (which we're currently not capturing for code within ccxt).

From looking at the code, there's 2 things that could be undefined in the affected line - `id` (in theory) - and `expiryDatetime` - but i'm not entirely sure how this is normally handled in ccxt - as the error appears while raising an error (actually while compiling the error string) - and not raising the error is not really an alternative.

https://github.com/ccxt/ccxt/blob/210f94844a3e34c2a41072670884702f8f701acd/js/ftx.js#L586

Now i'm perfectly fine with "please handle this client side" - but i think a bug that's not reported is guaranteed to not be fixed.

**Comment by samgermain** [comment]
It looks like this was fixed in PR #12549 so I'm going to close this issue
