### ISSUE TITLE
How can you set 'Take-profit and 'Stop-loss type and b on bitget?

### ISSUE THREAD

**Issue by hansoryyy** [ccxt/ccxt#12475]
Hello
I want to set Take profit and stop loss order of bitget. I am inquiring because there are no bitget Take profit and stop loss order  settings in the document, issue, and sample. The three examples I tried are as follows. Binance and FTX examples were applied, but they also did not work. I'd really appreciate it if you could give me an example of bitget Take profit and stop loss order configuration. I've been suffering from this problem for two weeks. Please help me. Thank you..

- OS: window10
- Programming Language version: python 3.10
- CCXT version: 1.76.72

```python
    
    apiKey = "????"
    secretKey = "???"
    password = '???'

    bitget = ccxt.bitget(config={
        'apiKey': apiKey,
        'secret': secretKey,
        'password': password,
        'options': {
            'defaultType': 'swap'
        }
    })
    
    target_coin_tiacker= 'BTC/USDT:USDT'
    amount = float(0.001)
    currentPrice = bitget.fetch_ticker('BTC/USDT:USDT')
    side = 'sell'
    
    # try 1
    type = 'lmit'
    result = bitget.create_order(target_coin_tiacker, type , side, amount, params={"triggerPrice": 43879, "reduceOnly": True})
    
    # try 2
    type = 'takeProfit'
    result = bitget.create_order(target_coin_tiacker, type , side, amount, params={"triggerPrice": 43879, "reduceOnly": True})

    # try 3
    type='TAKE_PROFIT_MARKET'
    result = bitget.create_order(target_coin_tiacker, type , side, amount, params={"stopPrice": 43879})
    
```

**Comment by IlliaMel** [comment]
Hello, have you found any solution to this problem?

**Comment by Amyaas1** [comment]
Bonjour, avez-vous trouvé une solution à ce problème ?
