### ISSUE TITLE
Coinbase  fetch_ohlcv() not supported yet

### ISSUE THREAD

**Issue by babydl-abc** [ccxt/ccxt#12471]
- OS: Windows
- Programming Language version: Python 3.9
- CCXT version: 1.64.6

```
import ccxt


exchange = ccxt.coinbase()
tickers = exchange.fetch_ohlcv('BTC/USD', timeframe='1H', limit=200)
d = pd.DataFrame(tickers, columns=['time', 'open', 'high', 'low', 'close', 'volume'])
```

```
error : 
fetch_ohlcvc  raise NotSupported('fetch_ohlcv() not supported yet')
ccxt.base.errors.NotSupported: fetch_ohlcv() not supported yet
```

**Comment by kroitor** [comment]
Use coinbasepro (the exchange), instead of coinbase (the wallet service). The latter was added to satisfy the Coinbase wallet usage requests. If you need the trading history, then you should use the Coinbase Pro exchange.
