### ISSUE TITLE
Huobi future LONG/SHORT orders

### ISSUE THREAD

**Issue by flav1ooo** [ccxt/ccxt#12483]
Im trying to make future orders in Huobi exchange :

For example i want to open a long contract and then close it

How can i open and close it? While closing should i use extra parameters ( for ex. i used reduceOnly in binance )?

Also the code that in below correct opening long contract syntax?

param= {"offset":"open"}
exchange.create_order("XRP/USDT:USDT","market","buy",2,None,param)

If you explain to me with some syntax examples i will be glad. Thank you !

**Comment by carlosmiei** [comment]
Hello @flav1ooo 
Few notes on your snippet:
- currently, Huobi does not support market orders for contracts so it should be limit
- To close an open contract you need to issue an order in the opposite direction, so in this case, you would need to set "offset": close and side="sell" to close it.

Please check this out, a complete example of a contract opening/closing that you can refer to
https://github.com/ccxt/ccxt/blob/192946916cc4f7d6f892eef50fb075ad0cd7ece3/examples/py/huobi-open-close-contract.py

**Comment by flav1ooo** [comment]
Should i add the parameter that reduce only when i want to close a contract?

**Comment by kroitor** [comment]
> Should i add the parameter that reduce only when i want to close a contract?

Yes, when closing a Huobi contract position, you should add a reduce_only flag, however, it is invalid in hedge mode and will work only with one-way positions.
