### ISSUE TITLE
kucoin watch_my_trades missing symbol and limit at line 630

### ISSUE THREAD

**Issue by leastchaos** [ccxt/ccxt#12492]
Hi

Kucoin watch_my_trades missing symbol and limit at line 630
![image](https://user-images.githubusercontent.com/64965782/160232195-a7cbcb05-4af2-47ca-a5eb-dcb4dd9ef95d.png)

```
  File "python3.10/site-packages/ccxtpro/kucoin.py", line 630, in watch_my_trades
    limit = trades.getLimit()
TypeError: ArrayCache.getLimit() missing 2 required positional arguments: 'symbol' and 'limit'
```

**Comment by kroitor** [comment]
@leastchaos hi! What is your version of CCXT Pro ?

**Comment by leastchaos** [comment]
the latest version, i took that screenshot directly from repository to confirm.
https://github.com/kroitor/ccxt.pro/blob/master/python/ccxtpro/kucoin.py

**Comment by leastchaos** [comment]
Sorry, there is another issue with the watch_my_trades. it is acting like watch_orders instead of watch_my_trades.
```
#pylint: disable=all
import asyncio
import ccxtpro
import sys
sys.stdout = open('watch_my_trade.txt', 'w')
print(ccxtpro.__version__)
symbol = 'BTC/USDT'
exchange: ccxtpro.Exchange = getattr(ccxtpro, 'kucoin')({
    'enableRateLimit': True,
    'apiKey': 'redact',
    'secret': 'redact',
    'password': 'redact',
    'newUpdates': False
})
exchange.verbose=True

async def main():
    while True:
        result = await exchange.watch_my_trades(symbol)
        print(result)
    await exchange.close()
```
```
[{'info': {'symbol': 'BTC-USDT', 'orderType': 'limit', 'side': 'buy', 'orderId': '623ed5350efd510001bccd1f', 'type': 'canceled', 'orderTime': 1648284981666806190, 'size': '0.00001', 'filledSize': '0', 'price': '44491.5', 'remainSize': '0', 'status': 'done', 'ts': 1648285011976931932}, 'symbol': 'BTC/USDT', 'id': '623ed5350efd510001bccd1f', 'clientOrderId': None, 'timestamp': 1648285011976, 'datetime': '2022-03-26T08:56:51.976Z', 'lastTradeTimestamp': None, 'type': 'limit', 'timeInForce': None, 'postOnly': None, 'side': 'buy', 'price': 44491.5, 'stopPrice': None, 'amount': 1e-05, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 1e-05, 'status': 'canceled', 'fee': None, 'trades': [], 'fees': []}, {'info': {'symbol': 'BTC-USDT', 'orderType': 'limit', 'side': 'buy', 'orderId': '623ed56415b4170001eeffe9', 'type': 'filled', 'orderTime': 1648285028225599526, 'size': '0.00001', 'filledSize': '0.00001', 'price': '44514.5', 'remainSize': '0', 'status': 'done', 'ts': 1648285028225599526}, 'symbol': 'BTC/USDT', 'id': '623ed56415b4170001eeffe9', 'clientOrderId': None, 'timestamp': 1648285028225, 'datetime': '2022-03-26T08:57:08.225Z', 'lastTradeTimestamp': None, 'type': 'limit', 'timeInForce': None, 'postOnly': None, 'side': 'buy', 'price': 44514.5, 'stopPrice': None, 'amount': 1e-05, 'cost': 0.445145, 'average': None, 'filled': 1e-05, 'remaining': 0.0, 'status': 'closed', 'fee': None, 'trades': [], 'fees': []}]
```
the structure returned seems to be order structure instead of trade structure. and it takes in every order update.
I understand it is probably due to the channel being the same for order event change and trade. 
but from the code, I see that it has parsed trade structure so it is weird.
and I think for this method, it should filter only filled orders back, if not it is no different from watch_orders

verbose
[watch_my_trade.txt](https://github.com/ccxt/ccxt/files/8355054/watch_my_trade.txt)

**Comment by carlosmiei** [comment]
Hello @leastchaos,
I'll take a look at that too but yes I think you're right, this seems to be an order update, not a trade one

**Comment by kroitor** [comment]
Fixed in kroitor/ccxt.pro#280, thanks for reporting!

**Comment by leastchaos** [comment]
@kroitor should i create a new issue to keep track of the 2nd issue for kucoin?
watch_my_trade method is acting like watch_orders instead of watching trade.

> Sorry, there is another issue with the watch_my_trades. it is acting like watch_orders instead of watch_my_trades. CCXT Version: 1.0.42 OS: Linux Python 3.10
> 
> ```
> #pylint: disable=all
> import asyncio
> import ccxtpro
> import sys
> sys.stdout = open('watch_my_trade.txt', 'w')
> print(ccxtpro.__version__)
> symbol = 'BTC/USDT'
> exchange: ccxtpro.Exchange = getattr(ccxtpro, 'kucoin')({
>     'enableRateLimit': True,
>     'apiKey': 'redact',
>     'secret': 'redact',
>     'password': 'redact',
>     'newUpdates': False
> })
> exchange.verbose=True
> 
> async def main():
>     while True:
>         result = await exchange.watch_my_trades(symbol)
>         print(result)
>     await exchange.close()
> ```
> 
> ```
> [{'info': {'symbol': 'BTC-USDT', 'orderType': 'limit', 'side': 'buy', 'orderId': '623ed5350efd510001bccd1f', 'type': 'canceled', 'orderTime': 1648284981666806190, 'size': '0.00001', 'filledSize': '0', 'price': '44491.5', 'remainSize': '0', 'status': 'done', 'ts': 1648285011976931932}, 'symbol': 'BTC/USDT', 'id': '623ed5350efd510001bccd1f', 'clientOrderId': None, 'timestamp': 1648285011976, 'datetime': '2022-03-26T08:56:51.976Z', 'lastTradeTimestamp': None, 'type': 'limit', 'timeInForce': None, 'postOnly': None, 'side': 'buy', 'price': 44491.5, 'stopPrice': None, 'amount': 1e-05, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 1e-05, 'status': 'canceled', 'fee': None, 'trades': [], 'fees': []}, {'info': {'symbol': 'BTC-USDT', 'orderType': 'limit', 'side': 'buy', 'orderId': '623ed56415b4170001eeffe9', 'type': 'filled', 'orderTime': 1648285028225599526, 'size': '0.00001', 'filledSize': '0.00001', 'price': '44514.5', 'remainSize': '0', 'status': 'done', 'ts': 1648285028225599526}, 'symbol': 'BTC/USDT', 'id': '623ed56415b4170001eeffe9', 'clientOrderId': None, 'timestamp': 1648285028225, 'datetime': '2022-03-26T08:57:08.225Z', 'lastTradeTimestamp': None, 'type': 'limit', 'timeInForce': None, 'postOnly': None, 'side': 'buy', 'price': 44514.5, 'stopPrice': None, 'amount': 1e-05, 'cost': 0.445145, 'average': None, 'filled': 1e-05, 'remaining': 0.0, 'status': 'closed', 'fee': None, 'trades': [], 'fees': []}]
> ```
> 
> the structure returned seems to be order structure instead of trade structure. and it takes in every order update. I understand it is probably due to the channel being the same for order event change and trade. but from the code, I see that it has parsed trade structure so it is weird. and I think for this method, it should filter only filled orders back, if not it is no different from watch_orders
> 
> verbose [watch_my_trade.txt](https://github.com/ccxt/ccxt/files/8355054/watch_my_trade.txt)

**Comment by carlosmiei** [comment]
> @kroitor should i create a new issue to keep track of the 2nd issue for kucoin? watch_my_trade method is acting like watch_orders instead of watching trade.
> 
> > Sorry, there is another issue with the watch_my_trades. it is acting like watch_orders instead of watch_my_trades. CCXT Version: 1.0.42 OS: Linux Python 3.10
> > ```
> > #pylint: disable=all
> > import asyncio
> > import ccxtpro
> > import sys
> > sys.stdout = open('watch_my_trade.txt', 'w')
> > print(ccxtpro.__version__)
> > symbol = 'BTC/USDT'
> > exchange: ccxtpro.Exchange = getattr(ccxtpro, 'kucoin')({
> >     'enableRateLimit': True,
> >     'apiKey': 'redact',
> >     'secret': 'redact',
> >     'password': 'redact',
> >     'newUpdates': False
> > })
> > exchange.verbose=True
> > 
> > async def main():
> >     while True:
> >         result = await exchange.watch_my_trades(symbol)
> >         print(result)
> >     await exchange.close()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > [{'info': {'symbol': 'BTC-USDT', 'orderType': 'limit', 'side': 'buy', 'orderId': '623ed5350efd510001bccd1f', 'type': 'canceled', 'orderTime': 1648284981666806190, 'size': '0.00001', 'filledSize': '0', 'price': '44491.5', 'remainSize': '0', 'status': 'done', 'ts': 1648285011976931932}, 'symbol': 'BTC/USDT', 'id': '623ed5350efd510001bccd1f', 'clientOrderId': None, 'timestamp': 1648285011976, 'datetime': '2022-03-26T08:56:51.976Z', 'lastTradeTimestamp': None, 'type': 'limit', 'timeInForce': None, 'postOnly': None, 'side': 'buy', 'price': 44491.5, 'stopPrice': None, 'amount': 1e-05, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 1e-05, 'status': 'canceled', 'fee': None, 'trades': [], 'fees': []}, {'info': {'symbol': 'BTC-USDT', 'orderType': 'limit', 'side': 'buy', 'orderId': '623ed56415b4170001eeffe9', 'type': 'filled', 'orderTime': 1648285028225599526, 'size': '0.00001', 'filledSize': '0.00001', 'price': '44514.5', 'remainSize': '0', 'status': 'done', 'ts': 1648285028225599526}, 'symbol': 'BTC/USDT', 'id': '623ed56415b4170001eeffe9', 'clientOrderId': None, 'timestamp': 1648285028225, 'datetime': '2022-03-26T08:57:08.225Z', 'lastTradeTimestamp': None, 'type': 'limit', 'timeInForce': None, 'postOnly': None, 'side': 'buy', 'price': 44514.5, 'stopPrice': None, 'amount': 1e-05, 'cost': 0.445145, 'average': None, 'filled': 1e-05, 'remaining': 0.0, 'status': 'closed', 'fee': None, 'trades': [], 'fees': []}]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the structure returned seems to be order structure instead of trade structure. and it takes in every order update. I understand it is probably due to the channel being the same for order event change and trade. but from the code, I see that it has parsed trade structure so it is weird. and I think for this method, it should filter only filled orders back, if not it is no different from watch_orders
> > verbose [watch_my_trade.txt](https://github.com/ccxt/ccxt/files/8355054/watch_my_trade.txt)

@leastchaos I don't think it is necessary

**Comment by carlosmiei** [comment]
@leastchaos fyi I opened a PR fixing Kucoin's `watchMyTrades`
