### ISSUE TITLE
defining newUpdates in initializing exchange causes watch_balance/fetch_balance error?

### ISSUE THREAD

**Issue by leastchaos** [ccxt/ccxt#12525]
- OS: linux
- Programming Language version: python 3.10
- CCXT version: 1.0.47

Not sure if I been doing it wrongly but I just realised that if i define newUpdates, I will have error in any balance method?
I been using this boiler plate to try out new ccxt code but i just realised if i use this for fetch_balance and watch_balance method it will fail.  

```
#pylint: disable=all
import asyncio
import ccxtpro
import sys
# sys.stdout = open('watch_my_trade.txt', 'w')
print(ccxtpro.__version__)
symbol = 'BTC/USDT'
exchange: ccxtpro.Exchange = getattr(ccxtpro, 'kucoin')({ # tried with ascendex and gateio also
    'enableRateLimit': True,
    'apiKey': 'redact',
    'secret': 'dredact',
    'password': 'redact',
    'newUpdates': False
})
exchange.verbose=False

async def main():
    while True:
        result = await exchange.fetch_balance(symbol) # await exchange.watch_balance(symbol)
        print(result)
    await exchange.close()

asyncio.run(main())

```

```

    result = await exchange.fetch_balance(symbol)
  File "/root/miniconda3/envs/_/lib/python3.10/site-packages/ccxt/async_support/kucoin.py", line 1914, in fetch_balance
    response = await self.privateGetAccounts(self.extend(request, params))
  File "/root/miniconda3/envs/_/lib/python3.10/site-packages/ccxt/base/exchange.py", line 888, in extend
    result.update(arg)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```
verbose
[balance_test.txt](https://github.com/ccxt/ccxt/files/8364127/balance_test.txt)

**Comment by carlosmiei** [comment]
Hi again @leastchaos,

You're having this crash because a wrong parameter is being passed to fetchBalance/watchBalance.

Currently, you're doing:
`await exchange.fetch_balance(symbol)`

However, the only accepted argument for both methods is an object (params). In this case, symbol and fetchBalance do not look like a normal combination can that be the bug on your end?

I'm going to close this issue feel free to reopen it if anything 🙂

**Comment by leastchaos** [comment]
@carlosmiei ahhh yes sorry, i have only recently been using the methods with symbol, i forgotten balance does not have symbol. Thank you.
