### ISSUE TITLE
Questions about `active`, `deposit`, `withdraw `and `withdraw fees` for a token

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#12529]
OS: Windows Server 2019 Datacenter
Programming Language version: Node.js 15.3.0
CCXT version: 1.49.98
Exchange: Binance and All Exchanges
Method: exchange.currencies['USDT']

Hello!

I have a few questions about `active`, `deposit`, `withdraw `and `withdraw fees` for a token.

1. Is it true that Binance doesn't return information about this as in Example 1?
2. Looking at Example 2 with `Kucoin `and the token `USDT`. Does `deposit: true` and `withdraw: true` stand for that `USDT` is possible to deposit to the exchange and withdraw from the exchange. If so how reliable is this to use in order to automate this process?
3. What does `active` stand for. Does it stand for that it is `active` for trading at this very moment (It has nothing to do with `deposit `and `withdraw` as in my previous question?)
4. I wonder about the withdrawal fee. In Example 2, it says: `35`. Now I know that this is returned for the `ETH` network(but network is not seen in the response?). For example `TRX` does also exist for `USDT` for kucoin. How is it possible to return the withdrawal fee for `TRX` network for example to also be sure what network the info belong to?
5. In Example 2, this is seen: `info{ withdrawalMinSize: '20' }`. But this info is not found in the unified field. Is this possible to return in any unified manner?

_6. I know the question often can be closed right away. I wonder if it still is possible to ask something more if needed even if the question is closed? (Just to know in general)_

Many thanks!

Example1:
```
const Exchange = ccxt["binance"];
const exchange = new Exchange({ enableRateLimit: true, 'timeout': 10000 }); 
var response = exchange.currencies['USDT'];
console.log(response);
```

Response:
{ id: 'USDT', numericId: undefined, code: 'USDT', precision: 8 }

Example2:
```
const Exchange = ccxt["kucoin"];
const exchange = new Exchange({ enableRateLimit: true, 'timeout': 10000 }); 
var response = exchange.currencies['USDT'];
console.log(response);
```

Response:
{
  id: 'USDT',
  name: 'Tether',
  code: 'USDT',
  precision: 8,
  info: {
    currency: 'USDT',
    name: 'USDT',
    fullName: 'Tether',
    precision: 8,
    confirms: 12,
    contractAddress: '',
    withdrawalMinSize: '20',
    withdrawalMinFee: '35',
    isWithdrawEnabled: true,
    isDepositEnabled: true,
    isMarginEnabled: true,
    isDebitEnabled: true
  },
  active: true,
  deposit: true,
  withdraw: true,
  fee: 35,
  limits: {
    leverage: { min: undefined, max: undefined },
    amount: { min: undefined, max: undefined },
    price: { min: undefined, max: undefined },
    cost: { min: undefined, max: undefined }
  }
}

**Comment by kroitor** [comment]
> 1. Is it true that Binance doesn't return information about this as in Example 1?

No. It can return that information, but it requires authentication for accessing that information, so you have to provide your api keys to the exchange constructor as documented in the Manual.

> 2. Looking at Example 2 with `Kucoin `and the token `USDT`. Does `deposit: true` and `withdraw: true` stand for that `USDT` is possible to deposit to the exchange and withdraw from the exchange. If so how reliable is this to use in order to automate this process?

The values of `deposit` and `withdraw` are either undefined or they are boolean (`true` or `false`) values based on the information from the exchange API. That information is as reliable as is the underlying exchange.

> 3. What does `active` stand for. Does it stand for that it is `active` for trading at this very moment (It has nothing to do with `deposit `and `withdraw` as in my previous question?)

In a `currency` active usually means that the currency is depositable and withdrawable at least, and sometimes, if it's tradeable or delisted. In a `market` the `active` flag means that the market is tradeable. Thus, a currency can be inactive, and then you cannot deposit or withdraw that currency, but you can still trade that currency if the corresponding market is active.

> 4. I wonder about the withdrawal fee. In Example 2, it says: `35`. Now I know that this is returned for the `ETH` network(but network is not seen in the response?). For example `TRX` does also exist for `USDT` for kucoin. How is it possible to return the withdrawal fee for `TRX` network for example to also be sure what network the info belong to?

This aspect is not entirely unified in CCXT yet, however, you will see the corresponding `network`, `currency`, and `fee`, ad most of the time the exchanges charge fees in the same currency on the same network as the funds you're withdrawing.

> 5. In Example 2, this is seen: `info{ withdrawalMinSize: '20' }`. But this info is not found in the unified field. Is this possible to return in any unified manner?

Yes, check currency limits: 

- https://github.com/ccxt/ccxt/wiki/Manual#currency-structure
- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

> _6. I know the question often can be closed right away. I wonder if it still is possible to ask something more if needed even if the question is closed? (Just to know in general)_

Yes, you can still answer questions on closed issues.

**Comment by shfkv** [comment]
Hi! Were you able to get information about fees and networks on Binance?
