### ISSUE TITLE
fetchMyTrades last 100 trades with all symbols

### ISSUE THREAD

**Issue by Calugarul** [ccxt/ccxt#12527]
I know that I need to specify a trading pair like 'JASMY/USDT' but I want to get the last 20 trades without specifying a symbol. Like that to give all tradings with all trading pairs from the last 20 transactions. Of course, I don't want to abuse it with thousands of transactions, etc, but merely to be able to get the JSON and transfer them to my database. Is there a way to do this?

The code I have:

```
if (binanceEx.has['fetchMyTrades']) {
            const trades = await binanceEx.fetchMyTrades ('', binanceEx.parse8601 ('2022-03-01 00:00:00') , 20, undefined);
            console.log('Orders: ', trades);
}
```

**Comment by kroitor** [comment]
> Is there a way to do this?

No, you have to iterate over those symbols. The exchanges just don't have a corresponding endpoint to return all trades at once for all symbols in a single mixed response, even if you request a limited set of those.
