### ISSUE TITLE
about trade in yobit exchange platform

### ISSUE THREAD

**Issue by cimp43** [ccxt/ccxt#12528]
i have already download ccxt file
and i just want to know how how to  place un order and cancel order i mean what should i wrote if i want to place buy or sell order 
i want the method
and one more thing wich file that i have to put my secret key and api key
so please help me

**Comment by kroitor** [comment]
Please, read the Manual on how to use CCXT:

- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/
- https://docs.ccxt.com

Also, see the examples here:

- https://github.com/ccxt/ccxt/tree/master/examples/
- https://github.com/ccxt/ccxt/tree/master/examples/#see-also
