### ISSUE TITLE
[BUG] invalid limits on Gate.io

### ISSUE THREAD

**Issue by dawadam** [ccxt/ccxt#12544]
Hi
It seems that there is a problem with the limit data transmitted for the Gate.io exchange.

For example for LUNA/USDT

The minimum amount passed by ccxt is **25**:

```
limits: {
  leverage: { min: 1, max: 3 },
  amount: { min: 25, max: undefined },
  price: { min: undefined, max: undefined },
  cost: { min: 1, max: undefined }
}
```

While according to Gate.io API it is **0.0001**

[https://data.gateio.co/api2/1/marketinfo](https://data.gateio.co/api2/1/marketinfo)

It's like that for a lot of pairs.

I'm using ccxt 1.77.36 on typescript.

**Comment by kroitor** [comment]
You're looking at the outdated v2 API.

The new Gate.io v4 API is here:

- https://api.gateio.ws/api/v4/margin/currency_pairs

<img width="1679" alt="Screenshot 2022-03-29 at 22 11 02" src="https://user-images.githubusercontent.com/1294454/160689083-ce955a5b-dac7-4b26-abc5-eaa4ed065afb.png">

**Comment by kroitor** [comment]
Will check again shortly.

**Comment by dawadam** [comment]
Data are not valid.
I'm testing make order of 0.01 LUNA/USDT and he passes.
If minimum amount of LUNA is 25$, cost 2500$ actualy.

**Comment by kroitor** [comment]
@dawadam i've pushed a fix for it in CCXT 1.77.49+. Let me know if you still have this issue after upgrading.

**Comment by dawadam** [comment]
Yes, it working, good job.

**Comment by kroitor** [comment]
@dawadam thanks for your feedback and for pointing it out!
