### ISSUE TITLE
Kucoin: Creates empty order instead of raising BadSymbol exception 

### ISSUE THREAD

**Issue by SmartManoj** [ccxt/ccxt#12550]
- OS:
- Programming Language version: py
- CCXT version: 1.77.49

```
import ccxt

connection = ccxt.kucoin({
   
})

connection.load_markets()
connection.verbose = 1
my_trades = connection.create_order('URUS/USDT', 'market', 'buy', amount=None, params={'funds': 5})
print((my_trades))

```

```
 {"code":"400600","msg":"validation.createOrder.symbolNotAvailable"}
{'amount': None,
 'average': None,
 'clientOrderId': '1c0471e6-6693-4252-8ed6-aa4549af0e19',
 'cost': 5.0,
 'datetime': '2022-03-30T08:39:44.496Z',
 'fee': None,
 'filled': None,
 'id': None,
 'info': {},
 'lastTradeTimestamp': None,
 'price': None,
 'remaining': None,
 'side': 'buy',
 'status': None,
 'symbol': 'URUS/USDT',
 'timestamp': 1648629584496,
 'trades': None,
 'type': 'market'}
```

**Comment by ttodua** [comment]
You are using :
```my_trades = connection.create_order('URUS/USDT', 'market', 'buy', amount=None, params={'funds': 5})```
but look, you miss the 5th argument of function `price`, and the `params` argument should be 6th:
```my_trades = connection.create_order('URUS/USDT', 'market', 'buy', amount=None, price=12345,  params={'funds': 5})```
So, your usage leads to unexpected results, and maybe CCXT doesn't have a handler for that specific incorrect usage.
Let me know if any issue exists, when you correct the code

**Comment by SmartManoj** [comment]
> You are using : `my_trades = connection.create_order('URUS/USDT', 'market', 'buy', amount=None, params={'funds': 5})` but look, you miss the 5th argument of function `price`, and the `params` argument should be 6th: `my_trades = connection.create_order('URUS/USDT', 'market', 'buy', amount=None, price=12345, params={'funds': 5})` So, your usage leads to unexpected results, and maybe CCXT doesn't have a handler for that specific incorrect usage. Let me know if any issue exists, when you correct the code

price is not needed for market order. Also the coin is not listed at the time.

**Comment by SmartManoj** [comment]
```
fetch Request: kucoin POST http://localhost:8080/kucoin/api/v1/orders RequestHeaders: {'KC-API-KEY-VERSION': '2', 'KC-API-KEY': '', 'KC-API-TIMESTAMP': '1649336475275', 'Content-Type': 'application/json', 'KC-API-PASSPHRASE': '=', 'KC-API-SIGN': '=', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} RequestBody: {"clientOid":"2eacb890-9ddd-47cb-b4e5-a75e0263939e","side":"buy","symbol":"RPC-USDT","type":"limit","size":"53.625","price":"0.55944"}

fetch Response: kucoin POST http://localhost:8080/kucoin/api/v1/orders 200 ResponseHeaders:
```

Returns empty order for this too when there is no response.
version : 1:77:41

**Comment by ttodua** [comment]
@SmartManoj 
Sorry for delay, I couldn't get to this issue back till date.
I'll be updating the error-codes, as seems that error code `validation.createOrder.symbolNotAvailable` is not included in ccxt, and next time that happens, it will throw BadSymbol exception. 
I am not sure how to reproduce it. You might provide 'verbose' output next time when that happens (not only `responseHeaders` but also response body).

about empty order - ccxt is built such as if response doesn't fall into exception category, and instead returns the empty body (i havent seen the resposne body in your replies, that's why I am talking in general) the ccxt will not throw exception and will still return unified response (but of course, in that case all properties will be missing). that's why I need to see what is actual response in that exceptional occasions, so I could consider that response as buggy response and include that in ccxt too.

**Comment by kroitor** [comment]
@SmartManoj please, paste your complete verbose request+response (you can remove your credentials if necessary):

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.kucoin({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'password': 'YOUR_API_PASSWORD',
})

exchange.load_markets()
exchange.verbose = True
order = exchange.create_order('URUS/USDT', 'market', 'buy', amount=None, params={'funds': 5})
print(order)
```

**Comment by ttodua** [comment]
_as a side-note: when exchange supports market-order by quote-currency amounts, you can also use unified `cost` param instead of `funds` (or an exchange-specific param-name, if you dont know what, as `cost` is an unified name for it)_

**Comment by SmartManoj** [comment]
> ```
> fetch Response: kucoin POST http://localhost:8080/kucoin/api/v1/orders 200 ResponseHeaders:
> ```

Response output : Just empty

**Comment by SmartManoj** [comment]
> > ```
> > fetch Response: kucoin POST http://localhost:8080/kucoin/api/v1/orders 200 ResponseHeaders:
> > ```
> 
> Response output : Just empty

This is the verbose output.
Related issue: https://stackoverflow.com/a/7491149

**Comment by SmartManoj** [comment]
> 1. does this happen only for those symbols that are not yet listed

During 1st min of listing

> 2. in what interval do you send requests to exchange (i.e. every 100ms or once in i.e. 10 seconds)

100ms as default ratelimit

> 3. does it happen on each of the request, or only one of the X request ends in that way, while other return expected response

only some

> 4. do you have any other active connection (i.e. websockets) to kucoin at that moment, or making other queries from same ip

yes

**Comment by ttodua** [comment]
according to your answers, I highly suspect the issue might be from kucoin API engine side. It's known [issue that kucoin engine has](https://github.com/ccxt/ccxt/issues/10273). Possible remedies:
1) dont be edge of ratelimit - increase interval to 110-120 (or even more) MS if your latency to server is not very low.
2) I've myself experienced that issue myself. Orders sent on kucoin api during first seconds of the listing ends up in throttled (on exchange side) queue, and either timeout-ing or returning response after 60-120 seconds. I dont know at this moment, but it might not be surprising if kucoin hasnt solved their engine issue 
3) dont have any Websocket open connection at that moment, when you make REST requests, kucoin API engine had obvious problems and misbehavior a few months ago. So, try not to use an WS connection during first few seconds.

the above steps might help to succeed in order placements.
