### ISSUE TITLE
Binance fetch_tickers ['last'] is empty 

### ISSUE THREAD

**Issue by aReigoto** [ccxt/ccxt#1257]
- OS: osx 10.11.6
- Programming Language version: Python 2.7.11
- CCXT version: 1.10.706
- Exchange: binance
- Method: ccxt.binance().fetch_tickers()

Just notice that this key ['last'] is empty and not only for BTC/USDT:
```python
>>> ccxt.binance().fetch_tickers()['BTC/USDT']['last']
>>>
```

and here there is no problem:
```python
>>> ccxt.binance().fetch_ticker('BTC/USDT')['last']
>>> 13078.96
```
on CCXT version:1.10.567 both methods returned the same value

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/issues/1177

**Comment by aReigoto** [comment]
Thanks that was quick !!!

**Comment by kroitor** [comment]
@aReigoto you're welcome. Please, note, that we are likely to rework it again very soon, as described [here](https://github.com/ccxt/ccxt/issues/1177#issuecomment-356976015), and we will restore the old behaviour of fetchTickers for Binance in one of upcoming commits.
