### ISSUE TITLE
Transfer USDT between spot and futures

### ISSUE THREAD

**Issue by euphrates85** [ccxt/ccxt#12576]
- OS: Windows 
- Programming Language version: 3.10
- CCXT version: 1.77.62

```
import time
start = time.time()
exchange.sapi_post_futures_transfer({
    'asset': 'USDT',
    'amount': '10',
    'type': 2,
})
end = time.time()
```
I want to take a long position in the spot market and a short position in the future market. To do that, I have to make a USDT transfer between spot and future wallets. My question is:

Execution time of the above transfer code is around 1 second. Except for USDT transfer between wallets, my entire code, including creating orders, takes milliseconds. Since USDT transfer takes 1 second, is there a risk that the order execution code runs before USDT transfer so the order can not be implemented due to lack of funds? If so, what would be the best solution?

Maybe I should clarify my question
Let's say that I am in full long position and I receive short signal. So I have to close all long positions, transfer USDT to future wallet and open short positions. Transferring USDT takes around 1 second. I wonder if there is a risk that execution order code(opening short positions) runs before money transfer? If it happens there wont be enough funds to open short position.

**Comment by ttodua** [comment]
as I assume, you are using synchronous code. If so, it doesn't matter if transfer takes 800MS, 1200MS or 1000MS , as long as you execute trade after transfering. 
if you run asynchronous code, then right - it will need some extra steps - when you get the 'short' signal, then you can asynchronously initiate the transfer, and paralelly, i.e. every 200MS, check the balance to ensure the funds are received.

But again, if you run synchronous code, then I don't see why it would be an issue, i.e.:
````
if (short_signal_received) {
    exchange.sapi_post_futures_transfer({...});
    exchange.create_order(.....); //so, order will be only fired after the above line finishes its work.
}
````
Let me know if i misunderstood the question.

**Comment by samgermain** [comment]
You can just use the unified `transfer` method

```
import ccxt
import pprint

print('CCXT Version:', ccxt.__version__)

binance = ccxt.binance()
transfer = binance.transfer(USDT, 0.01, spot, future)
pprint(transfer)
```

**Comment by euphrates85** [comment]
Thank you very much.  I am using synchronous code. I was worried that the code would continue to run without waiting for the money to be physically transferred between wallets. But it seems i shouldn't worry about that
