### ISSUE TITLE
In kucoin create order, costToPrecision  is not used and params['size'] is ignored

### ISSUE THREAD

**Issue by SmartManoj** [ccxt/ccxt#12588]
amountToPrecision is used instead of costToPrecision 
https://github.com/ccxt/ccxt/blob/a1b71becca0211274f6f4ec886e8848627070316/js/kucoin.js#L1142

params['size'] is ignored here. Or should one use only amount param?
https://github.com/ccxt/ccxt/blob/a1b71becca0211274f6f4ec886e8848627070316/js/kucoin.js#L1145-L1146

**Comment by samgermain** [comment]
So above the line ` costString = this.amountToPrecision (symbol, quoteAmount); ` you'll notice a comment which says `             // kucoin uses base precision even for quote values` so using `amountToPrecision` for the quote value is correct.

`params['size'] is ignored here. Or should one use only amount param?`

That's correct, you need to use the unified `amount` parameter if you want the CCXT method to take care of precision adjustments for you. If you pass `params['size']` to the `createOrder` method, that parameter will still be sent to the exchange, but it will be sent as is, and you would have to adjust the precision yourself, so it makes more sense to just use the `amount` parameter

**Comment by samgermain** [comment]
I'm going to close this issue, but feel free to reopen it if you have any more questions
