### ISSUE TITLE
Can't get withdrawal fees of any exchange

### ISSUE THREAD

**Issue by radadan** [ccxt/ccxt#12597]
I am working on a code that analyzes the markets of 8 different exchanges. Under no circumstances am I able to obtain withdrawal fees for a particular market.
While using the proposed function on the documentation for withdrawal fees:
```
exchange.currencies['ETH']['fee']
```
 I give an error for all 8 exchanges:
```
currency = exchange.currencies['ETH']['fee']
KeyError: 'fee'
```
Is there any way to get these fees?

**Comment by kroitor** [comment]
@radadan Hi!

- Can you please list out the exchanges in question ?
- If possible, please, paste the code you use to initialize the exchange instances (or a complete short snippet without your keys) – https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by radadan** [comment]
These are the exchanges tried: Binance, bitflyer, bitfinex, bittrex, coinbase, gemini, liquid, poloniex and kraken. 
This is the code I have used:
```
exchange = ccxt.binance()
markets = exchange.load_markets()
currency = exchange.currencies['BTC']['fee']
pprint(currency)
```
And this is the error I get for all the exchanges: 
```
Traceback (most recent call last):
  File "C:/Users/prova.py", line 9, in <module>
    currency = exchange.currencies['BTC']['fee']
KeyError: 'fee'

```

**Comment by radadan** [comment]
@kroitor thanks, I forgot to mention you

**Comment by Epikem** [comment]
I can't find any way to get withdrawal fees in advance.
Is there anyone how to handle this problem?

```py
# test code:

  withdrawal_fee_usdt = client_a.currencies['USDT']
  logger.info(f'withdrawal fee usdt: {withdrawal_fee_usdt}')

  withdrawal_fee_usdt = client_b.currencies['ETH']
  logger.info(f'withdrawal fee usdt: {withdrawal_fee_usdt}')

# ftx
2022-05-15 10:54:39 INFO [root] withdrawal fee usdt: {'id': 'USDT', 'code': 'USDT', 'info': {'name': 'Tether', 'id': 'USDT'}, 'type': None, 'name': 'Tether', 'active': None, 'deposit': None, 'withdraw': None, 'fee': None, 'precision': None, 'limits': {'withdraw': {'min': None, 'max': None}, 'amount': {'min': None, 'max': None}}}

# upbit
2022-05-15 11:19:55 INFO [root] withdrawal fee usdt: {'id': 'ETH', 'numericId': None, 'code': 'ETH', 'precision': 8}
```

**Comment by DoctorSlimm** [comment]
@Epikem @radadan there are no withdrawal fees for `markets`, rather there are withdrawal fees for `currencies`, and these fees vary depending on the `network`, some exchanges have a `fetchTransactionFee(code, params = {})` or `fetchTransactionFees(codes, params = {})` methods, (eg: kucoin, bitmart, bibox)which return information about withdrawal and deposit fees for specific currencies if available. However the unification of these methods is work in progress and is not present in most exchanges, hope this helps. On some exchanges (for example binance and huobi) you can also find information about withdrawal fees by network in the `currency` object, however this information is also not always available. 

```Python
import ccxt
exchange_id = 'kucoin'
exchange = getattr (ccxt, exchange_id) ()
exchange.load_markets ()
transaction_fees = exchange.fetchTransactionFee('USDT')
```

Returns:
`
{
  info: {
    code: '200000',
    data: {
      currency: 'USDT',
      limitBTCAmount: '1.00000000',
      usedBTCAmount: '0.00000000',
      remainAmount: '30522.368535',
      availableAmount: '0.000000',
      withdrawMinFee: '25',
      innerWithdrawMinFee: '0',
      withdrawMinSize: '50',
      isWithdrawEnabled: true,
      precision: 6,
      chain: 'ERC20'
    }
  },
  withdraw: { USDT: 25 },
  deposit: {}
}
`

```Python
import ccxt
exchange_id = 'huobi'
exchange = getattr (ccxt, exchange_id) ()
exchange.load_markets ()
# if available contains
currency = exchange.currency ('BTC')
# if available contains withdrawal information by chain
networks = currency['networks'] 
```

The `networks` object will contain information about withdrawal fees for specific networks (if available), otherwise the `currency` object may contain information about fees. 

networks:
`
{'BEP20': {'active': True,
           'deposit': True,
           'fee': 4e-06,
           'id': 'bep20btcb',
           'info': {'addrDepositTag': False,
                    'addrWithTag': False,
                    'chain': 'bep20btcb',
                    'depositStatus': 'allowed',
                    'displayName': 'BEP20',
                    'fullName': 'BTCB',
                    'isDynamic': False,
                    'maxWithdrawAmt': '17.000000000000000000',
                    'minDepositAmt': '0.000001',
                    'minWithdrawAmt': '0.000001',
                    'numOfConfirmations': '30',
                    'numOfFastConfirmations': '15',
                    'transactFeeWithdraw': '0.000004',
                    'withdrawFeeType': 'fixed',
                    'withdrawPrecision': '8',
                    'withdrawQuotaPerDay': '17.000000000000000000',
                    'withdrawQuotaPerYear': None,
                    'withdrawQuotaTotal': None,
                    'withdrawStatus': 'allowed'},
           'limits': {'withdraw': {'max': 17.0, 'min': 1e-06}},
           'network': 'BEP20',
           'precision': 1e-08,
           'withdraw': True},
 'BTC': {'active': True,
         'deposit': True,
         'fee': 0.0004,
         'id': 'btc',
         'info': {'addrDepositTag': False,
                  'addrWithTag': False,
                  'chain': 'btc',
                  'depositStatus': 'allowed',
                  'displayName': 'BTC',
                  'fullName': 'Bitcoin',
                  'isDynamic': False,
                  'maxWithdrawAmt': '100.000000000000000000',
                  'minDepositAmt': '0.0005',
                  'minWithdrawAmt': '0.001',
                  'numOfConfirmations': '2',
                  'numOfFastConfirmations': '1',
                  'transactFeeWithdraw': '0.0004',
                  'withdrawFeeType': 'fixed',
                  'withdrawPrecision': '8',
                  'withdrawQuotaPerDay': '100.000000000000000000',
                  'withdrawQuotaPerYear': None,
                  'withdrawQuotaTotal': None,
                  'withdrawStatus': 'allowed'},
         'limits': {'withdraw': {'max': 100.0, 'min': 0.001}},
         'network': 'BTC',
         'precision': 1e-08,
         'withdraw': True},
 'ERC20': {'active': True,
           'deposit': True,
           'fee': 0.00034716,
           'id': 'hbtc',
           'info': {'addrDepositTag': False,
                    'addrWithTag': False,
                    'baseChain': 'ETH',
                    'baseChainProtocol': 'ERC20',
                    'chain': 'hbtc',
                    'depositStatus': 'allowed',
                    'displayName': 'ERC20',
                    'fullName': 'HBTC',
                    'isDynamic': True,
                    'maxWithdrawAmt': '50.000000000000000000',
                    'minDepositAmt': '0.0005',
                    'minWithdrawAmt': '0.001',
                    'numOfConfirmations': '12',
                    'numOfFastConfirmations': '12',
                    'transactFeeWithdraw': '0.00034716',
                    'withdrawFeeType': 'fixed',
                    'withdrawPrecision': '8',
                    'withdrawQuotaPerDay': '50.000000000000000000',
                    'withdrawQuotaPerYear': None,
                    'withdrawQuotaTotal': None,
                    'withdrawStatus': 'allowed'},
           'limits': {'withdraw': {'max': 50.0, 'min': 0.001}},
           'network': 'ERC20',
           'precision': 1e-08,
           'withdraw': True},
 'HRC20': {'active': True,
           'deposit': True,
           'fee': 2.06e-06,
           'id': 'hrc20btc',
           'info': {'addrDepositTag': False,
                    'addrWithTag': False,
                    'baseChain': 'HECO',
                    'baseChainProtocol': 'HRC20',
                    'chain': 'hrc20btc',
                    'depositStatus': 'allowed',
                    'displayName': 'HRC20',
                    'fullName': 'HBTC',
                    'isDynamic': True,
                    'maxWithdrawAmt': '100.000000000000000000',
                    'minDepositAmt': '0.0005',
                    'minWithdrawAmt': '0.001',
                    'numOfConfirmations': '20',
                    'numOfFastConfirmations': '10',
                    'transactFeeWithdraw': '0.00000206',
                    'withdrawFeeType': 'fixed',
                    'withdrawPrecision': '8',
                    'withdrawQuotaPerDay': '100.000000000000000000',
                    'withdrawQuotaPerYear': None,
                    'withdrawQuotaTotal': None,
                    'withdrawStatus': 'allowed'},
           'limits': {'withdraw': {'max': 100.0, 'min': 0.001}},
           'network': 'HRC20',
           'precision': 1e-08,
           'withdraw': True}}
`

Hope this helps

**Comment by ttodua** [comment]
@DoctorSlimm had answered above, so closing this issue.
let us know if you have any problem with CCXT.
