### ISSUE TITLE
Mandatory parameter error occur when create market order

### ISSUE THREAD

**Issue by hvagday** [ccxt/ccxt#12593]
- OS: windows 11
- Programming Language version: python 3.8.11
- CCXT version: 1.55.48

I want to close my short position in Binance futures.
I submitted a market order as follows, but mandatory parameter error occurred.
There was no problem when the long position close order was conducted in the same way, I don't understand. (side='sell')

```   
exchange = ccxt.binance()
position_all = exchange.fetch_balance()['info']['positions'] 
position = [p for p in position_all if p['symbol'] == ETHUSDT][0]
close = exchange.create_order(symbol=ETH/USDT, type="MARKET", side="buy", 
                                                  amount=position['positionAmt'], params={"reduceOnly": True})
```

```
ccxt.base.errors.BadRequest: binance {"code":-1102,"msg":"Mandatory parameter 'quantity' was not sent, was empty/null, or malformed."}
```

**Comment by EkremSel** [comment]
How did you solve this issue. I'm having the same problem. 

`balance = exchange.fetch_balance()`
                
`all_positions=balance['info']['positions']`
                
`current_positions2 = [position for position in all_positions if (position['symbol']) == "UNIUSDT"]`
 
`close_position = exchange.create_order(symbol='UNI/USDT', type="MARKET", side="buy", amount=current_positions2[0]['positionAmt'], params={"reduceOnly": True}) `
