### ISSUE TITLE
Post sell/buy order with 'timeInForce ': 'GTX'

### ISSUE THREAD

**Issue by Hadevmin** [ccxt/ccxt#12591]
Hi,

OS: Windows
Programming Language version: Python 3.10
CCXT version: 1.77.79

For the binance exchange, I would like to post a limit order(for this example, a buy order) with the param PostOnly on the future market.
In the documentation of binance API(https://binance-docs.github.io/apidocs/futures/en/#public-endpoints-info) we need to use Time in force (timeInForce): GTX - Good Till Crossing (Post Only)
So I write this line:
`exchange.create_limit_buy_order('BTC/BUSD', 0.001, 42000, {'type': 'future', 'timeInForce ': 'GTX'}))`

And I get this return:
`{'info': {'orderId': 'xxx', 'symbol': 'BTCBUSD', 'status': 'NEW', 'clientOrderId': 'x-xxxxx', 'price': '42000', 'avgPrice': '0.0000', 'origQty': '0.001', 'executedQty': '0', 'cumQty': '0', 'cumQuote': '0', 'timeInForce': 'GTC', 'type': 'LIMIT', 'reduceOnly': False, 'closePosition': False, 'side': 'BUY', 'positionSide': 'BOTH', 'stopPrice': '0', 'workingType': 'CONTRACT_PRICE', 'priceProtect': False, 'origType': 'LIMIT', 'updateTime': '1648656546218'}, 'id': 'xxxx', 'clientOrderId': 'x-xxx', 'timestamp': 1648656546218, 'datetime': '2022-03-30T16:09:06.218Z', 'lastTradeTimestamp': None, 'symbol': 'BTC/BUSD', 'type': 'limit', 'timeInForce': 'GTC', 'postOnly': False, 'side': 'buy', 'price': 42000.0, 'stopPrice': None, 'amount': 0.001, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 0.001, 'status': 'open', 'fee': None, 'trades': [], 'fees': []}`

We can see in the response : 
`'timeInForce': 'GTC'` and `'postOnly': False`

So I have activated the verbose mode and we can see below the request of the order:
`fetch Request: binance POST https://fapi.binance.com/fapi/v1/order RequestHeaders: {'X-MBX-APIKEY': 'xxx', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} RequestBody: timestamp=1648656546267&recvWindow=5000&symbol=BTCBUSD&type=LIMIT&side=BUY&newClientOrderId=x-xxx&newOrderRespType=RESULT&quantity=0.001&price=42000&timeInForce=GTC&timeInForce+=GTX&signature=e903ef41129eac210c9701f5e563af75db4e5002d859c05adbc2d8fd29348bd7`

We can see in the order request:
`&timeInForce=GTC&timeInForce+=GTX`

Is this a normal behavior?
If so, what is the methodology for posting a postonly limit order?

Thank you for your answers

**Comment by ttodua** [comment]
I see that you have a space after `timeInForce` word and before the ending quote:
```
'timeInForce ': 'GTX' 
```
--------------^
please fix that and if you still have issues, I'll give it deeper check.

**Comment by Hadevmin** [comment]
I'm really sorry to wash your time...
Anyway, your project is awesome! Thank you for this product! 

Have a nice day
