### ISSUE TITLE
quoine qryptos php create_order and Uncaught exception Issues

### ISSUE THREAD

**Issue by bimble1** [ccxt/ccxt#1260]
- OS: Linux CentOS
- Programming Language version: PHP
- CCXT version: 1.10.658
- Exchange: quoine
- Method: create_order

create_order path is being sent incorrectly comes up as
https://api.quoine.com/limitArray1ArraysellArray1.01Array20000

I have bypassed this test further and found there is also an issue with the error handling - this is for InsufficientFunds
`<b>Fatal error</b>:  Uncaught exception 'ccxt\InsufficientFunds' with message 'quoine {&quot;errors&quot;:{&quot;user&quot;:[&quot;not_enough_free_balance&quot;]}}' in /home/xxxx/public_html/ccxt/php/qryptos.php:391
--
  | Stack trace:
  | #0 /home/xxxx/public_html/ccxt/php/Exchange.php(850): ccxt\qryptos-&gt;handle_errors(422, '', 'https://api.quo...', 'POST', Array, '{&quot;errors&quot;:{&quot;use...')
  | #1 /home/xxxx/public_html/ccxt/php/Exchange.php(702): ccxt\Exchange-&gt;fetch('https://api.quo...', 'POST', Array, '{&quot;order&quot;:{&quot;orde...')
  | #2 /home/xxxx/public_html/ccxt/php/Exchange.php(706): ccxt\Exchange-&gt;fetch2('orders', 'private', 'POST', Array, NULL, NULL)
  | #3 [internal function]: ccxt\Exchange-&gt;request('orders', 'private', 'POST', Array)
  | #4 /home/xxxx/public_html/ccxt/php/Exchange.php(645): call_user_func(Array, 'orders', 'private', 'POST', Array)
  | #5 [internal function]: ccxt\Exchange-&gt;ccxt\{closure}(Array)
  | #6 /home/xxxx/public_html/ccxt/php/Exchange.php(1470): call_user_func_array(Object(Closure), Array)
  | #7 /home/xxxx in <b>/home/xxxx/public_html/ccxt/php/qryptos.php</b> on line <b>391</b><br />`

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/issues/1237#issuecomment-357441152

**Comment by bimble1** [comment]
Thanks, that doesn't cover the first error:
create_order path is being sent incorrectly comes up as
https://api.quoine.com/limitArray1ArraysellArray1.01Array20000
it seams to be sending the array as the path.
all other functions seams to be ok, just a problem on create_order

**Comment by kroitor** [comment]
@bimble1 without seeing your code, it's hard to tell, can you please post it [according to this](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue) ?

**Comment by bimble1** [comment]
OS: Linux CentOS
Programming Language version: PHP
CCXT version: 1.10.658
Exchange: quoine
Method: create_order

`$api->create_order('BTC/USD','limit','sell','1.01','20000');`
then sends the following array to function sign .. the path is being sent as the array rather than /orders.  I've made a work around but its too much of a hack to submit replacement code, so I'm reporting the error.
`Array
--
  | (
  | [0] => POST
  | [1] => https://api.quoine.com/limitArray1ArraysellArray1.01Array20000
  | [2] => Array
  | (
  | [0] => X-Quoine-API-Version: 2
  | [1] => Content-Type: application/json
  | [2] => X-Quoine-Auth: xxxx (removed for post)
  | )
  |  
  | [3] => {"order":{"order_type":"limit","product_id":"1","side":"sell","quantity":"1.01","price":"20000"}}
  | )`
