### ISSUE TITLE
Invalid API key error for Gateio

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#12600]
OS: Windows Server 2019 Datacenter
Programming Language version: Node.js 15.3.0
CCXT version: 1.49.98
Exchange: Gate
Method: exchange.fetchBalance()

Hello!

I am trying to declare `Gateio` exchange with API keys. I have put `apiKey, secret and password `.
I am trying to `fetchBalance` in this test but I get the error:

`{"label":"INVALID_KEY","message":"Invalid key provided"}`

But I am sure I have the correct keys. I have just created those keys 1 hour ago.
I have also tried without the `password` with the same problem.
I have attached the `verbose` output. 

I am not sure if my code is not correct for `gateio`?  _(I have changed API keys in the code)_

Thanks!

```
declareGATEIO();
async function declareGATEIO()
{
    const Exchange = ccxt["gateio"];
    const exchange = new Exchange({ enableRateLimit: true, 'timeout': 10000 });

    exchange.verbose = true;
    exchange.apiKey = "BBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBBBB";
    exchange.secret = "secretsecretsecretsecretsecretsecretsecretsecretsecret";
    exchange.password = "000T000";

    //Get balances
    const balance = await exchange.fetchBalance();
    console.log(balance) //show in console
}
```

Verbose Output:
```
fetch Request:
 gateio GET https://api.gateio.ws/api/v4/spot/accounts
RequestHeaders:
 {
  KEY: 'BBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBBBB',
  Timestamp: '1648853889',
  SIGN: 'e2cf15c9a0fe34385ab0390cbc3e00872039ba4baef4f3e0cfd468863099d42ccf9828db1bfd0ef9fa647fe033c038e7499372abe176c16f2d31613deead3974',
  'Content-Type': 'application/json'
}
RequestBody:
 undefined

handleRestResponse:
 gateio GET https://api.gateio.ws/api/v4/spot/accounts 401 Unauthorized
ResponseHeaders:
 {
  Connection: 'keep-alive',
  'Content-Type': 'application/json',
  Date: 'Fri, 01 Apr 2022 22:58:09 GMT',
  Server: 'openresty',
  'Transfer-Encoding': 'chunked'
}
ResponseBody:
 {"label":"INVALID_KEY","message":"Invalid key provided"}


C:\myproject\node_modules\ccxt\js\base\Exchange.js:632
            throw new exact[string] (message)
                  ^

AuthenticationError: gateio {"label":"INVALID_KEY","message":"Invalid key provided"}

    at gateio.throwExactlyMatchedException (C:\myproject\node_modules\ccxt\js\base\Exchange.js:632:19)
    at gateio.handleErrors (C:\myproject\node_modules\ccxt\js\gateio.js:3116:18)
    at C:\myproject\node_modules\ccxt\js\base\Exchange.js:709:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async timeout (C:\myproject\node_modules\ccxt\js\base\functions\time.js:203:20)
    at async gateio.fetchBalance (C:\myproject\node_modules\ccxt\js\gateio.js:1538:24)
    at async declareGATEIO (C:\myproject\functions.js:155:21) {
  constructor: [class AuthenticationError extends ExchangeError]
}
```

**Comment by carlosmiei** [comment]
Hello @jackpotcityco,
Please double check your keys validity or request new ones, as you can see in the image seems to be working fine on my end.
![image](https://user-images.githubusercontent.com/43336371/161377574-ebda5984-9aea-4835-a520-c8b837b0700a.png)

**Comment by jackpotcityco** [comment]
> Hello @jackpotcityco, Please double check your keys validity or request new ones, as you can see in the image seems to be working fine on my end. ![image](https://user-images.githubusercontent.com/43336371/161377574-ebda5984-9aea-4835-a520-c8b837b0700a.png)

I tried to create new keys also but still I get this error together with the verbose output above. I can't understand how it can't work. Do you use the same code as I do and also put the `fundpassword` ?

`AuthenticationError: gateio {"label":"INVALID_KEY","message":"Invalid key provided"}`

**Comment by Elton-gif** [comment]
OS: Windows Server 2019 Datacenter
Programming Language version: Node.js 20.13.0.     
CCXT version: 4.3.53
Exchange: Gate
Method : setSandboxMode

Encountered the same error while using testnet api keys.
