### ISSUE TITLE
Missing docs for gateio spot order types

### ISSUE THREAD

**Issue by zozoheir** [ccxt/ccxt#12616]
I see in https://github.com/ccxt/ccxt/blob/master/python/ccxt/gateio.py variables related to spot order parameters (stopPrice, reduceOnly)
```
    def create_order(self, symbol, type, side, amount, price=None, params={}):
        self.load_markets()
        market = self.market(symbol)
        contract = market['contract']
        stopPrice = self.safe_number(params, 'stopPrice')
        methodTail = 'Orders'
        reduceOnly = self.safe_value_2(params, 'reduce_only', 'reduceOnly')
        defaultTimeInForce = self.safe_value_2(params, 'tif', 'time_in_force', 'gtc')
        timeInForce = self.safe_value(params, 'timeInForce', defaultTimeInForce)
        params = self.omit(params, ['stopPrice', 'reduce_only', 'reduceOnly', 'tif', 'time_in_force', 'timeInForce'])
        isLimitOrder = (type == 'limit')
        isMarketOrder = (type == 'market')
```

However, I can't find any type of definition or available options on the Gateio API spot order docs page. In fact, GateIO API docs do not list available order types and/or their parameters. Only order type shown on official docs is 'limit order'.

https://www.gate.io/docs/apiv4/en/#create-an-order

- OS: Mac OS
- Programming Language version: Python
- CCXT version: latest

**Comment by samgermain** [comment]
[I created a docstring](https://github.com/ccxt/ccxt/pull/12617) for `gateio.createOrder`

> Only order type shown on official docs is 'limit order'.

That's correct gateio spot can only do limit orders

**Comment by cagriKarakulak** [comment]
gateio now supports market order but I can't create market order with ccxt
