### ISSUE TITLE
ccxt/python/deribit: Nonce Reused

### ISSUE THREAD

**Issue by inthestatic** [ccxt/ccxt#12618]
It appears that when using multiple instances of ccxt in python for the deribit exchange, ccxt re-uses (or generates the same nonces) for different requests.

Here is the error json:

{\"jsonrpc\":\"2.0\",\"error\":{\"message\":\"invalid_credentials\",\"data\":{\"invalid\":\"nonce\"},\"code\":13004}

Other than NOT running multiple ccxt instances at the same time, how can this issue be avoided or corrected?

**Comment by inthestatic** [comment]
I see that the nonce generation is the exchange base class here.
https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L1083

Im only running a few (<10) scripts) at the same time, so its unclear, due to the high frequency of this nonce re-use errors, how only 10 scripts running every second or so would collide. Perhaps devs or other users have input.

**Comment by kroitor** [comment]
That is expected, if you're using multiple instances of the same exchange, they're not aware of each other and their rate limiting is separate. That is a violation of the exchange rules if you're not managing your rate limits across the exchange instances. An alternative solution to a custom rate limiter shared between your instances would be to use a cloud of vpc or a set of ups ad rotating them in a round-robin fashion.

Please, read the docs on the rate limiter:

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter

Let us know if that does not answer your question. Feel free to reopen it or just ask further questions here if any.

**Comment by inthestatic** [comment]
@kroitor , thanks for the comments.

I confirmed with the exchange, deribit, and they seemed to also think the error was nonce reuse and didn’t mentioned API limits. Also our API limits are twice per second what we are using. Not sure if that helps. Is there any debugging I can do further on my side to troubleshoot / get more info?

**Comment by kroitor** [comment]
@inthestatic i would suggest reading the entire Manual from top to bottom, especially the sections linked above on how the rate limiting works in CCXT in order to understand and control it. Also, you can enable the verbose mode and see exactly what is happening in the background:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://docs.ccxt.com/en/latest/manual.html#troubleshooting
