### ISSUE TITLE
gateio fetchMyTrades info dict missing "text" key

### ISSUE THREAD

**Issue by zozoheir** [ccxt/ccxt#12628]
The info dict returned by fetchMyTrades in gateio is missing the "text" key which is actually present when requesting orders using the official API directly as per official website.

list-orders section in https://www.gate.io/docs/apiv4/ 

- OS: Mac 
- Programming Language version: Python
- CCXT version: Latest

```
ccxt.gateio().fetchMyTrades(symbol, since, limit, params)
```
No text attribute

**Comment by kroitor** [comment]
Please, read the CCXT Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#order-structure

You can find the `text` key under the `info` dict inside the order, if the exchange specifies it. The `info` dict will contain the order as returned from the exchange as is.

**Comment by zozoheir** [comment]
That is exactly the issue: it is NOT present in the info dict when fetching with CCXT, but it is present in the data returned directly by the Gateio API:
Below is an example info dict from fetching GateIO trades with CCXT:

```
gateio_exchange_object.fetchMyTrades(symbol, since, limit, params)
```
```
{'id': '3170637655',
   'create_time': '1649120741',
   'create_time_ms': '1649120741109.332000',
   'currency_pair': 'BTC_USDT',
   'side': 'buy',
   'role': 'taker',
   'amount': '0.0001',
   'price': '46532.01',
   'order_id': '140665174841',
   'fee': '2e-07',
   'fee_currency': 'BTC',
   'point_fee': '0',
   'gt_fee': '0'}
```
As you can see, no 'text' key.

**Comment by kroitor** [comment]
@zozoheir on Gate.io orders' info has the `text` key, but they trades' info does not have it, as returned from the exchange API. Use fetchOrders / fetchClosedOrders / fetchOpenOrders for fetching orders.

**Comment by zozoheir** [comment]
Ah...thank you very much.  I'm getting this error when opening [the link](https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades):

"The wiki page took too long to render.
This wiki page’s content is too large to render on this page."

**Comment by kroitor** [comment]
@zozoheir here's an alternative link: https://docs.ccxt.com/en/latest/manual.html#how-orders-are-related-to-trades

**Comment by zozoheir** [comment]
Thank you sir! very responsive. love ccxt
