### ISSUE TITLE
PHP custom object types instead of arrays

### ISSUE THREAD

**Issue by pursehouse** [ccxt/ccxt#1262]
There are already central methods to return the same format for orders/trades/etc.
It would be nice if these could be instances of a class ( struct ) instead of just an array. This would cause compatibility issues with existing projects using the system, but is a much more functional way to use PHP code.
This allows for hinting of field names in our IDE's and ideally utilize PHPDoc instructions and PHP7 type hinting for the method return. As well as method argument type hinting.

I could do this project myself, would it be accepted into the main project if I did so?

thanks

**Comment by kroitor** [comment]
> This allows for hinting of field names in our IDE's and ideally utilize PHPDoc instructions and PHP7 type hinting for the method return. As well as method argument type hinting.

Your arguments are absolutely clear, and we agree with that.

> I could do this project myself, would it be accepted into the main project if I did so?

We had plans for adding an option that would:
- be portable
- be backward compatible
- support both the oop-way and the plain json-struct style in all languages

More about it here:
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

We would be happy for all contributions. But we should be overly-careful/critical on the code formatting and architectural aspects of it, so to make it work seamlessly everywhere. It's on our plans and we hope to deliver this feature asap.
