### ISSUE TITLE
[Zipmex] watchTrades with multiple pairs  is not sending others pairs data except the first one

### ISSUE THREAD

**Issue by prinprem** [ccxt/ccxt#12621]
OS: macOS Monterey 12.2.1
Programming Language version: JS, Node 17.7.1
CCXT version:1.77.18 & CCXT.Pro
Which exchange it is: Zipmex

Which method you're trying to call: watchTrades()

```
 const symbols = ['USDT/THB', 'BTC/THB', 'ETH/THB',]

  await Promise.all(symbols.map(symbol =>
    (async () => {

      while (true) {
        try {
          const trades = await exchange.watchTrades(symbol, 0, 1)
          console.log(new Date(), symbol, trades);
        } catch (e) {
          console.log(symbol, e)
        }
      }
    })())
```

I only received the first symbol data that connects to the watchTrades function. Could you please check my code. Is the anything wrong in my code?

**Comment by carlosmiei** [comment]
Hello @prinprem 
You're passing 1 as the limit so that means it will only return 1 trade on each update. Can you increase that number or even don't pass a limit at all to see if solves your problem?

```Javascript
//                                                                                             > this is the limit argument
const trades = await exchange.watchTrades(symbol, 0, 1)
```

If don't, please reopen this issue with a verbose request + response so we can analyze it better.

**Comment by prinprem** [comment]
I did what you told me. It still does not work.

**Comment by carlosmiei** [comment]
Hello @prinprem to better understand the problem would be very useful if you could post a verbose output log of the request + response of the described issue

**Comment by kroitor** [comment]
Reposted and continued here: https://github.com/ccxt/ccxt/issues/12866.

**Comment by prinprem** [comment]
I had ran the code you provided for a couple of mintues. This is the output.

CCXT Pro Version: 1.0.71
2022-04-17T07:16:38.718Z connecting to wss://apws.zipmex.com/WSGateway
2022-04-17T07:16:38.881Z onUpgrade
2022-04-17T07:16:38.882Z onOpen
2022-04-17T07:16:38.882Z sending {
m: 0,
i: 1,
n: 'SubscribeTrades',
o: '{"OMSId":1,"InstrumentId":53,"IncludeLastCount":100}'
}
2022-04-17T07:16:38.930Z onMessage {
m: 1,
i: 1,
n: 'SubscribeTrades',
o: '[[680869,53,0.06070,33.8112,1074363024,1074363025,1650163201622,2,1,1,0],[680870,53,0.21900,33.8113,1074365668,1074365669,1650163518513,1,0,1,0],[680871,53,2,33.8112,1074363215,105592,1650163546878,2,1,0,0],[680872,53,0.22020,33.7731,1074367009,1074367010,1650163659821,2,0,1,0],[680873,53,2.9402,33.7731,1074372227,1074373164,1650164338907,0,1,0,0],[680874,53,0.23480,33.8039,1074373235,1074373236,1650164347814,1,1,1,0],[680875,53,0.0766,33.804,105591,1074373519,1650164376152,1,0,0,0],[680876,53,0.0207,33.7731,1074372227,1074376542,1650164715868,2,1,0,0],[680877,53,3.0574,33.7730,1074307371,1074376542,1650164715868,2,1,0,0],[680878,53,5.9014,33.7730,1074307371,1074376781,1650164742598,0,1,0,0],[680879,53,0.22750,33.8039,1074377460,1074377461,1650164809364,1,1,1,0],[680880,53,7.2587,33.7730,1074307371,1074380429,1650165138861,2,1,0,0],[680881,53,0.22770,33.7731,1074382473,1074382474,1650165384941,1,0,1,0],[680882,53,4.0612,33.7730,1074307371,1074382492,1650165387329,2,1,0,0],[680883,53,17.662000000000000000000000000,33.804,105593,1074385496,1650165736066,1,0,0,0],[680884,53,1.9781,33.7730,1074307371,1074385960,1650165782426,2,1,0,0],[680885,53,1.4792000000000000000000000000,33.804,1074378374,1074388256,1650166034777,1,0,0,0],[680886,53,23.4135,33.7730,1074307371,1074388733,1650166093279,2,1,0,0],[680887,53,5.9224,33.7699,1073999948,1074388733,1650166093279,2,1,0,0],[680888,53,9.2518,33.7599,1073977599,1074388733,1650166093279,2,1,0,0],[680889,53,5.928,33.738,1073772173,1074388733,1650166093279,2,1,0,0],[680890,53,6013.7043,33.7363,105575,1074388733,1650166093279,2,1,0,0],[680891,53,0.16850,33.7401,1074390628,1074390629,1650166331132,1,0,1,0],[680892,53,0.1506,33.7363,105575,1074394760,1650166829869,2,1,0,0],[680893,53,0.0561,33.74,1074396352,1074396792,1650167079478,1,1,0,0],[680894,53,0.14150,33.8005,1074397452,1074397453,1650167163091,1,1,1,0],[680895,53,0.0374,33.74,1074396352,1074398618,1650167308006,2,1,0,0],[680896,53,2.9958,33.7329,105575,1074402915,1650167820907,2,1,0,0],[680897,53,0.17610,33.8005,1074403769,1074403770,1650167930471,1,1,1,0],[680898,53,470,33.74,1074402964,1074404644,1650168042802,2,1,0,0],[680899,53,470,33.74,1074404662,1074404783,1650168061767,0,1,0,0],[680900,53,460,33.74,1074404801,1074404848,1650168071262,0,1,0,0],[680901,53,460,33.74,1074404860,1074404907,1650168079269,0,1,0,0],[680902,53,451,33.74,1074404931,1074405139,1650168111401,0,1,0,0],[680903,53,451,33.74,1074405167,1074405209,1650168119775,0,1,0,0],[680904,53,447.1222,33.74,1074405222,1074405300,1650168135643,0,1,0,0],[680905,53,6790.8778,33.7329,105575,1074405300,1650168135643,2,1,0,0],[680906,53,0.04750,33.7401,1074406377,1074406378,1650168269967,1,0,1,0],[680907,53,0.13320,33.7401,1074410310,1074410311,1650168762456,0,0,1,0],[680908,53,10.4277,33.74,1074410128,1074411010,1650168848792,2,1,0,0],[680909,53,1.3644,33.7500,1074413171,1074413238,1650169103868,1,1,0,0],[680910,53,29.8702,33.7500,1074413171,1074413962,1650169186289,0,1,0,0],[680911,53,146.8856,33.74,1074410128,1074413962,1650169186289,2,1,0,0],[680912,53,0.11220,33.7401,1074416204,1074416205,1650169456477,1,0,1,0],[680913,53,0.14360,33.8005,1074416934,1074416935,1650169549715,1,1,1,0],[680914,53,0.20780,33.8005,1074417708,1074417709,1650169645597,0,1,1,0],[680915,53,0.15290,33.8039,1074426409,1074426410,1650170651204,1,1,1,0],[680916,53,0.10610,33.8039,1074426772,1074426773,1650170698256,0,1,1,0],[680917,53,0.108,33.75,1074418618,1074426853,1650170708357,2,1,0,0],[680918,53,0.09480,33.7501,1074427500,1074427501,1650170792116,1,0,1,0],[680919,53,2.8895000000000000000000000000,33.804,1074378374,1074427567,1650170799571,1,0,0,0],[680920,53,29.5216,33.75,1074418618,1074428485,1650170933564,2,1,0,0],[680921,53,1460.4784,33.7329,105575,1074428485,1650170933564,2,1,0,0],[680922,53,3.1351,33.7329,105575,1074430622,1650171185878,0,1,0,0],[680923,53,0.11390,33.8039,1074430813,1074430814,1650171207885,1,1,1,0],[680924,53,15.5,33.7329,105575,1074432012,1650171355345,2,1,0,0],[680925,53,52.1983,33.7329,105575,1074433026,1650171474005,0,1,0,0],[680926,53,0.06870,33.733,1074433499,1074433500,1650171530258,1,0,1,0],[680927,53,0.3247,33.74,1074433553,1074434800,1650171673844,1,1,0,0],[680928,53,0.22150,33.7401,1074436065,1074436066,1650171818461,1,0,1,0],[680929,53,2.0207000000000000000000000000,33.804,1074378374,1074438054,1650172048664,1,0,0,0],[680930,53,15.910300000000000000000000000,33.8147,105594,1074438054,1650172048664,1,0,0,0],[680931,53,1.4778,33.74,1074433553,1074440276,1650172314734,2,1,0,0],[680932,53,17.8951,33.74,1074433553,1074441341,1650172445132,0,1,0,0],[680933,53,6.0484,33.74,1074433553,1074441805,1650172500853,0,1,0,0],[680934,53,0.11640,33.7401,1074443480,1074443481,1650172698872,1,0,1,0],[680935,53,60.1883,33.74,1074433553,1074443906,1650172743478,2,1,0,0],[680936,53,2.072,33.7401,1074443902,1074446749,1650173053382,1,0,0,0],[680937,53,60.772900000000000000000000000,33.8073,105588,1074446749,1650173053382,1,0,0,0],[680938,53,0.20820,33.8072,1074449342,1074449343,1650173355627,2,1,1,0],[680939,53,14.8104,33.76,1074447431,1074449462,1650173374679,2,1,0,0],[680940,53,48.3755,33.74,1074433553,1074449462,1650173374679,2,1,0,0],[680941,53,1.0364,33.74,1074433553,1074449809,1650173416806,0,1,0,0],[680942,53,25.7216,33.8073,1074443384,1074450623,1650173525403,1,0,0,0],[680943,53,1482.8283000000000000000000000,33.8073,105600,1074450623,1650173525403,0,0,0,0],[680944,53,5.5046,33.74,1074433553,1074451913,1650173677143,2,1,0,0],[680945,53,14.8322,33.74,1074433553,1074453149,1650173827292,0,1,0,0],[680946,53,16362.198300000000000000000000,33.804,105589,1074453804,1650173910902,1,0,0,0],[680947,53,8167.754400000000000000000000,33.804,105587,1074454010,1650173935971,0,0,0,0],[680948,53,0.00980,33.7401,1074456837,1074456838,1650174269297,2,0,1,0],[680949,53,0.0189,33.74,1074457038,1074459668,1650174586856,2,1,0,0],[680950,53,0.8845,33.74,1074463013,1074463271,1650174980462,0,1,0,0],[680951,53,0.02900,33.7401,1074464639,1074464640,1650175143129,1,0,1,0],[680952,53,21.4092,33.7329,105575,1074467963,1650175520548,2,1,0,0],[680953,53,2.9585,33.8,1074456584,1074468032,1650175529508,1,0,0,0],[680954,53,0.04140,33.7401,1074472683,1074472684,1650176070730,2,0,1,0],[680955,53,0.02060,33.7999,1074474130,1074474131,1650176242780,1,1,1,0],[680956,53,2.0,33.8,1074456584,1074474902,1650176348071,1,0,0,0],[680957,53,13.1606,33.7329,105575,1074476038,1650176478182,2,1,0,0],[680958,53,2.9155,33.74,1074476293,1074477399,1650176641715,1,1,0,0],[680959,53,0.23890,33.733,1074480796,1074480797,1650177029231,2,0,1,0],[680960,53,25.5074,33.74,1074481628,1074481952,1650177161887,1,1,0,0],[680961,53,0.001,33.74,1074481628,1074484561,1650177471516,0,1,0,0],[680962,53,0.18180,33.7401,1074486360,1074486362,1650177681875,1,0,1,0],[680963,53,0.05650,33.733,1074489278,1074489279,1650178025423,2,0,1,0],[680964,53,0.05160,33.7999,1074495924,1074495925,1650178849261,1,1,1,0],[680965,53,7.7591,33.80,1074489072,1074497891,1650179101765,1,0,0,0],[680966,53,52.649700000000000000000000000,33.8081,105590,1074497891,1650179101765,1,0,0,0],[680967,53,0.07340,33.733,1074498573,1074498574,1650179179620,2,0,1,0],[680968,53,1.3423,33.7329,105575,1074502024,1650179599105,2,1,0,0]]'
}
2022-04-17T07:16:38.934Z zipmex USDT/THB 100 trades
2022-04-17T07:17:08.892Z onPing
2022-04-17T07:17:08.939Z onPong
2022-04-17T07:17:38.890Z onPing
2022-04-17T07:17:38.920Z onPong
2022-04-17T07:18:08.887Z onPing
2022-04-17T07:18:08.923Z onPong
2022-04-17T07:18:38.888Z onPing
2022-04-17T07:18:38.922Z onPong
2022-04-17T07:19:08.888Z onPing
