### ISSUE TITLE
wach_my_trades doesn't work when use the example code in doc for PHP

### ISSUE THREAD

**Issue by zafixcap** [ccxt/ccxt#12624]
OS: Windows 10
Programming Language version: PHP 7.2.5
CCXT version: 1.76.20
CCXT Pro version: 1.0.28
exchange: Binance

```
       if ($exchange->has['watchMyTrades']) {
            $exchange::execute_and_run(function () use ($exchange) {
                while (true) {
                    try {
                        $balance = yield $exchange->watch_balance();
                        echo date('c'), ' ', json_encode($balance), "<br>";
                    } catch (Exception $e) {
                        echo get_class($e), ' ', $e->getMessage(), "<br>";
                    }
                }
            });
        }
```

I get nothing in output. I don't get any exceptions or errors at all.
but this is working.

```
       if ($exchange->has['watchTicker']) {
            $symbol = "ETH/USDT";
            $params = ["type" => "future"];
            $exchange::execute_and_run(function () use ($exchange, $symbol, $params) {
                while (true) {
                    try {
                        $ticker = yield $exchange->watch_ticker($symbol, $params);
                        echo date('c'), ' ', json_encode($ticker), "<br>";
                    } catch (Exception $e) {
                        echo get_class($e), ' ', $e->getMessage(), "<br>";
                    }
                }
            });
        }
```
is this about exchange or subscription?

in verbose mode, I get the output of the exchange's information.

**Comment by kroitor** [comment]
> I get nothing in output. I don't get any exceptions or errors at all.

You have to make some trades if you're watching your trades (watchMyTrades) – if you don't place any orders, then watchMyTrades will not get your personal trade updates from the exchange, cause there will be none, obviously.

If you want to watch public trades, use `watchTrades` instead of `watchMyTrades`.

Hope that answers your question.

**Comment by zafixcap** [comment]
thanks for answering.
when I watch my trades and do a trades get an error.

```
Recoil\Exception\KernelException
Unhandled exception in kernel: Error (Cannot assign by reference to an array dimension of an object).
```

in verbose mode information of trade from Binance was received but  (I think) Recoil can't handle that while when getting account information, can handle it.
getting account information to occur when I watch my trades.
