### ISSUE TITLE
KuCoin Futures Sandbox CCXT Fundings

### ISSUE THREAD

**Issue by amirnz026** [ccxt/ccxt#12638]
I've created an account at https://sandbox.kucoin.com/ and then I created an api key and secret key for the spot trades. Everything works great with spot trades and ccxt in my script. But I can not fund my futures account. Whenever I try to transfer funds from spot to futures, those funds will be reduced from my spot account but they will not be added to my futures account. Could you help me?

Has anybody used kucoin futures sandbox with ccxt? Does it work?

- OS: Linux
- Programming Language version: Python
- CCXT version: 1.78.4

```
import ccxt

exchange = ccxt.kucoinfutures({
    'adjustForTimeDifference': True,
    "apiKey": API_PUBLIC_KEY,
    "secret": API_PRIVATE_KEY,
    'password': API_PASSPHRASE
})
exchange.set_sandbox_mode(True)
exchange.verbose = True

print(exchange.fetch_balance())
```

```
ccxt.base.errors.ExchangeNotAvailable: kucoinfutures Internal Server Error
```

**Comment by samgermain** [comment]
> I've created an account at https://sandbox.kucoin.com/ 

The sandbox url for futures is different, it looks like you might have to create an account at https://sandbox-futures.kucoin.com

> I created an api key and secret key for the spot trades. Everything works great with spot trades and ccxt in my script.

`kucoinfutures` requires a separate `apiKey` and `secret` from `kucoin`, 

> Whenever I try to transfer funds from spot to futures, those funds will be reduced from my spot account but they will not be added to my futures account.

could you provide more details on how the assets aren't in your futures account? When I transfer them, I can see them in there


```JavaScript
Node.js: v14.17.0
CCXT v1.78.7

kucoinfutures.fetchBalance ()

// {
//   info: {
//     code: '200000',
//     data: {
//       accountEquity: 1.2e-9,
//       unrealisedPNL: 0,
//       marginBalance: 1.2e-9,
//       positionMargin: 0,
//       orderMargin: 0,
//       frozenFunds: 0,
//       availableBalance: 1.2e-9,
//       currency: 'USDT'
//     }
//   },
//   timestamp: undefined,
//   datetime: undefined,
//   USDT: { free: 1.2e-9, used: 0, total: 1.2e-9 },
//   free: { USDT: 1.2e-9 },
//   used: { USDT: 0 },
//   total: { USDT: 1.2e-9 }
// }

kucoin.transfer (USDT, 15, funding, future)

// {
//   info: { code: '200000', data: { orderId: '624c5765c935a000013e5874' } },
//   id: '624c5765c935a000013e5874',
//   timestamp: undefined,
//   datetime: undefined,
//   currency: 'USDT',
//   amount: '15',
//   fromAccount: 'main',
//   toAccount: 'contract',
//   status: undefined
// }

kucoinfutures.fetchBalance ()

// {
//   info: {
//     code: '200000',
//     data: {
//       accountEquity: 15.0000000012,
//       unrealisedPNL: 0,
//       marginBalance: 15.0000000012,
//       positionMargin: 0,
//       orderMargin: 0,
//       frozenFunds: 0,
//       availableBalance: 15.0000000012,
//       currency: 'USDT'
//     }
//   },
//   timestamp: undefined,
//   datetime: undefined,
//   USDT: { free: 15.0000000012, used: 0, total: 15.0000000012 },
//   free: { USDT: 15.0000000012 },
//   used: { USDT: 0 },
//   total: { USDT: 15.0000000012 }
// }
```

**Comment by amirnz026** [comment]
Thank you for your response, I appreciate it. Thanks to you my futures account is now funded. But kucoin futures sandbox does not have many pairs, only BTC/USDT, ADA/USDT and ETH/USDT. I cannot trade on other pairs. Do you have the same issue or the problem is with my client?

**Comment by samgermain** [comment]
> Thank you for your response, I appreciate it. Thanks to you my futures account is now funded. But kucoin futures sandbox does not have many pairs, only BTC/USDT, ADA/USDT and ETH/USDT. I cannot trade on other pairs. Do you have the same issue or the problem is with my client?

It looks like those are the only 3 markets on kucoinfutures sandbox for USDT margined

![](https://i.imgur.com/x2VkGPd.png)

And then there's one for coin margined

![](https://i.imgur.com/X0QqNTC.png)

--------------

I'm going to close this issue because it looks like it's solved, but feel free to reopen it if you have more questions
