### ISSUE TITLE
kucoin spot average entry price?

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#12643]
does kucoin not have this either for spot market?

**Comment by DoctorSlimm** [comment]
@adamrg73 do you mean when a limit order was filled at different prices?

**Comment by Dan-krm** [comment]
Tracking the average entry price for your holdings in spot markets isn't supported as a standalone endpoint on most exchange API's you'd need to create a custom function using data from methods like fetchClosedOrders
