### ISSUE TITLE
Has anyone had any luck getting CCXT to run in a Webworker?

### ISSUE THREAD

**Issue by dmh1974** [ccxt/ccxt#12646]
I cant seem to find any examples of this.

Any example code would be helpful.

Much Thanks!

**Comment by carlosmiei** [comment]
Hello @dmh1974, I'll try to come up with a simple example demonstrating it

**Comment by carlosmiei** [comment]
Hello @dmh1974, I've just added an example, please check it out here: https://github.com/ccxt/ccxt/pull/12796

Demo:
![webWorkerExample](https://user-images.githubusercontent.com/43336371/163345850-2e821cd9-e9db-4012-b3aa-a6a05b99433b.gif)
