### ISSUE TITLE
"Insufficient margin available" error in HUOBI instead of i have USDT

### ISSUE THREAD

**Issue by flav1ooo** [ccxt/ccxt#12645]
Hi, imt trying to make future contracts in huobi, i got 7 usdt in my wallet and my code is below:
import ccxt

account_huobi = ccxt.huobi({
    "apiKey": 'api',
    "secret": 'secret',
    'options': {
        'defaultType': 'future',  
        'defaultSubType': 'linear',
    }

})
params_huobi_open = {"offset": "open", "client_order_id": 1,"lever_rate":2} 
params_huobi_close = {"offset": "close", "client_order_id": 5, "reduce_only": 1}
amount=5

HuobiADA = account_huobi.fetch_ticker("ADA/USDT:USDT")["last"]
account_huobi.create_order("ADA/USDT:USDT", "limit", "buy", amount, huobiADA,params_huobi_open)

so i get insufficient margin available error after im trying to create LONG order also i tried swap in defaultType and can create long order by hand in Huobi website.

Thanks !

**Comment by carlosmiei** [comment]
Hello @flav1ooo,

When dealing with swaps we usually measure them in contracts, so the amount=1 means 1 contract, amount=2 means 2 contracts, etc. 

Each exchange has its own contract definition and for Huobi (for this particular example) 1 contract has the value of 10 ADA (regardless of the base asset price)

**Example:**
limit order where ADA price = 1 --> 1 contract ---> 10 Ada -> Cost 10 usd
limit order where ADA price = 0.5 --> 1 contract ---> 10 Ada -> Cost 5 usd

We also have to take into consideration things like leverage when doing these calculations. 

Just to sum up, if you please an order with the price let's say 1 USD and amount 5,  you're creating an order for 5 contracts = 50 ADA so you would need to have at least 50usd in your account.

Hope this answers your question. Thank you!

**Comment by flav1ooo** [comment]
So how can i change leverage before create order ?

**Comment by flav1ooo** [comment]
> Hello @flav1ooo,
> 
> When dealing with swaps we usually measure them in contracts, so the amount=1 means 1 contract, amount=2 means 2 contracts, etc.
> 
> Each exchange has its own contract definition and for Huobi (for this particular example) 1 contract has the value of 10 ADA (regardless of the base asset price)
> 
> **Example:** limit order where ADA price = 1 --> 1 contract ---> 10 Ada -> Cost 10 usd limit order where ADA price = 0.5 --> 1 contract ---> 10 Ada -> Cost 5 usd
> 
> We also have to take into consideration things like leverage when doing these calculations.
> 
> Just to sum up, if you please an order with the price let's say 1 USD and amount 5, you're creating an order for 5 contracts = 50 ADA so you would need to have at least 50usd in your account.
> 
> Hope this answers your question. Thank you!

So how can i change leverage before create order ?

**Comment by kroitor** [comment]
@flav1ooo you cannot buy less than one swap contract, contracts are traded in whole numbers usually, hence you can't buy 0.1 ADA/USDT, and the contract side of 1 ADA/USDT:USDT contact is 10 USDT:

- https://github.com/ccxt/ccxt/wiki/Manual#limits-and-precision

```JavaScript
~/ccxt $ node examples/js/cli huobi market ADA/USDT:USDT
2022-04-07T04:34:31.722Z
Node.js: v16.13.2
CCXT v1.78.20
huobi.market (ADA/USDT:USDT)
2022-04-07T04:34:32.989Z iteration 0 passed in 0 ms

{
  id: 'ADA-USDT',
  symbol: 'ADA/USDT:USDT',
  base: 'ADA',
  quote: 'USDT',
  baseId: 'ADA',
  quoteId: 'usdt',
  active: true,
  type: 'swap',
  linear: true,
  inverse: false,
  spot: false,
  swap: true,
  future: false,
  option: false,
  margin: false,
  contract: true,
  contractSize: 10, // << -----------------
  expiry: undefined,
  expiryDatetime: undefined,
  optionType: undefined,
  strike: undefined,
  settle: 'USDT',
  settleId: 'usdt',
  precision: { amount: 1, price: 0.000001, cost: undefined }, // << -----------------
  limits: {
    leverage: { min: 1, max: 1, superMax: 1 },  // << -----------------
    amount: { min: undefined, max: undefined },
    price: { min: undefined, max: undefined },
    cost: { min: 0, max: undefined }
  },
  info: {
    symbol: 'ADA',
    contract_code: 'ADA-USDT',
    contract_size: '10.000000000000000000',
    price_tick: '0.000001000000000000',
    delivery_date: '',
    delivery_time: '',
    create_date: '20201120',
    contract_status: '1',
    settlement_date: '1649318400000',
    support_margin_mode: 'all',
    business_type: 'swap',
    pair: 'ADA-USDT',
    contract_type: 'swap',
    trade_partition: 'USDT'
  },
  tierBased: false,
  percentage: true,
  taker: undefined,
  maker: undefined,
  feeSide: 'get',
  lowercaseId: 'ada-usdt',
  lowercaseBaseId: 'ada'
}
~/ccxt $
```

**Comment by flav1ooo** [comment]
> @flav1ooo you cannot buy less than one swap contract, contracts are traded in whole numbers usually, hence you can't buy 0.1 ADA/USDT, and the contract side of 1 ADA/USDT:USDT contact is 10 USDT:
> 
> * https://github.com/ccxt/ccxt/wiki/Manual#limits-and-precision
> 
> ```js
> ~/ccxt $ node examples/js/cli huobi market ADA/USDT:USDT
> 2022-04-07T04:34:31.722Z
> Node.js: v16.13.2
> CCXT v1.78.20
> huobi.market (ADA/USDT:USDT)
> 2022-04-07T04:34:32.989Z iteration 0 passed in 0 ms
> 
> {
>   id: 'ADA-USDT',
>   symbol: 'ADA/USDT:USDT',
>   base: 'ADA',
>   quote: 'USDT',
>   baseId: 'ADA',
>   quoteId: 'usdt',
>   active: true,
>   type: 'swap',
>   linear: true,
>   inverse: false,
>   spot: false,
>   swap: true,
>   future: false,
>   option: false,
>   margin: false,
>   contract: true,
>   contractSize: 10, // << -----------------
>   expiry: undefined,
>   expiryDatetime: undefined,
>   optionType: undefined,
>   strike: undefined,
>   settle: 'USDT',
>   settleId: 'usdt',
>   precision: { amount: 1, price: 0.000001, cost: undefined }, // << -----------------
>   limits: {
>     leverage: { min: 1, max: 1, superMax: 1 },  // << -----------------
>     amount: { min: undefined, max: undefined },
>     price: { min: undefined, max: undefined },
>     cost: { min: 0, max: undefined }
>   },
>   info: {
>     symbol: 'ADA',
>     contract_code: 'ADA-USDT',
>     contract_size: '10.000000000000000000',
>     price_tick: '0.000001000000000000',
>     delivery_date: '',
>     delivery_time: '',
>     create_date: '20201120',
>     contract_status: '1',
>     settlement_date: '1649318400000',
>     support_margin_mode: 'all',
>     business_type: 'swap',
>     pair: 'ADA-USDT',
>     contract_type: 'swap',
>     trade_partition: 'USDT'
>   },
>   tierBased: false,
>   percentage: true,
>   taker: undefined,
>   maker: undefined,
>   feeSide: 'get',
>   lowercaseId: 'ada-usdt',
>   lowercaseBaseId: 'ada'
> }
> ~/ccxt $
> ```

Ok i got it Thanks ! i bought 1 contract by  hand with 7 USDT and leverage . Is there any chance to set leverage before create order ?

**Comment by kroitor** [comment]
What is your verbose output:

```Python
account_huobi.verbose = True
account_huobi.create_order("ADA/USDT:USDT", "limit", "buy", 1, huobiADA, {'lever_rate':2,'offset':'open'})
```

?

**Comment by flav1ooo** [comment]
> 

I got 100 USDT on contract account in huobi now also i changed unit "Contract" to "Coin" so in my code amount = coin quantity but it still says "insufficient margin available"

**Comment by flav1ooo** [comment]
> What is your verbose output:
> 
> ```python
> account_huobi.verbose = True
> account_huobi.create_order("ADA/USDT:USDT", "limit", "buy", 1, huobiADA, {'lever_rate':2,'offset':'open'})
> ```
> 
> ?

fetch Request: huobi POST https://api.hbdm.com/linear-swap-api/v1/swap_order?AccessKeyId=ed2htwf5tf-45d9b9f0-8c3f3448-676b5&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2022-04-11T20%3A38%3A41&Signature=EaiZNr0c3h6KGYuHlBmkzKiA2xPt%2FGwfGxtcUphjlwA%3D RequestHeaders: {'Content-Type': 'application/json', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} RequestBody: {"contract_code":"ADA-USDT","volume":"10","direction":"buy","offset":"open","lever_rate":3,"price":"0.947964","order_price_type":"limit","channel_code":"AA03022abc","client_order_id":"3"}

fetch Response: huobi POST https://api.hbdm.com/linear-swap-api/v1/swap_order?AccessKeyId=ed2htwf5tf-45d9b9f0-8c3f3448-676b5&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2022-04-11T20%3A38%3A41&Signature=EaiZNr0c3h6KGYuHlBmkzKiA2xPt%2FGwfGxtcUphjlwA%3D 200 ResponseHeaders: {'Date': 'Mon, 11 Apr 2022 20:38:40 GMT', 'Content-Type': 'text/plain;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache, no-store, no-store', 'Expires': 'Thu, 01 Jan 1970 00:00:00 GMT', 'ReqId': '2cb9cc19388d8567567c471ac88b0572', 'ratelimit-remaining': '71', 'ratelimit-reset': '1649709523767', 'ratelimit-interval': '3000', 'ratelimit-limit': '72', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '6fa686f81d5463d4-ATL', 'Content-Encoding': 'gzip'} ResponseBody: {"status":"error","err_code":1047,"err_msg":"Insufficient margin available.","ts":1649709520771}
---------------------------------------------------------------------------
InsufficientFunds                         Traceback (most recent call last)
[<ipython-input-36-050cae85ff0e>](https://localhost:8080/#) in <module>()
     58 print(huobiEth)
     59 account_huobi.verbose=True
---> 60 account_huobi.create_order("ADA/USDT:USDT", "limit", "buy", amount, huobiEth,params_huobi_open)
     61 #while True:
     62  # print(account_huobi.fetch_ticker("ADA/USDT:USDT")["ask"])

7 frames
[/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py](https://localhost:8080/#) in throw_exactly_matched_exception(self, exact, string, message)
    552     def throw_exactly_matched_exception(self, exact, string, message):
    553         if string in exact:
--> 554             raise exact[string](message)
    555 
    556     def throw_broadly_matched_exception(self, broad, string, message):

InsufficientFunds: huobi {"status":"error","err_code":1047,"err_msg":"Insufficient margin available.","ts":1649709520771}
