### ISSUE TITLE
Gateio - swap - fetch_balance() does not account for 'order_margin' in calculating 'total' or 'used'

### ISSUE THREAD

**Issue by elitwilliams** [ccxt/ccxt#12648]
- OS: Windows
- CCXT version: 1.77.49

```
import ccxt
g = ccxt.gateio({"apiKey": "XXXXX", "options": {"defaultType": "swap"}, "secret": "XXXX"})
print(g.fetch_balance())
```

There is no error thrown, but the `total` and `used` values should be inclusive of the `order_margin` amount, and they currently are not. The `order_margin` value simply represents capital frozen for open limit orders. Comparing the ccxt `total` to the gateio `total` value will reveal the issue - see below example response with dummy values from one of our gateio accounts. The `order_margin` values are 0s in the ccxt code comment examples, which is likely why this was missed.

An easy fix would just be to use `total` from the gateio response for the ccxt `total`, which is correct, and add the `order_margin` amount to the current `used` amount.

```
{
    'info': [
    {
        'order_margin': '10834.01705442',  #   <-----   This should be added to all "total" and "used" amounts
        'point': '0',
        'bonus': '0',
        'history':
        {
            XXXXXXX
        },
        'unrealised_pnl': '-140.04463642463',
        'total': '69272.113609838708',
        'available': '55956.266010078328',
        'in_dual_mode': False,
        'currency': 'USDT',
        'position_margin': '2481.83054534038',
        'user': 'XXXXXXXX'
    }],
    'USDT':
    {
        'free': 55956.266010078325,
        'used': 2481.83054534038,
        'total': 58438.096555418706
    },
    'free':
    {
        'USDT': 55956.266010078325
    },
    'used':
    {
        'USDT': 2481.83054534038
    },
    'total':
    {
        'USDT': 58438.096555418706
    }
}
```

**Comment by elitwilliams** [comment]
I think you also need to add `unrealized_pnl` to the `total` amounts for an accurate reflection of total asset value, depending on how you guys account for that.

**Comment by samgermain** [comment]
@elitwilliams Thanks for pointing this out, I've fixed the issue in https://github.com/ccxt/ccxt/pull/12661
