### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by kizbitz** [ccxt/ccxt#1265]
- OS: On MacOS Sierra 10.12.6 (Running CCXT in a Docker container using Debian GNU/Linux 8) (jessie) as base
- Programming Language version: Python 3.6.4
- CCXT version: ccxt==1.10.693
- Exchange: GDAX
- Method: fetch_orders()

---

```
>>> o = gdax.fetch_orders()

... successful returned content removed ...

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/ccxt/gdax.py", line 376, in fetch_orders
    return self.parse_orders(response, market, since, limit)
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 949, in parse_orders
    array = [self.parse_order(order, market) for order in array]
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 949, in <listcomp>
    array = [self.parse_order(order, market) for order in array]
  File "/usr/local/lib/python3.6/site-packages/ccxt/gdax.py", line 338, in parse_order
    remaining = amount - filled
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```

**Comment by kizbitz** [comment]
After testing the other order functions the problem may be with *closed* orders. Fetching open orders works fine. `fetch_closed_orders()` returns the same error.

**Comment by kroitor** [comment]
@kizbitz can you please post verbose output?

```Python
>>> o.verbose = true
>>> o = gdax.fetch_orders()
```

?

**Comment by kizbitz** [comment]
After further digging and troubleshooting other method calls - I believe this was caused by my system timestamp being off more than a minute than the GDAX servers. I can't reproduce now so I'll go ahead and close.

If anyone runs across this issue in the future. Check for `ccxt.base.errors.ExchangeError: gdax {"message":"request timestamp expired"}` in the output logs and then confirm your system time is correct.

**Comment by kroitor** [comment]
@kizbitz ok, thanks for reporting back! One more hint: you really want to set up not just basic time synch, but a **very** frequent timesynch, like once every 10 minutes. This will save you a lot of time with other exchanges. Let us know if you have any other difficulties with it. Cheers!
