### ISSUE TITLE
binance watch ticker

### ISSUE THREAD

**Issue by pickmone** [ccxt/ccxt#12656]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

```
binance = ccxtpro.binance({'options': {'defaultType': 'future'}})

price = await binance.watchTicker('KSM/USDT')
```

```
Hi all, 

Just tried to run watchTicker on binance, but all bid, ask value come back as None. Is this a bug?

thank you, 
```

**Comment by kroitor** [comment]
> Just tried to run watchTicker on binance, but all bid, ask value come back as None. Is this a bug?

No, it's not a bug. The ticker will usually contain the OHLCV info for the past 24h, but will not necessarily include the bid/ask prices. Some exchanges will also fill-in the bidask prices, others will not. If you really need the bid/ask price, then you should watchOrderBook, instead of watchTicker.

**Comment by kroitor** [comment]
P.S. you can verify if the bidask info is present in the ticker WS updates by enabling the verbose mode: https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by pickmone** [comment]
ok, thank you for confirming

**Comment by pickmone** [comment]
Hi Kroitor, 

not sure if i am doing something wrong or it is because i m looking at swaps. 

the code is simply:

binance = ccxtpro.binance({'options': {'defaultType': 'future'}})

binance.verbose=True

price = await binance.watchTicker('BTC/USDT') 

but this is what i get as return, which doesn't seem to include bids and asks. But I guess this is just a Binance issue then.

2022-04-06T12:15:38.339Z connecting to wss://fstream.binance.com/ws with timeout 10000 ms
2022-04-06T12:15:38.571Z connected
2022-04-06T12:15:38.571Z ping loop
2022-04-06T12:15:38.572Z sending {'method': 'SUBSCRIBE', 'params': ['btcusdt@ticker'], 'id': 1}
2022-04-06T12:15:38.637Z pong WSMessage(type=<WSMsgType.PONG: 10>, data=bytearray(b''), extra='')
2022-04-06T12:15:38.637Z message {"id":1,"result":null}
2022-04-06T12:15:38.994Z message {"e":"24hrTicker","E":1649247338130,"s":"BTCUSDT","p":"-1819.10","P":"-3.892","w":"45666.84","c":"44914.60","Q":"0.001","o":"46733.70","h":"47188.00","l":"44349.70","v":"337912.420","q":"15431392799.00","O":1649160900000,"C":1649247338125,"F":2099049679,"L":2102125549,"n":3074666}

@kroitor On another note, I see on Binance Futures API Doc, there is another channel: <symbol>@bookTicker, which according to the doc returns the best bid and asks. 

![image](https://user-images.githubusercontent.com/81128701/161973245-c6eaa1b4-b72e-4197-80e9-dfc6a86240f5.png)

**Comment by kroitor** [comment]
> but this is what i get as return, which doesn't seem to include bids and asks. But I guess this is just a Binance issue then.

Exactly.

> @kroitor On another note, I see on Binance Futures API Doc, there is another channel: @bookTicker, which according to the doc returns the best bid and asks.

Yes, and you can use that with CCXT Pro:

- https://github.com/kroitor/ccxt.pro/blob/master/python/ccxtpro/binance.py#L59

```Python
binance = ccxtpro.binance({
    'options': {
        'defaultType': 'future',
        'watchTicker': {
            'name': 'bookTicker',
        },
    }
})
```

Let us know if that does not help.

**Comment by pickmone** [comment]
works, Thanks!
