### ISSUE TITLE
example for open positions is incorrect for FTX exchange

### ISSUE THREAD

**Issue by xarthurx** [ccxt/ccxt#12666]
For FTX, the received data of `exchange.private_get_positions()` use different `str` for `future` and `symbol`.
For instance, for the `GMT-PERP`, data returned from my account is like this:

```
{'collateral': manual-erased,
 'contractSize': None,
 'contracts': 1.0,
 'datetime': None,
 'entryPrice': 2.256,
 'info': {'collateralUsed': '0.228115',
          'cost': '-2.28115',
          'cumulativeBuySize': '0.0',
          'cumulativeSellSize': '1.0',
          'entryPrice': '2.28115',
          'estimatedLiquidationPrice': 'manual-erased',
          'future': 'GMT-PERP',
          'initialMarginRequirement': '0.1',
          'longOrderSize': '0.0',
          'maintenanceMarginRequirement': '0.03',
          'netSize': '-1.0',
          'openSize': '1.0',
          'realizedPnl': 'manual-erased',
          'recentAverageOpenPrice': '2.256',
          'recentBreakEvenPrice': '2.256',
          'recentPnl': 'manual-erased',
          'shortOrderSize': '0.0',
          'side': 'sell',
          'size': '1.0',
          'unrealizedPnl': '0.0'},
 'initialMargin': manual-erased,
 'initialMarginPercentage': 0.1,
 'leverage': 10,
 'liquidationPrice': manual-erased,
 'maintenanceMargin': manual-erased,
 'maintenanceMarginPercentage': manual-erased,
 'marginRatio': 0.0001,
 'marginType': 'cross',
 'markPrice': 2.28115,
 'notional': 2.28115,
 'percentage': -11.02,
 'side': 'short',
 'symbol': 'GMT/USD:USD',
 'timestamp': None,
 'unrealizedPnl': manual-erased}
```

notice that the `future` value is: `GMT-PERP` (which is the one I use to order)
However, the `symbol` value is: `GMT/USD:USD` (which should be the one used for index_by in the below example scripts)

https://github.com/ccxt/ccxt/blob/9d73ee5c2c7137d8bdea6f432fd067e1bbe25d17/examples/py/ftx-close-position-reduceOnly.py#L25-L29

**Comment by xarthurx** [comment]
It is the same for other types of futures: `BTC`, `ETH`, ...

**Comment by samgermain** [comment]
`GMT-PERP` is an example of an exchange specific id for a market, you can use it, but it will only work for FTX. For this reason, CCXT creates a unified symbol that looks like `GMT/USD:USD` that represents a market with a base of `GMT` and a quote of `USD` that is settled in `USD`. Unifying the symbols is a work in progress, but currently every exchange except Binance, Bitfinex, and Bybit uses these unified symbols for swap markets. [I created a PR](https://github.com/ccxt/ccxt/pull/12671) to update the example files to use the unified symbols. 

You can also [read the manual](https://docs.ccxt.com/en/latest/manual.html#contract-naming-conventions) to learn more about this naming convention.

**Comment by xarthurx** [comment]
@kroitor  @samgermain  
You see, I bought the `pro` version 2 days ago, and during the past two days, I've been encountering many issues about either the lib or the doc (YES, I'm also happy to contribute PRs, and I already did).

IMHO, I really don't think the library is mature enough to a stage where a monthly subscription ~ `$29` makes sense...
Software at this price usually provides a much better experience and tutorials.

I can accept a one-time payment for the current WIP stage, but a monthly subscription... I would think about it.

**Comment by xarthurx** [comment]
@samgermain 
The example script is still having problems when there's no open position and it tries to create a reduce-only order:

```
Traceback (most recent call last):
  File "C:\Users\xarthur\scoop\apps\miniconda3\current\envs\crypto\lib\site-packages\ccxt\base\exchange.py", line 647, in fetch
    response.raise_for_status()
  File "C:\Users\xarthur\scoop\apps\miniconda3\current\envs\crypto\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://ftx.com/api/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xarthur\source\repo\cryptoT\test.py", line 68, in <module>
    order = exchange.create_order(symbol, type, side, amount, price, params)
  File "C:\Users\xarthur\scoop\apps\miniconda3\current\envs\crypto\lib\site-packages\ccxt\ftx.py", line 1447, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\xarthur\scoop\apps\miniconda3\current\envs\crypto\lib\site-packages\ccxt\base\exchange.py", line 489, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\xarthur\scoop\apps\miniconda3\current\envs\crypto\lib\site-packages\ccxt\base\exchange.py", line 540, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\Users\xarthur\scoop\apps\miniconda3\current\envs\crypto\lib\site-packages\ccxt\base\exchange.py", line 536, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\xarthur\scoop\apps\miniconda3\current\envs\crypto\lib\site-packages\ccxt\base\exchange.py", line 663, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, r
equest_body)
  File "C:\Users\xarthur\scoop\apps\miniconda3\current\envs\crypto\lib\site-packages\ccxt\ftx.py", line 2220, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "C:\Users\xarthur\scoop\apps\miniconda3\current\envs\crypto\lib\site-packages\ccxt\base\exchange.py", line 554, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidOrder: ftx {"success":false,"error":"Invalid reduce-only order"}
```

May I ask how to handle the error?

**Comment by xarthurx** [comment]
OK, I can use a `    if position['contracts'] != 0:` to filter if there's a contract open.
Let me know if there's a better approach.

> @samgermain And is there a way to get the correct `symbol` from the name that appears on the website? For instance: `GMT-PERP` --> `GMT/USD:USD` by a function `get_symbol` to make the interface more user-friendly.

**Comment by samgermain** [comment]
> @samgermain The example script is still having problems when there's no open position and it tries to create a reduce-only order:
> May I ask how to handle the error?

A reduceOnly order is an order to exit out of a position either partially or fully, so if there is no open position, you will not be able to create a reduce only order. There's no position to reduce, so it's impossible.

> @samgermain And is there a way to get the correct symbol from the name that appears on the website?

```
exchange = ccxt.ftx({...})
exchange.load_markets()
market = exchange.market('GMT/USD:USD')
id = market['id']
```

> OK, I can use a if position['contracts'] != 0: to filter if there's a contract open.

That looks like a fine solution

**Comment by xarthurx** [comment]
> > @samgermain And is there a way to get the correct symbol from the name that appears on the website?
> 
> ```
> exchange = ccxt.ftx({...})
> exchange.load_markets()
> market = exchange.market('GMT/USD:USD')
> id = market['id']
> ```
> 

I want the reverse direction. `GMT-PERP` --> `GMT/USD:USD`
The former is what users usually get from the website.

**Comment by samgermain** [comment]
exchange = ccxt.ftx({...})
exchange.load_markets()
market = exchange.market('GMT-PERP')
symbol = market['symbol']
