### ISSUE TITLE
Bitfinex createMarketBuyOrder ..... error "bitfinex2 createOrder not implemented yet"

### ISSUE THREAD

**Issue by mikenew** [ccxt/ccxt#1266]
***Environment***
- OS: Mac
- Programming Language version: python 3.6.3
- CCXT version: 
- Exchange: Bitfinex
- Method: CreateOrder and CreateMarketBuyOrder

***Error Description***
Calling `CreateOrder` or `CreateMarketBuyOrder` results in an error: `error "bitfinex2 createOrder not implemented yet"` 

***Note***
The bitfinex exchange object contents: 
          `.....  'has': {  .....    'createOrder': True,  ..... } .....`

It would be good to have CreateMarketBuyOrder as part of the `has` dictionary as well.

***Simplified code***
```
import ccxt
import time
bfx = ccxt.bitfinex2()
bfx.apiKey = 'XXX'
bfx.secret = 'XXX'
print('BFX hasFetchOrder',bfx.hasFetchOrder)
print('BFX has fetch balance: ',bfx.has['fetchBalance'])
bfx.load_markets()

symbol1 = "QTUM/USD"
trade_amount = 10
bfx.createMarketBuyOrder(symbol1, trade_amount)
bfx.createOrder(symbol1,'Market','Buy',100)
```

***Error Message for createMarketBuyOrder***

> ---------------------------------------------------------------------------
> NotSupported                              Traceback (most recent call last)
> <ipython-input-69-984cd7ad8f0a> in <module>()
>       1 symbol1 = "QTUM/USD"
>       2 trade_amount = 10
> ----> 3 bfx.createMarketBuyOrder(symbol1, trade_amount)
> 
> /usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py in create_market_buy_order(self, symbol, amount, params)
>    1013 
>    1014     def create_market_buy_order(self, symbol, amount, params={}):
> -> 1015         return self.create_order(symbol, 'market', 'buy', amount, None, params)
>    1016 
>    1017     def create_market_sell_order(self, symbol, amount, params={}):
> 
> /usr/local/lib/python3.6/site-packages/ccxt/bitfinex2.py in create_order(self, symbol, type, side, amount, price, params)
>     355 
>     356     def create_order(self, symbol, type, side, amount, price=None, params={}):
> --> 357         raise NotSupported(self.id + ' createOrder not implemented yet')
>     358 
>     359     def cancel_order(self, id, symbol=None, params={}):
> 
> NotSupported: bitfinex2 createOrder not implemented yet

**Error Message for createOrder**

> ---------------------------------------------------------------------------
> NotSupported                              Traceback (most recent call last)
> <ipython-input-70-92f85d8cfd08> in <module>()
> ----> 1 bfx.createOrder(symbol1,'Market','Buy',100)
>       2 #  createOrder (market, type, side, amount,
> 
> /usr/local/lib/python3.6/site-packages/ccxt/bitfinex2.py in create_order(self, symbol, type, side, amount, price, params)
>     355 
>     356     def create_order(self, symbol, type, side, amount, price=None, params={}):
> --> 357         raise NotSupported(self.id + ' createOrder not implemented yet')
>     358 
>     359     def cancel_order(self, id, symbol=None, params={}):
> 
> NotSupported: bitfinex2 createOrder not implemented yet

**Comment by kroitor** [comment]
For bitfinex2 – this is their experimental Bitfinex API v2 (it's raw and they don't guarantee that it works), and v2 does not offer an endpoint for creating orders at all. This is not because we can't implement it, it's just because their v2 does not offer that yet. So, for trading with Bitfinex, use v1 (the stable version of it).

Does this answer your question?

**Comment by mikenew** [comment]
OK thanks that's clear!

Would be good to change the `'createOrder': True,` flag on the Bitfinex v2 exchange object to `False`

Again thanks for your help ...

**Comment by fluffytid** [comment]
I have same problem, when I use bitfinex it fails to fetch, when I use bitfinex2 it has no create order yet. Kind of stuck.

**Comment by kroitor** [comment]
> when I use bitfinex it fails to fetch

Can you please be more specific? I mean, how it fails, in particular, maybe, show your verbose output? https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by fluffytid** [comment]
Sorry newbie here, 

	var bf = new ccxt.bitfinex () ;
	bf.apiKey = "xxx";
	bf.secret = "xxxx";
	var symbol = "XRP/USD";
	var side = "sell";
	var type = "limit";
	var ammount = "5";
	var price = "3";
	
	var z = await bf.createLimitSellOrder(symbol, ammount, price);



this will lead to a catch wich shows the following:

TypeError: Failed to fetch

I get this error when I try to loadmarkets with bitfinex, I have been using bitfinex2 since I found it worked better.

**Comment by kroitor** [comment]
@fluffytid try this and paste here what you see (assuming you have node 8 or higher, check that with `node --version`):

```
'use strict';
const ccxt = require ('ccxt')
const bf = new ccxt.bitfinex ({
    apiKey: 'YOUR_API_KEY',
    secret: 'YOUR_SECRET',
}) 
const symbol = "XRP/USD";
const amount = 5; // ←----------- amount and price should be numbers, not strings !
const price = 3;

(async () => {
    try {
        const order = await bf.createLimitSellOrder(symbol, amount, price);
        console.log (order);
        console.log ('Order placed successfully');
    } catch (e) {
        console.log (e.constructor.name, e.message);
        throw e
    }
}) ()
```

The above snippet should print a clear error message for the erroneous order (obviously, 3 and 5 are bad parameters).

You might want to see this:
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/tree/master/examples

**Comment by fluffytid** [comment]
Thank you, but I am not using nodejs.

**Comment by kroitor** [comment]
@fluffytid oh, sorry, then you really should have started by describing your environment first )

**Comment by kroitor** [comment]
```Python
import ccxt
bf = ccxt.bitfinex({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
symbol = "XRP/USD"
amount = 5  # ←--------------- should be a number, not a string!
price = 3  #  ←----------------- should be a number, not a string!
exchange.load_markets()
exchange.verbose = True
order = bf.create_limit_sell_order(symbol, amount, price)
print(order)

**Comment by fluffytid** [comment]
I tested this:

try
{
var bf = new ccxt.bitfinex({
    'apiKey': apibf,
    'secret': prapibf,
})
var symbol = "XRP/USD";
var amount = 5 ;// # ←--------------- should be a number, not a string!
var price = 3 ; //#  ←----------------- should be a number, not a string!
bf.load_markets();
bf.verbose = true;
var order = bf.create_limit_sell_order(symbol, amount, price);
pr(order);
}
catch (e)
{
	alert(e);
}

And I think since the loadmatrkets has no await it is doing nothing, it will just post "bitfinex" and then {}

I have been unable to use loadmarkets from the start with bitfinex v1, and that is the main problem I think. It says typerror, failed to fetch. And when I try to create order, it will try to loadmarkets firsts and fail to fetch.

**Comment by fluffytid** [comment]
Going to sleep, so don't go crazy about it now. I really think the problem lies in loadmarkets, not in createorder. Loadmarkets fails to fetch.

**Comment by kroitor** [comment]
@fluffytid need to know more about your environment, the OS, the programming language version, ccxt version.

**Comment by fluffytid** [comment]
xampp 3.2.2, Chrome latest update, Windows 7 and windows 10, ccxt const version = '1.10.738'.

On either OS I get:

await gdax.loadMarkets() -> success
await bitfinex2.loadMarkets() -> success
await bitfinex.loadMarkets() -> Type Error: Failed to fetch.

Tomorrow if you think it is useful I can try more exchanges so you can find the difference between those.

**Comment by fluffytid** [comment]
I found a better tool, and I got more info on my problem:

Failed to load https://api.bitfinex.com/v1/symbols_details: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by kroitor** [comment]
@fluffytid https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin

**Comment by fluffytid** [comment]
I wanted to thank you Igor, but I couldn't, because the extension I found for chrome to do the cors has made me unable to answer here, or watch youtube, or use facebook :)

I finally found how to disable it. Now I got through this, I've found this one:

Failed to load https://api.bitfinex.com/v1/order/new: Response for preflight has invalid HTTP status code 404

Will work on it. Thanks a lot for your support.

**Comment by jjhesk** [comment]
hi, for now i have all calls using bitfinex2 is that possible to kick back into v1 when making call for `createOrder` ?

**Comment by kroitor** [comment]
@jjhesk yeah, that is what we were going to do actually ) Will let you know, of course) Thx!

**Comment by AndrejLischishin** [comment]
Hi @kroitor,
is there any update about createOrder with bitfinex2, maybe in some other branch?

**Comment by kroitor** [comment]
@AndrejLischishin there's no v2 endpoint for placing orders in the Bitfinex's REST API, so I'd recommend to use v1 for that.

**Comment by AndrejLischishin** [comment]
@kroitor got you,
is there any smart way to use both versions v1 and v2 in the same script, or should i just create two exchange objects?

**Comment by kroitor** [comment]
> is there any smart way to use both versions v1 and v2 in the same script, or should i just create two exchange objects?

Well, in general, whatever you might need from v2 is available in some way via v1, so, I would recommend to use v2 only if you want some specific feature of v2, and for everything else – use v1. I mean, you can get away with just one v1 object, you don't need both most likely.

**Comment by AndrejLischishin** [comment]
@kroitor , I need v2 because I am using @lfern's implementation of websockets, that is why the whole circus. Thank you

**Comment by kroitor** [comment]
@AndrejLischishin well, yes, in that case, you would need to mix them. But still, because @lfern's implementation of WS does orderbooks only – I'd have v2 for just the orderbooks and v1 for everything else. Hope this helps.
