### ISSUE TITLE
bitstamp - fetch_ledger returns error TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by derki-source** [ccxt/ccxt#12667]
- OS: any
- Programming Language version: python
- CCXT version: 1.73.1, 1.78.20

you need to have valid movements in FIAT currency and than call 
```
bitstamp.fetch_ledger()
```

**Error:**
```
File "/usr/local/lib/python3.10/site-packages/ccxt/bitstamp.py", line 1442, in parse_ledger_entry
 TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Reason:**
bitstamp have inconsistent currency id for fiat currency, eg. id for EUR is "EUR" but transaction key is "eur"

so line 1450 bitstamp.py
amount = self.safe_number(item, currencyId) will return None
which is than compared on line 1451 bitstamp.py 

easy fix is just to force lower() on currencyId at line 1449

**Comment by samgermain** [comment]
Thanks for pointing this out, I've push a fix in this PR https://github.com/ccxt/ccxt/pull/12672

**Comment by derki-source** [comment]
its not fixed, the problem is that currencies_by_id have small cap key eg "eur", and you are trying to find "EUR", that wont be found and you will take default which is again "EUR" ...

so the currencyId is again capital EUR and produces the same error.
