### ISSUE TITLE
You applying broker code when sending orders,  i cant receive affilate bonus because of this...

### ISSUE THREAD

**Issue by mustafademiray1** [ccxt/ccxt#12678]
When i use your library with my own algorithm, i didn't get referral bonus for 1 month. I'am trying to solve why can not i receive affilate bonus for 1 month. I have 30+ customers and their monthly volume over 50.000 usd per account. I researched and i find it. I used ccxt because of i think it is free.  But you implemented brokerId and referral links in okx.py folder. When you apply broker id to sending orders to okx, i cant receive affilate bonus. I think i didnt get affilate rewards from okx because of this reason. Why are you trick people ? I lost 750 USD because of this reason. You should say this information before when people want to use your library...

**Comment by kroitor** [comment]
Hi! I would suggest reaching out to the Binance Affiliate program support, cause based on the information we have, the referral code takes precedence over the broker code.

You can also disable and override all the settings, including the broker id, by specifying your own client order id with createOrder:

- https://docs.ccxt.com/en/latest/manual.html#overriding-unified-api-params

```Python
exchange.create_order(symbol, type, side, amount, price, {'clientOrderId': exchange.uuid22()})
```

You can also override all options and that is also documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-exchange-properties-upon-instantiation

```Python
exchange = ccxt.binance ({
    'options': {
        'broker': {
             'spot': undefined,
             'margin': undefined,
             'future': undefined,
             'delivery': undefined,
        },
    },
})
```

Hope that answers your question. Feel free to reopen this issue or just ask further questions if any.

**Comment by mustafademiray1** [comment]
'brokerId': 'e847386590ce4dBC',

        if clientOrderId is None:
            brokerId = self.safe_string(self.options, 'brokerId')
            if brokerId is not None:
                request['clOrdId'] = brokerId + self.uuid16()
        else:
            request['clOrdId'] = clientOrderId
            params = self.omit(params, ['clOrdId', 'clientOrderId'])

ClientOrderId is parameter, and im sure no one use this.
Your code applying broker Id when sending orders. Im working with OKX not Binance. Im talking with support for 1 month. They are not understand coding. Finally i found these codes in your okx.py file , but im soo sad because i lost 1 month because of this.

**Comment by kroitor** [comment]
@mustafademiray1 for OKX that would be almost identical:

```Python
order = exchange.create_order(symbol, type, side, amount, price, {'clientOrderId': exchange.uuid16()})
```

```Python
exchange = ccxt.okx ({
    'options': {
        'brokerId': None,
    },
})
```

**Comment by mustafademiray1** [comment]
Thank you i changed this option to 'None'.
I read https://golangremotely.com/job/8494-ccxt-crypto-trading-developer this page and i understand.  You are making money from unconscious people like me :)
I have 30+ referral user. Can i get referral bonus from my affilate link after this ?

**Comment by kroitor** [comment]
@mustafademiray1 i would suggest reaching out to the Binance Referral program team, cause your referral id should take precedence over the broker id anyways, according to our info from Binance.

**Comment by mustafademiray1** [comment]
Im not working with Binance. I guess it's not like that in OKX...

**Comment by kroitor** [comment]
@mustafademiray1 you can still reach out to the OKX tech support on that, they can probably compensate it. The CCXT library is open-source and it comes under the MIT license. We obviously use the reflinks and other codes to fund the work on the library, but we also allow the users to override everything.
