### ISSUE TITLE
Binance Api Broken?

### ISSUE THREAD

**Issue by gerardo15** [ccxt/ccxt#1267]
Hello.

10 Hours ago Binance released a new API

Well.. first my robots all got banned.. lol..

not sure if the new api rate limits are per IP or per APIKEY.

Also i think autorization method now changed because i keep getting "Invalid API KEY or IP" message

https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

**Comment by kroitor** [comment]
> 10 Hours ago Binance released a new API

It was published several weeks ago and current version of CCXT integrates it.

> Well.. first my robots all got banned.. lol..
> not sure if the new api rate limits are per IP or per APIKEY.

Without any versions info or code from you it's hard to tell. Try updating the library first and recreating the keys.

> Also i think autorization method now changed because i keep getting "Invalid API KEY or IP" message

This should be covered by the most recent version of CCXT.

Hope it answers your questions, let us know if not.

**Comment by orkenstein** [comment]
@gerardo15 probably you get banned because of violation of limits:
`418 I'm a Teapot {"code":-1003,"msg":"Way too many requests; IP banned until 1516180405741."}`
Have you seen this?
@kroitor another problem, that there's no `429 DDoSProtection`. I can see only 418 right away.
