### ISSUE TITLE
Huobi Futures bugs detected

### ISSUE THREAD

**Issue by TayTech** [ccxt/ccxt#12670]
Hi, very greate job on this library, is not easy to manage all. (sorry for my english)
I'm using it for huobi and on spot trading is good, but for the features I'm not find it easy for those reasons:

- the fetchAccount method is calling only the spot account and not any futures
- in some methods mapping from isolated or cross management are missing
- in other there are linearSwap missing despite the fact that the methods to call are implemented

I get to knew that were missing after looking at these code:  https://github.com/ccxt/ccxt/blob/master/js/huobi.js

and going verbose mode otherwise I couldn't get how everything wasn't returning the right results.

**Comment by kroitor** [comment]
Hi!

> the fetchAccount method is calling only the spot account and not any futures

Which endpoint is in question?

For spot-market accounts Huobi has this endpoint: https://huobiapi.github.io/docs/spot/v1/en/#get-all-accounts-of-the-current-user

There is no such endpoint for futures, however. Huobi has these endpoints, but that is the information corresponds to the fetchBalance and fetchPositions unified methods, not fetchAccounts: https://huobiapi.github.io/docs/dm/v1/en/#query-user-s-account-information

Can you list out the links to the Huobi API docs on the account endpoints for futures? (Not margin balances, but the accounts specifically). 

> in some methods mapping from isolated or cross management are missing

If possible, please elaborate a bit, which methods?

> in other there are linearSwap missing despite the fact that the methods to call are implemented

`linearSwap` is deprecated use these options to drive it: 

- `defaultType` https://github.com/ccxt/ccxt/blob/master/js/huobi.js#L822
- `defaultSubType` https://github.com/ccxt/ccxt/blob/master/js/huobi.js#L823
- `marginType` ( 'cross' or 'isolated')
- https://docs.ccxt.com/en/latest/manual.html#exchange-properties
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-exchange-properties-upon-instantiation

Also, check the examples in this issue for reference:

- https://github.com/ccxt/ccxt/issues/11606

**Comment by TayTech** [comment]
Hi, thanks for replying

About: "There is no such endpoint for futures, however. Huobi has these endpoints, but that is the information corresponds to the fetchBalance and fetchPositions unified methods, not fetchAccounts: https://huobiapi.github.io/docs/dm/v1/en/#query-user-s-account-information"
=> Ok, I see, but calling fetchBalance it calls "contractPrivatePostLinearSwapApiV1SwapCrossAccountInfo" that I think is not showing me informations about isolated balance (which I need)

**Comment by kroitor** [comment]
@TayTech you can switch your default margin type like this, please read the links posted above for more details:

```JavaScript
const exchange = new exchange.huobi ({
    'options': {
        'defaultType': 'swap', // 'spot', 'swap', 'future',
        'defaultSubType': 'linear', // 'linear', 'inverse',
        'defaultMarginType': 'isolated',
    },
})
```

**Comment by kroitor** [comment]
Closing this issue for now, feel free to reopen it or just ask further questions if any.

**Comment by TayTech** [comment]
Sorry, I still can't check the balance on the linear swap account, this is the exchange:
`const ex = new ccxt.huobi({
    ...keys,
    enableRateLimit: true,
    options: {
      defaultType: 'swap',
      defaultSubType: 'linear',
      defaultMarginType: 'isolated'
    }
  });`

I've activated the login in order to be able to see on the web what was the bot doing, this is the call:
`const bal = (await exchange.fetchBalance()).info.data;`

And this is the result of the verbose mode:
`.
.
.
fetch Request:
 huobi GET https://api.hbdm.com/swap-api/v1/swap_contract_info 
RequestHeaders:
 {
  'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36'
} 
RequestBody:
 undefined 

handleRestResponse:
 huobi GET https://api.hbdm.com/swap-api/v1/swap_contract_info 200 OK 
ResponseHeaders:
 {
  'Cache-Control': 'no-cache, no-store',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '6f850939290da258-FCO',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'text/plain;charset=UTF-8',
  Date: 'Thu, 07 Apr 2022 19:05:40 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Expires: 'Thu, 01 Jan 1970 00:00:00 GMT',
  Pragma: 'no-cache',
  'Ratelimit-Interval': '3000',
  'Ratelimit-Limit': '120',
  'Ratelimit-Remaining': '119',
  'Ratelimit-Reset': '1649358343149',
  Reqid: '5c2234twf4343fd895813a54b6323',
  Server: 'cloudflare',
  'Transfer-Encoding': 'chunked',
  Vary: 'Accept-Encoding'
} 
ResponseBody:
 {"status":"ok","data":[{"symbol":"B

fetch Request:
 huobi POST https://api.hbdm.com/linear-swap-api/v1/swap_cross_account_info?AccessKeyId=34343-ac8f0&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2022-04-07T19%3A05%3A40&Signature=SignlM%3D 
RequestHeaders:
 {
  'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36',
  'Content-Type': 'application/json'
} 
RequestBody:
 {} 

handleRestResponse:
 huobi POST https://api.hbdm.com/linear-swap-api/v1/swap_cross_account_info?AccessKeyId=mykey&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2022-04-07T19%3A05%3A40&Signature=kvjG8F7wzQd580FlhxCNoN707tipStir75dufYSjwlM%3D 200 OK `

**Comment by kroitor** [comment]
@TayTech we've merged a fix by @carlosmiei , please, upgrade your version of CCXT to 1.78.42+ , the new build will arrive in ~20 minutes. Let us know if that solves the issue on your side or not (using the same code above). Thank you!

**Comment by TayTech** [comment]
You guys are GREEEEEAT!!!!!!!!
