### ISSUE TITLE
Please add Indian exchanges like zebpay, unicoin

### ISSUE THREAD

**Issue by chsivateja** [ccxt/ccxt#1268]
Please add Indian exchanges like zebpay, unicoin
__
[EDIT] removed: _koinex([deprecated](https://medium.com/koinex-crunch/koinex-shutdown-announcement-termination-of-exchange-services-bea4a472ea79))_, coinome(_deprecated_), coinbase(_integrated_), coindelta([_deprecated_](https://coindelta.com))

**Comment by BigBull90** [comment]
Please add Indian exchanges like koinex, zebpay, coinome, coinbase, unicoin, coindelta. They are missed out completely now.

**Comment by jjhesk** [comment]
@BigBull90 please list them one by one. its the best to provide each exchange with their API guide URL and its company background information for each ticket. so that people can follow one by one.

**Comment by kroitor** [comment]
Didn't know Coinbase is an Indian exchange )

**Comment by jjhesk** [comment]
@BigBull90 the above exchanges are not trading with high volume in the market and it will put into low priority to support it.

**Comment by kroitor** [comment]
> Should I create a new issue to track progress or a new PR?

As you wish ) We welcome all contributions, but, please, make sure to read this first: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

Thx! )

**Comment by gauraviitr** [comment]
@kroitor Thanks for working on this! Any update on the ETA? 
Appreciate the effort

**Comment by kroitor** [comment]
@gauraviitr how to get to it soon, currently have 25+ pull requests to merge ))

**Comment by zuntah** [comment]
Thank you! :)

**Comment by parthi2929** [comment]
Hi

Its 2019 and koinex still not available. Any update?

**Comment by kroitor** [comment]
@parthi2929 

> Its 2019 and koinex still not available. Any update?

Koinex: _"Trading on all our platforms will be suspended at 2 PM IST, 27th June 2019"_.

- https://medium.com/koinex-crunch/koinex-shutdown-announcement-termination-of-exchange-services-bea4a472ea79
- https://koinex.in

<img width="1532" alt="Screen Shot 2019-12-18 at 22 35 45" src="https://user-images.githubusercontent.com/1294454/71117328-fed83b80-21e6-11ea-99cc-914fd693f723.png">

**Comment by frosty00** [comment]
not a priority
