### ISSUE TITLE
MEXC market orders not supported

### ISSUE THREAD

**Issue by Silur** [ccxt/ccxt#12696]
```
import ccxt
mexc = ccxt.mexc({'apiKey': '...', 'secret': '...'})
exchange.createMarketBuyOrder('TRX/USDT', 1)
```
results in:
```
raise InvalidOrder(self.id + ' createOrder() does not support ' + type + ' order type, specify one of LIMIT, LIMIT_ORDER, POST_ONLY or IMMEDIATE_OR_CANCEL
```

However MEXC API does support market orders.
Issue present in CCXT 1.78.43

**Comment by Dan-krm** [comment]
Version 2 of the Mexc spot API doesn't support market orders. There is an upgrade to version 3 of the api that will be finished soon that should support market orders. #12376

**Comment by bachapk** [comment]
Changed from mexc to mexc3 via the following code:
`mexc = ccxt.mexc3({
    'apiKey': '--------------',
    'secret': '--------------',
})`

and now the following error are showing:
"BadRequest mexc3 {"msg":"api market order is disabled","code":30019}"

 p.s. I am using the latest ccxt version, installed via pip for python 3.7

**Comment by kroitor** [comment]
> "BadRequest mexc3 {"msg":"api market order is disabled","code":30019}"

That error message is coming from the exchange directly, apart from the support on the CCXT side, those market orders also have to be enabled on the exchange side. In this case they are disabled for your symbol, or maybe for all symbols. I'd suggest asking MEXC about it.

**Comment by bachapk** [comment]
Thank you :)

**Comment by block98ct** [comment]
Error placing order on MEXC Global: mexc {"msg":"api market order is disabled","code":30051}
I also getting the same issue anyone knows how to resolve it??
