### ISSUE TITLE
ZB Exchange API updates (zb.com)

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1269]
Followed by the latest doc and announcement, the new update implementations from the official guide https://github.com/zb2017/api 

the previous talk #1024, #622
https://www.zb.com/i/developer/websocketApi#config

@kroitor @Deathamns 

ZB WebSocket address：wss://api.zb.com:9999/websocket 
The english translated api guide instruction
https://translate.google.com/translate?hl=en&sl=zh-CN&tl=en&u=https%3A%2F%2Fwww.zb.com%2Fi%2Fdeveloper%2FwebsocketApi

**Comment by kroitor** [comment]
This is fixed in #1300 and #1717. 

Related duplicate: #1269

Please don't forget to update ccxt to version 1.10.1234.

Thanks for reporting!
