### ISSUE TITLE
Getting USDT Balance

### ISSUE THREAD

**Issue by euphrates85** [ccxt/ccxt#12708]
- OS: Windows
- Programming Language version: Python 3.10
- CCXT version: 1.77.62

```
import ccxt
exchange = ccxt.binance({
    "apiKey": 'xxx,
    "secret": 'xxx',
})

import time
start = time.time()
balance = exchange.fetch_balance()
end = time.time()
print(end - start)
print(balance['free']['USDT'])
```

Hello,
I want to get my USDT balance with above code. It takes 2 seconds that seems too much to me. Is there a way to get the balance faster?
Thank you in advance.

**Comment by kroitor** [comment]
You're missing how market-loading and the rate limiter works, cause you're creating the exchange instance and reload the markets upon each launch of that script: 

- https://docs.ccxt.com/en/latest/manual.html#loading-markets
- https://docs.ccxt.com/en/latest/manual.html#rate-limit
- https://docs.ccxt.com/en/latest/manual.html#notes-on-rate-limiter

```Python
import ccxt
import time

exchange = ccxt.binance({
    "apiKey": 'xxx,
    "secret": 'xxx',
})

markets = exchange.load_markets()

while True:
    print('----------------------------------')
    start = time.time()
    balance = exchange.fetch_balance()
    end = time.time()
    print(end - start)
    print(balance['free']['USDT'])
```

Hope that answers your question.

**Comment by euphrates85** [comment]
Yes it helped, thanks a lot.
