### ISSUE TITLE
New Exchange: btctradeim

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1270]
url: https://www.btctrade.im
api: https://www.btctrade.im/help.api.html
company: COINCLOUD (HK) TECHNOLOGY CO.,LIMITED
country based: China
company registered: hong kong

**Comment by kroitor** [comment]
When I go here, they say, no API docs yet, unfortunately :(

<img width="1208" alt="screen shot 2018-01-15 at 11 27 18" src="https://user-images.githubusercontent.com/1294454/34933232-1a47137a-f9e7-11e7-8eae-e5a2c28130ee.png">

**Comment by jjhesk** [comment]
lets make it to the pending api list. once its ready, this thread can put back to the development flow

**Comment by kroitor** [comment]
@jjhesk as you say ) I've subscribed to their changes... If you are tracking that exchange, please, let us know if you have any news or updates on it.

**Comment by jjhesk** [comment]
@kroitor will update you in realtime!

**Comment by Deathamns** [comment]
It seems that is has the same engine as CoinEgg #1215.

**Comment by jjhesk** [comment]
@Deathamns can you verify?

**Comment by Deathamns** [comment]
No, that's why I said it seems. But, most probably it's the same.
