### ISSUE TITLE
phemex fetch_closed_orders()

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#12712]
Can you show me how to get ALL closed orders since inception with no limit with fetch_closed_orders..
im assuming have to use params and/or limit and/or since..

I appear to be getting only 100 orders without using those parameters.

Thanks

**Comment by kroitor** [comment]
@adamrg73 hi! I'd recommend going through this section of the Manual:

- https://docs.ccxt.com/en/latest/manual.html#pagination

You can also find some examples of using pagination here:

- https://github.com/ccxt/ccxt/tree/master/examples/

Let me know if that does not answer your question. Feel free to reopen it or just ask further questions if any.
