### ISSUE TITLE
New Exchange: LBank

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1271]
url: https://www.lbank.info/
api doc: https://www.lbank.info/api/api-overview
api doc english: https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=https%3A%2F%2Fwww.lbank.info%2Fapi%2Fapi-overview
based country: china
registered company: hong kong
detail: UNIT 04,7/F,BRIGHT WAY TOWER,NO.33 MONG KOK ROAD,KOWLOON HK.
telegram: https://t.me/LBankinfo

**Comment by Deathamns** [comment]
If no one has started implementing this, I might.

**Comment by noidasector56c20** [comment]
i want to get all ticker information in single api call but did not find any api or websokect . do anyone have suggestion?

**Comment by kroitor** [comment]
@noidasector56c20  

> but did not find any api or websokect

WS is not supported yet. More about it here: #56

**Comment by garciapd** [comment]
hi @Deathamns @kroitor , i was checking the create market order, and it seems that in the price i have to put the cost (price * amount) so it is shown properly on the trade list but i'm not sure if the mapping is ok or even following other exchanges, because the amount when i create the order is in "quote currency" and it should be in base currency right?

**Comment by kroitor** [comment]
@garciapd hi! We'll take a look, thanks for pointing it out! Are you using lbank or lbank2 btw?

**Comment by garciapd** [comment]
The issue I see is with lbank2, I'm using lbank2 for almost everything, but, there are some calls I still do with lbank because with lbank2 are not working

This work well (as far as i have seen) on lbank but not on lbank2
- fetchOrderBook
- fetchClosedOrders

**Comment by garciapd** [comment]
for the market orders, the price I think is not working as expected

and when fetch the order, the amount is on quote currency, which misleads also the "filled" calculation

**Comment by kroitor** [comment]
@garciapd what's your version number of CCXT?

**Comment by garciapd** [comment]
1.82.94

**Comment by ttodua** [comment]
> hi @Deathamns @kroitor , i was checking the create market order, and it seems that in the price i have to put the cost (price * amount) so it is shown properly on the trade list but i'm not sure if the mapping is ok or even following other exchanges, because the amount when i create the order is in "quote currency" and it should be in base currency right?

can you mention , do both buy/sell misbehaves that way, or only sell?

**Comment by garciapd** [comment]
Hi, looks like only Buy Market Order misbehaves, i'm attaching a picture comparing the different cases in [#13381](https://github.com/ccxt/ccxt/issues/13381)

**Comment by garciapd** [comment]
@ttodua @kroitor also this 2 methods are not working, just FYI

fetchOrderBook
fetchClosedOrders
