### ISSUE TITLE
Handle PHP 8.1 deprecation: Passing null to non-nullable parameters of built-in functions

### ISSUE THREAD

**Issue by spondec** [ccxt/ccxt#12719]
- OS: macOS Catalina
- Programming Language version: PHP 8.1
- CCXT version: 1.78.59

```
Basically, any example giving null as a separator to implode() will reproduce the error on PHP 8.1.
```

```
Stack trace:
#0 [internal function]: Whoops\Run->handleError(8192, 'implode(): Pass...', '/Users/...', 734)
#1 vendor/ccxt/ccxt/php/Exchange.php(734): implode(NULL, Array)
#2 vendor/ccxt/ccxt/php/FTX.php(2280): ccxt\Exchange::implode_params('orders', Array)
#3 vendor/ccxt/ccxt/php/Exchange.php(1539): ccxt\ftx->sign('orders', 'private', 'POST', Array, NULL, NULL)
#4 vendor/ccxt/ccxt/php/Exchange.php(1544): ccxt\Exchange->fetch2('orders', 'private', 'POST', Array, NULL, NULL, Array, Array)
#5 [internal function]: ccxt\Exchange->request('orders', 'private', 'POST', Array, NULL, NULL, Array, Array)
```
If empty separator is as designed, then the error can be suppressed by using the null coalescing operator, such as this: 
```
$string = implode($value ?? '', mb_split('{' . preg_quote($key) . '}', $string));
```

This deprecation may affect the use of various internal PHP functions in the future. Please see: https://www.php.net/manual/en/migration81.deprecated.php

> **Passing null to non-nullable parameters of built-in functions**
> 
> Scalar types for built-in functions are nullable by default, this behaviour is deprecated to align with the behaviour of user-defined functions, where scalar types need to be marked as nullable explicitly.

**Comment by ttodua** [comment]
Late reply, but can you please tell how you reached this line:
> #5 [internal function]: ccxt\Exchange->request('orders', 'private', 'POST', Array, NULL, NULL, Array, Array)

which method have you been using which causes null null there. please post a demonstrational snippet
