### ISSUE TITLE
how to get latest orderId by exchange.fetch_orders("BTC/USDT") in Binance

### ISSUE THREAD

**Issue by ctu1121** [ccxt/ccxt#12710]
Hi there,
I use exchange.fetch_orders("BTC/USDT") to get all information ( including orderId, status, clientOrderId,.......) 
within a period of time in Binance.
Please advise what is the code if I only want to get the latest orderId for "BTC/USDT". Thanks.

Charles

**Comment by DoctorSlimm** [comment]
@ctu1121 python or javascript?
