### ISSUE TITLE
Can't cancel Stop orders on Kucoin futures

### ISSUE THREAD

**Issue by maciekzygmunt** [ccxt/ccxt#12729]
Hi, i'm trying to cancel my stop orders with cancel_all_orders but it doesn't work. It only cancels only open orders, not stop orders.
When i'm trying to use fetch_open_orders() i get empty array.  How can i close them?

- OS:  Windows
- Programming Language version: Python
```
 client.cancelAllOrders(symbol='XBTUSDTM')
client.fetch_open_orders()
```
![image](https://user-images.githubusercontent.com/77489537/162782653-5fd3fb5f-2c08-49e9-8e33-277ec3f7d153.png)

**Comment by samgermain** [comment]
I've created a [PR](https://github.com/ccxt/ccxt/pull/12770) so that you can cancel and fetch stop orders by passing `"stop": true` via params to `cancelAllOrders` and `fetchOpenOrders` respectively

**Comment by samgermain** [comment]
The PR is merged, so I'm closing this issue now
