### ISSUE TITLE
kucoin - price limits are not set

### ISSUE THREAD

**Issue by SmartManoj** [ccxt/ccxt#12728]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version: 
- CCXT version: 1.78.63

max price = price * (1+priceLimitRate) 
min price = priceIncrement [Docs](https://docs.kucoin.com/#:~:text=the%20priceincrement%20field%20specifies%20the%20min%20order%20price%20as%20well%20as%20the%20price%20increment.)

**Comment by RenatoExpert** [comment]
Sorry?

**Comment by ttodua** [comment]
Thanks for report, I confirm it was missing. added a reference PR , which will fix it.

**Comment by ttodua** [comment]
late update, but as this issue was left open, i'm closing this, as limits are implemented on kucoin.
