### ISSUE TITLE
How to access the timestamp at which markets were loaded

### ISSUE THREAD

**Issue by HartS** [ccxt/ccxt#12730]
Is there an easy way to access the time at which markets were last loaded for an exchange instance? It'd be useful to be able to determine this programmatically from the instance data, so we could automatically refresh it after some period (e.g. every 4 hours). However, there's nothing in the `exchange.markets` object.

Is there another way to access this timestamp, or would you consider making it accessible in a property (such as how `.last_http_response` gives you the most recent response)?

**Comment by HartS** [comment]
Also, I can make a PR for this if it's something you'd be interested in merging

**Comment by kroitor** [comment]
@HartS your PRs are welcome! 

Design-wise, i think we should differentiate (a) the timestamp when the data was loaded from (b) the timestamp when the data was generated and reported by the exchange.

We could probably add timestamp (b) to the market structure, as for the timestamp (a) – since that information is generated on the client side, maybe we should keep it in the userland? I mean to get timestamp (a), you would do something like:

```Python
markets = exchange.load_markets()
when_markets_were_loaded = exchange.milliseconds()
```

What do you think on the above ?

**Comment by HartS** [comment]
I was definitely more interested in (I think) `(a)`, because it allows us to do something like, check the timestamp at which market info was last loaded; if older than a certain age, reload markets (allows us to stay in sync with new markets without spamming the exchange).

It's of course possible to do this on the client side as well, but would be really nice to have it in ccxt since that's a more persistent state stored in the client.

I'll also take a look at what exchanges are providing for the response, though, to see how I can reconcile that with potentilaly available exchange-provided information that a user might be interested in

**Comment by ttodua** [comment]
I think I would mark this as `wontfix` as all responses ccxt provides from exchange, is whatever data is provided from exchanges itself. in `fetchMarkets` response we don't have any place where it could be propagated (i am against adding the same value in each market-object, as it doesn't make any sense to add same unimportant timestamp to 1000's markets).
Moreover, `fetchMarkets` is not (should not be!) frequently used method and it's only called once per instantiation, however, if you want to keep track of it and refresh, I see that a perfect fit for userland code. If you want it to load once in several hours, I don't understand, why it wouldnt be best approach to store timestamp on client side (without need to know that timestamp from exchange, as even in worst scenario, the difference at maximum might be several seconds, and  several seconds absolutely play no difference if you are reloading it once in every X hours).

I know it's good that library had shorthands for everything user needs, but this case belongs to userland code.
Let us know if you have any further issue with CCXT.
