### ISSUE TITLE
New Exchange: bitsane

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1273]
api doc: https://bitsane.com/info-api
web url: https://bitsane.com/
priority: low
avg volume: https://coinmarketcap.com/exchanges/bitsane/

**Comment by jjhesk** [comment]
this exchange is in the list but its not too important as it doesnt have major volume in this exchange

**Comment by Deathamns** [comment]
I could take a shot at this one too.

**Comment by kroitor** [comment]
@Deathamns that would be awesome! I'm currently merging the cobinhood request.
