### ISSUE TITLE
New Exchange: rightbtc

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1274]
api doc: 
volume: https://coinmarketcap.com/exchanges/rightbtc/
ip tracking: https://tools.keycdn.com/geo?host=54.215.240.91
telegram: https://t.me/RightbtcExchange
priority: low

**Comment by jjhesk** [comment]
note: there is an api settings from the user profile security but the api doc url is not found from the research.

**Comment by Deathamns** [comment]
If no one has started implementing this, I might.
