### ISSUE TITLE
New Exchange: bitgrail

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1277]
api doc: https://bitgrail.com/api-documentation
volume: https://coinmarketcap.com/exchanges/bitgrail/
company info: BitGrail S.r.l., P.IVA: IT06791600486
based country: italy
priority: low
address: We use industry-standard data encryption technology and have implemented restrictions related to the storage of and the ability to access your personal information. Currently, BitGrail/WEBCOIN SOLUTIONS servers and business operations are entirely located in Europe (France, Italy and Netherlands).Please note that no transmission over the Internet or method of electronic storage can be guaranteed to be 100% secure.

**Comment by Deathamns** [comment]
If no one has started implementing this, I might.

**Comment by kroitor** [comment]
https://bitgrail.com/news

06 / 15 / 2018 15:00 UTC
On June 5, 2018, pursuant to the Tribunal of Florence orders, the Bitcoins contained in the company's wallets were seized and brought under control of the judicial authorities pending further Court decisions in the prebankruptcy proceeding.
