### ISSUE TITLE
Huobi cant creating INSTANT position in future or swap in any coin.

### ISSUE THREAD

**Issue by flav1ooo** [ccxt/ccxt#12787]
I am creating a futures limit order on the Huobi exchange, but although the price is the same as the price of the limit order I created, the order is waiting under the limit tab, not in positions sometimes it opens as position. Can't I open the order I created at the current price as a direct position, just like in binance? ( Like binance.create_order("ADA/USDT", "market", "buy", amount, None,param) )

My code is:
account_huobi = ccxt.huobi({
     "apiKey": 'api',
     "secret": 'secret',
     'options': {
         'defaultType': 'future', # or 'margin'
         "defaultSubType": "linear",
         'marginType': 'cross',  
     },
     "enableRateLimit":False

params_huobi_open = {"offset": "open","lever_rate":2}
params_huobi_close = {"offset": "close", "reduce_only": 1}
amount=1
huobiAda = account_huobi.fetch_ticker("ADA/USDT:USDT")["last"]
account_huobi.create_order("ADA/USDT:USDT", "limit", "buy", amount, huobiAda,params_huobi_open)

I just want to open position with instant price of coin.

I hope I have explained myself. Thanks!

**Comment by carlosmiei** [comment]
Hello again @flav1ooo , 
Basically, you want to place a market order so that is filled immediately but unfortunately, Huobi doesn't support market orders for futures/swaps so really there's nothing we can do about it. You can probably try to adjust the price a bit up or down (depending on if you're buying or selling) to increase your odds of being be matched as soon as possible

**Comment by flav1ooo** [comment]
> Hello again @flav1ooo , Basically, you want to place a market order so that is filled immediately but unfortunately, Huobi doesn't support market orders for futures/swaps so really there's nothing we can do about it. You can probably try to adjust the price a bit up or down (depending on if you're buying or selling) to increase your odds of being be matched as soon as possible

I hope I didn't give you a headache today :D Can you briefly explain the difference between future and swap?

**Comment by carlosmiei** [comment]
> I hope I didn't give you a headache today :D 
don't worry 🙂 

Very briefly, CCXT supports the following types of derivative contracts:
- `future` – for expiring futures contracts that have a delivery/settlement date [](https://en.wikipedia.org/wiki/Futures_contract)
- `swap` – for perpetual swap futures that don't have a delivery date [](https://en.wikipedia.org/wiki/Perpetual_futures)
