### ISSUE TITLE
Get available networks for exchanges

### ISSUE THREAD

**Issue by kursadaydin** [ccxt/ccxt#12795]
> QUESTION

- OS: Windows 10
- Programming Language version: Python 3.9.6
- CCXT version: 1.75.74

I need to list all appropriate networks which in BINANCE, HUOBI, KUCOIN etc.
There is a template of getting networks which works in BINANCE but not the others....
**How can i get all networks for all exchanges?**

Can @kroitor help?

I have found template which links below, but it gets default network but i need to get all networks
[https://github.com/ccxt/ccxt/blob/master/examples/py/fetch-create-deposit-address.py](url)

Thanks for helps
```
import os
import sys
from pprint import pprint

import ccxt  
import config as cfg


currency_code = 'USDT'  
exchange_id = 'kucoin'  

exchange_KUCOIN = ccxt.kucoin({

    'apiKey': cfg.KUCOIN_API_KEY,
    'secret': cfg.KUCOIN_API_SECRET,
    'password':cfg.KUCOIN_PASSWORD,
    'enableRateLimit': True,  

})

exchange_BINANCE = ccxt.binance({

    'apiKey': cfg.BINANCE_API_KEY,
    'secret': cfg.BINANCE_API_SECRET,
    'enableRateLimit': True,  

})

currencies =exchange_BINANCE.fetch_currencies()
pprint(currencies['BNB']['info']['networkList'])


```

**Comment by ttodua** [comment]
`networks` unification is work-in-progress in ccxt and is not yet fully unified across all exchanges. at this stage, they are available to be used/accessed only in several exchanges (mostly big & major exchanges), and not even all exchanges provide networks data through their API. 

What you've shown yourself, it's correct - binance includes that data in their api response for currencies, and you should access them from `info` property. You have to manually find-out such information for other exchanges too inside their `info` properties or using some specific implicit API calls for your target exchange.

You might also take a look of i.e.  `print (exchange_BINANCE .options)` object where you might see `networks` object and generally available networks for exchange.

**Comment by DoctorSlimm** [comment]
@kursadaydin try this it will get you all the networks listed in the 'options' 'network' property of each exchange as @ttodua stated, though these are by no means exhaustive and this feature is work in progress, but will at least give you a vague idea for which exchanges support networks and the extent of support (some exchanges support very few networks (eg: only ERC20, TRC20, and a couple others), whilst a few others support more networks, and most do not support the functionality at all).

```Python 
from pprint import pprint
import ccxt

exchange_ids = ccxt.exchanges
network_info_by_exchange = {}

for id in exchange_ids:
    exchange = getattr (ccxt, id) ()
    options = getattr (exchange, 'options')
    try:
        networks = options['networks']
        network_info_by_exchange[id] = networks
    except Exception as e:
        print(f'no network information for {id}')

pprint(network_info_by_exchange)
```

**Comment by kroitor** [comment]
> @kursadaydin try this it will get you all the networks listed in the 'options' 'network' property of each exchange 

@DoctorSlimm unfortunately, that won't help, cause options['networks'] don't contain all the networks, just a subset of unified network aliases that can be used across the exchanges. However, each exchange has many more networks, you can see them in the currencies in bybit, okx or huobi. In many cases that requires authentication:

```Python
from pprint import pprint
import ccxt
exchange = ccxt.okx({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'password': 'YOUR_PASSWORD',
})
markets = exchange.load_markets()
pprint(exchange.currencies['USDT']) 
```

**Comment by kroitor** [comment]
One more thing to add, this _networks_ aspect is going to be unified in the `'networks'` property of each currency, that will store those networks indexed by their unified names:

```Python
from pprint import pprint
import ccxt
exchange = ccxt.okx({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'password': 'YOUR_PASSWORD',
})
markets = exchange.load_markets()
pprint(exchange.currencies['USDT']['networks']) 
```

**Comment by ttodua** [comment]
the PRs and their statuses are listed here https://github.com/orgs/ccxt/projects/54/views/1
I suggest all ccxt users subscribed to announcements channel:
- https://t.me/ccxt_announcements
- https://discord.com/channels/690203284119617602/1057748769690619984

**Comment by aslanahmtv** [comment]
.loadMarkets() requires authentication. Is there a way to fetch networks without this method?
