### ISSUE TITLE
New Exchange: Mr. Exchange

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1279]
api doc: 
url: https://mr-ripple.com/ja, https://mr.exchange/en-JP
volume: https://coinmarketcap.com/exchanges/mr-exchange/
address: 株式会社 Mr. Exchange, Inc. 〒812-0011 福岡県福岡市博多区博多駅前4丁目-2番20号 C-9ビル8階-C, 10am-6pm (Monday-Friday) 8F Hakataekimae C-9 Bill, 4-2-20 Hakataekimae Hakata-ku, Fukuoka 812-0011, Japan 
company info: Mr. Exchange, Inc. https://mr.exchange/en-JP/about
based country: japan
priority: low

**Comment by An-Net** [comment]
Shutdown since 2018 June 11:

- https://mr.exchange/

![Снимок экрана 2020-03-25 в 20 27 11](https://user-images.githubusercontent.com/51840849/77566681-10606c00-6ed7-11ea-9c6e-a5b47bf77460.png)
