### ISSUE TITLE
Huobi swap incorrect response from Position call

### ISSUE THREAD

**Issue by TayTech** [ccxt/ccxt#12790]
Hi, as object, I'm using nodejs on huobi exchange, referring to this link https://github.com/ccxt/ccxt/blob/master/js/huobi.js I'm controlling my code.
Calling fetchPositions('BTC/USDT:USDT') in my opinion the returned data is incorrect as follows:
- 'entryPrice' should be 'cost_open'
- 'unrealizedProfit' should be profit

This is what I have now:
![Schermata 2022-04-14 alle 01 28 01](https://user-images.githubusercontent.com/93889593/163286009-66b62c2f-bd93-4d25-865d-92aa48489181.png)

**Comment by TayTech** [comment]
Hi, I don't know if I have to open another issue, but for semplicity I'll write it here:
On huobi swap exchange (like above) calling "fetchPosition('BTC/USDT:USDT')", with this parameter it tells me that there is not such symbol on huobi but I tought that on your methods I should use your symbols, so what I did was to change in huobi's symbol and it works (personally I don't think should be like that..).

Similarly like above the returned value is not perfectly correct:
- The property entryPrice is not showing cost_open but cost_hold
- The property position is undefined

![Schermata 2022-04-15 alle 09 56 13](https://user-images.githubusercontent.com/93889593/163542642-a589c970-820e-40e8-b1e0-7ea17f31c1cb.png)

**Comment by kroitor** [comment]
> Similarly like above the returned value is not perfectly correct:
> 
> * The property entryPrice is not showing cost_open but cost_hold

We will fix that

> * The property position is undefined

Our unified position structure does not a position property: https://docs.ccxt.com/en/latest/manual.html#position-structure
