### ISSUE TITLE
[Lbank] Add "fetchMyTrades" method

### ISSUE THREAD

**Issue by aFluxx** [ccxt/ccxt#12803]
- OS: Windows 11
- Programming Language version: PHP
- CCXT version: 1.79.2

FEATURE REQUEST:

Lbank doesn't have the fetchMyTrades method. Probably because it wasn't available when the exchange was implemented into CCXT.
It seems they now have an endpoint for this. https://docs.lbkex.net/en/#historical-transaction-details

I would like to make a feature request to add this to the Lbank features on CCXT

PS/ They added a bunch of new features for SPOT trading to their API:
https://docs.lbkex.net/en/#spot-trading
https://docs.lbkex.net/en/#quote-interface
https://docs.lbkex.net/en/#wallet-interface

**Comment by kroitor** [comment]
Lbank's fetchMyTrades will be added in this v2 PR very soon: https://github.com/ccxt/ccxt/pull/12311

**Comment by CEOBTCUNIVERSE** [comment]
Can I have my stuff back, ask zhaoqiong li to give me my personal effects,and tell Rex Jones ll to mind his own biz.

**Comment by CEOBTCUNIVERSE** [comment]
Or gwon dong gets john gonged

**Comment by aFluxx** [comment]
> Lbank's fetchMyTrades will be added in this v2 PR very soon: #12311

Awesome thanks! I searched through issues & PR's, but didn't come across that one!
