### ISSUE TITLE
New Exchange: abucoins

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1281]
api doc: https://docs.abucoins.com/#introduction, https://github.com/timmolter/XChange/blob/develop/xchange-abucoins/api-specification.txt
url: https://abucoins.com/
volume: https://coinmarketcap.com/exchanges/abucoins/
address: Rybaki 19/22 61-884 Poznań, Poland
company info: Abucoins Sp. z o.o. | REGON: 367914649 | VAT-ID: 7831762644 | KRS: 0000689296
based country: Poland
priority: low
note:

**Comment by Deathamns** [comment]
Similar to gdax API.

**Comment by npomfret** [comment]
They shut down.  Might as well close this.

**Comment by jpfleury** [comment]
Indeed. This exchange no longer exists, so this issue should be closed.
