### ISSUE TITLE
New Exchange: bitinka

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1282]
api doc: https://www.bitinka.com/bitinka/api_documentation
url: https://www.bitinka.com
volume: https://coinmarketcap.com/exchanges/bitinka/
address: Rybaki 19/22 61-884 Poznań, Poland
company info: Abucoins Sp. z o.o. | REGON: 367914649 | VAT-ID: 7831762644 | KRS: 0000689296
based country: Poland
priority: low
note:

**Comment by waclock** [comment]
Bitinka is peruvian

**Comment by An-Net** [comment]
Exchange is inactive.

- https://coinmarketcap.com/exchanges/bitinka/
- https://bitcointalk.org/index.php?topic=5137515.0
- https://www.coingecko.com/en/exchanges/bitinka
