### ISSUE TITLE
New Exchange: mercatox

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1283]
api doc: https://mercatox.com/docs, https://mercatox.com/public
url: https://mercatox.com/
volume: https://coinmarketcap.com/exchanges/mercatox/
address: UK
company info: MERCATOX  LTD, UK 
based country: UK
priority: low
note:

**Comment by gaardiolor** [comment]
FYI, Mercatox only has a public API.

**Comment by samjeckert** [comment]
any update on this?

**Comment by is0initial** [comment]
I really need support Mercatox in CCXT.

**Comment by is0initial** [comment]
+0.1 ltc  - it's me.

**Comment by kroitor** [comment]
@is0initial we'll do our best to prioritize it, thx so much for your contribution!

**Comment by paxpelus** [comment]
I would also love to see mercatox on ccxt

**Comment by Showgofar** [comment]
seems that they had added trade api

**Comment by frosty00** [comment]
no being worked on
