### ISSUE TITLE
ExchangeError is thrown for status code 429 in bitmex

### ISSUE THREAD

**Issue by kevyu** [ccxt/ccxt#1284]
In bitmex, ExchangeError is thrown for status code 429, it should throw DDoSProtection.

I think it is caused by handleErrors in bitmex.

------------

- OS: Windows
- Programming Language version: Javascript
- CCXT version: 1.10.713
- Exchange: Bitmex
- Method: fetchTicker

**Comment by kroitor** [comment]
Will fix this asap. Thx for reporting!

**Comment by kevyu** [comment]
thanks,  it seems the same problem in binance.

**Comment by kevyu** [comment]
by the way, is it possible to use exchange response headers for rate limit ? 
for example, bitmex includes headers below
```
"x-ratelimit-limit": 300
"x-ratelimit-remaining": 297
"x-ratelimit-reset": 1489791662
"Retry-After": "xxxx"
```
so I can use the header info to detemine the time to retry.

**Comment by kroitor** [comment]
> by the way, is it possible to use exchange response headers for rate limit ?

Will add that as well.

**Comment by kevyu** [comment]
The fix is not correct, I enable verbose and got the response as below:
```
bitmex GET https://www.bitmex.com/api/v1/instrument/activeAndIndices 429 Too Many Requests Object {} 
Response:
{"error":{"message":"Rate limit exceeded, retry in 2 seconds.","name":"RateLimitError"}}
```

It still return ```ExchangeError``` in method ```handleErrors``` of bitmex
