### ISSUE TITLE
ftx fetchOhlcv returns inconsistent results 

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#12855]
- OS: linux
- Programming Language version: python
- CCXT version: 1.79.19

the `fetch_ohlcv` request on ftx returns some strange, inconsistent resutls depending on parameters given.

Depending on the time within the candle (and on the pair - it's kinda random) - ccxt seems to be omitting the incomplete candle.

in it's most simple form (no additional parameter) the last candle is (sometimes) missing.
The result will also depend on the time within the candle and the pair - so it's not reproducible 100% of the time.

``` python
import ccxt
exchange = ccxt.ftx()

x = exchange.fetch_ohlcv(pair, timeframe='5m')
print(
    f"{datetime.now(tz=timezone.utc).isoformat()}, {limit=},  last-date: {datetime.fromtimestamp(x[-1][0] // 1000).replace(tzinfo=timezone.utc).isoformat()}")

> 2022-04-15T12:28:18.825696+00:00,  last-date: 2022-04-15T12:25:00+00:00
> 2022-04-15T12:21:20.123123+00:00, limit=1500,  last-date: 2022-04-15T14:15:00+00:00
```

Analyzing this a bit, it seems like ccxt is sending an undocumented (but working) parameter in `limit` to the exchange. 
The [documentation](https://docs.ftx.com/#get-historical-prices) does not mention this (or does no longer mention this parameter) - which makes it's behaviour unclear.

using a slightly different call 
`x = exchange.fetch_ohlcv(pair, timeframe='5m', limit=20)` - i always get the right "last" candle candle.

I've compiled a slightly "bigger" testcase - depend

``` python
import ccxt
exchange = ccxt.ftx()

import requests
pair = 'FTT/USD'

for limit in (1500, 20, 1500):
    x = exchange.fetch_ohlcv(
        pair, 
        timeframe='5m', 
        limit=limit, 
    )

    print(f"{datetime.now(tz=timezone.utc).isoformat()}, {limit=},  last-date: {datetime.fromtimestamp(x[-1][0] // 1000).astimezone(tz=timezone.utc).isoformat()}")
    url = f"https://ftx.com/api/markets/{pair}/candles?resolution=300&limit={limit}"
    r = requests.get(url)
    print("direct with limit ", r.json()['result'][-1]['startTime'], len(r.json()['result']))


    start_date = datetime.now() - timedelta(seconds=300 * limit)
    print(start_date)
    url = f"https://ftx.com/api/markets/{pair}/candles?resolution=300&start_time={int(start_date.timestamp())}"
    r = requests.get(url)
    print("nolimit ", r.json()['result'][-1]['startTime'], len(r.json()['result']))
    exchange.verbose = False
    x = exchange.fetch_ohlcv(
        pair,
        timeframe='5m',
        # limit=limit,
        # limit=1300,
        # limit=20,
        since=int(start_date.timestamp() * 1000)
    )
    exchange.verbose = False

    print(
         f"ccxt_since, {limit=}, {len(x)=}, last-date: {datetime.fromtimestamp(x[-1][0] // 1000).astimezone(tz=timezone.utc).isoformat()}")

    print(20 * "-")

```

``` output
2022-04-15T12:30:15.937353+00:00, limit=1500,  last-date: 2022-04-15T12:25:00+00:00  <-- Wrong candle - should be 12:30
direct with limit  2022-04-15T12:25:00+00:00 1499
2022-04-10 09:30:15.999850
nolimit  2022-04-15T12:30:00+00:00 1500
ccxt_since, limit=1500, len(x)=1500, last-date: 2022-04-15T12:30:00+00:00  
--------------------
2022-04-15T12:30:17.217232+00:00, limit=20,  last-date: 2022-04-15T12:30:00+00:00   <-- right candle
direct with limit  2022-04-15T12:30:00+00:00 20
2022-04-15 12:50:17.335706
nolimit  2022-04-15T12:30:00+00:00 20
ccxt_since, limit=20, len(x)=20, last-date: 2022-04-15T12:30:00+00:00
--------------------
2022-04-15T12:30:17.996662+00:00, limit=1500,  last-date: 2022-04-15T12:25:00+00:00 <-- Wrong candle again
direct with limit  2022-04-15T12:25:00+00:00 1499
2022-04-10 09:30:18.045789
nolimit  2022-04-15T12:30:00+00:00 1500
ccxt_since, limit=1500, len(x)=1500, last-date: 2022-04-15T12:30:00+00:00
--------------------
```

Interestingly, when using `since` in the call to `fetch_ohlcv` as well - the response changes and is always correct (see `ccxt_since` output above).

the same behavior can also be observed when we remove ccxt from the equation (so we use requests on the endpoint directly).
You'll also notice that the above calls were made right after the new candle starts.
if i wait until 12:34 (1 minute before the next candle) - the returned candles will usually be correct (but the time will differ).

While i can fix this pretty easily for my usage (always send "since") - i think you may want to change behavior of ccxt here - as in my understanding, calling `fetch_ohlcv` without any parameter should give you the latest `limit` candles, which currently depends on the time within the last candle - and is therefore kindof unreliable behavior.

**Comment by ttodua** [comment]
thnx for such thorough report. the best is that exchange fixed it, but if that will not happen (we had some advises sent to them specifically ohlcv endpoint, which is unreliable), then we will think to make an non-intrusive fix to this problem. I'll leave this issue open till taht time.
