### ISSUE TITLE
POST_ONLY fails when passing None to price

### ISSUE THREAD

**Issue by RoscoeTheDog** [ccxt/ccxt#12868]
Found a few bugs while trying to work with the Python version of this framework. This was recently installed a couple days ago (as of 4/16) so I should be on the latest build of CCXT. Python version is 3.8 .I am guessing this is specific issue with the MEXC exchange config, since it is not very popular exchange yet.

The problem:
The MEXC exchange doesn't seem to support market orders, according to the other error I encountered when invoking `create_market_order()`. So I took a different approach and used the generic `create_order()` method instead, passing in the order type when making the request. When invoking `exchange.create_order()` and passing `POST_ONLY` to `type`, the later call to `decimal_to_precision` from mexc.py does not check the price paramter for `None` first before trying to cast to string causing the error. Unless I am not understanding this correctly, `POST_ONLY` should behave similarly to a market order and post at the current market price when it reaches the exchange, therefore a price param should be optional here unless I am wrong about how POST_ONLY behaves. If I am wrong, then I think this error could still be handled a little more elegantly so it is clear if it is an end-user problem.

- OS: Windows 10 x64
- Programming Language version: Python 3.8
- CCXT version: Latest (pip check)

```
import json
import base64
import ccxt

api_key = ''
api_secret = ''

supported_exchanges = ['binance', 'coinbase', 'kucoin', 'kraken', 'mexc']


def lambda_handler(event, context):

    response = {
        'statusCode': 200,
        'headers': {'Content-Type': 'application/json'},
        'body': ''
    }

    body = event
    if body['api_key'] == api_key and body['api_secret'] == api_secret:

        exchange = 0

        for e in supported_exchanges:
        
            if str.lower(body['exchange']) == e:
                exchange_class = getattr(ccxt, body['exchange'])
                
                exchange = exchange_class({
                    'apiKey': body['api_key'],
                    'secret': body['api_secret'],
                    'enableRateLimit': True,
                })

        if exchange:
            response['body'] = exchange.create_order(symbol=body['symbol'],
                                        side=body['side'],
                                        type=body['type'],
                                        amount=body['amount']
                                        )
    return response

# test our code now with a local run, not through webhost
e = {
  "api_key": "",
  "api_secret": "",
  "exchange": "mexc",
  "symbol": "CHICKS/USDT",
  "side": "BUY",
  "type": "POST_ONLY",
  "amount": "5"
}

lambda_handler(e, 0)
```

```
Traceback (most recent call last):
  File "/home/aspen/PycharmProjects/pythonProject/main.py", line 102, in <module>
    lambda_handler(e, 0)
  File "/home/aspen/PycharmProjects/pythonProject/main.py", line 70, in lambda_handler
    order_results = exchange.create_order(symbol=body['symbol'],
  File "/home/aspen/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/ccxt/mexc.py", line 1678, in create_order
    return self.create_spot_order(symbol, type, side, amount, price, query)
  File "/home/aspen/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/ccxt/mexc.py", line 1700, in create_spot_order
    'price': self.price_to_precision(symbol, price),
  File "/home/aspen/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1417, in price_to_precision
    return self.decimal_to_precision(price, ROUND, market['precision']['price'], self.precisionMode, self.paddingMode)
  File "/home/aspen/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/ccxt/base/decimal_to_precision.py", line 55, in decimal_to_precision
    dec = decimal.Decimal(str(n))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

Here is also the traceback when passing "MARKET" to `type`
```
Traceback (most recent call last):
  File "/home/aspen/PycharmProjects/pythonProject/main.py", line 102, in <module>
    lambda_handler(e, 0)
  File "/home/aspen/PycharmProjects/pythonProject/main.py", line 70, in lambda_handler
    order_results = exchange.create_order(symbol=body['symbol'],
  File "/home/aspen/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/ccxt/mexc.py", line 1678, in create_order
    return self.create_spot_order(symbol, type, side, amount, price, query)
  File "/home/aspen/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/ccxt/mexc.py", line 1697, in create_spot_order
    raise InvalidOrder(self.id + ' createOrder() does not support ' + type + ' order type, specify one of LIMIT, LIMIT_ORDER, POST_ONLY or IMMEDIATE_OR_CANCEL')
ccxt.base.errors.InvalidOrder: mexc createOrder() does not support MARKET order type, specify one of LIMIT, LIMIT_ORDER, POST_ONLY or IMMEDIATE_OR_CANCEL
```

**Comment by kroitor** [comment]
> POST_ONLY should behave similarly to a market order and post at the current market price when it reaches the exchange, therefore a price param should be optional here unless I am wrong about how POST_ONLY behaves

A post only order is a limit order that will only be accepted if the price of the order does not cross the orderbook, so it will only be accepted if your limit price wouldn't cause it to be filled immediately. In other words, the post only flag enforces your order to hang at least a while on the orderbook. Just like any other limit order, a postOnly order must have a price.

More about the order matching here: https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades

Hope that answers your question. Feel free to reopen this issue or just ask further questions if any.
