### ISSUE TITLE
New Exchange: xt.com

### ISSUE THREAD

**Issue by aFluxx** [ccxt/ccxt#12865]
Hi there,

I was looking through the Github issues and I couldn't find any request for this exchange yet.

I will like to propose adding XT.com

Info:
https://github.com/xtpub/api-doc
https://github.com/xtpub/api-doc/blob/master/rest-api-v1-en.md
https://github.com/xtpub/api-doc/blob/master/websocket-api-v1-en.md

This exchange has 1B daily volume and is ranked 32th on Coinmarketcap

**Comment by nikess** [comment]
Just to note that this is now the THIRD largest derivatives exchange by volume (coingecko)
