### ISSUE TITLE
problems with M1 mac mini 

### ISSUE THREAD

**Issue by TayTech** [ccxt/ccxt#12871]
Hi, I recently moving my application on a M1 mac mini but I'm finding some issues:
- difficult installation (it takes from 80 to 100+ seconds to install)
- after installation is not correctly recognized by the editor (VS Code) in doing Quick fix, so I have to manually import the library
- calling exchange.loadMarkets() fails a lot of time giving RequestTimeout error

my ccxt version: 1.79.61
language used: Node.js
Exchange id: huobi
function used: loadMarkets

**Comment by kroitor** [comment]
Hi!

> difficult installation (it takes from 80 to 100+ seconds to install)

It works much faster for me, what's your version of Node.js / npm ? 

> after installation is not correctly recognized by the editor (VS Code) in doing Quick fix, so I have to manually import the library

CCXT is editor-agnostic, it's up to you to configure your editor how you want.

> calling exchange.loadMarkets() fails a lot of time giving RequestTimeout error

Please follow these guides literally to a word: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by TayTech** [comment]
I'm currently running nodejs v 17.9.0 with yarn

Request and response in verbose:
```
fetch Request:
 huobi GET https://api.huobi.pro/v2/reference/currencies 
RequestHeaders:
 {
  'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36'
} 
RequestBody:
 undefined 
```
Error message: "huobi GET https://api.huobi.pro/v2/reference/currencies request timed out (10000 ms)"
(I also tried increasing timeout to 50000ms but gives me the same error with different timing)

I'm writing in typescript v4.5.5
my ccxt version: 1.79.61
Exchange id: huobi
function used: loadMarkets

Code wrote:
```
const exc = new ccxt['huobi']({
      apiKey: --key--,
      secret: --secret--,
      verbose: true,
      enableRateLimit: true,
      options: {
        defaultType: 'swap',
        defaultSubType: 'linear' ,
        defaultMarginType: 'isolated' 
      }
  });
    
    
    await exc.loadMarkets(true);
```

**Comment by TayTech** [comment]
Hi, I also noticed that calls like for example get position with ccxt takes longer than normal calls, for ex. in binance with another library the response
is immediate, but with ccxt the same call takes like 4 or 5 seconds.
Is it normal? (this is doing it both with M1 and with i7 processors)
________________________________
Da: Igor Kroitor ***@***.***>
Inviato: domenica 17 aprile 2022 00:56
A: ccxt/ccxt ***@***.***>
Cc: TayTech ***@***.***>; Author ***@***.***>
Oggetto: Re: [ccxt/ccxt] problems with M1 mac mini (Issue #12871)


Hi!

difficult installation (it takes from 80 to 100+ seconds to install)

It works much faster for me, what's your version of Node.js / npm ?

after installation is not correctly recognized by the editor (VS Code) in doing Quick fix, so I have to manually import the library

CCXT is editor-agnostic, it's up to you to configure your editor how you want.

calling exchange.loadMarkets() fails a lot of time giving RequestTimeout error

Please follow these guides literally to a word: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by kroitor** [comment]
> Hi, I also noticed that calls like for example get position with ccxt takes longer than normal calls, for ex. in binance with another library the response is immediate, but with ccxt the same call takes like 4 or 5 seconds. Is it normal? (this is doing it both with M1 and with i7 processors)

It depends on how you measure it. You're probably measuring the market loading time, which isn't an entirely correct way of measuring it. That is documented in the Manual:

- https://docs.ccxt.com/en/latest/manual.html#loading-markets
- https://docs.ccxt.com/en/latest/manual.html#notes-on-rate-limiter

```JavaScript
const ccxt = require ('ccxt')

console.log ('CCXT Version:', ccxt.version)

async function main () {
    const exchange = new ccxt.huobi()
    const markets = await exchange.loadMarkets ()
    // exchange.verbose = true // uncomment for debugging purposes if necessary
    const symbol = 'BTC/USDT'
    let previousTimestamp = exchange.milliseconds ();
    while (true) {
        const ticker = await exchange.fetchTicker (symbol)
        const currentTimestamp = exchange.milliseconds ()
        console.log (symbol, ticker['last'], currentTimestamp - previousTimestamp, 'ms')
        previousTimestamp = currentTimestamp
    }
}

main ()
```

**Comment by TayTech** [comment]
My problem is that using huobi there is the problem of the settlement time, having a strategy that places the order on 4 hours conditions, some times
it tries to place it at the settlement time, so I call the
fetchMarketsByTypeAndSubType('swap', 'linear')
in order to extract the contract status in that moment but as it returns 1, after I place the order and fails immediatly.

________________________________
Da: Igor Kroitor ***@***.***>
Inviato: mercoledì 20 aprile 2022 23:45
A: ccxt/ccxt ***@***.***>
Cc: TayTech ***@***.***>; Author ***@***.***>
Oggetto: Re: [ccxt/ccxt] problems with M1 mac mini (Issue #12871)


Hi, I also noticed that calls like for example get position with ccxt takes longer than normal calls, for ex. in binance with another library the response is immediate, but with ccxt the same call takes like 4 or 5 seconds. Is it normal? (this is doing it both with M1 and with i7 processors)

It depends on how you measure it. You're probably measuring the market loading time, which isn't an entirely correct way of measuring it. That is documented in the Manual:

  *   https://docs.ccxt.com/en/latest/manual.html#loading-markets
  *   https://docs.ccxt.com/en/latest/manual.html#notes-on-rate-limiter

const ccxt = require ('ccxt')

console.log ('CCXT Version:', ccxt.version)

async function main () {
    const exchange = new ccxt.huobi()
    const markets = await exchange.loadMarkets ()
    // exchange.verbose = true // uncomment for debugging purposes if necessary
    const symbol = 'BTC/USDT'
    let previousTimestamp = exchange.milliseconds ();
    while (true) {
        const ticker = await exchange.fetchTicker (symbol)
        const currentTimestamp = exchange.milliseconds ()
        console.log (symbol, ticker['last'], currentTimestamp - previousTimestamp, 'ms')
        previousTimestamp = currentTimestamp
    }
}

main ()

**Comment by ttodua** [comment]
To add late notes additionally to above @ kroitor 's answer:
> calling exchange.loadMarkets() fails a lot of time giving RequestTimeout error

it seems strange, and I suspect that your location/IP whatever might be problem. In such cases, you might try that from another IP/VPN to find out if that will solve the problem (if so, then your IP is problem). otherwise, we definitely don't have that problem you describe (and no-one reported) so  that problem seems specific to your network/IP in my opinion.

about `fetchMarketsByTypeAndSubType('swap', 'linear')` - have you tried to put that in `try/catch` and whenever the order fails (after getting `1` as status) re-call that `fetchMarkets` to see if that status is changed, it means that in-between that call and createOrder, the status become closed, therefore causing that issue. You might setup your script to try to submit order few seconds earlier.

Let us know if you face further issues with CCXT or need help.
