### ISSUE TITLE
STEX - Uncaught (in promise) PermissionDenied: stex {     "message": "Invalid scope(s) provided." }

### ISSUE THREAD

**Issue by dmh1974** [ccxt/ccxt#12870]
I'm having difficulty getting stex private api to work

I have generated a server to server key and assigned it to exchange.token='<hash>'

I have also tried adding a custom headers {scope: 'profile reports'}

Any examples on how to instantiate Stex for private requests would be helpful.

Thank you!

**Comment by kroitor** [comment]
@dmh1974 please follow the guides literally to a word: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by dmh1974** [comment]
my appologies, i was trying to fetch open orders and did not give the appropriate scope permission when generating the key.
