### ISSUE TITLE
bibox: json issue with PHP

### ISSUE THREAD

**Issue by kornrunner** [ccxt/ccxt#1287]
- OS: archlinux
- Programming Language version: PHP
- CCXT version: 1.10.717
- Exchange: bibox
- Method: any

There's an issue with Bibox and `Exchange->json` due to second parameter `JSON_FORCE_OBJECT` passed to `json_encode`.

Bibox expects JSON request to look like:
```json
{"cmds":"[{\"cmd\":\"api\\\/marketAll\",\"body\":[]}]"}
```

However, with given parameter in PHP it looks like:
```json
{"cmds":"{\"0\":{\"cmd\":\"api\\\/marketAll\",\"body\":{}}}"}
```

And that causes all requests fail with response:
```json
{
  "error": {
    "code": "3000",
    "msg": "请求参数错误"
  }
}
```

 I believe we can't simply remove the `JSON_FORCE_OBECT` (don't know why was it introduced), especially as there aren't tests for PHP.
What solution would you suggest? (I'll be more than happy to submit a PR)

**Comment by kroitor** [comment]
> I believe we can't simply remove the JSON_FORCE_OBECT (don't know why was it introduced), especially as there aren't tests for PHP.

Yep, we can't, however, you see, I was too lazy to comment it properly, so now I have to remember, why I added it there in the first place, but I recall there was a problem with an exchange that wanted assoc arrays instead of plain lists. Let me get back to you on this after reviewing it.

> What solution would you suggest? (I'll be more than happy to submit a PR)

I would get rid of it, but let's make sure not to break anything first. I hope to be quick on this.

**Comment by kornrunner** [comment]
It seems it has been there from the very beginning:
https://github.com/ccxt/ccxt/commit/35ad58a8e49e2c27298a2a9e089a51e1f48f2cfe#diff-420ef125a6adce3355f82c1909e40d0aR478

**Comment by kroitor** [comment]
Well, that isn't the beginning, it's the beginning of ccxt.php, and before that everything was in one file + it was moved from folder to folder in recent months, so, it's quite hard to find the reason now ) But, if you're ok to wait a little, I'll come up with a reason for that. In other words, I would not add "just in case", I would only add it to fix a bug – that's what I'm sure of.

**Comment by kroitor** [comment]
Found it: https://github.com/ccxt/ccxt/commit/8878dcbe1d4e853dbbe2cafcb9e766f6652f3456#diff-c6deef1c2fc818f35b7d71a16d6fff0eR389

**Comment by kornrunner** [comment]
So, it should be cryptopia related if I'm reading that right?

**Comment by kroitor** [comment]
This commit: https://github.com/ccxt/ccxt/commit/7d6d14bb8a8dea4dab9fd6b729b670d16451c709

**Comment by kroitor** [comment]
> So, it should be cryptopia related if I'm reading that right?

Looks like it, really.

**Comment by kroitor** [comment]
Yet still, I can't see anything inside Cryptopia that would require a json-object (for now)...

**Comment by kroitor** [comment]
Unfortunately, can't really tell the exact reason. So... From here we have several options:
1. Delete it, cross fingers and see if breaks anything ) I don't really like it )
2. Make it an optional boolean flag ($associative=true or smth), supported by this.json ? I would add a few rules to the transpiler then.

**Comment by kornrunner** [comment]
I'm also for better safe than sorry. In PHP `json_encode` second param is for flags, and it's a bitmask, so it can take a variety of stuff (but bool flag for current use case would be sufficient).

Some other options:
- introduce jsonObject in base 
- override this.json in cryptopia (but I reckon it would make a mess in transpiler)

**Comment by kroitor** [comment]
Ok, I would prefer the added flag, or, maybe even the second config object (assoc array of various options) – this would be enough for all future needs, I think. Will add that soon.

**Comment by pursehouse** [comment]
I assume this is the same issue I'm having now

`Error : bibox {"error":{"code":"3000","msg":"\u8bf7\u6c42\u53c2\u6570\u9519\u8bef"}}`

If it is the array/object variant issue then it would make sense for each exchange to have a settings to define the format of their json packages

**Comment by kornrunner** [comment]
You can try kornrunner/ccxt package - it is in sync with ccxt/ccxt, but
json issue with bibox is mitigated for PHP

**Comment by kroitor** [comment]
@kornrunner Here it is! Got an example of it, at last!! ))) And yes, it is Cryptopia! )
- https://github.com/ccxt/ccxt/issues/1634
- https://github.com/ccxt/ccxt/commit/fe06a8836a5e6e59dfbe2bc029c26a57135881b5
- https://github.com/ccxt/ccxt/blob/master/js/cryptopia.js#L595
- https://github.com/ccxt/ccxt/blob/master/php/cryptopia.php#L593

**Comment by kornrunner** [comment]
Boss that, thanks!
