### ISSUE TITLE
Huobi Flash Close in Swap

### ISSUE THREAD

**Issue by flav1ooo** [ccxt/ccxt#12887]
Is there a function in CCXT to use flash close feature in Huobi Swap ?

**Comment by ttodua** [comment]
Late reply here, but to add a note : API docs doesn't directly mention `flash-close` orders, but you might want: https://huobiapi.github.io/docs/usdt_swap/v1/en/#isolated-place-an-order
`order_price_type` parameter.  might use `optimal_20`, BBO or whatever, depending your goals.

Let us know if that doesn't solve your goals or you have other issues with CCXT.
