### ISSUE TITLE
Error running app - SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by jamespfarrell** [ccxt/ccxt#1288]
Guys, I'm on linux, and can't get this running on my local machine.

I have cloned from git.

```
git clone https://github.com/ccxt/ccxt.git
cd ccxt
npm i
node example.js
```
I get the following errros.

![image](https://user-images.githubusercontent.com/10499048/34941741-54a99c28-f9f5-11e7-9b00-e1dcb84ca410.png)

My node version is:
v7.8.0

Am I doing something wrong, I'm just trying have a first look at the project and I'm really excited about it, but my wheels are spinning, and I've already spent quite a lot of time trying to get this going...

**Comment by kroitor** [comment]
Hi!

![screen-shot-2018-01-15-at-15 18 06](https://user-images.githubusercontent.com/1294454/34942183-b4420488-fa07-11e7-9e06-dc5799c3574c.jpg)

Unfortunately, it isn't for *running*. It is for *programming*.

Explained here:
- https://github.com/ccxt/ccxt/issues/900
- https://github.com/ccxt/ccxt/issues/1203
- https://github.com/ccxt/ccxt/issues/1206

The `example.js` script that you're trying to launch is not supposed to be launched at all, it is a sample for the runkit website. Ignore it.

You still can, however, launch various examples, and you almost managed to do it right, just replace the `example.js` with a script name from here: https://github.com/ccxt/ccxt/tree/master/examples/js

So,

1. To install:

```
git clone https://github.com/ccxt/ccxt.git
cd ccxt
npm install
```

2. To run (being in ccxt folder):

- ```node examples/js/arbirage-pairs.js```
- ```node examples/js/symbols.js```
- ```node examples/js/tickers.js```
- ```node examples/js/live-orderbook.js```

etc...

The above commands will run the examples, and among them you will find some pretty useful ones.

Hope it answers your question.
