### ISSUE TITLE
Fastest way to make exchange deposits/withdrawals?

### ISSUE THREAD

**Issue by cdcv** [ccxt/ccxt#12893]
Looking for the fastest way to programmatically get a token out of an exchange, eg in a few seconds (ideally one block time) rather than minutes.
Is there any method using the api / any exchanges that make this possible?
When using the ccxt withdraw method from the private API, what is the range of how long it takes form when the ccxt call is made to withdraw funds (eg on Binance) till when the funds are available in you?  Via the UI the documentation says that they take many blocks before a withdrawal is completed.  Is there a way using the APIs to get it to happen faster, eg in a single block?  Are there any of the exchanges that provide this via their api?
For deposits, same question.
Thank you

**Comment by Dan-krm** [comment]
Hi, I think this is something that's limited by the exchanges withdrawal fee structure and the chosen network. I'm not aware of any centralized exchanges that allow you to increase the gas price to process a withdrawal faster, but most decentralized exchanges would allow you to do this. CCXT currently supports IDEX as an example of a decentralized exchange, and I believe CCXT is planning to add support for more decentralized exchanges in the future.

Also, using less congested blockchain networks other than the Bitcoin or Ethereum network will generally process transactions faster and for a lower fee. The Withdraw method allows you to specify a network in the params argument:
https://github.com/ccxt/ccxt/wiki/Manual#withdrawal
TRX, BSC and Matic networks are commonly supported for ERC-20 cryptocurrencies.
