### ISSUE TITLE
How to download airdrops/dividends on Binance?

### ISSUE THREAD

**Issue by ludekvodicka** [ccxt/ccxt#12896]
Hi,
what is the recommended way to download dividends/airdrops on Binance? I tried to search through code/issues here on the Github as same as in the code but I didn't find any way.

I found this PR https://github.com/ccxt/ccxt/pull/5725

but the exchange object doesn't have any `fetch_aidrops` or `fetch_dividends`.

I found the method `sapiGetAssetAssetDividend` but without any documentation or information on how to use it (and probably it's Binance dependent method and not a universal method).

- OS: Windows
- Programming Language version: NodeJS
- CCXT version: 1.79.88

Thank you for pointing me to any documentation/example where I can check it.

Ludek

**Comment by kroitor** [comment]
You can do that with implicit API:

- https://docs.ccxt.com/en/latest/manual.html#implicit-api
- https://docs.ccxt.com/en/latest/manual.html#implicit-api-methods
- https://binance-docs.github.io/apidocs/spot/en/#asset-dividend-record-user_data

```JavaScript
const ccxt = require ('ccxt')

console.log ('CCXT Version:', ccxt.version)

async function main () {

    const exchange = new ccxt.binance({
        'apiKey': 'YOUR_API_KEY',
        'secret':' YOUR_SECRET',
    })
    
    const markets = await exchange.loadMarkets()
    
    const response = await exchange.sapiGetAssetAssetDividend ({
         // your params here if necessary: https://binance-docs.github.io/apidocs/spot/en/#asset-dividend-record-user_data
    })
    
    console.log (response)
}

main ()
```

I would highly recommend reading the entire Manual from top to bottom – it will really save your time.
Also, check the examples:

- https://docs.ccxt.com/
- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/tree/master/examples/

Hope that answers your question. Let us know if not. Feel free to reopen this issue or just ask further questions if any.

**Comment by ludekvodicka** [comment]
Thanks a lot for the example.

I already read a whole manual but didn't find any mention of this API. I tried transfers, ledger, ... and a lot of other things but without success.
