### ISSUE TITLE
connection header is not used as session headers are not used

### ISSUE THREAD

**Issue by SmartManoj** [ccxt/ccxt#12894]
https://github.com/ccxt/ccxt/blob/2cad76f3896be2f090daf897885921695043fc16/python/ccxt/base/exchange.py#L574

 Here there should be an extra line `headers.update(self.session.headers)` .
 
 But for kucoin, I get `Invalid KC-API-SIGN` after changing this.

**Comment by kroitor** [comment]
How do you set your headers  in the userland ?

**Comment by SmartManoj** [comment]
Userland?

https://2.python-requests.org/en/master/user/advanced/#keep-alive

When a session object is created, it contains `connection: keepalive` header which tells the server to keep the connection.
Here we are explicitly passing headers every time without the initial headers.

**Comment by kroitor** [comment]
@SmartManoj i mean the documented method of setting headers is this:

```Python
import ccxt
exchange = ccxt.kucoin({
    'headers': {
         # YOUR HEADERS HERE
    },
})
```

The keep-alive functionality is automated in Python requests: https://docs.python-requests.org/en/latest/user/advanced/#keep-alive 

Which specific headers do you override?
Can you paste the code (without the secrets, of course)?

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by SmartManoj** [comment]
> The keep-alive functionality is automated in Python requests: [docs.python-requests.org/en/latest/user/advanced/#keep-alive](https://docs.python-requests.org/en/latest/user/advanced/#keep-alive)

Yes, but ccxt overrides the headers here. 
https://github.com/ccxt/ccxt/blob/2cad76f3896be2f090daf897885921695043fc16/python/ccxt/base/exchange.py#L627

**Comment by kroitor** [comment]
@SmartManoj if you follow the callchain, the headers are taken from `exchange.headers` / `self.headers` on this line: https://github.com/ccxt/ccxt/blob/2cad76f3896be2f090daf897885921695043fc16/python/ccxt/base/exchange.py#L605

Which is why you can set your headers as documented here: https://github.com/ccxt/ccxt/issues/12894#issuecomment-1103459691

**Comment by SmartManoj** [comment]
> @SmartManoj if you follow the callchain, the headers are taken from `exchange.headers` / `self.headers` on this line:
> 
> https://github.com/ccxt/ccxt/blob/2cad76f3896be2f090daf897885921695043fc16/python/ccxt/base/exchange.py#L605
> 
> Which is why you can set your headers as documented here: [#12894 (comment)](https://github.com/ccxt/ccxt/issues/12894#issuecomment-1103459691)

I don't want to set any extra headers. I am saying that default session headers are not used.

**Comment by kroitor** [comment]
> I don't want to set any extra headers. I am saying that default session headers are not used.

Ah, ok, now I get it, will check that and will be back to you asap. Thx!
