### ISSUE TITLE
Long/Short orders in FTX Future

### ISSUE THREAD

**Issue by flav1ooo** [ccxt/ccxt#12898]
Im trying to make future orders in FTX exchange :

For example i want to open a long contract and then close it

How can i open and close it? While closing should i use extra parameters ( for ex. i used reduceOnly in binance )?

Also the code that in below correct opening long contract syntax?

exchange.create_order("ADA-PERP","market","buy",2,None) or exchange.create_order("ADA-PERP","limit","buy",2,price,)

If you explain to me with some syntax examples i will be glad. Thank you !

**Comment by samgermain** [comment]
You should be able to do it the same way you did it in binance. I'd recommend to not use symbols like `ADA-PERP` but instead use `ADA/USD:USD` which is a [unified symbol](https://docs.ccxt.com/en/latest/manual.html#contract-naming-conventions). Binance is currently the only exchange which doesn't accept the unified swap and future naming conventions

**Comment by samgermain** [comment]
I'm going to close this issue. Feel free to reopen it if you have any more questions
