### ISSUE TITLE
HuobiPro API call for load_markets() blocked by CloudFlare

### ISSUE THREAD

**Issue by valentinbora** [ccxt/ccxt#1289]
Tried running `ccxt/examples/py/symbols.py huobipro` and got an HTML result back from the API saying "The owner of this website (api.huobi.pro) has banned your access based on your browser's signature".

The API request `GET` `https://api.huobi.pro/v1/common/symbols` works in a regular Chrome browser without issue, but not from ccxt/CLI.

- OS: Mac OS X
- Programming Language version: Python 3.6.3 :: Anaconda, Inc.
- CCXT version: c993007953aefd1078cae7d7552c35704f46351e / 1.10.718 / Mon Jan 15 13:12:49 2018 +0000
- Exchange: HuobiPro
- Method: `load_markets`

**Comment by augmenter** [comment]
Anxpro is also behind cloudflare, so the url
https://anxpro.com/api/2/USDBTC/money/ticker?currency_pair=USDBTC
does not work from node, but it works in browser after solving a captcha.
Also tried using cloudscraper to no avail….

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/blob/master/examples/js/bypass-cloudflare.js
- https://github.com/ccxt/ccxt/blob/master/examples/py/bypass-cloudflare.py

Hope it helps. Let us know if not. Thx!

**Comment by augmenter** [comment]
Thanks for replying, I have already tried with cloudscraper but I got the ErrorType = 1, which
is "1 cloudflare returned captcha. Nothing to do here. Bad luck".
You can close the ticket.

**Comment by kroitor** [comment]
@augmenter there's still one option, though, you can copy those credentials manually from your browser! Check this out: 

![abc-cfscrape](https://user-images.githubusercontent.com/1294454/35126483-a4f2d91c-fcbe-11e7-871f-f6b5fb61c8d8.jpg)

A. Go to that URL, then hit `cmd+alt+I` or `ctrl+alt+I` to show the Web Inspector in Chrome. Select the network tab in web inspector and hit ctrl-R to refresh the page once more. It will show a list of network requests made.

B. Click that request, to show its details.

C. Copy the Cookie and the User-Agent from the **request headers**, and set them on your exchange instance like so:

```
exchange = ccxt.anxpro()
your_cookie_string = '__cfduid=da6158215b19a196ceff329a5450ca5401513273261; cf_clearance=1ac56559bce6bb4c01779045fec4a0c4e228be6d-1516317193-3600'
your_user_agent_string = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36'
exchange.headers = {
    'Cookie': your_cookie_string,
    'User-Agent': your_user_agent_string,
}
exchange.fetch_ticker('BTC/USD')
```

Does this help?
