### ISSUE TITLE
Binance spot entry price

### ISSUE THREAD

**Issue by ctu1121** [ccxt/ccxt#12891]
Hi, 
Please advice may I get Binance spot entry price by ccxt?
Thanks for your help.

Charles

**Comment by kroitor** [comment]
Hi! You can use any of these endpoints with the implicit methods as documented in the Manual:

- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L210

Docs:

- https://docs.ccxt.com/en/latest/manual.html#implicit-api
- https://docs.ccxt.com/en/latest/manual.html#implicit-api-methods

Let us know if that does not answer your question.
