### ISSUE TITLE
Huobipro: Withdrawl  attribute missing

### ISSUE THREAD

**Issue by HydroMining** [ccxt/ccxt#1290]
Hi,

for Huobipro, the withdraw attribute/method is missing - Can you check?

Thanks for you great software & regards,

Hydro

- OS: All
- Programming Language version: Python 3.6
- CCXT version: 1.10.717
- Exchange: Huobipro
- Method: withdraw

**Comment by kroitor** [comment]
Sorry, but is not implemented yet, yet still you can use their custom API from ccxt to withdraw funds right away, until we unify that. The usage of custom methods is described here: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods (I'd recommend to read the entire manual). Closing this for now. Feel free to reopen it if needed or just ask questions. Your contributions are welcome!
