### ISSUE TITLE
FTX fetching "ANYCOIN-PERP" price

### ISSUE THREAD

**Issue by flav1ooo** [ccxt/ccxt#12916]
Hi i want to get coins average price in FTX but im not so sure about FTX exchange . Is it the appropriate code to get the instant price of any coin?

For example : ADA

exchange.fetch_ticker("ADA-PERP")["last"]

**Comment by kroitor** [comment]
> Is it the appropriate code to get the instant price of any coin?
> For example : ADA
> exchange.fetch_ticker("ADA-PERP")["last"]

It depends on how you define the _"instant"_ price. You also have to define in which currency you want the price, could be dollars, euros, ducks or apples. That code will give you the price of the most recent trade of ADA/USD that some two traders have just traded on FTX. Apart from the last traded price, there are also the current buying price and the current selling price. And also the average price and the mid price. So you have to be very specific about which exact price you want, cause there is not such thing as just the price – it depends.

**Comment by flav1ooo** [comment]
> 

I mean market price. I just want to open a instant position when i want

**Comment by flav1ooo** [comment]
> > Is it the appropriate code to get the instant price of any coin?
> > For example : ADA
> > exchange.fetch_ticker("ADA-PERP")["last"]
> 
> It depends on how you define the _"instant"_ price. You also have to define in which currency you want the price, could be dollars, euros, ducks or apples. That code will give you the price of the most recent trade of ADA/USD that some two traders have just traded on FTX. Apart from the last traded price, there are also the current buying price and the current selling price. And also the average price and the mid price. So you have to be very specific about which exact price you want, cause there is not such thing as just the price – it depends.

I mean market price. I just want to open a instant position when i want

**Comment by kroitor** [comment]
> I mean market price. I just want to open a instant position when i want

Yes, but there's no single market price. There's the bid market price and the ask market price. So, it depends on whether you want to buy or sell the ADA perpetual contract.

**Comment by flav1ooo** [comment]
> > I mean market price. I just want to open a instant position when i want
> 
> Yes, but there's no single market price. There's the bid market price and the ask market price. So, it depends on whether you want to buy or sell the ADA perpetual contract. You can get that information from the orderbook (like `exchange.fetch_order_book('ADA-PERP')`)

Sorry for my ignorance, can you explain to me difference between ["bid"] and ["last"] price or ["ask"] and ["last"] price. I know what bid and ask mean

**Comment by kroitor** [comment]
@flav1ooo sure, check this section of the manual to understand the matching process, what an open order is and how it looks on the orderbook (`bid` / `ask`), how orders are closed and how two orders generate a trade (`last` traded price):

- https://docs.ccxt.com/en/latest/manual.html#how-orders-are-related-to-trades

**Comment by flav1ooo** [comment]
> @flav1ooo sure, check this section of the manual to understand the matching process, what an open order is and how it looks on the orderbook (`bid` / `ask`), how orders are closed and how two orders generate a trade (`last` traded price):
> 
> - https://docs.ccxt.com/en/latest/manual.html#how-orders-are-related-to-trades

So "last" means last traded price of that coin right?

**Comment by kroitor** [comment]
> So "last" means last traded price of that coin right?

Exactly.
