### ISSUE TITLE
[okx] bad error mapping?

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#12913]
When trying to do a futures trade with the wrong 'account mode' setting I saw this:

`InsufficientFunds okex5 {"code":"1","data":[{"clOrdId":"uJrfGFth9F","ordId":"","sCode":"51010","sMsg":"The current account mode does not support this API interface. ","tag":""}],"msg":"Operation failed."}`

`InsufficientFunds` doesn't feel right.

**Comment by SvChek** [comment]
how to solve this problem? I ran into her too
