### ISSUE TITLE
Disable async context switching with enableRateLimit. 

### ISSUE THREAD

**Issue by cfytrok** [ccxt/ccxt#12915]
async Python.
I want to send orders as soon as possible. But when I call create_order, interpreter switchs to my background asyncio task befor sending request.
Is there a way to send request during create_order without switching context with enableRateLimit=True?
Is there an Event that sets when request is sent?

**Comment by ttodua** [comment]
`await` yields control back to the event loop, so it introduces a context switch. if anyone has any custom solutions, users might post in this thread.
