### ISSUE TITLE
fetchBorrowRateHistory bug in https://github.com/ccxt/ccxt/commit/5b5ab8ae98052f8aa05bc1749cf31198cfc3073f

### ISSUE THREAD

**Issue by daviidarr** [ccxt/ccxt#12926]
Hi,
bug has been introduded in fxt.js in version 1.78.61 when an argument was added to fetchBorrowRateHistories: fetchBorrowRateHistory is called with only 3 arguments.

Fix would be to pass "code" argument of fetchBorrowRateHistory as "codes" arguement of fetchBorrowRateHistories:
histories = await self.fetch_borrow_rate_histories(since, limit, params)
-->
histories = await self.fetch_borrow_rate_histories([code],since, limit, params)

I am not sure what type "codes" is supposed to be in python: it needs to have a .includes() method if parse_borrow_rate_histories is not to throw...I am not sure includes() exists in python, though:
if codes is None or codes.includes(code):
-->
if codes is None or code in codes:

**Comment by kroitor** [comment]
@daviidarr this issue is fixed in the most recent version, 1.80.30+

- https://github.com/ccxt/ccxt/commit/394f5f9630dc6961a6568a139272c1269a98496c
