### ISSUE TITLE
Why fee an trades aren't reported when an order is filled at Binance ?

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#12943]
Hello,

I try to understand why `fee`, `fees` and `trades` keys are empty in the dictionary returned by the exchange after an order is filled (method `fetchOrder`). Sometime the keys contain data. Please find below two orders executed on ETH/USDT spot market of Binance. One order has values but not the other. What could be the reason ?

As you can see both orders have status `FILLED`. One is `sell` the other is `buy`.

`fee` is null

`{"id": "8664222318", "fee": null, "cost": 18.07068, "fees": [], "info": {"side": "SELL", "time": "1650610804472", "type": "LIMIT", "price": "3011.78000000", "status": "FILLED", "symbol": "ETHUSDT", "orderId": "8664222318", "origQty": "0.00600000", "isWorking": true, "stopPrice": "0.00000000", "icebergQty": "0.00000000", "updateTime": "1650610829617", "executedQty": "0.00600000", "orderListId": "-1", "timeInForce": "GTC", "clientOrderId": "6qgr8", "origQuoteOrderQty": "0.00000000", "cummulativeQuoteQty": "18.07068000"}, "side": "sell", "type": "limit", "price": 3011.78, "amount": 0.006, "filled": 0.006, "status": "closed", "symbol": "ETH/USDT", "trades": [], "average": 3011.78, "datetime": "2022-04-22T07:00:04.472Z", "postOnly": false, "remaining": 0.0, "stopPrice": null, "timestamp": 1650610804472, "timeInForce": "GTC", "clientOrderId": "6qgr8", "lastTradeTimestamp": null}`

`fee` contains data 

`{"id": "8665290466", "fee": {"cost": 2.99e-05, "currency": "ETH"}, "cost": 89.71196, "fees": [{"cost": 2.99e-05, "currency": "ETH"}], "info": {"side": "BUY", "type": "LIMIT", "fills": [{"qty": "0.02990000", "price": "3000.40000000", "tradeId": "807983332", "commission": "0.00002990", "commissionAsset": "ETH"}], "price": "3000.40000000", "status": "FILLED", "symbol": "ETHUSDT", "orderId": "8665290466", "origQty": "0.02990000", "executedQty": "0.02990000", "orderListId": "-1", "timeInForce": "GTC", "transactTime": "1650618004892", "clientOrderId": "8iMM1", "cummulativeQuoteQty": "89.71196000"}, "side": "buy", "type": "limit", "price": 3000.4, "amount": 0.0299, "filled": 0.0299, "status": "closed", "symbol": "ETH/USDT", "trades": [{"id": "807983332", "fee": {"cost": 2.99e-05, "currency": "ETH"}, "cost": 89.71196, "fees": [{"cost": "0.00002990", "currency": "ETH"}], "info": {"qty": "0.02990000", "price": "3000.40000000", "tradeId": "807983332", "commission": "0.00002990", "commissionAsset": "ETH"}, "side": "buy", "type": "limit", "order": "8665290466", "price": 3000.4, "amount": 0.0299, "symbol": "ETH/USDT", "datetime": null, "timestamp": null, "takerOrMaker": null}], "average": 3000.4, "datetime": "2022-04-22T09:00:04.892Z", "postOnly": false, "remaining": 0.0, "stopPrice": null, "timestamp": 1650618004892, "timeInForce": "GTC", "clientOrderId": "8iMM1", "lastTradeTimestamp": null}`

**Comment by kroitor** [comment]
@Kinzowa do you always use fetchOrder in all cases, or do you get those orders from different methods (say, fetchOrder / fetchOrders, or fetchOrder/createOrder, etc) ?

**Comment by Kinzowa** [comment]
Now I understand, `fee` and `trades` are only reported by the exchange with `createOrder` if the order is executed.

**Comment by Kinzowa** [comment]
https://binance-docs.github.io/apidocs/spot/en/#new-order-trade

**Comment by Kinzowa** [comment]
Do you think there is a possibility to know the commissions when an order is not executed instantly ?

**Comment by kroitor** [comment]
> Now I understand, fee and trades are only reported by the exchange with `createOrder` if the order is executed.
>
> If I understand correctly, Binance returns `fee` and `commission` keys when the order takes liquidity (taker), but not if it's a maker.

Basically, the fee is a property of a trade, not a property of an order. Most of the exchanges will return those fees with trades from fetchMyTrades. Some exchanges will also return those fees in the orders, but not all of them. That is because a single order can be filled with multiple trades, and then you have to sum up those fees to get the total fee. When the exchange does not specify a total fee on the order, ccxt can calculate it, if the exchange returns the trade information within the order. However, Binance exchange will only return that trade+fee information within createOrder upon placing it. And when you query it later, the trade+fee info is not available. Hence, you have to fetchMyTrades, filter those trades by the order id and sum up their fees by currency. Hope that answers your question. Feel free to reopen this issue or just ask further questions if any.
