### ISSUE TITLE
kucoin only returns 6 asks and 6 bids and 10 trades

### ISSUE THREAD

**Issue by hippylover** [ccxt/ccxt#1295]
kucoin only returns 6 asks and bids(separately) and 10 trades even if i provide depth parameter.

```
exchange = ccxt.kucoin()
exchange.loadMarkets()

lel = exchange.fetchOrderBook('ACT/BTC', {"depth":"100"})
pprint.pprint(lel)

{'asks': [[4.535e-05, 631.323],
          [4.536e-05, 2.4947],
          [4.552e-05, 13.2283],
          [4.565e-05, 10.0],
          [4.575e-05, 3737.226],
          [4.576e-05, 4000.0]],
 'bids': [[4.483e-05, 241.0],
          [4.451e-05, 2000.0],
          [4.407e-05, 5555.0],
          [4.391e-05, 2428.0708],
          [4.39e-05, 235.8133],
          [4.375e-05, 820.5871]],
 'datetime': '2018-01-15T17:28:53.819Z',
 'timestamp': 1516037332819}
```

Should be 150 according to api doc atleast: https://liqui.io/api

**Comment by gaardiolor** [comment]
You can pass params to fetchOrderbook: `{'limit': 100}` gets 100 orders. Kucoin API by default returns 6. 

Not sure if ccxt should do this by default though.

**Comment by kroitor** [comment]
@hippylover 

For **Kucoin**:

```Python
exchange = ccxt.kucoin()
exchange.loadMarkets()
lel = exchange.fetchOrderBook('ETH/BTC', {"limit":"100"})
pprint.pprint(lel)
```

For **Liqui**:
```Python
exchange = ccxt.liqui()
exchange.loadMarkets()
lel = exchange.fetchOrderBook('ETH/BTC', {"limit":"100"})
pprint.pprint(lel)
```

**Comment by hippylover** [comment]
Oh yeah im mixing. Pretty sure the api docs say one is supposed to use the {} for exchange specific settings but i didnt realise the words would be unified too as with liqui.

**Comment by kroitor** [comment]
> Oh yeah im mixing. Pretty sure the api docs say one is supposed to use the {} for exchange specific settings but i didnt realise the words would be unified too as with liqui.

It's the opposite, they're not unified yet, you just used a wrong parameter name `depth` instead of `limit`. It just so happens, that both Kucoin and Liqui have the same name for that `limit` parameter.

**Comment by hippylover** [comment]
oh XD. I just looked at the "method depth" name. Goddamit!

**Comment by hippylover** [comment]
I just remembered. I don't know if it's a bug or not but this only results in 10 trades. Iv'e tried looking at their API but can't find any settings that will make it possible to get more(although i couldnt find where trades where supposed to be...)

```
exchange = ccxt.kucoin()
exchange.loadMarkets()
#pprint.pprint(exchange.symbols)

lel = exchange.fetchTrades('ETH/BTC')
pprint.pprint(lel)
```

**Comment by trainerbill** [comment]
@hippylover Same boat.  don't think its possible on their backend.  Limit and since have zero affect on the api.

https://kucoinapidocs.docs.apiary.io/#reference/0/market/recently-deal-orders(open)
