### ISSUE TITLE
retrieving fills (transactions) information of a filled order - binance

### ISSUE THREAD

**Issue by kooomix** [ccxt/ccxt#12987]
Hi,

When fetching order using:

exchange.fetch_orders(symbol, limit=10)

I'm getting the aggregated orders information but the fills lists for each order are empty.

Is there any way to fetch also fills information of historical orders?

Thanks,
Eran

**Comment by kroitor** [comment]
@kooomix 

> Is there any way to fetch also fills information of historical orders?

Yes, but you will need to watch the fills with watchMyTrades in parallel and match them to your orders using the order ids.

**Comment by kooomix** [comment]
Thanks. I see it is implemented in ccxt pro which i'm currently not using.
I have found that fetchMyTrades can answer my needs at the moment...

I think it might be nice to be able to fetch trades information by orderIds and/or to be able to get it along with the fetchOrder.

Thanks for the help.

**Comment by kroitor** [comment]
> Thanks. I see it is implemented in ccxt pro which i'm currently not using. I have found that fetchMyTrades can answer my needs at the moment...

Yes, that is correct.

> I think it might be nice to be able to fetch trades information by orderIds and/or to be able to get it along with the fetchOrder.

It depends on the underlying exchange API, CCXT does support that if the underlying exchange sends fills along with orders, but not that many exchanges will provide that info in one go, so you have to make a few calls to fetchOrders, fetchMyTrades, etc...
