### ISSUE TITLE
Margin limit order with sideEffectType = 'MARGIN_BUY' - Binance

### ISSUE THREAD

**Issue by kooomix** [ccxt/ccxt#12988]
Hi,

When creating a margin limit order (using exchange.create_order) with sideEffectType = 'MARGIN_BUY' I have found a conceptual issue I believe is out of ccxt control but maybe someone have an idea how to cope - 

The margin_buy order combines 2 steps - borrowing an asset and then selling it. For "market" order type it works ok as the exact borrowed quantity is guaranteed to be sold.

However, when order_type is "limit", then not all the borrowed quantity is guaranteed to be sold, therefore there is a chance there will be un-desired quantity left for the asset.

So if I want to margin_buy limit 1000 units, it will borrow the 1000 units, but might sell 400 units which leaves 600 units as "free" which needs to be sold (loss of commissions $).

Any idea how to approach?

Thanks!

**Comment by sc0Vu** [comment]
Hi @kooomix 

May I ask does the limit order supposed to have this partial fills situation?

**Comment by kroitor** [comment]
@sc0Vu yes, in general, a limit order may be partially filled, check this section: https://docs.ccxt.com/en/latest/manual.html#how-orders-are-related-to-trades

**Comment by ttodua** [comment]
@kooomix I probably understand what you mean, as market order doesn't guarantee to execute any specific/predetermined amount, then the best route might be one from the following two scenarios:
1) when submitting the order, read it's response:
```
order = exchange.create_order(..)
print (order.amount) # this will show how many units were sold, and then in your calculations, find out the remaining amount and submit another order, like:
order2 = exchange.create_order (..., ..., ..., remaining_amount)
```

2) second route could be, to fetch balance after triggering first order, and according to the existing amounts, re-trigger `create_order` with those target amounts.

Hope the answer might help. Let us know if you experience issues with CCXT.

**Comment by kooomix** [comment]
Thanks @ttodua
The solution you offer is one way to go, in case you don't care to sell the remaining amount in a market order. But, usually, when you send a limit order, you want to sell only what goes within the limit, then this solution might not be sufficient.

I offer a different approach:
1. creating the order, that will borrow the whole amount (origin_amount) and will sell whatever within the limit (sold_amount). 
2. Repay the remaining amount that wasn't sold as planned (origin_amount-sold_amount). 

This will ensure there is no borrowed amount left that was not sold.

I think having such built in functionality in CCXT can help having this conceptual process much easier.

Thanks,
Eran

**Comment by alexanderVorozhtsov** [comment]
> Hi,
> 
> When creating a margin limit order (using exchange.create_order) with sideEffectType = 'MARGIN_BUY' I have found a conceptual issue I believe is out of ccxt control but maybe someone have an idea how to cope -
> 
> The margin_buy order combines 2 steps - borrowing an asset and then selling it. For "market" order type it works ok as the exact borrowed quantity is guaranteed to be sold.
> 
> However, when order_type is "limit", then not all the borrowed quantity is guaranteed to be sold, therefore there is a chance there will be un-desired quantity left for the asset.
> 
> So if I want to margin_buy limit 1000 units, it will borrow the 1000 units, but might sell 400 units which leaves 600 units as "free" which needs to be sold (loss of commissions $).
> 
> Any idea how to approach?
> 
> Thanks!

Hello.
How do you transmit parameter sideEffectType='MARGIN_BUY' in exchange.create_order(self, symbol: str, type: OrderType, side: OrderSide, amount, price=None, params={})? If I try to send something in params I receive only:
"InsufficientFunds: binance Account has insufficient balance for requested action." (It is not truth though) or
"BadRequest: binance {"code":-1104,"msg":"Not all sent parameters were read; read '11' parameter(s) but was sent '12'."}"
Thanks.

**Comment by ttodua** [comment]
@alexanderVorozhtsov I will look into issue a bit later and let you know. 
for a quick note:
```
myParams =  { 'sideEffectType': 'MARGIN_BUY' }
exchange.create_order(........................, params=myParams)
```
you need to have balance in margin account specifically to symbol (whether it's isolated or cross). btw, are you using `reduceOnly`?

**Comment by alexanderVorozhtsov** [comment]
> @alexanderVorozhtsov I will look into issue a bit later and let you know. for a quick note:
> 
> ```
> myParams =  { 'sideEffectType': 'MARGIN_BUY' }
> exchange.create_order(........................, params=myParams)
> ```
> 
> you need to have balance in margin account specifically to symbol (whether it's isolated or cross). btw, are you using `reduceOnly`?

Thank you.
I repeated your code and received response:
BadRequest: binance {"code":-1104,"msg":"Not all sent parameters were read; read '11' parameter(s) but was sent '12'."}
I have enough balance in my cross-margin account, where I send order, because I can do this operation via the web personal account. No, I don't use reduceOnly, I want to borrow and sell coin simultaneously, at one request. btw How can I explore all available params?

**Comment by alexanderVorozhtsov** [comment]
Resolved. It works only with myParams =  {'type':'margin', 'sideEffectType': 'MARGIN_BUY' }
