### ISSUE TITLE
create_order delayed, which causes it to buy or sell at a price different 

### ISSUE THREAD

**Issue by flav1ooo** [ccxt/ccxt#12986]
Is there way to make it faster ? 

I tried to solve with:

EnableRateLimit = False,
EnableRateLimit = True,
Loading Markets

Do you have any suggestions except the ways that i mentioned above.

Thank you !

**Comment by kroitor** [comment]
@flav1ooo can you please paste your code? https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by flav1ooo** [comment]
> @flav1ooo can you please paste your code? https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

Of course, im trying to do simple arbitrage bot between two exchanges my code is below:

import ccxt

diffmax = 0.0020
diffmin = 0.0005

pairone = "ADA/USDT" 
amount = 10 # coin quantity

account_ftx = ccxt.ftx({
    "apiKey": 'api',
    "secret": 'secret',
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future'
    }
})

account_binance = ccxt.binance({
    "apiKey": 'api',
    "secret": 'secret',
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future'
    }
})

account_binance.load_markets()
account_ftx.load_markets()

bought_BinanceFTX= True
bought_FTXBinance = True

binanceFTXCheck = True
FTXBinanceCheck = True

params = {"reduceOnly": True} 
params_huobi_open = {"offset": "open","lever_rate":2}  # kaldıraç katsayısı için "lever_rate" = 1 gibi
params_huobi_close = {"offset": "close","reduce_only": 1}
account_binance.set_leverage(2,pairone) 
account_ftx.set_leverage(2,"ADA-PERP") 

while True:
    try:
        binanceEth = float(account_binance.fetch_ticker(pairone)["info"]["lastPrice"])
        ftxEth = float(account_ftx.fetch_ticker("ADA-PERP")["info"]["price"])
        farkBinanceFTX= (binanceEth - ftxEth) / binanceEth
   
    except Exception as e:
        print(e)
        continue
    
    if binanceFTXCheck == True and farkBinanceFTX <= -diffmax and bought_BinanceFTX== True:
        account_binance.create_order(pairone, "market", "buy", amount, None)
        account_ftx.create_order("ADA-PERP", "market", "sell", amount, None)
        print(farkBinanceFTX)
        bought_BinanceFTX = False
        FTXBinanceCheck = False
     
        # closing
    elif binanceFTXCheck == True and farkBinanceFTX >= -diffmin and bought_BinanceFTX== False:
        account_binance.create_order(pairone, "market", "sell", amount, None, params)
        account_ftx.create_order("ADA-PERP", "market", "buy", amount, None, params)
        print(farkBinanceFTX)
        bought_BinanceFTX = True
        FTXBinanceCheck = True
      
    elif FTXBinanceCheck == True and farkBinanceFTX >= diffmax and bought_FTXBinance == True:
        account_binance.create_order(pairone, "market", "sell", amount, None)
        account_ftx.create_order("ADA-PERP", "market", "buy", amount, None)
        print(farkBinanceFTX)
        bought_FTXBinance = False
        binanceFTXCheck = False

        #closing
    elif FTXBinanceCheck == True and farkBinanceFTX <=diffmin and bought_FTXBinance == False:
        account_binance.create_order(pairone, "market", "buy", amount, None, params)
        account_ftx.create_order("ADA-PERP", "market", "sell", amount, None,params)
        print(farkBinanceFTX)
        bought_FTXBinance = True
        binanceFTXCheck = True

**Comment by flav1ooo** [comment]
> > @flav1ooo can you please paste your code? https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
> 
> Of course, im trying to do simple arbitrage bot between two exchanges my code is below: 
```

`` import ccxt
> 
> diffmax = 0.0020 diffmin = 0.0005
> 
> pairone = "ADA/USDT" amount = 10 # coin quantity
> 
> account_ftx = ccxt.ftx({ "apiKey": 'api', "secret": 'secret', 'enableRateLimit': True, 'options': { 'defaultType': 'future' } })
> 
> account_binance = ccxt.binance({ "apiKey": 'api', "secret": 'secret', 'enableRateLimit': True, 'options': { 'defaultType': 'future' } })
> 
> account_binance.load_markets() account_ftx.load_markets()
> 
> bought_BinanceFTX= True bought_FTXBinance = True
> 
> binanceFTXCheck = True FTXBinanceCheck = True
> 
> params = {"reduceOnly": True} params_huobi_open = {"offset": "open","lever_rate":2} # kaldıraç katsayısı için "lever_rate" = 1 gibi params_huobi_close = {"offset": "close","reduce_only": 1} account_binance.set_leverage(2,pairone) account_ftx.set_leverage(2,"ADA-PERP")
> 
> while True: try: binanceEth = float(account_binance.fetch_ticker(pairone)["info"]["lastPrice"]) ftxEth = float(account_ftx.fetch_ticker("ADA-PERP")["info"]["price"]) farkBinanceFTX= (binanceEth - ftxEth) / binanceEth
> 
> ```
> except Exception as e:
>     print(e)
>     continue
> 
> if binanceFTXCheck == True and farkBinanceFTX <= -diffmax and bought_BinanceFTX== True:
>     account_binance.create_order(pairone, "market", "buy", amount, None)
>     account_ftx.create_order("ADA-PERP", "market", "sell", amount, None)
>     print(farkBinanceFTX)
>     bought_BinanceFTX = False
>     FTXBinanceCheck = False
>  
>     # closing
> elif binanceFTXCheck == True and farkBinanceFTX >= -diffmin and bought_BinanceFTX== False:
>     account_binance.create_order(pairone, "market", "sell", amount, None, params)
>     account_ftx.create_order("ADA-PERP", "market", "buy", amount, None, params)
>     print(farkBinanceFTX)
>     bought_BinanceFTX = True
>     FTXBinanceCheck = True
>   
> elif FTXBinanceCheck == True and farkBinanceFTX >= diffmax and bought_FTXBinance == True:
>     account_binance.create_order(pairone, "market", "sell", amount, None)
>     account_ftx.create_order("ADA-PERP", "market", "buy", amount, None)
>     print(farkBinanceFTX)
>     bought_FTXBinance = False
>     binanceFTXCheck = False
> 
>     #closing
> elif FTXBinanceCheck == True and farkBinanceFTX <=diffmin and bought_FTXBinance == False:
>     account_binance.create_order(pairone, "market", "buy", amount, None, params)
>     account_ftx.create_order("ADA-PERP", "market", "sell", amount, None,params)
>     print(farkBinanceFTX)
>     bought_FTXBinance = True
>     binanceFTXCheck = True


```

**Comment by flav1ooo** [comment]
> @flav1ooo can you please paste your code? https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

Also i have one more question. Is there speed difference between createOrder and create_market_buy_order&create_market_sell_order

**Comment by kroitor** [comment]
> Also i have one more question. Is there speed difference between createOrder and create_market_buy_order&create_market_sell_order

Nope, those are the aliases for the same endpoint/call.

**Comment by flav1ooo** [comment]
> > Also i have one more question. Is there speed difference between createOrder and create_market_buy_order&create_market_sell_order
> 
> Nope, those are the aliases for the same endpoint/call.

Did you check my code? Any suggestions to speed up orders

**Comment by kroitor** [comment]
@flav1ooo i would suggest executing the calls to place orders on the exchanges in parallel async mode – that can really speed it up:

- https://docs.ccxt.com/en/latest/manual.html#synchronous-vs-asynchronous-calls
- https://github.com/ccxt/ccxt/tree/master/examples/py
- https://github.com/ccxt/ccxt/tree/master/examples/

**Comment by flav1ooo** [comment]
> @flav1ooo i would suggest executing the calls to place orders on the exchanges in parallel async mode with asyncio – that can really speed it up:
> 
> - https://docs.ccxt.com/en/latest/manual.html#synchronous-vs-asynchronous-calls
> - https://github.com/ccxt/ccxt/tree/master/examples/py
> - https://github.com/ccxt/ccxt/tree/master/examples/
> 
> ↑ See "async" examples here.

Thank you sir . I know maybe i want a lot but im not super good at programming, Is there chance to you help me to transform my sync code above to async?

**Comment by kroitor** [comment]
@flav1ooo I would recommend learning asyncio, there's a ton of tutorials on google and videos on youtube, like _"asyncio in 24 hours"_, _"aasyncio tutorial"_, etc. it will really help save your time in the future. Your script translates to something like this:

```Python
import sys
import ccxt.async_support as ccxt
from pprint import pprint
from asyncio import run, gather


print('CCXT Version:', ccxt.__version__)


diffmax = 0.0020
diffmin = 0.0005

symbol = "ADA/USDT"
amount = 10 # coin quantity

ftx = ccxt.ftx({ "apiKey": 'api', "secret": 'secret' })
binance = ccxt.binanceusdm({ "apiKey": 'api', "secret": 'secret' })


async def main():

    await gather(*[
        binance.load_markets(),
        ftx.load_markets(),
    ])

    # binance.verbose = True  # uncomment for debugging purposes if necessary
    # ftx.verbose = True  # uncomment for debugging purposes if necessary

    binanceFTXCheck = True
    FTXBinanceCheck = True
    bought_BinanceFTX= True
    bought_FTXBinance = True

    await gather(*[
        binance.set_leverage(2, symbol),
        ftx.set_leverage(2,"ADA-PERP"),
    ])

    params = {"reduceOnly": True}

    while True:
        try:
            tickers = await gather(*[
                binance.fetch_ticker(symbol),
                ftx.fetch_ticker("ADA-PERP"),
            ])
            [ binanceLast, ftxLast ] = [ticker['last'] for ticker in tickers]
            farkBinanceFTX = (binanceLast - ftxLast) / binanceLast
        except Exception as e:
            print(e)
            continue

        if binanceFTXCheck == True and farkBinanceFTX <= -diffmax and bought_BinanceFTX== True:
            orders = await gather(*[
                binance.create_order(symbol, "market", "buy", amount, None),
                ftx.create_order("ADA-PERP", "market", "sell", amount, None),
            ])
            print(farkBinanceFTX)
            bought_BinanceFTX = False
            FTXBinanceCheck = False
            # closing
        elif binanceFTXCheck == True and farkBinanceFTX >= -diffmin and bought_BinanceFTX== False:
            orders = await gather(*[
                binance.create_order(symbol, "market", "sell", amount, None, params),
                ftx.create_order("ADA-PERP", "market", "buy", amount, None, params),
            ])
            print(farkBinanceFTX)
            bought_BinanceFTX = True
            FTXBinanceCheck = True
        elif FTXBinanceCheck == True and farkBinanceFTX >= diffmax and bought_FTXBinance == True:
            orders = await gather(*[
                binance.create_order(symbol, "market", "sell", amount, None),
                ftx.create_order("ADA-PERP", "market", "buy", amount, None),
            ])
            print(farkBinanceFTX)
            bought_FTXBinance = False
            binanceFTXCheck = False
            #closing
        elif FTXBinanceCheck == True and farkBinanceFTX <=diffmin and bought_FTXBinance == False:
            orders = await gather(*[
                binance.create_order(symbol, "market", "buy", amount, None, params),
                ftx.create_order("ADA-PERP", "market", "sell", amount, None, params),
            ])
            print(farkBinanceFTX)
            bought_FTXBinance = True
            binanceFTXCheck = True

    await ftx.close()
    await binance.close()


run(main())
```

**Comment by flav1ooo** [comment]
> 

I used the end of the code asyncio.run(main()) but it gives error that : This event loop is already running

**Comment by flav1ooo** [comment]
> @flav1ooo I would recommend learning asyncio, there's a ton of tutorials on google and videos on youtube, like _"asyncio in 24 hours"_, _"aasyncio tutorial"_, etc. it will really help save your time in the future. Your script translates to something like this:
> 
> ```python
> import sys
> import ccxt.async_support as ccxt
> from pprint import pprint
> from asyncio import run, gather
> 
> 
> print('CCXT Version:', ccxt.__version__)
> 
> 
> diffmax = 0.0020
> diffmin = 0.0005
> 
> symbol = "ADA/USDT"
> amount = 10 # coin quantity
> 
> ftx = ccxt.ftx({ "apiKey": 'api', "secret": 'secret' })
> binance = ccxt.binanceusdm({ "apiKey": 'api', "secret": 'secret' })
> 
> 
> async def main():
> 
>     await gather(*[
>         binance.load_markets(),
>         ftx.load_markets(),
>     ])
> 
>     # binance.verbose = True  # uncomment for debugging purposes if necessary
>     # ftx.verbose = True  # uncomment for debugging purposes if necessary
> 
>     binanceFTXCheck = True
>     FTXBinanceCheck = True
>     bought_BinanceFTX= True
>     bought_FTXBinance = True
> 
>     await gather(*[
>         binance.set_leverage(2, symbol),
>         ftx.set_leverage(2,"ADA-PERP"),
>     ])
> 
>     params = {"reduceOnly": True}
> 
>     while True:
>         try:
>             tickers = await gather(*[
>                 binance.fetch_ticker(symbol),
>                 ftx.fetch_ticker("ADA-PERP"),
>             ])
>             [ binanceLast, ftxLast ] = [ticker['last'] for ticker in tickers]
>             farkBinanceFTX = (binanceLast - ftxLast) / binanceLast
>         except Exception as e:
>             print(e)
>             continue
> 
>         if binanceFTXCheck == True and farkBinanceFTX <= -diffmax and bought_BinanceFTX== True:
>             orders = await gather(*[
>                 binance.create_order(symbol, "market", "buy", amount, None),
>                 ftx.create_order("ADA-PERP", "market", "sell", amount, None),
>             ])
>             print(farkBinanceFTX)
>             bought_BinanceFTX = False
>             FTXBinanceCheck = False
>             # closing
>         elif binanceFTXCheck == True and farkBinanceFTX >= -diffmin and bought_BinanceFTX== False:
>             orders = await gather(*[
>                 binance.create_order(symbol, "market", "sell", amount, None, params),
>                 ftx.create_order("ADA-PERP", "market", "buy", amount, None, params),
>             ])
>             print(farkBinanceFTX)
>             bought_BinanceFTX = True
>             FTXBinanceCheck = True
>         elif FTXBinanceCheck == True and farkBinanceFTX >= diffmax and bought_FTXBinance == True:
>             orders = await gather(*[
>                 binance.create_order(symbol, "market", "sell", amount, None),
>                 ftx.create_order("ADA-PERP", "market", "buy", amount, None),
>             ])
>             print(farkBinanceFTX)
>             bought_FTXBinance = False
>             binanceFTXCheck = False
>             #closing
>         elif FTXBinanceCheck == True and farkBinanceFTX <=diffmin and bought_FTXBinance == False:
>             orders = await gather(*[
>                 binance.create_order(symbol, "market", "buy", amount, None, params),
>                 ftx.create_order("ADA-PERP", "market", "sell", amount, None, params),
>             ])
>             print(farkBinanceFTX)
>             bought_FTXBinance = True
>             binanceFTXCheck = True
> 
>     await ftx.close()
>     await binance.close()
> 
> 
> run(main())
> ```

I used the end of the code asyncio.run(main()) but it gives error that : This event loop is already running

**Comment by kroitor** [comment]
@flav1ooo in my code i'm using `run(main())` – it works for me (tested on my side), make sure that you use the same code snippet (edit for your keys)

**Comment by flav1ooo** [comment]
> @flav1ooo in my code i'm using `run(main())` – it works for me (tested on my side), make sure that you use the same code snippet (edit for your keys)

Ok i solved the problem now it gives : 

160 
    161 
--> 162 run(main())

5 frames
[/usr/lib/python3.7/asyncio/tasks.py](https://localhost:8080/#) in gather(loop, return_exceptions, *coros_or_futures)
    743     nfinished = 0
    744     for arg in coros_or_futures:
--> 745         if arg not in arg_to_fut:
    746             fut = ensure_future(arg, loop=loop)
    747             if loop is None:

TypeError: unhashable type: 'dict'

**Comment by kroitor** [comment]
@flav1ooo make sure that your code around the `gather` calls is correct (see how it's done in my snippet), i can't really debug your code blindly.

**Comment by flav1ooo** [comment]
> @flav1ooo in my code i'm using `run(main())` – it works for me (tested on my side), make sure that you use the same code snippet (edit for your keys)

It works! but there is a warning in output : 

ftx requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add exchange.close() to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff40cac1bd0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7ff40be7cb40>, 1558.095487588)]']
connector: <aiohttp.connector.TCPConnector object at 0x7ff40cac1c10>
binance requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add exchange.close() to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff40cac1150>

**Comment by kroitor** [comment]
@flav1ooo read the output above that message (from top to bottom) and make sure that your tabulation is ok and make sure that your code is ok in general.

**Comment by kroitor** [comment]
@flav1ooo you are calling fetchBalance twice here for each of the two exchanges, that means you're calling it four times, and the other two times you don't await for the result here.

```Python
            cuzdanFTX = await account_ftx.fetchBalance()
            cuzdanBinance = await account_binance.fetchBalance()
            print(account_ftx.fetchBalance())  # <<<<<<<<<<<<<<<<<<<<<<<<< BIG MISTAKE
            print(account_binance.fetchBalance())
```

**Comment by kroitor** [comment]
@flav1ooo hope this helps:

```Python
This should work:

```Python
from google.colab import output
import ccxt.async_support as ccxt
from pprint import pprint
from asyncio import run, gather

  
makas_max = 0.0020
makas_min = 0.0005

# HER BORSADAN FUTURE OLARAK YANİ VADELİ OLARAK ÇEKİLMEK ZORUNDA ANLIK FİYATLAR ! ! !!!!!!!!!!!!!!!!
symbol = "ADA/USDT"  # Gate ve Binance
pairone_huobi = "ETH/USDT:USDT"  # HUOBI Pair GATE içinde ya bu şekilde kullanılmalı ya da "XRP_USDT" şeklinde
amount = 10 # alım satım yapılacak coin miktarı
# pairone_bitmex = "ETHUSD"  # ETHUSDT OLARAK SPOTTAN ALIYOR AMA "ETHUSD" şeklinde yapınca future dan çekiyor (utkularınkiyle aynı)
account_ftx = ccxt.ftx({
    "apiKey": 'apij',
    "secret": 'secret',
})
  # account_poloniex = ccxt.poloniex()
account_binance = ccxt.binanceusdm({
      "apiKey": 'api',
      "secret": 'secret',
  })
  
async def main():

    await gather(*[
        account_binance.load_markets(),
        account_ftx.load_markets(),
    ])

    # Switch ve parametreler [ bought_(LongGirilenBorsa)(ShortGirilenBorsa) şeklinde tanımlandı.]
    bought_BinanceHuobi = True
    bought_BinanceGate = True
    bought_HuobiBinance = True
    bought_GateBinance = True
    bought_HuobiGate = True
    bought_GateHuobi = True

    # ilk yakalama sonrasında durum değişkenleri (örn; binance huobi'den büyükse huobiBinanceCheck = True gibi...)
    binanceHuobiCheck = True
    binanceGateCheck = True
    huobiBinanceCheck = True
    gateBinanceCheck = True
    huobiGateCheck = True
    gateHuobiCheck = True

    params = {"reduceOnly": True} # binance ve gate parametreleri
    params_huobi_open = {"offset": "open","lever_rate":2}  # kaldıraç katsayısı için "lever_rate" = 1 gibi
    params_huobi_close = {"offset": "close","reduce_only": 1}
    await gather(*[
        account_binance.set_leverage(2, symbol),
        account_ftx.set_leverage(2,"ADA-PERP"),
    ])
    # Diğer borsalar için kaldıraç kodları buraya eklenmeli
    while True:
        # Tüm koşullar kontrol edilip optimize edilecek
        # boughtlar her alım yapıldığında diğerleri için kapatılacak
        # Borsalardan çekilen anlık coin değerleri utkularınkiyle karşılaştırılacak
        try:
          # gateEth = account_gateio.fetch_ticker(pairone_huobi)["last"]
            #huobiEth = account_huobi.fetch_ticker(pairone_huobi)
            tickers = await gather(*[
                account_binance.fetch_ticker(symbol),
                account_ftx.fetch_ticker("ADA-PERP"),
            ])
            [ binanceLast, ftxLast ] = [ticker['last'] for ticker in tickers]
            farkBinanceFTX = (binanceLast - ftxLast) / binanceLast
            
            # Eğer huobi binance 'dan büyükse
            if binanceHuobiCheck == True and farkBinanceFTX <= -makas_max and bought_BinanceHuobi == True:
                orders = await gather(*[
                    account_binance.create_order(symbol, "market", "buy", amount, None),
                    account_ftx.create_order("ADA-PERP", "market", "sell", amount, None),
                ])
                print(farkBinanceFTX)
                print("Binance için Long order oluşturuldu buy fiyatı: ", binanceLast)
                print("FTX için Short order oluşturuldu sell fiyatı: ", ftxLast)
                print(farkBinanceFTX)
                # Sell kontrolü açılıyor
                bought_BinanceHuobi = False
                # Diğer kapılar kapatılıyor
                binanceGateCheck = False
                huobiBinanceCheck = False
                gateBinanceCheck = False
                huobiGateCheck = False
                gateHuobiCheck = False
            # Eğer huobi binance ' dan büyükse işlemlerini kapatma
            elif binanceHuobiCheck == True and farkBinanceFTX >= -makas_min and bought_BinanceHuobi == False:
                orders = await gather(*[
                    account_binance.create_order(symbol, "market", "sell", amount, None, params),
                    account_ftx.create_order("ADA-PERP", "market", "buy", amount, None, params),
                ])
                print("Binance Long kapatıldı sell fiyatı :",binanceLast)
                print("ftxi short kapatıldı buy fiyatı :",ftxLast)
                print(farkBinanceFTX)
                bought_BinanceHuobi = True
                binanceGateCheck = True
                huobiBinanceCheck = True
                gateBinanceCheck = True
                huobiGateCheck = True
                gateHuobiCheck = True
            # Eğer Binance huobi'den büyükse
            elif huobiBinanceCheck == True and farkBinanceFTX >= makas_max and bought_HuobiBinance == True:
                orders = await gather(*[
                    account_binance.create_order(symbol, "market", "sell", amount, None),
                    account_ftx.create_order("ADA-PERP", "market", "buy", amount, None),
                ])
                print("Binance için Short order oluşturuldu sell fiyatı: ", binanceLast)
                print("FTX için Long order oluşturuldu buy fiyatı: ", ftxLast)
                print(farkBinanceFTX)
                # Sell kontrolü açılıyor
                bought_HuobiBinance = False
                # Diğer kapılar kapatılıyor
                binanceHuobiCheck = False
                binanceGateCheck = False
                gateBinanceCheck = False
                huobiGateCheck = False
                gateHuobiCheck = False
            # Eğer Binance huobi 'den büyükse işlemleri KAPATMA
            elif huobiBinanceCheck == True and farkBinanceFTX <= makas_min and bought_HuobiBinance == False:
                orders = await gather(*[
                    account_binance.create_order(symbol, "market", "buy", amount, None, params),
                    account_ftx.create_order("ADA-PERP", "market", "sell", amount, None, params),
                ])
                print("Binance Short kapatıldı buy fiyatı :", binanceLast)
                print("FTX Long kapatıldı sell fiyatı: ", ftxLast)
                print(farkBinanceFTX)
                bought_HuobiBinance = True
                binanceHuobiCheck = True
                binanceGateCheck = True
                gateBinanceCheck = True
                huobiGateCheck = True
                gateHuobiCheck = True

            balances = await gather(*[
                account_ftx.fetch_balance(),
                account_binance.fetch_balance()
            ])
            [ cuzdanFTX, cuzdanBinance ] = balances
            print(cuzdanFTX)
            print(cuzdanBinance)

        except Exception as e:
            print(e)
            continue

    await account_ftx.close()
    await account_binance.close()


run(main())
```

**Comment by flav1ooo** [comment]
> @flav1ooo hope this helps:
> 
> ```python
> from google.colab import output
> import ccxt.async_support as ccxt
> from pprint import pprint
> from asyncio import run, gather
> 
>   
> makas_max = 0.0020
> makas_min = 0.0005
> 
> # HER BORSADAN FUTURE OLARAK YANİ VADELİ OLARAK ÇEKİLMEK ZORUNDA ANLIK FİYATLAR ! ! !!!!!!!!!!!!!!!!
> symbol = "ADA/USDT"  # Gate ve Binance
> pairone_huobi = "ETH/USDT:USDT"  # HUOBI Pair GATE içinde ya bu şekilde kullanılmalı ya da "XRP_USDT" şeklinde
> amount = 10 # alım satım yapılacak coin miktarı
> # pairone_bitmex = "ETHUSD"  # ETHUSDT OLARAK SPOTTAN ALIYOR AMA "ETHUSD" şeklinde yapınca future dan çekiyor (utkularınkiyle aynı)
> account_ftx = ccxt.ftx({
>     "apiKey": 'apij',
>     "secret": 'secret',
> })
> # account_poloniex = ccxt.poloniex()
> account_binance = ccxt.binanceusdm({
>       "apiKey": 'api',
>       "secret": 'secret',
>   })
>   
> async def main():
> 
>     await gather(*[
>         account_binance.load_markets(),
>         account_ftx.load_markets(),
>     ])
> 
>     # Switch ve parametreler [ bought_(LongGirilenBorsa)(ShortGirilenBorsa) şeklinde tanımlandı.]
>     bought_BinanceHuobi = True
>     bought_BinanceGate = True
>     bought_HuobiBinance = True
>     bought_GateBinance = True
>     bought_HuobiGate = True
>     bought_GateHuobi = True
> 
>     # ilk yakalama sonrasında durum değişkenleri (örn; binance huobi'den büyükse huobiBinanceCheck = True gibi...)
>     binanceHuobiCheck = True
>     binanceGateCheck = True
>     huobiBinanceCheck = True
>     gateBinanceCheck = True
>     huobiGateCheck = True
>     gateHuobiCheck = True
> 
>     params = {"reduceOnly": True} # binance ve gate parametreleri
>     params_huobi_open = {"offset": "open","lever_rate":2}  # kaldıraç katsayısı için "lever_rate" = 1 gibi
>     params_huobi_close = {"offset": "close","reduce_only": 1}
>     await gather(*[
>         account_binance.set_leverage(2, symbol),
>         account_ftx.set_leverage(2,"ADA-PERP"),
>     ])
>     # Diğer borsalar için kaldıraç kodları buraya eklenmeli
>     while True:
>         # Tüm koşullar kontrol edilip optimize edilecek
>         # boughtlar her alım yapıldığında diğerleri için kapatılacak
>         # Borsalardan çekilen anlık coin değerleri utkularınkiyle karşılaştırılacak
>         try:
>             # gateEth = account_gateio.fetch_ticker(pairone_huobi)["last"]
>             #huobiEth = account_huobi.fetch_ticker(pairone_huobi)
>             tickers = await gather(*[
>                 account_binance.fetch_ticker(symbol),
>                 account_ftx.fetch_ticker("ADA-PERP"),
>             ])
>             [ binanceLast, ftxLast ] = [ticker['last'] for ticker in tickers]
>             farkBinanceFTX = (binanceLast - ftxLast) / binanceLast
>             
>             # Eğer huobi binance 'dan büyükse
>             if binanceHuobiCheck == True and farkBinanceFTX <= -makas_max and bought_BinanceHuobi == True:
>                 orders = await gather(*[
>                     account_binance.create_order(symbol, "market", "buy", amount, None),
>                     account_ftx.create_order("ADA-PERP", "market", "sell", amount, None),
>                 ])
>                 print(farkBinanceFTX)
>                 print("Binance için Long order oluşturuldu buy fiyatı: ", binanceLast)
>                 print("FTX için Short order oluşturuldu sell fiyatı: ", ftxLast)
>                 print(farkBinanceFTX)
>                 # Sell kontrolü açılıyor
>                 bought_BinanceHuobi = False
>                 # Diğer kapılar kapatılıyor
>                 binanceGateCheck = False
>                 huobiBinanceCheck = False
>                 gateBinanceCheck = False
>                 huobiGateCheck = False
>                 gateHuobiCheck = False
>             # Eğer huobi binance ' dan büyükse işlemlerini kapatma
>             elif binanceHuobiCheck == True and farkBinanceFTX >= -makas_min and bought_BinanceHuobi == False:
>                 orders = await gather(*[
>                     account_binance.create_order(symbol, "market", "sell", amount, None, params),
>                     account_ftx.create_order("ADA-PERP", "market", "buy", amount, None, params),
>                 ])
>                 print("Binance Long kapatıldı sell fiyatı :",binanceLast)
>                 print("ftxi short kapatıldı buy fiyatı :",ftxLast)
>                 print(farkBinanceFTX)
>                 bought_BinanceHuobi = True
>                 binanceGateCheck = True
>                 huobiBinanceCheck = True
>                 gateBinanceCheck = True
>                 huobiGateCheck = True
>                 gateHuobiCheck = True
>             # Eğer Binance huobi'den büyükse
>             elif huobiBinanceCheck == True and farkBinanceFTX >= makas_max and bought_HuobiBinance == True:
>                 orders = await gather(*[
>                     account_binance.create_order(symbol, "market", "sell", amount, None),
>                     account_ftx.create_order("ADA-PERP", "market", "buy", amount, None),
>                 ])
>                 print("Binance için Short order oluşturuldu sell fiyatı: ", binanceLast)
>                 print("FTX için Long order oluşturuldu buy fiyatı: ", ftxLast)
>                 print(farkBinanceFTX)
>                 # Sell kontrolü açılıyor
>                 bought_HuobiBinance = False
>                 # Diğer kapılar kapatılıyor
>                 binanceHuobiCheck = False
>                 binanceGateCheck = False
>                 gateBinanceCheck = False
>                 huobiGateCheck = False
>                 gateHuobiCheck = False
>             # Eğer Binance huobi 'den büyükse işlemleri KAPATMA
>             elif huobiBinanceCheck == True and farkBinanceFTX <= makas_min and bought_HuobiBinance == False:
>                 orders = await gather(*[
>                     account_binance.create_order(symbol, "market", "buy", amount, None, params),
>                     account_ftx.create_order("ADA-PERP", "market", "sell", amount, None, params),
>                 ])
>                 print("Binance Short kapatıldı buy fiyatı :", binanceLast)
>                 print("FTX Long kapatıldı sell fiyatı: ", ftxLast)
>                 print(farkBinanceFTX)
>                 bought_HuobiBinance = True
>                 binanceHuobiCheck = True
>                 binanceGateCheck = True
>                 gateBinanceCheck = True
>                 huobiGateCheck = True
>                 gateHuobiCheck = True
> 
>             balances = await gather(*[
>                 account_ftx.fetch_balance(),
>                 account_binance.fetch_balance()
>             ])
>             [ cuzdanFTX, cuzdanBinance ] = balances
>             print(cuzdanFTX)
>             print(cuzdanBinance)
> 
>         except Exception as e:
>             print(e)
>             continue
> 
>     await account_ftx.close()
>     await account_binance.close()
> 
> 
> run(main())
> ```

It works pretty well but after a while i get this error : 

RuntimeError: cannot enter context: <Context object at 0x7f9db195f0f0> is already entered
Exception in callback BaseAsyncIOLoop._handle_events(14, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(14, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
