### ISSUE TITLE
Coinbase Prime should be called Coinbase Exchange

### ISSUE THREAD

**Issue by aely-aronoff** [ccxt/ccxt#12999]
Apparently, Coinbase renamed a product that used to be called "Coinbase Prime" to "Coinbase Exchange":
https://help.coinbase.com/en/prime/onboarding/prime-faq

This means the CCXT exchange client for `coinbaseprime` is actually for Coinbase Exchange. You can see it in the URLs in the `coinbaseprime` class:
https://github.com/ccxt/ccxt/blob/master/python/ccxt/coinbaseprime.py

Looking at the new Coinbase Prime API docs, it looks like it's pretty different from the Coinbase Pro/Coinbase Exchange API.
Coinbase Prime API docs: https://docs.cloud.coinbase.com/prime/docs/introduction
Coinbase Pro/Exchange API docs: https://docs.cloud.coinbase.com/exchange/docs/welcome

Three differences I noticed are:
* Slight difference in the request headers (eg, `CB-ACCESS-KEY` on Pro/Exchange, `X-CB-ACCESS-KEY` on Prime)
* Different endpoints for fetching open vs filled orders (on Pro/Exchange you query `GET /orders` with different request params, Prime has a `GET /orders` endpoint to get closed orders and `GET /open_orders` to get open orders)
* Prime API doesn't have any public endpoints. My guess is they want those types of requests to go through the Pro/Exchange API instead.

Anyways, not sure how you want to handle it, but I would at least consider taking Coinbase Prime out of the list of supported exchanges and switching it to Coinbase Exchange, just to avoid any potential confusion.

**Comment by vitor-nascent** [comment]
Please, updates in this matter? It can really cause misunderstanding

**Comment by ttodua** [comment]
coinbase prime had been removed from ccxt at this stage
