### ISSUE TITLE
Cannot get Bybit spot (testnet) account balance

### ISSUE THREAD

**Issue by bugb** [ccxt/ccxt#12996]
- OS: MacOS
- Programming Language version: NodeJs v14
- CCXT version:  1.80.67

This code below does not get the right balance for spot account, instead the output as same as the balance for my future account  when using`'defaultType': 'future'`
```
const ccxt = require("ccxt");
const exchangeId = "bybit";
const exchangeClass = ccxt[exchangeId];
exchange = new exchangeClass({
  apiKey: "",
  secret: "",
  options: {
    'defaultType': 'spot',
  }
});
exchange.setSandboxMode(true)
async function getOrderBook(){
  // const data = await exchange.fetchOrderBook('ETHUSDT');
  // console.log({data: JSON.stringify(data)})
  const r = await exchange.fetchBalance();
  console.log({r})
}
getOrderBook().then().catch()
```

**Comment by kroitor** [comment]
@bugb please check this duplicate issue, we will add the support for bybit's spot markets asap: https://github.com/ccxt/ccxt/issues/9803

**Comment by bugb** [comment]
@kroitor thank for this!

**Comment by kroitor** [comment]
@bugb in the meantime you can still try to fetch it with the implicit API:

- https://docs.ccxt.com/en/latest/manual.html#implicit-api

```JavaScript
const ccxt = require("ccxt");
const exchangeId = "bybit";
const exchangeClass = ccxt[exchangeId];
exchange = new exchangeClass({
  apiKey: "",
  secret: "",
  options: {
    'defaultType': 'spot',
  }
});
exchange.setSandboxMode(true)
async function getOrderBook(){
  // const data = await exchange.fetchOrderBook('ETHUSDT');
  // console.log({data: JSON.stringify(data)})
  const r = await exchange.privateGetSpotV1Account();
  console.log({r})
}
getOrderBook().then().catch()
```

**Comment by bugb** [comment]
@kroitor awesome, it works, thank you a lot man!

**Comment by YuriyTigiev** [comment]
Hello, 

I have the same issue with python code.  
ccxt-1.82.37.dist-info

    import ccxt
    from pprint import pprint
    exchange = ccxt.bybit({
        'apiKey': 'key',
        'secret': 'secret',
        'options': {
            'defaultType': 'spot',
        }
    })
    markets = exchange.load_markets()
    exchange.verbose = True
    exchange.set_sandbox_mode(True)
    balances = exchange.fetchBalance()
    print(balances['USDT'], balances['BTC'])

result

`{'free': 0.0, 'used': 0.0, 'total': 0.0} {'free': 0.0, 'used': 0.0, 'total': 0.0}`


![image](https://user-images.githubusercontent.com/22752322/168462384-77d2a122-6d46-4746-9537-6cec35217142.png)

**Comment by carlosmiei** [comment]
Hello @YuriyTigiev,
Recently we updated Bybit's fetchBalance to handle spot markets. If you update your CCXT version and run that snippet again you should be able to see it now.

**Comment by YuriyTigiev** [comment]
Problem solved.

Successfully installed ccxt-1.82.52

{'free': 9970.65012, 'used': 0.0, 'total': 9970.65012} {'free': 1.000999, 'used': 0.0, 'total': 1.000999}

![image](https://user-images.githubusercontent.com/22752322/168463801-bad8b088-e098-4576-a1d8-edc79ca6156e.png)

**Comment by YuriyTigiev** [comment]
But it doesn't work for async mode 

```
import asyncio
import ccxt.async_support as ccxt


async def main():

    exchange = getattr(ccxt, 'bybit')({
        'apiKey': 'key',
        'secret': 'secret',
        'enableRateLimit': True})

    markets = await exchange.load_markets()
    exchange.verbose = True
    exchange.set_sandbox_mode(True)
    balances = await exchange.fetchBalance()
    print(balances['USDT'], balances['BTC'])


if __name__ == "__main__":

    loop = asyncio.new_event_loop()
    task = loop.create_task(main())
    loop.run_forever()

```

Result

`{'free': 0.0, 'used': 0.0, 'total': 0.0} {'free': 0.0, 'used': 0.0, 'total': 0.0}`

**Comment by kroitor** [comment]
@YuriyTigiev it should not really depend on whether it's sync or async, could it be that you're using different versions of keys there?

**Comment by YuriyTigiev** [comment]
You are right. Everything ok.

```
import asyncio
import ccxt.async_support as asyncccxt
import ccxt as syncccxt


async def main():

    exchange_async = getattr(asyncccxt, 'bybit')({
        'apiKey': 'q2Qo73HkZ45QcrWOuE',
        'secret': 'A4ydLt1vQLZX53MweOjPv0z9OHH6pr6aZ4PD',
        'options': {
            'defaultType': 'spot',
        }})

    markets = await exchange_async.load_markets()
    exchange_async.set_sandbox_mode(True)
    balances = await exchange_async.fetchBalance()
    print('Async:', balances['USDT'], balances['BTC'])


if __name__ == "__main__":

    exchange_sync = syncccxt.bybit({
        'apiKey': 'q2Qo73HkZ45QcrWOuE',
        'secret': 'A4ydLt1vQLZX53MweOjPv0z9OHH6pr6aZ4PD',
        'options': {
            'defaultType': 'spot',
        }
    })
    markets = exchange_sync.load_markets()
    exchange_sync.set_sandbox_mode(True)
    balances = exchange_sync.fetchBalance()
    print('Sync:', balances['USDT'], balances['BTC'])

    loop = asyncio.new_event_loop()
    task = loop.create_task(main())
    loop.run_forever()

```

Results

```
Sync: {'free': 9970.65012, 'used': 0.0, 'total': 9970.65012} {'free': 1.000999, 'used': 0.0, 'total': 1.000999}
Async: {'free': 9970.65012, 'used': 0.0, 'total': 9970.65012} {'free': 1.000999, 'used': 0.0, 'total': 1.000999}
```
