### ISSUE TITLE
gate io await watch_order_book not returning result after some time

### ISSUE THREAD

**Issue by leastchaos** [ccxt/ccxt#13000]
Sorry I am having issue with gate.io orderbook not updating after a while
I added async_timeout to the code to test.
there were no issues with other exchange with the same code.
It seems that there is order_book_update but the await does not return it.
Can you help to check?

Also, how do i reset the connection from here as calling the method again does not work?

- OS: linux
- Programming Language version: python 3.10.4
- CCXT version: 1.0.98

```
import async_timeout
import asyncio
import ccxtpro
from pprint import pprint
import sys
sys.stdout = open('error', 'w')
print(ccxtpro.__version__)
symbol = 'EXRD/USDT'
exchange: ccxtpro.Exchange = getattr(ccxtpro, 'gateio')({
    'enableRateLimit': True,
    'apiKey': '',
    'secret': '',
    'uid': '',
    'options': {
        'defaultType': 'margin', # spot margin
    }
})
async def main():
    while True:
        try:
            async with async_timeout.timeout(10):
                response = await exchange.watch_order_book(symbol)
        except asyncio.TimeoutError:
            print('@@@@timeout@@@@', response['timestamp'])
    await exchange.close()
asyncio.run(main())
```
[gateio orderbook.txt](https://github.com/ccxt/ccxt/files/8558711/gateio.orderbook.txt)

**Comment by leastchaos** [comment]
@carlosmiei, i think roughly 30mins for this run but sometimes it can run for quite some time before it stops. 
I think the issue starts when suddenly there is a large block of update which happens to be the next block 
after that the await stops.
for this run the timestamp stopped at 1650902404541 and the next update was much larger than usual

`2022-04-25T16:00:04.906Z message {"time":1650902404,"channel":"spot.order_book_update","event":"update","result":{"t":1650902404541,"e":"depthUpdate","E":1650902404,"s":"EXRD_USDT","U":51198605,"u":51198613,"b":[["0.1196","3555.652"],["0.1168","1415.06"],["0.1241","2489.457"],["0.1238","1587.606"],["0.1236","1495.458"],["0.0909","0"],["0.091","0"],["0.0915","0"]],"a":[["0.1245","1294.791"],["0.1244","430.779"]]}}`
`2022-04-25T16:00:06.062Z message {"time":1650902406,"channel":"spot.order_book_update","event":"update","result":{"t":1650902405867,"e":"depthUpdate","E":1650902405,"s":"EXRD_USDT","U":51198624,"u":51198624,"b":[["0.122","2470.871"],["0.1196","3555.652"],["0.1241","2489.457"],["0.1222","82781.177"],["0.1137","10.08"],["0.0949","263.435"],["0.091","1000"],["0.1224","95.478"],["0.1217","2813.275"],["0.1184","18.714"],["0.101","276.333"],["0.119","8.126"],["0.1156","10.08"],["0.1232","26887.413"],["0.1183","307.852"],["0.1181","186.267"],["0.0982","75.095"],["0.1211","59.796"],["0.095","6612.788"],["0.0934","2060.176"],["0.112","297.231"],["0.0915","860.488"],["0.1231","0"],["0.1207","443.882"],["0.1176","1700.68"],["0.1056","552.8"],["0.1165","623.544"],["0.1066","10.08"],["0.109","100.611"],["0.1159","1000"],["0.1022","1956.947"],["0.1049","10.08"],["0.1234","24191.62"],["0.1225","1326.468"],["0.1101","76.126"],["0.1175","10.08"],["0.1111","6710.78"],["0.11","4651.263"],["0.0927","79.83"],["0.1235","4837.054"],["0.0916","545.851"],["0.1119","18.212"],["0.1106","2000"],["0.123","11852.526"],["0.1168","1415.06"],["0.115","2174.178"],["0.1187","710.288"],["0.1202","1171.466"],["0.1233","16690.963"],["0.1082","211.967"],["0.1016","10.08"],["0.1228","24159.49"],["0.104","70.485"],["0.1001","72.298"],["0.1167","232.121"],["0.1223","24169.6"],["0.1236","1495.458"],["0.105","2584.761"],["0.1122","66.59"],["0.1213","4078.74"],["0.1237","6735.738"],["0.098","10275.5"],["0.108","68.614"],["0.1188","62.112"],["0.1121","4402.58"],["0.1026","9.746"],["0.1195","355.288"],["0.1013","493.583"],["0.1238","1587.606"],["0.1226","23968.724"],["0.093","16883.416"],["0.1227","643.033"],["0.0977","14.28"],["0.1086","1000"],["0.0942","255"],["0.1033","48.4"],["0.12","494619.623"],["0.1197","1186.686"],["0.1216","40125.004"],["0.124","8361.737"],["0.1218","18.714"],["0.1032","10.08"],["0.1205","2101.919"],["0.1229","24540.766"],["0.1084","10.08"],["0.1194","10.08"],["0.0945","76.846"],["0.1192","429.01"],["0.106","67.874"],["0.1166","456.085"],["0.1","21439.828"],["0.0921","108.577"],["0.102","73.249"],["0.0963","78.059"],["0.1215","2479.168"],["0.1219","0"],["0.1239","11406.368"],["0.121","1091.179"],["0.1212","805.907"],["0.1206","18.714"],["0.1189","406.774"],["0.1144","64.077"]],"a":[["0.1405","7.618"],["0.1377","987.876"],["0.1307","76.681"],["0.1376","437.686"],["0.1248","2404.338"],["0.132","78.714"],["0.1245","1294.791"],["0.1409","33.737"],["0.1332","74.505"],["0.1357","41.623"],["0.1299","3036.421"],["0.127","560.413"],["0.1403","507.65896"],["0.1381","150.834"],["0.1394","60"],["0.1254","3426.16"],["0.1338","52.451"],["0.1295","18.714"],["0.1258","134.617"],["0.1287","301.129"],["0.1411","53.716"],["0.1279","737.277"],["0.125","8835.714"],["0.1259","32234.972"],["0.1301","18.714"],["0.1407","221.816"],["0.1351","52.451"],["0.1247","6414.459"],["0.1402","17.946"],["0.1364","52.451"],["0.1326","18.714"],["0.139","52.451"],["0.1274","41967.483"],["0.1324","635.115"],["0.1294","10.08"],["0.1397","18.714"],["0.1344","1172.662"],["0.133","19363.276"],["0.1253","23867.832"],["0.1384","72.459"],["0.1298","1028.464"],["0.1272","2621.61"],["0.1318","33.737"],["0.1265","82919.347"],["0.1396","276.59657175"],["0.13","1000"],["0.1269","74.669"],["0.14","921.22"],["0.1286","2081.785"],["0.1249","74.617"],["0.1379","1500.71226812"],["0.1362","60"],["0.1356","20"],["0.1392","9.136"],["0.1257","27351.736"],["0.1268","60"],["0.1246","2456.475"],["0.1282","57.816"],["0.1267","1538.292"],["0.1262","26634.417"],["0.1289","78.714"],["0.1331","93.737"],["0.1358","74.558"],["0.126","745.145"],["0.1345","18.714"],["0.1337","10.08"],["0.1252","1789.602"],["0.1311","212.007"],["0.1371","1401.768"],["0.1305","33.737"],["0.1325","6891.498"],["0.1271","1303.744"],["0.1293","1729.597"],["0.1244","79.521"],["0.1285","2583.608"],["0.1373","60"],["0.128","1541.285"],["0.1359","10.08"],["0.1353","7.91"],["0.1277","18.714"],["0.1317","338.575"],["0.141","448.773"],["0.1292","2531.825"],["0.1314","153.115578"],["0.1341","60"],["0.1261","24132.157"],["0.131","60"],["0.1383","93.737"],["0.1283","18.714"],["0.1255","47091.563"],["0.1273","108.354"],["0.1312","33.737"],["0.1278","2050.659"],["0.1313","18.714"],["0.1404","60"],["0.1264","74.669"],["0.137","52.451"],["0.1352","60"],["0.1316","10.08"],["0.1251","1000"]]}}`

**Comment by leastchaos** [comment]
[order_book_2.txt](https://github.com/ccxt/ccxt/files/8572632/order_book_2.txt)
this is another log if it can help.
maybe it is due to illiquid order book leading to internal timeout as sometimes there is no order book update for seconds which is not handled?
for now i have done the following but its not ideal as there can still be a gap of 30second of stale orderbook but it has helped me restart the connection whenever it fails.

```
async def main():
    while True:
        try:
            async with async_timeout.timeout(30):
                response = await exchange.watch_order_book(symbol)
        except asyncio.TimeoutError:
            print('@@@@timeout@@@@', response['timestamp'])
            await exchange.close()
    await exchange.close()
asyncio.run(main())
```

**Comment by carlosmiei** [comment]
@leastchaos humm not sure, even if there's no update for a long time the connection has to stay alive regardless and uses the ping-pong mechanism to signal this intention. I'll take a look at your logs because unfortunately, I could not reproduce it yet

**Comment by carlosmiei** [comment]
@leastchaos  Actually I don't think you should be using this timeout option.  watchOrderBook will only return after getting an update regardless of how much time has passed (it might take minutes, hours, etc). The state of the connection with the exchange is maintained internally by ccxt so you should not worry about that.

**Comment by leastchaos** [comment]
@carlosmiei I did not do this initially, this was added for gateio because of the stale orderbook issue which took me sometime to found out as it is impacting my script. so I had to add it in order to correct it.

**Comment by leastchaos** [comment]
just a update, i changed my server to another server with a much lower latency to gateio and this issue does not seem to occur since.

**Comment by kroitor** [comment]
@leastchaos do you have this issue with the most recent versions of CCXT (1.81.30) and CCXT Pro (1.1.10+) ?

**Comment by DulajSP** [comment]
I'm still getting this issue with the latest version. Any update on this?

**Comment by carlosmiei** [comment]
Hello @DulajSP, can you please the snippet of the code you're using?

**Comment by DulajSP** [comment]
`while (true) {
    try {
      var ticker = await gateio.watchOrderBook("XCAD/USDT");
      if (ticker && ticker.bids && ticker.bids[0]) {
        bestBid = ticker.bids[0][0];
      }
      if (ticker && ticker.asks && ticker.asks[0]) {
        bestAsk = ticker.asks[0][0];
      }

      console.log(new Date().toLocaleString(), bestBid, bestAsk);
    } catch (error) {
      console.log(error);
    }

    await sleep(100);
  }`

**Comment by DulajSP** [comment]
New version running smoothly. Thank you for fixing it.

**Comment by carlosmiei** [comment]
@DulajSP thank you for your help debugging it 🙂
