### ISSUE TITLE
New exchange: dydx

### ISSUE THREAD

**Issue by coding-lover** [ccxt/ccxt#13005]
Would request https://dydx.exchange/ exchange support in ccxt

**Comment by kroitor** [comment]
See this duplicate issues: 

- https://github.com/ccxt/ccxt/search?q=dydx
- https://github.com/ccxt/ccxt/issues/9272
- https://github.com/ccxt/ccxt/pull/11643

We will merge it shortly.

**Comment by coding-lover** [comment]
您好，您发的邮件我已收到，谢谢。

**Comment by coding-lover** [comment]
您好，您发的邮件我已收到，谢谢。
