### ISSUE TITLE
balance format unify account address

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1301]
i think we need to fetch and parse properly when the account wallet address is available.  Also noticed that this is under progress.

ref: https://github.com/ccxt/ccxt/wiki/Manual#querying-account-balance

**Comment by kroitor** [comment]
Hi! This is mostly covered by [fetchDepositAddress()](https://github.com/ccxt/ccxt/pull/653). We are going to add address parsing to balance structures as well, working on it. Your contributions are welcome. Let me know if you have more questions and details on this.

**Comment by jjhesk** [comment]
@kroitor it is great. i have working on implementations of this library and i also working to source more developer to work on this project.

**Comment by kroitor** [comment]
@jjhesk would you mind if I close this issue temporarily? We will update you on progress anyway.
