### ISSUE TITLE
bleutrade tries to use bittrex

### ISSUE THREAD

**Issue by claytondukes** [ccxt/ccxt#1303]
- OS: osx
- Programming Language version: Python 2.7.12
- CCXT version: 1.10.730
- Exchange: Bleutrade
- Method: fetch_balance

Getting Bleutrade balance is referencing bittrex:

I'm thinking that #1234 may be causing this?

```
import ccxt
bleutrade = ccxt.bleutrade ()
bleutrade.apiKey = 'blah'
bleutrade.secret = 'blah'
print (bleutrade.fetch_balance ())
```
```
Traceback (most recent call last):
  File "./bleutrade.py", line 11, in <module>
    print (bleutrade.fetch_balance ())
  File "/usr/local/lib/python2.7/site-packages/ccxt/bittrex.py", line 211, in fetch_balance
    balances = response['result']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by gaardiolor** [comment]
At first I thought it was weird too - then I figured out that this happens because bleutrade inherets some methods from bittrex, because they are similar. I think this is by-design.

**Comment by claytondukes** [comment]
Er, ok - but it's borked somehow I guess - I can't fetch balance :)

**Comment by kroitor** [comment]
@claytondukes show verbose output, please (always).

```
import ccxt
bleutrade = ccxt.bleutrade ()
bleutrade.verbose = True
bleutrade.apiKey = 'blah'
bleutrade.secret = 'blah'
print (bleutrade.fetch_balance ())
```

**Comment by claytondukes** [comment]
Please forgive my noobness/lack of python-fu. I'm a bit old school (shell, perl, etc.) :)

It's my own stupidity, I had the secret wrong...ugh!

```
u'{"success":"false","message":"Invalid apikey or apisecret","result":[]}')
Traceback (most recent call last):
  File "bleutrade.py", line 10, in <module>
    print (bleutrade.fetch_balance ())
  File "/usr/local/lib/python2.7/site-packages/ccxt/bittrex.py", line 211, in fetch_balance
    balances = response['result']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by kroitor** [comment]
@claytondukes thanks for reporting back anyway! Let us know if you have any difficulties with it. We will try to make it throw a more readable error.
