### ISSUE TITLE
Why I can't use setMarginMode to just change leverage?

### ISSUE THREAD

**Issue by 9808us** [ccxt/ccxt#13046]
HI! Just a quick question here!

I wonder why I can't use setMarginMode to just change the leverage.

I see that if the type of margin in the exchange doesn't match the one set by setMarginMode then I can change leverage.
But if I try to just change the leverage and marginType matches with the exchange, then the leverage is unaffected and not changed.

I see I can use set_leverage and change leverage with that ... but to me it would be more useful to just have one method and with that control both the leverage and the type of margin.

Is there any particular reason for this behaviour?

**Comment by samgermain** [comment]
What exchange and what language are you using?

Could you also share you CCXT version?

**Comment by 9808us** [comment]
Oh sorry, I thought it was a standard behaviour for all exchanges.

Exchange is Bybit
CCXT version = '1.66.17'

I was also referring to this issue https://github.com/ccxt/ccxt/issues/11268 
as explained here https://github.com/ccxt/ccxt/issues/11268#issuecomment-1018086375

**Comment by samgermain** [comment]
> Oh sorry, I thought it was a standard behaviour for all exchanges.
> 
> Exchange is Bybit CCXT version = '1.66.17'
> 
> I was also referring to this issue #11268 as explained here [#11268 (comment)](https://github.com/ccxt/ccxt/issues/11268#issuecomment-1018086375)

This has to do with Bybit's api, if you try to set the margin mode to `isolated` and it's already `isolated` bybit returns an error response, CCXT squelches this error response because we felt that trying to change to isolated and staying as isolated wasn't an error, but maybe this is a reason to not squelch the response, @kroitor what do you think

**Comment by samgermain** [comment]
@9808us I'm going to close this issue. Feel free to reopen it if you have any more questions
