### ISSUE TITLE
Get currency by its id

### ISSUE THREAD

**Issue by Deathamns** [ccxt/ccxt#1304]
There's currently an `exchange.currency()` method, I would like to have a `currencyById` map or function or something for getting currencies by their id.

**Comment by kroitor** [comment]
Will add that property as well! Thank you!

**Comment by kroitor** [comment]
Added `.currencies_by_id` property in 1.10.758. Thx!

**Comment by Deathamns** [comment]
I asked this because some exchanges use unique IDs for currencies (and for markets), but don't give currency codes(/market symbols), so for example `commonCurrencyCode` doesn't help there. I could define the `markets` in `describe` with currency IDs, however the exchange has APIs for both `fetchCurrencies` and `fetchMarkets`.
Another problem is that `loadMarkets` first fetches the markets then generates the currencies, but the exchange sends markets like this: `[{base: '1', quote: '2', ...}, ...]`, so they send only currency IDs, and at this point I already have to know what are the codes for those currency IDs.
I could do `this.currencies = await this.fetchCurrencies()` in the beginning of `fetchMarkets`, but perhaps there is a more elegant solution...

Also, camelCase? As with [marketsById](https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L500).
