### ISSUE TITLE
kucoin returns empty order for 400200

### ISSUE THREAD

**Issue by SmartManoj** [ccxt/ccxt#13047]
- OS:
- Programming Language version: Py
- CCXT version: 1.80.54 

{"code":"400200","msg":"Forbidden to place an order"}

Discussion: https://t.me/KuCoin_API/110144

**Comment by kroitor** [comment]
Here's a related issue: https://github.com/ccxt/ccxt/issues/13047

**Comment by kroitor** [comment]
I've pushed a fix in CCXT 1.81.3 (the new build will arrive in ~20 minutes). Thanks for reporting!

**Comment by SmartManoj** [comment]
@kroitor Any reason for this error? Happens when created order before listing. The error should be `BadSymbol`.

**Comment by kroitor** [comment]
@SmartManoj do you still have this issue with the most recent version of CCXT (1.82+) ?
