### ISSUE TITLE
New Exchange: zarclays.com

### ISSUE THREAD

**Issue by layinka** [ccxt/ccxt#13050]
Would like to request https://zarclays.com/ exchange support in ccxt

See PR 

[PR 13049](https://github.com/ccxt/ccxt/pull/13049)

**Comment by ttodua** [comment]
website doesn't even work, when you click "trade" button on homepage, the links are broken.

**Comment by layinka** [comment]
Just looked through, thats fixed now

**Comment by frosty00** [comment]
looks like a scam, the terms of service are just copied and pasted from binance

**Comment by layinka** [comment]
Definitely Not a scam.

Been waiting for anyone to respond since 

terms of service is being replaced, dev used that before now

**Comment by frosty00** [comment]
@layinka we won't list it on ccxt because the exchange is too small

**Comment by layinka** [comment]
its fine

i think you should make the requirements clear. I never knew there was any size requirement.

**Comment by frosty00** [comment]
@layinka we don't have any requirements but we need to protect our users, because a small unknown exchange could easily exit scam
