### ISSUE TITLE
How can i make a stop-loss or stop limit order on phemex?

### ISSUE THREAD

**Issue by CloudTrauma** [ccxt/ccxt#13052]
- OS: Windows 11
- Programming Language version: Python
- CCXT version: 1.81.4

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/blob/master/examples/py/phemex-open-cancel-close-positions.py
- https://github.com/ccxt/ccxt/blob/master/examples/py/phemex-create-stop-order.py

**Comment by CloudTrauma** [comment]
Thanks
