### ISSUE TITLE
huobi fetch_order_book and watch_order_book swap

### ISSUE THREAD

**Issue by pickmone** [ccxt/ccxt#13068]
Hello, 

i see that for Huobi swap the fetch_orderbook and watch_orderbook function returns the amount in term of contracts rather than underlying, which is different than other exchanges. 

Would it be possible to have Huobi swap return amount in term of underlying amount like the other exchanges?

**Comment by kroitor** [comment]
The majority of the exchanges will return derivatives' amounts in contracts as whole integers. Most of the exchanges will only accept integer amounts with `createOrder` for swaps, futures and other contracts.

CCXT returns whatever is available from the exchange, we can't invent that info out of thin air, so what you see is what you get from the exchange first-hand, for example: https://huobiapi.github.io/docs/usdt_swap/v1/en/#general-subscribe-incremental-market-depth-data

Hope that answers your question, let us know if not.
