### ISSUE TITLE
[bybit] possible bad error mapping?

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#13077]
I'm getting this from time to time which is being reported as `RateLimitExceeded`:

`POST https://api.bybit.com/private/linear/order/cancel 403 Forbidden <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;waffailover&#46;bybit&#46;com&#47;error&#46;json" on this server.<P>
Reference...
</BODY>
</HTML>`

Is this intentional?

**Comment by kroitor** [comment]
@npomfret can you please paste the code to reproduce it ?

**Comment by npomfret** [comment]
I checked with the exchange.  This is the correct error for that response
