### ISSUE TITLE
1 Hour Data is Missing

### ISSUE THREAD

**Issue by euphrates85** [ccxt/ccxt#13071]
- OS: Windows
- Programming Language version: Python 3.10
- CCXT version: 1.77.62

```
import ccxt
import pandas as pd
import numpy as np
import datetime
import warnings

warnings.filterwarnings("ignore", category=np.VisibleDeprecationWarning)
pd.set_option('display.max_rows', None)

exchange = ccxt.binance({
    "apiKey": 'xxx',
    "secret": 'yyy',
    'options': {
        'adjustForTimeDifference': True
    },
    'enableRateLimit': True
})

exchange_f = ccxt.binance({
    "apiKey": 'xxx',
    "secret": 'yyy',
    'options': {
        'defaultType': 'future',
        'adjustForTimeDifference': True
    },
    'enableRateLimit': True
})

coin = "ETH"+"/USDT"
exchange.load_markets()
exchange_f.load_markets()
data= pd.DataFrame([[0]], columns=['timestamp'])
# some codes here

while 1:
    try:
        bars = exchange.fetch_ohlcv(coin, timeframe='5m', limit=10)   
        bars_f = exchange_f.fetch_ohlcv(coin, timeframe='5m', limit=2)  
        df = pd.DataFrame(bars[:], columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
        df_f = pd.DataFrame(bars_f[:], columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
    except ccxt.BaseError as Error:
        print("[ERROR] ", Error)
        continue

if df['timestamp'].iloc[-2] not in data.values and (df['timestamp'].dt.minute.iloc[-2] % 10 == 5):
 data= pd.DataFrame([[df['timestamp'].iloc[-2]]], columns=['timestamp'])
print('time', data)
```

Hello,
I am using above code and i realized today that my code didn't work properly around 1 hour. The code "print('time', data)" produced "time 2022-05-01 19:35:00" and  then same code produced "time 2022-05-01 20:45:00" next. Around 1 hour is missing. 
I am using Amazon server i dont know if the problem resulted from this or not. Maybe i was banned from Binance for an hour but if this was the case wouldnt i receive any error? Could you please advise me if i broke the rate limiter?
Could you please share what could be the reasons?
Thank you.

**Comment by euphrates85** [comment]
@kroitor i would be appreciated if you can check the above code and share with me if there is a possbility that i broke the ratelimiter? I read the documents but my coding knowledge is not very good and i coudnt understand the documents exactly. I didnt get any error related to ban but some say that i dont have to receive an error if i am banned.

**Comment by samgermain** [comment]
@euphrates85 Could you be more specific with your explanation? 

For example, you said 

> The code "print('time', data)" produced "time 2022-05-01 19:35:00" and then same code produced "time 2022-05-01 20:45:00" next

but I only see the line `"print('time', data)"` once in your code so I'm not exactly sure what you mean by "next". Could you also minimize your code to exclude all non-necessary code for your example? It doesn't look like `df_f`, `exchange_f` or `data_f` are needed.

**Comment by euphrates85** [comment]
it was due to the low performance of server. I updated and it is solved
