### ISSUE TITLE
Running example code: AttributeError: type object '_asyncio.Task' has no attribute 'all_tasks'

### ISSUE THREAD

**Issue by reisenmachtfreude** [ccxt/ccxt#13085]
I've tried to run this example:
https://github.com/ccxt/ccxt/blob/master/examples/py/async.py

The following error appears:
```
Traceback (most recent call last):
  File "/home/somthing/test.py", line 39, in <module>
    pending = asyncio.Task.all_tasks()
AttributeError: type object '_asyncio.Task' has no attribute 'all_tasks'
```

- OS: Ubuntu 21.10
- Programming Language version: Python 3.9.7
- CCXT version: 1.81.26

**Comment by carlosmiei** [comment]
Hello @reisenmachtfreude, this example is 5 years old now and some APIs have changed since then, I'll fix it asap. Thanks for reporting it.
