### ISSUE TITLE
Request Timed Out (10000 ms) Node/Nginx

### ISSUE THREAD

**Issue by jackel27** [ccxt/ccxt#1308]
<hr>

> **Operating System**: Ubuntu 16.04.3 LTS - NodeJS v8.9.4 - NGINX
> **Programming Language Version**: JS
> **CCXT Version**: Latest,
> **Echange**: Bittrex,
> **Method(s)**: async() FetchMarketsSummary, balance, and a few others..
<hr>
First off, Great Job! I'm loving it! <3

Locally all of this works. I have a proxy set up, (as defined in the CCXT manual/installation) to avoid CORS issues. During my development - it work flawless.

I have now moved to host it on a digital ocean droplet, but experiencing issues with CORS (or related?).

I am thinking it may be an NGINX related setup as during page load I get timeouts in the console, but again, I am not sure.

From the console:

```console
m: bittrex GET http://m.y.i.p.:8080/https://bittrex.com/api/v2.0/pub/Markets/GetMarketSummaries request timed out (10000 ms)
    at h.catch.i (http://m.y.i.p./static/js/vendor.4fa3562b56993144a72d.js:1:340155)
    at <anonymous>
```

I am **not** very familiar with CORS and how to get around it with the server side of things. I am not receiving a CORS error response, but instead just timeouts. I am curious on if anyone has had any luck with NGINX + CCXT. Not sure if there is additional configuration server side. 

I have tried setting up NGINX config for allowing all and setting the Headers properly with no luck. I have tried [other suggestions](https://enable-cors.org/server_nginx.html) as well which has not got me anywhere. 

```.mod
node proxy 8080
```
Bittrex.js Instatiation
```js
import ccxt from 'ccxt'
export let bittrex
export function init (key, secret) {
  // eslint-disable-next-line
  bittrex = new ccxt.bittrex({
    apiKey: key,
    secret: secret
  })
  bittrex.proxy = 'http://127.0.0.1:8080/'
 // Have also tried: 'http://MY.IP:8080
}

export default {
  bittrex,
  init
}

```
 node proxy.js is running in the background (new window): 
```javascript 
let port = (process.argv.length > 2) ? parseInt (process.argv[2]) : 8080; // default
require ('cors-anywhere').createServer ().listen (port, 'localhost')
```

**Comment by kroitor** [comment]
Hi! One question: why do you need nginx in the first place?

**Comment by jackel27** [comment]
That is a good question, I may end up expanding and nginx could be helpful. I ended up exposing the port properly with NGINX in addition to adjusting the built in firewall. Still using the Proxy script. Here is my project so far on [GitHub. ](https://github.com/jackel27/mybittrex)
and I have it hosted [here.](http://kaiserdome.com)
(**_Please do not test with your api/key permissions set to full!_**)
If anyone needs help with setting it up with NGINX / NODE - Let me know..
I will help out anyway I can. Thanks!

**Comment by kroitor** [comment]
Thank you for reporting back, @jackel27 ! And for the proposal as well! Feel free to ask if you have any other questions! Cheers!
