### ISSUE TITLE
Buying a large group of wallets at once

### ISSUE THREAD

**Issue by Sadam-beshr** [ccxt/ccxt#13095]
I used a repeat buying ring for everyone who subscribed to me in a certain currency.. If the number of subscribers is 100 subscribers...there is a difference between the purchase from the first person to the last....Is there a solution to buy for everyone without using the order limit. I want to use the market purchase for everyone at the same time ... knowing that the time difference between buying for the first subscriber until the last subscriber is 3 minutes ... which is a very big time ...... What is the correct way to buy for all subscribers at once
`for($i=0;$i<=$cou;$i++){
$myapi = new Binance\API($api_key,$api_secret);
 	$order =$myapi->buy($symbol, $quantity, 0, "MARKET");
}`

The problem is that there is a difference between the time of buying the first wallet and the last one..... What is the solution to buying all the wallets at once at one price?

**Comment by samgermain** [comment]
There's no unified method for placing multiple orders, and it doesn't look like there's an implicit method for binance spot, but there is a [binance futures method for placing batch orders](https://binance-docs.github.io/apidocs/futures/en/#place-multiple-orders-trade). This method would be `dapiPrivatePostBatchOrders` using CCXT. It is an [implicit method](https://docs.ccxt.com/en/latest/manual.html#implicit-api).
. 
![](https://i.imgur.com/kFj2Pjc.png)
![](https://i.imgur.com/3R5Lmwz.png)

**Comment by ttodua** [comment]
I will add another comment to above answer - what you want, can be definitely achieved easily. It seems you are not familiar with asynchronous programming, so you should get familiar with it, and then you will be able to make 100 purchases for 100 users (or whatever) is quicker asynchronously.
 See [this](https://github.com/ccxt/ccxt/blob/master/examples/php/load-all-at-once-async.php) or [this](https://github.com/ccxt/ccxt/blob/master/examples/php/async-multiple-tickers-one-exchange.php) example (or other exchanges under `/examples/php` folder.


But as I see, you use PHP, it's a bit specific (compared to JS) and I assume that your script is being called on request-basis. In such case, you should consider - when instantiating so many instances (and thus, loading same markets simultaneously across 100 instances) binance might ban your IP, so you have to do one of the following:

1) make some custom snippet, where you load binance instance separately (before those 100 loops), then use `load_markets()` for that first instance, and then when you create all other instances, do not call `load_markets()` for them, instead use the already loaded markets from first instance, and set those markets manually with `set_markets($markets)` for other instances. thus, you will avoid making 100 `load_markets()` call simultaneously, and it will be uncomparable performance. 

or you can do:

2) asynchronously load all those 100 instances, but make an artificial 'sleep' between calling their `load_markets()` like:
```
$async_array = [];
for ($i=0; $i<$usersAmount; $i++)
{
   $instance = new ccxt\\binance([...]);
   $async_array[$i] =function() use ($instance, $i) {
       sleep($i);
       yield $instance->load_markets();
       yield $instance->create_order(....);
   }
}
yield $async_array;
```
this is just idea/pseudo-code, but you should do per your needs and do your homework per your needs.

Let us know if you have further issues with CCXT.
