### ISSUE TITLE
how can I fetch all coins order history trade ?

### ISSUE THREAD

**Issue by babydl-abc** [ccxt/ccxt#13093]
- OS: Windows10/64
- Programming Language version: Python 3.9.9
- CCXT version: 1.77

```
# work code when fixed symbol 
symbol = 'ALGO/USDT'
get_orders = exchange.fetch_my_trades(symbol)

# doesn't work code when i need get all symbol history
get_trade_list = exchange.fetch_my_trades()   --> error


```

```
ccxt.base.errors.ArgumentsRequired: binance fetchMyTrades() requires a symbol argument
```

how can I fetch all coins order history trade ?

**Comment by kroitor** [comment]
> how can I fetch all coins order history trade ?

Depending on the exchange, you have to iterate over all symbols. This is documented in the Manual. I would highly recommend reading the entire Manual from top to bottom – it has the answers to most of the starting questions and it will really save your time.

- https://docs.ccxt.com/

Also, check the examples here:

- https://github.com/ccxt/ccxt/tree/master/examples/

Hope that helps, let us know if not.
