### ISSUE TITLE
Question - CoinMarketCap, CoinGeko, etc aggregators

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#13092]
Will ccxt support any aggregator like CoinMarketCap, CoinGeko, etc ? 
I

**Comment by kroitor** [comment]
Hi! Yes, we hope to unify that eventually, there's a few dedicated issues:

- https://github.com/ccxt/ccxt/issues/6580
- https://github.com/ccxt/ccxt/issues/3543

**Comment by YuriyTigiev** [comment]
Can you consider a free API of  https://min-api.cryptocompare.com/ ? 
Yes. This API is partially free  but I think for most cases it will be enough.

**Comment by kroitor** [comment]
@YuriyTigiev we're not against that too, will probably have to make a sublist of aggregators to unify.

**Comment by YuriyTigiev** [comment]
Hello,

Did you have to implement supporting any aggregators?
If yes, how can I use it?
