### ISSUE TITLE
New Exchange: Radar Relay

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1310]
api doc: https://radarrelay.com/standard-relayer-api/
url: https://radarrelay.com
volume: N/A
address: 824 South College Avenue, Fort Collins, CO 80524, United States
company info: Radar Relay, LLC, https://www.bloomberg.com/profiles/companies/1567056D:US-radar-relay-llc, http://www.whogotfunded.com/companies/265914-radar-relay-llc, https://www.linkedin.com/company/radar-relay/
based country: USA
demo: https://app.radarrelay.com/ZRX/WETH, https://www.youtube.com/watch?v=_FMbAYxaEM4
priority: low
news: https://medium.com/@RadarRelay
type: decentralised ex

**Comment by jjhesk** [comment]
they just dropped the document for api.

**Comment by ChTejaswini** [comment]
how u added language switching in this project

**Comment by Djusk8** [comment]
Exchange is not working. 
Url [https://radarrelay.com](https://radarrelay.com) is redirecting to [https://radar.tech/](https://radar.tech/).
I think this issue can be closed.
