### ISSUE TITLE
Binance credit card transactions

### ISSUE THREAD

**Issue by steebchen** [ccxt/ccxt#13111]
It seems like fetchWithdrawals/fetchDeposits for Binance does not return credit card transactions. Is there a way to get these?

**Comment by samgermain** [comment]
That seems like something binance should have, but I looked through all the endpoints under `https://binance-docs.github.io/apidocs/spot/en/#wallet-endpoints`, `https://binance-docs.github.io/apidocs/spot/en/#fiat-endpoints` and `https://binance-docs.github.io/apidocs/spot/en/#pay-endpoints` and couldn't find one that returned the credit card transactions
