### ISSUE TITLE
Bybit, how get spot wallet blance ?

### ISSUE THREAD

**Issue by markHervagault** [ccxt/ccxt#13123]
Hi,

why "fetchBalance" of bybit.js does not return the funds in the 'spot' account ? And how to get them ?

Thank,
Mark.

**Comment by carlosmiei** [comment]
Hello @markHervagault,
Currently, it is not supported by `fetchBalance` (it is being migrated right now) but you can always use the implicit API to get the raw balance data.

Example:
```Python

import ccxt  # noqa: E402

exchange = ccxt.bybit({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET_KEY',
}

spotBalance = this.privateGetSpotV1Account()
print(spotBalance)

```
Feel free to reopen it if anything!
