### ISSUE TITLE
Okx BBO watch orderbook

### ISSUE THREAD

**Issue by pickmone** [ccxt/ccxt#13124]
Hello, 

with OkX’s change to the orderbook channel, I see that the BBO channel is included as part of the watch orderbook function. Is it possible to move the BBO channel to the watch ticker function like the other exchanges?

thank you

**Comment by kroitor** [comment]
1. Make sure your version of CCXT Pro is 1.1.16+ (the new build will arrive in ~20 minutes)
2. Check this snippet: https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/okx-bbo-tbt.py

```Python
import ccxtpro
from asyncio import run


print('CCXT Pro version', ccxtpro.__version__)


async def main():
    exchange = ccxtpro.okx({
        'options': {
            'watchOrderBook': {
                'depth': 'bbo-tbt',  # tick-by-tick best bidask
            },
        },
    })
    markets = await exchange.load_markets()
    # exchange.verbose = True  # uncomment for debugging purposes if necessary
    symbol = 'BTC/USDT'
    while True:
        try:
            # -----------------------------------------------------------------
            # use this:
            # orderbook = await exchange.watch_order_book(symbol)
            # print(orderbook['datetime'], symbol, orderbook['asks'][0], orderbook['bids'][0])
            # -----------------------------------------------------------------
            # or this:
            ticker = await exchange.watch_ticker(symbol)
            print(ticker['datetime'], symbol, [ticker['ask'], ticker['askVolume']], [ticker['bid'], ticker['bidVolume']])
            # -----------------------------------------------------------------
        except Exception as e:
            print(type(e).__name__, str(e))
            break
    await exchange.close()


run(main())
```

Hope that answers your question, let us know if not.

**Comment by pickmone** [comment]
Thanks! Just wondering if set the option here to BBO, would it also impact watch_orderbook, I know for the other exchanges, how you guys set it up is that can have watch ticker return BBO while watch orderbook returns what would be “books” for okx. It would be good if this is Also the case for okx now just to be standardized with the other implementations. (Also helpful for me since I use both BBO and deeper orderbook data together).

**Comment by kroitor** [comment]
> Thanks! Just wondering if set the option here to BBO, would it also impact watch_orderbook, I know for the other exchanges, how you guys set it up is that can have watch ticker return BBO while watch orderbook returns what would be “books” for okx. It would be good if this is Also the case for okx now just to be standardized with the other implementations. (Also helpful for me since I use both BBO and deeper orderbook data together).

Tbh, we don't route L1 orderbooks through watchTicker in the other exchanges, so you might be slightly misinformed. CCXT pro will allow you to choose which orderbook subscription type it is, and will also let you pick whether you want orderbooks or tickers, however, it will not route orderbooks through tickers or vice versa.

The point that I am trying to show above is how to switch the orderbook stream in a way that would be identical to watch_ticker in terms of the relevant data (topmost bidasks). So you can use either approach, and you will also note that watch_orderbook (tick by tick) is updated slightly faster than watch_ticker (regular intervals).

**Comment by pickmone** [comment]
yup, thank you, and very helpful and not a problem. 

No issue for me, as this works too, but I guess just to clarify what I meant to avoid confusion. I think other exchanges don't use the orderbook url for BBO, unlike how OKX decided to do things going forward. For example:

FTX has a separate ticker URL for BBO:
![image](https://user-images.githubusercontent.com/81128701/167110782-63b775ac-e13e-455a-9466-6610f9d0fdf0.png)

Binance's BBO:
![image](https://user-images.githubusercontent.com/81128701/167111023-5a6c975a-5218-4513-8fb9-2227bc63b304.png)

So when using the watch_ticker function for other exchange it returns the BBO, which doesn't impact the URL for orderbook when calling the watch_order_book. 

But yea, just thought to clarify, but all is good now. 

thanks!
