### ISSUE TITLE
A unified address tag for withdrawing XRP, XMR, XLM, etc

### ISSUE THREAD

**Issue by kornrunner** [ccxt/ccxt#1313]
I've got a question about withdrawal API for currencies that require `memo`/`message`/`tag`/`paymentId` or variations for deposit/withdrawal.

Here's a short list of affected currencies (likely there are more):
- AEON
- BTS
- GXS
- NXT
- SBD
- STEEM
- STR
- XEM
- XLM
- XMR
- XRP

As far as I've seen, for fetch/create deposit addres API (where available/implemented) for most of the exchanges aren't returning that value - so, nothing much that we can do about that. Binance is one example where they return the value (rather an exception). Perhaps we can add (map) it to the return array of fetch/create deposit address calls (new key). This should be easy to do, but we'd need to agree upon key name (if accepted).

Other thing that I'm wondering is if we could find a unified way to handle this parameter in withdraw/deposit calls:
Thing is - every exchange that has withdrawals enabled usually accepts this optional param, and currently we'd have to pass it within optional `params` array. However, since the key name differs per exchange, so all clients need to do this mapping on their own - and this something that we could handle on library level IMO.

Adding new parameter is a BC break, I suppose that's something we'd like to avoid... I'm open to any suggestions you may have. Thank you!

**Comment by kroitor** [comment]
Looks like we should add that `message=undefined` parameter even though it would be a BC-break. Most active users would still migrate quickly. So, yes, I totally agree with what you say.

So, the proposal is to change from this:

```
withdraw (currencyCode, amount, address, params = {})
```

To this:

```
withdraw (currencyCode, amount, address, message = undefined, params = {})
```

And I'm all for it! ) Will add the necessary things and will make the announcement )

**Comment by kornrunner** [comment]
Thank you very much!

Here are some of my own findings:
poloniex: `paymentId` for XMR
binance: `addressTag` (for any currency, optional)
hitbtc: `paymentId` IF `payoutIsPaymentId` in currencies call (for given currency)
cryptopia: `PaymentId` (for CryptoNote coins - maybe for others)

Waiting to hear from yobit if they will start returning it in API call (for XEM)

**Comment by kornrunner** [comment]
In XRP world it's called Tag. Other coins have their own names for that (thus memo, message, paymentId). As it differs per currency, I'd put something generic.
 `addressTag` that `binance` is fine, `tag` is also fine by me...

**Comment by kroitor** [comment]
Moved to #1348 ) Thank you!
