### ISSUE TITLE
Unable to call exchange methods with "new CCXT[id]" declaration 

### ISSUE THREAD

**Issue by ydkishore30** [ccxt/ccxt#1314]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:Windows
- Programming Language version:Node Js 
- CCXT version:latest
- Exchange:
- Method:loadmarkets()

I am not able to call exchange methods with below declarations.
```
let id = 'gdax'
let gdax = new ccxt[id]();
gdax.loadmarkets(); //Throwing error as function not found.
```

**Comment by kroitor** [comment]
1. There is no such method as **loadmarkets**, the proper name is `loadMarkets` or `load_markets`. If you want to make any use of this library, you will have to start paying all of your attention to each symbol literally.
2. The method itself is asynchronous, it returns a JS Promise (google for it), so you can't call it like you did in your snippet. The proper code would look like the following:

```JavaScript
let id = 'gdax'
let gdax = new ccxt[id]();
(async () => {
    console.log (await gdax.load_markets()) // does not throw any errors anymore
}) ()
```

Sorry, but your question isn't really related to the library itself, it is mostly about using proper JavaScript syntax. I'm closing this for now, if you don't mind. Hope it answers your question.

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/tree/master/examples

**Comment by ydkishore30** [comment]
Thanks for Quick reply Igor!! :)
