### ISSUE TITLE
Bibox load_markets() mixes DASH and DRK markets

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#13157]
- OS: Linux Mint
- Programming Language version: Python 3.10
- CCXT version: 1.81.77

```
exchange = ccxt.bibox({...})
exchange.load_markets()
print(exchange.market('DASH/USDT'))
```

```
{'id': 'DRK_USDT', 'symbol': 'DASH/USDT', 'base': 'DASH', 'quote': 'USDT', 'baseId': 'DRK', 'quoteId': 'USDT', 'active': None, 'type': 'spot', 'linear': None, 'inverse': None, 'spot': True, 'swap': False, 'future': False, 'option': False, 'margin': False, 'contract': False, 'contractSize': None, 'expiry': None, 'expiryDatetime': None, 'optionType': None, 'strike': None, 'settle': None, 'settleId': None, 'precision': {'amount': 2, 'price': 8}, 'limits': {'leverage': {'min': None, 'max': None}, 'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': 1.0, 'max': None}}, 'info': {'id': '999', 'pair': 'DRK_USDT', 'pair_type': '1', 'area_id': '15', 'is_hide': '0', 'decimal': '8', 'alias': None, 'amount_scale': '2'}, 'percentage': True, 'tierBased': False, 'taker': 0.002, 'maker': 0.001, 'numericId': 999}
```

In the output above, DASH and DRK currency symbols have clearly been mixed up at some point. The same mix up occurs also in the dictionary returned by `fetch_markets` method. DRK/USDT market is also missing and cannot be fetched with `market` method. 

According to https://api.bibox.com/v3/mdata/pairList Bibox has both DASH and DRK currencies, where the latter is probably a small cap coin called Draken. According to exchange.py DASH is a common currency code for DRK. 

My guess is that problem lies in how the result dictionaries are build in `fetch_market` method. In it `safe_currency_code` probably swaps DRK to DASH, causing the issue. 

This feels kind of a dangerous problem, as the wrong 'id' causes wrong markets to be used in many other exchange methods. One can receive an incorrect order book with `fetch_order_book` method, for example. Maybe the problem has some general solution for all the exchanges? Like for example, when the markets are initialized there could be a check that the markets do not contain both the original and the substitute symbols from the CommonCurrencyCodes, and in a rare case when that happens, that substitution would be ignored?

**Comment by pcriadoperez** [comment]
Thanks for opening this @JovianMoon

I found the issue is that we replace DRK to DASH by default, because about 7 years ago Dash rebranded from Darkcoin (DRK) to Dash (DASH), and some exchanges were using the old symbol. I'll open a PR to fix this.

**Comment by JovianMoon** [comment]
@pcriadoperez Thank you for taking a look at the problem!

I was just wondering if there is something that can be done prevent these type of mix ups occurring due to replacement of currency symbols for all currencies in all exchanges? Maybe by having additional check ups while loading the markets by making sure that they do not contain currencies for both the original and the replacement symbols?

**Comment by pcriadoperez** [comment]
It's a good question.

So in general we assign these replacements on an exchange level.
On a global level we only replace:
```
                'XBT': 'BTC',
                'BCC': 'BCH',
                'DRK': 'DASH', (I opened a PR to remove it)
                'BCHABC': 'BCH',
                'BCHSV': 'BSV',
```
I checked the other symbols, and no significant cryptos seem to be using them and they are common replacements so I think we are safe for now. However of course it could always happen in the future that someone adopts one of these symbols.

I think the chance is very small, but if we really wanted to we could maybe add that check in `test.fetchMarkets`. @kroitor thoughts?
