### ISSUE TITLE
How to return sequence info from fetchOrderBook()

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#13155]
OS: Windows Server 2019 Datacenter
Programming Language version: Node.js 15.3.0
CCXT version: 1.49.98
Exchange: Kucoin
Method: exchange.fetchOrderBook()

Hello!

I wonder for the `fetchOrderBook()` when looking at the documentation for kucoin for example a `"sequence": "3262786978"` information is also returned for the Level2 orderbook:
https://docs.kucoin.com/#get-full-order-book-aggregated

However I can't find that field in this response. Is it possible to return this somehow?

Thank you!

```
    const Exchange = ccxt["kucoin"];
    var exchange = new Exchange({ enableRateLimit: true, 'timeout': 10000 });

    const orderbook = await exchange.fetchOrderBook("XDC/USDT", 20);
    console.log(orderbook);
```
Response:
```
{
  symbol: 'XDC/USDT',
  bids: [
    [ 0.06318, 20964.9213 ],
    [ 0.06317, 5600 ],
    [ 0.06316, 22902.7614 ],
    [ 0.06315, 22904.4161 ],
    [ 0.06313, 7633.7741 ],
    [ 0.06312, 11447.3595 ],
    [ 0.0631, 7352.9147 ],
    [ 0.06304, 593118.9619 ],
    [ 0.06303, 2492.693 ],
    [ 0.063, 14645.3862 ],
    [ 0.06298, 1539.0865 ],
    [ 0.06297, 6341 ],
    [ 0.06294, 81.0995 ],
    [ 0.06293, 3956.656 ],
    [ 0.06292, 84.1874 ],
    [ 0.06291, 980.8227 ],
    [ 0.0629, 100030.5385 ],
    [ 0.06289, 76.7855 ],
    [ 0.06287, 83.1782 ],
    [ 0.06286, 143.4252 ]
  ],
  asks: [
    [ 0.0632, 71671.80088106 ],
    [ 0.06326, 600340.4399 ],
    [ 0.06327, 777.2199 ],
    [ 0.06328, 770.1961 ],
    [ 0.06329, 32.6034 ],
    [ 0.0633, 32099.139 ],
    [ 0.06332, 69.7983 ],
    [ 0.06333, 278.2634 ],
    [ 0.06334, 29.2291 ],
    [ 0.06335, 49.2519 ],
    [ 0.06336, 103.3659 ],
    [ 0.06337, 222.2938 ],
    [ 0.06339, 5809.6795 ],
    [ 0.0634, 1304.7829 ],
    [ 0.06341, 3984.5605 ],
    [ 0.06343, 101222.6758 ],
    [ 0.06344, 102.5243 ],
    [ 0.06346, 159.7468 ],
    [ 0.06347, 11321.5707 ],
    [ 0.06349, 127.9759 ]
  ],
  timestamp: 1651930314204,
  datetime: '2022-05-07T13:31:54.204Z',
  nonce: 1620483594320
}
```

**Comment by samgermain** [comment]
@kroitor is there a reason why we don't attach `info` to the `fetchOrderBook` response?

**Comment by kroitor** [comment]
> However I can't find that field in this response. Is it possible to return this somehow?

@jackpotcityco the `sequence` is parsed as the `nonce` number when returned from fetchOrderBook.

> @kroitor is there a reason why we don't attach `info` to the `fetchOrderBook` response?

@samgermain we used to store tick-by-tick orderbook snapshots before, and having the `info` would cause it to just return a lot of duplicate info... We could probably return the info for orderbooks depending on an option, otherwise the user will have to drop the info to store tick-by-tick snapshots.

**Comment by kroitor** [comment]
@jackpotcityco closing it for now, let us know if `orderbook['nonce']` does not help.

**Comment by jackpotcityco** [comment]
> > However I can't find that field in this response. Is it possible to return this somehow?
> 
> @jackpotcityco the `sequence` is parsed as the `nonce` number when returned from fetchOrderBook.
> 
> > @kroitor is there a reason why we don't attach `info` to the `fetchOrderBook` response?
> 
> @samgermain this is due to the most frequent use-cases for orderbooks – we used to store tick-by-tick orderbook snapshots before, and having the `info` would cause it to just return and store a lot of duplicate info... We could probably return the info for orderbooks depending on an option, otherwise the user will have to drop the info to store tick-by-tick snapshots/deltas.

Thank you, I think the "nonce" then could work. I am trying out that then.
