### ISSUE TITLE
binance AuthenticationError

### ISSUE THREAD

**Issue by uioiuioi** [ccxt/ccxt#13162]
- OS: mac
- Programming Language version: python
- CCXT version: latest

```
from pprint import pprint
import ccxt

API_KEY = "***"
SECRET = "****"

class BinanceApi:
    def __init__(self):
        self.binance_api = ccxt.binance(
            {
                "apiKey": API_KEY,
                "secret": SECRET,
                "options": {"defaultType": "future"},
                "enableRateLimit": True,
            }
        )

    def get_position(self, symbol):
         self.binance_api.fapiPrivateGetPositionRisk()

```
When I run get_position especially fapiPrivateGetPositionRisk(), I got the error shown below. When I run different functions such as load_markets(), it succeeded. I'm pretty sure that the API is correct and I checked the options of "Enable Margin Loan, Repay & Transfer" in binance website.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 656, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fapi.binance.com/fapi/v1/leverageBracket?timestamp=1652001719852&recvWindow=5000&signature=a245519531ad724b13876b70b00e616de7ab9bdfd5f5f2e96b09c5eb158ea759

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/opt/start.py", line 77, in <module>
    position = binance.get_position(symbol)
  File "/root/opt/bi_api.py", line 21, in get_position
    balance = self.binance_api.fetchPositionsRisk()
  File "/usr/local/lib/python3.10/site-packages/ccxt/binance.py", line 4733, in fetch_positions_risk
    self.load_leverage_brackets()
  File "/usr/local/lib/python3.10/site-packages/ccxt/binance.py", line 4592, in load_leverage_brackets
    response = getattr(self, method)(query)
  File "/usr/local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 496, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.10/site-packages/ccxt/binance.py", line 5064, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/usr/local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 543, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 672, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/usr/local/lib/python3.10/site-packages/ccxt/binance.py", line 5042, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/usr/local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 561, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action, request ip: "my IP address"}```

**Comment by DoctorSlimm** [comment]
@uioiuioi do any of the other binance private endpoints work for you? such as `fetchBalance ()` or `createOrder ()` ?

**Comment by uioiuioi** [comment]
> @uioiuioi do any of the other binance private endpoints work for you? such as `fetchBalance ()` or `createOrder ()` ?

No, it doesn't work such functions.

**Comment by kroitor** [comment]
@uioiuioi do you use the testnet keys? Does your API key look correct in verbose mode? 

- https://docs.ccxt.com/en/latest/manual.html#troubleshooting

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
markets = exchange.load_markets()
exchange.verbose = True
balance = exchange.fetch_balance()
pprint(balance)
```

What do you see?

**Comment by uioiuioi** [comment]
> 

I don't see any error in executing those functions.
I can see the asset and the balance in each currency.

**Comment by kroitor** [comment]
@uioiuioi ok, now please try this snippet:

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binanceusdm({  # <<<<<<<<<<<<<<< changed for binanceusdm here
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
markets = exchange.load_markets()
exchange.verbose = True
response = exchange.fapiPrivateGetPositionRisk()  # <<<<<<<<<<<<<<< changed for fapiPrivateGetPositionRisk here
pprint(response)
```

**Comment by uioiuioi** [comment]
> @uioiuioi ok, now please try this snippet:
> 
> ```python
> import ccxt
> from pprint import pprint
> print('CCXT Version:', ccxt.__version__)
> exchange = ccxt.binanceusdm({  # <<<<<<<<<<<<<<< changed for binanceusdm here
>     'apiKey': 'YOUR_API_KEY',
>     'secret': 'YOUR_SECRET',
> })
> markets = exchange.load_markets()
> exchange.verbose = True
> response = exchange.fapiPrivateGetPositionRisk()  # <<<<<<<<<<<<<<< changed for fapiPrivateGetPositionRisk here
> pprint(response)
> ```

then I got an error like below

`  File "/usr/local/lib/python3.10/site-packages/ccxt/binance.py", line 5033, in handle_errors
    raise DDoSProtection(self.id + ' temporary banned: ' + body)
ccxt.base.errors.DDoSProtection: binance temporary banned: {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action, request ip: 150.249.51.239"}`

**Comment by kroitor** [comment]
@uioiuioi have you checked the API key permissions on the website ? Does it have the necessary futures-trading permissions ?

**Comment by uioiuioi** [comment]
@kroitor 
Thank you so much!!!!!!!!!!
I was able to solve this problem. The problem was I created the API before opening the Binance future account, so I wasn't able to use the futures-trading permission.
Appreciate it!!!!!!

**Comment by kroitor** [comment]
@uioiuioi yep, it's a known common problem, recreating the API keypair usually helps. Thanks for the feedback!
