### ISSUE TITLE
phemex charts vs ccxt fetch ohlcv does not match at all 1minute chart

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#13184]
how come the phemex 1m chart on interface does not match the dataframe from fetch_ohlcv 1 minute chart??

**Comment by kroitor** [comment]
@adamrg73 hi! Please, elaborate a bit, ideally, post your code and your verbose output + the web interface screenshots:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by ttodua** [comment]
I've been investigating this issue and seems PHEMEX ohlcv is not a regular API endpoint, but ccxt uses emulated WEB-UI data (which is not meant to be a real API). 
and after testing thoroughly I can confirm that 1min data is missing the last bar always. 
if that's the only issue, there is nothing we can do atm, as their chart data uses websockets to get the latest realtime bar, and with CCXT rest api it cant be obtained.
if that's you mean, then i will close the issue. if you have other issues aside from this, please reopen the topic and provide more info as @kroitor already replied.
