### ISSUE TITLE
bitbay withdraw don't throw Error

### ISSUE THREAD

**Issue by pmizel** [ccxt/ccxt#1319]
Hi Igor,

i think it would be better to throw an Exeption when Error-Code is in response.
what is your opinion?

Error codes and code Description
400 At least one parameter wasn't set
401 Invalid order type
402 No orders with specified currencies
403 Invalid payment currency name
404 Error. Wrong transaction type
405 Order with this id doesn't exist
406 No enough money or crypto
408 Invalid currency name
501 Invalid public key
502 Invalid sign
503 Invalid moment parameter. Request time doesn't match current server time
504 Invalid method
505 Key has no permission for this action
506 Account locked. Please contact with customer service
509 The BIC/SWIFT is required for this currency
510 Invalid market name

**Comment by kroitor** [comment]
Hello )

Yes, you're absolutely right, we are working on adding proper error handlers, check out handleErrors in Liqui, for example, here: https://github.com/ccxt/ccxt/blob/master/js/liqui.js#L620

Because this is a work is progress, it may still be missing in some exchanges. Would be great if you could contribute to it as well.

(p.s. I'm merging your pr soon, sorry for the delay)

**Comment by pmizel** [comment]
handleErrors (httpCode, reason, url, method, headers, body) {
        if ((typeof body !== 'string') || (body.length < 2))
            return; // fallback to default error handler
        if ((body[0] === '{') || (body[0] === '[')) {
            let response = JSON.parse (body);
            if ('code' in response) {
                //
                // 1 - bitbay returns the integer 'success' key from their private API
                //
                //      {code: 502, message: "Invalid sign"}
                //
                //      400 At least one parameter wasn't set
                //      401 Invalid order type
                //      402 No orders with specified currencies
                //      403 Invalid payment currency name
                //      404 Error. Wrong transaction type
                //      405 Order with this id doesn't exist
                //      406 No enough money or crypto
                //      408 Invalid currency name
                //      501 Invalid public key
                //      502 Invalid sign
                //      503 Invalid moment parameter. Request time doesn't match current server time
                //      504 Invalid method
                //      505 Key has no permission for this action
                //      506 Account locked. Please contact with customer service
                //      509 The BIC/SWIFT is required for this currency
                //      510 Invalid market name
                //
                let code = this.safeValue (response, 'code', 200);
                if (typeof code === 'number' && code >= 400) {
                    const code = response['code'];
                    //const message = response['message'];
                    const feedback = this.id + ' ' + this.json (response);

                    if (code === 501) {
                        throw new AuthenticationError (feedback);
                    } else if (code >= 400 && code <= 408) { // errorCode 0
                        throw new InvalidOrder (feedback);
                    } else {
                        throw new ExchangeError (this.id + ' unknown "error" value: ' + this.json (response));
                    }
                }
            }
        }
    }

**Comment by kroitor** [comment]
Looks very good, except for these two minor things:
- `typeof code === 'number'` is not portable, because the 'number' string is JS-only, so we can only compare types to undefined and strings (those are portable)
- the empty line inside that method will break the transpiler as well

**Comment by pmizel** [comment]
i update this snippet in comment...do you need a pr?

with every pr i learn more and more about your transpiler :-(

**Comment by kroitor** [comment]
I've uploaded it already in the repo ) Reworked it a little, so now it should handle errors as expected. Thx )
