### ISSUE TITLE
Bibox changed hostname

### ISSUE THREAD

**Issue by MrWeb** [ccxt/ccxt#13205]
I had trouble connecting to Bibox despite having API key and secret in place, I spoke with support and they said to change bibox.com to bibox.tech as a hostname. I did locally in the package and it now works.

File: `vendor/ccxt/ccxt/php/bibox.php`
Line #22 
From `'hostname' => 'bibox.com'` to `'hostname' => 'bibox.tech',`

**Comment by sc0Vu** [comment]
Looks like they have two exchange (https://www.bibox.tech / https://www.bibox.com)? And the api endpoint / ip are different.

**Comment by sc0Vu** [comment]
You can set hostname when initialize bibox:
```PHP
new \ccxt\bibox([
    'hostname' => 'bibox.tech'
])
```
