### ISSUE TITLE
Failing using watch_order for Kucoin spot

### ISSUE THREAD

**Issue by KevinBaudin** [ccxt/ccxt#13203]
- OS: Ubuntu 20.04
- Programming Language version: 3.8.10
- CCXT version: 1.82.14

```
import asyncio
import ccxtpro  # ccxtpro.__version__ == '1.1.21'
import ccxt  # ccxt.__version__ == '1.82.14'

asyncio_loop = asyncio.get_event_loop()

keys = {
    "apiKey": "XXX", 
    "secret": "XXX", 
    "password": "XXX"}

exchange_params = {
            'asyncio_loop': asyncio_loop,
            'enableRateLimit': True,
            'apiKey': keys['apiKey'],
            'secret': keys['secret'],
            'password': keys['password'],
            'options': {
                'defaultType': 'spot',
            },
        }

exchange_stream = getattr(ccxtpro, 'kucoin')(exchange_params)
exchange_stream.verbose = True

i = 1
while i < 10:
    # kucoin watchOrderBook 'limit' argument must be None, 20 or 100
    ob = await exchange_stream.watch_order_book('GLMR/USDT', limit=None) 
    print(ob)
    i += 1
```
[output_issue_kucoin.txt](https://github.com/ccxt/ccxt/files/8676287/output_issue_kucoin.txt)

I can't find a way to use watch_order_book for any token on Kucoin for now, am I doing something wrong? 
Thanks a lot in advance

(Edit: output link was broken)

**Comment by carlosmiei** [comment]
Hello @KevinBaudin 

First and foremost, in the output file, you leaked some parts of your API keys, so I'd recommend revoking them immediately just in case.

I've tested and seems to be working. If you're using partial keys or default values (example API_KEY=XXX) that might be causing the issue. Just for testing purposes can you try removing all the keys and running it again? after all this is a public endpoint.

Example
```Python
import asyncio
import ccxtpro  # ccxtpro.__version__ == '1.1.21'
import ccxt  # ccxt.__version__ == '1.82.14'

asyncio_loop = asyncio.get_event_loop()

exchange_params = {
            'asyncio_loop': asyncio_loop,
            'enableRateLimit': True,
            'options': {
                'defaultType': 'spot',
            },
        }

exchange_stream = getattr(ccxtpro, 'kucoin')(exchange_params)
exchange_stream.verbose = True

async def main():
    i = 1
    while i < 10:
        # kucoin watchOrderBook 'limit' argument must be None, 20 or 100
        ob = await exchange_stream.watch_order_book('GLMR/USDT', limit=None) 
        print(ob)
        i += 1

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

**Comment by KevinBaudin** [comment]
Hi and thank you

(API_KEY=XXX was edited by me to hide my key, but was not used at all.)
I removed the line completely in case it had some extra infos I did not want to share, thanks for the warning.

I did try your fix, by using no api_key at all, and it worked. Also, I retried my code, and it worked too.
So, I guess that's not from ccxtpro, but from Kucoin, and I'll have to handle this.

**Comment by carlosmiei** [comment]
@KevinBaudin Feel free to reopen the issue if anything! Thanks
