### ISSUE TITLE
[Binance] Does the fetchOrder endpoint not convert trades?

### ISSUE THREAD

**Issue by MalteToenjes** [ccxt/ccxt#13202]
- OS: -
- Programming Language version: Javascipt
- CCXT version: newest

I noticed that the private endpoint fetchOrder only returns the [spot trades](https://www.binance.com/en/trade/BTC_USDT?theme=dark&type=spot) for Binance. But if the Binance account was used to make [convert trades](https://www.binance.com/en/convert), this data is not fetched. Is there another endpoint for this or is this not possible with the ccxt lib?

**Comment by kroitor** [comment]
Yes, you can do that via the implicit API: https://docs.ccxt.com/en/latest/manual.html#implicit-api

```JavaScript
const ccxt = require('ccxt')

async function main () {
    const exchange = new ccxt.binance({
    })
}
```

**Comment by kroitor** [comment]
**Updated the sample snippet above.**
