### ISSUE TITLE
kucoin wrong order id on fetchClosedOrders

### ISSUE THREAD

**Issue by sirpy** [ccxt/ccxt#1321]
on v1.10.730 
exchange: kucoin
method: fetchClosedOrders

the id of the order returned is incorrect.
the raw result had two fields (info field) oid and orderOid, the id returned is oid but the original issued id is actually orderOid, meaning it is the id returned when you issue createOrder

**Comment by kroitor** [comment]
Hi! Can you please post verbose output? (set .verbose = true) on the exchange before calling the fetchClosedOrders, like described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
Thx!
