### ISSUE TITLE
MIN_NOTIONAL error

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#13214]
Exploring ccxt and caught such error: ccxt.base.errors.InvalidOrder: binance {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}
Why this is happening and how to fix it?

CODE
```
import ccxt
import config

exchange = ccxt.binance({
    "apiKey" : config.BINANCE_API_KEY,
    "secret" : config.BINANCE_SECRET_KEY
})

order = exchange.create_market_buy_order("BSW/USDT", 10)

```

**Comment by kroitor** [comment]
That just means your total cost of the order is too low:

- https://docs.ccxt.com/en/latest/manual.html#precision-and-limits

Duplicate:

- https://github.com/ccxt/ccxt/search?q=MIN_NOTIONAL&type=issues
- https://github.com/ccxt/ccxt/issues/9324
- https://github.com/ccxt/ccxt/issues/8408
- https://github.com/ccxt/ccxt/issues/6420
