### ISSUE TITLE
bleutrade.create_limit_buy_order raises strange exception 

### ISSUE THREAD

**Issue by ironexmaiden** [ccxt/ccxt#1323]
- OS:Linux
- Programming Language version:Python
- CCXT version:1.10.586
- Exchange:bleutrade
- Method:create_limit_buy_order

I call create_limit_buy_order('VRC/BTC', 26.17, 0.01244)

and it raise an exception 

`list indices must be integers or slices, not str`

**Comment by kroitor** [comment]
Hi! Can you please post verbose output? (set .verbose = true) on the exchange before calling the fetchClosedOrders, like described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
Thx!

**Comment by ironexmaiden** [comment]
Bleutrade verbost


Trying to sellVRC for BTC
https://bleutrade.com/api/v2/market/buylimit?market=VRC_BTC&apikey=830252553cdc1fb5fc01bf688075d163&nonce=1516144818&quantity=26.17012473&rate=0.00010000 GET https://bleutrade.com/api/v2/market/buylimit?market=VRC_BTC&apikey=830252553cdc1fb5fc01bf688075d163&nonce=1516144818&quantity=26.17012473&rate=0.00010000 
Request: {'Accept-Encoding': 'gzip, deflate', 'apisign': '0cc5e55ba6dedfc2297c320d6501a41e1ff963160fefdaf94ec4366003949f35dce13476046d37435d4bb3ee0afede880d213d94b7008289f548ce54ad6ab54d', 'User-Agent': 'python-requests/2.14.2'} None
GET https://bleutrade.com/api/v2/market/buylimit?market=VRC_BTC&apikey=830252553cdc1fb5fc01bf688075d163&nonce=1516144818&quantity=26.17012473&rate=0.00010000 
Response: {'Accept-Encoding': 'gzip, deflate', 'apisign': '0cc5e55ba6dedfc2297c320d6501a41e1ff963160fefdaf94ec4366003949f35dce13476046d37435d4bb3ee0afede880d213d94b7008289f548ce54ad6ab54d', 'User-Agent': 'python-requests/2.14.2'} {"success":"false","message":"Insufficient funds!","result":[]}

**Comment by kroitor** [comment]
Does that last message tell you anything? Also, why did you cut the output? It doesn't contain the exception info itself now... %)

**Comment by ironexmaiden** [comment]
It tell me that I do not have enough funds but ok firstly I have the funds and secondly the exception which must raised is insuffisient fund exception like create_limit_sell_order do. I have the only doubt if I call the function properly

I have 26.17 VRC and I want to buy BTC with these which way is the proper?

**Comment by kroitor** [comment]
@ironexmaiden the exception you got is indeed not a correct one, you are right, and we will fix it soon, however, when we fix it, you will have a proper InsufficientFunds error, but you should still have enough fund to make your order, anyway.

**Comment by ironexmaiden** [comment]
That's why I haven't still understand I have the proper funds. And how much funds I set on the buy order I have just retrieve through fetch_balance function.

**Comment by kroitor** [comment]
@ironexmaiden you have to have funds + fee on your balance.

**Comment by ironexmaiden** [comment]
Exactly this is my fault! Sorry for the inconvience I have thought that the fee is being cretided on the transaction...

**Comment by kroitor** [comment]
I hope you don't mind if I close this for now? Feel free to reopen it if needed, or just ask questions, if any. Thx!

**Comment by ironexmaiden** [comment]
close it thank you
