### ISSUE TITLE
Binance 1W candle missing

### ISSUE THREAD

**Issue by SudheendraSoftionik** [ccxt/ccxt#13230]
Hi guys,

In binance for 1W timeframe we can get only 200 - 230 candles why? But for other timeframe we can get 1000 candles. Why 1W timeframe candles are missing.? Is that missing candles data available in the ccxt pro?

**Comment by kroitor** [comment]
@SudheendraSoftionik which symbol is it? 200-230 weekly candles is a few years of history. Not all coins and pairs existed back then. Some coins and pairs that were listed this year will have less than 52 candle-weeks of history, obviously.
