### ISSUE TITLE
I am getting this error most of the time how to fix it 

### ISSUE THREAD

**Issue by vensilver** [ccxt/ccxt#13233]
('ftx {"success":false,"error":"Cannot send more than 1500 requests per minute"}',)

i am getting this error how do i fix it

**Comment by sc0Vu** [comment]
May I ask which api did you call?

**Comment by kroitor** [comment]
@vensilver please, follow these guides literally to a word, paste your versions, your code and your verbose output:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by vensilver** [comment]
> May I ask which api did you call?

Authentication: CCXT Version: 1.72.79

**Comment by kroitor** [comment]
@vensilver please, upgrade your version to the most recent number 1.82.34+ – do you have this issue with the most recent version of the library? Also, please, follow the guidelines and paste your code: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by vensilver** [comment]
> @vensilver please, upgrade your version to the most recent number 1.82.34+ 

ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.

What is this ?

**Comment by vensilver** [comment]
same error message even after updating the ccxt to the current version.

Got an error RateLimitExceeded ('ftx {"success":false,"error":"Cannot send more than 1500 requests per minute"}',)

**Comment by kroitor** [comment]
@vensilver as far as i understand, you are relaunching your script over and over, and it prints out that message?

**Comment by kroitor** [comment]
@vensilver can you paste your code?

**Comment by vensilver** [comment]
> @vensilver can you paste your code?

https://colab.research.google.com/drive/1ZhXe0_chp8vvo9ylujQyxgsWMG76PT2P?usp=sharing

check the link

**Comment by kroitor** [comment]
@vensilver it is working fine if you launch it locally, not via the google colab website – it may be related to the fact that the google colab ip address space is used by too many users and FTX rate-limits those requests by IP. 

Do you have issues running this script on your local machine? ↓

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)  # assuming you have the most recent version of ccxt
exchange = ccxt.ftx({
    'apiKey': 'YOUR_API_KEY',  # edit for your keys
    'secret': 'YOUR_SECRET',
    'headers': {'FTX-SUBACCOUNT': 'YOUR_SUBACCOUNT'}
})
markets = exchange.load_markets()
balance = exchange.fetch_balance()
pprint(balance)
```

**Comment by vensilver** [comment]
> 

I am running the code in azure vm

**Comment by kroitor** [comment]
@vensilver make sure you don't violate this rate-limiting rule (this may be caused by not reusing the exchange instance and recreating it over and over in short time) https://docs.ccxt.com/en/latest/manual.html#notes-on-rate-limiter

**Comment by vensilver** [comment]
can multiple bots run with the same code on different pairs cause this?

are all running in the same vm.

**Comment by kroitor** [comment]
Yes, cause they're not syncrhonized between each other in terms of rate limits. The exchanges will rate limit your requests by IP, and each bot works independently of another and does not know about the other bots.

**Comment by vensilver** [comment]
> Yes, cause they're not synchronized between each other in terms of rate limits. The exchanges will rate limit your requests by IP, and each bot works independently of another and does not know about the other bots.

do you have any idea how can i solve this

**Comment by kroitor** [comment]
@vensilver either split your scripts across multiple source IP addresses (this will require some configuration on your provider's website and on the systems themselves), or reuse the same exchange instance across your execution loops. It depends whether each bot has it's own API credentials or they all use the same credentials.

**Comment by vensilver** [comment]
> @vensilver either split your scripts across multiple source IP addresses (this will require some configuration on your provider's website and on the systems themselves), or reuse the same exchange instance across your execution loops. It depends whether each bot has it's own API credentials or they all use the same credentials.

they all use different credentials all are running in azure vm using [tmux ](https://www.howtogeek.com/671422/how-to-use-tmux-on-linux-and-why-its-better-than-screen/)to run in  different screens

**Comment by kroitor** [comment]
@vensilver the easiest way to solve this is to add an IP address per each running instance, and then configure each instance's session with its own IP:

- https://github.com/ccxt/ccxt/blob/master/examples/py/source-ip-address.py

```Python
# -*- coding: utf-8 -*-

import requests
from pprint import pprint
import ccxt


# configure the source IP address
ip_address = '192.168.1.2'  # YOUR EXTERNAL IP ADDRESS HERE
session = requests.Session()
for prefix in ('http://', 'https://'):
    session.get_adapter(prefix).init_poolmanager(
        # those are default values from HTTPAdapter's constructor
        connections=requests.adapters.DEFAULT_POOLSIZE,
        maxsize=requests.adapters.DEFAULT_POOLSIZE,
        # This should be a tuple of (address, port). Port 0 means auto-selection.
        source_address=(ip_address, 0),
    )


exchange = ccxt.ftx({
    'session': session,
    # ... other config properties here if necessary ...
})


markets = exchange.load_markets()
exchange.verbose = True

ticker = exchange.fetch_ticker('BTC/USD')
pprint(ticker)

```

**Comment by kroitor** [comment]
https://www.google.com/search?q=azure+multiple+ip+addresses

**Comment by vensilver** [comment]
In azure, there are private IP and public IP 
which must I use here

# configure the source IP address
ip_address = '192.168.1.2'  # YOUR EXTERNAL IP ADDRESS HERE

for ping I use private IP

 ping -I 10.0.0.5 outlook.com but ping for public IP ping dos not work.
