### ISSUE TITLE
ccxt bybit balance

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#13239]
ccxt doesn't show actual bybit SPOT balance, instead it show Futures balance. Why does it happen?

bybit = ccxt.bybit({
    "apiKey": config.BYBIT_API_KEY,
    "secret": config.BYBIT_SECRET_KEY,
    "options": {'defaultType': 'spot' }
})
print(bybit.fetch_balance()["total"]["USDT"])

**Comment by carlosmiei** [comment]
Hello @KindSpidey 
Very soon we will merge an update that allows fetching the balance of every market type (spot, swaps, futures and usdc)

**Comment by KindSpidey** [comment]
But how i can fix it now? I use type stop, as you can see, but bybit make orders on futures and shows futures balance. Why so?

**Comment by carlosmiei** [comment]
@KindSpidey if you can't wait you can always use the implicit API to get it

Example:
```Python
bybit = ccxt.bybit({
"apiKey": config.BYBIT_API_KEY,
"secret": config.BYBIT_SECRET_KEY,
"options": {'defaultType': 'spot' }
})
print(bybit.privateGetSpotV1Account())
```

**Comment by KindSpidey** [comment]
Thanks. How can i make orders with this construction?

**Comment by kroitor** [comment]
@KindSpidey 

> How can i make orders with this construction?

I would highly recommend reading the Manual from top to bottom, cause it has the answers to your questions and it will really save your time:

- https://docs.ccxt.com/
- https://docs.ccxt.com/en/latest/manual.html#implicit-api

Hope it helps.

**Comment by carlosmiei** [comment]
@KindSpidey We updated Bybit's `fetchBalance` so you can use it now to fetch spot balances.

**Comment by flieks** [comment]
it seems to show the spot balances by default now. How can i get the futures balance with fetchBalance() now ?

**Comment by carlosmiei** [comment]
@flieks You just need to change the default market type.

Example:

```Python
bybit = ccxt.bybit({
"apiKey": BYBIT_API_KEY,
"secret": BYBIT_SECRET_KEY,
"options": {'defaultType': 'future' } # <------ future or swap here
})
print(bybit.fetch_balance())

**Comment by carlosmiei** [comment]
@flieks You just need to change the default market type.

Example:

```Python
bybit = ccxt.bybit({
"apiKey": BYBIT_API_KEY,
"secret": BYBIT_SECRET_KEY,
"options": {'defaultType': 'future' } # <------ future or swap here
})
print(bybit.fetch_balance())

**Comment by wrone** [comment]
Hey @carlosmiei, I see that sport should be default but it's not default for me - I was able to fetch the right balance only after specifying the type
