### ISSUE TITLE
How to set leverage on bybit?

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#13241]
bybit = ccxt.bybit({
    "apiKey": config.BYBIT_API_KEY,
    "secret": config.BYBIT_SECRET_KEY,
    "options": {'defaultType': 'future' }
})
bybit.set_leverage(
    symbol="GMTUSDT",
    buy_leverage=10,
    sell_leverage=10
))

This shows error TypeError: bybit.set_leverage() got an unexpected keyword argument 'buy_leverage'

**Comment by KindSpidey** [comment]
Solved! Need to use this: bybit.set_leverage(10, "GMTUSDT", {"buy_leverage": 10,"sell_leverage":10}))

**Comment by carlosmiei** [comment]
@KindSpidey Nice, I'll close the issue then, feel free to reopen if needed!
