### ISSUE TITLE
Bitfinex cancel_order returning Bad Request

### ISSUE THREAD

**Issue by drewUCL** [ccxt/ccxt#1324]
I am trying to cancel a margin order on bitfinex but it doesnt work. 

I am going short on margin which works fine. I then want to exit the trade by canceling the order (would be better to claim though). This does not work - the only way I seem to be able to get the order to reverse (i.e. exit the trade) is by executing a margin order of the same quantity in the opposite direction (e.g. a buy order in this case). 

**CODE**
```
# setup
symbol = 'IOTA/USD'
trade_amount = 6

# short order on margin
bitfinex.create_market_sell_order(symbol, trade_amount, {'type': 'market'})

# get trade details
newest_trade = bitfinex.fetch_my_trades('IOTA/USD')[0] 
trade_id = newest_trade['order']

# need to claim the order into our account
print(bitfinex.fetchOrder(trade_id)) # works - so it does exist
print(bitfinex.cancelOrder(trade_id)) # doesnt seem to work

# only way I can find to reverse is to do the following (???)
bitfinex.create_market_buy_order (symbol , trade_amount , {'type': 'market'} )
```

**ERROR**

Traceback (most recent call last):
  File "C:\Users\drewm\Anaconda2\envs\tensorflow\lib\site-packages\ccxt\base\exchange.py", line 350, in fetch
    response.raise_for_status()
  File "C:\Users\drewm\Anaconda2\envs\tensorflow\lib\site-packages\requests\models.py", line 929, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.bitfinex.com/v1/order/cancel

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bitfinex_margin_trade.py", line 34, in <module>
    print(bitfinex.cancel_order(ORDER_ID))
  File "C:\Users\drewm\Anaconda2\envs\tensorflow\lib\site-packages\ccxt\bitfinex.py", line 427, in cancel_order
    return self.privatePostOrderCancel({'order_id': int(id)})
  File "C:\Users\drewm\Anaconda2\envs\tensorflow\lib\site-packages\ccxt\bitfinex.py", line 655, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\drewm\Anaconda2\envs\tensorflow\lib\site-packages\ccxt\base\exchange.py", line 297, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\drewm\Anaconda2\envs\tensorflow\lib\site-packages\ccxt\base\exchange.py", line 362, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, None, self.last_http_response)
  File "C:\Users\drewm\Anaconda2\envs\tensorflow\lib\site-packages\ccxt\bitfinex.py", line 642, in handle_errors
    raise OrderNotFound(error)
ccxt.base.errors.OrderNotFound: bitfinex Order could not be cancelled.

**SOLUTION**
I was wondering if this is a known issue or if there is a fix to this? I want to be able to claim/cancel the margin position. With the current method it seems if cancel_order works that would be great. Note that I put ORDER_ID in place of the actual ID in this example.

- OS: Windows 10
- Programming Language version: Python
- CCXT version: 1.10.727
- Exchange: Bitfinex
- Method: cancel_order( . )

**Comment by kroitor** [comment]
You are canceling a trade, not an order. An order consists of multiple trades. The difference is described here: https://github.com/ccxt/ccxt/wiki

Try this:

```Python
# setup
symbol = 'IOTA/USD'
trade_amount = 6

# short order on margin
order = bitfinex.create_market_sell_order(symbol, trade_amount, {'type': 'market'})  #  ← here
order_id = order['id']  # ←-------------------------------------------------------------- here

# need to claim the order into our account
print(bitfinex.fetchOrder(order_id)) # ←------------------------------------------------- here
print(bitfinex.cancelOrder(order_id)) # ←------------------------------------------------ here
```

Let us know if it helps you or not.
