### ISSUE TITLE
How to make market buy/sell orders and get balance on SPOT Bybit?

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#13244]
I found that bybit make orders on Futures market (and showing Futures balance as well) when i use common commands such as fetchbalance and createmarketbuyorder. 

Can you please help me with examples of code, how to make SPOT market orders? Today one man helped me with getting balance: I need to write bybit_spot.privateGetSpotV1Account())), but I still dont know hot to get exact my balance number

**Comment by KindSpidey** [comment]
Solved getting balance.
`bybit_spot.privateGetSpotV1Account()["result"]["balances"][0]["total"]`
But still needs help with making orders

**Comment by carlosmiei** [comment]
Hello again @KindSpidey 

First, please avoid creating duplicated issues.

Regarding the implicit API usage please check that out: https://docs.ccxt.com/en/latest/manual.html#implicit-api-methods

For creating orders using the implicit API you need to manually construct the request following Bybit's API specification which might be very laborious. We will update all order-related methods very soon so that every market available at Bybit (spot, futures,swaps, usdc) is also available through our unified methods. If you're not very familiar with API integrations I would suggest waiting a bit until the update is deployed. I'll let you know as soon as we merge it.

**Comment by KindSpidey** [comment]
I got it, and I've constructed such request, but it doesnt work. Can you help with it?

My code is `bybit_spot.private_post_spot_v1_order("GMTUSDT", amount, "Buy", "MARKET")`
Compare it to https://bybit-exchange.github.io/docs/spot/#t-placeactive and i cant understand what i am doing wrong

**Comment by carlosmiei** [comment]
@KindSpidey  in this case you would need to do something like this:

```Python

exchange = ccxt.bybit({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

request = {
    'symbol': 'GMTUSDT',
    'qty': 10, # amount in USDT for market orders and in the base quote for the others
    'type': 'MARKET',# or LIMIT OR LIMIT_MAKER
    'timeInForce': 'GTC', # FOK, IOC
    'side': 'Buy', # or Sell
    #'price': 100 <- use only for limit orders
}

order = exchange.privatePostSpotV1Order(request)
print(order)
```

**Comment by KindSpidey** [comment]
```
bybit_spot = ccxt.bybit({
    "apiKey": config.BYBIT_API_KEY,
    "secret": config.BYBIT_SECRET_KEY,
})
balance = float(bybit_spot.private_get_spot_v1_account()["result"]["balances"][0]["total"])
price = float((next((x for x in bybit_spot.public_get_spot_quote_v1_ticker_price()["result"] if x["symbol"] == "GMTUSDT"), None)["price"]))
amount = float(balance/price)
request = {
    'symbol': 'GMTUSDT',
    'qty': amount, # amount in USDT for market orders and in the base quote for the others
    'type': 'MARKET',# or LIMIT OR LIMIT_MAKER
    'timeInForce': 'GTC', # FOK, IOC
    'side': 'Buy', # or Sell
    #'price': 100 <- use only for limit orders
}
```
Used it, but getting ccxt.base.errors.ExchangeError: bybit {"ret_code":-1004,"ret_msg":"Missing required parameter \u0027symbol\u0027","ext_code":null,"ext_info":null,"result":null}

**Comment by carlosmiei** [comment]
@KindSpidey I checked and  unfortunately Spot markets use a different signing process but using the implicit API we cannot bypass the current signing logic so I think we don't really have a way to do it without the above mentioned update

**Comment by KindSpidey** [comment]
You mean for Spot i should use something like they are using? 
```
from pybit import HTTP
session = HTTP("https://api-testnet.bybit.com",
               api_key="", api_secret="",
               spot=True)
```

**Comment by carlosmiei** [comment]
@KindSpidey We added the new signing mechanism to spot endpoints. Being that if you update your CCXT to the latest version you should be able to place orders using the implicit API (as shown earlier)

Example:
```Python
exchange = ccxt.bybit({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

request = {
    'symbol': 'GMTUSDT',
    'qty': 10, # amount in USDT for market orders and in the base quote for the others
    'type': 'MARKET',# or LIMIT OR LIMIT_MAKER
    'timeInForce': 'GTC', # FOK, IOC
    'side': 'Buy', # or Sell
    #'price': 100 <- use only for limit orders
}

order = exchange.privatePostSpotV1Order(request)
print(order)
```

**Comment by KindSpidey** [comment]
Version 1.82.52
```
bybit = ccxt.bybit({
    "apiKey": config.BYBIT_API_KEY,
    "secret": config.BYBIT_SECRET_KEY
})
request = {
    'symbol': 'GMTUSDT',
    'qty': 10, # amount in USDT for market orders and in the base quote for the others
    'type': 'MARKET',# or LIMIT OR LIMIT_MAKER
    'timeInForce': 'GTC', # FOK, IOC
    'side': 'Buy', # or Sell
    #'price': 100 <- use only for limit orders
}

order = bybit.privatePostSpotV1Order(request)
print(order)
```
Still got
`ccxt.base.errors.ExchangeError: bybit {"ret_code":-1004,"ret_msg":"Missing required parameter \u0027symbol\u0027","ext_code":null,"ext_info":null,"result":null}`

**Comment by kroitor** [comment]
@KindSpidey please, paste your verbose output: 

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.bybit({
    "apiKey": config.BYBIT_API_KEY,
    "secret": config.BYBIT_SECRET_KEY,
    'options': {
        'defaultType': 'spot',
    }
})

markets = exchange.load_markets()
exchange.verbose = True

request = {
    'symbol': 'GMTUSDT',
    'qty': 10, # amount in USDT for market orders and in the base quote for the others
    'type': 'MARKET',# or LIMIT OR LIMIT_MAKER
    'timeInForce': 'GTC', # FOK, IOC
    'side': 'Buy', # or Sell
    #'price': 100 <- use only for limit orders
}

order = exchange.privatePostSpotV1Order(request)
print(order)

**Comment by KindSpidey** [comment]
Still `ccxt.base.errors.ExchangeError: bybit {"ret_code":-1004,"ret_msg":"Missing required parameter \u0027symbol\u0027","ext_code":null,"ext_info":null,"result":null}`

**Comment by carlosmiei** [comment]
@KindSpidey Yes you're right I'm sorry I got confused, actually you need this PR https://github.com/ccxt/ccxt/pull/13263 to be merged before being able to place spot orders. After that update, you will be able to place spot orders normally using the unified method `createOrder`

**Comment by KindSpidey** [comment]
Can you show it with examples of actual code how to make SPOT market order on bybit?

**Comment by marianturchyn** [comment]
exchange.fetchBalance({type: "spot"});
