### ISSUE TITLE
How to make market buy order on MECX?

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#13254]
This

```
balance = mexc_spot.fetch_balance()["free"]["USDT"]
price = mexc_spot.fetch_ticker("BTC/USDT")['last']
amount = float(balance/price)
mexc_spot.create_market_buy_order("BTC/USDT", amount)
```
Got this
```
ccxt.base.errors.InvalidOrder: mexc createOrder() does not support market orders, only limit orders are allowed
```
But in MECX app i can make market orders. So what it is?

**Comment by kroitor** [comment]
@KindSpidey please, upgrade your version of CCXT to the most recent one (1.18.52) and use `mexc3` instead of `mexc`. The v3 API of MEXC was added just days ago and it does support market orders. Hope that helps, let us know if not.

**Comment by KindSpidey** [comment]
Tried, but it shows this error `ccxt.base.errors.InvalidOrder: mexc3 createOrder() requires the price argument with market buy orders to calculate total order cost(amount to spend), where cost = amount * price. Supply a price argument to createOrder() call if you want the cost to be calculated for you from price and amount, or, alternatively, add .options['createMarketBuyOrderRequiresPrice'] = False to supply the cost in the amount argument(the exchange-specific behaviour)`
Why so? Market order should not ask for price, because it already knows it. isnt it?

**Comment by kroitor** [comment]
@KindSpidey 

> Why so? Market order should not ask for price, because it already knows it. isnt it?

That is covered in the Manual here: https://docs.ccxt.com/en/latest/manual.html#market-buys

I would highly recommend reading the entire Manual from top to bottom, it will really save your time, cause it has the answers to most of the starting questions. Hope it helps.

**Comment by KindSpidey** [comment]
Already fixed my mistake. Should add `{'createMarketBuyOrderRequiresPrice' : False, 'defaultType': 'spot'}`
But then here's another `error ccxt.base.errors.BadRequest: mexc3 {"msg":"api market order is disabled","code":30019}`

**Comment by KindSpidey** [comment]
Can you enable api market order?)
