### ISSUE TITLE
Kucoin futures Invalid KC-API-PASSPHRASE

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#13252]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

```
kucoin_futures = ccxt.kucoinfutures({
    "apiKey": config.KUCOIN_FUTURES_API_KEY,
    "secret": config.KUCOIN_FUTURES_API_KEY,
    "password": config.KUCOIN_PASSWORD
})
balance = kucoin_futures.fetch_balance()
print (balance)
```
Got
```
ccxt.base.errors.AuthenticationError: kucoinfutures Invalid KC-API-PASSPHRASE
```
BUT
When i do same with spot, everything works
```
kucoin_spot = ccxt.kucoin({
        "apiKey": config.KUCOIN_API_KEY,
        "secret": config.KUCOIN_SECRET_KEY,
        "password": config.KUCOIN_PASSWORD
    })
balance = kucoin_spot.fetch_balance()
print (balance)
```

**Comment by kroitor** [comment]
@KindSpidey kucoinfutures is a different exchange and you will need a kucoinfutures api keypair for it (not to be confused with the regular kucoin api keys). You will need to create an account and the API keys here: https://futures.kucoin.com/ . Let us know if that does not help.

**Comment by KindSpidey** [comment]
Yep, and i use  ```
"apiKey": config.KUCOIN_FUTURES_API_KEY,
    "secret": config.KUCOIN_FUTURES_API_KEY,
``` for futures, as you can see. Isnt password the same for spot and futures?

**Comment by kroitor** [comment]
> Isnt password the same for spot and futures?

It depends on which password you've set, but it is not your login password afaik, must be an API key password, specifically. Cause Kucoin has multiple passwords for different things.

**Comment by KindSpidey** [comment]
Cant understand what's happening, Just created new futures API with password, get it to the code and still same error

**Comment by kroitor** [comment]
@KindSpidey actually, can you try the login password instead? If that does not help, I'll debug it on my side asap.

**Comment by KindSpidey** [comment]
Tried. Still same error

**Comment by kroitor** [comment]
@KindSpidey when you enable the verbose mode, does your password look ok in the request?

**Comment by KindSpidey** [comment]
How can i check it?

**Comment by kroitor** [comment]
> How can i check it?

Enable the verbose mode after loading the markets as documented in the Manual:

- https://docs.ccxt.com/en/latest/manual.html#troubleshooting

```Python
kucoin_futures = ccxt.kucoinfutures({
    "apiKey": config.KUCOIN_FUTURES_API_KEY,
    "secret": config.KUCOIN_FUTURES_API_KEY,
    "password": config.KUCOIN_PASSWORD
})
markets = exchange.load_markets()
exchange.verbose = True  # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
balance = kucoin_futures.fetch_balance()
print (balance)
```

**Comment by samgermain** [comment]
> Yep, and i use
> 
> ```
> "apiKey": config.KUCOIN_FUTURES_API_KEY,
>     "secret": config.KUCOIN_FUTURES_API_KEY,
> ```

The value for `config.KUCOIN_FUTURES_API_KEY` can not match `config.KUCOIN_API_KEY`, you must create a specific api key on kucoinfutures, which is not a kucoin spot api key. Just checking that you're doing that

![](https://i.imgur.com/rohybJR.png)

> for futures, as you can see. Isnt password the same for spot and futures?

The password won't be the same, you create specific passphrase to use with the kucoin futures api when you create the api key

![](https://i.imgur.com/EFyv1oQ.png)

**Comment by KindSpidey** [comment]
Yes! I did it all and this is unbeliviable, but it doesnt work

**Comment by KindSpidey** [comment]
Guys. I've just created new API for SPOT just for check and EVERYTHING WORKS
But with futures its ubeliviable, but it doesnt!

**Comment by KindSpidey** [comment]
I cant miss in password. I am sorry, but i used just 00000000, cant get error in this. I copied it! I am using futures API key and futures SECRET key, I am usung ccxt.kucoinfutures, but still got ccxt.base.errors.AuthenticationError: kucoinfutures Invalid KC-API-PASSPHRASE

**Comment by samgermain** [comment]
> Guys. I've just created new API for SPOT just for check and EVERYTHING WORKS But with futures its ubeliviable, but it doesnt!

If you just created it for spot then it won't work for futures

**Comment by KindSpidey** [comment]
Man, its not even funny. I UNDERSTAND IT and wrote just as an example. There is definitely something wrong with ccxt kucoin futures. Devs should check it

**Comment by samgermain** [comment]
Can you try with this apiKey and secret, these are read only keys, so you can't make any trades

```
"kucoinfutures": {
    "apiKey": "62829d2ae2d4de00014f1698",
    "secret": "91d38586-ea83-47f9-bdfc-8a23afd14c75",
    "password": "00000000"
  },
  ```

**Comment by KindSpidey** [comment]
This one works

**Comment by kroitor** [comment]
@KindSpidey i've just noticed a duplicate value in your config:

```
kucoin_futures = ccxt.kucoinfutures({
    "apiKey": config.KUCOIN_FUTURES_API_KEY,
    "secret": config.KUCOIN_FUTURES_API_KEY, # <<<<<< MUST BE KUCOIN_FUTURES_SECRET_KEY HERE
    "password": config.KUCOIN_PASSWORD
})
```

@KindSpidey is is possible that you've just made a copypaste typo in the code?

**Comment by KindSpidey** [comment]
Thank you very much for wasting so much time on me. I don't know what it it was, but now it works and I logged in Futures. Was some mistake in config file i guess. Dont know which one, but if not your exampe with direct request i would figure it out much longer. Thank you very much again!
