### ISSUE TITLE
How to set leverages, make buys and sells on gateio futures?

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#13253]
For all actions throwgh `ccxt got ccxt.base.errors.BadSymbol: gateio does not have market symbol`
Can you show examples of code how to set futures mode: isolated and crossed, get tickers and make orders?

**Comment by kroitor** [comment]
Please, read the Manual:

- https://docs.ccxt.com/en/latest/manual.html#markets
- https://github.com/ccxt/ccxt/tree/master/examples/py

```Python
import ccxt
exchange = ccxt.gateio({
    'options': {
        'defaultType': 'swap',
        # 'marginMode': 'cross',  # or isolated
    },
})
markets = exchange.load_markets()
for market in markets.values():
    print(market['symbol'], 'linear' if market['linear'] else 'inverse', market['type'])
print('----------------------------------------------------------')
tickers = exchange.fetch_tickers()
for symbol, ticker in tickers.items():
    print(symbol, ticker['last'])
```

Hope that helps.
