### ISSUE TITLE
How to create a Phemex bracket order for contracts

### ISSUE THREAD

**Issue by CloudTrauma** [ccxt/ccxt#13266]
I am trying to make a long position with Post only and bracket(TP/SL), but cant find examples for it

**Comment by samgermain** [comment]
Post only and TP/SL aren't unified in CCXT yet, but  [you can specify `PostOnly` as a timeInForce option](https://github.com/phemex/phemex-api-docs/blob/master/Public-Contract-API-en.md#common-constants)

[Here's an example of how to set a stop order as a separate order](https://github.com/ccxt/ccxt/blob/9e0c76c5ea2bca7cfebc8cc4dfd8d542097b502b/examples/js/binance-margin-stop-order.js#L1)

**Comment by samgermain** [comment]
You can set `params['stopLossPrice']` and `params['takeProfitPrice']` in createOrder to set stopLoss and takeProfit. 

You can read more about how to use these parameters on #13822

Support was added in #11046
