### ISSUE TITLE
Huobi fututres balance

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#13260]
Trying to get huobi futures balance. I have dollars in account, but ccxt doesnt see them
```
huobi_futures = ccxt.huobipro({
    "apiKey": config.HUOBI_API_KEY,
    "secret": config.HUOBI_SECRET_KEY,
    "options" : {'createMarketBuyOrderRequiresPrice' : False, 'defaultType': 'future'}
})
balance = huobi_futures.fetch_balance()["USDT"]
print(balance)
```
Shows
```
{'free': 0.0, 'used': 0.0, 'total': 0.0}
```

**Comment by kroitor** [comment]
Are you looking for futures or swaps ?

**Comment by KindSpidey** [comment]
Futures

**Comment by kroitor** [comment]
@KindSpidey linear or inverse futures ?

**Comment by kroitor** [comment]
Have you checked this issue:

- https://github.com/ccxt/ccxt/issues/11606#issuecomment-1023192231
- https://github.com/ccxt/ccxt/issues/11606#issuecomment-1023231264

**Comment by KindSpidey** [comment]
Well, I'm trying like an in manual:
```
huobi_futures = ccxt.huobipro({
    "apiKey": config.HUOBI_API_KEY,
    "secret": config.HUOBI_SECRET_KEY,
    "options" : {'createMarketBuyOrderRequiresPrice' : False,
                 'defaultType': 'future',
                 "defaultSubType":'linear'}
})
balance = huobi_futures.fetch_balance()
print(balance)
```

And it shows I have 0 USDT, when in reality I have ones in account

**Comment by kroitor** [comment]
@KindSpidey if you can paste a screenshot of the huobi's website section with the balance you're trying to get – i'll post the ccxt code for it here.

**Comment by KindSpidey** [comment]
![изображение_2022-05-15_180828500](https://user-images.githubusercontent.com/44064808/168474456-bcb5a887-64e7-49d6-931a-0d3c3117b05b.png)

**Comment by kroitor** [comment]
@KindSpidey let me know if this does not help:

```Python
huobi_futures = ccxt.huobipro({
    "apiKey": config.HUOBI_API_KEY,
    "secret": config.HUOBI_SECRET_KEY,
    "options" : {
        'createMarketBuyOrderRequiresPrice' : False,
        'defaultType': 'swap',
        "defaultSubType":'linear',
        'marginMode': 'cross',
    }
})
balance = huobi_futures.fetch_balance()
print(balance)
```

**Comment by KindSpidey** [comment]
It helped. Thank you very much!
