### ISSUE TITLE
Want to know meaning of seat in the subscription plane

### ISSUE THREAD

**Issue by moahemdsobhy** [ccxt/ccxt#13265]
Please I want to know the meaning of a seat in the subscription plane and if there are any limitations to the number of requests?

**Comment by kroitor** [comment]
Hi! 

The number of seats is the number of developers that will have the access to the repository with your subscription, this is handy when working in a team. 

Please, check these links for more info:

- https://ccxt.pro/faq
- https://github.com/ccxt/ccxt/issues/6543
