### ISSUE TITLE
Is flash close on Huobi Futures is available in ccxt?

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#13279]
I am talking about this function from official Huobi Futures: how you can close position on futures by tapping 1 button - https://www.huobi.com/support/en-us/detail/360000268261/

Can i do the same with ccxt?

**Comment by sc0Vu** [comment]
Hi @KindSpidey 

After check documentation of houbi and their UI, I found these api: 

https://huobiapi.github.io/docs/dm/v1/en/#place-flash-close-order

https://huobiapi.github.io/docs/coin_margined_swap/v1/en/#place-lightning-close-order

https://huobiapi.github.io/docs/usdt_swap/v1/en/#isolated-place-lightning-close-order

https://huobiapi.github.io/docs/usdt_swap/v1/en/#cross-place-lightning-close-position

It depends on which contract do you use.

If you want to place these order with ccxt, try this (in javascript):
```JS
huobi.contractPrivatePostApiV1LightningClosePosition(payload)

huobi.contractPrivatePostSwapApiV1SwapLightningClosePosition(payload)

huobi.contractPrivatePostLinearSwapApiV1SwapLightningClosePosition(payload)

huobi.contractPrivatePostLinearSwapApiV1SwapCrossLightningClosePosition(payload)
```
