### ISSUE TITLE
CCXT will not import inside Web Worker 

### ISSUE THREAD

**Issue by psytron** [ccxt/ccxt#13284]
- OS: Mac OS Big Sur
- Programming Language version: JavaScript Vanilla in Browser 
- CCXT version: 1.81

CCXT will not import inside Web Worker 

```
// main.js
var w = new Worker( 'worker' , { type:'module'} ) 

// web_worker.js
import { * as ccxt } from './ccxt.browser.js';
```

```
silent fail to load  
```

**Comment by carlosmiei** [comment]
Hello @psytron,

Please check out this example regarding web workers' usage: https://github.com/ccxt/ccxt/tree/master/examples/html/webworker

Let me know if that does not help.

**Comment by psytron** [comment]
Thanks @carlosmiei. This example is using old style importScripts and requires WebWorker type:'classic' 

New esm style import using Worker( {type:module } )  enable intermixing and importing new es6 modules.

**Comment by frosty00** [comment]
@psytron we are working on adding esm support to ccxt - see #12619, we plan to complete it later this month

**Comment by psytron** [comment]
In the meantime are solutions like  https://esm.sh/  and https://esbuild.github.io/  recommended ?

**Comment by psytron** [comment]
Is this recommended in the meantime ?  https://github.com/carlosmiei/ccxt

**Comment by psytron** [comment]
Any movement on this?   Enabling smooth fast UI and responsive apps would benefit tremendously from ability to offload heavy server communications like ccxt into an independent process ( web worker )

**Comment by dkraemerwork** [comment]
Yes, its working again since the first of november actually.

**Comment by frosty00** [comment]
closing since this has been fixed
