### ISSUE TITLE
ExchangeError is thrown for status code 429 in bitfinex2

### ISSUE THREAD

**Issue by kevyu** [ccxt/ccxt#1328]
In bitfinex2 , ExchangeError is thrown for status code 429, it should throw DDoSProtection.

-------
- OS: windows
- Programming Language version: js
- CCXT version: 1.10.738
- Exchange: bitfinex2
- Method: fetchTickers

**Comment by kroitor** [comment]
Can you please show verbose output of it?

**Comment by kroitor** [comment]
I would close this for now until we have a follow up on this. Let us know if you still have problems with it, feel free to reopen this issue or just ask questions, if any. Thx.
