### ISSUE TITLE
How to resolve two different currencies with same ticker on different exchanges

### ISSUE THREAD

**Issue by bdelamotte** [ccxt/ccxt#1330]
Binance has CMT ticker, but it's the CyberMiles currency
Cryptopia has CMT ticker, but it's the Comet currency

Is there a way to compare these two ticker symbols using ccxt to make sure they are in fact the same coin on two different exchanges? What possible workarounds would you recommend if not? This is probably a rare case as I'm sure currencies try to avoid this issue and pick a different ticker symbol, but it seems it will be an issue with the following current coins pairs:

AdCoin ACC, Accelerator ACC
ArcticCoin ARC, Arcade Token ARC
BetaCoin BET, DAO.Casino BET
Bitcoin Scrypt BTCS, Bitcoin Silver BTCS
Bitcoin Gold BTG, Bitgem BTG
Bitmark BTM, Bytom BTM
CanYaCoin CAN, Content and A... CAN
Cashcoin CASH, Cash Poker Pro CASH
Catcoin CAT, BitClave CAT, BlockCAT CAT
COMSA [ETH] CMS, COMSA [XEM] CMS
Comet CMT, CyberMiles CMT
EncryptoTel [... ETT, EncryptoTel [... ETT
FairCoin FAIR, FairGame FAIR
TheGCCcoin GCC, GuccioneCoin GCC
Global Tour Coin GTC, Game GTC
Helleniccoin HNC, Huncoin HNC
iCoin ICN, Iconomi ICN
KingN Coin KNC, Kyber Network KNC
LiteBitcoin LBTC, Lightning Bit... LBTC
NetCoin NET, Nimiq NET
Propy PRO, ProChain PRO
Cubits QBT, Qbao QBT
Rcoin RCN, Ripio Credit ... RCN
Russian Miner... RMC, Remicoin RMC
SmartCash SMART, SmartBillions SMART
International... XID, Sphre AIR XID

The result of not being able to compare if these are really the same token (via description or name) means that it could be possible to transfer a balance of one ticker to the same ticker but different coin on another exchange, and lose all your money.

**Comment by kroitor** [comment]
Hi! In general, the issue that you describe, is about a symbol name inconsistency across different exchanges. And we have a policy for that: the symbol with the highest market cap (as per coinmarketcap) wins. So, we are going to remove these duplicates one by one.

The same type of question is also answered (and fixed) here:
- https://github.com/ccxt/ccxt/issues/1171
- https://github.com/ccxt/ccxt/issues/348
- https://github.com/ccxt/ccxt/issues/390
- https://github.com/ccxt/ccxt/issues/302

> Is there a way to compare these two ticker symbols using ccxt to make sure they are in fact the same coin on two different exchanges?

Compare prices and volumes.

> What possible workarounds would you recommend if not? 

We will deduplicate them one by one quite quickly, as soon as our Travis CI system gets back online. Hopefully in a few hours. Thx for reporting!

**Comment by kroitor** [comment]
Fixed more of them for Cryptopia. Let us know if you find more (we need the symbol + exchange, where that symbol is present, in order to fix it). Thx!

**Comment by michaeldim** [comment]
HNC/BTC, HellenicCoin on Livecoin and Huncoin on Coinexchange.

**Comment by TorosCrypto** [comment]
(KEY) ticker conflict. 
SelfKey is highest cap and traded on Binance however ticker symbol is taken by Key coin which sits at 1544 on coinmarketcap.

**Comment by VillageDeveloper2019** [comment]
I see the logo for the blockstack  token (STX) on MetaMask is different than the logo on coinbase. Is this usual? Shouldn't the logo be consistent or it is different tokens that have the same trading symbol?

**Comment by kroitor** [comment]
@VillageDeveloper2019 MetaMask might point to Stocks (STX), while Coinbase points to Blockstack Stacks (STX). They're different token that have the same symbol.

**Comment by VillageDeveloper2019** [comment]
> @VillageDeveloper2019 MetaMask might point to Stocks (STX), while Coinbase points to Blockstack Stacks (STX). They're different tokens that have the same symbol.

Thanks for the explanation. I do notice Stox (STX) on Coinbase. The logo for that is also different from STX I see on MetaMask. Most likely a third STX token or just any of Stacks or Stox.
