### ISSUE TITLE
Can you help me with getting number of max leverage of contract on gateio?

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#13302]
Doing

```
print(gateio_futures.fetch_contract_markets())
```
Getting
```
TypeError: gateio.fetch_contract_markets() missing 1 required positional argument: 'params'
```
Dont know what to do with it. Can you show the example of code how to get max leverage for pair GMT/USDT on futures?

**Comment by carlosmiei** [comment]
Hello @KindSpidey,

You should refrain from using the implicit API whenever possible, if you carefully read CCXT manual you will see that most of the information you might wanna consult is available through our unified methods in a simple and organized way.

For instance, to check the leverage limits for a certain market pair you can simply do something like this:

```Python
exchange = ccxt.gateio({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET_KEY',
    'options': {
        'defaultType': 'swap',
    },
})

markets = exchange.load_markets()
target_market = markets['BTC/USDT:USDT']
print(target_market['limits']['leverage'])
````

**Comment by KindSpidey** [comment]
Thank you very much!
