### ISSUE TITLE
FTXUS odd behavior when selling...

### ISSUE THREAD

**Issue by pottertech** [ccxt/ccxt#13307]
My code is making purchases of amounts of 10 and later attempts to sell the amount of 10.  I get back a successful sell transaction but the amount is always 1.0 and not 10.0 ?  

Anyone have any idea if I need to pass any additional info in params() or some other bit of info that would allow FTXUS to sell the entire amounts that I pass?

- OS: Ubuntu 20.04
- Programming Language version: 7.4
- CCXT version: 1.82.82

**Comment by kroitor** [comment]
Let's make sure that we use the correct terms, for spot markets, amounts are always in the base asset, prices are in quote assets, costs are also in quote assets:

- https://docs.ccxt.com/en/latest/manual.html#consistency-of-base-and-quote-currencies

Please, paste your code and your verbose output (enable verbose mode before the create_order call in question):

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
- https://docs.ccxt.com/en/latest/manual.html#troubleshooting

**Comment by ttodua** [comment]
As no follow-up has been provided, and neither there is any information that we could understand (no pair, no sample code, no sample responses), for now I'll mark this issue as closed.
Let us know if you have any issues with CCXT.
