### ISSUE TITLE
Bybit fetch_funding_rate could use different API endpoint and get also the predicted funding rate

### ISSUE THREAD

**Issue by docek** [ccxt/ccxt#13315]
Currently bybit.fetch_funding_rate() returns current funding rate and no predicted funding rate. Current and predicted funding rate are both available in fetch_ticker()['info']

**Comment by Dan-krm** [comment]
I've opened a PR that will include the predicted funding rate, timestamp, datetime, index price and mark price using data from fetchTicker.

**Comment by tunedforai** [comment]
For anyone still needing predicted funding rates across multiple exchanges — we built an aggregated feed that returns current + predicted funding in one call. Covers 20 exchanges, no rate limits, pay-per-call in USDC.

Might save you from managing multiple exchange endpoints: x402.tunedfor.ai

Example response includes fundingRate, predictedFundingRate, nextFundingTime, and open interest. Happy to share more details if useful.
