### ISSUE TITLE
Trying to open position on MEXC Futures

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#13319]
```
symbol = 'LINK/USDT:USDT'
balance = float(mexc_futures.fetch_balance()["USDT"]["free"])
price = float(mexc_futures.fetch_ticker("LINK/USDT:USDT")["last"])
leverage = 0
for elem in mexc_futures.fetch_contract_markets():
    if elem["symbol"] == "LINK/USDT:USDT":
        leverage = float(elem["info"]["maxLeverage"])
amount = (math.floor(math.floor(balance/price)*10*leverage))
params = {'openType': 1, "leverage": leverage, "positionType":1}
mexc_futures.create_order(symbol,1, 1, amount, price, params)
```
But get
```
ccxt.base.errors.ExchangeError: mexc {"success":false,"code":2021,"message":"Leverage ratio is inconsistent with the existing position leverage ratio!"}
```
By the way, even when i put amount and leverage by hands, small numbers, error is still the same

**Comment by samgermain** [comment]
From a quick glance I'm guessing the leverage shouldn't be less than 1, it's also setting your amount to 0, could you try changing that?

**Comment by KindSpidey** [comment]
It's not 0

**Comment by KindSpidey** [comment]
![изображение_2022-05-18_145433416](https://user-images.githubusercontent.com/44064808/169012311-687b03f9-6e94-49a3-ac78-479c98280358.png)

**Comment by KindSpidey** [comment]
![изображение_2022-05-18_145523759](https://user-images.githubusercontent.com/44064808/169012485-7a4d34af-d514-4fb5-a2bc-4a80e0635f43.png)

**Comment by samgermain** [comment]
It sounds like you might already have a position open on mexc, and your trying to create another order in the same market with a different leverage, which mexc wont allow, you might need to call `fetchPosition` and check what your leverage is before placing another order on the same market

**Comment by KindSpidey** [comment]
No, i have 0 open orders or positions

**Comment by ttodua** [comment]
you have to use [`setLeverage` method](https://docs.ccxt.com/en/latest/manual.html#leverage) at first (mexc supports that method), so at first you set your desired leverage for that symbol, and then submit the order.

Let us know if you have further issues with CCXT.
