### ISSUE TITLE
Make mexc futures order

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#13314]
Trying to do
```
mexc_futures = ccxt.mexc({
    "apiKey": config.MEXC_API_KEY,
    "secret": config.MEXC_SECRET_KEY,
    "options": {'defaultType': 'swap' }
})
balance = mexc_futures.fetch_balance()["USDT"]["free"]
price = mexc_futures.fetch_ticker("BTC/USDT:USDT")["last"]
amount = balance/price
print(balance,price,amount)
mexc_futures.create_order("BTC/USDT:USDT",1, 1, amount, price)
```
Getting
```
ccxt.base.errors.ArgumentsRequired: mexc createSwapOrder() requires an integer openType parameter, 1 for isolated margin, 2 for cross margin
```

**Comment by kroitor** [comment]
Just add the openType parameter to it:

- https://docs.ccxt.com/en/latest/manual.html#placing-orders
- https://docs.ccxt.com/en/latest/manual.html#overriding-unified-api-params

```Python
mexc_futures = ccxt.mexc({
    "apiKey": config.MEXC_API_KEY,
    "secret": config.MEXC_SECRET_KEY,
    "options": {'defaultType': 'swap' }
})
balance = mexc_futures.fetch_balance()["USDT"]["free"]
price = mexc_futures.fetch_ticker("BTC/USDT:USDT")["last"]
amount = balance/price
print(balance,price,amount)
params = {'openType': 1}  # ------------------------------------ ↓
mexc_futures.create_order("BTC/USDT:USDT",1, 1, amount, price, params)
```

**Comment by KindSpidey** [comment]
`ccxt.base.errors.ArgumentsRequired: mexc createSwapOrder() requires a leverage parameter for isolated margin orders`

**Comment by KindSpidey** [comment]
Wait
Fixed it to this 
`params = {'openType': 1, "leverage":1} 
mexc_futures.create_order("BTC/USDT:USDT",1, 1, 2, price, params)`

And gettint this `ccxt.base.errors.InvalidOrder: mexc {"success":false,"code":1002,"message":"Contract not allow place order!"}`
Why so?

**Comment by kroitor** [comment]
> ccxt.base.errors.ArgumentsRequired: mexc createSwapOrder() requires a leverage parameter for isolated margin orders

When you see an error message like this just keep adding those params as it says:

```Python
mexc_futures = ccxt.mexc({
    "apiKey": config.MEXC_API_KEY,
    "secret": config.MEXC_SECRET_KEY,
    "options": {'defaultType': 'swap' }
})
balance = mexc_futures.fetch_balance()["USDT"]["free"]
price = mexc_futures.fetch_ticker("BTC/USDT:USDT")["last"]
amount = balance/price
print(balance,price,amount)
params = {'openType': 1, 'leverage': 1}  # --------------------- ↓
mexc_futures.create_order("BTC/USDT:USDT",1, 1, amount, price, params)
```

> Wait Fixed it to this `params = {'openType': 1, "leverage":1} mexc_futures.create_order("BTC/USDT:USDT",1, 1, 2, price, params)`
> And gettint this `ccxt.base.errors.InvalidOrder: mexc {"success":false,"code":1002,"message":"Contract not allow place order!"}` Why so?

According to MEXC's tech support, the BTC, ETH and LTC swaps are not enabled for API trading on the exchange side yet. Other markets should work.

**Comment by KindSpidey** [comment]
Well, trying this
`balance = mexc_futures.fetch_balance()["USDT"]["free"]
price = mexc_futures.fetch_ticker("LINK/USDT:USDT")["last"]
amount = balance/price
print(balance,price,amount)
params = {'openType': 1, "leverage":1, "positionType":1}  
mexc_futures.create_order("LINK/USDT:USDT",1, 1, 2, price, params)`

Getting `ccxt.base.errors.ExchangeError: mexc {"success":false,"code":7002,"message":"Position mode mis match"}`

**Comment by kroitor** [comment]
@KindSpidey if you upgrade to CCXT 1.82.94 in ~20 minutes, then you will be able to manage your position mode with the following implicit methods:

- https://docs.ccxt.com/en/latest/manual.html#implicit-api
- https://docs.ccxt.com/en/latest/manual.html#passing-parameters-to-api-methods
- https://mxcdevelop.github.io/APIDoc/

<img width="1680" alt="Screenshot 2022-05-18 at 10 41 20" src="https://user-images.githubusercontent.com/1294454/168986245-683287eb-36a3-41cf-961e-e18b71983928.png">

```Python
symbol = '"LINK/USDT:USDT'
balance = mexc_futures.fetch_balance()["USDT"]["free"]
price = mexc_futures.fetch_ticker("LINK/USDT:USDT")["last"]
amount = balance/price
print(balance,price,amount)

leverage = mexc_futures.contract_private_get_position_position_mode()
print('Leverage:', leverage)

response = mexc_futures.contract_private_post_position_change_position_mode({'positionMode':1})
print('Response:', response)

params = {'openType': 1, "leverage":1, "positionType":1}  
mexc_futures.create_order(symbol,1, 1, 2, price, params)
```

**Comment by KindSpidey** [comment]
Thanks

**Comment by KindSpidey** [comment]
Your code brings `ccxt.base.errors.BadSymbol: mexc does not have market symbol "LINK/USDT:USDT`
