### ISSUE TITLE
Slow response time from Binance with CCXT

### ISSUE THREAD

**Issue by HeinrichKg** [ccxt/ccxt#13311]
- OS: Windows 10
- Programming Language version: Python 3.10.
- CCXT version: 1.81.48
- Exchange: Binance

Hi, I am new at CCXT. I am trying to do something, and I noticed that simple things, like getting order book for trading pairs is so, so slow. Getting order books for 3 pairs last around 3 seconds. This is my test code:

```
beginning = exchange.fetchTime()
dubina = exchange.fetchOrderBook("LTC/BUSD", limit=1)
for i, v in dubina.items():
    print(f"{i}: {v}")
dubina = exchange.fetchOrderBook("LTC/BNB", limit=1)
for i, v in dubina.items():
    print(f"{i}: {v}")
dubina = exchange.fetchOrderBook("BNB/BUSD", limit=1)
for i, v in dubina.items():
    print(f"{i}: {v}")
theend = exchange.fetchTime()
print(theend-beginning)
``` 

My result is:
```
symbol: LTC/BUSD
bids: [[72.7, 106.29]]
asks: [[72.8, 237.409]]
timestamp: None
datetime: None
nonce: 890099690
***************
symbol: LTC/BNB
bids: [[0.2399, 0.467]]
asks: [[0.2401, 19.599]]
timestamp: None
datetime: None
nonce: 334885324
***************
symbol: BNB/BUSD
bids: [[303.3, 24.272]]
asks: [[303.4, 67.709]]
timestamp: None
datetime: None
nonce: 2211911517
***************
3552
```

I am desperate :(
When I ping api.binance.com I get 13ms

**Comment by kroitor** [comment]
You're measuring the rate-limited queue and the fetchTime roundtrip and also counting the market-loading time, which isn't an entirely correct way of measuring it. 

If you really want to measure your latency, please, read the Manual from top to bottom, especially on the rate limiting, and then run the following script:

- https://docs.ccxt.com/
- https://docs.ccxt.com/en/latest/manual.html#rate-limit
- https://docs.ccxt.com/en/latest/manual.html#notes-on-rate-limiter
- https://docs.ccxt.com/en/latest/manual.html#loading-markets

-------------------

- https://github.com/ccxt/ccxt/blob/master/examples/py/fetch-order-book-latency.py

```Python
# -*- coding: utf-8 -*-

import os
import sys
from pprint import pprint

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402


# WARNING!
# This example measures the round-trip time by fetching the orderbook from an exchange
# In order to measure the speed of requests it disables the rate-limiting
# Disabling the rate-limiter is required to do an accurate measurement
# If you keep running without a rate limiter for a long time the exchange will ban you
# In a live production system always use either the built-in rate limiter or make your own


def main():

    # the exchange instance has to be reused
    # do not recreate the exchange before each call!

    exchange = ccxt.binance({

        # if you do not rate-limit your requests the exchange can ban you!
        'enableRateLimit': False,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

    })

    exchange.load_markets()  # https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

    # exchange.verbose = True  # uncomment for debugging purposes if needed

    symbol = 'BTC/USDT'

    results = []
    num_iterations = 10

    for i in range(0, num_iterations):
        started = exchange.milliseconds()
        orderbook = exchange.fetch_order_book(symbol)
        ended = exchange.milliseconds()
        elapsed = ended - started
        pprint(elapsed, 'ms')
        results.append(elapsed)

    pprint(results)

    rtt = int(sum(results) / len(results))
    print('Successfully tested', num_iterations, 'calls, the average round-trip time per call is', rtt, 'milliseconds')


main()
```

Hope that answers your question, let us know if not.

**Comment by kroitor** [comment]
Feel free to reopen this issue if the above does not help or just ask further questions if any.

**Comment by HeinrichKg** [comment]
Thank you very much, your answer was pretty quick, and tnx for that.

I agree, this kind of measurement is much better way to measure. 

This is my result with your code:

250 ms
251 ms
252 ms
251 ms
923 ms
929 ms
930 ms
249 ms
250 ms
938 ms
922 ms
249 ms
251 ms
925 ms
252 ms
252 ms
252 ms
248 ms
248 ms
933 ms
257 ms
255 ms
253 ms
251 ms
251 ms
251 ms
253 ms
251 ms
924 ms
251 ms
254 ms
253 ms
252 ms
249 ms
249 ms
248 ms
250 ms
250 ms
249 ms
251 ms
251 ms
248 ms
250 ms
250 ms
250 ms
253 ms
248 ms
251 ms
250 ms
252 ms

Successfully tested 50 calls, the average round-trip time per call is 359 milliseconds`

This is much faster. I guess this has to do with `exchange.load_markets()`, especially on first call.
I tried `'enableRateLimit': False` and also with `'enableRateLimit': True` and it seems that it doesn't have any effect. Results are the same.

It seems to me that Binance API is slower then I expected :( 250 ms is good, but I thought it could be better (triangular arbitrage is on my mind). It is interesting to me that results of single request are either around 250 ms, or around 920 ms, there is nothing in the middle (400 ms, 700 ms ...).

Once again thanks a lot. I am beginner, so my questions are maybe... But I hope that in some time I will be able to help to other beginners in this great community :) You are doing great job with CCXT 👍

**Comment by kroitor** [comment]
> It seems to me that Binance API is slower then I expected :( 250 ms is good, but I thought it could be better (triangular arbitrage is on my mind). It is interesting to me that results of single request are either around 250 ms, or around 920 ms, there is nothing in the middle (400 ms, 700 ms ...).

Your can have a shorter RTT if you move your machine close to Binance servers. Some people report RTT of 20-50ms. Also, some exchanges offer colocation, so you can place your server on their site or even run your code on their machines within their network, that should reduce your latency even further.
