### ISSUE TITLE
Bug wih opening position on MEXC Futures

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#13322]
THIS
```
mexc_futures = ccxt.mexc({
    "apiKey": config.MEXC_API_KEY,
    "secret": config.MEXC_SECRET_KEY,
    "options": {'defaultType': 'swap' }
})
symbol = 'LINK/USDT:USDT'
balance = float(mexc_futures.fetch_balance()["USDT"]["free"]) - float(mexc_futures.fetch_balance()["USDT"]["free"])/100*5
price = float(mexc_futures.fetch_ticker("LINK/USDT:USDT")["last"])
leverage = 0
for elem in mexc_futures.fetch_contract_markets():
    if elem["symbol"] == "LINK/USDT:USDT":
        leverage = int(elem["info"]["maxLeverage"])
amount = (math.floor((balance/price)*10*leverage)*0.98)
params = {'openType': 1,  "positionType":1, "leverage": leverage}
mexc_futures.create_swap_order(symbol, 1, 1, amount, price*1.01, params)
```
gets error
```
ccxt.base.errors.ExchangeError: mexc {"success":false,"code":2021,"message":"Leverage ratio is inconsistent with the existing position leverage ratio!"}
```
If i pass params by hand, for example 
`
symbol = 'LINK/USDT:USDT'
balance = float(mexc_futures.fetch_balance()["USDT"]["free"]) - float(mexc_futures.fetch_balance()["USDT"]["free"])/100*5
price = float(mexc_futures.fetch_ticker("LINK/USDT:USDT")["last"])
params = {'openType': 1,  "positionType":1, "leverage": 50}
mexc_futures.create_swap_order(symbol, 1, 1, 2, price*1.01, params)`

It will still say to me `ccxt.base.errors.ExchangeError: mexc {"success":false,"code":2021,"message":"Leverage ratio is inconsistent with the existing position leverage ratio!"}`
Looks like another bug, because this contract HAS 50x leverage, but ccxt doesnt see this

If i try `params = {'openType': 1,  "positionType":1, "leverage": 1}
mexc_futures.create_swap_order(symbol, 1, 1, 3, price*1.01, params)` - it works, with the leverage MORE than 1 - IT DOESNT
```
params = {'openType': 1,  "positionType":1, "leverage": 2}
mexc_futures.create_swap_order(symbol, 1, 1, 3, price*1.01, params)
```
`ccxt.base.errors.ExchangeError: mexc {"success":false,"code":2021,"message":"Leverage ratio is inconsistent with the existing position leverage ratio!"}`

My dear sweat devs, who saves me all these days, can you please check it and fix it?

**Comment by carlosmiei** [comment]
Hello @KindSpidey,

First and foremost, I would recommend using the latest mexc API by instantiating **mexc3** instead of mexc. 

```Python
mexc_futures = ccxt.mexc3({
(...)
})
```
Regarding your question, can you try to set the leverage using the set_leverage method before creating the order, to see if it works?

Something like this:
```Python

params = {'openType': 1,  'positionType':1}
leverage = 2
exchange.set_leverage(leverage, symbol, params)
```

**Comment by carlosmiei** [comment]
@KindSpidey, To reduce a position you just need to issue an order for the opposite side with the reduceOnly flag = true.

Example:

```
# First order that will open your position
side = 1 # open long
type = 'market'
amount = 1 # your amount here

opening_order = exchange.create_order(symbol, type, side, amount)

# Second order that will reduce your position

params = {
    'reduceOnly': True
}

reduce_side = 4 # close long -> the opposite of the first order
reduce_amount = x # your reduce amount here
reduce_type = 'market'

reduce_order = exchange.create_order(symbol, reduce_type, reduce_side, reduce_amount, None, params)

```

**Comment by KindSpidey** [comment]
thanks!

**Comment by carlosmiei** [comment]
@KindSpidey yep I forgot to add the openType as you had in the beginning:

```
params = {
    'openType': 1, # choose 1 for isolated margin and 2 for cross
    'reduceOnly': True
}

**Comment by KindSpidey** [comment]
Nope. still the same
`ccxt.base.errors.ArgumentsRequired: mexc createSwapOrder() requires a leverage parameter for isolated margin orders
`

**Comment by KindSpidey** [comment]
Thank you very much, it works

**Comment by tungnt128888** [comment]
> Thank you very much, it works

Hi KindSpidey,

Plz can you send me the full code to login MEXC. I tried to write some but its not working. Tks.

**Comment by philipperemy** [comment]
`cccxt.mexc3` is not available what should we use now?
