### ISSUE TITLE
Fill or Kill limit order doesn't fill although the orderbook shows it should

### ISSUE THREAD

**Issue by echograph** [ccxt/ccxt#13326]
- OS: Windows 10
- Programming Language version: Python 3.10.2
- CCXT version: 1.82.94

Hi! This is my first issue submitting, so I'll try to do my best.
This is a question, not an issue :D (I dont know if I have to label it or the team does it)

My script has 2 clear phases:
 - Checks orderbook at exchange 1
 - Puts a limit order based on that orderbook in exchange 2 with time in force: fill or kill

Aswell, I monitorize the price differences between both exchanges all the time.

There is no error code, simply I don't understand why sometimes it executes correctly but not always, it is not consistent.

Here is the code where I check the orderbook and place an order based on that.

```
sask = 9999999999
sbid = 9999999999
params = {
    'timeInForce': 'FOK',
}

orderbook = exchange_1.fetch_order_book(symbol_1)
sbid = orderbook['bids'][0][0] if len (orderbook['bids']) > 0 else None
sask = orderbook['asks'][0][0] if len (orderbook['asks']) > 0 else None

if sbid != 9999999999 and sask != 9999999999:
    askTarget = sask + (sask * profit)
    bidTarget = sbid - (sbid * profit)

    try:
        if direction == "sold":
            cqty = min(((qtyUSD/bidTarget)*0.997), qtyCoin)
            buy_order = exchange_2.create_limit_buy_order(symbol_2, cqty, bidTarget, params)
            sell_order = None
        elif direction == "bought":
            cqty = min(((qtyUSD/askTarget)*0.997), qtyCoin)
            sell_order = exchange_2.create_limit_sell_order(symbol_2, cqty, askTarget, params)
            buy_order = None
```

I checked and monitorized the mayority of the possible problems and I discarded some issues.

 - The order is set always at the price I want correctly.
 - The amount is correct always.
 - I manage the exceptions but I deleted them from the code snippet in order to be easier to read and understand it, so it is not exception management issue.
 
I'm working with kucoin, Binance, Ftx, bybit etc.

I noticed this hapens trading in spot, but when I apply the same code in futures, it executes perfectly, always.

So I monitorized the script printing the variables in the phases, and this is an example of one of the failed ones:

```
---------------  binance  -  kucoin  -  AGLD/USDT  -  AGLD/USDT  -  0.155  ---------------
(All from Kucoin): bid target:  0.5761 ask:  0.585 ask target:  0.5809 bid:  0.5821
(Actual placed order): Sell Order price:  0.5808989999999999
(*)Margin:  0.2067
(first layer of orderbook [price, amount]): [0.5821, 119.0119]
```
* Margin: Price difference between exchange 1 and echange 2, calculated like that: ((bid/askTarget)-1). Being both from kucoin. (askTarget is calculated with binance price as seen in the code snippet). So when margin > 0 the bid is actually bigger than my sell price, so it should fill.

In this case, I'm putting a sell order at kucoin at my target which is: ask target:  0.5809.
So as you can see the sell order sets perfectly at price: 0.5808989999999999
And the bid in that moment is 0.5821, which is bigger.

I though that a possible reason why it doesn't fill, could be that, as I use Time in Force: 'FOK', the amount of the first bid could be smaller than my order, but as you can see at the orderbook stamp, [0.5821, 119.0119], there is 119 coins at price 0.5821, and my order amount was 35.

I use Threading and execute this every 0.35 seconds. So it could be that too.

So I don't really know why it doesn't fill. Any idea?

There is another cases where the order is filled when the margin is between -1 and -0.6, which does not make much sense, as the bid should be much lower than my sell order.

Thanks in advance, and I'm sorry if there is gramatical errors (as I'm not native speaker) or something I did bad. This is my first issue submit, so feel free to correct me :D

**Comment by echograph** [comment]
Hi, I've been testing more with this issue, and I have some conclusions. So, I've tested a lot more, and the program executes when margins suggest it shouldn't, and it does not execute when it should. That makes me think that fill or kill limit orders doesn't match the orderbook orders but the market orders instead. That would explain why the orders fill when my orders are in a price where it shouldn't fill (a 'FoK' limit buy order at any price shouldn't fill if there are more buy orders above).

Could this be possible?
Do you have any idea what's happening?

If you need more test cases or more code or explanations just tell me :D

Thanks!

**Comment by ttodua** [comment]
I will add my thoughts:
1) orderbooks doesn't always reflect the truth (depends on exchange quality). there are many cases when "top-tier" exchanges (to name a few, I've myself met gate.io, mexc, etc) having fake entries in data/orderbook, while there are actually no real orders. also washtrading... So, when you expect that there is `X` amount in orderbook, it might not be in reality.
2) the second thing, which I think it more realistically related to your issue, is that, when you fetch orderbook data, then already i.e. 1-2 seconds might be gone before your next script-decided order reaches exchange server. So, by that time, that orderbook entry might already by taken by someone other trader (don't think that you are the only one who trades arbitrage, and ppl have more strong servers/scripts). So, it might be the problem, which you might not be able to fix
3) also, last note, are you sure the parameter keyname `timeInForce` is accepted on `exchange2`? ensure that.

let us know if you have any further issue with CCXT.
