### ISSUE TITLE
Bugs in safe_ticker() in exchange.py

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#13329]
- OS: Linux Mint
- Programming Language version: Python 3.10
- CCXT version: 1.82.94

It seems that one of the purposes of the `safe_ticker` function in exchange.py is to figure out values that are missing from the raw `ticker` argument. However, it would seem that the function fails to do so in some cases for quite many exchanges. Here's an example for CoinFalcon:

```
exchange = ccxt.coinfalcon({...})
print(exchange.fetch_tickers())
```

```
...
{'symbol': 'BTC/EUR', 'timestamp': 1652878306271, 'datetime': '2022-05-18T12:51:46.271Z', 'high': None, 'low': None, 'bid': 27930.08, 'bidVolume': None, 'ask': 29184.07, 'askVolume': None, 'vwap': None, 'open': 28650.44, 'close': 28649.54, 'last': 28649.54, 'previousClose': None, 'change': -0.9, 'percentage': None, 'average': None, 'baseVolume': None, 'quoteVolume': 6511.37, 'info': {'name': 'BTC-EUR', 'precision': '2', 'min_volume': '0.00000001', 'min_price': '0.01', 'volume': '6511.37', 'last_price': '28649.54', 'highest_bid': '27930.08', 'lowest_ask': '29184.07', 'change_in_24h': '-0.9', 'size_precision': '8', 'price_precision': '2'}}
...
```
First I would like to note that CoinFalcon `parse_ticker` probably has a bug, as 'change_in_24h' value from the exchange API dictionary should most likely be used as the 'percentage' value in ccxt dictionary.

Secondly, 'percentage' and 'average' values are None, even though there should be nothing to stop calculating them in `safe_ticker`, as according to ccxt manual 'percentage' should be equal to `(change/open) * 100` and 'average' should be equal to `(last + open) / 2` and `change`, `open` and `last` have proper values in this case after `safe_ticker` has done its job.

My take is that `safe_ticker` cannot currently handle all the situation where some of these values are known and some are not. For example, `open` is calculated in line 2079 in exchange.py:
```                
open = Precise.string_sub(last, change)
```
This value could be then used for calculating the 'percentage' value, but that calculation is not considered anymore after line 2079.

Line 2077 is also mathematically incorrect:
```
change = Precise.string_div(Precise.string_mul(percentage, last), '100')
```
This becomes clear by using an example. If `open=10`, `last=12`, `change=2` and `percentage=20` (that are mathematically consistent), one can see that the right side of this equation would give value `2.4`, which is incorrect. 

The same issues probably apply to both `legacy=True` and `legacy=False` parts of the `safe_ticker` code. The other programming language versions of the code are most likely worthy of checking too.

After all this, the question then becomes in which situations can the unknown values (None:s) be determined and with what formulas? It is easies to first consider `open`, `close`, `change` and `percentage` values. Clearly, if only zero or one of those are known, nothing can be done to figure out the rest. If all are known, nothing needs to be done. I find it most useful to consider a case where two of those values are known. As a matter of fact, in every such case the rest of the values can be determined as long as there is no division by zero. There are in total 6 of such cases, which are presented below. The known values are on the left side and formulas for calculating the rest to the right from them:
```
open, last -> change = last - open -> percentage = change/open*100
open, change -> last = open + change -> percentage = change/open*100
last, change -> open = last - change -> percentage = change/open*100
change, percentage -> open = change/percentage*100 -> last = open + change
open, percentage -> change = open*percentage/100 -> last = open + change
last, percentage -> change = last*percentage/(100 + percentage) -> open = last - change
```
If I did not make any mistakes, all these formulas should work. It can be checked with the example values I gave above.

In a situation where three values are known one of the two given formulas can be skipped in each of the 6 cases. 

After using the formulas `average` and `close` values can be determined, if needed. If you want to go one step further, either `open` or `last` can be calculated if one of them as well as `average` value is known before using the formulas. In that case it should be made sure that the `average` value received from the exchange API has the exact same meaning as ccxt is using for every exchange (the same principle obviously applies to all raw ticker values).

One more peculiarity is that 'previousClose' value is not being considered at all by `safe_ticker.` In case of some exchanges this leads to it having string type even though it by default should have a float type according to the manual. I'm guessing `safe_number` should be applied to it at some point. It would also be really nice to know the exact meaning of this number and its relation to other values in the ticker.

EDIT: Fixed a typo in the first formula of the last case

**Comment by JovianMoon** [comment]
Just wanted to add here that using wrong math can cause quite nasty issues, such as negative 'open' values. However, In other cases they can also be negative because other raw ticker values are wrong and `safe_ticker` does its math correctly. Here's an example of a negative 'open' for Gate.io in 1.84.5:

```
{'symbol': 'FTM3L/USDT', 'timestamp': None, 'datetime': None, 'high': 0.16678, 'low': 0.00182, 'bid': 0.16562, 'bidVolume': None, 'ask': 0.16749, 'askVolume': None, 'vwap': 0.003174039582806609, 'open': -12.2659293, 'close': 0.163, 'last': 0.163, 'previousClose': None, 'change': 12.4289293, 'percentage': 7625.11, 'average': None, 'baseVolume': 11857335.926087, 'quoteVolume': 37635.653576035, 'info': {'currency_pair': 'FTM3L_USDT', 'last': '0.163', 'lowest_ask': '0.16749', 'highest_bid': '0.16562', 'change_percentage': '7625.11', 'base_volume': '11857335.926087', 'quote_volume': '37635.653576035', 'high_24h': '0.16678', 'low_24h': '0.00182', 'etf_net_value': '0.16702788', 'etf_pre_net_value': '0.13489234', 'etf_pre_timestamp': '1653571080', 'etf_leverage': '2.0498848630104796'}}
```

The math there (in `safe_ticker`) went to my best understanding like this:
```
change = percentage/last*100 = 7625.11*0.163/100 = 12.4289293
open = last - change = 0.163 - 12.4289293 = -12.2659293
```
Whereas the correct way do it would be:
```
change = last*percentage/(100 + percentage) = 0.163*7625.11/(100 + 7625.11) = 0.16088999768
open = last - change = 0.163 - 0.16088999768 = 0.00211000232
```

It should be pretty easy and fast to fix the change calculation there. The other issues in `safe_ticker` might take a little bit more time...

**Comment by kroitor** [comment]
@JovianMoon thanks for your feedback, we'll fix this asap.

**Comment by kroitor** [comment]
@JovianMoon let us know if it works better for you with 1.84.20+. Thanks for your feedback!

**Comment by JovianMoon** [comment]
@kroitor Yes, now the math that `safe_ticker` does do looks better. As a consequence of the fix it does not anymore try to calculate 'change' and 'open' from 'last' and 'percentage' for gate.io for instance. I will stay tuned for math to be added for the missing values in the future.

Btw, removal of the legacy code from `safe_ticker` seems to have made `fetch_tickers` calls work with `exchange.number=str` for all exchanges now without throwing any exceptions, which seems promising.

**Comment by JovianMoon** [comment]
@ttodua I would not yet consider this issue fully solved. More specifically, `safe_ticker` could calculate some of the missing values using the formulas given above. Take for example SHIB/USDT ticker from latoken exchange:
```
{'symbol': 'SHIB/USDT', 'timestamp': 1730216662143, 'datetime': '2024-10-29T15:44:22.143Z', 'low': None, 'high': None, 'bid': '0.0000188291', 'bidVolume': '55502053', 'ask': '0.0000188403', 'askVolume': '375964607', 'vwap': '0.000018248409264678', 'open': None, 'close': '0.000018830000000000', 'last': '0.000018830000000000', 'previousClose': None, 'change': None, 'percentage': '10.5700', 'average': None, 'baseVolume': '419035321927.000000000000000000', 'quoteVolume': '7646728.050880009100000000', 'info': {'symbol': 'SHIB/USDT', 'baseCurrency': 'b209e09c-7f95-403c-9b2d-1b8086472673', 'quoteCurrency': '0c3a106d-bde3-4c13-a26e-3fd2394529e5', 'volume24h': '7646728.050880009100000000', 'volume7d': '22063953.380369867000000000', 'change24h': '10.5700', 'change7d': '3.2300', 'amount24h': '419035321927.000000000000000000', 'amount7d': '1258282473614.000000000000000000', 'lastPrice': '0.000018830000000000', 'lastQuantity': '27133638.000000000000000000', 'bestBid': '0.0000188291', 'bestBidQuantity': '55502053', 'bestAsk': '0.0000188403', 'bestAskQuantity': '375964607', 'updateTimestamp': '1730216662143'}, 'indexPrice': None, 'markPrice': None}`
```
'change', 'open' and 'average' could all have been calculated from 'last' and 'percentage' given that those values are correct. Instead, they all have value `None`. The same thing applies to many other exchanges. My other old issue #13487 should give an idea how common it is.

I think the goal should be to calculate the missing values whenever mathematically possible, as is already done in some specific cases. Of course, there is a risk that resulting numbers would be complete garbage if the known numbers had been misinterpreted or are otherwise wrong. I understand though if you have decided that "going all in" would be too risky or not worth the time.

**Comment by ttodua** [comment]
@JovianMoon I had seen your #13487 and I'm working on updates for fetch-tickers tests. I'll lyk once it gets merged
