### ISSUE TITLE
Bybit set a trailing stop

### ISSUE THREAD

**Issue by Parcanss** [ccxt/ccxt#13325]
I'm looking to set a trailing stop when creating a Bybit order. I added the parameters to create order, nothing errors the order goes through fine but there is no trailing stop set. 

I looked through the Bybit docs and came across [trading stop](https://bybit-exchange.github.io/docs/inverse/#t-tradingstop). I'm unsure if this method is in ccxt? 

```
let params = {
	'time_in_force': 'GoodTillCancel',
	'take_profit': takeProfit,
	'trailing_stop': 10,
	'new_trailing_active': stopLoss
}
await bybit.createOrder(symbol, 'market', side, qtyToUse, 0, params)
```
Using CCXT with NodeJS.

**Comment by carlosmiei** [comment]
Hello @Parcanss,

Currently, this is not available through our unified methods but you can always set a trading stop using the implicit API.

Example:

```Javascript

let params = {
        'symbol':  symbol // exchange-specific symbol here
	'take_profit': takeProfit,
	'trailing_stop': 10,
	'new_trailing_active': stopLoss
}
await bybit.privatePostV2PrivatePositionTradingStop(params);

```
