### ISSUE TITLE
Is Bybit Spot working now?

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#13341]
Hey developers team! First of all, I want to say eternals thanks to you for creating this library. It helps me to create my trading robot which includes mexc, binance, kucoin, huobi, gateio and bybit. Love you.

But with bybit-spot i got a problem. It refuses to show actual balance, to make market buy and sell orders and etc what is about spot. With futures everything is more than perfect. So is bybit Spot works now? Like an any other spot exchange on ccxt?

**Comment by carlosmiei** [comment]
Hello @KindSpidey, currently spot is not available but will be as soon as we merge this https://github.com/ccxt/ccxt/pull/13263, hopefully, today or tomorrow

**Comment by carlosmiei** [comment]
@KindSpidey, sorry I misread the question you should be able to fetch spot balances at this moment even without that merge. 

What do you get when you run:


```Python
    bybit = ccxt.bybit({
        "apiKey": config.BYBI.
        "secret": config.BYBIT_SECRET_KEY,
        "options": {'defaultType': 'spot' } # <---- spot here
    })
    print(bybit.fetch_balance())
```

**Comment by KindSpidey** [comment]
Yep, it works. Got my spot balance

**Comment by KindSpidey** [comment]
Waiting for making orders complete. I've did it through official API, but there's several problems with it. Hope with ccxt library it will work without errors and occasions

**Comment by carlosmiei** [comment]
@KindSpidey as I said the order update will be available very soon
