### ISSUE TITLE
The wiki page took too long to render

### ISSUE THREAD

**Issue by legitalk** [ccxt/ccxt#13358]
Url https://github.com/ccxt/ccxt/wiki/Manual#canceling-orders is showing:

The wiki page took too long to render.
This wiki page’s content is too large to render on this page.

Can you please fix this? Thank you.

**Comment by kroitor** [comment]
Yes, will fix this bug by breaking it into shorter files asap. In the meantime you can use this newer working mirror: https://docs.ccxt.com

**Comment by ttodua** [comment]
_duplicate of: https://github.com/ccxt/ccxt/issues/13453_
