### ISSUE TITLE
Can you fix minimum and maximum amount in Huobi Futures (and in Futures in general) in ccxt?

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#13362]
I want to show you some examples of how limitations (of ccxt?) of amount ruins code and transforms it into monster. Example will be on Huobi Futures.

First i want to show healthy work of making order, I have 5.04 dollars and i want to buy GMT. Calculations shows me that with my balance and 5X leverage i can buy 17 GMT, Ok, thats great, mobile application of Huobi shows the same numbers, And there is no problem with buying.

Then the hell is starting, I want to buy SHIB. Official application tells me it will take 2millions+ tokens of Shib. Ok, last time with GMT i sent GMT numbers, that was great. But NOW in code i will get this error `huobipro {"status":"error","err_code":1041,"err_msg":"The order amount exceeds the limit (1600000Cont), please modify and order again.","ts":1653055618866}`
WHAT?!

Opposite, if I try to buy token which amount will be less than 1, it will bring `huobipro {"status":"error","err_code":1040,"err_msg":"Invalid amount, please modify and order again.","ts":1653055796135}`

Do you know how I did fix buying big pricing active? By this:
```
                result = "1"
                if (amount<1):
                    for elem in str(amount).split("0"):
                        if elem == "" or elem == ".":
                            result += "0"
                        else:
                            suply_on_this__zeroes = int(result)
                            amount=math.floor(amount*suply_on_this__zeroes)
                            break
                else:
                    amount = math.floor(amount)
```
Should I do something like it with price<1 coins? And what i should do with others, because with GMT it was luck that conractsSize and GMT size were the same. How to calculate it? 

I understand that without you I won't create anything, and thank you for this library, but things like this,,,, And the most interesting part is that there are no same problems with Binance and Bybit. It only with Huobi (at least for now, didnt check gate and mexc).

![изображение_2022-05-20_190307564](https://user-images.githubusercontent.com/44064808/169544658-9a217795-7e7d-4783-adc2-2ab9e65c29eb.png)
![изображение_2022-05-20_191412189](https://user-images.githubusercontent.com/44064808/169546852-cd387fba-769b-46be-8f79-19a97602802d.png)

**Comment by ttodua** [comment]
you should check two things when you trade on leverage markets. for each `markets` object, check:
```
const mktObj = exchange.market ('GMT/USDT:USDT');
console.log (mktObj);
```
and there check `contractSize` and `limits` properties. That might help.
let us know if that solves your issue.
