### ISSUE TITLE
Binance Futrues - STOP MARKET - Position Take Pofit 

### ISSUE THREAD

**Issue by esteban2006** [ccxt/ccxt#13372]
I would like to know how to create a position take profit , is it posible?

- OS: Windows 10
- Programming Language version: Python 3.10.1
- CCXT version: 1.83.11

```
class Main():
    def __init__(self):
        self.window = None
    
    def futurePlaceOrder(self, symbol, type, side, amount, price=None, params={}):
        o = self.binanceFuture.createOrder (symbol, type, side, amount, price, params)
        return (o)

if __name__ == '__main__':
    symbol = 'BTC/USDT'
    type = 'STOP_MARKET'
    side = 'BUY'
    amount = 100
    params = None
    main = Main()

    STOP_MARKET =  (main.futurePlaceOrder(
        symbol = 'BTC/USDT',
        type = 'STOP_MARKET',
        side = 'BUY',
        amount = 0.003,
        params = {
            'stopPrice': '30100',
            'closePosition': False
        }
    ))

```

```
Changing this to a question
```

**Comment by sc0Vu** [comment]
May I ask what do you mean take profit?

**Comment by esteban2006** [comment]
@sc0Vu Thank you for asking, Binance has an option name “Take Profit Order”,  you can read the description here [How to Place Stop Loss Order and Take Profit Order](https://www.binance.com/en/support/faq/360040016512), so I was wondering if that is posible to do with CCXT, the main usage is that the all other orders will be automatically be cancelled after the “Take Profit Order” is FILLED and close. thank you

**Comment by kroitor** [comment]
@esteban2006 yes, CCXT does support all that, for example:

- https://github.com/ccxt/ccxt/blob/master/examples/php/binance-create-order-stop-loss-take-profit.php

**Comment by kroitor** [comment]
@esteban2006 you can see more about the supported order types here: 

- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L2837

Example:

- https://github.com/ccxt/ccxt/blob/master/examples/py/binance-stop-loss-take-profit.py

```Python
# -*- coding: utf-8 -*-

import ccxt

exchange = ccxt.binanceusdm({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

markets = exchange.load_markets()
# exchange.verbose = True  # uncomment for debugging purposes

symbol = 'BTC/USDT'
side = 'buy'
amount = 0.01
price = None
stopLossPrice = 25000
takeProfitPrice = 35000

try:

    order = exchange.create_order(symbol, 'MARKET', side, amount)
    print(order)

    inverted_side = 'sell' if side == 'buy' else 'buy'

    stopLossParams = {'stopPrice': stopLossPrice}
    stopLossOrder = exchange.create_order(symbol, 'STOP_MARKET', inverted_side, amount, price, stopLossParams)
    print(stopLossOrder)

    takeProfitParams = {'stopPrice': takeProfitPrice}
    takeProfitOrder = exchange.create_order(symbol, 'TAKE_PROFIT_MARKET', inverted_side, amount, price, takeProfitParams)
    print(takeProfitOrder)

except Exception as e:
    print(type(e).__name__, str(e))
```

**Comment by esteban2006** [comment]
@kroitor thank u for the response, the examples are to the dot, I have to add that,  TAKE_PROFIT_MARKET will turn into a stop loss  or take profit order depending on you order price compared to the current maket price, and that will make this order powerfull, can think of it like an OCO for Binance Future or a TRAILING STOP everytime the market goes up even 1 penny
