### ISSUE TITLE
New Exchange: komodoplatform (BarterDex)

### ISSUE THREAD

**Issue by ericvrp** [ccxt/ccxt#1337]
Are there plans to support decentralized exchanges like BarterDex?

https://www.komodoplatform.com/en/technology/barterdex

**Comment by kroitor** [comment]
> Are there plans to support decentralized exchanges like BarterDex?

Yes. In general, there are plans to support all of them ;)

**Comment by jjhesk** [comment]
api doc: http://docs.supernet.org/#introduction
url: https://www.komodoplatform.com
fee: --
volume:  --
address: --
company info: --
Registration: --
based country:--
whitepaper: https://www.komodoplatform.com/en/technology/whitepaper/2018-01-18-Komodo-White-Paper-Full.pdf
priority: low
github group: https://github.com/KomodoPlatform
note: ranked top : NA

**Comment by frosty00** [comment]
not clear where the apidocs are or what the exchange is
