### ISSUE TITLE
Is it possible to make market orders on Gateio Futures?

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#13379]
I use only limits, but markets are better. It is possible in their app, but is it possible in their API and ccxt?

**Comment by carlosmiei** [comment]
Hello @KindSpidey, yes market orders are available for futures using Gateio's API

**Comment by KindSpidey** [comment]
Thanks! Really works

**Comment by KindSpidey** [comment]
By the way, what's about Bybit spot?

**Comment by carlosmiei** [comment]
@KindSpidey was already merged so if you update your ccxt version you should be able to/create/edit/cancel/Orders using spot markets 🙂

**Comment by KindSpidey** [comment]
Ohhh, thats great! Love u guys
