### ISSUE TITLE
bybit.py of async version fetch_order() returns coroutine object. 

### ISSUE THREAD

**Issue by kjnh10** [ccxt/ccxt#13383]
- OS: Linux
- Programming Language version: python 3.8.3
- CCXT version: 1.83.42

``` my code
import ccxt.async_support as ccxt
bybit = ccxt.bybit({'api_key': '', 'secret': ''})

async def exec():
     id = # get id from order already submitted
     symbol = # same as above
     result1 = await bybit.fetch_order(id=id, symbol=symbol)
     print(result1)

asyncio.run(exec())
```

``` output
<coroutine object bybit.fetch_orders at 0x7f7f35081f40>
```

**Comment by kroitor** [comment]
@kjnh10 thanks for pointing it out, we have pushed a fix for it in CCXT 1.83.44, the new build will arrive in ~20 minutes. Please, let us know if that solves the issue for you or not after upgrading to the most recent version in 20 minutes. Thank you!

**Comment by kjnh10** [comment]
@kroitor 
I'm using python version. It seems that 0233a5d is for javascript only, right?

**Comment by kroitor** [comment]
> @kroitor I'm using python version. It seems that [0233a5d](https://github.com/ccxt/ccxt/commit/0233a5db2fb839aaff96dabde32aecbb7c1688ed) is for javascript only, right?

Py/PHP are built automatically: 

- https://github.com/ccxt/ccxt/wiki/FAQ#hey-the-fix-youve-uploaded-is-in-js-would-you-fix-python--php-as-well-please
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

**Comment by kjnh10** [comment]
Oh great, thanks.
And maybe fetch_order() return the result as a list (not dict). I checked this by awaiting the result of fetch_order().
This is because fetch_order() use fetch_orders().

So should use return fetch_orders()[0], right?

**Comment by kroitor** [comment]
> @kroitor Oh great, thanks. And maybe fetch_order() return the result as a list (not dict). I checked this by awaiting the result of fetch_order(). This is because fetch_order() use fetch_orders().
> 
> So should use return fetch_orders()[0] or something, right?

Yes, you're right, will fix that as well.

**Comment by kjnh10** [comment]
@kroitor 
1.83.44 works fine for me. Thanks for your quick action.
