### ISSUE TITLE
ccxt fetchbalances() returns SPOT balance by default

### ISSUE THREAD

**Issue by flieks** [ccxt/ccxt#13382]
How can i get the futures balance with fetchBalance() now ?

My regular fetchBalances() call without parameters is now translated to
https://api.bybit.com/spot/v1/account?

How can i get FUTURES ?

**Comment by kroitor** [comment]
```Python
import ccxt
from pprint import pprint
exchange = ccxt.bybit({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'options': {'defaultType': 'swap'},
})
balance = exchange.fetch_balance()
pprint(balance)
```

> My regular fetchBalances() call without parameters is now translated to https://api.bybit.com/spot/v1/account?

Will fix that shortly.

**Comment by xmatthias** [comment]
@kroitor bybit is now the only "non-futures" exchange that uses "non-spot" as defaultType.

The only other exchanges which don't default to spot are `binanceusdm`, `binancecoinm` and `kucoinfutures` (and `xena` - but they don't have spot if i see that correctly).

As such - i think the correct way for this would be to 
* leave bybit as spot
* add a `bybitfutures` exchange (if you think there must be a "futures" variant) - or have people default to using `{'defaultType': 'swap'}` (which would be the aligned way if we look at it from an "all exchanges" perspective).

**Comment by kroitor** [comment]
> @kroitor bybit is now the only "non-futures" exchange class that uses "non-spot" as defaultType.
> 
> The only other exchanges which don't default to spot are `binanceusdm`, `binancecoinm` and `kucoinfutures` (all have a spot counterpart in ccxt) and `xena` - but they don't have spot if i see that correctly.
> 
> As such - i think the correct way for this would be to
> 
> * default bybit defaultType to spot
> * add a `bybitfutures` exchange (if you think there must be a "futures" variant) - or have people default to using `{'defaultType': 'swap'}` (which would be the aligned way if we look at it from an "all exchanges" perspective).

Bybit is actually a futures-mostly exchange. They have added the spot API not so long ago, and they only had inverse and perpetual contracts before. That is the reason why bybit defaults to swap markets, cause the exchange is mostly a contracts-exchange, like deribit.
