### ISSUE TITLE
FTX: can't get fees for market order

### ISSUE THREAD

**Issue by CodingCryptoTrading** [ccxt/ccxt#13398]
Hi, 
I don't get the fee structure for market orders when I use FTX, while I do get it when I use Binance. Is it normal?

Here an example of an FTX market order:

```
[
    {
        "info": {
            "id": "148627082576",
            "clientId": null,
            "market": "BTC/USD",
            "type": "market",
            "side": "buy",
            "price": null,
            "size": "0.0001",
            "status": "closed",
            "filledSize": "0.0001",
            "remainingSize": "0.0",
            "reduceOnly": false,
            "liquidation": false,
            "avgFillPrice": "29919.0",
            "postOnly": false,
            "ioc": true,
            "createdAt": "2022-05-22T20:00:01.204790+00:00",
            "future": null
        },
        "id": "148627082576",
        "clientOrderId": null,
        "timestamp": 1653249601204,
        "datetime": "2022-05-22T20:00:01.204Z",
        "lastTradeTimestamp": null,
        "symbol": "BTC/USD",
        "type": "market",
        "timeInForce": "IOC",
        "postOnly": false,
        "side": "buy",
        "price": 29919.0,
        "stopPrice": null,
        "amount": 0.0001,
        "cost": 2.9919,
        "average": 29919.0,
        "filled": 0.0001,
        "remaining": 0.0,
        "status": "closed",
        "fee": null,
        "trades": [],
        "fees": []
    }
]
```

Thanks

**Comment by kroitor** [comment]
> Hi, I don't get the fee structure for market orders when I use FTX, while I do get it when I use Binance. Is it normal?

Yes, that is normal. Fees aren't a property of orders in general. They are a property of trades. Most of the exchanges will return fees in your private trades (`fetchMyTrades`). Some exchanges will also calculate the order trades for you, but not all of them:

- https://docs.ccxt.com/en/latest/manual.html#how-orders-are-related-to-trades

Hope that answers your question, let us know if not.

**Comment by CodingCryptoTrading** [comment]
Thanks for the clarification. 

Just one more thing. So, to get the paid fees what I can do is to run:
```
if exchange.has['fetchOrderTrades']:
    trades = exchange.fetch_order_trades(order_id, symbol=None, since=None, limit=None, params={})
```

It seems to work. However, what happens when the order is split into multiple trades? I guess in this case `trades` will be composed of multiple dictionaries (one for each trade). I can compute the total fee by summing the fee of each trade. Is that correct? Is there a better way to get the total fees of a market order?

Thanks

**Comment by CodingCryptoTrading** [comment]
Thanks!
