### ISSUE TITLE
Bybit Spot API, Perpetual Swaps, Futures, USDC contracts

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#13399]
# Good news everyone!

We are happy to announce the extended support for **[Bybit APIs](https://www.bybit.com/app/register?ref=X7Prm) in CCXT as of version 1.83.60+**

![bybit-logo-2021-1600-400](https://user-images.githubusercontent.com/1294454/169809374-e7ed371f-a529-4eac-80b6-dfa920b365ef.jpeg)

The following Bybit APIs are now supported in CCXT:

- Perpetual swaps (linear and inverse)
- Futures 
- Spot API
- USDC options and perpetuals

Please, find the source code examples here:

JavaScript:

- https://github.com/ccxt/ccxt/blob/master/examples/js/bybit-updated.js

Python:

- https://github.com/ccxt/ccxt/blob/master/examples/py/bybit-updated.py

PHP:

- https://github.com/ccxt/ccxt/blob/master/examples/php/bybit-updated.php

Your feedback and reports are very much appreciated!

Related issues and requests:

- ccxt/ccxt#13341
- ccxt/ccxt#13248
- ccxt/ccxt#13244
- ccxt/ccxt#13239
- ...

**Thanks for using CCXT!**

**Comment by alesha1488** [comment]
Bybit order status "PARTIALLY_FILLED". Must be "open"

**Comment by pulkitsharma** [comment]
exchange.options['defaultType'] = 'spot';
should be mentioned in the documentation.

**Comment by rsquared99** [comment]
Could you confirm what the correct defaultType should be for interacting with USDC options as it does not appear to be covered in the documentation.

Can you provide a working example in the code of opening an USDC option contract via market order in the documentation?

**Comment by ttodua** [comment]
> Could you confirm what the correct defaultType should be for interacting with USDC options as it does not appear to be covered in the documentation.
> 
> Can you provide a working example in the code of opening an USDC option contract position via market order in the documentation?

@sc0Vu have you worked on option contracts , or can you answer to this one? I dont remind, if not you, who worked on options recently.

**Comment by samgermain** [comment]
> 

ask @Dan-krm

**Comment by Dan-krm** [comment]
> Could you confirm what the correct defaultType should be for interacting with USDC options as it does not appear to be covered in the documentation.
> 
> Can you provide a working example in the code of opening an USDC option contract position via market order in the documentation?

I'll look into this for you and create an example

**Comment by Dan-krm** [comment]
> Could you confirm what the correct defaultType should be for interacting with USDC options as it does not appear to be covered in the documentation.
> 
> Can you provide a working example in the code of opening an USDC option contract position via market order in the documentation?

You can check our naming conventions for options here: https://docs.ccxt.com/en/latest/manual.html#option

For options the symbol naming convention is:
`BASE/QUOTE:SETTLE-EXPIRY-STRIKE-TYPE`
`BTC/USD:USDC-221209-18000-C`

The defaultType can be set to 'option'

I've opened a PR that provides an example order on bybit here: #15816
```
exchange = ccxt.bybit ({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
    'defaultType': 'option',
    # 'verbose': True,  # for debug output
})

# BTC/USD:USDC-YYMMDD-STRIKE-C
symbol = 'BTC/USD:USDC-221209-18000-C'
amount = 0.01

try:
    order = exchange.create_order(symbol, 'market', 'buy', amount)
    pprint(order)
except Exception as err:
    print(err)
```

If you have any other questions or notice any missing features for Bybit options feel free to open a separate issue

**Comment by qingliisacutie** [comment]
Help~~~~~ How can I fetch the perpetual swaps prices of all the coins?

The symbol is a bit hard to identify, here is my inperfect code which cannot achieve but almost, thanks very much for the help!!!
"import ccxt
import time

def fetch_perpetual_swap_prices():
    # 创建 Bybit 实例
    bybit = ccxt.bybit({
        'enableRateLimit': True,  # 启用速率限制
    })

    # 加载市场
    bybit.load_markets()

    # 获取所有永久合约的价格
    prices = {}
    try:
        # 遍历所有市场，找到永久合约
        for symbol, market in bybit.markets.items():
            # 检查市场类型为 swap
            if market['type'] == 'swap':
                # 进一步筛选出 Perpetual Swaps
                if 'perpetual' in symbol.lower():  # 假设合约符号中包含 "perpetual"
                    try:
                        ticker = bybit.fetch_ticker(symbol)
                        prices[symbol] = ticker['last']  # 存储最新价格
                        print(f"{symbol}: {ticker['last']}")  # 打印每个永久合约的价格
                    except Exception as e:
                        print(f"Error fetching ticker for {symbol}: {e}")
                time.sleep(1)  # 增加请求间隔
    except Exception as e:
        print(f"Error fetching data: {e}")
        return None

    return prices

# 使用示例
if __name__ == "__main__":
    all_prices = fetch_perpetual_swap_prices()
    if all_prices is not None:
        print("All perpetual swap prices fetched successfully.")
        print("\nFetched Prices:")
        for symbol, price in all_prices.items():
            print(f"{symbol}: {price}")  # 打印所有抓取到的价格"
