### ISSUE TITLE
Auto retry call

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#13392]
Hello, 

Will ccxt  add support auto retry call a function for case with network issue? 
For example by default retry parameters could be 
1) retry_attempts = 0
2) retry_period = 2 sec

**Comment by kroitor** [comment]
CCXT does not have a built-in function for that, but you can easily code it in the userland:

```JavaScript
    async retry (exchange, attempts, delay, method, ... args) {
        for (let i = 0; i < attempts; i++) {
            try {
                return await exchange[method] (... args)
            } catch (e) {
                // retry
                await exchange.sleep (delay) // delay in milliseconds
            }
        }
        throw new ccxt.ExchangeError (exchange.id + ' ' + method + ' () failed after ' + attempts.toString () + ' attempts')
    }
```

**Comment by YuriyTigiev** [comment]
I had the similar approach, but question is - could we implement this code on the library level?

**Comment by YuriyTigiev** [comment]
What is equivalent of code for  python for the string - `return await exchange[method] (... args)`

**Comment by kroitor** [comment]
Python async:

```Python
    async def retry(exchange, attempts, delay, method, *args):	
        for i in range(0, attempts):	
            try:	
                return await getattr(exchange, method)(*args)	
            except Exception as e:	
                # retry	
                await exchange.sleep (delay)  # delay in milliseconds
        raise ExchangeError(exchange.id + ' ' + method + ' () failed after ' + str(attempts) + ' attempts')
```

Python sync:

```Python
    def retry(exchange, attempts, delay, method, *args):	
        for i in range(0, attempts):	
            try:	
                return getattr(exchange, method)(*args)	
            except Exception as e:	
                # retry	
                exchange.sleep(delay)  # delay in milliseconds	
        raise ExchangeError(exchange.id + ' ' + method + ' () failed after ' + str(attempts) + ' attempts')
```

**Comment by YuriyTigiev** [comment]
Does current version of library support auto reconnect?

**Comment by kroitor** [comment]
@YuriyTigiev CCXT Pro does auto-reconnection with the WS API, and CCXT is a RESTful API.

**Comment by YuriyTigiev** [comment]
It's means I don't need to use previous code if I use ccxt.pro. Correct ?

**Comment by kroitor** [comment]
> It's means I don't need to use previous code if I use ccxt.pro. Correct ?

Nope, the above code is not a part of CCXT or CCXT Pro. The code above does not handle reconnections, it just handles a number of attempts/retries on HTTPS failures, if any. Don't confuse retry-calls over HTTPS with reconnections over WS, they're different things. The code above does not involve any type of connection at all. CCXT Pro is using WS connections, but that is not related to the above code either.

**Comment by YuriyTigiev** [comment]
when approximately ccxt.pro will be free to use ?
