### ISSUE TITLE
fetch_tickers() doesn't work for FTX futures products

### ISSUE THREAD

**Issue by serteikas** [ccxt/ccxt#13401]
ccxt=1.83.66, FTX exchange

When using fetch_tickers for multiple symbols, ex:

`exchange.fetch_tickers(["BTC-PERP", "BNB-PERP"])` **-> Empty**

However, when using fetch_ticker with each individual ticker, ex:

`exchange.fetch_ticker("BTC-PERP")` **-> Fine**
`exchange.fetch_ticker("BNB-PERP")` **-> Fine**

Spot market products seem to work fine though, ex:

`exchange.fetch_tickers(["BTC/USDT", "BNB/USDT"])` **-> Fine**

Is this a specific issue with FTX perpetual futures where you can only query one symbol at a time?

**Comment by kroitor** [comment]
Please, read this:

- https://docs.ccxt.com/en/latest/manual.html#contract-naming-conventions
- https://github.com/ccxt/ccxt/issues/10931

```
exchange.fetch_tickers(['BTC/USD:USD', 'BNB/USD:USD'])
```

Let us know if that does not answer your question.

**Comment by kroitor** [comment]
@serteikas if you upgrade to CCXT 1.83.67+, then `exchange.fetch_tickers(["BTC-PERP", "BNB-PERP"])` will also work (the new build will arrive in ~20 minutes).
