### ISSUE TITLE
Handling Poloniex 422 Unprocessable Entity

### ISSUE THREAD

**Issue by kornrunner** [ccxt/ccxt#1340]
- OS: archlinux
- Programming Language version: php
- CCXT version: 1.10.749
- Exchange: poloniex
- Method: privatePostReturnDepositsWithdrawals

I've mistakingly issued a request that did not contain required params. 

It resulted in [HTTP 422](https://httpstatuses.com/422), which should translate to `Unprocessable Entity`, but because of [Exchange.php#L859](https://github.com/ccxt/ccxt/blob/master/php/Exchange.php#L859)
it returned `ExchangeError`, with message `422 not accessible from this location at the moment` (which is misleading).

Perhaps this code shouldn't be in that array?

**Comment by kroitor** [comment]
@kornrunner yes, looks like it shouldn't be there, indeed... Feel free to move it to another else-case, or remove it. Would you want to submit a PR on this? If not, I can edit that, no worries. Let me know. Thx!

**Comment by kornrunner** [comment]
I'll try to handle it, just wanted to hear from you first. Thanks!

**Comment by kroitor** [comment]
Fixed in #1342, thank you for your help, @kornrunner !
