### ISSUE TITLE
Kraken how to query all items with fetchLedger?

### ISSUE THREAD

**Issue by steebchen** [ccxt/ccxt#13414]
fetchLedger for kraken seems to return 50 items, but how would I query it?

The custom `ofs` option actually seems to work, but I'm wondering why my code below doesn't work.

Is it because kraken returs the latest trades, instead of older ones first? This doesn't make much sense to me though...

- OS:
- Programming Language version:
- CCXT version: 1.83.71

```
const kraken = new ccxt.kraken({
	apiKey: process.env.KRAKEN_PUBLIC_KEY,
	secret: process.env.KRAKEN_PRIVATE_KEY,
	enableRateLimit: true,
})

ledger(kraken)

async function ledger(exchange: ccxt.Exchange) {
	let items = []
	let types = {}

	let since = exchange.parse8601('2015-01-01T00:00:00Z')
	while (since > exchange.milliseconds()) {
		const txs = await kraken.fetchLedger(undefined, since)
		if (!txs.length) {
			break
		}
		console.log(txs)
		console.log(txs.length)
		for (const item of txs) {
			types[item.type] = (types[item.type] || 0) + 1
		}
		items.push(...txs)

		since = txs[txs.length - 1].timestamp + 1
	}

	console.log('types:', types)
	console.log('total:', items.length)
}
```

```
fetching 1420070400000
[
  {
    info: {
      aclass: 'currency',
      amount: '-0.00010453',
      asset: 'USDT',
      balance: '0.00000021',
      fee: '0.00000000',
....
50
fetching 1652343926291
types: { trade: 35, transaction: 15 }
total: 50
```

Here ^ it stops after using the latest date, so I guess kraken returns the latest trades instead of the earliest? How can I query th trades by earliest first though so it works with this default pagination?

**Comment by pcriadoperez** [comment]
Hi @steebchen , correct Kraken's api returns the 50 most recent ledger entries, and unfortunately it doesn't allow to query in the reverse order. (https://docs.kraken.com/rest/#operation/getLedgers)

To get older entries you could use kraken's parameter `ofs` to incorporate pagination, and go as far back as you need or the api allows you.
```javascript
    const txs = await kraken.fetchLedger(undefined, since, 50, {'ofs':50})
 ```
And then with the results sort them from oldest to newest.

**Comment by steebchen** [comment]
Yeah, thanks for the comment. It's a bit frustrating that there is not really an overview of what works with fetchLedger and what doesn't. Right now I'm using fetchDeposits/fetchWithdrawals/etc. by default, but when fetchLedger is available, I just use that. This works for some, but then it falls apart for Kraken. I'm wondering if there could be something added to ccxt to mark methods in specific exchanges as incompleted or something

**Comment by steebchen** [comment]
I realised this is similar with other exchanges, like Bitfinex: https://docs.bitfinex.com/reference/rest-auth-ledgers

It seems the best way to query for this data is by somehow going from future to past using `start` and `end`

**Comment by steebchen** [comment]
I'm doing something like this now to go through Bitfinex/Kraken, and add some specifics for Kraken. Will see how it goes for other exchanges.

```
const begin = exchange.parse8601('2015-01-01T00:00:00Z')
const types = {}
let end = exchange.milliseconds()
let start = exchange.parse8601(scannedAt.toISOString())
while (begin < end) {
	const txs = await exchange.fetchLedger(undefined, start, undefined, {
		end: exchange.name === 'Kraken' ? end / 1000 : end,
	})
	if (!txs.length) {
		break
	}
	onTransactions(transformLedger(txs))

	if (end === txs[0].timestamp) {
		break
	}
	end = txs[0].timestamp
}
```
