### ISSUE TITLE
Bybit spot (testnet) - Order price decimal too long.

### ISSUE THREAD

**Issue by szwagros** [ccxt/ccxt#13416]
- OS: Linux
- Programming Language version: php 8
- CCXT version: 1.83.69

```
$e = new \ccxt\bybit([
'apiKey' => '',
'secret' =>'',
'timeout' => 30000,
'enableRateLimit' => true,
'options' => ['defaultType' => 'spot']]
);

$e->set_sandbox_mode(true);
$e->load_markets();

$e->create_order('BTC3S/USDT', 'limit', 'buy', 1.0, $e->price_to_precision('BTC3S/USDT',18.0331288));

```

```
ccxt\ExchangeError with message 'bybit {"ret_code":-1134,"ret_msg":"Order price decimal too long.","ext_code":null,"ext_info":null,"result":null}'

```

**Comment by kroitor** [comment]
@szwagros do you have this issue with the following code:

```PHP
$e = new \ccxt\bybit([
'apiKey' => '',
'secret' =>'',
'timeout' => 30000,
'enableRateLimit' => true,
'options' => ['defaultType' => 'spot']]
);

$e->set_sandbox_mode(true);
$e->load_markets();
$e->verbose = true;
$e->create_order('BTC3S/USDT', 'limit', 'buy', 1.0, 18.0331288);
```

If you still have this issue with the above edit (CCXT should handle the formatting for you) – please paste your verbose output.

**Comment by szwagros** [comment]
Yes issue is still present:


>>> $e->verbose = true;
=> true
>>> $e->create_order('BTC3S/USDT', 'limit', 'buy', 1.0, 18.0331288);
Array
(
    [0] => fetch Request:
    [1] => bybit
    [2] => POST
    [3] => https://api-testnet.bybit.com/spot/v1/order
    [4] => RequestHeaders:
    [5] => Array
        (
            [Content-Type] => application/x-www-form-urlencoded
        )

    [6] => RequestBody:
    [7] => symbol=BTC3SUSDT&side=Buy&type=LIMIT&timeInForce=GTC&qty=1&price=18.0331288&agentSource=CCXT&api_key=api_key&recv_window=5000&timestamp=1653425347729&sign=sign
)
Array
(
    [0] => fetch Response:
    [1] => bybit
    [2] => POST
    [3] => https://api-testnet.bybit.com/spot/v1/order
    [4] => 200
    [5] => 
    [6] => ResponseHeaders:
    [7] => Array
        (
            [Content-Type] => application/json;charset=UTF-8
            [Content-Length] => 106
            [error_code] => -1134
            [Server] => T-GATEWAY
            [Expires] => Tue, 24 May 2022 20:49:08 GMT
            [Cache-Control] => max-age=0, no-cache, no-store
            [Pragma] => no-cache
            [Date] => Tue, 24 May 2022 20:49:08 GMT
            [Connection] => keep-alive
        )

    [8] => ResponseBody:
    [9] => {"ret_code":-1134,"ret_msg":"Order price decimal too long.","ext_code":null,"ext_info":null,"result":null}
)
ccxt\ExchangeError with message 'bybit {"ret_code":-1134,"ret_msg":"Order price decimal too long.","ext_code":null,"ext_info":null,"result":null}'

**Comment by kroitor** [comment]
@szwagros ok, i've pushed a fix, please, upgrade your version of the lib to 1.83.78 (the new build will arrive in ~20 minutes) and let me know if that solves the issue for you or not. Thanks for your feedback!

**Comment by szwagros** [comment]
Yes now orders are created. Thank you! But I've noticed strange thing (maybe it's just bybit testnet "feature"). Every market buy returns with status Canceled (both from websocket or when using fetch_closed_orders). Here is output from fetch_closed_orders :

```
     [
       "info" => [
         "accountId" => "174714",
         "exchangeId" => "301",
         "symbol" => "BTC3SUSDT",
         "symbolName" => "BTC3SUSDT",
         "orderLinkId" => "1653504200566",
         "orderId" => "1164072042557875200",
         "price" => "0",
         "origQty" => "20",
         "executedQty" => "1.106",
         "cummulativeQuoteQty" => "19.9982496",
         "avgPrice" => "18.0816",
         "status" => "CANCELED",
         "timeInForce" => "GTC",
         "type" => "MARKET",
         "side" => "BUY",
         "stopPrice" => "0.0",
         "icebergQty" => "0.0",
         "time" => "1653504201181",
         "updateTime" => "1653504201334",
         "isWorking" => true,
       ],
       "id" => "1164072042557875200",
       "clientOrderId" => "1653504200566",
       "timestamp" => 1653504201181.0,
       "datetime" => "2022-05-25T18:43:21.181Z",
       "lastTradeTimestamp" => 1653504201334,
       "symbol" => "BTC3S/USDT",
       "type" => "market",
       "timeInForce" => "IOC",
       "postOnly" => false,
       "side" => "buy",
       "price" => 18.0816,
       "stopPrice" => "0.0",
       "amount" => 20.0,
       "cost" => 19.9982496,
       "average" => 18.0816,
       "filled" => 1.106,
       "remaining" => 18.894,
       "status" => "canceled",
       "fee" => null,
       "trades" => [],
       "fees" => [],
     ],
   ]

```
and here is info regarding the same order from bybit orders history page:



```
Spot Pairs	Order Type	Direction	Order Value		Avg. Filled Price	Filled Qty	Order Price	Order Qty	Order Value		Order Status		Order Time		Order ID
BTC3S/USDT	Market		Buy		19.99824960 USDT	18.0816 USDT		1.1060 BTC3S	Market		--		20.00000000 USDT	Partially Filled	2022-05-25 20:43:21	57875200


```
Notice that status is "Partially Filled" and there is no Order Qty.

**Comment by kroitor** [comment]
@szwagros as you can see from the info above, the status is coming from the exchange API (the testnet) directly, first hand – the `info` field contains the order structure returned from the exchange as is, untouched. And it says, `"status" => "CANCELED"`, so that is what the exchange API says. This is not an issue in CCXT, but it could be a peculiarity of the Bybit testnet.

**Comment by szwagros** [comment]
Sure. I was just pointing out difference between order status in bybit gui and api response. Btw. there is probably bug in timeInForce field parsing - API returns  GTC a ccxt return IOC.

**Comment by DoctorSlimm** [comment]
@szwagros what endpoint/on what kind of order are you seeing the `timeInForce` parsing error? so that I can reproduce it, thanks
