### ISSUE TITLE
Today's Profit - 3Commas stats

### ISSUE THREAD

**Issue by birk151** [ccxt/ccxt#13415]
- OS: Mojave
- Programming Language version: Py 3.10.1
- CCXT version: 1.72.37

Searching for CCTX command to fetch 'today's profit' amount from 3Commas bot stats (which is listed as "Today Profit:" on 3Commas Overall stats)

**Comment by ttodua** [comment]
I will mark this issue as `invalid` because there is no `3comma` implemented in CCXT, and furthermore `3comma`'s stats are out of scope. it's not even an exchange.

If you have more details about the issue you are experiencing with CCXT, let us know.
