### ISSUE TITLE
{"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}

### ISSUE THREAD

**Issue by joeevon** [ccxt/ccxt#13426]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:Python 3.9.10
- CCXT version: 1.83.71

```
May i hava pardon how solve this issue? And where can i read all error code?
```

```
{"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
```

**Comment by kroitor** [comment]
Make sure that you have configures your API keys correctly, please, check the following sections of the Manual:

- https://docs.ccxt.com/en/latest/manual.html#authentication
- https://docs.ccxt.com/en/latest/manual.html#troubleshooting

Also, please, check your API key settings on the exchange website (I suppose, Binance in this case, cause you have not specified it). Make sure that your IP has the permissions to use the key. Also, please, make sure that you have not used that key with the other software before.

Let us know if that does not answer your question. Feel free to reopen this issue or just ask further questions here if any.
