### ISSUE TITLE
TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation

### ISSUE THREAD

**Issue by mgroenouwe** [ccxt/ccxt#1343]
I'm using the <script type="text/javascript" src="https://unpkg.com/ccxt"></script>

Since build number 1.10.747 I'm getting an exception when I try to get the orderbook data from GDAX:
TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation

Loading balance data isn't working either, so I think nothing works anymore from 747 and up.

Tried to use a fixed version, and that worked:
<script type="text/javascript" src="https://unpkg.com/ccxt@1.10.746"></script>

Everything is working fine again with this version.

**Comment by kroitor** [comment]
Thanks for reporting will look into it and fix shortly.

**Comment by kroitor** [comment]
Fixed in current version 1.10.753. Let us know if you have any other difficulties with it. Thank you!
