### ISSUE TITLE
How can I add take_profit / stop_loss to a current position? 

### ISSUE THREAD

**Issue by YusakuFujiii** [ccxt/ccxt#13439]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Ubntu 20.04
- Programming Language version: python 
- CCXT version: 1.82.28

I am trying to add take profit / stop loss to my current position using : 

"""
bybit.editOrder(id='current position's id', symbol='BTCUSDT',type='limit',side='buy',params={'take_profit": 30000})
"""
This never causes any errors, but my current position stays with no take profit  price.

What should I do with this problem?  Thank you in advance.

**Comment by Dan-krm** [comment]
Hi, we're currently adding stop-loss and take-profit functionality to CCXT you can track the progress here: https://github.com/ccxt/ccxt/issues/13822
This is still in development so some things may change as we make progress with unifying SL/TP orders.

These PR's started work on adding this functionality to Bybit:
https://github.com/ccxt/ccxt/pull/13859
https://github.com/ccxt/ccxt/pull/13888

I don't think we have full functionality for Bybit or any of the exchanges yet, but you should be able to make a conditional order with a reduceOnly flag to create an order similar to what you're asking for the time being. That would be made using order type 1 or order type 2, the requirements for these types of orders can be referenced from this master issue of the SL/TP unification https://github.com/ccxt/ccxt/issues/13822

**Comment by YusakuFujiii** [comment]
I really appreciate you for your informative reply.
