### ISSUE TITLE
createStopOrder bybit error (stop_px/base_price required)

### ISSUE THREAD

**Issue by flieks** [ccxt/ccxt#13442]
Hi,

 I am doing this as test with Bybit exchange

```
const value = exchange.createStopOrder(
                symbol,
                'market',
                'buy',
                position,
                price,
                price * 0.9)
```

and i get this response: 

`bybit createOrder() requires both the stop_px and base_price params for a conditional market order`

Placing normal market or limit orders work fine with the same parameters except that last stopLoss parameter.

Greetings

**Comment by carlosmiei** [comment]
Hello @flieks, As the error message states Bybit requires an additional parameter in order to create stop/conditional orders which is the `base_price`.

Example:

```Javascript

const params = {
    'base_price': 3000 // random number use yours here
}

const value = exchange.createStopOrder(
                symbol,
                'market',
                'buy',
                position,
                price,
                price * 0.9,
                params )
```

More info on the base price:
![image](https://user-images.githubusercontent.com/43336371/170460344-77bc5e18-432e-41cb-9e68-4d05caf8511c.png)


Feel free to reopen it if anything!

**Comment by flieks** [comment]
Thanks @carlosmiei 
I tried is with XLMUSDT and it only creates a conditional order.
![image](https://user-images.githubusercontent.com/5032389/170671361-6ea51da5-1a71-4919-8959-c617e12e1d4e.png)

I thought this would create a market or limit order and then set a SL or TP on it..

**Comment by carlosmiei** [comment]
@flieks, If you want to place a sl/tp order it is a bit different, something like this (assuming it is a USDT contract):

```Python
const params = {
    'take_profit': 3000, # your take profit here
     'stop_loss': 1000 # your stop loss price here
}

const value = exchange.createOrder( # <-- using createOrder instead
                symbol,
                'market',
                'buy',
                amount,
                price,
                params )
```

**Comment by flieks** [comment]
@carlosmiei thanks that works. 

But like createStopOrder should work for other exchanges ? Bybit has it enabled TRUE in the echange.has list so maybe there is a bug there...
