### ISSUE TITLE
Wiki page "User Manual" could not be opened.

### ISSUE THREAD

**Issue by jinzongna** [ccxt/ccxt#13453]
The "User Manual" wiki page is too long to render. "The wiki page took too long to render." is displayed
Split it up may resolve the issue.
https://github.com/ccxt/ccxt/wiki/Manual

**Comment by kroitor** [comment]
We are working on a fix. Thanks! In the meantime, you can use this alternative mirror: https://docs.ccxt.com

**Comment by frosty00** [comment]
the github renderer has since been fixed
