### ISSUE TITLE
Question for selling an altcoin for bitcoin

### ISSUE THREAD

**Issue by ironexmaiden** [ccxt/ccxt#1345]
OS:Linux
Programming Language version:Python
CCXT version:1.10.586
Exchange:bleutrade
Method:create_limit_buy_order

I want to sell an alt coin for bitcoin but calling create_limit_sell_order or create_limit_buy_order raise the exception of insufficient funds

**Comment by kroitor** [comment]
Do you have sufficient funds to place the order? The exception states it clearly, you need to have `amount * price + fee` on your balance to place the order.

**Comment by ironexmaiden** [comment]
(amountOfBtc I want to buy)*priceOfAltcoinInBtc + fee right?

**Comment by kroitor** [comment]
Which pair are you trading?

**Comment by ironexmaiden** [comment]
I want to convert VRC to BTC

**Comment by kroitor** [comment]
Ok, the symbol is `VRC/BTC`, and the amount is always on the left (before the slash), the price is on the right (after the slash).

Therefore, the amount is in VRC. And the price is in BTC.

So,

> (amountOfBtc I want to buy)*priceOfAltcoinInBtc + fee right?

Wrong )
The correct version is:
`amount of VRC you want to buy * price of 1 VRC in BTC + fee`

Does this answer your question?

**Comment by ironexmaiden** [comment]
I want to buy BTC with the amount of VRC

**Comment by kroitor** [comment]
@ironexmaiden as far as I know, their API does not allow that.

**Comment by ironexmaiden** [comment]
ok thank you

**Comment by kroitor** [comment]
@ironexmaiden 

You can't do this:

*I want to buy BTC with the amount of VRC*

But you can do this:

*I want to sell the amount VRC for BTC*

And it's the same thing, you just need to be exact in sides and terms.

**Comment by ironexmaiden** [comment]
How can I achieve this @kroitor ? with create_limit_sell_order? I have thought that this function is selling BTC for the altcoin in  the trade symbol i.e VRC/BTC sells BTC for VRC
