### ISSUE TITLE
Python error request historical data 1/3 times

### ISSUE THREAD

**Issue by Mosjil** [ccxt/ccxt#13461]
- OS: Ubuntu
- Programming Language version: Python
- CCXT version: Lastest

When i try to get the data, its working like 1/3 time.  (I use multiple pair, so sometime its BTC-PERP, ETH-PERP etc)

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 658, in fetch
    response.raise_for_status()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://ftx.com/api/markets/BTC-PERP/candles?resolution=86400&end_time=1653656768&limit=210&start_time=1635512768
```

Thanks

**Comment by Dosix** [comment]
Same issue for me too

**Comment by Mosjil** [comment]
> Same issue for me too

Maybe its just a bug and we need a patch

**Comment by kroitor** [comment]
@Mosjil @Dosix 

> When i try to get the data, its working like 1/3 time. (I use multiple pair, so sometime its BTC-PERP, ETH-PERP etc)

Please, paste your code and your verbose output (enable verbose mode after loading the markets as documented in the Manual):

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
- https://docs.ccxt.com/en/latest/manual.html#troubleshooting

**Comment by Mosjil** [comment]
@kroitor 

So I tried again this morning and it worked normaly. Idk what was the problem, like a misscumunication between FTX and ccxt ?
Here's the part of the code that bugged : 
```
//I use an external prog with all the functions, I wrote the one used in this code
def get_last_historical(self, symbol, timeframe, limit):
     result = pd.DataFrame(data=self._session.fetch_ohlcv(symbol, timeframe, None, limit=limit))
     result = result.rename(columns={0: 'timestamp', 1: 'open', 2: 'high', 3: 'low', 4: 'close', 5: 'volume'})
     result = result.set_index(result['timestamp'])
     result.index = pd.to_datetime(result.index, unit='ms')
     del result['timestamp']
     return result

perpSymbolList = ['BTC-PERP', 'ETH-PERP', 'ADA-PERP', 'SOL-PERP']
timeframe = '1d'
dfList = {}
for pair in perpSymbolList:
    # print(pair)
    df = ftx.get_last_historical(pair, timeframe, 210)
    dfList[pair] = df
```

**Comment by kroitor** [comment]
@Mosjil what is your actual runtime version of the lib? run this in python:

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
```

**Comment by ttodua** [comment]
@Mosjil  Can you please confirm whether the issue has been still ongoing, or it has gone away?

**Comment by Mosjil** [comment]
> @Mosjil  Can you please confirm whether the issue has been still ongoing, or it has gone away?

Hello ! Its has gone a couple days after

**Comment by ttodua** [comment]
thnx for letting us know ;
