### ISSUE TITLE
Bitget fetch ohlcv doesn't working 

### ISSUE THREAD

**Issue by fimenten** [ccxt/ccxt#13460]
- OS: docker python:3.8-slim-buster
- Programming Language version:python 
- CCXT version:1.83.93

I am trying to fetch OHLCV data from bitget, which we need to use "since" as the following code.
but it does not working. It constantly returns data of latest one day.
 
I confirmed all of HTTP GET headers are correctly set, by which I mean ccxt is correct.
Thus, I think bitget api are not working right now.
Does anyone have same problem ? 

```
import ccxt
import pandas as pd
import datetime
if __name__ == "__main__":
    inst = ccxt.bitget()
    markets = [t for t in inst.fetch_markets()]
    # print(markets)
    since = datetime.datetime(2022, 2, 10)
    to = datetime.datetime.now()
    tickers = [d["symbol"] for d in markets]
    
    ohlcv_ = inst.fetch_ohlcv(tickers[0],timeframe="1m",since=int(since.timestamp()*1000))
    df = pd.DataFrame(
    ohlcv_, columns="timestamp,open,high,low,close,volume".split(","))
    df["datetime"] = pd.to_datetime(df["timestamp"].apply(
        lambda x: datetime.datetime.fromtimestamp(x / 1000)))
    df = df.set_index(df["datetime"])
    df = df.sort_index()
    print(df)

```

**Comment by samgermain** [comment]
Thank you for bringing this up. I fixed this issue in [this PR](https://github.com/ccxt/ccxt/issues/13460), although there appear to be limits to how far back you can you go

**Comment by fimenten** [comment]
Thank you for fixing ! I am proud to improve the project.

By the way, As [samgermain](https://github.com/samgermain) mentioned and I confirmed, 
It seems impossible to fetch 1m resolution all historical data from bitget,
If someone knows it ,I want you to share it. 
And I am going to ask bitget, this behaver is what they intended.
