### ISSUE TITLE
Bittrex error handling

### ISSUE THREAD

**Issue by kornrunner** [ccxt/ccxt#1346]
- OS: archlinux
- Programming Language version: PHP
- CCXT version: 
- Exchange: bittrex
- Method: handle_errors

I think there might be some issues here, such as:
[bittrex.php#L686](https://github.com/ccxt/ccxt/blob/master/php/bittrex.php#L686) is a call to `throwExceptionOrError` which is not defined (likely it should call `throw_exception_on_error`)

Next, [bittrex.php#L687](https://github.com/ccxt/ccxt/blob/master/php/bittrex.php#L687) executes only if `success` key exists. It seems very odd that [400+ result code](https://github.com/ccxt/ccxt/blob/master/php/bittrex.php#L683) have a `success` key?

And [bittrex.php#L692](https://github.com/ccxt/ccxt/blob/master/php/bittrex.php#L692) seems redundant if [bittrex.php#L686](https://github.com/ccxt/ccxt/blob/master/php/bittrex.php#L686) gets corrected (or vice versa)

**Comment by kroitor** [comment]
Added transpilation for the throw-function. Thx for pointing that out!

>  It seems very odd that 400+ result code have a success key?

Oh yes, indeed, but they do return a HTTP 400+ code + JSON body (many exchanges do that).

**Comment by kroitor** [comment]
Another important thing here is that Bleutrade is inherited from Bittrex. We might just decouple their implementations and remove the throw-function.

**Comment by LeonLegion** [comment]
in throwExceptionOrError invalid letter "r" in "Or" it must be "On"

**Comment by kroitor** [comment]
@LeonLegion thanks for your attention! A typo... my bad.

**Comment by LeonLegion** [comment]
What about error message 'INVALID_SIGNATURE'? 
May be throw 'AuthenticationError'?

**Comment by kroitor** [comment]
@LeonLegion would you submit a PR on that?

**Comment by kroitor** [comment]
Nevermind, I'll do it now )

**Comment by LeonLegion** [comment]
And last. I take error (success: false) with code 200 from Binance now.
What is wrong?

**Comment by kroitor** [comment]
@LeonLegion can you show a snippet to reproduce it?

**Comment by LeonLegion** [comment]
https://bittrex.com/api/v1.1/account/getbalances?nonce=1516225411&apikey=1

**Comment by LeonLegion** [comment]
But it url returned with status  code 200 and [bittrex.php#L690](https://github.com/ccxt/ccxt/blob/master/php/bittrex.php#L690) skip error.

**Comment by kroitor** [comment]
@LeonLegion no way to tell this without your full verbose output, as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

**Comment by LeonLegion** [comment]
Ok. I did it :)

**Comment by kroitor** [comment]
@LeonLegion sorry, the previous link was incorrect, the correct link is: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

> Ok. I did it :)

I don't really understand. You did what? Where?
