### ISSUE TITLE
partial data download 

### ISSUE THREAD

**Issue by theanonymoustrader** [ccxt/ccxt#13475]
- OS: osx Monterrey 12.4
- Programming Language version: Python
- CCXT version: 1.84.27

Hi everyone! I've runned this code, to download data from FTX with 1h timeframe.

```
data = exchange.fetch_ohlcv("BTC-PERP", "1h")
```

Currently, I've data only for the last 2 months. But I'd like the entire data of BTC perpetual. How I can obtain it?
Thanks

**Comment by kroitor** [comment]
Hi!

You should apply some pagination. It is documented in the Manual here:

- https://docs.ccxt.com/en/latest/manual.html#pagination

Also, check the examples here:

- https://github.com/ccxt/ccxt/tree/master/examples

Hope it helps, let us know if not. Feel free to reopen this issue or just ask further questions if any.
