### ISSUE TITLE
bitfinex and "/offers/hist" request

### ISSUE THREAD

**Issue by cresg820** [ccxt/ccxt#1347]
win 10/python/1.10.456/bitfinex "/offers/hist"

If i try to run this code
```
finex = ccxt.bitfinex(.......)
finex.request('/offers/hist', api='private', method="POST", params={"request": "/v1/offers/hist"})
```

I get this error
`HTTPError: 400 Client Error: Bad Request for url: https://api.bitfinex.com/v1//offers/hist?request=%2Fv1%2Foffers%2Fhist`

I think it's due to this line https://github.com/ccxt/ccxt/blob/master/python/ccxt/bitfinex.py#L608

I've tried a monkey patch removing the "or" condition and it works as expected.

**Comment by kroitor** [comment]
Sorry, but you're not supposed to override the "request" param (no such param overrideable at all). What are you actually trying to achieve with this?

**Comment by kroitor** [comment]
Try this:

```Python
finex = ccxt.bitfinex(...)
print(finex.private_post_offers_hist())
```

Does this help?

**Comment by cresg820** [comment]
Works, thank you.
Buy i didn't have found nothing in the code base or in the docs about this function, it is documented?

**Comment by kroitor** [comment]
Yep, it's explained here: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
