### ISSUE TITLE
The wiki page took too long to render

### ISSUE THREAD

**Issue by avatar-lavventura** [ccxt/ccxt#13480]
I am seeing following message: `The wiki page took too long to render.`

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/18537398/170847324-da73ea98-2042-4364-9d20-ffa79dd17351.png">

Is this issue related to my browser (I am using Safari) or something else?

**Comment by kroitor** [comment]
Duplicate:

- https://docs.ccxt.com/
- https://github.com/ccxt/ccxt/issues/13453

**Comment by kroitor** [comment]
@avatar-lavventura nothing wrong with the browser, it's a limitation of GitHub, we're working on a fix.

**Comment by avatar-lavventura** [comment]
@kroitor Thanks for the fast response as always. GitHub gets worse since Microsoft keeps adding unnessesary features into it.
