### ISSUE TITLE
huobipro fee incorrect 

### ISSUE THREAD

**Issue by hzmbeyond80** [ccxt/ccxt#1349]
the source file listed fee as none

it's should be 0.2% 
https://www.huobi.pro/about/fee/

ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by kroitor** [comment]
What exactly is incorrect?

```Python
import ccxt
exchange = ccxt.huobipro()
exchange.load_markets()
for symbol in list(exchange.markets.keys()):
    taker_fee = exchange.markets[symbol]['taker']
    maker_fee = exchange.markets[symbol]['maker']
    print(symbol, 'taker:', taker_fee, 'maker:', maker_fee)
```
