### ISSUE TITLE
Max safe frequency for fetch_tickers() on Binance?

### ISSUE THREAD

**Issue by beachboy88** [ccxt/ccxt#13499]
Any experience with this? Is twice per minute safe?

**Comment by kroitor** [comment]
Yes, it is safe. The built-in rate limiter should take care of that:

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance()
while True:
    tickers = exchange.fetch_tickers()
    print(exchange.iso8601(exchange.milliseconds()), 'received', len(list(tickers.keys())), 'tickers')
```

**Comment by kroitor** [comment]
Also, check these links:

- https://docs.ccxt.com/en/latest/manual.html#rate-limit
- https://docs.ccxt.com/en/latest/manual.html#notes-on-rate-limiter
