### ISSUE TITLE
get realtime ftx funding rate of all symbols

### ISSUE THREAD

**Issue by springrider** [ccxt/ccxt#13503]
I tried ftx.public_get_funding_rates() and found it is the history funding rate. 
and public_get_futures_future_name_stats seems return the realtime "nextFundingRate".   but this method only accept one symbol at a time.
so does it mean I need to iterate the symbols and request the funding rate one by one?

thanks!

**Comment by samgermain** [comment]
> I tried ftx.public_get_funding_rates() and found it is the history funding rate. and public_get_futures_future_name_stats seems return the realtime "nextFundingRate". but this method only accept one symbol at a time. so does it mean I need to iterate the symbols and request the funding rate one by one?
> 
> thanks!

To get the realtime nextFundingRate, it looks like you'll have to fetch them one by one. I recommend using the [unified `fetchFundingRate` method](https://docs.ccxt.com/en/latest/manual.html#funding-rate) to get it though

**Comment by springrider** [comment]
thanks, based on this ticket:
https://github.com/ccxt/ccxt/issues/9118
for binance exchange, one call to 
`exchange.fapiPublicGetPremiumIndex() `
would be enough right? I tried this api and the results seems correct.

**Comment by samgermain** [comment]
> thanks, based on this ticket: #9118 for binance exchange, one call to `exchange.fapiPublicGetPremiumIndex() ` would be enough right? I tried this api and the results seems correct.

Yeah, but just use the [unified `fetchFundingRates` method](https://docs.ccxt.com/en/latest/manual.html#funding-rate)

**Comment by springrider** [comment]
great, thanks!
