### ISSUE TITLE
Is it possible to get ROE from Binance Futures?

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#13501]
I fetched my positions and it only has unrealizedProfit as something what can describe the status of my futures positions

**Comment by samgermain** [comment]
In future questions can you follow the instructions in the issue template? Like sharing your CCXT version and language version?

---------------------------------------------------

All the fields returned by the `fetchPositions` method are [described here in the documentation](https://docs.ccxt.com/en/latest/manual.html#position-structure). If you think that we should add a field to the position structure please feel free to make a suggestion, or if some data in the output is incorrect please let us know. I'm not really sure where to go with this based on your original post though
