### ISSUE TITLE
Running CCXT through Tor: Is This Possible

### ISSUE THREAD

**Issue by GA-VI** [ccxt/ccxt#13545]
In node.js, I am trying to run CCXT through Tor, with the Tor app running in the background on my Mac computer. That is to say, I want to connect to the crypto exchange through the Tor network.

Connecting node.js to Tor involves connecting to a local SOCKS proxy.  

[This article](https://betterprogramming.pub/how-to-anonymize-node-js-applications-using-tor-bc233356b163) provides some node.js code facilitating connection to Tor via a SOCKS proxy, using the module **socks-proxy-agent**.

[This CCXT documentation](https://docs.ccxt.com/en/latest/install.html) gives a code example for routing CCXT through a https proxy, using the node.js module **https-proxy-agent**.

So I combined the two pieces of code, and was hoping that the following code I created would route CCXT through Tor. However, it does not seem to work, because I still appear to be connected to the exchange via my regular IP, and not through Tor.

```
const ccxt = require ('ccxt')
const { SocksProxyAgent } = require('socks-proxy-agent')

const agent = new SocksProxyAgent('socks5h://127.0.0.1:9050')

const exchange = new ccxt.kraken({ agent })

exchange.apiKey = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX'
exchange.secret = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX'
```

Any suggestions on getting this code working gratefully received.

I have presently set up the exchange API to only accept requests from my regular IP. So if the above code was working, the exchange would reject requests to retrieve exchange private account information, and this is how I would be able to tell that CCXT has been successfully routed through Tor.

**Comment by samgermain** [comment]
I have a solution from an old book I have of how to use tor with Python, no js sorry, you might need to did a little bit more

Having [Tor installed](https://www.torproject.org/ download/download) and running is a requirement for using Tor with Python. [Pysocks](url)  can route traffic through proxy servers and which works with Tor.

```
import socks
import socket
from urllib.request import urlopen
socks.set_default_proxy(socks.SOCKS5, "localhost", 9150) socket.socket = socks.socksocket print(urlopen('http://icanhazip.com').read())
```

This script should display an IP address that is not yours

You can also use Selenium and PhantomJS (replaced with headless chrome I believe) instead of PySocks, Selenium should connect to port 9150

```
from selenium import webdriver
service_args = [ '--proxy=localhost:9150', '--proxy-type=socks5', ] driver = webdriver.PhantomJS(executable_path='<path to PhantomJS>',
                                 service_args=service_args)
driver.get("http://icanhazip.com") print(driver.page_source) driver.close()
```

**Comment by GA-VI** [comment]
Thanks very much for your reply, samgermain.

I am able to get Tor working with node.js. If I run my above code, and then run the code blow:
```
const https = require('https')
https.get('https://checkip.amazonaws.com', {agent}, function(res){ return res.pipe(process.stdout) } )
```
this then displays an IP address that is not mine, and is a confirmed Tor exit node. 

So my node.js script is able to successfully hook up with the Tor app running locally on my computer. 

But I am unable to get CCXT to hook up to Tor.

**Comment by samgermain** [comment]
> Thanks very much for your reply, samgermain.
> 
> I am able to get Tor working with node.js. If I run my above code, and then run the code blow:
> 
> ```
> const https = require('https')
> https.get('https://checkip.amazonaws.com', {agent}, function(res){ return res.pipe(process.stdout) } )
> ```
> 
> this then displays an IP address that is not mine, and is a confirmed Tor exit node.
> 
> So my node.js script is able to successfully hook up with the Tor app running locally on my computer.
> 
> But I am unable to get CCXT to hook up to Tor.

@kroitor @frosty00 Do you have any opinion on this? I don't know much about this topic

**Comment by sc0Vu** [comment]
I finally setup a socks proxy and test script on my computer. The proxy agent works great in ccxt (the base implementation is node-fetch). I also test the agent with node-fetch, it works as well.

```js
const endpoint = 'https://ipinfo.io/ip'
const opts = {
  agent
}
fetch(endpoint, opts)
  .then(async (d) => {
      console.log(await d.text())
    })
  .catch((err) => console.error)
```

Have you try to turn off the socks server and run ccxt with agent? It should throw error `ECONNREFUSED xx.xx.xx.xx:1080` if the socks server turn off.

**Comment by GA-VI** [comment]
When I run you script in mine, sc0Vu, the IP address it returns is my own regular IP, not a Tor IP.

**Comment by GA-VI** [comment]
Anyone else have any ideas regarding how to run CCXT through Tor?

**Comment by samgermain** [comment]
> Anyone else have any ideas regarding how to run CCXT through Tor?

I believe [this was the book](https://www.oreilly.com/library/view/web-scraping-with/9781491985564/) that I used to learn everything I know about using Tor

**Comment by ttodua** [comment]
Have you tried to setup TOR as proxy in its configuration (i.e. see [this](https://superuser.com/questions/458491/configure-tor-as-a-listening-proxy-server-that-i-can-connect-to-remotely)) and then use that as CCXT's `proxy` property?

**Comment by frosty00** [comment]
answered by @ttodua
