### ISSUE TITLE
FTX error while fetching order book

### ISSUE THREAD

**Issue by flav1ooo** [ccxt/ccxt#13552]
It was running well but after yesterday it gives this error : 

ftx {"successs" :false, "error":"Please retry request"}

**Comment by kroitor** [comment]
> It was running well but after yesterday it gives this error :
> 
> ftx {"successs" :false, "error":"Please retry request"}

It means what it says – retry it:

```Python
while True:
    try:
        orderbook = exchange.fetch_order_book(symbol)
        break
    except ccxt.ExchangeNotAvailable as e:
        pass # retry or whatever
```

- https://docs.ccxt.com/en/latest/#error-handling
