### ISSUE TITLE
Zero trading fee when using sanbox mode

### ISSUE THREAD

**Issue by Omar-Alsabbagh17** [ccxt/ccxt#13553]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10
- Programming Language version: Python 
- CCXT version:  1.83.1

```
exchange =  ccxt.binance({
        'apiKey': test_key,
        'secret': test_secret})

exchange.set_sandbox_mode(True)
order_info = exchange.create_order(symbol='ETHUSDT', type = 'market', side='buy', amount=1)  # -> outputs zero fee??

```

```
'fee': {'cost': 0.0, 'currency': 'ETH'},
   'fees': [{'currency': 'ETH', 'cost': '0.00000000'}]}],
 'fees': [{'currency': 'ETH', 'cost': 0.0}]}
```

**Comment by kroitor** [comment]
@Omar-Alsabbagh17 please, always paste your verbose output along with your code:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
exchange =  ccxt.binance({'apiKey': test_key,'secret': test_secret})
exchange.set_sandbox_mode(True)
markets = exchange.load_markets()
exchange.verbose = True
order_info = exchange.create_order(symbol='ETHUSDT', type = 'market', side='buy', amount=1)  # -> outputs zero fee??
```

**Comment by kroitor** [comment]
Closing this for now, feel free to reopen it or just ask further questions here if any.
