### ISSUE TITLE
CCXT PRO part of CCXT

### ISSUE THREAD

**Issue by echograph** [ccxt/ccxt#13557]
Hi, is there an exact date set for ccxt pro to become part of ccxt? Is Q3 still the target?

**Comment by flav1ooo** [comment]
What better features will come in addition to the standard ccxt

**Comment by kroitor** [comment]
> Hi, is there an exact date set for ccxt pro to become part of ccxt? Is Q3 still the target?

Hi @echograph ! Yes, it is still the target. We're planning it for July 2022.

> What better features will come in addition to the standard ccxt

Most of all – more responsive and faster communication. Due the underlying details WS APIs have twice lower latency compared to REST APIs, and fewer delays allow your application to react faster and be more profitable.
