### ISSUE TITLE
Bitfinex: fetch_ohlcv() ignores `since`

### ISSUE THREAD

**Issue by fredfortier** [ccxt/ccxt#1358]
- OS: Mac
- Programming Language version: Python 3.6
- CCXT version: 1.10.565
- Exchange: Bitfinex
- Method: fetch_ohlcv()

I convert '2017-9-1' into milliseconds from epoch to populate the since value. The request seems to ignore it and respond with the most recent candles. The exact same code works correctly with Binance and Poloniex.

Here is what I see in my debugger:
![screenshot 2018-01-18 17 37 56](https://user-images.githubusercontent.com/1474114/35125128-7d2d37c6-fc76-11e7-853e-a6ada3db27b7.png)
![screenshot 2018-01-18 17 38 31](https://user-images.githubusercontent.com/1474114/35125135-82840a7e-fc76-11e7-83f3-06f66302ef39.png)

**Comment by kroitor** [comment]
Will look into it and will get back to you asap.

**Comment by kroitor** [comment]
@fredfortier, does this work for you?

```Python
import ccxt
bitfinex = ccxt.bitfinex()
bitfinex.verbose = True
ohlcvs = bitfinex.fetch_ohlcv('ETH/BTC', '30m', bitfinex.parse8601('2017-09-01T00:00:00'))
print(bitfinex.iso8601(ohlcvs[0][0]))  # prints '2017-09-01T00:00:00.000Z'
```

**Comment by fredfortier** [comment]
So you think that the issue was with using milliseconds for the date instead of a custom parse function? How should I reliably parse my `since` dates to ensure compatibility across all exchanges?

**Comment by kroitor** [comment]
> So you think that the issue was with using milliseconds for the date instead of a custom parse function? 

No, I just used a built-in function for parsing, but this should be the same, really

```Python
import ccxt
bitfinex = ccxt.bitfinex()
bitfinex.verbose = True
ohlcvs = bitfinex.fetch_ohlcv('ETH/BTC', '30m', 1504224000000)
print(bitfinex.iso8601(ohlcvs[0][0]))  # prints '2017-09-01T00:00:00.000Z'
```

`2017-09-01T00:00:00` = 1504224000000 (UTC timestamp in milliseconds)

> How should I reliably parse my since dates to ensure compatibility across all exchanges?

The fetch_ohlcv method takes the ms UTC timestamp, so any function would do the job.

Have you tried the snippet?

**Comment by fredfortier** [comment]
Ok, I'm doing it right then.

I tried but it does not work for me. I'll try to upgrade to the latest.
![screenshot 2018-01-18 21 23 39](https://user-images.githubusercontent.com/1474114/35131743-eba8ec44-fc95-11e7-848e-d29e6d4847ea.png)

**Comment by fredfortier** [comment]
Looking good now! I'll run some regression tests and use the latest version. I should have upgraded first.
![screenshot 2018-01-18 21 26 01](https://user-images.githubusercontent.com/1474114/35131814-4f6dbc50-fc96-11e7-82ec-b2e1528f9f96.png)

**Comment by kroitor** [comment]
@fredfortier no worries at all. Glad you have it resolved. As you know we ask users to update frequently, because we are fixing it "live", it's under very active development. And I've checked through history, the bug was fixed 13 days ago, and your version is approx 19 days old )
