### ISSUE TITLE
[Python] Create market order with take profit and stop loss in Kucoin future

### ISSUE THREAD

**Issue by YuxinSUN89** [ccxt/ccxt#13598]
Hey Team,
Apologies if this might be a duplicate ticket. However, I did find any solution for this issue. 

I am trying to create a market order with take profit and stop loss in Kucoin future. 

- OS: Mac OS
- Programming Language version: Python
- CCXT version: 1.84.70
```
exchange = ccxt.kucoinfutures({
    'apiKey': config.MOH_BUY_API_KEY,
    'secret': config.MOH_BUY_API_SECRET,
    'password': config.MOH_BUY_API_PASSPHRASE
})

symbol = 'AVAX/USDT:USDT'
amount = 1
leverage = 10
side = 'buy'
price =  9.75
stopPrice = (100-config.STOPLOSS)*0.01*price

params = {'leverage': leverage, 'stop': 'loss', 'stopPrice': stopPrice , 'stopPriceType': 'TP'}

order = exchange.create_order(symbol=symbol, type='limit', side=side, amount=amount, price=price, params=params)

```

```
ccxt.base.errors.BadRequest: kucoinfutures error.createOrder.stopInvalid
```
Can anyone please shed some light on how to create a market order with take profit and stop loss in Kucoin future? 

@MohammadTaherkhani Hope the we can get the solution this time. 

Thank you CCXT team !

**Comment by sc0Vu** [comment]
Hi @YuxinSUN89 

Have you try to remove stopPriceType from parameter? I didn't see this in their documentation: https://docs.kucoin.com/#place-a-new-order-2

If you want to create market order of stop loss, the type should be `market`.

**Comment by YuxinSUN89** [comment]
Thanks for replying @sc0Vu  
If I remove stopPriceType, I saw the following error.
```
ccxt.base.errors.BadRequest: kucoinfutures error.createOrder.stopInvalid
```

I am more interested in Take Profit (TP) function, but I couldnt find it in documentation. Is there any TP function in Kucoin future ? Thanks

**Comment by fatehkurd** [comment]
> Hey Team, Apologies if this might be a duplicate ticket. However, I did find any solution for this issue.
> 
> I am trying to create a market order with take profit and stop loss in Kucoin future.
> 
> * OS: Mac OS
> * Programming Language version: Python
> * CCXT version: 1.84.70
> 
> ```
> exchange = ccxt.kucoinfutures({
>     'apiKey': config.MOH_BUY_API_KEY,
>     'secret': config.MOH_BUY_API_SECRET,
>     'password': config.MOH_BUY_API_PASSPHRASE
> })
> 
> symbol = 'AVAX/USDT:USDT'
> amount = 1
> leverage = 10
> side = 'buy'
> price =  9.75
> stopPrice = (100-config.STOPLOSS)*0.01*price
> 
> params = {'leverage': leverage, 'stop': 'loss', 'stopPrice': stopPrice , 'stopPriceType': 'TP'}
> 
> order = exchange.create_order(symbol=symbol, type='limit', side=side, amount=amount, price=price, params=params)
> ```
> 
> ```
> ccxt.base.errors.BadRequest: kucoinfutures error.createOrder.stopInvalid
> ```
> 
> Can anyone please shed some light on how to create a market order with take profit and stop loss in Kucoin future?
> 
> @MohammadTaherkhani Hope the we can get the solution this time.
> 
> Thank you CCXT team !



> 

This is my oldest problem in kucoin future. Please do somthing for it.

**Comment by samgermain** [comment]
[We are currently working towards adding the `stopLossPrice` and `takeProfitPrice` parameters across exchanges,](https://github.com/ccxt/ccxt/issues/13822) feel free to post a kucoinfutures PR if you like

**Comment by sc0Vu** [comment]
Hi @YuxinSUN89 

I think we already add stop price in the latest version ccxt, now you can call with:

```python
// stopPriceType default is TP
// iceberg & visibleSize for limit order
params = {stopPrice': stopPrice , 'stopPriceType': 'MP', 'iceberg': true, 'visibleSize': size}

order = exchange.create_order(symbol=symbol, type='limit', side=side, amount=amount, price=price, params=params)
```

**Comment by 1J0A6L6** [comment]
In the latest CCXT documentation, it appears there are now take profit and stop loss orders across all exchanges. I'm waiting for my trading conditions to actually hit, but I'm curious whether the way the CCXT documentation has said it works in general is the way it works for Kucoin Futures (stoploss and takeprofit). Has anyone tested this with any good result? I don't want to think my code just isn't working.

**Comment by samgermain** [comment]
> In the latest CCXT documentation, it appears there are now take profit and stop loss orders across all exchanges. I'm waiting for my trading conditions to actually hit, but I'm curious whether the way the CCXT documentation has said it works in general is the way it works for Kucoin Futures (stoploss and takeprofit). Has anyone tested this with any good result? I don't want to think my code just isn't working.

No, they're not implemented across EVERY exchange. You should check if `has['createStopLossOrder']`/`has['createTakeProfitOrder']` are set to true (`has['createStopOrder']` for regular stop orders that are not explicitly linked to a position). 

I can update the manual to make this more obvious
