### ISSUE TITLE
Cryptopia.php load_markets not returning right symbol sometimes

### ISSUE THREAD

**Issue by vitoo** [ccxt/ccxt#1359]
Hi,

I'm using the PHP lib

Cryptopia load_markets() is not returning the right symbol sometimes

Example : 

NetCoin/BTC instead of NET/BTC
WarCoin/BTC instead of WRC/TC

Don't know why yet, the code looks correct  https://github.com/ccxt/ccxt/blob/master/php/cryptopia.php#L115

**Comment by kroitor** [comment]
Hi!

This questions is answered here (some symbols are substituted to resolve for conflicts):
- https://github.com/ccxt/ccxt/issues/1330
- https://github.com/ccxt-dev/ccxt/wiki/Manual#symbols-and-market-ids

Let me know if this helps.

**Comment by vitoo** [comment]
Hi @kroitor 

I dont think it's a synonym issue like BCC > BCH

Its more instrument shortname and longname are reverse here

**Comment by kroitor** [comment]
@vitoo 

> I dont think it's a synonym issue like BCC > BCH or BTC > XBT

Yet still, it is, namely it's the NET → NetCoin. Why? Because which other substitution would it be? Why substitute? Because NET stands for Nimiq, which has higher market cap.

**Comment by vitoo** [comment]
ah okay 

So when the long name is chosen, it's because shortname is already used
