### ISSUE TITLE
Huobi stop-limit order on future

### ISSUE THREAD

**Issue by maldred115** [ccxt/ccxt#13590]
Hello, i am trying to create a buy stop-limit order on huobi, but receive an error. 

exchange.load_markets()   
type = 'stop-limit'               
market = exchange.market('ADA/USDT')
operator = 'lte'
params = {'stopPrice': 0.6, 'operator': operator}
order = exchange.create_order('ADA/USDT', type, 'buy', 15, 0.62, params)

huobi {"status":"error","err-code":"order-stop-order-hit-trigger","err-msg":"Orders that are triggered immediately are not supported.","data":null}

**Comment by sc0Vu** [comment]
I think the order was rejected by huobi because of the stop price was less than 0.6. Try another operator, `gte`.

**Comment by maldred115** [comment]
I changed operator from 'lte' to 'gte'. But it still dont work. I think i have enough USDT for this operation. 
<img width="363" alt="Снимок экрана 2022-06-05 в 08 44 49" src="https://user-images.githubusercontent.com/106880764/172038971-e00be117-c4f9-4526-8237-24a6fab0c7df.png">


exchange.load_markets()   
type = 'stop-limit'               
market = exchange.market('ADA/USDT')
operator = 'gte'
offset = 'open'
params = {'offset': offset, 'stopPrice': 0.6, 'operator': operator}
order = exchange.create_order('ADA/USDT', type, 'buy', 15, 0.62, params)

InsufficientFunds: huobi {"status":"error","err-code":"account-frozen-balance-insufficient-error","err-msg":"trade account balance is not enough, left: `0`","data":null}

**Comment by maldred115** [comment]
I think i need to use method: contractPrivatePostLinearSwapApiV1SwapCrossTriggerOrder' / /linear-swap-api/v1/swap_cross_trigger_order'. How i can use it via ccxt?

**Comment by ttodua** [comment]
late reply, but for future readers:
1) if you want to make CCXT work in unified manner, you should provide unified symbol names. e.g. `BTC/USDC:USDC` for  linear swap, or `BTC/USD:BTC` for inverse swap. Then it will use correct endpoint (and you don't need to manually choose `contractPrivatePostOrder` or whatever)

2) you can take a look into https://docs.ccxt.com/#/README?id=trigger-order and also make use of `triggerDirection` unified param, as htx seems to support it 

let us know if any issues
