### ISSUE TITLE
Poloniex: fetch_ohlcv() without since inconsistent

### ISSUE THREAD

**Issue by fredfortier** [ccxt/ccxt#1360]
- OS: Mac
- Programming Language version: Python 3.6
- CCXT version: 1.10.565
- Exchange: Poloniex
- Method: fetch_ohlcv()

When I don't give the `since` parameters, CCXT assumes 0. This never returns expected results (one candle from 1970). With other exchanges (as far as I could tell), it results in the specified number of candles until the current time. I think that `since` should be either mandatory or omitting should result in predictable behavior across exchanges.

**Comment by kroitor** [comment]
Hi!

> This never returns expected results (one candle from 1970).

It depends on the particular param values and on what is an expected result with since = 0

```Python
import ccxt
p = ccxt.poloniex({ 'timeout': 30000 })
candles = p.fetch_ohlcv ('ETH/BTC', '5m', 0)
print(p.iso8601(candles[0][0]))
```

> I think that since should be either mandatory or omitting should result in predictable behavior across exchanges.

I agree, absolutely, but the expected predictable behaviour isn't easy to define. What would you suggest?
