### ISSUE TITLE
Bug - unable to open short position with TP/SL on v1.84.40 (OKX)

### ISSUE THREAD

**Issue by bzhongy** [ccxt/ccxt#13622]
- OS: Big Sur 11.6
- Programming Language version: Python 3.8.10
- CCXT version: 1.84.40
- Exchange used: OKX

Hi, there seems to be a bug in recent version of CCXT with code that used to work in version 1.62.40. Issue arises in creating TakeProfit/StopLoss when creating a Short position in OKX. 

Validated through testing that below code works on 1.62.40 but not on 1.84.40. Basically saying TakeProfit cannot be lower than order price even though it is a Sell order

Errors:
- "TP trigger price can not be lower than the mark price"
- "SL trigger price can not be higher than the last price"

```
symbol = 'GMT/USDT:USDT'

params = {'mgnMode': 'cross'}

OKX.setLeverage(symbol=symbol,leverage=leverage,params=params)

current_price = OKX.fetchTicker(symbol = symbol)['last']

side ='sell'

amount = 15

tp = current_price*(1-0.05)
sl = current_price+(current_price*0.05)

params = {
    'side': 'sell',
    'positionSide':'short',
    'slTriggerPxType': 'mark',
    'tpTriggerPxType': 'mark'
    'tpTriggerPx': tp,
    'tpOrdPx': tp,
    'slTriggerPx': sl,
    'slOrdPx': sl,
    'tdMode': 'cross'
}

# market order
order = OKX.createOrder(type = 'market', symbol=symbol, side=side, amount=amount, price = current_price, params = params)
```

```
okex5 {"code":"1","data":[{"algoId":"","sCode":"51280","sMsg":"SL trigger price can not be higher than the last price."}],"msg":""}

okex5 {"code":"1","data":[{"algoId":"","sCode":"51303","sMsg":"TP trigger price can not be lower than the mark price."}],"msg":""}
```

**Comment by frosty00** [comment]
have you tried switching the tp price with the sl price?

**Comment by frosty00** [comment]
maybe it worked for buy orders but it is reversed for sell orders

**Comment by boiledchickenegg** [comment]
HI, I have but it for some reason only executes the stop order and no actual short position (which is weird?). I've gone back to the older version of ccxt to keep the code working but will keep trying to debug but this hasnt worked

> have you tried switching the tp price with the sl price?

**Comment by frosty00** [comment]
for a sell order the stopLossPrice should be below the current price, whereas for a buy order the stopLossPrice should be above the current price. and it is the opposite for the takePricePrice

**Comment by frosty00** [comment]
ah, it's because you want to make a market order. do this instead:

```
params = {
    'side': 'sell',
    'positionSide':'short',
    'slTriggerPxType': 'mark',
    'tpTriggerPxType': 'mark'
    'tpTriggerPx': tp,
    # 'tpOrdPx': tp,
    'slTriggerPx': sl,
    # 'slOrdPx': sl,
    'tdMode': 'cross'
}
```

**Comment by frosty00** [comment]
or you can omit the tpOrdPrice

**Comment by frosty00** [comment]
btw this code will also work:
```
price = ...
okx.createOrder ('GMT/USDT:USDT', 'market', 'sell', 15, params={ stopLossPrice: price*0.95, takeProfitPrice: price*1.05 })
```

let me know if that helps

**Comment by frosty00** [comment]
it's because you are making a stop limit order instead of a stop market order, you can change the price to whatever

**Comment by frosty00** [comment]
@bzhongy thanks for reporting, will try to fix it now

**Comment by bzhongy** [comment]
> @bzhongy thanks for reporting, will try to fix it now

Appreciate it. Will try the SL/TP orders again once this is rectified. Thanks for the help!

**Comment by frosty00** [comment]
@bzhongy the new build should arrive in around 15mins, if you can update ccxt and try again after it arrives and report the results here that would be really appreciated!

**Comment by bzhongy** [comment]
> @bzhongy the new build should arrive in around 15mins, if you can update ccxt and try again after it arrives and report the results here that would be really appreciated!

@frosty00 Thx, looks like the tgtCcy error is fixed. However still having the same issue with TP/SL and getting the errors around setting the TP/SL. 

> for a sell order the stopLossPrice should be below the current price, whereas for a buy order the stopLossPrice should be above the current price. and it is the opposite for the takePricePrice

Perhaps I am overthinking but the logic that worked in previous version is a 'sell order' should open a short position with TP lower than the order/current price and SL should be higher than the order/current price (as a price movement up would be). This worked in v1.62.40

When I switch up the TP/SL in params all it does is open a Sell stop order and **doesn't** open a Short position. Not sure the logic here but don't have time to debug now but will in a few hrs. Same result happens with below code 

> btw this code will also work in the latest version of ccxt:
> 
> ```
> price = ...
> okx.createOrder ('GMT/USDT:USDT', 'market', 'sell', 15, params={ stopLossPrice: price*0.95, takeProfitPrice: price*1.05 })
> ```
> 
> let me know if that helps

**Comment by frosty00** [comment]
I think in this case you will need to first open up a position and make a second order to be a stopLoss for the position using the reduceOnly flag

**Comment by bzhongy** [comment]
@frosty00 This is fine if this is the solution but find it strange it doesn't work anymore. Perhaps a change on OKX side?

Thanks for the help

**Comment by frosty00** [comment]
@bzhongy i've tested it and it is because stop orders were not properly being made in old versions so it just made a market order instead, please update to the latest version and let us know if the issue persists.

**Comment by bzhongy** [comment]
@frosty00 does this mean that current versions would be the below solution?

> I think in this case you will need to first open up a position and make a second order to be a stopLoss for the position using the reduceOnly flag

**Comment by poloxue** [comment]
Is this issue still not solved? 

I can not create a limit order with take profit and stop loss. It used a stop a order url API  `/api/v5/trade/order-algo` not `/api/v5/trade/order`. I think that is the root cause. Only if parameters like `sl price` `tp price` or any parameter related to algo order, it will create the order using algo order api.
