### ISSUE TITLE
Binanace rate limit error for fetchTickers

### ISSUE THREAD

**Issue by ninadpachpute** [ccxt/ccxt#1365]
- OS: Ubuntu 16.04.3
- Programming Language version: Node live-tickers.js
- CCXT version: a9e763b21908f29c790f6c0279e868013c3394e9
- Exchange: Binance
- Method: fetchTickers

I ran a js example from 'examples/js' directory -
$ node live-tickers.js binance

Got rate limit error -- Error: binance 418 I'm a Teapot {"code":-1003,"msg":"Way too many requests; IP banned until 1516363116074."}

Following is complete console output -
```
--------------------------------------------------------
binance 2018-01-19T11:56:35.581Z
Fetched 243 tickers:
  symbol |          price |                 datetime
----------------------------------------------------
BTC/USDT | 11579.98000000 | 2018-01-19T11:56:34.828Z
ETH/USDT |  1054.93000000 | 2018-01-19T11:56:35.217Z
NEO/USDT |   146.01700000 | 2018-01-19T11:56:35.352Z
BNB/USDT |    15.05020000 | 2018-01-19T11:56:33.205Z
LTC/USDT |   194.50000000 | 2018-01-19T11:56:35.164Z
BCH/USDT |  1800.00000000 | 2018-01-19T11:56:35.307Z
 CND/BNB |     0.01316000 | 2018-01-19T11:56:33.318Z
 NEO/BNB |     9.70700000 | 2018-01-19T11:56:34.718Z
 TRX/ETH |     0.00007927 | 2018-01-19T11:56:34.415Z
 XLM/BNB |     0.03452000 | 2018-01-19T11:56:21.864Z
 VEN/BNB |     0.38990000 | 2018-01-19T11:56:08.951Z
 LTC/BNB |    12.87000000 | 2018-01-19T11:56:34.757Z
 ICX/BNB |     0.55990000 | 2018-01-19T11:56:34.065Z
 ADX/BNB |     0.14703000 | 2018-01-19T11:56:34.284Z
 XRP/ETH |     0.00154450 | 2018-01-19T11:56:35.352Z
IOTA/BNB |     0.18926000 | 2018-01-19T11:56:34.942Z
 BCH/BNB |   119.06000000 | 2018-01-19T11:56:35.232Z
 TRX/BTC |     0.00000724 | 2018-01-19T11:56:35.232Z
 QSP/BNB |     0.03443000 | 2018-01-19T11:56:32.388Z
 CND/ETH |     0.00018801 | 2018-01-19T11:56:35.315Z
(node:14108) UnhandledPromiseRejectionWarning: Error: binance 418 I'm a Teapot {"code":-1003,"msg":"Way too many requests; IP banned until 1516363116074."}
    at binance.handleErrors (/home/ninad/apps/jackbot/ccxt/repo/ccxt/js/binance.js:827:23)
    at response.text.then.text (/home/ninad/apps/jackbot/ccxt/repo/ccxt/js/base/Exchange.js:452:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14108) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


```

**Comment by orkenstein** [comment]
@ninadpachpute 
That's because you make too much requests. Under the hood `fetchTickers` uses `tickers/24h`, which is quite "heavy" request. And you're limited to 1200 points per minute, when `fetchTickers` takes 242 points at this moment.
At `sleep(X)` to avoid this and count your requests: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

There's also another problem: Binance should return 429 first, not 418. But AFAIU, it's a known bug for this moment.

**Comment by kroitor** [comment]
Answered here: https://github.com/ccxt/ccxt/issues/1177
Let us know if it doesn't help. Thx!

**Comment by orkenstein** [comment]
@kroitor actually this might be a problem in future, 'cause `ccxt` violates Binance quite fast, and there's no inner mechanism to avoid that. I expect much more strict rules on majow exchanges soon.
Maybe we have to add some internal counter and smart-throttle strategy, what do you think?

**Comment by kroitor** [comment]
@orkenstein 

> Maybe we have to add some internal counter and smart-throttle strategy, what do you think?
Yeah, you're right. Not sure how it will be in the end, but we should probably add some protection. Let me think of it a little. We might also need to parse their current rate-limit info from here: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#exchange-information

**Comment by orkenstein** [comment]
@kroitor I'm working on Binance bot now, so gonna dive into it. If you have a plan, how to implement counter in a good way, lemme know.
