### ISSUE TITLE
bybit limit close/sell/tp order creates short order

### ISSUE THREAD

**Issue by flieks** [ccxt/ccxt#13675]
Hi, 

This code created a `close/sell order` a few days ago but with the latest ccxt version it creates a `short order`:

```
exchange.createOrder({
            symbol,
            'limit',
            'sell',
            position,
            price
})
```

Maybe this is bybit related issue. A change in their API ? 
How to place a short vs a sell with `createOrder` ?

**Comment by carlosmiei** [comment]
Hello @flieks, sorry I'm not sure I understood your question. Can you please illustrate it with a small example specifying exactly the markets and parameters used?

**Comment by carlosmiei** [comment]
@flieks When you're dealing with derivatives usually sell means 'open a short position' so I don't see a problem there. If you want to trade spot markets instead and sell or buy coins normally you can check out how this example: https://github.com/ccxt/ccxt/blob/master/examples/py/bybit-updated.py#L24.


I'll close this issue but free feel to reopen it if this does not answer your question.

**Comment by flieks** [comment]
@carlosmiei but then this like is a sell on derivatives and is a TP order ...
https://github.com/ccxt/ccxt/blob/a12f37a58fcc392309cd3f781edb20cce9982241/examples/js/bybit-updated.js#L102

**Comment by flieks** [comment]
@carlosmiei by reopening you mean make a new issue ?

**Comment by kroitor** [comment]
@flieks nope, since you're the author of the issue you can reopen it if it was closed / if necessary.

**Comment by flieks** [comment]
thanks but i never see a button to reopen it so i thought i dont have permissions. 
I found this on google `you can re-open your own issues if you closed them yourself`

my question is that of yesterday (see last post):
If i use ADAUSDT as ticker id, and use `limit` and `sell`, that should create a TP limit order to close an existing position right ?

**Comment by carlosmiei** [comment]
@flieks It is not a TP limit order, it is a "limit order" only. TP/SL orders are a different thing but I think I get what you meant, by closing the current position you might have a profit or a loss. 

If you have an open long position and want to close it yes you should issue an order in the opposite direction (sell in this case) and you should also provide the 'reduce_only' flag as true.

Please check out this example that demontrastes precisely that: https://github.com/ccxt/ccxt/blob/master/examples/py/bybit-updated.py#L54

**Comment by flieks** [comment]
@carlosmiei hmm thanks for the explanation.

It seems indeed that the `reduce_only` did the trick. Putting it to true creates a limit close instead of a limit short. I wonder if other exchanges will work to with this setup but this i will test later.

Thanks for the help
