### ISSUE TITLE
Bittrex IP violation

### ISSUE THREAD

**Issue by srg0** [ccxt/ccxt#1367]
If Bittrex show IP violation - unknown error
- OS:any
- Programming Language version:js
- CCXT version:last
- Exchange:bittrex
- Method:buy

**Comment by kroitor** [comment]
@srg0 can you please provide the following info, like described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

  - **set `.verbose = true` property on the exchange instance before calling its methods**
  - **surround code and output with triple backticks: &#096;&#096;&#096;YOUR\_CODE&#096;&#096;&#096;**
  - paste a complete code snippet you're having difficulties with, avoid one-liners
  - paste the full stacktrace of that snippet in verbose mode as is, unchanged
  - don't confuse the backtick symbol (&#096;) with the quote symbol (\'), &#096;&#096;&#096;GOOD&#096;&#096;&#096;, '''BAD'''
  - write your language **and version**
  - write ccxt library version
  - which exchange it is
  - which method you're trying to call

**Comment by kroitor** [comment]
I would close this for now until we have a follow up on this. Let us know if you still have problems with it, feel free to reopen this issue or just ask questions, if any. Thx.

**Comment by azharuniverse** [comment]
**In Bittrex limit buy order, ccxt unable to parse error properly.**
"ccxt": "^1.10.833"

Logging error in catch block of limit buy order
`console.log('error in ccxt limit buy', err, err.constructor.name, err.message);`

```
Response:
{"success":false,"message":"WHITELIST_VIOLATION_IP","result":null}
error in ccxt limit buy TypeError: Cannot read property 'result' of undefined
    at bittrex.createOrder (C:\..........\node_modules\ccxt\js\bittrex.js:435:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) TypeError Cannot read property 'result' of undefined
```
