### ISSUE TITLE
Quoinex exchange id wrong in manual

### ISSUE THREAD

**Issue by wannesdemaeght** [ccxt/ccxt#1368]
Hi, 

per the manual, the id of Quoinex is "quoinex"

However, using this code
`let Quoinex = new ccxt.quoinex ({apiKey: API.Quoinex.Key, secret: API.Quoinex.Secret})`

results in this error: 

> TypeError: ccxt.quoinex is not a constructor
>     at c:\Trader\Logic\Test.js:68:22
>     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

If I use "new ccxt.quoine", it does work.

So manual is wrong, (but I would actually prefer the naming to be per the manual, "quoinex")

So, do I change my code, or do you change yours?

**Comment by Deathamns** [comment]
It was renamed recently #1311. `quoinex` is the correct one, just make sure you're using a newer version of the library.

**Comment by wannesdemaeght** [comment]
Aha, great.
Thanks!
