### ISSUE TITLE
Implementation for Bittrex of fetch_currencies breaks when Bittrex does not return a countable.

### ISSUE THREAD

**Issue by iwanluijks** [ccxt/ccxt#13704]
Implementation for Bittrex of fetch_currencies breaks when Bittrex does not return a countable.

- OS: CentOS
- Programming Language version: PHP
- CCXT version: latest

```
$bittrex->fetch_currencies([]);
```

As to the implementation of fetch_currencies for Bittrex, ccxt has the code as shown below inside. The `$response` however might not be a countable value, and might be for example `null`, which if it is, results in the error `ErrorException count(): Parameter must be an array or an object that implements Countable`.

```
$response = $this->publicGetCurrencies ($params);
$result = array();

for ($i = 0; $i < count($response); $i++) {
// etc...
```

Expected some kind of Ccxt exception or simply an empty array returned.

**Comment by kroitor** [comment]
> The $response however might not be a countable value, and might be for example null

Can you please paste the code you use to reproduce it or your complete verbose output with a null-response? It should have been intercepted in the error handler.

**Comment by iwanluijks** [comment]
The code in the issue is actually the code...

We call `$bittrex->fetch_currencies([]);`, thus `fetch_currencies` with an empty array for the `$params` argument. The first line in `fetch_currencies` is:
```
$response = $this->publicGetCurrencies ($params);
```

That results in `$response` being `null` sometimes (not always, sometimes). And `$response` is used a few lines below that within `fetch_currencies` as:
```
for ($i = 0; $i < count($response); $i++) {
```

which thus fails as `$response` is not countable...

**Comment by kroitor** [comment]
@iwanluijks we will try to add the handling for it, but it would help speed it up if you could paste your verbose output for the failing call:

```PHP
$bittrex->load_markets();
$bittrex->verbose = true;
$bittrex->fetch_currencies([]);
```

**Comment by ttodua** [comment]
bittrex is closed
