### ISSUE TITLE
Bitfinex2: allow omitting currency code in fetchTrades

### ISSUE THREAD

**Issue by steebchen** [ccxt/ccxt#13702]
According to the API, you can omit the currency code when fetching trades:

<img width="397" alt="image" src="https://user-images.githubusercontent.com/5013932/172461278-9673b4d1-5a00-4537-b5ec-71bd0be7c076.png">

https://docs.bitfinex.com/reference/rest-auth-trades

This seems similar to the fetchLedgers behaviour (which is already implemented to allow providing no code/symbol).

I didn't look into too much yet, but if anyone thinks this might be worth exploring, I can take a look

**Comment by carlosmiei** [comment]
Hello @steebchen,

The method you're pointing to is the authenticated one meaning that returns user trades. If you check our implementation (**fetchMyTrades**) you'll see that we also don't require a symbol there: https://github.com/ccxt/ccxt/blob/master/js/bitfinex2.js#L1738

Fetching public trades (our fetchTrades) requires a symbol as you can see here: https://docs.bitfinex.com/reference/rest-public-trades

Feel free to reopen it if anything!

**Comment by steebchen** [comment]
Ah, I was indeed talking about fetchMyTrades, but I think somehow I messed something up... I tested it again and it indeed works, sorry for the inconvenience and thanks so much for the quick help!
