### ISSUE TITLE
Bittrex maker/taker fees incorrect

### ISSUE THREAD

**Issue by evan-coygo** [ccxt/ccxt#13701]
- OS: Ubuntu
- Programming Language version: js
- CCXT version:  1.85.60

Bittrex spot trading fees at tier 1 are 0.35 taker / 0.35 maker. They are currently 0.75 in ccxt.

https://bittrex.zendesk.com/hc/en-us/articles/115000199651-Bittrex-fees
![image](https://user-images.githubusercontent.com/42989004/172460985-eb3ba5ca-ebdc-489c-8990-8f506e44adac.png)

Current code in bittrex.js
```js
                'trading': {
                    'tierBased': true,
                    'percentage': true,
                    'maker': this.parseNumber ('0.0075'),
                    'taker': this.parseNumber ('0.0075'),
                }
```

**Comment by evan-coygo** [comment]
I just noticed that Bittrex (0.35) has different fees than Bittrex Global (0.75) which is what the code is currently set to. They both appear to use the same API endpoint (as described here https://bittrex.github.io/api/v3) and the same ccxt client so perhaps there's no way to have this correct for everybody if it's hard coded

**Comment by kroitor** [comment]
@evan-coygo use `exchange.fetchTradingFees` to fetch your private per-account fees. Let us know if that does not help.

**Comment by evan-coygo** [comment]
Yup that will do thanks
