### ISSUE TITLE
Deribit - problem with markets on testnet

### ISSUE THREAD

**Issue by docek** [ccxt/ccxt#13705]
- OS: Linux on ChromeOS
- Programming Language version: Python 3.10
- CCXT version: 1.85.69

On Deribit production I get

```
import ccxt

e = ccxt.deribit()
e.set_sandbox_mode(False)
e.load_markets()
print(e.market('BTC/USD:BTC')['id'])
```
correct result
```
BTC-PERPETUAL
```
However if I switch to sandbox I get
```
import ccxt

e = ccxt.deribit()
e.set_sandbox_mode(True)
e.load_markets()
print(e.market('BTC/USD:BTC')['id'])
```
falsely
```
BTC-FS-17JUN22_PERP
```

which cause the problem with fetch_position() function does not work with unified symbols.

**Comment by samgermain** [comment]
@kroitor Should we unify the sandbox symbols as well?

**Comment by samgermain** [comment]
When I run the following code I get `BTC-PERPETUAL` printed

```
import ccxt

e = ccxt.deribit()
e.set_sandbox_mode(True)
e.load_markets()
print(e.market('BTC/USD:BTC')['id'])
```

--------------------

python version: 3.10.4 (main, Apr 26 2022, 19:42:59) [Clang 13.1.6 (clang-1316.0.21.2)]
CCXT Version: 1.88.53
OS: MacOS Monteray 12.4
Hardware: Mac Mini 3.6 GHz Quad-Core Intel Core i3

**Comment by kroitor** [comment]
@docek do you have this issue with the most recent version of CCXT ?

**Comment by docek** [comment]
No, I get the correct result now in sandbox mode too. Thanks for the great work.
