### ISSUE TITLE
Total balance of a account

### ISSUE THREAD

**Issue by 300Gram** [ccxt/ccxt#13712]
Hi, I am not very good in programming so I tried googling on how to use CCXT to get the overall account balance using the "balance" function, but no luck. 

So I wonder if anyone can help me out. 
I am trying to get the overall account balance of any exchange, instead of just 1 assets. 

Thank you in advance.

**Comment by carlosmiei** [comment]
Hello @300Gram, which exchange do you use?

Also, I would suggest reading the manual carefully you will find most of the things you might need there.

**Comment by FabLK** [comment]
@300Gram Hello, I'm doing that for my project and this is how I proceed:

1/Getting balances of every token
2/For every token, find the price against USDT (if not available against BTC or ETH then against USDT) of course you can do this against USD or every currency you want
3/Convert my token balances into usdEquivalent balances
4/Sum all usdEquivalent balances 

This is how I proceed for Binance (this code may be not optimal but it gives you an idea): 
```py
        def get_balance(self):
            start = time.time()
            balances = self.exchange.fetch_balance()['info']['balances']
            self.balance = 0

            for i in balances:
                if float(i['free'])!=0 or float(i['locked'])!=0:
                    if i['asset'] != 'USDT':
                        request = i['asset']+'/USDT'
                        try:
                            price = float(self.exchange.fetchTicker(request)['last'])
                        except:
                            try:
                                request = i['asset']+'/BTC'
                                price = float(self.exchange.fetchTicker(request)['last'])
                                val_btc = (float(i['free'])+float(i['locked']))*price
                                price = float(self.exchange.fetchTicker('BTC/USDT')['last'])
                                self.balance += val_btc*price
                            except:
                                try:
                                    request = i['asset']+'/ETH'
                                    price = float(self.exchange.fetchTicker(request)['last'])
                                    val_btc = (float(i['free'])+float(i['locked']))*price
                                    price = float(self.exchange.fetchTicker('ETH/USDT')['last'])
                                    self.balance += val_btc*price
                                except:
                                    print(i['asset'])

                        self.balance += (float(i['free'])+float(i['locked']))*price
                    else:
                        self.balance += float(i['free'])+float(i['locked'])
            self.latency = time.time()-start
```

**Comment by 300Gram** [comment]
Thanks! I wonder if there is any shorter way to get this done. (i mean the simpler the better). 

But thank you! Appreciate it, will try to implement into my code (:

**Comment by 300Gram** [comment]
> @300Gram Hello, I'm doing that for my project and this is how I proceed:
> 
> 1/Getting balances of every token 2/For every token, find the price against USDT (if not available against BTC or ETH then against USDT) of course you can do this against USD or every currency you want 3/Convert my token balances into usdEquivalent balances 4/Sum all usdEquivalent balances
> 
> This is how I proceed for Binance (this code may be not optimal but it gives you an idea): **The ccxt object is self.exchange**
> 
> ```python
>         def get_balance(self):
>             start = time.time()
>             balances = self.exchange.fetch_balance()['info']['balances']
>             self.balance = 0
> 
>             for i in balances:
>                 if float(i['free'])!=0 or float(i['locked'])!=0:
>                     if i['asset'] != 'USDT':
>                         request = i['asset']+'/USDT'
>                         try:
>                             price = float(self.exchange.fetchTicker(request)['last'])
>                         except:
>                             try:
>                                 request = i['asset']+'/BTC'
>                                 price = float(self.exchange.fetchTicker(request)['last'])
>                                 val_btc = (float(i['free'])+float(i['locked']))*price
>                                 price = float(self.exchange.fetchTicker('BTC/USDT')['last'])
>                                 self.balance += val_btc*price
>                             except:
>                                 try:
>                                     request = i['asset']+'/ETH'
>                                     price = float(self.exchange.fetchTicker(request)['last'])
>                                     val_btc = (float(i['free'])+float(i['locked']))*price
>                                     price = float(self.exchange.fetchTicker('ETH/USDT')['last'])
>                                     self.balance += val_btc*price
>                                 except:
>                                     print(i['asset'])
> 
>                         self.balance += (float(i['free'])+float(i['locked']))*price
>                     else:
>                         self.balance += float(i['free'])+float(i['locked'])
>             self.latency = time.time()-start
> ```

Thanks for your code! I referred some of your code and make it my own with a much simpler code (I am a beginner, so the simpler the better).
