### ISSUE TITLE
installing CCXT PRO in docker container

### ISSUE THREAD

**Issue by darkfennertrader** [ccxt/ccxt#13727]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- OS: UBUNTU 20.04
- Programming Language version: python
- CCXT version: 1.1.60

Hello,
I am trying to install CCXT-PRO in container and when building the container it throws me the followinmg error:
```
  Cloning https://github.com/kroitor/ccxt.pro.git (to revision 1.1.60) to /tmp/pip-req-build-rf3mk3ab
  Running command git clone --filter=blob:none --quiet https://github.com/kroitor/ccxt.pro.git /tmp/pip-req-build-rf3mk3ab
  fatal: could not read Username for 'https://github.com': No such device or address
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/kroitor/ccxt.pro.git /tmp/pip-req-build-rf3mk3ab did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/kroitor/ccxt.pro.git /tmp/pip-req-build-rf3mk3ab did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

```
What should I do to install it properly? Is it related with git access?

thanks Raimondo

**Comment by kroitor** [comment]
@darkfennertrader if you can, please, elaborate a bit more on what you did to fix the credential issue, that will help other users as well. Thanks!

**Comment by darkfennertrader** [comment]
Sure. 
If you want to clone a private repository from within a doker image. I tried to install CCXT-PRO with HTTPS authentication
pip3 install git+https://github.com/kroitor/ccxt.pro.git#subdirectory=python 
you need to add inside the Dockerfile the following two lines:
.....
ARG GIT_TOKEN
RUN python -m pip install git+https://${GIT_TOKEN}@github.com/kroitor/ccxt.pro.git@1.1.60#subdirectory=python
....
where the ARG GIT_TOKEN can be retrieved from GitHub and pass it during the build
docker build -t my_image_name:x.y.z --build-arg GIT_TOKEN=your_token.

WARNING: Do not use this procedure in Production since yoour credentials are exposed in docker image. Use it only for Development and Testing.

Hope this help.
