### ISSUE TITLE
Issues with various currency reporting via API

### ISSUE THREAD

**Issue by outsideintel** [ccxt/ccxt#1372]
- OS: Ubuntu
- Programming Language version: Python
- CCXT version: cctx-1.0.0
- Exchange: kraken (and others)
- Method: fetch_order_book

It looks like Kraken (and others, on fybse, fybsg, vaultoro, coinexchange, coinsecure and maybe others) appear to be reporting in the wrong currency for certain queries.  Maybe it's because these queries were never supposed to exist, or someone thought they were there and they really aren't and they're defaulting back to a default currency.  But the simple test case I have is:

```
import ccxt

exchangeinquestion = 'kraken'
symbolinquestion   = 'BTC/GBP'

thisexchange = getattr (ccxt, exchangeinquestion) ()
json = thisexchange.fetch_order_book (symbolinquestion)
print(json)
```

As of this moment this is saying that bitcoin is around 5,800 pounds, when it's really more like 8,300.  I validated with the API at Kraken and they do not support this particular symbol.

https://api.kraken.com/0/public/AssetPairs

I'm not sure if there is a way to properly warn people ahead of time, if they're about to make a mistake, but this seems like it could cause people to spend way too much/little inadvertently.

**Comment by kroitor** [comment]
I'm getting this.

However, I don't see anything wrong here, the data is correctly handled by ccxt, you see exactly what comes from Kraken itself. We're not in charge of their prices.

```
mbp:ccxt igorkroitor$ python examples/py/tickers.py kraken BTC/GBP
Instantiating kraken
kraken has 59 symbols: BCH/BTC, BCH/EUR, BCH/USD, BTC/CAD, BTC/EUR, BTC/GBP, BTC/JPY, BTC/USD, DASH/BTC, DASH/EUR, DASH/USD, EOS/BTC, EOS/ETH, ETC/BTC, ETC/ETH, ETC/EUR, ETC/USD, ETH/BTC, ETH/CAD, ETH/EUR, ETH/GBP, ETH/JPY, ETH/USD, ETHCAD.d, ETHEUR.d, ETHGBP.d, ETHJPY.d, ETHUSD.d, ETHXBT.d, GNO/BTC, GNO/ETH, ICN/BTC, ICN/ETH, LTC/BTC, LTC/EUR, LTC/USD, MLN/BTC, MLN/ETH, REP/BTC, REP/ETH, REP/EUR, USDT/USD, XBTCAD.d, XBTEUR.d, XBTGBP.d, XBTJPY.d, XBTUSD.d, XDG/BTC, XLM/BTC, XLM/EUR, XMR/BTC, XMR/EUR, XMR/USD, XRP/BTC, XRP/EUR, XRP/USD, ZEC/BTC, ZEC/EUR, ZEC/USD
{'info': {u'a': [u'6630.00000', u'1', u'1.000'], u'c': [u'6325.40000', u'0.10000000'], u'b': [u'5740.00000', u'1', u'1.000'], u'h': [u'6918.90000', u'6918.90000'], u'l': [u'5680.00000', u'5670.20000'], u'o': u'6650.00000', u'p': [u'6363.12343', u'6342.58659'], u't': [10, 19], u'v': [u'0.23858500', u'0.42333581']}, 'last': 6325.4, 'timestamp': 1516386834250, 'symbol': u'BTC/GBP', 'vwap': 6342.58659, 'datetime': '2018-01-19T18:33:54.250Z', 'high': 6918.9, 'average': None, 'low': 5670.2, 'quoteVolume': 2685.044031572788, 'ask': 6630.0, 'close': None, 'percentage': None, 'baseVolume': 0.42333581, 'open': 6650.0, 'bid': 5740.0, 'change': None, 'first': None}
kraken BTC/GBP ticker 2018-01-19T18:33:54.250Z high: 6918.9 low: 5670.2 bid: 5740.0 ask: 6630.0 volume: 2685.04403157
mbp:ccxt igorkroitor$ 
```

>  I validated with the API at Kraken and they do not support this particular symbol.

Which particular symbol? BTC/GBP? They report that they do support it. Don't confuse symbols and market ids: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

Let us know if it doesn't help.

**Comment by outsideintel** [comment]
I was confusing market ids (I thought that I had been ignoring them entirely per the documentation's warnings that it's meant for internal use but apparently it snuck back into my code).  But also I may be confusing their public API ( https://api.kraken.com/0/public/AssetPairs ) and the fact that I can't find anything that says "GBP" that looks like the same endpoint.  I don't know - their API is rather hard to read.

I but I am concerned that even though those two things above might be wrong (now fixed) they're saying it's GBP but it's actually some other currency (which one I have no idea).  So it's always going to be wrong, not just sometimes.  So to me that seems like the API itself is broken/wrong since it's reporting incorrectly (their fault, not yours I'd think, but I'm not sure since I haven't dug into the internals of ccxt).  I'm not sure how to fix this since it's their problem (assuming it is).  But it really hurts the reliability since there's no way that trade would ever work in reality, I'd assume.

**Comment by kroitor** [comment]
<img width="1021" alt="screen shot 2018-01-19 at 22 12 31" src="https://user-images.githubusercontent.com/1294454/35167263-db8c1798-fd65-11e7-8f0a-41cf75ea5740.png">

Kraken's internal currency ids are prefixed with `X` for crypto (XETH, XXBT) and letter `Z` for fiat currencies (ZUSD, ZGBP, ZEUR...).

> So to me that seems like the API itself is broken/wrong since it's reporting incorrectly (their fault, not yours I'd think, but I'm not sure since I haven't dug into the internals of ccxt).

Welcome to our world! This is the least of surprises you will get from exchanges, get ready for a long ride )

**Comment by outsideintel** [comment]
Blerg. Yeah, I dig.  And thanks for being patient as I'm diving in.  Should we start compiling a list of known issues at least?  Maybe take a conservative approach to the API and warn people when they're using an API that's got known issues?  Something like:

```
knownerrors = None
(knownerrors, json) = cctx.kraken.fetch_order_book (symbol)
if knownerrors is not None:
  #discard or warn
```

Just trying to think how we can warn the next guy before he makes a bad trade.  I know fybsg for instance is reporting BTC/SEK in Singapore dollars instead of Swedish Crowns for instance.  I messaged them on twitter and got no reply.  Not even sure if that's a real company, to be honest.

**Comment by kroitor** [comment]
@outsideintel well, it depends on what is considered to be a *workable* issue. 

Most often these effects are temporary (if you mean the price discrepancy) and they usually disappear before you even have a chance to hardcode them. For the BTC/SEK at fybsg, we can add a workaround (will do), because we already have a generic solution for these types of name conflicts. But with Kraken BTC/GBP, there isn't really a good workaround, because this isn't a name conflict at all, it's just how they report the price for bitcoin in pounds from their engine. We can't really decide for the user on how to treat that data, and whether it is valid or "makes sense". This is somewhat beyond the scope of the library, which is to deliver data as it is, no cherry-picking. Does this answer your question?
