### ISSUE TITLE
About canceling contract orders

### ISSUE THREAD

**Issue by qwe231cvb** [ccxt/ccxt#13730]
The exchange used is FTX and the programming language used is Python.

Suppose I have set take profit and stop loss orders for the contract, if the stop loss order has been filled,

So will the exchange automatically cancel the take profit order?
And how to cancel the contract order? How is the code implemented?

**Comment by sherhan** [comment]
This is not possible. You will have to cancel the other order manually.

I would suggest creating a celery worker running in the background to monitor and cancel opposing orders if one order in the set gets filled.

**Comment by Dan-krm** [comment]
Closing this now
