### ISSUE TITLE
Python: Async support is broken, `NameError: name 'TRUNCATE' is not defined`

### ISSUE THREAD

**Issue by Yolley** [ccxt/ccxt#13752]
- OS: Ubuntu 20.04.4
- Programming Language version: Python 3.9
- CCXT version: 1.89.13

```python3
from ccxt.async_support import binance
client = binance()
order = await self.client.create_order("BTC/USDT", "market", "buy", 0.01)
```

```pytb
    order = await c.create_order("BTC/USDT", "market", "buy", 0.001)
  File "/lib/python3.9/site-packages/ccxt/async_support/binance.py", line 2843, in create_order
    request['quantity'] = self.amount_to_precision(symbol, amount)
  File "/lib/python3.9/site-packages/ccxt/async_support/base/exchange.py", line 672, in amount_to_precision
    return self.decimal_to_precision(amount, TRUNCATE, market['precision']['amount'], self.precisionMode, self.paddingMode)
NameError: name 'TRUNCATE' is not defined
```

It seems that the issue is in the base class for async_support exchange https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/base/exchange.py TRUNCATE and ROUND are not imported. It got broken in 1.86.4 with these commits https://github.com/ccxt/ccxt/commit/af27a610a2b881de52577263ce803318915397bb and https://github.com/ccxt/ccxt/commit/ca6b53085b6184affb4dbbf15e3ab4ca2bc94892

**Comment by kroitor** [comment]
@Yolley thank you for your feedback! The fix will arrive in CCXT 1.86.18 in ~20 minutes.
