### ISSUE TITLE
New exchange request: Stellar (StellarX DEX)

### ISSUE THREAD

**Issue by walkjivefly** [ccxt/ccxt#1376]
Checked existing (open and closed) issues, didn't find matching one.
Stellar DEX provides a [RESTful API](https://www.stellar.org/developers/horizon/reference/index.html).

I know there is already [#715](https://github.com/ccxt/ccxt/issues/715) for EtherDelta and other WS based decentralised exchanges like EtherDelta but there is already a JS [reference implementation](https://github.com/stellar/js-stellar-sdk) which might facilitate inclusion in ccxt. Unfortunately, I don't have the skill to do it myself.

**Comment by jjhesk** [comment]
api doc: https://stellar.github.io/js-stellar-sdk/ , https://www.stellar.org/developers/reference/
url: https://www.stellar.org/
fee: --
volume: --
address: --
company info: --
Registration: --
based country:--
whitepaper: https://www.stellar.org/how-it-works/stellar-basics/
priority: low
github group: https://github.com/KomodoPlatform
note: ranked top : NA

**Comment by berlinguyinca** [comment]
could we please get this added?

**Comment by berlinguyinca** [comment]
does a tutorial/spec exist how to add an exchange, datamodel etc?

**Comment by kroitor** [comment]
@berlinguyinca 
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md
- https://github.com/ccxt/ccxt/blob/skeleton/examples/js/skeleton.js

**Comment by berlinguyinca** [comment]
thanks. I look into it
