### ISSUE TITLE
Bitfinex v2 fetch_markets() all price precisions are None

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#13769]
- OS: Linux Mint
- Programming Language version: Python 3.10
- CCXT version: 1.86.23

```
exchange = ccxt.bitfinex2()
print(exchange.fetch_markets())
```

```
...
{'id': 'tDUSK:BTC', 'symbol': 'DUSK/BTC', 'base': 'DUSK', 'quote': 'BTC', 'settle': None, 'baseId': 'fDUSK', 'quoteId': 'fBTC', 'settleId': 'fBTC', 'type': 'spot', 'spot': True, 'margin': False, 'swap': False, 'future': False, 'option': False, 'active': True, 'contract': False, 'linear': None, 'inverse': None, 'contractSize': None, 'expiry': None, 'expiryDatetime': None, 'strike': None, 'optionType': None, 'precision': {'amount': 8, 'price': None}, 'limits': {'leverage': {'min': None, 'max': None}, 'amount': {'min': 18.0, 'max': 100000.0}, 'price': {'min': 1e-08, 'max': None}, 'cost': {'min': None, 'max': None}}, 'info': [None, None, None, '18.0', '100000.0', None, None, None, None, None, None, None]}
...
```

All 'price' precisions are None. The information is not available in the 'info' section either. I believe this is because the end point to fetch this info was changed in the ccxt code recently.

**Comment by carlosmiei** [comment]
Hello @JovianMoon, thanks for letting us know, will be fixed very soon

**Comment by carlosmiei** [comment]
@JovianMoon sorry I misinterpreted the issue initially, as you said the information is not available in v2 and yes we recently updated fetch_markets to use v2 because we need to follow exchanges' recommendations and adopt their new api versions because they add new features, and eventually v1 will be deprecated. Nonetheless, v2 is not in the final state yet so this information might be added in the future we'll pay attention to that. Moreover, if that information is crucial to you, consider using the **bitfinex** (v1) instead of bitfinex2 (v2).

**Comment by JovianMoon** [comment]
@carlosmiei Ok, I actually did not notice earlier that their v2 was still in beta. I guess that's a good reason to not mix v1 among v2 enpoints.

**Comment by JovianMoon** [comment]
@carlosmiei I suppose this is kind of a bug in line 521 of bitfinex2.py, because the code is still trying to parse the price precision from the old v1 response. Does not really affect anything though:
```
                    'price': self.safe_integer(market, 'price_precision'),
```

**Comment by carlosmiei** [comment]
@carlosmiei you're right I had my master branch outdated so I got confused for a bit I'm sorry for that. I'll fix that line soon

**Comment by JovianMoon** [comment]
@carlosmiei Just noticed that having all price precisions as None makes it impossible to create orders:

```
exchange = ccxt.bitfinex2({...})
exchange.load_markets()
exchange.create_limit_buy_order('EOS/ETH', '100', '0.00072222')
```

```
Traceback (most recent call last):
...
    exchange.create_limit_buy_order('EOS/ETH', '100', '0.00072222')
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2868, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', amount, price, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/bitfinex2.py", line 1473, in create_order
    request['price'] = self.price_to_precision(symbol, price)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2885, in price_to_precision
    return self.decimal_to_precision(price, ROUND, market['precision']['price'], self.precisionMode, self.paddingMode)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/base/decimal_to_precision.py", line 37, in decimal_to_precision
    assert precision is not None
AssertionError
```
... but looks like you already noticed that and price precision is going to be 5 for all pairs for now.

By the way, I'm not totally sure about this, but I think prices might have a second rule too: it seems that there are never more than 8 digits after the decimal point (I didn't check all pairs though).
