### ISSUE TITLE
CoinEx fetch_my_trades() unnecessarily requires 'symbol'?

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#13771]
- OS: Linux Mint
- Programming Language version: Python 3.10
- CCXT version: 1.86.37

```
exchange = ccxt.coinex({...})
exchange.fetch_my_trades()
```

```
Traceback (most recent call last):
...
    print(exchange.fetch_my_trades())
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/coinex.py", line 2461, in fetch_my_trades
    raise ArgumentsRequired(self.id + ' fetchMyTrades() requires a symbol argument')
ccxt.base.errors.ArgumentsRequired: coinex fetchMyTrades() requires a symbol argument
```

According to CoinEx API documentation (https://viabtc.github.io/coinex_api_en_doc/spot/#docsspot003_trade014_user_deals) market name is not required for calling "/order/user/deals" end point for spot markets, but ccxt is requiring 'symbol' for `fetch_my_trades` call by default. Does CoinEx have wrong info in their documentation, or is this a ccxt bug?

CoinEx futures markets do require the market name to be defined btw:
https://viabtc.github.io/coinex_api_en_doc/futures/#docsfutures001_http013_user_deals

**Comment by carlosmiei** [comment]
Hello @JovianMoon you're totally right, thanks for letting us know will be fixed soon
