### ISSUE TITLE
How to work with OKX exchange?

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#13789]
Hey guys. I am trying to make OKX orders on spot and futures. This exchange has one and the same wallet for spot and futures trades. So, accessing OKX with code below easy give an opportunity to make spot orders.
```
 okx_spot = ccxt.okx({
        "apiKey": config.OKX_API_KEY,
        "secret": config.OKX_SECRET_KEY,
        "password": config.OKX_PASSWORD,
        "options": {'defaultType': 'spot'}
    })
```
  But this one makes orders on spot market as well, not on futures. 
```
 okx_futures = ccxt.okx({
        "apiKey": config.OKX_API_KEY,
        "secret": config.OKX_SECRET_KEY,
        "password": config.OKX_PASSWORD,
        "options": {'defaultType': 'futures'}
    })
balance = float(okx_futures.fetch_balance()["free"]["USDT"])
price = .okx_futures.fetch_ticker('GMT/USDT')["last"]
amount = float(balance / price)*robot.okx_leverage
params = {"mgnMode" : "isolated"}
okx_futures.set_leverage(2, "GMT/USDT", params)
.okx_futures.create_market_buy_order("GMT/USDT", amount)
```
So how i can trade on futures market with ccxt?

**Comment by kroitor** [comment]
Use the unified contract symbols for placing orders with perpetual future swaps, futures and other contracts:

- https://docs.ccxt.com/en/latest/manual.html#contract-naming-conventions
- https://github.com/ccxt/ccxt/issues/10931

```Python
exchange = ccxt.okx()
markets = exchange.load_markets()
for symbol in exchange.symbols:
    market = exchange.market(symbol)
    print(market['symbol'], 'is a', market['type'], 'market')
```

-------

```Python
 okx_futures = ccxt.okx({
        "apiKey": config.OKX_API_KEY,
        "secret": config.OKX_SECRET_KEY,
        "password": config.OKX_PASSWORD,
        "options": {'defaultType': 'swap'}
    })
symbol = 'GMT/USDT:USDT'
balance = float(okx_futures.fetch_balance()["free"]["USDT"])
price = okx_futures.fetch_ticker(symbol)["last"]
amount = 1  # how many contracts you want to buy
params = {"mgnMode" : "isolated"}
okx_futures.set_leverage(2, symbol, params)
okx_futures.create_market_buy_order(symbol, amount)
```

**Comment by KindSpidey** [comment]
Love you man. Thank you very much!

**Comment by KindSpidey** [comment]
It brings error `ccxt.base.errors.BadRequest: okx {"code":"51000","data":[],"msg":"Parameter posSide  error"}`

**Comment by KindSpidey** [comment]
```
symbol = 'GMT/USDT:USDT'
balance = float(robot.okx_futures.fetch_balance()["free"]["USDT"])
price = robot.okx_futures.fetch_ticker(symbol)["last"]
amount = 1  # how many contracts you want to buy
params = {"mgnMode" : "isolated", "posSide" : "long" }
robot.okx_futures.set_leverage(2, symbol, params)
robot.okx_futures.create_market_buy_order(symbol, amount)
```

`ccxt.base.errors.BadRequest: okx {"code":"1","data":[{"clOrdId":"e847386590ce4dBC920edbd43cd5c7ce","ordId":"","sCode":"51000","sMsg":"Parameter posSide  error ","tag":""}],"msg":"Operation failed."}`

**Comment by frosty00** [comment]
does it work if you don't send the posSide param, or posSide: both?

**Comment by KindSpidey** [comment]
with "net" getting `ccxt.base.errors.BadRequest: okx {"code":"51000","data":[],"msg":"Parameter posSide  error"}`
without posSide getting `ccxt.base.errors.BadRequest: okx {"code":"51000","data":[],"msg":"Parameter posSide  error"}`

**Comment by boy-be-ambitious** [comment]
> with "net" getting `ccxt.base.errors.BadRequest: okx {"code":"51000","data":[],"msg":"Parameter posSide error"}` without posSide getting `ccxt.base.errors.BadRequest: okx {"code":"51000","data":[],"msg":"Parameter posSide error"}`

hi @KindSpidey , Did you resolve the "pos" issue with the future contract on the OKEX exchange later on?

**Comment by unsphere** [comment]
I am facing the same issue. Could someone please provide a working example?

```javascript
const params = { mgnMode: 'isolated', posSide: 'long' };
const leverage = await exchange.setLeverage(10, symbol, params);
const order = await exchange.createMarketBuyOrder(symbol, 1);
```

BadRequest: okx {"code":"51000","data":[],"msg":"Parameter posSide  error"}

**Comment by d0ksan8** [comment]
any update?

**Comment by carlosmiei** [comment]
@installKnox CCXT assumes you're in the one-way mode, if you're using the `hedged` position mode oyu just need to provide `{"hedged": true}` in `params` upon placing an order
