### ISSUE TITLE
Mark Price in SPOT for Binance

### ISSUE THREAD

**Issue by deepak0418** [ccxt/ccxt#13784]
How to get Binance SPOT MARK price in python?

**Comment by carlosmiei** [comment]
Hello @deepak0418.

Although mark price uses the spot price of a market in its formula (among other metrics) it is actually a futures concept, and is used to estimate the fair value of a contract, so 'spot mark price' is not quite correct.

More info about it: https://www.binance.com/en/support/faq/fff6ec1b3f5845d19f1fb924644a0877

Nonetheless, if you actually wanted to check the mark price of a contract, you can do something like this:

```Python
exchange = ccxt.binanceusdm({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
})

params = {
    'price': 'mark'
}
markPrices = exchange.fetch_ohlcv('BTC/USDT', '1m', None, None, params)
```
