### ISSUE TITLE
The problem of Gate.io's privateFuturesPostSettlePriceOrders' price

### ISSUE THREAD

**Issue by Ben0ni** [ccxt/ccxt#13801]
Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Ubuntu
- Programming Language version: Python 3.7.0
- CCXT version:1.79.88

```
short_sl_order = exchange.privateFuturesPostSettlePriceOrders({"initial": {"contract": "BTC_USDT", "size": 0, "price": 0, "tif": "gtc", "reduce_only": True},
                                              "trigger": {"strategy_type": 0, "price_type": 0, "price": short_sl_price, "rule": 1},
                                              "order_type": "plan-close-short-position", 'settle': 'usdt'})
```

```
gateio {“label“:“AUTO_INVALID_REQUEST_BODY“,“message“:“invalid json json: cannot unmarshal number into Go struct field FutureReqOrder.initial.price of type string“}

```

I don't know why this happened.
the variable short_sl_price is str. Do I need to use float to do it?

Could you please help me?
Thank you very much.

**Comment by DoctorSlimm** [comment]
@Ben0ni are you using ccxtpro? it looks like that might be a websocket endpoint judging by their docs

**Comment by Ben0ni** [comment]
I used float type to do it.
It also has the same problem.
I am so confused why it happened.
I mean, if I have a short position, for example, I sell at price 10, then I plan to close my order when price over 11.
That is what I want to do.
@samgermain

**Comment by samgermain** [comment]
I recommend to just use the [unified `create_order` method](https://docs.ccxt.com/en/latest/manual.html#orders) and add `stopPrice: short_sl_price` to `params` like

```
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.gateio({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'options': {
        'defaultType': 'swap'
    }
})

markets = exchange.load_markets()
# exchange.verbose = True  # uncomment for debugging purposes

symbol = 'BTC/USDT'
side = 'buy'
amount = 0.01
price = 25000
stopLossPrice = 25000
type = 'limit'

stopLossOrder = exchange.create_order(symbol, type, side, amount, price, {'stopPrice': stopLossPrice, 'reduceOnly': true})
print(stopLossOrder)
```

-------------------

If you're going to use the implicit methods, you can see the type that gateio requires for each parameter in their [api docs](https://www.gate.io/docs/developers/apiv4/en/#create-a-price-triggered-order-2). These types are not necessarily the same for the unified methods, and you can check the type for the unified methods in the [docstrings](https://github.com/ccxt/ccxt/blob/9648c6f13735a4bc1dab1a9d96219d66ff1be246/js/gateio.js#L2839)

**Comment by Ben0ni** [comment]
So if I use the [unified create_order method](https://docs.ccxt.com/en/latest/manual.html#orders), the result is the same. Right?

**Comment by samgermain** [comment]
> So if I use the [unified create_order method](https://docs.ccxt.com/en/latest/manual.html#orders), the result is the same. Right?

Can you provide your code and the response that you got

**Comment by Ben0ni** [comment]
I tested. It is totally the same. Thank you very much. Hope ccxt better and better.

**Comment by Ben0ni** [comment]
Another question, this is for the long position. When I want to stop loss. For example, if I have a long position, I need to create a when price >= x, then buy. For a short position, I need to when price <= x. However, when I want to close the long position at a lower price, there is a mistake
"gateio {"label":"AUTO_TRIGGER_PRICE_LESS_LAST","message":"invalid argument: Trigger.Price must < last_price"}"

**Comment by samgermain** [comment]
For stop loss, you'll need to set the stop price 

- higher than current for shorts (e.g. if current price is 2, you lose money as the price goes up, so you want a stopPrice higher than 2)
- lower than current for longs

If you need to do the opposite, you'll have to set params equal to something like in your original comment

`params = {"initial": {"contract": "BTC_USDT", "size": 0, "price": 0, "tif": "gtc", "reduce_only": True},
                                              "trigger": {"strategy_type": 0, "price_type": 0, "price": short_sl_price, "rule": 1}`

**Comment by Ben0ni** [comment]
Thank you again, I think now it is clear.
Thank you very much.
