### ISSUE TITLE
There always raise an error when I use inner transfer coin in Kucoin 

### ISSUE THREAD

**Issue by ldkklj** [ccxt/ccxt#13808]
- OS:Linux
- Programming Language version:Python 3.8.5
- CCXT version:`1.86.93`
mycode:

```
    try:
        if exchange.id=='okex':
            response = exchange.transfer(coin,amount,'6','18',params={})
        elif exchange.id == 'kucoin':
            response = exchange.transfer(coin, amount, 'main', 'trade', params={})
        print(response)
    except Exception as e:
        print('\n\nError in innertransfer() ', e)
        return None
```

and coin =='LUNC' and amount ==2500
always raise a Exception:
'\'NoneType\' object has no attribute \'lower\''

**Comment by pcriadoperez** [comment]
Thanks @ldkklj  for opening the issue. I opened a PR to solve the issue: https://github.com/ccxt/ccxt/pull/13811
