### ISSUE TITLE
ccxt.base.errors.BadSymbol: ftx does not have market symbol BTC/USD:USD

### ISSUE THREAD

**Issue by qwe231cvb** [ccxt/ccxt#13809]
I want to buy BTC/USD perpetual contract at market price

But is shows error as follows:
ccxt.base.errors.BadSymbol: ftx does not have market symbol BTC/USD:USD

The code as follows:
```
symbol = 'BTC/USD:USD'
btc_price = ftx.fetch_ticker("BTC/USD")['bid']
btc_amount = 20 / btc_price
create_order = ftx.create_order(symbol, 'market', 'buy', btc_amount)

```

**Comment by alphatio** [comment]
try `BTC-PERP`

**Comment by kroitor** [comment]
@qwe231cvb please, paste your complete code, versions and verbose output without your keys:

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.ftx({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
markets = exchange.load_markets()
symbol = 'BTC/USD:USD'
market = exchange.market(symbol)
pprint(market)
exchange.verbose = True
btc_price = exchange.fetch_ticker(symbol)['bid']
btc_amount = 20 / btc_price
create_order = exchange.create_order(symbol, 'market', 'buy', btc_amount)
```

**Comment by qwe231cvb** [comment]
> @qwe231cvb please, paste your complete code, versions and verbose output without your keys:
> 
> ```python
> import ccxt
> from pprint import pprint
> print('CCXT Version:', ccxt.__version__)
> exchange = ccxt.ftx({
>     'apiKey': 'YOUR_API_KEY',
>     'secret': 'YOUR_SECRET',
> })
> markets = exchange.load_markets()
> symbol = 'BTC/USD:USD'
> market = exchange.market(symbol)
> pprint(market)
> exchange.verbose = True
> btc_price = exchange.fetch_ticker(symbol)['bid']
> btc_amount = 20 / btc_price
> order = exchange.create_order(symbol, 'market', 'buy', btc_amount)
> pprint(order)
> ```

the modify as follows:
```
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
ftx = ccxt.ftx({
    'apiKey': 'my_apikey',
    'secret': 'my_secret',
})
markets = ftx.load_markets()
symbol = 'BTC/USD:USD'
market = ftx.market(symbol)
pprint(market)
ftx.verbose = True
btc_price = ftx.fetch_ticker(symbol)['bid']
btc_amount = 20 / btc_price
order = ftx.create_order(symbol, 'market', 'buy', btc_amount)
pprint(order)
```
The errors as follows:
CCXT Version: 1.64.28
Traceback (most recent call last):
  File "C:\Users\fxu50\PycharmProjects\pythonProject1\contract.py", line 40, in <module>
    market = ftx.market(symbol)
  File "C:\Users\fxu50\PycharmProjects\pythonProject1\ccxt\base\exchange.py", line 2054, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: ftx does not have market symbol BTC/USD:USD

**Comment by kroitor** [comment]
@qwe231cvb your version of CCXT is too old. Please, upgrade to 1.87.8+. Let us know if that does not resolve this issue for you.

**Comment by qwe231cvb** [comment]
> try `BTC-PERP`. You may also want to use `amount_to_precision` https://docs.ccxt.com/en/latest/manual.html#precision-and-limits

Changing to 'BTC-PERP' is valid,I have a another question,
This line of code will output a large number of contract market data,
···
symbol = 'BTC-PERP'
market = ftx.market(symbol)
pprint(market)
···
But I just want to get the market price of the contract, how to get only the market price of the contract?

**Comment by kroitor** [comment]
> how to get only the market price of the contract?

```Python
symbol = 'BTC-PERP'
ticker = ftx.fetch_ticker(symbol)
only_the_price = ticker['last']
print(only_the_price)
```

**Comment by qwe231cvb** [comment]
> @qwe231cvb your version of CCXT is too old. Please, upgrade to 1.87.8+. Let us know if that does not resolve this issue for you.

When I upgrade to CCXT version 1.87.10, I can use `symbol = 'BTC/USD:USD'`

**Comment by kroitor** [comment]
@qwe231cvb yes, check this related issue on contract naming, it is relatively new: 

- https://github.com/ccxt/ccxt/issues/10931
- https://docs.ccxt.com/en/latest/manual.html#contract-naming-conventions

**Comment by qwe231cvb** [comment]
I have another question,
The code below works fine, but it doesn't seem to output the market price.
```
ftx.load_markets()
symbol = 'BTC/USD:USD'
btc_price = ftx.fetch_ticker(symbol)
pprint(btc_price['bid'])
```

The following code seems to output the market price, but it shows an error, 
```
ftx.load_markets()
symbol = 'BTC/USD:USD'
market = ftx.market(symbol)
pprint(market['bid'])
```
the error is as follows:
Traceback (most recent call last):
  File "C:\Users\fxu50\PycharmProjects\pythonProject1\contract.py", line 19, in <module>
    pprint(market['bid'])
KeyError: 'bid'

**Comment by kroitor** [comment]
@qwe231cvb with ftx the market price you get from `ftx.market(symbol)` is the same as the ask price of a ticker, any of the following will work:

```Python
ftx.load_markets()
symbol = 'BTC/USD:USD'
market = ftx.market(symbol)
pprint(market['info']['price'])
```

```Python
ftx.load_markets()
symbol = 'BTC/USD:USD'
market = ftx.market(symbol)
pprint(market['info']['ask'])
```

```Python
ftx.load_markets()
symbol = 'BTC/USD:USD'
market = ftx.fetch_ticker(symbol)
pprint(ticker['ask'])
```

**Comment by qwe231cvb** [comment]
The following code Bitcoin price is 25182.0,It seems is not market price.
```
ftx.load_markets()
symbol = 'BTC/USD:USD'
market = ftx.fetch_ticker(symbol)
pprint(market['ask'])
```
The following code Bitcoin price is 25140.0,It seems is market price.
```
ftx.load_markets()
symbol = 'BTC/USD:USD'
market = ftx.market(symbol)
pprint(market['info']['price'])

ftx.load_markets()
symbol = 'BTC/USD:USD'
market = ftx.market(symbol)
pprint(market['info']['ask'])
```

**Comment by qwe231cvb** [comment]
The following code shows error,the code as follows:
```
ftx.load_markets()
symbol = 'BTC/USD:USD'
market = ftx.market(symbol)
pprint(market['info']['price'])
btc_amount = 20 / market['info']['price']
create_order = ftx.create_order(symbol, 'market', 'buy', btc_amount)
```
The error as follows:
TypeError: unsupported operand type(s) for /: 'int' and 'str'

It seems that you need to convert characters to integers to place an order. How to convert characters to integers,

**Comment by kroitor** [comment]
@qwe231cvb it is documented in the Manual that the `info` subdictionary will contain the exchange response as is:

- https://docs.ccxt.com/en/latest/manual.html#market-structure

So if you're using the exchange-specific things from `info`, then you will have to convert the string to a float on your own. I mean, it's really not a question about using CCXT, but more of a question on how to use Python:

```Python
ftx.load_markets()
symbol = 'BTC/USD:USD'
market = ftx.market(symbol)
pprint(market['info']['price'])
btc_amount = 20 / float(market['info']['price'])
create_order = ftx.create_order(symbol, 'market', 'buy', btc_amount)
```

**Comment by qwe231cvb** [comment]
Characters can now be converted to floats,the code as follows:
```
ftx.load_markets()
symbol = 'BTC/USD:USD'
market = ftx.market(symbol)
pprint(market['info']['price'])
b = market['info']['price']
a = float(b)
pprint(a)
btc_amount = 20 / a
create_order = ftx.create_order(symbol, 'market', 'buy', btc_amount)
```
