### ISSUE TITLE
How to make StopLoss orders on exchanges with ccxt?

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#13816]
Hey guys. I've discovered all your issues with stopLosses and read docs, but didnt find the answer to how to create stopLoss orders. What I mean exactly: stop loss orders must be not conditional orders, because if so, they are blocking function to sell coins. When real stop losses (TP/SL on exchanges) allows users to sell their coins, when they have stop loss active order.

Can you give an example of how to do it on some of them: OKX, Kucoin, MEXC, Gateio, Bybit, Huobi?

**Comment by samgermain** [comment]
I just created [an issue to unify the params `stopLossPrice` and `takeProfitPrice` in `createOrder`](https://github.com/ccxt/ccxt/issues/13822), it's not unified in very many exchanges currently

**Comment by samgermain** [comment]
I'm going to close this issue. You can follow the progress of the `stopLossPrice` and `takeProfitPrice` parameters for createOrder on #13822
