### ISSUE TITLE
The withdraw func made me crazy~!!!!

### ISSUE THREAD

**Issue by ldkklj** [ccxt/ccxt#13849]
- OS:Linux
- Programming Language version: python3.8.5
- CCXT version:1.87.25

```
okex.withdraw(code, amount, tgtaddress, tag,params)
coin 'USDT'
amount 50
tagtadrss  : a TRC20 address
tag : None
                params['fee'] = '0.8'
                params['pwd'] = 'fdsafdsaf'
                params['chain'] = 'USDT-TRC20'
```

return OK ,withdraw right

But

```
okex.withdraw(code, amount, tgtaddress, tag,params)
coin 'LUNC'
amount 50000
tagtadrss  : a LUNC address
tag : None
                params['fee'] = '1000'
                params['pwd'] = 'fdsafdsaf'
                params['chain'] = 'LUNC-Terra'
 raise E:"code":10232,"msg":"The currency not exist. Please check coin name and chain is correct."
```
And alsio
```
mexc.withdraw(code, amount, tgtaddress, tag,params)
coin 'USDT'
amount 50
tagtadrss  : a TRC20 address
tag : None
params['chain'] = 'TRC20'
```
 raise E:mexc {"code":10232,"msg":"The currency not exist. Please check coin name and chain is correct."}

Last version seems have less erros.
Please check the withdraw fuction in  OKEX and MEXC,I  have only check these two exchanges but I got so many exceptions which drove me crazy!

**Comment by ldkklj** [comment]
@pcriadoperez
actually ,if I use the TRC-20 chain ,It will also won't work either,I have tried,you can try it.I read the mexc.py code ,actually you translate TRX and TRC20 to TRC-20 in the withdraw function, So I can't really find where the problem is.
Hope the unifying network will be active soon ,it will be a gread achievement.Thank you .

**Comment by kroitor** [comment]
@ldkklj i suggest using the unified `network` param, since `chain` is exchange-specific.

```Python
mexc.withdraw(code, amount, tgtaddress, tag, {'network':'TRC20})
```

Let us know if that does not help.

**Comment by Maciejrybak4** [comment]
maciek.rybak21@op.pl
