### ISSUE TITLE
GDAX create limit buy and sell orders

### ISSUE THREAD

**Issue by kz0** [ccxt/ccxt#1388]
- OS: Ubuntu 16.04.3 LTS 
- Programming Language version: Python 3.5.1
- CCXT version: 1.10.749
- Exchange: GDAX
- Method: exchange.create_limit_buy_order and exchange.create_limit_sell_order

When trying to post a buy order i receive the following error: 
```ccxt.base.errors.ExchangeError: gdax {"message":"Insufficient funds"}```

I'm fetching the first bid and truncating to get the amount without float rounding to 8 decimals with the following code:
```price = exchange.fetch_l2_order_book(symbol)['bids'][0][0]```
```amount = math.trunc(pow(10.0, 8) * (quote_balance / price)) / pow(10.0, 8)```

Lowering the bid price buy 10 also causes the same error.

As for the limit sell order the order was filled as taker instead of maker so the fees were applied. Is there a way to force maker orders always?

**Comment by kroitor** [comment]
> When trying to post a buy order i receive the following error: `ccxt.base.errors.ExchangeError: gdax {"message":"Insufficient funds"}`

Your balance should have amount * price + fee, to make it sufficient.

> Is there a way to force maker orders always?

No, it depends on the price and volume. But you can't force it. It's the exchanges business.

Let us know if it doesn't help.

**Comment by kz0** [comment]
> Your balance should have amount * price + fee, to make it sufficient.

 The fees are always 0 as maker so the price + fee is always the price.

**Comment by kroitor** [comment]
@kz0 

> The fees are always 0 as maker so the price + fee is always the price.

That is only true, if you are guaranteed to be a maker. But you're not guaranteed to be a maker, so the above sentence is false, right?

**Comment by kz0** [comment]
Yeah, i'm trying to post orders only as maker, reading the GDAX API passing post_only like this
```exchange.create_limit_buy_order(symbol, amount, price, { 'post_only': 'true' })```
should prevent buying/selling as taker?

**Comment by wannesdemaeght** [comment]
Problem of insufficient funds is because of this:
quote_balance / price

say you have 10 eth, trading at 0.09 btc, you'd be trying to sell 111.11 eth...

maker or taker is only defined by the price. 
If you post a limit SELL order equal or higher to lowest ask, it's a maker order.
If you post a limit BUY order equal or lower to highest bid, it's a maker order.

Basically, if you post a trade which will get filled immediately, you're a taker.

**Comment by kroitor** [comment]
@kz0 

- https://support.gdax.com/customer/en/portal/articles/2625326-enabling-%22post-only%22-for-limit-orders this page says, that setting the `post_only` flag will guarantee a maker order or will throw an error
- https://docs.gdax.com/#place-a-new-order this page, however, does not document possible types of values for that flag, but if you search for other appearances of `post_only` within that doc you will notice, that it is a boolean `true` or `false`, not a string (not `'true'`, nor `'false'`). Try `exchange.create_limit_buy_order(symbol, amount, price, { 'post_only': true })`. Hope it helps.

**Comment by kz0** [comment]
> Problem of insufficient funds is because of this:
quote_balance / price

That is only for the buying amount. If i had 10 ETH to sell my order amount would be my base balance.

> Try exchange.create_limit_buy_order(symbol, amount, price, { 'post_only': true }). Hope it helps.

I've tested with the string first and it works, going to change it to bool to see if it works too.
Thank you for your help.
