### ISSUE TITLE
Consistent way to get filled market orders

### ISSUE THREAD

**Issue by CodingCryptoTrading** [ccxt/ccxt#13889]
- Programming Language version: python
- CCXT version: '1.77.5'

I am trying to create a dca bot that can work on various exchanges. I have trouble retrieving the results (price, amount, cost, filled ...) of market orders in a way that works consistently regardless of the exchange you choose.

With Binance, I only need to look at the results of: 
```
order = self.exchange.create_order(symbol, type_order, side, amount, price)
```
But I realized that for other exchanges, as FTX, that doesn't work. So, I have to fetch_order using the order ID: 
```
order = self.exchange.create_order(symbol, type_order, side, amount, price)
order = self.exchange.fetch_order(order['id'], symbol)
```
I thought the above would resolve any problem, since it does work with FTX. Surprisingly, the above doesn't work with Kucoin. Even after fetch_order, the fields are null/zero and the "status" is still "open". 

I thought maybe I need to give some time to the exchange to fill the order, so I wrote the following:
```
order = self.exchange.create_order(symbol, type_order, side, amount, price)
# for some exchanges (as FTX) the order must be retrieved to be updated
waiting_time = 0.25; total_time = 0
while order['status'] == 'open':
        if total_time > 1:
               raise Exception("The exchange did not return a closed order")
        time.sleep(waiting_time)  # let's give the exchange some time to fill the order
        order = self.exchange.fetch_order(order['id'], symbol)
        total_time += waiting_time
```
 But, it's even worse now. Now, the "status" field is null too. 

How can I collect the result of a market order in a reliable way (i.e., that works on every (or almost all) exchanges)? Thank you!

**Comment by samgermain** [comment]
Some exchanges won't return all the fields, so CCXT fills in the fields that are available, and sets the field to None otherwise. 

You can look inside the value for `info` to see if there's other information that you might find useful, and if you notice a value in info that could be used for one of the fields that's set to None, then we can update it.

It's also possible that the exchange api has posted a new api endpoint that we haven't seen yet, so if you notice something on the exchange api, we could update that too

> Even after fetch_order, the fields are null/zero and the "status" is still "open".

What should it be? Why would calling `fetch_order` change the status of the order to other than open?

**Comment by CodingCryptoTrading** [comment]
I was referring to very basic fields of a **market order**, such as  *price*, *amount*, *cost* and *filled*. 

Actually, calling `fetch_order` after a `create_order` does populate the missing fields in FTX. It also does work for kucoin, but it seems that I have to wait some time to ensure that the market order is filled and the position is closed. 
Indeed, I found out that the code I posted above works if I replace the while condition from 
```while order['status'] == 'open':``` 
 to:
```while order['status'] != 'closed'):```


I just wandering if this strategy is going to work for every exchange. Or perhaps there is a more reliable strategy, such as fetching trades?

Thanks

**Comment by samgermain** [comment]
> I was referring to very basic fields of a **market order**, such as  *price*, *amount*, *cost* and *filled*. 

No matter how basic they are, if the exchange doesn't return them, then we can't provide them in the response. You can double check the info parameter in the response and if the information isn't in there then we can't provide it.

> I'm just wondering if this strategy will work for every exchange. Or perhaps there is a more reliable strategy, such as fetching trades?

`fetchMyTrades`, `fetchOrder`, `fetchClosedOrders` are the only kinds of methods I can think of that would work for what you want

**Comment by CodingCryptoTrading** [comment]
Ok, thanks
