### ISSUE TITLE
How can I sell all of a specific token in my account?

### ISSUE THREAD

**Issue by shep-analytics** [ccxt/ccxt#13886]
- OS: OSX
- Programming Language version: python3.9
- CCXT version: latest

I want to sell all of the AXS (a smaller-cap token) in my FTX account.
My FTX account has 130.8238727 AXS  in it.
When I run ftx.fetchBalance(), I can pull that number, and I save it as position_info['spot_held'].

I then try to sell it all on the spot market.

```
submission = ftx.create_order ("AXS/USD", 'market', side='sell', amount=abs(position_info["spot_held"]),  params={"reduceOnly": True})
```

But I am then greeted with an Insufficient Funds error:

```
ccxt.base.errors.InsufficientFunds: ftx {"success":false,"error":"Not enough balances"}
```

Why can't I sell all of the tokens in my account, and if I can't sell them all, how can I pass an argument to sell as many as allowed?

Thank you

**Comment by pier0074** [comment]
Hello @shep-analytics 

The code you are using works fine with me.
I assume the error comes from the fact that you are trying to sell more than what you have.

Could you please share the result of ftx.fetchBalance() ?

Note that there are 2 balances for a coin: free and total. 
You can only sell the free balance which is equal to total - all pending orders that you have placed.
So if you have current pending orders for AXS, they are not considered free anymore and cannot be sold.
You can either cancel all orders on AXS and execute your code again, or sell only the free balance of AXS.

Hope it helps.

**Comment by ttodua** [comment]
@pier0074 thank you for your assistance to OP , appreciated !
@shep-analytics can you share your follow-up about that incident - have you been able to figure out the reason?
side-note: `reduceOnly` flag wouldnt do anything extra, as it's spot order for sell, so it was enough. for swap's `reduceOnly` flag plays important role, but that was not your issue. as @pier0074  noted, ccxt works well with that code and have no issues. I doubt that there might have been some accidental issue in userland code. 
Also, consider updating ccxt to latest version and let us know if you have other issues.
