### ISSUE TITLE
okx rate-limit incorrect

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#13883]
- OS: linux
- Programming Language version: python
- CCXT version:  1.87.54

When using asyncio to retrieve a lot of leverage tiers - it becomes apparent that the rate-limit for that endpoint is incorrect.
In my understanding, ccxt's throttler should kick in based on configured rate-limits - and not make the requests to the exchange too often.

based on the below - i'd expect no output other than the "128" for the length of pairs.

``` python
import ccxt.async_support as ccxt_async
exchange = ccxt_async.okx({'options': {'defaultType': 'swap'}, 'enableRateLimit': True})

import asyncio
async def fetch_levt(p):
    try:
        return await exchange.fetch_market_leverage_tiers(p)
    except Exception as e:
        print(p)
        print(e)
        return None

async def test():
    lt = []
    m = await exchange.load_markets()
    for p in m.keys():
        if p.endswith(':USDT'):
            lt.append(fetch_levt(p))
    print(len(lt))
    await asyncio.gather(*lt, return_exceptions=True)

asyncio.run(test())
```

```
128
1INCH/USDT:USDT
okx {"msg":"Requests too frequent.","code":"50011"}
BSV/USDT:USDT
okx {"msg":"Requests too frequent.","code":"50011"}
ENJ/USDT:USDT
okx {"msg":"Requests too frequent.","code":"50011"}
ICP/USDT:USDT
okx {"msg":"Requests too frequent.","code":"50011"}
NFT/USDT:USDT
okx {"msg":"Requests too frequent.","code":"50011"}
SAND/USDT:USDT
okx {"msg":"Requests too frequent.","code":"50011"}
THETA/USDT:USDT
okx {"msg":"Requests too frequent.","code":"50011"}
XLM/USDT:USDT
okx {"msg":"Requests too frequent.","code":"50011"}

```

there are however quite some `okx {"msg":"Requests too frequent.","code":"50011"}` messages mixed in - causing a delay in operations.

Now obviously we can handle this and retry (freqtrade does so) - but it's still slowing us down more than it should.
It doesn't seem "too far" off - but just slightly - enough to cause an exception on 8 out of 128 requests - so roughly one every 16 requests.

Based on the docs - the rate-limit for this endpoint should be `Rate Limit: 10 requests per 2 seconds` ... it's currently set to "2"  - but it's unclear to me what unit "2" is in.
(https://github.com/ccxt/ccxt/blob/bbda875a9de4209535afe6987a14534204dcae42/js/okx.js#L170)

**Comment by DoctorSlimm** [comment]
@xmatthias the `rateLimit` property of the exchange represents the number of `ms` between calls **for the cheapest endpoint**, this endpoint will have a `weight` of `1`, the number on each endpoint endpoint represents `weight`. The `rateLimit` * `weight` = `ms between calls for this endpoint`. So in this case `100` * `2` = `200ms` between calls to the endpoint, which is effectively `1000ms / 200ms = 5` calls per second so 10 calls per 2 seconds. 

What your experiencing is likely a known issue with `ccxt asyncio` in `python`,  and it is being worked on to be fixed asap, due to the leaky bucket algorithm, which is implemented in the throttler, sometimes it sends an extra request or two, and some exchanges are extremely strict of this, and others are not.

**Comment by samgermain** [comment]
> @xmatthias the `rateLimit` property of the exchange represents the number of `ms` between calls **for the cheapest endpoint**, this endpoint will have a `weight` of `1`, the number on each endpoint represents `weight`. The `rateLimit` * `weight` = `ms between calls for this endpoint`. So in this case `100` * `2` = `200ms` between calls to the endpoint, which is effectively `1000ms / 200ms = 5` calls per second so 10 calls per 2 seconds.
> 
> What your experiencing is likely a known issue with `ccxt asyncio` in `python`, and it is being worked on to be fixed asap, due to the leaky bucket algorithm, which is implemented in the throttler, sometimes it sends an extra request or two, and some exchanges are extremely strict of this, and others are not.

Are there any PRs or branches I can look at that are fixing this?

**Comment by frosty00** [comment]
@xmatthias the code works for me, could be a  variety of factors causing you to hit the ratelimit, including:

- buffering on your computer local socket
- buffering on your NAT router
- buffering on your ISP

please connect to a fast internet server like an AWS machine and let me know if the issue persists

**Comment by frosty00** [comment]
> What your experiencing is likely a known issue with ccxt asyncio in python, and it is being worked on to be fixed asap, due to the leaky bucket algorithm, which is implemented in the throttler, sometimes it sends an extra request or two, and some exchanges are extremely strict of this, and others are not.

Actually there is no issue here, it's working as intended. It has the capacity for an extra request which allows markets to load faster

**Comment by frosty00** [comment]
also if you're on windows it's more likely that you will have this issue since the internet stack latencies are likely to be higher
