### ISSUE TITLE
Can't fetch positions for specific symbol on Kucoin Futures

### ISSUE THREAD

**Issue by maciekzygmunt** [ccxt/ccxt#13881]
- Programming Language version: python 3.10
- CCXT version: 1.87.54

I updated ccxt to latest version and fetch_positions(symbols='XBTUSDTM') stopped working.

```
client.fetch_positions(symbols='XBTUSDTM')
```
Error which i get:
```
ccxt.base.errors.BadSymbol: kucoinfutures does not have market symbol X
```

**Comment by kroitor** [comment]
@maciekzygmunt nevermind, the fetchPositions `symbols` argument must be an array, not a string:

```
client.fetch_positions(symbols=['SYMBOL1', 'SYMBOL2'], ...)
```
