### ISSUE TITLE
Calculating LOT Size In OKX

### ISSUE THREAD

**Issue by buckydroid** [ccxt/ccxt#13892]
I just started using CCXT few days ago. Just wondering if there's any easy or direct way to calculate future lot size on OKX or do I have to calculate it manually?

For example,
Is there any API which can take the available USDT as an input and give the max lot size in return?

Currently I'm doing something like this,

```
def fetch_order_qty(symbol):
    
    leverage = 10

    balance_req = okx.fetchBalance()
    balance = balance_req['free']['USDT']
    ticker_req = okx.fetchTicker(symbol)
    ticker_cost = ticker_req['bid']

    # risking 10% of the available capital
    trade_capital = 10/100*balance
    
    ticker_qty = (trade_capital / ticker_cost) * leverage  *  lot_multiplier
    return ticker_qty

print(fetch_order_qty('BTC-USDT-SWAP'))  
```
But every symbol got different kind of lots. So is there any ways to calculate it. Or is there a way to just directly buy the order using USDT margin amount without mentioning any LOT quantity using CCXT (OKX) ?

**Comment by kroitor** [comment]
@buckydroid have you checked the `market['contractSize']` ? 

```Python
import ccxt
print ('CCXT Version:', ccxt.__version__)
exchange = ccxt.okx()
markets = exchange.load_markets()
market = exchange.market('BTC/USDT:USDT')  # same as BTC-USDT-SWAP 
print(market['symbol'], 'contractSize =', market['contractSize'])
```

On a sidenote, I'd suggest using the unified contract names: 

- https://github.com/ccxt/ccxt/issues/10931
- https://docs.ccxt.com/en/latest/manual.html#contract-naming-conventions

**Comment by kroitor** [comment]
> Or is there a way to just directly buy the order using USDT margin amount without mentioning any LOT quantity using CCXT (OKX) ?

Yes, with OKX you can do that using the params-overrides in the following manner:

- https://docs.ccxt.com/en/latest/manual.html#overriding-unified-api-params
- https://docs.ccxt.com/en/latest/manual.html#market-buys

```Python
import ccxt
print ('CCXT Version:', ccxt.__version__)
exchange = ccxt.okx({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
    'password': 'YOUR_API_PASSWORD',
})
markets = exchange.load_markets()
# exchange.verbose = True  # uncomment for debugging purposes if necessary
symbol = 'BTC/USDT:USDT'  # same as BTC-USDT-SWAP 
params = {
    'tgtCcy': 'quote_ccy',  # a switch to spend USDT
}
amount = YOUR_USDT_AMOUNT
price = 1  # or set a price for limit orders
order = exchange.create_order(symbol, 'market', 'buy', amount, price, params)
```

Hope that answers your question, let us know if not. Feel free to reopen this issue or just ask further questions if any.

**Comment by buckydroid** [comment]
> @buckydroid have you checked the `market['contractSize']` ?
> 
> ```python
> import ccxt
> print ('CCXT Version:', ccxt.__version__)
> exchange = ccxt.okx()
> markets = exchange.load_markets()
> market = exchange.market('BTC/USDT:USDT')  # same as BTC-USDT-SWAP 
> print(market['symbol'], 'contractSize =', market['contractSize'])
> ```
> 
> On a sidenote, I'd suggest using the unified contract names:
> 
> * [Unified contract naming conventions #10931](https://github.com/ccxt/ccxt/issues/10931)
> * https://docs.ccxt.com/en/latest/manual.html#contract-naming-conventions

Thank you so much. Weird coincidence but I discovered the contract size data and modified the code just 5 minutes ago. Then I received this notification lol.

**Comment by buckydroid** [comment]
> > Or is there a way to just directly buy the order using USDT margin amount without mentioning any LOT quantity using CCXT (OKX) ?
> 
> Yes, with OKX you can do that using the params-overrides in the following manner:
> 
> * https://docs.ccxt.com/en/latest/manual.html#overriding-unified-api-params
> * https://docs.ccxt.com/en/latest/manual.html#market-buys
> 
> ```python
> import ccxt
> print ('CCXT Version:', ccxt.__version__)
> exchange = ccxt.okx({
>     'apiKey': 'YOUR_API_KEY',
>     'secret': 'YOUR_API_SECRET',
>     'password': 'YOUR_API_PASSWORD',
> })
> markets = exchange.load_markets()
> # exchange.verbose = True  # uncomment for debugging purposes if necessary
> symbol = 'BTC/USDT:USDT'  # same as BTC-USDT-SWAP 
> params = {
>     'tgtCcy': 'quote_ccy',  # a switch to spend USDT
> }
> amount = YOUR_USDT_AMOUNT
> price = 1  # or set a price for limit orders
> order = exchange.create_order(symbol, 'market', 'buy', amount, price, params)
> ```
> 
> Hope that answers your question, let us know if not. Feel free to reopen this issue or just ask further questions if any.

I wasn't aware of that. That's gonna save a lot of time.

Btw does that work for all exchanges? Or is the params specific for OKX?

Thanks again.

**Comment by buckydroid** [comment]
> > Or is there a way to just directly buy the order using USDT margin amount without mentioning any LOT quantity using CCXT (OKX) ?
> 
> Yes, with OKX you can do that using the params-overrides in the following manner:
> 
> * https://docs.ccxt.com/en/latest/manual.html#overriding-unified-api-params
> * https://docs.ccxt.com/en/latest/manual.html#market-buys
> 
> ```python
> import ccxt
> print ('CCXT Version:', ccxt.__version__)
> exchange = ccxt.okx({
>     'apiKey': 'YOUR_API_KEY',
>     'secret': 'YOUR_API_SECRET',
>     'password': 'YOUR_API_PASSWORD',
> })
> markets = exchange.load_markets()
> # exchange.verbose = True  # uncomment for debugging purposes if necessary
> symbol = 'BTC/USDT:USDT'  # same as BTC-USDT-SWAP 
> params = {
>     'tgtCcy': 'quote_ccy',  # a switch to spend USDT
> }
> amount = YOUR_USDT_AMOUNT
> price = 1  # or set a price for limit orders
> order = exchange.create_order(symbol, 'market', 'buy', amount, price, params)
> ```
> 
> Hope that answers your question, let us know if not. Feel free to reopen this issue or just ask further questions if any.

I haven't tested it on other crypto. But it's saying "The instrument corresponding to this APE-USDT-SWAP does not support the tgtCcy parameter." error on APE. :(

**Comment by hosseinab** [comment]
> > > Or is there a way to just directly buy the order using USDT margin amount without mentioning any LOT quantity using CCXT (OKX) ?
> > 
> > 
> > Yes, with OKX you can do that using the params-overrides in the following manner:
> > 
> > * https://docs.ccxt.com/en/latest/manual.html#overriding-unified-api-params
> > * https://docs.ccxt.com/en/latest/manual.html#market-buys
> > 
> > ```python
> > import ccxt
> > print ('CCXT Version:', ccxt.__version__)
> > exchange = ccxt.okx({
> >     'apiKey': 'YOUR_API_KEY',
> >     'secret': 'YOUR_API_SECRET',
> >     'password': 'YOUR_API_PASSWORD',
> > })
> > markets = exchange.load_markets()
> > # exchange.verbose = True  # uncomment for debugging purposes if necessary
> > symbol = 'BTC/USDT:USDT'  # same as BTC-USDT-SWAP 
> > params = {
> >     'tgtCcy': 'quote_ccy',  # a switch to spend USDT
> > }
> > amount = YOUR_USDT_AMOUNT
> > price = 1  # or set a price for limit orders
> > order = exchange.create_order(symbol, 'market', 'buy', amount, price, params)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope that answers your question, let us know if not. Feel free to reopen this issue or just ask further questions if any.
> 
> I haven't tested it on other crypto. But it's saying "The instrument corresponding to this APE-USDT-SWAP does not support the tgtCcy parameter." error on APE. :(

hi @kroitor . i have this problem

**Comment by jbolter** [comment]
Looking at the docs `tgtCcy` is only supported for spot.
