### ISSUE TITLE
TypeError ftx.py

### ISSUE THREAD

**Issue by Hadevmin** [ccxt/ccxt#13903]
- OS: Windows 
- Programming Language version: python 3.10
- CCXT Version: 1.87.66

That works in v1.84.70 but now I have an error when I execute this request:
```
exchange = ccxt.ftx({...})
first = 1595808000
end = first + 1796400
request = {'start_time': first, 'end_time': end, }
funding = exchange.fetch_funding_rate_history(symbol, params=request)
```

```
File "ftx.py", line 1300, in fetch_funding_rate_history
    request['end_time'] = int(until / 1000)
TypeError: unsupported operand type(s) for /: 'str' and 'int'
```

**Comment by kroitor** [comment]
@Hadevmin thanks for reporting it, pushed a fix for it in CCXT 1.87.69, the new build will arrive in ~20 minutes. Please, let us know if you have this issue or not after upgrading.

**Comment by Hadevmin** [comment]
@kroitor Thanks for your new build. I'm in v1.87.69 and I don't have the problem of typeError.
But for the request described above, I have a return that is still not identical to the old version. It start from 1653631200(2022-05-27T06:00:00.000Z) to now.
Before I get 500 data from the 1595808000.

Is there a change to execute this request since version 1.84.70?

Thanks you

**Comment by kroitor** [comment]
> Is there a change to execute this request since version 1.84.70?

No, FTX has always aligned their pagination results to end_time, not to start_time. You can verify that if you enable the verbose mode (https://docs.ccxt.com/en/latest/manual.html#troubleshooting) – CCXT does not limit those results. Hence, you get 500 most recent results before the end_time. You will need to paginate in a loop to get the data for the entire desired timerange, as shown, for example, here:

- https://github.com/ccxt/ccxt/blob/master/examples/py/ftx-fetch-all-my-trades.py

Hope that answers your question, let us know if not.

**Comment by Hadevmin** [comment]
@kroitor Thanks you for your answer, I had read the ccxt docs, example and API documentation of FTX several days ago.
And I will test tomorrow to change my code. But I already use pagination in a loop to get the data for the entire desired timerange. And I my code works in 1.84.70 but not in the actual version. But it's not a problem, I will try to change him tomorrow.
Thanks you

**Comment by kroitor** [comment]
@Hadevmin i found one more minor issue there, please, upgrade to 1.87.71 one more time (the build will arrive in 20 minutes, as always), that should now work as it did before. Thanks for your feedback!

**Comment by kroitor** [comment]
Check this example (tested it on my side):

- https://github.com/ccxt/ccxt/blob/master/examples/py/ftx-fetch-all-funding-rate-history.py

```Python
# -*- coding: utf-8 -*-

import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.ftx()

markets = exchange.load_markets ()

# exchange.verbose = True  # uncomment for debugging

all_results = []
symbol = 'BTC/USD:USD'
since = exchange.parse8601 ('2022-01-01T00:00:00.000Z')
limit = None
end_time = exchange.milliseconds()

while True:
    print('------------------------------------------------------------------')
    params = {
        'end_time': int(end_time / 1000),
    }
    results = exchange.fetch_funding_rate_history(symbol, since, limit, params)
    if len(results):
        first = results[0]
        last = results[len(results) - 1]
        end_time = first['timestamp'] - 1
        print('Fetched', len(results), 'funding rates from', first['datetime'], 'till', last['datetime'])
        all_results = results + all_results
        if end_time < since:
            break
    else:
        print('Done')
        break


all_results = exchange.sort_by(all_results, 'timestamp')

print('Fetched', len(all_results), 'funding rates')
for i in range(0, len(all_results)):
    result = all_results[i]
    print(i + 1, result['symbol'], result['datetime'], result['fundingRate'])

```

**Comment by Hadevmin** [comment]
@kroitor thank you very much! My code works again in v1.87.71 . Good job! I'm trying to see how I can help solve the problems I find, but the package is very complicated, I don't have the level to do a PR. But I can comment! Thanks for listening, you are doing a great job!

**Comment by mmehrle** [comment]
Wow this is awesome. I started using FTX's REST API via python and it looked like a nightmare to deal with. Found this by accident and it's a heaven's sent. Thanks a ton Kroiter - ccxt has literally saved me months of coding over the past few years.

**Comment by mmehrle** [comment]
You are too quick Kroiter and probably missed my edit. Question:

Question: The symbol 'BTC/USD:USD' - is that to be used in place of 'BTC-PERP'?

**Comment by mmehrle** [comment]
Another question (sorry): What exchange or what exchanges are those funding rates based on? I don't see a reference to FTX or any other exchange in there.

**Comment by kroitor** [comment]
@mmehrle 

> Question: The symbol 'BTC/USD:USD' - is that to be used in place of 'BTC-PERP'?

Yes, though, the recommended notation is BTC/USD:USD, though BTC-PERP should also be supported:

- https://docs.ccxt.com/en/latest/manual.html#contract-naming-conventions
- https://github.com/ccxt/ccxt/issues/10931

**Comment by mmehrle** [comment]
The perpetual futures funding rates, e.g.:

https://ftx.com/api/futures/

**Comment by kroitor** [comment]
@mmehrle they're coming from FTX directly and FTX has a specification defining those funding rates. In CCXT you can fetch them with a family methods like `exchange.fetch_funding_rate`, `exchange.fetch_funding_rate_history`, etc:

- https://help.ftx.com/hc/en-us/articles/360027946571-Funding

**Comment by mmehrle** [comment]
When I compare the current BTC-PERP print with what FTX shows, it seems there is very little similarity:

4357 BTC/USD:USD 2022-07-01T12:00:00.000Z -1.5e-05

https://www.coinglass.com/FundingRate

**Comment by kroitor** [comment]
@mmehrle i'd suggest asking coinglass about it.

**Comment by mmehrle** [comment]
> @mmehrle they're coming from FTX directly and FTX has a specification defining those funding rates. In CCXT you can fetch them with a family methods like `exchange.fetch_funding_rate`, `exchange.fetch_funding_rate_history`, etc:
> 
> * https://help.ftx.com/hc/en-us/articles/360027946571-Funding

Okay that sounds very promising. Forgive me for being thick but I don't see FTX being mentioned in the code anywhere. Is that implicit? Meaning you internally only pull PFFRs from FTX?

Thanks for any clarification.

**Comment by kroitor** [comment]
@mmehrle CCXT only pulls data from the exchanges first-hand, no other aggregators are used, when you use CCXT you're talking to the exchanges directly.

**Comment by mmehrle** [comment]
No, what I mean is this: WHICH exchange is the funding rate coming from? If you look at coinglass.com for example you'll see that every exchange reports a slightly different perpetual futures funding rate.

There's FTX, ByBit, Gate.io, Binance, etc. etc. Are you pulling the data from FTX or are you pulling it from all of them and are averaging the data? Hope this makes it more clear.

**Comment by mmehrle** [comment]
NEVER MIND I am withdrawing my question. For some reason I missed the first line in your code:

exchange = ccxt.ftx()

Ooops... must get more sleep ;-)
