### ISSUE TITLE
Only binance support future market by set defaultType to future ?

### ISSUE THREAD

**Issue by ldkklj** [ccxt/ccxt#13923]
- OS:Linux
- Programming Language version:Python3.8.5
- CCXT version:1.87.77

```
huobi = ccxta.huobi({
    'apiKey': 'dddddddd',
    'secret': 'dddddddd',
})
huobi.options['defaultType']='future'

binance = ccxta.binance({
    'apiKey': 'dddddddd',
    'secret': 'dddddddd',
})
binance.options['defaultType']='future'

okex = ccxta.okex({
    'apiKey': 'dddddddd',
    'secret': 'dddddddd',
    'password': 'dddddddd',
})
okex.options['defaultType']='future'

mexc = ccxta.mexc({
    'apiKey': 'dddddddd',
    'secret': 'dddddddd',
})
mexc.options['defaultType']='swap'

kucoin = ccxta.kucoin({
    'apiKey': 'dddddddd',
    'secret': 'dddddddd',
    'password': 'dddddddd',
})
kucoin.options['defaultType']='future'

exchanges=[]
exchanges.append(huobi)
exchanges.append(binance)
exchanges.append(mexc)
exchanges.append(okex)
exchanges.append(kucoin)

for i in range (0,len(exchanges)):
    exchange = exchanges[i]
    try:
        market= await exchange.load_markets()
    except Exception as e:
        print(e)
        continue

```
Finally ,I only got bianance  and mexc switched to future market ,other market such as huobi/okex/kucoin is still spot.

**Comment by samgermain** [comment]
Yes that's correct, we're waiting on this PR to unify the naming https://github.com/ccxt/ccxt/pull/12586

If you want to trade perpetual futures on any other exchange, set `defaultType` to `swap`, setting `defaultType` to `future` on any other exchange will trade delivery futures. 

Only on binance do you set `defaultType` to `future` to trade perpetual futures, and `defaultType` to `delivery` to trade delivery futures.

Once that PR gets merged you can move to the new naming for binance as well

**Comment by samgermain** [comment]
@ldkklj I'm going to close this issue, but feel free to reopen it if you have any more questions
