### ISSUE TITLE
How to cancel a stop loss or take profit order？

### ISSUE THREAD

**Issue by qwe231cvb** [ccxt/ccxt#13922]
The code as follows:
```
type = 'stop'
side = 'sell'
price = None
drop_btc_price = btc_maket_price - btc_maket_price * 0.02
params = {
    'stopPrice': drop_btc_price,
}
order2 = ftx.create_order(symbol, type, side, btc_amount, price, params)
```
How to cancel this stop loss order?

**Comment by samgermain** [comment]
The current way you can do this is by assigning the params argument to `{"type": "stop"}`. 

I've added [a PR](https://github.com/ccxt/ccxt/pull/13929), so that you can do it by assigning params to `{"stop": true}`, to make this method more in line with other exchanges and methods.
