### ISSUE TITLE
New Exchange: Upbit

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1392]
api doc: 
url: https://upbit.com/exchange?code=CRIX.UPBIT.KRW-BTC
fee: 
volume: https://coinmarketcap.com/exchanges/upbit/
address: 서울시 강남구 테헤란로 4길 14, 5층
company info: 두나무 주식회사
Registration 통신판매업신고 2014-서울강남-02571호 고객센터 1588-5682
based country: korea
priority: high
note: ranked top : 3

**Comment by jjhesk** [comment]
still looking for the api that we all can have access to. i will find out when this is available.

**Comment by d1gits** [comment]
https://crix-api-endpoint.upbit.com/v1/crix/trades/ticks?code=CRIX.UPBIT.KRW-XRP&count=1

**Comment by mgavaudan** [comment]
Is it possible to place buy/sell orders on an Upbit API yet?

**Comment by jindouyunonline** [comment]
Is there any way to fetch order book data of upbit?

**Comment by AlexN93** [comment]
Yes an orderbook will help a lot.

**Comment by jjhesk** [comment]
@jindouyunonline yes, are you interested to crawl out this js. you will get the [anwser](https://gist.github.com/jjhesk/35fceb5d5d0876c67ff1dd7bd5bd2020)

**Comment by jjhesk** [comment]
got some `  var t = "CRIX.UPBIT.BTC-" + n.props.master.baseCurrencyCode, r = "/exchange?code=" + t;`

**Comment by araa47** [comment]
This is the URL I'm using: https://crix-api-endpoint.upbit.com/v1/crix/candles/minutes/3?code=CRIX.UPBIT.KRW-BTC&count=1

**Comment by idefen1** [comment]
Any idea on the endpoint for general currencies? 

These do not work =\
https://crix-api-endpoint.upbit.com/v1/crix/currencies 
https://crix-api-endpoint.upbit.com/v1/crix/markets

**Comment by araa47** [comment]
Just use the link I posted and change the currency pair KRW-BTC to whatever currency pair you want to use

**Comment by swilso793** [comment]
How would you go about finding all of the symbols deterministically?

**Comment by araa47** [comment]
I think this is what you are looking for https://coinmarketcap.com/exchanges/upbit/

**Comment by jjhesk** [comment]
most importantly you need to get the restful api access for trading. it is best to gain access with api key and secret. @swilso793 coinmaketcap have been registered by upbit so they have exclusive access.

**Comment by jjhesk** [comment]
yes for now you might need to hardcode all symbols

**Comment by davidmckenzie** [comment]
There was a public API open here but it was closed after it leaked some imminent listings: https://ccx.upbit.com/api/v1/market_status/all

Not sure if it work with an actual API key, as I haven't been able to sign up

**Comment by rafald121** [comment]
I didn't see clear response about previous question so I would ask again: when Upbit will support placing orders and other private methods ? On the ccxt wiki page there is no information about Upbit API yet.

**Comment by jjhesk** [comment]
@rafald121 have you contact upbit about this?
i am sure they have internal documents to do that..

**Comment by jayarjo** [comment]
Is there an API to actually trade on Upbit?

**Comment by kroitor** [comment]
@jayarjo not that we know of at this moment...

**Comment by xinqiyang** [comment]
hi, Will follow upbit support? this is in the plan?

**Comment by donglesquare** [comment]
https://docs.upbit.com/v1.0/reference

Upbit API for trading is opened several days ago. Not sure about existence of English reference page.

**Comment by jayarjo** [comment]
However, still no WebSocket API :/

**Comment by insoochoo** [comment]
Any updates?

**Comment by catalsdevelop** [comment]
@jayarjo ws api listed on its docs now.

**Comment by JoshVarty** [comment]
I have mostly finished my work on #1577 so I am willing to try to implement this exchange if no one else has started. I am unfamiliar with streaming APIs, so for now I would only plan to implement the basic RESTful methods (`fetchMarkets`, `fetchTrades` etc.)

**Comment by kroitor** [comment]
@JoshVarty hey, thx! ) One thing though: we are already working on Upbit ) Would be great if you could choose another one, just to split the workload and to avoid duplication. Here's the full list:
https://github.com/ccxt/ccxt/issues?q=is%3Aopen+is%3Aissue+label%3A%22new+exchange%22
And thx for your effort on BCEX, btw, really helpful!

**Comment by CryptoRyphe** [comment]
If someone has an upbit api key and willing to share it with me for some testing purpose, please contact me.

**Comment by kroitor** [comment]
@jjhesk , @jindouyunonline We would like to integrate this exchange, but because Upbit has a very strict KYC/AML policy that requires a Korean phone number which is quite hard to obtain, we can't really test it properly. 

We will be thankful if someone from the community sends us a zero-balance key to info@ccxt.trade or to igor@ccxt.trade for debugging purposes. We don't need the money nor your personal info, this is for debugging and testing only.

**Comment by arielorvits** [comment]
didn't tried on upbit, but on other exchange I used https://www.virtualphone.com/ .
maybe it can help

**Comment by gyjoo** [comment]
@kroitor Hey I'm a heavy user of ccxt. I can send you keys if you still want it.

**Comment by mobibeat** [comment]
@gyjoo Hello I am trying to make a simple script for upbit but it is impossible to create an api key :(
I know nobody in south Korea
I would really appreciate it if you can share a key with me.
Thank you

**Comment by kroitor** [comment]
@gyjoo sorry for a long wait and thx for your responsiveness. I've already got the key from another user, but I will let you know if anything. Unfortunately, I've been quite occupied recently, so didn't have the time to upload it yet, but hope to do this in the coming days.

**Comment by mobibeat** [comment]
@kroitor any chance you could share the keys so I can make few tests as well ?

**Comment by kroitor** [comment]
@mobibeat sorry, but I promised to not disclose them (not my own keys). Wouldn't be a problem if those were mine. Hope for your understanding.

**Comment by dongx3** [comment]
@kroiter
Hi, is there any progress on this issue?

**Comment by dongx3** [comment]
@kroitor
Hi, is there any progress on this issue?

**Comment by mesyakim** [comment]
@kroitor How's it going? Is there a problem?

**Comment by Gennttii** [comment]
So noone can create an Upbit API, outside Korea?

**Comment by kroitor** [comment]
@Gennttii @mesyakim @dongx3 it's in progress, and we will add it this month, hopefully.

**Comment by kroitor** [comment]
UPbit exchange has been integrated and listed in CCXT version 1.17.558+

- https://github.com/ccxt/ccxt/blob/master/js/upbit.js
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/upbit.py
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/upbit.py
- https://github.com/ccxt/ccxt/blob/master/php/upbit.php

The UPbit exchange is now listed on our list of Certified Exchanges here:

- https://user-images.githubusercontent.com/1294454/49252340-d1322000-f434-11e8-9b64-e8fc3057ff5a.jpg
- https://github.com/ccxt/ccxt#certified-cryptocurrency-exchanges

And it is also listed in our list of all supported exchanges here:

- https://user-images.githubusercontent.com/1294454/49252355-dd1de200-f434-11e8-90c7-436b7eba468d.jpg
- https://github.com/ccxt/ccxt#supported-cryptocurrency-exchange-markets

We will be happy if you report back whatever issues, bugs or inconsistencies you may find – we hope to fix them all asap, if any. 

Thank you for using this library!

**Comment by kroitor** [comment]
> You did it , but UPbit is still only for koreans ..

That is correct, we have integrated it because we had many requests for it from users. The KYC/AML limitations are due to South Korean laws.

**Comment by abchzw** [comment]
> @kroitor嘿，我是ccxt的重要用户。如果你还想要，我可以寄给你钥匙。

hi,can you help me ,I a upbit api to test,it is very import ,thank you.
