### ISSUE TITLE
`zonda.fetch_my_trades` returns only last 10 trades

### ISSUE THREAD

**Issue by iirekm** [ccxt/ccxt#13939]
- `nextPageCursor` should be "start"
- there's no reading all pages in loop!

**Comment by kroitor** [comment]
@iirekm CCXT supports pagination, but you will have to paginate on your own. Check this section of the Manual for more details:

- https://docs.ccxt.com/en/latest/manual.html#pagination

Also, please, check the examples here:

- https://github.com/ccxt/ccxt/tree/master/examples/

Let us know if that does not answer your question. Feel free to reopen it or just ask further questions here if any.
