### ISSUE TITLE
Question: get the candle limit in fetch_ohlcv

### ISSUE THREAD

**Issue by gilbh** [ccxt/ccxt#13957]
This is a simple question: is there a way of ccxt exchange letting me know what is the maximum/limit number of candles returned on fetch_ohlcv? That would have me build a generic engine for fetching with different date ranges.

Thanks.

**Comment by kroitor** [comment]
> This is a simple question: is there a way of ccxt exchange letting me know what is the maximum/limit number of candles returned on fetch_ohlcv? That would have me build a generic engine for fetching with different date ranges.

This is not fully unified yet, we will cover that asap, in the meantime, please, check this related issue: https://github.com/ccxt/ccxt/issues/6772

**Comment by gilbh** [comment]
Thanks!! Indeed, I see some shared interest there. You guys are doing great work!
