### ISSUE TITLE
php base files

### ISSUE THREAD

**Issue by pursehouse** [ccxt/ccxt#1395]
The docs say there should be a php/base folder with the non-generated files, but the folder does not exist. Are all the php files generated from js?

**Comment by kroitor** [comment]
The docs are slightly outdated, all files are here: https://github.com/ccxt/ccxt/tree/master/php

- base files are not generated (Exchange.php, errors classes)
- derived exchange classes are generated

All files were moved to one folder for compatibility with PHP+Composer+autoload, by these pull requests:

- https://github.com/ccxt/ccxt/pull/876
- https://github.com/ccxt/ccxt/pull/873
- https://github.com/ccxt/ccxt/pull/865
- ...

Let me know if it doesn't answer your question. Thx!

**Comment by pursehouse** [comment]
hmm... whoever said composer needs files to be in the same folder was confused. having all the files in the same folder is fairly confusing for trying to do non-js editing

**Comment by kroitor** [comment]
@pursehouse if you would suggest a better structure, we welcome all contributions! ) It's all open and editable, just make sure not to break anything (remember, we have to work seamlessly in three languages and various environments, windows, unix and mac). 

You already know where our docs are, but I'd leave a link here for others: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

Feel free to ask questions, if any. Thx!
