### ISSUE TITLE
itbit (paxos) - v2 update

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#13951]
itbit exchange api needs an update to **v2** :
https://developer.paxos.com/docs/v2/api#operation/ListMarkets

**Comment by frosty00** [comment]
itbit has since been delisted

**Comment by ttodua** [comment]
> itbit has since been delisted

but we might still leave a chance for this, because iirc it was delisted because API was not updated. was there other reason for delist? itbit might be somewhat good grade exchange (used by some solid traders too) because it's by Paxos
