### ISSUE TITLE
Coinbase: fetchMyTrades no longer supported?

### ISSUE THREAD

**Issue by Bomper** [ccxt/ccxt#13954]
Wanted to fetch trades from the new "Advanced Trade" in Coinbase that's replacing Coinbase Pro, but got this error

```
node_modules/ccxt/js/base/Exchange.js:2163
        throw new NotSupported (this.id + ' fetchMyTrades() is not supported yet');
              ^
NotSupported: coinbase fetchMyTrades() is not supported yet
```

- OS: Linux
- Node version: 16.15.1
- CCXT version: 1.87.95

```js
import ccxt from 'ccxt';
const coinbase = new ccxt.coinbase({
    apiKey: '...',
    secret: '...',
});
await coinbase.fetchMyTrades('BTC/USD', undefined, 1000);
```

**Comment by samgermain** [comment]
The CCXT coinbase class never had the `fetchMyTrades` method. To use coinbases "Advanced Trading", there would need to be some PRs to CCXT to add trading functionality to the `coinbase` class, but it doesn't even look like Coinbase has API endpoints for advanced trading yet, so this isn't possible at the moment

**Comment by kroitor** [comment]
@Bomper please, use `ccxt.coinbasepro` instead.

**Comment by pottertech** [comment]
Coinbase Advanced Trade API is now available in BETA: [](https://docs.cloud.coinbase.com/advanced-trade-api/docs)
