### ISSUE TITLE
[QUESTION] How to buy market without calculating the output?

### ISSUE THREAD

**Issue by Naografix** [ccxt/ccxt#13965]
Hello,

I'm trying to buy market BTC with USDT:

```
let concatenedCurrencies = `${toCurrency}/${fromCurrency}`.toLocaleUpperCase(); //USDT/BTC
result = await exchange.createMarketOrder(concatenedCurrencies, "buy", amount);
```

But got _InsufficientFunds: binance Account has insufficient balance for requested action._ error.

I know I need to calculate the output in the amount parameter, but is it possible to avoid this technique?

Thanks

**Comment by kroitor** [comment]
Yes, use the `quoteOrderQty` param override, or just specify the multiplier in the `price` argument:

```
const cost = HOW_MUCH_USDT_TO_SPEND
result = await exchange.createOrder('BTC/USDT', 'market', 'buy', amount, undefined, {'cost': cost});
// or
result = await exchange.createOrder('BTC/USDT', 'market', 'buy', amount, undefined, {'quoteOrderQty': cost});
// or
result = await exchange.createOrder('BTC/USDT', 'market', 'buy', cost, 1);
```

**Comment by Naografix** [comment]
> Yes, use the `cost` param override, or the `quoteOrderQty` param override, or just specify the multiplier in the `price` argument:
> 
> * https://docs.ccxt.com/en/latest/manual.html#overriding-unified-api-params
> * https://docs.ccxt.com/en/latest/manual.html#placing-orders
> * https://docs.ccxt.com/
> 
> ```js
> const cost = HOW_MUCH_USDT_TO_SPEND
> result = await exchange.createOrder('BTC/USDT', 'market', 'buy', anyAmount, undefined, {'cost': cost});
> // or
> result = await exchange.createOrder('BTC/USDT', 'market', 'buy', anyAmount, undefined, {'quoteOrderQty': cost});
> // or
> result = await exchange.createOrder('BTC/USDT', 'market', 'buy', cost, 1);
> ```

Oh ok! I put whatever I want in "amount" if it's in market! Cool thank you @kroitor

**Comment by yurifontoura** [comment]
> Yes, use the `cost` param override, or the `quoteOrderQty` param override, or just specify the multiplier in the `price` argument:
> 
> * https://docs.ccxt.com/en/latest/manual.html#overriding-unified-api-params
> * https://docs.ccxt.com/en/latest/manual.html#placing-orders
> * https://docs.ccxt.com/
> 
> ```js
> const cost = HOW_MUCH_USDT_TO_SPEND
> result = await exchange.createOrder('BTC/USDT', 'market', 'buy', anyAmount, undefined, {'cost': cost});
> // or
> result = await exchange.createOrder('BTC/USDT', 'market', 'buy', anyAmount, undefined, {'quoteOrderQty': cost});
> // or
> result = await exchange.createOrder('BTC/USDT', 'market', 'buy', cost, 1);
> ```

I tried the solution, but cost is not overriding the anyAmount. It creates an order with the anyAmount value.

Thank you!
