### ISSUE TITLE
[BamsoonPapa] CANNOT LIST-UP futures market symbols.

### ISSUE THREAD

**Issue by BamsoonPapa** [ccxt/ccxt#13963]
- OS: Windows 11
- Programming Language version: Python (Jupyter notebook)
- CCXT version: 1.84.87

I want to list-up crypto-futures market symbols only.
but CCXT displays all market symbols(including spot market)
my code is below.
please, solve this problem.

Sincerely,
BamsoonPapa

※ below

def getMarkets_FuturesUSD(exchange):

    try:
        ecg = eval("ccxt." + exchange.lower() + "(config={'options':{'defaultType':'future'}})")

        result = ecg.load_markets()

        markets = []
        for key in result.keys():
            markets.append(key)

        return markets

    except:
        return "CANNOT EXECUTE !!"

**Comment by kroitor** [comment]
This is not a problem with CCXT, it's a problem with your code, here's a correct example:

- https://github.com/ccxt/ccxt/blob/master/examples/js/load-all-contracts.js

```JavaScript
"use strict";

const ccxt = require ('ccxt')

console.log ('CCXT Version:', ccxt.version)

async function loadExchange (exchangeId) {
    try {
        const exchange = new ccxt[exchangeId]()
        if (exchange.has['swap'] || exchange.has['future'] || exchange.has['option']) {
            await exchange.loadMarkets ()
            exchange.symbols.map (symbol => {
                const market = exchange.market (symbol)
                console.log (exchange.id, 'loaded', market['type'], symbol, 'market')
            })
        } else {
        }
    } catch (e) {
        console.log (e.constructor.name, e.message)
    }
}

async function main () {

    await Promise.all (ccxt.exchanges.map (exchangeId => loadExchange (exchangeId)))
}

main ()
```

**Comment by carlosmiei** [comment]
Hello @BamsoonPapa by default if there are no conflicting ids within the exchange we load all market types (spot, futures, swaps, ...). You can however filter them as you want since each market has a property illustrating its type as @kroitor just demonstrated, so I would suggest doing something like this:

```Python
try:
    ecg = eval("ccxt." + exchange.lower() + "(config={'options':{'defaultType':'future'}})")

    result = ecg.load_markets()

    markets = []
    for key in result.keys():
        market = result[key]
        if market['future']:
            markets.append(key)
    return markets

except:
    return "CANNOT EXECUTE !!"
```

**Comment by BamsoonPapa** [comment]
Hello, @carlosmiei ,

really thank you for your kind explanation.
This is my first post on github in my life. So I will remember your name for the rest of my life for helping me understand.

I've tested your code toward Huobi.
result is below.
there is no Perpetual Symbols.
FTX was the same.

I hope my writing improves the completeness of ccxt and helps other users.
Thank you again.

※ below(Huobi case)

['BTC/USDT:USDT-220624',
 'BTC/USDT:USDT-220701',
 'ETH/USDT:USDT-220624',
 'ETH/USDT:USDT-220701',
 'BTC/USD:BTC-220624',
 'BTC/USD:BTC-220701',
 'BTC/USD:BTC-220930',
 'ETH/USD:ETH-220624',
 'ETH/USD:ETH-220701',
 'ETH/USD:ETH-220930',
 'LTC/USD:LTC-220624',
 'LTC/USD:LTC-220701',
 'LTC/USD:LTC-220930',
 'EOS/USD:EOS-220624',
 'EOS/USD:EOS-220701',
 'LINK/USD:LINK-220624',
 'LINK/USD:LINK-220701',
 'DOT/USD:DOT-220624',
 'DOT/USD:DOT-220701',
 'TRX/USD:TRX-220624',
 'TRX/USD:TRX-220701',
 'ADA/USD:ADA-220624',
 'ADA/USD:ADA-220701',
 'BCH/USD:BCH-220624',
 'BCH/USD:BCH-220701',
 'XRP/USD:XRP-220624',
 'XRP/USD:XRP-220701',
 'BSV/USD:BSV-220624',
 'BSV/USD:BSV-220701',
 'ETC/USD:ETC-220624',
 'ETC/USD:ETC-220701',
 'FIL/USD:FIL-220624',
 'FIL/USD:FIL-220701']

**Comment by kroitor** [comment]
@BamsoonPapa try this one instead:

- https://github.com/ccxt/ccxt/commit/a2f94a91cac2b4032aab0cf4d51dedad9f930262

```JavaScript
"use strict";

const ccxt = require ('ccxt')

console.log ('CCXT Version:', ccxt.version)

async function loadExchange (exchange) {
    try {
        await exchange.loadMarkets ()
        exchange.symbols.map (symbol => {
            const market = exchange.market (symbol)
            if (market['contract']) {
                console.log (exchange.id, 'loaded', market['type'], symbol, 'market')
            }
        })
    } catch (e) {
        console.log (e.constructor.name, e.message)
    }
}

async function loadAllExchanges (exchangeId) {
    try {

        const exchanges = [];
        [ 'swap', 'future', 'options' ].forEach (defaultType => {
            const exchange = new ccxt[exchangeId]()
            if (exchange.has[defaultType]) {
                exchanges.push (exchange);
            }
        })
        await Promise.all (exchanges.map (exchange => loadExchange (exchange)))
    } catch (e) {
        console.log (e.constructor.name, e.message)
    }
}

async function main () {
    await Promise.all (ccxt.exchanges.map (exchangeId => loadAllExchanges (exchangeId)))
}

main ()
```

**Comment by kroitor** [comment]
We will also add a Python example asap.

**Comment by BamsoonPapa** [comment]
@kroitor ,
really thank you for your comment.
I will study hard. 
have a nice day.

**Comment by BamsoonPapa** [comment]
@carlosmiei ,
I solved my problem as below.
thank you for your teaching.
have a peaceful day.

※ below

def getMarkets_FuturesUSD(exchange):

    try:
        ecg = eval("ccxt." + exchange.lower() + "(config={'options':{'defaultType':'future'}})")

        result = ecg.load_markets()

        markets = []
        for key in result.keys():
            marketDetail = result[key]
            if marketDetail['future'] or marketDetail['swap']:
                markets.append(key)

        return markets

    except:
        return "CANNOT EXECUTE!!"

**Comment by chulwoohan** [comment]
I had the same issue after upgrading ccxt. ccxt used to return only future (swap) symbols if defaultType is set to 'future'. In the new version, the defaultType appears to have no effect on market loading.
