### ISSUE TITLE
rateLimits

### ISSUE THREAD

**Issue by michnovka** [ccxt/ccxt#1399]
I was wondering how you come up with rateLimit values for given exchanges. They are usually > 1000 (as I understand this is in ms), but on exchanges which publish their limits its more like 1000/min and 1,000,000/day which comes to about 87ms rateLimit instead.

I would also like to spark conversation about implementing rateLimit natively into all libs so that we do not have to care about ddos protection in our code. 

This is what I use now in my code:

```

let _EXCHANGES_API_LAST_CALLED = {};

function APICallTimeLog(exchange_id){
    _EXCHANGES_API_LAST_CALLED[exchange_id] = Date.now();
}

async function APISleep(exchange_id){

    let sleep = (ms) => new Promise (resolve => setTimeout (resolve, ms));

    let wait_time = APICallWait(exchange_id);

    if(wait_time)
        await sleep(wait_time);

    APICallTimeLog(exchange_id);

}

function APICallWait(exchange_id){
    if(!_EXCHANGES_API_LAST_CALLED[exchange_id])
        return 0;

    let last_called_time = parseInt(_EXCHANGES_API_LAST_CALLED[exchange_id]);

    let wait = last_called_time + config.exchanges[exchange_id].rateLimit - Date.now();

    if(wait < 0)
        return 0;

    return wait;
}
```

and then during API communications:

```

            let promise = (async () => {

                await APISleep(exchange_id);

                return await exchange.fetchTickers();
            })();

```

would be nice if all this were under the hood implemented. I am willing to look into this if there is interest, thanks for your opinion

**Comment by wannesdemaeght** [comment]
@kroitor , what about this?

> I was wondering how you come up with rateLimit values for given exchanges. They are usually > 1000 (as I understand this is in ms), but on exchanges which publish their limits its more like 1000/min and 1,000,000/day which comes to about 87ms rateLimit instead.

**Comment by hippylover** [comment]
Maybe test the exchanges you think allow that and tell kroitor/us. The picture might be more complex than that though. For example on bittrex they allow personal calls once every second or so but public calls they don't care about but and since it's throttled.

**Comment by wannesdemaeght** [comment]
>  but public calls they don't care about but and since it's throttled.

Sorry, you lost me there. Could you reformulate please?

**Comment by michnovka** [comment]
@hippylover this is a good point, Id propose something like this:

```
rateLimits: {
    'public': {
        '__general': 1000, // 1000ms
        'fetchTickers': 1500, // 1500ms
        'fetchOCHLV': -1 // unlimited
    },
    'private': {
        '__general': 2000 // 2000ms
    }
}
```

such structure would allow to specify rateLimit per concrete function, per API type (public/private) and it would also allow to set no rate limit (-1) on some requests.

**Comment by hippylover** [comment]
@wannesdemaeght just what iv'e heard in bittrex slack from one of the devs. With "throttled" he probably means if you send a public request bittrex makes you wait anyway until they decide you have waited long enough relative to previous request. And/or it's cached somehow.

Anyway, kroitor have to chime in on this one, i only know it's like that on bittrex but not how it is on other exchanges.

**Comment by kroitor** [comment]
@michnovka the structure you described is already supported by tokenBucket intrinsically, so, yes, in general, this is the way we would go, however, it still isn't all that easy, some exchanges have variable call cost.

**Comment by michnovka** [comment]
can you please give an example of 1 or 2 so that i can have a look at their
api? thanks

On Jan 24, 2018 2:34 PM, "Igor Kroitor" <notifications@github.com> wrote:

@michnovka <https://github.com/michnovka> the structure you described is
already supported by tokenBucket intrinsically, so, yes, in general, this
is the way we would go, however, it still isn't all that easy, some
exchanges have variable call cost.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ccxt/ccxt/issues/1399#issuecomment-360133270>, or mute
the thread

**Comment by kroitor** [comment]
@michnovka sorry, I didn't quite get the last question and missed it somehow, can you elaborate please? Most of details are already described in my initial answer above. Do you mean something beyond that?

**Comment by kroitor** [comment]
@Codewyvern 

> Does that mean the rate limit is fully automatically handled by the library

Yep.

> do I still need to call it manually like here?

Nope. You should either do it manually, or enable and use the built-in rate-limiting in the library, but not both.
