### ISSUE TITLE
Bitget futures leverage setup exception: object has no attribute 'fapiPrivate_post_leverage'.

### ISSUE THREAD

**Issue by teslatrader** [ccxt/ccxt#14005]
Hi there.
Got some bugs when was trying to change futures perpetual leverage on Bitget.
Here are the details:

    OS: debian 10.12
    Programming Language version: python 3.7.3
    CCXT version: 1.87.66

SOURCE CODE:
```
import ccxt

api = ''
secret = ''
passphrase = ''

exchange = ccxt.bitget({
    "apiKey":api,
    "secret":secret,
    "password": passphrase,
    "options": {'defaultType': 'swap', 'adjustForTimeDifference' : True},
    "timeout": 60000,
    "enableRateLimit": True,
})

exchange.verbose = True

symbol = 'LTCUSDT_UMCBL'
leverage = 3

try:
    params = {
        'symbol': symbol,
        'leverage': leverage,
    }
    exchange.fapiPrivate_post_leverage(params=params)

except Exception as e:
    print(f'Exception: \n{e}')
```

OUTPUT:
```
Exception:
'bitget' object has no attribute 'fapiPrivate_post_leverage'
```
Thanks in advance!

**Comment by kroitor** [comment]
@teslatrader `fapiPrivate_post_leverage` is an implicit method of Binance so it will be available with Binance, but not with Bitget. Bitget has its own implicit methods. To understand what is implicit API, please, read the Manual to CCXT, it will really save your time. We recommend reading it at least once from top to bottom to be able to work with this library efficiently:

- https://docs.ccxt.com/
- https://docs.ccxt.com/en/latest/manual.html#implicit-api

We also recommend using the unified API instead:

- https://docs.ccxt.com/en/latest/manual.html#unified-api

Apart from that, check the examples here:

- https://github.com/ccxt/ccxt/tree/master/examples/
- https://github.com/ccxt/ccxt/tree/master/examples/py
- https://github.com/ccxt/ccxt/tree/master/examples/#see-also
