### ISSUE TITLE
Can't get pending deposits and withdrawals at Bittrex

### ISSUE THREAD

**Issue by miranska** [ccxt/ccxt#14002]
When retrieving deposits and withdrawals from Bittrex, only completed ones are shown.

OS: MacOS
Programming Language version: Python 3.9.7
CCXT version: 1.88.26

To repro:
```
exchange = ccxt.bittrex({'apiKey': 'KEY', 'secret': 'SECRET'})
print(exchange.fetch_deposits(code='USDT'))
print(exchange.fetch_withdrawals(code='USDT'))
```

Looking at the code, this happens because we query only `https://api.bittrex.com/v3/deposits/closed?currencySymbol=USDT` and `https://api.bittrex.com/v3/withdrawals/closed?currencySymbol=USDT` endpoints in the code:

https://github.com/ccxt/ccxt/blob/fecf5c8965e5724fc130e6651dd70a74b36f2f57/python/ccxt/bittrex.py#L1263

https://github.com/ccxt/ccxt/blob/fecf5c8965e5724fc130e6651dd70a74b36f2f57/python/ccxt/bittrex.py#L1285

To get pending deposits and withdrawals, we need to get a response from `privateGetDepositsOpen` and `privateGetWithdrawalsOpen` functions (which are already defined), and then concatenate the resulting `open` and `closed` lists.

**Comment by pcriadoperez** [comment]
As a general rule we only do one api call per method with the exception of `fetchMarkets`, that's why we didn't concatenate both api calls.
@kroitor  do you think for this case it would make sense to add a `method` argument in `params` to allow the users to use `privateGetWithdrawalsOpen ` in `fetchDeposits`?

**Comment by kroitor** [comment]
You can now get bittrex withdrawals and deposits, depending on their `status`:

```Python
exchange = ccxt.bittrex({'apiKey': 'KEY', 'secret': 'SECRET'})
print('-------------------------------------')
print(exchange.fetch_deposits(code='USDT'))
print(exchange.fetch_withdrawals(code='USDT'))
print('-------------------------------------')
print(exchange.fetch_deposits(code='USDT', params={'status':'ok'}))  # same as above
print(exchange.fetch_withdrawals(code='USDT', params={'status':'ok'}))
print('-------------------------------------')
print(exchange.fetch_deposits(code='USDT', params={'status':'pending'}))
print(exchange.fetch_withdrawals(code='USDT', params={'status':'pending'}))
print('-------------------------------------')
print(exchange.fetch_pending_deposits(code='USDT'))  # same as above
print(exchange.fetch_pending_withdrawals(code='USDT'))
```

Thx to @DoctorSlimm for adding this!

**Comment by miranska** [comment]
Magic, thank you!
