### ISSUE TITLE
KC-API-KEY not exists issue with a valid api key

### ISSUE THREAD

**Issue by karahancodes** [ccxt/ccxt#14009]
Hey , i keep getting this error to call fetch_balance for kucoin. I've tried getting couple of different api keys (all on kucoinfutures).

- OS: MacOS
- Programming Language version: Python 3.9
- CCXT version: 1.88
 
I've my variables setup like that in a .env file , and i'm sure of getting proper values in python.
```
mn_kucoin_key=apikey
mn_kucoin_secret=secretkey
tn_kucoin_password=paraphrase
```

```
ccxt.base.errors.AuthenticationError: kucoin KC-API-KEY not exists
```

Any help is appreciated , thanks.

**Comment by samgermain** [comment]
Can you share a more complete version of your code, something that one of us can copy and test out?

**Comment by karahancodes** [comment]
Thanks for your answers , here s my test code :
```
async def test_kucoin():
    exchange:kucoinfutures = ccxtpro.kucoin(kucoin_params)  
    balance = await exchange.fetch_balance()
    print(balance)
    await exchange.close()
```
kucoin_params is just the dictionary with my keys. 
I'm sure of creating futures api keys , not spot ones or testnet ones. Thanks in advance.

**Comment by kroitor** [comment]
@karahancodes please, try this and make sure that your API keys are configured correctly (check the API key sent in the request in verbose mode and make sure it matches the API key from the website).

```Python
import ccxt.async_support as ccxt
import ccxtpro
import asyncio

print('CCXT Version:', ccxt.__version__)
print('CCXT Pro Version:', ccxtpro.__version__)

async def main():
    exchange = ccxtpro.kucoin({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_API_SECRET',
        'password': 'YOUR_API_PASSWORD',
    })  
    markets = await exchange.load_markets()
    exchange.verbose = True
    balance = await exchange.fetch_balance()
    print(balance)
    await exchange.close()
    
   
asyncio.run(main())
```

**Comment by karahancodes** [comment]
Ive tried and im still getting  ```{"code":"400003","msg":"KC-API-KEY not exists"}``` unfortunately... Tried with 2 different accounts and more than 10+ as well.

**Comment by kroitor** [comment]
@karahancodes oh, you should instantiate `ccxtpro.kucoinfutures` instead, let me know if this does not help:

```Python
import ccxt.async_support as ccxt
import ccxtpro
import asyncio

print('CCXT Version:', ccxt.__version__)
print('CCXT Pro Version:', ccxtpro.__version__)

async def main():
    exchange = ccxtpro.kucoinfutures({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_API_SECRET',
        'password': 'YOUR_API_PASSWORD',
    })  
    markets = await exchange.load_markets()
    exchange.verbose = True
    balance = await exchange.fetch_balance()
    print(balance)
    await exchange.close()
    
   
asyncio.run(main())
```

**Comment by karahancodes** [comment]
I'm still getting ``` ccxt.base.errors.AuthenticationError: kucoin KC-API-KEY not exists ``` ....  it matches with the API key sent in the request in verbose mode as well.

**Comment by kroitor** [comment]
@karahancodes with the spot key you have to use `ccxt.kucoin`, while with the futures key you have to use `ccxt.kucoinfutures`. 



Hope that answers your question, let us know if not.

> I managed to get this output by trying with spot api key as well but don't really see what it means

That is a regular empty balance structure: https://docs.ccxt.com/en/latest/manual.html#balance-structure

**Comment by psashish** [comment]
> @karahancodes oh, you should instantiate `ccxtpro.kucoinfutures` instead, let me know if this does not help:
> 
> ```python
> import ccxt.async_support as ccxt
> import ccxtpro
> import asyncio
> 
> print('CCXT Version:', ccxt.__version__)
> print('CCXT Pro Version:', ccxtpro.__version__)
> 
> async def main():
>     exchange = ccxtpro.kucoinfutures({
>         'apiKey': 'YOUR_API_KEY',
>         'secret': 'YOUR_API_SECRET',
>         'password': 'YOUR_API_PASSWORD',
>     })  
>     markets = await exchange.load_markets()
>     exchange.verbose = True
>     balance = await exchange.fetch_balance()
>     print(balance)
>     await exchange.close()
>     
>    
> asyncio.run(main())
> ```


still I'm getting Authentication Error
ccxt.base.errors.AuthenticationError: kucoin KC-API-KEY not exists

**Comment by carlosmiei** [comment]
@psashish I just tested and it worked, so the problem must be with your keys

```
p kucoinfutures fetchBalance                               
Python v3.11.7
CCXT v4.3.29
kucoinfutures.fetchBalance()
{'USDT': {'free': 36.11541357, 'total': 36.11541357, 'used': 0.0},
 'datetime': None,
 'free': {'USDT': 36.11541357},
 'info': {'code': '200000',
          'data': {'accountEquity': 36.11541357,
                   'availableBalance': 36.11541357,
                   'currency': 'USDT',
                   'frozenFunds': 0.0,
                   'marginBalance': 36.11541357,
                   'orderMargin': 0.0,
                   'positionMargin': 0,
                   'unrealisedPNL': 0}},
 'timestamp': None,
 'total': {'USDT': 36.11541357},
 'used': {'USDT': 0.0}}
```
