### ISSUE TITLE
API method name collisions

### ISSUE THREAD

**Issue by Deathamns** [ccxt/ccxt#1401]
HTTP `method` is [removed](https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L274) from the beginning of API paths, and this can cause methods to overwrite each other. [Example](https://www.exx.com/help/restApi#trade), where only a `privateGetOrder` will be available, but no `privateGetGetOrder`.

**Comment by kroitor** [comment]
We were trying to avoid the `GetGet`, but apparently, the exchanges don't want us to do that, so will have to delete the method name deduplication and rename a few endpoints then. Hope to do it soon.

**Comment by Deathamns** [comment]
There is a similar (convenience) thing which I did in a few places. Namely when an exchange response has always the same structure, something like `{code: 0, message: 'none', data: {...}}`. In this cases in the `request` method I would return `response.data` instead of `response` for easier access in other methods. Should I always return `response` instead?

**Comment by kroitor** [comment]
The problem with returning `response['data']` or `response.data` is that in error cases exchanges will drop that field, and dereferencing it in Python will throw an exception. So we have to check keys for safety.

As for your question, we tend to return the entire response, being as less intrusive as possible. This may be less convenient, but may be more compatible with other software.

**Comment by Deathamns** [comment]
I'm aware of the Python issue, I was curious only about the response. And I've got the answer, however I have another related question about the `info` property.
`info` should contain the whole response object when possible, or the relevant part is enough? For instance: response is `{code: 0, msg: '', pager: {}, data: { balances: { id: {}, id2: {} } } }`, but the relevant part is only the `balances` property.

**Comment by kroitor** [comment]
@Deathamns this isn't really specified anywhere, but I am trying to return as much as possible in the `info` field, though this is sometimes not very possible if the data is a list of orders or multiple tickers, for example. So, basically, `info` should contain either the data from the exchange, or the biggest available portion of it, say one of full tickers, if we're talking about fetchTickers. For the fetchBalance I would return the entire structure anyway.

**Comment by Deathamns** [comment]
One more thing about method naming. Exchanges use a wide range of URL parameter names for the same thing. For example: `ticker/:traiding_pair`, `ticker/:pair`, `ticker/:coin`, `ticker/:symbol` and so on. How should the library handle these cases? Use a unified name for the same thing, or respect how the exchange named it?
In both cases it's possible to have a collision (URL param is `symbol`, and there could be a query param with the name `symbol`), so that should not matter when choosing.

**Comment by kroitor** [comment]
> One more thing about method naming. Exchanges use a wide range of URL parameter names for the same thing. For example: ticker/:traiding_pair, ticker/:pair, ticker/:coin, ticker/:symbol and so on. How should the library handle these cases? Use a unified name for the same thing, or respect how the exchange named it?

We think preserving them as per exchange is better, because later we could add a swagger-importer or a parser of this kind of format which is common to many exchanges (their API docs) and could make it much easier importing new exchanges later:
```
GET https://.../markets
POST https://.../trade
GET https://.../order/{id}
```
The parser should also support other types of brackets around named url params, like in `<id>` and `[id]` or `:foobar`, etc...

If we find some naming that is not consistent with their original schema, we better make the URL listings look as similar as possible to the exchanges originals from docs.

> In both cases it's possible to have a collision (URL param is symbol, and there could be a query param with the name symbol), so that should not matter when choosing.

Most of the time we can resolve these types of collisions. but so far we haven't encountered them.
