### ISSUE TITLE
Coinbasepro deprecation of order size limits

### ISSUE THREAD

**Issue by robbielitebit** [ccxt/ccxt#14013]
https://docs.cloud.coinbase.com/exchange/reference/exchangerestapi_getproducts#details

For coinbasepro the properties `base_max_size`, `base_min_size`, `max_market_funds` are deprecated and will be removed on June 30. I see those are still used in coinbasepro: https://github.com/ccxt/ccxt/blob/master/js/coinbasepro.js#L394

Would be nice if this can updated before June 30

**Comment by robbielitebit** [comment]
Thanks for updating so quickly @kroitor  and @DoctorSlimm. Just one more question. Shouldn't the amount minimum and price minimum be set to the increment? Like:

```ts
'amount': {
    'min': this.safeNumber (market, 'base_increment'),
    'max': undefined,
},
'price': {
    'min': this.safeNumber (market, 'quote_increment'),
    'max': undefined,
},
```

https://blog.coinbase.com/upcoming-changes-to-order-size-limits-2fed4dc31b5c

**Comment by DoctorSlimm** [comment]
@robbielitebit the `increment` is not the same thing as the `price` minimum, which is the lowest price which you can create an order for a single unit of the base asset. The increment determines the precision of a the market, and can be see in lines 386-389 in `js/coinbasepro.js` 

```JavaScript
'precision': {
                    'amount': this.safeNumber (market, 'base_increment'),
                    'price': this.safeNumber (market, 'quote_increment'),
                },
```
