### ISSUE TITLE
HedgeMode function not responding 

### ISSUE THREAD

**Issue by Daanish283** [ccxt/ccxt#14011]
I am coding with python and ccxt library. I am trying to make a bot for binance futures. My bot is supposed to run on Hedge mode, everything seemed to be working great until i changed my preference to Hedge mode from one-way mode. I searched and tried everything i could, to resolve the problem. This is the error I am having -:

```
binance {"code":-4061,"msg":"Order's position side does not match user's setting."}
```
Below is all my code

```
import ccxt
    exchange = ccxt.binance({
        'base_url': 'https://testnet.binancefuture.com',
        'account_info': '/api/v3/account',
        'enableRateLimit': True,
        'apiKey': 'bd2c49e130ac3bfbefdb3e9cadfecb7398b3d6bdd9bea3aa8681f469544be260',
        'secret': '81f6f70cda3c4d4b6186cca57d08393cd9f676dfea5aa4f40150ac82cada8817',
        'hedgeMode': True,
        'options': {
            'defaultType': 'future',
       },
    })
    exchange.set_sandbox_mode(True)
    balance = exchange.fetch_balance()
    balance
```

The above code works just fine I have also changed my API credentials a bit for safety reasons although i am using a test net, apart from that everything is as it is.

My problem is with the code bellow

```
symbol = 'ETH/USDT'

    typee = 'market'  # or "limit"
    side1 = 'buy'
    side2 = 'sell'
    amount = 0.1  # your amount
    #price = 0.21  # your price
    # overrides
    params = {
     "hedged" = True
    'position_side': 'LONG' and 'SHORT'
   #'stopPrice': ,# your stop price
    }  

    buy_market_order = exchange.create_order(symbol, typee, side1, amount, params) 
    #INCLUDE 'price' IF NEEDED
    sell_market_order = exchange.create_order(symbol, typee, side2, amount, params)
```
I also tried using the below line of code after "symbol"

```
exchange.set_position_mode(hedged=True, symbol=symbol) 
```

But that gives me another problem, see below

binance {"code":-4059,"msg":"No need to change position side."} .

I've literally tried every combination and revised the ccxt docs carefully still nothing seems to work.

**Comment by kroitor** [comment]
I've replied to your question on stackoverflow: https://stackoverflow.com/questions/72684256/not-able-to-place-a-hedge-order-on-binance-using-ccxt/72705491#comment128434535_72705491

```Python
symbol = 'ETH/USDT'

    try:
        exchange.set_position_mode(hedged=True, symbol=symbol)  # ADD THIS
    except Exception as e:
        pass  # swallow the error if you're already in hedge mode
    
    typee = 'market'  # or 'market', other types aren't unified yet
    side1 = 'buy'
    side2 = 'sell'
    amount = 0.1  # your amount
    #price = 0.21  # your price
    # overrides
    params = {
        'positionSide': 'LONG' and 'SHORT'
        #'stopPrice': ,# your stop price
    }  

    buy_market_order = exchange.create_order(symbol, typee, side1, amount, params) 
    #INCLUDE 'price' IF NEEDED
    sell_market_order = exchange.create_order(symbol, typee, side2, amount, params)
```

> @DaanishPM if you are already in hedge mode, then you don't need to call `set_position_mode`, or you can wrap it in a try-catch as i've shown above (edited the code slightly). Also, I've noticed a typo, it should be `positionSide`, not `position_side` in your `params`. Let me know if that does not help.

- https://binance-docs.github.io/apidocs/futures/en/#new-order-trade

Hope that answers your question, let us know if not. Feel free to reopen this issue or just ask further questions if any.
