### ISSUE TITLE
FTX.com fails to auth

### ISSUE THREAD

**Issue by proskurin** [ccxt/ccxt#14014]
OS: Linux
Programming Language version: Python3
CCXT version: 1.83.11

I am trying to connect to FTX.com using:

```
import ccxt
exchange = ccxt.ftx ({
    'enableRateLimit': True
    'apiKey': api,
    'secret': secret,
})
exchange.load_markets()
exchange.verbose = True
print(exchange.fetch_balance())
```
However, I get `ExchangeError: ftx {"success":false,"error":"Invalid api key"}` error. I was also trying to add `'adjustForTimeDifference': True` , but it also had not effect.

I have double checked my API and secret keys and tried different one - no effect.

**Comment by kroitor** [comment]
@proskurin have you checked the verbose output? Does your API key from the verbose output match the API key that you see on the exchange website in your API key settings? If not, that means, you have not configured your keys correctly.

**Comment by kroitor** [comment]
@proskurin also, are you trying ftx.us keys or ftx.com keys ?

**Comment by proskurin** [comment]
@kroitor 
I am using FTX.com API keys, yes.

I have the following verbose output which contains my API key

f```
etch Request: ftx GET https://ftx.com/api/wallet/balances RequestHeaders: {'FTX-KEY': <MY_API_KEY>, 'FTX-TS': '1655911190794', 'FTX-SIGN': 'b820413fe79c5f44ed08fb40b65f893a3861306b8835bbe8aaaa815cf7d6c315', 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: ftx GET https://ftx.com/api/wallet/balances 400 ResponseHeaders: {'Date': 'Wed, 22 Jun 2022 15:19:51 GMT', 'Content-Type': 'application/json', 'Content-Length': '43', 'Connection': 'keep-alive', 'cache-control': 'private, max-age=0, no-cache', 'CF-Cache-Status': 'MISS', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Vary': 'Accept-Encoding', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '71f5f6eec9e37552-LHR', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'} ResponseBody: {"success":false,"error":"Invalid api key"}
```

**Comment by proskurin** [comment]
I have regenerated API key, whitelisted my IP and it works! Thank you
