### ISSUE TITLE
How can i get ip address log in from FTX API 

### ISSUE THREAD

**Issue by MunSunouk** [ccxt/ccxt#14033]
i just have question that how can i know all ip address that try to log in my FTX account by API.
i only can see the ip address in ftx page where log in by ftx page not an API

**Comment by kroitor** [comment]
The FTX API does not provide that information: https://docs.ftx.com/ so it cannot be done via the API at this time. You can try scraping that information from their webpage using a headless engine like https://github.com/puppeteer/puppeteer , but that is beyond the scope of the CCXT library at this time.
