### ISSUE TITLE
Request: margin trade for cryptocom (crypto.com)

### ISSUE THREAD

**Issue by kjnh10** [ccxt/ccxt#14042]
As title, could you implement margin trade for crypto.com?
There are APIs for margin trading, seeing API document.

**Comment by kjnh10** [comment]
Hello, Why is this #14107 pending for a week?

**Comment by kroitor** [comment]
@kjnh10 i had a delay on my side, so it took longer to review, pardon for the long wait, merged it now, it should work as of CCXT 1.90.68+ (the new build will arrive in ~20 minutes). Thank you for your feedback!

**Comment by kjnh10** [comment]
@kroitor 
Thanks for merging!
