### ISSUE TITLE
How Installl?

### ISSUE THREAD

**Issue by Cantalupo** [ccxt/ccxt#1404]
I would like to use the PHP version.

I already have a web server ready, but it displays "HTTP ERROR 500"

How do i run correctly?

Thank you

**Comment by kroitor** [comment]
It is documented here:
- https://github.com/ccxt/ccxt/wiki/Install#php
- https://github.com/ccxt/ccxt/wiki

Let us know if it doesn't answer your question. Thx!

**Comment by binoculars88** [comment]
I'm having trouble with this too... 
What does 

> It can also be installed from the source code: ccxt.php

 mean?

I simply copied all files from the master to my server, and ran the ccxt.php file, but I'm getting the same error as @Cantalupo .

**Comment by kroitor** [comment]
@binoculars88 you did copy ccxt files to your server, but those are library files, now you need to read the Manual and write your code to work with the library: https://github.com/ccxt/ccxt/wiki/Manual

**Comment by kroitor** [comment]
@binoculars88 thx for reporting back!

**Comment by Cantalupo** [comment]
@kroitor I also did not succeed with PHP.
