### ISSUE TITLE
[JS] fetchOHLCV only works awaiting, not with .then(callback)

### ISSUE THREAD

**Issue by ivnnv** [ccxt/ccxt#14061]
Hi,
Im implementing a custom multi-exchange multi-coin concurrent fetcher on a infinte while loop that only executes the call to each exchage's coin's endpoint when at least one minute has passed from the previous exchange's coin's call, so im always getting the last fresh minute candle for all exchanges coins).

- macOS
- Javascript
- CCXT version: `1.88.94`

It correctly works as:
```
const batchTrades = await exchange.instance.fetchOHLCV(
  coin.symbol, '1m', fetchSince, timeFrames['1m'].batchSize, { only: 'swap' }
);
console.log("batchtrades.length", batchTrades.length); // shows as expected
```

But it never resolves as:
```
exchange.instance.fetchOHLCV(
  coin.symbol, '1m', fetchSince, timeFrames['1m'].batchSize, { only: 'swap' }
).then(batchTrades => {
  console.log("batchtrades.length", batchTrades.length); // never executed
});
```

Why? There are supossed to be similar syntaxes but even trying to get into the most deep of the code, I didnt found a solid reason (my only guess is somehow `Exchange.fetch2` is who never resolves, as `Exchange.fetch` is never called from there).

**Comment by kroitor** [comment]
Please, paste your complete output:

```JavaScript
const ccxt = require ('ccxt')
console.log ('CCXT Version:', ccxt.version)
const exchange = new ccxt.ftx()
exchange.fetchOHLCV('BTC/USD', '1m').then (candles => {
    console.log (candles);
})
```

↑ That works for me:

<img width="580" alt="Screenshot 2022-06-25 at 16 54 23" src="https://user-images.githubusercontent.com/1294454/175776680-588e08d2-350b-4a97-944b-dda08affc8ef.png">

**Comment by ivnnv** [comment]
Hi, thanks for the prompt response.
I have created a minimun reproducible example that wont work as intended on the callback, but it does on the awaited one:

```
import ccxt from 'ccxt';

const iterCoins = ['BTCUSDT', 'ETCUSDT', 'ADAUSDT'];

(async () => {
  console.log('CCXT Version:', ccxt.version);
  const exchange = new ccxt.binance();

  for (const idx in iterCoins) {
    const coin = iterCoins[idx];

    let isRequestingCoin = false;
    let shouldContinueFetchingCoin = true;

    do {
      if (isRequestingCoin)
        continue;
      isRequestingCoin = true;

      console.log("Try fetching", coin, "on", exchange.name);

      // const batchTradesAwait = await exchange.fetchOHLCV(coin, '1m');
      // console.log("batchTradesAwait.length", batchTradesAwait.length); // outputs if uncommented

      exchange.fetchOHLCV(coin, '1m').then(batchTradesCallBack => {
        console.log("batchTradesCallBack.length", batchTradesCallBack.length);  // never outputs
      }).catch(err => {
        console.log(`Error catch`, err);
        shouldContinueFetchingCoin = false;
      }).finally(() => {
        isRequestingCoin = false;
      });
    } while (shouldContinueFetchingCoin);
  }

  console.log("End Processing");
})();
```

**Comment by ivnnv** [comment]
Hi, thanks for the prompt response.
I have created a minimun reproducible example of my use case that wont work as intended on the callback, but it does on the awaited one:

```
import ccxt from 'ccxt';

const iterCoins = [
  {
    symbol: 'BTCUSDT',
    isProcessing: false,
  },
  {
    symbol: 'ETCUSDT',
    isProcessing: false,
  },
  {
    symbol: 'ADAUSDT',
    isProcessing: false,
  }
];

(async () => {
  console.log('CCXT Version:', ccxt.version);
  const exchange = new ccxt.binance();

  let coinIndex = 0;
  let shouldContinueFetchingCoins = true;

  do {
    do {
      const coin = iterCoins[coinIndex];

      if (coin.isProcessing)
        continue;
      coin.isProcessing = true;

      console.log("Try fetching", coin.symbol, "on", exchange.name);

      /*
        const batchTradesAwait = await exchange.fetchOHLCV(coin.symbol, '1m');
        console.log("batchTradesAwait.length", batchTradesAwait.length); // outputs if uncommented
        await new Promise(r => setTimeout(r, exchange.rateLimit));
        coin.isProcessing = false;
      */

      coin.isProcessing = true;
      exchange.fetchOHLCV(coin.symbol, '1m').then(batchTradesCallBack => {
        console.log("batchTradesCallBack.length", batchTradesCallBack.length);  // never outputs
      }).catch(err => {
        console.log(`Error catch`, err);
        shouldContinueFetchingCoins = false;
      }).finally(() => {
        coin.isProcessing = false;
      });

      if (coinIndex < 2)
        coinIndex++;
      else
        coinIndex = 0;
    } while (shouldContinueFetchingCoins);
  } while (shouldContinueFetchingCoins);

  console.log("End Processing");
})();
```

**Comment by kroitor** [comment]
@ivnnv i'll post a working example here without `await`. Side question: any specific reason why you wouldn't want to use the modern `async/await` approach to Promises? It would help streamline your design, frankly.

**Comment by ivnnv** [comment]
The reason is if I `await` I could not benefit of fetching as many coins as possible on paralell.
Thats what Im currently doing and I can not get fresh last-minute candles for each coin if I try to get 200 coins from a single exchange [delay 2-4 minutes].

**Comment by kroitor** [comment]
> The reason is if I `await` I could not benefit of fetching as many coins as possible on paralell.

That is actually what `async/await` is all about – running the code in parallel, you might want to take a deeper look into it.

I'll post a script here shortly that fetches OHLCVs for a number of pairs with respect to the exchange rate limits, and it does that in parallel.

**Comment by kroitor** [comment]
@ivnnv try this and let me know if it does not help:

```
const ccxt = require ('ccxt')


async function symbolLoop (exchange, symbol, timeframe) {
    while (true) {
        try {
            const ohlcvs = await exchange.fetchOHLCV (symbol, timeframe)
            console.log (symbol, 'batchTradesCallBack.length', ohlcvs.length)
            // await exchange.sleep (60 * 1000) // sleep one minute if necessary, though not required
        } catch (e) {
            console.log (symbol, e.constructor.name, e.message)
        }
    }
}

async function main () {
    const exchange = new ccxt.binance ()
    const symbols = [
        'BTC/USDT',
        'ETH/USDT',
        'ADA/USDT',
    ]
    const timeframe = '1m'
    const loops = symbols.map (symbol => symbolLoop (exchange, symbol, timeframe))
    await Promise.all (loops)
}


main ()
```

**Comment by ivnnv** [comment]
@kroitor yeah the above example works, and ill definitelly adapt my use case to use that approach, thanks for the help.

But it is also true that the request is somehow never resolving on my above callback-based example right? Just to confirm im not crazy :P

**Comment by kroitor** [comment]
> But it is also true that the request is somehow never resolving on my above callback-based example right? Just to confirm im not crazy :P

I'm not sure yet, will post an alternative version of it without the use of `async/await`, using then-callbacks.

**Comment by kroitor** [comment]
@ivnnv here's a snippet that does the same without `async/await`:

```JavaScript
'use strict';

const ccxt = require ('ccxt')

console.log('CCXT Version:', ccxt.version)

function symbolLoop (exchange, symbol, timeframe) {
    exchange.fetchOHLCV (symbol, timeframe).then (ohlcvs => {
        console.log (exchange.iso8601 (exchange.milliseconds ()), exchange.id, symbol, ohlcvs.length, 'OHLCV candles received')
        setTimeout (() => symbolLoop (exchange, symbol, timeframe), 0)
    }).catch (e => {
        console.log (exchange.iso8601 (exchange.milliseconds ()), exchange.id, symbol, e.constructor.name, e.message)
        setTimeout (() => symbolLoop (exchange, symbol, timeframe), 0)
    })
}

function main () {
    const exchange = new ccxt.binance ()
    // exchange.verbose = true // uncomment for debugging purposes if necessary
    const symbols = [
        'BTC/USDT', // unified symbols used here as opposed to exchange-specific market ids
        'ETH/USDT', // more about unified symbols vs exchange-specific ids here:
        'ADA/USDT', // https://docs.ccxt.com/en/latest/manual.html#markets
    ]
    const timeframe = '1m'
    exchange.loadMarkets ().then (markets => {
        for (const symbol of symbols) {
            setTimeout (() => symbolLoop (exchange, symbol, timeframe), 0)
        }
    })
}

main ()
```

You can find both snippets here:

- https://github.com/ccxt/ccxt/blob/master/examples/js/binance-fetch-ohlcv-many-symbols-async-await.js
- https://github.com/ccxt/ccxt/blob/master/examples/js/binance-fetch-ohlcv-many-symbols-promise-then-callbacks.js

Obviously, this is not an issue with CCXT, it depends on how you structure your code in the userland. Closing this for now, feel free to reopen it or just ask further questions if any.

**Comment by ivnnv** [comment]
@kroitor thanks for the detailed snippet and putting those as example for others to use, Im definitelly implemeting the per-symbol async'ed way 👍🏽
