### ISSUE TITLE
"TRADES[]" data with Bybit when order is executed is empty

### ISSUE THREAD

**Issue by Naografix** [ccxt/ccxt#14063]
Hello,

I just integrated Bybit to my project and I can see  that there is nothing in the "TRADES" tag while other exchanges, like Binance, have content.
I use this tag to be able to retrieve the purchase PRICE and the AMOUNT.

Is it normal that it is empty?

```
{
  info: {
    accountId: '',
    symbol: 'BTCUSDT',
    symbolName: 'BTCUSDT',
    orderLinkId: '',
    orderId: '', 
    transactTime: '',  
    price: '0',
    origQty: '0.00094',
    executedQty: '0',
    status: 'NEW',
    timeInForce: 'GTC',
    type: 'MARKET',
    side: 'SELL'
  },
  id: '',
  clientOrderId: '',
  timestamp: ,
  datetime: '2022-06-25T23:16:30.401Z',
  lastTradeTimestamp: undefined,
  symbol: 'BTC/USDT',
  type: 'market',
  timeInForce: 'GTC',
  postOnly: false,
  side: 'sell',
  price: undefined,
  stopPrice: undefined,
  amount: 0.00094,
  cost: undefined,
  average: undefined,
  filled: 0,
  remaining: 0.00094,
  status: 'open',
  fee: undefined,
  trades: [],
  fees: []
}
```

**Comment by kroitor** [comment]
> Is it normal that it is empty?

Yes, that is normal, some exchanges won't return trades immediately, so you have to fetch the order again or fetch the order trades, depending on which method the [`exchange.has`](https://docs.ccxt.com/en/latest/manual.html#exchange-metadata). In general, you should not rely on trades being available immediately from `create_order`, but you can usually fetch them later when the exchange engine updates its internal database, use `fetch_order`, `fetch_orders`, `fetch_order_trades`, `fetch_closed_orders`, `fetch_open_orders` and `fetch_my_trades` whatever is available from the underlying exchange API. Hope that answers your question, let us know if not. Feel free to reopen this issue or just ask further questions if any.

**Comment by Naografix** [comment]
> > Is it normal that it is empty?
> 
> Yes, that is normal, some exchanges won't return trades immediately, so you have to fetch the order again or fetch the order trades, depending on which method the [`exchange.has`](https://docs.ccxt.com/en/latest/manual.html#exchange-metadata). In general, you should not rely on trades being available immediately from `create_order`, but you can usually fetch them later when the exchange engine updates its internal database, use `fetch_order`, `fetch_orders`, `fetch_order_trades`, `fetch_closed_orders`, `fetch_open_orders` and `fetch_my_trades` whatever is available from the underlying exchange API. Hope that answers your question, let us know if not. Feel free to reopen this issue or just ask further questions if any.

Aarg, it's really a pity to make a whole system only for Bybit... I'm a bit sad...

I will get the order back as I only work in market order.

Thanks

**Comment by Naografix** [comment]
> > Is it normal that it is empty?
> 
> Yes, that is normal, some exchanges won't return trades immediately, so you have to fetch the order again or fetch the order trades, depending on which method the [`exchange.has`](https://docs.ccxt.com/en/latest/manual.html#exchange-metadata). In general, you should not rely on trades being available immediately from `create_order`, but you can usually fetch them later when the exchange engine updates its internal database, use `fetch_order`, `fetch_orders`, `fetch_order_trades`, `fetch_closed_orders`, `fetch_open_orders` and `fetch_my_trades` whatever is available from the underlying exchange API. Hope that answers your question, let us know if not. Feel free to reopen this issue or just ask further questions if any.

Aarg, it's really a pity to make a whole system only for Bybit... I'm a bit sad...

I will get the order back as I only work in market order.

Thanks
