### ISSUE TITLE
Huobi Bad fee data in fetch_closed_spot_orders

### ISSUE THREAD

**Issue by Curro666** [ccxt/ccxt#14060]
- OS: Windows
- Programming Language version: Python Python 3.8.10
- CCXT version: CCXTversion 1.88.65

Hello,
i see bad fee data when import closed spot orders in Huobi. 

This is the data returned for one order using huobi.fetch_closed_spot_orders('CAW/USDT')

{'info': 
{'id': '563643151353171', 'symbol': 'cawusdt', 'account-id': 'XXXXXXX', 'client-order-id': '', 'amount': '75025608.000000000000000000', 'price': '0.000000060769000000', 'created-at': '1655157071951', 
'type': 'buy-limit', 'field-amount': '75025608.000000000000000000', 'field-cash-amount': '4.559231172552000000', 'field-fees': '150051.216000000000000000', 'finished-at': '1655157124601',
 'source': 'spot-api', 'state': 'filled', 'canceled-at': '0'}, 'id': '563643151353171', 'clientOrderId': None, 'timestamp': 1655157071951, 'datetime': '2022-06-13T21:51:11.951Z', 
 'lastTradeTimestamp': None, 'symbol': 'CAW/USDT', 'type': 'limit', 'timeInForce': None, 'postOnly': None, 'side': 'buy', 'price': 6.0769e-08, 'stopPrice': None, 'average': 6.0769e-08, 
 'cost': 4.559231172552, 'amount': 75025608.0, 'filled': 75025608.0, 'remaining': 0.0, 'status': 'closed', 
 'fee': {'cost': 150051.216, 'currency': 'CAW'}, 'trades': [], 'fees': [{'cost': 150051.216, 'currency': 'CAW'}], 

In this returned data i see what the fee is in CAW but not correct. I see in the website what the fee are in HT coin.

Now im use huobi.fetch_order_trades('563643151353171') and get the data (in this case is the same as website of Huobi)

[{'id': '561618077945718', 
'info': 
{'symbol': 'cawusdt', 'fee-currency': 'caw', 'source': 'spot-api', 'role': 'maker', 'price': '0.000000060769', 'order-id': '563643151353171', 'created-at': '1655157124599', 'filled-fees': '0', 
'filled-points': '0.001541504631292074', 'fee-deduct-currency': 'ht', 'fee-deduct-state': 'done', 'filled-amount': '75025608', 'match-id': '55879657', 'trade-id': '1419731', 'id': '561618077945718', 
'type': 'buy-limit'}, 
'order': '563643151353171', 'timestamp': 1655157124599, 'datetime': '2022-06-13T21:52:04.599Z', 'symbol': 'CAW/USDT', 'type': 'limit', 'side': 'buy', 'takerOrMaker': 'maker', 'price': 6.0769e-08, 
'amount': 75025608.0, 'cost': 4.559231172552, 
'fee': {'cost': 0.001541504631292074, 'currency': 'HT'}, 
'fees': [{'currency': 'HT', 'cost': 0.001541504631292074}]}]

Sorry for my english :-)

BR

**Comment by kroitor** [comment]
@Curro666 in CCXT all structures that you get contain the `info` dictionary, that is the exchange response as is, untouched. 

In the first case, the exchange returns the fees for the entire order and the fee currency there is in CAW, you can verify that if you divide `'field-fees': '150051.216000000000000000'` by `'field-amount': '75025608.000000000000000000'`:

```
150051.216000000000000000 / 75025608.000000000000000000 = 0.002 = 0.2% fee
```

In the second case the exchange does specify the fee currency along with the fee itself, so it shows HT in trades.

Obviously, we can't really invent that information out of thin air, and what you see is coming from the exchange directly. I'd recommend forwarding your question to the exchange's tech support, since the above is not an issue in CCXT, really.

**Comment by Curro666** [comment]
I'm not sure what you're saying is entirely correct. I'm doing some research and I still don't have things clear, I think something is wrong and now I'm a bit confused.

with ccxt received this (huobi.fetch_order_trades('563643151353171'))
[
{'id': '561618077945718', 
'info': {
	'symbol': 'cawusdt', 
	'fee-currency': 'caw', 
	'source': 'spot-api', 
	'role': 'maker', 
	'price': '0.000000060769', 
	'order-id': '563643151353171', 
	'created-at': '1655157124599',
	'filled-fees': '0', 'filled-points': '0.001541504631292074', 
	'fee-deduct-currency': 'ht', 
	'fee-deduct-state': 'done', 
	'filled-amount': '75025608', 
	'match-id': '55879657', 'trade-id': '1419731', 'id': '561618077945718', 'type': 'buy-limit'}, 
 
 'order': '563643151353171', 
 'timestamp': 1655157124599, 
 'datetime': '2022-06-13T21:52:04.599Z', 
 'symbol': 'CAW/USDT', 
 'type': 'limit', 
 'side': 'buy', 
 'takerOrMaker': 'maker', 
 'price': 6.0769e-08, 
 'amount': 75025608.0, 
 'cost': 4.559231172552, 
 'fee': {'cost': 0.001541504631292074, 'currency': 'HT'}, 'fees': [{'currency': 'HT', 'cost': 0.001541504631292074}]}]

but when comparing with the api of     https://github.com/HuobiRDCenter/huobi_Python
receive this:
Order Id : 563643151353171
Symbol : cawusdt
Price : 0.000000060769000000
Amount : 75025608.000000000000000000
Create Time : 1655157071951
Cancel Time : 0
Finish Time : 1655157124601
Order Type : buy-limit
Filled Amount : 75025608.000000000000000000
Filled Cash Amount : 4.559231172552000000
Filled Fees : 150051.216000000000000000
Order Source : spot-api
Order State : filled
Client Order Id : 
Stop Price : 
Operator : 
Next Time : 0

It is true that the data sent by the exchange is not correct, but the fact is that in ccxt the fees work out if I consult an order only despite the fact that the exchange provides the wrong data. That data comes from somewhere and my question is, can't the same thing be done so that the data returned by huobi.fetch_closed_spot_orders('CAW/USDT') comes out right?

**Comment by kroitor** [comment]
> can't the same thing be done so that the data returned by huobi.fetch_closed_spot_orders('CAW/USDT') comes out right?

I don't see how that can be done, since Huobi does not return the fee currency in the response from the fetch_closed_spot_orders endpoint, just the fee size.

**Comment by kroitor** [comment]
@Curro666 we have raised this to the Huobi tech team, will let you know if/when it gets fixed.

**Comment by Curro666** [comment]
Thanks for your attention. It really is better this way, you can explain the problem better than me :-).
I am testing everything related to Huobi with ccxt and I see something else that can be improved, such as fetch_closed_spot_orders. There is only one parameter for since and the exchange provides two, start and end. In ccxt the 'end' is wrapped automatically.
I think that it should be in such a way that if the data is not provided it becomes automatic but it should be in order to be able to use it correctly.
I know that there is a problem with Huobi because it only returns a maximum of 100 orders and for me it is a problem because I have more than 100 operations in less than 1 hour. As I did not download the files before, it is a bit tedious when it comes to being able to import all the records.
Right now I am using a script for purchases with another api and I wanted to pass the script to ccxt because it would allow me to be able to expand to other exchanges with minimal changes.
I have also seen that you have ccxt pro and I have some doubt about if I pay for a month and then I can continue enjoying the code even if I don't pay more for the moment until updates come out.
I can't afford to pay every month and at the moment I'm using other systems than ccxt where I use rest for certain things and websocket for order and price updates.

**Comment by kroitor** [comment]
@Curro666 i'd recommend reading this CCXT Pro release issue for licensing questions, it has the answers to most questions, make sure to expand the collapsed comments as well: https://github.com/ccxt/ccxt/issues/6543

Also, please, note that CCXT Pro will become free in Q3 2022 (very soon): https://ccxt.pro

**Comment by Curro666** [comment]
I think you misunderstood what I wanted to tell you earlier, I'll try to explain it better :-).

using ccxt
order = '563643151353171'
m = huobi.fetch_order_trades(order)

CCXTversion 1.88.65
[{'id': '561618077945718', 'info': {'symbol': 'cawusdt', 'fee-currency': 'caw', 'source': 'spot-api', 'role': 'maker', 'price': '0.000000060769', 'order-id': '563643151353171', 'created-at': '1655157124599', 'filled-fees': '0', 'filled-points': '0.001541504631292074',
 'fee-deduct-currency': 'ht',
 'fee-deduct-state': 'done', 
'filled-amount': '75025608', 'match-id': '55879657', 'trade-id': '1419731', 'id': '561618077945718', 'type': 'buy-limit'}, 'order': '563643151353171', 'timestamp': 1655157124599, 'datetime': '2022-06-13T21:52:04.599Z', 'symbol': 'CAW/USDT', 'type': 'limit', 'side': 'buy', 'takerOrMaker': 'maker', 'price': 6.0769e-08, 'amount': 75025608.0, 'cost': 4.559231172552,
 'fee': {'cost': 0.001541504631292074, 'currency': 'HT'}, 
'fees': [{'currency': 'HT', 'cost': 0.001541504631292074}]}]

I get the data of the fees perfectly despite the fact that the exchange provides the fees data wrong.





> > can't the same thing be done so that the data returned by huobi.fetch_closed_spot_orders('CAW/USDT') comes out right?
> 
> I don't see how that can be done, since Huobi does not return the fee currency in the response from the fetch_closed_spot_orders endpoint, just the fee size. It boils down to data that is available from the exchange, CCXT does not invent that data, it is taken from the exchange first-hand, so whatever data the exchange returns – you get that with CCXT, and we don't alter it. Hope that answers your question, let us know if not.

**Comment by kroitor** [comment]
> I think you misunderstood what I wanted to tell you earlier, I'll try to explain it better :-).

I mean, I got that, but that doesn't change my reply above – it still holds. We cannot determine the currency of fetch_closed_spot_orders, since the exchange API does not indicate the fee currency there.

**Comment by ttodua** [comment]
i think this issue no longer exists, so closing this topic.
if anyone experiences similar, let us know again
