### ISSUE TITLE
New Exchange: Upcoin

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1406]
api doc:
url: https://upcoin.com/?ID=3d5fac28
fee: 0.1%, 0.2%
volume: https://coinmarketcap.com/exchanges/upcoin/
address: 
company info: 
Registration 
based country: 
priority: low
note: ranked top : NA

previous: conversations - https://bitcointalk.org/index.php?topic=2645776.0, https://www.facebook.com/upcoin.exchange/
registration: https://upcoin.com/?ID=3d5fac28

**Comment by jjhesk** [comment]
lets put this to the backlog. They are still testing their beta API from the channel discussion.

**Comment by An-Net** [comment]
Shutdown

- https://www.reddit.com/r/Upcoin/comments/9uqp04/is_this_exchange_dead/

![Снимок экрана 2020-07-20 в 16 54 15](https://user-images.githubusercontent.com/51840849/87945752-db8dab80-caa9-11ea-9b9d-3b292e0c7e33.png)
