### ISSUE TITLE
New Exchange: bitcoin.de

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1407]
api doc: https://www.bitcoin.de/en/api/marketplace
url: https://www.bitcoin.de
fee: --
volume: https://coinmarketcap.com/exchanges/bitcoin-de/
address: Nordstraße 14, 32051 Herford, Germany
company info: Bitcoin Deutschland AG
Registration: Die Bitcoin Group SE ist eine Holding mit Schwerpunkt auf innovativen und disruptiven Geschäftsmodellen und Technologien aus den Bereichen Cryptocurrency und Blockchain, https://www.bitcoin.de/en/impressum
based country: Germany
priority: low 
note: ranked top : NA

**Comment by jjhesk** [comment]
api key needs to apply independently. aml is uphigh

**Comment by jjhesk** [comment]
Bitcoin.de Specifications
==============================
From their API page:  "Access to the API is limited to two calls every 60 seconds. Tradehistory and orderbook are updated every 60 seconds."
An API key is required for access, API keys are open to anybody with an account. Create one on their API page (linked below).

Links:
	[1] https://www.bitcoin.de/en
	[2] https://www.bitcoin.de/de/api/marketplace

**Comment by GuybrushX** [comment]
Just want to add:
You have to request API access. Seems they handle that manually since after around 2 weeks (probably more) I still didn't get anything from them.

It also seems that they have v1 + v2. On the website I saw v1 only but I found that repo which is talking about v2:
https://github.com/peshay/btcde -> seems it's not implementing BTG yet

But yes, API access in ccxt would be very nice :-)

**Comment by machinekoder** [comment]
`v2` API can be accessed directly without user intervention. It's a bit misleading since the Google link points to the legacy API which requires manual issuing of the key.

**Comment by machinekoder** [comment]
The exchange is very important for the German/DACH region. It was one of the first ones around and is probably one of the most secure exchanges here.

**Comment by kroitor** [comment]
@machinekoder the problem with integrating it is actually getting the keys for testing... They're too restrictive to non-european citizens...

**Comment by machinekoder** [comment]
@kroitor I can test if you want.

**Comment by MarcelBeining** [comment]
any news on that?

**Comment by kroitor** [comment]
@MarcelBeining not yet, but we hope to address it this week.

**Comment by MarcelBeining** [comment]
I dont know if this is relevant for your implementation but I got this message from bitcoin.de about API changes:


Dear Bitcoin.de Trading-API User,

we want to inform you about an upcoming change in our SSL/TLS
configuration that might need your attention.

If you're using a software or app to interact with our
Trading-API at api.bitcoin.de your software is currently
able to connect to api.bitcoin.de via https using protocol
TLS 1.0, TLS 1.1 or TLS 1.2.

As of June 1st, 2018 our servers will only accept https
connections using protocol TLS 1.2 or TLS 1.3.

It is of utmost importance you make sure that your software
(and libraries your software might use) all support at least
TLS 1.2. Connections from clients that only support TLS 1.1 or
earlier will be refused as of June 1st, 2018.

How do I make sure my software can connect after June 1st, 2018?
================================================================

To check that your software stack is able to connect to
bitcoin.de Trading-API after June 1st, 2018 we have setup
a new domain bitcoinapi.de that has the new TLS settings applied
already.

WARNING: bitcoinapi.de is NOT a sandbox or test environment!
         It interacts with your bitcoin.de account like
         api.bitcoin.de does.

If you want to check your software stack for compliance
with the new TLS requirements we suggest you modify your
software to do e.g. order book retrievals via the
bitcoinapi.de domain.

**Comment by MarcelBeining** [comment]
any news on implementation of bitcoin.de API ?

**Comment by kroitor** [comment]
@MarcelBeining hope to get to it soon...

**Comment by MarcelBeining** [comment]
Still not implemented?

**Comment by MarcelBeining** [comment]
Hello?

**Comment by kroitor** [comment]
@MarcelBeining really sorry for the delay, didn't have a chance to get to it yet.

**Comment by MarcelBeining** [comment]
@kroitor If I can be of any help, tell me. Hope you get to it before the end of the year (when I would need it). ;-)

**Comment by kroitor** [comment]
@MarcelBeining I apologize for the wait, I know it's a terribly long delay, but, hey, we have some good news, if you can provide us with sample output of the following URLs, we think we could integrate their API this week (change for your key below):

- https://bitcoinapi.de/v1/YOUR_API_KEY/trades.json
- https://bitcoinapi.de/v1/YOUR_API_KEY/orderbook.json
- https://bitcoinapi.de/v1/YOUR_API_KEY/rate.json

**Comment by kroitor** [comment]
This sucks, by the way:

<img width="1116" alt="screen shot 2018-11-02 at 10 51 48" src="https://user-images.githubusercontent.com/1294454/47900274-5f92a080-de8d-11e8-8e57-90e260df20c1.png">

Restricting access to the API itself is understandable, but restricting access to API docs is a poor policy, we think. Developers have to rely on 3rd party info instead of having it from first hands, that is, the exchange itself. We will have to recollect the spec from what is published on the internet, npm, pypi, github, etc...

**Comment by MarcelBeining** [comment]
Hi @kroitor ,
nice to hear from you! Ok I'll check the results, however as far as I could see, the way the requests are made is different. E.g. the orderbook is checked by making a request to https://api.bitcoin.de/v2/orders (or v1) with fields: type and optional fields: amount ,price,order_requirements_fullfilled ,only_kyc_full , only_express_orders , only_same_bankgroup ,only_same_bic ,seat_of_bank.

Do you need the whole bitcoin.de API documentation (v1/v2?) ? I could copy it for you. Yes it is really annoying that they do not provide API info publicy, I guess it is the "German security thinking" :-D

By the way, that guy here make a python framework for bitcoin.de API requests, maybe this is also of help for you:
https://github.com/peshay/btcde

**Comment by kroitor** [comment]
Hi, @MarcelBeining !

> Do you need the whole bitcoin.de API documentation (v1/v2?) ? I could copy it for you. Yes it is really annoying that they do not provide API info publicy, I guess it is the "German security thinking" :-D

Yes, that would help a lot! If you can, please, post it here or send me a link or an archive to igor@ccxt.trade.

> By the way, that guy here make a python framework for bitcoin.de API requests, maybe this is also of help for you: https://github.com/peshay/btcde

Yep, we also found https://www.npmjs.com/package/bitcoinde-api and some other implementations, just wanted to make sure that we are in line with their official docs...

Thx for your involvement!

**Comment by marcelvoss95** [comment]
Here is the doc of Bitcoin.de.
Its in german but maybe it helps...

[Bitcoin.de Trading-API - v2.pdf](https://github.com/ccxt/ccxt/files/2592232/Dokumentation.der.Bitcoin.de.Trading-API.-.v2.pdf)

**Comment by MarcelBeining** [comment]
Hi Igor, any news on that? It starts to get urgent for tax report ;-)

**Comment by MarcelBeining** [comment]
This request has its birthday in 2 days. Any proceedings or something I can help with? I really need that support of ccxt for bitcoin.de

**Comment by MarcelBeining** [comment]
So are there any issues right now why this has not been implemented yet? Unfortunately taxes are now due and I have to find another solution for this exchange than ccxt =/

**Comment by phips28** [comment]
Is bitcoin.de already implemented, couldn't find anything? Any plans on implementing it?

**Comment by frosty00** [comment]
closing due to low volume / not a priority
