### ISSUE TITLE
IDEX Rate limit exceeded with two consecutive public API calls

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#14088]
- OS: Linux Mint
- Programming Language version: Python 3.10
- CCXT version: 1.89.14

Rate limiting error occurs with IDEX every time (at least at this moment) with the following code:
```
exchange = ccxt.idex()
exchange.fetch_markets()
exchange.fetch_tickers()
```

```
Traceback (most recent call last):
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 617, in fetch
    response.raise_for_status()
  File "/home/xyz/.local/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api-matic.idex.io/v1/tickers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xyz/test.py", line 5, in <module>
    exchange.fetch_tickers()
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/idex.py", line 383, in fetch_tickers
    response = self.publicGetTickers(params)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 497, in inner
    return entry(_self, **inner_kwargs)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2616, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2613, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 633, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/idex.py", line 1383, in handle_errors
    raise Exception(self.id + ' ' + message)
ccxt.base.errors.DDoSProtection: idex Rate limit exceeded
```
If I add `time.sleep(0.8)` between the two API calls  (making the code wait 0.8 seconds before the next call) I see no error.

According to IDEX API documentation (https://api-docs-v3.idex.io/#rate-limits) the number of allowed calls depends on the type of the endpoint, whether API keys were used or not and whether the call returns at max 100 objects or more. `fetch_markets` and `fetch_tickers` both return 27 objects at the moment, but I suppose IDEX still considers them to be a "bundled" requests that require 1 s rate limiting time. The same problem might apply to other methods like `fetch_balance`, `fetch_open_orders`, `fetch_my_trades` ect. but I haven't tested those ones out.

If I understood the code correctly, ccxt is currently assuming 200 ms rate limit for every IDEX endpoint. I know that the new rate limiting method is still under construction in ccxt (#13949), but it would still be nice to avoid the rate limiting errors, maybe with some temporary fix.

The new rate limiting method allows different rate limits for different endpoints, but in case of IDEX it also makes a difference whether API keys were used and whether the call was "single" or "bundled". I wonder if these could also be taken into account in the ccxt code - at least the latter case feels quite relevant.

EDIT: After some further testing the rate limiting error does not seem to occur in this particular test case if I use API keys, so I don't think IDEX documentation is quite up do date.

**Comment by ttodua** [comment]
if anyone still experiences issue with this, let us know
