### ISSUE TITLE
I want to use 'CROSS leverage'. But my code does not work.

### ISSUE THREAD

**Issue by BamsoonPapa** [ccxt/ccxt#14083]
- OS: Windows 11
- Programming Language version: Python (Jupyter notebook)
- CCXT version: 1.84.87

This is a function that make SHORT with market price by the specified quantity.
I want to use 'CROSS leverage'.
But below code does not work.
Could you help me?

def shortMarketPriceQty_FuturesUSD(exchange, usd, coin, qty, lvrg):
        ecg = eval("ccxt." + exchange.lower() + 
                   "(config={'apiKey':API_KEY_" + exchange.lower() +
                   ",'secret':SECRET_KEY_" + exchange.lower() +
                   ",'enableRateLimit':True,'options':{'defaultType':'future'}})")

        ecg.load_markets()
        symbol = coin + "/" + usd
        market = ecg.market(symbol)
        ecg.fapiPrivate_post_leverage({
            'symbol':market['id'],
            'leverage':lvrg,
            'isIsolated': 'FALSE'
        })

        result = ecg.create_market_sell_order(
            symbol = coin + "/" + usd,
            amount = qty
            )

        return result

**Comment by kroitor** [comment]
@BamsoonPapa please, upgrade to the most recent version of CCXT, enable verbose output and paste the verbose request + response log here:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
    ecg.load_markets()
    ecg.verbose = True  # <<<<<<<<<<<<<<<<<<<<<<<< after loading the markets
    symbol = coin + "/" + usd
    market = ecg.market(symbol)
    ecg.fapiPrivate_post_leverage({
        'symbol':market['id'],
        'leverage':lvrg,
        'isIsolated': 'FALSE'
    })

    result = ecg.create_market_sell_order(
        symbol = coin + "/" + usd,
        amount = qty
        )

    return result
```

**Comment by ttodua** [comment]
as there has not been any follow-up, i'm closing this issue as stale.
Let us know further if you still face any issue with CCXT.
