### ISSUE TITLE
BIBOX fetch_my_trades from fetch_markets - possible issue?

### ISSUE THREAD

**Issue by derki-source** [ccxt/ccxt#14095]
- OS: any
- Programming Language version: python
- CCXT version: 1.89.17

`fetch_markets()` returns symbols including "NFT/USDT", as far as my understanding goes, all of these symbols should be usable as `symbol` for `fetch_my_trades()`
```
exchange.fetch_my_trades(symbol="NFT/USDT")
exchange.fetch_my_trades(symbol="nonexistingcode")
```

the error also differ for non existing symbol vs the NFT/USDT
```
# error for NFT/USDT:
ccxt.base.errors.ExchangeNotAvailable: bibox POST https://api.bibox.com/v1/orderpending 403 Forbidden <!DOCTYPE html>
# error for nonexistingcode
ccxt.base.errors.BadSymbol: bibox does not have market symbol nonexistingcode
```

this is the only exchange implementation so far where I cant directly use to fetch all of the account trades for all markets:
```
for market in exchange.fetch_markets():
    exchange.fetch_my_trades(symbol=market["symbol"])
```

I am not sure if this is intended behaviour or not, if yes feel free to close it

**Comment by samgermain** [comment]
The bibox api endpoints will hopefully soon be updated to v4 and v3, so this issue should be fixed when that happens
