### ISSUE TITLE
The most accurate way to determine futures trading support?

### ISSUE THREAD

**Issue by RoscoeTheDog** [ccxt/ccxt#14099]
I am trying to implement futures to improve my existing DCA strategy that is already deployed on the normal spot Binance.US markets. To be perfectly clear: I have this running fine with generic `place_order()` methods using ccxt and binance. The Kucoin exchange is currently the only one that offers futures here in the US, so I am trying to wrap it's functions and translate it's returned dict data so it can behave the same in the strategy's run block. It seems that `kucoin` or `kucoinfutures` do not return the same or all relevant data that `binance` does, so like I said it needs to be parsed manually.

I'm currently sending off a message with JSON to an endpoint on a webhost on my server and this does a couple of things. This will parse a config, async run the trade bot with ccxt, check if that exchange supports futures, and return that information that relevant info to the user. The problem is I don't see any _**reliable way of checking**_ a market if it supports futures. This is somewhat problematic since it operates on how many target buy/sell contracts to place for each order, which is calculated differently from spot buying the asset directly based on each markets `precision` value. Because of this they also have to be handled differently when invoking an wrapped `place_order` function call in my program which I want to be compatible with multiple exchanges.

As a band-aid solution, I am checking for string `"futures"` in the targeted exchange id which works in the case of `kucoinfutures` but this doesn't work when trying to call the wrapped function targeting the mexc exchange instead, since it's name is registered as `"mexc"` or `"mexc3"`. MEXC supports futures but I'm still not really aware on how to implement it using the ccxt API.

What is the most accurate way of determining whether an instantiated exchange supports futures markets?

**Comment by samgermain** [comment]
If you check the has array you can see if an exchange has futures support. We try not to set it to true until it has full support from all the existing methods.

```
# -*- coding: utf-8 -*-

import json
import ccxt  # noqa: E402
from pprint import pprint

keys = json.load(open('../keys.local.json'))
exchange = ccxt.mexc()
pprint(exchange.has)

'''
{
    'CORS': None,
    'addMargin': True,
    'cancelAllOrders': True,
    'cancelOrder': True,
    'cancelOrders': None,
    'createDepositAddress': None,
    'createLimitOrder': True,
    'createMarketOrder': False,
    'createOrder': True,
    'createPostOnlyOrder': None,
    'createReduceOnlyOrder': False,
    'createStopLimitOrder': True,
    'createStopMarketOrder': False,
    'createStopOrder': True,
    'editOrder': 'emulated',
    'fetchAccounts': None,
    'fetchBalance': True,
    'fetchBidsAsks': None,
    'fetchBorrowInterest': None,
    'fetchBorrowRate': None,
    'fetchBorrowRateHistory': None,
    'fetchBorrowRates': None,
    'fetchBorrowRatesPerSymbol': None,
    'fetchCanceledOrders': True,
    'fetchClosedOrder': None,
    'fetchClosedOrders': True,
    'fetchCurrencies': True,
    'fetchDeposit': None,
    'fetchDepositAddress': True,
    'fetchDepositAddresses': None,
    'fetchDepositAddressesByNetwork': True,
    'fetchDeposits': True,
    'fetchFundingFee': None,
    'fetchFundingFees': None,
    'fetchFundingHistory': True,
    'fetchFundingRate': True,
    'fetchFundingRateHistory': True,
    'fetchFundingRates': False,
    'fetchIndexOHLCV': True,
    'fetchL2OrderBook': True,
    'fetchLedger': None,
    'fetchLedgerEntry': None,
    'fetchLeverage': None,
    'fetchLeverageTiers': True,
    'fetchMarginMode': False,
    'fetchMarkOHLCV': True,
    'fetchMarketLeverageTiers': 'emulated',
    'fetchMarkets': True,
    'fetchMyTrades': True,
    'fetchOHLCV': True,
    'fetchOpenInterestHistory': False,
    'fetchOpenOrder': None,
    'fetchOpenOrders': True,
    'fetchOrder': True,
    'fetchOrderBook': True,
    'fetchOrderBooks': None,
    'fetchOrderTrades': True,
    'fetchOrders': None,
    'fetchPermissions': None,
    'fetchPosition': True,
    'fetchPositionMode': True,
    'fetchPositions': True,
    'fetchPositionsRisk': False,
    'fetchPremiumIndexOHLCV': True,
    'fetchStatus': True,
    'fetchTicker': True,
    'fetchTickers': True,
    'fetchTime': True,
    'fetchTrades': True,
    'fetchTradingFee': False,
    'fetchTradingFees': True,
    'fetchTradingLimits': None,
    'fetchTransactions': None,
    'fetchTransfer': True,
    'fetchTransfers': True,
    'fetchWithdrawal': None,
    'fetchWithdrawals': True,
    ##########################################################################################
    'future': False,
    ##########################################################################################
    'loadMarkets': True,
    'margin': None,
    'option': False,
    'privateAPI': True,
    'publicAPI': True,
    'reduceMargin': True,
    'setLeverage': True,
    'setMargin': None,
    'setMarginMode': False,
    'setPositionMode': True,
    'signIn': None,
    'spot': True,
    'swap': True,
    'transfer': True,
    'withdraw': True
}
'''
```
