### ISSUE TITLE
Fetching OHLVC futures data on bybit, doesn't work after update 

### ISSUE THREAD

**Issue by Kalelv45** [ccxt/ccxt#14091]
- OS: iOS Mojave 
- Programming Language version: python3.7
- CCXT version:1.89.5

```
scrape_candles_to_csv('LTC_bybit.csv', 'bybit', 500, 'LTC/USDT', '1h', '2022-06-20T00:00:00Z', 100)
```

Before the update when I was running this code it would automatically download perpetual future data. Now it doesn't. Can't find  a way. When you load markets many symbols have changed form LTC/USDT to LTC/USDT:USDT, yet if I use that it doesn't work either.

**Comment by carlosmiei** [comment]
Hello @Kalelv45,

Can you please post a verbose output with the error you're getting? Also, please bear in mind that to fetch OHLCV data from Bybit you need to provide necessarily the **since** and/or the **limit** argument.

Example:

```Python
# Providing the limit and the not the since
ohlcv = await exchange.fetch_ohlcv(symbol,'1m', None, 30)

# Providing the since and the not the limit
ohlcv = await exchange.fetch_ohlcv(symbol,'1m', 1656406144102, None)

# Providing both
ohlcv = await exchange.fetch_ohlcv(symbol,'1m', 1656406144102,30)
```

**Comment by ttodua** [comment]
@carlosmiei wdyt, maybe we can traverse all exchanges, and remove requirement of setting `since/limit` from exchanges, which require. so, in the background, we set i.e. `limit = 500` or whatever default,  if user doesn't provide `limit` arg. imho that might simplify the usage of exchanges in bulk/loop

**Comment by ttodua** [comment]
@Kalelv45 please provide any reply to above @carlosmiei 's response. Otherwise, we have no further clue.
To add a small note, you might do the following inside instantiation code of exchange:
```
exchange = ccxt.bybit()
exchange['optioins']['defaultType'] = 'spot' # or 'swap' or 'future'
exchange.load_markets()
# you can also: `print(exchange.markets.keys())` to see the symbol-names
```

If you face issues still, please let us know it with more details, as mentioned by Carlos.

**Comment by carlosmiei** [comment]
> @carlosmiei wdyt, maybe we can traverse all exchanges, and remove requirement of setting `since/limit` from exchanges, which require. so, in the background, we set i.e. `limit = 500` or whatever default, if user doesn't provide `limit` arg. imho that might simplify the usage of exchanges in bulk/loop

Yeah I agree, but we do that for some exchanges, so I don't even know if there's a reason to not do it for the others

**Comment by pleomax0730** [comment]
For those who want to fetch the future's kline, you need to set params={"category": "linear"}.

`
candles = exchange_client.fetch_ohlcv(symbol, timeframe=interval, since=None, limit=limit, params={"category": "linear"})
`

**Comment by ttodua** [comment]
there is no need to use `category: linear`  if users are using symbols  with standard CCXT format (https://docs.ccxt.com/#/README?id=consistency-of-base-and-quote-currencies ) , eg `XYZ/USDT` , `XYZ/USDT:USDT` etc..

**Comment by pleomax0730** [comment]
> there is no need to use `category: linear` if users are using symbols with standard CCXT format (https://docs.ccxt.com/#/README?id=consistency-of-base-and-quote-currencies ) , eg `XYZ/USDT` , `XYZ/USDT:USDT` etc..

Yes! {symbol}/USDT:USDT worked.
