### ISSUE TITLE
Binance Timeout Error 

### ISSUE THREAD

**Issue by BamsoonPapa** [ccxt/ccxt#14110]
- OS: Windows 11
- Programming Language version: Python (jupyter notebook)
- CCXT version:    1.84.87

When I use 'fetch_order_book()',
I've got bellow error message.  [~~~~ Read timed out. (read timeout=10)]
I want to increase 'timeout_value'
10 seconds is too short to guarantee stability of my system.
Could you tell me how to do?

File C:\anaconda3\lib\site-packages\urllib3\connectionpool.py:340, in HTTPConnectionPool._raise_timeout(self, err, url, timeout_value)
    339 if isinstance(err, SocketTimeout):
--> 340     raise ReadTimeoutError(
    341         self, url, "Read timed out. (read timeout=%s)" % timeout_value
    342     )
    344 # See the above comment about EAGAIN in Python 3. In Python 2 we have
    345 # to specifically catch it and throw the timeout error

ReadTimeoutError: HTTPSConnectionPool(host='fapi.binance.com', port=443): Read timed out. (read timeout=10)

**Comment by kroitor** [comment]
You can increase the timeout by setting the exchange.timeout value or by adding it to the exchange constructor (the timeout is in milliseconds):

```Python
import ccxt
exchange = ccxt.binance {{
    'timeout': 30000,
})
```

Also, make sure you don't violate this rule: https://docs.ccxt.com/en/latest/manual.html#notes-on-rate-limiter

Hope the above answers your question, let us know if not. Feel free to reopen this issue or just ask further questions if any.

**Comment by BamsoonPapa** [comment]
@kroitor 
thank you for your kind coaching.
Thanks to your advice, I was able to halve the number of API calls. Thank you for your kind help to a free member like me. I hope you have a good day.
