### ISSUE TITLE
'array' variable name crashes PHP because 'array' is a keyword 

### ISSUE THREAD

**Issue by KRV1** [ccxt/ccxt#14127]
Please refrain from using the **array** keyword as a variable name - it makes PHP code not work  with _Undefined variable: array_

So we got a lot of such places in Exchange.php etc...

**Comment by carlosmiei** [comment]
Hello @KRV1, did you find any other problematic scenario? We are aware that might be problematic in some specific cases

**Comment by kroitor** [comment]
@KRV1 We have removed most of the incorrect naming, please, paste a link to a problematic line in this file: 

- https://github.com/ccxt/ccxt/blob/master/php/Exchange.php

Make sure that your version of CCXT is up to date. Feel free to reopen this issue or just ask further questions here if the above does not help.
