### ISSUE TITLE
Bybit watchOrders skip order

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#14121]
We have noticed that on `watchOrders` sometimes order data doesn't appends in orders buffer when order is submitted via REST immediately after socket connection is established, i.e.:

Case#1
socket connection established (`onConnected`): 08:00:37.530
create order submitted via REST: 08:00:38.156
order received from REST (received status: `open`): 08:00:38.654
order completed on FTX (status: `closed`): 08:00:38.424 - not appeared in orders buffer

Case#2
socket connection established (`onConnected`): 01:59:19.968
create order submitted via REST: 01:59:19.995
order received from REST (received status: `open`): 01:59:20.318
order completed on FTX (status: `closed`): 01:59:20.215 - not appeared in orders buffer

Case#3
socket connection established (`onConnected`): 12:00:30.717
create order submitted via REST: 12:00:30.860
order received from REST (received status: `open`): 12:00:31.964
order completed on FTX (status: `closed`): 12:00:31.717 - not appeared in orders buffer

This cases show our requests flow.
So that socket connection established before order creation and `closed` order result should be in `watchOrders` buffer.
Maybe there is issue in our `watchOrders` reading implementation that lead to out issue:

```
while (true) {
	try {
                const orders = await exchange.watchOrders();

                do {
                    let order = orders.shift();

                    // received order handling
                } while (orders.length);
	}
	catch(e) {
		// on error handling and exit from loop 
	}
}
```

This issue is rare and hard to implement, but maybe it causes when multiple (1000+) socket connections established at the same time.
(Just in case, for each API profile we create separate exchange CCXT instance.)

- OS: Debian (Docker)
- Programming Language version: NodeJS, JavaScript
- CCXT version: PRO 1.1.82

**Comment by kroitor** [comment]
@wunderb1t we will merge the `onSubscribed` callback very soon: https://github.com/kroitor/ccxt.pro/pull/341 that should help mitigate your issue.

**Comment by wunderb1t** [comment]
Same issue we detect on Bybit sockets.

**Comment by wunderb1t** [comment]
Hi @kroitor .
Any updates? Thanks!

**Comment by wunderb1t** [comment]
Hi.
Any updates about this issue?

**Comment by wunderb1t** [comment]
Hi @kroitor @ttodua 
Any updates? Thanks!
