### ISSUE TITLE
When ccxtpro will be free?

### ISSUE THREAD

**Issue by flav1ooo** [ccxt/ccxt#14130]
What is exact date of ccxtpro free release?

Thank you.

**Comment by flav1ooo** [comment]
> Hi @flav1ooo we don't have an exact date except for as soon as we are ready to release it. Currently this is looking to be around the end of July / beginning of August

All currently supported features will be supported at that time, right?

**Comment by kroitor** [comment]
@frosty00 yes, that is correct, we're going to release it soon.
