### ISSUE TITLE
Kucoin fetchOrder

### ISSUE THREAD

**Issue by janeCMD** [ccxt/ccxt#1416]
This is a question, not an issue report.  I see, that kucoin doesnt support fetchOrder method.

Want to ask, if this is just temporary state since exchange is added not that long ago, or if there is some problem preventing to implement this method ? Its sort of important method...

Thanks

**Comment by janeCMD** [comment]
And additional question / Report. In OHLC, time returned is in normal second timestamp format, unlike other exchanges which return time in milisecond format. Should not this be the same ?

**Comment by wannesdemaeght** [comment]
https://kucoinapidocs.docs.apiary.io/#reference/0/trading/order-details

Supported by API, so should be possible.
I will take a look at this, but I'm a newbie, so don't get your hopes up :-)

**Comment by wannesdemaeght** [comment]
got response working, now parsing to unified response.
Should be ready shortly.

**Comment by davzucky** [comment]
@wannesdemaeght Thank you for doing that work, I was looking for it :-) Please let us know when the merge happen

**Comment by kroitor** [comment]
Added in #1431, had to rework it significantly, because for some reason filling trade fees were confused with order fees in #1431.
