### ISSUE TITLE
bitfinex2 symbols_details endpoint down

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1418]
- OS: linux
- Programming Language version: js
- CCXT version: 1.10.804
- Exchange: bitfinex2
- Method: loadmarkets

this api is down and maybe suggested to review the api health again.  #1051

**Comment by kroitor** [comment]
Sorry? What do you mean "down" ? Works for me, as far as I can tell. Can you clarify please?

**Comment by jjhesk** [comment]
the api for all market endpoints seems to be blocked. https://api.bitfinex.com/v2/symbols_details

**Comment by kroitor** [comment]
@jjhesk why do you think this is an endpoint at all? Can't find it anywhere in their docs. Where is this URL from?

**Comment by jjhesk** [comment]
@kroitor this is requested from ur ccxt library.

**Comment by kroitor** [comment]
@jjhesk sorry, my bad, missed it somehow, now i see it %) yes, now I understand, and yes, it seems like it is down... However, we are not requesting that URL from anywhere inside the library, are you sure it is requested?
