### ISSUE TITLE
Why CCXT Pro will become a free part of CCXT in Q3 2022 ?

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#14192]
Hello,

I'm just curious about the reason behind this anoucement. Could you tell if it there will be and impact on the development of the library as a whole ? 

Also, could you please tell us when Binance `sapi`, `fapi` and `dapi` endpoints will be unified ?

Thanks!

**Comment by frosty00** [comment]
@kroitor is working on the latter, hopefully in the coming weeks

**Comment by samgermain** [comment]
> sapi, fapi and dapi endpoints will be unified ?

These will never be unified / are already unified. If a method starts with `sapi`, `fapi` or `dapi`then it's an [implicit method](https://docs.ccxt.com/en/latest/manual.html#implicit-api), implicit methods are never unified. If the purpose of a triplet of these methods is the same but for spot/future/delivery though, then these methods will be used within a unified method, unless the purpose of those methods hasn't been written for a unified method yet

**Comment by ttodua** [comment]
maybe we missed to answer to first part of the question - the release of CCXT-PRO is for positive purposes and there is nothing worrying behind it - in opposite , that step is aiming toward more development.

**Comment by samgermain** [comment]
@kroitor I think the OP is wondering why CCXT PRO isn't just a free part of CCXT now? Why the wait?

**Comment by ttodua** [comment]
as both of you have answered, without further follow-ups, this question/issue can be closed.

**Comment by camposfyi** [comment]
Can you let me beta test it now? Or do you have a timeline when the pro version will be released as part of the free version?

**Comment by frosty00** [comment]
@camposfyi we already have people who've bought it testing it for the past 2 years, but we plan to do it within the next 4 weeks
