### ISSUE TITLE
How do I only watch the latest updates from watch_orders in CCXT PRO?

### ISSUE THREAD

**Issue by AlgoQ** [ccxt/ccxt#14198]
I'm not sure that when I change the limit parameter to 1 I receive all updates from watch_orders? Or is it possible that I miss some order updates? If so how do I resolve this, such that I only watch the latest order updates (not a list with the newest X orders)?

```python
orders = await connection.watch_orders(symbol, limit=1)
```

**Comment by carlosmiei** [comment]
Hello @AlgoQ,

There is an option to do precisely that returning only the latest updates, called `newUpdates`

Please check this out to see how `newUpdates` works and its usage:
https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual#newupdates-mode
