### ISSUE TITLE
ccex is 403

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1419]
- OS: linux
- Programming Language version: js
- CCXT version: 1.10.804
- Exchange: ccex
- Method: init

 new t.ccex({verbose: false}),

and it seems to be blocked by cloudflare and given 403 when using loadmarkets method.  #868, #1061, #77

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/blob/master/examples/py/bypass-cloudflare.py
- https://github.com/ccxt/ccxt/blob/master/examples/js/bypass-cloudflare.js

**Comment by jjhesk** [comment]
@kroitor lets add this.
```javascript
  async interceptCloudFlareRoboticCheck(c) {
        const exclude = ["bleutrade", "gatecoin", "gateio"];
        if (exclude.includes(c.id)) return;
        try {
            c.headers = await ex_wallet.scrapeCloudflareHttpHeaderCookie(c.urls.www);
        } catch (e) {
            log.bright.red("🛑 , error from getting the cloudflare verifications");
        }
    }
```

**Comment by kroitor** [comment]
@jjhesk will add that, thank you!
