### ISSUE TITLE
How to create an order with an Account Percentage in OKEX ? How to set the parameters ?

### ISSUE THREAD

**Issue by CatalaniCD** [ccxt/ccxt#14209]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

**Comment by carlosmiei** [comment]
Hello @CatalaniCD what do you mean by "account percentage" ?

**Comment by ttodua** [comment]
The issue got no follow-ups from OP after @ carlosmiei's request. I'm marking this topic as closed.
If you have any issues with CCXT, let us know.

To add a small note - if the intention was to "get account's amount of X coin and trade it's percentage", then the flow would be:
- use [`.fetchBalance()`](https://docs.ccxt.com/en/latest/manual.html#account-balance) and from its response, get the available amount of target coin
- calculate percentage per your needs and use [`.createOrder`](https://docs.ccxt.com/en/latest/manual.html#placing-orders)
