### ISSUE TITLE
Ability to get last http request in addition to last http response

### ISSUE THREAD

**Issue by gshpychka** [ccxt/ccxt#14203]
When debugging, the `last_json_response` proprety (in python) is very useful. Is it possible to access the last raw request the same way? if not, would it be easy to add this ability?

**Comment by carlosmiei** [comment]
Hello @gshpychka, currently we don't have such property but are considering adding it now following your suggestion

**Comment by gshpychka** [comment]
@frosty00 do you think this can be added?

**Comment by gshpychka** [comment]
@ttodua is this still on the table?

**Comment by ttodua** [comment]
@gshpychka you can see this PR which solve(s) this particular issue: https://github.com/ccxt/ccxt/pull/14809
if you want it very much, you might adopt those changes, because that exact PR is not merged (wont be) as different response structure will be implemented in future.

**Comment by gshpychka** [comment]
> @gshpychka you can see this PR which solve(s) this particular issue: https://github.com/ccxt/ccxt/pull/14809
> 
> if you want it very much, you might adopt those changes, because that exact PR is not merged (wont be) as different response structure will be implemented in future.

why not merge it before this different structure is implemented? It's been almost a year already, who knows when that will be.

**Comment by ttodua** [comment]
> > @gshpychka you can see this PR which solve(s) this particular issue: #14809
> > if you want it very much, you might adopt those changes, because that exact PR is not merged (wont be) as different response structure will be implemented in future.
> 
> why not merge it before this different structure is implemented? It's been almost a year already, who knows when that will be.

I can't say, maybe @carlosmiei can answer.

**Comment by carlosmiei** [comment]
@gshpychka Now you have access to

```
last_request_headers
last_request_body
last_request_url
```
