### ISSUE TITLE
Proposal of removing dynamic keys from type definition

### ISSUE THREAD

**Issue by susemeee** [ccxt/ccxt#14212]
In class Exchange from `ccxt.d.ts` there is a property that allows every key for the class.
https://github.com/ccxt/ccxt/blob/9634675a32cece7694e92e1d420966029f0208d0/ccxt.d.ts#L241

It might be present due to implicit APIs, however, because of this property, type checking became useless.

Since it is a type definition, I think removing it would be better for type checking perspective (and declaring type definition in user's code).

**Comment by samgermain** [comment]
> In class Exchange from `ccxt.d.ts` there is a property that allows every key for the class.
> 
> https://github.com/ccxt/ccxt/blob/9634675a32cece7694e92e1d420966029f0208d0/ccxt.d.ts#L241
> 
> It might be present due to implicit APIs, however, because of this property, type checking became useless.
> 
> Since it is a type definition, I think removing it would be better for type checking perspective (and declaring type definition in user's code).

Could you try removing and seeing if you get any errors/warnings? I just looked up what ` [key: string]: any; ` means, and I kind of get it, but not practically. I think we can probably remove it if there aren't any warnings/errors.

@kroitor @frosty00 What do you think?

**Comment by ttodua** [comment]
We are in process of migration into ESM, then the type definitions become fixed and better. We will announce it. Please subscribe to our telegram/discord announcements channel
