### ISSUE TITLE
okex raise an error in func:load_markets

### ISSUE THREAD

**Issue by ldkklj** [ccxt/ccxt#14219]
- OS:Linux
- Programming Language version:python3.8
- CCXT version:1.89.99

```
okex = ccxta.okex({
    'apiKey': 'yyyyyyyyyyyyyyyyyyy',
    'secret': 'ccccccccccccccccccc',
    'password': 'ddddddddddddd',
})
market = await exchange.load_markets()

```
okex GET https://www.okx.com/api/v5/asset/currencies
```
When load_market,raise this error . Only okex raise this erro;biance/mx/ftx all run this code well.

**Comment by carlosmiei** [comment]
Hello @ldkklj,
If you provide credentials to OKEX a private endpoint will be used to fetch currencies, one of the steps of loading the markets, so please make sure your credentials are correct. I've also tested on my side and worked fine with valid credentials.

Alternatively, you can load its markets without any credentials by doing:

```Python
okex = ccxt.okex({})
market = await exchange.load_markets()
```
