### ISSUE TITLE
[python] Binance withdraw error

### ISSUE THREAD

**Issue by HiddenFox** [ccxt/ccxt#1421]
- OS: Linux version 4.9.76-3.78.amzn1.x86_64 (mockbuild@gobi-build-60009) (gcc version 7.2.1 20170915 (Red Hat 7.2.1-2) (GCC) )
- Programming Language version: python 2.7
- CCXT version: ccxt==1.10.780
- Exchange: Binance
- Method: def withdraw(self, currency, amount, address, params={})

Got an error:
{'info': {u'msg': u'The label must not exceed 20 characters.', u'success': False}, 'id': None}

But the same script works well on another win7 PC.

The other APIs work well on the same Linux PC, such as create_order,  fetch_orders, fetch_balance...

**Comment by kroitor** [comment]
Fixed yesterday, in this PR: https://github.com/ccxt/ccxt/pull/1386
Please update your version to the most recent one. Thx!
