### ISSUE TITLE
fetchOrderBook exception with Binance when limiting bids/asks

### ISSUE THREAD

**Issue by cristoforo** [ccxt/ccxt#1422]
- OS: Windows 10
- Programming Language version: JS (Node 9.4.0)
- CCXT version: 1.10.738
- Exchange: Binance
- Method: fetchOrderBook 

When using `limit_bids`, `limit_asks` and `group` parameters in `fetchOrderBook`, Binance throws an exception (these parameters are not supported and not expected):

> (node:32196) UnhandledPromiseRejectionWarning: Error: binance GET  https://api.binance.com/api/v1/depth?symbol=ETHBTC&limit=100&limit_bids=5&limit_asks=5&group=1 400 Bad Request {"code":-1101,"msg":"**Too many parameters; expected '2' and received '5'.**"} (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)
>     at binance.defaultErrorHandler (E:\Personal\Crypto\cryptoarbitrage\node_modules\ccxt\js\base\Exchange.js:431:15)
>     at response.text.then.text (E:\Personal\Crypto\cryptoarbitrage\node_modules\ccxt\js\base\Exchange.js:447:25)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:160:7)

How to reproduce: 
Try the basic `fetchOrderBook` example at https://github.com/ccxt/ccxt/blob/master/examples/js/order-book-extra-level-depth-param.js with Binance and ETH/BTC

I think we should only pass the additional params to exchanges explicitly supporting them.

**Comment by kroitor** [comment]
Those additional params are bitfinex-only. 

Explained here:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods
- https://github.com/ccxt/ccxt/wiki/Manual#order-book--market-depth

The name of that parameter is currently not unified yet, so you will have to specify exchange-specific params if you want to limit the output \. We are working on standardizing this particular aspect.

As you can see from here: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#market-data-endpoints the correct extra parameter name is `limit`, however it affects the rate-limiter applied to you.

Let us know if it doesn't answer your question.
