### ISSUE TITLE
Bugs on FTX wrapper

### ISSUE THREAD

**Issue by KaitaoQiu** [ccxt/ccxt#14235]
when `unrealized pnl` is 0.0(from `info`, we can find the original unrealizedPnl), the ccxt ftx will transfer 0 to None.
![截图 2022-07-06 02-51-13](https://user-images.githubusercontent.com/85727393/177395777-6f78837a-483c-4ff9-a5b9-d66651145685.png)

**Comment by ttodua** [comment]
Thanks for report! I'll fix that.

**Comment by KaitaoQiu** [comment]
good job, love ccxt team

**Comment by filipegalo** [comment]
good job on the fast response
