### ISSUE TITLE
Gateio calculate_fee for futures not working correctly

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#14234]
- OS: linux
- Programming Language version: python
- CCXT version:1.90.22

```python
import ccxt
ct = ccxt.gateio({'options': {'defaultType': 'swap'}})
_ = ct.loadMarkets()

ct.calculate_fee('APE/USDT:USDT', 'maker', 'buy', 10, 100)
```

```
{'type': 'taker',
 'currency': 'APE',
 'rate': 7.5e-06,
 'cost': 7.500000000000001e-05}
```

Correct output would be something around

```
{'type': 'taker',
 'currency': 'USDT',
 'rate': 0.0,
 'cost': 0.0}
```

The above output  is wrong in 2 ways.
Futures, you'll never pay fee in "receiving" currency - always in settlement currency.
Also, the taker fee is not 7.5e-06 - but 0.

CCXT seems to be aware of "real" fees for swap mode on gate (see below) - but it seems like the `calculate_fee()` method is not getting that correctly (at least not the python version of it, i didn't test the js version).

https://github.com/ccxt/ccxt/blob/9e3ed8ffb320c77ab2c965b2a0561e9f073b8bfb/js/gate.js#L493-L496

Interestingly, the call to https://api.gateio.ws/api/v4/futures/usdt/contracts returns `"maker_fee_rate":"-0.00025","taker_fee_rate":"0.00075"` - which is somewhat aligned with their [documentation](https://www.gate.io/help/futures/delivery/22168/trading-and-settlement-fees#:~:text=If%20takers%20choose%20to%20pay,table%20of%20tiered%20fee%20rates.) - at least for taker fees - but ccxt seems to divide this by 100 - making the value way too low (as well as using the "taker" value for both taker and maker fees).

![image](https://user-images.githubusercontent.com/5024695/177391309-709bd521-fc0f-4b0d-ba42-6f89b186cb2a.png)

**Comment by ttodua** [comment]
Thanks for report.
1) right, when swap is linear (or for most contract types), settlement currency is mostly same as quote currency (USDT in that case).
2) those hardcoded fee-values (i.e...`'0.0005'`..) in ccxt, is not being used in `calculate_fee` as that method gets rates from market-object itself (`taker/maker`) property. 

I've submited a [PR](https://github.com/ccxt/ccxt/pull/14251) which fixes your above mentioned issue.
However, note - by default `calculate_fee` makes calculations based `type` and `takerOrMaker` argument. if `type` is set to `"market"` then it will end up as `taker` fee (independent of `takerOrMaker` argument, however, if `type` is set to any other order-type (not "market") then it uses `takerOrMaker` argument to decide whether it should return fee for `taker` or `maker` side.

**Comment by xmatthias** [comment]
@kroitor @ttodua unfortunately, the fix doesn't seem to fix this issue - but make it worse.

running the sample code from above with ccxt 2.1.21 breaks completely:

```
import ccxt
ct = ccxt.gateio({'options': {'defaultType': 'swap'}})
_ = ct.loadMarkets()

ct.calculate_fee('APE/USDT:USDT', 'maker', 'buy', 10, 100)
```

```
In [10]: ct.calculate_fee('APE/USDT:USDT', 'maker', 'buy', 10, 100)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In [10], line 1
----> 1 ct.calculate_fee('APE/USDT:USDT', 'maker', 'buy', 10, 100)

File ~/.pyenv/versions/3.10.7/envs/trade_3107_copy/lib/python3.10/site-packages/ccxt/base/exchange.py:2139, in Exchange.calculate_fee(self, symbol, type, side, amount, price, takerOrMaker, params)
   2135 if cost is not None:
   2136     cost = Precise.string_mul(cost, rate)
   2137 return {
   2138     'type': takerOrMaker,
-> 2139     'currency': market[key],
   2140     'rate': self.parse_number(rate),
   2141     'cost': self.parse_number(cost),
   2142 }
```

**Comment by ttodua** [comment]
@xmatthias thanks for input, we had several PRs for calculate_fee in last days and crashed, my bad. submitting the PR asap.

**Comment by xmatthias** [comment]
Many thanks - works now! :+1:
