### ISSUE TITLE
gateio fetch_my_trades fees "cost" has wrong type

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#14247]
- OS: linux
- Programming Language version: python
- CCXT version:1.90.27

```python
import ccxt
ct = ccxt.gateio({'options': {'defaultType': 'swap'}})
_ = ct.loadMarkets()

trades = ct.fetch_my_trades('APE/USDT:USDT')
# Obviously assumes that trades exist
print(trades[0])
```

```
[{'amount': 13.0,
  'cost': 47.7087,
  'datetime': '2022-06-17T20:54:37.108Z',
  'fee': None,
  'fees': [{'cost': '0.019560567', 'currency': None}],
  'id': '8799416',
  'info': {'contract': 'APE_USDT',
           'create_time': '1655499277.1085',
           'fee': '0.019560567',
           'id': '8799416',
           'order_id': '173423995062',
           'point_fee': '0',
           'price': '3.6699',
           'role': 'taker',
           'size': '13',
           'text': 'api'},
  'order': 'xxxxx',
  'price': 3.6699,
  'side': 'buy',
  'symbol': 'APE/USDT:USDT',
  'takerOrMaker': 'taker',
  'timestamp': 1655499277108,
  'type': None},
```

in the fees response (which is great that this was added!) `'fees': [{'cost': '0.019560567', 'currency': None}],`  - 'cost' is returned as string.

I suspect the problem comes form this area
https://github.com/ccxt/ccxt/blob/38dfe65b39e77b731dba05fe80a92d8902ddf128/js/gate.js#L2678-L2679
- which i suspect should be "safeNumber" - to return this as a number OR a string, depending on global settings.

I guess it's not properly converted "back" to number in `safe_trade` as it's already parsed / assigned.

What's odd here though is that (at least in the python version) - fees seem to be converted / parsed twice (`shouldParseFees` is True in this case - as `parseFee` is None) - but are then not used (`parseFees` is False).
https://github.com/ccxt/ccxt/blob/38dfe65b39e77b731dba05fe80a92d8902ddf128/python/ccxt/base/exchange.py#L2172-L2186

This is not really an issue - it may be something that can be optimized in the future.

**Comment by ttodua** [comment]
Thanks for report, I'll get to it asap.

**Comment by ttodua** [comment]
about parsing the fees twice, please open a new issue , so we could assign it independently from this original issue.

**Comment by xmatthias** [comment]
Unfortunately, the fix doesn't seem to fully fix the original problem.

Running the above now has a clearly different output (fee is populated, ...)

```
[{'amount': 13.0,
  'cost': 47.7087,
  'datetime': '2022-06-17T20:54:37.108Z',
  'fee': {'cost': 0.019560567, 'currency': 'USDT'},
  'fees': [{'cost': '0.019560567', 'currency': 'USDT'}],
  'id': '8799416',
  'info': {'contract': 'APE_USDT',
           'create_time': '1655499277.1085',
           'fee': '0.019560567',
           'id': '8799416',
           'order_id': '173423995062',
           'point_fee': '0',
           'price': '3.6699',
           'role': 'taker',
           'size': '13',
           'text': 'api'},
  'order': '173423995062',
  'price': 3.6699,
  'side': 'buy',
  'symbol': 'APE/USDT:USDT',
  'takerOrMaker': 'taker',
  'timestamp': 1655499277108,
  'type': None}]

```


The `fees` (multiple) part however is still pushed through as string (`  'fees': [{'cost': '0.019560567', 'currency': 'USDT'}],`) - which i guess is not desired.

**Comment by ttodua** [comment]
Yes I guess, my edits were not enough and it needed further updates in base-parser functions, but as I couldnt finish it on time yesterday, @kroitor merged the PR not to have a delay. Today I'll submit further edits. Gate.io has further inaccuracies in fees structure: from website vs from API, which need revision.

**Comment by ttodua** [comment]
closing this one too. let me know if still any issue.

**Comment by xmatthias** [comment]
Hi @ttodua,

Testing this today shows that it's still the same - 'cost' is returned as string (same code than above, but now with ccxt 4.3.24).

```
{'info': {'price': '4.6628',
  'text': 'api',
  'fee': '0.093256',
  'create_time': '1666709287.6734',
  'point_fee': '0',
  'trade_id': '10316560',
  'contract': 'APE_USDT',
  'role': 'taker',
  'order_id': '212718760364',
  'size': '40'},
 'id': '10316560',
 'timestamp': 1666709287673,
 'datetime': '2022-10-25T14:48:07.673Z',
 'symbol': 'APE/USDT:USDT',
 'order': '212718760364',
 'type': None,
 'side': 'buy',
 'takerOrMaker': 'taker',
 'price': 4.6628,
 'amount': 40.0,
 'cost': 186.512,
 'fee': None,
 'fees': [{'cost': '0.093256', 'currency': 'USDT'},
  {'cost': '0', 'currency': 'GatePoint'}]}
```

Now freqtrade has a workaround for this ccxt bug in place (for years now) - but i think from a consistency perspective, "cost" in the fee dictionary should be a number, not a string.

**Comment by ttodua** [comment]
ahhh.... thanks.  i've revived my old PR. I hope it might get merged at this stage.
