### ISSUE TITLE
Batch orders for Binance

### ISSUE THREAD

**Issue by Hadevmin** [ccxt/ccxt#14257]
Hi!

I can't submit a PR, I'm sorry... But are you planning to add batch orders functions in a future version for the binance exchange?
This is to see if I try to use implicit methods, or wait your release.
You can find the documentation on opening and cancelling multiples orders here:
https://binance-docs.github.io/apidocs/futures/en/#place-multiple-orders-trade
https://binance-docs.github.io/apidocs/futures/en/#cancel-multiple-orders-trade

Thanks you for your answer!

**Comment by ttodua** [comment]
We are planning to add and unify everything common across exchanges, but the workload is much and we have plans depending priorities. Batch orders are also in our radar, but I recommend that you don't us to and used implicit API in the meantime (as unification of batch orders might take months).
