### ISSUE TITLE
Pegged option in create order but says unsupported

### ISSUE THREAD

**Issue by CloudTrauma** [ccxt/ccxt#14250]
In the phemex ccxt file, it says the ordertype includes Pegged but when trying it out, says unsupported. Is this a bad copy and paste from another exchange or am i creating the order wrong?
What i did:
```
print(Short.create_order(symbol,'Pegged','buy',1))
```

**Comment by ttodua** [comment]
Actually, commened lines (as the code itself) might not be always up-to-date.
After checking their API docs, it seems `pegged` order is nowhere supported/mentioned : 

https://github.com/phemex/phemex-api-docs/blob/master/Public-Spot-API-en.md#common-constants
https://github.com/phemex/phemex-api-docs/blob/master/Public-Contract-API-en.md#common-constants

 so can't say if it was there in the past or is a mistake. anyway PR fix is submitted to remove that comment.

**Comment by kroitor** [comment]
Phemex seems to have dropped the support for the `Pegged` order type: https://github.com/phemex/phemex-api-docs/commit/1a1a19a70aae385f3d377855e4211b24eb2be8c6
