### ISSUE TITLE
safeTrade eventually parses fees again while then ignoring the outcome

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#14264]
- OS: linux
- Programming Language version: python
- CCXT version:1.90.27

Pulled from #14247 to be treated as separate issue as requested.

I guess it's not properly converted "back" to number in `safe_trade` as it's already parsed / assigned.

(at least in the python version) - fees seem to be converted / parsed twice (`shouldParseFees` is True in this case - as `parseFee` is None) - but are then not used (`parseFees` is False).
https://github.com/ccxt/ccxt/blob/38dfe65b39e77b731dba05fe80a92d8902ddf128/python/ccxt/base/exchange.py#L2172-L2186

This is not really an issue - it may however be something that can be optimized in the future.

**Comment by kroitor** [comment]
@xmatthias i'm trying to reproduce it on my side, but it looks like a proper number to me – can you plz paste your verbose output from this snippet? ↓

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.ftx({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
markets = exchange.load_markets()
exchange.verbose = True
trades = exchange.fetch_my_trades()
pprint(trades[0])
```

**Comment by xmatthias** [comment]
the "wrong type" error was fixed in #14247 (or rather #14259).
i seem to have been ... a bit quick opening the "new issue about the 2nd part" - leaving some parts in comments wrong for this issue..

While analyzing the gateio problem (it seemed correct to me, too), i wondered "why is the type not correct" ? - which is because the 'fees' output in this area is never used (only the one from the gateio class is used).
My initial expectation after looking at this quickly was that `safe_trade()` would convert units (for example cost) back to "parse_number" - even though parse_string was used in the exchange.

My point in this area was not a "wrong output" per se (if parsing is done by safe_trade - it seems perfectly fine) - but that if 'fees' is set already when entering `safe_trade` (which it is in gateio's case) - then it'll parse the fees again (populating `reducedFees`) - however `trade['fees'] = reducedFees ` is never reached as `parseFees` is false.
so even before the #14259 fix - ccxt internally had "cost" in the correct type internally for a short moment - but didn't use that part.

It's not necessarily a big problem - maybe it's even wanted/accepted for certain exchanges - and there as "fallback" for exchanges that don't do fee parsing themselves.

**Comment by xmatthias** [comment]
An example for this in the latest version (1.90.40) can be found below:

"fee" is now correct (as float) - but the content in "fees" is not.
The code in "safeTrade" suggests that the conversation happens - but the result of that conversation is never used - as "fees" is used from the incoming "gateio" specific code.

```
[{'amount': 13.0,
  'cost': 47.7087,
  'datetime': '2022-06-17T20:54:37.108Z',
  'fee': {'cost': 0.019560567, 'currency': 'USDT'},
  'fees': [{'cost': '0.019560567', 'currency': 'USDT'}],
  'id': '8799416',
  'info': {'contract': 'APE_USDT',
           'create_time': '1655499277.1085',
           'fee': '0.019560567',
           'id': '8799416',
           'order_id': '173423995062',
           'point_fee': '0',
           'price': '3.6699',
           'role': 'taker',
           'size': '13',
           'text': 'api'},
  'order': '173423995062',
  'price': 3.6699,
  'side': 'buy',
  'symbol': 'APE/USDT:USDT',
  'takerOrMaker': 'taker',
  'timestamp': 1655499277108,
  'type': None},
```

**Comment by ttodua** [comment]
@xmatthias I was strolling in old issues, and found this was fixed in the past, not in my PR.
