### ISSUE TITLE
How to solve rate limit issue

### ISSUE THREAD

**Issue by proskurin** [ccxt/ccxt#14262]
- OS: Mac OS
- Programming Language version: Python
- CCXT version: latest ccxt 

Hi, I am using ccxt for FTX trading to generate market orders.
```
exchange_client = ccxt.ftx(
            {'apiKey': cfg['API_KEY'], 'secret': cfg['SECRET_KEY'], 'enableRateLimit': True, 'headers': headers})
```

But after some time - I run into the issue
```
ccxt.base.errors.RateLimitExceeded: ftx {"success":false,"error":"Do not send more than 7 orders less than the market large order threshold per 200ms"}
```

What if I want to send many orders? How can I configure that?

**Comment by proskurin** [comment]
Do you have any ideas how to resolve that , @DoctorSlimm @kroitor ?

**Comment by DoctorSlimm** [comment]
@proskurin I'm taking a look into it, can you describe in more detail the code which you are running so that I can exactly reproduce your error?

**Comment by proskurin** [comment]
Yeah, it looks like a real problem here, cause this problem persists 
@DoctorSlimm 
` ftx {"success":false,"error":"Do not send more than 7 orders less than the market large order threshold per 200ms"}`

**Comment by DoctorSlimm** [comment]
@proskurin thank you, it is being investigated. There are a handful of possible causes for this, and it may even quite possibly be down to the exchange itself, and they are being looked into.

**Comment by frosty00** [comment]
ftx has been delisted
