### ISSUE TITLE
fetch_my_trades returns empty array

### ISSUE THREAD

**Issue by SergeySypalo** [ccxt/ccxt#14266]
Hey folks, I'm having an issue with getting my trades

- OS: Windows 11
- Programming Language version: Python 3.10.5
- CCXT version: 1.90.35

```
exchange.fetch_my_trades('BTC/USDT')
```

The command above returns an empty array from both Kraken and Huobi Global exchanges, while working just fine on Binance and FTX

**Comment by ttodua** [comment]
but when did you have last trades executed? you might need to use the `since` argument too. set it to i.e. last 3 days or whatever you need.
```
exchange.fetch_my_trades('BTC/USDT', exchange.milliseconds - 3 * 86400 * 1000 )
```

let me know if that helps

**Comment by SergeySypalo** [comment]
Yeah, I tried yesterday, but no luck, got the same empty array.
But, it looks like today after upgrading to 1.90.39 everything is working as expected.

**Comment by ttodua** [comment]
as soon as/if you notice issue  re-occuring, let me know. tnx

**Comment by SergeySypalo** [comment]
Noticed that there are no trades returned from Huobi Global exchange, checked Binance - working as expeted.
I'm using Python 3.11.1 and ccxt 2.7.8 on Windows 11

**Comment by ttodua** [comment]
please include verbose logs https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by SergeySypalo** [comment]
Looks like it was a glitch on Huobi, I made one trade manually, updated ccxt to 2.7.15 and now it appeared when fetching my trades via API, but in GUI on the website, I see previous trades too. Anyway, I needed only the last one.
