### ISSUE TITLE
How to get from websocket for market/limit orders. How much size/funds I received  total

### ISSUE THREAD

**Issue by DAigory** [ccxt/ccxt#14273]
- OS: arch
rust
kucoin api

For market sell case:
subscriptoin: spotMarket/tradeOrders
Market side sell:
{\"type\":\"message\",\"topic\":\"/spotMarket/tradeOrders\",\"userId\":\"62b14ee431a60900019892df\",\"channelType\":\"private\",\"subject\":\"orderChange\",\"data\":{\"symbol\":\"BTC-USDT\",\"orderType\":\"market\",\"side\":\"sell\",\"orderId\":\"62c826d736d11f0001cc504c\",\"type\":\"canceled\",\"orderTime\":1657284311545304778,\"size\":\"5\",\"filledSize\":\"2.26\",\"remainSize\":\"0\",\"status\":\"done\",\"ts\":1657284311545304778}}" 

market side buy:
"{\"type\":\"message\",\"topic\":\"/spotMarket/tradeOrders\",\"userId\":\"62b14ee431a60900019892df\",\"channelType\":\"private\",\"subject\":\"orderChange\",\"data\":{\"symbol\":\"BTC-USDT\",\"orderType\":\"market\",\"side\":\"buy\",\"orderId\":\"62c826d736d11f0001cc504t\",\"type\":\"canceled\",\"orderTime\":1657285110883695009,\"filledSize\":\"0.00046746\",\"remainFunds\":\"0\",\"funds\":\"10\",\"remainSize\":\"0\",\"status\":\"done\",\"ts\":1657285110883695009}}" 

I could guess from market buy:  filledSize is answer but it could be last match size
for market sell: I can't see price either funds I recieved;

I could accumulate all match events and calculate average price and size/funds for buy/sell  but 
1. there is no information about their total count 
2.  websocket messages receiving in unordered way and some match could be receive  after done status of last match and I still need to know count of matches 

The same problem with limits.
The resolution:
I could wait 'done' status of "spotMarket/tradeOrders" and then do rest api request of my order but...it is slowing down trading system and what the purpose of websocket subscription then if after every order 'done' I have to ask info about them?

**Comment by carlosmiei** [comment]
Hello @DAigory, sorry but I really can't understand the problem with ccxt here. Please read this: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by ttodua** [comment]
closing this issue.
