### ISSUE TITLE
Where can I find information about the data structure for staking ledger?

### ISSUE THREAD

**Issue by MalteToenjes** [ccxt/ccxt#14276]
Are there any infos about the ledger structure when I use fetchLedger for staking entries? Can't find anything about it in the docs. Is the structure the same across all exchanges or is there a separate structure for each exchange?

**Comment by samgermain** [comment]
Here's the [docs ledger section](https://docs.ccxt.com/en/latest/manual.html#ledger). It is the same across all exchanges, but depending on the exchange, the values of some fields may be `undefined`/`None`/`null`

**Comment by samgermain** [comment]
I'm going to close this issue. Feel free to reopen it if you have any more questions.
