### ISSUE TITLE
How to scrape last OHLC while accounting for timezones?

### ISSUE THREAD

**Issue by RoscoeTheDog** [ccxt/ccxt#14279]
I'm trying to fetch candlestick data from binance using an example snippit of code found [here](https://github.com/ccxt/ccxt/blob/master/examples/py/binance-fetch-ohlcv-to-csv.py). I've tried modifying it for my own needs since I don't need to write to CSV and I don't want to enter a constant for a string value each time. All I want to do is return the OHLCV start from the current `now() - start_date` so I can process the last x number of candlesticks to see which way the trend is moving in real-time. There seems to be an issue with the given start date right now in my code. It seems to return too many results than what is expected. For example, if I enter 24 hours on an hourly time-frame I am getting 32 results back. I don't think it's calculating the entered datetime correctly due to timezone issues but I'm not really too sure. The python datetime module is supposed to be easy but everytime I come back to it I end up getting confused lol. When stepping through the code in the debugger line by line the entered data looks correct. I don't know if when its being `parse8601()` if extra length is getting added due to timezone, and if so what is the solution to getting it to account for timezone differences from the local machine.

I noticed when debugging that using the `exchange.fetch_ohlcv()` method in ccxt only returns 1000 of the last results beginning from the _start time_. So if we have a start date that's length is beyond 1000 candlesticks, we have to accommodate that somehow. That is what I believe this line of code below is doing. It should be updating the `fetch_since` variable to be +1000 candlesticks length, but it's written inline weirdly and the split syntax is just not making sense to me.

Maybe someone can verify its validity.

```
fetch_since = (ohlcv[-1][0] + 1) if len(ohlcv) else (fetch_since + timedelta)
all_ohlcv = all_ohlcv + ohlcv
```

Here is my revisions and where I've been playing around debugging. 
```
    def retry_fetch_ohlcv(self, max_retries, symbol, timeframe, since, limit):
        num_retries = 0
        try:
            num_retries += 1
            ohlcv = self.exchange.fetch_ohlcv(symbol, timeframe, int(since), limit)
            print('Fetched', len(ohlcv), symbol, 'candles from', exchange.iso8601 (ohlcv[0][0]), 'to', exchange.iso8601 (ohlcv[-1][0]))
            return ohlcv
        except Exception as e:
            logger.error('could not fetch ohlcv from exchange', exc_info=e)
            if num_retries > max_retries:
                raise  # Exception('Failed to fetch', timeframe, symbol, 'OHLCV in', max_retries, 'attempts')


    def scrape_ohlcv(self, max_retries, symbol, timeframe, start_time, limit):
        # convert since from string to milliseconds integer if needed
        if isinstance(start_time, datetime.datetime):
            start_time = start_time.strftime('%Y-%m-%dT%H:%M:%S.%f%z')
        if isinstance(start_time, str):
            start_time = self.exchange.parse8601(start_time)
        timeframe_duration_in_seconds = self.exchange.parse_timeframe(timeframe)
        timeframe_duration_in_ms = timeframe_duration_in_seconds * 1000
        timedelta = limit * timeframe_duration_in_ms
        now = self.exchange.milliseconds()
        all_ohlcv = []
        seek_start = start_time

        while seek_start < now:
            ohlcv = self.retry_fetch_ohlcv(max_retries, symbol, timeframe, seek_start, limit)
            seek_start = (ohlcv[-1][0] + 1) if len(ohlcv) else (seek_start + timedelta)
            all_ohlcv = all_ohlcv + ohlcv
            if len(all_ohlcv):
                print(len(all_ohlcv), 'candles in total from', self.exchange.iso8601(all_ohlcv[0][0]), 'to',
                      self.exchange.iso8601(all_ohlcv[-1][0]))
            else:
                print(len(all_ohlcv), 'candles in total from', self.exchange.iso8601(seek_start))
        data = self.exchange.filter_by_since_limit(all_ohlcv, start_time, None, key=0)
        return data


# this is an async thread that will scrape candles periodically and set a global flag that changes trade-bot configurations.
def trend_watchdog(dca_strategy, symbol):
        num_hours = 24  # when set to 24, 32 results are returned
        timeframe = '1h'
        time_delta = datetime.datetime.now() - datetime.timedelta(hours=num_hours)
        candlestick_data = dca_strategy.scrape_ohlcv(3, symbol, timeframe, time_delta, 1000) # limit '1000' here just for testing. I want to modify this to accept unlimited length and the function append it all neatly together somehow.
```

**Comment by samgermain** [comment]
import json
import ccxt  # noqa: E402
from pprint import pprint

keys = json.load(open('../keys.local.json'))
exchange = ccxt.binance()

> I'm trying to fetch candlestick data from binance using an example snippit of code found here. 

Which snippet?

> I noticed when debugging that using the exchange.fetch_ohlcv() method in ccxt only returns 1000 of the last results beginning from the start time. 
 
Yeah, that's a restriction set by binance

> So if we have a start date that's length is beyond 1000 candlesticks, we have to accommodate that somehow. 

You'll need to make multiple calls

> That is what I believe this line of code below is doing. It should be updating the fetch_since variable to be +1000 candlesticks length, but it's written inline weirdly and the split syntax is just not making sense to me.
> Maybe someone can verify its validity.

> `fetch_since = (ohlcv[-1][0] + 1) if len(ohlcv) else (fetch_since + timedelta)`

The `if len(ohlcv)` is just checking if ohlcv has a length greater than 0

---

You have a lot of code, and It's kind of hard to tell what you're trying to do, and you also do have a program that I can just copy and paste and then run because I don't know what some of your variables are

Can you try to post your code in the format of a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), and post some example output that you want to get? 

Thanks
