### ISSUE TITLE
Bybit: fetchOrder() fetchOrders() UsdcSettled, future and inverse markets question

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#14275]
We notice that in last version there is no `fetchOrder` support for `UsdcSettled`, `future` and `inverse` markets in `bybit.js`.
Also by the logic in `bybit.js` code alternatives enters into `fetchOrders` were i.e. `future` and `inverse` markets actually supported.

`bybit.js` `fetchOrder` method code snippet:
```
if (isUsdcSettled || market['future'] || market['inverse']) {
	throw new NotSupported (this.id + ' fetchOrder() supports spot markets and linear non-USDC perpetual swap markets only');
} else {
	// only linear swap markets allow using all purpose
	// fetchOrders endpoint filtering by id
        const orders = await this.fetchOrders (symbol, undefined, undefined, params);
        const order = this.safeValue (orders, 0);
        if (order === undefined) {
            throw new OrderNotFound (this.id + ' fetchOrder() order ' + id + ' not found');
        }
        return order;
}
```

`bybit.js` `fetchOrders` method code snippet:
```
if (market['linear']) {
        method = isConditionalOrder ? 'privateGetPrivateLinearStopOrderList' : 'privateGetPrivateLinearOrderList';
} else if (market['future']) {
        method = isConditionalOrder ? 'privateGetFuturesPrivateStopOrderList' : 'privateGetFuturesPrivateOrderList';
} else {
        // inverse swap
        method = isConditionalOrder ? 'privateGetV2PrivateStopOrderList' : 'privateGetV2PrivateOrderList';
}
```

That is just mistake or this can be described by some logic that we don't see?
If that's all is correct then which method should we use instead of `fetchOrder` for `UsdcSettled`, `future` and `inverse` markets?

- OS: Debian (Docker)
- Programming Language version: NodeJS, JavaScript
- CCXT version: PRO 1.1.88

**Comment by carlosmiei** [comment]
Hello @wunderb1t,

Bybit has different APIs depending on the market type (spot, swap, usdc, etc). Our current definition of "fetchOrder" says that it should return the order associated with a specific id regardless of its state. For some markets Bybit does not support this, we have to choose between fetching open or closed orders. 

Our suggestion: if **fetchOrder** is not supported you could try replace it by `fetchOpenOrders` and/or `fetchClosedOrders`

**Comment by shyrik13** [comment]
Is there any possibility to resolve this on `ccxt` side in `fetchOrder` method (use different `fetchOrders` methods for different market types)?
Because that will be really handy to use only one `fetchOrder` method for different markets (like it is made on different exchanges instances).
Also I noticed, that i.e. for `inverse` markets there is `order id` in received response from exchange.

**Comment by wunderb1t** [comment]
> Is there any possibility to resolve this on `ccxt` side in `fetchOrder` method (use different `fetchOrders` methods for different market types)? Because that will be really handy to use only one `fetchOrder` method for different markets (like it is made on different exchanges instances). Also I've noticed that e.g. for `inverse` markets there is `order id` in received response from exchange if pass into `fetchOrders,` but there is very strange `price`, `cost`, `average` fields results.
> 
> OS: Debian (Docker) Programming Language version: NodeJS, JavaScript CCXT version: PRO 1.1.88

@carlosmiei there will be possibility in future that mentioned in this comment?

**Comment by Kinzowa** [comment]
> Hello @wunderb1t,
> 
> Bybit has different APIs depending on the market type (spot, swap, usdc, etc). Our current definition of "fetchOrder" says that it should return the order associated with a specific id regardless of its state. For some markets Bybit does not support this, we have to choose between fetching open or closed orders.
> 
> Our suggestion: if **fetchOrder** is not supported you could try replace it by `fetchOpenOrders` and/or `fetchClosedOrders`

Hi Carlos,

I'm facing a situation where an order in inverse market was cancelled and I'm unable to update my database because `fetchOrder` is not supported with COIN-margined perp, and `fetchOpenOrders` and `fetchClosedOrders` don't return this cancelled order. `fetchCanceledOrders` is not supported neither. Seems like we must extrapolate in this specific case.

**Comment by frosty00** [comment]
you can use `fetchOrders ({ settle: 'USDC' })`
