### ISSUE TITLE
Kucoin loadMarkets timeout

### ISSUE THREAD

**Issue by wannesdemaeght** [ccxt/ccxt#1427]
Verbose output:

```
kucoin GET https://api.kucoin.com/v1/market/open/symbols
Request:
 { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36' } undefined
(node:7464) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: kucoin GET https://api.kucoin.com/v1/market/open/symbols request timed out (10000 ms)
(node:7464) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

same url in chrome gives the correct response in about 1 second.
Any idea?

**Comment by kroitor** [comment]
Have you tried raising the timeout to a higher value?

**Comment by wannesdemaeght** [comment]
timeout is set at 10 seconds, should be plenty I think?

**Comment by kroitor** [comment]
@wannesdemaeght 10s is the default, and when I say raise it, I mean a value higher than the default ))

**Comment by wannesdemaeght** [comment]
Set it to 15 seconds, same error (well, stating 15000 ms seconds ofcourse).
I don't really see the point in setting it higher than that, my script polls every 5 seconds for balance and tickers.
A promise resolving after 30 seconds, could overwrite correct vars with depreciated data.

I'm just curious as to  why the exact same call in chrome gets resolved in sub 1 second?
Could it be a cloudflare issue of some sort maybe?

**Comment by kroitor** [comment]
> Could it be a cloudflare issue of some sort maybe?

Yes, it could. Have you tried bypassing it? (there are a couple of examples for that in the examples folder in the repo).
