### ISSUE TITLE
[coinbase] error handling question 

### ISSUE THREAD

**Issue by bonetjoshua** [ccxt/ccxt#14280]
- OS: Mac
- Programming Language version: Python
- CCXT version: Most recent

```
ticker = exchange.fetchTicker(f"{symbol}")
```

```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.pro.coinbase.com/products/WLUNA-USDT/ticker
...
 raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: coinbasepro Not allowed for delisted products
```

**Comment by carlosmiei** [comment]
Hello @bonetjoshua,

The error message is pretty self-explanatory, you can't get ticker info for delisted markets. 

If you want to know beforehand if the market is delisted or not you can always do something like this:

```Python

exchange = ccxt.coinbasepro({
    # 'apiKey': 'YOUR_API_KEY',
    # 'secret': 'YOUR_SECRET_KEY',
})

symbol = "WLUNA/USDT" # your symbol here

markets = await exchange.load_markets()
if markets[symbol]['active']:
    print("Product is active")
    # your logic here
else:
     print("Product delisted/inactive")
```

**Comment by bonetjoshua** [comment]
> Hello @bonetjoshua,
> 
> The error message is pretty self-explanatory, you can't get ticker info for delisted markets.
> 
> If you want to know beforehand if the market is delisted or not you can always do something like this:
> 
> ```python
> exchange = ccxt.coinbasepro({
>     # 'apiKey': 'YOUR_API_KEY',
>     # 'secret': 'YOUR_SECRET_KEY',
> })
> 
> symbol = "WLUNA/USDT" # your symbol here
> 
> markets = await exchange.load_markets()
> if markets[symbol]['active']:
>     print("Product is active")
>     # your logic here
> else:
>      print("Product delisted/inactive")
> ```

Nice, I will definitely apply this to my code, thank you ir
