### ISSUE TITLE
OKX futures order creation broken

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#14284]
- OS:
- Programming Language version: python
- CCXT version: '1.90.39'

``` python
import ccxt
exchange = ccxt.binance({'apiKey': '<yourApiKey>', 'secret': '<yoursecret>', 'options': {'defaultType': 'swap'}})
lm = ct.loadMarkets()
pair = 'SOL/USDT:USDT'
params = {
    'posSide': 'long',
    'tdMode': 'isolated'
}
ct.create_order(pair, 'limit', 'buy', 1.0, 20, params=params)
```

```
NotSupported                              Traceback (most recent call last)
/tmp/ipykernel_272472/1511064681.py in <module>
      4     'tdMode': 'isolated'
      5 }
----> 6 ct.create_order(pair, 'limit', 'buy', 1.0, 20, params=params)

~/devel/cryptos/ccxt/python/ccxt/okx.py in create_order(self, symbol, type, side, amount, price, params)
   1946             margin = self.safe_value(params, 'margin', False)
   1947         if margin is True and not market['margin']:
-> 1948             raise NotSupported(self.id + ' does not support margin trading for ' + symbol + 'market')
   1949         if spot:
   1950             if margin:

NotSupported: okx does not support margin trading for SOL/USDT:USDTmarket
```

Apart from the missing space in the exception (between "USDT" and "market") - the message is wrong (margin mode detection seems wrong at first glance as it depends on tdMode).

The above used to create orders just fine a few days ago (tested with ccxt==1.90.1) - but it seems broken now.

**edit** seems to have been introduced in #14246 ...

**Comment by carlosmiei** [comment]
Hello @xmatthias, thanks for the heads-up, I introduced indeed this bug while resolving others, will be fixed soon.

**Comment by xmatthias** [comment]
@carlosmiei No worries - happens :laughing: the link to the PR was not meant to point fingers, but to help identify the fix ;)

**Comment by carlosmiei** [comment]
@xmatthias Yeah I know no worries 😅
