### ISSUE TITLE
CCXT Pro Status?

### ISSUE THREAD

**Issue by pcurello** [ccxt/ccxt#14288]
What is the situation of CCXT Pro right now?

My license expired and I can't even find the website to renew it. 

I'm trying to install it on an ubuntu machine and I can't see the repository in GitHub anymore. How am I supposed to install it now?

Thanks.

**Comment by kroitor** [comment]
The CCXT Pro website is here: https://ccxt.pro
The plan is to merge it with CCXT in the coming few weeks and make it free and public.
Let us know if that does not answer your question.
