### ISSUE TITLE
Phemex BadSymbol ERROR, but symbol is certainly correct.

### ISSUE THREAD

**Issue by Dedados** [ccxt/ccxt#14303]
Hello, I am having the following issue in CCXTPRO using the `watch_my_trades` function. When using the symbol: `BTC/USD:USD` an error attributed to another symbol: `LUNAOLDUSD` is created. The symbol `BTC/USD:BTC` works well in the same code.

- OS: MacOS 12.0.1
- Programming Language version: Python 3.9.13
- CCXT version: 1.90.43
- CCXT pro version: 1.1.90

CODE:

```
import ccxtpro
import asyncio
from pprint import pprint



async def main_function():

	exchange_phemex = ccxtpro.phemex({
				'options': {
					'defaultType': 'swap'
					},
				'newUpdates': False,
				# 'timeout': 5000,
				'apiKey': 'redacted',
				'secret': 'redacted'
				})
			

	exchange_phemex.verbose = True
	pprint(await exchange_phemex.watch_my_trades(symbol='BTC/USD:USD'))


asyncio.run(main_function())
```

ERROR:

```
fetch Request: phemex GET https://api.phemex.com/exchange/public/cfg/v2/products RequestHeaders: {'User-Agent': 'python-requests/2.26.0', 'Accept-Encoding': 'gzip, deflate'} RequestBody: None

fetch Response: phemex GET https://api.phemex.com/exchange/public/cfg/v2/products 200 ResponseHeaders: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Mon, 11 Jul 2022 12:27:32 GMT', 'Server': 'nginx', 'x-phemex-request-tracing': '4874c43b-bd87-418f-941f-1eea00978fec', 'X-RateLimit-Remaining': '99', 'X-RateLimit-Capacity': '100', 'X-Content-Type-Options': 'nosniff, nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate, no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY, DENY', 'Referrer-Policy': 'no-referrer, no-referrer', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 


..... A lot more of the same content .....


":5243,"orderCostEv":0,"posCostEv":0,"positionMarginEv":0,"positionStatus":"Normal","riskLimitEv":250000000,"sellLeavesQty":0,"sellLeavesValueEv":0,"sellValueToCostEr":5153750,"side":"None","size":0,"symbol":"OPUSD","takerFeeRateEr":0,"term":1,"transactTimeNs":1657543885426247437,"unrealisedPnlEv":0,"updatedAtNs":0,"usedBalanceEv":0,"userID":637679,"valueEv":0},{"accountID":6376790002,"assignedPosBalanceEv":0,"avgEntryPriceEp":0,"bankruptCommEv":0,"bankruptPriceEp":0,"buyLeavesQty":0,"buyLeavesValueEv":0,"buyValueToCostEr":5146250,"createdAtNs":0,"crossSharedBalanceEv":3711278,"cumClosedPnlEv":0,"cumFundingFeeEv":0,"cumTransactFeeEv":0,"curTermRealisedPnlEv":0,"currency":"USD","dataVer":2,"deleveragePercentileEr":0,"displayLeverageEr":2000000000,"estimatedOrdLossEv":0,"execSeq":399104157,"freeCostEv":0,"freeQty":0,"initMarginReqEr":5000000,"lastFundingTime":1657543878370710625,"lastTermEndTime":0,"leverageEr":0,"liquidationPriceEp":0,"maintMarginReqEr":1000000,"makerFeeRateEr":0,"markPriceEp":49201,"orderCostEv":0,"posCostEv":0,"positionMarginEv":0,"positionStatus":"Normal","riskLimitEv":250000000,"sellLeavesQty":0,"sellLeavesValueEv":0,"sellValueToCostEr":5153750,"side":"None","size":0,"symbol":"u100ROSEUSD","takerFeeRateEr":0,"term":1,"transactTimeNs":1657543878375827018,"unrealisedPnlEv":0,"updatedAtNs":0,"usedBalanceEv":0,"userID":637679,"valueEv":0}]}
Exception in callback FastClient.receive_loop.<locals>.handler() at /opt/homebrew/lib/python3.9/site-packages/ccxtpro/base/fast_client.py:20
handle: <Handle FastClient.receive_loop.<locals>.handler() at /opt/homebrew/lib/python3.9/site-packages/ccxtpro/base/fast_client.py:20>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/homebrew/lib/python3.9/site-packages/ccxtpro/base/fast_client.py", line 25, in handler
    self.handle_message(message)
  File "/opt/homebrew/lib/python3.9/site-packages/ccxtpro/base/aiohttp_client.py", line 32, in handle_message
    self.handle_text_or_binary_message(message.data)
  File "/opt/homebrew/lib/python3.9/site-packages/ccxtpro/base/aiohttp_client.py", line 27, in handle_text_or_binary_message
    self.on_message_callback(self, decoded)
  File "/opt/homebrew/lib/python3.9/site-packages/ccxtpro/phemex.py", line 895, in handle_message
    self.handle_orders(client, orders)
  File "/opt/homebrew/lib/python3.9/site-packages/ccxtpro/phemex.py", line 646, in handle_orders
    self.handle_my_trades(client, trades)
  File "/opt/homebrew/lib/python3.9/site-packages/ccxtpro/phemex.py", line 506, in handle_my_trades
    market = self.market(symbol)
  File "/opt/homebrew/lib/python3.9/site-packages/ccxt/async_support/base/exchange.py", line 1465, in market
    raise BadSymbol(self.id + ' does not have market symbol ' + symbol)
ccxt.base.errors.BadSymbol: phemex does not have market symbol LUNAOLDUSD
```

**Comment by Dedados** [comment]
I am running the exact code I sent above. The puzzling thing is that it works perfectly for BTC/USD:BTC but not for BTC/USD:USD. (ie. works for BTC margined futures but not for USD margined). I'll investigate a bit more.

Thanks.

**Comment by kroitor** [comment]
@Dedados make sure your runtime versions of ccxt/ccxt pro are up to date:

```Python
import ccxt
import ccxtpro
import asyncio
from pprint import pprint

print('CCXT Version:', ccxt.__version__)
print('CCXT Pro Version:', ccxtpro.__version__)


async def main_function():

	exchange_phemex = ccxtpro.phemex({
				'options': {
					'defaultType': 'swap'
					},
				'newUpdates': False,
				# 'timeout': 5000,
				'apiKey': 'redacted',
				'secret': 'redacted'
				})
			

	exchange_phemex.verbose = True
	pprint(await exchange_phemex.watch_my_trades(symbol='BTC/USD:USD'))


asyncio.run(main_function())
```

**Comment by Dedados** [comment]
They are: 
```
CCXT Version: 1.90.43
CCXT Pro Version: 1.1.90
```
Thanks

**Comment by carlosmiei** [comment]
@Dedados Can you please post the entirety of the log you get by running the snippet above left by @kroitor ?

**Comment by Dedados** [comment]
> @Dedados Can you please post the entirety of the log you get by running the snippet above left by @kroitor ?

Running exactly the code sent by kroitor:

https://gist.github.com/Dedados/66d12048b4a34979c0b20d8adf6b1144

**Comment by carlosmiei** [comment]
@Dedados thanks, can you please show what's in line 27 of this file?
![image](https://user-images.githubusercontent.com/43336371/178310602-472422cd-1cd1-4549-b8ff-07e9f6ac806f.png)

**Comment by Dedados** [comment]
> @Dedados thanks, can you please show what's in line 27 of this file? ![image](https://user-images.githubusercontent.com/43336371/178310602-472422cd-1cd1-4549-b8ff-07e9f6ac806f.png)

As I mentioned it is exactly the code sent by Kroitor above

**Comment by Dedados** [comment]
It seems that the Accounts-orders-positions function is called successfully (https://github.com/phemex/phemex-api-docs/blob/master/Public-Contract-API-en.md#aopsub).

However after that the error occurs, which I cannot trace.

(I removed the gist link above for the sake of privacy)

**Comment by carlosmiei** [comment]
@Dedados yes the subscription is being made correctly, the problem is with some updates of "non-existent" markets due to delisting. We'll patch it soon

**Comment by Dedados** [comment]
> @Dedados ok I think I know what is happening, Phemex has a single stream for private info, meaning that we subscribe to "account updates" and in that stream will be broadcasted every update regardless of its market, the filtering for market X or Y is made by us on the client-side. You probably traded that luna market in the past and now it is delisted but phemex still broadcasts "old" updates at the beginning of the session but since it is inactive now will crash with the error you showed us.
> 
> We will try to come up with a solution, thank you for your detailed explanations!


I thought that may be the case, but why would it work with 'BTC/USD:BTC'? Can't remember trading luna as well.

Thanks for the time.

**Comment by carlosmiei** [comment]
> > @Dedados ok I think I know what is happening, Phemex has a single stream for private info, meaning that we subscribe to "account updates" and in that stream will be broadcasted every update regardless of its market, the filtering for market X or Y is made by us on the client-side. You probably traded that luna market in the past and now it is delisted but phemex still broadcasts "old" updates at the beginning of the session but since it is inactive now will crash with the error you showed us.
> > We will try to come up with a solution, thank you for your detailed explanations!
> 
> I thought that may be the case, but why would it work with 'BTC/USD:BTC'? Can't remember trading luna as well.
> 
> Thanks for the time.

It is a bit weird that you don't get that error when using the inverse contract, cause the subscription we send to the exchange is exactly the same

**Comment by Dedados** [comment]
Ok, so I got past this issue by creating a sub-account, which gets rid of the trading history, and (almost) everything works smoothly now.

I say almost as there was another error when there were no trades to show, as was the case with the freshly made sub-account. The fix may be trivial so I won't make another thread.


```
Exception in callback FastClient.receive_loop.<locals>.handler() at /opt/homebrew/lib/python3.9/site-packages/ccxtpro/base/fast_client.py:20
handle: <Handle FastClient.receive_loop.<locals>.handler() at /opt/homebrew/lib/python3.9/site-packages/ccxtpro/base/fast_client.py:20>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/homebrew/lib/python3.9/site-packages/ccxtpro/base/fast_client.py", line 25, in handler
    self.handle_message(message)
  File "/opt/homebrew/lib/python3.9/site-packages/ccxtpro/base/aiohttp_client.py", line 32, in handle_message
    self.handle_text_or_binary_message(message.data)
  File "/opt/homebrew/lib/python3.9/site-packages/ccxtpro/base/aiohttp_client.py", line 27, in handle_text_or_binary_message
    self.on_message_callback(self, decoded)
  File "/opt/homebrew/lib/python3.9/site-packages/ccxtpro/phemex.py", line 895, in handle_message
    self.handle_orders(client, orders)
  File "/opt/homebrew/lib/python3.9/site-packages/ccxtpro/phemex.py", line 666, in handle_orders
    messageHash = 'orders:' + type
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by carlosmiei** [comment]
Hello @Dedados Yes there is no need to open a new issue, both problems will be fixed very soon!
