### ISSUE TITLE
amount_to_lots TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by KamuelaFranco** [ccxt/ccxt#1430]
- OS: MacOS High Sierra 10.13.2 
- Programming Language version: Python 3.6.4
- CCXT version: 1.10.804
- Exchange: Binance
- Method: amount_to_lots

The line that causes this problem is:

`lot_sized_quantity = exchange.amount_to_lots(symbol='ETH/BTC', amount=raw_quantity)`

`raw_quantity` in this case is: `20.952858273950913`

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-1ed8d0675032> in <module>()
      8     price = float(client.get_ticker(symbol=symbol)['lastPrice'])
      9     raw_quantity = max_trade_size / price
---> 10     lot_sized_quantity = exchange.amount_to_lots(symbol='ETH/BTC', amount=raw_quantity)
     11     try:
     12         open_position(symbol=symbol, quantity=lot_sized_quantity, client=client, real_order=False)

~/Dropbox/Trading/.venv/lib/python3.6/site-packages/ccxt/base/exchange.py in amount_to_lots(self, symbol, amount)
    797 
    798     def amount_to_lots(self, symbol, amount):
--> 799         lot = self.markets[symbol]['lot']
    800         return self.amount_to_precision(symbol, math.floor(amount / lot) * lot)
    801 

TypeError: 'NoneType' object is not subscriptable

```

Thank you.

**Comment by kroitor** [comment]
You are required to call `.load_markets()` once, prior to performing any operations with them.
https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
Let us know if it doesn't help. Thx!

**Comment by KamuelaFranco** [comment]
This did help. Is it possible to make this more explicit? Also, doesn't
>  If you forget to load markets the ccxt library will do that automatically upon your first call to the unified API
mean it wasn't happening?

**Comment by kroitor** [comment]
@KamuelaFranco you haven't called any unified API method, so you haven't made a fist call to the unified API before actually accessing them. If you follow it literally, then you'll immediately notice, that it is explicit already. You just have to account for each word in that sentence )
