### ISSUE TITLE
HitBTC -> hitbtc $order $amount should be evenly divisible by lot unit size of 1000

### ISSUE THREAD

**Issue by darthf1** [ccxt/ccxt#1432]
Hi, im getting the following error when executing a limit sell order on HitBTC:

`$hitbtc->createLimitSellOrder('XVG/BTC', '210.49790575916', '0.00000955');`

`hitbtc $order $amount should be evenly divisible by lot unit size of 1000`

How should I interpret this? Which should be divisible by 1000, the total amount of the order? In this specific trade, the trade amount would be 0.002010255 BTC. What should my trade amount be for this trade to continue?

**Comment by kroitor** [comment]
When you submit an order you pass the amount and the price.

```
$hitbtc->createLimitSellOrder($symbol, $amount, $price);
```

In this specific trade the amount is 210.497905575916

```
$hitbtc->load_markets();
echo $hitbtc->markets[$symbol]['lot'] . "'\n";
```

The amount should be divisible by lot size.
Let us know if this does not answer your question.

**Comment by darthf1** [comment]
Thanks for your reply! Does this mean the minimal trade amount should be 1000, instead of 210? So I can only trade 1000, 2000, 3000 etc?

**Comment by kroitor** [comment]
@darthf1 is you version up to date? The error message has changed now. Can you update and try again? The lot size is 1 for XVG/BTC, so your amounts should be 239, 240, 241...

**Comment by darthf1** [comment]
I checked `composer.lock` and I am at `1.10.809`.

Got the same error with the same trade.
`hitbtc $order $amount should be evenly divisible by lot unit size of 1000`

**Comment by kroitor** [comment]
@darthf1 yes, sorry, I was looking at Binance instead of HitBTC. With HitBTC the lot size for XVG/BTC is indeed 1000, so, yes, 1000, 2000, 3000, etc.

**Comment by darthf1** [comment]
Ok thanks!
