### ISSUE TITLE
How to test methods of exchange?

### ISSUE THREAD

**Issue by copyNdpaste** [ccxt/ccxt#14335]
Should I mocking methods manually? or Are there  some way to testing methods calling?

For example, I want to test createLimitBuyOrder methods without spend money.

**Comment by ttodua** [comment]
if exchange supports, you can try to use "sandbox mode". Read more at: https://github.com/ccxt/ccxt/wiki/Manual#testnets-and-sandbox-environments.
The another way would be, to move out the money/asset from primary account to sub-account (if that exchange supports it) and test out the 'real' createLimitBuyOrder to see what response you'll get.

Let us know if you have a further question,

**Comment by copyNdpaste** [comment]
@ttodua oh second answer has risk of loss.. but I consider that way. I will research first way too
