### ISSUE TITLE
Livecoin: trades from API differs to trades from web version

### ISSUE THREAD

**Issue by nedark** [ccxt/ccxt#1433]
Hello. I tried to get all trades from BTC/USD market from livecoin and compare to the trades shown in web version and only some coincides... most of them are different. 
https://www.livecoin.net/es/trade/index?currencyPair=BTC%2FUSD
Moreover the sell/buy side is inverted O.O

Is this normal behaviour? Maybe web version is delayed compared to API version?

Regards

**Comment by kroitor** [comment]
Hi!

Sorry, but we need much more info from you to investigate.

With `node examples/js/cli livecoin fetchTrades BTC/USD` I'm seeing a consistent picture now:

![trades-livecoin](https://user-images.githubusercontent.com/1294454/35310233-7696d120-00c1-11e8-813c-ff21ab56044b.jpg)

So, maybe you're accessing them at different times (they change quite quickly), or this may be an inconsistency with them that only appears occasionally. In general the exchanges will throw all sorts of problems at you, so you have to be prepared. We've had inconsistencies from Livecoin earlier:
https://github.com/ccxt/ccxt/issues/467

So, for now having that much input info, we can't really help on the issue. We need you to log everything very thoroughly, like it's described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Closing it for now, if you don't mind. Let us know if you have a followup on this. Thx!
