### ISSUE TITLE
binance currency_to_precision won't work - code precision is None

### ISSUE THREAD

**Issue by kooomix** [ccxt/ccxt#14344]
Hi,

I'm using ccxt version 1.79.94.

It appears that recently the currency_to_precision stopped working properly.

Looking into it, I have found that the self.currencies[code]["precision"] entry is always None (even though I'm using a valid API key pair) so the currency_to_precision is not running the decimal_to_precision function.

Any idea what might be the cause of it?

Thanks.

**Comment by samgermain** [comment]
what exchange are you using?

**Comment by kooomix** [comment]
Binance

**Comment by samgermain** [comment]
I went through a few versions over the past 9 months, all the way back to `1.58.67` and it doesn't look like `self.currencies[code]["precision"]` was assigned on any of them

Can you be more specific about what method you are trying to use exactly?

**Comment by ttodua** [comment]
@kooomix please update to latest version and re-test. if that will solve issue or not, let us know

**Comment by kooomix** [comment]
just checked it with version '1.91.20' and still getting the same issue.

example code:

exchange = ccxt.binance({
            'apiKey': api_key,
            'secret': api_secret,
            'enableRateLimit':True,
            'options': {
                'newOrderRespType': 'FULL'
        }})
markets = exchange.load_markets()

exchange.currency_to_precision("USDT", float("361.4492880000001"))

result is: 361.4492880000001 while I would expect to get 361.449288

I am getting None for exchange.currencies["USDT"]["precision"].  This causes the currency_to_precision function to run self.number_to_string instead of self.decimal_to_precision

Thanks.

**Comment by ttodua** [comment]
@kooomix I've submited PR (see above reference) which will fix the issue, however, don't miss accidentally, you will need to do `exchange.load_markets()` at first (you are doing correctly now, so wait for PR to be merged)

**Comment by kooomix** [comment]
Cool, thanks.

**Comment by kroitor** [comment]
@kooomix you just have to be authenticated for it to work and have non-None precision, that is because Binance's fetchCurrencies endpoint requires authentication. Let us know if that does not help.

**Comment by kooomix** [comment]
As I mentioned in the post, I'm having this issue under a valid API key... Any specific parameters I should use when initializing the Binance exchange object to make it work?

**Comment by kroitor** [comment]
@kooomix as you can see from the verbose output and from the `currency['info']` Binance does not return a per-currency precision, they have a per-network precision instead:

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
# exchange.verbose = True  # uncomment for debug output
markets = exchange.load_markets()
currency = exchange.currencies['USDT']
pprint(currency)
```

So if you want to format a number to a per-network precision, you could do something like this:

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
# exchange.verbose = True  # uncomment for debug output
markets = exchange.load_markets()
currency = exchange.currencies['USDT']
networks_by_network = exchange.index_by(currency['networks'], 'network')
network = networks_by_network['TRX']
precision = exchange.precision_from_string(network['withdrawIntegerMultiple'])
amount = float("361.4492880000001")
formatted_amount = exchange.decimal_to_precision(amount, ccxt.ROUND, precision, exchange.precisionMode, exchange.paddingMode)
print(formatted_amount)
```

Also, please, note that we're going to refactor Binance's networks from a list to dictionary in the coming days.
Hope the above helps, let us know if not.

**Comment by ttodua** [comment]
For future readers, `currencies[code]["precision"]` is now available in binance (it just the highest precision among all network precisions)
