### ISSUE TITLE
Bybit - Stop loss order for open long position

### ISSUE THREAD

**Issue by fconsani** [ccxt/ccxt#14342]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Linux
- Programming Language version: Node.js v18.4.0
- CCXT version: '1.1.81'

Basically trying to set a SL on bybit, which worked for a selling position, by creating a buy stop order, with stopLoss params and reduce only. But it doesn't work for a long position.
Creating a SL for long result with the error : expect Rising, but trigger_price[195000000] \u003c= current[201470000]??
While i can create a conditional order with the same amount of my position and a price lower than the current one through the interface.

```
async function createStopOrder(symbol, type, side, amount, price, params) {
    exchange.verbose = true;
    let order = await exchange.createOrder(symbol,type, side, amount, price, params);
    return order;
}

async function main() {
 await exchange.loadMarkets();
 let createdSl = await createStopOrder("BTC/USDT:USDT","market","sell","0.044",undefined,{'stopLossPrice': "19500.00",  'reduceOnly': true});
}
```

```
stdout: fetch Request:
 bybit POST https://api-testnet.bybit.com/private/linear/stop-order/create 
RequestHeaders:
 { 'Content-Type': 'application/json', Referer: 'CCXT' } 
RequestBody:
 {"symbol":"BTCUSDT","side":"Sell","order_type":"Market","time_in_force":"GoodTillCancel","qty":0.044,"reduce_only":true,"close_on_trigger":false,"trigger_by":"LastPrice","stop_px":19500,"base_price":19499.5,"api_key":"hidden","recv_window":5000,"timestamp":"1657755224546","sign":"312c79639c37951fe2765b4ecb4f65048260062135d257551fbf38ddb762a296"} 


stdout: handleRestResponse:
 bybit POST https://api-testnet.bybit.com/private/linear/stop-order/create 200 OK 
ResponseHeaders:
 {
  'Cache-Control': 'max-age=0, no-cache, no-store',
  Connection: 'keep-alive',
  'Content-Length': '262',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Wed, 13 Jul 2022 23:33:44 GMT',
  Expires: 'Wed, 13 Jul 2022 23:33:44 GMT',
  Pragma: 'no-cache',
  Server: 'T-GATEWAY'
} 
ResponseBody:
 {"ret_code":130074,"ret_msg":"expect Rising, but trigger_price[195000000] \u003c= current[201470000]??LastPrice","ext_code":"","ext_info":"","result":null,"time_now":"1657755224.642873","rate_limit_status":99,"rate_limit_reset_ms":1657755224639,"rate_limit":100} 


stderr: /home/app/node_modules/ccxt/js/base/Exchange.js:2075
            throw new exact[string] (message);
                  ^

InvalidOrder: bybit {"ret_code":130074,"ret_msg":"expect Rising, but trigger_price[195000000] \u003c= current[201470000]??LastPrice","ext_code":"","ext_info":"","result":null,"time_now":"1657755224.642873","rate_limit_status":99,"rate_limit_reset_ms":1657755224639,"rate_limit":100}
    at bybit.throwExactlyMatchedException (/home/app/node_modules/ccxt/js/base/Exchange.js:2075:19)
    at bybit.handleErrors (/home/app/node_modules/ccxt/js/bybit.js:4977:18)
    at /home/app/node_modules/ccxt/js/base/Exchange.js:598:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (/home/app/node_modules/ccxt/js/base/functions/time.js:181:20)
    at async bybit.fetch2 (/home/app/node_modules/ccxt/js/base/Exchange.js:1802:16)
    at async bybit.request (/home/app/node_modules/ccxt/js/base/Exchange.js:1806:16)
    at async bybit.createContractOrder (/home/app/node_modules/ccxt/js/bybit.js:3007:26)
    at async bybit.createOrder (/home/app/node_modules/ccxt/js/bybit.js:2738:20)
    at async createStopOrder (/home/app/systemBybit.js:72:17) {
  constructor: [class InvalidOrder extends ExchangeError]
}

Node.js v18.4.0
```

**Comment by samgermain** [comment]
[CCXT is currently adding support for `stopLossPrice` and `takeProfitPrice`][1]

You can create an order with a stop loss and take profit tied to the order like

```
exchange.create_order(
    symbol='BTC/USDT:USDT',
    type='limit',
    side='sell',
    amount=0.01,
    price=21100,
    params={
        'leverage': 1,
        'stopLossPrice': 20950,
        'takeProfitPrice': 21950,
    },
)
```

---------------------------------------------

`createStopOrder` is for trigger orders that are not tied to an existing order and are independent. You can read more about [the difference between stop orders and stop loss orders on this issue](https://github.com/ccxt/ccxt/issues/12044)

  [1]: https://github.com/ccxt/ccxt/issues/13822

**Comment by fconsani** [comment]
Seems promising, though i am willing to create a stoploss binded to a position which is open, not an order.
The trigger order works for a short position, by creating a buy with params stopLossPrice, but not for a long position, as it shows the error above.

**Comment by fconsani** [comment]
Fixed this by sending base_price param when creating the order, as the value of current ticker price.

**Comment by flieks** [comment]
@fconsani thanks for the tip. Any solution for changing an existing stopLoss order (bound to an open position)

**Comment by samgermain** [comment]
> @fconsani thanks for the tip. Any solution for changing an existing stopLoss order (bound to an open position) ?

If the exchange has `editOrder` implemented, we may be able to add functionality to that method to edit the stopLoss; besides that, you'd have to cancel the order, and create a new order

**Comment by belqit** [comment]
```
var params = {
            symbol: "BTCUSDT",
            side: "Buy",
            take_profit: 30000,
            stop_loss: 12000
        }

ex.privatePostPrivateLinearPositionTradingStop(params)
```

**Comment by saiooo** [comment]
Guys, can you help me, I am getting the same issue now. My code:

```
const params={
        'leverage': 5,
        'base_price': "17160.0",
        'stopLossPrice': "16800.0"
    }
    


    const promise = bybitConnect().createMarketBuyOrder(symbol, amount, params) 
    const observable = from(promise);

    return observable;
```

**Comment by segundocarlos** [comment]
hi, i have a same problem,  
TakeProfit and StopLoss are not working in bybit when create order

**Comment by plouisn123** [comment]
> [CCXT is currently adding support for `stopLossPrice` and `takeProfitPrice`](https://github.com/ccxt/ccxt/issues/13822)
> 
> You can create an order with a stop loss and take profit tied to the order like
> 
> ```
> exchange.create_order(
>     symbol='BTC/USDT:USDT',
>     type='limit',
>     side='sell',
>     amount=0.01,
>     price=21100,
>     params={
>         'leverage': 1,
>         'stopLossPrice': 20950,
>         'takeProfitPrice': 21950,
>     },
> )
> ```
> 
> `createStopOrder` is for trigger orders that are not tied to an existing order and are independent. You can read more about [the difference between stop orders and stop loss orders on this issue](https://github.com/ccxt/ccxt/issues/12044)

Hello, this code doesn't works for me and I don't understand why:
bybit {"retCode":10001,"retMsg":"Request parameter error.","result":{},"retExtInfo":{},"time":1679173883972}

**Comment by Dan-krm** [comment]
@segundocarlos @plouisn123 You can view this pull request for examples of how to create different stop orders https://github.com/ccxt/ccxt/pull/17100

This should work for creating an order with a stopLoss and takeProfit attached on Bybit:
```
exchange.create_order(
    symbol='BTC/USDT:USDT',
    type='limit',
    side='sell',
    amount=0.01,
    price=21100,
    params={
        'stopLoss': 20950,
        'takeProfit': 21950,
    },
)
```

**Comment by plouisn123** [comment]
> @segundocarlos @plouisn123 You can view this pull request for examples of how to create different stop orders #17100
> 
> This should work for creating an order with a stopLoss and takeProfit attached on Bybit:
> 
> ```
> exchange.create_order(
>     symbol='BTC/USDT:USDT',
>     type='limit',
>     side='sell',
>     amount=0.01,
>     price=21100,
>     params={
>         'stopLoss': 20950,
>         'takeProfit': 21950,
>     },
> )
> ```

Thank you for the answer but I have the same error... So I use 3 orders for one trade.

**Comment by weslienlive** [comment]
@plouisn123 can you post an example?

**Comment by plouisn123** [comment]
> @plouisn123 can you post an example?

Hello, here an exemple but you have to close useless order manually because I create 3 differents orders

## Ordres
#Entry
orderPE = exchange.create_limit_order(symbol=symbol, side=Side, amount=quantity, price=PE)
#TP
orderTP = exchange.create_order(symbol=symbol, type='limit', side=close, amount=quantity, price=TPs[2])                    
#SL
if Side == 'Buy':
    orderSL = exchange.create_limit_order(symbol=symbol, side=close, amount=quantity, price=SL, params={'stopLossPrice': SL}) #Close long
else:
    orderSL = exchange.create_limit_buy_order(symbol=symbol, amount=quantity, price=SL, params = {'stopPrice': SL}) #Open long

If you want you can check on my page, I make an entire code with descriptions which explain how to copy trades from telegram to Bybit without manually actions to close trade:
https://github.com/plouisn123/Bybit_bot_telegram.git
