### ISSUE TITLE
MEXC Position None Bug?

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#14340]
Hey guys. I am trying to get info about my position on MEXC, but almost every important field is filled with None. Why so? Is this ccxt bug or MEXC doesnt give this info? Other exchanges (bybit, kucoin, okx, gateio) provide this info without Nones
![image](https://user-images.githubusercontent.com/44064808/178819006-0253b662-14e0-4024-a537-59aaf286aebb.png)

**Comment by samgermain** [comment]
You can value for `info` to get the response returned from MEXC. That response looks like

```JavaScript
{
        "positionId": 1394650,
        "symbol": "ETH_USDT",
        "positionType": 1,
        "openType": 1,
        "state": 1,
        "holdVol": 1,
        "frozenVol": 0,
        "closeVol": 0,
        "holdAvgPrice": 1217.3,
        "openAvgPrice": 1217.3,
        "closeAvgPrice": 0,
        "liquidatePrice": 1211.2,
        "oim": 0.1290338,
        "im": 0.1290338,
        "holdFee": 0,
        "realised": -0.0073,
        "leverage": 100,
        "createTime": 1609991676000,
        "updateTime": 1609991676000,
        "autoAddIm": false
}
```

I don't know what you mean by "important field", but it looks like we've filled what we are able to fill in. Sometimes we may be an api endpoint that is not the best choice, and another api endpoint might be a better option, but considering that this api endpoint is `api/v1/private/position/open_positions` I don't think that this is the case this time

**Comment by KindSpidey** [comment]
@samgermain yeah, info helps with dollars changing, but it still doesn't provide percentage of position. "Important" fields are pnl and roe (dollars profit and percentage profit). And there is no way to get percentage from MEXC,

**Comment by samgermain** [comment]
> @samgermain yeah, info helps with dollars changing, but it still doesn't provide percentage of position. "Important" fields are pnl and roe (dollars profit and percentage profit). And there is no way to get percentage from MEXC,

If it's not in `info` then we cannot get it. `info` is the raw response from the exchange

**Comment by KindSpidey** [comment]
Ok, got it
