### ISSUE TITLE
How to use sandbox mode on mexc3?

### ISSUE THREAD

**Issue by copyNdpaste** [ccxt/ccxt#14347]
I want to test some orders on test mode.

But `NotSupported: mexc3 does not have a sandbox URL` error raised.

How to set or add for testing on sandbox mode?

**Comment by samgermain** [comment]
I don't believe that a sandbox trading system exists on MEXC

**Comment by ttodua** [comment]
as answered by @samgermain , mexc doesnt have testnet, so there is nothing ccxt can do in such case. 
let us know if you will discover any issue in ccxt.

**Comment by oleh-popovych** [comment]
Hello

mexc has a testnet (https://futures.testnet.mexc.com/exchange)

@ttodua could you please suggest how I can use it?

**Comment by ttodua** [comment]
even though MEXC has https://futures.testnet.mexc.com/ I can't find any API access to it, neither in docs, neither their testnet UI dashboard has any API management page.
