### ISSUE TITLE
Add clientOrderId to HitBTC fetchClosedOrders

### ISSUE THREAD

**Issue by brucetus** [ccxt/ccxt#1434]
- OS: Debian 9
- Programming Language version: Node v8.9.4
- CCXT version: 10.81.1
- Exchange: HitBTC
- Method: fetchClosedOrders

I think we should add the id (the clientOrderId, not the id given by the exchange) to 
 the parameters for fetchClosedOrders so that I can get orders by my clientOrderId. The reason I want the id in fetchClosedOrders instead of fetchOrder and fetchOpenOrders is that the last 2 methods only work for open orders.

This is the original
<img width="982" alt="screen shot 2018-01-22 at 3 01 09 pm" src="https://user-images.githubusercontent.com/31704711/35249946-f49f7ca0-ff88-11e7-82d0-63bdd4a7170d.png">

And this is what I was thinking for the fix, but I'm not 100% sure if this is the right way to go about it
<img width="822" alt="screen shot 2018-01-22 at 3 33 40 pm" src="https://user-images.githubusercontent.com/31704711/35250117-dd37edf8-ff89-11e7-8bd4-710293c27348.png">

**Comment by kroitor** [comment]
> I think we should add the id (the clientOrderId, not the id given by the exchange) to
the parameters for fetchClosedOrders so that I can get orders by my clientOrderId. 

Nope, I don't think so )

> The reason I want the id in fetchClosedOrders instead of fetchOrder and fetchOpenOrders is that the last 2 methods only work for open orders.

It is already there, we wouldn't add it twice )) Have you seen `fetchOrder()` ? )

There are four methods available with HitBTCv2:
- fetchOrder ← you're looking for this one
- fetchOpenOrder
- fetchOpenOrders
- fetchClosedOrders

Let us know if it doesn't help ;)

**Comment by brucetus** [comment]
fetchOrder only gets open orders though, thats why I want the id option available in fetchClosedOrders. fetchClosedOrders in this case actually gets closed and open orders, so I think the whole naming scheme is confusing

**Comment by brucetus** [comment]
My bad. I don't know how I didn't see that fetchOrder and fetchClosedOrders both call privateGetHistoryOrder.. thanks
