### ISSUE TITLE
Bybit Inverse : fetch_position doesn't work

### ISSUE THREAD

**Issue by knao124** [ccxt/ccxt#14350]
The result of bybit `privateGetV2PrivatePositionList` and `fetch_positions` does not match.

## versions
- OS: Debian 11
- Programming Language version: python 3.8.12
- CCXT version: 1.90.74

## code to reproduce

this works:
```
import ccxt

bybit = ccxt.bybit({
    'apiKey': ...,
    'secret': ...
})
bybit.set_sandbox_mode(True)
symbol = 'BTCUSD'
ret = bybit.privateGetV2PrivatePositionList(dict(symbol=symbol))
ret['result']['size']  # => 1000
```

but, this doesn't work:
```
import ccxt

bybit = ccxt.bybit({
    'apiKey': ...,
    'secret': ...
})
bybit.set_sandbox_mode(True)
symbol = 'BTCUSD'
ret = bybit.fetch_positions(symbols=[symbol])
ret  # => []
```

## note
When I do print-debugging, I found that at the end of `fetch_positions` method, `self.filter_by_array(results, 'symbol', symbols, False)` is called with
symbols is `[BTCUSD]`, but the symbol field in the `results` is `BTCUSD:BTC`, so filter method returns empty list.

**Comment by carlosmiei** [comment]
Hello @knao124, thanks for letting us know, we found indeed an issue when providing exchange-specific ids but will be fixed soon!

**Comment by knao124** [comment]
@carlosmiei @kroitor thank you for the prompt fix! I confirmed it works :+1:
