### ISSUE TITLE
ccxt github wiki documentation wont render.

### ISSUE THREAD

**Issue by donjonson** [ccxt/ccxt#14357]

**Comment by samgermain** [comment]
This is a known issue. We need to reduce the size of the documentation. You can still view the documentation on https://docs.ccxt.com/en/latest/manual.html

**Comment by samgermain** [comment]
@carlosmiei Was this fixed? The page is rendering now for me

**Comment by frosty00** [comment]
> @carlosmiei Was this fixed? The page is rendering now for me

maybe github fixed it on their end

**Comment by donjonson** [comment]
This seems to have been resolved one way or another.  I am able to see the wiki on github now.
