### ISSUE TITLE
poloniex.com/tradingApi 422 not accessible from this location at the moment

### ISSUE THREAD

**Issue by MarkLuds** [ccxt/ccxt#1436]
- OS: LINUX
- Programming Language version: PHP 5.6
- CCXT version: not sure
- Exchange: poloniex
- Method: create_order

Hi, im getting this error message:
poloniex POST https://poloniex.com/tradingApi 422 not accessible from this location at the moment

the whole output is (took out my key and sign):
Request: Array ( [0] => GET [1] => https://poloniex.com/public?command=returnTicker [2] => Array ( ) [3] => ) Request: Array ( [0] => POST [1] => https://poloniex.com/tradingApi [2] => Array ( [0] => Content-Type: application/x-www-form-urlencoded [1] => Key: **** [2] => Sign: **** ) [3] => command=sell¤cyPair=USDT_BTC&rate=10207.00000000&amount=0.0001&nonce=1516666018745 ) poloniex POST https://poloniex.com/tradingApi 422 not accessible from this location at the moment

this part looks strange? "command=sell¤cyPair=USDT_BTC"

maybe it is linked to this issue:
https://github.com/ccxt/ccxt/issues/1340

but the code works fine for binance and kraken

thanks very much,

Mark

```
$exchange = 'poloniex';
$a = '\ccxt\\';
        $class = $a.$exchange; 
        $apis[$exchange] = new $class (array (
            'verbose' => true,
            'apiKey' => $keys[$x]['api_key'],
            'secret' => $keys[$x]['api_secret']
        ));
         $res = $apis[$exchange]->create_order('BTC/USDT', 'limit', 'sell', 0.001, 10000, array ());
```

**Comment by kroitor** [comment]
Hi, can you please report your version of ccxt?

**Comment by MarkLuds** [comment]
Hi, this I am guessing. From changelog:

# Сhangelog

## Version 1.10.1 2017-11-06

Thanks,
Mark

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by kroitor** [comment]
The changelog is outdated, can you verify your actual installed version? How did you install it?

**Comment by MarkLuds** [comment]
hi, sorry, i thought i'd replied to this. It was installed via composer so im not completely sure how to find the version? I installed it about a month ago if that helps. thanks

**Comment by kroitor** [comment]
@MarkLuds hi, which command did you use exactly to install it with Composer?

**Comment by MarkLuds** [comment]
hi, sorry, i actually got the people on the server to install it for me using composer i think. is there another way to check the version? or maybe there is something within the code that i can check that will suggest the version? Sorry for not being more helpful.

**Comment by kroitor** [comment]
Sorry for such a long wait... in general we can't really help setting it up, you would probably need to ask the same people who installed it for you, to upgrade it. In general a 422 is temporary and can be easily handled, as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#error-handling. Let us know if you still have issues with this. Closing it for now if you don't mind. Feel free to reopen it if needed or just ask questions if any...
