### ISSUE TITLE
leverage = 0 should be allowed

### ISSUE THREAD

**Issue by jackRoark** [ccxt/ccxt#14361]
Phemex allows sending `leverage = 0` to switch the symbol's margin from _isolated_ to _cross_, however the code that validates the value for leverage in the function `set_leverage` raises an error if a leverage < 1 is passed in:

https://github.com/ccxt/ccxt/blob/294e13d16ac1a7ecf29ab2c29dab014f1b4af391/python/ccxt/phemex.py#L3207

above should be replaced with:

`   if (leverage < 0) or (leverage > 100):`

PS: amazing job you guys have done with this project!

**Comment by ttodua** [comment]
As I see, you want to achieve different goal, that the intent of the unified set_leverage. What you are trying, is already implemented and can be achieved with another unified method `exch.set_margin_mode('cross')`. Let me know if you will have any issues further.

**Comment by jackRoark** [comment]
Oh, wow, this function was added on 1.82.5 and I was still on 1.80.67. Sorry about that.

Thank you so much!
