### ISSUE TITLE
What kind of AMM, orderbook strategies are exist based on ccxt?

### ISSUE THREAD

**Issue by copyNdpaste** [ccxt/ccxt#14369]
I want to replace AMM bot on CEX to AMM that I create.

I thought implementing strategy that made myself is not close to good strategy.

Could you let me know what kind of AMM, orderbook strategies that can be used on CEX?

**Comment by ttodua** [comment]
I don't remind any publicly shared ready-made AMM systems based on CCXT, but you might try to search thoroughly across internet or github. Basically, you need to search a generic/descriptionary approaches to good AMM strategies, and use CCXT (you need to have at least basic programming skills, if not advanced) to turn the conceptual logic into codes/systems. 
I'll leave the topic open for further answers
