### ISSUE TITLE
lbank fetchDepositAddress() is not supported yet

### ISSUE THREAD

**Issue by hosseinab** [ccxt/ccxt#14377]
OS: Windows 11
Programming Language version: PYTHON 3.10.5
CCXT version: "ccxt/ccxt": "^1.90",
Exchange: lbank
Method: fetch_deposit_address()

hi
I am getting this error
    raise NotSupported(self.id + ' fetchDepositAddress() is not supported yet')
ccxt.base.errors.NotSupported: lbank fetchDepositAddress() is not supported yet

But there is this function in the document
https://www.lbank.info/en-US/docs/index.html#get-deposit-address
please check this link

**Comment by sc0Vu** [comment]
Hi,

Have you try the v2 version (lbank2) exchange? There is `fetchDepositAddress()`.

**Comment by hosseinab** [comment]
@sc0Vu 
Yes I tried this too

**Comment by sc0Vu** [comment]
@hosseinab did you get any error?

**Comment by hosseinab** [comment]
@sc0Vu 
raise NotSupported(self.id + ' fetchDepositAddress() is not supported yet')
ccxt.base.errors.NotSupported: lbank fetchDepositAddress() is not supported yet

**Comment by sc0Vu** [comment]
@hosseinab lbank2 works for me, did it work? BTW, we're going to remove v1, pls use v2 instead!
