### ISSUE TITLE
fetch_tickers returns invalid data from hitbtc exchange

### ISSUE THREAD

**Issue by hosseinab** [ccxt/ccxt#14371]
OS: Windows 11
    Programming Language version: PYTHON 3.10.5
    CCXT version: "ccxt/ccxt": "^1.90",
    Exchange: hitbtc
    Method: fetch_tickers()

Problem

My problem is in displaying the currencies that do not exist in the hitbtc exchange
      connection = ccxt.hitbtc({
                'enableRateLimit': True,
                'apiKey': api_key,
                'secret': api_secret,
                'options': {
                    'adjustForTimeDifference': True,
                     'verbose': True,
                    'defaultType': 'spot',
                },
      })
     markets = connection.load_markets()
     currencies = connection.fetch_tickers()
     print(currencies)

I get the following data back:

'DOGE/USDT': {'symbol': 'DOGE/USDT', 'timestamp': 1657899521000, 'datetime': '2022-07-15T15:38:41.000Z', 'high': 0.0155, 'low': 0.015, 'bid': 0.01519081, 'bidVolume': None, 'ask': 0.01537312, 'askVolume': None, 'vwap': 0.015167330162337662, 'open': 0.01503535, 'close': 0.01519081, 'last': 0.01519081, 'previousClose': None, 'change': 0.00015546, 'percentage': 1.0339632931724236, 'average': 0.01511308, 'baseVolume': 40040.0, 'quoteVolume': 607.2998997, 'info': {

dogcoin is not exist in the hitbtc

**Comment by carlosmiei** [comment]
Hello @hosseinab,

What makes you think that does not exist?  
I can see it there in many markets, for example https://hitbtc.com/doge-to-usdt

**Comment by hosseinab** [comment]
this url redirect to https://hitbtc.com/btc-to-usdt
please check it
and Also the price of Dogecoin is 6 cents. This price that returns is wrong

**Comment by ttodua** [comment]
@hosseinab at first, please use `hitbtc3` instead of `hitbtc`.

**Comment by hosseinab** [comment]
@ttodua 
thanks for this Response
hitbtc3  has the same problem

**Comment by pier0074** [comment]
@hosseinab, both hitbtc and hitbtc3 work perfectly fine, even for DOGE/USDT.

```
		$hitbtc = new ccxt\hitbtc();
		$hitbtc->load_markets();
		print_r( $hitbtc->fetch_ticker( 'DOGE/USDT' )['info'] );

		$hitbtc3 = new ccxt\hitbtc();
		$hitbtc3->load_markets();
		print_r( $hitbtc3->fetch_ticker( 'DOGE/USDT' )['info'] );
```

Results are the same:
```
Array
(
    [symbol] => DOGEUSD
    [ask] => 0.01741477
    [bid] => 0.01638828
    [last] => 0.01629138
    [low] => 0.01552218
    [high] => 0.01839950
    [open] => 0.01639999
    [volume] => 132240
    [volumeQuote] => 2222.05816790
    [timestamp] => 2022-08-21T13:45:38.447Z
)
Array
(
    [symbol] => DOGEUSD
    [ask] => 0.01741475
    [bid] => 0.01638828
    [last] => 0.01629138
    [low] => 0.01552218
    [high] => 0.01839950
    [open] => 0.01639999
    [volume] => 132240
    [volumeQuote] => 2222.05816790
    [timestamp] => 2022-08-21T13:45:39.850Z
)
```

And results match the current ticker on the exchange (see bid and ask) from https://hitbtc.com/doge-to-usdt (that also work perfectly fine with no redirection) :
<img width="590" alt="image" src="https://user-images.githubusercontent.com/53877621/185794134-96fdb350-9a6f-461c-937f-c9dacaf16ed6.png">

The problem comes from hitbtc pricing of DOGE in the exchange itself. see #14726 .
Be careful if you want to trade this asset on hitbtc as you cannot withdraw it from the exchange at the moment, see [system monitor](https://hitbtc.com/system-monitor).

**Comment by ttodua** [comment]
@pier0074 thanks for your involvement in the topic ! You might be right, we will check that.
@hosseinab let us know your replies, as there seems to be no issue in CCXT. however , if you think there is issue still, let us know
