### ISSUE TITLE
Bybit - Conditional Orders with different stop loss configurations

### ISSUE THREAD

**Issue by Astraioss** [ccxt/ccxt#14381]
1- With Bybit you can only add a trailing stop loss after the original limit order has been filled and it is active. So I was wondering how this can be doing using ccxt. I guess it is through the edit order functionality
`async editOrder (id, symbol, type, side, amount = undefined, price = undefined, params = {})`
but since I am just in the testing phase I didn't really want to have a live order to test this out on so any help with that would be appreciated.

2- If the above is not possible I'd like to implement a staggered/multiple TP/SL configuration either side of the conditional order buy/sell order, similiar to how it would look on a DCA bot for example. How can I go about setting multiple individual TP/SLs that would reduce the position by X percent on each interval.

Current conditional order code:
```......
//Conditional Limit Order with standard TP/SL Config
    if (chosenSide = "buy") {
        var basePrice = limitPrice + 1
    } else if (chosenSide = "sell"){
        var basePrice = limitPrice - 1
    }
     console.log(basePrice)
    const symbol = 'BTC/USDT:USDT'
    const side = chosenSide // 'sell'
    const price = limitPrice // Order Price
    const type = 'limit'
    const amount = size // Order Quantity
    const params = {
        'timeInForce': 'GTC',
        'leverage': lev,
        'take_profit': TP,
        'stop_loss': SL,
        //'trailing_stop': '0.5',
        'stop_px' : limitPrice, //Trigger Price
        'base_price' : basePrice/10, // Trigger price compared to this. baseprice > stoppx = long and vice versa
        'trigger_by': 'LastPrice',
    }
.....
const order = await exchange.createOrder(symbol, type, side, amount, price, params)
```

Just to add to that, I also am not sure about the leverage param, it doesn't seem to be translating to my order

**Comment by ttodua** [comment]
late reply, but for readers, yes, that's right, after a position is opened, you can submit a trailing order for that open position. View the doc: https://docs.ccxt.com/#/README?id=trailing-orders
however, that exchange should have unified Trailing Stop functionality (you can also check [`features`](https://github.com/ccxt/ccxt/pull/23629) PR which is pending)
let us know if you have any issues
