### ISSUE TITLE
Python Bybit createOrder  type='market' returns  'status': 'open'

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#14401]
bybit spot market module ready to use?
Create a "market" order returns an order `'status': 'open'`. Is it correct behavior?

- OS: windows 11
- Programming Language version: python 3.10.4
- CCXT version: '1.90.88'

`orderExchange = await self.exchange.createOrder(symbol=symbol, type='market', side='buy', amount=1.05, price=3.9679)`

`{'info': {'accountId': '5702327', 'symbol': 'NEARUSDT', 'symbolName': 'NEARUSDT', 'orderLinkId': '1658166721155481', 'orderId': '1203184094979133952', 'transactTime': '1658166721161', 'price': '0', 'origQty': '1.05', 'executedQty': '0', 'status': 'NEW', 'timeInForce': 'GTC', 'type': 'MARKET', 'side': 'BUY'}, 'id': '1203184094979133952', 'clientOrderId': '1658166721155481', 'timestamp': 1658166721161.0, 'datetime': None, 'lastTradeTimestamp': None, 'symbol': 'NEAR/USDT', 'type': 'market', 'timeInForce': 'GTC', 'postOnly': False, 'side': 'buy', 'price': None, 'stopPrice': None, 'amount': 1.05, 'cost': None, 'average': None, 'filled': 0.0, 'remaining': 1.05, 'status': 'open', 'fee': None, 'trades': [], 'fees': []}`

**Comment by carlosmiei** [comment]
@YuriyTigiev This is fixed now.
