### ISSUE TITLE
FTX: TWAP Order

### ISSUE THREAD

**Issue by 300Gram** [ccxt/ccxt#14402]
I realise FTX has recently introduced a new way to execute order. 

I wonder if the current CCXT version is able to post the TWAP order to FTX. 

I tried searching for TWAP related topic in the ccxt github, but no luck. So i decided to ask here if it's possible to create a twap order using the current CCXT params.

**Comment by sc0Vu** [comment]
Thanks, we'll add TWAP api soon.
