### ISSUE TITLE
DYDX: New exchange

### ISSUE THREAD

**Issue by jfitz001** [ccxt/ccxt#14404]
Could you build out the connection to this exchange?

https://dydx.exchange/

Thanks,
Jamie

**Comment by sc0Vu** [comment]
Hi @jfitz001,

We're working on the dYdX exchange, still work in progress.

**Comment by jfitz001** [comment]
Hi @sc0Vu,
Glad to hear it! Do you have any plans for other DEX platforms?

**Comment by kroitor** [comment]
> Do you have any plans for other DEX platforms?

Yes, we already support IDEX, Waves.Exchange, ByteTrade, and we will add more DEXes as soon as we can.

Duplicates: 

- https://github.com/ccxt/ccxt/issues/9272
- https://github.com/ccxt/ccxt/pull/11643 (you can help test this DYDX PR)

**Comment by nomad5am** [comment]
Any news? The time is perfect to migrate to a DEX... And DYDX is amazing.
I understand the API Auth is different from CEXs - but besides that it shouldn't be much. 
 @ttodua  contact me on telegram id: @nomad5am I can help out!
