### ISSUE TITLE
market limits variable 'None'

### ISSUE THREAD

**Issue by bonetjoshua** [ccxt/ccxt#14411]
- CCXT version: 1.90.94
Inside the loadMarkets() function, the limits variable is none for price and amount for several exchanges such as CoinbasePro, FTX, Binance, Gemini, etc

```
markets = exchange.loadMarkets()
markets['PAX-USD']
```

```
<img width="1010" alt="Screen Shot 2022-07-19 at 10 11 43 AM" src="https://user-images.githubusercontent.com/51464032/179799548-6ed9a63d-cbfc-4b00-a35f-9c5ff00a2e7e.png">
```

**Comment by carlosmiei** [comment]
Hello @bonetjoshua.
CCXT is a middleware between traders and exchanges so we don't control the information provided by exchanges, if they don't provide it we cannot unifiy it.

 Did you find some disparity between the unified response and the information available in the API?

**Comment by bonetjoshua** [comment]
Good morning @carlosmiei , I do recall that CoinbasePro's API has a new variable for limit orders called min_max_funds:
![image](https://user-images.githubusercontent.com/51464032/180024230-6e96ec1d-325f-4052-92c6-69558b79dd6f.png)

For Binance's API, it shows min_price and max_price:
![image](https://user-images.githubusercontent.com/51464032/180025074-1fd7d7ad-de55-49c2-a085-1589c6850701.png)

For Gemini's API, it shows as minimum order size:
![image](https://user-images.githubusercontent.com/51464032/180026443-e11c8011-528a-44c5-8cb5-a23df7c8b8e0.png)

For Kraken's api it's called ordermin:
<img width="338" alt="Screen Shot 2022-07-20 at 9 50 12 AM" src="https://user-images.githubusercontent.com/51464032/180027136-2f226b10-61ad-4379-9d52-1a0bd5967315.png">

Let me know if this works, it does look like that some variables have been removed recently from exchanges and some have been renamed.

**Comment by ttodua** [comment]
we are in the process of filling up the missing `.limits.amount.min` & `.limits.cost.min` fields for markets. 
Please open one issue per exchange, if you feel some of them has a bug or missing data (the data that is present in API but not being set in unified ccxt fields).
