### ISSUE TITLE
amount_to_string broken

### ISSUE THREAD

**Issue by basnijholt** [ccxt/ccxt#1441]
```python
binance.amount_to_string('BNB/BTC', 1.73)
```
```
Out [19]: '1.72'
```

It would be great if `create_order` would accept a string from the start such that I won't run into such problems.

On a lower level this is because of `truncate_to_string`:
```
truncate_to_string(1.73, 2)
```
```
Out [25]: '1.72'
```

EDIT:
My PR https://github.com/ccxt/ccxt/pull/1442 fixes this issue.

**Comment by glassoff** [comment]
After this fix we have next problem:
truncate_to_string(0.25466498, 8)
returns '0.254665'

I think that '%f' allows only 6 digits after point, if I change to '%.20f', result of truncate_to_string() is 0.25466497

**Comment by kroitor** [comment]
@glassoff this is being reworked right now, here:
- https://github.com/ccxt/ccxt/pull/1635
- https://github.com/ccxt/ccxt/pull/2121
- https://github.com/ccxt/ccxt/pull/2171
- https://github.com/ccxt/ccxt/issues/522
- https://github.com/ccxt/ccxt/issues/1483

Will be updated very soon.
