### ISSUE TITLE
Edit stop-loss/take-profit orders for an open position

### ISSUE THREAD

**Issue by sirrisingeagle** [ccxt/ccxt#14423]
Hello
How can I edit my stop loss and take profit for an open position using ccxt python? I couldn't find any solution on internet

**Comment by ttodua** [comment]
The same question was asked before [here](https://github.com/ccxt/ccxt/issues/10073), please refer to this and let us know if that doesn't help.

**Comment by sirrisingeagle** [comment]
Thanks But here is the problem. I am creating a limit order with sl and tp.
bybit.create_order(symbol='BTCUSDT', type='Limit', side='Buy', amount=0.001, price=23000, params={'stop_loss': 22700, 'take_profit': 23300})
After my order filled, I can't get my sl and order id. Therefore it's can't be edited.

**Comment by ttodua** [comment]
Ah, now you have provided the details which was better to be in original post, so I would have understand it better. 
Oky, re-opening the issue.

**Comment by ttodua** [comment]
While looking at https://github.com/ccxt/ccxt/blob/master/js/bybit.js#L3574 it becomes obvious, that you can use:
```
const orders = await exch.fetchOpenOrders ('BTC/USDT:USDT',  undefined, undefined, {'orderType':'conditional'});
```
and loop through the orders to get their ID and then edit those orders. 
Let us know if still any issues.

**Comment by sirrisingeagle** [comment]
Thanks. This actually worked.
