### ISSUE TITLE
[Python] [binance] sapi_post_staking_purchase still not working

### ISSUE THREAD

**Issue by StevenFurious** [ccxt/ccxt#14420]
hi team, this issue is in Python, but i see you directed it to JS.

_Originally posted by @StevenFurious in https://github.com/ccxt/ccxt/issues/14417#issuecomment-1190069050_

**Comment by sc0Vu** [comment]
Hi @StevenFurious,

Basically, the python script was generated automatically from js file. You can install the latest version of ccxt.

**Comment by kroitor** [comment]
@StevenFurious Python is transpiled from JS in CCXT, just update your Python version of CCXT with pip and you should be fine: 

- https://github.com/ccxt/ccxt/wiki/FAQ#hey-the-fix-youve-uploaded-is-in-js-would-you-fix-python--php-as-well-please
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
