### ISSUE TITLE
Can't fetch huobi future positions 

### ISSUE THREAD

**Issue by ldkklj** [ccxt/ccxt#14421]
I use huobi.fetch_balance func ,only get ['info']['data'] ,and it contains any information about my future postion .
I also use fetch_postions ,such as:
pos = huobiN.fetch_positions(symbols=['BTC/USDT:USDT'])
and pos contains no item

**Comment by sc0Vu** [comment]
Hi @ldkklj 

Not sure what kind of position you use, you can use another type (inverse) in second parameter.

**Comment by kroitor** [comment]
@ldkklj what is your version of CCXT? Do you have this issue with the most recent version? How do you initialize the exchange instance? Please, paste your verbose output (enable verbose mode after loading the markets):

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by ttodua** [comment]
please try :
```
..fetch_positions(symbols=['BTC/USDT:USDT'], {'subType':'linear', 'marginMode': 'cross' } )  
#                                                                                            ^                                   ^
#                                                                                'linear' or 'inverse'       'cross' or 'isolated'
```
that should solve your frustration. Let us know if you still experience other issues.
