### ISSUE TITLE
the amount is always 0.01btc in binance

### ISSUE THREAD

**Issue by uioiuioi** [ccxt/ccxt#14431]
When I run this code, The binance creates orders with the amount 0.01btc always

`exchange.create_order(
            'BTC/USDT',
            'limit',
            side,
            0.001,     
            price,
        )`

I can't order the amount of btc, it always buy or sell with the amount 0.01

**Comment by ttodua** [comment]
Please read this : https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

Otherwise, we can't help, because when I test and execute the same code, it correctly send amount `0.001`, and not converting into `0.01`.
