### ISSUE TITLE
CCXT calls return BadRequest when setting Risk Limit and Leverage on swap contracts

### ISSUE THREAD

**Issue by lemozade** [ccxt/ccxt#14440]
- OS: Mac OS Monterey
- Programming Language version: Python 3.8.8
- CCXT version: 1.83.62

I am trying to set the Risk Limit and Leverage for swap contracts. Both API calls return BadRequest. I am following the v4 API document, and the required parameters look to be correct. Can someone please help?

Initialise Gate.io on CCXT:
self.exchange = ccxt.gateio({'apiKey': settings.gate_key, 'secret': settings.gate_secret, 'enableRateLimit': False})

Method for setting Risk Limit:
self.exchange.private_futures_post_settle_positions_contract_risk_limit( params={'settle': 'usdt', 'contract': 'BTC_USDT', 'risk_limit': '10'})

Returns:
BadRequest: gateio {"label":"INVALID_PROTOCOL","detail":"invalid argument: https://github.com/gateio/gateapi-python/issues/3"}

Method for setting Leverage:
self.exchange.private_futures_post_settle_positions_contract_leverage(params={'settle': 'usdt', 'contract': 'BTC_USDT', 'leverage': '0', 'cross_leverage_limit': '10'})

Returns:
BadRequest: gateio {"label":"INVALID_PROTOCOL","detail":"invalid argument: https://github.com/gateio/gateapi-python/issues/3"}

**Comment by carlosmiei** [comment]
Hello @lemozade, yes there is indeed an issue with that endpoint using the implicit API, we will fix it soon, thanks for reporting it!
