### ISSUE TITLE
wrong contract in PHP for fetchTrades

### ISSUE THREAD

**Issue by LeonLegion** [ccxt/ccxt#1444]
#1443 
https://github.com/ccxt/ccxt/wiki/Manual#trades-orders-executions-transactions

Base class  has wrong default parametrs for fetchTrades [Exchange.php#L1272](https://github.com/ccxt/ccxt/blob/master/php/Exchange.php#L1272)

**Comment by kroitor** [comment]
Fixed in #1443, thank you!
