### ISSUE TITLE
Cancel Order unified response

### ISSUE THREAD

**Issue by adi90x** [ccxt/ccxt#1445]
Hello, 

Just to know if someone if already working on unifing cancelOrder response ?
Or is there at least guideline of what should be return ?

**Comment by kroitor** [comment]
> Just to know if someone if already working on unifing cancelOrder response ?

Not yet.

> Or is there at least guideline of what should b

Let's make it together right here, right now? ) How about that? ) What would you propose? )

**Comment by adi90x** [comment]
I think hitbtc already do that ! 
Not sure if it better to implement cache everywhere or just unified to a True / False execution statuts ?

**Comment by kroitor** [comment]
@adi90x 

> I think hitbtc already do that !

They are in the list of approx 5% of exchanges that do that. Others don't.

> Not sure if it better to implement cache everywhere or just unified to a True / False execution statuts ?

It is already indicated, should throw an exception on error = false. No exception = true. If you find some exchange that doesn't obey that rule, let us know.

**Comment by hippylover** [comment]
bittrex had some issues this week that made a cancelorder and a buylimit/sellimit get a requesttimeout(i had 20 seconds sat), but the order/call still went through every time. Don't know if anything can be done with it though.

**Comment by adi90x** [comment]
Had the same kind of problem : now wrapping cancelOrder request in a retry
function (using async-retry module in nodejs, this module basically retry
same code as long as it catch an error ( plus, it can be heavily
configured, delay between each retry, etc)

You should look into it !

**Comment by kroitor** [comment]
Moved to #2983 for deduplication.
