### ISSUE TITLE
okex5 Parameter from  error

### ISSUE THREAD

**Issue by hosseinab** [ccxt/ccxt#14469]
OS: Windows 11
Programming Language version: PYTHON 3.10.5
CCXT version: "ccxt/ccxt": "^1.90.94",
Exchange: okex5
Method: transfer

hi
call this method :
connection.transfer(symbol, amount, 'spot', 'funding')

output :
okex5 {"code":"51000","data":[],"msg":"Parameter from  error"}

**Comment by carlosmiei** [comment]
Hello @hosseinab,

I don't think you're using the right arguments, are you sure `transfer` is the method you're looking for?
![image](https://user-images.githubusercontent.com/43336371/180660428-64d49f4e-fbe1-4b99-8359-0992812d431e.png)

**Comment by hosseinab** [comment]
@carlosmiei 
Yes . I worked in the same way for kucoin and it was correct. But Okex gives error

**Comment by hosseinab** [comment]
Is it possible to send a sample code?

**Comment by carlosmiei** [comment]
Hello @hosseinab, can you try something like this?

```Python

currency = 'USDT' # your currency here
amount = 10 # your amount here
from = '6' # 6 means funding account 
to = '18' # 18 means trading account
exchange.transfer(currency, amount, from, to)
```

You can check this out for more information about this `transfer` endpoint:  https://www.okx.com/docs-v5/en/#rest-api-funding-funds-transfer

**Comment by hosseinab** [comment]
@carlosmiei 
thank you . this code fix my problem

**Comment by d0ksan8** [comment]
Thanks <3
