### ISSUE TITLE
how to create future order in MEXC ? HELP ME

### ISSUE THREAD

**Issue by duckduck33** [ccxt/ccxt#14463]
Help me.
I want to place an order for the futures market.
 The code I wrote is as follows.
-------------python code------------------------
import ccxt
import hashlib
import math
import pprint

mexc_futures = ccxt.mexc({
    "apiKey": "xxxxxxxxxxxxxxx",
    "secret": "xxxxxxxxxxxxxxxxx",
    "options": {'defaultType': 'swap' }
})
symbol = 'BTC/USDT:USDT'
type = 5
side = 1
amount=0.001
params = {'openType': 1,  "positionType":1, "leverage": 30}
mexc_futures.create_swap_order(symbol, type, side, amount, params=params)
----------------------------------------------------------

The error is as follows
-------------
**ccxt.base.errors.ExchangeError: mexc {"success":false,"code":2011,"message":"Order quantity error, please try to modify."}**
--------------

What's the problem? help me to modify

**Comment by carlosmiei** [comment]
Hello @duckduck33,

In mecx we should express the `amount` field of derivatives in _contracts_ instead of the _base quote_.

So knowing that 
`0.0001 BTC ----> 1 contract`

If you want to buy 0.001 worth of BTC, I would say that your amount should be 10

` 0.001 / 0.0001 = 10 contracts `

Can you please try again with `amount = 10` to see if works as expected?

**Comment by duckduck33** [comment]
Thank you. As you said, I changed it to account=10 and executed it. The results are as follows.
"ccxt.base.errors.InvalidOrder: mexc {"success":false,"code":1002,"message":"Contract not allow place order!"}"
Could you tell me the complete open long order code as an example?
u are my hero. plz.

**Comment by carlosmiei** [comment]
Hello @duckduck33, yeah I've checked, and unfortunately "BTC/USDT:USDT", is one of the "unavailable contracts to trade using the API", so there's nothing we can do on our end.

**Comment by duckduck33** [comment]
Thank you. I just found out. I had a meaningless struggle like a fool. I'll ask for help again next time
