### ISSUE TITLE
kucoin pairs update

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1446]
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version: 1.10.900

please add more pairs as it is now announced.

https://news.bitcoin.com/pr-kucoin-exchange-adds-bch-trading-pairs/?utm_source=OneSignal%20Push&utm_medium=notification&utm_campaign=Push%20Notifications

**Comment by kroitor** [comment]
@jjhesk in fact, they are supported intrinsically by the current version of the lib, not hardcoded, so we don't have to add them, they are added automatically. Let us know if you can't find them with current version of the library.
