### ISSUE TITLE
Question: fetchOHLCV Implementation

### ISSUE THREAD

**Issue by kenchambers** [ccxt/ccxt#14475]
- OS: Mac
- Programming Language version: node v16.3.0
- CCXT version: 1.80.23

Not an issue, just a question. 

I am looking for a way to fetch candlestick data between two dates. I accidentally passed a time into `param[3]`  then i realized that it was not possible to get date ranges that way. Is it possible to get this information (in this way) using ccxt or ccxt.pro?

your time is greatly appreciated ! thanks for everything

```javascript
// for binanceus
// didnt work :(
let response = await this.client.fetchOHLCV(
            this.product,
            this.interval,
            new Date(start).getTime(),
            new Date(end).getTime()
          );
```

**Comment by kenchambers** [comment]
upon further inspection of docs, I saw that ccxt allows for additonal (exchange specific params) to be sent with the request, so according to: https://github.com/ccxt/ccxt/blob/master/js/binance.js and also to binance us docs (https://docs.binance.us/#get-order-book-depth) i should be able to pass in `startTime` and `endTime`.

### So heres attempt 2

```javascript
 let response = await this.client.fetchOHLCV(
            this.product,
            this.interval,
            new Date(start).getTime(),
            1000,
            {
              startTime: new Date(start).getTime(),
              endTime: new Date(end).getTime(),
            }
          );
```

But The candle stick end dates are still off by alot:

```
console.log(response[0]); //Sun Jan 24 2021 00:00:00 GMT+0100 (Central European Standard Time) {}
          console.log(response[response.length - 1]); //Wed Jan 27 2021 11:15:00 GMT+0100 (Central European Standard Time) {}
```

**Comment by kenchambers** [comment]
### Attempt 3

```javascript

let response = await this.client.fetchOHLCV(
            this.product,
            this.interval,
            new Date(start).getTime(),
            1000,
            {},
            undefined,
            new Date(end).getTime()
          );


```

I'm still getting only about 3 days out 

```
[ 1611442800000, 32075, 32133.51, 31934.65, 31950, 0.953527 ] //first
[ 1611742500000, 31341.61, 31403.9, 31244.8, 31293.12, 2.915708 ] //last
```

**Comment by sc0Vu** [comment]
Hi @kenchambers 

We used Kline api endpoint as default. In Binance, there is 1000 limit for Kline api: https://docs.binance.us/#get-candlestick-data.

The `startTime` and `endTime` you used in attempt 2 should work and send to Binance server. It only returned 1000 rows because of the limitation

**Comment by kenchambers** [comment]
yes your right! thanks so much for your time! closing issue.
