### ISSUE TITLE
Option symbols are not unique

### ISSUE THREAD

**Issue by mattepozz** [ccxt/ccxt#14473]
On OKX (and potentially on other exchanges) there are multiple option contracts sharing the same `symbol`.
This happens because options can have different expiry but same strike price. The `symbol` identifier does not include the `expiry`.

- OS: MacOS
- Programming Language version: Python
- CCXT version: `1.91.22`

```python
exchange = ccxt.okx()
exchange.load_markets()
markets = [
    market
    for market in exchange.markets_by_id.values()
    if market["symbol"] == "BTC/USD:BTC-120000-P"
]
for market in markets:
    print(f"Id: {(market['id'])} — symbol: {market['symbol']}")
```

Output:

```
id: BTC-USD-220930-120000-P — symbol: BTC/USD:BTC-120000-P
id: BTC-USD-221230-120000-P — symbol: BTC/USD:BTC-120000-P
id: BTC-USD-230630-120000-P — symbol: BTC/USD:BTC-120000-P
```

A consequence is that the `markets` object—which is indexed by symbol—contains only one of these three options.

**Comment by carlosmiei** [comment]
Hello @mattepozz, thanks for letting us know, will be fixed soon!
