### ISSUE TITLE
fetch_funding_rate does not match historical or data on FTX

### ISSUE THREAD

**Issue by mmehrle** [ccxt/ccxt#14482]
I am pulling the live funding rate for perpetual futures as such:

`
import ccxt
exchange = ccxt.ftx({'enableRateLimit': True})
result = exchange.fetch_funding_rate(symbol)
`

Here's example output for BTC-PERP, ETH-PERP, and 'XRP-PERP' - all run during the 15:00 UTC hourly interval:

`{'info': {'volume': '1984204.523', 'nextFundingRate': '-9e-6', 'nextFundingTime': '2022-07-25T15:00:00+00:00', 'openInterest': '693806.1406'}, 'symbol': 'ETH/USD:USD', 'markPrice': None, 'indexPrice': None, 'interestRate': 0.0, 'estimatedSettlePrice': None, 'timestamp': None, 'datetime': None, 'fundingRate': -9e-06, 'fundingTimestamp': 1658761200000, 'fundingDatetime': '2022-07-25T15:00:00.000Z', 'nextFundingRate': None, 'nextFundingTimestamp': None, 'nextFundingDatetime': None, 'previousFundingRate': None, 'previousFundingTimestamp': None, 'previousFundingDatetime': None}

info': {'volume': '108043.4471', 'nextFundingRate': '-5e-6', 'nextFundingTime': '2022-07-25T15:00:00+00:00', 'openInterest': '57848.7969'}, 'symbol': 'BTC/USD:USD', 'markPrice': None, 'indexPrice': None, 'interestRate': 0.0, 'estimatedSettlePrice': None, 'timestamp': None, 'datetime': None, 'fundingRate': -5e-06, 'fundingTimestamp': 1658761200000, 'fundingDatetime': '2022-07-25T15:00:00.000Z', 'nextFundingRate': None, 'nextFundingTimestamp': None, 'nextFundingDatetime': None, 'previousFundingRate': None, 'previousFundingTimestamp': None, 'previousFundingDatetime': None}

{'info': {'volume': '107197570.0', 'nextFundingRate': '-0.000012', 'nextFundingTime': '2022-07-25T15:00:00+00:00', 'openInterest': '174111771.0'}, 'symbol': 'XRP/USD:USD', 'markPrice': None, 'indexPrice': None, 'interestRate': 0.0, 'estimatedSettlePrice': None, 'timestamp': None, 'datetime': None, 'fundingRate': -1.2e-05, 'fundingTimestamp': 1658761200000, 'fundingDatetime': '2022-07-25T15:00:00.000Z', 'nextFundingRate': None, 'nextFundingTimestamp': None, 'nextFundingDatetime': None, 'previousFundingRate': None, 'previousFundingTimestamp': None, 'previousFundingDatetime': None}
`

The problem I am encountering is that the live quotes are different from what is shown at that time over at https://ftx.com/funding

It's also different that of the historical data I later pull via this call: 

`params = {
            'end_time': int(end_time / 1000),
        }
results = exchange.fetch_funding_rate_history(symbol, since, limit, params)
`

That data seems to match that over at https://ftx.com/funding

I understand that you have no little control over what FTX reports, but it's strange that the 'live' call would produce different output than the historic one.

**Comment by mmehrle** [comment]
any ideas here?

**Comment by frosty00** [comment]
@mmehrle the fundingRate is the estimated funding rate for the next hour, if you notice the hour has not finished at the time the fundingRate is quoted so it is impossible to tell what the actual fundingRate it will settle at will be unless you make a call at 12:59

**Comment by mmehrle** [comment]
Okay so this is the future/estimated funding rate? And yes I noticed that the hour had not finished at that time, just assumed that was the way it was quoted (for that ongoing hour).

**Comment by samgermain** [comment]
closing because FTX is delisted now
