### ISSUE TITLE
okex withdraw error

### ISSUE THREAD

**Issue by hosseinab** [ccxt/ccxt#14499]
OS: Windows 11
Programming Language version: PYTHON 3.10.5
CCXT version: "ccxt/ccxt": "^1.90.94",
Exchange: okex
Method: withdraw

hi
i use this code for withdraw from okex5 :
symbol = "USDT"
amount = 5
address = "TWQ3VrD4KXXbymggfWVdTykWHp6xeUWU3D"
tag = None

params = {
      'fee': '0.8',
      'pwd': '*****',
      'chain': 'USDT-TRC20'
  }
  response = connection.withdraw(symbol, amount, address, tag, params)
  print(response)

and output this :
{"code":"58203","data":[],"msg":"Please add a withdrawal address."}

What is the reason of this error?

**Comment by sc0Vu** [comment]
Hi @hosseinab 

Have you whitelist the withdrawal address in okey?

**Comment by hosseinab** [comment]
hi @sc0Vu
No . Is it not possible to withdraw without creating white list?

**Comment by hosseinab** [comment]
I added the address to the whitelist and it was fixed. Is there a way to add this address to the whitelist with a code?

**Comment by sc0Vu** [comment]
I think they didn't have this api yet.
