### ISSUE TITLE
How can I generate a sign for a simple http API request?

### ISSUE THREAD

**Issue by kmeans27** [ccxt/ccxt#14497]
Hello, 

I am no experienced programmer. I simply just want to get my bybit order data so i can analyze it automatically. 
I am currently trying to connect to the API via http. Later on I want to import the data into excel for analysis purposes.

I am not understanding how I can generate a sign..

**This is my request:** 

https://api.bybit.com/v2/private/execution/list?api_key=************&recv_window=100000000000000&symbol=BTCUSD&timestamp=1658829803291

(I know I am not using the correct timestamp, but I do not know how to submit the timestamp automatically via a simple http request...)
Note here that i am not submiting any sign, because I don't know how to find out!

**This is my error message:**
 {"ret_code":10004,"ret_msg":"error sign! origin_string[api_key=***********\u0026recv_window=100000000000000\u0026symbol=BTCUSD\u0026timestamp=1658829803291]","ext_code":"","ext_info":"","result":null,"time_now":"1658830285.048043"}
 
 
 Thank you in advance.

**Comment by carlosmiei** [comment]
Hello @kmeans27,

CCXT handles all of that for you, please make sure to read our manual carefully top to bottom, and check some of the examples:
https://docs.ccxt.com/en/latest/
https://github.com/ccxt/ccxt/tree/master/examples

**Comment by ttodua** [comment]
I'll mark the topic as closed, because it got the valid answer. let us know if you have any issue with CCXT.
