### ISSUE TITLE
[BYBIT] [HOW-TO] Add multiple stop loss & take profit to open order

### ISSUE THREAD

**Issue by aFluxx** [ccxt/ccxt#14506]
- OS: Ubuntu 20.04
- Programming Language version: JavaScript
- CCXT version: latest

Hi,

With [this endpoint ](https://bybit-exchange.github.io/docs/linear/#t-tradingstop) you can add multiple stop losses & take profit for an already open long or short position.

I was browsing through `bybit.js` from the ccxt package, but I can't seem to find how to use it via ccxt.  I was hoping someone could explain to me how I can use this functionality?

I can see these endpoints are in the `describe()` method of `bybit.js`, but I can't seem to find a method which acutally can performs these actions.

**Comment by sc0Vu** [comment]
Hi

You can call implicit method in ccxt. For the `POST /private/linear/position/trading-stop`, you can use either `privatePostV2PrivatePositionTradingStop` or `private_post_v2_private_position_trading_stop`.

**Comment by aFluxx** [comment]
> Hi
> 
> You can call implicit method in ccxt. For the `POST /private/linear/position/trading-stop`, you can use either `privatePostV2PrivatePositionTradingStop(params)` or `private_post_v2_private_position_trading_stop(params)`.

Awesome, thanks, i'll try that out.

**Comment by ttodua** [comment]
I'll mark the topic as closed. let us know if you have any further issues with CCXT.
