### ISSUE TITLE
How can I get Buy and Sell Orders from Binance?

### ISSUE THREAD

**Issue by delgec** [ccxt/ccxt#14508]
Hello Guys

I want to retrieve **buy and sell orders** from binance. I looked but I didn't find anything.

How can I get **Buy and Sell Orders** from Binance?

Sincerely

**Comment by carlosmiei** [comment]
Hello @delgec, I think you're looking for `fetchOrders`.

Check this out: https://docs.ccxt.com/en/latest/manual.html#orders

**Comment by ttodua** [comment]
The above post answers the issue. Also, to save your time and find things quicker, I advise to look through the manual which was included in above post.
let us know if you have any further problems with CCXT

**Comment by delgec** [comment]
> Hello @delgec, I think you're looking for `fetchOrders`.
> 
> Check this out: https://docs.ccxt.com/en/latest/manual.html#orders

It's worked. Thanks.
