### ISSUE TITLE
NotSupported ('kucoin no auth',) kucoin no auth

### ISSUE THREAD

**Issue by avibrazil** [ccxt/ccxt#14505]
- OS: Linux
- Programming Language version: Python 3.10
- CCXT version: 1.91.35 (latest as of today)

KuCoin stopped working for me since yesterday.

Tested [this simple CCXT example](https://github.com/ccxt/ccxt/blob/master/examples/py/tickers.py).
Output shows a list for pairs, but then:
```
NotSupported ('kucoin no auth',) kucoin no auth
```

Tested from Brazil and Taiwan, result is the same.

**Comment by carlosmiei** [comment]
Hello @avibrazil,
I've just tested and it is working fine on my end.
Are you sure that your API keys did not expire and don't have in place some IP whitelisting for instance?

**Comment by avibrazil** [comment]
Does it work with your API keys?
That's a rhetorical question, because this script doesn't need API keys, its an anonymous call to KuCoin API.

I'm currently investigating if they blocked my IP or not.

**Comment by avibrazil** [comment]
Problem was a `~/.netrc` file with a **default** login that I use in some other services to login. I had:

```
default
login some_username
password some_password
```

Apparently Python's underlying requests or urllib use this as authentication to login into sites. Simply removing `~/.netrc` made it work again. But you don't have to. Just be more specific where to use this user name and password, so I changed my `~/.netrc` content to:

```
machine some_specific_hostname.com
login some_username
password some_password
```

**Comment by carlosmiei** [comment]
@avibrazil alright, thanks for letting us know! 🙂
