### ISSUE TITLE
Can i open a position with a trailing stop on phemex?

### ISSUE THREAD

**Issue by CloudTrauma** [ccxt/ccxt#14502]

**Comment by carlosmiei** [comment]
Hello @CloudTrauma,

You can by providing two additional values inside `params`, `pegOffsetValueEp` and `pegPriceType`.

The first one refers to the trailing offset from current price (Negative value when position is long, positive when position is short) and the latter might be `TrailingStopPeg` or `TrailingTakeProfitPeg`.

You might want to check this out: https://github.com/phemex/phemex-api-docs/blob/master/Public-Contract-API-en.md#placeorder

**Comment by CloudTrauma** [comment]
I don't mean to have a trailing stop in the position. I mean for the trailing stop to open the position

**Comment by carlosmiei** [comment]
@CloudTrauma Ok, I misinterpreted the question initially.
I don't think it is possible, since the goal of the trailing stop is to protect the current position and close it if needed.

https://phemex.com/user-guides/trailing-stops-and-activation-prices

**Comment by CloudTrauma** [comment]
Opening this back up because when i try to open the position with a trailing stop as a market order, it ignores the params
