### ISSUE TITLE
binance.py fetch_positions_risk() - Missing arguments?

### ISSUE THREAD

**Issue by hedeer-showk** [ccxt/ccxt#14503]
https://github.com/ccxt/ccxt/blob/b459dd73c99c744e7f623ed56aa93e646b1f59f8/python/ccxt/binance.py#L5109

I'm getting an error here using the default binance exchange object and calling fetchPositions() with:

```
binance.fetchPositions(params={'type': 'future'})
```

From what I see in the code, fetch_positions_risk() is calling load_leverage_brackets() but not passing `params`.  The error below shouldn't be happening imo if I'm passing `params` to fetch_positions_risk (i.e., it should be passed through so L5109 should be `self.load_leverage_brackets(params=params)`.  Am I completely off here?

```
    def load_leverage_brackets(self, reload=False, params={}):
        self.load_markets()
        # by default cache the leverage bracket
        # it contains useful stuff like the maintenance margin and initial margin for positions
        leverageBrackets = self.safe_value(self.options, 'leverageBrackets')
        if (leverageBrackets is None) or (reload):
            method = None
            defaultType = self.safe_string(self.options, 'defaultType', 'future')
            type = self.safe_string(params, 'type', defaultType)
            query = self.omit(params, 'type')
            if type == 'future':
                method = 'fapiPrivateGetLeverageBracket'
            elif type == 'delivery':
                method = 'dapiPrivateV2GetLeverageBracket'
            else:
>               raise NotSupported(self.id + ' loadLeverageBrackets() supports linear and inverse contracts only')
E               ccxt.base.errors.NotSupported: binance loadLeverageBrackets() supports linear and inverse contracts only

venv/lib/python3.8/site-packages/ccxt/binance.py:4943: NotSupported
```

Happy to open a PR to update this if need be...I've just started using ccxt though so may not be on the right track.

Edit:
Seems the `defaultType` is set to `'spot'` so that's why this is failing:

```
if (leverageBrackets is None) or (reload):
            method = None
            defaultType = self.safe_string(self.options, 'defaultType', 'future')
            type = self.safe_string(params, 'type', defaultType)
            query = self.omit(params, 'type')
            if type == 'future':
                method = 'fapiPrivateGetLeverageBracket'
            elif type == 'delivery':
                method = 'dapiPrivateV2GetLeverageBracket'
            else:
                raise NotSupported(self.id + ' loadLeverageBrackets() supports linear and inverse contracts only')
```

Definitely think `params` should get passed through here...simple fix

**Comment by hedeer-showk** [comment]
In fact this might also need to be in `fetch_account_positions()`?

**Comment by carlosmiei** [comment]
Hello @hedeer-showk, you're right `params` should be propagated to `load_leverage_brackets`. However, to avoid conflicts, if you're handling 'futures' it is advisable to instantiate `binanceusdm` instead

```Python
exchange = ccxt.binanceusdm({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET_KEY',
}
```

**Comment by hedeer-showk** [comment]
@carlosmiei I have this patched in a fork and can PR but running tests I see a fail on `xena` for the python transpilation.  The `js` tests run fine.  I do see the fix properly transpiled into binance.py  (not sure if it needs to be in any of the other binance exchanges?).

**Comment by carlosmiei** [comment]
@hedeer-showk, bear in mind that if you want to make your custom changes and build it from the source to make it available in every language, you must change the Javascript file only and following all of our code guidelines to make sure that when you build it the transpilations process works as expected.

You can read more about it here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

**Comment by ttodua** [comment]
@hedeer-showk 
please take a look how the above referenced PR (and the "files" in that PR) was changed, thus, you can understand what you needed to do, in order to make a mergeable PR.

**Comment by hedeer-showk** [comment]
Thanks @ttodua.  I managed the fix but had trouble getting the php tests to run properly.  Tried it in the docker container and still had some issues unfortunately @kroitor recommended I run `composer install` in the container shell (we talked on discord) and it now worked.

How about having the Dockerfile run `composer install` for you?  Happy to PR that as well if you guys think it'll help.

**Comment by ttodua** [comment]
@hedeer-showk 
it's always welcomed if you make a PR. however, please note, that you should do in JS, and if you have issues with testing php/py etc, you can ignore that initially and I'll do that on my side. but again, emphasize on JS.

**Comment by hedeer-showk** [comment]
@ttodua thanks and makes sense.  I had the js fix in without issue and checked it transpiled properly into php and python by reading the code.  Next time I'll PR it there but I would like to get the whole test suite working anyway.  Thanks for the response too and sorry it took a while...got hit by covid :/!

**Comment by ttodua** [comment]
> @ttodua thanks and makes sense. I had the js fix in without issue and checked it transpiled properly into php and python by reading the code. Next time I'll PR it there but I would like to get the whole test suite working anyway.

Yeah good, that will make PR's to be reviewed & merged easier
