### ISSUE TITLE
gate.io parseTrade fees

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#14515]
I have some questions about `fee/fees` on gate.io.
In code of  `parseTrade` we have:
```
 'fee': undefined,
 'fees': fees,
```

In case of zero fees:
```
{
    info: {
      id: '3890811349',
      create_time: '1659011681',
      create_time_ms: '1659011681543.849900',
      currency_pair: 'BTC_USDT',
      side: 'sell',
      role: 'maker',
      amount: '0.0018',
      price: '22892.76',
      order_id: '184929604262',
      fee: '0',
      fee_currency: 'USDT',
      point_fee: '0',
      gt_fee: '0'
    },
    id: '3890811349',
    timestamp: 1659011681543,
    datetime: '2022-07-28T12:34:41.543Z',
    symbol: 'BTC/USDT',
    order: '184929604262',
    type: undefined,
    side: 'sell',
    takerOrMaker: 'maker',
    price: 22892.76,
    amount: 0.0018,
    cost: 41.206968,
    fee: undefined,
    fees: []
  }
```

`fee` is `undefined` in all cases. Is it normal? 
Because there is no fee in my case, is it normal that `fees` is an empty array? Or it should be like `[{ 'cost': 0, 'currency': 'USDT'}]`?

**Comment by frosty00** [comment]
@ndubel that's a good point, I think it should be specified here. The problem is that we would need to do: fee: `[ { 'currency': 'GT', 'cost': 0 }, { 'currency': 'USDT', 'cost': 0 } ]`

**Comment by ttodua** [comment]
If there was trade, and fees is not filled, then it's bug possibly. Thanks for report, i'll take a look into this now.
