### ISSUE TITLE
okx default type does not change

### ISSUE THREAD

**Issue by ar3sla** [ccxt/ccxt#14512]
i'm using the latest version of ccxt
in okx, when i change defaultType to swap or any other kinds it does not change and when i call an order it still shows spot mode price and ..... .
and when I wanna create a swap order it shows error which i don't have when i use binance and change defaultType to future.

okex = ccxt.okx({
    'apiKey': config.API_KEY,
    'secret': config.API_SECRET,
    'password' : config.API_PASS,
    'options':{
        'defaultType' : 'swap'
        },

})
okex.set_sandbox_mode(True)

leve = okex.set_leverage(10 , 'ETH-USDT' ,  params = {'mgnMode' : 'isolated'} , )
order1 = okex.create_market_buy_order('ETH-USDT' , 6 )
print(order1)

but when i use this code i can get swap price but i can't open an order with swap symbol :

okex = ccxt.okx({
    'apiKey': config.API_KEY,
    'secret': config.API_SECRET,
    'password' : config.API_PASS,
})

ticker = okex.fetch_ticker('ETH-USDT-SWAP')
print(ticker)

**Comment by carlosmiei** [comment]
Hello @ar3sla you're mixing up spot and swap market ids.

If you want to place an order for the linear ETH/USDT swap you should be using `ETH-USDT-SWAP` as an argument for `createMarketBuyOrder` instead of `ETH-USDT`, the latter represents the spot symbol.

**Comment by ar3sla** [comment]
hi @carlosmiei, thanks for your answer
but when i change it to ETH-USDT-SWAP with this code:
okex = ccxt.okx({
    'apiKey': config.API_KEY,
    'secret': config.API_SECRET,
    'password' : config.API_PASS,
    'options':{
        'defaultType' : 'swap'
        },

})
okex.set_sandbox_mode(True)

params1 = {
    "instId":"ETH-USDT-SWAP",
    "tdMode":"isolated",
    "side":"buy",
    'posSide':"SWAP",
    "ordType":"market",
    "sz":"6"
}
order1 = okex.create_market_buy_order('ETH-USDT-SWAP' , 6 , params=params1)
print(order1)

it shows me this error :
ccxt.base.errors.BadRequest: okx {"code":"1","data":[{"clOrdId":"e847386590ce4dBC2ffbe9c12cb175e0","ordId":"","sCode":"51000","sMsg":"Parameter posSide  error ","tag":""}],"msg":"Operation failed."}



and if i use ETH-USDT in this code :
okex = ccxt.okx({
    'apiKey': config.API_KEY,
    'secret': config.API_SECRET,
    'password' : config.API_PASS,


})
okex.set_sandbox_mode(True)


order1 = okex.create_market_buy_order('ETH-USDT' , 6 )
print(order1)

it shows me this error :

ccxt.base.errors.InsufficientFunds: okx {"code":"1","data":[{"clOrdId":"e847386590ce4dBCb25a7bde230285b0","ordId":"","sCode":"51008","sMsg":"Order placement failed due to insufficient balance ","tag":""}],"msg":"Operation failed."}

**Comment by carlosmiei** [comment]
Hello @ar3sla,

> order1 = okex.create_market_buy_order('ETH-USDT' , 6 )
> print(order1)

this is not what you want, as said earlier 'ETH-USDT' is a spot symbol, so you're saying "I want to buy 6 ETH with USDT"

> order1 = okex.create_market_buy_order('ETH-USDT-SWAP' , 6 , params=params1)
> print(order1)

You're almost there, you're just missing the `postSide` parameter required by OKX.

Something like this:
```Python

params1 = {
    "marginMode":"isolated", # or cross
    "posSide":"long", # long or short depending on your intent
}
symbol = "ETH-USDT-SWAP"
amount = 6 # number of contracts
order1 = okex.create_market_buy_order(symbol , amount , params=params1)
print(order1)
```

**Comment by ar3sla** [comment]
thanks a lot @carlosmiei
the posside solved my problem.
i'm really thankfull

**Comment by ar3sla** [comment]
thanks a lot @carlosmiei
the posside solved my problem.
I'm really thankful
