### ISSUE TITLE
ccxtpro watch_balance only fetch first one position changes?

### ISSUE THREAD

**Issue by keezyshen** [ccxt/ccxt#14516]
I am now using ccxrpro, with the endpoint of watch_balance, when I have dumped all the positions at the same time, (for example : nearusdt and uniusdt
)but it's just fectched the balance of nearusdt (sure, it's zero) but there's no balance inof about uniusdt. 

the data returned from watch_balance as follows: 
{'info': {'e': 'ACCOUNT_UPDATE', 'T': 1659018683218, 'E': 1659018683228, 'a': {'B': [{'a': 'USDT', 'wb': '11849.72056194', 'cw': '11849.72056194',
'bc': '0'}], 'P': [{'s': 'NEARUSDT', 'pa': '0', 'ep': '0.0000', 'cr': '0', 'up': '0', 'mt': 'isolated', 'iw': '0', 'ps': 'BOTH', 'ma': 'USDT'},
{'s': 'NEARUSDT', 'pa': '0', 'ep': '0.0000', 'cr': '116.37600000', 'up': '0', 'mt': 'isolated', 'iw': '0', 'ps': 'LONG', 'ma': 'USDT'},
{'s': 'NEARUSDT', 'pa': '0', 'ep': '0.0000', 'cr': '503.78699999', 'up': '0', 'mt': 'isolated', 'iw': '0', 'ps': 'SHORT', 'ma': 'USDT'}], 
'm': 'ORDER'}}, 'USDT': {'free': None, 'used': None, 'total': 11849.72056194}, 'timestamp': None, 'datetime': None, 'free': {'USDT': None}, 
'used': {'USDT': None}, 'total': {'USDT': 11849.72056194}}

Question is I can not obtain the real balance data of uninear again, how can I fix this problem?

	while True :
		try : 
			balance = await exchange.watch_balance({'type' : 'future'}) 
		except ccxt.NetworkError as e:
			await asyncio.sleep(1)
			continue 
		except Exception as e:
		 	print(type(e).__name__, str(e))
		 	raise Exception(str(e))
      
     print(balance)
     
     #processing the balance code below....
     
   many thanks.

**Comment by carlosmiei** [comment]
Hello @keezyshen,

I think you're confusing "balance" with "positions info".  `watchBalance` only processes the account balance and if you notice inside the raw update only this `B` object refers to the balance, as you can see there's only USDT in there:
![image](https://user-images.githubusercontent.com/43336371/181596017-7d78b8bd-d507-4ca8-a31d-3c80667c0f5e.png)

The P object contains information regarding your current positions (margin, unrealised pnl, etc) but that is not considered balance information. We have plans to unify `watchPositions` that is most likely what you're looking for but it's not done yet, unfortunately.
![image](https://user-images.githubusercontent.com/43336371/181596182-bad18db4-d791-433a-8dae-705dd0203c21.png)

You can read more about this specific binance update here: https://binance-docs.github.io/apidocs/futures/en/#event-margin-call

**Comment by keezyshen** [comment]
Understood , many thanks team !------------------ Original ------------------From: Carlos Gonçalves  ***@***.***>Date: Fri,Jul 29,2022 1:05 AMTo: ccxt/ccxt ***@***.***>Cc: Wesley S ***@***.***>, Mention ***@***.***>Subject: Re: [ccxt/ccxt] ccxtpro watch_balance only fetch first one positionchanges? (Issue #14516)
Hello @keezyshen,
I think you're confusing "balance" with "positions info".  watchBalance only processes the account balance and if you notice inside the raw update only this B object refers to the balance, as you can see there's only USDT in there:

The P object contains information regarding your current positions (margin, unrealised pnl, etc) but that is not considered balance information. We have plans to unify watchPositions that is most likely what you're looking for but it's not done yet, unfortunately.

You can read more about this specific binance update here: https://binance-docs.github.io/apidocs/futures/en/#event-margin-call

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/ccxt/ccxt/issues/14516#issuecomment-1198409129",
"url": "https://github.com/ccxt/ccxt/issues/14516#issuecomment-1198409129",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by carlosmiei** [comment]
@keezyshen alright I'll close this issue then, let us know if anything! Thanks
