### ISSUE TITLE
Add Exbitron.com to list

### ISSUE THREAD

**Issue by Sterling2p** [ccxt/ccxt#14518]
Please consider adding Exbitron.com to the list of exchanges. 

https://www.exbitron.com/kb/api.html

**Comment by JustFragger** [comment]
Our API is almost same as AltMarkets API which is already integrated as I saw code.
So should not be problem with integration.

**Comment by Sterling2p** [comment]
Exbitron API is almost same as AltMarkets API which is already integrated as I saw code.
So should not be problem with integration.

**Comment by JustFragger** [comment]
> Exbitron API is almost same as AltMarkets API which is already integrated as I saw code. So should not be problem with integration.

Yeah I wrote that, but deleted my comment because AltMarkets is not in CCXT integrated. I wrote this to different issue repo 😆

**Comment by Sterling2p** [comment]
ah, that's why I didn't see it when I came on here. I have asked a friend to help on this. Hopefully he can produce something.

**Comment by nitrocon** [comment]
I would absolutely recommend to get exbitron to the list...I need to add it to octobot, ASAP 🗡️

**Comment by JustFragger** [comment]
@samgermain is possible to implement by myself? Or needs to be implemented by CCXT team?

**Comment by samgermain** [comment]
> @samgermain is possible to implement by myself? Or needs to be implemented by CCXT team?

You can, but there's a lot of new exchange PRs that have been there for a while, and I'll not sure how soon it will get merged. I can help review it and make sure everything is up to standard. Here's a [new exchange PR](https://github.com/ccxt/ccxt/pull/10778) that I just completed where everything is in near perfect condition.

**Comment by frosty00** [comment]
the exchange has no volume
