### ISSUE TITLE
Binanceusdm "Illegal characters found in parameter 'startTime'; legal range is '1659009407615'

### ISSUE THREAD

**Issue by proskurin** [ccxt/ccxt#14513]
- OS: Mac OS
- Programming Language version: Python 3.8
- CCXT version: latest

Hi, I am trying to get trades from Binance perpetuals using `since` parameter.

```
import ccxt
import pandas as pd

exchange_client = ccxt.binanceusdm(
    {'apiKey': api, 'secret': secret, 'enableRateLimit': True})
symbol='BTCUSDT'
t = pd.Timestamp(2022, 7, 1)
since = t.timestamp() * 1000
trades = exchange_client.fetch_my_trades(symbol, since=since, limit=None)
```

As a result, I get:

```
BadRequest: binanceusdm {"code":-1100,"msg":"Illegal characters found in parameter 'startTime'; legal range is '1659010400603'."}
```

Exactly the same code works perfectly fine for FTX(

**Comment by kroitor** [comment]
@proskurin thanks, please, let us know if you have this issue with CCXT 1.91.41+

**Comment by ttodua** [comment]
please try `since = int(t.timestamp() * 1000)` and let me know. ensure, you provide the required types in arguments into ccxt unified methods.

**Comment by ttodua** [comment]
ah, issue was already answered/fixed in the meantime, i missed the above comment.

**Comment by proskurin** [comment]
With the newest version - no mistake is generated, but the problem is that the method always returns empty array of trades despite the fact that the account has trades

**Comment by kroitor** [comment]
@proskurin please, paste your verbose output (make sure you're using the correct keys): 

```Python
import ccxt
import pandas as pd

print('CCXT Version:', ccxt.__version__)

exchange_client = ccxt.binanceusdm(
    {'apiKey': api, 'secret': secret, 'enableRateLimit': True})
symbol='BTCUSDT'
t = pd.Timestamp(2022, 7, 1)
since = t.timestamp() * 1000
markets = exchange_client.load_markets()
exchange_client.verbose = True
trades = exchange_client.fetch_my_trades(symbol, since=since, limit=None)
```

**Comment by proskurin** [comment]
I used ADAUSDT (cause I had trades with that). That's what I get:


`fetch Request: binanceusdm GET https://fapi.binance.com/fapi/v1/userTrades?timestamp=1659107236818&symbol=ADAUSDT&startTime=1656633600000&recvWindow=5000&signature=50a2167ccc748f22253b6e0012a314ad438a396329d76f741a5956871da150ab RequestHeaders: {'X-MBX-APIKEY': 'KH7V7R3gsdVWyz5JWuL47OxHgYLdDopeIH2hc60t79jd7QRudBifb5BQ9cji222Y', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None`

`fetch Response: binanceusdm GET https://fapi.binance.com/fapi/v1/userTrades?timestamp=1659107236818&symbol=ADAUSDT&startTime=1656633600000&recvWindow=5000&signature=50a2167ccc748f22253b6e0012a314ad438a396329d76f741a5956871da150ab 200 ResponseHeaders: {'Content-Type': 'application/json', 'Content-Length': '2', 'Connection': 'keep-alive', 'Date': 'Fri, 29 Jul 2022 15:07:16 GMT', 'Server': 'Tengine', 'X-MBX-USED-WEIGHT-1M': '5', 'x-response-time': '4ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': '*,clienttype,Content-Type,lang,x-ui-request-trace,bnc-uuid', 'Content-Security-Policy': "default-src 'self'", 'cache-control': 'no-cache, no-store, must-revalidate', 'expires': '0', 'pragma': 'no-cache', 'strict-transport-security': 'max-age=31536000; includeSubdomains', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 047bf774bd56c377ffa47dc61e91fca2.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'CDG52-P1', 'X-Amz-Cf-Id': 'oDVfs7_f1WQX9m6HTCFDXqOz9D40dxhQO1KVNz6uNqANaXJsqns5Kw=='} ResponseBody: []`

**Comment by proskurin** [comment]
Here is what I get:

`fetch Request: binanceusdm GET https://fapi.binance.com/fapi/v1/userTrades?timestamp=1659107236818&symbol=ADAUSDT&startTime=1656633600000&recvWindow=5000&signature=50a2167ccc748f22253b6e0012a314ad438a396329d76f741a5956871da150ab RequestHeaders: {'X-MBX-APIKEY': '<hidden api key>', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None`

`fetch Response: binanceusdm GET https://fapi.binance.com/fapi/v1/userTrades?timestamp=1659107236818&symbol=ADAUSDT&startTime=1656633600000&recvWindow=5000&signature=50a2167ccc748f22253b6e0012a314ad438a396329d76f741a5956871da150ab 200 ResponseHeaders: {'Content-Type': 'application/json', 'Content-Length': '2', 'Connection': 'keep-alive', 'Date': 'Fri, 29 Jul 2022 15:07:16 GMT', 'Server': 'Tengine', 'X-MBX-USED-WEIGHT-1M': '5', 'x-response-time': '4ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': '*,clienttype,Content-Type,lang,x-ui-request-trace,bnc-uuid', 'Content-Security-Policy': "default-src 'self'", 'cache-control': 'no-cache, no-store, must-revalidate', 'expires': '0', 'pragma': 'no-cache', 'strict-transport-security': 'max-age=31536000; includeSubdomains', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 047bf774bd56c377ffa47dc61e91fca2.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'CDG52-P1', 'X-Amz-Cf-Id': 'oDVfs7_f1WQX9m6HTCFDXqOz9D40dxhQO1KVNz6uNqANaXJsqns5Kw=='} ResponseBody: []`

**Comment by proskurin** [comment]
@kroitor

**Comment by kroitor** [comment]
@proskurin does your api key correspond to the account in question? From this response body `ResponseBody: []` it follows that your apiKey didn't make any trades in the past month ? Could it be a wrong apiKey / wrong account ?

**Comment by proskurin** [comment]
@kroitor I have double checked that and yeah, trades are in place. Furthermore, I've checked also Binance Test Net account - empty response also (

**Comment by kroitor** [comment]
@proskurin we're talking of binance futures ADAUSDT trades, not binance spot USDT trades, right?

**Comment by proskurin** [comment]
@kroitor, yes, perpetual swap ADAUSDT trades

**Comment by kroitor** [comment]
@proskurin make sure that your API key from the verbose output corresponds to the API key on your Binance account.

**Comment by proskurin** [comment]
Yeah, I made sure. Because I am able to get account value, open positions, etc with this API key
But trades response is empty(

**Comment by kroitor** [comment]
@proskurin have you created this API key before opening the swap/futures account (before accepting it) ? If that is the case, then you will need to create another key after enabling futures trading for your account – that is one of known issues with Binance. Please, let me know if it still does not work with a fresh new keypair.

**Comment by proskurin** [comment]
Ok, I have just created 2 trades on the platform - and API brings me them if I set to July 25. I July 1st - empty response
It looks like, if I ask set since parameter for too early - the API will generate empty response

**Comment by proskurin** [comment]
The question is: how to make sure that I get all trades?

**Comment by kroitor** [comment]
@proskurin your query window must be narrowed to 7 days, for that you should set the `endTime` param as well:

Let me know if this does not help:

```Python
import ccxt
import pandas as pd

print('CCXT Version:', ccxt.__version__)

exchange_client = ccxt.binanceusdm(
    {'apiKey': api, 'secret': secret, 'enableRateLimit': True})
symbol='BTCUSDT'
t = pd.Timestamp(2022, 7, 1)
since = int(t.timestamp() * 1000)
endTime = int(since + 7 * 24 * 60 * 60 * 1000 - 1)
markets = exchange_client.load_markets()
exchange_client.verbose = True
trades = exchange_client.fetch_my_trades(symbol, since=since, limit=None, {'endTime':until})
```

**Comment by proskurin** [comment]
I see, thank you!

**Comment by kroitor** [comment]
@proskurin I've added some workarounds that should make fetching Binance perpetual swap trades easier. If possible, please, upgrade to CCXT 1.91.45+ (the new build will arrive in ~20 minutes) and let me know if you have issues with this code (it should print the runtime ccxt version for reference):

```Python
mport ccxt
import pandas as pd

print('CCXT Version:', ccxt.__version__)

exchange_client = ccxt.binanceusdm(
    {'apiKey': api, 'secret': secret, 'enableRateLimit': True})
symbol='BTCUSDT'
t = pd.Timestamp(2022, 7, 1)
since = int(t.timestamp() * 1000)
markets = exchange_client.load_markets()
exchange_client.verbose = True
trades = exchange_client.fetch_my_trades(symbol, since=since, limit=None)
```

Thanks for your feedback!
