### ISSUE TITLE
fetch_trades is ignoring `since` argument.

### ISSUE THREAD

**Issue by fccoelho** [ccxt/ccxt#1451]
- OS: Ubuntu Linux
- Programming Language version: Python
- CCXT version: 1.10.738
- Exchange: bitmex, bitfinex tested maybe others
- Method: fetch_trades

Fetch trades is ignoring the `since` parameter. No matter what data you pass to it, it returns the `n` most recent trades, and `n` varies from exchange to exchange.

**Comment by kroitor** [comment]
This is related to the following: https://github.com/ccxt/ccxt/issues/470
Your contributions are welcome: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

Will fix it for bitmex, bitfinex, where possible. Unfortunately bitmex does not specify their date-time format precisely in their docs.

I suggest moving this discussion to that topic, if you don't mind. Closing this as a duplicate for now. Feel free to reopen it or ask questions, if any.

**Comment by sergeijust** [comment]
I have the same problem with binance exchange. I use python. Any value for `since` is ignored
Even this return all orders: `exchange.fetch_orders(symbol, since=time.time())`
