### ISSUE TITLE
Bybit fetch_total_balance() returns everything as 0

### ISSUE THREAD

**Issue by Vamaka12** [ccxt/ccxt#14528]
- OS: Windows 10
- Programming Language version: Python 3.10
- CCXT version: 1.91.43

I am trying to get my spot balance on Bybit
But everything is just 0

I was trying before on Waves Exchange and everything was working perfectly
Am I doing something wrong or it's a bug?

```
import ccxt

bybit = ccxt.bybit({
    'apiKey': '',
    'secret': '',

})


trade_symbol = 'BTC/USDT:USDT'

bybit.load_markets()


while True:
    print(bybit.fetch_total_balance())
```

```
{'ADA': 0.0, 'BIT': 0.0, 'BTC': 0.0, 'DOT': 0.0, 'EOS': 0.0, 'ETH': 0.0, 'LTC': 0.0, 'LUNA': 0.0, 'MANA': 0.0, 'SOL': 0.0, 'USDT': 0.0, 'XRP': 0.0}
{'ADA': 0.0, 'BIT': 0.0, 'BTC': 0.0, 'DOT': 0.0, 'EOS': 0.0, 'ETH': 0.0, 'LTC': 0.0, 'LUNA': 0.0, 'MANA': 0.0, 'SOL': 0.0, 'USDT': 0.0, 'XRP': 0.0}
{'ADA': 0.0, 'BIT': 0.0, 'BTC': 0.0, 'DOT': 0.0, 'EOS': 0.0, 'ETH': 0.0, 'LTC': 0.0, 'LUNA': 0.0, 'MANA': 0.0, 'SOL': 0.0, 'USDT': 0.0, 'XRP': 0.0}
```

**Comment by carlosmiei** [comment]
Hello @Vamaka12,
In the past, Bybit was a derivatives-only exchange, so by default will load the derivatives info such as balance, markets, etc.

You can easily change that by setting the `defaultType` as 'spot' upon instantiating it:

```Python

exchange = ccxt.bybit({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
     'options': {
         'defaultType': 'spot',
     },
})
```
Let us know if that does not solve it!

**Comment by Vamaka12** [comment]
@carlosmiei 
Thank you very much, That worked perfectly!

**Comment by Vamaka12** [comment]
@carlosmiei H again, I have a question. Is there a function to get RSI indicator (like the one at Tradingview) data or something similar?

**Comment by carlosmiei** [comment]
@Vamaka12 Hello, you CCXT itself does not provide any indicator, only trading information (ohlcv, tickers, orderbook, etc) in a unified and very easy-to-process format, so calculating indicators like RSI with it is pretty simple too. Please checkout this example: https://github.com/ccxt/ccxt/blob/master/examples/py/rsi.py

**Comment by Vamaka12** [comment]
@carlosmiei Thanks, I am not home now, I will let you know if I will have any problem with it.
