### ISSUE TITLE
definion of precision from exchange.markets[currency] vary in exchanges

### ISSUE THREAD

**Issue by kjnh10** [ccxt/ccxt#14524]
- OS: Linux
- Programming Language version: Python 3.8
- CCXT version: 1.91.43

```
import ccxt
binance = ccxt.binace()
bybit = ccxt.bybit()
print(binance.markets['ILV/USDT']['precision']['amount'])
print(bybit.markets['ILV/USDT:USDT']['precision']['amount'])
```

This returns
```
3
0.01
```

But I think this should be
```
3
2
```

**Comment by ttodua** [comment]
We are migrating into `TICK_SIZE` precisions, the only `binance` (and few ones) remain which has DIGITS. 
So, in opposite, soon you will see like:
```
0.001 (instead of 3)
0.01 (instead of 2)
```

To know which exchange uses which mode for precisions, try: `exchange_instance.precisionMode` (which should be 0/1/2 : DECIMAL_PLACES/SIGNIFICANT_DIGITS/TICK_SIZE ).

Let us know if that doesn't clarify your concern or you have other issues with CCXT.

**Comment by kjnh10** [comment]
Thanks for the reply.

bybit_instanceprecisionMode returns 4. what does this mean?

**Comment by kjnh10** [comment]
<img width="189" alt="image" src="https://user-images.githubusercontent.com/6933428/182404917-bb7777e8-0be8-42fa-863a-c9fec3e2c2e5.png">

**Comment by kjnh10** [comment]
I understood that I should write like below. Thanks

```
from ccxt.base.decimal_to_precision import TICK_SIZE, DECIMAL_PLACES, SIGNIFICANT_DIGITS

# some code

if exchange.precisionMode == TICK_SIZE:
......
```

**Comment by carlosmiei** [comment]
Hello @kjnh10, can you please check this out https://docs.ccxt.com/en/latest/manual.html#precision-and-limits? I think that will answer most of your questions.

**Comment by ttodua** [comment]
> I understood that I should write like below. Thanks
> 
> ```
> from ccxt.base.decimal_to_precision import TICK_SIZE, DECIMAL_PLACES, SIGNIFICANT_DIGITS
> 
> # some code
> 
> if exchange.precisionMode == TICK_SIZE:
> ......
> ```

sorry my bad, different languages (js/py/php) have different number for those constants, so I confirm that the best method to compare them is what you have quoted.
