### ISSUE TITLE
What is the difference between fetch_my_trades and fetch_trades

### ISSUE THREAD

**Issue by proskurin** [ccxt/ccxt#14529]
These two methods look like similar but fetch_trades yields way more records? Any difference between these two?

**Comment by carlosmiei** [comment]
Hi @proskurin, yes there is one major difference.

`fetchTrades` returns public trades whereas `fetchMyTrades` is a private endpoint and returns only your own trades.

Check this out:
https://docs.ccxt.com/en/latest/manual.html#public-trades
https://docs.ccxt.com/en/latest/manual.html#my-trades

**Comment by proskurin** [comment]
Thank you very much, @carlosmiei ! 
I have one more question. I am trying to fetch_my_trades from Binance, but it yields empty results for me. Despite the fact that I have trades in my system (

```
all_trades = []
for symbol in tqdm(markets):
    since = start_ms
    exit_flag = False
    while exit_flag is False:
        trades = exchange_client.fetch_my_trades(symbol, since=since, limit=None)
        if len(trades) != 0:
            last_trade = trades[-1]
            since = last_trade['timestamp'] + 1 # Add one millisecond to start a new page.
            all_trades.extend(trades)
        else:
            exit_flag = True
```

**Comment by proskurin** [comment]
It is related to this issue: https://github.com/ccxt/ccxt/issues/14513

**Comment by carlosmiei** [comment]
@proskurin What do you get if you don't pass the `since` argument?

**Comment by proskurin** [comment]
Still 0 trades(

**Comment by ttodua** [comment]
@proskurin 
to add 2 quick notes:
1) ensure you are referring same market types (i.e. you have trades on spot market, not futures) and instance is not initiated with future/swap type.
2) when fetching trades, there might be some "covered period" from since, if I correctly recall, try setting the `since` within 7 days range of your trades, and they might appear there.

**Comment by ttodua** [comment]
I think I will mark the question as closed, because ccxt works as expected. please post more details when you have an issue , by looking through: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
