### ISSUE TITLE
 Question - ccxt.browser.js contents 

### ISSUE THREAD

**Issue by kumboo** [ccxt/ccxt#1453]
Hi there, I'm using ccxt.browser.js version 1.10.810. 
I'm wondering what is that huge piece of base64 encoded data in browserified JS file and what were reasons to encode it that way. Can one safely delete that part?

Thanks

**Comment by michnovka** [comment]
its a source map. [check this](https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/) for more information. It is safe to delete

**Comment by kroitor** [comment]
Thanks, @michnovka !

@kumboo feel free to ask if you still have questions on this. Closing it for now as @michnovka has already answered correctly.

**Comment by kumboo** [comment]
Thank you @michnovka , @kroitor !
