### ISSUE TITLE
fetchpositions stoploss info

### ISSUE THREAD

**Issue by flieks** [ccxt/ccxt#14531]
I am testing with bybit and i can see the `stop_loss` in the `info` object. 
Are there plans to move this to the unified api and put on the root ?

**Comment by samgermain** [comment]
> I am testing with bybit and i can see the `stop_loss` in the `info` object. Are there plans to move this to the unified api and put on the root ?

I'm guessing that we probably won't, because these values are not returned in the response from very many exchanges, but I created a [PR](https://github.com/ccxt/ccxt/pull/14537) to add these fields and @kroitor @frosty00 and @carlosmiei can make the final decision

**Comment by samgermain** [comment]
I thought about this a bit more, and it might be a good idea to merge PR #14537 , because the fields are there in 3/12 of the exchanges that have fetchPositions that I looked at so far

**Comment by flieks** [comment]
thanks alot, i hope this gets merged.. i see you added support for 12 exchanges that have it

**Comment by samgermain** [comment]
> thanks alot, i hope this gets merged.. i see you added support for 12 exchanges that have it

9 of those exchanges just set the value to undefined

**Comment by flieks** [comment]
ow ok thats too bad
