### ISSUE TITLE
Enable NodeSecurity

### ISSUE THREAD

**Issue by thijstriemstra** [ccxt/ccxt#1454]
https://nodesecurity.io/ provides security scans for node packages in package.json, would be nice to enable this check.

**Comment by thijstriemstra** [comment]
fyi, there are no files or configs that need to be added to the repository, you simply enable it on their website.

**Comment by kroitor** [comment]
[![NSP Status](https://nodesecurity.io/orgs/ccxt/projects/856d3088-8b46-4515-9324-6b7cd2470522/badge)](https://nodesecurity.io/orgs/ccxt/projects/856d3088-8b46-4515-9324-6b7cd2470522)

**Comment by kroitor** [comment]
https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting
