### ISSUE TITLE
How can I fetch single currency's balance from margin or fund?

### ISSUE THREAD

**Issue by avatar-lavventura** [ccxt/ccxt#14554]
I want to fetch balance of single currency (like: `btc`) from `margin` or `fund` and don't want to fetch other balances that I know that they are zero.

I have tried:

```output = await exchange.spot.fetch_balance(params={"type": "margin")``` which works but return all the currencies even they are zero.

When I tried:
```
output = await exchange.spot.fetch_balance(params={"type": "margin", "currency": "btc"})
```

which gives: `binance {"code":-1101,"msg":"Too many parameters; expected '3' and received '4'."}` error message

**Comment by carlosmiei** [comment]
Hello @avatar-lavventura,

You can't do that filtering on the API level, but you can easily do it on your side because we're returning a dictionary indexed by currencies.

Example:
```Python
output = await exchange.spot.fetch_balance(params={"type": "margin")
my_currency="BTC"
my_balance = output[my_currency]
my_balance_free = output['free'][my_currency]
my_balance_used = output['used'][my_currency]
```
Does this solve your issue?

**Comment by avatar-lavventura** [comment]
@carlosmiei No matter what, we have to fetch complete `dict` of balances, right?

**Comment by carlosmiei** [comment]
@avatar-lavventura Right, binance does not allow passing a "filtering coin" to this endpoint, as you can see here: https://binance-docs.github.io/apidocs/spot/en/#query-cross-margin-account-details-user_data

**Comment by avatar-lavventura** [comment]
@carlosmiei Ah I got it that's sad. Does it all in any other endpoints like `fund`?
