### ISSUE TITLE
Poloniex big changes in API

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#14565]
https://twitter.com/Poloniex/status/1554309498004709376?t=GosDV306XoZFyKHNKWdSyg&s=35
I have no time to check now, but I see, that many endpoints work not like before, for example `fetchBalance` returns:

```
  timestamp: undefined,
  datetime: undefined,
  EXCHANGE: { free: undefined, used: undefined, total: undefined },
  MARGIN: { free: undefined, used: undefined, total: undefined },
  LENDING: { free: undefined, used: undefined, total: undefined },
  free: { EXCHANGE: undefined, MARGIN: undefined, LENDING: undefined },
  used: { EXCHANGE: undefined, MARGIN: undefined, LENDING: undefined },
  total: { EXCHANGE: undefined, MARGIN: undefined, LENDING: undefined }
```

**Comment by redwoz** [comment]
from around an hour ago, requests are failing:

`ExchangeNotAvailable: poloniex GET https://poloniex.com/public?command=returnTicker 500 Internal Server Error {
  "code" : 500,
  "message" : "System error"
}`

**Comment by Djusk8** [comment]
> https://twitter.com/Poloniex/status/1554309498004709376?t=GosDV306XoZFyKHNKWdSyg&s=35 I have no time to check now, but I see, that many endpoints work not like before, for example `fetchBalance` returns:
> 
> ```
>   timestamp: undefined,
>   datetime: undefined,
>   EXCHANGE: { free: undefined, used: undefined, total: undefined },
>   MARGIN: { free: undefined, used: undefined, total: undefined },
>   LENDING: { free: undefined, used: undefined, total: undefined },
>   free: { EXCHANGE: undefined, MARGIN: undefined, LENDING: undefined },
>   used: { EXCHANGE: undefined, MARGIN: undefined, LENDING: undefined },
>   total: { EXCHANGE: undefined, MARGIN: undefined, LENDING: undefined }
> ```

I can confirm that method parce_balance() in poloniex exchange doesn't work properly from yesterday. Exchange returns only separate balances for EXCHANGE, MARGIN and LENDING accounts now.

<img width="574" alt="изображение" src="https://user-images.githubusercontent.com/35682654/182577962-cf065ceb-e477-40d3-be5b-9178c7663909.png">

For temporary solution I override `parse_balance()` method to parce only EXCHANGE account balances.

```
    def parse_balance(self, response):

++      response = response['exchange']  # Add this line

        result = {
            'info': response,
            'timestamp': None,
            'datetime': None,
        }
       ....
       ....
```

**Comment by sc0Vu** [comment]
They've upgraded their api service, also upgrade signing method.

We'll integrate their new api soon.

**Comment by page1** [comment]
Thank you for working through this update. My system is now throwing:

`requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://poloniex.com/public?command=returnCurrencies`

From `load_markets()` in python.

**Comment by LefterisJP** [comment]
> They must have changed something.

Their entire API is changed. They claim they have kept their old API but it's not working.

What's funnier we (rotki) have a direct integration (not using ccxt) so we tried to use their new API. Stuff don't really work: https://twitter.com/LefterisJP/status/1555184278597672961

So api key is recognized okay by the server, new signature authentication also fine, but trades return empty list, while the account in question should have had hundreds of trades in history.

When you guys integrate I am curious to see if you hit the same issues. Will try to also post if we find out what's wrong in case that helps you or anyone else.

**Comment by LefterisJP** [comment]
So @sc0Vu in case it helps here is our implementation of the poloniex api changes in rotki: https://github.com/rotki/rotki/pull/4646
More specifically this commit contains the bulk: https://github.com/rotki/rotki/pull/4646/commits/21ce47fb392b9afd1bb5e084b11a7010dc9cc67c


The new api docs are accurate but one **really** ugly detail is that for historical trades query we now can only query up to 90 days in the past. So this is a loss of functionality in comparison to the previous API.

**Comment by LefterisJP** [comment]
> query up to 90 days in the past.

That may not be correct. The 90 days is what poloniex told me in Twitter but the test trade I made with them 12 days ago is no longer retrievable via the api.

**Comment by ttodua** [comment]
@ndubel can you tell, why you think this issue was better to get closed?

**Comment by ndubel** [comment]
as I see https://github.com/ccxt/ccxt/pull/14592 was merged, also Poloniex is working fine for me

**Comment by chasovskih-grisha** [comment]
There are no sense yo use this library, because [free poloniex trading bot](https://darkbot.io) already exists... no code required
