### ISSUE TITLE
Python Requests’ module uses ~/.netrc and this might affect APIs of some exchanges

### ISSUE THREAD

**Issue by avibrazil** [ccxt/ccxt#14560]
- OS: Linux
- Programming Language version: Python
- CCXT version: 1.91.39

If you have some content on `~/.netrc`, it might affect how some exchanges respond. I had problems with KuCoin.

Ways to reproduce the problem:

1. On Linux, create `$HOME/.netrc` with content:
   ```
   default
   login abc123
   password 123abc
   ```
1. Run a [simple anonymous CCXT script to get KuCoin ticker](https://github.com/ccxt/ccxt/blob/master/examples/py/tickers.py) prices:
   ```
   python tickers.py kucoin
   ```
1. Watch it fail

I reported this problem in [another bug as a KuCoin problem](https://github.com/ccxt/ccxt/issues/14505), but I'm opening it here with a more generic language. I think CCXT must force `requests` to not use `~/.netrc` or at least document how sensible some exchanges might be to this old Unix file.

**Comment by frosty00** [comment]
@avibrazil can confirm this affects both ubuntu and freebsd
