### ISSUE TITLE
Binance withdrawal not including asset

### ISSUE THREAD

**Issue by Deusing** [ccxt/ccxt#1457]
- OS: Ubuntu
- Programming Language version: PHP
- CCXT version: 1.10.810
- Exchange: Binance
- Method: withdraw

I fire a withdraw command with

```
$exchange->withdraw("XRP", 25, 'abcabcacbacbacbacbacbacb', 123123123123);
```

and when enabling debug see

```
Request:
Array
(
    [0] => POST
    [1] => https://api.binance.com/wapi/v3/withdraw.html?timestamp=1516758889295&recvWindow=100000&asset=XRP&address=abcabcacbacbacbacbacbacb&amount=25&name=abcabcacbacbacbacbacbacb&addressTag=123123123123&signature=aabbccdd12313123132
    [2] => Array
```

when i look at https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#signed-endpoint-examples-for-post-wapiv3withdrawhtml

looks like the asset=XRP is not pushed

**Comment by kroitor** [comment]
Sorry, what is not pushed where?

![asset-binance](https://user-images.githubusercontent.com/1294454/35310939-ff478354-00c4-11e8-9900-745c0cf8ea24.jpg)

**Comment by Deusing** [comment]
Thanks for your quick answer. I must have overlooked it indeed.
Than I am only puzzled why nothing seems to happen, no error, but also no (pending) withdrawal in Binance. Any idea?

**Comment by Deusing** [comment]
Hmm, now it does show up as supposed, i think there might be some delay in showing the withdrawal in Binance side, but it did show up ultimately. Closing this, thanks!
