### ISSUE TITLE
help me to load recent 3 ohlcv datas in fairdesk with python 

### ISSUE THREAD

**Issue by duckduck33** [ccxt/ccxt#14574]
I'm trying to load the information of the last 3 candles ohlcv with Python.
But it failed.
my code is as follows.

**resp = exchange.fetch_ohlcv( symbol='btcusdt', interval='15m', from_ts=-3, to_ts=-1,limit=3)
pprint.pprint(resp)**

and The results are as follows.
**{'data': None,
 'error': 'Internal Server Error, Please try again.',
 'status': 500}**

How should I set 'from_ts=???' and 'to_ts=???' to load candles recent in order? 
Help me.

**Comment by carlosmiei** [comment]
Hello @duckduck33,

`fetch_ohlcv` supports two different filters, `from` and `limit`.  The first one refers to the timestamp (in milliseconds) that filters candles created after that time. The latter represents a numeric limit that caps the number of candles returned.


If you want to get only the last three candles, you can simply do:
```Python
 exchange.fetch_ohlcv( symbol='btcusdt', interval='15m', None , 3)
```
You can read more about it here: https://docs.ccxt.com/en/latest/manual.html#ohlcv-structure

Additionally, you can also check some of our examples:
- [async-binance-usdm-fetch-continuous-klines-ohlcv.py](https://github.com/ccxt/ccxt/blob/master/examples/py/async-binance-usdm-fetch-continuous-klines-ohlcv.py)
- [binance-fetch-ohlcv.py](https://github.com/ccxt/ccxt/blob/master/examples/py/binance-fetch-ohlcv.py)
- [fetch-ohlcv-sequentially.py](https://github.com/ccxt/ccxt/blob/master/examples/py/fetch-ohlcv-sequentially.py)
- ...

**Comment by frosty00** [comment]
answered by @carlosmiei
