### ISSUE TITLE
Huobi Pro wrong exchange name

### ISSUE THREAD

**Issue by FabianWassermann** [ccxt/ccxt#14570]
I noticed that the exchanges with id ```huobi``` and ```huobipro``` have the same name ```Huobi```.

- OS: macOS Monterey 12.4
- Programming Language version: Node 18.6
- CCXT version: 1.91.46

**Comment by samgermain** [comment]
They don't when I check
```
import ccxt

huobi = ccxt.huobi()
print(huobi.id)
huobipro = ccxt.huobipro()
print(huobipro.id)

```
prints
```
huobi
huobipro
```

**Comment by FabianWassermann** [comment]
As I said: The ```id``` is different but the name is the same.

For Example: ```coinbase``` has the name ```Coinbase``` and ```coinbasepro``` has the name ```Coinbase Pro```.
But for Huobi it´s: ```huobi``` has the name ```Huobi``` and ```huobipro``` has the name ```Huobi```.

As I said: Exchanges with id ```huobi``` and ```huobipro``` have the same name ```Huobi```

Thanks!
