### ISSUE TITLE
CoinbasePro Closing Down

### ISSUE THREAD

**Issue by pottertech** [ccxt/ccxt#14571]
What should we do about CoinbasePro closing down and migrating to Coinbase?

I keep getting asked by Coinbase to transfer my Pro funds but I dont want to do that until I know we can get an API key generated that CCXT can use.

Any thoughts on what we should do?

**Comment by carlosmiei** [comment]
Hello @pottertech, 
CCXT supports Coinbase as well, so it should be straightforward to generate an API key to use it with CCXT.

**Comment by pottertech** [comment]
What I have read about the closing of CoinbasePro stated that the Advanced Trading feature might have its own API and Websockets.

**Comment by samgermain** [comment]
> I keep getting asked by Coinbase to transfer my Pro funds but I dont want to do that until I know we can get an API key generated that CCXT can use.

That might not be possible, I have not been able to find an API for coinbase advanced trading, but expect that it will be released in the future. After it is released, it will take at least some time for CCXT to write the implementation for it. 

I don't think coinbase has set a definitive date for when coinbase pro will shut down; maybe this date is in the emails they send you?

You should definitely transfer your assets from coinbase pro to coinbase before the deadline to avoid the risk of losing them.

**Comment by LefterisJP** [comment]
From what I understand coinbase pro will just be sunset and all users be moved into coinbase advanced trading. So I don't think there is any risk of asset loss. https://blog.coinbase.com/hello-advanced-trade-goodbye-coinbase-pro-5b0715b03ef0

I suppose we are all waiting until they document how to use the new Advance Trading API **and** how users will be able to access old CBPro history from there.

**Comment by samgermain** [comment]
> From what I understand coinbase pro will just be sunset and all users be moved into coinbase advanced trading. So I don't think there is any risk of asset loss. https://blog.coinbase.com/hello-advanced-trade-goodbye-coinbase-pro-5b0715b03ef0

It looks like that's correct

> For customers holding funds on Coinbase Pro, there is no action to take- funds will remain safe on Coinbase. Meanwhile, customers are welcome to begin using [Advanced Trade](http://www.coinbase.com/advancedtrading) on the Coinbase mobile app and Coinbase.com.

It looks like Coinbase Pro will shutdown at some point in 2022

> As we continue to add more features to Advanced Trade on Coinbase, we will sunset Coinbase Pro later this year.

I can't find a date for when the Coinbase Advanced Training API will be released, but they did post instructions on how to transfer to Coinbase Advanced Trading

> To get started, customers will need to fund their Coinbase accounts if they haven’t already by depositing funds or transferring funds directly from Coinbase Pro by following these steps:
> 
> 1. Log into [Coinbase Pro](https://pro.coinbase.com/) and select “Portfolios”
> 2. Choose “Withdraw” on the top right
> 3. Select the cryptocurrency you want to transfer, or “All Portfolios” to transfer all assets to Coinbase.com
> 4. Choose “Transfer to Coinbase”
> 5. Then visit [Coinbase.com/advanced-trade](https://coinbase.com/advanced-trade) or tap the “Advanced Trade” drop down from the Trade tab in the Coinbase mobile app to get started with Advanced Trade
> 
> To learn more about Advanced Trade, check out the latest [tips and tutorials](https://www.coinbase.com/advanced-trade/tutorials) on Coinbase Learn,

**Comment by pottertech** [comment]
Based on this link [https://forums.coinbasecloud.dev/t/advanced-trading-api-release-date/1145/6](url) Coinbase is saying they will not "sunset" the CoinbasePro APIs when they merge user accounts into their "Advanced Trade" feature.  Coinbase will keep the CoinbasePro APIs functional until they have completed and released new APIs.

**Comment by pottertech** [comment]
I got the following response from Coinbase so I am feeling better about the situation:

Thank you for contacting Coinbase Support. We acknowledge your concern in relation to the upcoming shutdown of Coinbase Pro and we understand that you are using Coinbase Pro API for trading automation on your Coinbase account. We do recognize how important it is for you to be on top of your account. Please know that we strive to provide an accurate response with regards to this matter.

Please be advised that customers who connect their Coinbase API to other websites and create order on Pro from other websites will take longer to migrate their accounts to Retail Advanced Trading.

In line with this, we would like to inform you that we are currently building REST and websocket protocols on Advanced Trade so that customers can use Advanced Trade under one unified Coinbase account. We will not begin sunsetting Pro APIs until we have the replacement ready for our current customers.

Once it's ready, we'll notify our Coinbase Pro API customers to start moving their Pro balances to Advanced Trade on Coinbase. Until then, customers can continue to use Coinbase Pro APIs for their trading needs.

Please be assured that our team is still working on this and will keep you updated.

Regards,
Coinbase Support

**Comment by StevenProhashing** [comment]
Coinbase Advanced trading API is now available in public beta.
Coinbase Pro is going to be sunsetted in early 2023.
https://docs.cloud.coinbase.com/advanced-trade-api/docs
https://forums.coinbasecloud.dev/t/about-the-advanced-trade-api-category/1743
