### ISSUE TITLE
Phemex `fetch_positions` does not support phemex official symbol

### ISSUE THREAD

**Issue by takami-ml** [ccxt/ccxt#14584]
Phemex `fetch_positions` does not support phemex official symbol

## versions
* OS: Debian 11
* Programming Language version: python 3.8.12
* CCXT version: 1.91.68

### setup
```
import ccxt

ccxt_exchange = ccxt.phemex({
    'apiKey': ...,
    'secret': ...,
})
```

### fetch_positions does not support uXXXUSD format
```
ccxt_exchange.fetch_positions(symbols=['uBTCUSD']) # => returns `[]`
ccxt_exchange.fetch_positions(symbols=['BTC/USD:USD']) # => returns position structured response
```

### fetch_positions does not support neither inverse formats
```
ccxt_exchange.fetch_positions(symbols=['BTCUSD']) # => returns `[]`
ccxt_exchange.fetch_positions(symbols=['BTC/USD:BTC']) # => returns `[]`
```

**Comment by carlosmiei** [comment]
Hello @takami-ml 

> ccxt_exchange.fetch_positions(symbols=['uBTCUSD']) # => returns `[]`
> ccxt_exchange.fetch_positions(symbols=['BTC/USD:USD']) # => returns position structured response

Can you double-check this? I've just tested and worked fine with both formats, unified and exchange-specific.


> fetch_positions does not support neither inverse formats
> ccxt_exchange.fetch_positions(symbols=['BTCUSD']) # => returns `[]`
> ccxt_exchange.fetch_positions(symbols=['BTC/USD:BTC']) # => returns `[]`

By default will try to load "linear contracts" to fetch inverse contracts (BTC settled in this case), please provide the settle currency as `code` inside params.

Something like this:
```Python
ccxt_exchange.fetch_positions(symbols=['BTC/USD:BTC'], {'code':'BTC'})
```

**Comment by takami-ml** [comment]
@carlosmiei 

Thank you for the information.

> Can you double-check this? I've just tested and worked fine with both formats, unified and exchange-specific.

I'm sorry,  this one was my mistake. (I just had an inverse position, not linear.)
I confirmed it worked as expected.

> By default will try to load "linear contracts" to fetch inverse contracts (BTC settled in this case), please provide the settle currency as code inside params.

When I set `code` to BTC, it worked.
I did not understand the `defaultSubType` option and `code` params. Thanks for the information.

In conclusion, in both cases, there was no problem. I am very sorry to have used your time!

**Comment by carlosmiei** [comment]
@takami-ml no problem at all, I'll close this issue then, let us know if anything! 🙂
