### ISSUE TITLE
Poloniex fetchBalance not working

### ISSUE THREAD

**Issue by ggecy** [ccxt/ccxt#14581]
- OS: MacOS 12.4
- Programming Language version: typescript 3.9.2
- CCXT version: 1.91.66

Calling fetchBalance() on poloniex exchange doesn't work anymore - the structure of the poloniex rest call response has changed and now the balances are wrapped inside an `exchange` property.

**Comment by sc0Vu** [comment]
Related to #14565

We'll integrate to their new api.
