### ISSUE TITLE
Kraken timestamp mismatch - fetchTrades since parameter bug

### ISSUE THREAD

**Issue by chageman8** [ccxt/ccxt#14590]
**Kraken uses nanosecond UNIX timestamps** for all their since parameters in API calls across the exchange, but **CCXT uses millisecond timestamps**. This could create issues across a number of methods but I've specifically run into the issue with fetchTrades. Is there any way we can **integrate a timestamp adjustment for the Kraken exchange** such that **millisecond timestamps from CCXT are converted to nanoseconds before being provided as a parameter** (i.e. just multiply but 10^6)? This is something I can integrate in my own code but thought it would be useful for all CCXT users to have this automatically adjusted.

**Comment by carlosmiei** [comment]
Hello @chageman8,
Actually, we're converting it to nanoseconds, so I'm not quite sure what's the issue yet


As a workaround, you can do this to provide your raw timestamp (assuming you're using the Python version):

````Python
since = None
params = {
    'since' : YOUR_TIMESTAMP_HERE
}
trades = exchange.fetchTrades (symbol, None, None, params )
```

**Comment by samgermain** [comment]
I'm going to close this issue because it looks like it's answered and it's been some time since a response
