### ISSUE TITLE
[KuCoin Future] Best ways to avoid "Too Many Requests" Error when submitting order  -> simple question 

### ISSUE THREAD

**Issue by YuxinSUN89** [ccxt/ccxt#14597]
Hey Team,
Apologies if this might be a duplicate ticket. However, I did find any solution for this issue.

I am trying to create  two market orders in a row. First close old long position, and then open a new long position.

OS: Mac OS
Programming Language version: Python
CCXT version: 1.84.70

```
futures_exchange = ccxt.kucoinfutures({
    'apiKey' : config.KUCOIN_API_KEY,
    'secret' : config.KUCOIN_API_SECRET,
    'enableRateLimit': True, 
    'password': config.KUCOIN_PASS_PHRASE,
})

# First close old long positions
try:
    order = futures_exchange.create_order(symbol='ETH/USDT:USDT', type='market', side='sell',amount=int(100),   params=config.params)
    print('old position closed')
except:
    print('ooops, cannot close position')

# Then open a new  long positions
try:
    order = futures_exchange.create_order(symbol='BTC/USDT:USDT', type='market', side='buy',amount=int(20),   params=config.params)
    print('new position opened')
except Exception as e:
     print('ooops, cannot open position')
     print (e)

```

Output message:
```
old position closed
kucoinfutures POST [https://api-futures.kucoin.com/api/v1/orders](https://protect-eu.mimecast.com/s/JNBJCQ6KmT6M097EFPYk-f?domain=api-futures.kucoin.com) 429 Too Many Requests {"code":"429000","msg":"Too Many Requests"}
```

Message says got old position closed, but I could not open new position . 
Whats the best way to avoid "Too Many Requests" when submitting orders here ? 

I have two potential solutions

1. Use 'while-try' loop 

```
attempts = 0
while attempts <= 100: 
    try:        
        order = futures_exchange.create_order(symbol='BTC/USDT:USDT', type='market', side='buy',amount=int(20),   params=config.params)
    except Exception as e:
        print('Error try again !')
        print (e)
        attempts += 1
        time.sleep(5)
        continue
    break
```
I am worried that this would keep submitting duplicated orders. 
For example in the first attemp it manages to submit 10 order, and then restart the loop and submit another 20 orders.
In then end, I open 30 in long position intotal. 

2. Just add time.sleep(5) between two orders

```
time.sleep(5) 
```
Its possible that I still get  "Too Many Requests"  after the sleep (?)

Guys, any thought ? Thanks

**Comment by samgermain** [comment]
@DoctorSlimm It sounds like this might be an issue with the rate limits set on the CCXT `kucoinfutures` class

**Comment by DoctorSlimm** [comment]
Will take a look

**Comment by YuxinSUN89** [comment]
Thanks @samgermain  @DoctorSlimm  . 

I did a few experiment. 
I submitted 4 market buy order in a row, with each order followed by 'time.sleep(5)'. 
Guess what? 
Only the first order and fourth order got executed. 

For the second and third order I got "Too Many Requests" Error. 
This seems very odd. 

If I want to execute every order I submitted, then I have to Use 'while-try' loop mentioned above. 

Looks like something is off here.

**Comment by DoctorSlimm** [comment]
@YuxinSUN89  After extensive testing, it seems that there is something wrong on their side with the `POST /v1/orders` endpoint. I have contacted them and hope they will get back to me soon.

**Comment by RoscoeTheDog** [comment]
Thanks for this thread. When I get more than 5 or 6 bots running of a singular account then I start to run into the same message/issue. I thought it'd be worth mentioning in my case that each bot does about 5-6 checks per iteration to check for safety order status, take profit status and position status amonst other market stuffs, but all bots are using the same CCXT object instance with it's built-in rate limiting. It seems these bots will run fine for a minute or so and execute these checks within a reasonably fast rate (5-6 requests within a 2-3 second time frame) but then suddenly, **all** bots will report the 429000 code for around 35-40 seconds before finally allowing traffic through once more.

![image](https://user-images.githubusercontent.com/54086262/185568866-c8440c03-87ce-4d17-bfac-75b068a12ec0.png)

Do we have a work around other than increasing the rate limit parameter when creating the exchange obj?

**Comment by RoscoeTheDog** [comment]
Do we have an update to this issue? I saw @DoctorSlimm was unassigned 6 days ago, but I was hoping for a bug fix solution instead of just a temporary workaround. I use Kucoin Futures mostly and want to run a lot of strategies simultaneously.

**Comment by philipperemy** [comment]
@RoscoeTheDog no solution you have to bite the dust.

**Comment by ttodua** [comment]
I have been looking in old issues and found this one, if anyone still experiences this, let us know.

**Comment by ttodua** [comment]
if anyone still experiences this, let us know.
