### ISSUE TITLE
How to create TP/SL orders after creating limit order 

### ISSUE THREAD

**Issue by buckydroid** [ccxt/ccxt#14595]
For example let's say the current price is 80 and I want to create a new limit order at 100. But after creating limit order I want to set a stop loss at 95 and take profit at 105.

But when I create new tp or sl order after creating the limit order, I get message that the order would trigger immediately. So is there any way to do that currently using binance api?

**Comment by DoctorSlimm** [comment]
@buckydroid 

After doing some digging into the binance API I can tell you that:

1. Binance only allows placing stop-orders with a stop-price below the last market price
=> this means that you cannot create an order to buy at a price which is currently above the market price without the order executing immediately at the best current price.
3. therefore your take-profit order needs to be a limit-sell order 
4. Binance does not allow placing limit orders without currently holding the amount of the asset in your account.

So your Strategy for Binance will not necessarily work.

However, alternatively, I can suggest, you run a script which checks the last price, and then creates a market order at 100, followed by an OCO order to implement the upper and lower stop limits. 
* OCO creates two orders at once, and one will cancel the other if it is executed
* Meaning you dont need to worry about cancelling stand-alone stop orders after one is executed
* it combines a limit order at your upper bound to act as a take-profit, 
* and a stop-limit order at the lower bound to act as your stop-loss

This can be done like so: 

```Python
import ccxt

binance = ccxt.binance ({'apiKey': 'APIKEY', 'secret': 'SECRET'})

symbol = 'DOGE/USDT'
amount = 200

# fetch ticker and last prices
ticker = binance.fetch_ticker(symbol)
last = ticker['last']

stop_loss_price = last*0.8
take_profit_price = last*1.2

# create market buy order
market_buy_order = binance.create_order(symbol, 'market', 'buy', amount)

# create OCO order
params = {
        'symbol': binance.market(symbol)['id'],
        'side': 'SELL',
        'quantity': binance.amount_to_precision(symbol, amount),
        'price': binance.price_to_precision(symbol, take_profit_price),
        'stopPrice': binance.price_to_precision(symbol, stop_loss_price),
        'stopLimitPrice': binance.price_to_precision(symbol, stop_loss_price*1.01),  # to ensure it executes
        'stopLimitTimeInForce': 'GTC',
}

oco_order = binance.privatePostOrderOco(params)
```

**Comment by thucungcuatoi** [comment]
> @buckydroid
> 
> After doing some digging into the binance API I can tell you that:
> 
> 1. Binance only allows placing stop-orders with a stop-price below the last market price
>    => this means that you cannot create an order to buy at a price which is currently above the market price without the order executing immediately at the best current price.
> 2. therefore your take-profit order needs to be a limit-sell order
> 3. Binance does not allow placing limit orders without currently holding the amount of the asset in your account.
> 
> So your Strategy for Binance will not necessarily work.
> 
> However, alternatively, I can suggest, you run a script which checks the last price, and then creates a market order at 100, followed by an OCO order to implement the upper and lower stop limits.
> 
> * OCO creates two orders at once, and one will cancel the other if it is executed
> * Meaning you dont need to worry about cancelling stand-alone stop orders after one is executed
> * it combines a limit order at your upper bound to act as a take-profit,
> * and a stop-limit order at the lower bound to act as your stop-loss
> 
> This can be done like so:
> 
> ```python
> import ccxt
> 
> binance = ccxt.binance ({'apiKey': 'APIKEY', 'secret': 'SECRET'})
> 
> symbol = 'DOGE/USDT'
> amount = 200
> 
> # fetch ticker and last prices
> ticker = binance.fetch_ticker(symbol)
> last = ticker['last']
> 
> stop_loss_price = last*0.8
> take_profit_price = last*1.2
> 
> # create market buy order
> market_buy_order = binance.create_order(symbol, 'market', 'buy', amount)
> 
> # create OCO order
> params = {
>         'symbol': binance.market(symbol)['id'],
>         'side': 'SELL',
>         'quantity': binance.amount_to_precision(symbol, amount),
>         'price': binance.price_to_precision(symbol, take_profit_price),
>         'stopPrice': binance.price_to_precision(symbol, stop_loss_price),
>         'stopLimitPrice': binance.price_to_precision(symbol, stop_loss_price*1.01),  # to ensure it executes
>         'stopLimitTimeInForce': 'GTC',
> }
> 
> oco_order = binance.privatePostOrderOco(params)
> ```

Hi @DoctorSlimm 
This is solution for spot trading! In future trading don't allow OCO! :( Have any solution for Future Trading?

**Comment by ttodua** [comment]
late reply, but for future readers - 

1) for creating order with attached SL & TP (during submission), you can use: https://docs.ccxt.com/#/README?id=stoploss-and-takeprofit-orders-attached-to-a-position

2) if you already have an open position, you can use regular "close" orders with `stopLossPrice` : https://docs.ccxt.com/#/README?id=stop-loss-orders

3) if you have a pending limit order where you want to add SL & TP, then you can cancel that order and use `(1)` approach to place an order with SL & TP.
