### ISSUE TITLE
Binance support new sapi functions

### ISSUE THREAD

**Issue by koala974** [ccxt/ccxt#14591]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version: 1.91.64

```
Please can  U support new sapi functions like:
/sapi/v3/asset/getUserAsset
/sapi/v1/staking/productList
```

```
sapi_get_staking_productList not supported
```

**Comment by sc0Vu** [comment]
@koala974

We already add these api endpoints, try this:

```
binance.sapi_get_staking_productlist()
```

**Comment by koala974** [comment]
Thks works well with "productlist"Tried with "productList" didnt workDoes getuserasset function coming soon ?Le 5 août 2022 03:40, Peter Lai ***@***.***> a écrit :
@koala974
We already add these api endpoints, try this:
binance.sapi_get_staking_productlist()
