### ISSUE TITLE
request of IDE config export

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1460]
@kroitor can you share your IDE js format configuration mentioned in [wiki](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes) for phpStorm or WebStorm? that will be huge thanks.

**Comment by kroitor** [comment]
@jjhesk it's called "eslint" and using a *linter* it's a standard way of highlighting in most editors (integrates mostly anywhere).

- https://github.com/ccxt/ccxt/search?q=lint&type=Issues&utf8=✓
- https://github.com/ccxt/ccxt/search?q=eslint&type=Issues&utf8=✓
- https://github.com/ccxt/ccxt/blob/master/js/.eslintrc
- https://github.com/ccxt/ccxt/blob/master/js/base/.eslintrc.js

From here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes:

> Use the linter `npm run lint js/your-exchange-implementation.js` before you build. It will cover many (but not all) the issues, so manual checking will still be required if transpilation fails.

Does that answer your question?

**Comment by jjhesk** [comment]
@kroitor thank you.  it works
