### ISSUE TITLE
fetch_ohlcv function cannot get samples by setting "since" parameter.

### ISSUE THREAD

**Issue by Kmasato** [ccxt/ccxt#14614]
I cannot fetch the number of OHLCV samples set in the "since" parameter on fech_ohlcv func. 
When I set the 90 min for since parameter like a this code,  I could only get few data about 15 min ago.

For example,
I started this code at 1659878840000(07/08/2022, 22:27:20 JST), the out put is only two data like this.

[[1659882600000,
  3122562.0,
  3122562.0,
  3120698.0,
  3122541.0,
  0.6630000000000003],
 [1659883500000,
  3122541.0,
  3125011.0,
  3120974.0,
  3123439.0,
  3.2685345499999947]]

```
def GetUnixTimeMinutesAgo(minutes):
    dateTime = datetime.utcnow()
    unixTime = calendar.timegm(dateTime.utctimetuple())
    since = (unixTime - 60 * minutes) * 1000
    print(since)
    return since # [msec]

if __name__ == "__main__":
    print("Getting Simple Moving Average test")

    bitflyer = ccxt.bitflyer()
    bitflyer.apiKey = apikey.key
    bitflyer.secret = apikey.secret

    fromTime = GetUnixTimeMinutesAgo(90) # fetch the data from 90 min ago
    candleList = bitflyer.fetch_ohlcv(
        symbol="BTC/JPY",
        timeframe = "15m",
        since = fromTime
    )

    pprint(candleList)
```

This is output.
```
Getting Simple Moving Average test
1659878840000
[[1659882600000,
  3122562.0,
  3122562.0,
  3120698.0,
  3122541.0,
  0.6630000000000003],
 [1659883500000,
  3122541.0,
  3125011.0,
  3120974.0,
  3123439.0,
  3.2685345499999947]]
```

- OS: windows 10
- Programming Language version: 3.8.1
- CCXT version: 1.91.91

**Comment by sc0Vu** [comment]
It turns out they didn't provide api for k line, we simulate this api with trades data. They didn't use time when query trades (only id), the data may be incomplete...

**Comment by Kmasato** [comment]
Thank you for investigate. Then I will try to use the official API directly.
