### ISSUE TITLE
Info: New Poloniex limits

### ISSUE THREAD

**Issue by Curro666** [ccxt/ccxt#14617]
Many currencies have changed their decimals both in price and quantity. At this address the new limits appear with new fields.
 
   "priceScale" : 10,
    "quantityScale" : 0,
    "amountScale" : 8,
    "minQuantity" : "100",

extracted of 
https://api.poloniex.com/markets/

[ {
  "symbol" : "BTS_BTC",
  "baseCurrencyName" : "BTS",
  "quoteCurrencyName" : "BTC",
  "displayName" : "BTS/BTC",
  "state" : "NORMAL",
  "visibleStartTime" : 1659018816626,
  "tradableStartTime" : 1659018816626,
  "symbolTradeLimit" : {
    "symbol" : "BTS_BTC",
    "priceScale" : 10,
    "quantityScale" : 0,
    "amountScale" : 8,
    "minQuantity" : "100",
    "minAmount" : "0.00001",
    "highestBid" : "0",
    "lowestAsk" : "0"
  }

**Comment by sc0Vu** [comment]
Hi, thanks for your information, new poloniex api is related to #14565

We'll integrate soon.
