### ISSUE TITLE
seems like spread error

### ISSUE THREAD

**Issue by Showgofar** [ccxt/ccxt#14610]
- CentOS 7	
- php 5.5
- CCXT version: latest

Parse error: syntax error, unexpected '.' in /home/httpd/ccxt/php/Exchange.php](/ccxt/php/Exchange.php) on line 864

864 $merged = array_merge(...array_slice($args, 1));

PHP supported argument unpacking (AKA spread operator) since 5.6 
but its written that 5.4+ php required for ccxt
Thank you

**Comment by Showgofar** [comment]
864         $merged = array_merge(...array_slice($args, 1));

**Comment by ttodua** [comment]
right, there was referential mistake in docs (or  might be  the code itself which doesn't support 5.4). We are to fix that now, just a question, can you tell me please, what are valid use-cases nowadays, where you want to use such old PHP version? is there anything that prevents you from using never PHP version?

**Comment by Showgofar** [comment]
so it should be 5.6+ then
or you can replace spread with function and it should work
before update to latest ccxt version it was working fine on php 5.5

**Comment by Showgofar** [comment]
Also there is one more error if i replace code
to
```
$sliced = array_slice($args, 1);
$merged = array();
foreach ($sliced as $item)
{
	$merged = array_merge($merged, $item);
}
```

Parse error: syntax error, unexpected '$this' (T_VARIABLE) in //home/httpd/ccxt/php/async/Exchange.php on line 136
136             $result = yield $this->browser->request($method, $url, $headers, $body);

**Comment by ttodua** [comment]
@Showgofar fix can be made of course, please wait. the answer I wanted (which i asked for) is that I am curious, what could be valid uses cases for users, using php 5.5 or lower. Can you name, what prevents you from using upper php versions? I just want to know it to collect the feedback, because, if there are not real need for old php versions, we would better support more newer versions of php.

**Comment by ttodua** [comment]
we are bumping the required version to more safer level (7.0+), so will not be supporting the old code.
I advise you take steps to update your php too, so the system will work better in overall.
if you have no chance to make an update and want to stick to old version, you might use updated version (will be available once the above reference PR is merged), but even thought it might or might not work on old versions, we will now be supporting officially 7.0+ versions.
