### ISSUE TITLE
Is now ccxt pro integrated to free one?

### ISSUE THREAD

**Issue by myehrajat** [ccxt/ccxt#14626]
Hi
I right now ccxt pro integrated to free version?
If not when exactly it will be  as a part of free version?
Is there any documentation for it available??

**Comment by carlosmiei** [comment]
Hello @myehrajat,
Not yet, but it will be soon. We don't have a specific date yet, but we're working hard to make it happen as soon as possible.

> Is there any documentation for it available??
We will make all CCXT.PRO documentation public after the release.
