### ISSUE TITLE
No "Seats" available after Corporate upgrade

### ISSUE THREAD

**Issue by mikmik** [ccxt/ccxt#14635]
Hi Guys,

This is a CCXT Corporate account issue.
I have upgraded from  Professional to Corporate a couple of days ago but can't add any more seats above the 2 we already had.

Please help,
Thank you,
Franck

**Comment by mikmik** [comment]
Dear mikmik,

Your order payment is confirmed!

You will be invited to the CCXT Pro source code repository shortly:

    https://github.com/kroitor/ccxt.pro

________________________

Order Details
________________________

Order ID:  7e76c6fb7257 
Tier:      Corporate
Months:    1
Total:     199 USD
Status:    paid

Next payment due: 2022 Oct 08 13:56:45 UTC

Thank you for using CCXT Pro!

**Comment by ttodua** [comment]
Sorry for confusion, we have release PRO version as free recently, so you no longer need to purchase the subscription. You just need to use only CCXT package now. Please let us know if you have any issue now.
