### ISSUE TITLE
ZB exchange watch_order_book() fails.

### ISSUE THREAD

**Issue by SimonTibra** [ccxt/ccxt#14631]
- OS: Linux
- Programming Language version: Python 3.8.12
- CCXT version: 1.91.85

This replicates the error:
```
import ccxtpro
ex = ccxtpro.zb()
await ex.watch_order_book('AMC/USDT')
```

Error:
```
NetworkError: Cannot connect to host api.{hostname}:443 ssl:default [Name or service not known]
```

In zb.js the line:
```
const url = this.urls['api']['ws'] + '/' + market['baseId'];
```

Should be:
```
const url = this.implodeHostname (this.urls['api']['ws']) + '/' + market['baseId'];
```

**Comment by samgermain** [comment]
> * OS: Linux
> 
>     * Programming Language version: Python 3.8.12
> 
>     * CCXT version: 1.91.85
> 
> 
> This replicates the error:
> 
> ```
> import ccxtpro
> ex = ccxtpro.zb()
> await ex.watch_order_book('AMC/USDT')
> ```
> 
> Error:
> 
> ```
> NetworkError: Cannot connect to host api.{hostname}:443 ssl:default [Name or service not known]
> ```
> 
> In zb.js the line:
> 
> ```
> const url = this.urls['api']['ws'] + '/' + market['baseId'];
> ```
> 
> Should be:
> 
> ```
> const url = this.implodeHostname (this.urls['api']['ws']) + '/' + market['baseId'];
> ```

Thanks, if you post a PR with this change, I expect it will be merged shortly

**Comment by carlosmiei** [comment]
Hello @SimonTibra, you're right thanks for reporting it, we will fix it asap!
