### ISSUE TITLE
Print All Order Types Per Exchange

### ISSUE THREAD

**Issue by mmehrle** [ccxt/ccxt#14630]
I have a comprehensive script that prints a lot of information about each exchange. However one piece of information I am missing are the order types per exchange. Specifically I need to know which exchange supports an OCO. Is there a hook for that in ccxt?

**Comment by mmehrle** [comment]
(sorry the code somehow gets all messed up)

**Comment by samgermain** [comment]
This is some information that we can add with the [`has.features`](https://github.com/ccxt/ccxt/issues/6772) structure once it get's implemented and merged, which is something I have been working on, but took a break to add full support for isolated/cross margin on some popular exchanges

**Comment by mmehrle** [comment]
Thanks Samgermain - that would be appreciated. I work with many clients in various geographic regions and that question will keep coming up. It would be brilliant to simply run a script and print the names of the exchanges that support OCOs.
