### ISSUE TITLE
KuCoin Spot Market Order - 'cost':None 'average':None 'filled':None 'remaining':None 'status':None 'fee':None 'trades':None

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#14634]
Why does a KuCoin Spot market order return  'cost', 'average', 'filled', 'remaining', 'status', 'fee', 'trades' = None ?
How to check status of order in this case ?

- OS: win 10 pro
- Programming Language version: python 3.10.5
- CCXT version: 1.91.100

```
'id':'62f2a47d1f0caa00016c62d3'
'clientOrderId':'9844eb71-ddbc-46c9-9c32-2dc841f577fb'
'info':{'orderId': '62f2a47d1f0caa00016c62d3'}
'timestamp':1660068989558
'datetime':'2022-08-09T18:16:29.558Z'
'lastTradeTimestamp':None
'symbol':'KCS/USDC'
'type':'market'
'side':'buy'
'price':10.507
'amount':0.0999
'cost':None
'average':None
'filled':None
'remaining':None
'status':None
'fee':None
'trades':None
```

**Comment by samgermain** [comment]
None of those fields are returned by the `kucoin` api (you can check the kucoin response in `info`) so we can't fill them in because no information is provided

**Comment by YuriyTigiev** [comment]
How to get the actual order status in this case?  Based on provided example is this order complete or not ? What about fee ?

**Comment by samgermain** [comment]
> How to get the actual order status in this case? Based on provided example is this order complete or not ? What about fee ?

You would have to use the `fetchOrder` method, because it looks like the status is not returned by the kucoin API
