### ISSUE TITLE
ccxt 1.91.100 requires yarl==1.7.2; python_version >= "3.5.2", but you have yarl 1.8.1 which is incompatible.

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#14633]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ccxt 1.91.100 requires yarl==1.7.2; python_version >= "3.5.2", but you have yarl 1.8.1 which is incompatible.

**Comment by nuaimat** [comment]
+1 

Please upgrade ccxt to yarl 1.8.1
