### ISSUE TITLE
Insufficient balance okx

### ISSUE THREAD

**Issue by hosseinab** [ccxt/ccxt#14642]
OS: Windows 11
Programming Language version: PYTHON 3.10.5
CCXT version: "ccxt/ccxt": "^1.90.94",
Exchange: okx
Method: transfer

hi . run this code :
output = connection.transfer("TRX", 29.177378306, '18', '6')
get this error :
{"code":"58350","data":[],"msg":"Insufficient balance"}

This is my account balance which shows that I have this amount of balance :
{'info': {'code': '0', 'data': [{'adjEq': '', 'details': [{'availBal': '29.177378306', 'availEq': '', 'cashBal': '29.177378306', 'ccy': 'TRX', 'crossLiab': '', 'disEq': '1.699348867298052', 'eq': '29.177378306', 'eqUsd': '1.99923396152712', 'frozenBal': '0', 'interest': '', 'isoEq': '', 'isoLiab': '', 'isoUpl': '', 'liab': '', 'maxLoan': '', 'mgnRatio': '', 'notionalLever': '', 'ordFrozen': '0', 'stgyEq': '0', 'twap': '0', 'uTime': '1660113943291', 'upl': '', 'uplLiab': ''}, {'availBal': '0.09959450185261', 'availEq': '', 'cashBal': '0.09959450185261', 'ccy': 'USDT', 'crossLiab': '', 'disEq': '0.09959450185261', 'eq': '0.09959450185261', 'eqUsd': '0.09959450185261', 'frozenBal': '0', 'interest': '', 'isoEq': '', 'isoLiab': '', 'isoUpl': '', 'liab': '', 'maxLoan': '', 'mgnRatio': '', 'notionalLever': '', 'ordFrozen': '0', 'stgyEq': '0', 'twap': '0', 'uTime': '1660113126751', 'upl': '', 'uplLiab': ''}], 'imr': '', 'isoEq': '', 'mgnRatio': '', 'mmr': '', 'notionalUsd': '', 'ordFroz': '', 'totalEq': '2.09882846337973', 'uTime': '1660114149959'}], 'msg': ''}, 'TRX': {'free': 29.177378306, 'used': 0.0, 'total': 29.177378306}, 'USDT': {'free': 0.09959450185261, 'used': 0.0, 'total': 0.09959450185261}, 'timestamp': 1660114149959, 'datetime': '2022-08-10T06:49:09.959Z', 'free': {'TRX': 29.177378306, 'USDT': 0.09959450185261}, 'used': {'TRX': 0.0, 'USDT': 0.0}, 'total': {'TRX': 29.177378306, 'USDT': 0.09959450185261}}

**Comment by hosseinab** [comment]
And I will transfer this amount with the website itself, there is no problem

**Comment by sc0Vu** [comment]
HI @hosseinab 

The default type for `fetchBalance` is funding (6) account, would you like to check the balance in trading (18)?

BTW, the transfer works on my side.

**Comment by hosseinab** [comment]
fetch_balance from trading account ?
How should I do this?

**Comment by hosseinab** [comment]
use this code: 
params = {
    'account': 18
}
obj = connection.fetch_balance(params=params)

The output is no different

**Comment by lefeverela** [comment]
@hosseinab you show this as completed. What was the final solution for you? I am experiencing same issue
