### ISSUE TITLE
how to set crypto.com margin mode?

### ISSUE THREAD

**Issue by kjnh10** [ccxt/ccxt#14641]
For the detail, please see #14107

**Comment by sc0Vu** [comment]
Hi @kjnh10,

I think set the defaultType is the only way for now, because the `market['type']` will replace the global options.defaultType.

**Comment by Dan-krm** [comment]
I've opened a PR that will allow you to set marginMode in the params of the method you're using to 'cross', that will allow you to use the margin endpoints as an alternative to setting defaultType to 'margin'. It looks like Crypto.com doesn't currently support isolated margin.

**Comment by kjnh10** [comment]
Thanks for considering.
But it seems that your change does not fit my request.
My intention is to separate using margin(not spot) easily.

Let's clarify my request.
When I would like to trade a margin pair In the current version, I need to pass 'params{'type':'margin'}' to each request, create_order, fetch_order, ..... every time.

My request is to specify margin by passing options['defaultType':'margin'] when creating exchange instance.
Once I created the instance, I can skip passing params{'type':'margin'}' to each request.

**Comment by Dan-krm** [comment]
Currently you can set the defaultType to margin to use the margin features without specifying a 'type' parameter with each request:
```
        'options': {
            'defaultType': 'margin',
        },
```

**Comment by kjnh10** [comment]
I thought it should be. But the actual implementation is not. (Maybe a bug?)

In #14107, I have written the details about this. Could you check it?

**Comment by Dan-krm** [comment]
> I thought it should be. But the actual implementation is not. (Maybe a bug?)
> 
> In summary, within 'handle_market_and_params' function, market['type'] is prioritized than option['defaultType'] In #14107, I have written the details about this. Could you check it?

Interesting, thanks for pointing this out, in this PR: https://github.com/ccxt/ccxt/pull/14661 I overwrite handleMarginModeAndParams and with the changes if defaultType is margin, handleMarginModeAndParams will default to 'cross' and the margin endpoint will be used fixing your issue.

**Comment by kjnh10** [comment]
I confirmed that it's working as expected!
Many thanks,
