### ISSUE TITLE
I have the following questions

### ISSUE THREAD

**Issue by qwe231cvb** [ccxt/ccxt#14659]
The code as follows:
```
#coding=u8
import ccxt
import pandas as pd
import time
import sys
from datetime import datetime
exchange = ccxt.poloniex()
hold = 30
limit = 1000
def download(symbol, from_timestamp, end_timestamp, timeframe):
    tf_multi = exchange.parse_timeframe(timeframe) * 1000
    data = []
    candle_no = (int(end_timestamp)-int(from_timestamp)) / tf_multi +1
```
first question:
What is the difference between 'from_timestamp' and 'int(from_timestamp)'?

second question:
What does 'data = []' mean?

Third question:
What is the difference between 'tf_multi = exchange.parse_timeframe(timeframe)' and 'tf_multi = exchange.parse_timeframe(timeframe) * 1000'?

Fourth question:
What does the line 'candle_no = (int(end_timestamp)-int(from_timestamp)) / tf_multi +1' do?

**Comment by samgermain** [comment]
I don't think any of these are questions about CCXT, so I'll still answer them, but I'm going to close this issue right after seeing as it's unrelated, but feel free to post any questions you still have

> What is the difference between 'from_timestamp' and 'int(from_timestamp)'?

If `from_timestamp` is a different data type like a string and is set to something like `"1660284118000"` then running `int(from_timestamp)` would return the integer data type with the same number (`1660284118000`)

> second question:
> What does 'data = []' mean?

`data = []` creates an empty [list](https://www.w3schools.com/python/python_lists.asp) which is named data

> Third question:
> What is the difference between 'tf_multi = exchange.parse_timeframe(timeframe)' and 'tf_multi = exchange.parse_timeframe(timeframe) * 1000'?

The second line of code multiplies value by 1000, so `tf_multi` is 1000 times larger using the second line. 
I can see that it's multiplying a timeframe though, so given the context, it looks like the first line of code might store the timeframe value using seconds as the unit, and the second line of code would then store the timeframe value using milliseconds as the unit

> Fourth question:
> What does the line 'candle_no = (int(end_timestamp)-int(from_timestamp)) / tf_multi +1' do?

I don't really know what this code is from so I can't tell you, but it looks like it's trying to determine the number of candles (-1) that are in your data prior to the candle that you're looking at. It looks like it's calculating the time difference between the end and start timestamp for the numerator, and I don't really know what the `tf_multi` and +1 are for without some more context.
