### ISSUE TITLE
Issue when accessing BinanceUS account information : binanceus {"code":-1100,"msg":"Illegal characters found in a parameter."}

### ISSUE THREAD

**Issue by jblon** [ccxt/ccxt#14651]
I am having trouble getting the binanceus package to accept my api key and secret. 

- OS: Windows 10
- Programming Language version: Python 3.7.7
- CCXT version: '1.92.10'

```
self.ExchangeAPIdict = {}
api = 'binance'
credential_dict = {
                            'apiKey': str(acess_key),
                            'secret': str(secret_key),                                
                            }   
self.ExchangeAPIdict[api] = {}
self.ExchangeAPIdict[api]['APIlink'] = ccxt.binanceus(credential_dict)
self.exchange_dict = {}
self.exchange_dict[api] = self.ExchangeAPIdict[api]['APIlink'].fetch_currencies()
```

```
 File "C:\Python\envs\tf-cpu\lib\site-packages\ccxt\base\exchange.py", line 620, in fetch
    response.raise_for_status()

  File "C:\Python\envs\tf-cpu\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

HTTPError: 400 Client Error:  for url: https://api.binance.us/sapi/v1/capital/config/getall?timestamp=1660188826402&recvWindow=10000&signature="MyGeneratedSignature"


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-4-4ad52ca62ea9>", line 1, in <module>
    t.pullPriceInfo()

  File "D:\MarketProject\SourceCode\ArbiterSpy.py", line 110, in pullPriceInfo
    self.getAllMarkets()

  File "D:\MarketProject\SourceCode\ArbiterSpy.py", line 92, in getAllMarkets
    self.exchange_dict[api] = self.ExchangeAPIdict[api]['APIlink'].fetch_currencies()

  File "C:\Python\envs\tf-cpu\lib\site-packages\ccxt\binance.py", line 1308, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)

  File "C:\Python\envs\tf-cpu\lib\site-packages\ccxt\base\exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)

  File "C:\Python\envs\tf-cpu\lib\site-packages\ccxt\binance.py", line 5513, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)

  File "C:\Python\envs\tf-cpu\lib\site-packages\ccxt\base\exchange.py", line 2624, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File "C:\Python\envs\tf-cpu\lib\site-packages\ccxt\base\exchange.py", line 636, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File "C:\Python\envs\tf-cpu\lib\site-packages\ccxt\binance.py", line 5491, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)

  File "C:\Python\envs\tf-cpu\lib\site-packages\ccxt\base\exchange.py", line 2867, in throw_exactly_matched_exception
    raise exact[string](message)

BadRequest: binanceus {"code":-1100,"msg":"Illegal characters found in a parameter."}
```

I know the keys are valid because when I use the actual binance package instead of the ccxt package I can access everything, but there in the client initialization there as a variable tld='us' that I pass and it makes it work, not sure if I am missing something like that here. I've tried forcing the keys as strings just in case something strange was happening to my variables. I have also tried not storing the ccxt.binanceus object in a dictionary to see if that was causing issues and that didn't help either.

I am connecting to kucoin and zb just fine and everything is working great, just something about the binance stuff (of course if I use ccxt.binance my keys are invalid since I am a US user). The error message gives me the url it is trying to pull from and when I copy that into my browser I get this message : 
{"code":-2014,"msg":"API-key format invalid."}

So it seems like something is going wrong with how my key is presented but I can't for the life of me figure out what it is since I can get it working with a different python binance package. I have seen some others with the same issue recently but I haven't had any luck trying what they were doing, appreciate any and all help :)

**Comment by kbwhodat** [comment]
I also had this same issue. I downgraded to 1.84.25 and it worked. Not sure whats wrong with the latest versions

**Comment by ttodua** [comment]
Please tell us, if you still experience the issue with latest version of ccxt.

**Comment by jblon** [comment]
No issue anymore, there was a phantom blank space being added into the secret key somewhere that I tracked down and fixed.

**Comment by ttodua** [comment]
@jblon thanks for sharing that note.
