### ISSUE TITLE
Cannot import CCXT to AWS Lambda

### ISSUE THREAD

**Issue by julian-dotcom** [ccxt/ccxt#14657]
I am trying to use/import CCXT in AWS Lambda. I created a layer with packages installed in an Ubuntu Docker container, zipped them and uploaded them as a layer to my lambda function. But it fails to import. 

Checked online for help and there were other people that had the same problem, but no one had a solution...

I also tried to install cryptography, but it says it's already installed.

- OS: AWS Lambda environment
- Programming Language version: Python 3.9
- CCXT version: ccxt-1.92.14

```
import ccxt
```

```
{
  "errorMessage": "Unable to import module 'lambda_function': /opt/python/lib/python3.9/site-packages/cryptography/hazmat/bindings/_rust.abi3.so: cannot open shared object file: No such file or directory",
  "errorType": "Runtime.ImportModuleError",
  "requestId": "12345",
  "stackTrace": []
}
```

**Comment by samgermain** [comment]
You may want to look at this issue by the way https://github.com/ccxt/ccxt/issues/12142

**Comment by julian-dotcom** [comment]
> You may want to look at this issue by the way #12142

Thanks, already have, but it didn't answer the question

**Comment by julian-dotcom** [comment]
Following this tutorial seems to fix the `import` issue. Thanks!

**Comment by samgermain** [comment]
> Following this tutorial seems to fix the `import` issue: https://www.linkedin.com/pulse/add-external-python-libraries-aws-lambda-using-layers-gabe-olokun/ Thanks

Great, I'm going to close this issue. Feel free to reopen it if you have any more questions
