### ISSUE TITLE
Get FTX Future coins list?

### ISSUE THREAD

**Issue by leonfresh** [ccxt/ccxt#14664]
Hi I'm looking for a list of coins ending with -PERP for the FTX exchange. 

I tried 

```
coins = ccxt.ftx({'options': { 'defaultType': 'future', }}).load_markets()
```

but it just gives a list of coins with USDT and USD and it's 800 length as opposed to FTX amount of futures (less than 150). 

This code works for binance, if I just switch ftx() to binance().

**Comment by samgermain** [comment]
There are no coins that end in `-PERP` only market ids that end in `-PERP`. I would also suggest using the unified symbol names, because they are the same between exchanges.

```
import ccxt  # noqa: E402
from pprint import pprint

exchange = ccxt.ftx()
exchange.load_markets()
markets = exchange.markets
# coins = [market['id'] for symbol, market in markets.items() if market['swap']] // uncomment if you want to use the -PERP market ids
coins = [symbol for symbol, market in markets.items() if market['swap']]

pprint(coins)
pprint(len(coins))
```
prints
```
['1INCH/USD:USD',
 'AAVE/USD:USD',
 'ADA/USD:USD',
 'AGLD/USD:USD',
 'ALCX/USD:USD',
 'ALGO/USD:USD',
 'ALICE/USD:USD',
 'ALPHA/USD:USD',
 ...
 'XRP/USD:USD',
 'XTZ/USD:USD',
 'YFI/USD:USD',
 'YFII/USD:USD',
 'ZEC/USD:USD',
 'ZIL/USD:USD',
 'ZRX/USD:USD']
177
```

**Comment by leonfresh** [comment]
> There are no coins that end in `-PERP` only market ids that end in `-PERP`. I would also suggest using the unified symbol names, because they are the same between exchanges.
> 
> ```
> import ccxt  # noqa: E402
> from pprint import pprint
> 
> exchange = ccxt.ftx()
> exchange.load_markets()
> markets = exchange.markets
> # coins = [market['id'] for symbol, market in markets.items() if market['swap']] // uncomment if you want to use the -PERP market ids
> coins = [symbol for symbol, market in markets.items() if market['swap']]
> 
> pprint(coins)
> pprint(len(coins))
> ```
> 
> prints
> 
> ```
> ['1INCH/USD:USD',
>  'AAVE/USD:USD',
>  'ADA/USD:USD',
>  'AGLD/USD:USD',
>  'ALCX/USD:USD',
>  'ALGO/USD:USD',
>  'ALICE/USD:USD',
>  'ALPHA/USD:USD',
>  ...
>  'XRP/USD:USD',
>  'XTZ/USD:USD',
>  'YFI/USD:USD',
>  'YFII/USD:USD',
>  'ZEC/USD:USD',
>  'ZIL/USD:USD',
>  'ZRX/USD:USD']
> 177
> ```


Thank you that worked perfectly. Is the code you gave me using unified symbol names already?

**Comment by samgermain** [comment]
> Thank you that worked perfectly. Is the code you gave me using unified symbol names already?

Yes it is
