### ISSUE TITLE
CCXT 1m BTC/USD Market data going back to 2021 to now TO CSV file

### ISSUE THREAD

**Issue by Talha-Islam** [ccxt/ccxt#14668]
How to add 1m market data from 2021 to now to CSV file. For backtrader use case. I am using FTX and the maxing it can do is 5000 candles. Is there a way to multiply calls to give the data or some other way?

#How to run code 
#python3 ccxt_market_data.py -s BTC/USD -e ftx -t 1m 

- OS: MAC M1
- Programming Language version: Python
- CCXT version: pip install ccxt
Requirement already satisfied: ccxt in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (1.92.14)
m

import ccxt
from datetime import datetime, timedelta, timezone
import math
import argparse
import pandas as pd

def parse_args():
    parser = argparse.ArgumentParser(description='CCXT Market Data Downloader')

    parser.add_argument('-s','--symbol',
                        type=str,
                        required=True,
                        help='The Symbol of the Instrument/Currency Pair To Download')

    parser.add_argument('-e','--exchange',
                        type=str,
                        required=True,
                        help='The exchange to download from')

    parser.add_argument('-t','--timeframe',
                        type=str,
                        default='1d',
                        choices=['1m', '5m','15m', '30m','1h', '2h', '3h', '4h', '6h', '12h', '1d', '1M', '1y'],
                        help='The timeframe to download')

    parser.add_argument('--debug',
                            action ='store_true',
                            help=('Print Sizer Debugs'))

    return parser.parse_args()

#Get our arguments
args = parse_args()

#Get our Exchange
try:
    exchange = getattr (ccxt, args.exchange) ()
except AttributeError:
    print('-'*36,' ERROR ','-'*35)
    print('Exchange "{}" not found. Please check the exchange is supported.'.format(args.exchange))
    print('-'*80)
    quit()

#Check if fetching of OHLC Data is supported
if exchange.has["fetchOHLCV"] != True:
    print('-'*36,' ERROR ','-'*35)
    print('{} does not support fetching OHLC data. Please use another exchange'.format(args.exchange))
    print('-'*80)
    quit()

#Check requested timeframe is available. If not return a helpful error.
if (not hasattr(exchange, 'timeframes')) or (args.timeframe not in exchange.timeframes):
    print('-'*36,' ERROR ','-'*35)
    print('The requested timeframe ({}) is not available from {}\n'.format(args.timeframe,args.exchange))
    print('Available timeframes are:')
    for key in exchange.timeframes.keys():
        print('  - ' + key)
    print('-'*80)
    quit()

#Check if the symbol is available on the Exchange
#exchange.load_markets()
#if args.symbol not in exchange.symbols:
###print('-'*36,' ERROR ','-'*35)
###print('The requested symbol ({}) is not available from {}\n'.format(args.symbol,args.exchange))
###print('Available symbols are:')
###for key in exchange.symbols:
#####print('  - ' + key)
###print('-'*80)
###quit()

#Get data
data = exchange.fetch_ohlcv(args.symbol, args.timeframe, limit = 5000)
header = ['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume']
df = pd.DataFrame(data, columns=header).set_index('Timestamp')
#Save it
symbol_out = args.symbol.replace("/","/")
filename = '{}-{}-{}.csv'.format(args.exchange, symbol_out,args.timeframe)
df.to_csv(filename)

```

```
How to add 1m Market data to CSV from 2021 to now for Backtrader use case?

```

**Comment by samgermain** [comment]
Here's an example of how you can do it

```
# -*- coding: utf-8 -*-

import os
import sys
import ccxt  # noqa: E402
import numpy as np
from datetime import datetime

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

print('CCXT Version:', ccxt.__version__)

# data
exchange_name = 'ftx'
symbol = "BTC/USD"
max_candles = 5000
timeframe = '1m'
start = 1609459200000  # Jan 1, 2021
ms_per_candle = {
    '1m': 60000,
    '5m': 300000,
    '15m': 900000,
    '30m': 1800000,
    '1h': 3600000,
    '2h': 7200000,
    '4h': 14400000,
    '8h': 28800000,
    '12h': 57600000,
    '1d': 86400000,
}

now = int(datetime.now().timestamp() * 1000)
outfile = f"{symbol.replace('/', '-')}_{timeframe}_{exchange_name}_{start}-{now}.csv"

# setup
exchange = ccxt.ftx()
exchange.load_markets()
ohlcv = []

# make requests for candle data
while start < now:
    candles = exchange.fetch_ohlcv(symbol, timeframe, start, max_candles)
    ohlcv += candles
    start = start + (ms_per_candle[timeframe] * max_candles)

# write to csv
np.savetxt(
    outfile,
    ohlcv,
    delimiter=",",
    fmt='%d,%s,%s,%s,%s,%s'
)
```

For the 1m timeframe, your going to be making a lot of calls, and you may want to consider making this code asynchronous to perform the task quicker.

This example file shows how you can make multiple calls asynchronously, so you could reference this in making this program asynchronous
https://github.com/ccxt/ccxt/blob/master/examples/py/sort-swap-markets-by-hourly-price-change.py

**Comment by Talha-Islam** [comment]
The data is coming in as unix timestamp in milliseconds. 
So i am using #dtformat=lambda x: datetime.datetime.utcfromtimestamp(int(x) / 1000).
import backtrader as bt
import datetime

cerebro = bt.Cerebro()
data = bt.feeds.GenericCSVData(dataname="ftx1h.csv", dtformat=lambda x: datetime.datetime.utcfromtimestamp(int(x) / 1000))
cerebro.adddata(data)
cerebro.run()
cerebro.plot()

# But now there is an #IndexError: list index out of range problem.
Traceback (most recent call last):
  File "/Users/talha/VScode/Backtest/Strategy5.py", line 7, in <module>
    cerebro.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/backtrader/cerebro.py", line 1127, in run
    runstrat = self.runstrategies(iterstrat)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/backtrader/cerebro.py", line 1212, in runstrategies
    data.preload()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/backtrader/feed.py", line 688, in preload
    while self.load():
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/backtrader/feed.py", line 479, in load
    _loadret = self._load()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/backtrader/feed.py", line 710, in _load
    return self._loadline(linetokens)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/backtrader/feeds/csvgeneric.py", line 148, in _loadline
    csvfield = linetokens[csvidx]
IndexError: list index out of range

# The Data
1660435200000,24454.0,24528.0,24355.0,24527.0,67147303.3027
1660438800000,24527.0,24682.0,24422.0,24598.0,116587503.2913
1660442400000,24598.0,24632.0,24514.0,24608.0,34892443.4722
1660446000000,24608.0,24635.0,24553.0,24584.0,22989205.8046
1660449600000,24584.0,24652.0,24506.0,24581.0,44973942.2299
1660453200000,24581.0,24636.0,24540.0,24603.0,47360860.8874
1660456800000,24613.0,24695.0,24603.0,24689.0,32459071.9839
1660460400000,24689.0,25065.0,24682.0,24900.0,301312472.1925
1660464000000,24900.0,24902.0,24608.0,24673.0,170952143.2637
1660467600000,24672.0,24790.0,24643.0,24758.0,70969336.6324
1660471200000,24758.0,24759.0,24618.0,24627.0,64221863.5382
1660474800000,24627.0,24682.0,24525.0,24569.0,76070172.2453
1660478400000,24569.0,24593.0,24475.0,24535.0,59713290.9481
1660482000000,24535.0,24538.0,24406.0,24481.0,89923365.2962
1660485600000,24481.0,24534.0,24466.0,24518.0,49835330.6131
1660489200000,24518.0,24549.0,24468.0,24528.0,46556537.1289
1660492800000,24528.0,24560.0,24313.0,24315.0,108465182.8929
1660496400000,24315.0,24332.0,24178.0,24232.0,176757581.0963
1660500000000,24232.0,24300.0,24155.0,24282.0,68322221.4964
1660503600000,24281.0,24327.0,24244.0,24289.0,34982570.2998
1660507200000,24289.0,24352.0,24255.0,24315.0,40799224.029
1660510800000,24315.0,24448.0,24278.0,24349.0,94709768.3767
1660514400000,24349.0,24372.0,24182.0,24265.0,75704499.2116
1660518000000,24265.0,24358.0,24240.0,24310.0,46011851.1185
1660521600000,24310.0,24418.0,24171.0,24406.0,90810435.293
1660525200000,24406.0,24665.0,24340.0,24655.0,233812433.3012
1660528800000,24654.0,24950.0,24653.0,24937.0,223521446.7061
1660532400000,24937.0,25232.0,24813.0,24883.0,373106086.273
1660536000000,24883.0,24900.0,24696.0,24863.0,172798798.982
1660539600000,24863.0,24998.0,24762.0,24835.0,110243603.1486
1660543200000,24835.0,24841.0,24088.0,24129.0,338761936.3576
1660546800000,24130.0,24218.0,23950.0,24026.0,287354302.5387
1660550400000,24025.0,24089.0,23873.0,24044.0,151992609.2842
1660554000000,24044.0,24210.0,23992.0,24176.0,132115004.5245
1660557600000,24180.0,24300.0,24133.0,24275.0,88762538.3025
1660561200000,24275.0,24316.0,24009.0,24057.0,116716391.6228
1660564800000,24057.0,24197.0,23891.0,23966.0,135401782.9878
