### ISSUE TITLE
Cannot fetch funding rate from Gate io

### ISSUE THREAD

**Issue by kieran-mackle** [ccxt/ccxt#14663]
**Machine details:**
- OS: Fedora Linux 36
- Programming Language version: Python
- CCXT version: 1.92.14

**Issue:**
The source code for Gate checks if the symbol is a swap contract and [raises an exception if it is not](https://github.com/ccxt/ccxt/blob/master/python/ccxt/gate.py#L1263-L1265). However, after loading all markets, there are none which will satisfy this condition. See the code below, which shows that no markets for Gate io have `'swap': True`.

```
import ccxt

exchange = ccxt.gate()
markets = exchange.load_markets()
for market in markets:
    if exchange.market(market)['swap']:
        print(market)
```

How can the funding rate be fetched for Gate io? Or what is the symbol naming convention for contracts like [ETH_USDT](https://www.gate.io/en/futures_trade/USDT/ETH_USDT) for example?

**Comment by sc0Vu** [comment]
Hi @kieran-mackle 
You can fetch funding rate of eth usdt perp with: `ETH/USDT:USDT` symbol.

**Comment by kieran-mackle** [comment]
Hi @sc0Vu, 
I still get the `BadSymbol` exception when trying that.

```python
import ccxt

exchange = ccxt.gate()
exchange.fetchFundingRate(symbol='ETH/USDT:USDT')
```
```
BadSymbol: gate does not have market symbol ETH/USDT:USDT
```

**Comment by samgermain** [comment]
> Hi @sc0Vu, I still get the `BadSymbol` exception when trying that.
> 
> ```python
> import ccxt
> 
> exchange = ccxt.gate()
> exchange.fetchFundingRate(symbol='ETH/USDT:USDT')
> ```
> 
> ```
> BadSymbol: gate does not have market symbol ETH/USDT:USDT
> ```

You must pass `{"options": {"defaultType": "swap"}}` to `gateio` to fetch the `swap` markets. 
I also cleaned up your example a little bit

```
import ccxt
from pprint import pprint

exchange = ccxt.gate({
    'options': {
        'defaultType': 'swap',
    }
})
exchange.load_markets()
for symbol, market in exchange.markets.items():
    if market['swap']:
        pprint(symbol)
```

**Comment by kieran-mackle** [comment]
@samgermain that did the trick, thanks!
