### ISSUE TITLE
bitget create_order is taking amount as cost

### ISSUE THREAD

**Issue by toleRB** [ccxt/ccxt#14667]
- OS: macOS Monterey 12.5
- Programming Language version: PHP 8.1.9
- CCXT version: 1.92.14

![image](https://user-images.githubusercontent.com/51666575/184391502-1cc0939a-3df4-49c2-8525-4dec6cfe854b.png)

```
Array
(
    [info] => Array
        (
            [accountId] => xxxxxxxx
            [symbol] => XXXXXX_SPBL
            [orderId] => xxxxxxxx
            [clientOrderId] => CCXT#xxxxxxxxxxx
            [price] => 0.000000000000
            [quantity] => 2459.700000000000
            [orderType] => market
            [side] => buy
            [status] => full_fill
            [fillPrice] => 0.011407602044
            [fillQuantity] => 215619.300000000000
            [fillTotalAmount] => 2459.699167200000
            [cTime] => 1660315155867
        )

```

The amount indicated in the fourth parameter from create_order was 2,459.7, however the filled amount, as we can see in the output of fetch_order is 215,619. It looks like that filled amount multiplies by the price it gives you the 2,459 that were intended to buy. which means that is taking the amount as cost instead of amount.

**Comment by samgermain** [comment]
> I just got response from bitget support, it looks like the quantity in their create order endpoint, at least for market orders, is expected in the quote of the symbol so, it is the cost.

Is this issue resolved then?

**Comment by toleRB** [comment]
I got more responses from them:
"sell market  order  size is UNI,  buy market order  size is  USDT",

so, same endpoint used the same parameter as difference things depending if you are sending a sell or buy.

I'm closing the issue @samgermain. There is nothing wrong with ccxt, but i don't know if you wanna implement something to have consistency with all the exchanges.

**Comment by carlosmiei** [comment]
Hi @toleRB, we usually implement a logic to prevent mistakes when some exchange requires the cost for market buy orders. We will do the same for Bitget. Thanks for letting us know.
