### ISSUE TITLE
React-native error BigInt

### ISSUE THREAD

**Issue by ValyaBabenkov** [ccxt/ccxt#14674]
Good afternoon, connected the library to the project on React-Native.
Some exchangers work, but most give the error:

```
TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at Precise.div (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.crypto.vsp:219789:32)
    at Function.stringDiv
```

Tried commenting the code: node_modules/metro-react-native-babel-preset/src/configs/main.js

```
// if (!isHermes && (isNull || src.indexOf("**") !== -1)) {   
// extraPlugins.push([   
// require("@babel/plugin-transform-exponentiation-operator"),   
// ]);
// }
```

Didn't help ;(

Stack:
```
"react": "17.0.2",  
"react-native": "0.68.2",
"ccxt": "^1.90.57",
```

**Comment by samgermain** [comment]
> Good afternoon, connected the library to the project on React-Native. Some exchangers work, but most give the error:
> 
> ```
> TypeError: Cannot convert a BigInt value to a number
>     at Math.pow (<anonymous>)
>     at Precise.div (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.crypto.vsp:219789:32)
>     at Function.stringDiv
> ```
> 
> Tried commenting the code: node_modules/metro-react-native-babel-preset/src/configs/main.js
> 
> ```
> // if (!isHermes && (isNull || src.indexOf("**") !== -1)) {   
> // extraPlugins.push([   
> // require("@babel/plugin-transform-exponentiation-operator"),   
> // ]);
> // }
> ```
> 
> Didn't help ;(
> 
> Stack:
> 
> ```
> "react": "17.0.2",  
> "react-native": "0.68.2",
> "ccxt": "^1.90.57",
> ```

Which exchange is that specifically that's failing?

**Comment by ttodua** [comment]
per what I see in lib code, this issue shouldn't be happening any longer. but if anyone still experience it, let us know, and please provide some demonstrational code (simplified snippet)
