### ISSUE TITLE
privatePostV2PrivateLinearPositionTradingStop bybit

### ISSUE THREAD

**Issue by flieks** [ccxt/ccxt#14678]
Hi,

`privatePostV2PrivatePositionTradingStop` exists which translates (for bybit) to 
`https://api.bybit.com/v2/private/position/trading-stop`

But for the USDT pairs i want to use
`https://api.bybit.com/v2/private/linear/position/trading-stop` (according to bybit docs)

So i would assume ccxt would have a `privatePostV2PrivateLinearPositionTradingStop` right ?

**Comment by flieks** [comment]
found it
had to leave the V2 keyword
`privatePostPrivateLinearPositionTradingStop` works

**Comment by kroitor** [comment]
@flieks thx for reporting back!
