### ISSUE TITLE
kucoin withdraw return none

### ISSUE THREAD

**Issue by hosseinab** [ccxt/ccxt#14672]
OS: Windows 11
Programming Language version: PYTHON 3.10.5
CCXT version: "ccxt/ccxt": "^1.90.94",
Exchange: kucoin
Method: withdraw

hi . run this code :

amount = 100
symbol = "TRX"
address = "address"
tag = None
chain = "TRC20"

params = {
           'chain': chain,
 }
response = connection.withdraw(symbol, amount, address, tag, params)
print(response)

output :
{'id': None, 'info': {}, 'timestamp': None, 'datetime': None, 'network': None, 'address': None, 'addressTo': None, 'addressFrom': None, 'tag': None, 'tagTo': None, 'tagFrom': None, 'currency': 'TRX', 'amount': None, 'txid': None, 'type': 'deposit', 'status': None, 'comment': None, 'fee': None, 'updated': None}

**Comment by sc0Vu** [comment]
Hi @hosseinab,

Would you like to add `verbose: true` and paste the raw response from exchange (please remember to remove some sensitive information)?

**Comment by hosseinab** [comment]
fetch Request: kucoin POST https://api.kucoin.com/api/v1/withdrawals RequestHeaders: {'KC-API-KEY-VERSION': '2', 'KC-API-KEY': '*****', 'KC-API-TIMESTAMP': '1660461772546', 'Content-Type': 'application/json', 'KC-API-PASSPHRASE': '******', 'KC-API-SIGN': '*********', 'KC-API-PARTNER-SIGN': '******', 'KC-API-PARTNER': 'ccxt', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"currency":"TRX","address":"TTdPiLH4u9H3vQNRfNtGtdbj4o48WzLahG","amount":50.5,"chain":"TRC20"}

fetch Response: kucoin POST https://api.kucoin.com/api/v1/withdrawals 200 ResponseHeaders: {'Date': 'Sun, 14 Aug 2022 07:22:45 GMT', 'Content-Type': 'application/json', 'Content-Length': '41', 'Connection': 'keep-alive', 'Set-Cookie': 'AWSALB=*****; Expires=Sun, 21 Aug 2022 07:22:45 GMT; Path=/, AWSALBCORS=*****; Expires=Sun, 21 Aug 2022 07:22:45 GMT; Path=/; SameSite=None; Secure, __cfruid=******; path=/; domain=.kucoin.com; HttpOnly; Secure; SameSite=None', 'Strict-Transport-Security': 'max-age=9800; includeSubDomains; preload', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '******'} ResponseBody: {"code":"900014","msg":"Invalid chainId"}


@sc0Vu 
verbose output

**Comment by hosseinab** [comment]
@sc0Vu 
this is output of fetch transaction fee :
TRC20 Chain is correct
{'info': {'code': '200000', 'data': {'currency': 'TRX', 'limitBTCAmount': '1.00000000', 'usedBTCAmount': '0.00029001', 'remainAmount': '349548.947055', 'availableAmount': '0.56900054', 'withdrawMinFee': '1.5', 'innerWithdrawMinFee': '0', 'withdrawMinSize': '3', 'isWithdrawEnabled': True, 'precision': 6, **'chain': 'TRC20'**}}, 'withdraw': {'TRX': 1.5}, 'deposit': {}}

**Comment by hosseinab** [comment]
@kroitor 
hi . I guess this is a bug
when set chain to 'trx' its ok

**Comment by sc0Vu** [comment]
Hi @hosseinab,

It works on both situation:

1. without chain option 
2. with chain `trx`.
 
But it didn't work with the uppercase `TRX` (that's weird).

Anyway, I found a line in there api documentation:
<img width="531" alt="image" src="https://user-images.githubusercontent.com/10494397/184545085-bd0920e8-03de-4ab9-a60a-6f7712e358aa.png">, since they only support TRX on TRC20, you don't have to set chain.

BTW, I'll add this error.

**Comment by hosseinab** [comment]
@sc0Vu 
Thanks for adding this error
But in my opinion, chain name conversion should be done in API functions.
for example when call api with TRC20 Chain , api replace "TRC20" with "trx"

**Comment by sc0Vu** [comment]
@carlosmiei 

How do you think about this (support `currency lowercase name` when there is only one network?

**Comment by carlosmiei** [comment]
@sc0Vu @hosseinab We're already doing this; the thing is, we should be using our unified param "network" instead of the exchange-specific "chain" to get the argument parsed correctly. 

Like this:
```Python
params = {
'network': chain,
}
response = connection.withdraw(symbol, amount, address, tag, params)
```

**Comment by hosseinab** [comment]
@carlosmiei 
thank you . its work fine

**Comment by hosseinab** [comment]
@carlosmiei  @sc0Vu 
please set network params for fetch_transaction_fee function in kucoin

**Comment by sc0Vu** [comment]
@hosseinab Thanks!
