### ISSUE TITLE
websocket binance

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1468]
api: https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md

just looked into the guide from websocket binance [doc](https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md) support. let me know if i can get the hook for exchange init struct so i can start from there.

**Comment by kroitor** [comment]
Sorry, but we should not create multiple WS issues yet. We already know their endpoints.
