### ISSUE TITLE
Issue with leverage futures Kucoin

### ISSUE THREAD

**Issue by xanadui** [ccxt/ccxt#14682]
Hi all,

I seem to be getting this error using CCXT for trading ETH perps but I do have the necessary funds in my account to trade the position on 5 times leverage. Please let me know if you need more info on my issue or if there is something that I'm missing. Thanks!

- OS: macOS Monterey 12.0.1
- Programming Language version: Python
- CCXT version:1.90.23

```
import ccxt

ku = ccxt.kucoinfutures({
    'adjustForTimeDifference': True,
    "apiKey": api_key,
    "secret": secret_key,
    "password": pw
});


amount = 640
price = ku.fetchTicker("ETH/USDT:USDT")
time.sleep(8)
order = ku.createOrder("ETH/USDT:USDT", 'market', 'buy', ((math.floor(amount/float(price['info']['price'])*1000)/1000)*100),{'leverage': 5})

```

```
ccxt.base.errors.InsufficientFunds: kucoinfutures Balance insufficient. The order would cost 621.7596314550.
```

**Comment by carlosmiei** [comment]
Hello @xanadui,

I've tested it, and it seems to be working fine. Can you please double-check your available balance and/or try to place the same order using the WebUI?

Also, please bear in mind that the amount should be in contract units, and in this case, 1 contract = 0.01 ETH

**Comment by xanadui** [comment]
Thanks @carlosmiei it started working when I changed the order to a limit order and that worked so maybe that was the issue. Thank you!

**Comment by ttodua** [comment]
This topic is now closed. Let us know if you have any other issue with CCXT.
