### ISSUE TITLE
Issue with `formatScientificNotationFTX()` in CCXT Pro

### ISSUE THREAD

**Issue by pietrodn** [ccxt/ccxt#14695]
In CCXT Pro 1.2.14 for Python, `watch_order_book()` for FTX crashes because `format_number()` [calls](https://github.com/kroitor/ccxt.pro/blob/master/python/ccxtpro/ftx.py#L292-L298) `self.format_scientific_notation_ftx(n)`.

However the function [is defined](https://github.com/kroitor/ccxt.pro/blob/master/python/ccxtpro/base/exchange.py#L169-L172) with a different name in `exchange.py`: `formatScientificNotationFTX()`.

Therefore I get this error:
`AttributeError: 'ftx' object has no attribute 'format_scientific_notation_ftx'`

Note that in JavaScript the function is defined and called consistently with the CamelCase notation: `formatScientificNotationFTX`.
It must be some problem into the JavaScript to Python names translation.

**Comment by carlosmiei** [comment]
Hello @pietrodn,
yes, it is indeed a problem with names, will be fixed soon. Thanks for letting us know!
