### ISSUE TITLE
Understanding regarding stop loss order

### ISSUE THREAD

**Issue by xsaad67** [ccxt/ccxt#14699]
- OS:Win10
- Programming Language version: Node v14.18.1
- CCXT version:1.9

Consider i place a stop loss order with following parameters
await this.exchange.createOrder('BNB/USDT','limit', 'sell', 0.5, 320.6, 
                {
                    'stopPrice':315.6,
                    'type':'stoplimit'
                });
Market price for BNB is 318.6

As per my understanding this order gets closed on either when the Limit price(320.6) or StopPrice(315.6) reached. Or does this order gets closed when it's price reaches to only stop price which is 315.6?

**Comment by carlosmiei** [comment]
Hello @xsaad67,

I think you're confusing `stop orders/ trigger orders` with `stop Loss/ take profit orders`.  The `stopPrice` simply triggers the order placement in the orderbook. So, in this case, when `BNB/USDT` reaches 315.6 your order will be placed.

Please check this out, it might help you understand better the different order types:
- https://www.binance.com/en/support/faq/360036351051
- https://www.binance.com/en/support/faq/360040016512

**Comment by xsaad67** [comment]
@carlosmiei Thanks for answering but i'm bit of curious then what's the purpose of giving limit amount? as it's not any triggering point

**Comment by carlosmiei** [comment]
@xsaad67 The trigger price sets the moment when the order will be placed into the orderbook. The "limit price" sets the value of the order itself, meaning the price you want to buy/sell the asset. 

For example: You want to buy 0.1 BTC at 25 000 USDT and your `stopPrice` is 27000 USDT.

When BTC reaches 27000 USDT, the exchange will put in the orderbook your order "Buy 0.1 Btc at 25k"

Is it a bit more clear now?

**Comment by ttodua** [comment]
issue should be closed. for future readers, you can take a look in unified methods: https://docs.ccxt.com/#/README?id=stop-loss-orders
let us know if any further issue.
