### ISSUE TITLE
fetchOHLCVV - unified baseVolume & quoteVolume response

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#14704]
The referenced PR will be addressing the pre-determined base-vs-quote volume values in response.

- [x] aax
- [x] ascendex
- [x] bibox
- [x] bigone
- [x] binance (binanceus)
- [x] binancecoinm
- [x] binanceusdm
- [x] bit2c
- [x] bitbank
- [x] bitbns
- [x] bitfinex
- [x] bitfinex2
- [x] bitflyer
- [x] bitforex
- [x] bitget
- [x] bithumb
- [x] bitmart
- [x] bitmex
- [x] bitopro
- [x] bitpanda
- [x] bitrue
- [x] bitso
- [x] bitstamp
- [x] bitstamp1
- [x] bittrex
- [x] bitvavo
- [x] bkex
- [x] bl3p
- [x] blockchaincom
- [x] btcalpha
- [x] btcbox
- [x] btcex
- [x] btcmarkets
- [x] btctradeua
- [x] btcturk
- [x] buda
- [x] bw
- [x] bybit
- [x] bytetrade
- [x] cdax
- [x] cex
- [x] coinbase
- [x] coinbaseprime
- [x] coinbasepro
- [x] coincheck
- [x] coinex
- [x] coinfalcon
- [x] coinmate
- [x] coinone
- [x] coinspot
- [x] crex24
- [x] cryptocom
- [x] currencycom
- [x] delta
- [x] deribit
- [x] digifinex
- [x] eqonex
- [x] exmo
- [x] ftx (ftxus)
- [x] gate (gateio)
- [x] gemini
- [x] hitbtc (fmfwio; bitcoincom; bequant)
- [x] hitbtc3
- [x] hollaex
- [x] huobi (huobipro)
- [x] huobijp
- [x] idex
- [x] independentreserve
- [x] indodax
- [x] itbit
- [x] kraken
- [x] kucoin
- [x] kucoinfutures
- [x] kuna
- [x] latoken
- [x] lbank
- [x] lbank2
- [x] liquid
- [x] luno
- [x] lykke
- [x] mercado
- [x] mexc
- [x] mexc3
- [x] ndax (flowbtc; zipmex)
- [x] novadax
- [x] oceanex
- [x] okcoin
- [x] okx  (okex; okex5)
- [x] paymium
- [x] phemex
- [x] poloniex
- [x] probit
- [x] qtrade
- [x] ripio
- [x] stex
- [x] therock
- [x] tidebit
- [x] tidex
- [x] timex
- [x] tokocrypto
- [x] upbit
- [x] wavesexchange
- [x] wazirx
- [x] whitebit
- [x] woo
- [x] xena
- [x] yobit
- [x] zaif
- [x] zb
- [x] zonda (bitbay)

**Comment by businessengine** [comment]
@ttodua It would be more convenient for `fetchOHLCV` to return both `baseVolume` and `quoteVolume` instead  of only `volume`. That means `ohlcv = [open, high, low, close, baseVolume, quoteVolume]`. Please consider this change.

**Comment by ttodua** [comment]
@businessengine Thanks for suggestion. We have already been discussing that, and part of exchanges doesn't return both volume, and thus, this change only affects `fetchOHLCV`. We might introduce `fetchOHLCVV` which will return both , as we don't want to break existing code (where people use fetchOHLCV with the way it has the data currently). 
We'll make small announcement after this is clarified.

**Comment by ttodua** [comment]
I'll close this issue, as the successor [PR](https://github.com/ccxt/ccxt/pull/14743) takes this into better direction.
