### ISSUE TITLE
Price and amount format is not the same on exchanges

### ISSUE THREAD

**Issue by Curro666** [ccxt/ccxt#14729]
- OS: W10
- Programming Language version: python 3.10.6
- CCXT version: 1.92.32

Hello,
I am performing several tests and I see that the returned values of amount and price do not have the same format. Is it normal or is it an error? I personally like the format (int) that Binance and bitfinex have better.

exchange.markets[pair]['precision']['amount']
exchange.markets[pair]['precision']['price']

Exchange Binance price 2
Exchange Binance amount 5
Exchange Bitfinex price 5
Exchange Bitfinex amount 8
Exchange Bittrex price 1e-08
Exchange Bittrex amount 1e-08
Exchange EXMO price 0.01
Exchange EXMO amount 1e-08
Exchange Huobi price 0.01
Exchange Huobi amount 1e-06
Exchange KuCoin price 0.1
Exchange KuCoin amount 1e-08
Exchange OKX price 0.1
Exchange OKX amount 1e-08
Exchange Poloniex price 2.0
Exchange Poloniex amount 6.0

BR

**Comment by carlosmiei** [comment]
Hello @Curro666,

Please check this out (https://docs.ccxt.com/en/latest/manual.html#precision-and-limits) to understand better what and how precision works in ccxt. Basically, those numbers will vary depending on the precision type (ticker_size, decimal_places, etc)

**Comment by Curro666** [comment]
Hello @carlosmiei,
I understand that there is no exact definition right now and that it can be variable but I think it would be better to define it and format the output.
In my personal case I am using an arbitration bot and I use the data of that field as an integer for the calculations (I use round for this).
I do not use the price and quantity formats offered by ccxt because in some cases it would modify the real data calculated by my bot.
It would be interesting to create a field called, for example, PrecisionPrice and PrecisionAmount to show the values ​​in integer to know how many decimal places those fields have.

int((f'{lot:e}'.split('e')[-1]).replace('-', ''))

Right now I use this to convert the data in that field to give me the integer I need. In some cases I have to do this, in others I have to convert to an integer and in others I take that data as it is in the base but it changes every time there is a new version of ccxt.
I even have to add new lines in the ccxt source code because the necessary data for the conversion does not appear.
For example in OKX I have had to add a new variable (lot) that contains the data I need for the correct conversion.
lot = float(self.safe_string(market, 'lotSz'))
currently ccxt only has this line and does not have the correct data for that conversion
tickSize = self.safe_string(market, 'tickSz')

In arbitration, for example, you have to make calculations on the minimum amount that can be bought or sold based on the balance, also on the amount that is in ask and bid and each exchange uses different decimals in quantity and price, that is why I think it is interesting to field containing an integer.

BR

**Comment by carlosmiei** [comment]
Hello @Curro666 Sorry If I was not clear there is an exact definition regarding precision, but that depends on the exchange. Some exchanges will accept 'X decimal places of precision, whereas others will accept `Y significant digits` or even `Z tick size`. That's the reason we might have different formats there, to be as precise as needed depending on the exchange's needs

**Comment by Curro666** [comment]
Hello @carlosmiei,
sorry, my english is not very good.
It is true what you say that each exchange has different sizes and ways of managing orders with minimum and maximum data both in price and quantity, but in the end all this is summed up in that they have X decimal places and what you send cannot have more decimal places than X.
Even if an exchange has Z tick size the number of decimals is still X

Although X is a variable, it is common to all.
Formerly ccxt had that perfectly formatted and although there were separate fields that contained that information that you mention, there was also the information with integers.
In the current versions of ccxt there is no longer that common format and as i was telling you right now i have modified the original ccxt files to add those fields and all the data is taken from ccxt, there is nothing that I get from another site.

Simply, and it is common for all exchanges, the price field of pair Z has Y decimal places and the amount field of pair Z has Y decimal places.

It's just a suggestion. Precisely i think that the best thing that ccxt has is the formatting and unification of parameters regardless of the structure of each exchange and in the section that i comment there is no common formatting in exchanges.

BR

**Comment by Curro666** [comment]
One example:
BTC/USDT Poloniex
Price  2 decimals
amount 6 decimals
0.000001   The amount min required

You cannot put and order of 0.0000019595 because the max decimals are 6  even if you have met the minimum required quantity limitation

**Comment by cserrb** [comment]
In my case, I have experienced errors with **poloniexfutures**.
The support method **price_to_precision** does not work correctly. Looking at the parameters of the contract (Market) in cctx and in poloniex futures there are differences. ccxt is taking for the precision of the price the attribute **indexPriceTickSize** seems to be, instead of **tickSize** which is the correct one.
This causes the exchange to return an error when formatting a price and creating a limit order with it, because the price should only contain one decimal place instead of two (in this case, BTCUSDTPERP). For this reason I have to do the formatting by hand.
It would be nice to review this part and correct that problem.

**Comment by ttodua** [comment]
late reply, but for future readers, we now everywhere (few exceptions for SIGNIFICANT_DIGITS) use `TICK_SIZE` and nowhere `DECIMAL_PLACES`: https://docs.ccxt.com/#/README?id=precision-mode
