### ISSUE TITLE
Huobi Futures fetch my trades does not use since argument

### ISSUE THREAD

**Issue by acodemics** [ccxt/ccxt#14722]
- OS: Windows
- Programming Language version: Python 3.10
- CCXT version: 1.91.74

When fetching trades for Huobi USDM the library does not use the `since` parameter as part of the query. This causes an issue when using the direction of next (order ascending from start time) as it finds the earliest available trades which are then filtered according to the since paramter.

The work around is to set `start_time` in the params argument. It can be easily fixed in the library by setting the `start_time` field in the request.

```
 huobiApi = ccxt.huobi(
    {
        "apiKey": APIKey,
        "secret": secretKey,
        "options": {
            "defaultType": "swap",
            "defaultSubType": "linear",
            "marginMode": "cross"
        }
    }
)

params = {"direct": "next"}
symbol = 'BTC-USDT'
startTime = round((time.time() - 86400) * 1000)
huobiApi.fetch_my_trades(symbol=self.symbol, since=startTime)
```

**Comment by carlosmiei** [comment]
Hello @acodemics,

We're not using it in the request because the endpoint does not allow it:
https://huobiapi.github.io/docs/usdt_swap/v1/en/#general-query-a-batch-of-trade-records-of-a-contract

**Comment by acodemics** [comment]
Apologies, I wasn't clear enough.

This is about fetching our own historical trades - https://huobiapi.github.io/docs/usdt_swap/v1/en/#cross-get-history-match-results

We are using the `start_time` parameter with `fetch_my_trades` to get the desired behaviour.

**Comment by carlosmiei** [comment]
@acodemics, I'm sorry, I misread it initially and thought you were referring to public trades. However, after taking a second look, I guess you're right we're missing it for derivative markets, will be adding it soon! Thanks for reporting it!

**Comment by acodemics** [comment]
No problem, you might also want to look at the `direct` parameter - by default the end point searches from the `end_time` rather than `start_time`. 

Setting `{"direct": "next"}` should make it in line with expectations.

**Comment by ttodua** [comment]
late reply, was looking into the issues and i've checked the implementation and seems htx supports `since` param for fetchMyTrades.
let us know if anyone has any issue
