### ISSUE TITLE
Poloniex create_order dont work

### ISSUE THREAD

**Issue by Curro666** [ccxt/ccxt#14730]
OS: W10
Programming Language version: python 3.10.6
CCXT version: 1.92.32

Hi, i cannot make orders in poloniex.

Code:

print('CCXTversion', ccxt.__version__)
par = 'SHIB/USDT'
cantidad = 9918377
precio = 0.000064841
opor0 = 'POLONIEX'
tipo  = 'Venta'

try:
    
    order = Poloniex.create_order(par, 'LIMIT', 'SELL', cantidad, precio)
    
    print(order)
except Exception as E:
    print('Error ', E)

I have changed these lines and it works fine

line:1018
        else:
            request['quantity'] = self.amount_to_precision(symbol, amount)
            request['price'] = self.price_to_precision(symbol, price)

        else:
            request['quantity'] = amount
            request['price'] = price

BR

**Comment by carlosmiei** [comment]
Hello @Curro666,

Thanks for reporting, there's indeed an issue with the precision but it will be fixed very soon.

**Comment by Curro666** [comment]
Hello @carlosmiei,
maybe is related to #14729

BR

**Comment by carlosmiei** [comment]
@Curro666 in #14729, only Poloniex values are wrong, which is why we're having this issue with `createOrder`. I've already opened a PR to fix it
