### ISSUE TITLE
[BITMART] It seems Bitmart is going through with discontinueing their tickers endpoint

### ISSUE THREAD

**Issue by DeBelserArne** [ccxt/ccxt#14732]
- OS: Ubuntu 20.04
- Programming Language version: PHP 8.1
- CCXT version: latest

Some time ago I created a ticket #14425 to notify the team that Bitmart was deprecating their tickers endpoint.

It seems that that day has come, since the endpoint is no longer available.
![image](https://user-images.githubusercontent.com/32774303/185365311-044fb25c-471a-49ff-b649-3fe298de40e1.png)

Their support teams asked to use [this endpoint ](https://prod.bitmart.run/v1/ifcontract/api/tickers) for the time being.

I'm wondering how I can make ccxt work with the endpoint they provided? Could anyone point me in the right direction. It confuses me becuase it uses a different domain `prod.bitmart.run` instead of `api-cloud.bitmart.com`

**Comment by sc0Vu** [comment]
Hi,

I think you can update their api urls when initiate exchange object. However, it seems the api route is different (https://prod.bitmart.run/v1/ifcontract/api/tickers). @carlosmiei do we need to integrate this new endpoint?

**Comment by aFluxx** [comment]
Hi @sc0Vu,

Yes indeed, the route is different so even if we update the endpoint the request would end up with a 404.

Their documentation isn't updated either, one of their staff told me they would do it in the future, but by deprecating this endpoint without updating their documentation they will shoot a lot of developers in the knee.

**Comment by aFluxx** [comment]
The endpoint is up again (for how long)

**Comment by ttodua** [comment]
seems this issue is no longer actual. 
let us know if anyone has any issues.
