### ISSUE TITLE
Bitmart tickers 'Not Found' - New endpoints?

### ISSUE THREAD

**Issue by SpenTappy** [ccxt/ccxt#14748]
**Intro**
Hi @kroitor, hope you're well.   Bitmart CCXT code that has been running for months has started failing for some (but not all) instances.
There is a problem with endpoints, sometimes occurring within the 'ccxt.load_markets' initialisation routine, before even trying to retrieve data for specific pairs.  I think it may be something to do with new derivatives ('contracts') on Bitmart having different endpoints, although I am trading spot.  

**Environment**
- OS:  Windows Server
- Programming Language version:  Python 3.9
- CCXT version:  1.92.45  [19-Aug-22, up to date]
(It is the same thing even on some very old CCXT versions, 1.75.65 and even older.)

**Code** - Have hardcoded some values for readability
```
def __init__(self,  config: Dict ):     
    exchange_id = 'bitmart'
    self.exchange_class = getattr(ccxt, exchange_id)     
    self.ccxt = self.exchange_class({ 
        'apiKey': config['apiKey'],         
        'secret': config['secret'],         
        'uid': config['uid'],         
        'options': {             
           'defaultType': 'spot',         
        },         
    'enableRateLimit': True,     
    })     
    self.ccxt.set_sandbox_mode( False)     
    self.ccxt.load_markets()   <- errors out here. In some cases it gets past here but fails at the first 'fetch_orderbook'
```

**Error Output**
```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api-cloud.bitmart.com/contract/v1/tickers

'bitmart {"timestamp":"2022-08-19T14:42:23.760+0000","status":404,"error":"Not Found","message":"Not Found","path":"/v1/tickers"}'
```
BitMart contact says "_you need to use spot endpoint, https://api-cloud.bitmart.com/spot/v1/ticker_"
Could there be an error in CCXT?  Is there a way I can hack bitmart.py to get things working again in the short term?

Thank you for reading

**Comment by sc0Vu** [comment]
There is another issue: ccxt/ccxt#14732 I think their contract tickers api up sometimes.

**Comment by aFluxx** [comment]
Yes, the current api endpoint is wonky, it goes down often. They have a replacement, but this has a different domain. So it's not possible to use this replacement with ccxt.

**Comment by ttodua** [comment]
As this issue is duplicate, any further discussion should be continued int that reference issue
