### ISSUE TITLE
not getting liquidation price from open positions (Binance)

### ISSUE THREAD

**Issue by babydl-abc** [ccxt/ccxt#14747]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10/64bits
- Programming Language version: Python 3.99
- CCXT version:1.9

(Binance)
 liquidation price  = Nane ,   not getting liquidation price ,

```
balance = exchange.fetch_balance()
            positions = balance['info']['positions']
            position_info = pd.DataFrame(positions, columns=["symbol", "entryPrice", "unrealizedProfit", "positionAmt", "positionSide", "liquidationPrice"])
            print(position_info)
```

```
symbol entryPrice unrealizedProfit positionAmt positionSide  liquidationPrice
0  EGLDUSDT       57.4     137.01159805       -31.3        SHORT               NaN
```

**Comment by carlosmiei** [comment]
Hello @babydl-abc If you open Binance's Web Ui and go to your open positions, what do you see here?
![image](https://user-images.githubusercontent.com/43336371/185646912-1f6c1a91-7230-4dc7-8a68-23a140c950bc.png)

**Comment by carlosmiei** [comment]
@babydl-abc if we see '--' it means that the margin allocated to the position is enough to sustain a drop to 0 from the coin and for those cases, we return None in the `liquidationPrice` field (probably not ideal though).

**Comment by babydl-abc** [comment]
> Hello @babydl-abc If you open Binance's Web Ui and go to your open positions, what do you see here? ![image](https://user-images.githubusercontent.com/43336371/185646912-1f6c1a91-7230-4dc7-8a68-23a140c950bc.png)


my position :

[
![position](https://user-images.githubusercontent.com/98079756/185659972-60a0fff7-d539-4fff-b708-d1fcb5de4892.jpg)
](url)

**Comment by ttodua** [comment]
late reply, but I assume this issue should no longer exist, because binance implementation returns liquidation price.
let us know if anyone experiences any issue
