### ISSUE TITLE
Question about exchange.has['postOnly'] == True

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#14742]
- OS: linux
- Programming Language version: python
- CCXT version: 1.92.42

the documentation for timeInForce states that the "PO" unification for timeInForce is a work in progress, and that exchanges supporting that have `postOnly` set to True.
At this point, this seems to be limited to gemini.

Code in ftx and binance suggest that it should be implemented there as well (but "postOnly" is missing from the `.has` object).

Has the flag been forgotten for these exchanges - or is there still something missing for unification of 'PO' orders to be complete for these exchanges?

**Comment by samgermain** [comment]
> * OS: linux
> 
>     * Programming Language version: python
> 
>     * CCXT version: 1.92.42
> 
> 
> the documentation for timeInForce states that the "PO" unification for timeInForce is a work in progress, and that exchanges supporting that have `postOnly` set to True. At this point, this seems to be limited to gemini.
> 
> Code in ftx and binance suggest that it should be implemented there as well (but "postOnly" is missing from the `.has` object).
> 
> Has the flag been forgotten for these exchanges - or is there still something missing for unification of 'PO' orders to be complete for these exchanges?

We actually have a flag inside has as `createPostOnlyOrder`, and you can either set params to `{"postOnly": true}' or `{"timeInForce": "PO"}`

I [created a PR for Binance](https://github.com/ccxt/ccxt/pull/14204) but it hasn't been merged.
I'm not sure why it's not there for FTX yet, I'll add it soon

**Comment by samgermain** [comment]
It looks like ftx has the logic, the flag just wasn't added to has

**Comment by samgermain** [comment]
@kroitor This actually isn't fixed until the [binance PR](https://github.com/ccxt/ccxt/pull/14204) is also merged

**Comment by xmatthias** [comment]
@samgermain Seems like this is still not really fixed (though the linked PR's have been closed).

Binance doesn't have `exchange.has['postOnly'] == True` (as of 2.6.65) - and posting an order as follows doesn't work, but yields `BadRequest: binance {"code":-1106,"msg":"Parameter 'timeInForce' sent when not required."}`.

``` python
import ccxt
exchange = ccxt.binance({'apiKey': '<yourApiKey>', 'secret': '<yoursecret>' })
params = {
    'timeInForce': 'PO'
}
pair = 'SOL/USDT'
o = exchange.create_order(pair, 'limit', 'buy', 1, 15, params=params)
print(res)
```

From the [timeInForce documentation](https://docs.ccxt.com/en/latest/manual.html#timeinforce), i read that it should work that way ?

**Comment by samgermain** [comment]
@xmatthias It looks like this was fixed https://github.com/ccxt/ccxt/commit/148aad74c419f026770044173069ed875f8ebd02 on Jan 9

**Comment by xmatthias** [comment]
Hi @samgermain ,

The code i posted above does work in recent versions for binance (i think it was fixed sometime in March).

however the original question - `exchange.has.get('postOnly') == True`  is still not available for binance (despite PO working as timeInForce) - and now seems to yield true ONLY for gemini - which most likely suggests that this key is obsolete and should be changed in the docs, which (as of today) still shows that this is the key to check.

![image](https://github.com/ccxt/ccxt/assets/5024695/db54de69-33b6-4b9a-82ed-956597d1f217)
