### ISSUE TITLE
UNWATCH* - Unsubscribe from socket streams

### ISSUE THREAD

**Issue by csotto** [ccxt/ccxt#14741]
I am researching for a way to 'unwatch' (Unsubcribe) from a socket stream when it is not needed anymore.
This is request is the same issue as "Manually stop watch* socket #8225", declined/postponed and closed 20 months ago on Jan 8, 2021.

The fundamental problem addressed here is in simple words - Resource Conservation. Releasing no long needed resource is a fundamental demand for system stability and performance.

Since the prior request was declined, I feel I should present my arguments and my facts here:
•	Currently I run a REST-only app using ccxt focused at Binance. 
•	I can monitor 328 symbols using ccxt async_support in dynamic priority schema that updates symbol info with frequencies intervals that varies from 10 to 165 seconds, depending on the outcome of the evaluation algorithm. I am doing this at 45%~65% CPU usage.
•	I want to move some functionality to stream subscription (WATCH) but watching first level data requires high resource usage for one symbol, not to speak about doing it for all 328 symbols at the same time.
•	The natural technical solution would be start WATCHing when algorithm indicate that the Streaming is recommended and release resources by UNWATCHing when it no longer necessary (Probably very few symbols will demand WATCH at the same point in time in a 7x24 schema, but large number of different symbols may request WATCH process a different points in time during a large time span. 
•	I have even made a lab tests of cancelling exclusively the async task that watches some data, without closing the exchange connection, but I found that even after the watch async coroutine has been confirmed cancelled ccxt.pro continues, in background, to receive the watched stream (checked with set exchange.verbose=True). 
•	Furthermore, I also learned that ccxt.pro continues to store the received stream after the cancellation. When starting another async watch coroutine for the same data stream, the first results that are delivered are the old data that ccxt.pro stored after the completion of the task.cancel() command. (All tests done with option 'newUpdates': True)
•	Unwatching, unsubscribing or simply dropping the subscription stream using its handler when respective async task (coroutine) is cancelled will resolve the Resource Conservation issue.  

**Conclusions:**
1) I am struggling to start using ccxtpro capabilities without disrupting the resource equation I have, which is working here, but I could not find a way out for UNWATCH (UNSUBSCRIBE). There is no implicit method I could use since ccxt.pro - internally - must be aware of the UNWATCH request to stop subscribing the streams.
2) Full close of the exchange connection (async exchange.close()), as was suggested at issue #8225 is not an option. I practice ordered startups and shutdowns for all asyncs, I use comprehensive exception handling and frequent log screening, many other efforts to keep uptime high, to be able to monitor market 7 x 24. Completely closing exchange connection would disrupt too many things. 

Unfortunately, I do not feel I have the necessary coding skills to make internal changes to ccxt.pro and propose a pull request.
(I am an old timer TI professional but for many years I had managing responsibilities and was not coding anymore. I have been studying Python for the last 3 years, as I learned about ccxt. I have been using Python async for the last 1 1/2 year I and I am starting subscription streaming tests after I signed up for ccxt.pro last may/2022. I do not feel I am yet capable to help sending a pull request for ccxt.pro.)

Thanks for your attention and for the great piece of software you have developed!

**Comment by csotto** [comment]
I am trying to find out what did I do wrong.

Did I ask a question that was not pertinent?
Did I use improper wording, procedure, or channel in my question?
Have I touched some very delicate subject without knowing it?

I did read throughout the manual and Guidelines before submitting a issue. 
My question is conceptual, focused on server resource conservation. 
The ability to UNSUBSCRIBE from a WebSocket stream is a quite common functionality in crypto exchanges that have SUBSCRIBE method. Asking for UNWATCH for CCXTPRO seems a fair question to me.

If you know why - after eleven days - my issue has received no response or attention so far, please let me know. 
I have no intention of deliberately doing anything wrong. If I made any mistake I will not know it unless someone tells me what is wrong in above **UNWATCH - Unsubscribe from socket streams #14741** issue.

Thanks for the attention.

**Comment by csotto** [comment]
Hi @kroitor, could you please comment on this issue.

**Comment by ttodua** [comment]
unwatch methods has been implemented in some top tier exchanges and is till being added.
If you want to request for specific exchange, let us know.
