### ISSUE TITLE
Question about $exchange->has returns false or null

### ISSUE THREAD

**Issue by pier0074** [ccxt/ccxt#14759]
- OS: linux
- Programming Language version: PHP 8.1
- CCXT version: 1.92.48

I have questions regarding the `has` object.
When a property is not implemented for an exchange, it sometimes returns `null` and sometimes `false`.
It is on purpose that there are 2 different value returned ?

**Comment by samgermain** [comment]
From [the manual](https://docs.ccxt.com/en/latest/manual.html?highlight=has#exchange-metadata)

> - a value of undefined / None / null means the method is not currently implemented in ccxt (either ccxt has not unified it yet or the method isn’t natively available from the exchange API)
> - boolean false specifically means that the endpoint isn’t natively available from the exchange API
> - boolean true means the endpoint is natively available from the exchange API and unified in the ccxt library
> - 'emulated' string means the endpoint isn’t natively available from the exchange API but reconstructed (as much as possible) by the ccxt library from other available true-methods
