### ISSUE TITLE
CCXT pro merge into CCXT in Q3 - status?

### ISSUE THREAD

**Issue by everycoinprice** [ccxt/ccxt#14767]
- OS: MacOS
- Programming Language version: Node.js
- CCXT version: 1.92.52

The CCXT Pro (https://ccxt.pro/) website says that it will become free part of CCXT library in Q3, 2022. But i am not able to find websocket feature in CCXT, while we are in Q3 now, Which is available in CCXT Pro. Is the merge still underway? or is it delayed

Thanks for the great library and the assistance!

![Screenshot 2022-08-22 at 2 54 19 PM](https://user-images.githubusercontent.com/101936368/185829486-3af263e0-b123-4458-aac6-6a8548720be2.png)

**Comment by frosty00** [comment]
the merge is still in progress, we hope to have more updates soon

**Comment by everycoinprice** [comment]
Great, closing the issue

Thanks

**Comment by tileb1** [comment]
@frosty00 great news! Do you have a time estimate for the merge? e.g. is it in the order of weeks or months?

Thanks!
