### ISSUE TITLE
get Future (swap) markets and symbol from exchange

### ISSUE THREAD

**Issue by pier0074** [ccxt/ccxt#14761]
OS: linux
Programming Language version: PHP 8.1
CCXT version: 1.92.48

Hello,

How do I get all future or swap symbols from a specific exchange. It seems to be working fine for binance but not for others.
After reading a lot of issues and comments I did not find the exact answer to my question, closer one was [this one](https://github.com/ccxt/ccxt/issues/14664).

When I instantiate a binance exchange like following, it limits markets and symbols to futureMarket.
```
$binance = new ccxt\binance( [ 'options' => [ 'defaultType' => 'future' ] ] );
$markets = $binance->load_markets();
$symbols = $binance->symbols;
```

However, when I do it to aax or ftx, there are all markets and symbols, exact as if I did **not** include [ 'options' => [ 'defaultType' => 'swap' ] ].

```
$aax = new ccxt\aax( [ 'options' => [ 'defaultType' => 'swap' ] ] );
$markets = $aax->load_markets();
$symbols = $aax->symbols;

$ftx = new ccxt\ftx( [ 'options' => [ 'defaultType' => 'swap' ] ] ); 
$markets = $ftx->load_markets();
$symbols = $ftx->symbols;
```
Both codes return all markets and symbols, include spot ones.

What is included in markets seems to be correct, as it includes the type, for example : 
```
FTX : 
[1INCH/USD:USD] => Array
        (
            [id] => 1INCH-PERP
...
            [type] => swap
)

    [1INCH/USD:USD-220930] => Array
        (
            [id] => 1INCH-0930
            [symbol] => 1INCH/USD:USD-220930
...
            [type] => future
)

AAX: 
    [SOL/USDT:USDT] => Array
        (
            [id] => SOLUSDTFP
            [symbol] => SOL/USDT:USDT
...
            [type] => swap
```

So I think, it would be interesting that load_markets and symbols object would be filtered by type based on 'defaultType'.

**Comment by samgermain** [comment]
What was wrong with [this answer?](https://github.com/ccxt/ccxt/issues/14664)

**Comment by pier0074** [comment]
There is nothing wrong with your answer. 
I just think there is inconsistency in the way markets and symbols are loaded when using options['defaultType'].
As you pointed out, you ftx with the swap options but symbols return more than 800 symbols whereas -Perp (really swap symbols usable in ftx future) are less than 150. When loading ftx with options['defaultType']= 'swap', the symbols array should reduced to the ones that are actually future and tradable in ftx future (-perp one in the case of ftx).
Ftx is not the only exchange where I think there is inconsistency between the exchange with parameters options['defaultType'] and array of symbols/markets returned.

**Comment by samgermain** [comment]
> There is nothing wrong with your answer. I just think there is inconsistency in the way markets and symbols are loaded when using options['defaultType']. As you pointed out, when you initialize ftx with the swap options, symbols return more than 800 symbols whereas -Perp (really swap symbols usable in ftx future) are less than 150. When loading ftx with options['defaultType']= 'swap', the markets and symbols array should be reduced to the ones that are actually future and tradable in ftx future (-perp one in the case of ftx). Ftx is not the only exchange where I think there is inconsistency between the exchange with parameters options['defaultType'] and array of symbols/markets returned.

- The reason for this is that `ftx` uses one api endpoint to fetch every market available. 
    - `binance` uses a different endpoint for `spot`/`swap`/`future`, and they use the same market ids for `spot`/`swap` (`ADAUSDT` is used for `ADA/USDT` and `ADA/USDT:USDT`). 
    - We have parse methods that take the `marketId` returned from the exchange (`ADAUSDT`) and then give you the unified symbol (`ADA/USDT` or `ADA/USDT:USDT`). 
    - They are the same id on binance, so right now we determine what the symbol is by using the `defaultType`
    - There is a plan to call all the endpoints on binance and create some other way to let the parser work, but I don't know if it will ever happen
- ftx uses different ids for these 2 markets, so `defaultType` isn't needed

**Comment by samgermain** [comment]
I'm going to close this issue, feel free to reopen it if you have any more questions
