### ISSUE TITLE
future vs swap

### ISSUE THREAD

**Issue by pier0074** [ccxt/ccxt#14760]
OS: linux
Programming Language version: PHP 8.1
CCXT version: 1.92.48

From the [documentation](https://docs.ccxt.com/en/latest/manual.html#future), I understand you make the distinction between future for future contracts with an expiry date and swap for perpetual future contracts without expiry date.

**On binance:** 
To have the swap contracts (perpetual futures), we need to initiate with `'defaultType' => 'future'`. Shouldn't it be `'defaultType' => 'swap'` ?
And for the future contracts (with expiry), we need to initiate with `'defaultType' => 'delivery'`. Shouldn't it be `'defaultType' => 'future` ?

Also, on **binanceusdm**, which I understand is the binance perpetual future exchange for binance, the `'has'` object is set to 
```
'has' => array(
                'spot' => true,
                'swap' => null,
                'future' => null,
            ),
```
It should be set to ` 'spot' => false`, and either `'swap' or 'future' to true` , depending on the above comment.

Also, on **binancecoinm**, which I understand is the binance future with expiry date exchange for binance, the `'has'` object is set to 
```
'has' => array(
                'spot' => true,
                'swap' => null,
                'future' => null,
            ),
```
It should be set to ` 'spot' => false`, and either `'swap' or 'future' to true` , depending on the above comment.

**Comment by samgermain** [comment]
Binance remains as the one exchange that isn't using the new naming schema. @kroitor Can we try to get [this PR](https://github.com/ccxt/ccxt/pull/12586) merged immediately?

**Comment by samgermain** [comment]
Duplicat of #11121
