### ISSUE TITLE
Bybit exchange.fetch_ohlcv

### ISSUE THREAD

**Issue by MRCTRADE** [ccxt/ccxt#14771]
I used this code to get the market data history on the BTC/USDT symbol with daily time frame.
Well the data that is returned does not match with the data on the official Bybit platform for the same symbol spot market.
while if I use the same code by changing the exchage in Binance the markets data match perfectly
what could be the problem?

import ccxt
exchange = ccxt.bybit()

ohlc = exchange.fetch_ohlcv('BTC/USDT',timeframe='1d',limit=5)
for candle in ohlc:
    print(candle)

**Comment by pier0074** [comment]
Here is the return from BTC/USDT : 
```
[1660780800000.0, 23335.92, 23594.7, 23097.68, 23187.3, 1689.865001]
[1660867200000.0, 23187.3, 23199.37, 20785.07, 20827.96, 5178.872814]
[1660953600000.0, 20827.96, 21370.11, 20768.12, 21137.82, 2911.976528]
[1661040000000.0, 21137.82, 21783.45, 21068.22, 21516.52, 1931.580462]
[1661126400000.0, 21516.52, 21540.0, 20899.33, 21325.05, 1966.100943]
```

And the value from exchange itself https://www.bybit.com/en-US/trade/spot/BTC/USDT : 
Timestamp 1660780800000 (18.08.2022): 
<img width="581" alt="TS 1660780800000" src="https://user-images.githubusercontent.com/53877621/185978175-4a04f9cd-469f-4bf7-b66e-5c449422712b.png">
Timestamp 1660867200000 (19.08.2022): 
<img width="578" alt="1660867200000" src="https://user-images.githubusercontent.com/53877621/185978239-546a25b9-61ff-458d-8b4e-b305884f688c.png">
And Timestamp 1661040000000 (21.08.2022):
<img width="629" alt="1661040000000" src="https://user-images.githubusercontent.com/53877621/185978483-e599a6ab-c721-4155-a940-2c84161eb0e6.png">

So basically it works and give the exact same information.

Please note that by default bybit on CCXT is configured in 'swap'.
If you want to have spot you need to override it by using : 
`exchange = ccxt.bybit({'options': {'defaultType': 'spot'}})`
Also, on the exchange page make sure you are looking at the spot trading of BTC/USDT and not the price of the derivatives USDT perpetual.

**Comment by kroitor** [comment]
@pier0074 thanks for your great answer to this question!

**Comment by MRCTRADE** [comment]
thank you so much for the very complete and detailed answer, I see that the data match but mine do not
for what reason?

import ccxt
#exchange = ccxt.bybit()
exchange = ccxt.bybit({'options': {'defaultType': 'spot'}})

ohlc = exchange.fetch_ohlcv('BTC/USDT',timeframe='1d',limit=5)
for candle in ohlc:
    print(candle)


Here is the return from BTC/USDT :
[1660867200000, 23188.0, 23198.0, 20754.5, 20819.0, 312308.071]
[1660953600000, 20819.0, 21365.0, 20730.0, 21124.0, 153410.543]
[1661040000000, 21124.0, 21780.0, 21060.5, 21505.5, 134458.04]
[1661126400000, 21505.5, 21538.0, 20858.0, 21382.5, 182711.163]
[1661212800000, 21382.5, 21455.0, 20885.0, 21232.5, 48179.721]

Timestamp 1660867200000 (Friday, 19 August 2022 00:00:00)
<img width="1440" alt="Screenshot 2022-08-23 at 10 43 45" src="https://user-images.githubusercontent.com/49906349/186114077-50389c96-a9fd-4a71-83d1-d694ebc88e93.png">


Timestamp 1660953600000 (Saturday, 20 August 2022 00:00:00)
<img width="1440" alt="Screenshot 2022-08-23 at 10 22 40" src="https://user-images.githubusercontent.com/49906349/186109565-6106b888-4f33-4987-823f-fa04592f78d5.png">

Timestamp 1661040000000 (Sunday, 21 August 2022 00:00:00)
<img width="1440" alt="Screenshot 2022-08-23 at 10 28 57" src="https://user-images.githubusercontent.com/49906349/186112385-001b5753-e0d7-470c-9e96-4b1c05b9d874.png">

Timestamp 1661126400000 (Monday, 22 August 2022 00:00:00)
<img width="1440" alt="Screenshot 2022-08-23 at 10 39 08" src="https://user-images.githubusercontent.com/49906349/186113291-097ff41c-590c-4179-a45e-8ab302b829b0.png">
