### ISSUE TITLE
Currency.com fetch_my_trades issue

### ISSUE THREAD

**Issue by SergeySypalo** [ccxt/ccxt#14793]
Hi there,
I'm unable to fetch my trades if, I guess, symbol contains space

- OS: Windows 11
- Programming Language version: Python 3.10.6
- CCXT version: 1.92.71

The code:
```
exchange.fetch_my_trades('OIL - BRENT/USD')
```
The error:
```
ccxt.base.errors.AuthenticationError: currencycom {"code":"-1025","msg":"Invalid API-key, IP, or permissions for action"}
```
Checked on another pair where I didn't make any trades yet 'CORN/USD', works as expected, returns empty array

**Comment by farisei77** [comment]
> Hi there, I'm unable to fetch my trades if, I guess, symbol contains space
> 
> * OS: Windows 11
> * Programming Language version: Python 3.10.6
> * CCXT version: 1.92.71
> 
> The code:
> 
> ```
> exchange.fetch_my_trades('OIL - BRENT/USD')
> ```
> 
> The error:
> 
> ```
> ccxt.base.errors.AuthenticationError: currencycom {"code":"-1025","msg":"Invalid API-key, IP, or permissions for action"}
> ```
> 
> Checked on another pair where I didn't make any trades yet 'CORN/USD', works as expected, returns empty array

**Comment by carlosmiei** [comment]
Hi @SergeySypalo, is this problem solved with the new API keys?

**Comment by SergeySypalo** [comment]
Nope, I re-created them from scratch before the posting issue here, thought it was a problem with them, but no.

**Comment by carlosmiei** [comment]
@SergeySypalo what do you get when you call for instance `fetch_balance` ?

**Comment by SergeySypalo** [comment]
dict with my balances, as expected.
