### ISSUE TITLE
[Livecoin] Exchange Issues

### ISSUE THREAD

**Issue by FlowOverFail** [ccxt/ccxt#1479]
- OS:  Windows 10 & Ubuntu 16.04
- Programming Language version:  Python and NodeJS
- CCXT version:  Latest
- Exchange: Livecoin
- Method:  Fetch_Ticker

Exchange is taking very long to load and grab the ticker value.  Sometimes it even says the exchange is not available.  However, if you visit the API link directly, it loads the ticker value within 1 second.

**Comment by kroitor** [comment]
@FlowOverFail without seeing your code and measurements, it's hard to tell. But the thing is, if you are measuring one call to fetch_ticker on a freshly created instance, it will preload markets and currencies as well on you first call, as described here: https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

You should not compare this against a single opening of one page:

```
import ccxt
exchange = ccxt.livecoin()
exchange.fetch_ticker('ETH/BTC')  # makes three calls
```

You should be measuring this instead:

```
import ccxt
exchange = ccxt.livecoin()
exchange.load_markets() # force-preload them 
print('Now count seconds, and compare to your browser please...')
print(exchange.fetch_ticker('ETH/BTC')) # does just one call
```

Let us know if it doesn't help.

**Comment by kroitor** [comment]
P.S. @FlowOverFail if you want to see actual requests getting sent, just add `.verbose = True` on your exchange instance like so:
- `exchange = ccxt.livecoin ({ 'verbose': True })`
- or `exchange.verbose = True`
