### ISSUE TITLE
Bybit Unified Margin Account

### ISSUE THREAD

**Issue by eonsmile** [ccxt/ccxt#14804]
https://bybit-exchange.github.io/docs/derivativesV3/unified_margin/#t-introduction

Is anybody going to be able to introduce these endpoints to ccxt?  It seems that the request format has changed from earlier methodologies.

**Comment by sc0Vu** [comment]
Hi @eonsmile 

We've added these api endpoints, now you can call with implicit API methods.

For example:

```JS
// GET /derivatives/v3/public/order-book/L2
bybit.publicGetDerivativesV3PublicOrderBookL2({
  "category":"linear",
  "symbol":"ETHUSDT"
})
```

**Comment by kjnh10** [comment]
can I expect these to be implemented with standard methods like create_order?

**Comment by eonsmile** [comment]
There may be a bug with using cursors in v3:

limit = 1
d = {'category': 'linear', 'limit': limit}
result = bb.private_get_unified_v3_private_position_list(d)['result'] # successful for page 1

d['cursor']=result['nextPageCursor']
result = bb.private_get_unified_v3_private_position_list(d)['result'] # failed for subsequent pages

There seems to be a bybit authentication error: "error sign"

-------------------------------------------------------


Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Local\Programs\Python\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 10, in <module>
  File "C:\OneDrive\Py\venv\lib\site-packages\ccxt\base\exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "C:\OneDrive\Py\venv\lib\site-packages\ccxt\base\exchange.py", line 2612, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "C:\OneDrive\Py\venv\lib\site-packages\ccxt\base\exchange.py", line 2609, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\OneDrive\Py\venv\lib\site-packages\ccxt\base\exchange.py", line 662, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\OneDrive\Py\venv\lib\site-packages\ccxt\bybit.py", line 5091, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "C:\OneDrive\Py\venv\lib\site-packages\ccxt\base\exchange.py", line 2882, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: bybit {"retCode":10004,"retMsg":"error sign!","result":null,"retExtInfo":null,"time":1666842529748}

**Comment by MikaelLind** [comment]
Is there any progress made for this bug? Latest version still have problems with the cursor.

**Comment by frosty00** [comment]
bybit has since been updated to v5

**Comment by LAMBOBLACK666** [comment]
ccxt worked only v5 ?margin spot or no? i cant create limit order in spot USDC x10
