### ISSUE TITLE
Request to add total traded value to fetch_ohlc

### ISSUE THREAD

**Issue by jingyuan-wu** [ccxt/ccxt#14810]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

**Comment by carlosmiei** [comment]
Hello @jingyuan-wu, 

Do you mean the quote volume?

**Comment by jingyuan-wu** [comment]
Yes. for example for BTC/USDT, total traded value during time frame in terms of USDT

**Comment by jingyuan-wu** [comment]
An useful alternative would be to provide a way to return the raw kline/candle api output from the exchange similar to how the fetch_my_trades function works

**Comment by ttodua** [comment]
this issue was also discussed in other topics, however, ccxt does not support it at this moment , but users can make custom overload to include raw info too: https://docs.ccxt.com/#/README?id=get-raw-ohlcv-response
