### ISSUE TITLE
Bitmart Place Batch Orders

### ISSUE THREAD

**Issue by kaiqiangh** [ccxt/ccxt#14811]
- OS: Windows 10
- Programming Language version: PHP 7.4
- CCXT version: ` 1.91.22

![image](https://user-images.githubusercontent.com/9014062/187079166-41d446d3-3dd7-4ccc-a41f-96f713d1dda0.png)

I noted that the Bitmart exchange natively supports to place batch orders in one request (please see the screenshow above). Is it possible to call this API by Bitmart CCXT (as I did not find the revelant code)? Thanks.

Kind regards.
Kai

**Comment by sc0Vu** [comment]
Hi @kaiqiangh 

You can call batch orders with our implicit methods: `privatePostSpotV1SubmitOrder`

**Comment by kaiqiangh** [comment]
> 

Thanks!
