### ISSUE TITLE
Currency.Network structure differs on different exchages?

### ISSUE THREAD

**Issue by LexmanRu** [ccxt/ccxt#14814]
- OS: win 10
- Programming Language version: python 3.10.6
- CCXT version: 1.92.58

Hi. I ran into something incomprehensible when manually comparing structures in (as example) binance.currencies[].networks and huobi.currencies[].networks during debug:

The huobi structure fully complies with the [documentation](https://docs.ccxt.com/en/latest/manual.html#network-structure),
for example: 
**_{'info': {'chain': 'bep20mdx', 'displayName': 'BEP20', 'fullName': '', 'baseChain': 'BSC', 'baseChainProtocol': 'bep20', 'isDynamic': False, 'numOfConfirmations': '30', 'numOfFastConfirmations': '15', 'depositStatus': 'allowed', ...}, 'id': 'bep20mdx', 'network': 'bep20', 'limits': {'withdraw': {...}}, 'active': False, 'deposit': True, 'withdraw': False, 'fee': 0.2, 'precision': 1e-08}_**

but on binance I have this:
**_{'network': 'BSC', 'coin': 'MDX', 'withdrawIntegerMultiple': '0.00000001', 'isDefault': True, 'depositEnable': True, 'withdrawEnable': True, 'depositDesc': '', 'withdrawDesc': '', 'specialTips': '', 'specialWithdrawTips': 'The network you have selected is BSC. Please ensure that the withdrawal address supports the Binance Smart Chain network. You will lose your assets if the chosen platform does not support retrievals.', 'name': 'BNB Smart Chain (BEP20)', 'resetAddressStatus': False, 'addressRegex': '^(0x)[0-9A-Fa-f]{40}$', 'addressRule': '', ...}_**

the fiealds are totally different and the **networks** doesn't look as dict on Binance, but as a list...

The structures got from identical parts of code (cycle).
Where I gone wrong? Thnx.

**Comment by ttodua** [comment]
Thanks for report.
I'll submit a fix today. We are in the process of unification of networks, so keep an eye to updates and our telegram announcement channel.

**Comment by Showgofar** [comment]
> Thanks for report. I'll submit a fix today. We are in the process of unification of networks, so keep an eye to updates and our telegram announcement channel.



What is your Telegram channel btw?

**Comment by LexmanRu** [comment]
one more related issue:

The okx.currency structure now looks this way (example):

{'id': 'DORA', 'numericId': None, 'code': 'DORA', 'precision': 1e-06}

and the 'example' dict is missing (not empty {}), as well as many other parameters.

**Comment by LexmanRu** [comment]
plus one more related issue/question:

some exchanges (f.e. ccxt) has no field 'networks' 

> > Thanks for report. I'll submit a fix today. We are in the process of unification of networks, so keep an eye to updates and our telegram announcement channel.
> 
> What is your Telegram channel btw?

+1

**Comment by ttodua** [comment]
A follow-up: we are waiting for binance's update PR to be merged, and after that I'll be working to implement the needed functionalities with binance

**Comment by ton77v** [comment]
I've also noticed that even though data @ Huobi complies with the unified structure, there's no information about deposit limits while it presents in info. Example from currencies['USDT']['ALGO']:
`{'info': {... 'minDepositAmt': '1', ...}, 'id': 'algousdt', 'network': 'ALGO', 'limits': {'withdraw': {'min': 2.0, 'max': 1000000.0}}, 'active': False, 'deposit': True, 'withdraw': False, 'fee': 0.001, 'precision': 1e-06}`

While @ Gate currencies there are no .network keys at all. Example from currencies['USDT']:
`{'id': 'USDT', 'lowerCaseId': 'usdt', 'name': None, 'code': 'USDT', 'precision': 0.0001, 'info': {...}, 'active': True, 'deposit': True, 'withdraw': True, 'fee': None, 'fees': [], 'limits': {'leverage': {'min': None, 'max': None}, 'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}}`

**Comment by ttodua** [comment]
@carlosmiei 

> > What is your Telegram channel btw?
> 

ccxt's telegram announcements channel is: https://t.me/ccxt_announcements

**Comment by ttodua** [comment]
duplicate of https://github.com/ccxt/ccxt/issues/12795 _(please post further comments there. there is also listed announcement channels of ccxt)_

**Comment by frandey7998** [comment]
test

**Comment by frandey7998** [comment]
test

**Comment by Maciejrybak4** [comment]
@5a72ebf4a2b594f32b0162c687b657bac0dde882

**Comment by Maciejrybak4** [comment]
Macirybak v

**Comment by Maciejrybak4** [comment]
Maciej rybak Jose

**Comment by mrgarri19** [comment]
Please I am new here how may I learn about it
