### ISSUE TITLE
It is possible to serialise FTX or Binance object to Json ?

### ISSUE THREAD

**Issue by filipegalo** [ccxt/ccxt#14824]
- OS: MacOS
- Programming Language version: Python 3.9
- CCXT version: 1.92.87

I'm asking this question because I have a massive list of Customers with their respective credentials. I'm trying to make the application more robust by saving each Customer on Redis. But I'm having problem saving the FTX or Binance objects on Redis.

This is my object:
```
from redis_om import JsonModel
from ccxt.ftx import ftx
class Exchange(JsonModel):
    exchange: ftx
```

This is how I'm building each connection:

```
import ccxt

def exchange_connection(api_key, api_secret_key, exchange, sub_account):
    if exchange == "FTX":
        client = ccxt.ftx({
            'apiKey': api_key,
            'secret': api_secret_key,
            'headers': {
                'FTX-SUBACCOUNT': sub_account,
            }
        })
        
    return client
```

And this is the for cycle where I'm saving each customer on Redis:

```

for user in tqdm(users['users']):
        exchange_object = exchange_connection(user['api_key'], user['api_secret_key'], user['exchange'], user['sub_account'])
        exchange = Exchange(exchange=exchange_object)
        exchange.save()

```

However, it is giving me the error -> TypeError: Object of type 'ftx' is not JSON serializable

Is it possible to serialize the FTX object somehow to JSON?

Thank you.

**Comment by sc0Vu** [comment]
Hi @filipegalo 

There is `describe()` function to get basic configuration of the exchange, eg `exchange.describe()`. To encode user configuration (apiKey or some other credentials), I think you can encode as json and save to Redis in your code.

**Comment by samgermain** [comment]
@filipegalo 

Does this work?

`
import json

...

json.dumps(exchange_object.__dict__)
`

**Comment by filipegalo** [comment]
> @filipegalo
> 
> Does this work?
> 
> ```
> import json
> 
> ...
> 
> json.dumps(exchange_object.__dict__)
> ```

Exception has occurred: TypeError
Object of type type is not JSON serializable

That also doesn't work.


> Hi @filipegalo
> 
> There is `describe()` function to get basic configuration of the exchange (but without user configuration), eg `exchange.describe()`. To encode user configuration (apiKey or some other credentials), I think you can encode as json and save to Redis in your code and initiate next time.

This can be a good approach, whatever I'm trying to achieve something different. 
Imagine that I have 1000 Users with their respective API_KEY and API_SECRET_KEY, it takes a lot of time to build the exchange object with user configurations for all those users. So I was trying to use Redis to save these configurations in the cache. So, when the time came to for example get all their balances it will be faster.

**Comment by samgermain** [comment]
> > @filipegalo
> > Does this work?
> > ```
> > import json
> > 
> > ...
> > 
> > json.dumps(exchange_object.__dict__)
> > ```
> 
> Exception has occurred: TypeError Object of type type is not JSON serializable
> 
> That also doesn't work.
> 
> > Hi @filipegalo
> > There is `describe()` function to get basic configuration of the exchange (but without user configuration), eg `exchange.describe()`. To encode user configuration (apiKey or some other credentials), I think you can encode as json and save to Redis in your code and initiate next time.
> 
> This can be a good approach, whatever I'm trying to achieve something different. Imagine that I have 1000 Users with their respective API_KEY and API_SECRET_KEY, it takes a lot of time to build the exchange object with user configurations for all those users. So I was trying to use Redis to save these configurations in the cache. So, when the time came to for example get all their balances it will be faster.
> 
> Thanks @samgermain & @sc0Vu for your responses!

Could you just overwrite `options['apiKey']` and `options['secret']`?

```
exchange['options']['apiKey'] = user['apiKey']
exchange['options']['apiKey'] = user['secret']
```

**Comment by samgermain** [comment]
> > > @filipegalo
> > > Does this work?
> > > ```
> > > import json
> > > 
> > > ...
> > > 
> > > json.dumps(exchange_object.__dict__)
> > > ```
> > 
> > 
> > Exception has occurred: TypeError Object of type type is not JSON serializable
> > That also doesn't work.
> > > Hi @filipegalo
> > > There is `describe()` function to get basic configuration of the exchange (but without user configuration), eg `exchange.describe()`. To encode user configuration (apiKey or some other credentials), I think you can encode as json and save to Redis in your code and initiate next time.
> > 
> > 
> > This can be a good approach, whatever I'm trying to achieve something different. Imagine that I have 1000 Users with their respective API_KEY and API_SECRET_KEY, it takes a lot of time to build the exchange object with user configurations for all those users. So I was trying to use Redis to save these configurations in the cache. So, when the time came to for example get all their balances it will be faster.
> > Thanks @samgermain & @sc0Vu for your responses!
> 
> Could you just overwrite `options['apiKey']` and `options['secret']`?
> 
> ```
> exchange['options']['apiKey'] = user['apiKey']
> exchange['options']['apiKey'] = user['secret']
> ```

**Comment by ttodua** [comment]
you should try it without `['options']` :
```
exchange['apiKey'] = user['apiKey']
exchange['apiKey'] = user['secret']
```

**Comment by samgermain** [comment]
@filipegalo It looks like this issue has gone stale, I'm going to close it, but feel free to reopen it if you have any more questions
