### ISSUE TITLE
Market-order seems to be broken for `Bitvavo`

### ISSUE THREAD

**Issue by keebrev** [ccxt/ccxt#14828]
- OS: MacOS + Linux (tried on both)
- Programming Language version: Python 3.9
- CCXT version: 1.92.91

It comes down to the following:
```
order = {'symbol': 'BTC/EUR', 'type': 'market', 'side': 'buy', 'amount': 0.00020072, 'price': 23000.0}
exchange.create_order(**order)
```

```
> ccxt.base.errors.BadRequest: bitvavo {"errorCode":205,"error":"amountQuote parameter is invalid."}
```

Verbose mode gave me:
```
fetch Request: bitvavo POST https://api.bitvavo.com/v2/order RequestHeaders: {'BITVAVO-ACCESS-KEY': 'xxx', 'BITVAVO-ACCESS-SIGNATURE': 'xxx', 'BITVAVO-ACCESS-TIMESTAMP': 'xxx', 'BITVAVO-ACCESS-WINDOW': '10000', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"market":"BTC-EUR","side":"buy","orderType":"market","amountQuote":"4.6165"}

fetch Response: bitvavo POST https://api.bitvavo.com/v2/order 400 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '61', 'Connection': 'keep-alive', 'access-control-allow-origin': '*', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'bitvavo-ratelimit-limit': '1000', 'bitvavo-ratelimit-remaining': '999', 'bitvavo-ratelimit-resetat': '1661868780000', 'etag': 'W/"3d-xIczCOb+npzIyrpffTRpH2OZ/UQ"', 'date': 'Tue, 30 Aug 2022 14:12:15 GMT', 'x-envoy-upstream-service-time': '18', 'server': 'istio-envoy', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 614841c4d4b9d16b3be042dd1938400c.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'AMS50-C1', 'X-Amz-Cf-Id': 'xx'} ResponseBody: {"errorCode":205,"error":"amountQuote parameter is invalid."}
```

This worked flawlessly half a year ago. First I thought this would be on my side, however, I never touch the `amountQuote` parameter. Is this a known issue?

Edit: I think the rounding for the 'amountQuote' parameter is off. Could that cause this issue?

**Comment by carlosmiei** [comment]
Hello @keebrev, thanks for reporting it. According to the docs `amountQuote` should be a valid parameter but we will investigate it.

https://docs.bitvavo.com/#tag/Orders/paths/~1order/post

**Comment by keebrev** [comment]
> Hello @keebrev, thanks for reporting it. According to the docs `amountQuote` should be a valid parameter but we will investigate it.
> 
> 
> 
> https://docs.bitvavo.com/#tag/Orders/paths/~1order/post

Hi! Yes I am aware that this is a valid parameter, I already checked the docs, that's why I am confused. Maybe check the rounding of the value for the param. Could have something to do with that.

**Comment by ttodua** [comment]
Late reply, but i was looking in this issue and found that there are `market.limits.cost.min` > 5, so that could be such issues. so, before submitting order "by cost", ensure the cost is above market minimums for that pair.

let us know if anyone has any issues
