### ISSUE TITLE
Poloniex fetch order book doesnt work

### ISSUE THREAD

**Issue by Showgofar** [ccxt/ccxt#14829]
- Programming Language version: PHP 
- CCXT version: latest

After update to latest PHP and latest ccxt i have problem with order book at poloniex (other functions are working fine I can place\cancel order and fetch order data but order book is always empty without any errors)
And I don't know how to find an error

![image](https://user-images.githubusercontent.com/38069687/187591073-009f790b-c7d7-4690-bd1b-556a1a9a9e05.png)

**Comment by sc0Vu** [comment]
@Showgofar oh, it looks like a bug, we'll fix soon.

**Comment by Showgofar** [comment]
seems that it was fixed only at JS version
