### ISSUE TITLE
Anyone have any CCXT code examples for a short sell margin trade on Binance?

### ISSUE THREAD

**Issue by GA-VI** [ccxt/ccxt#14825]
Does anyone have any CCXT code (preferably in Node.js javascript) for margin trading and short selling on Binance?

I am looking for some CCXT code examples which execute the following steps of a short sell within the margin account:

- Borrow some specified cryptocurrency
- Short sell the cryptocurrency
- Repurchase the cryptocurrency some time later at (hopefully) a lower price
- Repay the loaned cryptocurrency

The way this short selling is achieved manually in the Binance app is detailed in [this video](https://www.binance.com/en/support/faq/c5124a83ca4c48468115a5ac7ce7bc24) and [this video](https://www.youtube.com/watch?v=aYsKqOh-E3U). However, I wish to automate the process in Node.js javascript. 

I have Googled extensively, but could not find any complete code examples for such margin trading and short selling.

.

I am also looking for some code examples demonstrating how to trade crypto coins in the margin account. Code which allows one crypto to be traded for another, but within the margin account, not the spot account.

I already have some code for trading coins in the spot account, namely this code:

```
const currencyPair = 'BTC/USDT';
const type = 'market';
const side = 'sell';
const amount = 0.001;

var order = await exchange.createOrder(currencyPair, type, side, amount);
```
But I would like to adapt the above code to work in the Binance margin trading account.

Thanks in advance for any help with this.

**Comment by carlosmiei** [comment]
Hello @GA-VI, we will try to add a few examples very soon

**Comment by GA-VI** [comment]
> Hello @GA-VI, we will try to add a few examples very soon

Thank you carlosmiei, that is very much appreciated.

**Comment by ttodua** [comment]
I'll be posting this example shortly.

**Comment by GA-VI** [comment]
> I'll be posting this example shortly.

Thanks for posting that link, @ttodua. Though I cannot see any code examples of actually short selling a coin in that link. I can only see code which fetches the account balance.

I am looking for some example code for short selling within the Binance margin account.

**Comment by ttodua** [comment]
You should have clicked the `files` under that `PR` to see what file(s) were being submitted in update.
Now PR is merged, and you can see the example snippet in repository too:  https://github.com/ccxt/ccxt/blob/master/examples/js/margin-borrow-buy-sell-repay-example.js

**Comment by GA-VI** [comment]
> You should have clicked the `files` under that `PR` to see what file(s) were being submitted in update.
> Now PR is merged, and you can see the example snippet in repository too: https://github.com/ccxt/ccxt/blob/master/examples/js/margin-borrow-buy-sell-repay-example.js
> thnx

Got it! Thank you so much, @ttodua, really appreciated.

**Comment by GA-VI** [comment]
> You should have clicked the `files` under that `PR` to see what file(s) were being submitted in update.
> Now PR is merged, and you can see the example snippet in repository too: https://github.com/ccxt/ccxt/blob/master/examples/js/margin-borrow-buy-sell-repay-example.js
> thnx

@ttodua , thank you very much for that example code for short selling in the Binance margin account.

Would it be possible for you to add a few more lines of code in your example, that shows (after the short sell is complete) how to repurchase the borrowed cryptocurrency some time later, and then repay the loan? 

How this is done in the Binance app is described at timecode 3:38 of [this video](https://www.youtube.com/watch?v=aYsKqOh-E3U&t=3m38s).

Buying back the borrowed cryptocurrency (hopefully at a lower price) and repaying the loan completes the full cycle of the the short sell and buy back process.

**Comment by ttodua** [comment]
@GA-VI I will try to add the example today, and let you know

**Comment by GA-VI** [comment]
Thank you, @ttodua.
