### ISSUE TITLE
Huobi IOC

### ISSUE THREAD

**Issue by Showgofar** [ccxt/ccxt#14838]
- Programming Language version: PHP
- CCXT version: Latest

One more issue after updating to latest PHP and CCXT

When I am trying create IOC order at huobi I am getting an error 
@
Response:

Caught exception: huobi sell-ioc does not have a value in mapping

@

**Comment by sc0Vu** [comment]
Hi @Showgofar

I can create IOC order, would you like to paste the parameters you used?

**Comment by Showgofar** [comment]
I am sending parameter
"type" : "buy-ioc"
the same way like I am sending 
"immediateOrCancel": 1 
for poloniex

**Comment by Showgofar** [comment]
Is it was changed somehow? because previosly to create IOC order you should send params (and it was diffrent for every exchange)
so we do it like
$response = $ccxt[0]->create_order($pair['pair_symbol'], 'limit', 'buy', floatval($amount), floatval($price), $params);

**Comment by Showgofar** [comment]
seems poloniex also doesnt work that way
but and its works with binance and bitrix for example 
so is there any standardization for IOC orders now?
Because its strange that some exchanges are working fine with parameter and some are ignoring it

**Comment by Showgofar** [comment]
So what i have find out)
Here is manual
![image](https://user-images.githubusercontent.com/38069687/188085581-aaabc593-f2ef-4947-8518-d77681b26551.png)

For binance and poloniex  works fine :
        "timeInForce": "IOC"
for bitrex 
        "timeInForce": "IMMEDIATE_OR_CANCEL" 
otherwise if send 
"timeInForce": "IOC" for bittrex i got an error

Response:

Caught exception: bittrex {"code":"BAD_REQUEST","detail":"Refer to the data field for specific field validation failures or extra fields in the body that were rejected.","data":{"newOrder.timeInForce":["Error converting value \"IOC\" to type 'System.Nullable`1[Bittrex.Platform.Models.TimeInForce]'. Path 'timeInForce', line 1, position 108.","The TimeInForce field is required."]}}

So for  Huobi if i send

        "timeInForce": "IMMEDIATE_OR_CANCEL"  or
        "timeInForce": "IOC"
it creates normal GTC order without any error

if i send 

"type" : "buy-ioc"
I am getting an error

Response:

Caught exception: huobi buy-ioc does not have a value in mapping

**Comment by sc0Vu** [comment]
Hi @Showgofar 

I can create buy-ioc order in spot, also ioc order in swap. Would you like to post the specify script that is reproducible?

**Comment by Showgofar** [comment]
do you use buy-ioc isntead of limit? or you create limit order with buy-ioc  option?
because its completely change the logic. 
In first case we should create exchange specific orders when in second case it still can be unified

**Comment by Showgofar** [comment]
still havent got an idea how to send IOC at huobi - other exchanges are OK for me

**Comment by ttodua** [comment]
@sc0Vu if you have a minute, please drop the example code you execute (an unified example) so issue would become closed. basically, it should be like:
```
ex.createOrder (symbol, 'limit', 'buy', amount, price, {'ioc': true})
```

**Comment by Showgofar** [comment]
Thank you
I had updated to latest version and got new error
so I wasnt even possible to try
Fatal error: Uncaught Error: Class "React\Promise\Deferred" not found in /home/ccxt/php/pro/Future.php:8
 Stack trace: #0 /home/ccxt/ccxt.php(128): require_once() #1 /home/admin.php(928): require('...') #2 {main} thrown in /home/ccxt/php/pro/Future.php on line 8

**Comment by carlosmiei** [comment]
Hello @Showgofar, you probably upgrade from a pre-merge version that's why you getting this error. Just run `composer update` inside your directory to solve it

**Comment by Showgofar** [comment]
yep, but i was always update it like that (direct download and replace php files)

**Comment by Showgofar** [comment]
> @sc0Vu 
> ex.createOrder (symbol, 'limit', 'buy', amount, price, {'timeInForce': 'ioc'})
this doesn't work as I mentioned above - parameter is just ignored

**Comment by carlosmiei** [comment]
@Showgofar 

> yep, but i was always update it like that (direct download and replace php files)

We know, but the ccxt.pro added a new dependency, after doing it once (composer update) it should be fine and you can't keep downloading + replacing


> this doesn't work as I mentioned above - parameter is just ignored

what if you send it as `order_price_type`? example: `ex.createOrder (symbol, 'limit', 'buy', amount, price, {'order_price_type': 'ioc'})` 

can you check if this works for you? ⬆️

**Comment by Showgofar** [comment]
> We know, but the ccxt.pro added a new dependency, after doing it once (composer update) it should be fine and you can't keep downloading + replacing

ok it works fine thank you

> what if you send it as `order_price_type`? example: `ex.createOrder (symbol, 'limit', 'buy', amount, price, {'order_price_type': 'ioc'})`
> 
> can you check if this works for you? ⬆️
no, still the same it creates limit order

**Comment by carlosmiei** [comment]
@Showgofar Hello again, an IOC order is a limit order in its essence so you can't have a market IOC order, the only difference between a regular limit order is if it does not find an opposite matching order in the orderbook, is immediately canceled. 
![image](https://user-images.githubusercontent.com/43336371/197993459-b686dad1-ac79-44b5-b8a7-4b95711cf39c.png)

**Comment by Showgofar** [comment]
ok) I know well what is IOC)
let say other way it still create GTC limit order

**Comment by carlosmiei** [comment]
@Showgofar By default `limit` orders are GTC, so by doing this:
`ex.createOrder (symbol, 'limit', 'buy', amount, price)`  you create a limit (gtc by default) order

**Comment by Showgofar** [comment]
yes I understood
I am using IOC orders several years
and 
as i said before
For binance and poloniex works fine :
"timeInForce": "IOC"
for bitrex works (its not unified)
"timeInForce": "IMMEDIATE_OR_CANCEL"

for huobi doesnt work:
"timeInForce": "IOC"
"timeInForce": "IMMEDIATE_OR_CANCEL"
"order_price_type": "ioc"

**Comment by carlosmiei** [comment]
@Showgofar as you can see in my image above, using `order_price_type` I managed to place an IOC order at huobi

**Comment by ttodua** [comment]
Late reply, but I have been testing this issue and found the IOC orders are working as intended:
```
const result = await e.create_order("LTC/USDT:USDT",  "limit",  "buy",  1,  30, {"timeInForce": 'IOC'}  )
```

let us know if anyone have issues
