### ISSUE TITLE
ccxt pro not support watchTickers?

### ISSUE THREAD

**Issue by 583** [ccxt/ccxt#14851]
I was purchased ccxtpro. But I have a problem.
The ccxt pro code show that watchTickers is false.
But watchTicker only support one symbol, I want to get all perp symbol price list, because I want get a price change list like this.
![image](https://user-images.githubusercontent.com/18026534/188108718-404dee70-f4fd-45e4-9335-a4a58ce3d3a0.png)

It is possible to fix it?
Can I only solve this problem by writing a lot of watchtickers?
I saw the binance can get "[All Market Mini Tickers Stream](https://binance-docs.github.io/apidocs/futures/en/#all-market-tickers-streams)" from websocket, how to use it via ccxt pro?

**Comment by KevinMyDing** [comment]
You can use watch_ticker.    
Like this:    
```python
    while 1:
        symbol = 'BTC/USDT:USDT'

        data = await exchange.watch_ticker(symbol)
        print(data)
```

**Comment by 583** [comment]
> You can use watch_ticker. Like this:
> 
> ```python
> async def run(symbol):
>     while 1:
>         data = await exchange.watch_ticker(symbol)
>         print(data)
> 
> async def watch_tickers():
>     swap_list = await exchange.fetch_tickers(params={'instType': 'SWAP'})
>     swap_list = [v for k, v in swap_list.items() if
>                  '/USDT:USDT' in v['symbol']]
> 
>     try:
>         await asyncio.gather(*[run(x['symbol']) for x in swap_list])
> 
>     except Exception as e:
>         logger.error(e)
> asyncio.run(watch_tickers())
> ```

Thanks.
I try get get swap tickers via the following code
`

var exchange = new window.ccxt.binance();
var tks = await exchange.fetchTickers({'instType': 'SWAP'});
console.log(tks);

`
but it return Object {  }
and try again with following code
`

var exchange = new window.ccxt.binance();
var tks = await exchange.fetchTickers();
console.log(tks);

`
it return Object { "ETH/BTC": {…}, "LTC/BTC": {…}, "BNB/BTC": {…}, "NEO/BTC": {…}, "QTUM/ETH": {…}, "EOS/ETH": {…}, "SNT/ETH": {…}, "BNT/ETH": {…}, "BCC/BTC": {…}, "GAS/BTC": {…}, … }

But it's not a perpetual contract, how to get perpetual contract?

**Comment by ttodua** [comment]
@583 
use this:
```
var exchange = new window.ccxt.binance();  
exchange.options.defaultType = 'swap'; // can be 'swap', 'future'
exchange.options.defaultSubType = 'linear'; // can be 'linear', 'inverse'
var tks = await exchange.fetchTickers();  
console.log(tks);  
```
