### ISSUE TITLE
HuobiPro: Signature not valid

### ISSUE THREAD

**Issue by tobiasredel** [ccxt/ccxt#1485]
- OS: Mac
- Programming Language version: PHP 7.1.13
- CCXT version: 1.10.837
- Exchange: HuobiPro
- Method: fetchBalance()

Iam trying to fetch my balance from HuobiPro but i get an error response from HuobiPro everytime i try to access a private method (using my api credentials) - the error response says that the calculated signature is wrong:

`{"status":"error","err-code":"api-signature-not-valid","err-msg":"Signature` not valid: 校验失败","data":null}`

The request in verbose mode looks like that (I replaces my keyId with ###):
`Request:
Array
(
    [0] => GET
    [1] => https://api.huobi.pro/v1/account/accounts?AccessKeyId=###&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2018-01-25T08%3A13%3A02&Signature=mgOSp3q5NhH6A4kRK%2BMbTcm%2FD2RwR5VAualNUMjrUkk%3D
    [2] => Array
        (
            [User-Agent] => Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36
        )

    [3] => 
)
`

All public methods from HuobiPro seem to work - only private methods where signature is required do fail. I already deleted and created new api keys to check if that could cause the error - but the signature not valid error persists.

Can anyone check if the signature calculation is wrong - or if it is just an issue on my end?

**Comment by kroitor** [comment]
Is this a new keypair or it has been used already? Have you tried with a fresh new keypair?

**Comment by tobiasredel** [comment]
I created fresh keypairs yesterday - but the error persists.

**Comment by kroitor** [comment]
Yes, sorry, missed it in your original post. Will look into it and will get back to you.

**Comment by imikay** [comment]
Python version ccxt-1.10.911 had this issue as well:
  

> ccxt.base.errors.ExchangeError: huobipro {"status":"error","err-code":"api-signature-not-valid","err-msg":"Signature not valid: \u6821\u9a8c\u5931\u8d25","data":null}

**Comment by kroitor** [comment]
@imikay make sure your time is synchronized once every 10 minutes and your timezone is UTC (non-DST). It's the same issue as here: #850 . Also make sure your keys are correct.

**Comment by imikay** [comment]
Worked perfect well hours before, but broken after upgrading to the latest version. Keys and time are checked, maybe something changed in the new version? 

Thanks for the quick reply.

**Comment by kroitor** [comment]
@imikay hard to tell, without seeing the full report from you as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
Trying to reproduce it in Py2/3 on my side and in JS, and not having the signature problem... Need to know much more about your environment, your code and your **verbose output***.

**Comment by imikay** [comment]
Found the problem, I reset the api endpoint upon initialization, this broke the signature:

> ccxt.huobipro({'apiKey': os.environ['HUOBIPRO_API_KEY'],
>                           'secret': os.environ['HUOBIPRO_API_SECRET'],
>                           'urls': {'api': 'https://api.huobipro.com'}})

**Comment by kroitor** [comment]
@imikay ok, so, now it works for you normally, right?

**Comment by imikay** [comment]
Yes, it works now. Thanks.

**Comment by infinityCounter** [comment]
Reporting similar issue, I used the code straight from https://github.com/huobiapi/REST-API-demos/blob/master/REST-GO-demo/untils/Untils.go to sign and make the request

**Comment by izoomrud** [comment]
can you help me pls, i have same trouble

```
date_default_timezone_set("Etc/GMT+0");

//$url = '/v1/query/deposit-withdraw';
$url = '/v1/account/accounts';
$request['AccessKeyId'] = $api_key;
$request['SignatureMethod'] = 'HmacSHA256';
$request['SignatureVersion'] = 2;
//$request['Timestamp'] = date("Y-m-d\TH:i:s", $wallet_status['data']/1000);
$request['Timestamp'] = date("Y-m-d\TH:i:s", time());

$request = http_build_query($request);

$query = 'GET\napi.huobi.pro\n' . $url . '\n' . $request; echo $query.'</br>';
$signature['Signature'] = base64_encode(hash_hmac('sha256', $query, $api_secret, true));
$signature = http_build_query($signature);
$endpoint = $baseurl . $url . '?' . $request . '&' . $signature;
echo $endpoint.'</br>';

$ch = curl_init();
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); // return into a variable
curl_setopt($ch, CURLOPT_URL, $endpoint);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
$data = curl_exec($ch); 
$wallet_status = json_decode($data, true); 
curl_close($ch);
```

**Comment by kroitor** [comment]
@izoomrud see how it's implemented here: https://github.com/ccxt/ccxt/blob/master/php/huobipro.php#L959

**Comment by izoomrud** [comment]
it is difficult to understand

**Comment by kroitor** [comment]
@izoomrud try double quotes around `"\n"`:

```PHP
mbp:ccxt igorkroitor$ php -a
Interactive shell

php > echo '\n';
\n
php > echo "\n";

php >
```

**Comment by izoomrud** [comment]
жесть, помогло, ппц, я столько времени убил на эти 5 строчек кода, спасибо!

**Comment by kroitor** [comment]
@izoomrud more about the difference here: https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.double

**Comment by izoomrud** [comment]
you are grand the best, tx bro!

**Comment by AlexHladun** [comment]
I have the same problem. javascript

**Comment by kroitor** [comment]
@AlexHladun 

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

Please, paste your code (without your keys, but including the exchange instantiation) and your verbose output in this issue.

**Comment by AlexHladun** [comment]
`const privateRequest = async (data, endPoint, type) => {
    const baseUrl = huobiConfig.HOST_URL.slice(8) //api.huobi.pro
    const queryString = qs.stringify({
        AccessKeyId: huobiConfig.API_KEY,
        SignatureMethod: 'HmacSHA256',
        SignatureVersion: 2,
        Timestamp: createTimestamp(),
        ...data
    })
    const preSignedText = [type, baseUrl, endPoint, queryString].join('\n')
    const hmac = HmacSHA256(preSignedText, huobiConfig.API_SECRET)
    const signature = encodeURIComponent(cryptoJs.enc.Base64.stringify(hmac))
    const requestConfig = {
        method: type,
        url: huobiConfig.HOST_URL + endPoint + '?' + `AccessKeyId=${huobiConfig.API_KEY}` + '&SignatureMethod=HmacSHA256' + '&SignatureVersion=2' + `&Timestamp=${createTimestamp()}` + `&Signature=${signature}`,
    };

    try {
        console.log('URL: ', requestConfig.url);
        const response = await axios(requestConfig);
        console.log(response);
        return response;
    }
    catch (err) {
        console.log(err);
        return err;
    }
};`

**Comment by AlexHladun** [comment]
`const privateRequest = async (data, endPoint, type) => {
    const baseUrl = huobiConfig.HOST_URL.slice(8) //api.huobi.pro
    const queryString = qs.stringify({
        AccessKeyId: huobiConfig.API_KEY,
        SignatureMethod: 'HmacSHA256',
        SignatureVersion: 2,
        Timestamp: createTimestamp(),
        ...data
    })
    const preSignedText = [type, baseUrl, endPoint, queryString].join('\n')
    const hmac = HmacSHA256(preSignedText, huobiConfig.API_SECRET)
    const signature = encodeURIComponent(cryptoJs.enc.Base64.stringify(hmac))
    const requestConfig = {
        method: type,
        url: huobiConfig.HOST_URL + endPoint + '?' + `AccessKeyId=${huobiConfig.API_KEY}` + '&SignatureMethod=HmacSHA256' + '&SignatureVersion=2' + `&Timestamp=${createTimestamp()}` + `&Signature=${signature}`,
    };

    try {
        console.log('URL: ', requestConfig.url);
        const response = await axios(requestConfig);
        console.log(response);
        return response;
    }
    catch (err) {
        console.log(err);
        return err;
    }
};`

**Comment by kroitor** [comment]
@AlexHladun we can't consult you on your custom code, we can only help if you're using CCXT. With CCXT you can pretty much do everything you would do yourself, although it will help you save your time. Start here:

- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/Manual

**Comment by ivan-digital** [comment]
I am observing periodic error, querying accounts and account balances. Sometimes it respods correct, sometimes wih sifnature validity error. But in parralel I have websocet connection and it works correct all the times.
