### ISSUE TITLE
kucoin add xlm network

### ISSUE THREAD

**Issue by hosseinab** [ccxt/ccxt#14865]
hi
Kucoin does not include XLM network for some currencies .
like this :
{'address': 'GAJ4BSGJE6UQHZAZ5U5IUOABPDCYPKPS3RFS2NVNGFGFXGVQDLBQJW2P', 'network': 'XLM', 'chain': 'XLM', 'tag': '1923105646'}

**Comment by ttodua** [comment]
Hi. Please provide more info, which method you are calling, with what arguments, and what doesn't work.

**Comment by hosseinab** [comment]
run this code :
params = {
      'network': "XLM"
}
fetch_result = connection.fetch_deposit_address("VELO", params)

output :
BadRequest('kucoin Invalid chainId')

**Comment by sc0Vu** [comment]
@hosseinab  It works after this PR merged: https://github.com/ccxt/ccxt/pull/14600

**Comment by hosseinab** [comment]
@sc0Vu please test "XLM" with Capital letters .
Because the fetch_deposit_address function returns chainid in capital letters

**Comment by sc0Vu** [comment]
@hosseinab 

It should work now:

```BASH
$ node examples/js/cli kucoin fetchDepositAddress VELO '{"network":"XLM"}'
Node.js: v14.17.0
CCXT v1.93.54
kucoin.fetchDepositAddress (VELO, [object Object])

{
  info: {
    code: '200000',
    data: {
      address: 'GAxxxxxxxxx',
      memo: '192xxxx',
      chain: 'XLM'
    }
  },
  currency: 'VELO',
  address: 'GAxxxxxxxxx',
  tag: '192xxxx',
  network: 'xlm'
}
```

**Comment by hosseinab** [comment]
@sc0Vu does not work for me . " kucoin Invalid chainId "
this work with "xlm" lowercase characters
