### ISSUE TITLE
Monitor remaining rate of rate limit

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#14869]
from phemex support:

as I said last time, you may add the rate-limit header including contract and other group, and monitor the remaining rate before getting 429, then you may find where it goes unexpected
----

How do you monitor the remaining rate with ccxt? and will it work with many or all exchanges? thanks

**Comment by ttodua** [comment]
Late reply, but a note for future readers - you can make use of exchange prop: `exchange.throttler` and see it's config (remaining and maximum capacities). that is what is available at this moment.

let us know if you have further issues
