### ISSUE TITLE
how to fetch future order book in binance

### ISSUE THREAD

**Issue by pppppico** [ccxt/ccxt#14877]
- OS: macOS
- Programming Language version: 3.10
- CCXT version: 1.92.52

for the spot, i can fetch the price with this

```
spot_price = exchange.fetch_order_book(symbol='MATICUSDT')
print(spot_price)

```
but for the future, it failed                                                                                                                                               
```
future_price = exchange.fetch_order_book(symbol='MATICUSDT_PERP') 
print(future_price)
```
and here is the error info:
`ccxt.base.errors.BadSymbol: binance does not have market symbol MATICUSDT_PERP`

is my symbol structure getting wrong?

**Comment by sc0Vu** [comment]
Hi @pppppico 

In binance, you can fetch order book from different market by setting `type`, eg:

```
exchange.fetch_order_book(symbol='MATIC/USDT', 100, {
  'type': 'future'
}) 
```

**Comment by pppppico** [comment]
@sc0Vu sorry,  but there was a red wavy line under 
` 100, { 'type': 'future'}`

**Comment by sc0Vu** [comment]
@pppppico I updated the script, lmn if you have other question.

**Comment by pppppico** [comment]
@sc0Vu  i get the information with 
`exchange.dapiPublicGetDepth(params={'symbol': 'MATICUSD_PERP', 'LIMIT': 10})`
but still thx for ur help :)
