### ISSUE TITLE
FTX watchorderbook "ftx invalid checksum"

### ISSUE THREAD

**Issue by pickmone** [ccxt/ccxt#14872]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

```
exch = ccxtpro.ftx()
    
while True:
    orderbook = await exch.watch_order_book('BTC/USD:USD', 20)
    print('got orderbook', orderbook['bids'][0][0])
```
hello, after updating the ccxtpro library, after it stream the first orderbook it would keep getting the "ftx invalid checksum" error just from running the above simple code. If I connect to any other exchange (Binance, OKX, etc), it works fine. 

any advice appreciated 
```

**Comment by ryanobjc** [comment]
I also get this.  I modified the exception and got this:
ccxt.base.errors.InvalidNonce: ftx invalid checksum resp: 3136327619 expected 2527839467

This code works correctly in ccxt.pro version 1.1.91 so it's def a regression.

**Comment by ryanobjc** [comment]
I note that sometimes this code does seem to succeed.  The error handling leaves a lot to be desired, the ftx api docs specifically say:
"If not, you have likely lost or mishandled a packet and should re-subscribe to receive the initial snapshot."

**Comment by tintinwyt** [comment]
I got the error as well even after the ccxt pro/ccxt merge!

**Comment by frosty00** [comment]
for now it should work without the limit argument, we will add support for checksums with the limit argument soon

**Comment by samgermain** [comment]
closing as ftx is delisted now
