### ISSUE TITLE
How can I fetch Binance's margin/isolated/Account Equity balance

### ISSUE THREAD

**Issue by avatar-lavventura** [ccxt/ccxt#14878]
I want to fetch `Account Equity` under `Margin/Isolated/Account Equity` from Binance.

<img width="773" alt="image" src="https://user-images.githubusercontent.com/18537398/188486966-e776227e-8a31-46c9-8613-e47bfbd8cc8f.png">

For example I have a position in ORN but when I try following it does not fetch ORN's balance, hence `ORN` does not exist in balance dict.

```
ops["options"] = {
            "adustForTimeDifference": True,
            "defaultType": "margin",
            "fetchBalance": "margin",
            "marginType": "isolated",
}
margin = ccxt.binance(ops)
balances =  await margin.fetch_total_balance()
```

**Comment by sc0Vu** [comment]
Hi @avatar-lavventura 
Have you used `fetchPositions`?

**Comment by avatar-lavventura** [comment]
Let me try `fetchPositions ` but I believe we have to do additional operations to convert `fetchPositions` into `Account Equity` right?

**Comment by avatar-lavventura** [comment]
for `fetch_positions()` I am getting following error:

```bash
    doo = await helper.exchange.margin.fetch_positions()
  File "/home/alper/venv/lib/python3.8/site-packages/ccxt/async_support/binance.py", line
5104, in fetch_positions
    return await self.fetch_positions_risk(symbols, params)
  File "/home/alper/venv/lib/python3.8/site-packages/ccxt/async_support/binance.py", line
5148, in fetch_positions_risk
    await self.load_leverage_brackets(False, params)
  File "/home/alper/venv/lib/python3.8/site-packages/ccxt/async_support/binance.py", line
4982, in load_leverage_brackets
    raise NotSupported(self.id + ' loadLeverageBrackets() supports linear and inverse
contracts only')
ccxt.base.errors.NotSupported: binance loadLeverageBrackets() supports linear and inverse
contracts only
An exception of type NotSupported occurred. Arguments:
('binance loadLeverageBrackets() supports linear and inverse contracts only',)
```

**Comment by samgermain** [comment]
@avatar-lavventura You can call `fetchBalance({"marginMode": "isolated"})`

This is a functionality that I have been adding recently, so it isn't in the documentation yet

**Comment by avatar-lavventura** [comment]
@samgermain Thanks for considiring to adding this functionality. As I understand balances gets all the assets' balances. instead could we get single value that contains only the `Account Equity`?
