### ISSUE TITLE
cctx.pro public date

### ISSUE THREAD

**Issue by xarthurx** [ccxt/ccxt#14876]
This is a more general question about ccxt.pro.

On the website, it says
**CCXT Pro will become a free part of CCXT in Q3 2022**

Is there a specific timeline for that? The beginning of Q3 or ending?

I subscribed to the repo a few months ago for a while, and now want to continue with my work.
Just want to check if I should wait for a few days before the repo will be open to the public.

**Comment by gshpychka** [comment]
@kroitor can you shed some light on this? Q3 ends tomorrow.

**Comment by carlosmiei** [comment]
Hello @xarthurx @gshpychka, we're very very close to releasing it, as you can see here: https://github.com/ccxt/ccxt/pull/15085

**Comment by ttodua** [comment]
It has been merged - https://github.com/ccxt/ccxt/issues/15171 .
