### ISSUE TITLE
Name normalization MGO / EMGO / MGO (ETH) / MGO (WAVE)

### ISSUE THREAD

**Issue by pmizel** [ccxt/ccxt#1487]
there is an issue with name convention for Mobile Go, 

liqui use MGO and is MGO on Etherium
tidex use MGO and is MGO on Waves
tidex use EMGO and is MGO on Etherium

do we need some name normalization?

**Comment by kroitor** [comment]
Yes, we do. Check this out: https://github.com/ccxt/ccxt/blob/master/js/liqui.js#L102
Also: https://github.com/ccxt/ccxt/issues/1330#issuecomment-358271236

**Comment by kroitor** [comment]
What would you propose? Rename MGO → WMGO and EMGO → MGO on tidex?

**Comment by pmizel** [comment]
i know MGO is short and nice but not specific, meybe is better to use EMGO and WMGO for unique identity
but i'm not shure.

HitBTC use EMGO as name too.

**Comment by kroitor** [comment]
We tend to use coinmarketcap symbols... And CMC uses MGO. 75% exchanges will list it under MGO, others will use a unique name. 

Here it is:

```

node examples/js/search-all-exchanges.js MGO

...

--------------------------------------------------------------- (test @ search-all-exchanges.js:90)

Currencies: (test @ search-all-exchanges.js:92)

id    code  exchange       name               active  status  fee  type    payin  payout  transfer
--------------------------------------------------------------------------------------------------
MGO   MGO   allcoin                                                                               
MGO   MGO   coinmarketcap  MobileGo           true    ok                                          
MGO   MGO   cryptopia      MobileGo           true    ok      4                                   
MGO   MGO   gatecoin                                                                              
EMGO  EMGO  hitbtc                                                                                
WMGO  WMGO  hitbtc                                                                                
EMGO  EMGO  hitbtc2        MobileGo           true    ok           crypto  true   true    true    
WMGO  WMGO  hitbtc2        MobileGo on WAVES  false   ok           crypto  false  false   true    
MGO   MGO   liqui                                                                                 
EMGO  EMGO  tidex                                                                                 
MGO   MGO   tidex                                                                                 
MGO   MGO   yobit                                                                                  (test @ search-all-exchanges.js:104)

```

**Comment by kroitor** [comment]
Notice that WMGO is switched off with HitBTC, btw.

**Comment by pmizel** [comment]
I agree. lets do it ;-)

how can i help?

**Comment by kroitor** [comment]
> how can i help?

From above it follows that we need to edit two exchanges:
1. HitBTC
2. Tidex

For HitBTC we just need to add overrides here:
- https://github.com/ccxt/ccxt/blob/master/js/hitbtc2.js#L510
- https://github.com/ccxt/ccxt/blob/master/js/hitbtc.js#L485

For Tidex we need to copy the base method from Liqui:
- https://github.com/ccxt/ccxt/blob/master/js/liqui.js#L102

If you are going to give it a try, please do one exchange at a time. Thx!
