### ISSUE TITLE
bibox transfer

### ISSUE THREAD

**Issue by hosseinab** [ccxt/ccxt#14886]
hi . please add python sample for transfer between accounts in bibox

**Comment by samgermain** [comment]
The transfer method has not been implemented for bibox, I am working on an implementation for it

**Comment by hosseinab** [comment]
@samgermain thank you

**Comment by samgermain** [comment]
I pushed a PR to add transfer to bibox, once it's merged you will be able to use it the same way that [binance transfer](https://github.com/ByteX-Dev/ccxt/blob/3bb0b0a7428943306e8df26ac22d3e57f78ed581/examples/py/binance-universal-transfer.py#L1) is used, but on bibox, all transfers must be made to/from main
