### ISSUE TITLE
create sub account and api key with api ? kucoin has it

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#14888]
can we do this with ccxt?

<img width="1274" alt="Screen Shot 2022-09-06 at 12 13 16 PM" src="https://user-images.githubusercontent.com/70821026/188685424-d1750b99-dadd-4625-9895-e2a7ecb111f9.png">

**Comment by sc0Vu** [comment]
@adamrg73 we've added these apis, you can create api key for sub-account in kucoin:

```JS
exchange.privatePostSubUser({"subName":"******","password":"******"})
exchange.privateGetSubUser()
exchange.privatePostSubApiKey({"subName":"******","passphrase":"******","remark":"******"})
exchange.privatePostSubApiKeyUpdate({"subName":"******","ipWhitelist":"******","apiKey":"******"})
exchange.privateGetSubApiKey()
```
