### ISSUE TITLE
Connection aborted ConnectionResetError10054

### ISSUE THREAD

**Issue by Ahmed089** [ccxt/ccxt#14898]
- OS: Windows
- Programming Language version: Python 3.7
- CCXT version: 1.82.62

could you please let me know the cause of this error & also let me know what are the possibilities to resolve this issue
```
Exception at line 769: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

```

**Comment by carlosmiei** [comment]
Hello @Ahmed089,

That seems a network issue, which exchange are you using?

**Comment by Ahmed089** [comment]
Hello @carlosmiei , It's not network issue from my side & I'm sure about that, we're using the rest endpoint to fetch live price rather than websocket as we haven't found the exact same price in websocket as the Live website shows on Binance so not sure that might be that endpoint issue or not.

This is the rest endpoint we're using to fetch the live price: https://fapi.binance.com/fapi/v1/ticker/price?symbol=BTCUSDT

if you think there is anything else you know to match same price as that price ticker is showing then you can let me know so I can try that too.
