### ISSUE TITLE
Conditional Order Help

### ISSUE THREAD

**Issue by 8ball030** [ccxt/ccxt#1489]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by 8ball030** [comment]
Hi,
I'm using the most recent ccxt and I'm trying to figure out how to use krakens conditional order types in python. 
It would be amazing to have an example as for the life of me I can't figure out how to do it!
I have seen from a previous issue it is possible :)

**Comment by kroitor** [comment]
Hi! 

You should have clarifid what you mean under *conditional order types*. 

If you mean `stop-loss` and those types, that should be as easy as

```Python
import ccxt
exchange = ccxt.kraken({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'SECRET',
})
// see all params here: https://www.kraken.com/en-us/help/api#add-standard-order
kraken_specific_params = {
    'ordertype': 'stop-loss',
    'other': 'field',  # ←------------------ set other params as needed
    'another': 'parameter_of_your_choice',
    # ... 
}
amount = 1.0  # ←---------------------- change your values
price = 1.0
print(exchange.create_order ('limit', 'buy', amount, price, kraken_specific_params))
```

Other params should be overrideable like that. Let us know if it doesn't help.

**Comment by 8ball030** [comment]
Thank you very much for your help here :)
You guys are pros

**Comment by Guillerbr** [comment]
God
