### ISSUE TITLE
bibox fetch_withdrawals has error

### ISSUE THREAD

**Issue by hosseinab** [ccxt/ccxt#14890]
hi
since = None
limit = 200
end_time = connection.milliseconds()
params = {
     'end_time': int(end_time / 1000),
}
withdrawals = connection.fetch_withdrawals("TRX", since, limit, params)

error :
bibox {"error":{"code":"3000","msg":"请求参数错误"},"cmd":"transfer/transferInList"}

**Comment by kubeat** [comment]
i try to debug your code.the param 'limit' too big，you can try change 'limit ' to 100 。bibox Api have update to v3 ,v4,the ccxt is v1
