### ISSUE TITLE
ccxt connect to FTX JP 

### ISSUE THREAD

**Issue by unclecharliecrypto** [ccxt/ccxt#14897]
- OS: macOS (M1)
- CCXT version: 1.93.13

Extend ccxt FTX coverage from current (ftx, ftxus) to also include ftx jp (FTX Japan). 
1. Using Python JupyterNB & FTX JP API keys.
2. Attempt to download FTX JP ETH/USD historical data - n/a
3. Attempt to download parent FTX ALT-PERP historical data - works fine. 
4. The FTX JP API keys return proper FTX JP account balance & order placement, but historical price data still links to parent FTX site.

```

**Comment by sc0Vu** [comment]
Hi @unclecharliecrypto 

After checking how ftx jp works and their api documentation, it seems they use the same api as ftx.com. I can find the markets in ftx jp with ccxt as well.

Would you like to provide produceable scripts (without credentials)?

**Comment by unclecharliecrypto** [comment]
Hi Peter

Ah weird - I followed the 4 steps above and now I can see the FTX JP ETH/USD historical data.
I might have been using the wrong spot pair syntax the first time round? (ETH-USD instead of ETH/USD).
Also tried for XRP/JPY pair and worked fine too.
Apologies for the inconvenience.

Best Regards,
Grant
