### ISSUE TITLE
fetchDepositAddress() error in huobi

### ISSUE THREAD

**Issue by hosseinab** [ccxt/ccxt#14911]
OS: Windows 11
Programming Language version: PYTHON 3.10.5
CCXT version: "ccxt/ccxt": "^1.90.94",
Exchange: huobi
Method: fetchDepositAddress

hi
run this code :
                params = {
                    'network': "bep20",
                }
                fetch_result = connection.fetch_deposit_address("HOTCROSS", params)

output :
huobi fetchDepositAddress() cannot find BEP20 deposit address for HOTCROSS

huobi has bep20 network for HOTCROSS Token

**Comment by sc0Vu** [comment]
Hi @hosseinab 

Thanks, we'll fix this bug soon.
