### ISSUE TITLE
deribit create_market_order issue

### ISSUE THREAD

**Issue by amaioli** [ccxt/ccxt#14919]
- OS: Linux
- Programming Language version: Python 3.9.4
- CCXT version: 1.92.97

```
import ccxt

deribit = ccxt.deribit({"apiKey": key, "secret": secret})

order = deribit.create_market_order('BTC-FUTURE', 'buy', 0.1)
```

```
AttributeError: 'deribit' object has no attribute 'privateGetLong'
```

**Comment by amaioli** [comment]
solved

**Comment by kroitor** [comment]
@amaioli can you elaborate a bit on what was the issue and what was the solution? thx!

**Comment by amaioli** [comment]
I put long instead buy in the side ..

Il Ven 9 Set 2022, 11:57 Igor Kroitor ***@***.***> ha scritto:
