### ISSUE TITLE
[KuCoin future] submit future orders by USDT amount - due to fast price fluctuation

### ISSUE THREAD

**Issue by YuxinSUN89** [ccxt/ccxt#14917]
Hey Team,

I wonder if I could submit buy/short future order by **USDT amount rather than by future quantity** in KuCoin ?

OS: Mac OS
Programming Language version: Python
CCXT version: 1.84.70

I am doing  future trading for months and it runs fine. 
However, I always have issue with just one future **'LUNC/USDT:USDT'**

Lets say I got 500 USDT in my account and each time I want to invest only  440 USDT . 
In the process below, I fetch the latest price, then quantity =  440 / (price * contractSize) 
Due to the fast price fluctuation, the order cannot be filled. 

Here is the error message 
```
ccxt.base.errors.InsufficientFunds: kucoinfutures Balance insufficient. The order would cost 512.34252345623784.
```
So my question here is can I submit future order just by USDT not by order quantity? Thanks

My code is here: 
```
futures_exchange = ccxt.kucoinfutures({
    'apiKey' : config.KUCOIN_API_KEY,
    'secret' : config.KUCOIN_API_SECRET,
    'enableRateLimit': True, 
    'password': config.KUCOIN_PASS_PHRASE,
})

#Get the fund
invest_ratio = 0.88  # -> leave some room for price fluctuation
balance = futures_exchange.fetch_balance()
Total_bal = balance.get('USDT')['total']
fund = int((Total_bal)* invest_ratio)  # fund = 440 USDT

symbol = 'LUNC/USDT:USDT'

#Fetch information for all futures and Get the latest price for 'LUNC/USDT:USDT', and then Calculate the order quantity
future_df = pd.DataFrame(futures_exchange.load_markets()).transpose().reset_index()
future_df = future_df[['symbol','contractSize', 'info']]
future_df['price'] = future_df['info'].apply(lambda x: x.get('lastTradePrice'))  # Get the latest price 
long_df = future_df[future_df['symbol']==symbol ]

try:
    new_long_qty = int((fund)/(long_df['price'].to_list()[0] * long_df['contractSize'].to_list()[0]))
    order = futures_exchange.create_order(max_inst, type='market', side='buy', amount=int(new_long_qty),   params=config.params)
    print('Open new long position %.1f shares of %s.'  %(new_long_qty, symbol ))
 
except Exception as e:
     print('# # # # Something went wrong. Could not Open new long position # # # ')
     print(traceback.format_exc())
 
```

**Comment by evan8623** [comment]
I have the same problem, have you solved it?

**Comment by carlosmiei** [comment]
Hello @YuxinSUN89 @evan8623, I'm afraid that's not possible, Kucoin requires the amount to be in the `base` currency and offers no other alternative

https://docs.kucoin.com/futures/#place-an-order

**Comment by YuxinSUN89** [comment]
> I have the same problem, have you solved it?

Hi I only got a way to workaround. 

That is to set an invest_ratio = 0.95 so every time you invest 95% of your fund. 

When selected ticker is a volatile one, then invest_ratio = 0.8 

In that way, a 20% price fluctuation buffer is created. And hopefully, the price fluctuation wont exceed 20% by the time order submission has been created.

**Comment by ttodua** [comment]
with kucoin futures, it is now possible to send an order with `cost`, e.g.:
```
ord = await e.create_order('DOT/USDT:USDT', 'market', 'buy', None, None, {'cost':20, 'leverage': 10})
```
let us know if further questions
