### ISSUE TITLE
Error Call to undefined function gmp_init() php kucoin 

### ISSUE THREAD

**Issue by a-bahrami** [ccxt/ccxt#14923]
- OS: linux 
- Programming Language version: php 7.4 - laravel 
- CCXT version: latest version 

error in  Precise.php
```

Precise::$base = \gmp_init(10);

```

![image](https://user-images.githubusercontent.com/35418407/189355002-5ff6880c-b307-4954-bce4-504e77853cc3.png)

**Comment by carlosmiei** [comment]
Hello @a-bahrami,
can you please make sure that you have `gmp` correctly loaded?

You can run something like this in your terminal:

```
 php -m |  grep gmp
```

Expected result:

```
gmp
```

**Comment by a-bahrami** [comment]
when i run command nothing happen 

![image](https://user-images.githubusercontent.com/35418407/189399404-01cc3225-b8f7-4362-9e83-b3166f7fd8b0.png)

**Comment by sc0Vu** [comment]
Hi @a-bahrami 
If you have `gmp` installed, it should look like:

```
$ php -m | grep gmp
gmp
```

**Comment by frosty00** [comment]
to add to this you can install gmp with https://www.php.net/manual/en/gmp.installation.php 

```
sudo apt install php-gmp
```

**Comment by ttodua** [comment]
also, you might also try `pickle` to install extensions seamlessly.
let us know if you still have any issues with ccxt
