### ISSUE TITLE
Historical Balances (Question not Issue)

### ISSUE THREAD

**Issue by bonetjoshua** [ccxt/ccxt#14927]
Is there a way to retrieve historical balances using CCXT? I understand that FTX API has the following get API so I was wondering how to incorporate it to CCXT since you need to authenticate yourself in order to use this API.

```
GET /historical_balances/requests/<request_id>
```

```
NA
```

**Comment by sc0Vu** [comment]
Hi @bonetjoshua

Thanks, we'll add these endpoints asap.

**Comment by sc0Vu** [comment]
@bonetjoshua 

We've added historical_balances, you can call these methods with implicit method.

```js
exchange.privateGetHistoricalBalancesRequestsRequestId({
  'request_id': 'xxx',
})
```

**Comment by bonetjoshua** [comment]
Thank you so much @sc0Vu for the help, you guys are awesome. We definitely appreciate your hard work!

**Comment by bonetjoshua** [comment]
@sc0Vu I do have a question, I noticed that the function requires a request_id, but there's also a POST to get those requests, is it possible to do that as well in the same function or that would require a different one?

FTX API DOC:
Request
POST /historical_balances/requests
