### ISSUE TITLE
fetch_balance on bleutrade and cryptopia

### ISSUE THREAD

**Issue by TJoostenNL** [ccxt/ccxt#1492]
- OS: MacOS High Sierra v10.13.2
- Programming Language version: Python 3.6
- CCXT version:
- Exchange: bleutrade and cryptopia
- Method: fetch_balance()

Fetching my balance from both bleutrade and cryptopia doesn't work in my project. 

BLEUTRADE:
```
bleutrade = ccxt.bleutrade({
    'apiKey': 'MY_OWN_API',
    'secret': 'MY_OWN_SECRET',
})
bleutrade.load_markets()

print(bleutrade.fetch_balance())
```
-----
This returns the error:
```
   print(bleutrade.fetch_balance())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/bittrex.py", line 202, in fetch_balance
    balances = response['result']
TypeError: 'NoneType' object is not subscriptable
```
---
CRYPTOPIA:
```
Cryptopia = ccxt.cryptopia()
cryptopia.load_markets()
cryptopia.apiKey = 'MY_OWN_API'
cryptopia.secret = 'MY_SECRET'
print(cryptopia.fetchbalance())
```
----
This causes my Python Shell to stop responding. Shell has been running for over 10 minutes, so I'm guessing that something went wrong.

Could you please help?

**Comment by kroitor** [comment]
Need to do it step by step.

1. Does this work?

```Python
import ccxt
print(ccxt.bleutrade().load_markets())
```

?

**Comment by TJoostenNL** [comment]
This causes my python Shell to stop responding so far for about 1 minute

**Comment by kroitor** [comment]
What's your version of ccxt?

**Comment by TJoostenNL** [comment]
good question, how do I check that (sorry: newbe)

**Comment by kroitor** [comment]
> how do I check that

```
pip list
```

How do you launch your shell?

**Comment by kroitor** [comment]
@TJoostenNL if copypasted the code above in your shell, you have to press Enter after that in order to execute it. Otherwise it will stay on that line waiting for your next move, and it would appear as if nothing happens. Are you sure you know how code in Python?

**Comment by TJoostenNL** [comment]
Just starting, but I'm finding my way around. But hitting enter is not te problem ;)

**Comment by TJoostenNL** [comment]
python3.6 installed on Mac, starting shell via programs / python 3.6 idle

**Comment by TJoostenNL** [comment]
ccxt is version 1.10.809 with pip3  list
and version 1.10840 with pip list

**Comment by TJoostenNL** [comment]
I just ran pip3 install ccxt --upgrade, so now that is also 1.10.840

**Comment by kroitor** [comment]
> I just ran pip3 install ccxt --upgrade, so now that is also 1.10.840

I guess you opened your terminal when you ran that, right?

**Comment by TJoostenNL** [comment]
sure

**Comment by kroitor** [comment]
Ok, then you can launch your python from your Terminal as well.

Do this in your terminal:

```
python --version
python3 --version
```

What is there?

**Comment by TJoostenNL** [comment]
python is version 3.6.3. :: anaconda, inc
python3 is version 3.6.4

**Comment by TJoostenNL** [comment]
running:
import ccxt
print(ccxt.bleutrade().load_markets()) 
in my terminal gives the list of markets no problem btw

**Comment by kroitor** [comment]
Ok, I was going to write how to test it in your terminal. So, this is your setup issue. And, without actually having access to your mac, it would be hard to help. Try not using launching it from Programs, because some different Python gets launched, because you installed many of them somehow?

**Comment by TJoostenNL** [comment]
Ok, I'm gonna try to uninstall and see what that does thanx for the help so far

**Comment by kroitor** [comment]
@TJoostenNL would you mind if I close it for now? Feel free to reopen it if needed, or just ask questions, if any. Ok?

**Comment by TJoostenNL** [comment]
yeah, no problem.
