### ISSUE TITLE
deribit.private_get_get_account_summary() not working on lastest version

### ISSUE THREAD

**Issue by extremk** [ccxt/ccxt#14943]
GetAccountSummary = deribit.private_get_get_account_summary()

private_get_get_account_summary()  not working on lastest version
(<class 'TypeError'>, TypeError('string indices must be integers')

working on previous version 1.7

Please fix it

**Comment by carlosmiei** [comment]
Hello @extremk, I believe that the endpoint you're referring to requires the argument `currency`, and you're not providing it.

Additionally, you could be using the unified method `fetchBalance` instead. 

Example:

```Python
account_summary = deribit.fetch_balance("BTC") # if not provided it will use BTC by default
raw_response = account_summary['info']
````

**Comment by extremk** [comment]
GetAccountSummary = deribit.private_get_get_account_summary({"currency": "ETH"})
Not working at all

In addition, I am not used to obtain the account balance, but the data of the account Delta. The fetch_balance function does not have the ability to obtain the Delta of the account.

CCXT version 1.7, this function is normal, but cannot be used after upgrading to the latest version

**Comment by carlosmiei** [comment]
@extremk, it works on my side, and that stack trace is not that useful, can you show me the code?

```
CCXT v1.93.25
deribit.private_get_get_account_summary({'currency': 'BTC'})
{'jsonrpc': '2.0',
 'result': {'available_funds': '99.0',
            'available_withdrawal_funds': '99.0',
            'balance': '99.0',
            'currency': 'BTC',
            'delta_total': '0.0',
            'delta_total_map': {},
            'deposit_address': 'bcrt1qhe24trh0d34lwh6j5rfmpyr8l9j76g3gey7jgs',
            'equity': '99.0',
            'estimated_liquidation_ratio': '0.0',
            'estimated_liquidation_ratio_map': {},
            'fee_balance': '0.0',
            'futures_pl': '0.0',
            'futures_session_rpl': '0.0',
            'futures_session_upl': '0.0',
            'initial_margin': '0.0',
            'limits': {'matching_engine': {'burst': '20', 'rate': '5'},
                       'non_matching_engine': {'burst': '100', 'rate': '20'}},
            'maintenance_margin': '0.0',
            'margin_balance': '99.0',
            'options_delta': '0.0',
            'options_gamma': '0.0',
            'options_pl': '0.0',
            'options_session_rpl': '0.0',
            'options_session_upl': '0.0',
            'options_theta': '0.0',
            'options_value': '0.0',
            'options_vega': '0.0',
            'portfolio_margining_enabled': False,
            'projected_delta_total': '0.0',
            'projected_initial_margin': '0.0',
            'projected_maintenance_margin': '0.0',
            'session_rpl': '0.0',
            'session_upl': '0.0',
            'total_pl': '0.0'},
 'testnet': True,
 'usDiff': '4250',
 'usIn': '1662808316367892',
 'usOut': '1662808316372142'}
 ```

**Comment by extremk** [comment]
I have found the problem, the old version of CCXT, using
deribit = ccxt.deribit({
    'urls': {
        'api': 'https://www.tibired.com',
        'www': 'https://www.tibired.com',
    },
to change the domain
new version:

    'urls': {
        'api':
            {
                'rest': 'https://www.tibired.com'
            },
        'www': 'https://www.tibired.com',
    },

problem has been fixed
