### ISSUE TITLE
CCXT raises DDoSProtection instead of RateLimitExceeded on Binance

### ISSUE THREAD

**Issue by cfytrok** [ccxt/ccxt#14957]
RateLimitExceeded discribed here
https://github.com/ccxt/ccxt/blob/28909d00c96c7997a9c65a9dc4b3e9c4d916c04c/python/ccxt/binance.py#L1061
but ccxt raises DDoSProtection indstead of RateLimitExceeded 
HTTP response code: 429 
msg: {"code":-1015,"msg":"Too many new orders; current limit is 300 orders per TEN_SECONDS."}
It seems that the problem is in this line.
https://github.com/ccxt/ccxt/blob/28909d00c96c7997a9c65a9dc4b3e9c4d916c04c/python/ccxt/binance.py#L5485

**Comment by samgermain** [comment]
@cfytrok Thanks for the heads up! Do you think you could provide a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for this problem? The line you're referencing is in a general `handle_errors` method, which covers all errors, so I'm not sure how you're running into it, and it also looks like that line is only reachable inside `if (code == 418) or (code == 429):`, so I don't know how you would reach that when the code is `-1015`

**Comment by samgermain** [comment]
Without more information, this issue cannot be resolved
