### ISSUE TITLE
gateio watch_orders for all symbols

### ISSUE THREAD

**Issue by leastchaos** [ccxt/ccxt#14951]
gateio allows all symbols to be read if symbol is set to !all
is it possible to add this functionality to current watch_orders for gateio?
https://www.gate.io/docs/developers/apiv4/ws/en/#orders-channel

- CCXT version: 1.2.29
![image](https://user-images.githubusercontent.com/64965782/189521451-78e06304-20e6-46e5-9e00-33b3681398e2.png)

**Comment by carlosmiei** [comment]
@leastchaos This is supported now.
