### ISSUE TITLE
Can't get only USDT balance with bitget

### ISSUE THREAD

**Issue by karahancodes** [ccxt/ccxt#14954]
Hey , i'm trying to see my usdt balance using fetchbalance , passing USDT as param but i'm getting every coins balance (which is 0.0 by default) on spot. What should i do to get only USDT ? 

- OS: MacOS monterey
- Programming Language version: node v18.7.0
- CCXT version: 1.61.24

``` javascript
const bitget = new ccxt.bitget({
    apiKey : process.env.tn_bitget_key, 
    secret : process.env.tn_bitget_secret,
    password : process.env.tn_bitget_password
    //{defaultType :'swap' }
})
async function bitgetTestfetchBalance () {
    let balance = await bitget.fetchBalance('USDT')
    console.log(balance)
}

```

**Comment by carlosmiei** [comment]
Hello @karahancodes, although you can't do that filtering directly, `fetchBalace` returns a dictionary index by currency, so you can just do this:

```Javascript
    let balance = await bitget.fetchBalance('USDT')
    console.log(balance['USDT'])
```
