### ISSUE TITLE
Kucoin Futures StopLoss/TakeProfit

### ISSUE THREAD

**Issue by reddigszymon** [ccxt/ccxt#14956]
Hello, i am trying to create market order in Kucoin Futures along with a stop loss and take profit.

Is there any way to do it? I've searched through previous issues, but there were no example codes on how to implement it.

Is anyone able to supply me with the code that would be needed to set a stop loss and take profit of any asset? Would be greatly appreciated.

**Comment by fferreizq** [comment]
Hi. I have the same problem. I can open the position but no way to set stoploss or takeprofit. 
Only, "invalid arguments" or closing the position immediately.

Help is welcomed.

**Comment by fferreizq** [comment]
I have tried with this:

// STOPLOSS FOR CLOSING LONG
const params = {
	'stop': 'down',
	'stopPriceType': 'TP',
	'stopPrice': 2.01,
	'reduceOnly': false,
	'closeOrder': true
}
const order = await this.accessBroker.kucoin.futures.createOrder('RUNE:USDT/UST', 'market', 'sell', 100, undefined, params)


But order is triggered immediately instead of waiting that the price get lower than 2.01

**Comment by mixowo** [comment]
I have tried something similiar to you aswell, the market closes the order immediately, rather than wait for the price.

Also, {"code":"429000","msg":"Too Many Requests"} -> i get this error almost every time i try to create an order, sometimes i have to wait for like 30 seconds before i can actually request an order. Do you get this error?

**Comment by fferreizq** [comment]
> I have tried something similiar to you aswell, the market closes the order immediately, rather than wait for the price.
> 
> Also, {"code":"429000","msg":"Too Many Requests"} -> i get this error almost every time i try to create an order, sometimes i have to wait for like 30 seconds before i can actually request an order. Do you get this error?

Yes, I have the same problem. I "sleep" 2 seconds between requests.

**Comment by fferreizq** [comment]
If you set stoploss by using kucoin app, and you list the order created by using ccxt, you can see something like this:

{
    id: 'xxxxxxxxxxx',
    clientOrderId: undefined,
    symbol: 'RUNE/USDT:USDT',
    type: 'market',
    timeInForce: 'IOC',
    postOnly: false,
    side: 'sell',
    amount: 390,
    price: undefined,
    stopPrice: 2.01,
    cost: 0,
    filled: 0,
    remaining: 390,
    timestamp: 1662911948000,
    datetime: '2022-09-11T15:59:08.000Z',
    fee: { currency: undefined, cost: undefined },
    status: 'open',
    info: {
      id: 'xxxxxxxxxxx',
      symbol: 'RUNEUSDTM',
      type: 'market',
      side: 'sell',
      price: null,
      size: 390,
      value: '0',
      dealValue: '0',
      dealSize: 0,
      stp: '',
      stop: 'down',
      stopPriceType: 'TP',
      stopTriggered: null,
      stopPrice: '2.01',
      timeInForce: '',
      postOnly: false,
      hidden: false,
      iceberg: false,
      leverage: '1',
      forceHold: false,
      closeOrder: true,
      visibleSize: null,
      clientOid: null,
      remark: null,
      tags: null,
      isActive: true,
      cancelExist: false,
      createdAt: 1662911948000,
      updatedAt: 1662911948000,
      endAt: null,
      orderTime: null,
      settleCurrency: 'USDT',
      status: 'open',
      filledSize: 0,
      filledValue: '0',
      reduceOnly: false
    },
    lastTradeTimestamp: undefined,
    average: undefined,
    trades: [],
    fees: [ [Object] ]
  }

This is very similar at the order requested by my aplication:
const params = {
'stop': 'down',
'stopPriceType': 'TP',
'stopPrice': 2.01,
'reduceOnly': false,
'closeOrder': true
}
const order = await this.accessBroker.kucoin.futures.createOrder('RUNE/USDT:USDT', 'market', 'sell', 100, undefined, params)

but this one is triggered inmediately... don't know why

**Comment by mixowo** [comment]
Change from 'market' to 'limit'. Should work then, but you have to supply price aswell.

**Comment by onasipim** [comment]
It seems that kucoinfutures.py has not yet implemented the stop order routes. The regular kucoin.py has it
https://docs.kucoin.com/#stop-order

@kroitor Could this be done? Or am I missing something? Thanks

**Comment by Dan-krm** [comment]
The kucoin futures API doesn't allow attaching stop-loss or take-profits to opening an order yet but I've updated the createOrder implementation to allow for emulated stop-loss and take-profit orders. Some examples will be available in this file: **examples/py/kucoinfutures-create-stop-order.py** once the PR is merged.

**Comment by 3ntr0phy** [comment]
Any way to create an order with both stop loss and take profit?

**Comment by Dan-krm** [comment]
> Any way to create an order with both stop loss and take profit?

In this file **examples/py/kucoinfutures-create-stop-order.py** there is two commented out examples of creating emulated stop-loss and take-profit trigger orders. These will be listed as 'stop orders' on the Kucoin website

Currently the Kucoin API doesn't allow attaching a stop-loss and take-profit to an order like you can on the website, but the emulated examples can serve the same purpose
