### ISSUE TITLE
loadMarkets for multiple users?

### ISSUE THREAD

**Issue by emorling** [ccxt/ccxt#14965]
I have a use case where I will be instantiating an exchange for many users. Will I need to perform loadMarkets() for each user? Or can I set markets manually or similar?

**Comment by emorling** [comment]
Seems like I can do this. Will test it out:

`
if (!cctxByBitCache) {
        await bybit.loadMarkets();
        cctxByBitCache = {
          markets: bybit.markets,
          currencies: bybit.currencies,
          markets_by_id: bybit.markets_by_id,
        };
      } else {
        bybit.markets = cctxByBitCache.markts;
        bybit.markets_by_id = cctxByBitCache.markets_by_id;
        bybit.currencies = cctxByBitCache.currencies;
      }`

**Comment by pcriadoperez** [comment]
Hi @emorling,
I'll close this issue because it seems to be solved. But feel free to reopen or post another issue if you have any other questions.
