### ISSUE TITLE
cdax was removed from ccxt but ccxtpro still requires it

### ISSUE THREAD

**Issue by AdamPrisen** [ccxt/ccxt#14961]
Hello i have an issue that from ccxt 1.93.31 and further was async_support.cdax removed but ccxtpro still requires it so when i am trying to run my ccxtpro app a have an error that  there is no module cdax, i have fixed it temporary  that i force to install ccxt 1.93.30 and then ccxtpro 

- OS: macOs Monterey
- Programming Language version: Python 3.10
- CCXT version: 1.93.37
- CCXTPRO version: 1.2.32

```
import ccxtpro
```

```
ModuleNotFoundError: No module named 'ccxt.async_support.cdax'
```

**Comment by carlosmiei** [comment]
Hello @AdamPrisen, thanks a lot for letting us know, it will be fixed very soon!
