### ISSUE TITLE
unify bybit position mode (positionIdx param)

### ISSUE THREAD

**Issue by Hades2525** [ccxt/ccxt#14960]
- OS: Windows 10
- Programming Language version: Python 3.10.7
- CCXT version: 1.93.37

I think it could be nice if there was a way to avoid having to pass the positionIdx param for creating orders in non-hedged mode and this could be unified using something like this:
 
```python
exchange = ccxt.bybit({
    "apiKey": 'apiLey',
    "secret": 'secret',
    "options": {
        "defaultPositionMode": False # or oneWay / hedged
    }
})
```

code for the issue :
```python
import ccxt

symbol = 'BTC/USDT:USDT'
exchange = ccxt.bybit({
    "apiKey": 'apiKey',
    "secret": 'secret'
})

exchange.set_sandbox_mode(True)
# exchange.verbose = True

exchange.load_markets()

try:
    exchange.set_position_mode(hedged=False, symbol=symbol)
except Exception as e:
    print(e)

try:
    exchange.create_order(symbol=symbol, type='limit', side='buy', amount=0.1, price=20000)
except Exception as e:
    print(e)
```

Exception :
```
bybit {"ret_code":130001,"ret_msg":"position idx not match position mode","ext_code":"","ext_info":"","result":null,"time_now":"1662979581.875564","rate_limit_status":87,"rate_limit_reset_ms":1662979581873,"rate_limit":100}
```

Verbose :
```
fetch Request: bybit POST https://api-testnet.bybit.com/private/linear/position/switch-mode RequestHeaders: {'Content-Type': 'application/json', 'Referer': 'CCXT', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"symbol":"BTCUSDT","mode":"MergedSingle","api_key":"api_key","recv_window":5000,"timestamp":"1662979919888","sign":"7b6ab4df54e4bdc4222da2275777a1941e94c247946ce5636193951d9665e5a8"}

fetch Response: bybit POST https://api-testnet.bybit.com/private/linear/position/switch-mode 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '175', 'Server': 'Openresty', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': '*', 'Access-Control-Max-Age': '5', 'Access-Control-Expose-Headers': '*', 'Access-Control-Allow-Headers': 'X-BAPI-API-KEY,X-BAPI-TIMESTAMP,X-BAPI-RECV-WINDOW,X-BAPI-SIGN,X-BAPI-MAKER-API-KEY,X-BAPI-MAKER-SIGN,X-Referer,Content-Type', 'Expires': 'Mon, 12 Sep 2022 10:52:02 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Mon, 12 Sep 2022 10:52:02 GMT', 'Connection': 'keep-alive'} ResponseBody: {"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":"","time_now":"1662979922.693448","rate_limit_status":73,"rate_limit_reset_ms":1662979922688,"rate_limit":75}

fetch Request: bybit POST https://api-testnet.bybit.com/private/linear/order/create RequestHeaders: {'Content-Type': 'application/json', 'Referer': 'CCXT', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"symbol":"BTCUSDT","side":"Buy","order_type":"Limit","time_in_force":"GoodTillCancel","qty":0.1,"reduce_only":false,"close_on_trigger":false,"price":20000.0,"api_key":"api_key","recv_window":5000,"timestamp":"1662979920491","sign":"2dd975d854733322564f94ada627bcd56a42e4ed5750894e5d98eb02efbbdc2f"}

fetch Response: bybit POST https://api-testnet.bybit.com/private/linear/order/create 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '217', 'Server': 'Openresty', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': '*', 'Access-Control-Max-Age': '5', 'Access-Control-Expose-Headers': '*', 'Access-Control-Allow-Headers': 'X-BAPI-API-KEY,X-BAPI-TIMESTAMP,X-BAPI-RECV-WINDOW,X-BAPI-SIGN,X-BAPI-MAKER-API-KEY,X-BAPI-MAKER-SIGN,X-Referer,Content-Type', 'Expires': 'Mon, 12 Sep 2022 10:52:03 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Mon, 12 Sep 2022 10:52:03 GMT', 'Connection': 'keep-alive'} ResponseBody: {"ret_code":130001,"ret_msg":"position idx not match position mode","ext_code":"","ext_info":"","result":null,"time_now":"1662979923.292874","rate_limit_status":98,"rate_limit_reset_ms":1662979923289,"rate_limit":100}
bybit {"ret_code":130001,"ret_msg":"position idx not match position mode","ext_code":"","ext_info":"","result":null,"time_now":"1662979923.292874","rate_limit_status":98,"rate_limit_reset_ms":1662979923289,"rate_limit":100}
```

**Comment by Skanouch** [comment]
You did not set the positionIdx. 

For Non Hedged mode : 
Long:
bybit.create_limit_buy_order(symbol=symbol, amount=trading_qty, price=price, params={'positionIdx': '0'})
Short:
bybit.create_limit_sell_order(symbol=symbol, amount=trading_qty, price=price, params={'positionIdx': '0'})

Hedged Mode Activated:
Long :
bybit.create_limit_buy_order(symbol=symbol, amount=trading_qty, price=price, params={'positionIdx': '1'})
Short:
bybit.create_limit_sell_order(symbol=symbol, amount=trading_qty, price=price, params={'positionIdx': '2'})

**Comment by Utayaki** [comment]
> You did not set the positionIdx.
> 
> For Non Hedged mode : Long: bybit.create_limit_buy_order(symbol=symbol, amount=trading_qty, price=price, params={'positionIdx': '0'}) Short: bybit.create_limit_sell_order(symbol=symbol, amount=trading_qty, price=price, params={'positionIdx': '0'})
> 
> Hedged Mode Activated: Long : bybit.create_limit_buy_order(symbol=symbol, amount=trading_qty, price=price, params={'positionIdx': '1'}) Short: bybit.create_limit_sell_order(symbol=symbol, amount=trading_qty, price=price, params={'positionIdx': '2'})

Though Hedge-Mode is being executed flawlessly; Non-Hedged mode is still broken

`
bybit.create_limit_sell_order("SANDUSDT", 2, 0.8855, params = {"position_idx":0})
`
output is, nevertheless, the same. Same error.

**Comment by Utayaki** [comment]
> You did not set the positionIdx.
> 
> For Non Hedged mode : Long: bybit.create_limit_buy_order(symbol=symbol, amount=trading_qty, price=price, params={'positionIdx': '0'}) Short: bybit.create_limit_sell_order(symbol=symbol, amount=trading_qty, price=price, params={'positionIdx': '0'})
> 
> Hedged Mode Activated: Long : bybit.create_limit_buy_order(symbol=symbol, amount=trading_qty, price=price, params={'positionIdx': '1'}) Short: bybit.create_limit_sell_order(symbol=symbol, amount=trading_qty, price=price, params={'positionIdx': '2'})

SOLVED!!!


The only thing you have to write is 
` 
exchange.set_position_mode(False, symbol="DOGE/USDT:USDT")
`
put it before your initializing an order

"False" here states for "Enabling Hedge-Mode" and symbol is self-explanatory. 
Sorry if I wrote your symbol name wrong, feel free to correct me.

As for my case the line of code was
`
bybit.set_position_mode(False, symbol="SANDUSDT")
`

Have a good day!

**Comment by ttodua** [comment]
late reply, but `hedge/oneway` mode are unified in topmost exchanges, you need to pass `params['hedged'] = true` to specifically set to hedged mode, otherwise `false` (or omit).

let us know if anyone has any issues
