### ISSUE TITLE
how to add margin in isolated future position ?

### ISSUE THREAD

**Issue by gnedoy** [ccxt/ccxt#14962]
hi all
i create isolated future order (binance).
how do i add margin ?
thx

**Comment by carlosmiei** [comment]
Hello @gnedoy, can you try to do something like this?

```Python

exchange = ccxt.binanceusdm({
    'apiKey': 'API_KEY',
    'secret': 'SECRET',
})

symbol = "LTC/USDT" # your symbol here
currency = "USDT" # your currency here
amount = 5 # your amount here

# Example 1: Add (isolated) margin to futures from main account
async def example_1():
    markets = await exchange.load_markets()
    market = exchange.market(symbol)
    
    # Make sure our account is set to cross margin mode
    margin_mode = await exchange.set_margin_mode("isolated", symbol)
    print(margin_mode)

    # Add margin
    params = {
        'type': 'MAIN_UMFUTURE', # All types: https://binance-docs.github.io/apidocs/spot/en/#user-universal-transfer-user_data
        'toSymbol': market['id'] # allocate margin to this symbol
    }
    #add_margin = await exchange.transfer(currency, amount, None, None, params)
    #print(add_margin)

async def main():
   await example_1()
        
asyncio.run(main())

```

**Comment by gnedoy** [comment]
hello, @carlosmiei
thx answer, but not work 
   

>  params = {
>         'type': 'MARGIN_ISOLATEDMARGIN', # All types: https://binance-docs.github.io/apidocs/spot/en/#user-universal-transfer-user_data
>         'toSymbol': market['id'] # allocate margin to this symbol
>     }
>     add_margin = exchange.transfer(currency, amount, None, None, params)
>     print(add_margin)

ccxt.base.errors.AuthenticationError: binanceusdm {"code":-1002,"msg":"You are not authorized to execute this request."}
api key correct

**Comment by carlosmiei** [comment]
Hello @gnedoy, the keys might be correct but may not have the necessary permissions, can you check that, please?

**Comment by samgermain** [comment]
@gnedoy You can use the [`addMargin`](https://docs.ccxt.com/en/latest/manual.html#margin) method to add more margin to your position from your futures wallet

What @carlosmiei is explaining is how to transfer margin from you spot account to your futures account

-------------

regarding your error message, make sure that you have **permits universal transfer** and **enable futures** checked under your **api restrictions** for your api key

![](https://i.imgur.com/se45wVI.png)

**Comment by samgermain** [comment]
I'm going to close this issue. Feel free to reopen it if you have any more quesitons
