### ISSUE TITLE
fetch_deposits and fetch_withdrawals error in lbank2

### ISSUE THREAD

**Issue by hosseinab** [ccxt/ccxt#14972]
OS: Windows 11
Programming Language version: PYTHON 3.10.5
CCXT version: "ccxt/ccxt": "^1.90.94",
Exchange: lbank2
Method: fetch_deposits 

my code : 
        since = None
        limit = 100
        end_time = connection.milliseconds()
       params = {
             'end_time': int(end_time / 1000),
        }
        deposits = connection.fetch_deposits("BTT", since, limit, params)

returns error : 
string indices must be integers

verbose output : 
fetch Request: lbank2 POST https://api.lbank.info/v2/supplement/deposit_history.do RequestHeaders: {'Content-Type': 'application/x-www-form-urlencoded', 'timestamp': '1663008277193', 'signature_method': 'RSA', 'echostr': '**', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: api_key=**&coin=btt&end_time=1663008274&sign=****

fetch Response: lbank2 POST https://api.lbank.info/v2/supplement/deposit_history.do 200 ResponseHeaders: {'Date': 'Mon, 12 Sep 2022 18:44:37 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '353', 'Connection': 'keep-alive', 'Set-Cookie': 'acw_tc=****;path=/;HttpOnly;Max-Age=1800', 'Server': 'openresty', 'Accept-Charset': 'big5, big5-hkscs, cesu-8, euc-jp, euc-kr, gb18030, gb2312, gbk, ibm-thai, ibm00858, ibm01140, ibm01141, ibm01142, ibm01143, ibm01144, ibm01145, ibm01146, ibm01147, ibm01148, ibm01149, ibm037, ibm1026, ibm1047, ibm273, ibm277, ibm278, ibm280, ibm284, ibm285, ibm290, ibm297, ibm420, ibm424, ibm437, ibm500, ibm775, ibm850, ibm852, ibm855, ibm857, ibm860, ibm861, ibm862, ibm863, ibm864, ibm865, ibm866, ibm868, ibm869, ibm870, ibm871, ibm918, iso-2022-cn, iso-2022-jp, iso-2022-jp-2, iso-2022-kr, iso-8859-1, iso-8859-13, iso-8859-15, iso-8859-2, iso-8859-3, iso-8859-4, iso-8859-5, iso-8859-6, iso-8859-7, iso-8859-8, iso-8859-9, jis_x0201, jis_x0212-1990, koi8-r, koi8-u, shift_jis, tis-620, us-ascii, utf-16, utf-16be, utf-16le, utf-32, utf-32be, utf-32le, utf-8, windows-1250, windows-1251, windows-1252, windows-1253, windows-1254, windows-1255, windows-1256, windows-1257, windows-1258, windows-31j, x-big5-hkscs-2001, x-big5-solaris, x-compound_text, x-euc-jp-linux, x-euc-tw, x-eucjp-open, x-ibm1006, x-ibm1025, x-ibm1046, x-ibm1097, x-ibm1098, x-ibm1112, x-ibm1122, x-ibm1123, x-ibm1124, x-ibm1166, x-ibm1364, x-ibm1381, x-ibm1383, x-ibm300, x-ibm33722, x-ibm737, x-ibm833, x-ibm834, x-ibm856, x-ibm874, x-ibm875, x-ibm921, x-ibm922, x-ibm930, x-ibm933, x-ibm935, x-ibm937, x-ibm939, x-ibm942, x-ibm942c, x-ibm943, x-ibm943c, x-ibm948, x-ibm949, x-ibm949c, x-ibm950, x-ibm964, x-ibm970, x-iscii91, x-iso-2022-cn-cns, x-iso-2022-cn-gb, x-iso-8859-11, x-jis0208, x-jisautodetect, x-johab, x-macarabic, x-maccentraleurope, x-maccroatian, x-maccyrillic, x-macdingbat, x-macgreek, x-machebrew, x-maciceland, x-macroman, x-macromania, x-macsymbol, x-macthai, x-macturkish, x-macukraine, x-ms932_0213, x-ms950-hkscs, x-ms950-hkscs-xp, x-mswin-936, x-pck, x-sjis_0213, x-utf-16le-bom, x-utf-32be-bom, x-utf-32le-bom, x-windows-50220, x-windows-50221, x-windows-874, x-windows-949, x-windows-950, x-windows-iso2022jp', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=31536000'} ResponseBody: {"result":true,"data":{"total":1,"depositOrders":[{"insertTime":1663005500000,"amount":4190536.12800000000000000000,"address":"TNF5wyWSmmAo4GxMd2NXZBtSHw47D2JnU4","networkName":"--","txId":"2fbc9c0cbabfbd522aca069a3a7830b62f9b4897057361d32ec4dd3751e55d80","coin":"btt","status":"2"}],"page_length":20,"current_page":1},"error_code":0,"ts":1663008277653}

**Comment by kukiz999** [comment]
> OS: Windows 11
> Programming Language version: PYTHON 3.10.5
> CCXT version: "ccxt/ccxt": "^1.90.94",
> Exchange: lbank2
> Method: fetch_deposits 
> 
> my code : 
>         since = None
>         limit = 100
>         end_time = connection.milliseconds()
>        params = {
>              'end_time': int(end_time / 1000),
>         }
>         deposits = connection.fetch_deposits("BTT", since, limit, params)
> 
> returns error : 
> string indices must be integers
> 
> verbose output : 
> fetch Request: lbank2 POST https://api.lbank.info/v2/supplement/deposit_history.do RequestHeaders: {'Content-Type': 'application/x-www-form-urlencoded', 'timestamp': '1663008277193', 'signature_method': 'RSA', 'echostr': '**', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: api_key=**&coin=btt&end_time=1663008274&sign=****
> 
> 
> fetch Response: lbank2 POST https://api.lbank.info/v2/supplement/deposit_history.do 200 ResponseHeaders: {'Date': 'Mon, 12 Sep 2022 18:44:37 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '353', 'Connection': 'keep-alive', 'Set-Cookie': 'acw_tc=****;path=/;HttpOnly;Max-Age=1800', 'Server': 'openresty', 'Accept-Charset': 'big5, big5-hkscs, cesu-8, euc-jp, euc-kr, gb18030, gb2312, gbk, ibm-thai, ibm00858, ibm01140, ibm01141, ibm01142, ibm01143, ibm01144, ibm01145, ibm01146, ibm01147, ibm01148, ibm01149, ibm037, ibm1026, ibm1047, ibm273, ibm277, ibm278, ibm280, ibm284, ibm285, ibm290, ibm297, ibm420, ibm424, ibm437, ibm500, ibm775, ibm850, ibm852, ibm855, ibm857, ibm860, ibm861, ibm862, ibm863, ibm864, ibm865, ibm866, ibm868, ibm869, ibm870, ibm871, ibm918, iso-2022-cn, iso-2022-jp, iso-2022-jp-2, iso-2022-kr, iso-8859-1, iso-8859-13, iso-8859-15, iso-8859-2, iso-8859-3, iso-8859-4, iso-8859-5, iso-8859-6, iso-8859-7, iso-8859-8, iso-8859-9, jis_x0201, jis_x0212-1990, koi8-r, koi8-u, shift_jis, tis-620, us-ascii, utf-16, utf-16be, utf-16le, utf-32, utf-32be, utf-32le, utf-8, windows-1250, windows-1251, windows-1252, windows-1253, windows-1254, windows-1255, windows-1256, windows-1257, windows-1258, windows-31j, x-big5-hkscs-2001, x-big5-solaris, x-compound_text, x-euc-jp-linux, x-euc-tw, x-eucjp-open, x-ibm1006, x-ibm1025, x-ibm1046, x-ibm1097, x-ibm1098, x-ibm1112, x-ibm1122, x-ibm1123, x-ibm1124, x-ibm1166, x-ibm1364, x-ibm1381, x-ibm1383, x-ibm300, x-ibm33722, x-ibm737, x-ibm833, x-ibm834, x-ibm856, x-ibm874, x-ibm875, x-ibm921, x-ibm922, x-ibm930, x-ibm933, x-ibm935, x-ibm937, x-ibm939, x-ibm942, x-ibm942c, x-ibm943, x-ibm943c, x-ibm948, x-ibm949, x-ibm949c, x-ibm950, x-ibm964, x-ibm970, x-iscii91, x-iso-2022-cn-cns, x-iso-2022-cn-gb, x-iso-8859-11, x-jis0208, x-jisautodetect, x-johab, x-macarabic, x-maccentraleurope, x-maccroatian, x-maccyrillic, x-macdingbat, x-macgreek, x-machebrew, x-maciceland, x-macroman, x-macromania, x-macsymbol, x-macthai, x-macturkish, x-macukraine, x-ms932_0213, x-ms950-hkscs, x-ms950-hkscs-xp, x-mswin-936, x-pck, x-sjis_0213, x-utf-16le-bom, x-utf-32be-bom, x-utf-32le-bom, x-windows-50220, x-windows-50221, x-windows-874, x-windows-949, x-windows-950, x-windows-iso2022jp', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=31536000'} ResponseBody: {"result":true,"data":{"total":1,"depositOrders":[{"insertTime":1663005500000,"amount":4190536.12800000000000000000,"address":"TNF5wyWSmmAo4GxMd2NXZBtSHw47D2JnU4","networkName":"--","txId":"2fbc9c0cbabfbd522aca069a3a7830b62f9b4897057361d32ec4dd3751e55d80","coin":"btt","status":"2"}],"page_length":20,"current_page":1},"error_code":0,"ts":1663008277653}
>

**Comment by ttodua** [comment]
There is no `end_time` in lbank api https://docs.lbkex.net/en/ , but there is `endTime`.
I think you are confusing it with other exchanges. 
`end_time` is being still in process of unification and some exchanges doesn't implement that unified scrpting yet.
For now, as I check lbank api, you have to use `endTime` for that purpose (deposits & withdrawals) and also, it shouldnt be 10-digit integer (in seconds) but should be in 13-digit (milliseconds).

So, please adjust the code and then let us know back.

**Comment by ttodua** [comment]
note, i've tested and seems their `endTime` param doesnt work at all, even if you provide with `integer` or `string` it still ignores that param.

**Comment by ttodua** [comment]
I've further tested and the issue seems specific to `python` and not just related to the lbank api param. I'll submit further fix.

**Comment by ttodua** [comment]
Please update CCXT to latest version, the issue is fixed.

**Comment by hosseinab** [comment]
@ttodua why id is None ?

**Comment by ttodua** [comment]
which `id` you mean, can you please post that part?

**Comment by hosseinab** [comment]
@ttodua 
[{'info': {'insertTime': '1663005500000', 'amount': '4190536.12800000000000000000', 'address': 'TNF5wyWSmmAo4GxMd2NXZBtSHw47D2JnU4', 'networkName': '--', 'txId': '2fbc9c0cbabfbd522aca069a3a7830b62f9b4897057361d32ec4dd3751e55d80', 'coin': 'btt', 'status': '2'}, **'id': None**, 'txid': '2fbc9c0cbabfbd522aca069a3a7830b62f9b4897057361d32ec4dd3751e55d80', 'timestamp': 1663005500000, 'datetime': '2022-09-12T17:58:20.000Z', 'network': '--', 'address': 'TNF5wyWSmmAo4GxMd2NXZBtSHw47D2JnU4', 'addressTo': None, 'addressFrom': 'TNF5wyWSmmAo4GxMd2NXZBtSHw47D2JnU4', 'tag': None, 'tagTo': None, 'tagFrom': None, 'type': 'deposit', 'amount': 4190536.128, 'currency': 'BTT', 'status': 'ok', 'updated': None, 'comment': None, 'internal': False, 'fee': None}]

**Comment by ttodua** [comment]
@hosseinab about `id` not being set - you need to look through your last comment/response carefully and you'll find out why `id` is not being set - the original response doesn't contain any value that refers to `id`, so ccxt doesn't invent values to fill that. As it's seen, the `txid` is available only in original response from exchange API, and that's all we can use in this specific case. 
Hope this is clean now.
