### ISSUE TITLE
lbank2 fetch_deposit_address not have network or chain params

### ISSUE THREAD

**Issue by hosseinab** [ccxt/ccxt#14984]

**Comment by ttodua** [comment]
I've linked a PR above. After merge, you have to input the `network` param, i.e.:
```
const address = await exch.fetch_deposit_address ( 'USDT', {network: 'TRC20'});
```

**Comment by hosseinab** [comment]
@ttodua 
merge not done?

**Comment by hosseinab** [comment]
@cabanossi this merge not approved ?

**Comment by ttodua** [comment]
> @cabanossi this merge not approved ?

You have incorrectly tagged @cabanossi , you have to tag @carlosmiei

**Comment by carlosmiei** [comment]
@ttodua @hosseinab will take a look now, sorry for the delay

**Comment by hosseinab** [comment]
@ttodua i'm sorry . You're right

@carlosmiei thank you
