### ISSUE TITLE
coinbase API calls return swapped bid and ask values

### ISSUE THREAD

**Issue by madelmann** [ccxt/ccxt#14988]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Linux, Ubuntu 18.04
- Programming Language version: PHP 7.2.24-0ubuntu0.18.04.13
- CCXT version: 1.93.43

```
php/coinbase.php:
            //$bid = $this->safe_string($buyData, 'amount');
            $bid = $this->safe_string($sellData, 'amount');
            //$ask = $this->safe_string($sellData, 'amount');
            $ask = $this->safe_string($buyData, 'amount');
```

```
WRONG: "symbol":"BTC\/EUR","timestamp":1663094460304,"datetime":"2022-09-13T18:41:00.304Z","bid":20749.01,"ask":20531.8
CORRECT: "symbol":"BTC\/EUR","timestamp":1663094460304,"datetime":"2022-09-13T18:41:00.304Z","bid":20531.8,"ask":20749.01
```

**Comment by samgermain** [comment]
@madelmann Thanks for letting us know, we've fixed this in PR #14992
