### ISSUE TITLE
fetch(ohlcv) Only Returning One Day Worth of Data for Some Exchanges

### ISSUE THREAD

**Issue by prestoneckhardt** [ccxt/ccxt#14982]
Hello - 

For some larger exchanges such as Binance.US, CoinbasePro, etc., I am able to pull years worth of data with the same lines of code below. For other smaller exchanges notably Bitflyer and itBit, I only get returned 1 day or today's worth of data... No idea what to do if I'm looking to specifically get months worth of data. I have no problems with any other exchanges so far except itbit and bitflyer. Any and all help is so very appreciated.

```
import ccxt
import pandas as pd

names = ['timestamp', 'o', 'h', 'l', 'c', 'v']
exchange = ccxt.itbit()
raw = exchange.fetch_ohlcv('BTC/USD', '1d')
res = [dict(zip(names, i)) for i in raw]
df = pd.DataFrame(res).set_index('timestamp')
df.index = pd.to_datetime(df.index / 1000, unit='s')
print(df)
df.to_csv('btc-usd-itbit.csv')
```

RESULT: (1 day's worth of data = not good!)

```
o        h        l         c          v
timestamp                                                 
2022-09-12  22352.0  22395.0  22274.5  22344.75  10.972934
Process finished with exit code 0```

**Comment by pcriadoperez** [comment]
Hi @prestoneckhardt ,

`Itbit` api does not support a call for `fetch_ohlcv()` therefore the data is built from the most recent trades using this endpoint (https://api.itbit.com/docs#market-data-get-recent-trades-get)

`Bitflyer` is a similar case. Their API does not support `fetch_ohlcv()` therefore it is built from calling `fetchTrades ()` which returns the last 100 trades.
According to it's API you can get up to 31 days of data if you implement pagination (https://lightning.bitflyer.com/docs?lang=en#execution-history)

Let me know if you need help with anything else, if not feel free to close the issue.
