### ISSUE TITLE
ccxt pro support watchPositions?

### ISSUE THREAD

**Issue by 583** [ccxt/ccxt#14985]
I only see the following api, but not perp/futures position api

watchBalance (params)
watchOrders (symbol, since, limit, params) 
watchCreateOrder (symbol, type, side, amount, price, params)
watchCancelOrder (id, symbol, params)
watchMyTrades (symbol, since, limit, params) wip

**Comment by carlosmiei** [comment]
Hello @583, it is definitely in the plans, but we haven't had the chance yet to implement it

**Comment by 583** [comment]
> 

Thanks

**Comment by dawadam** [comment]
I think this pull request is on topic:

https://github.com/ccxt/ccxt/pull/15622
