### ISSUE TITLE
ByBit: General problem with order_link_id

### ISSUE THREAD

**Issue by emorling** [ccxt/ccxt#14989]
There seems to be a general problem with working with orders that are identified by order_link_id. Querying orders with order_link_id is supported in the ByBit API, but not in CCTX. There seems to be notice of ByBit CCTX being reworked in January. Is this still the case?

**Comment by samgermain** [comment]
> There seems to be a general problem with working with orders that are identified by order_link_id. Querying orders with order_link_id is supported in the ByBit API, but not in CCTX. There seems to be notice of ByBit CCTX being reworked in January. Is this still the case?

Can you provide an example of what you're referring to please?

**Comment by emorling** [comment]
@samgermain 

The ByBit API enables us to 

- Get Active Order using order_link_id (not only order_id)
https://bybit-exchange.github.io/docs/futuresV2/linear/#t-getactive
- Cancel Active Order
https://bybit-exchange.github.io/docs/futuresV2/linear/#t-cancelactive
- Replace Active Order
https://bybit-exchange.github.io/docs/futuresV2/linear/#t-cancelallactive

However, these functions in CCXT and ByBit.js only accept order_id.
For example fetchOrder: cancelOrder, editContractOrder

Please advise.
