### ISSUE TITLE
bitget general problem with market symbols 

### ISSUE THREAD

**Issue by karahancodes** [ccxt/ccxt#14990]
Hey , i always have difficulties when i'm trying to parse/fetch by symbol , is there any method to check whole symbols of trading pairs (swap) on bitget? Like for example , i cant fetchmytrades by using btc/usdt

`const bitget = new ccxt.bitget({
    apiKey : process.env.tn_bitget_key, 
    secret : process.env.tn_bitget_secret,
    password : process.env.tn_bitget_password,
    options : {defaultType :'swap'}})

async function bitgetTestmytrades () {
    let trades = await bitget.fetchMyTrades()
    console.log(trades)
}
bitgetTestmytrades('BTC/USDT')
`

**Comment by samgermain** [comment]
@karahancodes 

`BTC/USDT` is the spot symbol, but your using `options : {defaultType :'swap'}`. The swap symbol is `BTC/USDT:USDT` as long as your talking about a contract settled using USDT. You can read about the [symbol naming schemas here](https://docs.ccxt.com/en/latest/manual.html#contract-naming-conventions)

**Comment by karahancodes** [comment]
That symbol worked , thanks and i understood the symbol scheme.But ; 
  ** BadSymbol: bitget fetchMyTrades() only supports spot markets** 
Closing the issue , thanks.
