### ISSUE TITLE
How to print a market's tick size

### ISSUE THREAD

**Issue by mmehrle** [ccxt/ccxt#1499]
Hey guys - apologies in advance if this is not the proper place to ask this question. Feel free to delete if not. That said: How do I determine the tick sizes offered by a particular exchange? I can't any references in the API docs. Thanks a ton in advance.

**Comment by kroitor** [comment]
@mmehrle see `limits` and `precision` in the market structure: https://github.com/ccxt/ccxt/wiki/Manual#market-structure

Let me know it it doesn't answer your question.

**Comment by mmehrle** [comment]
Sorry to be a pain but it doesn't. I actually studied this section previously and didn't see anything related to tick size. There's min order but I don't think that is the same. Please advise.

**Comment by mmehrle** [comment]
Actually one more follow up question. I'm trying to get to each symbol's precision but can't even properly load the symbols into a list, let alone the precision attribute:

smbls = [mkt.symbol for mkt in (exchange.markets)]

Throws an error. What is the proper way to pull the market objects after which I can get to its respective attributes?

Thanks in advance.

**Comment by kroitor** [comment]
> Throws an error. What is the proper way to pull the market objects after which I can get to its respective attributes?

Depends on the error? Can you show you full code snippet to reproduce it?
