### ISSUE TITLE
How to fetch or cancel orders sent on Binance isolated margin account

### ISSUE THREAD

**Issue by sirui0112** [ccxt/ccxt#14994]
- OS: Windows 10
- Programming Language version: Python 3.9.12
- CCXT version: 1.84.5

Code snippet to send the order
```
ex = ccxt.binance({
        "apiKey": api_key,
        "secret": secret,
        "enableRateLimit": True,
        'options': {
            'defaultType': "margin"
        },
    })

ex.create_order(symbol="ETHUSDT", 
                type="limit", 
                side="buy", 
                amount=0.1, 
                price=1500,
                params={"isIsolated": True})
```
The order is sent successfully but I am unable to fetch or cancel the order using the order id.

```
ex.fetch_order(id=id, symbol="ETHUSDT")
>>> OrderNotFound: binance {"code":-2013,"msg":"Order does not exist."}

ex.cancel_order(id=id, symbol="ETHUSDT")
>>> OrderNotFound: binance {"code":-2011,"msg":"Unknown order sent."}
```

**Comment by carlosmiei** [comment]
Hello @sirui0112, can you please post a verbose log of the request?

**Comment by sirui0112** [comment]
Hi @carlosmiei I am working with **orders sent on Binance 10x isolated margin account** on product ETH/USDT. I was able to send the order successfully and it’s viewable on Binance website.
However as mentioned in the description above, methods fetch_order and cancel_order (both worked on normal orders sent on spot or futures account) throw errors when used on the isolated order (while the order is still active in market). 
So I’m wondering if there’s any necessary setting that needed to be adjusted, or any parameters required for me to fetch or cancel the order. Thanks.

**Comment by carlosmiei** [comment]
@sirui0112 can you try to pass `params={"isIsolated": True}` to `fetchOrder` and `cancelOrders` as well?

**Comment by sirui0112** [comment]
Hi @carlosmiei it works, thanks a lot. Closing the issue now.
