### ISSUE TITLE
Binance All Book Tickers Stream

### ISSUE THREAD

**Issue by BlockchainHe** [ccxt/ccxt#14996]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: ubuntu 20.04 TLS
- Programming Language version: Python 3.9.0
- CCXT version: 1.2.22

how can i get the best bid or ask's price or quantity in real-time for all future symbols in binance by ccxtpro ??

I want to subscribe all book tickers stream by call stream name: !bookTicker??

**Comment by carlosmiei** [comment]
Hello @BlockchainHe,
Unfortunatel, this is not yet possible we're in the process of unifying `watchTickers` but it has not been done yet
