### ISSUE TITLE
zb.fetchOpenOrders: OrderNotFound: zb {"code":3001,"message":"挂单没有找到或已完成"}

### ISSUE THREAD

**Issue by zoomzoomgithub** [ccxt/ccxt#14998]
- OS: Windows 11
- Programming Language version: Javascript
- CCXT version: 8.15.0

Hello,

Exchange zb is returning OrderNotFound when using zb.fetchOpenOrders.  This is different from all the other unified exchanges that are returning [].

CODE:

const ccxtpro = require ('ccxt.pro');

var zb = new ccxtpro.zb  ({
"apiKey": "####",
"secret": "####"})

var zbOpenOrders = await zb.fetchOpenOrders  ("BTC/USDT")
var t10 = zbOpenOrders.toString();
if (t10 !== "") { console.log("t10") }

ERROR:

C:\Users\####\####\node_modules\ccxt\js\base\Exchange.js:2105
            throw new exact[string] (message);
                  ^

OrderNotFound: zb {"code":3001,"message":"挂单没有找到或已完成"}
    at zb.throwExactlyMatchedException (C:\Users\####\####\node_modules\ccxt\js\base\Exchange.js:2105:19)
    at zb.handleErrors (C:\Users\####\####\node_modules\ccxt\js\zb.js:4357:22)
    at C:\Users\####\####\node_modules\ccxt\js\base\Exchange.js:598:51
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async timeout (C:\Users\####\####\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async zb.fetch2 (C:\Users\####\####\node_modules\ccxt\js\base\Exchange.js:1801:16)
    at async zb.request (C:\Users\####\####\node_modules\ccxt\js\base\Exchange.js:1805:16)
    at async zb.fetchOpenOrders (C:\Users\####\####\node_modules\ccxt\js\zb.js:2677:26)
    at async file:///C:/Users\####\####\Bot.js:65:20 {
  constructor: [class OrderNotFound extends InvalidOrder]

**Comment by carlosmiei** [comment]
Hello @zoomzoomgithub , it depends on how the exchange handles it, come just return an empty array but consider it as a valid HTTP response, others like ZB just throw an exception

**Comment by zoomzoomgithub** [comment]
> just return an empty array but consider it as a valid HTTP response, others like ZB just throw an exception

How do I handle the exception that is thrown?  my try catch is not working.

	if (zbOpenOrder !== "") {
        openOrder = 'true';
        if (zb.has['fetchOrder']) {
            try {
                order = await zb.fetchOpenOrders ("BTC/USDT")
                buyOrderId = '';
                buyOrderStatus = '';
                console.log(order)
            } catch (e) {console.log (e)}
        }
    }

**Comment by frosty00** [comment]
zb has since been delisted
