### ISSUE TITLE
Question - Is USDT TetherUS-ERC20 the same USDT used by the BTC/USDT symbol?

### ISSUE THREAD

**Issue by zoomzoomgithub** [ccxt/ccxt#15004]
- OS: Windows 11
- Programming Language version: Javascript
- CCXT version: 8.15.0

Hi,

Can you please tell me if USDT TetherUS-ERC20 is the same USDT used by the BTC/USDT symbol?  I couldn't find an answer in the closed issues.

Thanks!

**Comment by sc0Vu** [comment]
Hi @zoomzoomgithub 

Yes, I think so. Also, TetherUSDT had deployed on different blockchain (Tron, BSC or AVAX).

**Comment by zoomzoomgithub** [comment]
Thank you!
