### ISSUE TITLE
Get values of frozen and hold within balance info

### ISSUE THREAD

**Issue by zoomzoomgithub** [ccxt/ccxt#15018]
- OS: Windows 11
- Programming Language version: Javascript
- CCXT version: 8.15.0

Can you please help me figure out how to read the values of frozen, hold, balance and available within balance info?  Thank you!

const currency = 'USDT';

async function fetchBalance(currency) {
  const balance = await exchange.fetchBalance();
  console.log(balance)
} fetchBalance(currency)

Output:

{
  info: [
    {
      frozen: '0',
      hold: '0',
      id: '',
      currency: 'USDT',
      balance: '49.80079681',
      available: '49.80079681',
      holds: '0'
    }
  ],
  timestamp: undefined,
  datetime: undefined,
  USDT: { free: 49.80079681, used: 0, total: 49.80079681 },
  free: { USDT: 49.80079681 },
  used: { USDT: 0 },
  total: { USDT: 49.80079681 }
}

I am trying to use something like console.log(balance.info[currency]) but this is not working.

**Comment by sc0Vu** [comment]
Hi,

I think you can find in our wiki: https://github.com/ccxt/ccxt/wiki/Manual#account-balance

**Comment by zoomzoomgithub** [comment]
> Hi,
> 
> I think you can find in our wiki: https://github.com/ccxt/ccxt/wiki/Manual#account-balance

Hi sc0Vu, it didn't answer my question directly but luckily I did find that 'used' will fulfill my needs.  Thanks!
