### ISSUE TITLE
Binance fetch_ohlcv : does not return the last refreshed data when using 30m timeframe and bigger

### ISSUE THREAD

**Issue by samia81** [ccxt/ccxt#15010]
- OS: Windows
- Programming Language version: Python 3.9.13
- CCXT version:1.92.93

I am using fetch_ohlcv to get the 100 last historical data. timeframe=1h , limit=100 
The problem is that after few seconds, this method does not return the last refreshed data. 
I have to wait for more than 15min or more to get the refreshed data with the last timestamp included in the historical data.

```
        try:
            
            #logger.debug("before fetch_ohlc : " + str(sarAge) )
            data = excha.fetch_ohlcv(
                coin_pair, timeframe, limit=settings.limit_cycle)
             
            #logger.debug("after fetch_ohlc : " + str(sarAge) )
        except:
            logger.debug("fetch_ohlcv error")
            #traceback.print_exception(*sys.exc_info())
            return False,0
        # update timestamp to human readable timestamp
        data = [[excha.iso8601(candle[0])] + candle[1:] for candle in data]
       
        header = ['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume']
        historical_data = pd.DataFrame(data, columns=header)
```

**Comment by pcriadoperez** [comment]
Hi @samia81,

I'm not sure if I fully understand the issue.
After calling several times `fetch_ohlcv()` I see the volume on the last timestamp gets updated every time, however due to the large timeframe there is no new timestamp for several minutes as expected.

Can you confirm what is output you are expecting?

Also if you add `exchange.verbose = true` you can see the raw response from binance.

**Comment by ttodua** [comment]
There has been no follow-up posted by user for more than 1 month. I'll close this issue, and if anyone experiencing anything alike, let us know, with more details of the request/response you expect and receive.

**Comment by samia81** [comment]
Sorry for my late feedback.
The problem is when I call fetchOHLCV w8th timeframe=2h at 10am for example, it still returns ohlcv values that gives old sar value,
