### ISSUE TITLE
setLeverage issue on BitGet

### ISSUE THREAD

**Issue by karahancodes** [ccxt/ccxt#15033]
Hey , i'm having issues setting leverage with setLeverage method.  I do have a holdSide param but i'm still getting this error message. 
```js
const bitget = new ccxt.bitget({
    apiKey : process.env.tn_bitget_key,
    secret : process.env.tn_bitget_secret,
    password : process.env.tn_bitget_password,
    options : {defaultType :'swap'}}
)
async function bitgetTestSetLeverage (){
    const lev = await bitget.setLeverage(
        '20',
        'BTC/USDT:USDT',
        {'holdSide': 'sell'})
    console.log(lev)
}

bitgetTestSetLeverage()
```

```js
ExchangeError: bitget {"code":"40019","msg":"参数 holdSide 不能为空","requestTime":1663386087504,"data":null}
```

**Comment by sc0Vu** [comment]
Hi @karahancodes 
<img width="106" alt="image" src="https://user-images.githubusercontent.com/10494397/190840803-ef7acc4d-45ef-4525-93f7-a75a79227db5.png">

The parameter of `holdSide` should be long or short.

**Comment by ttodua** [comment]
As answered by @sc0Vu , I'll close this issue. let us know if you have any other issue with CCXT.
