### ISSUE TITLE
[feature] Sandbox or not in the exchange info list.

### ISSUE THREAD

**Issue by dawadam** [ccxt/ccxt#15037]
It would be helpful to know if the exchange supports sandbox or not in the exchange info list.

**Comment by pcriadoperez** [comment]
I'll leave this issue open to see what @kroitor or @carlosmiei think of the idea.

In the meantime you can check if the exchange supports a sandbox by using this if statement for each exchange:  `if ('test' in exchange.urls)`

**Comment by samgermain** [comment]
@dawadam You can already kind of do this by checking if there is a url listed in `exchange.describe()['urls']['test']`

**Comment by dawadam** [comment]
Hi, bitget exchange no have test url but now have sandbox mode :

https://github.com/ccxt/ccxt/issues/16235

**Comment by frosty00** [comment]
@dawadam yep, we will unify that
