### ISSUE TITLE
Loadmarkets Kraken error

### ISSUE THREAD

**Issue by normanu** [ccxt/ccxt#1503]
- OS: Arch Linux
- Programming Language version: 8.9.3
- CCXT version: 1.10.845
- Exchange: Kraken
- Method:

(async () => {
    let kraken = new ccxt.kraken ()
    let markets = await kraken.load_markets ()
    console.log (kraken.id, markets)
}) ()

gives following error,

(node:21894) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: kraken GET https://kraken.zendesk.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size- request timed out (10000 ms)
(node:21894) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kroitor** [comment]
> gives following error,

You can either raise your timeout:

```Javascript
(async () => {
let kraken = new ccxt.kraken ({ timeout: 60000 })
let markets = await kraken.load_markets ()
console.log (kraken.id, markets)
}) ()
```

... or handle the errors properly (see [examples](https://github.com/ccxt/ccxt/tree/master/examples) and [docs](https://github.com/ccxt/ccxt/wiki/Manual#error-handling)).

Hope it answers your question.

**Comment by authenticfake** [comment]
From Europe I receive the same error and the configuration you proposed doesn't work.
Do you know if this issue is based on the location? From Italy the load market doesn't work

**Comment by kroitor** [comment]
@authenticfake https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
