### ISSUE TITLE
coinone ccxt grammer error [ def create_order]

### ISSUE THREAD

**Issue by sohw400** [ccxt/ccxt#15048]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: windows 
- Programming Language version:  python3
- CCXT version:

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS

```
exchange.create_order('ZRX/KRW','limit','sell',10,10)
```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

line 613, in parse_order
    symbol = base + '/' + quote
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

there is a something error with create_order

**Comment by ttodua** [comment]
the issue was fixed in #15051
