### ISSUE TITLE
ccxt.d.ts vs. ccxt.js mismatch

### ISSUE THREAD

**Issue by rekt0x** [ccxt/ccxt#15049]
- OS: macOS 12.5.1
- Programming Language version: Typescript (esnext)
- CCXT version: 1.93.66

I'm using ccxt via Typescript but I just found out there seems to be an issue with [ccxt.d.ts](https://github.com/ccxt/ccxt/blob/master/ccxt.d.ts) - it doesn't expose e.g. the `fetchPositions` function, but the Javascript library does, see here: [ccxt.js](https://github.com/ccxt/ccxt/blob/master/ccxt.js)

**Comment by sc0Vu** [comment]
Hi @rekt0x 

Thanks, we'll add these methods.
