### ISSUE TITLE
How to request all symbols from all exchanges ?

### ISSUE THREAD

**Issue by cocotr** [ccxt/ccxt#1504]
Do you have any sample how to request all symbols from all exchanges at once? or any ideas how to do it?

thx.

**Comment by kroitor** [comment]
Which language?)

**Comment by cocotr** [comment]
JS

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/blob/master/examples/js/load-all-symbols-at-once.js

**Comment by cocotr** [comment]
Thanks, I found this, but how to request market data for all of them ( level 1 or the whole order books) ?

**Comment by kroitor** [comment]
Change Line 20 from:

```
await exchange.loadMarkets ()
```

to

```
    console.log (exchange.fetchOrderBook (yourSymbol) // will load your selected symbol
```

If you want to load all markets, and then to load all data for all markets at once, exchanges won't like it. They will throttle your requests, so you have to cycle through symbols, and, most likely, you don't want all of them. All of it is documented here: https://github.com/ccxt/ccxt/wiki

We are also going to merge this pull-request soon that does what you want in one call: https://github.com/ccxt/ccxt/pull/1050

Apart from the examples in this repo, I would recommend to look at other projects that use ccxt and check how they load all data at once: https://github.com/ccxt/ccxt/network/dependents (lots of useful examples there).

In short, you will need a serious infrastructure, like your own datacenter, just to be able to *accept* all incoming data for all orderbooks for all symbols from all exchanges at once. And this is usually done by means of libraries like ccxt and other, but it really depends on too many factors, including the connectivity between you and each particular exchange which may, the time of day, the load on the exchanges themselves, etc, etc... So the task of loading "all data at once" isn't easily solvable right away. You will have to consider *the problem of scaling*. Start with something much simpler to understand how it all works. Try just two exchanges and two orderbooks. Then 3 orderbooks. Then 30 orderbooks. Etc. You will quickly get into the core of the problem.

Let us know if it doesn't help. Closing it for now.
