### ISSUE TITLE
AuthenticationError: bitmart {"message":"Header X-BM-SIGN is wrong"

### ISSUE THREAD

**Issue by zoomzoomgithub** [ccxt/ccxt#15046]
- OS: Windows 11
- Programming Language version: Javascript
- CCXT version: 8.15.0

Can you please tell me why I am receiving AuthenticationError: bitmart {"message":"Header X-BM-KEY not found" ?

What needs to be changed?  I have already tried creating a new API key and using let.. var doesn't work either.  I see one issue that was opened for this same error but does not show a resolution.  If the code below works for you please let me know .  Thank you for your help!

var exchange1 = new ccxtpro.bitmart  ({
    "apiKey": "XXXXXXXXXXXXXXXXXXXXXXXX",
    "secret": "XXXXXXXXXXXXXXXXXXXXXXXX",
   "uid": "XXXXXXXXXXXXXXXXXXXXXXXX"})

var exchange2 = new ccxtpro.phemex  ({
    "apiKey": "XXXXXXXXXXXXXXXXXXXXXXXX",
    "secret": "XXXXXXXXXXXXXXXXXXXXXXXX"})

let exchange2USDTAddress = '';
const USDT = "USDT";

// get exchange2 USDT address
async function getexchange2USDTAddress(exchange2) {
    exchange2USDTAddress = await exchange2.fetchDepositAddress("USDT", { 'network': 'ETH' })
    exchange2USDTAddress = exchange2USDTAddress['address'];
    console.log("exchange2: " + exchange2.name)
    console.log("exchange2 USDT address: " + exchange2USDTAddress)
}
await getexchange2USDTAddress(exchange2)

// Withdrawal USDT from exchange1 to exchange2
async function withdrawalUSDTFromexchange1Toexchange2 (exchange1, exchange2USDTAddress) {
        var exchange1USDTWithdrawalToexchange2 = await exchange1.withdraw ('USDT', 10, exchange2USDTAddress, { 'chain': 'ETH' })  
        console.log("exchange1 USDT withdrawal to exchange2: " + exchange1USDTWithdrawalToexchange2)
}
await withdrawalUSDTFromexchange1Toexchange2 (exchange1, exchange2USDTAddress)

AuthenticationError: bitmart {"message":"Header X-BM-KEY not found","code":30002,"trace":"325e1c0cf9084827893224c714dfbfd7.69.16634724607790377","data":{}}
    at bitmart.throwExactlyMatchedException (C:\Users\####\####\node_modules\ccxt\js\base\Exchange.js:2105:19)
    at bitmart.handleErrors (C:\Users\####\####\node_modules\ccxt\js\bitmart.js:3128:18)
    at C:\Users\####\####\node_modules\ccxt\js\base\Exchange.js:598:51
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async timeout (C:\Users\####\####\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async bitmart.fetch2 (C:\Users\####\####\node_modules\ccxt\js\base\Exchange.js:1801:16)
    at async bitmart.request (C:\Users\####\####\node_modules\ccxt\js\base\Exchange.js:1805:16)
    at async bitmart.withdraw (C:\Users\####\####\node_modules\ccxt\js\bitmart.js:2310:26)
    at async withdrawalUSDTFromHomeBaseToMinExchange (file:///C:/####/####/Bitcoin%20Bot/Bot.js:404:51)
    at async file:///C:/####/####/Bitcoin%20Bot/Bot.js:410:1 {
  constructor: [class AuthenticationError extends ExchangeError]

**Comment by zoomzoomgithub** [comment]
I think there might be a problem with Bitmart

**Comment by ttodua** [comment]
@zoomzoomgithub please let us know if you were able to fix the issue (and what was happening on your side? was it CCXT issue or something in your userland code?)

**Comment by kroitor** [comment]
@zoomzoomgithub cannot reproduce your issue, this works for me with a correct key, try this simpler snippet first:

```JavaScript
const exchange = new ccxtpro.bitmart ({
    "apiKey": "XXXXXXXXXXXXXXXXXXXXXXXX",  // 40 chars
    "secret": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",  // 64 chars
    "uid": "XXXXXXXXXXXXXXXXXXXXXXXX"  // the name of your api key
})
await exchange.loadMarkets()
exchange.verbose = true
const balance = await exchange.fetchBalance ()
```

**Comment by kroitor** [comment]
@zoomzoomgithub make sure you've configured your API Key UID correctly and you're using the correct key and secret, feel free to reopen this issue if the above snippet does not work.
