### ISSUE TITLE
BitGet TypeError: this[method] is not a function while cancelling batch orders 

### ISSUE THREAD

**Issue by karahancodes** [ccxt/ccxt#15042]
I'm trying to cancel batch orders , but i keep getting ```TypeError: this[method] is not a function```
```js
const bitget = new ccxt.bitget({
    apiKey : process.env.tn_bitget_key,
    secret : process.env.tn_bitget_secret,
    password : process.env.tn_bitget_password,
    options : {defaultType :'swap'}}
)

```

```js
async function bitgetTestCancelOrders () {
    const allCancelled = await bitget.cancelOrders(['orderid1','orderid2'],'BTC/USDT:USDT')
    return allCancelled
}
```
Thanks in advance.

**Comment by carlosmiei** [comment]
Hello @karahancodes, thanks for reporting it, there is indeed an issue there. We will fix it soon, but as a workaround, if you really need to use it now, you can do it through the implicit API.

Example:

```Javascript
const ids = ['orderid1','orderid2']
const symbol = "BTC/USDT:USDT"
const market = bitget.market(symbol)
const request = {
    'ids' : ids,
    'symbol': market['id']
}

const cancelAll = await bitget.privateMixPostOrderCancelBatchOrders(request)
```

**Comment by karahancodes** [comment]
Okay , thanks for the fix.  But i'm having params issues now , could you check this out please ?

```js
async function bitgetTestCancelOrders () {
    const allCancelled = await bitget.cancelOrders(['954855266430111745','954855913896431617'],'BTC/USDT:USDT',{'marginCoin':'USDT'})
    return allCancelled
}
```
**marginCoin** param does not seem to work properly,  i'm getting this error mesage ; 

```js 
ExchangeError: bitget {"code":"40017","msg":"null 不能为空","requestTime":1663424839148,"data":null}
```

**Comment by carlosmiei** [comment]
Hello @karahancodes the fix was only merged today, can you please update your ccxt version and try again?

**Comment by karahancodes** [comment]
Hello @carlosmiei ,
Thanks for your interest , i already updated and still got the same issue!
