### ISSUE TITLE
Weird BitGet cancelorders issue

### ISSUE THREAD

**Issue by karahancodes** [ccxt/ccxt#15058]
- CCXT version: Latest commit 
Hello , me again;

After i've reported an issue with implicit api endpoint , you fixed it but i still can't get the correct output.

```JS
async function bitgetTestCancelOrders () {
    const allCancelled = await bitget.cancelOrders(['954855266430111745','954855913896431617'],'BTC/USDT:USDT',{'marginCoin':'USDT'})
    return allCancelled
}
```
The error i get is ; 
```js
ExchangeError: bitget {"code":"40017","msg":"null 不能为空","requestTime":1663589057925,"data":null}
```

**Comment by carlosmiei** [comment]
Hello again @karahancodes, ok we will try to reproduce it on our side, thanks for letting us know

**Comment by carlosmiei** [comment]
@karahancodes can you please try again now?

**Comment by karahancodes** [comment]
@carlosmiei  I still get the 
**ExchangeError: bitget {"code":"40017","msg":"null 不能为空","requestTime":1663670845910,"data":null}** unfortunately even after pulling the latest commit

**Comment by karahancodes** [comment]
My bad , updated to the latest commit and it works flawlessly , thank you very much !
