### ISSUE TITLE
"code":1002,"message":"Contract not allow place order!" in Mexc

### ISSUE THREAD

**Issue by felipebrazil02** [ccxt/ccxt#15055]
Hi, leaving my code and my error here to see if anybody can help.

const mexc = new mexc3({
    apiKey: key || '',
    secret: secret || '',
    options: {
        defaultType: 'swap'
    }
});

async sendBuyOrder(symbol = 'BTC/USDT', type = 1, side = 1, amount = 0.0001, price = 0.0001){
        try {
            return mexc.createOrder(symbol, type, side, amount, price, {"openType" : 1, "leverage": 20});
        } catch (error) {
            return error.message;
        }
    }

I've enabled the contracts in API but getting the following error still:

"code":1002,"message":"Contract not allow place order!"

**Comment by sc0Vu** [comment]
Hi @felipebrazil02 

I can't reproduce this, would you like to paste your ccxt version? BTW, the symbol is for spot market, if you want to create order for the swap, you can use these format: `base/quote:settle` eg,`ADA/USDT:USDT`

**Comment by felipebrazil02** [comment]
> Hi @felipebrazil02 
> 
> 
> 
> I can't reproduce this, would you like to paste your ccxt version? BTW, the symbol is for spot market, if you want to create order for the swap, you can use these format: `base/quote:settle` eg,`ADA/USDT:USDT`

My version is 1.80.9

About the spot symbol you mentioned is just a function. When I call its perpetual futures just like you sent(base/quite:settle).

**Comment by carlosmiei** [comment]
@felipebrazil02 @sc0Vu Mexc temporarily disabled trading in most of the derivatives, please check this out: https://support.mexc.com/hc/en-001/articles/8681589415961-MEXC-Upgrade-and-Maintenance-of-API-for-Perpetual-Futures-Trading-Pairs

**Comment by felipebrazil02** [comment]
> @felipebrazil02 @sc0Vu Mexc temporarily disabled trading in most of the derivatives, please check this out: https://support.mexc.com/hc/en-001/articles/8681589415961-MEXC-Upgrade-and-Maintenance-of-API-for-Perpetual-Futures-Trading-Pairs

Thanks in advance! I'll check this out!

**Comment by ttodua** [comment]
Right, that problem could have been because of MEXC api engine limitations.
Let us know if you have any further issue with CCXT.
