### ISSUE TITLE
Set Stop Loss for an Open Position on ByBit

### ISSUE THREAD

**Issue by emorling** [ccxt/ccxt#15059]
I am stuck with setting Stop Loss for an Open Position on ByBit.

I have attempted to set all these params, without any success:

```
await bybit.editOrder(id, symbol, type, side, amount, undefined, {
      stopPrice: 0.21,
      triggerPrice: 0.21,
      stop_px: 0.21,
      stopLoss: 0.21,
      stop_loss: 0.21,
    });
```

I get this response, but nothing happens in regards to changing the stop loss of an open position:

```
{
  info: {
    ret_code: '0',
    ret_msg: 'OK',
    ext_code: '',
    ext_info: '',
    result: { order_id: '7690bc7b-9a58-4842-98e3-1c40efa4aee4' },
    time_now: '1663593305.548126',
    rate_limit_status: '99',
    rate_limit_reset_ms: '1663593305546',
    rate_limit: '100'
  },
  id: '7690bc7b-9a58-4842-98e3-1c40efa4aee4',
  order_id: '7690bc7b-9a58-4842-98e3-1c40efa4aee4',
  stop_order_id: undefined
}
```

I also attempted this for "StopLoss and TakeProfit orders attached to a position"
https://docs.ccxt.com/en/latest/manual.html#stoploss-and-takeprofit-orders-attached-to-a-position
```
stopLoss: {
        stopLossPrice: 0.21,
      }
```

However, that produces this error response:
`{"ret_code":10001,"ret_msg":"fuzzyStringDecoder: not number or string, error found in #10 byte of ...|stopLoss\\":{\\"stopLoss|..., bigger context ...|.21,\\"triggerPrice\\":0.21,\\"stop_px\\":0.21,\\"stopLoss\\":{\\"stopLossPrice\\":0.21},\\"stop_loss\\":0.21,\\"stopLossP|...","ext_code":"","ext_info":"","result":null,"time_now":"1663593624.429265"}`

Any ideas?

**Comment by 3ntr0phy** [comment]
Hi,
I am trying to do the exact same thing but I get some errors:
```ccxt.base.errors.ExchangeError: bybit {"ret_code":130001,"ret_msg":"position idx not match position mode","result":{},"ext_code":"","ext_info":"","time_now":"1673890061.788647","rate_limit_status":74,"rate_limit":75,"rate_limit_reset_ms":1673890061786}```

Despite I tried to use 

```
 exchange.set_position_mode(hedged=False, ssymbol)
 exchange.set_margin_mode("ISOLATED", symbol)
        ```
        
   Any idea on what am I doing wrong?
   Thanks
