### ISSUE TITLE
digifinex currencies not correct

### ISSUE THREAD

**Issue by hosseinab** [ccxt/ccxt#15052]
OS: Windows 11
Programming Language version: PYTHON 3.10.5
CCXT version: "ccxt/ccxt": "^1.93.59",
Exchange: digifinex
Method: load_markets - currencies

hi . 
my code :
connection.load_markets()
markets = connection.currencies
print(markets)

output :
{'USDT': {'id': 'USDT', 'code': 'USDT', 'info': [{'deposit_status': '0', 'min_withdraw_fee': '5', 'withdraw_fee_currency': 'USDT', 'chain': 'OMNI', 'withdraw_fee_rate': '0', 'min_withdraw_amount': '10', 'currency': 'USDT', 'withdraw_status': '0', 'min_deposit_amount': '10'}, {'deposit_status': '1', 'min_withdraw_fee': '15', 'withdraw_fee_currency': 'USDT', 'chain': 'ERC20', 'withdraw_fee_rate': '0', 'min_withdraw_amount': '10', 'currency': 'USDT', 'withdraw_status': '1', 'min_deposit_amount': '10'}, {'deposit_status': '1', 'min_withdraw_fee': '1', 'withdraw_fee_currency': 'USDT', 'chain': 'TRC20', 'withdraw_fee_rate': '0', 'min_withdraw_amount': '10', 'currency': 'USDT', 'withdraw_status': '1', 'min_deposit_amount': '10'}, {'deposit_status': '1', 'min_withdraw_fee': '1', 'withdraw_fee_currency': 'USDT', 'chain': 'BEP20', 'withdraw_fee_rate': '0', 'min_withdraw_amount': '10', 'currency': 'USDT', 'withdraw_status': '1', 'min_deposit_amount': '10'}, {'deposit_status': '1', 'min_withdraw_fee': '2', 'withdraw_fee_currency': 'USDT', 'chain': 'Polygon', 'withdraw_fee_rate': '0', 'min_withdraw_amount': '10', 'currency': 'USDT', 'withdraw_status': '1', 'min_deposit_amount': '10'}], 'type': None, 'name': None, **'active': False, 'deposit': False, 'withdraw': False,** 'fee': 0.0, 'precision': 1e-08, 'limits': {'amount': {'min': None, 'max': None}, 'withdraw': {'min': 10.0, 'max': None}}}, 'USDC': {'id': 'USDC', 'code': 'USDC', ...

in this output usdt withdraw = False but in website usdt withdraw is enable.

**Comment by pcriadoperez** [comment]
Thanks @hosseinab for pointing this out! There is a bug where it's only checking the first network. I'll open a PR to fix this and also include the different networks in the currency structure.

**Comment by hosseinab** [comment]
@pcriadoperez 
this merge not approved ?
