### ISSUE TITLE
Kucoin stop orders - stopPrice is being changed before calling the exchange

### ISSUE THREAD

**Issue by fferreizq** [ccxt/ccxt#15053]
Hello. I'm trying to set TP and SL to an open trade in KUCOIN FUTURE exchange.

For that I'm using the method "createStopMarketOrder" setting parameters "stop" to "up" or "down" and stopPrice.

What I have seen is that the parameter stopPrice that is sent to exchange, sometimes change to zero or other value. Sometimes it works, but normally it's changed to another value that makes the order execute inmediately.

I'm the example I'm trying to set TP for an open trade of PEOPLE (LONG entryPrice: 0.02084), and stopPrice is changed to zero:

### My app logs with the method invoked:
[18/09/2022 15:56:00.329] Kucoin futures sell take profit order for PEOPLE/USDT:USDT at 0.02163 for 119 contracts
[18/09/2022 15:56:00.329] createStopMarketOrder(marketId: **'PEOPLE/USDT:USDT'**, orderSide: **'sell'**, amount: **119**, price: **0.02163**, params: **{"stop":"up","stopPrice":0.02163,"stopPriceType":"TP","closeOrder":true}**)

### CCXT Verbose logs:
**fetch Request:**
 kucoinfutures POST https://api-futures.kucoin.com/api/v1/orders 
RequestHeaders:
 {
  'KC-API-KEY-VERSION': '2',
  'KC-API-KEY': '',
  'KC-API-TIMESTAMP': '1663509360662',
  'Content-Type': 'application/json',
  'KC-API-PASSPHRASE': '',
  'KC-API-SIGN': '=',
  'KC-API-PARTNER-SIGN': '',
  'KC-API-PARTNER': 'ccxtfutures'
} 
**RequestBody**:
 {"clientOid":"097df5e7-0f21-44c8-a160-d6b6348b8296","side":"sell","symbol":"PEOPLEUSDTM","type":"market","size":119,"leverage":1,"stop":"up","stopPriceType":"TP","stopPrice":"0","closeOrder":true} 

**handleRestResponse**:
 kucoinfutures POST https://api-futures.kucoin.com/api/v1/orders 200 OK 
**ResponseHeaders**:
 {
  'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '74ca95203f86d681-MAD',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json',
  Date: 'Sun, 18 Sep 2022 13:56:00 GMT',
  Expires: '0',
  Server: 'cloudflare',
  'Set-Cookie': '',
  'Strict-Transport-Security': 'max-age=9800; includeSubDomains; preload',
  'Transfer-Encoding': 'chunked',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'X-Xss-Protection': '1; mode=block'
} 
ResponseBody:
 {"code":"100001","msg":"The stop price parameter of the stop order is invalid."} 

Any idea what I should be doing wrong?
THANKS A LOT!!!!

**Comment by pcriadoperez** [comment]
Hi @fferreizq .

I was not able to reproduce the error using the same create order.
But looking at the code the only operation done to the stopPrice is converting it to the precision of the symbol. So maybe for very small amounts it is converting to zero?

Where you able to find a pattern of when this happens or a way I could reproduce it?

**Comment by fferreizq** [comment]
Hi Pablo!. Thanks a lot for you help.

I have been working on this problem since yesterday. Let me share with you what I have seen.

First at all let me tell you what my app is doing because it's important to reproduce the problem. My app is doing the following:
1) Creating a market order (createOrder)
2) Checking the order created every 5 seconds until it had been closed (getOrder)
3) Checking the position (getPosition)
4) Creating a market stop order (StopLoss) (createStopMarketOrder)
5) Creating a market stop order (Take Profit) (createStopMarketOrder)


**Conclusions:**

It only happens in kucoin production environment.

If the app takes the five steps, **the problem always happens.**
if I stop the app after the third step, and restart it, the app resumes and step 4 and 5 work perfect, as expected. 

if the ticker price is lower than 0.5, the stopPrice is becoming 0 (error stop order is invalid)
If the ticker price is higher than 0.5, the stopPrice is becoming 1 (no error, but close order is executed inmediately)
The same happens with another values. It looks like it has been rounded.



**My theory:**

The method _createOrder_ in _kucoinfuture.js_ is asking for markets:

_await this.loadMarkets();_

I think that request is failing because a rate limit exceeded error, and this.market property has default values in which precision is 1. 

I have added log lines to this method to show this.market property to confirm or refute this point.

**Comment by fferreizq** [comment]
I have modify the method to this:

async createOrder(symbol, type, side, amount, price = undefined, params = {}) {
        /**
         * @method
         * @name kucoinfutures#createOrder
         * @description Create an order on the exchange
         * @param {string} symbol Unified CCXT market symbol
         * @param {string} type 'limit' or 'market'
         * @param {string} side 'buy' or 'sell'
         * @param {float} amount the amount of currency to trade
         * @param {float} price *ignored in "market" orders* the price at which the order is to be fullfilled at in units of the quote currency
         * @param {object} params  Extra parameters specific to the exchange API endpoint
         * @param {float} params.leverage Leverage size of the order
         * @param {float} params.stopPrice The price at which a trigger order is triggered at
         * @param {bool} params.reduceOnly A mark to reduce the position size only. Set to false by default. Need to set the position size when reduceOnly is true.
         * @param {string} params.timeInForce GTC, GTT, IOC, or FOK, default is GTC, limit orders only
         * @param {string} params.postOnly Post only flag, invalid when timeInForce is IOC or FOK
         * @param {string} params.clientOid client order id, defaults to uuid if not passed
         * @param {string} params.remark remark for the order, length cannot exceed 100 utf8 characters
         * @param {string} params.stop 'up' or 'down', defaults to 'up' if side is sell and 'down' if side is buy, requires stopPrice
         * @param {string} params.stopPriceType  TP, IP or MP, defaults to TP
         * @param {bool} params.closeOrder set to true to close position
         * @param {bool} params.forceHold A mark to forcely hold the funds for an order, even though it's an order to reduce the position size. This helps the order stay on the order book and not get canceled when the position size changes. Set to false by default.
         * @returns {object} an [order structure]{@link https://docs.ccxt.com/en/latest/manual.html#order-structure}
         */
        await this.loadMarkets();

        console.log(`SYMBOL IS: -${symbol}-`)
        const market = this.market(symbol);

        // required param, cannot be used twice
        console.log(`PARAM IS: ${JSON.stringify(params)}`)
        const clientOrderId = this.safeString2(params, 'clientOid', 'clientOrderId', this.uuid());
        params = this.omit(params, ['clientOid', 'clientOrderId']);
        if (amount < 1) {
            throw new InvalidOrder(this.id + ' createOrder() minimum contract order amount is 1');
        }

        console.log(`AMOUNT IS: -${amount}-`)
        const preciseAmount = parseInt(this.amountToPrecision(symbol, amount));
        console.log(`PRECISE AMOUNT IS: -${preciseAmount}-`)
        const request = {
            'clientOid': clientOrderId,
            'side': side,
            'symbol': market['id'],
            'type': type, // limit or market
            'size': preciseAmount,
            'leverage': 1,
        };
        
        const stopPrice = this.safeValue2(params, 'triggerPrice', 'stopPrice');
        console.log(`STOPPRICE IS -${stopPrice}-`)
        if (stopPrice) {
            request['stop'] = (side === 'buy') ? 'up' : 'down';
            const stopPriceType = this.safeString(params, 'stopPriceType', 'TP');
            request['stopPriceType'] = stopPriceType;
            request['stopPrice'] = this.priceToPrecision(symbol, stopPrice);
        }
        const uppercaseType = type.toUpperCase();
        const timeInForce = this.safeStringUpper(params, 'timeInForce');
        if (uppercaseType === 'LIMIT') {
            if (price === undefined) {
                throw new ArgumentsRequired(this.id + ' createOrder() requires a price argument for limit orders');
            } else {
                request['price'] = this.priceToPrecision(symbol, price);
            }
            if (timeInForce !== undefined) {
                request['timeInForce'] = timeInForce;
            }
        }
        const postOnly = this.safeValue(params, 'postOnly', false);
        const hidden = this.safeValue(params, 'hidden');
        if (postOnly && (hidden !== undefined)) {
            throw new BadRequest(this.id + ' createOrder() does not support the postOnly parameter together with a hidden parameter');
        }
        const iceberg = this.safeValue(params, 'iceberg');
        if (iceberg) {
            const visibleSize = this.safeValue(params, 'visibleSize');
            if (visibleSize === undefined) {
                throw new ArgumentsRequired(this.id + ' createOrder() requires a visibleSize parameter for iceberg orders');
            }
        }
        params = this.omit(params, ['timeInForce', 'stopPrice', 'triggerPrice']); // Time in force only valid for limit orders, exchange error when gtc for market orders

        console.log(`REQUET: ${JSON.stringify(request)}`)
        console.log(`PARAMS: ${JSON.stringify(params)}`)


        if (!stopPrice) { // 
            const response = await this.futuresPrivatePostOrders(this.extend(request, params));
            //
            //    {
            //        code: "200000",
            //        data: {
            //            orderId: "619717484f1d010001510cde",
            //        },
            //    }
            //
            const data = this.safeValue(response, 'data', {});
            return {
                'id': this.safeString(data, 'orderId'),
                'clientOrderId': undefined,
                'timestamp': undefined,
                'datetime': undefined,
                'lastTradeTimestamp': undefined,
                'symbol': undefined,
                'type': undefined,
                'side': undefined,
                'price': undefined,
                'amount': undefined,
                'cost': undefined,
                'average': undefined,
                'filled': undefined,
                'remaining': undefined,
                'status': undefined,
                'fee': undefined,
                'trades': undefined,
                'timeInForce': undefined,
                'postOnly': undefined,
                'stopPrice': undefined,
                'info': response,
            };
        }
    }



And this is what I have:

SYMBOL IS: -SOL/USDT:USDT-
PARAM IS: {"stop":"up","stopPriceType":"TP","closeOrder":true,"stopPrice":33.41}
AMOUNT IS: -7-
PRECISE AMOUNT IS: -7-
STOPPRICE IS -33.41-
REQUET: {"clientOid":"d796841c-9c95-4f7d-8347-2abda749724f","side":"sell","symbol":"SOLUSDTM","type":"market","size":7,"leverage":1,"stop":"down","stopPriceType":"TP","stopPrice":"33"}
PARAMS: {"stop":"up","stopPriceType":"TP","closeOrder":true}



StopPrice is being rounded by priceToPrecision method

request['stopPrice'] = this.priceToPrecision(symbol, stopPrice);

Another thing is that "stop" parameter is sending twice with two different values. "UP" is the value wanted (because is to set TP for a LONG trade) and "DOWN" is set by this line:

request['stop'] = (side === 'buy') ? 'up' : 'down';

**Comment by ttodua** [comment]
being not reproducible and old topic, that didn't get further follow-ups, i'll mark this topic as closed, however, if anyone still experiences any issue, feel free to resurface this and let us know
