### ISSUE TITLE
Nothing printed when create order doesnt work

### ISSUE THREAD

**Issue by Smartromain** [ccxt/ccxt#15050]
Sometime, it doesnt create order on binance spot, and doesn't print the error. 
When the create order work, it print the order correctly.

Why and how to find out the error.

my code:

```
order = exchange.create_order(symbol, type, side, amount, price, params)
print(order)
```

- OS: win10
- Programming Language version: python
- CCXT version: 1.93.1

**Comment by sc0Vu** [comment]
Hi @Smartromain 

I can create order, would you like to paste reproducible script (remove credentials or sensitive information)?

**Comment by Smartromain** [comment]
Most of the time it buy and sell without problem but I've noticed, it's when the price move up or down very fast, that it doesn't work. but how come it doesn't print anything.

**Comment by pcriadoperez** [comment]
Hi @Smartromain ,

It should print out an error when it fails.
If you are able to reproduce it, can you paste the verbose output?
You can turn the verbose on by `exchange.verbose = True`

**Comment by ttodua** [comment]
@Smartromain it will not print anything if the createOrder leads to exception. so, you'd better use `try/catch` everywhere:
```
try:
    order = exchange.create_order(symbol, type, side, amount, price, params)
    print(order)
except Exception as e:
    print("Exception triggered in create_order", str(e))
```
Let us know what happens then.
