### ISSUE TITLE
digifinex timestamp error

### ISSUE THREAD

**Issue by hosseinab** [ccxt/ccxt#15057]
OS: Windows 11
Programming Language version: PYTHON 3.10.5
CCXT version: "ccxt/ccxt": "^1.93.59",
Exchange: digifinex
Method: create_order

hi
my code : 
            params = {}
            data = connection.create_order(symbol="TRX/USDT", type='market', amount=10, side='buy',
                                           price=0.06, params=params)

output : 
Timestamp for self request is invalid, timestamp must within 1 minute

**Comment by pcriadoperez** [comment]
Hi @hosseinab ,

Can you provide the full verbose output to better see the issue? (https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue)

Also if it's a timestamp issue you can check the time of digifinex calling `exchange.fetch_time()` and comparing to your machine's timestamp to see if that may be an issue.

**Comment by hosseinab** [comment]
@pcriadoperez 
thank you for respone 
this error fixed after sync clock time .
