### ISSUE TITLE
fetchOHLCV gives Error: poloniex {"error":"Please specify a valid period."}

### ISSUE THREAD

**Issue by ericvrp** [ccxt/ccxt#1505]
The following code gives the error message 
> Error: poloniex {"error":"Please specify a valid period."}

but works for on on other exchanges

```
const symbol = BCN/BTC
const since = undefined // new Date().getTime() - 1 * DAY // undefined
const limit = 1
exchange.fetchOHLCV(symbol, '1m', since, limit)
```

Also computing an actual 'since' one day in the past gives the same error

**Comment by kroitor** [comment]
@ericvrp 

```
>>> import ccxt
>>> ccxt.poloniex().timeframes
{'15m': 900, '5m': 300, '30m': 1800, '4h': 14400, '2h': 7200, '1d': 86400}
>>>
```

Let us know if it doesn't answer your question.

**Comment by ericvrp** [comment]
Ah yes, that got rid of the error message but now I get all 0's for ohlcv. Will look into this...

**Comment by kroitor** [comment]
@ericvrp you can also try setting `exchange.verbose = true` on the instance if you want to see requests sent and received. This can help troubleshooting sometimes.

**Comment by jsappme** [comment]
Any reason why the 1h candle data is not available?

**Comment by ngatiajim** [comment]
Leaving out the limit returns all the ohlcvs for the specied period. The below works for me
const symbol = 'BCN/BTC'
const since = new Date().getTime() -1000*3600*24*5 //the actual start date i.e. 5 days ago in milliseconds
exchange.fetchOHLCV(symbol, '5m', since)
