### ISSUE TITLE
Trailing stop gets ignored

### ISSUE THREAD

**Issue by CloudTrauma** [ccxt/ccxt#15063]
`print(auth_client.create_order(symbol,'market','buy',1,None,{'pegPriceType': 'TrailingStopPeg ','pegOffsetValueEp': -100000}))`
It opened the position but the trailing stop got ignored

**Comment by pcriadoperez** [comment]
Hi @CloudTrauma ,

Can you provide what exchange you are seeing this and the verbose output?
(https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue)

**Comment by CloudTrauma** [comment]
I am using Phemex .
https://justpaste.it/9bo5v
link for verbose

**Comment by CloudTrauma** [comment]
`Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

===== RESTART: C:\Users\gginc\OneDrive\Documents\TradingBot\Phemex\test.py =====

fetch Request: phemex GET https://api.phemex.com/exchange/public/cfg/v2/products RequestHeaders: {'User-Agent': 'python-requests/2.28.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: phemex GET https://api.phemex.com/exchange/public/cfg/v2/products 200 ResponseHeaders: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Tue, 20 Sep 2022 00:59:06 GMT', 'Server': 'nginx', 'x-phemex-request-tracing': '9c30f522-7aa9-48b5-b232-2f0ecedf2123', 'X-RateLimit-Remaining': '99', 'X-RateLimit-Capacity': '100', 'X-Content-Type-Options': 'nosniff, nosniff', 'X-XSS-Protection': '1; mode=block, 1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate, no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY, SAMEORIGIN', 'Referrer-Policy': 'no-referrer, origin-when-cross-origin', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'X-Cache': 'Hit from cloudfront', 'Via': '1.1 1645a9d28193126ae7c151e9fce40ee8.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'DFW3-C1', 'X-Amz-Cf-Id': 'S-YB-keAbUROn54cLBtPP0ByyLgTexS--RCgBleR_9FEQro73cns5w==', 'Age': '824'} ResponseBody: 

fetch Request: phemex GET https://api.phemex.com/exchange/public/cfg/v2/products RequestHeaders: {'User-Agent': 'python-requests/2.28.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: phemex GET https://api.phemex.com/exchange/public/cfg/v2/products 200 ResponseHeaders: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Tue, 20 Sep 2022 00:59:06 GMT', 'Server': 'nginx', 'x-phemex-request-tracing': '9c30f522-7aa9-48b5-b232-2f0ecedf2123', 'X-RateLimit-Remaining': '99', 'X-RateLimit-Capacity': '100', 'X-Content-Type-Options': 'nosniff, nosniff', 'X-XSS-Protection': '1; mode=block, 1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate, no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY, SAMEORIGIN', 'Referrer-Policy': 'no-referrer, origin-when-cross-origin', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'X-Cache': 'Hit from cloudfront', 'Via': '1.1 1645a9d28193126ae7c151e9fce40ee8.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'DFW3-C1', 'X-Amz-Cf-Id': 'TKhxrRPD4exdUAxkez46V7YigMj4Z6WsiAl4g52xGirYW579Uhs8gA==', 'Age': '828'} ResponseBody: 

fetch Request: phemex GET https://api.phemex.com/v1/exchange/public/products RequestHeaders: {'User-Agent': 'python-requests/2.28.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: phemex GET https://api.phemex.com/v1/exchange/public/products 200 ResponseHeaders: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Tue, 20 Sep 2022 00:56:34 GMT', 'Server': 'nginx', 'x-phemex-request-tracing': 'fe4019ea-8ce0-4ef2-82a9-ad98166086b2', 'X-RateLimit-Remaining': '99', 'X-RateLimit-Capacity': '100', 'X-Content-Type-Options': 'nosniff, nosniff', 'X-XSS-Protection': '1; mode=block, 1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate, no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY, SAMEORIGIN', 'Referrer-Policy': 'no-referrer, origin-when-cross-origin', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'X-Cache': 'Hit from cloudfront', 'Via': '1.1 1645a9d28193126ae7c151e9fce40ee8.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'DFW3-C1', 'X-Amz-Cf-Id': 'VWyczjETQ6mtk1q6juWQococQDhANM9P9A_LjMQo5vUNymELcnoFOQ==', 'Age': '984'} ResponseBody: 

fetch Request: phemex POST https://api.phemex.com/orders RequestHeaders: {'x-phemex-access-token': '13d00bda-7a1a-45d4-9c01-1016bc043666', 'x-phemex-request-expiry': '1663636438', 'Content-Type': 'application/json', 'x-phemex-request-signature': '5415ef38a4d03ce9b72134b07fc4c42259fde33922bcc731792de534c8bbc946', 'User-Agent': 'python-requests/2.28.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"symbol":"uBTCUSD","side":"Buy","ordType":"Market","clOrdID":"ccxt20228aacc78fb8055e42","orderQty":1,"pegPriceType":"TrailingStopPeg ","pegOffsetValueEp":-100000}

fetch Response: phemex POST https://api.phemex.com/orders 200 ResponseHeaders: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Tue, 20 Sep 2022 01:12:58 GMT', 'Server': 'nginx', 'Vary': 'Accept-Encoding', 'x-phemex-request-tracing': 'a482fade-2d58-4c9d-b1ce-a3554b9f827d', 'X-RateLimit-Remaining-CONTRACT': '392', 'X-RateLimit-Capacity-CONTRACT': '500', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate, no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Content-Type-Options': 'nosniff, nosniff', 'X-Frame-Options': 'DENY, SAMEORIGIN', 'X-XSS-Protection': '1 ; mode=block, 1; mode=block', 'Referrer-Policy': 'no-referrer, origin-when-cross-origin', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 1645a9d28193126ae7c151e9fce40ee8.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'DFW3-C1', 'X-Amz-Cf-Id': 'Pw3HPFD8qOGb6t-n3ryAKxf7zJ_gr3XgG0mi1lSxJL9cQQ7SxQmbDQ=='} ResponseBody: {"code":0,"msg":"","data":{"bizError":0,"orderID":"55c4ab8d-d48d-43ab-8eb4-09c21ba71899","clOrdID":"ccxt20228aacc78fb8055e42","symbol":"uBTCUSD","side":"Buy","actionTimeNs":1663636378888046093,"transactTimeNs":1663636378888046093,"orderType":"Market","priceEp":200330000,"price":20033.00000000,"orderQty":1,"displayQty":0,"timeInForce":"ImmediateOrCancel","reduceOnly":false,"closedPnlEv":0,"closedPnl":0E-8,"closedSize":0,"cumQty":0,"cumValueEv":0,"cumValue":0E-8,"leavesQty":1,"leavesValueEv":200330,"leavesValue":20.03300000,"stopDirection":"UNSPECIFIED","stopPxEp":0,"stopPx":0E-8,"trigger":"UNSPECIFIED","pegOffsetValueEp":-100000,"execStatus":"PendingNew","pegPriceType":"TrailingStopPeg","ordStatus":"Created","execInst":"None"}}
{'info': {'bizError': '0', 'orderID': '55c4ab8d-d48d-43ab-8eb4-09c21ba71899', 'clOrdID': 'ccxt20228aacc78fb8055e42', 'symbol': 'uBTCUSD', 'side': 'Buy', 'actionTimeNs': '1663636378888046093', 'transactTimeNs': '1663636378888046093', 'orderType': 'Market', 'priceEp': '200330000', 'price': '20033.00000000', 'orderQty': '1', 'displayQty': '0', 'timeInForce': 'ImmediateOrCancel', 'reduceOnly': False, 'closedPnlEv': '0', 'closedPnl': '0E-8', 'closedSize': '0', 'cumQty': '0', 'cumValueEv': '0', 'cumValue': '0E-8', 'leavesQty': '1', 'leavesValueEv': '200330', 'leavesValue': '20.03300000', 'stopDirection': 'UNSPECIFIED', 'stopPxEp': '0', 'stopPx': '0E-8', 'trigger': 'UNSPECIFIED', 'pegOffsetValueEp': '-100000', 'execStatus': 'PendingNew', 'pegPriceType': 'TrailingStopPeg', 'ordStatus': 'Created', 'execInst': 'None'}, 'id': '55c4ab8d-d48d-43ab-8eb4-09c21ba71899', 'clientOrderId': 'ccxt20228aacc78fb8055e42', 'datetime': '2022-09-20T01:12:58.888Z', 'timestamp': 1663636378888, 'lastTradeTimestamp': 1663636378888, 'symbol': 'BTC/USD:USD', 'type': 'market', 'timeInForce': 'IOC', 'postOnly': False, 'reduceOnly': False, 'side': 'buy', 'price': 20033.0, 'stopPrice': 0.0, 'amount': 1.0, 'filled': 0.0, 'remaining': 1.0, 'cost': 0.0, 'average': None, 'status': 'open', 'fee': None, 'trades': None}
`

**Comment by pcriadoperez** [comment]
Hi @CloudTrauma,

Thanks for the verbose output. So the issue is the `ordType` is being sent as a market and not as a Stop or MarketIfTouched. (https://github.com/phemex/phemex-api-docs/blob/master/Public-Contract-API-en.md#orderexample)
I'll open a PR so that this is changed automatically when params for a stop order are passed in. In the meantime you can pass in the params `'ordType': 'Stop'` for a stop loss or  `'ordType':MarketIfTouched` for a takeProfit

**Comment by CloudTrauma** [comment]
This is good for take profit and stop loss but what about trailing stop

**Comment by ttodua** [comment]
after some research and looking into a correct way, I found out the correct way.
Will link a PR to this issue, and after it you would be able to run:
```
order = await ex.create_order('BTC/USDT:USDT', 'market', 'sell', 1, None, {
    'triggerPrice':85000,
    'triggerDirection': 'down', 
    'reduceOnly': true,
    'pegPriceType': 'TrailingStopPeg',
    'pegOffsetValueRp': -1234 // for inverse or margin markets you might need `pegOffsetValueEp` 
})
```
