### ISSUE TITLE
Bybit Conditional Order "params error!"

### ISSUE THREAD

**Issue by Nitrix321** [ccxt/ccxt#15070]
Hello :) ,  

I hope someone can help me with my issue.
I get the below Error if the program tries to place the stop limit / conditional order for ETHUSD inverse contracts. With linear contract ETHUSDT it is working fine. I don't know why and whats the difference there. 
Short explanation. It's a reduce only order to place stop limit below market price if long and in a winning position or above market price if short and in a winning position.

- OS: Windows 10
- Programming Language version: Python Spyder 3.9
- CCXT version: 1.92.81

```
    symbol = 'ETHUSD'
    pos_size = 2
    params = {"type":"swap","code":"ETH"}
    
    bybit_pos = bybit.fetch_positions([symbol], params=params)
    bybit_pos = bybit_pos[0]['info']
    entryprice = float(bybit_pos['entry_price'])
    stop_price = entryprice 
    
    paramslong={'base_price': stop_price+1, 
                  'stop_px': stop_price-1,
                  'reduce_only': True}   
    
    paramsshort={'base_price': stop_price-1,
                  'stop_px': stop_price+1,
                  'reduce_only': True}
    if long == False:
        
        bybit.create_stop_limit_order(symbol, side='buy', amount=pos_size, price=stop_price, stopPrice=stop_price, params=paramsshort)

     elif long == True:
        bybit.create_stop_limit_order(symbol, side='sell', amount=pos_size, price=stop_price, stopPrice=stop_price, params=paramslong)

    else:
        print('+++++++++ SOMETHING I DIDNT EXCPECT HAPPENS')        
   
```

```
 File ~\Desktop\bybit\BBETH.py:739 in <module>
    kill_switch3()

  File ~\Desktop\bybit\BBETH.py:279 in kill_switch3
    bybit.create_stop_limit_order(symbol, side='buy', amount=pos_size, price=stop_price, stopPrice=stop_trigger1, params=paramsshort)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:3105 in create_stop_limit_order
    return self.create_order(symbol, 'limit', side, amount, price, query)

  File ~\anaconda3\lib\site-packages\ccxt\bybit.py:2606 in create_order
    return self.create_contract_order(symbol, type, side, amount, price, params)

  File ~\anaconda3\lib\site-packages\ccxt\bybit.py:2855 in create_contract_order
    response = getattr(self, method)(self.extend(request, params))

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:500 in inner
    return entry(_self, **inner_kwargs)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2627 in request
    return self.fetch2(path, api, method, params, headers, body, config, context)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2624 in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:662 in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File ~\anaconda3\lib\site-packages\ccxt\bybit.py:5023 in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2870 in throw_exactly_matched_exception
    raise exact[string](message)

BadRequest: bybit {"ret_code":10001,"ret_msg":"params error!","ext_code":"","ext_info":"","result":null,"time_now":"1663685209.167718","rate_limit_status":99,"rate_limit_reset_ms":1663685209166,"rate_limit":100}
```

**Comment by Nitrix321** [comment]
Hi, if I find out how to create a verbose log, i will share it here :).

**Comment by carlosmiei** [comment]
@Nitrix321 simply do this `exchange.verbose = True`

**Comment by Nitrix321** [comment]
OK, thank you :), no clou why I havent't found that command with google...

Here you can see the complete log:

fetch Request: bybit GET https://api.bybit.com/v2/private/position/list?api_key=XXXXXXXXXXXXXXXX&code=ETH&recv_window=5000&symbol=ETHUSD&timestamp=1664099982335&type=swap&sign=fbdd58eefc5e716096ad488416dc21614b86ffefa1b49e8335da3b08503f4b89 RequestHeaders: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bybit GET https://api.bybit.com/v2/private/position/list?api_key=xxxxxxxxxxxxxxxx&code=ETH&recv_window=5000&symbol=ETHUSD&timestamp=1664099982335&type=swap&sign=fbdd58eefc5e716096ad488416dc21614b86ffefa1b49e8335da3b08503f4b89 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '1051', 'Server': 'Openresty', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': '*', 'Access-Control-Max-Age': '5', 'Access-Control-Expose-Headers': '*', 'Access-Control-Allow-Headers': 'X-BAPI-API-KEY,X-BAPI-TIMESTAMP,X-BAPI-RECV-WINDOW,X-BAPI-SIGN,X-BAPI-MAKER-API-KEY,X-BAPI-MAKER-SIGN,X-Referer,Content-Type', 'Expires': 'Sun, 25 Sep 2022 09:59:42 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Sun, 25 Sep 2022 09:59:42 GMT', 'Connection': 'keep-alive'} ResponseBody: {"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":{"id":0,"position_idx":0,"mode":0,"user_id":3346489,"risk_id":11,"symbol":"ETHUSD","side":"Sell","size":2,"position_value":"0.00151211","entry_price":"1322.65509784","is_isolated":false,"auto_add_margin":1,"leverage":"50","effective_leverage":"0.07","position_margin":"0.00003114","liq_price":"99999.9","bust_price":"99999.9","occ_closing_fee":"0.00000002","occ_funding_fee":"0","take_profit":"0","stop_loss":"0","trailing_stop":"0","position_status":"Normal","deleverage_indicator":2,"oc_calc_data":"{\"blq\":0,\"slq\":0,\"bmp\":0,\"smp\":0,\"fq\":2,\"bv2c\":0.021212,\"sv2c\":0.021188}","order_margin":"0","wallet_balance":"0.02498379","realised_pnl":"-0.00000091","unrealised_pnl":4e-07,"cum_realised_pnl":"-0.24706198","cross_seq":10608813242,"position_seq":0,"created_at":"2021-06-03T12:21:32.471834105Z","updated_at":"2022-09-25T09:58:06.623774692Z","tp_sl_mode":"Full"},"time_now":"1664099982.499325","rate_limit_status":117,"rate_limit_reset_ms":1664099982497,"rate_limit":120}

fetch Request: bybit GET https://api.bybit.com/v2/private/position/list?api_key=xxxxxxxxxxxxxxxxx&code=ETH&recv_window=5000&symbol=ETHUSD&timestamp=1664099982836&type=swap&sign=0db7c9e4a2fca664073eb77058e2665291494c145f26198ee0766f2badf6eb9d RequestHeaders: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bybit GET https://api.bybit.com/v2/private/position/list?api_key=xxxxxxxxxxxxxxx&code=ETH&recv_window=5000&symbol=ETHUSD&timestamp=1664099982836&type=swap&sign=0db7c9e4a2fca664073eb77058e2665291494c145f26198ee0766f2badf6eb9d 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '1051', 'Server': 'Openresty', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': '*', 'Access-Control-Max-Age': '5', 'Access-Control-Expose-Headers': '*', 'Access-Control-Allow-Headers': 'X-BAPI-API-KEY,X-BAPI-TIMESTAMP,X-BAPI-RECV-WINDOW,X-BAPI-SIGN,X-BAPI-MAKER-API-KEY,X-BAPI-MAKER-SIGN,X-Referer,Content-Type', 'Expires': 'Sun, 25 Sep 2022 09:59:43 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Sun, 25 Sep 2022 09:59:43 GMT', 'Connection': 'keep-alive'} ResponseBody: {"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":{"id":0,"position_idx":0,"mode":0,"user_id":3346489,"risk_id":11,"symbol":"ETHUSD","side":"Sell","size":2,"position_value":"0.00151211","entry_price":"1322.65509784","is_isolated":false,"auto_add_margin":1,"leverage":"50","effective_leverage":"0.07","position_margin":"0.00003114","liq_price":"99999.9","bust_price":"99999.9","occ_closing_fee":"0.00000002","occ_funding_fee":"0","take_profit":"0","stop_loss":"0","trailing_stop":"0","position_status":"Normal","deleverage_indicator":2,"oc_calc_data":"{\"blq\":0,\"slq\":0,\"bmp\":0,\"smp\":0,\"fq\":2,\"bv2c\":0.021212,\"sv2c\":0.021188}","order_margin":"0","wallet_balance":"0.02498379","realised_pnl":"-0.00000091","unrealised_pnl":4e-07,"cum_realised_pnl":"-0.24706198","cross_seq":10608813242,"position_seq":0,"created_at":"2021-06-03T12:21:32.471834105Z","updated_at":"2022-09-25T09:58:06.623774692Z","tp_sl_mode":"Full"},"time_now":"1664099983.000293","rate_limit_status":116,"rate_limit_reset_ms":1664099982997,"rate_limit":120}

fetch Request: bybit GET https://api.bybit.com/v2/private/position/list?api_key=xxxxxxxxxxxxxxx&code=ETH&recv_window=5000&symbol=ETHUSD&timestamp=1664099983337&type=swap&sign=7adbb8b73cec5db317a13294b1faec9c0818f0af35b3c9af71e2e309567e282a RequestHeaders: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bybit GET https://api.bybit.com/v2/private/position/list?api_key=xxxxxxxxxxxx&code=ETH&recv_window=5000&symbol=ETHUSD&timestamp=1664099983337&type=swap&sign=7adbb8b73cec5db317a13294b1faec9c0818f0af35b3c9af71e2e309567e282a 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '1051', 'Server': 'Openresty', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': '*', 'Access-Control-Max-Age': '5', 'Access-Control-Expose-Headers': '*', 'Access-Control-Allow-Headers': 'X-BAPI-API-KEY,X-BAPI-TIMESTAMP,X-BAPI-RECV-WINDOW,X-BAPI-SIGN,X-BAPI-MAKER-API-KEY,X-BAPI-MAKER-SIGN,X-Referer,Content-Type', 'Expires': 'Sun, 25 Sep 2022 09:59:43 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Sun, 25 Sep 2022 09:59:43 GMT', 'Connection': 'keep-alive'} ResponseBody: {"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":{"id":0,"position_idx":0,"mode":0,"user_id":3346489,"risk_id":11,"symbol":"ETHUSD","side":"Sell","size":2,"position_value":"0.00151211","entry_price":"1322.65509784","is_isolated":false,"auto_add_margin":1,"leverage":"50","effective_leverage":"0.07","position_margin":"0.00003114","liq_price":"99999.9","bust_price":"99999.9","occ_closing_fee":"0.00000002","occ_funding_fee":"0","take_profit":"0","stop_loss":"0","trailing_stop":"0","position_status":"Normal","deleverage_indicator":2,"oc_calc_data":"{\"blq\":0,\"slq\":0,\"bmp\":0,\"smp\":0,\"fq\":2,\"bv2c\":0.021212,\"sv2c\":0.021188}","order_margin":"0","wallet_balance":"0.02498379","realised_pnl":"-0.00000091","unrealised_pnl":4e-07,"cum_realised_pnl":"-0.24706198","cross_seq":10608813242,"position_seq":0,"created_at":"2021-06-03T12:21:32.471834105Z","updated_at":"2022-09-25T09:58:06.623774692Z","tp_sl_mode":"Full"},"time_now":"1664099983.498851","rate_limit_status":115,"rate_limit_reset_ms":1664099983496,"rate_limit":120}

fetch Request: bybit POST https://api.bybit.com/v2/private/stop-order/create RequestHeaders: {'Content-Type': 'application/json', 'Referer': 'CCXT', 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"symbol":"ETHUSD","side":"Buy","order_type":"Limit","time_in_force":"GoodTillCancel","qty":2,"price":1322.65,"trigger_by":"LastPrice","stop_px":1323.65,"base_price":1321.65509784,"reduce_only":true,"api_key":"79vHDDYPIDEYfEn9PI","recv_window":5000,"timestamp":"1664099983939","sign":"75d902b80b242dadc181629eeb18492d1a83613d4116234c97dd4980f401f669"}

fetch Response: bybit POST https://api.bybit.com/v2/private/stop-order/create 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '193', 'Server': 'Openresty', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': '*', 'Access-Control-Max-Age': '5', 'Access-Control-Expose-Headers': '*', 'Access-Control-Allow-Headers': 'X-BAPI-API-KEY,X-BAPI-TIMESTAMP,X-BAPI-RECV-WINDOW,X-BAPI-SIGN,X-BAPI-MAKER-API-KEY,X-BAPI-MAKER-SIGN,X-Referer,Content-Type', 'Expires': 'Sun, 25 Sep 2022 09:59:44 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Sun, 25 Sep 2022 09:59:44 GMT', 'Connection': 'keep-alive'} ResponseBody: {"ret_code":10001,"ret_msg":"params error!","ext_code":"","ext_info":"","result":null,"time_now":"1664099984.101874","rate_limit_status":99,"rate_limit_reset_ms":1664099984100,"rate_limit":100}
Traceback (most recent call last):

  File ~\Desktop\bybit\BBETH.py:751 in <module>
    kill_switch3()

  File ~\Desktop\bybit\BBETH.py:287 in kill_switch3
    bybit.create_stop_limit_order(symbol, side='buy', amount=pos_size, price=stop_price, stopPrice=stop_trigger1, params=paramsshort)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:3105 in create_stop_limit_order
    return self.create_order(symbol, 'limit', side, amount, price, query)

  File ~\anaconda3\lib\site-packages\ccxt\bybit.py:2606 in create_order
    return self.create_contract_order(symbol, type, side, amount, price, params)

  File ~\anaconda3\lib\site-packages\ccxt\bybit.py:2855 in create_contract_order
    response = getattr(self, method)(self.extend(request, params))

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:500 in inner
    return entry(_self, **inner_kwargs)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2627 in request
    return self.fetch2(path, api, method, params, headers, body, config, context)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2624 in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:662 in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File ~\anaconda3\lib\site-packages\ccxt\bybit.py:5023 in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2870 in throw_exactly_matched_exception
    raise exact[string](message)

BadRequest: bybit {"ret_code":10001,"ret_msg":"params error!","ext_code":"","ext_info":"","result":null,"time_now":"1664099984.101874","rate_limit_status":99,"rate_limit_reset_ms":1664099984100,"rate_limit":100}

**Comment by Nitrix321** [comment]
OK, thank you :), no clou why I havent't found that command with google...

Here you can see the complete log:

fetch Request: bybit GET https://api.bybit.com/v2/private/position/list?api_key=XXXXXXXXXXXXXXXX&code=ETH&recv_window=5000&symbol=ETHUSD&timestamp=1664099982335&type=swap&sign=fbdd58eefc5e716096ad488416dc21614b86ffefa1b49e8335da3b08503f4b89 RequestHeaders: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bybit GET https://api.bybit.com/v2/private/position/list?api_key=xxxxxxxxxxxxxxxx&code=ETH&recv_window=5000&symbol=ETHUSD&timestamp=1664099982335&type=swap&sign=fbdd58eefc5e716096ad488416dc21614b86ffefa1b49e8335da3b08503f4b89 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '1051', 'Server': 'Openresty', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': '*', 'Access-Control-Max-Age': '5', 'Access-Control-Expose-Headers': '*', 'Access-Control-Allow-Headers': 'X-BAPI-API-KEY,X-BAPI-TIMESTAMP,X-BAPI-RECV-WINDOW,X-BAPI-SIGN,X-BAPI-MAKER-API-KEY,X-BAPI-MAKER-SIGN,X-Referer,Content-Type', 'Expires': 'Sun, 25 Sep 2022 09:59:42 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Sun, 25 Sep 2022 09:59:42 GMT', 'Connection': 'keep-alive'} ResponseBody: {"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":{"id":0,"position_idx":0,"mode":0,"user_id":3346489,"risk_id":11,"symbol":"ETHUSD","side":"Sell","size":2,"position_value":"0.00151211","entry_price":"1322.65509784","is_isolated":false,"auto_add_margin":1,"leverage":"50","effective_leverage":"0.07","position_margin":"0.00003114","liq_price":"99999.9","bust_price":"99999.9","occ_closing_fee":"0.00000002","occ_funding_fee":"0","take_profit":"0","stop_loss":"0","trailing_stop":"0","position_status":"Normal","deleverage_indicator":2,"oc_calc_data":"{\"blq\":0,\"slq\":0,\"bmp\":0,\"smp\":0,\"fq\":2,\"bv2c\":0.021212,\"sv2c\":0.021188}","order_margin":"0","wallet_balance":"0.02498379","realised_pnl":"-0.00000091","unrealised_pnl":4e-07,"cum_realised_pnl":"-0.24706198","cross_seq":10608813242,"position_seq":0,"created_at":"2021-06-03T12:21:32.471834105Z","updated_at":"2022-09-25T09:58:06.623774692Z","tp_sl_mode":"Full"},"time_now":"1664099982.499325","rate_limit_status":117,"rate_limit_reset_ms":1664099982497,"rate_limit":120}

fetch Request: bybit GET https://api.bybit.com/v2/private/position/list?api_key=xxxxxxxxxxxxxxxxx&code=ETH&recv_window=5000&symbol=ETHUSD&timestamp=1664099982836&type=swap&sign=0db7c9e4a2fca664073eb77058e2665291494c145f26198ee0766f2badf6eb9d RequestHeaders: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bybit GET https://api.bybit.com/v2/private/position/list?api_key=xxxxxxxxxxxxxxx&code=ETH&recv_window=5000&symbol=ETHUSD&timestamp=1664099982836&type=swap&sign=0db7c9e4a2fca664073eb77058e2665291494c145f26198ee0766f2badf6eb9d 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '1051', 'Server': 'Openresty', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': '*', 'Access-Control-Max-Age': '5', 'Access-Control-Expose-Headers': '*', 'Access-Control-Allow-Headers': 'X-BAPI-API-KEY,X-BAPI-TIMESTAMP,X-BAPI-RECV-WINDOW,X-BAPI-SIGN,X-BAPI-MAKER-API-KEY,X-BAPI-MAKER-SIGN,X-Referer,Content-Type', 'Expires': 'Sun, 25 Sep 2022 09:59:43 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Sun, 25 Sep 2022 09:59:43 GMT', 'Connection': 'keep-alive'} ResponseBody: {"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":{"id":0,"position_idx":0,"mode":0,"user_id":3346489,"risk_id":11,"symbol":"ETHUSD","side":"Sell","size":2,"position_value":"0.00151211","entry_price":"1322.65509784","is_isolated":false,"auto_add_margin":1,"leverage":"50","effective_leverage":"0.07","position_margin":"0.00003114","liq_price":"99999.9","bust_price":"99999.9","occ_closing_fee":"0.00000002","occ_funding_fee":"0","take_profit":"0","stop_loss":"0","trailing_stop":"0","position_status":"Normal","deleverage_indicator":2,"oc_calc_data":"{\"blq\":0,\"slq\":0,\"bmp\":0,\"smp\":0,\"fq\":2,\"bv2c\":0.021212,\"sv2c\":0.021188}","order_margin":"0","wallet_balance":"0.02498379","realised_pnl":"-0.00000091","unrealised_pnl":4e-07,"cum_realised_pnl":"-0.24706198","cross_seq":10608813242,"position_seq":0,"created_at":"2021-06-03T12:21:32.471834105Z","updated_at":"2022-09-25T09:58:06.623774692Z","tp_sl_mode":"Full"},"time_now":"1664099983.000293","rate_limit_status":116,"rate_limit_reset_ms":1664099982997,"rate_limit":120}

fetch Request: bybit GET https://api.bybit.com/v2/private/position/list?api_key=xxxxxxxxxxxxxxx&code=ETH&recv_window=5000&symbol=ETHUSD&timestamp=1664099983337&type=swap&sign=7adbb8b73cec5db317a13294b1faec9c0818f0af35b3c9af71e2e309567e282a RequestHeaders: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bybit GET https://api.bybit.com/v2/private/position/list?api_key=xxxxxxxxxxxx&code=ETH&recv_window=5000&symbol=ETHUSD&timestamp=1664099983337&type=swap&sign=7adbb8b73cec5db317a13294b1faec9c0818f0af35b3c9af71e2e309567e282a 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '1051', 'Server': 'Openresty', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': '*', 'Access-Control-Max-Age': '5', 'Access-Control-Expose-Headers': '*', 'Access-Control-Allow-Headers': 'X-BAPI-API-KEY,X-BAPI-TIMESTAMP,X-BAPI-RECV-WINDOW,X-BAPI-SIGN,X-BAPI-MAKER-API-KEY,X-BAPI-MAKER-SIGN,X-Referer,Content-Type', 'Expires': 'Sun, 25 Sep 2022 09:59:43 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Sun, 25 Sep 2022 09:59:43 GMT', 'Connection': 'keep-alive'} ResponseBody: {"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":{"id":0,"position_idx":0,"mode":0,"user_id":3346489,"risk_id":11,"symbol":"ETHUSD","side":"Sell","size":2,"position_value":"0.00151211","entry_price":"1322.65509784","is_isolated":false,"auto_add_margin":1,"leverage":"50","effective_leverage":"0.07","position_margin":"0.00003114","liq_price":"99999.9","bust_price":"99999.9","occ_closing_fee":"0.00000002","occ_funding_fee":"0","take_profit":"0","stop_loss":"0","trailing_stop":"0","position_status":"Normal","deleverage_indicator":2,"oc_calc_data":"{\"blq\":0,\"slq\":0,\"bmp\":0,\"smp\":0,\"fq\":2,\"bv2c\":0.021212,\"sv2c\":0.021188}","order_margin":"0","wallet_balance":"0.02498379","realised_pnl":"-0.00000091","unrealised_pnl":4e-07,"cum_realised_pnl":"-0.24706198","cross_seq":10608813242,"position_seq":0,"created_at":"2021-06-03T12:21:32.471834105Z","updated_at":"2022-09-25T09:58:06.623774692Z","tp_sl_mode":"Full"},"time_now":"1664099983.498851","rate_limit_status":115,"rate_limit_reset_ms":1664099983496,"rate_limit":120}

fetch Request: bybit POST https://api.bybit.com/v2/private/stop-order/create RequestHeaders: {'Content-Type': 'application/json', 'Referer': 'CCXT', 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"symbol":"ETHUSD","side":"Buy","order_type":"Limit","time_in_force":"GoodTillCancel","qty":2,"price":1322.65,"trigger_by":"LastPrice","stop_px":1323.65,"base_price":1321.65509784,"reduce_only":true,"api_key":"xxxxxxxxxxxxx","recv_window":5000,"timestamp":"1664099983939","sign":"75d902b80b242dadc181629eeb18492d1a83613d4116234c97dd4980f401f669"}

fetch Response: bybit POST https://api.bybit.com/v2/private/stop-order/create 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '193', 'Server': 'Openresty', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': '*', 'Access-Control-Max-Age': '5', 'Access-Control-Expose-Headers': '*', 'Access-Control-Allow-Headers': 'X-BAPI-API-KEY,X-BAPI-TIMESTAMP,X-BAPI-RECV-WINDOW,X-BAPI-SIGN,X-BAPI-MAKER-API-KEY,X-BAPI-MAKER-SIGN,X-Referer,Content-Type', 'Expires': 'Sun, 25 Sep 2022 09:59:44 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Sun, 25 Sep 2022 09:59:44 GMT', 'Connection': 'keep-alive'} ResponseBody: {"ret_code":10001,"ret_msg":"params error!","ext_code":"","ext_info":"","result":null,"time_now":"1664099984.101874","rate_limit_status":99,"rate_limit_reset_ms":1664099984100,"rate_limit":100}
Traceback (most recent call last):

  File ~\Desktop\bybit\BBETH.py:751 in <module>
    kill_switch3()

  File ~\Desktop\bybit\BBETH.py:287 in kill_switch3
    bybit.create_stop_limit_order(symbol, side='buy', amount=pos_size, price=stop_price, stopPrice=stop_trigger1, params=paramsshort)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:3105 in create_stop_limit_order
    return self.create_order(symbol, 'limit', side, amount, price, query)

  File ~\anaconda3\lib\site-packages\ccxt\bybit.py:2606 in create_order
    return self.create_contract_order(symbol, type, side, amount, price, params)

  File ~\anaconda3\lib\site-packages\ccxt\bybit.py:2855 in create_contract_order
    response = getattr(self, method)(self.extend(request, params))

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:500 in inner
    return entry(_self, **inner_kwargs)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2627 in request
    return self.fetch2(path, api, method, params, headers, body, config, context)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2624 in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:662 in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File ~\anaconda3\lib\site-packages\ccxt\bybit.py:5023 in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2870 in throw_exactly_matched_exception
    raise exact[string](message)

BadRequest: bybit {"ret_code":10001,"ret_msg":"params error!","ext_code":"","ext_info":"","result":null,"time_now":"1664099984.101874","rate_limit_status":99,"rate_limit_reset_ms":1664099984100,"rate_limit":100}

**Comment by pcriadoperez** [comment]
Hi @Nitrix321 ,

So the issue is that too many decimals are being passed to the base_price.
You can fix this for now by changing the parameter `base_price` to `basePrice`.

I'll also open a PR to fix this to allow passing `base_price`

**Comment by Nitrix321** [comment]
Hi @pcriadoperez thank you very much!
