### ISSUE TITLE
"okx Exchange"  Unordered issue

### ISSUE THREAD

**Issue by sanghoon-o** [ccxt/ccxt#15075]
- OS:
- Programming Language version:  node (v12.0.0)
- CCXT version: 1.92.95

When my bot trades all contract volumes to the opposite position to close the position, a small amount (0.01) is re-captured to the opposite position with an unknown process after about 1 minute.

```
 const result = await this.getExchange().createOrder(
                    'BTC-USDT-SWAP', 'market', orderSide, myPosition.contracts,
                    undefined, {'tdMode': 'isolated'});
```

If I made a trade in my bot system, a record should be recorded in the log, but unknown trades were not left in my bot log.
Although it is not possible to know where this unknown transaction was made, a record remains in the okx application order history.

This experience was experienced several times after I changed the exchange from Binance to okx.
This is an issue that has not been experienced on the Binas Exchange.

I want you to experience similar unknown trading on okx exchange or share in alternative method.

Thank you.

**Comment by carlosmiei** [comment]
Hello @sanghoon-o, I'm not quite sure yet what's the role of CCXT on the issue you described, as you know, ccxt is only a middleware between the trader and the exchange, so if the exchange is doing something unexpected I'd suggest reaching out to them directly

**Comment by sanghoon-o** [comment]
> Hello @sanghoon-o, I'm not quite sure yet what's the role of CCXT on the issue you described, as you know, ccxt is only a middleware between the trader and the exchange, so if the exchange is doing something unexpected I'd suggest reaching out to them directly
