### ISSUE TITLE
[ccxt.pro]: gateio unable to ever start watching orderbook if synchronize fails

### ISSUE THREAD

**Issue by robbielitebit** [ccxt/ccxt#15083]
We had an issue when using `watchOrderBook` to connect with a market and it failed with the message: "gateio failed to synchronize WebSocket feed with the snapshot ....". 

After receiving this error, our code retried to call `watchOrderBook` again. However this call to `watchOrderBook` (after getting the  synchronize error) didn't resolve in any result.

I checked the code and if I understand correctly `fetchOrderBookSnapshot` is never called again because the subscription already exists. Is this intentional? And how would we be able to retry connecting to the market after getting the synchronize error?

**Comment by pcriadoperez** [comment]
Hi @robbielitebit ,

Correct the client only fetches the snapshot once.  I'll open a PR to solve this, so it does it on it's own after the error is thrown.

However in the meantime, you can close exchange and reopen it `exchange.close()`, however if you have other subscriptions this might not work for you. You can also set `exchange.clients[url][subscriptionHash] = undefined`

And a third options is to try is to increase the number of attempts to synchronize by setting `this.options['maxOrderBookSyncAttempts'] = 10` the default is 3.
