### ISSUE TITLE
about fetch_ohlcv

### ISSUE THREAD

**Issue by wtksyjpy** [ccxt/ccxt#1509]
Hi Author,

First thank you so much for creating such a great library.
I'd like to ask if you could add both quoteVolume and baseVolume into fetch_ohlcv?
Right now I think it is just quoteVolume?
Thanks!

Best,
Hank

**Comment by mkutny** [comment]
> Right now I think it is just `quoteVolume`?

Base volume.

> I'd like to ask if you could add both `quoteVolume` and `baseVolume` into fetch_ohlcv?

If an exchange provides `quoteVolume` it's technically possible to pass it through `ccxt`. But I'm afraid most of them do not.

Still wonder: what indicator would need it?

**Comment by wtksyjpy** [comment]
HI Max,

Thank you so much for your answers.
I will try to extract it for specific exchanges then.
I'm trying to keep all the info and rebuild the real picture.

Best,
Hank
