### ISSUE TITLE
poloniex fetchwithdrawals and fetchDeposits error

### ISSUE THREAD

**Issue by hosseinab** [ccxt/ccxt#15098]
OS: Windows 11
Programming Language version: PYTHON 3.10.5
CCXT version: "ccxt/ccxt": "^1.93.66",
Exchange: poloniex
Method: fetchwithdrawals and fetchDeposits

hi
my code :
since = None
limit = 100
end_time = connection.milliseconds()
params = {
'end_time': int(end_time / 1000),
}
deposits = connection.fetch_deposits("USDT", since, limit, params)

error :
poloniex GET https://api.poloniex.com/wallets/activity?start=1352965515&end=1664005515&limit=100&end_time=1664005514 400 Bad Request {
  "code" : "FORBIDDEN",
  "message" : "Invalid API key/secret pair."
}

verbose output :
fetch Request: poloniex GET https://api.poloniex.com/wallets/activity?start=1352965515&end=1664005515&limit=100&end_time=1664005514 RequestHeaders: {'Content-Type': 'application/json', 'key': '***', 'signTimestamp': '1664005515195', 'signature': '***', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None
127.0.0.1 - - [24/Sep/2022 11:15:15] "GET / HTTP/1.1" 200 -

fetch Response: poloniex GET https://api.poloniex.com/wallets/activity?start=1352965515&end=1664005515&limit=100&end_time=1664005514 400 ResponseHeaders: {'Date': 'Sat, 24 Sep 2022 07:45:15 GMT', 'Content-Type': 'application/json', 'Content-Length': '72', 'Connection': 'keep-alive', 'RateLimit-Filter': 'updated', 'Web-Filter': 'authenticated', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '**-AMS'} ResponseBody: {
  "code" : "FORBIDDEN",
  "message" : "Invalid API key/secret pair."
}

***** my api key and secret is valid .

**Comment by hosseinab** [comment]
fetch_deposit_address it has the same error in poloniex

**Comment by carlosmiei** [comment]
Hello @hosseinab, thanks for letting us know, we will check it

**Comment by carlosmiei** [comment]
@hosseinab can you please update to the latest version and check if the error is gone?

**Comment by hosseinab** [comment]
@carlosmiei upgrade to ccxt-1.93.98
but get the same error :

fetch Request: poloniex GET https://api.poloniex.com/wallets/activity?start=1352987590&end=1664027590&end_time=1664027588 RequestHeaders: {'Content-Type': 'application/json', 'key': '***', 'signTimestamp': '1664027590298', 'signature': '****=', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: poloniex GET https://api.poloniex.com/wallets/activity?start=1352987590&end=1664027590&end_time=1664027588 400 ResponseHeaders: {'Date': 'Sat, 24 Sep 2022 13:53:10 GMT', 'Content-Type': 'application/json', 'Content-Length': '72', 'Connection': 'keep-alive', 'RateLimit-Filter': 'updated', 'Web-Filter': 'authenticated', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '74fc0136d933b71f-AMS'} ResponseBody: {
  "code" : "FORBIDDEN",
  "message" : "Invalid API key/secret pair."
}
fetch withdrawals : poloniex GET https://api.poloniex.com/wallets/activity?start=1352987590&end=1664027590&end_time=1664027588 400 Bad Request {
  "code" : "FORBIDDEN",
  "message" : "Invalid API key/secret pair."
}
