### ISSUE TITLE
ccxt.base.errors.ExchangeError: bybit markets not loaded

### ISSUE THREAD

**Issue by Smartromain** [ccxt/ccxt#15097]
Hello,

How come this doesnt work, and get error : ccxt.base.errors.ExchangeError: bybit markets not loaded

import ccxt
symbol = 'BTCUSDT'
print(exchange.market(symbol)['precision']['amount'])

but this works:

import ccxt
symbol = 'BTCUSDT'
print(exchange.fetch_ohlcv(symbol, timeframe='1m', limit=1))
print(exchange.market(symbol)['precision']['amount'])

- OS: win10
- Programming Language version: python 3.8
- CCXT version: 1.93.43

**Comment by carlosmiei** [comment]
Hello @Smartromain, markets will be automatically loaded after the first call to a unified method, if you want to access it right away, you can do this:

```Python
symbol = 'BTCUSDT'
exchange.load_markets() # Trigger market loading
print(exchange.market(symbol)['precision']['amount'])
```

**Comment by Smartromain** [comment]
Thanks, amazing. I will try it

**Comment by samgermain** [comment]
> Thanks, amazing. I will try it

Did this work for you?

**Comment by Smartromain** [comment]
yes it worked
