### ISSUE TITLE
createDepositAddress error for usdt in bitfinex2

### ISSUE THREAD

**Issue by hosseinab** [ccxt/ccxt#15103]
OS: Windows 11
Programming Language version: PYTHON 3.10.5
CCXT version: "ccxt/ccxt": "^1.93.98",
Exchange: bitfinex2
Method: createDepositAddress 

hi . 
my code :
params = {
    'network': "TRC20",
}
fetch_result = connection.fetch_deposit_address("USDT", params)

output :
ccxt.base.errors.PermissionDenied: bitfinex2 Unknown currency

verbose :
fetch Request: bitfinex2 POST https://api.bitfinex.com/v2/auth/w/deposit/address RequestHeaders: {'bfx-nonce': '***', 'bfx-apikey': '****', 'bfx-signature': '****', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"method":"tetherusx","wallet":"exchange","op_renew":0}

fetch Response: bitfinex2 POST https://api.bitfinex.com/v2/auth/w/deposit/address 500 ResponseHeaders: {'Date': 'Sat, 24 Sep 2022 16:38:10 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '34', 'Connection': 'keep-alive', 'X-Frame-Options': 'sameorigin', 'X-XSS-Protection': '1; mode=block', 'Referrer-Policy': 'same-origin', 'X-Download-Options': 'noopen', 'X-Content-Type-Options': 'nosniff', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains;', 'X-Permitted-Cross-Domain-Policies': 'none', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '74fcf2ea9d83b737-AMS'} ResponseBody: ["error",10001,"Unknown currency"]

**Comment by carlosmiei** [comment]
Hello @hosseinab, 

I managed to fetch it on my end, can you please double-check your API permissions?

```
p bitfinex2 fetchDepositAddress "USDT" '{"network":"TRC20"}'          
Python v3.9.7
CCXT v1.93.69
bitfinex2.fetchDepositAddress(USDT,{'network': 'TRC20'})
{'address': 'TQFEBKq3JZ2oeAYrk3s3jmbVzx99zSYex3',
 'currency': 'USDT',
 'info': ['1664044169115',
          'acc_dep',
          None,
          None,
          [None,
           'TETHERUSX',
           'USX',
           None,
           'TQFEBKq3JZ2oeAYrk3s3jmbVzx99zSYex3',
           None],
          None,
          'SUCCESS',
          'success'],
 'network': None,
 'tag': None}
```

**Comment by hosseinab** [comment]
@carlosmiei 
your account Has kyc?

**Comment by carlosmiei** [comment]
@hosseinab yes it has, afaik you can't deposit/withdrawal at bitfinex without KYC
