### ISSUE TITLE
GDAX post-only

### ISSUE THREAD

**Issue by fluffytid** [ccxt/ccxt#1510]
- OS: Windows 7
- Programming Language version: Javascript/Chrome
- CCXT version: 
- Exchange: GDAX
- Method: createLimitSellOrder

GDAX API has a post-only option when submitting a limit order to avoid that lag makes it execute as market because the prize moves while submitting

https://docs.gdax.com/#place-a-new-order

"POST ONLY
The post-only flag indicates that the order should only make liquidity. If any part of the order results in taking liquidity, the order will be rejected and no part of it will execute."

I supposed this would be included in ccxt using the extra params, but I have no idea how to get it to work, so far I tried this:

res = await gdax.createLimitSellOrder("ETH/EUR", round8(order.ammount), round(order.prize), {post_only: "true"});

But didn't work.

Thanks for your time.

**Comment by mkutny** [comment]
If you do `gdax.verbose = true` before you make a call it will be easier to see where the problem is.

Nevertheless. Don't have an account on GDAX but it might happen if you use `true` instead of `"true"`. At least in their example at the link you provided, they use `false`, not `"false"`.

**Comment by kroitor** [comment]
@fluffytid the answer of @mkutny is correct, can you please show verbose output and change `"true"` to `true` ?

> But didn't work.

You have to much more precise than that ) What you expected to see? And what you saw instead (with verbose output)?

**Comment by fluffytid** [comment]
I think it is working now because some orders near the limit are "disappearing" while the number of orders with fees has been greatly reduced. Thanks for your help.

**Comment by fluffytid** [comment]
Still curious that gdax seems to be sending me an id for the order, but however when I later try to fetch it, the order is no longer existing.

**Comment by kroitor** [comment]
@fluffytid ok, let us know if you have any questions with it, but, please, next time don't forget to post verbose output as per this doc: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Thx!
