### ISSUE TITLE
Bybit ccxt - How to close my position with a market order

### ISSUE THREAD

**Issue by Azure2424** [ccxt/ccxt#15126]
Hi, I've just started learning Python a week ago and a complete beginner/noob. 
I have a issue that I cannot solve.

I've created a working entry bot with python to enter positions via market order on bybit, the bot gets a json message from tradingview webhook alerts of the asset it wants to enter and then enters it with 99% of my account balance. 

This is what my code looks like

```
import ccxt
import Config

bybit = ccxt.bybit({
    'apiKey': Config.API_KEY,
    'secret': Config.API_SECRET,
    'password': Config.PASSPHRASE
})

def crypto(request):
    
    data = request.get_json()
    if data['PASSPHRASE'] != Config.PASSPHRASE:
        return{
            "code": "error",
            "message": "invalid passphrase"
        }


    tickers = { 
        'ADA' :  "ADA/USDT:USDT",
        'BTC' : "BTC/USDT:USDT",
        'SOL' : "SOL/USDT:USDT",
        'LINK' : "LINK/USDT:USDT"
    }


    ticker = tickers[data['ticker']]

    
    orderbook = bybit.fetch_order_book(ticker)
    bidy = orderbook['bids'][0][0] if len (orderbook['bids']) > 0 else None
    asky = orderbook['asks'][0][0] if len (orderbook['asks']) > 0 else None

    
    freebalance = bybit.fetch_total_balance()
    usdtfreebalance = freebalance['USDT']
    usdtfreebalancepercentage = usdtfreebalance * 0.99
    qauntity = usdtfreebalancepercentage / asky


    order = bybit.create_market_buy_order(ticker, qauntity)

    return order
```
^ This is a working entry bot that runs on my google cloud server and takes any orders sent to it for entry positions

I would like to make another bot that would fully close my positions with a market order dynamically, meaning I would not want to set the quantity of contracts to close, just to fully close all contracts of the position. so for more clarification: just like my entry bot for example, when an json message from my alert like "ticker": "ADA" gets sent to it. my entry bot enters that ticker with 99% of my balance. I would want to make a bot that does the same thing but with closing positions so when an "ticker": "ADA json message gets sent to it it would fully market close the adausdt position that the entry bot has opened.

Please if someone could write what the code for the closing positions bot would that look like.
I would greatly appreciate your help!

**Comment by carlosmiei** [comment]
Hello @Azure2424,

Please check out this example where a position is open and closed: https://github.com/ccxt/ccxt/blob/master/examples/py/bybit-updated.py#L54

**Comment by Azure2424** [comment]
Thanks for your help.

is there a way to make the bot choose between if it will a enter position or close position with a json text message?

so for example if the json message says “position”: “enter” the bot would enter And if it says “position: “close” it will close the open position.

**Comment by Azure2424** [comment]
How would I go about dynamically calculating the quantity needed to close the position?

**Comment by Azure2424** [comment]
When i try to close my order I'm getting this error code: AttributeError
AttributeError: type object 'type' has no attribute 'lower'
