### ISSUE TITLE
ccxt.base.errors.BadSymbol

### ISSUE THREAD

**Issue by newbienoobnoob** [ccxt/ccxt#15136]
- OS: win 10 
- Programming Language version: python 3.9.12 
- CCXT version: 1.93.108

That code gets the symbol, price and volume filtered at a specific time.
The code that was working normally for 2 months suddenly stopped working about a week ago because of this error.
`AXSBIDR` is the symbol that should be filtered.

If it's a problem with my Python code, I think it shouldn't have worked in the first place.
I don't know what the problem is.

# CODE

```
import pandas as pd
import datetime as dt
import ccxt
import time
import schedule

# print('CCXT version:', ccxt.__version__)  # Python

def timer():

    exchange = ccxt.binance({})
    tickers = exchange.fetch_tickers()

    pairs = []
    for symbol, d in tickers.items():
        if not exchange.market(symbol)['active']:
            continue

        if symbol.endswith('UP') or symbol.endswith('DOWN'):
            continue
        

        coin, quote = symbol.split('/')

        if coin in ('BUSD', 'USDC') or quote not in ('USDT', 'BUSD', 'BTC'):
            continue

        pairs.append((coin, quote, d['close'], d['quoteVolume']))

    pair_dict = {}
    for coin, quote, close, volume in pairs:
        pair_dict[coin] = pair_dict.get(coin, {})
        pair_dict[coin].update({quote: (close, volume)})

    filtered_pairs = []
    for coin, data_dict in pair_dict.items():
        if data_dict.get('USDT', None):
            filtered_pairs.append((f'{coin}/USDT', data_dict['USDT'][0], data_dict['USDT'][1]))

        elif data_dict.get('BUSD', None):
            filtered_pairs.append((f'{coin}/BUSD', data_dict['BUSD'][0], data_dict['BUSD'][1]))


        elif data_dict.get('BTC', None):
            filtered_pairs.append((f'{coin}/BTC', data_dict['BTC'][0], data_dict['BTC'][1]))

    df = pd.DataFrame(data=filtered_pairs, columns=['symbol', 'close', 'volume'])
    df = df.astype({
        'symbol': 'category', 'close': 'float64', 'volume': 'float64'
    })


    df.to_pickle(f'data/{dt.datetime.today().date()}_binance.pkl')


schedule.every().day.at("00:00:00").do(timer)

while True:
    schedule.run_pending()
    time.sleep(1)

```

# OUTPUT

```
Traceback (most recent call last):
  File "c:\Users\User\Desktop\Bot\timer.py", line 68, in <module>
    schedule.run_pending()
  File "C:\Users\User\anaconda3\lib\site-packages\schedule\__init__.py", line 780, in run_pending
    default_scheduler.run_pending()
  File "C:\Users\User\anaconda3\lib\site-packages\schedule\__init__.py", line 100, in run_pending
    self._run_job(job)
  File "C:\Users\User\anaconda3\lib\site-packages\schedule\__init__.py", line 172, in _run_job
    ret = job.run()
  File "C:\Users\User\anaconda3\lib\site-packages\schedule\__init__.py", line 661, in run
    ret = self.job_func()
  File "c:\Users\User\Desktop\Bot\timer.py", line 18, in timer
    if not exchange.market(symbol)['active']:
  File "C:\Users\User\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 3002, in market
    raise BadSymbol(self.id + ' does not have market symbol ' + symbol)
ccxt.base.errors.BadSymbol: binance does not have market symbol AXSBIDR
```

**Comment by samgermain** [comment]
The error is correct, there is no market on binance for `AXSBIDR` or `AXS/BIDR`
I'm not really sure what your question is

**Comment by newbienoobnoob** [comment]
I'd like to know why the error suddenly occurred in code that wasn't problematic. Is it a problem with my code or a CCXT problem?

**Comment by samgermain** [comment]
> I'd like to know why the error suddenly occurred in code that wasn't problematic. Is it a problem with my code or a CCXT problem?

I can't know without seeing your code, but I do know that there is no market symbol that looks like `AXSBIDR` on binance, so if you tried to pass `AXSBIDR` as a symbol to a method, you would receive this error

**Comment by newbienoobnoob** [comment]
I have attached the code, please check it

**Comment by samgermain** [comment]
> I have attached the code, please check it

I'm getting `undefined name 'pairs'`, I'm going to need to know what pairs is

**Comment by samgermain** [comment]
[Binance removed the axsbidr market back in february.](https://www.binance.com/en/support/announcement/f7af728484fc4e8b82cdecf017d8b18a) I know that today binance removed a lot of trading pairs for other stable coins. Maybe you had axsbidr stored in some kind of data structure that wasn't updated, and when you tried to access that market for that symbol, the market wasn't there anymore. I'm not sure why you just got the error now if it was removed back in February, but maybe it was still listed on their API until now

**Comment by samgermain** [comment]
Basically the error is happening because you are calling `exchange.market` with a symbol that no longer exists among binance's markets, either directly or via a method that calls `exchange.market`. You'll need to keep track of what symbols you're using, and when you refresh your exchange objects markets, you need to make sure that you're no longer retaining delisted markets elsewhere in your program (other than for special use cases where you fully understand what you're doing)

I'm going to close this issue. Feel free to reopen it if you have any more questions
