### ISSUE TITLE
Gemini API update on February 9, 2018

### ISSUE THREAD

**Issue by kornrunner** [ccxt/ccxt#1513]
I've received notification from Gemini:

> In two weeks on February 9, 2018, Gemini will release the following breaking changes to the REST API:
>
> - when an API user makes an order status request but the order is not found, instead of returning 500 the server will now return 404
> - when an API user tries to place an order but has insufficient funds, instead of returning 500 the server will now return 406
> - when an API user tries to place or cancel an order but this action cannot be allowed due to timing or market conditions (market is closed, auction is not open, etc) then instead of returning 500 the server will now return 400
> - the text of the error message for an attempt to retrieve more than seven days of public trade history has been corrected
>
> As always, in addition to the 4xx response code, the Gemini API response body will contain a JSON object whose reason and message are documented at https://docs.gemini.com/rest-api/#error-payload.
>
> We expect the changes to be available to test in our sandbox environment for two weeks beginning this Friday, January 26, 2018, after the scheduled maintenance period ends.

**Comment by mkutny** [comment]
What a great list of http status code abuses )
Still, 4xx is better than 500.
