### ISSUE TITLE
Kucoin fetch_order_book count

### ISSUE THREAD

**Issue by JT102** [ccxt/ccxt#1514]
Noticed that when I request order book from Kucoin function returns just 6 bids/asks (default by Kucoin).
- Programming Language version: PHP (I suppose others too)
- Exchange: Kucoin
- Method: fetch_order_book, fetch_L2_order_book
This is how it is called:
https://api.kucoin.com/v1/open/orders?symbol=DBC-ETH&count=10
Should be (limit instead of count):
https://api.kucoin.com/v1/open/orders?symbol=DBC-ETH&limit=10

Can someone fix it?
Thank you for awesome project!

**Comment by mkutny** [comment]
Can't reproduce.
Can you `exchange.verbose = true` and show the exact call & output?

You also missed ccxt version.

**Comment by JT102** [comment]
sorry can't find ccxt version. but I just downloaded it two days ago.
```
$exchange = '\\ccxt\\kucoin';
$exchange = new $exchange (array('verbose' => true,));
$order_book = $exchange->fetch_l2_order_book ('DBC/ETH',array('count'=>10));
```
Output:

> Request:
> Array
> (
>     [0] => GET
>     [1] => https://api.kucoin.com/v1/market/open/symbols
>     [2] => Array
>         (
>             [User-Agent] => Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
>         )
> 
>     [3] => 
> )
> 
> Request:
> Array
> (
>     [0] => GET
>     [1] => https://api.kucoin.com/v1/open/orders?symbol=DBC-ETH&count=10
>     [2] => Array
>         (
>             [User-Agent] => Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
>         )
> 
>     [3] => 
> )
> array(4) {
>   ["bids"]=>
>   array(6) {
>     [0]=>
>     array(2) {
>       [0]=>
>       float(0.00016)
>       [1]=>
>       float(695.3238)
>     }
>     [1]=>
>     array(2) {
>       [0]=>
>       float(0.000159)
>       [1]=>
>       float(2428.796)
>     }
>     [2]=>
>     array(2) {
>       [0]=>
>       float(0.000158)
>       [1]=>
>       float(2722.367)
>     }
>     [3]=>
>     array(2) {
>       [0]=>
>       float(0.000157)
>       [1]=>
>       float(22194.3267)
>     }
>     [4]=>
>     array(2) {
>       [0]=>
>       float(0.000156)
>       [1]=>
>       float(13364.8151)
>     }
>     [5]=>
>     array(2) {
>       [0]=>
>       float(0.000155)
>       [1]=>
>       float(137339.8061)
>     }
>   }
>   ["asks"]=>
>   array(6) {
>     [0]=>
>     array(2) {
>       [0]=>
>       float(0.000163)
>       [1]=>
>       float(62.4398)
>     }
>     [1]=>
>     array(2) {
>       [0]=>
>       float(0.000164)
>       [1]=>
>       float(1760.558)
>     }
>     [2]=>
>     array(2) {
>       [0]=>
>       float(0.000165)
>       [1]=>
>       float(415.9801)
>     }
>     [3]=>
>     array(2) {
>       [0]=>
>       float(0.000167)
>       [1]=>
>       float(9253.8926)
>     }
>     [4]=>
>     array(2) {
>       [0]=>
>       float(0.000168)
>       [1]=>
>       float(5287.7072)
>     }
>     [5]=>
>     array(2) {
>       [0]=>
>       float(0.000169)
>       [1]=>
>       float(14570.7055)
>     }
>   }
>   ["timestamp"]=>
>   string(13) "1516525569643"
>   ["datetime"]=>
>   string(29) "2018-01-21T09:06:10.643+00:00"
> }
>

**Comment by kroitor** [comment]
> Can someone fix it?

Let's see... In your code you are breaking the otherwise-working library yourself. You are adding `'count' => 10, where the exchange expects `limit` instead of `count`, like you said it yourself. Yet still, you are passing a `count` parameter for an unexplained reason. Here's your code:

```PHP
$exchange = '\\ccxt\\kucoin';
$exchange = new $exchange (array('verbose' => true,));
$order_book = $exchange->fetch_l2_order_book ('DBC/ETH',array('count'=>10));
```

And here's the proper code:

```PHP
$exchange = '\\ccxt\\kucoin';
$exchange = new $exchange (array('verbose' => true,));
$order_book = $exchange->fetch_l2_order_book ('DBC/ETH',array('limit'=>10));
```

Let us know if it doesn't help.

**Comment by JT102** [comment]
Thanks but I took an example from wiki:
```
// instantiate the exchange by id
$exchange = '\\ccxt\\kraken';
$exchange = new $exchange ();
var_dump ($exchange->fetch_order_book ('BTC/USD', array (
    'count' => 10, // up to ten orders on each side for example
)));
```
I thought that 'count' is uniform for all exchanges. So should I put 'limit' or 'count' depends on what exchange I use?

**Comment by kroitor** [comment]
@JT102 yes, the extra `params` are not unified, those are exchange-specific. We will unify the depth of the orderbook soon, as an argument of the fetchOrderBook function, but for now you will have to use exchange-specific params.

> So should I put 'limit' or 'count' depends on what exchange I use?

Exactly.
