### ISSUE TITLE
OKX batch orders

### ISSUE THREAD

**Issue by kaiqiangh** [ccxt/ccxt#15154]
- OS: Ubuntu 20.04
- Programming Language version: PHP 7.4
- CCXT version: 1.91.22

Just a simple question: Does CCXT support to place batch orders in one request for OKX exchange? Thanks.

Kind regards.
Kai

**Comment by carlosmiei** [comment]
Hello @kaiqiangh, yes it does, you just need to set it in the options like this:

```Python
exchange.options['createOrder'] = 'privatePostTradeBatchOrders'
```

**Comment by kaiqiangh** [comment]
Hi @carlosmiei ,

Thanks for your reply. 

I found that the default method is already set to 'privatePostTradeBatchOrders' in the function 'createOrder'.
`        const defaultMethod = this.safeString (this.options, 'createOrder', 'privatePostTradeBatchOrders');
`

Then I overwrote some piece of codes in this function (around line 2154) and works for me. 
`
if ((method === 'privatePostTradeOrder') || (method === 'privatePostTradeOrderAlgo')) {
            extendedRequest = this.extend (request, params);
        } else if (method === 'privatePostTradeBatchOrders') {
            // keep the request body the same
            // submit a single order in an array to the batch order endpoint
            // because it has a lower ratelimit
            // extendedRequest = [ this.extend (request, params) ];
            if(batch) {
                extendedRequest = [request, params];
            } else {
                extendedRequest = [ this.extend (request, params) ];
            }
        } else {
            throw new ExchangeError (this.id + ' createOrder() this.options["createOrder"] must be either privatePostTradeBatchOrders or privatePostTradeOrder');
        }
`

**Comment by kaiqiangh** [comment]
I figure out how it works now. Thanks.
