### ISSUE TITLE
ccxt pro kucoinfutures interface

### ISSUE THREAD

**Issue by simonblack** [ccxt/ccxt#15161]
Hey all, 

How would I go about creating a Kucoin Futures interface for ccxt pro and is the reason it isnt alread implemented a matter of difficulty or something im missing

cheers

**Comment by samgermain** [comment]
> Hey all,
> 
> How would I go about creating a Kucoin Futures interface for ccxt pro and is the reason it isnt alread implemented a matter of difficulty or something im missing
> 
> cheers

The `kucoinfutures` CCXT class is relatively new compared to the other exchanges. I plan to write a ccxtpro implementation for `kucoinfutures` soon

**Comment by simonblack** [comment]
Ah okay, thanks for the update

**Comment by ttodua** [comment]
@simonblack you are always welcome to contribute to CCXT if you know how to code. typically, you can take another existing WS exchange and imitate to it, and make a Pull Request . https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

**Comment by simonblack** [comment]
> @simonblack you are always welcome to contribute to CCXT if you know how to code. typically, you can take another existing WS exchange and imitate to it, and make a Pull Request . https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

Okay sounds good! I initially made a rough port in python then realized everything here is generated from JS, something im a tad rusty in! Was going to make a JS attempt in the future if @samgermain is still too tied up with their other assignments on here by that time

cheers!

**Comment by samgermain** [comment]
> 

I plan to implement the kucoinfutures websocket/pro interface next week

**Comment by Hadevmin** [comment]
Thanks a lot @samgermain
