### ISSUE TITLE
Binance minimal order value

### ISSUE THREAD

**Issue by darthf1** [ccxt/ccxt#1516]
A couple of weeks ago Binance silently implemented a minimal trade value of `0.002 BTC` / `0.02 ETH`. Now this is also updated on their trading rule page. 

https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule

If i check the `MIN_NOTIONAL` filter for Binance market `ETH/BTC` it is currently defined as `0.001`. Isn't that the old value or am i looking at the wrong variable?

**Comment by kroitor** [comment]
MIN_NOTIONAL is the minimal **cost** of the order.

- `cost = amount * price`
- `cost !== amount`
- cost should be greater than MIN_NOTIONAL
- amount should be evenly divisible by their lot size

Their filters are described here: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#filters

![binance-filters](https://user-images.githubusercontent.com/1294454/35457066-aaaef072-02e8-11e8-8c56-89f2697e6bd3.jpg)

If you're looking for minimal costs and minimal amounts, you should not be looking at exchange-specific params (red), instead you can take unified ccxt params (green), those should be standard for all exchanges, not just Binance.

The red `info` field contains their answer, unparsed, `as is`, and the rest of those fields contain the parsed unified info, which is exchange-agnostic.

Let us know if it doesn't answer your question.

**Comment by darthf1** [comment]
Ok thanks for your reply. But how can I get the minimal trade value for a market/exchange? This is what i get (in PHP) when i dump the `getMarkets()` value for `ETH/BTH`. 

![afbeelding](https://user-images.githubusercontent.com/17253332/35457404-22f14d9c-02d9-11e8-9aae-1ed650845369.png)

**Comment by kroitor** [comment]
@darthf1 

> But how can I get the minimal trade value for a market/exchange?

If you can precisely define what a *"minimal trade"* is – I will be able to tell how to get it.
In general, there is no such thing as **minimal trade**.

There are:

- minimal amount of the order
- minimal cost of the order
- minimal price of the order
- cost = amount * price

Which of those minimums you want?

**Comment by darthf1** [comment]
Terminology is important here indeed. Thanks again for replying.

I'm looking for what Binance calls the minimal order value ([as defined here](https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule)), which would be (for me) the minimal order amount. And with `amount` I mean the `quantity * price`. But i think my quantity is your amount, so what im actually looking for in your terminology would be `cost`?

Wild example:
So if I create a buy order for a quantity of 2 ETH, where the price is currently 0.0005 BTC, the total order amount would be 0.001 BTC. This results in an error because the order amount is below the limit of 0.002 BTC. I'm looking for a variable which holds the min limit of 0.002 BTC.

So, looking at the picure:

![afbeelding](https://user-images.githubusercontent.com/17253332/35458138-7bb09b7a-02db-11e8-822b-075b24177502.png)

Shouldn't `$market['limits']['cost']['min']` be `0.002` instead of `0.001`?

**Comment by kroitor** [comment]
> I'm looking for what Binance calls the minimal order value (as defined here), which would be (for me) the minimal order amount. And with amount I mean the quantity * price. But i think my quantity is your amount, so what im actually looking for in your terminology would be cost?

Exactly. My `cost` == your `quantity * price`. My `amount` = your `quantity`.

> Wild example:
> So if I create a buy order for a quantity of 2 ETH, where the price is currently 0.0005 BTC, the total order amount would be 0.001 BTC. This results in an error because the order amount is below the limit of 0.002 BTC. I'm looking for a variable which holds the min limit of 0.002 BTC.

According to Binance (https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule), their current minimums are:

- min amount (quantity) = 0.001ETH
- min price = 0.000001 BTC
- min cost = 0.002BTC

However, their API reports min cost of 0.001BTC, so there's a conflict. We've contacted their team on this, waiting for their reply, and will update you here.

> Shouldn't $market['limits']['cost']['min'] be 0.002 instead of 0.001?

It should, but, obviously, it's not. So, let's wait for their answer, maybe they will update the API info as well. If not, we will then add a workaround to web-scrape their minimums from their Trading Rule page.

**Comment by darthf1** [comment]
Great! Thats all i needed, thanks! Waiting eagerly for the reply from their team.

**Comment by kroitor** [comment]
```
Igor Kroitor, [26.01.18 23:06]
Hi! Hope you're doing well )
One quick question on minimums:

This page has been updated and it is now showing a min notional of 0.002BTC for any order:
https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule

However, the API still reports 0.001. 
Which one is lying?

Igor Kroitor, [26.01.18 23:07]
From trial-and-error it seems that Trading Rule is the actual one, while the API reports old values?

Ninj0r, [27.01.18 01:54]
The API is the correct one

Igor Kroitor, [27.01.18 01:54]
Thank you for answering, as always!

Ninj0r, [27.01.18 01:54]
np
```

**Comment by kroitor** [comment]
The problem with that `cost` is that it is still in `'BTC'`, so you can't really handle it properly, unless you're recalculating their BTC prices continuously.

**Comment by darthf1** [comment]
Hm so what you are saying is that the Binance Team says the API (so the 0.001) is correct? Im 99,99% sure the 0.001 value is false, since I got a lot of errors.

See also these threads, there was quite a fuzz about it:
https://www.reddit.com/r/binance/comments/7o9hnb/binance_quietly_doubled_minimum_trade_from/
https://www.reddit.com/r/binance/comments/7obusc/total_must_be_at_least_0002/
https://www.reddit.com/r/binance/comments/7ovm96/limit_order_minimum_increased_to_0002/
https://www.reddit.com/r/binance/comments/7p538w/binance_changed_the_minimum_sell_value_to_0002_btc/
https://www.reddit.com/r/binance/comments/7o9gqh/how_long_min_order_total_is_0002_btc/

The first link shows a screenshot from the Binance page itselfs, where an error is shown because the order is below 0.002.

**Comment by darthf1** [comment]
> The problem with that min cost limit is that it is still in 'BTC', even when you trade a non-related pair, like BNB/USDT, for example... so, you can't really handle it properly, unless you're recalculating their BTC prices continuously.

I thought this min cost is defined per market? This is from their API docs:

> MIN_NOTIONAL
> 
> The MIN_NOTIONAL filter defines the minimum notional value allowed for an order on a symbol. An order's notional value is the price * quantity.
> 
> /exchangeInfo format:
> 
>   {
>     "filterType": "MIN_NOTIONAL",
>     "minNotional": "0.00100000"
>   }

https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#min_notional

**Comment by darthf1** [comment]
@kroitor A polite bump. I'm not sure if you get updates on this thread as you closed it yesterday.

**Comment by kroitor** [comment]
@darthf1 i'm getting all updates )

**Comment by kroitor** [comment]
```
Igor Kroitor, [27.01.18 15:59]
Hey, sorry for bothering, but it still looks like a contradiction: 
https://www.reddit.com/r/binance/comments/7o9hnb/binance_quietly_doubled_minimum_trade_from/
↑ it has a screenshot showing a web interface error saying 
min total is 0.002BTC... our users also reported the same... 
so it looks like the API isn't reporting the correct min total? 

Or is that info outdated already and the issue is tackled so 
that we should trust the API? Or, maybe, that screenshot is 
related to web only that has its own separate rules and 
you're not in charge of those?

Ninj0r, [27.01.18 16:00]
The API is correct

Ninj0r, [27.01.18 16:03]
He's looking at the static web page

Igor Kroitor, [27.01.18 16:04]
No, I mean the error message above it, is it static as well?

Igor Kroitor, [27.01.18 16:05]
This one:
```

<img width="341" alt="screen shot 2018-01-27 at 16 05 06" src="https://user-images.githubusercontent.com/1294454/35472811-457465bc-0387-11e8-9e32-5dbdabbaf6c3.png">

```
Ninj0r, [27.01.18 16:05]
The UI might be

Igor Kroitor, [27.01.18 16:06]
ok, I see, thx again for your time
```

**Comment by darthf1** [comment]
This is surely confusing. The quickest way to find out now would be to do a [test trade](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#test-new-order-trade), however this is not implemented yet in CCXT is it? I'm unable to quickly create a test trade from custom code. Maybe I can create a new order of 0.001 BTC to trigger the error, but a test trade would have my preference.

**Comment by kroitor** [comment]
> This is surely confusing. 

It is )

The quickest way to find out now would be to do a test trade, however this is not implemented yet in CCXT is it? 

It is ) We implement all endpoints, not all of them get to the unified API though, because, obviously, many of them are exchange-specific. So, the unified API is the core common to all exchanges, but we still support all of their endpoints out of the box.

To see all methods available with Binance you can do this:
```
var_dump (new \ccxt\binance ()); // PHP
```

The method you are looking for is:

```
$params = array (
    // order params as described here: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-order--trade
    'quantity': '54321,
    'price': 12345,
    // ...
);
$exchange->private_post_order_test ($params);
```

Explained here: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

Let me know if it doesn't help.

**Comment by kroitor** [comment]
@darthf1 you can copy the code from $binance->create_order and tweak it for using that test endpoint:

```
    public function create_test_order ($symbol, $type, $side, $amount, $price = null, $params = array ()) {
        $this->load_markets();
        $market = $this->market ($symbol);
        $order = array (
            'symbol' => $market['id'],
            'quantity' => $this->amount_to_string($symbol, $amount),
            'type' => strtoupper ($type),
            'side' => strtoupper ($side),
        );
        if ($type === 'limit') {
            $order = array_merge ($order, array (
                'price' => $this->price_to_precision($symbol, $price),
                'timeInForce' => 'GTC', // 'GTC' = Good To Cancel (default), 'IOC' = Immediate Or Cancel
            ));
        }
        $response = $this->privatePostOrderTest (array_merge ($order, $params));
        return $this->parse_order($response);
    }
```

**Comment by darthf1** [comment]
I'm trying.

`dump($binance->create_test_order('ETH/BTC', 'limit', 'buy', 1, 0.001));`

Results in

> In binance.php line 626:
> 
>   Notice: Undefined index: status

Investigating further..

**Comment by kroitor** [comment]
@darthf1 turn `$binance->verbose = true` to see it...

**Comment by darthf1** [comment]
To see the full request message?

```
Request:
Array
(
    [0] => GET
    [1] => https://api.binance.com/api/v1/exchangeInfo
    [2] => Array
        (
        )

    [3] =>
)

Request:
Array
(
    [0] => POST
    [1] => https://api.binance.com/api/v3/order/test
    [2] => Array
        (
            [0] => X-MBX-APIKEY: l4v8cQsyRDfV63gkYnAj5JMgSjKhKsgcE3AZLCfjx6CAjGM1fNH2g3E0MzmmmMO0
            [1] => Content-Type: application/x-www-form-urlencoded
        )

    [3] => timestamp=1517066616147&recvWindow=5000&symbol=ETHBTC&quantity=1.0&type=LIMIT&side=BUY&price=0.001000&timeInForce=GTC&signature=63ef000e49fd06eb50d241e65ed3df82dc2faf97c9a890a2c4a6f80d082031f6
)

In binance.php line 625:

  Notice: Undefined index: status
```

**Comment by kroitor** [comment]
@darthf1 can you please update to 1.10.871 and retry the same code once again? Should work now. Let me know if it doesn't. Thx!

**Comment by darthf1** [comment]
@kroitor  same error but now on the symbol;

```
$binance->create_test_order('ETH/BTC', 'limit', 'buy', 1, 0.001);

Request:
Array
(
    [0] => GET
    [1] => https://api.binance.com/api/v1/exchangeInfo
    [2] => Array
        (
        )

    [3] =>
)

Request:
Array
(
    [0] => POST
    [1] => https://api.binance.com/api/v3/order/test
    [2] => Array
        (
            [0] => X-MBX-APIKEY: APIKEY
            [1] => Content-Type: application/x-www-form-urlencoded
        )

    [3] => timestamp=1517068316509&recvWindow=5000&symbol=ETHBTC&quantity=1.0&type=LIMIT&side=BUY&price=0.001000&timeInForce=GTC&signature=fe07c3304fc7d6abb506debfdcb6b490c1f53e8a97142a8e532a05842a97ef0b
)

In binance.php line 613:

  Notice: Undefined index: symbol
```

**Comment by kroitor** [comment]
@darthf1 ok, then just delete the last line, the return an empty object upon success anyway:

```PHP
public function create_test_order ($symbol, $type, $side, $amount, $price = null, $params = array ()) {
        $this->load_markets();
        $market = $this->market ($symbol);
        $order = array (
            'symbol' => $market['id'],
            'quantity' => $this->amount_to_string($symbol, $amount),
            'type' => strtoupper ($type),
            'side' => strtoupper ($side),
        );
        if ($type === 'limit') {
            $order = array_merge ($order, array (
                'price' => $this->price_to_precision($symbol, $price),
                'timeInForce' => 'GTC', // 'GTC' = Good To Cancel (default), 'IOC' = Immediate Or Cancel
            ));
        }
        $response = $this->privatePostOrderTest (array_merge ($order, $params));
        return $response;
    }
```

This is tested and it works.

**Comment by darthf1** [comment]
Ok. Well then! The conclusion:

This is a success (I get no response): `$binance->create_test_order('ETH/BTC', 'limit', 'buy', 1, 0.001)`
This is not a success: `$binance->create_test_order('ETH/BTC', 'limit', 'buy', 1, 0.0001)`
The error response: `binance order cost = amount * price is too small {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}`

Which means the 0.001 is correct after all (via API).

Thanks @kroitor for helping me clearing this out.

**Comment by mkutny** [comment]
@darthf1 , if 0.001 is correct, how was that possible:

> I'm 99,99% sure the 0.001 value is false since I got a lot of errors in the beginning of January because of this. Both through the API and through the web interface.

**Comment by darthf1** [comment]
That is the question. I know for sure I got that error, but I didnt record any of it so i cant show you. And it is also all over the internet as well (see my posts earlier). Hell, it is even on their own support website.

**Comment by mkutny** [comment]
>  I'm unable to quickly create a test trade from custom code.

There is a command line shortcut for that:
>  $ node examples/js/cli.js binance privatePostOrderTest '{"symbol":"ETHBTC","quantity":"1","type":"LIMIT","side":"BUY","price":"0.001","timeInForce":"GTC"}'

**Comment by fvisconti** [comment]
> MIN_NOTIONAL is the minimal **cost** of the order.
> 
> * `cost = amount * price`
> * `cost !== amount`
> * cost should be greater than MIN_NOTIONAL
> * amount should be evenly divisible by their lot size
> 
> Their filters are described here: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#filters
> 
> ![binance-filters](https://user-images.githubusercontent.com/1294454/35457066-aaaef072-02e8-11e8-8c56-89f2697e6bd3.jpg)
> 
> If you're looking for minimal costs and minimal amounts, you should not be looking at exchange-specific params (red), instead you can take unified ccxt params (green), those should be standard for all exchanges, not just Binance.
> 
> The red `info` field contains their answer, unparsed, `as is`, and the rest of those fields contain the parsed unified data, which is exchange-agnostic.
> 
> Let us know if it doesn't answer your question.

I think I'm not getting it totally right.
According to [this](https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule), the Min Order Value (which should be MIN_NOTIONAL, isn't it?) is different for each coin: BTC is 0.001, ETH is 0.01, and so on.

So the _unified ccxt api _ min `cost` has to be mapped to each coin, right?

**Comment by kroitor** [comment]
@fvisconti 

This is explained here: https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

> (which should be MIN_NOTIONAL, isn't it?)

Yes, it should, however, that particular Trading Rule web page https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule is outdated

> So the _unified ccxt api _ min cost has to be mapped to each coin, right?

Almost right, but, to be precise, it should be mapped not to **each coin**, but to **each market** (aka each *symbol* or *trading pair*):

**Example**

```JavaScript
const ccxt = require ('./ccxt')
const exchange = new ccxt.binance({'enableRateLimit': true})
;(async () => {
    await exchange.loadMarkets ();
    for (let symbol of exchange.symbols) {
        market = exchange.market (symbol)
        console.log (symbol, 'min cost', market['limits']['cost']['min'])
    }
}) ()
```

**Output**

```
ADA/BNB min cost 1
ADA/BTC min cost 0.001
ADA/ETH min cost 0.01
ADA/USDT min cost 10
ADX/BNB min cost 1
ADX/BTC min cost 0.001
ADX/ETH min cost 0.01
AE/BNB min cost 1
AE/BTC min cost 0.001
AE/ETH min cost 0.01
AGI/BNB min cost 1
...
```

Let me know if the above does not answer your question.
