### ISSUE TITLE
exchange.markets['BTC/USDT']['limits']['leverage']['max'] returns None

### ISSUE THREAD

**Issue by MyStyleAlways** [ccxt/ccxt#15165]
I tried to check the MAX Leverage of Binance Future. But my code returns None. I have no idea why I can not see it. Is this bug or am I missing something? I tried 10 different symbols, but every output was None.  I have 200USDT in my Binance Future account.

- OS: Ubuntu 20.04.5 LTS
- Programming Language version: Python 3.9.6
- CCXT version: 1.94.16

```
exchange = ccxt.binance({"apiKey": key1, "secret": key2,\
                        'options': {'defaultType': 'future'},\
                        'enableRateLimit': True})

exchange.load_markets()

print(exchange.markets['BTC/USDT']['limits']['leverage']['max'])
```
output
```
None
```
If you know what's going on. Please help me :(

**Comment by carlosmiei** [comment]
Hello @MyStyleAlways, unfortunately not every exchange provides that information through the API
