### ISSUE TITLE
Bybit: Incorrect cost calculation. How to calculate cost properly

### ISSUE THREAD

**Issue by wa1one** [ccxt/ccxt#15168]
- OS: MacOS Monterey 12.6
- Programming Language version: node js 16
- CCXT version: 1.93.105

I'm always getting 0.1% slippage when making market BUY order (I request order within 5ms after getting quote). It's incorrect. I want to buy EXACT amount of crypto with MARKET order. I tried just `price * amount` formula as `cost` and round it to either 6 or 8 decimals. (incorrect precision?)
But slippage is really big. On other exchanges, I don't have this issue. 
I want to buy 0.001 BTC but I always get 0.000999 BTC.
I saw you were getting this issue with Huobi and you fixed it and changed precision of cost to base currency. Is this needed?

I am OK if it is everywhere but this is happening only on ByBit exchange.

Please suggest something.

I am using createOrder function of spot market.

**Comment by samgermain** [comment]
I'm thinking, but not certain, that some of the problem might be fixed by #14915 and then setting `exchange.number = decimal.Decimal`
