### ISSUE TITLE
CCXT Pro Websockets merged with CCXT!

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#15171]
Dear users of CCXT and CCXT Pro!

We are happy to announce the merge of CCXT Pro into CCXT.
CCXT Pro is now a part of the free CCXT package as of version 1.95+
All of the CCXT Pro Websocket functionality is retained in CCXT.
Please, make sure to upgrade your scripts accordingly.
You can find the examples here: 

- https://github.com/ccxt/ccxt/tree/master/examples/
- https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro

All feedback is very welcome and is especially valued during this period of transition.

A word to existing CCXT Pro users: please, ignore the subscription expiry notifications and switch to CCXT. Don't hesitate to reach out to us here on GitHub and in Discord (https://discord.gg/ccxt) in case you have any difficulties migrating or if you have any questions regarding the merge.

Thanks for using CCXT!

Yours faithfully,
The CCXT Dev Team.

**Comment by jshcrowthe** [comment]
First of all thanks to all on the hard work here! As a user, the added OSS functionality is much appreciated.

I noticed that the API surface has now changed. Whereas before the import scheme was:

```js
import * as ccxt from ccxt;

// Do CCXT things
```

Importing CCXT as originally documented the watch functionality is not available. Instead I have to import at the `pro` subpath:

<details>

<summary>ESM</summary>

```js
import { pro as ccxt } from ccxt;

// Do CCXT things
```

</details>

<details>

<summary>CommonJS</summary>

```js
const ccxt = require('ccxt').pro;

// Do CCXT things
```

</details>

Is the plan here to merge both API interfaces into one? Or is the "pro" entrypoint going to be an ongoing thing?

**Comment by frosty00** [comment]
@jshcrowthe we're going to add esm support soon #12619

**Comment by xiguakaoya** [comment]
thx!

**Comment by ambrosestartup** [comment]
Thank you!

**Comment by suenot** [comment]
Игорь, спасибо тебе!

**Comment by suenot** [comment]
Simple example: 
```
const ccxt = require ('ccxt').pro;

(async () => {

  const exchange = new ccxt.binance({ enableRateLimit: true })

  while (true) {
    const orderbook = await exchange.watchOrderBook('ETH/BTC')
    console.log (new Date (), orderbook['asks'][0], orderbook['bids'][0])
  }

}) ()
```

**Comment by pottertech** [comment]
I am on PHP 7.4 but the composer.json in the package says it requires PHP 8.1.  What requires 8.1 in the ccxt package?

**Comment by carlosmiei** [comment]
@pottertech React/Async
https://reactphp.org/async/

**Comment by pottertech** [comment]
@carlosmiei Thanks, I changed the required block in the ccxt/composer.json file to this:

    "require": {
        "php": ">=7.4.0",
        "ext-bcmath": "*",
        "ext-curl": "*",
        "ext-iconv": "*",
        "ext-pcre": "*",
        "ext-json": "*",
        "ext-openssl": "*",
        "ext-gmp": "*",
        "symfony/polyfill-mbstring": "^1.7",
        "pear/console_table": "1.3.1",
        "ratchet/pawl": ">=0.4.1",
        "react/http": ">=1.6.0",
        "react/async": "^3"
    },

then did command: composer update

And everything seems to be working fine now for PHP 7.4

**Comment by Kinzowa** [comment]
Hello, 
I changed ccxtpro to ccxt but it throws an error. How can I fix the issue ?

```
celery_worker-1  |   File "/app/trading/tasks.py", line 188, in main
celery_worker-1  |     await asyncio.gather(*loops)
celery_worker-1  |   File "/app/trading/tasks.py", line 139, in clients_loop
celery_worker-1  |     await asyncio.gather(method_loop(client, exid, wallet, method, private, args))
celery_worker-1  |   File "/app/trading/tasks.py", line 118, in method_loop
celery_worker-1  |     await client.close()
celery_worker-1  | AttributeError: 'ftx' object has no attribute 'close'
```

**Comment by pottertech** [comment]
After installing CCXT with the following command:  git clone https://github.com/ccxt/ccxt.git --depth 1 

I am ready to update CCXT but I am not sure what the command is to do it correctly.  Can someone help me out please?

**Comment by jorisw** [comment]
@pottertech Cloning a source repository is not the correct way to use most open source libraries. Rather, it involves importing the module into your project. How this is done depends on your choice of scripting language. See the [wiki install docs](https://github.com/ccxt/ccxt/wiki/Install).

**Comment by pottertech** [comment]
Thank you.

**Comment by simonblack** [comment]
Hey all, are requests to the websocket endpoints "real" event subscriptions (and connections kept open) or are they just single api requests? Wondering why *it seems* like the connections are closed right after a request / why requests have to be performed one at a time within a loop.

Lets use binance for this question, should you need an exchange in particular.

Thanks!

**Comment by carlosmiei** [comment]
> Hey all, are requests to the websocket endpoints "real" event subscriptions (and connections kept open) or are they just single api requests? Wondering why _it seems_ like the connections are closed right after a request / why requests have to be performed one at a time within a loop.
> 
> Lets use binance for this question, should you need an exchange in particular.
> 
> Thanks!

Hello @simonblack,
They are real event subscriptions and the connection is kept open. Now, depending from exchange to exchange, we might establish different connections if they require to.

**Comment by simonblack** [comment]
> > Hey all, are requests to the websocket endpoints "real" event subscriptions (and connections kept open) or are they just single api requests? Wondering why _it seems_ like the connections are closed right after a request / why requests have to be performed one at a time within a loop.
> > Lets use binance for this question, should you need an exchange in particular.
> > Thanks!
> 
> Hello @simonblack, They are real event subscriptions and the connection is kept open. Now, depending from exchange to exchange, we might establish different connections if they require to.

Thanks a lot!

**Comment by HawtDogFlvrWtr** [comment]
Where's the best place to donate?

**Comment by bugb** [comment]
@kroitor  Thank you so much for make it free for everyone, much appreciated!

**Comment by muhammad-rizwan-brainx** [comment]
Do all the exchanges in ccxt support WSS?

**Comment by carlosmiei** [comment]
> Do all the exchanges in ccxt support WSS?

@muhammad-rizwan-brainx Not all of them but a significant part do, you can check it here https://github.com/ccxt/ccxt#supported-cryptocurrency-exchange-markets

**Comment by muhammad-rizwan-brainx** [comment]
Can I transfer funds from one exchange to another with CCXT?
@carlosmiei

**Comment by carlosmiei** [comment]
> Can I transfer funds from one exchange to another with CCXT? @carlosmiei

@muhammad-rizwan-brainx Yes, by using the `withdraw` method.

**Comment by muhammad-rizwan-brainx** [comment]
fetchDepositAddress would be used to get the address of account ? I am trying it with kraken exchange but it's not working
@carlosmiei

**Comment by Arsam1313** [comment]
I've been encountering this error with BingX since yesterday! Could you please help me with this? "file "/usr/local/lib/python3.9/dist-packages/ccxt/async_support/bingx.py", line 2967, in handle_errors code = self.safe_currency_code(currencyId, currency) ccxt.base.errors.ExchangeError: bingx {"code":80020,"msg":"risk forbidden","data":{}}"

**Comment by carlosmiei** [comment]
@Arsam1313 Can you please open a different issue?

**Comment by celernetworkcoloros** [comment]
https://github.com/ccxt/ccxt/issues/20886
Resolved:✴️

**Comment by mariocasila** [comment]
Hey, cctx pro is free version?

**Comment by dohikazuki888-dev** [comment]
Hello, I want to use your ccxt pro.
How can I use this?
Please Guide!

**Comment by kroitor** [comment]
@dohikazuki888-dev we highly recommend reading the Manuals from top to bottom and checking the examples, it will save your time:
- https://github.com/ccxt/ccxt/wiki/Install
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual
- https://github.com/ccxt/ccxt/tree/master/examples
- https://github.com/ccxt/ccxt/wiki/FAQ

**Comment by miguelmoreira91** [comment]
where is the direct link to buy ccxt pro? all pages bring me up here...

**Comment by kroitor** [comment]
> where is the direct link to buy ccxt pro? all pages bring me up here...

The [opening post](https://github.com/ccxt/ccxt/issues/15171#issue-1393949926) of this issue says that you don't have to buy CCXT Pro, cause it's free now.
