### ISSUE TITLE
I just cannot install new ccxt version

### ISSUE THREAD

**Issue by janeCMD** [ccxt/ccxt#15183]
Sorry to create request, but while installing new version of ccxt, i hit into myriad of problems which i am not able to overcome.

I copied and unzipped ccxt into directory. When including it in php, following error appears:

```
Fatal error: Class 'React\Promise\Deferred' not found in /var/www/ccxt-2022/ccxt-master/php/pro/Future.php on line 8
```
I installed React\Promise\Deferred using composer (according to manuals), but error doesnt disappear and i failed to google anything which could lead me to solution or cause of the issue.

I tried alternative solution by installing CCXT using pip (in case that method would automatically install dependencies), but i hit into following error when typing 'pip3 install ccxt':

```
No matching distribution found for setuptools>=60.9.0 (from ccxt)
```
Can you somebody point me to manual which will help me overcome some of these issues, so i can make it work ?

**Comment by carlosmiei** [comment]
Hello @janeCMD, regarding the PHP issue, just run `composer update` inside the folder and try again.

Regarding the pip error, I'll take a look

**Comment by janeCMD** [comment]
@carlosmiei Thank you for advice. 

With bit of hacking, i was able to make it work. composer.json contained some constraints, which i am not able to satisfy easily (php8+). So i just rewrote those constraints to php 7.0 and it does work luckily.

**Comment by ttodua** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/15194
