### ISSUE TITLE
Bittrex: add fields to result of createOrder

### ISSUE THREAD

**Issue by LeonLegion** [ccxt/ccxt#1518]
Can you add field **symbol**, **type**, **side** and **status** to response of [createOrder](https://github.com/ccxt/ccxt/blob/master/js/bittrex.js#L420)?
somthing like this
```
        let result = {
            'info': response,
            'id': response['result'][orderIdField],
            'symbol': symbol,
            'type': type,
            'side': side,
            'status': 'open',
        };
```

**Comment by kroitor** [comment]
We actually think of returning the entire order (the fields you listed + other order properties as well) from createOrder and cancelOrder. This is still a work in progress. Some exchanges already do that, like HitBTC, for example (you can see that in hitbtc2.js), others are still lacking that, like Bittrex. Your contributions on this would be appreciated! I hope to get to this aspect of Bittrex asap. Let me know if I answered your question. Thx!

**Comment by LeonLegion** [comment]
Can i make patch for it in bittrex.js? 
and create pull request?

**Comment by kroitor** [comment]
@LeonLegion sure, as long as it does not introduce a breaking change or a backward-incompatible change, why not )

**Comment by LeonLegion** [comment]
#1528
