### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'React\Promise\Deferred' 

### ISSUE THREAD

**Issue by pottertech** [ccxt/ccxt#15184]
Am I missing something? After updating to 1.95.7 my code can not find one of the React classes. I did install React using composer.  Here is a snippet of the composer.json file:
{
        "react/http": "^1.8",
        "react/socket": "^1.12",
        "react/promise": "^2.9",
        "recoil/recoil": "^1.0"

- OS: Ubuntu 20.4
- Programming Language version: PHP
- CCXT version: 1.95.7

``` Code:
require_once __DIR__ . '/ccxt/ccxt.php';
```

``` Error:
PHP Fatal error:  Uncaught Error: Class 'React\Promise\Deferred' not found in /root/ccxt/php/pro/Future.php:8
Stack trace:
#0 /root/ccxt/ccxt.php(128): require_once()
#1 /root/rpc_TNR_Indicators.php(13): require_once('/root/ccxt/ccxt...')
#2 {main}
  thrown in /root/ccxt/php/pro/Future.php on line 8
```

**Comment by carlosmiei** [comment]
Hello @pottertech can you try to run `composer update` ?

**Comment by pottertech** [comment]
I found another comment that states that we have to run composer install inside the ccxt directory before it will work with React.
