### ISSUE TITLE
Binance Cross Margin Account Borrow Limits per Security : Download via CCXT

### ISSUE THREAD

**Issue by ALIANS-PRODUCTIONS** [ccxt/ccxt#15182]
Is it possible to retrieve the borrow limits in Cross Margin account (Binance) using CCXT?

I need to get the last column on the screen shot below :borrow limit per asset, applicable to users account

![cross margin limits](https://user-images.githubusercontent.com/21268921/193798212-22f01553-9a91-427e-bcca-b862ad631d54.png)

**Comment by Dan-krm** [comment]
@ALIANS-PRODUCTIONS You can use the implicit api with a few different endpoints to fetch the borrow limit information:
### CCXT Implicit API:
https://docs.ccxt.com/en/latest/manual.html#implicit-api

### All Assets Borrow Limit:
```
node examples/js/cli binance sapiGetMarginMaxBorrowable '{"asset":"AAVE"}'
```
https://binance-docs.github.io/apidocs/spot/en/#query-max-borrow-user_data

### Cross Borrow Limit:
```
node examples/js/cli binance sapiGetMarginCrossMarginData '{"coin":"AAVE"}'
```
https://binance-docs.github.io/apidocs/spot/en/#query-cross-margin-fee-data-user_data

### Isolated Borrow Limit:
```
node examples/js/cli binance sapiGetMarginIsolatedMarginData '{"symbol":"AAVEUSDT"}'
```
https://binance-docs.github.io/apidocs/spot/en/#query-isolated-margin-fee-data-user_data

**Comment by ALIANS-PRODUCTIONS** [comment]
Thats perfect thank you Dan!
