### ISSUE TITLE
How to get all public orders from exchange?

### ISSUE THREAD

**Issue by mironsv** [ccxt/ccxt#15196]
Hi CCXT team,

- OS: Ubuntu 22.04
- Programming Language version: Python 3.9
- CCXT version: 1.95.7

code from example [](https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/watch-custom-exchange-specific-streams.py)
```
    market = exchange.market('BTC/USDT')
    message_hash = market['lowercaseId'] + '@miniTicker'
    while True:
        try:
            print(await exchange.watch_public(message_hash))
```
Error:
```
AttributeError 'MyBinance' object has no attribute 'watch_public'
```

Task: watch all public orders or trades from exchange. I mean "all users", overall. For example Binance API websocket @trade provides a stream of trades with order ids (ask + bid).
CCXT problem: I'm able to watch only my orders: exchange.watch_orders(symbol).
Question: how to watch all public orders from exchange? exchange.watch_public(message_hash) doesn't work for me.

**Comment by samgermain** [comment]
There's `watchOrderBook` and [`fetchOrderBook`](https://docs.ccxt.com/en/latest/manual.html?#order-book)

**Comment by mironsv** [comment]
> There's `watchOrderBook` and [`fetchOrderBook`](https://docs.ccxt.com/en/latest/manual.html?#order-book)

Thank you @samgermain !
Method fetchOrderBook returns order-book-structure: https://docs.ccxt.com/en/latest/manual.html?#order-book-structure
The structure has fields: symbol, price, amount. It hasn't fields: order_id, status, etc. Therefore I can't reach my goal.

Let me describe the goal. My bot trades for **many** clients. Bot needs to watch if any of client's order was filled (executed).
1. I can use websocket watch_orders(symbol). I think the idea to create websocket for each user is incorrect as I need too many websockets simultaneously (I mean too many resources).
2. I need something common with detailed orders (id, status, price, qty). For example in Binance there is a websocket (stream @trade) that provides filled orders. In the dictionary my bot can find client's filled order by id and perform an action.

**Comment by samgermain** [comment]
> > There's `watchOrderBook` and [`fetchOrderBook`](https://docs.ccxt.com/en/latest/manual.html?#order-book)
> 
> Thank you @samgermain ! Method fetchOrderBook returns order-book-structure: https://docs.ccxt.com/en/latest/manual.html?#order-book-structure The structure has fields: symbol, price, amount. It hasn't fields: order_id, status, etc. Therefore I can't reach my goal.
> 
> Let me describe the goal. My bot trades for **many** clients. Bot needs to watch if any of client's order was **filled** (executed).
> 
>     1. I can use websocket watch_orders(symbol). But I think the idea to create websocket for each user is incorrect as I need too many websockets simultaneously (I mean too many resources) and number of connections per user ID: ≤ 50 ([Kucoin](https://docs.kucoin.com/#request-rate-limit)).
> 
>     2. I need something common with detailed orders (id, status, price, qty). For example in Binance there is a websocket (stream @trade) that provides filled orders. In the dictionary my bot can find client's filled order by id and perform an action.

So are you able to perform what you want to do on Binance, but your not able to perform it on Kucoin?

**Comment by mironsv** [comment]
Yes, I can get a websocket with public orders on Binance, but I can't find the same on Kucoin.

**Comment by mironsv** [comment]
https://docs.kucoin.com/#match-execution-data - websocket with public trades on Kucoin
I use Kucoin SDK directly because I couldn't find appropriate websocket in ccxt.
