### ISSUE TITLE
Bittrex: add minimal cost of order

### ISSUE THREAD

**Issue by LeonLegion** [ccxt/ccxt#1519]
Now Bittrex can return error like **DUST_TRADE_DISALLOWED_MIN_VALUE_50K_SAT**
May be need add minimal cost of order to [fetchMarkets](https://github.com/ccxt/ccxt/blob/master/js/bittrex.js#L150)?

Somthing like this
```
result.push (this.extend (this.fees['trading'], {
                'id': id,
                'symbol': symbol,
                'base': base,
                'quote': quote,
                'baseId': baseId,
                'quoteId': quoteId,
                'active': active,
                'info': market,
                'lot': Math.pow (10, -precision['amount']),
                'precision': precision,
                'limits': {
                    'amount': {
                        'min': market['MinTradeSize'],
                        'max': undefined,
                    },
                    'price': {
                        'min': undefined,
                        'max': undefined,
                    },
                    //new lines start
                    'cost': {
                        'min': 0.005,
                        'max': undefined,
                    }
                    //end
                },
```

**Comment by kroitor** [comment]
The problem with hardcoding is that they had DUST_TRADE_DISALLOWED_MIN_VALUE_**100K**_SAT two months ago... If there was some page or API endpoint to get that info from Bittrex, that would make it possible to scrape those numbers, but we refrain from hardcoding (while still capturing and detecting the exception properly).

Do you think hardcoding those values for Bittrex is something we should do? Maybe we should push on Bittrex a little for them to add it to their API somehow?

**Comment by LeonLegion** [comment]
Ok. 
I think the same way.
It is not big problem.

**Comment by kroitor** [comment]
Yep, you see, the other problem with 50K SAT is that with `DASH/ETH` pair, the minimal trade is still 50k sat of `BTC` (!). So, that is a dynamic limit that depends on the price of `BTC` with Bittrex. So, if we put `0.005` there, it would be false for some pairs, if we don't designate the limit currency, right? Therefore we better leave it up to the user to decide. Would you mind if I close this for now?

**Comment by kroitor** [comment]
Related: #1516 (Binance)
