### ISSUE TITLE
WebSocket connection to ‘wss://stream.data.alpaca.markets/v1beta2/crypto’ failed:

### ISSUE THREAD

**Issue by chatofking** [ccxt/ccxt#15195]
- OS:
- Programming Language version:
- CCXT version:
windows
javascript
1.94.2

---------

# CODE

```
const url = "wss://stream.data.alpaca.markets/v1beta2/crypto";

const socket = new WebSocket(url);

console.log(socket);
```

# OUTPUT
```
WebSocket connection to 'wss://stream.data.alpaca.markets/v1beta2/crypto' failed: Error during WebSocket handshake: Unexpected response code: 403

**Comment by samgermain** [comment]
Websocket implementation has not been written in CCXT for Alpaca yet

**Comment by chatofking** [comment]
i just follow this video and I got  [{"T":"success","msg":"connected"}] before
after while I got above error.
https://youtu.be/6U6NhKAbO5Y
https://github.com/hackingthemarkets/gridbot-websockets
