### ISSUE TITLE
Class 'React\Promise\Deferred' not found in ccxt/php/pro/Future.php:8

### ISSUE THREAD

**Issue by koala974** [ccxt/ccxt#15194]
- OS: windows
- Programming Language version:  PHP
- CCXT version: the latest

```
Trying to connect to exchange
```

```
Fatal error: Uncaught Error: Class 'React\Promise\Deferred' not found in ccxt/php/pro/Future.php:8 Stack trace: #0 ccxt/ccxt.php(128): require_once()
{main} thrown in ccxt/php/pro/Future.php on line 8
```

**Comment by samgermain** [comment]
have you run `composer install`?

**Comment by koala974** [comment]
> composer install

composer ? no i use a synology NAS with php 7.4.
Its worked well before last update :(

**Comment by samgermain** [comment]
> > composer install
> 
> composer ? no i use a synology NAS with php 7.4. Its worked well before last update :(

I'm not an expert in PHP, but I believe that I fixed this issue just by installing the dependencies

**Comment by koala974** [comment]
> > > composer install
> > 
> > 
> > composer ? no i use a synology NAS with php 7.4. Its worked well before last update :(
> 
> I'm not an expert in PHP, but I believe that I fixed this issue just by installing the dependencies

i dont know what is composer lol just checking in was not include on synology NAS.
All my code worked well before the last update, so i think it will be possible to continue without composer ?!

**Comment by carlosmiei** [comment]
@koala974 `composer` is just a dependency manager, and since we have external dependencies to other libraries (React PHP), I don't think you can skip it, but it should be very easy to install. 

Assuming you're running a Unix-based OS in your NAS, you can follow these steps: https://getcomposer.org/doc/00-intro.md#installation-linux-unix-macos

**Comment by ttodua** [comment]
I am not sure how ccxt can be used (even older versions) without composer & dependencies, but anyway, if you managed to make it work, good.
(I suppose the break is related to the merge of CCXT PRO into REST, and maybe you wanted only REST).
I will take a look into this to avoid any unexpected breaks.

**Comment by koala974** [comment]
Thank you very much.Yes i think it was due to the fusion with ccxt pro tooLe 22 oct. 2022 11:23, "T. Todua" ***@***.***> a écrit :
I am not sure how ccxt can be used (even older versions) without composer & dependencies, but anyway, if you managed to make it work, good.
(I suppose the break is related to the merge of CCXT PRO into REST, and maybe you wanted only REST).
I will take a look into this to avoid any unexpected breaks.

**Comment by ttodua** [comment]
Yes, the pre-merge version https://github.com/ccxt/ccxt/releases/tag/1.94.15 might be what you want, however, it will be unsupported and will become outdated as time goes.

**Comment by cyiwin** [comment]
I had the exact same error. Windows 10, xampp, PHP 8.1.5.  Composer was the fix for me.
