### ISSUE TITLE
on createOrder, bybit returns the order cost instead of the amount bought

### ISSUE THREAD

**Issue by danieltorscho** [ccxt/ccxt#15208]
I have a fully functional binance exchange. While trying to implement additional "bybit" exchange, I've noticed some differences.
Once the order has been placed with the `createOrder` function for 100$, it returns two different versions of results for both exchanges:
binance: `order.amount: 0.004988`  (this is correct: 100 / 20048.11)
bybit: `order.amount: 99.96056748` (here it returns an actual cost instead of the bought amount of crypto)

Order: SPOT

I believe it should be unified into the same output, without such difference or do I missing something ?

- OS: Win 10 x64
- Programming Language version: Javascript
- CCXT version: 1.95.16

```
const order = await exchange.createOrder('BTCUSDT', 'market', 'buy', 0.004988, 100).catch(e => e.message)
```

```
The output for binance:

binance: order.amount: 0.004988
bybit: order.amount: 99.96056748 (here it returns an actual cost instead of the bought amount of crypto)

```

**Comment by sc0Vu** [comment]
Hi @danieltorscho

May I ask which pair did you create order (spot/inverse/linear/option)?

**Comment by danieltorscho** [comment]
I fixed it with some temp fix like rewriting the values:
```
orderPending = await exchange.fetchOrder(orderPending.id, config.SYMBOL)
if (config.EXCHANGE_ID === 'bybit') {
  orderPending.cost = orderPending.amount
  orderPending.amount = orderPending.cost / price
  orderPending.price = price
}
```

**Comment by sc0Vu** [comment]
Hi @danieltorscho 

You're right, the amount, filled and cost should be present as base currency (https://github.com/ccxt/ccxt/wiki/Manual#order-structure), it seems to be quote currency in bybit spot trade.

We'll fix this asap.

**Comment by danieltorscho** [comment]
> And cost should be 'filled' * 'price' (filling price used where available).

thanks for pointing this out, now it's like so:

```
if (config.EXCHANGE_ID === 'bybit') {
  order.cost = order.filled * price
  order.amount = order.cost / price
  order.price = price
}
```
