### ISSUE TITLE
ccxtpro how to set up proxies?

### ISSUE THREAD

**Issue by zhubiaogg** [ccxt/ccxt#15202]
- OS: win 10
- Programming Language version: python 3.9
- CCXT version: 1.95.11

**code**
`import ccxt.pro as ccxtpro
import ccxt
from asyncio import run
print('CCXT Version:', ccxt.__version__)
async def main():
    exchange = ccxtpro.binance({
        'options': {
            'defaultType': 'future',  # spot, margin, future, delivery
        },
    })
    exchange.proxies = {
        "http": "127.0.0.1:7890",
        "https": "127.0.0.1:7890"
    }
    symbol = 'BTC/USDT'
    while True:
        try:
            orderbook = await exchange.watch_order_book(symbol)
            print(exchange.iso8601(exchange.milliseconds()), exchange.id, symbol, 'ask:', orderbook['asks'][0], 'bid:', orderbook['bids'][0])
        except Exception as e:
            print(type(e).__name__, str(e))
            break
    await exchange.close()

run(main())`

![image](https://user-images.githubusercontent.com/43566543/194277514-dc87bc75-3180-4c2d-9d15-ab3def0f9236.png)

![image](https://user-images.githubusercontent.com/43566543/194278857-21113617-c8e2-436f-9f4e-e23a0eba18d4.png)

I have to use vpn, and  I try  set up exchange.proxies = {
"http": "127.0.0.1:7890",
"https": "127.0.0.1:7890"
},  But it doesn't seem to be working

**Comment by carlosmiei** [comment]
Hello @zhubiaogg, currently it's not possible to send the `ws_proxy` as an option to the exchange (it's a work in progress) but you can always do this:

1: Set these environment variables:
```
HTTP_PROXY="http://127.0.0.1:1086"
HTTPS_PROXY="https://127.0.0.1:1086"
WS_PROXY= url here
WSS_PROXY= url here
```

2: instantiate the exchange with these options:
import ccxt.pro as ccxt

```
exchange = ccxt.binance({
   # your options ..
   aiohttp_trust_env = True
})
```

**Comment by KevinBaudin** [comment]
Since we can only define a SINGLE proxy address in env variables, that means that we cannot use multiple proxies, am I right?

Is it something you plan to add in the future?

**Comment by carlosmiei** [comment]
> Since we can only define a SINGLE proxy address in env variables, that means that we cannot use multiple proxies, am I right?
> 
> Is it something you plan to add in the future?

@KevinBaudin Instead of providing proxies using `environment variables` you can use an option, for example:

```Python
exchange = ccxt.binance({
   # your options ..
   aiohttp_proxy = 'proxy.com'
})
# change it
exchange.aiohttp_proxy = 'newproxy.com'
```

**Comment by anyongjin** [comment]
I'd like to use `watch_trades` and `load_markets` in ccxt pro.
**If none of `environment variables` or `aiohttp_proxy` is set, both `watch_trades` and `load_markets` would fail with `RequestTimeout`**  
**If `aiohttp_proxy` is set and left `environment variables` as empty, `load_markets` is ok but `watch_trades` would fail with `RequestTimeout`:**  
```text
File "E:\trade\banbot\banbot\main\live_trader.py", line 47, in _init_pairs
    trades = await self.exg_pro.watch_trades(pair)
  File "D:\Softs\Miniconda3\envs\p10\lib\site-packages\ccxt\pro\binance.py", line 395, in watch_trades
    trades = await self.watch(url, messageHash, self.extend(request, query), messageHash, subscribe)
ccxt.base.errors.RequestTimeout: Connection timeout
```
**if  `environment variables`  is set and left `aiohttp_proxy` as default, both `watch_trades` and `load_markets` works well**  

So, is it possible to add support for `watch_*` methods with  `aiohttp_proxy` in ccxt pro? 
Thanks for your excellent work!
@carlosmiei
