### ISSUE TITLE
[okx] erc20 network indexed as coin name

### ISSUE THREAD

**Issue by krychla1** [ccxt/ccxt#15204]
Dear fellows.
Problematic part okx -> fetchCurrencies -> networks part.
All the coin networks are indexed by their corresponding network name, but the erc20 network, which is indexed by the coin name.
![image](https://user-images.githubusercontent.com/33096727/194293131-3b5d9195-b4ff-43b9-a79f-3cda794ab53e.png)

The root cause is, that erc20 tokens are marked as mainnet, thus following code kicks in.

```Javascript
const mainNet = this.safeValue (chain, 'mainNet', false);
...
if (mainNet && !(chainPart in layerTwo)) {
    // BTC lighting and liquid are both mainnet but not the same as BTC-Bitcoin
    network = code;
}
... 
networks[network] = {
                        'id': networkId,
                        'network': network,
                        'active': active,
```

- OS: linux
- Programming Language version: nodejs
- CCXT version: 1.95.12

Please take a look.
Thanks!

**Comment by ttodua** [comment]
@krychla1 thanks for the report! I'll take a look and will try to submit fix soon.
