### ISSUE TITLE
FTX.US maker/taker fees not right

### ISSUE THREAD

**Issue by evan-coygo** [ccxt/ccxt#15219]
- OS: ubuntu
- Programming Language version: node 14.19.3
- CCXT version: 1.95.7

FTX.US trading fees aren't correct. They're pulling from the ftx.js base class with has maker/taker as 0.2/0.7 but FTX.US has 0.1/0.2, see docs https://help.ftx.us/hc/en-us/articles/360043579273-Fees

**Comment by frosty00** [comment]
#15228

**Comment by frosty00** [comment]
y r u reopening this

**Comment by samgermain** [comment]
> y r u reopening this

The `ftxus` fees are still wrong https://github.com/ccxt/ccxt/pull/15228#issuecomment-1272287643
