### ISSUE TITLE
MBX_WEIGHT_1M header parameter, know your 1min limits 

### ISSUE THREAD

**Issue by ngdekhai** [ccxt/ccxt#15212]
Hi, I am using ccxt version 1.81.14 in php. I just talk to Binance customer support and find out that I can know whenever I am going to hit the hard-limits like 1200 weight per 1min. There is a parameter in header, MBX_WEIGHT_1M, from Binance api's response. 

So my question is, how can we get the header parameter response from ccxt? 

btw i am using this list of functions:
for future, i am using $exchange->market, $exchange->fapiPrivate_post_leverage, $exchange->fetchTicker, and $exchange->create_order()

for spot, i am just using $exchange->create_market_buy_order

**Comment by carlosmiei** [comment]
Hello @ngdekhai, You can activate the `last_response_headers` option to access that information, example:

```Python
exchange = ccxt.bybit({
    # 'apiKey': 'YOUR_API_KEY',
    # 'secret': 'YOUR_SECRET_KEY',
    'last_response_headers': True,
})

markets = await exchange.load_markets()

order = await exchange.create_order()
## Get headers from the last call
headers = exchange.last_response_headers
print(headers)
```

**Comment by ngdekhai** [comment]
Hi @carlosmiei , thanks for you previous help, I got the x-mbx-used-weight data. 

But I face another problem in Binance spot trade order; I am just using a simple market order (PHP), $exchange->create_market_buy_order($symbol, $amount,null);. The order is success, but the x-mbx-used-weight is 11 weight per order. Which is weird, because if it is just create new trade, it suppose to be only 1 weight (https://binance-docs.github.io/apidocs/spot/en/#new-order-trade)

Do you know what make it 11 weight?

**Comment by ngdekhai** [comment]
@carlosmiei thanks for the help
