### ISSUE TITLE
FTX CCXT cancel SL / TP after position closes

### ISSUE THREAD

**Issue by ProStrike-hub** [ccxt/ccxt#15214]
- Programming Language version: PHP 8.2
- CCXT version: latest

Hello, I already have the code to send orders to FTX (with TP and SL).

But since TP and SL are not 'attached' to the position and the positions are aggregated it makes a mess with orders.

I have seen people suggest cancelling all orders before opening a new one: https://stackoverflow.com/a/69371405/6014804 Which is a nice idea but unusable in my case.

I regularly have several current positions at the same time.

So I can't cancel all pending orders as soon as I open a new position. Because some orders are still active and relevant.

The only option I guess is to fetch closed orders/positions (when a TP / SL is hit) to individually cancel the remaining order to this position (the opposite order, either TP / SL). Right?

Even if it's the right solution, I don't know how to do that. Has anyone ever experienced that? Thanks in advance.

**Comment by carlosmiei** [comment]
Hello @ProStrike-hub, assuming that you're keeping the order ids and using Rest only, you could do something like this:
- place tp order
- place sl order 
- start a polling mechanism to detect when one or another order is closed
- after detecting, cancel the remaining

Very rough example:

```Python

tp_order = await exchange.create_order(...)
sl_order = await.exchange.create_order(...)

    while True:
        if tp_status == 'open' and sl_status == 'closed':
            # cancel tp order
            cancel_tp_order = await exchange.cancel_order(tp_order['id'])
            break
        
        if sl_status == 'open' and tp_status == 'closed':
            # cancel sl order
            cancel_sl_order = await exchange.cancel_order(sl_order['id'])
            break
       asyncio.sleep(5) # sleep 5 seconds before trying again
```

Alternatively, you could use WS (they're free now) to detect in real-time which order was filled and immediately close the other.

**Comment by ProStrike-hub** [comment]
> Hello @ProStrike-hub, assuming that you're keeping the order ids and using Rest only, you could do something like this:
> 
> * place tp order
> * place sl order
> * start a polling mechanism to detect when one or another order is closed
> * after detecting, cancel the remaining
> 
> Very rough example:
> 
> ```python
> tp_order = await exchange.create_order(...)
> sl_order = await exchange.create_order(...)
> 
>     while True:
>         if tp_status == 'open' and sl_status == 'closed':
>             # cancel tp order
>             cancel_tp_order = await exchange.cancel_order(tp_order['id'])
>             break
>         
>         if sl_status == 'open' and tp_status == 'closed':
>             # cancel sl order
>             cancel_sl_order = await exchange.cancel_order(sl_order['id'])
>             break
>        asyncio.sleep(5) # sleep 5 seconds before trying again
> ```
> 
> Alternatively, you could use WS (they're free now) to detect in real-time which order was filled and immediately close the other.

Thank you very much @carlosmiei !

Although that's Python, I guess, and I'm using PHP (I don't know anything about Python)...
Do you have an equivalent snippet of code for PHP?

"start a polling mechanism to detect when one or another order is closed" what's this polling mechanism you're talking about? Do you have examples please?

You're speaking about WS. What's the acronym/service behind? 

Thank you very much in advance!

**Comment by ProStrike-hub** [comment]
Hello @carlosmiei !

Could you please clarify what you were talking about with the "polling mechanism" and what's "WS"?

I would be very grateful! Have a nice day.

**Comment by ProStrike-hub** [comment]
Hello, 

Sorry to tag you @samgermain @pcriadoperez @sc0Vu @frosty00 @Dan-krm @ttodua but @carlosmiei seems to be inactive... 

Could one of you provide more info, or examples if possible, about this "polling mechanism" and "WS" Carlos was talking about please?

> start a polling mechanism to detect when one or another order is closed

> alternatively, you could use WS (they're free now) to detect in real-time which order was filled and immediately close the other

The idea is to detect when a TP/SL is hit/filled on FTX and to cancel its opposite order.
- Programming Language version: PHP 8.2
- CCXT version: latest

Thanks!

**Comment by carlosmiei** [comment]
Hello @ProStrike-hub 

sorry for the delay, the "polling mechanism" might be as simple as the while True in the snippet above, it's just something that periodically checks the order state.

WS refers to websockets, that allows for real-time updates if you have an open connection, so instead of you asking the server constantly,  the server would notify you when an update occurs, you can check plenty WS examples here:
 https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro/py

More info about WebSockets: https://www.fullstackpython.com/websockets.html

**Comment by ProStrike-hub** [comment]
Thank you @carlosmiei ! 

Okay I understood what you meant about "polling mechanism" now. 

I'm interested in the WS, though I see several features for multiple exchanges but not FTX... 
When looking at the "many-exchanges" I only see WS about 'orderbooks' and 'streams'.

Could you please specify which one will allow real-time updates on my current trades at FTX please?

**Comment by ttodua** [comment]
@ProStrike-hub here, under `has` key, you can see which exchange supports which `watch` method: https://github.com/ccxt/ccxt/blob/master/js/pro/ftx.js#L14 
 about trades/orders, you will need to use  `watchMyTrades` or also `watchOrders` for similar purpose.
let us know if it makes thing clear for you, and feel free to re-open the issue.

**Comment by ProStrike-hub** [comment]
> @ProStrike-hub here, under `has` key, you can see which exchange supports which `watch` method: https://github.com/ccxt/ccxt/blob/master/js/pro/ftx.js#L14 about trades/orders, you will need to use `watchMyTrades` or also `watchOrders` for similar purpose. let us know if it makes thing clear for you, and feel free to re-open the issue.

Thanks @ttodua 
I'm using PHP and not JS so I checked this file instead: https://github.com/ccxt/ccxt/blob/master/php/pro/ftx.php

Okay I need to use `watchMyTrades` and/or `watchOrders`, understood. 
But I have no clue of what to do next. Your colleague @carlosmiei kindly recommended: 
> Alternatively, you could use WS (they're free now) to detect in real-time which order was filled and immediately close the other.

But at that time I didn't even knew WS = WebSockets. I've never used any kind of WS, yet. 
So I have no idea what the code Carlos describes in his solution would look like... 

Could you please provide examples of how you use `watchMyTrades` and/or `watchOrders` (in PHP) to "detect in real-time which order was filled and immediately close the other"?

**Comment by ttodua** [comment]
@ProStrike-hub please check https://github.com/ccxt/ccxt/tree/master/examples `ccxt.pro->php` page for examples.

**Comment by ProStrike-hub** [comment]
> @ProStrike-hub please check https://github.com/ccxt/ccxt/tree/master/examples `ccxt.pro->php` page for examples.

@ttodua I already did. 
There's only 3 examples out there; watch balance, ticker and orderbook. 

Nothing to detect in real-time which order was filled. As @carlosmiei puts it: 
> Alternatively, you could use WS (they're free now) to detect in real-time which order was filled and immediately close the other.

Trust me, I've already checked the whole documentation. This is not covered, anywhere. 
Therefore could you please provide an example please?

**Comment by carlosmiei** [comment]
@ProStrike-hub we will try to come up with some basic watch orders examples in PHP

**Comment by ProStrike-hub** [comment]
> > ```python
> > tp_order = await exchange.create_order(...)
> > sl_order = await exchange.create_order(...)
> > 
> >     while True:
> >         if tp_status == 'open' and sl_status == 'closed':
> >             # cancel tp order
> >             cancel_tp_order = await exchange.cancel_order(tp_order['id'])
> >             break
> >         
> >         if sl_status == 'open' and tp_status == 'closed':
> >             # cancel sl order
> >             cancel_sl_order = await exchange.cancel_order(sl_order['id'])
> >             break
> >        asyncio.sleep(5) # sleep 5 seconds before trying again
> > ```

Hello @carlosmiei, 

I've just translated, in php, and implemented this code. 
But to check `'tp_status'` and `'sl_status'` I use `fetch_order('id')`. 
Though, this doesn't return Trigger Orders / Conditional Orders. 

I checked solutions here and all I could find is using `fetch_open_orders(symbol, since=None, limit=None, {'method':'privateGetConditionalOrders'})` which returns all Trigger Orders / Conditional Orders... I cannot set and ('id') to only return the one I'm interested in...

Any solution please?

**Comment by ttodua** [comment]
@ProStrike-hub I'll reply you shortly.

**Comment by ttodua** [comment]
After checking codes inside ccxt, I see that getting conditional orders using `fetchOrder` it's not implemented yet. We will implement it and post here an update.

**Comment by ProStrike-hub** [comment]
Thanks @ttodua any idea on the update schedule? 
Cause I'm looking for a turnaround meanwhile. Should I just wait for your update shortly?

**Comment by ttodua** [comment]
I've checked FTX api and it seems the only way to get the open trigger(conditional) orders is the way you already mentioned.
 however, instead of `{'method':'privateGetConditionalOrders'}` you should provide an unified parameter `{'trigger': true}`, , so ccxt will know that you are referring to `trigger` (a.k.a. `conditional`) order/s.

**Comment by ProStrike-hub** [comment]
@ttodua Thanks but this doesn't do the work. 

First of all, that's going to return all conditional open orders. While I only want to get one by specifying its ID. 
At first, I was using `fetch_order` which has an `'id'` parameter, but this function does not return conditional orders apparently, true?

So then I used `fetch_orders` which returns all orders... I only want to retrieve one based on its id. 
_Using `fetch_open_orders` isn't a great idea actually since some of the conditional orders I want to retrieve have `status: closed`. Which I need._ 

Looking at issues in the Git Repo I found several people encountering the same issue. But none of their solutions appeared to work from what I tested: 
- https://github.com/ccxt/ccxt/issues/6669#issuecomment-603765137
- https://github.com/ccxt/ccxt/issues/7178#issuecomment-650330403 

Do you have any **solution** in mind **which will retrieve only one conditional order based on its id**, please?

**Comment by ttodua** [comment]
I forgot to mention, you should wait to this PR https://github.com/ccxt/ccxt/pull/15375 to get merged, after that you will be able to user `trigger: true`. atm, you can use `stop:true` (but this is deprecated param and will work just for a while).

**Comment by ttodua** [comment]
about getting many orders , as I said, FTX doesn't seem to have an endpoint to get single conditional order, so you have to use `fetch_open_orders` and inside that, locate your target order based on its `id`.

**Comment by ttodua** [comment]
if order is not in `open_orders` then it means that trigger order was closed. alternatively, you can just use `fetch_orders` instead of `fetch_open_orders`, and there will be `closed` ones too.
