### ISSUE TITLE
Bitget module missing endpoint

### ISSUE THREAD

**Issue by domb16** [ccxt/ccxt#15216]
Bitget module has `fetchOpenOrders` and `fetchOrder`, but this only allows symbol based search, the Bitget API itself has another endpoint:

**"GET /api/mix/v1/order/marginCoinCurrent"** - this endpoint would get all of the open orders symbol independent but based on instrument type (UCMBL, DCMBL) which is required for other endpoints anyway.

"privateMixGetOrderMarginCoinCurrent" implicit call cannot be found in the Bitget module

**Comment by carlosmiei** [comment]
Hey @domb16 thanks for letting us know, will be adding this endpoint to the implicit API shortly

**Comment by carlosmiei** [comment]
@domb16 it should be working now

Example:
```Python
response = await bitget.privateMixGetOrderMarginCoinCurrent({"productType":"umcbl"})
```

**Comment by domb16** [comment]
Appreciate the quick turnaround feel free to close the issue!
