### ISSUE TITLE
Newlly added Binance Option market

### ISSUE THREAD

**Issue by GabinTB** [ccxt/ccxt#15221]
Hello, 

First of all thank you for your work and the merge of CCXTPRO in CCXT, great to use!

Just an issue to know how to retreive newlly added Binance Options from Binance (future?) CCXT instance?
Is it available? If not, will it be (as a separate exchange or part of Binance Futures?)?

Thank you in advance

- OS: Linux
- Programming Language version: Python 3.8
- CCXT version: 1.95.5 
- CCXTPRO version: same as CCXT?

**Comment by samgermain** [comment]
> Hello,
> 
> First of all thank you for your work and the merge of CCXTPRO in CCXT, great to use!
> 
> Just an issue to know how to retreive newlly added Binance Options from Binance (future?) CCXT instance? Is it available? If not, will it be (as a separate exchange or part of Binance Futures?)?
> 
> Thank you in advance
> 
>     * OS: Linux
> 
>     * Programming Language version: Python 3.8
> 
>     * CCXT version: 1.95.5
> 
>     * CCXTPRO version: same as CCXT?

For the most part, you can only trade options by using [implicit API](https://docs.ccxt.com/en/latest/manual.html#implicit-api) methods that start with `vapiPublic` and `vapiPrivate`, but we do plan to add support for options to the binance class in the future

**Comment by samgermain** [comment]
Feel free to reopen this PR if you have any more questions
