### ISSUE TITLE
FTX parses position leverage error

### ISSUE THREAD

**Issue by CEX68** [ccxt/ccxt#15223]
- OS: Linux
- Programming Language version: Python
- CCXT version: [1.95.22](https://github.com/ccxt/ccxt/releases/tag/1.95.22)

Code that raises error
```python
import ccxt
ftx = ccxt.ftx(
    'apiKey': '',
    'secret': '',
    'precisionMode': ccxt.TICK_SIZE,
)
ftx.fetch_positions()
```

Position returned by FTX. I haven't gotten such kind position before, maybe added by FTX recently.
```python
{'future': 'BTC-PERP', 'size': '0.0', 'side': 'buy', 'netSize': '0.0', 'longOrderSize': '-0.0', 'shortOrderSize': '0.0', 'cost': '0.0', 'entryPrice': None, 'unrealizedPnl': '0.0', 'realizedPnl': '-1', 'initialMarginRequirement': '0.0', 'maintenanceMarginRequirement': '0.03', 'openSize': '0.0', 'collateralUsed': '0.0', 'estimatedLiquidationPrice': '3200', 'recentAverageOpenPrice': None, 'recentPnl': None, 'recentBreakEvenPrice': None, 'cumulativeBuySize': None, 'cumulativeSellSize': None}
```

will result error in [ftx parse_position()](https://github.com/ccxt/ccxt/blob/master/python/ccxt/ftx.py#L2279)
```
initialMarginPercentage = self.safe_string(position, 'initialMarginRequirement')
leverage = int(Precise.string_div('1', initialMarginPercentage, 0))
```

My fix
```python
initialMarginPercentage = self.safe_string(position, 'initialMarginRequirement')
leverage = Precise.string_div('1', initialMarginPercentage, 0)
if leverage:
    leverage = int(leverage)
```

**Comment by MrE-r** [comment]
I got the same error too.

**Comment by Looma1116** [comment]
> I got the same error too.

in ccxt ftx.py -> parse_position

original]
leverage = int(Precise.string_div('1', initialMarginPercentage, 0))

fix]
leverage = Precise.string_div('1', initialMarginPercentage, 0)
if leverage:
leverage = int(leverage)

**Comment by SpaceMonkeyForever** [comment]
@Looma1116 can we merge this please?
