### ISSUE TITLE
Can't execute createMarketOrder due to "insufficient balance" error

### ISSUE THREAD

**Issue by AmirPooresv2** [ccxt/ccxt#15220]
I executed the following code in kucoin sandbox and got this weird error:

command : `exchange.createMarketOrder('BTC/USDT', 'SELL',  0.1)`

`error : InsufficientFunds: kucoin Balance insufficient!`

I got this error while my testnet balance status is as: 

```
[{'id': '63407cfc2b968a0001e25313',
  'type': 'main',
  'currency': 'BTC',
  'info': {'id': '63407cfc2b968a0001e25313',
   'currency': 'BTC',
   'type': 'main',
   'balance': '5',
   'available': '5',
   'holds': '0'}},
 {'id': '63407cfc2b968a0001e25315',
  'type': 'main',
  'currency': 'USDT',
  'info': {'id': '63407cfc2b968a0001e25315',
   'currency': 'USDT',
   'type': 'main',
   'balance': '50000',
   'available': '50000',
   'holds': '0'}}
```
   
 what would be the issue?
thanks in advance

**Comment by carlosmiei** [comment]
Hello @AmirPooresv2 I think you have all your money inside the `main` account, you have to transfer it to `trade` account to place orders
![image](https://user-images.githubusercontent.com/43336371/194714899-87917827-f6cc-4ef0-888c-2cf1db46c7bc.png)

**Comment by AmirPooresv2** [comment]
thanks @carlosmiei 
it works :)
