### ISSUE TITLE
hasFetchOHLCV result different from exchange.has for multiple exchanges

### ISSUE THREAD

**Issue by justinxjx** [ccxt/ccxt#1522]
- OS: Windows 10
- Programming Language version: Python 3.6.4
- CCXT version: 1.10.854
- Exchange: bittrex, gdax, maybe others
- Method: hasFetchOHLCV
```
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> bittrex = getattr(ccxt, 'bittrex')({'verbose': True})
>>> bittrex.hasFetchOHLCV
False
>>> bittrex.has.get('fetchOHLCV')
True
>>> gdax = getattr(ccxt, 'gdax')({'verbose': True})
>>> gdax.hasFetchOHLCV
False
>>> gdax.has.get('fetchOHLCV')
True```

**Comment by kroitor** [comment]
The `hasFetchOHLCV` is now deprecated (as well as other properties alike). The new metainfo interface is contained within `.has = { }` dictionary. Let us know if you find some exchanges with incorrect values in their `.has = { }` property. We will update them appropriately. Hope it answers your question.

**Comment by justinxjx** [comment]
Yes. That answers the question. I apologize if I missed seeing that deprecation somewhere.
