### ISSUE TITLE
backtest and optimization usage not found in document

### ISSUE THREAD

**Issue by vnxz** [ccxt/ccxt#15236]
anyone know this package include backtesting? optimization?
I not found in documentation/

**Comment by cryptoCCY** [comment]
This is a low level library used to connect to exchanges.
If you are looking for turnkey bot automation you might be looking for something more along the following lines:

https://github.com/freqtrade
https://github.com/hummingbot/hummingbot

**Comment by samgermain** [comment]
> This is a low level library used to connect to exchanges. If you are looking for turnkey bot automation you might be looking for something more along the following lines:
> 
> https://github.com/freqtrade https://github.com/hummingbot/hummingbot

I second this, CCXT is mainly a library that's meant to send requests to the exchanges and then get information back. If you want to optimize it, I believe the javascript code is the fastest version. Maybe you could clarify what exactly you mean by backtesting and optimization? I don't think CCXT will have it though, I would recommend freqtrade
