### ISSUE TITLE
PHP create_market_buy_order function have 11 weight request?

### ISSUE THREAD

**Issue by ngdekhai** [ccxt/ccxt#15235]
Hi, I am using ccxt version 1.81.14 in php. A simple market order, $exchange->create_market_buy_order($symbol, $amount,null), make a 11 weight request per order. The order is success, but the x-mbx-used-weight is 11 weight per order. Which is weird, because if it is just create new trade, it suppose to be only 1 weight (https://binance-docs.github.io/apidocs/spot/en/#new-order-trade)

Do you know what make it 11 weight? Does other language also make the same problem?

**Comment by sc0Vu** [comment]
Hey @ngdekhai 

Is that value from exchange? 

<img width="616" alt="image" src="https://user-images.githubusercontent.com/10494397/194821623-0dc61bfa-d3ff-4baf-b63f-6ceb1783ca1b.png">

**Comment by ngdekhai** [comment]
@sc0Vu yes it is the value from ccxt function last_response_headers,

"header":{"Content-Type":"application\/json;charset=UTF-8","Content-Length":"297","Connection":"keep-alive","Date":"Fri, 07 Oct 2022 17:00:24 GMT","Server":"nginx","x-mbx-used-weight":"11","x-mbx-used-weight-1m":"11","x-mbx-order-count-10s":"1","x-mbx-order-count-1d":"2"..............

**Comment by ngdekhai** [comment]
the reason for 11 weight, is because of exchangeInfo (10 weight), and order (1 weight).

is it possible to remove exchangeInfo api?

**Comment by sc0Vu** [comment]
@ngdekhai 

Oh, we call exchangeInfo when `loadMaarkets`. I think we only call it once if you use the same exchange instance (only the first order would be 11 weight).

**Comment by ngdekhai** [comment]
@sc0Vu 

okay, I understand but because I have a lot of users (different account) need to create market order, thats why multiple instance. My expectation is 1 apikey = 1 instance, so is there a way to create a single instance with multiple apikey to trigger multiple accounts creating orders?
