### ISSUE TITLE
Bybit tickers values changes for inverse perpetual, usdt linear, inverse futures "GET /v2/public/tickers"

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#15239]
Hi, we receive from Bybit message that there will be some changes made for inverse perpetual, usdt linear, inverse futures tickers data.

Here is the full message:

> Dear traders,
> On 2022-10-12 UTC+8, the values of 6 fields under "GET /v2/public/tickers" on mainnet will no longer be used and we will assign them to be empty string or 0.
> Changes have been made on testnet, you can refer to the response messages on testnet.
> For examples: https://api-testnet.bybit.com/v2/public/tickers?symbol=BTCUSDT
> Here are the 6 fields to be adjusted:
> countdown_hour: 0
> predicted_funding_rate: ""
> price_1h_pcnt: ""
> open_value: ""
> total_turnover: ""
> total_volume: 0

Also they send `json` data for single BTCUSDT ticker as example:

```
{
  "ret_code": 0,
  "ret_msg": "OK",
  "result": [
    {
      "symbol": "BTCUSDT",
      "bid_price": "19535",
      "ask_price": "19535.5",
      "last_price": "19535.50",
      "last_tick_direction": "ZeroPlusTick",
      "prev_price_24h": "19920.50",
      "price_24h_pcnt": "-0.019326",
      "high_price_24h": "20244.00",
      "low_price_24h": "19050.00",
      "prev_price_1h": "19499.50",
      "mark_price": "19535.50",
      "index_price": "19517.17",
      "open_interest": 57970.206,
      "countdown_hour": 0,
      "turnover_24h": "689669956.8264993",
      "volume_24h": 35206.90199999,
      "funding_rate": "0.0001",
      "predicted_funding_rate": "",
      "next_funding_time": "2022-10-08T08:00:00Z",
      "predicted_delivery_price": "",
      "total_turnover": "",
      "total_volume": 0,
      "delivery_fee_rate": "",
      "delivery_time": "",
      "price_1h_pcnt": "",
      "open_value": ""
    }
  ],
  "ext_code": "",
  "ext_info": "",
  "time_now": "1665213957.873116"
}
```

We write about this to avoid some issues on ccxt side.

**Comment by carlosmiei** [comment]
Hello @wunderb1t, we are aware of this change and will update our method accordingly, thanks for reporting it!

**Comment by samgermain** [comment]
> Hello @wunderb1t, we are aware of this change and will update our method accordingly, thanks for reporting it!

bybit's `parseTicker` method doesn't read any of those fields, so no changes are required
