### ISSUE TITLE
[okx] 'number': String problem

### ISSUE THREAD

**Issue by krychla1** [ccxt/ccxt#15238]
Dear fellows,
I am with you for very long time and for nearly same amount of time I struggle with rounding/precision for numbers in your framework. I try 'number': String property, but it costs me even more headaches again and again. What is your progress with the precision problems? Is the number to string usable, or still kind do on your risk?

To the actual problem of okx, currencies.precision is for majority of currencies in exponential form (which can't be handled by your own functions such as "decimalToPrecision").

e.g.:
1) set options to 'number': String
2) load markets
3) check exchange.currencies["LON"].precision

actual: "1e-4"
expected: "0.0001"

Please check.
Thanks!

**Comment by sc0Vu** [comment]
Hi @krychla1 

IMHO, the precision should be number, some language did parse number to scientific notation, which program language did you use?

```
export interface Currency {
        id: string;
        code: string;
        numericId?: number;
        precision: number;
}
```

**Comment by krychla1** [comment]
Hi @sc0Vu,
Nodejs. I am not sure how the 'number': String setting works with the code you posted.

**Comment by krychla1** [comment]
How is this completed?

**Comment by ttodua** [comment]
as mentioned, this topic will be close as "duplicate" in favor of this https://github.com/ccxt/ccxt/issues/16167

**Comment by samgermain** [comment]
> as mentioned, this topic will be close as "duplicate" in favor of this #16167

this focuses on the specific okx issue, so I think we should leave it open as it can be solved more simply, while the other issue focuses on the entire precise/string math issue

**Comment by krychla1** [comment]
Any updates here?

**Comment by samgermain** [comment]
> Any updates here?

Can you share an [MRE](https://stackoverflow.com/help/minimal-reproducible-example) so I can more easily reproduce the problem?

**Comment by krychla1** [comment]
set options to 'number': String
load markets
check exchange.currencies["LON"].precision
actual: "1e-4"
expected: "0.0001"

**Comment by samgermain** [comment]
> set options to 'number': String load markets check exchange.currencies["LON"].precision actual: "1e-4" expected: "0.0001"

share an MRE please, I don't have the same problem you do

```js
const ccxt = require ('/Users/sam/Documents/dev/CCXT/ccxt');

async function main () {

    const exchange = new ccxt.okx ();
    exchange.number = String;

    const markets = await exchange.loadMarkets ();
    const currency = exchange.currencies["LON"].precision
    console.log (currency)
};

main ();
```

outputs
```js
0.000001
```

**Comment by krychla1** [comment]
Has it been fixed? I haven't tried since I reported as there was no info. 
I will try and confirm with you after. Thanks for now!

**Comment by krychla1** [comment]
Hi @samgermain 
Your MRE works for me without issues as well, however the problem is still there. You need to enhance the code with credentials:
```Javascript
const ccxt = require('ccxt').pro;

async function main () {

    // option 1
    const exchange = new ccxt.okx ({
        'apiKey': ...,
        'secret': ...,
        'password': ...,
        'number': String,
        
    });
    const markets = await exchange.loadMarkets ();
    const currency = exchange.currencies["LON"].precision
    console.log (currency)
}

main ();
```
Outputs:
```
1e-8
```
Now I see the reason to use MRE even for such a primitive scenarios :)

**Comment by samgermain** [comment]
@kroitor @carlosmiei @frosty00 

So it looks like with `fetchCurrencies` (authenticated) in okx, we use parsePrecision, which returns a string as `1e-8`

![](https://i.imgur.com/T1iIk0X.png)

and then we use `parseNumber`, which casts the string to a string, and so it returns `1e-8` again

![](https://i.imgur.com/K854dUR.png)

Is this the expected behaviour? The user is expecting a response that looks like `'0.000001'`

**Comment by krychla1** [comment]
@samgermain 
exponential form of number as string is not feasible as it throws exceptions in functions like "decimalToPrecision", etc.
