### ISSUE TITLE
Signed load_markets results into -1100 error at binance and binance us

### ISSUE THREAD

**Issue by timschuiling** [ccxt/ccxt#15233]

**Comment by carlosmiei** [comment]
Hey @timschuiling , whichlocation are you using to access binanceus?

**Comment by ttodua** [comment]
You might check api keys, to ensure they dont include whitespace in the end/start, like [this user said](https://github.com/ccxt/ccxt/issues/14651#issuecomment-1287433465).
Let us know any replies, whether you have not yet fixed the issue.
