### ISSUE TITLE
How to get all deposit addresses for USDT for Gate exchange?

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#15232]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10
- Programming Language version: Node JS (Version 18.0.0)
- CCXT version: 1.95.27

```
'use strict';
const ccxt = require ('ccxt');

(async function () {
    let gate = new ccxt.gate ({
        apiKey: 'My_Api_Key',
        secret: 'My_Secret_Key',
    })
    await gate.loadMarkets()
    console.log(await gate.fetchDepositAddress('USDT'))
}) ();
```

```
D:\nodejs\CCXT_Wallet>node GateIO.js
(node:16856) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
{
  info: {
    currency: 'USDT',
    address: '1CvW4…...',
    multichain_addresses: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  code: 'USDT',
  currency: 'USDT',
  address: '1CvW4…...',
  tag: undefined,
  network: undefined
}

```
Hello:
I want to use CCXT JavaScript to get all deposit addresses in my Gate exchange account.
The following is my code:

'use strict';
const ccxt = require ('ccxt');

(async function () {
    let gate = new ccxt.gate ({
        apiKey: 'My_Api_Key',
        secret: 'My_Secret_Key',
    })
    await gate.loadMarkets()
    console.log(await gate.fetchDepositAddress('USDT'))
}) ();
When I run the script, I got the following output:
D:\nodejs\CCXT_Wallet>node GateIO.js
(node:16856) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
{
  info: {
    currency: 'USDT',
    address: '1CvW4…...',
    multichain_addresses: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  code: 'USDT',
  currency: 'USDT',
  address: '1CvW4…...',
  tag: undefined,
  network: undefined
}

D:\nodejs\CCXT_Wallet>npm list ccxt
CCXT_Wallet@ D:\nodejs\CCXT_Wallet
`-- ccxt@1.95.27

But when I login to my account in GateIO exchange, I can see that I have 14 different deposit addresses on different networks, even count the distinct deposit addresses, there are 8 distinct deposit addresses.  But from the ccxt JavaScript output, I can see only 2 deposit addresses, or only one distinct deposit addresses.  Yet, there are still 15 [Object] in the output, let me know how I can show all my deposit addresses with JavaScript.
Please advise,
Thanks,

**Comment by sc0Vu** [comment]
Hi @zydjohnHotmail 

I think you can simply loop the `result.info.multichain_addresses`.

**Comment by zydjohnHotmail** [comment]
Hello:
As I am newbie with CCXT, can you please share some code on how to loop the 
result.info.multichain_addresses?
Thanks,
