### ISSUE TITLE
Digifinex - fetch_my_trades and fetch_ledger return empty array.

### ISSUE THREAD

**Issue by nandorcsupor** [ccxt/ccxt#15242]
- OS: Linux
- Programming Language version: Python
- CCXT version: 1.95.33

exchange = ccxt.digifinex({
    "api_key": "",
    "secret": "",
})

print(exchange.fetch_my_trades())

print(exchange.fetch_ledger())

Both functions return an empty array whereas they used to work in previous ccxt versions. (Pretty sure at least fetch_my_trades used to work correctly in the middle of September)

**Comment by ttodua** [comment]
I've tested myself with latest ccxt version, and everything works fine (including fetchMyTrades and fetchLedger).
Please re-test and consider reading https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
feel free post a further comment if you think there is still an issue in ccxt

**Comment by nandorcsupor** [comment]
@ttodua Thanks for checking it, but I think there is still an issue. I confirmed that my API key is active by calling fetch_deposits, which seems to work like it used to. I also tried getting a new key from the website but I get the same results. Still both "fetch_ledger" and "fetch_my_trade" return an empty array, even though I have made several trades and when I first implemented this exchange I even saved the response in a json, so there was definitely a response from these functions a couple weeks ago. Any recommendations are welcome.


fetch Request: digifinex GET https://openapi.digifinex.com/v3/spot/mytrades RequestHeaders: {'ACCESS-KEY': '<access-key>', 'ACCESS-SIGN': '<access-sign>', 'ACCESS-TIMESTAMP': '1665570930', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: digifinex GET https://openapi.digifinex.com/v3/spot/mytrades 200 ResponseHeaders: {'Date': 'Wed, 12 Oct 2022 10:35:31 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'Expires': 'Wed, 12 Oct 2022 10:35:30 GMT', 'Cache-Control': 'no-cache', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS', 'Access-Control-Allow-Headers': 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type', 'Content-Encoding': 'gzip', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '758f306e2b0968bf-BUD'} ResponseBody: {"list":[],"code":0}
[]

**Comment by ttodua** [comment]
@carlosmiei do you have any ideas?

**Comment by ttodua** [comment]
@nandorcsupor as you say that it worked in September, then please check any version from September builds. i.e.
https://github.com/ccxt/ccxt/archive/d94d3c1247346abaa25dbb025ecbc0f297b1e16a.zip  (1st september, or you can choose any state hash number from [here ](https://github.com/ccxt/ccxt/commits/master?after=b91e0b06dfe067b2ccd7fed6413a7e0298e78f26+1154&branch=master&qualified_name=refs%2Fheads%2Fmaster))
