### ISSUE TITLE
Could not find query cross margin fee data.

### ISSUE THREAD

**Issue by newbienoobnoob** [ccxt/ccxt#15245]
- OS: win 10
- Programming Language version: python3 3.10
- CCXT version: 1.93.88

binance documentation - GET /sapi/v1/margin/crossMarginData (HMAC SHA256)
https://www.binance.com/en/margin-fee

I am looking for this data in ccxt. Isn't it implemented in ccxt?

**Comment by carlosmiei** [comment]
Hello @newbienoobnoob 

You can do it using the implicit API:

Example:

```Python

    exchange = ccxt.binance({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET_KEY',
    })

    params = {
        'coin':'BTC' # optional param
    }
    response = await exchange.sapiGetMarginCrossMarginData(params)
    ```

**Comment by newbienoobnoob** [comment]
thanks bro!
