### ISSUE TITLE
Supporting Binance stop loss and stop limit loss?

### ISSUE THREAD

**Issue by mmahalwy** [ccxt/ccxt#1524]
Just got hit trying a `binance.createLimitSellOrder` that's under the current price. Sold my coins at a big loss while trying the API :(

I guess there is no way to do stop-loss order without passing it as params?

**Comment by kroitor** [comment]
We currently unify `market` and `limit` orders, and for other order types you need to consult these docs:

- https://github.com/ccxt/ccxt/wiki/Manual#custom-order-params
- https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-order--trade

Let us know if this doesn't answer your question. Thx!
