### ISSUE TITLE
Computational performance in Node.js too slow

### ISSUE THREAD

**Issue by BongSuCHOI** [ccxt/ccxt#15258]
hello. I'm making a cryptobot with Node.js.

I've created a trading signal logic at the moment, and my tests have found that the calculation speed is too slow.
Is there any way to improve that issue?

I did a lot of searching but couldn't find a solution in Node.js.

But as far as I know, Python does a good job in this area.
In addition, I know that Python and Node are interoperable.

Then, in my opinion, can I now receive the OHLCV information of the exchange from the node and separate the logic for calculating the index into Python + WebSocket, and then receive the signal value returned by Python from the Node and place an order?

If my thinking is correct, can you explain a little more specific way?

If you have a solution, please help!

- OS: window10
- Programming Language version: node 16.x
- CCXT version: 1.95.35

current code (Don't worry about hoisting. Write in sequence for easy viewing)
```node
const executeTrade = async (json) => {
	await exchange.loadMarkets();

	const position = await exchange.fetchPositions([TICKER]);
	const ticker = await exchange.fetchTicker(TICKER);
	const usdtBalance = await getBalances();
	const currentLeverage = position[0].leverage;
	const curruntPrice = ticker.last;

	// test
	od_type = 'MARKET';
	od_side = 'buy';
	od_price = undefined;
	od_amount_rate = 0.1;
	od_amount = (usdtBalance * od_amount_rate) / (curruntPrice / currentLeverage);
	od_sl_rate = 0.005;
	od_ts_rate = 5;
	od_ts_trigger = 80;
	// od_leverage = json.leverage ? json.leverage : 10;
	od_leverage = 5;
	limitAverageDown = 2;
	averageDownRate = 0.003;

	if (currentLeverage !== od_leverage) {
		// setLeverage(json.leverage);
		setLeverage(od_leverage);
	}

	monitoring();
};
```
```node
const monitoring = async () => {
	while (true) {
                // A function containing await exchange.fetchOHLCV()
		const {cmo, vo, rvi} = Indicators()
		let isEffectiveCMO; /*.cmo..*/
		let isEffectiveVO; /*..vo..*/
		let isEffectiveRVI; /*..rvi..*/

		if (isEffectiveCMO && isEffectiveVO && isEffectiveRVI) {
			openPosition();
			break;
		}
	}
};
```
```node
const openPosition = async () => {
	lastTradeDirection = od_side;
	await exchange.createOrder(TICKER, od_type, od_side, od_amount, od_price);
	await liveTicker();
};
```
```node
const liveTicker = async () => {
	const position = await exchange.fetchPositions([TICKER]);
	const averagePrice = Number(position[0].info.entry_price);
	const ts_triggerPrice = averagePrice + od_ts_trigger;
	const sl_TriggerPrice = averagePrice - Math.round(averagePrice * od_sl_rate);
	const averageDownPrice = averagePrice - Math.round(averagePrice * averageDownRate);

	while (true) {
		let tickerDetails = await exchange.fetchTicker(TICKER);

		// average down
		if (tickerDetails.last <= averageDownPrice && averageDownCount < limitAverageDown) {
			averageDown();
			break;
		}

		// stop loss
		if (tickerDetails.last <= sl_TriggerPrice && averageDownCount == limitAverageDown) {
			closePosition(position);
			break;
		}

		// trigger stop
		if (tickerDetails.last >= ts_triggerPrice) {
			trailingStop();
			break;
		}
	}
};
```

**Comment by pcriadoperez** [comment]
Hi @BongSuCHOI , 

So Node.js is actually faster than python, as node.js is a compiled language while python is interpreted. However the difference in performance is really minimal and don't think this is your issue. To reduce complexity I would recommend sticking to the language you feel more comfortable in.

The slowest part in your code will be the calls to the server much more than the calculations. Here Websockets can definitely help and they are available through ccxt in javascript, php and python. I would to try that first.

I'll close this issue for now, but feel free to re-open or ask more questions if they come up.

**Comment by BongSuCHOI** [comment]
@pcriadoperez 
> The slowest part in your code will be the calls to the server


The answer was late.
thank you! I think I found the keyword of performance improvement refactoring after hearing your answer.

Looking closely at my code, asynchronous functions such as the fetchOHLCV() function were being called multiple times.

If the problem still occurs after improving the performance, I will open the problem again, thank you!
