### ISSUE TITLE
mexc3 withdraw function has bug

### ISSUE THREAD

**Issue by hosseinab** [ccxt/ccxt#15251]
OS: Windows 11
Programming Language version: PYTHON 3.10.5
CCXT version: "ccxt/ccxt": "^1.95.37",
Exchange: mexc3
Method: withdraw

hello
in mexc document for withdraw chain writed this text (https://mxcdevelop.github.io/apidocs/spot_v2_en/#withdraw):
withdraw  USDT to TRX must set this parameter to  **"TRC20"**...

in mexc3 class writed networks :
```
'networks': {
                    'TRX': 'TRC-20',
                    'TRC20': 'TRC-20',
                    'ETH': 'ERC-20',
                    'ERC20': 'ERC-20',
                    'BEP20': 'BEP20(BSC)',
                    'BSC': 'BEP20(BSC)',
                },
```
and run withdraw function for usdt :
in verbose input :
```
RequestBody: {"currency":"USDT","address":"TM6GGF3PsTDsZEgjKF6w4VXse7BEB2HLwt","amount":52.8486,"chain":"TRC-20"}

```
verbose output :
```
ResponseBody: {"code":10232,"msg":"Coin is not exist"}
```

must networks array change to :
```
'networks': {
                    'TRX': 'TRC20',
                    'TRC20': 'TRC20',
                    'ETH': 'ERC20',
                    'ERC20': 'ERC20',
                    'BEP20': 'BEP20(BSC)',
                    'BSC': 'BEP20(BSC)',
                },
```

**Comment by samgermain** [comment]
@hosseinab Thanks, do you know how to create a PR? If you know what the fix is, a PR would be a lot easier. If you need some help creating a PR, you can message me on discord (samweow#8804) or email me (sam.germain@usask.ca)

**Comment by hosseinab** [comment]
@samgermain thank you . I will send a message to you

**Comment by hosseinab** [comment]
@samgermain please set this networks for mexc3 class .
