### ISSUE TITLE
Do you have any information to verify the ID of the referral account?

### ISSUE THREAD

**Issue by big100** [ccxt/ccxt#15262]
Below is an example. You can get the information below from bybit.
Is there any way to get below information from ccxt?
No matter how much I search, I can't find it, so I'm asking.

Inviter ID (the UID of the account which invited this account to the platform)

![image](https://user-images.githubusercontent.com/37491415/195397591-2cc08743-3d1f-43ca-8ee7-1e4b0c1634ce.png)

**Comment by carlosmiei** [comment]
Hello @big100,
Yes you can call it using the implicit API.

Example:
```Python
bybit = ccxt.bybit({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET_KEY',
})

response = await bybit.privateGetV2PrivateAccountApiKey()
print(response)

```

**Comment by big100** [comment]
> Hello @big100, Yes you can call it using the implicit API.
> 
> Example:
> 
> ```python
> bybit = ccxt.bybit({
>     'apiKey': 'YOUR_API_KEY',
>     'secret': 'YOUR_SECRET_KEY',
> })
> 
> response = await bybit.privateGetV2PrivateAccountApiKey()
> print(response)
> ```

Thank you very much.
I thought about it a lot, but thanks to you, it was solved.

**Comment by big100** [comment]
@carlosmiei 
Thank you very much.
I thought about it a lot, but thanks to you, it was solved.
