### ISSUE TITLE
Unable to get account balance at exchange Bigone - Access denied!

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#15264]
- OS: Windows 10 (Version 21H2)
- Programming Language version: Node (version 18.10.0)
- CCXT version:  1.95.40

Hello:
I want to use CCXT JavaScript to get balance from my account with exchange Bigone.
The following is my node JS code:

```JavaScript
const ccxt = require ('ccxt');

(async function () {
    let bigone = new ccxt.bigone ({
        apiKey: 'My_Api_Key',
        secret: 'My_Secret_Key',
    })
    console.log(await bigone.fetchBalance())
}) ();
```

When I run the script, I got the following output:

```
D:\nodejs\CCXT_Wallet>node bigoneBalance.js
(node:34548) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\Exchange.js:753
            throw new ErrorClass (this.id + ' ' + method + ' ' + url + ' ' + codeAsString + ' ' + reason + ' ' + body);
                  ^

ExchangeNotAvailable: bigone GET https://big.one/api/v3/asset_pairs 403 Forbidden <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>

You don't have permission to access "http&#58;&#47;&#47;big&#46;one&#47;api&#47;v3&#47;asset&#95;pairs" on this server.<P>
Reference&#32;&#35;18&#46;8f251102&#46;1665600941&#46;214b20d2
</BODY>
</HTML>

    at bigone.handleHttpStatusCode (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\Exchange.js:753:19)
    at D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\Exchange.js:600:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async bigone.fetch2 (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\Exchange.js:1803:16)
    at async bigone.request (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\Exchange.js:1807:16)
    at async bigone.fetchMarkets (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\bigone.js:180:26)
    at async bigone.loadMarketsHelper (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\Exchange.js:626:25)
    at async bigone.loadMarkets (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\bigone.js:273:25)
    at async bigone.fetchBalance (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\bigone.js:766:9) {
  constructor: [class ExchangeNotAvailable extends NetworkError]
}
```

When I login to my account, I can see that I have passed KYC verification, and my API_Key and Secret_Key are correct, and I have enough access right to all API functions.
Let me know what could be the issue to get access deined error message.
Please advise,
Thanks

**Comment by Dan-krm** [comment]
@zydjohnHotmail fetchBalance on Bigone is working properly for me, could you try the following and share the output:
``` Javascript
(async function () {
    console.log (ccxt.version)
    const exchange = new ccxt.bigone ({
        apiKey: 'My_API_Key',
        secret: 'My_Secret_Key',
        verbose: true,
    })
    const balance = await exchange.fetchBalance();
    console.log(balance)
}) ();
```

Bigone seems to have restricted access for people located in certain countries, you might be getting restricted based on your ip address. Also make sure you have the correct permissions checked when you create your API key:

![image](https://user-images.githubusercontent.com/83686770/197373594-3146233a-cea4-4aba-97b1-15c7082a58dc.png)

**Comment by zydjohnHotmail** [comment]
Hello:
I changed my code according to your code template, the following is the output of the results:
D:\nodejs\CCXT_Wallet>node bigoneBalance.js
2.0.58
fetch Request:
 bigone GET https://big.one/api/v3/asset_pairs
RequestHeaders:
 {}
RequestBody:
 undefined

(node:17148) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
handleRestResponse:
 bigone GET https://big.one/api/v3/asset_pairs 403 Forbidden
ResponseHeaders:
 {
  Connection: 'close',
  'Content-Length': '283',
  'Content-Type': 'text/html',
  Date: 'Mon, 24 Oct 2022 07:27:52 GMT',
  Expires: 'Mon, 24 Oct 2022 07:27:52 GMT',
  'Mime-Version': '1.0',
  Server: 'AkamaiGHost',
  'Server-Timing': 'cdn-cache; desc=HIT, edge; dur=1',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Xss-Protection': '1; mode=block'
}
ResponseBody:
 <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>

You don't have permission to access "http&#58;&#47;&#47;big&#46;one&#47;api&#47;v3&#47;asset&#95;pairs" on this server.<P>
Reference&#32;&#35;18&#46;ccd31102&#46;1666596472&#46;1921ec22
</BODY>
</HTML>


D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\Exchange.js:753
            throw new ErrorClass (this.id + ' ' + method + ' ' + url + ' ' + codeAsString + ' ' + reason + ' ' + body);
                  ^

ExchangeNotAvailable: bigone GET https://big.one/api/v3/asset_pairs 403 Forbidden <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>

You don't have permission to access "http&#58;&#47;&#47;big&#46;one&#47;api&#47;v3&#47;asset&#95;pairs" on this server.<P>
Reference&#32;&#35;18&#46;ccd31102&#46;1666596472&#46;1921ec22
</BODY>
</HTML>

    at bigone.handleHttpStatusCode (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\Exchange.js:753:19)
    at D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\Exchange.js:600:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async bigone.fetch2 (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\Exchange.js:1803:16)
    at async bigone.request (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\Exchange.js:1807:16)
    at async bigone.fetchMarkets (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\bigone.js:180:26)
    at async bigone.loadMarketsHelper (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\Exchange.js:626:25)
    at async bigone.loadMarkets (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\bigone.js:273:25)
    at async bigone.fetchBalance (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\bigone.js:766:9) {
  constructor: [class ExchangeNotAvailable extends NetworkError]
}

Node.js v18.10.0

I checked my settings, I gave all the permissions to my API key.
I am living in Spain now, I think for people in Spain, it is OK to use API, and I passed KYC verification at least 3 weeks ago, there should be no other issues to use API.
I asked some advices on the bigone telegram channel, hope I can get some feed back on the access denied issue.

**Comment by Dan-krm** [comment]
Does clicking on this URL show **Access Denied** or **404** for you? https://big.one/api/v3/asset_pairs

The error you're receiving is being thrown with the **asset_pairs** endpoint which is public and used for fetchMarkets

I'd try making a new API key without any restricted IP addresses and make sure the **apiKey** and **secret** are filled in correctly
You could also try deleting your `node_modules` file and execute `npm install ccxt` again to see if that fixes the issue

You could try something like the following to see if you can diagnose the issue:
```
node examples/js/cli bigone fetchBalance --trace-warnings
```
Or try to suppress the issue:
```
node examples/js/cli bigone fetchBalance --no-experimental-fetch
```

Unfortunately I don't think this is an issue that can be fixed on CCXT's end
