### ISSUE TITLE
Wrong argument in docs for OKex

### ISSUE THREAD

**Issue by adradr** [ccxt/ccxt#15277]
```
:param str params['marginMode']: 'cross' or 'isolated'` 
```
should be changed to reflect actual code to:
```
:param str params['mgnMode']: 'cross' or 'isolated'
```

https://github.com/ccxt/ccxt/blob/a200ae66b3c7c1cba72284cbbc3cf8ca2a3abf85/python/ccxt/okx.py#L4460

**Comment by carlosmiei** [comment]
Hello @adradr `marginMode` is the unified term used by ccxt across all exchanges to describe the margin mode

**Comment by adradr** [comment]
> Hello @adradr `marginMode` is the unified term used by ccxt across all exchanges to describe the margin mode

I got that but it was returning with an error for `okex` (using `ccxt==1.92.30` )
```
BadRequest: okex setLeverage() params["mgnMode"] must be either cross or isolated
```

![Screenshot 2022-10-13 at 15 23 22](https://user-images.githubusercontent.com/9167422/195608481-30385308-3134-4501-85b5-aa89b591236c.png)

**Comment by carlosmiei** [comment]
Hello @adradr what is your ccxt version? I think this issue is fixed on the latest versions of ccxt

**Comment by ttodua** [comment]
@adradr as advised by Carlos above, please update your CCXT version to latest and the issue should be gone.
If still any issues, please let us know.

**Comment by adradr** [comment]
> @adradr as advised by Carlos above, please update your CCXT version to latest and the issue should be gone.
> If still any issues, please let us know.

Thanks for the replies, can confirm its solved in the latest version!
