### ISSUE TITLE
'binance' object has no attribute 'timeDelta'

### ISSUE THREAD

**Issue by andy-io** [ccxt/ccxt#1527]
AttributeError: 'binance' object has no attribute 'timeDelta'
https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L308
- OS: Mac
- Programming Language version: python 3.6
- CCXT version: 1.10.860
- Exchange: Binance
- Method: fetch_markets

**Comment by darthf1** [comment]
Got the same. Went from version` 1.10.849` (no issue) to `1.10.861` and got the same issue.

**Comment by andy-io** [comment]
yes the base class has no such attribute

**Comment by kroitor** [comment]
Sorry for the inconvenience, the Python 3 seems to be more restrictive than Python 2. The fix is upcoming in 5-10 minutes in 1.10.862.

**Comment by darthf1** [comment]
I justed updated, now i get 

` Notice: Undefined property: ccxt\binance::$recvWindow`

**Comment by kroitor** [comment]
@darthf1 uploaded a fix for PHP as well, sorry once again, my bad. Waiting for the next build now, tested in all environments and working.

**Comment by darthf1** [comment]
Np! Thanks for fixing it quickly.

**Comment by kroitor** [comment]
@LiYijin fixed everywhere in the most recent version? Is your version up to date?

**Comment by LiYijin** [comment]
@kroitor  I updated to the newest, and this is solved! Thank you!

**Comment by kroitor** [comment]
@LiYijin thanks for reporting back! Cheers!
