### ISSUE TITLE
OKEX exchange client does not support trade account transfer from master account to sub account

### ISSUE THREAD

**Issue by dugusanfeng** [ccxt/ccxt#15273]
- OS: Linux
- Programming Language version: nodejs v14.18.1
- CCXT version: 1.95.36

OKEX exchange client does not support trade account transfer from master account to sub account

```javascript
"use strict";

const ccxt = require ('ccxt')
const exchange = new ccxt.okex ({
        'apiKey': '036d5070-8392-44f7-96fb-520487e36495',
        'secret': 'C8EF94587309061EEDAFDD56E0D0A443',
        'password': 'Zhu88jie!',
        agent
})
// 模拟交易
exchange.setSandboxMode(true)
const transfer = await exchange.transfer ('USDT', 100, 'master', 'steven')
console.log('transfer: ', transfer)
```

Print request: 
```
request:  {
  ccy: 'USDT',
  amt: '100',
  type: '1',
  from: '6',
  to: '6',
  subAcct: 'steven'
}
```

OKEX official documentation about the API description：

![image](https://user-images.githubusercontent.com/12732760/195492711-daced63e-8aca-4a65-b27d-02633166da7e.png)

**Comment by samgermain** [comment]
@dugusanfeng  Could you clarify what this issue is about please?

**Comment by dugusanfeng** [comment]
@samgermain The master account of OKEX exchange transfers funds to the sub-account. The interface request parameters from and to support two options of 6 and 18, and the sdk is currently hardcoded as 6

> @dugusanfeng Could you clarify what this issue is about please?

**Comment by dugusanfeng** [comment]
@samgermain Problems with my method calls，The params parameter specifies the values of from and to。
