### ISSUE TITLE
Receive data from upbit to websocket symbol is displayed as None.

### ISSUE THREAD

**Issue by big100** [ccxt/ccxt#15279]
Receive data from upbit to websocket
symbol is displayed as None.

-source code-

import ccxt.pro
import asyncio

async def __connect_socket():

    exchange = ccxt.pro.upbit(config={
    'enableRateLimit': True,
    })
    await exchange.load_markets()
    while True:
        print(await exchange.watch_order_book("KRW-BTC"))

asyncio.run(__connect_socket())

-result-

{'asks': [[27547000.0, 0.072], [27549000.0, 1.57384619], [27558000.0, 3.20311465], [27562000.0, 0.0101596], [27564000.0, 1.022], [27566000.0, 0.03633456], [27569000.0, 0.479], [27571000.0, 1.0643627], [27576000.0, 0.516], [27578000.0, 1.04], [27582000.0, 0.59583152], [27585000.0, 0.00018126], [27586000.0, 0.50633251], [27589000.0, 0.0969], [27590000.0, 0.00362451]],
 'bids': [[27545000.0, 7.907e-05], [27530000.0, 0.001], [27528000.0, 0.00544536], [27527000.0, 0.1675869], [27526000.0, 0.0660322], [27525000.0, 0.52777423], [27522000.0, 0.01350905], [27519000.0, 0.473], [27518000.0, 0.00187947], [27514000.0, 0.03608031], [27513000.0, 0.487], [27510000.0, 0.3513587], [27506000.0, 1.69805421], [27505000.0, 0.001], [27504000.0, 0.001]],
 'datetime': '2022-10-13T17:01:49.900Z',
 'nonce': None,
 'symbol': None,
 'timestamp': 1665680509900}

**Comment by carlosmiei** [comment]
Hi @big100, thanks for reporting it will be added asap

**Comment by carlosmiei** [comment]
@big100 yes the change will be propagated to all languages, don't worry

**Comment by big100** [comment]
@carlosmiei 
thank you. The program is very well used.
