### ISSUE TITLE
I think I found a couple of small errors.

### ISSUE THREAD

**Issue by ptfu0** [ccxt/ccxt#15292]
https://github.com/ccxt/ccxt/blob/b9bb41b888d52c54316390a18f4258ab3c5dd917/python/ccxt/bybit.py#L2104-L2106
I think result not response:
        timestamp = self.safe_timestamp(result, 'time_now')
        if timestamp is None:
            timestamp = self.safe_integer(result, 'time')

**Comment by carlosmiei** [comment]
Hello @ptfu0, yes you're right, thanks for reporting it, will be fixed asap
