### ISSUE TITLE
Can we add timestamp?

### ISSUE THREAD

**Issue by ptfu0** [ccxt/ccxt#15291]
https://github.com/ccxt/ccxt/blob/b9bb41b888d52c54316390a18f4258ab3c5dd917/python/ccxt/bitmart.py#L982
return self.parse_order_book(data, symbol, data['timestamp'], 'buys', 'sells', 'price', 'amount')

**Comment by ptfu0** [comment]
Hello! Bitmart provides it. Here is the corrected code:
return self.parse_order_book(data, symbol, data['timestamp'], 'buys', 'sells', 'price', 'amount')

**Comment by carlosmiei** [comment]
@ptfu0, you're right again, my bad 😅, it will also be fixed soon!

thanks!
