### ISSUE TITLE
bitmart deposit timestamp and datetime error

### ISSUE THREAD

**Issue by derki-source** [ccxt/ccxt#15307]
- OS: any
- Programming Language version: python
- CCXT version: 2.0.25

after trying to get deposits, most probably withdrawals too with `since` parameter
```python
exchange = ccxt.bitmart(
 args
)

pprint(exchange.fetch_deposits(since=123))
```

```
site-packages/ccxt/base/exchange.py", line 1539, in <listcomp>
    array = [entry for entry in array if entry[key] >= since]
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

check the python implementation syntax:
https://github.com/ccxt/ccxt/blob/b58ad0ef1b2f3e83c3ffa67f4ab3ac97793a3520/python/ccxt/bitmart.py#L2201-L2202
it doesnt seems to have sense nor effect.

Resulting returning `None` for every deposit, and later in `filter_by_value_since_limit` it fails comparing `int` and `None`

**Comment by sc0Vu** [comment]
Hi @derki-source,

I didn't get those error. Probably there is missing `apply_time` in the history data.

Would you like to paste the record (remove `id`/`tx_id`/`amount`/`address` some sensitive data)?

**Comment by derki-source** [comment]
Hey, 

`apply_time` is present in the data. The problem is not that the data is missing, its in the python implementation itself, check the code i am reffering the if condition doesnt make sense:
`timestamp != timestamp if 0 else None, `
that means use:
`timestamp != timestamp`
if the this condtion is met:
`if 0` - which will be always False
and if the condition is not met use:
`None`

so for every tx transform it will be always `None`

are you trying python implementation or javascript? 

example tx returned by ccxt without using since - you can see the missing datetime and timestamp as the result of what i mentioned above even when apply_time is present :
```
{'address': '3BubKTUu37CBQZmeqeiXSzXnjQRPdzDQex',
  'addressFrom': None,
  'addressTo': None,
  'amount': 0.00501526,
  'currency': 'BTC',
  'datetime': None,
  'fee': {'cost': 0.0, 'currency': 'BTC'},
  'id': '13984060',
  'info': {'address': '3BubKTUu37CBQZmeqeiXSzXnjQRPdzDQex',
           'address_memo': '',
           'apply_time': '1662463664000',
           'arrival_amount': '0.00501526',
           'currency': 'BTC',
           'deposit_id': '13984060',
           'fee': '0',
           'operation_type': 'deposit',
           'status': '3',
           'tx_id': 'ded88ea796fb062ba4d69c3be21145be52a063db635356c3d76a6b73c60b4df9',
           'withdraw_id': ''},
  'network': None,
  'status': 'ok',
  'tag': None,
  'tagFrom': None,
  'tagTo': None,
  'timestamp': None,
  'txid': 'ded88ea796fb062ba4d69c3be21145be52a063db635356c3d76a6b73c60b4df9',
  'type': 'deposit',
  'updated': None}
```
