### ISSUE TITLE
Is there an any way to make buy faster and to catch coin on the start of growth, not on spread?

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#15329]
Situation: I've created crypto trading robot using ccxt, which boy coins when they get news about listing on Binance. I'm listening Telegram channel. and when news come, robot buys token on Gate.

This morning there was the listing of token APT, and I am not very happy of how my robot has dealt with it. Can you look at my code and give advices how to improve it and make it faster.

First. as you can see on the screen, token had great open price at 0,0042$. But my robot bought in only for 0.0068. And I don't know why so.

![изображение_2022-10-18_095012445](https://user-images.githubusercontent.com/44064808/196338175-aba52433-ab8f-4e64-8df9-529900d9c4bd.png)
![image](https://user-images.githubusercontent.com/44064808/196338454-bf8a5c3e-f856-4ebf-bbdc-4cc2c614b1ca.png)

This is my code:

```
balance = float(exchange.fetch_balance()["free"]["USDT"])
price = exchange.fetch_ticker(coin + self.usdt)['last']*1.01
amount = float(balance / price)*0.98
exchange.create_limit_buy_order((coin + self.usdt), amount, price)
```

What is its weak place? Usually it buys coin for 1 second. Can it be even faster? As I've seen this morning. 1 second and limit order is not enough. Is there a way to buy market on Gate Spot. buy flesh. right now. and as fast as possible? With CCXT for sure.
And if not, can using of Gateio API V4 help? Will it be faster or not?

I hope you can help me.

**Comment by krychla1** [comment]
You provided very little information to analyze this. Additionally 5min granularity is too high, if you want to analyze problems in seconds.
From what you posted it seems, that you are too slow with everything that proceeded the orders stuff. You create limit order at time, when the price was already too high, you cant expect to execute an order at 0.0042 when you get your ticker at more than 0.0067.

**Comment by KindSpidey** [comment]
> You provided very little information to analyze this. Additionally 5min granularity is too high, if you want to analyze problems in seconds.
> From what you posted it seems, that you are too slow with everything that proceeded the orders stuff. You create limit order at time, when the price was already too high, you cant expect to execute an order at 0.0042 when you get your ticker at more than 0.0067.

Wait no, there is no 5 min, where you find it? Post was at 06:04:seconds_no_info, robot buys token at 06:05:35. So, at least for 35 seconds there was no buy. Why? I've tested my code, when there is no listing, and he made it for 1.5 second. Not for 35.

**Comment by krychla1** [comment]
You've got 5min chart there, we can see just a big green spike there. You have to check exactly when the price started to take off, exactly when you fetched tickers, exactly when you placed order at which price, exactly when it was executed (you have provided only this - 06:05:35).

**Comment by KindSpidey** [comment]
> You've got 5min chart there, we can see just a big green spike there. You have to check exactly when the price started to take off, exactly when you fetched tickers, exactly when you placed order at which price, exactly when it was executed (you have provided only this - 06:05:35).

Oh, got you

**Comment by Dan-krm** [comment]
I'd recommend placing a market order if you'd like to execute the order as quickly as possible, It might be beneficial to use fetchOrderBook to analyze the spread and depth as well.
