### ISSUE TITLE
Is there anyone who know how to get options dataframe from ccxt? Thanks for your answer.

### ISSUE THREAD

**Issue by Clairewangxiaotong** [ccxt/ccxt#15328]

**Comment by carlosmiei** [comment]
Hello @Clairewangxiaotong,
You can check the map ccxt timeframe <-> exchange-specific timeframe by doing `exchange.timeframes`

**Comment by Clairewangxiaotong** [comment]
I apologize for my lack of clarity.
I mean How to get K lines or order books of options?Like this
[image: image.png]

Carlos Gonçalves ***@***.***> 于2022年10月18日周二 16:59写道：

**Comment by Dan-krm** [comment]
> I mean How to get K lines or order books of options? Like this

CCXT plans on adding more unified options support soon, currently you can use the implicit api with a specific endpoint to obtain the data you're looking for: https://docs.ccxt.com/en/latest/manual.html#implicit-api

If you want Klines or order book details, then the applicable unified methods would be fetchOHLCV and fetchOrderBook although I'm not sure how many exchanges will support options for those methods.

I'm going to start working on unifying options and I'll likely create a fetchOptionChain method that I think would be what you're looking for. I'll also look into adding support to fetchOHLCV and fetchOrderBook if possible.

**Comment by Clairewangxiaotong** [comment]
Awesome, thanks!

Dan ***@***.***> 于2022年10月20日周四 13:40写道：

**Comment by Dan-krm** [comment]
I've opened a pull request that adds some examples for options trading on Binance using the implicit API: #15420
Basically the implicit API is calling the endpoints directly with request parameters that are required by the exchanges API documentation. You can use the same approach with any of the endpoints available in the exchanges API documentation.

Feel free to reopen this issue it if you have any more questions. More unified options trading support is coming soon
