### ISSUE TITLE
Kucoin fetchDepositAddress not working!

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#15333]
- OS: Windows 10 (21H2)
- Programming Language version: Node.js (version 18.10.0)
- CCXT version: 2.0.34

```JavaScript
const ccxt = require('ccxt');
console.log(ccxt.version)

const coin1 = process.argv[2];
var json_data = async () => {
    let kucoin = new ccxt.kucoin({
        apiKey: 'My_API_Key',
        secret: 'My_Secret_Key',
        adjustForTimeDifference: true,
        defaultType: 'spot',
        password: 'My_Password',
        uid: 'My_User_ID'
    });
    try {
        const kucion_markets = await kucoin.loadMarkets();
        console.log(kucion_markets);
        const deposits = await kucoin.fetchDepositAddress(coin1);
        console.log(deposits);
    } catch (e) {
        console.log(e.constructor.name, e.message)
    }
};
json_data();
```

```
InvalidAddress kucoin address is undefined
```

Hello:
I want to get deposit address for some currencies, but my code did NOT work:
When I run my code, for `kucoin.loadMarkets();` it works, I can see a lot of markets are displayed; however, the 

`kucoin.fetchDepositAddress(coin1);`
return something like the following:
```
……
InvalidAddress kucoin address is undefined
```
Please check and let me know how I can fix this issue.
Thanks,

**Comment by sc0Vu** [comment]
Hi @zydjohnHotmail 

Have you created deposit address for that coin first?

```
const created = await kucoin.createDepositAddress(coin1);
// they also retrun deposit address, see: https://docs.kucoin.com/#create-deposit-address
// const deposits = await kucoin.fetchDepositAddress(coin1);
```

**Comment by zydjohnHotmail** [comment]
Hello:
I don't know I have to run createDepositAddress first, now I changed my code, so for exchange kucoin, the fetchDepositAddress is working now for kucoin.
