### ISSUE TITLE
exchange.transfer is not working with on bybit exchange

### ISSUE THREAD

**Issue by danieltorscho** [ccxt/ccxt#15345]
Transfering funds from "spot" to "funding" accounts works fine on binance exchange, but not with bybit.
Maybe I'm missing some arguments in my request ?

- OS: Win 10 x64
- Programming Language version: Node.js 18
- CCXT version: 2.0.25

```
// Transfering 2 USDT from spot to funding
exchange.transfer('USDT', 2, 'spot', 'funding')
```

```
BadRequest: bybit {"ret_code":10001,"ret_msg":"invalid parameter","ext_code":"","result":null,"ext_info":null,"time_now":1666163282207}
    at bybit.throwExactlyMatchedException (/home/user/www/nodeccxt/node_modules/ccxt/js/base/Exchange.js:2142:19)
    at bybit.handleErrors (/home/user/www/nodeccxt/node_modules/ccxt/js/bybit.js:5420:18)
    at /home/user/www/nodeccxt/node_modules/ccxt/js/base/Exchange.js:598:51
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async timeout (/home/user/www/nodeccxt/node_modules/ccxt/js/base/functions/time.js:181:20)
    at async bybit.fetch2 (/home/user/www/nodeccxt/node_modules/ccxt/js/base/Exchange.js:1803:16)
    at async bybit.request (/home/user/www/nodeccxt/node_modules/ccxt/js/base/Exchange.js:1807:16)
    at async bybit.transfer (/home/user/www/nodeccxt/node_modules/ccxt/js/bybit.js:5064:26)
    at async withdrawToWallet (/home/user/www/nodeccxt/src/testing.js:32:3)
    at async start (/home/user/www/nodeccxt/src/testing.js:21:3) {
  constructor: [class BadRequest extends ExchangeError]
}
```

**Comment by sc0Vu** [comment]
@danieltorscho

It didn't work on my side either. Will take a look.

**Comment by danieltorscho** [comment]
@sc0Vu please leave this issue open for a while, I will try to find a solution for this issue based on your suggestion.

**Comment by danieltorscho** [comment]
@ttodua 
Thanks for clarifying. Unfortunately it still doesn't work with `unified` nor `UNIFIED`.

`exchange.options.accountsByType` returns:
```
{
  spot: 'SPOT',
  margin: 'SPOT',
  future: 'CONTRACT',
  swap: 'CONTRACT',
  option: 'OPTION',
  investment: 'INVESTMENT',
  unified: 'UNIFIED'
}
```
Transfer from `spot` to `swap` works:
```
exchange.transfer('USDT', 1, 'spot', 'swap').then(console.log)
```

Transfering from `spot` to `unified` still doesn't work:
```
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 18651,
  [Symbol(trigger_async_id_symbol)]: 18649,
  [Symbol(destroyed)]: { destroyed: false }
}
> Uncaught:
ExchangeError: bybit {"ret_code":90060,"ret_msg":"ForbiddenTransfer","ext_code":"","result":null,"ext_info":null,"time_now":1666738041427,"rate_limit_status":17,"rate_limit_reset_ms":1666738041427,"rate_limit":3}
    at bybit.handleErrors (/home/user/www/node-ccxt/node_modules/ccxt/js/bybit.js:5500:19) {
  constructor: [class ExchangeError extends BaseError]
}
```

**Comment by danieltorscho** [comment]
@ttodua @sc0Vu
So I came up with a following solution to be able to transfer from **SPOT** to **FUNDING** account.

*Just for info:
We do not need an `UNIFIED` account type in that case.
As suggest by one guy from Bybit Telegram Group, to be able to transfer to `UNIFIED` account type, you should upgrade your Bybit account into Unified margin account which takes some precautions and actions by you. By clickin on yellow UPGRADE NOW button in the right top corner [on this page](https://www.bybit.com/user/assets/home/usdcaccount)*

I've made a hard-coded changes into `ccxt/js/bybit.js`:

```
'accountsByType': {
    'spot': 'SPOT',
    'margin': 'SPOT',
    'future': 'CONTRACT',
    'swap': 'CONTRACT',
    'option': 'OPTION',
    'investment': 'INVESTMENT',
    'unified': 'UNIFIED',
    'funding': 'FUND' // <-- Add this line, to make it work identically as in binance.js
}
```

**Comment by ttodua** [comment]
@danieltorscho thanks for your follow ups! I will revise the current state of our bybit integration and its API docs, to find out what has been changed, and then push an update in ccxt.
