### ISSUE TITLE
editOrder on bitget doesn't work

### ISSUE THREAD

**Issue by AstraDynamic** [ccxt/ccxt#15346]
I have issues editing stop orders on bitget. Once placed, i am not able to change it via ccxt (Node Js):

1) Placing Order:

async function teststop () {
    let params = {
        'stopLossPrice': 1295, // your stop loss price
    }

    let order = await bitget.createOrder (symbol='ETH/USDT:USDT', type='market', side='buy', amount=0.1, price=undefined, params)
    console.log(order)

}

Output:

{
  info: { clientOid: '966559794399354880', orderId: '966559794399354881' },
  id: '966559794399354881',
  clientOrderId: '966559794399354880',
  timestamp: undefined,
  datetime: undefined,
  lastTradeTimestamp: undefined,
  symbol: undefined,
  type: undefined,
  timeInForce: undefined,
  postOnly: undefined,
  side: undefined,
  price: undefined,
  stopPrice: undefined,
  average: undefined,
  cost: undefined,
  amount: undefined,
  filled: undefined,
  remaining: undefined,
  status: undefined,
  fee: undefined,
  trades: [],
  fees: []
}

2) Trying to edit order using the provided id:

async function testadjust () {
    let new_params = {
        'stopLossPrice': 1290 // your stop loss price
    }

    let result = await bitget.editOrder (id='966559794399354881', symbol='ETH/USDT:USDT', type='market', side='buy', amount=0.1, price = undefined, params = new_params )
    dLog(result)
}

Output:

(node:1636619) UnhandledPromiseRejectionWarning: ExchangeError: bitget {"code":"40768","msg":"Order does not exist","requestTime":1666171771617,"data":null}

Checking on bitget: stop order is still there.

3) Trying to check on openOrders:

async function fetchopen () {
    let result = await bitget.fetchOpenOrders(symbol='ETH/USDT:USDT', since = undefined, limit =12, params = {})
    dLog(result)
}

Output:

log [] +0ms

Empty!

... I verified that this generally works by placing an unfilled limit orders. In that case, it is returned via openOrders.

Can you provide some guidance? Many thanks!

**Comment by pcriadoperez** [comment]
Hi Astra,

The first order is a market order, therefore it is being created and filled. And I'm guessing that is why you are getting an `Order does not exit error` when trying to edit it.
My recommendation to add a stop order to the position, is to create a stop order, or to add a stop Loss when creating the initial position.

Hope that helps! Let me know if you have any other questions.
