### ISSUE TITLE
How to work with big spread? Give advice please

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#15349]
Hello guys. 

I have a crypto trading robot, which works with Binance listings. When news about new listing come, robot buys token on Gate. But the price of the listing token increases imediately in multiple percents. 

How should I setup my robot to buy token for the best and lowest price? 

Right now after getting news i get price of token and then place limit order with higher on +10% price. Is it good?

Or maybe I should use something, but not limit order? Maybe market buy? Or something which can notice the big spread and work with this spread? What are your ideas?

**Comment by Dan-krm** [comment]
I think these types of questions might be better served in the CCXT general discord or some other channels, generally issues should be opened for bugs or recommended enhancements to the library.

For your trading bot you can use fetchOrderBook to analyze the depth and spread of the trading pair:
https://docs.ccxt.com/en/latest/manual.html#order-book

If you'd like to buy as soon as possible I'd just create a market order, or maybe a limit order based on the depth of the orderbook to ensure it gets filled.

**Comment by KindSpidey** [comment]
Thank you very much

**Comment by KindSpidey** [comment]
But can you give an advice with market vs limit orders? Market order will be always executed? I mean, does it depend on big spread? I place market order, and it doesn't matter, if price go higher or lower immediately, it will be executed anyway and right now? 
For limit order in my robot I place price higher for 8%, to make a bought. Is it risky?

**Comment by Dan-krm** [comment]
Market orders will execute at the current market price set by the price/amount on the orderbooks ask side

- If you're wanting to fill an order as fast as possible and are currently setting a limit order on the ask side of the orderbook it makes sense to just place a market order for an amount that you're comfortable with, it will fill for the amount that you set but the price it fills will vary depending on the depth of the ask side of the orderbook

- If you're placing a big market order on an illiquid trading pair that has a shallow market depth, you might end up overpaying for some of the order and consider using limit orders instead

https://www.investopedia.com/ask/answers/100314/whats-difference-between-market-order-and-limit-order.asp
https://www.investopedia.com/terms/b/bid-and-ask.asp
https://www.investopedia.com/terms/m/marketdepth.asp

**Comment by Dan-krm** [comment]
@KindSpidey you could also add a timeInForce argument to your params to test with different order types: https://docs.ccxt.com/en/latest/manual.html#timeinforce
