### ISSUE TITLE
How to use ccxt.pro to watch binanceusdm perp positions?

### ISSUE THREAD

**Issue by 583** [ccxt/ccxt#15350]
Hi, I can only see the watchTrades, but not watchPositions, how to watch binanceusdm perp?

**Comment by carlosmiei** [comment]
Hello @583 currently there is only `watchOrders`, `watchPositions` is a work in progress, but should be available soon

**Comment by 583** [comment]
> Hello @583 currently there is only `watchOrders`, `watchPositions` is a work in progress, but should be available soon

OK, watchOrders not able to watch position?

**Comment by 583** [comment]
> @583 nop, only the order itself, so it has no effect after the order is filled

Thanks~ 
In ccxt.pro websocket, It's there any raw-method like (ccxt)binance.fapiPrivateGetPositionRisk() to get biance position ? ws position update event: https://binance-docs.github.io/apidocs/futures/en/#event-balance-and-position-update

**Comment by ttodua** [comment]
> > @583 nop, only the order itself, so it has no effect after the order is filled
> 
> Thanks~ In ccxt.pro websocket, It's there any raw-function like (ccxt)binance.fapiPrivateGetPositionRisk() to get biance position ? websocket get position update event: https://binance-docs.github.io/apidocs/futures/en/#event-balance-and-position-update

iirc, we plan adding custom endpoint subscriptions, like it's possible in REST. stay tuned and subscribe to CCXT's announcements telegram/discord channels.

**Comment by zexz** [comment]
> Hello @583 currently there is only `watchOrders`, `watchPositions` is a work in progress, but should be available soon

is "watchOrders" available in php version of ccxt pro? Was trying to use it but it gives "watchOrders method not found"

Could you give me a hint where i gone wrong?

```
        $exchange = new \ccxt\pro\binanceusdm();
        $exchange->apiKey = $credentials->public_key;
        $exchange->secret = $credentials->secret_key;
        $exchange::execute_and_run(function() use ($exchange) {
            while (true) {
                $orders = yield $exchange->watchOrders();
                var_dump($orders);
                echo PHP_EOL;
            }
        });
```

**Comment by ttodua** [comment]
> > Hello @583 currently there is only `watchOrders`, `watchPositions` is a work in progress, but should be available soon
> 
> is "watchOrders" available in php version of ccxt pro? Was trying to use it but it gives "watchOrders method not found"
> 
> Could you give me a hint where i gone wrong?
> 
> ```
>         $exchange = new \ccxt\pro\binanceusdm();
>         $exchange->apiKey = $credentials->public_key;
>         $exchange->secret = $credentials->secret_key;
>         $exchange::execute_and_run(function() use ($exchange) {
>             while (true) {
>                 $orders = yield $exchange->watchOrders();
>                 var_dump($orders);
>                 echo PHP_EOL;
>             }
>         });
> ```

I'll post a reply soon.

**Comment by ttodua** [comment]
here[ is PR](https://github.com/ccxt/ccxt/pull/15446) that demonstrates it. you can see it now under `files` or when it will be merged, you can check those files in `/example/ccxt.pro/php`

**Comment by zexz** [comment]
Hello everyone, any update on adding watchPositions() method so far?

**Comment by tensorboy** [comment]
Same waiting for the watchPositions() method

**Comment by etienne51** [comment]
Also asking the same question, I was hoping to use it on ByBit mainly.

**Comment by carlosmiei** [comment]
@etienne51  
@tensorboy 
@etienne51 

We're aware that you guys are waiting for it, and we will do our best to add `watchPositions` as soon as possible. It's not trivial because every exchange has a different take on handling positions, their sides, their fields, etc but we will try to find a solution.

**Comment by bugb** [comment]
+1 for it

**Comment by acassan** [comment]
+1 as well

**Comment by carlosmiei** [comment]
@etienne51
@tensorboy
@zexz
@bugb 
@acassan 

Just a quick update, if everything goes well, we will release it in a few days, hang tight 😅

**Comment by nikky78** [comment]
Hi Guys! Any update, please ? :)

**Comment by carlosmiei** [comment]
@nikky78 will be released today!

**Comment by carlosmiei** [comment]
@etienne51
@tensorboy
@zexz
@bugb
@acassan
@nikky78 
@583 

We finally released it as of 4.1.46. 
Please bear in mind this is an experimental feature that might produce unexpected results, but CCXT will be here to assist you if needed. 

Thank you very much for your patience!

**Comment by nikky78** [comment]
NotSupported: bybit watchPosition() is not supported yet

**Comment by carlosmiei** [comment]
@nikky78 Binance, OKX, Bitget, Kraken, Kucoin, Gate, Huobi, and CryptoCom but you should be using `watchPositions` (plural)

**Comment by nikky78** [comment]
I get "BadSymbol: bybit does not have market symbol B", with both BTCUSDT or BTC/USDT:USDT.

**Comment by ttodua** [comment]
> I get "BadSymbol: bybit does not have market symbol B", with both BTCUSDT or BTC/USDT:USDT.

note about signature of methods. where they need array to be provided, you should provide argument `['BTC/USDT:USDT']` intead of string `BTC/USDT:USDT`
