### ISSUE TITLE
How to work with Futures for other exchanges except Binance and KuCoin?

### ISSUE THREAD

**Issue by rvoitovich** [ccxt/ccxt#15351]
Hi,
Based on the list of available exchanges, it can be seen that Binance and KuCoin have a separate id for working with Futures. But what about other exchanges? For example, HitBTC also has futures in its API.

Work with them is not implemented or is there a trick here?

Thanks

**Comment by pcriadoperez** [comment]
Hi @rvoitovich,
Some exchanges have seperate id's when they have specific api keys, or different urls. But for most exchanges ccxt uses the same id for different markets types. You can check if an exchange supports futures by checking  `if (exchange.has['future'] === true` or `if (exchange.has['swap'] === true)` for perpetuals.
In the case of hitBTC, the exchange id hitBTC3 supports swaps but not futures.

I'll close this issue for now but feel free to comment or open a new issue if you have any further questions
