### ISSUE TITLE
Clarification on createOrder / createMarketBuyOrder

### ISSUE THREAD

**Issue by julienbfabre** [ccxt/ccxt#15352]
I'm trying to understand `createOrder` / `createMarketBuyOrder` methods.

What i'm trying to do is place a market order on Binance specifying how much i want to spend in the quote currency, say for the symbol BTC/USDT i want to spend 100 USDT to buy whatever BTC that amounts to, without having to specify the price of BTC since i want the spot price, the way i understand the docs, this should be possible in the second example found here: https://docs.ccxt.com/en/latest/manual.html#market-buys 
It says i can specify the cost instead of the amount and price so:

```
this.exchange = new ccxt[settings.exchange]({
      'apiKey': conf.api[settings.exchange].key,
      'secret': conf.api[settings.exchange].secret,
      'verbose': true,
      'createMarketBuyOrderRequiresPrice': false,   //we just want to specify how much we want to spend, not at what price we want to buy
});

this.exchange.setSandboxMode(true);

const order = await this.exchange.createMarketBuyOrder("BTC/USDT", 100, { clientOrderId: 'my-custom-uuid' });
```

This gives me a `{"code":-2010,"msg":"Account has insufficient balance for requested action."} `

My balance is 1 BTC and 10000 USDT so it seems i am mixing something up and somehow trying to spend 100 BTC?

Looking at the [source code](https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L2337) for `createMarketBuyOrder` i see that the param that is explained as `cost` in the docs is in fact the `amount` that is passed straight to `createOrder`.

Are the docs wrong, or there's a bug or am i completely misunderstanding all this?

**Comment by samgermain** [comment]
I actually think this section of the docs might be inaccurate, sorry about that.

I've opened a [PR](15353) providing what is hopefully a better explanation

**Comment by julienbfabre** [comment]
@samgermain i had a look at the PR, so if i understand correctly my only options are either leaving `createMarketBuyOrderRequiresPrice` as `true` and passing both the amount (base currency) and price (quote currency) or setting it to `false` and specifying just the amount (base currency)?

is there no way to place a buy order specifying just how much quote currency i want to spend? 
Like "hey binance i want to buy 100 dollars of bitcoin, give me whatever amount of bitcoins that is on the current market price".

**Comment by samgermain** [comment]
> @samgermain i had a look at the PR, so if i understand correctly my only options are either leaving `createMarketBuyOrderRequiresPrice` as `true` and passing both the amount (base currency) and price (quote currency) or setting it to `false` and specifying just the amount (base currency)?
> 
> is there no way to place a buy order specifying just how much quote currency i want to spend? Like "hey binance i want to buy 100 dollars of bitcoin, give me whatever amount of bitcoins that is on the current market price".

I added another commit to that PR with an updated explanation, let me know if this explanation makes sense

**Comment by julienbfabre** [comment]
@samgermain i'm still not sure i understand this correctly. 

if `createMarketBuyOrderRequiresPrice ` is `true` then i can specify the amount in quote currency (USD in my example), but i must also specify the price as it says here: 

> you specify the amount in quote currency when creating your order, but must also supply the price

and if set to `false`, then i don't have to specify the price, but i have to specify the amount in base currency (BTC in my example) as it says here:

> Setting `createMarketBuyOrderRequiresPrice` to `false` allows you to specify the amount in base currency instead The price argument will not be required

so there is no way to place an order by simply specifying the amount of quote currency (USD in my example) and no price so that the current market price is used?

**Comment by carlosmiei** [comment]
Hello @julienbfabre, I'm seeing some confusion here so let me try to clarify it a bit:

> if createMarketBuyOrderRequiresPrice is true then i can specify the amount in quote currency (USD in my example), but i must also specify the price as it says here:

Nop, if `createMarketBuyOrderRequiresPrice`  is true you can provide the amount in base currency (BTC) and the price, so that we can calculate the `cost` and send it (amount*price)

Example: `createOrder("BTC/USDT", "market", "buy", 0.1, 10000)` <- this will place place an order worth of 100 USDT, regardless of the current BTC price

If you manually set `createMarketBuyOrderRequiresPrice` to false, you can just do this: 

`createOrder("BTC/USDT", "market", "buy", 100, undefined)` <- amount here is the cost (quote currency), in this case 100 USD

**Comment by julienbfabre** [comment]
hi @carlosmiei , thanks for jumping in, i tried both, one does work, the other not, here's some details:

considering the balance:
- BTC: 1
- USDT: 10000

### trying your first example:

```
//binance
this.exchange = new ccxt[settings.exchange]({
      'apiKey': conf.api[settings.exchange].key,
      'secret': conf.api[settings.exchange].secret,
      'verbose': true,
      'createMarketBuyOrderRequiresPrice': true,   
});

this.exchange.setSandboxMode(true);

const order = await this.exchange.createOrder("BTC/USDT", "market", "buy", 0.1, 10*10, { clientOrderId: 'my-custom-uuid' });
```

This results in the following request:

```
RequestBody:
 timestamp=1666365640167&symbol=BTCUSDT&type=MARKET&side=BUY&newClientOrderId=ebf48740-5153-11ed-ae25-21847f7ce67c&newOrderRespType=FULL&quoteOrderQty=10&recvWindow=10000&signature=REDACTED
```

which was fulfilled successfuly, so that one works even though i have to resort to passing an amount of `0.1` and price of `{amount i want to spend} * 10` so that the math adds up to what i want to spend, not ideal but at least that works.

### Now trying your second example:

```
//binance
this.exchange = new ccxt[settings.exchange]({
      'apiKey': conf.api[settings.exchange].key,
      'secret': conf.api[settings.exchange].secret,
      'verbose': true,
      'createMarketBuyOrderRequiresPrice': false,   
});

this.exchange.setSandboxMode(true);

const order = await this.exchange.createOrder("BTC/USDT", "market", "buy", 10, undefined, { clientOrderId: 'my-custom-uuid' });
```

This makes the following request:
```
fetch Request:
 binance POST https://testnet.binance.vision/api/v3/order 
RequestBody:
 timestamp=1666365030225&symbol=BTCUSDT&type=MARKET&side=BUY&newClientOrderId=8066c3e0-5152-11ed-8d08-5d5e4dba01c0&newOrderRespType=FULL&quantity=10&recvWindow=10000&signature=REDACTED 
```

which results in the following error:

```
{"code":-2010,"msg":"Account has insufficient balance for requested action."} 
```

so clearly it is trying to spend 10 BTC instead of 10 USDT, which i believe is because in the POST it is using `quantity` instead of `quoteOrderQty`. 

Seems there's either an issue there or we expect something different than what that boolean flag is supposed to do, right?

**Comment by carlosmiei** [comment]
Hello again @julienbfabre, sorry for the delay in replying

I was talking about the `createMarketBuyRequiresPrice` option only, not every exchange has it, and binance is not one of them, but you can easily do it for binance as well.

If you want to use the cost for market buy just do this:

```Python

binance.options['quoteOrderQty'] = true
params = { 'cost': 100 } # spending 100 USDT
order = await exchange.create_order("BTC/USDT", "market", "buy", None, None, params)
```
Let me know if this does not help ⬆️

**Comment by julienbfabre** [comment]
ok understood, thanks @carlosmiei !
