### ISSUE TITLE
IS there anyone who know how to get a  current position with symbol= 'BTC/USDT' by binance?Thanks!

### ISSUE THREAD

**Issue by Clairewangxiaotong** [ccxt/ccxt#15357]
![image](https://user-images.githubusercontent.com/103891038/196848239-716c9be6-eb2a-4f41-9111-bc5a353b4a6e.png)

**Comment by pcriadoperez** [comment]
Hi @Clairewangxiaotong you can fetch by using the function `fetchPositions`
So for example: `binanceusdm.fetchPositions (['BTCUSDT'])`

**Comment by Clairewangxiaotong** [comment]
Hi @pcriadoperez ,THANKS for your answer,but I met a new bug when I used the function which you suggested.
![image](https://user-images.githubusercontent.com/103891038/196857785-be3bacc3-98f8-4708-a2c1-5ae571f81843.png)

**Comment by samgermain** [comment]
> Hi @pcriadoperez ,THANKS for your answer,but I met a new bug when I used the function which you suggested. ![image](https://user-images.githubusercontent.com/103891038/196857785-be3bacc3-98f8-4708-a2c1-5ae571f81843.png)

If your using the exchange with classname `binance` make sure that when you instantiate it, you set the `defaultType` to `future`

**ex.**
```
exchange = ccxt.binance({
    'apiKey': '...',
    'secret': '...',
    'options': {
        'defaultType': 'future'
    },
})
```

alternatively you can just use the exchange name `binanceusdm` instead of `binance`

**ex.**
```
exchange = ccxt.binanceusdm({
    'apiKey': '...',
    'secret': '...',
})
```

**Comment by Clairewangxiaotong** [comment]
WOW！  Thank you very much! It helps me too much!Have a nice day!!!


Sam Germain ***@***.***> 于2022年10月20日周四 12:45写道：
