### ISSUE TITLE
hasFetchTickers property wrong in WEX (Python)

### ISSUE THREAD

**Issue by 2msd** [ccxt/ccxt#1536]
- OS: MacOS 10.12.6
- Programming Language version: Python3.6
- CCXT version: 1.10.873
- Exchange: WEX

hasFetchTickers property is False (wrong)
has['fetchTickers'] property is True (correct)

I suppose it has something to do with class inheritance from liqui, but I can't find out why. 
hasFetchTickers is correct with other exchanges (e.g. Kraken)

**Comment by kroitor** [comment]
We are migrating to the new metainfo format, that is the `.has = {}` property that we are making now to reflect the truth, and the older separate `.has***` properties are now deprecated. Please update your code. Thx, and sorry for the inconvenience! Hope to finish the migration asap with as little pain as possible. Let me know if I can help with anything else or if I didn't answer your question.
