### ISSUE TITLE
Binance VAPI -> EAPI

### ISSUE THREAD

**Issue by diwenshi61** [ccxt/ccxt#15373]
Binance has removed the 'vapi' endpoints and added 'eapi' endpoints for options trading.
E.g.

GET https://vapi.binance.com/vapi/v1/time
is removed instead
GET https://eapi.binance.com/eapi/v1/time

Some endpoints previously in vapi such as 'optionInfo' are not in eapi (returns 404). Should be removed.

Might be related to this issue #15221

**Comment by Dan-krm** [comment]
Thanks for reporting, I've opened a pull request that will resolve this issue once it's merged
