### ISSUE TITLE
bybit Can't get any info of usdc perp

### ISSUE THREAD

**Issue by croissantty** [ccxt/ccxt#15377]
Hi, I have search and try method about options type already but still no clue. I can't access to any USDC perpetual symbol or balance. Its only show future balance&pair(USDT). I want to trade in usdc perpetual sir but 
```
ccxt.base.errors.BadSymbol: bybit does not have market symbol BTCPERP
```

This is header
```
bybit = ccxt.bybit({
"apiKey": "xxxx",
"secret": "xxxx",
"options": {'defaultType': 'future'}
})
print(bybit.fetchMarkets())
```

Is bybit USDC perp contracts have some specific type for it?

ps. Sorry for trouble

**Comment by carlosmiei** [comment]
Hello @croissantty, Bybit has conflicting ids between USDT settle derivatives and the USDC one (BTC-PERP), so I would recommend using the unified symbol, in this case `BTC/USD:USDC`

Example:
```Python
ticker = await exchange.fetch_ticker('BTC/USD:USDC')
```

Regarding the balance, by default  will return the usdt based wallet balance, to change it, you have two options
- settle the `defaultSettle` option as `USDC` `exchange.options['defaultSettle`] = 'USDC' `
- add `settle` to `params` 

Example:

```Python
params = {
    'settle': 'USDC'
}
balance = await exchange.fetch_balance(params)
```

**Comment by croissantty** [comment]
Very thank you @carlosmiei, with your help now I can access balance and symbol. but look like `fetchMyTrades()` is not working with this exchange or I'm missing something?

```
ccxt.base.errors.NotSupported: bybit fetchMyTrades() is not supported for market BTC/USD:USDC
```

**Comment by ttodua** [comment]
> is not supported for market

You are right, seems the current implementation doesn't have any endpoint to access it, so it seems bybit is lacking that endpoint, we can't do anything in such case (if anyone finds out that that bybit added/supports it now and we have a missing implementation, let us know)
