### ISSUE TITLE
CCXTPRO removed dependence

### ISSUE THREAD

**Issue by AdamPrisen** [ccxt/ccxt#15374]
- OS: Mac OS
- Programming Language version: Python
- CCXT version:  2.0.53
- CCXT version:  1.2.36

```
from ccxt.async_support.eqonex import eqonex                              # noqa: F401
```
in the newest version of ccxt was removed dependence  which ccxtpro is still requiring

**Comment by carlosmiei** [comment]
Hello @AdamPrisen are you still using the standalone ccxt.pro package?

**Comment by AdamPrisen** [comment]
Hello yea i am still using ccxt.pro but i am reading that websockets were merged to ccxt so we will change it to that version

**Comment by carlosmiei** [comment]
@AdamPrisen yeah ccxt.pro was merged into ccxt and the old package won't get updates anymore, so we strongly recommend migrating it

**Comment by HUGH-XUUUU** [comment]
Hi,What do you mean abou "merged into ccxt"? Can we still use these websocket supported method in ccxt.pro?

**Comment by HUGH-XUUUU** [comment]
@carlosmiei

**Comment by carlosmiei** [comment]
Hello @HUGH-XUUUU in the past ccxt.pro was a paid product with its own package, now it's free and merged into the regular ccxt package, so if you're still using the "paid" package it's better to migrate because won't get more updates/fixes

**Comment by HUGH-XUUUU** [comment]
Thanks man @carlosmiei !

**Comment by ttodua** [comment]
As everything is clear, I'll close this issue. let us know if you have any further issues with CCXT.
