### ISSUE TITLE
bybit Can't fetch my USDT deposit address on TRC20 network

### ISSUE THREAD

**Issue by HowardTrades** [ccxt/ccxt#15384]
Hi, I have been using the following code to fetch my USDT deposit address. It works on Binance, FTX, Mexc and OKX. However, when I use the code on Bybit, it cannot find TRC20 deposit address for USDT (I also try TRC too, didn't work).

```python
exchange = ccxt.bybit({
    'apiKey': BYBIT_API_KEY,
    'secret': BYBIT_API_SECRET,
})
deposit_address = exchange.fetch_deposit_address("USDT", params={"network":"TRC20"})
```

output
```python
ccxt.base.errors.InvalidAddress: bybit fetchDepositAddress() cannot find TRC20 deposit address for USDT
```

Then I try to replace network with chain, only to get ERC 20 deposit address (seems like the params has been neglected)
```python
deposit_address = exchange.fetch_deposit_address("USDT", params={"chain":"TRC20"})`
```
output:
```python
{'currency': 'USDT', 'address': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'tag': None, 'network': 'ETH', 'info': {'chain_type': 'ERC20', 'address_deposit': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'tag_deposit': '', 'chain': 'ETH'}}
```

thank you

**Comment by samgermain** [comment]
You need to use `TRX` right now, after [this PR](https://github.com/ccxt/ccxt/pull/15386) gets merged you'll be able to use `TRC20`
