### ISSUE TITLE
hitbtc2 request timed out (10000 ms)

### ISSUE THREAD

**Issue by rhrahul** [ccxt/ccxt#1538]
Hi,
So sometimes I am getting this error, Even in public request and private request,
same error.

Error: Uncaught (in promise): Error: hitbtc2 GET http://localhost:8080/https://api.hitbtc.com/api/2/public/symbol request timed out (10000 ms)
Error: hitbtc2 GET http://localhost:8080/https://api.hitbtc.com/api/2/public/symbol request timed out (10000 ms)

- OS: Windows 10
- Programming Language version: JavaScript
- CCXT version: Latest
- Exchange: HitBTCv2
- Method: Any Method

**Comment by kroitor** [comment]
Hi!

This question has been already answered in previous issues, for example here:
- https://github.com/ccxt/ccxt/issues/1427
- search for "timeout" in the issues of this repo
- search for "timed out"
- read the troubleshooting section: https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- read the error handling section: https://github.com/ccxt/ccxt/wiki/Manual#error-handling

Let us know if the above does not help. Thx!

**Comment by rhrahul** [comment]
How can I set timeout manually ?

**Comment by kroitor** [comment]
@rhrahul 

```JavaScript
const ccxt = require ('ccxt')
const exchange = new ccxt.hitbtc2 ({ timeout: 30000 }) // 30000 in milliseconds = 30 seconds
```

**Comment by rhrahul** [comment]
Ok, thanks

**Comment by kroitor** [comment]
@rhrahul if it doesn't help, you may want to set your user-agent as well... Most exchange properties are described here: https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

**Comment by rhrahul** [comment]
Ok, Thanks 👍
