### ISSUE TITLE
fetch data from OKX

### ISSUE THREAD

**Issue by markxma1** [ccxt/ccxt#15389]
I try to make full overview over my transaktions (bye/sell/deposit/withdrawl/earnings and boot trades) with python for Okx, but I get only 2 Trades (but I have made more than 2).

I have tried to send request with orders-history-archive and fetchMyTrades from CCXT Library (have tried some other functions, but I steed don't get my transactions.)

Is there some way to get full overview for Okx with python (and other Brocker/Wallets)?

here How I try to get the data with CCXT (it give only 2 outputs):

    def getMyTrades(self):
        tData = []
        tSymboles = [
            'BTC/USDT',
            'ETH/USDT',
            'SHIB/USDT',
            'CELO/USDT',
            'XRP/USDT',
            'SAMO/USDT',
            'NEAR/USDT',
            'ETHW/USDT',
            'DOGE/USDT',
            'SOL/USDT',
            'LUNA/USDT'
        ]
        for item in tSymboles:
            if exchange.has['fetchMyTrades']:
                since = exchange.milliseconds() - 60*60*24*180*1000  # -180 days from now
                while since < exchange.milliseconds():
                    symbol = item  # change for your symbol
                    limit = 20  # change for your limit
                    orders = exchange.fetchMyTrades(symbol, since, limit)
                    if len(orders):
                        since = orders[len(orders) - 1]['timestamp'] + 1
                        tData += orders
                    else:
                        break

**Comment by Curro666** [comment]
Hi @markxma1,
it would help developers a lot if you put the version of ccxt you are using.
I just replied to a message from @ttodua and i have seen your problem.
As the code is and I have a little free time i have tried and these are my results (I put it here in case it helps)

```
def getMyTrades():
    tData = []
    tSymboles = [
        'BTC/USDT',
        'ELON/USDT',
        'GAS/USDT',
        'GAS/BTC',
        'LUNA/USDT',
        'LUNC/USDT',
        'SHIB/USDT',
        'SNT/USDT',
        'SWEAT/USDT',
        'XEC/USDT'
    ]
    for item in tSymboles:
        if exchange.has['fetchMyTrades']:
            since = exchange.milliseconds() - 60*60*24*180*1000  # -180 days from now
            while since < exchange.milliseconds():
                symbol = item  # change for your symbol
                limit = 100  # change for your limit
                orders = exchange.fetchMyTrades(symbol, since, limit)
                print(since, symbol, len(orders))
                if len(orders):
                    since = orders[len(orders) - 1]['timestamp'] + 1
                    tData += orders
                else:
                    break
                
                
getMyTrades()
```
the result:

CCXT Version: 2.0.103
1651723995885 BTC/USDT 20
1666960218737 BTC/USDT 0
1651723998373 ELON/USDT 72
1667246686279 ELON/USDT 0
1651723999297 GAS/USDT 85
1667261487829 GAS/USDT 0
1651723999922 GAS/BTC 11
1666621666421 GAS/BTC 0
1651724000476 LUNA/USDT 25
1665555857800 LUNA/USDT 0
1651724001032 LUNC/USDT 78
1666983903335 LUNC/USDT 0
1651724001649 SHIB/USDT 33
1667249445848 SHIB/USDT 0
1651724002206 SNT/USDT 0
1651724002554 SWEAT/USDT 100
1667258960170 SWEAT/USDT 0
1651724003243 XEC/USDT 1
1665187226631 XEC/USDT 0

**Comment by ttodua** [comment]
I will post a full example later, but as a quick note , instead of :
```
                orders = exchange.fetchMyTrades(symbol, since, limit)
                if len(orders):
                    since = orders[len(orders) - 1]['timestamp'] + 1
                    tData += orders
                else:
                    break
```
try : 
```
                tradeFills = exchange.fetchMyTrades(symbol, since, limit)
                if len(orders):
                    since = tradeFills[len(tradeFills ) - 1]['timestamp'] + 1
                    tData += tradeFills 
                else:
                    since  = since  + 86400 * 1000 # add one day if no result found
```
then let my know if that makes any change

**Comment by ttodua** [comment]
@markxma1 as OKX api says here:
https://www.okx.com/docs-v5/en/#rest-api-trade-get-order-history-last-7-days
you can get orders from only last 7 days. So, I assume something similar limitation for 'order-trades' too. that could be reason. to ensure CCXT works, you can make a dummy minimal trade and check if that trade is being retrieved with your function. If answer is "yes", then it means, older trades couldnt be retrieved because of being too far in the past.

**Comment by ttodua** [comment]
@markxma1 I consider this topic can be closed now, please feel free to re-open this topic if you see think is any issue in CCXT.
