### ISSUE TITLE
fetch order book without calls to load all markets?

### ISSUE THREAD

**Issue by aleqx** [ccxt/ccxt#15388]
I noticed the fetch_order_book() calls load_markets(), and the latter takes a pretty long time on some exchanges. However, loading all markets is not necessary to fetch the order book, as most exchanges provide a public API endpoint that only requires the market symbol.

If I wanted to do it in a loop this would cause an high unnecessary amount of traffic and delay. I know I could go websocket but that adds code complexity I didn't want to deal with.

Is there a clean way to fetch the order book without any prior API calls? Or maybe at least cache it?

I could follow the code to see that *depending on the exchange* there are flags I could play with, e.g. on Huobi, i noticed it checks for has[fetchCurrencies] and then options[fetchMarkets], options[types], etc, but it seems unsafe to use as config (as some are meant as capabilities, rather than config options).

It feels like some methods could have a flag to skip API calls that aren't strictly necessary.

**Comment by aleqx** [comment]
For running in a loop I notice it doesn't fetch markets again (missed that check). Although my initial point stands, i.e. it does download a heck of a chunk of unnecessary data, I guess the design principle is that it's only once per session to gain convenience.

**Comment by ttodua** [comment]
@aleqx CCXT has more flavours inside backgrounds than you might think of surface. for example, "just get the orderbook" of course doesn't need markets to be loaded per se, but ccxt is a huge framework which deals with not only "just getting the orderbook" but whole instances, sessions, other unified methods and etc... and for the library to understand and link methods and responses to the specific market/symbol, there is an unavoidable need to have the required "markets information" loaded at first, to wrap all other methods (be it orderbook or etc) inside unified responses.

However, as noticed by yourself then, "markets loading" is done only once per script's lifetime, so you might retain that instance and reuse in a loop as long as you wish.
