### ISSUE TITLE
What Async\await appeared in the method load_markets for the bitget exchange

### ISSUE THREAD

**Issue by kleninmaxim** [ccxt/ccxt#15397]
- OS: ubuntu 22.04
- Programming Language version: php8.1
- CCXT version: 2.0.65

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$exchange_class = "\\ccxt\\bitget";

$exchange = new $exchange_class(["enableRateLimit" => false]);

$exchange->load_markets();

print_r($exchange->symbols); echo PHP_EOL;
```

```shell
PHP Fatal error:  Uncaught Error: Call to undefined function ccxt\Async\await() in /home/ubuntu/work/instances-code/vendor/ccxt/ccxt/php/bitget.php:808
Stack trace:
#0 /home/ubuntu/work/instances-code/vendor/ccxt/ccxt/php/Exchange.php(1835): ccxt\bitget->fetch_markets()
#1 /home/ubuntu/work/instances-code/index.php(19): ccxt\Exchange->load_markets()
#2 {main}
  thrown in /home/ubuntu/work/instances-code/vendor/ccxt/ccxt/php/bitget.php on line 808
```

At ccxt 1.94.7 version it work correct.

**Comment by carlosmiei** [comment]
Hello @kleninmaxim, you're migrating from a pre-merge version, can you try to run `composer update` inside your directory?

**Comment by carlosmiei** [comment]
@kleninmaxim Alright, please give us some time we're debugging it now

**Comment by carlosmiei** [comment]
Hello again @kleninmaxim, it should be fixed now, can you upgrade to the latest version and try again?

**Comment by kleninmaxim** [comment]
> Hello again @kleninmaxim, it should be fixed now, can you upgrade to the latest version and try again?


Thanks! Code works without error :)
