### ISSUE TITLE
Bitmex order qty error, always goes to 0 for USDT margin trading pairs

### ISSUE THREAD

**Issue by kaiserex** [ccxt/ccxt#15394]
- OS: Ubuntu
- Programming Language version: Python 3.10.6
- CCXT version: ccxt-2.0.63

```python
params = {'execInst': 'ParticipateDoNotInitiate'}
response = self.exchange.create_order('BCH/USDT:USDT', 'limit', 'buy', 0.01, 100.75, params)
            return response['id']
```

```python
 File "/home/mr/PycharmProjects/The_Wiseman/venv/lib/python3.10/site-packages/ccxt/bitmex.py", line 1711, in create_order
    response = self.privatePostOrder(self.extend(request, params))
  File "/home/mr/PycharmProjects/The_Wiseman/venv/lib/python3.10/site-packages/ccxt/base/exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "/home/mr/PycharmProjects/The_Wiseman/venv/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2612, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/mr/PycharmProjects/The_Wiseman/venv/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2609, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/mr/PycharmProjects/The_Wiseman/venv/lib/python3.10/site-packages/ccxt/base/exchange.py", line 636, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/mr/PycharmProjects/The_Wiseman/venv/lib/python3.10/site-packages/ccxt/bitmex.py", line 2534, in handle_errors
    raise BadRequest(feedback)
ccxt.base.errors.BadRequest: bitmex {"error":{"message":"Invalid orderQty","name":"ValidationError"}}

Process finished with exit code 1

```

I can see in the ccxt bitmex class, that the amount comes in completely fine, but it gets sent as 0, after this line
```
'orderQty': float(self.amount_to_precision(symbol, amount)),  # lot size multiplied by the number of contracts

request = {'symbol': 'BCHUSDT', 'side': 'Buy', 'orderQty': 0.0, 'ordType': 'Limit', 'price': 100.75}
```          
Am i doing something wrong or the amount to precision has a bug of some sort?

**Comment by kaiserex** [comment]
Figured it out this morning. To send 0.01 BCH, you have to send 1000 as size, since 1 contract size is 0.00001 BCH

**Comment by kaiserex** [comment]
My bad on this one, but really bad from Bitmex's side as well, it introduces potential to send unwanted orders 10x or 100x the size you want when working with different exchanges, or they update contract size on their side and you get liquidated on using too much leverage.

**Comment by Dan-krm** [comment]
> Figured it out this morning. To send 0.01 BCH, you have to send 1000 as size, since 1 contract size is 0.00001 BCH

Thanks for the update, we have a convertValue helper method for bitmex to convert bitmex's number system for returning values but we might consider adding something similar like a submitValue helper method, although that might be harder to maintain.

**Comment by onasipim** [comment]
This convert_helper() function didn't actually help. I ended up using
```
size = 0.01
size = exchange.market(self.symbol)['info']['underlyingToPositionMultiplier'] * size
```
to get from 0.01 BCH to 1000

**Comment by kaiserex** [comment]
It is way too dangerous for production. I ended up fetching market data,
validating received contract value and minimum order size data and based on
that calculating how much to increase size before sending an order,
aditionally added extra checks after order is sent. In reality some day
Bitmex will adjust their contract size and all bots with harcoded
multiplication have high chance of.liquidation.

**Comment by Dan-krm** [comment]
> This convert_helper() function didn't actually help. I ended up using
> 
> ```
> size = 0.01
> size = exchange.market(self.symbol)['info']['underlyingToPositionMultiplier'] * size
> ```
> 
> to get from 0.01 BCH to 1000 contracts

The convertValue helper method is for doing the opposite conversion from 1000 to 0.01 for example. We may add a submitValue helper method taking the approach you described but there is a concern that it could cause breaking changes and hopefully if bitmex adjusts their contract size in the future it would be through a new API version

**Comment by flowerDAI** [comment]
@kaiserex hello, I use C# ,have same problems.  when I need place order 0.001BTC
var createOrder = await exchangeBitmex.CreateOrder("BTC/USDT:USDT", "market", "sell", 0.001);
show error : ccxt.BadRequest:“bitmex {"error":{"message":"Invalid orderQty","name":"ValidationError"}}”
