### ISSUE TITLE
Unified naming for order types and statuses...

### ISSUE THREAD

**Issue by tumma72** [ccxt/ccxt#15407]
Hi there,
 I am not sure this is a specific issue or rather an improvement request. The problem is the following:
- I have created a trading bot that can run multiple strategies, on multiple markets on multiple exchanges, and is using CCXT, or at least trying;
- The expectations I had was that the order type, would be standardized, possibly as Enum across the library, so one could abstract from the specific exchange and implement code that creates order or fetches them, without having to check which exchange is actually running;
- At the moment I am running with FTX, CryptoCom, Binance, Bittrex and Kraken, and it is getting pretty messy. As an example consider the following comparisons: order type "stop loss" is actually "stop" in FTX, "STOP_MARKET" in Binance, "CEALING_LIMIT" in Bittrex, "STOP_LOSS" on CryptoCom (coming up new API soon) and finally "stop-loss" in Kraken.

I hope my point is clear and makes sense, it would be great to have enums with mapping to different translation for each of the exchange, in this way one could implement strategies working independently of the underlying exchange.

- OS: MacOS, Linux Ubuntu LTS 20.04
- Programming Language version: 3.10.7
- CCXT version: 2.0.67

Thanks
ANdreaT

**Comment by carlosmiei** [comment]
Hello @tumma72 thanks a lot for your suggestion, it's hard to unify it 100% because different exchanges have slightly different order definitions, but you're completely right.

One suggestion, most of the times type=`market/limit`  + `stopPrice` inside `params` is enough to place stop-limit/stop-market orders

**Comment by samgermain** [comment]
> Hello @tumma72 thanks a lot for your suggestion, it's hard to unify it 100% because different exchanges have slightly different order definitions, but you're completely right.
> 
> One suggestion, most of the times type=`market/limit` + `stopPrice` inside `params` is enough to place stop-limit/stop-market orders

I think that we should unify the response though in `parseOrder`, so that instead of returning `'type': 'stop'` or something, we convert it to a unified type

**Comment by tumma72** [comment]
> > Hello @tumma72 thanks a lot for your suggestion, it's hard to unify it 100% because different exchanges have slightly different order definitions, but you're completely right.
> > One suggestion, most of the times type=`market/limit` + `stopPrice` inside `params` is enough to place stop-limit/stop-market orders
> 
> I think that we should unify the response though in `parseOrder`, so that instead of returning `'type': 'stop'` or something, we convert it to a unified type

Thank you both for the quick reply :-) The way I have solved the problem now is by creating two different mappings, given the data is changed from the actual exchanges, there isn’t much I can do from outside the library. The solution I have adopted now is the following:

1. Using `MultiValueEnum`, I created enums with the value I want to use in my software, each of the canonical values has a series of aliases, this is needed so that with validation on, when the order comes back from the exchange, it doesn’t break :-)
2. In my exchange wrapper, I have a translation map, and then a utility function which `translates_to_native` on the exchange, which is sending the appropriate verbs to the exchange. When it comes back with the same value it is still accepted by the enum

It’s not brilliant but works… what I would do is to create a `ccxt.base.native` with extended Enums which can automatically translate from each exchange back to ccxt dialect and the other way around. Possibly the parseOrder is the right place to apply the translations in both ways.

Ciao
ANdreaT

**Comment by tumma72** [comment]
I have moved on with this issue and I have introduced `Pydantic` for validation. By having the CCXT data structures mapped with Pydantic `BaseModel` classes it is possible to use aliases to map the internal name to the external names. As you can create a `@root_validator` for each class you can have multiple alternative values. 

I think it would be beneficial to use a library like Pydantic in CCXT but that's not working of course if you want to keep the compatibility across all 3 languages: Python, PHP and JavaScript.
