### ISSUE TITLE
Help with Binance European style-vanilla options

### ISSUE THREAD

**Issue by jokomad** [ccxt/ccxt#15406]
- OS: Windows 10 (21H2)
- Programming Language version: node.js (ver 18.10.0)
- CCXT version: 2.0.37

# Question

Does ccxt offer possibility to trade european options on binance? On mobile application i can select call, put and vol orders and time frame from 5min to 1day expiration. Supported coins are BTCUSDT, ETHUSDT ,XRPUSDT, LTCUSDT, LINKUSDT and BNBUSDT.

Also, if it is possible i can not find any working example.

Thank you.

# Attached picture from mobile...

![0b846bc180b14984b10a3e411aa7bdc3](https://user-images.githubusercontent.com/83660420/197812409-c9f7568a-38a1-4d10-a301-f485e8fea874.png)

**Comment by Dan-krm** [comment]
@jokomad You can trade options on Binance using the implicit API: https://docs.ccxt.com/en/latest/manual.html#implicit-api
Basically the implicit API is calling the endpoints directly with request parameters that are required by the exchanges API documentation. Unified options trading support is coming soon.

I've opened a pull request that adds some examples for options trading on Binance using the implicit API: #15420
Once the PR is merged the examples should be viewable here: https://github.com/ccxt/ccxt/tree/master/examples/py
