### ISSUE TITLE
Override ws client with uWebSockets.js

### ISSUE THREAD

**Issue by AndrewBarba** [ccxt/ccxt#15413]
In the base ccxt client we have the ability to override the `fetchImplementation` with a more optimized http client such as [undici](https://undici.nodejs.org/#/). I'd like a similar ability to override the default `ws` client with a more optimized library such as [uWebSockets.js](https://github.com/uNetworking/uWebSockets.js)

**Comment by sc0Vu** [comment]
Hi @AndrewBarba 

These libraries looks pretty cool. We probably need to check their codebase and discuss.
