### ISSUE TITLE
About using google cloud VM for trading bot in binance using ccxt

### ISSUE THREAD

**Issue by Mbuilder117** [ccxt/ccxt#15422]
Hi, I am going to upload my bot in google cloud VM.
But I as you know, when the connection between internet and python code cut off, the program stop and return Network Error.
I can't handle it manually because I have to go Korea Army, so I decided to use google cloud VM.

The problem is, at some period Google stops VM for maintenance and do 'migration' to another VM, and I'm worried that the enternet connection cut off in this case.

I hope there are some people who know and actually experienced about same thing.

PS. for all who think and repeat for my questions
God bless you. Thank you so much. I won't forget

**Comment by sc0Vu** [comment]
Hi @Mbuilder117 

I think this issue is not related to `ccxt` library, but I'll leave some notes.

You probably want to check `systemd` or `watchdog` on linux. If you run nodejs, you can checkout `pm2`.

**Comment by Mbuilder117** [comment]
Thanks but, I want to ask 'does the google cloud server sometimes cut off internet', not how to check it..
So can you reopen the question?

**Comment by Mbuilder117** [comment]
But they looks interesting, so i'm gonna study very soon
