### ISSUE TITLE
Bitget demo trading pairs

### ISSUE THREAD

**Issue by lockey33** [ccxt/ccxt#15431]
- OS: MAC
- Programming Language version: Python 3.9.13
- CCXT version: 2.0.77

Hello, I want to use ccxt on demo trading pairs (Bitget exchange) 

![Capture d’écran 2022-10-27 à 20 02 55](https://user-images.githubusercontent.com/100852969/198365132-c95d8e8d-1daa-42b8-8f82-879891e806ec.png)

This is the demo pair symbol on bitget interface : SBTCSUSDT_SUMCBL but i can't find this pair when I load all the market data of bitget with the "load_markets" function

How can I do ?

**Comment by carlosmiei** [comment]
Hello @lockey33, yeah currently it's not possible, but we will add it very soon

**Comment by lockey33** [comment]
@carlosmiei very good news ! thank you :)
