### ISSUE TITLE
Binance has zero methods for fetching ledger entries

### ISSUE THREAD

**Issue by roadbridgeaward** [ccxt/ccxt#15444]
Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: 
- Programming Language version: node js v14.20.1
- CCXT version: ccxt-js @1.15.38

All the methods that are associated with the fetching of ledger entries (fetchLedgerEntry(),  fetchLedger(), .. etc) are disabled or undefined for the Binance exchange.

Example from: https://github.com/ccxt/ccxt/blob/master/js/binance.js

                'fetchLedger': undefined,

I propose that the default behavior for such a well-known exchange is is to have them enabled out of the box.

**Comment by sc0Vu** [comment]
Hi @roadbridgeaward 

I think they didn't expose api to fetch ledger. We'll update once they have this api.

**Comment by roadbridgeaward** [comment]
Thanks a lot sc0Vu,

I already did a thorough review for the original Binance API documentation and I found that they already expose all of the API using which we can use in ccxt to fetch the ledger, here are some example from https://binance-docs.github.io/apidocs

o	Daily Account Snapshot (USER_DATA)
o	Asset Dividend Record (USER_DATA)
o	Query User Universal Transfer History (USER_DATA)
o	User Asset (USER_DATA)
o	Account Trade List (USER_DATA)
o	User Data Streams for Binance
o	Get Flexible Product Position (USER_DATA)
o	Get Fixed/Activity Project Position (USER_DATA)
o	Lending Account (i.e., saving) (USER_DATA)
o	Get Purchase Record (USER_DATA)
o	Get Redemption Record (USER_DATA)
o	Get Interest History (USER_DATA)
o	Get Staking Product Position(USER_DATA)
o	Get Staking History(USER_DATA)
o	Get Fiat Deposit/Withdraw History (USER_DATA)
o	Get Fiat Payments History (USER_DATA)
o	Get C2C Trade History (USER_DATA) 

So, the API does exist and is supported by Binance. Yes, this cannot be achieved in one call to the Binance API, but it can be achieved by a set of calls to the above mentioned functions / methods.
