### ISSUE TITLE
How to specify withdraw network parameter if not known?

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#15467]
- OS: Windows 10
- Programming Language version: Node.js (version 18.10.0)
- CCXT version: 2.0.90

```JavaScript
const ccxt = require('ccxt');
console.log(ccxt.version);

if (process.argv.length != 5) 
{ 
console.error('Usage: BTC Amount Address'); 
console.error('Please try again!'); 
process.exit(1);  
} 
const [nodejs, script1, coin1, amount1, address1] = process.argv; 

const withdraw1Coin(coin1, amount1, address1) = async () => 
{
    try {
        const exchange = new ccxt.binance({
            apiKey: 'My_API_Key',
            secret: 'My_Secret_Key',
            adjustForTimeDifference: true,
            defaultType: 'spot',
            recvWindow: 100000,
            verbose: false,
        })
        const transfer1 = await exchange.withdraw(coin1, amount1, address1, undefined, undefined);
        console.log(transfer1);
    }
    catch (err) {
        console.log(err);
    }
};

withdraw1Coin(coin1, amount1, address1);
```

Hello:
I want to withdraw some fund from my exchange account, but for some not well-know symbols, I don’t know their network, or one network address can be used for multiple chains.  For example, one address can be used for both ERC20 and BEP20 network.
In those cases, can I simply use only the network address, but give parameter an undefined value?

Please advise,
Thanks,

**Comment by sc0Vu** [comment]
Hi @zydjohnHotmail 

IMHO, you might want to set withdrawal network each time. In binance, when you didn't set network, they'll use the `defaultNetwork`. You can find the default network here (sapiGetCapitalConfigGetall).

**Comment by zydjohnHotmail** [comment]
Hello:
OK, I will try to set network each time, but as I see CCXT support only the following networks, right?
'networks': {
     'ERC20': 'ETH',
    'TRC20': 'TRX',
     'BEP2': 'BNB',
    'BEP20': 'BSC',
    'OMNI': 'OMNI',
    'EOS': 'EOS',
     'SPL': 'SOL',
},
What if the deposit belongs to a network not in the list, for example: XRP (Ripple) network, what I should do?

**Comment by zydjohnHotmail** [comment]
Hello:
I tried to get config from binance, but my code did not work:
const ccxt = require('ccxt')
const keys = require ('./keys.local.json');
console.log ('CCXT Version:', ccxt.version);

const exchange = new ccxt.binance ({
    'apiKey': keys.binance.apiKey,
    'secret': keys.binance.secret,
    adjustForTimeDifference: true,
    defaultType: 'spot',
    recvWindow: 100000,
    verbose: false,	
});

const configAll = async () => {
    try {
        const markets = await exchange.loadMarkets();
		const config = await exchange.sapiGetCapitalConfigGetall();
		console.log(config);
    }
    catch (err) {
        console.log(err);
    }
};

configAll();

D:\nodejs\CCXT_Binance>node BinanceConfigAll.js
CCXT Version: 2.0.90
(node:1176) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
    at binance.throwExactlyMatchedException (D:\nodejs\CCXT_Binance\node_modules\ccxt\js\base\Exchange.js:2142:19)
    at binance.handleErrors (D:\nodejs\CCXT_Binance\node_modules\ccxt\js\binance.js:5970:18)
    at D:\nodejs\CCXT_Binance\node_modules\ccxt\js\base\Exchange.js:598:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (D:\nodejs\CCXT_Binance\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async binance.fetch2 (D:\nodejs\CCXT_Binance\node_modules\ccxt\js\base\Exchange.js:1803:16)
    at async binance.request (D:\nodejs\CCXT_Binance\node_modules\ccxt\js\binance.js:5999:26)
    at async binance.fetchCurrencies (D:\nodejs\CCXT_Binance\node_modules\ccxt\js\binance.js:1310:26)
    at async binance.loadMarketsHelper (D:\nodejs\CCXT_Binance\node_modules\ccxt\js\base\Exchange.js:624:26)
    at async configAll (D:\nodejs\CCXT_Binance\BinanceConfigAll.js:16:25) {
  constructor: [class InvalidNonce extends NetworkError]
}

How can I fix this issue, it has been there for a long time, sometimes with this exchange, other times, with another exchange.
Please advise!
Thanks

**Comment by sc0Vu** [comment]
Hi @zydjohnHotmail

Have you checked your computer time? Looks like the timestamp went too fast (`Timestamp for this request was 1000ms ahead of the server's time.`).

**Comment by zydjohnHotmail** [comment]
Hello:
Actually, I found one solution, have to setup Windows time service to start automatically, then it works well after the PC clock is sync with NTP time server.
