### ISSUE TITLE
New Exchange: alpaca.markets

### ISSUE THREAD

**Issue by vensilver** [ccxt/ccxt#15463]
[please support alpaca.markets in ccxt
](https://alpaca.markets/)

**Comment by carlosmiei** [comment]
Hello @vensilver it's already supported 🙂 
![image](https://user-images.githubusercontent.com/43336371/198872382-7c746c8a-1b12-488e-9a6c-5e7dc6ad2d26.png)

**Comment by vensilver** [comment]
is it just for crypto or even stocks?

**Comment by carlosmiei** [comment]
@vensilver currently crypto only

**Comment by flieks** [comment]
Is there any exchange supported by ccxt to trade stocks?
