### ISSUE TITLE
( 2 of 2) Binance has zero methods for fetching ledger entries

### ISSUE THREAD

**Issue by roadbridgeaward** [ccxt/ccxt#15479]
- OS:
- Programming Language version: node js v14.20.1
- CCXT version: ccxt-js @1.15.38

Reference to issue #15444 ( https://github.com/ccxt/ccxt/issues/15444 ), I mentioned in that issue that Binance ledger features are mentioned in ccxt source code as:

            'fetchLedger': undefined,
(from https://github.com/ccxt/ccxt/blob/master/js/binance.js )

That issue was closed based on the fact that the native Binance API themselves does not support the ledger functionality and hence ccxt does not support them, which made sense at that time.

After closing that issue (thanks to sc0Vu), I did a thorough review for the original Binance API documentation and I found that they already expose all of the API using which we can use in ccxt to fetch the ledger, here are some example ( from https://binance-docs.github.io/apidocs ) 

o Daily Account Snapshot (USER_DATA)
o Asset Dividend Record (USER_DATA)
o Query User Universal Transfer History (USER_DATA)
o User Asset (USER_DATA)
o Account Trade List (USER_DATA)
o User Data Streams for Binance
o Get Flexible Product Position (USER_DATA)
o Get Fixed/Activity Project Position (USER_DATA)
o Lending Account (i.e., saving) (USER_DATA)
o Get Purchase Record (USER_DATA)
o Get Redemption Record (USER_DATA)
o Get Interest History (USER_DATA)
o Get Staking Product Position(USER_DATA)
o Get Staking History(USER_DATA)
o Get Fiat Deposit/Withdraw History (USER_DATA)
o Get Fiat Payments History (USER_DATA)
o Get C2C Trade History (USER_DATA)

So, the API does exist and is supported by Binance. Yes, this cannot be achieved in one call to the Binance API, but it can be achieved by a set of calls to the above mentioned functions / methods.

thoughts on the same are welcomed and please let me if I misunderstood something?

5 Nov 2022: Mentioning @sc0Vu 

Thank you so much.

**Comment by samgermain** [comment]
@kroitor @carlosmiei @frosty00 

What are your thoughts, it looks like `fetchLedger` can be implemented, but only via multiple api calls

**Comment by carlosmiei** [comment]
@roadbridgeaward Binance supports fetchLedger now.

**Comment by roadbridgeaward** [comment]
> @roadbridgeaward Binance supports fetchLedger now.

This is super good news, thank you so much @carlosmiei
