### ISSUE TITLE
BitGet exchange.timeframes incomplete

### ISSUE THREAD

**Issue by dawadam** [ccxt/ccxt#15483]
Hi,
BitGet **timeframes** parametter seem incomplete, result doesn't include available time frames on documentation :

https://bitgetlimited.github.io/apidoc/en/spot/#get-candle-data

Only include : 1w  1d 12h 4h 1h 30m 15m 5m 1m

**Comment by carlosmiei** [comment]
Hello again @dawadam, will be added alongside the fix to the problem you reported earlier. Thanks!
