### ISSUE TITLE
BitGet fetchOHLCV

### ISSUE THREAD

**Issue by dawadam** [ccxt/ccxt#15482]
Hi,
When use fetchOHLCV in **bitget** exchange, in 1 week, request use _7day_ **period parameter value**.
It must to be _1week_ value.

Exemple :

```
const exchange = new ccxt.bitget()
const symbol = 'BTC/USDT'
const timeFrame = '1w'
const candleList = await exchange.fetchOHLCV(symbol, timeFrame)
```

request :

`https://api.bitget.com/api/spot/v1/market/candles?symbol=BTCUSDC_SPBL&period=7day&limit=100`

must be :

``https://api.bitget.com/api/spot/v1/market/candles?symbol=BTCUSDC_SPBL&period=1week&limit=100``

**Comment by carlosmiei** [comment]
Hey @dawadam, thanks for reporting it we will fix it asap
