### ISSUE TITLE
FTX 'askVolume' / 'bidVolume' = None

### ISSUE THREAD

**Issue by ProStrike-hub** [ccxt/ccxt#15484]
- Programming Language version: php
- CCXT version: latest

Hello, When using `fetch_ticker` at FTX `'askVolume'` and `'bidVolume'` returned are set at `'None'`. 
The price is returned, fortunately. 

Could you please fix/add the volume?
Thanks in advance.

**Comment by carlosmiei** [comment]
Hello @ProStrike-hub ,

Those fields are `None` because ftx does not provide them through the API: 
https://docs.ftx.com/#markets

**Comment by ProStrike-hub** [comment]
Hello @carlosmiei 

Alright. 
Is there another way of collecting the volumes available (aka order book) to determine at which price to set limit orders? Thanks.

**Comment by samgermain** [comment]
closing as ftx is delisted now

-----------------------

You can always check the information inside `info` though, or check the response of other methods on the api to know if there's somewhere else you can get information for something
