### ISSUE TITLE
Bkex may freeze your account if you make some profit

### ISSUE THREAD

**Issue by lukasgor** [ccxt/ccxt#15486]
Hello everyone, at the beginning I'd like to thank the developers of this great library, you are doing an amazing job!

I would like to warn everyone about bkex exchange, I was running my trading algorithm there and after it made some profit they have frozen my account 😞 I'm running my trading algo on 10+ different exchanges without any issues.

Here's my conversation with their customer support:

<img width="799" alt="Screenshot 2022-10-31 at 11 11 29" src="https://user-images.githubusercontent.com/7783613/198997337-0c91a71b-68cd-4fa0-8778-5f2b8af04a28.png">

<img width="811" alt="Screenshot 2022-10-31 at 11 11 41" src="https://user-images.githubusercontent.com/7783613/198997372-b3f305df-c463-4694-93bc-d5c5373e3e54.png">

<img width="801" alt="Screenshot 2022-10-31 at 11 11 52" src="https://user-images.githubusercontent.com/7783613/198997395-9bc486b0-1639-45bb-913e-60f406c6dba6.png">

<img width="808" alt="Screenshot 2022-10-31 at 11 12 03" src="https://user-images.githubusercontent.com/7783613/198997440-a672d230-c550-49cc-8a4a-df770a4bf6a0.png">

<img width="796" alt="Screenshot 2022-10-31 at 11 12 11" src="https://user-images.githubusercontent.com/7783613/198997480-1d57aa86-34e5-49d3-a47a-7a0354d28bd1.png">

Conversation attachment:
<img width="596" alt="Screenshot 2022-10-31 at 11 12 31" src="https://user-images.githubusercontent.com/7783613/198997509-14f46c46-838a-4766-9f5c-e10b4bddd4e7.png">

I strongly discourage using this exchange.

**Comment by zydjohnHotmail** [comment]
Hello:
I have tried to chat with the customer service, for 2 agents. They both insist that the rules to be obeded.  And I check the rules: https://bkex.zendesk.com/hc/en-us/articles/4403752763161-Standard-of-Unusual-Transactions
The most important issue seems to be this:
 Excessive transactions: too large trading volume in one day;
And I asked the support stuff to give me any definite standard for "too large trading volume", one agent "Gina" said: the right to explain this is reserved with bkex.
Therefore, I think this exchange really sucks!
Please do NOT use this exchange!

**Comment by frosty00** [comment]
bkex has since been delisted

**Comment by frosty00** [comment]
#19329
