### ISSUE TITLE
Will CCXT support typings in Python codes?

### ISSUE THREAD

**Issue by MinsungKim-BlockCrafters** [ccxt/ccxt#15481]
Hello.

I am a quant engineer who is using CCXT as data feed and also interested in static typing in Python. I can see currently CCXT is not doing any of typing support in Python, probably because CCXT is being developed in Javascript and non-JS codes are transpiled from it.

So here are my questions;

1. Will CCXT support typings in Python codes?
2. Does CCXT currently accept any stub files contribution?

If the maintainers of CCXT don't have any plans to support typings now, I think at least some sort of simple stub files contribution will be nice. Since most of CCXT methods are building some unified data structure, it would be nice to provide type hints.

Thanks for reading this.

**Comment by carlosmiei** [comment]
Hello @MinsungKim-BlockCrafters 
We appreciate your suggestion and will be taken it into account for sure. Yes currently ccxt is developed and then transpiled to Python so at the moment we can't infer types and for that reason is not possible to add types at "transpile" time. 

However, this will change soon because we intend to migrate to Typescript, allowing us to type everything and access those types during the transpilation process.

Regarding your second question, yes contributions are always very welcome.

**Comment by MinsungKim-BlockCrafters** [comment]
@carlosmiei I was trying to make some type hint commits for CCXT and I realized CCXT is supporting Python 3.5+ (according to documentation); Do you have any plan to support Python 3.7+ instead of 3.5.3+? The reasons why I am asking this is because;

1. Python ~3.6 is [deprecated.](https://endoflife.date/python) (3.7 will be deprecated in several months too)
2. In Python 3.5, you have to use type comments to support type hints. For `.pyi` files it is not a problem, but I think it is good to define common typing structures like [Order Structure](https://docs.ccxt.com/en/latest/manual.html#order-structure) etc, and those have to be in normal python files.

**Comment by MinsungKim-BlockCrafters** [comment]
I tried some work but seems mypy and typeshed module does not support 3.5, and probably with this reason the static analysis does not work well. https://github.com/python/typeshed/issues/9119

**Comment by MinsungKim-BlockCrafters** [comment]
@carlosmiei I see, I will not make any breaking change on Python 3.5. Fortunately I resolved the static analysis issue on Python 3.5 (probably because I mixed different version of typeshed in same mypy cache), so I will make some PRs (but, if you don't like it then feel free to reject)

**Comment by carlosmiei** [comment]
@MinsungKim-BlockCrafters sure, after we migrate to typescript probably we will be able to automatically generate these types, but until then I think it's a good alternative

**Comment by frosty00** [comment]
we have started to add type hints in python
