### ISSUE TITLE
Bittrex withdraw currency TypeError

### ISSUE THREAD

**Issue by oswaldonfire** [ccxt/ccxt#1549]
Hi, 

I am seeing a new TypeError when calling the Bittrex withdraw() method using the latest version of ccxt.

Environment is Ubuntu 16.04, Python 3.5.2, ccxt 1.10.888.

Stack trace:
```
TypeError: argument of type 'NoneType' is not iterable
  File "ubuntu/trading.py", line 374, in Withdraw
    withdrawal = exch.withdraw(symbol, amount, address, options)
  File "ccxt/bittrex.py", line 607, in withdraw
    if 'result' in response:
```

stdout with .verbose enabled:
```
GET https://bittrex.com/api/v1.1/account/withdraw?currency=NEO&quantity=0.244&address=AeLBkT9Hza9NLXaVRfrwY9k8AzQHke9oSG&nonce=1517144620&apikey=xxxx
Request: {'Accept-Encoding': 'gzip, deflate', 'apisign': '2911efc72bc8af66a2f204d83ddf049be083e3cd2de0dde4d7bd3459cde4f6f1138e38abdc8a31be1cbccd366214b1dc014ef406a6e4d5a79fbf7cce039dd9bc', 'User-Agent': 'python-requests/2.18.4'} None
```

Minimal example to reproduce:
```
exch = ccxt.bittrex({ 'apiKey' : 'xxx', 'secret' : 'xxx', })
withdrawal = exch.withdraw('NEO', 0.229, 'AeLBkT9Hza9NLXaVRfrwY9k8AzQHke9oSG', {})
```

**Comment by wannesdemaeght** [comment]
Neo needs to be sent in whole numbers. Also account for the withdrawal fee.

**Comment by oswaldonfire** [comment]
@wannesdemaeght thank you - I've checked and even trying to send an amount sufficient for a minimum of 1.0 NEO after fees fails. However, it led me to discover the real cause of this issue, that the NEO wallet is currently disabled on Bittrex (https://support.bittrex.com/hc/en-us/articles/360000203372). This is my mistake as I should have checked that possibility before posting. 

It would be nice to see a more verbose error if possible - maybe this could be raised as a ```ccxt.ExchangeError``` or ```ccxt.ExchangeNotAvailable``` ?

Along those lines, does anyone have a programmatic way to check whether an exchange's wallet (deposits or withdrawals or both) is online? I imagine this might not be possible in a unified way.

Anyways, thank you to all who contribute towards making this a great library.

**Comment by kroitor** [comment]
You're using the old withdraw signature:

```Python
withdraw (code, amount, address, params = {})
```

↑ this has been changed to this ↓

```Python
withdraw (code, amount, address, tag=None, params={})
```

It was announced here:
https://github.com/ccxt/ccxt/issues/1348

So you should change your code from this

```Python
exch = ccxt.bittrex({ 'apiKey' : 'xxx', 'secret' : 'xxx', })
withdrawal = exch.withdraw('NEO', 0.229, 'AeLBkT9Hza9NLXaVRfrwY9k8AzQHke9oSG', {})
```

To this:

```Python
exch = ccxt.bittrex({ 'apiKey' : 'xxx', 'secret' : 'xxx', })
code = 'NEO'
amount = 12345  # ←------------ your amount here
address = '54321'  # ←--------- your address
tag = None  # ←---------------- your tag
withdrawal = exch.withdraw(code, amount, address, tag, {})
```

See also:

```
import ccxt
from pprint import pprint
b = ccxt.bittrex()
b.load_markets()
pprint(b.currencies['NEO'])
```

Let us know if it doesn't help.

**Comment by oswaldonfire** [comment]
Everything is working perfectly including the market status checks, thank you!
