### ISSUE TITLE
Gate.io Batch Orders

### ISSUE THREAD

**Issue by Tongoko** [ccxt/ccxt#15509]
- OS: Windows 10
- Programming Language version: Python 3.10
- CCXT version: 2.0.68

Just a question: Does CCXT support to place batch orders for Gate.io? If so how? Thanks!

**Comment by sc0Vu** [comment]
Hi @Tongoko 

For now, you can call batch order with implicit api, eg, `spotPostBatchOrders` or `spotPostCancelBatchOrders`.

**Comment by samgermain** [comment]
> * OS: Windows 10
> 
>     * Programming Language version: Python 3.10
> 
>     * CCXT version: 2.0.68
> 
> 
> Just a question: Does CCXT support to place batch orders for Gate.io? If so how? Thanks!

Only in spot/margin, and only using the [implicit api](https://docs.ccxt.com/en/latest/manual.html#implicit-api) methods `spotPostBatchOrders` and `spotPostCancelBatchOrders`. There is no unified method for batch orders. 

-------------------------------------

```JavaScript
const ccxt = require ('./ccxt');
const keys = require ('./keys.local.json');

async function main () {

    const exchange = new ccxt.gateio (keys.gateio);
    await exchange.loadMarkets ();

    const ada = exchange.market ('ADA/USDT');
    const xrp = exchange.market ('XRP/USDT')

    orders = await exchange.privateSpotPostBatchOrders (
        [
            {
                text: "t-123456",
                currency_pair: ada['id'],
                type: "limit",
                account: "spot",
                side: "buy",
                amount: "3",
                price: "0.4"
            },
            {
                text: "t-123456",
                currency_pair: xrp['id'],
                type: "limit",
                account: "spot",
                side: "buy",
                amount: "3",
                price: "0.47"
            }
        ]
    );

    console.log (orders);

};


main ();
```

-------------------------------------

# Gateio docs

![](https://i.imgur.com/2xaDryD.png)
![](https://i.imgur.com/tIfVe1n.png)
![](https://i.imgur.com/z4a748r.png)

![](https://i.imgur.com/4r56mNy.png)

**Comment by Tongoko** [comment]
Thanks a lot for the answers. Worked flawlessly!
