### ISSUE TITLE
ExchangeError: okx  "Trigger orders are not available in buy/sell mode for futures and perpetual swaps"

### ISSUE THREAD

**Issue by Nitrix321** [ccxt/ccxt#15513]
Hello, I am trying to create a simple stop market or stop limit order on OKX.  When the program should place the order theres an Echange Error Message that Trigger orders are not available there. 
So I don't know what I am doing wrong here. I never had such a problem to create a stop order on other exchanges.  

Perhaps someone can explain me how to create a stop order(limit or market) below market price on okx. 

- OS: Windows 10
- Programming Language version: Python Spyder 3.9
- CCXT version: 1.92.81

```
symbol = 'ETH/USDT:USDT'
pos_size = 1

#in this example I was in a LONG Position, entry price around 1600$, and I wanted to place a stop market order at 1500$

okx.create_stop_market_order(symbol, side='sell', amount=pos_size, stopPrice='1500')

```
fetch Request: okx POST https://www.okx.com/api/v5/trade/order-algo RequestHeaders: {'OK-ACCESS-KEY': 'xxxxxx', 'OK-ACCESS-PASSPHRASE': 'xxxxx', 'OK-ACCESS-TIMESTAMP': '2022-11-01T11:21:29.172Z', 'Content-Type': 'application/json', 'OK-ACCESS-SIGN': 'qV87i8K1736uni1KZZ21yAOnu+dXEdICzCNDwCjZsv4=', 'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"instId":"ETH-USDT-SWAP","side":"sell","ordType":"trigger","sz":"1","tdMode":"cross","triggerPx":"1500","orderPx":"-1","clOrdId":"e847386590ce4dBC6d7cfe5189e603e1"}

fetch Response: okx POST https://www.okx.com/api/v5/trade/order-algo 200 ResponseHeaders: {'Date': 'Tue, 01 Nov 2022 11:21:29 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': 'locale=en-US; Max-Age=604800; Expires=Tue, 08-Nov-2022 11:21:29 GMT; Path=/, locale=en-US; Max-Age=604800; Expires=Tue, 08-Nov-2022 11:21:29 GMT; Path=/, __cf_bm=tlWxeGiszX_AKFyvO_qKFMGoGKN6lv...gLOjvvBYqE-1667301689-0-AWEQ9dZlTMqOYM3Py/qKQ8yMJuzgX1337m9LagWOh5IFw9BP36zlU/WuWAFgICF5Vog3EAvw6Nqnb77U9STFbcg=; path=/; expires=Tue, 01-Nov-22 11:51:29 GMT; domain=.okx.com; HttpOnly; Secure; SameSite=None', 'X-BrokerID': '0', 'Strict-Transport-Security': 'max-age=63072000; includeSubdomains; preload', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '76343f455be691ed-FRA', 'Content-Encoding': 'gzip'} ResponseBody: {"code":"1","data":[{"algoId":"","clOrdId":"","sCode":"51298","sMsg":"Trigger orders are not available in buy/sell mode for futures and perpetual swaps"}],"msg":""}
Traceback (most recent call last):
```

**Comment by noel45** [comment]
This is an a rejection coming from the exchange. It seems they don't accept trigger orders on SWAPs in net mode.

You can check that page :
https://www.okx.com/docs-v5/log_en/#2021-10-19
**Trigger orders are not available in the net mode of futures and perpetual swaps**

**Comment by Nitrix321** [comment]
Hi @noel45,

ok that means I can not place a stop order on this exchange? Or is there another way placing a stop order?
Without stop order it's not usable for me :(.

**Comment by ZetZ1** [comment]
No solution, right?... months working and now i need change of exchange.....................

**Comment by ttodua** [comment]
I'll review this tomorrow and post a reply.

**Comment by ZetZ1** [comment]
i find a simple solution, sorry for my horrible english

solution: change to hedge mode manually from exchange (i dont know if is possible change from okx intantation, is possible?) 

sl_id = exchange.create_stop_market_order(ticker, 'sell', position_contracts,
                        stopPrice = signal_data['SL'], params={'posSide': 'short'}) <——————this s a stop loss for a short position. posside for choose long or short direction of position. and use sell for sell the short or buy for buy short contracts. For long

long or short as parameter for choose direction. Sell or buy for buy contracts or sell contracts. Simply

**Comment by ttodua** [comment]
anyone reading this, you can use i.e. `.createOrder ('BTC/USDT:USDT', 'market', 'sell', 1, undefined, {'stopLossPrice': 60123, 'hedged':true });`   <-- notice the 'hedged' param to tell the ccxt which mode you trade.
