### ISSUE TITLE
How to add a implicit api method to ccxt.browser.js

### ISSUE THREAD

**Issue by 583** [ccxt/ccxt#15519]
Hi, 

bybit api: https://bybit-exchange.github.io/docs/zh-my/derivativesV3/contract/#t-contract_getrealtimeorder
I add 'contract/v3/private/order/unfilled-orders': 1 to ccxt.browser.js and bybit.js

![image](https://user-images.githubusercontent.com/18026534/199468359-69eda896-3761-4a71-b110-5ee2e1dd0a20.png)

then I call exchange.privateGetContractV3PrivateOrderUnfilledOrders

But it still throw

TypeError: exchange.privateGetContractV3PrivateOrderUnfilledOrders is not a function

It's there any error？

**Comment by carlosmiei** [comment]
Hello you're calling the correct function, but to access it in python you would need to transpile the code or manually add it to the python file.

But don't worry we will add the missing endpoint asap so that it will be available out of the box.


Thanks for reporting it!

**Comment by 583** [comment]
> 

I calling it in a html web page by require ccxt.browser.js.  Thanks

**Comment by 583** [comment]
> > 
> 
> 


> Hello you're calling the correct function, but to access it in python you would need to transpile the code or manually add it to the python file.
> 
> But don't worry we will add the missing endpoint asap so that it will be available out of the box.
> 
> Thanks for reporting it!

https://github.com/ccxt/ccxt/issues/15519#issuecomment-1300033589

**Comment by 583** [comment]
> Hello you're calling the correct function, but to access it in python you would need to transpile the code or manually add it to the python file.
> 
> But don't worry we will add the missing endpoint asap so that it will be available out of the box.
> 
> Thanks for reporting it!

I calling it in html web page by require ccxt.browser.js, thanks.

**Comment by carlosmiei** [comment]
Sorry @583 I thought you were using the Python version, in that case yes it should work

**Comment by 583** [comment]
> Sorry @583 I thought you were using the Python version, in that case yes it should work
But it not work really, return privateGetContractV3PrivateOrderUnfilledOrders is not a function
