### ISSUE TITLE
Binance missing trading pairs

### ISSUE THREAD

**Issue by J4k3j4k3** [ccxt/ccxt#15517]
Hi,

Just wondering if anything can be done about missing Binance trading pairs? I can see for instance that Binance has a 1INCH/BTC trading pair: https://www.binance.com/en/trade/1INCH_BTC?theme=dark&type=spot

However this throws the error "ccxt.base.errors.BadSymbol: binance does not have market symbol 1INCHBTC"

I can see why too, the symbol is missing from https://testnet.binance.vision/api/v3/exchangeInfo

Just wondering if there's any way to run these pairs? Other examples are ANKR/BTC, COMP/BTC, ICP/BTC, LPT/BTC, NEO/BTC and ONT/BTC

Thanks!

**Comment by J4k3j4k3** [comment]
On further investigation, these symbols are missing from the Binance test API. Happy to close this as it is not a ccxt defect, but any idea how I can run any of these pairs in sandbox mode without live trading?

**Comment by carlosmiei** [comment]
Hello @J4k3j4k3, yeah I don't think that is possible ccxt is only a middleware, so it just "formats" the requests and "parsed" the responses, we can't emulate our own sandbox.
