### ISSUE TITLE
Cryptocom : parse_ticker not working properly after latest exchange update

### ISSUE THREAD

**Issue by noel45** [ccxt/ccxt#15528]
- OS: Windows
- Programming Language version: Python 3.9
- CCXT version: 2.1.9
- Exchange : cryptocom

In exchange cryptocom.py, method parse_ticker always return "None" values after latest exchange upgrade.
Example:
{'symbol': 'HERO/USDT', 'timestamp': None, 'datetime': None, 'high': None, 'low': None, 'bid': None, 'bidVolume': None, 'ask': None, 'askVolume': None, 'vwap': None, 'open': None, 'close': None, 'last': None, 'previousClose': None, 'change': None, 'percentage': None, 'average': None, 'baseVolume': None, 'quoteVolume': None, 'info': [{'i': 'HERO_USDT', 'h': '0.0045415', 'l': '0.0042208', 'a': '0.0043777', 'v': '1220700.0', 'vv': '5405.83', 'c': '-0.0180', 'b': '0.0043126', 'k': '0.0043791', 't': '1667405476074'}]}

The reason is that the ticker dictionary is now returned encapsulated in an array : 
**[** {'i': 'HERO_USDT', 'h': '0.0045415', 'l': '0.0042208', 'a': '0.0043777', 'v': '1220700.0', 'vv': '5405.83', 'c': '-0.0180', 'b': '0.0043126', 'k': '0.0043791', 't': '1667405475907'} **]**

Please help to fix, thank you.

**Comment by carlosmiei** [comment]
Hello @noel45, yeah apparently cryptocom changed its API, we will fix it asap. Thanks for letting us know!
