### ISSUE TITLE
PHP: Is it correct array for verbose?

### ISSUE THREAD

**Issue by LeonLegion** [ccxt/ccxt#1552]
[$verbose_headers](https://github.com/ccxt/ccxt/blob/master/php/Exchange.php#L855) used for verbose after request, but may be must use [$response_headers](https://github.com/ccxt/ccxt/blob/master/php/Exchange.php#L822) because $verbose_headers already printed for [request](https://github.com/ccxt/ccxt/blob/master/php/Exchange.php#L803).
Can i fix it?

**Comment by kroitor** [comment]
@LeonLegion sure! We welcome all contributions! Thx!

**Comment by kroitor** [comment]
@LeonLegion I hope you don't mind if I close this for now, feel free to reopen it if needed. We will be waiting for a commit from you, or we will add this in one of the upcoming releases.
