### ISSUE TITLE
How to update CCXT? 

### ISSUE THREAD

**Issue by Nitrix321** [ccxt/ccxt#15531]
I hope someone can help me with my problem, please:-)! I am searching now for over 2 days but I can't find an answer.
Actually my CCXT Version is 1.92.81, but how can I update it to the latest Version or at least 1.95+ ? 

- OS: Windows 10 
- Programming Language version: 3.9
- CCXT version: 1.92.81

**Comment by carlosmiei** [comment]
Hello @Nitrix321,

have you tried to run `pip install ccxt --upgrade´ ?

**Comment by Nitrix321** [comment]
Hello @carlosmiei,

thank u so much, that solved my problem :-). Why didn't google tell me that? 

print('CCXT Pro Version:', ccxtpro.__version__)
print('CCXT Version:', ccxt.__version__)

CCXT Pro Version: 2.1.13
CCXT Version: 2.1.13

Did I understand that correctly, that in CCXT now All of the CCXT Pro Websocket functionality is retained?
So I it's ok to use only the "normal" CCXT Module? It's the same now , so to speak, CCXT and CCXT.PRO, right?

**Comment by carlosmiei** [comment]
@Nitrix321 yes `ccxt.pro` is now merged into ccxt, you can see how to use it here: https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro/py
