### ISSUE TITLE
Are there methods to set or get Multi-Assets mode for Binance

### ISSUE THREAD

**Issue by sirui0112** [ccxt/ccxt#15537]
- OS: Windows 10
- Programming Language version: Python 3.9.12
- CCXT version: 2.0.25

Hi, I read on Binance API documents that it is possible to change or get current multi-assets mode for USD-M futures: https://binance-docs.github.io/apidocs/futures/en/#change-multi-assets-mode-trade 
Wondering if there are corresponding methods implemented for both operations, thanks.

**Comment by carlosmiei** [comment]
Hello @sirui0112,

You can always call them using the implicit API.

Example:
```Python

get_multiasset = await binance.fapiPrivateGetMultiAssetsMargin()

params = {
    "multiAssetsMargin": "true" # or false
}

set_multiasset = await binance.fapiPrivatePostMultiAssetsMargin()
```

**Comment by carlosmiei** [comment]
Hello @sirui0112,

You can always call them using the implicit API.

Example:
```Python

get_multiasset = await binance.fapiPrivateGetMultiAssetsMargin()

params = {
    "multiAssetsMargin": "true" # or false
}

set_multiasset = await binance.fapiPrivatePostMultiAssetsMargin()
```

**Comment by sirui0112** [comment]
Thanks @carlosmiei for the reply. Both methods are working fine. 
May I know why I am unable to view the methods from the library?

**Comment by carlosmiei** [comment]
Hello @sirui0112,  you're welcome
These are not unified methods hence they're not documented, here are making direct API calls to binance API, that's what we call `Implicit API`, you can read more about it here: https://docs.ccxt.com/en/latest/manual.html#implicit-api-methods

**Comment by sirui0112** [comment]
That helps, thanks @carlosmiei. Closing the issue now.
