### ISSUE TITLE
cryptocom wrong precision amount

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#15546]
After last crypto.com maintenance there are problems with amount precision on spot wallets.
https://api.crypto.com/v2/public/get-instruments
for example SHIB/USDT
`{"instrument_name":"SHIB_USDT","quote_currency":"USDT","base_currency":"SHIB","price_decimals":9,"quantity_decimals":0,"margin_trading_enabled":true,"margin_trading_enabled_5x":true,"margin_trading_enabled_10x":true,"max_quantity":"10000000000","min_quantity":"10000","max_price":"0.1","min_price":"0.000000001","last_update_date":1667263094856},`
Tick size for this pair is `10000` but ccxt parse `quantity_decimals` and we have precision amount `1`

As I tested `min_quantity` in their API response is always give right tick size for each pair. Should we implement amount precision base d on `min_quantity` not `quantity_decimals`?

**Comment by ndubel** [comment]
https://github.com/ccxt/ccxt/pull/15791

**Comment by oliviera9** [comment]
I had a conversation with Crypto.com support and this is an extract:
```
> That holds in general for every instrument in the exchange. I need to place an order that is > min_quantity and a multiple of quantity_tick_size

< That is correct this is the one that you should be checking, our Te4ch team has confirmed it.
```
