### ISSUE TITLE
Kucoin testnet not working for ccxt version 2.1.14

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#15540]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Window 10 Pro (21H2)
- Programming Language version: Node.js (version 19.0.0)
- CCXT version: 2.1.14

```
const ccxt = require('ccxt');
console.log(ccxt.version);

if (process.argv.length != 3) 
{
	console.error('Usage: BTC/USDT');
	console.error('Please try again!');
	process.exit(1);
}
const [nodejs, script1, pair1] = process.argv;

let exchange = new ccxt.kucoin
({
	defaultType: 'spot',
	'adjustForTimeDifference': true,
	'verbose': true,
});

async function getPair1Orderbook(pair1)
{
try 
{
	exchange.setSandboxMode(true);
	const l1_orderbook = await exchange.fetchOrderBook(pair1);
	console.log(l1_orderbook);
}
catch (err) 
{
	console.error(err)
}
};
getPair1Orderbook(pair1);

```

```

D:\nodejs\CCXT_Sandbox>node test_kucoin_pair1OrderBook.js BTC/USDT
2.1.14
fetch Request:
 kucoin GET https://openapi-sandbox.kucoin.com/api/v1/currencies
RequestHeaders:
 {}
RequestBody:
 undefined

(node:2732) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
handleRestResponse:
 kucoin GET https://openapi-sandbox.kucoin.com/api/v1/currencies 200 OK
ResponseHeaders:
 {
  'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '764438d02b4b11b3-BCN',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json',
  Date: 'Thu, 03 Nov 2022 09:53:17 GMT',
  Expires: '0',
  Server: 'cloudflare',
  'Set-Cookie': '60993a88a1da4a4caf34c7c8a72657a8=WyIzMzc4MDk4MjQ5Il0; Expires=Thu, 03-Nov-22 10:13:16 GMT; Domain=openapi-sandbox.kucoin.com; Path=/; Secure; HttpOnly, __cfruid=4e860c5c7df399aa367bcd96b5eadb0f2ee645b1-1667469197; path=/; domain=.kucoin.com; HttpOnly; Secure; SameSite=None',
  'Transfer-Encoding': 'chunked',
  Vary: 'Accept-Encoding',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'X-Xss-Protection': '1; mode=block'
}
ResponseBody:
 {"code":"200000","data": ...]
 
fetch Request:
 kucoin GET https://openapi-sandbox.kucoin.com/api/v2/symbols
RequestHeaders:
 {}
RequestBody:
 undefined

handleRestResponse:
 kucoin GET https://openapi-sandbox.kucoin.com/api/v2/symbols 404 Not Found
ResponseHeaders:
 {
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '764438d25f3711b3-BCN',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json',
  Date: 'Thu, 03 Nov 2022 09:53:17 GMT',
  Server: 'cloudflare',
  'Set-Cookie': '60993a88a1da4a4caf34c7c8a72657a8=WyIxMDY2MDE5NTcxIl0; Expires=Thu, 03-Nov-22 10:13:17 GMT; Domain=openapi-sandbox.kucoin.com; Path=/; Secure; HttpOnly, __cfruid=4e860c5c7df399aa367bcd96b5eadb0f2ee645b1-1667469197; path=/; domain=.kucoin.com; HttpOnly; Secure; SameSite=None',
  'Transfer-Encoding': 'chunked'
}
ResponseBody:
 {"code":"404","msg":"Not Found","retry":false,"success":false}

NotSupported: kucoin Not Found
    at kucoin.throwExactlyMatchedException (D:\nodejs\CCXT_Sandbox\node_modules\ccxt\js\base\Exchange.js:2150:19)
    at kucoin.handleErrors (D:\nodejs\CCXT_Sandbox\node_modules\ccxt\js\kucoin.js:3271:14)
    at D:\nodejs\CCXT_Sandbox\node_modules\ccxt\js\base\Exchange.js:598:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (D:\nodejs\CCXT_Sandbox\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async kucoin.fetch2 (D:\nodejs\CCXT_Sandbox\node_modules\ccxt\js\base\Exchange.js:1811:16)
    at async kucoin.request (D:\nodejs\CCXT_Sandbox\node_modules\ccxt\js\base\Exchange.js:1815:16)
    at async kucoin.fetchMarkets (D:\nodejs\CCXT_Sandbox\node_modules\ccxt\js\kucoin.js:551:26)
    at async kucoin.loadMarketsHelper (D:\nodejs\CCXT_Sandbox\node_modules\ccxt\js\base\Exchange.js:626:25)
    at async kucoin.fetchOrderBook (D:\nodejs\CCXT_Sandbox\node_modules\ccxt\js\kucoin.js:1189:9) {
  constructor: [class NotSupported extends ExchangeError]
}

D:\nodejs\CCXT_Sandbox>
```

Hello:
I have just created my API keys for testnet on Kucoin exchange, and want to test if I can load one currency pair order book, like: BTC/USDT.
The same code works on production net, but on testnet, I got error message like above, as I checked, the URL: https://openapi-sandbox.kucoin.com/api/v2/symbols
does NOT exist.
Please check to make sure their documents are changed or some other issue to prevent testnet on kucoin not working.
Thanks,

**Comment by carlosmiei** [comment]
Hello @zydjohnHotmail, thanks for reporting it will be fixed asap!

**Comment by zydjohnHotmail** [comment]
D:\nodejs\CCXT_Sandbox>node  test_kucoin_pair1OrderBook.js BTC/USDT
2.1.18
fetch Request:
 kucoin GET https://openapi-sandbox.kucoin.com/api/v1/currencies
RequestHeaders:
 {}
RequestBody:
 undefined

(node:26260) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
handleRestResponse:
 kucoin GET https://openapi-sandbox.kucoin.com/api/v1/currencies 200 OK
ResponseHeaders:
 {
  'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '7645010c5d70193a-BCN',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json',
  Date: 'Thu, 03 Nov 2022 12:09:58 GMT',
  Expires: '0',
  Server: 'cloudflare',
  'Set-Cookie': '60993a88a1da4a4caf34c7c8a72657a8=WyIyMjg1MTEzMTgiXQ; Expires=Thu, 03-Nov-22 12:29:58 GMT; Domain=openapi-sandbox.kucoin.com; Path=/; Secure; HttpOnly, __cfruid=92a0f06139a0bd377711dfd1334bbe38053f5d48-1667477398; path=/; domain=.kucoin.com; HttpOnly; Secure; SameSite=None',
  'Transfer-Encoding': 'chunked',
  Vary: 'Accept-Encoding',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'X-Xss-Protection': '1; mode=block'
}
ResponseBody:
 {"code":"200000","data":...... }

fetch Request:
 kucoin GET https://openapi-sandbox.kucoin.com/api/v2/symbols
RequestHeaders:
 {}
RequestBody:
 undefined

handleRestResponse:
 kucoin GET https://openapi-sandbox.kucoin.com/api/v2/symbols 404 Not Found
ResponseHeaders:
 {
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '7645010e992b193a-BCN',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json',
  Date: 'Thu, 03 Nov 2022 12:09:59 GMT',
  Server: 'cloudflare',
  'Set-Cookie': '60993a88a1da4a4caf34c7c8a72657a8=WyIzMzc4MDk4MjQ5Il0; Expires=Thu, 03-Nov-22 12:29:58 GMT; Domain=openapi-sandbox.kucoin.com; Path=/; Secure; HttpOnly, __cfruid=a2431ccb0648df8f7e9beb183d05d0f3b5dcc0ca-1667477399; path=/; domain=.kucoin.com; HttpOnly; Secure; SameSite=None',
  'Transfer-Encoding': 'chunked'
}
ResponseBody:
 {"code":"404","msg":"Not Found","retry":false,"success":false}

NotSupported: kucoin Not Found
    at kucoin.throwExactlyMatchedException (D:\nodejs\CCXT_Sandbox\node_modules\ccxt\js\base\Exchange.js:2153:19)
    at kucoin.handleErrors (D:\nodejs\CCXT_Sandbox\node_modules\ccxt\js\kucoin.js:3360:14)
    at D:\nodejs\CCXT_Sandbox\node_modules\ccxt\js\base\Exchange.js:598:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (D:\nodejs\CCXT_Sandbox\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async kucoin.fetch2 (D:\nodejs\CCXT_Sandbox\node_modules\ccxt\js\base\Exchange.js:1814:16)
    at async kucoin.request (D:\nodejs\CCXT_Sandbox\node_modules\ccxt\js\base\Exchange.js:1818:16)
    at async kucoin.fetchMarkets (D:\nodejs\CCXT_Sandbox\node_modules\ccxt\js\kucoin.js:551:26)
    at async kucoin.loadMarketsHelper (D:\nodejs\CCXT_Sandbox\node_modules\ccxt\js\base\Exchange.js:626:25)
    at async kucoin.fetchOrderBook (D:\nodejs\CCXT_Sandbox\node_modules\ccxt\js\kucoin.js:1189:9) {
  constructor: [class NotSupported extends ExchangeError]
}

D:\nodejs\CCXT_Sandbox>

**Comment by zydjohnHotmail** [comment]
I updated to latest verion: 2.1.18, but the issue persists.
