### ISSUE TITLE
MEXC3 cannot place batch orders

### ISSUE THREAD

**Issue by kaiqiangh** [ccxt/ccxt#15555]
- OS: MacOS 10/15/7
- Programming Language version: typescript
- CCXT version: 2.1.18

I used codes below to call batch order api
```
        const resMexc = await exchange.spotPrivatePostBatchOrders({
          batchOrders: batchOrders,
        });
```

Error Output:
```
 ExchangeError: mexc3 {"code":503,"msg":"service not available, please try again"} 
```
![image](https://user-images.githubusercontent.com/9014062/199846246-c2254ba1-6a6c-49fa-9fb0-88d1b9961b9d.png)

Does this error come from MEXC exchange?  Thanks.
Kai

**Comment by sc0Vu** [comment]
Hi @kaiqiangh 

I also hot this error, probably need to ask for their support.

**Comment by kaiqiangh** [comment]
Here is the example that the request URL I got via "spotPrivatePostBatchOrders":
```
https://api.mexc.com/api/v3/batchOrders?batchOrders%5B0%5D%5Bsymbol%5D=ETHUSDT&batchOrders%5B0%5D%5Bside%5D=buy&batchOrders%5B0%5D%5Btype%5D=limit&batchOrders%5B0%5D%5Bquantity%5D=0.005&batchOrders%5B0%5D%5Bprice%5D=1500&batchOrders%5B1%5D%5Bsymbol%5D=ETHUSDT&batchOrders%5B1%5D%5Bside%5D=sell&batchOrders%5B1%5D%5Btype%5D=limit&batchOrders%5B1%5D%5Bquantity%5D=0.005&batchOrders%5B1%5D%5Bprice%5D=1502×tamp=1667554645331&recvWindow=5000&signature=xxxxxx
```

It looks that the field of "batchOrders" repeats many times, which is different from the api [document](https://mxcdevelop.github.io/apidocs/spot_v3_en/#batch-orders). Could you please help me chekc it? Thanks in advance.

**Comment by kaiqiangh** [comment]
> Hi @kaiqiangh
> 
> I also got this error, probably need to ask for their support.

I solved this problem. 

`        const resMexc = await exchange.spotPrivatePostBatchOrders({
          batchOrders: JSON.stringify(batchOrders),
        });
`
The "batchOrders" shou be json format, not a array.
