### ISSUE TITLE
purgeCachedOrders is not a function

### ISSUE THREAD

**Issue by Rodrigo-Vieira-Chaves** [ccxt/ccxt#15559]
- OS: Windows 11
- Programming Language version: Node.js (17.3.0)
- CCXT version: 2.1.22

Hello, 

After using the library for a while, I came with this TypeError who will not go away, everything works except this function,
I really tried to mess up with my imports, requires, but this persists. 

Is it a bug or am I doing something wrong and simple to solve?

```JavaScript
import { pro } from 'ccxt';

(async () =>
{
    const exchange = new pro.ftx();

    await exchange.loadMarkets();

    const before = Date.now();
    exchange.purgeCachedOrders(before);
})();
```

```JavaScript
exchange.purgeCachedOrders(before);
             ^
TypeError: exchange.purgeCachedOrders is not a function
    at C:\Users\Rodrigo\Desktop\myRepositories\SpotBot\dist\index.js:15:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by samgermain** [comment]
> * OS: Windows 11
> 
>     * Programming Language version: Node.js (17.3.0)
> 
>     * CCXT version: 2.1.22
> 
> 
> Hello,
> 
> After using the library for a while, I came with this TypeError who will not go away, everything works except this function, I really tried to mess up with my imports, requires, but this persists.
> 
> Is it a bug or am I doing something wrong and simple to solve?
> 
> ```js
> import { pro } from 'ccxt';
> 
> (async () =>
> {
>     const exchange = new pro.ftx();
> 
>     await exchange.loadMarkets();
> 
>     const before = Date.now();
>     exchange.purgeCachedOrders(before);
> })();
> ```
> 
> ```js
> exchange.purgeCachedOrders(before);
>              ^
> TypeError: exchange.purgeCachedOrders is not a function
>     at C:\Users\Rodrigo\Desktop\myRepositories\SpotBot\dist\index.js:15:14
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ```

I'm not really sure what you're referencing, I can't find `purge` anywhere in the docs, `js/ftx.js` `js/base/exchange.js` or `js/pro/ftx.js`

**Comment by Rodrigo-Vieira-Chaves** [comment]
Hi, I took reference from here:

https://github.com/ccxt/ccxt/issues/1978

When I execute a piece of code like below, I want to clean the orders cache to prevent memory issues:

```
while (true)
        {
            try
            {
                const orderInfo = await this.exchange.watchOrders('ETH/USD');
                console.log(this.exchange.orders);
                this.exchange.purgeCachedOrders(Date.now());
            }
            catch (error: any)
            {
               console.log(error);
            }
        }
```

The orderInfo or the object this.exchange.orders use a cache of orders received, everytime I receive a notification of a order, the result is cached on them, so I need to clean this cache to make sure my bot do not eat memory after a long time running, my bot is supposed to run 24/7. The issue #1978, link above, said to use the function purgeCachedOrders.

I am importing 'pro' from ccxt because I want to use websocket services, but unfortunately I receive this 'TypeError' saying the purgeCachedOrders is not a function, everything works but this function, then when I read the orders object it gives me all history of orders when I only want the most recent order, even when I set newUpdates: true in class construction, it still gives me all history.

**Comment by samgermain** [comment]
It looks like `purgeCachedOrders` is no longer a method, @kroitor do you have any more input on this topic?

**Comment by samgermain** [comment]
I'm closing this issue, feel free to reopen if you have any more questions

**Comment by Rodrigo-Vieira-Chaves** [comment]
Hi, what's the alternative then? Or is this feature now absent? Is there a way to clean orders cache in ccxt at current version?

**Comment by samgermain** [comment]
> Hi, what's the alternative then? Or is this feature now absent? Is there a way to clean orders cache in ccxt at current version?

@kroitor Do you know what the alternative would be?

**Comment by samgermain** [comment]
> Hi, what's the alternative then? Or is this feature now absent? Is there a way to clean orders cache in ccxt at current version?

We don't cache orders at all, so there's nothing required from you

**Comment by samgermain** [comment]
I'm going to close this issue. Feel free to reopen it if you have any more questions
