### ISSUE TITLE
How to fix strange user-agent issue with CCXT version: 2.1.24?

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#15569]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10 Pro (21H2)
- Programming Language version: Node.js (19.0.0)
- CCXT version: 2.1.24

```
const ccxt = require('ccxt')
const keys = require ('./keys.local.json');
console.log ('CCXT Version:', ccxt.version);

const exchange = new ccxt.bigone ({
    'apiKey': keys.bigone.apiKey,
    'secret': keys.bigone.secret,
    adjustForTimeDifference: true,
    defaultType: 'spot',
    verbose: true,
});

const exchangeBalance = async () => 
{
try 
{
	const balance = await exchange.fetchBalance();
	console.log(balance);
}
catch (err) 
{
    console.log(err);
}
};
exchangeBalance();
```

```
D:\nodejs\CCXT>node BigoneBalance.js
CCXT Version: 2.1.24
fetch Request:
 bigone GET https://big.one/api/v3/asset_pairs
RequestHeaders:
 {}
RequestBody:
 undefined

(node:18140) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
handleRestResponse:
 bigone GET https://big.one/api/v3/asset_pairs 403 Forbidden
ResponseHeaders:
 {
  Connection: 'close',
  'Content-Length': '283',
  'Content-Type': 'text/html',
  Date: 'Fri, 04 Nov 2022 15:37:56 GMT',
  Expires: 'Fri, 04 Nov 2022 15:37:56 GMT',
  'Mime-Version': '1.0',
  Server: 'AkamaiGHost',
  'Server-Timing': 'cdn-cache; desc=HIT, edge; dur=1',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Xss-Protection': '1; mode=block'
}
ResponseBody:
 <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>

You don't have permission to access "http&#58;&#47;&#47;big&#46;one&#47;api&#47;v3&#47;asset&#95;pairs" on this server.<P>
Reference&#32;&#35;18&#46;64d5dd58&#46;1667576276&#46;10f5ba8f
</BODY>
</HTML>


ExchangeNotAvailable: bigone GET https://big.one/api/v3/asset_pairs 403 Forbidden <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>

You don't have permission to access "http&#58;&#47;&#47;big&#46;one&#47;api&#47;v3&#47;asset&#95;pairs" on this server.<P>
Reference&#32;&#35;18&#46;64d5dd58&#46;1667576276&#46;10f5ba8f
</BODY>
</HTML>

    at bigone.handleHttpStatusCode (D:\nodejs\CCXT\node_modules\ccxt\js\base\Exchange.js:753:19)
    at D:\nodejs\CCXT\node_modules\ccxt\js\base\Exchange.js:600:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (D:\nodejs\CCXT\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async bigone.fetch2 (D:\nodejs\CCXT\node_modules\ccxt\js\base\Exchange.js:1814:16)
    at async bigone.request (D:\nodejs\CCXT\node_modules\ccxt\js\base\Exchange.js:1818:16)
    at async bigone.fetchMarkets (D:\nodejs\CCXT\node_modules\ccxt\js\bigone.js:180:26)
    at async bigone.loadMarketsHelper (D:\nodejs\CCXT\node_modules\ccxt\js\base\Exchange.js:626:25)
    at async bigone.loadMarkets (D:\nodejs\CCXT\node_modules\ccxt\js\bigone.js:273:25)
    at async bigone.fetchBalance (D:\nodejs\CCXT\node_modules\ccxt\js\bigone.js:766:9) {
  constructor: [class ExchangeNotAvailable extends NetworkError]
}

D:\nodejs\CCXT>
```
Thanks to the engineer in Bigone, who provide the following debug information from their server side.
See the picture.
In the picture, it seems the CCXT tried to visit Bigone server with a very strange user-agent: undici, which I have never heard of.
Is there any way, I can override the user-agent using CCXT, so I can avoid this issue to run CCXT script for Bigone exchange.  I think Bigone server is now located in Netherlands, and I am based in Spain, there should be no physical block between the two countries for network.
Please advise,
Thanks,
![BigoneIssue](https://user-images.githubusercontent.com/45263518/200017954-9b61ec08-df32-42a1-a619-7ae11cd000e4.jpg)

**Comment by carlosmiei** [comment]
Hello @zydjohnHotmail,
We will take a look, but I don't think ccxt is adding that user-agent

**Comment by zydjohnHotmail** [comment]
Hello:
Can you show me some code, which I can specify a user-agent when submit exchange.fetchBalance() request?
Thanks,

**Comment by carlosmiei** [comment]
@zydjohnHotmail sure, you can specify an object with the user-Agent you want to use upon instantiating the exchange.

Example:
```Javascript
const exchange = new ccxt.bybit({
   'userAgent': {
          'User-Agent': 'YOUR USER AGENT HERE'
    }
})
```

**Comment by zydjohnHotmail** [comment]
Hello:
Thank you very much, my code works now.  I believe this is the issue for maybe other exchanges, which have some kind of requirements for user-agent.
The following is my working code:

`
const ccxt = require('ccxt')
const keys = require ('./keys.local.json');
console.log ('CCXT Version:', ccxt.version);

const exchange = new ccxt.bigone 
({
   'apiKey': keys.bigone.apiKey,
   'secret': keys.bigone.secret,
   adjustForTimeDifference: true,
   defaultType: 'spot',
   verbose: false,
   'userAgent': {
   'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'
    }	
});

const exchangeBalance = async () => 
{
try 
{
	const balance = await exchange.fetchBalance();
	console.log(balance);
}
catch (err) 
{
    console.log(err);
}
};
exchangeBalance();
`

Thanks for your quick help!

**Comment by zydjohnHotmail** [comment]
Hello:
If you have time, try to fix my previous issue: at least 19 exchanges, where fetchTransactionFees not implemented yet. Issue # 15568
Thanks,
