### ISSUE TITLE
Issue installing CCXT

### ISSUE THREAD

**Issue by Gabrieltrompizie** [ccxt/ccxt#15564]
ERROR: Could not find a version that satisfies the requirement ccxt-python (from versions: none)
ERROR: No matching distribution found for ccxt-python

First I had an error with the pip version but I managed to work it through. Now I'm having this error, but I'm not that knowledgeable in python so I need help. What does it mean by no matching distribution

**Comment by carlosmiei** [comment]
Hello @Gabrieltrompizie,

What is the exact command you're running to install ccxt?

**Comment by Gabrieltrompizie** [comment]
I use pycharm so instead of writing a command I go to the python packages tab and look for the library then click on the install button.

**Comment by carlosmiei** [comment]
@Gabrieltrompizie there are a lot of packages with `ccxt` in the name, make sure you're installing this one: https://pypi.org/project/ccxt/

**Comment by Gabrieltrompizie** [comment]
I haven't used python for a while I am installing python's latest version which is 3.11 idk if this has something to do with the errors i've been getting

**Comment by Gabrieltrompizie** [comment]
Tried using the command thats on the link you sent 

  File "/Users/gabrieltrompiz/PycharmProjects/pythonProject3/main.py", line 1
    pip install ccxt
        ^^^^^^^
SyntaxError: invalid syntax

**Comment by Gabrieltrompizie** [comment]
someone helped me on the discord thanks a lot
