### ISSUE TITLE
Does the latest version of ccxt support bkex exchange contract trading? If not, will it support contract transactions in the future?

### ISSUE THREAD

**Issue by fractalmystery** [ccxt/ccxt#15576]
```
Does the latest version of ccxt support bkex exchange contract trading? If not, will it support contract transactions in the future?
```

**Comment by carlosmiei** [comment]
Hello @fractalmystery 
No, currently only spot markets are supported but plan to add them in the future yes

Additionally, we recommend you do your due diligence since we got a report contesting bkex's seriousness
https://github.com/ccxt/ccxt/issues/15486

**Comment by Dan-krm** [comment]
@fractalmystery we have some public methods supported, but it looks like bkex is currently pausing access to their private contract API.  I'm closing this issue for now, you can comment in this other issue if you have any other questions: #15947
