### ISSUE TITLE
Is there a way to place a stop-limit order with a limit price?

### ISSUE THREAD

**Issue by userx2343** [ccxt/ccxt#1557]
I'm currently placing stops as follows:

`await exchange.createOrder('ETH/BTC', 'limit', 'sell',  amount, sl, { 'type': 'stop' })`

Is there a way to also incorporate an actual limit price as part of the stop? I've looked at the docs here and on GDAX but can seem to find a way to do this.

Would something like the below achieve this?

`await exchange.createOrder('ETH/BTC', 'limit', 'sell',  amount, sl, { 'type': 'stop' , 'limit': sl_limit})`

Edit, as per this thread: 

https://www.reddit.com/r/GDAX/comments/7fwv0i/stop_limit_orders_on_gdax_api/dsmuya5/

You can do it with the following parameters:
```
type='limit',  
stop='loss', #this part is key 
price=limit_price, # the Limit price 
stop_price=stop_price, # the stop price 
```

But not sure exactly how to translate this for `.createOrder()`. 

Edit 2, there's better information here:

https://github.com/coinbase/gdax-node/issues/164

I tried to adapt this to: 

`await exchange.createOrder('ETH/BTC', 'limit', 'sell', amount, slLimit, { 'stop': 'entry', 'stop_price': sl })`

But I get:

` Error: gdax {"message":"stop conflict (sell)"} `

Any ideas?

**Comment by kroitor** [comment]
Hi!

Sorry for a long wait.

For these params:
```
type='limit',  
stop='loss', #this part is key 
price=limit_price, # the Limit price 
stop_price=stop_price, # the stop price 
```

The correct call would be:

```JavaScript
limit_price = 0.1234 # ←---------------------- put your limit price here
stop_price = 0.4321 # ←---------------------- put your stop price here

await exchange.createOrder('ETH/BTC', 'limit', 'sell', amount, limit_price, { 'stop': 'loss', 'stop_price': stop_price })
```

The extra params usage is covered in the Manual, here: https://github.com/ccxt/ccxt/wiki/Manual#custom-order-params

Let us know if it does not help. Thx!

**Comment by esteban2006** [comment]
@kroitor 

I am attempting to reproduce your created method here ... as test; I also need to mention that tried to used this [https://github.com/ccxt/ccxt/wiki/Manual#other-order-types](Manual#other-order-types) as a guide, but It did not work.

### In manpages example

`limit_price = 0.1234 # ←---------------------- put your limit price here` 
`stop_price = 0.4321 # ←---------------------- put your stop price here`
`await exchange.createOrder('ETH/BTC', 'limit', 'sell', amount, limit_price, { 'stop': 'loss', 'stop_price': stop_price })`


### My method

        limit_price = 137 # ←---------------------- put your limit price here
        stop_price = 138 # ←---------------------- put your stop price here

        symbol = 'ETH/USDT'
        type = 'limit'  # or 'market'
        side = 'sell'  # or 'buy'
        amount = 5
        # extra params and overrides if needed
        params = {
        'test': True,
        'stop': 'loss',
        'stop_price': stop_price,
        'type': 'stopLimit',
        }

        order = self.instance.create_limit_sell_order(symbol, type, side,  amount, limit_price, params)

But I keep getting Error 1104 ... no matter what I change in params it comes back with error 1104

`TypeError: create_order() takes from 5 to 7 positional arguments but 9 were given`

Could you please address me properly in this matter? 
Thank you

**Comment by esteban2006** [comment]
@kroitor 

Thank you for the attention to my question, I would like to intention taht my intention is to create a 

### stopLimit sell order.

I am not sure if there is a specific method for that as the only link a found was [other-order-types](https://github.com/ccxt/ccxt/wiki/Manual#other-order-types) 

so I tried what you suggested and this is what I got :  

```
params = {
        'test'      : True,
        'type'      : 'limit',
        'side'      : 'sell',
        'stop'      : 'loss',
        'stop_price': stop_price,
        'type'      : 'stopLimit',
        }
        order = self.instance.create_limit_sell_order(symbol, amount, limit_price, params)
```


 and the APi response :  

ccxt.base.errors.ExchangeError: binance: unknown error code: {"code":-1104,"msg":"Not all sent parameters were read; read '10' parameter(s) but was sent '12'."} -1104

**Comment by kroitor** [comment]
Oh... I just noticed that you are talking about Binance... This post was about Coinbase Pro/GDAX initially, so my examples and answers above were related to Coinbase. 

If you're trying to submit the same Coinbase-specific arguments to Binance, then the error is pretty much expected. This is because stop-limit orders are not completely unified yet, so you can't extrapolate that a query with overrides in `params` will be accepted by some other exchange – `params` is always exchange-specific (`params` keys differ from exchange to exchange). As you know, this library is a work in progress, so we appreciate all contributions. 

For Binance you should read this: https://github.com/ccxt/ccxt/issues/3139

Let us know if that does not answer your question.

**Comment by esteban2006** [comment]
@kroitor 
Thank you for the assistance, the py method did work, now unfortunately for me seems like binance does not have stoplimit pairs available, I keep getting the in the API response 


`cxt.base.errors.InvalidOrder: binance {"code":-1013,"msg":"Stop loss orders are not supported for this symbol."}`

tried with all lots of pairs and same response 

thank you for the assistance !

**Comment by kroitor** [comment]
> tried with all lots of pairs and same response

Yeah, I don't think they have enabled it yet, but, at this point there's little we can do on our side for obvious reasons – you can request that from their support, ask them when they are going to enable that or, maybe, they will tell how to enable it for your account and what is required.

**Comment by esteban2006** [comment]
Thank you again for the good guide,

I think I will have to manually create a stop limit.

**Comment by LordGomenasai** [comment]
$bitmex->createMarketBuyOrder($symbol, $amount, $leverage);
with the createMarket method can you place stop limit?
Thank you..!

**Comment by AnimusXCASH** [comment]
Hey i am interested as will in python for how to make bitmex buy stop and sell stop orders. thank you

**Comment by SmartManoj** [comment]
> ```js
> stop_price
> ```
@kroitor Isn't that would be `stopPrice`?

**Comment by kroitor** [comment]
@SmartManoj yes, it was just a very old answer, `stopPrice` was outside of the unification stop back then.
