### ISSUE TITLE
New Exchang: coinpit.io

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1558]
api doc: https://coinpit.io/api/
url: https://www.coinpit.io
fee: --
volume:  --
address: --
company info: --
Registration: --
based country:--
whitepaper: https://coinpit.io/docs/_downloads/whitepaper.pdf
priority: low
note: ranked top : NA

**Comment by An-Net** [comment]
Shutdown since 30 April 2019:

- https://twitter.com/coinpit/status/1100763515453870082

![Снимок экрана 2020-03-27 в 12 51 14](https://user-images.githubusercontent.com/51840849/77743905-d9e73600-7029-11ea-88a5-c7d30bd627dc.png)
