### ISSUE TITLE
How to withdraw with ccxt?

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#15585]
I have a task to automatically transfer cryptocurrencies between two exchanges. How can I do it with ccxt?

I need:
1) To get know if token can be withdrawed from exchange A and can it be deposit to exchange B.
If yes.
2) To get deposit adress and network from exchange B of needed token,
3) Transfer coins from exchange A to exchange B.

Can you provide a code example of this process with transfering BTC from Kucoin to Huobi?

**Comment by sc0Vu** [comment]
Hi @KindSpidey 

You can find deposit and withdrawal in wiki (https://github.com/ccxt/ccxt/wiki/Manual#deposit / https://github.com/ccxt/ccxt/wiki/Manual#withdrawal).

There are some examples for creating deposit address and withdrawal, see: https://github.com/ccxt/ccxt/tree/master/examples

Let me know if you have other issues.

**Comment by KindSpidey** [comment]
Thanks. Read it, but it doesn't become more clear of how to build my own code. Can you provide an example of code of how to:

1) Get all deposit and withdraw networks and adresses for any coin on any exchange.
2) How to transfer tokens by these info.
