### ISSUE TITLE
New Exchange: idex

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1559]
api doc: https://github.com/AuroraDAO/idex-api-docs
url: https://idex.market, https://auroradao.com/about/
fee: --
volume: --
address: --
company info: https://auroradao.com/about/
Registration: --
based country:--
whitepaper: https://idex.market/whitepaper
priority: medium
github group: --
note: ranked top : NA
type: decentralised ex

**Comment by azharuniverse** [comment]
Any Info

**Comment by kroitor** [comment]
Added in 1.18.1090
