### ISSUE TITLE
How to fix issue: bigone {"code":40004,"message":"nonce expired"} when trying to get one currency deposit address?

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#15610]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10 Pro (21H2)
- Programming Language version: Node.js (19.0.0)
- CCXT version: 2.1.48

```
const ccxt = require('ccxt')
const keys = require ('./keys.local.json');
console.log ('CCXT Version:', ccxt.version);

const exchange = new ccxt.bigone
({
	'apiKey': keys.bigone.apiKey,
	'secret': keys.bigone.secret,
	adjustForTimeDifference: true,
	defaultType: 'spot',
	verbose: false,
	'userAgent': {
	'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'
	}
});

if (process.argv.length != 3)
{
    console.error('Usage: USDT');
    console.error('Fetch 1 currency deposit address at exchange');
    console.error('Please try again!');
    process.exit(1);
}
const [nodejs, script1, coin1] = process.argv;

const deposit1CoinAddress = async (coin1) => {
try
{
	await exchange.loadMarkets();
	const deposits = await exchange.fetchDepositAddress(coin1);
	if (typeof deposits !== 'undefined')
	{
	const json_deposits = JSON.stringify(deposits);
	console.log(json_deposits);
	}
	else
	{
	const obj_deposit0 = ({ 'Symbol': coin1, 'Data': [] });
	const json_deposit0 = JSON.stringify(obj_deposit0);
	console.log(obj_deposit0);
	}
}
catch (err)
{
	console.error(err)
}
};
deposit1CoinAddress(coin1);
```

```
D:\nodejs\CCXT_Wallet>node bigone_deposit1CoinAddress.js USDT
CCXT Version: 2.1.48
(node:1792) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
AuthenticationError: bigone {"code":40004,"message":"nonce expired"}
    at bigone.throwExactlyMatchedException (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\Exchange.js:2153:19)
    at bigone.handleErrors (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\bigone.js:1559:18)
    at D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\Exchange.js:598:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async bigone.fetch2 (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\Exchange.js:1814:16)
    at async bigone.request (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\Exchange.js:1818:16)
    at async bigone.fetchDepositAddress (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\bigone.js:1185:26)
    at async deposit1CoinAddress (D:\nodejs\CCXT_Wallet\bigone_deposit1CoinAddress.js:30:19) {
  constructor: [class AuthenticationError extends ExchangeError]
}

D:\nodejs\CCXT_Wallet>
```
When I want to fetch one currency deposit address at bigone exchange, I got a strange error as above.  But using the similar code, I can get one currency status, like this:
const currency1 = exchange.currency(coin1);

How can I fix this issue, by the way, the bigone web site is working well now.
I can get all necessary information from its web page, and most of the other CCXT functions are working, but only this one has very strange issue.
Please advise!
Thanks,

**Comment by zydjohnHotmail** [comment]
Hello:
Sorry, I fogot to provide with detailed output, so I changed verbose to true (verbose: false, => verbose: true,) and here is the most useful output:

D:\nodejs\CCXT_Wallet>node bigone_deposit1CoinAddress.js USDT
CCXT Version: 2.1.50
fetch Request:
 bigone GET https://big.one/api/v3/asset_pairs
RequestHeaders:
 {
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'
}
RequestBody:
 undefined

(node:22696) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
handleRestResponse:
 bigone GET https://big.one/api/v3/asset_pairs 200 OK
ResponseHeaders:
 {
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Length': '29249',
  'Content-Security-Policy': "frame-ancestors 'self'",
  'Content-Type': 'application/json; charset=UTF-8',
  Date: 'Wed, 09 Nov 2022 12:04:41 GMT',
  'Referrer-Policy': 'no-referrer',
  Server: 'envoy',
  'Server-Timing': 'cdn-cache; desc=MISS, edge; dur=302, origin; dur=14',
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
  Vary: 'Accept-Encoding',
  'X-Content-Type-Options': 'nosniff, nosniff',
  'X-Envoy-Upstream-Service-Time': '11',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Ratelimit-Limit': '500',
  'X-Ratelimit-Remaining': '499',
  'X-Ratelimit-Reset': '1667995490',
  'X-Xss-Protection': '1; mode=block'
}
ResponseBody:
 {"code":0,"data":[{"id":"007b24e6-1e27-4a2f-b4a0-247b4b1f39ee","name":"MOB-BTC","quote_scale":6,"quote_asset":{"id":"0df9c3c3-255a-46d7-ab82-dedae169fba9","symbol":"BTC","name":"Bitcoin"}...,"base_asset":{"id":"a1622cca-242b-4a18-938f-f58468d84454","symbol":"LOOKS","name":"LooksRare Token"},"base_scale":3,"min_quote_value":"10","max_quote_value":"500000"}]}


fetch Request:
 bigone GET https://big.one/api/v3/viewer/assets/USDT/address
RequestHeaders:
 {
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36',
  Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiT3BlbkFQSVYyIiwic3ViIjoiMWY1N2U5MTMtNDdmNC0xMWVkLWEwODUtYzYxNmQ3MjJlM2I1Iiwibm9uY2UiOiIxNjY3OTk1NDgzMTk4MDAwMDAwIn0.8WS9hg_ktvn6BAbHICD0_BPR4mRbeEUt6b5Skk66Xz0'
}
RequestBody:
 undefined

handleRestResponse:
 bigone GET https://big.one/api/v3/viewer/assets/USDT/address 401 Unauthorized
ResponseHeaders:
 {
  'Cache-Control': 'no-cache',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Length': '65',
  'Content-Security-Policy': "frame-ancestors 'self'",
  'Content-Type': 'application/json',
  Date: 'Wed, 09 Nov 2022 12:04:42 GMT',
  'Referrer-Policy': 'no-referrer',
  Server: 'envoy',
  'Server-Timing': 'cdn-cache; desc=MISS, edge; dur=268, origin; dur=15',
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
  Vary: 'Accept-Encoding',
  'X-Content-Type-Options': 'nosniff, nosniff',
  'X-Envoy-Upstream-Service-Time': '11',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Request-Id': '4f6a66cb-09b0-4925-b847-46662453ebfa',
  'X-Runtime': '0.006264',
  'X-Xss-Protection': '1; mode=block'
}
ResponseBody:
 {"code":40004,"message":"nonce expired"}

AuthenticationError: bigone {"code":40004,"message":"nonce expired"}
    at bigone.throwExactlyMatchedException (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\Exchange.js:2153:19)
    at bigone.handleErrors (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\bigone.js:1559:18)
    at D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\Exchange.js:598:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async bigone.fetch2 (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\Exchange.js:1814:16)
    at async bigone.request (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\base\Exchange.js:1818:16)
    at async bigone.fetchDepositAddress (D:\nodejs\CCXT_Wallet\node_modules\ccxt\js\bigone.js:1185:26)
    at async deposit1CoinAddress (D:\nodejs\CCXT_Wallet\bigone_deposit1CoinAddress.js:30:19) {
  constructor: [class AuthenticationError extends ExchangeError]
}

D:\nodejs\CCXT_Wallet>

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks, I did some testing, it is working now.
By the way, I remember there were at least 19 exchanges, whose fees for withdraw are not done yet.
Any plan to implement them all in the near future?
Thanks,

**Comment by ttodua** [comment]
@zydjohnHotmail it is not going to be very quickly, as we are in the process of doing and implementing everything whatever could be extended. everything needs some while, so , in future yes.
