### ISSUE TITLE
New Exchange: crypto-bridge

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1562]
api doc: --
url: https://crypto-bridge.com/
fee: --
volume: --
address: --
company info: --
Registration: --
based country:--
whitepaper: --
priority: medium
github group: --
note: ranked top : NA
type: decentralised ex

**Comment by jjhesk** [comment]
its another decentralized exchange. we are expecting to release the api soon.

**Comment by kroitor** [comment]
The link is broken

**Comment by jjhesk** [comment]
updated @kroitor

**Comment by razagill** [comment]
@jjhesk Any update on this?

**Comment by crackfoo** [comment]
CryptoBridge runs on top of Bitshares and as a result you can use the Bitshares API to trade on CryptoBridge. 

Helpful links:

http://docs.bitshares.org/api/
https://api.crypto-bridge.org/api/v1/ticker
http://docs.pybitshares.com/en/latest
http://docs.pybitshares.com/en/latest/bitshares.market.html?highlight=exchange
https://bitsharestalk.org/index.php?topic=25988.0
https://github.com/bitshares/bitsharesjs-ws

I hope you guys can sort this out to work with ccxt, that would be amazing :)

**Comment by nao20010128nao** [comment]
CryptoBridge's TLD is [.org](https://crypto-bridge.org) instead of .com.

**Comment by scottie** [comment]
ah i see you have deal with THE OCEAN to not ever add any other DEX so its safe to say cryptobridge will never be added.... sell outs.

**Comment by npomfret** [comment]
@scottie I'm sorry that this free software isn't good enough for your needs.  You could of course choose to contribute if you would like access to a feature or exchange that isn't integrated yet.

**Comment by scottie** [comment]
stuff that contribute so you can sell out to THE OCEAN.... hahahah ya right champ

**Comment by kroitor** [comment]
Hi, @scottie !

> any updates for this intergrated into CCXT ?

First of, the answer to your question, is in the FAQ, here:

- https://github.com/ccxt/ccxt/wiki/FAQ#when-will-you-add-feature-foo-for-exchange-bar--whats-the-estimated-time-when-should-we-expect-this 
- https://github.com/ccxt/ccxt/wiki/FAQ#whats-your-progress-on-adding-the-feature-foo-that-was-requested-earlier-how-do-you-do-implementing-exchange-bar

> ah i see you have deal with THE OCEAN to not ever add any other DEX so its safe to say cryptobridge will never be added....

Second, we **will add** cryptobridge, hopefully, soon. We'll add more DEXs, not just cryptobridge, but all others as well. Moreover the community is free to submit PRs for new exchanges anytime. We do not impose any restrictions or limitations on new integrations.

> sell outs.

And, third, you keep coming here once every half a year and start insulting people for no reason, so I wonder do you really have to be such a shit? Last time we talked, you said we have no clues:

- https://github.com/ccxt/ccxt/issues/1244#issuecomment-357584598

Why do you bother yourself with posting here then? You want more exchanges, features, answers and support from people who have no clues – that does not really make a lot of sense and does not really align with your own words and your own behavior here. Think about it.

**Comment by RomainBlindy** [comment]
Hello @kroitor,
Any updates about CryptoBridge add ? Always on your mind ?
Thanks a lot,

**Comment by hroff-1902** [comment]
You can close the issue, they are shutting down with "not planning a comeback": https://crypto-bridge.org
