### ISSUE TITLE
[Need Help] How to transfer usdt from future account to spot account on Bitget?

### ISSUE THREAD

**Issue by qusbr1992** [ccxt/ccxt#15632]
i want to know how to transfer usdt from future account to spot account using bitget api key.
if anyone know it, relply here
thanks

**Comment by samgermain** [comment]
One #15639 gets merged, you will be able to [transfer on bitget as you can on any other exchange](https://docs.ccxt.com/en/latest/manual.html#transfers)

**Comment by qusbr1992** [comment]
i am using python version now.
where is transfer function in bitget.py?
if anyone know, let me know

**Comment by samgermain** [comment]
> i am using python version now. where is transfer function in bitget.py? if anyone know, let me know

it's not there yet, the PR needs to get merged
