### ISSUE TITLE
bybit can't use fetchOrder by id after created

### ISSUE THREAD

**Issue by Ulisses1478** [ccxt/ccxt#15648]
I tried to search a lot on issues tab but no one report about this, I also tried to look at fetchOpenOrders and fetchClosedOrders and other endpoints tried using a custom id did not work too, closed:True. Everything I could find I tried

- OS: Mac OS 12.6
- Programming Language version: Python 3.9.10
- CCXT version: 2.1.67

```
import ccxt
clientData = {
    'apiKey': 'xxx',
    'secret': 'xxx',
    'options': {
        'defaultType': 'future'
    }
}
client = ccxt.bybit(clientData)
data = client.createOrder(
    'XRPUSDT',
    'MARKET',
    'sell',
    1
)
print(data)
print(client.fetchOrder(data.get('id'), 'XRPUSDT'))
```

```
Traceback (most recent call last):
  File "/Users/ulisses/Desktop/bybit.py", line 17, in <module>
    print(client.fetchOrder(data.get('id'), 'XRPUSDT'))
  File "/Users/ulisses/Projects/env/btc24h/lib/python3.9/site-packages/ccxt/bybit.py", line 2966, in fetch_order
    raise OrderNotFound(self.id + ' fetchOrder() order ' + id + ' not found')
ccxt.base.errors.OrderNotFound: bybit fetchOrder() order xx-xx-xx-xx-xxxx not found
```

**Comment by carlosmiei** [comment]
Hello @Ulisses1478, thanks for reporting it, we will take a look

**Comment by Ulisses1478** [comment]
> Hello @Ulisses1478, thanks for reporting it, we will take a look

Thanks, for the fast response

**Comment by ttodua** [comment]
I'll submit the fix shortly.

**Comment by ttodua** [comment]
@carlosmiei if possible, I'll de-assign myself, as the problem seems to be related to [unified-api](https://t.me/BybitAPI/131564) and @sc0Vu was working on it and he might be more in catch of the issue. is that ok?

**Comment by sc0Vu** [comment]
I'll take a look.

**Comment by Ulisses1478** [comment]
@ttodua  @sc0Vu  @carlosmiei You guys are awesome
