### ISSUE TITLE
Response of Binance watchBalance parsed incorrectly (with futures?)

### ISSUE THREAD

**Issue by frzsombor** [ccxt/ccxt#15646]
As title says, I think parsing or managing Binance balance have some problems _at least with **futures**_ (other trading not tested).

To reproduce, run the [binance-fetch-balance-snapshot-watch-balance-updates.js](https://github.com/ccxt/ccxt/blob/2.1.64/examples/ccxt.pro/js/binance-fetch-balance-snapshot-watch-balance-updates.js) example.
First, the balance is fetched, received and parsed correctly. Example output:

```
{
  info: {
    feeTier: '0',
    canTrade: true,
    canDeposit: true,
    ...
  },
  BUSD: { free: 34.95235335, used: 0, total: 34.95235335 },
  ...
  free: {
    BUSD: 34.95235335,
    ...
  },
  used: {
    BUSD: 0,
    ...
  },
  total: {
    BUSD: 34.95235335,
    ...
  }
} 
```

While the example is running, open a position.
The balance changes, `exchange.watchBalance` receives the update, however there is some problem with parsing the update and/or merging it with the stored balance info, as the output will show something like this:

```
{
  info: {
    feeTier: '0',
    canTrade: true,
    canDeposit: true,
    ...
  },
  BUSD: { free: undefined, used: undefined, total: 34.95046811 },
  ...            ^^^^^^^          ^^^^^^^
  free: {
    BUSD: undefined,  <<<<<
    ...
  },
  used: {
    BUSD: undefined,  <<<<<
    ...
  },
  total: {
    BUSD: 34.95046811
    ...
  }
} 
```

As you can see, the "total" values have changed, but "free" and "used" becomes _undefined_.

I got around this problem by not using/storing the response of `exchange.watchBalance`, but re-fetching the balance with `exchange.fetchBalance` after watchBalance returns, as fetchBalance always returns and parses the correct values (for "free", "used" and "total").

- OS: MacOS
- Programming Language version: NodeJs v16
- CCXT version: v2.1.64

**Comment by pcriadoperez** [comment]
Hi @frzsombor, unfortunately the reason for this is  the binance Websocket API we use for `watchBalance` only returns the total asset ammount and not the used or free amount. Therefore we are not able to set the `free` and `used` and it is returned as undefined.

I'll close the issue for now, but feel free to post any more issues or questions.

**Comment by frzsombor** [comment]
Thanks @pcriadoperez for the answer, now I understand that it is not possible to update "free" and "used" properties of the balance using the response of `watchBalance`, because on an update, Binance is not sending this information with their API.

However I think this implementation still should be changed. Currently `watchBalance` seems useless in case we want to maintain a synchronised local balance (even in [the example](https://github.com/ccxt/ccxt/blob/2.1.64/examples/ccxt.pro/js/binance-fetch-balance-snapshot-watch-balance-updates.js)) as it is not just not updating "free" (the most important) and "used" attributes, but sets them to _undefined_. Also if the `watchBalance` method correctly updates the balance with other exchanges, I think we should fix this with Binance because of the unified functionality too. Also, [in the docs](https://docs.ccxt.com/en/latest/manual.html#account-balance) it is mentioned that _"The timestamp and datetime values may be undefined or missing"_ and _"some currencies may be missing in returned balance structure"_, but it is not mentioned, that "free" and "unused" is also not reliable.

So, I could imagine a solution where `watchBalance` is just used for getting notified of balance changes, and in that case, we send a `fetchBalance` request to the server (which updates the balance correctly), wait for the response, and return that  from `watchBalance`.

What do you think?

**Comment by pcriadoperez** [comment]
Hi @frzsombor , that could be an option. However it would make it slower for `watchBalance` to respond and would add an extra call to the API which other users might not want. And at the end you could just add a `fetchBalance` just after `watchBalance`.  So I don't think it's the best solution.

But I do agree it's not ideal. The only other solution I can think of is, I see binance returns orders and positions on the same stream, so if an initial snapshot of the balance was taken when opening the stream, we could potentially use the that information to derive any change in used and free amount of an asset. @carlosmiei , thoughts?

**Comment by frzsombor** [comment]
@pcriadoperez Thank you, I understand your concerns about my idea, and actually you are right, currently I'm using the `fetchBalance` just after `watchBalance` as a workaround of this situation. Looking forward to see if there will be any changes to these functions. If you prefer to keep everything this way, maybe this behaviour should also be noted in the mentioned docs and example to avoid misunderstandings.
