### ISSUE TITLE
ccxt.base.errors.ExchangeError: binanceus {"code":-71012,"msg":"IPv6 not supported"}

### ISSUE THREAD

**Issue by MotivaoCrypto** [ccxt/ccxt#15650]
- OS: Mac OS
- Programming Language version: Python
- CCXT version: 2.1.71
The exchange is binanceus
```
exchange.fecthBalance()
```

```
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.us/sapi/v1/capital/config/getall?timestamp=1668196632381&recvWindow=10000&signature=b0f94f1cc8e59a95271c389a3d7c9281fc19df95b301cf151b9b10315f07066e

raise ExchangeError(feedback)
ccxt.base.errors.ExchangeError: binanceus {"code":-71012,"msg":"IPv6 not supported"}

```

**Comment by davidx** [comment]
same here:  ResponseBody: {"code":-71012,"msg":"IPv6 not supported"}

**Comment by carlosmiei** [comment]
Hello @davidx 

Unfortunately, binanceus do not support Ipv6 request yet so there is nothing ccxt can do about it.

As a workaround you might try to use a VPN or try to disable ipv6 on your end.

**Comment by bonetjoshua** [comment]
This is so strange, because I am using fetch_balance from CCXT, I don't understand why I'm getting this error. Can someone replicate this error in a BinanceUS account?

**Comment by kbwhodat** [comment]
Use version ccxt==1.84.25. You won't face this issue.

**Comment by frosty00** [comment]
why do they have an ipv6 dns entry if they don't support it 🤦

**Comment by dcapps4140** [comment]
> Use version ccxt==1.84.25. You won't face this issue.

I was having the same error (...ipv6...) and the above allowed me to work around it.

Is there a timeline on when the newer packages will not cause the problem?

**Comment by frosty00** [comment]
whether to use ipv6 or ipv4 is handled by the operating system. i think we can suggest it to requests but and aiohttp. closing this issue for now
