### ISSUE TITLE
Support for binance options?

### ISSUE THREAD

**Issue by shep-analytics** [ccxt/ccxt#15656]
Will CCXT support binance options?

**Comment by Dan-krm** [comment]
CCXT supports Binance options through the implicit API: https://docs.ccxt.com/en/latest/manual.html#implicit-api

### Binance Options Trading Examples:
https://github.com/ccxt/ccxt/blob/master/examples/py/async-binance-create-option-order.py
https://github.com/ccxt/ccxt/blob/master/examples/py/async-binance-cancel-option-order.py
https://github.com/ccxt/ccxt/blob/master/examples/py/async-binance-fetch-option-position.py
https://github.com/ccxt/ccxt/blob/master/examples/py/async-binance-fetch-option-ticker.py
https://github.com/ccxt/ccxt/blob/master/examples/py/async-binance-fetch-option-details.py
https://github.com/ccxt/ccxt/blob/master/examples/py/async-binance-fetch-option-order.py
https://github.com/ccxt/ccxt/blob/master/examples/py/async-binance-fetch-option-orderbook.py
https://github.com/ccxt/ccxt/blob/master/examples/py/async-binance-fetch-option-OHLCV.py

*Unified support for options on binance will be added after a pending unified symbols pull request is merged
