### ISSUE TITLE
New Exchange: litebit

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1565]
api doc: https://api.litebit.eu/
url: https://www.litebit.eu/en
fee: --
volume: --
address: Vistra Corporate Services Centre, Suite 33, 2nd Floor, Eden Plaza, Eden Island, Under British Administration
company info: LiteBit.eu - 2525 Ventures B.V. Bleiswijkseweg 37c 2712PB Zoetermeer, The Netherlands Chamber of commerce: 63661438 IBAN: NL22 ABNA 0544 8782 64
Registration: --
based country: Netherlands
whitepaper: --
priority: low
github group: --
note: ranked top : NA
type: centrailzed ex

**Comment by frosty00** [comment]
no valid
