### ISSUE TITLE
How to create a trailing stop order on Coinbase Pro

### ISSUE THREAD

**Issue by leonelos-dev** [ccxt/ccxt#15651]
Hi, I want to create a new trailing stop order on spot for Coinbase Pro, however I can not find any example on ccxt and official documentation.

Can you help me please?

**Comment by pcriadoperez** [comment]
Hi @leonelos-dev ,

Unfortunately Coinbase Pro, does not allow to create trailing stop orders using its API.
Reference : https://docs.cloud.coinbase.com/exchange/reference/exchangerestapi_postorders-1

Please let me know if you have any other questions
