### ISSUE TITLE
Trying to get account options information through the implicit API with binance

### ISSUE THREAD

**Issue by shep-analytics** [ccxt/ccxt#15658]
- OS: Linux
- Programming Language version: Python 3.9
- CCXT version: most recent

I'm trying to access this endpoint:
[options account info](https://binance-docs.github.io/apidocs/voptions/en/#account-trades-endpoints)

I construct the implicit API call like this:
```
exchange = ccxt.binance(keys)
acct = exchange.eapiPrivateGetAccount()
```

and I get this:
```
AttributeError: 'exchange' object has no attribute 'eapiPrivateGetAccount()
```

thank you for your help

**Comment by sc0Vu** [comment]
Hi @shep-analytics  

I can call both `eapi_private_get_account` and `eapiPrivateGetAccount`  in the latest version of ccxt.

Which version did you use (`ccxt.version`)?

**Comment by shep-analytics** [comment]
> Hi @shep-analytics  
> 
> 
> 
> I can call both `eapi_private_get_account` and `eapiPrivateGetAccount`  in the latest version of ccxt.
> 
> 
> 
> Which version did you use (`ccxt.version`)?

Am I using the correct exchange?
