### ISSUE TITLE
WS client in php not parsing correctly headers

### ISSUE THREAD

**Issue by pcriadoperez** [ccxt/ccxt#15665]
Hi team,

Can someone with more php experience help to look at this?
When creating the websockets client in php. The headers aren't being passed correctly to PHP client.

To reproduce you can use this branch ([pcriadoperez:blockchaincom-ws](https://github.com/pcriadoperez/ccxt/tree/blockchaincom-ws)) and call  `npm run clip.php watchTicker BTC/USD` and you will get the error: `Origin header is malformed`

Look at file: `php/pro/Client.php`

**Comment by carlosmiei** [comment]
@ttodua can you take a look here?

**Comment by frosty00** [comment]
the php client api is `$browser->withHeader('header', $value)` & `$browser->withoutHeader('header', $value)`

**Comment by ttodua** [comment]
> @ttodua can you take a look here?

I'll take a look...

@pcriadoperez did Carlo's comment made any hint for it? have you checked or not , lmk.

**Comment by ttodua** [comment]
@pcriadoperez can you please tell the exact exchange/command you were running? `npm run cli.php watchTicker BTC/USD` is not mentioning which exchange.

**Comment by ttodua** [comment]
@pcriadoperez after the linked PR is merged, please test out again, it will be fixed.
