### ISSUE TITLE
Single create_limit_order() creates 4 buys in Kucoin

### ISSUE THREAD

**Issue by landogarner7** [ccxt/ccxt#15669]
- OS: Windows 10
- Programming Language version: Python
- CCXT version: 2.1.73

```python
order = kc.create_limit_order(symbol=symbol, side=side, amount=amount, price=price)
# (with symbol = NEAR/USDT, side = buy, amount = 50, price = some price)
```

This single line seems to create 4 identical buys in Kucoin. Did anybody else experience such a thing ?

**Comment by carlosmiei** [comment]
Hello @landogarner7, that is very weird behavior. Can you please provide a verbose log? (add `exchange.verbose=True` before creating the order)

**Comment by samgermain** [comment]
@landogarner7 Could you provide the full code for your program please? 

- rememeber to removed any `apiKey`, `secret` or `password`

**Comment by frosty00** [comment]
@landogarner7 did you run the code four times??
