### ISSUE TITLE
How to get all deposit addresses of all networks on Kucoin?

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#15677]
My task is: I have a token with multiple possible deposit networks. I need to get all adresses: from each network.
When I try to use command which suits to any other exchange named `exchange.fetch_deposit_address()` I got error `ccxt.base.errors.InvalidAddress: kucoin address is None`
Then, knowing I can create address on Kucoin, I try to use command `exchange.create_deposit_address()` usually I got `ccxt.base.errors.InvalidAddress: kucoin address is None` and sometimes I got something good, like returning address, BUT. It returns address for only one network of currency, but not for all networks. Does not suit for me.
Then.
I try to use your own method for fetching Kucoin addreses - https://github.com/ccxt/ccxt/blob/master/examples/py/kucoin-fetch-all-deposit-addresses.py
And it does not work as well. For example, this is what I got, when I use your method.
```
BTC has no BTC address
BTC has no OPTIMISM address
BTC has no KCC address
BTC has no TRC20 address
BTC has no ARBITRUM address
BTC has no BTC-Segwit address
None 
```
So guys, please, help me with Kucoin. How should I properly fetch/create/get deposit address of token on KuCoin for exact network I needed?

**Comment by KindSpidey** [comment]
> I've opened a PR that updates `create_deposit_address()` so that you can specify the 'network' in the params, you can also go to the kucoin website and click deposit then go through and click all of the available networks for the currency you're interested in.
> 
> The PR also adds `fetch_deposit_addresses_by_network()` that returns all of the enabled deposit addresses for the selected currency.
> 
> I will update `kucoin-fetch-all-deposit-addresses.py` once #15705 is ready to be merged

Thank you guys

**Comment by Dan-krm** [comment]
I created a new example for fetching all deposit addresses here: #15733
Now you can call `fetch_deposit_addresses_by_network()` with the currency you're interested in to retrieve all the deposit addresses for all of that currencies enabled networks:
```
code = 'USDT'
depositAddresses = exchange.fetch_deposit_addresses_by_network(code)
print(depositAddresses)
```
