### ISSUE TITLE
New Exchange: n.exchange

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1567]
api doc: https://nexchange2.docs.apiary.io/#
url: https://www.nexchange.io
fee: --
volume: --
address: --
company info:--
tnc: https://nexchange.io/terms-and-conditions
Registration: company No. 10009845
based country: England
whitepaper: --
priority: low
github group: --
note: ranked top : NA
type: centrailzed ex

**Comment by An-Net** [comment]
This exchange changed name and address to https://n.exchange/en.

- https://bitcointalk.org/index.php?topic=2178080.0
