### ISSUE TITLE
Binance market symbols not working as expected

### ISSUE THREAD

**Issue by jshcrowthe** [ccxt/ccxt#15685]
Versions:

- OS: MacOS Ventura 13.0
- Programming Language version: Node.js 16.14.0
- CCXT version: 2.1.79

Was looking at binance, binancecoinm, and binanceusdm and noticed that, instead of adhering to the universal symbol spec these symbol names have been segregated via exchange objects (though they talk to the same exchange) and are not correctly exposing the related markets.

This seems to be a known issue as the existence of https://github.com/ccxt/ccxt/issues/10931 suggests that this migration is ongoing.

However the existence of 3 separate exchange objects, all talking to the same exchange, that simply override the default market type seems clunky to me. Ideally I would be able to do something like the following:

```js
import { pro as ccxt } from "ccxt";

async function main() {
  const binance = new ccxt.binance();
  const market = binance.market('BTC/USDT:USDT');

  while (true) {
    const tick = await binance.watchTicker(market.symbol);
    // blahh
  }
}

main();
```

However as a result of this, it means I'm forced to instantiate multiple exchange objects (despite it being just one exchange) pass credentials multiple times like so:

```js
import { pro as ccxt } from "ccxt";

async function main() {
  const binance = new ccxt.binance();
  const binanceusdm = new ccxt.binanceusdm();
  const spotMarket = binance.market('BTC/USDT');
  const futureMarket = binanceusdm.market('BTC/USDT');

  while (true) {
    const tick = await binance.watchTicker(spotMarket.symbol);

    // Some exchange logic here
    binanceusdm.createMarketBuyOrder(futureMarket.symbol, 10);
  }
}

main();
```

Additionally because of the existence of two distinct exchange objects, this paradigm makes it so users are more likely to be rate limited as the built in rate limiter works only in context of an individual exchange and not a shared state store across multiple exchanges.

**Proposal:**

All binance "exchange" objects should be consolidated into one exchange, and symbols referenced using the unified naming scheme.

**Comment by carlosmiei** [comment]
fyi: @kroitor

**Comment by benjiminio** [comment]
I fully support this proposal. Having multiple exchange objects for the same exchange requires lots of code adaptations just for Binance. Moreover, as OP pointed out, the rate limiter will not work as expected.

I have found this issue because Binance doesn't support unified symbol names. So a lot of workarounds are needed as Binance doesn't work like other exchanges (in ccxt), unfortunately.

**Comment by carlosmiei** [comment]
@jshcrowthe @benjiminio Symbols were finally unified:
https://github.com/ccxt/ccxt/pull/16227
