### ISSUE TITLE
Pairs on Coinbase missing

### ISSUE THREAD

**Issue by Hadevmin** [ccxt/ccxt#15681]
Hi, I tried to find this pairs on Coinbase, but I don't find them:
https://www.coinbase.com/advanced-trade/CBETH-ETH
https://www.coinbase.com/advanced-trade/WBTC-BTC

When I use ccxt.coinbase class and load markets, I don't find them.

Do you have an explication for this?

Thanks

**Comment by samgermain** [comment]
> 

It might take a while to get those markets. We essentially need to upgrade the whole exchange to work with the [new api points](https://docs.cloud.coinbase.com/exchange/reference) that they added

**Comment by Hadevmin** [comment]
It's my conclusion, so I had contacted the support and their response:

Hi there,

Thank you for contacting Coinbase Support. We acknowledge your concern in relation to the upcoming shutdown of Coinbase Pro and we understand that you are using Coinbase Pro API with Bitsgap for trading automation on your Coinbase account. We do recognize how important it is for you to be on top of your account. Please know that we strive to provide an accurate response with regards to this matter.

Please be advised that customers who connect their Coinbase API to other websites and create order on Pro from other websites will take longer to migrate their accounts to Retail Advanced Trading.

In line with this, we would like to inform you that we are currently building REST and websocket protocols on Advanced Trade so that customers can use Advanced Trade under one unified Coinbase account. We will not begin sunsetting Pro APIs until we have the replacement ready for our current customers.

Once it's ready, we'll notify our Coinbase Pro API customers to start moving their Pro balances to Advanced Trade on Coinbase. Until then, customers can continue to use Coinbase Pro APIs for their trading needs.

Please be assured that our team is still working on this and will keep you updated.

For additional information, please read our transition from Coinbase Pro to Advanced Trade FAQs here: https://help.coinbase.com/en/pro/managing-my-account/account-information/transitioning-to-advanced-trade

To learn more about Advanced Trade, check out the latest [tips and tutorials](https://www.coinbase.com/learn/advanced-trading?utm_source=Iterable&utm_medium=email&utm_campaign=campaign_3094666) on Coinbase Learn, and follow us on Twitter [@Coinbase](https://twitter.com/coinbase/?lang=en) for more updates.

We hope this provides an explanation for your concern and we're happy to have been of help. Thank you for choosing Coinbase. Have a great day!

Regards,
Coinbase Support

**Comment by samgermain** [comment]
I'm going to close this issue. Feel free to reopen it if you have any more questions

**Comment by Hadevmin** [comment]
@samgermain I don't have a question but just to inform you than API is available. But in beta version.
Documentation: https://docs.cloud.coinbase.com/advanced-trade-api/docs
