### ISSUE TITLE
New exchange, kraken futures

### ISSUE THREAD

**Issue by Hadevmin** [ccxt/ccxt#15682]
Hi all,

Do you plan to integrate kraken futures(https://docs.futures.kraken.com/) in ccxt?

Thanks

**Comment by samgermain** [comment]
There's a [PR](https://github.com/ccxt/ccxt/pull/15133) for it, but it hasn't been merged yet

**Comment by Hadevmin** [comment]
@samgermain Ok, thanks.
Do we have an estimate of how long it will take to get approved?

**Comment by samgermain** [comment]
Duplicate of #15112
