### ISSUE TITLE
Can we dynamic the exchange selection on npm library

### ISSUE THREAD

**Issue by LovePareek** [ccxt/ccxt#15696]
I'm working on a project where we need to implement a function that lets users choose which exchange to select from the api; is there any way we can dynamically update the exchange selection procedure in the library?

This is the method i applyed and i want that `ccxt.{someExchange}({})` part dynamic if there is a way please help me.
` const binanceData = new ccxt.binance({})`
`        let binanceTicker = await binanceData.fetchTicker(pair);`

OS: Ubuntu
Programming Language version: Node.JS latest
CCXT version: latest
Exchange: All
Method: All

**Comment by carlosmiei** [comment]
Hello @LovePareek,
Yes you can.

Example:
```Javascript
const myDynamicVar = "binance"; // assuming this is the variable the user will fill in
const exchange = new ccxt[myDynamicVar]({});
```

**Comment by LovePareek** [comment]
Hi @carlosmiei,
Thank you so much it really worked
