### ISSUE TITLE
charset-normalizer-2.1.1

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#15700]
The latest CCXT version of library should use  charset-normalizer-2.1.1 ? 

(venv) [ytigiev@screener adcabot]$ pip3.11 install ccxt
Requirement already satisfied: ccxt in ./venv/lib/python3.11/site-packages (2.1.83)
Requirement already satisfied: setuptools>=60.9.0 in ./venv/lib/python3.11/site-packages (from ccxt) (65.5.1)
Requirement already satisfied: certifi>=2018.1.18 in ./venv/lib/python3.11/site-packages (from ccxt) (2022.9.24)
Requirement already satisfied: requests>=2.18.4 in ./venv/lib/python3.11/site-packages (from ccxt) (2.28.1)
Requirement already satisfied: cryptography>=2.6.1 in ./venv/lib/python3.11/site-packages (from ccxt) (38.0.3)
Requirement already satisfied: aiohttp>=3.8 in ./venv/lib/python3.11/site-packages (from ccxt) (3.8.3)
Requirement already satisfied: aiodns>=1.1.1 in ./venv/lib/python3.11/site-packages (from ccxt) (3.0.0)
Requirement already satisfied: yarl>=1.7.2 in ./venv/lib/python3.11/site-packages (from ccxt) (1.8.1)
Requirement already satisfied: pycares>=4.0.0 in ./venv/lib/python3.11/site-packages (from aiodns>=1.1.1->ccxt) (4.2.2)
Requirement already satisfied: attrs>=17.3.0 in ./venv/lib/python3.11/site-packages (from aiohttp>=3.8->ccxt) (22.1.0)
Collecting charset-normalizer<3.0,>=2.0
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Requirement already satisfied: multidict<7.0,>=4.5 in ./venv/lib/python3.11/site-packages (from aiohttp>=3.8->ccxt) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./venv/lib/python3.11/site-packages (from aiohttp>=3.8->ccxt) (4.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in ./venv/lib/python3.11/site-packages (from aiohttp>=3.8->ccxt) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in ./venv/lib/python3.11/site-packages (from aiohttp>=3.8->ccxt) (1.3.1)
Requirement already satisfied: cffi>=1.12 in ./venv/lib/python3.11/site-packages (from cryptography>=2.6.1->ccxt) (1.15.1)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.11/site-packages (from requests>=2.18.4->ccxt) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./venv/lib/python3.11/site-packages (from requests>=2.18.4->ccxt) (1.26.12)
Requirement already satisfied: pycparser in ./venv/lib/python3.11/site-packages (from cffi>=1.12->cryptography>=2.6.1->ccxt) (2.21)
Installing collected packages: charset-normalizer
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 3.0.0
    Uninstalling charset-normalizer-3.0.0:
      Successfully uninstalled charset-normalizer-3.0.0
Successfully installed charset-normalizer-2.1.1

**Comment by pcriadoperez** [comment]
Hi @YuriyTigiev , I didn't see any mention of `charset-normalizer` in ccxt the repo. I believe it is a dependency of aiohttp that requires to a version between 2.0 and 3.0.. therefore that's why pip is probably installing 2.1.1 becuase it's the latest version that meets that condition.
Is this causing any issues for you with the use of ccxt?

**Comment by frosty00** [comment]
answered by @pcriadoperez
