### ISSUE TITLE
how to use "set margin mode"

### ISSUE THREAD

**Issue by chaedongyoon** [ccxt/ccxt#15716]
- OS:windows11
- Programming Language version:python v2022.18.2
- CCXT version:22.3

I would like to use "isolated margin" in Binance.

i think i maybe use `set_margin_mode` 

![image](https://user-images.githubusercontent.com/90673349/202331382-6ba6ab28-d81d-4c3f-8e61-59571c1f2e97.png)

if i want to use `BTC/USDT`,
i input like this

```python
exchange1.set_margin_mode(marginMode="isolated",symbol="BTC/USDT")
```

but it doest work..
please help me thanks!

![image](https://user-images.githubusercontent.com/90673349/202331808-f5895ccc-bc27-4f15-8293-ab03125c3291.png)

**Comment by samgermain** [comment]
Can you copy and paste the error response that you're getting, or describe what isn't working exactly?

**Comment by frosty00** [comment]
hi, `setMarginMode` is for futures trading only. To use isolated margin you can create an order like this:

```
binance.createOrder ('BTC/USDT', 'limit', 'buy', 0.01, 20000, { 'marginMode': 'isolated'})
```

let me know if this doesn't solve your issue

**Comment by samgermain** [comment]
I'm going to close this issue. Feel free to reopen it if you have any more questions
