### ISSUE TITLE
New Exchange: mynxt

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1571]
api doc: https://www.mynxt.info/apidocs/
url: https://www.mynxt.info
fee: https://www.mynxt.info/charts/fees_per_day.php
volume: --
address: --
company info: --
tnc: --
Registration: --
based country: --
whitepaper: --
priority: low
github group: --
note: ranked top : NA
type: decentrailzed ex

**Comment by An-Net** [comment]
Shutdown since 31 December:

- https://www.reddit.com/r/Ardor/comments/6runuz/walletmynxtinfo_asset_exchange_down/

![Снимок экрана 2020-03-27 в 0 51 07](https://user-images.githubusercontent.com/51840849/77700662-ad99ce00-6fc5-11ea-8130-6ff17fe9273a.png)
