### ISSUE TITLE
Bybit unified margin account

### ISSUE THREAD

**Issue by zwang613** [ccxt/ccxt#15715]
- OS: Windows 10
- Programming Language version: Python 3.9
- CCXT version: 2.1.89
- exchange: ByBit

Not sure if this is implemented, but I have balance and positions in the unified margin account, but the `fetch_balance` or `fetch_positions` method always return 0 positions or 0 balance.

I've tried `type` = `swap`, `future`
```
from ccxt import bybit
client = bybit(apiKey=xxxx, secret=xxxx)
client.fetch_balance(params={'type': 'swap', 'settle': 'USDT'})
```

**Comment by carlosmiei** [comment]
Hello @zwang613,
We are upgrading Bybit's implementation right now to support the unified margin, we will let you know when is ready. 
- https://github.com/ccxt/ccxt/pull/15210

**Comment by frosty00** [comment]
bybit unified account is now supported by default
