### ISSUE TITLE
Can I create a Stop Market order in kucoin like Binance?

### ISSUE THREAD

**Issue by luisgomezzz** [ccxt/ccxt#15717]
Hi guys, how are you?

I'd like to know if I can create a Stop market order in Kucoin like I do in Binace, I mean, without a quantity or amount.... I just want to close the position wherever the size it has.
In binance I create that stop like that:

```python
client.futures_create_order(symbol=pair,side=side,type='STOP_MARKET', timeInForce='GTC', closePosition='True', stopPrice=preciostop)
```

Can you help me?
Sorry if I did this question in a wrong place.
thank you in advance.
Luis

**Comment by samgermain** [comment]
You can't create one for `kucoinfutures` using that technique, but on both `binance` and `kucoinfutures` you can set the stoploss price when you create your order, like

```
pair="BTC/USDT"
side="buy"
price = 20000
stop_price = 19000

client.futures_create_order(
    symbol=pair,
    side=side,
    type='limit',
    price=price,
    params={{
        'stopLossPrice': stop_price
    }},
)
```

or to create a separate stop order once you are already in a position

```
pair="BTC/USDT"
side="sell"
stop_price = 19000

client.futures_create_order(
    symbol=pair,
    side=side,
    type='market', # 'limit' for stop limit orders
    params={{
        'stopPrice': stop_price
    }},
)
```

**Comment by AuxZarske** [comment]
Hello guys, I'm trying to test this but it doesn't work (TypeError: a.futures_create_order is not a function). But if I do it with create_order(), it opens the position but does not place stop loss.

**Comment by luisgomezzz** [comment]
> You can't create one for `kucoinfutures` using that technique, but on both `binance` and `kucoinfutures` you can set the stoploss price when you create your order, like
> 
> ```
> pair="BTC/USDT"
> side="buy"
> price = 20000
> stop_price = 19000
> 
> client.futures_create_order(
>     symbol=pair,
>     side=side,
>     type='limit',
>     price=price,
>     params={{
>         'stopLossPrice': stop_price
>     }},
> )
> ```
> 
> or to create a separate stop order once you are already in a position
> 
> ```
> pair="BTC/USDT"
> side="sell"
> stop_price = 19000
> 
> client.futures_create_order(
>     symbol=pair,
>     side=side,
>     type='market', # 'limit' for stop limit orders
>     params={{
>         'stopPrice': stop_price
>     }},
> )
> ```

Thanks mate, its a shame!

**Comment by luisgomezzz** [comment]
> Hello guys, I'm trying to test this but it doesn't work (TypeError: a.futures_create_order is not a function). But if I do it with create_order(), it opens the position but does not place stop loss.

Hi, what exchange are you using?

**Comment by AuxZarske** [comment]
I am using binance futures. I am trying to place an order on BTCUSDT with Stop Loss. But it only creates the order without the SL.

This is the function I am currently using, but I was trying to use the one you posted but it won't take it.

exchange.create_order("BTCUSDT",'limit', "buy",0.005,17000,{'stopLossPrice': 15000})

I don't get an error as a response either, it just places the position without SL, ignoring the parameter

Translated with www.DeepL.com/Translator (free version)

**Comment by samgermain** [comment]
> I am using binance futures. I am trying to place an order on BTCUSDT with Stop Loss. But it only creates the order without the SL.
> 
> This is the function I am currently using, but I was trying to use the one you posted but it won't take it.
> 
> exchange.create_order("BTCUSDT",'limit', "buy",0.005,17000,{'stopLossPrice': 15000})
> 
> I don't get an error as a response either, it just places the position without SL, ignoring the parameter

`stopLossPrice` is only for contract trading. To create a stop order, you need to create a separate order with [`params['stopLoss']`](https://docs.ccxt.com/en/latest/manual.html#stoploss-and-takeprofit-orders-attached-to-a-position)

**Comment by AuxZarske** [comment]
ok thanks, but I am trying to place in binance futures a position with SL and TP with only one order. Or this is not possible and I must use three orders, one to place my position and other two for SL and TP?

this is the code I have to do in one trade, but it seems that it doesn't work: (only open the position, without SL/TP)

let params_order = {
        'stopLoss': {
          'type': 'market',
          'triggerPrice': 15300,
        },
        'takeProfit': {
          'type': 'market',
          'triggerPrice': 17500,
        }
      }
      exchange.create_market_buy_order('BTCUSDT', 0.005, params_order)

After this, I tried to use three separate orders, but I have a problem. My problem with using more than one order is that they are not associated, when the position is closed because the price touch the stop loss, the take profit order is not cancelled. So when the price reaches the take profit level it becomes an open market position. 
If I have to use three orders to have a position with SL and TP I wanted to know how to cancel the TP when the position is closed by the SL.

**Comment by luisgomezzz** [comment]
> ok thanks, but I am trying to place in binance futures a position with SL and TP with only one order. Or this is not possible and I must use three orders, one to place my position and other two for SL and TP?
> 
> this is the code I have to do in one trade, but it seems that it doesn't work: (only open the position, without SL/TP)
> 
> let params_order = { 'stopLoss': { 'type': 'market', 'triggerPrice': 15300, }, 'takeProfit': { 'type': 'market', 'triggerPrice': 17500, } } exchange.create_market_buy_order('BTCUSDT', 0.005, params_order)
> 
> After this, I tried to use three separate orders, but I have a problem. My problem with using more than one order is that they are not associated, when the position is closed because the price touch the stop loss, the take profit order is not cancelled. So when the price reaches the take profit level it becomes an open market position. If I have to use three orders to have a position with SL and TP I wanted to know how to cancel the TP when the position is closed by the SL.

Hi Mate,

I use 3 differents orders to do that and when the tp or sl is reach I excecute close all orderes.... something like that:

#position:
clienttrade.create_market_order(side=side,symbol=symbol,type='market',size=size,lever=lever)
#stop:
type='market'
            params ={'stopPrice': stopprice,
                    'closePosition': True}
            var.exchange.create_order(symbol, type, side, amount, price=None, params=params)
#take:
exchange.create_order (symbol, 'limit', side, amoun, limitprice, params)


#when pnl =0 then I execute this:

                clienttrade.cancel_all_limit_order(symbol)
                clienttrade.cancel_all_stop_order(symbol)

**Comment by samgermain** [comment]
> ok thanks, but I am trying to place in binance futures a position with SL and TP with only one order. Or this is not possible and I must use three orders, one to place my position and other two for SL and TP?
> 
> this is the code I have to do in one trade, but it seems that it doesn't work: (only open the position, without SL/TP)
> 
> ```js
> let params_order = {
>         'stopLoss': {
>           'type': 'market',
>           'triggerPrice': 15300,
>         },
>         'takeProfit': {
>           'type': 'market',
>           'triggerPrice': 17500,
>         }
>       }
>       exchange.create_market_buy_order('BTCUSDT', 0.005, params_order)
> ```
> 
> After this, I tried to use three separate orders, but I have a problem. My problem with using more than one order is that they are not associated, when the position is closed because the price touch the stop loss, the take profit order is not cancelled. So when the price reaches the take profit level it becomes an open market position. If I have to use three orders to have a position with SL and TP I wanted to know how to cancel the TP when the position is closed by the SL.

The  parameter names are `stopLossPrice` and `takeProfitPrice` and they are numbers, not objects

**Comment by samgermain** [comment]
I'm going to close this issue. Feel free to reopen it if you have any more questions
