### ISSUE TITLE
New Exchange: kex

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1572]
api doc: http://bitcatoss.oss-ap-southeast-1.aliyuncs.com/API1.0.docx
url: https://www.kex.com
fee: https://www.kex.com/about/about.html?id=143
volume: --
address: manager@kex.com
company info: manager@kex.com
tnc: https://www.kex.com/about/about.html?id=145
Registration: --
based country: korea / china
whitepaper: --
priority: low
github group: --
note: ranked top : NA
type: centrailzed ex
discussion: --

**Comment by frosty00** [comment]
not a crypto exchange
