### ISSUE TITLE
New Exchange: Satang Pro Exchange (former TDAX)

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1573]
api doc: https://api-docs.tdax.com/
url: https://tdax.com ( https://satangcorp.com/ )
fee: --
volume: --
address: 89 AIA Capital Center Tower, 20th floor, Suite No. 2058, Ratchadapisek Road, Din Daeng, Din Daeng, Bangkok.
company info: TDAX Co., Ltd.
tnc: https://tdax.com/term
Registration: --
based country: thailand
whitepaper: --
priority: low
github group: --
note: ranked top : NA
type: centrailzed ex
discussion: --

**Comment by tobiasmuehl** [comment]
I guess this isn't really relevant for ccxt, but there have been accusations of TDAX faking volume.

**Comment by kroitor** [comment]
@tobiasmuehl Thanks for letting us know! Can you please post links to the sources?

**Comment by tobiasmuehl** [comment]
@kroitor I'm afraid there aren't any online sources for this

**Comment by kroitor** [comment]
@tobiasmuehl 

> but there have been accusations of TDAX faking volume

When you say there have been accusations, I mean, can you clarify, which accusations exactly? Each accusation has to be stressed carefully, unfair competitors can also spread false-accusations around, so we can't really treat one's word or human statement as evidence.

> @kroitor I'm afraid there aren't any online sources for this

Ok, but, how do you know that it's true or false? Some other trustworthy sources maybe? In other words, is this you, who is actually accusing that exchange? ) No offense, but, you sound like "I know who killed Kennedy, but have no proofs".

**Comment by tobiasmuehl** [comment]
What I mean is that in the local scene in Bangkok, TDAX has gotten themselves in a bad light. There are no official sources for this, it's mostly rumors that are told over beers (of the manipulation, bribery, corruption type), reports of slow withdrawals, [problems with bank accounts (government pressure, however it was not applied to other local exchanges in the same fashion)](https://www.bangkokpost.com/news/general/1418935/ktb-shuts-down-crypto-trade-accounts), questionable ICOs (jfin, TukTuk Pass), 1 million USD daily volume although there is less than 1 BTC on the order book.

Still they are an operating exchange so it makes sense that they'll get integrated into ccxt

**Comment by kroitor** [comment]
@tobiasmuehl got it, thanks for explaining!

**Comment by An-Net** [comment]
This exchange changed name and address to https://satang.pro/exchange/market/BTC-THB (Satang Pro):

- https://twitter.com/ChainNewscom/status/1067725015221702656
- https://www.chainnews.com/news/820557358092.htm
- https://bitcointalk.org/index.php?topic=3037180.0

**Comment by pottertech** [comment]
I use the PHP in CCXT and I need to be able to trade on SatangPro and Bitkub (both Thailand exchanges).  What will it take to get those two finished and added to the CCXT baseline?

**Comment by pottertech** [comment]
Well it has now been 2 years since my last post on SatangPro (May 23, 2021).  Is anyone going to work on adding SatangPro to CCXT?  I think this exchange has proven itself by now...

**Comment by frosty00** [comment]
closing due to low volume / not a priority
