### ISSUE TITLE
Unable to get ccxt pro license

### ISSUE THREAD

**Issue by shep-analytics** [ccxt/ccxt#15748]
- OS: ubuntu 20.04
- Programming Language version: Python 3.10

The CCXT pro website gives me a "Internal Server Error" whenever I try to login to my account and obtain a license.

I see that it has been made a free part of CCXT; however, I am still unable to download and install it.

Thank you

**Comment by CHXER** [comment]
I got the exactly same issue. Try this:
`import ccxt.async_support as ccxtpro`
