### ISSUE TITLE
New Exchange: digatrade

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1574]
api doc: fully powered by anxpro - https://anxv3.docs.apiary.io/#
url: https://digatrade.com
fee: --
volume: --
address: 1500 West Georgia Street, Suite 1300 Vancouver, BC V6G-2Z6 , Canada
company info: DIGATRADE FINANCIAL CORP
tnc: https://digatrade.com/pages/terms
Registration: --
based country: Canada
whitepaper: --
priority: low
github group: --
note: ranked top : NA
type: centrailzed ex
discussion: --

**Comment by jaguarqc** [comment]
The homepage of this exchange seems to indicate this is a dead project.
