### ISSUE TITLE
bybit conditional orders - triggerPrice not working in spot

### ISSUE THREAD

**Issue by kretxo** [ccxt/ccxt#15750]
Hi,

I'm trying to launch conditional orders in Bybit, but the parameter "triggerPrice" is ignored when I'm using Spot market. 
If I use Futures, it works correctly. 
Am is missing anything, or is not implemented for spot market?

DERIVATIVES - USDC_PERPETUAL.
  Here it works fine.
  
  ```
  exchange.options['defaultType'] = 'usdc_perpetual'  
  symbol = 'BTCPERP'  
  type = 'limit'  
  side = 'buy'
  amount = 0.001  
  price = 11000  
  params = {'triggerPrice': 19000}
  order = exchange.create_order(symbol, type, side, amount, price, params)
  print (order)
  ```
  
  output:
  `{'info': {'orderId': '9ce5c114-99b1-4cf4-9277-82cf96cf5def', 'orderLinkId': '', 'mmp': False, 'symbol': 'BTCPERP', 'orderType': 'Limit', 'side': 'Buy', 'orderQty': '0.00100000', 'orderPrice': '11000.00', 'iv': '0', 'timeInForce': 'GoodTillCancel', 'orderStatus': 'Untriggered', 'createdAt': '1668935098028121', 'basePrice': '18999.50', 'triggerPrice': '19000.00', 'takeProfit': '0.00', 'stopLoss': '0.00', 'slTriggerBy': 'UNKNOWN', 'tpTriggerBy': 'UNKNOWN'}, 'id': '9ce5c114-99b1-4cf4-9277-82cf96cf5def', 'clientOrderId': None, 'timestamp': 1668935098028, 'datetime': '2022-11-20T09:04:58.028Z', 'lastTradeTimestamp': None, 'symbol': 'BTC/USD:USDC', 'type': 'limit', 'timeInForce': 'GTC', 'postOnly': False, 'side': 'buy', 'price': 11000.0, 'triggerPrice': '19000.00', 'stopPrice': '19000.00', 'amount': 0.001, 'cost': None, 'average': None, 'filled': None, 'remaining': None, 'status': 'open', 'fee': None, 'trades': [], 'fees': []}`

SPOT
  Here the "triggerPrice" parameter is ignored
    
    ```
    exchange.options['defaultType'] = 'spot'  
    symbol = 'BTC/USDC'  
    type = 'limit'  
    side = 'buy'
    amount = 0.001  
    price = 11000  
    params = {'triggerPrice': 19000}
    
    order = exchange.create_order(symbol, type, side, amount, price, params)
    print (order)
    ```
    
  Output:
`{'id': '1293521538902966784', 'clientOrderId': '1668935783663864', 'timestamp': 1668935783671, 'datetime': '2022-11-20T09:16:23.671Z', 'lastTradeTimestamp': None, 'symbol': 'BTC/USDC', 'type': 'limit', 'timeInForce': 'GTC', 'postOnly': False, 'side': 'buy', 'price': 11000.0, 'triggerPrice': None, 'stopPrice': None, 'amount': 0.001, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 0.001, 'status': 'open', 'fee': None, 'trades': [], 'info': {'orderId': '1293521538902966784', 'orderLinkId': '1668935783663864', 'symbol': 'BTCUSDC', 'createTime': '1668935783671', 'orderPrice': '11000', 'orderQty': '0.001', 'orderType': 'LIMIT', 'side': 'BUY', 'status': 'NEW', 'timeInForce': 'GTC', 'accountId': '5412620', 'execQty': '0', 'orderCategory': '0'}, 'fees': []}`
   

Thank you

**Comment by carlosmiei** [comment]
Hello @kretxo,
I've tested it, and I can confirm that is not working, although the request is following the API spec. We will reach out to Bybit in order to clarify this as soon as possible.

Thanks for letting us know.

**Comment by carlosmiei** [comment]
Hello again @kretxo we have confirmed that `conditional orders` are not yet available through the API for spot markets. Bybit expects to release it in January if everything goes well!

**Comment by ttodua** [comment]
as I had also noted that previously here  https://github.com/ccxt/ccxt/pull/15402#issue-1422407919  including their official response, it is not yet available for spot. I don know why it needs to much time to add just a simple parameter for them, but ... anyway, we should wait and close this issue for now.

**Comment by kretxo** [comment]
OK. Thank you both.
