### ISSUE TITLE
New Exchange: Ace Exchange

### ISSUE THREAD

**Issue by ace-exchange** [ccxt/ccxt#15764]
We're top3 Exchange in Taiwan and Asia, over 150k users.
Many users are asking us for ccxt integration.
Hope we can discuss this integration process. 

Official Website:
https://ace.io/

Official API:
https://github.com/ace-exchange/ace-offical-api-docs/blob/master/api.md

**Comment by ace-exchange** [comment]
I already took a look at
https://gist.github.com/kroitor/5c99bcb9bf1aebf05fec621e5c17b22f
https://ccxt.com/offer/

It's okay for us to hiring Dev team of ccxt, wanna make quick integration.

**Comment by carlosmiei** [comment]
Hello @ace-exchange, can you reach out on Discord? https://discord.gg/ccxt
Thanks

**Comment by sc0Vu** [comment]
I can take a look because it's in Taiwan 👍 🇹🇼 .

**Comment by sc0Vu** [comment]
Ah, PR was merged.
