### ISSUE TITLE
New Exchange: bcex

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1577]
api doc: https://www.bcex.ca/api_market/market
url: https://www.bcex.ca/coins
fee: --
volume: --
address: canada
company info: cascadia blockchain group
tnc: --
Registration: --
based country: canada
whitepaper: --
priority: low
github group: --
note: ranked top : NA
type: centrailzed ex
discussion: --

**Comment by JoshVarty** [comment]
I would like to try my hand at adding this exchange if no one else has started already. This would be my first code contribution. 

Would this PR be a good place for me to start? https://github.com/ccxt/ccxt/pull/3321/

**Comment by kroitor** [comment]
@JoshVarty thx! #3090 is ok, #3321 will need a bit more cleanup before merging... basically, you can look into any of existing exchanges and copy from there. Will be happy to help along the way. The most important info is here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

**Comment by pakaplace** [comment]
Are you still doing this @JoshVarty , if not I'm happy to do it

**Comment by JoshVarty** [comment]
One question I have: How do you guys typically implement order methods? BCEX doesn't have a "Test Endpoints" that I can use. 

I'm thinking about just sending over some ETH and making orders that won't be filled. I'm open to any better suggestions, though.

**Comment by kroitor** [comment]
> I'm thinking about just sending over some ETH and making orders that won't be filled. I'm open to any better suggestions, though.

Yep, we usually do it in the same manner )

**Comment by kroitor** [comment]
Merged in #3471
