### ISSUE TITLE
decimal.Conversion.Syntax Error 

### ISSUE THREAD

**Issue by EkremSel** [ccxt/ccxt#15771]
- OS: Win10
- Programming Language version: python 3.10.7
- CCXT version: 2.1.102

```python
exchange=ccxt.binance({
    'apiKey':'',
    'secret':'',
    'options':{
        'defaultType':'future',
    },
})

 try:
        if  signals_global['signals1'][last_row_index]==1:
            if not in_position:
                params = {
                    'quoteOrderQty': 1000,
                }
                amount = None
                price = None
                order_long=exchange.create_order('SUSHI/USDT','market','buy',amount,price,params)
                
                print(order_long)
                
            else:
                print('already in a position')

except Exception as e:
        print(type(e).__name__, str(e))
```

```
InvalidOperation [<class 'decimal.ConversionSyntax'>]
```

**Comment by samgermain** [comment]
could you share your full code and full error response please?

**Comment by EkremSel** [comment]
Can it be because params quoteOrderQty is supported by Binance spot/margin and not futures?  Would I have to convert it manually?

**Comment by EkremSel** [comment]
@samgermain 

This is the full error:

File "c:\Users\user\stat arb bot.py", line 114, in order_entry
    order_long=exchange.create_order('SUSHI/USDT','market','buy',params)
  File "C:\Python310\lib\site-packages\ccxt\binance.py", line 2996, in create_order
    request['quantity'] = self.amount_to_precision(symbol, amount)
  File "C:\Python310\lib\site-packages\ccxt\base\exchange.py", line 3069, in amount_to_precision
    return self.decimal_to_precision(amount, TRUNCATE, market['precision']['amount'], self.precisionMode, self.paddingMode)
  File "C:\Python310\lib\site-packages\ccxt\base\decimal_to_precision.py", line 55, in decimal_to_precision
    dec = decimal.Decimal(str(n))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

**Comment by EkremSel** [comment]
Binance does not support quote orders on futures.
