### ISSUE TITLE
Poloniex fetchTickers failing

### ISSUE THREAD

**Issue by evan-coygo** [ccxt/ccxt#15785]
- OS: Linux
- Programming Language version: node 14.19.3
- CCXT version: 2.1.102

Poloniex `fetchTickers()` is failing during `parseTicker()`. This is because the tickers endpoint:
```
GET https://api.poloniex.com/markets/ticker24h
```
is returning some markets not returned by the `fetchMarkets()` endpoint 

```
GET https://api.poloniex.com/markets
```

For example, BTC_USDP is included in the response for `GET /markets/ticker24h` but not in `GET /markets`.  This makes ccxt unable to find the corresponding market and throws during `this.market()` within `parseTicker()`. I've contacted Poloniex support to inquire about if this is a bug on their end but thought I should report it here as well for visibility.

**Comment by carlosmiei** [comment]
Hello @evan-coygo, Yeah, we bumped on this a few days ago and we still don't know why `/markets` is not returning the PAX Dollar market. However, we add extra protection, so this error should no happen in the latest version.

Can you update your ccxt version and try again, please?

**Comment by evan-coygo** [comment]
Yup looks like I was actually one patch version behind. Thanks!
