### ISSUE TITLE
pip3 install ccxt Error

### ISSUE THREAD

**Issue by zxlii** [ccxt/ccxt#15787]
i'm install the ccxt package use pip like:
```
[root@iZj6c52iwklk71rzg3ripuZ ~]# pip3 install ccxt
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting ccxt
  Could not find a version that satisfies the requirement ccxt (from versions: )
No matching distribution found for ccxt
[root@iZj6c52iwklk71rzg3ripuZ ~]# python3 --version
Python 3.6.8
[root@iZj6c52iwklk71rzg3ripuZ ~]# pip3 -V
pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
```

' Could not find a version that satisfies the requirement ccxt (from versions: )???'

why?

i need some help，thank you！

- OS: centos8.2
- Programming Language version: python3.6.8
- CCXT version: default

**Comment by carlosmiei** [comment]
Hello @zxlii not sure what is preventing the installation, but as the warning suggests installing it with `root` is not a good idea. 
Can you try without it?
`pip3 install --user ccxt`

**Comment by frosty00** [comment]
seems related to user's environment, unable to reproduce
