### ISSUE TITLE
python proxy documentation wrong

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#15783]
- OS:
- Programming Language version: python
- CCXT version: 

The python [proxy documentation](https://docs.ccxt.com/en/latest/install.html#proxy) seems wrong / no longer functional.

it suggests that (for regular usecases) - using environment variables works.

```
$ export HTTP_PROXY="http://10.10.1.10:3128"
$ export HTTPS_PROXY="http://10.10.1.10:1080"
```

this may be true for "regular" usage of requests - it seems to be non-working in the ccxt context.

a very simple reproduction - best use a proxy that does not exist.

`export HTTPS_PROXY="http://localhost:1080"`

``` python
import ccxt
exchange = ccxt.binance()
res = exchange.load_markets()   # expected to fail - since the proxy is invalid (does not fail!)

import ccxt
exchange = ccxt.binance({'proxies': {'https': 'http://localhost:1080'}})
res = exchange.load_markets()   # This one really fails - since i'm using an invalid proxy.

```

i suspect it's because proxies is set explicitly on the object ... i can't really reproduce this on a regular requests call outside of the ccxt context though.

https://github.com/ccxt/ccxt/blob/93d25b243cbda568155ae22867d1d8707969e5ec/python/ccxt/base/exchange.py#L594

Either way - i think this should either be fixed somehow - or the documentation should be updated to no longer list environment variables as acceptable proxy method.

**Comment by sc0Vu** [comment]
Hi @xmatthias 

Have you initialized as `HttpsProxyAgent`?

**Comment by xmatthias** [comment]
I'm not sure i understand this comment?

I'm attempting to follow the ccxt docs by setting the environment variables for proxies - which don't work properly for basic ccxt requests.

**Comment by xzmeng** [comment]
It confused me too after I haven't used ccxt for several months, apparently now it doesn't respect the environment any longer and the docs is out of date or it's a bug.

**Comment by ttodua** [comment]
late update here, but proxies were unified several months ago, and you can read updated manual here: https://docs.ccxt.com/#/?id=proxy
also, proxies for Websockets are also being unified in upcoming days.
let me know if any question
