### ISSUE TITLE
OKEx v5: How to create new order by websocket instead of REST

### ISSUE THREAD

**Issue by BlockchainHe** [ccxt/ccxt#15786]
- OS: ubuntu 22.04 TLS
- Programming Language version: Python 3.6
- CCXT version: 2.2.5

OKEx v5: How to create new order by websocket instead of REST？？
Have some examples？

**Comment by sc0Vu** [comment]
Hi @BlockchainHe 

Currently, we don't have interface for sending order through websocket (ccxt.pro). Imho, you probably can do something like this:

```JS
await okxPro.authenticate()

// sending order directly to server
// https://www.okx.com/docs-v5/en/#websocket-api-trade-place-order
const res = await okxPro.watch (url, messageHash, orderRequest, subscribeHash, subscription )
```

**Comment by BlockchainHe** [comment]
If possible, I hope you can add an example to this project.

Thanks

**Comment by BlockchainHe** [comment]
sorry, send the trade request in this way will block, Could you please help me to see what is the problem?
`okPro = ccxtpro.okex({
        "apiKey": params["okex"]["apikey"],
        "secret": params["okex"]["secret"],
        'password': params["okex"]["password"],
        'options': {
            'defaultType': params["okex"]["type"],
            'watchOrderBook': {
                'depth': 'bbo-tbt',  # tick-by-tick best bidask
            },
        }
    })
    url = "wss://ws.okx.com:8443/ws/v5/private"

    await okPro.load_markets()
    await okPro.authenticate()
    trade_param = {"id": "1512", "op": "order", "args": [
        {"side": "buy", "instId": "BTC-USDT", "tdMode": "isolated", "ordType": "limit", "px": "19777", "sz": "1"}]}
    await okPro.load_markets()
    await okPro.watch(url, "create_order", json.dumps(trade_param), "create_order")

    await okPro.close()`

**Comment by BlockchainHe** [comment]
sorry, send the trade request in this way will block, Could you please help me to see what is the problem?
`
okPro = ccxtpro.okex({
"apiKey": params["okex"]["apikey"],
"secret": params["okex"]["secret"],
'password': params["okex"]["password"],
'options': {
'defaultType': params["okex"]["type"],
'watchOrderBook': {
'depth': 'bbo-tbt', # tick-by-tick best bidask
},
}
})
url = "wss://ws.okx.com:8443/ws/v5/private"

await okPro.load_markets()
await okPro.authenticate()
trade_param = {"id": "1512", "op": "order", "args": [
    {"side": "buy", "instId": "BTC-USDT", "tdMode": "isolated", "ordType": "limit", "px": "19777", "sz": "1"}]}
await okPro.load_markets()
await okPro.watch(url, "create_order", json.dumps(trade_param), "create_order")

await okPro.close()
`

**Comment by BlockchainHe** [comment]
sorry, send the trade request in this way will block, Could you please help me to see what is the problem?
`    okPro = ccxtpro.okex({
        "apiKey": params["okex"]["apikey"],
        "secret": params["okex"]["secret"],
        'password': params["okex"]["password"],
        'options': {
            'defaultType': params["okex"]["type"],
            'watchOrderBook': {
                'depth': 'bbo-tbt',  # tick-by-tick best bidask
            },
        }
    })
    url = "wss://ws.okx.com:8443/ws/v5/private"

    await okPro.load_markets()
    await okPro.authenticate()
    trade_param = {"id": "1512", "op": "order", "args": [
        {"side": "buy", "instId": "BTC-USDT", "tdMode": "isolated", "ordType": "limit", "px": "19777", "sz": "1"}]}
    await okPro.load_markets()
    await okPro.watch(url, "create_order", json.dumps(trade_param), "create_order")

    await okPro.close()`

**Comment by carlosmiei** [comment]
@BlockchainHe we now support `createOrderWs` on OKX.
