### ISSUE TITLE
New Exchange: bibao 

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1579]
api doc: ---
url: https://www.bibaovip.com
fee: --
volume: --
address: 香港九龙长沙湾长裕街5号中国宏兴大厦11楼B室
company info: --
tnc: --
Registration: --
based country: china
whitepaper: --
priority: low
github group: --
note: ranked top : NA
type: centrailzed ex
discussion: --

this exchange is coming soon. almost done

**Comment by An-Net** [comment]
This exchange does not work anymore.
