### ISSUE TITLE
How to get info on locked savings products on Binance

### ISSUE THREAD

**Issue by LLIax** [ccxt/ccxt#15804]
- OS: Linux
- Programming Language version: Python 3.10.8
- CCXT version: 2.2.1

How to get info on locked savings products on Binance? When I try to fetch savings balance with following code

```
api_key = exchange.api_key
api_secret = exchange.api_secret
binance = ccxt.binance({'apiKey': api_key, 'secret':api_secret})
balance = binance.fetch_balance({'type':'savings'})
```
I'm getting only flexible positions

**Comment by sc0Vu** [comment]
Hi @LLIax 

For the `savings` type, the api we used only return flexible savings. If you want to fetch locked balance, use implicit method before we update this function:

```
// product could be: STAKING, F_DEFI, L_DEFI
const fixedPositions = await sapiGetStakingPosition ({"product":"STAKING"})
```

**Comment by LLIax** [comment]
Thanks, it works.
