### ISSUE TITLE
phemex transfer funds Permission Denied

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#15815]
CCXT Version: 1.93.3

amountToTransfer = round(0.05 * totalFunds) #this is wrong,need amount of funds of the opposite account
            print('amountToTransfer:')
            print(amountToTransfer)
            #TODO if not enough funds found to transfer then send email/sms
            transfer_params = {}
            print('Trying to start transfer')
            print(code)
            print(fromAccount)
            print(toAccount)
            transfer = exchange.transfer (code, amountToTransfer, fromAccount, toAccount, transfer_params)
            print('transfer:')
            print(transfer)

Trying to start transfer
USD
UID_NUMBERICANTDISCLOSEINPUBLICCHAT
UID_NUMBERICANTDISCLOSEINPUBLICCHAT
Error on line 541 PermissionDenied phemex {"code":34003,"msg":"Access forbidden","data":null}
Got an error PermissionDenied ('phemex {"code":34003,"msg":"Access forbidden","data":null}',) , retrying in 5 seconds...

**Comment by adamrg73** [comment]
any idea why this is happening?

**Comment by adamrg73** [comment]
Hi I got it to work with code='USDT' first test.. but had to use an api key and secret from the Main account, not sub account.

**Comment by adamrg73** [comment]
Ok, so how do you specify you want to transfer from the futures accounts into a sub account's futures account ?? not spot ?
and also if I need to, how do you specify going from spot account into futures account?

**Comment by adamrg73** [comment]
no support on this issue? anybody alive?

**Comment by Dan-krm** [comment]
Hey @adamrg73 sorry for the late response, I'm looking into it now, I am going to add some functionality to the transfer method on Phemex and provide some examples. I don't think transferring from future-main to spot-main is working properly at the moment either. Once it's completed you won't be able to transfer from spot-main to future-sub for example but transferring between spot-main and spot-sub or future-main and future-sub should work

**Comment by adamrg73** [comment]
> Hey @adamrg73 sorry for the late response, I'm looking into it now, I'll probably add some functionality to the transfer method on Phemex then provide some examples. Once it's completed you won't be able to transfer from spot-main to future-sub for example but transferring between spot-main and spot-sub or future-main and future-sub should work

ya that will suffice. But, if you have a direction parameter but if you can try and have it so you can put in and out from spot to future, that way if need be, you can basically go from spot to future but in more steps.

Here is some python code to reference from phemex api.
https://github.com/harper1999/phemex-python-api/blob/API-docs/examples/REST/account/main%26sub%20universal%20transfer.py

https://github.com/harper1999/phemex-python-api

**Comment by adamrg73** [comment]
if you need help with any pieces of code in python I can write some, then you can commit it, let me know plz I want to speed things up, im trying to use ccxt as much as possible.

**Comment by Dan-krm** [comment]
@adamrg73 there's a Phemex main-account to sub-account transfer example here: https://github.com/ccxt/ccxt/blob/master/examples/py/phemex-transfer.py 
You can transfer between the main future account and the sub future account by providing the 'bizType' parameter as 'PERPETUAL'

Transferring between main and sub accounts requires the UID's as a string.
Transferring between spot and future accounts on your sub-account requires using the subaccounts separate API key and secret.

I've changed the naming of the `future` account to `swap` and I've updated the example in this PR #15846 to include a few more examples:
```
# Example 1: Transfer between the spot main-account and swap main-account
def main_account_transfer():
    exchange = ccxt.phemex({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET',
        # 'verbose': True,  # for debug output
    })
    code = 'USDT'
    amount = 10
    fromAccount = 'spot'
    toAccount = 'swap'
    params = {}

    try:
        transfer = exchange.transfer(code, amount, fromAccount, toAccount, params=params)
        pprint(transfer)
    except Exception as err:
        print(err)


# Example 2: Transfer between main-account and sub-account (Requires the main and sub-account UID's found on the account/sub-accounts page on Phemex)
def transfer_between_main_and_sub_accounts():
    exchange = ccxt.phemex({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET',
        # 'verbose': True,  # for debug output
    })
    code = 'USDT'
    amount = 10
    fromAccount = '4148428'
    toAccount = '4663243'
    # set the bizType to 'SPOT' or 'PERPETUAL', default is 'SPOT'
    bizType = 'PERPETUAL'
    params = {
        'bizType': bizType
    }

    try:
        transfer = exchange.transfer(code, amount, fromAccount, toAccount, params=params)
        pprint(transfer)
    except Exception as err:
        print(err)


# Example 3: Transfer between the spot sub-account and swap sub-account (Requires a sub-account API key and secret)
def sub_account_transfer():
    exchange = ccxt.phemex({
        'apiKey': 'YOUR_SUB_ACCOUNT_API_KEY',
        'secret': 'YOUR_SUB_ACCOUNT_SECRET',
        # 'verbose': True,  # for debug output
    })
    code = 'USDT'
    amount = 10
    fromAccount = 'spot'
    toAccount = 'swap'
    params = {}

    try:
        transfer = exchange.transfer(code, amount, fromAccount, toAccount, params=params)
        pprint(transfer)
    except Exception as err:
        print(err)


main_account_transfer()
# transfer_between_main_and_sub_accounts()
# sub_account_transfer()
```

**Comment by adamrg73** [comment]
does currency USD work with your last update?
Looks like you got USDT working, just making sure.

**Comment by adamrg73** [comment]
> @adamrg73 there's a Phemex main-account to sub-account transfer example here: https://github.com/ccxt/ccxt/blob/master/examples/py/phemex-transfer.py You can transfer between the main future account and the sub future account by providing the 'bizType' parameter as 'PERPETUAL'
> 
> Transferring between main and sub accounts requires the UID's as a string. Transferring between spot and future accounts on your sub-account requires using the subaccounts separate API key and secret.
> 
> I've changed the naming of the `future` account to `swap` and I've updated the example in this PR #15846 to include a few more examples:
> 
> ```
> # Example 1: Transfer between the spot main-account and swap main-account
> def main_account_transfer():
>     exchange = ccxt.phemex({
>         'apiKey': 'YOUR_API_KEY',
>         'secret': 'YOUR_SECRET',
>         # 'verbose': True,  # for debug output
>     })
>     code = 'USDT'
>     amount = 10
>     fromAccount = 'spot'
>     toAccount = 'swap'
>     params = {}
> 
>     try:
>         transfer = exchange.transfer(code, amount, fromAccount, toAccount, params=params)
>         pprint(transfer)
>     except Exception as err:
>         print(err)
> 
> 
> # Example 2: Transfer between main-account and sub-account (Requires the main and sub-account UID's found on the account/sub-accounts page on Phemex)
> def transfer_between_main_and_sub_accounts():
>     exchange = ccxt.phemex({
>         'apiKey': 'YOUR_API_KEY',
>         'secret': 'YOUR_SECRET',
>         # 'verbose': True,  # for debug output
>     })
>     code = 'USDT'
>     amount = 10
>     fromAccount = '4148428'
>     toAccount = '4663243'
>     # set the bizType to 'SPOT' or 'PERPETUAL', default is 'SPOT'
>     bizType = 'PERPETUAL'
>     params = {
>         'bizType': bizType
>     }
> 
>     try:
>         transfer = exchange.transfer(code, amount, fromAccount, toAccount, params=params)
>         pprint(transfer)
>     except Exception as err:
>         print(err)
> 
> 
> # Example 3: Transfer between the spot sub-account and swap sub-account (Requires a sub-account API key and secret)
> def sub_account_transfer():
>     exchange = ccxt.phemex({
>         'apiKey': 'YOUR_SUB_ACCOUNT_API_KEY',
>         'secret': 'YOUR_SUB_ACCOUNT_SECRET',
>         # 'verbose': True,  # for debug output
>     })
>     code = 'USDT'
>     amount = 10
>     fromAccount = 'spot'
>     toAccount = 'swap'
>     params = {}
> 
>     try:
>         transfer = exchange.transfer(code, amount, fromAccount, toAccount, params=params)
>         pprint(transfer)
>     except Exception as err:
>         print(err)
> 
> 
> main_account_transfer()
> # transfer_between_main_and_sub_accounts()
> # sub_account_transfer()
> ```

looks great can wait to try , with USD currency though, gona try it tonite or tomorrow

**Comment by Dan-krm** [comment]
Any currency that can be transferred should work the same, just adjust the code variable, also keep in mind the examples are using the account name 'swap' instead of 'future' using 'swap' won't work until the PR I submitted is merged and using 'future' will stop working once the PR is merged

**Comment by adamrg73** [comment]
> Any currency that can be transferred should work the same, just adjust the code variable, also keep in mind the examples are using the account name 'swap' instead of 'future' using 'swap' won't work until the PR I submitted is merged and using 'future' will stop working once the PR is merged

ok sounds good thanks a lot!

**Comment by adamrg73** [comment]
> Any currency that can be transferred should work the same, just adjust the code variable, also keep in mind the examples are using the account name 'swap' instead of 'future' using 'swap' won't work until the PR I submitted is merged and your CCXT version is updated and using 'future' will stop working once the PR is merged and your CCXT version is updated

i know they use the word swap.but lately theyre using the word futures on their branding.. what do most exchanges use, we should use what most exchanges use to make the code more compatible.. I can ask phemex what their future plans are I have close convos with their devs daily..
let me know if i should ask

**Comment by Dan-krm** [comment]
> > Any currency that can be transferred should work the same, just adjust the code variable, also keep in mind the examples are using the account name 'swap' instead of 'future' using 'swap' won't work until the PR I submitted is merged and your CCXT version is updated and using 'future' will stop working once the PR is merged and your CCXT version is updated
> 
> i know they use the word swap.but lately theyre using the word futures on their branding.. what do most exchanges use, we should use what most exchanges use to make the code more compatible.. I can ask phemex what their future plans are I have close convos with their devs daily.. let me know if i should ask

CCXT calls perpetual futures `swap` and delivery futures with an expiry `future`
