### ISSUE TITLE
New Exchange: coingogo

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1581]
api doc: ---
url: https://www.coingogo.com
fee: --
volume: --
address: beijing
company info: --
tnc: --
Registration: --
based country: china
whitepaper: --
priority: low
github group: --
note: ranked top : NA
type: centrailzed ex
discussion: --
sign up: http://www.coingogo.com/site/signup?gid=NTcxNDk%3D

**Comment by damien-piedanna** [comment]
This exchange does not seem to exist anymore, I think that this issue can be closed.
