### ISSUE TITLE
New Exchange: topbtc

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1582]
api doc: ---
url: https://www.topbtc.com
fee: --
volume: --
address: 
company info: The Commonwealth of Australia DABTC PTY LTD.
tnc: --
Registration: --
based country: China
whitepaper: --
priority: low
github group: --
note: ranked top : NA
type: centrailzed ex
discussion: --
sign up: --

**Comment by jjhesk** [comment]
here is the doc: https://documenter.getpostman.com/view/2597586/topperex/RW1bmyPW

**Comment by An-Net** [comment]
Scam allegations:

- https://bitcointalk.org/index.php?topic=5174704.0

- https://www.forexbrokerz.com/brokers/topbtc-review

- https://www.reddit.com/r/voise/comments/7vv41w/voise_on_topbtc_exchange/

- https://deeponion.org/community/threads/are-you-ok-with-topbtc.37009/

- https://bitcointalk.org/index.php?topic=2524648.0
