### ISSUE TITLE
New Exchange: komid

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1583]
api doc: ---
url: https://www.komid.co.kr
fee: --
volume: --
address: 05510 서울시 송파구 올림픽로35가길 10 더샵스타파크 B동 605호
company info: 사업자등록번호 : 449-86-00761
tnc: --
Registration: --
based country: Korea
whitepaper: --
priority: low
github group: --
note: ranked top : NA
type: centrailzed ex
discussion: --
sign up: --

**Comment by frosty00** [comment]
@jjhesk 

Asking a bit much ...   ;0

**Comment by Guillerbr** [comment]
ok

**Comment by An-Net** [comment]
The website doesn't work anymore:

- https://blog.naver.com/komid2017/221468465952
