### ISSUE TITLE
Pypl is now missing versions 1.59.9 through 1.59.16?

### ISSUE THREAD

**Issue by j-rp** [ccxt/ccxt#15840]
I'm aware that these are old versions, but is there a reason that the version numbering on pypl now jumps from 1.59.8 to 1.59.20?  I'm curious as to the rationale for the removal of these versions from pypl - seems like a fairly specific cleanup?

**Comment by kroitor** [comment]
Hey! Thanks for asking. The reason is simple - PyPI does not allow us to
store more than 20gb of releases, so we clean up our old archives every
once in a while. Hope for your understanding. We keep each minor version
x.1.1 though, for history.

**Comment by j-rp** [comment]
Thank you!!  You're a prince of a man.
