### ISSUE TITLE
Recoil/React

### ISSUE THREAD

**Issue by Showgofar** [ccxt/ccxt#15851]
Hello

At pro version Recoil/React  was included
and also it was check if it exist

if (!class_exists('Recoil\\React\\ReactKernel')) {
            throw new ccxt\NotSupported("Recoil is not installed\n\ncomposer require --ignore-platform-reqs recoil/react:\"1.0.2\"\n\n");
        }
and for now seems that Recoil doesnt included anymore
Could you please check

**Comment by carlosmiei** [comment]
Hello @Showgofar,

Yes it was replaced by ReactPHP: https://github.com/reactphp/reactphp

**Comment by Showgofar** [comment]
Ok
What was the reason?
BTW examples still contain Recoil/React

**Comment by ttodua** [comment]
> Ok What was the reason? BTW examples still contain Recoil/React

thanks for reporting, I will try to fix those examples.  Recoil has been totally removed from all dependencies and replaced by reactPHP

**Comment by frosty00** [comment]
closing this error, please reopen if it persists
