### ISSUE TITLE
kraken fetch_min_order_sizes() broken

### ISSUE THREAD

**Issue by davewwww** [ccxt/ccxt#1585]
- OS: linux
- Programming Language version: php
- CCXT version: 1.10.902
- Exchange: kraken
- Method: fetch_min_order_sizes()

**Error:**
> Undefined offset: 1
>   at vendor\ccxt\ccxt\php\kraken.php:219

The request for "https://kraken.zendesk.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-" delivers not the expected html output.
output of $html (line 210) is:
`<html><body>You are being <a href="https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-">redirected</a>.</body></html>`

apparently a redirect protection

**Comment by kroitor** [comment]
@davewwww can you please update ccxt to version 1.10.904, then retry the same code again and report whether it works normally for you or not? Thx!

**Comment by davewwww** [comment]
@kroitor yes, the request works, but now the parsing is broken:

> ErrorException:
> Warning: explode() expects at least 2 parameters, 1 given
> at vendor\ccxt\ccxt\php\kraken.php:224
> at ccxt\kraken->fetch_min_order_sizes()

**Comment by kroitor** [comment]
@davewwww ok, tested with 1.10.906 and should work normally now. Let us know if you still have difficulties with it. Thx!

**Comment by davewwww** [comment]
btw, that code works for me 

```     
        $result = [];
        if (preg_match('/div class=\"article-body.*ul\>(.*)\<\/ul.*/isU', $html, $list)) {
            if (preg_match_all('/li>\w+ \((\w+)\)\: ([\d\.?]+)\<\/li\>/', $list[1], $listItems)) {
                foreach ($listItems[0] as $key => $item) {
                    $currency = $listItems[1][$key];
                    $limit = (float) $listItems[2][$key];
                    $result[$currency] = $limit;
                }
            }
        }
        
        return $result;
```

**Comment by kroitor** [comment]
@davewwww https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code ;)

**Comment by davewwww** [comment]
i see ..

now it works!

**Comment by kroitor** [comment]
@davewwww ok, thx for letting me know and for your feedback! Cheers!
