### ISSUE TITLE
Always get 403 forbidden when use await mexc.loadMarkets()

### ISSUE THREAD

**Issue by James1847** [ccxt/ccxt#15873]
When I'm going to load all the markets from below, I will always the the error below even if I tried to change my IP address, but it will success  last week, and now I can even runs well using command line on Terminal:  curl  https://www.mexc.com/open/api/v2/market/coin/list

- OS: MACOS/ LINUX
- Programming Language version: nodejs 18.02
- CCXT version: latest

```
export const exchangeArray = [
    {name: "kraken", exchange: kraken},
    {name: "bitfinex", exchange: bitfinex},
    {name: "huobipro", exchange: huobipro},
    {name: "okex", exchange: okex},
    {name: "mexc", exchange: mexc},
    {name: "binance", exchange: binance},
    {name: "kucoin", exchange: kucoin},
    // {name: "gateio", exchange: geteio}
]


export const loadExchanges = async () => {
    let promises = [];
    for (let i = 0; i < exchangeArray.length; i++) {
        promises.push(exchangeArray[i].exchange.loadMarkets())
    }
    await Promise.all(promises)
    return "success"

}
```

```
ExchangeNotAvailable: mexc GET https://www.mexc.com/open/api/v2/market/coin/list 403 Forbidden <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;www&#46;mexc&#46;com&#47;open&#47;api&#47;v2&#47;market&#47;coin&#47;list" on this server.<P>
Reference&#32;&#35;18&#46;1fcbdc17&#46;1669729350&#46;8cdc15
</BODY>
</HTML>

    at mexc.handleHttpStatusCode (/Users/amandachadwick/PycharmProjects/freelancer/0_mine/node_modules/ccxt/js/base/Exchange.js:753:19)
    at /Users/amandachadwick/PycharmProjects/freelancer/0_mine/node_modules/ccxt/js/base/Exchange.js:600:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (/Users/amandachadwick/PycharmProjects/freelancer/0_mine/node_modules/ccxt/js/base/functions/time.js:181:20)
    at async mexc.fetch2 (/Users/amandachadwick/PycharmProjects/freelancer/0_mine/node_modules/ccxt/js/base/Exchange.js:1901:16)
    at async mexc.request (/Users/amandachadwick/PycharmProjects/freelancer/0_mine/node_modules/ccxt/js/base/Exchange.js:1905:16)
    at async mexc.fetchCurrencies (/Users/amandachadwick/PycharmProjects/freelancer/0_mine/node_modules/ccxt/js/mexc.js:408:26)
    at async mexc.loadMarketsHelper (/Users/amandachadwick/PycharmProjects/freelancer/0_mine/node_modules/ccxt/js/base/Exchange.js:624:26)
    at async Promise.all (index 4)
    at async loadExchanges (file:///Users/amandachadwick/PycharmProjects/freelancer/0_mine/cex/cex.js:32:5) {
  constructor: [class ExchangeNotAvailable extends NetworkError]
}

Node.js v18.12.1



```

**Comment by ttodua** [comment]
@James1847 thanks for reporting. We are already working on it. When this issue gets closed, it means the fix is applied and then updated your ccxt, and it will work.

**Comment by James1847** [comment]
> @James1847 thanks for reporting. We are already working on it. When this issue gets closed, it means the fix is applied and then updated your ccxt, and it will work.

Bro, what's going on, is the error with the code or with my own ip address?

**Comment by ttodua** [comment]
> > @James1847 thanks for reporting. We are already working on it. When this issue gets closed, it means the fix is applied and then updated your ccxt, and it will work.
> 
> Bro, what's going on, is the error with the code or with my own ip address?

no, IP address is of no matter. MEXC support is looking into issue, they will need time.

**Comment by nilswx** [comment]
On my machine, `curl` works but `fetch` only works in the browser - not on Node.js.

Looks like Akamai is fingerprinting and blocking these HTTPS requests based on TLS ciphers. Workaround described [here](https://httptoolkit.com/blog/tls-fingerprinting-node-js/), but I agree that MEXC should fix this.

**Comment by nilswx** [comment]
On my machine, `curl` works but `fetch` only works in the browser - not on Node.js (v19).

It's not the IP, or the request content/headers, nor the `User-Agent`. Akamai is fingerprinting and blocking these HTTPS requests to MEXC based on your TLS ciphers. Explanation [here](https://httptoolkit.com/blog/tls-fingerprinting-node-js/), but I agree that MEXC should fix this.

Until then, just reorder your TLS ciphers at the start of your program. Fixed it for me.

```js
const tls = require('tls');
tls.DEFAULT_CIPHERS = 'TLS_AES_256_GCM_SHA384:ECDHE-RSA-AES256-GCM-SHA384';
tls.DEFAULT_MIN_VERSION = 'TLSv1.2';
```

```js
fetch('https://www.mexc.com/open/api/v2/market/coin/list')
  .then(res => res.json())
  .then(console.log); // Works now!
```

**Comment by James1847** [comment]
I asked the mexc workers, they said my IP has been banned cause exceed the rate limit, they already helped me unbanned my ip, and now I can use it again.

**Comment by ttodua** [comment]
this issue is also related not IP but what @nilswx described, so we still have to wait their fix.

**Comment by James1847** [comment]
> this issue is also related not IP but what @nilswx described, so we still have to wait their fix.

Ok, I will explain that the first time I asked the worker for help in the mexc global telegram api group, He told me my IP has been banned from their system cause rate limit issues, after 3 days, he told me my IP has been unbanned from their system, but Actually it still didn't work, I still got 403 forbidden problems with that, So I continue asking for help with that guy, he said he will check somthing for me, Then I waited for at least 5 days, And today he told me my ip just been unbanned right now, He wanna me to try for the second time, And now it's working well. So I think it's maybe they didin't successfully unbanned the ip from their system, maybe they need other procedure to make it work again
