### ISSUE TITLE
Mexc create order:    TypeError: string indices must be integers

### ISSUE THREAD

**Issue by Nitrix321** [ccxt/ccxt#15878]
Hello, 

probably I made a stupid mistake but unfortunately I can't find the error. I've tried "everything" for hours now...
Perhaps someone can see what I have done wrong in this specific case?
Thanks in advance!

- OS: Windows 10
- Programming Language version: Python Spyder 3.9
- CCXT version: 2.1.13

```
mexc = ccxt.mexc3({
    'enableRateLimit': True,
    'apiKey': mexcconfig.api_key,
    'secret': mexcconfig.api_secret,
    'options': {'defaultType': 'swap'
    }})

def ask_bid():
    ob = mexc.fetch_order_book(symbol)
    #print(ob)

    bid = ob['bids'][0][0]
    ask = ob['asks'][0][0]
    
    return ask, bid, 

bid = ask_bid()[1]
ask = ask_bid()[0]

#print(ask_bid())

symbol = 'ETH/USDT'
timeframe = '1m'
type = 5
side = 1
pos_size = 1

params={
        "openType": 1,
        "leverage": 10,
        }

mexc.create_swap_order(symbol, type, side, amount=pos_size, price=bid, params=params)



```

```
File "C:\Users\Dell\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\dell\desktop\bybit\mexctest.py", line 198, in <module>
    mexc.create_swap_order(symbol, type, side, amount=pos_size, price=bid, params=params)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\mexc3.py", line 1666, in create_swap_order
    symbol = market['symbol']

TypeError: string indices must be integers
```

**Comment by samgermain** [comment]
> mexc = ccxt.mexc3({
>     'enableRateLimit': True,
>     'apiKey': mexcconfig.api_key,
>     'secret': mexcconfig.api_secret,
>     'options': {'defaultType': 'swap'
>     }})
> 
> def ask_bid():
>     ob = mexc.fetch_order_book(symbol)
>     #print(ob)
> 
>     bid = ob['bids'][0][0]
>     ask = ob['asks'][0][0]
>     
>     return ask, bid, 
> 
> bid = ask_bid()[1]
> ask = ask_bid()[0]
> 
> #print(ask_bid())
> 
> symbol = 'ETH/USDT'
> timeframe = '1m'
> type = 5
> side = 1
> pos_size = 1
> 
> params={
>         "openType": 1,
>         "leverage": 10,
>         }
> 
> mexc.create_swap_order(symbol, type, side, amount=pos_size, price=bid, params=params)

`create_swap_order` is an internal method, don't use it, instead use `create_order` and use [swap symbols](https://docs.ccxt.com/en/latest/manual.html#perpetual-swap-perpetual-future) like `ETH/USDT:USDT`

**Comment by Nitrix321** [comment]
Hi @samgermain, thank you but

when I use symbol ETH/USDT:USDT the following error occurs. With symbol ETH/USDT as I used before it also still doesn't work.


   File "C:\Users\Dell\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\dell\desktop\bybit\mexctest.py", line 200, in <module>
    mexc.create_order(symbol, type, side, amount=pos_size, price=bid, params=params)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\mexc3.py", line 1601, in create_order
    return self.create_swap_order(market, type, side, amount, price, marginMode, query)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\mexc3.py", line 1670, in create_swap_order
    raise NotSupported(self.id + ' createSwapOrder() does not support yet self symbol:' + symbol)

NotSupported: mexc3 createSwapOrder() does not support yet self symbol:ETH/USDT:USDT

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\mexc3.py", line 1670, in create_swap_order
    raise NotSupported(self.id + ' createSwapOrder() does not support yet self symbol:' + symbol)

NotSupported: mexc3 createSwapOrder() does not support yet self symbol:ETH/USDT:USDT

**Comment by Nitrix321** [comment]
Unfortunately I still couldn't fix my issue. I tried several different create_order types, with different params and symbols.
I also tried advise like mentioned here [#12332](https://github.com/ccxt/ccxt/issues/12332). 

I tried the following create order types

1)
mexc.create_swap_order(symbol="BTC/USDT:USDT", type=5, side=1, amount=2, price=None, params={
  "openType": 1,
  "leverage": 20,
  })

TypeError: create_swap_order() got an unexpected keyword argument 'symbol'

2)
symbol = 'BTC/USDT:USDT'

mexc.create_swap_order(symbol, type=5, side=1, amount=2, price=None, params={
  "openType": 1,
  "leverage": 20,
  })

TypeError: string indices must be integers

3)
symbol = 'BTC/USDT:USDT'

mexc.create_order(symbol, type=5, side=1, amount=2, price=None, params={
  "openType": 1,
  "leverage": 20,
  })

NotSupported: mexc3 createSwapOrder() does not support yet self symbol:BTC/USDT:USDT

Could I confirm you are able to submit an order of any type to MEXC via one of the codes above?

**Comment by samgermain** [comment]
Do you still have `'options': {'defaultType': 'swap'}` inside the parameter that you pass to the exchange constructor?

**Comment by Nitrix321** [comment]
Hi, yes 'options': {'defaultType': 'swap'} still inside. 
As you can see above I tried create_swap_order AND create_order as you said, but create_order also gives me error message as you can see above.

**Comment by samgermain** [comment]
> Hi, yes 'options': {'defaultType': 'swap'} still inside. As you can see above I tried create_swap_order AND create_order as you said, but create_order also gives me error message as you can see above.

Can you provide a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for you third order (the one that just uses `create_order`)?

**Comment by Nitrix321** [comment]
Hello, sorry I was not at home the last few days.

Here's the example you asked for.



import ccxt
import pandas as pd
import numpy as np
import mexcconfig
from datetime import date, datetime, timezone, tzinfo
import time, schedule



mexc = ccxt.mexc3({
    'enableRateLimit': True,
    'apiKey': mexcconfig.api_key,
    'secret': mexcconfig.api_secret,
    'options': {'defaultType': 'swap'
    }})



mexc.create_order(symbol= 'BTC/USDT:USDT', type=5, side=1, amount=2, price=None, params={
  "openType": 1,
  "leverage": 20,
  })



And the error message here:

  File "C:\Users\Dell\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\dell\desktop\bybit\mexctest2.py", line 26, in <module>
    mexc.create_order(symbol= 'BTC/USDT:USDT', type=5, side=1, amount=2, price=None, params={

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\mexc3.py", line 1601, in create_order
    return self.create_swap_order(market, type, side, amount, price, marginMode, query)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\mexc3.py", line 1670, in create_swap_order
    raise NotSupported(self.id + ' createSwapOrder() does not support yet self symbol:' + symbol)


NotSupported: mexc3 createSwapOrder() does not support yet self symbol:BTC/USDT:USDT

**Comment by samgermain** [comment]
> 

It looks like it's related to these lines https://github.com/ccxt/ccxt/blob/2496b2f5e20e29a717f6f65c3c99ee963fe67194/js/mexc3.js#L351 , and I'm not sure why those are there. It looks like @carlosmiei added them

**Comment by samgermain** [comment]
> ```python
> TypeError: create_swap_order() got an unexpected keyword argument 'symbol'
> ```

This error makes sense because `create_swap_order()` is an internal method that takes an argument named `market` but does not take an argument named `symbol` so that's why it's unexpected

**Comment by samgermain** [comment]
> ```python
> TypeError: string indices must be integers
> ```

This error makes sense because `create_swap_order` expects it's first argument to be an object. The method tries to read to read a property from the object (e.g. `object['property']` but it cannot be read because the argument is a string so it's trying to do something like `"string"['property']`. The only indices you can give to a string are integers, like `"string"[0]`, `"string"[1]` ...

**Comment by Nitrix321** [comment]
Hello @samgermain , thank you very much for your efforts. 

So that means contract trading is not possible via api on Mexc exchange, actually...
Thats sad.
