### ISSUE TITLE
What is 'requests.exceptions.HTTPError: 451 Client Error'??? (binance)

### ISSUE THREAD

**Issue by zacra** [ccxt/ccxt#15872]
Hello.
I am operating a class that allows automatic sales through Python by communicating with CCXT through AWS server.

---------------------------------------------------------------------------------------
```python
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 613, in fetch
    response.raise_for_status()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 451 Client Error:  for url: https://fapi.binance.com/fapi/v1/exchangeInfo
```
---------------------------------------------------------------------------------------
However, some students suddenly encounter the above error and cannot call the API.

Was it blocked due to excessive API calls? Or is there another problem?
Please give me feedback on when such a message comes.

**Comment by rogershihtw** [comment]
I also have the same problem when running auto trade in Binance Futures. The error appeared in the Google Cloud Functions. However, the ccxt seems to run well when I test it in my local debug environment(my notebook). 

I guess it must be something wrong with BinanceAPI or they are changing policies toward API management.

**Comment by singhyun90** [comment]
Try running the code in an environment other than the US.
It looks like Binance has blocked the US API.

Link : https://www.binance.com/en/terms
--> For the purposes hereof, “Restricted Location” shall include the United States, Malaysia, Ontario (Canada), and such other locations as designated by Binance Operators from time to time as a “Restricted Location” for the purposes hereof;

**Comment by gldstrrbt** [comment]
> Try running the code in an environment other than the US. It looks like Binance has blocked the US API.
> 
> Link : https://www.binance.com/en/terms --> For the purposes hereof, “Restricted Location” shall include the United States, Malaysia, Ontario (Canada), and such other locations as designated by Binance Operators from time to time as a “Restricted Location” for the purposes hereof;

It makes sense they don't want to allow US customers, but to block their public api is a bit far. If anyone has a solution for client side workarounds other than connecting a device to a vpn/proxy, that'd be greatly appreciated. This is really screwing my project over.

**Comment by xmatthias** [comment]
It's quite an interesting behavior - we see similar behavior in CI (github actions runs on US Azure servers), however limited by time - seemingly to US "out of business" hours.

CI with active calls is passing fine during the european afternoon  / evening - but is failing overnight / mornings.
I doubt regulations will change depending on the hour of the day - so this is pretty strange behavior.

**Comment by adens123** [comment]
如果是使用GCP Functions，可以透過以下方式解決，我已經可以使用了。
https://github.com/AlvarDev/functions-static-ip
https://hackmd.io/@S00kkKo0QbqD2O5ZCJZuyA/HkmnWorvo

**Comment by frosty00** [comment]
yeah, also i recommend using http://ip-api.com/json to check your ip

**Comment by ttodua** [comment]
see https://github.com/ccxt/ccxt/issues/15891
