### ISSUE TITLE
yobit unknown "error" value: {"success":0,"error":"invalid nonce (has already been used)"}

### ISSUE THREAD

**Issue by davydovpv** [ccxt/ccxt#1588]
yobit unknown "error" value: {"success":0,"error":"invalid nonce (has already been used)"}
yobit.create_order

- OS: CentOS 6
- Programming Language version: Python
- CCXT version:
- Exchange: YoBit
- Method: create_order

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki/Manual#authentication
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/Manual#error-handling
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-the-nonce
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Let us know if it does not help.
