### ISSUE TITLE
How to fix the issue where upbit open API with different countries?

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#15886]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10 Pro (22H2)
- Programming Language version: Node.js (versioin: 19.1.0)
- CCXT version: 2.2.41

```
const ccxt = require('ccxt');
console.log(ccxt.version);

let exchange = new ccxt.upbit
({
apiKey: 'My_Access_Key',
secret: 'My_Secret_Key',
'options': {
'adjustForTimeDifference': true,
'fetchCurrencies': true,
'verbose': true, }
});

async function getExchangeBalance()
{
try
{
const balance = await exchange.fetchBalance();
console.log(balance);
}
catch (err)
{
console.error(err)
}
};
getExchangeBalance();
```

```
D:\CCXT>node upbit_getExchangeBalance.js
2.2.41
AuthenticationError: upbit {"error":{"name":"invalid_access_key","message":"잘못된 액세스 키입니다."}}
    at upbit.throwBroadlyMatchedException (D:\CCXT\node_modules\ccxt\js\base\Exchange.js:2282:19)
    at upbit.handleErrors (D:\CCXT\node_modules\ccxt\js\upbit.js:1814:18)
    at D:\CCXT\node_modules\ccxt\js\base\Exchange.js:598:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (D:\CCXT\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async upbit.fetch2 (D:\CCXT\node_modules\ccxt\js\base\Exchange.js:1919:16)
    at async upbit.request (D:\CCXT\node_modules\ccxt\js\base\Exchange.js:1923:16)
    at async upbit.fetchBalance (D:\CCXT\node_modules\ccxt\js\upbit.js:501:26)
    at async getExchangeBalance (D:\CCXT\upbit_getExchangeBalance.js:18:17) {
  constructor: [class AuthenticationError extends ExchangeError]
}
```
Hello:
I just registered with Upbit in its Singapore company, as I don't understand Korean language, but its Singapore company web site uses English. And I created API keys yesterday, but today, when I did some testing, I saw the above errors.
I can verify that my IP address is not changing, the same as when I created API keys. The API keys are correct, as I keep records for all the access key and secret key.
However, from the error message, I guess that the Node CCXT sends get account balance request to Upbit in Korea, where I didn't have account, but I have account with Upbit in Singapore; therefore, CCXT requests failed, it is logic.
My question is: can I use CCXT script to get account balance from my account in Upbit Singapore not in Korea.
Please advise,
Thanks,

**Comment by carlosmiei** [comment]
Hello @zydjohnHotmail,
By default upbit uses this hostname `api.upbit.com` you can always change it if they have a different one depending on the location.

**Comment by Dan-krm** [comment]
Here is how to point to Upbit in Singapore, you can change the base hostname, like this:

```Python
import ccxt
exchange = ccxt.upbit({
    'apiKey': 'GLOBAL_API_KEY',
    'secret': 'GLOBAL_SECRET',
    'enableRateLimit': True,
    'hostname': 'sg-api.upbit.com',  # ←----------------- HERE
})
print(exchange.fetch_balance())
```
