### ISSUE TITLE
How to access the queue object which is used to store ticker or ohlc data in ccxt pro?

### ISSUE THREAD

**Issue by Sailendrakc** [ccxt/ccxt#15888]
The ccxt pro documentation mentions about the data structure (like sliding window or queue) in which the watched (fetched) data is stored. How can we access that object? Coz I tried logging the whole object and searching but was not able to find it.

**Comment by carlosmiei** [comment]
Hello @Sailendrakc 

You should be able to access them by doing:

```Javascript
exchange.trades
exchange.tickers
```
