### ISSUE TITLE
Problem with logging into OKX via CCXT and API

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#15895]
Hey, guys, I'm stuck on the first step: I cant login.
using
```
okx = ccxt.okx({
        "apiKey": config.OKX_API_KEY,
        "secret": config.OKX_SECRET_KEY,
        "password": config.OKX_PASSWORD,
        "options": {'defaultType': 'spot'}
    })
okx.fetch_balance()
```
I got error `ccxt.base.errors.RequestTimeout: okex5 GET https://www.okx.com/api/v5/asset/currencies` and msg in URL `{"msg":"Request header OK-ACCESS-KEY can not be empty.","code":"50103"}`

Looks like I send empty string, but its not true (I think). Is there any way to debug it and print the header of request?

**Comment by sc0Vu** [comment]
Hi @KindSpidey 

There is comment in okx implementation, would you like to check your api credentials in exchange?

```
        // has['fetchCurrencies'] is currently set to true, but an unauthorized request returns
        //
        //     {"msg":"Request header “OK_ACCESS_KEY“ can't be empty.","code":"50103"}
```

To print the request header, you can set `verbose` when initialize exchange. Let me know if you have other questions.

**Comment by KindSpidey** [comment]
@sc0Vu this is my header request 
`fetch Request: okex5 GET https://www.okx.com/api/v5/asset/currencies RequestHeaders: {'OK-ACCESS-KEY': '915f16fc-fcc0-4a9f-8616-91df7dc8ed0e', 'OK-ACCESS-PASSPHRASE': 'Aa_12345', 'OK-ACCESS-TIMESTAMP': '2022-12-02T07:16:02.508Z', 'OK-ACCESS-SIGN': '5TE8nLuvi/VNDEm+OxGbiZoWXHx9gfudjdoUlx5xVZE=', 'User-Agent': 'python-requests/2.28.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None`

I guess, everything has sent. Can you try my API in your code? I dont have any money on the account, so Its ok to share it for finding a reason of error:
```
OKX_TEST_API_KEY = "915f16fc-fcc0-4a9f-8616-91df7dc8ed0e"
OKX_TEST_SECRET_KEY = "8029F7FF3C3E5B8202EFA879D87E5949"
OKX_TEST_PASSWORD = "Aa_12345"
okx_test = ccxt.okex5({
"apiKey": OKX_TEST_API_KEY,
    "secret": OKX_TEST_SECRET_KEY,
    "password": OKX_TEST_PASSWORD,
    "verbose": True
})
```

**Comment by ttodua** [comment]
@KindSpidey can you please tell, if that problem was temporary and was already went away for you?

**Comment by KindSpidey** [comment]
@ttodua yep. still have it
I got
`ccxt.base.errors.NetworkError: okx GET https://www.okx.com/api/v5/asset/currencies`
and on site
`{"msg":"Request header OK-ACCESS-KEY can not be empty.","code":"50103"}`

I use verbose mode, so my headers are not empty

**Comment by ttodua** [comment]
@carlosmiei any thoughts?

**Comment by carlosmiei** [comment]
@ttodua @KindSpidey 

I think the error here is a bit misleading because it means here that's an authentication error, not that something is missing on the payload. I would suggest double-checking your API keys.

**Comment by ttodua** [comment]
when the api key is invalid, it throws `{"msg":"Invalid OK-ACCESS-KEY","code":"50111"}`

**Comment by KindSpidey** [comment]
@ttodua thank you for your care. I'll try when I have this opportunity and will let you know. Happy New Year, man!

**Comment by KindSpidey** [comment]
@ttodua by the way I have one thought about it. I live in Russia and OKX is blocked here. I can log into it only by using VPN. So, perhaps, it meets problems, because of it.

**Comment by ttodua** [comment]
@KindSpidey I think that might be problem, but once you revise that (use vpn when using ccxt with the same code you get error) and if VPN will help, then the issue is found. 
if using VPN you also get the same problem, please re-open the issue and let me know.

**Comment by KindSpidey** [comment]
@ttodua it's finally here. I used VPN on my PC and everything works! So, I regret that OKX does not work in Russia withoun VPN, but that's the way it is.

**Comment by ttodua** [comment]
> @ttodua it's finally here. I used VPN on my PC and everything works! So, I regret that OKX does not work in Russia withoun VPN, but that's the way it is.

good to know the reason. thanks for reporting.
