### ISSUE TITLE
Bybit Spot watchOrders result contains of incorrect and not full data

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#15904]
We've noticed that for Bybit 'spot' market watchOrders result contains of incorrect and not full data that Bybit actually sent.

- In our cases we use `clientOrderId`, in the Bybit data `clientOrderId` exists (`c` parameter inside ccxt `info` field), but suddenly ccxt `clientOrderId` value is `undefined`.
- `amount`, `filled`, `remaining` values calculated incorrectly for 'MARKET_OF_QUOTE' (market buy order) because `amount = info.q` and `filled = info.l` where ` info.q` value represented in quote currency amount (for market buy order only) but `info.l` represented in base currency amount (always).
- `average`, `price`, `cost`, `fee` fields in ccxt result also `undefined` (looks like parsing the `spot` order ccxt uses logic like for `swap` and `futures`)

Here is a link to Bybit Spot order docs:
https://bybit-exchange.github.io/docs/spot/v3/#:~:text=Reserved%20for%20orders-,order,-How%20to%20Subscribe

Here is the orders results:
Market Buy ('MARKET_OF_QUOTE' ):
```
{
  info: {
    e: 'executionReport',
    E: '1669880775175',
    s: '1INCHUSDT',
    c: 'xxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    S: 'BUY',
    o: 'MARKET_OF_QUOTE',
    f: 'GTC',
    q: '10',
    p: '0',
    X: 'CANCELED',
    i: 'yyyyyyyyyyyyyyyyyyyyyy',
    M: '1301445441138739200',
    l: '19.14',
    z: '19.14',
    L: '0.5224',
    n: '0',
    N: '1INCH',
    u: true,
    w: true,
    m: false,
    O: '1669880775129',
    Z: '9.998736',
    A: '0',
    C: false,
    v: '0',
    d: 'NO_LIQ',
    t: '2230000000031212661'
  },
  id: 'yyyyyyyyyyyyyyyyyyyyyy',
  clientOrderId: undefined,
  timestamp: 1669880775129,
  datetime: '2022-12-01T07:46:15.129Z',
  lastTradeTimestamp: 1669880775175,
  symbol: '1INCH/USDT',
  type: 'market',
  timeInForce: 'GTC',
  postOnly: undefined,
  side: 'buy',
  price: undefined,
  stopPrice: undefined,
  amount: 10,
  cost: undefined,
  average: undefined,
  filled: 19.14,
  remaining: -9.14,
  status: 'canceled',
  fee: undefined,
  trades: [],
  fees: []
}
```

Market Sell ('MARKET_OF_BASE' ):

```
{
  info: {
    e: 'executionReport',
    E: '1669882902633',
    s: '1INCHUSDT',
    c: 'xxx-xxxxxxxxxxxxxxxxxxxxxxxxxxx',
    S: 'SELL',
    o: 'MARKET_OF_BASE',
    f: 'GTC',
    q: '20',
    p: '0',
    X: 'FILLED',
    i: 'yyyyyyyyyyyyyyyyyyyyyyyyy',
    M: '1301465553296190464',
    l: '20',
    z: '20',
    L: '0.5175',
    n: '0',
    N: 'USDT',
    u: true,
    w: true,
    m: false,
    O: '1669882902578',
    Z: '10.35',
    A: '0',
    C: false,
    v: '0',
    d: 'NO_LIQ',
    t: '2230000000031216507'
  },
  id: 'yyyyyyyyyyyyyyyyyyyyyyyyy',
  clientOrderId: undefined,
  timestamp: 1669882902578,
  datetime: '2022-12-01T08:21:42.578Z',
  lastTradeTimestamp: 1669882902633,
  symbol: '1INCH/USDT',
  type: 'market',
  timeInForce: 'GTC',
  postOnly: undefined,
  side: 'sell',
  price: undefined,
  stopPrice: undefined,
  amount: 20,
  cost: undefined,
  average: undefined,
  filled: 20,
  remaining: 0,
  status: 'closed',
  fee: undefined,
  trades: [],
  fees: []
}
```

- OS: Debian (Docker)
- Programming Language version: NodeJS, JavaScript
- CCXT version: CCXT 2.2.46

**Comment by carlosmiei** [comment]
@wunderb1t Bybit was migrated to v5, so I don't think this issue still applies.
