### ISSUE TITLE
ByBit fetchTickers() Isn't Accepting The Pattern: Base/Quote

### ISSUE THREAD

**Issue by drsavant-pub** [ccxt/ccxt#15914]
When I run the code I get this error for each coin pair (see markets below):
**BadSymbol: bybit does not have market symbol [COIN]/USDT**

### If I remove the '/' slash I do get the expected results!
_Except for the extra characters:_  symbol: **'SOL/USDT:USDT'** (the same for each coin)

### I Also Get The Same Error in ccxt.pro, but if I remove the '/' slash I get results!
_Except for the extra characters:_  symbol: **'SOL/USDT:USDT'**  (the same for each coin)

### Note:

1. My workaround is to remove the '/' slash from markets, and filter out the extra characters from the output: ":USDT"
3. If needed I can create a separate ticket for ccxt.pro

- OS: Windows 8.1
- Programming Language version: Nodejs v16.14.2
- CCXT version: 2.2.47

### Code:
```js
let ccxt = require('ccxt')
let ex = new ccxt.bybit({verbose: true})
let markets = [
  'AVAX/USDT',
  'DOT/USDT',
  'SOL/USDT',
  'TRX/USDT',
  'XLM/USDT',
  'XRP/USDT'
]

async function run(){
  ex.fetchTickers(markets).then( (results)=>{
    console.log('results', results)
  })
}

run()
```

### Error:
```
The full output of the error is in the attached file: 
But the important part is this last sentence:
BadSymbol: bybit does not have market symbol AVAX/USDT
```
The error is the same for each coin in **markets**.

[20221201-bybit.ccxt.fetchTickers.error.txt](https://github.com/ccxt/ccxt/files/10136859/20221201-bybit.ccxt.fetchTickers.error.txt)

**Comment by carlosmiei** [comment]
Hello @drsavant-pub,

By default, bybit loads swap markets only, if you want to handle spot markets if you have to change the `defaultType`.

Example:

```Javascript
let ex = new ccxt.bybit({verbose: true, options: {defaultType: "spot"}})
```

**Comment by drsavant-pub** [comment]
I tried your suggestion, but it returned 
 results = {}

**Comment by drsavant-pub** [comment]
I'll just stick with my workaround for now.
