### ISSUE TITLE
Get highest and lowest price of last 10 candles?

### ISSUE THREAD

**Issue by janstrw13** [ccxt/ccxt#15915]
Hello, i want to get the highest and lowest price of the last 10 candles in one hour chart. 
I know how i can get the price of one single candle so when i go into 12H candles and get highest and lowest it is fine but the problem is when a new 12H candle is opened it gives me incorrect data.

How can i get this?

**Comment by samgermain** [comment]
Can you explain how you get incorrect data? With code examples?

**Comment by janstrw13** [comment]
DailyTimeFrame = '4h'
TimeFrame = '1h'
HedgeBerechnung= '6h'
Moving_Average_Length = 50

exchange = ccxt.bybit({
    "apiKey": Key,
    "secret": Secret,
    "options": {'defaultType': 'future'}
})
limit = Moving_Average_Length
bars = exchange.fetch_ohlcv(symbol, HedgeBerechnung, since=now ,limit=limit)
df = pd.DataFrame(bars[:-1], columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
cur=exchange.fetch_ticker(symbol)
close_price = float(df['close'].iloc[-1])
close_price=cur['close']
print(cur['low'])
DifferenzAbstand= cur['high'] - cur['low']
print(cur['high'])
1 Idea
In this example i get the highest and lowest price of the 6Hour candle. But now i want to check the last ten 1H candles and find the highest and lowest price of the last ten candles. 
2 Idea
Or is there a possibility where i can get the penultimate 6hour candle lowest and highest price? Like this one 
![image](https://user-images.githubusercontent.com/119401920/205238810-c73852d3-983d-42b8-8fdf-228bd619ddc1.png)

**Comment by samgermain** [comment]
> ```python
> DailyTimeFrame = '4h'
> TimeFrame = '1h'
> HedgeBerechnung= '6h'
> Moving_Average_Length = 50
> 
> exchange = ccxt.bybit({
>     "apiKey": Key,
>     "secret": Secret,
>     "options": {'defaultType': 'future'}
> })
> limit = Moving_Average_Length
> bars = exchange.fetch_ohlcv(symbol, HedgeBerechnung, since=now ,limit=limit)
> df = pd.DataFrame(bars[:-1], columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
> df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
> cur=exchange.fetch_ticker(symbol)
> close_price = float(df['close'].iloc[-1])
> close_price=cur['close']
> print(cur['low'])
> DifferenzAbstand= cur['high'] - cur['low']
> print(cur['high'])
> ```
> 
> 1 Idea In this example i get the highest and lowest price of the 6Hour candle. But now i want to check the last ten 1H candles and find the highest and lowest price of the last ten candles. 2 Idea Or is there a possibility where i can get the penultimate 6hour candle lowest and highest price? Like this one ![image](https://user-images.githubusercontent.com/119401920/205238810-c73852d3-983d-42b8-8fdf-228bd619ddc1.png)

Your example doesn't really match what you're talking about, you only use the `6h` timeframe there, and you print out the high and low values from `fetch_ticker`

Please provide a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), and provide some comment lines/explanation as to what the code is supposed to do

----------------------------------

If it helps, I formatted your example, and filled in the missing variables. In the future, it will help to provide enough code to be a working program. You will get an answer faster if we can just copy your code, and run it, without any additions

- you don't need the since argument, and setting it to `now` will assure you that you get no candles, because you're asking for all the candles that have published after right now

```
import pandas as pd
# import time
import ccxt
from pprint import pprint
import json

keys = json.load(open('../keys.local.json'))

# now = int(time.time() * 1000)  # current time in milliseconds
dailytime_frame = '4h'
time_frame = '1h'
hedge_berechnung = '6h'
moving_average_length = 50
symbol = 'BTC/USD:BTC-221230'

exchange = ccxt.bybit({
    "apiKey": keys['bybit']['apiKey'],
    "secret": keys['bybit']['secret'],
    "options": {'defaultType': 'future'}
})

exchange.load_markets()

limit = moving_average_length
bars = exchange.fetch_ohlcv(
    symbol,
    hedge_berechnung,
    # since=now,
    limit=limit
)

df = pd.DataFrame(
    bars[:-1],
    columns=['timestamp', 'open', 'high', 'low', 'close', 'volume']
)
df['timestamp'] = pd.to_datetime(
    df['timestamp'],
    unit='ms'
)

cur = exchange.fetch_ticker(symbol)

close_price = float(df['close'].iloc[-1])
close_price = cur['close']
pprint(cur['low'])

differenz_abstand = cur['high'] - cur['low']
pprint(cur['high'])
```
