### ISSUE TITLE
Unable to bybit.fetch_positions

### ISSUE THREAD

**Issue by PlainStack** [ccxt/ccxt#15927]
I'm at a complete loss. I'm unable to fetch_positions from Bybit. It worked perfectly fine earlier in the day, and now it keeps giving me an error. I utilised the example code with the output below to test, but I got the same error with my code.

- OS: Windows
- Programming Language version: Python 3.9
- CCXT version: 2.2.55

```
import os
import sys
import config

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402

from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.bybit ({
    'apiKey': config.bybit_testnet_api,
    'secret': config.bybit_testnet_secret,
})

exchange.set_sandbox_mode(True)


markets = exchange.load_markets() # https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

exchange.verbose = True  # uncomment for debugging

# -----------------------------------------------------------------------------

symbol = 'BTC/USDT:USDT'  # https://docs.ccxt.com/en/latest/manual.html#contract-naming-conventions
market = exchange.market(symbol)
params = {'subType':'linear' if market['linear'] else 'inverse'}
linear_positions = exchange.fetch_positions([ symbol ], params)
pprint(linear_positions)

# -----------------------------------------------------------------------------

symbol = 'BTC/USD:BTC'
market = exchange.market(symbol)
params = {'subType':'linear' if market['linear'] else 'inverse'}
inverse_positions = exchange.fetch_positions([ symbol ], params)
pprint(inverse_positions)
```

```
Reloaded modules: config
CCXT Version: 2.2.55
Traceback (most recent call last):

  File "C:\Users\***\My Drive\Python\Moon Dev\untitled0.py", line 31, in <module>
    linear_positions = exchange.fetch_positions([ symbol ], params)

  File "C:\Users\***\anaconda3\lib\site-packages\ccxt\bybit.py", line 5749, in fetch_positions
    raise ArgumentsRequired(self.id + ' fetchPositions() does not accept an array of symbols')

ArgumentsRequired: bybit fetchPositions() does not accept an array of symbols
```

**Comment by carlosmiei** [comment]
Hello @PlainStack 

Very recently, Bybit was upgraded to the latest version (v3), so some things changed slightly, can you try to provide the symbol directly instead of an array?

Example:

```Python
symbol = "BTC/USDT:USDT"
pos = await bybit.fetch_positions(symbol)
```

**Comment by PlainStack** [comment]
> ```python
> await bybit.fetch_positions(symbol)
> ```

I've tried providing the symbol directly, but it gives me a "BadSymbol: bybit does not have market symbol B" error.

When I try 'ETH/USDT:USDT', it gives me "BadSymbol: bybit does not have market symbol E".

**Comment by carlosmiei** [comment]
@PlainStack Can you update to the lastest version and try again please? I added a fix so it should be working now, either using a symbol or an array with the symbol inside.

**Comment by PlainStack** [comment]
> @PlainStack Can you update to the lastest version and try again please? I added a fix so it should be working now, either using a symbol or an array with the symbol inside.

No luck, only returns an empty list.

```
exchange.fetch_positions("BTC/USD:BTC")

fetch Request: bybit GET https://api-testnet.bybit.com/unified/v3/private/position/list?category=linear RequestHeaders: {'Content-Type': 'application/json', 'X-BAPI-API-KEY': 'vbHyRye4YA0rVnA8aE', 'X-BAPI-SIGN-TYPE': '2', 'X-BAPI-TIMESTAMP': '1670058512666', 'X-BAPI-RECV-WINDOW': '5000', 'X-BAPI-SIGN': 'd7f6b7fdd55fcda3dab0b794dc662e3f89c0dfb4b28cb6fe5a5c91be2a1d1767', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bybit GET https://api-testnet.bybit.com/unified/v3/private/position/list?category=linear 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '132', 'Ret_code': '0', 'Traceid': '4004cd1186c61d3b0379be0ea1c852a9', 'Timenow': '1670058512907', 'Server': 'Openresty', 'Expires': 'Sat, 03 Dec 2022 09:08:33 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Sat, 03 Dec 2022 09:08:33 GMT', 'Connection': 'keep-alive'} ResponseBody: {"retCode":0,"retMsg":"Success","result":{"nextPageCursor":null,"category":"linear","list":[]},"retExtInfo":{},"time":1670058512907}
Out[210]: []
```

**Comment by frosty00** [comment]
> > @PlainStack Can you update to the lastest version and try again please? I added a fix so it should be working now, either using a symbol or an array with the symbol inside.
> 
> No luck, only returns an empty list.
> 
> ```
> exchange.fetch_positions("BTC/USD:BTC")
> 
> fetch Request: bybit GET https://api-testnet.bybit.com/unified/v3/private/position/list?category=linear RequestHeaders: {'Content-Type': 'application/json', 'X-BAPI-API-KEY': 'vbHyRye4YA0rVnA8aE', 'X-BAPI-SIGN-TYPE': '2', 'X-BAPI-TIMESTAMP': '1670058512666', 'X-BAPI-RECV-WINDOW': '5000', 'X-BAPI-SIGN': 'd7f6b7fdd55fcda3dab0b794dc662e3f89c0dfb4b28cb6fe5a5c91be2a1d1767', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None
> 
> fetch Response: bybit GET https://api-testnet.bybit.com/unified/v3/private/position/list?category=linear 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '132', 'Ret_code': '0', 'Traceid': '4004cd1186c61d3b0379be0ea1c852a9', 'Timenow': '1670058512907', 'Server': 'Openresty', 'Expires': 'Sat, 03 Dec 2022 09:08:33 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Sat, 03 Dec 2022 09:08:33 GMT', 'Connection': 'keep-alive'} ResponseBody: {"retCode":0,"retMsg":"Success","result":{"nextPageCursor":null,"category":"linear","list":[]},"retExtInfo":{},"time":1670058512907}
> Out[210]: []
> ```

you should use `fetchPosition` instead of fetchPositions for fetching a single symbol. `fetchPositions` takes an array of symbols instead.

**Comment by PlainStack** [comment]
> > > @PlainStack Can you update to the lastest version and try again please? I added a fix so it should be working now, either using a symbol or an array with the symbol inside.
> > 
> > 
> > No luck, only returns an empty list.
> > ```
> > exchange.fetch_positions("BTC/USD:BTC")
> > 
> > fetch Request: bybit GET https://api-testnet.bybit.com/unified/v3/private/position/list?category=linear RequestHeaders: {'Content-Type': 'application/json', 'X-BAPI-API-KEY': 'vbHyRye4YA0rVnA8aE', 'X-BAPI-SIGN-TYPE': '2', 'X-BAPI-TIMESTAMP': '1670058512666', 'X-BAPI-RECV-WINDOW': '5000', 'X-BAPI-SIGN': 'd7f6b7fdd55fcda3dab0b794dc662e3f89c0dfb4b28cb6fe5a5c91be2a1d1767', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None
> > 
> > fetch Response: bybit GET https://api-testnet.bybit.com/unified/v3/private/position/list?category=linear 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '132', 'Ret_code': '0', 'Traceid': '4004cd1186c61d3b0379be0ea1c852a9', 'Timenow': '1670058512907', 'Server': 'Openresty', 'Expires': 'Sat, 03 Dec 2022 09:08:33 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Sat, 03 Dec 2022 09:08:33 GMT', 'Connection': 'keep-alive'} ResponseBody: {"retCode":0,"retMsg":"Success","result":{"nextPageCursor":null,"category":"linear","list":[]},"retExtInfo":{},"time":1670058512907}
> > Out[210]: []
> > ```
> 
> you should use `fetchPosition` instead of fetchPositions for fetching a single symbol. `fetchPositions` takes an array of symbols instead.

I used fetchPositions in my code not even 24 hours ago without any issues, which is why I'm so baffled with things not working anymore. I tried fetchPosition and it gives me NotSupported: bybit fetchPosition() does not allow inverse market orders for BTC/USD:BTC markets.
