### ISSUE TITLE
bitstamp requires `uid`

### ISSUE THREAD

**Issue by andy-io** [ccxt/ccxt#1592]
ccxt.base.errors.AuthenticationError: bitstamp requires `uid`
cannot perform fetch balance 

- OS: Mac Sierra
- Programming Language version: Python
- CCXT version: 1.10.867
- Exchange: bistamp
- Method: fetch_balance

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki/Manual#authentication
- https://github.com/ccxt/ccxt/wiki/Manual#api-keys-setup

Let us know if it doesn't answer your question.

**Comment by andy-io** [comment]
@kroitor Thanks i added the uid when initiating the object.

now i get this error:  ccxt.base.errors.ExchangeNotAvailable: bitstamp POST https://www.bitstamp.net/api/v2/balance/ 403 Client Error: Authentication Failed for url: https://www.bitstamp.net/api/v2/balance/ {"status": "error", "reason": "Invalid signature", "code": "API0005"}

**Comment by kroitor** [comment]
https://github.com/askmike/gekko/issues/1509#issuecomment-352887651

**Comment by kroitor** [comment]
@andy-io let me know if you still have difficulties with it.

**Comment by andy-io** [comment]
@kroitor : thanks for the support. I still get the error even though i have only one main account in bitstamp and the api key/secret and customer id are all pointing to this main account. Looks to me like a bitstamp issue

**Comment by andy-io** [comment]
does it work for you (fetching balance from bitstamp) without any error ?

**Comment by wannesdemaeght** [comment]
@andy-io  try initializing like this:
`let` Bitstamp = new ccxt.bitstamp ({apiKey: xxx, secret: xxx, uid: xxx, timeout: 5000});
Please note that uid is NOT your emailadress, but your user ID.

**Comment by andy-io** [comment]
@kroitor @wannesdemaeght thanks for helping out, i had a wrong key when i copied it. I had an extra character that gave this error. Thanks once again !!!

**Comment by kroitor** [comment]
@fedecaccia it is covered briefly here: https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

> timeout: A timeout in milliseconds for a request-response roundtrip (default timeout is 10000 ms = 10 seconds). You should always set it to a reasonable value, hanging forever with no timeout is not your option, for sure.

And here: https://github.com/ccxt/ccxt/wiki/Manual#requesttimeout

**Comment by fedecaccia** [comment]
@kroitor txs!
