### ISSUE TITLE
How to get tokens contract address?

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#15930]
Hello:

I want to know if I can use CCXT to get currency’s contract address. 
For example, the USDT contract address is: 0xdac17f958d2ee523a2206206994597c13d831ec7

Can I write some CCXT code (I think Binance has most cover of tokens), to give a currency name, like: USDT, BTC, ETH, and CCXT code return the contract address? 

For example, for USDT, CCXT return contract address: 0xdac17f958d2ee523a2206206994597c13d831ec7

Please advise,
Thanks,

**Comment by samgermain** [comment]
Getting the `contractAddress` isn't unified in CCXT at the moment, so you'll need to use the [implicit API](sapiGetNftUserGetAsset), which means a different implementation for each exchange. 

For binance you can use the method `sapiGetNftUserGetAsset`. 

![](https://i.imgur.com/z85r1zH.png)

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply, I wrote the following code:
const ccxt = require('ccxt')
const keys = require ('./keys.local.json');
console.log ('CCXT Version:', ccxt.version);

const exchange = new ccxt.binance ({
    'apiKey': keys.binance.apiKey,
    'secret': keys.binance.secret,
    adjustForTimeDifference: true,
    defaultType: 'spot',
    verbose: false,	
});

const contract_address = async () => {
    try {
		const contracts = await exchange.sapiGetNftUserGetAsset();
		console.log(contracts);
    }
    catch (err) {
        console.log(err);
    }
};

contract_address();

But when I run it, it showed only one symbol:
D:\nodejs\CCXT_Binance>node Binance_ContractAddress.js
CCXT Version: 2.2.57
{
  total: '1',
  list: [
    {
      network: 'BSC',
      contractAddress: '0xfb39c5690673b7075169c498d46c9c7df68c1356',
      tokenId: '222301138202'
    }
  ]
}

D:\nodejs\CCXT_Binance>

Give me some examples on how to get different currency contract address, like: USDT, BTC and ETH.
Thanks,

**Comment by samgermain** [comment]
> Hello: Thanks for your reply, I wrote the following code:
> 
> ```js
> const ccxt = require('ccxt')
> const keys = require ('./keys.local.json');
> console.log ('CCXT Version:', ccxt.version);
> 
> const exchange = new ccxt.binance ({
>     'apiKey': keys.binance.apiKey,
>     'secret': keys.binance.secret,
>     adjustForTimeDifference: true,
>     defaultType: 'spot',
>     verbose: false,	
> });
> 
> const contract_address = async () => {
>     try {
>         const contracts = await exchange.sapiGetNftUserGetAsset();
> 	console.log(contracts);
>     }
>     catch (err) {
>         console.log(err);
>     }
> };
> 
> contract_address();
> ```
> 
> But when I run it, it showed only one symbol:
> 
> ```
> D:\nodejs\CCXT_Binance>node Binance_ContractAddress.js
> CCXT Version: 2.2.57
> {
>   total: '1',
>   list: [
>     {
>       network: 'BSC',
>       contractAddress: '0xfb39c5690673b7075169c498d46c9c7df68c1356',
>       tokenId: '222301138202'
>     }
>   ]
> }
> 
> D:\nodejs\CCXT_Binance>
> ```
> 
> Give me some examples on how to get different currency contract address, like: USDT, BTC and ETH. Thanks,

To be honest I don't know a ton about NFTs or contract addresses, but it kind of looks like it returns the addresses of all the nft's that you have. When I run this script, I don't get any.

```
{ total: '0', list: [] }
```

-------------

The only methods that I can find where the api docs mention the contract address, other than the one above, are

[sapiGetNftHistoryTransactions](https://binance-docs.github.io/apidocs/spot/en/#nft-endpoints)
[sapiGetNftHistoryDeposit](https://binance-docs.github.io/apidocs/spot/en/#get-nft-deposit-history-user_data)
[sapiGetNftHistoryWithdraw](https://binance-docs.github.io/apidocs/spot/en/#get-nft-withdraw-history-user_data)

It looks like those are the only NFT endpoints for binance also, so if one of those can't do what you want, you may be out of luck, but you could always go through binance technical support and request more

**Comment by samgermain** [comment]
I'm going to close this issue because it looks like it's been answered as much as it can be. Please reopen it if you have any more questions
