### ISSUE TITLE
bkex add futures support

### ISSUE THREAD

**Issue by frosty00** [ccxt/ccxt#15947]
https://bkexapi.github.io/docs/api_en.htm?shell#contract

**Comment by Dan-krm** [comment]
### Public Methods

- [x] fetchMarkets #15993
- [x] fetchOHLCV #16015
- [x] fetchOrderBook #16018
- [x] fetchTrades #16037
- [x] fetchTicker, fetchTickers #16057
- [x] fetchFundingRateHistory #16038
- [x] fetchMarketLeverageTiers #16093
- [x] ~~fetchLeverageTiers~~
- [x] ~~fetchFundingHistory~~
- [x] ~~fetchFundingRate, fetchFundingRates~~
- [x] ~~fetchMarkOHLCV~~
- [x] ~~fetchIndexOHLCV~~
- [x] ~~fetchPremiumIndexOHLCV~~
- [x] ~~fetchOpenInterest~~


### Private Methods
Private contract endpoints on bkex can't be accessed:

![image](https://user-images.githubusercontent.com/83686770/215904084-044690b7-46ca-4233-a7d8-a81ff0b84176.png)
Derivatives permissions have been in review for a few months:
![image](https://user-images.githubusercontent.com/83686770/215904401-69e2d452-b0fe-4ba0-8762-0d3237260e36.png)

- [ ] fetchBalance https://bkexapi.github.io/docs/api_en.htm?shell#contract-account-balance
- [ ] createOrder https://bkexapi.github.io/docs/api_en.htm?shell#contract-deal-order-open
- [ ] fetchOrders https://bkexapi.github.io/docs/api_en.htm?shell#contract-deal-order-finished
- [ ] fetchClosedOrders https://bkexapi.github.io/docs/api_en.htm?shell#contract-deal-order-finishedInfo
- [ ] fetchOpenOrders https://bkexapi.github.io/docs/api_en.htm?shell#contract-deal-order-unFinish
- [ ] cancelOrder https://bkexapi.github.io/docs/api_en.htm?shell#contract-deal-order-cancel
- [ ] cancelOrders https://bkexapi.github.io/docs/api_en.htm?shell#contract-deal-order-batchCancel
- [ ] cancelAllOrders https://bkexapi.github.io/docs/api_en.htm?shell#contract-deal-order-closeAll
- [ ] setLeverage https://bkexapi.github.io/docs/api_en.htm?shell#contract-account-setLeverage
- [ ] fetchPositionMode https://bkexapi.github.io/docs/api_en.htm?shell#contract-deal-position-info
- [ ] setPositionMode https://bkexapi.github.io/docs/api_en.htm?shell#contract-deal-position-update
- [ ] fetchPosition https://bkexapi.github.io/docs/api_en.htm?shell#contract-account-position
- [x] ~~transfer~~
- [x] ~~fetchPositions~~
- [x] ~~fetchOrder~~
- [x] ~~setMarginMode~~

**Comment by Dan-krm** [comment]
Closed because bkex has been delisted
