### ISSUE TITLE
KUCOIN - ccxt.base.errors.ExchangeNotAvailable: kucoin Server busy - CCXT not up to date with APIv2 ?

### ISSUE THREAD

**Issue by bluetyphoon77** [ccxt/ccxt#15952]
Dear support,
I get the ccxt.base.errors.ExchangeNotAvailable: kucoin Server busy, please retry later error on fetchOpenOrders function, is this an issue on kucoin side? Or is it CCXT which is not up to date with the Kucoin api v2 ? (the v1 is deprecated since August)
We also have problem to fetch balance...
Thanks in advance

**Comment by bluetyphoon77** [comment]
![image](https://user-images.githubusercontent.com/38290272/205499682-b6a46df3-f875-4ec5-8669-2f8762f3e4fe.png)

**Comment by bluetyphoon77** [comment]
@kroitor Do you have any advice ? :) thanks a lot

**Comment by sc0Vu** [comment]
Hi @bluetyphoon77 

I think you can set version in options, just remember they didn't support some endpoint for v2.

**Comment by 2dOverlord** [comment]
Hey @sc0Vu 
for v2 endpoints, kucoin does not have https://api.kucoin.com/api/v2/currencies endpoint, that ccxt is calling during fetchOpenOrders function

![image](https://user-images.githubusercontent.com/74546413/205985779-a6944b3e-4ee0-4143-b0c3-fd059ac6c8a4.png)

**Comment by bluetyphoon77** [comment]
@frosty00

**Comment by bluetyphoon77** [comment]
Hi dear devs. Is there anyone who knows about this ?
