### ISSUE TITLE
Loading markets question

### ISSUE THREAD

**Issue by JT102** [ccxt/ccxt#1595]
Why is it necessary to load markets if we do other requests, order placement for example?
There is always one extra request to load markets prior to any balance check, withdrawal, order placement, etc. This add delays and sometime rate limit applied. Is there any workaround to avoid it (cache between scripts executions)?

**Comment by kroitor** [comment]
@JT102 

> There is always one extra request to load markets prior to any balance check, withdrawal, order placement, etc.

In fact, they are cached already, for the runtime, and the inner working of the cache is described here: https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

So, they are not loaded prior to any balance check, as the markets are loaded just once and then cached (no further reloads and no added requests).

However, markets are not cached between the executions of your script if you exit and relaunch, so you need to cache them on user side (we think this task is currently beyond the scope of the library).

To cache them on user side you would do this (you 

```PHP
// load them once
$exchange->load_markets();
// save to cache after loading
file_put_contents ('markets.json', json_encode ($exchange->markets));
```

And later, to restore the cached markets

```
// instantiate exchange
$exchange = new \ccxt\kucoin ();
// load markets from cache
$exchange->markets = json_decode (file_get_contents ('markets.json'));
$exchange->markets_by_id = $exchange->indexBy ($exchange->markets, 'id');
```

Let us know if it doesn't help.

**Comment by JT102** [comment]
Awesome! That's what I was looking for!
Let me just edit code, to make it work (changes are: json_decode and $filename variable in file_put/get_contents):

```
$filename = 'markets.json';
if (!file_exists ($filename)) {
    // load them from internet once
    $exchange->load_markets();
    // save to cache after loading
    file_put_contents ($filename, json_encode ($exchange->markets));
} else {
    // load markets from cache
    $exchange->markets = json_decode (file_get_contents ($filename), true);
    $exchange->markets_by_id = $exchange->indexBy ($exchange->markets, 'id');
}
```

**Comment by legitalk** [comment]
Actually in 2023 it has to be:

```
$filename = 'markets.json';

if (!file_exists($filename)) {
    // load them from internet once
    self::$exchange->load_markets();

    // save to cache after loading
    file_put_contents($filename, json_encode(self::$exchange->markets));
} else {
    // load markets from cache
    self::$exchange->set_markets(json_decode(file_get_contents($filename), true));
}
```
