### ISSUE TITLE
Binance watchMyTrades 

### ISSUE THREAD

**Issue by AwooOOoo** [ccxt/ccxt#15955]
Hi,
    I am switching my code over to the streaming API from all the REST calls and am having trouble with watchMyTrades. I am trying to monitor when my trade was fully closed, before moving to the next steps. Previously I used fetchClosedOrders and this worked fine.

**CCXT version:** 1.95.43
**Language:** NodeJS (via WSL2)
**Operating System:** WIndows 10 Enterprise (10.0.19045)

Here is my sample code

```
'use strict';

const ccxt = require ('ccxt');

//local modules
let crypt = require('./src/crypt');                    // Protection of config file

const configFile = './conf/conf.dat';

(async () => {
    /////////////////////////////////////////////////////////////////////
    // Load the exchange configuration
    /////////////////////////////////////////////////////////////////////
    const config = await crypt.getConfig(configFile)

    /////////////////////////////////////////////////////////////////////
    // Connect to the Exchange
    /////////////////////////////////////////////////////////////////////
    const exchangeName = "binance";

    let serverType = "production";
    //let serverType = "test";

    const exchangeStream = new ccxt.pro[exchangeName] ({ 
        apiKey: config.credentials[exchangeName][serverType][0]['key'],
        secret: config.credentials[exchangeName][serverType][0]['secret'],

        enableRateLimit: true,
    });
    if (serverType === "test") {
        exchangeStream.set_sandbox_mode(true);
    }

    console.log("CCXT version:", ccxt.version);
    const symbol = 'ETH/BTC'
    
    while (true) {
        try {
            const minutes = 2;
            const exchangeTime = exchangeStream.milliseconds ();
            const since = exchangeTime - minutes * 60000;
            console.log("got here");
            const trades = await exchangeStream.watchMyTrades(symbol, since);
            console.log("didn't get here");
            console.log(trades);
        } catch (e) {
            console.log (e.constructor.name, e.message)
        }
    }

}) ()
```

...and the output..
```
>node watchMyTrades.js
Please Enter config password?********
CCXT version: 1.95.43
got here
^C
```

I saw in the documentation that "_this method is a work in progress now (may be unavailable)_", but in [ccxt](https://github.com/ccxt/ccxt)/[js](https://github.com/ccxt/ccxt/tree/master/js)/[pro](https://github.com/ccxt/ccxt/tree/master/js/pro)/binance.js, it shows **'watchMyTrades': true**. So is this a bug, or am I misusing it somehow? Is it supposed to be blocking until a trade is made?

Thanks in advance.

**Comment by pcriadoperez** [comment]
Hi @AwooOOoo , 
Did you execute any trades while it was running?
`watchMyTrades`  will wait and until a new trade update is received.
Also by default `exchange.newUpdates = true`  which means it will return only the latest trade update and not past trades. So you probably don't need to pass in a since argument for your use case.

**Comment by AwooOOoo** [comment]
Hi @pcriadoperez,
    OK, that makes sense. Yes, I ran a createOrder just prior. Normally capture the "since" time before the order so I know how far to look back, but not so far back that it might get a hit from a prior order. I do notice that I switched from the Rest command 'fetchTime' to just a simple 'new Date()', so it might be possible that a clock misalignment with the server means I don't register the order. Is there a streaming equivalent to fetchTime? Even the time of the most recently received message (as I request a lot), Unless you know a better way to get confirm my trade was completed (using just the streaming interface).

**Comment by AwooOOoo** [comment]
HI @pcriadoperez,
    Thanks. Understood. I appreciate the clarification.
