### ISSUE TITLE
BYBIT - Cannot get Open Orders on Spot and Derivatives

### ISSUE THREAD

**Issue by bluetyphoon77** [ccxt/ccxt#15959]
Is it now possible to fetch those open orders on spot and derivatives market with CCXT ? thanks a lot

**Comment by pcriadoperez** [comment]
Yes, you can use the function `bybit.fetchOpenOrders()` and you can also use the websockets version with `watchOrders()`. The websockets we are working on soon releasing support for bybit v3 api.

I'll close this issue for now, but feel free to post any more questions you might have.

**Comment by bluetyphoon77** [comment]
Hi thanks a lot for your answer. I will let this closed. But my dev checked your answer and said it is not true, what you said is not working. So he will create an issue himself with screenshots. Cheers

**Comment by frosty00** [comment]
@bluetyphoon77 you need to set

```
bybit.options['defaultType'] = 'spot'; // for spot
bybit.options['defaultType'] = 'swap'; // for swap
```

**Comment by bluetyphoon77** [comment]
Thanks a lot @frosty00 ;) 
I asked my dev to continue here himself. Thanks a lot for your help
Hope this will work !
PS: If you have any knowledge about kucoin don't hesitate to give me any advice you'd have, it will be super helpful, I have another issue about this, thanks a lot :)
