### ISSUE TITLE
ccxtpro: watchCreateOrder

### ISSUE THREAD

**Issue by Hadevmin** [ccxt/ccxt#15960]
Hi,

I find in the documentation of ccxt pro the method 'watchCreateOrder'(https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual#watchCreateOrder). 
It says '- this method is a work in progress now (may be unavailable)'

I know you have a lot of work to do, I just want to know if this functionality is still in the roadmap or if it has been abandoned?

Thank for your answer and thank you very much for the work done for this library.

**Comment by pcriadoperez** [comment]
Hi @Hadevmin ,
So we aren't actively working on `watchCreateOrder`  but `watchOrders` is quite available across exchanges. You can then check the status of the order if you want to filter them in any way.

**Comment by Hadevmin** [comment]
Thanks you @pcriadoperez,
Following the documentation, the correspondence  with ccxt is like this:
fetchOrders → watchOrders
createOrder → watchCreateOrder

Thanks for the information about watchOrders, it is very useful to supervise the orders sent via the REST API.

In my experiment, I wanted to place market orders to test the difference in speed between the REST API and the WS.

I will read documentations and try to make my test with the websocket-client library.

**Comment by pcriadoperez** [comment]
Hi @Hadevmin , wanted to check in to see if you had any questions or we can close this issue?
