### ISSUE TITLE
Withdrawal from Bybit bug

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#15967]
Hello. Can't withdraw from Bybit
`bybit.withdraw(coin, amount, address, tag=None, params={"network": network})`
brings 
`ccxt.base.errors.ExchangeError: bybit {"retCode":131002,"retMsg":"Withdraw address chain or destination tag are not equal","result":{},"retExtInfo":{},"time":1670251569306}`
and no matter how I paste "network" param - TRX or TRC20, anyway this error
and no matter, if I put name of network into tag - still same error

**Comment by sc0Vu** [comment]
Hi @KindSpidey 

I can withdraw from bybit trx network. Which ccxt version did you use? Was address format correct?

**Comment by KindSpidey** [comment]
Hi @sc0Vu 
2.2.40
Yes, just string, copied from MEXC

I tried "trx" instead of "TRC20" - still doesnt work
Do you use any whitelist on Bybit? I dont

**Comment by sc0Vu** [comment]
@KindSpidey I can reproduce this with lowercase chain trx, please use uppercase `TRX` before we update.

**Comment by KindSpidey** [comment]
@sc0Vu same with TRX `ccxt.base.errors.ExchangeError: bybit {"retCode":131002,"retMsg":"Withdraw address chain or destination tag are not equal","result":{},"retExtInfo":{},"time":1670321132934}`

**Comment by AlgoQ** [comment]
Hello,

> Do you use any whitelist on Bybit? I dont

Thank you for your inquiry about the use of withdraws on Bybit. According to the information provided by Bybit, it appears that it is necessary to enable IP restrictions and withdraws are only permitted to whitelisted addresses.

Please note that it is not necessary to open a new issue if your current issue has not been closed. If you need further assistance with your issue, you may post another reply and we will do our best to resolve it as soon as possible.

If you continue to experience difficulties, please do not hesitate to let us know.

**Comment by KindSpidey** [comment]
@AlgoQ ok, thanks
