### ISSUE TITLE
Bybit `fetch_funding_rate_history()` requires auth

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#15974]
- OS: linux
- Programming Language version: python
- CCXT version: 2.2.67

Using bybit's new `fetch_funding_rate_history()` endpoint requires authentication in ccxt - while the endpoint itself is a public endpoint and readily available [example](https://api.bybit.com/derivatives/v3/public/funding/history-funding-rate?category=linear&symbol=BTCUSDT&startTime=1652112000000&endTime=1652198400000) [docs](https://bybit-exchange.github.io/docs/derivativesV3/unified_margin/#t-dv_historyfundingratehead)

``` python
import ccxt
exchange = ccxt.bybit()
res = exchange.fetch_funding_rate_history('BTC/USDT:USDT')
```

```
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?e96dde98-4421-4e84-add7-aafb8876bce6)
---------------------------------------------------------------------------
AuthenticationError                       Traceback (most recent call last)
Cell In [7], line 2
      1 exchange.verbose = True
----> 2 exchange.fetch_funding_rate_history('BTC/USDT:USDT')

File ~/.pyenv/versions/3.10.8/envs/trade_3108/lib/python3.10/site-packages/ccxt/bybit.py:2138, in bybit.fetch_funding_rate_history(self, symbol, since, limit, params)
   2128 def fetch_funding_rate_history(self, symbol=None, since=None, limit=None, params={}):
   2129     """
   2130     fetches historical funding rate prices
   2131     :param str|None symbol: unified symbol of the market to fetch the funding rate history for
   (...)
   2136     :returns [dict]: a list of `funding rate structures <https://docs.ccxt.com/en/latest/manual.html?#funding-rate-history-structure>`
   2137     """
-> 2138     enableUnifiedMargin = self.is_unified_margin_enabled()
   2139     if not enableUnifiedMargin:
   2140         raise BadRequest(self.id + ' fetchFundingRateHistory() must enable unified margin mode')

File ~/.pyenv/versions/3.10.8/envs/trade_3108/lib/python3.10/site-packages/ccxt/bybit.py:845, in bybit.is_unified_margin_enabled(self, params)
    843 enableUnifiedMargin = self.safe_value(self.options, 'enableUnifiedMargin')
    844 if enableUnifiedMargin is None:
--> 845     response = self.privateGetUserV3PrivateQueryApi(params)
    846     #
    847     #     {
    848     #         "retCode":0,
...
-> 2902         raise AuthenticationError(self.id + ' requires "' + key + '" credential')
   2903     else:
   2904         return False

AuthenticationError: bybit requires "apiKey" credential
```

The request is also failing with `BadRequest: bybit {"retCode":10001,"retMsg":"params error: Time Is Invalid","result":{"category":"","list":[]},"retExtInfo":{},"time":1670268644916}` if only a start-time is provided ... which is a case i'd assume to be supported.

``` python
exchange.fetch_funding_rate_history('BTC/USDT:USDT', limit=1000, since=since_ms)
```

---

While using an API key is an option (not a good one, for a public endpoint), i think the permissions required for that are unjustified high in `"Account Transfer", "Subaccount Transfer", "Withdrawal"`.

```
PermissionDenied: bybit private api uses /user/v3/private/query-api to check if you have a unified account. The API key of user id must own one of permissions: "Account Transfer", "Subaccount Transfer", "Withdrawal" {"retCode":10005,"retMsg":"permission denied","result":null,"retExtInfo":null,"time":1670268474997}
```

**Comment by carlosmiei** [comment]
Hello @xmatthias,
Actually, the private call is made to figure out if the account is using the `unified` margin mode or not so it's not directly related to `funding rate` endpoint,  but yeah, I agree it's not ideal, we will re-evaluate it. 

Thanks for letting us know.

**Comment by xmatthias** [comment]
Hi @carlosmiei 

at least i can override this with `{'options': {'enableUnifiedMargin': True}` as exchange parameter ... 
but i assume that's account dependant in reality - so might break stuff?

No argument against calls where this is really necessary (it should default to "False" if that permission is missing) - but for a public endpoint, it seems unnecessary to call the private endpoint at all.
