### ISSUE TITLE
Wrong field "clientOrderId" on fetchMyTrades (spot) (api.hitbtc.com)

### ISSUE THREAD

**Issue by escoman** [ccxt/ccxt#15973]
- OS: Windows 10
- Programming Language version: PHP
- CCXT version: 2.2.36

On fetchMyTrades (spot) api.hitbtc.com returns "client_order_id" field.
But in ccxt/php/hitbtc3.php (row 979):
`$orderId = $this->safe_string($trade, 'clientOrderId');`

```
{
    "id": "1998105087",
    "fee": "0.000864500000",
    "side": "sell",
    "price": "17290.00",
    "taker": false,
    "symbol": "BTCUSDT",
    "order_id": "1017250371370",
    "quantity": "0.00005",
    "timestamp": "2022-12-05T02:47:22.148Z",
    "client_order_id": "6BC49F0585374DA291815BC885BEEFD2"
}
```

**Comment by carlosmiei** [comment]
Hello @escoman,
Thanks for letting us know, we will fix it soon!
