### ISSUE TITLE
Gateio fetch_deposits doesn't work | Bug

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#15980]
It just simply returns empty list

```
gateio = ccxt.gateio({
        "apiKey": config.GATEIO_API_KEY,
        "secret": config.GATEIO_SECRET_KEY,
        "options": {'defaultType': 'spot' }
    })
gateio.fetch_deposits()
```

**Comment by carlosmiei** [comment]
Hello @KindSpidey, can you provide a verbose log?

**Comment by carlosmiei** [comment]
@KindSpidey as you can see the exchange itself returns an empty array, are aware of this condition?
![image](https://user-images.githubusercontent.com/43336371/205977427-804347e1-b7d3-4d20-88af-eaeb3581ce86.png)

More info: https://www.gate.io/docs/developers/apiv4/en/#retrieve-deposit-records

**Comment by carlosmiei** [comment]
> @carlosmiei
> 
> No, so, as I understand, if there are no deposits for last 7 days, exchange will return empty array?

@KindSpidey If you don't set a `since` it will return deposits for the last 7 days, if none yes will return an empty array. By defining a `since` you can retrieve deposits from up to 30 days.

**Comment by KindSpidey** [comment]
@carlosmiei
Oh, got it. Thank you very much. "Since" must be sent into params?
