### ISSUE TITLE
bybit fetchFundingRateHistory since/limit bug

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#15990]
- OS:linux
- Programming Language version: python
- CCXT version: '2.2.79'

with #15974 fixed, there's another bug in fetch_funding_rate when providing since in combination with "limit".

Aligned with other such endpoints, i'd expect the "limit" parameter to be respected, so the below request should work.

```python
import ccxt
from datetime import timedelta, datetime
exchange = ccxt.bybit()
res = exchange.fetch_funding_rate_history('BTC/USDT:USDT', since=int((datetime.now() - timedelta(days=200)).timestamp() * 1000), limit=200)
```

Yields the following exception (with verbose log):

```
fetch Request: bybit GET https://api.bybit.com/derivatives/v3/public/funding/history-funding-rate?symbol=BTCUSDT&category=linear&startTime=1653063081904&limit=199 RequestHeaders: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bybit GET https://api.bybit.com/derivatives/v3/public/funding/history-funding-rate?symbol=BTCUSDT&category=linear&startTime=1653063081904&limit=199 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '130', 'Traceid': '7484a5fb19611d004148fabf95663fa8', 'Timenow': '1670346928381', 'Server': 'Openresty', 'Expires': 'Tue, 06 Dec 2022 17:15:28 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Tue, 06 Dec 2022 17:15:28 GMT', 'Connection': 'keep-alive'} ResponseBody: {"retCode":10001,"retMsg":"params error: Time Is Invalid","result":{"category":"","list":[]},"retExtInfo":{},"time":1670346928381}

BadRequest: bybit {"retCode":10001,"retMsg":"params error: Time Is Invalid","result":{"category":"","list":[]},"retExtInfo":{},"time":1670346777827}
```

It seems that (countrary to the [documentation for this endpoint](https://bybit-exchange.github.io/docs/derivativesV3/unified_margin/#t-dv_historyfundingratehead)) `endTime` is mandatory even if limit is given.
This might just as well be a bug in their API ... - but assuming current behavior as given .

Obviously using the parameter "until" would work - but for most other exchanges, ccxt calculates this automatically if only since _and limit_ is given.

**Comment by sc0Vu** [comment]
It seems the parameter should be `start` & `until`.

We probably calculate these parameters for ohlcv data (timeframe data).

Anyway, I'll check on this.
