### ISSUE TITLE
crypto.com fetchOHLCV returns only 25 candles

### ISSUE THREAD

**Issue by levikarod** [ccxt/ccxt#16007]
- Programming Language version: python 3.9.9
- CCXT version: 2.2.69

Hi guys! So I'm using fetchOHLCV to get the candles from crypto.com but I'm only receiving 25 regardless of the arguments limit and since. Whereas with the crypto.com api I'm getting 300.

Could this be a bug? or am I missing something

This my code:
```
exchange_id = 'cryptocom'
store = getattr(ccxt, exchange_id)
config = {
        "options":{
        "defaultType":"future"}
    }
store = store(config)

ohlcv = store.fetchOHLCV(symbol='BTCUSD-PERP', timeframe='1m', limit=1000)
print(len(ohlcv)) # 25
```

**Comment by carlosmiei** [comment]
Hello @levikarod, yeah we're not setting the limit as we should, will fix it soon. 

In the meantime, as a workaround you can do this: `store.fetchOHLCV(symbol='BTCUSD-PERP', timeframe='1m', limit=1000, params = {'count': 300})`
