### ISSUE TITLE
Kraken's response has little information

### ISSUE THREAD

**Issue by bonetjoshua** [ccxt/ccxt#16006]
- OS:
- Programming Language version:
- CCXT version:

```
 order = kraken.createOrder(symbol_name, type,side,quantity, price)
```
This is the response I get:
```
{'id': 'XXXXXXXXXXX', 'clientOrderId': None, 'info': {'txid': ['XXXXXXXXX'], 'descr': {'order': 'sell 0.00178900 XBTUSD @ limit 16776.3'}}, 'timestamp': None, 'datetime': None, 'lastTradeTimestamp': None, 'status': None, 'symbol': 'BTC/USD', 'type': 'limit', 'timeInForce': None, 'postOnly': None, 'side': 'sell', 'price': 16776.3, 'stopPrice': None, 'cost': None, 'amount': 0.001789, 'filled': None, 'average': None, 'remaining': None, 'fee': None, 'trades': [], 'fees': []} 
```
I looked up Kraken's REST API and they seem to have information about the trade when it's open and when it's closed but the response inside CCXT is just all NONE which does not help at all.

The following is the open orders response from Kraken:
{
  "result": {
    "open": {
      "txid1": {
        "refid": "string",
        "userref": "string",
        "status": "pending",
        "opentm": 0,
        "starttm": 0,
        "expiretm": 0,
        "descr": {
          "pair": "string",
          "type": "buy",
          "ordertype": "market",
          "price": "string",
          "price2": "string",
          "leverage": "string",
          "order": "string",
          "close": "string"
        },
        "vol": "string",
        "vol_exec": "string",
        "cost": "string",
        "fee": "string",
        "price": "string",
        "stopprice": "string",
        "limitprice": "string",
        "trigger": "last",
        "misc": "string",
        "oflags": "string",
        "trades": [
          "string"
        ]
      },
      "txid2": {
        "refid": "string",
        "userref": "string",
        "status": "pending",
        "opentm": 0,
        "starttm": 0,
        "expiretm": 0,
        "descr": {
          "pair": "string",
          "type": "buy",
          "ordertype": "market",
          "price": "string",
          "price2": "string",
          "leverage": "string",
          "order": "string",
          "close": "string"
        },
        "vol": "string",
        "vol_exec": "string",
        "cost": "string",
        "fee": "string",
        "price": "string",
        "stopprice": "string",
        "limitprice": "string",
        "trigger": "last",
        "misc": "string",
        "oflags": "string",
        "trades": [
          "string"
        ]
      }
    }
  },
  "error": [
    "EGeneral:Invalid arguments"
  ]
}

It seems like you guys have a lot on your plate so I do appreciate any help possible. Thank you

**Comment by carlosmiei** [comment]
Hello @bonetjoshua, upon creating the order Kraken returns little information but you can use `fetchOrder` after creating it to get the full data.

**Comment by bonetjoshua** [comment]
I appreciate the work around, I wish CCXT could fix this in the future. I'll close this issue
