### ISSUE TITLE
fetchBalance()

### ISSUE THREAD

**Issue by partosup** [ccxt/ccxt#16004]
- OS: UBUNTU
- Programming Language version: PHP
- CCXT version: 2.2.79

        $exchange_class = "\\ccxt\\bybit";
        $credentials = [
            'apiKey' => 'apikey',
            'secret' => 'secretkey',
        ];
        $exchange = new $exchange_class($credentials);
        $exchange->enableRateLimit = true;
        $exchange->options['defaultType'] = 'spot';
        $bal = $exchange->fetchBalance();

the result does not see the real balance,
there is a balance in USDT , but displays in USDC with a zero balance.

version "ccxt/ccxt": "2.1.70" shows correct balance

**Comment by carlosmiei** [comment]
Hello @partosup, yes we detected this issue before, can you update to the latest version and try again please?

**Comment by partosup** [comment]
It works, thanks

**Comment by partosup** [comment]
![image](https://user-images.githubusercontent.com/14160218/207439227-868ef2d0-0df9-4446-83e2-daa116fe8cd0.png)
no, it does not work

**Comment by samgermain** [comment]
> ![image](https://user-images.githubusercontent.com/14160218/207439227-868ef2d0-0df9-4446-83e2-daa116fe8cd0.png) it does not work, latest version 2.2.103

can you copy and paste the error response instead of taking a screenshot? It would be helpful to see what's inside `info`

**Comment by partosup** [comment]
Thanks, the problem is in the geolocation of the VPS.
Exchange response - "Service unavailable from a restricted location according to 'b. Eligibility' "

**Comment by partosup** [comment]
> > ![image](https://user-images.githubusercontent.com/14160218/207439227-868ef2d0-0df9-4446-83e2-daa116fe8cd0.png) it does not work, latest version 2.2.103
> 
> can you copy and paste the error response instead of taking a screenshot? It would be helpful to see what's inside `info`

Array
(
    [info] => Array
        (
            [retCode] => 0
            [retMsg] => OK
            [result] => Array
                (
                    [balances] => Array
                        (
                            [0] => Array
                                (
                                    [coin] => BTC
                                    [coinId] => BTC
                                    [total] => 0.0000002348
                                    [free] => 0.0000002348
                                    [locked] => 0
                                )

                            [1] => Array
                                (
                                    [coin] => USDT
                                    [coinId] => USDT
                                    [total] => 48.5650332
                                    [free] => 48.5650332
                                    [locked] => 0
                                )

                        )

                )

            [retExtInfo] => Array
                (
                )

            [time] => 1671033774795
        )

    [USDC] => Array
        (
            [free] => 
            [used] => 
            [total] => 
        )

    [free] => Array
        (
            [USDC] => 
        )

    [used] => Array
        (
            [USDC] => 
        )

    [total] => Array
        (
            [USDC] => 
        )

)

**Comment by partosup** [comment]
Array
(
    [info] => Array
        (
            [retCode] => 0
            [retMsg] => OK
            [result] => Array
                (
                    [balances] => Array
                        (
                            [0] => Array
                                (
                                    [coin] => BTC
                                    [coinId] => BTC
                                    [total] => 0.0000002348
                                    [free] => 0.0000002348
                                    [locked] => 0
                                )

                            [1] => Array
                                (
                                    [coin] => USDT
                                    [coinId] => USDT
                                    [total] => 48.5650332
                                    [free] => 48.5650332
                                    [locked] => 0
                                )

                        )

                )

            [retExtInfo] => Array
                (
                )

            [time] => 1671033774795
        )

    [USDC] => Array
        (
            [free] => 
            [used] => 
            [total] => 
        )

    [free] => Array
        (
            [USDC] => 
        )

    [used] => Array
        (
            [USDC] => 
        )

    [total] => Array
        (
            [USDC] => 
        )

)
