### ISSUE TITLE
is createMarketBuyOrder part of the unified API?

### ISSUE THREAD

**Issue by michnovka** [ccxt/ccxt#1600]
I need a way to detect if exchange supports market / limit orders. I came across function `createMarketBuyOrder` [in Wiki](https://github.com/ccxt/ccxt/wiki/Manual#unified-api) but I cannot find this function implemented e.g. in Binance, where market orders are supported.

So my questions are:

1. should we add createMarketBuyOrder, createMarketSellOrder, createLimitSellOrder, createLimitBuyOrder into "has" of an exchange?
2. are these functions supposed to exist in exchanges which support these features? Or are they part of somewhat old design that is no longer used and createOrder is enough.
3. related to question 2. - should I work on adding these functions into exchanges which support market/limit orders and have these not implemented?

Thanks,
T

**Comment by kroitor** [comment]
> but I cannot find this function implemented e.g. in Binance

These methods:
- `createMarketBuyOrder`
- `createMarketSellOrder`
- `createLimitSellOrder`
- `createLimitBuyOrder`

... are implemented in the base class and those four methods are just convenience wrappers around `createOrder`:

- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L797
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L1038
- https://github.com/ccxt/ccxt/blob/master/php/Exchange.php#L1361

> 1. should we add createMarketBuyOrder, createMarketSellOrder, createLimitSellOrder, createLimitBuyOrder into "has" of an exchange?

We think adding four properties is excessive, instead we think of, maybe, adding two more wrappers and these two properties to the `has` metainfo:

- `has['createMarketOrder']
- `has['createLimitOrder']

However, the above two options are also pretty much excessive as practically with any exchange you can emulate markets orders with limit orders anyway.

> 2. are these functions supposed to exist in exchanges which support these features?

No need to redefine them, we just inherit them from the base class.

> Or are they part of somewhat old design that is no longer used and createOrder is enough.

No, they are not a part of old design, they are part of current implementation.

> 3. related to question 2. - should I work on adding these functions into exchanges which support market/limit orders and have these not implemented?

From the above it follows, that, no, you shouldn't ) Thx )

Let me know if it does not answer your questions, or if you want to suggest a different approach.

**Comment by michnovka** [comment]
> We think adding four properties is excessive, instead we think of, maybe, adding two more wrappers and these two properties to the has metainfo:
    has['createMarketOrder']
    has['createLimitOrder']

Yes, this would be sufficient.

> However, the above two options are also pretty much excessive as practically with any exchange you can emulate markets orders with limit orders anyway.

Yes, I assume you can put some incredible price like 100BTC/coin and this will of course sell as market order, however it is not 100% the same and it does help me to know about feature set of individual exchanges. If possible, can we agree to add these 2 params and start the slow process of integrating this into all exchanges? I will gladly help with all those I use. We should also update wiki to mention this.

Thanks,
T

**Comment by kroitor** [comment]
> If possible, can we agree to add these 2 params and start the slow process of integrating this into all exchanges? 

Sure, why not ) Let me upload the wrappers first, you'll see a commit notification here.

> I will gladly help with all those I use. We should also update wiki to mention this.

Thx for that!

**Comment by kroitor** [comment]
@cristoforo hi ) 

> I would gladly help with several exchanges about has['createMarketOrder']
and has['createLimitOrder'].

Thx! )

> I see this issue was closed, should we open a new one?

Whatever is more convenient to you, we can continue here or move to a new one, totally up to you.
