### ISSUE TITLE
watchBookTicker() feature request

### ISSUE THREAD

**Issue by L1nkus** [ccxt/ccxt#16009]
Most exchanges have a 'bookTicker' websocket endpoint, with real-time best bids and asks.

Ccxt has watchTicker(), which uses 'ticker' and not 'bookTicker' endpoints, and this generally updates very slowly, like every 1s, vs bookTicker is real-time.

Is watchBookTicker() on a todo list?

**Comment by pcriadoperez** [comment]
Hi @L1nkus , for exchanges that offer `bookTicker`  we implement it inside `watchTicker()` as an option. So for example in bybit you can set the option  `this.options['spot']['watchTickerTopic'] = 'bookticker'

Was there any exchange you were specially interested in?

**Comment by L1nkus** [comment]
Thanks for response @pcriadoperez, I didn't know about options.

Yep, I were interested about huobi, and there doesn't seem to be such an option for it. Huobi has bookticker named as bbo (best bid-ask): https://huobiapi.github.io/docs/spot/v1/en/#best-bid-offer

**Comment by pcriadoperez** [comment]
Hi @L1nkus , I opened a PR to add the option for huobi (https://github.com/ccxt/ccxt/pull/16198)
