### ISSUE TITLE
okx : fetch_mark_ohlcv : history-mark-price-candles

### ISSUE THREAD

**Issue by Hadevmin** [ccxt/ccxt#16014]
- Programming Language version: Python
- CCXT version: 2.2.80

I would like use https://www.okx.com/docs-v5/en/#rest-api-market-data-get-mark-price-candlesticks-history

But when I use fetch_mark_ohlcv method it's mark-price-candles endpoint called:
```
exchange = ccxt.pro.okx()
since = int(time.time() - 300000) * 1000
await exchange.fetch_mark_ohlcv('ETH/USDT', '1m', since=since, limit=100)
```

```
fetch Request: okx GET https://www.okx.com/api/v5/market/mark-price-candles?instId=ETH-USDT&bar=1m&limit=100&before=1670157530999&after=1670163530999 RequestHeaders: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate'} RequestBody: None

fetch Response: okx GET https://www.okx.com/api/v5/market/mark-price-candles?instId=ETH-USDT&bar=1m&limit=100&before=1670157530999&after=1670163530999 200 ResponseHeaders: {'Date': 'Wed, 07 Dec 2022 23:58:52 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY', 'X-BrokerID': '0', 'Strict-Transport-Security': 'max-age=63072000; includeSubdomains; preload', 'Content-Encoding': 'gzip', 'CF-Cache-Status': 'DYNAMIC', 'Set-Cookie': '__cf_bm=IaDNIT0XudestxbTRH7RsGgS1PQVmd7IH7YHE4qtkyE-1670457532-0-AZWylwNod2rC1VQa+MfMNxGOK1z8ABcU8Jz/N7j63g/kr/z6BmoIcxJ/6shxHoeZqMprxmE9MMLzpdJ77+JFksM=; path=/; expires=Thu, 08-Dec-22 00:28:52 GMT; domain=.okx.com; HttpOnly; Secure; SameSite=None', 'Server': 'cloudflare', 'CF-RAY': '776136381a79102f-MRS'} ResponseBody: {"code":"0","msg":"","data":[]}
```

Is there a method to get the 'history-mark-price-candles' or I have to use a exchange.public_get_market_history_mark_price_candles() ?

Thanks

**Comment by samgermain** [comment]
> 

Can you explain what the difference between the 2 endpoints is?

**Comment by Hadevmin** [comment]
Hi @samgermain,

First: (use with exchange.fetch_mark_ohlcv() )
doc: https://www.okx.com/docs-v5/en/#rest-api-market-data-get-mark-price-candlesticks
'/api/v5/market/mark-price-candles' can retrieve the latest 1,440 data entries.

Second:
doc: https://www.okx.com/docs-v5/en/#rest-api-market-data-get-mark-price-candlesticks-history
'/api/v5/market/history-mark-price-candles' can retrieve the candlestick charts of mark price from recent years.

If we want get mark price with large history, we need to use the second method.
I didn't have time to investigate but using 'public_get_market_history_mark_price_candles()' I have a response time that is much higher than all other methods to get ohlcv.

**Comment by Hadevmin** [comment]
Hi @samgermain ,

I trying to understand how the exchange object work, but I don't understand how can I try to change the endpoint used by fetch_mark_ohlcv for try the functionality or create new funtion fetch_mark_ohlcv_history. So I can't propose a PR...

Other thing, in assync_support\okx.py line 178, I have replace 
'market/history-mark-price-candles': 120 
by 
'market/history-mark-price-candles': 2
The time to get candles after this change is faster and I don't get HTTP 429 return from the server.

I assume that this value is used by the rate limiter. So I followed the logic that the limit is half as big as for the endpoint market/mark-price-candles
As I observed that 'market/mark-price-candles': 1, I doubled the value to assign it to 'market/history-mark-price-candles'.

**Comment by samgermain** [comment]
> Hi @samgermain ,
> 
> I trying to understand how the exchange object work, but I don't understand how can I try to change the endpoint used by fetch_mark_ohlcv for try the functionality or create new funtion fetch_mark_ohlcv_history. So I can't propose a PR...
> 
> Other thing, in assync_support\okx.py line 178, I have replace 'market/history-mark-price-candles': 120 by 'market/history-mark-price-candles': 2 The time to get candles after this change is faster and I don't get HTTP 429 return from the server.
> 
> I assume that this value is used by the rate limiter. So I followed the logic that the limit is half as big as for the endpoint market/mark-price-candles As I observed that 'market/mark-price-candles': 1, I doubled the value to assign it to 'market/history-mark-price-candles'.

It would be something like
```js
...
if (price === 'mark') {
    const defaultMethod = this.safestring (this.options, 'fetchMarkOHLCVMethod', 'publicGetMarketMarkPriceCandles');
    method = this.safeString2 (params, 'method', 'fetchMarkOHLCVMethod', defaultMethod);
} else if (price === 'index') {
...
```

in [this part](https://github.com/ccxt/ccxt/blob/efcff1a92c2ce4298a13356f768e8a5b61754c8e/js/okx.js#L1654) of the okx class, and then you can set `fetchMarkOHLCVMethod` in options when you instantiate your exchange object like

```
const exchange = ccxt.okx({
    'apiKey': '...',
    'secret': '...',
    'options': { 
        'fetchMarkOHLCVMethod': 'publicGetMarketHistoryMarkPriceCandles',
    }
```

or you can set the method in the params of `fetchOHLCV`

```js
exchange.fetchOHLCV(symbol='BTC/USDT', params={'method': 'publicGetMarketHistoryMarkPriceCandles', 'price': 'mark'})
```
or
```js
exchange.fetchOHLCV(symbol='BTC/USDT', params={'fetchMarkOHLCVMethod': 'publicGetMarketHistoryMarkPriceCandles', 'price': 'mark'})
```

You should also set `fetchMarkOHLCVMethod: 'publicGetMarketMarkPriceCandles'` within `options` in the `describe` method

Here's [an example](https://github.com/ccxt/ccxt/blob/efcff1a92c2ce4298a13356f768e8a5b61754c8e/js/alpaca.js#L331) of what I'm talking about

**Comment by Hadevmin** [comment]
@samgermain Thanks you to have taken the time to explain to me. I understand more and more how ccxt works, it's nice to exchange with you.
@sc0Vu thanks you for your PR. I hope that my explanations have simplified your work.

A last question, how can I set in the instantiation of my exchange object, the value for line 178 in async.okx:
```
'api': {
                'public': {
                    'get': {
                       ...
                        'market/history-mark-price-candles': 120,  <---- THIS
```

Thanks you for your help.
