### ISSUE TITLE
bybit spot side parsing bug: 'side' is incorrectly parsed for fetch_my_trades

### ISSUE THREAD

**Issue by yatoh22** [ccxt/ccxt#16017]
Spot trades side parameter is incorrectly parsed as 0 when isBuyer is True

- OS:Windows
- Programming Language version:Python
- CCXT version: 2.2.84

```
exchange = ccxt.bybit()
exchange.set_sandbox_mode(True)
exchange.verbose = True
exchange.apiKey = api_Bybit
exchange.secret = api_secret_Bybit
exchange.options['defaultType'] = 'spot'
unified = exchange.fetch_my_trades(symbol = 'XRP/USDT')
raw = exchange.privateGetSpotV1MyTrades(params={'symbol': 'XRPUSDT'})['result']
```

```
raw return 'isBuyer' as True but unified would return side as 'Sell'
```
verbose output:

fetch Request: bybit GET https://api-testnet.bybit.com/user/v3/private/query-api?api_key=NKNXjUFIuD4UEoPAdm&recv_window=5000&timestamp=1670480599045&sign=2e5c343f86e7d534ea8b6a70608a4275ef94416088b5e72ef4e54b966e237d9c RequestHeaders: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bybit GET https://api-testnet.bybit.com/user/v3/private/query-api?api_key=NKNXjUFIuD4UEoPAdm&recv_window=5000&timestamp=1670480599045&sign=2e5c343f86e7d534ea8b6a70608a4275ef94416088b5e72ef4e54b966e237d9c 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '577', 'X-Bapi-Limit': '10', 'X-Bapi-Limit-Status': '9', 'X-Bapi-Limit-Reset-Timestamp': '1670480598874', 'Traceid': '31670f48f014ba283a2e64a7aace02af', 'Timenow': '1670480598879', 'Server': 'Openresty', 'Expires': 'Thu, 08 Dec 2022 06:23:18 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 08 Dec 2022 06:23:18 GMT', 'Connection': 'keep-alive'} ResponseBody: {"retCode":0,"retMsg":"OK","result":{"id":"366474","note":"read only","apiKey":"NKNXjUFIuD4UEoPAdm","readOnly":1,"secret":"","permissions":{"ContractTrade":["Order","Position"],"Spot":["SpotTrade"],"Wallet":["AccountTransfer","SubMemberTransfer"],"Options":["OptionsTrade"],"Derivatives":["DerivativesTrade"],"CopyTrading":["CopyTrading"],"BlockTrade":[],"Exchange":["ExchangeHistory"],"NFT":["NFTQueryProductList"]},"ips":["*"],"type":1,"deadlineDay":86,"expiredAt":"2023-03-05T03:40:04Z","createdAt":"2022-12-05T03:40:04Z","unified":0},"retExtInfo":null,"time":1670480598879}

fetch Request: bybit GET https://api-testnet.bybit.com/spot/v3/private/my-trades?api_key=NKNXjUFIuD4UEoPAdm&recv_window=5000&symbol=XRPUSDT&timestamp=1670480599209&sign=8b74451df3f4185749a186c02bc0c2676a907d4d0451ec19aa4ccea040dd2f95 RequestHeaders: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bybit GET https://api-testnet.bybit.com/spot/v3/private/my-trades?api_key=NKNXjUFIuD4UEoPAdm&recv_window=5000&symbol=XRPUSDT&timestamp=1670480599209&sign=8b74451df3f4185749a186c02bc0c2676a907d4d0451ec19aa4ccea040dd2f95 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '744', 'X-Bapi-Limit': '20', 'X-Bapi-Limit-Status': '19', 'X-Bapi-Limit-Reset-Timestamp': '1670480599033', 'Ret_code': '0', 'Traceid': '86b086d94d8a1093fd8677b23ff6d575', 'Timenow': '1670480599042', 'Server': 'Openresty', 'Expires': 'Thu, 08 Dec 2022 06:23:19 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 08 Dec 2022 06:23:19 GMT', 'Connection': 'keep-alive'} ResponseBody: {"retCode":0,"retMsg":"OK","result":{"list":[{"symbol":"XRPUSDT","id":"1306477215912839168","orderId":"1306477215669569536","tradeId":"2110000000001007685","orderPrice":"0.1154","orderQty":"460.92","execFee":"0","feeTokenId":"XRP","creatTime":"1670480220702","isBuyer":"0","isMaker":"1","matchOrderId":"1306135110375974912","makerRebate":"0","executionTime":"1670480220723"},{"symbol":"XRPUSDT","id":"1306477215904450560","orderId":"1306477215669569536","tradeId":"2110000000001007684","orderPrice":"0.1154","orderQty":"405.63","execFee":"0","feeTokenId":"XRP","creatTime":"1670480220702","isBuyer":"0","isMaker":"1","matchOrderId":"1304993033407711232","makerRebate":"0","executionTime":"1670480220722"}]},"retExtInfo":{},"time":1670480599042}

fetch Request: bybit GET https://api-testnet.bybit.com/spot/v1/myTrades?api_key=NKNXjUFIuD4UEoPAdm&recv_window=5000&symbol=XRPUSDT&timestamp=1670480599373&sign=52da41cc19b407b16320e9ad540072feefd6101ac219df0036e48a85a7943203 RequestHeaders: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bybit GET https://api-testnet.bybit.com/spot/v1/myTrades?api_key=NKNXjUFIuD4UEoPAdm&recv_window=5000&symbol=XRPUSDT&timestamp=1670480599373&sign=52da41cc19b407b16320e9ad540072feefd6101ac219df0036e48a85a7943203 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '985', 'X-Bapi-Limit': '20', 'X-Bapi-Limit-Status': '19', 'X-Bapi-Limit-Reset-Timestamp': '1670480599200', 'Ret_code': '0', 'Traceid': 'daed7c13662fd102975c3744f64a9d4a', 'Timenow': '1670480599210', 'Server': 'Openresty', 'Expires': 'Thu, 08 Dec 2022 06:23:19 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 08 Dec 2022 06:23:19 GMT', 'Connection': 'keep-alive'} ResponseBody: {"ret_code":0,"ret_msg":"OK","result":[{"id":"1306477215912839168","symbol":"XRPUSDT","symbolName":"XRPUSDT","orderId":"1306477215669569536","ticketId":"2110000000001007685","matchOrderId":"1306135110375974912","price":"0.1154","qty":"460.92","commission":"0","commissionAsset":"XRP","time":"1670480220702","isBuyer":true,"isMaker":false,"fee":{"feeTokenId":"XRP","feeTokenName":"XRP","fee":"0"},"feeTokenId":"XRP","feeAmount":"0","makerRebate":"0","executionTime":"1670480220723"},{"id":"1306477215904450560","symbol":"XRPUSDT","symbolName":"XRPUSDT","orderId":"1306477215669569536","ticketId":"2110000000001007684","matchOrderId":"1304993033407711232","price":"0.1154","qty":"405.63","commission":"0","commissionAsset":"XRP","time":"1670480220702","isBuyer":true,"isMaker":false,"fee":{"feeTokenId":"XRP","feeTokenName":"XRP","fee":"0"},"feeTokenId":"XRP","feeAmount":"0","makerRebate":"0","executionTime":"1670480220722"}],"ext_code":"","ext_info":{},"time_now":"1670480599.210120"}

**Comment by carlosmiei** [comment]
Hello @yatoh22,
thanks for reporting it, will be fixed very soon
