### ISSUE TITLE
Kucoin watchBalance() no response 

### ISSUE THREAD

**Issue by alexey-gorlitsky** [ccxt/ccxt#16019]
- OS: Linux
- Programming Language version: node:18.10
- CCXT version: 2.4.33

Hi,
on watching the balance, there is no response on updating the balance:

```
const kucoin = new ccxt.kucoin({
      apiKey: "xxxxxxxxxxxxxx",
      secret: "xxxxxxxxxxxxxx",
      password: "xxxxxxxxxxxxx",
    });

await kucoin.loadMarkets();
while (true) {
    try {
       const balanceUpdated = await kucoin.watchBalance();
       console.log("INFO Updated balance: ", balanceUpdated); 
        //
      } catch (e) {
        console.log("Error: ", e);
        break;
      } 
}
```
with param kucoin.verbose = true; 
we are getting debug output with updated data, no errors

**Comment by AlgoQ** [comment]
Hi @alexey-gorlitsky,
You need to import your exchange from `ccxt.pro` whenever you are making use of any websockets function (all the `watch` functions)

Example:
```js
const ccxt = require ('ccxt')

async function main () {
     const exchange = new ccxt.pro.kucoin ({
      "apiKey": "YOUR_API_KEY",
      "secret": "YOUR_SECRET_KEY", 
      "password": "YOUR_PASSWORD",
    })
    await exchange.loadMarkets ()
    while (true) {
        try {
            const response = await exchange.watchBalance ()
            console.log (new Date (), response)
        } catch (e) {
            console.log (e.constructor.name, e.message)
            await exchange.sleep (1000)
        }
    }
}

main ()
```

**Comment by alexey-gorlitsky** [comment]
Hi @AlgoQ ,
sorry for confusing you,
I do use **ccxt.pro** for the websockets functions, I just made a mistake in my example here.
My code looks exactly like yours and still, there is no response on updating the balance on watching **kucoin** balance.

**Comment by AlgoQ** [comment]
Hi @alexey-gorlitsky,

I took a closer look at the issue and found out that `watchBalance()` only responses the balance from your trading account. After you have some balance in your trading account you will. When you transfer money from your main -> trading account or visa verse, `watchBalance` will log the updated response:
```
2022-12-20T14:43:17.259Z {
  USDT: { free: 10.2, used: 0, total: 10.2 },
  free: { USDT: 10.2 },
  used: { USDT: 0 },
  total: { USDT: 10.2 }
}
2022-12-20T14:46:17.554Z {
  USDT: { free: 8.2, used: 0, total: 8.2 },
  free: { USDT: 8.2 },
  used: { USDT: 0 },
  total: { USDT: 8.2 }
}
```

**Comment by alexey-gorlitsky** [comment]
Hey @AlgoQ ,
thank you for your response, 
but how can you explain the fact that I can see a balance update on the main account in the output with param kucoin.verbose = true; ?
