### ISSUE TITLE
I always get a request timeout error on bybit api…

### ISSUE THREAD

**Issue by janstrw13** [ccxt/ccxt#16021]
Why I always get this error… any
![4FFB0E24-CDF6-4C1F-87B0-B1960F8E6EAB](https://user-images.githubusercontent.com/119401920/206430643-01adab87-a3c7-436f-b11e-0f33b44d64c7.png)
 solutions?

**Comment by carlosmiei** [comment]
Hello @janstrw13,
That seems related to some network issue, are you using a proxy or something like that? Do you get a successful response when opening that URL in the browser?

**Comment by Uther2022** [comment]
I get the same error on phemex as well. I did have the refresh rate on the boy set to 10 secnds and it would crash with that error in about 20 minutes. I chaged the refresh rate to 30 seconds and its been unning for about 2 hours. Not sure if this will fix the issue though in the long run.

**Comment by frosty00** [comment]
you should catch and handle the error using try: except
