### ISSUE TITLE
Can I use the repo to receive tokens to and from different networks?

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#16022]
- OS: Windows 10 PRO
- Programming Language version: Node.js (version 19.2.0)
- CCXT version: 2.2.84

Hi,

I know I can use CCXT to withdraw tokens to any address if they are in ERC20, BEP20, SPL, TRC20 networks.
But I want to know if I can use some wallet, like Exodus which has desktop version, I create a wallet and I have the private key. I can withdraw tokens from my account in exchange to my wallet and can I use CCXT with the private key to send tokens from my wallet address to another my account in another exchange.

For example: 

Let’s say I setup Exodus wallet for Windows 10, and I have the address with the private key.

If I want to withdraw some USDT from my Binance account via ERC20 network, after I receive the USDT from my Binance account, can I use CCXT with the Exodus wallet private key, after paying the gas fees, send USDT to my Huobipro account via BEP20 network?

I think receiving the USDT should work,  as it just a different address as any other exchange address.

Please advise if I can send USDT from wallet address with private key to another account in different exchange.
Thanks,

**Comment by carlosmiei** [comment]
Hello @zydjohnHotmail, the short answer is no,
CCXT wraps the exchange's API so basically, we're only a middleware that wraps the REST calls you make to the Exchange. So as you said, yes you can use ccxt to ask the exchange X to withdraw the token to Y wallet, but not the other way around but ccxt itself does not interact with the blockchain.

**Comment by zydjohnHotmail** [comment]
Thanks for your feed back!

**Comment by carlosmiei** [comment]
@zydjohnHotmail You're welcome! 🙂
