### ISSUE TITLE
ccxt.pro.bitget is not a constructor

### ISSUE THREAD

**Issue by kaiqiangh** [ccxt/ccxt#16033]
- OS: macos 16
- Programming Language version: node 16.18.1
- CCXT version: 2.2.91

```
new ccxt.pro.bitget(exchangeAPIKey);
```

<img width="603" alt="WechatIMG7" src="https://user-images.githubusercontent.com/9014062/206729878-7272afa9-b8a0-4a64-951b-282bf613a571.png">

I got an error - "TypeError: ccxt.pro.bitget is not a constructor". Any suggestion for this issue? Thanks

**Comment by samgermain** [comment]
> * OS: macos 16
> 
>     * Programming Language version: node 16.18.1
> 
>     * CCXT version: 2.2.91
> 
> 
> ```
> new ccxt.pro.bitget(exchangeAPIKey);
> ```
> 
> <img alt="WechatIMG7" width="603" src="https://user-images.githubusercontent.com/9014062/206729878-7272afa9-b8a0-4a64-951b-282bf613a571.png">
> 
> I got an error - "TypeError: ccxt.pro.bitget is not a constructor". Any suggestion for this issue? Thanks

That's weird, it's working fine for me

```js
const ccxt = require ('ccxt');
const keys = require ('./keys.local.json');

console.log ('CCXT Version:', ccxt.version);

async function main () {

    const exchange = new ccxt.pro.bitget ({
        'apiKey': keys.bitget.apiKey,
        'secret': keys.bitget.secret,
        'password': keys.bitget.password,
    });
    const balance = await exchange.fetchDepositAddress ('BTC');
    console.log (balance);
};

main ();
```

prints out

```
CCXT Version: 2.2.98
{
  currency: 'BTC',
  address: '0x207451fc93101b104cb92129bb71f8d731bdbbba',
  tag: undefined,
  network: undefined,
  info: {
    coin: 'BTC',
    address: '0x207451fc93101b104cb92129bb71f8d731bdbbba',
    chain: null,
    tag: '',
    url: 'https://bscscan.com/tx/'
  }
}
```

**Comment by kaiqiangh** [comment]
After upgrading CCXT, it works. Thanks!
