### ISSUE TITLE
NotSupported:   bitrue fetchPosition() is not supported yet

### ISSUE THREAD

**Issue by Nitrix321** [ccxt/ccxt#16032]
Hello,

is it planned to add this function? 
I like this exchange so far for several reasons, but without fetchposition unfortunately not usable for me.

**Comment by Nitrix321** [comment]
I also tried several other exchanges.
Is it true, that in all of the following exchanges the function "fetch_positions" ist not available?

-Bitmart
-Bkex
-Bitrue
-Bigone
-Digifinex
-Poloniex

I get the same "error" message on all of them:  NotSupported: "exchange" fetchPositions() is not supported yet

**Comment by samgermain** [comment]
> I also tried several other exchanges. Is it true, that in all of the following exchanges the function "fetch_positions" ist not available?
> 
> -Bitmart -Bkex -Bitrue -Bigone -Digifinex -Poloniex
> 
> I get the same "error" message on all of them: NotSupported: "exchange" fetchPositions() is not supported yet

The method is only available for exchanges that have `swap`/`future` trading implemented

**Comment by Nitrix321** [comment]
You mean implemented on the exchange or implemented in ccxt?
Future trading is possible on all of them via the normal webside. 
Where can i see which exchanges have implemented futures. Can u please tell me?

**Comment by samgermain** [comment]
> You mean implemented on the exchange or implemented in ccxt?

implemented on ccxt

> Future trading is possible on all of them via the normal webside. 

- On bitmart, there's not much you can do with futures trading via their api
- poloniex futures was a [branch that I started](https://github.com/samgermain/ccxt/tree/poloniexFuturesPaths), but abandoned in favour of working on some other things 
- it is implemented on digifinex

> Where can i see which exchanges have implemented futures. Can u please tell me?

you can check `exchange.has['future']` or `exchange.has['swap']` for perpetual futures

**Comment by Nitrix321** [comment]
Ok thank you very much, I will try it :-). 
Puuh it's quite difficult to find an exchange who offers all the functions I need. I am actually searching an exchange where it is possible to get a moving average over 500. in best case 1000 or more, where contract trading is possible, trigger orders are allowed, and who works correct. The only exchange I found is phemex, but unfortunately there's a bug like mentioned here [https://github.com/ccxt/ccxt/issues/11999](url). Candle delay. So, it is reasonably usable with 1min timeframe, perhaps 3min timeframe. But everything higher not usable because you are always 1 Candle later then real time/live ticker.

**Comment by samgermain** [comment]
> 

binance, okx, and huobi are three of the most complete exchanges in the library
