### ISSUE TITLE
block code bitfinex

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1603]
i have search thru this [method](https://github.com/ccxt/ccxt/search?utf8=%E2%9C%93&q=publicGetBookSymbolPrecision&type=) but there is no document about it.

**Comment by kroitor** [comment]
It's documented in the Manual, here: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods )

**Comment by jjhesk** [comment]
thank you, thats really helpful for studying it.
