### ISSUE TITLE
CCXT for Bybit can not fetch order book.

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#16045]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10 PRO
- Programming Language version: node.js (19.2.0)
- CCXT version: 2.2.92

```
const ccxt = require('ccxt');
console.log(ccxt.version);

if (process.argv.length != 3)
{
console.error('Usage: BTC/USDT');
console.error('Get pair1 order book from exchange');
console.error('Please try again!');
process.exit(1);
}
const [nodejs, script1, pair1] = process.argv;
const pair1OrderBook = async (pair1) => {
let exchange = new ccxt.bybit
({'adjustForTimeDifference': true,
defaultType: 'spot',
'verbose': true });
try
{
await exchange.loadMarkets();
const orderbook1 = await exchange.fetchOrderBook(pair1);
if (typeof orderbook1 !== 'undefined')
{
const json_orderbook = JSON.stringify(orderbook1);
console.log(json_orderbook);
}
else
{
const obj_orderbook0 = ({ 'Symbol': pair1, 'Data': [] });
const json_orderbook0 = JSON.stringify(obj_orderbook0);
console.log(json_orderbook0);
}
}
catch (err) {
console.error(err)
}
};
pair1OrderBook(pair1);

```

```
.........
fetch Request:
 bybit GET https://api.bybit.com/derivatives/v3/public/instruments-info?category=option&limit=1000&cursor=9000%2C10000
RequestHeaders:
 {}
RequestBody:
 undefined

handleRestResponse:
 bybit GET https://api.bybit.com/derivatives/v3/public/instruments-info?category=option&limit=1000&cursor=9000%2C10000 200 OK
ResponseHeaders:
 {
  'Cache-Control': 'max-age=0, no-cache, no-store',
  Connection: 'keep-alive',
  'Content-Length': '205',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Sat, 10 Dec 2022 18:46:12 GMT',
  Expires: 'Sat, 10 Dec 2022 18:46:12 GMT',
  Pragma: 'no-cache',
  Ret_code: '0',
  Server: 'Openresty',
  Timenow: '1670697972655',
  Traceid: '71cfdf0b8398766408808fde0b0dfe0a'
}
ResponseBody:
 {"retCode":0,"retMsg":"success","result":{"resultTotalSize":9122,"cursor":"10000%2C11000","dataList":[],"category":"option","nextPageCursor":"10000%2C11000","list":[]},"retExtInfo":{},"time":1670697972655}

BadSymbol: bybit does not have market symbol BTC/USDT
    at bybit.market (C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\base\Exchange.js:2513:15)
    at bybit.fetchOrderBook (C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\bybit.js:2741:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async pair1OrderBook (C:\ArbitApps\CCXT\CCXTNodeByFunctions\bybit_pair1OrderBook.js:20:20) {
  constructor: [class BadSymbol extends BadRequest]
```
Hello:
I just create an account with Bybit, and got an API key, I did some tests, most of them working. Like: fetchCurrency, loadMarkets.
But when I use the following command to fetch order book for one trading pair: BTC/USDT, I got the following errors (turn off verbose output):
C:\ArbitApps\CCXT\CCXTNodeByFunctions>node bybit_pair1OrderBook.js BTC/USDT
2.2.92
BadSymbol: bybit does not have market symbol BTC/USDT
    at bybit.market (C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\base\Exchange.js:2513:15)
    at bybit.fetchOrderBook (C:\ArbitApps\CCXT\CCXTNodeByFunctions\node_modules\ccxt\js\bybit.js:2741:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async pair1OrderBook (C:\ArbitApps\CCXT\CCXTNodeByFunctions\bybit_pair1OrderBook.js:20:20) {
  constructor: [class BadSymbol extends BadRequest]
}

C:\ArbitApps\CCXT\CCXTNodeByFunctions>

But if I fetch each currency, like: fetch BTC, and fetch USDT, it works.
Please let me know how can I use fetchOrderbook for bybit exchange.
Thanks,

**Comment by carlosmiei** [comment]
Hello @zydjohnHotmail,

By default, bybit loads only swap markets and apparently you're trying to fetch the orderbook for a spot market. If you want to handle spot markets please change the `defaultType` value upon instantiating the exchange.

Example:

```Python
exchange = ccxt.bybit({
   'options': {
       'defaultType':'spot'   
    }
})
```

**Comment by zydjohnHotmail** [comment]
Thanks, it works!
