### ISSUE TITLE
Deribit Websockets 10028 error 'too_many_requests' because of missing authentication in webosckets

### ISSUE THREAD

**Issue by cjelsa** [ccxt/ccxt#16055]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Mac latest
- Programming Language version: Python 3.10.6
- CCXT version: 2.2.91

An update would be to force authentication for Deribit WS

```
async def main():
 
    deribit = ccxt.deribit()
    await deribit.load_markets()
 
    while True:
        try:
            book = await deribit.watch_order_book('BTC/USD:BTC')
            await write_top(book, deribit.iso8601(deribit.milliseconds()))
            await deribit.close()

        except Exception as e:
            print(e)
```

```
client_connection: Connection<ConnectionKey(host='www.deribit.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None)>
Exception in callback FastClient.receive_loop.<locals>.handler() at /Users/XXXX/ccxt/python/ccxt/pro/base/fast_client.py:20
handle: <Handle FastClient.receive_loop.<locals>.handler() at /Users/XXXX/ccxt/python/ccxt/pro/base/fast_client.py:20>
Traceback (most recent call last):
  File "/Users/XXXX/conda-env/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/XXXX/ccxt/python/ccxt/pro/base/fast_client.py", line 25, in handler
    self.handle_message(message)
  File "/Users/XXXX/ccxt/python/ccxt/pro/base/aiohttp_client.py", line 32, in handle_message
    self.handle_text_or_binary_message(message.data)
  File "/Users/XXXX/ccxt/python/ccxt/pro/base/aiohttp_client.py", line 27, in handle_text_or_binary_message
    self.on_message_callback(self, decoded)
  File "/Users/XXXX/ccxt/python/ccxt/pro/deribit.py", line 704, in handle_message
    raise ExchangeError(self.id + ' ' + self.json(error))
ccxt.base.errors.ExchangeError: deribit {"message":"too_many_requests","code":10028}
1006
```

**Comment by cjelsa** [comment]
Just to add some additional info, when subscribing while authenticated this error does not happen

**Comment by pcriadoperez** [comment]
Hi @cjelsa.
I believe this is being cause by the `deribit.close()` and not `watch_order_book`. Have you tried removing `await deribit.close()` or moving it to the catch clause? 
Without it works ok for me.

**Comment by cjelsa** [comment]
Yes! this seems to solve the problem. Where do you suggest I close the connection, after the Exception?

**Comment by pcriadoperez** [comment]
Glad to hear it!
I'd move it outside the while loop. So that you just close the exchange before you exit the script
