### ISSUE TITLE
Can't open new position on Bybit

### ISSUE THREAD

**Issue by Vamaka12** [ccxt/ccxt#16050]
- OS: Windows 10 Pro
- Programming Language version: Python 3.10.4
- CCXT version: 2.2.92

```
import ccxt

bybit = ccxt.bybit({
    'apiKey': 'KEY',
    'secret': 'SECRET_KEY',
    'enableRateLimit': True
})

def set_margin():
    try:
        bybit.set_margin_mode("ISOLATED", trade_symbol, {
            'leverage': 10
        })
    except:
        pass
    try:
        bybit.set_leverage(10, trade_symbol)
    except:
        pass

trade_symbol = 'SOLUSDT'

bybit.load_markets()

set_margin()

order = bybit.create_market_buy_order(trade_symbol, 1)

print(order)
```

```
ccxt.base.errors.BadRequest: bybit {"retCode":10001,"retMsg":"position idx not match position mode","result":{},"retExtInfo":{},"time":1670760752616}
```

I am trying to open new position on deravatives. I tried create_order(), create_limit_buy_order() nothing helped, I think it's because of set_magin() but when I run the code without it nothing changes.

It was working few days ago but I couldn't add take profit and stop loss (I was getting upstream server error), but now I can't even open position.

**Comment by saiooo** [comment]
I am coding with javascript but this worked for me:

const promise = exchange.createOrder(symbol, type, side, amount, undefined)

and call looks like this:

Bybit.placeOrder('BTCUSDT', 'market', 'buy', 0.01);

**Comment by Vamaka12** [comment]
`order = bybit.create_order('SOLUSDT', 'market', 'buy', 1)`

Still same error

**Comment by carlosmiei** [comment]
Hello @Vamaka12,

Recently we upgraded bybit to v3, so some slight adjustments might be required.

`positionIdx` is a required parameter if you're under `one way mode`. 
Can you try to provide it? 
![image](https://user-images.githubusercontent.com/43336371/207024394-088f600e-c2b8-4c36-97ce-496f4b8516dc.png)

**Comment by Vamaka12** [comment]
@carlosmiei Hi, everything works with positionIdx: 1

```
order = bybit.create_order('SOLUSDT', 'market', 'buy', 1, params={
    'positionIdx': 1
})
```


What about Take profit and Stop loss?

```
order = bybit.create_order('SOLUSDT', 'market', 'buy', 1, params={
    'positionIdx': 1,
    'takeProfit': 15
})
```

I am getting error 'ccxt.base.errors.ExchangeError: bybit {"retCode":10016,"retMsg":"upstream server error","result":{},"retExtInfo":{},"time":1670842207428}
'

**Comment by carlosmiei** [comment]
Hello @Vamaka12, hum `stopLoss`and `takeProfit` should work, do you get this error consistently?

**Comment by Vamaka12** [comment]
@carlosmiei Hello, yes I am getting it consistently. I updated ccxt from 2.2.92 to 2.4.9 but I have still the same issue.

Here's the code

```
order = bybit.create_order('SOLUSDT', 'market', 'buy', 1, params={
    'positionIdx': 1,
    'takeProfit': 15
})
```

**Comment by saiooo** [comment]
> @carlosmiei Hello, yes I am getting it consistently. I updated ccxt from 2.2.92 to 2.4.9 but I have still the same issue.
> 
> Here's the code
> 
> ```
> order = bybit.create_order('SOLUSDT', 'market', 'buy', 1, params={
>     'positionIdx': 1,
>     'takeProfit': 15
> })
> ```

Check my last update: https://github.com/ccxt/ccxt/issues/16049

**Comment by Nitrix321** [comment]
I had exactly the same issue, for me it's working again with normal settings and no positionIdx. There where also several other issues on bybit last week. But strangely not always only sometimes. 


bybit = ccxt.bybit({'enableRateLimit': True,
                       'apiKey': config.api_key,
                       'secret': config.api_secret,
                       'options': {'defaultType': 'swap'}
                       })

symbol = 'ETH/USDT:USDT'
pos_size = 0.01

bybit.create_market_buy_order(symbol, pos_size)

**Comment by xmatthias** [comment]
`'positionIdx': 1,` must match the setting of the [position mode](https://bybit-exchange.github.io/docs/derivativesV3/contract/#t-dv_switchpositionmode) of this pair.


Basically, your code then becomes (to be sure of the position mode):

```
bybit.set_position_mode(True, 'SOL/USDT:USDT')
order = bybit.create_order('SOL/USDT:USDT', 'market', 'buy', 1, params={
    'positionIdx': 1,
    'takeProfit': 15
})
```
(use true for hedge mode, false for one-way mode - obviously `positionIdx` must match the setting you made).

You can also omit the symbol - which will change the mode for the whole account (Without open orders/positions).

**Comment by Utayaki** [comment]
> `'positionIdx'` must match the setting of the [position mode](https://bybit-exchange.github.io/docs/derivativesV3/contract/#t-dv_switchpositionmode) of this pair.
> 
> Basically, your code then becomes (to be sure of the position mode):
> 
> ```
> bybit.set_position_mode(True, 'SOL/USDT:USDT')
> order = bybit.create_order('SOL/USDT:USDT', 'market', 'buy', 1, params={
>     'positionIdx': 1,
>     'takeProfit': 15
> })
> ```
> 
> (use true for hedge mode, false for one-way mode - obviously `positionIdx` must match the setting you made).
> 
> You can also omit the symbol - which will change the mode for the whole account (Without open orders/positions).

THANK YOU! You're a savior!!
