### ISSUE TITLE
Checking Orders

### ISSUE THREAD

**Issue by janstrw13** [ccxt/ccxt#16056]
Hello, my question is if there is any possibility to check if my take profit or stop loss of my order got hit. Maybe with a stop loss or take profit id?
Please post the code that I can test it! Thank you so much.

**Comment by 6642248687** [comment]
>

**Comment by 6642248687** [comment]
Y

**Comment by janstrw13** [comment]
Or is there a possibility to check if a order of a specific price is filled?

if order(filledprice=price) is filled
    exchange.createOrder....

if u know something like this please let me know

**Comment by carlosmiei** [comment]
Hello @janstrw13, if you're using WS you can try to watch for it using `watchOrders` otherwise you can periodically poll the exchange using REST requests to check if some order was already filled or not.
