### ISSUE TITLE
CCXT for Bybit - How to create a spot limit order for Long/short using margin?

### ISSUE THREAD

**Issue by Darthlatte** [ccxt/ccxt#16054]
Hi team! 

How can I place long and short orders for the coin pairs on Bybit (spot), which supports using a leverage of 5x using ccxt?

OS: Windows
Programming Language version: Python 3.10
CCXT version: ccxt@2.2.79

I have tried a lot of different configurations and methods, but no luck.

At the moment I'm creating buy and sell orders (not using leverage) by using the code below:

`bybit = ccxt.bybit({
    'apiKey': api_key,
    'secret': api_secret,
    'timeout': 30000,
    'enableRateLimit': True,
    "options": {
        'defaultType': 'spot',  # spot, margin, future, delivery
        'createMarketBuyOrderRequiresPrice': False,
        'adjustForTimeDifference': True,
        'recvWindow': 10000
    }
})`

Buy order:

`bybit.createLimitBuyOrder(asset, amount, limit)`

Sell order:

`bybit.createLimitSellOrder(asset, amount, limit)`

Thanks in advance

**Comment by carlosmiei** [comment]
Hello @Darthlatte,

You just need to borrow funds (using `borrowMargin`) before placing the order, the same way you would place a regular spot order.

**Comment by ttodua** [comment]
you might also check this example (which works for binance atm): https://github.com/ccxt/ccxt/blob/master/examples/js/margin-borrow-buy-sell-repay-example.js
