### ISSUE TITLE
getbtc invalid currencies

### ISSUE THREAD

**Issue by Esc4pism** [ccxt/ccxt#1606]
Exchange: GetBTC
Priority: low

supports 3 markets BTC/EUR, BTC/USD, BTC/RUB as defined in the getbtc.js class.

But somehow all of the markets from its extended class _1btcxe make it into its list as well, which arent supported in getbtc and throw "invalid currency" errors when im trying to fetch tickers.

**Comment by kroitor** [comment]
@Esc4pism will fix it shortly, thx for reporting!
