### ISSUE TITLE
Binance fetchBalance Undefined array key 0

### ISSUE THREAD

**Issue by partosup** [ccxt/ccxt#16079]
- OS: UBUNTU
- Programming Language version: PHP
- CCXT version: 2.2.9

```php
        $exchange_class = "\\ccxt\\bybit";
        $credentials = [
            'apiKey' => 'apikey',
            'secret' => 'secretkey',
        ];
        $exchange = new $exchange_class($credentials);
        $exchange->enableRateLimit = true;
        $exchange->options['defaultType'] = 'spot';
        $bal = $exchange->fetchBalance();
 ```
        
        return Undefined array key 0
        
        
        
![image](https://user-images.githubusercontent.com/14160218/207452218-7f0a4314-c9cf-4a06-a745-4e2e7c741924.png)

**Comment by sc0Vu** [comment]
It seems the response is empty.

**Comment by samgermain** [comment]
@partosup Can you include that part between `/*...*/`

Also, try calling `exchange->load_markets()` before calling `exchange->fetch_balance()`
