### ISSUE TITLE
ExchangeNotAvailable (binance)

### ISSUE THREAD

**Issue by partosup** [ccxt/ccxt#16078]
- OS: Ubuntu
- Programming Language version: php8.1
- CCXT version: 2.2.103

```php
  $credentials = [
         'apiKey' => '*',
         'secret' => '*'
];
$exchange = new \ccxt\binance($credentials);
$exchange->enableRateLimit = true;
$exchange->options['defaultType'] = 'spot';
$bal = $exchange->fetchBalance();
```         
         
Return error ccxt\ExchangeNotAvailable

![image](https://user-images.githubusercontent.com/14160218/207450757-21ccdf4f-ef0e-45d3-b9ef-1ccf36278b5f.png)

**Comment by sc0Vu** [comment]
Hi @partosup 

Have you checked the error code from binance? (you can set `verbose` to see the request / response)

**Comment by samgermain** [comment]
@partosup 

Can you copy and paste you're full error message instead of posting a screenshot please? Can you also include any lines that might be missing from your program?

**Comment by partosup** [comment]
> Hi @partosup
> 
> Have you checked the error code from binance? (you can set `verbose` to see the request / response)

Thanks, the problem is in the geolocation of the VPS. 
Exchange response - "Service unavailable from a restricted location according to 'b. Eligibility' "
