### ISSUE TITLE
New Exchange: bitcoinaverage

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1607]
api doc: https://apiv2.bitcoinaverage.com
url: https://bitcoinaverage.com/
fee: --
volume: --
company info: Blockchain Data LTD 
tnc: https://bitcoinaverage.com/en/terms
based country: USA
whitepaper: --
priority: low
github group: --
note: ranked top : NA
type: centrailzed ex
discussion: --
sign up: --

**Comment by frosty00** [comment]
not an exchange
