### ISSUE TITLE
New Exchange: cryptofacilities

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1608]
api doc: https://www.cryptofacilities.com/resources/hc/en-us/articles/115003084394-REST-API
url: https://www.cryptofacilities.com
volume: --
address: Crypto Facilities Ltd, 25 Copthall Avenue, London EC2R 7BP, United Kingdom
company info: Crypto Facilities Ltd
based country: UK
priority: low
tnc: https://www.cryptofacilities.com/membership-agreement
type: centralised exchange

**Comment by SergeGardien** [comment]
Are there any updates on Crypto Facilities?

**Comment by kroitor** [comment]
@SergeGardien https://github.com/ccxt/ccxt/wiki/FAQ

**Comment by frosty00** [comment]
not an exchange
