### ISSUE TITLE
fetchOHLCV error -> TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by forvest3io** [ccxt/ccxt#16097]
hi
version : "2.4.11"

--------------------

const ccxt = require ('ccxt');

const main = async()=>{

    let exchange = new ccxt.bybit()
    exchange.enableRateLimit = true;
    exchange.timeout = 30000;

    const response = await exchange.fetchOHLCV( 'ADA/USD:ADA' , '1h' , 1640995200000 , 200 );
    console.log(response);

}

main();

-------
Errro -> TypeError: Cannot read properties of undefined (reading 'length')

**Comment by carlosmiei** [comment]
Hello @forvest3io ccxt is not correctly handling this response, but it basically means it was an empty response. That usually indicates you're requesting data too far in time.

**Comment by forvest3io** [comment]
in verson "1.92.32" it is ok.

**Comment by carlosmiei** [comment]
@forvest3io does it return data, or just an empty array?
