### ISSUE TITLE
New Exchange: cryptonit

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1609]
api doc: https://cryptonit.net/documentation/public-api
url: https://www.cryptonit.net
volume: --
address: 7/11 Minerva Road, Park Royal, London NW10 6HJ, United Kingdom
company info: Cryptonit Solutions Ltd. | Registration number in UK Companies House: 08810990
based country: UK
priority: low
tnc: https://www.cryptonit.net/en/terms
type: centralised exchange

**Comment by jjhesk** [comment]
Cryptonit Exchange API specification
================================


Cryptonit API Documentation
---------------------------

https://cryptonit.net/documentation/public-api


Public API

Ticker
------
https://cryptonit.net/apiv2/rest/public/ccorder.json?bid_currency=usd&ask_currency=btc&ticker

Orders
------
https://cryptonit.net/apiv2/rest/public/ccorder.json?bid_currency=BTC&ask_currency=USD&type=placed&limit=1000

Trades
------
https://cryptonit.net/apiv2/rest/public/ccorder.json?bid_currency=BTC&ask_currency=USD&type=filled&limit=1000

**Comment by kroitor** [comment]
The exchange is shutdown on 15 May 2019 - July 2019: https://www.cryptonit.net/en/about
