### ISSUE TITLE
poloniex for future

### ISSUE THREAD

**Issue by kjnh10** [ccxt/ccxt#16099]
In poloniex, it seems functions does not work for futures. 
for example, create_order, fetch_order, and so on.

If so, could you implement?

**Comment by carlosmiei** [comment]
Hello @kjnh10, 
We will try to add it shortly, thanks.

**Comment by samgermain** [comment]
I started a [branch once,](https://github.com/samgermain/ccxt/tree/poloniexFuturesPaths) but abanoned it to work on other things. Some of the work is there though. Poloniex Futures will require a new exchange file, and doesn't use the same apiKeys as poloniex
