### ISSUE TITLE
btcchina Error 503 / unavailable

### ISSUE THREAD

**Issue by Esc4pism** [ccxt/ccxt#1610]
Bitcoin China seems to have closed/shut down. Their apis are also no longer accessible, atleast for me.

https://cms.btcchina.com/notices?lang=zh

This looks to be their new platform (same icon) https://www.btcc.com/ but i could only find docs there for websocket and FIX api's, no REST.

**Comment by kroitor** [comment]
@Esc4pism yes, that was announced a few months ago, however, they seem to be reworking their business now. We are watching them closely. Thx!
