### ISSUE TITLE
Bybit: timestamp field in fetch_ohlcv method is returned as float instead of int

### ISSUE THREAD

**Issue by marcoismobile** [ccxt/ccxt#16107]
After upgrading to one of the more recent CCXT versions, I found that the timestamp field changed from **int** to **float** in the fetch_ohlcv method response on the ByBit exchange.

As it was before (and as mentioned in the documentation) this should be an integer value, instead of the float (which always ends in .0) value.

- OS: Linux
- Programming Language version: python
- CCXT version: 2.4.18

Example code snipped to reproduce:
```
exchange = ccxt.bybit({
            'options': {
                'defaultType': 'swap',
                'defaultSubType': 'linear',
                'defaultSettle': 'USDT',
            }
        })

ohlcv = exchange.fetch_ohlcv('BTC/USDT:USDT', '1h')
print(ohlcv)
```

Output:
```
[[1671166800000.0, 17376.5, 17394.0, 17359.5, 17393.5, 1598.719], [1671170400000.0, 17393.5, 17413.5, 17370.0, 17412.0, 1251.156], [1671174000000.0, 17412.0, 17530.0, 17411.5, 17496.5, 9542.803], [1671177600000.0, 17496.5, 17508.5, 17171.0, 17217.5, 18271.581], [1671181200000.0, 17217.5, 17218.0, 16950.0, 17001.0, 29191.407]]
```

**Comment by carlosmiei** [comment]
Hello @marcoismobile,
Thanks for reporting it, will be fixed very soon!
