### ISSUE TITLE
New Exchange: koinim

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1611]
api doc: --
url: https://koinim.com/
volume: --
address: KOİNİM BİLİŞİM A.Ş. Yapı Kredi Plaza C Blok No:40-41 Beşiktaş, İstanbul Ticaret Sicil No: 861986 Vergi Numarası: 5740552286 Vergi Dairesi: Beşiktaş
company info: KOİNİM BİLİŞİM A.Ş.
based country: VE
priority: low
tnc: --
type: centralised exchange

**Comment by jjhesk** [comment]
The documentation for Koinim exchange platform
================================

Public API


Documentation
-------------
No documentation


Ticker
------
https://www.koinim.com/ticker

**Comment by frosty00** [comment]
no volume
