### ISSUE TITLE
coinbase createOrder() is not supported yet

### ISSUE THREAD

**Issue by brootas** [ccxt/ccxt#16120]
Hello!

Coinbase automatically moved me from CB Pro to regular Coinbase since they are phasing out Pro. 

I'm trying to set up my app to work with Coinbase, but it is giving me an error message that 'coinbase createOrder() is not supported yet'.

My understanding is that historically Coinbase Pro API allowed orders, though regular Coinbase did not. Advanced Trading on Coinbase is now meant to take its place, and their Advanced Trading API documentation makes it appear that it is now possible.
https://docs.cloud.coinbase.com/advanced-trade-api/reference/retailbrokerageapi_postorder

I just updated ccxt today.

Is this:
• a Coinbase issue?
• a PEBKAC issue?
• or is this something that needs to be updated in ccxt's coding to work with the changes being made by Coinbase?

```
# python

import ccxt
import config

# basic info
coin = 'BTC'
tradepair = 'BTC/USD'
exchange_cb = ccxt.coinbase({
    'apiKey': config.CB_API_KEY,
    'secret': config.CB_API_SECRET,
})

# get balances
acct_balances = exchange_cb.fetch_balance()
coin_bal = acct_balances[coin]['total']     # get current acct bal of traded coin.
usd_bal = acct_balances['USD']['total']     # get current acct bal of 'USD'.

# buy / sell
tx_side = 'BUY'
coin_price = float(exchange_cb.fetch_ticker(tradepair)['close'])
trade_quantity = format((usd_bal / coin_price), (".%sf" % 8))
order_statement = exchange_cb.create_market_order(symbol=tradepair, side=tx_side, amount=trade_quantity)
print(order_statement)
```

```
Traceback (most recent call last):
  File "/Users/seanriker/pyapps/Waverunner/shortorder.py", line 23, in <module>
    order_statement = exchange_cb.create_market_order(symbol=tradepair, side=tx_side, amount=trade_quantity)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 3207, in create_market_order
    return self.create_order(symbol, 'market', side, amount, price, params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 3119, in create_order
    raise NotSupported(self.id + ' createOrder() is not supported yet')
ccxt.base.errors.NotSupported: coinbase createOrder() is not supported yet
```

**Comment by sc0Vu** [comment]
Hi @brootas 

Looks like they had migrated coinbase pro (https://www.coinbase.com/blog/hello-advanced-trade-goodbye-coinbase-pro), and the api seems different (can't use coinbase pro). We'll update asap.

**Comment by MatteWannabeCoder** [comment]
Any news?

**Comment by diogopms** [comment]
Hi, thanks for adding this issue. I'm still interested in this feature 🙏🏻

**Comment by frosty00** [comment]
#16322 it's in progress
