### ISSUE TITLE
Bybit fetch_tickers function gives wrong symbol parsing

### ISSUE THREAD

**Issue by zwang613** [ccxt/ccxt#16121]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

Bybit `fetch_tickers" function give wrong symbol parsing, it parses some spot to contract like symbols

OS: Windows 10
Programming Language version: python
CCXT version: 2.4.26

Example code snipped to reproduce:

```
from ccxt import bybit
ex = bybit()
ex.fetch_spot_tickers(['UNIUSDT'])
```

Output:
```
{'UNI/USDT:USDT': {'symbol': 'UNI/USDT:USDT',
  'timestamp': 1671344640000,
  'datetime': '2022-12-18T06:24:00.000Z',
  'high': 5.44,
  'low': 5.31,
  'bid': 5.36,
  'bidVolume': None,
  'ask': 5.37,
  'askVolume': None,
  'vwap': 5.376700809564523,
  'open': 5.33,
  'close': 5.36,
  'last': 5.36,
  'previousClose': None,
  'change': 0.03,
  'percentage': 0.5628517823639774,
  'average': 5.345,
  'baseVolume': 75835.586,
  'quoteVolume': 407745.25664,
  'info': {'t': '1671344640000',
   's': 'UNIUSDT',
   'bp': '5.36',
   'ap': '5.37',
   'lp': '5.36',
   'o': '5.33',
   'h': '5.44',
   'l': '5.31',
   'v': '75835.586',
   'qv': '407745.25664'}}}
```

**Comment by carlosmiei** [comment]
Hello @zwang613,

Bybit has clashing ids between spot and swap markets (they're the same), and by default, it loads `swap` markets only. That's why you are wrongfully getting a swap ticker when calling `fetch_spot_ticker`. 

If you want to handle spot markets you should change the default type upon instantiating the exchange.

Example: 
```Python
exchange = ccxt.bybit({
    'options': {
        'defaultType': 'spot'
    }
})
```
