### ISSUE TITLE
Kucoin - Is it still working with CCXT ? A Previous issue was closed even though it was not resolved.

### ISSUE THREAD

**Issue by bluetyphoon77** [ccxt/ccxt#16127]
Hi, 
Since awhile now, we try to get an answer from devs. What is happening ? Why is Kucoin not working anymore with CCXT ?
Thanks a lot guyz !
Here is the closed post: https://github.com/ccxt/ccxt/issues/15952

@carlosmiei @2dOverlord @kroitor

**Comment by bluetyphoon77** [comment]
Hey @carlosmiei 
Thanks for your answer. My dev is busy for the moment I'm trying to have his answer. But could you check what he already said in the previous issue ?

**Comment by 2dOverlord** [comment]
@carlosmiei Here are the logs:
![image](https://user-images.githubusercontent.com/74546413/209010510-e963d520-5f68-410a-97b7-25843b1580d6.png)

**Comment by 2dOverlord** [comment]
![image](https://user-images.githubusercontent.com/74546413/209010602-a8d784c5-f9e8-40cd-aba4-ccccf78b8dd9.png)

**Comment by 2dOverlord** [comment]
the python version is 3.11
the ccxt version is 2.4.47

**Comment by bluetyphoon77** [comment]
Thanks a lot @2dOverlord. Hope you can help us @carlosmiei 
Cheeers
