### ISSUE TITLE
bitmarket certificate errors

### ISSUE THREAD

**Issue by Esc4pism** [ccxt/ccxt#1612]
Exchange: BitMarket

Error: bitmarket GET https://www.bitmarket.net/json/BTCEUR/ticker.json system request to https://www.bitmarket.net/json/BTCEUR/ticker.json failed, reason: unable to verify the first certificate

getting the same url in a browser works, but not when called with fetchTicker()

**Comment by kroitor** [comment]
Can you please follow these recommendations when submitting new issues: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?
It would be easier for me to fix it then. Thx!

**Comment by Esc4pism** [comment]
heres a short sample code:
´´´let bitmarket = new ccxt.bitmarket({verbose: true});
bitmarket.loadMarkets().then(result => {
    bitmarket.fetchTicker("LTC/PLN").then(value => {
        // do something with the data ...
    },function(error){
        console.log(error);
    });
});´´´

After some googling and testing to call the same api directly through ajax which returned the same error, I get that this api requires a valid ssl certificate of my server even for public calls, which i dont have currently as im testing and developing locally.

I know its unsafe, but is there any option to disable ssl verification for just local testing purposes? like adding "rejectUnauthorized": false in the GET parameters?

**Comment by frosty00** [comment]
It's probably your version of openssl, try updating that.

**Comment by kroitor** [comment]
@Esc4pism what's your version of the openssl? Have you tried updating it like @frosty00 said?

**Comment by Esc4pism** [comment]
I needed to have this explained by a coworker as im still quite new to server-sided development in general. Anyway it seems this issue has resolved itself for me now, since fetching tickers from bitmarket works now without having changed anything about my requests. I can only assume that they sent me weird or false errors yesterday, maybe i was blocked temporarily.

I honestly dont know if or what version of openssl is running on my server, as its a plain node-js server (node 9.4.0). I have a http webservice (rest api) and a websocket server started on it, but they are unrelated to ccxt or any other api calls.

**Comment by kroitor** [comment]
Ok, I would close this issue for now if you don't mind, thanks for reporting back! Feel free to reopen it if needed, or just ask questions, if you have any difficulties with it further.
