### ISSUE TITLE
New Exchange: thodex.com (former koineks.com) 

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1613]
api doc: https://koineks.com/info/api
url: https://koineks.com
volume: --
address: KOİNEKS TEKNOLOJİ A.Ş. | Merkez Mah. Akar Cad. iTower Bomonti No:3 Şişli/İstanbul
based country: VE
priority: low
tnc: --
type: centralised exchange

**Comment by An-Net** [comment]
This exchange changed name and address to https://www.thodex.com/tr (THODEX):

- https://koineks.com/

![Снимок экрана 2020-03-27 в 19 35 53](https://user-images.githubusercontent.com/51840849/77778578-44b46380-7062-11ea-9ee2-df1bdfedade8.png)

**Comment by An-Net** [comment]
Shutdown since April 2021.

- https://www.reuters.com/technology/turkey-jails-6-crypto-probe-including-thodex-ceos-siblings-courthouse-2021-04-30/

- ![Снимок экрана 2021-05-16 в 19 51 35](https://user-images.githubusercontent.com/51840849/118406710-ab8d4580-b685-11eb-9902-388de6d14d81.jpg)
