### ISSUE TITLE
New Exchange: openexchangerates

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1615]
api doc: https://docs.openexchangerates.org/
url: https://openexchangerates.org/
based country: USA
whitepaper: --
priority: low
github group: --
note: ranked top : NA
type: index only

**Comment by jjhesk** [comment]
Open Exchange Rates API specification
================================

Public API

https://openexchangerates.org/documentation

Latest
------
http://openexchangerates.org/api/latest.json?app_id=ab32c922bca749ec9345b4717914ee1f

Currencies
------
http://openexchangerates.org/api/currencies.json?app_id=ab32c922bca749ec9345b4717914ee1f

Data update rate!
------
According to https://openexchangerates.org/about, the rates are updated once an hour. Therefore, to limit APIs calls, the rates are cached and refreshed once per hour.

**Comment by frosty00** [comment]
not an exchange
