### ISSUE TITLE
OKX fetch positions always shows contract size 10 and side short  if NOT in position

### ISSUE THREAD

**Issue by Nitrix321** [ccxt/ccxt#16166]
Hello,

on OKX I have the following problem. If I fetch position it always displays a contract size 10 and side short if not in position.
If IN position side changes to the correct direction but contract size is still 10. Always 10. No matter what position size I choose.

- OS: Win10
- Programming Language version:  Python Spyder 3.9
- CCXT version: ccxt-2.4.47

```
okx = ccxt.okex5({'enableRateLimit': True,
                       'apiKey': okxconfig.api_key,
                       'secret': okxconfig.api_secret,
                       'password' : '*********',})

symbol = 'ETH/USD:ETH'

params={"type":"swap","code":"ETH"}
    
okx_pos = okx.fetch_positions([symbol], params=params)
print(okx_pos)
```

```
[{'info': {'adl': '', 'availPos': '', 'avgPx': '', 'baseBal': '', 'baseBorrowed': '', 'baseInterest': '', 'bizRefId': '', 'bizRefType': '', 'cTime': '1671649458108', 'ccy': 'ETH', 'closeOrderAlgo': [], 'deltaBS': '', 'deltaPA': '', 'gammaBS': '', 'gammaPA': '', 'imr': '', 'instId': 'ETH-USD-SWAP', 'instType': 'SWAP', 'interest': '', 'last': '', 'lever': '', 'liab': '', 'liabCcy': '', 'liqPx': '', 'margin': '', 'markPx': '', 'mgnMode': 'cross', 'mgnRatio': '', 'mmr': '0', 'notionalUsd': '', 'optVal': '', 'pendingCloseOrdLiabVal': '', 'pos': '0', 'posCcy': '', 'posId': '503988418058293251', 'posSide': 'net', 'quoteBal': '', 'quoteBorrowed': '', 'quoteInterest': '', 'spotInUseAmt': '', 'spotInUseCcy': '', 'thetaBS': '', 'thetaPA': '', 'tradeId': '204371917', 'uTime': '1671649587523', 'upl': '', 'uplRatio': '', 'usdPx': '', 'vegaBS': '', 'vegaPA': ''}, 'id': None, 'symbol': 'ETH/USD:ETH', 'notional': None, 'marginMode': 'cross', 'liquidationPrice': None, 'entryPrice': None, 'unrealizedPnl': None, 'percentage': None, 'contracts': 0.0, 'contractSize': 10.0, 'markPrice': None, 'side': 'short', 'hedged': False, 'timestamp': 1671649587523, 'datetime': '2022-12-21T19:06:27.523Z', 'maintenanceMargin': 0.0, 'maintenanceMarginPercentage': 0.0, 'collateral': None, 'initialMargin': None, 'initialMarginPercentage': None, 'leverage': None, 'marginRatio': None}]


![OKX](https://user-images.githubusercontent.com/114005997/208985007-cf768d76-7c4a-49a5-a761-d21bb840875e.PNG)

```

**Comment by sc0Vu** [comment]
Hi @Nitrix321 

The contractSize means the size of one contract in quote units. It's from exchange market.

**Comment by samgermain** [comment]
The contract size refers to the amount of the underlying asset that the contract is based on, so it should stay constant. 

Examples

- In a linear market, like `ADA/USDT:USDT`, a `contractSize` of 10 means that when you create an order for 1 contract in the `ADA/USDT:USDT` market, this contract is equal to 10 ADA

- In coin-margined markets, `ETH/USD:ETH`, a `contractSize` of 10 means that when you create an order for 1 contract in the `ETH/USD:ETH` market, this contract is equal to 10 USD

For this reason, the `contractSize` shouldn't change

**Comment by Nitrix321** [comment]
Hi @all ah ok, I understand. Sorry. My bad! But side: 'short' if not in position should not be ok?

**Comment by ttodua** [comment]
> Hi @ALL ah ok, I understand. Sorry. My bad! But side: 'short' if not in position should not be ok?

no, side:short seems bug. @samgermain

**Comment by samgermain** [comment]
> > Hi @ALL ah ok, I understand. Sorry. My bad! But side: 'short' if not in position should not be ok?
> 
> no, side:short seems bug. @samgermain I see you have assigned this issue. lmk if you dont have time and I can re-assign

if you could take a look at this that would be good, my phone was stolen recently and I lost access to a few of my accounts because of google authenticator, OKX being one of them

**Comment by ttodua** [comment]
@Nitrix321 I've submited a fix, will be merged soon.
