### ISSUE TITLE
Bybit derivatives instruments-info enpoint changes

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#16163]
Hi,
we've received from Bybit message that there will be some changes made for derivatives endpoint.

Here is the full message:

> Please note that, there will be changes in this endpoint: /derivatives/v3/public/instruments-info
> We will delete “dataList”, “cursor” and “resultTotalSize” fields in the final version which will be released on testnet on 20/Dec and on mainnet on 22/Dec (02-03 AM UTC)
> Please refer to the examples:
> https://docs.google.com/document/d/1GzFIoZycKL5tOtLOuK1HkUAnIR-d62Ewz3uiNv2Otbs

**Comment by carlosmiei** [comment]
Hello @sc0Vu,
Thanks a lot for letting us know
