### ISSUE TITLE
New Exchange: truefx

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1616]
api doc: https://www.truefx.com/dev/data/TrueFX_MarketDataWebAPI_DeveloperGuide.pdf
url: https://www.truefx.com/
based country: USA
whitepaper: --
priority: low
github group: --
note: ranked top : NA
type: index only

**Comment by jjhesk** [comment]
TrueFX API specification
========================

https://www.truefx.com/dev/data/TrueFX_MarketDataWebAPI_DeveloperGuide.pdf

**Comment by frosty00** [comment]
not an exchange
