### ISSUE TITLE
New Exchange: vircurex

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1617]
api doc: https://vircurex.com/welcome/api?locale=en
url: https://vircurex.com/
fee: --
volume: --
address: --
company info: --
tnc: --
Registration: --
based country: USA
whitepaper: --
priority: low
github group: --
note: ranked top : NA
type: centrailzed exchange

**Comment by An-Net** [comment]
Shutdown:

- https://www.coindesk.com/former-customers-sue-vircurex-exchange-over-frozen-crypto-funds

- https://bitcointalk.org/index.php?topic=2947211.0
