### ISSUE TITLE
Alpaca exchange has['fetchOHLCV'] == false but timeframes not empty

### ISSUE THREAD

**Issue by dawadam** [ccxt/ccxt#16170]
Hi, sorry, i'm not respect the model of message, please forgive me.
In documentation, it is noted that _exchange.timeframes_ is empty if the _exchange.has['fetchOHLCV'] !== true_

Alpaca exchange has _exchange.has['fetchOHLCV']_ == false but _exchange.timeframes_ is :

```
{
  '1m': '1min',
  '3m': '3min',
  '5m': '5min',
  '15m': '15min',
  '30m': '30min',
  '1h': '1H',
  '2h': '2H',
  '4h': '4H',
  '6h': '6H',
  '8h': '8H',
  '12h': '12H',
  '1d': '1D',
  '3d': '3D',
  '1w': '1W',
  '1M': '1M'
}
```

**Comment by carlosmiei** [comment]
Hello @dawadam,
Thanks for reporting it, the issue here `fetchOHLCV = false`, because alpaca has `fetchOHLCV` implemented, so it should be true.

Going to fix it asap!
