### ISSUE TITLE
New Exchange: tauruscoin

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1618]
api doc: https://github.com/timmolter/XChange/tree/develop/xchange-taurus/src/main/java/org/knowm/xchange/taurus
url: https://www.tauruscoin.com/
fee: --
volume: --
address: --
company info: --
tnc: --
Registration: --
based country: USA
whitepaper: https://tauruscoin.com/Taurus%20White%20Paper.pdf
priority: low
github group: --
note: ranked top : NA
type: centrailzed exchange

**Comment by An-Net** [comment]
The website doesn't work anymore.
