### ISSUE TITLE
Bybit watch_order_book does not continuously update values

### ISSUE THREAD

**Issue by nickglt22** [ccxt/ccxt#16187]
- OS: macOS Mojave 10.14.4
- Programming Language version: Python 3.10.5
- CCXT version: 2.4.55

```
import ccxt.pro as ccxtpro
from asyncio import run


async def main():
    exchange = ccxtpro.bybit({
        'options': {
            'defaultType': 'swap',
        },
    })
    symbol = 'BTC/USDT:USDT'
    while True:
        orderbook = await exchange.watch_order_book(symbol)
        print(orderbook['bids'][0], orderbook['asks'][0])
    await exchange.close()
      #await exchange.close() <-- when indented, the orderbook values update properly


run(main())
```

Hello, while accessing the Bybit exchange specifically, watch_order_book does not continuously update the orderbook values as it does for other exchanges. I've done a bit of testing so far and noticed a few things. For one, the code above does return the most recent bid and ask entries correctly, it just does not update from there (continues to print the same initial values repeatedly). Secondly, I copied this code directly from an examples folder and noticed that by default, await exchange.close() is not accessed. When I indented that line specifically so that it could be accessed (see commented out code above), I noticed the orderbook values did update correctly, but slowly. I tested multiple symbols on Binance and regardless of whether the await exchange.close() line was indented or not, the values would update continuously. I've also experimented with watch_trades and found that it works properly, so I believe this to be an issue specifically with watch_order_book functionality.

Any help on this would be appreciated, and if I'm misunderstanding something please correct me as I'm attempting to familiarize myself with this library.

Thanks

EDIT: I just ran another test with the 'defaultType': 'swap' switched to 'spot' to see if the symbol 'BTC/USDT' on the Bybit spot market works properly and found that it does. Not sure what to make of that, but perhaps it is useful information.

**Comment by frosty00** [comment]
@nickglt22 thanks for finding this bug, i've fixed it in the latest version of ccxt
