### ISSUE TITLE
CCXT Ascendex Stopped Working (fetch_markets())

### ISSUE THREAD

**Issue by SpenTappy** [ccxt/ccxt#16193]
Hi all.

Have been using CCXT for Ascendex successfully for months.  Recently it stopped working.
It's failing in 'load_markets'.  Base currency & quote currency for some trading pair I don't even care about are both Null, this leads to a Type error during concatenation.    I would guess some bad/null data coming from the exchange, or that Null's are not being filtered/handled properly in CCXT Ascendex.

- OS:  AWS EC2 (Windows)
- Programming Language version:  Python 3.9 ( 3.9.5 I think)
- CCXT version:  latest, 2.2.89

YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS

ascendex.py, line 573, 'fetch_markets()'

ERROR LINE>>>symbol = base + '/' + quote 
 
Fails with Type error, because base & quote are both = None.
The symbol is XMR5S/USDT, which I am not even interested in.

----
The calling code is standard set up:
```
self.exchange_class = getattr(mod, exchange_id)  
self.ccxt = self.exchange_class({     'apiKey': config['apiKey'],     'secret': config['secret'],     'uid': config['uid'],     'password': config['password'],     'options': {         'defaultType': 'spot',     },     'enableRateLimit': True, })  
self.ccxt.set_sandbox_mode( config['is_sandbox'] ) 
 self.ccxt.load_markets()

```

YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```
Not very useful is it doesn't cast light on WHY they are None value.
"unsupported operand type(s) for +: 'NoneType' and 'str'"
```

Please advise, thank you

**Comment by carlosmiei** [comment]
Hello @SpenTappy,
Yes, we detected this issue recently, but it should already be fixed. Can you try updating to the latest version?

Thanks!

**Comment by SpenTappy** [comment]
Thanks so much for quick response.  Turns out my 'latest' version wasn't as latest as I thought it was..
Confirmed this is running well in `ccxt     2.4.55`
Happy holidays.
