### ISSUE TITLE
New Exchange: bitkonan

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1619]
api doc: https://bitkonan.com/info/api
url: https://bitkonan.com
fee: https://bitkonan.com/info/fees
volume: --
address: Put Plokita 87, Split, Croatia
company info: Digital Assets d.o.o.
tnc: https://bitkonan.com/info/terms-of-use
Registration: --
based country: Croatia
whitepaper: --
priority: low
github group: --
note: ranked top : NA
type: centrailzed exchange

**Comment by An-Net** [comment]
The exchange has no trading volume
- https://www.coingecko.com/en/exchanges/bitkonan
- https://coinpaprika.com/birzhi/bitkonan/
