### ISSUE TITLE
Is there any ETA for websockets support?

### ISSUE THREAD

**Issue by hexdump2002** [ccxt/ccxt#1620]
Hi,

I would like to apologize if this is not the right way to answer this kind of questions, but didn't see any other way to get in touch with you.

Just wanted to know if there's any ETA for WebSupport in this awesome lib. Mainly for graph drawing and order book updating.

Thanks a lot in advance, you're doing a magnificient work!
Cheers.

**Comment by kroitor** [comment]
@hexdump2002 it's all here: #56 

I suggest to move this discussion to that post. Closing this for now as a duplicate, if you don't mind. Thx!
