### ISSUE TITLE
No ccxt/pro/hitbtc3 in php library

### ISSUE THREAD

**Issue by escoman** [ccxt/ccxt#16201]
- Programming Language version: PHP 8.1
- CCXT version: 2.4.55

There are no ccxt/pro/hitbtc3 implementation in last version of CCXT.
But there are hitbtc3 in the Exchanges support list of CCXT PRO Manual (https://docs.ccxt.com/en/latest/ccxt.pro.manual.html).
Why?

**Comment by carlosmiei** [comment]
Hello @escoman 
Currently, there's only `hitbtc` on the `pro` side, so yeah that's a bug. We will remove it, thanks for letting us know.
