### ISSUE TITLE
Available start date for querying a symbol

### ISSUE THREAD

**Issue by mmehrle** [ccxt/ccxt#1621]
One issue I keep running into when pulling data is the start date, for example with 'cex' (one of the better data providers) but also with others what I get is often something like this:

Requesting historical data from cex starting at 2016-01-11 00:00.
******* Next slice starting at: 2016-01-11 00:00:00
Requesting DASH/USD 1m data starting at 2016-01-11 00:00:00...
('Got an error', 'ExchangeError', ('cex returned null',), '.')
Unable to retrieve 1m data...

So here I was trying to pull DASH/USD data starting in 1/1/2016 but obviously cex doesn't have that much data and throws back an error. What we need is a different type of response, e.g. the script should return the earliest start date which I then can use to adjust my request window. Hope this makes sense. 

If this functionality already exists please point me in the right direction, otherwise it's something I would very much enjoy seeing. Right now it's a little bit of a Roulette game as I never know from when a particular symbol is available.

Thanks in advance.

Michael

**Comment by kroitor** [comment]
Hi, Michael!

If you could post your **verbose output** as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue we would be able to add that quickly (where available from the exchange). We will not hardcode those dates if the exchanges themselves don't provide that. Hope it answers your request.

**Comment by mmehrle** [comment]
Hi Kroitor - once again thanks for the quick response. Here you go:

`CCXT version: 1.10.621
SSL versionOpenSSL 1.0.2l  25 May 2017
market id: cex
('GET', 'https://cex.io/api/currency_limits/', '\nRequest:', {'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'python-requests/2.14.2'}, None)
('GET', 'https://cex.io/api/currency_limits/', '\nResponse:', '{\'Expect-CT\': \'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"\', \'CF-RAY\': \'3e543bd168ed2f65-MAD\', \'Content-Encoding\': \'gzip\', \'Transfer-Encoding\': \'chunked\', \'Set-Cookie\': \'__cfduid=dddd40dabe3d97e12dd14af6ca46f269f1517313236; expires=Wed, 30-Jan-19 11:53:56 GMT; path=/; domain=.cex.io; HttpOnly\', \'Vary\': \'Accept-Encoding\', \'Server\': \'cloudflare\', \'Connection\': \'keep-alive\', \'Date\': \'Tue, 30 Jan 2018 11:53:56 GMT\', \'X-Frame-Options\': \'DENY\', \'Content-Type\': \'text/json\', \'Access-Control-Allow-Origin\': \'*\'}', u'{"e":"currency_limits","ok":"ok","data":{"pairs":[{"symbol1":"BTC","symbol2":"USD","minLotSize":0.002,"minLotSizeS2":20,"maxLotSize":30,"minPrice":"1500","maxPrice":"35000"},{"symbol1":"ETH","symbol2":"USD","minLotSize":0.05,"minLotSizeS2":20,"maxLotSize":1000,"minPrice":"70","maxPrice":"4096"},{"symbol1":"BCH","symbol2":"USD","minLotSize":0.02,"minLotSizeS2":20,"maxLotSize":30,"minPrice":"150","maxPrice":"8192"},{"symbol1":"BTG","symbol2":"USD","minLotSize":0.07,"minLotSizeS2":20,"maxLotSize":null,"minPrice":"50","maxPrice":"2048"},{"symbol1":"DASH","symbol2":"USD","minLotSize":0.03,"minLotSizeS2":20,"maxLotSize":null,"minPrice":"100","maxPrice":"4096"},{"symbol1":"XRP","symbol2":"USD","minLotSize":40,"minLotSizeS2":10,"maxLotSize":null,"minPrice":"0.05","maxPrice":"50"},{"symbol1":"ZEC","symbol2":"USD","minLotSize":0.07,"minLotSizeS2":20,"maxLotSize":null,"minPrice":"50","maxPrice":"4096"},{"symbol1":"BTC","symbol2":"EUR","minLotSize":0.002,"minLotSizeS2":20,"maxLotSize":30,"minPrice":"1500","maxPrice":"35000"},{"symbol1":"ETH","symbol2":"EUR","minLotSize":0.05,"minLotSizeS2":20,"maxLotSize":null,"minPrice":"70","maxPrice":"4096"},{"symbol1":"BCH","symbol2":"EUR","minLotSize":0.02,"minLotSizeS2":20,"maxLotSize":null,"minPrice":"150","maxPrice":"8192"},{"symbol1":"BTG","symbol2":"EUR","minLotSize":0.07,"minLotSizeS2":20,"maxLotSize":null,"minPrice":"50","maxPrice":"2048"},{"symbol1":"DASH","symbol2":"EUR","minLotSize":0.03,"minLotSizeS2":20,"maxLotSize":null,"minPrice":"100","maxPrice":"4096"},{"symbol1":"XRP","symbol2":"EUR","minLotSize":40,"minLotSizeS2":10,"maxLotSize":null,"minPrice":"0.05","maxPrice":"50"},{"symbol1":"ZEC","symbol2":"EUR","minLotSize":0.07,"minLotSizeS2":20,"maxLotSize":null,"minPrice":"50","maxPrice":"4096"},{"symbol1":"BTC","symbol2":"GBP","minLotSize":0.002,"minLotSizeS2":20,"maxLotSize":null,"minPrice":"1300","maxPrice":"30000"},{"symbol1":"ETH","symbol2":"GBP","minLotSize":0.05,"minLotSizeS2":20,"maxLotSize":null,"minPrice":"60","maxPrice":"5128"},{"symbol1":"BCH","symbol2":"GBP","minLotSize":0.02,"minLotSizeS2":20,"maxLotSize":null,"minPrice":"150","maxPrice":"8192"},{"symbol1":"DASH","symbol2":"GBP","minLotSize":0.03,"minLotSizeS2":20,"maxLotSize":null,"minPrice":"100","maxPrice":"4096"},{"symbol1":"ZEC","symbol2":"GBP","minLotSize":0.07,"minLotSizeS2":20,"maxLotSize":null,"minPrice":"40","maxPrice":"4096"},{"symbol1":"BTC","symbol2":"RUB","minLotSize":0.001,"minLotSizeS2":1000,"maxLotSize":null,"minPrice":"10000","maxPrice":"2000000"},{"symbol1":"ETH","symbol2":"BTC","minLotSize":0.025,"minLotSizeS2":0.001,"maxLotSize":1000,"minPrice":"0.025","maxPrice":"2"},{"symbol1":"BCH","symbol2":"BTC","minLotSize":0.007,"minLotSizeS2":0.001,"maxLotSize":30,"minPrice":"0.005","maxPrice":"2"},{"symbol1":"BTG","symbol2":"BTC","minLotSize":0.04,"minLotSizeS2":0.001,"maxLotSize":null,"minPrice":"0.005","maxPrice":"2"},{"symbol1":"DASH","symbol2":"BTC","minLotSize":0.015,"minLotSizeS2":0.001,"maxLotSize":null,"minPrice":"0.005","maxPrice":"2"},{"symbol1":"XRP","symbol2":"BTC","minLotSize":40,"minLotSizeS2":0.001,"maxLotSize":null,"minPrice":"0.000003","maxPrice":"0.001"},{"symbol1":"ZEC","symbol2":"BTC","minLotSize":0.03,"minLotSizeS2":0.001,"maxLotSize":null,"minPrice":"0.005","maxPrice":"2"},{"symbol1":"GHS","symbol2":"BTC","minLotSize":100,"minLotSizeS2":0.00001,"maxLotSize":null,"minPrice":"0.000001","maxPrice":"0.01"}]}}')
`

**Comment by kroitor** [comment]
@mmehrle thanks, but now there's no error in your output %) Basically, we need to see their response that generates the error on your side in order to workaround it. So, we need not just regular output, but their response in case of the error, and that should show up on your verbose output when the you trigger the error. That is what would be really helpful. Thx again!
