### ISSUE TITLE
btcex add swap support

### ISSUE THREAD

**Issue by frosty00** [ccxt/ccxt#16222]
- [x] fetchLeverageTiers #16585
- [x] setLeverage #16659
- [x] setMarginMode #16660
- [x] transfer #16664
- [x] fetchFundingRate #16678
- [x] fetchFundingRates #16678
- [x] fetchOpenInterest #16690
- [x] createOrder #16657
- [x] fetchOrder #16658
- [x] fetchPosition
- [x] fetchPositions
- [x] fetchClosedOrders
- [x] fetchOpenOrders
- [x] cancelOrder
- [x] cancelAllOrders
- [x] ~~fetchFundingHistory~~
- [x] ~~fetchFundingRateHistory~~
- [x] ~~fetchMarkOHLCV~~
- [x] ~~fetchIndexOHLCV~~
- [x] ~~fetchPremiumIndexOHLCV~~
- [x] ~~setPositionMode --createOrder Parameter~~

**Comment by Dan-krm** [comment]
Completed!
