### ISSUE TITLE
binance can't fetch all fiat deposits

### ISSUE THREAD

**Issue by uiii** [ccxt/ccxt#16224]
- Programming Language version: js
- CCXT version: 2.4.64

`fetchDeposits` in `binance` exchange is not able to get all fiat deposits. If I do not specify the `code` parameter all crypto deposits are returned. To fetch fiat deposits I have to iterate over all fiat currencies. Is this a bug or intended behavior? The Binance API is capable of returning all fiat deposits.

**Comment by carlosmiei** [comment]
Hello @uiii, it's "intended behavior", but I agree that you should be able to fetch all fiat deposits without specifying the currency if the exchange allows it. I will take a look.

**Comment by uiii** [comment]
thanks @carlosmiei, out of curiosity, why is it intended behavior? if the `fetchDeposits` function is able to fetch both types of deposits (fiat and crypto) why it can't fetch all of them together? I see it could be problematic bacause of the sorting, but is it quite confusing to have one function which behave very differently depending on the argument? I would rather see `fetchFiatDeposits` and `fetchCryptoDeposits`, or at least have it properly documented somewhere.

**Comment by carlosmiei** [comment]
> thanks @carlosmiei, out of curiosity, why is it intended behavior? If the `fetchDeposits` function is able to fetch both types of deposits (fiat and crypto) why it can't fetch all of them together? I see it could be problematic bacause of the sorting, but is it quite confusing to have one function which behave very differently depending on the argument. I would rather see `fetchFiatDeposits` and `fetchCryptoDeposits`, or at least have it properly documented somewhere.

@uiii The main reason is that fiat and crypto transactions require different endpoints and ccxt has this rule: every unified method should only make 1 HTTP request (with a few exceptions like fetchMarkets) so users can easily manage things like RateLimits on their end if they want to.

**Comment by uiii** [comment]
ok, understand, thanks
