### ISSUE TITLE
Waves.Exchange fetch_tickers() only fetches first 100 tickers

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#16229]
- OS: Linux Mint
- Programming Language version: Python 3.10
- CCXT version: 2.4.66

```
exchange = ccxt.wavesexchange()
print('market count:', len(exchange.fetch_markets()))
print('ticker count:', len(exchange.fetch_tickers()))
```

```
market count: 111
ticker count: 100
```

`fetch_tickers` in Waves.Exchange doesn't probably fetch all tickers that it could. Recently I have noticed such pairs as ETH/BTC occasionally missing from the fetched tickers.

`fetch_tickers` is currenlty using https://api.wavesplatform.com/v0/pairs end point. The url shows the following when clicked:
```
{"__type":"list","isLastPage":false,"lastCursor":"OExRVzhmN1A1ZDVQWk03R3RaRUJnYXFSUEdTelMzRGZQdWlYclVSSjRBSlM6REcyeEZrUGREd0tVb0JrekdBaFF0THBTR3pmWExpQ1lQRXplS0gyQWQyNHA=","data":[{"__type":"pair","data":{"firstPrice":0.02,"lastPrice":0.14,"volume":1800030,"quoteVolume":210002.1,"high":0.14,"low":0.02,"weightedAveragePrice":0.11666588,"txsCount":10,"volumeWaves":281402814000},"amountAsset":"Ge5Vp4GnsUc5AZTGk2hQdCBgx4HicenuKnt24WJLQYLr","priceAsset":"8vrLCmd25LEA2GwvSYHtVy4cEf8TevywJHUnG4GiBBuo"}
...
```
As can be seen, "isLastPage" is actually `false`, so therefore there should be more tickers to fetch on the next cursor or something like that, but ccxt is currently only making one API call to fetch the tickers.

However, I think it would probably better to use the same end point as `fetch_markets` is using: https://waves.exchange/api/v1/forward/marketdata/api/v1/tickers

This end point seems at a quick glance provide the same information as the other (I haven't fully confirmed this however) and only requires one call to fetch all tickers. It does also sound thematically more correct end point to use.

**Comment by carlosmiei** [comment]
Hello @JovianMoon,
Thanks for reporting it, we will take a look 

cc/ @sc0Vu

**Comment by JovianMoon** [comment]
@sc0Vu @carlosmiei @kroitor Fixing `fetch_tickers` did introduce a new bug for `fetch_ticker` as described above, and still exists in 2.6.27. I don't seem to have a permission to reopen this issue, but maybe one of you could?
