### ISSUE TITLE
Bitmex fetch_total_balance decimal issue

### ISSUE THREAD

**Issue by KevinBaudin** [ccxt/ccxt#16234]
OS: Ubuntu 22.04.1 LTS
Programming Language version: Python 3.8.13
CCXT version: 2.4.70

Hello guys,
I've been working on Bitmex and came across this:

```
import ccxt
exchange_id = "bitmex"
keys = {"apiKey": XXX, "secret": YYY}

exchange_params = {
    'enableRateLimit': True,
    'apiKey': keys['apiKey'],
    'secret': keys['secret'],
    'options': {
        'defaultType': 'spot',
    },
    'enableRateLimit': True,
}

exchange = getattr(ccxt, exchange_id)(exchange_params)

exchange.fetch_total_balance()
>>> {'BTC': 0.0, 'USDT': 32.517974, 'USDC': 0.0, 'TRX': 10.0, 'ETH': 0.02}
```

My balances are currently:
![image](https://user-images.githubusercontent.com/20791331/209802780-e375e1f3-7aed-4ec8-8431-c3b32dd7ddfb.png)

I suspect that there is an issue in this part of the code: 
https://github.com/ccxt/ccxt/blob/master/python/ccxt/bitmex.py#L548

I think the divide should be by the factor, for non USDT coins:

```
symbol = "TRX_USDT"
infos = exchange.load_markets()[symbol]["info"]
factor = int(infos["underlyingToPositionMultiplier"])
```

Thanks for your work :)

**Comment by carlosmiei** [comment]
Hello @KevinBaudin,
thanks for reporting it, we will take a look!
