### ISSUE TITLE
How to remove manual install

### ISSUE THREAD

**Issue by mmehrle** [ccxt/ccxt#1623]
- OS: OS X
- Programming Language version: python
- CCXT version: 1.10.912

I downloaded the latest version and ran 'python setup.py install' from the CLI. Now I'm running anaconda and somehow all my conda environments are screwed up as I can't get rid of that manual deployment. I can't install or uninstall via pip either now as I always get:

Can't uninstall 'ccxt'. No files were found to uninstall.

But when I drop into the python command line I am able to load ccxt via import and print the version. I have been trying to figure out how to get rid of this installation but am unable to. My last resort would be to uninstall conda but I have an inkling that may not even fix this.

Also, in PyCharm I am able to load my conda environment but ccxt is not shown as a package although it's available from the command line. So something got really screwed up here.

Can you help me sort this out?

**Comment by kroitor** [comment]
First, you need to determine which pythons are installed, check their versions and your $PATH environment variable, remove the Cond

> I downloaded the latest version and ran 'python setup.py install' from the CLI.

What do you see when you type `python --version` in console?

**Comment by mmehrle** [comment]
Thanks to getting back to me. I've got several envs installed but did deactivate them. So on the regular install I get 'Python 3.6.0 :: Anaconda custom (64-bit)'.

To show you where my problem lies please take a look at the sequence of commands I posted below. The bold part shows that there is already some requirement satisfied. And I have a hard time getting rid of it :-(

`
MBP:bin michael$ conda info --envs
# conda environments:
#
base                  *  /Users/michael/anaconda3
py36                     /Users/michael/anaconda3/envs/py36
quant                    /Users/michael/anaconda3/envs/quant

MBP:bin michael$ source activate py36
(py36) MBP:bin michael$ python
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 13:19:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ccxt'
>>> ^Z
[10]+  Stopped                 python
(py36) MBP:bin michael$ source deactivate py36
MBP:bin michael$ source activate base
(base) MBP:bin michael$ python
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 13:19:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ccxt'
>>> ^Z
[11]+  Stopped                 python
(base) MBP:bin michael$ source deactivate base
MBP:bin michael$ conda create -n py27 python=2.7
Solving environment: done

## Package Plan ##

  environment location: /Users/michael/anaconda3/envs/py27

  added / updated specs: 
    - python=2.7


The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-ha1e5d58_0
    certifi:         2018.1.18-py27_0     
    libcxx:          4.0.1-h579ed51_0     
    libcxxabi:       4.0.1-hebd6815_0     
    libedit:         3.1-hb4e282d_0       
    libffi:          3.2.1-h475c297_4     
    ncurses:         6.0-hd04f020_2       
    openssl:         1.0.2n-hdbc3d79_0    
    pip:             9.0.1-py27h1567d89_4 
    python:          2.7.14-hde5916a_29   
    readline:        7.0-hc1231fa_4       
    setuptools:      38.4.0-py27_0        
    sqlite:          3.21.0-h3efe00b_2    
    tk:              8.6.7-h35a86e2_3     
    wheel:           0.30.0-py27h677a027_1
    zlib:            1.2.11-hf3cbc9b_2    

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate py27
#
# To deactivate an active environment, use
#
#     $ conda deactivate

MBP:bin michael$ conda activate py27
(py27) MBP:bin michael$ pwd
/Users/michael/anaconda3/bin
(py27) MBP:bin michael$ pip install ccxt
Collecting ccxt
  Using cached ccxt-1.10.912-py2.py3-none-any.whl
**Requirement already satisfied: setuptools in /Users/michael/anaconda3/envs/py27/lib/python2.7/site-packages (from ccxt)
Collecting requests (from ccxt)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Requirement already satisfied: certifi in /Users/michael/anaconda3/envs/py27/lib/python2.7/site-packages (from ccxt)**
Collecting chardet<3.1.0,>=3.0.2 (from requests->ccxt)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests->ccxt)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests->ccxt)
  Using cached idna-2.6-py2.py3-none-any.whl
Installing collected packages: chardet, urllib3, idna, requests, ccxt
Successfully installed ccxt-1.10.912 chardet-3.0.4 idna-2.6 requests-2.18.4 urllib3-1.22
(py27) MBP:bin michael$ 
`

**Comment by mmehrle** [comment]
Hey kroitor - I think I fixed it somehow by the sequence of commands I posted in my previous comment. Go figure.

>>> import ccxt
>>> import os
>>> print (os.path.abspath(ccxt.__file__))
/Users/michael/anaconda3/envs/py27/lib/python2.7/site-packages/ccxt/__init__.pyc

It's also showing in PyCharm now, so I think I'm good. But quite frankly I have no idea how this got screwed up before and how I managed to fix it.
