### ISSUE TITLE
Bitget has no futures ?

### ISSUE THREAD

**Issue by dawadam** [ccxt/ccxt#16233]
- CCXT version: 2.4.56

Why bitget exchange has futures to false ?

```
const exchange = new ccxt.bitget()
console.log("has", exchange.has)
```
print :

```
has {
  publicAPI: true,
  privateAPI: true,
  CORS: undefined,
  spot: true,
  margin: false,
  swap: true,
  future: false,
  option: false,
  addMargin: true,
  cancelAllOrders: true,
  cancelOrder: true,
[...]
```

**Comment by frosty00** [comment]
bitget has `swap` markets, which are perpetual futures, but it doesn't have an expiring futures (that's the meaning of the `future` key

**Comment by dawadam** [comment]
Yet on their site it is clearly stated "Futures".
And there are contracts that expire.

**Comment by frosty00** [comment]
where? they are all perps...

**Comment by frosty00** [comment]
ah I see two markets let me check

**Comment by frosty00** [comment]
<img width="613" alt="Screenshot 2022-12-28 at 00 32 08" src="https://user-images.githubusercontent.com/14319357/209782962-4f95a4cf-0f71-4294-a764-3d08b57bd721.png">

will fix these symbols and test it
