### ISSUE TITLE
Bybit order book stream gives always the same data

### ISSUE THREAD

**Issue by quantoor** [ccxt/ccxt#16241]
- OS: Windows 10
- Programming Language version: Python 3.10.4
- CCXT version: 2.4.55

I am watching the order book updates of bybit and I am always receiving the same data. I run the following code and it always prints 'True', except the first iteration.

```
import ccxt.pro as ccxtpro
import asyncio

async def main():
    exchange = ccxtpro.bybit({'newUpdates': True})
    last = None

    while True:
        orderBook = await exchange.watch_order_book("BTCUSDT")
        print(orderBook == last)
        last = orderBook

asyncio.run(main())
```

If I print best bid and ask I get something like this:

```
[16644.5, 68.634] [16645.0, 53.637]
[16644.5, 68.634] [16645.0, 53.637]
[16644.5, 68.634] [16645.0, 53.637]
[16644.5, 68.634] [16645.0, 53.637]
[16644.5, 68.634] [16645.0, 53.637]
[16644.5, 68.634] [16645.0, 53.637]
[16644.5, 68.634] [16645.0, 53.637]
[16644.5, 68.634] [16645.0, 53.637]
[16644.5, 68.634] [16645.0, 53.637]
[16644.5, 68.634] [16645.0, 53.637]
[16644.5, 68.634] [16645.0, 53.637]
[16644.5, 68.634] [16645.0, 53.637]
[16644.5, 68.634] [16645.0, 53.637]
[16644.5, 68.634] [16645.0, 53.637]
[16644.5, 68.634] [16645.0, 53.637]
```

I checked the order book stream of other exchanges like binance, phemex and mexc, and it seems to work fine.

**Comment by frosty00** [comment]
please make sure you have the latest version of ccxt

**Comment by quantoor** [comment]
ok I have upgraded to ccxt `2.4.71`, now the Bybit order book stream seems working fine for the spot symbol `BTC/USDT`, but I keep getting `Connection timeout` for the swap symbol `BTC/USDT:USDT`

**Comment by frosty00** [comment]
@quantoor it seems to be working for me

**Comment by quantoor** [comment]
@frosty00 I am running this code, do you see anything wrong?
```
import ccxt.pro as ccxtpro
import asyncio

async def main():
    print('start')
    exchange = ccxtpro.bybit({'newUpdates': True})

    while True:
        orderBook = await exchange.watch_order_book("BTC/USDT:USDT")
        print(orderBook['bids'][0], orderBook['asks'][0])

asyncio.run(main())
```

**Comment by frosty00** [comment]
@quantoor there were some bugs in bybit swap due to the recent updates of the symbol conflicts, I pushed a fix just recently #16243 so if you wait 30 mins ccxt > 2.41.72 it should be fixed. In the meantime you can use the REST implementation without any bugs and with support for loading all the markets at once now. Apologies for these bugs!!

**Comment by quantoor** [comment]
ok I'll wait for the update v2.41.72, thanks

**Comment by ttodua** [comment]
as mentioned by frosty00 , the bug should be fixed now.
I'll close this issue.
let us know if you have any further issues.

**Comment by quantoor** [comment]
@frosty00 @ttodua the version 2.4.72 is not available yet, right?

If I try to install `pip install ccxt==2.4.72` 
I get `ERROR: No matching distribution found for ccxt==2.4.72`

**Comment by carlosmiei** [comment]
> @frosty00 @ttodua the version 2.4.72 is not available yet, right?
> 
> If I try to install `pip install ccxt==2.4.72` I get `ERROR: No matching distribution found for ccxt==2.4.72`

Hello @quantoor, we had an issue with the build and the package was not published. We expect that this will be fixed soon (30/40min).

**Comment by quantoor** [comment]
> > @frosty00 @ttodua the version 2.4.72 is not available yet, right?
> > If I try to install `pip install ccxt==2.4.72` I get `ERROR: No matching distribution found for ccxt==2.4.72`
> 
> Hello @quantoor, we had an issue with the build and the package was not published. We expect that this will be fixed soon (30/40min).

I have installed v2.4.72 now and it seems fixed, thanks!
