### ISSUE TITLE
ByBit: market symbols behaviour changed since 2.4.65

### ISSUE THREAD

**Issue by marcoismobile** [ccxt/ccxt#16253]
It seems the symbols in the markets list is changed since version 2.4.65 of CCXT, before this version it was working as expected.

Exchange is initialized with:
````
            'options': {
                'defaultType': 'swap',  # 'swap', 'future', 'option', 'spot'
                'defaultSubType': 'linear',  # 'linear', 'inverse'
                'defaultSettle': 'USDT',  # 'USDT', 'USDC'
            }
````

e.g. on the **fetchTickers()** the list of symbols contained :

**v2.4.65** of CCXT returned (when e.g. filtered on XRP):
- XRP/USD:USDC
- XRP/USDT

**v2.4.64** of CCXT returned (when e.g. filtered on XRP):
- XRP/USD:USDC
- XRP/USDT:USDT

So it looks like starting from v2.4.65, the spot markets are overriding the Contract markets or something?

It might have something to do with one of the following commits:
https://github.com/ccxt/ccxt/commit/8980c76dd8e7469f6b2463375af5c7fea40bea53

If you need more debug/additional information please let me know.

**Comment by frosty00** [comment]
hi @marcoismobile. there's a known bug in ccxt 2.4.65 can you please update to the latest version
