### ISSUE TITLE
how to enable or disable margin account?

### ISSUE THREAD

**Issue by chaedongyoon** [ccxt/ccxt#16261]
- OS:windows11
- Programming Language version:python v2022.18.2
- CCXT version:22.3
![image](https://user-images.githubusercontent.com/90673349/209982594-f43a14e1-99f5-491c-b160-f91e2cf3c51d.png)
https://binance-docs.github.io/apidocs/spot/en/#disable-isolated-margin-account-trade

it is regard of above screenshot

how to enable isolated margin account (ex : btc/ usdt) with ccxt?
maybe it is related to https://github.com/ccxt/ccxt/issues/7384

**Comment by pcriadoperez** [comment]
Hi @chaedongyoon ,

You can call the endpoint using ccxt implicit api. (https://docs.ccxt.com/en/latest/manual.html#implicit-api-methods)
So for example: `binance.sapiDeleteMarginIsolatedAccount ({symbol: 'BTCUSDT'})`

I'll close this issue for now but feel free to reach out with any more questions.

**Comment by chaedongyoon** [comment]
> Hi @chaedongyoon ,
> 
> You can call the endpoint using ccxt implicit api. (https://docs.ccxt.com/en/latest/manual.html#implicit-api-methods) So for example: `binance.sapiDeleteMarginIsolatedAccount ({symbol: 'BTCUSDT'})`
> 
> I'll close this issue for now but feel free to reach out with any more questions.

i'm very sorry for this , 
![image](https://user-images.githubusercontent.com/90673349/210131991-97b38553-dc83-47bd-889e-8fa22225425c.png)

it loooks just grey font, and it's not work  
T_T sorry 
could you help me?
