### ISSUE TITLE
Is there any convert api

### ISSUE THREAD

**Issue by MadhuraJoshi1** [ccxt/ccxt#16272]
I want to implement convert API of OKX exchange using CCXT. Is there any API to achieve this ?

**Comment by pcriadoperez** [comment]
Hi @MadhuraJoshi1,
We don't use the convert API on any of our endpoints but you can call it using ccxt by using the Implicit API of ccxt You can read more here (https://docs.ccxt.com/en/latest/manual.html#implicit-api)

An example would be to call `okx.privateGetAssetConvertCurrencies()`

I'll close this issue for now, but feel free to reach out with any more questions.
