### ISSUE TITLE
OHLCV flag always false

### ISSUE THREAD

**Issue by mmehrle** [ccxt/ccxt#1627]
- OS: OS X
- Programming Language version: python 2.7
- CCXT version: 1.10.912

I just upgraded to 1.10.912 and got it working (thanks kroitor!) but I think there's a bug with the OHLCV flag:

`
import sys
import ccxt

print "CCXT version: " + ccxt.__version__

exchanges = ccxt.exchanges

for name in exchanges:
    exchange = getattr(ccxt, name)({
        "verbose": True,
    })

    print(exchange.id)
    print("offers OHLCV: {}".format(exchange.hasFetchOHLCV))
`

Well, what I'm getting is this:

`CCXT version: 1.10.912
_1broker
offers OHLCV: False
_1btcxe
offers OHLCV: False
acx
offers OHLCV: False
allcoin
offers OHLCV: False
anxpro
offers OHLCV: False
bibox
offers OHLCV: False
binance
offers OHLCV: False
bit2c
offers OHLCV: False
bitbay
offers OHLCV: False
bitcoincoid
offers OHLCV: False
bitfinex
offers OHLCV: False
bitfinex2
offers OHLCV: False
bitflyer
offers OHLCV: False
bithumb
offers OHLCV: False
bitlish
offers OHLCV: False
bitmarket
offers OHLCV: False
bitmex
offers OHLCV: False
bitso
offers OHLCV: False
bitstamp
offers OHLCV: False
bitstamp1
offers OHLCV: False
bittrex
offers OHLCV: False
bl3p
offers OHLCV: False
bleutrade
offers OHLCV: False
braziliex
offers OHLCV: False
btcbox
offers OHLCV: False
btcchina
offers OHLCV: False
btcexchange
offers OHLCV: False
btcmarkets
offers OHLCV: False
btctradeua
offers OHLCV: False
btcturk
offers OHLCV: False
btcx
offers OHLCV: False
bter
offers OHLCV: False
bxinth
offers OHLCV: False
ccex
offers OHLCV: False
cex
offers OHLCV: False
chbtc
offers OHLCV: False
chilebit
offers OHLCV: False
coincheck
offers OHLCV: False
coinexchange
offers OHLCV: False
coinfloor
offers OHLCV: False
coingi
offers OHLCV: False
coinmarketcap
offers OHLCV: False
coinmate
offers OHLCV: False
coinsecure
offers OHLCV: False
coinspot
offers OHLCV: False
cryptopia
offers OHLCV: False
dsx
offers OHLCV: False
exmo
offers OHLCV: False
flowbtc
offers OHLCV: False
foxbit
offers OHLCV: False
fybse
offers OHLCV: False
fybsg
offers OHLCV: False
gatecoin
offers OHLCV: False
gateio
offers OHLCV: False
gdax
offers OHLCV: False
gemini
offers OHLCV: False
getbtc
offers OHLCV: False
hitbtc
offers OHLCV: False
hitbtc2
offers OHLCV: False
huobi
offers OHLCV: False
huobicny
offers OHLCV: False
huobipro
offers OHLCV: False
independentreserve
offers OHLCV: False
itbit
offers OHLCV: False
jubi
offers OHLCV: False
kraken
offers OHLCV: False
kucoin
offers OHLCV: False
kuna
offers OHLCV: False
lakebtc
offers OHLCV: False
liqui
offers OHLCV: False
livecoin
offers OHLCV: False
luno
offers OHLCV: False
lykke
offers OHLCV: False
mercado
offers OHLCV: False
mixcoins
offers OHLCV: False
nova
offers OHLCV: False
okcoincny
offers OHLCV: False
okcoinusd
offers OHLCV: False
okex
offers OHLCV: False
paymium
offers OHLCV: False
poloniex
offers OHLCV: False
qryptos
offers OHLCV: False
quadrigacx
offers OHLCV: False
quoinex
offers OHLCV: False
southxchange
offers OHLCV: False
surbitcoin
offers OHLCV: False
therock
offers OHLCV: False
tidex
offers OHLCV: False
urdubit
offers OHLCV: False
vaultoro
offers OHLCV: False
vbtc
offers OHLCV: False
virwox
offers OHLCV: False
wex
offers OHLCV: False
xbtce
offers OHLCV: False
yobit
offers OHLCV: False
yunbi
offers OHLCV: False
zaif
offers OHLCV: False
zb
offers OHLCV: False`

I know for a fact that some of them offer OHLCV so upgrading to the latest version broke it for me :-(

**Comment by kroitor** [comment]
Hi! This is answered here: https://github.com/ccxt/ccxt/issues/1536#issuecomment-361001847
We are migrating from `has***` properties to a single dictionary of `.has = {}` properties. You have to change your code accordingly with the new version. Sorry for the inconvenience. Hope it helps.

**Comment by mmehrle** [comment]
Kroitor - I just checked and publicAPI and privateAPI do not seem to be implemented yet.
