### ISSUE TITLE
KulCoin Java SDK Not found

### ISSUE THREAD

**Issue by ChikaKing** [ccxt/ccxt#16283]
### Description

I can not install Kulcoin dependency on my Spring boot application

Error: 
com.kucoin:kucoin-java-sdk:jar:1.0.6 was not found in https://repo.maven.apache.org/maven2 

<img width="855" alt="Screenshot 2023-01-01 at 12 50 24" src="https://user-images.githubusercontent.com/115144077/210169749-16e3afa3-6b33-4a1f-b6d5-e7c116c447df.png">

<img width="914" alt="Screenshot 2023-01-01 at 12 50 56" src="https://user-images.githubusercontent.com/115144077/210169754-15e71c2a-8ffc-4405-930b-30eb0c51a7c0.png">

### Code

```
  

```

**Comment by sc0Vu** [comment]
You probably looked for the kucoin java sdk: https://github.com/Kucoin/kucoin-java-sdk.
