### ISSUE TITLE
[NEW EXCHANGE]: ztb

### ISSUE THREAD

**Issue by yyclr99** [ccxt/ccxt#16282]
### Exchange Name

ZT

### URL of the Exchange

https://www.ztb.im

### URL of the Exchange's API docs

https://zt-global.github.io/ztapi/cn/#45fa4e00db

### Why should this exchange be implemented?

Many new coins will be listed on this exchange, and there are some coins that are only available on this exchange, such as vollar. hope to add ZT exchange soon. Thank you!

**Comment by ttodua** [comment]
dead ex
