### ISSUE TITLE
Gate market order not working: createMarketBuyOrder is not defined

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#16296]
### Operating System

Windows 10

### Programming Languages

JS

### CCXT Version

2.5.5

### Description

Hello:
I want to place a limit buy order in exchange gate, but I found gate seems not support limit order, so I changed my code to use market order, but I got error:
createMarketBuyOrder is not defined.
The following is the total output:
D:\nodejs\CCXT_Gate>node gate_actPair1MarketOrder.js buy BTCST/USDT 3.4
2.5.5
Place a buy market oder!
ReferenceError: createMarketBuyOrder is not defined
    at actPair1MarketOrder (D:\nodejs\CCXT_Gate\gate_actPair1MarketOrder.js:32:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

D:\nodejs\CCXT_Gate>

### Code

```
const ccxt = require('ccxt');
console.log(ccxt.version);

if (process.argv.length != 5)
{
console.error('Usage: buy|sell BTC/USDT Amount');
console.error('Buy|Sell Pair1 at market price with amount');
console.error('Please try again!');
process.exit(1);
}
const [nodejs, script1, act1, pair1, amount1] = process.argv;

let exchange = new ccxt.gate
({
apiKey: 'My_API_Key',
secret: 'My_Secret_Key',
'options': {
'adjustForTimeDifference': true,
'fetchCurrencies': true,
'verbose': true, }
});

const actPair1MarketOrder = async (act1, pair1, amount1) =>
{
try
{
await exchange.loadMarkets();
switch (act1)
{
case 'buy':
console.log('Place a buy market oder!');
const buy_market1 = await createMarketBuyOrder(pair1, amount1);
const json_buy = JSON.stringify(buy_market1);
console.log(json_buy);
break;
case 'sell':
console.log('Place a sell market oder!');
const sell_market1 = await createMarketSellOrder(pair1, amount1);
const json_sell = JSON.stringify(sell_market1);
console.log(json_sell);
break;
}
}
catch (err)
{
console.error(err);
}
};
actPair1MarketOrder(act1, pair1, amount1);

```

**Comment by carlosmiei** [comment]
Hello @zydjohnHotmail,
According to your snippet, you're calling a local undefined `createMarketSellOrder()`. You need to do `exchange.createMarketSellOrder()`

**Comment by zydjohnHotmail** [comment]
Hi:
Thanks for your findings, I will change it and do some testing later.
Thanks,

**Comment by carlosmiei** [comment]
@zydjohnHotmail Will close the issue, let us know if anything
