### ISSUE TITLE
Binance Unified Symbols

### ISSUE THREAD

**Issue by frosty00** [ccxt/ccxt#16306]
We are updating Binance to support the unified contract naming scheme. Please read about the contract naming scheme here https://docs.ccxt.com/en/latest/manual.html#contract-naming-conventions

All code will continue to work as before expect that the symbols parsed by ccxt will be returned as the unified symbols in the exchange response. Symbols and market ids passed into ccxt functions will be backwards compatible and you will be able to use the old symbol scheme as well as the new contract naming scheme. All markets will now be loaded in a single call to loadMarkets on Binance. 

*Usage:*

```javascript
const binance = new ccxt.binance ()
await binance.loadMarkets ()

binance.createOrder ('BTC/USD:BTC',   ... ) // always inverse perpetual swap
binance.createOrder ('BTCUSD_PERP',   ... ) // always inverse perpetual swap
binance.createOrder ('BTC/USD',       ... ) // always inverse perpetual swap
binance.createOrder ('BTC/USDT:USDT', ... ) // always linear  perpetual swap

binance.createOrder ('BTC/USDT', ... )      // can be spot or future depending on .options['defaultType'] or .options['defaultSubType'] (default is spot)
binance.createOrder ('BTCUSDT', ... )       // can be spot or future depending on .options['defaultType'] or .options['defaultSubType'] (default is spot)
```

```javascript
binance.options['defaultType'] = 'future'   // legacy option
binance.createOrder ('BTC/USDT:USDT', ... ) // perpetual swap
binance.createOrder ('BTC/USDT', ... )      // perpetual swap
binance.createOrder ('BTCUSDT', ... )       // perpetual swap
```

```javascript
binance.options['defaultType'] = 'swap'     // new unified mode
binance.createOrder ('BTCUSDT', ... )       // perpetual swap
```

```javascript
binance.options['defaultSubType'] = 'linear' // new unified mode
binance.createOrder ('BTC/USDT', ... )       // perpetual swap
binance.createOrder ('BTCUSDT', ... )        // perpetual swap
```

Now the unified contract symbols will be returned from all unified methods:

```javascript
binance.options['defaultType'] = 'swap'
binance.fetchOrderBook ('BTCUSDT', ... )    // perpetual swap

> { 'symbol': 'BTC/USDT:USDT', ... }

```

binanceusdm and binancecoinm will continue to work as before but with the added support of the unified symbols. We are letting you know in advance so that you can adjust your code to accommodate for these changes. We will release a new version of ccxt with support for the symbols this week.

**Comment by kroitor** [comment]
Related PR: https://github.com/ccxt/ccxt/pull/16227

**Comment by samgermain** [comment]
> Related PR: #16227

Should this PR be closed then?
