### ISSUE TITLE
[php] Bittrex fetch_tickers() causing division by zero

### ISSUE THREAD

**Issue by vitoo** [ccxt/ccxt#1630]
Hi,
Using : 

`$exchange->fetch_tickers();`

is causing division by zero 

Must be here : https://github.com/ccxt/ccxt/blob/master/php/bittrex.php#L243

Maybe because there is new market like : https://bittrex.com/Market/Index?MarketName=BTC-IGNIS

**Comment by vitoo** [comment]
You will fix php too ? 

Thanks

**Comment by kroitor** [comment]
@vitoo it will get fixed automatically: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support (5-10 minutes)

**Comment by kroitor** [comment]
FIxed in 1.10.913. Thx for reporting!

**Comment by vitoo** [comment]
Amazing !
