### ISSUE TITLE
It seems that the spot margin exchange and the derivatives exchange are not distinguished and merged.

### ISSUE THREAD

**Issue by big100** [ccxt/ccxt#16310]
### Programming Languages

python

### CCXT Version

2.5.12

### Description

There was no problem with ccxt v2.0.84.
After updating to ccxt v2.5.12 the problem arose.

In ccxt v2.0.84
exchange = ccxt.bybit ({
     'enableRateLimit': False,
     'options': {
     'defaultType': 'future'
     }
})
exchange.load_markets()
usdt_symbol = [i for i in exchange.ids if i.endswith("USDT")]
print('usdt_symbol: ', len(usdt_symbol))

result = >>>> usdt_symbol: 183

In ccxt v2.5.12
exchange = ccxt.bybit ({
     'enableRateLimit': False,
     'options': {
     'defaultType': 'future'
     }
})
exchange.load_markets()
usdt_symbol = [i for i in exchange.ids if i.endswith("USDT")]
print('usdt_symbol: ', len(usdt_symbol))

result = >>>> usdt_symbol: 375

It seems that the spot margin exchange and the derivatives exchange are not distinguished and merged.

Is there a new way to tell them apart?
Or is it a bug?

![image](https://user-images.githubusercontent.com/37491415/210303568-1098ca85-0beb-45ba-9166-ffe389b859ab.png)
![image](https://user-images.githubusercontent.com/37491415/210303588-ad1643f0-f2c5-4567-8b8c-9276a77a219c.png)

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @big100,

That's not a bug, recently, we added support to conflicting market ids so exchanges like bybit and gate can load all the markets simultaneously. Each market has a set of boolean properties (swap, linear, inverse, spot, etc) that allows for quick filtering and an easy way to tell its type. Moreover, our unified symbols reflect that as well, if you see `symbol: "BTC/USDT:USDT` it's safe to assume it's a linear swap, whereas `symbol: BTC/USD:BTC` represents an inverse swap.

Please read more about it here: https://docs.ccxt.com/en/latest/manual.html#symbols-and-market-ids

Let's say you want to get all linear swaps in a list, you just do this:
```Python
linear_swaps = list([i for i in markets.values() if i['swap'] and i['linear']])
```

**Comment by big100** [comment]
It's solved thanks.
have a good day
