### ISSUE TITLE
CCXT Pro's `watch_orders` and `watch_balance` is not working on Bitmex Testnet

### ISSUE THREAD

**Issue by jelofsson** [ccxt/ccxt#16311]
### Operating System

Arch Linux

### Programming Languages

python

### CCXT Version

2.4.71

### Description

await exchange.watch_balance() and await exchange.watch_orders() produces error

`Connection closed by remote server, closing code 0`

**Comment by sc0Vu** [comment]
Hi @jelofsson

It worked for me, probably the network issue. Would you like to call again?

**Comment by jelofsson** [comment]
My bad. It works now.
