### ISSUE TITLE
Huobi fetch_deposit_address problem

### ISSUE THREAD

**Issue by KindSpidey** [ccxt/ccxt#16319]
### Operating System

Windows

### Programming Languages

python

### CCXT Version

2.5.16

### Description

Everything worked well, but a few days ago I got error which still happens, when I try to fetch address.

So what happened and how to fix it?

### Code

```
  huobi.fetch_deposit_address("QRDO",{"network": "ERC20"})
```
brings
`ccxt.base.errors.AuthenticationError: huobipro {"code":1003,"message":"invalid signature"}`

**Comment by sc0Vu** [comment]
@KindSpidey 

Probably they invalidate the api key, it works after I apply another new key.
