### ISSUE TITLE
Binance API Endpoint Signing using RSA

### ISSUE THREAD

**Issue by eonsmile** [ccxt/ccxt#16320]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

https://binance-docs.github.io/apidocs/futures/en/#signed-trade-and-user_data-endpoint-security

**For Binance, does CCXT support user generated api keys based on RSA algorithm (ie., not traditional HMAC methods)?**

FYI, this is an announcement from Binance:

[VIP Client Notification - Critical - API Key Deletion Notice]

As part of the change we are making on API key security, we will be deleting some of your API keys which are with non-readonly permission but with no bound IPs. For non-VIP account the deletion process will start on 5th Jan. For VIP accounts the deletions starts on 11th Jan and took a few days to complete.

To avoid those API keys being delete there are a few options.

1. Add whitelist IP binding to impacted API keys. API functions are available to manage IP whitelisting from master accounts on all sub accounts.
2. Use the new self-generated API keys to replace the impacted API keys. The self-generated API keys do not require IP binding.
3. Change the impacted API keys to have only readonly permission. Pure readonly API keys will be not be impacted.

You can find below resources to help to make relevant changes
- To get current IP binding details of sub accounts via API: https://binance-docs.github.io/apidocs/spot/en/#get-ip-restriction-for-a-sub-account-api-key-for-master-account
- To add IP binding via API: https://binance-docs.github.io/apidocs/spot/en/#update-ip-restriction-for-sub-account-api-key-for-master-account
- How to set up self-generated API keys: https://www.binance.com/en/support/announcement/binance-now-supports-rsa-api-keys-2022-12-29-f418fed3f05f4854a7bbccaad3104a1c

If you have any question or concern please reach out to your client manager or a member of the KAC team.

### Describe the solution you'd like

CCXT new version supporting this feature

**Comment by sc0Vu** [comment]
@eonsmile 

We already support rsa signature in binance. You can simply put your rsa private key in private option. The private key looks like:

```
-----BEGIN RSA PRIVATE KEY-----
...
```

**Comment by eonsmile** [comment]
Sorry; I found the following page with solutions now:

https://github.com/ccxt/ccxt/pull/16280
