### ISSUE TITLE
Bitmex fetch_positions decimals issue

### ISSUE THREAD

**Issue by KevinBaudin** [ccxt/ccxt#16327]
### Operating System

Ubuntu 22.04.1 LTS

### Programming Languages

python

### CCXT Version

2.5.3

### Description

Hello guys, once again with Bitmex and decimal issues.
This time, it's about derivatives.

See the code, it prints:

>  BTC/USDT:USDT None
Returned Value None
Expected Value None
------
> ETH/USDT:USDT 0.001
Returned Value 0.001
Expected Value 0.01
------
> DOGE/USDT:USDT 0.027
Returned Value 0.027
Expected Value 270
------

Here is a screenshot of my current balance as bitmex shows me:
![image](https://user-images.githubusercontent.com/20791331/210541659-020656c4-0db6-478d-927c-0c72ef889edd.png)

Thanks for your work :)

### Code

```
import ccxt
from ccxt.base.precise import Precise

keys = {"apiKey": "-", "secret": "-"}

exchange_params = {
    'enableRateLimit': True,
    'apiKey': keys['apiKey'],
    'secret': keys['secret'],
}


exchange = getattr(ccxt, "bitmex")(exchange_params)
markets = exchange.load_markets()

for p in exchange.fetch_positions():
    symbol, contracts = p["symbol"], p["contracts"]
    position = p["info"]
    
    market = exchange.safe_market(exchange.safe_string(position, 'symbol'), None)
    print(symbol, contracts)
    
    # See convert value function in ccxt.bitmex https://github.com/ccxt/ccxt/blob/master/python/ccxt/bitmex.py#L2120
    value = exchange.omit_zero(exchange.safe_number(position, 'currentQty'))
    value = exchange.number_to_string(value)
    resultValue = Precise.string_mul(value, '0.000001')
    print("Returned Value", resultValue)
    
    # Expected Value, and how I think the issue could be solved
    value = exchange.omit_zero(exchange.safe_number(position, 'currentQty'))
    value = exchange.number_to_string(value)
    resultValue = Precise.string_div(value, market["info"]["underlyingToPositionMultiplier"])
    print("Expected Value", resultValue)
    
    print("------")

```

**Comment by samgermain** [comment]
> ### Operating System
> 
> Ubuntu 22.04.1 LTS
> ### Programming Languages
> 
> python
> ### CCXT Version
> 
> 2.5.3
> ### Description
> 
> Hello guys, once again with Bitmex and decimal issues. This time, it's about derivatives.
> 
> See the code, it prints:
> 
> > BTC/USDT:USDT None
> > Returned Value None
> > Expected Value None
> 
> > ETH/USDT:USDT 0.001
> > Returned Value 0.001
> > Expected Value 0.01
> 
> > DOGE/USDT:USDT 0.027
> > Returned Value 0.027
> > Expected Value 270
> 
> Here is a screenshot of my current balance as bitmex shows me: ![image](https://user-images.githubusercontent.com/20791331/210541659-020656c4-0db6-478d-927c-0c72ef889edd.png)
> 
> Thanks for your work :)
> ### Code
> 
> ```
> import ccxt
> from ccxt.base.precise import Precise
> 
> keys = {"apiKey": "-", "secret": "-"}
> 
> exchange_params = {
>     'enableRateLimit': True,
>     'apiKey': keys['apiKey'],
>     'secret': keys['secret'],
> }
> 
> 
> exchange = getattr(ccxt, "bitmex")(exchange_params)
> markets = exchange.load_markets()
> 
> for p in exchange.fetch_positions():
>     symbol, contracts = p["symbol"], p["contracts"]
>     position = p["info"]
>     
>     market = exchange.safe_market(exchange.safe_string(position, 'symbol'), None)
>     print(symbol, contracts)
>     
>     # See convert value function in ccxt.bitmex https://github.com/ccxt/ccxt/blob/master/python/ccxt/bitmex.py#L2120
>     value = exchange.omit_zero(exchange.safe_number(position, 'currentQty'))
>     value = exchange.number_to_string(value)
>     resultValue = Precise.string_mul(value, '0.000001')
>     print("Returned Value", resultValue)
>     
>     # Expected Value, and how I think the issue could be solved
>     value = exchange.omit_zero(exchange.safe_number(position, 'currentQty'))
>     value = exchange.number_to_string(value)
>     resultValue = Precise.string_div(value, market["info"]["underlyingToPositionMultiplier"])
>     print("Expected Value", resultValue)
>     
>     print("------")
> ```

@KevinBaudin [I've seen this problem a little bit](https://github.com/ccxt/ccxt/pull/14719#discussion_r969686416), but haven't really identified a solution yet. I'll be working on this soon, but if your able to identify a solution, that would be much appreciated

**Comment by samgermain** [comment]
I think I figured out a solution. I'll be creating PRs to fix these issues soon

**Comment by samgermain** [comment]
@carlosmiei Fixed by https://github.com/ccxt/ccxt/issues/18385 ?
