### ISSUE TITLE
Yobit FetchTickers return error.

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#16324]
### Operating System

Windows 10

### Programming Languages

JS

### CCXT Version

2.5.20

### Description

Hello:
I want to use exchange.fetchTickers() to get all tickers latest period price data, I have tried for more than 10 exchanges, they all worked well.  However, for the exchange yobit, I got the errors:
D:\nodejs\CCXT_Tickers>node yobit_fetchTickers.js
2.5.20
ArgumentsRequired: yobit fetchTickers() has 8956 markets exceeding max URL length for this endpoint (512 characters), please, specify a list of symbols of interest in the first argument to fetchTickers
    at yobit.fetchTickers (D:\nodejs\CCXT_Tickers\node_modules\ccxt\js\yobit.js:560:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchTickers (D:\nodejs\CCXT_Tickers\yobit_fetchTickers.js:14:17) {
  constructor: [class ArgumentsRequired extends ExchangeError]
}

The verbose output is similar to the errors above, but only show some markets price data.  I want to know if there is some easy way to show the tickers price data in chunks or in pages, or how to simply split the total 8956 markets in big chunks.
Please advise,

### Code

```
const ccxt = require('ccxt');
console.log(ccxt.version);

const fetchTickers = async () => 
{
let exchange = new ccxt.yobit
({'adjustForTimeDifference': true,
defaultType: 'spot',
'verbose': true });
try
{
if (exchange.has['fetchTickers'])
{
const tickers = await exchange.fetchTickers();
if (typeof tickers !== 'undefined')
{
const json_tickers = JSON.stringify(tickers);
console.log(json_tickers);
}
else
{
const obj_jsonTicker0 = ({ 'Data': [] });
const json_ticker0 = JSON.stringify(obj_jsonTicker0);
console.log(json_ticker0);
}
}
}
catch (err) 
{
console.error(err)
}
};
fetchTickers();  

```

**Comment by carlosmiei** [comment]
Hello @zydjohnHotmail, yes, you can split it into different chunks, for instance:

```Javascript
    await exchange.loadMarkets ();
    const marketSymbols = Object.keys (exchange.markets);
    const chunkSize = 300;
    let tickers = [];
    for (let i = 0; i < marketSymbols.length; i += chunkSize) {
        const chunk = marketSymbols.slice(i, i + chunkSize);
        const chunkTickers = await exchange.fetchTickers (chunk);
        tickers = tickers.concat (Object.values(chunkTickers));
    }
    // all tickers
    console.log(tickers)
```

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply, I will do some testing today.  But I have yet another question: what is the biggest chunk size I can set? Like 512 or 1024?
Please advise,
Thanks,

**Comment by carlosmiei** [comment]
> Hello: Thanks for your reply, I will do some testing today. But I have yet another question: what is the biggest chunk size I can set? Like 512 or 1024? Please advise, Thanks,

@zydjohnHotmail Theoretically, you could fetch 2048 max, but in practice, I could not do more than 300/400 each request.

**Comment by zydjohnHotmail** [comment]
Thanks and your code works well!
