### ISSUE TITLE
Wrong order type for Bitfinex

### ISSUE THREAD

**Issue by capriole-yassine** [ccxt/ccxt#16339]
### Operating System

Ubuntu

### Programming Languages

python

### CCXT Version

2.5.33

### Description

In bitfinex2.py, CCXT converts 'market' order type to 'EXCHANGE MARKET' and 'limit' to 'EXCHANGE LIMIT' using the option orderTypes.
However, when we do that, bitfinex raises this error: bitfinex2 type: invalid

We shouldn't convert 'market' type to 'EXCHANGE MARKET'. Same thing for 'limit'.

### Code

```
# convert 'market' to 'EXCHANGE MARKET'
# convert 'limit' 'EXCHANGE LIMIT'
# everything else remains as is
'orderTypes': {
     'market': 'EXCHANGE MARKET',
     'limit': 'EXCHANGE LIMIT',
},

```

**Comment by carlosmiei** [comment]
Hello @capriole-yassine,
Can you please share with us a verbose log?

**Comment by capriole-yassine** [comment]
Hello @carlosmiei , here is a verbose log
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/82177487/210969866-29338b56-36e3-4560-add4-3f7e1b7bae94.png">

**Comment by carlosmiei** [comment]
> Hello @carlosmiei , here is a verbose log <img alt="image" width="1019" src="https://user-images.githubusercontent.com/82177487/210969866-29338b56-36e3-4560-add4-3f7e1b7bae94.png">

@capriole-yassine the image is cut and if you can please paste it in text format so it's easier to read and parse

**Comment by capriole-yassine** [comment]
@carlosmiei 
fetch Response: bitfinex2 POST https://api.bitfinex.com/v2/auth/w/order/submit 500 ResponseHeaders: {'Date': 'Fri, 06 Jan 2023 09:14:21 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '31', 'Connection': 'keep-alive', 'X-Frame-Options': 'sameorigin', 'X-XSS-Protection': '1; mode=block', 'Referrer-Policy': 'same-origin', 'X-Download-Options': 'noopen', 'X-Content-Type-Options': 'nosniff', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains;', 'X-Permitted-Cross-Domain-Policies': 'none', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '785357cb6fa08fd0-FRA'} ResponseBody: ["error",10001,"type: invalid"]
