### ISSUE TITLE
Is that possible to use websockets without providing symbols and change the maxCapacity?

### ISSUE THREAD

**Issue by kerimaksoy** [ccxt/ccxt#16337]
### ؜

OS: Windows
Programming Language version: Node.js 16.14.2
CCXT version: 2.2.46

I use websockets in a C# project with exchanges like Binance and Huobi. And I can watch all tickers without providing any symbols. But when I am using ccxt I have to provide a symbol or symbols to watchTicker() method. Why?

And there is no capacity limit for the Huobi in C# but when I try to use ccxt watchTicker() for all symbols from Huobi I got error: 

```
 throw new Error ('throttle queue is over maxCapacity (' + this.config['maxCapacity'].toString () + '), see https://github.com/ccxt/ccxt/issues/11645#issuecomment-1195695526');
                  ^
```
I tried to changing the maxCapacity by

```
exchange.throttle.config['maxCapacity'] = 10000;
```
But still I got the same error.

I suppose maxCapacity means the max. number of symbols I can use concurrently for watchTicker(), Am I correct?

I would like to ask, Is that possible to use websockets without providing any symbols and Is there any method gives the maxCapacity of the exchange on ccxt?

**Comment by pcriadoperez** [comment]
Hi @kerimaksoy,
We are working on implementing the function `watchTickers (symbols = undefined, params = {})` for the exchanges that allow it.
In the case of binance, we recently added it so you should be able to call `binance.watchTickers()` to listen to all symbols.

I'll close this issue for now but feel free to reach out with any other questions

**Comment by nautonk** [comment]
> Hi @kerimaksoy, We are working on implementing the function `watchTickers (symbols = undefined, params = {})` for the exchanges that allow it. In the case of binance, we recently added it so you should be able to call `binance.watchTickers()` to listen to all symbols.
> 
> I'll close this issue for now but feel free to reach out with any other questions

Hello @pcriadoperez i tried to implement it but not all symbols are fetched, for example symbol ETH/BIDR.

Thank you
