### ISSUE TITLE
CCXT OKEX fetchorders not showing stoploss orders

### ISSUE THREAD

**Issue by pachinkopirate** [ccxt/ccxt#16348]
### Programming Languages
Python3

### CCXT Version
1.79.95

### Description
for okex, fetch_open_orders() outputs my limit orders but not my stoploss/takeprofit orders

how can i get my stoploss/takeprofit orders? it's driving me nuts!

### Code
okex = ccxt.okex({
     "apiKey": xxx,
     "secret": xxx,
     "password": xxx,
     'enableRateLimit': True,
     'options': {
         'defaultType': 'swap',
         'swap': True# ←-------------- quotes and 'future'
     }
})

```
okex.fetch_open_orders() #shows limit orders but not SL/TP orders

params = {'stop':True} 
okex.fetch_open_orders(params=params) 

#outputs ccxt.base.errors.BadRequest: okex {"code":"51000","data":[],"msg":"Parameter ordType  error"}
  

```

**Comment by sc0Vu** [comment]
Hi @pachinkopirate 

The `ordType` is required.
ordType | String | Yes | Order typeconditional: One-way stop orderoco: One-cancels-the-other ordertrigger: Trigger ordermove_order_stop: Trailing ordericeberg: Iceberg ordertwap: TWAP order
-- | -- | -- | --

eg:

```python
symbol = 'ETH/USDT:USDT'
params = {'stop':True,'ordType':'oco'} 
okex.fetch_open_orders(symbol, None, None, params) 
```

**Comment by pachinkopirate** [comment]
omg - works perfectly.  thank you so much!! @sc0Vu
