### ISSUE TITLE
Kucoin taker fee is wrong

### ISSUE THREAD

**Issue by dav1d8** [ccxt/ccxt#16340]
Hi, I found a typo, currently taker fee equals to maker fee in kucoin.js

Please have a look at the following line in the master branch:
https://github.com/ccxt/ccxt/blob/390e4ba33870cbc0183c0bf3657c88d49d3904b8/js/kucoin.js#L635

**Comment by carlosmiei** [comment]
Hello @dav1d8,
thanks for reporting it, will be fixed asap!

**Comment by dav1d8** [comment]
Thanks!
