### ISSUE TITLE
Can't market order using leverage in ByBit

### ISSUE THREAD

**Issue by Osthumus** [ccxt/ccxt#16343]
### Operating System

Windows 11

### Programming Languages

python

### CCXT Version

Latest

### Description

it is a simple test program just to market long but it says insufficient balance but there is clearly enough balance i.e $20 as printed which is enough for that order. Can you please help me point out the problem here. 
I suspect it is trying to open order in spot accout and therefore returning insufficient balance but I am trying to long SOL in future perpetual swap market. Is there any ways I can redirect the code so that it will long instead of trying to buy in spot account.
I have attached picture of my actual code snippet and the error output as well so you can have better idea of what I am talking about. 
![20230105_122711](https://user-images.githubusercontent.com/122043524/210839933-d4cd7879-7650-43c2-a4fc-7dd7f30c8634.jpg)
![20230105_122716](https://user-images.githubusercontent.com/122043524/210839942-3e915e0c-e97c-4ab4-9366-b43870eb80f8.jpg)

Thank you. I appreciate your help.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @Osthumus,

You're using the wrong unified symbol, if you want the linear swap SOL/USDT you should be using `SOL/USDT:USDT` 
Check this out: https://docs.ccxt.com/en/latest/manual.html#consistency-of-base-and-quote-currencies

Additionally, at bybit you can't set the leverage like that, you should call `set_leverage` before placing the order 

Example:
```Python
symbol = "SOL/USDT:USDT"
change_leverage = exchange.set_leverage(10, symbol) # adjust this accordingly
order = exchange.create_order(....)
```

**Comment by Osthumus** [comment]
Okay thanks.
In parms do i use  "leverage": change_leverage 
                               Or "leverage": 10

**Comment by carlosmiei** [comment]
> Okay thanks @carlosmiei . In parms do i use "leverage": change_leverage Or "leverage": 10

@Osthumus inside `params` you don't need to add anything regarding leverage

**Comment by Osthumus** [comment]
@carlosmiei hi mate, I did as you said but I am still getting error.
here is my code.
```
`
symbol = 'BTC/USDT:USDT'
leverage = 4

exchange.set_leverage(leverage, symbol)

order = exchange.create_market_buy_order(symbol, 0.1)
print(order)`
```

And the error I am getting is:
`ccxt.base.errors.BadRequest: bybit {"retCode":140043,"retMsg":"leverage not modified","result":{},"retExtInfo":{},"time":1672957685268}
`

**Comment by radian-rgc** [comment]
Same problem

```
var cc_exchange         = new ccxt.bybit({
    apiKey: apiKey,
    secret: apiSecret,
});    
cc_exchange.options['defaultMarginMode']    = 'isolated'
cc_exchange.options['defaultType']          = 'swap'

try {
    const symbol            = 'BTC/USDT:USDT';
    const leverage          = 10;
    await cc_exchange.setLeverage(leverage, symbol)
} catch(error) {
    return { status: 0,data:null,tag:error.message };
}
```

`bybit {\"retCode\":140043,\"retMsg\":\"leverage not modified\",\"result\":{},\"retExtInfo\":{},\"time\":1676411742144}`
