### ISSUE TITLE
Cryptopia Not Fetching Balance in PHP

### ISSUE THREAD

**Issue by tescoint** [ccxt/ccxt#1634]
- OS: UBUNTU
- Programming Language version: PHP 7.2
- CCXT version: 1.10.912
- Exchange: Cryptopia
- Method: fetch_balance

Trying to fetch balance on cryptopia account but keep getting 
`[Exchange Error] cryptopia {"Success":false,"Error":"Bad Request","Data":null}

**Comment by kroitor** [comment]
Are you using a new API key or an existing one?

**Comment by tescoint** [comment]
A new api key

**Comment by kroitor** [comment]
Are you sure your secret key is correct (no missed symbols at the end of it) ? Also, can you post your code snippet to reproduce it (without the keys), please?

**Comment by tescoint** [comment]
$exchange  = new \ccxt\cryptopia  (array (
								    'apiKey' => $api_key,
								    'secret' => $api_secret,
								    'timeout' => 20000,
								));
try {
$coin = "BTC";
				// var_dump($exchange);die();
			   $balances = $exchange->fetch_balance();
			   $balance = $balances[$coin]['free'];
			   $depositAddress = $exchange->fetch_deposit_address($coin);
			   $depositAddress = $depositAddress['address'];
			} catch (\ccxt\NetworkError $e) {
			    echo '[Network Error] ' . $e->getMessage () . "\n";
			} catch (\ccxt\ExchangeError $e) {
			    echo '[Exchange Error] ' . $e->getMessage () . "\n";
			} catch (Exception $e) {
			    echo '[Error] ' . $e->getMessage () . "\n";
			}

**Comment by tescoint** [comment]
Hey @kroitor were you able to recreate the error?

**Comment by kroitor** [comment]
@tescoint yes, it's a php-only bug, does not appear in JS or Python, working on the fix right now.

**Comment by kroitor** [comment]
Fixed in 1.10.920. Thank you for reporting1

**Comment by tescoint** [comment]
thanks for the quick fix:)
