### ISSUE TITLE
The balance() command worked fine in the previous version, but now it gives an error.

### ISSUE THREAD

**Issue by big100** [ccxt/ccxt#16354]
### Programming Languages

python

### CCXT Version

2.5.36

### Description

exchange.fetch_balance()
An error occurs when using the command.

There is no problem with version 2.0.84

In the latest version, ccxt-2.5.36, a permission error occurs as shown below.
==>>
ccxt.base.errors.PermissionDenied: bybit private api uses /user/v3/private/query-api to check if you have a unified account. The API key of user id must own one of permissions: "Account Transfer", "Subaccount Transfer", "Withdrawal" {"retCode":10005,"retMsg":"permission denied","result":null,"retExtInfo":null,"time":1672971506299}

Is this a bug or is there something I need to do beforehand?

### Code

```
  exchange = ccxt.bybit ({
    "apiKey" : "CDm64",
    "secret" : "7Dgw",
    'enableRateLimit': False,
    'options': {
    'defaultType': 'future'
    }
})
markets = exchange.load_markets()
print('exchange.fetch_balance(): ', exchange.fetch_balance())

```

**Comment by big100** [comment]
After testing several versions,
Up to 2.2.45 is fine.
On 2.2.46 the problem starts happening.

**Comment by frosty00** [comment]
you need to add the permissions to the api key:

"Account Transfer", "Subaccount Transfer", "Withdrawal"

this is because we make a call to the api to check if the account is a unified account or not, as they use different api endpoints.

**Comment by Mehdi-Verfaillie** [comment]
> you need to add the permissions to the api key:
> 
> "Account Transfer", "Subaccount Transfer", "Withdrawal"
> 
> this is because we make a call to the api to check if the account is a unified account or not, as they use different api endpoints.

To fetch balance account, we will need additional permission to our API keys? If yes, this function responsibility is really concerning in addition to providing more permissions than necessary which is dangerous. 

Also, I'm concerned about such breaking changes. I may have missed the information, but I didn't see any announcement about it.

**Comment by big100** [comment]
There is no problem with the permission of the api key I use.
The api key is the same.

The api key is the same, and the latest version caused an error.

**Comment by big100** [comment]
"Account Transfer", "Subaccount Transfer", "Withdrawal"

Do I really need to use Permissions?

This is a problem if you must use this permission.

**Comment by frosty00** [comment]
no you can also set:

```
bybit.options['enableUnifiedMargin'] = true/false
```

to remove the requirement of these permissions

**Comment by big100** [comment]
> 다음을 설정할 수도 있습니다.
> 
> ```
> bybit.options['enableUnifiedMargin'] = true/false
> ```
> 
> 이러한 권한의 요구 사항을 제거하려면

thank you it is solved

**Comment by gshpychka** [comment]
@frosty00 where is that option documented?

**Comment by furryboffin** [comment]
I am having the same problem since upgrading ccxt. I have set the permissions on my API key as described in this thread and I have set the option `enableUnifiedMargin` to `true`, but I continue to get the same error:

```
 Error PermissionDenied: bybit private api uses /user/v3/private/query-api to check if you have a unified account. The API key of user id must own one of permissions: "Account Transfer", "Subaccount Transfer", "Withdrawal" {"retCode":10005,"retMsg":"Permission denied, please check your API key permissions.","result":{},"retExtInfo":{},"time":1677569948461}
```

Note also that this error implies that only one of these permissions is required. (which makes no sense anyway. why should we need these permissions to view balance data?).

**Comment by furryboffin** [comment]
There is a similar thread here: https://github.com/ccxt/ccxt/issues/17004#issuecomment-1449581444
