### ISSUE TITLE
ccxt createOrder with BadSymbol errror

### ISSUE THREAD

**Issue by giang21199z** [ccxt/ccxt#16353]
### ؜

OS: 13.0 (22A380)
Programming Language version: Node v14.21.1
CCXT version: 1.95.43

Hi supporters.
I got an error when I createOrder with symbol BCHUSDT and LINKUSDT, etc..
This is my code example for BCHUSDT case
```
let binanceTransaction: ccxt.Order
try {
      binanceTransaction = await binance.createOrder(
        'BCHUSDT',
        'MARKET',
        'sell',
       10,
      )
    } catch (error) {
      this.logger.debug(`Create Order Binance Failed Reason: ${error}`)
}
```
I got an error bellows
```
Create Order Binance Failed Reason: BadSymbol: binance does not have market symbol BCHUSDT
```
Please help me check or give me some incorrect points.
Thank you.

**Comment by sc0Vu** [comment]
@giang21199z 

You can check whether markets is supported after load markets.

```js
pair = 'xxx/xxx'
try {
  await exchange.loadMarkets()
  try {
    const market = exchange.market(pair)
  } catch (err) {
    // pair not supported
  }
} catch (err) {
  // probably network / credential issue
}
```

Let me know if you have other questions.
