### ISSUE TITLE
fetchOHLCV data order mismatch between exchange

### ISSUE THREAD

**Issue by anandanand84** [ccxt/ccxt#1636]
fetchOHLCV doesn't unify the order of the data. For example Binance, Bittrex lists data in ascending order while GDAX lists data in descending order of timestamp.

- OS: Any
- Programming Language version: 
- CCXT version: 1.10.849
- Exchange: GDAX
- Method: fetchOHLCV

**Comment by kroitor** [comment]
Hi! Sorry, this is a duplicate of these issues:
- https://github.com/ccxt/ccxt/issues/986
- https://github.com/ccxt/ccxt/issues/987
I suggest moving this discussion there. We are working on it, your is much appreciated as always!
