### ISSUE TITLE
Can not fetchTicker and do anything with Bybit

### ISSUE THREAD

**Issue by AlwxDavydov** [ccxt/ccxt#16375]
### Operating System

Windows 10 

### CCXT Version

2.5.47

### Description

Hello, I ran into a problem that I can not receive tickers on bybit. With the rest of the exchanges everything is fine. Baybit is not banned in my country. I already saw a similar problem in the summer, it was corrected later. And now it appears to have reappeared.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @AlwxDavydov,
The code section is empty and we don't have extra info to help us debug it

**Comment by JCoyk** [comment]
I had the same issues and switched exchanges.

**Comment by AnthonyFJGarner** [comment]
Does this help? [https://github.com/ccxt/ccxt/issues/16381](url)

**Comment by carlosmiei** [comment]
> I had the same issues and switched exchanges.

Hey @JCoyk 
What's the ccxt version used? I tested and seems to be working for every market type. 

Can you try to update to the latest version?

**Comment by AlwxDavydov** [comment]
> Does this help? [#16381 (comment)](https://github.com/ccxt/ccxt/issues/16381#issue-1524523254)

Yea, it helped, thank you.

**Comment by carlosmiei** [comment]
@AlwxDavydov @JCoyk Ok I found the issue, it's related to the market type inference, and will be fixed asap!
