### ISSUE TITLE
Kraken futures How to pull PR to my local

### ISSUE THREAD

**Issue by croissantty** [ccxt/ccxt#16376]
Hi, I know kraken futures still not merge yet and look like this [PR](https://github.com/ccxt/ccxt/pull/15133) can do but I not understand how to install this PR to my local ccxt to use? I install ccxt by pip. and Is it available to have like "ccxt1" package separate from original to use in my local?

Don't get me wrong that I'm lazy ass asker. I have search and try some but look like It not to the point and continue going the wrong way.

I know ccxt would merge soon but Who knows. Its good to know something new :)

**Comment by sc0Vu** [comment]
Hi @croissantty 

You probably need to add and sync others ccxt repository to local and build library.

```
$ git remote add kraken-futures xxxxxxxxxxxx.git
$ git fetch kraken-futures
$ git switch -c <branch-name> kraken-futures/<branch-name>
```
