### ISSUE TITLE
Bybit throttled watchOrderBook() returns "handler not found"

### ISSUE THREAD

**Issue by skafendre** [ccxt/ccxt#16378]
### Operating System

Windows 10 Pro 19044.2364

### Programming Languages

JS

### CCXT Version

2.5.51

### Description

Hi,

I'm trying to watch order books changes using watchOrderBook() from CCXT Pro on Bybit. 

I'm following the tutorial https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual#watchOrderBook

Using watchOrderBook() with throttling as mentionned in the documentation, Bybit returns an ExchangeError with 'error:handler not found'. 

Note: 
This same error is thrown when setting up watchOrderBook in real-time mode while using the optional limit parameter.
If no limit is used, then the code works as intended.

### Code

Reproduction:
``` TS
import {pro} from "ccxt"
const bybit = new pro.bybit()

async function watchSymbolThrottled() {
    await bybit.loadMarkets()
    bybit.verbose = true

    const limit = 10
    const symbol = 'XRPUSDT'

    await bybit.watchOrderBook(symbol, limit)
    while (true) {
        console.log(bybit.orderbooks[symbol].limit(limit))
        await bybit.sleep(100)
    }
}

watchSymbolThrottled()

```

CCXT Pro verbose logs:
``` LOG
2023-01-08T02:59:55.234Z connecting to wss://stream.bybit.com/contract/usdt/public/v3
2023-01-08T02:59:55.937Z onUpgrade
2023-01-08T02:59:55.938Z onOpen
2023-01-08T02:59:55.939Z sending { op: 'subscribe', req_id: 1, args: [ 'orderbook.10.XRPUSDT' ] }
2023-01-08T02:59:56.111Z onMessage {
  success: false,
  ret_msg: 'error:handler not found,topic:orderbook.10.XRPUSDT',
  conn_id: '4d8737d7-61c3-4fec-8d3e-0a731ed773be',
  req_id: '1',
  op: 'subscribe'
}
```

**Comment by sc0Vu** [comment]
Hi @skafendre,
It seems they only support limit 1, 50 and 200 for usdt contract (https://bybit-exchange.github.io/docs/derivativesV3/contract/#t-websocketorderbookdepth). 

> Topic:
orderbook.1.{symbol}
orderbook.50.{symbol}
orderbook.200.{symbol}
