### ISSUE TITLE
Symbol Split Error when Cryptopia returns: "GEO/Old/BTC"

### ISSUE THREAD

**Issue by dekermann** [ccxt/ccxt#1637]
Hello there, and thanks for a great library!

So I use the fetch_balance() method and traced the error to:

File "\Python\Python36-32\lib\site-packages\ccxt\cryptopia.py", line 127, in fetch_markets
     base, quote = symbol.split('/')

Cryptopia API seems to return this (somewhere within the call):
{"Id":1328,"Label":"GEO/Old/BTC","Currency":"GeoCoin","Symbol":"GEO_Old","BaseCurrency":"Bitcoin","BaseSymbol":"BTC","Status":"Paused"...more stuff...

- OS: Windows 10
- Programming Language version: Python 3.6.4
- CCXT version: 3.5
- Exchange: Cryptopia
- Method: fetch_balance()

Best Regards, David

**Comment by kroitor** [comment]
@dekermann hi! Sorry, but this bug was fixed a few days ago (current most recent version working normally). As you may know, the ccxt library is under active development, so we ask our users to update frequently. Thx!

**Comment by kroitor** [comment]
https://gitter.im/ccxt-dev/ccxt?at=5a6bddb6ce68c3bc740c0dd4

**Comment by dekermann** [comment]
My bad, thought I was up to date, thanks for the quick response!

**Comment by kroitor** [comment]
@dekermann thx for reporting anyway, let us know if you have any other difficulties! Cheers!
