### ISSUE TITLE
Bybit fetch_spot_tickers - exchange returns dictionary not list

### ISSUE THREAD

**Issue by AnthonyFJGarner** [ccxt/ccxt#16381]
### Operating System

Windows 11

### Programming Languages

python

### CCXT Version

2.2.47

### Description

"tickerList" in line 1733 of bybit.py (line 1738 of the async version) expects a list of dictionaries, each of which is passed one by one to the parser.  Instead `tickerList = self.safe_value(response, 'result', [])` returns a structure of nested dictionaries.

The solution is to amend line 1736 of the async version (and the corresponding line of the synchronous version) as follows: `tickerList = self.safe_value(response['result'], 'list', [])`

Or so it seems to me.

### Code

```
from pprint import pprint
import ccxt  # noqa: E402

exchange = ccxt.bybit({"options":{"defaultType":"spot"}})#'verbose': True,  # for debug output)
exchange.load_markets()

symbols = ["BTC/USDT", "LTC/USDT",]
mysymbols = exchange.fetch_tickers(symbols)

pprint(symbols) 

```

**Comment by carlosmiei** [comment]
Hello @AnthonyFJGarner,

I'm not sure what's the problem here but every `fetch_tickers` returns a dictionary with `symbols` as the keys. Nonetheless, if you are facing an error, I suggest updating your ccxt version to the latest because, most likely, it's fixed there.

**Comment by AnthonyFJGarner** [comment]
Ah. Fixed in the latest version. In the manner I had suggested. Thanks
A
