### ISSUE TITLE
Extending ExchangePro throws TypeError

### ISSUE THREAD

**Issue by TomToms55** [ccxt/ccxt#16392]
### Operating System

Windows11

### Programming Languages

JS

### CCXT Version

2.5.14

### Description

 Extending the class ExchangePro from ccxt shows a TypeError at compilation.
 `TypeError: Class extends value undefined is not a constructor or null`
 
 Extending the class Exchange from ccxt runs fine.

### Code

```js
const { Exchange, ExchangePro } = require("ccxt");

//this works fine
class ExtendedCEX extends Exchange {

}

//this throws TypeError: Class extends value undefined is not a constructor or null
class ExtendedProCEX extends ExchangePro {

}

```

**Comment by sc0Vu** [comment]
Hi @TomToms55 

We export pro under namespace `pro`. You probably can do this:

```JS
const { pro } = require("ccxt");

class ExtendedProCEX extends pro.Exchange {}
```

Let me know if you have any other questions.

**Comment by TomToms55** [comment]
Hey @sc0Vu. Thanks for the quick reply.

Unfortunately that does not fix it and returns the same "TypeError".

**Comment by carlosmiei** [comment]
> Hey @sc0Vu. Thanks for the quick reply.
> 
> Unfortunately that does not fix it and returns the same "TypeError".

Hello @TomToms55, out of curiosity, why would you do that?

**Comment by TomToms55** [comment]
Hey @carlosmiei. 
Not sure how that's relevant to the bug, but the goal of using the keyword `extends` is to use Inheritance. 
>When you want to create a new class and there is already a class that includes some of the code that you want, you can derive >your new class from the existing class. In doing this, you can reuse the fields and methods of the existing class without having >to write (and debug!) them yourself.

Basically I want to create a subclass of Exchange to add my custom logic, override methods and add additional attributes. The code I sent above with an empty class was just for demo/simplification reasons.

(You can read more about inheritance [here](https://docs.oracle.com/javase/tutorial/java/IandI/subclasses.html) or [here](https://www.w3schools.com/js/js_class_inheritance.asp))

Regarding the bug, I believe it might be caused by some circular dependency in ccxt types (?) see [here](https://stackoverflow.com/a/44727578)

**Comment by carlosmiei** [comment]
@TomToms55 I know what inheritance is 🙂 thanks, I was asking about the "purpose" of extending base `Exchange`.

Regarding the issue, it will be fixed here: https://github.com/ccxt/ccxt/pull/16395

**Comment by TomToms55** [comment]
Thank you! That fixes it 🙂
