### ISSUE TITLE
Parsing position error in Bybit derivates v3 

### ISSUE THREAD

**Issue by dmunozfer** [ccxt/ccxt#16402]
### Programming Languages

JS

### CCXT Version

2.5.67

### Description

I have found that ccxt does not correctly parse the position in the API REST derivatives v3 endpoint "/contract/v3/private/private/position/list".

### Code

```

{
    "info": {
        "positionIdx": "0",
        "riskId": "1",
        "symbol": "BTCUSDT",
        "side": "None",
        "size": "0.000",
        "positionValue": "0",
        "entryPrice": "0",
        "tradeMode": "0",
        "autoAddMargin": "0",
        "leverage": "10",
        "positionBalance": "0",
        "liqPrice": "0.00",
        "bustPrice": "0.00",
        "takeProfit": "0.00",
        "stopLoss": "0.00",
        "trailingStop": "0.00",
        "unrealisedPnl": "0",
        "createdTime": "1657872303983",
        "updatedTime": "1673300815901",
        "tpSlMode": "Partial",
        "riskLimitValue": "2000000",
        "activePrice": "0.00",
        "markPrice": "17179.57",
        "cumRealisedPnl": "-15189.76585547",
        "positionMM": "",
        "positionIM": "",
        "positionStatus": "Normal",
        "sessionAvgPrice": "0.00",
        "occClosingFee": "0",
        "avgPrice": "0"
    },
    "symbol": "BTC/USDT:USDT",
    "notional": 0,
    "leverage": 10,
    "contracts": 0,
    "contractSize": 1,
    "markPrice": 17179.57,
    "collateral": 0,
    "marginMode": "isolated",
    "side": "short"
}

```

From API docs https://bybit-exchange.github.io/docs/derivativesV3/contract/#t-dv_myposition:

<html>
<body>

tradeMode | integer | Cross/isolated mode. 0: cross margin mode; 1: isolated margin mode
-- | -- | --

</body>
</html>

In the example CCXT return marginMode="isolated" when it should be "cross".
TradeMode = 0 -> marginMode="cross"

**Comment by sc0Vu** [comment]
Hi @dmunozfer 

We currently check `addAutoMargin` instead of `tradeMode` (the margin mode seems wrong if addAutoMargin is 0, should be cross). I'll fix asap.

**Comment by dmunozfer** [comment]
Thanks 👍👍
