### ISSUE TITLE
Huobi: failure on placing buy-market order

### ISSUE THREAD

**Issue by amid-flice** [ccxt/ccxt#16416]
### Operating System

linux

### Programming Languages

python

### CCXT Version

2.2.40

### Description

Placing a buy-market order on Huobi ends up with `KeyError`. Looks like the issue is located inside `ccxt.huobi.huobi.cost_to_precision()` method: 
```
    def cost_to_precision(self, symbol, cost):
        return self.decimal_to_precision(cost, TRUNCATE, self.markets[symbol]['precision']['cost'], self.precisionMode)
```
Here precision is taken from `markets` dictionary which contains unified symbols as keys. Though `cost_to_precision` is invoked from `create_spot_order()` method with huobi-specific symbol (concatenated lowercased currency codes with no delimiter) passed as an argument. Thus `KeyError` gets raised.
In order to fix the issue `market()` method should be used instead of `markets` dictionary to obtain cost precision.

So my proposal is to update `costToPrecision()` method within source `js/huobi.js` as follows:
```
    costToPrecision (symbol, cost) {
        return this.decimalToPrecision (cost, TRUNCATE, this.market (symbol)['precision']['cost'], this.precisionMode);
    }
```

**Comment by carlosmiei** [comment]
Hello @amid-flice,
Can you please share with us the symbol used + verbose request? (`exchange.verbose = True` before `createo_order`)

**Comment by amid-flice** [comment]
@carlosmiei 
I've make it work finally. The issue actually was in my inattention when reading documentation: I should pass unified symbol to `create_order()` method instead of exchange-specific one - in this case it works like a charm. Sorry for distracting you.
