### ISSUE TITLE
bitget fetchTickers symbol without separator /

### ISSUE THREAD

**Issue by ptfu0** [ccxt/ccxt#16415]
### Operating System

linux

### Programming Languages

python

### CCXT Version

2.4.61

### Description

Hi! Since version 2.4.61 fetchTickers() for bitget exchange returns symbol without separator /

example of fetchTickers() in 2.4.60:
'BONK/USDT': {
  'symbol': 'BONK/USDT',
  'timestamp': 1673346534274,
........

example of fetchTickers() in 2.4.61:
'BONKUSDT': {
  'symbol': 'BONKUSDT',
  'timestamp': 1673346612275,
........

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @ptfu0,
Thanks for reporting it, we will take a look asap
