### ISSUE TITLE
[Binance Future USDⓈ-M] : Whats the time window for 'Time-in-Force' and 'Fill or Kill' orders ? 

### ISSUE THREAD

**Issue by YuxinSUN89** [ccxt/ccxt#16428]
### ؜

Hey Team and Traders, 

I know many of you use 'Time-in-Force' (TIF) and 'Fill or Kill' (FOK) orders to get more control over slippage and trading window.

OS: Mac OS
Programming Language version: Python
CCXT version: 1.84.70

I know the code to submit TIF and FOK orders

```
exchange = ccxt.binance({
    'apiKey' : config.BIAN_API_KEY,
    'secret' : config.BIAN_API_SECRET,
    'enableRateLimit': True, 
    'options': {'defaultType': 'future'},
})
exchange.load_markets()

# Fill or Kill 
fok_params = {
    'timeInForce': 'FOK'
    }
exchange.create_order(symbol='BTC/USDT', type='LIMIT', amount=0.001, price=18000, params=fok_params)

#Time-in-Force
tif_params = {
    'timeInForce': 'GTX'
    }
exchange.create_order(symbol='BTC/USDT', type='LIMIT', amount=0.001, price=18000, params=tif_params)
```

However, I got three questions:

1. What is the time window for FOK order ? 
    i.e. If the order is not executed within **x** second(s), then it will get cancelled.  What is the **x** here ? 
    
2. What is the **expiry time point** for TIF order ?  
    i.e. If the order is not executed by the end of the day (i.e. **23:59:59**   ?), then it will get cancelled ?

3. Can I customize  **expiry time point** for TIF order ? 
    i.e. I want unexecuted limit order to be live in the next 30 minutes . If its still not executed afterwards, then cancel it. 
    How can I do that ? 
    
    
I didnt find the answer in documentation. Any help will be appreciated

**Comment by pcriadoperez** [comment]
Hi @YuxinSUN89 ,

To answer your questions:
1. For FOK I believe this will change by exchange, but it will be in the milliseconds being practically immediate. (https://www.binance.com/en/support/faq/what-are-maker-post-only-order-time-in-force-order-and-iceberg-order-5d3fa5e5709f47e0b5f186b350da1655)

2. and 3. The TIF values you can find here (https://docs.ccxt.com/en/latest/manual.html#timeinforce)
It is not possible to set an expiry time. Therefore if you want to cancel an order after 30 minutes and you are using python I would use an asyncio task or some scheduler. And after creating the order I would create a task to cancel that order with its id after 30 min. Here is a good article on tasks (https://stackoverflow.com/questions/37278647/fire-and-forget-python-async-await/37345564#37345564)

I'll close this issue for now but feel free to reach out with any questions
