### ISSUE TITLE
Exchange Phemex. It is not possible to trade USDT pairs, only USD.

### ISSUE THREAD

**Issue by waplay** [ccxt/ccxt#16431]
### ؜

Perpetual contract using USDT as margin. It is not possible to trade USDT pairs, only USD. 

```
phemex = ccxt.phemex({
    'type': {'defaultType': 'swap'},
    'enableRateLimit': True,
    'apiKey': API_KEY,
    'secret': API_SECRET
})
markets = phemex.load_markets(params={'type':'swap', 'code':'USDT'})
phemex.set_leverage(10, 'BTC/USDT:USDT')
```

Throws an error:
`ccxt.base.errors.ExchangeError: phemex {"code":39999,"msg":"Error in change leverage","data":null}`

Using the symbol "BTC/USDT" gives the same result.

Using the symbol "BTC/USD:USD" works as expected.

Exchange Phemex [Public-Hedged-Perpetual-API](https://github.com/phemex/phemex-api-docs/blob/master/Public-Hedged-Perpetual-API.md) not implemented? Or am I doing something wrong?

**Comment by NeoSephiroth** [comment]
I also haven't been able to place USDT swap orders

**Comment by pcriadoperez** [comment]
Hi @waplay , @NeoSepiroth , I was able to reproduce the issue and will look to solve it along the weekend.
The [Public-Hedged-Perpetual-API](https://github.com/phemex/phemex-api-docs/blob/master/Public-Hedged-Perpetual-API.md) is not implemented but [Public-Contract-API](https://github.com/phemex/phemex-api-docs/blob/master/Public-Contract-API-en.md) is which should allow to setLeverage and place USDT swap orders

**Comment by NeoSephiroth** [comment]
I'm not having issues with leverage, I'm having issues placing simple USDT margined orders and editing the price...
When you think you have fixed it..can you provide a simple script that place a 1 contract order on a perpetual USDT margined contracts and then amends its price?

Like 1 BTCUSDT long contract at limit price 20000 and then amend that order to switch price to 19500 ?

The complete script so that I have just to edit with my private keys...the price can be entered by me ( again id the price now of BTC is 21200 I will enter 21800 and then 21500 or whatever just to test)

Thanks

**Comment by NeoSephiroth** [comment]
@pcriadoperez yes, I'm not using hedge mode at all.

**Comment by NeoSephiroth** [comment]
hi! Any updates of sort?

**Comment by elitwilliams** [comment]
@pcriadoperez watching this topic (USDT margined perps on phemex) as well. thanks for all your hard work on this!

**Comment by aolson659** [comment]
keeping an eye on this one as well! Appreciate the work you guys do

**Comment by carlosmiei** [comment]
@elitwilliams @aolson659 if everything goes well this will be ready in a few days

**Comment by DjToken6** [comment]
Thanks for your work. Any updates on this ?

**Comment by carlosmiei** [comment]
@NeoSephiroth @elitwilliams @aolson659 @DjToken6 @waplay  USDT markets are already available, they were added here: https://github.com/ccxt/ccxt/pull/16911

Let us know if anything!

**Comment by DjToken6** [comment]
> @NeoSephiroth @elitwilliams @aolson659 @DjToken6 @waplay USDT markets are already available, they were added here: #16911
> 
> Let us know if anything!

Thank you sir, Much Appericated.
Everything is working well.

**Comment by DjToken6** [comment]
> @NeoSephiroth @elitwilliams @aolson659 @DjToken6 @waplay USDT markets are already available, they were added here: #16911
> 
> Let us know if anything!

Thanks for the Clarification,
will follow if phemex would make it possible in the near future.
All this fud around USD, dont know if its the best option to trade USD pairs for now

**Comment by galnat** [comment]
Same issue i have

**Comment by klulla** [comment]
Still having some trouble with this. 
python version - 3.11.5
ccxt version 4.0.103
Here is my code:

import ccxt
import pandas as pd
import ta
import time
import sys
from datetime import datetime
import math
import requests
import json





phemex = ccxt.phemex({
    'adjustForTimeDifference': True,
    'enableRateLimit': True,
    "apiKey": '',
    "secret": '',

});


params={"type":"swap","code":"USDT"}
income = float(phemex.fetch_balance(params=params)['info']['data']['account']['accountBalanceRv']) * 0.96

symbol = 'ETH/USDT:USDT'
price = phemex.fetchTicker(symbol)["last"]
print(price)
print((float(income)/float(price))*0.95)
phemex.createOrder('ETH/USDT:USDT','limit','buy',0.1,float(price)*1.0003)
