### ISSUE TITLE
"Place Trailing Stop Order" method is not functionnal for bitget

### ISSUE THREAD

**Issue by payet9744** [ccxt/ccxt#16434]
### Operating System

Ubuntu

### Programming Languages

Python

### CCXT Version

Last one

### Description

The create order function of ccxt do not allow to place a trailing stop order on bitget
It is not possible to add  rangRate : '10' and planType : 'moving_plan' instead of 'normal_plan'

### Code

    @authentication_required
    def place_trailing_stop_loss(self, symbol, side, amount, trigger_price, reduce=False):
        
        try:
            return self._session.createOrder(
                symbol, 
                'market', 
                side, 
                self.convert_amount_to_precision(symbol, amount), 
                self.convert_price_to_precision(symbol, trigger_price),
                params = {
                    'planType': 'moving_plan'
                    'triggerprice': self.convert_price_to_precision(symbol, trigger_price),  # your stop price
                    "triggerType": "market_price",
                    'rangeRate': 10,
                    "reduceOnly": reduce
                }
            )
        except BaseException as err:
            raise Exception(err)

**Comment by samgermain** [comment]
There is no unified way to place trailing stop orders. You need to use the [implicit api method ](https://docs.ccxt.com/en/latest/manual.html#implicit-api)`privateMixPostPlanPlaceTPSL` for bitget. 

These are the bitget api docs for that method

https://bitgetlimited.github.io/apidoc/en/mix/#place-stop-order

**Comment by samgermain** [comment]
Closing this issue. Please reopen if you have any more questions

**Comment by payet9744** [comment]
When trying to use implicit method : 

(tried différent parameters in function below, but not able to get a moving plan (trailing order) in place)

    @authentication_required
    def place_trailing_stop(self, symbol, side, amount, trigger_price, reduce=False):
        try:
            params = {
                'symbol': symbol,  
                'marginCoin': 'USDT',
                'size': self.convert_amount_to_precision(symbol, amount),
                'triggerPrice': self.convert_price_to_precision(symbol, trigger_price),
                "planType" : "moving_plan",
                "holdSide" : 'long',
                "side" : "close_long",
                'rangeRate': 10,
                #"reduceOnly": reduce
            }
            return self._session.private_mix_post_plan_placetpsl(params)
        except BaseException as err:
            raise Exception(err)

When I use private_mix_get_plan_currentplan, the plan order is empty  ({'code': '00000', 'msg': 'success', 'requestTime': '0', 'data': []})

**Comment by lasys** [comment]
give it a try with 
```            
params = {
                "symbol": symbol.uppercased() + "_UMCBL",
                "marginCoin": "USDT",
                "triggerPrice": "124.00",
                "planType": "track_plan",
                "holdSide": "long"
                "rangeRate": "10.0"
            }
```

**Comment by payet9744** [comment]
Thank you, this looks like working
