### ISSUE TITLE
Huobipro withdraw fund has some errors.

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#16443]
### Operating System

Windows 10

### Programming Languages

JS

### CCXT Version

2.5.89

### Description

Hello:
I bought one kind of crypto token: 1SOL at huobipro exchange, and I want to send it to my personal wallet, but I got error message: "API withdrawal does not support temporary addresses"
The same code works for withdraw at Binance exchange, but have issue with both gate and huobipro exchanges.
Please advise on what I can do for this. By the way, I can do withdraw from web page without any issue, but it is rather complicated. So, I prefer to do this via CCXT!
The following is the output for running my code:

C:\CCXT>node huobipro_send1CoinChain1.js 1SOL 3619.4 0x626504956a55fffee8d2c9256ece94d73835ffec undefined ERC20
PermissionDenied: huobipro {"status":"error","err-code":"api-not-support-temp-addr","err-msg":"API withdrawal does not support temporary addresses","data":null}
    at huobipro.throwExactlyMatchedException (C:\CCXT\node_modules\ccxt\js\base\Exchange.js:2400:19)
    at huobipro.handleErrors (C:\CCXT\node_modules\ccxt\js\huobi.js:5737:22)
    at C:\CCXT\node_modules\ccxt\js\base\Exchange.js:603:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (C:\CCXT\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async huobipro.fetch2 (C:\CCXT\node_modules\ccxt\js\base\Exchange.js:2023:16)
    at async huobipro.request (C:\CCXT\node_modules\ccxt\js\base\Exchange.js:2027:16)
    at async huobipro.withdraw (C:\CCXT\node_modules\ccxt\js\huobi.js:5082:26)
    at async send1Coin (C:\CCXT\huobipro_send1CoinChain1.js:26:19) {
  constructor: [class PermissionDenied extends AuthenticationError]

### Code

```
const ccxt = require('ccxt');

if (process.argv.length != 7)
{
console.error('Usage: Coin1 Amount Address (Tag|undefined) (Network|undefined)');
console.error('Send Coin1 to an address with full network data');
console.error('Please try again!');
process.exit(1);
}
const [nodejs, script1, coin1, amount1, address1, tag1, chain1] = process.argv;

let exchange = new ccxt.huobipro
({
apiKey: 'My_AKI_Key',
secret: 'My_Secret_Key',
'options': {
'adjustForTimeDifference': true,
'fetchCurrencies': true,
'verbose': true, }
});

const send1Coin = async (coin1, amount1, address1, tag1, chain1) =>
{
try
{
const transfer1 = await exchange.withdraw(coin1, amount1, address1, tag1, {'network': chain1});
const json_transfer = JSON.stringify(transfer1);
console.log(json_transfer);
}
catch (err)
{
console.error(err);
}
};
send1Coin(coin1, amount1, address1, tag1, chain1);
```

**Comment by sc0Vu** [comment]
Hi @zydjohnHotmail 

Have you added the withdrawal address to whitelist?

**Comment by zydjohnHotmail** [comment]
Hello:
I have searched around, but I can't find how to do this via CCXT, do I have to add the address to whitelist by hand from Huobi web page?
If yes, then this could mean quite some labor, since I may have multiple addresses to add by hand.
Please advise!
