### ISSUE TITLE
bitget batch createOrders 

### ISSUE THREAD

**Issue by maydo7777** [ccxt/ccxt#16440]
- OS: macOS
- Programming Language version: Python 3.10
- CCXT version: 2.5.89

```
import ccxt.async_support as ccxt
await exchange.cancel_orders(ids, symbol, {'marginCoin': marginCoin})

```

```
howto create batch_orders on bitget ?
batch "cancel_orders" is working but not "create_orders"
there is an endpoint for this
POST /api/mix/v1/order/batch-orders
```

**Comment by samgermain** [comment]
There's no unified method of creating batch orders, so you'll need to use the [implicit api method ](https://docs.ccxt.com/en/latest/manual.html#implicit-api)`privateSpotPostTradeBatchOrders`. 

Here is the [bitget api docs](https://bitgetlimited.github.io/apidoc/en/spot/#batch-order) for that method

--------------

[`cancelOrders` on the other hand is a unified method](https://docs.ccxt.com/en/latest/manual.html#canceling-orders)

**Comment by maydo7777** [comment]
yes the implicit method is working
'''
privateMixPostOrderBatchOrders
'''
for swap

**Comment by samgermain** [comment]
> yes the implicit method is working
> 
> `privateMixPostOrderBatchOrders`
> 
> for swap

Great! Closing this issue. Reopen it if you have any more questions

**Comment by Alkem314** [comment]
Hi algo traders ;)

Is it possible to create multiple trigger market orders with integrated stop-loss? 

When I try with the implicit method or with create_orders, my orders are simple market orders that are immediately filled. If I send the exact same list of orders but one by one, I get my trigger orders with stop-loss! Just for example, you can reuse this snippet:

`try:
    orders = [
        {
            'symbol': 'ADA/USDT:USDT', 
            'type': 'market', 
            'side': 'buy', 
            'amount': 20, 
            'price': None, 
            'params': {
                "marginCoin": "USDT", 
                "tradeSide": "Open", 
                "triggerPrice": 0.45, 
                "triggerType": "fill_price", 
                "planType": "normal_plan", 
                "stopLoss": {
                    "triggerPrice": 0.41, 
                    "price": 0.4, 
                    "type": "mark_price"
                }
            }
        },
        {
            'symbol': 'ADA/USDT:USDT', 
            'type': 'market', 
            'side': 'sell', 
            'amount': 20, 
            'price': None, 
            'params': {
                "marginCoin": "USDT", 
                "tradeSide": "Open", 
                "triggerPrice": 0.45, 
                "triggerType": "fill_price", 
                "planType": "normal_plan", 
                "stopLoss": {
                    "triggerPrice": 0.5, 
                    "price": 0.51, 
                    "type": "mark_price"
                }
            }
        }
    ]

    # MULTIPLE ORDERS
    resp_orders = await exchange.create_orders(orders)
    print(f"resp order is {resp_orders}")

    # ONE BY ONE ORDERS
    for order in orders:
        resp_order = await exchange.create_order(order['symbol'], order['type'], order['side'], order['amount'], order['price'], order['params'])
        print(f"resp order is {resp_order}")

except KeyboardInterrupt:
    print("Interrupted by user")
finally:
    await exchange.close()
    print("Exchange connection closed")
`

If anyone can help, I would really appreciate it because I can't figure this out on my own.
