### ISSUE TITLE
Latoken can not get specific token amount, but it shows in total exchange balance

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#16444]
### Operating System

Windows 10

### Programming Languages

JS

### CCXT Version

2.5.89

### Description

Hello:
I send one kind of crypto: 1SOL to my account at Latoken, my code can’t show its value in my account. But the code to show total exchange balance finds the amount without currency name.
Please advise if I made any mistake.  The same code works for Binance, Gate and Huobipro, but not Latoken.
The following is the output for my code to get specific token’s balance:
C:\ArbitApps\CCXT\CCXTNodeByFunctions>node latoken_getCoin1Balance.js 1SOL
{"Ticker":"1SOL","Amount":0}

The following is the output for my code to get my balance in the exchange without currency name:
C:\ArbitApps\CCXT\CCXTNodeByFunctions>node latoken_getExchangeBalance.js
{
  info: [
    {
      id: 'b0e4bc98-49b0-4f9e-952c-3a242c39b8f7',
      status: 'ACCOUNT_STATUS_ACTIVE',
      type: 'ACCOUNT_TYPE_WALLET',
      timestamp: '1673473520129',
      currency: 'e7e442e1-9f23-44df-98c7-06a1e95dc6b0',
      available: '3583.217930846400000000',
      blocked: '0.000000000000000000'
    }
  ],
  timestamp: undefined,
  datetime: undefined,
  free: {},
  used: {},
  total: {}
}

Please advise if I made any mistake.
The following is my code for exchange balance:
const ccxt = require('ccxt');

let exchange = new ccxt.latoken
({
apiKey: 'My_API_Key',
secret: 'My_Secret_Key',
'options': {
'adjustForTimeDifference': true,
'fetchCurrencies': true,
'verbose': false, }
});

async function getExchangeBalance()
{
try
{
const balance = await exchange.fetchBalance();
console.log(balance);
}
catch (err)
{
console.error(err)
}
};
getExchangeBalance();

### Code

```
const ccxt = require('ccxt');

if (process.argv.length != 3)
{
console.error('Usage: Currency1_Balance USDT');
console.error('Get Coin1 balance at exchange');
console.error('Please try again!');
process.exit(1);
 }
const [nodejs, script1, coin1] = process.argv;

let exchange = new ccxt.latoken
({
apiKey: 'My_API_Key',
secret: 'My_Secret_Key',
'options': {
'adjustForTimeDifference': true,
'fetchCurrencies': true,
'verbose': true, }
});


const getCoin1Balance = async(coin1) =>
{
try
{
const dict_money = await exchange.fetchBalance();
const coin1_balance = dict_money.free[coin1];
if (typeof coin1_balance !== 'undefined')
{
const balance1 = ({ 'Ticker': coin1, 'Amount': coin1_balance });
const json_balance1 = JSON.stringify(balance1);
console.log(json_balance1);
}
else
{
const balance0 = ({ 'Ticker': coin1, 'Amount': 0 });
const json_balance0 = JSON.stringify(balance0);
console.log(json_balance0);
}
}
catch (err)
{
console.error(err)
}
};
getCoin1Balance(coin1);
```

**Comment by sc0Vu** [comment]
Hi @zydjohnHotmail 

Because the coin is in `ACCOUNT_TYPE_WALLET`, and the default wallet is `ACCOUNT_TYPE_SPOT`. Please use `await exchange.fetchBalance({'type':'wallet'})` and you'll see `1SOL` in your balance.
