### ISSUE TITLE
Kucoin Futures - 'stopPrice'/'triggerPrice' argument not working

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#16442]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

2.5.89

### Description

Currently I am unable to place a stop market order, as the code below when either using "stopPrice" or "triggerPrice" it immediately triggers the order on Kucoin. 

Please let me know in case I am overlooking something or whether I need to add other arguments to params. As currently below code will just execute a market order. 

### Code

```
import ccxt

public = ""
private = ""
password = ""

client = ccxt.kucoinfutures(
    {'apiKey': public, 'secret': private, 'password': password})

ticker = "BTC/USDT:USDT"
side = "buy"
quantity = 1
price = 18000

order = client.create_order(symbol=ticker, type="market",
                            side=side, amount=quantity,
                            price=None, params={'stopPrice': price})
print(order)

```

When printing the order it also gives the message "Cannot close a position of size 0. " in case the argument "closeOrder": True is provided in params.

**Comment by Dan-krm** [comment]
@Tomas-MP kucoinFutures doesn't support market orders, it needs to be a limit order with the stopPrice being the trigger to create an order for the price.
examples: https://github.com/ccxt/ccxt/blob/master/examples/py/kucoinfutures-create-stop-order.py

**Comment by Tomas-MP** [comment]
Thanks for fixing @samgermain
