### ISSUE TITLE
Which end point is used for Gemini load markets function?

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#16450]
### Operating System

Windows 10

### Programming Languages

JS

### CCXT Version

2.5.90

### Description

Hello:
About 2 days ago, I received an email from Gemini saying that Gemini is Now supporting: Tether (USDT) and Cosmos (ATOM)!
And I logged into Gemini web site, I saw some new trading pairs, including BTC/USDT.  However, using the CCXT load markets function, I can’t find BTC/USDT in the market list. Therefore, I sent an email to Gemini support, and Gemini support asked me which endpoint I am using.
I tested with verbose option for CCXT load markets function, but I can’t see the end point shown.
Can you please check if Gemini is using new end point to including new trading pair, like BTC/USDT.
Before having USDT in trading platform, Gemini is rather useless exchange for me, since I only want to trade Crypto/Crypto pair, but Gemini has only Crypto/FIAT, like BTC/USD; however, since I am based in Europe, the only currencies I can trade is EUR and GBP, which has no trading volume again BTC, so I already delete Gemini from CCXT platform list.  However, since they become smarter knowing that using only EUR, GBP in EU markets, they will do no business at all.
But any way, please advise on which end point the load markets function is using, so I can reply to Gemini support and get more information.
I didn't add output of my code here, since there is no necessary information, like the end point it is querying, showing in the code output window.
Thanks,

### Code

```
const ccxt = require('ccxt');
console.log(ccxt.version);

let exchange = new ccxt.gemini
({
'options': {
'adjustForTimeDifference': true,
'fetchCurrencies': true,
'verbose': true, }
});

async function loadMarkets()
{
try
{
const exchange_markets = await exchange.loadMarkets();
if (typeof exchange_markets !== 'undefined')
{
const json_markets = JSON.stringify(exchange_markets);
console.log(json_markets);
}
else
{
const obj_market0 = ({ 'Data': [] });
const json_markets0 = JSON.stringify(obj_market0);
console.log(json_markets0);
}
}
catch (err)
{
console.error(err)
}
};
loadMarkets();
```

**Comment by carlosmiei** [comment]
Hello @zydjohnHotmail,
Thanks for letting us know, we will add a fix to load the USDT markets asap.
