### ISSUE TITLE
Latoken how to move funds from wallet to spot account?

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#16451]
### Operating System

Windows 10

### Programming Languages

JS

### CCXT Version

2.5.90

### Description

Hello:
Yesterday, I deposited some funds (1SOL) to my wallet account in Latoken exchange, now I can see it via CCXT code, I saw the following output, it seems it went through.

```
C:\ArbitApps\CCXT\CCXTNodeByFunctions>node latoken_actPair1LimitOrder.js sell 1SOL/USDT 0.00609312 3582.81
Place a limit sell oder!
{"id":"74132c4a-827e-401e-939e-ad1f0ba83709","info":{"id":"74132c4a-827e-401e-939e-ad1f0ba83709","clientOrderId":"","message":"order accepted for placing","status":"SUCCESS"},"status":"open","trades":[],"fees":[]}
```

However, until today, I found that the fund (1SOL) is still in wallet account, and if I want to place sell orders, I have to move the fund to spot account. I searched CCXT documents, and I can’t find which function can do this.  And with the fetch open orders function, there is no open orders for such pair 1SOL/USDT.
I think if the funds are not in spot account, the place limit oder function should report error, which is better to users to know there is an issue for placing an order, otherwise, the success message is rather misleading.
Please advise,
Thanks,

The following is my code for placing limit order.

```JavaScript
const ccxt = require('ccxt');
if (process.argv.length != 6) {
    console.error('Usage: buy|sell BTC/USDT Price Amount');
    console.error('Buy|Sell Pair1 at price with amount');
    console.error('Please try again!');
    process.exit(1);
}
const [nodejs, script1, act1, pair1, price1, amount1] = process.argv;

let exchange = new ccxt.latoken
    ({
        apiKey: 'My_API_Key',
        secret: 'My_Secret_Key',
        'options': {
            'adjustForTimeDifference': true,
            'fetchCurrencies': true,
            'verbose': false,
        }
    });


const actPair1LimitOrder = async (act1, pair1, price1, amount1) => {
    try {
        await exchange.loadMarkets();
        switch (act1) {
            case 'buy':
                console.log('Place a limit buy oder!');
                const buy_limit1 = await exchange.createOrder(pair1, 'LIMIT', 'buy', amount1, price1);
                const json_buy = JSON.stringify(buy_limit1);
                console.log(json_buy);
                break;
            case 'sell':
                console.log('Place a limit sell oder!');
                const sell_limit1 = await exchange.createOrder(pair1, 'LIMIT', 'sell', amount1, price1);
                const json_sell = JSON.stringify(sell_limit1);
                console.log(json_sell);
                break;
        }
    }
    catch (err) {
        console.error(err);
    }
};
actPair1LimitOrder(act1, pair1, price1, amount1);
```
### Code

```js
const ccxt = require('ccxt');
console.log(ccxt.version);

if (process.argv.length != 3) {
    console.error('Usage: Fetch_OpenOrder BTC/USDT');
    console.error('Get open orders at exchange');
    console.error('Please try again!');
    process.exit(1);
}
const [nodejs, script1, pair1] = process.argv;

let exchange = new ccxt.latoken
    ({
        apiKey: 'My_API_Key',
        secret: 'My_Secret_Key',
        'options': {
            'adjustForTimeDifference': true,
            'fetchCurrencies': true,
            'verbose': true,
        }
    });


const fetchOpenOrders = async (pair1) => {
    try {
        const open_orders = await exchange.fetchOpenOrders(pair1);
        if (typeof open_orders !== 'undefined') {
            const json_orders = JSON.stringify(open_orders);
            console.log(json_orders);
        }
        else {
            const orders0 = ({ 'Data': [] });
            const json_orders0 = JSON.stringify(orders0);
            console.log(json_orders0);
        }
    }
    catch (err) {
        console.error(err)
    }
};
fetchOpenOrders(pair1);
```

**Comment by hafizatanghardapi** [comment]
> ### Operating System
> Windows 10
> 
> ### Programming Languages
> JS
> 
> ### CCXT Version
> 2.5.90
> 
> ### Description
> Hello: Yesterday, I deposited some funds (1SOL) to my wallet account in Latoken exchange, now I can see it via CCXT code, I saw the following output, it seems it went through. C:\ArbitApps\CCXT\CCXTNodeByFunctions>node latoken_actPair1LimitOrder.js sell 1SOL/USDT 0.00609312 3582.81 Place a limit sell oder! {"id":"74132c4a-827e-401e-939e-ad1f0ba83709","info":{"id":"74132c4a-827e-401e-939e-ad1f0ba83709","clientOrderId":"","message":"order accepted for placing","status":"SUCCESS"},"status":"open","trades":[],"fees":[]}
> 
> However, until today, I found that the fund (1SOL) is still in wallet account, and if I want to place sell orders, I have to move the fund to spot account. I searched CCXT documents, and I can’t find which function can do this. And with the fetch open orders function, there is no open orders for such pair 1SOL/USDT. I think if the funds are not in spot account, the place limit oder function should report error, which is better to users to know there is an issue for placing an order, otherwise, the success message is rather misleading. Please advise, Thanks,
> 
> The following is my code for placing limit order.
> 
> const ccxt = require('ccxt'); if (process.argv.length != 6) { console.error('Usage: buy|sell BTC/USDT Price Amount'); console.error('Buy|Sell Pair1 at price with amount'); console.error('Please try again!'); process.exit(1); } const [nodejs, script1, act1, pair1, price1, amount1] = process.argv;
> 
> let exchange = new ccxt.latoken ({ apiKey: 'My_API_Key', secret: 'My_Secret_Key', 'options': { 'adjustForTimeDifference': true, 'fetchCurrencies': true, 'verbose': false, } });
> 
> const actPair1LimitOrder = async (act1, pair1, price1, amount1) => { try { await exchange.loadMarkets(); switch (act1) { case 'buy': console.log('Place a limit buy oder!'); const buy_limit1 = await exchange.createOrder(pair1, 'LIMIT', 'buy', amount1, price1); const json_buy = JSON.stringify(buy_limit1); console.log(json_buy); break; case 'sell': console.log('Place a limit sell oder!'); const sell_limit1 = await exchange.createOrder(pair1, 'LIMIT', 'sell', amount1, price1); const json_sell = JSON.stringify(sell_limit1); console.log(json_sell); break; } } catch (err) { console.error(err); } }; actPair1LimitOrder(act1, pair1, price1, amount1);
> 
> ### Code
> ```
> const ccxt = require('ccxt');
> console.log(ccxt.version);
> 
> if (process.argv.length != 3)
> {
> console.error('Usage: Fetch_OpenOrder BTC/USDT');
> console.error('Get open orders at exchange');
> console.error('Please try again!');
> process.exit(1);
>  }
> const [nodejs, script1, pair1] = process.argv;
> 
> let exchange = new ccxt.latoken
> ({
> apiKey: 'My_API_Key',
> secret: 'My_Secret_Key',
> 'options': {
> 'adjustForTimeDifference': true,
> 'fetchCurrencies': true,
> 'verbose': true, }
> });
> 
> 
> const fetchOpenOrders = async(pair1) =>
> {
> try
> {
> const open_orders = aprop 
exchange.fetchOpenOrders(pair1);
> if (typeof open_orders !== 'undefined')
> {
> const json_orders = JSON.stringify(open_orders);
> console.log(json_orders);
> }
> else
> {
> const orders0 = ({ 'Data': [] });
> const json_orders0 = JSON.stringify(orders0);
> console.log(json_orders0);
> }
> }
> catch (err)
> {
> console.error(err)
> }
> };
> fetchOpenOrders(pair1);
> ```

**Comment by pcriadoperez** [comment]
Hi @zydjohnHotmail, 
ccxt has a function called transfer() that allows to transfer between different account types. (https://docs.ccxt.com/en/latest/manual.html#transfers)
However Latoken does not offer this through their API, there is a transfer function but its to transfer funds between latoken users (https://api.latoken.com/doc/v2/#tag/Transfer/operation/transferById)
So unfortunately in this case you will have to transfer funds from one account to another using their UI.

With respect to the success message. That message is coming from the exchange and not ccxt, so it means the order should have gone through.

I'll close this issue for now, but feel free to reach out with any other questions
