### ISSUE TITLE
Coinbase new version load markets and fetch tickers show different trading pairs.

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#16476]
### Operating System

Windows 10

### Programming Languages

JS

### CCXT Version

2.6.7

### Description

Hello:
As Coinbase will phrase out old API and migrate to Coinbase advanced trade with new API, I tested latest version of CCXT (version 2.6.7), I can see the load markets function return some new trading pairs, like: BTC/USDT, but using fetch tickers function, I can not find such trading pair: BTC/USDT.
The following is the output of my code:
D:\nodejs\CCXT_Tickers>node coinbase_fetch1Ticker.js BTC/USDT
ExchangeError: coinbase {"errors":[{"id":"not_found","message":"Invalid currency"}]}
    at coinbase.throwExactlyMatchedException (D:\nodejs\CCXT_Tickers\node_modules\ccxt\js\base\Exchange.js:2400:19)
    at coinbase.handleErrors (D:\nodejs\CCXT_Tickers\node_modules\ccxt\js\coinbase.js:1723:30)
    at D:\nodejs\CCXT_Tickers\node_modules\ccxt\js\base\Exchange.js:603:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (D:\nodejs\CCXT_Tickers\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async coinbase.fetch2 (D:\nodejs\CCXT_Tickers\node_modules\ccxt\js\base\Exchange.js:2023:16)
    at async coinbase.request (D:\nodejs\CCXT_Tickers\node_modules\ccxt\js\base\Exchange.js:2027:16)
    at async coinbase.fetchTicker (D:\nodejs\CCXT_Tickers\node_modules\ccxt\js\coinbase.js:1081:22)
    at async fetch1Ticker (D:\nodejs\CCXT_Tickers\coinbase_fetch1Ticker.js:29:17) {
  constructor: [class ExchangeError extends BaseError]
}

From the output of loadMarkets function, I can see BTC/USDT trading pair. The following is my code for loadMarkets:

const ccxt = require('ccxt');

let exchange = new ccxt.coinbase
({
apiKey: 'My_API_Key',
secret: 'My_Secret_Key',
'options': {
'adjustForTimeDifference': true,
'fetchCurrencies': true,
'verbose': false, }
});

async function loadMarkets()
{
try
{
const exchange_markets = await exchange.loadMarkets();
if (typeof exchange_markets !== 'undefined')
{
const json_markets = JSON.stringify(exchange_markets);
console.log(json_markets);
}
else
{
const obj_market0 = ({ 'Data': [] });
const json_markets0 = JSON.stringify(obj_market0);
console.log(json_markets0);
}
}
catch (err)
{
console.error(err)
}
};
loadMarkets();

### Code

```
const ccxt = require('ccxt');

if (process.argv.length != 3)
{
console.error('Usage: BTC/USDT');
console.error('Fetch 1 ticker price');
console.error('Please try again!');
process.exit(1);
}
const [nodejs, script1, pair1] = process.argv;

let exchange = new ccxt.coinbase
({
apiKey: 'My_API_Key',
secret: 'My_Secret_Key',
'options': {
'adjustForTimeDifference': true,
'fetchCurrencies': true,
'verbose': false, }
});

const fetch1Ticker = async(pair1) =>
{
try
{
if (exchange.has['fetchTicker'])
{
await exchange.loadMarkets();
const ticker1 = await exchange.fetchTicker(pair1);
if (typeof ticker1 !== 'undefined')
{
const json_ticker1 = JSON.stringify(ticker1);
console.log(json_ticker1);
}
else
{
const obj_jsonTicker0 = ({ 'Data': []});
const json_ticker0 = JSON.stringify(obj_jsonTicker0);
console.log(json_ticker0);
}
}
}
catch (err)
{
console.error(err)
}
};
fetch1Ticker(pair1);
```

**Comment by carlosmiei** [comment]
Hello @zydjohnHotmail, we're gradually upgrading to the new API and will try to do it as fast as possible.

**Comment by carlosmiei** [comment]
cc/ @Dan-krm

**Comment by zydjohnHotmail** [comment]
Thanks for your quick reply.
Please let me know when the updating is done.
