### ISSUE TITLE
[okx] [fetchPositions] margin position side is wrong

### ISSUE THREAD

**Issue by szmcdull** [ccxt/ccxt#16488]
### Operating System

any

### Programming Languages

JS

### CCXT Version

latest

### Description

currently ccxt okx margin (with "net" posSide) position side is determined by position size (positive/negative). But according to okx documenation (https://www.okx.com/docs-v5/en/#rest-api-account-get-positions), description on the posSide field, margin position side should be determined by posCcy (`MARGIN: posCcy being base currency means long position, posCcy being quote currency means short position`)

### Code

```
  

```

**Comment by szmcdull** [comment]
currently I have short margin position, but ccxt reports  as long position.

**Comment by carlosmiei** [comment]
Hello @szmcdull,
Thanks for letting us know, we will take a look!

**Comment by carlosmiei** [comment]
@szmcdull you're right, this issue will be fixed very soon (1hr). Thanks once again!

**Comment by szmcdull** [comment]
after upgrading, the `contract` field of margin position is None:

```
{
  'info': {
    'adl': '1',
    'availPos': '444.80699999999996',
    'avgPx': '0.043736118604046',
    'baseBal': '',
    'baseBorrowed': '',
    'baseInterest': '',
    'bizRefId': '',
    'bizRefType': '',
    'cTime': '1674060751840',
    'ccy': 'USDT',
    'closeOrderAlgo': [
      
    ],
    'deltaBS': '',
    'deltaPA': '',
    'gammaBS': '',
    'gammaPA': '',
    'imr': '224.64999999999998',
    'instId': 'GALA-USDT',
    'instType': 'MARGIN',
    'interest': '0',
    'last': '0.04487',
    'lever': '1',
    'liab': '-5000',
    'liabCcy': 'GALA',
    'liqPx': '2.654620449481712',
    'margin': '',
    'markPx': '0.04493',
    'mgnMode': 'cross',
    'mgnRatio': '17.253305111930867',
    'mmr': '17.971999999999998',
    'notionalUsd': '218.43132775946995',
    'optVal': '',
    'pendingCloseOrdLiabVal': '',
    'pos': '218.46191242720977',
    'posCcy': 'USDT',
    'posId': '384530099038752792',
    'posSide': 'net',
    'quoteBal': '',
    'quoteBorrowed': '',
    'quoteInterest': '',
    'spotInUseAmt': '',
    'spotInUseCcy': '',
    'thetaBS': '',
    'thetaPA': '',
    'tradeId': '27330796',
    'uTime': '1674060751840',
    'upl': '-6.188087572790209',
    'uplRatio': '-0.0282973787811969',
    'usdPx': '',
    'vegaBS': '',
    'vegaPA': ''
  },
  'id': None,
  'symbol': 'GALA/USDT',
  'notional': 218.43132775946995,
  'marginMode': 'cross',
  'liquidationPrice': 2.654620449481712,
  'entryPrice': 0.043736118604046,
  'unrealizedPnl': -6.188087572790209,
  'percentage': -2.82973787811969,
  'contracts': None,
  'contractSize': None,
  'markPrice': 0.04493,
  'side': 'short',
  'hedged': False,
  'timestamp': 1674060751840,
  'datetime': '2023-01-18T16:52:31.840Z',
  'maintenanceMargin': 17.971999999999998,
  'maintenanceMarginPercentage': 0.0823,
  'collateral': 218.46191242720977,
  'initialMargin': 224.64999999999998,
  'initialMarginPercentage': 1.0284,
  'leverage': 1.0,
  'marginRatio': 0.0822
}
```

**Comment by szmcdull** [comment]
@carlosmiei @kroitor

**Comment by carlosmiei** [comment]
> @carlosmiei @kroitor

@szmcdull Hum, I don't think the changes could have affected that, are you sure `contracts` was defined before the side fix?

**Comment by szmcdull** [comment]
> > @carlosmiei @kroitor
> 
> @szmcdull Hum, I don't think the changes could have affected that, are you sure `contracts` was defined before the side fix?

yes. now the contract field is only assigned in the `else` block

**Comment by carlosmiei** [comment]
> > > @carlosmiei @kroitor
> > 
> > 
> > @szmcdull Hum, I don't think the changes could have affected that, are you sure `contracts` was defined before the side fix?
> 
> yes. now the contract field is only assigned in the `else` block

@szmcdull You're right, it will be fixed asap. Thanks!
