### ISSUE TITLE
New Exchange: Pancakeswap

### ISSUE THREAD

**Issue by Benjam6** [ccxt/ccxt#16484]
### Exchange Name

Pancakeswap

### URL of the Exchange

https://pancakeswap.finance/swap

### URL of the Exchange's API docs

https://github.com/pancakeswap/pancake-info-api

### Why should this exchange be implemented?

There are arbitrage opportunities between DEX's like Pancakeswap and between Binance.

**Comment by ttodua** [comment]
duplicate of: #6337
