### ISSUE TITLE
gateio market order

### ISSUE THREAD

**Issue by cagriKarakulak** [ccxt/ccxt#16494]
### Operating System

windows 10

### Programming Languages

python

### Description

gateio now supports market order but I can't create market order with ccxt

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @cagriKarakulak,
Thanks for letting us know we will check it asap!

**Comment by cagriKarakulak** [comment]
my ccxt version: 2.6.22 but I still can't create a market order.

order = exchange.create_order("BTC/USDT", "market", "buy", qty)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cagri\AppData\Local\Programs\Python\Python311\Lib\site-packages\ccxt\gate.py", line 2963, in create_order
    raise InvalidOrder(self.id + ' createOrder() does not support ' + type + ' orders for ' + market['type'] + ' markets')
ccxt.base.errors.InvalidOrder: gateio createOrder() does not support market orders for spot markets
