### ISSUE TITLE
Key error in ccxtpro.binanceusdm

### ISSUE THREAD

**Issue by LuizDMM** [ccxt/ccxt#16499]
### Operating System

Debian 11

### Programming Languages

python

### CCXT Version

2.6.22

### Description

When I try to run "watch_orders()" using binanceusdm, I'm getting this exception: 

```
File "/home/luizdmm/.pyenv/versions/profitor-3.11.1/lib/python3.11/site-packages/ccxt/pro/binance.py", line 1173, in watch_orders
    url = self.urls['api']['ws'][type] + '/' + self.options[type]['listenKey']
                                               ~~~~~~~~~~~~^^^^^^
KeyError: 'spot'
```

I've written a simplified version of the code to reproduce the issue. I just updated my ccxt, and the code was working before (previous version was 2.1.5). My python version is 3.11.1, and now I'm using ccxt 2.6.22. Is this a bug or do I have to change anything in my code?

### Code

```python3
from asyncio import run

import ccxt.pro as ccxtpro


async def main():
    config = {
        "apiKey": api_key,
        "secret": api_secret,
    }
    exchange = ccxtpro.binanceusdm(config)
    await exchange.load_markets()

    while True:
        received_orders = await exchange.watch_orders()
        print(received_orders)

    await exchange.close()


run(main())
```

**Comment by kroitor** [comment]
@LuizDMM thx for reporting, will fix this bug asap! This issue has been introduced just recently, this is related to the unification of Binance's derivative symbols here: https://github.com/ccxt/ccxt/issues/16306

**Comment by kroitor** [comment]
@LuizDMM please upgrade to CCXT 2.6.24 and let us know if you still have this issue or not, thanks again for your feedback!
