### ISSUE TITLE
Pagination limit

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#16505]
Hello all,

I followed the example given in the documentation to fetch multiples transactions with pagination parameters `since` and `limit`. However, I noticed that when the `limit` parameter is smaller than the amount of objects to retrieve, then the remaining objects aren't retrieved at all.

The example given in the documentation doesnt handle this case because after a bunch of objects have been received then it increments `since`, leaving the remaining objects behind.

What do you think should be the right way to fetch all objects in this specific situation ? 

Thank you,

```
# Python
if exchange.has['fetchOrders']:
    since = exchange.milliseconds () - 86400000  # -1 day from now
    # alternatively, fetch from a certain starting datetime
    # since = exchange.parse8601('2018-01-01T00:00:00Z')
    all_orders = []
    while since < exchange.milliseconds ():
        symbol = None  # change for your symbol
        limit = 20  # change for your limit
        orders = await exchange.fetch_orders(symbol, since, limit)
        if len(orders):
            since = orders[len(orders) - 1]['timestamp'] + 1
            all_orders += orders
        else:
            break
```

**Comment by Kinzowa** [comment]
To be more precise, I tried to fetch BitMEX ledger objects with a limit of 10, and the objects received were 9. As soon as I increased the limit to 20 I received 12 objects. The 3 that were missing are the oldest ones, which make me think that BitMEX counts objects starting from the most recent ones. I did tried with `params={'reverse': True}` but the objects received are the same.

I don't think the problem is related to CCXT but rather with BitMEX. Would love to hear your thoughts about this case.

**Comment by pcriadoperez** [comment]
Hi @Kinzowa , can you provide a verbose output of the code? I think with that we can confirm if it's a ccxt or BitMex issue.

**Comment by Kinzowa** [comment]
Hi @pcriadoperez 

Please find below the verbose output. I think it's a Bitmex related issue but would love to have your thought before closing the ticker. The query below, with `limit` = 10, returns 9 objects, and the query with `limit` = 11 returns 10 objects.

In [19]: len(c.fetch_ledger(since=1673308800000, limit=10))

fetch Request: bitmex GET https://www.bitmex.com/api/v1/user/walletHistory?count=10 RequestHeaders: {'Content-Type': 'application/json', 'api-key': 'aze', 'api-expires': '1674249798', 'api-signature': 'azs', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bitmex GET https://www.bitmex.com/api/v1/user/walletHistory?count=10 200 ResponseHeaders: {'Date': 'Fri, 20 Jan 2023 21:23:14 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie'; Secure, __cf_bm=AA-1674249794-0-Aa0PkhyYE+UeiBz3yOwPG28/AA=; path=/; expires=Fri, 20-Jan-23 21:53:14 GMT; domain=.bitmex.com; HttpOnly; Secure; SameSite=None', 'X-User-ID': '8490', 'X-RateLimit-Limit': '120', 'X-RateLimit-Remaining': '119', 'X-RateLimit-Reset': '1674249794', 'X-Powered-By': 'Profit', 'ETag': 'W/"e82-tRPQyNIq2Dk8yiTpz+t6ETgfCqQ"', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '78cadeb7f942bbaa-FRA', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'} ResponseBody: [{"transactID":"00000000-0000-0000-0000-000000000000","account":0000,"currency":"XBt","network":"","transactType":"UnrealisedPNL","amount":-10348274,"fee":0,"transactStatus":"Pending","address":"XBTUSD","tx":"","text":"","transactTime":null,"walletBalance":445976486,"marginBalance":435628212,"timestamp":null},{"transactID":"00000000-0000-0000-0000-000000000000","account":0000,"currency":"XBt","network":"","transactType":"RealisedPNL","amount":-51739,"fee":0,"transactStatus":"Completed","address":"XBTUSD","tx":"","text":"","transactTime":"2023-01-21T12:00:00.000Z","walletBalance":445976486,"marginBalance":null,"timestamp":"2023-01-21T12:00:00.000Z"},{"transactID":"3d096d41-7ac2-747b-a924-7c073ae08017","account":0000,"currency":"XBt","network":"","transactType":"RealisedPNL","amount":23229,"fee":0,"transactStatus":"Completed","address":"XBTUSD","tx":"53cbdd0d-334d-3916-c849-3335b4d3748e","text":"","transactTime":"2023-01-20T12:00:00.000Z","walletBalance":446028225,"marginBalance":null,"timestamp":"2023-01-20T12:00:00.007Z"},{"transactID":"c8478ced-723e-74bc-57c3-941156e603e0","account":0000,"currency":"XBt","network":"","transactType":"RealisedPNL","amount":-18802,"fee":0,"transactStatus":"Completed","address":"XBTUSD","tx":"aef231cf-01a3-9ed1-f778-ae4ef5839d9b","text":"","transactTime":"2023-01-19T12:00:00.000Z","walletBalance":446004996,"marginBalance":null,"timestamp":"2023-01-19T12:00:00.007Z"},{"transactID":"72339137-b46f-e1d1-612e-a1c4fe226dac","account":0000,"currency":"XBt","network":"","transactType":"RealisedPNL","amount":45827,"fee":0,"transactStatus":"Completed","address":"XBTUSD","tx":"26edbf4c-39b2-1009-f288-dbe29328ef40","text":"","transactTime":"2023-01-18T12:00:00.000Z","walletBalance":446023798,"marginBalance":null,"timestamp":"2023-01-18T12:00:00.059Z"},{"transactID":"521f701d-1375-5154-8ad0-d43547078483","account":0000,"currency":"XBt","network":"","transactType":"RealisedPNL","amount":46242,"fee":0,"transactStatus":"Completed","address":"XBTUSD","tx":"c7e29766-4a85-e15c-6921-28e26c4bcc76","text":"","transactTime":"2023-01-17T12:00:00.000Z","walletBalance":445977971,"marginBalance":null,"timestamp":"2023-01-17T12:00:00.074Z"},{"transactID":"69cc2a69-e5b5-19e2-b4ad-930735b2d64a","account":0000,"currency":"XBt","network":"","transactType":"RealisedPNL","amount":312129,"fee":0,"transactStatus":"Completed","address":"XBTUSD","tx":"b7e0c6cb-4e4b-e37e-181a-0e2e2fcc520b","text":"","transactTime":"2023-01-16T12:00:00.000Z","walletBalance":445931729,"marginBalance":null,"timestamp":"2023-01-16T12:00:00.019Z"},{"transactID":"b1cc5283-bb8b-87ff-a804-7208e18ae726","account":0000,"currency":"XBt","network":"","transactType":"RealisedPNL","amount":-40053,"fee":0,"transactStatus":"Completed","address":"XBTUSD","tx":"0469879f-9d0a-b4a0-e85b-d1836a2b60fb","text":"","transactTime":"2023-01-15T12:00:00.000Z","walletBalance":445619600,"marginBalance":null,"timestamp":"2023-01-15T12:00:00.024Z"},{"transactID":"791ea085-1ee1-62e4-be95-921734fdb74b","account":0000,"currency":"XBt","network":"","transactType":"RealisedPNL","amount":11059860,"fee":0,"transactStatus":"Completed","address":"XBTUSD","tx":"674926dd-2654-031e-09c4-fb7beccfe11a","text":"","transactTime":"2023-01-14T12:00:00.000Z","walletBalance":445659653,"marginBalance":null,"timestamp":"2023-01-14T12:00:00.006Z"},{"transactID":"809bcdfa-7fc8-4230-658c-8c78a1b4a54c","account":0000,"currency":"XBt","network":"","transactType":"RealisedPNL","amount":-9830653,"fee":0,"transactStatus":"Completed","address":"XBTUSD","tx":"37afb035-e60b-e43e-00cc-cd2944c38f98","text":"","transactTime":"2023-01-13T12:00:00.000Z","walletBalance":434599793,"marginBalance":null,"timestamp":"2023-01-13T12:00:00.087Z"}]

Out[19]: 9

In [20]: len(c.fetch_ledger(since=1673308800000, limit=11))

fetch Request: bitmex GET https://www.bitmex.com/api/v1/user/walletHistory?count=11 RequestHeaders: {'Content-Type': 'application/json', 'api-key': 'A', 'api-expires': '1674250387', 'api-signature': 'A', 'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bitmex GET https://www.bitmex.com/api/v1/user/walletHistory?count=11 200 ResponseHeaders: {'Date': 'Fri, 20 Jan 2023 21:33:02 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': 'AWSALBTG=AA+l9+A+A/NRy11w2vILMqsp2M+SKtRHjUFrX08ALeU4hF1ranj/A/wBs; Expires=Fri, 27 Jan 2023 21:33:02 GMT; Path=/, AWSALBTGCORS=A+l9+MUPDtD7wlARv2YNfZNg+A/NRy11w2vILMqsp2M+SKtRHjUFrX08ALeU4hF1ranj/YUfuHudWqbc1fLHviAoa9Z6NewoTA2QeqF0/wBs; Expires=Fri, 27 Jan 2023 21:33:02 GMT; Path=/; SameSite=None; Secure, __cf_bm=iWK5i5JSjHGWUm.rVbS7AzSAawXOjeRV0vMtsO3idRg-1674250382-0-A+PUh4oAFDY=; path=/; expires=Fri, 20-Jan-23 22:03:02 GMT; domain=.bitmex.com; HttpOnly; Secure; SameSite=None', 'X-User-ID': '0000', 'X-RateLimit-Limit': '120', 'X-RateLimit-Remaining': '119', 'X-RateLimit-Reset': '1674250383', 'X-Powered-By': 'Profit', 'ETag': 'W/"1001-1s66UR8CZWZOUMkdnDNT/MXBx8o"', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '78caed183a71bb74-FRA', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'} ResponseBody: [{"transactID":"00000000-0000-0000-0000-000000000000","account":0000,"currency":"XBt","network":"","transactType":"UnrealisedPNL","amount":-10264617,"fee":0,"transactStatus":"Pending","address":"XBTUSD","tx":"","text":"","transactTime":null,"walletBalance":445976486,"marginBalance":435711869,"timestamp":null},{"transactID":"00000000-0000-0000-0000-000000000000","account":0000,"currency":"XBt","network":"","transactType":"RealisedPNL","amount":-51739,"fee":0,"transactStatus":"Completed","address":"XBTUSD","tx":"","text":"","transactTime":"2023-01-21T12:00:00.000Z","walletBalance":445976486,"marginBalance":null,"timestamp":"2023-01-21T12:00:00.000Z"},{"transactID":"3d096d41-7ac2-747b-a924-7c073ae08017","account":0000,"currency":"XBt","network":"","transactType":"RealisedPNL","amount":23229,"fee":0,"transactStatus":"Completed","address":"XBTUSD","tx":"53cbdd0d-334d-3916-c849-3335b4d3748e","text":"","transactTime":"2023-01-20T12:00:00.000Z","walletBalance":446028225,"marginBalance":null,"timestamp":"2023-01-20T12:00:00.007Z"},{"transactID":"c8478ced-723e-74bc-57c3-941156e603e0","account":0000,"currency":"XBt","network":"","transactType":"RealisedPNL","amount":-18802,"fee":0,"transactStatus":"Completed","address":"XBTUSD","tx":"aef231cf-01a3-9ed1-f778-ae4ef5839d9b","text":"","transactTime":"2023-01-19T12:00:00.000Z","walletBalance":446004996,"marginBalance":null,"timestamp":"2023-01-19T12:00:00.007Z"},{"transactID":"72339137-b46f-e1d1-612e-a1c4fe226dac","account":0000,"currency":"XBt","network":"","transactType":"RealisedPNL","amount":45827,"fee":0,"transactStatus":"Completed","address":"XBTUSD","tx":"26edbf4c-39b2-1009-f288-dbe29328ef40","text":"","transactTime":"2023-01-18T12:00:00.000Z","walletBalance":446023798,"marginBalance":null,"timestamp":"2023-01-18T12:00:00.059Z"},{"transactID":"521f701d-1375-5154-8ad0-d43547078483","account":0000,"currency":"XBt","network":"","transactType":"RealisedPNL","amount":46242,"fee":0,"transactStatus":"Completed","address":"XBTUSD","tx":"c7e29766-4a85-e15c-6921-28e26c4bcc76","text":"","transactTime":"2023-01-17T12:00:00.000Z","walletBalance":445977971,"marginBalance":null,"timestamp":"2023-01-17T12:00:00.074Z"},{"transactID":"69cc2a69-e5b5-19e2-b4ad-930735b2d64a","account":0000,"currency":"XBt","network":"","transactType":"RealisedPNL","amount":312129,"fee":0,"transactStatus":"Completed","address":"XBTUSD","tx":"b7e0c6cb-4e4b-e37e-181a-0e2e2fcc520b","text":"","transactTime":"2023-01-16T12:00:00.000Z","walletBalance":445931729,"marginBalance":null,"timestamp":"2023-01-16T12:00:00.019Z"},{"transactID":"b1cc5283-bb8b-87ff-a804-7208e18ae726","account":0000,"currency":"XBt","network":"","transactType":"RealisedPNL","amount":-40053,"fee":0,"transactStatus":"Completed","address":"XBTUSD","tx":"0469879f-9d0a-b4a0-e85b-d1836a2b60fb","text":"","transactTime":"2023-01-15T12:00:00.000Z","walletBalance":445619600,"marginBalance":null,"timestamp":"2023-01-15T12:00:00.024Z"},{"transactID":"791ea085-1ee1-62e4-be95-921734fdb74b","account":0000,"currency":"XBt","network":"","transactType":"RealisedPNL","amount":11059860,"fee":0,"transactStatus":"Completed","address":"XBTUSD","tx":"674926dd-2654-031e-09c4-fb7beccfe11a","text":"","transactTime":"2023-01-14T12:00:00.000Z","walletBalance":445659653,"marginBalance":null,"timestamp":"2023-01-14T12:00:00.006Z"},{"transactID":"809bcdfa-7fc8-4230-658c-8c78a1b4a54c","account":0000,"currency":"XBt","network":"","transactType":"RealisedPNL","amount":-9830653,"fee":0,"transactStatus":"Completed","address":"XBTUSD","tx":"37afb035-e60b-e43e-00cc-cd2944c38f98","text":"","transactTime":"2023-01-13T12:00:00.000Z","walletBalance":434599793,"marginBalance":null,"timestamp":"2023-01-13T12:00:00.087Z"},{"transactID":"11b30815-22bb-f193-cef7-b649c5f71aef","account":0000,"currency":"XBt","network":"","transactType":"RealisedPNL","amount":-424249,"fee":0,"transactStatus":"Completed","address":"XBTUSD","tx":"329b4c18-d759-0cdf-d007-a049ad6972b0","text":"","transactTime":"2023-01-12T12:00:00.000Z","walletBalance":444430446,"marginBalance":null,"timestamp":"2023-01-12T12:00:00.073Z"}]

Out[20]: 10

In [21]:

**Comment by pcriadoperez** [comment]
Hi @Kinzowa, thanks for verbose output. So I found the issue.
Bitmex is returning correctly the last 10 transacrtions. However in both cases the first transaction a has null timestamp, so when filtering by the `since` value it gets filtered out. If you use `since=None` you will get the full list.

Let me know if I can help in any other way
