### ISSUE TITLE
How to fetchCurrencies workes?

### ISSUE THREAD

**Issue by AlwxDavydov** [ccxt/ccxt#16500]
### Operating System

Windows 10 

### Programming Languages

Nodejs

### CCXT Version

2.5.47

### Description

This is not exactly a bug request, more of a question. I'm sorry, I couldn't find the question section. The thing is, I can't get the currency structure. In the documentation, this method is listed as public, but I saw a similar question where the developers said that the structure of the token, the commission and the network can only be obtained with an API key. How can I get Currency Structure? I also tried the example directly from the documentation, but it's most likely for python, or I'm using it incorrectly

### Code

```
  
const ccxt = require("ccxt");

(async function () {
  let binance = new ccxt.binance();
  await binance.loadMarkets;
  let cur= await binance.fetchCurrencies["ETH"];
  console.log(cur);  // undefined
})();

// Example from docs
(async function () {
  let binance = new ccxt.binance();
  await binance.loadMarkets();
  let cur= binance.currencies["ETH"]["fee"];
  console.log(cur);  // undefined
})(); /

//I want this Currency Structure

{
    'id':       'btc',       
    'code':     'BTC',       
    'name':     'Bitcoin',   
    'active':    true,       
    'fee':       0.123,      
    'precision': 8,         
    'deposit':   true      
    'withdraw':  true        
    'limits': {              
        'amount': {
            'min': 0.01,     
            'max': 1000,     
        },
        'withdraw': { ... },
        'deposit': {...},
    },
    'networks': {...}        
    'info': { ... },    
}

**Comment by sc0Vu** [comment]
Hi @AlwxDavydov 

After loadMarkets, you can get currency:

`let cur= binance.currency('ETH')`

**Comment by AlwxDavydov** [comment]
Thank you!
