### ISSUE TITLE
binance fetch_bids_asks not using unified symbols

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#16514]
### Programming Languages

python

### CCXT Version

2.6.24

### Description

Based on my understanding of https://github.com/ccxt/ccxt/issues/16306 - with the below code, i should be getting the new, unified symbols back.

This doesn't seem to be the case with fetch_bids_asks - which still returns the old namings.

I suspect it's just a minor thing that's missing in this method to fix this again ...
as is - it's a quite severe problem as the symbols are different from the rest of the responses.

### Code

``` python

import ccxt
exchange = ccxt.binance({'options': {'defaultType': 'swap'}})
lm = exchange.load_markets()
x = exchange.fetch_bids_asks()
print(x['BTC/USDT'])  # <-- This shouldn't work 
print(x['BTC/USDT:USDT'])  # <-- this does crash with key error
```

**Comment by carlosmiei** [comment]
Hello @xmatthias, yeah that is not expected we will take a look asap
