### ISSUE TITLE
API Key not found on phemex

### ISSUE THREAD

**Issue by jbarber2016** [ccxt/ccxt#16535]
### Programming Languages

python

### CCXT Version

2.6.22

### Description

I created an api key on Phemex, and then plugged into a basic code example.  I can't get this to work at all.  I am not sure what I am missing, but the response header says Miss from cloudfront and also Api Key not found.  

fetch Request: phemex GET https://api.phemex.com/accounts/accountPositions?currency=USD RequestHeaders: {'x-phemex-access-token': ‘XXXXXXXX, 'x-phemex-request-expiry': '1674085017', 'x-phemex-request-signature': '6728e0b71b0eb4133c75d26ab6253e62308aaceb337163915e1590559efee693', 'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: phemex GET https://api.phemex.com/accounts/accountPositions?currency=USD 200 ResponseHeaders: {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '132', 'Connection': 'keep-alive', 'Date': 'Wed, 18 Jan 2023 23:35:58 GMT', 'Server': 'nginx', 'x-phemex-request-tracing': '3b875b74-9ad4-4402-a911-14c654637337', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate, no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Content-Type-Options': 'nosniff, nosniff', 'X-Frame-Options': 'DENY, SAMEORIGIN', 'X-XSS-Protection': '1 ; mode=block, 1; mode=block', 'Referrer-Policy': 'no-referrer, origin-when-cross-origin', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Cache': '**Miss from cloudfront**', 'Via': '1.1 d5b8ff1568ca9900eb00feb643d95cd4.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'BOS50-P1', 'X-Amz-Cf-Id': 'majASjARhXsE1_chttOKH0J-bo3hUSUbUMIS1MlyBFnhaac5x36dZg=='} ResponseBody: {"msg":"**Api key not found** XXXXXXXX","code":10500}

### Code

```
import ccxt
import config as cfg

phemex = ccxt.phemex({
    "enableRateLimit": True,
    "apiKey": cfg.PHEMEX_API_KEY,
    "secret": cfg.PHEMEX_SECRET_KEY,
    "verbose": True
})

params = {'type': 'swap', 'code': 'USD'}
balance = phemex.fetch_balance(params=params)

print(balance)  

```

**Comment by sc0Vu** [comment]
@jbarber2016 

I think X Cache header is from AWS cloudfront service (https://aws.amazon.com/tw/premiumsupport/knowledge-center/cloudfront-x-cachemiss-error/), it hsould be fine. And the api works for me, would you like to check your api key in phemex?

**Comment by jbarber2016** [comment]
@sc0Vu I copied it directly from Phemex.  I don't know exactly what I am doing different.  Under API Management, I choose create new API Key, I select the default option (api.phemex.com).  On the next screen I provide a name, I select Bind IP and enter my public IP address, and give trading permission.  On the next screen I enter my google authenticator code, and then it produces a final screen.  On the final screen I get both ID and API secret.  I copied the API Secret into the API Key of phemex config.  The secret I get from when I first bind google authenticator.  Can you confirm what I did is correct??

**Comment by jbarber2016** [comment]
I finally figured out my issue.  Thank you for your help.
