### ISSUE TITLE
Bybit Derivatives V3 not working

### ISSUE THREAD

**Issue by reddigszymon** [ccxt/ccxt#16534]
### Operating System

Windows

### Programming Languages

python

### CCXT Version

Newest

### Description

After derivatives V3 have been released on Bybit i ccxt does not work for me, i get PermissionDenied, please check your API key permissions, even though I have everything enabled.

Does ccxt support new bybit derivatives v3? Is there any way for me to use bybit? 

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @reddigszymon 

Yes we did support derivatives v3. I'm not sure which api you called, unified margin or contract v3? If it was unified margin api, you have upgrade to unified margin account first.

BTW, would you like to give detail about the request/response (please remove sensitive information)?

**Comment by reddigszymon** [comment]
Hey @sc0Vu I dont really know how to distinguish between the two, here's a sample of how I initialize the exchange on ccxt:

![image](https://user-images.githubusercontent.com/63747414/213391754-44a4dc7e-bd08-4d41-baf9-bd1cae42f7fb.png)

Example call i would like to make (which worked before:

![image](https://user-images.githubusercontent.com/63747414/213391840-4f13eacf-0949-416d-8f1f-0b08ea8f2db0.png)

And the error:

![image](https://user-images.githubusercontent.com/63747414/213391877-b03669ae-c396-4326-a02c-44ca64b20d33.png)

**Comment by carlosmiei** [comment]
Hello @reddigszymon,

Do you have the unified margin in your account? If not, can you please try to provide this option?

```Python
exchange = ccxt.bybit ({
    'options': {
           'enableUnifiedMargin': False
     }
})
```

**Comment by reddigszymon** [comment]
@carlosmiei  unfortunately that does not work - i still get that permission is denied. Any other ideas what can I do? With my last API key my code worked perfectly, but after i had to create a new one (gave it all the permissions) i am stuck.

**Comment by carlosmiei** [comment]
@reddigszymon can you show me what you have here? (no private info pls only the permissions)
![image](https://user-images.githubusercontent.com/43336371/213426918-1269b989-4537-4493-a34c-28b7de156d1c.png)

**Comment by reddigszymon** [comment]
@carlosmiei  no I don't. Seems like I can't create any orders, set leverage or do anything related to futures.

**Comment by carlosmiei** [comment]
> @carlosmiei no I don't. Seems like I can't create any orders, set leverage or do anything related to futures.

Can you share a verbose log trying to place an order or set the leverage? `exchange.verbose=True`

**Comment by carlosmiei** [comment]
@reddigszymon From the log, I noticed you have an outdated version of `ccxt` that still uses the deprecated V2 endpoints. Can you try to upgrade it pls? `pip install --upgrade ccxt` ?

**Comment by reddigszymon** [comment]
It works now, but I had to upgrade ccxt and i had to switch my permissions to write+read in the settings of API

![image](https://user-images.githubusercontent.com/63747414/213450868-b2d19dd7-0aa9-4718-9098-a636821de14c.png)

Thanks :)
