### ISSUE TITLE
Binance isolated margin sapi_post_margin_loan raise error

### ISSUE THREAD

**Issue by nikky78** [ccxt/ccxt#16544]
### CCXT Version

2.6.47

### Description

response = await exchange.sapi_post_margin_loan({
    'asset': 'BTC',
    'amount': "0.001",
    'isIsolated': "TRUE",
    'symbol': 'BTCUSDT'
})

raise AuthenticationError: binance {"code":-1002,"msg":"You are not authorized to execute this request."}

While I manage to send orders in isolated mode.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @nikky78 
Can you check if you have the necessary permissions enabled in your account’s API Management page?
