### ISSUE TITLE
Wex addOrder nonce-Problem

### ISSUE THREAD

**Issue by slothary** [ccxt/ccxt#1654]
Hello,

i try to add a Order on wex and i get the result:
`array(1) { [0]=> string(121) "wex {"success":0,"error":"invalid nonce parameter; on key:1517393213, you sent:'1517393213', you should send:1517393214"}" }`

I did read the manual: https://github.com/ccxt/ccxt/wiki/Manual#overriding-the-nonce
but the patch doesn't work with PHP. Can anyone help me to resolve this issue?

thank you!
Sebastian

**Comment by kroitor** [comment]
@slothary is it a new key? Or you have used it previously?

**Comment by slothary** [comment]
both

**Comment by kroitor** [comment]
Both new (unused) and used? %)

**Comment by slothary** [comment]
yes i had one, who worked with balance() and so on, but addOrder didn't work and i got this message. My Friend told me that i should try to get a new key. I created a new key and tried it out, with the same result.

**Comment by slothary** [comment]
I can get the balance/ticker, data and so on with old or new key, but i can't place a order.

**Comment by kroitor** [comment]
@slothary do you have any rate-limiting enabled? Let me guess, you're fetching balance, and then you're creating an order, right? I mean, before you create an order, there's always another private call in your code, right? Would be much easier to help you if you could provide your minimal code snippet to reproduce the problem, and other info, as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Docs and examples on rate-limiting (just add `array ('enableRateLimit' => true)` to your constructor params:
- https://github.com/ccxt-dev/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#authentication
- https://github.com/ccxt/ccxt/blob/master/examples/php/built-in-rate-limiting-poller.php

Let us know if it doesn't help.

**Comment by slothary** [comment]
you are a live saver! Works just fine! Thank you very much!
Solution: array ('enableRateLimit' => true)
Issue: can be closed.

**Comment by kroitor** [comment]
Ok, let us know if you have any difficulties with it. I'd recommend to read the entire Manual very carefully, as most answers are there: https://github.com/ccxt/ccxt/wiki. Cheers!
