### ISSUE TITLE
Can't get historical funding rates from KUCOINFutures 

### ISSUE THREAD

**Issue by mrgalindo** [ccxt/ccxt#16549]
### Operating System

Mac OS 13.1

### Programming Languages

python

### CCXT Version

2.6.47

### Description

I am trying to get the historical funding rate from KUCOIN Futures. While `kucoin.fetch_funding_rate(symbol="BTC/USDT:USDT")` works, if I try `kucoin.fetch_funding_history(symbol="BTC/USDT:USDT")` I get an empty array

Thank you in advance

### Code

```python
import ccxt
kucoin = ccxt.kucoinfutures({'apiKey': 'xxxxxx',
                             'secret': 'xxxxx',
                             'password': 'xxxxx',
                             })  

h=kucoin.fetch_funding_history(symbol="BTC/USDT:USDT")
```

**Comment by carlosmiei** [comment]
Hello @mrgalindo,
If you turn on the verbose mode, you will see that the exchange itself is returning an empty array, so does not seem related to ccxt, we will try to reach out to them.

**Comment by samgermain** [comment]
@mrgalindo `fetch_funding_history` returns the history of your accounts funding payments. Kucoin makes funding payment exchanges at 4:00, 12:00 and 20:00, so if you haven't held a swap contract position at these times, then you would have had no funding payments exchanged. `fetchFundingRateHistory` is how you get the history of funding rates (not tied to your account), but this method is unimplemented on kucoinfutures because the api does not provide this information

**Comment by mrgalindo** [comment]
Thank you very much for the explanation. It is much clearer now. I would have thought fetchFundingRateHistory is implemented since the following call works:

https://futures.kucoin.com/_api/web-front/contract/XBTUSDTM/funding-rates?reverse=true&maxCount=8

Thanks!!

**Comment by samgermain** [comment]
> @samgermain
> 
> Thank you very much for the explanation. It is much clearer now. I would have thought fetchFundingRateHistory is implemented since the following call works:
> 
> https://futures.kucoin.com/_api/web-front/contract/XBTUSDTM/funding-rates?reverse=true&maxCount=8
> 
> Thanks!!

That endpoint isn't in their api docs. HOw did you find it?

**Comment by mrgalindo** [comment]
> > @samgermain
> > Thank you very much for the explanation. It is much clearer now. I would have thought fetchFundingRateHistory is implemented since the following call works:
> > https://futures.kucoin.com/_api/web-front/contract/XBTUSDTM/funding-rates?reverse=true&maxCount=8
> > Thanks!!
> 
> That endpoint isn't in their api docs. HOw did you find it? I'm trying to see if theres a way that i can send a startAt/since parameter to it

To be honest I forgot how I found it, I had it for a long time in one of my files. 

The "maxCount" Parameter helps you with that but I think it has a 30days limit

**Comment by samgermain** [comment]
> https://futures.kucoin.com/_api/web-front/contract/XBTUSDTM/funding-rates?reverse=true&maxCount=8

The `maxCount` parameter does not help with that, I'm asking for a way to define a timestamp, not a limit

**Comment by mrgalindo** [comment]
> > https://futures.kucoin.com/_api/web-front/contract/XBTUSDTM/funding-rates?reverse=true&maxCount=8
> 
> The `maxCount` parameter does not help with that, I'm asking for a way to define a timestamp, not a limit

I am not sure if I get your point. 

In any case apart from the timestamp (UNIX time stamp) already included in the answer (e.g. timePoint:1675166400000 which would be equivalent to Jan 31 2023 12:00:00 GMT+0000 ) i wouldn't know how to get other data
