### ISSUE TITLE
Huobi fetchBalance of linear error 4002

### ISSUE THREAD

**Issue by Mnemon1k** [ccxt/ccxt#16543]
### Operating System

Windows 10

### Programming Languages

JS

### CCXT Version

2.2.62

### Description

I am trying to fetch Huobi futures account balance and catch error

`
ExchangeError: Huobi {"status":"error","err_code":4002,"err_msg":"The merged cross and isolated margin account for USDT-M futures is unavailable. Please complete the query with linear-swap-api/v3/unified_account_info","ts":1674149112391}
`

Would someone be able to help me?

### Code

```
const balance = await huobiExchange.fetchTotalBalance({
		"defaultType" : "swap",
		"defaultSubType": "linear"
});

```

**Comment by carlosmiei** [comment]
Hello @Mnemon1k, can you please share a verbose (request+response) complete log?

**Comment by Mnemon1k** [comment]
This?

```
/Users/alex/dev/bot/node_modules/ccxt/js/huobi.js:5742
                throw new ExchangeError (feedback);
                      ^
ExchangeError: huobi {"status":"error","err_code":4002,"err_msg":"The merged cross and isolated margin account for USDT-M futures is unavailable.Please complete the query with linear-swap-api/v3/unified_account_info","ts":1674398486181}
    at huobi.handleErrors (/Users/alex/dev/bot/node_modules/ccxt/js/huobi.js:5742:23)
    at /Users/alex/dev/bot/node_modules/ccxt/js/base/Exchange.js:603:51
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (/Users/alex/dev/bot/node_modules/ccxt/js/base/functions/time.js:181:20)
    at async huobi.fetch2 (/Users/alex/dev/bot/node_modules/ccxt/js/base/Exchange.js:2023:16)
    at async huobi.request (/Users/alex/dev/bot/node_modules/ccxt/js/base/Exchange.js:2027:16)
    at async huobi.fetchBalance (/Users/alex/dev/bot/node_modules/ccxt/js/huobi.js:2979:26)
    at async huobi.fetchPartialBalance (/Users/alex/dev/bot/node_modules/ccxt/js/base/Exchange.js:2233:25)
    at async huobi.fetchTotalBalance (/Users/alex/dev/bot/node_modules/ccxt/js/base/Exchange.js:2246:16)
    at async file:///Users/alex/dev/bot/src/CollapseBot.ts:88:22 {
  constructor: [class ExchangeError extends BaseError]

```

**Comment by ttodua** [comment]
@carlosmiei this doesn't seem to be related to newly added endpoints. `unified_account_info` is nowhere mentioned or documented in API docs. 
I think it will need more research. I will need a day  or so.

**Comment by kroitor** [comment]
@Mnemon1k please enable verbose mode and paste your verbose output:

- https://github.com/ccxt/ccxt/wiki/faq#what-is-required-to-get-help
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

```JavaScript
await huobiExchange.loadMarkets()

huobiExchange.verbose = true  // <<<<<<<<<<<<<<<<< after loading the markets

const balance = await huobiExchange.fetchTotalBalance({
		"defaultType" : "swap",
		"defaultSubType": "linear"
});
```

**Comment by Mnemon1k** [comment]
Is it right info?
```

fetch Request:
 huobi POST https://api.hbdm.com/linear-swap-api/v1/swap_cross_account_info?AccessKeyId=1qdmpe4rty-24061045-b8a8ae56-5e8dd&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2023-01-23T10%3A28%3A58&Signature=2qUdxbxfqovHR0aWQ4Yhyln3yUumm63DFg%2FMnhtFMLQ%3D 
RequestHeaders:
 {
  'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36',
  'Content-Type': 'application/json'
} 
RequestBody:
 {} 

handleRestResponse:
 huobi POST https://api.hbdm.com/linear-swap-api/v1/swap_cross_account_info?AccessKeyId=1qdmpe4rty-24061045-b8a8ae56-5e8dd&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2023-01-23T10%3A28%3A58&Signature=2qUdxbxfqovHR0aWQ4Yhyln3yUumm63DFg%2FMnhtFMLQ%3D 200 OK 
ResponseHeaders:
 {
  'Cache-Control': 'no-cache, no-store',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '78dfd87c79e724a4-KBP',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'text/plain;charset=UTF-8',
  Date: 'Mon, 23 Jan 2023 10:28:59 GMT',
  Expires: 'Thu, 01 Jan 1970 00:00:00 GMT',
  Pragma: 'no-cache',
  'Ratelimit-Interval': '3000',
  'Ratelimit-Limit': '72',
  'Ratelimit-Remaining': '71',
  'Ratelimit-Reset': '1674469742115',
  Reqid: 'bab92485dacc2eb33a2f82c373b6cda8',
  'Request-Id': '5397f51d946bd11b6531fe5734ca2644',
  Server: 'cloudflare',
  'Set-Cookie': '__cf_bm=cCgOOgiitB78RlBMPze0uy19FF.ZbV68LGtkwQo1vjY-1674469739-0-AVtvDrvSkjojMCkK+34YWWuQQ2+fvNMJ83OiTB8x2cTcv0UCMhZK2GchwE5E9zhqEHzbnAiExWtCdOsIhFQK/fs=; path=/; expires=Mon, 23-Jan-23 10:58:59 GMT; domain=.hbdm.com; HttpOnly; Secure; SameSite=None',
  'Transfer-Encoding': 'chunked',
  'X-Request-Id': 'bab92485dacc2eb33a2f82c373b6cda8'
} 
ResponseBody:
 {"status":"error","err_code":4002,"err_msg":"The merged cross and isolated margin account for USDT-M futures is unavailable.Please complete the query with linear-swap-api/v3/unified_account_info","ts":1674469739115} 

```

**Comment by kroitor** [comment]
@Mnemon1k yes, thank you! We will try to resolve it asap and will revert back to you here!

**Comment by ttodua** [comment]
@Mnemon1k can you confirm whether the issue has gone away? for me, it works at this moment. I suspect there has been some temporary bug in huobi api.

**Comment by Mnemon1k** [comment]
Hmm, no i still have error

**Comment by ttodua** [comment]
@Mnemon1k did you try to update ccxt (npm update)?

**Comment by carlosmiei** [comment]
Hello @Mnemon1k you did upgrade to the unified margin account right?
Right now, Huobi does not seem to fully support it so we didn't add it yet, but we will follow this matter closely
![image](https://user-images.githubusercontent.com/43336371/214876496-c70112e0-0899-48ab-a84f-3fec3f138241.png)

**Comment by Mnemon1k** [comment]
Oh, i dont understand what is "unified margin account", i dont remeber i doing something like that.
Can you help me i can somehow make it work?

**Comment by ttodua** [comment]
use `await e.contractPrivatePostLinearSwapApiV3SwapSwitchAccountType ({'account_type':1})` before and then re-try.

**Comment by Mnemon1k** [comment]
Yes, its working, thanks.

If i use fetchBalance i have response:
```
{
  info: { status: 'ok', data: [ [Object] ], ts: '1675327573460' },
  free: {},
  used: {},
  total: {}
}

```

And info about balance is in response.info.data. But free, used, total is empty. Its just information for you, may be its valuable. And huobi.fetchFreeBalanse() also return empty response.

But now i have issue with market order on futures, as i understand from another issues its not possible due to the exchange functionality?

**Comment by ttodua** [comment]
@Mnemon1k thanks for your report, I found that there is implementation bug in huobi's balance parser. 
I will fix this today.

**Comment by ttodua** [comment]
@Mnemon1k update the lib and re-try. it is now fixed.

**Comment by ttodua** [comment]
look into this too: https://github.com/ccxt/ccxt/issues/16633
