### ISSUE TITLE
Waves.Exchange fetch_ticker() returns only None:s

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#16554]
### Operating System

Linux Mint

### Programming Languages

python

### CCXT Version

2.6.47

### Description

`fetch_tickers` was recently updated (see issue #16229) to use a new endpoint and `parse_ticker` was updated to support it. `fetch_ticker` however is still using the old endpoint but also the renewed `parse_ticker` and therefore parsing fails and the returned ticker contains only `None` values. `fetch_ticker` should most likely be updated to use the new endpoint as well.

### Code

```
exchange = ccxt.wavesexchange()
print(exchange.fetch_ticker('ETH/BTC'))
```
```
{'symbol': 'ETH/BTC', 'timestamp': None, 'datetime': None, 'high': None, 'low': None, 'bid': None, 'bidVolume': None, 'ask': None, 'askVolume': None, 'vwap': None, 'open': None, 'close': None, 'last': None, 'previousClose': None, 'change': None, 'percentage': None, 'average': None, 'baseVolume': None, 'quoteVolume': None, 'info': {'__type': 'pair', 'data': {'firstPrice': '0.080999', 'lastPrice': '0.08101', 'volume': '3.88023152', 'quoteVolume': '0.3247630715753605', 'high': '0.093', 'low': '0.076', 'weightedAveragePrice': '0.08369682', 'txsCount': '139', 'volumeWaves': '0.00000000000031092682774'}, 'amountAsset': '474jTeYx2r2Va35794tCScAXWJG9hU2HcgxzMowaZUnu', 'priceAsset': '8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS'}}
```

**Comment by carlosmiei** [comment]
Hello @JovianMoon thanks for letting us know, we will fix it asap!
