### ISSUE TITLE
How to check if websocket is still alive

### ISSUE THREAD

**Issue by nikky78** [ccxt/ccxt#16561]
### CCXT Version

2.6.47

### Description

Hi,

There is an issue with the websocket on future:
`future: <Task finished name='Task-32' coro=<watch_orders() done, defined at /main.py:839> 
exception=RequestTimeout('Connection to wss://fstream.binance.com/ws/mykey timed out due to a ping-pong keepalive missing on time')>

Traceback (most recent call last):

  File "/main.py", line 841, in watch_orders
    await gather(*loops)

  File "/main.py", line 819, in watch_symbol_orders
    _orders = await exchange.watch_orders(symbol, params={'type':'future'})

  File "/usr/local/lib/python3.10/dist-packages/ccxt/pro/binance.py", line 1183, in watch_orders
    orders = await self.watch(url, messageHash, message, type)

ccxt.base.errors.RequestTimeout: Connection to wss://fstream.binance.com/ws/mykey timed out due to a ping-pong keepalive missing on time

But I saw this problem many hours after when manually monitoring my orders.

Is there a way to see if the websocket (watch_orders for instance) is still alive please?

### Code

```
  

```

**Comment by pcriadoperez** [comment]
Hi @nikky78 , in this case when the websocket is disconnected, it will throw an error, and then reconnect automatically on the next call to `watch_orders`.
