### ISSUE TITLE
Gate editOrder error

### ISSUE THREAD

**Issue by gokuMaker** [ccxt/ccxt#16579]
### Operating System

Windows

### Programming Languages

JS

### CCXT Version

2.6.36

### Description

When i try to edit my order I get error: 
"label":"INVALID_PARAM_VALUE","message":"Only can chose one of amount or price"}

Even if I leave same amount.

### Code

```
  let result = await exchange.ccxtExchange.createOrder("BTC/USDT", "limit", "buy", 0.0001, 16000, {clientOrderId: "1234"});
    console.log(result);

    let edit = await exchange.ccxtExchange.editOrder(result.id, "BTC/USDT", "limit", "buy", 0.0001, 17000);

```

**Comment by pcriadoperez** [comment]
Hey @gokuMaker , if you wish to change only the price you can send an undefined amount.
```javascript
    let edit = await exchange.ccxtExchange.editOrder(result.id, "BTC/USDT", "limit", "buy", undefined, 17000);
```

**Comment by gokuMaker** [comment]
What to do in case, when I want to change amount and price in the same time?

**Comment by pcriadoperez** [comment]
Unfortunately Gate api only allows to edit one at a time (https://www.gate.io/docs/developers/apiv4/en/#amend-an-order)
So you would have to call editOrder twice, one to edit the price and once to edit the amount.

**Comment by pcriadoperez** [comment]
Hi @gokuMaker , I'll close this issue for now but feel free to reach out with any questions
