### ISSUE TITLE
binancecoinm fetch_positions() returns non standard symbol name for LUNA in sandbox mode

### ISSUE THREAD

**Issue by FredTingey** [ccxt/ccxt#16578]
### Operating System

Linux

### Programming Languages

python

### CCXT Version

2.6.21

### Description

ccxt.bianncecoinm.fetch_positions() (and fetch_positions_risk()) return a non-standard symbol name for LUNAUSD_PERP instead of either a) not returning it at all or b) returning LUNA/USD:LUNA.

However, ccxt.binancecoinm.fetch_account_positions() does not return this symbol at all.

This appears to be driven by the underlying binance call returning LUNA as a symbol for the api call fetchPositionsRisk but not returning it for the api call fetchAccountPositions ??? and in turn, LUNA is no longer included in the markets mapping for safe_symbol() for some reason - so the default 'LUNAUSD_PERP' is returned.

I lost it there... not sure what the correct fix would be in order to respect the unified symbol naming convention.

For now, I will use fetch_account_positions() as it seems 'cleaner'.

The code below shows the #62 symbols (with LUNA) from fetch_positions() and fetch_positions_risk() vs. the #61 symbols returned from fetch_account_positions()

### Code

```
  import ccxt 

config = {
    'apiKey': 'b...c9',
    'secret': '9...2e',
}

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binancecoinm(config)
exchange.set_sandbox_mode(True)
markets = exchange.load_markets()

print("LUNA with non-standard symbol name in fetch_positions()")
positions = exchange.fetch_positions()
print("POSITIONS #", len(positions))
for position in positions:
    if 'LUNA' in position['symbol']:
        print(position['symbol'], position['info']['symbol'])

print("LUNA with non-standard symbol name in fetch_position_risk()")
positions = exchange.fetch_positions_risk()
print("POSITIONS RISK #", len(positions))
for position in positions:
    if 'LUNA' in position['symbol']:
        print(position['symbol'], position['info']['symbol'])

print("The LUNA token does not appear in list for fetch_account_positions()")
positions = exchange.fetch_account_positions()
print("ACCOUNT POSITIONS #", len(positions))
for position in positions:
    if 'LUNA' in position['symbol']:
        print(position['symbol'], position['info']['symbol'])

```

**Comment by carlosmiei** [comment]
Hello @FredTingey, yeah if the market is already delisted and not returned by the API I don't think there's an easy solution on the ccxt side. Can't you handle it on your side easily?

**Comment by FredTingey** [comment]
I can handle it on my side for sure.

I thought it would not be easy as the binance api is giving two different results; one with LUNA the other without. So what to do? Filter to only return what is defined in the market or return what the exchange gives?
