### ISSUE TITLE
ByBit timeframe not the same in documentation

### ISSUE THREAD

**Issue by dawadam** [ccxt/ccxt#16582]
### CCXT Version

2.6.36

### Description

Hi, in the library timeframes of bybit exchange are :

```
{
  '1m': '1',
  '3m': '3',
  '5m': '5',
  '15m': '15',
  '30m': '30',
  '1h': '60',
  '2h': '120',
  '4h': '240',
  '6h': '360',
  '12h': '720',
  '1d': 'D',
  '1w': 'W',
  '1M': 'M',
  '1y': 'Y'
}
```

but [in documentation](https://bybit-exchange.github.io/docs/derivativesV3/unified_margin/#kline-interval-interval), there are :

```
    1 - 1 minute
    3 - 3 minutes
    5 - 5 minutes
    15 - 15 minutes
    30 - 30 minutes
    60 - 1 hour
    120 - 2 hours
    240 - 4 hours
    360 - 6 hours
    720 - 12 hours
    D - 1 day
    W - 1 week
    M - 1 month
```

1 year is too much.

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @dawadam 

After test, the 1 year timeframe works for derivatives endpoint, but I got empty response for mark/index kline data.

Anyway, we'll fix this asap.
