### ISSUE TITLE
Binance Websocket Help Please!

### ISSUE THREAD

**Issue by janstrw13** [ccxt/ccxt#16586]
### ؜

Can you help me... i am switching from Bybit to Binance but i dont know how i can get these 3 Websocket Datas from Binance...
 

- execution stream
- kline stream
- order stream

it would be great if you can help me!
Also i liked the format of bybit websocket like:

ws_linear = usdt_perpetual.WebSocket(
    test=False,
    api_key=Key,
    api_secret=Secret,
    ping_interval=30,  # the default is 30
    ping_timeout=10,  # the default is 10
    domain="bybit"  # the default is "bybit"
)

def handle_message(msg):
    print(msg)
ws_linear.execution_stream(
    handle_message
)

Is it possible to get all of this three via BinanceSpot?

**Comment by sc0Vu** [comment]
@janstrw13 

You can call these function.

```
// execution
binance.watchTrades

// order
binance.watchOrders

// kline
binance.watchOHLCV
```

If you want to subscribe other data stream, please checkout our documentation (https://docs.ccxt.com/en/latest/ccxt.pro.manual.html#unified-api).

**Comment by janstrw13** [comment]
> // order
> binance.watchOrders

Can you please give me an example how this works in python?

**Comment by cryptoCCY** [comment]
sc0Vu was really trying to help with: https://docs.ccxt.com/en/latest/ccxt.pro.manual.html#unified-api
The manual is super helpful.

Examples are fairly easy to find, here: https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro/py
