### ISSUE TITLE
ccxt - bitget change leverage -Error 404

### ISSUE THREAD

**Issue by Olidefo** [ccxt/ccxt#16591]
### Operating System

windows 11 pro

### Programming Languages

python

### CCXT Version

2.5.36

### Description

Hi all,

I made the following code to change leverage param with ccxt on bitget exchange but got an error message that i cannot solve.
I already tried a lot of othe rdev possibilities but nothing work at all.

Can someone help me in this long dark tunnel for me ?
thx

The following code give me "<Response [404]>"

### Code

api_key = xxx
secret_key =xxx
PASSPHRASE = xxx
account_id = xxx
new_leverage = ?

timestamp = str(int(time.time() * 1000))
method = 'PUT'
path = '/leverage'
query_string = 'account_id=' + account_id + '&leverage=' + str(new_leverage)
message = method + path + timestamp + query_string
signature = hmac.new(bytes(secret_key, 'latin-1'), msg=bytes(message, 'latin-1'), digestmod=hashlib.sha256).hexdigest().upper()
headers = {'Content-Type': 'application/json', 'FC-ACCESS-KEY': api_key, 'FC-ACCESS-SIGNATURE': signature, 'FC-ACCESS-TIMESTAMP': timestamp}

url = 'https://api.bitget.com'+path+'?'+query_string
response = requests.put(url, headers=headers)

print(response.status_code)
print(response.json())

**Comment by sc0Vu** [comment]
Hi @Olidefo 

You can use `bitget.setLeverage (leverage, symbol` in ccxt.

**Comment by Olidefo** [comment]
Thx for your so quick response ...
But I cannot follow your idea.
I tried to install this library "pip install bitget" or "bitget-python" but the package does not exist !

Any idea ?

**Comment by sc0Vu** [comment]
Oh I mean bitget in ccxt. Have you installed ccxt (https://docs.ccxt.com/en/latest/install.html#id1)?

**Comment by Olidefo** [comment]
yes !
but i read so many docs that i don't see clearly what i should do ... i'm sorry :(

**Comment by sc0Vu** [comment]
We have some examples, not sure whether you use async or not:

https://github.com/ccxt/ccxt/blob/master/examples/py/bitget-perpetual-futures-swaps.py

https://github.com/ccxt/ccxt/blob/master/examples/py/binance-futures-set-leverage.py

**Comment by Olidefo** [comment]
so many kind of you !
i wil test this and come back to you
;-)

**Comment by Olidefo** [comment]
Hello
I did the following:

    try:

        markets = exchange.load_markets()

        # exchange.verbose = True  # uncomment for debugging purposes if necessary

        # fetching balance
        balance = exchange.fetch_balance()
        print('++++', balance['total'])

        # placing a limit order
        #symbol = 'ETH/USDT:USDT'
        #type = 'limit'
        #side = 'buy'
        #amount = 1  # how many contracts to buy or sell, integer number of contracts
        #price = 3000
        #order = exchange.create_order(symbol, type, side, amount, price)
        #print(order)
        # placing a market order
        symbol = 'ETH/USDT:USDT'
        type = 'market'
        side = 'sell'
        amount = 0.01  # how many contracts to buy or sell, integer number of contracts
        order = exchange.create_order(symbol, type, side, amount)
        print(order)

        exchange.setLeverage (7, symbol)

    except Exception as e:
        print(type(e).__name__, str(e))


main()


but I got the followin: (the buy has bee successfully done, but the set leverage failed)

1. TEST in Spyder (Anaconda)

++++ {'USDT': None}
{'info': {'clientOid': 'CCXT#6caed7efd8a1fb57551117', 'orderId': '1001390304617181185'}, 'id': '1001390304617181185', 'clientOrderId': 'CCXT#6caed7efd8a1fb57551117', 'timestamp': None, 'datetime': None, 'lastTradeTimestamp': None, 'symbol': None, 'type': None, 'timeInForce': None, 'postOnly': None, 'side': None, 'price': None, 'stopPrice': None, 'average': None, 'cost': None, 'amount': None, 'filled': None, 'remaining': None, 'status': None, 'fee': None, 'trades': [], 'fees': []}
Traceback (most recent call last):

  File "C:\Users\Mediamonster\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 621, in fetch
    response.raise_for_status()

  File "C:\Users\Mediamonster\anaconda3\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

HTTPError: 400 Client Error: Bad Request for url: https://api.bitget.com/api/mix/v1/account/setLeverage


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\Mediamonster\Desktop\Cryptos\setleverage.py", line 46, in main
    exchange.setLeverage (7, symbol)

  File "C:\Users\Mediamonster\anaconda3\lib\site-packages\ccxt\bitget.py", line 3269, in set_leverage
    return self.privateMixPostAccountSetLeverage(self.extend(request, params))

  File "C:\Users\Mediamonster\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 501, in inner
    return entry(_self, **inner_kwargs)

  File "C:\Users\Mediamonster\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 2785, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)

  File "C:\Users\Mediamonster\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 2782, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File "C:\Users\Mediamonster\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 637, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File "C:\Users\Mediamonster\anaconda3\lib\site-packages\ccxt\bitget.py", line 3454, in handle_errors
    raise ExchangeError(feedback)  # unknown message

ExchangeError: bitget {"code":"40808","msg":"Parameter verification exception double fixed, hold side is null","requestTime":1674475974594,"data":null}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\Mediamonster\Desktop\Cryptos\setleverage.py", line 52, in <module>
    main()

  File "C:\Users\Mediamonster\Desktop\Cryptos\setleverage.py", line 49, in main
    print(type(e).__name__, str(e))

TypeError: 'str' object is not callable



2. TEST from a dos box directly with Python:

++++ {'USDT': None}
{'info': {'clientOid': '1001391557740998659', 'orderId': '1001391557711638529'}, 'id': '1001391557711638529', 'clientOrderId': '1001391557740998659', 'timestamp': None, 'datetime': None, 'lastTradeTimestamp': None, 'symbol': None, 'type': None, 'timeInForce': None, 'postOnly': None, 'side': None, 'price': None, 'stopPrice': None, 'triggerPrice': None, 'average': None, 'cost': None, 'amount': None, 'filled': None, 'remaining': None, 'status': None, 'fee': None, 'trades': [], 'fees': []}
Traceback (most recent call last):
  File "C:\Users\Mediamonster\_Python\Lib\site-packages\ccxt\base\exchange.py", line 622, in fetch
    response.raise_for_status()
  File "C:\Users\Mediamonster\_Python\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.bitget.com/api/mix/v1/account/setLeverage

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mediamonster\Desktop\Cryptos\setleverage.py", line 46, in main
    exchange.setLeverage (7, symbol)
  File "C:\Users\Mediamonster\_Python\Lib\site-packages\ccxt\bitget.py", line 3274, in set_leverage
    return self.privateMixPostAccountSetLeverage(self.extend(request, params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mediamonster\_Python\Lib\site-packages\ccxt\base\exchange.py", line 502, in inner
    return entry(_self, **inner_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mediamonster\_Python\Lib\site-packages\ccxt\base\exchange.py", line 2813, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mediamonster\_Python\Lib\site-packages\ccxt\base\exchange.py", line 2810, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mediamonster\_Python\Lib\site-packages\ccxt\base\exchange.py", line 638, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mediamonster\_Python\Lib\site-packages\ccxt\bitget.py", line 3488, in handle_errors
    raise ExchangeError(feedback)  # unknown message
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ccxt.base.errors.ExchangeError: bitget {"code":"40808","msg":"Parameter verification exception double fixed, hold side is null","requestTime":1674476273396,"data":null}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mediamonster\Desktop\Cryptos\setleverage.py", line 52, in <module>
    main()
  File "C:\Users\Mediamonster\Desktop\Cryptos\setleverage.py", line 49, in main
    print(type(e).__name__, str(e))
          ^^^^^^^
TypeError: 'str' object is not callable

**Comment by sc0Vu** [comment]
Hi @Olidefo 

Due to you used fixed margin mode, you need to set `holdSide` in parameters (https://bitgetlimited.github.io/apidoc/en/mix/#change-leverage) eg `{'holdSide': 'long'}`.

**Comment by Olidefo** [comment]
Dear
So many thanks !
It works fine !!
:)
Super thanks for your help: straight to the point and super fast
