### ISSUE TITLE
Timestamp error ccxt binance.... nothing works 

### ISSUE THREAD

**Issue by janstrw13** [ccxt/ccxt#16617]
### ؜

![image](https://user-images.githubusercontent.com/119401920/214338864-fb9be9eb-5b24-4362-9595-1ea384ad42d0.png)

**Comment by kroitor** [comment]
@janstrw13 there is no `time` function or property on the exchange instance, so it is done differently:

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'options': {
        'adjustForTimeDifference': True,
    },
})
markets = exchange.load_markets()
exchange.verbose = True
balance = exchange.fetch_balance()
print(balance)
```

Let us know if that does not help. Make sure that your API key is correct and you've set the correct permissions on the exchange website.

**Comment by kroitor** [comment]
Duplicate issues:
- https://github.com/ccxt/ccxt/search?q=1000ms+ahead&type=issues

**Comment by janstrw13** [comment]
> @janstrw13 there is no `time` function or property on the exchange instance, so it is done differently:
> 
> ```python
> import ccxt
> print('CCXT Version:', ccxt.__version__)
> exchange = ccxt.binance({
>     'apiKey': 'YOUR_API_KEY',
>     'secret': 'YOUR_SECRET',
>     'options': {
>         'adjustForTimeDifference': True,
>     },
> })
> markets = exchange.load_markets()
> exchange.verbose = True
> balance = exchange.fetch_balance()
> print(balance)
> ```
> 
> Let us know if that does not help. Make sure that your API key is correct and you've set the correct permissions on the exchange website.

That does not work... Same error now when load_markets ....
API Keys are correct!

**Comment by nikolabate** [comment]
The same issue here!

**Comment by ManutdGTA** [comment]
the same issue!

**Comment by Pipe-Vash** [comment]
If you are using WSL2, you may want to sync its time also.... That worked for me.
