### ISSUE TITLE
Missing latest versions of CCXT in JavaScript with NPM/Node.js

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#16633]
Hello dear CCXT users!

This is an urgent announcement on the JavaScript version of CCXT in NPM for Node.js. **It does not affect Python or PHP users.**

We experience a temporary difficulty publishing new JavaScript versions of CCXT to the [NPM registry](https://www.npmjs.com/package/ccxt). That is the reason for a discrepancy between the latest version of CCXT for JavaScript (2.6.36) and the versions of CCXT for the other languages we support, like Python (2.6.87).

The technical cause of the issue is blunt and stupid – we've exceeded the NPM registry space quota. We've suddenly ran out of space, put shortly. 

We cannot publish new versions of CCXT to the NPM unless we get more space from NPM or drop some of the old versions dating back 2 years or more to make room for the new versions. The problem with purging old versions is that [NPM's unpublish policy](https://docs.npmjs.com/policies/unpublish) disallows unpublishing older versions in certain cases like ours.
So, it's a closed loop, cannot upload new JavaScript versions to NPM cause there's no space left, and cannot delete the old versions to free up some space either.

We have reached out to the NPM support on this issue and we're in the process of resolving it with them, but that might take a few days to fix. In the meantime, publishing the new versions of CCXT with NPM/Node.js is blocked.  Please, subscribe to [this announcement on GitHub](https://github.com/ccxt/ccxt/issues/16633) to get notified when a new version of CCXT is published with NPM. The GitHub announcement will be closed when we solve the problem.

If you are a JavaScript developer using CCXT with Node.js and you would like to have the latest version of CCXT with all the most recent edits and updates – you can do that by cloning it from GitHub and installing it from your working directory:

```
git clone --depth=1 https://github.com/ccxt/ccxt.git
cd ccxt
npm install
npm link
cd path/to/your/node/project
npm link ccxt
```

Thank you for your understanding!

Yours, CCXT Dev Team

**Comment by zydjohnHotmail** [comment]
Hello:
Do you have any ETA for this issue?
Please advise,
Thanks,

**Comment by carlosmiei** [comment]
> Hello: Do you have any ETA for this issue? Please advise, Thanks,

Hello @zydjohnHotmail,
We're waiting for the npm team to fix the issue, hopefully it will be resolved in the next couple of days

**Comment by alxtz** [comment]
I wonder if there's a better short term solution other than massive un-publishing. CI & production build breaks immediately from this (could stop publishing before npm fixes this be better?)

**Comment by kroitor** [comment]
Hello dear users! At this time we have asked the tech support of NPM to manually unpublish some of our old versions to free up some space for the new updates. We are now able to publish to the NPM registry again, and the JS version of CCXT has been updated to 2.7+ at NPM. We are still in contact with the NPM support to help us finish resolving this issue and to avoid it in the future.

**Comment by adamsoffer** [comment]
This is affecting all my github workflows / actions. Any suggestion on how to resolve in the mean time?

<img width="965" alt="CleanShot 2023-02-15 at 12 33 24@2x" src="https://user-images.githubusercontent.com/555740/219107977-f015e68e-795e-451f-9d87-fddae5390796.png">

**Comment by adamsoffer** [comment]
@carlosmiei thanks. Thing is I'm not using this dependency anywhere in my project. I think github is using it in one of its actions? Here's the github workflow I'm using: https://github.com/web3index/web3index-org/blob/main/.github/workflows/arweave.yml

**Comment by HartS** [comment]
Could ccxt in the future build the "core" and each exchange library as separate, scoped packages, e.g. `@ccxt/core`, `@ccxt/binance`, `@ccxt/kraken`? This might reduce the overall size of ccxt for users, make it more friendly for inclusion in the browser and also avoid going over the size limit for any individual package

**Comment by carlosmiei** [comment]
> Could ccxt in the future build the "core" and each exchange library as separate, s

Hello @HartS, thanks for your suggestion. We're also working on the ESM migration, so it could help on that matter too.

**Comment by carlosmiei** [comment]
@dorienh Can you check if your package.json has a specific version of ccxt pinned? That would prevent the upgrade.

**Comment by dorienh** [comment]
Oh, yes heh, that would indeed prevent it...

**Comment by 6642248687** [comment]
Ok
