### ISSUE TITLE
How to create a trailing stop order on Binance SPOT MARKET

### ISSUE THREAD

**Issue by ali-han** [ccxt/ccxt#16632]
### Programming Languages

php

### CCXT Version

latest

### Description

Hi, I want to create a trailing stop order on spot for Binance, however, I can not find any example on CCXT or official documentation.

Please HELP ;)

How to Use Spot Trailing Stop Order: https://www.binance.com/en/support/faq/how-to-use-spot-trailing-stop-order-339635f6260d43c5aefa4c3c921728ec

Binance API Docs. > Spot Trailing Stop order FAQ: https://github.com/binance/binance-spot-api-docs/blob/master/faqs/trailing-stop-faq.md

**Comment by carlosmiei** [comment]
Hello @ali-han,
I will post an example soon.

**Comment by carlosmiei** [comment]
Hello @ali-han,
You can check this example now: https://github.com/ccxt/ccxt/blob/master/examples/php/binance-spot-trailing.php, but please bear in mind that you need the latest ccxt version to make it work.
