### ISSUE TITLE
Request: add a flag in the exchange indicating if we can create orders at market price (type == 'market')

### ISSUE THREAD

**Issue by LaurentIsRunning** [ccxt/ccxt#1664]
Request: add a flag in the exchange indicating if we can create orders at market price (type == 'market')
Suggestion : exchange.has['createMarketOrder']

- OS: WIndows 10
- Programming Language version: Python
- CCXT version: 1.10.914
- Exchange:lakeBTC
- Method: createOrder

**Comment by LaurentIsRunning** [comment]
Thank you very much for your answer!

The emulation is not straightforward to me, maybe I dont have the right approach...
It seems to me that I have to check the market depth, analyse the volumes of the existing orders and place a limit orders accordingly. 

Is it correct or is there an easiest way to emulate it?

**Comment by kroitor** [comment]
Depends on the exchange, but most of the time a market sell can be emulated with a limit sell at a very low price – the exchange will automatically make it a taker order for market price (the price that is in your best interest currently from the ones that are available in the order book). And the opposite is also true – a market buy can be emulated with a limit buy for a very high price. Most  exchanges will again close your order at best available price, that is, the market price. However, you should test it first. You can even try that in their web interface first to verify the logic.

**Comment by LaurentIsRunning** [comment]
Thank you very much for your super fast ad clear answer!!
