### ISSUE TITLE
fetch_ticker got KeyError: 'index' 

### ISSUE THREAD

**Issue by croissantty** [ccxt/ccxt#16656]
### Operating System

windows

### Programming Languages

python

### CCXT Version

2.7.1

### Description

I has use PR#15133. before This everything working fine Then suddenly This error came from nowhere. I has test an other function and They still working fine except fecth_ticker

```
exchange = ccxt.krakenfutures({
    'apiKey': api_key,
    'secret': api_secret
})

ticker = exchange.fetch_ticker('XRP/USD:USD')
print(ticker)
```

```
 Traceback (most recent call last):
  File "c:\Users\user\Desktop\Kraken_fu\testo.py", line 39, in <module>
    ticker = exchange.fetch_ticker('XRP/USD:USD')
  File "c:\Users\user\Desktop\Kraken_fu\ccxt\base\exchange.py", line 3143, in fetch_ticker 
    tickers = self.fetch_tickers([symbol], params)
  File "c:\Users\user\Desktop\Kraken_fu\ccxt\krakenfutures.py", line 476, in fetch_tickers 
    return self.parse_tickers(tickers, symbols)
  File "c:\Users\user\Desktop\Kraken_fu\ccxt\base\exchange.py", line 3405, in parse_tickers
    ticker = self.extend(self.parse_ticker(tickers[i]), params)
  File "c:\Users\user\Desktop\Kraken_fu\ccxt\krakenfutures.py", line 515, in parse_ticker  
    baseVolume = volume if (not market['index'] and market['linear']) else None
KeyError: 'index' 
```

**Comment by AlgoQ** [comment]
Hi @croissantty,

We are still implementing kraken futures in this [PR](https://github.com/ccxt/ccxt/pull/15133). 
If you already want to use the PR check out this [issue](https://github.com/ccxt/ccxt/issues/16376).

**Comment by croissantty** [comment]
Yes, I understand That PR#15133 is implementing. That issue#16376 was also my post. Sorry that I am annoying and misrepresentation.

I mean I already pull and used PR#15133. Everything was working fine until yesterday something wrong happen with fetch_ticker even I didn't touch anything. This is first time I experiencing this(I has use so many exchange) so I try to ask because kraken futures still return the same everything. I don't sure If other people pulled This PR are experiencing this or just me?

fetch_ticker show That error with even correct symbol. other function still working fine by the way

**Comment by AlgoQ** [comment]
Sorry I didn't notice, I will look into it

**Comment by AlgoQ** [comment]
Hi @croissantty,

Are you using the latest version of this PR? Also can you send the full verbose?
I just tried it out and everything seems to work fine:
```js
Python v3.10.6
CCXT v1.93.108
krakenfutures.fetchTicker(XRP/USD:USD)
{'ask': 0.40382,
 'askVolume': 2322.0,
 'average': 0.40167,
 'baseVolume': 10642922.0,
 'bid': 0.40366,
 'bidVolume': 1350.0,
 'change': 0.00328,
 'close': 0.40331,
 'datetime': '2023-01-31T17:05:27.233Z',
 'high': None,
 'info': {'ask': '0.40382',
          'askSize': '2322',
          'bid': '0.40366',
          'bidSize': '1350',
          'fundingRate': '0.000001506195876028',
          'fundingRatePrediction': '0.0000022916595625',
          'indexPrice': '0.40359',
          'last': '0.40331',
          'lastSize': '18514',
          'lastTime': '2023-01-31T17:05:27.233Z',
          'markPrice': '0.40367',
          'open24h': '0.40003',
          'openInterest': '1250679.00000000',
          'pair': 'XRP:USD',
          'postOnly': False,
          'suspended': False,
          'symbol': 'pf_xrpusd',
          'tag': 'perpetual',
          'vol24h': '10642922',
          'volumeQuote': '4205614.75348'},
 'last': 0.40331,
 'low': None,
 'open': 0.40003,
 'percentage': 0.819938504612154,
 'previousClose': None,
 'quoteVolume': None,
 'symbol': 'XRP/USD:USD',
 'timestamp': 1675184727233,
 'vwap': None}
```

**Comment by croissantty** [comment]
This must be joking. I swear to god I didn't touch or try to update anything. I just leave it there after I report an error because I have tried everything I know. After I saw your response so I try to check and now It is completely running normal like nothing happend... wtf is this

So now fetchticker can do it's job like it use to be... I'm sure something change but I do not know

Thank you for your help. I really forget to report verbose log before That will help the issue. Damn I really look like an idiot. I swear I didn't try to annoy you guys here

by the way the method I used are diffirent. I didn't use git command in [issue](https://github.com/ccxt/ccxt/issues/16376)(I don't understand how to use git). I use samgermain [method](https://github.com/ccxt/ccxt/pull/15133#issuecomment-1356680954) to create python version of it

**Comment by croissantty** [comment]
@AlgoQ Hi, Excuse me for tagging you but I think I just got a bit of clue of the problem. kraken futures must changed something

```params={"post_only": True}``` was working before but now It is not. Could you try sending an order with post only below trading price? It's should be ejected but for me It is excuted(as taker).

```exchange.verbose = True
exchange.createOrder (pair, 'limit', 'sell', s, p, params={"post_Only":True})
```

```
fetch Response: krakenfutures POST https://futures.kraken.com/derivatives/api/v3/sendorder?orderType=lmt&symbol=pf_xrpusd&side=sell&size=1&limitPrice=0.4&post_Only=true 200 ResponseHeaders: {'Date': 'Thu, 02 Feb 2023 19:43:12 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Expose-Headers': 'Content-Disposition', 'Cache-Control': 'no-store', 'Vary': 'Origin', 'CF-Cache-Status': 'DYNAMIC', 'Set-Cookie': '__cf_bm=Ie5uCpnocn86LUP2M2yn403G2Y5.ewUag6dipZzndyg-1675366992-0-AdhVtGL+Wd7H/ARdB/Zad8WYGXkR16+ZidUi5mm9Aelp0eGwWcWVLBpmtV7nRT2scVFB3DoNf/Jh/R7YuU7MCTI=; path=/; expires=Thu, 02-Feb-23 20:13:12 GMT; domain=.futures.kraken.com; HttpOnly; Secure; SameSite=None', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '79356a149f4710d2-BKK', 'Content-Encoding': 'gzip'} ResponseBody: {"result":"success","sendStatus":{"order_id":"1108ae1a-7172-4d47-aae9-9ee9bcd59754","status":"placed","receivedTime":"2023-02-02T19:43:12.197Z","orderEvents":[{"executionId":"97d79e86-8853-499e-b4cd-e62459167821","price":0.41220,"amount":1,"orderPriorEdit":null,"orderPriorExecution":{"orderId":"1108ae1a-7172-4d47-aae9-9ee9bcd59754","cliOrdId":null,"type":"lmt","symbol":"pf_xrpusd","side":"sell","quantity":1,"filled":0,"limitPrice":0.4,"reduceOnly":false,"timestamp":"2023-02-02T19:43:12.197Z","lastUpdateTimestamp":"2023-02-02T19:43:12.197Z"},"takerReducedQuantity":null,"type":"EXECUTION"}]},"serverTime":"2023-02-02T19:43:12.198Z"}
```

I really starting to get sick of this exchange :/

**Comment by samgermain** [comment]
> params={"post_Only":True})

It needs to `"postOnly": true` or `"timeInForce": "PO"`

**Comment by croissantty** [comment]
Thank you for reply @samgermain but both are not works with my
```"postOnly": true```
```NameError: name 'true' is not defined. Did you mean: 'True'?```

```"postOnly": True```
```ccxt.base.errors.ExchangeNotAvailable: krakenfutures POST https://futures.kraken.com/derivatives/api/v3/sendorder?orderType=postOnly&symbol=pf_maticusd&side=sell&size=1&limitPrice=1.15&postOnly=true 400 Bad Request {"status":"BAD_REQUEST","result":"error","errors":[{"code":11,"message":"Argument invalid: orderType"}],"serverTime":"2023-02-03T06:29:00.862Z"}```

```"timeInForce": "PO"``` the order sent but take as taker. position is created
```"post_Only":True``` the order sent but take as taker. position is created

I don't understand Why I can't use ```postOnly``` Which is newer version of it but ```post_only``` was work before but now look like It is skipped. If in next week It just suddenly magic happen and It is back to work like It use to be. I am done another joke :/
