### ISSUE TITLE
python async speed slower

### ISSUE THREAD

**Issue by akasimo** [ccxt/ccxt#16650]
### Operating System

ubuntu

### Programming Languages

python

### CCXT Version

2.6.94

### Description

While I was trying to migrate my code to async I noticed that my execution was slower.

I wrote a small code to compare the async vs sync speed. 

Average execution time of both is written below in seconds in one of my test runs. On average async takes rougly 2x longer . Similar results when tested in other methods such as "fetch_tickers".

async mean: 1.1664345026016236
sync mean: 0.5469205617904663

### Code

```
import asyncio
import time

import ccxt.async_support as ccxta  
import ccxt
import os
from dotenv import load_dotenv
load_dotenv()

binance_keys = {
        "apikey" : os.getenv("BINANCE_APIKEY"),
        "secret" : os.getenv("BINANCE_SECRET")
    }

async def get_balance_async(exchange):
    balance = await exchange.fetch_balance()
    await exchange.close()
    return balance

exchange_async = ccxta.binance({
        'apiKey': binance_keys["apikey"],
        'secret': binance_keys["secret"],
    })

exchange_sync = ccxt.binance({
        'apiKey': binance_keys["apikey"],
        'secret': binance_keys["secret"],
    })

time_sync = []
time_async = []

loop = asyncio.get_event_loop()
for i in range(10):

    start = time.time()
    loop.run_until_complete(get_balance_async(exchange_async))
    time_async.append(time.time() - start)
    time.sleep(0.2)

    start = time.time()
    balance = exchange_sync.fetch_balance()
    time_sync.append(time.time() - start)
    time.sleep(0.2)

print("Async data: ", time_async)
print("Sync data: ", time_sync)
print(f"async mean: {sum(time_async)/len(time_async)}")
print(f"sync mean: {sum(time_sync)/len(time_sync)}")
  

```

**Comment by carlosmiei** [comment]
Hello @akasimo,
The difference is not related to the sync vs async approach, but the default RateLimiter ccxt async has in place. You can disable it if you want by providing this option: `enableRateLimit: False`.

**Comment by akasimo** [comment]
perfect, thanks!
