### ISSUE TITLE
Deribit create stop order:  InvalidOperation: [<class 'decimal.ConversionSyntax'>]

### ISSUE THREAD

**Issue by Nitrix321** [ccxt/ccxt#16663]
### ؜

Operating System: Windows 10
Programming Languages: Python
CCXT Version: 2.4.47

Hello, when I try to create a stop order on deribit it always fails, entry price ETH is 1575$ long position and I want to create a stop order at 1560$. It always appears the following message:  InvalidOperation: [<class 'decimal.ConversionSyntax'>].

Hope someone can help me please, thanks. 

```
import ccxt
import pandas as pd
import numpy as np
import deribitconfig
from datetime import date, datetime, timezone, tzinfo
import time, schedule


deribit = ccxt.deribit({
    'enableRateLimit': True,
    'apiKey': deribitconfig.api_key,
    'secret': deribitconfig.api_secret,
    })
 

pos_size = 10 

params = {
    'stopLossPrice': 1560,
    
}

deribit.create_order(symbol, type='market', side='sell', amount=pos_size, price=1560, params=params)



```

  File "C:\Users\Dell\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\dell\desktop\bybit\deribittest2023.py", line 87, in <module>
    deribit.create_order(symbol, type='market', side='sell', amount=pos_size, price=1560, params=params)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\deribit.py", line 1629, in create_order
    request['trigger_price'] = self.price_to_precision(symbol, triggerPrice)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 3242, in price_to_precision
    result = self.decimal_to_precision(price, ROUND, market['precision']['price'], self.precisionMode, self.paddingMode)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\decimal_to_precision.py", line 55, in decimal_to_precision
    dec = decimal.Decimal(str(n))

InvalidOperation: [<class 'decimal.ConversionSyntax'>]

**Comment by carlosmiei** [comment]
Hello @Nitrix321,
Thanks for reporting it we will take a look and fix it asap!
