### ISSUE TITLE
The problem with fapiPrivateGetLeverageBracke

### ISSUE THREAD

**Issue by netsesame** [ccxt/ccxt#16667]
### Operating System

windows 11

### Programming Languages

python

### CCXT Version

CCXT Version: 2.7.5

### Description

The fapiPrivateGetLeverageBracke function does not return the same value as binance

fapiPrivateGetLeverageBracke:
[{'symbol': 'GALAUSDT', 'brackets': [{'bracket': '1', 'initialLeverage': '20', 'notionalCap': '7500', 'notionalFloor': '0', 'maintMarginRatio': '0.01', 'cum': '0.0'}, {'bracket': '2', 'initialLeverage': '10', 'notionalCap': '37500', 'notionalFloor': '7500', 'maintMarginRatio': '0.025', 'cum': '112.5'}, {'bracket': '3', 'initialLeverage': '8', 'notionalCap': '150000', 'notionalFloor': '37500', 'maintMarginRatio': '0.05', 'cum': '1050.0'}, {'bracket': '4', 'initialLeverage': '5', 'notionalCap': '375000', 'notionalFloor': '150000', 'maintMarginRatio': '0.1', 'cum': '8550.0'}, {'bracket': '5', 'initialLeverage': '2', 'notionalCap': '1500000', 'notionalFloor': '375000', 'maintMarginRatio': '0.125', 'cum': '17925.0'}, {'bracket': '6', 'initialLeverage': '1', 'notionalCap': '4500000', 'notionalFloor': '1500000', 'maintMarginRatio': '0.5', 'cum': '580425.0'}]}]
binance:
https://www.binance.com/en-AU/futures/trading-rules/perpetual/leverage-margin
![image](https://user-images.githubusercontent.com/3131317/215327494-3db0197a-7dbe-4eab-a71e-2375ee6e958d.png)

### Code

```
  # -*- coding: utf-8 -*-

import os
import sys
import ccxt  # noqa: E402

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    'apiKey': 'xx',
    'secret': 'xx',
    'options': {
        'defaultType': 'future',
    },
})

exchange.proxies = {
                'http': 'http://127.0.0.1:1081',
                'https': 'http://127.0.0.1:1082',
}
markets = exchange.load_markets()
exchange.verbose = True  # UNCOMMENT THIS AFTER LOADING THE MARKETS FOR DEBUGGING

print('----------------------------------------------------------------------')
print('LeverageBracke')
response = exchange.fapiPrivateGetLeverageBracket({"symbol":"GALAUSDT"})
print(response)
print('----------------------------------------------------------------------')


```

**Comment by sc0Vu** [comment]
Hi @netsesame 

This api is private api (https://binance-docs.github.io/apidocs/futures/en/#get-income-history-user_data), I think the data depends on user. For me it's the same as that page.

**Comment by netsesame** [comment]
I see, thank you!
