### ISSUE TITLE
MEXc futures symbol error

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#16672]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

2.7.8

### Description

When trying to create an order, it throws an "NotSupported" error where it says that for example BTC/USDT:USDT is not supported. 

Please see code below to reproduce the issue. 

### Code

```
import ccxt

public = ''
private = '' 

client = ccxt.mexc3({'apiKey': public, 'secret': private})

ticker = "BTC/USDT:USDT"
order_type = 'limit'
side = 'buy'
quantity = 0.001
price = 23000

response = client.create_order(symbol=ticker, type=order_type, side=side,
                                           amount=quantity, price=price,
                                           params=({'marginMode': 'cross'}))

```
Traceback (most recent call last):

  Cell In[8], line 1
    response = client.create_order(symbol=ticker, type="limit", side=side,

  File ~\anaconda3\lib\site-packages\ccxt\mexc3.py:1613 in create_order
    return self.create_swap_order(market, type, side, amount, price, marginMode, query)

  File ~\anaconda3\lib\site-packages\ccxt\mexc3.py:1682 in create_swap_order
    raise NotSupported(self.id + ' createSwapOrder() does not support yet self symbol:' + symbol)

NotSupported: mexc3 createSwapOrder() does not support yet self symbol:BTC/USDT:USDT

**Comment by carlosmiei** [comment]
Hello @Tomas-MP,
MEXC disabled futures trading through the API a few months ago for scheduled maintenance and didn't re-open it yet, so there is nothing ccxt can do about it. 

You can read the announcement here:
https://support.mexc.com/hc/en-001/articles/8681589415961-MEXC-Upgrade-and-Maintenance-of-API-for-Perpetual-Futures-Trading-Pairs

**Comment by philipperemy** [comment]
@carlosmiei no way! So even now, there's no way to place orders via their API? That's ridiculous.

**Comment by carlosmiei** [comment]
@philipperemy Yeah, still disabled...

**Comment by krevetych** [comment]
Hi everyone,

Does anyone have any updates on the MEXC futures API? It's been marked as "under maintenance" since mid-2022, and as far as I can tell, it's still disabled.

Has MEXC provided any official communication or timeline for when futures trading via API will be available again?

**Comment by philipperemy** [comment]
@krevetych maybe dont trade on MEXC. It looks dangerous.

**Comment by krevetych** [comment]
@philipperemy Yeah, kinda sketchy that the futures API has been “under maintenance” for 2+ years. Doesn’t inspire much confidence.
