### ISSUE TITLE
Can't download kline data for 1 month ago

### ISSUE THREAD

**Issue by SIR-MHD73** [ccxt/ccxt#16697]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

2.7.21

### Description

I am trying to get kline data for 1 min time frame from 1 month ago with "coinex.fetch_ohlcv" method with python and the first candle that I receive is for 17 hours ago. 

Is there a limitation for downloading old data in coinex API that I do not know about, or it's a bug in the ccxt?

Did anyone experience that?

### Code

```
klines = coinex.fetch_ohlcv("BNBBTC", "1m", 1672494554000, 1000)           #"1672494554000" is timestamp of 1 month ago  

```
Response: 
       Timestamp         Open         High          Low        Close       Volume
0  1675113960000  0.013458  0.013458  0.013458  0.013458  0.006790
1  1675114020000  0.013446  0.013446  0.013446  0.013446  0.005086
2  1675114080000  0.013446  0.013446  0.013446  0.013446  0.005566
3  1675114140000  0.013442  0.013442  0.013442  0.013442  0.005665
4  1675114200000  0.013440  0.013440  0.013440  0.013440  0.005806

**Comment by AlgoQ** [comment]
HI @SIR-MHD73,

Coinex doesn't [support](https://viabtc.github.io/coinex_api_en_doc/spot/#docsspot001_market006_market_kline) the `since` param for the `fetch_ohlcv` function.

**Comment by SIR-MHD73** [comment]
> HI @SIR-MHD73,
> 
> Coinex doesn't [support](https://viabtc.github.io/coinex_api_en_doc/spot/#docsspot001_market006_market_kline) the `since` param for the `fetch_ohlcv` function.

Yes you're right. I didn't notice that. I have worked before with Binance API and there we had this option, so I thought we have here too.

Is there any way we can download old chart data with coinex API?

**Comment by AlgoQ** [comment]
Yup that's true Binance supports the `since` possibility. 

For 1min data, no i don't think so

**Comment by SIR-MHD73** [comment]
Thank you
