### ISSUE TITLE
create_limit_sell_order on lakeBTC says  that the symbol is not valid

### ISSUE THREAD

**Issue by LaurentIsRunning** [ccxt/ccxt#1670]
Hello, 

When I try to use create_limit_sell_order method on the LakeBTC exchange I get the following error message:

`ExchangeNotAvailable : lakebtc POST https://api.lakebtc.com/api_v2 400 {"error":"Failed to submit order: invalid symbol"}
`

The private fetchBalance is working for me, so the private api semms OK.
The sent symbol is 'btceur' which seems correct regarding the documentation provided by LakeBTC...

Sorry, I can't find what it is not working...

Thanks in advance if you have some clue, 

Laurent

- OS: Windows 10
- Programming Language version: Python
- CCXT version: 1.10.914
- Exchange: LakeBTC
- Method: create_limit_sell_order

**Comment by kroitor** [comment]
Hi, thx for reporting! Will look into it and will get back to you asap!

**Comment by LaurentIsRunning** [comment]
Thanks a lot!

**Comment by kroitor** [comment]
@LaurentIsRunning please update ccxt to version 1.10.1251 and retry your code. If the issue persists, we will need you to provide **your minimal snippet of code to reproduce the problem and your verbose output** precisely as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Hope it helps. Let us know if it doesn't.

**Comment by LaurentIsRunning** [comment]
Thank you very much, 
I'll do that ASAP!
