### ISSUE TITLE
Php Bitget

### ISSUE THREAD

**Issue by mikaelhc86** [ccxt/ccxt#16709]
### Programming Languages

php

### CCXT Version

2.7.18

### Description

In parse_order function  sometimes $order['symbol'] its null, so next code set market to null:

```
2206        $marketId = $this->safe_string($order, 'symbol');
2207        $market = $this->safe_market($marketId);
```

therefore I propose the following modification:

### Code

```
  if (!$market){
            $marketId = $this->safe_string($order, 'symbol');
            $market = $this->safe_market($marketId);
        }

```

**Comment by carlosmiei** [comment]
Hello @mikaelhc86, yeah we will apply a similar patch so it can default to `market` if `marketId` is undefined
