### ISSUE TITLE
I think the code might not be correct for coinex

### ISSUE THREAD

**Issue by Warrenn** [ccxt/ccxt#16716]
### Operating System

Mac OS

### Programming Languages

TypeScript

### CCXT Version

2.6.36

### Description

There is a bug when using the ccxt.pro.coinex exchange object and creating a maker only order using {"option":"MAKER_ONLY"}

### Code

```
  let cO = await coinEx.createLimitBuyOrder(symbol, 10, cPrice, { "option": "MAKER_ONLY" });
```
Throws:
Uncaught Object.assign ExchangeError: Invalid Parameter
    at handleErrors (c:\workbench\experiment\funding-arbitrage\ccxt-node\node_modules\ccxt\js\coinex.js:4670:19)
    at <anonymous> (c:\workbench\experiment\funding-arbitrage\ccxt-node\node_modules\ccxt\js\base\Exchange.js:603:51)
    at processTicksAndRejections (internal/process/task_queues:95:5)
    --- await ---
    at processTicksAndRejections (internal/process/task_queues:95:5)
    --- await ---
    at runMainESM (internal/modules/run_main:55:21)
    at executeUserEntryPoint (internal/modules/run_main:78:5)
    at <anonymous> (internal/main/run_main_module:18:47)

**Comment by carlosmiei** [comment]
Hello @Warrenn, your issue is empty can you please fill it in so we can get more details about the problem?

**Comment by Warrenn** [comment]
on line 1884 of /js/coinex.js I think the line
`params = this.omit (params, [ 'reduceOnly', 'positionId', 'timeInForce', 'postOnly', 'stopPrice', 'triggerPrice', 'stopLossPrice', 'takeProfitPrice' ]);` should include 'option' so that the request doesnt post a 'option':'MAKER_ONLY' 
eg:
`params = this.omit (params, [ 'reduceOnly', 'positionId', 'timeInForce', 'postOnly', 'stopPrice', 'triggerPrice', 'stopLossPrice', 'takeProfitPrice', 'option' ]);`

**Comment by Dan-krm** [comment]
@Warrenn it's working for me:
`node examples/js/cli coinex createLimitBuyOrder BTC/USDT 0.001 20000 '{"option":"MAKER_ONLY"}'`
```
Node.js: v16.9.1
CCXT v2.7.39
coinex.createLimitBuyOrder (BTC/USDT, 0.001, 20000, [object Object])
2023-02-03T23:43:59.315Z iteration 0 passed in 249 ms

{
  id: '76629031499',
  clientOrderId: undefined,
  datetime: '2023-02-03T23:44:01.000Z',
  timestamp: 1675467841000,
  lastTradeTimestamp: undefined,
  status: 'open',
  symbol: 'BTC/USDT:USDT',
  type: 'limit',
  timeInForce: undefined,
  postOnly: undefined,
  reduceOnly: undefined,
  side: 'buy',
  price: 20000,
  stopPrice: undefined,
  triggerPrice: undefined,
  cost: 0,
  average: undefined,
  amount: 0.001,
  filled: 0,
  remaining: 0.001,
  trades: [],
  fee: { currency: 'USDT', cost: 0 },
  info: {
    amount: '0.001',
    asset_fee: '0',
    avg_price: '0.00',
    client_id: '',
    create_time: '1675467841',
    deal_amount: '0',
    deal_fee: '0',
    deal_money: '0',
    fee_asset: null,
    fee_discount: '1',
    finished_time: null,
    id: '76629031499',
    left: '0.001',
    maker_fee_rate: '0.002',
    market: 'BTCUSDT',
    money_fee: '0',
    order_type: 'limit',
    price: '20000',
    status: 'not_deal',
    stock_fee: '0',
    taker_fee_rate: '0.002',
    type: 'buy'
  },
  fees: [ { currency: 'USDT', cost: 0 } ]
}
```

CCXT Pro is for websockets and createOrder isn't supported, you should be using the standard CCXT library for REST API requests like createOrder. `ccxt.coinex` instead of `ccxt.pro.coinex`
