### ISSUE TITLE
Coinbase throws AuthenticationError when using request()

### ISSUE THREAD

**Issue by GittyGitGitGitty** [ccxt/ccxt#16719]
### Operating System

Arch Linux (php 8.2.2)

### Programming Languages

php

### CCXT Version

2.5.94+

### Description

Introduced in f8dab51e0da6be12ca730f55455af1bd4586036c, affects 2.5.94 and all versions after.

```
PHP Fatal error:  Uncaught ccxt\AuthenticationError: coinbase {"errors":[{"id":"invalid_token","message":"The access token is invalid"}]} in /ccxt/ccxt/php/Exchange.php:4077
Stack trace: 
#0 /ccxt/ccxt/php/coinbase.php(1696): ccxt\Exchange->throw_exactly_matched_exception()
#1 /ccxt/ccxt/php/Exchange.php(1849): ccxt\coinbase->handle_errors()
#2 /ccxt/ccxt/php/Exchange.php(3701): ccxt\Exchange->fetch()
#3 /ccxt/ccxt/php/Exchange.php(3705): ccxt\Exchange->fetch2()
#4 /test.php(9): ccxt\Exchange->request() 
```

Rolling back to previous commit ded43625adce7ef05dced982fef88509c0c5daa6 works as expected.

### Code

```php
<?php

$coinbase = new \ccxt\coinbase(array(
    'apiKey' => 'XXXXXXXX',
    'secret' => 'XXXXXXXX',
    'enableRateLimit' => true)
);
    
$coinbase->request($path, 'private');  // Where $path is a working path

?>
```

**Comment by carlosmiei** [comment]
Hello @GittyGitGitGitty,
As you can see `request` requires a lot more parameters to work properly:

```Php
    public function request($path, $api = 'public', $method = 'GET', $params = array (), $headers = null, $body = null, $config = array (), $context = array ()) {
        return Async\async(function () use ($path, $api, $method, $params, $headers, $body, $config, $context) {
            return Async\await($this->fetch2 ($path, $api, $method, $params, $headers, $body, $config, $context));
        }) ();
    }
```

**Comment by GittyGitGitGitty** [comment]
Hello @carlosmiei ,

As you can see:

1. I'm not using the async implementation, nor is the error thrown in the async implementation, nor am I using ReactPHP.
2. In the async implementation, reverting 114c24a8b703be2d1d30269cb2fa4ff05308b707 or c4341818ba620ee17836ef5cf100aeba3257ad69 does not fix issue.
3. Prior to those commits, the only possible "breaking" change was 4f7b72c053fb1ee60a2e5065b9ff36a1c61fd104 which far pre-dates the issue and is not a breaking change.
4. The parameters in both async implementation and non-async `Exchange.php` sets default parameters, so there has been no need for me to set them (defaults have worked fine prior to 2.5.94).

Regarding the implementation I'm using:

1. The previous change to `request()` was 35580a23ea8ef7154dde1a36d7a4ce3c06bf0b5f, long before the issue.
2. Again, the parameters in both async implementation and non-async `Exchange.php` sets default parameters, so there has been no need for me to set them (defaults have worked fine prior to 2.5.94).
3. **To me, the breaking change may be in https://github.com/ccxt/ccxt/commit/f8dab51e0da6be12ca730f55455af1bd4586036c#diff-64c7afaabb23cd062c01eda2972e0517640a58e4c09887d577f79163852ec8e9 with the addition of Coinbase V2/V3 separation and change in ccxt's `sign()`ing parameters/implementation.**

Documentation update or facade update required? I don't know, I haven't looked!

**Comment by GittyGitGitGitty** [comment]
Can someone please help with this?

**Comment by GittyGitGitGitty** [comment]
Can't reproduce. Perhaps an internal Coinbase change?
