### ISSUE TITLE
hasFetchOHLCV broken for bitmex exchange

### ISSUE THREAD

**Issue by spallesen** [ccxt/ccxt#1673]
Runing CCXT on Python 3.6/Win10.

bitmex = ccxt.bitmex()
bitmex.hasFetchOHLCV

Returns False - should be True. Has the method hasFetchOHLCV changed?

**Comment by kroitor** [comment]
Hi! Answered here: https://github.com/ccxt/ccxt/issues/1536#issuecomment-361001847
