### ISSUE TITLE
Binance spot  entry price and position

### ISSUE THREAD

**Issue by ctu1121** [ccxt/ccxt#16738]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Describe the solution you'd like

I use ccxt to request binance future "entry price" and "existing position" of specific product. 
However, I can not request  "entry price" and "existing position" of spot product. Will ccxt
provide this function? or does ccxt pro (paid version) provide this function? Thanks.

Charles

**Comment by pcriadoperez** [comment]
Hi @ctu1121,
I believe the concepts of entry price and position are only part of futures and do not exist in spot markets

Also ccxt.pro is now free and part of ccxt 🥳

**Comment by ctu1121** [comment]
Understood
Thanks a lot

Pablo Criado-Perez ***@***.***>於 2023年2月6日 週一，09:21寫道：
