### ISSUE TITLE
Gemini error when fetch tickers.

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#16732]
### Operating System

Windows 10

### Programming Languages

JS

### CCXT Version

2.6.36

### Description

Hello:
I want to use ccxt function to fetch tickers for exchange Gemini, I got the following error:

C:\CCXT>node gemini_fetchTickers.js
ArgumentsRequired: gemini safeMarket() requires a fourth argument for btcusdt to disambiguate between different markets with the same market id
    at gemini.safeMarket (C:\CCXT\node_modules\ccxt\js\base\Exchange.js:2175:31)
    at gemini.parseTicker (C:\CCXT\node_modules\ccxt\js\gemini.js:691:23)
    at gemini.parseTickers (C:\CCXT\node_modules\ccxt\js\base\Exchange.js:2773:50)
    at gemini.fetchTickers (C:\CCXT\node_modules\ccxt\js\gemini.js:769:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchTickers (C:\CCXT\gemini_fetchTickers.js:14:17) {
  constructor: [class ArgumentsRequired extends ExchangeError]
}

I tried to use verbose output to see some details, but the output data is too much, I can not find any useful information.
Please check.
Thanks,

### Code

```
const ccxt = require('ccxt');

let exchange = new ccxt.gemini
({'adjustForTimeDifference': true,
defaultType: 'spot',
'verbose': false });

const fetchTickers = async() => 
{
try
{
if (exchange.has['fetchTickers'])
{
const tickers = await exchange.fetchTickers();
if (typeof tickers !== 'undefined')
{
const json_tickers = JSON.stringify(tickers);
console.log(json_tickers);
}
else
{
const obj_jsonTicker0 = ({ 'Data': []});
const json_ticker0 = JSON.stringify(obj_jsonTicker0);
console.log(json_ticker0);
}
}
}
catch (err)
{
console.error(err)
}
};
fetchTickers();
```

**Comment by carlosmiei** [comment]
Hello @zydjohnHotmail, thanks for letting us know I will take a look asap

**Comment by carlosmiei** [comment]
@zydjohnHotmail Actually, I think this issue is already fixed the reason you can't get it is due to the npm issue that prevents us from updating the package. We expect to have it fixed soon, but in the meantime, you can:
-> get the latest version of the repo and manually link it
-> copy and paste the contents of `js/gemini.js` into your local package.

**Comment by zydjohnHotmail** [comment]
Hi,
It is very important that I know how to get the latest version of the repo and manually link it.
Give me some instructions!
Thanks,

**Comment by carlosmiei** [comment]
@zydjohnHotmail I understand, please check this out https://github.com/ccxt/ccxt/issues/16633, we explain it there.

**Comment by carlosmiei** [comment]
@zydjohnHotmail I don't know if I was very clear in the message above you can do one thing (clone + link) or another (replace the file directly). The latter should be easy if you only want to fix Gemini.

**Comment by zydjohnHotmail** [comment]
Hello:
Thank you very much, the instructions work.
However, please close this issue only when new npm packages can be published.
Thanks,

**Comment by carlosmiei** [comment]
> Hello: Thank you very much, the instructions work. However, please close this issue only when new npm packages can be published. Thanks,

@zydjohnHotmail sure thanks!
