### ISSUE TITLE
Tokocrypto

### ISSUE THREAD

**Issue by mb-trading** [ccxt/ccxt#16739]
### Operating System

Windows - Visual Studio

### Programming Languages

python

### CCXT Version

in my file ccxt-1.75.14.dist-info

### Description

I can't find the file Tokocrypto
code in bottom

I entered it manually from https://github.com/ccxt/ccxt/blob/master/python/ccxt/tokocrypto.py into my site-packages file but it still doesn't connect import and other functions

can you help me for fix that ? i want to try get account information like a history trade, amount account, running position

Thanks 

### Code

my code : 

```
import ccxt
print(ccxt.exchanges)


```
output 

['aax', 'ascendex', 'bequant', 'bibox', 'bigone', 'binance', 'binancecoinm', 'binanceus', 'binanceusdm', 'bit2c', 'bitbank', 'bitbay', 'bitbns', 'bitcoincom', 'bitfinex', 'bitfinex2', 'bitflyer', 'bitforex', 'bitget', 'bithumb', 'bitmart', 'bitmex', 'bitpanda', 'bitrue', 'bitso', 'bitstamp', 'bitstamp1', 'bittrex', 'bitvavo', 'bl3p', 'blockchaincom', 'btcalpha', 'btcbox', 'btcmarkets', 'btctradeua', 'btcturk', 'buda', 'bw', 'bybit', 'bytetrade', 'cdax', 'cex', 'coinbase', 'coinbaseprime', 'coinbasepro', 'coincheck', 
'coinex', 'coinfalcon', 'coinmate', 'coinone', 'coinspot', 'crex24', 'cryptocom', 'currencycom', 'delta', 'deribit', 'digifinex', 'eqonex', 'equos', 'exmo', 'flowbtc', 'fmfwio', 'ftx', 'ftxus', 'gateio', 'gemini', 'hitbtc', 'hitbtc3', 'hollaex', 'huobi', 'huobijp', 'huobipro', 'idex', 'independentreserve', 'indodax', 'itbit', 'kraken', 'kucoin', 'kucoinfutures', 'kuna', 'latoken', 'lbank', 'liquid', 'luno', 'lykke', 'mercado', 'mexc', 'ndax', 'novadax', 'oceanex', 'okcoin', 'okex', 'okex5', 'okx', 'paymium', 'phemex', 'poloniex', 'probit', 'qtrade', 'ripio', 'stex', 'therock', 'tidebit', 'tidex', 'timex', 'upbit', 'vcc', 'wavesexchange', 'wazirx', 'whitebit', 'woo', 'xena', 'yobit', 'zaif', 'zb', 'zipmex', 'zonda']

**Comment by carlosmiei** [comment]
Hello @mb-trading, You have installed an old version of ccxt that does not contain `tokocrypto` yet. 

After updating it, you should be able to find it. 

Command to update:
```
pip install --upgrade ccxt
```

**Comment by mb-trading** [comment]
oke thanks , fixed
