### ISSUE TITLE
suddenly, fetch_order() does not work in Binance future USDⓢ-M market.

### ISSUE THREAD

**Issue by BamsoonPapa** [ccxt/ccxt#16743]
### Operating System

Windows Server 2022 English Full Base

### Programming Languages

python

### CCXT Version

2.7.3

### Description

I made this function a year ago. I've been using this function normally for the past year. These days, however, this function causes an error every time it runs. The error message is as follows.

I can find out the order ID through the Binance app. Even if I put the order ID that I found with the Binance app into this function, this error continues to occur.

When I tested it, my short order was completed normally. Even if I run this function immediately to get the order result data, an error occurred. Even if I run after 10 seconds, an error occurs.  Even if I run it after a long time, an error also occurs. It was not an error due to time difference.

There will be many people in the world who have this problem besides me. Please solve it.

----[ The error message ]-----------------------------------------------------------------------

HTTPError                                 Traceback (most recent call last)
~\anaconda3\lib\site-packages\ccxt\base\exchange.py in fetch(self, url, method, headers, body)
    624             self.logger.debug("%s %s, Response: %s %s %s", method, url, http_status_code, headers, http_response)
--> 625             response.raise_for_status()
    626 

~\anaconda3\lib\site-packages\requests\models.py in raise_for_status(self)
   1020         if http_error_msg:
-> 1021             raise HTTPError(http_error_msg, response=self)
   1022 

HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order?timestamp=1675511807866&symbol=XRPUSDT&orderId=29775009207&recvWindow=10000&signature=~~~$!$!%~~~

During handling of the above exception, another exception occurred:

OrderNotFound                             Traceback (most recent call last)
~\AppData\Local\Temp\2\ipykernel_992\3693205162.py in <module>
----> 1 getOrderData_FuturesUSD('BINANCE', 'USDT', 'XRP', '29775009207')

~\AppData\Local\Temp\2\ipykernel_992\1154987171.py in getOrderData_FuturesUSD(exchange, mkt, coin, orderId)
   1503                    ",'password':'IntraLoop007!'})")
   1504 
-> 1505         result = ecg.fetch_order(
   1506             id = orderId,
   1507 #             symbol = coin + mkt,

~\anaconda3\lib\site-packages\ccxt\binance.py in fetch_order(self, id, symbol, params)
   3502             request['orderId'] = id
   3503         requestParams = self.omit(query, ['type', 'clientOrderId', 'origClientOrderId'])
-> 3504         response = getattr(self, method)(self.extend(request, requestParams))
   3505         return self.parse_order(response, market)
   3506 

~\anaconda3\lib\site-packages\ccxt\base\exchange.py in inner(_self, params, context)
    503                 if context is not None:
    504                     inner_kwargs['context'] = params
--> 505                 return entry(_self, **inner_kwargs)
    506             return inner
    507         to_bind = partialer()

~\anaconda3\lib\site-packages\ccxt\binance.py in request(self, path, api, method, params, headers, body, config, context)
   6198 
   6199     def request(self, path, api='public', method='GET', params={}, headers=None, body=None, config={}, context={}):
-> 6200         response = self.fetch2(path, api, method, params, headers, body, config, context)
   6201         # a workaround for {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
   6202         if (api == 'private') or (api == 'wapi'):

~\anaconda3\lib\site-packages\ccxt\base\exchange.py in fetch2(self, path, api, method, params, headers, body, config, context)
   2828         self.lastRestRequestTimestamp = self.milliseconds()
   2829         request = self.sign(path, api, method, params, headers, body)
-> 2830         return self.fetch(request['url'], request['method'], request['headers'], request['body'])
   2831 
   2832     def request(self, path, api='public', method='GET', params={}, headers=None, body=None, config={}, context={}):

~\anaconda3\lib\site-packages\ccxt\base\exchange.py in fetch(self, url, method, headers, body)
    639         except HTTPError as e:
    640             details = ' '.join([self.id, method, url])
--> 641             skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
    642             if not skip_further_error_handling:
    643                 self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)

~\anaconda3\lib\site-packages\ccxt\binance.py in handle_errors(self, code, reason, url, method, headers, body, response, requestHeaders, requestBody)
   6176                 # binanceusdm {"code":-4046,"msg":"No need to change margin type."}
   6177                 raise MarginModeAlreadySet(feedback)
-> 6178             self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
   6179             raise ExchangeError(feedback)
   6180         if not success:

~\anaconda3\lib\site-packages\ccxt\base\exchange.py in throw_exactly_matched_exception(self, exact, string, message)
   3131     def throw_exactly_matched_exception(self, exact, string, message):
   3132         if string in exact:
-> 3133             raise exact[string](message)
   3134 
   3135     def throw_broadly_matched_exception(self, broad, string, message):

OrderNotFound: binance {"code":-2013,"msg":"Order does not exist."}

### Code

#getOrderData_FuturesUSD('BINANCE', 'USDT', 'XRP', '29775009207')

def getOrderData_FuturesUSD(exchange, mkt, coin, orderId):

        ecg = eval("ccxt." + exchange.lower() + 
                   "(config={'apiKey':API_KEY_" + exchange.lower() + 
                   ",'secret':SECRET_KEY_" + exchange.lower() +
                   ",'password':'*****'})")

        result = ecg.fetch_order(
            id = orderId,
            symbol = coin + "/" + mkt,
            params={"type":"future"}
            )
        
        return result

**Comment by carlosmiei** [comment]
Hello @BamsoonPapa,
A few weeks ago we merged an update on binance to add the unified symbol. Your current setup is invalid now (you can't use type=Future + legacy symbols anymore) but it's very easy to fix.

Please check this out https://github.com/ccxt/ccxt/issues/16306 where a detailed explanation is given and let us know if you have any questions!

**Comment by BamsoonPapa** [comment]
Thanks for your rapid help.
In conclusion, do I have to modify my function code like below?

#getOrderData_FuturesUSD('BINANCE', 'USDT', 'XRP', '29775009207')

------------------------------------------------------------------
def getOrderData_FuturesUSD(exchange, mkt, coin, orderId):

    ecg = eval("ccxt." + exchange.lower() + 
               "(config={'apiKey':API_KEY_" + exchange.lower() + 
               ",'secret':SECRET_KEY_" + exchange.lower() +
               ",'password':'*****'})")

    result = ecg.fetch_order(
        id = orderId,
        symbol = coin + mkt,
        params={"type":"swap"}
        )
    
    return result

**Comment by samgermain** [comment]
> @carlosmiei Thanks for your rapid help. In conclusion, do I have to modify my function code like below?
> 
> #getOrderData_FuturesUSD('BINANCE', 'USDT', 'XRP', '29775009207')
> 
> def getOrderData_FuturesUSD(exchange, mkt, coin, orderId):
> 
> ```
> ecg = eval("ccxt." + exchange.lower() + 
>            "(config={'apiKey':API_KEY_" + exchange.lower() + 
>            ",'secret':SECRET_KEY_" + exchange.lower() +
>            ",'password':'*****'})")
> 
> result = ecg.fetch_order(
>     id = orderId,
>     symbol = coin + "/" + mkt + ":" + mkt,
>     params={"type":"swap"}
>     )
> 
> return result
> ```

That looks correct, but you'll need to modify it if you want to trade contracts in coin-margined markets instead of usd-margined markets

the currency after the `:` is actually the settle currency
- in linear markets (USD-M) you gain or lose USDT/BUSD/... based on the results of your trade, so that's what makes the symbol after the `:` the same as the quote currency (e.g. `BTC/USDT:USDT` when trading contracts in an inverse market with BTC price compared to the price of USDT)
- in inverse markets (COIN-M), you gain or lose the base currency based on your trade, so the symbol after the `:` would be the same as the symbol of your base currency (e.g. `BTC/USD:BTC` when trading contracts in an inverse market with BTC price compared to the price of USD)
