### ISSUE TITLE
Bitget unable to fetch order information for conditional orders

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#16756]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

2.7.45

### Description

I am unable to retrieve order information, it throws an order not found error although I placed the order and I can see it on the exchange. 

### Code

```
public = ""
private = ""
password = ""

client = ccxt.bitget({'apiKey': public, 'secret': private,  'password': password})

ticker = "BTC/USDT:USDT"
side = "buy"
quantity = 0.001
price = 23000

response = client.create_order(symbol=ticker, type="limit", side=side,
                               amount=quantity, price=price,
                               params={'triggerPrice': price})
info = client.fetch_order(response['id'], ticker)

```
Traceback (most recent call last):

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:625 in fetch
    response.raise_for_status()

  File ~\anaconda3\lib\site-packages\requests\models.py:1021 in raise_for_status
    raise HTTPError(http_error_msg, response=self)

HTTPError: 400 Client Error: Bad Request for url: https://api.bitget.com/api/mix/v1/order/detail?orderId=1006220010476609537&symbol=BTCUSDT_UMCBL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  Cell In[25], line 1
    client.fetch_order(response['id'], ticker)

  File ~\anaconda3\lib\site-packages\ccxt\bitget.py:2596 in fetch_order
    response = getattr(self, method)(self.extend(request, query))

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:505 in inner
    return entry(_self, **inner_kwargs)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2833 in request
    return self.fetch2(path, api, method, params, headers, body, config, context)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2830 in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:641 in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File ~\anaconda3\lib\site-packages\ccxt\bitget.py:3835 in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:3133 in throw_exactly_matched_exception
    raise exact[string](message)

OrderNotFound: bitget {"code":"40109","msg":"The data of the order cannot be found, please confirm the order number","requestTime":1675627472291,"data":null}

**Comment by carlosmiei** [comment]
Hello @Tomas-MP,
We will double-check, but I don't think bitget provides the endpoint for that (fetch isolated trigger order). As a workaround, you can fetch_open_orders+fetch_closed_orders and look inside it for the target order.

Example:
```Python
params = {
     'stop':True
}
target_id = 'MY ID'
closed_orders = await bitget.fetch_closed_orders(symbol = symbol, params = params)
open_orders = await bitget.fetch_open_orders(symbol = symbol, params = params)
both = closed_orders + open_orders
filtered = list(filter(lambda order: order['id'] === target_id,  both))
```
