### ISSUE TITLE
Bitget unable to create a conditional market order

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#16755]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

2.7.45

### Description

I am unable to post a conditional market order, what I want is to buy at the market price for example when the price crosses 23000. See code below to replicate this error. 

### Code

```
public = ""
private = ""
password = "" 

client = ccxt.bitget({'apiKey': public, 'secret': private,  'password': password})

ticker = "BTC/USDT:USDT"
side = "buy"
quantity = 0.001
price = 23000

response = client.create_order(symbol=ticker, type="market", side=side,
                                           amount=quantity, price=None,
                                           params={'triggerPrice': price})

```
Traceback (most recent call last):

  Cell In[11], line 1
    response = client.create_order(symbol=ticker, type="market", side=side,

  File ~\anaconda3\lib\site-packages\ccxt\bitget.py:2290 in create_order
    request['executePrice'] = self.price_to_precision(symbol, price)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:3295 in price_to_precision
    result = self.decimal_to_precision(price, ROUND, market['precision']['price'], self.precisionMode, self.paddingMode)

  File ~\anaconda3\lib\site-packages\ccxt\base\decimal_to_precision.py:55 in decimal_to_precision
    dec = decimal.Decimal(str(n))

InvalidOperation: [<class 'decimal.ConversionSyntax'>]

**Comment by carlosmiei** [comment]
Hello again @Tomas-MP, we will take a look and revert asap
