### ISSUE TITLE
ByBit implementation in Python does not work for different defaultTypes/Types

### ISSUE THREAD

**Issue by ilikecubes** [ccxt/ccxt#16760]
### Disclaimer
I've not tested every functionality completely and didn't collect logs for everything. The issue seems to have multiple causes. While some functions do not call the correct endpoint others just don't parse the response correctly (I will be using one of those as the example here)

### Description
When fetching the Open Orders with the distinct `derivatives` functions or the normal ones via the type `swap` the response received from ByBit isn't parsed correctly.

### Additional Information
It appears that the ByBit implementation is faulty in general when it comes to switching between the types: `spot`, `futures` and `swap`. A lot of functionality resolves to trigger the spot API when it shouldn't. From my testing this applies to every single method if you do not specifically call its derivatives equivalent. `fetch_ohlc`, `create_limit_buy_order`, `create_limit_sell_order` or `fetch_order` just to name a few.

### Versions Used
OS: **macOS (13.1)**
CCXT: **2.7.38**
Python: **3.11.1**
Pip: **23.0**

### Code to Reproduce
```python
bybit = bybit({
   "enableRateLimit": True,
   "apiKey": "API_KEY",
   "secret": "API_SECRET",
   "options": {
      "defaultType": "swap"
   }
})
bybit.verbose = True

print(bybit.fetch_derivatives_open_orders(symbol="BTC/USDT"))
```

### Verbose Log of the Response
```json
{"retCode":0,"retMsg":"OK","result":{"list":[{"symbol":"BTCUSDT","orderId":"edd4fe44-a29c-4f8a-b777-ef3214294bbf","side":"Sell","orderType":"Limit","stopOrderType":"UNKNOWN","price":"22877.00","qty":"0.022","timeInForce":"GoodTillCancel","orderStatus":"New","triggerPrice":"0.00","orderLinkId":"","createdTime":"1675684557784","updatedTime":"1675684557786","takeProfit":"0.00","stopLoss":"0.00","tpTriggerBy":"UNKNOWN","slTriggerBy":"UNKNOWN","triggerBy":"UNKNOWN","reduceOnly":false,"leavesQty":"0.022","leavesValue":"503.294","cumExecQty":"0.000","cumExecValue":"0","cumExecFee":"0","triggerDirection":0,"cancelType":"UNKNOWN","lastPriceOnCreated":"","iv":"","closeOnTrigger":false},{"symbol":"BTCUSDT","orderId":"f95a9ebc-e2c0-47b1-92ff-327af2c31ec1","side":"Buy","orderType":"Limit","stopOrderType":"UNKNOWN","price":"22844.00","qty":"0.022","timeInForce":"GoodTillCancel","orderStatus":"New","triggerPrice":"0.00","orderLinkId":"","createdTime":"1675684366749","updatedTime":"1675684366751","takeProfit":"0.00","stopLoss":"0.00","tpTriggerBy":"UNKNOWN","slTriggerBy":"UNKNOWN","triggerBy":"UNKNOWN","reduceOnly":false,"leavesQty":"0.022","leavesValue":"502.568","cumExecQty":"0.000","cumExecValue":"0","cumExecFee":"0","triggerDirection":0,"cancelType":"UNKNOWN","lastPriceOnCreated":"","iv":"","closeOnTrigger":false},{"symbol":"BTCUSDT","orderId":"f675a635-1ace-441f-a52e-5d4a72655f92","side":"Buy","orderType":"Limit","stopOrderType":"UNKNOWN","price":"22837.00","qty":"0.022","timeInForce":"GoodTillCancel","orderStatus":"New","triggerPrice":"0.00","orderLinkId":"","createdTime":"1675684295799","updatedTime":"1675684295800","takeProfit":"0.00","stopLoss":"0.00","tpTriggerBy":"UNKNOWN","slTriggerBy":"UNKNOWN","triggerBy":"UNKNOWN","reduceOnly":false,"leavesQty":"0.022","leavesValue":"502.414","cumExecQty":"0.000","cumExecValue":"0","cumExecFee":"0","triggerDirection":0,"cancelType":"UNKNOWN","lastPriceOnCreated":"","iv":"","closeOnTrigger":false}],"nextPageCursor":"UnJlN3pFTXdGcnNYZ3FPOStNTmdYSjhSWXJlemduV0g5MHhESVh2S21udTAvU0w3cktDdktYTHlWZy8vTytSMldPRkF1REcwYlFWMmk2cTlKOGhNWEE9PQ==","category":""},"retExtInfo":{},"time":1675684558440}
```

### Output of Python Code
```shell
[]
```

**Comment by carlosmiei** [comment]
Hello @ilikecubes, You're not using the unified API, and you're providing contradictory arguments to that function. I would suggest using `fetchOpenOrders` instead. Regarding the symbol, that's the unified symbol for the spot BTC/USDT market, if you want to fetch orders from the linear swap BTC/USDT contract you should use `BTC/USDT:USDT` instead.

Example:
```Python
open_orders = await bybit.fetch_open_orders("BTC/USDT") # spot orders
open_orders_swap = await bybit.fetch_open_orders("BTC/USDT:USDT") # swap orders

You can read more about our naming convention here: https://docs.ccxt.com/en/latest/manual.html#contract-naming-conventions

**Comment by ilikecubes** [comment]
Well I'd still expect the Library to return swap orders for this, if my defaultType is set to swap, otherwise the whole point of having the option of specifying it wouldn't make sense like it is used now:

```python
open_orders = await bybit.fetch_open_orders("BTC/USDT")
```

Let's say I would allow a user of my program to select their exchange themselves while being on a fixed pair, although minimal work: In order to reuse the same code I would need to modify my symbol based on what exchange settings a user may select. Especially considering that we have a unified API wouldn't the expected behaviour be exactly that? So selecting `swap` if available and passing the normal symbol should be parsed to the perpetual swap symbol in my opinion.

I just feel like the actual outcome of calling methods this way is not very unified. Why should `fetch_balance` consider the type specified and return the balance for the specific account on the exchange, but a lot of other stuff still requires me to specify the symbol in a special way? Seems like a redundant step. Looks like an avoidable issue to me or am I missing something?

**Comment by sevenjay** [comment]
I agree with @ilikecubes, and I trace the code.
In ccxt/base/exchange.py, when `market` is not None will overwrite `defaultType`:
![image](https://github.com/ccxt/ccxt/assets/1086156/7e5fb1be-540c-41ee-aa54-ef3e187bc46e)

and in ccxt/bybit.py bybit.market it always return `markets[0]`. some `markets` will have 2 types, spot and swap. 
![image](https://github.com/ccxt/ccxt/assets/1086156/96f85989-1903-4920-8af4-8dd2da8882a6)

I know this happens in these functions:
    cancel_all_orders
    fetch_open_orders
    create_order

**Comment by sevenjay** [comment]
ok, I think I fix it, and test ok. but I don't know how to send the patch, just paste below, hope someone could merge it, thx.
in ccxt/bybit.py class bybit market function
```python
    def market(self, symbol):
        if self.markets is None:
            raise ExchangeError(self.id + ' markets not loaded')
        if isinstance(symbol, str):
            if symbol in self.markets:
                return self.markets[symbol]
            elif symbol in self.markets_by_id:
                defaultType = self.safe_string_2(self.options, 'defaultType', 'type', 'spot')
                markets = self.markets_by_id[symbol]
                for market in markets:
                    if market['type'] == defaultType:
                        return market
                return markets[0]
            elif (symbol.find('-C') > -1) or (symbol.find('-P') > -1):
                return self.create_expired_option_market(symbol)
        raise BadSymbol(self.id + ' does not have market symbol ' + symbol)
```

**Comment by carlosmiei** [comment]
@ilikecubes should be working now.
