### ISSUE TITLE
ccxt.base.errors.AuthenticationError: binance {"code":-2008,"msg":"Invalid Api-Key ID."}

### ISSUE THREAD

**Issue by netsesame** [ccxt/ccxt#16777]
### Operating System

ubuntu

### Programming Languages

python

### CCXT Version

ccxt                  2.1.52

### Description

Why does this error occur? Two servers running different policies, using the same KEY, and only one of them has this error

ccxt.base.errors.AuthenticationError: binance {"code":-2008, "msg": "Invalid Api-Key ID."}

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @netsesame,
It's very hard to tell without more information, what are the different policies in this context? Do you have a geographic/ip restriction enabled? Are you accessing it from the US?

**Comment by netsesame** [comment]
I think I know what the problem is. binance has recently deleted a lot of unsafe API KEY. Thank you
