### ISSUE TITLE
How to mock fetch() or any XHR request for purpose of testing

### ISSUE THREAD

**Issue by remon-georgy** [ccxt/ccxt#1677]
As in the title, I wonder how can one mock any kind of XHR request while running unit tests.

Thanks!

**Comment by remon-georgy** [comment]
On a second thought, I think entire ccxt.[exchange] got to be mocked, despite how challenging that could be.

**Comment by kroitor** [comment]
> As in the title, I wonder how can one mock any kind of XHR request while running unit tests.

Well, the question is a little vague, but, if you want a straight answer, one can mock any kind of XHR request by issuing all XHR requests once and saving the results into JSON to test against it later. Alternatively, this can be automated with swagger schemas or API blueprints. However, we don't have it yet, as this is still a work in progress. 

I've also answered a related question here: https://stackoverflow.com/questions/5757864/structuring-online-documentation-for-a-rest-api/44891930#44891930

> On a second thought, I think entire ccxt.[exchange] got to be mocked, despite how challenging that could be.

We are currently approaching this task.

Your contributions are welcome, just make sure to read this doc first: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

Let me know if this answers your question or not.

**Comment by skeller88** [comment]
Hi Kroitor, what's the Github issue I can watch that captures the work on mocking the ccxt? Is your plan to create a mock Exchange class for each exchange, or to create a single Exchange mock that returns dummy values for all fields? Ideally it'd be the former. That's more work, but the main reason I want a mock is to test different exchange responses.
