### ISSUE TITLE
Get only futures coins form CoinEx

### ISSUE THREAD

**Issue by radian-rgc** [ccxt/ccxt#16776]
Hello,
Is it possible to get only future coins in CoinEx?

Im using below code but returned all coins:

```
const exchange      = new ccxt.coinex({'options':{'defaultType':'swap'}});
await exchange.loadMarkets()
const symbols = exchange.symbols
```
Related: `https://api.coinex.com/perpetual/v1/market/list`

**Comment by carlosmiei** [comment]
Hello @radian-rgc,

If you want to filter out only `swap` markets, you can do something like this:

```Javascript
const swap_symbols = Object.values(exchange.markets).filter(m=> m['contract']).map(m=> m['symbol'])
```
