### ISSUE TITLE
Kucoin subaccount operations - fetch balance

### ISSUE THREAD

**Issue by fniko** [ccxt/ccxt#16783]
### Operating System

macOS 13.1 (22C65)

### Programming Languages

python

### CCXT Version

2.7.60

### Description

I am unable to retrieve account balance of Kucoin subaccount using `fetch_balance()` method. I am also using `sandbox` version of Kucoin, but it should not make any difference.

I am recieveing following error (_I can share full traceback if required_)
```
  File "/Users/.../venv/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://openapi-sandbox.kucoin.com/api/v1/accounts?type=trade
...
  File "/Users/.../venv/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3133, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.ExchangeNotAvailable: kucoin Internal Server Error
```

I think the API url should be `/api/v1/sub-accounts` instead of  `/api/v1/accounts`, but I was unable to find how to swich `cctx` to work with subaccounts.

#### EDIT
After few tries, the error changed to, so the API might be down temporarily
```
  File "/Users/.../venv/lib/python3.10/site-packages/ccxt/base/exchange.py", line 1753, in handle_http_status_code
    raise ErrorClass(self.id + ' ' + method + ' ' + url + ' ' + codeAsString + ' ' + reason + ' ' + body)
ccxt.base.errors.ExchangeNotAvailable: kucoin GET https://openapi-sandbox.kucoin.com/api/v1/accounts?type=trade 503 Service Unavailable {"code":"503000","msg":"Service Unavailable"}
```

### Code

```
k = ccxt.kucoin()
k.apiKey = KUCOIN_API_KEY
k.secret = KUCOIN_API_SECRET
k.password = KUCOIN_PASSPHRASE

# Enable sandbox
k.set_sandbox_mode(True)

k.fetch_balance()
```

**Comment by samgermain** [comment]
For now you'll have to use the [implicit api](https://docs.ccxt.com/en/latest/manual.html#implicit-api)

You can use any api endpoint with the implicit api, so the method would be `k.private_get_sub_accounts ()`
