### ISSUE TITLE
Can ccxt identify whenever API changes are pushed on an exchange's endpoint?

### ISSUE THREAD

**Issue by RoscoeTheDog** [ccxt/ccxt#16796]
There has been some mention of work being done by this team to unify the ccxt schema amongst all these various exchanges to allow for easier implementations for developers. I am also aware that there are many cases currently where each exchange needs to be handled differently based on what the exchange itself actually supports, such as the _binanceus_ exchange and the _kucoinfutures_ exchange, which use different schemas simply because of the nature in how each exchange trades: spot currencies and purpetual futures contracts. It's a given that when invoking a place_order() function call on both exchanges, it's not always going to translate over 1:1, so I'm trying to figure out the cleaniest way of wrapping code and handling this which has brought a few concerns to my attention.

I was thinking of wrapping various ccxt methods into a base python class and having my various strategy classes inheret from this. This way, using the _exchange_id_ as the unique identifier in the base class, I can write some code to address the differences in each schema and unify it into a single dictionary without the need for a bunch of conditionals in my strategy classes.

However as time goes on, APIs and exchange endpoints can change. If an exchanges endpoint decides to change their schema even _just a little bit_ and it goes above my radar or isn't supported by the newest version of ccxt yet, then it could cause unpredictable behavior in my strategies and potentially cause financial loss if not handle properly. Ideally ccxt framework would update their libraries to keep the schema up to date in relation to exchanges API changes. But if new changes are not yet supported after something been pushed, then is there any way to catch this-- either through manually validating differences in the expected schemas, or perhaps checking for an API version control number on the endpoint?

How could I raise an exception if there an issue between what the exchange provides and what ccxt expects? How can I raise an exception if there are issues between what ccxt's schema provides and what my unified wrapper methods expect?

**Comment by pcriadoperez** [comment]
Hi @RoscoeTheDog, you are right that there is a risk that the exchange might change their API behavior. However this risk would also exist by calling directly the exchange API. To mitigate the risk we do have several things in place. First we try to stay on top of API changes, with certified exchanges there is a direct communication channel between the ccxt team and the exchange team, also the ccxt community helps in reporting any issues and lastly we have a set of tests we run at build time to try and check the functions are working as expected.
If you really wanted to further control for this, my best suggestion would be to write specific tests for your use case, to make sure the return values are what you expect.

**Comment by RoscoeTheDog** [comment]
Thank you for your response. All of that sounds fairly reassuring. Is there a way I could parse an order dictionary schema in advanced before placing an order on the exchange? I'd like to create a validation method that searches the dictionary for a few keywords which code might rely on for correct functionality. This way, if ccxt ever changes their schema, my code can catch it in advance before the order even goes through.

**Comment by pcriadoperez** [comment]
From the ccxt side, our schema is quite consistent and we always try to be backwards compatible. If you want to run a validation you could write your code in typescript and use `ccxt.d.ts` to run type validation checks during build. However do note that even though this confirms the schema, it does not confirm if for a certain exchange those values may be populated or not, as depending on the exchange they are not always available. Also note, the one place I'd be slightly more cautious is under the 'info' parameters, for example `order['info']` as there we return the raw response from the exchange and will change if the exchange changes their response and is not unified.

**Comment by pcriadoperez** [comment]
Hi @RoscoeTheDog , I'll close this issue for now but feel free to reach out with any other questions
