### ISSUE TITLE
HitBTC doesn't have any currencies listed

### ISSUE THREAD

**Issue by alexlacey** [ccxt/ccxt#1679]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by kroitor** [comment]
Can you show your code? Most often this is due to forgetting to load the markets properly.

https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

Let us know, if it doesn't answer your question.
