### ISSUE TITLE
Watch ticker for many symbols but watched only last symbol on Coinex

### ISSUE THREAD

**Issue by radian-rgc** [ccxt/ccxt#16790]
### Operating System

Linux Centos 8

### Programming Languages

JS

### CCXT Version

2.6.36

### Description

Im trying to get ticker data by `watchTicker(symbol)` , but only last request is keep alive and fetching data and another is not watching.

This problem is only have on Coinex exchange , but in Binance is working fine.

### Code

```js
const ccxt = require ('ccxt');

console.log ('CCXT Version:', ccxt.version);

async function ticker(exchange,symbol)  {
    while (true) {
        try {  
            const ticker = await exchange.watchTicker(symbol);      
            console.log (new Date (), exchange.id, symbol, ticker['last'])   
        } catch (e) {
            console.log (e)
        }
    }
}  

async function main () {

    const exchangeId = 'coinex';
    const exchange = new ccxt.pro[exchangeId];
    exchange['options']['defaultType'] = 'spot';
    exchange.verbose = true;

    await Promise.all([
        ticker (exchange, "ADA/USDT"),
        ticker (exchange, "SOL/USDT"),
        ticker (exchange, "ETH/USDT"),
        ticker (exchange, "ETC/USDT"),
    ])
}

main ();
```
Only watching ticker for `ETC/USDT`

Log output:

`onMessage { method: 'state.update', params: [ { ETCUSDT: [Object] } ], id: null }`

This code for Binance exchange is working fine!

**Comment by pcriadoperez** [comment]
Hi @radian-rgc , thanks for bringing this up. It looks like in the case of coinex, the exchange is unsubscribing the previous subscriptions when creating a new one. I'll open a PR to fix this.
