### ISSUE TITLE
Is there any max. number of orders limit for fetchOrders?

### ISSUE THREAD

**Issue by kerimSD** [ccxt/ccxt#16800]
### ؜

OS: Windows
Programming Language version: Nodejs v16.17.0
CCXT version: 2.5.25

Hi, I would like to ask a question about Orders and Trades. For example, If the user has more than 1000 orders, Is fetchClosedOrders() method gonna return all of them or last 300-500 of them? Is there any limit on ccxt or exchanges? (Is this same for trades, openorders etc. ?)

I couldn't find any information in ccxt manual and exchange's docs.

**Comment by kroitor** [comment]
Hi! 
؜
> For example, If the user has more than 1000 orders, Is fetchClosedOrders() method gonna return all of them or last 300-500 of them?

In most cases without any pagination added the exchanges will return the last N orders or trades.

> Is there any limit on ccxt or exchanges? 

CCXT will not limit them, however, the exchanges themselves have limitations. They usually don't serve more than 100-500-1000 last orders / last trades. You can get your complete history by applying some pagination (say, fetching by 500 orders in a loop and shifting the datetime to obtain them all) as described in the CCXT Manual.

> Is this same for trades, openorders etc. ?
No, it can vary from endpoint to endpoint even within the same exchange. Say, the limit could be 500 last orders and 1000 last trades.
 
> I couldn't find any information in ccxt manual and exchange's docs.

Please, check here:
- https://github.com/ccxt/ccxt/wiki/Manual#pagination
- https://github.com/ccxt/ccxt/wiki/Manual#querying-orders
- https://github.com/ccxt/ccxt/wiki/Manual#personal-trades

Also, check the examples here:
- https://github.com/ccxt/ccxt/tree/master/examples

Let us know if the above does not answer your question. Feel free to reopen it if necessary.
