### ISSUE TITLE
Binance Features Mismatch

### ISSUE THREAD

**Issue by fredfortier** [ccxt/ccxt#1680]
- OS: Mac
- Programming Language version: Python 3.6
- CCXT version: 1.10.944
- Exchange: Binance
- Method: Features

In this version `exchange.hasFetchMyTrades == False` but `exchange.has['fetchMyTrades'] == True`. The latter syntax appears to hold the correct value so I switched to that. Both were equal in earlier versions.

**Comment by Deathamns** [comment]
The former style was deprecated, also removed in recent versions, so stop depending on it.
`has.feature` is the proper way.

**Comment by kroitor** [comment]
@fredfortier the above answer given by @Deathamns is correct, we are migrating to the new metainfo format. Sorry for the inconvenience.
