### ISSUE TITLE
ZB create_order error 

### ISSUE THREAD

**Issue by sbyinin** [ccxt/ccxt#1681]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: OS X 10.12.6
- Programming Language version:3.5
- CCXT version:1.10.891
- Exchange:zb
- Method:create_order()

I checked the document: https://www.zb.com/i/developer/restApi#trade
It seems that request methods should be GET.

`import ccxt`
`zb = ccxt.zb({"apiKey": "x",`
`    "secret": "x",`
`    "verbose": True})`
`order = zb.create_order('BAT/BTC', 'market', 'buy', 10, price='0.000051', params={})`

> POST https://trade.zb.com/api/order?accesskey=x&method=order&sign=x&reqTime=1517466681267 
Request: {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None
POST https://trade.zb.com/api/order?accesskey=x&method=order&sign=x&reqTime=1517466681267 
Response: {'CNDServer': 'cache_server_1', 'Connection': 'keep-alive', 'Content-Type': 'text/javascript;charset=utf-8', 'Date': 'Thu, 01 Feb 2018 06:31:21 GMT', 'Server': 'nginx/1.12.2', 'Content-Length': '38', 'Access-Control-Allow-Origin': '*'} {"code":1001,"message":"Error Market"}
Traceback (most recent call last):
  File "d.py", line 7, in <module>
    order = zb.create_order('BAT/BTC', 'market', 'buy', 10, price='0.000051', params={})
  File "/usr/local/lib/python3.5/dist-packages/ccxt/zb.py", line 316, in create_order
    response = self.privatePostOrder(paramString)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/zb.py", line 378, in request
    raise ExchangeError(self.id + ' ' + self.json(response))
ccxt.base.errors.ExchangeError: zb {"code":1001,"message":"Error Market"}

**Comment by kroitor** [comment]
Thx for reporting, will look into it and will fix it shortly. Related PR: https://github.com/ccxt/ccxt/pull/1300

**Comment by redindian** [comment]
Also saw this, didn't change the POST into GET yet with the recent PR. The POST method in PR #1717 still works while parameters are added to the URL, see: https://github.com/redindian/ccxt/blob/5262ca68b92a8f125b941ed9d43c3dd3485688a2/js/zb.js#L506. Seems like an easy fix to change 'post' to 'get' in https://github.com/redindian/ccxt/blob/5262ca68b92a8f125b941ed9d43c3dd3485688a2/js/zb.js#L86 because all private methods seems to require 'get' according to the ZB API.

**Comment by kroitor** [comment]
This is fixed in #1300 and #1717. 

Duplicate: #1269

Please don't forget to update ccxt to version 1.10.1234.

Thanks for reporting!
