### ISSUE TITLE
CCXT Binance min price tick size does not match tick size for python-binance package on DOWN/UP USDT pairs (and PAX/USDT)

### ISSUE THREAD

**Issue by viper7882** [ccxt/ccxt#16847]
### Operating System

Windows 11

### Programming Languages

python

### CCXT Version

2.7.93

### Description

During cross validation between CCXT and python-binance, I've discovered there is a discrepancy for between the two over Binance exchange's 420 USDT currency pairs in the spot market for the **_minimum price tick size_**. Note that the minimum lot/quantity step size is 100% matching and NOT affected.

The list of currency pairs affected including:
1. PAX/USDT
2. BTCUP/USDT
3. BTCDOWN/USDT
4. ETHUP/USDT
5. ETHDOWN/USDT
6. ADAUP/USDT
7. ADADOWN/USDT
8. LINKUP/USDT
9. LINKDOWN/USDT
10. BNBUP/USDT
11. BNBDOWN/USDT
12. XTZUP/USDT
13. XTZDOWN/USDT
14. EOSUP/USDT
15. EOSDOWN/USDT
16. TRXUP/USDT
17. TRXDOWN/USDT
18. XRPUP/USDT
19. XRPDOWN/USDT
20. DOTUP/USDT
21. DOTDOWN/USDT
22. LTCUP/USDT
23. LTCDOWN/USDT
24. UNIUP/USDT
25. UNIDOWN/USDT
26. SXPUP/USDT
27. SXPDOWN/USDT
28. YFIUP/USDT
29. YFIDOWN/USDT
30. AAVEUP/USDT
31. AAVEDOWN/USDT
32. SUSHIUP/USDT
33. SUSHIDOWN/USDT
34. XLMUP/USDT
35. XLMDOWN/USDT
36. 1INCHUP/USDT
37. 1INCHDOWN/USDT

This covers 8.8% of total USDT pairs listed. The rest of the USDT pairs do not seem to be affected.

P/S: I only screened USDT pairs in the spot market. Someone might want to screen other currency pairs other than USDT for confirmation over the scope of impact.

### Code

```python
import ccxt

from binance.client import Client

# ---------------------------------------------------------------------------------------
# Python-Binance Exchange
# ---------------------------------------------------------------------------------------
client = Client(testnet=False)

# Fetch the exchange information
exchange_info = client.get_exchange_info()

# ---------------------------------------------------------------------------------------
# CCXT Exchange
# ---------------------------------------------------------------------------------------
# Initialize the Binance exchange object
exchange = ccxt.binance()

fetch_tickers__dict = dict(
    type="spot",   # CCXT Market Type
)
tickers = exchange.fetch_tickers(params=fetch_tickers__dict)
usdt_pairs = [symbol for symbol in tickers.keys() if symbol.endswith('USDT')]

print("ccxt.__version__: ", ccxt.__version__)

for symbol_name in usdt_pairs:
    symbol_id = symbol_name.replace("/", "").replace(":USDT", "")
    # ---------------------------------------------------------------------------------------
    # Python-Binance Symbol
    # ---------------------------------------------------------------------------------------
    try:
        # Find the symbol in the exchange information
        symbol_info = [s for s in exchange_info["symbols"] if s["symbol"] == symbol_id][0]
    except IndexError:
        # For some reason, BSV/USDT is not found in python-binance
        # msg = "WARNING: Skipped {}".format(symbol_name)
        # print(msg)
        continue

    # Retrieve the minimum price tick size
    price_filter = [f for f in symbol_info["filters"] if f["filterType"] == "PRICE_FILTER"][0]
    min_price_tick_size = float(price_filter["tickSize"])

    # Retrieve the minimum volume step size
    lot_size_filter = [f for f in symbol_info["filters"] if f["filterType"] == "LOT_SIZE"][0]
    min_volume_step_size = float(lot_size_filter["stepSize"])

    # ---------------------------------------------------------------------------------------
    # CCXT Symbol
    # ---------------------------------------------------------------------------------------
    # Retrieve the symbol's information
    symbol_info = exchange.load_markets(symbol_name)

    # Retrieve the minimum price tick size
    ccxt_min_price_tick_size = symbol_info[symbol_name]['limits']['price']['min']
    if min_price_tick_size != ccxt_min_price_tick_size:
        msg = "WARNING: {}: min_price_tick_size: Expected: {}, Actual: {}".format(
            symbol_name, min_price_tick_size, ccxt_min_price_tick_size)
        print(msg)

    # Retrieve the minimum volume step size
    ccxt_min_volume_step_size = symbol_info[symbol_name]['limits']['amount']['min']
    if min_volume_step_size != ccxt_min_volume_step_size:
        msg = "WARNING: {}: min_volume_step_size: Expected: {}, Actual: {}".format(
            symbol_name, min_volume_step_size, ccxt_min_volume_step_size)
        print(msg)
```

The observed output:
```bash
D:\Issue\ccxt\venv\Scripts\python.exe D:\Issue\ccxt\ccxt_binance_exchange_vs_python-binance.py 
ccxt.__version__:  2.7.93
WARNING: PAX/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.7
WARNING: BTCUP/USDT: min_price_tick_size: Expected: 0.001, Actual: 0.399
WARNING: BTCDOWN/USDT: min_price_tick_size: Expected: 1e-06, Actual: 0.001845
WARNING: ETHUP/USDT: min_price_tick_size: Expected: 0.001, Actual: 0.385
WARNING: ETHDOWN/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.0512
WARNING: ADAUP/USDT: min_price_tick_size: Expected: 0.001, Actual: 0.041
WARNING: ADADOWN/USDT: min_price_tick_size: Expected: 1e-06, Actual: 0.00028
WARNING: LINKUP/USDT: min_price_tick_size: Expected: 1e-05, Actual: 0.00063
WARNING: LINKDOWN/USDT: min_price_tick_size: Expected: 1e-06, Actual: 0.000193
WARNING: BNBUP/USDT: min_price_tick_size: Expected: 0.01, Actual: 4.19
WARNING: BNBDOWN/USDT: min_price_tick_size: Expected: 1e-05, Actual: 0.00161
WARNING: XTZUP/USDT: min_price_tick_size: Expected: 1e-06, Actual: 0.00026
WARNING: XTZDOWN/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.2588
WARNING: EOSUP/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.0212
WARNING: EOSDOWN/USDT: min_price_tick_size: Expected: 1e-07, Actual: 3.76e-05
WARNING: TRXUP/USDT: min_price_tick_size: Expected: 1e-05, Actual: 0.00389
WARNING: TRXDOWN/USDT: min_price_tick_size: Expected: 0.001, Actual: 0.114
WARNING: XRPUP/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.0093
WARNING: XRPDOWN/USDT: min_price_tick_size: Expected: 1e-07, Actual: 2.08e-05
WARNING: DOTUP/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.0097
WARNING: DOTDOWN/USDT: min_price_tick_size: Expected: 0.001, Actual: 1.668
WARNING: LTCUP/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.0486
WARNING: LTCDOWN/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.2228
WARNING: UNIUP/USDT: min_price_tick_size: Expected: 0.001, Actual: 0.107
WARNING: UNIDOWN/USDT: min_price_tick_size: Expected: 0.001, Actual: 0.219
WARNING: SXPUP/USDT: min_price_tick_size: Expected: 1e-05, Actual: 0.01745
WARNING: SXPDOWN/USDT: min_price_tick_size: Expected: 1e-05, Actual: 0.00897
WARNING: YFIUP/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.0117
WARNING: YFIDOWN/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.092
WARNING: AAVEUP/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.0597
WARNING: AAVEDOWN/USDT: min_price_tick_size: Expected: 1e-06, Actual: 0.000471
WARNING: SUSHIUP/USDT: min_price_tick_size: Expected: 1e-06, Actual: 0.00047
WARNING: SUSHIDOWN/USDT: min_price_tick_size: Expected: 0.001, Actual: 3.78
WARNING: XLMUP/USDT: min_price_tick_size: Expected: 1e-05, Actual: 0.00244
WARNING: XLMDOWN/USDT: min_price_tick_size: Expected: 0.001, Actual: 0.431
WARNING: 1INCHUP/USDT: min_price_tick_size: Expected: 1e-06, Actual: 0.00633
WARNING: 1INCHDOWN/USDT: min_price_tick_size: Expected: 1e-06, Actual: 0.000627

Process finished with exit code 0
```

**Comment by samgermain** [comment]
> ### Operating System
> 
> Windows 11
> ### Programming Languages
> 
> python
> ### CCXT Version
> 
> 2.7.93
> ### Description
> 
> During cross validation between CCXT and python-binance, I've discovered there is a discrepancy for between the two over Binance exchange's 420 USDT currency pairs in the spot market for the **_minimum price tick size_**. Note that the minimum lot/quantity step size is 100% matching and NOT affected.
> 
> The list of currency pairs affected including:
> 
>     1. PAX/USDT
> 
>     2. BTCUP/USDT
> 
>     3. BTCDOWN/USDT
> 
>     4. ETHUP/USDT
> 
>     5. ETHDOWN/USDT
> 
>     6. ADAUP/USDT
> 
>     7. ADADOWN/USDT
> 
>     8. LINKUP/USDT
> 
>     9. LINKDOWN/USDT
> 
>     10. BNBUP/USDT
> 
>     11. BNBDOWN/USDT
> 
>     12. XTZUP/USDT
> 
>     13. XTZDOWN/USDT
> 
>     14. EOSUP/USDT
> 
>     15. EOSDOWN/USDT
> 
>     16. TRXUP/USDT
> 
>     17. TRXDOWN/USDT
> 
>     18. XRPUP/USDT
> 
>     19. XRPDOWN/USDT
> 
>     20. DOTUP/USDT
> 
>     21. DOTDOWN/USDT
> 
>     22. LTCUP/USDT
> 
>     23. LTCDOWN/USDT
> 
>     24. UNIUP/USDT
> 
>     25. UNIDOWN/USDT
> 
>     26. SXPUP/USDT
> 
>     27. SXPDOWN/USDT
> 
>     28. YFIUP/USDT
> 
>     29. YFIDOWN/USDT
> 
>     30. AAVEUP/USDT
> 
>     31. AAVEDOWN/USDT
> 
>     32. SUSHIUP/USDT
> 
>     33. SUSHIDOWN/USDT
> 
>     34. XLMUP/USDT
> 
>     35. XLMDOWN/USDT
> 
>     36. 1INCHUP/USDT
> 
>     37. 1INCHDOWN/USDT
> 
> 
> This covers 8.8% of total USDT pairs listed. The rest of the USDT pairs do not seem to be affected.
> 
> P/S: I only screened USDT pairs in the spot market. Someone might want to screen other currency pairs other than USDT for confirmation over the scope of impact.
> ### Code
> 
> ```python
> import ccxt
> 
> from binance.client import Client
> 
> # ---------------------------------------------------------------------------------------
> # Python-Binance Exchange
> # ---------------------------------------------------------------------------------------
> client = Client(testnet=False)
> 
> # Fetch the exchange information
> exchange_info = client.get_exchange_info()
> 
> # ---------------------------------------------------------------------------------------
> # CCXT Exchange
> # ---------------------------------------------------------------------------------------
> # Initialize the Binance exchange object
> exchange = ccxt.binance()
> 
> fetch_tickers__dict = dict(
>     type="spot",   # CCXT Market Type
> )
> tickers = exchange.fetch_tickers(params=fetch_tickers__dict)
> usdt_pairs = [symbol for symbol in tickers.keys() if symbol.endswith('USDT')]
> 
> print("ccxt.__version__: ", ccxt.__version__)
> 
> for symbol_name in usdt_pairs:
>     symbol_id = symbol_name.replace("/", "").replace(":USDT", "")
>     # ---------------------------------------------------------------------------------------
>     # Python-Binance Symbol
>     # ---------------------------------------------------------------------------------------
>     try:
>         # Find the symbol in the exchange information
>         symbol_info = [s for s in exchange_info["symbols"] if s["symbol"] == symbol_id][0]
>     except IndexError:
>         # For some reason, BSV/USDT is not found in python-binance
>         # msg = "WARNING: Skipped {}".format(symbol_name)
>         # print(msg)
>         continue
> 
>     # Retrieve the minimum price tick size
>     price_filter = [f for f in symbol_info["filters"] if f["filterType"] == "PRICE_FILTER"][0]
>     min_price_tick_size = float(price_filter["tickSize"])
> 
>     # Retrieve the minimum volume step size
>     lot_size_filter = [f for f in symbol_info["filters"] if f["filterType"] == "LOT_SIZE"][0]
>     min_volume_step_size = float(lot_size_filter["stepSize"])
> 
>     # ---------------------------------------------------------------------------------------
>     # CCXT Symbol
>     # ---------------------------------------------------------------------------------------
>     # Retrieve the symbol's information
>     symbol_info = exchange.load_markets(symbol_name)
> 
>     # Retrieve the minimum price tick size
>     ccxt_min_price_tick_size = symbol_info[symbol_name]['limits']['price']['min']
>     if min_price_tick_size != ccxt_min_price_tick_size:
>         msg = "WARNING: {}: min_price_tick_size: Expected: {}, Actual: {}".format(
>             symbol_name, min_price_tick_size, ccxt_min_price_tick_size)
>         print(msg)
> 
>     # Retrieve the minimum volume step size
>     ccxt_min_volume_step_size = symbol_info[symbol_name]['limits']['amount']['min']
>     if min_volume_step_size != ccxt_min_volume_step_size:
>         msg = "WARNING: {}: min_volume_step_size: Expected: {}, Actual: {}".format(
>             symbol_name, min_volume_step_size, ccxt_min_volume_step_size)
>         print(msg)
> ```
> 
> The observed output:
> 
> ```shell
> D:\Issue\ccxt\venv\Scripts\python.exe D:\Issue\ccxt\ccxt_binance_exchange_vs_python-binance.py 
> ccxt.__version__:  2.7.93
> WARNING: PAX/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.7
> WARNING: BTCUP/USDT: min_price_tick_size: Expected: 0.001, Actual: 0.399
> WARNING: BTCDOWN/USDT: min_price_tick_size: Expected: 1e-06, Actual: 0.001845
> WARNING: ETHUP/USDT: min_price_tick_size: Expected: 0.001, Actual: 0.385
> WARNING: ETHDOWN/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.0512
> WARNING: ADAUP/USDT: min_price_tick_size: Expected: 0.001, Actual: 0.041
> WARNING: ADADOWN/USDT: min_price_tick_size: Expected: 1e-06, Actual: 0.00028
> WARNING: LINKUP/USDT: min_price_tick_size: Expected: 1e-05, Actual: 0.00063
> WARNING: LINKDOWN/USDT: min_price_tick_size: Expected: 1e-06, Actual: 0.000193
> WARNING: BNBUP/USDT: min_price_tick_size: Expected: 0.01, Actual: 4.19
> WARNING: BNBDOWN/USDT: min_price_tick_size: Expected: 1e-05, Actual: 0.00161
> WARNING: XTZUP/USDT: min_price_tick_size: Expected: 1e-06, Actual: 0.00026
> WARNING: XTZDOWN/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.2588
> WARNING: EOSUP/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.0212
> WARNING: EOSDOWN/USDT: min_price_tick_size: Expected: 1e-07, Actual: 3.76e-05
> WARNING: TRXUP/USDT: min_price_tick_size: Expected: 1e-05, Actual: 0.00389
> WARNING: TRXDOWN/USDT: min_price_tick_size: Expected: 0.001, Actual: 0.114
> WARNING: XRPUP/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.0093
> WARNING: XRPDOWN/USDT: min_price_tick_size: Expected: 1e-07, Actual: 2.08e-05
> WARNING: DOTUP/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.0097
> WARNING: DOTDOWN/USDT: min_price_tick_size: Expected: 0.001, Actual: 1.668
> WARNING: LTCUP/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.0486
> WARNING: LTCDOWN/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.2228
> WARNING: UNIUP/USDT: min_price_tick_size: Expected: 0.001, Actual: 0.107
> WARNING: UNIDOWN/USDT: min_price_tick_size: Expected: 0.001, Actual: 0.219
> WARNING: SXPUP/USDT: min_price_tick_size: Expected: 1e-05, Actual: 0.01745
> WARNING: SXPDOWN/USDT: min_price_tick_size: Expected: 1e-05, Actual: 0.00897
> WARNING: YFIUP/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.0117
> WARNING: YFIDOWN/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.092
> WARNING: AAVEUP/USDT: min_price_tick_size: Expected: 0.0001, Actual: 0.0597
> WARNING: AAVEDOWN/USDT: min_price_tick_size: Expected: 1e-06, Actual: 0.000471
> WARNING: SUSHIUP/USDT: min_price_tick_size: Expected: 1e-06, Actual: 0.00047
> WARNING: SUSHIDOWN/USDT: min_price_tick_size: Expected: 0.001, Actual: 3.78
> WARNING: XLMUP/USDT: min_price_tick_size: Expected: 1e-05, Actual: 0.00244
> WARNING: XLMDOWN/USDT: min_price_tick_size: Expected: 0.001, Actual: 0.431
> WARNING: 1INCHUP/USDT: min_price_tick_size: Expected: 1e-06, Actual: 0.00633
> WARNING: 1INCHDOWN/USDT: min_price_tick_size: Expected: 1e-06, Actual: 0.000627
> 
> Process finished with exit code 0
> ```

The lot/quantity size is the tick size, so if those are matching then the tick sizes are matching. The value under `limits['price']['min']` refers to the lowest price that you can place a limit order in this market for, so it's going to be different than the tick size

**Comment by viper7882** [comment]
Thanks for the explanations @samgermain. It is somewhat different from my impression of how to use `limits['price']['min']`. My intention is to query the minimum price step size and minimum quantity size of a given symbol. May I know what are the correct API calls to achieve that objective since `limits['price']['min']` and `limits['amount']['min']` aren't the correct candidate?

**Comment by samgermain** [comment]
> Thanks for the explanations @samgermain. It is somewhat different from my impression of how to use `limits['price']['min']`. My intention is to query the minimum price step size and minimum quantity size of a given symbol. May I know what are the correct API calls to achieve that objective since `limits['price']['min']` and `limits['amount']['min']` aren't the correct candidate?

Those numbers are under `precision['amount']` and `precision['price']`

**Comment by viper7882** [comment]
Hmm, after replacing codes with your suggestions, I'm getting even more warnings:
```bash
WARNING: BTC/USDT: min_price_tick_size: Expected: 0.01, Actual: 2
WARNING: BTC/USDT: min_volume_step_size: Expected: 1e-05, Actual: 5
WARNING: ETH/USDT: min_price_tick_size: Expected: 0.01, Actual: 2
WARNING: ETH/USDT: min_volume_step_size: Expected: 0.0001, Actual: 4
WARNING: BNB/USDT: min_price_tick_size: Expected: 0.1, Actual: 1
WARNING: BNB/USDT: min_volume_step_size: Expected: 0.001, Actual: 3
WARNING: BCC/USDT: min_price_tick_size: Expected: 0.01, Actual: 2
WARNING: BCC/USDT: min_volume_step_size: Expected: 1e-05, Actual: 5
WARNING: NEO/USDT: min_price_tick_size: Expected: 0.01, Actual: 2
WARNING: NEO/USDT: min_volume_step_size: Expected: 0.01, Actual: 2
WARNING: LTC/USDT: min_price_tick_size: Expected: 0.01, Actual: 2
WARNING: LTC/USDT: min_volume_step_size: Expected: 0.001, Actual: 3
.
.
.
```

In the debugger, I saw those entries under `precision` are digits. I doubt they are the values I'm referring. May be you would like to double check?

**Comment by samgermain** [comment]
This issue looks like it's resolved to me, so I'm going to close it. Feel free to reopen it if you have any more questions
