### ISSUE TITLE
Error with proxy-anywhere

### ISSUE THREAD

**Issue by Sandr0oo** [ccxt/ccxt#16857]
### ؜

What could be the problem? I use cors-anywhere. Help please.
![изображение](https://user-images.githubusercontent.com/61181414/219120178-3d6d434d-b08c-4452-bee2-a68c16f1b4e3.png)
![изображение](https://user-images.githubusercontent.com/61181414/219120213-49d8f201-ef0e-4136-b6ac-fbcba79cc3e1.png)
Proxy works:
![изображение](https://user-images.githubusercontent.com/61181414/219120454-e152fe2e-f187-458e-89c4-cd2df1858ce8.png)

**Comment by sc0Vu** [comment]
Hi @Sandr0oo 

Would you like to paste detail for the request / response? Or the log of proxy server?

**Comment by Sandr0oo** [comment]
@sc0Vu I'm not sure that's what you asked for. Tell me how to get the information you need.
![изображение](https://user-images.githubusercontent.com/61181414/219300506-efba8949-fac2-4692-93f8-5e8a776c7492.png)


And in the text file information from the handleInitialRequest function.
![изображение](https://user-images.githubusercontent.com/61181414/219300889-a2918ae8-d7d3-405c-b899-c77858650bca.png)


And here is the text file:
[request.txt](https://github.com/ccxt/ccxt/files/10753366/request.txt)
