### ISSUE TITLE
TakeProfit and StopLoss are not working

### ISSUE THREAD

**Issue by SequoiaB** [ccxt/ccxt#16856]
### ؜

OS = Win 10

LANGUAGE = PYTHON

CCXT version = i didn't really understand how to get it 

My question is, what's the proper way to set stop loss and take profit?

exchange = bybit

also why all the attributes of the dictionary order are none?

Thx in advance

```python
def executeOrder(side, takeProfitPrice, stopLossPrice, quantity):
    print("order executer activated")
    params = {
        'stopPrice': stopLossPrice,
        'stopLimitPrice': stopLossPrice,
        'stopPriceType': 'limit',
        'takeProfitPrice': takeProfitPrice,
        'takeProfitPriceType': 'limit'
    }
    print(params)
    order = exchange.create_order(
        "ETH/USDT:USDT", 'market', side, quantity, params)
    print(order)
```

and it returns
(I formatted it a little bit to make it more readable)
```
order executer activated
{'stopPrice': 1551.456682573667, 'stopLimitPrice': 1551.456682573667, 'stopPriceType': 'limit', 'takeProfitPrice': 1551.4566825
{'info': {'orderId': '04893131-a394-4340-94ea-bbde30c30536', 'orderLinkId': ''}, 
'id': '04893131-a394-4340-94ea-bbde30c30536', 'clientOrderId': None, 'timestamp': None, 'datetime': None, 
'lastTradeTimestamp': None, 'symbol': None, 'type': None, 'timeInForce': None, 'postOnly': None, 'side': None, 'price': None, 
'stopPrice': None, 'triggerPrice': None, 'amount': None, 'cost': None, 'average': None, 'filled': None, 'remaining': None,
 'status': None, 'fee': None, 'trades': [], 'fees': [], 'reduceOnly': None}
```

**Comment by samgermain** [comment]
Look at https://github.com/ccxt/ccxt/issues/13822

**Comment by segundocarlos** [comment]
hi, i have a same problem,  
TakeProfit and StopLoss are not working in bybit when create order

**Comment by samgermain** [comment]
> hi, i have a same problem, TakeProfit and StopLoss are not working in bybit when create order

@Dan-krm It looks like you added bybit takeProfit and stopLoss (https://github.com/ccxt/ccxt/pull/13859) functionality, can you take a look at this?

Thanks

**Comment by Dan-krm** [comment]
> > hi, i have a same problem, TakeProfit and StopLoss are not working in bybit when create order
> 
> @Dan-krm It looks like you added bybit takeProfit and stopLoss (#13859) functionality, can you take a look at this?
> 
> Thanks

I think it was changed a few times since then, I'll take a look though

**Comment by Dan-krm** [comment]
@SequoiaB I opened a PR that will make stopLoss and takeProfit orders follow the schema highlighted in https://github.com/ccxt/ccxt/issues/13822

Almost all of the dictionary keys are None because that endpoint only returns the orderId and no other fields:
```
            {
                "retCode": 0,
                "retMsg": "OK",
                "result": {
                    "orderId": "e10b0716-7c91-4091-b98a-1fa0f401c7d5",
                    "orderLinkId": "test0000003"
                },
                "retExtInfo": null,
                "time": 1664441344238
            }
```

**Comment by Dan-krm** [comment]
@SequoiaB @segundocarlos on bybit you can simply set `stopLoss` and `takeProfit` to float values in the params when creating an order
