### ISSUE TITLE
InvalidOrder: binance {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}

### ISSUE THREAD

**Issue by oppfx** [ccxt/ccxt#16866]
### code：
```
let exchange = new ccxt.binance ({
        apiKey: 'my apikey',
        secret: 'my secret',
        'options': {
            'createMarketBuyOrderRequiresPrice': false, // switch off
        },
    })
    // var bal=await exchange.fetchBalance()
   
    var bal=await exchange.fetchBalance()
    console.info('usdt：'+bal.total.USDT)
    
    
    const symbol = 'SAND/USDT'
    const price = 5 // USDt
  
    const order = await exchange.createMarketBuyOrder (symbol, price)
    // const order = await exchange.createOrder (symbol, 'market', 'buy', 1, price)  //same error
    console.info(order)
```

### error ：
InvalidOrder: binance {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}

**Comment by sc0Vu** [comment]
Hi @oppfx 

It seems the price * quantity is too low (https://binance-docs.github.io/apidocs/spot/en/#filter-failures).

**Comment by oppfx** [comment]
fix this !
price>= $10

code :
`const order = await exchange.createOrder (symbol, 'market', 'buy', 1, 10) // use $10 buy as many tokens as possible
 `

**Comment by oppfx** [comment]
> 

i set default, is true

**Comment by carlosmiei** [comment]
> > 
> 
> i set default, is true

@oppfx what does that even mean? we're trying to help, but you're not being clear about your intent. Try to share as much information as possible.
