### ISSUE TITLE
Binance Spot Websocket API

### ISSUE THREAD

**Issue by L1nkus** [ccxt/ccxt#16867]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Describe the solution you'd like

Spot WebSocket API on Binance was introduced at the end of last December and has been running with stable performance.

The new API allows clients to send spot trading related requests  through Websocket connection. It is a separate Websocket connection than previously existed Data Stream. Noticeable endpoints are:
- Order Management: place new order, query order, cancel order 
- Market Data: order book, recent trades, ticker.
- Account: account details, order history, account history

WIth the connection established, sending requests through the Websocket API generally has lower latency.

Docs at: https://binance-docs.github.io/apidocs/websocket_api/en/#introduction

**Comment by hzpkk520** [comment]
I believe the mentioned Websocket APIs are mostly included in the **_[ccxt.pro](https://ccxt.pro/)_**, which is now free to use.

**Comment by pcriadoperez** [comment]
Hi @L1nkus, yes I believe @frosty00 , is working on implementing the new Websocket API.

**Comment by L1nkus** [comment]
@pcriadoperez Nice, very cool. In meantime I found https://github.com/binance/binance-connector-python with a ready implementation

**Comment by ttodua** [comment]
> @pcriadoperez Nice, very cool. In meantime I found https://github.com/binance/binance-connector-python with a ready implementation

I've looked through that python library's readme, and they I couldnt find if they support WEBSOCKET-API your refer to. at list, in their readme, they dont mention and just mention the typical websocket api, which is already in ccxt.

**Comment by alikam** [comment]
hi, I want to know that is this implemented in ccxt or not yet? thanks

**Comment by carlosmiei** [comment]
@alikam Hello, yes this is available.

**Comment by gshpychka** [comment]
Then this issue could be closed?

**Comment by ttodua** [comment]
@gshpychka yes right, the issue is closed now, thanks
