### ISSUE TITLE
Bug: coniEX precision of amount is wrong

### ISSUE THREAD

**Issue by kjnh10** [ccxt/ccxt#16876]
### Operating System

Linux

### Programming Languages

python

### CCXT Version

2.0.1

### Description

I think ccxt code should use 'amount_prec' instead of 'stoc_prec' for 'precision' of the amount in coinex.py.

Below is an example of "WAVESUSDT".

coinex.py
<img width="853" alt="image" src="https://user-images.githubusercontent.com/6933428/219613448-e3bdbf9c-9add-4750-8773-bf626b25dd5c.png">

markets["WAVESUSDT"]["info"]
<img width="434" alt="image" src="https://user-images.githubusercontent.com/6933428/219613729-c0d6dbf9-7e80-459f-9cf0-ca9d504f77dc.png">

I confirmed that I can enter 0.1 as a minimum amount. I couldn't enter 0.01.
<img width="605" alt="image" src="https://user-images.githubusercontent.com/6933428/219614260-ab113348-bea4-4443-a412-f77a53648494.png">

**Comment by ttodua** [comment]
Hi.
I'll look into this bug. but , at first, your screenshot is of different market, seems OMG token.

**Comment by ttodua** [comment]
I've gone further and checked myself and I confirmed the bug.
submitted the fix. when this issue gets closed, update ccxt and it should be fixed.
