### ISSUE TITLE
The parameters of orders are null

### ISSUE THREAD

**Issue by SequoiaB** [ccxt/ccxt#16878]
### ؜

hello, this is what I get after calling

`write(order=exchange.create_market_order(symbol, side, size, params))`

where write is a function that dumps a json in a json file

`{
    "info": {
        "orderId": "2c471e2c-7160-40e0-842b-6234a0333e2a",
        "orderLinkId": ""
    },
    "id": "2c471e2c-7160-40e0-842b-6234a0333e2a",
    "clientOrderId": null,
    "timestamp": null,
    "datetime": null,
    "lastTradeTimestamp": null,
    "symbol": null,
    "type": null,
    "timeInForce": null,
    "postOnly": null,
    "side": null,
    "price": null,
    "stopPrice": null,
    "triggerPrice": null,
    "amount": null,
    "cost": null,
    "average": null,
    "filled": null,
    "remaining": null,
    "status": null,
    "fee": null,
    "trades": [],
    "fees": [],
    "reduceOnly": null
}`

why are all the attributes null? what am I doing wrong?

**Comment by carlosmiei** [comment]
Hello @SequoiaB,
You're doing nothing wrong. Some exchanges, upon creating an order return only its id immediately (some order creation processes are async so they don't have the information available right away). Using that id you can fetch all the information by using the unified method `fetchOrder`

**Comment by SequoiaB** [comment]
thx
