### ISSUE TITLE
Binance: edit_order add support for cancel by client id

### ISSUE THREAD

**Issue by speedingonatram** [ccxt/ccxt#16887]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

Binance cancelReplace supports both 'cancelOrigClientOrderId' and 'cancelOrderId':
https://binance-docs.github.io/apidocs/spot/en/#cancel-an-existing-order-and-send-a-new-order-trade

But in ccxt we currently only support using 'cancelOrderId' inside 'edit_order':
https://github.com/ccxt/ccxt/blob/c81f5181ddb4454736771294ac3cd7fa42869da8/python/ccxt/async_support/binance.py#L3243

### Describe the solution you'd like

Change the edit_order function for Binance so that user can choose if the id they pass in is 'cancelOrderId' or 'cancelOrigClientOrderId'

**Comment by carlosmiei** [comment]
Hello @speedingonatram thanks for your report, we will add that feature very soon!
