### ISSUE TITLE
Phemex Missing parameter - to","data":null

### ISSUE THREAD

**Issue by Nitrix321** [ccxt/ccxt#16896]
### ؜

OS: Windows 10
Programming Language version: Python
CCXT version: 2.8.16

Hello,

My programm worked for months now, I changed NOTHING but

suddenly I get this Error:           BadRequest: phemex {"code":412,"msg":"Missing parameter - to","data":null}

**I only get this Error at the inverse contract  'USD/USD:ETH'  but not at the linear contract 'ETH/USD:USD'
although it's exactly the same code.** 

Here's my code:

import ccxt
import pandas as pd
import numpy as np
import phemconfig
from datetime import date, datetime, timezone, tzinfo
import time, schedule

pd.set_option('display.max_rows', None)

phemex = ccxt.phemex({
    'enableRateLimit': True,
    'apiKey': phemconfig.api_key,
    'secret': phemconfig.api_secret})

phemex.verbose = True

# settings

symbol = 'USD/USD:ETH'
pos_size = 1
timeframe = '1m'
num_bars = 200

params = {"type":"swap","code":"ETH"}
bars = phemex.fetch_ohlcv(symbol, timeframe=timeframe, limit=num_bars)
#print(bars)

df_d = pd.DataFrame(bars, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
df_d['timestamp'] = pd.to_datetime(df_d['timestamp'], unit='ms')
#print(df_d)

Error Message: 

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 625, in fetch
    response.raise_for_status()

  File "C:\Users\Dell\AppData\Local\Programs\Spyder\pkgs\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

HTTPError: 400 Client Error: Bad Request for url: https://api.phemex.com/exchange/public/md/kline?resolution=60&limit=1000&symbol=cETHUSD

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\Dell\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\dell\desktop\bybit\phemex2.py", line 523, in <module>
    bars = phemex.fetch_ohlcv(symbol, timeframe=timeframe, limit=num_bars)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\phemex.py", line 1066, in fetch_ohlcv
    response = getattr(self, method)(self.extend(request, params))

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 505, in inner
    return entry(_self, **inner_kwargs)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 2833, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 2830, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 641, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\phemex.py", line 3507, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 3133, in throw_exactly_matched_exception
    raise exact[string](message)

BadRequest: phemex {"code":412,"msg":"Missing parameter - to","data":null}

Verbose log:(partly)

fetch Response: phemex GET https://api.phemex.com/v1/exchange/public/products 200 ResponseHeaders: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Sun, 19 Feb 2023 13:31:48 GMT', 'Server': 'nginx', 'x-phemex-request-tracing': '338801a5-f45e-4da5-9558-33aed9af34dd', 'X-RateLimit-Remaining': '99', 'X-RateLimit-Capacity': '100', 'X-Content-Type-Options': 'nosniff, nosniff', 'X-XSS-Protection': '1; mode=block, 1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate, no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY, SAMEORIGIN', 'Referrer-Policy': 'no-referrer, origin-when-cross-origin', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'X-Cache': 'Hit from cloudfront', 'Via': '1.1 0c688bb347bc402edc1209f13e04d88c.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'FRA56-P2', 'X-Amz-Cf-Id': 'm_wZzTAJpSnW0B3tCMG6r_VwkyozZsObJarvTr66AffCN1BavZXHfQ==', 'Age': '1441'} ResponseBody: {"code":0,"msg":"OK","data":[{"symbol":"BTCUSD","underlyingSymbol":".BTC","quoteCurrency":"USD","baseCurrency":"BTC","settlementCurrency":"BTC","maxOrderQty":1000000,"maxPriceEp":100000000000000,"lotSize":1,"tickSize":"0.5","contractSize":"1 USD","priceScale":4,"ratioScale":8,"valueScale":8,"defaultLeverage":0,"maxLeverage":100,"initMarginEr":"1000000","maintMarginEr":"500000","defaultRiskLimitEv":10000000000,"deleverage":true,"makerFeeRateEr":-250000,"takerFeeRateEr":750000,"fundingInterval":8,"marketUrl":"https://phemex.com/trade/BTCUSD","description":"BTCUSD is a BTC/USD perpetual contract priced on the .BTC Index. Each contract is worth 1 USD of Bitcoin. Funding is paid and received every 8 hours. At UTC time: 00:00, 08:00, 16:00.","type":"Perpetual"},{"symbol":"ETHUSD","underlyingSymbol":".ETH","quoteCurrency":"USD","baseCurrency":"ETH","settlementCurrency":"USD","maxOrderQty":500000,"maxPriceEp":200000000,"lotSize":1,"tickSize":"0.05","contractSize":"0.005 ETH","priceScale":4,"ratioScale":8,"valueScale":4,"defaultLeverage":0,"maxLeverage":20,"initMarginEr":"5000000","maintMarginEr":"1000000","defaultRiskLimitEv":5000000000,"deleverage":true,"makerFeeRateEr":-250000,"takerFeeRateEr":750000,"fundingInterval":8,"marketUrl":"https://phemex.com/trade/ETHUSD","description":"ETHUSD is a ETH/USD perpetual contract priced on the .ETH Index. Each contract is worth 0.005 ETH of USD. Funding is paid and received every 8 hours. At UTC time: 00:00, 08:00, 16:00.","type":"Perpetual"},{"symbol":"XRPUSD","underlyingSymbol":".XRP","quoteCurrency":"USD","baseCurrency":"XRP","settlementCurrency":"USD","maxOrderQty":500000,"maxPriceEp":2000000,"lotSize":1,"tickSize":"0.0001","contractSize":"5 XRP","priceScale":4,"ratioScale":8,"valueScale":4,"defaultLeverage":0,"maxLeverage":20,"initMarginEr":"5000000","maintMarginEr":"1000000","defaultRiskLimitEv":5000000000,"deleverage":true,"makerFeeRateEr":-250000,"takerFeeRateEr":750000,"fundingInterval":8,"marketUrl":"https://phemex.com/trade/XRPUSD","description":"XRPUSD is a XRP/USD perpetual contract priced on the .XRP Index. Each contract is worth 5 XRP of USD. Funding is paid and received every 8 hours. At UTC time: 00:00, 08:00, 16:00.","type":"Perpetual"},{"symbol":"LINKUSD","underlyingSymbol":".LINK","quoteCurrency":"USD","baseCurrency":"LINK","settlementCurrency":"USD","maxOrderQty":500000,"maxPriceEp":20000000,"lotSize":1,"tickSize":"0.001","contractSize":"0.2 LINK","priceScale":4,"ratioScale":8,"valueScale":4,"defaultLeverage":0,"maxLeverage":20,"initMarginEr":"5000000","maintMarginEr":"1000000","defaultRiskLimitEv":5000000000,"deleverage":true,"makerFeeRateEr":-250000,"takerFeeRateEr":750000,"fundingInterval":8,"marketUrl":"https://phemex.com/trade/LINKUSD","description":"LINKUSD is a LINK/USD perpetual contract priced on the .LINK Index. Each contract is worth 0.2 LINK of USD. Funding is paid and received every 8 hours. At UTC time: 00:00, 08:00, 16:00.","type":"Perpetual"},{"symbol":"XTZUSD","underlyingSymbol":".XTZ","quoteCurrency":"USD","baseCurrency":"XTZ","settlementCurrency":"USD","maxOrderQty":500000,"maxPriceEp":20000000,"lotSize":1,"tickSize":"0.001","contractSize":"0.5 XTZ","priceScale":4,"ratioScale":8,"valueScale":4,"defaultLeverage":0,"maxLeverage":20,"initMarginEr":"5000000","maintMarginEr":"1000000","defaultRiskLimitEv":5000000000,"deleverage":true,"makerFeeRateEr":-250000,"takerFeeRateEr":750000,"fundingInterval":8,"marketUrl":"https://phemex.com/trade/XTZUSD","description":"XTZUSD is a XTZ/USD perpetual contract priced on the .XTZ Index. Each contract is worth 0.5 XTZ of USD. Funding is paid and received every 8 hours. At UTC time: 00:00, 08:00, 16:00.","type":"Perpetual"},{"symbol":"LTCUSD","underlyingSymbol":".LTC","quoteCurrency":"USD","baseCurrency":"LTC","settlementCurrency":"USD","maxOrderQty":500000,"maxPriceEp":1000000000,"lotSize":1,"tickSize":"0.01","contractSize":"0.02 LTC","priceScale":4,"ratioScale":8,"valueScale":4,"defaultLeverage":0,"maxLeverage":20,"initMarginEr":"5000000","maintMarginEr":"1000000","defaultRiskLimitEv":5000000000,"deleverage":true,"makerFeeRateEr":-250000,"takerFeeRateEr":750000,"fundingInterval":8,"marketUrl":"https://phemex.com/trade/LTCUSD","description":"LTCUSD is a LTC/USD perpetual contract priced on the .LTC Index. Each contract is worth 0.02 LTC of USD. Funding is paid and received every 8 hours. At UTC time: 00:00, 08:00, 16:00.","type":"Perpetual"},{"symbol":"GOLDUSD","underlyingSymbol":".GOLD","quoteCurrency":"USD","baseCurrency":"GOLD","settlementCurrency":"USD","maxOrderQty":500000,"maxPriceEp":1000000000,"lotSize":1,"tickSize":"0.05","contractSize":"0.001 GOLD","priceScale":4,"ratioScale":8,"valueScale":4,"defaultLeverage":0,"maxLeverage":100,"initMarginEr":"1000000","maintMarginEr":"500000","defaultRiskLimitEv":5000000000,"deleverage":true,"makerFeeRateEr":-250000,"takerFeeRateEr":750000,"fundingInterval":8,"marketUrl":"https://phemex.com/trade/GOLDUSD","description":"GOLDUSD is a GOLD/USD perpetual contract priced on the .GOLD Index. Each contract is worth 0.001 troy ounce GOLD of USD. Funding is paid and received every 8 hours. At UTC time: 00:00, 08:00, 16:00.","type":"Perpetual"},{"symbol":"ADAUSD","underlyingSymbol":".ADA","quoteCurrency":"USD","baseCurrency":"ADA","settlementCurrency":"USD","maxOrderQty":500000,"maxPriceEp":1000000000,"lotSize":1,"tickSize":"0.0001","contractSize":"20 ADA","priceScale":4,"ratioScale":8,"valueScale":4,"defaultLeverage":0,"maxLeverage":20,"initMarginEr":"5000000","maintMarginEr":"1000000","defaultRiskLimitEv":5000000000,"deleverage":true,"makerFeeRateEr":-250000,"takerFeeRateEr":750000,"fundingInterval":8,"marketUrl":"https://phemex.com/trade/ADAUSD","description":"ADAUSD is a ADA/USD perpetual contract priced on the .ADA Index. Each contract is worth 20 ADA of USD. Funding is paid and received every 8 hours. At UTC time: 00:00, 08:00, 16:00.","type":"Perpetual"},{"symbol":"BCHUSD","underlyingSymbol":".BCH","quoteCurrency":"USD","baseCurrency":"BCH","settlementCurrency":"USD","maxOrderQty":500000,"maxPriceEp":1000000000,"lotSize":1,"tickSize":"0.05","contractSize":"0.005 BCH","priceScale":4,"ratioScale":8,"valueScale":4,"defaultLeverage":0,"maxLeverage":20,"initMarginEr":"5000000","maintMarginEr":"1000000","defaultRiskLimitEv":5000000000,"deleverage":true,"makerFeeRateEr":-250000,"takerFeeRateEr":750000,"fundingInterval":8,"marketUrl":"https://phemex.com/trade/BCHUSD","description":"BCHUSD is a BCH/USD perpetual contract priced on the .BCH Index. Each contract is worth 0.005 BCH of USD. Funding is paid and received every 8 hours. At UTC time: 00:00, 08:00, 16:00.","type":"Perpetual"},{"symbol":"COMPUSD","underlyingSymbol":".COMP","quoteCurrency":"USD","baseCurrency":"COMP","settlementCurrency":"USD","maxOrderQty":500000,"maxPriceEp":1000000000,"lotSize":1,"tickSize":"0.05","contractSize":"0.005 COMP","priceScale":4,"ratioScale":8,"valueScale":4,"defaultLeverage":0,"maxLeverage":20,"initMarginEr":"5000000","maintMarginEr":"1000000","defaultRiskLimitEv":5000000000,"deleverage":true,"makerFeeRateEr":-250000,"takerFeeRateEr":750000,"fundingInterval":8,"marketUrl":"https://phemex.com/trade/COMPUSD","description":"COMPUSD is a COMP/USD perpetual contract priced on the .COMP Index. Each contract is worth 0.005 COMP of USD. Funding is paid and received every 8 hours. At UTC time: 00:00, 08:00, 16:00.","type":"Perpetual"},{"symbol":"YFIUSD","underlyingSymbol":".YFI","quoteCurrency":"USD","baseCurrency":"YFI","settlementCurrency":"USD","maxOrderQty":500000,"maxPriceEp":10000000000,"lotSize":1,"tickSize":"0.5","contractSize":"0.0001 YFI","priceScale":4,"ratioScale":8,"valueScale":4,"defaultLeverage":0,"maxLeverage":20,"initMarginEr":"5000000","maintMarginEr":"1000000","defaultRiskLimitEv":5000000000,"deleverage":true,"makerFeeRateEr":-250000,"takerFeeRateEr":750000,"fundingInterval":8,"marketUrl":"https://phemex.com/trade/YFIUSD","description":"YFIUSD is a YFI/USD perpetual contract priced on the .YFI Index. Each contract is worth 0.0001 YFI of USD. Funding is paid and received every 8 hours. At UTC time: 00:00, 08:00, 16:00.","type":"Perpetual"},{"symbol":"ALGOUSD","underlyingSymbol":".ALGO","quoteCurrency":"USD","baseCurrency":"ALGO","settlementCurrency":"USD","maxOrderQty":500000,"maxPriceEp":2000000,"lotSize":1,"tickSize":"0.0001","contractSize":"5 ALGO","priceScale":4,"ratioScale":8,"valueScale":4,"defaultLeverage":0,"maxLeverage":20,"initMarginEr":"5000000","maintMarginEr":"1000000","defaultRiskLimitEv":5000000000,"deleverage":true,"makerFeeRateEr":-250000,"takerFeeRateEr":750000,"fundingInterval":8,"marketUrl":"https://phemex.com/trade/ALGOUSD","description":"ALGOUSD is a ALGO/USD perpetual contract priced on the .ALGO Index. Each contract is worth 5 ALGO of USD. Funding is paid and received every 8 hours. At UTC time: 00:00, 08:00, 16:00.","type":"Perpetual"},{"symbol":"DOTUSD","underlyingSymbol":".DOT","quoteCurrency":"USD","baseCurrency":"DOT","settlementCurrency":"USD","maxOrderQty":500000,"maxPriceEp":2000000,"lotSize":1,"tickSize":"0.001","contractSize":"1 DOT","priceScale":4,"ratioScale":8,"valueScale":4,"defaultLeverage":0,"maxLeverage":20,"initMarginEr":"5000000","maintMarginEr":"1000000","defaultRiskLimitEv":5000000000,"deleverage":true,"makerFeeRateEr":-250000,"takerFeeRateEr":750000,"fundingInterval":8,"marketUrl":"https://phemex.com/trade/DOTUSD","description":"DOTUSD is a DOT/USD perpetual contract priced on the .DOT Index. Each contract is worth 1 DOT of USD. Funding is paid and received every 8 hours. At UTC time: 00:00, 08:00, 16:00.","type":"Perpetual"},{"symbol":"UNIUSD","underlyingSymbol":".UNI","quoteCurrency":"USD","baseCurrency":"UNI","settlementCurrency":"USD","maxOrderQty":500000,"maxPriceEp":2000000,"lotSize":1,"tickSize":"0.001","contractSize":"1 UNI","priceScale":4,"ratioScale":8,"valueScale":4,"defaultLeverage":0,"maxLeverage":20,"initMarginEr":"5000000","maintMarginEr":"1000000","defaultRiskLimitEv":5000000000,"deleverage":true,"makerFeeRateEr":-250000,"takerFeeRateEr":750000,"fundingInterval":8,"marketUrl":"https://phemex.com/trade/UNIUSD","description":"UNIUSD is a UNI/USD perpetual contract priced on the .UNI Index. Each contract is worth 1 UNI of USD. Funding is paid and received every 8 hours. At UTC time: 00:00, 08:00, 16:00.","type":"Perpetual"}]}

fetch Request: phemex GET https://api.phemex.com/exchange/public/md/kline?resolution=60&limit=100&symbol=cETHUSD RequestHeaders: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: phemex GET https://api.phemex.com/exchange/public/md/kline?resolution=60&limit=100&symbol=cETHUSD 400 ResponseHeaders: {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Sun, 19 Feb 2023 13:55:50 GMT', 'Server': 'nginx', 'x-phemex-request-tracing': '9f12671e-6262-4349-8a08-b2fd8479a5bc', 'X-RateLimit-Remaining-OTHER': '88', 'X-RateLimit-Capacity-OTHER': '100', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY', 'Referrer-Policy': 'no-referrer', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 0c688bb347bc402edc1209f13e04d88c.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'FRA56-P2', 'X-Amz-Cf-Id': 'a7ZqG-054uFHnCGEk5KiB3zcUC7dZ0_mgT-8a_z-fz8xLYqVob7nnQ=='} ResponseBody: {"code":412,"msg":"Missing parameter - to","data":null}

**Comment by carlosmiei** [comment]
Hello @Nitrix321, thanks for letting us know we will take a look.
