### ISSUE TITLE
Kucoinfutures fetch open orders shows no data anymore

### ISSUE THREAD

**Issue by Nitrix321** [ccxt/ccxt#16898]
### ؜

OS: Windows 10
Programming Language version: Python
CCXT version: 2.8.16

Hello, 

since a few days kucoinfutures doesn't show any data if I try to fetch open orders when STOP ORDER is placed. Issue occurs at linear and inverse contracts.   If a limit order above price is placed it works. 
Also here I didn't change anything, it has worked fine for months now, but suddenly it doesn't work anymore. 

kucoin = ccxt.kucoinfutures({'enableRateLimit': True,
                       'apiKey': kucoinconfig.api_key,
                       'secret': kucoinconfig.api_secret,
                       'password' : 'xxxxxxxxxxx',})

symbol = 'ETH/USDT:USDT'
pos_size = 1

orders = kucoin.fetch_open_orders(symbol)
        print(orders)

Output is this --> []

**Comment by carlosmiei** [comment]
Hello @Nitrix321,

If you want to fetch open `stop` orders you should provide `stop:True` inside `params`.
Example:
```
params = {
   'stop': True
}
stop_open_orders = kucoin.fetch_open_orders(symbol, params=params)
```

**Comment by Nitrix321** [comment]
Hi @carlosmiei,
you are right, now it's working. I could have sworn it worked all along. 
But ok, now it is.

Thank you again :-)
