### ISSUE TITLE
Add BingX to your library

### ISSUE THREAD

**Issue by ocmich74** [ccxt/ccxt#16899]
### Exchange Name

BingX

### URL of the Exchange

https://bingx.com

### URL of the Exchange's API docs

https://bingx-api.github.io/docs/swap/introduce.html

### Why should this exchange be implemented?

This exchange use to be called bingbon. It's pretty popular and would be a great addition to your library

**Comment by sc0Vu** [comment]
It's duplicated: https://github.com/ccxt/ccxt/issues/13206.
