### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by Industrial** [ccxt/ccxt#16897]
### Operating System

nixos

### Programming Languages

python

### CCXT Version

latest

### Description

Trying to get ccxt installed on NixOS, I get an error that the README.md file is not available in the `setup.py`.

To reproduce: `docker run -it python pip install ccxt --no-binary :all:`

### Code

```
  

```

**Comment by aaronmondal** [comment]
@kroitor This is a bug. Getting the same issue with nix. The README is not packaged in the pypi package.

**Comment by aaronmondal** [comment]
cc @JannisFengler
