### ISSUE TITLE
Huobi - can't fetch deposti address

### ISSUE THREAD

**Issue by CanberraMenthonnex** [ccxt/ccxt#16900]
### Operating System

Mac Os

### Programming Languages

JS

### Description

I'm trying to fetch the deposit addresses of a token on Huobi with this method: fetchDepositAddress().

But CCXT returns this error: 

![Capture d’écran 2023-02-19 à 21 12 25](https://user-images.githubusercontent.com/70761366/219972762-5cc88404-2611-4277-8dd9-421262550c00.png)

And it's pretty strange because when I run the code on a browser and check the network, the API called on the Huobi side returns me the correct addresses (with a nice code 200) to deposit as on their documentation 
(cf: https://huobiapi.github.io/docs/spot/v1/en/#query-deposit-address)

So I'm quite confused, if anyone have an idea ?

### Code

```
      const exchange = new ccxt.huobi (
      {
        apiKey: API_KEY,
        secret: SECRET,
        timeout: 30000
      }
    )
    const data = await exchange.fetchDepositAddress("usdt");
    console.log(data);

```

**Comment by carlosmiei** [comment]
Hello @CanberraMenthonnex, can you try to call `fetchDepositAddress` with the unified currency code  (`USDT` ) instead of `usdt` ?

**Comment by kroitor** [comment]
@CanberraMenthonnex hi! Please, post your verbose output: 

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

```JavaScript
      const exchange = new ccxt.huobi (
      {
        apiKey: API_KEY,
        secret: SECRET,
        timeout: 30000
      }
    )
    const markets = await exchange.loadMarkets ()
    exchange.verbose = true // after loading the markets
    const data = await exchange.fetchDepositAddress("usdt");
    console.log(data);
```
