### ISSUE TITLE
ccxtpro function 'watch_order_book' seems won't work for   phemex

### ISSUE THREAD

**Issue by ldkklj** [ccxt/ccxt#16909]
### Operating System

Centos 7

### Programming Languages

python

### CCXT Version

the latest one

### Description

watch_order_book always return None .
hope to fix that ,other exchange is ok

### Code

```
  

```

**Comment by pcriadoperez** [comment]
Hi @ldkklj , I just tested it with both javascript and python for `BTC/USDT` on the latest ccxt version and both seem to be working ok. What market are you trying?

**Comment by ldkklj** [comment]
sorry ,I use the future pair such as 'KAVA/USDT:USDT' or 'KAVAUSDT' ,neither return a value

**Comment by ldkklj** [comment]
@pcriadoperez sorry ,I use the future pair such as 'KAVA/USDT:USDT' or 'KAVAUSDT' ,neither return a value
