### ISSUE TITLE
Kucoin fetchBalance method returning empty data

### ISSUE THREAD

**Issue by jordanimmanuel914** [ccxt/ccxt#16929]
### ؜

I think this is a stupid question.
But I don't know why. please help me.
For testing purpose, I deposited 55$ to kucoin main account and can check it.

0.00230737BTC≈ 55.03USD(Loans: 0.00 BTC)

I also created an API key.
```
Key : 63f666faf2ac4300019c0de5
API Restrictions : General, Trade
Period of Validity : 30 days
IP Restriction : No（less secure; binding an IP address is recommended)

Keys and secrets are correct.

const kucoin = new ccxt.kucoin({
    'apiKey': config.kucoin_apiKey,
    'secret': config.kucoin_secret,
    'password' : config.kucoin_password,
    'enableRateLimit': true,
    'trust': true // enable trust option
});
console.log (await kucoin.fetchBalance ())

result is : 
{
  info: { code: '200000', data: [] },
  timestamp: undefined,
  datetime: undefined,
  free: {},
  used: {},
  total: {}
}

when I test with fetchDeposits(), the result is correct.

OS : Windows 10
Programming Language version: Node JS 14.18.1
CCXT version : 2.4.96

**Comment by samgermain** [comment]
Can you try 

`kucoin.fetchBalance('{"type": "main"}')`

and 

`kucoin.fetchBalance('{"type": "spot"}')`

------------------------------

`kucoin.fetchBalance` defaults to getting the balance from your spot account, when you make a deposit to your kucoin account, it will go into your `funding`/`main` account

**Comment by jordanimmanuel914** [comment]
Great!

`kucoin.fetchBalance({"type": "main"})`

it works well.
Thank you a lot.
