### ISSUE TITLE
Bytbit - UTA but not unified flag

### ISSUE THREAD

**Issue by ndywicki** [ccxt/ccxt#16937]
### Operating System

Win WSL

### Programming Languages

python

### CCXT Version

.8.31

### Description

Hi,

I've convert my Bybit account to Unified Trading Account.
But all fetch balance are empty.

I notice that the Python code check the `unified` value from the request `https://api.bybit.com/user/v3/private/query-api` but for my account unified is 0 and uat is 1:

````
"createdAt":"2023-02-23T13:56:51Z","unified":0,"uta":1,"
````

So for the balance cctx use the request `https://api.bybit.com/contract/v3/private/account/wallet/balance` instead of `https://api.bybit.com/unified/v3/private/account/wallet/balance`

It's ok if I call manually the right request :
````
balance = exchange.privateGetUnifiedV3PrivateAccountWalletBalance()
````

I'm not sure if is already take into account with the PR bybit: upgrade to v5 api #16699

Thanks

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @ndywicki 

Thanks, we have a PR for upgrading to bybit v5 api: https://github.com/ccxt/ccxt/pull/16699. Once PR merged you can upgrade ccxt library and this should fix.
