### ISSUE TITLE
Kucoin: `PROCESSING` deposits should be handled as `pending`, not `ok`.

### ISSUE THREAD

**Issue by srisi** [ccxt/ccxt#16938]
### Operating System

Ubuntu

### Programming Languages

python

### CCXT Version

2.8.30

### Description

For Kucoin transactions, `PROCESSING` gets parsed as `ok`: https://github.com/ccxt/ccxt/blob/56bb5f84bf2ecd2a60c615e33c39e08a31b308d6/python/ccxt/kucoin.py#L2174 

However, at least for deposits, `PROCESSING` should likely get parsed as `pending` since the funds are not yet available for trading or further transfers in this state.

Thanks!

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @srisi, I agree, thanks for reporting it. We will change it soon.

**Comment by srisi** [comment]
Thank you!
