### ISSUE TITLE
watchBalance function does't return info (untouched exchange response)

### ISSUE THREAD

**Issue by erenyavas** [ccxt/ccxt#16930]
### Operating System

windows 11

### CCXT Version

2.8.31

### Description

watchBalance function does't return info (untouched exchange response) so can't get some data like relationEvent.

fetchBalance function returns info (the original untouched non-parsed reply with details) [doc link](https://docs.ccxt.com/en/latest/manual.html#balance-structure)

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @erenyavas, which exchange are you using?

**Comment by erenyavas** [comment]
kucoin

**Comment by erenyavas** [comment]
@carlosmiei when i turn on verbose mode i can reach so much data about watchBalance but ccxt parse it so i can't reach what i want. I think ccxt should return a data like ['info'] which contains exchange response and didn't parse data. thanks

**Comment by carlosmiei** [comment]
Hello @erenyavas yes I agree, we will try to add it

**Comment by pcriadoperez** [comment]
Hey @carlosmiei I have a branch with the fix I'll push today. Also I'll double check to make sure it's not happening in other exchanges too.
Thanks for bringing it up @erenyavas
