### ISSUE TITLE
Bitget - Unable to Fetch Invalidated Stoploss

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#16939]
### Operating System

Windows 10

### CCXT Version

2.8.31

### Description

When I place a conditional market reduce-only order and it gets invalidated (being triggered without an underlying position), then it is not retrievable anymore via the fetch_order method although I can still see it in my order history on the exchange. 

Per code below, you will see that once the position is triggered it is not retrievable anymore and throws an IndexError. 

The issue could also be on the Exchange's end. 

### Code

```
import ccxt

# Define client
public = ""
private = ""
password = ""

client = ccxt.bitget({'apiKey': public, 'secret': private, 
					  'password': password})

# Parameters
ticker = "BTC/USDT:USDT"
side = 'buy'
quantity = 0.001
price = 23840
params = {'triggerPrice': price, 
		  'reduceOnly': True}

response = client.create_order(symbol=ticker, type="market", side=side,
                                           amount=quantity, price=None,
                                           params={'triggerPrice': price,
                                                   'reduceOnly': True})
	
# Get order information	
identifier = response['id']

params = {'stop': True}
closed = client.fetch_closed_orders(ticker, params=params)
active = client.fetch_open_orders(ticker, params=params)

both = closed + active
order = list(filter(lambda o: o['id'] == identifier, both))[0]

```

**Comment by carlosmiei** [comment]
Hello @Tomas-MP,
After looking into the docs, I think it might be possible using a different endpoint:(https://bitgetlimited.github.io/apidoc/en/mix/#get-plan-order-tpsl-list)

We will take a look:
cc\ @Dan-krm

**Comment by Tomas-MP** [comment]
@carlosmiei the code below indeed seems to do the trick. 

ticker = "BTC/USDT:USDT"
orders = client.fetch_closed_orders(ticker, params={'stop': True, 'isPlan': True})

It also seems that you guys have a fetch_canceled_orders and fetch_canceled_and_closed_orders method. Will check these out as well thanks.

**Comment by Dan-krm** [comment]
> @carlosmiei the code below indeed seems to do the trick.
> 
> ticker = "BTC/USDT:USDT" orders = client.fetch_closed_orders(ticker, params={'stop': True, 'isPlan': True})
> 
> It also seems that you guys have a fetch_canceled_orders and fetch_canceled_and_closed_orders method. Will check these out as well thanks.

Hey that's good to see that you were able to resolve the issue you were having. `params={'stop': True, 'isPlan': True}` should work for fetchClosedOrders, fetchCanceledOrders and fetchOpenOrders, the endpoint carlos mentioned is used in fetchOpenOrders
