### ISSUE TITLE
Binance spot margin fetch my trades broken

### ISSUE THREAD

**Issue by acodemics** [ccxt/ccxt#16949]
[out.log](https://github.com/ccxt/ccxt/files/10813136/out.log)

Attached a stripped down log of what happens - when using the symbol `BTCUSDT` and spot cross margin we correctly get a list of trades from the Binance API but then internally in CCXT `parse_trades` the trade symbol gets changed to `BTC/USDT:USDT` which is then filtered out by `filter_by_symbol_since_limit`.

```
Input:
{
    "symbol": "BTCUSDT",
    "id": "2761208980",
    "orderId": "18983877407",
    "price": "24602.24",
    "qty": "0.04056",
    "quoteQty": "997.8668544",
    "commission": "0",
    "commissionAsset": "BNB",
    "time": "1676980335115",
    "isBuyer": True,
    "isMaker": True,
    "isBestMatch": True,
    "isIsolated": False
}

Output:
{
    "info": {
        "symbol": "BTCUSDT",
        "id": "100",
        "orderId": "100",
        "price": "24602.24",
        "qty": "0.04056",
        "quoteQty": "997.8668544",
        "commission": "0",
        "commissionAsset": "BNB",
        "time": "1676980335115",
        "isBuyer": True,
        "isMaker": True,
        "isBestMatch": True,
        "isIsolated": False
    },
    "timestamp": 1676980335115,
    "datetime": "2023-02-21T11:52:15.115Z",
    "symbol": "BTC/USDT:USDT",
    "id": "100",
    "order": "100",
    "type": None,
    "side": "buy",
    "takerOrMaker": "maker",
    "price": 24602.24,
    "amount": 0.04056,
    "cost": 997.8668544,
    "fee": {
        "cost": 0.0,
        "currency": "BNB"
    },
    "fees": [
        {
            "cost": 0.0,
            "currency": "BNB"
        }
    ]
}
```

The above is the before and after from the Binance `parse_trade` method, it appears that the `marketType` variable condition is incorrect and returning `contract` even though it's spot margin. Spot margin trades from `myTrades` have a different structure to the non margin ones, specifically there is no `orderListId` field.

`marketType = ('isIsolated' in trade) or ('M' in trade) or 'spot' if ('orderListId' in trade) else 'contract'`]

Maybe a bad transpile? Converting the above line to a correct format works - 

` 'spot' if ('isIsolated' in trade) or ('M' in trade) or ('orderListId' in trade) else 'contract'`

_Originally posted by @acodemics in https://github.com/ccxt/ccxt/issues/16926#issuecomment-1441622827_

**Comment by carlosmiei** [comment]
Hello @acodemics,
Thanks for letting us know, I remember I fixed this specific issue, but probably the changes were lost somehow. I will patch it asap.

**Comment by acodemics** [comment]
Thanks!

I think your changes were added, you added an `isIsolated` condition right? The error here looks like the Python code is incorrectly generated from that change.

**Comment by carlosmiei** [comment]
> 

@acodemics I know, and I'm sure that after testing in Python I hit the exact same issue and pushed a new commit, but the commit probably didn't go through. Nonetheless, it will be fixed asap. Thanks once again.
