### ISSUE TITLE
How do I get a list of all available networks for coin withdrawal?

### ISSUE THREAD

**Issue by userxxx0** [ccxt/ccxt#16955]
### Programming Languages

python

### Description

How do I get a list of all available networks for coin withdrawal?

### Code

```
  

```

**Comment by userxxx0** [comment]
for example gate.io

**Comment by Dan-krm** [comment]
Hey you can use the implicit API: https://docs.ccxt.com/en/latest/manual.html#implicit-api
With this endpoint: https://www.gate.io/docs/developers/apiv4/en/#list-chains-supported-for-specified-currency
```
node examples/js/cli gate publicWalletGetCurrencyChains '{"currency":"ETH"}'

gate.publicWalletGetCurrencyChains ([object Object])
2023-02-25T02:58:24.421Z iteration 0 passed in 452 ms

  chain |       name_cn |       name_en | is_disabled | is_deposit_disabled | is_withdraw_disabled
--------------------------------------------------------------------------------------------------
    ETH |      以太坊ERC20 |     ETH/ERC20 |           0 |                   0 |                    0
    BSC |      智能链BEP20 |     BSC/BEP20 |           0 |                   0 |                    0
    ARB |  Arbitrum One |  Arbitrum One |           0 |                   0 |                    0
ARBNOVA | Arbitrum Nova | Arbitrum Nova |           0 |                   0 |                    0
  OPETH |      Optimism |      Optimism |           0 |                   0 |                    0
5 objects
```

### Python example:
```
  exchange = ccxt.gate({
      'apiKey': 'YOUR_API_KEY',
      'secret': 'YOUR_SECRET',
      # 'verbose': True,  # for debug output
  })
  try:
      response = exchange.publicWalletGetCurrencyChains({
          'currency': 'ETH',
      })
      pprint(response)
  except Exception as e:
      print('publicWalletGetCurrencyChains() failed')
      print(e)
```

Networks are in the early stages of being unified in CCXT and you can follow along with PR's like this one #16024 and perhaps in the future we will add specific methods for fetching networks by currency, but in the meantime you can use the implicit API with the above approach.

**Comment by userxxx0** [comment]
> Hey you can use the implicit API: https://docs.ccxt.com/en/latest/manual.html#implicit-api With this endpoint: https://www.gate.io/docs/developers/apiv4/en/#list-chains-supported-for-specified-currency
> 
> ```
> node examples/js/cli gate publicWalletGetCurrencyChains '{"currency":"ETH"}'
> 
> gate.publicWalletGetCurrencyChains ([object Object])
> 2023-02-25T02:58:24.421Z iteration 0 passed in 452 ms
> 
>   chain |       name_cn |       name_en | is_disabled | is_deposit_disabled | is_withdraw_disabled
> --------------------------------------------------------------------------------------------------
>     ETH |      以太坊ERC20 |     ETH/ERC20 |           0 |                   0 |                    0
>     BSC |      智能链BEP20 |     BSC/BEP20 |           0 |                   0 |                    0
>     ARB |  Arbitrum One |  Arbitrum One |           0 |                   0 |                    0
> ARBNOVA | Arbitrum Nova | Arbitrum Nova |           0 |                   0 |                    0
>   OPETH |      Optimism |      Optimism |           0 |                   0 |                    0
> 5 objects
> ```
> 
> ### Python example:
> ```
>   exchange = ccxt.gate({
>       'apiKey': 'YOUR_API_KEY',
>       'secret': 'YOUR_SECRET',
>       # 'verbose': True,  # for debug output
>   })
>   try:
>       response = exchange.publicWalletGetCurrencyChains({
>           'currency': 'ETH',
>       })
>       pprint(response)
>   except Exception as e:
>       print('publicWalletGetCurrencyChains() failed')
>       print(e)
> ```
> 
> Networks are in the early stages of being unified in CCXT and you can follow along with PR's like this one #16024 and perhaps in the future we will add specific methods for fetching networks by currency, but in the meantime you can use the implicit API with the above approach.

thank u! is there any way to find out the withdrawal fee?

**Comment by Dan-krm** [comment]
@userxxx0 Unfortunately I'm not seeing an endpoint for retrieving the withdrawal fee before making the withdrawal, you can however check the withdrawal fees for all currencies and chains on gate through this link under `Deposit & Withdraw`: https://www.gate.io/fee

There is also this endpoint for checking the fees you were charged on your executed withdrawals:
https://www.gate.io/docs/developers/apiv4/en/#retrieve-withdrawal-records
`privateWalletGetWithdrawals`
