### ISSUE TITLE
Create Order in ccxt bybit Testnet position idx not match position mode

### ISSUE THREAD

**Issue by hambi44** [ccxt/ccxt#16952]
### ؜

I want create a simple order in Derivates -> USDT Perpetual -> BTCUSDT. 

I have following Balance:
'coin': 'BTC', 'equity': '1.07893293', 'walletBalance': '1.07893293'

Here is my code:

import ccxt

exchange = ccxt.bybit({
    'apiKey': 'apiKey',
    'secret': 'secretKey',
    'enableRateLimit': True,
    'options': {
        'recvWindow': 10000,
    }
})
exchange.set_sandbox_mode(True)
exchange.options["defaultType"] = 'swap'
symbol = 'BTC/USDT:USDT'
order = exchange.createOrder(symbol=symbol, type='Market', side='buy', amount=0.01)

But i get this error:
bybit {"retCode":10001,"retMsg":"position idx not match position mode","result":{},"retExtInfo":{},"time":1677246036932}

Have somebody a solution?
Thanks

**Comment by carlosmiei** [comment]
Hello @hambi44,
Yes you just need to provide `positionIdx` inside params.

Example:
```Python
params = {
    'positionIdx': 1 #  0 One-Way Mode, 1 Buy-side, 2 Sell-side
}
symbol = 'BTC/USDT:USDT'
order = exchange.createOrder(symbol=symbol, type='Market', side='buy', amount=0.01, params = params)
```

**Comment by hambi44** [comment]
Best thanks. It works
