### ISSUE TITLE
Take Profit could be limit?

### ISSUE THREAD

**Issue by atilagf1** [ccxt/ccxt#16979]
### ؜

From docs:
**# Python
symbol = 'ETH/BTC'
type = 'limit'  # or 'market'
side = 'buy'
amount = 123.45  # your amount
price = 115.321  # your price
params = {
    'stopLoss': {
        'type': 'limit', # or 'market'
        'price': 100.33,
        'stopLossPrice': 101.25,
    },
    'takeProfit': {
        'type': 'market',
        'takeProfitPrice': 150.75,
    }
}
order = exchange.create_order (symbol, type, side, amount, price, params)**

Could I use take profit with limit? Or I can only use as market order and I would need to make an unattached limit order?

**Comment by sc0Vu** [comment]
Hi @atilagf1 

It depends on which exchange you used, and most exchange accept take profit order with limit.

**Comment by atilagf1** [comment]
Thank you.
