### ISSUE TITLE
can not get Binance future market data via exchange.fetch_ticker('BTC/USDT')

### ISSUE THREAD

**Issue by ctu1121** [ccxt/ccxt#16988]
### Operating System

Mac OS 13.2.1

### Programming Languages

Spyder(Pythpn3.9)

### CCXT Version

2023.02.28 newest version

### Description

can not get Binance future market data. 

### Code

exchange.fetch_ticker('BTC/USDT')
  

```

**Comment by sc0Vu** [comment]
Hi @ctu1121 

For future market, you can use symbol `BTC/USDT:USDT`. You can find our announcement for unified contract market ids (https://github.com/ccxt/ccxt/issues/10931).
