### ISSUE TITLE
Bybit fetch order book  InvalidNonce: bybit {"retCode":10002,"retMsg":"invalid request 

### ISSUE THREAD

**Issue by Nitrix321** [ccxt/ccxt#16985]
### ؜

OS: Windows 10
Programming Language version: Python Spyder
CCXT version: ccxt-2.8.5

Hello, suddenly this error message occurs on bybit if I try to fetch order book

on linear and inverse contracts:

symbol = 'ETH/USD:ETH'      
#symbol = 'ETH/USDT:USDT'

ob = bybit.fetch_order_book(symbol)
print(ob)

It's strange, sometimes it works, but most of the time not. 

fetch Request: bybit GET https://api.bybit.com/asset/v3/private/coin-info/query?api_key=xxxxxxx&recv_window=5000&timestamp=1677506205537&sign=32ca3cc122fd RequestHeaders: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bybit GET https://api.bybit.com/asset/v3/private/coin-info/query?api_key=xx&recv_window=5000&timestamp=1677506205537&sign=10e2260caad291a3cca6ca122fd 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '230', 'Connection': 'keep-alive', 'Date': 'Mon, 27 Feb 2023 13:56:44 GMT', 'Ret_code': '10002', 'Cache-Control': 'no-store', 'Traceid': '6ae755a29cf4ecf17981adea85a91c9f', 'Timenow': '1677506204520', 'Server': 'Openresty', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 c813ed55721b9ee3209e2abab7207a00.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'FRA56-P4', 'X-Amz-Cf-Id': '1Z1w298xreKvCBOT6WNf0q3hsPQ=='} ResponseBody: {"retCode":10002,"retMsg":"invalid request, please check your server timestamp or recv_window param. req_timestamp[1677506205537],server_timestamp[1677506204520],recv_window[5000]","result":{},"retExtInfo":{},"time":1677506204520}
Traceback (most recent call last):

  File "C:\Users\Dell\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\dell\desktop\bybit\bybittest1.py", line 48, in <module>
    bid = ask_bid()[1]

  File "c:\users\dell\desktop\bybit\bybittest1.py", line 35, in ask_bid
    ob = bybit.fetch_order_book(symbol)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\bybit.py", line 2697, in fetch_order_book
    self.load_markets()

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 1459, in load_markets
    currencies = self.fetch_currencies()

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\bybit.py", line 933, in fetch_currencies
    response = self.privateGetAssetV3PrivateCoinInfoQuery(params)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 505, in inner
    return entry(_self, **inner_kwargs)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 2833, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 2830, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 667, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\bybit.py", line 6773, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)

  File "C:\Users\Dell\anaconda3\Lib\site-packages\ccxt\base\exchange.py", line 3133, in throw_exactly_matched_exception
    raise exact[string](message)

InvalidNonce: bybit {"retCode":10002,"retMsg":"invalid request, please check your server timestamp or recv_window param. req_timestamp[1677506205537],server_timestamp[1677506204520],recv_window[5000]","result":{},"retExtInfo":{},"time":1677506204520}

**Comment by carlosmiei** [comment]
Hello @Nitrix321,
That error usually indicates a significant difference between your clock and the server's clock. I would suggest checking this thread: https://github.com/ccxt/ccxt/issues/14870

**Comment by Nitrix321** [comment]
OK, thanks, I will check.

**Comment by Nitrix321** [comment]
It seems working again. Tried several times now, looks good again, changed nothing!  Excuse me please, but I waited a while before reporting the problem. It's strange sometimes :-). 

{'symbol': 'ETH/USD:ETH', 'bids': [[1644.25, 48239.0], [1644.2, 928.0], [1644.15, 25491.0], [1644.1, 20750.0], [1644.05, 26310.0], [1644.0, 30012.0], [1643.95, 17765.0], [1643.9, 22388.0], [1643.85, 21418.0], [1643.8, 29956.0], [1643.75, 16877.0], [1643.7, 44274.0], [1643.65, 148.0], [1643.6, 22086.0], [1643.55, 9973.0], [1643.5, 36885.0], [1643.45, 19981.0], [1643.4, 16029.0], [1643.35, 16558.0], [1643.3, 9987.0], [1643.25, 12487.0], [1643.2, 15535.0], [1643.15, 19962.0], [1643.1, 19962.0], [1643.05, 29979.0]], 'asks': [[1644.3, 84828.0], [1644.35, 809.0], [1644.4, 1243.0], [1644.45, 10000.0], [1644.5, 40611.0], [1644.55, 5197.0], [1644.6, 42481.0], [1644.65, 28104.0], [1644.7, 33163.0], [1644.75, 22120.0], [1644.8, 870.0], [1644.85, 103988.0], [1644.9, 91177.0], [1644.95, 9973.0], [1645.0, 9973.0], [1645.1, 10979.0], [1645.15, 14924.0], [1645.2, 19975.0], [1645.25, 45312.0], [1645.3, 63343.0], [1645.35, 166157.0], [1645.4, 327989.0], [1645.45, 129987.0], [1645.5, 22824.0], [1645.55, 139970.0]], 'timestamp': 1677514207804, 'datetime': '2023-02-27T16:10:07.804Z', 'nonce': None}
