### ISSUE TITLE
New exchange: bit.team

### ISSUE THREAD

**Issue by AndreiKozak** [ccxt/ccxt#16982]
API Doc: https://bit.team/trade/api/documentation#/CCXT
URL: https://bit.team
Fee: 0.2%
Volume: $1,153,166
Address: 85 Great Portland Street, First Floor, London, England, W1W 7LT
Company Info: NDAX
TNC: https://bit.team/docs
Registration: UK
Based Country: UK
Whitepaper: --
Priority: normal
Github group: https://github.com/orgs/bitteamgroup/teams/bit-team
Note: ranked top : NA
Type: Centrailzed Ex
Discussion: https://t.me/BitteamLive

**Comment by ttodua** [comment]
exchange had been implemented in ccxt https://github.com/ccxt/ccxt/pull/20049
