### ISSUE TITLE
Binance-USD-M: fetch_my_trades() return unexpected empty list

### ISSUE THREAD

**Issue by Chakyiu** [ccxt/ccxt#16986]
### Operating System

Mac OS

### Programming Languages

python

### CCXT Version

2.8.17

### Description

I was using ccxt.binance(), ccxt.binancecoinm() and ccxt.binanceusdm() and use fetch_my_trades() to try to get all my trades record. binance and binancecoinm functions as expected. However, binanceusdm always return empty list but I pretty sure I have trade record in my binance USD-M account.

![image](https://user-images.githubusercontent.com/49145984/221616585-9f840b17-7736-498c-a651-e8a9a893f4cf.png)

### Code

```python
import ccxt

binance_usd_m = ccxt.binanceusdm({
          'apiKey': config.api,
          'secret': config.secret,
          'verbose': True
      })

# I have try different symbol format _BTCBUSD_ / _BTC/BUSD_ / BTC/BUSD:BUSD_ according to market info.
trades = binance_usd_m.fetch_my_trades(symbol='BTCBUSD', since=binance_usd_m.milliseconds() - 30 * 86400 * 1000)
print(trades, flush=True) # always return []
```

**Comment by sc0Vu** [comment]
Hi @Chakyiu 

Based on their documentation (https://binance-docs.github.io/apidocs/futures/en/#account-trade-list-user_data), have you checked the time between startTime and endTime not be longer than 7 days?

**Comment by Chakyiu** [comment]
@sc0Vu You save my life. I spent a couple of days on it... Thanks for your help!
