### ISSUE TITLE
CCXT For Binance Futures slow ... is speedup possible ?

### ISSUE THREAD

**Issue by spc789** [ccxt/ccxt#16997]
### ؜

Using : OS : Linux 5.4.0 | CCXT version : ccxt 2.8.37 ccxtpro 1.0.1 | Python 3.9
Ping times to all 4 binance api and fapi clusters are in the range 25~40ms 
Ratelimit False | Using binance futures

Using following code (not complete) :

```
for i in range(5):
     try:
          order = exchange.create_order(symbol=symbol, type='STOP_MARKET', side='buy', amount=order_sizes[i], params={'leverage': leverage, 'stopPrice': buy_prices[i], 'quantity': order_sizes[i], 'closePosition': False })
     except Exception as e:
          print(f"==> {e}")
          cancelAllStopOrders(symbol, "ERROR")
          sys.exit(-1)

```

which is a simple loop, just placing orders, no software delays gives at the python side (local time timestamps). 
There is aprox a 300ms spacing between the order placement.

> [ 12:16:12.832 ]        Initial buy stop order 1 placed [ 2957100834 ]
> [ 12:16:13.132 ]        Initial buy stop order 2 placed [ 2957100838 ]
> [ 12:16:13.443 ]        Initial buy stop order 3 placed [ 2957100847 ]
> [ 12:16:14.179 ]        Initial buy stop order 4 placed [ 2957100859 ]
> [ 12:16:14.912 ]        Initial buy stop order 5 placed [ 2957100868 ]

On the binance side (checked with a watch_orders websocket loop) timestamps seem to be aggregated. (Those timestamps are the same as seen in the webclient)(GMT Timestamps)

> 11:16:12.1677579372 BUY STOP_MARKET 2957100834 NEW 
> 11:16:13.1677579373 BUY STOP_MARKET 2957100838 NEW 
> 11:16:13.1677579373 BUY STOP_MARKET 2957100847 NEW 
> 11:16:14.1677579374 BUY STOP_MARKET 2957100859 NEW 
> 11:16:14.1677579374 BUY STOP_MARKET 2957100868 NEW 

- Are there some parameters or other methods to make that binance doesn't "aggregate" order execution ? 
- Are there other ways to speed up order creation ?
- Is the cancelAndReplace binance order allready integreted in CCXT ? (it could shave off some other secs in other part of the code)

**Comment by carlosmiei** [comment]
Hello @spc789, If you have the rate limiter off, there's not much you can do on the ccxt side. You can, however, try to relocate your server closer to Binance's server to reduce the delay. 

Also if you're not loading the markets before placing the order, I'd highly suggest you to do it because the first unified call has to load the markets if they're not loaded yet (`await exchange.load_markets()`

> Is the cancelAndReplace binance order allready integreted in CCXT ? (it could shave off some other secs in other part of the code)

Yes, check the `editOrder` method.

**Comment by spc789** [comment]
Hi @carlosmiei , load_markets() is loaded before. It's just a code snippet. Did you notice the timestamps on the binance sides ? For example there are two orders on *the same* timestamp which ends in 73, two orders on *the same* timestamp ending in 74. It looks like for some reason binance (or something others) "groups" orders... 
.

**Comment by spc789** [comment]
In some other thread (https://github.com/ccxt/ccxt/issues/10661) there was talk about making ccxt compilable (for example C++). 
Is there any progress on that one ? Or is cythonising the ccxt code an option ?

**Comment by carlosmiei** [comment]
> In some other thread (#10661) there was talk about making ccxt compilable (for example C++). Is there any progress on that one ? Or is cythonising the ccxt code an option ?

@spc789 We don't have much progress towards that yet, but I'm sure that if you're just placing some orders the language is not the bottleneck here. Recently we made some benchmarks against a Rust and C++ library and we didn't notice a degradation in performance (comparing only order placement)
