### ISSUE TITLE
What is the difference between BTC/USDT:USDT and BTC/USDT symbols?

### ISSUE THREAD

**Issue by kerimSD** [ccxt/ccxt#16998]
### ؜

OS: Windows 
Programming Language version: Nodejs
CCXT version: ccxt 2.8

When I fetch symbols from gateio with fetchMarkets() method, I see some symbols called
ETH/USDT:USDT, BTC/USDT:USDT etc. Why those are called like that?

And what is the difference between BTC/USDT:USDT and BTC/USDT ?

**Comment by sc0Vu** [comment]
Hi @kerimSD 


ETH/USDT:USDT
You can find it in unified naming announcement (https://github.com/ccxt/ccxt/issues/10931).

**Comment by kerimSD** [comment]
> Hi @kerimSD
> 
> ETH/USDT is for spot, and ETH/USDT:USDT is for contract swap (perpetual).
> 
> You can find it in unified naming announcement (#10931).

thanks 👍
