### ISSUE TITLE
Please add bingx 

### ISSUE THREAD

**Issue by fotrosi** [ccxt/ccxt#17011]
### Exchange Name

Bingx

### URL of the Exchange

https://bingx.com/en-us/

### URL of the Exchange's API docs

https://bingx-api.github.io/docs/swap/introduce.html

### Why should this exchange be implemented?

Rank 36 on the https://coinmarketcap.com/rankings/exchanges/

**Comment by sc0Vu** [comment]
Duplicated issue: ccxt/ccxt#13206
