### ISSUE TITLE
Node.js function fetchOrderBook for new Coinbase exchange

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#17024]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

For the new Coinbase exchange, the fetchOrderBook is not implemented or not having some example to use.
I provide some example code to use node.js to use fetchOrderBook functions.

### Describe the solution you'd like

There is one way to use Node JS to fetchOrderBook for the new Coinbase exchange.
Steps:
1) npm install axios (version 1.3.4)
2) Write the following level1.js code:
const axios = require('axios');

let config = {
  method: 'get',
maxBodyLength: Infinity,
  url: 'https://api.exchange.coinbase.com/products/BTC-USDT/book?level=1',
  headers: { 
    'Content-Type': 'application/json'
  }
};

axios(config)
.then((response) => {
  console.log(JSON.stringify(response.data));
})
.catch((error) => {
  console.log(error);
});
3) Run the level1.js code:
D:\nodejs\CCXT\coinbase>node level1.js
{"bids":[["23427.36","0.04601012",1]],"asks":[["23431.75","0.11",2]],"sequence":7373980045,"auction_mode":false,"auction":null}

4) Make a level2.js script:
const axios = require('axios');

let config = {
  method: 'get',
maxBodyLength: Infinity,
  url: 'https://api.exchange.coinbase.com/products/BTC-USD/book?level=2',
  headers: { 
    'Content-Type': 'application/json'
  }
};

axios(config)
.then((response) => {
  console.log(JSON.stringify(response.data));
})
.catch((error) => {
  console.log(error);
});
5) Run level2.js:
D:\nodejs\CCXT\coinbase>node level2.js
{"bids":[["23432.57","0.2010786",6],["23431.76","0.03200673",1],["23431.75","0.03200673",1],["23431.47","0.032011",1],["23431.09","0.05",1],["23431.08","0.79354399",1],["23431.07","1.07736612",3],["23431.06","0.08535676",1],["23430.83","0.16173828",1],["23430.82","0.64625591",1],["23430.81","0.32128621",1],["23429.8","0.00085354",1],…...["21059483","0.0025",1],["32438915","0.0001",1],["48322747.41","0.25",1],["1000000000","1",1],["9999999999","0.00019602",1]],"sequence":55881110657,"auction_mode":false,"auction":null}

For API document, refer to this URL:
https://docs.cloud.coinbase.com/exchange/reference/exchangerestapi_getproductbook

### Describe alternatives you've considered

The other ways like using wss is too complicated.
Using the above code is much easier!
Please consider to add this to new release of CCXT, the ccxt current version is: 2.8.69. I am using Windows 10 OS.

**Comment by Dan-krm** [comment]
You can access this endpoint using the coinbasepro class and fetchOrderBook instead of the coinbase class

**Comment by zydjohnHotmail** [comment]
Hi,
I don't quite understand your meaning.
Can you share the code sample for using coinbasepro class in CCXT?
Thanks,

**Comment by Dan-krm** [comment]
`node examples/js/cli coinbasepro fetchOrderBook BTC/USDT`

instead of:

`node examples/js/cli coinbase fetchOrderBook BTC/USDT`

or
```
const exchange = new ccxt.coinbasepro({
    apiKey: "YOUR_API_KEY",
    secret: "YOUR_SECRET",
})
```
python:
```
exchange = ccxt.coinbasepro({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
})
```
