### ISSUE TITLE
call apikey from json and see error: binance {"code":-2008,"msg":"Invalid Api-Key ID."}

### ISSUE THREAD

**Issue by ctu1121** [ccxt/ccxt#17031]
### Operating System

macOS

### Programming Languages

python

### CCXT Version

newest

### Description

If I write apiky on python, it is ok to place order.
However, I try to call apikey from json file to place order for binance spot instrument, and see the error as below:
binance {"code":-2008,"msg":"Invalid Api-Key ID."}

Please advise where could I revise. Thanks.

 

### Code

with open("API.json", 'r') as f:
     text = f.read()
     print(text)
  
   
exchange = ccxt.binance({
      'enableRateLimit': True,
      'apiKey':'A',
      'secret':'B',
      'options': {
      'defaultType': 'spot',
        },
        })
                
    

b="CFXUSDT"    

order = exchange.create_order(
  symbol=b,
  type='STOP_LOSS_LIMIT',
  amount=35,
  price=0.32,
  side='buy',
  params={'stopPrice': 0.32}
)

**Comment by kroitor** [comment]
@ctu1121 in your code you're not reading JSON as JSON, you're reading it as text. Also make sure that you're passing the contents of API.json as `apiKey` and `secret` to the exchange constructor. Apart from that you're missing the `await` keyword with `exchange.create_order`, cause it returns a JS Promise. 

In short, this is not a question on how to use CCXT, but more like a question on the basics of JavaScript / Node.js programming.

If your `API.json` looks like this:

```JSON
{
    "apiKey": "XXXXXXXXXXXXXXXXXX",
    "secret": "YYYYYYYYYYYYYYYYYYY"
}
```

Then your code should look like this:

```JavaScript

const config = require('API.json')

exchange = ccxt.binance(config)

b="CFXUSDT"

order = await exchange.create_order(
symbol=b,
type='STOP_LOSS_LIMIT',
amount=35,
price=0.32,
side='buy',
params={'stopPrice': 0.32}
)
```
