### ISSUE TITLE
Bybit unable to retrieve balance

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#17036]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

2.8.80

### Description

I am unable to retrieve the balance of my futures account after updating CCXT. 

### Code

```
public = ""
private = "" 

client = ccxt.bybit({'apiKey': public, 'secret': private})
client.options['defaultType'] = 'swap'

info = client.fetch_balance()

```
Traceback (most recent call last):

  Cell In[6], line 1
    info = client.fetch_balance()

  File ~\anaconda3\lib\site-packages\ccxt\bybit.py:3014 in fetch_balance
    return self.fetch_derivatives_balance(self.extend(query, {'type': 'swap'}))

  File ~\anaconda3\lib\site-packages\ccxt\bybit.py:2928 in fetch_derivatives_balance
    response = self.privateGetV5AccountWalletBalance(self.extend(request, params))

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:505 in inner
    return entry(_self, **inner_kwargs)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2833 in request
    return self.fetch2(path, api, method, params, headers, body, config, context)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2830 in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:667 in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File ~\anaconda3\lib\site-packages\ccxt\bybit.py:7842 in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:3133 in throw_exactly_matched_exception
    raise exact[string](message)

BadRequest: bybit {"retCode":10001,"retMsg":"params error: account_type only support CONTRACT","result":{},"retExtInfo":{},"time":1677832203557}

**Comment by Tomas-MP** [comment]
It seems to work when using params={'accountType': 'contract'} as an argument

**Comment by carlosmiei** [comment]
Hello @Tomas-MP thanks for reporting it, it will be fixed here very soon: https://github.com/ccxt/ccxt/pull/17033/files

**Comment by carlosmiei** [comment]
@Tomas-MP It should be fixed now if you update to the latest version
