### ISSUE TITLE
Bid and ask sizes are None for coinbase ticker updates

### ISSUE THREAD

**Issue by L1nkus** [ccxt/ccxt#17037]
Hi,

{'symbol': 'USDT-USD', 'timestamp': 1677833804822, 'datetime': '2023-03-03T08:56:44.822Z', 'high': 1.00076, 'low': 0.9999, 'bid': 1.00026, 'bidVolume': None, 'ask': 1.00027, 'askVolume': None, 'vwap': None, 'open': 1.00008, 'close': 1.00027, 'last': 1.00027, 'previousClose': None, 'change': None, 'percentage': None, 'average': None, 'baseVolume': 165900854.89, 'quoteVolume': None, 'info': {'type': 'ticker', 'sequence': 585493821, 'product_id': 'USDT-USD', 'price': '1.00027', 'open_24h': '1.00008', 'volume_24h': '165900854.89000000', 'low_24h': '0.9999', 'high_24h': '1.00076', 'volume_30d': '3242791564.59000000', 'best_bid': '1.00026', 'best_bid_size': '174038.39', 'best_ask': '1.00027', 'best_ask_size': '52775.89', 'side': 'buy', 'time': '2023-03-03T08:56:44.822229Z', 'trade_id': 38620183, 'last_size': '263.75'}}

There is 'best_bid_size' and 'best_ask_size' in 'info', but 'bidVolume' and 'askVolume' are none

**Comment by carlosmiei** [comment]
Hello @L1nkus,
I think that `best_bid_size` or `best_ask_size` represent the `best_bid`/`best_ask` volume, not the overall `ask`/`bid` volume.

**Comment by L1nkus** [comment]
> Hello @L1nkus,
> I think that `best_bid_size` or `best_ask_size` represent the `best_bid`/`best_ask` volume, not the overall `ask`/`bid` volume.

From ccxt docs:

The structure of a ticker is as follows:

{
    'symbol':        string symbol of the market ('BTC/USD', 'ETH/BTC', ...)
    'info':        { the original non-modified unparsed reply from exchange API },
    'timestamp':     int (64-bit Unix Timestamp in milliseconds since Epoch 1 Jan 1970)
    'datetime':      ISO8601 datetime string with milliseconds
    'high':          float, // highest price
    'low':           float, // lowest price
    'bid':           float, // current best bid (buy) price
    'bidVolume':     float, // current best bid (buy) amount (may be missing or undefined)
    'ask':           float, // current best ask (sell) price
    'askVolume':     float, // current best ask (sell) amount (may be missing or undefined)
    'vwap':          float, // volume weighed average price
    'open':          float, // opening price
    'close':         float, // price of last trade (closing price for current period)
    'last':          float, // same as `close`, duplicated for convenience
    'previousClose': float, // closing price for the previous period
    'change':        float, // absolute change, `last - open`
    'percentage':    float, // relative change, `(change/open) * 100`
    'average':       float, // average price, `(last + open) / 2`
    'baseVolume':    float, // volume of base currency traded for last 24 hours
    'quoteVolume':   float, // volume of quote currency traded for last 24 hours
}
Notes On Ticker Structure

All fields in the ticker represent the past 24 hours prior to timestamp.
The bidVolume is the volume (amount) of current best bid in the orderbook.
The askVolume is the volume (amount) of current best ask in the orderbook.
The baseVolume is the amount of base currency traded (bought or sold) in last 24 hours.
The quoteVolume is the amount of quote currency traded (bought or sold) in last 24 hours.

I think the wiki says that those fields are meant to represent the current volumes on best levels?

**Comment by Dan-krm** [comment]
@L1nkus Which method are you using? I'm not able to find `best_bid_size` or `best_ask_size` using fetchTicker of fetchTickers

**Comment by L1nkus** [comment]
> @L1nkus Which method are you using? I'm not able to find `best_bid_size` or `best_ask_size` using fetchTicker of fetchTickers

@Dan-krm from ccxt.pro watchTicker

**Comment by Dan-krm** [comment]
> > @L1nkus Which method are you using? I'm not able to find `best_bid_size` or `best_ask_size` using fetchTicker of fetchTickers
> 
> @Dan-krm from ccxt.pro watchTicker

Thanks for pointing this out, I opened a PR that will resolve this issue
