### ISSUE TITLE
Bitget stop limit order does not update "filled" in response

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#17041]
### Operating System

Windows 10

### CCXT Version

2.8.80

### Description

When placing a stop limit order which eventually gets filled, the "filled" key within the response dictionary still shows None. The order has been executed on the exchange though. 

### Code

```
    
    import ccxt

    public = ""
    private = ""
    password = ""

    client = ccxt.bitget(
        {'apiKey': public, 'secret': private, 'password': password})

    ticker = 'XRP/USDT:USDT'
    side = 'sell'
    quantity = 453
    price = 0.3672

    response = client.create_order(symbol=ticker, type="limit", side=side,
                                   amount=quantity, price=price,
                                   params={'triggerPrice': price,
                                           'triggerType': 'fill_price'})

    identifier = response['id']
    active = (client.fetch_open_orders(ticker, params={'stop': True})
              + client.fetch_open_orders(ticker))
    order = list(filter(lambda o: o['id'] == identifier, active))[0]
    print(order)
```
{'info': {'orderId': '1015554957507104769',
  'executeOrderId': '1015555290507677700',
  'symbol': 'XRPUSDT_UMCBL',
  'marginCoin': 'USDT',
  'size': '453',
  'executePrice': '0',
  'triggerPrice': '0.3672',
  'status': 'triggered',
  'orderType': 'limit',
  'planType': 'normal_plan',
  'side': 'open_short',
  'triggerType': 'fill_price',
  'presetTakeProfitPrice': '0',
  'presetTakeLossPrice': '0',
  'rangeRate': None,
  'executeTime': '1677853170070',
  'executeSize': '453',
  'cTime': '1677853090645'},
 'id': '1015554957507104769',
 'clientOrderId': None,
 'timestamp': 1677853090645,
 'datetime': '2023-03-03T14:18:10.645Z',
 'lastTradeTimestamp': None,
 'symbol': 'XRP/USDT:USDT',
 'type': 'limit',
 'timeInForce': None,
 'postOnly': None,
 'side': 'sell',
 'price': None,
 'stopPrice': 0.3672,
 'triggerPrice': 0.3672,
 'average': None,
 'cost': None,
 'amount': 453.0,
 'filled': None,
 'remaining': None,
 'status': 'closed',
 'fee': None,
 'trades': [],
 'fees': [],
 'reduceOnly': None}

**Comment by Dan-krm** [comment]
From the API response you can see that Bitget doesn't provide us with any data to populate the filled key for stop orders:
```
                     {
                         "orderId": "910246821491617792",
                         "symbol": "BTCUSDT_UMCBL",
                         "marginCoin": "USDT",
                         "size": "16",
                         "executePrice": "20000",
                         "triggerPrice": "24000",
                         "status": "triggered",
                         "orderType": "limit",
                         "planType": "normal_plan",
                         "side": "open_long",
                         "triggerType": "market_price",
                         "presetTakeProfitPrice": "0",
                         "presetTakeLossPrice": "0",
                         "cTime": "1652745674488"
                     }
```

You should be able to use `fetchOrder` without the stop flag in the params to find the filled amount
