### ISSUE TITLE
Bybit v5 update breaks bybit spot mode

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#17054]
### Operating System

linux

### Programming Languages

python

### CCXT Version

2.8.88

### Description

Running bybit in spot mode breaks fetch_tickers (multiple).

It appears like all overlapping pairs (where there is both a spot and a futures market) are converted to futures naming wrongly (i'm in spot mode).

### Code

``` python
import ccxt
exchange = ccxt.bybit({'options': {'defaultType': 'spot'}})
mark = exchange.load_markets()
t = exchange.fetch_tickers()
assert 'BTC/USDT' in t    # Breaks
'BTC/USDT:USDT' in t     # Should not be in fetch_tickers() for spot market.
```

**Comment by carlosmiei** [comment]
Hey @xmatthias, yeah that's not expected I will take a look asap.
Thanks for letting us know.
