### ISSUE TITLE
bybit v5 upgrade breaks fetch_total_balance for unified account

### ISSUE THREAD

**Issue by cowboyee** [ccxt/ccxt#17057]
### Operating System

Mac OS

### Programming Languages

Python

### CCXT Version

2.8.88

### Description

method in fetch_balance in bybit.py is still V3

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @cowboyee 

You can get unified balance with these parameters before we update this (remember to authorize transfer permission).

```python
fetch_total_balance ({"type":"fund","accountType":"UNIFIED"})
```

We'll update this asap.

**Comment by sc0Vu** [comment]
Close this issue because we already integrated bybit v5 api.
