### ISSUE TITLE
gate.io & bter fetch/create deposit address

### ISSUE THREAD

**Issue by kornrunner** [ccxt/ccxt#1705]
I want to implement fetch/create deposit address methods for gateio as per their API spec: https://gate.io/api2

However, I see that given class extends `bter`, so I wanted to define it in base, but their API docs seem to be gone: https://bter.com/api2

So I'm not sure if I should implement in `gateio` only, or just do the fingercrossed one in `bter` and let `gateio` inherit it and hope that it will work for `bter` too?

Thanks!

**Comment by kroitor** [comment]
@kornrunner well, that was big news last year
- https://bitcointalk.org/index.php?topic=956738.0
- https://hype.codes/btercom-closing-down?page=49
- https://github.com/ccxt/ccxt/issues/353

In the end of the story, bter told their users to migrate to gateio... Afaik, bter is not working anymore, so we can probably remove it entirely, and move all implementation to gateio.

**Comment by kornrunner** [comment]
Thanks, didn't know that! 

For the sake of simplicity, I think I'll implement new stuff in `gateio` and submit another PR to merge / drop `bter` if that's okay with you.

**Comment by kroitor** [comment]
Sounds awesome! Thx!
