### ISSUE TITLE
Bybit V5 Unified Accout, no support for WatchOrders

### ISSUE THREAD

**Issue by kingkong404** [ccxt/ccxt#17064]
### CCXT Version

2.8.97

### Description

After upgrading my account to a unified account on Bybit, WatchOrders no longer functions using the V3 API. I believe watchOrders needs to be upgraded to support new v5 API as well. 

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @kingkong404, 
You're right. We need to update the WS side as well; we will try to do it as soon as possible.

**Comment by sc0Vu** [comment]
Hi @kingkong404 

Before upgrade ccxt pro to v5, would you like to see whether the watch balance works if set `"enableUnifiedMargin": true,`? (The unified margin v3 endpoint works for me.)

**Comment by kingkong404** [comment]
> Hi @kingkong404
> 
> Before upgrade ccxt pro to v5, would you like to see whether the watch balance works if set `"enableUnifiedMargin": true,`? (The unified margin v3 endpoint works for me.)

Hi @sc0Vu 

I updated my bybit instance to 
```
export const bybit = new ccxtpro.bybit({
  apiKey: process.env.BYBIT_API,
  secret: process.env.BYBIT_SECRET,
  enableRateLimit: true,
  options: { enableUnifiedMargin: true },
})
```

and ran 
```
    while (true) {
      const res = await bybit.watchBalance()
      logger.debug(res)
    }
```

I then opened a BTC long and closed it and got **no updates** in the watchBalance. 
NOTE: I am on a unified account and on CCXT version 2.9.6

**Comment by sc0Vu** [comment]
Hi @kingkong404 

It should receive update when create order (the balance changed). My account works might be I upgraded to unified margin before. Not sure whether that is reason. (we are working on the websocket updates.)

BTW, would you like to check whether the endpoint is `wss://stream.bybit.com/unified/private/v3` in the verbose output?

eg,
```
connecting to wss://stream.bybit.com/unified/private/v3
```

**Comment by hanxuh-hub** [comment]
> Hi @kingkong404
> 
> It should receive update when create order (the balance changed). My account works might be I upgraded to unified margin before. Not sure whether that is reason. (we are working on the websocket updates.)
> 
> BTW, would you like to check whether the endpoint is `wss://stream.bybit.com/unified/private/v3` in the verbose output?
> 
> eg,
> 
> ```
> connecting to wss://stream.bybit.com/unified/private/v3
> ```

I have the same problem as what @kingkong404 described. I can see `connecting to wss://stream.bybit.com/unified/private/v3` but still the method does not work. I guess you are right that it works on your end because you upgraded to unified margin.

**Comment by hodlerhacks** [comment]
Hi, as this issue hasn't been closed yet, I wanted to check what the status is. Is watchOrders now supported for Bybit unified accounts? (I can't test myself, but need to understand if my application will work for Bybit users.) Same question for watchTrades.

**Comment by hanxuh-hub** [comment]
> Hi, as this issue hasn't been closed yet, I wanted to check what the status is. Is watchOrders now supported for Bybit unified accounts? (I can't test myself, but need to understand if my application will work for Bybit users.) Same question for watchTrades.

I believe watchOrders in v5 unified account is already supported in the latest release. This issue should be closed? @sc0Vu @carlosmiei

**Comment by carlosmiei** [comment]
> > Hi, as this issue hasn't been closed yet, I wanted to check what the status is. Is watchOrders now supported for Bybit unified accounts? (I can't test myself, but need to understand if my application will work for Bybit users.) Same question for watchTrades.
> 
> I believe watchOrders in v5 unified account is already supported in the latest release. This issue should be closed? @sc0Vu @carlosmiei

Hello @kingkong404 @hodlerhacks yeah it should be working now
