### ISSUE TITLE
ccxt mexc3 error for only specific symbols : {"code":10007,"msg":"bad symbol"}

### ISSUE THREAD

**Issue by vwy089** [ccxt/ccxt#17069]
### Operating System

windows10

### Programming Languages

python

### CCXT Version

2.7.3

### Description

There is a weird error when using 'create_order()' in ccxt package.

the below code works well for ADA/USDT, ADAUSDT, QTUM/USDT, QTUMUSDT
But cause an error when setting symbol = 'BTCUSDT' or 'BTC/USDT' or 'ETHUSDT' or 'ETH/USDT'

* {"code":10007,"msg":"bad symbol"}

what am I missing?

I really appreciate your help!!!
thanks!

### Code

```
bot = ccxt.mexc3(config ={'apiKey':key1,'secret':key2,'enableRateLimit': True})

symbol = "BTCUSDT"
quantity = 0.001
price = 20000
res = bot.create_order(
    symbol=symbol,
    amount=quantity,
    price=price,
    type='limit',
    side='buy',
)  

```

**Comment by snakeaid** [comment]
MEXC is having API maintenance and upgrade for these symbols right now.
https://support.mexc.com/hc/en-001/articles/15020779966105
https://support.mexc.com/hc/en-001/articles/15149585234969

**Comment by vwy089** [comment]
I really appreciate it!

**Comment by hosseinab** [comment]
@snakeaid i have this problem with EOS/USDT

**Comment by Sosyetekadir** [comment]
10007
