### ISSUE TITLE
Code returns  NotSupported: huobi fetchTransactionFees() is not supported yet with whom it has worked before

### ISSUE THREAD

**Issue by AlwxDavydov** [ccxt/ccxt#17086]
### Operating System

Windows 10 

### Programming Languages

python

### CCXT Version

2.8.31

### Description

I got this error: NotSupported: huobi fetchTransactionFees() is not supported yet with all exchangers that I tried to use. I tried mexc, kucoin and huobi. And if I'am not mistaken it worked with all this exchangers in past. Please tell me is it a bug or It's really not supported right now. And if it's not please tell me all exchangers that support it. Thank you.

### Code

data = ccxt.kucoin({apikey:xxxxxx, secret:'xxxxxxxxxxxxxx'}).fetch_transaction_fees()
print(data)

**Comment by carlosmiei** [comment]
Hello @AlwxDavydov,
`fetchTransactionFees` was deprecated and replaced with `fetchDepositWithdrawFees`.  Can you try to use the latter instead?

**Comment by AlwxDavydov** [comment]
@carlosmiei Thank you, I tried it. So it helped with huobi. As for the kuсoшn, I only see fetch_deposit_withdraw_fee. It turns out that fetch_deposit_withdraw_fee() is not ralized for him? The strangest answer I get is in the case of Mexc. He will return 3042, in fetch_deposit_withdraw_fee
    if not self.has['fetchDepositWithdrawFees']:
KeyError: 'fetchDepositWithdrawFees'

**Comment by AlwxDavydov** [comment]
Little example of code 
import ccxt
import sys

sys.stdout.reconfigure(encoding='utf-8')

exchange = ccxt.mexc()
deposit_addresses = exchange.fetch_deposit_withdraw_fee('USDT')
print(deposit_addresses)

**Comment by AlgoQ** [comment]
@AlwxDavydov That's right, kucoin does only support the `fetch_deposit_withdraw_fee()` function but not the `fetch_deposit_withdraw_fees()` function.

Whenever you use *mexc* you make use of version 2 of mexc's api, version 2 doesn't support `fetch_deposit_withdraw_fee()`/ `fetch_deposit_withdraw_fees()`, *mexc3* does support both tho.

Code example:
```python
import ccxt

exchange = ccxt.mexc3({api:'xxx', secret:'xxx'}) 

deposit_withdraw_fee = exchange.fetch_deposit_withdraw_fee('USDT')
print(deposit_withdraw_fee)
```
