### ISSUE TITLE
Precision error when creating market buy order

### ISSUE THREAD

**Issue by lindomar-oliveira** [ccxt/ccxt#17085]
### ؜

**OS:** Linux, Mac
**Programming Language:** Python
**CCXT Version:** 2.9.7

**Description**
When creating a market purchase order on **Bybit**, the error occurs::
https://github.com/ccxt/ccxt/blob/1655c1f00b1fa0e7d82acfce34a859468055f319/python/ccxt/base/exchange.py#L3307

Which in my investigation, as it is described here:
https://github.com/ccxt/ccxt/blob/1655c1f00b1fa0e7d82acfce34a859468055f319/python/ccxt/bybit.py#L3365

But when running cost precision, **market['precision']['amount']** is used instead of **market['precision']['price']**, which works correctly
https://github.com/ccxt/ccxt/blob/1655c1f00b1fa0e7d82acfce34a859468055f319/python/ccxt/base/exchange.py#L3305

Because it would not be the amount of the base asset, but the cost that is related to the quote asset.

**Comment by carlosmiei** [comment]
Hello @lindomar-oliveira,
Which values are you using for `price` and `amount`? Also is it possible to provide a verbose log/stacktrace?

**Comment by lindomar-oliveira** [comment]
@carlosmiei Of course, below is a code to reproduce the error.

```py
import ccxt

cli = ccxt.bybit({
    'apiKey': 'MY_API_KEY',
    'secret': 'MY_API_SECRET',
    'options': {
        'defaultType': 'spot'
    }
})
cli.verbose = True

symbol = 'MATIC/BTC'
ticker = cli.fetch_ticker(symbol)
cli.create_order(symbol, side='buy', type='market', amount=10, price=ticker['bid'])
```
