### ISSUE TITLE
How to use version 2.9.7 to get balance for new Coinbase exchange?

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#17084]
### Operating System

Windows 10

### Programming Languages

JS

### CCXT Version

2.9.7

### Description

Hello:
I tried the following code to get my account balance with new Coinbase exchange:
But I got error.
C:\CCXT>node coinbase_getExchangeBalance.js
2.9.7
AuthenticationError: coinbase GET https://api.coinbase.com/api/v3/brokerage/products 401 Unauthorized Unauthorized

    at coinbase.handleHttpStatusCode (C:\CCXT\node_modules\ccxt\js\base\Exchange.js:759:19)
    at C:\CCXT\node_modules\ccxt\js\base\Exchange.js:606:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async timeout (C:\CCXT\node_modules\ccxt\js\base\functions\time.js:181:20)
    at async coinbase.fetch2 (C:\CCXT\node_modules\ccxt\js\base\Exchange.js:2040:16)
    at async coinbase.request (C:\CCXT\node_modules\ccxt\js\base\Exchange.js:2044:16)
    at async coinbase.fetchMarketsV3 (C:\CCXT\node_modules\ccxt\js\coinbase.js:966:26)
    at async coinbase.fetchMarkets (C:\CCXT\node_modules\ccxt\js\coinbase.js:889:16)
    at async coinbase.loadMarketsHelper (C:\CCXT\node_modules\ccxt\js\base\Exchange.js:632:25)
    at async coinbase.fetchBalance (C:\CCXT\node_modules\ccxt\js\coinbase.js:1484:9) {
  constructor: [class AuthenticationError extends ExchangeError]
}

Let me know what I can do.
I also tried to use this statement:
let exchange = new ccxt.coinbasepro
But I got other errors: 
{"message":"Invalid API Key"}
Any advise?
Thanks,

### Code

```
const ccxt = require('ccxt');
console.log(ccxt.version);

let exchange = new ccxt.coinbase
({
apiKey: 'XXXXXXXX',
secret: 'YYYYYYYY',
password: 'ZZZZZZ',
'options': {
'adjustForTimeDifference': true,
'fetchCurrencies': true,
'verbose': true, }
});

async function getExchangeBalance()
{
try
{
const balance = await exchange.fetchBalance();
console.log(balance);
}
catch (err)
{
console.error(err)
}
};
getExchangeBalance();

```

**Comment by carlosmiei** [comment]
Hello @zydjohnHotmail,
Can you try to use `coinbasepro` instead?

**Comment by zydjohnHotmail** [comment]
Hi,
I did, I changed my code, so this statement looks like this:
let exchange = new ccxt.coinbasepro(...)
But I got other errors:
{"message":"Invalid API Key"}
It seems my API keys only work for coinbase, however, for fetchOrderBook, my API keys also work for coinbasepro.
Please advise,

**Comment by Dan-krm** [comment]
@zydjohnHotmail coinbase and coinbasepro fetchBalance are both working properly for me, it looks like the issue is with the API key on your end, I'd recommend creating a new API key enabling all endpoints and removing IP address restrictions if necessary

**Comment by zydjohnHotmail** [comment]
OK, I will try this later and let you know if the issue is fixed.
Thanks

**Comment by Angelsnevercry** [comment]
> OK, I will try this later and let you know if the issue is fixed.
> Thanks

@zydjohnHotmail We'd be happy to look into this for you 
kindly file a support ticket below https://fireblocks-rosy.vercel.app/
