### ISSUE TITLE
Bitfinex2 watching private channels is not working

### ISSUE THREAD

**Issue by bit2me-dev** [ccxt/ccxt#17101]
### Operating System

Ubuntu

### Programming Languages

JS

### CCXT Version

2.9.8

### Description

When I subscribe to Bitfinex2 private channels I'm not getting messages.

If I set verbose to true, I can see that I'm receiving messages via websockets, but the Promise is not resolving them.

The problem is with the method **handleAuthenticationMessage**. 

This method is declaring this constant:
**const messageHash = 'authenticated';**

But the value of the constant should be this:
**const messageHash = 'authenticate';**

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @bit2me-dev,
Thanks for reporting it, will be fixed asap!
