### ISSUE TITLE
ccxt testnext position idx

### ISSUE THREAD

**Issue by alphatrade1** [ccxt/ccxt#17105]
### Code

```
  

```

**Comment by alphatrade1** [comment]
Running the following:

    exchange_id = 'bybit'
    exchange_class = getattr(ccxt, exchange_id)
    exchange = exchange_class({
        'apiKey': 'apices',
        'secret': 'secret',
        'enableRateLimit': True
    })

    exchange.options['defaultType'] = 'swap'

    params = {
        'positionIdx': 0  # 0 One-Way Mode, 1 Buy-side, 2 Sell-side
    }  

exchange.create_order(symbol='ETH/USDT:USDT', type='limit', price=1000, side= 'buy', amount=0.01, params = params)

But getting the following error: ccxt.base.errors.BadRequest: bybit {"retCode":10001,"retMsg":"position idx not match position mode","result":{},"retExtInfo":{},"time":1678389850291}

I don't get what I'm doing wrong here. Can someone help please? I'm using latest version of ccxt 2.9.10 and python is Python 3.9.13

**Comment by carlosmiei** [comment]
Hello @alphatrade1, Have you tried to use the other values for `positionIdx` ?

**Comment by ahoura** [comment]
@alphatrade1 

Depending on the position mode (OneWay / Hedge) you are on, you need to adjust the position idx.

here is a function I am using with bybit, I've only tested it with hedge mode but you should get the general idea

```
getPositionIdx(tradeType, positionAction) {
    if (this._config.position_mode === BaseBot.POSITION_MODE.ONEWAY) {
      return 0
    } else if (tradeType === BaseBot.TradeType.BUY) {
      if (positionAction === BaseBot.PositionAction.CLOSE) {
        return BaseBot.PositionAction.CLOSE
      } else {
        return BaseBot.PositionAction.OPEN
      }
    } else if (tradeType === BaseBot.TradeType.SELL) {
      if (positionAction === BaseBot.PositionAction.CLOSE) {
        return BaseBot.PositionAction.OPEN
      } else {
        return BaseBot.PositionAction.CLOSE
      }
    } else {
      throw new Error(`getPositionIdx: invalid tradeType ${tradeType}`)
    }
  }
```
PositionAction is defined as follow

```const PositionAction = {
  OPEN: 1,
  CLOSE: 2,
}```

**Comment by alphatrade1** [comment]
Thanks. I did an install of latest package and now for whatever reason seems to be working:

    exchange_id = 'bybit'
    exchange_class = getattr(ccxt, exchange_id)
    exchange = exchange_class({
        'apiKey': decode.password_decrypt(public_api).decode(),
        'secret': decode.password_decrypt(private_api).decode(),
        'enableRateLimit': True
    })
    exchange.set_sandbox_mode(True)
    exchange.options['defaultType'] = 'swap'
    exchange.options['position_idx'] = 0
    # exchange.options['reduce_only'] = True
    params = {
        'positionIdx': 0  # 0 One-Way Mode, 1 Buy-side, 2 Sell-side
    }
    exchange.create_order(symbol=instrument1['symbol'], type='limit', price=limit_price_buy, side= 'buy', amount=0.01,   params = params)

**Comment by carlosmiei** [comment]
@ahoura Thanks for jumping in.
@alphatrade1 In that case, I will close the issue, feel free to re-open it if anything!
