### ISSUE TITLE
Unable to cancel conditional order Bitget

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#17112]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

2.9.11

### Description

I am unable to cancel a conditional order on Bitget. Also when using params={'stop': True}

### Code

```
  
        import ccxt
        client = ccxt.bitget({'apiKey': "",
                              'secret': "",
                              'password': ""})

        ticker = "XRP/USDT:USDT"
        side = "buy"
        quantity = 30
        price = 0.4

        response = client.create_order(symbol=ticker, type="limit", side=side,
                                       amount=quantity, price=price,
                                       params={'triggerPrice': price,
                                               'triggerType': 'fill_price'})

        client.cancel_order(response['id'], ticker)

```
ExchangeError: bitget {"code":"40768","msg":"Order does not exist","requestTime":1678468608482,"data":null}

**Comment by sc0Vu** [comment]
Hi @Tomas-MP 

To cancel stop order, you need to set stop to true.

```python
client.cancel_order(id=response['id'], symbol=ticker, params={'stop': True})
```

**Comment by Tomas-MP** [comment]
@sc0Vu unfortunately it still throws the following error: 

ArgumentsRequired: bitget cancelOrder() requires a planType parameter for stop orders, either normal_plan, profit_plan or loss_plan

**Comment by carlosmiei** [comment]
> @sc0Vu unfortunately it still throws the following error:
> 
> ArgumentsRequired: bitget cancelOrder() requires a planType parameter for stop orders, either normal_plan, profit_plan or loss_plan

Hello @Tomas-MP yeah for swap markets you also need to provide that parameter, if you're canceling a "normal" stop order you can just do this:

```Python
params={'stop': True, "planType":"normal_plan"}
```

**Comment by Tomas-MP** [comment]
@carlosmiei awesome will try!
