### ISSUE TITLE
Sorry, CCXT is terrible

### ISSUE THREAD

**Issue by atilagf1** [ccxt/ccxt#17110]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

I was hopeful about CCXT, but it's terrible. The idea was to make it easier for those who need to operate with several brokers. But the truth is that it makes it difficult. I couldn't even perform a basic operation as placing an order with stop loss and take profit. In addition, the brokers have many variations. The best thing is to look at the brokers' documentation, in my opinion.

### Describe the solution you'd like

Perhaps improving the documentation and maintaining continuous testing for exchanges. This way, there would be detailed information about each one.

### Describe alternatives you've considered

Work with my own code using the libraries offered by the exchanges or create my own API client.

**Comment by frosty00** [comment]
We're working on improving the documentation, and we appreciate your feedback. All the code is open source and you are not to use it.
