### ISSUE TITLE
I need USDT/USD value. Help me please.

### ISSUE THREAD

**Issue by BamsoonPapa** [ccxt/ccxt#17121]
I need “something/USD” (the real fiat US Dollar price)
“Something” means both stable coins and other crypto…
Can I do this with CCXT?

Above all, I need USDT/USD value.

PLEASE HELP ME.

**Comment by carlosmiei** [comment]
Hello @BamsoonPapa, you can use, for instance `fetchTicker` (assuming that the exchange has that market)

Example:
```Python
ticker = exchange.fetchTicker('BTC/USD')
ticker = exchange.fetchTicker('BTC/USDT')
```

**Comment by BamsoonPapa** [comment]
https://www.binance.us/trade/pro/USDT_USD

I found upper site.
How can I create binance us object?
Ex) obj = ccxt.binanceus() ?

**Comment by carlosmiei** [comment]
> @carlosmiei
> 
> https://www.binance.us/trade/pro/USDT_USD
> 
> I found upper site. How can I create binance us object? Ex) obj = ccxt.binanceus() ?

@BamsoonPapa yes that should work

**Comment by BamsoonPapa** [comment]
@carlosmiei 

Thank you so much. Thanks to you, I was able to completely solve this problem.
