### ISSUE TITLE
Market fetching error for Bybit exchange

### ISSUE THREAD

**Issue by jurekl** [ccxt/ccxt#17120]
### Operating System

Linux/Windows

### CCXT Version

2.9.11

### Description

For Bybit exchange, the **fetch_spot_markets()** function returns incorrectly **all** pairs as INACTIVE.

### Code

This piece of code is important (**bybit.py** and **async_support/bybit.py** ):
```
...
             status = self.safe_string(market, 'status')
             active = (status == 'trading') or (status == '1') # the latter can be removed after 10/03
...
```

The problem is that the current Bybit API returns the status 'Trading', not 'trading'.

Verification:
https://api.bybit.com/v5/market/instruments-info?category=spot&symbol=BTCUSDT
returns:
```
{"retCode":0,"retMsg":"OK","result":{"category":"spot","list":[{"symbol":"BTCUSDT","baseCoin":"BTC", "quoteCoin":"USDT","innovation":"0","status":"Trading","lotSizeFilter":{"basePrecision":"0.000001","quotePrecision":"0.00000001","minOrderQty":" 0.000048","maxOrderQty":"46.13","minOrderAmt":"1","maxOrderAmt":"1200000"},"priceFilter":{"tickSize":"0.01"}}]},"retExtInfo":{ },"time":1678541674313}
```

**Comment by carlosmiei** [comment]
Hello @jurekl,
That issue was patched yesterday, can you update to the latest version?

**Comment by jurekl** [comment]
Hi @carlosmiei ,

after
```
(.env) D:\Binance_Freqtrade_2\freqtrade>pip install -U ccxt
Requirement already satisfied: ccxt in d:\binance_freqtrade_2\freqtrade\.env\lib\site-packages (2.9.11)
...
...
```

I see 

```
            status = self.safe_string(market, 'status')
            active = (status == 'trading') or (status == '1')  # latter can be removed after 10/03
```
I take it pip doesn't ship this fix yet?

**Comment by carlosmiei** [comment]
@jurekl you're right, something is wrong with the publishing process, we will try to figure it out as soon as possible. Thanks for letting us know.

**Comment by jurekl** [comment]
> @jurekl you're right, something is wrong with the publishing process, we will try to figure it out as soon as possible. Thanks for letting us know.

I see in git sources, that it is corrected. Thanks for the info, regards :-)

**Comment by carlosmiei** [comment]
@jurekl It should be ok now, thanks once again! 🙂
