### ISSUE TITLE
[Phemex] - Deploying same code a month later to AWS Lambda gives ccxt.base.errors.ExchangeError: phemex {"msg":"Failed to find symbol ETHUSD","code":10500}

### ISSUE THREAD

**Issue by TheOnyxKing** [ccxt/ccxt#17123]
### Operating System

Windows 10 Pro Version 22H2 build 22621.1344

### Programming Languages

python

### CCXT Version

2.9.12

### Description

On the 11th of February 2023, under CCXT version 2.7.86, I deployed a code on AWS Lambda that is placing trades on Phemex. It still works perfect placing market order trades for one pair. 

For the last 2 days I have tried to make the same code work, but without success. I can deploy it to AWS Lambda, and if I call a function such as fetchBalance() it works perfectly, but when I try to place an order either market or limit it doesn't work, although I use the same code as before. I made sure I was using same virtual environment with same Python version when deploying through Chalice. When I tried to place orders using the Jupyter Notebook that has ccxt version 2.7.86 it works perfectly. After some digging I realized AWS uses latest version of ccxt 2.9.12 and returns the following log when trying to run the code:

2023-03-11T20:19:39.316+01:00 | INIT_START Runtime Version: python:3.7.v23 Runtime Version ARN: ...
  | 2023-03-11T20:19:40.606+01:00 | START RequestId: 7ae86438-db7e-4525-9b93-1747a649ea02 Version: $LATEST
  | 2023-03-11T20:19:43.924+01:00 | ETH-1m-V6 - ERROR - Caught exception for path /
  | 2023-03-11T20:19:43.924+01:00 | Traceback (most recent call last):
  | 2023-03-11T20:19:43.924+01:00 | File "/var/task/chalice/app.py", line 1914, in _get_view_function_response
  | 2023-03-11T20:19:43.924+01:00 | response = view_function(**function_args)
  | 2023-03-11T20:19:43.924+01:00 | File "/var/task/app.py", line 39, in trade
  | 2023-03-11T20:19:43.924+01:00 | order = phemex.create_market_order(symbol=symbolAlert, side=sideAlert, amount=round(prevMarketPositionSize + amountAlert,0))
  | 2023-03-11T20:19:43.924+01:00 | File "/var/task/ccxt/base/exchange.py", line 3278, in create_market_order
  | 2023-03-11T20:19:43.924+01:00 | return self.create_order(symbol, 'market', side, amount, price, params)
  | 2023-03-11T20:19:43.924+01:00 | File "/var/task/ccxt/phemex.py", line 2189, in create_order
  | 2023-03-11T20:19:43.924+01:00 | response = getattr(self, method)(self.extend(request, params))
  | 2023-03-11T20:19:43.924+01:00 | File "/var/task/ccxt/base/exchange.py", line 505, in inner
  | 2023-03-11T20:19:43.924+01:00 | return entry(_self, **inner_kwargs)
  | 2023-03-11T20:19:43.924+01:00 | File "/var/task/ccxt/base/exchange.py", line 2831, in request
  | 2023-03-11T20:19:43.924+01:00 | return self.fetch2(path, api, method, params, headers, body, config, context)
  | 2023-03-11T20:19:43.924+01:00 | File "/var/task/ccxt/base/exchange.py", line 2828, in fetch2
  | 2023-03-11T20:19:43.924+01:00 | return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  | 2023-03-11T20:19:43.924+01:00 | File "/var/task/ccxt/base/exchange.py", line 667, in fetch
  | 2023-03-11T20:19:43.924+01:00 | self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  | 2023-03-11T20:19:43.924+01:00 | File "/var/task/ccxt/phemex.py", line 3820, in handle_errors
  | 2023-03-11T20:19:43.924+01:00 | raise ExchangeError(feedback) # unknown message
  **| 2023-03-11T20:19:43.924+01:00 | ccxt.base.errors.ExchangeError: phemex {"msg":"Failed to find symbol ETHUSD","code":10500}**
  | 2023-03-11T20:19:43.926+01:00 | END RequestId: 7ae86438-db7e-4525-9b93-1747a649ea02

It seems that it fails to find symbol ETHUSD, although on ccxt version 2.7.86 that the first code is running now is working perfectly. So between these two versions of ccxt there were some changes that prevent placement of orders on Phemex. 

Could you investigate this problem? If you need further info I will be quite responsive, so feel free to ask. 

### Code

import ccxt, json, requests
from chalice import Chalice

app = Chalice(app_name='ETH_1m')

phemex = ccxt.phemex({
	'enableRateLimit': True,
	'apiKey':'MY APIKEY',
	'secret':'MY SECRET'
})

@app.route('/', methods=['POST'])
def trade():
	request = app.current_request
	alert_input = request.json_body
   
# Extract the parameters from the alert input
	
	symbolAlert = "ETHUSD"
	sideAlert = alert_input["trade_side"]
	amountAlert = abs(alert_input["position_size"]*200)
	priceAlert = alert_input["trade_price"]
	prevMarketPositionSize = alert_input["prev_market_position_size"]*200

 # Place the trade

	order = phemex.create_market_order(symbol=symbolAlert, side=sideAlert, amount=round(prevMarketPositionSize + amountAlert,0))
	
	
	return {
        'Message': 'Trade placed successfully',
    }

**Comment by TheOnyxKing** [comment]
Last version that works for me is 2.8.67. So somewhere in version 2.8.68 there were some changes that are breaking something related to order placement on Phemex.

**Comment by carlosmiei** [comment]
Hello @TheOnyxKing thanks for reporting it, we will take a look asap
