### ISSUE TITLE
How CCXT is able to differentiate a quarterly futures from a weekly futures if they expire at the same time?

### ISSUE THREAD

**Issue by x1i4b1x2** [ccxt/ccxt#17134]
### Programming Languages

JS

### CCXT Version

latest

### Description

On Friday 31st March, Weekly futures (like in OKX) and Quarterly futures will expire at the same time. That will result in a potential conflict if fetching something like "BTC/USD:BTC-230331" (from the same exchange) where they share the same settlement date.

I haven't found anything in the documentation. Some exchanges attach some helpful metadata in the "info" object of a market, but not all. Like OKX will tell you in the "alias" if is "quarter" or "this_week".

Am I missing something or the library doesn't account for such an event?

Thank you!

### Code

```
  

```

**Comment by frosty00** [comment]
it's only one contract. does when the contract was created affect the price?

**Comment by x1i4b1x2** [comment]
So as an example, if I go to OKX's website the last week of March, looking for 0331Wkly and 0331Qtly, they will be the same contract, with the same price, volume, and order book?

**Comment by frosty00** [comment]
yeah, they merge the contracts
