### ISSUE TITLE
( HELP ME ) how to check the liquidation price and mark price in USDM-futures market.

### ISSUE THREAD

**Issue by BamsoonPapa** [ccxt/ccxt#17130]
1) I would like to check the liquidation price of my short position of USD-M futures on the Binance exchange to prevent it from being liquidated.

2) Additionally, I would like to monitor the Mark Price of USD-M futures in real-time, which affects the liquidation.

Please let me know how to do these two things. (function, object, etc)

Thank you.

**Comment by sc0Vu** [comment]
Hi @BamsoonPapa 

1. can get liquidation price when call fetchPositions in binance.
2. can subscribe mark price by calling watchOHLCV and set topic to `markPriceKline` (also `indexPriceKline`).
