### ISSUE TITLE
Set Trailing-Stop on Bybit 

### ISSUE THREAD

**Issue by CharafChnioune** [ccxt/ccxt#17131]
### Operating System

windows/mac/linux

### CCXT Version

Version: 2.9.12

### Description

Is it possible to set a trailingstop with CCXT on bybit? I stried everything and it seems to only work with pybit but not with ccxt.

I am trying to open it for this market buy order and litterly tried all parms ect with no succes

### Code

```
  

```
buy = exchange.create_order(SYMBOL, 'market', 'buy', AMOUNT)

**Comment by ahoura** [comment]
what bybit API version are you using? I think in all cases (only tested V3 myself), you would be setting a trailing order on the POSITION. https://bybit-exchange.github.io/docs/derivatives/contract/trading-stop

I am not sure about a unified CCXT api for this function but you can use the private fn ccxt exposes under bybit.

**Comment by Mocro020** [comment]
v3 same got it working with that but was wondering if i can just use ccxt to create a trailingstop instead of using pybit library

**Comment by ahoura** [comment]
yea ccxt creates a non-unified api call for every api endpoint. look at "privatePostContractV3PrivateCopytradingOrderTradingStop" for creating such an order. this is specific to bybit and not available across other exchanges.

**Comment by Mocro020** [comment]
well i am trying everything out untill this works lol thx for the tip

**Comment by IsaTTeN** [comment]
I am in the same situation. I don´t know how to open a trailing stop order. It seems Bybit hos now two parameters when we define a trailing stop order in V5 API:

_- trailingStop: Cannot be less than 0, 0 means cancel TS. note: valid for USDT Perpetual only_. **Is this the offset price?**
_- activePrice: Trailing stop trigger price. Trailing stop will be triggered when this price is reached only_. **Is this the Trigger Price?**

In other closed issues I read that for Bybit we have to open a second order after order creation if we want to have trailing but I don´t know to do this: 

Using exchange.privatePostPrivateLinearPositionTradingStop (trailingParams)?
or
using exchanget.privatePostV2PrivatePositionTradingStop(params)?

BR
