### ISSUE TITLE
Bitstamp: Invalid Nonce

### ISSUE THREAD

**Issue by andy-io** [ccxt/ccxt#1714]
ccxt.base.errors.ExchangeNotAvailable: bitstamp POST https://www.bitstamp.net/api/v2/balance/ 403 Client Error: Authentication Failed for url: https://www.bitstamp.net/api/v2/balance/ {"status": "error", "reason": "Invalid nonce", "code": "API0004"}

- OS: Mac sierra
- Programming Language version: Python 3.6
- CCXT version: 1.10.867
- Exchange: Bitstamp
- Method: fetch_balance()

**Comment by kroitor** [comment]
Any code to reproduce the problem? Is it a new key? Have you tried a new key?...

- https://github.com/ccxt/ccxt/wiki/Manual#authentication
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/issues/1654#issuecomment-361896127
- https://github.com/ccxt/ccxt/blob/master/examples/py/basic-rate-limiting.py

Let us know if the above does not help.

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by andy-io** [comment]
Thanks i will debug further and let you know...

**Comment by andy-io** [comment]
@kroitor 
`
import ccxt

exchange = ccxt.bitstamp({
    'apiKey': 'xxx',
    'secret': 'xxx',
    'uid': 'xxx',
    'enableRateLimit': True,
    'verbose': True
})
response = exchange.fetch_balance()
print(response)
`
This code produces either invalid nonce or invalid signature

**Comment by kroitor** [comment]
@andy-io is it a new API key?

**Comment by andy-io** [comment]
@kroitor i tried it with bold old and new keys. new key gives invalid signature error while the old one gives invalid nonce error

**Comment by kroitor** [comment]
@andy-io sure the keys are not messed up? Wrong secret with a wrong key, or something? Sorry for asking this, need to make sure twice, as your symptoms kinda indicate a key setup error. Maybe try it once again to ensure this. Because this works for most users, afaik.

**Comment by andy-io** [comment]
@kroitor tried now multiple times. If i use the sample code from bitstamp, the same keys are working without any errors
```
import hmac
import hashlib
from time import time
import requests


def get_nonce():
    return str(int(time() * 1e6))

api_key = ''
api_secret = ''
customer_id = ''

nonce = get_nonce()

message = nonce + customer_id + api_key
signature = hmac.new(
    str.encode(api_secret),
    msg=str.encode(message),
    digestmod=hashlib.sha256
).hexdigest().upper()

data = {
    'key': api_key,
    'signature': signature,
    'nonce': nonce
}

response = requests.post('https://www.bitstamp.net/api/v2/balance/', data=data)
print(response.json())
```

**Comment by kroitor** [comment]
Oh... you should not really try the keys chaotically %) Because when you used them with your script, the nonce is set to time() * 1e6. And from there you can't use that key with ccxt.

Can you try it in the other order? First try a new key with ccxt with your code:

```Python
import ccxt

exchange = ccxt.bitstamp({
    'apiKey': 'xxx',  #  ←---------  create a new key once again, even if you did that previously
    'secret': 'xxx',  # ←------- don't forget to change the secret as well
    'uid': 'xxx',
    'enableRateLimit': True,
    'verbose': True
})
response = exchange.fetch_balance()
print(response)
```

↑ This should work with a new unused key (not screwed with that script yet).
If it does, there's no need to check your script, as it will screw your nonce number.

**Comment by andy-io** [comment]
@kroitor i tried it with a new set of keys Still getting the invalid signature error. 
```
import ccxt

exchange = ccxt.bitstamp({
    'apiKey': '',
    'secret': '',
    'uid': '',
    'enableRateLimit': True,
    'verbose': True,
    'nonce': lambda: ccxt.Exchange.milliseconds()
})
response = exchange.fetch_balance()
print(response)
```

**Comment by andy-io** [comment]
@kroitor what i found is that the above code works in python 2 and not in python 3 !!!

**Comment by kroitor** [comment]
@andy-io will check for that, thx for reporting back! I'll update you on my findings, probably, with a fix.

**Comment by andy-io** [comment]
@kroitor : any updates on this one ?

**Comment by kroitor** [comment]
@andy-io didn't have enough time to look into it, but, you could help speed it up, if you post your verbose output, from Python 3 version as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Also, a quick question to you: is it the same machine you're testing with Python 2 and Python 3 or different systems?
