### ISSUE TITLE
CCXT now in TypeScript with ESM

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#17149]
Hello, dear CCXT users!

We are excited to announce that we are migrating CCXT development from CommonJS and JavaScript to TypeScript with ES modules (ESM). This transition will bring numerous benefits to our product and our development process, and we wanted to highlight some of the key advantages:

Enhanced safety: TypeScript provides a type system that catches errors at compile-time. This means we can catch potential issues before they make it to production, leading to more reliable and stable code. Since the Python/PHP version derives from the TS version, those packages will also (indirectly) benefit from the compile time checking.

Increased productivity: With TypeScript's advanced tooling and editor integrations, our developers can write code faster and with fewer errors. 

Tree shakability: ES modules (ESM) are the standard for modern JavaScript and improves significantly the tree-shaking process, reducing the amount of unnecessary code that needs to be loaded, resulting in a quicker and more streamlined user experience.

**This change is 100% backward compatible, therefore, current users working on a Javascript + CommonJS codebase won't be negatively affected whatsoever by this update**.

Thank you for using CCXT!
Yours, the CCXT Dev Team

**Comment by cpecorari** [comment]
Hi @kroitor , thanks for this update !
We are using Typescript with ccxt in our actual project and we used the previous typings in `2.9.*`, but with version `3.0.*` we now have lot of errors in our typings.
For example, the Exchange class is now defined like this : 
```js
export default class Exchange {
[...]
   has: {};
[...]
}
```
which as a result does not feels ok and Typescript complains on accessing keys like `exchange.has["setLeverage"]` :
```md
Element implicitly has an 'any' type because expression of type '"setLeverage"' can't be used to index type '{}'.
  Property 'setLeverage' does not exist on type '{}'.ts(7053)
  ```
And if i'm not mistaking the type should be defined like this : 
  ```js
export default class Exchange {
[...]
   has: { [key: string]: boolean};
[...]
}
```

Or am i misunderstanding something ?

Are typings moved somewhere else ?

Also, ccxt can't be used anymore in direct import ESM like this : 
`import ccxt from "ccxt";` for typings, but now named import is required like this `import ccxt, { Exchange } from "ccxt";`, too bad, i really liked the namespace for types like this `const exchange: ccxt.Exchange` ;)

Thanks again for any answer !

**Comment by carlosmiei** [comment]
> 

Hello @cpecorari, thanks for reporting it
I will take a look at the `has` issue. Can you specify the TS version used?

Regarding the imports, you should be able to make `default` imports as usual,  we export the exact same object as before https://github.com/ccxt/ccxt/blob/master/js/ccxt.js#L394 🤔

**Comment by cpecorari** [comment]
Hi @carlosmiei, thanks for your fast reply, using `typescript 4.9.4` should i try bumping in 5+ ?
We got other similar issues for example TS says there is no more `.setLeverage()`: 
`Property 'setLeverage' does not exist on type 'Exchange'.ts(2339)`

About the imports i don't know what changed, but now TS complains about the namespace as you can see here : 
![Capture d’écran 2023-03-21 à 11 39 54](https://user-images.githubusercontent.com/56672657/226582549-a04fe60d-cf1f-4c11-b384-c79e30446728.png)

**Comment by cpecorari** [comment]
Ok solved namespace with importing everything like this (ref: https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html)
```js
import * as ccxt from "ccxt";
```
But still same problem with `setLeverage`, `has` and many specific "custom-built" exchange functions like `contractPrivatePostOrderSubmit` on Mexc for example.

**Comment by carlosmiei** [comment]
> Ok here it is, can you also tell me what is your tsconfig ? Thanks ! https://github.com/cpecorari/ccxt-types-test.git

@cpecorari thanks I will try to run it.
Our tsconfig is here: https://github.com/ccxt/ccxt/blob/master/tsconfig.json

**Comment by cpecorari** [comment]
Thanks, found the issue for the "exchange.has[...]" with the `"noImplicitAny": false,`, as we have it implicitly to `true` with strict ...  ref: https://www.typescriptlang.org/tsconfig#noImplicitAny
ccxt namespace still has issue if not imported with `* as ccxt from "ccxt"`.

**Comment by cpecorari** [comment]
Yep exactly ! Except when importing all `* as ccxt` .

**Comment by cpecorari** [comment]
Hey @carlosmiei , while having time and tired of TS yelling at me, i tried to hack the Exchange type like this, and yeay it works 👍 
But that may need a TS expert to validate ?
`Exchange.d.ts`
```js
export default class Exchange {
[...]
[key: string]: (...args: any[]) => any;
[...]
}
```

**Comment by carlosmiei** [comment]
> Hey @carlosmiei , while having time and tired of TS yelling at me, i tried to hack the Exchange type like this, and yeay it works 👍 But that may need a TS expert to validate ? `Exchange.d.ts`
> 
> ```js
> export default class Exchange {
> [...]
> [key: string]: (...args: any[]) => any;
> }
> ```

Hello @cpecorari, what is your ccxt version? I think this error should be fixed by now on master

**Comment by cpecorari** [comment]
Wow awesome thanks, did not update that fast !
Was still on  `"ccxt": "^3.0.25",` just upgraded to `3.0.43` 👍
