### ISSUE TITLE
Fetchledger vs fetchtransactions

### ISSUE THREAD

**Issue by naward-cs** [ccxt/ccxt#17142]
### ؜

What is the difference between fetchledger and fetchtransactios

**Comment by Dan-krm** [comment]
From the CCXT documentation: https://docs.ccxt.com/#/

fetchTransactions covers the deposit and withdrawal history, fetchLedger covers all transactions that change the users balance.

### fetchTransactions
the user can fetch the history of their transactions (on-chain transactions which are either deposits to the exchange account or withdrawals from the exchange account) with `fetchTransactions()`, or with `fetchDeposit()`, `fetchDeposits()`, `fetchWithdrawal()`, and `fetchWithdrawals()` separately, depending on what is available from the exchange API

### fetchLedger
if the exchange API provides a ledger endpoint, the user can fetch a history of all money movements that somehow affected the balance, with `fetchLedger()` that will return all accounting ledger entries such as trades, deposits, withdrawals, internal transfers between accounts, rebates, bonuses, fees, staking profits and so on, as described in the [Ledger](https://docs.ccxt.com/#/?id=ledger) section.
