### ISSUE TITLE
Issues regarding CCXT docs 

### ISSUE THREAD

**Issue by spc789** [ccxt/ccxt#17153]
1. link on the github page which links to the doc system doesn't work : (link is : https://docs.ccxt.com/en/latest/manual.html ) which gives a 404 error page.

2. searching in the doc system (https://docs.ccxt.com/#/) doesn't work as expected. For example searching in the docs  "fapiPrivate_post_leverage" doesn't give anything as result. 
---
Anyone can help me out how the fapiPrivate_post_leverage function is formed, which are the possible parameters ? Specific I'm searching how to set the leverage and cross or isolated margin mode for binance futures. 

Following code snipper doesn't work (ccxt 2.9.10 / python 3.8 / linux) : 

```python
leverage = 5
print (market['id'])
print (leverage)
leverage = float(leverage)
print (type(leverage))

exchange.fapiPrivate_post_leverage({
        "symbol": market['id'],  
        "leverage": leverage,
})
```

Nor specifying a str type for leverage doesn't work : (leverage = 5 ; type(leverage) = str)

```python
leverage = 5
print (market['id'])
print (leverage)
leverage = str(leverage)
print (type(leverage))

exchange.fapiPrivate_post_leverage({
        "symbol": market['id'],  
        "leverage": leverage,
})
```

Both code snippets give as error : 
```python
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/leverage
```
and 
```python
> ccxt.base.errors.BadRequest: binance {"code":-1102,"msg":"Mandatory parameter 'leverage' was not sent, was empty/null, or malformed."}
```
With `verbose = True`, this is what I get (some data edited with ---): 
```python
> fetch Request: binance POST https://fapi.binance.com/fapi/v1/leverage RequestHeaders: {'X-MBX-APIKEY': ----------', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': python->requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: timestamp=1678720225433&symbol=BTCUSDT&leverage=5.0&signature=--------------------

>fetch Response: binance POST https://fapi.binance.com/fapi/v1/leverage 400 ResponseHeaders: {'Content-Type': application/json', 'Content-Length': '97', 'Connection': 'keep-alive', 'Date': 'Mon, 13 Mar 2023 15:10:25 GMT', 'Server': Tengine', 'X-MBX-USED-WEIGHT-1M': '8', 'x-response-time': '2ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 -----------.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'NRT12-C3', 'X-Amz-Cf-Id': '-------------=='} ResponseBody: {"code":-1102,"msg":"Mandatory parameter 'leverage' was not sent, was empty/null, or malformed."}
```
---
Additional question outside the scope of the topic : since mid dec 2022 binance has a private ws stream where one can create orders etc in the ws stream. (SPOT WEBSOCKET API .) Is there an eta when this functionality will be incorporated in ccxt ?

**Comment by samgermain** [comment]
#17159 should fix problem 1

**Comment by samgermain** [comment]
The [implicit api methods](https://docs.ccxt.com/#/README?id=implicit-api) won't be in the documentation. These methods are specific to each exchange and directly access the api endpoints. CCXT has a way of dynamically accessing each endpoint based on the method name, so there's no documentation produced for these methods.

If you search for a [unified method](https://docs.ccxt.com/#/README?id=unified-api), you'll be able to find it in the documentation

**Comment by spc789** [comment]
I quickly searched with the help of the new documentation links. (https://docs.ccxt.com/#/README?id=leverage)
while using the setLeverage function. The opposite of "cross" as margin-mode is "isolated" I presume ? 
Besides "cross" as margin-mode, no further parametrisation is given in the docs.

**Comment by samgermain** [comment]
> I quickly searched with the help of the new documentation links. (https://docs.ccxt.com/#/README?id=leverage) while using the setLeverage function. The opposite of "cross" as margin-mode is "isolated" I presume ? Besides "cross" as margin-mode, no further parametrisation is given in the docs.

That's untrue, `cross` and `isolated` are both explained under the [margin mode documentation](https://docs.ccxt.com/#/README?id=margin-mode)

**Comment by spc789** [comment]
Indeed in the margin mode documentation (setMarginMode) it is mentioned : 
https://docs.ccxt.com/#/README?id=margin-mode
In the set leverage function (setLeverage ) it ain't.

In the setMarginMode documentation there is no mention that leverage must be an int (it is mentioned in setLeverage).
In setLeverage docu there's no mention of 'isolated', while it is mentioned in setMarginMode.
