### ISSUE TITLE
Bybit v5 - amount of createOrder not correct

### ISSUE THREAD

**Issue by hanxuh-hub** [ccxt/ccxt#17164]
### Operating System

Windows

### Programming Languages

python

### CCXT Version

3.0.4

### Description

I am using Bybit UTA account and try to use ccxt.pro to create order for spot market. When I place a market buy order of 10 DOGE/USDT, I found that the it bought 10 USDT worth of DOGE instead of 10 DOGE. The problem disappears when I place a market sell order or limit buy/sell order.

### Code

```
  await client.createOrder(symbol=symbol, type='market', side='buy', amount=10, params={'isLeverage': 1})

```

**Comment by carlosmiei** [comment]
Hello @hanxuh-hub,
Thanks for letting us know, we should emit a warning when that happens to make sure users are aware that market-buy orders require the cost instead.  I will fix it asap.
