### ISSUE TITLE
Handling bybit WS connection / NetworkError errors

### ISSUE THREAD

**Issue by ahoura** [ccxt/ccxt#17162]
### Operating System

N/A

### Programming Languages

JS

### CCXT Version

2.8.89

### Description

As per the ccxt [documentations](https://docs.ccxt.com/#/ccxt.pro.manual?id=streaming-specifics), connection error handling is suppose to be done automagically under the hood. At the moment I am receiving the following error from bybit ws implementation:

```
/engine/node_modules/ccxt/js/pro/base/Client.js:230
            this.reset (new NetworkError ('connection closed by remote server, closing code ' + String (event.code)))
                        ^

NetworkError: connection closed by remote server, closing code 1006
    at WsClient.onClose (/engine/node_modules/ccxt/js/pro/base/Client.js:230:25)
    at callListener (/engine/node_modules/ccxt/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/engine/node_modules/ccxt/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emitClose (/engine/node_modules/ccxt/node_modules/ws/lib/websocket.js:258:10)
    at Receiver.receiverOnFinish (/engine/node_modules/ccxt/node_modules/ws/lib/websocket.js:1169:20)
    at Receiver.emit (node:events:513:28)
    at finish (node:internal/streams/writable:756:10)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  constructor: [class NetworkError extends BaseError]
}
```

code 1006 appears to be a [CCXT ws specific error](https://github.com/ccxt/ccxt/blob/master/ts/src/base/ws/Client.ts#L139). Having followed the code, it appears to just call onClose callback fn followed by [this.reset()](https://github.com/ccxt/ccxt/blob/master/ts/src/base/ws/Client.ts#L133) which simply clears interval based functions and rejects all pending promises waiting to be fulfilled. 

My question is how should I go about handling this exception without breaking the design flow of CCXT?

**Comment by pcriadoperez** [comment]
Hi @ahoura,

Are you using the watch function inside a try.. catch clause? Or maybe you can share a snippet of your code?

We usually suggest to use the watch functions with the following patten. Inside a while loop and inside a try.. catch clause, so if any errors happen it catches them and reconnects automatically. The 1006 error is usually many times caused by creating too many connections to the server at once, but if can share your code I can look better into it

**Suggested pattern:**
```
while (true) {

    try {

        // fetch some data
        orderbook = await exchange.fetchOrderBook (symbol, limit)

        // do something or react somehow based on that data
        // ...

    } catch (e) {

        // handle errors
    }
}
```

**Comment by ahoura** [comment]
Hi @pcriadoperez 

Thank you for your response, Yes I am using a while loop but no I didnt wrap it around try{}catch(e){}. So I am guessing the script stops due to an uncatched error? once error(s) occur that are related to remote server connections being closed, should I just assume data integrity is no longer there and resync everything or will CCXT handle resyncing as well? 

here is a simplified version of my BaseBot class that I use to handle connecting and syncing data with an exchange. Ill leave only the portion related to watch* functions as to not waste your time with unrelated stuff. 

```
class BaseBot {
  constructor(_config) {
    this._config = Object.assign({}, DEFAULT_CONFIG, _config)
    this._client = new pro[_config.exchange.name]({
      apiKey: _config.exchange.key,
      secret: _config.exchange.secret,
      enableRateLimit: true,
      // verbose: true,
    })

    this._isready = {
      wallet: false,
      orders: false,
      orderbook: false,
      position: false,
    }

    this.currentTimestamp = Date.now()
  }

  async init() {
    // 
    this.syncData()
  }

 
  async syncData() {
    this.syncWallet()
    this.syncOrders()
    this.syncPositions()
    this.syncOrderbook()
    return Promise.resolve()
  }

  async syncOHLCV() {
    while (true) {
      await this._client.watchOHLCV(this._config.pair) // .then((_ohlcv) => this.parseOHLCV(_ohlcv))
      // this.onTick(ohlcv)
    }
  }

  async syncPositions() {
    const positions = await this._client.fetchPositions(this._config.pair)
    this._client.positions = this._client.positions || {};
    positions.forEach(position => {
      this._client.positions[position.symbol] = this._client.positions[position.symbol] || {}
      this._client.positions[position.symbol][position.side] = position
    })
    this._isready.position = true
    while (true) {
      const _positions = await this._client.watchPosition(this._config.pair)
      this.onPositionUpdated(_positions)
    }
  }

  async syncOrderbook() {
    // we call orderbook once to sync up, then loop 
    await this._client.watchOrderBook(
      this._config.pair,
      50
    );
    this._isready.orderbook = true
    while (true) {
      await this._client.sleep(this._config.ticker_frequency)
      this.currentTimestamp = Date.now()
      this.tick()
    }
  }

  async syncOrders() {
    const orders = await this._client.fetchOpenOrders(this._config.pair)
    this._client.orders = new ArrayCacheBySymbolById()
    orders.forEach((order) => this._client.orders.append(order))
    this._isready.orders = true
    while (true) {
      const orders = await this._client.watchOrders(this._config.pair)
      orders.forEach((order) => {
        // console.log('order', order)
        if (order.status === 'closed') {
          this.onOrderFilled(order)
          if (order.side === 'buy') {
            this.onBuyOrderCompleted(order)
          } else if (order.side === 'sell') {
            this.onSellOrderCompleted(order)
          }
        } else if (order.status === 'canceled') {
          this.onOrderCanceled(order)
        }
      })
    }
  }

  async syncWallet() {
    this._client.balance = await this._client.fetchBalance()
    this._isready.wallet = true
    while (true) {
      await this._client.watchBalance()
    }
  }

}
```

**Comment by ahoura** [comment]
Hi @pcriadoperez 

any thoughts on ^^?

Thanks in advance

**Comment by pcriadoperez** [comment]
Hi @ahoura , Correct we recommend to wrap the `watch` function in a try, catch clause. In general ccxt is quite stable and I've watch a thousand symbols for several hours without any errors, but errors do happen. On any error ccxt on the next call to `watch` will attempt to re-establish the connection.
About your question around data integrity. In the case of `watchOrderBook` depending on the exchange we are sometimes able to fetch the latest snapshot and use the nonce to make sure no messages are lost. Unfortunately with other messages if any messages are sent during that disconnect or error, they may be lost
