### ISSUE TITLE
Unable to create stoploss order on Bybit

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#17172]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

3.0.6

### Description

Unfortunately, Bybit throws an error when trying a stop market order. Is it possible to fix this? 

### Code

```
   import ccxt
     client = ccxt.bybit({'apiKey': "",
                         'secret': ""})

    ticker = "LTC/USDT:USDT"
    side = 'sell'
    quantity = 0.1
    price = 90
    mode = 1

    response = client.create_order(symbol=ticker, type="market", side=side,
                                   amount=quantity, price=None,
                                   params={'triggerPrice': price,
                                           'close_on_trigger': True,
                                           'position_idx': mode})

```
 Cell In[4], line 7
    response = client.create_order(symbol=ticker, type="market", side=side,

  File ~\anaconda3\lib\site-packages\ccxt\bybit.py:3278 in create_order
    return self.create_contract_v3_order(symbol, type, side, amount, price, params)

  File ~\anaconda3\lib\site-packages\ccxt\bybit.py:3636 in create_contract_v3_order
    response = self.privatePostContractV3PrivateOrderCreate(self.extend(request, params))

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:505 in inner
    return entry(_self, **inner_kwargs)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2850 in request
    return self.fetch2(path, api, method, params, headers, body, config, context)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2847 in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:667 in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File ~\anaconda3\lib\site-packages\ccxt\bybit.py:7772 in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:3151 in throw_exactly_matched_exception
    raise exact[string](message)

BadRequest: bybit {"retCode":10001,"retMsg":"Request parameter error.","result":{},"retExtInfo":{},"time":1678811778065}

**Comment by sc0Vu** [comment]
Hi @Tomas-MP 

For stopLoss order, you might need to set `stopLoss` in params.

I can't create triggerOrder and stopLoss order neither, will look into this issue.

**Comment by Tomas-MP** [comment]
@sc0Vu stopPrice instead of triggerPrice seems to work!
