### ISSUE TITLE
watch_ohlcv function not working for Bybit exchange

### ISSUE THREAD

**Issue by sumitgautam0101** [ccxt/ccxt#17170]
### Operating System

Windows 11

### Programming Languages

python

### CCXT Version

2.8.89

### Description

I am trying to connect with Bybit using the watch_ohlcv function to stream live data, but it returns an array with no values. The same code works fine for Binance Exchange.

Output ---

[[None, None, None, None, None, None]]
[[None, None, None, None, None, None]]
[[None, None, None, None, None, None]]
[[None, None, None, None, None, None]]
[[None, None, None, None, None, None]]

### Code

```
import asyncio
import ccxt.pro


market = "future"
api_key = "api_key"
api_sec = "api_secret"

exchange = ccxt.pro.bybit({
    'enableRateLimit': True,
    'options': {
        'defaultType': market,
        'adjustForTimeDifference': True
    },
    "apiKey" : api_key,
    "secret" : api_sec
})



async def fetch_kline():

    while True:

        live_feed = await exchange.watch_ohlcv("ETH/USDT", "1m")

        print(live_feed)



asyncio.run(fetch_kline())
```

**Comment by carlosmiei** [comment]
Hello @sumitgautam0101,
Do you mind updating your ccxt version? I think this issue was fixed in the meantime.

**Comment by sumitgautam0101** [comment]
Thank You, it works now !!

**Comment by carlosmiei** [comment]
@sumitgautam0101 nice, will close this issue then. Let us know if anything!
