### ISSUE TITLE
Problem with fetchOHLCV volume of OKX futures contract crypto-settled

### ISSUE THREAD

**Issue by x1i4b1x2** [ccxt/ccxt#17177]
### Programming Languages

JS

### CCXT Version

2.9.9

### Description

When fetching OHLCV from OKX futures, CCXT returns the number of contracts, and not the number of coins, as volume.

This can be easy to handle when futures are Stablecoin settled, where 1 contract can be equal to a number of coins.

But in the case of futures contracts that are Crypto settled, 1 contract equals an amount of USD, not coins, making it impossible to have the precise amount of volume in coins from CCXT.

You can see the difference here:

Settled in cryptocurrency
<img width="295" alt="Screenshot 2023-03-14 at 7 41 21 PM" src="https://user-images.githubusercontent.com/100806945/225105764-c46a0e2c-ddc7-440f-b72b-88c8764f22fa.png">

Settled in stablecoin
<img width="298" alt="Screenshot 2023-03-14 at 7 41 51 PM" src="https://user-images.githubusercontent.com/100806945/225105873-721c9496-f864-4365-b043-2682185cb682.png">

In the API response, OKX provides also the amount of coin as volume, under "volCcy", see below:

<img width="1039" alt="Screenshot 2023-03-14 at 7 44 29 PM" src="https://user-images.githubusercontent.com/100806945/225106357-3a597638-98c8-470c-83ea-42b7c5d1ec7e.png">

I think that volume should be what CCXT puts in the volume of OHLCV, like with every other exchange. Thoughts?

### Code

```
  

```

**Comment by Dan-krm** [comment]
Thanks for pointing this out, I'll open a PR to change this so fetchOHLCV will retrieve the base volume
