### ISSUE TITLE
New Exchange: omniexplorer

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#1718]
api: https://omniexplorer.info/apidocumentation.aspx
url: http://www.omnilayer.org/
coinmarket: --
type: decentralized exchange

**Comment by Guillerbr** [comment]
go

**Comment by kroitor** [comment]
@Guillerbr go? )

**Comment by swilso793** [comment]
Omniexplorer's api is in alpha/beta. It fails to respond very often.

**Comment by frosty00** [comment]
exchange doesn't exist
