### ISSUE TITLE
Property 'sign' in type 'exchange' is not assignable to the same property in base type 'Exchange'.

### ISSUE THREAD

**Issue by MedionSF** [ccxt/ccxt#17189]
### Operating System

ubuntu 22

### Programming Languages

JS

### CCXT Version

3.0.9

### Description

Since upgrading to version 3+, I can't run build anymore

### Code

```
node_modules/ccxt/js/src/tidex.d.ts:78:5 - error TS2416: Property 'sign' in type 'tidex' is not assignable to the same property in base type 'Exchange'.
  Type '(path: any, api?: string | undefined, method?: string | undefined, params?: {} | undefined, headers?: any, body?: any) => { url: any; method: string; body: any; headers: any; }' is not assignable to type '(path: any, api: string | object, method?: string | undefined, params?: {} | undefined, headers?: any, body?: any) => {}'.
    Types of parameters 'api' and 'api' are incompatible.
      Type 'string | object' is not assignable to type 'string | undefined'.

78     sign(path: any, api?: string, method?: string, params?: {}, headers?: any, body?: any): {
```

**Comment by carlosmiei** [comment]
Hello @MedionSF, we moved ccxt entirely to Typescript so now, instead of manually generated type definitions, they are automatically emitted by `tsc`. Due to that, some discrepancies might appear for users relying on the old types, but it should be very easy to fix. 

Can you show use the code producing that error?

(as a quick fix you can always temporarily add `as any` cast to the exchange)

**Comment by carlosmiei** [comment]
@MedionSF Actually I found the reason, our project does not seem to work with old versions of typescript (<4).
What is your ts version?

**Comment by MedionSF** [comment]
> @MedionSF Actually I found the reason, our project does not seem to work with old versions of typescript (<4). What is your ts version?

version 4.7.4

What seems weird is that there is indeed a discrepancy in the params between the abstract class and the concrete classes inheriting it.

I've taken the easy route and removed true casts in favor on any, and require instead of import. But it doesn't feel right :D

**Comment by carlosmiei** [comment]
@MedionSF I will check that discrepancy but it's weird that our tsc build does not detect anything and I've also configured two different typescript projects (one esm and the other cjs) and  they both compiled perfectly with `ccxt` as a dependency

**Comment by MedionSF** [comment]
> @MedionSF I will check that discrepancy but it's weird that our tsc build does not detect anything and I've also configured two different typescript projects (one esm and the other cjs) and they both compiled perfectly with `ccxt` as a dependency

Thanks!

Maybe I'm doing something wrong. But as soon as I call an exchange I get the issue.

Actually it's true that when checking exchanges ts files I can see:
`sign(path: any, api?: string, method?: string, params?: {}, headers?: any, body?: any)`

While the parent class has
`sign(path: any, api: string | object, method?: string, params?: {}, headers?: any, body?: any): {};`

**Comment by carlosmiei** [comment]
> > @MedionSF I will check that discrepancy but it's weird that our tsc build does not detect anything and I've also configured two different typescript projects (one esm and the other cjs) and they both compiled perfectly with `ccxt` as a dependency
> 
> Thanks!
> 
> Maybe I'm doing something wrong. But as soon as I call an exchange in the code I get the issue in the build.
> 
> Actually it's true that when checking exchanges ts files I can see: `sign(path: any, api?: string, method?: string, params?: {}, headers?: any, body?: any)`
> 
> While the parent class has `sign(path: any, api: string | object, method?: string, params?: {}, headers?: any, body?: any): {};`

@MedionSF this difference will be fixed asap

**Comment by MedionSF** [comment]
> > > @MedionSF I will check that discrepancy but it's weird that our tsc build does not detect anything and I've also configured two different typescript projects (one esm and the other cjs) and they both compiled perfectly with `ccxt` as a dependency
> > 
> > 
> > Thanks!
> > Maybe I'm doing something wrong. But as soon as I call an exchange in the code I get the issue in the build.
> > Actually it's true that when checking exchanges ts files I can see: `sign(path: any, api?: string, method?: string, params?: {}, headers?: any, body?: any)`
> > While the parent class has `sign(path: any, api: string | object, method?: string, params?: {}, headers?: any, body?: any): {};`
> 
> @MedionSF this difference will be fixed asap

Thanks a lot!
