### ISSUE TITLE
PHP: gdax cancel order 

### ISSUE THREAD

**Issue by umarsa** [ccxt/ccxt#1719]
**Information:**
- OS: Linux Centos 6
- Programming Language version: PHP
- CCXT version: 1.10.775
- Exchange: gdax
- Method: not sure, POST? cancel_order?

**The Issue:**
It seems that if you try to cancel more than one order, the exchange returns the error invalid signature.

**Code:**
```
if($engine->CreateLimitOrder($amount, $price, $side)) {
	echo "First order created\n";
	
	if($engine->CreateLimitOrder($amount, $price, $side)) {
		echo "Second order created\n";
		
		if($engine->CancelLimitOrder($amount, $price, $side)) {
			echo "First order canceled!\n";
			
			if($engine->CancelLimitOrder($amount, $price, $side)) {
				echo "Second order cancelled!\n";
			}
		}
	}
}
```

**Output:**
First order created
Second order created
First order canceled!
gdax {"message":"invalid signature"}

**Edit:**
It works fine if a new instance of the Exchange is created but I am fairly sure this should not be necessary?

**Comment by kroitor** [comment]
Are you applying any rate-limiting at all?

Most likely the same issue:
- https://github.com/ccxt/ccxt/issues/1654#issuecomment-361896127
- https://github.com/ccxt/ccxt/issues/1714#issuecomment-362380202

Let us know if it does not help.

**Comment by umarsa** [comment]
I am creating the instance like so:
```
new \ccxt\gdax (
                array (
                    'apiKey' => xxx, 
                    'secret' => xxx,
                    'password' => xxx,
		    'enableRateLimit' => true
                )
            );
```

Is this correct and if so, should this be working? I have also tried letting the script sleep in-between the two cancel commands.

**Comment by kroitor** [comment]
> Is this correct and if so, should this be working?

Yes, this seems correct and this should be working.

> I have also tried letting the script sleep in-between the two cancel commands.

Ok, let me check that on my side, I will get back to you asap.

**Comment by umarsa** [comment]
Is this something that is currently being worked on?

I feel as though it may have been closed and forgotten about?

**Comment by kroitor** [comment]
Sorry, been busy recently, and this fell out of my scope, indeed. You could help speed it up, if you can provide some more verbose output for it. Does this work for you?

```PHP
<?php

include_once ('ccxt.php'); // or link with Composer autoload 

$gdax = new \ccxt\gdax (array (
    'apiKey' => xxx,
    'secret' => xxx,
    'password' => xxx,
    'enableRateLimit' => true,
    'verbose' => true, // add this line and copypaste the output here
));

$symbols = array (
    'ETH/BTC', // change to whatever your first symbol is
    'ETH/BTC', // change to whatever your second symbol is
);

$sides = array (
    'buy', // change to whatever your first side is
    'sell', // change to whatever the side of the second order is
);

$amounts = array (
    0.123, // change to whatever first amount is...
    0.321, // ...
);

$prices = array (
    0.1, // change to whatever the first price...
    0.1, // change to whatever the second price...
);

$orders = array ();

echo "Now creating the first order:\n";
$orders[0] = $gdax->create_limit_order ($symbols[0], $sides[0], $amounts[0], $prices[0]);
echo "Order 1:\n";
print_r (orders[0]);
echo "Now creating the second order:\n";
$orders[1] = $gdax->create_limit_order ($symbols[1], $sides[1], $amounts[1], $prices[1]);
echo "Order 2:\n";
print_r (orders[1]);

$results = array ();

echo "Now canceling the first order:\n";
$results[0] = $gdax->cancel_order ($orders[0]);
print_r ($results[0]);
echo "Now canceling the second order:\n";
$results[1] = $gdax->cancel_order ($orders[1]);
print_r ($results[0]);

?>
```

Thx!

**Comment by umarsa** [comment]
Unfortunately, I am no longer using this library; I created my own library.

I will try to test this to help with your project when/if I find some time or when/if I decide to switch back to this library. I will keep this thread up to date if I end up testing/fixing this.
