### ISSUE TITLE
Exchange not available any longer in ccxt.pro?

### ISSUE THREAD

**Issue by tumma72** [ccxt/ccxt#17194]
It appears that the `Exchange` class isn’t any longer exported from the `ccxt.pro` Python package. It was until two versions ago, is this a design decision?

_No response_

**Comment by kroitor** [comment]
@tumma72 CCXT pro has been merged with CCXT and it is now a free part of CCXT, so you don’t have to pay for it anymore. Which exchange is in question?

**Comment by tumma72** [comment]
> @tumma72 CCXT pro has been merged with CCXT and it is now a free part of CCXT, so you don’t have to pay for it anymore. Which exchange is in question?

Sorry see my other comment. Now I have to:

```
import ccxt.async_support as ccxt
Import ccxt.pro as ccxtpro 

exchange: ccxt.Exchange = getattr(ccxtpro, name)
```

Before was all exported in the ccxt.pro directly. I wanted to know if this has been a design decision or another issue with the build scripts 😉

**Comment by kroitor** [comment]
The third line is not necessary, you can do it as shown in the examples:

- https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro

```Python

import ccxt.pro
from asyncio import run

exchange = getattr(ccxt.pro, 'binance')()
```

**Comment by tumma72** [comment]
> The third line is not necessary, you can do it as shown in the examples:
> 
> 
> 
> - https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro
> 
> 
> 
> ```Python
> 
> 
> 
> import ccxt.pro
> 
> from asyncio import run
> 
> 
> 
> exchange = getattr(ccxt.pro, 'binance')()  # your exchange name here 
> 
> ```

Well if I want to use type hints I need to declare the variable type as `Exchange` which isn't any longer exported in the ccxt.pro module. Is that a design decision?

**Comment by kroitor** [comment]
> Is that a design decision?

we will check that and will restore the exports where necessary, thx for your feedback!

**Comment by carlosmiei** [comment]
Hello @tumma72,

Yes both the Pro Exchange was merged into to base Exchange to make our architecture a bit more clean and without circular dependencies. 
With that said, now you just need to import the base exchange to have access to rest+ws methods.

Example:
```Python
import ccxt.async_support as ccxt
exchange = ccxt.exchange # ws and rest capabilities
```

You can read more about the refactor here: https://github.com/ccxt/ccxt/pull/14282

cc @kroitor

**Comment by carlosmiei** [comment]
@tumma72 Nonetheless, I will try to expose it again through `pro` module to avoid changes on your side

**Comment by tumma72** [comment]
Thanks @carlosmiei I'll check the docs, it would be nice to have the documentation updated as well. Anyway it makes sense to me to unify the potential WS related methods into the same library. Also given not all Exchanges will support WS, there will always be a fetch_ replacement in the same module.
