### ISSUE TITLE
Bybit req_timestamp invalid

### ISSUE THREAD

**Issue by hodlerhacks** [ccxt/ccxt#17193]
### Operating System

Windows

### Programming Languages

JS

### CCXT Version

3.0.10

### Description

I'm trying to get CCXT working with Bybit, but I keep getting the following error:

BadRequest: bybit {"retCode":10001,"retMsg":"openapi params error! req_timestamp invalid","result":{},"retExtInfo":{},"time":1678906940599}

Code snippet below.

I've been playing with the options to try and fix the problem. My clock is synced (I can use Binance with the same code without issues). The API key works using the Altrady trading software, so that doesn't seem to be the problem either.

Any hints?

### Code

```
    const exchangeClass = ccxt['bybit'];

    exchange = new exchangeClass({
        'apiKey': apiKey,
        'secret': apiSecret,
        'timeout': 30000,
        'enableRateLimit': true,
        'newUpdates': true,
        'options': {
            'defaultType': 'spot',
            'adjustForTimeDifference': true,
            'recvWindow': 7000,
        }
    });
 
```

**Comment by carlosmiei** [comment]
Hello @hodlerhacks,

Do you see that error every time and on every method call? Also, what is your account type?

**Comment by hodlerhacks** [comment]
Hi @carlosmiei,

Thanks for your quick response (and apologies for my slow response). I'm not getting past:

exchange.loadMarkets();

That's where I'm getting this error.

Not sure what account types exist for Bybit. I just registered, deposited some crypto, and then started testing my application. Is there any specific account information you're looking for?

**Comment by carlosmiei** [comment]
> {"retCode":10001,"retMsg":"openapi params error! req_timestamp invalid","result":{},"retExtInfo":{},"time":1678906940599}

@hodlerhacks Is it possible to share with us a verbose log so we can see the request in detail? 
`exchange.verbose = true` after instantiating it

**Comment by hodlerhacks** [comment]
Sure, here you go:

fetch Request:
 bybit GET https://api.bybit.com/v5/asset/coin/query-info?
RequestHeaders:
 {
  'Content-Type': 'application/json',
  'X-BAPI-API-KEY': '9vThtravCWLYdv7PT9',
  'X-BAPI-TIMESTAMP': 'NaN',
  'X-BAPI-RECV-WINDOW': '7000',
  'X-BAPI-SIGN': '15f3f2acbaa196268d21ede018ae5fbbe74c2584914c179137c9c7ee1b7d7f23'
}
RequestBody:
 undefined

handleRestResponse:
 bybit GET https://api.bybit.com/v5/asset/coin/query-info? 200 OK
ResponseHeaders:
 {
  'Cache-Control': 'no-store',
  Connection: 'close',
  'Content-Length': '121',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Fri, 17 Mar 2023 11:16:56 GMT',
  Ret_code: '10001',
  Server: 'Openresty',
  Timenow: '1679051816191',
  Traceid: '6f08bae85acd652d0c88a7b11a2e36ea',
  Via: '1.1 2a46367687c8f1815bbea20c92c7d64c.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'PjWn5dk32RNg1F7ZIl4aQ-IWIQYJ8EjWUdN2KtlQ_kxLHNqZQ1dulA==',
  'X-Amz-Cf-Pop': 'AMS1-P2',
  'X-Cache': 'Miss from cloudfront'
}
ResponseBody:
 {"retCode":10001,"retMsg":"openapi params error! req_timestamp invalid","result":{},"retExtInfo":{},"time":1679051816191}

C:\code\node-apps\balance-bot\bb-v2\node_modules\ccxt\dist\ccxt.bundle.cjs:20494
            throw new exact[string](message);
                  ^

BadRequest: bybit {"retCode":10001,"retMsg":"openapi params error! req_timestamp invalid","result":{},"retExtInfo":{},"time":1679051816191}
    at bybit.throwExactlyMatchedException (C:\code\node-apps\balance-bot\bb-v2\node_modules\ccxt\dist\ccxt.bundle.cjs:20494:19)
    at bybit.handleErrors (C:\code\node-apps\balance-bot\bb-v2\node_modules\ccxt\dist\ccxt.bundle.cjs:92741:18)
    at C:\code\node-apps\balance-bot\bb-v2\node_modules\ccxt\dist\ccxt.bundle.cjs:18453:51
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async bybit.fetch2 (C:\code\node-apps\balance-bot\bb-v2\node_modules\ccxt\dist\ccxt.bundle.cjs:20140:16)
    at async bybit.request (C:\code\node-apps\balance-bot\bb-v2\node_modules\ccxt\dist\ccxt.bundle.cjs:20143:16)
    at async bybit.fetchCurrencies (C:\code\node-apps\balance-bot\bb-v2\node_modules\ccxt\dist\ccxt.bundle.cjs:85568:26)
    at async bybit.loadMarketsHelper (C:\code\node-apps\balance-bot\bb-v2\node_modules\ccxt\dist\ccxt.bundle.cjs:18476:26)
    at async testAPI (C:\code\node-apps\balance-bot\bb-v2\test.js:34:9)

Interesting to see that NaN timestamp in the request header...

**Comment by hodlerhacks** [comment]
Some markdown formatting was applied to this line:

"throw new exact[string](message);"

**Comment by hodlerhacks** [comment]
Markdown formatting was applied to this line:

`throw new exact[string](message);`

**Comment by sc0Vu** [comment]
@carlosmiei if `adjustForTimeDifference` enable, we'll calculate time difference with server time. Is that possible that `fetchTime()` hit the limit?

**Comment by hodlerhacks** [comment]
@sc0Vu, please note that I ran into this timestamp issue already before using `adjustForTimeDifference`. I only enabled it, hoping that would resolve the issue.

**Comment by hodlerhacks** [comment]
This issue can be closed. It's working now, without the `adjustForTimeDifference` and `recvWindow`. Not really clear why this was not working before.
