### ISSUE TITLE
pip install git+https://github.com/ccxt/ccxt

### ISSUE THREAD

**Issue by tileb1** [ccxt/ccxt#17196]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

Hello,
I am a python user. I would like to pip install ccxt by using the explicit github link (instead of simply doing pip install ccxt). That way, ccxt could also be installed similarly in an easy manner into a python env with a forked repository and tweaked code.

However, this cannot be done currently:
```
$ pip install git+https://github.com/ccxt/ccxt
ERROR: git+https://github.com/ccxt/ccxt does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

### Describe the solution you'd like

Add the necessary config files into the repository such that ccxt could be installed like this:
```
pip install git+https://github.com/ccxt/ccxt
```
That would be very convenient for easily testing tweaked code. Thank you!

**Comment by carlosmiei** [comment]
Hello @tileb1, this is perfectly possible because `pip` has a VSC option to specify a directory inside the repo, so you can just do this:

```Python
python -m pip install "git+https://github.com/ccxt/ccxt/#subdirectory=python"    
```

Docs: https://pip.pypa.io/en/stable/cli/pip_install/#vcs-support

**Comment by tileb1** [comment]
Hi @carlosmiei, thanks for the quick reply! Ah yes my bad, the setup.py is inside the subdirectory.
