### ISSUE TITLE
CoinEx parse_deposit_address tag issue for CFX addresses

### ISSUE THREAD

**Issue by StevenProhashing** [ccxt/ccxt#17197]
### Operating System

Debian 11

### Programming Languages

php

### CCXT Version

3.0.1

### Description

For coins with deposit tags, Coinex's api returns deposit addresses in the format of [address]:[tag].

However, Conflux (CFX) mainnet addresses start with "cfx:", but Conflux does not use deposit tags. An example CFX address returned by CoinEx's api is cfx:aamj21bd60ufr2jg04rzf75t10tvsjj7ge9twkpp7k.

This causes ccxt's CoinEx parse_deposit_address function to incorrectly think that the address is cfx and the tag is aamj21bd60ufr2jg04rzf75t10tvsjj7ge9twkpp7k

Examples:
[Correct - EOS]
```php
Array
(
    [info] => Array
        (
            [coin_address] => coinexdoteos:XpYUqxingQMmYD1oHrjTJS
            [is_bitcoin_cash] =>
        )

    [currency] => EOS
    [address] => coinexdoteos
    [tag] => XpYUqxingQMmYD1oHrjTJS
    [network] => EOSIO
)
```
[Incorrect - CFX]
```php
Array
(
    [info] => Array
        (
            [coin_address] => cfx:aamj21bd60ufr2jg04rzf75t10tvsjj7ge9twkpp7k
            [is_bitcoin_cash] =>
        )

    [currency] => CFX
    [address] => cfx
    [tag] => aamj21bd60ufr2jg04rzf75t10tvsjj7ge9twkpp7k
    [network] => CFX
)
```

**Comment by samgermain** [comment]
Are you trying to say that there shouldn't be a `fetchDepositAddress` method for `coinflux`? I'm not exactly sure what the problem is here

**Comment by StevenProhashing** [comment]
For Conflux, the address should be cfx:aamj21bd60ufr2jg04rzf75t10tvsjj7ge9twkpp7k and the tag null.
Conflux (CFX) does not use tags.

**Comment by StevenProhashing** [comment]
https://github.com/Conflux-Chain/CIPs/blob/master/CIPs/cip-37.md

**Comment by StevenProhashing** [comment]
I confirmed this issue also affects Kaspa (KAS), as Kaspa addresses also use the colon ":" character. Example Kaspa mainnet address "kaspa:qqetp7ct8kqss99fxmymyz5t3fezppxp0t58wl6pawp27elqd46uudme00cl0".

CCXT will incorrectly think "kaspa" is the address and "qqetp7ct8kqss99fxmymyz5t3fezppxp0t58wl6pawp27elqd46uudme00cl0" is the tag on CoinEx.

**Comment by samgermain** [comment]
@carlosmiei [This issue seems well understood](https://github.com/Conflux-Chain/CIPs/blob/master/CIPs/cip-37.md) and there is a [PR to fix it here](https://github.com/pcriadoperez/ccxt/commit/a1f3e31db4be3def7061ebed2cb9e414cd84235a)

**Comment by carlosmiei** [comment]
> @carlosmiei [This issue seems well understood](https://github.com/Conflux-Chain/CIPs/blob/master/CIPs/cip-37.md) and there is a [PR to fix it here](https://github.com/pcriadoperez/ccxt/commit/a1f3e31db4be3def7061ebed2cb9e414cd84235a)

@samgermain will merge it

**Comment by StevenProhashing** [comment]
> I confirmed this issue also affects Kaspa (KAS), as Kaspa addresses also use the colon ":" character. Example Kaspa mainnet address "kaspa:qqetp7ct8kqss99fxmymyz5t3fezppxp0t58wl6pawp27elqd46uudme00cl0".
> 
> CCXT will incorrectly think "kaspa" is the address and "qqetp7ct8kqss99fxmymyz5t3fezppxp0t58wl6pawp27elqd46uudme00cl0" is the tag on CoinEx.

Thank you, though I would suggest doing

if (partsLength > 1 && parts[0] !== 'cfx' && parts[0] !== 'kaspa') {

Because this issue also affects Kaspa (KAS) addresses on CoinEx

**Comment by StevenProhashing** [comment]
> > I confirmed this issue also affects Kaspa (KAS), as Kaspa addresses also use the colon ":" character. Example Kaspa mainnet address "kaspa:qqetp7ct8kqss99fxmymyz5t3fezppxp0t58wl6pawp27elqd46uudme00cl0".
> > CCXT will incorrectly think "kaspa" is the address and "qqetp7ct8kqss99fxmymyz5t3fezppxp0t58wl6pawp27elqd46uudme00cl0" is the tag on CoinEx.
> 
> Thank you, though I would suggest doing
> 
> if (partsLength > 1 && parts[0] !== 'cfx' && parts[0] !== 'kaspa') {
> 
> Because this issue also affects Kaspa (KAS) addresses on CoinEx

Could this fix be done for kaspa too? I confirmed it is correct

**Comment by StevenProhashing** [comment]
@samgermain @carlosmiei
