### ISSUE TITLE
How to watch ticker and watch olhvc at same time?

### ISSUE THREAD

**Issue by Sailendrakc** [ccxt/ccxt#17201]
### ؜

Hi, guyz, is there a way to watch tickers and watch for olhcv at same time?
Atm, I can either watch ticker or watch olhcv seperately at same time, but not together.. I did not find it in the example either. 
I use javascript and free release of latest ccxt pro.

**Comment by carlosmiei** [comment]
Hello @Sailendrakc yes ofc, you just need to structure your code correctly, check this out: https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/js/gateio-swap-watch-many-orderbooks.js
