### ISSUE TITLE
how to run set trading stop in bybit

### ISSUE THREAD

**Issue by hosseinab** [ccxt/ccxt#17208]
hi . how to run trading stop in bybit exchange ?
https://bybit-exchange.github.io/docs/derivatives/contract/trading-stop

**Comment by hosseinab** [comment]
please remove new exchange label

**Comment by samgermain** [comment]
> hi . how to run trading stop in bybit exchange ?
> 
> https://bybit-exchange.github.io/docs/derivatives/contract/trading-stop

In this issue we explain how to set stop loss and take profit orders https://github.com/ccxt/ccxt/issues/13822

There's currently no unified way to set a trailing stop order

**Comment by samgermain** [comment]
> hi . how to run trading stop in bybit exchange ?
> 
> https://bybit-exchange.github.io/docs/derivatives/contract/trading-stop

In this issue we explain how to set stop loss and take profit orders https://github.com/ccxt/ccxt/issues/13822

There's currently no unified way to set a trailing stop order

**Comment by samgermain** [comment]
The implicit api method privatePostContractV3PrivateCopytradingOrderTradingStop corresponds to the bybit api documentation link that you posted

**Comment by hosseinab** [comment]
@samgermain ok . please explain edit tp and sl for open positions in bybit exchange.

**Comment by samgermain** [comment]
> @samgermain This task can be done with derivatives/contract/trading-stop

yes, but not using a unified ccxt method
