### ISSUE TITLE
Coinone will delete an api soon which is being used.

### ISSUE THREAD

**Issue by jkjin7** [ccxt/ccxt#17202]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

Coinone exchange [announced](https://doc.coinone.co.kr/#tag/Order-V2/operation/v2_order_order_info) they will delete an endpoint `/v2/order/order_info/` on end of this month(March 2023).

So I look into ccxt's implementation for that in `js/src/coinone.js`, then I found ccxt uses it.

The problem is getting order information is very important endpoint.

### Describe the solution you'd like

According to the [Coinone docs](https://doc.coinone.co.kr/#tag/Order-V2/operation/v2_order_order_info), we can use `/v2/order/query_order` instead.

I think they're pretty similar, so I want to do it myself but I haven't have enough experience in this project. That's why I'm just asking. If there is an opportunity for me to contribute in any way, please let me know.

### Describe alternatives you've considered

If this change is not completed on time, I will need to write my own source code for it, including all other endpoints (most of public, private for querying and ordering).

This is because I'm planning launch a beta service using ccxt and Coinone in early April.

**Comment by pcriadoperez** [comment]
Hi @jkjin7, thanks for reporting this. I'll work on implementing the change.

**Comment by jkjin7** [comment]
Thanks a lot!! It will help me so much!
