### ISSUE TITLE
Error ExchangeNotAvailable import

### ISSUE THREAD

**Issue by x1i4b1x2** [ccxt/ccxt#17221]
### Programming Languages

JS

### CCXT Version

latest

### Description

In version 2.9.9, this how you imported ExchangeNotAvailable, but in 3.x it doesn't find it there.

<img width="887" alt="Screenshot 2023-03-16 at 10 40 51 PM" src="https://user-images.githubusercontent.com/100806945/225758796-39dec55c-4885-4770-952e-75498ea6dc75.png">

But it finds it here:
<img width="485" alt="Screenshot 2023-03-16 at 10 36 12 PM" src="https://user-images.githubusercontent.com/100806945/225758011-770fa41a-9b25-4105-8340-33eba5f9d9b7.png">

But then when you run, this happens: 
<img width="778" alt="Screenshot 2023-03-16 at 10 37 47 PM" src="https://user-images.githubusercontent.com/100806945/225758271-72403155-65ce-46d0-918b-a50718b5815c.png">

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @x1i4b1x2 
You should be able to do 
```Typescript
import { errors } from 'ccxt'
const {ExchangeNotAvailable} = errors;
```
Also I don't know how that import would be possible using the 2.9.9 version because we never did `named exports` of Exceptions (however we will consider it)

**Comment by carlosmiei** [comment]
> 

@x1i4b1x2 Can you show me how you're importing `ccxt` here?

**Comment by x1i4b1x2** [comment]
<img width="440" alt="Screenshot 2023-03-17 at 11 08 03 AM" src="https://user-images.githubusercontent.com/100806945/225875142-5ac05e65-2d16-4311-b6d5-7c4395ef735b.png">

**Comment by carlosmiei** [comment]
> <img alt="Screenshot 2023-03-17 at 11 08 03 AM" width="440" src="https://user-images.githubusercontent.com/100806945/225875142-5ac05e65-2d16-4311-b6d5-7c4395ef735b.png">
> 
> By clicking on it, it goes right here: <img alt="Screenshot 2023-03-17 at 11 13 21 AM" width="516" src="https://user-images.githubusercontent.com/100806945/225876262-3e0500c5-cf39-4a6d-91ba-80dedeac775a.png">

@x1i4b1x2 thanks for helping me debugging it, it will be fixed asap here https://github.com/ccxt/ccxt/pull/17222/commits
