### ISSUE TITLE
Binance JS canelOrder - cannot delete the order

### ISSUE THREAD

**Issue by amtf** [ccxt/ccxt#1722]
Cannot delete the order. I am sure the order id is correct.
Query the balance is OK, the apikey should be OK.
Thanks.

binance DELETE https://api.binance.com/api/v3/order
Request:
 { 'X-MBX-APIKEY': 'FMxpmpmQRLoqKwuHPsGfl6A8PnxKuTHnCmD46DuT25ZT6Rv0NjoOblAyEtigxBnk',
  'Content-Type': 'application/x-www-form-urlencoded' } timestamp=1517541173090&recvWindow=5000&symbol=ETHBTC&orderId=11008153&signature=5e2a2ed30df8da2e0d1a5de9be65984f1e79d9750e9ae409a8346551282e8687
[Exchange Error] binance {"code":-2011,"msg":"UNKNOWN_ORDER"}

**Comment by kroitor** [comment]
We're investigating into it, but it seems they had a glitch approx 5 hours ago, and our tests have also detected the same error.

**Comment by amtf** [comment]
binance DELETE https://api.binance.com/api/v3/order
Request:
 { 'X-MBX-APIKEY': 'FMxpmpmQRLoqKwuHPsGfl6A8PnxKuTHnCmD46DuT25ZT6Rv0NjoOblAyEtigxBnk',
  'Content-Type': 'application/x-www-form-urlencoded' } timestamp=1517562389995&recvWindow=5000&symbol=ETHBTC&orderId=11008153&signature=d098731c4d87fc19ff08e603a37695501a8bcc1f3b02a52e34e99bb04d7573e4
[Exchange Error] binance {"code":-2011,"msg":"UNKNOWN_ORDER"}

Still got the error. Thanks.

**Comment by kroitor** [comment]
@amtf sure that the order exists (was successfully registered) in your history at all? Because if you're now retrying to cancel the non-existent order, you will get the same error over and over again... Or, do you first create the order and then try to cancel it?

Ensuring that it is a newly created and successfully opened order:

1. createOrder (catch exceptions)
2. fetchOrder (catch exceptions)
3. cancelOrder if `order['status'] !== 'closed'

Is that what you are trying? Can you post a minimal, but complete snippet of your code (without the keys, of course)?

**Comment by amtf** [comment]
1. Just created the new order

binance POST https://api.binance.com/api/v3/order
Request:
 { 'X-MBX-APIKEY': 'FMxpmpmQRLoqKwuHPsGfl6A8PnxKuTHnCmD46DuT25ZT6Rv0NjoOblAyEtigxBnk',
  'Content-Type': 'application/x-www-form-urlencoded' } timestamp=1517566448722&recvWindow=5000&symbol=ADABTC&quantity=1&type=LIMIT&side=SELL&price=0.11100000&timeInForce=GTC&signature=e6610f904f88b63105e16920f466384f43cfbaecca70dfc58b157fad30cfde50
binance POST https://api.binance.com/api/v3/order 200 OK
Response:
{"symbol":"ADABTC","orderId":11076428,"clientOrderId":"Qn2semfGh8A96e7EmWTWEt","transactTime":1517566449030,"price":"0.11100000","origQty":"1.00000000","executedQty":"0.00000000","status":"NEW","timeInForce":"GTC","type":"LIMIT","side":"SELL"}
binance { info:
   { symbol: 'ADABTC',
     orderId: 11076428,
     clientOrderId: 'Qn2semfGh8A96e7EmWTWEt',
     transactTime: 1517566449030,
     price: '0.11100000',
     origQty: '1.00000000',
     executedQty: '0.00000000',
     status: 'NEW',
     timeInForce: 'GTC',
     type: 'LIMIT',
     side: 'SELL' },
  id: '11076428',
  timestamp: 1517566449030,
  datetime: '2018-2-2 18:14:09',
  symbol: 'ADA/BTC',
  type: 'limit',
  side: 'sell',
  price: 0.111,
  amount: 1,
  cost: 0.111,
  filled: 0,
  remaining: 1,
  status: 'open',
  fee: undefined }

2. Just cancel the created order, but I got the error.

binance DELETE https://api.binance.com/api/v3/order
Request:
 { 'X-MBX-APIKEY': 'FMxpmpmQRLoqKwuHPsGfl6A8PnxKuTHnCmD46DuT25ZT6Rv0NjoOblAyEtigxBnk',
  'Content-Type': 'application/x-www-form-urlencoded' } timestamp=1517566493624&recvWindow=5000&symbol=ETHBTC&orderId=11076428&signature=8d152a2846bdb2725c888c549539fc5b5f54312428058d434d59451ca1ca7cab
[Exchange Error] binance {"code":-2011,"msg":"UNKNOWN_ORDER"}

**Comment by kroitor** [comment]
What's your programming language?

**Comment by mkutny** [comment]
This order came from a different symbol.

**Comment by amtf** [comment]
Yes. you are right. Sorry, I made the mistake.

Thanks for your time.

Some exchange is no need to pass the symbol that can delete the record, so I pass some default symbol in it.

Thanks again.

**Comment by kroitor** [comment]
@amtf thx for reporting back, closing it for now, if you don't mind. Fee free to reopen it, or jusk ask questions if you have any.

**Comment by kroitor** [comment]
@mkutny thx for your help, missed it somehow...

**Comment by mkutny** [comment]
@amtf just leaked his api keys so the issue was easy to spot once I've got into his account...

**Comment by kroitor** [comment]
@mkutny I didn't see a secret key anywhere, how is that possible? o.O

**Comment by mkutny** [comment]
If I tell you then you'll get access to that account too. Well, everyone would be able to get access to that account. But there is not enough money there for both of us. So let's wait until withdrawal request completes :-E

**Comment by kroitor** [comment]
Now I'm really shitting bricks... I don't want the access, just want to know if it is possible to obtain the access with the limited info that is currently present on this page? Is the security flaw still open?

**Comment by amtf** [comment]
@mkutny How can you do that? :-(

**Comment by mkutny** [comment]
Well... it's easy if to think in the right direction.
You disclosed your api key **and** the signature.
So if `signature = request * private key` then `private key = signature / request`.

**Comment by amtf** [comment]
@mkutny Really? Would you tell me what is my private key?
