### ISSUE TITLE
Get all markets across all exchanges

### ISSUE THREAD

**Issue by ankitgoyal100** [ccxt/ccxt#1723]
Ability to get all markets across all exchanges supported by ccxt

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/blob/master/examples/js/arbitrage-pairs.js
- https://github.com/ccxt/ccxt/blob/master/examples/py/arbitrage-pairs.py
- https://github.com/ccxt/ccxt/blob/master/examples/py/async-instantiate-all-at-once.py
- https://github.com/ccxt/ccxt/blob/master/examples/php/arbitrage-pairs.php
- https://github.com/ccxt/ccxt/blob/master/examples/php/load-all-at-once.php
