### ISSUE TITLE
Get best exchange price for specified symbol

### ISSUE THREAD

**Issue by ankitgoyal100** [ccxt/ccxt#1724]
Given a symbol (ex. 'BTC/USD'), should be able to get best exchange rate (depending on whether you want to buy or sell)

**Comment by wannesdemaeght** [comment]
This should give you a decent start.

```
let TickerExchanges = ["Gdax", "Bitstamp", "Quoinex", "Kraken"];
let exch = [];
let Price = [];
let Price,Bid = [];
let Price.Ask = [];
	
for (let x in TickerExchanges){
	let name = TickerExchanges[x];
	exch[name] = new ccxt[name.toLowerCase()]({});
	exch[name].fetchTicker("BTC/USD").then((result) => {
		Price.Bid[name]	= result.bid;
		Price.Ask[name]	= result.ask;
	}).catch((err) => {
		console.log( "no Ticker from", name);
	});
};
```

**Comment by kroitor** [comment]
@ankitgoyal100 this isn a swiss-army-knife library, it does not solve the logical tasks of finding best symbols for you, but, instead, it provides tools for you to build these types of algorithms easily, like shown by @wannesdemaeght above. Without even knowing your programming language it's quite hard to satisfy your request. Let us know if we can help with anything else on the subject.

- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/tree/master/examples
