### ISSUE TITLE
Same tickers for htibtc3, fmfwio and bitcoincom

### ISSUE THREAD

**Issue by Pennywise83** [ccxt/ccxt#17240]
### Operating System

Linux

### Programming Languages

JS

### CCXT Version

2.4.3

### Description

I've noticed that the ticker returned by the metod "fetchTicker" for hitbtc3, fmfwio and bitcoincom exchanges are always the same:

![Schermata del 2023-03-17 23-20-41](https://user-images.githubusercontent.com/6907768/226063591-8e07a0e4-b3a8-48fc-925d-2ec102a01aaa.png)

### Code

Step to reproduce the problem:

node ./cli.js bitcoincom fetchTicker BTC/USDT --poll

node ./cli.js fmfwio fetchTicker BTC/USDT --poll

 node ./cli.js hitbtc3 fetchTicker BTC/USDT --poll

**Comment by carlosmiei** [comment]
Hello @Pennywise83,
That is true because they are all alias to the same exchange, so the API used is the same (similar to the gate vs gateio exchanges)

**Comment by Pennywise83** [comment]
So fmfw and hitbtc are the same exchange?

**Comment by carlosmiei** [comment]
> So fmfw and hitbtc are the same exchange?

@Pennywise83 ok maybe saying they are the same might be inaccurate, but they're related somehow because although they use different servers the API is exactly the same
