### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by hodlerhacks** [ccxt/ccxt#17251]
### Operating System

Windows

### Programming Languages

JS

### CCXT Version

3.0.20

### Description

One of the users of my software got the following exception: Error [ERR_REQUIRE_ESM]: require() of ES Module

This appeared after updating my software, which jumped to CCXT (pro) v3.x.

I had no problem myself running both on Windows and Ubuntu. This person is running the software on Windows as well. 

Further details:

Node.js v18.12.1
2023/03/18 20:32:54: Bot Mgr > Restarting Bot 001
C:\Balance Bot\node_modules\ccxt\dist\ccxt.cjs:1
const ccxt = require('./cjs/ccxt.js');
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Balance Bot\node_modules\ccxt\dist\cjs\ccxt.js from C:\Balance Bot\node_modules\ccxt\dist\ccxt.cjs not supported.
ccxt.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename ccxt.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in C:\Balance Bot\node_modules\ccxt\package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.<anonymous> (C:\Balance Bot\node_modules\ccxt\dist\ccxt.cjs:1:14)
    at Object.<anonymous> (C:\Balance Bot\bb\bot.js:1:1169) {
  code: 'ERR_REQUIRE_ESM'
}

Any idea what might be causing this? Can I avoid this somehow? Or should I downgrade to v2.x for now?

### Code

```
  

```

**Comment by hodlerhacks** [comment]
I noticed that the exception points at a problem in line 1 in ccxt.cjs:

const ccxt = require('./cjs/ccxt.js');

But ccxt.cjs has the following instead:

const ccxt = require('./ccxt.bundle.cjs');

**Comment by carlosmiei** [comment]
Hello @hodlerhacks, that as a temporary issue with the package only in that version, can you try to update and try again? It should be fixed

**Comment by hodlerhacks** [comment]
Hi @carlosmiei, great! I already spotted some (seemingly) relevant changes in v3.0.23, and updated to that earlier today. I've asked the person who experienced the problem to test again. Will let you know.

**Comment by carlosmiei** [comment]
> Hi @carlosmiei, great! I already spotted some (seemingly) relevant changes in v3.0.23, and updated to that earlier today. I've asked the person who experienced the problem to test again. Will let you know.

@hodlerhacks let us know if anything!

**Comment by hodlerhacks** [comment]
Apologies for the delay, but I just got confirmation that this issue is now resolved. Thanks!
