### ISSUE TITLE
Too many requests; current limit of IP(XXX.XXX.XXX.XXX) is 2400 requests per minute. Please use the websocket for live updates to avoid polling the API

### ISSUE THREAD

**Issue by roisitbon** [ccxt/ccxt#17258]
### Operating System

Ubuntu 22.02

### Programming Languages

python

### CCXT Version

2.9.12

### Description

Hi all,
Sure this issue was raised by multiple people in the past but i can't seem to find a solution that will match my environment setup.
I have an Algo Trading bot for binance futures running on a multiThread per symbol in a single python script , it runs on a loop for 14 symbols.
I've set the interval to run every 2 seconds
Each interval for each symbol performs 
1. fetch OHLC
2. fetch balance
3. fetch trades

### Code

```
  

```

**Comment by pcriadoperez** [comment]
Hi @roisitbon , instead of polling we recommend to use websockets for these cases. You can use the functions `watchOHLCV`, `watchBalance` and `watchTrades`. Would this solve your issue?

**Comment by roisitbon** [comment]
That could help but doesn’t that require ccxt pro?

**Comment by roisitbon** [comment]
You just made my day !
I’ll test it thanks!
 Is there a limit of requests ?

**Comment by ConnectGrid** [comment]
> You just made my day ! I’ll test it thanks! Is there a limit of requests ?
> […](#)

With WebSockets, you open a persistent connection and data can flow in two directions. You may have already known that, but it replaces the need for request-response behaviour, so polling is not needed. Your script just waits for new data, and responds to it when that data is pushed to you. No need to ask for it.

**Comment by pcriadoperez** [comment]
Clossing this issue for now, but feel free to open any new questions here or through our discord
