### ISSUE TITLE
How do I close the current position in phemex (that has stoploss)?

### ISSUE THREAD

**Issue by yongguncodework** [ccxt/ccxt#17255]
### Programming Languages

python

### CCXT Version

newest

### Description

I saw the description that once I create order with stoploss, I can't make another stoploss for opposite side.
for example,

```
    exchange.create_order(
    symbol = symbol2,
    type = 'market', 
    side = 'buy', 
    amount = amount_cont,
    # price = price,
    params = {'stopLossPrice': price-30}
    )
```

if I want to place next order as opposite (now as sell), it doesn't let me.
Is there any way I can close this order and then place new sell order with stoploss as well?
I wanted to use cancel_all_orders or cancel_order, but I think they don't work.

I wish to know close any current position

### Code

```
  

```

**Comment by AlgoQ** [comment]
Hi,

The `cancel_order`/`cancel_all_orders` is only able to delete open orders.

To close a position:
```py
symbol = 'ETH/USDT:USDT'

exchange.createOrder(symbol, 'market', 'buy', 0.01, None, {'posSide':'Long', 'stopPrice':1600})
# close position
exchange.createOrder(symbol, 'market', 'sell', 0.01, None, {'posSide':'Long', 'reduceOnly': True})
```
