### ISSUE TITLE
poloniex async cancel_order, edit_order wrong Exception

### ISSUE THREAD

**Issue by cfytrok** [ccxt/ccxt#1726]
- OS: Windows 10
- Programming Language version: python
- CCXT version: 1.10.970
- Exchange: poloniex
- Method: cancel_order, edit_order

cancel_order and edit_order methonds in asynchronous mode raise ExchangeError instead of OrderNotFound when order doesn't exist. Seems self.last_http_response is not set.

**Comment by kroitor** [comment]
Can you please show verbose output (add `{'verbose':True}` to constructor params and show their replies) ?

**Comment by cfytrok** [comment]
https://poloniex.com/tradingApi POST https://poloniex.com/tradingApi 
Request: {'Content-Type': 'application/x-www-form-urlencoded', 'Key': '***', 'Sign': '***', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} command=cancelOrder&orderNumber=60531094403&nonce=1517574559495
POST https://poloniex.com/tradingApi 
Response: {'Content-Type': 'application/x-www-form-urlencoded', 'Key': '***', 'Sign': '***', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} {"error":"Invalid order number, or you are not the person who placed the order.","success":0}

**Comment by cfytrok** [comment]
Still not work.
poloniex Response code is 200, so handle_errors don't handle this error.

**Comment by cfytrok** [comment]
Could you add response code to verbose output?

**Comment by kroitor** [comment]
> Could you add response code to verbose output?

Yep, will do, thx.
