### ISSUE TITLE
phemex orderID missing from fetch_position

### ISSUE THREAD

**Issue by yongguncodework** [ccxt/ccxt#17261]
### Programming Languages

python

### Description

I was using fetch_positions to findout orderID, so I can use edit_order.
However, there is no way to get orderID in there.
Can you make some example for it or fix the function?
There is no way to use edit_order function since there is no way to get orderID even if I have position.

I keep getting such as below
`{'collateral': 0.0125929,
 'contractSize': 1.0,
 'contracts': 2.0,
 'datetime': None,
 'entryPrice': 27122.3217,
 'hedged': False,
 'id': None,`

### Code

```
  

```

**Comment by pcriadoperez** [comment]
Hi @yongguncodework , In the case of positions, there is not an assoiciated order id, as it could have been created by several different orders. If you wish to change your existing position you can use `create_order` to create a new order to either increase or reduce your position.

I hope this answers your question, I'll close the issue for now but feel free to reach out with any more questions.

**Comment by yongguncodework** [comment]
@pcriadoperez Hi Thank you for the answer.
Could you answer one more thing for me?
I was checking the edit_order in phemex part and I got confuse.
for example if I have an order that is placed at 25000 and wish to switch to 24000 buy order, how should I write it?
i was trying, but got stuck here.
`
checking_orders = exchange.fetch_open_orders(symbol = symbol2, params=params)
# Get 1st order id
1st_order_id = checking_orders [0]['info']['id']
my_edit_order = exchange.edit_order(id=1st_order_id , symbol=my_symbol, type="Limit", side="Buy", amount="This part is the question", price="1000", params={}):
`
Can you help me for this question? I wonder how to edit the current holding order.
