### ISSUE TITLE
amount_to_precision 

### ISSUE THREAD

**Issue by cfytrok** [ccxt/ccxt#1727]
OS: Windows 10
Programming Language version: python 3.6.3
CCXT version: 1.10.970
Exchange: poloniex
Method: amount_to_precision

Exchange.amount_to_precision() returns anexpected result because of float rounding.
Example:
amount_to_precision('ETH/BTC',0.00000003) returns 2e-08

Seems have to use same code as for Exchange.price_to_precision()

**Comment by kroitor** [comment]
It is a known issue and we are working on it here:

- https://github.com/ccxt/ccxt/issues/522
- https://github.com/ccxt/ccxt/issues/1483
- https://github.com/ccxt/ccxt/pull/1635

We will update on this, hope to resolve it soon, in the meantime, I suggest to move all precision-related discussion to one of the above posts. Closing this as a duplicate for now. Let us know if the above does not answer your question.
