### ISSUE TITLE
Uncaught Exception while watching orderbook with ccxt pro 

### ISSUE THREAD

**Issue by ratroot92** [ccxt/ccxt#17271]
### Operating System

ubuntu

### Programming Languages

JS

### Description

While watching the order book with ccxt pro i encountered the above error 
![Screenshot from 2023-03-20 15-07-21](https://user-images.githubusercontent.com/49342301/226309110-f77d45f6-4ce2-4704-be9b-58dfd31bceca.png)

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @ratroot92,
What is your ccxt version, exchange used and if possible can you share with us a verbose log?

**Comment by ratroot92** [comment]
exchange is binance and ccxt version is 
 "name": "ccxt.pro",
  "version": "1.0.53",

**Comment by carlosmiei** [comment]
@ratroot92 Ok so you have a pretty outdated version of ccxt and you're still using the old detached` ccxt.pro`, so I would suggest upgrading to the latest ccxt version that also includes `ccxt.pro`. 

You only need to change your import statement slightly:

```Javascript
const ccxt = require('ccxt').pro
```
or  (if you're using esm)

```Javascript
import { pro } from 'ccxt'
```

**Comment by carlosmiei** [comment]
goo
