### ISSUE TITLE
Bybit missing endpoints

### ISSUE THREAD

**Issue by yatoh22** [ccxt/ccxt#17285]
### Operating System

Windows

### Programming Languages

python

### CCXT Version

3

### Description

Unable to find some endpoints for bybit, e.g. "/spot/v3/private/margin-loan-infos"

Is there a way to add custom endpoint to CCXT .api properties?

Thanks in advance.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @yatoh22 we will try to add them as soon as possible. Thanks for the heads up!
cc/ @sc0Vu
