### ISSUE TITLE
OKX Demo Trading - Basic functions come back with "This feature is temporarily unavailable in demo trading"

### ISSUE THREAD

**Issue by jalapeno777** [ccxt/ccxt#17295]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

3.0.26

### Description

Attempts at using OKX's demo servers seems to produce errors doing even basic things like getting balances or getting available symbols.  No issues running this on the live api.  Spoke with OKX support and they stated all API functions are live on the demo server so not sure where the issue may be stemming from

### Code

# connect to an exchange

import ccxt
import key_file as k

print('CCXT Version: ', ccxt.__version__)

exchange = ccxt.okx({
    'enableRateLimit': True,
    'apiKey' : k.livekey,
    'secret': k.livesecret,
    'password' : k.livepassphrase
})
exchange.set_sandbox_mode(True)
exchange.verbose = True
permissions = exchange.has
print(permissions)
markets = exchange.load_markets()
bal = exchange.fetch_balance()

print(markets)
print(bal)

CCXT Version:  3.0.26
{'publicAPI': True, 'privateAPI': True, 'CORS': None, 'spot': True, 'margin': True, 'swap': True, 'future': True, 'option': None, 'addMargin': True, 'cancelAllOrders': False, 'cancelOrder': True, 'cancelOrders': True, 'createDepositAddress': False, 'createLimitOrder': True, 'createMarketOrder': True, 'createOrder': True, 'createPostOnlyOrder': True, 'createReduceOnlyOrder': True, 'createStopOrder': True, 'createStopLimitOrder': True, 'createStopMarketOrder': True, 'editOrder': 'emulated', 'fetchAccounts': True, 'fetchBalance': True, 'fetchBidsAsks': None, 'fetchBorrowInterest': True, 'fetchBorrowRate': True, 'fetchBorrowRateHistory': True, 'fetchBorrowRatesPerSymbol': False, 'fetchBorrowRates': True, 'fetchCanceledOrders': True, 'fetchClosedOrder': None, 'fetchClosedOrders': True, 'fetchCurrencies': True, 'fetchDeposit': True, 'fetchDepositAddress': True, 'fetchDepositAddresses': False, 'fetchDepositAddressesByNetwork': True, 'fetchDeposits': True, 'fetchFundingFee': None, 'fetchFundingFees': None, 'fetchFundingHistory': True, 'fetchFundingRate': True, 'fetchFundingRateHistory': True, 'fetchFundingRates': False, 'fetchIndexOHLCV': True, 'fetchL2OrderBook': True, 'fetchLedger': True, 'fetchLedgerEntry': None, 'fetchLeverageTiers': False, 'fetchMarketLeverageTiers': True, 'fetchMarkets': True, 'fetchMarkOHLCV': True, 'fetchMyTrades': True, 'fetchOHLCV': True, 'fetchOpenOrder': None, 'fetchOpenOrders': True, 'fetchOrder': True, 'fetchOrderBook': True, 'fetchOrderBooks': False, 'fetchOrders': False, 'fetchOrderTrades': True, 'fetchPermissions': None, 'fetchPosition': True, 'fetchPositions': True, 'fetchPositionsRisk': False, 'fetchPremiumIndexOHLCV': False, 'fetchStatus': True, 'fetchTicker': True, 'fetchTickers': True, 'fetchTime': True, 'fetchTrades': True, 'fetchTradingFee': True, 'fetchTradingFees': False, 'fetchTradingLimits': False, 'fetchTransactions': False, 'fetchTransfers': False, 'fetchWithdrawal': True, 'fetchWithdrawals': True, 'reduceMargin': True, 'setLeverage': True, 'setMargin': False, 'setMarginMode': True, 'setPositionMode': True, 'signIn': False, 'transfer': True, 'withdraw': True, 'borrowMargin': True, 'fetchBorrowRateHistories': True, 'fetchDepositWithdrawFee': 'emulated', 'fetchDepositWithdrawFees': True, 'fetchL3OrderBook': False, 'fetchLeverage': True, 'fetchOpenInterest': True, 'fetchOpenInterestHistory': True, 'fetchTransactionFee': False, 'fetchTransactionFees': False, 'fetchTransfer': True, 'fetchWithdrawalWhitelist': False, 'repayMargin': True}

fetch Response: okx GET https://www.okx.com/api/v5/asset/currencies 200 ResponseHeaders: {'Date': 'Tue, 21 Mar 2023 19:00:55 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': 'locale=en_US; Max-Age=604800; Expires=Tue, 28-Mar-2023 19:00:55 GMT; Path=/, locale=en_US; Max-Age=604800; Expires=Tue, 28-Mar-2023 19:00:55 GMT; Path=/, __cf_bm=ZpbfobErm1DEnH3Pe0CI6iviPY8ar5HI.Dx3RGfT8Zk-1679425255-0-ARSx6Kb9E+uqbX4yl+rIEFosb4qYoGc1MPgWnDVbsBQG0V+IlC1dD4Adc7qO+EzAdB3cVDwoO2vyDLbcI+l+S0I=; path=/; expires=Tue, 21-Mar-23 19:30:55 GMT; domain=.okx.com; HttpOnly; Secure; SameSite=None', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY', 'X-BrokerID': '9999', 'Strict-Transport-Security': 'max-age=63072000; includeSubdomains; preload', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '7ab870c51f605425-YYZ', 
'Content-Encoding': 'gzip'} ResponseBody: {"code":"50038","data":[],"msg":"This feature is temporarily unavailable in demo trading"}
Traceback (most recent call last):
  File "c:\Users\Tacos\bots\4_algo_orders.py", line 18, in <module>
    markets = exchange.load_markets()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\site-packages\ccxt\base\exchange.py", line 1459, in load_markets
    currencies = self.fetch_currencies()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\site-packages\ccxt\okx.py", line 1205, in fetch_currencies
    response = self.privateGetAssetCurrencies(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\site-packages\ccxt\base\exchange.py", line 505, in inner
    return entry(_self, **inner_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\site-packages\ccxt\base\exchange.py", line 2931, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\site-packages\ccxt\base\exchange.py", line 2928, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\site-packages\ccxt\base\exchange.py", line 667, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "D:\Python\Python311\Lib\site-packages\ccxt\okx.py", line 5610, in handle_errors
    raise ExchangeError(feedback)  # unknown message
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ccxt.base.errors.ExchangeError: okx {"code":"50038","data":[],"msg":"This feature is temporarily unavailable in demo trading"}

**Comment by carlosmiei** [comment]
Hey @jalapeno777 @filipzupancic, we will be fixed asap, thanks for letting us know
