### ISSUE TITLE
Coinmarketcap CAT: BlockCAT vs CatCoin conflict

### ISSUE THREAD

**Issue by swilso793** [ccxt/ccxt#1729]
Ubuntu
Python 3.5.3
CCXT version Latest
CoinmarketCap
FetchTickers

The symbol is not a unique ID in coinmarketcap. So fetch tickers retrieves only the first/last coin with a specific symbol. There is a unique field in ['info']['id']. 
Example to recreate. Fetch ticker for CAT expecting BlockCAT but you get CatCoin.

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/issues/1359
- https://github.com/ccxt/ccxt/issues/1171
- https://github.com/ccxt/ccxt/issues/1330
- https://github.com/ccxt/ccxt/issues/1487

In general the one with highest market cap wins and the other one is to be renamed. Will fix it for that particular currency shortly.
