### ISSUE TITLE
exchange.loadMarkets() returns unsupported TUSD pairs for Binance

### ISSUE THREAD

**Issue by hodlerhacks** [ccxt/ccxt#17307]
### Operating System

Windows

### Programming Languages

JS

### CCXT Version

3.0.23

### Description

The symbols returned when using exchange.loadMarkets() with Binance returns the following TUSD trading pairs:

ADA/TUSD
ALGO/TUSD
ANKR/TUSD
ATOM/TUSD
BAT/TUSD
BCH/TUSD
BCPT/TUSD
BNB/TUSD
BSV/TUSD
BTC/TUSD
BTT/TUSD
EOS/TUSD
ETC/TUSD
ETH/TUSD
FTM/TUSD
GTO/TUSD
LINK/TUSD
LTC/TUSD
NEO/TUSD
ONE/TUSD
PAX/TUSD
PHB/TUSD
TFUEL/TUSD
TRX/TUSD
TUSD/BNB
TUSD/BTC
TUSD/BUSD
TUSD/ETH
TUSD/USDT
TUSDB/TUSD
USDC/TUSD
USDS/TUSD
WAVES/TUSD
XLM/TUSD
XRP/TUSD
ZEC/TUSD

Of these, only the following are actually available on Binance:
BNB/TUSD
BTC/TUSD
ETH/TUSD
TUSD/USDT

Perhaps this is a problem on the Binance side, but reporting it just in case.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @hodlerhacks,
Thanks but if you look closely the market has `active:false` meaning that the market exists but is not available for trading
