### ISSUE TITLE
Will CCXT allow spot market order on Gate.io? 

### ISSUE THREAD

**Issue by stspinu** [ccxt/ccxt#17304]
Hi team,

This post is related to -> https://github.com/ccxt/ccxt/blob/eaf415341690c4700ed1a6d8f6d70a0aa89cdfe9/ts/src/gate.ts#L75

The exchange Gateio now **supports _spot_ market orders** (starting with v4.34.0), as shown on their documentation below:
[GateIO Developer Documentation link](https://www.gate.io/docs/developers/apiv4/en/#changelog)

![image](https://user-images.githubusercontent.com/46924453/226953110-7aa3550b-af12-44c4-9361-28e7a99d78db.png)

Would it be possible for you to introduce market orders within CCXT please, so that we can use it in our tools (ex: freqtrade, as discussed on [thread 6005](https://github.com/freqtrade/freqtrade/issues/6005) and [thread 8368](https://github.com/freqtrade/freqtrade/issues/8368))?

Or are there any plans to introduce support for Market Orders on the SPOT market in the near future?

Thank you!

**Comment by carlosmiei** [comment]
> 

@xmatthias Hey, hum I don't see that logic 🤔 
Basic this is the flow:
- If market buy order, gate requires the amount in the quote currency (`cost`) so the user needs to either provide amount+price so that we can multiply and find the cost or provide `amount=cost` after disabling the `createmarketBuyRequiresPrice` option.

The explicit disable is required to avoid the user providing `amount = 1000000` thinking he is sizing in SHIB but ending up with a huge order because he provided the cost instead.

**Comment by xmatthias** [comment]
@carlosmiei i do think that i do understand the meaning of `createMarketBuyOrderRequiresPrice`. It's used in other exchanges, too - but in my understanding, the ccxt default for it is false if it's not set (it's not set for binance for example - and binance works perfectly fine without price -> the ccxt default is assumed to be false).

As gate doesn't set this - my assumption is that `createMarketBuyOrderRequiresPrice` defaults to false - but then order creation does not work.

**Comment by stspinu** [comment]
> @carlosmiei i do think that i do understand the meaning of `createMarketBuyOrderRequiresPrice`. It's used in other exchanges, too, defining the need for price in a market order (which would normally not be required).
> 
> in my understanding, the ccxt default for it is false if it's not set (it's not set for binance for example - and binance works perfectly fine without price -> the ccxt default is assumed to be false).
> 
> As gate doesn't set this - my assumption is that `createMarketBuyOrderRequiresPrice` defaults to false - but then order creation does not work.

hi @xmatthias and @carlosmiei - is the market order now available on CCXT and thus on Freqtrade as well? Or not yet? Thank you!

**Comment by xmatthias** [comment]
it's available in freqtrade as of 2023.3 - - and was also mentioned in the [changelog](https://github.com/freqtrade/freqtrade/releases/tag/2023.3).
