### ISSUE TITLE
how to install ccxt pro in python?

### ISSUE THREAD

**Issue by chaedongyoon** [ccxt/ccxt#17300]
### Operating System

windows 11

### CCXT Version

nope

### Description

Python
# if you're using Git/HTTPS authentication
pip3 install git+https://github.com/kroitor/ccxt.pro.git#subdirectory=python

# if you are connecting to GitHub with SSH
pip3 install git+ssh://git@github.com/kroitor/ccxt.pro.git#subdirectory=python

--------------------------------------------------------------------------------
I had read above article, and then tried to install it 

but it can't.  error msg is below

### Code

C:\coding>pip3 install git+https://github.com/kroitor/ccxt.pro.git#subdirectory=python
Collecting git+https://github.com/kroitor/ccxt.pro.git#subdirectory=python
  Cloning https://github.com/kroitor/ccxt.pro.git to c:\users\name\appdata\local\temp\pip-req-build-d5613_39
  Running command git clone --filter=blob:none --quiet https://github.com/kroitor/ccxt.pro.git 'C:\Users\name\AppData\Local\Temp\pip-req-build-d5613_39'
info: please complete authentication in your browser...
  remote: Repository not found.
  fatal: repository 'https://github.com/kroitor/ccxt.pro.git/' not found
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/kroitor/ccxt.pro.git 'C:\Users\name\AppData\Local\Temp\pip-req-build-d5613_39' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/kroitor/ccxt.pro.git 'C:\Users\name\AppData\Local\Temp\pip-req-build-d5613_39' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

C:\coding>

**Comment by carlosmiei** [comment]
Hello @chaedongyoon,
CCXT.PRO was merged into `ccxt` so you just need to install `ccxt` to access it. 
You can check how to use it here: https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro

**Comment by chaedongyoon** [comment]
import ccxt.pro
from pprint import pprint
from asyncio import run


print('CCXT Version:', ccxt.__version__)


async def main():
    exchange = ccxt.pro.binance({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET',
    })

    markets = await exchange.load_markets()

    # exchange.verbose = True  # uncomment for debugging purposes if necessary

    symbol = 'ETH/BTC'
    type = 'limit'  # or 'market'
    side = 'sell'  # or 'buy'
    amount = 1.0
    price = 0.060154  # or None

    order = await exchange.create_order(symbol, type, side, amount, price)
    canceled = await exchange.cancel_order(order['id'], order['symbol'])

    pprint(canceled)

    await exchange.close()


run(main())

-------------------------------------------------------------------------------------

C:\coding>C:/Python310/python.exe c:/Python310/lib/site-packages/ccxt/pro/__init__.py
CCXT Version: 1.88.47
Traceback (most recent call last):
  File "c:\Python310\lib\site-packages\ccxt\pro\__init__.py", line 1, in <module>
    import ccxt.pro
  File "C:\Python310\lib\site-packages\ccxt\pro\__init__.py", line 33, in <module>
    run(main())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Python310\lib\site-packages\ccxt\pro\__init__.py", line 10, in main
    exchange = ccxt.pro.binance({
AttributeError: module 'ccxt' has no attribute 'pro'



i cant apply sample, beacuse of above error code,

and it is white color that between ""  => ccxt.pro,"binance"
could you give me a help?
