### ISSUE TITLE
Bybit: triggerPrice not working anymore, but stopPrice does work

### ISSUE THREAD

**Issue by marcoismobile** [ccxt/ccxt#17323]
### Operating System

Linux

### Programming Languages

python

### CCXT Version

3.0.31

### Description

It seems that when trying to create a 'Conditional' order on Bybit, the **triggerPrice** is no longer working the same as in previous versions, while using the create_order method (and calling the create_contract_v3_order method indirectly).

In version 2.7.32 it was still working with the **triggerPrice**, but now in version 3.0.31 it gives the following error:

```
BadRequest('bybit {"retCode":10001,"retMsg":"Request parameter error.","result":{},"retExtInfo":{},"time":1679666400145}')
```

After some debugging:

- it seems to be still working if I change the **triggerPrice** to **stopPrice**. (which is also still assigned to the same variable:         triggerPrice = self.safe_number_2(params, 'triggerPrice', 'stopPrice')

When comparing both versions, I could find that the **triggerPrice** is no longer 'omitted'  from the params variable, not sure if that can be the cause of this problem? : https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/bybit.py#L3398

### Code

```
  

```

**Comment by Dan-krm** [comment]
@marcoismobile in the previous version the `triggerPrice` variable was set as the default to the `stopLossTriggerPrice` variable, If you want to use the `triggerPrice` or `stopPrice` parameters the same as it was used before you need to add `'reduceOnly':true` to your code, otherwise you can use `stopLossPrice` or `takeProfitPrice` parameters instead that automatically set reduceOnly to true.

The triggerPrice doesn't need to be omitted because it's a parameter accepted by the exchange api. I tested and it looks like it's working as expected:

```
bybit createOrder BTC/USDT:USDT limit buy 0.001 20000 '{"triggerPrice":"21000"}'

bybit.createOrder (BTC/USDT:USDT, limit, buy, 0.001, 20000, [object Object])
2023-03-24T20:04:58.187Z iteration 0 passed in 637 ms

{
  info: { orderId: '45dec4e1-8059-4b1a-a243-c0611d244820', orderLinkId: '' },
  id: '45dec4e1-8059-4b1a-a243-c0611d244820',
  clientOrderId: undefined,
  timestamp: undefined,
  datetime: undefined,
  lastTradeTimestamp: undefined,
  symbol: undefined,
  type: undefined,
  timeInForce: undefined,
  postOnly: undefined,
  reduceOnly: undefined,
  side: undefined,
  price: undefined,
  stopPrice: undefined,
  triggerPrice: undefined,
  amount: undefined,
  cost: undefined,
  average: undefined,
  filled: undefined,
  remaining: undefined,
  status: undefined,
  fee: undefined,
  trades: [],
  fees: []
}
```

Some of this might change again in the future as there's still some debate about how we want to unify trigger and stopLoss/takeProfit orders. For example, I think the current stopLossPrice and takeProfitPrice parameters will probably be removed or renamed to stopLossTriggerPrice and takeProfitTriggerPrice eventually because they're just reduceOnly trigger orders in most cases and true stopLoss and takeProfit orders are separate and attached to positions.

Let us know if you have any more questions, and if you have any more questions please share examples of your requests and verbose output.

**Comment by marcoismobile** [comment]
@Dan-krm Thank you for your response!

But I the reason why I am using the conditional/triggered order is:
- in dual position mode
- open a hedge position in de opposite direction with a conditional market order, so the reduceOnly = False in my case.

NOT WORKING::
```
Request:
params ={'position_idx': 2, 'triggerPrice': 1.1602080319489017, 'triggerDirection': 1, 'triggerBy': 'LastPrice', 'reduceOnly': True}
bybit.createOrder('MATIC/USDT:USDT', 'market', 'buy', 2.5365765276079175, None, params)

Response:
{'info': {'orderId': '92c0b053-b7aa-44d9-9f43-5f7209bf3b04', 'orderLinkId': ''}, 'id': '92c0b053-b7aa-44d9-9f43-5f7209bf3b04', 'clientOrderId': None, 'timestamp': None, 'datetime': None, 'lastTradeTimestamp': None, 'symbol': None, 'type': None, 'timeInForce': None, 'postOnly': None, 'reduceOnly': None, 'side': None, 'price': None, 'stopPrice': None, 'triggerPrice': None, 'amount': None, 'cost': None, 'average': None, 'filled': None, 'remaining': None, 'status': None, 'fee': None, 'trades': [], 'fees': []}
```

WORKING::
```
Request:
params ={'position_idx': 2, 'stopPrice': 1.1602080319489017, 'triggerDirection': 1, 'triggerBy': 'LastPrice', 'reduceOnly': True}
bybit.createOrder('MATIC/USDT:USDT', 'market', 'buy', 2.5365765276079175, None, params)

Response:
BadRequest('bybit {"retCode":10001,"retMsg":"Request parameter error.","result":{},"retExtInfo":{},"time":1679666400145}')
```

So the only difference here is the **triggerPrice** vs. **stopPrice**, so unless there is another way to open a hedge position with a conditional market order?

**Comment by Dan-krm** [comment]
Thanks for clarifying

Both are working for me:
`node examples/js/cli bybit createOrder ADA/USDT:USDT market buy 8.0 undefined '{"triggerPrice":"0.5433","positionIdx":1,"triggerDirection":1}'`
and:
`node examples/js/cli bybit createOrder ADA/USDT:USDT market buy 8.0 undefined '{"stopPrice":"0.5433","positionIdx":1,"triggerDirection":1}'`

That's unusual that it's working for stopPrice and not triggerPrice for you but it looks like you might have an issue with setting your parameters, The triggerPrice requires a string on bybit and for the ADA/USDT:USDT pair it only goes up to four decimal places so `"triggerPrice":"0.5434"` also the parameter `position_idx` should instead be `positionIdx`
https://bybit-exchange.github.io/docs/derivatives/contract/place-order

Let me know if those changes to your parameters fix the issue for you

**Comment by marcoismobile** [comment]
@Dan-krm Thank you very much for the response, it was indeed the way I was setting the parameter!

I was using a **float** instead of the required **string** and on top of that the **precision** was wrong, so changing the code to this solved my problem:
```
'triggerPrice':  self.price_to_precision(symbol, 0.543375)
```

Thanks again for your clarification and this solves my problem ;-)
