### ISSUE TITLE
DSX market order not implemented (and API seems still in V1 instead of V2)

### ISSUE THREAD

**Issue by LaurentIsRunning** [ccxt/ccxt#1732]
The creation of market order on the DSX exchange is not implemented.
And the exchange does not allow to emulate them because the API allows to make 'market order' (I also tried on their website and confirm that it doesn't work).
However the DSX api seems still in V1 and not in V2.

Is there some plan to implement it?

- OS: Winows 10
- Programming Language version: Python
- CCXT version: 1.10.914
- Exchange:DSX
- Method: create_market_sell_order

**Comment by LaurentIsRunning** [comment]
Hi, 

In the documentation [here](https://dsx.docs.apiary.io/#reference/order/new-order/create-new-order) the url to place an order is 'https://dsx.uk/tapi/v2/order/new'.

If I understand the code correctly, the current dsx api point to https://dsx.uk/tapi, but there is nothing to adress the 'v2'.
But I must admit that the way implicit methods are build is not yet totally clear for me. 
It is not alos totally clear why dsx inherit from liqui. (Maybe I should read the code in javascript and not in Python).

Something that seems not so easy for the generic aspect of ccxt is that, even for market order, dsx requires a price (a "security" limit price).

I hope this helps...

**Comment by Sukaesihessy** [comment]
Saya mau my github bisa untuk membuat bot protech and bot kick


Pada tanggal 12 Feb 2018 15.53, "Laurent" <notifications@github.com>
menulis:

**Comment by ongkhua** [comment]
anyone working on this ?
