### ISSUE TITLE
hitbtc invalid sign

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#17325]
### Operating System

Linux

### Programming Languages

JS

### CCXT Version

3.0.32

### Description

every private method on hitbtc gives `ExchangeError: hitbtc {"error":{"code":1004,"message":"Unsupported authorization method"}}`
it was ok in 3.0.29

**Comment by carlosmiei** [comment]
> The same problem at least on ZB and Coinex

Hello @ndubel coinex is already fixed, will check ZB and HITBTC now. Thanks for letting us know
