### ISSUE TITLE
[Bug] Bittrex OHLCV not realtime?

### ISSUE THREAD

**Issue by andyperisho** [ccxt/ccxt#1733]
Here's how I'm doing the OHLCV requests:
```
  new ccxt[exchange]().fetchOHLCV(
    'ETH/BTC", 
    '1m',
    undefined
  )

```

And, here's the output for 3 exchange (binance, bittrex, okex):
```
okex:
Fri Feb 02 2018 21:52:00 GMT+0700 (+07) (printCurrent @ index.mjs:32)

binance
 Fri Feb 02 2018 21:52:00 GMT+0700 (+07) (printCurrent @ index.mjs:32)

bittrex
Fri Feb 02 2018 21:49:00 GMT+0700 (+07) (printCurrent @ index.mjs:32)
```

Notice how bittrex is lagging? I kept on running the script for a while, and bittrex OHLCV was consistently 3-4 min lagging behind.
Is this a bug in my code, or a bug in the library?

**Comment by kroitor** [comment]
> Is this a bug in my code, or a bug in the library?

This is neither a bug in your code, nor a bug in the library. It's just how Bittrex works, and if you enable the `{'verbose': True}` to the constructor params, and check their URLS yourself. Bittrex does not have an official OHLCV endpoint at all, and we use their undocumented v2.0 endpoint for that. Hope it answers your question. Thx!

**Comment by andyperisho** [comment]
Wow! I checked their own website, and I get the same 'delay' on their own charts. That's really not a good thing at all, but that's beyoud the scope of this library.
Your answer makes total sense. Thx a lot!
