### ISSUE TITLE
COINEX fetch_funding_rate_history gives exception by default - coinex safeMarket() requires a fourth argument to disambiguate

### ISSUE THREAD

**Issue by BertkeOfUtrecht** [ccxt/ccxt#17353]
### Operating System

Windows

### Programming Languages

python

### CCXT Version

3.0.36

### Description

Hi, 

As can be seen from below log, coinex fetch_funding_rate_history gives error always even though api returns data.

# Start of console log with explanatory python style comments
CCXT Version: 3.0.36

#Below calls first to init as usual
# self.exchange = ccxt.coinex()
# self.exchange.load_markets()
fetch Request: coinex GET https://api.coinex.com/perpetual/v1/time RequestHeaders: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: coinex GET https://api.coinex.com/perpetual/v1/time 200 ResponseHeaders: {'Date': 'Sun, 26 Mar 2023 21:08:07 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '46', 'Connection': 'keep-alive', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '7ae25df9bcf2b742-AMS'} ResponseBody: {"code":0,"data":1679864887432,"message":"OK"}

# self.exchange.fetch_funding_rate_history('BTC/USDT:USDT', 0, 100, {'end_time': 1617152887})
# end_time is in secs since coinex uses end time in secs and if milisec given, api gives "invalid argument" error
fetch Request: coinex GET https://api.coinex.com/perpetual/v1/market/funding_history?market=BTCUSDT&limit=100&offset=0&start_time=0&end_time=1617152887 RequestHeaders: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: coinex GET https://api.coinex.com/perpetual/v1/market/funding_history?market=BTCUSDT&limit=100&offset=0&start_time=0&end_time=1617152887 200 ResponseHeaders: {'Date': 'Sun, 26 Mar 2023 21:08:07 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '7ae25dfb6e8bb742-AMS'} ResponseBody: # API returns valid data, removed due to length }, "message": "OK"}
# receiving exception with below msg from exchange.py safe_market function
**coinex safeMarket() requires a fourth argument for BTCUSDT to disambiguate between different markets with the same market** id

Process finished with exit code 0

#I see fix should be adding 'swap' parameter in call  symbol = self.safe_symbol(marketId)
symbol = self.safe_symbol(marketId, None, None, 'swap')

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @BertkeOfUtrecht,
Thanks for letting us know I will take a look

**Comment by BertkeOfUtrecht** [comment]
Hello,

Any news about the fix?
Thanks.

**Comment by carlosmiei** [comment]
@BertkeOfUtrecht yeah this was fixed long ago.
