### ISSUE TITLE
[kucoin] private_post_accounts results in wrong endpoint

### ISSUE THREAD

**Issue by krychla1** [ccxt/ccxt#17369]
### Operating System

linux, windows

### Programming Languages

JS

### CCXT Version

3.0.37

### Description

Dear support,
exchange.private_post_accounts results in v2 endpoint, which doesn't work. v1 should be used instead.

### Code

```
  
POST https://api.kucoin.com/api/v2/accounts 
RequestBody:
 {"currency":"USDP","type":"main"} 
404 Not Found 


POST https://api.kucoin.com/api/v1/accounts 
RequestBody:
 {"currency":"USDP","type":"main"} 
200 OK 

```

**Comment by carlosmiei** [comment]
Hello @krychla1, Thanks for reporting it we will fix it asap
