### ISSUE TITLE
Missing import in translation from binance.js -> binance.py

### ISSUE THREAD

**Issue by ChristianCoenen** [ccxt/ccxt#17367]
### CCXT Version

3.0.37

### Description

[Commit fa5026b](https://github.com/ccxt/ccxt/commit/fa5026bc703845d4aeb1fb2901740d5d68e5e952#) changed [these lines in binance.js](https://github.com/ccxt/ccxt/commit/fa5026bc703845d4aeb1fb2901740d5d68e5e952#diff-3952aa176b11da39057127c8df19692aaf0057acdc0414916be3e1f2e5054816R7411) resulting in [this translation to binance.py](https://github.com/ccxt/ccxt/commit/fa5026bc703845d4aeb1fb2901740d5d68e5e952#diff-2aff90032c37118652e9734d049a0f915e110af83751d012c42ee3a64bb96065R8).

As can be seen, the `rsa` import is missing. This leads to the following error:
```shell
NameError: name 'rsa' is not defined
```

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @ChristianCoenen,
Thanks for letting us know, I will take a look soon!
