### ISSUE TITLE
Let CCXT to use NTP.org servers instead localtime

### ISSUE THREAD

**Issue by daniel-lucio** [ccxt/ccxt#17386]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

Coinbase (and maybe other exchanges) require a signature that comes from the local time of the client. Coinbase will invalidate all signatures that are not within a 30secs time offset (if I am not mistaken).

This becomes a problem on VPSes as sometimes the systems create an offset. When the offset is longer, Coinbase will reject all the requests.

### Describe the solution you'd like

Since many of us do not have access to physical nodes, it would be very useful if CCXT could use an NTP library such as https://packagist.org/packages/bt51/ntp to pull the time.

**Comment by carlosmiei** [comment]
Hello @daniel-lucio,
Thanks for your suggestion. For some exchanges, we have a `loadTimeDifference` that compares your clock with the server's clock and subtracts that difference upon signing the request, usually, that helps prevent these timestamp issues.  We will try to add it to Coinbase as soon as possible.

**Comment by frosty00** [comment]
ntp servers aren't really the best solution since it's better to sync the time to the exchange. most exchanges that rely on time syncing provide a way to load the time from their API
