### ISSUE TITLE
in biance how can i get futures kline(not spot) with(exchange.fetchOHLCV(symbol="BTC/USDT", timeframe="3m",limit=2)),?

### ISSUE THREAD

**Issue by longeila** [ccxt/ccxt#17418]
### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @longeila,
I would suggest using the unified symbols to avoid ambiguities between spot and future markets, in this case you could do:

```Python
exchange.fetchOHLCV(symbol="BTC/USDT:USDT", timeframe="3m",limit=2)
```

You can read more about unified symbols here: https://docs.ccxt.com/#/README?id=symbols-and-market-ids
