### ISSUE TITLE
Kraken Futures incorrect base and symbol for usdc-usd, usdt-usd

### ISSUE THREAD

**Issue by mattcol** [ccxt/ccxt#17410]
### Programming Languages

JS

### Description

The base for the pf_usdcusd and pf_usdtusd stablecoin markets are being incorrectly set to cusd and tusd instead of usdc and usdt. This also bugs the symbol.

Caused by this code replacing the first instance of 'usd':
`const baseId = splitMarket.replace('usd', '');`

### Code

```
   {
    id: 'pf_usdcusd',
    symbol: 'CUSD/USD:USD',
    base: 'CUSD',
    quote: 'USD',
    baseId: 'cusd',
    quoteId: 'usd',
    
    ............
},
info: {
    symbol: 'pf_usdcusd',
    type: 'flexible_futures',
    
    ............
},



{
    id: 'pf_usdtusd',
    symbol: 'TUSD/USD:USD',
    base: 'TUSD',
    quote: 'USD',
    baseId: 'tusd',
    quoteId: 'usd',
        
    ............
},
info: {
    symbol: 'pf_usdtusd',
    type: 'flexible_futures',
        
    ............
},

```

**Comment by carlosmiei** [comment]
Hello @mattcol thanks for letting us know, we will patch it asap
