### ISSUE TITLE
Gate.io watch_orders and watch_my_trades all symbols bug

### ISSUE THREAD

**Issue by speedingonatram** [ccxt/ccxt#17430]
### Operating System

Windows 11

### Programming Languages

python

### CCXT Version

3.0.47

### Description

In Gate.io ccxt pro Python functions such as: watch_orders, watch_my_trades
The payload we're using for watching all symbols is 'not all', but the correct one should be '!all'

See below:
https://www.gate.io/docs/developers/futures/ws/en/#orders-api

This seems only to be an issue in Python because the TS version has the correct payload string.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @speedingonatram,
Thanks for letting us know, yeah there is a transpilation issue, but it will be fixed asap!
