### ISSUE TITLE
There is a bug in fetchOpenOrders in Phemex's COIN-M Perpetual.

### ISSUE THREAD

**Issue by bongkook** [ccxt/ccxt#17434]
### Operating System

Windows

### Programming Languages

JS

### CCXT Version

3.0.46

### Description

Hello,
There is a bug in fetchOpenOrders in Phemex's COIN-M Perpetual.
When COIN-M Perpetual's BTC/USD:USD is executed, the spot function is executed.
The privateGetOrdersActiveList function should be running, but the privateGetSpotOrders function is running.
please check.

### Code

```
phemex = ccxt.phemex({
'type': {'defaultType': 'swap'},
'enableRateLimit': True,
'apiKey': API_KEY,
'secret': API_SECRET
})
phemex.fetchOpenOrders('BTC/USD:USD')
```

**Comment by carlosmiei** [comment]
Hello @bongkook,
Thanks for letting us know I will check it asap.
