### ISSUE TITLE
There is a bug when using the fetchTicker function in Phemex's testnet.

### ISSUE THREAD

**Issue by bongkook** [ccxt/ccxt#17437]
### Operating System

Windows

### Programming Languages

JS

### CCXT Version

3.0.48

### Description

Hello,

The error does not occur on the mainnet, but when I run the fetchTicker function on the testnet, an error occurs.
The cause seems to be that the error occurs because there is no urls['test']['v2'].
please check.

-----------------source----------------------
'urls': {
    'test': {
        'v1': 'https://testnet-api.phemex.com/v1',
        'public': 'https://testnet-api.phemex.com/exchange/public',
        'private': 'https://testnet-api.phemex.com',
    },
    'api': {
        'v1': 'https://{hostname}/v1',
        'v2': 'https://{hostname}',
        'public': 'https://{hostname}/exchange/public',
        'private': 'https://{hostname}',
    },
}

### Code

```
  phemex = ccxt.phemex({
'urls': 'test'
'type': {'defaultType': 'swap'},
'enableRateLimit': True,
'apiKey': API_KEY,
'secret': API_SECRET
})
phemex.fetchTicker('BTC/USDT:USDT')
```
-----result-----
>  TypeError: Cannot read properties of undefined (reading 'replace')
>      at phemex.implodeParams (/Users/bongkook/Develop/chromeExtensions/tvextbot-cloud/functions/node_modules/ccxt/dist/cjs/src/base/functions/misc.js:99:33)
>      at phemex.implodeHostname (/Users/bongkook/Develop/chromeExtensions/tvextbot-cloud/functions/node_modules/ccxt/dist/cjs/src/base/Exchange.js:3080:21)
>      at phemex.sign (/Users/bongkook/Develop/chromeExtensions/tvextbot-cloud/functions/node_modules/ccxt/dist/cjs/src/phemex.js:3844:20)
>      at phemex.fetch2 (/Users/bongkook/Develop/chromeExtensions/tvextbot-cloud/functions/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2440:30)
>      at async phemex.request (/Users/bongkook/Develop/chromeExtensions/tvextbot-cloud/functions/node_modules/ccxt/dist/cjs/src/base/Exchange.js:2444:16)
>      at async phemex.fetchTicker (/Users/bongkook/Develop/chromeExtensions/tvextbot-cloud/functions/node_modules/ccxt/dist/cjs/src/phemex.js:1256:26)
>      at async Phemex.fetchTicker (/Users/bongkook/Develop/chromeExtensions/tvextbot-cloud/functions/api/exchanges/phemex.js:589:16)

**Comment by carlosmiei** [comment]
Hello @bongkook, thanks for reporting it, we will take a look.
