### ISSUE TITLE
ccxt.coinbase.fetch_ticker()

### ISSUE THREAD

**Issue by ZengYuQin** [ccxt/ccxt#17447]
### Operating System

windows11

### Programming Languages

python

### CCXT Version

3.0.50

### Description

There is a problem when I use the method ccxt.coinbase.fetch_ticker():

1. The bid and ask obtained by `fetchTickerV3` are both `None`; The result is:
```python
{'symbol': 'AVAX/USDT', 'timestamp': None, 'datetime': None, 'bid': None, 'ask': None, 'last': 16.96, 'high': None, 'low': None, 'bidVolume': None, 'askVolume': None, 'vwap': None, 'open': None, 'close': 16.96, 'previousClose': None, 'change': None, 'percentage': None, 'average': None, 'baseVolume': None, 'quoteVolume': None, 'info': {'trade_id': '3213620', 'product_id': 'AVAX-USDT', 'price': '16.96', 'size': '0.45', 'time': '2023-04-03T03:51:47.395232Z', 'side': 'SELL', 'bid': '', 'ask': ''}}.
```
2. fetchTickerV2 cannot fetch the USDT currency and will report an error: 
```python
'coinbase {"errors":[{"id":"not_found","message":"Invalid currency"}]}';
```
### Code

```python
exchange = ccxt.coinbase()
exchange.options['fetchTicker'] = 'fetchTickerV2'
ticker = exchange.fetch_ticker('AVAX/USDT')  
```

**Comment by LevBeta** [comment]
Coinbase tickers uses - instead of / 
ex. BTC-USD

**Comment by samgermain** [comment]
> Coinbase tickers uses - instead of / ex. BTC-USD

Using `/` will still work.

With `fetchTickersV2` using `USDT` won't work, you need to use `USD`, V2 was a little bit different in that it just looked at the value of an asset when fetching tickers and wasn't looking at a specific market exactly

**Comment by samgermain** [comment]
I'm going to close this issue because it looks solved, feel free to reopen it if you have any more questions
