### ISSUE TITLE
ccxt.coinbase.create_order()

### ISSUE THREAD

**Issue by ZengYuQin** [ccxt/ccxt#17448]
### Operating System

windows11

### Programming Languages

python

### CCXT Version

3.0.50

### Description

```python
in create_order():
response = self.v3PrivatePostBrokerageOrders(self.extend(request, params))
success = self.safe_value(response, 'success')
if success is not True:
      raise BadRequest(self.id + ' createOrder() has failed, check your arguments and parameters')
```
question: Please also raise the response error when success is false

### Code

```python
response = self.v3PrivatePostBrokerageOrders(self.extend(request, params))
success = self.safe_value(response, 'success')
 if success is not True:
      raise BadRequest(self.id + ' createOrder() has failed, check your arguments and parameters')
```

**Comment by samgermain** [comment]
> 

Can you post an [MRE](https://stackoverflow.com/help/minimal-reproducible-example) please. It's not clear what problem your having

**Comment by samgermain** [comment]
> question: Please also raise the response error when success is false

If success is `False` then `success is not True` will be a true statement, meaning that the response error will already be raised
