### ISSUE TITLE
Can someone help?

### ISSUE THREAD

**Issue by SuchUmami** [ccxt/ccxt#17442]
### ؜

Hello,

I am a day trader and I have been trying to automate my strategy through python. Unfortunately last year I lost a lot of money from the FTX collapse and am still in recovery mode. Thanks to the python resources and community, I have learned a lot and have made a basic trading algo but I keep running into basic problems. I was wondering if anyone could help me with this project? You will have full access to my various trading strategies which is far more advanced than anything I've seen on the web and are welcome to have anything we develop together for your own personal use. I am working on this full time, so it's not like I'm looking for someone to develop it for me, I just keep running into road blocks which seem to waste a full days worth of work but turn out to be a very simple fix. This has some what disheartened me as I could have spent that time trading.

If you think you could help. Please send me a message.

**Comment by samgermain** [comment]
You'll probably have more luck on the [discord server](https://discord.gg/ccxt) 

You can also try [Freqtrade](https://discord.gg/Kv8k8qsa)
