### ISSUE TITLE
Gate.io watch_order_book related bugs

### ISSUE THREAD

**Issue by speedingonatram** [ccxt/ccxt#17443]
### Operating System

Windows 11

### Programming Languages

python

### CCXT Version

3.0.49

### Description

Currently the Python version of Gate watch_order_book doesn't run at all. (please let me know if it works for you)

I found some bugs that are contributing to it.

1. https://github.com/ccxt/ccxt/blob/3.0.49/python/ccxt/pro/gate.py#L825
Request id is stored as a string in client.subscriptions so this line insead should be:
id = self.safe_string(...)
Believe the original code errors in Python but not in TS due to how dictionary keys work differently.

2. https://github.com/ccxt/ccxt/blob/3.0.49/python/ccxt/pro/gate.py#L200
this line should instead be:
subscription = client.subscriptions[messageHash]

Would be helpful if you could run some tests on the watch functions for Gate in Python.

Thank you

### Code

```
  

```

**Comment by pcriadoperez** [comment]
Hi @speedingonatram , thanks for bringing this up. I opened a PR and implemented the changes to fix it.
