### ISSUE TITLE
WooX cancel_order is not supported with client_order_id

### ISSUE THREAD

**Issue by KevinBaudin** [ccxt/ccxt#17453]
### Operating System

Ubuntu 22.04

### Programming Languages

python

### CCXT Version

3.0.51

### Description

Hi

Quite simple, I think there is a method missing in woo cancel_order function.

What's working:
```
import ccxt

keys = {"apiKey": "xxx", "secret": "yyy", "uid": "zzz"}

exchange_params = {
    'enableRateLimit': True,
    'apiKey': keys['apiKey'],
    'secret': keys['secret'],
    'uid': keys["uid"],
    'options': {
        'defaultType': 'spot',
    },
}

exchange = getattr(ccxt, "woo")(exchange_params)

exchange.create_order("ETH/USDC", "limit", "sell", price=1900, amount=0.01, params={"clientOrderId": "123456"})
exchange.fetch_order("", "ETH/USDC", params={"clientOrderId": "123456"})
```

What's not working:

```
exchange.cancel_order("a", "ETH/USDC", params={"clientOrderId": "123456"})
```

In the code, you are using the same endpoint for client order id cancellation and for order_id.
I think that `v1PrivateDeleteClientOrder` is needed somewhere.

Thanks for the great work :)

### Code

```
  

```

**Comment by sc0Vu** [comment]
@KevinBaudin 

Thanks, it should use another endpoint for client order id.

**Comment by KevinBaudin** [comment]
Thanks :)
