### ISSUE TITLE
bybit stoploss handling inconsistent / broken

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#17456]
### Programming Languages

python

### CCXT Version

3.0.50

### Description

Placing a bybit futures stoploss order is a bit of a challange at the moment.

Placing the order with `stopPrice` fails with wrong direction.
Placing the order with stopLossPrice works - but the response doesn't contain this field - making usage of this quite odd an non-unified.

As it's important with bybit - my account is NOT unified - and the create-order requests therefore go through the v3 api.

### Code

``` python
import ccxt
exchange = ccxt.bybit({'apiKey': '<yourApiKey>', 'secret': '<yoursecret>', 'options': {'defaultType': 'swap'}})
params = {
    'stopPrice': 1600,

}
o = exchange.create_order(pair, 'limit', 'sell', amount=0.01, price=1600, params=params)
```

Fails with 
```
BadRequest: bybit {"retCode":10001,"retMsg":"expect Rising, but trigger_price[16010000] \u003c= current[17985500]??1","result":{},"retExtInfo":{},"time":1680544529422}
```

Now from past experience, i know that using stopLossPrice is an alternative if one doesn't work.

``` python
import ccxt
exchange = ccxt.bybit({'apiKey': '<yourApiKey>', 'secret': '<yoursecret>', 'options': {'defaultType': 'swap'}})
params = {
    'stopLossPrice': 1600,

}
o = exchange.create_order(pair, 'limit', 'sell', amount=0.01, price=1600, params=params)
print(o)

print(exchange.fetch_order(o['id'], pair))

```

This works - and the response is Okish - However - i'd expect stopLossPrice in the response - but stopPrice is used (which is wrong).

```
{'info': {'orderId': '44a665de-1a3e-4573-8cf8-dc403725147f',
  'orderLinkId': ''},
 'id': '44a665de-1a3e-4573-8cf8-dc403725147f',
 'clientOrderId': None,
 'timestamp': None,
 'datetime': None,
 'lastTradeTimestamp': None,
 'symbol': None,
 'type': None,
 'timeInForce': None,
 'postOnly': None,
 'reduceOnly': None,
 'side': None,
 'price': None,
 'stopPrice': None,
 'triggerPrice': None,
 'amount': None,
 'cost': None,
 'average': None,
 'filled': None,
 'remaining': None,
 'status': None,
 'fee': None,
 'trades': [],
 'fees': []}

// Fetch_order reslt
{'info': {'orderId': '44a665de-1a3e-4573-8cf8-dc403725147f',
  'orderLinkId': '',
  'blockTradeId': '',
  'symbol': 'ETHUSDT',
  'price': '1601.00',
  'qty': '0.01',
  'side': 'Sell',
  'isLeverage': '',
  'positionIdx': '0',
  'orderStatus': 'Untriggered',
  'cancelType': 'UNKNOWN',
  'rejectReason': 'EC_NoError',
  'avgPrice': '0',
  'leavesQty': '0.01',
  'leavesValue': '16.01',
  'cumExecQty': '0.00',
  'cumExecValue': '0',
  'cumExecFee': '0',
  'timeInForce': 'GTC',
  'orderType': 'Limit',
  'stopOrderType': 'Stop',
  'orderIv': '',
  'triggerPrice': '1601.00',
  'takeProfit': '0.00',
  'stopLoss': '0.00',
  'tpTriggerBy': 'UNKNOWN',
  'slTriggerBy': 'UNKNOWN',
  'triggerDirection': '2',
  'triggerBy': 'LastPrice',
  'lastPriceOnCreated': '0.00',
  'reduceOnly': True,
  'closeOnTrigger': False,
  'createdTime': '1680544580692',
  'updatedTime': '1680544580692'},
 'id': '44a665de-1a3e-4573-8cf8-dc403725147f',
 'clientOrderId': None,
 'timestamp': 1680544580692,
 'datetime': '2023-04-03T17:56:20.692Z',
 'lastTradeTimestamp': 1680544580692,
 'symbol': 'ETH/USDT:USDT',
 'type': 'limit',
 'timeInForce': 'GTC',
 'postOnly': False,
 'reduceOnly': True,
 'side': 'sell',
 'price': 1601.0,
 'stopPrice': 1601.0,
 'triggerPrice': 1601.0,
 'amount': 0.01,
 'cost': 0.0,
 'average': None,
 'filled': 0.0,
 'remaining': 0.01,
 'status': 'open',
 'fee': {'cost': 0.0, 'currency': 'USDT'},
 'trades': [],
 'fees': [{'cost': 0.0, 'currency': 'USDT'}]}

```

**edit**
seems to have been introduced in #17262 - which dropped the fallback to `triggerPrice` from the assignment of `stopLossTriggerPrice`.

**Comment by sc0Vu** [comment]
Hi @xmatthias 

For the stop loss order, would you like to paste verbose log for using `stopLoss` (first one)? I found a small bug, but the logic worked for me.

**Comment by xmatthias** [comment]
@sc0Vu sure, absolutely no problem.

When testing this - make sure to use a subaccount with unification disabled (assuming the account is unified).
mine is not - and i know from others that subaccounts start non-unified as well.


``` python
import ccxt
exchange = ccxt.bybit({'apiKey': '<yourApiKey>', 'secret': '<yoursecret>', 'options': {'defaultType': 'swap'}})
params = {
    'stopLoss': 1601
}
pair = 'ETH/USDT:USDT;
o = exchange.create_order(pair, 'limit', 'sell', amount=0.01, price=1601, params=params)
```

```
fetch Request: bybit GET https://api.bybit.com/user/v3/private/query-api?api_key=6RvMxqP1fTCyqX7voi&recv_window=5000&timestamp=1680581980714&sign=3cf3c943d0a789cd4a663c8d47edd6a274fcdd99b75a029c83812d01122a68bd RequestHeaders: {'User-Agent': 'python-requests[/2.28.2](https://file+.vscode-resource.vscode-cdn.net/2.28.2)', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*[/](https://file+.vscode-resource.vscode-cdn.net/)*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bybit GET https://api.bybit.com/user/v3/private/query-api?api_key=6RvMxqP1fTCyqX7voi&recv_window=5000&timestamp=1680581980714&sign=3cf3c943d0a789cd4a663c8d47edd6a274fcdd99b75a029c83812d01122a68bd 200 ResponseHeaders: {'Content-Type': 'application[/json](https://file+.vscode-resource.vscode-cdn.net/json); charset=utf-8', 'Content-Length': '662', 'Connection': 'keep-alive', 'Date': 'Tue, 04 Apr 2023 04:19:42 GMT', 'X-Bapi-Limit': '10', 'X-Bapi-Limit-Status': '9', 'X-Bapi-Limit-Reset-Timestamp': '1680581982091', 'Ret_code': '0', 'Traceid': '7e6a2cc51a91b16e7597712990c565a8', 'Timenow': '1680581982118', 'Server': 'Openresty', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 e37b7824685046c107e13d08c43993fc.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'FRA56-P4', 'X-Amz-Cf-Id': 'yNOfIglrQcfqY2OhyZwSjf-aCXoQXMJs7EHghzOnHCC-GHaTj5hipw=='} ResponseBody: {"retCode":0,"retMsg":"","result":{"id":"15075334","note":"FT_local","apiKey":"6RvMxqP1fTCyqX7voi","readOnly":0,"secret":"","permissions":{"ContractTrade":["Order","Position"],"Spot":["SpotTrade"],"Wallet":["AccountTransfer","SubMemberTransfer"],"Options":[],"Derivatives":["DerivativesTrade"],"CopyTrading":[],"BlockTrade":[],"Exchange":[],"NFT":[]},"ips":["185.187.221.153"],"type":1,"deadlineDay":-2,"expiredAt":"1970-01-01T00:00:00Z","createdAt":"2022-12-05T19:24:07Z","unified":0,"uta":0,"userID":44846619,"inviterID":799875,"vipLevel":"No VIP","mktMakerLevel":"0","affiliateID":35953,"rsaPublicKey":"","isMaster":true},"retExtInfo":{},"time":1680581982118}

fetch Request: bybit POST https://api.bybit.com/contract/v3/private/order/create RequestHeaders: {'Content-Type': 'application[/json](https://file+.vscode-resource.vscode-cdn.net/json)', 'X-BAPI-API-KEY': '6RvMxqP1fTCyqX7voi', 'X-BAPI-TIMESTAMP': '1680581981234', 'X-BAPI-RECV-WINDOW': '5000', 'X-BAPI-SIGN-TYPE': '2', 'X-BAPI-SIGN': '93a1946445e94b7e6e7b0ccd1b2cff542a87b10505248066c653ee8f2e3f5d48', 'Referer': 'CCXT', 'User-Agent': 'python-requests[/2.28.2](https://file+.vscode-resource.vscode-cdn.net/2.28.2)', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*[/](https://file+.vscode-resource.vscode-cdn.net/)*', 'Connection': 'keep-alive'} RequestBody: {"symbol":"ETHUSDT","side":"Sell","orderType":"Limit","timeInForce":"GoodTillCancel","qty":"0.01","price":"1601","stopLoss":1601}

fetch Response: bybit POST https://api.bybit.com/contract/v3/private/order/create 200 ResponseHeaders: {'Content-Type': 'application[/json](https://file+.vscode-resource.vscode-cdn.net/json); charset=utf-8', 'Content-Length': '102', 'Connection': 'keep-alive', 'Date': 'Tue, 04 Apr 2023 04:19:42 GMT', 'Ret_code': '10001', 'Cache-Control': 'no-store', 'Traceid': '790ada86becfc135238f1e444275d448', 'Timenow': '1680581982611', 'Server': 'Openresty', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 e37b7824685046c107e13d08c43993fc.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'FRA56-P4', 'X-Amz-Cf-Id': 'ODOQOqaOxtxHGdyODOhDv2VBXVUrTSd3KWxla21gDUa4yfS-O0PVdg=='} ResponseBody: {"retCode":10001,"retMsg":"Request parameter error.","result":{},"retExtInfo":{},"time":1680581982611}
```

**Comment by xmatthias** [comment]
@sc0Vu to be clear - i think there's 2 separate areas of improvement here.

for one - the response parsing (`fetch_order()`), which should include `stopLossPrice` (i can post an order with that - but it's not part of the response)

more importantly, the definition of `isStopLossTriggerOrder` - which is (since recently) ignoring  `stopPrice` (as well as `triggerPrice`) - and is therefore incorrectly setting `ascending` - which leads to `triggerDirection` being wrong.

Relevant code parts:

https://github.com/ccxt/ccxt/blob/596694ae26754ac6ff9e4f83bb5e1b0541bfba76/ts/src/bybit.ts#L3806-L3817

**Comment by sc0Vu** [comment]
Hi @xmatthias 

Looks like the price was number instead of string. I've submit a PR for this (https://github.com/ccxt/ccxt/pull/17461)

**Comment by xmatthias** [comment]
@sc0Vu  i don't really see how the PR will change the type of the value sent (the PR only contains a change to which values will be omitted).

Neither do i see how it'll fix the response parsing - where `stopLossPrice` is missing from the response, therefore that PR will definitely not completely close this issue (not in it's current state, anyway).

**Comment by xmatthias** [comment]
For a slightly more complex (futures) sample (short, with reduceOnly=True):


```
fetch Request: bybit POST https://api.bybit.com/contract/v3/private/order/create RequestHeaders: {'Content-Type': 'application/json', 'X-BAPI-API-KEY': 'xxx', 'X-BAPI-TIMESTAMP': '1680629363025', 'X-BAPI-RECV-WINDOW': '5000', 'X-BAPI-SIGN-TYPE': '2', 'X-BAPI-SIGN': 'a333b5e07b13cd766e0012591102e1bba0dbf823c0d07d30c3e30f0f9a938b11', 'Referer': 'CCXT', 'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"symbol":"ETHUSDT","side":"Buy","orderType":"Limit","timeInForce":"GoodTillCancel","qty":"0.01","price":"1962.81","triggerDirection":2,"triggerPrice":"1960.84","reduceOnly":"true","triggerBy":"MarkPrice"}

fetch Response: bybit POST https://api.bybit.com/contract/v3/private/order/create 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '151', 'Connection': 'keep-alive', 'Date': 'Tue, 04 Apr 2023 17:29:23 GMT', 'X-Bapi-Limit': '10', 'X-Bapi-Limit-Status': '9', 'X-Bapi-Limit-Reset-Timestamp': '1680629363130', 'Ret_code': '10001', 'Cache-Control': 'no-store', 'Traceid': '37584ca2e45275c8742ac3e162710b84', 'Timenow': '1680629363132', 'Server': 'Openresty', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 ade2b5e2170ccd4f394b741b27bb0eec.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'FRA56-P4', 'X-Amz-Cf-Id': 'cU7FTZ18699rOUq3PqS9DxYQa1fnm0fa7xDEcbHkGi7xDI_e0isYHg=='} ResponseBody: {"retCode":10001,"retMsg":"expect Failling, but trigger_price[19608400] \u003e= current[18674900]??2","result":{},"retExtInfo":{},"time":1680629363132}
```

**Comment by sc0Vu** [comment]
Hi @xmatthias 

The `stopLoss` and `takeProfit` was exchange specific `sl/tp` value, and they are tied to some position. When createOrder with these value, exchange would check price value (that's why you got BadRequest: bybit {"retCode":10001,"retMsg":"sl:16010000 set for Sell position should greater base_price:18577300??LastPrice","result":{},"retExtInfo":{},"time":1680624978500}).

For the triggerDirection issue, I'm working on it. Let me know if you have any other issues.

**Comment by xmatthias** [comment]
Hi @sc0Vu 

If i'm setting `stopLossPrice` - then I'd expect this value to be part of the response for `fetch_order()`, too - which is not the case (see 2nd part of the issue). that contains only `stopLoss` - which makes this unaligned / wrong (I need to place with `stopLossPrice` - but the response won't contain this key).
If you don't want to address this as part of this issue, I'm more than happy to reopen that as a separate issue (i'll copy/paste most of this issue related to this) (it's partially independent to this issue - but still an issue).

---

Apart from that - i disagree with most of what you say.
when using `stopLoss` (instead of `stopLossPrice`) - then the value set for `ascending` is wrong - and with that, the triggerDirection sent.

https://github.com/ccxt/ccxt/blob/a94148e988fdc723042619945adf68b19a7d04f8/ts/src/bybit.ts#L3816

`stopPrice` is not (no longer) considered for the value of `stopLossTriggerPrice` .

This used to be working up until https://github.com/ccxt/ccxt/pull/17262/files - which removed the fallback
![image](https://user-images.githubusercontent.com/5024695/230321239-3ed37bcb-1209-49fb-b9b3-4211eeaba9fc.png)
- and therefore broke behavior of this.

> For the triggerDirection issue, when use the stopPrice with buy order, I think the expected behavior might be that create order when price fall to the triggerPrice (buy the dip)

No, this is wrong.
in the above example (https://github.com/xmatthias), i used stopPrice to (attempt) to exit a **short** position (Exit if my position value drops by more than X%, and i therefore lost X%). Therefore the stop must be ABOVE current price - and the direction will be buy, with reduceOnly  - which will result in an exit short.

this order IS tied to an existing position (i'm trying to exit an existing short)- but placement fails, and is therefore clearly a bug based on your description above.

**Comment by sc0Vu** [comment]
Hi @xmatthias 

Sorry for that, I kind of misunderstanding of this issue. For `stopLossPrice` not showing in the order struct, that might be a good feature if we can tell this kind of order with algo order values (but I think it's ccxt specific order, see: https://github.com/ccxt/ccxt/issues/12044).

For the `triggerDirection` issue, I got the same error when test my "un unified" account. I think that default `stopLossTriggerPrice` made the first `triggerPrice` condition useless (ascending always be `!isBuy`).

**Comment by xmatthias** [comment]
> For the `triggerDirection` issue, I got the same error when test my non unified account. I think that default `stopLossTriggerPrice` made the first `triggerPrice` condition useless (ascending always be `!isBuy`).

That's what i mean - it's a bug making everything that uses `stopPrice` useless.

---

I'm not sure i understand your point about `stopLossPrice` - an order we place through ccxt is never "tied to a position" (as you mentioned above) - unless we use `params` (custom/different by exchange).
so using stopLossPrice (for both placing the order, as well as fetching) would be correct - but the fetching part is missing for bybit (`stopLossPrice` is not parsed correctly).

**Comment by xmatthias** [comment]
@sc0Vu @carlosmiei 
as we now agree on having  abug on `stopPrice` - any chance to have this fixed anytime soon please?

**Comment by carlosmiei** [comment]
> 

@xmatthias I will try to take a look asap, just to recap, providing `stopPrice` using a non-unified account fails, right?

**Comment by xmatthias** [comment]
that's correct.

the problem is that `stopLossTriggerPrice` is not set in this case - which makes `ascending` wrong in turn - resulting in `stopLossTriggerPrice` being always wrong.

**Comment by carlosmiei** [comment]
@xmatthias Can you test it again using the latest version pls?

**Comment by xmatthias** [comment]
Hi @carlosmiei,

Stoploss orders do work again now :+1: 
Thanks a lot for your help!
