### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by naward-cs** [ccxt/ccxt#17458]
### Operating System

linux

### Programming Languages

JS

### CCXT Version

3.0.51

### Description

assets by status 930 bytes [cached] 1 asset
./ts/ccxt.ts 19 KiB [built] [1 error]

ERROR in ./ts/ccxt.ts 45:10
Module parse failed: Unexpected token (45:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| const version = '3.0.51';
| 
> (Exchange as any).ccxtVersion = version
| 
| //-----------------------------------------------------------------------------

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @naward-cs, can you elaborate a bit more? How can we reproduce this issue locally?

**Comment by naward-cs** [comment]
@carlosmiei

I did npm install > npm build and got the error

**Comment by carlosmiei** [comment]
> @carlosmiei
> 
> I did npm install > npm build and got the error

@naward-cs Can you try to remove `nodeModules` and do `npm i` again?

**Comment by naward-cs** [comment]
I found the issue. I was trying build within a node_modules of a project that I used npm i ccxt from my git repo vice using npm link to a local clean dir
