### ISSUE TITLE
Gate.io fetchOHLCV does not work properly

### ISSUE THREAD

**Issue by bit2me-dev** [ccxt/ccxt#17464]
### Operating System

Ubuntu

### Programming Languages

JS

### CCXT Version

3.0.10

### Description

CCXT is able to fetch OHLCV information sending the parameters **symbol**, **timeframe** and **since**.

For Gate.io, if you don't send the parameter **until** then CCXT calculates it in this way:

`const toTimestamp = this.sum(request['from'], limit * duration - 1);`

However, it not always work fine. Depending on the **since** parameter it fails.

For example, if I run this command:

`
const ohlc = await gate.fetchOHLCV('DAO/USDT', '1h', 1667237607000);
`

Then I get this error:

`
BadRequest: gateio {"label":"INVALID_PARAM_VALUE","message":"Candlestick range too broad. Maximum 1000 data points are allowed per request"}
`

CCXT is calculating the *to* parameter based on the limit (1000) and based on the **from** parameter, but it is calculating it wrong and Gati.io fails.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @bit2me-dev,
Thanks for letting us know, will be fixed very soon!
