### ISSUE TITLE
ccxt.coinbase.fetch_ticker('BTC-USD')

### ISSUE THREAD

**Issue by ZengYuQin** [ccxt/ccxt#17462]
### Operating System

windows11

### Programming Languages

python

### CCXT Version

3.0.51

### Description

When I use the interesting method of ccxt.coinbase.fetch_ticker('BTC-USD'), the result I get is None for both ask and bid. I have no other way to get these two correct values.
I can get the value of ask and bid by using ccxt.coinbasepro.fetch_ticker('BTC-USD'), can I only use ccxt.coinbasepro? Can ccxt.coinbase also support returning bid and ask values?
Or is there any other way for ccxt.coinbase to return the ask and bid of the symbol I want?
Thank you for your contribution.

### Code

```
ccxt.coinbase.fetch_ticker('BTC-USD')
ccxt.coinbasepro.fetch_ticker('BTC-USD')
```

**Comment by Dan-krm** [comment]
@ZengYuQin I opened a pull request that updates coinbase to include the bid and ask prices in fetchTicker
