### ISSUE TITLE
Fetch oldest candles on BitGet, no response

### ISSUE THREAD

**Issue by dawadam** [ccxt/ccxt#17479]
### Operating System

linux

### Programming Languages

JS

### CCXT Version

3.0.52

### Description

Hi @carlosmiei,

I'm trying to retrieve the oldest candles for a symbol on BitGet.
I use a large time frame to estimate the first market time.
But no candle is returned.
See example.
Work fine on Binance and ByBit.

### Code

```
      const exchange = new ccxt['bitget']()

    // big time frame
    let ohlcvRawList = await exchange.fetchOHLCV('ETH/USDT:USDT', '1w')

    let firstMonthCandle = ohlcvRawList[0]
    const timeStart = firstMonthCandle[0]

    const timeStartTenMonthAfter = timeStart + 60 * 60 * 24 * 30 * 10 * 1000

    console.log('first month candle', firstMonthCandle)
    ohlcvRawList = await exchange.fetchOHLCV('ETH/USDT:USDT', '1h', timeStart)
    console.log(ohlcvRawList.length) // 0

    // try 10 months after
    ohlcvRawList = await exchange.fetchOHLCV('ETH/USDT:USDT', '1h', timeStartTenMonthAfter)
    console.log(ohlcvRawList.length) // 0
```

**Comment by sc0Vu** [comment]
Hi @dawadam 

After test, it seems you can fetch data within 30 days for 1h (the documentations said for `1m` candles)

**Comment by dawadam** [comment]
Ok, not a bug, juste exchange sucks.
