### ISSUE TITLE
CCXT unable to place trigger close order

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#17487]
### Operating System

Windows 10

### CCXT Version

3.0.54

### Description

I am unable to place trigger orders after updating to the newest version. 

### Code

```
  
import ccxt
        
private = "" 
public = ""

ticker = "XRP/USDT:USDT"
side = 'sell'
quantity = 30
price = 0.5
mode = 1

client = ccxt.bybit({'apiKey': public, 'secret': private})



response = client.create_order(symbol=ticker, type="market", side=side,
                               amount=quantity, price=None,
                               params={'stopPrice': price,
                                       'close_on_trigger': True,
                                       'position_idx': mode})
```
BadRequest: bybit {"retCode":10001,"retMsg":"expect Rising, but trigger_price[50000000] \u003c= current[51340000]??1","result":{},"retExtInfo":{},"time":1680697304648}

**Comment by sc0Vu** [comment]
Hi @Tomas-MP 

When use `stopPrice`, the direction was set to `rise` if side is `sell`. If you want to hedge the long position, you can set `stopLossPrice` or set `triggerDirection` to `2` (`fall` direction).
