### ISSUE TITLE
ImportError: cannot import name 'Literal' from 'typing'

### ISSUE THREAD

**Issue by zacra** [ccxt/ccxt#17498]
### Operating System

amazon linux 2

### Programming Languages

python

### CCXT Version

Since version 3.0.46

### Description

import ccxt
In the syntax, the following error occurs.

    import ccxt
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/__init__.py", line 29, in <module>
    from ccxt.base.exchange import Exchange                     # noqa: F401
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/__init__.py", line 24, in <module>
    from ccxt.base import exchange
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 31, in <module>
    from ccxt.base.types import Balance, IndexType, OrderSide, OrderType
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ccxt/base/types.py", line 2, in <module>
    from typing import Union, Literal
ImportError: cannot import name 'Literal' from 'typing' (/usr/lib64/python3.7/typing.py)

In versions prior to 3.0.45 it works fine.
It seems that the ccxt/base/types.py file needs to be modified.
Please check!

### Code

```
import ccxt
```

I think the types.py file can be modified as follows.

import sys
from typing import Union

try:
    from typing import Literal
except ImportError:
    from typing_extensions import Literal
    
if sys.version_info.minor > 7:
    from typing import TypedDict
else:
    TypedDict = dict

OrderSide = Literal['buy', 'sell']
OrderType = Literal['limit', 'market']

class Balance(TypedDict):
    free: Union[None, str, float]
    used: Union[None, str, float]
    total: Union[None, str, float]

IndexType = Union[str, int]

**Comment by carlosmiei** [comment]
Hello @frosty00 thanks, for letting us know, we will be fixing it soon!
