### ISSUE TITLE
mexc spot - markets somehow wrong (listing BTC/USDT as inactive ...)

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#17492]
### Operating System

python

### Programming Languages

python

### CCXT Version

3.0.53

### Description

mexc markets report for example BTC/USDT as inactive - while it's active for spot trading according to the endpoint used (https://api.mexc.com/api/v3/exchangeInfo) - as well as based on the exchange webpage.

```
...

{"symbol":"BTCUSDT","status":"ENABLED","baseAsset":"BTC","baseAssetPrecision":6,"quoteAsset":"USDT","quotePrecision":2,"quoteAssetPrecision":2,"baseCommissionPrecision":6,"quoteCommissionPrecision":2,"orderTypes":["LIMIT","MARKET","LIMIT_MAKER"],"quoteOrderQtyMarketAllowed":false,"isSpotTradingAllowed":false,"isMarginTradingAllowed":false,"quoteAmountPrecision":"5.000000000000000000","baseSizePrecision":"0.000001","permissions":["SPOT","MARGIN"],"filters":[],"maxQuoteAmount":"5000000.000000000000000000","makerCommission":"0","takerCommission":"0","quoteAmountPrecisionMarket":"5.000000000000000000","maxQuoteAmountMarket":"500000.000000000000000000"},

...
```

### Code

  

``` python
import ccxt
exchange = ccxt.mexc()

exchange.verbose = True
lm = exchange.load_markets()
print(lm['BTC/USDT'])
```

```
{'id': 'BTCUSDT',
 'symbol': 'BTC/USDT',
 'base': 'BTC',
 'quote': 'USDT',
 'baseId': 'BTC',
 'quoteId': 'USDT',
 'active': False,   <-- Inactive
 'type': 'spot',
 'linear': None,
 'inverse': None,
 'spot': True,
 'swap': False,
 'future': False,
 'option': False,
 'margin': False,
 'contract': False,
 'contractSize': None,
 'expiry': None,
 'expiryDatetime': None,
 'optionType': None,
 'strike': None,
 'settle': None,
 'settleId': None,
 'precision': {'amount': 1e-06, 'price': 0.01},
 'limits': {'amount': {'min': 1e-06, 'max': None},
  'price': {'min': None, 'max': None},
  'cost': {'min': 5.0, 'max': 5000000.0},
  'leverage': {'min': None, 'max': None}},
 'info': {'symbol': 'BTCUSDT',
  'status': 'ENABLED',
  'baseAsset': 'BTC',
  'baseAssetPrecision': '6',
  'quoteAsset': 'USDT',
  'quotePrecision': '2',
  'quoteAssetPrecision': '2',
  'baseCommissionPrecision': '6',
  'quoteCommissionPrecision': '2',
  'orderTypes': ['LIMIT', 'MARKET', 'LIMIT_MAKER'],
  'quoteOrderQtyMarketAllowed': False,
  'isSpotTradingAllowed': False,
  'isMarginTradingAllowed': False,
  'quoteAmountPrecision': '5.000000000000000000',
  'baseSizePrecision': '0.000001',
  'permissions': ['SPOT', 'MARGIN'],
  'filters': [],
  'maxQuoteAmount': '5000000.000000000000000000',
  'makerCommission': '0',
  'takerCommission': '0',
  'quoteAmountPrecisionMarket': '5.000000000000000000',
  'maxQuoteAmountMarket': '500000.000000000000000000'},
 'percentage': True,
 'tierBased': False,
 'maker': 0.0,
 'taker': 0.0}
```

a suspected offender might be the check for `isSpotTradingAllowed` - which is false for BTC (from the exchange side) - which is strange, as i can clearly trade spot on btc ... 

https://github.com/xmatthias/ccxt/blob/1fa7fafc1cd8622ea8bbd6ba966e9579c47692f4/ts/src/mexc.ts#L857

**Comment by carlosmiei** [comment]
@xmatthias You're right, we're relying on the `isSpotTradingAllowed` value but clearly something is off, I will try to reach out to Mexc to clarify this issue.

**Comment by xmatthias** [comment]
Seems to be a generic mexc problem.
trading on BTC/USDT through the api is not working (`BadSymbol: mexc {"code":10007,"msg":"symbol not support api"}`).

What i found is [this news link](https://support.mexc.com/hc/en-001/articles/15149585234969-MEXC-Upgrade-and-Maintenance-of-API-for-BTC-USDT-FTM-USDT-OP-USDT-DOGE-USDT) - and it seems like it didn't recover yet (no further anouncement of availability).

As such - i conclude that ccxt is showing the correct info - it's mexc seemingly unable (or unwilling) to bring trading through the API of some major pairs (ETH/USDT is also inactive).

**Comment by xmatthias** [comment]
Due to the above findings, i'm gonna close this - it's not a bug in ccxt, but the api is really not providing the highest volume pairs.
