### ISSUE TITLE
How to check supported deposit/withdraw networks for given currency?

### ISSUE THREAD

**Issue by RoscoeTheDog** [ccxt/ccxt#17496]
I couldn't get the answer from chatGPT, sorry :(

I'm looking for a way to validate whether a network supports a given currency before attempting to process a withdrawal or deposit. If a user wants to use a specific network then I'd like to validate it first before setting it in a given configuration.

The exchange in question is Kucoin / KucoinFutures, but if there was a unified way to do it that would be preferred.

**Comment by carlosmiei** [comment]
Hello @RoscoeTheDog, 
If avalaible, you can use the `fetchDepositWithdrawFee` . Alternatively, you can inspect the `exchange.currencies` dictionary.

**Comment by ttodua** [comment]
`exchange.currencies['networks']` is what you need. however, it is being unified across exchanges. I suggest everyone to post further comments in this thread: https://github.com/ccxt/ccxt/issues/12795
