### ISSUE TITLE
Kucoin UNAUTH. Login required on Win7. On Ubuntu all is fine

### ISSUE THREAD

**Issue by frg-x** [ccxt/ccxt#1750]
When I trying to launch my trading_script.py on Win7 have a such errors below, but on Ubuntu 16.04 all is fine.
Api key&secret on both OSs the same

`requests.exceptions.HTTPError: 401 Client Error:  for url:  https://api.kucoin.com/v1/order/active-map?symbol=BCH-BTC`

` {"code":"UNAUTH","msg":"Login required","success":false,"timestamp":1517637518626}`

`ccxt.base.errors.InvalidNonce: kucoin {"code":"UNAUTH","msg":"Invalid nonce","success":false,"timestamp":1517637279984}`

- OS: Win 7
- Programming Language version: Python 3.6.4
- CCXT version: 1.10.981 or any latest
- Exchange: kucoin

**Comment by bargulg** [comment]
Same here. Works on Fedora, but on Win10 I get the same error frg-x described.

**Comment by kroitor** [comment]
Have you guys checked your timezones and nonce values?

The system clock on Windows should be synchronized UTC (non-DST). If you're testing a Linux, then testing the same key with Windows having a different time setting – this will screw your nonce number.

- https://github.com/ccxt/ccxt/wiki/Manual#authentication
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Try **a fresh unused new key** with your windows systems, but make sure to synchronize your system clocks on windows systems, enabling the internet time synch checkbox **is not enough**. You should make it synchronize the time every 10 minutes via the Registry... More about it here: #850

Let us know if this does not help. Thx!
