### ISSUE TITLE
ExchangeError: mexc nonce is behind cache after 3 tries. when watch many order books

### ISSUE THREAD

**Issue by lovepocky** [ccxt/ccxt#17511]
### Operating System

ubuntu 20.04

### Programming Languages

python

### CCXT Version

3.0.56

### Description

test code:

```python
import ccxt.pro as ccxt
import asyncio as aio

async def start():
    mexc = ccxt.mexc()
    # mexc.verbose = True
    await mexc.load_markets()
    print("start watches")

    await mexc.watch_order_book("ETH/USDT")
    await mexc.watch_order_book("BTC/USDT")
    await mexc.watch_order_book("RDNT/USDT")
    await mexc.watch_order_book("DOT/USDT")
    await mexc.watch_order_book("OG/USDT")

    while True:
        await aio.sleep(0.1)


loop = aio.get_event_loop()
loop.run_until_complete(start())

```

output: (same in CPython3.8 and pypy3.8)
```bash
start watches                                                            
  File "./pypy38/test/test_mexc.py", line 11, in start                       
    await mexc.watch_order_book("BTC/USDT")                              
  File "/home/lovepocky/Sync/main/studio/trade-strategies/.venv/lib/python3.8/site-packages/ccxt/pro/mexc.py", line 350, in watch_order_book       
    orderbook = await self.watch_spot_public(channel, messageHash, params)                                                                         
  File "/home/lovepocky/Sync/main/studio/trade-strategies/.venv/lib/python3.8/site-packages/ccxt/pro/mexc.py", line 155, in watch_spot_public      
    return await self.watch(url, messageHash, self.extend(request, params), channel)                                                               
ccxt.base.errors.ExchangeError: mexc nonce is behind cache after 3 tries.
```

### Code

```
  

```

**Comment by pcriadoperez** [comment]
Hi @lovepocky , I was not able to reproduce the error. Are you receiving it consistently?

**Comment by lovepocky** [comment]
> Hi @lovepocky , I was not able to reproduce the error. Are you receiving it consistently?

yes，every time

**Comment by pcriadoperez** [comment]
Can you try maybe increasing the snapshot delay and the retries in the options?

```python
this.options = {
    'watchOrderBook': {
        'snapshotDelay': 50,
         'maxRetries': 5,
    },
}
```

**Comment by lovepocky** [comment]
> Can you try maybe increasing the snapshot delay and the retries in the options?
> 
> ```python
> this.options = {
>     'watchOrderBook': {
>         'snapshotDelay': 50,
>          'maxRetries': 5,
>     },
> }
> ```

ok. I will try that

**Comment by lovepocky** [comment]
> Can you try maybe increasing the snapshot delay and the retries in the options?
> 
> ```python
> this.options = {
>     'watchOrderBook': {
>         'snapshotDelay': 50,
>          'maxRetries': 5,
>     },
> }
> ```

set snapshotDelay to 50, this error disappered in my test.

**Comment by pcriadoperez** [comment]
That's great to hear! I opened a PR to also increase the delay by default, just in case other users run into the same issue.
