### ISSUE TITLE
Can I help with testing as an end user of the service?

### ISSUE THREAD

**Issue by Guillerbr** [ccxt/ccxt#1751]
Sorry to open this, but I would like to help in the project, even if initially as a final client of testing deployments, please tell me how I should proceed.

Att

**Comment by kroitor** [comment]
Hi! Thank you for asking! We are not an end-user product, but a library (a utility toolkit) that is used to build many other products. If you are familiar with programming, your help with testing various new exchanges like [this one](https://github.com/ccxt/ccxt/pull/1126) on [Bit-Z](#860)  will be very much appreciated, thx! If you browse through currently open [pull requests](https://github.com/ccxt/ccxt/pulls), there's a lot of new things that are still subject to testing ;) Let us know if this does not answer your question. Thank you!
