### ISSUE TITLE
Ternary conditional operator (?:) transpiles to wrong python code

### ISSUE THREAD

**Issue by youknowone** [ccxt/ccxt#17522]
### Operating System

N/A

### Programming Languages

python

### CCXT Version

3.0.58

### Description

re-opening #17518

ts code:
```typescript
const auth = postData + '/api/' + (api === 'private' ? endpoint : api + '/' + endpoint); // 1
```
ref: https://github.com/ccxt/ccxt/blob/3.0.58/ts/src/krakenfutures.ts#L1993

generated actual: 
```python
auth = postData + '/api/' + (api == endpoint if 'private' else api + '/' + endpoint)  # 1
```
ref: https://github.com/ccxt/ccxt/blob/3.0.58/python/ccxt/async_support/krakenfutures.py#L1881

generated expected: 
```python
auth = postData + '/api/' + (endpoint if (api == 'private') else (api + '/' + endpoint))  # 1
```

The bug is introduced from #17424 52ae325f2006c8307a8a9ff346cfa9d70eb968a6 but I believe a fundamental fix is desired for the operator.

### Code

N/A

**Comment by carlosmiei** [comment]
Fixed here: https://github.com/ccxt/ccxt/issues/17518

**Comment by youknowone** [comment]
@carlosmiei do you mean transpilation mechanism is fixed or the specific python code generation is fixed?

**Comment by youknowone** [comment]
idk well about ccxt policy, but this will happen again unless at least a linter checks it.
https://github.com/ccxt/ccxt/issues/17518#issuecomment-1501760719

**Comment by carlosmiei** [comment]
@youknowone Right now, we use a regex transpiler, so we can only use ternaries if they are very simple and the only expression in that line because regexes have no context and they just match and replace. We might migrate to an ast-based transpiler (https://github.com/carlosmiei/ast-transpiler)  in the future which would completely fix this issue.
