### ISSUE TITLE
Example binance-fetch-ohlcv.py is KO

### ISSUE THREAD

**Issue by ThibautRoperch** [ccxt/ccxt#17526]
### Operating System

Windows

### Programming Languages

python

### CCXT Version

3.0.60

### Description

The example https://github.com/ccxt/ccxt/blob/master/examples/py/binance-fetch-ohlcv.py runs into an error :    
`list indices must be integers or slices, not str` 

The problem is near the line 3060 of file `site-packages/ccxt/binance.py:3060` :    
`value = dictionary.__getitem__(key)`

### Code

```
  

```

**Comment by tsiitd** [comment]
Facing the same issue. 
fetch_ohlcv works for kucoin and kraken fine. Doesnt work for binance or Binance US either

<img width="842" alt="image" src="https://user-images.githubusercontent.com/84249778/231090523-a89604e1-5df6-4c75-b5a0-4163dc413d9e.png">

<img width="826" alt="image" src="https://user-images.githubusercontent.com/84249778/231090597-d8578584-5a7e-45f0-9ac8-f4705669d66e.png">

**Comment by carlosmiei** [comment]
Hello @ThibautRoperch @tsiitd,
Thanks for letting us know, it should be fixed by now since it was fixed here: https://github.com/ccxt/ccxt/pull/17531

Can you please update to the latest version and try again?

**Comment by ThibautRoperch** [comment]
Thanks ! It works perfectly :D
`pip install ccxt==3.0.61`
