### ISSUE TITLE
Lake BTC = fetchBalance error.

### ISSUE THREAD

**Issue by wannesdemaeght** [ccxt/ccxt#1752]
Verbose output of fetchBalance:

```
fetch:
 lakebtc POST https://api.lakebtc.com/api_v2
Request:
 { 'Json-Rpc-Tonce': '1517646467959000',
  Authorization: 'Basic xxx',
  'Content-Type': 'application/json' }
 {"method":"getAccountInfo","params":"","id":xxx}

handleRestResponse:
 lakebtc POST https://api.lakebtc.com/api_v2 201 Created
Response:
 { 'Json-Rpc-Tonce': '1517646467959000',
  Authorization: 'Basic xxx',
  'Content-Type': 'application/json' }
 {"balance":{"btc":"0.2","eur":"0.0","eth":"0.0","ltc":"0.0","bch":"0.0","xrp":"0.0"},"locked":{"btc
":"0.0","eur":"0.0","eth":"0.0","ltc":"0.0","bch":"0.0","xrp":"0.0"},"profile":{"email":"xxx@gmail.com","uid":"xxx","btc_deposit_addres":"xxx"}}

(node:9508) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeErr
or: Cannot read property 'code' of undefined
```

Seems to be a problem with fetching the currencies, will try to look into this later.

**Comment by wannesdemaeght** [comment]
Update:

I was interested in LakeBTC because the prices there are much higher than other exchanges, creating great arbitrage conditions.

HOWEVER:
you can not get your fiat money out, because it's a weird ponzi type of withdrawal scheme.
Look it up.

Because of the above, I have no further interest in making the integration of ccxt and lakebtc better.

If anybody REALLY needs this, I'll have a look, but ask yourself if you absolutely want to deal with lakebtc.

@kroitor I would even go as far as to suggest complete removal of this exchange.

**Comment by kroitor** [comment]
@wannesdemaeght thanks for reporting back! Will consider their presence in the lib.
