### ISSUE TITLE
load_markets() from json 

### ISSUE THREAD

**Issue by spc789** [ccxt/ccxt#17537]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

In some situations it could be useful that the load_markets() function loads it variables from disk/cache instead of calling the exchange to populate it. Besides speeding up the retrieval of those variables by reading them - in some situations - locally from disk instead of reading them from the exchange there's also a reduction in rate limiting weight used. 

### Describe the solution you'd like

expanding the behavior of the load_markets() function to incorporate a variable which could load the market structure from a var 
So we can do something like this (pseudo code) : 

```
if file_with_vars_esists:
    exchangedata_from_file = load_file_data('somefile.txt/json/pickle')
    market = load_markets(exchangedata_from_file)
else:
    market = load_markets()
```

**Comment by carlosmiei** [comment]
Hello @spc789 I think you can do something similar right now because you can provide `markets` upon instantiating the exchange and by doing that ccxt will not fetch them again.

Example:

```Python
markets = load_markets_from_file()
exchange = ccxt.bybit({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET_KEY',
   'markets': markets
})
```

```

**Comment by spc789** [comment]
Hi Carlos, thx for your suggestion. However, I wonder if those structures also can be populate *after* the exchange was instantiated ?
Something like this : 
```
print(f"{timeNowStr()} Loading markets ...")

filename = './'+exch.upper()+'.CPKL'
if os.path.exists(filename):
    print ('DATA FILE EXISTS')
    with open(exch.upper()+'.CPKL', 'rb') as fh:
        exchange.markets = cPickle.load(fh)
        exchange.currencies = cPickle.load(fh)
        exchange.symbols = cPickle.load(fh)
        exchange.markets_by_id = cPickle.load(fh)

else:
    print ('NO DATA FILE FOUND')
    markets = exchange.load_markets()
    print ('Dumping structures in pickle')

    with open(exch.upper()+'.CPKL', 'wb') as fh:
        cPickle.dump(exchange.markets, fh)
        cPickle.dump(exchange.currencies, fh)
        cPickle.dump(exchange.symbols, fh)
        cPickle.dump(exchange.markets_by_id, fh)
```
I read the docs and it seems those are the only structures which are updated by the load_markets() function. 
Is this correct ?

**Comment by ikhwanperwira** [comment]
Is there latest news about easier interface to load the market from disk?
