### ISSUE TITLE
CCXT Throws Error when fetching expiring futures Bitget

### ISSUE THREAD

**Issue by x1i4b1x2** [ccxt/ccxt#17547]
### Programming Languages

JS

### CCXT Version

3.0.59

### Description

When fetching expiring futures from Bitget, the library throws Error.

<img width="645" alt="Screenshot 2023-04-13 at 2 34 42 PM" src="https://user-images.githubusercontent.com/100806945/231759838-5c7ca1a1-0e79-4a15-a890-9397728cd655.png">

<img width="1065" alt="Screenshot 2023-04-13 at 2 31 35 PM" src="https://user-images.githubusercontent.com/100806945/231759727-2a6fe8b3-3ba6-4139-83c5-d0b51b6f4e43.png">

Even though it is in exchange.markets.

<img width="344" alt="Screenshot 2023-04-13 at 2 35 42 PM" src="https://user-images.githubusercontent.com/100806945/231760111-d1ca40be-2e32-4648-938a-ec669c8ca88d.png">

Perpetuals are fine, the problem is just with expiring futures.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @x1i4b1x2,
Thanks for bringing this up, we will take a look asap!
