### ISSUE TITLE
is fetching greedy & fear data supported

### ISSUE THREAD

**Issue by lfzCarlosC** [ccxt/ccxt#17552]
### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @lfzCarlosC,
Can you please elaborate a bit more? We support most APIs so if you find an exchange that provides that information through the API you can use ccxt (either using the unified methods or implicit API) to get it.

**Comment by cryptoCCY** [comment]
Not sure if exchanges provide fear & greed data for crypto (e.g. like CNN for S&P or alternative.me for crypto).

This would be a nice to have or something good to know when wanting to buy or sell from overly emotional traders (e.g. buy low from irrationally fearful holders and sell high to irrationally greedy holders).

It sounds like OP is asking if ccxt provides this, which it does not if it is not published by the exchange of interest.

**Comment by samgermain** [comment]
If the exchange provides an api endpoint for the data, you can access it using the [implicit api](https://docs.ccxt.com/#/?id=implicit-api)
