### ISSUE TITLE
Please help with your syntacsis

### ISSUE THREAD

**Issue by artbred** [ccxt/ccxt#1756]
Im working on yobit and i need to make an order so my code looks like that
const rurtoethprice = async () =>{
    let ticker = await (yobit.fetchTicker ('ETH/RUR'))
    let price = ticker.info.buy
}

const buysnmyobit = async() =>{
    yobit.createOrder('ETH/RUB','market',)
}
and i dont know what to write further in create order,please help

**Comment by michnovka** [comment]
Please refer to [wiki](https://github.com/ccxt/ccxt/wiki/Manual#unified-api)

everything is explained there. The syntax for createOrder is

`createOrder (symbol, type, side, amount[, price[, params]])`

More info on the very same wiki [here](https://github.com/ccxt/ccxt/wiki/Manual#placing-orders)

**Comment by kroitor** [comment]
Thanks to @michnovka for the correct answer!

@artbred let us know if you have questions on the Manual. Thx!

**Comment by artbred** [comment]
Oh thank you, i just skipped part where type side and etc. where explained)
