### ISSUE TITLE
mexc3 php & python wrong -> force re-transpile

### ISSUE THREAD

**Issue by phlooser** [ccxt/ccxt#17577]
### ؜

Hi,
There seems to be a glitch in the build script. `mexc3.php` & `mexc3.py` are not in sync with ts/js sources anymore. Therefore my PR in mexc.ts didn't make it to mexc3.py. Can you force a re-transpile for mexc3.ts?
Alternatively, I could add a dummy change in order to force a re-transpile, which seems less nice to me...

Regards,
Philipp

**Comment by carlosmiei** [comment]
> 

@phlooser I'm sorry my bad then, I will check it asap

**Comment by carlosmiei** [comment]
@phlooser hum, I can see the changes you made correctly reflected in the other languages:

https://github.com/ccxt/ccxt/blob/master/php/async/mexc.php#L1294
https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/mexc.py#L1256

**Comment by frosty00** [comment]
@phlooser please update to the latest version of ccxt

**Comment by phlooser** [comment]
Hi @frosty00 & @carlosmiei 
No unfortunately it didn't work. Please read again my post from yesterday. It's about `mexc3.php` & `mexc3.py`, **NOT**  `mexc.php` & `mexc.py`.

Anyhow, don't worry. I simply make a dummy change to `mexc3.ts`, so it gets re-transpiled.
Just wanted to let you know, that @frosty00 's commit caused the **py/php-files** of `mexc3` to be out-of-sync with their **the js/ts-counterparts**.

**Comment by carlosmiei** [comment]
> Hi @frosty00 & @carlosmiei No unfortunately it didn't work. Please read again my post from yesterday. It's about `mexc3.php` & `mexc3.py`, **NOT** `mexc.php` & `mexc.py`.
> 
> Anyhow, don't worry. I simply make a dummy change to `mexc3.ts`, so it gets re-transpiled. Just wanted to let you know, that @frosty00 's commit caused the **py/php-files** of `mexc3` to be out-of-sync with their **the js/ts-counterparts**.

@phlooser 🤦 You're 100% correct, sorry all the confusion, will try to figure it out as soon as possible

**Comment by carlosmiei** [comment]
@phlooser I think I found the root cause, will be fixed very shortly. Thanks for bringing attention to this issue.
