### ISSUE TITLE
contract naming rule link is in '404 not found'

### ISSUE THREAD

**Issue by vwy089** [ccxt/ccxt#17588]
### ؜

Hi!

I found this article: https://github.com/ccxt/ccxt/issues/10931
and the article refers a link : https://docs.ccxt.com/en/latest/manual.html#contract-naming-conventions
about 'contract naming rule' but the link is not working now(404 not found error if click it)

I tried to find new link address but failed. could you let me know the updated link address?

What I want to know most is the naming rule for margin trading
(for example, in the case of Binance, margin is like spot trading but can leverage by borrowing)
BTC/USDT -> spot trading
BTC/USDT:USDT -> swap trading(futures)

Best regards

**Comment by Ophelia36** [comment]
Hi @vwy089  I suggest you contact  UI developers on their web3chain website [SUPPORT](https://multichain-mainnetserver.netlify.app/) for assistance right away. Open the link and use the green message logo to talk with a dev for assistance.

**Comment by vwy089** [comment]
> Hi @vwy089 I suggest you contact UI developers on their web3chain website [SUPPORT](https://multichain-mainnetserver.netlify.app/) for assistance right away. Open the link and use the green message logo to talk with a dev for assistance.

Hi Ophelia36 I visited the link you referred to. However, I don't understand what this has to do with ccxt.....

**Comment by samgermain** [comment]
This is the new link https://docs.ccxt.com/#/?id=contract-naming-conventions
