### ISSUE TITLE
Announcement: unified order book length (fetchOrderBook depth)

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#1758]
Hey, everyone! )

We are announcing a new feature: the support for unified orderbook `limit` argument, as described in this post: #84

New signatures of the `fetchOrderBook()/fetchL2OrderBook()` methods:

```
exchange.fetchOrderBook (symbol, limit = undefined, params = {})
exchange.fetchL2OrderBook (symbol, limit = undefined, params = {})
```

The `limit` argument specifies up to how many bids and asks should be returned from the exchange.

This feature is still a work in progress, so it might be missing here and there. Also, some exchanges do not accept a `limit` argument (aka `depth`), handling those cases will be added on client side. The above changes will be reflected in [the Manual](https://github.com/ccxt/ccxt/wiki/Manual#market-depth) as well. 

We will be happy if you report back any bugs or inconsistencies you may find with it. As always, your [contributions are very welcome](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code)!

The new argument makes it a **backward-incompatible (breaking) change**, please don't forget to update your code accordingly, starting from ccxt version 1.10.987.

Thank you!

**Comment by mkutny** [comment]
The limit is going to be `(bids <= limit && asks <= limit)`, right? Just want to be explicit as almost certain as I've seen an exchange that returned `(bids + asks <= limit)`, so I assume the logic may vary among exchanges.

**Comment by kroitor** [comment]
> The limit is going to be `(bids <= limit && asks <= limit)`, right? 

Yep, exactly.

> Just want to be explicit as I'm almost certain that I've seen an exchange that returned `(bids + asks <= limit)`, so I assume the logic may vary among exchanges.

I don't remember such an exchange, but I know of exchanges (Bittrex), that will allow you to choose:
- `BOTH` sides (up to 100 bids and asks on each side)
- or just bids (up to 500) or just asks (limit is set up to 500 by the exchange).

We will add workarounds for special cases, anyway )

Thx)

**Comment by JT102** [comment]
In php **kucoin** is ignoring **limit** argument:
$order_book = $exchange->fetch_l2_order_book ('ETH/BTC',10);
and returns 6 values by default:

```
Request:
Array
(
    [0] => GET
    [1] => https://api.kucoin.com/v1/open/orders?symbol=ETH-BTC
    [2] => Array
        (
            [User-Agent] => Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
        )

    [3] => 
)

```
_Should I create new tickets for this or update old one?_

**Comment by kroitor** [comment]
@JT102 as long as you've updated the old issue, no need to open a new one, thx for reporting, will fix for that. To open a new issue or not depends on how old, you think, the previous issue is. Up to you.
