### ISSUE TITLE
All markets for binanceus have the 'future' property set to true, yet Binance.US doesn't offer any futures markets.

### ISSUE THREAD

**Issue by enderwiggum** [ccxt/ccxt#17595]
### Operating System

Debian 10

### Programming Languages

php

### CCXT Version

3.0.64

### Description

All markets for binanceus have the 'future' property set to true, yet Binance.US doesn't offer any futures markets.

Also, these same markets DO NOT have the contract property set to true, which would seem to be a contradiction per the manual.

### Code

```
  

```
$exchange = new \ccxt\binancus();

print_r($exchange->load_markets());

#see the 'future' property in the output.

**Comment by carlosmiei** [comment]
Hello @enderwiggum, this afternoon, we merged an update that fixes that issue, so it should be fixed in the next release (should happen in the next few hours). Thanks for letting us know!

**Comment by carlosmiei** [comment]
@enderwiggum it should be fixed as of 3.0.71. Can you update your ccxt version and try again please?
