### ISSUE TITLE
Error Bitget futures fetchOpenInterest

### ISSUE THREAD

**Issue by x1i4b1x2** [ccxt/ccxt#17594]
### Programming Languages

JS

### CCXT Version

3.0.63

### Description

When calling bitget.fetchOpenInterest on expiring futures it throws a weird InvalidOrder.

<img width="347" alt="Screenshot 2023-04-18 at 11 03 33 PM" src="https://user-images.githubusercontent.com/100806945/232904707-260e0b91-4a49-462d-9c49-7e872ac9876e.png">

<img width="1137" alt="Screenshot 2023-04-18 at 11 01 56 PM" src="https://user-images.githubusercontent.com/100806945/232904679-cc62a5c8-c3e4-4f91-9636-0483eacc3278.png">

With perpetuals it's all good.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @x1i4b1x2 thanks for letting us know, we will take a look asap.

**Comment by Dan-krm** [comment]
The method works with delivery futures that expire:
```
bitget.fetchOpenInterest (BTC/USD:BTC-230630)
2023-04-19T02:19:46.762Z iteration 0 passed in 269 ms

{
  symbol: 'BTC/USD:BTC-230630',
  openInterestAmount: 305.594,
  openInterestValue: undefined,
  timestamp: 1681870787704,
  datetime: '2023-04-19T02:19:47.704Z',
  info: {
    symbol: 'BTCUSD_DMCBL_230630',
    amount: '305.594',
    timestamp: '1681870787704'
  }
}
```

It doesn't work with contracts that are expired since expired contracts can't have any open interest:
```
bitget.fetchOpenInterest (BTC/USD:BTC-221230)
BadRequest bitget {"code":"40019","msg":"Parameter BTCUSD_DMCBL_221230 cannot be empty","requestTime":1681870808775,"data":null}
---------------------------------------------------
[BadRequest] bitget {"code":"40019","msg":"Parameter BTCUSD_DMCBL_221230 cannot be empty","requestTime":1681870808775,"data":null}

    at throwExactlyMatchedException  …sers/Dan/Documents/GitHub/ccxt/js/src/base/Exchange.js:2797  
    at handleErrors                  mnt/c/Users/Dan/Documents/GitHub/ccxt/js/src/bitget.js:4356   
    at                               …Users/Dan/Documents/GitHub/ccxt/js/src/base/Exchange.js:754  
    at processTicksAndRejections     node:internal/process/task_queues:96
    at fetch2                        …sers/Dan/Documents/GitHub/ccxt/js/src/base/Exchange.js:2439  
    at request                       …sers/Dan/Documents/GitHub/ccxt/js/src/base/Exchange.js:2442  
    at fetchOpenInterest             mnt/c/Users/Dan/Documents/GitHub/ccxt/js/src/bitget.js:4125   
    at async run                     mnt/c/Users/Dan/Documents/GitHub/ccxt/examples/js/cli.js:295  

bitget {"code":"40019","msg":"Parameter BTCUSD_DMCBL_221230 cannot be empty","requestTime":1681870808775,"data":null}
```

I opened a pull request that changes this error from InvalidOrder to BadRequest because I think it's more generic and makes more sense in this case

**Comment by x1i4b1x2** [comment]
Yes, it seems also that bitget.markets is labeling expired futures as active

<img width="374" alt="Screenshot 2023-04-19 at 11 01 31 AM" src="https://user-images.githubusercontent.com/100806945/233024802-9a07f2a9-1b25-4c0f-b745-c6f320186f55.png">
