### ISSUE TITLE
Bitget fetch_ohlcv still uses wrong timeframe values

### ISSUE THREAD

**Issue by svax974** [ccxt/ccxt#17606]
### Operating System

Debian 11

### CCXT Version

3.0.71

### Description

When calling fetch_ohlcv on bitget, it uses timeframes like '5m', '1d' in the underlying call whereas it should use '5min' and '1day' those cases. Same goes for all *m timeframes, *d and also for w (week).
Thus every fetch_ohlcv seems to get 1m candles by default even when specifying '5m' for instance.

### Code

```
  

```

**Comment by svax974** [comment]
Quick and dirty fix for those interested in bitget.py, just add :
```
2088         selectedTimeframe = self.safe_string(timeframes, timeframe, timeframe)
2089         unit = selectedTimeframe[-1]
2090         if unit == 'm':
2091             selectedTimeframe += 'in'
2092         elif unit == 'd':
2093             selectedTimeframe += 'ay'
2094         elif unit == 'w':
2095             selectedTimeframe += 'eek'
```

**Comment by svax974** [comment]
Moreover, ccxt reports BitGet support 3min timeframe but it seems the API does not thus also getting 1min candles with fetch_ohlcv instead of 3min ones.

**Comment by samgermain** [comment]
The [bitget documentation](https://bitgetlimited.github.io/apidoc/en/mix/#candlestick-interval) specifies the values that we send them, not 1min/3min/etc.

It works fine for me

```
2023-05-04T03:26:18.571Z
Node.js: v18.15.0
CCXT v3.0.90
bitget.fetchOHLCV (BTC/USDT, 5m)

// bitget GET https://api.bitget.com/api/spot/v1/market/candles?symbol=BTCUSDT_SPBL&period=5m&limit=100 200 OK 

2023-05-04T03:26:20.780Z iteration 0 passed in 452 ms

1683164820000 | 29034.47 | 29046.33 | 29034.47 | 29043.45 | 6.9752
1683164880000 | 29043.45 | 29054.76 | 29043.45 |  29050.3 | 4.6058
...
1683170700000 |  29076.5 | 29084.72 |  29074.9 | 29079.67 | 6.9454
1683170760000 | 29079.67 | 29079.77 | 29079.27 | 29079.49 | 2.8184
100 objects
2023-05-04T03:26:20.780Z iteration 1 passed in 452 ms

2023-05-04T03:26:49.054Z
Node.js: v18.15.0
CCXT v3.0.90
bitget.fetchOHLCV (BTC/USDT, 1d)

// bitget GET https://api.bitget.com/api/spot/v1/market/candles?symbol=BTCUSDT_SPBL&period=1Dutc&limit=100 

2023-05-04T03:26:51.373Z iteration 0 passed in 446 ms

1674604800000 | 22631.05 | 23802.11 | 22338.87 |  23053.7 | 11390.9257
1674691200000 |  23053.7 | 23277.68 | 22862.75 | 23008.61 | 11143.8178
...
1683072000000 | 28668.28 | 29262.96 |  28122.3 |  29025.6 |  6483.6821
1683158400000 |  29025.6 | 29189.47 | 28956.64 | 29076.22 |   891.2982
100 objects
2023-05-04T03:26:51.373Z iteration 1 passed in 446 ms

% date -r 1683072000   
Tue May  2 20:00:00 EDT 2023
% date -r 1683158400   
Wed May  3 20:00:00 EDT 2023
% date -r 1683170700   
Wed May  3 23:25:00 EDT 2023
% date -r 1683170760   
Wed May  3 23:26:00 EDT 2023
```

**Comment by svax974** [comment]
Well, ok, but it is stated differently in their doc specifically on the get candles rest api : 
https://bitgetlimited.github.io/apidoc/en/spot/#get-candle-data

And unless I mistake : the time difference between your first 2 candles (and the 2 last ones) seems to be 60 secs, not 5 mins as you specified it, thus presenting the same problem I pointed out.
Seems ok for the daily candles though because 1Dutc is ok too in the get candles doc I linked.

**Comment by ttodua** [comment]
@svax974 I reproduced the issue, will submit a fix

**Comment by ttodua** [comment]
The problem was that @samgermain was referring to futures-api docs, while user @svax974 referred to spot-api docs. So, Sam's posted url real to misleading output, as it used `5m` (futures parameter) to spot api, and thus it caused misunderstanding.

however, the linked PR would fix the problem

However,

**Comment by svax974** [comment]
Great this can be nailed !

However I have another question / precision : I'm using the '5min' parameter to download BTC/USDT (spot) and also BTC/USDT:USDT (swap market = perp future, no ? At least the data retrieved do match the Bitget BTC/USDT.P on TradingView).
It work for both, does ccxt use the "spot" API for both ? I'm a bit confused...

**Comment by svax974** [comment]
Thanks for the fix !

But was the problem fixed only for JS, not python ? If not that would need a fix too... and maybe for php too...

And btw, I can confirm that downloading for futures indeed needs '5m' (BTC/USDT:USDT for example) and won't work with '5min', ccxt has to handle both cases if not already.

**Comment by ttodua** [comment]
Note two things:
1) Almost every change for CCXT is being made in Javascript (TypeScript), however, changes are being reflected to all other ccxt supported langs. So, after you download ccxt update, all langs will have that update.

2) ccxt uses unified approach, which means you dont need to use "exchange-specific" values, like "5min, 5-minute" or whatever . ccxt has only one unified list of timeframes, for minute timeframes you just need to add `m` to the number. so, `5m` in your case, and it would work for that exchange (if exchange api has five minute bars).

**Comment by svax974** [comment]
1. Ok, great, I didn't know sorry
2. I'm aware of the unified thing, I only meant that the underlying call to the Bitget API has to be with 5m for futures and 5min for spot otherwise the Bitget API complains about it, so timeframes have to be handled correctly when calling their APIs, but that might be the case already
Thanks

**Comment by ttodua** [comment]
> 1. Ok, great, I didn't know sorry
> 2. I'm aware of the unified thing, I only meant that the underlying call to the Bitget API has to be with 5m for futures and 5min for spot otherwise the Bitget API complains about it, so timeframes have to be handled correctly when calling their APIs, but that might be the case already
>    Thanks

Thank you at first, for reporting the issue ! ;)
and yeah, `5m` should work on any type (spot, swap ,...) seamlessly, if you find it otherwise, then you are welcome to report the bug again.
