### ISSUE TITLE
Unified trade account

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#17607]
### ؜

Hello,

I don't understant this message when fetching orders of the spot markets. Could you please elaborate what is a "unified trade account" ? I'm confused because `fetchOrders` is set to True for Bybit and I get this error message. I'm wondering what checks need to be performed when choosing between the `fetch_orders` or alternative `fetch_open_orders` + `fetch_closed_orders`.

`bybit fetchOrders() only support spot markets for unified trade account, use exchange.fetch_open_orders() and exchange.fetchClosedOrders() instead`

Thank you,
Kinzowa

**Comment by carlosmiei** [comment]
Hello @Kinzowa,
As you probably know, bybit offers different account types (normal, unified margin, UTA), and the endpoint used varies depending on the type, as the error message suggests, if you do not have a UTA account, there is no endpoint available to perform `fetchOrders` but you can use `fetch_open_orders` + `fetch_closed_orders` to emulate this behavior.

**Comment by Kinzowa** [comment]
Hi Carlos, thanks for the information, I didn't know about these differents account types.

**Comment by indigoram89** [comment]
@carlosmiei  I try to call fetch_order and get the following error: fetchOrder() is not supported after the 5/02 update for UTA accounts, please use fetchOpenOrder or fetchClosedOrder.

<img width="1175" alt="Screenshot 2024-03-10 at 13 47 57" src="https://github.com/ccxt/ccxt/assets/85135210/2dd6e857-4ab9-417a-97df-f988295ca88e">


But as I see ByBit supports it:

<img width="1027" alt="Screenshot 2024-03-10 at 13 46 13" src="https://github.com/ccxt/ccxt/assets/85135210/69033ef6-edc9-43f1-adb1-28a19d2f50b7">
