### ISSUE TITLE
Could not create 'Nonce' for Bigone jwt

### ISSUE THREAD

**Issue by AntonDe** [ccxt/ccxt#17608]
### ؜

Hi there,

I'm trying to read the balance from my Bigone account using a python script.
Beside the API_Key and Secret, there is also an JWT I need. But when I create the jwt, I always get an error:

ccxt.base.errors.AuthenticationError: bigone {"code":40004,"message":"nonce expired"} 

I have try everything, but get still the same error. Here is my code:

`
bigoneApi = os.environ.get('BIGONE_API_KEY')
bigoneSecret = os.environ.get('BIGONE_SECRET')

issuedAt = int(time.time())
expiration = int(time.time()) + 432000 # JWT will expire in 5 days
nonce = int(time.time() * 1000)

payload = {
    "type": "OpenAPI",
    "sub": bigoneApi,
    "iat": issuedAt,
    "exp": expiration,
    "nonce": nonce
}

bigoneToken = jwt.encode(payload, bigoneSecret, algorithm='HS256')
bigoneEx = ccxt.bigone({
    'apiKey': bigoneApi,
    'secret': bigoneSecret,
    'headers': {
        'Authorization': 'Bearer ' + bigoneToken
    }
})`

**Comment by carlosmiei** [comment]
Hello @AntonDe,
CCXT already does the signing logic for you why are you trying to do it manually? You just need to provide the apiKey and secret (token in this case).

**Comment by AntonDe** [comment]
You are right, by using Binance exchange for example I just provide the API and Secret. Bigone needs an JWT set, in other case by just setting the API and Secret and trying to get the balance from Bigone exchange. I get the error: 

invalid jwt

**Comment by carlosmiei** [comment]
> You are right, by using Binance exchange for example I just provide the API and Secret. Bigone needs an JWT set, in other case by just setting the API and Secret and trying to get the balance from Bigone exchange. I get the error:
> 
> invalid jwt

@AntonDe What is your ccxt version? I just tested and seems to be working fine

```
Python v3.10.9
CCXT v3.0.72
bigone.fetchBalance()
{'1INCH': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'AAVE': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'AAVE3L': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'AAVE3S': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'AAVE5L': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'AAVE5S': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'ABBC': {'free': 0.0, 'total': 0.0, 'used': 0.0},
```

**Comment by AntonDe** [comment]
It seems, that I have an error in my secret. I do not checking this because I was implementing the Bigone object with my key and secret, run .get_prices(exchange) on that object, and this do not return any errors, also as I was asking for the balance, the error said: 40004 invalid jwt instead of invalid secret :)
Tank you @carlosmiei
