### ISSUE TITLE
Can not send order to OKX: NaN: invalid number (contains an illegal character 'N')

### ISSUE THREAD

**Issue by nakazoomi** [ccxt/ccxt#17603]
### ؜

Hi there, 

I try to send an order to OKX but always got the following error: 
```
NaN: invalid number (contains an illegal character 'N')    
```
This is the order I am trying to send:
```
const order = await exchange.createOrder(
      payload.symbol, 
      payload.side, 
      payload.type, 
      payload.market, 
      Number(payload.leverage), // convert to number
      payload.amountType, 
      Number(payload.amount), // convert to number
    ); 
```
The JSON payload looks like this:
```
{
  symbol: 'BTC/USDT',
  side: 'buy',
  type: 'market',
  market: 'futures',
  leverage: 2,
  amountType: 'percent',
  amount: 20
}
```
Why do I get the error: `NaN: invalid number (contains an illegal character 'N')`  ?

It seems like the JSON payload is not correct. Can anyone help?

**Comment by samgermain** [comment]
You're not passing the parameters in the correct order, and that's not how you set leverage or use futures

Here is the documentation on
- [creating an order](https://docs.ccxt.com/#/?id=placing-orders)
- [setting leverage](https://docs.ccxt.com/#/?id=leverage)
- [contract naming](https://docs.ccxt.com/#/?id=contract-naming-conventions)
    - specifies what symbols to use for futures markets
