### ISSUE TITLE
Huobi unable to place conditional order

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#17615]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

3.0.59

### Description

I am unable to place a conditional limit order on Huobi, even when using the "tp_trigger_price" or "sl_trigger_price" params. For example, I want to place a conditional order to open a long position of 100 XRP at 0.5 USDT, but I am unable to do so. 

### Code

```
  
    public = ""
    private = ""
            
    client = ccxt.huobi({'apiKey': public, 'secret': private})
    
    ticker = "XRP/USDT:USDT"
    side = 'buy'
    quantity = 10
    price = 0.5
    mode = 'open'
    
    response = client.create_order(symbol=ticker, type="limit", side=side,
                                   amount=quantity, price=price,
                                   params={'tp_trigger_price': price, 'offset': mode})

```
ExchangeError: huobi {"status":"error","err_code":1405,"err_msg":"The take-profit price shall not be ≤0.5USDT ","ts":1681990337022}

**Comment by Dan-krm** [comment]
When the PR I opened is merged you'll be able to make a conditional order like this using:
```
response = client.create_order(symbol=ticker, type="limit", side=side, amount=quantity, price=price,
           params={"stopPrice": price, "triggerType":"ge"})
```

**Comment by Tomas-MP** [comment]
@Dan-krm is it also possible to create stop market orders? Below code throws the follwing error: 

response = client.create_order(symbol=ticker, type="optimal_20_ioc", side=side, amount=quantity, price=None, params={'stopPrice': price, 'triggerType': trigger})

InvalidOrder: huobi {"status":"error","err_code":1034,"err_msg":"Incorrect field of order price type.","ts":1682852039618}

**Comment by Dan-krm** [comment]
> 

Yeah for stop market orders you need to set the type to "optimal_20", "optimal_10" or "optimal_5"
https://huobiapi.github.io/docs/usdt_swap/v1/en/#cross-place-trigger-order
