### ISSUE TITLE
Phemex currently no funding_rate_history method

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#17625]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

I see that it is currently available in the api documentation of Phemex but has not been added to ccxt yet. 

See documentaton: https://phemex-docs.github.io/#get-funding-rate-history-2

### Describe the solution you'd like

A method fetch_funding_rate_history() to fetch the historical funding rates for a specific symbol. 

### Describe alternatives you've considered

None at the moment.

**Comment by carlosmiei** [comment]
Hello @Tomas-MP, thanks for letting us know.

However, I'm making some tests and the endpoint does not seem to retrieve any data 🤔 `https://api.phemex.com/api-data/public/data/funding-rate-history?symbol=BTCUSDT`

**Comment by Tomas-MP** [comment]
@carlosmiei I also tried around, their funding_rate_history endpoint is kinda weird indeed. When you use fetch_markets() the info also shows 'fundingRate8hSymbol', which then subsequently can be used to retrieve the corresponding funding rates. 

For example, to retrieve the funding rate history of BTCUSD perpetual you need to use: https://api.phemex.com/api-data/public/data/funding-rate-history?symbol=BTCFR8H. For BTCUSDT the ticker becomes BTCUSDTFR8H.

Kinda inconvenient but should be fixable.

**Comment by carlosmiei** [comment]
> @carlosmiei I also tried around, their funding_rate_history endpoint is kinda weird indeed. When you use fetch_markets() the info also shows 'fundingRate8hSymbol', which then subsequently can be used to retrieve the corresponding funding rates.
> 
> For example, to retrieve the funding rate history of BTCUSD perpetual you need to use: https://api.phemex.com/api-data/public/data/funding-rate-history?symbol=BTCFR8H. For BTCUSDT the ticker becomes BTCUSDTFR8H.
> 
> Kinda inconvenient but should be fixable.

@Tomas-MP Oh ok that  is feasible for sure, will try to add it soon, thanks! 🙂  (btw additionally you also need to add a dot `https://api.phemex.com/api-data/public/data/funding-rate-history?symbol=.BTCUSDTFR8H`
