### ISSUE TITLE
too many response is this right?

### ISSUE THREAD

**Issue by 2GEasy** [ccxt/ccxt#17621]
### Operating System

Windows 10

### Programming Languages

JS

### CCXT Version

3.0.61

### Description

I connect websocket and execute while(true) { watchTickers() } and etc.. 
and then client receive responses too many ! 

792 balance 14996.65082777 //792 RESPONSE
793 balance 14996.65503301 //793 RESPONSE
4759 ticker close >  28555 //4759 RESPONSE

is this right status?

### Code

//nestjs

@SubscribeMessage('tickers')
  async handleTickers(@MessageBody() data: any):Promise<void> {
      let exchangepro = getExchangePro(data.site);
        if(exchangepro.checkRequiredCredentials()) {
            while (true) {
              try {
                // console.log(exchangepro);
                if (exchangepro.has['watchTickers']) {
                  // const ticker = await exchangepro.watchTicker(data.coin)
                  // console.log ("ticker", ticker.close)
                  // exchangepro.sleep(10000);
                  // this.server.emit('ticker',{symbol:data.coin,ticker:ticker.close});
                  const tickers = await exchangepro.watchTickers();
                  console.log("tickers",moment().format('ss'));
                  // console.log("tickers", tickers['BTC/USDT:USDT'].close);
                  this.server.emit('tickers',tickers);
                  await sleep(10000);
                }
              } catch (e) {
                  console.log (e)
                  // throw e // uncomment to stop the loop on exceptions
              }
            }
        }
  }

**Comment by carlosmiei** [comment]
Hello @2GEasy,
Can you elaborate a bit more please? Which exchange are you using, how long it takes to get that error, etc

**Comment by 2GEasy** [comment]
Hello @carlosmiei !
I use binanceusdm and every seconds get that situation while looping. and i use socket each for get tickers, positions, balances.

**Comment by pcriadoperez** [comment]
Hi @2GEasy , I wasn't able to reproducing it by just calling watchTickers in a loop. Are you calliing also other watchFunctions? Are you getting the error consistently?

**Comment by frosty00** [comment]
not clear what the question is
