### ISSUE TITLE
ByBit doesn't have latest symbols

### ISSUE THREAD

**Issue by bbtrader22** [ccxt/ccxt#17620]
### Operating System

Ubuntu

### Programming Languages

python

### CCXT Version

3.0.73

### Description

Bybit misses USDT perpetual coins that have been added for a couple of weeks already.

Examples COCOSUSDT (https://www.bybit.com/trade/usdt/COCOSUSDT)

    order = exchange.create_order(
  File "/usr/local/lib/python3.10/dist-packages/ccxt/bybit.py", line 3298, in create_order
    market = self.market(symbol)
  File "/usr/local/lib/python3.10/dist-packages/ccxt/base/exchange.py", line 3347, in market
    raise BadSymbol(self.id + ' does not have market symbol ' + symbol)
ccxt.base.errors.BadSymbol: bybit does not have market symbol COCOS/USDT

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @bbtrader22 

For the unified symbol usage of usdt perpetual, it required settlement, eg `COCOS/USDT:USDT`. The `COCOS/USDT` symbol represent spot market. 

Let me know if you have any questions.

**Comment by bbtrader22** [comment]
Ha, thanks. I changed it now to include the :USDT by default. It works.

The funny thing was that by using 'category:linear', the 'old' symbols like 'ETH/USDT' did produce an order, while newer like 'COCOS/USDT' didn't.

  params={
            #'closePosition': False,
            'reduceOnly': False,
            'stopLoss': str(stop_loss),
            'takeProfit': str(take_profit),
            'category': 'linear',
            'timeInForce': 'GoodTillCancel',
           
            }
