### ISSUE TITLE
[Question] FetchStatus

### ISSUE THREAD

**Issue by 300Gram** [ccxt/ccxt#17631]
### ؜

Hi, 

I have been having trouble to find the answer by myself through the ccxt documentation. So I have no choice to ask it here. 
I would like to use exchange.fetchStatus() to do a initial check before running my script. 

But I wonder, what will be expected response if an exchange goes into maintenance mode? 
How will the 'eta' response be like? In seconds or date time? 

Because i am implementing a loop that will sleep until the ETA time before running the remaining code if it goes into maintenance mode. 

Sorry if this answer can be found, because i really didn't manage to find it.

**Comment by sc0Vu** [comment]
Hi @300Gram 

If the exchange start maintenance mode, the statue would be `maintenance`.

It seems not so much exchange response  `eta` (only see bitmart), and the data would be timestamp in ms.

Let me know if you have any other issues.

**Comment by 300Gram** [comment]
Thank you so much!
