### ISSUE TITLE
Cannot find a deposit address for token, MEXC

### ISSUE THREAD

**Issue by AlwxDavydov** [ccxt/ccxt#17647]
### Operating System

Windows 10 

### CCXT Version

2.8.31

### Description

I've noticed that mexс seems to require manually creating a deposit address, but that doesn't work for me. Is it possible to create an address in automatic mode to check which networks are available for deposits right now? For my goal, fetch_deposit_addresses_by_network is work great but it is also work only with alredy created adresses

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @AlwxDavydov 

I think you can check whether there is deposit address when call fetch_deposit_addresses_by_network, if the response is empty, call https://mxcdevelop.github.io/apidocs/spot_v3_cn/#97fb427a63 `spotPrivatePostCapitalDepositAddress`

**Comment by AlwxDavydov** [comment]
@sc0Vu That's the problem, using fetch_deposit_addresses_by_network with USDC I got:
mexc3 fetchDepositAddress() cannot find a deposit address for USDC, consider creating one using the MEXC platform. 

I tried old API but got the same. So I tried spotPrivatePostCapitalDepositAddress('USDC') but I got: 
'str' object does not support item assignment. 
I guess I do something wrong, can you please show me example of using it. Sorry for my stupidity

**Comment by sc0Vu** [comment]
@AlwxDavydov 

The params should be object.
```JS
spotPrivatePostCapitalDepositAddress({'coin':'USDC', 'network':'ERC20'}) 
```

**Comment by sc0Vu** [comment]
Hi @AlwxDavydov

We've added `createDepositAddress` in mexc, you can use that after update ccxt.

**Comment by AlwxDavydov** [comment]
@sc0Vu Thank you very much. So fast, WTF

**Comment by AlwxDavydov** [comment]
@sc0Vu  Thanks a lot, this works great. But I have a question, is it possible to check which networks are available to create an address. I can easily get the address if the coin uses popular blockchains, but some use their own, for example STX that use STACKS, which are not so well known
