### ISSUE TITLE
ModuleNotFoundError: No module named 'ccxt'

### ISSUE THREAD

**Issue by nihow666** [ccxt/ccxt#1764]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: win10
- Programming Language version: python3
- CCXT version: 1.10.992

I just install ccxt by using pip install ccxt.

import ccxt
print(ccxt.exchanges)

then it shows ModuleNotFoundError: No module named 'ccxt'

**Comment by kroitor** [comment]
Check if you have multiple Pythons installed:


```
python --version
pip list
pip --version
```

```
python3 --version
pip3 list
pip3 --version
```

Hope it helps.

**Comment by kroitor** [comment]
@anttonis what does `pip list` show?

**Comment by anttonis** [comment]
Hm.. it is not in the list. and uninstall says it does not exist.

when I do:
pip install ccxt again I get..
...
... Requirement already satisfied: etc...
Installing collected packages: setuptools, ccxt
  Found existing installation: setuptools 38.4.0
    Uninstalling setuptools-38.4.0:
You are using pip version 10.0.0,.....

And that is it

**Comment by kroitor** [comment]
This is a known issue of Anaconda, not related to CCXT (honestly sick of their incompatibilities with mainstream Python):

- https://www.google.com/search?q=anaconda+pip+install+not+working

Looks like you should install a conda-version of pip and use it...
1. `conda install pip` then restart your environment
2. `pip install ccxt`

Hope this helps. See other posts linked above if not, for more info. Thx!

**Comment by anttonis** [comment]
Yes, your suggestion worked!
You saved me some time and frustration with it.
Thanks!

**Comment by kroitor** [comment]
@anttonis thx for reporting back! Cheers!

**Comment by bradosaurus** [comment]
I'm having this same error message, but the above troubleshooting hasn't seemed to help.

- OS: Windows 7
- Programming Language version: Python 3.6.5 x64
- CCXT version: 1.17.249
- Editor: VS Code 1.27.1

I can't seem to import ccxt. Looking through the ccxt github and my local ccxt-master directory, there is a ccxt.d.ts, ccxt.js, and ccxt.php, but no ccxt.py. Am I misunderstanding this?

I have only ever installed Python 3.6.5 and have confirmed that there are no other versions of Python on this computer. I've checked `pip list` and `pip3 list` and neither show ccxt. I do not have Anaconda installed.

I used the standard `pip install ccxt` in cmd and it says `Requirement already satisfied` for most of the install items except for errors it gets when installing lru-dict and cytoolz. They both seem to be looking for a path that doesn't exist: 

```
error: [WinError 3] The system cannot find the path specified: 'C:\\ProgramFiles (x86)\\Microsoft Visual Studio 14.0\\VC\\PlatformSDK\\lib'
```

I'm not using Visual Studio, but I do have it installed on the computer. Should I uninstall it?

When I run these commands in VS Code editor:

```
import ccxt
print(ccxt.exchanges)
```

I get this error:

```
C:\Users\Bradley>python "c:/.../ccxt-master/test.py"
Traceback (most recent call last):
  File "c:/.../ccxt-master/test.py", line 1, in <module>
    import ccxt
ModuleNotFoundError: No module named 'ccxt'
```

Any other suggestions that might help me identify the problem?

This is the pip list:
```

C:\Users\Bradley>pip list
Package           Version
----------------- ---------
aiodns            1.1.1
aiohttp           3.3.1
astroid           1.6.5
async-timeout     3.0.0
attrs             18.1.0
cchardet          2.1.1
certifi           2018.4.16
chardet           3.0.4
colorama          0.3.9
eth-hash          0.2.0
eth-typing        1.3.0
idna              2.6
idna-ssl          1.0.1
isort             4.3.4
lazy-object-proxy 1.3.1
mccabe            0.6.1
multidict         4.3.1
pip               18.0
pycares           2.3.0
pycryptodome      3.6.6
pylint            1.9.2
pypiwin32         223
pywin32           223
requests          2.18.4
setuptools        39.0.1
six               1.11.0
toolz             0.9.0
urllib3           1.22
websockets        5.0.1
wheel             0.31.1
wrapt             1.10.11
yarl              1.1.0
```

**Comment by kroitor** [comment]
> Am I misunderstanding this?

Yes, because there's also a ccxt module in python, it's in the `python` folder. You don't really link directly against ccxt repository, unless you're trying to develop a new exchange class for it. Most often you don't need the repository at all. All you need is a properly installed version of Python3, then you just run `pip install ccxt` and that's it.

> ```error: [WinError 3] The system cannot find the path specified: 'C:\\ProgramFiles (x86)\\Microsoft Visual Studio 14.0\\VC\\PlatformSDK\\lib'```

↑ As for this line, have you tried googling it? Because this is an issue with your python setup, not with the library itself. Not sure if it should be `ProgramFiles (x86)` or `Program Files (x86)` (might be a space missing?). Anyways, you can try the following:

- https://www.google.ru/search?q=error%3A+%5BWinError+3%5D+The+system+cannot+find+the+path+specified%3A+%27C%3A%5C%5CProgramFiles+%28x86%29%5C%5CMicrosoft+Visual+Studio+14.0%5C%5CVC%5C%5CPlatformSDK%5C%5Clib%27
- https://www.google.ru/search?q=stackoverflow+The+system+cannot+find+the+path+specified+PlatformSDK+lib&oq=stackoverflow+The+system+cannot+find+the+path+specified+PlatformSDK+lib
- https://github.com/kpu/kenlm/issues/90

> I'm not using Visual Studio, but I do have it installed on the computer. Should I uninstall it?

Nope, you should install VS Code Build Tools, as described by those links... Let us know if that does not help.

**Comment by bradosaurus** [comment]
Thank you for taking the time and [leading me in the correct direction](http://lmgtfy.com/?q=You%27re+awesome!), @kroitor. Installing the Windows SDK and compiler on Visual Studio 2015 following [this simple instruction](https://stackoverflow.com/a/51662134) seems to have resolved the `pip install ccxt` issue and now `import ccxt` isn't showing an error.

**Comment by kroitor** [comment]
@bradosaurus thx for reporting, appreciate the feedback!

**Comment by lowgrind** [comment]
![image](https://user-images.githubusercontent.com/72610419/120277644-a8d25780-c2f7-11eb-963a-caa21b8c2c34.png)

did anyone get a fix for this? It's so weird how it doesn't detect it

**Comment by mazzorm** [comment]
> ![image](https://user-images.githubusercontent.com/72610419/120277644-a8d25780-c2f7-11eb-963a-caa21b8c2c34.png)
> 
> did anyone get a fix for this? It's so weird how it doesn't detect it

same proble
![Schermata 2021-09-21 alle 17 30 23](https://user-images.githubusercontent.com/72458037/134200914-484bee9d-9afc-4e18-90d3-6a0cd30487a1.png)
m

**Comment by kroitor** [comment]
@mazzorm check the above solutions: https://github.com/ccxt/ccxt/issues/1764#issuecomment-420053314

**Comment by TristonH55** [comment]
whats the fix for this @mazzorm 
Import "ccxt" could not be resolved

**Comment by semarql** [comment]
python --version
Python 3.13.2

pip list
Package                   Version
------------------------- -----------
aiodns                    3.2.0
aiohappyeyeballs          2.6.1
aiohttp                   3.10.11
aiosignal                 1.3.2
altair                    5.5.0
attrs                     25.3.0
blinker                   1.9.0
cachetools                5.5.2
ccxt                      4.4.69
certifi                   2025.1.31
cffi                      1.17.1
charset-normalizer        3.4.1
click                     8.1.8
colorama                  0.4.6
cryptography              44.0.2
frozenlist                1.5.0
gitdb                     4.0.12
GitPython                 3.1.44
idna                      3.10
Jinja2                    3.1.6
jsonschema                4.23.0
jsonschema-specifications 2024.10.1
MarkupSafe                3.0.2
multidict                 6.2.0
narwhals                  1.30.0
numpy                     2.2.3
packaging                 24.2
pandas                    2.2.3
pillow                    11.1.0
pip                       25.0.1
propcache                 0.3.0
protobuf                  5.29.3
pyarrow                   19.0.1
pycares                   4.5.0
pycparser                 2.22
pydeck                    0.9.1
python-dateutil           2.9.0.post0
pytz                      2025.1
referencing               0.36.2
requests                  2.32.3
rpds-py                   0.23.1
setuptools                77.0.3
six                       1.17.0
smmap                     5.0.2
streamlit                 1.43.2
tenacity                  9.0.0
toml                      0.10.2
tornado                   6.4.2
typing_extensions         4.12.2
tzdata                    2025.1
urllib3                   2.3.0
watchdog                  6.0.0
yarl                      1.18.3

pip --version
pip 25.0.1 from 


![Image](https://github.com/user-attachments/assets/906e6c92-e872-4f59-b10e-3194bfb9d956)

**Comment by carlosmiei** [comment]
@semarql Make sure you're installing the package in the same environment you're running it.
