### ISSUE TITLE
Bigone Bug fetch balance from funding account

### ISSUE THREAD

**Issue by AntonDe** [ccxt/ccxt#17643]
### Operating System

MacOS

### Programming Languages

python

### Description

Hi all,

when I trying to fetch balance from my funding account I get an error:

AttributeError: 'bigone' object has no attribute 'privateGetFundingAccounts'

The method fetch_balance() from the bigone.py can take some additional params which are the SPOT/FUNDING/etc. Then it generate the method:
method = 'privateGet' + self.capitalize(type) + 'Accounts'

But when the code runs I get the previously mentioned error.

### Code

```
# My code:
    funding_balance = await bigoneEx.fetch_balance(params={"type": "funding"})
    print("Funding balance: {}".format(funding_balance))

# Code from bigone.py from ccxt:
async def fetch_balance(self, params={}):
        """
        query for balance and get the amount of funds available for trading or funds locked in orders
        :param dict params: extra parameters specific to the bigone api endpoint
        :returns dict: a `balance structure <https://docs.ccxt.com/en/latest/manual.html?#balance-structure>`
        """
        await self.load_markets()
        type = self.safe_string(params, 'type', '')
        params = self.omit(params, 'type')
        method = 'privateGet' + self.capitalize(type) + 'Accounts'
        response = await getattr(self, method)(params)
```

**Comment by carlosmiei** [comment]
Hello @AntonDe,
Yeah right now it only accepts `type=fund` instead of the unified `funding` but I will patch it asap.

**Comment by AntonDe** [comment]
Thank you @carlosmiei 
Really appreciate your help :)
