### ISSUE TITLE
bybit: missing Spot Cross-Margin endpoints for non-unified accounts

### ISSUE THREAD

**Issue by gshpychka** [ccxt/ccxt#17655]
### CCXT Version

3.0.75

### Description

The following (implicit) endpoints are missing for bybit:

```
/v5/spot-cross-margin-trade/pledge-token
/v5/spot-cross-margin-trade/borrow-token
/v5/spot-cross-margin-trade/loan-info
/v5/spot-cross-margin-trade/account
/v5/spot-cross-margin-trade/loan
/v5/spot-cross-margin-trade/repay
/v5/spot-cross-margin-trade/orders
/v5/spot-cross-margin-trade/repay-history
/v5/spot-cross-margin-trade/switch
```

**Comment by carlosmiei** [comment]
@gshpychka Thanks for informing us, we will add them soon.

@sc0Vu can you add them pls?

**Comment by sc0Vu** [comment]
@carlosmiei turns out I have added these apis in other PR: https://github.com/ccxt/ccxt/pull/17184/files#diff-5b072b659fad4f748d901fd07dade97dc83dc072b2a5d3c9c03c9a3b1200da20

It might take some time to review that PR, I'll open another PR for these endpoints.
