### ISSUE TITLE
Binance Market structure not showing the limit costs even if it's in the info dictionary

### ISSUE THREAD

**Issue by tumma72** [ccxt/ccxt#17657]
### Operating System

Mac OS

### Programming Languages

Python 3.11

### CCXT Version

2.9.16

### Description

Not sure since which version this stopped working but the mapping of the filter structure for "NOTIONAL" in the Binance (asyncio) version of the exchange, isn't any longer copying correctly to the limit['cost'] dictionary of the CCXT normalized Market structure. As the information is in the info dictionary but not in the normalized limits structure I supposed something went lost in translation :-)

### Code
Here some copied and pasted code that might help...

from the info structure:
```
'filters': [{'filterType': 'PRICE_FILTER', 'minPrice': '0.01000000', 'maxPrice': '1000000.00000000', 'tickSize': '0.01000000'}, {'filterType': 'LOT_SIZE', 'minQty': '0.00001000', 'maxQty': '9000.00000000', 'stepSize': '0.00001000'}, {'filterType': 'ICEBERG_PARTS', 'limit': '10'}, {'filterType': 'MARKET_LOT_SIZE', 'minQty': '0.00000000', 'maxQty': '148.10423095', 'stepSize': '0.00000000'}, {'filterType': 'TRAILING_DELTA', 'minTrailingAboveDelta': '10', 'maxTrailingAboveDelta': '2000', 'minTrailingBelowDelta': '10', 'maxTrailingBelowDelta': '2000'}, {'filterType': 'PERCENT_PRICE_BY_SIDE', 'bidMultiplierUp': '5', 'bidMultiplierDown': '0.2', 'askMultiplierUp': '5', 'askMultiplierDown': '0.2', 'avgPriceMins': '5'}, {'filterType': 'NOTIONAL', 'minNotional': '10.00000000', 'applyMinToMarket': True, 'maxNotional': '9000000.00000000', 'applyMaxToMarket': False, 'avgPriceMins': '5'}, {'filterType': 'MAX_NUM_ORDERS', 'maxNumOrders': '200'}, {'filterType': 'MAX_NUM_ALGO_ORDERS', 'maxNumAlgoOrders': '5'}]
```

Where you can see that "NOTIONAL" is one of the dict inside the "filters" list, while looking at the normalized market structure:

```
{'amount': {'min': 1e-05, 'max': 9000.0}, 'price': {'min': 0.01, 'max': 1000000.0}, 'cost': {'min': None, 'max': None}, 'leverage': {'min': None, 'max': None}, 'market': {'min': 0.0, 'max': 148.10423095}}
```

Where you can see that the "cost" doesn't actually contains the filter values.

**Comment by carlosmiei** [comment]
Hello @tumma72, 
Is it possible to update to the latest version and try again? (I noticed you have a relatively outdated version)

**Comment by tumma72** [comment]
> Hello @tumma72, Is it possible to update to the latest version and try again? (I noticed you have a relatively outdated version)

Thanks @carlosmiei I have updated to the latest now, and the problem has been solved. It's strange because I am using Poetry and I thought it would update all of the packages itself, but apparently doesn't shift major versions unless explicitly asked to...

Sorry for wasting your time 😉

**Comment by tumma72** [comment]
Sorry I forgot to close the issue, this problem has been solved.
