### ISSUE TITLE
fetch_tickers() yobit error

### ISSUE THREAD

**Issue by cryptonic203** [ccxt/ccxt#17661]
### Operating System

WIndows

### CCXT Version

3.0.74

### Description

Hi.
I can't get the full list of currencies with prices that the function "fetch_tickers()" returns.
Each exchange gives out different results, for example:

```
$data=mysqli_source($con,"select * from `stocks` where `name`='{$stock}'");
$exchange = '\\ccxt\\'.$stock;

if ($data['apikey']='') $exchange = new $exchange (); 
else $exchange = new $exchange (array('apiKey' => $data['apikey'],'secret' => $data['secret'],));

echo 'load_markets: '.count($exchange->load_markets()).'<br>';
echo 'fetch_tickers: '.count($exchange->fetch_tickers()).'<br>';
echo 'fetch_tickers*: '.count($exchange->fetch_tickers(array_keys($exchange->load_markets()))).'<br>';
```

**Bybit** 
load_markets: 620
fetch_tickers: 217
fetch_tickers*: 250

**Binance**
load_markets: 2471
fetch_tickers: 2190
fetch_tickers*: 2185

**Gateio**
load_markets: 3775
fetch_tickers: 3049
fetch_tickers*: 3049

**Huobi**
load_markets: 1641
fetch_tickers: 802
fetch_tickers*: 785

**Yobit**
load_markets: 8950

**Fatal error**: Uncaught TypeError: implode(): Argument #1 ($pieces) must be of type array, string given in X:\domains\ccxt0\php\yobit.php:546 Stack trace: #0 X:\domains\ccxt0\php\yobit.php(546): implode() #1 X:\domains\ccxt\index.php(443): ccxt\yobit->fetch_tickers() #2 {main} thrown in X:\domains\ccxt0\php\yobit.php on line 546

fetch_tickers*: 0

As you can see on the "Yobit" exchange, an error occurs on the fetch_tickers() function.
Tell me how to correctly check prices in all currencies, and what to do with error on the stock Yobit.

thank you for your help

### Code

```
  

```

**Comment by ttodua** [comment]
I'll review this and submit the fix
