### ISSUE TITLE
Error with amountToPrecision function on Binance SOL/USDT:USDT

### ISSUE THREAD

**Issue by spc789** [ccxt/ccxt#17665]
### Operating System

Windows & Linux

### Programming Languages

python

### CCXT Version

3.0.54

### Description

The amountToPrecision function does not work as expected on Binance Futures for pair SOL/USDT:USDT
(Other pairs work ok)

market = exchange.market("SOLUSDT")
It seems market['precision']['amount'] returns 0

Exception type: 
> <class 'ccxt.base.errors.ArgumentsRequired'>

Exception message: 
> binance amount of SOL/USDT:USDT must be greater than minimum amount precision of 0

Traceback (most recent call last):
>   File "./slfid-CCXT-WS", line 3013, in <module>
>     calc_init()
>   File "./slfid-CCXT-WS", line 987, in calc_init
>     order_sizes.append(exchange.amountToPrecision(symbol, order_sizes1[ll]))
>   File "/usr/local/lib/python3.8/dist-packages/ccxt/base/exchange.py", line 3390, in amount_to_precision
>     raise ArgumentsRequired(self.id + ' amount of ' + market['symbol'] + ' must be greater than minimum amount precision of ' + self.number_to_string(market['precision']['amount']))

Market dict for SOLUSDT : 

```
{   'active': True,
    'base': 'SOL',
    'baseId': 'SOL',
    'contract': True,
    'contractSize': 1.0,
    'expiry': None,
    'expiryDatetime': None,
    'future': False,
    'id': 'SOLUSDT',
    'info': {   'baseAsset': 'SOL',
                'baseAssetPrecision': '8',
                'contractType': 'PERPETUAL',
                'deliveryDate': '4133404800000',
                'filters': [   {   'filterType': 'PRICE_FILTER',
                                   'maxPrice': '6857',
                                   'minPrice': '0.4200',
                                   'tickSize': '0.0010'},
                               {   'filterType': 'LOT_SIZE',
                                   'maxQty': '1000000',
                                   'minQty': '1',
                                   'stepSize': '1'},
                               {   'filterType': 'MARKET_LOT_SIZE',
                                   'maxQty': '1000',
                                   'minQty': '1',
                                   'stepSize': '1'},
                               {'filterType': 'MAX_NUM_ORDERS', 'limit': '200'},
                               {   'filterType': 'MAX_NUM_ALGO_ORDERS',
                                   'limit': '10'},
                               {   'filterType': 'MIN_NOTIONAL',
                                   'notional': '5.0'},
                               {   'filterType': 'PERCENT_PRICE',
                                   'multiplierDecimal': '4',
                                   'multiplierDown': '0.9500',
                                   'multiplierUp': '1.0500'}],
                'liquidationFee': '0.015000',
                'maintMarginPercent': '2.5000',
                'marginAsset': 'USDT',
                'marketTakeBound': '0.05',
                'maxMoveOrderLimit': '10000',
                'onboardDate': '1569398400000',
                'orderTypes': [   'LIMIT',
                                  'MARKET',
                                  'STOP',
                                  'STOP_MARKET',
                                  'TAKE_PROFIT',
                                  'TAKE_PROFIT_MARKET',
                                  'TRAILING_STOP_MARKET'],
                'pair': 'SOLUSDT',
                'pricePrecision': '4',
                'quantityPrecision': '0',
                'quoteAsset': 'USDT',
                'quotePrecision': '8',
                'requiredMarginPercent': '5.0000',
                'settlePlan': '0',
                'status': 'TRADING',
                'symbol': 'SOLUSDT',
                'timeInForce': ['GTC', 'IOC', 'FOK', 'GTX'],
                'triggerProtect': '0.0500',
                'underlyingSubType': ['Layer-1'],
                'underlyingType': 'COIN'},
    'inverse': False,
    'limits': {   'amount': {'max': 1000000.0, 'min': 1.0},
                  'cost': {'max': None, 'min': 5.0},
                  'leverage': {'max': None, 'min': None},
                  'market': {'max': 1000.0, 'min': 1.0},
                  'price': {'max': 6857.0, 'min': 0.42}},
    'linear': True,
    'lowercaseId': 'solusdt',
    'maker': 0.0002,
    'margin': False,
    'option': False,
    'optionType': None,
    'precision': {'amount': 0, 'base': 8, 'price': 3, 'quote': 8},
    'quote': 'USDT',
    'quoteId': 'USDT',
    'settle': 'USDT',
    'settleId': 'USDT',
    'spot': False,
    'strike': None,
    'swap': True,
    'symbol': 'SOL/USDT:USDT',
    'taker': 0.0004,
    'type': 'swap'}
```

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @spc789, thanks for reporting it and sorry for the delay. We will fix it asap.

**Comment by carlosmiei** [comment]
Hello @spc789, sorry for the late response. 

The confusing thing here is the error message, but the code is working correctly. In this case it means you can't buy fractional SOL contracts (for instance 0.5) you can only choose integer amounts (1 contract, 2 contracts, etc).

![image](https://user-images.githubusercontent.com/43336371/235347257-942f9bdf-d18b-4ecb-bcef-f1d221acb140.png)


We will try to improve the error message, thanks for reporting it!

**Comment by spc789** [comment]
Hi @carlosmiei , 

No problem for the late response.
What one could do is adapting the amountToPrecision function so it accepts a 0 as argument.
However then the possibility if errors goes away.
To tackle that possibility one could use -1 in the dict when the exchange didn't reply a valid amount. 

For example : 

If the dict is : 

> 'precision': {'amount': 0, 'base': 8, 'price': 3, 'quote': 8},

do the correct rounding in amountToPrecision

If the dict is : 

>    'precision': {'amount': -1, 'base': 8, 'price': 3, 'quote': 8},

throw an error

**Comment by carlosmiei** [comment]
Hello again @spc789, the thing is 0 is the correct value, because Binance uses the `DECIMAL_PLACES` precision mode so if can only buy integer amounts (1,2,3,4, etc) you have indeed 0 decimal places
