### ISSUE TITLE
I get Error BadRequest: binanceusdm {"code":-1102,"msg":"Mandatory parameter timestamp was not sent, was empty/null, or malformed."}

### ISSUE THREAD

**Issue by 2GEasy** [ccxt/ccxt#17672]
### Operating System

Windows 10

### Programming Languages

JS

### CCXT Version

3.0.61

### Description

I try stopLoss Market Order after limit order to implement the limit order with tp/sl.
and get this Error.

BadRequest: binanceusdm {"code":-1102,"msg":"Mandatory parameter timestamp was not sent, was empty/null, or malformed."}

I read document but other mandatory parameter is nothing.

site : binanceusdm  
symbol: BTCUSDT

### Code

var result = await exchange.createLimitOrder (coin, side, count, orderPrice,{}) //BTCUSDT sell 0.07 100000
var slResult = await exchange.createMarketOrder(coin, side, count, params) //BTCUSDT sell 0.07 { takeProfitPrice: 100400 }

**Comment by carlosmiei** [comment]
Hello @2GEasy, does it happens every time? Is it possible to share a verbose log?
