### ISSUE TITLE
binance {"code":-1102,"msg":"Mandatory parameter timestamp was not sent, was empty/null, or malformed."}

### ISSUE THREAD

**Issue by LukaPitamic** [ccxt/ccxt#17681]
### Operating System

Linux, docker + linux

### Programming Languages

python

### CCXT Version

3.0.75

### Description

When trying to place _stop-market_ order on _Binance_ I'm mosly getting:

`BadRequest: binance {"code":-1102,"msg":"Mandatory parameter timestamp was not sent, was empty/null, or malformed."}`

a few orders go through though (see the video demonstration):
https://www.screencast.com/t/Q2duZTpP

I was chatting with _Binance_ support for one hour and they concluded that the origin of the problem is added timestamp within ccxt in case of setting _stop-market_ order.  

### Code

```python
import ccxt

# exchange instatiation
apikey = ''
secretkey = ''
binance = ccxt.binance({
    'apiKey': apikey,
    'secret': secretkey,
    'enableRateLimit': True,
    'options': {'defaultType': 'future'} 
})

# testnet
binance.set_sandbox_mode(True)

# stop-market order
order_id=exchange.create_order(
    symbol=symbol,
    type='market',
    side='buy',
    amount=0.001,
    price=None,
    params={'triggerPrice':50000})['id']

```

**Comment by sc0Vu** [comment]
Hi @LukaPitamic 

Would you like to paste verbose log for the request (use verbose mode)?

**Comment by LukaPitamic** [comment]
Hi @sc0Vu , error response is gone. I was running the script for 24h, every 2s the order was placed and canceled successfully. In other words I cannot replicate the error. I will keep the script running if problem reapers, but for now let's consider the problem solved.

**Comment by sc0Vu** [comment]
@LukaPitamic Thanks, let me know if you have other issues.
