### ISSUE TITLE
Luno since field in dictionary is not included in call to the API, but since in parameter field is

### ISSUE THREAD

**Issue by craigt1212** [ccxt/ccxt#1769]
- OS: Mac OS X El Capitan
- Programming Language version: Python3
- CCXT version: 1.10.981
- Exchange: Luno
- Method: fetch_trades

I have noticed the following limitation in the Luno exchange fetch_trades method.
```
luno = ccxt.luno()
luno.load_markets()
luno.fetch_trades('BTC/ZAR', since=1517731259000)
```
The call to the API is as follows:
https://api.mybitx.com/api/1/trades?pair=XBTZAR
This should include the since parameter in the url, and as a result is only returning the newest 100 records.

The call to the API below is correct and returns the relevant records for the specified timeframe. 
```
luno = ccxt.luno()
luno.load_markets()
luno.fetch_trades('BTC/ZAR', params={'since':1517731259000})
```
https://api.mybitx.com/api/1/trades?pair=XBTZAR&since=1517731259000

**Comment by kroitor** [comment]
Fixed in 1.10.999, thanks for reporting!
