### ISSUE TITLE
GT is named GTX on bitfinex but is missing from the pairs list

### ISSUE THREAD

**Issue by batrudinych** [ccxt/ccxt#17697]
### CCXT Version

3.0.52

### Description

GT is labeled GTX on bitfinex. The symbols list that is returned by ccxt for bitfinex misses GT. See [here](https://trading.bitfinex.com/t/GTX:USD?type=exchange) and [here](https://support.bitfinex.com/hc/en-us/articles/360024667394-Gate-io-GTX-)

### Code

```
const ccxt = require('ccxt')
const exchange = new ccxt.bitfinex()
await exchange.loadMarkets()
for (const symData of exchange.symbols) {
  const [base, quote] = symData.split('/')
  if (base === 'GT') {
    console.log('bitfinex has GT listed')
    return
  }
}
console.log('GT not found on bitfinex')
```

**Comment by sc0Vu** [comment]
The market data was fetched from exchange, exchange might have different name on tokens. You might want to ask bitfinex for this.

<img width="571" alt="image" src="https://user-images.githubusercontent.com/10494397/235038144-f6239356-5613-41ef-9cd2-91dd05f63ddd.png">
