### ISSUE TITLE
Poloniex what is the withdraw param for memo

### ISSUE THREAD

**Issue by AntonDe** [ccxt/ccxt#17691]
### ؜

Hi all,

I try to send XLM from Poloniex to Binance with the withdraw method. I have already send XLM from Bigone to Binance, and insert as additional parameter 

```
binance_fetch_depo_dict = await binanceEx.fetch_deposit_address('XLM')
binance_xlm_address = binance_fetch_depo_dict['address']
binance_xlm_tag = binance_fetch_depo_dict['tag']
try:
        xlm_withdrawal = await bigoneEx.withdraw('XLM', xlm_amount, binance_xlm_address, params={'memo': binance_xlm_tag})
```

and this code works fine for Bigone. But trying the same with Poloniex did't work. So I checked out the api docs and saw that there is also possible to pass paymentId as parameter:

```
binance_fetch_depo_dict = await binanceEx.fetch_deposit_address('XLM')
binance_xlm_address = binance_fetch_depo_dict['address']
binance_xlm_tag = binance_fetch_depo_dict['tag']

try:
    xlm_withdrawal = await poloniexEx.withdraw('XLM', 20, binance_xlm_address, params={'paymentId': binance_xlm_tag})
```

Is the payment Id correct as a parameter for memo?

Thank you

**Comment by yzh-pelle** [comment]
Hello, @AntonDe !
Yes, `paymentId` is the correct param for this purpose.
Different exchanges often use specific names for the same params. In this case Bigone accepts `memo`,  but Poloniex accepts `paymentId` param in request for the same information.  
CCXT `exchange.withdraw ()` method has unified param `tag` (see more: https://docs.ccxt.com/#/README?id=withdrawal) converting to the exchange-specific request inside this method. So you don't have to add `binance_xlm_tag` as a specific `params` property, instead you can use it as a fourth argument of the `withdraw` method:
```py
binance_fetch_depo_dict = await binanceEx.fetch_deposit_address('XLM')
binance_xlm_address = binance_fetch_depo_dict['address']
binance_xlm_tag = binance_fetch_depo_dict['tag']
try:
  xlm_withdrawal_from_bigone = await bigoneEx.withdraw('XLM', xlm_amount, binance_xlm_address, binance_xlm_tag)
  xlm_withdrawal_from_poloniex = await poloniexEx.withdraw('XLM', xlm_amount, binance_xlm_address, binance_xlm_tag)
```
