### ISSUE TITLE
[Request] WooNetwork Algo Order

### ISSUE THREAD

**Issue by 300Gram** [ccxt/ccxt#17693]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Describe the solution you'd like

I tried to search for how to send an Algo-Order through the CCXT documentation for WooNetwork, but unfortunately, I couldn't find it.

Currently, the only way for me to place a reduce-only order for a trade is by creating a check function or method to confirm whether the order has been filled before sending the take-profit and stop-loss for that trade.

After exploring the Woo API, I found that the only way to place TP and SL with the trade is by using an Algo-order. Therefore, I would like to request that the CCXT contributors or admins implement this feature for WooNetwork, along with the fetchTickers and get-Algo Order information.

Unfortunately, I am not a professional developer and am unable to contribute, but I appreciate anyone who is able to make this possible!

**Comment by sevenjay** [comment]
we need this feature, too. I see @sc0Vu has implemented it, could we merge it?

**Comment by carlosmiei** [comment]
@sevenjay @300Gram we added this feature 6 months ago here: https://github.com/ccxt/ccxt/pull/18379
You should be able to access it if you have an updated ccxt version.
