### ISSUE TITLE
Unified list of deposit addresses 

### ISSUE THREAD

**Issue by ppisljar** [ccxt/ccxt#1770]
Would it be possible to have a unified way to get a list of all deposit addresses that exist on my account ?

right now i am using bittrex and cryptopia, and both give a list of deposit addresses when you query balances. 

at the moment i need to get them from:
bittrex: `balancesResponse.info.find(b => b.Currency === currencyCode).CryptoAddress`
cryptopia: `balancesResponse.info.Data.find(b => b.Symbol === currencyCode).Address`

perfectly i would do something like:
`market.loadMarkets(); market.fetchBalances();` and then all the available addresses would be available at `market.currencies[currencyCode].depositAddress`

thanks.

**Comment by kroitor** [comment]
This feature has been implemented and is now described here: https://github.com/ccxt/ccxt/wiki/Manual#funding-your-account
