### ISSUE TITLE
precision check error for okx " amount of asset must be greater than minimum amount precision of 1"

### ISSUE THREAD

**Issue by Sailendrakc** [ccxt/ccxt#17710]
### Operating System

windows 10

### CCXT Version

ccxt@3.0.78

### Description

Being more specefic, whenever I try to place long order for EDLD-USDT-SWAP for investment of 20 dollars at the rate of 40 dollars (i.e 0.5 amount), then the order gets rejected by ccxt saying it is less than the precision amount. But 0.5 amount of order is valid order and can be placed in okx website. As long as the amount is multiple of contract size, the order should be valid but it keeps getting rejected.

I have provided the minimal code to reproduce the error. Just copy paste and run script in a localhost. open dev tools to see the console outputs.

### Code

```
  <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/ccxt@3.0.78/dist/ccxt.browser.js"></script>
<script async>

(async function() {
    //login and authentication details
    let details = {
        "okx": {
        apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        secret: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        uid: 'xxxxxxxxxxxxxx',
        password: 'xxxxxxxxxxxxxxx'
        }
    }

// loading exchange and performing auth
    let exchange = new ccxt['okx']();
    let dt = details['okx'];
    if (dt) {
        exchange.apiKey = dt.apiKey;
        exchange.secret = dt.secret;
        exchange.uid = dt.uid;
        exchange.password = dt.password;
        exchange.nonce = function () {
        return exchange.milliseconds();
            }
        }

 // loading markets
    await exchange.loadMarkets();

    //create order.
    let symbol = "EGLD-USDT-SWAP"; 
    let type = "limit";
    let side = "buy";
    let rate = 40;
    let investment = 20;
    let market = await exchange.market(symbol);
    console.log("Market is: ");
    console.log(market);

//amount calculation so its multiple of contract size/lot size.
    let amount = investment / rate;

    let cSize = market.contractSize;
    console.log("Contract size is: " + cSize);

    if (cSize == 1) {
        //to match the lot size.
        amount = Math.floor(amount);
    }
    else {
        let flamount = Math.floor(amount / cSize);
        amount = parseFloat((flamount * cSize).toFixed(8));
    }

    if(amount == 0){
            console.log("More investment required");
            return;
    }

    console.log("Look if amount: " + amount.toString() + " is multiple of contrat size: " + cSize.toString());
    let params = {
            'posSide': 'long',
        }


//create an order
    let id = await exchange.createOrder(symbol = symbol, type = type, side = side, amount = amount, rate = rate, params);

})();

</script>
</html>

```

Now this will give output with error of: 

Market is: 
lottest:51 {taker: 0.0005, maker: 0.0002, id: 'EGLD-USDT-SWAP', symbol: 'EGLD/USDT:USDT', base: 'EGLD', …}
lottest:57 Contract size is: 0.1
lottest:73 Look if amount: 0.5 is multiple of contrat size: 0.1

ccxt.browser.js:9556 Uncaught (in promise) ArgumentsRequired: okx amount of EGLD/USDT:USDT must be greater than minimum amount precision of 1
    at okx.amountToPrecision (https://cdn.jsdelivr.net/npm/ccxt@3.0.78/dist/ccxt.browser.js:9556:19)
    at okx.createOrder (https://cdn.jsdelivr.net/npm/ccxt@3.0.78/dist/ccxt.browser.js:172189:24)
    at async http://localhost:3000/lottest:80:14

**Comment by carlosmiei** [comment]
Hello @Sailendrakc, futures are usually measured in `contract` units instead of the base currency (EDLD in this case). Assuming that `1 contract = 0.1` and you want to buy `0.5` you should be using `amount = 5` instead of `amount = 0.5`

**Comment by samgermain** [comment]
The error is saying that you're amount must be at least 1

**Comment by Sailendrakc** [comment]
@carlosmiei  Thank you Very much!

**Comment by Sailendrakc** [comment]
@carlosmiei  Thank you very much!
