### ISSUE TITLE
okex function okcoinFuture.future_position_4fix not working

### ISSUE THREAD

**Issue by leehow1984** [ccxt/ccxt#1771]
- OS: Windows 10
- Programming Language version: Python 3.6
- CCXT version: 1.10.456
- Exchange: okex
- Method: okcoinFuture.future_position_4fix

Hi, I am trying to use future_position_4fix('btc_usd',None,1) to get my future position from OKEX, but i have the following error

Code:
myposition2 = okcoinFuture.future_position_4fix('BTC/USD',None,1)

Error:
File "C:\****\Python\Python36\site-packages\ccxt\okcoinusd.py", line 574, in sign
    }, params))
File "C:\****\Python\Python36\site-packages\ccxt\base\exchange.py", line 511, in extend

ValueError: dictionary update sequence element #0 has length 1; 2 is required

I also tried other arguments such as 
private_post_future_position_4fix('BTC/USD','this_week',1)
private_post_future_position_4fix('btc_usd','this_week',1)

but none of them are working.

**Comment by kroitor** [comment]
Hi!

It does work, but you're not supplying a proper params dictionary to it (pass just one single argument, containing all exchange-specific params).

The method future_position_4fix is an exchange-specific implicit method. See here on how to properly pass params to implicitly defined methods:
- https://github.com/ccxt/ccxt/wiki/Manual#overview
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods

Let us know if that does not answer your question. Thx!

**Comment by leehow1984** [comment]
OK thanks! 

The problem is "The set of all possible API endpoints differs from exchange to exchange. **Most of methods accept a single associative array (or a Python dict) of key-value parameters**. The params are passed as follows:"

therefore one could:
dict1 = {'symbol':'btc_usd','contract_type':'this_week','type':1}
myposition = okex.private_post_future_position_4fix(dict1)
