### ISSUE TITLE
XT.com API calls return ExchangeError time sync issue

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#17724]
### Operating System

Windows 10

### CCXT Version

3.0.83

### Description

When I try to use a simple API call it returns the below error message, even when I synced the time settings of my machine. Is there a way to fix this? 

### Code

```
  
import ccxt
client = ccxt.xt({'apiKey': "" 'secret': ""})

client.options['defaultType'] = 'swap'
client.options['adjustForTimeDifference'] = True

info = client.fetch_balance(params={'type': 'swap'})


```
ExchangeError: xt {"returnCode":1,"msgInfo":"failure","error":{"code":"403","msg":"The request time 1682869381327 exceeds the specified time 1682869381269 limit by 5 second"},"result":null}

**Comment by carlosmiei** [comment]
Hello @Tomas-MP, Right now `adjustForTimeDifference` option is not implemented, but I will add it soon. What is your clock timezone?

**Comment by Tomas-MP** [comment]
@carlosmiei thank you, my clock time zone is UTC+2

**Comment by carlosmiei** [comment]
> @carlosmiei thank you, my clock time zone is UTC+2

@Tomas-MP For debugging purposes, is it possible to adjust it to UTC? 
Also very soon a new release with the `adjustForTimeDifference` option will be available, you can try that as well.

**Comment by Tomas-MP** [comment]
@carlosmiei will wait for the  adjustForTimeDifference option, thank you very much!
