### ISSUE TITLE
Request For Bitshares

### ISSUE THREAD

**Issue by rhrahul** [ccxt/ccxt#1772]
Hi,

Can you suggest me information on adding Bitshares Exchange ?

Thanks

**Comment by kroitor** [comment]
Hi!

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md
- https://github.com/ccxt/ccxt/wiki/Exchange-Markets
- https://github.com/ccxt/ccxt/pulls

Let us know if this does not answer your question.

Thx!

**Comment by scottie** [comment]
bitshares/cryptobridge api is horrid, adding bitshares/cryptobridge is no trivial task.
Good luck with your attempt.
