### ISSUE TITLE
Phemex set_position_mode()  not working for USD perps

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#17730]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

3.0.85

### Description

The set_position_mode argument is not working for Phemex perpetual USD futures (see code below).

### Code

```
  
import ccxt
client = ccxt.phemex({'apiKey': "", 'secret': ""})

ticker = "BTC/USD:USD"
client.set_position_mode(True, ticker)
```
Traceback (most recent call last):

  Cell In[20], line 1
    client.set_position_mode(True, ticker)

  File ~\anaconda3\lib\site-packages\ccxt\phemex.py:3552 in set_position_mode
    market = self.market(symbol)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:3328 in market
    raise ExchangeError(self.id + ' markets not loaded')

ExchangeError: phemex markets not loaded

**Comment by carlosmiei** [comment]
Hello @Tomas-MP, yeah we're missing the markets loading, thanks for letting us know.
