### ISSUE TITLE
Do markets need to be "re-loaded" in order to find out about new coin listings?

### ISSUE THREAD

**Issue by alexlacey** [ccxt/ccxt#1774]
I am wondering if the load_markets() function needs to be called multiple times if I want to determine when an exchange lists a new currency. I'm not sure if I need to use the "reload = True" flag. Thanks for the help!

In case it matters, here's some background information:
I am building a program that detects new coin listings on various exchanges. Essentially, for each exchange, I get a set of listed currencies every few minutes, and I compare each set to the previous set, looking for coins in the second set that aren't in the first set.

**Comment by kroitor** [comment]
> I am wondering if the load_markets() function needs to be called multiple times if I want to determine when an exchange lists a new currency.

Yes it needs to be called multiple times.

> I'm not sure if I need to use the "reload = True" flag.

Yes, you do need to use the `reload = True` flag:

```Python
exchange.load_markets(True)  # force reload
```

More about it here: https://github.com/ccxt/ccxt/wiki/Manual#market-cache-force-reload

Let us know if it doesn't answer your question. Thx!
