### ISSUE TITLE
Documentation CCXT Pro : "watchOHLCV" don't have "timeFrame" parametter

### ISSUE THREAD

**Issue by dawadam** [ccxt/ccxt#17749]
### ؜

On documentation of CCXT pro :

https://docs.ccxt.com/#/ccxt.pro.manual?id=watchohlcv

"watchOHLCV" don't have "timeFrame" parametter

```
// JavaScript
if (exchange.has['watchOHLCV']) {
    while (true) {
        try {
            const candles = await exchange.watchOHLCV (symbol, since, limit, params)
            console.log (new Date (), candles)
        } catch (e) {
            console.log (e)
            // stop the loop on exception or leave it commented to retry
            // throw e
        }
    }
}
```

On the code, parameter exists :

` async watchOHLCV (symbol, timeframe = '1m', since = undefined, limit = undefined, params = {}) {`

**Comment by yzh-pelle** [comment]
Thank you for your comment.  We fixed our wiki file.
