### ISSUE TITLE
https://ccxt.pro will redirect to https://ccxt.com 

### ISSUE THREAD

**Issue by bloodchen** [ccxt/ccxt#17741]
### Operating System

macos

### Programming Languages

JS

### Description

how to get the license?

### Code

```
  

```

**Comment by pcriadoperez** [comment]
Hi @bloodchen ccxt pro is now free and included in the ccxt library.

I'll close this issue for now but feel free to reach out if you have any questions.

**Comment by JoelAzaria** [comment]
It's nice to see that the Pro features are now free.  Suggest that this is made clear either on the project page somewhere, or in the links/redirects that are scattered throughout ref'ing ccxt.com and ccxt.pro.

Currently links just redirect back to the main github project page.  This is disorienting/confusing and I spent a fair few minutes trying to figure out why (till I found this closed ticket).

thx.
