### ISSUE TITLE
Quadriga error on private requests

### ISSUE THREAD

**Issue by adonayn** [ccxt/ccxt#1775]
HI

With any quadrigacx private request I get the error of missing payload. Is there a bug or am I doing something wrong? with other exchanges doesn't happen. 

This is the error:

quadrigacx.fetch_balance()
Traceback (most recent call last):

  File "<ipython-input-183-b3599b2da025>", line 1, in <module>
    quadrigacx.fetch_balance()

  File "build/bdist.macosx-10.6-x86_64/egg/ccxt/quadrigacx.py", line 79, in fetch_balance
    balances = self.privatePostBalance()

  File "build/bdist.macosx-10.6-x86_64/egg/ccxt/quadrigacx.py", line 239, in request
    raise ExchangeError(self.id + ' ' + self.json(response))

ExchangeError: quadrigacx {"error":{"message":"Invalid or missing payload","code":105}}

- OS: Mac
- Programming Language version: Python
- CCXT version: latest
- Exchange: quadrigacx
- Method: any private request

Thanks!

**Comment by kroitor** [comment]
Hi!

Can you please do this:

```Python
quadrigacx.verbose = True
quadrigacx.fetch_balance()
```

... and post your verbose output here? (remove/mask your keys if needed)

**Comment by adonayn** [comment]
'''
('POST', 'https://api.quadrigacx.com/v2/balance', '\nRequest:', {'Content-Type': 'application/x-www-form-urlencoded', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'python-requests/2.10.0'}, '{"nonce":1517808616,"key":"TDymaskV","signature":"20338mask60959f0296f9b27b66011"}')
('POST', 'https://api.quadrigacx.com/v2/balance', '\nResponse:', '{\'Expect-CT\': \'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"\', \'Content-Length\': \'79\', \'X-XSS-Protection\': \'1; mode=block\', \'CF-RAY\': \'3e837a10cacd3b56-YVR\', \'X-Content-Type-Options\': \'nosniff\', \'Content-Encoding\': \'gzip\', \'Set-Cookie\': \'__cfduid=d2e8ee294c5d0c6602179be53d44efa081mask; expires=Tue, 05-Feb-19 05:30:17 GMT; path=/; domain=.quadrigacx.com; HttpOnly\', \'Vary\': \'Accept-Encoding\', \'Server\': \'cloudflare\', \'Connection\': \'keep-alive\', \'Date\': \'Mon, 05 Feb 2018 05:30:17 GMT\', \'Access-Control-Allow-Origin\': \'*\', \'Content-Type\': \'application/json\', \'X-Frame-Options\': \'SAMEORIGIN\'}', u'{"error":{"code":105,"message":"Invalid or missing payload"}}')
Traceback (most recent call last):

  File "<ipython-input-187-86629fd4337b>", line 2, in <module>
    quadrigacx.fetch_balance()

  File "build/bdist.macosx-10.6-x86_64/egg/ccxt/quadrigacx.py", line 79, in fetch_balance
    balances = self.privatePostBalance()

  File "build/bdist.macosx-10.6-x86_64/egg/ccxt/quadrigacx.py", line 239, in request
    raise ExchangeError(self.id + ' ' + self.json(response))

ExchangeError: quadrigacx {"error":{"message":"Invalid or missing payload","code":105}}
'''

Here is the output. 
Thanks for taking a look

**Comment by kroitor** [comment]
The `.uid` must be a string-type (a numeric string to be precise), is that correctly set up in your case?

**Comment by adonayn** [comment]
Yes, my uid is a numeric string.

**Comment by kroitor** [comment]
Does this work for you?

```Python
import ccxt
quadrigacx = ccxt.quadrigacx ({ "apiKey": "qvFrjjJEEF", "secret": "f18f8f178696d36a760a6c4f13bc6fa7", "uid": "395037"})
print(quadrigacx.fetch_balance())
```

?

**Comment by adonayn** [comment]
No, it did not work either. I don't know if you made any changes but just in case I upgraded the version, mine was a few days ago, and now works. 

Thanks!

**Comment by kroitor** [comment]
Ok, let us know if you have any other difficulties with with it.
