### ISSUE TITLE
Huobi not returning order information for trigger orders

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#17756]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

3.0.86

### Description

I am unable to retrieve the information of orders with the trigger parameter, although it returns order information for limit/market orders fine. 

### Code

```
  
import ccxt

client = ccxt.huobi({'apiKey': '', 'secret': ''})

ticker = "XRP/USDT:USDT"
side = "buy"
quantity = 5
price = 0.5
trigger = "ge"
leverage = 5

response = client.create_order(symbol=ticker, type="limit", side=side,
                               amount=quantity, price=price,
                               params={'stopPrice': price,
                                       'triggerType': trigger,
                                       'offset': 'open',
                                       'lever_rate': leverage})
client.fetch_order(response['id'], ticker)
```
Traceback (most recent call last):

  Cell In[56], line 1
    client.fetch_order(response['id'], ticker)

  File ~\anaconda3\lib\site-packages\ccxt\huobi.py:3125 in fetch_order
    response = getattr(self, method)(self.extend(request, params))

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:507 in inner
    return entry(_self, **inner_kwargs)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2882 in request
    return self.fetch2(path, api, method, params, headers, body, config, context)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2879 in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:669 in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File ~\anaconda3\lib\site-packages\ccxt\huobi.py:5427 in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], code, feedback)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:3188 in throw_exactly_matched_exception
    raise exact[string](message)

OrderNotFound: huobi {"status":"error","err_code":1017,"err_msg":"Order doesnt exist.","ts":1683050470512}

**Comment by Dan-krm** [comment]
It doesn't look like there's an endpoint for using fetchOrder for trigger orders, but I opened a pull request that will add trigger order support to fetchOrders, fetchOpenOrders and fetchClosedOrders

**Comment by Tomas-MP** [comment]
Hi @Dan-krm, thank you for fixing this. I also approached this issue in the same way for Bitget so should be fine.
