### ISSUE TITLE
Maker/taker information in fetch_my_trades/parse_trade

### ISSUE THREAD

**Issue by nmiculinic** [ccxt/ccxt#1776]
I'd love to have maker/taker information in trades; that is knowing whether I'm maker or taker in particular trade. As far as I can see, there's no designated field in return dictionary. 

Can we add some?

**Comment by kroitor** [comment]
Sure, but most exchanges will not return that type of info... it will be undefined in the majority of cases. But we can add a new field to the trades, of course.

**Comment by nmiculinic** [comment]
But those that do, can you/we decide on field name? makerOrTaker or something meaningful to standardize it.

**Comment by mkutny** [comment]
I'd add `takerOrMaker` on exchanges where it gets determined for fee calculation. If we store its explicit value in trade it would make reasoning about "why do I have this fee" more apparent.

I can add it to the Manual first and then start adding on exchanges where applicable.

**Comment by kroitor** [comment]
> I can add it to the Manual first and then start adding on exchanges where applicable.

That would be awesome! )
