### ISSUE TITLE
Bybit watch_ticker() does not return values

### ISSUE THREAD

**Issue by mrpouley** [ccxt/ccxt#17769]
### Operating System

linux

### Programming Languages

python

### CCXT Version

3.0.90

### Description

Hi,

Bybit watch_ticker() seems broken for spot. Works fine for perpetual swaps. 

### Code

```
import asyncio
import ccxt.pro as ccxt

bybit = ccxt.bybit()
asyncio.run(bybit.watch_ticker("BTC/USDT"))  # this hangs forever
```

**Comment by carlosmiei** [comment]
Hello @mrpouley,
You need to set `defaultType = spot` because bybit has conflicting ids.

**Comment by carlosmiei** [comment]
> It works, thanks. So it's not possible to call watch_ticker() on both spot and futures using the same exchange object, am i correct?

@mrpouley As of now it is not possible, but we will try to fix this issue in the future

**Comment by carlosmiei** [comment]
@philipperemy @mrpouley After the v5 migration, this should work, you should be able to do
```Python
await bybit.watch_ticker('BTC/USDT')
await bybit.watch_ticker('BTC/USDT:USDT')
```
with no issues as long as you have an updated version of ccxt

**Comment by frosty00** [comment]
yep, ccxt 3.0 is very old...

**Comment by philipperemy** [comment]
@carlosmiei so it works but the `bid` and the `ask` are equal to `None` when it comes to spot instruments.

**Comment by philipperemy** [comment]
```python
import asyncio

import ccxt.pro

bybit = ccxt.pro.bybit()
print(asyncio.run(bybit.watch_ticker('BTC/USDT')))
```

```
{'symbol': 'BTC/USDT', 'timestamp': 1700697865426, 'datetime': '2023-11-23T00:04:25.426Z', 'high': None, 'low': 35822.01, 'bid': None, 'bidVolume': None, 'ask': None, 'askVolume': None, 'vwap': 36870.1403687674, 'open': 35829.61, 'close': 37445.77, 'last': 37445.77, 'previousClose': None, 'change': 1616.16, 'percentage': 4.51, 'average': 36637.69, 'baseVolume': 11610.147233, 'quoteVolume': 428067758.18276644, 'info': {'symbol': 'BTCUSDT', 'lastPrice': '37445.77', 'highPrice24h': '37864.94', 'lowPrice24h': '35822.01', 'prevPrice24h': '35829.61', 'volume24h': '11610.147233', 'turnover24h': '428067758.18276642', 'price24hPcnt': '0.0451', 'usdIndexPrice': '37451.710000000001'}}
```
