### ISSUE TITLE
XT - Unable to cancel conditional orders

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#17776]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

3.0.86

### Description

When placing a conditional order, I am unable to cancel it afterwards. See code below to reproduce the issue. 

### Code

```
  
import ccxt

client = ccxt.xt({'apiKey': "", 'secret': ""})

ticker = "XRP/USDT:USDT"
side = 'buy'
quantity = 30
price = 0.5


response = client.create_order(symbol=ticker, type="limit", side=side,
                               amount=quantity, price=price,
                               params={'stopPrice': price,
                                       'triggerPriceType': 'LATEST_PRICE'})
client.cancel_order(response['id'], ticker, params={'stop': True})

```
Traceback (most recent call last):

  Cell In[60], line 11
    client.cancel_order(response['id'], ticker, params={'stop': True})

  File ~\anaconda3\lib\site-packages\ccxt\xt.py:2750 in cancel_order
    response = self.privateLinearPostFutureTradeV1EntrustCancelPlan(self.extend(request, params))

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:507 in inner
    return entry(_self, **inner_kwargs)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2882 in request
    return self.fetch2(path, api, method, params, headers, body, config, context)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2879 in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:669 in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File ~\anaconda3\lib\site-packages\ccxt\xt.py:4146 in handle_errors
    raise ExchangeError(feedback)

ExchangeError: xt {"returnCode":1,"msgInfo":"failure","error":{"code":"E000","msg":"Internal Service Error"},"result":null}

**Comment by carlosmiei** [comment]
Hello again @Tomas-MP,  I will take a look. Thanks for bringing this up.

**Comment by carlosmiei** [comment]
@Tomas-MP I'm going to reach out to XT, apparently the request is well-formed so I'm not sure what is causing this issue.

**Comment by carlosmiei** [comment]
@Tomas-MP XT just deployed an update to the API, can you try it again to see if it works?

**Comment by Tomas-MP** [comment]
@carlosmiei will do thanks!
