### ISSUE TITLE
Phemex - unable to use fetch_funding_rate_history() for non USDT pairs

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#17774]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

3.0.86

### Description

Non-USDT pairs are excluded from the ccxt method although it is available in the API. For example https://api.phemex.com/api-data/public/data/funding-rate-history?symbol=.BTCFR8H shows the funding rates for the BTCUSD perpetual contract. Is it possible to still add this? 

### Code

```
  
import ccxt
client = ccxt.phemex()

rates = client.fetch_funding_rate_history("BTC/USD:USD")
```
Traceback (most recent call last):

  Cell In[3], line 1
    rates = client.fetch_funding_rate_history("BTC/USD:USD")

  File ~\anaconda3\lib\site-packages\ccxt\phemex.py:3937 in fetch_funding_rate_history
    raise BadRequest(self.id + ' fetchFundingRateHistory() supports USDT swap contracts only')

BadRequest: phemex fetchFundingRateHistory() supports USDT swap contracts only

**Comment by carlosmiei** [comment]
Hello @Tomas-MP, thanks for reporting it. I was not aware of this endpoint but will add it asap.
