### ISSUE TITLE
CoinEx unable to use since parameter for fetch_ohlcv()

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#17801]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

3.0.92

### Description

Unfortunately somehow the method only returns the most recent 100 values rather than returning the data from the point specified in the code below. I am not sure whether this is even feasible as the api docs (https://viabtc.github.io/coinex_api_en_doc/futures/#docsfutures001_http012_market_kline) do not mention anything about a since argument either. 

### Code

```
  
import time
import ccxt

client = ccxt.coinex()

since = int(time.time() - 10 * 86400) * 1000

data = client.fetch_ohlcv("BTC/USDT:USDT", '1m', since)
print(data[0][0])
print(since)

```
1683286920000
1682428876000

**Comment by carlosmiei** [comment]
Hello @Tomas-MP,
Unfortunately, there's not much ccxt can do because, as you said, the API does not accept a timestamp filter, so ccxt can only filter after getting the data from the exchange.

**Comment by Tomas-MP** [comment]
No problem, thank you for clarifying, will reach out to the exchange then !
