### ISSUE TITLE
Whitebit does not work

### ISSUE THREAD

**Issue by mrisedev** [ccxt/ccxt#17803]
### Operating System

Linux

### Programming Languages

python

### CCXT Version

3.0.93

### Description

exchange = ccxt.whitebit({
    'apiKey': self.api_key,
    'secret': self.api_secret
})
result = exchange.fetch_balance()

###

That's all, whitebit just broken.
both self.api_key and self.api_secret are strings. 

traceback:

  File "/******/github/crypto_bot/venv/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1192, in hmac
    h = hmac.new(secret, request, algorithm)
  File "/usr/lib/python3.9/hmac.py", line 170, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python3.9/hmac.py", line 93, in __init__
    self.update(msg)
  File "/usr/lib/python3.9/hmac.py", line 113, in update
    self._inner.update(msg)
TypeError: Strings must be encoded before hashing

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @mrisedev,

Thanks for letting us know and sorry for the inconvenience, we will fix it asap!

**Comment by carlosmiei** [comment]
@mrisedev If you update to 3.0.94 the issue should be fixed. Thanks once again.
