### ISSUE TITLE
Setting timeout and reconnect wait time for ws streams

### ISSUE THREAD

**Issue by spc789** [ccxt/ccxt#17818]
### Operating System

Windows & Linux

### Programming Languages

python

### CCXT Version

-

### Description

Is there a way to programmatically set the timeout property and a reconnect wait time for the websocket streams ? 

### Code

```
  

```

**Comment by pcriadoperez** [comment]
Hi @spc789 ,

You can set the property `exchange['streaming']['keepAlive']` which is the ping-pong keep-alive rate in milliseconds

For the reconnect, by default if the connection is lost we reconnect when the next time the `watch` function is called. To control the timming, we throw an error when there is a disconnect, so in the try.. catch.. clause you could look for that error and set a reconnect time.

I hope this answers the question, if not let me know or feel free to close the issue

**Comment by spc789** [comment]
Thx for the answer !
