### ISSUE TITLE
CoinEx reduceOnly orders not working properly

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#17826]
### Operating System

Windows 10

### CCXT Version

3.0.96

### Description

Not sure whether the API supports it but from the CCXT code it is possible to create a reduceOnly order. But when I open a long position and then try to reduce this position, it does end up with with a short position (see example below). 

### Code

```
  
import ccxt

client = ccxt.coinex({'apiKey': "", 'secret': ""})


ticker = "XRP/USDT:USDT"

open_ = client.create_order(symbol=ticker, type="market", side='buy',
                               amount=50, price=None)

close_ = client.create_order(symbol=ticker, type="market", side='sell',
                               amount=100, price=None,
                               params={'reduceOnly': True})

```

**Comment by carlosmiei** [comment]
Hello @Tomas-MP, yeah coinex is a bit peculiar with reduceOnly orders. Can you try to provide the position id inside `params` as well? 

Example:
```Python
params = {
   'reduceOnly': True
    'position_id': ID
```
More info: https://viabtc.github.io/coinex_api_en_doc/futures/#docsfutures001_http030_limit_close

**Comment by Tomas-MP** [comment]
@carlosmiei this indeed works, thank you! Then first the position id can be retrieved with id = client.fetch_position(ticker)['id']

**Comment by carlosmiei** [comment]
@Tomas-MP Nonetheless, I will add an explicit check of `position_id` to avoid this issue, thank you!

**Comment by Tomas-MP** [comment]
This issue can be fixed by putting reduceOnly to False, but then it will create a short position if your long stoploss is triggered and vice versa.
