### ISSUE TITLE
binance  DDoSProtection

### ISSUE THREAD

**Issue by nihow666** [ccxt/ccxt#1782]
- OS: win 10
- Programming Language version: python 3.6
- CCXT version: 1.10.1004
- Exchange: binance
- Method: fetch_tickers

It shows:
ccxt.base.errors.DDoSProtection: binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API."}

**Comment by kroitor** [comment]
What's your question about it?
