### ISSUE TITLE
binance handleOrderBook received an out-of-order nonce in watchOrderBook

### ISSUE THREAD

**Issue by spc789** [ccxt/ccxt#17827]
### Operating System

Linux

### Programming Languages

python

### CCXT Version

3.0.96

### Description

This afternoon I got an *binance handleOrderBook received an out-of-order nonce* error in the my watchOrderbook routine. (Version of ccxt is 3.0.96)

The following traceback is not complete as my onscreen traceback was overwritten with some other data. 
In my file logging routine was an error so the traceback wasn't saved there.
The moment the error shows up again I'll post a complete traceback

>Traceback (most recent call last):
>  File "./CCXT-WS", line 4263, in watch_ticker
>    orderbook = await exchange.watchOrderBook(symbol, orderbook_level)
>  File "/usr/local/lib/python3.8/dist-packages/ccxt/pro/binance.py", line 192, in watch_order_book
>[  >> LIVE >>  ] [ >>> TICKER BTC/USDT : high 29137.0 low : 28620.2 change -25.700 percentage -0.089 <<< ]
>[  >> LIVE >>  ] [ >>> ORDERBOOK BTC/USDT : bids 28841.4 asks : 28841.5 price : 28841.5 <<< ]
>ccxt.base.errors.ExchangeError: binance handleOrderBook received an out-of-order nonce
>[ 19:02:04.418 ]    >>> Error type : ExchangeError
>[ 19:02:04.419 ]    >>> Error msg : binance handleOrderBook received an out-of-order nonce

### Code

```
  

```

**Comment by pcriadoperez** [comment]
Hi @spc789 , it can happen that the orderbook falls out of sync, due to an out of order message or missing message from the server, and that's why the error is thrown.

However if you call `watchOrderBook` inside a try and catch clause, it should be able to reconnect after the error.

I'll close the issue for now, but feel free to reach out if you have any other questions or the error persists.

**Comment by spc789** [comment]
My code does a try / except and restarts, but at the same time at shows where are were, it was for your info

**Comment by spc789** [comment]
Delved a bit deeper into this, fyi, 
As soon as I used a net interceptor preloading library so I could dump the streaming packets the problem vanished. 
I suppose it has something to do with the internals of (re)connecting to the stream, at least in my case.
