### ISSUE TITLE
Phemex, unable to cancel orders (USDT swaps)

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#17835]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

3.0.97

### Description

It might be that the API endpoint is being updated (https://phemex-docs.github.io/#query-trading-account-and-positions), but still I am unable to cancel an order unfortunately. See the code below to reproduce. 

### Code

```
  
import ccxt

client = ccxt.phemex({'apiKey': "", 'secret': ""})

response = client.create_order(symbol="XRP/USDT:USDT", type="limit", side='buy',
                               amount=30, price=0.4,
                               params={'posSide': 'Long'})

client.cancel_order(response['id'], "XRP/USDT:USDT", params={'posSide': 'Hedged'})
```
Traceback (most recent call last):

  Cell In[32], line 1
    client.cancel_order(response['id'], ticker, params={'posSide': 'Hedged', 'stop': True})

  File ~\anaconda3\lib\site-packages\ccxt\phemex.py:2484 in cancel_order
    response = getattr(self, method)(self.extend(request, params))

  File ~\anaconda3\lib\site-packages\ccxt\base\types.py:25 in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2839 in request
    return self.fetch2(path, api, method, params, headers, body, config)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2836 in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:601 in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File ~\anaconda3\lib\site-packages\ccxt\phemex.py:4006 in handle_errors
    raise ExchangeError(feedback)  # unknown message

ExchangeError: phemex {"code":39999,"msg":"Error in cancel order","data":null}

**Comment by carlosmiei** [comment]
Hello @Tomas-MP, I will take a look and revert as soon as possible.

**Comment by carlosmiei** [comment]
@Tomas-MP Ok, I think you just need to fix the provided `posSide` parameter, it should be the same value as the one used to create the order, `Long/Short` in this case. 

Example:
```

➜  ccxt git:(master) ✗ n phemex cancelOrder "518ecf7f-63d6-456e-9d3b-e798eb8540a9" "XRP/USDT:USDT" '{"posSide":"Long"}' --sandbox --verbose
CCXT v3.0.97
phemex.cancelOrder (518ecf7f-63d6-456e-9d3b-e798eb8540a9, XRP/USDT:USDT, [object Object])

ResponseBody:
 {"code":0,"msg":"","data":{"bizError":0,"orderID":"518ecf7f-63d6-456e-9d3b-e798eb8540a9","clOrdID":"ccxt20221efb517314fdaf15","symbol":"XRPUSDT","side":"Buy","actionTimeNs":1683555840898120475,"transactTimeNs":1683555840898120475,"orderType":"Limit","priceRp":"0.4","orderQtyRq":"30","displayQtyRq":"30","timeInForce":"GoodTillCancel","reduceOnly":false,"closedPnlRv":"0","closedSizeRq":"0","cumQtyRq":"0","cumValueRv":"0","leavesQtyRq":"30","leavesValueRv":"12","stopDirection":"UNSPECIFIED","stopPxRp":"0","trigger":"UNSPECIFIED","pegOffsetValueRp":"0","pegOffsetProportionRr":"0","execStatus":"PendingCancel","pegPriceType":"UNSPECIFIED","ordStatus":"New","execInst":"None","takeProfitRp":"0","stopLossRp":"0"}} 
```

**Comment by Tomas-MP** [comment]
@carlosmiei this indeed works, I was confused as the docstring in the method says either 'Hedged' or 'OneWay' or 'Merged'.

**Comment by carlosmiei** [comment]
> @carlosmiei this indeed works, I was confused as the docstring in the method says either 'Hedged' or 'OneWay' or 'Merged'.

You're right that is wrong, will update the docs

**Comment by Tomas-MP** [comment]
I did some more testing , it seems that using "Long" or "Short" does not make a difference as it just cancels the order in general irrespective of the side.

**Comment by carlosmiei** [comment]
> I did some more testing , it seems that using "Long" or "Short" does not make a difference as it just cancels the order in general irrespective of the side.

Makes total sense then... 😅
