### ISSUE TITLE
Kucoin signature verification failed with createOrder, cancelOrder

### ISSUE THREAD

**Issue by orrelln** [ccxt/ccxt#1784]
- OS: ubuntu and windows
- Programming Language version: python 3.5
- CCXT version: 10.1004
- Exchange: kucoin
- Method: create_order

On kucoin, since today, whenever I attempt to make an order I get signature verification failed. I'm not sure the cause as it occurs on new api keys as well as on different operating systems.

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/issues/1750

Let us know if this does not help.

**Comment by orrelln** [comment]
'KC-API-NONCE': '1517867044443'
ccxt.base.errors.AuthenticationError: kucoin {"timestamp":1517867044445,"msg":"Signature verification failed","code":"UNAUTH","success":false}
This is on ubuntu, the nonce is two seconds different from the timestamp of the error

Then, I created a new key on windows and synced the clock.
'KC-API-NONCE': '1517867276578'
kucoin {"code":"UNAUTH","msg":"Signature verification failed","success":false,"timestamp":1517867276657}
The clock is synced to UTC. I'm really confused as this issue just started happening today.

**Comment by kroitor** [comment]
> Then, I created a new key on windows and synced the clock.

How much time has passed between the two tests?

1517867044445 - 1517867276578 = -232133 == 232 seconds. That's a big difference (almost 4 minutes).

> The clock is synced to UTC. 

How do you know that?

**Comment by orrelln** [comment]
I modified the registry through the method you had provided. However, that is beside the point as my ubuntu nonce was very close. Is it possible that it's a signature calculation problem?

**Comment by orrelln** [comment]
Looking into this issue further, it might be a kucoin infrastructure issue. I ran the code no problem, made a change to my script and then the issue started happening.

**Comment by kroitor** [comment]
@orrelln are you using any rate-limiting in your script? Can you show a minimal, but a complete snippet to reproduce the issue?

https://github.com/ccxt/ccxt/blob/master/examples/py/basic-rate-limiting.py

**Comment by orrelln** [comment]
I was previously not using rate-limiting, but have enabled it. It produced no difference in behavior.
To reproduce the issue would to just set up API keys and create an order. I'm not doing anything funky by any means and do not have an issue getting public API information. Once I try to perform any sort of private API calls I get errors.

**Comment by kroitor** [comment]
@orrelln does a simple fetch_balance (after setting the API keys) work for you?

**Comment by orrelln** [comment]
Actually, fetch balance does work just fine. However, attempting to cancel orders or performing trades does not.

**Comment by kroitor** [comment]
@orrelln ok, so it's not a signature problem, but most likely a parameter problem with certain calls. Thanks for the info, I'll look into it and will fix it hopefully soon.

**Comment by wannesdemaeght** [comment]
Cancel order and create order work fine here...
Could you provide us with your code to create or cancel an order?

**Comment by orrelln** [comment]
You can close this. This is an account related problem that has nothing to do with ccxt. I ran the same script on a different account and was able to make trades. Thank you for the patience and trying to help.

**Comment by mcgalvao** [comment]
@orrelln, I have the same problem with my account. But it happens often, like one or twice a day. Did you manage to solve it?

**Comment by jayarjo** [comment]
If it is intermittent issue then you guys might not be sorting params in a proper way.
