### ISSUE TITLE
Phemex set_leverage not working for USDT perpetual contracts

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#17855]
### Operating System

Windows 10

### CCXT Version

3.0.98

### Description

It is not possible to change the margin mode and leverage for USDT pairs although it is possible from the API documentation. See code below to raise the issue. 

### Code

```
  
import ccxt
client = ccxt.phemex({'apiKey': '', 'secret': ''})

client.set_margin_mode('cross', "XRP/USDT:USDT", params={'leverage': 15})
```
Traceback (most recent call last):

  Cell In[4], line 1
    client.set_margin_mode('cross', ticker, params={'leverage': leverage})

  File ~\anaconda3\lib\site-packages\ccxt\phemex.py:3529 in set_margin_mode
    raise BadSymbol(self.id + ' setMarginMode() supports swap(non USDT based) contracts only')

BadSymbol: phemex setMarginMode() supports swap(non USDT based) contracts only

**Comment by Tomas-MP** [comment]
@carlosmiei I checked some more, the issue is that for "BTC/USD:USD" it does work, nevertheless for "BTC/USDT:USDT" it does not somehow. So I am not sure which endpoint you guys used but I would not get the logic if the exchange allows it for USD perps but not USDT perps. 

What I could find in the documentation is this endpoint: https://phemex-docs.github.io/#set-leverage. Which does not mention margin mode though.

**Comment by Tomas-MP** [comment]
@carlosmiei tried that as well but then I am getting this error: 

 ExchangeError: phemex {"code":20004,"msg":"TE_ERR_INCONSISTENT_POS_MODE","data":null}
 
 I want to change both leverage and margin to 'cross' margin, but not sure whether this is even possible for USDT perps?

**Comment by carlosmiei** [comment]
@Tomas-MP I merged an update that allows you to set leverage in the `hedged` mode by doing `phemex.set_leverage(6,"LTC/USDT:USDT", {"hedged":true}) `


https://github.com/ccxt/ccxt/pull/17998

**Comment by kroitor** [comment]
Closing it for now, feel free to reopen it or just ask further questions here if any.

**Comment by samchaaa** [comment]
Is it possible to set/unset hedged mode via the API? 
I'm trying to make an order in something I've never ordered before, so I got: 
```python
ExchangeError: phemex {"code":20004,"msg":"TE_ERR_INCONSISTENT_POS_MODE","data":null}
``` 

I thought this was because I hadn't set leverage yet, so I tried the method above and got the same error.

**Comment by germangar** [comment]
Try .set_position_mode( False, [symbol] )
I think phemex has it.
