### ISSUE TITLE
Kraken Order Error | decimal.InvalidOperation: [<class 'decimal.DivisionImpossible'>]

### ISSUE THREAD

**Issue by Quirky-Fox** [ccxt/ccxt#17864]
### Operating System

Linux (Amazon Linux 2)

### Programming Languages

python

### CCXT Version

3.0.98

### Description

Python version:
3.8.16

When trying to create an order on Kraken, no matter the amount provided, the error is consistently:

```python
decimal.InvalidOperation: [<class 'decimal.DivisionImpossible'>]
```

Full error log:

```python
  File "<stdin>", line 1, in <module>
File "/var/app/venv/staging-LQM1lest/lib64/python3.8/site-packages/ccxt/base/exchange.py", line 3323, in create_market_buy_order
    return self.create_order(symbol, 'market', 'buy', amount, None, params)
  File "/var/app/venv/staging-LQM1lest/lib64/python3.8/site-packages/ccxt/kraken.py", line 1202, in create_order
    'volume': self.amount_to_precision(symbol, amount),
  File "/var/app/venv/staging-LQM1lest/lib64/python3.8/site-packages/ccxt/base/exchange.py", line 3341, in amount_to_precision
    result = self.decimal_to_precision(amount, TRUNCATE, market['precision']['amount'], self.precisionMode, self.paddingMode)
  File "/var/app/venv/staging-LQM1lest/lib64/python3.8/site-packages/ccxt/base/decimal_to_precision.py", line 77, in decimal_to_precision
    missing = abs(dec) % precision_dec
decimal.InvalidOperation: [<class 'decimal.DivisionImpossible'>]
````

### Code

```python
import ccxt

kraken = ccxt.kraken(
    {
        "apiKey": "kraken_key",
        "secret": "kraken_secret",
        "enableRateLimit": True,
        "rateLimit": 500,
    }
)
kraken.verbose = True
kraken.loadMarkets()
kraken.createMarketBuyOrder("USDTZUSD", 100)
```

**Comment by Quirky-Fox** [comment]
A little more information after some fiddling around on my side:

It works fine on my Mac, but strange that it's not working in a virtual environment.

Playing with the function that causes the error (decimal_to_precision) results in more oddities. For the relevant symbol on Kraken, the precision is 1e-8.

```
kraken.decimal_to_precision(100, precision=1e-8)
```
Results in the error as expected:

> decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]

But, setting the precision to an integer anywhere up to 5 works:
```
kraken.decimal_to_precision(100, precision=5)
```
Results in:
> '100'

But then breaks again at 6 and above:
```
kraken.decimal_to_precision(100, precision=6)
```
Results in:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/app/venv/staging-LQM1lest/lib64/python3.8/site-packages/ccxt/base/decimal_to_precision.py", line 105, in decimal_to_precision
    precise = '{:f}'.format(dec.quantize(power_of_10(precision)))  # ROUND_HALF_EVEN is default context
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]

And the precision value that works, varies based on the amount applied - precision 5 and amount 1000 breaks again. I also can't get any x-value in 1e-x to work this way.

**Comment by samgermain** [comment]
> Playing with the function that causes the error (decimal_to_precision) results in more oddities. For the relevant symbol on Kraken, the precision is 1e-8.

 if the precision mode is DECIMAL_PLACES or SIGNIFICANT_DIGITS then the precision must be an integer, it does not make sense to have 0.5 decimal places/significant digits
 
 ----
 
 All the other problems you mentioned look like they're working fine for me, maybe they've been fixed since the issue was posted
 
 Using this script, I got the output below
 
 ```python
 # -*- coding: utf-8 -*-

import json
import ccxt  # noqa: E402
from pprint import pprint

keys = json.load(open('../keys.local.json'))
exchange = ccxt.kraken({
    "apiKey": keys['kraken']['apiKey'],
    "secret": keys['kraken']['secret'],
    "enableRateLimit": True,
    "rateLimit": 500,
})
# exchange.verbose = True

exchange.loadMarkets()
order = exchange.createMarketBuyOrder("USDTZUSD", 5)

pprint(order)
pprint(exchange.decimal_to_precision(100, precision=6))
pprint(exchange.decimal_to_precision(1000, precision=5))
```
 
 ```
{'amount': 5.0,
 'average': None,
 'clientOrderId': None,
 'cost': None,
 'datetime': None,
 'fee': None,
 'fees': [],
 'filled': None,
 'id': 'OX4JRD-GQMFC-QUZIFC',
 'info': {'descr': {'order': 'buy 5.00000000 USDTUSD @ market'},
          'txid': ['OX4JRD-GQMFC-QUZIFC']},
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'postOnly': False,
 'price': None,
 'reduceOnly': None,
 'remaining': None,
 'side': 'buy',
 'status': None,
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': 'USDT/USD',
 'takeProfitPrice': None,
 'timeInForce': 'IOC',
 'timestamp': None,
 'trades': [],
 'triggerPrice': None,
 'type': 'market'}
'100'
'1000'
```
