### ISSUE TITLE
Binance: OrderId doesn't exist

### ISSUE THREAD

**Issue by chhudson** [ccxt/ccxt#1786]
- OS: Ubuntu 17.04
- Programming Language version: Python 3.6.4
- CCXT version: 1.10.981
- Exchange: Binance
- Method: fetch_order

Hi and thanks for this wonderful repo :)

Issue: It seems that on very rare occasions an order is placed but the orderID does not exist on the exchange yet.

![image](https://user-images.githubusercontent.com/11526817/35836474-01d57622-0aa6-11e8-98e1-52e6878f5822.png)

What I have tried so far: Adding a 2-second delay after the order has been placed.

What the code is doing:
My script takes all the of available pairs for BTC and checks the spreads. I then take the coin with the largest spread and then buy and sell at those the current bid/ask. The image above shows a successful trade and then it placed the other buy and (i think) it is not finding the orderID after two seconds.

Partial piece of code:
```
# Place buy order
BUY_ORDER = CLIENT.create_limit_buy_order(SYMBOL, ORDER_AMOUNT, PERCENT_BUY)
time.sleep(2)
BUY_ORDER_ID = BUY_ORDER['id'] <-- Error either occurs here
BUY_ORDER_QTY = BUY_ORDER['amount']

# Fetch order stats
BUY_ORDER_CHECK = CLIENT.fetch_order(BUY_ORDER_ID, symbol=SYMBOL) <-- Or here
BUY_ORDER_CHECK_STATUS = BUY_ORDER_CHECK['status']
BUY_ORDER_CHECK_QTY = BUY_ORDER_CHECK['amount']
BUY_ORDER_CHECK_AMOUNT_FILLED = BUY_ORDER_CHECK['filled']
```

If you'd to take a better look at whats going on just PM me and I'll add you to the private repo. This is not urgent (happens maybe once per day) but I would like to get this solved since I want to scale this across multiple VPS and exchanges.

Thanks for any help :)

**Comment by mkutny** [comment]
Actually, what exact errors do you have?

The issue is that once `create_limit_buy_order` call completes you have all params of `BUY_ORDER` populated. Whether you place a time delay does not matter.

Also, two error places which you pointed two are different. The first one is just a property lookup, the second one is a network call. So the errors should be different too.

**Comment by kroitor** [comment]
@chhudson hi! The answer from @mkutny is correct, you should handle the exceptions like described here: https://github.com/ccxt/ccxt/wiki/Manual#error-handling
Also, set `verbose` mode on your exchange instance (add `CLIENT.verbose = True` before creating  an order). This will help you see the reasons behind the failures and from there it should be obvious on how to handle them properly. Let us know if this does not help.

@mkutny thx again!

**Comment by chhudson** [comment]
@mkutny @kroitor Thanks for pointing me in the right direction :) I also updated ccxt package and that seems to have helped as well. I'll keep this bookmarked for future reference.

Thanks again and thanks for the software.

**Comment by chhudson** [comment]
@mkutny @kroitor let me know if I just need to open a new issue. I did some basic exception handling here it works great on bittrex :). But it seems, in binance, that once the order id isn't found it just continues to loop and never finds it. I don't believe there is anything wrong with the repo.

I know its basic but I really just wanted a catch-all. Should I possibly try to reload the markst with `.load_markets()`? Even though maintenance happened last night the ID should still be found right?

```
while True:
    try:
        BUY_ORDER_CHECK = CLIENT.fetch_order(BUY_ORDER_ID, symbol=SYMBOL)
        break
    except (ccxt.NetworkError, ccxt.ExchangeError):
        print("Network Error: DDoSProtection, RequestTimeout, ExchangeNotAvailable")
        print("Exchange Error: NotSupported, AuthenticationError, InvalidNonce, InsufficientFunds, InvalidOrder, OrderNotFound")
        time.sleep(5)
```

**Comment by mkutny** [comment]
What exact error do you have?

**Comment by chhudson** [comment]
OrderNotFound

**Comment by chhudson** [comment]
@mkutny exactly. On bittrex if there is any error it eventually tracks everything down and continues through the rest of the script. This seems to only occur on Binance. I do know that on Binance they use two order ids. One that can be manually set and one that is set by binance.

**Comment by mkutny** [comment]
> On bittrex if there is any error it eventually tracks everything down and continues through the rest of the script.

You know, although it goes somewhat beyond ccxt scope I'm going to save you a bit of time.

In your code snippet try to put the order id which surely does not exist. Something like
```
        BUY_ORDER_CHECK = CLIENT.fetch_order(1, symbol=SYMBOL)
```

Try to run it on bittrex and see how quick it will track everything down.

**Comment by chhudson** [comment]
Heres what the log shows for Binance.

DEBUG:urllib3.connectionpool:https://api.binance.com:443 "DELETE /api/v3/order HTTP/1.1" 400 None

**Comment by mkutny** [comment]
Ok, let's summarise.

Binance returns http status code 400 when you try to cancel non-existent order.
Receiving this code ccxt throws `OrderNotFound` exception.

Is anything wrong with this?

**Comment by vigrobizz** [comment]
I just ran into this issue on Binance, it's something on their side...
Ran this like 5 times after placing a stop-limit order: exchange.fetch_order(9954671, "ICX/USDT")
Every time it gave me {"code":-2013,"msg":"Order does not exist."} error.
Checked my order history on Binance website and it wouldn't show my last couple of trades even after several refreshes.  Probably 1-2 mins later it started showing it.
Then I ran the above command again and the order was found this time.
Sometimes when Binance is under a lot of load, it can act up.  This was all while BTC jumped $350 in just a few mins, so I can imagine their servers were fully loaded...

Thank you guys for all your work here!

**Comment by kroitor** [comment]
@vigrobizz thx for reporting! Indeed, we've seen the quality of service degrade during peak loads, therefore the website and/or the exchange API are subject to a "lag" that manifests itself with a delayed update of the status of your order. Unfortunately, this isn't something we can workaround on our side, as you understand. Thx again for your participiation!
