### ISSUE TITLE
Binance default precisions computed from https://www.binance.com/api/v1/exchangeInfo

### ISSUE THREAD

**Issue by aloysius-pgast** [ccxt/ccxt#1787]
- OS: Linux
- Programming Language version: NodeJS v8.9.4
- CCXT version: 1.10.1006
- Exchange: Binance
- Method: fetchMarkets

Hi. I noticed that current implementation for _Binance_ assumes that https://www.binance.com/api/v1/exchangeInfo returns _precisions_ values as _float_

From [js/binance.js](https://github.com/ccxt/ccxt/blob/master/js/binance.js)
```
let precision = {
    'base': market['baseAssetPrecision'],
    'quote': market['quotePrecision'],
    'amount': market['baseAssetPrecision'],
    'price': market['quotePrecision']
};
this.extend (this.fees['trading'], {
...
    'limits': {
        'amount': {
            'min': lot,
            'max': undefined,
        },
        'price': {
            'min': -1 * Math.log10 (precision['price']),
            'max': undefined,
        },
        'cost': {
            'min': lot,
            'max': undefined,
        }
    }
}
```
But _baseAssetPrecision_ & _quotePrecision_ are already provided by _Binance_ as _integers_

From [Binance](https://www.binance.com/api/v1/exchangeInfo) :

```
{
    "symbol":"BTCUSDT",
    "status":"TRADING",
    "baseAsset":"BTC",
    "baseAssetPrecision":8,
    "quoteAsset":"USDT",
    "quotePrecision":8,
    "orderTypes":[
        "LIMIT",
        "LIMIT_MAKER",
        "MARKET",
        "STOP_LOSS_LIMIT",
        "TAKE_PROFIT_LIMIT"
    ],
    "icebergAllowed":true,
    "filters":[
        {
            "filterType":"PRICE_FILTER",
            "minPrice":"0.01000000",
            "maxPrice":"10000000.00000000",
            "tickSize":"0.01000000"
        },
        {
            "filterType":"LOT_SIZE",
            "minQty":"0.00000100",
            "maxQty":"10000000.00000000",
            "stepSize":"0.00000100"
        },
        {
            "filterType":"MIN_NOTIONAL",
            "minNotional":"10.00000000"
        }
    ]
}
```
I don't know if there was a change on _Binance_ side recently. Problem is eventually fixed because _ccxt_ then update precisions from _filters_ but for consistency, maybe computation of _default precisions_ should be updated to use information returned from _Binance_, without applying _Math.log10_

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

Let us know if this does not answer your question. Thx!
