### ISSUE TITLE
XT.COM

### ISSUE THREAD

**Issue by althawadi7** [ccxt/ccxt#17876]
### Code

```
  

```

**Comment by althawadi7** [comment]
Xt.com not working with ccxt, its calling fapi instead on sapi, we tried many ways, please let us know how to fix it and call the spot market, : ERROR - Network error occurred: xt GET https://fapi.xt.com/future/market/v1/public/symbol/list

**Comment by althawadi7** [comment]
Xt.com not working with ccxt, its calling fapi instead on sapi, we tried many ways, please let us know how to fix it and call the spot market, : ERROR - Network error occurred: xt GET https://fapi.xt.com/future/market/v1/public/symbol/list

**Comment by carlosmiei** [comment]
Hello @althawadi7,
CCXT only calls that endpoint once to load all the markets (spot+swap) available, so you don't need to worry about it.

Regarding the network connection, do you get the same error when opening `https://fapi.xt.com/future/market/v1/public/symbol/list` in the browser?

**Comment by althawadi7** [comment]
Hey there, thanks for your reply, no I don't get any errors when opening it, but I'm getting the same error when I try to run it on CMD and the bot never works

**Comment by carlosmiei** [comment]
@althawadi7 In that case, the problem is most likely with your internet connection through CMD and not XT, I would suggest by debugging this network issue first.
