### ISSUE TITLE
plz add bingx exchange

### ISSUE THREAD

**Issue by Vain10** [ccxt/ccxt#17878]
### Exchange Name

Bingx

### URL of the Exchange

https://bingx.com

### URL of the Exchange's API docs

https://github.com/BingX-API/docs

### Why should this exchange be implemented?

this exchange has been choosed as the best exchange in TV for 2 years since it has good performance especially with bots and signal trading apps. and im testing it for 6 months, it has much better performance than kucoin

**Comment by Tomas-MP** [comment]
I think this has already been requested multiple times, nevertheless would also be happy to see it added!
