### ISSUE TITLE
XT.com ExchangeErrors which should be raised as NetworkError

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#17882]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

3.0.98

### Description

Sometimes when making a request I get a 504 GATEWAY_TIMEOUT error or connection refused error (which is an ExchangeError), now I am wondering what the best way is to catch this issue and whether it is solvable as well. Maybe it is possible to throw these errors as a NetworkError instead? 

### Code

```
  
client = ccxt.xt({'apiKey': "", ""})
client.fetch_balance()
```
Results in either: 

ccxt.base.errors.ExchangeError: xt {"returnCode":1,"msgInfo":"failure","error":{"code":"400","msg":"504 GATEWAY_TIMEOUT \"Response took longer than timeout: PT5S\"; nested exception is org.springframework.cloud.gateway.support.TimeoutException: Response took longer than timeout: PT5S"},"result":null}

or: 

ccxt.base.errors.ExchangeError: xt {"returnCode":1,"msgInfo":"failure","error":{"code":"400","msg":"Connection refused: /10.0.26.71:8080"},"result":null}

or: 

ccxt.base.errors.ExchangeError: xt {"returnCode":1,"msgInfo":"failure","error":{"code":"400","msg":"connection timed out: /10.0.63.70:8080"},"result":null}

**Comment by carlosmiei** [comment]
Hello @Tomas-MP, you're right I will add it asap
