### ISSUE TITLE
Bitget fetchOrder returning undefined values

### ISSUE THREAD

**Issue by FelipeJz** [ccxt/ccxt#17900]
### Operating System

Windows, Linux

### Programming Languages

JS

### CCXT Version

3.0.101

### Description

The fetchOrder method for Bitget is returning undefined values.
For what i could see the "safeValue" type is expecting an object but the response from the API is a string, resulting in the undefined values.

### Code

```
  {
  info: undefined,
  id: undefined,
  clientOrderId: undefined,
  timestamp: undefined,
  datetime: undefined,
  lastTradeTimestamp: undefined,
  symbol: 'USDC/USDT',
  type: undefined,
  timeInForce: undefined,
  postOnly: undefined,
  side: undefined,
  price: undefined,
  stopPrice: undefined,
  triggerPrice: undefined,
  average: undefined,
  cost: undefined,
  amount: undefined,
  filled: undefined,
  remaining: undefined,
  status: undefined,
  fee: undefined,
  trades: [],
  fees: [],
  reduceOnly: undefined
}


```

**Comment by sc0Vu** [comment]
Hi @FelipeJz 

I can fetch order through api, would you like to paste verbose log?

**Comment by FelipeJz** [comment]
It does work though the API, the response is a string. 
The simple solution is using the same conditional as in fetchOpenOrders.

`if (typeof response === 'string') {
            response = JSON.parse(response);
        }`
 
That way it works perfectly, i would pull request myself but i don't have my environment set up.

Thanks

**Comment by FelipeJz** [comment]
Didn't mean to close that, sorry.

**Comment by sc0Vu** [comment]
@FelipeJz

I'm curious about why the response is string...... From my side, the response is always object.

**Comment by daan-ost** [comment]
I have the same issue in php.
fetch_order is ok when the order has status new or cancelled. But once filled it gives an error:
Fatal error: Uncaught TypeError: ccxt\Exchange::safe_number(): Argument #1 ($obj) must be of type array, null given
bitget.php line 2385 and 2386
    'stopPrice' => $this->safe_number($order, 'triggerPrice'),
            'triggerPrice' => $this->safe_number($order, 'triggerPrice'),

not sure if it safe to share the verbose log...or DM? I do see my filled order in the verbose log.

**Comment by sc0Vu** [comment]
Hi @daan-ost, 

Thanks! Now, I can reproduce the bug. @FelipeJz like you said, the response was string......
