### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class "React\Promise\Deferred"

### ISSUE THREAD

**Issue by andreescocard** [ccxt/ccxt#17911]
### Operating System

Linux

### Programming Languages

php

### CCXT Version

1.95.1

### Description

Running on a ubuntu server with PHP 8.1.2-1ubuntu2.11 version i am getting this error after composer update command (upgrading CCXT from 1.53 to 1.95.1).

On 1.53 CCXT version in ubuntu i get another error too "PHP Fatal error:  Uncaught ccxt\BadSymbol: binance does not have market symbol BTC/BRL" but this doesn't make sense, this symbol exists.

On a Windows environment with php 8.1.10 with CCXT version 1.53 i can make my code work.

**Comment by carlosmiei** [comment]
Hello @andreescocard I noticed you're running an old version of ccxt. Is it possible to update to the latest and run `composer update` again?

**Comment by andreescocard** [comment]
I did that.
My composer.json:
`{
    "require": {
        "ccxt/ccxt": "3.0.105"
    }
}
`
Run composer install and composer update after.

Full error:

`Fatal error:  Uncaught Error: Class "React\Promise\Deferred" not found in /mypath/vendor/ccxt/ccxt/php/pro/Future.php:9`

**Comment by andreescocard** [comment]
Forget it, i fixed it adding 

`require 'vendor/autoload.php';` on my script.

I thought that only adding ccxt script would work but i needed to add the autoload.
