### ISSUE TITLE
watch_trades broken due to filterByLimit implementation

### ISSUE THREAD

**Issue by kizmonavt** [ccxt/ccxt#17919]
### Operating System

Linux

### Programming Languages

python

### CCXT Version

3.0.101

### Description

While testing binance's watch_trades method I noticed that in some cases watch_trades method was returning wrong trade updates. Turns out that if your first order executes immediately with two trades, watch_trades returns the first trade 2 times while the second trade is never returned.

Closer inspection revealed that this is because trades have the same timestamp which causes
```self.filter_by_symbol_since_limit(trades, None, None, 1)``` from watch_trades to return the first trade because it treats the trades arrey as descending.

snippet from base exchange reveals that when array's first and last timestamp are the same the array is treated as descending by default due to first < last instead of first <= last which would make more sense, since ascending is the default when comparison is not possible.
 
```
    // METHODS BELOW THIS LINE ARE TRANSPILED FROM JAVASCRIPT TO PYTHON AND PHP
    filterByLimit(array, limit = undefined, key = 'timestamp') {
        if (this.valueIsDefined(limit)) {
            const arrayLength = array.length;
            if (arrayLength > 0) {
                let ascending = true;
                if ((key in array[0])) {
                    const first = array[0][key];
                    const last = array[arrayLength - 1][key];
                    if (first !== undefined && last !== undefined) {
                        ascending = first < last; // true if array is sorted in ascending order based on 'timestamp'
                    }
                }
                array = ascending ? this.arraySlice(array, -limit) : this.arraySlice(array, 0, limit);
            }
        }
        return array;
    }
```
I noticed multiple semi-related issues on this repo and some of them might be caused by this discrepancy. 

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @kizmonavt, 
Thanks for reporting it, we will investigate this issue as soon as possible.
