### ISSUE TITLE
Huobi {"status":"error","err_code":1510,"err_msg":"Since you are the merged cross and isolated margin account for USDT-M futures , you cannot use the APIs. If you need to use, please change the account type via /linear-swap-api/v3/swap_switch_account_type

### ISSUE THREAD

**Issue by donewiththedollar** [ccxt/ccxt#17910]
### Operating System

Linux

### Programming Languages

python

### CCXT Version

3.0.102

### Description

I try to place an order using a new account on Huobi with a fresh API key, I am able to retrieve orderbook information on a symbol just fine and current position information.

I'm not sure what is going on here at this point, I have reached out to Huobi about this as it seems odd after reading through their documentation as @carlosmiei was pointing out this merge should not impact new users but this account is fresh.

Props to @carlosmiei for resolving the balance issues with unified, but now I am not sure where to go from here after receiving this error message.

### Code

In my exchange class

```
class Exchange:
    def __init__(self, exchange_id, api_key, secret_key, passphrase=None):
        self.exchange_id = exchange_id
        self.api_key = api_key
        self.secret_key = secret_key
        self.passphrase = passphrase
        self.name = exchange_id
        self.initialise()
        self.symbols = self._get_symbols()

    def initialise(self):
        exchange_class = getattr(ccxt, self.exchange_id)
        exchange_params = {
            "apiKey": self.api_key,
            "secret": self.secret_key,
        }
        if self.exchange_id.lower() == 'huobi':
            exchange_params['options'] = {
                'defaultType': 'swap',
                'defaultSubType': 'linear',
            }
        if self.passphrase:
            exchange_params["password"] = self.passphrase

        self.exchange = exchange_class(exchange_params)
```

```
      def create_contract_order_huobi(self, symbol, order_type, side, amount, price=None, params={}):
        return self.exchange.create_contract_order(symbol, order_type, side, amount, price, params)

```

In my huobi hedge strategy

```
            print(f"Testing trade")
            self.exchange.create_contract_order_huobi(parsed_symbol_swap, 'limit', 'buy', amount, price=best_bid_price)
```

Result:

```
Testing trade
An error occurred while executing the strategy: huobi {"status":"error","err_code":1510,"err_msg":"Since you are the merged cross and isolated margin account for USDT-M futures , you cannot use the APIs. If you need to use, please change the account type via /linear-swap-api/v3/swap_switch_account_type","ts":1684015912159}
```

**Comment by Dan-krm** [comment]
To resolve this issue you can run the specified endpoint with the required `account_type` parameter using the Implicit API, then you should stop getting that error.

Specified Endpoint: https://huobiapi.github.io/docs/usdt_swap/v1/en/#account-type-change
Implicit API: https://docs.ccxt.com/#/?id=implicit-api
```
python3 examples/py/cli.py huobi contractPrivatePostLinearSwapApiV3SwapSwitchAccountType '{"account_type":1}'
```
```
huobi.contractPrivatePostLinearSwapApiV3SwapSwitchAccountType({'account_type': 1})

{
  code: '200',
  msg: 'ok',
  data: { account_type: '1' },
  ts: '1684028016717'
}
```

**Comment by donewiththedollar** [comment]
`    def switch_account_type_huobi(self, account_type: int):
        if self.exchange_id.lower() != 'huobi':
            print("This operation is only available for Huobi.")
            return

        body = {
            "account_type": account_type
        }

        response = self.exchange.contractPrivatePostLinearSwapApiV3SwapSwitchAccountType(body)
        return response
`

`

            try:
                self.exchange.switch_account_type_huobi(1)
                time.sleep(0.05)
                print(f"Changed account type")
            except Exception as e:
                print(f"Error in switching account type {e}")
`

It works :) Thank you!
