### ISSUE TITLE
Gate.io fetchmytrades swaps time range issue

### ISSUE THREAD

**Issue by speedingonatram** [ccxt/ccxt#17938]
### Operating System

Windows

### Programming Languages

python

### CCXT Version

3.0.106

### Description

For fetching the trading history of swaps, we're using this function:

https://github.com/ccxt/ccxt/blob/5c5202be8949c9938e1b9b5074a6b27c0161579b/ts/src/gate.ts#L2791

but this function doesn't support retrieving trades by time range.

Instead we should use this function: (notice it takes 'from' and 'to' as parameters)

https://www.gate.io/docs/developers/apiv4/en/#list-personal-trading-history-by-time-range

Thanks

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @speedingonatram,
Thanks for letting us know, we will test the endpoint you're pointing to and update the implementation asap.
