### ISSUE TITLE
Bitmart unable to use fetch_ohlcv

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#17939]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

3.0.102

### Description

When trying to fetch historical data it throws an error (see example below to get the error). 

### Code

```
  
client = ccxt.bitmart()
ticker = "BTCUSDT"

timeframe = list(client.describe()['timeframes'].values())[-2]

new = General.request(lambda: client.fetch_ohlcv(
    ticker, timeframe, since=None, limit=10000))

```
Traceback (most recent call last):

  Cell In[12], line 3
    new = General.request(lambda: client.fetch_ohlcv(

  File ~\OneDrive\Documenten\Github\cryptocurrency\data2\functions\general.py:61 in request
    result = func_timeout(60, method)

  File ~\anaconda3\lib\site-packages\func_timeout\dafunc.py:108 in func_timeout
    raise_exception(exception)

  File ~\anaconda3\lib\site-packages\func_timeout\py3_raise.py:7 in raise_exception
    raise exception[0] from None

  Cell In[12], line 3 in <lambda>
    new = General.request(lambda: client.fetch_ohlcv(

  File ~\anaconda3\lib\site-packages\ccxt\bitmart.py:1251 in fetch_ohlcv
    duration = self.parse_timeframe(timeframe)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:1464 in parse_timeframe
    amount = int(timeframe[0:-1])

TypeError: 'int' object is not subscriptable

**Comment by Tomas-MP** [comment]
@carlosmiei what is the best way to do this?

**Comment by carlosmiei** [comment]
> @carlosmiei what is the best way to do this?

@Tomas-MP `exchange.verbose = True` before `fetch_ohlcv`  (ideally after loading markets to avoid polluting the log too much)

Example:
```Python
await exchange.log_markets()
exchange.verbose = True
ohlcv = client.fetch_ohlcv(
    ticker, timeframe, since=None, limit=10000))
```
Then, you just need to redirect the stdout to a file:

```
python script.py > out.txt
```

**Comment by Tomas-MP** [comment]
[error.txt](https://github.com/ccxt/ccxt/files/11510657/error.txt)

Hopefully this is useful, could not manage to filter out the loading markets.

**Comment by carlosmiei** [comment]
> [error.txt](https://github.com/ccxt/ccxt/files/11510657/error.txt)
> 
> Hopefully this is useful, could not manage to filter out the loading markets.

@Tomas-MP Humm actually i think the problem is related to this line: `timeframe = list(client.describe()['timeframes'].values())[-2]` because it returns the exchange-specific timeframe instead of the unified one.

Can you try to do this instead: `list(exchange.describe()['timeframes'])[-2]`  (remove .values)

**Comment by Tomas-MP** [comment]
for t in list(client.describe()['timeframes'].values()):
    try: 
        client.fetch_ohlcv(ticker, t, since=None, limit=1000)
    except TypeError:
        print("Timeframe {} not working".format(t))
        
Timeframe 1 not working
Timeframe 3 not working
Timeframe 5 not working
Timeframe 15 not working
Timeframe 30 not working
Timeframe 45 not working
Timeframe 60 not working
Timeframe 120 not working
Timeframe 180 not working
Timeframe 240 not working
Timeframe 1440 not working
Timeframe 10080 not working
Timeframe 43200 not working

**Comment by carlosmiei** [comment]
> lient.describe()['timeframes'].values()):

@Tomas-MP did you check my previous message?

**Comment by Tomas-MP** [comment]
Awesome, it seems that the describe() method is organized a little bit different, for the other exchanges I can retrieve the largest timeframe this way: list(client.describe()['timeframes'].values())[-1]. Where for Bitmart it should be list(exchange.describe()['timeframes'])[-1].

**Comment by carlosmiei** [comment]
> Awesome, it seems that the describe() method is organized a little bit different, for the other exchanges I can retrieve the largest timeframe this way: list(client.describe()['timeframes'].values())[-1]. Where for Bitmart it should be list(exchange.describe()['timeframes'])[-1].

@Tomas-MP the thing is probably the other exchanges are correctly parsing exchange-specific and unified timeframes whereas bitmart is not but, rule of thumb, it is better to go with the unified approach whenever possible 🙂
