### ISSUE TITLE
CCXT Dotnet for C#

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#17953]
Hello, CCXT community!

We're excited to announce that as of 4.2.34  we merged the **C#/.net** version into master and released a stable version with WebSockets capabilities. It works very similarly to the other languages.

**Please make sure you use the capitalized version of the unified method (`CreateOrder` instead of `createOrder`, the latter is not typed)**

*Package: https://www.nuget.org/packages/ccxt/*

Examples:
```C#
using ccxt;
// REST
        var exchange = new ccxt.binance(new Dictionary<string, object>() {
            { "apiKey", "MY_API_KEY" },
            { "secret", "MY_SECRET" },
        });
        var order = await exchange.CreateOrder("LTC/USDT", "limit", "buy", 1, 50);
        var orderId = order.id;
        Console.WriteLine($"Order Id: {orderId}");
```
```C#
using ccxt.pro;
// WS
        var binance = new ccxt.pro.binance(new Dictionary<string, object>() { });
        var symbols = new List<string>() { "BTC/USDT", "ETH/USDT", "DOGE/USDT" };
        while (true)
        {
            var trades = await binance.WatchTradesForSymbols(symbols);
        }
    }
```

You can check some examples here: https://github.com/ccxt/ccxt/tree/master/examples/cs/examples

Thank you for using CCXT!

Yours, the CCXT Dev Team

[![Discord](https://img.shields.io/discord/690203284119617602?logo=discord&logoColor=white)](https://discord.gg/ccxt) [ ![Telegram](https://img.shields.io/badge/-announcements-red?color=white&logo=telegram&logoColor=blue)](https://t.me/ccxt_announcements) [![Telegram](https://img.shields.io/badge/-chat-red?color=white&logo=telegram&logoColor=blue)](https://t.me/ccxt_chat) [![Twitter Follow](https://img.shields.io/twitter/follow/ccxt_official.svg?style=social&label=CCXT)](https://twitter.com/ccxt_official)

**Comment by infrastructure-finvest-global** [comment]
Hi I wanted to ask does this include ccxt.pro

**Comment by carlosmiei** [comment]
> Hi I wanted to ask does this include ccxt.pro

@infrastructure-finvest-global It does now, please read the updated announcement.

**Comment by Muaytie23** [comment]
�3��!��6���"�x�ﰵ膖���`Fɫ�
	��膖���)��Q�W�s�+�7����J#��s�E�) ��nB0w��h%�{�
��7�zĝ�l�U���&�`�
��O,�oI��P���Ӂ������eU$�I;��(�������'�<�s�s��c�-�*p�
��yb}JdΘ��6�\fl���!{�v�xb)����f
��ܯ&���ꢫ�h	�)��t���܉�`��rl�G�ȸ��6ʆw�N�gK�'��M�m��\@_m!�K�F�.IzT9٠�-�e����1M��"��(����o�z��)c�ݐA��O�S"���Wl����ϵe���T~O�dC�߹���Ū4'��ē���4�x�u�mNr\꞉�(������
�W�V��uY�?�3�ӟ�Q	��.fQ�< �Qiz�m�p�I�	DC�Ars�J]�)�W�@:CwZa[�8w���U�?`b������Q�}�xf����g<�r���T�Q����kX�e���J3�� 13F�d�j_�;xg��(G�7Wk�����f��

**Comment by Muaytie23** [comment]
�3��!��6���"�x�ﰵ膖���`Fɫ�
	��膖���)��Q�W�s�+�7����J#��s�E�) ��nB0w��h%�{�
��7�zĝ�l�U���&�`�
��O,�oI��P���Ӂ������eU$�I;��(�������'�<�s�s��c�-�*p�
��yb}JdΘ��6�\fl���!{�v�xb)����f
��ܯ&���ꢫ�h	�)��t���܉�`��rl�G�ȸ��6ʆw�N�gK�'��M�m��\@_m!�K�F�.IzT9٠�-�e����1M��"��(����o�z��)c�ݐA��O�S"���Wl����ϵe���T~O�dC�߹���Ū4'��ē���4�x�u�mNr\꞉�(������
�W�V��uY�?�3�ӟ�Q	��.fQ�< �Qiz�m�p�I�	DC�Ars�J]�)�W�@:CwZa[�8w���U�?`b������Q�}�xf����g<�r���T�Q����kX�e���J3�� 13F�d�j_�;xg��(G�7Wk�����f��

**Comment by Muaytie23** [comment]
�3��!��6���"�x�ﰵ膖���`Fɫ�
	��膖���)��Q�W�s�+�7����J#��s�E�) ��nB0w��h%�{�
��7�zĝ�l�U���&�`�
��O,�oI��P���Ӂ������eU$�I;��(�������'�<�s�s��c�-�*p�
��yb}JdΘ��6�\fl���!{�v�xb)����f
��ܯ&���ꢫ�h	�)��t���܉�`��rl�G�ȸ��6ʆw�N�gK�'��M�m��\@_m!�K�F�.IzT9٠�-�e����1M��"��(����o�z��)c�ݐA��O�S"���Wl����ϵe���T~O�dC�߹���Ū4'��ē���4�x�u�mNr\꞉�(������
�W�V��uY�?�3�ӟ�Q	��.fQ�< �Qiz�m�p�I�	DC�Ars�J]�)�W�@:CwZa[�8w���U�?`b������Q�}�xf����g<�r���T�Q����kX�e���J3�� 13F�d�j_�;xg��(G�7Wk�����f��

**Comment by Muaytie23** [comment]
�3��!��6���"�x�ﰵ膖���`Fɫ�
	��膖���)��Q�W�s�+�7����J#��s�E�) ��nB0w��h%�{�
��7�zĝ�l�U���&�`�
��O,�oI��P���Ӂ������eU$�I;��(�������'�<�s�s��c�-�*p�
��yb}JdΘ��6�\fl���!{�v�xb)����f
��ܯ&���ꢫ�h	�)��t���܉�`��rl�G�ȸ��6ʆw�N�gK�'��M�m��\@_m!�K�F�.IzT9٠�-�e����1M��"��(����o�z��)c�ݐA��O�S"���Wl����ϵe���T~O�dC�߹���Ū4'��ē���4�x�u�mNr\꞉�(������
�W�V��uY�?�3�ӟ�Q	��.fQ�< �Qiz�m�p�I�	DC�Ars�J]�)�W�@:CwZa[�8w���U�?`b������Q�}�xf����g<�r���T�Q����kX�e���J3�� 13F�d�j_�;xg��(G�7Wk�����f��
