### ISSUE TITLE
Kraken since parameter not working

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#17956]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

3.0.102

### Description

When I try to retrieve historical data from the first datapoint by using since, it does only return the most recent data points. Not sure whether this data is not held available anymore by Kraken or it is a bug in CCXT. 

### Code

```
  
import ccxt
import pandas as pd

client = ccxt.kraken()

ticker = "BTC/USD"

timeframe = list(client.describe()['timeframes'])[-1]
new = client.fetch_ohlcv(ticker, timeframe, since=None, limit=720)

since = new[0][0]

new2 = client.fetch_ohlcv(ticker, '1m', since=since, limit=None)

print(pd.DataFrame(new2))
```
                 0        1        2        3        4         5
0    1684457280000  26843.6  26847.6  26843.6  26847.6  0.191179
1    1684457340000  26849.4  26859.4  26849.4  26859.3  0.007351
2    1684457400000  26858.6  26858.6  26852.2  26852.3  0.079152
3    1684457460000  26850.3  26851.4  26850.3  26851.4  0.081174
4    1684457520000  26850.9  26869.1  26850.9  26862.7  0.960731
..             ...      ...      ...      ...      ...       ...
715  1684500180000  26936.9  26942.7  26936.9  26940.9  0.827606
716  1684500240000  26942.3  26943.5  26934.2  26934.2  0.075863
717  1684500300000  26934.1  26938.9  26934.1  26937.2  0.122053
718  1684500360000  26934.0  26934.0  26925.1  26925.1  0.170578
719  1684500420000  26925.1  26925.1  26925.1  26925.1  0.067804

[720 rows x 6 columns]

**Comment by carlosmiei** [comment]
Hello @Tomas-MP,

I just tested and it seems to be working fine:

```Javascript
 n kraken fetchOHLCV "BTC/USD" "1m" 1684468680000
CCXT v3.1.2
kraken.fetchOHLCV (BTC/USD, 1m, 1684468680000)
2023-05-19T14:59:48.566Z iteration 0 passed in 1258 ms

1684468680000 | 26838.4 |   26839 | 26838.4 |   26839 |  0.53200642
1684468740000 | 26838.5 | 26839.5 | 26838.4 | 26838.4 |  0.03310865
1684468800000 | 26838.5 | 26838.5 | 26838.4 | 26838.5 |  0.01051721
```
Can you please provide a verbose log?

**Comment by Tomas-MP** [comment]
@carlosmiei the problem is with older data, so for example when I use since = 1483228800000 it returns the data above.

**Comment by carlosmiei** [comment]
@Tomas-MP Yeah, but in that case, it's a limitation from the exchange side, usually they don't allow queries targetting data with more than a few months

**Comment by Tomas-MP** [comment]
@carlosmiei already was afraid of that, will test around a little bit to see where the limit is exactly, thanks!
