### ISSUE TITLE
Binance Future New modify order endpoint implementation in editOrder in Python 

### ISSUE THREAD

**Issue by himanshu24x77** [ccxt/ccxt#17952]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

is the New modify order endpoint is also available with python for binance future editOrder ? Can you pls also share or add an example of how to use the same in python/example ?

### Describe the solution you'd like

changes in binance future editOrder to support New modify in python 

### Describe alternatives you've considered

no alternative present

**Comment by carlosmiei** [comment]
Hello @himanshu24x77, it is available and it should be pretty straightforward to use you just need to provide the required values.
Example:

```Python
edit = await binance.edit_order('myOrderId', 'LTC/USDT:USDT', 'limit', 'buy', 2 , 55)
```
