### ISSUE TITLE
Bybit fetch_position(symbol) always returns 0 for 'contracts'

### ISSUE THREAD

**Issue by xmintx** [ccxt/ccxt#17961]
### Operating System

windows 11

### Programming Languages

python

### CCXT Version

ccxt-3.1.2

### Description

When calling fetch_position(symbol) the returned response always has 0 for the contracts. However when calling fetch_positions the correct amount of contracts are returned.

### Code

current_position = await self.exchange.fetch_position(symbol + settle_symbol)
current_positions= await self.exchange.fetch_positions()

**Comment by sc0Vu** [comment]
Hi @xmintx 

Would you like to paste which endpoints called (can find with verbose)?

**Comment by xmintx** [comment]
It seems that the fetch_position returns positionIDX 1 and positionIDX2 but both use the same key "size":

fetch Request: bybit GET https://api-testnet.bybit.com/v5/position/list?symbol=BTCUSDT&category=linear RequestHeaders: {'Content-Type': 'application/json', 'X-BAPI-API-KEY': 'TXQ6YtWtMurYa3GxDP', 'X-BAPI-TIMESTAMP': '1684585148357', 'X-BAPI-RECV-WINDOW': '5000', 'X-BAPI-SIGN': '77626b398b16d9bf197f92f59bf933715d40deb90486bcf2b7e9d919b4e39e4f', 'Accept-Encoding': 'gzip, deflate'} RequestBody: None

fetch Response: bybit GET https://api-testnet.bybit.com/v5/position/list?symbol=BTCUSDT&category=linear 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'Date': 'Sat, 20 May 2023 12:19:10 GMT', 'Ret_code': '0', 'Traceid': '0102696597bacac52c53a34be82cae66', 'Timenow': '1684585150377', 'Server': 'Openresty', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 e7f129711e11b0a56b98fec5b2ace678.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'TPE52-C1', 'X-Amz-Cf-Id': 'kGHUS5lDeLpjXOx6_fZBZKFnHap39DBm1GbHKhaKODHZgNeN88emxA=='} ResponseBody: {"retCode":0,"retMsg":"OK","result":{"nextPageCursor":"BTCUSDT%2C1684569600057%2C2","category":"linear","list":[{"symbol":"BTCUSDT","leverage":"1","autoAddMargin":0,"avgPrice":"0","liqPrice":"","riskLimitValue":"2000000","takeProfit":"","positionValue":"","tpslMode":"Full","riskId":1,"trailingStop":"0","unrealisedPnl":"","markPrice":"26891.55","adlRankIndicator":0,"cumRealisedPnl":"0","positionMM":"0","createdTime":"1684547784083","positionIdx":1,"positionIM":"0","updatedTime":"1684569600057","side":"","bustPrice":"","positionBalance":"0","size":"0","positionStatus":"Normal","stopLoss":"","tradeMode":0},{"symbol":"BTCUSDT","leverage":"1","autoAddMargin":0,"avgPrice":"26845","liqPrice":"199999.8","riskLimitValue":"2000000","takeProfit":"","positionValue":"161.07","tpslMode":"Full","riskId":1,"trailingStop":"0","unrealisedPnl":"-0.2793","markPrice":"26891.55","adlRankIndicator":2,"cumRealisedPnl":"-0.09165909","positionMM":"0.998634","createdTime":"1684547784083","positionIdx":2,"positionIM":"161.263284","updatedTime":"1684569600057","side":"Sell","bustPrice":"","positionBalance":"0","size":"0.006","positionStatus":"Normal","stopLoss":"","tradeMode":0}]},"retExtInfo":{},"time":1684585150377}

fetch Request: bybit GET https://api-testnet.bybit.com/v5/position/list?settleCoin=USDT&limit=200&category=linear RequestHeaders: {'Content-Type': 'application/json', 'X-BAPI-API-KEY': 'TXQ6YtWtMurYa3GxDP', 'X-BAPI-TIMESTAMP': '1684585148744', 'X-BAPI-RECV-WINDOW': '5000', 'X-BAPI-SIGN': '9f17b4974391d3af1c5a0a11960ebad33e45fcbdccc60a18692046ba33edb040', 'Accept-Encoding': 'gzip, deflate'} RequestBody: None

fetch Response: bybit GET https://api-testnet.bybit.com/v5/position/list?settleCoin=USDT&limit=200&category=linear 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '709', 'Connection': 'keep-alive', 'Date': 'Sat, 20 May 2023 12:19:10 GMT', 'Ret_code': '0', 'Traceid': '72730b28daf7968d7c90a49684a26498', 'Timenow': '1684585150659', 'Server': 'Openresty', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 e7f129711e11b0a56b98fec5b2ace678.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'TPE52-C1', 'X-Amz-Cf-Id': 'DSTbTTB-Rb26WXZwhsLMbcEOa66l_oatqqhRC-sceSfF3GOXWM7VjQ=='} ResponseBody: {"retCode":0,"retMsg":"OK","result":{"nextPageCursor":"BTCUSDT%2C1684569600057%2C2","category":"linear","list":[{"symbol":"BTCUSDT","leverage":"1","autoAddMargin":0,"avgPrice":"26845","liqPrice":"199999.8","riskLimitValue":"2000000","takeProfit":"","positionValue":"161.07","tpslMode":"Full","riskId":1,"trailingStop":"0","unrealisedPnl":"-0.2793","markPrice":"26891.55","adlRankIndicator":2,"cumRealisedPnl":"-0.09165909","positionMM":"0.998634","createdTime":"1684547784083","positionIdx":2,"positionIM":"161.263284","updatedTime":"1684569600057","side":"Sell","bustPrice":"","positionBalance":"0","size":"0.006","positionStatus":"Normal","stopLoss":"","tradeMode":0}]},"retExtInfo":{},"time":1684585150659}

**Comment by xmintx** [comment]
It seems that it only has an issue with reporting position size on shorts since it seems that the long position overrides the short position
