### ISSUE TITLE
In Python Triangular arbitrage

### ISSUE THREAD

**Issue by guram-asanidze-1-btu-edu-ge** [ccxt/ccxt#17964]
# Define the trading pairs for triangular arbitrage
trading_pairs = [
    {
        'leg1': '.../USDT',
        'leg2': '.../...',
        'leg3': '.../...'
    },
    {
        'leg1': '.../USDT',
        'leg2': '.../...',
        'leg3': '.../...'
    }
]

for pair in trading_pairs:
    leg1 = pair['leg1']
    leg2 = pair['leg2']
    leg3 = pair['leg3']

    # Fetch ticker data for all trading pairs
    ticker1 = exchange.fetch_ticker( leg1 )
    ticker2 = exchange.fetch_ticker( leg2 )
    ticker3 = exchange.fetch_ticker( leg3 )

    # Check if the ticker prices are valid
    if (
            ticker1['ask'] is None or
            ticker2['ask'] is None or
            ticker3['ask'] is None
    ):
        print( f"Invalid ticker prices for {leg1}, {leg2}, {leg3}." )
    else:
        # Extract the ask prices for each leg
        price1_ask = float( ticker1['ask'] )
        price2_ask = float( ticker2['ask'] )
        price3_ask = float( ticker3['ask'] )

        # Fetch the trading fees from Binance
        markets = exchange.fetch_markets()
        fees = {
            leg1: None,
            leg2: None,
            leg3: None
        }
        for market in markets:
            if market['symbol'] == leg1:
                fees[leg1] = market['maker']
            elif market['symbol'] == leg2:
                fees[leg2] = market['taker']
            elif market['symbol'] == leg3:
                fees[leg3] = market['taker']

        # Calculate the potential profit percentage with fees
        fee_leg1 = fees[leg1]
        fee_leg2 = fees[leg2]
        fee_leg3 = fees[leg3]

        # Calculate the potential profit percentage with fees
        profit_percentage = (
                                    (1 / (price1_ask * (1 + fee_leg1))) *
                                    (price2_ask * (1 - fee_leg2)) *
                                    (price3_ask * (1 - fee_leg3)) - 1
                            ) * 100

        # Print the profit percentage
        print( f"Profit percentage (with fees) for {leg1}, {leg2}, {leg3}: {profit_percentage:.2f}%" )

        if profit_percentage > 0.01:
            usdt_balance = exchange.fetch_balance()['total']['USDT']
            print( 'start balance:', usdt_balance )
            max1 = usdt_balance / price1_ask
            order1 = exchange.create_market_buy_order( leg1, max1 )
            time.sleep( 1 )

            for2=exchange.fetch_balance()['total'][leg2.split( '/' )[0]]
            max2 = for2 / price2_ask
            order2 = exchange.create_market_buy_order( leg2,max2  )
            time.sleep( 1 )

            for3=exchange.fetch_balance()['total'][leg3.split( '/' )[0]]
            max3=for3/price3_ask
            order3 = exchange.create_market_buy_order( leg3,max3  )
            time.sleep( 1 )

            print( "Market buy orders executed:" )
            print( f"Order 1: {order1}" )
            print( f"Order 2: {order2}" )
            print( f"Order 3: {order3}" )

            usdt_balance = exchange.fetch_balance()['total']['USDT']
            print( 'finish balance ', usdt_balance )
        else:
            usdt_balance = exchange.fetch_balance()['total']['USDT']
            print( 'just balance ', usdt_balance )
I get error on order 2, leg 2 need to round price, how to do it according to your library?

**Comment by frosty00** [comment]
the question is not clear, what is the error you get?
