### ISSUE TITLE
Bybit unified v5 set_position_mode() using V3 instead of V5.

### ISSUE THREAD

**Issue by xmintx** [ccxt/ccxt#17962]
### Operating System

windows 11

### Programming Languages

python

### CCXT Version

ccxt-3.1.2

### Description

When using the set_position_mode(hedged = true), response returned is 
"retCode":100028,"retMsg":"unified account is forbidden: recommend using v5 endpoint"

### Code

await exchange.set_position_mode(hedged = True)

**Comment by sc0Vu** [comment]
Hi @xmintx 

It seems bybit updated some apis, will update asap.

**Comment by evgeny-s** [comment]
Hey, guys.
Any update here?
I have the same error: `unified account is forbidden` when trying to use set leverage or switch isolated API.

**Comment by carlosmiei** [comment]
Hello @evgeny-s, can you please open a different issue? ideally posting the full error/ccxt version
