### ISSUE TITLE
Kucoin Futures `fetch_tickers()` returns dict full of `None` and inconsistent symbol

### ISSUE THREAD

**Issue by faberkeping** [ccxt/ccxt#17980]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

3.0.101

### Description

The tickers data, returned the `fetch_tickers()` function in `ccxt.kucoinfutures()`, has symbol with `BTC/USDT` format instead of `BTC/USDT:USDT`. From what I know, futures exchange symbol will use the `:USDT` formatting. Not only that, the tickers data returned by `fetch_tickers()` are full of `None`, except for the `info`.

### Code

Loop through the Kucoin Futures tickers data
```
exchange = ccxt.kucoinfutures()
tickers = exchange.fetch_tickers()
for _, ticker in tickers.items():
    market = exchange.market(ticker["symbol"])
```
Exception was raised
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Projects\env\bot\lib\site-packages\ccxt\base\exchange.py", line 3322, in market
    raise BadSymbol(self.id + ' does not have market symbol ' + symbol)
ccxt.base.errors.BadSymbol: kucoinfutures does not have market symbol NKN/USDT
```

Ticker data example:
```
>>> print(tickers["BTC/USDT"])  # all data is None, except for 'info'
{
    'symbol': 'BTC/USDT',
    'timestamp': None,
    'datetime': None,
    'high': None,
    'low': None,
    'bid': None,
    'bidVolume': None,
    'ask': None,
    'askVolume': None,
    'vwap': None,
    'open': None,
    'close': None,
    'last': None,
    'previousClose': None,
    'change': None,
    'percentage': None,
    'average': None,
    'baseVolume': None,
    'quoteVolume': None,
    'info': {
        'symbol': 'BTC-USDT', 'symbolName': 'BTC-USDT', 'buy': '27038.4',
        'sell': '27038.5', 'changeRate': '0.0054', 'changePrice': '146.8',
        'high': '27279.4', 'low': '26873.4', 'vol': '1190.85427752',
        'volValue': '32219533.276340055', 'last': '27038.4',
        'averagePrice': '26881.55848951', 'takerFeeRate': '0.001',
        'makerFeeRate': '0.001', 'takerCoefficient': '1',
        'makerCoefficient': '1', 'time': 1684665317062
    }
}
```

**Comment by carlosmiei** [comment]
Hello @faberkeping, 
Thanks for letting us know, actually, `kucoinfutures` does not have and endpoint to retrieve all tickers, so it does not implement `fetchTickers`. The problem is that `kucoinfutures` extends from `kucoin` so we're calling the parent `fetchTickers `, leading to this weird response. We will add a protection against this.

**Comment by mdengler** [comment]
`kucoinfutures` now seems to have an [`allTickers` method](https://www.kucoin.com/docs/rest/futures-trading/market-data/get-latest-ticker-for-all-contracts) that `ccxt` does use, so `ccxt.kucoinfutures(..).fetch_tickers()` works now.

**Comment by carlosmiei** [comment]
@mdengler correct :)
