### ISSUE TITLE
Requests speed decrease using watch_order_book()

### ISSUE THREAD

**Issue by ZakatZakat** [ccxt/ccxt#17985]
### ؜

**Operating System**
Windows 11

**Programming Languages**
Python

**CCXT Version**
3.1.1

**Description**
Hi,

I'm using the code example from [this example](https://github.com/ccxt/ccxt/blob/master/examples/py/async-fetch-many-orderbooks-continuously.py) to get orderbook information and save it into parquet file. At the beggining I got ~100ms speed of my requests as it can be shown below:

> 
> [2023-05-21 16:46:57.654000128]
> [2023-05-21 16:46:57.753999872]
> [2023-05-21 16:46:57.854000128]
> [2023-05-21 16:46:57.953999872]
> [2023-05-21 16:46:58.054000128]
> 

But as a time goes by, I see a noticable speed decrease:

> [2023-05-21 18:49:19.832999936]
> [2023-05-21 18:49:20.832999936]
> [2023-05-21 18:49:21.833999872]
> [2023-05-21 18:49:22.833999872]
> [2023-05-21 18:49:23.835000064]
> [2023-05-21 18:49:24.736000]
> [2023-05-21 18:49:25.736000]
> [2023-05-21 18:49:26.936999936]

Now, the average difference between requests is about 1 sec. Can you please tell me, why the speed is decreasing and what can I do to overcome it? As you can see, I'm only using 1 exchange and 1 trade-pair in my code (In the future, my expectation is to get 100ms information for about 4-5 exchanges).

```
import ccxt.pro
import asyncio
import datetime
import pandas as pd
import numpy as np
import os

async def watch_book(exchange, ticker):
    last = None
    limits = {'Binance': 1000,
              'Huobi': 150}
    columns = ['bids_price', 'bids_value', 'asks_price', 'asks_value', 'time']
    while True:
        try:
            bids, asks = {}, {}
            orderbook = await exchange.watch_order_book(ticker)
            now = datetime.datetime.now()

            for b in orderbook['bids']:
                bids[str(float(b[0]))] = float(b[1])
            for a in orderbook['asks']:
                asks[str(float(a[0]))] = float(a[1])

            x = np.empty(limits[exchange.name])
            x.fill(orderbook['timestamp'])
            data_table = pd.DataFrame([bids.keys(), bids.values(), asks.keys(), asks.values(), x], index=columns).T.dropna(axis=1, how='all').replace({None: np.nan}).fillna(0).astype(float).set_index('time')
            
            if os.path.exists(f'{exchange.name}_snap.parquet.gzip'):
                data_table.to_parquet(f'{exchange.name}_snap.parquet.gzip', engine='fastparquet', append=True,
                                      compression='gzip')
            else:
                data_table.to_parquet(f'{exchange.name}_snap.parquet.gzip', engine='fastparquet', compression='gzip')

        except Exception as e:
            print(f'{exchange.name} failed {type(e)} {e}')


async def main():
    exchange_ids = ['binance']
    exchanges = [getattr(ccxt.pro, exchange_id)() for exchange_id in exchange_ids]
    try:
        done, pending = await asyncio.wait({watch_book(exchange, 'BTC/USDT') for exchange in exchanges}, return_when=asyncio.FIRST_EXCEPTION)
        for completed in done:
            # trigger the exception here
            completed.result()
    except Exception as e:
        print(f'closing all exchanges because of exception {type(e)} {e}')
        await asyncio.gather(*[exchange.close() for exchange in exchanges])


asyncio.run(main())
```

**Comment by ZakatZakat** [comment]
> Hi @ZakatZakat , could it be as data increases the `data_table.to_parquet()` call takes longer to complete and that is causing the delay?

Tnx for an answear, I will try to change my saving process. Can you recommend some good ways of storing big amount of data from exchanges in python?

**Comment by frosty00** [comment]
answered by @pcriadoperez
