### ISSUE TITLE
exchange.hasFetchOrderBook != exchange.has['fetchOrderBook']

### ISSUE THREAD

**Issue by wardbradt** [ccxt/ccxt#1799]
- OS: Mac OS High Sierra 10.13.2
- Programming Language version: Python 3.6
- CCXT version: 1.10.1021
- Exchange: Coinmarketcap
- Method: `hasFetchOrderBook`

I just noticed that `fetchOrderBook` (and some other "fetch" methods, such as `fetchPrivateAPI`) for coinmarketcap (and possibly other exchanges) are broken. For example, this code
```
import ccxt
exchange = getattr(ccxt, 'coinmarketcap')()
print(exchange.hasFetchOrderBook)
print(exchange.has['fetchOrderBook'])
```
outputs
```
True
False
```

**Comment by kroitor** [comment]
The set of `.has***` properties was deprecated and is now replaced with the `.has = {}` dictionary, like, `has['fetchOrderBook'], has['fetchTicker'], ...`. Please update your code for compatibility.

Let us know if this does not answer your question: https://github.com/ccxt/ccxt/issues/1522.

Thx!
