### ISSUE TITLE
Bybit: fetch_balance() returns 0 balance in Testnet

### ISSUE THREAD

**Issue by ahagmann83** [ccxt/ccxt#18004]
### Operating System

Window 10

### Programming Languages

python

### CCXT Version

3.1.6

### Description

I have 10.000 USDT and 1 BTC on my Bybit Testnet account (Spot Balance). 
These Balances don´t show up (zero balance for all coins) with CCXT using fetch_balance() or fetch_free_balance()
![image](https://github.com/ccxt/ccxt/assets/90323196/6738263c-c4c5-4592-8319-4f6305971e45)

### Code

```
import ccxt

exchange = ccxt.bybit()
exchange.apiKey = my_key
exchange.secret = my_secret_key
exchange.set_sandbox_mode(True)

exchange.fetch_balance()
 

```

**Comment by carlosmiei** [comment]
Hello @ahagmann83,
Bybit was historically a derivatives exchange, so for that reason, we return the derivatives wallet by default. Can you try to do this instead: `exchange.fetch_balance({"type":"spot"})`

**Comment by carlosmiei** [comment]
@ahagmann83 Nice, in that case I will close this issue, let us know if anything!
