### ISSUE TITLE
Balance values incomplete for gateio

### ISSUE THREAD

**Issue by dwiltech** [ccxt/ccxt#18005]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

3.1.6

### Description

The gateio implementation is not responding with the expected balance figures for a Portfolio Margin Account. The fetch_balance result gives free, used, and total numbers, but the free and total are the values of the 'Available balance' (which does not change with the changes in the value of the holdings), not the 'Account equity' value as some other implementations give. The 'Account equity' value, or other values like PnL, do not seem to be available anywhere. Other implementations have that data in the 'info' section of the response. There are no other values available in the 'info' section in this response.

Language is Python. CCXT version: 3.1.6

Code: balance = exchange.fetch_balance()

fetch Request: gateio GET https://api.gateio.ws/api/v4/spot/accounts RequestHeaders: {'KEY': 'nnnn', 'Timestamp': '1684929528', 'SIGN': 'nnnnf26c61555f04', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'X-Gate-Channel-Id': 'ccxt'} RequestBody: None

fetch Response: gateio GET https://api.gateio.ws/api/v4/spot/accounts 200 ResponseHeaders: {'Date': 'Wed, 24 May 2023 11:58:50 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'openresty', 'X-Request-Id': '[533b2dd4-6103468431]', 'Access-Control-Allow-Methods': 'GET,POST,OPTIONS,DELETE,PUT', 'Access-Control-Allow-Headers': 'DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type', 'Access-Control-Max-Age': '1728000', 'Vary': 'Origin', 'Content-Encoding': 'gzip'} ResponseBody: [{"currency":"USDT","available":"nnnn.222089","locked":"0"}]

### Code

```
  

```
balance = exchange.fetch_balance()

**Comment by ttodua** [comment]
Sorry for a late reply.
I have checked this and you need to use 'cross' margin account to get the balances from portfolio, as GATE API includes those information under cross-margin account. So, you can use  `e.fetch_balance({'marginMode':'cross'})` and check its `info` key.

I had a bit questions whether portfolio account can be unified with standard unification way, so for now you have to use those custom fields from `info` and handle yourself at this moment
