### ISSUE TITLE
Question about fetch_ohlcv inside binance.py

### ISSUE THREAD

**Issue by wtksyjpy** [ccxt/ccxt#1803]
- OS: **Ubuntu 16.04**
- Programming Language version: **Python 3.6.3**
- CCXT version: **1.10.1026**
- Exchange: **Binance**
- Method: **fetch_ohlcv**

HI,

I have a question about the function **fetch_ohlcv** in binance.py
I noticed inside this function, you called:
line 536: response = self.**publicGetKlines**(self.extend(request, params))
But I cannot find the definition about **publicGetKlines**
Could you tell me where to find it?
Thanks~

Best,
Hank

**Comment by mkutny** [comment]
Let us know if [this part](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods) of the Manual answers your question.

**Comment by wtksyjpy** [comment]
Hi Max,

Thank you for your response.
I'm quite new with declarative programming.
Could you please tell me what kinds of methods you used for define implicit APIs?
And where can I find the .api definition?
Thank you for answering!

Best,
Hank

**Comment by mkutny** [comment]
Excerpt from the Manual:

> Upon exchange construction an implicit magic method (aka partial function or closure) will be created inside defineRestApi()/define_rest_api() on the exchange instance for each endpoint from the list of .api endpoints.

.api endpoints are listed starting from this line:
https://github.com/ccxt/ccxt/blob/25eb8523cba9d9b0155f3517190f8b08f42da1c1/python/ccxt/binance.py#L78

There you have [`binance.api.public.get.kline`](https://github.com/ccxt/ccxt/blob/25eb8523cba9d9b0155f3517190f8b08f42da1c1/python/ccxt/binance.py#L107) property. Existence of this property is an instruction for [`define_rest_api()`](https://github.com/ccxt/ccxt/blob/25eb8523cba9d9b0155f3517190f8b08f42da1c1/python/ccxt/base/exchange.py#L242) method to build that `publicGetKlines` in question.

This method is not in the source code, it's only created upon exchange instantiation, so you can see it with something like:
```python
>>> import ccxt
>>> binance = ccxt.binance()
>>> dir(binance)
```

**Comment by kroitor** [comment]
Thanks to @mkutny once again for the correct answer.
@wtksyjpy let us know if you have any difficulties with it after reading the docs linked above.
Closing it for now if you don't mind.
Thx!

**Comment by wtksyjpy** [comment]
HI Max,

Got it!
Thank you so much for your detailed explanation!

Best,
Hang
