### ISSUE TITLE
Requires network params despite it being declared 

### ISSUE THREAD

**Issue by 300Gram** [ccxt/ccxt#18031]
### Operating System

Ubuntu

### Programming Languages

python

### CCXT Version

3.1.8

### Description

I am having trouble trying to withdraw using ccxt. 

I kept getting ```ccxt.base.errors.BadRequest: woo withdraw() require network parameter``` error despite I have already declared network param in the code. 

[Edit]
For some reason, after switching machine to run the script, that code works. (Not sure why but it works, maybe an explanation would be great).

### Code

```
withdrawResponse = EXCHANGE.withdraw(baseCurrency, balance, withdrawAddress, withdrawMemo, params={'network':nativeNetwork})
```

**Comment by carlosmiei** [comment]
Hello @300Gram, are you sure the same versions were running?
