### ISSUE TITLE
Deepwaters exchange integration

### ISSUE THREAD

**Issue by gmussi** [ccxt/ccxt#18033]
### Exchange Name

Deepwaters

### URL of the Exchange

https://deepwaters.xyz/

### URL of the Exchange's API docs

https://rest.docs.api.deepwaters.xyz/index.html

### Why should this exchange be implemented?

Community wise, Deepwaters id the fastest growing unreleased project in web3 since November of last year. 50k twitter, 80k discord. >17.5% engagement across all socials.

I have written the implementation here:
https://github.com/ccxt/ccxt/pull/17045

I am currently running this implementation in my own market maker. I will also be maintaining this implementation.

**Comment by kroitor** [comment]
@gmussi just to clarify, are you affiliated with the exchange in question?

**Comment by gmussi** [comment]
@kroitor I got paid to code the implementation as a contractor. But I am not directly affiliated with the exchange.

**Comment by ttodua** [comment]
duplicate of https://github.com/ccxt/ccxt/issues/17035
