### ISSUE TITLE
Gate.io fetchTradingFee() returning wrong fee if exchange discount token is enabled

### ISSUE THREAD

**Issue by Tongoko** [ccxt/ccxt#18032]
### Operating System

Windows

### Programming Languages

python

### CCXT Version

3.0.80

### Description

fetchTradingFee() is returning a wrong value for **'maker'** if GT discount token is enabled on the exchange. **'taker'** is for some reason correct. I noticed though that **'maker_fee'** inside the **'info'** field is also incorrect, so maybe is it from the exchange side? **'gt_taker_fee'** and **'gt_maker_fee'** are correct.

Response:
`{'info': {'user_id': '12345678', 'taker_fee': '0.00139', 'maker_fee': '0.00175', 'gt_discount': True, 'gt_taker_fee': '0.00139', 'gt_maker_fee': '0.00131', 'loan_fee': '0.162', 'point_type': '1', 'futures_taker_fee': '0.00046', 'futures_maker_fee': '0.00015'}, 'symbol': 'XXX/USDT', 'maker': 0.00175, 'taker': 0.00139}`

### Code

```
.fetchTradingFee()

```

**Comment by Dan-krm** [comment]
It looks like taker fee is correct in this case because `'taker_fee'` and `'gt_taker_fee`' from the exchanges response are both the same value for this trading pair. I opened a pull request that adds gt discount support to fetchTradingFee and fetchTradingFees.
