### ISSUE TITLE
Bitget watchBalance() always returns None "used" and "total" balance

### ISSUE THREAD

**Issue by grozz97** [ccxt/ccxt#18041]
### Operating System

Ubuntu 20.04.5 LTS

### Programming Languages

python

### CCXT Version

3.1.7

### Description

Bitget: watchBalance() always returns **None** "used" and "total" balance:

```
{'BTC': {'free': 0.005, 'used': None, 'total': None},  'USDT': {'free': 53.757823259104, 'used': None, 'total': None}, 'free': {'BTC': 0.005, 'USDT': 53.757823259104}, 'used': {'BTC': None, 'USDT': None}, 'total': {'BTC': None, 'USDT': None}}
```

### Code

```
balance_update = await ccxt.bitget.watch_balance()

print(balance_update)

```

**Comment by carlosmiei** [comment]
Hello @grozz97, thanks for reporting it will apply a patch very soon.

**Comment by grozz97** [comment]
> Hello @grozz97, thanks for reporting it will apply a patch very soon.

Thanks
