### ISSUE TITLE
Additional parameters stopped working after update

### ISSUE THREAD

**Issue by JT102** [ccxt/ccxt#1806]
- OS: Linux
- Programming Language version: PHP
- CCXT version: current (pulled today)
- Exchange: bibance / bibox / all?
- Method: fetch_l2_order_book

This part of code stopped working after today git pull:
$order_book = $exchange->fetch_l2_order_book ('ETH/BTC',array('limit'=>10));
Request URL to the API is changed (same for different exchanges):

```
Request:
Array
(
    [0] => GET
    [1] => https://api.binance.com/api/v1/depth?symbol=ETHBTC&limit%5Blimit%5D=10
    [2] => Array
        (
        )
    [3] => 
)
```
API return:

> PHP Fatal error:  Uncaught exception 'ccxt\ExchangeNotAvailable' with message 'binance GET https://api.binance.com/api/v1/depth?symbol=ETHBTC&limit%5Blimit%5D=10 400 {"code":-1104,"msg":"Not all sent parameters were read; read '1' parameter(s) but was sent '2'."}' in .../ccxt/php/Exchange.php:706

Was it changed and how we should provide additional parameters now?
Thanks

**Comment by Deathamns** [comment]
#1758

**Comment by mkutny** [comment]
Since you use PHP you may try:
```sh
ccxt> php examples/php/cli binance fetchOrderBook ETH/BTC 10
```

**Comment by JT102** [comment]
Thanks **Deathamns**. I missed this update announcement.

**mkutny**, I couldn't run this kind of tests - how should it work? cli I have is Mono JIT compiler version 3.2.8 - is it what I need?

**Comment by mkutny** [comment]
The `cli`mentioned above is actually `cli.php`, it has nothing in common with Mono. Updated that comment, hope it's easier to spot now.

Open your terminal, `cd` into `ccxt` directory and type the command above.

**Comment by kroitor** [comment]
@JT102 here's the script mentioned by @mkutny https://github.com/ccxt/ccxt/blob/master/examples/php/cli.php

And the answer of @Deathamns is the right one – you just need to update the call signatures.

Let us know if this does not help.
