### ISSUE TITLE
watch_order_book do nothing in kucoinfutures

### ISSUE THREAD

**Issue by Avarong** [ccxt/ccxt#18076]
### Operating System

Windows Server 2019 Standard

### Programming Languages

python

### CCXT Version

3.1.8

### Description

I can not get something from watch_order_book for kucoinfutures. Tryed for different symbols. The same code works good for another exchanges.

### Code

```
   ex=ccxtpro.kucoinfutures({'newUpdates': True})
    while True:
        try:
            book=await ex.watch_order_book('XBT/USDTM:USDT',5)
            print('{} {}'.format(book['asks'][0],book['bids'][0]))
        except: await asyncio.sleep(0.1)

```

**Comment by carlosmiei** [comment]
Hello @Avarong I suspect you're providing an invalid symbol and your `except` branch hides the real exception. 

`XBT/USDTM:USDT` is not a valid symbol, I think you meant `BTC/USDT:USDT`

You can read more about symbols here: https://docs.ccxt.com/#/README?id=symbols-and-market-ids

**Comment by Avarong** [comment]
Thank you for your answer! I tryed different symbols. The real error was-
"Exception-kucoinfutures watchOrderBook 'limit' argument must be None, 20 or 100"
