### ISSUE TITLE
[SCAM Report] TIDEX Exchange - Unjustified Account Locking & Asset Seizure

### ISSUE THREAD

**Issue by yemreak** [ccxt/ccxt#18074]
Dear CCXT Team,

I am reaching out to report a disturbing issue with the **TIDEX exchange** that I believe you and the larger CCXT community should be made aware of.

Despite there being no clear prohibition against arbitrage trading in TIDEX's Terms & Rules, the platform appears to be locking accounts of users who engage in such practices. The customer support team has been less than helpful in this regard, responding to inquiries with weeks of "please wait" messages without resolving the issue.

After nearly a month of inaction, **TIDEX has chosen to return only the initial funds deposited into the account. It is as if they have unilaterally decided to confiscate and appropriate for themselves all profits and subsequent deposits.**

Unfortunately, they have now begun blocking my requests for help via Telegram and email, which is why I am bringing this issue to the attention of the CCXT community and the CCXT team itself.

I urge everyone not to use the TIDEX exchange for transactions with CCXT or similar software. Even if you strictly adhere to the Terms & Rules, your account might still be closed within a day or two under the pretext of "**arbitrage is prohibited**." I kindly request that this exchange be removed from CCXT to protect other users from enduring the same predicament.

Thank you for your attention to this matter and for your ongoing commitment to fostering a fair and transparent trading environment.

Yours sincerely,

**Comment by kroitor** [comment]
@yedhrab thank you for reporting it, we will try to reach out to TIDEX to get it resolved.

**Comment by yemreak** [comment]
I want to point out another long-term issue with Tidex. They are seizing assets sent to closed accounts. I mistakenly transferred USDT to an old account and they said they'd refund it, but four months have passed with no refund—only delays. Their support center keeps saying they've forwarded the issue to their finance department, but no solution has come forth for four months
@kroitor

**Comment by yemreak** [comment]
They blocked me from their Telegram channels because I explained that my assets haven't been returned for four months.

**Comment by ivanalexander0128-coder** [comment]
I never thought I’d see my tokens again, but tidex.io proved me wrong. Reactivated my account and got my withdrawal instantly.
