### ISSUE TITLE
Binance unable to retrieve historical data for perps

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#18125]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

3.1.19

### Description

When retrieving historical data it sometimes throws the error below (for the PERP pair), when trying the same data for for example USDT, it seems to be working. 

### Code

```
  
client = ccxt.binance()
ticker = "LINKUSD_PERP"
since = 1685095020000

new = client.fetch_ohlcv(ticker, '1m', since, 1500)

ticker2 = "LINKUSDT"

new2 = client.fetch_ohlcv(ticker2, '1m', since, 1500)

```
Traceback (most recent call last):

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:560 in fetch
    response.raise_for_status()

  File ~\anaconda3\lib\site-packages\requests\models.py:1021 in raise_for_status
    raise HTTPError(http_error_msg, response=self)

HTTPError: 400 Client Error: Bad Request for url: https://dapi.binance.com/dapi/v1/klines?interval=1m&limit=1500&symbol=LINKUSD_PERP&startTime=1685095020000&endTime=89999999

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  Cell In[36], line 1
    client.fetch_ohlcv(

  File ~\anaconda3\lib\site-packages\ccxt\binance.py:3173 in fetch_ohlcv
    response = getattr(self, method)(self.extend(request, params))

  File ~\anaconda3\lib\site-packages\ccxt\base\types.py:25 in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)

  File ~\anaconda3\lib\site-packages\ccxt\binance.py:7408 in request
    response = self.fetch2(path, api, method, params, headers, body, config)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:2865 in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:576 in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File ~\anaconda3\lib\site-packages\ccxt\binance.py:7385 in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:3175 in throw_exactly_matched_exception
    raise exact[string](message)

BadRequest: binance {"code":-1023,"msg":"Start time is greater than end time."}

**Comment by carlosmiei** [comment]
Hello @Tomas-MP, thanks for reporting it.

I made a few tests and seems to be working fine on my end, is it possible to specify the arguments (`since`, `symbol`, `timeframe`, `params`) that lead to this error?


```
p binance fetchOHLCV "LINK/USD:LINK" "1m" 1685095020000 100 
Python v3.10.9
CCXT v3.1.24
binance.fetchOHLCV(LINK/USD:LINK,1m,1685095020000,100)
[[1685095020000, 6.316, 6.316, 6.315, 6.315, 349.91653617],
 [1685095080000, 6.316, 6.316, 6.316, 6.316, 101.32995567],
 [1685095140000, 6.316, 6.316, 6.316, 6.316, 0.0],
 [1685095200000, 6.317, 6.319, 6.317, 6.318, 1760.12180769],
 [1685095260000, 6.32, 6.323, 6.32, 6.322, 597.94934201],
```
```
 p binance fetchOHLCV "BTC/USD:BTC" "1m" 1685095020000 100   
Python v3.10.9
CCXT v3.1.24
binance.fetchOHLCV(BTC/USD:BTC,1m,1685095020000,100)
[[1685095020000, 26446.9, 26446.9, 26444.8, 26444.8, 6.31835802],
 [1685095080000, 26444.6, 26444.6, 26444.5, 26444.5, 1.90965978],
 [1685095140000, 26444.5, 26444.5, 26444.5, 26444.5, 0.08697461],
 [1685095200000, 26444.5, 26444.6, 26440.8, 26440.8, 34.80000224],
 [1685095260000, 26440.9, 26440.9, 26440.7, 26440.8, 4.3190835],
```

**Comment by Tomas-MP** [comment]
It seems to be working here now too, not sure what caused the error then but will close. Thanks.

**Comment by Tomas-MP** [comment]
@carlosmiei did some more testing, the issue was on my side. The problem was that the since parameter type was numpy.int64 rather than a normal integer, thus it threw an error.
