### ISSUE TITLE
Request for Partnership: Seeking CCXT Official Certification

### ISSUE THREAD

**Issue by williamXu-art** [ccxt/ccxt#18134]
### ؜

Dear CCXT team,

Greetings! I work for a cryptocurrency exchange . We noticed that our API data has been connected to your library, but it hasn’t been certified yet.

We would like to inquire about the specific certification information required for us to proceed with the process.
We appreciate your time and look forward to hearing from you soon. Thank you very much.

**Comment by xu-winston** [comment]
@carlosmiei  I tried contacting on Discord but didn't receive a response.
