### ISSUE TITLE
Limit price can't be higher than xxx, binance -4183 error. 

### ISSUE THREAD

**Issue by Sailendrakc** [ccxt/ccxt#18135]
### Operating System

win 10

### Programming Languages

JS

### CCXT Version

3.0.78

### Description

This looks like binance issue so its more of a question.
What I am trying to do is, take a long position with stoploss price in same order. For example, I wanna go long in 
DOT/USDT:USDT at the price (rate) of 3.5 USDT and if things went bearish then get out of market by hitting stop loss at 3 USDT.

 Whenever I go long with limit stop loss in binance. It says

ExchangeError: binance {"code":-4183,"msg":"Limit price can't be higher than 3.15"}

The price 3.15 is related to stopPrice(See below). It is exactly 5% above whatever the stopPrice is. If I create order without stoploss then no any error occours. 
below is the code to replicate. I also have included a code to mitigate CORS header error using proxy.

### Code

```
    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/ccxt@3.0.78/dist/ccxt.browser.js"></script>
<script async>
(async function(){
    
    let exName = "binance";
    let proxxy = 'http://localhost:12000/';
    let ccxtpro = ccxt.pro;
    let exchange = new ccxtpro[exName]({
        'proxy': proxxy
    });
   
    //auth details
    let details = {
        "binance": {
            apiKey: 'xxxxxxxxxxxxxxxxxxxxxxx',
            secret: 'xxxxxxxxxxxxxxxxxxxxxxxx',
        }
    }

    //perform auth
    let dt = details['binance'];
    if (dt) {
        exchange.apiKey = dt.apiKey;
        exchange.secret = dt.secret;
        
        exchange.nonce = function () {
        return exchange.milliseconds();
        }
    }


    //load markets
    let k =await exchange.loadMarkets();
    console.log(k);
    let symbol = "DOT/USDT:USDT";
    
    let rate = 3.5;
    
    let stopLoss = 3;

    let params = {
            'stopPrice' : stoploss,
            'positionSide': 'long',
    }

    let type = 'STOP';
    let side = "buy";
    let amount = 3;

    //set leverage
    let lev = await exchange.setLeverage(1, symbol, {});

    //create long order
    // /let id = await exchange.createOrder(symbol = symbol, type = type, side = side, amount = amount, rate = rate, params); 
    //let id = await exchange.createOrder(symbol, type, side, amount, rate, {});   
    let stopid = await exchange.createOrder(symbol, "STOP", side, amount, rate, params) ; 

    //fetch the order detail to check if stoploss has been setup or no.
    let res = await exchange.fetch_open_orders(symbol, undefined, 5, {});
    console.log(res);

})();

</script>
</html>


```

The code for proxy is below. It uses cors-anywhere package from npm. So npm install "cors-anywhere" then use any port (12000) in this example. Then npm start it. Reflect the proxt value in exchange.proxy as done in code above.

```
// JavaScript CORS Proxy
// Save this in a file like cors.js and run with `node cors [port]`
// It will listen for your requests on the port you pass in command line or port 8080 by default
let port = (process.argv.length > 2) ? parseInt(process.argv[2]) : 12000; // default
require('cors-anywhere').createServer().listen(port, 'localhost')

```

**Comment by carlosmiei** [comment]
Hello @Sailendrakc, unfortunately, you can't do that at once using the API on Binance; you have to do it in two steps:
- place an order that will open the position, example: `binance.createOrder('BTC/USDT:USDT', market, buy, 1)` 
- place an order that will act as a StopLoss/takeProfit for the previously opened position, example: `binance.createOrder('BTC/USDT:USDT', market, sell, 1, undefined, {"stopLossPrice":20000})`

**Comment by Sailendrakc** [comment]
Thak you very much ! @carlosmiei 

For anyone looking for limit order then here is example:

```
    //Taking long order
    let longid = await exchange.createOrder(symbol, "LIMIT", "buy", amount, rate, {'timeInForce': 'GTC', 'positionSide': 'long'}) ; 

    //and then its stoploss
    let stopid = await exchange.createOrder(symbol, "LIMIT", "sell", amount, rate, {"stopPrice":5.163, 'positionSide': 'long'}) ; 
```

if positionSide is long we are dealing with long position, if its short we are dealing with short position.
if positionSide is long and side is "buy" we are opening long, if side is "sell" then we are closing long position. Vice versa for positionSide short.
