### ISSUE TITLE
[QUESTION] How to I access an API Point in bybit?

### ISSUE THREAD

**Issue by gilbh** [ccxt/ccxt#18165]
### ؜

Hi,

I am trying to get to this access point:
https://bybit-exchange.github.io/docs/v5/position/close-pnl#request-parameters

-- through ccxt bybit.

I found it in the `describe()` call, inside the returned dictionary , on line no. 381 in bybit.py:
```
                        'v5/position/closed-pnl': 2.5,
```

-- but I can't find it in the methods of my exchange object ... is there an ccxt interface for this and to get to it?

Thanks!

**Comment by sc0Vu** [comment]
Hi @gilbh 

We transform each api path to methods when initiate the exchange. You can checkout implicit methods in our wiki page (https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods).

Let me know if you have any other issues.

**Comment by gilbh** [comment]
Thank you very much for this!

I am not seeing a unified method for closed pnl, so will use this one for now.
