### ISSUE TITLE
Create_order : privatePostOrder not found

### ISSUE THREAD

**Issue by antoinemineau** [ccxt/ccxt#1817]
Hi,

Thanks for the amazing library, just started using it.
I have an issue when I try to place an order on Bibox, the error is : 

`
privatePostOrder not found
`

I found it used in https://github.com/ccxt/ccxt/blob/master/php/bibox.php#L331
I can't find a reference of this method in the 1.10.1034 or 1.10.997 (latest commit in the folder).
I tried to search in the git and an other issue related to it without success...

- OS: Debian 7
- Programming Language version: php
- CCXT version: 1.10.1034 / 1.10.997
- Exchange: Bibox
- Method: create_order

Thanks !

**Comment by kroitor** [comment]
Hi!

Please read the user Manual (from beginning to the very end): https://github.com/ccxt/ccxt/wiki/Manual
All your questions are answered there. You will save yourself a lot of time this way and it would help you really make use of the library.

Several specific aspects are covered here:
https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

Let us know if you have any difficulties or questions with it after that )

Thank you!

**Comment by antoinemineau** [comment]
Amazing, it's working !
Thank you very much for the library and the very very fast answer !

**Comment by kroitor** [comment]
@antoinemineau thanks for your support, we appreciate it very much! Let us know if you have any other money... just kidding... any other difficulties with the library )

**Comment by antoinemineau** [comment]
Haha, if I manage to develop my project using this library.
I might have more questions / money  :)
