### ISSUE TITLE
Binance createOrder BadRequest error due to mandatory parameter not being sent

### ISSUE THREAD

**Issue by hyunr01** [ccxt/ccxt#18180]
### ؜

OS: Windows
Programming Language version: Python 3.11.2
CCXT version: 3.1.15

```
binance = ccxt.binance(config={
    'apiKey': binance_access_key,
    'secret': binance_secret_key,
    'enableRateLimit': True, 
})
binance.options['defaultType'] = 'future'
symbol = 'ATOM'
fetch_bal = binance.fetch_balance(params={"type": "future"})
for position in fetch_bal['info']['positions']:
    if position['symbol'] == symbol+'USDT':
        position_amt = position['positionAmt']
binance_order = binance.createOrder(symbol+'USDT', 'market', 'buy', float(position_amt))
```
ccxt.base.errors.BadRequest: binance {"code":-1102,"msg":"Mandatory parameter 'quantity' was not sent, was empty/null, or malformed."}

Wondering why I'm getting this error as I'm passing in the amount of coins I have into createOrder with position_amt. I also saw on the Binance API that for the endpoint POST /fapi/v1/order (which createOrder uses), the 'quantity' parameter is not mandatory.

**Comment by kroitor** [comment]
@hyunr01 there’s a number of errors in your code: 

1. If you want to trade perpetual futures contracts also known as perpetual swaps, then you should set the defaultType to 'swap' or use binanceusdm.
2. Your order amount must be an integer number of contracts: https://github.com/ccxt/ccxt/wiki/Manual#position-structure
3. Use exchange.fetch_positions in a unified manner: https://github.com/ccxt/ccxt/wiki/Manual#position-structure
4. Use a proper perpetual symbol: https://github.com/ccxt/ccxt/wiki/Manual#contract-naming-conventions

```Python
binance = ccxt.binanceusdm(config={
    'apiKey': binance_access_key,
    'secret': binance_secret_key,
    'enableRateLimit': True, 
})
symbol = 'ATOM/USDT:USDT'
positions = binance.fetch_positions()
for position in positions:
    if position['symbol'] == symbol:
        position_amt = position['contracts']
binance_order = binance.createOrder(symbol, 'market', 'buy', position_amt)
```

**Comment by hyunr01** [comment]
Thanks for the response. However, the code that I wrote is meant to address the future derivatives market not swap.

**Comment by kroitor** [comment]
> Thanks for the response. However, the code that I wrote is meant to address the future derivatives market not swap.

A perpetual futures derivative is the same thing as a perpetual futures swap, please, read here for the naming standards of different types of contracts: https://github.com/ccxt/ccxt/wiki/Manual#contract-naming-conventions

**Comment by hyunr01** [comment]
Doesn't that list them as two different derivatives? Sorry if I'm wrong, just wondering why they would be listed separately with different descriptions if so. (future – for expiring futures contracts that have a delivery/settlement date
swap – for perpetual swap futures that don't have a delivery date)

**Comment by kroitor** [comment]
@hyunr01 there's two types of futures derivatives:
- expiring futures derivatives that have a delivery date
- non-expiring futures derivatives that do not have a delivery date (these are also known as perpetual future swaps, and looking at your initial code this is exactly what you want)

**Comment by hyunr01** [comment]
I'm not 100% if I have this correctly. I'm trying to open and close shorts based on other values I'm calculating from the spot market of another foreign exchange platform. That would mean that I will be opening and closing the shorts of float values of coins (i.e. 120.34 ATOM) on the binance usdm futures market which doesn't seem like it's possible in the code you provided as it requires an integer amount of contracts. I'm probably understanding something wrong as my other bits of the code which took in binance.createOrder(symbol+'USDT', 'market', 'buy', value) where value was a float was successfully able to close shorts on the binance usdm futures derivative that I opened earlier on in the code in a similar fashion.

**Comment by kroitor** [comment]
@hyunr01 Binance USDM Perpetual Futures Derivatives is the same thing as Binance USDM Perpetual Swap Derivatives. These terms are equivalent.

With Binance ATOM/USDT:USDT you can trade fractions since the precision of that contract allows up to 2 decimals:

```Python
import ccxt
from pprint import pprint
exchange = ccxt.binanceusdm()
markets = exchange.load_markets()
symbol = 'ATOM/USDT:USDT'
market = exchange.market(symbol)
pprint(market)
```

The output of that code is like this:

```Python
~/ccxt/python $ python3
Python 3.8.2 (default, Apr  8 2021, 23:19:18)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> from pprint import pprint
>>> exchange = ccxt.binanceusdm()
>>> markets = exchange.load_markets()
>>> symbol = 'ATOM/USDT:USDT'
>>> market = exchange.market(symbol)
>>> pprint(market)
{'active': True,
 'base': 'ATOM',
 'baseId': 'ATOM',
 'contract': True,
 'contractSize': 1.0,
 'expiry': None,
 'expiryDatetime': None,
 'feeSide': 'get',
 'future': False,
 'id': 'ATOMUSDT',
 'info': {'baseAsset': 'ATOM',
          'baseAssetPrecision': '8',
          'contractType': 'PERPETUAL',
          'deliveryDate': '4133404800000',
          'filters': [{'filterType': 'PRICE_FILTER',
                       'maxPrice': '100000',
                       'minPrice': '0.251',
                       'tickSize': '0.001'},
                      {'filterType': 'LOT_SIZE',
                       'maxQty': '100000',
                       'minQty': '0.01',
                       'stepSize': '0.01'},
                      {'filterType': 'MARKET_LOT_SIZE',
                       'maxQty': '20000',
                       'minQty': '0.01',
                       'stepSize': '0.01'},
                      {'filterType': 'MAX_NUM_ORDERS', 'limit': '200'},
                      {'filterType': 'MAX_NUM_ALGO_ORDERS', 'limit': '10'},
                      {'filterType': 'MIN_NOTIONAL', 'notional': '5.0'},
                      {'filterType': 'PERCENT_PRICE',
                       'multiplierDecimal': '4',
                       'multiplierDown': '0.9000',
                       'multiplierUp': '1.1000'}],
          'liquidationFee': '0.017500',
          'maintMarginPercent': '2.5000',
          'marginAsset': 'USDT',
          'marketTakeBound': '0.10',
          'maxMoveOrderLimit': '10000',
          'onboardDate': '1569398400000',
          'orderTypes': ['LIMIT',
                         'MARKET',
                         'STOP',
                         'STOP_MARKET',
                         'TAKE_PROFIT',
                         'TAKE_PROFIT_MARKET',
                         'TRAILING_STOP_MARKET'],
          'pair': 'ATOMUSDT',
          'pricePrecision': '3',
          'quantityPrecision': '2',
          'quoteAsset': 'USDT',
          'quotePrecision': '8',
          'requiredMarginPercent': '5.0000',
          'settlePlan': '0',
          'status': 'TRADING',
          'symbol': 'ATOMUSDT',
          'timeInForce': ['GTC', 'IOC', 'FOK', 'GTX'],
          'triggerProtect': '0.1000',
          'underlyingSubType': ['Layer-1'],
          'underlyingType': 'COIN'},
 'inverse': False,
 'limits': {'amount': {'max': 100000.0, 'min': 0.01}, <<<<<<<<<<<<<<<<<<<<<<<<<<
            'cost': {'max': None, 'min': 5.0},
            'leverage': {'max': None, 'min': None},
            'market': {'max': 20000.0, 'min': 0.01},
            'price': {'max': 100000.0, 'min': 0.251}},
 'linear': True,
 'lowercaseId': 'atomusdt',
 'maker': 0.0002,
 'margin': False,
 'option': False,
 'optionType': None,
 'percentage': True,
 'precision': {'amount': 2, 'base': 8, 'price': 3, 'quote': 8}, <<<<<<<<<<<<<<<<<<<<<
 'quote': 'USDT',
 'quoteId': 'USDT',
 'settle': 'USDT',
 'settleId': 'USDT',
 'spot': False,
 'strike': None,
 'swap': True,
 'symbol': 'ATOM/USDT:USDT',
 'taker': 0.0004,
 'tierBased': False,
 'type': 'swap'}
```

Note the limits and precision on that market – those things are explained in the Manual here:

- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

If you want to close an ATOM/USDT:USDT position, then the code I posted above should work. If it does not work, please enable verbose mode after loading the markets and paste your verbose output here:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by kroitor** [comment]
@hyunr01 this is the code with verbose mode on:

```Python
binance = ccxt.binanceusdm(config={
    'apiKey': binance_access_key,
    'secret': binance_secret_key,
})
markets = exchange.load_markets()
exchange.verbose = True  # after loading the markets
symbol = 'ATOM/USDT:USDT'
positions = binance.fetch_positions()
for position in positions:
    if position['symbol'] == symbol:
        position_amt = position['contracts']
binance_order = binance.createOrder(symbol, 'market', 'buy', position_amt)
```

**Comment by hyunr01** [comment]
Thanks a lot for the explanation. I will try it out once I'm back and let you know if something errors out.
