### ISSUE TITLE
Can't place futures order using leverage on bybit

### ISSUE THREAD

**Issue by mackdaddylmao** [ccxt/ccxt#18187]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

3.1.31

### Description

I'm trying to place an order using 75x leverage through bybit but I keep receiving the following error:

```An error occurred while placing the order: bybit {"retCode":140007,"retMsg":"remark:order[49649307 ae68f79f-a281-4f69-918e-4cd4eaaf271d] fix price failed for CannotAffordOrderCost.","result":{},"retExtInfo":{},"time":1686541103334}```

I have 27USDT in my account for testing purposes and with my code im trying to achieve is to fetch my total balance (which is done successfully) then use the entirety of my balance to create either a short or long with the desired leverage (which has been set succesfully) but it still struggles to purchase.

I cant understand why its giving me a CannotAffordOrderCost when i have the USDT in my derivates wallet. 

### Code

```
symbol ="ETHUSD"
leverage = 75
def set_leverage():
    try:
        exchange.set_leverage(leverage, symbol)
        print(f"Leverage set to {leverage}x for {symbol}.")
    except Exception as e:
        print(f"An error occurred while setting the leverage: {e}")

set_leverage()

def place_order(symbol, side):
    balance = get_balance()
    current_price = get_current_price(symbol)
    amount = ((balance / current_price) * leverage) * 0.95
    side = 'Buy' if side == 'long' else 'Sell'
    print(amount)
    try:
        exchange.create_market_order(symbol, side, amount)
        print(f"Market {side} order of {balance} {symbol} placed.")
    except Exception as e:
        print(f"An error occurred while placing the order: {e}")
        
place_order(symbol, 'short')
 

```

**Comment by mackdaddylmao** [comment]
> Hello @mackdaddylmao, Using the same amount, can you place the order using the WEB platform? Usually you can't allocate 100% of your capital to open a position so Bybit might be requiring you a small % to be left as margin for your position.

 Well in my code I actually multiply the order by 0.95 to adjust to that just in case, so it's a little smaller than 100%

**Comment by carlosmiei** [comment]
> > Hello @mackdaddylmao, Using the same amount, can you place the order using the WEB platform? Usually you can't allocate 100% of your capital to open a position so Bybit might be requiring you a small % to be left as margin for your position.
> 
> Well in my code I actually multiply the order by 0.95 to adjust to that just in case, so it's a little smaller than 100%

@mackdaddylmao I noticed that yes but even 5% might not be enough, that is why I asked if you had the opportunity to test in the WEB UI. Alternatively, you can decrease the 95% factor a bit to see if it makes a difference.

**Comment by mackdaddylmao** [comment]
> > > Hello @mackdaddylmao, Using the same amount, can you place the order using the WEB platform? Usually you can't allocate 100% of your capital to open a position so Bybit might be requiring you a small % to be left as margin for your position.
> > 
> > 
> > Well in my code I actually multiply the order by 0.95 to adjust to that just in case, so it's a little smaller than 100%
> 
> @mackdaddylmao I noticed that yes but even 5% might not be enough, that is why I asked if you had the opportunity to test in the WEB UI. Alternatively, you can decrease the 95% factor a bit to see if it makes a difference.

Ohhh sorry about that, thanks. So I just tested it with 0.8 to see if I can get a trade to work and it is now printing a new error:

`An error occurred while placing the order: bybit amount of ETH/USD:ETH must be greater than minimum amount precision of 1`

I imagine its because its trying to short less than 1 eth which I can do on bybit WEB UI, is there a way to order using the USDT in my account rather than ETH maybe?

**Comment by carlosmiei** [comment]
@mackdaddylmao bybit went through major updates and maybe this issue does not apply anymore. Please reopen it if needed.
