### ISSUE TITLE
Binding request to specific network interface

### ISSUE THREAD

**Issue by incompletude** [ccxt/ccxt#1819]
Maybe this an enhancement. 

Is there a supported way to bind a ccxt request to a specific network interface?

Thank you

**Comment by kroitor** [comment]
> Is there a supported way to bind a ccxt request to a specific network interface?

Yes, sure!

- JavaScript: you can pass a custom `fetchImplementation` with a custom agent class in constructor params to bind to a specific IP (see docs for node.js `http` and `node-fetch`)
- Python: you can use whatever `session` options are supported with `python-requests` and `aiohttp`, for that you can pass a custom `session` in constructor params
- PHP: you can use the CURLOPT_INTERFACE to bind underlying cURL to an IP, for that you can override `curlopt_interface` in constructor params.

Let us know if this does not answer your question. Thx!
