### ISSUE TITLE
Bitmex wrong entry price

### ISSUE THREAD

**Issue by Nitrix321** [ccxt/ccxt#18194]
OS: Windows 10
Programming Language version: Python
CCXT version: 3.1.35 ؜

Hello, if I try to fetch entry_price I get a "wrong" output.

Entry Price is 26000$
but it shows Entry Price:  25962.55.

If I fetch avgCostPrice it's correct. 

bitmex = ccxt.bitmex({'enableRateLimit': True,
                       'apiKey': bitmexconfig.api_key,
                       'secret': bitmexconfig.api_secret,})

symbol = 'XBTUSD'

params={"type":"swap","code":"USD"}
    bitmex_pos = bitmex.fetch_positions([symbol], params)

entry_price = bitmex_pos[0]['entryPrice']

print('Entry Price: ', entry_price)

--> Entry Price:  25962.55

**Comment by carlosmiei** [comment]
Hello @Nitrix321,
Is it possible to provide a verbose log? As you can see in the code right now we're using the `avgEntryPrice` value provided by the API:

```Javascript
            'contractSize': undefined,
            'entryPrice': this.safeNumber (position, 'avgEntryPrice'),
            'markPrice': this.safeNumber (position, 'markPrice'),
            'lastPrice': undefined,
```

**Comment by Nitrix321** [comment]
I took avgCostPrice, and now its working correctly again.
With avgCostPrice I get the correct entry Price.
Thanks for your help again :-).


params={"type":"swap","code":"USD"}
    bitmex_pos = bitmex.fetch_positions([symbol], params)
    print(bitmex_pos)
    entry_price = bitmex_pos[0]['entryPrice']
    avgcostprice = bitmex_pos[0]['info']
    avgcostprice = avgcostprice['avgCostPrice']
    #print(avgcostprice)
    #avgcostprice = bitmex_pos['info']['avgCostPrice']
    print('Entry Price: ', entry_price)
    print('Avg CostPrice: ', avgcostprice)
