### ISSUE TITLE
Severe sync issue with Binance

### ISSUE THREAD

**Issue by Ericxgao** [ccxt/ccxt#1821]
I was doing some algo trading and there appears to be a severe discrepancy between the Binance API and my orders. 

I started getting 
    {"code":-1000,"msg":"An unknown error occured while processing the request."}

To my fetch_open_order calls, and then when I did make limit orders, they would not reflect in my fetch_open_order returns.

There was also cases where I had cancelled a limit order yet it still shows itself as open.

See my order history: https://i.imgur.com/pusEBjd.png

    >>> binance.fetch_open_orders(symbol='VEN/BTC')
	[{'status': 'open', 'timestamp': 1518043562501, 'price': 0.00053297, 'datetime': '2018-02-07T22:46:02.501Z', 'cost': 0.0, 'id': '11680454', 'remaining': 57.0, 'info': {u'orderId': 11680454, u'clientOrderId': u'p6dQhvcJwjvtDvBjE1ZnFQ', u'origQty': u'57.00000000', u'icebergQty': u'0.00000000', u'symbol': u'VENBTC', u'side': u'SELL', u'timeInForce': u'GTC', u'status': u'NEW', u'stopPrice': u'0.00000000', u'time': 1518043562501, u'isWorking': True, u'type': u'LIMIT', u'price': u'0.00053297', u'executedQty': u'0.00000000'}, 'fee': None, 'side': u'sell', 'amount': 57.0, 'type': u'limit', 'symbol': u'VEN/BTC', 'filled': 0.0}]

VEN was cancelled yet even now, ten minutes later it continues to show up.

**Comment by kroitor** [comment]
This can happen when exchanges are stressed under high loads. Unfortunately an inconsistency in their engine has been reported earlier from many users here and in their telegram chat, but the issue is still there. We've also detected the same issue multiple times on our own. And we can't workaround it on our side, because this is an inter-engine inconsistency, not an inconsistency in the lib. Sorry about that.

**Comment by Ericxgao** [comment]
That's pretty awful - I assume they are aware of this?

**Comment by kroitor** [comment]
@Ericxgao I'm pretty sure they're aware, and, I guess, they're working on it...

Messages from their chat right now:
<img width="562" alt="screen shot 2018-02-08 at 02 35 14" src="https://user-images.githubusercontent.com/1294454/35947394-c3c4d452-0c78-11e8-900a-78292e43fc2c.png">

https://t.me/binance_api_english

See it yourself )

**Comment by Ericxgao** [comment]
Perfect - was looking for this group. Thanks for the support.
