### ISSUE TITLE
Bybit tickers confuses symbols

### ISSUE THREAD

**Issue by Sebastiaan240** [ccxt/ccxt#18211]
### Operating System

Ubuntu

### Programming Languages

python

### CCXT Version

3.1.21

### Description

When fetching tickers on Bybit with the fetch_tickers() function, the BTC/USDT ticker is from another symbol.
This is a very dangerous bug because in this case, the ticker suggests BTC is priced at $0.33 which could trigger extreme behaviour by algorithms using CCXT.

Below is the output. The "info" key shows that the data in this ticker is actually from CANDY/USDT.
Note that this happens with fetch_tickers(), both when requesting only BTC/USDT (as a one-item list) and when requesting multiple symbols including BTC/USDT (as a multi-item list).
fetch_ticker() does not seem to have this bug.

Sometimes instead of this wrong output, you get no output at all and instead fetch_tickers() returns an empty dictionary.
I'm not sure what decides whether you get a wrong output or no output. It seems random.

```
{'BTC/USDT': {'symbol': 'BTC/USDT', 'timestamp': None, 'datetime': None, 'high': 2.1421, 'low': 0.1, 'bid': 0.3255, 'bidVolume': 18.91, 'ask': 0.3308, 'askVolume': 42.93, 'vwap': 0.45267434559615505, 'open': 0.1, 'close': 0.3309, 'last': 0.3309, 'previousClose': None, 'change': 0.2309, 'percentage': 230.9, 'average': 0.21545, 'baseVolume': 1052042.26, 'quoteVolume': 476232.541585, 'info': {'symbol': 'CANDYUSDT', 'bid1Price': '0.3255', 'bid1Size': '18.91', 'ask1Price': '0.3308', 'ask1Size': '42.93', 'lastPrice': '0.3309', 'prevPrice24h': '0.1', 'price24hPcnt': '2.3090', 'highPrice24h': '2.1421', 'lowPrice24h': '0.1', 'turnover24h': '476232.541585', 'volume24h': '1052042.26'}}}
```

### Code

```
import ccxt

bybit = ccxt.bybit()

print(bybit.fetch_tickers(['BTC/USDT']))
```

**Comment by carlosmiei** [comment]
Hello @Sebastiaan240, thanks for reporting it, we will take a look asap.
