### ISSUE TITLE
WSL2 transpile.js not skipping already transpiled files

### ISSUE THREAD

**Issue by pkindruk** [ccxt/ccxt#18227]
### Operating System

Docker dev container (host Windows 10)

### Programming Languages

JS

### CCXT Version

3.1.37

### Description

My dev environment is WSL 2 docker container and almost all exchanges transpiled every time I run `npm run transpile`
`fs.utimesSync()` truncates milliseconds on some platforms https://github.com/nodejs/node/issues/13520

Changing line below line shown in sample solved the issue.
https://github.com/ccxt/ccxt/blob/e58bb9e50ba3b482dbce6d0749f5bd79d13afc7e/build/transpile.js#L1302
```ts
//const tsMtime = fs.statSync (tsPath).mtime.getTime ()
let tsMtime = fs.statSync (tsPath).mtime.getTime ()
tsMtime = tsMtime - tsMtime % 1000;
```

Also docs guarantee on second precision: https://nodejs.org/api/fs.html#fs_fs_utimes_path_atime_mtime_callback

**Comment by samgermain** [comment]
> ### Operating System
> 
> Docker dev container (host Windows 10)
> ### Programming Languages
> 
> JS
> ### CCXT Version
> 
> 3.1.37
> ### Description
> 
> My dev environment is WSL 2 docker container and almost all exchanges transpiled every time I run `npm run transpile` `fs.utimesSync()` truncates milliseconds on some platforms [nodejs/node#13520](https://github.com/nodejs/node/issues/13520)
> 
> Changing line below line shown in sample solved the issue.
> 
> https://github.com/ccxt/ccxt/blob/e58bb9e50ba3b482dbce6d0749f5bd79d13afc7e/build/transpile.js#L1302
> 
> ```ts
> //const tsMtime = fs.statSync (tsPath).mtime.getTime ()
> let tsMtime = fs.statSync (tsPath).mtime.getTime ()
> tsMtime = tsMtime - tsMtime % 1000;
> ```
> 
> Also docs guarantee on second precision: https://nodejs.org/api/fs.html#fs_fs_utimes_path_atime_mtime_callback

I created [a PR](https://github.com/ccxt/ccxt/pull/18229) with this change and still had a lot of unneeded transpilation

I have [an alternate PR](https://github.com/ccxt/ccxt/pull/17797) that I created about a month ago though which works correctly by subtracting 250 ms from the mtime

**Comment by ttodua** [comment]
@carlosmiei Sam's PR might fix it. I am not sure about context what/why that happens, but Sam had researched it and seems found a solution

**Comment by carlosmiei** [comment]
> @carlosmiei Sam's PR might fix it. I am not sure about context what/why that happens (maybe the reason is re-sorting the .has and rewriting it back? I don't remind, have to check it), but Sam had researched it and seems found a solution

@ttodua @samgermain I would rather try out the solution proposed by @pkindruk (truncate the timestamp) instead of hardcoding a subtraction of 250ms

**Comment by samgermain** [comment]
> > @carlosmiei Sam's PR might fix it. I am not sure about context what/why that happens (maybe the reason is re-sorting the .has and rewriting it back? I don't remind, have to check it), but Sam had researched it and seems found a solution
> 
> @ttodua @samgermain I would rather try out the solution proposed by @pkindruk (truncate the timestamp) instead of hardcoding a subtraction of 250ms

I tried that in [this PR](https://github.com/ccxt/ccxt/pull/18229)

**Comment by samgermain** [comment]
> > @carlosmiei Sam's PR might fix it. I am not sure about context what/why that happens (maybe the reason is re-sorting the .has and rewriting it back? I don't remind, have to check it), but Sam had researched it and seems found a solution
> 
> @ttodua @samgermain I would rather try out the solution proposed by @pkindruk (truncate the timestamp) instead of hardcoding a subtraction of 250ms

After some discussion with @pkindruk it looks like https://github.com/ccxt/ccxt/pull/18229 is working solution to this problem. If it could get merged soon that would be appreciated
