### ISSUE TITLE
CCXT placed my buy order at a higher rate than I specified

### ISSUE THREAD

**Issue by kerbe6** [ccxt/ccxt#1823]
- OS: linux
- Programming Language version: python 2
- CCXT version: 1.10.1049
- Exchange: poloniex
- Method: create_limit_buy_order

Not sure why, but for some reason a recent order was submitted at a higher price than I specified.

For all intents and purposes, it went like this:

```
base = 'EXP'
symbol = 'EXP/BTC'
qty = 0.3178300965
rate = 0.00346096865

print "Buying " + float_to_string(qty) + " " + base + " at " + float_to_string(rate) + "\n"
ret = exchange.createLimitBuyOrder(symbol, qty, rate)
print ret
```

Which gave the output:

> Buying 0.3178300965 EXP at 0.00346096865
> 
> {'timestamp': 1518064313000, 'price': 0.00034894, 'datetime': '2018-02-08T04:31:53.000Z', 'cost': 0.0001109, 'id': '2161255', 'info': {u'category': u'exchange', u'fee': u'0.00250000', u'tradeID': u'2161255', u'orderNumber': u'33133046940', u'amount': u'0.31783009', u'rate': u'0.00034894', u'date': u'2018-02-08 04:31:53', u'total': u'0.00011090', u'type': u'buy', u'globalTradeID': 342072998}, 'fee': {'currency': u'EXP', 'rate': 0.0025, 'cost': 0.000794575225, 'type': None}, 'order': '33133046940', 'symbol': u'EXP/BTC', 'amount': 0.31783009, 'type': 'limit', 'side': u'buy'}

(note that qty and rate were't actually hard-coded)

Which reveals that the order submitted was for 0.31783009 EXP (correct) at a rate of 0.00034894 BTC/EXP (incorrect). 

That's a 0.82% difference! Now I realize that may seem insignificant, but when you're making micro-transactions, this can make a big difference. My first thought was that maybe I did something wrong and was misunderstanding precision limits, but I can't see how a loss of precision would increase the price in any way.

Either way, help is appreciated. Thanks!

**Comment by kroitor** [comment]
This is very strange... Are you sure that this isn't float_to_string (formatting) function fault?

I tested your particular value and it's ok:

```Python
import ccxt
p = ccxt.poloniex()
p.load_markets()
p.price_to_precision('EXP/BTC', 0.00346096865)
#  '0.00346097'
```

So, from here we need a minimal but a complete snippet of code from you to investigate further, or, verbose output (set `p = ccxt.poloniex({'verbose': True})` in exchange constructor arguments to see what gets sent). Standing by for more info from you.

**Comment by kerbe6** [comment]
I can get you verbose output and more code tomorrow. Here's float_to_string:

```
def fts(f, p=None):

	if p is not None:
		ctx.prec = p
	else:
		ctx.prec = 10
	d1 = ctx.create_decimal(repr(f))
	return format(d1, 'f')
```

**Comment by kerbe6** [comment]
I actually think this might have something to do with how python handles floats. qty and rate went through a number of arithmetical operations before reaching the code I posted.
https://docs.python.org/2/tutorial/floatingpoint.html

**Comment by kerbe6** [comment]
I will investigate more tomorrow and return with results.

**Comment by kerbe6** [comment]
I ran the exact same code -- same conditions, same qty, same rate -- everything submitted exactly as expected this time.  That is really bizarre.

The only thing I can think of is that there was some sort of magic happening on Poloniex's end. I guess I'll close the issue. I'll comment here again if I run into the same problem again.
