### ISSUE TITLE
Bitkub exchange API update 

### ISSUE THREAD

**Issue by hastalamuerte** [ccxt/ccxt#18247]
Hello, there was 3 weeks ago an update of bitkub API https://github.com/bitkub/bitkub-official-api-docs/blob/master/restful-api.md
Here it is. 

Can dev team plz update an bitkub part of ccxt. Trying made it by hands, but always catch errors. 
Thx

@kroitor , @tuxitor special thanks for your work of implementation of exchange

**Comment by sc0Vu** [comment]
Related issue: https://github.com/ccxt/ccxt/issues/4488
