### ISSUE TITLE
Binance public_get_ticker_allprices does not return anything, API endpoint changed?

### ISSUE THREAD

**Issue by pbosch** [ccxt/ccxt#1824]
- OS: Windows, Linux
- Programming Language version: Python 3.6, Python 3.5
- CCXT version: 1.10.1050
- Exchange: Binance
- Method: public_get_ticker_allprices 

Verbose output:

GET https://api.binance.com/api/v1/ticker/allPrices 
Request: {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} 
 None
GET https://api.binance.com/api/v1/ticker/allPrices 200 
Response: {'Date': 'Thu, 08 Feb 2018 07:12:24 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'nginx', 'Vary': 'Accept-Encoding', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Encoding': 'gzip'} 

I call the above mentioned method and the actual object that I get back is of None type. 

Is it possible that the API endpoint has changed? I do not find the endpoint on [Binance API](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md) anymore. The closest endpoint seems GET /api/v3/ticker/price. It might be that other endpoints changed as well.

Thanks in advance for a response!

**Comment by kroitor** [comment]
They've been down for maintenance for more than several hours now.

- https://github.com/ccxt/ccxt/issues/1821
- https://support.binance.com/hc/en-us/articles/360000710431-
- https://t.me/binance_api_english

**Comment by kroitor** [comment]
```Python
import ccxt
b = ccxt.binance()
b.load_markets()
for symbol in b.markets:
    print(symbol, 'active:', b.markets[symbol]['active'])

```

**Comment by pbosch** [comment]
That was fast, thanks. I must have missed that. I'm still wondering, the endpoints that are used in ccxt can not be found on the Binance API website. Will they be updated in the future?

**Comment by kroitor** [comment]
@pbosch we are updating them as fast as we can in order to keep them up with current official API docs (will update the outdated one in this particular case as well). Whatever inconsistency there is now, it should not break the code, and the rest of them should cover all their endpoints.

**Comment by pbosch** [comment]
Can I offer some help? Although I only have Python skills and your main language seems Javascript and the rest is transpiled.

**Comment by kroitor** [comment]
@pbosch sure, your contributions are welcome, but make sure to read this carefully:
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
Thx!
