### ISSUE TITLE
mexc watchMyTrades fault

### ISSUE THREAD

**Issue by interenet** [ccxt/ccxt#18254]
### Operating System

OS Ubuntu 22

### Programming Languages

python

### CCXT Version

Ccxt ver3.1.41

### Description

Exchange mexc

### Code

```
code: await exchange.watch_my_trades()
error: bad operand type for unary -: 'NoneType'

```

**Comment by sc0Vu** [comment]
Hi @interenet 

Would you like to paste verbose log (remove sensitive information)?
