### ISSUE TITLE
I need help for this error: "BadRequest: Not all sent parameters were read"

### ISSUE THREAD

**Issue by D-Yay** [ccxt/ccxt#18268]
### ؜

Hi, I'm currently having an issue with the code below:

```const ccxt = require ('ccxt');

(async () => {
    const exchange = new ccxt.binance({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET',
        'enableRateLimit': true,
        // 'verbose': true,  // for debugging
    })

    symbol = 'BTC/USDT'
    type = 'limit'  // market, ...
    side = 'buy' // or sell
    amount = 123.45 // your amount here
    price = 543.21 // your price or undefined here

    // you can send any additional params like that
    params = {
        'positionSide': 'LONG', // or 'SHORT' or 'BOTH'
    }

    const order = await exchange.createOrder (symbol, type, side, amount, price, params)
    console.log (order)
    
}) ()
```

This code is belonged to @kroitor in this thread: https://github.com/ccxt/ccxt/issues/6859
but when I ran the code in the terminal it gave me this output:

```

BadRequest: binance {"code":-1104,"msg":"Not all sent parameters were read; read '9' parameter(s) but was sent '10'."}   
    at binance.throwExactlyMatchedException (C:\Users\NGUYEN TUNG LAM\lapi\node_modules\ccxt\dist\cjs\src\base\Exchange.js:2799:19)
    at binance.handleErrors (C:\Users\NGUYEN TUNG LAM\lapi\node_modules\ccxt\dist\cjs\src\binance.js:7566:18)
    at C:\Users\NGUYEN TUNG LAM\lapi\node_modules\ccxt\dist\cjs\src\base\Exchange.js:761:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async binance.fetch2 (C:\Users\NGUYEN TUNG LAM\lapi\node_modules\ccxt\dist\cjs\src\base\Exchange.js:2441:16)      
    at async binance.request (C:\Users\NGUYEN TUNG LAM\lapi\node_modules\ccxt\dist\cjs\src\binance.js:7596:26)
    at async binance.createOrder (C:\Users\NGUYEN TUNG LAM\lapi\node_modules\ccxt\dist\cjs\src\binance.js:4210:26)       
    at async tick (C:\Users\NGUYEN TUNG LAM\lapi\lapi.js:60:19)
```

Any solution for this? @kroitor  if you see this please help me and sorry for wasting your time if you think the question is bad :(

**Comment by sc0Vu** [comment]
Hi @D-Yay 

Looks like some parameters were wrong. Would you like to paste which endpoint you were calling?

**Comment by D-Yay** [comment]
> Hi @D-Yay
> 
> Looks like some parameters were wrong. Would you like to paste which endpoint you were calling?

The param that has the problem here is the 'params' one, which is {'positionSide': 'LONG''}, I don't know what's wrong here, it's in the binance API docs: https://binance-docs.github.io/apidocs/testnet/en/#new-order-trade
may be its because I didn't turn on the hedge mode or something like that

**Comment by sc0Vu** [comment]
Hi @D-Yay 

That's weird, does this work after you change position mode?

**Comment by D-Yay** [comment]
> Hi @D-Yay
> 
> That's weird, does this work after you change position mode?

Hi @sc0Vu 

I don't know how to change the position mode to hedge mode, I can't find it anywhere in the manual docs, I just started working with hedge, I'm using node js while most resources out there are in Python
