### ISSUE TITLE
StopLoss and TakeProfit orders attached to a position not working with Binance

### ISSUE THREAD

**Issue by hodlerhacks** [ccxt/ccxt#18269]
### Operating System

Windows

### Programming Languages

JS

### CCXT Version

3.1.44

### Description

Hi, I'm trying to use the [StopLoss and TakeProfit orders attached to a position](https://docs.ccxt.com/#/README?id=stoploss-and-takeprofit-orders-attached-to-a-position) function with Binance. I've copied the code from the manual and adjusted the price levels:

```
            const params = {
                'stopLoss': {
                    'type': 'limit',
                    'price': 0.737,
                    'stopLossPrice': 0.738,
                    // 'triggerPrice': 0.738,
                    'reduceOnly': true,
                },
                'takeProfit': {
                    'type': 'limit',
                    'takeProfitPrice': 0.8,
                    // 'triggerPrice': 0.8,
                    'reduceOnly': true,
                }
            }

            await exchange.createOrder('SUI/USDT', 'limit', 'buy', 15, 0.77, params);
```

I've tried with triggerPrice, but I read somewhere that Binance doesn't support this. Then tried with stopLossPrice and takeProfitPrice. I've tried with and without reduceOnly.

In all cases, I get an error like this:

BadRequest: binance {"code":-1104,"msg":"Not all sent parameters were read; read '11' parameter(s) but was sent '18'."}

Using verbose logging, this is the request body:

```
timestamp=1687156743361&symbol=SUIUSDT&side=BUY&newClientOrderId=x-R4BD3S82da705b6d0e9b4ad595d4f6&newOrderRespType=FULL&type=LIMIT&quantity=15&price=0.77&timeInForce=GTC&stopLoss%5Btype%5D=limit&stopLoss%5Bprice%5D=0.737&stopLoss%5BstopLossPrice%5D=0.738&stopLoss%5BreduceOnly%5D=true&takeProfit%5Btype%5D=limit&takeProfit%5BtakeProfitPrice%5D=0.8&takeProfit%5BreduceOnly%5D=true&recvWindow=10000&signature=13572e3c230fe84e7fd095cef88397cc00131d791be99a9d66fde3a12b77b83b
```

What am I doing wrong?

Also, I would like to use this function with multiple exchanges. How can I find out (without necessarily testing on all of them) on which exchanges this should work?

Thanks in advance for the help!

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @hodlerhacks

The feature might only work for okx exchange for now, still under unification.

**Comment by hodlerhacks** [comment]
Ah, that's a shame. Thanks for letting me know.
