### ISSUE TITLE
Slow orderbook websocket startup on MEXC

### ISSUE THREAD

**Issue by Sebastiaan240** [ccxt/ccxt#18281]
### Operating System

Windows 11 and Ubuntu

### Programming Languages

python

### CCXT Version

3.1.21

### Description

When starting an orderbook websocket client with CCXT on MEXC, it takes longer than expected for all orderbooks to be received.

High volume pairs like BTC/USDT and ETH/USDT seem to work fine, but for lower-volume pairs start-up takes much longer than expected. These are however not orderbooks that have no updates, as I can see in the UI that they do change and even creating an order of my own does not help.

With the code below I have reproduced this issue.
In this case it took 673 seconds but it can range from a minute to over an hour.

Here is part of the output (I have removed prints where the missing books did not change as all 673 prints would make this too long)
```
Waited for 0.0 seconds. Got 0 out of 6 books
Missing books: ['PEPEXL/USDT', 'CAL/USDT', 'BEN/USDT', 'HOLD/USDT', 'FBX/USDT', 'TENET/USDT']
Waited for 5.014318227767944 seconds. Got 1 out of 6 books
Missing books: ['PEPEXL/USDT', 'CAL/USDT', 'BEN/USDT', 'HOLD/USDT', 'FBX/USDT']
Waited for 7.006701231002808 seconds. Got 2 out of 6 books
Missing books: ['PEPEXL/USDT', 'CAL/USDT', 'HOLD/USDT', 'FBX/USDT']
Waited for 12.008705377578735 seconds. Got 3 out of 6 books
Missing books: ['PEPEXL/USDT', 'CAL/USDT', 'HOLD/USDT']
Waited for 16.004194498062134 seconds. Got 4 out of 6 books
Missing books: ['PEPEXL/USDT', 'CAL/USDT']
Waited for 90.0534496307373 seconds. Got 5 out of 6 books
Missing books: ['PEPEXL/USDT']
Waited for 673.4804337024689 seconds. Got 5 out of 6 books
Missing books: ['PEPEXL/USDT']
```
After the last print, it received the last orderbook and stopped printing.

### Code

```
import ccxt.pro as ccxtpro
import asyncio
import time


class WebsocketClient:
    def __init__(self, symbols):
        self.mexc = ccxtpro.mexc()
        self.books = {}
        self.symbols = symbols
        self.background_tasks = []

    async def watch_book(self, symbol):
        while True:
            self.books[symbol] = await self.mexc.watch_order_book(symbol)

    async def main(self):
        start_time = time.time()
        for symbol in self.symbols:
            task = asyncio.create_task(self.watch_book(symbol))
            task.add_done_callback(lambda t: self.background_tasks.remove(t))
            self.background_tasks.append(task)

        while len(self.books) < len(self.symbols):
            print(
                f"Waited for {time.time() - start_time} seconds. Got {len(self.books)} out of {len(self.symbols)} books")
            print(f"Missing books: {[symbol for symbol in self.symbols if symbol not in self.books]}")
            await asyncio.sleep(1)

        await self.mexc.close()


ws_client = WebsocketClient(['PEPEXL/USDT', 'CAL/USDT', 'BEN/USDT', 'HOLD/USDT', 'FBX/USDT'])
asyncio.run(ws_client.main())

```

**Comment by carlosmiei** [comment]
Hello @Sebastiaan240, I tested locally and had no issues watching thosebooks, do you get this issue every time?

**Comment by Sebastiaan240** [comment]
Hello @carlosmiei, thanks for checking in. It doesn't happen every time. I also just tested again and all the books were received in 10 seconds. I'm not sure what determines how long it takes. The 673 seconds I reported in the issue was just before I posted the issue and I experience this quite regularly.

**Comment by pcriadoperez** [comment]
I confirm that with PNB/USDT it did take me a while to get an update. But on the verbose output no message from the exchange was received, so I'm not sure there is anything we can do from our side.

**Comment by ttodua** [comment]
I think @pcriadoperez's answer is precise here, so if exchange API does not function properly, there is nothing we can do. I suggest you might use polling orderbook if it's critical for you, also, you might bring issue to their attention: https://t.me/MEXCAPIsupport
feel free to re-open the issue if you have anything to comment here further
