### ISSUE TITLE
can't work with Qryptos API

### ISSUE THREAD

**Issue by arielorvits** [ccxt/ccxt#1829]
getting this error when trying use the basic HTML example, replacing gdax with qryptos:

![image](https://user-images.githubusercontent.com/8501221/35969040-45d44194-0cce-11e8-8239-aeb3df7e5f35.png)

any solution?

10x!

**Comment by mkutny** [comment]
There is a tab named 'Console' in the Inspector, see if opening it helps.

**Comment by arielorvits** [comment]
https://stackoverflow.com/questions/20035101/why-does-my-javascript-get-a-no-access-control-allow-origin-header-is-present

solved my issue. 10x!
