### ISSUE TITLE
HitBTC v2 API will be deprecated 01.08.2023

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#18309]
https://api.hitbtc.com/v2
According announcement v2 API will be deprecated soon. Should we rename [hitbtc3.ts](https://github.com/ccxt/ccxt/blob/master/ts/src/hitbtc3.ts) to [hitbtc.ts](https://github.com/ccxt/ccxt/blob/master/ts/src/hitbtc.ts) in advance?

**Comment by kroitor** [comment]
> https://api.hitbtc.com/v2 According announcement v2 API will be deprecated soon. Should we rename [hitbtc3.ts](https://github.com/ccxt/ccxt/blob/master/ts/src/hitbtc3.ts) to [hitbtc.ts](https://github.com/ccxt/ccxt/blob/master/ts/src/hitbtc.ts) in advance?

Sure, we will get that done soon. Thank you for your involvement!

**Comment by ndubel** [comment]
@kroitor @carlosmiei should we speed up this change? it's only 3 weeks left

**Comment by carlosmiei** [comment]
> @kroitor @carlosmiei should we speed up this change? it's only 3 weeks left

@ndubel We will do our best to update it in time.
