### ISSUE TITLE
Kucoin fetchOrder only working for open orders

### ISSUE THREAD

**Issue by janeCMD** [ccxt/ccxt#1831]
Hi,

I was just checking kucoin fetchOrder which was added short while ago. But it does return OrderNotFound exception for closed order.

Works for Open orders as expected...

Is this expected ?

**Comment by Sarona93** [comment]
Hello, 
me too, I was just about to post same question here, 
I need to fetch_order by UUID and I get the message:
> [Not Supported] kucoin fetch_order() not implemented yet (ignoring5)

is there timeframe for implementing above function with Kucoin ?

Thank you.

**Comment by hippylover** [comment]
It's because the api of kucoin doens't return a result if your order is taken or canceled. Perhaps kucoin has a "get all orders, open or closed" call which could be used to simulate a call like this i dont remember(it would be more expensive for exchange and user though but not sure that matters). What i do is run a fetchorder and if i get an error i run fetchclosedorder and extract the relevant order.

**Comment by hippylover** [comment]
You are using old ccxt verion Sarona.

**Comment by janeCMD** [comment]
@hippylover yes, i asked about it and if there is no solution, i will do same way as you mention. Its just more expensive, i dont know how sensitive kucoin is for api calls...

**Comment by hippylover** [comment]
It should be fine as you would be running fetchorder most of the time and fetchclosed order only when the order has been taken.

**Comment by Sarona93** [comment]
@hippylover , yes, I just used the last version and "fetch_order()" was implemented there,
Thank you.

**Comment by wannesdemaeght** [comment]
fetchOrder should work on all orders for kucoin, open or closed, but sometimes their API is quirky.
I've had orders return a 404 not found for days, and then when rechecked later, they do work.

As you have figured out, one workaround is to do fetchClosedOrders, which does return all orders.

Concerning the  rate limit: afaik, kucoin has not implemented a limit yet.

**Comment by janeCMD** [comment]
Thanks for very informative replies !

**Comment by kroitor** [comment]
Closing this if you don't mind, thanks to @hippylover and @wannesdemaeght for their help. Feel free to reopen it if needed.
