### ISSUE TITLE
bitget invalid checksum when watch order book stream

### ISSUE THREAD

**Issue by Aleksey2006** [ccxt/ccxt#18322]
### Operating System

Ubuntu

### Programming Languages

python

### CCXT Version

3.1.49

### Description

I'm getting a checksum error while viewing the order book stream on the Bitget exchange.

### Code

```
  async def loop(exchange_id, symbol):
    exchange = getattr(ccxt.pro, exchange_id)()
    while True:
        try:
            orderbook = await exchange.watch_order_book(symbol)
            now = exchange.milliseconds()
            print(exchange.iso8601(now), exchange.id, symbol, orderbook['asks'][0], orderbook['bids'][0])
        except Exception as e:
            print(str(e))
            # raise e  # uncomment to break all loops in case of an error in any one of them
            break  # you can break just this one loop if it fails
    await exchange.close()


async def main():
    symbols = {
        'bitget': 'BTC/USDT',
        # 'binance': 'BTC/USDT',
        # 'bitmex': 'XBT_USDT',
    }
    await asyncio.gather(*[loop(exchange_id, symbol) for exchange_id, symbol in symbols.items()])


asyncio.run(main())

```

**Comment by carlosmiei** [comment]
Hello @Aleksey2006, how often do you get this error?

**Comment by A1arik** [comment]
I'm having the same problem, could someone share a solution?

**Comment by carlosmiei** [comment]
Hello @A1arik, we fixed this issue a few weeks ago. What's your ccxt version? If you update to the latest it should work properly

**Comment by A1arik** [comment]
Oh, I apologize, it's working - thank you.

**Comment by iockx** [comment]
> Hello @A1arik, we fixed this issue a few weeks ago. What's your ccxt version? If you update to the latest it should work properly

I also encountered this issue. Currently, the version of ccxt is 4.2.93, and the program runs for about 5 minutes before this prompt appears

Do you know if there is a better solution?
