### ISSUE TITLE
binance fapiprivate_delete_batchorders

### ISSUE THREAD

**Issue by chenadda** [ccxt/ccxt#18338]
### Operating System

windows

### Programming Languages

python

### CCXT Version

3.1.16

### Description

Implicit API fapiprivate_post_batchorders Can be used normally
but fapiprivate_delete_batchorders Error:
ccxt.base.errors.AuthenticationError: binance {"code":-1022,"msg":"Signature for this request is not valid."}

### Code

```

```
import ccxt
exchange = ccxt.binance({'apiKey': apiKey,
                                      'secret': secret,
                                      'timeout': 3000,
                                      'enableRateLimit': True,
                                      'options': {'defaultType': 'future'}, })

params ={
    'symbol':aa.symbol,
    'orderIdList':[1234567,2345678]
}
response=exchange.fapiprivate_delete_batchorders(order)
print(response)

**Comment by carlosmiei** [comment]
@gnemoug btw binance supports `cancelOrders` which makes this usage much simpler
