### ISSUE TITLE
Issues with marginType and document inconsistencies returned by the fetch_positions method on the Mexc exchange

### ISSUE THREAD

**Issue by git-aliuge** [ccxt/ccxt#18335]
### Operating System

Linux/Windows

### Programming Languages

python

### CCXT Version

3.1.33

### Description

1.[Position Structure](https://docs.ccxt.com/#/README?id=position-structure) Follow the instructions should return 'marginMode'
2.Call the fetch_positions() method directly, which actually returns 'marginType ' and does not 'marginMode'

**Comment by carlosmiei** [comment]
Hello @git-aliuge,
Thanks for reporting it, will be fixed asap.
