### ISSUE TITLE
In Manual, dead links

### ISSUE THREAD

**Issue by respectabiggle** [ccxt/ccxt#18334]
### ؜

https://github.com/ccxt/ccxt/wiki/Manual#formatting-to-precision

> "For examples of how to use the decimalToPrecision to format strings and floats, please, see the following files:"

links are dead.

Thanks for all your hard work!

**Comment by carlosmiei** [comment]
Hello @respectabiggle,
Thanks for letting us know, they were moved to the `base` folder in the same dir. I will update the docs asap.
