### ISSUE TITLE
binance api fapiprivate_delete_batchorders

### ISSUE THREAD

**Issue by chenadda** [ccxt/ccxt#18344]
### Operating System

windows

### Programming Languages

python

### CCXT Version

3.1.16

### Description

When the method is delete, Binance. sign will place the signature information in the URL instead of the body. However, this API requires the signature information to be placed in the body, so an error signature error will be reported

### Code

```
  order={
    'symbol':'ETHUSDT',
    'orderIdList':convert_list_to_json_array([12345678,23456789])
}
exchange.fapiprivate_delete_batchorders(order)
ccxt.base.errors.AuthenticationError: binance {"code":-1022,"msg":"Signature for this request is not valid."}
```

request=exchange.sign('batchOrders','fapiPrivate','POST',{'symbol': 'ETHUSDT', 'orderIdList': '[12345678,23456789]'},None,None)
print(exchange.fetch(request['url'], 'DELETE', request['headers'], request['body']))

**Comment by sc0Vu** [comment]
Hi @chenadda

I'm not sure how `convert_list_to_json_array` works on your side, but the function work for me if I use array string instead of list, eg `"[12345678,23456789]"`. Let me know if you have any other issue.

**Comment by carlosmiei** [comment]
Hello @chenadda, Binance does have the `cancelOrders` now, so if you update your ccxt version you should be able to get it.
