### ISSUE TITLE
CCXT Pro 'create_order_ws' on Kraken

### ISSUE THREAD

**Issue by AntoBr96** [ccxt/ccxt#18359]
### Operating System

MacOS

### CCXT Version

CCXT Pro 1.0.33

### Description

I am trying to submit an order with CCXT Pro on Kraken using web socket (Python).

`order = await exchange.create_order_ws(symbol="UNI/USD", type="market", side="buy", amount=1 )`

But I receive the following error:

`AttributeError: 'kraken' object has no attribute 'create_order_ws'`

Does it mean that not all the WS methods in CCXT Pro work for supported exchanges or am I missing something?

Thank you for your help!

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @AntoBr96, Are you still using the old package? The latest ccxt version is 3.1.53, which is very distant from yours.

Regarding your question, for now `kraken` is the only exchange with `create_order_Ws/cancel_order_ws/etc` available but we will be adding it to different exchanges in the future. 

In short, if you update your ccxt version you should be able to use that method.

**Comment by AntoBr96** [comment]
Hi @carlosmiei ! Thank you for your quick answer. I updated the CCXT package but I still see this error running the line of code reported in my previous question:

`NotSupported: kraken createOrderWs() is not supported yet`

Am I missing something?

Thank you!

**Comment by AntoBr96** [comment]
Thank you @carlosmiei! Your answer solved my question!

**Comment by reverendrenegade** [comment]
Are there any updates on exchange coverage beyond Kraken regarding the aforementioned web socket calls? 

"create_order_Ws/cancel_order_ws/etc"
