### ISSUE TITLE
Can I use orjson instead of std json for ccxt.pro?

### ISSUE THREAD

**Issue by hi-bingo** [ccxt/ccxt#18358]
### ؜

From the source code, it seems ccxtpro handles the json data by std json lib, since some other json libs will have better performance, is it possible to use these libs (e.g. orjson) ?

**Comment by carlosmiei** [comment]
Hello @hi-bingo, 

There is not an easy way to replace the parser but you can always fork or monkey patch your instance and apply the appropriate changes. 

We will take into consideration your suggestion though. 

Thanks

**Comment by philipperemy** [comment]
In my opinion orjson should be the default for ccxt.

When the number of messages gets too high, feeds start to slow down a lot.

**Comment by carlosmiei** [comment]
@philipperemy I agree but we can't make it default because `orjson` does not run on every interpreter.

We can try to detect the `orjson` installation and use it when detected. 

I will keep you posted.

**Comment by philipperemy** [comment]
@carlosmiei that makes sense. If `orjson` exists, use it else fall back to the default json reader of python

Some exchanges like Kucoin can have 3M messages par minute (TickerV2). With the default implementation, it is not usable because delays accumulate. But I'm guessing for most use cases it's alright.

**Comment by carlosmiei** [comment]
@philipperemy @hi-bingo CCXT now supports orjson. 

You just need to upgrade your ccxt version and have installed `orjson` in your environment. CCXT will detect it and use it automatically.

**Comment by philipperemy** [comment]
@carlosmiei thank you. I believe it's going to be very helpful for professional traders.
