### ISSUE TITLE
Manual rateLimit description is out of date

### ISSUE THREAD

**Issue by ryanfox** [ccxt/ccxt#1837]
In https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties:

> `rateLimit`: A request rate limit in milliseconds. Specifies the required minimal delay between two consequent HTTP requests to the same exchange. **This parameter is not used for now (reserved for future).**

This is out of date, since `enableRateLimit` is supported, yes?

**Comment by kroitor** [comment]
> This is out of date, since enableRateLimit is supported, yes?

Well, yes... The enableRateLimit is supported and yes, the docs are a little behind current codebase. Our resources are a little limited, but we are trying and doing what we can to keep it up. Your help would be really appreciated: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

There's also a lot of examples of rate limiter, and you can find a lot of info about it if you search for "rate limit", "rate limiting", "rateLimit", "enableRateLimit", **"tokenBucket"** in the issues.

Feel free to reopen this issue or just ask, if you have further questions.

Thx!
