### ISSUE TITLE
postOnly not working with createOrderWs

### ISSUE THREAD

**Issue by AntoBr96** [ccxt/ccxt#18387]
### Operating System

MacOS

### Programming Languages

python

### CCXT Version

3.1.53

### Description

I am trying to submit a limit order on Kraken using the `createOrderWs` function. Here my example:

`await exchange.createOrderWs(symbol='UNI/USD', type="limit", side="buy", price=entry_price, amount=1, params={'postOnly': True})`

I receive the following error message: `Error: Unsupported field: 'post_only' for the given msg type: add order`

Is there a way to fix this problem?

Thank you!

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @AntoBr96,
Thanks for letting us know, I will add support for it as soon as possible.
