### ISSUE TITLE
binance - how to avoid incorrect entryprice calculation 

### ISSUE THREAD

**Issue by spc789** [ccxt/ccxt#18386]
### Operating System

Linux

### Programming Languages

python

### CCXT Version

3.0.86

### Description

Hi all, 

Is there somewhere in the market dict a place where the entryprice precision can be found ? (Binance / futures)
Atm I'm calculating the average precision client side with the help of the data provided in the watch_orders function.
However I'm always off slight a bit and I suspect some rounding errors could come into play.

When I initially (at program start) fetch the entryprice data with the fetchPositions REST call I've noticed the entryprice precision of open positions is different then the amount, price, base or quote precision in the market dict. 

Can the entryprice precision somewhere be found in the market dict ? or - if not - ... does somebody know how binance creates/calculates the entryprice precision ?

### Code

```
  

```

**Comment by kroitor** [comment]
@spc789 hi! Have you checked the `limits` and `precision` fields in the corresponding market structure for the symbol in question?

- https://github.com/ccxt/ccxt/wiki/Manual#market-structure
- https://github.com/ccxt/ccxt/wiki/Manual#contract-naming-conventions

```Python
import ccxt
from pprint import pprint
exchange = ccxt.binanceusdm()
markets = exchange.load_markets()
symbol = 'ETH/USDT:USDT'
market = exchange.market(symbol)
pprint(market)
```

```
~/ccxt $ python3 examples/py/cli.py binanceusdm market ETH/USDT:USDT --verbose
Python v3.8.2
CCXT v3.1.52
binanceusdm.market(ETH/USDT:USDT)
{'active': True,
 'base': 'ETH',
 'baseId': 'ETH',
 'contract': True,
 'contractSize': 1.0,
 'expiry': None,
 'expiryDatetime': None,
 'feeSide': 'get',
 'future': False,
 'id': 'ETHUSDT',
 'info': {'baseAsset': 'ETH',
          'baseAssetPrecision': '8',
          'contractType': 'PERPETUAL',
          'deliveryDate': '4133404800000',
          'filters': [{'filterType': 'PRICE_FILTER',
                       'maxPrice': '306177',
                       'minPrice': '39.86',
                       'tickSize': '0.01'},
                      {'filterType': 'LOT_SIZE',
                       'maxQty': '10000',
                       'minQty': '0.001',
                       'stepSize': '0.001'},
                      {'filterType': 'MARKET_LOT_SIZE',
                       'maxQty': '2000',
                       'minQty': '0.001',
                       'stepSize': '0.001'},
                      {'filterType': 'MAX_NUM_ORDERS', 'limit': '200'},
                      {'filterType': 'MAX_NUM_ALGO_ORDERS', 'limit': '10'},
                      {'filterType': 'MIN_NOTIONAL', 'notional': '5.0'},
                      {'filterType': 'PERCENT_PRICE',
                       'multiplierDecimal': '4',
                       'multiplierDown': '0.9500',
                       'multiplierUp': '1.0500'}],
          'liquidationFee': '0.012500',
          'maintMarginPercent': '2.5000',
          'marginAsset': 'USDT',
          'marketTakeBound': '0.05',
          'maxMoveOrderLimit': '10000',
          'onboardDate': '1569398400000',
          'orderTypes': ['LIMIT',
                         'MARKET',
                         'STOP',
                         'STOP_MARKET',
                         'TAKE_PROFIT',
                         'TAKE_PROFIT_MARKET',
                         'TRAILING_STOP_MARKET'],
          'pair': 'ETHUSDT',
          'pricePrecision': '2',
          'quantityPrecision': '3',
          'quoteAsset': 'USDT',
          'quotePrecision': '8',
          'requiredMarginPercent': '5.0000',
          'settlePlan': '0',
          'status': 'TRADING',
          'symbol': 'ETHUSDT',
          'timeInForce': ['GTC', 'IOC', 'FOK', 'GTX'],
          'triggerProtect': '0.0500',
          'underlyingSubType': ['Layer-1'],
          'underlyingType': 'COIN'},
 'inverse': False,
 'limits': {'amount': {'max': 10000.0, 'min': 0.001},  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
            'cost': {'max': None, 'min': 5.0},
            'leverage': {'max': None, 'min': None},
            'market': {'max': 2000.0, 'min': 0.001},
            'price': {'max': 306177.0, 'min': 39.86}},
 'linear': True,
 'lowercaseId': 'ethusdt',
 'maker': 0.0002,
 'margin': False,
 'option': False,
 'optionType': None,
 'percentage': True,
 'precision': {'amount': 3, 'base': 8, 'price': 2, 'quote': 8}, <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
 'quote': 'USDT',
 'quoteId': 'USDT',
 'settle': 'USDT',
 'settleId': 'USDT',
 'spot': False,
 'strike': None,
 'swap': True,
 'symbol': 'ETH/USDT:USDT',
 'taker': 0.0004,
 'tierBased': False,
 'type': 'swap'}
~/ccxt $
```

**Comment by spc789** [comment]
Yes I did.

For example the limits and precision structure for BCH/USDT:USDT is : 

> 'precision': {'amount': 3, 'base': 8, 'price': 2, 'quote': 8},
> 'limits': {'amount': {'max': 10000.0, 'min': 0.001},
>            'cost': {'max': None, 'min': 5.0},
>            'leverage': {'max': None, 'min': None},
>            'market': {'max': 850.0, 'min': 0.001},
>            'price': {'max': 100000.0, 'min': 13.93}},
            
while an example for an open BCH/USDT:USDT position is :
    
```
{   'collateral': 32.81783761,
    'contractSize': 1.0,
    'contracts': 0.143,
    'datetime': '2023-06-27T21:31:20.691Z',
    'entryPrice': 229.4953679246,
    'hedged': False,
    'id': None,
    'info': {   'entryPrice': '229.4953679246',
                'isAutoAddMargin': 'false',
                'isolatedMargin': '0.00000000',
                'isolatedWallet': '0',
                'leverage': '25',
                'liquidationPrice': '0',
                'marginType': 'cross',
                'markPrice': '229.19786021',
                'maxNotionalValue': '250000',
                'notional': '32.77529401',
                'positionAmt': '0.143',
                'positionSide': 'BOTH',
                'symbol': 'BCHUSDT',
                'unRealizedProfit': '-0.04254360',
                'updateTime': '1687901480691'},
    'initialMargin': 1.31101176,
    'initialMarginPercentage': 0.04,
    'leverage': 25.0,
    'liquidationPrice': None,
    'maintenanceMargin': 0.16387647005,
    'maintenanceMarginPercentage': 0.005,
    'marginMode': 'cross',
    'marginRatio': 0.005,
    'marginType': 'cross',
    'markPrice': 229.19786021,
    'notional': 32.77529401,
    'percentage': -3.24,
    'side': 'long',
    'symbol': 'BCH/USDT:USDT',
    'timestamp': 1687901480691,
    'unrealizedPnl': -0.0425436}
```
If one counts the precision of the entryprice it seems to be 10 digits between the colon, which can't be found in the dict, neither in limits nor in precision.

**Comment by kroitor** [comment]
@spc789 the price precision on that contract is set to be 2 decimals by the exchange API as you can see from the `market['info']['pricePrecision']` – the `info` subdict contains the data as it has been received from the exchange API as is (as it is also documented in the CCXT Manual). The entryPrice has more digits since it's calculated as the average of the contract to notional ratio, and that depends on the market conditions, but the exchange will not accept more than 2 digits for the opening order if you try to place the order with more decimals. Let us know if you think that is wrong.

**Comment by kroitor** [comment]
@spc789 to clarify, please, read this section to understand how a single opening order can have "more than one price" leading to the entryPrice of a position having more than 2 decimals as in your case: https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades

**Comment by spc789** [comment]
@kroitor I noticed that the entryprice has more precision. Problems start when I calculate the average entryprice myself on the client side while not using the right amount of digits.

For example, suppose the entryprice on binance has 4 digits as precision, with some hypothetical orders :

We start with a hypothetical entryprice of 0.4562, place an order of 0.8755, the average becomes (0.4562+0.8755)/2 = 0.66585 I round it to 0.6659 because precision of the entryprice in this example is 4 digits. Let's do another hypothetical order of 0.2099. The average becomes : (0.6659+0.2099)/2 = 0.4379

Should in the hypothetical example the entryprice precision be 5 digits the last step in above is (0.66585 + 0.2099) / 2 = 0.437875, rounded to 5 digits it gives 0.43788. Which is slightly of the above. 

In above hypothetical example I know the precision because we started with a hypothetical entryprice where the precision is known. In this example 4. 

If one calculates entryprices on the fly at the client side with the data provided in the watch_order stream (like fillprice, lastfill etc) theres a possibility one doesn't know the entryprice precision because the possibility exists there wasnt an open order in the rest response for that specific pair which received fill data. In that specific case it becomes a guess (solely relying on the info in the watch order stream) what precision to use. If one doesnt use the right precision it gives rise to rounding errors. (in the example above with 3 orders a little bit, but sometimes I try to calculate the entryprice average for more then 10 orders and then the slightly off starts to become way more profound and hence it becomes more difficult to keep the client side calculated entryprice in sync with the entryprice on the exchange.

**Comment by kroitor** [comment]
> We start with a hypothetical entryprice of 0.4562, place an order of 0.8755, the average becomes (0.4562+0.8755)/2 = 0.66585 I round it to 0.6659 because precision of the entryprice in this example is 4 digits. Let's do another hypothetical order of 0.2099. The average becomes : (0.6659+0.2099)/2 = 0.4379

This is where the flaw starts, I think, cause the actual entryPrice is not calculated as (price1 + price2) / num_orders. It is calculated as the ratio of the filled trades' prices depending on the size of the filled trades. That is hard to catch, since market conditions fluctuate and that affects the actual prices of the filled trades in realtime.

**Comment by spc789** [comment]
Above was an example to clarify the rounding errors. 

In reality, indeed, average entryprice is calculated as :
> (prev_entryprice*abs(prev_quantity) + filled_price*abs(filled_quantity)) / (abs(prev_quantity) * abs(filled_quantity)) 

which even makes the rounding errors more profound because there are multiplications in that formula

**Comment by ttodua** [comment]
@spc789 I suspect that you might be trying to solve [XY problem](https://en.wikipedia.org/wiki/XY_problem). Can you please tell what are you trying to solve in reality (lets say you know entryprice precision and etcetera).

**Comment by spc789** [comment]
Hi @ttodua, 

1) In case I am able to calculate the average entryprice correctly on the client side with desired precision, with a correct entryprice I can calculate unrealised PNL and ROE on the client side too and can use these metrics/values in a strategy. Unrealised PNL and ROE depend on the average entryprice. (For example automatically close orders if the gain is 25% of the initial order size etc, calculate how fast unrealised pnl changes etc)
2) In case I am not able to calculate the average entryprice correctly the rounding error in the calculation propagates through all calculations as the average entryprice is calculated by (according to binance docs) the previous one and the current one with the formula I mentioned somewhere above. If the average entryprice is (slightly) off the av entryprice it should be, the calculated unrealised pnl is wrongly calculated afterwards on the client side and can't be used as a metric.

At the moment I'm using a workaround ie subscribing to the watch orders websocket and as soon as an order is filled for a pair/symbol I use the rest api to fetch the open positions for that pair and extract the entryprice from the info dict. This method works. However, instead of doing constantly rest requests as soon as an order is triggered I would rather calculate the entryprice on the client side, as doing much rest requests can trigger the limiter.

**Comment by ttodua** [comment]
@spc789 the thing that buzzed me what how that would affect the overal PLN stats would be distorted that much degree by that tiny detail, considering that if you trade a low volume (low budget) that the inaccuracy would be unnoticeable, and if you trade large volume, then fees charged by exchange would be far more important that such tiny precisional rounding miscalculation, and relying PLN efficiency on such dramatically low imperfection does not seem an ideal approach to me ( and i might have advised that you considered "worst" case, i.e. consider that rounding was done in worst way) . but who knows, maybe I am wrong and you are having some exceptional reasons for it, and ok, i'll understand. if you are going to continue on that, another thing comes to my mind is to not to use order's average entry price, but use `watch_my_trades` (or fetch_my_trades, depending how you do) and calculate PLN from them (but would be more trickier).

**Comment by ttodua** [comment]
I think there is not much more we can do, so, if anyone has any extra advise, feel free to post here and re-surface this subject.
