### ISSUE TITLE
Digifinex froze my account and wants money for unfroze 

### ISSUE THREAD

**Issue by AnastasiyaVoronova** [ccxt/ccxt#18393]
### Description

Hi, all! 
Unfortunately, I am user of Digifinex and it was my first attempt to take money from my account (I made verification my ID card, two-step verification with phone number, and so on).
I wanted to sell 1000 USDT and received answer from customer service, that to confirm that it's me, who makes this operation, I have to pay 1200 USDT to my account, and after that my transaction will be done. 
Before it, they froze my 1000 USDT and I couldn't receive them back, neither sell it.

Obviously, I don't have 1200 USDT for such 'confirmation'. 

Maybe someone could help me: 
1) unfroze my account without paying 1200 USDT
2) get back my 1000 USDT

thank you all in advance! Any advice will be helpful!

### Code

```
  

```

**Comment by Xyricon4445** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker11

**Comment by kroitor** [comment]
@AnastasiyaVoronova we've had reports of similar nature about Digifinex, please, post your story here in this duplicate thread: https://github.com/ccxt/ccxt/issues/7066
We will reconsider Digifinex's integration listing with CCXT based on that.
Thank you!
