### ISSUE TITLE
calls to ccxt.coinbase  only returning transactions made on Advanced, not vanilla

### ISSUE THREAD

**Issue by respectabiggle** [ccxt/ccxt#18394]
### Operating System

Win 10

### Programming Languages

JS

### CCXT Version

3.1.50

### Description

for both calls, only returned my handful of CB Advanced transactions, not my full 100+ Coinbase (vanilla) history.

> foo = await cb.fetchOrders ()
> bar = await cb.fetchMyTrades ()

Tried both old an new api key/secret combo

> old :  generated before Advanced existed
> new :  generated just now from vanilla platform
 

If it's my code that is the problem, I apologize in advance.
Thanks for all your hard work.  What an amazing library.

### Code

```
let uu = async function () {

	let cb = new ccxt.coinbase ({

		apiKey: 'mamasays',
		secret: 'foosball' 
	})
	
	cb.loadMarkets()

	res = await cb.fetchOrders ()
	res = await cb.fetchMyTrades ()

	log(res.length)
	log(res)

}
uu()
  

```

**Comment by Dan-krm** [comment]
@respectabiggle it doesn't look like coinbase provides endpoints that support those methods for their vanilla platform. There is v2 versions of a few methods that should work for the vanilla platform like `fetchMarketsV2`, `fetchTickerV2`, `fetchTickersV2` and `fetchAccountsV2`.

We also provided two methods `fetchMyBuys` and `fetchMySells` that are meant for the vanilla platform and can be used as a replacement for `fetchMyTrades`. And if you want to fetch all of your transactions on the vanilla platform `fetchLedger` should work for that.

**Comment by respectabiggle** [comment]
@Dan-krm That is awesome.  Thanks so much for taking the time to reply.
