### ISSUE TITLE
tidex fetch_balance incomplete python

### ISSUE THREAD

**Issue by hurtcomplex** [ccxt/ccxt#1839]
fetch_balance is meant to return the following.
'free/available' assets (works)
'used/frozen' assets (error)
'total/balance' assets (error)

Unfortunately, only the free/available one seems to work as everything else is returned as None even though I can confirm that they should return specific numbers. 

A lot of scripts require this information to operate properly.

**Comment by kroitor** [comment]
@hurtcomplex can you please post your verbose output (add `({'verbose':True})` to constructor params), like described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

?

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/pull/1870/files#diff-16dbf417e2857c1943c88aa3dd2c83efR1414

Let us know if this does not help. Closing it for now if you don't mind until we have a follow up on this. Feel free to reopen it or just questions if you have any. Thx!
