### ISSUE TITLE
[gatecoin][gateio](python) - lacks fetch_open_orders 

### ISSUE THREAD

**Issue by hurtcomplex** [ccxt/ccxt#1840]
Without fetch_open_orders or the equivalent, it is impossible to attain the necessary order_id to cancel an open order, not to mention run various other scripts.

**Comment by kroitor** [comment]
As you may know, this library is under active development. We are adding new features, bugfixes and missing methods every day. Your contributions are welcome!

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

Also, your particular question is covered in all aspects here:
- #71 

Let us know if this does not answer your question. Closing this as a duplicate for now.

Thx!
