### ISSUE TITLE
Ask questions about proxies. After updating ccxt to the latest version, you can no longer access the exchange. The old version is available, but the new version cannot be used.

### ISSUE THREAD

**Issue by ray147291617** [ccxt/ccxt#18408]
### ؜

Please advise, I am using a proxy to access the exchange, the following code, proxies access port 7890 of Clash to access the exchange. After I updated the latest version of ccxt, this error was reported, and it was prompted that the link to the exchange was wrong. How should the code of the new version of the proxies be adjusted?

exchange = ccxt.okex5({
    'apiKey': '*********',
    'secret': '*********',
    'password': '*********.',
    'enableRateLimit': True,
    'proxies': {'https': "http://127.0.0.1:7890", 'http': "http://127.0.0.1:7890"}
})

**Comment by ttodua** [comment]
Hi.
I will post a reply soon.

**Comment by FreekyDev** [comment]
@ray147291617
Have you tried `'proxies': {...}` -> `'aiohttp_proxy': "http://127.0.0.1:7890"`

**Comment by carlosmiei** [comment]
Hello @ray147291617, recently we unified proxies, can you please try to do this instead?
```Python
exchange = ccxt.okex5({
'apiKey': '',
'secret': '',
'password': '*********.',
'enableRateLimit': True,
'https_proxy': "http://127.0.0.1:7890", 
'http_proxy': "http://127.0.0.1:7890",
})
```

**Comment by ttodua** [comment]
@ray147291617 we have almost finished updating proxies documentations. I'll be posting a news once it's reflected and then you can choose the desired approach.
Just to confirm - did you use ccxt's synchronous python version?
I am now looking into the possible bug

**Comment by ray147291617** [comment]
Hello, thank you for your response. I'm glad to hear that the issue has been resolved following the code provided. By updating ccxt to the latest version and using the line of code you mentioned, `https_proxy': "http://127.0.0.1:7890/," the problem was resolved, and  access the exchange successfully. Thank you once again for your assistance.

**Comment by ray147291617** [comment]
> @ray147291617 we have almost finished updating proxies documentations. I'll be posting a news once it's reflected and then you can choose the desired approach. Just to confirm - did you use ccxt's synchronous python version? I am now looking into the possible bug
> 
> _(from next time, I suggest to use `okx` instead of `okex5`)_

Python version is 3.10.9. Thank you again for the information.
