### ISSUE TITLE
CRYPTO RECOVERY!!! 

### ISSUE THREAD

**Issue by andrewreedus7** [ccxt/ccxt#18416]
### Exchange Name

Reedus Andrew

### URL of the Exchange

https://github.com/

### URL of the Exchange's API docs

https://github.com/

### Why should this exchange be implemented?

“I invested with a Crypto broker without proper research to know what I was hoarding my hard-earned money into, only to find out it was a hoax and sham. I invested over $180,000 USD estimated to be 6.3 BTC. I was unable to make any withdrawals out of my initial deposits let alone the gains he claimed I have earned even after meeting the bogus fees and charges he is always requesting. Fortunately, I got to know about CYBER GENIE's Bitcoin recovery programmers through research and positive reviews on Google. After a couple of hours consulting with them, all my funds were recovered including my profits. I can’t thank these guys enough for making me not another prey to these scammers. Thank you Cyber Genie. Consult them via:
“Cy ber genie@ Cy ber services . com”
“WhatsApp!! +1,252,5,1,2-03,91”

**Comment by carlosmiei** [comment]
@andrewreedus7 One more post like this and you will be banned immediately.
