### ISSUE TITLE
coinbasepro :  fetchOrders() - "price" field - numbers are wonky

### ISSUE THREAD

**Issue by respectabiggle** [ccxt/ccxt#18412]
### Operating System

Win 10

### Programming Languages

JS

### CCXT Version

3.1.50

### Description

for rows where "average.price" was 

> 16186.81
> 16981.22
> 16978.36

"price" for same rows:

>  16200.00000000
> 169750.00000000  <- not a typo - had BTC price at six-figures
> 169980.00000000

Thanks as always 

### Code

```
const { log } = require('console')
const ccxt = require('ccxt')

let fo = async function () {

	

	let pro = new ccxt.coinbasepro ({
		apiKey: 'yesI',
		secret:  'rasTrent',
		password: 'myRoommateJakeIsAnIgnorantBaldhead'
	})
	
	pro.loadMarkets()

	array = await pro.fetchOrders ()										

	log(array) 


}
fo ()

```

**Comment by carlosmiei** [comment]
Hello @respectabiggle,
Sorry what is exactly the problem here?

**Comment by respectabiggle** [comment]
(Edited:  "info.price" -> "price" field ) 

Eh, though I was being helpful.   Assumed there was a math / rounding error.

Maybe the "price" field was my asking price? (or whatever it's called, "bid price", I'm not sure)

Thanks

**Comment by carlosmiei** [comment]
> (Edited: "info.price" -> "price" field )
> 
> Eh, though I was being helpful. Assumed there was a math / rounding error.
> 
> Maybe the "price" field was my asking price? (or whatever it's called, "bid price", I'm not sure)
> 
> Thanks

@respectabiggle Also not sure 😅, but if we have a rounding problem we should take a look yes but just bear in mind that for instance 1.0000 is exactly the same as 1 (the zeros might be omitted by the language).

**Comment by respectabiggle** [comment]
@carlosmiei Thank you

Upon second look, those fields (price, info.price) were definitely limit order prices I had set manually.

Sorry for the false alarm !
