### ISSUE TITLE
Issue with withdrawing from Exmo

### ISSUE THREAD

**Issue by romanakmath** [ccxt/ccxt#18411]
### ؜

Hi, I am new here, sorry if the question is stupid. I don't manage to withdraw the money from exmo with the following code
```
binance = ccxt.binance({
    "apiKey": '',
    "secret": '',
    'options': {
        'fetchCurrencies': True,
    },
})
binance.verbose = True
exmo = ccxt.exmo({
    'apiKey': '',
    'secret': '',
   
})
exmo.verbose = True

binance.load_markets()

code = 'USDT'
amount = 10

deposit_binance = binance.fetchDepositAddress(code, {'network': 'TRX'})


exmo.load_markets()
withdrawal = exmo.withdraw(
    code, amount, deposit_binance ['address'],  {'chain': 'TRC20'})
```
I get the following error. 

```
fetch Request: exmo POST https://api.exmo.com/v1.1/withdraw_crypt RequestHeaders: {'Content-Type': 'application/x-www-form-urlencoded', 'Key': '****', 'Sign': '****', 'User-Agent': 'python-requests/2.30.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: nonce=****&amount=10&currency=USDT&address=*****&chain=TRC20

fetch Response: exmo POST https://api.exmo.com/v1.1/withdraw_crypt 200 ResponseHeaders: {'Date': 'Thu, 29 Jun 2023 20:46:28 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'access-control-allow-methods': 'POST, GET, OPTIONS, PUT, DELETE', 'access-control-allow-headers': 'Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Key, Sign', 'access-control-allow-credentials': 'true', 'content-encoding': 'gzip', 'vary': 'Accept-Encoding', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '7df104e6eab12beb-FRA'} ResponseBody: {"result":false,"error":"Error 40035: Access is denied, param is not allowed"}
```

What does it mean and what can I do about it? I allowed all ips on exmo for testing. Many thanks in advance!

**Comment by kroitor** [comment]
@romanakmath make sure that your api keys have a permission to withdraw on the exchange website i your account settings. Let us know if that does not help. Feel free to reopen this issue or just post your reply here, we'll take a look.

**Comment by romanakmath** [comment]
Hi, I would suppose, I have the permission
<img width="1133" alt="Screenshot 2023-06-30 at 22 02 53" src="https://github.com/ccxt/ccxt/assets/18005462/af5477b0-5eb9-48b3-a80d-80c5c3732fe4">
also the command `exmo.fetchWithdrawals()` works for example

**Comment by kroitor** [comment]
@romanakmath hi! 

We assume you have the most recent version of CCXT (3.1.59). 

The correct unified parameter name for specified the withdrawal network is `network`. The exchange-specific parameter name is `transport`, so any of the following two code snippets should work:

```Python
exmo.load_markets()
withdrawal = exmo.withdraw(
    code, amount, deposit_binance ['address'],  {'network': 'TRC20'})
```

or

```Python
exmo.load_markets()
withdrawal = exmo.withdraw(
    code, amount, deposit_binance ['address'],  {'transport': 'TRC20'})
```

Let us know if that solves the issue for you or not, looking forward to hearing from you!

**Comment by romanakmath** [comment]
Hi, I've updated from version 3.1.24 to 3.1.59 and changed the code to `{'transport': 'TRC20'}`. I have unfortunately not any more funds to test it, but it seems to work since it gives `Your current balance is insufficient` error. I will close this issue now and will comment if some problem should occur related to it later.
