### ISSUE TITLE
fetch_open_interest_history() broken on gateio

### ISSUE THREAD

**Issue by mrpouley** [ccxt/ccxt#18427]
### Operating System

linux

### Programming Languages

python

### CCXT Version

3.1.37

### Code

```
import ccxt
gateio = ccxt.gateio()
gateio.fetch_open_interest_history("BTC/USDT:USDT")
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mrpouley/.local/lib/python3.11/site-packages/ccxt/gate.py", line 5238, in fetch_open_interest_history
    raise BadRequest(self.id + ' fetchOpenInterest() supports future markets only')
ccxt.base.errors.BadRequest: gateio fetchOpenInterest() supports future markets only
```

**Comment by carlosmiei** [comment]
Hello @mrpouley, that error means that as far as we know, Gate only provides that information in the API for expiring futures, and you're providing a swap/perpetual.

**Comment by mrpouley** [comment]
OK not sure what happened here but it worked perfectly fine a few weeks ago.

**Comment by carlosmiei** [comment]
@mrpouley Sorry I checked it and I think you're right, this check was added a few weeks ago inadvertently. I will check it as soon as possible.
