### ISSUE TITLE
Bybit AttributeError fetchTime when retrieving Balance

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#18437]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

4.0.4

### Description

When running my Bybit code in a larger program, it throws the below error when using client.fetch_balance. Not sure whether the issue is in the larger program or on CCXT's side. Please see code and error below, also let me know in case I can troubleshoot some more on my side. 

### Code

```
  
client = ccxt.bybit({'apiKey': "", 'secret': ""})
info = client.fetch_balance(params={'accountType': 'contract'})
```
    info = client.fetch_balance(params={'accountType': 'contract'})
  File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\bybit.py", line 2950, in fetch_balance
    self.load_markets()
  File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1427, in load_markets
    markets = self.fetch_markets(params)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\bybit.py", line 1396, in fetch_markets
    self.load_time_difference()
  File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 3603, in load_time_difference
    serverTime = self.fetchTime(params)
AttributeError: 'bybit' object has no attribute 'fetchTime'

**Comment by carlosmiei** [comment]
Hello @Tomas-MP,
I don't know exactly what causes this issue but is has to do with dynamically set props/methods like `fetchTime`. We had a similar report (on a different method) before. Nonetheless I will fix it as soon as possible by replacing `fetchTime` (runtime only) with `fetch_time` (always available)
