### ISSUE TITLE
Bitget/Huobi AttributeError handleOptionAndParam when retrieving Balance

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#18438]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

4.0.4

### Description

When running my Bitget/Huobi code in a larger program, it throws the below error when using client.fetch_balance. Not sure whether the issue is in the larger program or on CCXT's side. Please see code and error below, also let me know in case I can troubleshoot some more on my side.

### Code

```
  
client = ccxt.bitget({'apiKey': "", 'secret': ""})
info = client.fetch_balance()

client = ccxt.huobi({'apiKey': "", 'secret': ""})
info = client.fetch_balance()

```
  File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\bitget.py", line 2333, in fetch_balance
    subType, params = self.handle_sub_type_and_params('fetchBalance', None, params)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 3327, in handle_sub_type_and_params
    values = self.handleOptionAndParams(None, methodName, 'subType', defaultValue)  # no need to re-test params here
AttributeError: 'bitget' object has no attribute 'handleOptionAndParams'

  File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\huobi.py", line 2823, in fetch_balance
    marginMode, params = self.handle_margin_mode_and_params('fetchBalance', params)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 3337, in handle_margin_mode_and_params
    return self.handleOptionAndParams(params, methodName, 'marginMode', defaultValue)
AttributeError: 'huobi' object has no attribute 'handleOptionAndParams'

**Comment by carlosmiei** [comment]
Hello @Tomas-MP, 
I think this is the same issue as the other one, but I will also fix it. Thanks once again.
