### ISSUE TITLE
BUG: Bybit UTA v5 WatchOrders()

### ISSUE THREAD

**Issue by hanxuh-hub** [ccxt/ccxt#18441]
### Operating System

Windows 10, Ubuntu 20.04.6

### Programming Languages

python

### CCXT Version

4.0.3

### Description

The websocket method `.watch_orders()` does not work as expected. In the script attached, I place 2 orders with custom client ids and then cancel them after 1 second. `.watch_orders()` is supposed to return 4 messages: (open, bid_client_id) (open, ask_client_id) (canceled, bid_client_id) (canceled, ask_client_id). However, it returns (open, bid_client_id) (open, ask_client_id) (canceled, ask_client_id) (canceled, ask_client_id) with identical messages for the last two.

The problem does not exist on ccxt version 3.0.86 but exists after 3.1.48. Any clues? @carlosmiei @sc0Vu 

To replicate the results, you will need a UTA account with some funds (>10 USDT). Before running the script, replace api key and secret with yours. 

### Code

```
import time
import asyncio
import ccxt.pro as ccxt


async def place_and_cancel_orders(client):
    await asyncio.sleep(1)
    # fetch btc price
    btc_price = await client.fetch_ticker('BTC/USDT:USDT')
    bid = btc_price['bid']
    ask = btc_price['ask']
    # place orders
    client_id_bid = 'bid' + str(int(time.time() * 1000))
    client_id_ask = 'ask' + str(int(time.time() * 1000))
    await client.create_order(symbol='BTC/USDT:USDT', type='limit', side='buy', amount=0.001, price=bid-500, params={'orderLinkId': client_id_bid})
    await client.create_order(symbol='BTC/USDT:USDT', type='limit', side='sell', amount=0.001, price=ask+500, params={'orderLinkId': client_id_ask})
    await asyncio.sleep(1)
    # cancel orders
    await client.cancel_order(None, 'BTC/USDT:USDT', params={'orderLinkId': client_id_bid})
    await client.cancel_order(None, 'BTC/USDT:USDT', params={'orderLinkId': client_id_ask})


async def main():
    config={'apiKey': YOUR_API_KEY,
            'secret': YOUR_API_SECRET,
            'newUpdates': True,
            'enableRateLimit': False,
            'verbose': False}
    client = ccxt.bybit(config)
    await client.load_markets()

    task = asyncio.create_task(place_and_cancel_orders(client))

    for i in range(4):
        orders = await client.watch_orders()
        for order in orders:
            print(order)

    await task

    await client.close()


if __name__ == '__main__':
    asyncio.run(main())


```

**Comment by carlosmiei** [comment]
Hello @hanxuh-hub, thanks for reporting it, we will analyze it and revert.
