### ISSUE TITLE
WebSocket error handle is not working properly

### ISSUE THREAD

**Issue by Bladcoin** [ccxt/ccxt#18445]
### Operating System

Windows

### Programming Languages

JS

### CCXT Version

3.0.75

### Description

Hi. I had a misunderstanding with the error handling from `watch` fn. When I call fn, and if ws has been closed during this time, and the message I am sending is compressed by ws, then I get "The socket was closed while data was being compressed". 

Problem is follow: When I handle usually errors for ws( for instance `watchOrderBook`, `watchOrders` ) I can catch them from `try {} ... catch {}...` block but this error I cannot catch because it happen in sending request time

![image](https://github.com/ccxt/ccxt/assets/69966149/a4dd9343-3da3-4a8c-8836-5006180363cf)

I want to know how I can handle the error that was indicated in the image above?

Now I just rewrite watch fn for handle from my own code and set custom handlers( in my case I ignore it ) but I dont thinking that it is a better solution. My code is below

### Code

```
   constructor() {
   
   this.exchange.watch = this.watch.bind(this);

    }


    watch(url, messageHash, message = undefined, subscribeHash = undefined, subscription = undefined) {
    const client = this.client(url);
    const backoffDelay = 0;
    if ((subscribeHash === undefined) && (messageHash in client.futures)) {
      return client.futures[messageHash];
    }
    const future = client.future(messageHash);
    const connected = client.connect(backoffDelay);
    connected.then(() => {
      if (!client.subscriptions[subscribeHash]) {
        if (subscribeHash !== undefined) {
          client.subscriptions[subscribeHash] = subscription || true;
        }
        const options = this.safeValue(this.options, 'ws');
        const cost = this.safeValue(options, 'cost', 1);
        if (message) {
          if (this.enableRateLimit && client.throttle) {
            client.throttle(cost).then(() => {
              client.send(message);
            }).catch((e) => { console.log(e) });
          }
          else {
            client.send(message)
              .catch((e) => console.log(e));
          }
        }
      }
    });
    return future;
  }
```

**Comment by pcriadoperez** [comment]
Thanks for reporting @Bladcoin I will look into it.
