### ISSUE TITLE
[huobipro] Invalid signature error when withdrawing

### ISSUE THREAD

**Issue by HydroMining** [ccxt/ccxt#1844]
Huobipro responds with "Invalid signature" error when trying to withdraw...

- OS: All
- Programming Language version: Python 3.6.3
- CCXT version: 1056
- Exchange: Huobipro
- Method: withdraw

**Comment by kroitor** [comment]
Hi! Sorry for a long wait, can you please post verbose output and the code you use to reproduce this issue? https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue Thx!

**Comment by kroitor** [comment]
Feel free to reopen this if needed.
