### ISSUE TITLE
Error code -2015 connecting to Binance

### ISSUE THREAD

**Issue by AntoBr96** [ccxt/ccxt#18459]
### Operating System

MacOS

### Programming Languages

python

### CCXT Version

3.1.53

### Description

I am trying to connect to Binance through CCXT:

`exchange_id = 'binance'

exchange_class = getattr(ccxt, exchange_id) 

exchange = exchange_class({
    'apiKey': 'xxx',
    'secret': 'xxx',
})`

Each time I execute `exchange.fetchBalance()` I obtain the following error: `AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}`. On my Binance profile, API section, I flagged the following settings: 

- [v] Enable reading
- [v] Enable Spot & Margin Trading

with applied IP restrictions.

Please notice that, without IP restrictions, I can only read and, in that case, I am able to fetch the balance (but not submitting orders).

Thank you in advance for your help!

### Code

```
  

```

**Comment by kroitor** [comment]
@AntoBr96 please, try following code and let us know if that still fails or not. If it fails, please, post the failing request+response part of the verbose output.:

```python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance({
     'apiKey': 'YOUR_API_KEY',
     'secret': 'YOUR_API_SECRET',
})
exchange.verbose = True  # enable verbose mode
markets = exchange.load_markets() 
```

**Comment by carlosmiei** [comment]
Hello @AntoBr96 at first sight it seems a permissions issue (not a ccxt problem). Can you double-check if your IP hasn't or something like that?

**Comment by AntoBr96** [comment]
Many thanks to both @kroitor and @carlosmiei ! I solved the issue following this part of @kroitor advice: "you must have a public IP for it to work correctly". Before, I registered my private IP but, switching to the public one the problem is solved. 

Thank you again for your precious support!
