### ISSUE TITLE
Websocket missing for Crypto.com Derivatives

### ISSUE THREAD

**Issue by khukhunaishvili** [ccxt/ccxt#18464]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Describe the solution you'd like

Hello guys,

Crypto.com has websocket support for derivatives, but CCXT only supports websocket for spot trading. Do you have any plans to add websocket support for derivatives?

You can find the documentation here:  - https://exchange-docs.crypto.com/exchange/v1/rest-ws/index.html#trade-instrument_name

**Comment by Dan-krm** [comment]
@khukhunaishvili We'll be adding websocket support for derivatives on Crypto.com as soon as possible using the v1 documentation that you referenced

**Comment by khukhunaishvili** [comment]
@Dan-krm thank you. this Exchange v1 api is an upgraded version of Derivatives v1 api - https://exchange-docs.crypto.com/exchange/v1/rest-ws/index.html#introduction

**Comment by Dan-krm** [comment]
I opened a pull request that will allow you to use derivatives markets with all of our websocket methods on Crypto.com, we are also in the process of adding more websocket methods to Crypto.com that will be available soon
