### ISSUE TITLE
Kucoin - Amount precision is invalid

### ISSUE THREAD

**Issue by janeCMD** [ccxt/ccxt#1846]
Was testing Kucoin lately, with pair ETC/BTC. The api load_markets returns price and amount precision to be 8. When i create order, i get error from an exchange: Precision of ETC is 6.

**Comment by kroitor** [comment]
See `.currencies['ETC']`, they don't serve precision in markets.

```shell
node examples/js/symbols kucoin
```

<img width="830" alt="screen shot 2018-02-09 at 10 21 36" src="https://user-images.githubusercontent.com/1294454/36016244-1ee12d08-0d83-11e8-8ebc-cf7b53f03276.png">

Let us know if this does not answer your question. 

Thx!

**Comment by janeCMD** [comment]
Thanks... But actually, i am still being puzzled. I checked kucoin php, method create_order. Rounding of amounts and prices is included there... but i suspect mistake: 
`$order = array (
            'symbol' => $market['id'],
            'type' => strtoupper ($side),
            'price' => $this->price_to_precision($symbol, $price),
            'amount' => $this->truncate ($amount, $this->currencies[$base]['precision']),
        );`
Shouldnt be amount truncated by $quote currency precision instead of base ? That would explain, why i am getting this error when i should not get it.

**Comment by kroitor** [comment]
@janeCMD depends on which one you call base and which one you call quote. ETC is base, BTC is quote in ETC/BTC.

**Comment by janeCMD** [comment]
@kroitor OK, now i find where is the error. The method truncate in Exchange.php was using 

`return floatval ($number * $decimal_precision) / $decimal_precision;`

which was incorrect. This was bug which was already corrected in base here but i obviously didnt have up to date Exchange.php
