### ISSUE TITLE
OKX future exchange 

### ISSUE THREAD

**Issue by bebo12343** [ccxt/ccxt#18465]
### ؜

Dear what is the code of placing order on OKX future exchange ?

**Comment by sc0Vu** [comment]
Hi @bebo12343 

There are some examples for okx in https://github.com/ccxt/ccxt/tree/master/examples. You can create order with own api credentials.

Let me know if you have any questions.

**Comment by bebo12343** [comment]
@sc0Vu 


Brother this is complicated

I just need the normal formula (code) for place order on future OKX
