### ISSUE TITLE
About #12035. watchMyTrades problem in binance

### ISSUE THREAD

**Issue by Curro666** [ccxt/ccxt#18474]
### Operating System

windows 11

### Programming Languages

python

### CCXT Version

latest

### Description

file: https://github.com/ccxt/ccxt/tree/master/python/ccxt/pro/binance.py
line: 2081
code:
```python
def handle_my_trade(self, client: Client, message):
    messageHash = 'myTrades'
    executionType = self.safe_string(message, 'x')
    if executionType == 'TRADE':
```
..................

Hello!!,
It was reported some time ago that binance did not return results when using watch_my_trades.
I have been testing this week and I have seen a problem where the data is not displayed.
there is a filter that means that the data is not being processed.
In this line: `if executionType == 'TRADE':` it is filtered by `TRADE` and therefore nothing is received.
`executionType` from what I have been seeing is usually `"CANCELED"`, `"NEW"` and this is not treated so when there is some movement of orders it does not return any data.

BR

**Comment by samgermain** [comment]
> ### Operating System
> 
> windows 11
> ### Programming Languages
> 
> python
> ### CCXT Version
> 
> latest
> ### Description
> 
> file: https://github.com/ccxt/ccxt/tree/master/python/ccxt/pro/binance.py line: 2081 code:
> 
> ```python
> def handle_my_trade(self, client: Client, message):
>     messageHash = 'myTrades'
>     executionType = self.safe_string(message, 'x')
>     if executionType == 'TRADE':
> ```
> 
> ..................
> 
> Hello!!, It was reported some time ago that binance did not return results when using watch_my_trades. I have been testing this week and I have seen a problem where the data is not displayed. there is a filter that means that the data is not being processed. In this line: `if executionType == 'TRADE':` it is filtered by `TRADE` and therefore nothing is received. `executionType` from what I have been seeing is usually `"CANCELED"`, `"NEW"` and this is not treated so when there is some movement of orders it does not return any data.
> 
> BR

I think that you might be trying to use `watchOrders` instead. A trade cannot be cancelled, it has already been made. `NEW` also refers to new orders

**Comment by ttodua** [comment]
I think above answer covers the issue, so i'll close this. If any issues or questions, feel free to ask & reopen the topic.
