### ISSUE TITLE
watch_orders on okx throws a exception ‘key Error: 'timestamp'

### ISSUE THREAD

**Issue by JackieOnline** [ccxt/ccxt#18478]
### Operating System

ubuntu

### Programming Languages

python

### CCXT Version

4.0.9

### Description

the code is running well in binance, but bad in okx

btc/usdt:usdt 
swap

2023-07-06 18:04:04,950: Traceback (most recent call last):
  File "/home/ubuntu/eagle/eagle.py", line 37, in <module>
    main()
  File "/home/ubuntu/eagle/eagle.py", line 32, in main
    asyncio.run(stra.run())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/eagle/strategy/strategy.py", line 56, in run
    await asyncio.gather(*[exchange.run() for exchange in self.exchanges])
  File "/home/ubuntu/eagle/exchange/exchange.py", line 34, in run
    await asyncio.gather(self.ws_orderbook(self.watch_symbol),
  File "/home/ubuntu/eagle/exchange/exchange.py", line 69, in ws_orders
    orders = await self.watch_orders(symbol)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/eagle/venv/lib/python3.11/site-packages/ccxt/pro/okx.py", line 627, in watch_orders
    return self.filter_by_symbol_since_limit(orders, symbol, since, limit, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/eagle/venv/lib/python3.11/site-packages/ccxt/async_support/base/exchange.py", line 2507, in filter_by_symbol_since_limit
    return self.filter_by_value_since_limit(array, 'symbol', symbol, since, limit, 'timestamp', tail)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/eagle/venv/lib/python3.11/site-packages/ccxt/async_support/base/exchange.py", line 617, in filter_by_value_since_limit
    entryKeyGESince = entry[key] and since and (entry[key] >= since)
                      ~~~~~^^^^^
KeyError: 'timestamp'

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @JackieOnline,
Thanks for reporting it we will take a look asap.

**Comment by carlosmiei** [comment]
@JackieOnline I can't reproduce this issue locally. What kind of order are you placing?
```
 p okx watchOrders "BTC/USDT:USDT"  --sandbox
Python v3.10.9
CCXT v4.0.10
okx.watchOrders(BTC/USDT:USDT)
[{'amount': 1.0,
  'average': None,
  'clientOrderId': 'e847386590ce4dBCc098bc667d21c1fa',
  'cost': 0.0,
  'datetime': '2023-07-06T10:32:33.425Z',
  'fee': {'cost': 0.0, 'currency': 'USDT'},
  'fees': [{'cost': 0.0, 'currency': 'USDT'}],
  'filled': 0.0,
  'id': '597132798801035264',
  'info': {'accFillSz': '0',
           'algoClOrdId': '',
           'algoId': '',
           'amendResult': '',
           'amendSource': '',
           'attachAlgoClOrdId': '',
           'avgPx': '0',
           'cTime': '1688639553425',
           'cancelSource': '',
           'category': 'normal',
           'ccy': '',
           'clOrdId': 'e847386590ce4dBCc098bc667d21c1fa',
           'code': '0',
           'execType': '',
           'fee': '0',
           'feeCcy': 'USDT',
           'fillFee': '0',
           'fillFeeCcy': '',
           'fillNotionalUsd': '',
           'fillPnl': '0',
           'fillPx': '',
           'fillSz': '0',
           'fillTime': '',
           'instId': 'BTC-USDT-SWAP',
           'instType': 'SWAP',
           'lever': '3',
           'msg': '',
           'notionalUsd': '10.0023',
           'ordId': '597132798801035264',
           'ordType': 'limit',
           'pnl': '0',
           'posSide': 'long',
           'px': '10000',
           'quickMgnType': '',
           'rebate': '0',
           'rebateCcy': 'USDT',
           'reduceOnly': 'false',
           'reqId': '',
           'side': 'buy',
           'slOrdPx': '',
           'slTriggerPx': '',
           'slTriggerPxType': '',
           'source': '',
           'state': 'live',
           'stpId': '',
           'stpMode': '',
           'sz': '1',
           'tag': 'e847386590ce4dBC',
           'tdMode': 'cross',
           'tgtCcy': '',
           'tpOrdPx': '',
           'tpTriggerPx': '',
           'tpTriggerPxType': '',
           'tradeId': '',
           'uTime': '1688639553425'},
  'lastTradeTimestamp': None,
  'lastUpdateTimestamp': 1688639553425,
  'postOnly': None,
  'price': 10000.0,
  'reduceOnly': False,
  'remaining': 1.0,
  'side': 'buy',
  'status': 'open',
  'stopLossPrice': None,
  'stopPrice': None,
  'symbol': 'BTC/USDT:USDT',
  'takeProfitPrice': None,
  'timeInForce': None,
  'timestamp': 1688639553425,
  'trades': [],
  'triggerPrice': None,
  'type': 'limit'}]
```

**Comment by JackieOnline** [comment]
both on limit and market.  btc and eth swap. please repeat more times. it takes place over 50%, not ever time.

**Comment by carlosmiei** [comment]
> both on limit and market. btc and eth swap. please repeat more times. it takes place over 50%, not ever time.

@JackieOnline I will apply a patch to protect the code and avoid this issue regardless, thanks for your help.

**Comment by JackieOnline** [comment]
@carlosmiei thank you..
but there are another bug has been created by patch...
i used fetch_ohlcvs and it returns a array, looks like [16884885000,1961.68,1663.8...]
when use parse_ohlcv(), passed it to filter_by_since_limit()..

in 4.0.9 key is 0, it's ok
if (entry[key] >= since)

in 4.0.11 0
if (key in entry) and (entry[key] >= since)
.....alwasy false..

**Comment by JackieOnline** [comment]
@carlosmiei 
i try on 4.0.12
looks good
thank you

**Comment by carlosmiei** [comment]
@JackieOnline Thank you for reporting it (twice 😅 ) !
