### ISSUE TITLE
Bybit USDC options: ETH and SOL

### ISSUE THREAD

**Issue by Hadevmin** [ccxt/ccxt#18471]
### ؜

Programming Language version: Python 3.11
CCXT version: 4.0.8

Hi, 

I would like to get informations from USDC options on Bybit.
So I set `exchange.options['defaultType'] = 'option'` and after I get markets with `exchange.load_markets()`
When I list markets `exchange.markets`, I had only BTC contracts. 
I had try to fetch information manually from a ETH option like that: `await exchange.fetch_ticker('ETH/USD:USDC-230929-1200-C')` (the informations to build the name are corrects)
and I get: `ccxt.base.errors.BadSymbol: bybit does not have market symbol ETH/USD:USDC-230929-1200-C`

So I would like to know how interact with ETH/SOL options.

Thank you

**Comment by Hadevmin** [comment]
Another thing, for the initialization of the Bybit object, defaultType doesn't work:
```
import ccxt.asyncio as ccxt
ccxt.bybit({'apiKey': APIKEY', 'secret': SECRET', 'defaultType': 'option', })
```
When you call `options['defaultType']`, it's `swap`
But if you set the defaultType after initialization, it works.

**Comment by carlosmiei** [comment]
Hello @Hadevmin,

> Another thing, for the initialization of the Bybit object, defaultType doesn't work:

You need to put it inside `options`, example:

```Python
ccxt.bybit({'apiKey': APIKEY', 'secret': SECRET', 'options' : { defaultType': 'option'} })
```

Regarding the second question, we will take a look and ever asap.

**Comment by Hadevmin** [comment]
Hello @carlosmiei ,

Thank you for your answer. 
I'm sorry, I forgot how to initialize correctly... Thanks for the reminder.

I remain at your disposal if you need further information.

**Comment by Dan-krm** [comment]
@Hadevmin I opened a pull request that adds support for loading ETH and SOL option markets without the need for specifying the defaultType. I'll also be adding more option support to other methods on bybit soon

**Comment by Hadevmin** [comment]
@Dan-krm Thanks, I'm waiting for the PR to be merged to test your update.

**Comment by Hadevmin** [comment]
@Dan-krm Thanks for the PR.
I had test and all works! 918 contracts active on Bybit and 918 load with load_markets(). Well done, thank you!

One more thing, I don't remember if a specific exception is raise when you fetch a position for a contract where you haven't open position for this contract.
 For example: 
`await exchange_bybit.fetch_position('SOL/USD:USDC-230711-14-P')`
raise
```
File "\ccxt\base\exchange.py", line 850, in <lambda>
filtered_list = list(filter(lambda el: el in dictionary and dictionary[el] != '' and dictionary[el] is not None, key_list))
                                           ^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```
Do you have to catch 'TypeError' to know that you don't have an open position, or is it normally another raise exception?
