### ISSUE TITLE
OKX future  place order 

### ISSUE THREAD

**Issue by bebo12343** [ccxt/ccxt#18473]
### Programming Languages

python

### Description

Dears ,, what is the api formula (code) of placing order on OKX future ,, ?

**Comment by samgermain** [comment]
Here's [the documentation](https://docs.ccxt.com/#/?id=placing-orders) on how to place an order, it works for any exchange

We also have some example files on how to create an order

- https://github.com/ccxt/ccxt/blob/master/examples/py/coinbase-create-order.py (just swap coinbase for okx, and use the [correct market symbols](https://docs.ccxt.com/#/?id=contract-naming-conventions))
- https://github.com/ccxt/ccxt/blob/master/examples/py/create-order-position-with-takeprofit-stoploss.py#L0-L1

and you can check the [docstring](https://github.com/ccxt/ccxt/blob/master/python/ccxt/okx.py#L2188) to see if there are any specifics for your exchange

**Comment by bebo12343** [comment]
@samgermain 

My code : 

 exchange.create_order(symbol="XRP/USDT:USDT", type='market',side = "long" , amount=str(40))


Error code : 

File "c:\Users\user\Desktop\بوت منصات\order.py", line 155, in <module>
    exchange.create_order(symbol="XRP/USDT", type='market',side = "long" , amount=str(40))
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\okx.py", line 2330, in create_order
    response = getattr(self, method)(extendedRequest)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\types.py", line 25, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 2822, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 2819, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 602, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\okx.py", line 5954, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\ccxt\base\exchange.py", line 3169, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: okx {"code":"1","data":[{"clOrdId":"e847386590ce4dBCf9fede3f395dbbf7","ordId":"","sCode":"51000","sMsg":"Parameter side error","tag":"e847386590ce4dBC"}],"msg":""}

**Comment by kroitor** [comment]
@bebo12343 we've answered this question on Telegram: 

> Your side='long' argument is wrong as the error says, it has to be either 'buy' or 'sell'

- https://t.me/ccxt_chat/3649

Follow the instructions precisely, enable verbose mode and paste your verbose output here using this code:
```
markets = exchange.load_markets()
exchange.verbose = True  # after loading the markets
exchange.create_order(symbol="XRP/USDT:USDT", type='market',side = "buy" , amount=40)
```

**Comment by bebo12343** [comment]
@kroitor 

ccxt.base.errors.BadRequest: okx {"code":"1","data":[{"clOrdId":"e847386590ce4dBC34e3a805d4430256","ordId":"","sCode":"51000","sMsg":"Parameter posSide error ","tag":"e847386590ce4dBC"}],"msg":"All operations failed"}

What is mean ?

**Comment by kroitor** [comment]
@bebo12343 it means you have to add a `posSide` parameter to the failing call. Do you understand that?

(also, please, stop duplicating the same question in Telegram and on GitHub, cause it just takes more resources to help you, please pick one location for this question, either here on GitHub or there in Telegram).

**Comment by kroitor** [comment]
@bebo12343 fixing the posSide parameter error is done like documented in the Manual (you have to read and understand it to use this library efficiently, otherwise you will stumble on every single thing):

```Python
markets = exchange.load_markets()
# exchange.verbose = True  # uncomment for debugging to get verbose request+response
params = {'posSide': 'long'}
exchange.create_order(symbol="XRP/USDT:USDT", type='market',side = "buy" , amount=40, price=None, params)
```
