### ISSUE TITLE
[BiBox] Error 3000 when withdrawing

### ISSUE THREAD

**Issue by HydroMining** [ccxt/ccxt#1848]
BiBox responds with 

   {"error":{"code":"3000","msg":"\u8bf7\u6c42\u53c2\u6570\u9519\u8bef"}}

(compare https://github.com/ccxt/ccxt/issues/1287) error when trying to withdraw...

    OS: All
    Programming Language version: Python 3.6.3
    CCXT version: 1065
    Exchange: Huobipro
    Method: withdraw

**Comment by kroitor** [comment]
Do you have 2FA enabled for withdrawals?

**Comment by HydroMining** [comment]
No, not possible @BiBox - Will test your fix asap...

Thanks & regards,
Hydro

**Comment by kroitor** [comment]
> not possible @bibox 

Their docs disagree: https://github.com/Biboxcom/api_reference/wiki/home_en#341-v1transfer

> Will test your fix asap...

Standing by for updates from you. Thx!

**Comment by HydroMining** [comment]
Yes, i saw that but it's not implemented (yet) anywhere on the website like enabling/disabling or beeing able to be used with manual withdrawls. 

Additionally, version ccxt 1056 didn't throw that error, new 1066 still responds with "{"error":{"code":"3000","msg":"\u8bf7\u6c42\u53c2\u6570\u9519\u8bef"}}"

**Comment by kroitor** [comment]
Ok, I'll investigate further, thx for your feedback! Will get back to you with my findings.

**Comment by HydroMining** [comment]
No need to further investigate - You where right regarding the 2FA parameters!

When parsing my old logs i saw that some withdrawls in 1056 where denied because of DDos protection with another error **before** error 3000 came up.

I also went through their, well, strange, website for the 2FA settings - Looks login 2FA is simply implicit for withdrawls.

There's still a small flaw in bibox.py at line 486 where it should be

   'coin_symbol': currency['id'],

instead of

   'coin_symbol': currency,

With that and custom parameters "trade_pwd" & "totp_code" it works like a charm now...


Thanks for your help & great work on ccxt,
Hydro

**Comment by kroitor** [comment]
Thanks for your comprehensive report and for your feedback! Will fix the remaining issues asap.

**Comment by JT102** [comment]
How do you pass custom parameters "trade_pwd" & "totp_code" and also "addr_remark" I suppose?
I tried like this:  $res=$exchange->withdraw($currency,$amount,$address,array('trade_pwd'=>'XXXXXX',addr_remark=>'no',totp_code=>'XXXXXX'));
Thanks!

**Comment by Sukaesihessy** [comment]
Kenapa saya tidak dapat membuka line-tcr.py


Pada tanggal 10 Feb 2018 17.00, "JT102" <notifications@github.com> menulis:
