### ISSUE TITLE
the proxy error

### ISSUE THREAD

**Issue by wwwzone** [ccxt/ccxt#18481]
### Operating System

windows

### Programming Languages

python

### CCXT Version

ccxt-4.0.11

### Description

the code：
exchange = ccxt.binance({
    'timeout': 30000,
    'verbose': True,  # 启用调试模式
    'proxies': {
        'http_proxy': 'http://m_proxy:3128',
        'https_proxy': 'http://m_proxy:3128'
    }
})

data = exchange.fetch_ohlcv('BTC/USDT', '1m', since=exchange.parse8601('2021-01-01T00:00:00Z'), limit=1000)
the error info ：binance GET https://api.binance.com/api/v3/exchangeInfo
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)

During handling of the above exception, another exception occurred:

urllib3.exceptions.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)

The above exception was the direct cause of the following exception:

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))

there was no log in the proxy's access.log, and I cann't catch the net packect in wireshark。 so the error occurs in the ccxt lib. 

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @wwwzone, is there anything else you can share to help us debug this issue? We run CCXT through proxies and every day and has been working fine.

**Comment by ttodua** [comment]
Hi @wwwzone we had updated proxiefs functionality, and now it's unified across different languages: https://github.com/ccxt/ccxt/wiki/Manual#proxy 

can you try:
```
exchange = ccxt.binance({
    'timeout': 30000,
    'verbose': True,
    'http_proxy': 'http://m_proxy:3128',
})
```
or use `https_proxy` instead of `http_proxy`

**Comment by matam07** [comment]
How can i unset the proxy, as i'm getting this error
AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action, request ip: 130.176.104.78"}

Note: My system IP address is totally different 
Here is my code
const exchange = new ccxt.binance({
            apiKey: exchangeCredentials.apiKey,
            secret: exchangeCredentials.secretKey,
            enableRateLimit: true,
            options: {
              defaultType: "future",
            },
          });
          // console.log(exchangeCredentials,226)
          if(exchangeCredentials.network == 'TEST'){
            exchange.setSandboxMode(true); // enable sandbox mode
          }

          // console.log(side, positionSide, 33);
          const order = await exchange.createOrder(
            symbol,
            "market",
            side,
            quantity,
            price,
            {
              positionSide: positionSide,
            }
          );

**Comment by ttodua** [comment]
@matam07 we can't say anything, CCXT does not have any builtin turned on proxy, even that ip `130.176.104.78` is totally unrelated to ccxt. you might have some proxy settings either in your ccxt-related codes, or system-wide or even network-wide (residential router etc...). can't say more about this with your provided info.

**Comment by wwwzone** [comment]
When I change  'http_proxy': 'http://m_proxy:3128',
'https_proxy': 'http://m_proxy:3128'   to   'http': 'http://m_proxy:3128',
'https': 'http://m_proxy:3128'  , the error  go away.  thanks all !
