### ISSUE TITLE
fetchPositionsRisk() requires an array argument for symbols

### ISSUE THREAD

**Issue by spc789** [ccxt/ccxt#18498]
### Operating System

Linux

### Programming Languages

python

### CCXT Version

4.0.13

### Description

Seems like the bug from 18131 is still not solved in 4.0.13. Below code gives 
>binance fetchPositionsRisk() requires an array argument for symbols

Same error when one adds params={'type': 'future'} 

### Code

```
symbol = "LTC/USDT:USDT"
posResult = await exchange.fetchPositions(symbols = symbol)
```

**Comment by kroitor** [comment]
@spc789 the error says itself, the argument must be an array of symbols, not a single symbol:

```
symbol = "LTC/USDT:USDT"
posResult = await exchange.fetchPositions(symbols = [ symbol ])
```

**Comment by spc789** [comment]
Youre right, my excuses
