### ISSUE TITLE
Subscribing to Binance's bookTick data failed.

### ISSUE THREAD

**Issue by cclion** [ccxt/ccxt#18497]
### Operating System

Mac OS 13.4

### Programming Languages

JS

### CCXT Version

4.0.12

### Description

I subscribed to binance's bookTick data according to the documentation, but got an error.
Here is the error message:

--------------------------------------------------------------------------------------------

BTC/USDT TypeError: Cannot set properties of undefined (setting 'btcusdt@bookTicker')
    at binance.stream (/Users/grayson/Desktop/code/soliman/node_modules/ccxt/dist/cjs/src/pro/binance.js:117:73)
    at binance.watchTicker (/Users/grayson/Desktop/code/soliman/node_modules/ccxt/dist/cjs/src/pro/binance.js:766:63)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Code

```ts
// ts
import ccxt from "ccxt"
import { Ticker,Exchange } from "ccxt"

// your version must be 0.7+
console.log ('CCXT Version:', ccxt.version)

function handle (exchange: Exchange, symbol: string, ticker:Ticker) {
    console.log (new Date (), exchange.id, symbol, ticker)
}

async function loop (exchange: Exchange, symbol: string) {
    while (true) {
        try {
            const ticker = await exchange.watchTicker (symbol)
            handle (exchange, symbol, ticker)
        } catch (e) {
            console.log (symbol, e)
            // do nothing and retry on next loop iteration
            // throw e // uncomment to break all loops in case of an error in any one of them
            // break // you can also break just this one loop if it fails
        }
    }
}


async function main() {
 
    const binance = new ccxt.pro.binance()
    binance.options = { 'watchTicker': {
        'name': 'bookTicker', // ticker = 1000ms L1+OHLCV, bookTicker = real-time L1
    }}
    if (binance.has.watchTicker) {
        await loop (binance, 'BTC/USDT') // one symbol
    }
    
}

main ()


```

**Comment by kroitor** [comment]
@cclion you should not override all options, just replace this line with the following:

```TypeScript
    binance.options = { 'watchTicker': {
        'name': 'bookTicker', // ticker = 1000ms L1+OHLCV, bookTicker = real-time L1
    }}
```
↓
```TypeScript
    binance.options['watchTicker']['name'] = 'bookTicker'
```

Let us know if that does not help.

**Comment by kroitor** [comment]
Alternatively, try this:

```TypeScript
    const binance = new ccxt.pro.binance({
        'options': { 'watchTicker': 'bookTicker' },
    })
```

**Comment by kroitor** [comment]
@cclion feel free to reopen this issue or just post your comments here if the above does not work.
