### ISSUE TITLE
ErrorException in throttle() - usleep() expects parameter 1 to be integer, float given

### ISSUE THREAD

**Issue by ashbeats** [ccxt/ccxt#1850]
- OS: **Windows 10 64bit,   Ubuntu 16.04.3 LTS**
- Programming Language version: **PHP 7.1.7**
- CCXT version: **1.10.1050**
- Exchange: Any
- Method:  https://github.com/ccxt/ccxt/blob/3981848ea39d91100087016a64512a153e1e0492/php/Exchange.php#L721

## Summary:
usleep() expects parameter 1 to be integer, float given.

## Suggestion:
```
usleep ((int)($delay * 1000.0));
```

**Comment by kroitor** [comment]
Merged in #1851

**Comment by Sukaesihessy** [comment]
Saya tidak memiliki script utk membuat bot protech dengan 3 akun dengan my
github.mohon panduannya untuk script membuat bot protech


Pada tanggal 9 Feb 2018 16.23, "Igor Kroitor" <notifications@github.com>
menulis:
