### ISSUE TITLE
Coinbase - Staked Ethereum don't show up with fetchBalance()

### ISSUE THREAD

**Issue by theMoe** [ccxt/ccxt#18501]
After staking Ethereum on Coinbase the amount of Ethereum don't show up any more with fetchBalance().

Any idea how to access the staking balance?

**Comment by carlosmiei** [comment]
Hello @theMoe,
AFAIK Coinbase does not provide that information through the API.

**Comment by kroitor** [comment]
@theMoe closing this issue for now, feel free to reopen it or just ask further questions here if any.
