### ISSUE TITLE
Array is passed to function requiring string in /ccxt/php/async/Exchange.php:400  breaking watch_trades and watch_ohlcv.

### ISSUE THREAD

**Issue by anonFacePalm** [ccxt/ccxt#18506]
### Operating System

any

### Programming Languages

php

### CCXT Version

current

### Description

```PHP Fatal error:  Uncaught TypeError: mb_substr(): Argument #1 ($string) must be of type string, array given in /ccxt/ccxt/php/async/Exchange.php:400 ```

I've been trying to get watch_trades and watch_ohlcv to work on multiple exchanges, and something in ccxt was failing silently so the yield would never actually produce anything.  fetch_trades and fetch_ohlcv were working.

Anyway, after much digging, finally it produced an actual Error.

Here's the temporary stopgap fix in php, but as I don't currently know JS, someone else probably needs to fix this upstream.
Also, this may not provide the expected limitations, as it is merely a type checker.  But at least watch_trades and watch_ohlcv produce data now.

In [/ccxt/php/async/Exchange.php](https://github.com/ccxt/ccxt/blob/master/php/async/Exchange.php) , replace lines 399 and 425 ``` if($tail){ ```   with ``` if((is_string($result)) && ($tail)) {  ```

### Code

File:  [/ccxt/php/async/Exchange.php:385-401](https://github.com/ccxt/ccxt/blob/master/php/async/Exchange.php)
Starting from 385:  Looking at 387, 388, 390, and 394,  $result should be an array.  However, in 400:  $result (type: array) is passed to mb_substring, which is expecting a string, so it throws a TypeError.

```
public function filter_by_since_limit(mixed $array, ?int $since = null, ?int $limit = null, int|string $key = 'timestamp', $tail = false) {
        $sinceIsDefined = $this->valueIsDefined ($since);
        $parsedArray = $this->to_array($array);  //array
        $result = $parsedArray;  //array
        if ($sinceIsDefined) {
            $result = [ ];  //array
            for ($i = 0; $i < count($parsedArray); $i++) {
                $entry = $parsedArray[$i];
                if ($entry[$key] >= $since) {
                    $result[] = $entry;  //array
                }
            }
        }
        if ($tail) {
            return mb_substr($result, -$limit);     //mb_substr(string $string, int $start, ?int $length = null, ?string $encoding = null): string
        }
```

//From a cursory check, it appears this bug also happens in 426.

//My quick and dirty fix for this is to replace lines 399 and 425 as follows:

--- ```if($tail){```
+++ ```if((is_string($result)) && ($tail)) {```

**Comment by anonFacePalm** [comment]
This also appears in [/ccxt/php/Exchange.php:2225&&2251](https://github.com/ccxt/ccxt/blob/master/php/Exchange.php) and can be bypassed the same way.

**Comment by carlosmiei** [comment]
Hello @anonFacePalm, thanks for letting us know, will take a look asap

**Comment by anonFacePalm** [comment]
@carlosmiei  Yes, 4.0.17 works as is.  Thanks so much for quickly patching!
