### ISSUE TITLE
support for kucoin lending 2.0 API

### ISSUE THREAD

**Issue by kjnh10** [ccxt/ccxt#18510]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

none

### Describe the solution you'd like

I wish ccxt implement API for kucoin crypto lending 2.0.

https://docs.kucoin.com/#margin-trading-v3

### Describe alternatives you've considered

none

**Comment by carlosmiei** [comment]
Hello @kjnh10, 
Right now we support the v1 version of these endpoints, check for instance `borrowMargin` and `repayMargin` but we will try to add v3 very soon.
