### ISSUE TITLE
Huobi AttributeError when retrieving order information

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#18522]
### Operating System

Windows 10

### Programming Languages

python

### CCXT Version

4.0.14

### Description

Same as with issue #18507 but now for the fetch_orders() method, it throws another AttributeError. 

### Code

```
  

client = ccxt.huobi({'apiKey': "", 'secret': ""})
ticker = "XRP/USDT:USDT"
price = 0.4
quantity = 10
side = 'sell'
trigger = 'le'
leverage = 10

response = client.create_order(symbol=ticker, type="optimal_20",
                               side=side, amount=quantity, price=None,
                               params={'stopPrice': price,
                                       'triggerType': trigger,
                                       'offset': 'close',
                                       'lever_rate': leverage})
client.fetch_orders(ticker)

```
File "D:\OneDrive\Documenten\Github\cryptocurrency\tradingbot\functions\exchange.py", line 901, in
methods = [lambda: client.fetch_orders(ticker, params=par),
File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\huobi.py", line 3629, in fetch_orders
return getattr(self, method)(symbol, since, limit, params)
AttributeError: 'huobi' object has no attribute 'fetchContractOrders'

**Comment by carlosmiei** [comment]
Hey @Tomas-MP,
Same problem, so weird, what is your python version?

**Comment by Tomas-MP** [comment]
@carlosmiei will update python on all my devices, thank you for pointing this out!

**Comment by carlosmiei** [comment]
> @carlosmiei will update python on all my devices, thank you for pointing this out!

@Tomas-MP But can you share with us the python version used pls?

**Comment by Tomas-MP** [comment]
My Python version is 3.8.10

**Comment by Tomas-MP** [comment]
I am running my script in my anaconda environment via the windows terminal via the following code: 

pushd %~dp0
call "C:\Users\Tomas\anaconda3\Scripts\activate.bat"
"C:\Users\Tomas\anaconda3\python.exe" "D:\tradingbot\main.py"

Not sure whether this interferes with the dynamic attributes?

**Comment by carlosmiei** [comment]
> I am running my script in my anaconda environment via the windows terminal via the following code:
> 
> pushd %~dp0 call "C:\Users\Tomas\anaconda3\Scripts\activate.bat" "C:\Users\Tomas\anaconda3\python.exe" "D:\tradingbot\main.py"
> 
> Not sure whether this interferes with the dynamic attributes? It is also weird that the problem only is for Huobi, as I am running my bots also on Kucoin, Bybit and Bitget via CCXT.

@Tomas-MP We will try to replicate your environment, thanks for sharing it.
