### ISSUE TITLE
incorrect PHP syntax for append in multiple Pro/<name_of_exchange>.php files.

### ISSUE THREAD

**Issue by anonFacePalm** [ccxt/ccxt#18536]
### Operating System

any

### Programming Languages

php

### CCXT Version

4.0.17

### Description

the JS dot syntax might have been incorrectly transpiled in some of the pro/<name_of_exchange>.php files.  

[pro/bitpanda.php](https://github.com/ccxt/ccxt/blob/master/php/pro/bitpanda.php):  529, 732, 738, 990, 1000, 1017
line 529:
```$this->orders.append ($order);```
but should be:
```$this->orders->append ($order);```

coinex.php: 384, 758
deribit.php 615
krakenfutures.php 639
wazirx.php 616

### Code

```--- $this->orders.append ($order);```
```+++ $this->orders->append ($order);```

**Comment by kroitor** [comment]
@anonFacePalm thank you for reporting it, will fix this bug asap!
