### ISSUE TITLE
Coins which differ from coinmarketcap.com

### ISSUE THREAD

**Issue by Codewyvern** [ccxt/ccxt#1853]
- OS: Windows 7
- Programming Language version: Javascript
- CCXT version: Latest
- Exchange: Binance
- Method: loadMarkets()

I noticed there are quite a few coins that differ from coinmarketcap, I was using cmc to get more info about each coin like the change in 3 different timeframes. But I came across 4 coins that have different symbols on the exchange compared to the cmc ones.

An example of binance:
IOTA -> MIOTA
NANO -> XRB
BQX -> ???
YOYO -> YOYOW

Those are the only ones on binance it seems, but I only tested binance so far.
How do you propose to handle this type of thing? I remember the ccxt manual mentioning it does some auto conversions somewhere, but clearly this issue persists and will continue to persist as new coins are added.

An idea would be to write a script which crawls every single exchange and tries to find each coin on coinmarketcap, if it doesn't find it then add it to a list for conversion and a human manually updates this file? Thats the best I can think of right now.

**Comment by kroitor** [comment]
Hi!

Thx for reporting! I will fix the conflicts/inconsistencies shortly and will update you here.

> How do you propose to handle this type of thing?

The policy on symbol collisions is described here:
- https://github.com/ccxt/ccxt/issues/1330
- https://github.com/ccxt/ccxt/issues/1729

> An idea would be to write a script which crawls every single exchange and tries to find each coin on coinmarketcap, if it doesn't find it then add it to a list for conversion and a human manually updates this file?

Yep, something like that will do the job, we are adding a tool for that to our tests as well. Thx for sharing your thoughts!

**Comment by kroitor** [comment]
Here's what we have:

**IOTA vs MIOTA**

```
Currencies: (test @ search-all-exchanges.js:92)

id     code   exchange       name  active  status  fee
------------------------------------------------------
IOTA   IOTA   binance
IOT    IOTA   bitfinex
tIOTA  IOTA   bitfinex2
MIOTA  MIOTA  coinmarketcap  IOTA  true    ok
IOTA   IOTA   gateio
IOTA   IOTA   okex
```

Don't know if we should change the coinmarketcap code here, or all other exchanges, as most of them use `IOTA` instead of `MIOTA`.

**NANO vs XRB**

```
id     code   exchange       name       active  status  fee
-----------------------------------------------------------
NANO   NANO   binance
NANOX  NANOX  coinmarketcap  Project-X  true    ok
NANO   NANO   okex
NANOX  NANOX  yobi
```
```
id   code  exchange       name  active  status  fee
----------------------------------------------------
XRB  XRB   bitz
XRB  XRB   coinmarketcap  Nano  true    ok
XRB  XRB   kucoin         Nano  true    ok      0.05
```

Will rename to XRB, where appropriate.

**YOYO vs YOYOW**

```
id     code   exchange       name   active  status  fee  type    payin  payout  transfer
----------------------------------------------------------------------------------------
YOYO   YOYO   binance
YOYOW  YOYOW  coinmarketcap  YOYOW  true    ok
YOYOW  YOYOW  hitbtc
YOYOW  YOYOW  hitbtc2        Yoyow  true    ok           crypto  true   true    true
YOYO   YOYO   okex
```

Will check if those are all Waves-tokens and will most likely rename to YOYOW.

**Comment by Codewyvern** [comment]
Thanks for following up on this, this is just for binance or is this all the coins with problems? Yeah its a bit confusing what symbol to use, coinmarketcap is the number one coin tracker site, but if all exchanges use another common symbol then the coinmarketcap data is wrong. The only reason I am using coinmarketcap is because it has so much extra data compared to ccxt. For example I want to know hourly change% and total market cap in usd, so I am trying to combine both cmc data with the ccxt data in my scripts, sadly coinmarketcap doesn't even have all the coins on it so that's another pain to deal with.

**Comment by frossigneux** [comment]
I think that MIOTA should be renamed to IOTA in the CMC Python wrapper:
https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L261

Juste like it has been done in the JS wrapper:
https://github.com/ccxt/ccxt/commit/c09dee732d524fc8aeb6f0d356cdc645ea07980a

**Comment by Surf-N-Code** [comment]
Sorry to dig this up. 

BQC is now ETHOS. Can we put this into  this as well?
$this->commonCurrencies = array (
            'XBT' => 'BTC',
            'BCC' => 'BCH',
            'DRK' => 'DASH'
        );

**Comment by kroitor** [comment]
@Surf-N-Code i'll take a look into it shortly.
