### ISSUE TITLE
Fetch position Bybit

### ISSUE THREAD

**Issue by Hadevmin** [ccxt/ccxt#18541]
python 3.11
ccxt 4.0.19

Hello,

I don't remember if a specific exception is raise when you fetch a position for a contract where you haven't open position for this contract.
 For example: 
`await exchange_bybit.fetch_position('BTC/USD:USDC-230712-30500-P')`
raise
```
File "\ccxt\base\exchange.py", line 850, in <lambda>
filtered_list = list(filter(lambda el: el in dictionary and dictionary[el] != '' and dictionary[el] is not None, key_list))
                                           ^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```
Do you have to catch 'TypeError' to know that you don't have an open position, or is it normally another raise exception?

I have try on other exchange like deribit and I get a response without exception for same process:
`await exchange_deribit.fetch_position('BTC/USD:BTC-240628-120000-P'))`

**Comment by carlosmiei** [comment]
Hello @Hadevmin, no it is not expected to raise an exception, thanks for reporting it we will take a look.

**Comment by Hadevmin** [comment]
Thanks
