### ISSUE TITLE
OKX: ETH options

### ISSUE THREAD

**Issue by Hadevmin** [ccxt/ccxt#18547]
python 3.11
ccxt 4.0.19

Hello,

for OKX exchange, ETH options aren't load. Here a list of symbols with 'ETH' like 'base':
```
ETH/USDT
ETH/USDC
ETH/DAI
ETH/BTC
ETH/EURT
ETH/USD:ETH-230714
ETH/USD:ETH-230721
ETH/USD:ETH-230929
ETH/USD:ETH-231229
ETH/USDT:USDT-230714
ETH/USDT:USDT-230721
ETH/USDT:USDT-230929
ETH/USDT:USDT-231229
ETH/USDC:USDC-230714
ETH/USDC:USDC-230721
ETH/USDC:USDC-230929
ETH/USDC:USDC-231229
ETH/USD:ETH
ETH/USDT:USDT
ETH/USDC:USDC
```
`'options': {'defaultType': 'option'}` set in initialisation of ccxt.async_support.okx object. And for the BTC options, they are loaded.

Thanks

**Comment by carlosmiei** [comment]
Hello @Hadevmin,
thanks once again for reporting it we will check it.
