### ISSUE TITLE
Kraken: Index Error on fetch_trades

### ISSUE THREAD

**Issue by fredfortier** [ccxt/ccxt#1854]
- OS: Mac
- Programming Language version: Python 3.6
- CCXT version: 1.10.1069
- Exchange: Kraken
- Method: fetch_trades

Kraken.py line 533, is requesting index position 6 of the `trades` list which only holds six items.

I'm calling `fetch_trades` with with a symbol only. The list of trades seems to populate correctly until it reaches this line.
<img width="1552" alt="screenshot 2018-02-09 19 38 40" src="https://user-images.githubusercontent.com/1474114/36056418-5b6843e8-0dd2-11e8-9568-959d2eaa6793.png">

**Comment by kroitor** [comment]
Hi! Fixed in 1.10.1070.
Thanks for reporting, as always!
