### ISSUE TITLE
Abnormal order purchase

### ISSUE THREAD

**Issue by iockx** [ccxt/ccxt#18543]
### Operating System

Windows10

### Programming Languages

python

### CCXT Version

3.1.18

### Description

This issue occasionally occurs when placing an order to sell, but the cause of the problem has not been found
Do you know if there is a more elegant solution?
Thank you very much, brother
```
 {"msg":"Illegal characters found in parameter 'quantity'; legal range is '^([0-9]{1,20})(\\.[0-9]{1,20})?$'.","code":700008}
```

### Code

```
order_utils.create_order(exchange=exchange, amount=round(count, 2), price=price, side='sell')
```

**Comment by iockx** [comment]
Sorry to forget to mention that the docking is with the mx exchange

**Comment by carlosmiei** [comment]
Hello @iockx,
Can you provide a verbose log demonstrating that issue (`exchange.verbose=True`)? Also are you sure that `amount` never gets an invalid value like None?

**Comment by iockx** [comment]
> 你好@iockx， 您能否提供说明该问题的详细日志 ( `exchange.verbose=True`)？另外你确定`amount`永远不会得到像 None 这样的无效值吗？
Okay, I have added logs before and after the method. When this problem occurs again in the future, I will come back. Thank you for your reply

**Comment by kroitor** [comment]
@iockx closing this for now, feel free to reopen this issue when you have more input, or, ideally, just continue posting here.
