### ISSUE TITLE
OKX: edit_order

### ISSUE THREAD

**Issue by Hadevmin** [ccxt/ccxt#18549]
### ؜

python 3.11
ccxt 4.0.19

Hello,

For Okx exchange, the edit_order function raise `okx editOrder() does not support option orders, only spot orders are accepted`.
But in documentation: https://www.okx.com/docs-v5/en/#rest-api-trade-amend-order , we can read:
```
Rate limit rule (except Options): UserID + Instrument ID
Rate limit rule (Options only): UserID + Instrument Family
```
and no information that endpoint does not support Option orders.

Are you sure that Okx doesn't support amend order for Option orders?

Thanks

**Comment by carlosmiei** [comment]
Hello @Hadevmin, Yeah I think that requirement might be outdated, we will check it and revert asap.

**Comment by Hadevmin** [comment]
@carlosmiei 
I have commented the lines below to prevent control before sending the request:
```
# if not market['spot']:
        #     raise NotSupported(self.id + ' editOrder() does not support ' + market['type'] + ' orders, only spot orders are accepted')
```
I confirm that after commenting for test, my order amend has been successfully executed.

**Comment by carlosmiei** [comment]
@Hadevmin yeah we removed that in the latest version (4.0.23), so if you update it should work now.

Will close the issue but feel free to reopen it if anything.

Thanks
