### ISSUE TITLE
fetch u-main futures kline with quote asset volume and number of trades 

### ISSUE THREAD

**Issue by Vankeee** [ccxt/ccxt#18555]
### Exchange
Binance
### Programming Languages

python

### CCXT Version

1.91

### Description

I am confused about how to fetch u-main futures kline with quote asset volume and number of trades. What I can only find is the exchange.fetch_ohlcv function, but it dose not have data column " quote asset volume and number of trades".

Could big guys help me to figure out how to get these two columns?

**Comment by carlosmiei** [comment]
Hello @Vankeee,
First and foremost, I would recommend updating your ccxt version because it's too outdated and it does not include some significant updates that we did on binance.

Regarding your question, yes, those values (number of trades, quote volume) are not part of our unified response but you can easily get them by using the implicit API. 
Example (assuming you have an updated version 4+): 

```Python
    await exchange.load_markets(True)
    symbol = 'BTC/USDT:USDT' # change your market here
    market = exchange.market(symbol)
    params = {
        'interval': '1m',
        'limit': 500,
        'symbol': market['id']
    }
    ohlcv = await exchange.fapiPublicGetKlines(params)
    print(ohlcv)
```

**Comment by Vankeee** [comment]
Finally, I did by edit ccxt/binance.py.

`   def parse_ohlcv(self, ohlcv, market=None):
        # when api method = publicGetKlines or fapiPublicGetKlines or dapiPublicGetKlines
        #     [
        #         1591478520000,  # open time
        #         "0.02501300",  # open
        #         "0.02501800",  # high
        #         "0.02500000",  # low
        #         "0.02500000",  # close
        #         "22.19000000",  # volume
        #         1591478579999,  # close time
        #         "0.55490906",  # quote asset volume
        #         40,            # number of trades
        #         "10.92900000",  # taker buy base asset volume
        #         "0.27336462",  # taker buy quote asset volume
        #         "0"            # ignore
        #     ]
        #
        #  when api method = fapiPublicGetMarkPriceKlines or fapiPublicGetIndexPriceKlines
        #     [
        #         [
        #         1591256460000,          # Open time
        #         "9653.29201333",        # Open
        #         "9654.56401333",        # High
        #         "9653.07367333",        # Low
        #         "9653.07367333",        # Close(or latest price)
        #         "0",                    # Ignore
        #         1591256519999,          # Close time
        #         "0",                    # Ignore
        #         60,                     # Number of bisic data
        #         "0",                    # Ignore
        #         "0",                    # Ignore
        #         "0"                     # Ignore
        #         ]
        #     ]
        #
        return [
            self.safe_integer(ohlcv, 0),  # timestamp
            self.safe_number(ohlcv, 1),  # open
            self.safe_number(ohlcv, 2),  # high
            self.safe_number(ohlcv, 3),  # low
            self.safe_number(ohlcv, 4),  # close
            self.safe_number(ohlcv, 5),  # volume
            self.safe_number(ohlcv, 7),  # quote asset volume
            self.safe_number(ohlcv, 8),  # number of trades
            self.safe_number(ohlcv, 10),  # taker buy quote asset volume 

        ]`
