### ISSUE TITLE
Bit.com implementation cancelled?

### ISSUE THREAD

**Issue by Hadevmin** [ccxt/ccxt#18566]
Hello,

Regarding the PR https://github.com/ccxt/ccxt/pull/8869, there hasn't been an update for a long time.

I wonder if there was a red flag for not implementing this exchange or if it was just a matter of time. 

Thanks

**Comment by kroitor** [comment]
@Hadevmin 

> I wonder if there was a red flag for not implementing this exchange or if it was just a matter of time.

Yes, it is just a matter of time, we will get to reviewing and merging it asap, the delay is caused by the lack of human resources and the high demand, hope for your understanding.

**Comment by Hadevmin** [comment]
Hi @kroitor,
No problem, I was comparing several exchanges, which is why I asked if there was a "red flag". It wasn't to stress you out and tell you to quickly merge the PR.
Honestly, I'm impressed by your activity compared to the size of your team!
When I have a problem, @carlosmiei quickly submits a fix.
You do an excellent job and I understand that improvements can take time to be release.
Thank you for all your hard work!
