### ISSUE TITLE
Cryptopia: fetchOrder requires cached .orders

### ISSUE THREAD

**Issue by deltacat** [ccxt/ccxt#1856]
- OS: MacOS / CentOS
- Programming Language version: Nodejs v9.4
- CCXT version: 1.10.1074
- Exchange: cryptopia
- Method: fetchOrder

Created some limit orders. Then use a background thread to query/watch order status.
But cryptopia exchange return error like this:

`
cryptopia order 343589463 not found in cached .orders, fetchOrder requires .orders (de)serialization implemented for this method to work properly
`

For some reason, fetchOrders() is not suitable for this scene.

How to query order status via ID? I'm not sure it is cryptopia specified or common issue.

**Comment by kroitor** [comment]
Please, hold on, we're adding a section on *Order Cache* to the Manual here: https://github.com/ccxt/ccxt/pull/1870. After merging that PR (very soon) your question will be completely covered in the Manual. Sorry for the wait.

**Comment by kroitor** [comment]
Your question is now answered here: 
- https://github.com/ccxt/ccxt/wiki/Manual#querying-orders
- https://github.com/ccxt/ccxt/wiki/Manual#orders-cache
- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

Let us know if it does not help.

**Comment by deltacat** [comment]
Thanks a lot. The updated manual completely answered my question. :)

**Comment by kroitor** [comment]
@deltacat ok, thx for your feedback! Feel free to ask if you have further questions.
Also, some more Cryptopia-specific info with links to my posts on their forum on the limitations of their API. Still no answer from them, despite many people actually re-iterated my post...
