### ISSUE TITLE
API (GET /api/margin/v1/cross(or isolated)/account/assets) of Bitget should be private.

### ISSUE THREAD

**Issue by kjnh10** [ccxt/ccxt#18576]
### Operating System

Linux

### Programming Languages

python

### CCXT Version

3.1.53

### Description

The API which gets margin asset information is now put on public section, and if I Call it as public, bitget return authentication error.

### Code

```
  

```

**Comment by kjnh10** [comment]
site-packages/ccxt/abstract/bitget.py

<img width="1062" alt="image" src="https://github.com/ccxt/ccxt/assets/6933428/7135c526-39e8-4085-891f-d9dabf860e41">

https://bitgetlimited.github.io/apidoc/en/margin/#account

**Comment by carlosmiei** [comment]
Hello @kjnh10, thanks for letting us know we will check it asap.
