### ISSUE TITLE
Do not able to authenticate to Huobi

### ISSUE THREAD

**Issue by AntonDe** [ccxt/ccxt#18580]
### ؜

OS: Mac
Lang: python

Hi there,

I'm not able to authenticate to Huobi and getting the following error code:
```
ccxt.base.errors.AuthenticationError: huobi {"status":"error","err-code":"api-signature-not-valid","err-msg":"Signature not valid: Incorrect Access key [Access key错误]","data":null}
```
Here is my code:
```
huobiApi = os.environ.get('HUOBI_API_KEY')
huobiSecret = os.environ.get('HUOBI_SECRET')

huobiEx = ccxt.huobi({
   'apiKey': self.huobiApi,
   'secret': self.huobiSecret
})
```

This code works with other exchanges (Binance, Kraken etc). I was also printed the huobiApi and huobiSecret and compare it with the fresh created key on Huobi. The key has also all the necessary permissions (Read, Withdraw, Trade).

Do I miss a additional parameter or something else?

**Comment by kroitor** [comment]
@AntonDe which method/call is failing for you ? What is your version of CCXT? Please, enable verbose mode and post your code and verbose output (the failing request and response), follow the instructions here precisely (literally to a word):

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by AntonDe** [comment]
> @AntonDe which method/call is failing for you ? What is your version of CCXT? Please, enable verbose mode and post your code and verbose output (the failing request and response), follow the instructions here precisely (literally to a word):
> 
> * https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
> * https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Hi @kroitor 

sorry I forgot the important informations:

ccxt version = (3.0.56)

here is the output in the console:
`
Traceback (most recent call last):
  File "/Users/.../BinanceHuobiMainXmr.py", line 209, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/.../BinanceHuobiMainXmr.py", line 30, in main
    await trader.printCurrentAmounts()
  File "/Users/.../BinanceHuobiXmr.py", line 277, in printCurrentAmounts
    currentAmount = await self.getCurrentCoinAmounts()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../BinanceHuobiXmr.py", line 44, in getCurrentCoinAmounts
    currentHuobiBalance = await self.huobiEx.fetch_balance()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../venv/lib/python3.11/site-packages/ccxt/async_support/huobi.py", line 2826, in fetch_balance
    await self.load_accounts()
  File "/Users/.../venv/lib/python3.11/site-packages/ccxt/async_support/base/exchange.py", line 1622, in load_accounts
    self.accounts = await self.fetch_accounts(params)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../venv/lib/python3.11/site-packages/ccxt/async_support/huobi.py", line 2603, in fetch_accounts
    response = await self.spotPrivateGetV1AccountAccounts(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/...r/venv/lib/python3.11/site-packages/ccxt/async_support/base/exchange.py", line 1613, in request
    return await self.fetch2(path, api, method, params, headers, body, config, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../venv/lib/python3.11/site-packages/ccxt/async_support/base/exchange.py", line 1610, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../venv/lib/python3.11/site-packages/ccxt/async_support/base/exchange.py", line 180, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/Users/.../venv/lib/python3.11/site-packages/ccxt/async_support/huobi.py", line 5418, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], code, feedback)
  File "/Users/.../venv/lib/python3.11/site-packages/ccxt/async_support/base/exchange.py", line 1919, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: huobi {"status":"error","err-code":"api-signature-not-valid","err-msg":"Signature not valid: Incorrect Access key [Access key错误]","data":null}
`

Thank you

**Comment by carlosmiei** [comment]
Hello @AntonDe,
First and foremost, I would suggest updating your CCXT to the latest since during the last months, we did important upgrades across the entire lib.

Regarding your question, I just tested and seems to be working fine, so I suggest double-checking your API keys for empty spaces and things like that. Also, can you share with us what you're providing as `params` ? 

```
p huobi fetchAccounts                      
Python v3.10.9
CCXT v4.0.28
huobi.fetchAccounts()
[{'code': None,
  'id': 'dd',
  'info': {'id': 'dd',
           'state': 'working',
           'subtype': '',
           'type': 'point'},
  'type': 'point'},
 {'code': None,
  'id': 'xx',
  'info': {'id': 'xx', 'state': 'working', 'subtype': '', 'type': 'spot'},
  'type': 'spot'},
 {'code': None,
  'id': 'ss',
  'info': {'id': 'ss', 'state': 'working', 'subtype': '', 'type': 'otc'},
  'type': 'otc'},
 {'code': None,
  'id': 'xx',
  'info': {'id': 'xx',
           'state': 'working',
           'subtype': 'ltcusdt',
           'type': 'margin'},
  'type': 'margin'},
```

**Comment by AntonDe** [comment]
Hi @carlosmiei 

Thank you for the response, the update of ccxt seems to fix the issues and I'm now getting the data I expecting. Thank you

**Comment by carlosmiei** [comment]
> Hi @carlosmiei
> 
> Thank you for the response, the update of ccxt seems to fix the issues and I'm now getting the data I expecting. Thank you

@AntonDe no problem 🙂
