### ISSUE TITLE
binance async cancel_order wrong Exception

### ISSUE THREAD

**Issue by cfytrok** [ccxt/ccxt#1858]
OS: Windows 10
Programming Language version: python 3.6.3
CCXT version: 1.10.1074
Exchange: binance
Method: cancel_order

cancel_order methond in asynchronous mode raises AttributeError: 'NoneType' object has no attribute 'find' instead of OrderNotFound when order doesn't exist. 
Seems self.last_http_response is not set. line 724 binance.py.
Script crashes before Verbose output of responce, but previouse exception raises when handling this exception:
ccxt.base.errors.OrderNotFound: binance {"code":-2011,"msg":"UNKNOWN_ORDER"}

**Comment by kroitor** [comment]
@cfytrok are you using the sync or the async version of ccxt?

**Comment by cfytrok** [comment]
async
