### ISSUE TITLE
CCXT Cross exchange funds transfer

### ISSUE THREAD

**Issue by muhammad-rizwan-brainx** [ccxt/ccxt#18584]
> fetchDepositAddress would be used to get the address of account ? I am trying it with kraken exchange but it's not working @carlosmiei

@muhammad-rizwan-brainx Pls open a new issue, this one is not meant for these discussions.

_Originally posted by @carlosmiei in https://github.com/ccxt/ccxt/issues/15171#issuecomment-1637984172_

**Comment by carlosmiei** [comment]
Hello @muhammad-rizwan-brainx, what is not working exactly?

Please check this out to see how you should structure an issue in order to get help as fast as possible https://docs.ccxt.com/#/FAQ?id=what-is-required-to-get-help

**Comment by muhammad-rizwan-brainx** [comment]
@carlosmiei I thing you got my question. Would you mind answering otherwise you can just ignore it

**Comment by carlosmiei** [comment]
> I am trying it with kraken exchange but it's not working 

@muhammad-rizwan-brainx what can I conclude from "it's not working" ?  There is an infinite number of things that can fail, without seeing the stack, ccxt version, verbose log etc it's impossible to answer your question.
