### ISSUE TITLE
Exchange_id and Exchange Name conflict 

### ISSUE THREAD

**Issue by Mohdwaqas816** [ccxt/ccxt#18583]
### Operating System

Windows 11

### Programming Languages

python

### CCXT Version

latest 4

### Description

So When I iterate over all the exchange_id with their respective exchange name I did found two issues :-
1- Exchange ID: bitbay, Name: Zonda (Exchange_id bitbay is quoting to exchange name Zonda)
2- Exchange ID: bitcoincom, Name: FMFW.io (Exchange_id bitcoincom is quoting to exchange name FMFW)

please remove these because they are extra already we are getting the right one with their name but we also getting above two in addition.

### Code

```
  import ccxt
  def get_all_exchange_ids():
    exchanges = ccxt.exchanges
    exchange_ids = []

    for exchange_id in exchanges:
        exchange_class = getattr(ccxt, exchange_id)
        exchange_name = exchange_class().name
        exchange_ids.append((exchange_id, exchange_name))

    return exchange_ids

# Example usage:
all_exchange_ids = get_all_exchange_ids()
for exchange_id, exchange_name in all_exchange_ids:
    print(f"Exchange ID: {exchange_id}, Name: {exchange_name}")

```

**Comment by carlosmiei** [comment]
Hello @Mohdwaqas816, thanks for letting us know.

That happens because some exchanges are just an alias for other exchanges (for instance, bitbay is an alias for Zonda) and we're missing updating their names in the alias class. We will fix it shortly.
