### ISSUE TITLE
[Waves Exchange]- [Change domain name - to wx.network]

### ISSUE THREAD

**Issue by NikBuka** [ccxt/ccxt#18582]
### ؜

Since the Waves Exchange moved to a new domain wx.network, please change domain name in CCXT library from waves.exchange to **wx.network** .

**Comment by kroitor** [comment]
@NikBuka we're almost done implementing the conditional orders, have run a few tests already, will change the domain accordingly name upon merging.

**Comment by kroitor** [comment]
Related PR: https://github.com/ccxt/ccxt/pull/18578

**Comment by sc0Vu** [comment]
Hi @NikBuka 

It seems some links are still direct to https://docs.waves.exchange/ on https://wx.network/, eg. documentation and api documentation. Anyway, I'll test and update the new domain.

**Comment by NikBuka** [comment]
> Hi @NikBuka
> 
> It seems some links are still direct to https://docs.waves.exchange/ on https://wx.network/, eg. documentation and api documentation. Anyway, I'll test and update the new domain.

Hi @sc0Vu you may change link docs.waves.exchange on https://docs.wx.network/

**Comment by sc0Vu** [comment]
@NikBuka 

Do you mean all these api endpoints (for test and production)?:

```
'matcher': 'https://matcher-testnet.waves.exchange',
'node': 'https://nodes-testnet.wavesnodes.com',
'public': 'https://api-testnet.wavesplatform.com/v0',
'private': 'https://api-testnet.waves.exchange/v1',
'forward': 'https://testnet.waves.exchange/api/v1/forward/matcher',
'market': 'https://testnet.waves.exchange/api/v1/forward/marketdata/api/v1',
```

**Comment by NikBuka** [comment]
> @NikBuka
> 
> Do you mean all these api endpoints (for test and production)?:
> 
> ```
> 'matcher': 'https://matcher-testnet.waves.exchange',
> 'node': 'https://nodes-testnet.wavesnodes.com',
> 'public': 'https://api-testnet.wavesplatform.com/v0',
> 'private': 'https://api-testnet.waves.exchange/v1',
> 'forward': 'https://testnet.waves.exchange/api/v1/forward/matcher',
> 'market': 'https://testnet.waves.exchange/api/v1/forward/marketdata/api/v1',
> ```

Yes

**Comment by NikBuka** [comment]
Hey @sc0Vu, when do you plan release with our changes?

**Comment by NikBuka** [comment]
@kroitor hi, is  this issues already ready?

**Comment by kroitor** [comment]
> @kroitor hi, is this issue already ready?

Yes, I think we can close it already. Please let us know if you have issues with version 4.0.64+. Thanks for your patience!
