### ISSUE TITLE
fetchOHLCV method returns Promise<void>

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#18598]
### Operating System

windows 11 pro

### Programming Languages

JS

### CCXT Version

4.0.27

### Description

[ytigiev@screener ws_ohlcv]$ deno --version
deno 1.35.1 (release, x86_64-unknown-linux-gnu)
v8 11.6.189.7
typescript 5.1.6

Visual Studio Code is showing an error that the fetchOHLCV method returns Promise<void>.

(method) Exchange$1s.fetchOHLCV(symbol: any, timeframe?: string, since?: undefined, limit?: undefined, params?: {}): 

Promise<void>
[{
	"resource": "/home/ytigiev/adca2/ws_ohlcv/src/exchanges.ts",
	"owner": "deno",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'void'.",
	"source": "deno-ts",
	"startLineNumber": 46,
	"startColumn": 39,
	"endLineNumber": 46,
	"endColumn": 45
}]

### Code

```
export { default as ccxt } from "https://jspm.dev/ccxt@4.0.27";
////

const ohlcv = await exchange.fetchOHLCV(symbol, timeframe, since, FETCH_OHLCV_LIMIT);  

```

**Comment by sc0Vu** [comment]
Hi @YuriyTigiev 

It seems the type file wasn't loaded when use `export { default as ccxt } from "https://jspm.dev/ccxt@4.0.27";` (file: https://jspm.dev/npm:ccxt@4.0.27).

Would you like to install locally?

**Comment by YuriyTigiev** [comment]
The code works properly, but VSC displays errors

**Comment by kroitor** [comment]
@YuriyTigiev which exchange is it ?

**Comment by YuriyTigiev** [comment]
binance

**Comment by kroitor** [comment]
@YuriyTigiev it's weird since fetchOHLCV actually returns Promise<OHLCV[]> with latest version of CCXT:

- https://github.com/ccxt/ccxt/blob/dfec27e852009da9ecf71095abf66bb00a81ec43/js/src/base/Exchange.d.ts#L601

<img width="1022" alt="Screenshot 2023-07-19 at 08 10 38" src="https://github.com/ccxt/ccxt/assets/1294454/a4520ec6-72f6-465f-879c-ef30aedf79bf">

**Comment by YuriyTigiev** [comment]
Below my code. This code works, but the problem only with VSC for the Deno.

```
export async function fetchOHLCVData(exchange: Exchange, exchangeId: string, symbol: string, timeframe: string, since: number,
    maxRetries = 5, retryDelaySeconds = 2): Promise<OHLCVData[]> {
    let data: OHLCVData[] = [];
    let retry = 1;

    while (retry <= maxRetries) {
        try {
              loggerExchange.debug(`Fetching OHLCV records. Exchange: "${exchangeId}", symbol: "${symbol}", timeframe: "${timeframe}", since: "${since}"`);


            const ohlcv = await exchange.fetchOHLCV(symbol, timeframe, since, FETCH_OHLCV_LIMIT);
            const rtimestamp = ccxt.milliseconds();

            const ohlcvLength = ohlcv.length;

            if (ohlcvLength == 0) {
                loggerExchange.debug(`No data received from the exchange "${exchangeId}" for the symbol "${symbol}" with the timeframe "${timeframe}".`);
                return data;
            }

            data = transformData(exchangeId, symbol, timeframe, rtimestamp, ohlcv);

            loggerExchange.info(`Fetched ${ohlcvLength} OHLCV records from ${exchangeId} for ${symbol} with timeframe ${timeframe} since: ${since} ${ccxt.iso8601(since)}`);
            since = ohlcv[ohlcvLength - 1][0] + ccxt.parseTimeframe(timeframe) * 1000;

        } catch (error) {
            loggerExchange.error(`Failed to fetch OHLCV records from ${exchangeId} for ${symbol} with timeframe ${timeframe}. Error: ${error}. Retry: ${retry} of ${maxRetries}`);
            await wait(retryDelaySeconds);
            retry++;
        }
    }

    if (data.length === 0) {
        loggerExchange.error(`Failed to fetch OHLCV records from ${exchangeId} for ${symbol} with timeframe ${timeframe} after ${maxRetries} retries.`);
    }

    return data;
}

```

![image](https://github.com/ccxt/ccxt/assets/22752322/3fb7e3a9-a2dd-4eff-b1e9-a1ad92b5365b)

**Comment by kroitor** [comment]
@YuriyTigiev the JS build that is served from jspm does not contain the Exchange.d.ts file, so i think you will need to clone it or download a zip archive from CCXT's repository in order for Deno to recognize the type definitions, or configure it in some other way.

**Comment by YuriyTigiev** [comment]
I'm curious, why is the Exchange.d.ts file missing from the server? Who usually uploads these files?

**Comment by carlosmiei** [comment]
> I'm curious, why is the Exchange.d.ts file missing from the server? Who usually uploads these files?

@YuriyTigiev I think the problem here is that the browserified bundle does not include the types definition.

**Comment by YuriyTigiev** [comment]
Who is accountable for this?

**Comment by carlosmiei** [comment]
@YuriyTigiev Actually disregard what I said, I'm not sure how jspm works internally.

Can you try to import CCXT using specifiers instead? 

`import ccxt from "npm:ccxt";` 

CCXT is an ESM package by default so it should work.

**Comment by YuriyTigiev** [comment]
The issue has been resolved.

`export { default as ccxt } from "npm:ccxt@4.0.31"`
