### ISSUE TITLE
Bitfinex2 fetch_trades can crash while raising exception

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#18600]
Hello,

I have a problem with module `bitfinex2` because in some situation where the rate limit is reached the object `errorText` is set to None in the code below, which throws a TypeError exception : `TypeError: can only concatenate str (not "NoneType") to str`.

The problem appeared with:

```
>>> import ccxt
>>> b = ccxt.bitfinex2()
>>> b.fetch_trades('BTC/USD')
```

        if statusCode == 500:
            # See https://docs.bitfinex.com/docs/abbreviations-glossary#section-errorinfo-codes
            errorCode = self.number_to_string(response[1])
            errorText = response[2]
            feedback = self.id + ' ' + errorText
            self.throw_broadly_matched_exception(self.exceptions['broad'], errorText, feedback)
            self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
            self.throw_exactly_matched_exception(self.exceptions['exact'], errorText, feedback)
            print(self.id)
            print(response)
            print(errorText)
            print(errorCode)
            raise ExchangeError(self.id + ' ' + errorText + '(#' + errorCode + ')')
        return response

Would it be possible to fix this in the next release please ?

Similar issue : https://github.com/ccxt/ccxt/issues/12465

Best regards,
K

**Comment by carlosmiei** [comment]
Hello @Kinzowa, thanks for reporting it, will take a look asap
