### ISSUE TITLE
Bitforex get Wallet amounts and transfer between wallet and spot account

### ISSUE THREAD

**Issue by AntonDe** [ccxt/ccxt#18627]
### ؜

OS: MacOs
Programming Language: python
ccxt version: 4.0.29

Hi there, 

I'm trying to work with the Bitforex Exchange and facing a problem, that if i withdraw an fund to Bitforex it lands into the Wallet account. To be able to trade I need to transfer from wallet to spot. But somehow I do not able to check the following parameters:
- Wallet balance (calling the method bitforexExchange.fetch_balance() return the balance of the spot account)
- Transfer from Wallet to spot account

Are the methods for this not implemented yet?

Kind regards
Anton

**Comment by carlosmiei** [comment]
Hello @AntonDe,
Right now those functionalities are not available at bitforex because we didn't find a suitable endpoint able to provide them.

**Comment by ttodua** [comment]
I'll close the issue @AntonDe , if you notice any issue or have questions, feel free to post a follow-up.
