### ISSUE TITLE
Bybit error placing perptual order

### ISSUE THREAD

**Issue by martenzo7** [ccxt/ccxt#18626]
### Operating System

Linux

### Programming Languages

python

### CCXT Version

4.0.34

### Description

I'm trying to make a trading bot on bybit testnet useing ccxt, I'm tried to place order on BTC/USDT perptual but it's not working, it works just fine on spot trading

error:
```

ccxt.base.errors.BadRequest: bybit {"retCode":10001,"retMsg":"position idx not match position mode","result":{},"retExtInfo":{},"time":1690110862818}

```

NOTE: when i change the symbol "BTC/USDT:USDT" >> "BTC/USDT" it works but on the spot trading page not on the perptual.

### Code

```
  import ccxt
from pprint import pprint

exchange_id = 'bybit'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
    'api_key': "xxxx",
    'secret': "xxxx"
})
exchange.set_sandbox_mode(True)
exchange.options["defaultType"] = 'future'
exchange.load_markets()
res = exchange.fetchBalance()


params = {
    'reduce_only': True,
    'close_on_trigger': False,
}

order = exchange.create_order(symbol="BTC/USDT:USDT", type="Market", side="Buy", amount=4, price=50, params=params)

pprint(order)

```

**Comment by carlosmiei** [comment]
Hello @martenzo7, you just need to provide a value for `position_idx` inside `params`.

Example:

```Python
params = {
    'reduce_only': True,
    'close_on_trigger': False,
    'position_idx': 0 # 0 One-Way Mode, 1 Buy-side, 2 Sell-side
}

order = exchange.create_order(symbol="BTC/USDT:USDT", type="Market", side="Buy", amount=4, price=50, params=params)

pprint(order)
```

**Comment by martenzo7** [comment]
Hi [carlosmiei](https://github.com/carlosmiei),
still the same error, tried changing the price and the amount too. does that mean there is error with my API key?
```
ccxt.base.errors.BadRequest: bybit {"retCode":10001,"retMsg":"position idx not match position mode","result":{},"retExtInfo":{},"time":1690112176487}
```

**Comment by carlosmiei** [comment]
> Hi [carlosmiei](https://github.com/carlosmiei), still the same error, tried changing the price and the amount too. does that mean there is error with my API key?
> 
> ```
> ccxt.base.errors.BadRequest: bybit {"retCode":10001,"retMsg":"position idx not match position mode","result":{},"retExtInfo":{},"time":1690112176487}
> ```


@martenzo7 Which value did you use for `position_idx`? It needs to match your position mode, so if you're in hedged/dual side mode you need to provide 1 or 2

**Comment by martenzo7** [comment]
I changed the 'position_idx' to 1(since I'm in Buy mode) but this error showed up:

```
ccxt.base.errors.InvalidOrder: bybit {"retCode":140017,"retMsg":"current position is zero, cannot fix reduce-only order qty","result":{},"retExtInfo":{},"time":1690116471125}
```


code:
```
import ccxt
from pprint import pprint

exchange_id = 'bybit'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
    'api_key': "XXXX",
    'secret': "XXXX"
})
exchange.set_sandbox_mode(True)
exchange.options["defaultType"] = 'future'
exchange.load_markets()
res = exchange.fetchBalance()

params = {
    'reduce_only': True,
    'close_on_trigger': False,
    'position_idx': 1 # 0 One-Way Mode, 1 Buy-side, 2 Sell-side
}

order = exchange.create_order(symbol="BTC/USDT:USDT", type="Market", side="Buy", amount=4, price=50, params=params)


pprint(order)
```

**Comment by carlosmiei** [comment]
> I changed the 'position_idx' to 1(since I'm in Buy mode) but this error showed up:
> 
> ```
> ccxt.base.errors.InvalidOrder: bybit {"retCode":140017,"retMsg":"current position is zero, cannot fix reduce-only order qty","result":{},"retExtInfo":{},"time":1690116471125}
> ```
> 
> code:
> 
> ```
> import ccxt
> from pprint import pprint
> 
> exchange_id = 'bybit'
> exchange_class = getattr(ccxt, exchange_id)
> exchange = exchange_class({
>     'api_key': "XXXX",
>     'secret': "XXXX"
> })
> exchange.set_sandbox_mode(True)
> exchange.options["defaultType"] = 'future'
> exchange.load_markets()
> res = exchange.fetchBalance()
> 
> params = {
>     'reduce_only': True,
>     'close_on_trigger': False,
>     'position_idx': 1 # 0 One-Way Mode, 1 Buy-side, 2 Sell-side
> }
> 
> order = exchange.create_order(symbol="BTC/USDT:USDT", type="Market", side="Buy", amount=4, price=50, params=params)
> 
> 
> pprint(order)
> ```

@martenzo7 In that case if you don't have an opposite position opened you should not provide `reduce_only` in `params`

**Comment by martenzo7** [comment]
price error:
```

ccxt.base.errors.InsufficientFunds: bybit {"retCode":140007,"retMsg":"remark:order[438552 e1d49c8f-40e5-46a4-a4a0-a21e2c993906] fix price failed for CannotAffordOrderCost.","result":{},"retExtInfo":{},"time":1690118843569}

```
code:
```
import ccxt
from pprint import pprint

exchange_id = 'bybit'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
    'api_key': "XXXX",
    'secret': "XXXX"
})
exchange.set_sandbox_mode(True)
exchange.options["defaultType"] = 'future'
exchange.load_markets()
res = exchange.fetchBalance()

params = {
    'reduce_only': False,
    'close_on_trigger': False,
    'position_idx': 1 # 0 One-Way Mode, 1 Buy-side, 2 Sell-side
}

order = exchange.create_order(symbol="BTC/USDT:USDT", type="Market", side="Buy", amount=4, price=50, params=params)


pprint(order)

```

**Comment by martenzo7** [comment]
Thank you so much, It worked I just change the amount to `0.005`
