### ISSUE TITLE
bybit and bitget fetch_trades since error

### ISSUE THREAD

**Issue by kawaimineriko** [ccxt/ccxt#18620]
import ccxt

bitget = ccxt.bitget({'enableRateLimit': True,'rateLimit': 150})
bybit = ccxt.bybit({'enableRateLimit': True,'rateLimit': 150})

print(bitget.fetch_trades('STMX/USDT:USDT',since=1690015721830))
print(bybit.fetch_trades('STMX/USDT:USDT', since=1690015721830))

Only the transaction records of the latest time are printed out, and the transaction records of my given timeline are not printed

**Comment by carlosmiei** [comment]
Hello @kawaimineriko, what is your ccxt version?

**Comment by kawaimineriko** [comment]
@carlosmiei VERSION 3.0.44

**Comment by carlosmiei** [comment]
@kawaimineriko Can you please update to the latest and try again? We made a lot of upgrades in the meantime.

**Comment by kawaimineriko** [comment]
Successfully installed ccxt-4.0.34
the problem is still there

**Comment by carlosmiei** [comment]
@kawaimineriko Ok, the problem is that the bybit's endpoint does not accept  the `since` filter, so we can only filter the results after receiving them from the exchange: https://bybit-exchange.github.io/docs/v5/market/recent-trade.

At bitget it is possible by using a different endpoint (the default one does not accept a since value either), in this case through the implicit API, example:

```Python 
symbol = 'BTC/USDT:USDT'
await exchange.load_markets()
market = exchange.market(symbol)
params = {
   'symbol':market['id'],
   'startTime': SINCE_VALUE
}
trades = await exchange.publicMixGetMarketFillsHistory(params)
```

**Comment by kawaimineriko** [comment]
@carlosmiei do you mean that you can only download and sort through the data released by bybit?

**Comment by kawaimineriko** [comment]
okay,thanks

**Comment by carlosmiei** [comment]
> @carlosmiei do you mean that I can only download and sort through the data released by bybit?

@kawaimineriko That is what ccxt does now, but since bybit only retrieves the last 500 trades we cannot control the "start" time, if they have 500 in one minute we will get only 1 minute of trades.
