### ISSUE TITLE
Lykke: changed deposit and withdrawal fees on the 7th of februari

### ISSUE THREAD

**Issue by Quivelus** [ccxt/ccxt#1863]
Hi,

Lykke changed deposit and withdrawal fees on the 7th of februari.

Link to the website:
https://www.lykke.com/cp/wallet-fees-and-limits

Regards,
Quiv

**Comment by kroitor** [comment]
We will add web scraping for these URLs:

- https://www.lykke.com/cp/api-wallet-trading-rules-fees-limits
- https://www.lykke.com/cp/wallet-fees-and-limits

**Comment by kroitor** [comment]
Thank you for your feedback!
