### ISSUE TITLE
bitstamp timeframes wrong

### ISSUE THREAD

**Issue by patrick-geyer-21** [ccxt/ccxt#18649]
### Operating System

Mac

### Programming Languages

JS

### CCXT Version

^3.1.58

### Description

new ccxt.bitstamp().timeframes listed as : 

{
  '1m': '60',
  '3m': '180',
  '5m': '300',
  '15m': '900',
  '30m': '1800',
  '1h': '3600',
  '2h': '7200',
  '4h': '14400',
  '6h': '21600',
  '12h': '43200',
  '1d': '86400',
  '1w': '259200'
}

Oddly 1w is actually only 3 days, so don't know why it's represented as 1w.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @patrick-geyer-21, 
Thanks for letting us know, we will fix it as soon as possible
