### ISSUE TITLE
Failure to execute market orders on the Binance exchange.

### ISSUE THREAD

**Issue by prepheadrus** [ccxt/ccxt#18663]
### Operating System

Windows, Linux

### Programming Languages

JavaScript

### Description
I trade on the Binance exchange using Superalgos for algorithmic trading.
About 1 week ago I noticed that Superalgos was not executing the market orders I sent on the spot market. This is the error I got on the Superalgos side: 
"Error = binance {"code":-1013, "msg": "Quote order qty market orders are not supported for this symbol."}"

I then contacted binance customer service.
The customer representative told me that they are aware of the problem and are working to fix it. Their response was:
"We have ongoing maintenance that may affect the "quoteOrderQty" parameter for spot orders. Currently, quoteOrderQty is temporarily suspended in both the UI and API until further notice"

Here is Binance's announcement on this issue.

https://www.binance.com/en/support/announcement/binance-to-resume-the-market-order-function-for-all-spot-and-margin-trading-pairs-cc552486b23f4feeba4ffa9d01aa7d16

When I queried the exchangeInfo endpoint, they told me that the "quoteOrderQtyMarketAllowed" value is returned as "false", which tells me that the problem persists. 
When the query returns "true" we should know that the issue is resolved.

(for the query)

https://api.binance.com/api/v3/exchangeInfo?symbol=BTCTUSD

Finally, they suggested that you use the "quantity" parameter instead of "quoteOrderQty" in Spot Market orders to solve the problem in this process.

Is there anyone who can help with this?

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @prepheadrus, thanks for reporting it.
Can you please share with us your ccxt version and a minimal minimal reproducible example?

**Comment by ttodua** [comment]
@prepheadrus 
as suggested above, please post a minimal example of what code do you use.
I'm successfully running i.e.:
```
myOrder = await ex.createOrder('ADA/USDT', 'market', 'buy', 35);
````
but if I add a price parameter to market orders, then I am able to get the error message you say:
```
myOrder = await ex.createOrder('ADA/USDT', 'market', 'buy', 35, 1.2345);
```

So, I suggest that you remove price argument from market orders, so ccxt can use the way it does to submit market-order successfully. if you want to use a price, maybe you switch to use `limit` order instead of `market` with the desired ceiling price?

**Comment by ttodua** [comment]
I think the above answer should cover your request, if not, feel free to post a follow-up, so I'll continue support your issue.

**Comment by Awhiteweb** [comment]
So from what I can tell from testing myself using your example

This works:
```
let order = await exchange.createOrder('BTC/TUSD', 'market', 'buy', 1);
```

but neither of these work
```
let order = await exchange.createOrder('BTC/TUSD', 'market', 'buy', 1, 1);
let order = await exchange.createOrder('BTC/TUSD', 'market', 'buy', 1, 1, params);
```
and they return the following error:
```
InvalidOrder: binance {"code":-1013,"msg":"Quote order qty market orders are not supported for this symbol."}
```

**Comment by ttodua** [comment]
yes, that's what I said, so at this moment you should just set price argument to `undefined`:
```
let order = await exchange.createOrder('BTC/TUSD', 'market', 'buy', 1, undefined, params);
```

**Comment by Awhiteweb** [comment]
🤦🏻‍♂️ I misread your answer in my enthusiasm to contribute.

**Comment by prepheadrus** [comment]
> @prepheadrus as suggested above, please post a minimal example of what code do you use. I'm successfully running i.e.:
> 
> ```
> myOrder = await ex.createOrder('ADA/USDT', 'market', 'buy', 35);
> ```
> 
> but if I add a price parameter to market orders, then I am able to get the error message you say:
> 
> ```
> myOrder = await ex.createOrder('ADA/USDT', 'market', 'buy', 35, 1.2345); // side-note: you might not need to use `quoteOrderQty` param, because ccxt achieves the same thing that when you input price in market-order arguments, thus `quoteOrderQty` is set by `price * amount` within ccxt
> ```
> 
> So, I you can remove price argument from market orders, so ccxt can use the way mentioned as "submit an order using quantity" before the API resumes trading using quoteQty.

/My coding knowledge is almost zero. That's why my developer friend @Awhiteweb , from the Superalgos project got involved in the subject.

**Comment by ttodua** [comment]
You are welcome, absolutely no problem, feel free to post & comment anytime you think there is any issue in ccxt.

**Comment by BastianMuc** [comment]
Just using the opportunity to obtain your advice as I'm working on implementing the fix on our side:

We integrate with several other exchanges beyond Binance. I'm currently asking myself if I should set the price parameter to undefined only for Binance in case of market orders, or if I should do that in general.

What's confusing me is that per https://docs.ccxt.com/#/README?id=placing-orders , price should be ignored for market orders in any case. Obviously, it though makes a difference if the parameter is filled or not.

Many thanks for your fast and truly helpful support, very impressive!

**Comment by ttodua** [comment]
@BastianMuc you don't need to use price param for market-orders (that is the expected first-come behavior) but there are some exchanges which will "require" price arg also, because they calculate price*amount quote quantities. you can check such exchanges by `exch.options.createMarketBuyOrderRequiresPrice` being set to `true`.

**Comment by BigGremlin** [comment]
I just wanted to say thank you to you, @ttodua , for all your help on this issue!! You have helped our community very much!!! Thank You!!

**Comment by ttodua** [comment]
@BigGremlin you are welcome ;)
