### ISSUE TITLE
bitmex watch_order_book still return wrong size

### ISSUE THREAD

**Issue by TNumFive** [ccxt/ccxt#18665]
### Operating System

ubuntu22.04

### Programming Languages

Python

### CCXT Version

4.0.39

### Description

`watch_order_book` of `ccxt.pro.bitmex` still returns wrong size, raw data from exchange shall be converted by `convert_from_raw_quantity` just like `fetch_order_book` from `ccxt.async_support.bitmex`.

### Code

```
  

```

**Comment by samgermain** [comment]
Can you clarify the way in which it is wrong?

**Comment by TNumFive** [comment]
Precision of size value not adjusted;
Take BTC/USDT as example, the best bid shall like  `[29390.0, 0.0175]`, but it gives me  `[29390.0, 1750000.0]`;
You can try the `fetch_order_book` and `watch_order_book` to verify the problem I mentioned.

**Comment by carlosmiei** [comment]
Hello @TNumFive, yeah you're right we need to uniformize the amounts in the WS module as well. Thanks for letting us know, will be updated as soon as possible.

**Comment by TNumFive** [comment]
Hello @carlosmiei , I found that only spot's symbol are adujsted in async, due to realted function has a weird `if-clause`
```python
# quote from ccxt.async_support.bitmex line 403
def amount_to_precision(self, symbol, amount):
    symbol = self.safe_symbol(symbol)
    market = self.market(symbol)
    oldPrecision = self.safe_value(self.options, "oldPrecision")
    # **why limit to spot?**
    if market["spot"] and not oldPrecision:
        amount = self.convert_from_real_amount(market["base"], amount)
    return super(bitmex, self).amount_to_precision(symbol, amount)

def convert_from_raw_quantity(self, symbol, rawQuantity, currencySide="base"):
    if self.safe_value(self.options, "oldPrecision"):
        return self.parse_number(rawQuantity)
    symbol = self.safe_symbol(symbol)
    marketExists = self.in_array(symbol, self.symbols)
    if not marketExists:
        return self.parse_number(rawQuantity)
    market = self.market(symbol)
    # **why limit to spot?**
    if market["spot"]:
        return self.convert_to_real_amount(market[currencySide], rawQuantity)
    return self.parse_number(rawQuantity)
```

**Comment by carlosmiei** [comment]
@TNumFive I believe this issue is fixed now, but feel free to re open it if needed.
