### ISSUE TITLE
Normalization of timestamps reported by fetch_ohlcv()

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#18664]
Hello,

I was wondering how to interpret the timestamp of the candlesticks built by CCXT and I guess the timestamps correspond to the beginning of the time interval, not the end. I would love a confirmation from you guys, and would love to know if timestamps reported by exchanges are standardized by the library ? specifically for those echanges that report timestamps at the end of the period (Bitmex?).

Candlesticks are usually used for visualization and this situation timestamps are not so important, but when candlesticks are used for data modelization and strategy backtesting then **timestamps are very relevant**.

The documentation states that "info from the last (current) candle may be incomplete until the candle is closed" which implicitly means that timestamp correspond to the beginning of the time period. However, I could find this information in the documentation and I think it would be very informative to add it in the ohlcv-structure section.

Regards,
K

https://docs.ccxt.com/#/?id=ohlcv-structure

**Comment by carlosmiei** [comment]
Hello @Kinzowa, no, the timestamp is not standardized by CCXT (only its unit, milliseconds), we return what the exchange returns in the API, but most of the time, it represents the beginning of the candle.

**Comment by Kinzowa** [comment]
Hi @carlosmiei, thanks for the answer. I assume the timezone isn't normalized too, please let me know if it's the case.
