### ISSUE TITLE
In the PHP example, the quoinex file cannot be found

### ISSUE THREAD

**Issue by dgkerry** [ccxt/ccxt#18676]
### Programming Languages

PHP

### CCXT Version

4.0.39

### Description

I tried to write the code according to the example in the document, but the prompt was "cannot find the ccxt quoinex class", and I couldn't find the quoinex.php file in the ccxt's PHP directory. Is it true that the quoinex file has been deleted long ago?

### Code

```
// PHP

include 'ccxt.php'

// any time
$quoinex = new \ccxt\quoinex ();
$quoinex->apiKey = 'YOUR_QUOINE_API_KEY';
$quoinex->secret = 'YOUR_QUOINE_SECRET_KEY';


```

**Comment by carlosmiei** [comment]
Hello @dgkerry, yes unfortunately quoinex was delisted a long time ago.
