### ISSUE TITLE
Bybit spot market buy orders unexpected behavior

### ISSUE THREAD

**Issue by hodlerhacks** [ccxt/ccxt#18685]
### Operating System

Windows

### CCXT Version

4.0.40

### Description

When placing a market buy order on Bybit (spot market) like this:

```python
await exchange.createOrder('ETH/USDT', 'market', 'buy', 0.005, 1859);
```

I'm seeing some unexpected behavior. Note that I'm adding the price so the cost can be calculated, which is required by Bybit.

When the order gets filled, watchOrders() returns the following:

```python
{
  info: {
    symbol: 'ETHUSDT',
    orderId: '1474351881137507584',
    side: 'Buy',
    orderType: 'Market',
    cancelType: 'UNKNOWN',
    price: '0.00',
    qty: '9.2900000',
    orderIv: '',
    timeInForce: 'GTC',
    orderStatus: 'PartiallyFilledCanceled',
    orderLinkId: '1690492440294936',
    lastPriceOnCreated: '',
    reduceOnly: false,
    leavesQty: '',
    leavesValue: '',
    cumExecQty: '0.00500',
    cumExecValue: '9.2886000',
    avgPrice: '',
    blockTradeId: '',
    positionIdx: 0,
    cumExecFee: '0',
    createdTime: '1690492440298',
    updatedTime: '',
    rejectReason: '',
    stopOrderType: '',
    triggerPrice: '',
    takeProfit: '',
    stopLoss: '',
    tpTriggerBy: '',
    slTriggerBy: '',
    triggerDirection: 0,
    triggerBy: '',
    closeOnTrigger: false,
    category: 'spot',
    isLeverage: '0',
    smpType: 'None',
    smpGroup: 0,
    smpOrderId: ''
  },
  id: '1474351881137507584',
  clientOrderId: '1690492440294936',
  timestamp: 1690492440298,
  datetime: '2023-07-27T21:14:00.298Z',
  lastTradeTimestamp: undefined,
  lastUpdateTimestamp: undefined,
  symbol: 'ETH/USDT',
  type: 'market',
  timeInForce: 'GTC',
  postOnly: false,
  reduceOnly: false,
  side: 'buy',
  price: 1857.72,
  stopPrice: undefined,
  triggerPrice: undefined,
  takeProfitPrice: undefined,
  stopLossPrice: undefined,
  amount: 9.29,
  cost: 9.2886,
  average: 1857.72,
  filled: 0.005,
  remaining: 9.285,
  status: 'canceled',
  fee: { cost: 0, currency: undefined },
  trades: [],
  fees: [ { cost: 0, currency: undefined } ]
}
```

What is unexpected about this:

1. The 'filled' attribute is expressed as the number of ETH bought, while 'remaining' is expressed as the number of USDT still to be sold. However, at this point, remaining should be set to zero, as all the to be purchased ETH is already bought. Also, remaining is calculated by subtracting the filled amount (ETH) from the amount (9.29 USDT), so this is all mixed up

2. The status is set to 'canceled', even though the order is actually filled and completed when I look at the order history and the balance. Before I get this 'canceled' report, I also get a report with the same information, including the filled and remaining amounts, but the status set to 'open'. I would expect that one to so 'closed', and of course no 'canceled' report at all

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @hodlerhacks,

1) Yes that seems a bug and we will check it.

2) As you can see in the raw field sent in the message `orderStatus :PartiallyFilledCanceled`  but ccxt does not have this intermediate state we only have ('canceled`, 'open', `closed', 'expired', 'rejected') so we're defaulting to `canceled` here.

**Comment by hodlerhacks** [comment]
Thanks gents!

**Comment by hodlerhacks** [comment]
I did a bit of research on the Bybit API to understand this PartiallyFilledCanceled status. It turns out that this is used because a market buy order on Bybit is using quote order quantity, and that quote currency may not be 100% used to buy the base currency. This is from Bybit support on their Telegram support channel:

"example:  if you are trying to buy BTC for 10 USDT, then you got 0.000xxx BTC and deducted 9.99486 USDT. So for the reamining 0.00514 USDT, we cannot allocate the BTC. So order was partially filled and cancelled and you got the 0.00514 USDT back"

Source: https://t.me/BybitAPI/127799

When you map this PartiallyFilledCanceled status, wouldn't it be better to use 'closed' instead of 'canceled'? Other exchanges that support quote order quantity for market buy orders of course have the same 'problem' of not being able to spend the exact amount of quote quantity. But those set the status to 'closed'. An example for Binance, after placing a market buy order to buy ETH with 12 USDT:

{
  info: {
    e: 'executionReport',
    E: 1690608543777,
    s: 'ETHUSDT',
    c: 'x-R4BD3S823acff92187c84dc985e622',
    S: 'BUY',
    o: 'MARKET',
    f: 'GTC',
    q: '0.00640000',
    p: '0.00000000',
    P: '0.00000000',
    F: '0.00000000',
    g: -1,
    C: '',
    x: 'TRADE',
    X: 'FILLED',
    r: 'NONE',
    i: 13936995952,
    l: '0.00640000',
    z: '0.00640000',
    L: '1874.02000000',
    n: '0.00000640',
    N: 'ETH',
    T: 1690608543776,
    t: 1181959557,
    I: 29036622607,
    w: false,
    m: false,
    M: true,
    O: 1690608543776,
    Z: '11.99372800',
    Y: '11.99372800',
    Q: '12.00000000',
    W: 1690608543776,
    V: 'NONE'
  },
  symbol: 'ETH/USDT',
  id: '13936995952',
  clientOrderId: 'x-R4BD3S823acff92187c84dc985e622',
  timestamp: 1690608543776,
  datetime: '2023-07-29T05:29:03.776Z',
  lastTradeTimestamp: 1690608543776,
  lastUpdateTimestamp: 1690608543776,
  type: 'market',
  timeInForce: 'GTC',
  postOnly: false,
  reduceOnly: undefined,
  side: 'buy',
  price: 1874.02,
  stopPrice: 0,
  triggerPrice: 0,
  amount: 0.0064,
  cost: 11.993728,
  average: 1874.02,
  filled: 0.0064,
  remaining: 0,
  status: 'closed',
  fee: { cost: 0.0000064, currency: 'ETH' },
  trades: [
    {
      info: [Object],
      timestamp: 1690608543776,
      datetime: '2023-07-29T05:29:03.776Z',
      symbol: 'ETH/USDT',
      id: '1181959557',
      order: '13936995952',
      type: 'market',
      takerOrMaker: 'taker',
      side: 'buy',
      price: 1874.02,
      amount: 0.0064,
      cost: 11.993728,
      fee: [Object],
      fees: [Array]
    }
  ],
  fees: [ { cost: 0.0000064, currency: 'ETH' } ],
  takeProfitPrice: undefined,
  stopLossPrice: undefined
}

Just a suggestion to improve consistency.

**Comment by carlosmiei** [comment]
@hodlerhacks I agree, thanks for letting me know, will update it.

**Comment by hodlerhacks** [comment]
Cool, thank you!
