### ISSUE TITLE
BitGet Fetch_order error

### ISSUE THREAD

**Issue by ZetZ1** [ccxt/ccxt#18683]
0

**Comment by samgermain** [comment]
Can you provide the code that produces this errror please? Instead of just the output?

**Comment by ZetZ1** [comment]
exch = ccxt.bitget(({'apiKey': apikey, 'secret': secretkey, 'password': db[user]['passphrase'], 'enableRateLimit': True}))
sl_check = exch.fetch_order('604833074693799936', ticker, params={'clientOrderId': 'e847386590ce4dBC6745faf0bffe96a9', 'stop': True})

sl check error bitget {"code":"40109","msg":"The data of the order cannot be found, please confirm the order number","requestTime":1690486263882,"data":null}

one time each 5 iterations aprox works, usually error

**Comment by ZetZ1** [comment]
no, now never... straign...

**Comment by carlosmiei** [comment]
Hello @ZetZ1, CCXT requests are built deterministically so if sometimes work and sometimes don't most likely it is an issue with the exchange's API.

**Comment by samgermain** [comment]
@ZetZ1 are you still experiencing any issues?

**Comment by carlosmiei** [comment]
@ZetZ1 will close this issue, feel free to reopen it if needed

**Comment by ZetZ1** [comment]
after these issues, now never find the order if is a triggered / stop order

May a change from bitget api? i see than is added new apiparameters but its confused
