### ISSUE TITLE
Binance: TypeError: object dict can't be used in 'await' expression

### ISSUE THREAD

**Issue by clrockwell79** [ccxt/ccxt#1869]
Hi,

I get the above error using version 1.10.1076 and this code from one of the repo examples:

```
binance = ccxt.binance({
  "apiKey": 'my_real_api_key',
  "secret": 'my_real_secret',
  "enableRateLimit": True
  })
async def fetch_tickers(exchange):
    await exchange.load_markets()
    print(exchange.id, 'fetching all tickers by simultaneous multiple concurrent requests')
    symbols_to_load = get_active_symbols(exchange)
    input_coroutines = [fetch_ticker(exchange, symbol) for symbol in symbols_to_load]
    tickers = await asyncio.gather(*input_coroutines, return_exceptions=True)
    for ticker, symbol in zip(tickers, symbols_to_load):
        if not isinstance(ticker, dict):
            print(exchange.id, symbol, 'error')
        else:
            print(exchange.id, symbol, 'ok')
    print(exchange.id, 'fetched', len(list(tickers)), 'tickers')


asyncio.get_event_loop().run_until_complete(fetch_tickers(binance))
```
Possibly related: https://github.com/ccxt/ccxt/issues/617

**Comment by kroitor** [comment]
@clrockwell79 you're missing an instance of binance when calling fetch_ticker (or missing a code snippet of it):

```
    input_coroutines = [fetch_ticker(exchange, symbol) for symbol in symbols_to_load]
```

Should be:

```
    input_coroutines = [binance.fetch_ticker(symbol) for symbol in symbols_to_load]
```

Let us know if this does not help.

**Comment by zero-direwolf** [comment]
import keys
import ccxt
import asyncio

api_key, secret_key = keys.keys()

binance = ccxt.binance({
  "apiKey": api_key,
  "secret": secret_key,
  "enableRateLimit": True
  })

async def fetch_tickers(exchange):
    await exchange.load_markets()
    print(exchange.id, 'fetching all tickers by simultaneous multiple concurrent requests')
    symbols_to_load = get_active_symbols(exchange)
    input_coroutines = [binance.fetch_ticker(exchange, symbol) for symbol in symbols_to_load]
    tickers = await asyncio.gather(*input_coroutines, return_exceptions=True)
    for ticker, symbol in zip(tickers, symbols_to_load):
        if not isinstance(ticker, dict):
            print(exchange.id, symbol, 'error')
        else:
            print(exchange.id, symbol, 'ok')
    print(exchange.id, 'fetched', len(list(tickers)), 'tickers')


asyncio.get_event_loop().run_until_complete(fetch_tickers(binance))

i keep getting an error :
   await exchange.load_markets()
TypeError: object dict can't be used in 'await' expression

can anyone help me ?
thanks

**Comment by kroitor** [comment]
> can anyone help me ?

https://github.com/ccxt/ccxt#python

@zero-direwolf if you want to use the async version you should do:

```Python
# import ccxt                                      # sync
import ccxt.async_support as ccxt  # async ←---- you need this
```
