### ISSUE TITLE
Bittrex spot trades returning wrong side

### ISSUE THREAD

**Issue by HarshilMendpara** [ccxt/ccxt#18699]
### Operating System

Ubuntu 22.04

### Programming Languages

JavaScript

### CCXT Version

4.0.43

### Description

An object of the array returned by the `exchange.fetchMyTrades` function contains the `side` of the trade, which can be either `buy` or `sell`, depending on the response sent by the Bittrex exchange API. It also contains an `info` object, which shows the actual response sent by the Bittrex exchange. If the value of the `direction` key in the `info` object is `BUY`, then the value of the `side` key in the ccxt response should be `buy`. However, in some trades, it is returning the side as `sell`, even when the value of the `direction` key in the `info` object is `BUY`.

### Code

```
  

```

**Comment by ttodua** [comment]
bittrex exchange is closed
