### ISSUE TITLE
bingx async historical data error

### ISSUE THREAD

**Issue by meysamrn** [ccxt/ccxt#18702]
### Operating System

linux ubuntu 22.04

### Programming Languages

Python

### CCXT Version

4.0.43

### Description

when run a strategy thts needs hystorical data or when download data in freqtrade its happened,
the error is : Async code raised an exception: OperationalException('Exchange BingX does not support fetching historical candle (OHLCV) data

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @meysamrn,
That error does not seem to come from CCXT itself. Still, maybe freqtrade is protecting the code from calling `fetchOHLCV` with a spot symbol because bingx does provide that information through the API, right now, you can only fetch candles for derivative markets at bingx.
