### ISSUE TITLE
fetchOpenOrdersWs should return all orders, not only by one symbol

### ISSUE THREAD

**Issue by olegtaranenko** [ccxt/ccxt#18705]
### Operating System

windows, macos

### Programming Languages

JavaScript

### CCXT Version

4.0.39

### Description

binanceusdm pro fetchOpenOrdersWs requres symbol, but from Binance side it doesn't
Look into [Binance WS API docs](https://binance-docs.github.io/apidocs/websocket_api/en/#cancel-and-replace-order-trade).

> 

Name | Type | Mandatory | Description
-- | -- | -- | --
symbol | STRING | NO | If omitted, open orders for all symbols are returned
apiKey | STRING | YES |  
recvWindow | INT | NO | The value cannot be greater than 60000
signature | STRING | YES |  
timestamp | INT | YES |  

### Code

see ```ts/src/pro/binance.ts``` file, line from 1836
```
      this.checkRequiredSymbol ('fetchOpenOrdersWs', symbol);
        await this.loadMarkets ();
        this.checkIsSpot ('fetchOpenOrdersWs', symbol);
        const url = this.urls['api']['ws']['ws'];
        const requestId = this.requestId (url);
        const messageHash = requestId.toString ();
        let returnRateLimits = false;
        [ returnRateLimits, params ] = this.handleOptionAndParams (params, 'fetchOrderWs', 'returnRateLimits', false);
        const payload = {
            'symbol': this.marketId (symbol),
            'returnRateLimits': returnRateLimits,
        };
```
I think ```this.checkRequiredSymbol ('fetchOpenOrdersWs', symbol);``` and also ```this.checkIsSpot ('fetchOpenOrdersWs', symbol);``` should be gone

**Comment by carlosmiei** [comment]
Hello @olegtaranenko,
For now `fetchOpenOrdersWs` is only available for spot markets (binance did not release the futures version yet).
Regarding the `symbol` requirement I think you're right it does not seem mandatory, thanks for letting us know, will update it as soon as possible. 
 
![image](https://github.com/ccxt/ccxt/assets/43336371/02da6f54-7068-456a-95e5-b3f02ea36704)
