### ISSUE TITLE
lbank2 createOrder error 10008

### ISSUE THREAD

**Issue by interenet** [ccxt/ccxt#18716]
### Operating System

Ubuntu 22.04

### Programming Languages

Python

### CCXT Version

Ccxt ver3.1.41

### Code

```
import ccxt
exchange = ccxt.lbank2({
                                                'apiKey': 'XXX',
                                                'secret': 'YYY',
                                                'verbose': True,
                                              })
exchangeMarkets = exchange.loadMarkets()
print (exchange.create_order('ETH/USDT', 'limit', 'buy', '0.05', '1700'))

```
Answer:
{'id': None, 'info': {}, 'fees': [], 'clientOrderId': None, 'timestamp': None, 'datetime': None, 'symbol': None, 'type': None, 'side': None, 'lastTradeTimestamp': None, 'price': None, 'amount': None, 'cost': None, 'average': None, 'filled': None, 'remaining': None, 'timeInForce': None, 'postOnly': None, 'trades': [], 'reduceOnly': None, 'stopPrice': None, 'triggerPrice': None, 'status': None, 'fee': None}
Verbose:
fetch Request: lbank2 POST https://api.lbank.info/v2/supplement/create_order.do RequestHeaders: {'Content-Type': 'application/x-www-form-urlencoded', 'timestamp': '1690793614871', 'signature_method': 'HmacSHA256', 'echostr':'aaaaaaaaaaaaaa', 'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '/', 'Connection': 'keep-alive'} RequestBody: amount=0.05&api_key=xxxxxxxxxxxxxxxx&price=1700&sign=yyyyyyyyyyyyyy&symbol=eth_usdt&type=buy

fetch Response: lbank2 POST https://api.lbank.info/v2/supplement/create_order.do 200 ResponseHeaders: {'Date': 'Mon, 31 Jul 2023 08:53:35 GMT', .............ResponseBody: {"result":false,"error_code":10008,"ts":bbbbbbbbb}

**Comment by AlgoQ** [comment]
The [error code](https://www.lbank.com/en-US/docs/index.html#error-code) is related to an invalid symbol. Are you sure you used `ETH/USDT` as symbol?

**Comment by interenet** [comment]
Yes

**Comment by Dan-krm** [comment]
I tried creating an order using the implicit API and received the same error so I think this is an issue on Lbanks side. All we can do is reach out to them and let them know about the error and ask them to fix their API
