### ISSUE TITLE
How to hide verbose request output in PHP?

### ISSUE THREAD

**Issue by Sarona93** [ccxt/ccxt#1872]
Hi, 

I call fetch_balance function and it is working correctly, but I see it print a request output on the resulting page, like following 
 `Request: Array ( [0] => GET [1] => https://bittrex.com/api/v2.0/pub/Markets/GetMarketSummaries [2] => Array ( ) [3] => ) Request: Array ( [0] => GET [1] => https://bittrex.com/api/v1.1/account/getbalances?nonce=xxxxx&apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxx [2] => Array ( [0] => apisign: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ) [3] => ) Request: Array ( [0] => GET [1] => https://api.kucoin.com/v1/market/open/symbols [2] => Array ( [User-Agent] => Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) `

I want to hide this.

**Comment by kroitor** [comment]
@Sarona93 can you show your code? You need to remove the verbose mode from there.

**Comment by kroitor** [comment]
Let us know if we can help with anything else here. Just remove the `.verbose` flag.

**Comment by Sarona93** [comment]
@kroitor Thanks a lot, 
yes now it is working correctly,
