### ISSUE TITLE
KuCoin stop limit orders do not trigger watchOrders() events

### ISSUE THREAD

**Issue by hodlerhacks** [ccxt/ccxt#18726]
### Operating System

Windows

### Programming Languages

JavaScript

### CCXT Version

4.0.45

### Description

On KuCoin (spot market), when creating a stop limit order using the unified method for SL/TP orders like this:

`await exchange.createOrder('SOL/USDT', 'limit', 'sell', 0.333, 23.2, { stopLossPrice: 23.4 });`

the stop limit order is properly created. However, it does not trigger an event on the watchOrders() method when placing nor when canceling the order.

When the order is filled, a watchOrders() event is triggered properly.

I used the exact same code (see code snippet below) on Binance to validate the code itself, and that worked without problems.

### Code

```
    while (true) {
        try {
            const orders = await exchange.watchOrders();
            orders.forEach(order => {
                console.log(order)
            });
        } catch (e) {
            console.log(e)
        }
    }  
```

**Comment by samgermain** [comment]
The parameter `stopLossPrice` is specifically for stop losses that are attached to **contract** positions, so it can't work on spot.

You might want to try the parameter `triggerPrice` instead https://github.com/ccxt/ccxt/issues/12044

**Comment by hodlerhacks** [comment]
Hi @samgermain, it does work on spot as well. I'm using the unified method as described here: https://github.com/ccxt/ccxt/wiki/Manual#stop-loss-orders. On KuCoin, there was a bug that was fixed a few days ago, see here: https://github.com/ccxt/ccxt/issues/18606. And indeed, the stop limit order is now created as expected. I can see it appear as an order on the exchange. It does get triggered and filled as well. So all is fine, except that watchOrders() is not triggered upon creating and canceling.

**Comment by samgermain** [comment]
Yeah it looks like the watchOrders endpoint only accesses the trade orders on Kucoin. I'm working on a PR(#18747) to add the functionality to watch stop orders, but it will require a bit of back and forth

**Comment by hodlerhacks** [comment]
Great, thanks a lot @samgermain!

**Comment by samgermain** [comment]
@hodlerhacks Once https://github.com/ccxt/ccxt/pull/18747 gets merged, you should be able to watch stop orders on kucoin by passing the argument `params["stop"]`

**Comment by hodlerhacks** [comment]
Thanks for the update @samgermain! 

Just curious: wasn't it possible to resolve this without the additional parameter? I'm trying to keep my code as exchange-independent as possible. 

Would it be safe to pass this parameter also when using other exchanges? Or would I need to pass the parameter only when using KuCoin?

There was a similar case where this 'stop' parameter is needed to cancel spot orders on Bybit (see https://github.com/ccxt/ccxt/issues/18857#issuecomment-1674838604). But it turned out that I cannot use the parameter with (some) other exchanges. For instance, when using Binance, an error is thrown. 

Would I use it like this:

`exchange.wathOrders({'stop': true})` ?

**Comment by hodlerhacks** [comment]
Hi @samgermain, I was wondering if you had seen my comment and what your thoughts are. In order to keep my code clean, it would really help if stop orders could simply be watched without an additional 'stop' argument, and if that complexity was handled by CCXT under the hood. Otherwise I need to have multiple instances of `exchange.watchOrders()`, to make sure I capture all order events, for different exchanges and for stop and non-stop orders. That can be done of course, but I'm not sure if there is any benefit of leaving that 'complexity' to the client application. 

I already had to do something similar to be able to cancel all orders, stop and non-stop, on Bybit (see https://github.com/ccxt/ccxt/issues/18857), which actually caused additional issues, because if I do `exchange.cancelAllOrders(symbol, { 'stop': true })`, this could lead to an exception with other exchanges (at least with Binance). So I now have to use the stop argument only when Bybit is used, leading to additional exchange-specific code. And that's something I'd prefer to avoid.

Anyway, if there are good reasons to leave this to the client, all fine. I'm just not sure if there are any. Curious to hear your thoughts.

**Comment by leonvanhelvoort-tomtom** [comment]
Hi @samgermain, @kroitor, I tested with:

`exchange.watchOrders(undefined, undefined, undefined, { 'stop': true })`

But no luck. Stop limit orders are still not triggering any events. Am I doing something wrong?

**Comment by samgermain** [comment]
> it would really help if stop orders could simply be watched without an additional 'stop' argument,

that's not possible, stop orders are watched from a different endpoint, so some specification needs to be given specifying whether to watch the regular endpoint, or the stop orders endpoint

**Comment by hodlerhacks** [comment]
Ok, clear. So is this how I would use it:

`exchange.watchOrders(undefined, undefined, undefined, { 'stop': true })`

I tried this, but it doesn't work.

**Comment by samgermain** [comment]
> Ok, clear. So is this how I would use it:
> 
> `exchange.watchOrders(undefined, undefined, undefined, { 'stop': true })`
> 
> I tried this, but it doesn't work.

The websocket methods involve a different implementation that the REST methods. There is [manual on how to use the websocket methods here](https://github.com/ccxt/ccxt/wiki/ccxt.pro) and some examples listed on this issue https://github.com/ccxt/ccxt/issues/15171

**Comment by carlosmiei** [comment]
Hello @hodlerhacks, 
What's your ccxt version?

**Comment by leonvanhelvoort-tomtom** [comment]
Hi @carlosmiei, I'm using the latest version. However, I now got it working. I used a simple test application, and I placed the stop loss order immediately after setting the watchOrders(). But with a short delay in between it works. So my bad.

I'm still not sure though how to best use this. My application is developed to work with multiple exchanges. And I'm trying to get one trigger for every new order (of any type) or change in order status. 

What I thought I should do is:

1. Handle normal orders:
```        while (true) {
            try {
                const orders = await exchange.watchOrders();
                orders.forEach(order => {
                    console.log('NORMAL', order)
                });
            } catch (e) {
                console.log(e)
            }
```

And:

2. Handle stop orders, only in case exchange == kucoin:

```while (true) {
            try {
                const orders = await exchange.watchOrders(undefined, undefined, undefined, { 'stop': true });
                orders.forEach(order => {
                    console.log('STOP:', order)
                });
            } catch (e) {
                console.log(e)
            }
        }
```

This way I would catch any order event. However, if I do this and place a stop loss order, both 1 and 2 return the order information. Also when I place a normal order, both 1 and 2 return the order information.

Is there a better way, so that I get just one order update, no matter the type of order?

**Comment by hodlerhacks** [comment]
Hi @carlosmiei, I'm using the latest version. However, I now got it working. I used a simple test application, and I placed the stop loss order immediately after setting the watchOrders(). But with a short delay in between it works. So my bad.

I'm still not sure though how to best use this. My application is developed to work with multiple exchanges. And I'm trying to get one trigger for every new order (of any type) or change in order status.

What I thought I should do is:

Handle normal orders:
            try {
                const orders = await exchange.watchOrders();
                orders.forEach(order => {
                    console.log('NORMAL', order)
                });
            } catch (e) {
                console.log(e)
            }
And:

Handle stop orders, only in case exchange == kucoin:
            try {
                const orders = await exchange.watchOrders(undefined, undefined, undefined, { 'stop': true });
                orders.forEach(order => {
                    console.log('STOP:', order)
                });
            } catch (e) {
                console.log(e)
            }
        }
This way I would catch any order event. However, if I do this and place a stop loss order, both 1 and 2 return the order information. Also when I place a normal order, both 1 and 2 return the order information.

Is there a better way, so that I get just one order update, no matter the type of order?

**Comment by hodlerhacks** [comment]
Hi @carlosmiei, I'm using the latest version. However, I now got it working. I used a simple test application, and I placed the stop loss order immediately after setting the watchOrders(). But with a short delay in between it works. So my bad.

I'm still not sure though how to best use this. My application is developed to work with multiple exchanges. And I'm trying to get one trigger for every new order (of any type) or change in order status.

What I thought I should do is:

1. Handle normal orders:
```
            try {
                const orders = await exchange.watchOrders();
                orders.forEach(order => {
                    console.log('NORMAL', order)
                });
            } catch (e) {
                console.log(e)
            }
```
And:

2. Handle stop orders, only in case exchange == kucoin:
```
            try {
                const orders = await exchange.watchOrders(undefined, undefined, undefined, { 'stop': true });
                orders.forEach(order => {
                    console.log('STOP:', order)
                });
            } catch (e) {
                console.log(e)
            }
```

This way I would catch any order event. However, if I do this and place a stop loss order, both 1 and 2 return the order information. Also when I place a normal order, both 1 and 2 return the order information.

Is there a better way, so that I get just one order update, no matter the type of order?
