### ISSUE TITLE
OKX Liquid Marketplace

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#18727]
We are happy to announce the added support for the OKX new Liquid Marketplace API features: [**Request For Quote (RFQ Block Trading)**](https://www.okx.com/liquid-marketplace?channelid=CCXT2023) and [**Nitro Spreads**](https://www.okx.com/liquid-marketplace?channelid=CCXT2023)!

The corresponding OKX API endpoints are now available from CCXT!

-------------------------------------------------------------------------------

## RFQ

- https://github.com/ccxt/ccxt/blob/master/ts/src/okx.ts#L232
- https://github.com/ccxt/ccxt/blob/master/ts/src/okx.ts#L350

### RFQ API offers:

- Automated RFQ workflow with integrated position builder
- Anonymous RFQs with two-way quotes
- End-to-end connectivity with OKX risk management and settlement

-------------------------------------------------------------------------------
## Nitro Spreads

- https://github.com/ccxt/ccxt/blob/master/ts/src/okx.ts#L240
- https://github.com/ccxt/ccxt/blob/master/ts/src/okx.ts#L362

### Nitro Spreads API offers

- Deep liquidity for funding rate farming, future spreads strategies 
- Eliminates Leg Risk: Atomic executions with exchange listed spreads 
- Cheaper with 50% less trading fees versus trading outright legs

-------------------------------------------------------------------------------

All of the aforementioned APIs are available implicitly from CCXT as version 4.0.45+, as documented in the CCXT Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api

As always, we highly recommend upgrading to the most recent version of CCXT. 

-------------------------------------------------------------------------------

### Apply for access to these new API features using the following link: 

- https://www.okx.com/liquid-marketplace?channelid=CCXT2023

We would be happy to receive your feedback, please, don't hesitate to post here if you have any questions regarding the use of the new OKX API endpoints.

Yours, The CCXT Dev Team.

**Comment by LawrenceLai1107** [comment]
How to use Nitro Spreads function on okx exchange using ccxt?
Are there any C# examples?

**Comment by carlosmiei** [comment]
Hello @LawrenceLai1107,

Those features are not unified, but you can always call the method/endpoint directly through the implicit API.

You can check the available endpoints/methods here: https://github.com/ccxt/ccxt/blob/master/cs/ccxt/api/okx.cs
