### ISSUE TITLE
Cannot open both long&short position for a single symbol on KuCoin Futures?

### ISSUE THREAD

**Issue by yllvar** [ccxt/ccxt#18732]
### Operating System

Mac OS

### Programming Languages

Python

### Description

How can I create an short position independent from others (in python)?

If I place a long market order it'll automatically open a position on kucoin futures. If I place a short market order right after it, it'll deduct it from the total existing position.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @yllvar, 

For now, Kucoin does not support the hedged/dualPosition mode, so you can't have independent long and short positions opened simultaneously.

You can read more about it here: https://www.kucoin.com/support/900007221283

**Comment by quintin2003** [comment]
I'm not sure how long you have used KuCoin for my friend but one upon a time, KuCoin use to have hedge mode. 

I literally used it, I didn't understand it at the time and thought it was dumb. 

I can imagine lots of people ended up like that and never used it. This KuCoin dropped support for it.

**Comment by yllvar** [comment]
> I'm not sure how long you have used KuCoin for my friend but one upon a time, KuCoin use to have hedge mode. 
> 
> I literally used it, I didn't understand it at the time and thought it was dumb. 
> 
> I can imagine lots of people ended up like that and never used it. This KuCoin dropped support for it. 

Too bad the futures market has no hedge mode, I always wonder how the mechanism for kucoin futures market maker since no hedge is allowed
