### ISSUE TITLE
Kucoin load market error

### ISSUE THREAD

**Issue by hi-bingo** [ccxt/ccxt#18736]
### Programming Languages

Python

### CCXT Version

4.0.14

### Description

kucoin load_markets suddenly has problem? How to fix it?

### Code

```
import ccxt
k=ccxt.kucoin()
k.load_markets()

> 
ccxt.base.errors.NotSupported: kucoin fetchCurrencies() failed to fetch correct data from website. Probably webpage markup has been changed, breaking the page custom parser.kucoin GET https://kucoin.com/_api/currency/currency/chain-info 403 Forbidden <html>

```

**Comment by VanessaE** [comment]
This is affecting multiple users, but I don't think it's CCXT's fault.  Others are suggesting it's a DNS error on Kucoin's part.

**Comment by carlosmiei** [comment]
Hello @VanessaE @hi-bingo, yeah seems like the endpoint used to fetch currencies changed, but you can easily disable this step by doing:

```Python
exchange.options['fetchCurrencies']['webApiEnable'] = False
```
⬆️  this fixes the reported issue immediately. 

In the meantime we will try to implement a proper solution as soon as possible, thanks for reporting it.

**Comment by carlosmiei** [comment]
@VanessaE @hi-bingo Actually, if you update your ccxt version to the latest (as @VanessaE suggested), you should not get this error.

**Comment by hi-bingo** [comment]
> @VanessaE @hi-bingo Actually, if you update your ccxt version to the latest (as @VanessaE suggested), you should not get this error.

Thanks! I update the ccxt to the latest and now it works.

**Comment by ttodua** [comment]
yes, the error could have been happening in older versions, as in new versions the error is muted automatically
