### ISSUE TITLE
[Question] How to use your code for trading at Gate.io

### ISSUE THREAD

**Issue by Wel2odm** [ccxt/ccxt#1873]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Win10 64bit
- Programming Language version: Python 3.6
- CCXT version: Recent version
- Exchange:
- Method:

At first, Thank you for your code.
However, I don't know how can I use your code for trading at Gate.io.
I activated the phython code, but nothing is happened!
Could you please explain how can I use it in detail?

Thank you.

**Comment by kroitor** [comment]
Hi!

> Could you please explain how can I use it in detail?

You can use this library whatever way you want it, depends on your goals. But you will need programming skills to use it. 

Most of it is described in detail in the Manual: https://github.com/ccxt/ccxt/wiki/Manual

Also, there are a lot of examples on how to program this or that functionality with it, here: https://github.com/ccxt/ccxt/tree/master/examples

Let us know if this does not help.
