### ISSUE TITLE
Binance USDM reduce_only being inverted

### ISSUE THREAD

**Issue by LuizDMM** [ccxt/ccxt#18743]
### Operating System

Docker (python:3.11-slim image)

### Programming Languages

Python

### CCXT Version

4.0.46

### Description

I have an automated system to place orders in two accounts in Binance Futures. I'm sending the same orders to both accounts, in one my TPs and SLs are correctly being placed with reduce only = True, on the other, I call create_order with reduce_only = True, but it's placing the order without the reduce only. What is happening?

### Code

```
order_data = {
    "symbol": "APE/USDT:USDT",
    "type": "STOP_MARKET",
    "side": "sell",
    "amount": "45",
    "params": {
        "marginMode": "cross",
        "recvWindow": 60000,
        "stopPrice": "1.645",
        "reduceOnly": True,
    },
}
order = exchange.create_order(**order_data)
print(order)
# It returned:  "{'info': {'orderId': 'xxxxxx', 'symbol': 'APEUSDT', 'status': 'NEW', 'clientOrderId': 'xxxxxxx', 'price': '0.0000', 'avgPrice': '0.00', 'origQty': '45', 'executedQty': '0', 'cumQty': '0', 'cumQuote': '0.0000', 'timeInForce': 'GTC', 'type': 'STOP_MARKET', 'reduceOnly': False, 'closePosition': False, 'side': 'SELL', 'positionSide': 'BOTH', 'stopPrice': '1.6450', 'workingType': 'CONTRACT_PRICE', 'priceProtect': False, 'origType': 'STOP_MARKET', 'updateTime': '1690917610731'}, 'id': 'xxxxxxx', 'clientOrderId': 'xxxxxxxx', 'timestamp': 1690917610731, 'datetime': '2023-08-01T19:20:10.731Z', 'lastTradeTimestamp': None, 'lastUpdateTimestamp': 1690917610731, 'symbol': 'APE/USDT:USDT', 'type': 'stop_market', 'timeInForce': 'GTC', 'postOnly': False, 'reduceOnly': False, 'side': 'sell', 'price': None, 'triggerPrice': 1.645, 'amount': 45.0, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 45.0, 'status': 'open', 'fee': {'currency': None, 'cost': None, 'rate': None}, 'trades': [], 'fees': [{'currency': None, 'cost': None, 'rate': None}], 'stopPrice': 1.645, 'takeProfitPrice': None, 'stopLossPrice': None}"

```

**Comment by carlosmiei** [comment]
Hello @LuizDMM,
Can you please share a verbose log?

**Comment by LuizDMM** [comment]
Hey @carlosmiei I'm sorry, I couldn't get all logs in my tests here. What I found out: The system is working correctly for the hedged account, but it's not for the one-way mode one. Analyzing the logs, I saw a big fetch markets and then the order request isn't being sent with the reduceOnly, I couldn't figure out why.

**Comment by carlosmiei** [comment]
> Hey @carlosmiei I'm sorry, I couldn't get all logs in my tests here. What I found out: The system is working correctly for the hedged account, but it's not for the one-way mode one. Analyzing the logs, I saw a big fetch markets and then the order request isn't being sent with the reduceOnly, I couldn't figure out why.

@LuizDMM So if you place the order using the code above you don't see the `reduceOnly` being sent in the request?


Btw to remove the noise from markets loading you can turn on the verbose mode only after loading the markets, example:
```Python
await exchange.load_markets()
exchange.verbose = True
```
