### ISSUE TITLE
is Probit signIn() works?

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#18741]
### Operating System

Linux

### Programming Languages

JavaScript

### CCXT Version

latest

### Description

It stops working for me about a week ago. When I try to call `signIn()` I get `ExchangeNotAvailable: probit POST https://accounts.probit.com/token 403 Forbidden <!DOCTYPE html>...`. I don't make any changes and I don't see any influencing changes in there API

**Comment by samgermain** [comment]
> ### Operating System
> 
> Linux
> ### Programming Languages
> 
> JavaScript
> ### CCXT Version
> 
> latest
> ### Description
> 
> It stops working for me about a week ago. When I try to call `signIn()` I get `ExchangeNotAvailable: probit POST https://accounts.probit.com/token 403 Forbidden <!DOCTYPE html>...`. I don't make any changes and I don't see any influencing changes in there API

It works fine for me

```
2023-08-01T22:24:52.066Z
Node.js: v18.15.0
CCXT v4.0.47
probit.signIn ()
2023-08-01T22:24:54.539Z iteration 0 passed in 973 ms

{
  access_token: 'hR4cilNbmjD/gIEndshTMnNIKvuPiRvtk3N4aqYuMJs=',
  token_type: 'bearer',
  expires_in: '900'
}
2023-08-01T22:24:54.539Z iteration 1 passed in 973 ms
```

**Comment by samgermain** [comment]
It works fine for me

```
2023-08-01T22:24:52.066Z
Node.js: v18.15.0
CCXT v4.0.47
probit.signIn ()
2023-08-01T22:24:54.539Z iteration 0 passed in 973 ms

{
  access_token: '...',
  token_type: 'bearer',
  expires_in: '900'
}
2023-08-01T22:24:54.539Z iteration 1 passed in 973 ms
```

**Comment by ndubel** [comment]
@samgermain thank you, I will try with proxy

**Comment by aFluxx** [comment]
Probit is doing a lot of maintenances lately. This might be an indirect cause. Just a FYI
