### ISSUE TITLE
Bitvavo unable to place market order with EUR amount

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#18756]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

4.0.48

### Description

I am unable to place an order where I want all my EUR to be converted to XRP, see example below to replicate. 

### Code

```
  
import ccxt

public = 'x'
private = 'x'

client = ccxt.bitvavo({'apiKey': public, 'secret': private})

euros = client.fetch_balance()['EUR']['free']

t = client.create_order(currency+'/EUR', 'market', 'buy', None, params={'cost': euros})
```
File ~\anaconda3\lib\site-packages\ccxt\bitvavo.py:993, in bitvavo.create_order(self, symbol, type, side, amount, price, params)
    991         request['amountQuote'] = self.decimal_to_precision(cost, TRUNCATE, precision, self.precisionMode)
    992     else:
--> 993         request['amount'] = self.amount_to_precision(symbol, amount)
    994     params = self.omit(params, ['cost'])
    995 elif isLimitOrder:

File ~\anaconda3\lib\site-packages\ccxt\bitvavo.py:302, in bitvavo.amount_to_precision(self, symbol, amount)
    298 def amount_to_precision(self, symbol, amount):
    299     # https://docs.bitfinex.com/docs/introduction#amount-precision
    300     # The amount field allows up to 8 decimals.
    301     # Anything exceeding self will be rounded to the 8th decimal.
--> 302     return self.decimal_to_precision(amount, TRUNCATE, self.markets[symbol]['precision']['amount'], DECIMAL_PLACES)

File ~\anaconda3\lib\site-packages\ccxt\base\decimal_to_precision.py:58, in decimal_to_precision(n, rounding_mode, precision, counting_mode, padding_mode)
     55 context.traps[decimal.Underflow] = True
     56 context.rounding = decimal.ROUND_HALF_UP  # rounds 0.5 away from zero
---> 58 dec = decimal.Decimal(str(n))
     59 precision_dec = decimal.Decimal(str(precision))
     60 string = '{:f}'.format(dec)  # convert to string using .format to avoid engineering notation

InvalidOperation: [<class 'decimal.ConversionSyntax'>]

**Comment by Tomas-MP** [comment]
@carlosmiei I want to place an order where I convert all the EUR in my account to XRP, any idea how to do this then?

**Comment by carlosmiei** [comment]
@Tomas-MP In this case you have to place a market buy order where the `amount` is the number of XRP you want to buy.

Let's say XRP price is 0.5 EUR and you have 10 EUR available, you would need to provide 10/0.5 = 20 as the amount

**Comment by Tomas-MP** [comment]
@carlosmiei will do then, thank you!

**Comment by Tomas-MP** [comment]
@carlosmiei also getting an AssertionError when trying to withdraw: 

>>> for a in addresses:
...     transaction = client.withdraw(currency, int(send), a['address'], a['memo'])
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\bitvavo.py", line 1480, in withdraw
    'amount': self.currency_to_precision(code, amount),
  File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\bitvavo.py", line 296, in currency_to_precision
    return self.decimal_to_precision(fee, 0, self.currencies[code]['precision'], DECIMAL_PLACES)
  File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\base\decimal_to_precision.py", line 41, in decimal_to_precision   
    assert(isinstance(precision, numbers.Integral))
AssertionError

any idea what is going on here?

**Comment by carlosmiei** [comment]
> @carlosmiei also getting an AssertionError when trying to withdraw:
> 
> > > > for a in addresses:
> > > > ...     transaction = client.withdraw(currency, int(send), a['address'], a['memo'])
> > > > ...
> > > > Traceback (most recent call last):
> > > > File "", line 2, in 
> > > > File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\bitvavo.py", line 1480, in withdraw
> > > > 'amount': self.currency_to_precision(code, amount),
> > > > File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\bitvavo.py", line 296, in currency_to_precision
> > > > return self.decimal_to_precision(fee, 0, self.currencies[code]['precision'], DECIMAL_PLACES)
> > > > File "C:\Users\Tomas\anaconda3\lib\site-packages\ccxt\base\decimal_to_precision.py", line 41, in decimal_to_precision
> > > > assert(isinstance(precision, numbers.Integral))
> > > > AssertionError
> 
> any idea what is going on here?

@Tomas-MP That might be indeed an issue, will take a look asap

**Comment by carlosmiei** [comment]
@Tomas-MP You're right I found an issue with the precisions but will be fixed very soon.
