### ISSUE TITLE
Is there a function to grab all your coin asset?

### ISSUE THREAD

**Issue by MrDevBC** [ccxt/ccxt#1875]
Is there a function to grab all your coin asset?

ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows
- Programming Language version: PHP
- CCXT version: Latest
- Exchange: Binace
- Method:

**Comment by kroitor** [comment]
> Is there a function to grab all your coin asset?

Sure!

- https://github.com/ccxt/ccxt/wiki/Manual#querying-account-balance
- https://github.com/ccxt/ccxt/wiki/Manual#authentication

Let us know if this does not help.
