### ISSUE TITLE
OKX uses different endpoints for channels 'orders' and 'orders-algo'

### ISSUE THREAD

**Issue by kosmodromov** [ccxt/ccxt#18755]
### Operating System

Mac OS

### Programming Languages

Python

### CCXT Version

4.0.47

### Description

Hello,

OKX uses two different ws endpoints for  `orders` and `orders-algo` channels since April  https://www.okx.com/docs-v5/log_en/#2023-04-19

But ccxt still uses only `/private' endpoint 
```
        isStop = self.safe_value(params, 'stop', False)
        params = self.omit(params, ['stop'])
        channel = 'orders-algo' if isStop else 'orders'
```

```
        orders = await self.subscribe('private', messageHash, channel, symbol, self.extend(request, params))
```

https://github.com/ccxt/ccxt/blob/38084a9dcea71022b234acb169dd85d7184bc2ea/python/ccxt/pro/okx.py#L686C1-L721

### Code

```
  

```

**Comment by samgermain** [comment]
@kosmodromov It looks like not all the exchanges follow trigger orders currently

I have [started a PR to add this for kucoin,](https://github.com/ccxt/ccxt/pull/18747) and will look at okx as well when I finish that PR

**Comment by kosmodromov** [comment]
Thank you very much for your efforts!

**Comment by carlosmiei** [comment]
Hello @kosmodromov, actually, this is already implemented, you can right now do `watch_orders(params = {'stop':true})` at okx, we will just improve the implementation a bit.
