### ISSUE TITLE
Need advice for getting Binance a group of symbols data

### ISSUE THREAD

**Issue by zydjohnHotmail** [ccxt/ccxt#18762]
### Operating System

Windows 10

### Programming Languages

JavaScript

### CCXT Version

4.0.49

### Description

Hi, 
I want to write some JavaScript to get about 20 to 30 symbols OHLC data, like: BTC/USDT; ETH/USDT …
CCXT has the fetchOrderbook function, but this function will fetch data for only one pair, like: BTC/USDT.
If I want to fetch such data for 20 pairs, what I should do: I use a loop to fetch each pair’s order book?
I want to keep the JS code running to fetch such data every minute, but I don’t know if this will break the rate limit.
I see CCXT has also websocket data for Binance, but I don’t know if I can use websocket to get 20 or 30 pairs data, if it is possible, show me some code examples.
Thanks,

### Code

```
const orderbook = await exchange.fetchOrderBook(pair1);

```

**Comment by carlosmiei** [comment]
Hello @zydjohnHotmail,
Right now, yes you have to make 1 request per symbol, but that does not mean you have to do it sequentially, you can parallelize your requests. Regarding the RateLimit question, CCXT has a builtin RateLimiter so unless you're fetching a huge amount of data it should be ok. If you see that the limits are being crossed too many times you can also rotate your requests through different proxies to avoid getting limited. 

Example:

```Javascript
    const ohlcv = new ccxt.binance ();
    const symbols = ['BTC/USDT', 'ETH/BTC', 'ETH/USDT', 'LTC/BTC', 'LTC/USDT'] // your symbols here
    const promises = symbols.map (symbol => ohlcv.fetchOHLCV (symbol, '5m'))
    const result = await Promise.all (promises)
    for (let i = 0; i < symbols.length; i++) {
        const symbol = symbols[i]
        const ohlcv = result[i]
        console.log (symbol, ohlcv.length, 'candles')
    }
```

**Comment by zydjohnHotmail** [comment]
Hi,  thank you very much for your code, I tried to use your code, the following is my D:\nodejs\CCXT>type BinanceOHLCV.js
'use strict';
const ccxt = require('ccxt');

(async function () {
    console.log(ccxt.version)
    const ohlcv = new ccxt.binance ();
    const symbols = ['BTC/USDT', 'ETH/BTC', 'ETH/USDT', 'LTC/BTC', 'LTC/USDT']
    const promises = symbols.map (symbol => ohlcv.fetchOHLCV (symbol, '5m'))
    const result = await Promise.all (promises)
    for (let i = 0; i < symbols.length; i++) {
        const symbol = symbols[i]
        const ohlcv = result[i]
        console.log (symbol, ohlcv.length, 'candles')
    }
})();

When I run this code, I got the output: code: D:\nodejs\CCXT>node BinanceOHLCV.js
4.0.49
BTC/USDT 500 candles
ETH/BTC 500 candles
ETH/USDT 500 candles
LTC/BTC 500 candles
LTC/USDT 500 candles
=> The code is working, but the data is not what I want: I want to show the price values, like: open, high, low and close.  How can I change the code to get the data I want.  By the way, how can I run this code, so I will get all the data every minute or every 5 minutes?
Thanks,

**Comment by carlosmiei** [comment]
@zydjohnHotmail I was printing the length only but you can print the entire response.
If you want to fetch it every X minutes you can put it inside a while True, something like this:

```Javascript
    const binance = new ccxt.binance ();
    const symbols = ['BTC/USDT', 'ETH/BTC', 'ETH/USDT', 'LTC/BTC', 'LTC/USDT'] // your symbols here
    const sleepTime = 5000 // sleep time between requests in milliseconds (5mins)
    while (true) {
        const promises = symbols.map (symbol => binance.fetchOHLCV (symbol, '5m'))
        const result = await Promise.all (promises)
        for (let i = 0; i < symbols.length; i++) {
            const symbol = symbols[i]
            const ohlcv = result[i]
            console.log(symbol, ohlcv)
        }
        await binance.sleep(sleepTime)
    }
```

**Comment by zydjohnHotmail** [comment]
OK, thanks!
