### ISSUE TITLE
Binanceusm testnet error on fetch_positions 

### ISSUE THREAD

**Issue by idan-ben-ami** [ccxt/ccxt#18768]
### Operating System

Mac M1

### Programming Languages

Python

### CCXT Version

3.1.60

### Description

Received exchange error on binanceusdm (testnet):
ExchangeError('binanceusdm {\"code\":-5000,\"msg\":\"GET /fapi/v1/positionRisk is retired, please use GET /fapi/v2/positionRisk\"}')

### Code

```
await exchange.fetch_open_orders(symbol)
```

**Comment by sc0Vu** [comment]
Hi @idan-ben-ami 

We already update fapi to v2, would you like to upgrade ccxt?

**Comment by FelipeJz** [comment]
I'm running the latest version with the same issue

**Comment by Algo-Tradings** [comment]
> I'm running the latest version with the same issue

I was with the same problem. 
Anyway after `pip install ccxt --force`, I reinstalled the lib and it's working fine now.
Hope it helps!

**Comment by FelipeJz** [comment]
Sorry, i'm running nodejs, version 4.0.3. I deleted the node_modules folder and reinstalled, but the issue still remains :(

**Comment by Algo-Tradings** [comment]
ccxt need resources from other modules that may causing conflict. I guess you have npm installed, so instead of deleting ccxt folder try:
`npm uninstall -g ccxt`

**Comment by FelipeJz** [comment]
That did not work, but crazy enough, installing @latest, instead of the specific version updated other packages and that worked. Thank you for pointing me in the right direction! Cheers

**Comment by idan-ben-ami** [comment]
I'm sorry, my bad.
I managed to update to CCXT v4.0.* (uninstalled and reinstalled), and it all works well now.
Thanks a lot!

(Using poetry remove ccxt && poetry add ccxt - instead of poetry update ccxt)

**Comment by LAGD1979** [comment]
Hi!
i have the same issue, i already upgrade ccxt version, but i'm getting the same error message:
APIError(code=-5000): GET /fapi/v1/positionRisk is retired, please use GET /fapi/v2/positionRisk
I printed the versión: CCXT Version: 4.0.58
