### ISSUE TITLE
fetchBalance returns ambiguous symbols

### ISSUE THREAD

**Issue by gsdean** [ccxt/ccxt#1877]
Because symbols are not unique, it's not sufficient to return a hash with symbols as keys. It seems like the normalized response should include the contract address in some manner.

Or am I missing something?

- OS: OSX
- Programming Language version: node
- CCXT version: 1.10.1036
- Exchange: All
- Method: fetchBalance

**Comment by kroitor** [comment]
The fetchBalance has nothing to do with market symbols, it operates with `.currencies` and their `'code'` and `'id'`. To get the deposit address you would use a `fetchDepositAddress()` method with a unified currency code in its arguments. This issue also duplicates this one: #1770 

Docs: https://github.com/ccxt/ccxt/wiki

Let us know if the above does not answer your question.

**Comment by gsdean** [comment]
I'm talking about contract address, not deposit address. You can't identify a token simply by the symbol, making it ambiguous to return a hash of symbols for `fetchBalance`

**Comment by kroitor** [comment]
@gsdean we do not return a hash of symbols from fetchBalance at all, you're probably confusing terms, but a symbol is a pair of currencies, whereas fetchBalance returns a dictionary (or a hash, like you say) of currency codes. So, whenever there's ambiguity we should look at each particular case specifically. Can you tell which exchanges and currencies you mean exactly?

**Comment by gsdean** [comment]
They are referred to as "symbols" in the context of ERC20 tokens (https://ethereum.org/token#the-code). I guess in your terminology they are strictly called "currency codes".

At any case, they are not unique, so it's impossible for the consumer of `fetchBalance` to know what the actual currency is. It also breaks the abstraction of the specific exchange which is a bummer.

**Comment by kroitor** [comment]
> At any case, they are not unique, so it's impossible for the consumer of fetchBalance to know what the actual currency is. 

Can you tell examples of a conflict within current implementation in ccxt?

> It also breaks the abstraction of the specific exchange which is a bummer.

Which specific exchange?

**Comment by gsdean** [comment]
I'm not sure I understand, is there an exchange/implementation in which this would not be a conflict?

**Comment by kroitor** [comment]
The exchange returns MGO/WMGO for MGO on ETH vs MGO on Waves.

**Comment by kroitor** [comment]
> Because symbols are not unique

You may be starting with a false statement. They are unique.

**Comment by gsdean** [comment]
Are you saying they are unique in the scope of CCXT or unique in the scope of crypto currency?

**Comment by kroitor** [comment]
@gsdean they should be, however, as you may know, this library is still a work in progress, so there may be some missed conflicts here and there, so if you report a particular conflict with two exchanges having the same currency code designating different tokens, we will fix it then, but we need to know which two exchanges and which code is involved. We cannot really address the potential conflict issue here, because of how exchanges themselves work.

**Comment by gsdean** [comment]
I see, I guess, I'm talking about the discrepancy between how CCXT identifies currencies vs how uniques is maintained by external sources

As I understand it, it's the design goal of the library to normalize every currency to a unique proprietary currency code. This seems reasonable, however this is not how currencies are uniquely identified external to CCXT. This makes it cumbersome to reconcile with wallets, dex, etc. It forces the consumer to know the specifics of the exchange it just queried.

I dug through the source briefly and didn't see any way to map CCXT's representation to something that represents the currency uniquely in the real world (i.e. blockchain+contract address). I think this would be a useful addition, as currencies continue to be created this is going to get more confusing for callers to `fetchBalance`

Maybe something like this pseudo code:

```
const currencyCodes = {
    'WMGO': {
        blockchain: 'WAVES',
        uid: '2Y8eFFXDTkxgCvXbMT5K4J38cpDYYbQdciJEZb48vTDj'
    },
    'DYN': {
        'blockchain': 'DYN'
    },
    EDYN: { 
        blockchain: 'ETH',
        uid: '0x749128a5c72c10bbb9a67f7abb3fe0269fa448da'
}
```

This way if someone creates a ERC20 token called WMGO, the caller of `fetchBalance` knows that CCXT is referring to something else.

BTW: I'm including DYN here because this was the specific use case that tripped me up. I ran into an ERC20 with the DYN symbol in the wild.

**Comment by kroitor** [comment]
Have you looked into `.currencies` property of an exchange? It should contain that info (where available from the exchange).

**Comment by gsdean** [comment]
I have (just now) but it doesn't seem to enough information to uniquely identify a currency either. Without the contract address, I'm not sure it's possible. 

btw, uid in my above example is contract address...

**Comment by kroitor** [comment]
@gsdean without you telling which exchange it is, it's hard to tell the reason. Are you sure the info in question is provided from the exchange you're looking at, at all?

**Comment by gsdean** [comment]
Bittrex/Binance/Kraken

I'm certain it's not provided, what I'm suggesting is that CCXT provide it.

**Comment by kroitor** [comment]
@gsdean is there any way ccxt can provide it if the exchange in question does not? I mean, we'd love to, but we don't see a trustworthy source of info to rely on in the first place.

**Comment by gsdean** [comment]
I agree, there isn't an automated way of doing it. CCXT would have to become the source of truth which it is already sort of doing with `commonCurrencyCode`

**Comment by kroitor** [comment]
Would you agree that in that case the currency info should go into the .currencies, whereas fetchBalance should retain the old behaviour?

**Comment by gsdean** [comment]
absolutely, after talking to you, I have a better understanding of what the keys are in the dictionary returned by `fetchbalance`

**Comment by kroitor** [comment]
@gsdean ok, we will consider adding that info where it is known for sure and your contributions are welcome as well. Our topmost priorities are the support for arbitrary precision and websocket support, so, we will probably address this issue afterwards. Let us know if you have any further questions or more design considerations. Thx!

**Comment by gsdean** [comment]
cool, I'm a huge fan and anxiously awaiting websocket support myself.

I'll have to deal with the ambiguity in the application I'm working on, so, if I can do so in a manner that makes sense to roll into the library, I'll definitely create a PR.

**Comment by gsdean** [comment]
Just wanted to follow up based on my research two ideas have come up:

1. We could look at the wallets for the exchanges (i.e. https://etherscan.io/address/0x3f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be). This gives a pretty good signal to which contract the symbol refers too
2. We could use the dex community to make further assumptions (https://github.com/MyCryptoHQ/mycrypto.com/blob/8a2660acb881492ff18618e71ed5448158e2c445/app/scripts/tokens/ethTokens.json)

That's it for now, no real "solution", just some ideas that have surfaced...

**Comment by kroitor** [comment]
@gsdean thanks for useful hints and for your help!
