### ISSUE TITLE
Poloniex public returnChartData should return more data

### ISSUE THREAD

**Issue by erhardsc** [ccxt/ccxt#1878]
On the Poloniex documentation (https://poloniex.com/support/api/) you can call the method **returnChartData** and it should return the date, OHLCV, quote volume, and weighted average. 

![screenshot 2018-02-11 23 52 00](https://user-images.githubusercontent.com/17289312/36085954-a53fb5fe-0f86-11e8-98de-680303a0da1b.png)

In the ccxt wrapper for Poloniex, I can only get the OHLCV data and no weighted average.

I tried looking at the method **parse_ticker** in ccxt will always display none for the vwap and averages.

![screenshot 2018-02-11 23 53 18](https://user-images.githubusercontent.com/17289312/36085975-c2d32f74-0f86-11e8-9d20-14356b6b18f7.png)

Is there any chance I can get access to the weighted average that Poloniex already provides through their API using ccxt?

- OS: Mac OSX High Sierra 
- Programming Language version: Python 3.6.3
- CCXT version: 1.10.1085
- Exchange: Poloniex
- Method: parse_ticker

**Comment by kroitor** [comment]
> Is there any chance I can get access to the weighted average that Poloniex already provides through their API using ccxt?

Sure! There are many ways to your choice:
1. Because Poloniex returns the vwap from their OHLCV endpoint, that info is not present on tickers, however, if you fetch_ohlcv, the data they returned is available on the exchange instance in the `.last_json_response` property.
2. Alternatively, you can get that data from their method directly with ccxt: ```poloniex.public_get_returnchartdata``` – this will return a JSON as is from the exchange, unparsed.
3. You can mix between the two approaches to do it in a combined way (both parsed and handled manually simultaneously). Just use existing methods, as described in the Manual, here: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

```
console.log (new ccxt.kraken ())   // JavaScript
print (dir (ccxt.hitbtc ()))        # Python
var_dump (new \ccxt\okcoinusd ()); // PHP
```

Unfortunately, Poloniex doesn't return the vwap data from their tickers API:

```Python
>>> pprint(p.fetch_ticker('ETH/BTC'))
{'ask': 0.09990412,
 'average': None,
 'baseVolume': 14223.68208947,
 'bid': 0.09988393,
 'change': -0.00162654,
 'close': None,
 'datetime': '2018-02-12T07:05:15.703Z',
 'first': None,
 'high': 0.10113793,
 'info': {u'baseVolume': u'1424.80308676',
          u'high24hr': u'0.10113793',
          u'highestBid': u'0.09988393',
          u'id': 148,
          u'isFrozen': u'0',
          u'last': u'0.09988393',
          u'low24hr': u'0.09883001',
          u'lowestAsk': u'0.09990412',
          u'percentChange': u'-0.00162654',
          u'quoteVolume': u'14223.68208947'},
 'last': 0.09988393,
 'low': 0.09883001,
 'open': None,
 'percentage': None,
 'quoteVolume': 1424.80308676,
 'symbol': u'ETH/BTC',
 'timestamp': 1518419115703,
 'vwap': None}
>>>
```

Let us know if the above info does not help. Thx!

**Comment by erhardsc** [comment]
@kroitor Thank you so much for the detailed answer! However, I'm struggling to get my code to work with what you just mentioned above. Here is what I'm currently doing with ccxt using the Poloniex API.

`if (exchange == "poloniex"):
            # Grab Stored keys
            self.key = config.POLONIEX_CONFIG['key']
            self.secret = config.POLONIEX_CONFIG['secret']
            self.exchange = ccxt.poloniex()

            if backtest:
                self.exchange.load_markets()
                # Fetch public array of ohlcv data
                **poloData = self.exchange.fetch_ohlcv**(
                    self.pair, self.period, None, None, {
                        "start": self.startTime,
                        "end": self.endTime
                    })`

I'm a little unsure what to do with `self.exchange.fetch_ohlcv`

**Comment by kroitor** [comment]
```Python
if backtest:
    self exchange.load_markets()
    # fetch public array of ohlcv data
    # leave the call to fetch_ohlcv as is
    poloData = self.exchange.fetch_ohlcv(
        self.pair, self.period, None, None, {
            "start": self.startTime,
            "end": self.endTime
        })
    # add the following line:
    extendedData = self.exchange.last_json_response
    # from here you can now access the basic parsed data in poloData or
    # you can also access the raw unparsed extendedData, containing the average price, etc...
    # both variables contain JSON-like structures (dictionaries and lists) of data
```

Hope it helps.

**Comment by erhardsc** [comment]
Awesome! Works like a charm!
