### ISSUE TITLE
Binance Requests Constantly Print HTML

### ISSUE THREAD

**Issue by kaanguven** [ccxt/ccxt#18797]
### Operating System

Windows

### Programming Languages

Python

### Description

My code just prints constantly :

```
binance GET https://fapi.binance.com/fapi/v1/positionRisk?timestamp=16915108&recvWindow=10000&signature=3b58246ece86e6463ab4452d79b8f75a7 404 Not Found <!DOCTYPE html>
<!-- saved from url=(0032)https://www.binance.com/en/error -->
<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <meta name="format-detection" content="telephone=no,email=no,address=no">
  <title>Binance</title>
  <link rel="Shortcut Icon" href="https://www.binance.com/en/favicon.ico">
  <style>
    body {
      margin: 0
    }

    .img {
      width: 611px;
      margin: 68px auto 0
    }

    .info {
      width: 370px;
      margin: 0 auto;
      text-align: center;
      font-family: Arial;
    }

    .info h3 {
      margin: 0;
      font-size: 25px;
      color: #333;
      font-weight: normal;
    }

    .info p {
      font-size: 14px;
      font-family: Arial;
      color: #333;
      line-height: 18px;
      margin: 0
    }

    .info button {
      margin-top: 20px;
      width: 231px;
      height: 34px;
      background: #FFFFFF;
      border: 1px solid #F0B90B;
      box-sizing: border-box;
      border-radius: 3px;
      font-size: 14px;
      line-height: 16px;
      color: #F0B90B;
    }
  </style>
</head>

<body>
  <div class="img"><img alt="" src="/errorPages/404.jpg"></div>
  <div class="info">
    <h3>出错啦！您访问的网页不存在。</h3>
    <p>Sorry! The page you’re looking for cannot be found.</p>
    <a href="https://www.binance.com">
      <button>Return to Binance home page</button>
    </a>
  </div>

</body>

</html>
```

### Code

```
async def startBot(symbol,balanceNet):
        global TPSL,profitPrint,totalProfit,win,lose,winLoseTotal,leverage,startingBalance,leverage,currency,stopControl,botMode,carpan
        await account_binance.set_leverage(leverage, symbol)

        while True:
            try:
                ohlcvLB = await account_binance.fetch_ohlcv(symbol, timeframe)
                dfLB = pd.DataFrame(ohlcvLB, columns=['time', 'open', 'high', 'low', 'close', 'volume'])
                if len(ohlcvLB):
                    dfLB['time'] = pd.to_datetime(dfLB['time'], unit='ms')
                    priceCoin = await account_binance.fetch_ticker(symbol)
                    priceCoin = priceCoin["last"]
                    miktar = balanceNet/priceCoin
                    checkOpenPosition = await account_binance.fetch_positions(symbols = [symbol])
                    checkOpenOrder = await account_binance.fetch_open_orders(symbol)
                    //Some stuff but there is no request


        
            except Exception as e:
                print(e)

                 continue
                

```

**Comment by Rishirandhawa** [comment]
Getting same error randomly every few hours ! Seems to be 404 not found and returning junk. Any ideas yet what could be causing it ?

**Comment by carlosmiei** [comment]
Hello @Rishirandhawa @kaanguven, thanks for letting us know. Can you please share with us your ccxt version + a verbose log?

**Comment by carlosmiei** [comment]
@Rishirandhawa @kaanguven Actually, I noticed that your ccxt version is still using the now deprecated v1 endpoint, that might explain it. Can you please upgrade your CCXT version that already uses the newly added v2?

**Comment by kaanguven** [comment]
> @Rishirandhawa @kaanguven Actually, I noticed that your ccxt version is still using the now deprecated v1 endpoint, that might explain it. Can you please upgrade your CCXT version that already uses the newly added v2?

I actually did yesterday still same

**Comment by Rishirandhawa** [comment]
Yes. It seems CCXT is using V1 endpoint. However I updated CCXT library yesterday again and it's still pulling V1. 

Snapshot from error log below. 



Main loop error exit bot4 
Time (UTC): 2023-08-07 11:01 
Margin Ratio: 0.19926267740422426 
binance GET https://fapi.binance.com/fapi/v1/positionRisk?timestamp=1691406063333&symbol=XRPUSDT&recvWindow=10000&signature=49554eea802fb2c4f358dc00d87398a045d0d251d44cfcfc81544e72c45a0f04 404 Not Found <!DOCTYPE html>

<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <meta name="format-detection" content="telephone=no,email=no,address=no">
  <title>Binance</title>
  <link rel="Shortcut Icon" href="https://www.binance.com/en/favicon.ico">
  <style>

**Comment by carlosmiei** [comment]
> Yes. It seems CCXT is using V1 endpoint. However I updated CCXT library yesterday again and it's still pulling V1. Also strangely I am seeing this issue once every few hours. If it was constantly using V1 then I should see this issue every second. However it's happening randomly.
> 
> Snapshot from error log below.
> 
> Main loop error exit bot4 Time (UTC): 2023-08-07 11:01 Margin Ratio: 0.19926267740422426 binance GET https://fapi.binance.com/fapi/v1/positionRisk?timestamp=1691406063333&symbol=XRPUSDT&recvWindow=10000&signature=49554eea802fb2c4f358dc00d87398a045d0d251d44cfcfc81544e72c45a0f04 404 Not Found
> 
> <title>Binance</title> <style>

@Rishirandhawa I will double-check

**Comment by carlosmiei** [comment]
@Rishirandhawa which unified  method are you calling?

**Comment by Rishirandhawa** [comment]
I am callling private method - fapiPrivateGetPositionRisk

I have not upgraded the code yet to start using unified method fetchPositionsRisk

**Comment by carlosmiei** [comment]
> I am callling private method - fapiPrivateGetPositionRisk
> 
> I have not upgraded the code yet to start using unified method fetchPositionsRisk

@Rishirandhawa oh ok that explains it, you're calling the endpoint directly not a unified method. 

Can you try to call the upgrade version instead? `fapiPrivateV2GetPositionRisk`

**Comment by Rishirandhawa** [comment]
ah .. I see so new private method was created for V2 endpoint. Thanks @carlosmiei I will update the method. Will get to upgrading to unified methods soon as well since I see several new have been added that didn't exist before. Keep up the great work everyone !!

**Comment by kaanguven** [comment]
> > I am callling private method - fapiPrivateGetPositionRisk
> > I have not upgraded the code yet to start using unified method fetchPositionsRisk
> 
> @Rishirandhawa oh ok that explains it, you're calling the endpoint directly not a unified method.
> 
> Can you try to call the upgrade version instead? `fapiPrivateV2GetPositionRisk`

I only use fetch, open_positions stuff etc. what about me ?

**Comment by carlosmiei** [comment]
@kaanguven what is your ccxt version and which ccxt method are you using?

**Comment by kaanguven** [comment]
> 

![1](https://github.com/ccxt/ccxt/assets/83061705/edb07955-bc06-4b9e-824d-7708e07a542d)


> > > @kaanguven what is your ccxt version and which ccxt method are you using?
> > 
> > 
> > version: 4.0.52
> > And methods are classic:
> > fetch_ohlc create_order fetch_positions fetch_open_orders fetch_ticker fetch_balance set_leverage cancel_all_orders
> > thats all i use
> 
> @kaanguven hum if you're using that version, the endpoint used by ccxt should be the v2, can you pls double-check your version by doing `print(ccxt.__version__)` ?
![1](https://github.com/ccxt/ccxt/assets/83061705/621b7d8d-6fbd-49ae-8873-c8800c29d590)

**Comment by msobh13** [comment]
same issue with version  : 4.0.53

**Comment by Rishirandhawa** [comment]
Use fapiPrivateV2GetPositionRisk instead of fapiPrivateGetPositionRisk

**Comment by msobh13** [comment]
> 

thanks . it works !

**Comment by carlosmiei** [comment]
> /bin/pip:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
> 
> Maybe this causes ?

@kaanguven it does not seem related to this error

**Comment by Rishirandhawa** [comment]
@kaanguven based on your errorlog there is certainly a call going to V1 positionrisk private method in your code. None of Classic or Unified methods you posted above make the positionrisk endpoint call. Please check position risk call and method used in your code.

**Comment by kaanguven** [comment]
> > /bin/pip:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
> > Maybe this causes ?
> 
> @kaanguven it does not seem related to this error

I just updated CCXT and reset PC and its gone... weird but im OK ! :D Thanks carlos 🥇

**Comment by carlosmiei** [comment]
> > > /bin/pip:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
> > > Maybe this causes ?
> > 
> > 
> > @kaanguven it does not seem related to this error
> 
> I just updated CCXT and reset PC and its gone... weird but im OK ! :D Thanks carlos 🥇

No problem let us know if anything.

@Rishirandhawa @kaanguven @msobh13 The reported issue seems resolved by now so I will close this issue, feel free to reopen it if needed.
