### ISSUE TITLE
Bittrex does not have market symbol BTS/BTC

### ISSUE THREAD

**Issue by AhmMontasser** [ccxt/ccxt#1879]
Hello,

When using bittrex as the exchange the code returns an error while using exchange.fetch_ohlcv('BTS/BTC') 
while exchange.fetch_tickers() returns BTS/BTC as available ticker
The error is 
'ccxt.base.errors.ExchangeError: bittrex does not have market symbol BTS/BTC
'
Os: ubuntu 16.04 
python: 2.7.12 
exchange: bittrex 
method: .fetch_ohlcv()
ccxt version: 1.10.1036

**Comment by kroitor** [comment]
They don't offer any trading against BTS now, the error literally says it. Do you have any difficulties interpreting it? You can check that with their website.

![screen shot 2018-02-12 at 11 24 27](https://user-images.githubusercontent.com/1294454/36088247-623ebb0e-0fe7-11e8-916c-426e50a6f68e.png)

Hope it answers your question.

**Comment by AhmMontasser** [comment]
Thank you :)
