### ISSUE TITLE
How to parse & stringify BigInt in API request and response?

### ISSUE THREAD

**Issue by zgayjjf** [ccxt/ccxt#18809]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

There are some exchanges that store certain fields using BigInt, but when making API requests and calls, they use number directly instead of strings
For example:
```json
{
"orderId": 10996216051743211
}
```
The values above will produce wrong number during actual parsing due to precision issues. JS will interpret them as follows (note the last digit):
```json
{
"orderId": 10996216051743212
}
```

How should we parse this kind of data (Response body)? 
And when serializing, how should we perform serialization (Request body)?

### Describe the solution you'd like

1. We can specify how to perform serialization before making the request.
2. We can specify how to deserialize the response body before it is parsed by JSON.parse.

### Describe alternatives you've considered

[json-bitint](https://www.npmjs.com/package/json-bigint) seems to be a solution, can we import that and replace the default `fetch` method?

**Comment by carlosmiei** [comment]
Hey @zgayjjf, actually we have a method `convertToBigInt` to handle these cases. 

Can you pls specify which exchanges are having this problem?

**Comment by zgayjjf** [comment]
Hey @carlosmiei,  Thanks for the remind.  But I think `convertToBigInt` can not solve the problem here.
I want to integrate [pionex](https://pionex-doc.gitbook.io/apidocs/restful/orders/new-order) into ccxt. Their `order_id` are all `BigInt`, including request params and response body.

> Ideally, the should use string to transfer the `order_id`, but they just use plain number to do the thing.

I think that `convertToBigInt` can only be used to convert a string to BigInt. But now we need to parse the HTTP response body and parse the body using a library like `json-bigint`

For example, how to correctly parse the following **API response data**?
```
{"orderId":10996216051743211}
```
Paste this data into DevTool to view it, pay attention to the last digit, I think you should be able to understand what I mean.

**Comment by zgayjjf** [comment]
Here are two examples, notice the `orderId`:
```
// in request body
DELETE https://{site}/api/v1/trade/order
{
  "symbol":  "BTC_USDT",
  "orderId":  10996216051900939
}
```

```
// request
GET https://{site}/api/v1/trade/order?symbol=BTC_USDT&orderId=1234567890

// response
{ 
  "data": {
    "orderId": 10996216051900939,
    "symbol": "BTC_USDT",
    "type": "LIMIT",
    "side": "SELL",
    "price": "30000.00",
    "size": "0.1000",
    "filledSize": "0.0500",
    "filledAmount": "1500.00",
    "fee":  "0.15",
    "feeCoin":  "USDT",
    "status": "OPEN",
    "IOC":  false,
    "clientOrderId":  "9e3d93d6-e9a4-465a-a39c-2e48568fe194",
    "source": "API",
    "createTime": 1566676132311,
    "updateTime": 1566676132311
  },
  "result": true,
  "timestamp": 1566691672311
}

```

**Comment by zgayjjf** [comment]
I noticed that you have a method called `onJsonResponse` handled this kind of thing, I will try to resolve the thing with the same method.

I will close the issue the time I solve the problem or I will ask for your help.

Thanks all the same!

**Comment by zgayjjf** [comment]
I have solved the problem with the method we mentioned before.
I will submit a PR once I finish the integration.
