### ISSUE TITLE
BingX fetch_ohlcv() spot market support could be added

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#18804]
### Operating System

Linux Mint

### Programming Languages

Python

### CCXT Version

4.0.50

### Description

Spot market support could be added for `fetch_ohlcv` :

https://bingx-api.github.io/docs/#/spot/market-api.html#Candlestick%20chart%20data
https://open-api.bingx.com/openApi/spot/v1/market/kline?symbol=BTC-USDT&interval=1d

### Code

```
exchange = ccxt.bingx()
exchange.fetch_ohlcv('BTC/USDT')
```

```
Traceback (most recent call last):
  File "/home/xyz/test.py", line 4, in <module>
    exchange.fetch_ohlcv('BTC/USDT')
  File "/home/xyz/.local/lib/python3.10/site-packages/ccxt/bingx.py", line 567, in fetch_ohlcv
    raise NotSupported(self.id + ' fetchOHLCV is not supported for spot markets')
ccxt.base.errors.NotSupported: bingx fetchOHLCV is not supported for spot markets
```

**Comment by carlosmiei** [comment]
Hey @JovianMoon, thanks a lot for letting us know, will be added asap.
