### ISSUE TITLE
BingX fetch_trades() 'side' should be assigned

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#18827]
### Operating System

Linux Mint

### Programming Languages

Python

### CCXT Version

4.0.53

### Description

For BingX exchange `fetch_trades` assigns value for 'takerOrMaker' and 'side' is always None. In BingX API documentation (https://bingx-api.github.io/docs/#/spot/market-api.html#Query%20transaction%20records) 'isBuyerMaker' is described as "Buyer or not" suggesting that returned trades are always for maker of the trade and this boolean determines the side. I got a similar impression by comparing their API response to the trades shown at their website.

In my opinion it would be the least confusing for the ccxt user if trades would, whenever possible, be converted into **taker** trades and have the 'side' be determined as 'buy' or 'sell'. Or perhaps there is a technical limitation why it can't be always done?

As a side note `parse_trade` also assigns value (always 'taker' I think) for 'isBuyerMaker' for swap trades when `fetch_my_trades` is called, even though the API response doesn't seem to contain any taker/maker nor side information.

### Code

```
exchange = ccxt.bingx()

total_trade_count = 0      
buy_trade_count = 0
sell_trade_count = 0  
maker_trade_count = 0
taker_trade_count = 0

trades = exchange.fetch_trades('RBE/USDT', limit=100)
for trade in trades:
    total_trade_count += 1
    if trade['side'] == 'buy':
        buy_trade_count += 1
    if trade['side'] == 'sell':
        sell_trade_count += 1
    if trade['takerOrMaker'] == 'maker':
        maker_trade_count += 1
    if trade['takerOrMaker'] == 'taker':
        taker_trade_count += 1        
    
print(trades[0])
print('total trades:', total_trade_count)
print('buy trades:  ', buy_trade_count)
print('sell trades: ', sell_trade_count)   
print('maker trades:', maker_trade_count)
print('taker trades:', taker_trade_count)
```

```
{'id': '245505', 'info': {'id': '245505', 'price': '0.000000288', 'qty': '37320104', 'time': '1691164567717', 'buyerMaker': True}, 'timestamp': 1691164567717, 'datetime': '2023-08-04T15:56:07.717Z', 'symbol': 'RBE/USDT', 'order': None, 'type': None, 'side': None, 'takerOrMaker': 'maker', 'price': 2.88e-07, 'amount': 37320104.0, 'cost': 10.748189952, 'fee': {'cost': None, 'currency': None, 'rate': None}, 'fees': [{'cost': None, 'currency': None, 'rate': None}]}
total trades: 100
buy trades:   0
sell trades:  0
maker trades: 60
taker trades: 40
```

**Comment by sc0Vu** [comment]
Hi @JovianMoon

The `side` isn't in the api response, can't set in trade struct.

For the takerOrMaker, I'll submit PR to fix this.

**Comment by JovianMoon** [comment]
@sc0Vu 
> The `side` isn't in the api response, can't set in trade struct.

Are you sure? According to their API docs 'isBuyerMaker' is described as "Buyer or not". 

They have named 'isBuyerMaker' parameter very problematically, because it can be interpreted two ways if the value is `false`. Either it then means that:
1) Buyer is not **maker**, so therefore buyer is actually **taker**.
2) **Buyer** is not maker, so therefore **seller** is actually maker.

My bet is that it means the latter.

**Comment by sc0Vu** [comment]
Hi @JovianMoon 

I think the side could be `buy` or `sell` if isBuyerMaker is true. Anyway, I'll ask about this value.

**Comment by JovianMoon** [comment]
@sc0Vu Thank you for investigating! There are also other examples in ccxt where 'side' is determined from 'isBuyerMaker' type of API responses. Here's one from `parse_trade` function of binance.py (lines 3381-3391):

```
        side = None
        orderId = self.safe_string(trade, 'orderId')
        buyerMaker = self.safe_value_2(trade, 'm', 'isBuyerMaker')
        takerOrMaker = None
        if buyerMaker is not None:
            side = 'sell' if buyerMaker else 'buy'  # self is reversed intentionally
        elif 'side' in trade:
            side = self.safe_string_lower(trade, 'side')
        else:
            if 'isBuyer' in trade:
                side = 'buy' if trade['isBuyer'] else 'sell'  # self is a True side
```

The logic seems to be that "not buyer" equals "seller".

@kroitor Could this issue be kept open a little bit longer? In my opinion there is still a bug here.

**Comment by JovianMoon** [comment]
@sc0Vu I asked BingX support about meaning of "isBuyerMaker" field and how should `true` and `false` values be interpreted. Their response was very short, but clear:

> Hi ,
> if the value of isBuyerMaker field is false?  => sell

Could this issue now please be reopened and the problem fixed?
