### ISSUE TITLE
Iceberg orders on MEXC

### ISSUE THREAD

**Issue by sandstorm111** [ccxt/ccxt#18831]
### CCXT Version

^4.0.18

### Description

How to send iceberg/hidden spot orders on Mexc? Orders that don't have the amount displayed in the order book.

Haven't found anything in their documentation, aside from the existence the field "icebergQty" in some responses:

https://mxcdevelop.github.io/apidocs/spot_v3_en/#current-open-orders
https://mxcdevelop.github.io/apidocs/spot_v3_en/#all-orders

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @sandstorm111

I can't find any parameter in their documentation. Maybe you can ask exchange for help?

**Comment by PabloAliArgentina** [comment]
I can try in the Telegram API support channel:

[te.me/MEXCAPIsupport](url)

**Comment by taahanizam** [comment]
Has someone found the answer?

**Comment by samgermain** [comment]
It's not available using the Mexc API, you can contact Mexc support and make a feature request if you would like them to implement it, that looks like the only option
