### ISSUE TITLE
Bybit stop limit orders cannot be canceled

### ISSUE THREAD

**Issue by hodlerhacks** [ccxt/ccxt#18857]
### Operating System

Windows

### Programming Languages

JavaScript

### CCXT Version

4.0.57

### Description

When placing stop loss orders, using the CCXT unified method, on Bybit spot market (using a Unified Bybit account), it is not possible to cancel those orders. As an example, this is what I did:

`await exchange.createOrder('BTC/USDT', 'limit', 'sell', 0.001, 28500, { stopLossPrice: 29000 });`

When using `exchange.cancelAllOrders('BTC/USDT')`, the order is not canceled. No exception is thrown, but I still see the open order on the exchange.

When using `exchange.cancelOrder(<id>, 'BTC/USDT')`, using the id that is returned when creating the order, does not work either. In that case I get the following exception:

OrderNotFound: bybit {"retCode":170213,"retMsg":"Order does not exist.","result":{},"retExtInfo":{},"time":1691743905604}
    at bybit.throwExactlyMatchedException (C:\code\crypto-coding-course\code\cc-bot\node_modules\ccxt\dist\cjs\src\base\Exchange.js:3087:19)
    at bybit.handleErrors (C:\code\crypto-coding-course\code\cc-bot\node_modules\ccxt\dist\cjs\src\bybit.js:9161:18)
    at C:\code\crypto-coding-course\code\cc-bot\node_modules\ccxt\dist\cjs\src\base\Exchange.js:766:51
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async bybit.fetch2 (C:\code\crypto-coding-course\code\cc-bot\node_modules\ccxt\dist\cjs\src\base\Exchange.js:2666:16)
    at async bybit.request (C:\code\crypto-coding-course\code\cc-bot\node_modules\ccxt\dist\cjs\src\base\Exchange.js:2669:16)
    at async bybit.cancelUnifiedAccountOrder (C:\code\crypto-coding-course\code\cc-bot\node_modules\ccxt\dist\cjs\src\bybit.js:4690:26)
    at async bybit.cancelOrder (C:\code\crypto-coding-course\code\cc-bot\node_modules\ccxt\dist\cjs\src\bybit.js:4874:20)

Am I doing something wrong, or is this a bug?

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @hodlerhacks,
Have you tried to provide `stop:true` inside `params`? 

Example:
```Python
exchange.cancelAllOrders('BTC/USDT', {'stop': true})
```

**Comment by hodlerhacks** [comment]
Oh wow, that solves it indeed, thanks! :-)

I couldn't find this in the documentation. What exactly does this parameter do? When should I use it? Is it Bybit-specific and/or can I safely use that with other exchanges as well? (I'm developing an application that works with many different exchanges, and I'm trying to keep the code as generic as possible, hence the question.)

**Comment by carlosmiei** [comment]
> I couldn't find this in the documentation. What exactly does this parameter do? When should I use it? Is it Bybit-specific and/or can I safely use that with other exchanges as well? (I'm developing an application that works with many different exchanges, and I'm trying to keep the code as generic as possible, hence the question.)

@hodlerhacks Some exchanges have different endpoints to handle stop/trigger orders, so the `stop` parameter tells ccxt to use that endpoint instead, and yes it is unified across exchanges so you should be able to use it with other exchanges as well.

Additionally, we will try to improve our documentation, thanks for letting us know.

**Comment by hodlerhacks** [comment]
Thanks for clarifying and your quick response, appreciate it!

**Comment by carlosmiei** [comment]
@hodlerhacks no problem, feel free to reach out any time.
