### ISSUE TITLE
Phemex create withdraw should have otpCode

### ISSUE THREAD

**Issue by AdamSEY** [ccxt/ccxt#18850]
### Operating System

MacOS

### Programming Languages

JavaScript

### CCXT Version

4.0.21

### Description

According to the docs: https://github.com/phemex/phemex-api-docs/blob/master/Public-Contract-API-en.md#requestwithdraw

### Code

```
  async withdrawPhemex(amount, address, secret) {
		const params = {
			network: 'BEP20',
			"address": address,             
			"amountEv": amount,              
			"currency": 'USDT',
			otpCode: this.getGoogleAuthCode(secret)
		}
		return exchanges.phemex.privatePostExchangeWalletsCreateWithdraw(params)
		// Perform the withdrawal
	}

```

**Comment by samgermain** [comment]
Hi @AdamSEY

Thanks for posting, I don't understand what your question is though. Could you clarify a bit?

**Comment by AdamSEY** [comment]
Sorry if my question was not clear enough. According to [Phemex docs](https://github.com/phemex/phemex-api-docs/blob/master/Public-Contract-API-en.md#requestwithdraw), we need otpCode to create a withdraw and it should be sent as not in the body but in the URL query: POST /exchange/wallets/createWithdraw?otpCode=<otpCode>

When I try to send the code in the params, I get the following error:

ExchangeError: phemex {"code":30004,"msg":"phemex.error.otp.code","data":null}

However, it's good to mention that I had to use "privatePostExchangeWalletsCreateWithdrawAddress" instead of "privatePostExchangeWalletsCreateWithdraw" as this one returns the following:

ExchangeNotAvailable: phemex POST https://api.phemex.com/exchange/wallets/createWithdraw 404 Not Found {"timestamp":1691704967811,"status":404,"error":"Not Found","path":"/phemex-user/wallets/createWithdraw"}

**Comment by AdamSEY** [comment]
I think they are using a different endpoint:

https://phemex-docs.github.io/#create-withdraw-request

**Comment by samgermain** [comment]
@AdamSEY It looks like the [unified withdraw method](https://docs.ccxt.com/#/README?id=withdrawal) needs to be written for phemex, I'll probably do this next week

**Comment by mflanagan1041** [comment]
is there any update on this implementation?

**Comment by samgermain** [comment]
> is there any update on this implementation?

I created a [PR](https://github.com/ccxt/ccxt/pull/19936) to implement it, but receive the error `ExchangeError phemex {"msg":"please try again later! No matching handler","code":10500}` whenever I try to access the deposit/withdraw endpoints, I guess I'll try again later like it says
