### ISSUE TITLE
WEX PHP Fatal error: ExchangeError (invalid nonce parameter)

### ISSUE THREAD

**Issue by canegor** [ccxt/ccxt#1886]
- OS: FreeBSD wild 10.1-RELEASE FreeBSD 10.1-RELEASE #0 r274401: Tue Nov 11 22:51:51 UTC 2014     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  i386

- Programming Language version:
PHP 5.6.30 (cli) (built: Feb 25 2017 01:31:17) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

- CCXT version:
1.10.1085

- Exchange:
HP Fatal error:  Uncaught exception 'ccxt\ExchangeError' with message 'wex {"success":0,"error":"invalid nonce parameter; on key:1518520834, you sent:'1518520834', you should send:1518520835"}'

- Method:
create_limit_buy_order

Invalid nonce parameter for all action on the WEX! fetch_balance and other was woked normally.
cancel order

**Comment by kroitor** [comment]
@canegor add `array('enableRateLimit' => true)` to exchange constructor params, like shown here: https://github.com/ccxt/ccxt/blob/master/examples/php/built-in-rate-limiting-poller.php

More about it here:
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#authentication
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-the-nonce

Let us know if it does not solve the issue for you. Thx!
