### ISSUE TITLE
Does fetch_my_trades['info']['realizedPnl'] include commisions ?

### ISSUE THREAD

**Issue by kaanguven** [ccxt/ccxt#18864]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.0

### Description

In my code output is like :

```
{'amount': 103.0,
 'cost': 29.9421,
 'datetime': '2023-08-11T15:41:53.014Z',
 'fee': {'cost': 0.00598842, 'currency': 'USDT'},   
 'fees': [{'cost': 0.00598842, 'currency': 'USDT'}],
 'id': '249279148',
 'info': {'buyer': False,
          'commission': '0.00598842',
          'commissionAsset': 'USDT',
          'id': '249279148',
          'maker': True,
          'marginAsset': 'USDT',
          'orderId': '8705959000',
          'positionSide': 'BOTH',
          'price': '0.29070',
          'qty': '103',
          'quoteQty': '29.94210',
          'realizedPnl': '0.16480000',
          'side': 'SELL',
          'symbol': 'ENJUSDT',
          'time': '1691768513014'},
 'order': '8705959000',
 'price': 0.2907,
 'side': 'sell',
 'symbol': 'ENJ/USDT:USDT',
 'takerOrMaker': 'maker',
 'timestamp': 1691768513014,
 'type': None}
```
 My question is, as you see here 'realizedPnl': '0.16480000', is that include 'commission': '0.00598842', or not ?
 

### Code

```
  
total_pnl = 0
                trades = await account_binance.fetch_my_trades("ENJ/USDT",limit=200)
                for trade in reversed(trades):
                    realized_pnl = float(trade['info']['realizedPnl'])
                    commision = float(trade['info'].get('commission', 0))
                    pprint.pprint(trade)
                    if realized_pnl > 0:
                        print("total pnl ",total_pnl)
                        # pprint.pprint(trade)
                        break
                    total_pnl += realized_pnl - commision
```

**Comment by samgermain** [comment]
The info block includes the raw, unparsed, non-unified response that you receive from the exchange. CCXT explains the other properties in the [manual](https://docs.ccxt.com/#/README), but info will look different for each exchange, so if you want to learn anything about the properties inside info, you should look through the documentation from that specific exchange

It looks like your using binance because of your variable named `account_binance` so [this is the binance documentation](https://binance-docs.github.io/apidocs/spot/en/#spot-account-trade)

**Comment by kaanguven** [comment]
> The info block includes the raw, unparsed, non-unified response that you receive from the exchange. CCXT explains the other properties in the [manual](https://docs.ccxt.com/#/README), but info will look different for each exchange, so if you want to learn anything about the properties inside info, you should look through the documentation from that specific exchange
> 
> It looks like your using binance because of your variable named `account_binance` so [this is the binance documentation](https://binance-docs.github.io/apidocs/spot/en/#spot-account-trade)

There is no info in documents about fees are in realized pnl or not

**Comment by samgermain** [comment]
> > The info block includes the raw, unparsed, non-unified response that you receive from the exchange. CCXT explains the other properties in the [manual](https://docs.ccxt.com/#/README), but info will look different for each exchange, so if you want to learn anything about the properties inside info, you should look through the documentation from that specific exchange
> > It looks like your using binance because of your variable named `account_binance` so [this is the binance documentation](https://binance-docs.github.io/apidocs/spot/en/#spot-account-trade)
> 
> There is no info in documents about fees are in realized pnl or not

That's correct, you'll need to need to check the exchange api docs for that

**Comment by kaanguven** [comment]
> > > The info block includes the raw, unparsed, non-unified response that you receive from the exchange. CCXT explains the other properties in the [manual](https://docs.ccxt.com/#/README), but info will look different for each exchange, so if you want to learn anything about the properties inside info, you should look through the documentation from that specific exchange
> > > It looks like your using binance because of your variable named `account_binance` so [this is the binance documentation](https://binance-docs.github.io/apidocs/spot/en/#spot-account-trade)
> > 
> > 
> > There is no info in documents about fees are in realized pnl or not
> 
> That's correct, you'll need to need to check the exchange api docs for that

There is no info too :D

**Comment by samgermain** [comment]
> > > > The info block includes the raw, unparsed, non-unified response that you receive from the exchange. CCXT explains the other properties in the [manual](https://docs.ccxt.com/#/README), but info will look different for each exchange, so if you want to learn anything about the properties inside info, you should look through the documentation from that specific exchange
> > > > It looks like your using binance because of your variable named `account_binance` so [this is the binance documentation](https://binance-docs.github.io/apidocs/spot/en/#spot-account-trade)
> > > 
> > > 
> > > There is no info in documents about fees are in realized pnl or not
> > 
> > 
> > That's correct, you'll need to need to check the exchange api docs for that
> 
> There is no info too :D

so we take the information given by the exchange, and parse it to a common format. If the exchange does not provide this information, then we cannot provide this information. You will probably need to create some positions, and do the math to figure out if the realizedPnl includes commissions. [Here are the formulas to calculate PNL](https://www.binance.com/en/support/faq/how-to-calculate-profit-and-loss-for-futures-contracts-3a55a23768cb416fb404f06ffedde4b2)
