### ISSUE TITLE
Binance USD-M what is best way to put stop loss?

### ISSUE THREAD

**Issue by kaanguven** [ccxt/ccxt#18877]
### Operating System

Windows

### Programming Languages

Python

### Description

Which of the following is the correct way to put a stop loss?

Using ReduceOnly or using closePosition as a parameter?

I would be glad if you explain the difference.

### Code

```
  # -*- coding: utf-8 -*-

import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402

exchange = ccxt.binanceusdm({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

markets = exchange.load_markets()
# exchange.verbose = True  # uncomment for debugging purposes

symbol = 'BTC/USDT'
side = 'buy'
amount = 0.01
price = None
stopLossPrice = 25000
takeProfitPrice = 35000

try:

    order = exchange.create_order(symbol, 'MARKET', side, amount)
    print(order)

    inverted_side = 'sell' if side == 'buy' else 'buy'
   #1
    stopLossParams = {'stopPrice': stopLossPrice}
    stopLossOrder = exchange.create_order(symbol, 'STOP_MARKET', inverted_side, amount, price, {'stopPrice': stopLossPrice,"closePosition":True})
    print(stopLossOrder)

  #2
  stopLossParams = {'stopPrice': stopLossPrice}
      stopLossOrder = exchange.create_order(symbol, 'STOP_MARKET', inverted_side, amount, price, {'stopPrice': stopLossPrice,"reduceOnly":True})
      print(stopLossOrder)

    

except Exception as e:
    print(type(e).__name__, str(e))

```

**Comment by Dan-krm** [comment]
The `closePosition` parameter is only used if you want to close the entire position without requiring an amount argument. Setting `closePosition` to true will automatically set `reduceOnly` to true.

In your case I would probably do:
```
exchange.create_order(symbol, 'STOP_MARKET', inverted_side, None, None, '{"stopLossPrice":stopLossPrice,"closePosition":True}'
````
or if you only want to partially close the position and specify the amount you could do:
```
exchange.create_order(symbol, 'STOP_MARKET', inverted_side, amount, None, '{"stopLossPrice":stopLossPrice,"reduceOnly":True}'
```

Most exchanges have limited API support for stop-losses, and there is some minor differences between exchanges, but you can read more about how CCXT is unifying `stop`, `stopLoss` and `takeProfit` orders in the CCXT Documentation:

https://docs.ccxt.com/#/README?id=stop-orders
https://docs.ccxt.com/#/README?id=stop-loss-orders
https://docs.ccxt.com/#/README?id=take-profit-orders
https://docs.ccxt.com/#/README?id=stoploss-and-takeprofit-orders-attached-to-a-position

**Comment by kaanguven** [comment]
> The `closePosition` parameter is only used if you want to close the entire position without requiring an amount argument. Setting `closePosition` to true will automatically set `reduceOnly` to true.
> 
> In your case I would probably do:
> 
> ```
> exchange.create_order(symbol, 'STOP_MARKET', inverted_side, None, None, '{"stopLossPrice":stopLossPrice,"closePosition":True}'
> ```
> 
> or if you only want to partially close the position and specify the amount you could do:
> 
> ```
> exchange.create_order(symbol, 'STOP_MARKET', inverted_side, amount, None, '{"stopLossPrice":stopLossPrice,"reduceOnly":True}'
> ```
> 
> Most exchanges have limited API support for stop-losses, and there is some minor differences between exchanges, but you can read more about how CCXT is unifying `stop`, `stopLoss` and `takeProfit` orders in the CCXT Documentation:
> 
> https://docs.ccxt.com/#/README?id=stop-orders https://docs.ccxt.com/#/README?id=stop-loss-orders https://docs.ccxt.com/#/README?id=take-profit-orders https://docs.ccxt.com/#/README?id=stoploss-and-takeprofit-orders-attached-to-a-position

Oh now i get it, closePosition param probably do some job like "Close Position" in binance, i didnt think like that . Thanks !
