### ISSUE TITLE
Avoiding rate limit issues

### ISSUE THREAD

**Issue by dorienh** [ccxt/ccxt#18878]
### Operating System

unix

### Programming Languages

JavaScript

### CCXT Version

latest

### Description

I am in need of advice as I want to understand how to avoid rate limits. 

Say I am trading on Binance Futures with multiple API keys, at the same time. 

I understand the rate limit is per API (so per account)? And I realise the enableRateLimit should follow this per exchange connection. 

But **is there a possibility to get blocked out because all these requests come from the same IP (even with different API keys?)**? 

I understand websockets are only for requesting price info and not placing orders? 

### Code

```
  

```

**Comment by pcriadoperez** [comment]
Hi @dorienh,

In the case of futures, acording to the binance docs they limit by IP not by account (https://binance-docs.github.io/apidocs/futures/en/#limits).

Also there is a possibility to get blocked ("IP bans are tracked and scale in duration for repeat offenders, from 2 minutes to 3 days")

Also we recently added trading though websockets, but it also has rate limits you need to be aware of.
Each CCXT exchange provides a throttler on the rest side and we are working on also correctly throtteling trades on websockets.

Hope this answers all the quetions, let me know if there is anything else we can help with

**Comment by pcriadoperez** [comment]
Hi closing this issue for now, but feel free to reach out with any questions
