### ISSUE TITLE
Bybit - Insufficient Balance error when sending future order with create_limit_buy_order function

### ISSUE THREAD

**Issue by yunuscancengiz** [ccxt/ccxt#18874]
### Operating System

Windows 64 bit

### Programming Languages

Python

### CCXT Version

4.0.56

### Description

I want to send a future limit buy order on the BTCUSDT pair to Bybit. Every time I try, I get an "Insufficient Balance" error. I have enough funds in my Bybit derivatives wallet to complete the transaction. Other wallets (spot, funding etc) do not have money. So I set the "defaultType" value to "future" but it didn't help. I am new to CCXT, can you help me? 

### Code

```
exchange = ccxt.bybit({
    "enableRateLimit":True,
    "apiKey":API_KEY, 
    "secret":SECRET_KEY,
    "options":{
        "defaultType":"future"
    }
})

exchange.create_limit_buy_order(symbol="BTCUSDT", amount=0.001, price=29250.5)

```

**Comment by germangar** [comment]
Try "defaultType":"swap"

**Comment by yunuscancengiz** [comment]
> 

I also tried changing it to "swap" but unfortunately it still gives "Insufficient Balance" error.

**Comment by kroitor** [comment]
@yunuscancengiz 

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help (plz read this carefully and follow literally, post your version, your code and your verbose output)
- https://github.com/ccxt/ccxt/wiki/Manual#contract-naming-conventions

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.bybit({
    "enableRateLimit":True,
    "apiKey":API_KEY, 
    "secret":SECRET_KEY,
    "options":{
        "defaultType":"swap"
    }
})

markets = exchange.load_markets()

exchange.verbose = True
balance = exchange.fetchBalance ()
pprint(balance)
exchange.create_limit_buy_order(symbol="BTC/USDT:USDT", amount=0.001, price=29250.5)
```

**Comment by yunuscancengiz** [comment]
> @yunuscancengiz
> 
> * https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help (plz read this carefully and follow literally, post your version, your code and your verbose output)
> * https://github.com/ccxt/ccxt/wiki/Manual#contract-naming-conventions
> 
> ```python
> import ccxt
> from pprint import pprint
> print('CCXT Version:', ccxt.__version__)
> exchange = ccxt.bybit({
>     "enableRateLimit":True,
>     "apiKey":API_KEY, 
>     "secret":SECRET_KEY,
>     "options":{
>         "defaultType":"swap"
>     }
> })
> 
> markets = exchange.load_markets()
> 
> exchange.verbose = True
> balance = exchange.fetchBalance ()
> pprint(balance)
> exchange.create_limit_buy_order(symbol="BTC/USDT:USDT", amount=0.001, price=29250.5)
> ```

This worked fine for me. Thank you very much for your support.
