### ISSUE TITLE
AttributeError: 'binance' object has no attribute 'fapiPrivate_get_positionside_dual'

### ISSUE THREAD

**Issue by netsesame** [ccxt/ccxt#18893]
### Operating System

ubuntu

### Programming Languages

Python

### CCXT Version

installed ccxt-4.0.61

### Description

AttributeError: 'binance' object has no attribute 'fapiPrivate_get_positionside_dual'

### Code

```
  response = self._exchange.fapiPrivate_get_positionside_dual()

```

**Comment by carlosmiei** [comment]
Hello @netsesame,
Can you try instead `fapiprivate_get_positionside_dual` or `fapiPrivateGetPositionSideDual`? For some reason the snake_case version is not breaking the `private` part.

**Comment by netsesame** [comment]
Sure, I can try using fapiprivate_get_positionside_dual or fapiPrivateGetPositionSideDualinstead of fapiPrivate_get_positionside_dual.  I will make the necessary changes and see if it resolves the issue. Thank you for your suggestion!"

**Comment by netsesame** [comment]
I copied it from line 126 of ccxt/examples/py/binance-futures-margin.py.After making the modification, it is now working properly. Thank you for your assistance.

**Comment by carlosmiei** [comment]
@netsesame you're welcome
