### ISSUE TITLE
New Exchange: BTCC.com

### ISSUE THREAD

**Issue by harshvardhanmalpani** [ccxt/ccxt#1891]
- ExchangeAPI: https://www.btcc.com/apidocs/usd-spot-exchange-websocket-api#authentication
- ExchangeURL: https://www.btcc.com

**Comment by PyPatel** [comment]
I can add Python Support for this API. I will do that this Weekend. @kroitor

**Comment by kroitor** [comment]
@PyPatel please, read this first: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

**Comment by frosty00** [comment]
no API yet
