### ISSUE TITLE
bybit watch_ticker is broken since 4.0.47

### ISSUE THREAD

**Issue by youknowone** [ccxt/ccxt#18931]
### Operating System

macOS/Windows

### Programming Languages

Python

### CCXT Version

4.0.59

### Description

`bybit.watch_ticker()` is broken ~somewhere between `3.1.42` and `4.0.59`~ since `4.0.47`.

~With the same code, I can reproduce the bug in `4.0.59` but not in `3.1.42`.
I didn't check which specific version broke it yet.~

Since `4.0.47`, it permanently hangs on second run of `watch_ticker`.

### Code

```python
import ccxt.pro

bybit = ccxt.pro.bybit()

async def main():
    # first run is always successful
    r = await bybit.watch_ticker('BTC/USDT:USDT', {})
    # second run is up to ccxt versions
    print('run second call')
    r = await bybit.watch_ticker('BTC/USDT:USDT', {})
    print(r)

import asyncio

asyncio.run(main())

```

**Comment by carlosmiei** [comment]
Hello @youknowone, thanks for letting us know, I will take a look asap

**Comment by carlosmiei** [comment]
@youknowone you're right there's a small issue with it, but we will fix it asap. thanks once again.
