### ISSUE TITLE
Binance fapiPrivate_post_positionmargin method not working

### ISSUE THREAD

**Issue by Sekharonline4u** [ccxt/ccxt#18930]
### Operating System

**Mac OS**

### Programming Languages

**Python**

### CCXT Version

**CCXT Version: 4.0.65**

### Description

I was trying to create a Market Buy Order for Isolated Trade and Trying to Add the Margin Amount for handling the Liquidation , while executing the below code am getting the error  **response = exchange.fapiPrivate_post_positionmargin(
AttributeError: 'binance' object has no attribute 'fapiPrivate_post_positionmargin'** how to resolve this error. I know there is a API available at binance ""/fapi/v1/positionMargin" if i use the API directly with the support of requests it is working but when i use CCXT and the method fapiPrivate_post_positionmargin mentioned in documentation it is not working. Kindly advise

### Code

```
  import ccxt
import config
import requests
import time
import hashlib
import hmac
from urllib.parse import urlencode

api_key = config.BINANCE_FUTURE_API_KEY_TESTNET
secret_key = config.BINANCE_FUTURE_SECRET_KEY_TESTNET

print("CCXT Version:", ccxt.__version__)

exchange = ccxt.binance(
    {
        "apiKey": api_key,
        "secret": secret_key,
        "enableRateLimit": True,
        "options": {
            "defaultType": "future",
        },
    }
)

enable_sandbox_mode = True
exchange.set_sandbox_mode(enable_sandbox_mode)
symbol = "ETH/USDT"
side = "buy"  # or 'sell'
quantity = 1.0
price = None  # Use None for market orders
margin_amount = 1000.0  # Replace with your desired margin amount


# Executing BUY Trade
order = exchange.create_order(
    symbol,
    "market",
    "buy",
    quantity,
    params={"isIsolated": "TRUE"},
)
print(order)
# # for ISOLATED positions Adding Margin
print("Modifying your ISOLATED", symbol, "position margin:")
response = exchange.fapiPrivate_post_positionmargin(
    {
        "symbol": symbol,
        "amount": 1234.45,  # ←--------------  AMOUNT HERE
        "positionSide": "BOTH",  #  BOTH for One-way positions, LONG or SHORT for Hedge Mode
        "type": 1,  # 1 = add position margin, 2 = reduce position margin
    }
)
print(response)

```

**Comment by Sekharonline4u** [comment]
I have used the following link code: https://github.com/ccxt/ccxt/blob/master/examples/py/binance-futures-margin.py as reference

**Comment by ttodua** [comment]
I'll take a look into this soon

**Comment by ttodua** [comment]
what error did you get? please paste it,

**Comment by ttodua** [comment]
also, I advise you used native CCXT method for adding / removing margin with `exchange.add_margin ('ETH/USDT:USDT', 1.2345);`. similarly, ccxt has `.remove_margin` method.

let us know if that does not solve your issue.

**Comment by Sekharonline4u** [comment]
Thanks for your Update and quick response, will work on that and will update the status 
- Sekhar
