### ISSUE TITLE
Incorrect Volume in Futures (at least gate.io and okx)

### ISSUE THREAD

**Issue by dnuno89** [ccxt/ccxt#18941]
### Operating System

Windows 11

### Programming Languages

Python

### CCXT Version

3.1.44

### Description

When fetching futures candle data, the volume is not in quote currency units. It seems to me that it is defined in number of contracts, but I don't see how to get the value of each contract. Furthermore, the doc string for fetch_ohlcv() says: :returns [[int]]: A list of candles ordered, open, high, low, close, _volume(units in quote currency)_

See captures for 1 day candles for ADA at gate.io, the volume for August 17 is 15 M vs 1.5 M.

![image](https://github.com/ccxt/ccxt/assets/11979371/7f10c516-2b42-4823-99eb-732ae582d098)
![image](https://github.com/ccxt/ccxt/assets/11979371/8704d15e-6127-4bb2-a8ab-85873d9795fb)

### Code
```
import plotly.express as px
import ccxt
import pandas as pd
import numpy as np
import time

pairs = ['ADA/USDT:USDT', 'LTC/USDT:USDT']
exchange = ccxt.gateio()

# Set start and end times for data
start_time = exchange.parse8601('2023-08-01T00:00:00Z')
end_time = exchange.parse8601('2023-08-15T01:00:00Z')
timeframe = '1d' # 1 day candlesticks
limit = 120 # maximum number of candlesticks per request

mkts = exchange.load_markets()

for pair in pairs:
    df = pd.DataFrame()
    # Keep track of the last timestamp downloaded
    last_timestamp = start_time
    print(pd.to_datetime(last_timestamp, unit='ms'))
    
    # Keep downloading data until we have all data from start_time to end_time
    while last_timestamp < end_time:
        # Download OHLCV data for current timeframe and limit
        ohlcv = exchange.fetch_ohlcv(pair, timeframe, since=last_timestamp, limit=limit)
        ohlcv_df = pd.DataFrame(ohlcv, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
        df = pd.concat([df, ohlcv_df], axis=0)
        tickers = exchange.fetch_ticker(pair)
        print(tickers)
        # Set the last timestamp to the end of the last downloaded candlestick
        last_timestamp = int(ohlcv[-1][0]) + 1
        first_date = np.min(ohlcv_df['timestamp'])
        print(pd.to_datetime(first_date, unit='ms'))
        # Pause for a short time to avoid rate limiting
        
        time.sleep(1)
        
    # Convert timestamp to datetime format
    df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
    px.line(df, x='timestamp', y='close', title=pair).show()


    px.line(df, x='timestamp', y='volume', title=pair).show()
```

**Comment by carlosmiei** [comment]
Hello @dnuno89,

Unfortunately I don't think that the documentation for that particular method is correct, usually, the Volume in the OHLCV data refers to the base currency, not the quote one. 

If you need

**Comment by carlosmiei** [comment]
@dnuno89 when dealing with futures you're always handling contracts, so in this case you can consider it number of contracts (sorry if I was not explicit about it)

**Comment by dnuno89** [comment]
Is there any way to obtain the value of each contract? Thanks

**Comment by carlosmiei** [comment]
@dnuno89 You mean the contract size, right? In that case yes, of course, that information is stored inside the market object.
Example:
```Python
await exchange.loadMarkets()
symbol = 'BTC/USDT:USDT'
market = exchange.market(symbol)
print(market['contractSize']
```

**Comment by dnuno89** [comment]
Thanks for the explanation.
