### ISSUE TITLE
OKX (CCXT Pro) watch_ohlvc no data received

### ISSUE THREAD

**Issue by turbochoo** [ccxt/ccxt#18955]
### Operating System

Manjaro Linux x86_64

### Programming Languages

Python

### CCXT Version

4.0.68

### Description

didn't recievied any data from  perpetual BTC-USDT-SWAP symbol , in 1m dateframe.

### Code

```
import ccxt.pro as ccxt
from app.settings import settings
import asyncio
cfg = {
    "apiKey": settings.OKX_KEY,
    "secret": settings.OKX_SECRET,
    "password": settings.OKX_PASSPHRASE,
    "enableRateLimit": True,
    "options": {
    "defaultType": "swap",
    },
}
exchange = ccxt.okx(cfg)
exchange.streaming["keepAlive"] = 10000
symbol="BTC-USDT-SWAP"
print("xxx")
async def ws_monitor():
    while True:
        ohlcv = await exchange.watch_ohlcv(symbol)
        print(ohlcv)

if __name__ == '__main__':
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    try:
        asyncio.run(ws_monitor())
    except KeyboardInterrupt:
        pass


```

**Comment by turbochoo** [comment]
this code need a little change : from self.exchange to exchange  :)

**Comment by turbochoo** [comment]
while True:
    ohlcv = await exchange.watch_ohlcv(symbol)
    print(ohlcv)

**Comment by turbochoo** [comment]
full test code:
import ccxt.pro as ccxt
from app.settings import settings
import asyncio
cfg = {
    "apiKey": settings.OKX_KEY,
    "secret": settings.OKX_SECRET,
    "password": settings.OKX_PASSPHRASE,
    "enableRateLimit": True,
    "options": {
    "defaultType": "swap",
    },
}
exchange = ccxt.okx(cfg)
exchange.streaming["keepAlive"] = 10000
symbol="BTC-USDT-SWAP"
print("xxx")
async def ws_monitor():
    while True:
        ohlcv = await exchange.watch_ohlcv(symbol)
        print(ohlcv)

if __name__ == '__main__':
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    try:
        asyncio.run(ws_monitor())
    except KeyboardInterrupt:
        pass

**Comment by carlosmiei** [comment]
Hello @turbochoo, thanks for letting us know,  will take a look and revert asap

**Comment by turbochoo** [comment]
> Hello @turbochoo, thanks for letting us know, will take a look and revert asap

thanks , i set verbose: True in config , show me the error message :
 {"event":"error","msg":"This channel has been migrated to the '/business' URL. Please subscribe using the new URL. More details can refer to: https://www.okx.com/help-center/changes-to-v5-api-websocket-subscription-parameter-and-url","code":"64001"}
