### ISSUE TITLE
error conecting to bingx code:100204

### ISSUE THREAD

**Issue by simons1010** [ccxt/ccxt#18958]
### Operating System

windows

### Programming Languages

Python

### CCXT Version

4.08

### Description

Hi

I am using freqtrade as a trading bot that uses ccxt and bingx as exchange but I see this error on the console when running the bot :

freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair BTC/USDT due to ExchangeError. Message: bingx {"code":100204,"msg":"","timestamp":1692542166362}". Retrying still for 4 times.

I am not a technical person and I need to know if this problem is from your side or exchange. 

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @simons1010, 
Can you pinpoint the exact ccxt call freqtrade is doing here?
