### ISSUE TITLE
BingX fetch_trades() wrong API response parsing for 'side' and 'takerOrMaker'

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#18959]
### Operating System

Linux Mint

### Programming Languages

Python

### CCXT Version

4.0.69

### Description

This is basically a duplicate of issue #18827. I'm making a new issue here because the previous one was closed before the main bug was fixed.

The problem is that `fetch_trades` (or `parse_trade` to be more specific) assumes that 'buyerMaker' and 'isBuyerMaker' boolean in the BingX API response contains information whether the trade was made by 'maker' or 'taker' and assigns value for 'takerOrMaker' in the ccxt dictionary. The actual information is instead the **side** of the trade - `True` refers to 'buy' side maker trade and `False` refers to 'sell' side maker trade.

I justify these claims with the following:

1. In BingX API documentation (https://bingx-api.github.io/docs/#/spot/market-api.html#Query%20transaction%20records) "Field Description" for 'isBuyerMaker' is "Buyer or not".
2. I asked this from their support:
> Hi,
> 
> I have a technical question related to the BingX spot API:
> 
> In the spot API there is an endpoint called "/openApi/spot/v1/market/trades". In the API response there is a field called "isBuyerMaker". Does this field contain information about the side of the trade (buy/sell) OR if it is a taker/maker trade? What does it mean if this value is true, and what does it mean if the value is false?
> 
> And also, is it the same answer for the swap API?

And their answer was this:

> Hi ,
> if the value of isBuyerMaker field is false?  => sell

My additional wish is that, if possible, the trades were flipped to have a 'taker' side in the ccxt dictionary. In the other words: 
1. When 'buyerMaker'/'isBuyerMaker' has value `True` the 'side' would be `sell` and the 'takerOrMaker' would be `taker`.
2. When 'buyerMaker'/'isBuyerMaker' has value `False` the 'side' would be `buy` and the 'takerOrMaker' would be `taker`.

In my opinion, this is more intuitive instead of 'side' always having value 'maker'.

### Code

```
exchange = ccxt.bingx()
print(exchange.fetch_trades('BTC/USDT'))
```
```
[{'id': '58893690', 'info': {'id': '58893690', 'price': '26000.00', 'qty': '0.00192', 'time': '1692544114512', 'buyerMaker': True}, 'timestamp': 1692544114512, 'datetime': '2023-08-20T15:08:34.512Z', 'symbol': 'BTC/USDT', 'order': None, 'type': None, 'side': None, 'takerOrMaker': 'maker', 'price': 26000.0, 'amount': 0.00192, 'cost': 49.92, 'fee': {'cost': None, 'currency': None, 'rate': None}, 'fees': [{'cost': None, 'currency': None, 'rate': None}]}, ...
```

**Comment by ttodua** [comment]
thanks for the report!
submitted a PR to fix this. Note, that ccxt has uniform approach to this, as `takerOrMaker` is always `taker` with public trades, whereas `side` parameter tells which one was taker (buyer or seller). so you can always easily determine which one was taker/maker by that information

**Comment by ttodua** [comment]
oops, my bad, on the fly I forgot to reverse it, thanks!

**Comment by ttodua** [comment]
uodated, now ready.
and yes about your concern - if you find any cases  where for public trades there is 'maker' set, open an issue again. thanks for the reports

**Comment by JovianMoon** [comment]
Thank you for the fix, looking good now! I will try to make a report at some point about the problems in the public trades in different exchanges. I think there might also be some other problems lurking there...
