### ISSUE TITLE
Bybit withdraw throws an error of InsufficientFunds

### ISSUE THREAD

**Issue by AntonDe** [ccxt/ccxt#18998]
### Operating System

MacOS

### Programming Languages

Python

### CCXT Version

4.0.29

### Description

Hi there,

I'm trying to withdraw from Bybit to another Exchange (by the way: the API is set correctly, I'm able to trade), and there are also enough coins in the spot account, which I want to send. I also check the Bybit docs and the spot account, where my coins are located, is the default account, from which the withdraw is done, so there is no need to transfer the funds.

When running the code, I get the following error:
type = InsufficientFunds 
error = bybit {"retCode":131001,"retMsg":"Account available balance insufficient","result":{},"retExtInfo":{},"time":1692973194412}

Thanks

### Code

```
withdrawStatus = await bybitEx.withdraw('PEPE', sendAmount, otherExchangeAddress, params={
    'chain': networkName
})
 

```

**Comment by carlosmiei** [comment]
Hello @AntonDe, you're right the default account is the spot one. Are you sure that you're taking into consideration the fee of the tx as well? 

Also can you pls double-check your spot-balance by doing `balance = await bybit.fetch_balance({'type':'spot'})` ?

**Comment by AntonDe** [comment]
Hi @carlosmiei, I has check everything, but it seems that the error is on the Bybit side, because, just after I postet the question, I was not able to create an order, the code crashes with the same reason. Altough previously I was able to create order.

Thank you
