### ISSUE TITLE
binance fetchPositions() error - ccxt.base.errors.ExchangeError: binance {"code":-5000,"msg":"GET /fapi/v1/positionRisk is retired, please use GET /fapi/v2/positionRisk"}

### ISSUE THREAD

**Issue by frcd10** [ccxt/ccxt#18997]
### Operating System

windows

### Programming Languages

Python

### Description

ccxt.base.errors.ExchangeError: binance {"code":-5000,"msg":"GET /fapi/v1/positionRisk is retired, please use GET /fapi/v2/positionRisk"}

New endpoint for this

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @frcd10,

Binance deprecated the v1 endpoint but if you update your ccxt version it will fix the issue because we're already using v2 there.

relates to https://github.com/ccxt/ccxt/issues/18853

**Comment by frcd10** [comment]
thanks, it worked.
