### ISSUE TITLE
_static_dependencies_qs_index_cjs__WEBPACK_IMPORTED_MODULE_2__.stringify is not a function

### ISSUE THREAD

**Issue by bohdan-krupa** [ccxt/ccxt#19025]
### Operating System

MacOS Ventura

### Programming Languages

JavaScript

### CCXT Version

4.0.77

### When we use ccxt inside a React app and use any method that makes a request under the hood it fails with:

_static_dependencies_qs_index_cjs__WEBPACK_IMPORTED_MODULE_2__.stringify is not a function

<img width="1517" alt="Screenshot 2023-08-28 at 15 49 05" src="https://github.com/ccxt/ccxt/assets/29518768/c55101ff-0284-41f0-be94-b2f0de3f7880">

**Comment by carlosmiei** [comment]
Hello @maksym-trushevych, are you using the browserified version?

**Comment by maksym-trushevych** [comment]
> Hello @maksym-trushevych, are you using the browserified version?

Hello @carlosmiei , currently - yes. With the browserified version, there are no issues. However, I would like to use the ESM version for React SPA.

**Comment by carlosmiei** [comment]
@maksym-trushevych is there a way to share with me MRE (Minimal reproducible example)? Ideally something very simple to test and run.

**Comment by web3ToolBoxDev** [comment]
I caught into same issue,when use ccxt in react
<img width="603" alt="image" src="https://github.com/user-attachments/assets/5bd479de-4c67-4f03-8fc2-9eaf8cc97409">
<img width="622" alt="image" src="https://github.com/user-attachments/assets/00fc96ab-48c2-4b45-ab78-47733db44569">
