### ISSUE TITLE
Kucoin Symbol Does not Exist

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#19023]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

4.0.77

### Description

I am unable to change the margin for BTCUSDT, see code below to reproduce

### Code

```
client = ccxt.kucoinfutures({'apiKey': strategy.public,
                                      'secret': strategy.private,
                                      'password': password})

ticker = "BTC/USDT:USDT"
ticker = ticker.replace("/USDT:USDT", "USDTM")
client.futuresprivate_post_position_margin_auto_deposit_status(
    params={'symbol': ticker, 'status': True})
```
File ~\anaconda3\lib\site-packages\ccxt\base\types.py:26, in Entry.__init__.<locals>.unbound_method(_self, 
params)
     25 def unbound_method(_self, params={}):
---> 26     return _self.request(self.path, self.api, self.method, params, config=self.config)

File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:3019, in Exchange.request(self, path, api, method, params, headers, body, config)
   3018 def request(self, path, api: Any = 'public', method='GET', params={}, headers: Optional[Any] = None, body: Optional[Any] = None, config={}):
-> 3019     return self.fetch2(path, api, method, params, headers, body, config)

File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:3016, in Exchange.fetch2(self, path, api, method, 
params, headers, body, config)
   3014 self.lastRestRequestTimestamp = self.milliseconds()
   3015 request = self.sign(path, api, method, params, headers, body)
-> 3016 return self.fetch(request['url'], request['method'], request['headers'], request['body'])

File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:644, in Exchange.fetch(self, url, method, headers, body)
    641     else:
    642         raise ExchangeError(details) from e
--> 644 self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
    645 if json_response is not None:
    646     return json_response

File ~\anaconda3\lib\site-packages\ccxt\kucoin.py:3871, in kucoin.handle_errors(self, code, reason, url, method, headers, body, response, requestHeaders, requestBody)
   3869 self.throw_broadly_matched_exception(self.exceptions['broad'], body, feedback)
   3870 if errorCode != '200000':
-> 3871     raise ExchangeError(feedback)
   3872 return None

ExchangeError: kucoinfutures Contract symbol[BTCUSDTM] does not exist

**Comment by carlosmiei** [comment]
Hello @Tomas-MP, I think you're using the wrong exchange-specific market id, it should be `XBTUSDTM`

You can easily check it by doing
```Python
await ex.loadMarkets()
market = ex.market('BTC/USDT:USDT')
print(market['id'])
```

**Comment by Tomas-MP** [comment]
Works indeed, thank you!
