### ISSUE TITLE
Kucoin AttributeError when creating an order

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#19026]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

4.0.77

### Description

I am receiving an AttributeError when I try to place an order on Kucoin

### Code

```
  
client = ccxt.kucoinfutures({'apiKey': ''  'secret': '',  'password': ''})

response = client.create_order(symbol="BTC/USDT:USDT",  type="limit", side='buy', amount=1, price=26000,  params={'leverage': 10})

```
File ~\anaconda3\lib\site-packages\ccxt\kucoinfutures.py:1101, in kucoinfutures.create_order(self, symbol, type, side, amount, price, params)
   1092 preciseAmount = int(self.amount_to_precision(symbol, amount))
   1093 request = {
   1094     'clientOid': clientOrderId,
   1095     'side': side,
   (...)
   1099     'leverage': 1,
   1100 }
-> 1101 triggerPrice, stopLossPrice, takeProfitPrice = self.handleTriggerPrices(params)
   1102 params = self.omit(params, ['stopLossPrice', 'takeProfitPrice', 'triggerPrice', 'stopPrice'])  
   1103 if triggerPrice:

AttributeError: 'kucoinfutures' object has no attribute 'handleTriggerPrices'

**Comment by carlosmiei** [comment]
Hello @Tomas-MP, yeah same story regarding the dynamic props. 

Can you try to reproduce this issue using a simple python script? You can create a class and use `setattr` to check if dynamic props are working at all

```Python
class Student:
  marks = 88
  name = 'Sheeran'

person = Student()

# set value of name to Adam
setattr(person, 'name', 'Adam')
print(person.name)
```

**Comment by Tomas-MP** [comment]
@carlosmiei when I run the code above via a .bat script (see below), it seems to be working and it prints the name "Adam"

pushd %~dp0
call "C:\Users\Tomas\anaconda3\Scripts\activate.bat"
"C:\Users\Tomas\anaconda3\python.exe" "D:\test.py"
pause

Thus I am also not sure what is causing this issue. My other programs work in the same way (I call them via the .bat scripts similar to the code above).
