### ISSUE TITLE
Querying CCEX fetchBalance returns 'privateGetBalances is not a function'

### ISSUE THREAD

**Issue by dasilva333** [ccxt/ccxt#1903]
- OS: Windows 7
- Programming Language version: Ionic 3
- CCXT version: 1.10.1105
- Exchange:CCEX
- Method:fetchBalance

Looking at the functions available for that exchange it seems the auto generated function name differs from the expected name:

```
privateGetGetbalance
privateGetGetbalances
```

and line 109 of ccex.js:
`
let response = await this.privateGetBalances ();
`

Edit: Sidenote I'm upgrading from 1.10.909 and the problem is now there, not sure when the bug was introduced but it must be between 909 and 1105.

Thanks

**Comment by dasilva333** [comment]
I did a diff on Exchange.defineRestApi and found that the new one has this extra logic that might be affecting the way functions are named:
```
                    if (camelcaseSuffix.indexOf (camelcaseMethod) === 0)
                        camelcaseSuffix = camelcaseSuffix.slice (camelcaseMethod.length)

                    if (underscoreSuffix.indexOf (lowercaseMethod) === 0)
                        underscoreSuffix = underscoreSuffix.slice (lowercaseMethod.length)
```

**Comment by dasilva333** [comment]
@kroitor Still not working with the latest fix. Tried out ccxt 1.10.1115

I noticed you changed it from
`
let response = await this.privateGetBalances ();
`
to this:
`
let response = await this.privateGetbalances ();
`
But I still get this error:

`
TypeError: this.privateGetbalances is not a function
`

As I mentioned previously I looked through the generated function names that defineRestAPI creates for that exchange and neither of those function names are available, instead I see the following:

```
privateGetGetbalance
privateGetGetbalances
```

Let me know, thanks!

**Comment by kroitor** [comment]
It should work now in 1.10.1128. Thx again for your feedback!
