### ISSUE TITLE
Checking API Permissions

### ISSUE THREAD

**Issue by ahmedbodi** [ccxt/ccxt#1904]
- OS: Linux
- Programming Language version: PHP 7.0
- CCXT version: Master
- Exchange: All
- Method: N/A

Is there any way to check the permissions on the API Keys provided to the exchanges?

Thanks

**Comment by kroitor** [comment]
Not in the unified API yet, but the work on it has been started here: https://github.com/ccxt/ccxt/pull/1424. We hope to deliver it soon.

Let us know if this doesn't answer your question. Thx!
