### ISSUE TITLE
How do i get realized PNL on bitget trade history?

### ISSUE THREAD

**Issue by TYRANTHOSAURUS** [ccxt/ccxt#19055]
How do i get realized PNL?

When i do fetchTrades() i don't see realized PNL or profit anywhere. How do i access this? Am i using the wrong call? fetchMyTrades() only works for spot it seems? Its pretty like the most important stat for my app.

**Comment by sc0Vu** [comment]
HI @TYRANTHOSAURUS

You can use `fetchOrderTrades` to trades for swap, and there is `profit` in trades.

**Comment by TYRANTHOSAURUS** [comment]
Hi @sc0Vu , thanks for the reply!

Bur fetchOrderTrades returns: Uncaught (in promise) NotSupported: bitget `fetchOrders() `is not supported yet

I read another issue where it said this was added (which according to the bitget API documents can be used `privateMixGetPositionHistoryPosition()` https://github.com/ccxt/ccxt/pull/18651 however this also doesn't work.
source: https://bitgetlimited.github.io/apidoc/en/mix/#get-history-position

      const startDate = "2023-07-27T00:00:00Z";
            const startDateUnix = dayjs(startDate).unix();
            const endDate = "2023-08-27T00:00:00Z";
            const endDateUnix = dayjs(endDate).unix();

            const queryParams = {
                productType: "umcbl", // Not required according to bitget doc but gives error without on CCTX
                startTime: startDateUnix, 
                endTime: endDateUnix
            };

            const privateMixGetPositionHistoryPosition =
                await exchange.privateMixGetPositionHistoryPosition(queryParams);
            console.log("publicMixGetMarketFillsHistory", privateMixGetPositionHistoryPosition);

This returns (without SYMBOL which is not required):

`Uncaught (in promise) ExchangeError: bitget {"code":"40913","msg":"productType or symbol must be passed one","requestTime":1693469089928,"data":null}`

With SYMBOL "BTCUSDT_UMCBL" (empty data, which i'm sure has plenty of records):

```
handleRestResponse:
 bitget GET http://proxy.com/https://api.bitget.com/api/mix/v1/position/history-position?endTime=1693094400&productType=umcbl&startTime=1690416000&symbol=BTCUSDT_UMCBL 200 OK 
 
ResponseHeaders:
{
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Origin": "*",
  "Cache-Control": "no-cache, no-store, max-age=0, must-revalidate",
  "Cf-Cache-Status": "DYNAMIC",
  "Cf-Ray": "7ff3ce6baf5eb966-AMS",
  "Connection": "close",
  "Content-Encoding": "gzip",
  "Content-Type": "application/json",
  "Date": "Thu, 31 Aug 2023 08:12:04 GMT",
  "Expires": "0",
  "Pragma": "no-cache",
  "Requesttime": "1693469523937",
  "Server": "cloudflare",
  "Transfer-Encoding": "chunked",
  "Vary": "Accept-Encoding",
  "X-Content-Type-Options": "nosniff",
  "X-Final-Url": "https://api.bitget.com/api/mix/v1/position/history-position?endTime=1693094400&productType=umcbl&startTime=1690416000&symbol=BTCUSDT_UMCBL",
  "X-Frame-Options": "SAMEORIGIN",
  "X-Request-Id": "0c32902da0374d2aac5d71abf9e871c8",
  "X-Xss-Protection": "1; mode=block"
}

{
  "code": "00000",
  "msg": "success",
  "requestTime": "0",
  "data": {
    "list": [],
    "endId": null
  }
}
```

**Comment by sc0Vu** [comment]
Hi @TYRANTHOSAURUS 

You can use `fetchPositions`, we already integrate the api. And the product type should be uppercase (UMCBL).
