### ISSUE TITLE
Currencies from the KuCoin doesn't have networks

### ISSUE THREAD

**Issue by PovarovDenis** [ccxt/ccxt#19066]
### Operating System

macOS

### Programming Languages

JavaScript

### CCXT Version

4.0.78

### Description

When you're fetching currencies from kucoin `kucoin.fetchCurrencies()`, all the currencies doesn't have networks in the currency object. I've set `verbose: true` for the kucoin exchange and that is what I see in logs:

```
handleRestResponse:
 kucoin GET https://kucoin.com/_api/currency/currency/chain-info 403 Forbidden
ResponseHeaders:
 {
  Connection: 'keep-alive',
  'Content-Length': '150',
  'Content-Type': 'text/html; charset=UTF-8',
  Date: 'Thu, 31 Aug 2023 13:06:07 GMT',
  Server: '-',
  'Set-Cookie': 'AWSALB=QjW5meT9GCDo2/GwdyopfKoq/smKYoirx0jrKfWeup3K5Gw9rf/vQkAHE9QeHm5hZE+bNC1tvuy56dxmLz7CPFUKy60SBMRhEDaX5wSBuT5y2ValO4DcbFYvwa7k; Expires=Thu, 07 Sep 2023 13:06:07 GMT; Path=/, AWSALBCORS=QjW5meT9GCDo2/GwdyopfKoq/smKYoirx0jrKfWeup3K5Gw9rf/vQkAHE9QeHm5hZE+bNC1tvuy56dxmLz7CPFUKy60SBMRhEDaX5wSBuT5y2ValO4DcbFYvwa7k; Expires=Thu, 07 Sep 2023 13:06:07 GMT; Path=/; SameSite=None; Secure',
  Via: '1.1 4744809b984725c3d153dad79250fce4.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'vpZVQFRTd5ao5DQHACz5sMgqc7xSpw5pBP3W9_EArsBLOWz7TxZJtQ==',
  'X-Amz-Cf-Pop': 'OTP50-C1',
  'X-Cache': 'Error from cloudfront'
}
ResponseBody:
 <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

More of that I've checked the kucoin API docs and they don't have this API endpoint at all: `GET https://kucoin.com/_api/currency/currency/chain-info`

**Comment by carlosmiei** [comment]
Hello @PovarovDenis, until now, kucoin did not have a public endpoint to fetch all the currencies+networks, so we were using an internal API, and for some reason, it responds with a 403 error sometimes. 

You can retry by doing `await exchange.loadMarkets(True)`. 

Fortunately, Kucoin just announced that they introduced a new endpoint capable of replacing that internal API call, so we will integrate it as soon as possible, and that problem should be fixed.
