### ISSUE TITLE
binance spot trailing stop order

### ISSUE THREAD

**Issue by martenzo7** [ccxt/ccxt#19065]
### Operating System

linux

### Programming Languages

Python

### CCXT Version

4.0.34

### Description

Hi, I'm trying to set a trailing stop order on binance spot using this code:
```
from pprint import pprint
import ccxt

def ACTION():
    key=KEY
    secret=SECRET_KEY
    print('CCXT version:', ccxt.__version__)
    exchange = ccxt.binance({
        'enableRateLimit': True,
        'apiKey': key,
        'secret': secret,
    })
    exchange.set_sandbox_mode(True)
    markets = exchange.load_markets()
    symbol = 'BTC/USDT'
    side = 'sell'
    amount = 0.001
    order_type = 'TRAILING_STOP_MARKET'
    rate = '0.2'
    price = None
    params = {
        'stopPrice': 17200,
        'callbackRate': rate
    }
    order = exchange.create_order(symbol, order_type, side, amount, price, params)
    pprint(order)
ACTION()
```   
and I keep getting this error

```
ccxt.base.errors.InvalidOrder: binance TRAILING_STOP_MARKET is not a valid order type for the BTC/USDT market
```

NOTE: I'm using this function on a testnet account

**Comment by Dan-krm** [comment]
@martenzo7 TRAILING_STOP_MARKET is not a valid order type for spot markets, you can however set the order_type to STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT, or TAKE_PROFIT_LIMIT then set the `trailingDelta` parameter the same way you would set the callbackRate to create a trailing stop order for spot markets.

https://github.com/binance/binance-spot-api-docs/blob/master/faqs/trailing-stop-faq.md
https://binance-docs.github.io/apidocs/spot/en/#new-order-trade

**Comment by sainiankit** [comment]
@Dan-krm 
>RAILING_STOP_MARKET is not a valid order type for spot markets, you can however set the order_type to STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT, or TAKE_PROFIT_LIMIT then set the trailingDelta parameter the same way you would set the callbackRate to create a trailing stop order for spot markets.

Is this specific to Binance ? Or should work for most exchanges ? 

The documentation mentions somethig like mentioned below, but does not work for Binance.
```
symbol = 'BTC/USDT:USDT'
type = 'market'
side = 'sell'
amount = 1.0
price = None
params = {
    'trailingPercent': 1.0, # percentage away from the current market price 1.0 is equal to 1%
    # 'trailingAmount': 100.0, # quote amount away from the current market price
    # 'trailingTriggerPrice': 44500.0, # the price to trigger activating a trailing stop order
    # 'reduceOnly': True, # set to True if you want to close a position, set to False if you want to open a new position
}
order = exchange.create_order (symbol, type, side, amount, price, params)
```

**Comment by Dan-krm** [comment]
@sainiankit that example was specific for binance spot markets. I've opened a pull request that should make spot trailingPercent orders on binance a bit more unified and user friendly if it gets merged: https://github.com/ccxt/ccxt/pull/22414

The documentation example should work as expected for binance swap markets using the binanceusdm class
