### ISSUE TITLE
No response/error from exchange on create_order just hangs

### ISSUE THREAD

**Issue by kkairu** [ccxt/ccxt#19079]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.0.80

### Description

create_order() just pauses with not response/error/warning from exchange. This happens when invokes from webpage but from within the script it works fine 

It's a multi-threaded flask app with threads for tickers, balance and ohlcv. Everything else continues running ok but the order hangs...

### Code

```
  

```

async def open_position(_coin, _ticker, _amount, _side):
    
    global POSITIONS, BALANCES

    try:

        _last_price = PRICES.loc[PRICES['ticker'] == _ticker, 'price'].iloc[0]

        _decimal_value = decimal.Decimal(str(_last_price))
        _precision = -_decimal_value.as_tuple().exponent

        _qty = await get_trade_volume(_ticker, _last_price, _amount)

        #print(f'{_ticker} {_side} {_qty}')
            
        # Check if open positions risk is > max exposure for whole account

        _position_risk = BALANCES.iloc[-1]['position_risk']
        _max_exposure = BALANCES.iloc[-1]['max_exposure']

        if _position_risk < _max_exposure :

            try:
                _stoploss = OHLCV.loc[(slice(None), _coin), 'short_SL'].iloc[-1] if _side == 'sell' else OHLCV.loc[(slice(None), _coin), 'long_SL'].iloc[-1]
            
            except KeyError:
                _stoploss = None

            except Exception as e:
        
                print(f'[ERROR]: open_position _stoploss | {type(e).__name__}, {str(e)}')

            
            if _stoploss is not None and float(_qty) > 0 :

                if (_side == 'sell' and _last_price < _stoploss) or (_side == 'buy' and _last_price > _stoploss):

                    if TEST_MODE:
                        _open = await test_open_position(_ticker, _last_price, 'market', _side, _qty, None)
                    else:

                        try:

                            print(f'CREATE ORDER | {_ticker} - {_side} - {_qty}')
                            _open = await exchange.create_order(_ticker, 'market', _side, _qty, None)

                            print(_open)

                        except Exception as e:
        
                            print(f'[ERROR]: create_order | {type(e).__name__}, {str(e)}')

                    
                    _position_id = _open['id']
                    _status = 'O' #Open
                    _trade_type = 'LONG' if _side == 'buy' else 'SHORT'
                    _cost = _open['cost']/DEFAULT_LEVERAGE
                    
                    print(f'open_position ID = {_position_id}')
          
                    _position = {'position_id': _position_id, 'coin': _coin,'ticker':_ticker,
                                 'start_datetime':datetime.now(),'end_datetime':None,'side':_open['side'],'trade_type': _trade_type,
                                 'leverage':DEFAULT_LEVERAGE, 'qty': _open['amount'],'cost':_cost,
                                 'open_price':_open['average'],'close_price':None,'stoploss': round(_stoploss,_precision),
                                 'profitloss':0.00,'profitamt':0.00,'fees':None,
                                 'status': _status
                                }
                
                    #pprint(_position)

                    #with positions_lock:

                    # populate positions df
                    POSITIONS = POSITIONS.append(_position, ignore_index=True)

                    #print(f'open_position POSITIONS updated')

                    # Update balances

                    try:

                        with balances_lock:

                            _totalCrossWalletBalance = BALANCES['totalCrossWalletBalance'].iloc[0]
                            _availableBalance = BALANCES['availableBalance'].iloc[0] - _cost
                            _totalPositionInitialMargin = BALANCES['totalPositionInitialMargin'].iloc[0] + _cost
                            _totalCrossUnPnl = BALANCES['totalCrossUnPnl'].iloc[0]
                            _amount_per_trade = BALANCES['amount_per_trade'].iloc[0]
                            
                            _position_risk = round((_totalPositionInitialMargin / _totalCrossWalletBalance), 2) if _totalPositionInitialMargin > 0 else 0

                            #BALANCES['totalCrossWalletBalance'] = _totalCrossWalletBalance
                            BALANCES['availableBalance'] = _availableBalance
                            BALANCES['totalPositionInitialMargin'] = _totalPositionInitialMargin
                            #BALANCES['totalCrossUnPnl'] = _totalCrossUnPnl
                            #BALANCES['amount_per_trade'] = _amount_per_trade
                            BALANCES['position_risk'] = _position_risk
                            #BALANCES['max_exposure'] = MAX_EXPOSURE
                            
                            print(f'open_position UPDATED BAL = {_totalCrossWalletBalance} | {_availableBalance} | {_totalPositionInitialMargin} | {_totalCrossUnPnl} | {_amount_per_trade} | {_position_risk}')
                

                    except Exception as e:
                
                        print(f'[ERROR]: open_position balance update | {type(e).__name__}, {str(e)}')

                else:
                    print(f'[ERROR]: {_coin} {_side} | _last_price {_last_price} beyond _stoploss {_stoploss} ')

            else:
                print(f'[ERROR]: {_coin} {_side} | _stoploss NOT defined! or _qty is < 0 ')

        else:

            print(f'[ERROR]: Open position risk [ {_position_risk} ] > Max exposure [ {_max_exposure} ]')

        
    except Exception as e:
        
        print(f'[ERROR]: open_position | {type(e).__name__}, {str(e)}')
        

    await exchange.close()

**Comment by carlosmiei** [comment]
Hello @kkairu,

There's a lot of unrelated code in your snippet, so it's hard to debug. 
Can you please provide a MRE (minimum reproducible example), exchange used  and a verbose log `exchange.verbose=True`?

**Comment by kkairu** [comment]
That's the whole function where create_order() is called from... 

Even with verbose no output past the print output just before the create_order...

![image](https://github.com/ccxt/ccxt/assets/8553049/11bd5130-a0e8-49d1-af6c-a6acb0b9b089)

**Comment by carlosmiei** [comment]
@kkairu Sorry but this is impossible to debug it because you still haven't posted the complete verbose log (text-format) with the `createOrder` part.

**Comment by kkairu** [comment]
It's ok managed to fix issue was thread lock switched to async lock which was just causing the code to hang.

Also changed from flask to Quart that supports async routes better and to await form from frontend. and sever from waitress to hypercorn.
