### ISSUE TITLE
Problem when creating an order 

### ISSUE THREAD

**Issue by johnnychancf** [ccxt/ccxt#19082]
### Operating System

mac

### Programming Languages

Python

### CCXT Version

2.1.102

### Description

when i try to make this order using the below code.I

### Code

```
import ccxt
import time
import pandas as pd
import numpy as np
import datetime
from pprint import pprint

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

exchange = ccxt.bybit({
    'apiKey': 'APIKEY',
    'secret': 'SECRET',    
})

markets = exchange.load_markets()
symbol = 'BTCUSDT'
market = exchange.market(symbol)


def trade(signal):
    positions = exchange.fetch_positions([symbol])
    long = 0
    short = 0
    max_pos = 0.005

    for position in positions:
        side = position['side']  # 'Buy' for long, 'Sell' for short
        size = float(position['info']['size'])  # Access 'size' from 'info' dictionary
        
        if side == 'long':
            long += size
        elif side == 'short':
            short += size
        net_pos = long - short
        target_pos = max_pos *  df['pos'].iloc[-1]
        bet_size = round((target_pos) - (net_pos),3)
        
        
    # ### trade ###
        if target_pos > net_pos:
            if bet_size == 0:
                print('long ed')
                order = exchange.create_order('BTCUSDT', 'market', 'buy', max_pos, None)
                pprint(order)
            elif net_pos < bet_size:
                print('long ed')
                order = exchange.create_order('BTCUSDT', 'market', 'buy', max_pos, None)
                pprint(order)

        if target_pos < net_pos:
            if bet_size == 0:
                print('sell ed')
                order = exchange.create_order('BTCUSDT', 'market', 'sell', max_pos, None, params={'reduce_only': True})
                pprint(order)
            elif net_pos > bet_size:
                print('sell ed')
                order = exchange.create_order('BTCUSDT', 'market', 'sell', max_pos, None, params={'reduce_only': True})
                pprint(order)

    
    time.sleep(1)

    ### get account info after trade ###

    positions = exchange.fetch_positions([symbol])
    long = 0
    short = 0
    for position in positions:
        
        side = position['side']  # 'Buy' for long, 'Sell' for short
        size = float(position['info']['size'])  # Access 'size' from 'info' dictionary
        
        if side == 'long':
            long += size
        elif side == 'short':
            short += size
    net_pos = long - short
    target_pos = max_pos *  df['pos'].iloc[-1]
    print('after signal')
    print('current_long', long)
    print('current_short', short)
    print('nav', datetime.datetime.now(), exchange.fetch_balance()['USDT']['total'])


  

# ### define variables ###
pos = 0 # max amount of btc

while True:

    if datetime.datetime.now().second == 5:

        df = pd.read_csv(r'/Users/johnny/Desktop/Testing new/signal.csv')

        signal = df['pos'].iloc[-1] ### read the last row
        print('signal', signal)

        trade(pos)

        time.sleep(1)


```
the error returned:

```
Traceback (most recent call last):
  File "/Users/johnny/Desktop/Testing new/production1111.py", line 111, in <module>
    trade(pos)
  File "/Users/johnny/Desktop/Testing new/production1111.py", line 60, in trade
    order = exchange.create_order('BTCUSDT', 'market', 'sell', max_pos, None, params={'reduce_only': True})
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/bybit.py", line 2989, in create_order
    return self.create_contract_order(symbol, type, side, amount, price, params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/bybit.py", line 3246, in create_contract_order
    response = getattr(self, method)(self.extend(request, params))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 2637, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 2634, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 662, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/bybit.py", line 5650, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: bybit {"ret_code":130001,"ret_msg":"position idx not match position mode","result":{},"ext_code":"","ext_info":"","time_now":"1693603565.743817","rate_limit_status":98,"rate_limit":100,"rate_limit_reset_ms":1693603565741}
```

**Comment by Dan-krm** [comment]
You should try to use the unified naming conventions:
https://docs.ccxt.com/#/README?id=contract-naming-conventions
`BTC/USDT` for spot

Also in your params you should use `reduceOnly` instead of `reduce_only`
reduceOnly is the unified param name and reduce_only with the underscore isn't supported on bybit

Your error: "position idx not match position mode" can be resolved by setting the `positionIdx` parameter
Your positionIdx needs to match the position mode that can be set through the website or using setPositionMode ()
for example: params={'positionIdx': 1}
https://bybit-exchange.github.io/docs/v5/order/create-order

**Comment by carlosmiei** [comment]
Hello @johnnychancf,
First, I suggest upgrading your CCXT version because yours is pretty outdated.

>  {"ret_code":130001,"ret_msg":"position idx not match position mode","result":{},"ext_code":"","ext_info":"","time_now":"1693603565.743817","rate_limit_status":98,"rate_limit":100,"rate_limit_reset_ms":1693603565741}

Regarding this error, sometimes, to submit a derivatives order you need to specify your position side inside `params`, example:
```Python
params = {
'position_idx': 0 // 0 One-Way Mode, 1 Buy-side, 2 Sell-side
}
order = self.exchange.create_order(symbol, 'market', side, amount, None, params)
```

**Comment by johnnychancf** [comment]
I have updated my code with params to the below.
`     if target_pos > net_pos:
            if bet_size == 0:
                print('long ed')
                order = exchange.create_order('BTCUSDT', 'market', 'buy', max_pos, None,params={'positionIdx': 0})
                pprint(order)
            elif net_pos < bet_size:
                print('long ed')
                order = exchange.create_order('BTCUSDT', 'market', 'buy', max_pos, None,params={'positionIdx': 1})
                pprint(order)

        if target_pos < net_pos:
            if bet_size == 0:
                print('sell ed')
                order = exchange.create_order('BTCUSDT', 'market', 'sell', max_pos, None, params={'reduceOnly': True,'positionIdx': 0})
                pprint(order)
            elif net_pos > bet_size:
                print('sell ed')
                order = exchange.create_order('BTCUSDT', 'market', 'sell', max_pos, None, params={'reduceOnly': True,'positionIdx': 2})
                pprint(order)`
                
                
                
                However, it's still having the below message 

                  File "/Users/johnny/Desktop/Testing new/production1111.py", line 111, in <module>
    trade(pos)
  File "/Users/johnny/Desktop/Testing new/production1111.py", line 59, in trade
    order = exchange.create_order('BTCUSDT', 'market', 'sell', max_pos, None, params={'reduceOnly': True,'positionIdx': 2})
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/bybit.py", line 3691, in create_order
    return self.create_contract_v3_order(symbol, type, side, amount, price, params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/bybit.py", line 4066, in create_contract_v3_order
    response = self.privatePostContractV3PrivateOrderCreate(self.extend(request, params))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 3019, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 3016, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 644, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/bybit.py", line 8648, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 3382, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: bybit {"retCode":10001,"retMsg":"position idx not match position mode","result":{},"retExtInfo":{},"time":1693736945914}
johnny@Johnny---MBP Testing new %

**Comment by johnnychancf** [comment]
File "/Users/johnny/Desktop/Testing new/production1111.py", line 111, in <module>
    trade(pos)
  File "/Users/johnny/Desktop/Testing new/production1111.py", line 59, in trade
    order = exchange.create_order('BTCUSDT', 'market', 'sell', max_pos, None, params={'reduceOnly': True,'positionIdx': 2})
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/bybit.py", line 3691, in create_order
    return self.create_contract_v3_order(symbol, type, side, amount, price, params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/bybit.py", line 4066, in create_contract_v3_order
    response = self.privatePostContractV3PrivateOrderCreate(self.extend(request, params))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 3019, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 3016, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 644, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/bybit.py", line 8648, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ccxt/base/exchange.py", line 3382, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: bybit {"retCode":10001,"retMsg":"position idx not match position mode","result":{},"retExtInfo":{},"time":1693736945914}
johnny@Johnny---MBP Testing new %

**Comment by carlosmiei** [comment]
@johnnychancf can you try with the snake_case version instead? `position_idx` ?

**Comment by germangar** [comment]
Is this spot or swap? I'm not sure what'd the default for bybit, but the code isn't setting it to anything in particular.

**Comment by carlosmiei** [comment]
> Is this spot or swap? I'm not sure what'd the default for bybit, but the code isn't setting it to anything in particular.

@germangar that error is swap only. Btw you would not need to worry about the default type if you were using unified symbols (BTC/USDT:USDT)  instead of the bybit-specific ones (BTCUSDT)

**Comment by johnnychancf** [comment]
My calculation may have gone wrong. 
I have also tried to add leverage as a parameter to my trade. so here is thecode .


`markets = exchange.load_markets()
symbol = 'BTCUSDT'
market = exchange.market(symbol)


def trade(signal):
    positions = exchange.fetch_positions([symbol])
    long = 0
    short = 0
    max_pos = 0.03

    for position in positions:
        side = position['side']  # 'Buy' for long, 'Sell' for short
        size = float(position['info']['size'])  # Access 'size' from 'info' dictionary
        
        if side == 'long':
            long += size
        elif side == 'short':
            short += size
        net_pos = long - short
        target_pos = max_pos *  df['pos'].iloc[-1]
        bet_size = round((target_pos) - (net_pos),3)
        
        
        
    # ### trade ###
        if target_pos > net_pos:
            if bet_size == 0:
                print('long ed')
                params = {'position_idx': 0, 'leverage': 10}
                order = exchange.create_order('BTCUSDT', 'market', 'buy', max_pos, None,params)
                pprint(order)
            elif net_pos < bet_size:
                print('long ed')
                params = {'position_idx': 0 ,'leverage': 10}
                order = exchange.create_order('BTCUSDT', 'market', 'buy', max_pos, None,params)
                pprint(order)

        if target_pos < net_pos:
            if bet_size == 0:
                print('sell ed')
                params = {'positionIdx': 0 , 'leverage': 10}
                order = exchange.create_order('BTCUSDT', 'market', 'sell', max_pos, None, params)
                pprint(order)
            elif net_pos > bet_size:
                print('sell ed')
                params={'reduceOnly': True,'positionIdx': 0,'leverage': 10}
                order = exchange.create_order('BTCUSDT', 'market', 'sell', max_pos, None, params)
                pprint(order)

`




then here is my error message now.


ccxt.base.errors.InvalidOrder: bybit {"retCode":140017,"retMsg":"current position is zero, cannot fix reduce-only order qty","result":{},"retExtInfo":{},"time":1693904466357}

**Comment by johnnychancf** [comment]
What i wanted to do is a long short position. 

the signal comes with 1, 0 , -1


When I am in a close position and the signal comes at -1 and 1 it should either buy or sell.

When I am on short position. when the signal is on 1 , It should buy then it changed to close position and then long 

Etc...


Can anyone tell me if I have done my calculation wrong or is there a easier way to do it with leverage as we??



thank you all

**Comment by johnnychancf** [comment]
I am not sure if I should put my bet price that is already with leverage or should I put a small number of bets then the 'leverage': 10 will help me x10 with my bet price or should I put in the bet price that is already x10?


for now I have placed the bet price that is already x10

`markets = exchange.load_markets()
symbol = 'BTC/USDT:USDT'
market = exchange.market(symbol)


def trade(signal):
    positions = exchange.fetch_positions([symbol])
    long = 0
    short = 0
    max_pos = 0.301

    for position in positions:
        side = position['side']  # 'Buy' for long, 'Sell' for short
        size = float(position['info']['size'])  # Access 'size' from 'info' dictionary
        
        if side == 'long':
            long += size
        elif side == 'short':
            short += size
        net_pos = long - short
        target_pos = max_pos *  df['pos'].iloc[-1]
        bet_size = round((target_pos) - (net_pos),3)
        
        
        
    # ### trade ###
        if target_pos > net_pos:
            if bet_size == 0:
                print('long ed')
                params = {'position_idx': 0, 'leverage': 10}
                order = exchange.create_order('BTCUSDT', 'market', 'buy', max_pos, None,params)
                pprint(order)
            elif net_pos < bet_size:
                print('long ed')
                params = {'position_idx': 1 ,'leverage': 10}
                order = exchange.create_order('BTCUSDT', 'market', 'buy', max_pos, None,params)
                pprint(order)

        if target_pos < net_pos:
            if bet_size == 0:
                print('sell ed')
                params = {'positionIdx': 0 , 'leverage': 10}
                order = exchange.create_order('BTCUSDT', 'market', 'sell', max_pos, None, params)
                pprint(order)
            elif net_pos > bet_size:
                print('sell ed')
                params={'reduceOnly': True,'positionIdx': 2,'leverage': 10}
                order = exchange.create_order('BTCUSDT', 'market', 'sell', max_pos, None, params)
                pprint(order)
`

**Comment by germangar** [comment]
You send your order value in contracts, and the amount already scaled by the leverage. Here's my code involving the conversion from USDT to contracts, if it can be of help

```
    def roundUpTick( value, tick )-> float:
        return ceil( value / tick ) * tick

    def roundDownTick( value, tick )-> float:
        return floor( value / tick ) * tick
        
    def findContractSizeForSymbol(cls, symbol)->float:
        m = cls.markets.get(symbol)
        if( m == None ):
            cls.print( ' * ERROR: findContractSizeForSymbol called with unknown symbol:', symbol )
            return 1
        return m.get('contractSize')

    def findPrecisionForSymbol(cls, symbol)->float:
        m = cls.markets.get(symbol)
        if( m == None ):
            cls.print( ' * ERROR: findPrecisionForSymbol called with unknown symbol:', symbol )
            return 1
        return m['precision'].get('amount')

    def contractsFromUSDT(cls, symbol, amount, price, leverage = 1.0 )->float :
        contractSize = cls.findContractSizeForSymbol( symbol )
        precision = cls.findPrecisionForSymbol( symbol )
        coin = (amount * leverage) / (contractSize * price)
        return roundDownTick( coin, precision ) if ( coin > 0 ) else roundUpTick( coin, precision )
```

**Comment by johnnychancf** [comment]
No that doesn't answer my question at all I am afraid :/ As I don't know what is the meaning of that code. Would you be able to add a note to your code?

**Comment by germangar** [comment]
Ok, I'll try.
Exchanges receive the orders either in fractions of the coin you are trading or in contracts. Either way, using contractSize and precision fields of the market structure you can calculate it all together.

contractSize specifies how much of a coin is the value of a contract. For example in BTC a contract is typically 0.001BTC
precision is the step at which the price can move.

So when a exchange works directly using the coin the size of the contract is 1, but precision is a fraction of 1 (in this case in BTC precision would be 0.001 and contractSize would be 1) and if the exchange uses as base the contracts precision would be 1 and contractSize would be 0.001.

You don't need to figure it out each case, because the markets have them already defined so either way for sending your price you would do this calculation for converting your amount in USDT to contracts/coin fractions as the exchange requires:
coin = (amount * leverage) / (contractSize * price)
The leverage is already taken into account.

Ande the result needs to be snapped to 'the grid' defined by precision. Like this:
coin = round( coin / precision) * precision
