### ISSUE TITLE
Composer v2.6.1 install fatal error

### ISSUE THREAD

**Issue by claumaries** [ccxt/ccxt#19087]
### Operating System

Ubuntu 20.04.6 LTS

### Programming Languages

PHP

### CCXT Version

4.0.80

### Description

When I run `composer install --verbose --prefer-dist --no-progress --no-interaction --no-dev --optimize-autoloader` on my production server I get a PHP fatal error. I did not have this error before and I've run composer many times on production. Looks like the issue started with version 4.0.75 or 4.0.77. But now even if I lower the version still get the error 

 I don't get this error on my local environment when I run composer install (using docker)

`"require": {
        "ccxt/ccxt": "^4.0.80",
  }`

### Code

```
  PHP Fatal error:  Declaration of ccxt\pro\Future::then($onFulfilled = null,  
   $onRejected = null, $onProgress = null) must be compatible with React\Prom  
  ise\PromiseInterface::then(?callable $onFulfilled = null, ?callable $onReje  
  cted = null): React\Promise\PromiseInterface in /var/www/.../vendor/ccxt/ccxt/php/pro/Future.php on line 15 

```

**Comment by ttodua** [comment]
i'll get to this soon, thanks for the report

**Comment by ttodua** [comment]
I've reproduced the issue, working on a fix.

**Comment by claumaries** [comment]
@ttodua The problem in my case was the composer version. I has composer v2.6.1 and I downgraded it to 2.5.5 and now composer install works ok

**Comment by ttodua** [comment]
ok, i'll close this topic for now, and please post if you have any comment related to this issue again
