### ISSUE TITLE
possible issue with StopLoss 

### ISSUE THREAD

**Issue by theanonymoustrader** [ccxt/ccxt#19089]
### Operating System

Windows Server 2022

### Programming Languages

Python

### CCXT Version

4.0.65

### Description

Hello!
I've built a function that places a market order with TP and SL.

But I've got this error: 

Failed to place market order with take profit: bybit {"retCode":10001,"retMsg":"sl:257970000 set for Sell position should greater base_price:259477000??LastPrice","result":{},"retExtInfo":{},"time":1693745651526}

 I've understood that the Stop Loss for Sell should be greater than current price, but I am sure that the price that I'm passing is right.
What I'm wrong?
I'm using Bybit.

### Code

```
  def place_market_order_with_take_profit(side, amount, take_profit_price,current_price,stop_loss_price):
    print("stoploss:" + str(stop_loss_price) + " cp:" + str(current_price))
    try:
        response = exchange.create_market_order(
            symbol=symbol,
            side=side,
            amount=amount,
            params={'takeProfit': float(take_profit_price),'stopLoss':str(int(stop_loss_price))}
        )
        print('Market order with take profit placed:', response, "a tp" +str(take_profit_price))
    except ccxt.ExchangeError as e:
        print("Alla data e ora" + formatted_datetime + "per side." , side, " current price:" , str(current_price) , " Failed to place market order with take profit:", e, 'take profit:' + str(take_profit_price) + " e sl:" + str(stop_loss_price))


```

**Comment by Dan-krm** [comment]
Hi @theanonymoustrader can you share your verbose output? You can follow these guidelines for opening an issue: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

There have been some recent changes to our stopLoss and takeProfit implementations, I would recommend updating your version of CCXT and following this documentation if you're trying to create a market order with an attached takeProfit or stopLoss: https://docs.ccxt.com/#/README?id=stoploss-and-takeprofit-orders-attached-to-a-position

Here is an example of how to create an order with stopLoss params on bybit, I would generally just use the create_order method and fill in all of the arguments including the type and price even if the price is set to None so the arguments are in the correct place:
* make sure the stopLoss is greater than the current market price for a market order of a short position, and for perpetual futures markets on bybit set the positionIdx param to 2 or 0, 0 is one-way mode, 1 is hedge-mode buy side and 2 is hedge-mode sell-side, you can check the exchange specific parameters here: https://bybit-exchange.github.io/docs/v5/order/create-order
```
import ccxt

exchange = ccxt.bybit({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

markets = exchange.load_markets()
exchange.verbose = True

symbol = 'BTC/USDT:USDT'
type = 'market'
side = 'sell'
amount = 0.001
price = None
params = '{"stopLoss":{"stopPrice":"27000"},"positionIdx":2}'

try:
    order = exchange.create_order(symbol, 'market', side, amount, price, params)
    print(order)
except Exception as e:
    print(type(e).__name__, str(e))
```

**Comment by Dan-krm** [comment]
I'm going to close this issue now, let me know if you have any other issues with setting the stopLoss and takeProfit on Bybit
