### ISSUE TITLE
Typo in ccxt: contractsSize field inconsistency in Position interface

### ISSUE THREAD

**Issue by simuty** [ccxt/ccxt#19103]
### Operating System

_Ubuntu 20.0.6_

### Programming Languages

JavaScript

### CCXT Version

"ccxt": "^4.0.70"

### Description

I have noticed a discrepancy in the contractsSize field of the **Position** interface in the ccxt library. The field is defined as **contractsSize** in the interface, but when accessing the position data, it is returned as **contractSize**, missing the "s" at the end. 

### Code

```
const symbol = 'LPT/USDT:USDT'
const info = await okxInstance!.fetchPosition(symbol)
console.log(JSON.stringify(info));
```

return data =>
```
{
  "info": {}
  "symbol": "LPT/USDT:USDT",
  "notional": 7.38038184,
  "marginMode": "cross",
  "entryPrice": 7.387,
  "unrealizedPnl": -0.0029999999999992,
  "percentage": -0.12183565723567,
  "contracts": 10,
// this 
  "contractSize": 0.1,
...
}
```

```
//  node_modules/ccxt/js/src/base/types.d.ts
export interface Position {
    symbol: string;
    id: string;
    timestamp?: number;
    datetime: string;
    contracts?: number;
// this 
    contractsSize?: number;
...
```

**Comment by carlosmiei** [comment]
Hello @simuty, you're right thanks for letting us know, we will fix it soon.
