### ISSUE TITLE
Question:OKex - Force SPOT trading - Always goes to Futures Endpoint

### ISSUE THREAD

**Issue by rawoke083** [ccxt/ccxt#1910]
- OS: UBUNTU 17
- Programming Language version:python 3
- CCXT version:1.10.X (not sure how to check - installed it about 10 days ago)
- Exchange:OKEx
- Method:createLimitBuyOrder

Hi Guys
I am trying to buy on the SPOT market on OKex but the result is always the same it fails with code:
**20007** which is **"Illegal parameter"**

Upon investigation it seems its always trying to call the "**Futures API Endpoint**" instead of the "**SPOT Api Endpoint**"

```
python code
#I've tried to add the parameter 'type=spot' still goes to the futures api

res = self.exA.createLimitBuyOrder("BTC/USD",0.002,9711,{"type":"spot"})
		
#Result (verbose=true)
POST https://www.okex.com/api/v1/future_trade.do 
Request: {'Content-Type': 'application/x-www-form-urlencoded', 'Accept-Encoding': 'gzip, deflate'} amount=0.002&api_key=XXXXXXX&contract_type=this_week&lever_rate=10&match_price=0&price=9711&symbol=btc_usd&type=spot&sign=XXXXXX

POST https://www.okex.com/api/v1/future_trade.do 
Response: {'Date': 'Thu, 15 Feb 2018 12:46:53 GMT', 'Content-Type': 'application/json', 'Content-Length': '35', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=XXXXXXXX; expires=Fri, 15-Feb-19 12:46:52 GMT; path=/; domain=.okex.com; HttpOnly, locale=en_US; Expires=Thu, 22-Feb-2018 12:46:52 GMT; Path=/', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY, SAMEORIGIN', 'Content-Disposition': 'inline;filename=f.txt', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': 'XXXXXXXXX-CPT'} {"result":false,"error_code":20007}
````

Any ideas how to force a spot/futures trade.
*Sorry for all the bolding, thanks for  great API

**Comment by kroitor** [comment]
> Any ideas how to force a spot/futures trade.

*"spot"* or *"no spot (future)"* – that is a property of a market.

To force a spot market trade or a futures market trade you just choose a proper market symbol and that's it.

Now, in your code: `BTC/USD` is not a `spot` market symbol, it's a futures-markets. The spot market symbol is `BTC/USDT`, which is a different pair.

```python

# just for your information:
self.exA.load_markets ()
print('BTC/USD', self.exA.markets['BTC/USD']['type'])
print('BTC/USDT', self.exA.markets['BTC/USDT']['type'])

# a spot trade
res = self.exA.createLimitBuyOrder("BTC/USDT",0.002,9711)
```

Let us know if this does not answer your question. Thx!

**Comment by rawoke083** [comment]
Fantastic ! Probably could have figured it out myself ! Maybe we can have a FAQ.
Thanks again Kroitor
