### ISSUE TITLE
Bitget.fetchBalance does not return the total USDT of my account

### ISSUE THREAD

**Issue by Eddyroll** [ccxt/ccxt#19119]
### Operating System

Windows

### Programming Languages

Python

### Description

Hello, I am developing my futures trading bot on Bitget.
The code below returns Total USDT = $256.8, while my Bitget futures test account has a total of $343
However, I would like to use the total amount of my account to calculate the quantities to buy or shorten for my trading bot.
Could you give me the right command/parameter to use in cctx.biget to recover the right amount?
Thank you!

### Code

import ccxt
bitget = ccxt.bitget({
    'apiKey': 'apikey',
    'secret': 'secret',
    'password': 'pswd',
    'options': {
        'defaultType': 'swap',
    }
# Récupération balance du compte Bitget
balance = bitget.fetchBalance()
#correction dev
print('Total USDT:',balance["USDT"])

```

**Comment by carlosmiei** [comment]
Hello @Eddyroll,

Hum since you're using `defaultType = 'swap` it should be fetching the swap wallet, can you post a verbose log? `exchange.verbose = True` ?

**Comment by germangar** [comment]
> Hello @Eddyroll,
> 
> Hum since you're using `defaultType = 'swap` it should be fetching the swap wallet, can you post a verbose log? `exchange.verbose = True` ?

I don't remember how the response originally looked but I'm doing this with mine for the same reason. I did this early on so maybe my setup wasn't entirely correct back then. IDK:
```
if( cls.exchange.id == "bitget" ):
            # Bitget response message is all over the place
            # so we reconstruct it from the embedded exchange info
            data = response['info'][0]
            balance = {}
            balance['free'] = float( data.get('available') )
            balance['used'] = float( data.get('usdtEquity') ) - float( data.get('available') )
            balance['total'] = float( data.get('usdtEquity') )
```

**Comment by carlosmiei** [comment]
@germangar, the ccxt response seems ok

```
bitget.fetchBalance ()
2023-09-07T14:39:14.097Z iteration 0 passed in 471 ms

{
  info: [
    {
      marginCoin: 'USDT',
      locked: '0',
      available: '65.76139397',
      crossMaxAvailable: '60.14517397',
      fixedMaxAvailable: '60.14517397',
      maxTransferOut: '60.14517397',
      equity: '65.23129397',
      usdtEquity: '65.231293975215',
      btcEquity: '0.002538751106',
      crossRiskRate: '0.00381041897',
      unrealizedPL: '-0.5301',
      bonus: '0'
    }
  ],
  USDT: { free: 65.76139397, used: 0, total: 65.76139397 },
  free: { USDT: 65.76139397 },
  used: { USDT: 0 },
  total: { USDT: 65.76139397 }
}
2023-09-07T14:39:14.097Z iteration 1 passed in 471 ms
```

**Comment by germangar** [comment]
Maybe it happened when a position was open? Or maybe when in cross margin. I remember I had a position in cross margin when I did it.

**Comment by Eddyroll** [comment]
Hi @carlosmiei and @germangar Thank you for your answers, if defaultType = 'swap' is a wrong option to return the right total amount of my Bitget account,, which option should i choose instead?

**Comment by carlosmiei** [comment]
@Eddyroll it's not the wrong one, that's the point, but due to the reasons mentioned by @germangar we might be returning the wrong values depending on the margin mode used. If you could provide a verbose log that would help up debug it.

**Comment by Eddyroll** [comment]
@carlosmiei i am not used to verbose, how can i provide it?

**Comment by carlosmiei** [comment]
@Eddyroll   You just need to do `exchange.verbose = True` before calling `fetch_balance`

**Comment by Eddyroll** [comment]
OK! 
fetch Request: bitget GET https://api.bitget.com/api/mix/v1/account/accounts?productType=UMCBL RequestHeaders: {'ACCESS-KEY': '', 'ACCESS-SIGN': '', 'ACCESS-TIMESTAMP': '1694101509394', 'ACCESS-PASSPHRASE': '', 'X-CHANNEL-API-CODE': 'p4sve', 'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bitget GET https://api.bitget.com/api/mix/v1/account/accounts?productType=UMCBL 200 ResponseHeaders: {'Date': 'Thu, 07 Sep 2023 15:45:07 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'X-Request-ID': '0dcf019b49cd4590932f47329715a8ee', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'requestTime': '1694101507829', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS', 'Content-Encoding': 'gzip', 'CF-Cache-Status': 'DYNAMIC', 'Set-Cookie': '__cf_bm=u3XhzDPSAE.afUR2y0d_duYFgDOAA7zDYlxESVzNIWk-1694101507-0-AVRO9pKwZRJ7hMPY6YH2jbHGjG/xtwba/A9tgr7mSiGL4veiBLoYFhuJrkr/Fygocj2h6n7tfEaD980S15dC1r4=; path=/; expires=Thu, 07-Sep-23 16:15:07 GMT; domain=.bitget.com; HttpOnly; Secure; SameSite=None, _cfuvid=5qt8s_9fDbma2PnhafygSfL6F8zLCa2fpz3kMwqR.Zo-1694101507938-0-604800000; path=/; domain=.bitget.com; HttpOnly; Secure; SameSite=None', 'X-Frame-Options': 'SAMEORIGIN', 'Server': 'cloudflare', 'CF-RAY': '803013b6ec4c2a63-CDG'} ResponseBody: {"code":"00000","msg":"success","requestTime":1694101507812,"data":[{"marginCoin":"USDT","locked":"0","available":"256.7973822","crossMaxAvailable":"324.6254467","fixedMaxAvailable":"324.6254467","maxTransferOut":"238.1904067","equity":"343.2324222","usdtEquity":"343.232422209134","btcEquity":"0.01331749469","crossRiskRate":"0.009584943625","unrealizedPL":"86.435039999971","bonus":"0"}]}

**Comment by Eddyroll** [comment]
I seems that it returns "available" and it should return "equity" or "usdtequity" right?

**Comment by carlosmiei** [comment]
@Eddyroll We will check it but in the meantime you can get that values by doing `balance['info'])`

**Comment by Eddyroll** [comment]
what is the right string? because the string below doesn't work
print(balance['info'])
          ~~~~~~~^^^^^^^^
TypeError: 'float' object is not subscriptable

**Comment by germangar** [comment]
response = bitget.fetchBalance()
info= response['info'][0]

That should work

**Comment by Eddyroll** [comment]
Hi again, so now it seems that 'equity' is the right variable containing the total amount ($343) of my account, what do i have to write after
balance = bitget.fetchBalance()
to have that total amount in my python program?

**Comment by Dan-krm** [comment]
You would need to iterate through the info list in your balance response then pull the equity value, something like this might work:
```
info = balance['info']
for x in range(0, len(info)):
    entry = info[x]
    equity = entry['equity']
```
By the way the equity value includes the unrealized PNL of your open positions,
there's some descriptions of the values returned by the exchange here:
https://bitgetlimited.github.io/apidoc/en/mix/#get-account-list

**Comment by Eddyroll** [comment]
It works perfectly! Many thanks @Dan-krm @carlosmiei  @germangar
