### ISSUE TITLE
Get data from ccxt   dot match okex exchange match?

### ISSUE THREAD

**Issue by aboutgov** [ccxt/ccxt#19110]
### Operating System

centos7.9

### CCXT Version

4.0.78

### Description

get 1min  candle line data  dot not match  okex exchange data
for example:
![image](https://github.com/ccxt/ccxt/assets/27661618/3d28a485-d0a5-43ab-9878-d3ff9975ea88)

this is my python code
------------------------------------
from datetime import datetime, timedelta
import time
import pandas as pd
from email.mime.text import MIMEText
from smtplib import SMTP
import ccxt

exchange = ccxt.okex()
time_interval = '5m'

symbol = 'BTC/USDT'

content = exchange.fetch_ohlcv(symbol, timeframe=time_interval)
print(content)

### Code

from datetime import datetime, timedelta
import time
import pandas as pd
from email.mime.text import MIMEText
from smtplib import SMTP
import ccxt

exchange = ccxt.okex()
time_interval = '5m'

symbol = 'BTC/USDT'

content = exchange.fetch_ohlcv(symbol, timeframe=time_interval)
print(content)

**Comment by carlosmiei** [comment]
Hello @aboutgov, can you enable the verbose mode and check the raw data? (`exchange.verbose = True`). CCXT does not alter the data we just unify the information provided by the API
