### ISSUE TITLE
c# privatePostTradeCancelAlgos  return {"code":"50002","data":[],"msg":"json data format error"}

### ISSUE THREAD

**Issue by 810961186** [ccxt/ccxt#19113]
### CCXT Version

ccxt 0.0.29-beta

### Description

c# use privatePostTradeCancelAlgos  return {"code":"50002","data":[],"msg":"json data format error"}

### Code

```
      Dictionary<string, object> dicTradeCancelParams = new Dictionary<string, object>();
                        dicTradeCancelParams.Add("instId", order_symbol);
                        dicTradeCancelParams.Add("algoId", item.algoId);
   var tradeCancelAlgosObj = await exchange.privatePostTradeCancelAlgos(parameters: dicTradeCancelParams);


passed in should be an array

![image](https://github.com/ccxt/ccxt/assets/30916252/d2a0597c-a747-41a2-b750-3f259b9fabde)

```

**Comment by carlosmiei** [comment]
Hello @810961186, what is the exchange being used?

**Comment by 810961186** [comment]
var exchange = new okex5();

**Comment by 810961186** [comment]
![photo_2023-05-30_16-29-46](https://github.com/ccxt/ccxt/assets/30916252/30a8a327-db6f-433b-9be5-9d5ba96fee62)
What we pass in is an object, and the document requires an array.

**Comment by carlosmiei** [comment]
@810961186 I will check it and revert

**Comment by 810961186** [comment]
solve，List<object> listObject = new List<object>();
                        Dictionary<string, object> dicTradeCancelParams = new Dictionary<string, object>();
                        dicTradeCancelParams.Add("instId", order_symbol);
                        dicTradeCancelParams.Add("algoId", item.algoId);

                        listObject.Add(dicTradeCancelParams);

**Comment by 810961186** [comment]
donot use List<Dictionary<string, object>> listObject = new List<Dictionary<string, object>>();

**Comment by carlosmiei** [comment]
@810961186 Sorry not sure I got it, did that solve the problem or not?

**Comment by 810961186** [comment]
i solve  it

**Comment by carlosmiei** [comment]
@810961186 Thanks for letting me know, in that case I will close this issue feel free to reopen it if anything
