### ISSUE TITLE
A list of exchanges supporting WebSocket

### ISSUE THREAD

**Issue by incompletude** [ccxt/ccxt#1914]
Hi Kroitor,

Do you have a list of exchanges offering push APIs? I'm pretty sure ccxt will offer all of them, so I wonder if you have a list already.

Best,

**Comment by deltacat** [comment]
I also want to know. 😆

**Comment by ardabeyazoglu** [comment]
I've been using `bittrex`, `poloniex`, `binance` and `hitbtc` websocket/push apis already and they work fine.

@kroitor If you ever start writing a base for websocket implementation, I'd like to contribute. At least, listening for ticker updates would be very useful feature.

Also for some of the exchanges, there are already some libraries written for that (mostly js). Maybe integrating them to ccxt only for websocket functionality might be much easier and faster.

**Comment by dinhnv** [comment]
@ardabeyazoglu Did you use websocket for listening to a single ticker or multiple tickers? Can we implement a function for listening on many tickers for one exchange?

**Comment by ardabeyazoglu** [comment]
@dinhnv I've been using websocket for listening ticker updates for multiple coins in each exchange. Let's say, i have 4 different node scripts. Each of them is listening a different exchange's ticker updates for multiple coins. And yes in one function.

For bittrex, binance and poloniex there are already some node libraries that can do this easily. For hitbtc version2 api, there is none yet. However I implemented it in less than a few hours, coz it uses json-rpc and documentation is good.

**Comment by TomAshley303** [comment]
A while back, I had a heck of a time getting a decent websocket client going in PHP. I wound up getting it working though. The simplest way I found to do it was the composer library `textalk/websocket`

**Comment by kroitor** [comment]
The answer to the initial issue on the list of exchanges supporting WS: https://algosforcryptos.com/trading-apis-top-crypto-exchanges/

Hope it helps. I'd suggest to move further discussion related to WS to #56. Thx!

**Comment by jaredtkatz** [comment]
Would anyone happen to know which exchanges support _trading_ via websockets? OKEx is the only one I've found so far.
