### ISSUE TITLE
CAN´T CREATE AN ORDER IN UNILATERAL POSITION TYPE BITGET

### ISSUE THREAD

**Issue by carolestalisto** [ccxt/ccxt#19140]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

4.0.79

### Description

When i want to create a market buy/sell order, they give me this error: 

"ccxt.base.errors.ExchangeError: bitget {"code":"40774","msg":"The order type for unilateral position must also be the unilateral position type.","requestTime":1694274505084,"data":null}". 

There is a way to make an order for the unilateral position mode.

### Code

import ccxt

BITGET = ccxt.bitget({
    'apiKey': 'config.apikey',
    'secret': 'config.secretapikey',
    'password': 'config.password',
    'options': {
        'defaultType': 'swap',
    }
})
BITGET.set_sandbox_mode(True)

symbol = 'SETH/SUSDT:SUSDT'

ORDERMARKETBUY = BITGET.create_order(symbol, 'market', 'buy', 0.01)
print(ORDERMARKETBUY)

**Comment by germangar** [comment]
First you have to make sure you are in one-way more. You set the symbol to one-way mode with the set_position_mode method.
`response = cls.exchange.set_position_mode( False, symbol )`
And you set the margin mode with set_margin_mode
`response = cls.exchange.set_margin_mode( 'isolated', symbol, params )`
And finally set the leverage:
`response = cls.exchange.set_leverage( leverage, symbol, params )`

You don't need to do these everytime. Only the first time and when you want to change any of those parameters.
Then you can make the orders. For Bitget, when you are in one-way mode you have to add special params for long and short ('side':'buy_single' for long and 'side':'sell_single' for short)

```
            params = {}

            if( cls.exchange.id == 'bitget' ):
                params['side'] = 'buy_single' if( order.type == "buy" ) else 'sell_single'
                if( order.reverse ):
                    params['reverse'] = True
                    
            response = cls.exchange.create_market_order( order.symbol, order.type, order.quantity, None, params )
```

(These are snippets copy/pasted from my code so they have variables defined elsewhere. They are just meant as a guide)

**Comment by carlosmiei** [comment]
Hello @germangar, thanks for jumping in and helping out by explaining it.

**Comment by Dan-krm** [comment]
For bitget v2 it looks like one-way mode orders don't work if the `tradeSide` parameter is filled which is required for hedge mode orders.

I opened a pull request that allows you to set `"oneWayMode": true` in the createOrder params, so you can create one way mode orders on bitget without getting the unilateral error.

**Comment by isaquemelo** [comment]
To solve this while keeping using hedge-mode you can send the addicional param "tradeSide". 

Just adding the `tradeSide` param to the original will make it work:

This example is for cctx in node, but similar in python will work

```
            const params = {
                tradeSide: 'open'
            };
            
            const order = await this.exchange.createOrder(symbol, type, side, size, price, params)
```
