### ISSUE TITLE
Binance Exchange not working on production server

### ISSUE THREAD

**Issue by Mohdwaqas816** [ccxt/ccxt#19167]
### Operating System

Windows 11

### Programming Languages

Python

### CCXT Version

3.1.46

### Description

1 - Working perfectly in local server
2 - Getting this error on production server: 

{"error":"binance GET https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1692361185243&recvWindow=10000&signature=*******sjahef9wnr9323ufew99e8********  {\n  \"code\": 0,\n  \"msg\": \"Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error.\"\n}"}

### Code

```
import ccxt
from config import API_KEY_BINANCE, SECRET_KEY_BINANCE

binance = ccxt.binance({
    'apiKey': API_KEY_BINANCE,
    'secret': SECRET_KEY_BINANCE

})

def fetch_balance():
    balances = binance.fetch_balance()['total']
    filtered_balances = {currency: balance for currency, balance in balances.items() if balance > 0}
    print(filtered_balances)

fetch_balance()

```

**Comment by sc0Vu** [comment]
Hi @Mohdwaqas816 

It seems your server was in the unavailable service from binance. Can you deploy to another location?

**Comment by carlosmiei** [comment]
@Mohdwaqas816 Hello, make sure your server is not US based.

**Comment by Mohdwaqas816** [comment]
> Hi @Mohdwaqas816
> 
> It seems your server was in the unavailable service from binance. Can you deploy to another location?

Yes we are planning to change server location currently our server location is US-west

**Comment by Mohdwaqas816** [comment]
> @Mohdwaqas816 Hello, make sure your server is not US based.

thanks got it.
