### ISSUE TITLE
symbol BTC/FDUSD leverage not working

### ISSUE THREAD

**Issue by cO-Oe** [ccxt/ccxt#19177]
### Operating System

Windows11

### Programming Languages

Python

### CCXT Version

4.0.78

### Description

Hi, 

We are working on binance BTC/FDUSD symbol trading with leverage. 
This symbol is working totally fine without leveraging (e.g. binance.fetch_ticker, binance.create_market_buy_order), while when calling binance.markets[ 'BTC/FDUSD' ], the return leverage limit is None.

We've checked that the return of leverage with binance.markets[ 'BTC/USDT' ] is working while binance.markets[ 'BTC/FDUSD' ] and binance.markets[ 'FDUSD/BTC' ] are not (returns None), also binance.fapiPrivate_post_leverage is not working with 'FDUSD' symbols.

We've also confirmed with binance support that 'FDUSD' symbols endpoints are fine on binance side, so we suppose the issue is on the ccxt tool, thanks.

### Code

```
symbol = 'BTC/FDUSD'
self.binance = ccxt.binance({ })

result = float(self.binance.fetch_ticker(symbol)['bid']) # Works
order = self.binance.create_market_buy_order(symbol, amount) # Works
order = self.binance.create_market_sell_order(symbol, amount) # Works

self.binance.load_markets()
market = self.binance.markets[ symbol ]  # returns None in leverage limit
self.binance.fapiPrivate_post_leverage(symbol) # Not working
```

**Comment by carlosmiei** [comment]
Hello @cO-Oe,

The main issue is that you're calling a derivatives endpoint (fapiPrivate_post_leverage) using a spot symbol.

**Comment by cO-Oe** [comment]
Hi @carlosmiei, 

Appreciated! We've switched to margin trading for spot symbols and worked as what we would liked to, thanks!
