### ISSUE TITLE
ExchangeError: coinbasepro level2, level3, and full channels now require authentication.

### ISSUE THREAD

**Issue by Phionx** [ccxt/ccxt#19176]
### Operating System

MacOS

### Programming Languages

Python

### CCXT Version

'4.0.11'

### Description

Hi!

I'm unsure why the authentication is failing for coinbasepro when trying to stream orderbook data using `ccxt.pro`. 

Any guidance would be greatly appreciated. Thank you!

### Code

Code:
```
#!/usr/bin/env python3

import ccxt.pro as ccxtpro
from asyncio import run

creds = {
    "apiKey": <api-key>,
    "secret": <secret>,
    "password": <api-key-passphrase>,
}


async def main():
    exchange = ccxtpro.coinbasepro(creds)
    while True:
        orderbook = await exchange.watch_order_book("BTC/USD")
        print(orderbook["asks"][0], orderbook["bids"][0])
    await exchange.close()


run(main())
```

Error:
```
ccxt.base.errors.ExchangeError: coinbasepro level2, level3, and full channels now require authentication. https://docs.cloud.coinbase.com/exchange/docs/websocket-auth
```

**Comment by carlosmiei** [comment]
Hello @Phionx,
Can you try to update to the latest version? I believe this issue was solved in the meantime.

**Comment by Phionx** [comment]
Thank you for your response @carlosmiei ! 

I upgraded to version "4.0.90" and I am now able to stream orderbook data.
