### ISSUE TITLE
fetchOpenOrders for binance does not work

### ISSUE THREAD

**Issue by kungla** [ccxt/ccxt#1918]
fetchOpenOrders method for binance does not work. (tested kucoin as well, it works).
It returns always empty array.

(Not related but I also noticed that cancelOrder fro binance does not return symbol in correct format)

- OS: OSX 10.13.3
- Programming Language version: Node v8.9.3
- CCXT version: ^1.10.1120
- Exchange: binance
- Method: fetchOpenOrders

**Comment by kroitor** [comment]
> fetchOpenOrders method for binance does not work. (tested kucoin as well, it works).
It returns always empty array.

Can you, please, show a minimal snippet of your code (leave just the code that is needed to reproduce the problem)?

> (Not related but I also noticed that cancelOrder fro binance does not return symbol in correct format)

Can you show your *verbose output*? Add `{ verbose: true }` to exchange constructor arguments and copy-paste the output here (without the keys), as described in this section: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by kungla** [comment]
Thanks for quick replay. 

1) .verbose = true 
`fetch:
 binance GET https://api.binance.com/api/v1/exchangeInfo
Request:
 {}
 undefined

fetch:
 binance GET https://api.binance.com/api/v1/exchangeInfo
Request:
 {}
 undefined

handleRestResponse:
 binance GET https://api.binance.com/api/v1/exchangeInfo 200 OK
Response:
 { date: 'Fri, 16 Feb 2018 00:55:25 GMT',
  'content-type': 'application/json',
  'transfer-encoding': 'chunked',
  connection: 'close',
  server: 'nginx',
  'content-encoding': 'gzip',
  'strict-transport-security': 'max-age=31536000; includeSubdomains',
  'x-frame-options': 'SAMEORIGIN' }
 {"timezone":"UTC","serverTime":1518742525777,"rateLimits":... too long

fetch:
 binance POST https://api.binance.com/api/v3/order
Request:
 { 'X-MBX-APIKEY': 'X',
  'Content-Type': 'application/x-www-form-urlencoded' }
 timestamp=1518742525968&recvWindow=5000&symbol=BTCUSDT&quantity=1&type=LIMIT&side=BUY&price=100.00&timeInForce=GTC&signature=X

handleRestResponse:
 binance GET https://api.binance.com/api/v1/exchangeInfo 200 OK
Response:
 { date: 'Fri, 16 Feb 2018 00:55:25 GMT',
  'content-type': 'application/json',
  'transfer-encoding': 'chunked',
  connection: 'close',
  server: 'nginx',
  'content-encoding': 'gzip',
  'strict-transport-security': 'max-age=31536000; includeSubdomains',
  'x-frame-options': 'SAMEORIGIN' }
 {"timezone":"UTC","serverTime":1518742525783,"rateLimits":...too long

fetch:
 binance GET https://api.binance.com/api/v3/openOrders?timestamp=1518742526006&recvWindow=5000&symbol=BTCUSDT&signature=X
Request:
 { 'X-MBX-APIKEY': 'X' }
 undefined

handleRestResponse:
 binance GET https://api.binance.com/api/v3/openOrders?timestamp=1518742526006&recvWindow=5000&symbol=BTCUSDT&signature=X 200 OK
Response:
 { date: 'Fri, 16 Feb 2018 00:55:27 GMT',
  'content-type': 'application/json',
  'transfer-encoding': 'chunked',
  connection: 'close',
  server: 'nginx',
  vary: 'Accept-Encoding',
  'strict-transport-security': 'max-age=31536000; includeSubdomains',
  'x-frame-options': 'SAMEORIGIN',
  'content-encoding': 'gzip' }
 []

[]
handleRestResponse:
 binance POST https://api.binance.com/api/v3/order 200 OK
Response:
 { date: 'Fri, 16 Feb 2018 00:55:27 GMT',
  'content-type': 'application/json',
  'transfer-encoding': 'chunked',
  connection: 'close',
  server: 'nginx',
  vary: 'Accept-Encoding',
  'strict-transport-security': 'max-age=31536000; includeSubdomains',
  'x-frame-options': 'SAMEORIGIN',
  'content-encoding': 'gzip' }
 {"symbol":"BTCUSDT","orderId":46736083,"clientOrderId":"G0o9LNjSF1KjdVSQEmTYlX","transactTime":1518742527155,"price":"100.00000000","origQty":"1.00000000","executedQty":"0.00000000","status":"NEW","timeInForce":"GTC","type":"LIMIT","side":"BUY"}`

2) The code
```
const run = async () => {
    try {
        const ccxt = require('ccxt');
        const client = new ccxt.binance( {
            apiKey: "X",
            secret: "X"
        });
        client.createOrder('BTC/USDT', 'limit', 'buy', 1, 100);
        const activeOrders = await client.fetchOpenOrders('BTC/USDT');
        console.log(activeOrders); // returns []
    } catch (e) {
        console.error(e);
    }
};

run();

```
It prints always empty array even if there are orders open.

Also noticed that code asks for exchangeInfo twice, can I avoid that?

**Comment by kroitor** [comment]
```JavaScript
const run = async () => {
    try {
        const ccxt = require('ccxt');
        const client = new ccxt.binance( {
            apiKey: "X",
            secret: "X"
        });

        // add this missing "await" word here
        // ↓         
        // ↓

        await client.createOrder('BTC/USDT', 'limit', 'buy', 1, 100);
        const activeOrders = await client.fetchOpenOrders('BTC/USDT');
        console.log(activeOrders); // returns []
    } catch (e) {
        console.error(e);
    }
};

run();
```

Hope it helps.

**Comment by kungla** [comment]
Sorry for the bug in the example there.
I had a bit different setup before and I discovered there was problem with Binance. It showed in UI one open order that was not there actually. When I canceled it from UI, I got error from Binance and now all OK. 

Thank you very much. If I get it all working as needed, I promise to become supporter for you awesome project.

**Comment by DRMFR** [comment]
Can somebody please help. I sent btc from gdax to my Binance USDT address and is showing completed on my Coinbase account but is no where to be found on Binance and is not showing in history. I logged on to Omni explorer and it shows an available balance but have no idea where it is and why it didn’t get to Binance

**Comment by kroitor** [comment]
@DRMFR 

1. How many confirmations does your transaction have?
2. Are you sure that you've sent it to a correct address?

**Comment by DRMFR** [comment]
I just contacted gdax and it is confirmed and it is the correct address

**Comment by kroitor** [comment]
@DRMFR you should open a ticket with Binance, if you're sure everything is correct.

**Comment by DRMFR** [comment]
If I go to omniexplorer it shows the correct address and then underneath it shows an available balance as BTC. Where is this located? If I go to Blockcypher it shows the completed transaction

**Comment by DRMFR** [comment]
It isn’t even showing up in history on Binance even as pending

**Comment by DRMFR** [comment]
Binance wanted a bunch of information and .01BTC and they said they would get it back for me. I guess this happens a lot but it is clear it is probably better just deposit everything as ETH or BTC and buy from there. Do not use or try and transfer to USDT even though they keep adding more coins/USDT. Will let you know if they really help-Thanks

**Comment by saidab71** [comment]
hi
I'm trying to get open orders in binance.us with python using /api/v3/openOrders witch does not work,
please help

**Comment by kroitor** [comment]
@saidab71 https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it
