### ISSUE TITLE
Question OKex Margin-Spot (buy/sell)

### ISSUE THREAD

**Issue by rawoke083** [ccxt/ccxt#1922]
- OS:UBUNTU 17
- Programming Language version: python 3.6
- CCXT version: 1.10.x
- Exchange:Okex
- Method: createOrder

I'm trying todo margin trade on spot (BTC/USDT) not futures

Tried a few variations but nothing seems to work.
I do have BTC in my margin trading account	and setup to trade it
Just can't seem to workout what to put in the createOrder to do a margin-short-sell ?

``` 
#Tried a few variations 
res= okexExchange.createOrder ("BTC/USDT", "limit", "sell", 0.001,9999,{"leverage":1})
res= okexExchange.createOrder ("BTC/USDT", "limit", "sell", 0.001,9999)
res= okexExchange.createOrder ("BTC/USDT", "limit", "margin sell", 0.001,9999)
```

**Comment by kroitor** [comment]
> 'm trying todo margin trade on spot (BTC/USDT) not futures

But who said that OKEX allows that? They don't offer margin trading on crypto tokens, just the fiat futures only.

https://www.okex.com/rest_api.html

![okex-order-types](https://user-images.githubusercontent.com/1294454/36312898-fd543900-1340-11e8-9686-3946f5253561.jpg)

For the BTC/USDT they will accept basic `limit` or `market` orders and that's it.
Hope it answers your question.

**Comment by rawoke083** [comment]
Weird.. cause I can do it via the "interface"

Borrow some BTC then sell that ? Is that not "margin trading" 
Sorry I might be missing something ?


![btc](https://user-images.githubusercontent.com/5529508/36313077-28c2fb4c-1339-11e8-9cfc-dcbe08bc8c4d.png)

**Comment by rawoke083** [comment]
PS. How would the createOrder look to short  FUTURES ? Just Use "BTC/USD"  as symbol ?

**Comment by kroitor** [comment]
> How would the createOrder look to short FUTURES ? Just Use "BTC/USD" as symbol ?

Yep, exactly.

> Borrow some BTC then sell that ? Is that not "margin trading"

Technically, it is similar. The reason is that they won't allow to do that with crypto tokens (BTC/USDT) via their API. You cannot really leverage-sell (short) on `BTC/USDT` with their website, you can borrow BTC and sell it on `BTC/USDT` for USDT, but you cannot set a leverage rate upon the moment of selling the BTC for USDT with their API, afaik.

**Comment by rawoke083** [comment]
Ahh ok makes sense ! Thank you  Sir !
