### ISSUE TITLE
OKX create order  parms  takeProfit `tpTriggerPxType` is error

### ISSUE THREAD

**Issue by Chord-Labs** [ccxt/ccxt#19226]
### Operating System

mac

### Programming Languages

Python

### CCXT Version

4.0.3

### Code

```
  2513: takeProfitTriggerPriceType = self.safe_string_2(stopLoss, 'triggerPriceType', 'tpTriggerPxType')

```

**Comment by Dan-krm** [comment]
Hi @Chord-Labs can you elaborate on this issue and share your method call and verbose response? You can follow these guidelines for opening an issue: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by Chord-Labs** [comment]
```
params['takeProfit'] = {
      'tpTriggerPx': '31000', 
      'tpOrdPx': '-1',
      'tpTriggerPxType': 'mark',
    }

exchange = ccxt.okex({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET',
        'password': 'YOUR_API_PASSWORD',
    })
order = await exchange.create_order('BTC/USDT:USDT', 'limit','buy', '1', '21000', params)
```
Unable to set Take-profit trigger price type

**Comment by Chord-Labs** [comment]
#19233

**Comment by Dan-krm** [comment]
> #19233

Thanks I've also opened this #19230
