### ISSUE TITLE
Huobi Contract `create_order` carrying the wrong type of `clientOrderId` parameter

### ISSUE THREAD

**Issue by BaoziCDR** [ccxt/ccxt#19234]
### Operating System

MacOS 13.4.1 (Apple M1)

### Programming Languages

Python

### CCXT Version

4.0.82

### Description

 When I'm ready to call the contract to place an order, the `clientOrderId` parameter type required by contract to place an order is **long**, but CCXT converts it to **String** when reading the parameter. T-T
 - https://www.huobi.com/en-us/opend/newApiPages/?id=8cb77159-77b5-11ed-9966-0242ac110003

The following is the error message:
```
ccxt.base.errors.InvalidOrder: huobi {"status":"error","err_code":1067,"err_msg":"The client_order_id field is invalid. Please re-enter.","ts":1694589259929}
```
I think there's something wrong with this part of the code:
<img width="1088" alt="huobi" src="https://github.com/ccxt/ccxt/assets/44897251/b5f9f810-12b1-4b9a-b058-9b7f217e6984">

### Code

```Python
huobi = ccxt.huobi()
huobi.options['defaultType'] = 'swap'
huobi.options['marginMode'] = 'cross'
huobi.create_order(..., params={'client_order_id': 123123123, ....})
```

**Comment by carlosmiei** [comment]
Hello @BaoziCDR,
Thanks for letting us know, we will take a look and fix it asap.
