### ISSUE TITLE
OKEX - fetch_balance() returns USD not USDT

### ISSUE THREAD

**Issue by candreacchio** [ccxt/ccxt#1927]
- OS: Ubuntu 17.04
- Programming Language version: python3
- CCXT version: 1.10.1130 
- Exchange: OKEX

OKEX returns USD not USDT for balance

**Comment by kroitor** [comment]
Can you elaborate, please? Any info, verbose output, screenshots or something?

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by candreacchio** [comment]
So trying to fetch multiple exchanges balances at once... But simply in python

`
site = ccxt.okex({
    'apiKey': 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX',
    'secret': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
})

siteBalance = site.fetch_balance()
print(siteBalance['USDT']['free'])

`

This python code works fine on other exchanges (hitbtc & poloniex) but not on OKEX.. OKEX returns 

I turned on verbose and it was quite long, i can upload a text file if needed

**Comment by kroitor** [comment]
> i can upload a text file if needed

Yes, please, do upload it (pastebin or somewhere), but first, search for all occurrences of `usdt` in it to see yourself what is actually returned from OKEX.

**Comment by kroitor** [comment]
> So trying to fetch multiple exchanges balances at once...

You may be misunderstanding how USD futures markets work with OKEX. When you're trading with USD, you're using a different type of account (a margin account), not a crypto token trading account. 

- Margin account balance and futures contract trading: https://www.okex.com/rest_api.html#ftapi (you can fetch it from ccxt as well with implicit methods: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods)
- Spot account balance and crypto token trading: https://www.okex.com/rest_api.html#stapi (this is the default returned from ccxt)

Those two accounts are separated from each other on OKEX. CCXT will fetch for crypto account data by default, as this is the most common type of trading with OKEX. However, you can use implicit methods to fetch the margin account balance (USD) as well.

Let us know if it doesn't resolve your issue. Thx!
