### ISSUE TITLE
missing order_trades api call in php exmo 

### ISSUE THREAD

**Issue by guefi** [ccxt/ccxt#1931]
- OS: Win10 & Linux
- Programming Language version: PHP
- CCXT version: 1.10.1116
- Exchange: exmo
- Method: order_trades

Method is actually missing and needed for a limit order. By the way no user trades, orders methods are actually existing. 
Is it possible to estimate, when this could be provided. I assumed that this should be a minimal of requirement, if an exchange will be implemented in your cool api.

**Comment by kroitor** [comment]
See #2014 (to be merged soon).
