### ISSUE TITLE
kucoinfutures empty fetchPosition - error.

### ISSUE THREAD

**Issue by ptfu0** [ccxt/ccxt#19325]
### Operating System

ubuntu 23.04

### Programming Languages

Python

### CCXT Version

ccxt-4.0.100

### Description

If the position is empty, it returns an error (data = []):
Traceback (most recent call last):
    self._position = self.exchange.fetchPosition(symbol) 
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/ccxt/kucoinfutures.py", line 904, in fetch_position
    return self.parse_position(data[0], market)
                               ~~~~^^^
maybe we should fix it this way.
if len(data) > 0:
            return self.parse_position(data[0], market)
        else:
            return {}

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @ptfu0, thanks for letting us know, we will fix it asap.

**Comment by carlosmiei** [comment]
@ptfu0 Actually this bug was fixed already it will be available in the next release in a few minutes.

**Comment by ptfu0** [comment]
There is a new problem, there is no position, but fetchPosition started giving a non-existent position.
exchange.fetchPosition('BTC/USDT:USDT')
{'info': {'id': '', 'symbol': 'XBTUSDTM', 'autoDeposit': False, 'maintMarginReq': 0, 'riskLimit': 25000, 'realLeverage': 0, 'crossMode': False, 'delevPercentage': 0.0, 'openingTimestamp': 0, 'currentTimestamp': 1695133582609, 'currentQty': 0, 'currentCost': 0, 'currentComm': 0, 'unrealisedCost': 0, 'realisedGrossCost': 0, 'realisedCost': 0, 'isOpen': False, 'markPrice': 0, 'markValue': 0, 'posCost': 0, 'posCross': 0, 'posCrossMargin': 0, 'posInit': 0, 'posComm': 0, 'posCommCommon': 0, 'posLoss': 0, 'posMargin': 0, 'posMaint': 0, 'maintMargin': 0, 'realisedGrossPnl': 0, 'realisedPnl': 0, 'unrealisedPnl': 0, 'unrealisedPnlPcnt': 0, 'unrealisedRoePcnt': 0, 'avgEntryPrice': 0, 'liquidationPrice': 0, 'bankruptPrice': 0, 'settleCurrency': 'USDT', 'maintainMargin': 0, 'riskLimitLevel': 1}, 'id': None, 'symbol': 'BTC/USDT:USDT', 'timestamp': 1695133582609.0, 'datetime': None, 'lastUpdateTimestamp': None, 'initialMargin': 0.0, 'initialMarginPercentage': None, 'maintenanceMargin': 0.0, 'maintenanceMarginPercentage': 0.0, 'entryPrice': 0.0, 'notional': 0.0, 'leverage': 0.0, 'unrealizedPnl': 0.0, 'contracts': 0.0, 'contractSize': 0.001, 'realizedPnl': 0.0, 'marginRatio': None, 'liquidationPrice': 0.0, 'markPrice': 0.0, 'lastPrice': None, 'collateral': 0.0, 'marginMode': 'isolated', 'side': None, 'percentage': None, 'stopLossPrice': None, 'takeProfitPrice': None}

**Comment by carlosmiei** [comment]
@ptfu0 I would not call it a problem because that is the "default" position returned by kucoin. You can discard these empty positions by checking if the size and the price are 0.

**Comment by ptfu0** [comment]
Thanks, that's roughly what I did, except I did a side is None )
