### ISSUE TITLE
Is exchange XT.com supported ?

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#19326]
Hello,

I can't find a Python class for exchange XT.com and I'm wondering if this exchange is supported by CCXT. It has been discussed [here](https://github.com/ccxt/ccxt/pull/17118) and [here](https://github.com/ccxt/ccxt/pull/17118) but the documentation doesn't mentions it. Could you please clarify ?

XT.com itself wrote [a blog post](https://medium.com/@XT_com/xt-com-enters-strategic-partnership-with-ccxt-for-professional-traders-324decc936d3) about partnership with CCXT.

Thank you,
Kinzowa

**Comment by carlosmiei** [comment]
Hello @Kinzowa, it was delisted in the meantime, check this report https://github.com/ccxt/ccxt/issues/18315
