### ISSUE TITLE
FetchTicker/FetchTickers Suggestion

### ISSUE THREAD

**Issue by Kmasterrr** [ccxt/ccxt#1932]
Hi there,

When using fetchTicker or FetchTickers might i suggest that part of the "parseTicker" method that you add an extra property to the return structure called "exchange".

The problem is when dynamically reading through all the markets, there is no way to get the exchange that the response is from as the way i do it is via multiple promises.

I have been doing it manually by changing all the exchanges individual .js files, as below:

![image](https://user-images.githubusercontent.com/11454971/36339814-49427544-13d6-11e8-9fe7-caed889da657.png)

Please look into adding this. Otherwise, thanks for such an awesome node package :D

**Comment by kroitor** [comment]
> there is no way to get the exchange that the response is from as the way i do it is via multiple promises

We could, of course, add that field, but, hey, think this way: if most people don't ask for it, then, it means, they managed to solve the same issue somehow, right? Maybe, you're not doing it properly, and when organized properly, promises are capable of reporting their sources perfectly fine. However, it's hard to tell without seeing your code and we don't have time to go through your application. 

Therefore we propose the following:

https://github.com/ccxt/ccxt/blob/master/examples/js/fetch-from-many-exchanges-simultaneously.js

```JavaScript
'use strict'

const ccxt = require ('../../ccxt.js')
const log  = require ('ololog')

const symbol = 'ETH/BTC'
const exchanges = [ 'gdax', 'hitbtc2', 'poloniex' ]

;(async () => {

    const result = await Promise.all (exchanges.map (async id => {

        const exchange = new ccxt[id] ({ 'enableRateLimit': true })
        const ticker = await exchange.fetchTicker (symbol)
        return exchange.extend ({ 'exchange': id }, ticker)

    }))

    log (result);

}) ()
```

Let us know if this does not help.
