### ISSUE TITLE
[Bybit] 404 Not Found Error occurs when you run fetchbalance in Bybit Unified Account

### ISSUE THREAD

**Issue by bongkook** [ccxt/ccxt#19322]
### Operating System

Mac

### Programming Languages

JavaScript

### CCXT Version

4.0.100

### Description

Hello.

If you run fetchbalance in bybit Unified Account, you will get a 404 Not Found error as shown below.
I was using it without any problems up to version 4.0.95.
please check.
----------------------------------------result-------------------------------------------
fetch Request:
  bybit GET https://api-testnet.bybit.com/v5/account/wallet-balance?accountType=UNIFIED 
 RequestHeaders:
  {
   'Content-Type': 'application/json',
   'X-BAPI-API-KEY': 'TTOLXJHXPGCEHBAPPE',
   'X-BAPI-TIMESTAMP': '1695083257879',
   'X-BAPI-RECV-WINDOW': '5000',
   'X-BAPI-SIGN': '841eb5f95ad96a111daf09d4d2b3ba6c75082f6eb43eec99e4415fac008e3d4d'
 } 
 RequestBody:
  undefined 
 
⚠  External network resource requested!
   - URL: "https://api-testnet.bybit.com/v5/account/wallet-balance?accountType=UNIFIED"
 - Be careful, this may be a production service.
 handleRestResponse:
  bybit GET https://api-testnet.bybit.com/v5/account/wallet-balance?accountType=UNIFIED 404 Not Found 
 ResponseHeaders:
  {
   Connection: 'keep-alive',
   'Content-Length': '0',
   'Content-Type': 'application/json; charset=utf-8',
   Date: 'Tue, 19 Sep 2023 00:27:38 GMT',
   Server: 'Openresty',
   Timenow: '1695083258138',
   Traceid: '307b80e5025b351e1b06b98dc420e1de',
   Via: '1.1 28bff9aefde24bd849ea5665101cb2d6.cloudfront.net (CloudFront)',
   'X-Amz-Cf-Id': 'wrcaVgItgrd1-kXSkS40_D9DB1G9YIQKVqeFBWBwxLxPkyThRLpRiw==',
   'X-Amz-Cf-Pop': 'KIX56-C1',
   'X-Cache': 'Error from cloudfront'
 } 
 ResponseBody:

### Code

```
bybit = ccxt.bybit({
'type': {'defaultType': 'unified'},
'enableRateLimit': True,
'apiKey': API_KEY,
'secret': API_SECRET
})
bybit.fetchBalance()

```

**Comment by sc0Vu** [comment]
Hi @bongkook 

I think your api account is not UTA. Would you like to validate by calling `privateGetV5UserQueryApi` and see the 'uta' value?

**Comment by bongkook** [comment]
Thank you for your reply.
I checked and it was a regular account.

**Comment by bongkook** [comment]
I solved it.
thank you so much.
