### ISSUE TITLE
Fetching orderbook data of all market at once

### ISSUE THREAD

**Issue by l0urdm** [ccxt/ccxt#1933]
- OS: Win10
- Programming Language version: Python 2.7.14
- CCXT version: 1.10.1
- Exchange: Cryptopia
- Method: fetch_order_book

I am looking for a way to fetch the best bid and ask price and amount for all markets:

I changed this 
orderbook = exchange.fetch_order_book (exchange.symbols[0])

to this one to get the orderbook details for all markets
orderbook = cryptopia.fetch_order_book (cryptopia.symbols[0])

but I get this error: TypeError: 'NoneType' object has no attribute '__getitem__'

is there a way to fetch this data for all markets in one go?

**Comment by kroitor** [comment]
Your question has been answered here: #1930
