### ISSUE TITLE
AttributeError: 'bybit' object has no attribute 'parseContractOrder'

### ISSUE THREAD

**Issue by arrabyte** [ccxt/ccxt#19339]
### Operating System

Linux Ubuntu 20.04

### Programming Languages

Python

### CCXT Version

4.0.101 (4.0.100, 4.0.99)

### Description

Hi, I'm using ccxt (latest version) to place a limit order and the ccxt api watch_orders  to receive order update by websocket.
The watch_orders  fails to get order status and return this error:  AttributeError: 'bybit' object has no attribute 'parseContractOrder'
The strange thing is that days ago ( 2023/9/18 )  the problem did not appear. 
I tried to revert ccxt version to older, but nothing to do. The versions I tried are : 4.0.100 and 4.0.99.
Then I tied to revert to a ccxt version that does not use Bybit Api V5 and I install ccxt version 3.1.60 and te watch_order function well.
I guess that on date 2023/9/18 bybit make some changes to the v5 Api that involve watch_orders API.
The problem happens also using the bybit testnet.
The code is just a snapshot of the application that is used to reproduce the problem.
The test place an order of BTC/USDT perpetual ( One-Way Mode is required for the code below otherwise you should uncomment positionIdx).

Callstack:
An error occurred: 'bybit' object has no attribute 'parseContractOrder'
Future exception was never retrieved
future: <Future finished exception=AttributeError("'bybit' object has no attribute 'parseContractOrder'")>
Traceback (most recent call last):
  File "/home/alex/.local/lib/python3.8/site-packages/ccxt/async_support/base/ws/fast_client.py", line 27, in handler
    self.handle_message(message)
  File "/home/alex/.local/lib/python3.8/site-packages/ccxt/async_support/base/ws/aiohttp_client.py", line 32, in handle_message
    self.handle_text_or_binary_message(message.data)
  File "/home/alex/.local/lib/python3.8/site-packages/ccxt/async_support/base/ws/aiohttp_client.py", line 27, in handle_text_or_binary_message
    self.on_message_callback(self, decoded)
  File "/home/alex/.local/lib/python3.8/site-packages/ccxt/pro/bybit.py", line 1534, in handle_message
    exacMethod(client, message)
  File "/home/alex/.local/lib/python3.8/site-packages/ccxt/pro/bybit.py", line 999, in handle_order
    parsed = getattr(self, parser)(rawOrders[i])
AttributeError: 'bybit' object has no attribute 'parseContractOrder'
An error occurred: 'bybit' object has no attribute 'parseContractOrder'

### Code

```
import ccxt
import ccxt.pro
import asyncio

# Initialize the exchange object for Bybit testnet
exchange = ccxt.bybit({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
    'enableRateLimit': True,
})

# Enable the testnet mode for Bybit
exchange.set_sandbox_mode(True)

  
# Function to place an order with take profit and stop loss
async def place_order(symbol, side, entry_price, quantity, take_profit_price, stop_loss_price):
    global order_timestamps
    try:        
        hedge_mode = True
        # check if mode is hedges
        position_idx = (1 if side == "buy" else 2) if hedge_mode else 0

        # Create an OCO order with a take profit and stop loss        
        order = await exchange.create_limit_order(
            symbol,
            side,
            quantity,
            entry_price,
            {
                'stopLoss': stop_loss_price,
                'takeProfit': take_profit_price,
                #'positionIdx' : position_idx,
            },            
        )
                
        # Return the order object
        return order

    except ccxt.NetworkError as e:
        print(f"Network error: {e}")
    except ccxt.InsufficientFunds as e:
        print(f"InsufficientFunds error: {e}")
    except ccxt.ExchangeError as e:
        print(f"Exchange error: {e}")
    except Exception as e:
        print(f"An error occurred: {e}")

      
# Function to fetch order book data and make trading decisions with order book depth analysis
async def make_trading_decision(symbol):
  
    trade_amount = 100  # Replace with your fixed USDT amount
    take_profit_pct = 0.006  # Set your desired take profit percentage
    stop_loss_pct = 0.005  # Set your desired stop loss percentage    
    side = 'buy'
    
    try:

        # Fetch order book data
        order_book = await exchange.fetch_order_book(symbol)

        best_bid = order_book['bids'][0][0]
        best_ask = order_book['asks'][0][0]

        # Calculate the spread threshold as a percentage of the current price
        entry_price = best_bid 
        quantity = trade_amount / entry_price
        
        # Calculate take profit and stop loss prices
        take_profit_price = entry_price * (1 + take_profit_pct)
        stop_loss_price = entry_price * (1 - stop_loss_pct)

        # Place the limit order with take profit and stop loss
        order = await place_order(symbol, side, entry_price, quantity, take_profit_price, stop_loss_price)
        print(f"{side.capitalize()} trade entered for {symbol} at {entry_price}, Quantity: {quantity:.4f} {symbol.split('/')[0]}")
        print(f"Take Profit: {take_profit_price}, Stop Loss: {stop_loss_price}")

    except ccxt.NetworkError as e:
        print(f"Network error: {e}")
    except ccxt.ExchangeError as e:
        print(f"Exchange error: {e}")
    except Exception as e:
        print(f"An error occurred: {e}")      
      
# Function to monitor orders and watch their trades asynchronously
async def monitor_orders():    
    while True:
        try:
          orders = await exchange.watch_orders()
                     
          for order in orders:
                print(f'receive trade notify: {order}')

        except ccxt.NetworkError as e:
            print(f"Network error: {e}")
            #return {}
        except ccxt.ExchangeError as e:
            print(f"Exchange error: {e}")
            #return {}
        except Exception as e:
            print(f"An error occurred: {e}")
            #return {}
    
        
async def main():
  # Start the order monitoring function concurrently
  asyncio.create_task(monitor_orders())    

  await make_trading_decision('BTC/USDT:USDT')

  # Initialize the list of symbols to trade by fetching available tokens
  while True:

      # strategy loop

      # Add a delay between trading decisions (adjust as needed)
      await asyncio.sleep(10)
      

asyncio.get_event_loop().run_until_complete(main())
```

**Comment by carlosmiei** [comment]
Hello @arrabyte, we did a major upgrade on the REST side (v5 migration) that could have impacted the WS connector. Thanks for letting us know will take a look asap.
