### ISSUE TITLE
Bitvavo - Amount Parameter is invalid 

### ISSUE THREAD

**Issue by domantaskudzius** [ccxt/ccxt#19346]
### Operating System

Ubuntu

### Programming Languages

Python

### CCXT Version

4.0.80

### Description

For some reason, Bitvavo keeps throwing "amount parameter is invalid" despite using the correct amount?

1. amount = exchange.amount_to_precision("XRP/EUR", 69.94286835208308)
2.  "Placing Buy Order for XRP/EUR, qty: 69.94286835, price: 0.49019"
3.  InvalidOrder {"errorCode":205,"error":"amount parameter is invalid."}

I am not sure why this is happening considering I am using the CCXT function to format the amount. Precision for XRP/EUR on Bitvavo is 8 as well per CCXT.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @domantaskudzius,
can you please share the code used and a verbose log? (`exchange.verbose = True`)

**Comment by loren721** [comment]
what can i do for you

**Comment by domantaskudzius** [comment]
> Hello @domantaskudzius, can you please share the code used and a verbose log? (`exchange.verbose = True`)

Sure

```
exchange_class = getattr(ccxt, 'bitvavo')

exchange_dict = {
    'apiKey': api_key,
    'secret': api_secret,
    'timeout': 30000,
    'enableRateLimit': True
}

exchange = exchange_class(exchange_dict)
exchange.verbose = True
exchange.load_markets()
symbol = "XRP/EUR"
amount = exchange.amount_to_precision(symbol, "69.94286835208308")
order = exchange.create_order(symbol=symbol, type="limit", side="buy", amount=amount, price=0.481)
```

Logs (removed assets' response due to being overwhelming in size):

> fetch Request: bitvavo GET https://api.bitvavo.com/v2/assets RequestHeaders: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

> fetch Response: bitvavo GET https://api.bitvavo.com/v2/assets 200 ResponseHeaders: {'Date': 'Fri, 22 Sep 2023 10:46:31 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'access-control-allow-origin': '*', 'strict-transport-security': 'max-age=15552000; includeSubDomains; preload', 'bitvavo-ratelimit-limit': '1000', 'bitvavo-ratelimit-remaining': '997', 'bitvavo-ratelimit-resetat': '1695379620000', 'etag': 'W/"d181-pX3fjv9K4Uale9ZOdSxp3pZcPU4"', 'x-envoy-upstream-service-time': '17', 'CF-Cache-Status': 'DYNAMIC', 'Set-Cookie': '__cf_bm=vnBU_euefPj28_5QbNoKXyqfKLgAj62nY583pQrqNiA-1695379591-0-AVXU0yRx4R6JZVWgyYTtG7E/xf3uPPVUobvaqfg9/EsW04FFWFR7Sag4S2sEq2/4mLNxhkfHTeT+lphyx1/AV78=; path=/; expires=Fri, 22-Sep-23 11:16:31 GMT; domain=.bitvavo.com; HttpOnly; Secure; SameSite=None', 'Server': 'cloudflare', 'CF-RAY': '80a9f6ec99b6b7ca-AMS', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400'} 

> fetch Request: bitvavo GET https://api.bitvavo.com/v2/markets RequestHeaders: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

> fetch Response: bitvavo GET https://api.bitvavo.com/v2/markets 200 ResponseHeaders: {'Date': 'Fri, 22 Sep 2023 10:46:31 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'access-control-allow-origin': '*', 'strict-transport-security': 'max-age=15552000; includeSubDomains; preload', 'bitvavo-ratelimit-limit': '1000', 'bitvavo-ratelimit-remaining': '996', 'bitvavo-ratelimit-resetat': '1695379620000', 'etag': 'W/"14675-sNZCiSnJf7t7ANfFPEjFSR0AW9k"', 'x-envoy-upstream-service-time': '4', 'CF-Cache-Status': 'DYNAMIC', 'Set-Cookie': '__cf_bm=CPDh9UfqIgvbh_CjCsK_1Oz7WqCb_ZfPC8xVo38LXlU-1695379591-0-AcSKIFVrhZ5BFsTiRLNMdd9RaFTCK9bjb2JHRw5CeF4uFMIMFQ2p43Gh78jhlHz7Av5HG8d6mMrrfWnW0WjVZT4=; path=/; expires=Fri, 22-Sep-23 11:16:31 GMT; domain=.bitvavo.com; HttpOnly; Secure; SameSite=None', 'Server': 'cloudflare', 'CF-RAY': '80a9f6ecfa1cb7ca-AMS', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400'}

> fetch Request: bitvavo POST https://api.bitvavo.com/v2/order RequestHeaders: {'BITVAVO-ACCESS-KEY': '-', 'BITVAVO-ACCESS-SIGNATURE': '-', 'BITVAVO-ACCESS-TIMESTAMP': '1695379591312', 'BITVAVO-ACCESS-WINDOW': '10000', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"market":"XRP-EUR","side":"buy","orderType":"limit","price":"0.481","amount":"69.94286835"}

> fetch Response: bitvavo POST https://api.bitvavo.com/v2/order 400 ResponseHeaders: {'Date': 'Fri, 22 Sep 2023 10:46:31 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '56', 'Connection': 'keep-alive', 'access-control-allow-origin': '*', 'strict-transport-security': 'max-age=15552000; includeSubDomains; preload', 'bitvavo-ratelimit-limit': '1000', 'bitvavo-ratelimit-remaining': '998', 'bitvavo-ratelimit-resetat': '1695379620000', 'etag': 'W/"38-b/5iyfkKYFQ4bwQcfZuS3KoxS/k"', 'x-envoy-upstream-service-time': '35', 'CF-Cache-Status': 'DYNAMIC', 'Set-Cookie': '__cf_bm=SldGjQG5uLxT5JC.6N97BdMzEshu3dgwttGI_DWVPg4-1695379591-0-AaD+d5Y4uk3LXOfmOlByw0rB1aMiS/rsZ8z2hJ/0uE4eWwoZ2AerIb6EmVmz98dUuybnPoAVUnfpCg+LSals/AQ=; path=/; expires=Fri, 22-Sep-23 11:16:31 GMT; domain=.bitvavo.com; HttpOnly; Secure; SameSite=None', 'Server': 'cloudflare', 'CF-RAY': '80a9f6edbad7b7ca-AMS', 'alt-svc': 'h3=":443"; ma=86400'} ResponseBody: {"errorCode":205,"error":"amount parameter is invalid."}

> Traceback (most recent call last):
>   File "/home/server/.cache/pypoetry/virtualenvs/pyenv-py3.8/lib/python3.8/site-packages/ccxt/base/exchange.py", line 610, in fetch
>     response.raise_for_status()
>   File "/home/server/.cache/pypoetry/virtualenvs/pyenv-py3.8/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.bitvavo.com/v2/order
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "fix_balances.py", line 58, in <module>
>     order = exchange.create_order(symbol=symbol, type="limit", side="buy", amount=amount, price=0.481)
>   File "/home/server/.cache/pypoetry/virtualenvs/pyenv-py3.8/lib/python3.8/site-packages/ccxt/bitvavo.py", line 1016, in create_order
>     response = self.privatePostOrder(self.extend(request, params))
>   File "/home/server/.cache/pypoetry/virtualenvs/pyenv-py3.8/lib/python3.8/site-packages/ccxt/base/types.py", line 26, in unbound_method
>     return _self.request(self.path, self.api, self.method, params, config=self.config)
>   File "/home/server/.cache/pypoetry/virtualenvs/pyenv-py3.8/lib/python3.8/site-packages/ccxt/base/exchange.py", line 3051, in request
>     return self.fetch2(path, api, method, params, headers, body, config)
>   File "/home/server/.cache/pypoetry/virtualenvs/pyenv-py3.8/lib/python3.8/site-packages/ccxt/base/exchange.py", line 3048, in fetch2
>     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
>   File "/home/server/.cache/pypoetry/virtualenvs/pyenv-py3.8/lib/python3.8/site-packages/ccxt/base/exchange.py", line 626, in fetch
>     skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
>   File "/home/server/.cache/pypoetry/virtualenvs/pyenv-py3.8/lib/python3.8/site-packages/ccxt/bitvavo.py", line 1780, in handle_errors
>     self.throw_broadly_matched_exception(self.exceptions['broad'], error, feedback)
>   File "/home/server/.cache/pypoetry/virtualenvs/pyenv-py3.8/lib/python3.8/site-packages/ccxt/base/exchange.py", line 3419, in throw_broadly_matched_exception
>     raise broad[broadKey](message)
> ccxt.base.errors.InvalidOrder: bitvavo {"errorCode":205,"error":"amount parameter is invalid."}
