### ISSUE TITLE
Bitget fetch_ohlcv returns errors since last update on pip ccxt 4.0.101

### ISSUE THREAD

**Issue by tty666** [ccxt/ccxt#19340]
### Operating System

Mac OS using Conda

### Programming Languages

python 3.8.16

### CCXT Version

4.0.101

### Description

a relatively simple script I use to test the ccxt API for my trading bot (which is more complex) reports now errors and it was working perfectly before.

The error encountered is :

```
Traceback (most recent call last):
  File "test_api_ccxt.py", line 42, in <module>
    main()
  File "test_api_ccxt.py", line 37, in main
    df = get_candlestick_data(symbol, timeframe)
  File "test_api_ccxt.py", line 19, in get_candlestick_data
    ohlcv = bitget.fetch_ohlcv(symbol, timeframe, limit=200)
  File "/Users/tty666/miniforge3/envs/finRL/lib/python3.8/site-packages/ccxt/bitget.py", line 2487, in fetch_ohlcv
    data = self.safe_value(response, 'data', response)
  File "/Users/tty666/miniforge3/envs/finRL/lib/python3.8/site-packages/ccxt/base/exchange.py", line 748, in safe_value
    return dictionary[key] if Exchange.key_exists(dictionary, key) else default_value
  File "/Users/tty666/miniforge3/envs/finRL/lib/python3.8/site-packages/ccxt/base/exchange.py", line 680, in key_exists
    value = dictionary[key]
TypeError: byte indices must be integers or slices, not str
```

### Code

```
import os
import ccxt
import pandas as pd

# Liste des timeframes souhaités
#TIMEFRAMES = ['1m', '5m', '15m', '30m', '1h', '4h', '6h', '12h', '1d', '3d', '1w', '1M']
TIMEFRAMES = ['5m', '15m', '30m']

# Initialisation de l'échange Bitget
bitget = ccxt.bitget()

def get_spot_pairs():
    markets = bitget.fetch_markets()
    spot_pairs = [market['symbol'] for market in markets if market['type'] == 'spot' and market['symbol'].endswith('USDT')]
    return spot_pairs

def get_candlestick_data(symbol, timeframe):
    try:
        ohlcv = bitget.fetch_ohlcv(symbol, timeframe, limit=200)
        #print(ohlcv)
        df = pd.DataFrame(ohlcv, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
        return df
    except ccxt.ExchangeError:
        print(f"Failed to fetch data for {symbol} at {timeframe} timeframe.")
        return None

def main():
    spot_pairs = get_spot_pairs()
    for symbol in spot_pairs:
        directory = f"./bitget_test_spot/{symbol.replace('/', '_')}"  # Remplacez les '/' par '_' pour éviter les problèmes de dossier
        if not os.path.exists(directory):
            os.makedirs(directory)

        for timeframe in TIMEFRAMES:
            # Ajout d'une condition pour renommer le 1M en 1month
            file_timeframe = '1month' if timeframe == '1M' else timeframe
            df = get_candlestick_data(symbol, timeframe)
            if df is not None:
                df.to_csv(f"{directory}/{file_timeframe}.csv", index=False)

if __name__ == "__main__":
    main()

```

**Comment by carlosmiei** [comment]
Hello @tty666, 
I can't reproduce this issue, can you please specify the exact symbol and timeframe used?

**Comment by tty666** [comment]
Hello @carlosmiei 

timeframes are into the table : 5m, 15m, 30m (and the error reproduces for each timeframes because if I catch with an exception :

(finRL) tty666@MacBook-Pro-de-Emmanuel finRL-bitget % python test_api_ccxt.py           
An unexpected error occurred: byte indices must be integers or slices, not str
An unexpected error occurred: byte indices must be integers or slices, not str
An unexpected error occurred: byte indices must be integers or slices, not str

It happens 3 times ...
So for each timeframes.
for the symbols I collect all spot symbols :

def get_spot_pairs():
    markets = bitget.fetch_markets()
    spot_pairs = [market['symbol'] for market in markets if market['type'] == 'spot' and market['symbol'].endswith('USDT')]
    return spot_pairs

**Comment by carlosmiei** [comment]
@tty666 I will need more details because locally, it works as expected. Can you pinpoint the symbol causing the issue?

```
p bitget fetchOHLCV "ADA/USDT" 15m None 2 
Python v3.10.9
CCXT v4.0.101
bitget.fetchOHLCV(ADA/USDT,15m,None,2)
[[1695205800000, 0.251841, 0.251903, 0.251299, 0.251753, 46204.565],
 [1695206700000, 0.251753, 0.252062, 0.251707, 0.252062, 5892.977]]
```
```
 p bitget fetchOHLCV "ADA/USDT" 5m None 2 
Python v3.10.9
CCXT v4.0.101
bitget.fetchOHLCV(ADA/USDT,5m,None,2)
[[1695206400000, 0.251689, 0.251903, 0.251689, 0.251753, 15608.538],
 [1695206700000, 0.251753, 0.252062, 0.251707, 0.251938, 9131.16]]
```

**Comment by tty666** [comment]
caught it : 

@carlosmiei 
symbol : MCADE/USDT, An unexpected error occurred: byte indices must be integers or slices, not str
symbol : MCADE/USDT, An unexpected error occurred: byte indices must be integers or slices, not str
symbol : MCADE/USDT, An unexpected error occurred: byte indices must be integers or slices, not str

**Comment by tty666** [comment]
@carlosmiei 
I have another context where it causes the same issue with the same symbol :

```
Unexpected error occurred: object of type 'StreamReader' has no len()
Unexpected error occurred: object of type 'StreamReader' has no len()
Unexpected error occurred: object of type 'StreamReader' has no len()
Skipping MCADE/USDT - 5m: Insufficient data (less than 35 candles)
Skipping MCADE/USDT - 15m: Insufficient data (less than 35 candles)
Skipping MCADE/USDT - 30m: Insufficient data (less than 35 candles)
```

but in this case it comes into a "more complex" environment as it is asyncio bot data collection (not a simple test script) :


```
    async def fetch_and_save_data(self, symbol, timeframe, last_timestamp=None, initial_collection=True, check_data_length=True):
        async with self.semaphore:
            await self.bitget.sleep(0.05)
            try:
                retry_limit = 3
                retry_count = 0
                while retry_count < retry_limit:
                    try:
                        candles = await self.bitget.fetch_ohlcv(symbol, timeframe, limit=200)
                        if last_timestamp is not None:
                            candles = [candle for candle in candles if candle[0] > last_timestamp]
    
                        directory_path = os.path.join(self.output_folder, symbol.replace('/', '_').replace(':USDT',''))
                        filename = f"{directory_path}/{timeframe}.csv"
    
                        if os.path.isfile(filename):
                            existing_data = pd.read_csv(filename)
                            data = [[int(candle[0])] + candle[1:] for candle in candles]
                            new_data = pd.DataFrame(data, columns=existing_data.columns)
                            existing_data = pd.concat([existing_data, new_data], ignore_index=True).drop_duplicates(subset=['timestamp'])
                            
                            # Check if the updated data has sufficient length
                            if check_data_length and len(existing_data) < 35:
                                print(f"Insufficient data for {symbol} - {timeframe}. Deleting folder.")
                                if os.path.exists(directory_path):
                                    shutil.rmtree(directory_path)
                                return
                                
                            existing_data.to_csv(filename, index=False, float_format='%.15f')
                        else:
                            if check_data_length and (not candles or len(candles) < 35):
                                print(f"Skipping {symbol} - {timeframe}: Insufficient data (less than 35 candles)")
                                if os.path.exists(directory_path):
                                    shutil.rmtree(directory_path)
                                return
                                
                            data = [[int(candle[0])] + candle[1:] for candle in candles]
                            initial_df = pd.DataFrame(data, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
                            os.makedirs(os.path.dirname(filename), exist_ok=True)
                            initial_df.to_csv(filename, index=False, float_format='%.15f')
    
                        break
                    except ccxt_async.ExchangeError as e:
                        error_message = str(e)
                        if '"code":"40309","msg":"The symbol has been removed"' in error_message:
                            print(f"The symbol {symbol} - {timeframe} has been removed. Skipping.")
                            return
                        print(f"Error fetching data for {symbol} - {timeframe}: {e}")
                        retry_count += 1
                        if retry_count < retry_limit:
                            print(f"Retrying ({retry_count}/{retry_limit})...")
                            await asyncio.sleep(5)
                        else:
                            print("Retry limit reached. Aborting.")
            except Exception as e:
                print(f"Unexpected error occurred: {e}")
```

My guess is the initial problem is the same, maybe the symbol isn't fully published yet by bitget and cause this trouble ... but then maybe the internal ccxt functions should tackle it in another way to avoid errors in such cases.

**Comment by carlosmiei** [comment]
@tty666 still can't reproduce,  can you enable the verbose mode (`exchange.verbose = True` before fetch_ohlcv) and share the log with us?

```
 p bitget fetchOHLCV "MCADE/USDT" 15m None 200 
Python v3.10.9
CCXT v4.0.101
bitget.fetchOHLCV(MCADE/USDT,15m,None,200)
[[1695207600000, 0.0045, 0.012029, 0.0045, 0.009216, 5276697.2],
 [1695208500000, 0.009216, 0.0096, 0.009169, 0.00925, 3511793.77],
 [1695209400000, 0.00925, 0.01, 0.0092, 0.009998, 3531729.68],
 [1695210300000, 0.009998, 0.0104, 0.009282, 0.009425, 2790596.52],
 [1695211200000, 0.009425, 0.009996, 0.009345, 0.009538, 217354.55],
 [1695212100000, 0.009538, 0.009538, 0.009359, 0.009404, 25810.46]]
```
```
 p bitget fetchOHLCV "MCADE/USDT" 30m None     
Python v3.10.9
CCXT v4.0.101
bitget.fetchOHLCV(MCADE/USDT,30m,None)
[[1695207600000, 0.0045, 0.012029, 0.0045, 0.00925, 8788490.97],
 [1695209400000, 0.00925, 0.0104, 0.0092, 0.009425, 6322326.2],
 [1695211200000, 0.009425, 0.009996, 0.009345, 0.009412, 246375.69]
```

**Comment by tty666** [comment]
@carlosmiei let's wait a new token published, if the error pop up again I will adapt the testing script (new symbol) to catch it with verbose=True

**Comment by tty666** [comment]
@carlosmiei 

Again, new symbol, same problem :

symbol : PYUSD/USDT, An unexpected error occurred: byte indices must be integers or slices, not str
symbol : PYUSD/USDT, An unexpected error occurred: byte indices must be integers or slices, not str
symbol : PYUSD/USDT, An unexpected error occurred: byte indices must be integers or slices, not str

and here is the verbose output I caught :

fetch Request: bitget GET https://api.bitget.com/api/spot/v1/market/candles?symbol=PYUSDUSDT_SPBL&limit=200&period=5min RequestHeaders: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bitget GET https://api.bitget.com/api/spot/v1/market/candles?symbol=PYUSDUSDT_SPBL&limit=200&period=5min 200 ResponseHeaders: {'Date': 'Thu, 21 Sep 2023 08:02:09 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'X-Request-ID': '65719acccc214e48b57097491ca7c7c1', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS', 'CF-Cache-Status': 'DYNAMIC', 'Set-Cookie': '__cf_bm=bymVjpj7aPd21LGN6jQ8ZqH9YVhn0q0WfAip5Sl8k20-1695283329-0-AXQ3L3qKAYqhcfBlXgbF/AiANUlWMjMdC62rM4/S3WrOuxK+35axBD4R4ZueDA9CCpNW66/SQN0h/V3QpE+oMUg=; path=/; expires=Thu, 21-Sep-23 08:32:09 GMT; domain=.bitget.com; HttpOnly; Secure; SameSite=None, _cfuvid=IdR263GeVIFDmnWhHRyNt0USbJvwjbQGupIEwfGFOn0-1695283329114-0-604800000; path=/; domain=.bitget.com; HttpOnly; Secure; SameSite=None', 'X-Frame-Options': 'SAMEORIGIN', 'Server': 'cloudflare', 'CF-RAY': '80a0c8c55f9283db-BRU'} ResponseBody: 
symbol : PYUSD/USDT, An unexpected error occurred: byte indices must be integers or slices, not str

fetch Request: bitget GET https://api.bitget.com/api/spot/v1/market/candles?symbol=PYUSDUSDT_SPBL&limit=200&period=15min RequestHeaders: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bitget GET https://api.bitget.com/api/spot/v1/market/candles?symbol=PYUSDUSDT_SPBL&limit=200&period=15min 200 ResponseHeaders: {'Date': 'Thu, 21 Sep 2023 08:02:09 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'X-Request-ID': 'a1ca4f2d397f498d9e1be4294ca7231f', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS', 'CF-Cache-Status': 'DYNAMIC', 'Set-Cookie': '__cf_bm=k2BZiKnLcZOY7yedVvpcHX6clF9EtLt3WM31oukfMqo-1695283329-0-AZJxdbUea3wAVLQTcIslLIXxkoGK1+2WCqZXiy6LlkP/tStmqaPNlHn2FKiXAHfLk+dJCZPXbxMmFBKrAjv2rfA=; path=/; expires=Thu, 21-Sep-23 08:32:09 GMT; domain=.bitget.com; HttpOnly; Secure; SameSite=None, _cfuvid=xeZvMKfcSyrfDKvkmWmg0GZJ1kwSdSQQSTYUliVAbIk-1695283329393-0-604800000; path=/; domain=.bitget.com; HttpOnly; Secure; SameSite=None', 'X-Frame-Options': 'SAMEORIGIN', 'Server': 'cloudflare', 'CF-RAY': '80a0c8c70aa583db-BRU'} ResponseBody: 
symbol : PYUSD/USDT, An unexpected error occurred: byte indices must be integers or slices, not str

fetch Request: bitget GET https://api.bitget.com/api/spot/v1/market/candles?symbol=PYUSDUSDT_SPBL&limit=200&period=30min RequestHeaders: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bitget GET https://api.bitget.com/api/spot/v1/market/candles?symbol=PYUSDUSDT_SPBL&limit=200&period=30min 200 ResponseHeaders: {'Date': 'Thu, 21 Sep 2023 08:02:09 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'X-Request-ID': '670f18dd886b479986a958bbc42b9101', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS', 'CF-Cache-Status': 'DYNAMIC', 'Set-Cookie': '__cf_bm=Wfh0.GkGHp.XPqoBV1_wF2huPL6q.ANUg40Tt2z56SE-1695283329-0-Ab8SAUUYmQxYMnU1UyhSQ0x/BvS47dSDnrZnr1KPByUhwXXr0MuDA56gz69JO8+Wr2Yjc5KkD+4UYkPdv3yaaQ8=; path=/; expires=Thu, 21-Sep-23 08:32:09 GMT; domain=.bitget.com; HttpOnly; Secure; SameSite=None, _cfuvid=tsoVhgmE7fg3pgiRJzOcFgZaHWcgYlBpPvYKLxrVHvs-1695283329696-0-604800000; path=/; domain=.bitget.com; HttpOnly; Secure; SameSite=None', 'X-Frame-Options': 'SAMEORIGIN', 'Server': 'cloudflare', 'CF-RAY': '80a0c8c8ce8b83db-BRU'} ResponseBody: 
symbol : PYUSD/USDT, An unexpected error occurred: byte indices must be integers or slices, not str

**Comment by tty666** [comment]
It looks like the response body in such case is "empty" which could then lead to improper data structure creation like a dictionary empty or a table  or whatever else as substitution of the correct data structure to handle and parse the answer for API.

**Comment by carlosmiei** [comment]
@tty666 I can see it now, thanks! Will update it to return an empty array when that happens (instead of crashing)
