### ISSUE TITLE
Load_markets reports as 'active' a symbol pair that is not active at Binance.com 

### ISSUE THREAD

**Issue by csotto** [ccxt/ccxt#19369]
### Operating System

ALl

### CCXT Version

'4.0.104'

### Description

I just want to inform that load_markets reports as 'active'  the symbol pair FTT/USDT while this pair is not active at the BINANCE.COM exchange.

(Pdb) ccxt.__version__
'4.0.104'
(Pdb) pprint(markets['FTT/USDT'])
{'active': True,   <---
 'base': 'FTT',
 'baseId': 'FTT',
 'contract': False,
 'contractSize': None,
 'expiry': None,
 'expiryDatetime': None,
 'feeSide': 'get',
 'future': False,
 'id': 'FTTUSDT',
....
 

### Code

```
(Pdb) ccxt.__version__
'4.0.104'
(Pdb) pprint(markets['FTT/USDT'])
{'active': True,   <---
 'base': 'FTT',
 'baseId': 'FTT',
 'contract': False,
 'contractSize': None,
 'expiry': None,
 'expiryDatetime': None,
 'feeSide': 'get',
 'future': False,
 'id': 'FTTUSDT',
```

**Comment by pcriadoperez** [comment]
Hi @csotto , unfortunately this looks like an error from binance as their api says that FTT is currently trading. Here is the response from binance api:
```
{"symbol":"FTTUSDT","status":"TRADING","baseAsset":"FTT","baseAssetPrecision":8,"quoteAsset":"USDT","quotePrecision":8...
```

**Comment by csotto** [comment]
OK. I got it. I try to post on Binance. 
Thanls.
