### ISSUE TITLE
Bybit V5 - buggy stoploss behavior

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#19362]
### Operating System

linux

### Programming Languages

Python

### CCXT Version

4.0.101

### Description

Creating a stop-order on bybit futures now requires a slightly different paremter (we used to use `stopPrice` -  which is now triggering a "params error: TriggerDirection invalid" error.

Now adopting this to stopLossPrice is not a problem - but if i create an order with stopLossPrice, i'd expect to get this same price back.
Unfortunately, that's not the case, and stopLossPrice fails to parse.

``` python
import ccxt
exchange = ccxt.bybit({
    'apiKey': '<yourApiKey>', 
    'secret': '<yoursecret>', 
    'options': {'defaultType': 'swap'} 
    })
pair = 'ETH/USDT:USDT'
params = {
    'stopPrice': 1401,
}

# o = exchange.create_order(pair, 'limit', 'sell', amount=0.01, price=1401, params=params)
# Exception (see below detail block) for output

# Moving on
params = {
    'stopLossPrice': 1401,
}

o = exchange.create_order(pair, 'limit', 'sell', amount=0.01, price=1401, params=params)
o

exchange.fetch_order(o['id'], pair)

```

### Output

<details><summary>Exception output ... </summary>
<p>

```

fetch Request: bybit POST https://api.bybit.com/v5/order/create RequestHeaders: {'Content-Type': 'application/json', 'X-BAPI-API-KEY': '', 'X-BAPI-TIMESTAMP': '1695399145735', 'X-BAPI-RECV-WINDOW': '5000', 'X-BAPI-SIGN': '', 'Referer': 'CCXT', 'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"symbol":"ETHUSDT","side":"Sell","orderType":"Limit","category":"linear","qty":"0.01","price":"1401","triggerPrice":"1401"}

fetch Response: bybit POST https://api.bybit.com/v5/order/create 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '116', 'Connection': 'keep-alive', 'Date': 'Fri, 22 Sep 2023 16:12:26 GMT', 'Ret_code': '10001', 'Cache-Control': 'no-store', 'Traceid': 'e76f7b0639c9a53d8714e1f1415b7c3c', 'Timenow': '1695399146142', 'Server': 'Openresty', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 387adc951beb5181d840dfb5d1f09488.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'FRA56-P4', 'X-Amz-Cf-Id': '=='} ResponseBody: {"retCode":10001,"retMsg":"params error: TriggerDirection invalid","result":{},"retExtInfo":{},"time":1695399146142}


---------------------------------------------------------------------------
BadRequest                                Traceback (most recent call last)
[/home/xmatt/devel/cryptos/stuff/ccxt_bybit.ipynb](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/ccxt_bybit.ipynb) Cell 12 line 1
----> [1](vscode-notebook-cell:/home/xmatt/devel/cryptos/stuff/ccxt_bybit.ipynb#X14sZmlsZQ%3D%3D?line=0) o = ct.create_order(pair, 'limit', 'sell', amount=0.01, price=1401, params=params)
      [2](vscode-notebook-cell:/home/xmatt/devel/cryptos/stuff/ccxt_bybit.ipynb#X14sZmlsZQ%3D%3D?line=1) o

File [~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/bybit.py:3579](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/bybit.py:3579), in bybit.create_order(self, symbol, type, side, amount, price, params)
   3577     request['orderLinkId'] = self.uuid16()
   3578 params = self.omit(params, ['stopPrice', 'timeInForce', 'stopLossPrice', 'takeProfitPrice', 'postOnly', 'clientOrderId', 'triggerPrice', 'stopLoss', 'takeProfit'])
-> 3579 response = self.privatePostV5OrderCreate(self.extend(request, params))
   3580 #
   3581 #     {
   3582 #         "retCode": 0,
   (...)
   3590 #     }
   3591 #
   3592 order = self.safe_value(response, 'result', {})

File [~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/types.py:26](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/types.py:26), in Entry.__init__.<locals>.unbound_method(_self, params)
     25 def unbound_method(_self, params={}):
---> 26     return _self.request(self.path, self.api, self.method, params, config=self.config)

File [~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/exchange.py:3051](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/exchange.py:3051), in Exchange.request(self, path, api, method, params, headers, body, config)
   3050 def request(self, path, api: Any = 'public', method='GET', params={}, headers: Optional[Any] = None, body: Optional[Any] = None, config={}):
-> 3051     return self.fetch2(path, api, method, params, headers, body, config)

File [~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/exchange.py:3048](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/exchange.py:3048), in Exchange.fetch2(self, path, api, method, params, headers, body, config)
   3046 self.lastRestRequestTimestamp = self.milliseconds()
   3047 request = self.sign(path, api, method, params, headers, body)
-> 3048 return self.fetch(request['url'], request['method'], request['headers'], request['body'])

File [~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/exchange.py:654](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/exchange.py:654), in Exchange.fetch(self, url, method, headers, body)
    651     else:
    652         raise ExchangeError(details) from e
--> 654 self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
    655 if json_response is not None:
    656     return json_response

File [~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/bybit.py:6917](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/bybit.py:6917), in bybit.handle_errors(self, httpCode, reason, url, method, headers, body, response, requestHeaders, requestBody)
   6915         feedback = self.id + ' ' + body
   6916     self.throw_broadly_matched_exception(self.exceptions['broad'], body, feedback)
-> 6917     self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
   6918     raise ExchangeError(feedback)  # unknown message
   6919 return None

File [~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/exchange.py:3414](https://file+.vscode-resource.vscode-cdn.net/home/xmatt/devel/cryptos/stuff/~/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/ccxt/base/exchange.py:3414), in Exchange.throw_exactly_matched_exception(self, exact, string, message)
   3412 def throw_exactly_matched_exception(self, exact, string, message):
   3413     if string in exact:
-> 3414         raise exact[string](message)

BadRequest: bybit {"retCode":10001,"retMsg":"params error: TriggerDirection invalid","result":{},"retExtInfo":{},"time":1695399146142}
```

</p>
</details> 

```
-- Create order
{'info': {'orderId': 'b8273344-3013-4522-8f76-cde643747434',
  'orderLinkId': ''},
 'id': 'b8273344-3013-4522-8f76-cde643747434',
 'clientOrderId': None,
 'timestamp': None,
 'datetime': None,
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'symbol': 'ETH/USDT:USDT',
 'type': None,
 'timeInForce': None,
 'postOnly': None,
 'reduceOnly': None,
 'side': None,
 'price': None,
 'stopPrice': None,
 'triggerPrice': None,
 'takeProfitPrice': None,
 'stopLossPrice': None,
 'amount': None,
 'cost': None,
 'average': None,
 'filled': None,
 'remaining': None,
 'status': None,
 'fee': None,
 'trades': [],
 'fees': []}


--- subsequent fetch

{'info': {'orderId': 'b8273344-3013-4522-8f76-cde643747434',
  'orderLinkId': '',
  'blockTradeId': '',
  'symbol': 'ETHUSDT',
  'price': '1401.00',
  'qty': '0.01',
  'side': 'Sell',
  'isLeverage': '',
  'positionIdx': '0',
  'orderStatus': 'Untriggered',
  'cancelType': 'UNKNOWN',
  'rejectReason': 'EC_NoError',
  'avgPrice': '0',
  'leavesQty': '0.01',
  'leavesValue': '14.01',
  'cumExecQty': '0.00',
  'cumExecValue': '0',
  'cumExecFee': '0',
  'timeInForce': 'GTC',
  'orderType': 'Limit',
  'stopOrderType': 'Stop',
  'orderIv': '',
  'triggerPrice': '1401.00',
  'takeProfit': '0.00',
  'stopLoss': '0.00',
  'tpTriggerBy': 'UNKNOWN',
  'slTriggerBy': 'UNKNOWN',
  'triggerDirection': '2',
  'triggerBy': 'LastPrice',
  'lastPriceOnCreated': '0.00',
  'reduceOnly': True,
  'closeOnTrigger': False,
  'smpType': 'None',
  'smpGroup': '0',
  'smpOrderId': '',
  'tpslMode': '',
  'tpLimitPrice': '',
  'slLimitPrice': '',
  'placeType': '',
  'createdTime': '1695398854285',
  'updatedTime': '1695398854285',
  'nextPageCursor': 'page_token%3D12397685%26'},
 'id': 'b8273344-3013-4522-8f76-cde643747434',
 'clientOrderId': None,
 'timestamp': 1695398854285,
 'datetime': '2023-09-22T16:07:34.285Z',
 'lastTradeTimestamp': 1695398854285,
 'lastUpdateTimestamp': 1695398854285,
 'symbol': 'ETH/USDT:USDT',
 'type': 'limit',
 'timeInForce': 'GTC',
 'postOnly': False,
 'reduceOnly': True,
 'side': 'sell',
 'price': 1401.0,
 'stopPrice': 1401.0,
 'triggerPrice': 1401.0,
 'takeProfitPrice': None,
 'stopLossPrice': None, <-- i used this parameter to create the order - shouldn't it be filled?
 'amount': 0.01,
 'cost': 0.0,
 'average': None,
 'filled': 0.0,
 'remaining': 0.01,
 'status': 'open',
 'fee': {'cost': 0.0, 'currency': 'USDT'},
 'trades': [],
 'fees': [{'cost': 0.0, 'currency': 'USDT'}]}  

```

**Comment by Dan-krm** [comment]
This pull request removed automatically setting the triggerDirection for stopOrders but it is still automatically set for stopLossPrice and takeProfitPrice: https://github.com/ccxt/ccxt/pull/19323

On bybit setting the stopLossPrice or takeProfitPrice is the equivalent of setting the stopPrice but with the triggerDirection automatically set

In your fetch example the stopPrice and triggerPrice fields are filled and the stopLossPrice and takeProfitPrice fields would only be filled if you created an order with an attached stopLoss or takeProfit:
https://github.com/ccxt/ccxt/wiki/Manual#stoploss-and-takeprofit-orders-attached-to-a-position

Our implementation varies by exchange because often times setting the stopLossPrice is just a conditional order with a specified trigger direction and on some exchanges it's an independent stopLoss order that will be attached to a position, I'll check and see if we either want to remove stopLossPrice and takeProfitPrice functionality from Bybit or if we want to adjust our parseOrder implementation so that stopPrice, triggerPrice, stopLossPrice and takeProfitPrice all return the same value, then we could add separate stopLoss and takeProfit fields, or if we want to leave it as is

**Comment by xmatthias** [comment]
Well my expectation is that if i use one parameter (independent if it's `stopPrice` or `stopLossPrice`) - then the fetch-order corresponding to that particular order returns the same field.

If that's not the case, then that's a bug (i input one thing, and get something else out).
I understand that the usage of `stopPrice` and `stopLossPrice` in ccxt is not really standardized, and will depend on exchange.
yet for all other exchanges (i tried), creating an order with one key will fill that same element in the response.
If that's not the case, then my assumption is that either parsing is wrong - or ccxt is creating the wrong order.

**Comment by Dan-krm** [comment]
@xmatthias the reasoning for deleting that param is because it's not required and stopLossPrice and takeProfitPrice use that param so its redundant

**Comment by xmatthias** [comment]
@Dan-krm It introduced this bug.

i've hence created a PR to revert your change, which i see as buggy, introducing a bug and disconnect between creating an order and what the order returns (see explanation above).

If you think there's a different fix - more than happy to have my PR reverting your change superceded by your improvement, which fixes the bug you introduced in a different way.

**Comment by xmatthias** [comment]
> I'm not getting an error on my end

So you do create the stoploss order with `stopLossPrice` - and `stopLossPrice` is filled when you call fetchOrder?

Otherwise, you're failing to UNDERSTAND the bug in the first place.

**Comment by Dan-krm** [comment]
I can create a conditional order using stopLossPrice but since the exchange see's it as a conditional order the stopPrice and triggerPrice fields are getting populated instead of stopLossPrice in parseOrder

We can adjust parseOrder or remove stopLossPrice orders but I'm not seeing how reverting that PR fixes anything

**Comment by xmatthias** [comment]
@Dan-krm 
Reverting the PR fixes the misalignment in ccxt, which currently exists, which is that

* using `stopPrice` on futures fails
* forcing the use of `stopLossPrice`
* `fetch_order` has stopLossPrice empty (but populates `stopPrice`)

Based on your explanation, ccxt is wrong, either in how it places the order, or in how it interprets the result.

if you read very carefully, then i've never said WHICH way i see the bug / problem - all i see is a misalignment - which was introduced by that PR.

My expectation is that if i use one parameter to place the stop order (independend of WHICH parameter i use) - then i get the SAME parameter for that order back. Failing to do that is clearly a bug.

I'm more than happy to close my PR if i see a better solution from your side :) 
but so far, i didn't see anything other than ignorance or not understanding a problem from your side, therefore for now, reverting that PR is the best solution.

**Comment by carlosmiei** [comment]
Hello @xmatthias,

Thanks for your input. After some tests, I think you're right regarding the triggerDirection issue( We opened the removal PR after a report of a user that wanted to change the default `triggerDirection` value, and that was perfectly possible, so somehow we ended up concluding that it was not mandatory to set one (and I assumed the tests were made adequately, my bad). 

I can see know that without it we get the `{"retCode":10001,"retMsg":"params error: TriggerDirection invalid","result":{},"retExtInfo":{},"time":1695467076725}` error, so your PR will be merged very soon.

Regarding the `triggerPrice/stopLossPrice/takeProfitPrice` concepts, I think there's still some confusion. The `stopLossPrice/takeProfitPrice` is a CCXT concept that helps users place isolated trigger orders that will act as a takeProfit or stopLoss for an opening position. But from a pragmatic perspective, they are regular trigger Orders ( you can place a stopLossprice order to open a position if the price crosses the X value, as you would with the triggerOrder so they're basically interchangeable).

 Because of that, they end up being treated as regular trigger orders upon parsing the Order. How could we distinguish a regular trigger order from a `takeProfitPrice` or a `stopLossPrice` if they're conceptually the same? 

With that said, I don't know how we would populate the `takeProfit/stopLoss` prices inside `parseOrder`, it might be a bit confusing, but those fields are more suited to orders that have take-profit and stop-losses attached to it rather than independent trigger orders.

**Comment by xmatthias** [comment]
Unfortunately, the whole stoploss topic is a quite complex one, and seemingly one that's pretty prone to break - with parameters that work in one version suddenly breaking in the next and viceversa (the same, or in relation with parseOrder, unfortunately).

> Regarding the triggerPrice/stopLossPrice/takeProfitPrice concepts, I think there's still some confusion.

i'm not sure there is ... i know exchanges differ (sometimes quite severely) in how they treat these orders - and ccxt does a pretty good job in abstracting this.
Having different parameters per exchange is not per se a problem (the effective order-type changes too, after all).


the expectation i have is that i pass in parameter X - and i get parameter "X" back.  Y can be filled as well (so if i place the order with `stopLossPrice` - `stopPrice` might be filled in the response or viceversa). 
But i'd expect `stopLossPrice` to be filled - this is the parameter i used to place the order - which currently wasn't the case.

If that's not a base assumption i can take, i'm fine with that - but i'd need some logic that (roughly) aligns across exchanges - with this being the one that seems to make sense the most in my eyes - and which so far, seems to work across all exchanges we support stoploss on exchange for.

**Comment by carlosmiei** [comment]
@xmatthias 

> the expectation i have is that i pass in parameter X - and i get parameter "X" back. Y can be filled as well (so if i place the order with stopLossPrice - stopPrice might be filled in the response or viceversa).
But i'd expect stopLossPrice to be filled - this is the parameter i used to place the order - which currently wasn't the case.

That is a valid point, and I totally agree but it's trickier than that here. For instance, binance has dedicated isolated sl/tp orders, so if you provide `stopLossPrice` in `params`, even the type is adjusted to `STOP_LOSS_LIMIT/STOP_LOSS`, meaning that this is easily distinguishable from a regular trigger Order upon parsing it. The same does not happen with bybit, so even if you provide `create_order` with `stopLossPrice` , upon fetching it, we have no idea if that order is a regular stop order or a tp/sl order.

Take a look at the information returned by bybit:
```
0054072-62d7-4594-a626-969fa3b9f50c',
 'info': {'avgPrice': '0',
          'blockTradeId': '',
          'cancelType': 'UNKNOWN',
          'closeOnTrigger': False,
          'createdTime': '1695466788127',
          'cumExecFee': '0',
          'cumExecQty': '0.0',
          'cumExecValue': '0',
          'isLeverage': '',
          'lastPriceOnCreated': '0.00',
          'leavesQty': '0.1',
          'leavesValue': '5.6',
          'nextPageCursor': 'page_token%3D134868%26',
          'orderId': '80054072-62d7-4594-a626-969fa3b9f50c',
          'orderIv': '',
          'orderLinkId': '',
          'orderStatus': 'Untriggered',
          'orderType': 'Limit',
          'placeType': '',
          'positionIdx': '0',
          'price': '56.00',
          'qty': '0.1',
          'reduceOnly': True,
          'rejectReason': 'EC_NoError',
          'side': 'Buy',
          'slLimitPrice': '',
          'slTriggerBy': 'UNKNOWN',
          'smpGroup': '0',
          'smpOrderId': '',
          'smpType': 'None',
          'stopLoss': '0.00',
          'stopOrderType': 'Stop',
          'symbol': 'LTCUSDT',
          'takeProfit': '0.00',
          'timeInForce': 'GTC',
          'tpLimitPrice': '',
          'tpTriggerBy': 'UNKNOWN',
          'tpslMode': '',
          'triggerBy': 'LastPrice',
          'triggerDirection': '1',
          'triggerPrice': '100.00',
          'updatedTime': '1695466788127'},
```

I don't know how we could tell for sure that the `triggerPrice` value should be assigned to the `stopLossPrice` field in the unified Order structure.

**Comment by xmatthias** [comment]
> `'stopOrderType': 'Stop'` 

? (assuming if it's not a stop order).
based on the [docs](https://bybit-exchange.github.io/docs/v5/enum#stopordertype), this can have `Stop`, `StopLoss`, `TakeProfit` (and a few others ...)

**Comment by carlosmiei** [comment]
> > `'stopOrderType': 'Stop'`
> 
> ? based on the [docs](https://bybit-exchange.github.io/docs/v5/enum#stopordertype), this can have `Stop`, `StopLoss`, `TakeProfit` (and a few others ...)

@xmatthias The thing is, the order I fetched was placed using the `stopLossPrice` param that ends up being translated as a regular stop order in the request (and as you can see it has `Stop` for the `stopOrderType` ) so I'm not sure we're talking about the same type of orders here.

**Comment by xmatthias** [comment]
@carlosmiei i'm not entirely sure if the 2 orders do ACTUALLY differ (the way ccxt is placing them), or if it's ccxt's code that's causing the confusion here.

Both orders (on exchange) are identical - except for
* different trigger direction set by ccxt
* Trigger Orders enforcing `reduceOnly` (https://github.com/ccxt/ccxt/blob/2b73903f9a8310fdf4fe2ba49087b6aff80d3237/ts/src/bybit.ts#L3708)




Tested with 4.0.105

```
pair = 'ETH/USDT:USDT'


params = {
    'stopLossPrice': 1401,
    # 'stopPrice': 1401,
    'reduceOnly': True,
    # 'triggerBy': 'MarkPrice'
}
ct.verbose = True
o = ct.create_order(pair, 'limit', 'buy', amount=0.01, price=1401, params=params)
print(o)
print(ct.fetch_order(o['id'], pair))
```

<details><summary>outputs </summary>
<p>

``` 

--stopLossPrice

fetch Request: bybit POST https://api.bybit.com/v5/order/create RequestHeaders: {'Content-Type': 'application/json', 'X-BAPI-API-KEY': '', 'X-BAPI-TIMESTAMP': '1695618340968', 'X-BAPI-RECV-WINDOW': '5000', 'X-BAPI-SIGN': '', 'Referer': 'CCXT', 'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} 
RequestBody: {"symbol":"ETHUSDT","side":"Buy","orderType":"Limit","category":"linear","qty":"0.01","price":"1401","triggerDirection":1,"triggerPrice":"1801","reduceOnly":"true"}


fetch Response: bybit POST https://api.bybit.com/v5/order/create 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '141', 'Connection': 'keep-alive', 'Date': 'Mon, 25 Sep 2023 05:05:41 GMT', 'X-Bapi-Limit': '10', 'X-Bapi-Limit-Status': '9', 'X-Bapi-Limit-Reset-Timestamp': '1695618341057', 'Ret_code': '0', 'Traceid': '1d2187a63015a5a374b41887d7696ce0', 'Timenow': '1695618341059', 'Server': 'Openresty', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 82386e4e4f56a0c01411d1aea6f3fd46.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'FRA56-P4', 'X-Amz-Cf-Id': '8dP7X6J4KNzCatTTraP-VfEobTyKGKNN4LrjHq2ylgPuQFN7DXvcxA=='} 
ResponseBody: {"retCode":0,"retMsg":"OK","result":{"orderId":"a00902a1-f953-4cdf-8f30-fba4d996bde8","orderLinkId":""},"retExtInfo":{},"time":1695618341059}




{'info': {'orderId': 'a00902a1-f953-4cdf-8f30-fba4d996bde8',
  'orderLinkId': '',
  'blockTradeId': '',
  'symbol': 'ETHUSDT',
  'price': '1401.00',
  'qty': '0.01',
  'side': 'Buy',
  'isLeverage': '',
  'positionIdx': '0',
  'orderStatus': 'Untriggered',
  'cancelType': 'UNKNOWN',
  'rejectReason': 'EC_NoError',
  'avgPrice': '0',
  'leavesQty': '0.01',
  'leavesValue': '14.01',
  'cumExecQty': '0.00',
  'cumExecValue': '0',
  'cumExecFee': '0',
  'timeInForce': 'GTC',
  'orderType': 'Limit',
  'stopOrderType': 'Stop',
  'orderIv': '',
  'triggerPrice': '1801.00',
  'takeProfit': '0.00',
  'stopLoss': '0.00',
  'tpTriggerBy': 'UNKNOWN',
  'slTriggerBy': 'UNKNOWN',
  'triggerDirection': '1',
  'triggerBy': 'LastPrice',
  'lastPriceOnCreated': '0.00',
  'reduceOnly': True,
  'closeOnTrigger': False,
  'smpType': 'None',
  'smpGroup': '0',
  'smpOrderId': '',
  'tpslMode': '',
  'tpLimitPrice': '',
  'slLimitPrice': '',
  'placeType': '',
  'createdTime': '1695618341058',
  'updatedTime': '1695618341058',
  'nextPageCursor': 'page_token%3D12412661%26'},
 'id': 'a00902a1-f953-4cdf-8f30-fba4d996bde8',
 'clientOrderId': None,
 'timestamp': 1695618341058,
 'datetime': '2023-09-25T05:05:41.058Z',
 'lastTradeTimestamp': 1695618341058,
 'lastUpdateTimestamp': 1695618341058,
 'symbol': 'ETH/USDT:USDT',
 'type': 'limit',
 'timeInForce': 'GTC',
 'postOnly': False,
 'reduceOnly': True,
 'side': 'buy',
 'price': 1401.0,
 'stopPrice': 1801.0,
 'triggerPrice': 1801.0,
 'takeProfitPrice': None,
 'stopLossPrice': None,
 'amount': 0.01,
 'cost': 0.0,
 'average': None,
 'filled': 0.0,
 'remaining': 0.01,
 'status': 'open',
 'fee': {'cost': 0.0, 'currency': 'USDT'},
 'trades': [],
 'fees': [{'cost': 0.0, 'currency': 'USDT'}]}
```

```
# stopPrice
--stopPrice

fetch Request: bybit POST https://api.bybit.com/v5/order/create RequestHeaders: {'Content-Type': 'application/json', 'X-BAPI-API-KEY': '', 'X-BAPI-TIMESTAMP': '1695618379463', 'X-BAPI-RECV-WINDOW': '5000', 'X-BAPI-SIGN': '', 'Referer': 'CCXT', 'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} 
RequestBody: {"symbol":"ETHUSDT","side":"Buy","orderType":"Limit","category":"linear","qty":"0.01","price":"1401","triggerDirection":2,"triggerPrice":"1401","reduceOnly":"true"}

fetch Response: bybit POST https://api.bybit.com/v5/order/create 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '141', 'Connection': 'keep-alive', 'Date': 'Mon, 25 Sep 2023 05:06:19 GMT', 'X-Bapi-Limit': '10', 'X-Bapi-Limit-Status': '9', 'X-Bapi-Limit-Reset-Timestamp': '1695618379861', 'Ret_code': '0', 'Traceid': '3dc7a10628f540990c62b318479ae440', 'Timenow': '1695618379862', 'Server': 'Openresty', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 82386e4e4f56a0c01411d1aea6f3fd46.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'FRA56-P4', 'X-Amz-Cf-Id': 'FqfwGBtg1_Nc9flz6__WTNQ79FJCnFoS5vyEfI4-_0e0k4w6S2yVxQ=='} 
ResponseBody: {"retCode":0,"retMsg":"OK","result":{"orderId":"07d7aa32-745f-403b-b5d6-ed23a7e51a70","orderLinkId":""},"retExtInfo":{},"time":1695618379862}



{'info': {'orderId': '07d7aa32-745f-403b-b5d6-ed23a7e51a70',
  'orderLinkId': '',
  'blockTradeId': '',
  'symbol': 'ETHUSDT',
  'price': '1401.00',
  'qty': '0.01',
  'side': 'Buy',
  'isLeverage': '',
  'positionIdx': '0',
  'orderStatus': 'Untriggered',
  'cancelType': 'UNKNOWN',
  'rejectReason': 'EC_NoError',
  'avgPrice': '0',
  'leavesQty': '0.01',
  'leavesValue': '14.01',
  'cumExecQty': '0.00',
  'cumExecValue': '0',
  'cumExecFee': '0',
  'timeInForce': 'GTC',
  'orderType': 'Limit',
  'stopOrderType': 'Stop',
  'orderIv': '',
  'triggerPrice': '1401.00',
  'takeProfit': '0.00',
  'stopLoss': '0.00',
  'tpTriggerBy': 'UNKNOWN',
  'slTriggerBy': 'UNKNOWN',
  'triggerDirection': '2',
  'triggerBy': 'LastPrice',
  'lastPriceOnCreated': '0.00',
  'reduceOnly': True,
  'closeOnTrigger': False,
  'smpType': 'None',
  'smpGroup': '0',
  'smpOrderId': '',
  'tpslMode': '',
  'tpLimitPrice': '',
  'slLimitPrice': '',
  'placeType': '',
  'createdTime': '1695618379862',
  'updatedTime': '1695618379862',
  'nextPageCursor': 'page_token%3D12412663%26'},
 'id': '07d7aa32-745f-403b-b5d6-ed23a7e51a70',
 'clientOrderId': None,
 'timestamp': 1695618379862,
 'datetime': '2023-09-25T05:06:19.862Z',
 'lastTradeTimestamp': 1695618379862,
 'lastUpdateTimestamp': 1695618379862,
 'symbol': 'ETH/USDT:USDT',
 'type': 'limit',
 'timeInForce': 'GTC',
 'postOnly': False,
 'reduceOnly': True,
 'side': 'buy',
 'price': 1401.0,
 'stopPrice': 1401.0,
 'triggerPrice': 1401.0,
 'takeProfitPrice': None,
 'stopLossPrice': None,
 'amount': 0.01,
 'cost': 0.0,
 'average': None,
 'filled': 0.0,
 'remaining': 0.01,
 'status': 'open',
 'fee': {'cost': 0.0, 'currency': 'USDT'},
 'trades': [],
 'fees': [{'cost': 0.0, 'currency': 'USDT'}]}
```





</p>
</details> 

### Comparison image of the 2 "fetch" results

Results for these 2 calls are identical except for trigger direction and actual triggerPrice (both of which are due to how it's enforced in ccxt).
Also the calls themselfs are identical - obviously except for the parameters that are sent differently.


![image](https://github.com/ccxt/ccxt/assets/5024695/328b47c1-0214-4c82-a2c0-21a115f1afaa)

![image](https://github.com/ccxt/ccxt/assets/5024695/dd8e673a-d712-4979-b7f8-abf6c1cca603)

---



I tried your sample for an OCO order, too - but that seems to work entirely different - in my case, opening a position while attaching the 2 orders - but never _actually_ giving me the order id (s) for the OCO order - only for the initial order we placed (that seems to be a bybit issue though).

Fetching these through `fetch_open_orders()` gives me the types of `'stopOrderType': 'TakeProfit'`, and `'stopOrderType': 'StopLoss'`, though.

**Comment by xmatthias** [comment]
@carlosmiei @Dan-krm 
Based on the info @Dan-krm provided me in #19393 - which is that stopPrice == triggerPrice - i don't think this issue is fixed / should've been closed with the revert PR.

i think `parseOrder` must fill `stopLossPrice` an and `takeProfitPrice` (which is the other side that can be fixed).

The information should be there and is essentially just the reverse from `createOrder` logic - combining side, triggerDirection and reduceOnly (if reduceOnly, it's one of these 2 params - buy/sell + triggerdirection tells you if it's a stop (below current price for sell order) or a take profit (above current price for sell).

**Comment by carlosmiei** [comment]
@xmatthias 

>  which is that stopPrice == triggerPrice 
Yes, that is correct basically `stopPrice` was deprecated because it was a bit confusing (you can place a standalone trigger order so it's not stopping anything) and replaced with `triggerPrice` 

Upon parsing the order, we have access to the `triggerDirection` `triggerPrice` and `reduceOnly` but we don't know the current price so I'm not sure we can do that inference.

**Comment by xmatthias** [comment]
Yes you can - if trigger-direction is "raises to" (intentionally not using the bybit number to avoid confusion) - then this automatically means the order will be above the current price - otherwise the state would be "triggered".

Therefore i think you have the following combi (always assuming you have "reduceOnly=True" - which is implied for "stopLossPrice and `takeProfitPrice` orders on bybit).

|triggerDirection|side|result|
|--------|--------|--------|
|raises|buy|stopOrder (for a short)
|raises|sell|TP order (for a long)
|sinks|buy|TP order (for a short)
|sinks|sell|stoploss (for a long)


Assuming we don't want such logic... then i'm also not sure what bad it would do to populate both `takeProfitPrice` and `stopLossPrice` in the response - if we assume it could've been either of the two).
It'd be a LOT more aligned to how we place the order than current behavior, where we use a parameter as trigger (`stopLossPrice` or `takeProfitPrice`) - but get something completely different back.
