### ISSUE TITLE
This script seems to be having trouble placing an order.

### ISSUE THREAD

**Issue by qwe231cvb** [ccxt/ccxt#19368]
### Operating System

Ubuntu 18.04

### Programming Languages

Python

### CCXT Version

4.0.104

### Description

Does usdt_amount in the following code refer to the amount of usdt required to purchase XRP tokens?

This error occurs after running this code. The error is as follows:
Traceback (most recent call last):
  File "roboot5.py", line 11, in <module>
    create_order = lbank.create_order('XRP/USDT', 'market', 'buy', usdt_amount)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/lbank.py", line 591, in create_order
    response = self.privatePostCreateOrder(self.extend(order, params))
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 3051, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 3048, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 654, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/lbank.py", line 833, in handle_errors
    raise ErrorClass(message)
ccxt.base.errors.InvalidOrder: Market orders can not be missing the amount of the order

### Code

```
import ccxt
import time
from pprint import pprint

lbank = ccxt.lbank({
    'apiKey': 'my_apiKey',
    'secret': 'my_secret',
})
b = 0
usdt_amount = 8
create_order = lbank.create_order('XRP/USDT', 'market', 'buy', usdt_amount)
order = lbank.fetch_order(create_order['id'], create_order['symbol'])
order_status = order['status']
while b == 0:
    print("Order status:", order_status)
    time.sleep(1)  

```

**Comment by carlosmiei** [comment]
Hello @qwe231cvb, is it possible to share a verbose log with us? (exchange.verbose = True before calling `create_order`)

**Comment by qwe231cvb** [comment]
The code modified as follows:
`import ccxt
import time
from pprint import pprint

lbank = ccxt.lbank({
    'apiKey': 'my_apiKey',
    'secret': 'my_secret',
})
b = 0
usdt_amount = 8
lbank.verbose = True
create_order = lbank.create_order('XRP/USDT', 'market', 'buy', usdt_amount)
order = lbank.fetch_order(create_order['id'], create_order['symbol'])
order_status = order['status']
while b == 0:
    print("Order status:", order_status)
    time.sleep(1)`

Since there is too much content in the log output, I only intercepted the main content.，The log as follows：
fetch Request: lbank GET https://api.lbank.info/v1/accuracy.do RequestHeaders: {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: lbank GET https://api.lbank.info/v1/accuracy.do 200 ResponseHeaders: {'Date': 'Mon, 25 Sep 2023 17:43:56 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Accept-Charset': 'big5, big5-hkscs, cesu-8, euc-jp, euc-kr, gb18030, gb2312, gbk, ibm-thai, ibm00858, ibm01140, ibm01141, ibm01142, ibm01143, ibm01144, ibm01145, ibm01146, ibm01147, ibm01148, ibm01149, ibm037, ibm1026, ibm1047, ibm273, ibm277, ibm278, ibm280, ibm284, ibm285, ibm290, ibm297, ibm420, ibm424, ibm437, ibm500, ibm775, ibm850, ibm852, ibm855, ibm857, ibm860, ibm861, ibm862, ibm863, ibm864, ibm865, ibm866, ibm868, ibm869, ibm870, ibm871, ibm918, iso-2022-cn, iso-2022-jp, iso-2022-jp-2, iso-2022-kr, iso-8859-1, iso-8859-13, iso-8859-15, iso-8859-2, iso-8859-3, iso-8859-4, iso-8859-5, iso-8859-6, iso-8859-7, iso-8859-8, iso-8859-9, jis_x0201, jis_x0212-1990, koi8-r, koi8-u, shift_jis, tis-620, us-ascii, utf-16, utf-16be, utf-16le, utf-32, utf-32be, utf-32le, utf-8, windows-1250, windows-1251, windows-1252, windows-1253, windows-1254, windows-1255, windows-1256, windows-1257, windows-1258, windows-31j, x-big5-hkscs-2001, x-big5-solaris, x-compound_text, x-euc-jp-linux, x-euc-tw, x-eucjp-open, x-ibm1006, x-ibm1025, x-ibm1046, x-ibm1097, x-ibm1098, x-ibm1112, x-ibm1122, x-ibm1123, x-ibm1124, x-ibm1166, x-ibm1364, x-ibm1381, x-ibm1383, x-ibm300, x-ibm33722, x-ibm737, x-ibm833, x-ibm834, x-ibm856, x-ibm874, x-ibm875, x-ibm921, x-ibm922, x-ibm930, x-ibm933, x-ibm935, x-ibm937, x-ibm939, x-ibm942, x-ibm942c, x-ibm943, x-ibm943c, x-ibm948, x-ibm949, x-ibm949c, x-ibm950, x-ibm964, x-ibm970, x-iscii91, x-iso-2022-cn-cns, x-iso-2022-cn-gb, x-iso-8859-11, x-jis0208, x-jisautodetect, x-johab, x-macarabic, x-maccentraleurope, x-maccroatian, x-maccyrillic, x-macdingbat, x-macgreek, x-machebrew, x-maciceland, x-macroman, x-macromania, x-macsymbol, x-macthai,
fetch Request: lbank POST https://api.lbank.info/v1/create_order.do RequestHeaders: {'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: amount=8&api_key=a629ee03-30f4-4387-82d9-c8992beed992&symbol=xrp_usdt&type=buy_market&sign=j%2FZnTvjna7PL6r3IR0%2BgKluOAgkvjO1ZQdekz%2Fxqm%2F9LwyhERdZ%2FtEVwT6BWJqRIPZadQPUkE5ECs%2FdNRJFBkSQtsDMcPK8s8N0XeHkXIRo%2BAq%2FMf6k8q%2FKUTwOiHpm74iYdBnS5D%2Bsjy9zYovbf803Bn0iOWWxTysNrX2%2Faa4E%3D

fetch Response: lbank POST https://api.lbank.info/v1/create_order.do 200 ResponseHeaders: {'Date': 'Mon, 25 Sep 2023 17:43:57 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Accept-Charset': 'big5, big5-hkscs, cesu-8, euc-jp, euc-kr, gb18030, gb2312, gbk, ibm-thai, ibm00858, ibm01140, ibm01141, ibm01142, ibm01143, ibm01144, ibm01145, ibm01146, ibm01147, ibm01148, ibm01149, ibm037, ibm1026, ibm1047, ibm273, ibm277, ibm278, ibm280, ibm284, ibm285, ibm290, ibm297, ibm420, ibm424, ibm437, ibm500, ibm775, ibm850, ibm852, ibm855, ibm857, ibm860, ibm861, ibm862, ibm863, ibm864, ibm865, ibm866, ibm868, ibm869, ibm870, ibm871, ibm918, iso-2022-cn, iso-2022-jp, iso-2022-jp-2, iso-2022-kr, iso-8859-1, iso-8859-13, iso-8859-15, iso-8859-2, iso-8859-3, iso-8859-4, iso-8859-5, iso-8859-6, iso-8859-7, iso-8859-8, iso-8859-9, jis_x0201, jis_x0212-1990, koi8-r, koi8-u, shift_jis, tis-620, us-ascii, utf-16, utf-16be, utf-16le, utf-32, utf-32be, utf-32le, utf-8, windows-1250, windows-1251, windows-1252, windows-1253, windows-1254, windows-1255, windows-1256, windows-1257, windows-1258, windows-31j, x-big5-hkscs-2001, x-big5-solaris, x-compound_text, x-euc-jp-linux, x-euc-tw, x-eucjp-open, x-ibm1006, x-ibm1025, x-ibm1046, x-ibm1097, x-ibm1098, x-ibm1112, x-ibm1122, x-ibm1123, x-ibm1124, x-ibm1166, x-ibm1364, x-ibm1381, x-ibm1383, x-ibm300, x-ibm33722, x-ibm737, x-ibm833, x-ibm834, x-ibm856, x-ibm874, x-ibm875, x-ibm921, x-ibm922, x-ibm930, x-ibm933, x-ibm935, x-ibm937, x-ibm939, x-ibm942, x-ibm942c, x-ibm943, x-ibm943c, x-ibm948, x-ibm949, x-ibm949c, x-ibm950, x-ibm964, x-ibm970, x-iscii91, x-iso-2022-cn-cns, x-iso-2022-cn-gb, x-iso-8859-11, x-jis0208, x-jisautodetect, x-johab, x-macarabic, x-maccentraleurope, x-maccroatian, x-maccyrillic, x-macdingbat, x-macgreek, x-machebrew, x-maciceland, x-macroman, x-macromania, x-macsymbol, x-macthai, x-macturkish, x-macukraine, x-ms932_0213, x-ms950-hkscs, x-ms950-hkscs-xp, x-mswin-936, x-pck, x-sjis_0213, x-utf-16le-bom, x-utf-32be-bom, x-utf-32le-bom, x-windows-50220, x-windows-50221, x-windows-874, x-windows-949, x-windows-950, x-windows-iso2022jp', 'X-Frame-Options': 'SAMEORIGIN', 'CF-Cache-Status': 'DYNAMIC', 'Set-Cookie': '__cf_bm=kozHs0M9hJl2vPEISAJDUkZY1t5ZImj5YFaq1NAvC7A-1695663837-0-AVoLH+mnlbCiut8d2gufBYbZstP+bcLcOUvrel/liMbamjcwIiw9vlWF6yiqsAkRvPFAudNmqeaXTLmxPdzZWAo=; path=/; expires=Mon, 25-Sep-23 18:13:57 GMT; domain=.lbank.info; HttpOnly; Secure; SameSite=None, _cfuvid=A5xYc1EHXiwm4ysC3DzERVXmPcCufdJl1wdM7I4rAws-1695663837864-0-604800000; path=/; domain=.lbank.info; HttpOnly; Secure; SameSite=None', 'Server': 'cloudflare', 'CF-RAY': '80c512895be72ea5-LAX', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400'} ResponseBody: {"result":"false","error_code":10011,"ts":1695663837783}
Traceback (most recent call last):
  File "roboot5.py", line 12, in <module>
    create_order = lbank.create_order('XRP/USDT', 'market', 'buy', usdt_amount)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/lbank.py", line 591, in create_order
    response = self.privatePostCreateOrder(self.extend(order, params))
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 3058, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 3055, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 654, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/lbank.py", line 833, in handle_errors
    raise ErrorClass(message)
ccxt.base.errors.InvalidOrder: Market orders can not be missing the amount of the order

**Comment by carlosmiei** [comment]
@qwe231cvb That is strange, we can clearly see the amount in the request

>  amount=8&api_key=a629ee03-30f4-4387-82d9-c8992beed992&symbol=xrp_usdt&type=buy_market&s

@qwe231cvb can you try to instantiate `lbank2` (v2) instead?

**Comment by qwe231cvb** [comment]
You say instantiating lbank2 (v2), do you mean modifying it like this?
````
import ccxt
import time
from pprint import pprint

lbank2 = ccxt.lbank2({
    'apiKey': 'my_apiKey',
    'secret': 'my_secret',
})
b = 0
usdt_amount = 8
lbank.verbose = True
create_order = lbank2.create_order('XRP/USDT', 'market', 'buy', usdt_amount)
order = lbank2.fetch_order(create_order['id'], create_order['symbol'])
order_status = order['status']
while b == 0:
    order = lbank2.fetch_order(create_order['id'], create_order['symbol'])
    order_status = order['status']
    print("Order status:", order_status)
    time.sleep(1)
````

But after running this error appears:

fetch Request: lbank2 GET https://api.lbank.info/v2/accuracy.do RequestHeaders: {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: lbank2 GET https://api.lbank.info/v2/accuracy.do 200 ResponseHeaders: {'Date': 'Tue, 26 Sep 2023 19:38:42 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Accept-Charset': 'big5, big5-hkscs, cesu-8, euc-jp, euc-kr, gb18030, gb2312, gbk, ibm-thai, ibm00858, ibm01140, ibm01141, ibm01142, ibm01143, ibm01144, ibm01145, ibm01146, ibm01147, ibm01148, ibm01149, ibm037, ibm1026, ibm1047, ibm273, ibm277, ibm278, ibm280, ibm284, ibm285, ibm290, ibm297, ibm420, ibm424, ibm437, ibm500, ibm775, ibm850, ibm852, ibm855, ibm857, ibm860,
"baseCurrency":"ASTR","volumeMultiple":1.0,"exchangeID":"Exchange","priceCurrency":"USDT","priceLimitLowerValue":0.15,"clearCurrency":"USDT","symbolName":"ASTRUSDT","defaultLeverage":20.0,"minOrderCost":"5.0"},{"priceLimitUpperValue":0.2,"symbol":"SEIUSDT","volumeTick":1.0,"indexPrice":"0.11743200","minOrderVolume":"1.0","priceTick":0.0001,"maxOrderVolume":"5000000.0","baseCurrency":"SEI","volumeMultiple":1.0,"exchangeID":"Exchange","priceCurrency":"USDT","priceLimitLowerValue":0.2,"clearCurrency":"USDT","symbolName":"SEIUSDT","defaultLeverage":75.0,"minOrderCost":"5.0"},{"priceLimitUpperValue":0.15,"symbol":"BNXUSDT","volumeTick":0.1,"indexPrice":"0.20744000","minOrderVolume":"0.1","priceTick":0.0001,"maxOrderVolume":"300000.0","baseCurrency":"BNX","volumeMultiple":1.0,"exchangeID":"Exchange","priceCurrency":"USDT","priceLimitLowerValue":0.15,"clearCurrency":"USDT","symbolName":"BNXUSDT","defaultLeverage":20.0,"minOrderCost":"5.0"}],"error_code":0,"msg":"Success","result":"true","success":true}
Traceback (most recent call last):
  File "roboot5.py", line 13, in <module>
    create_order = lbank2.create_order('XRP/USDT', 'market', 'buy', usdt_amount)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/lbank2.py", line 1259, in create_order
    raise InvalidOrder(self.id + " createOrder() requires the price argument with market buy orders to calculate total order cost(amount to spend), where cost = amount * price. Supply the price argument to createOrder() call if you want the cost to be calculated for you from price and amount, or, alternatively, add .options['createMarketBuyOrderRequiresPrice'] = False to supply the cost in the amount argument(the exchange-specific behaviour)")
ccxt.base.errors.InvalidOrder: lbank2 createOrder() requires the price argument with market buy orders to calculate total order cost(amount to spend), where cost = amount * price. Supply the price argument to createOrder() call if you want the cost to be calculated for you from price and amount, or, alternatively, add .options['createMarketBuyOrderRequiresPrice'] = False to supply the cost in the amount argument(the exchange-specific behaviour)

**Comment by carlosmiei** [comment]
@qwe231cvb 

Some exchanges for spot market buy orders require price+amount by default so we can compute the cost because that is what the exchange accepts, so instead of saying buy 0.0001 BTC we have to say buy 10 USDT worth of Bitcoin for instance. 
Example:
```Python
spot_order = await exchange.create_order('BTC/USDT', 'market', 'buy', 2, 30000) # by default we require price+quantity for market orders because gate requires the cost and ccxt does 2 * 30000 (amount * price) to get it

# alternatively you can disable that option and provide the cost only
exchange.options['createMarketBuyOrderRequiresPrice'] = False
spot_order = await exchange.create_order('BTC/USDT', 'market', 'buy', 60000) # here the amount is the cost in USDT
```

**Comment by qwe231cvb** [comment]
> @qwe231cvb
> 
> Some exchanges for spot market buy orders require price+amount by default so we can compute the cost because that is what the exchange accepts, so instead of saying buy 0.0001 BTC we have to say buy 10 USDT worth of Bitcoin for instance. Example:
> 
> ```python
> spot_order = await exchange.create_order('BTC/USDT', 'market', 'buy', 2, 30000) # by default we require price+quantity for market orders because gate requires the cost and ccxt does 2 * 30000 (amount * price) to get it
> 
> # alternatively you can disable that option and provide the cost only
> exchange.options['createMarketBuyOrderRequiresPrice'] = False
> spot_order = await exchange.create_order('BTC/USDT', 'market', 'buy', 60000) # here the amount is the cost in USDT
> ```

The code is modified as follows: but the error is still displayed:
````
import ccxt
import time
from pprint import pprint

lbank = ccxt.lbank({
    'apiKey': 'my_apikey',
    'secret': 'my_secret',
  })
b = 0
lbank.options['createMarketBuyOrderRequiresPrice'] = False
create_order = await lbank.create_order('XRP/USDT', 'market', 'buy', 4)
order = lbank.fetch_order(create_order['id'], create_order['symbol'])
order_status = order['status']
while b == 0:
    order = lbank.fetch_order(create_order['id'], create_order['symbol'])
    order_status = order['status']
    print("Order status:", order_status)
    time.sleep(1)
````
The errors as follows:
  File "roboot5.py", line 11
    create_order = await lbank.create_order('XRP/USDT', 'market', 'buy', 4)
                  ^
SyntaxError: 'await' outside function

**Comment by sc0Vu** [comment]
Hey @qwe231cvb 

The code used `await` functionality, I think you need to wrap the `await` in `async` function.
