### ISSUE TITLE
huobi withdraw problem with networks

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#19377]
### Operating System

Linux

### Programming Languages

JavaScript

### CCXT Version

latest

### Description

When I try to make withdraw of USDT ERC20 like this:
```
await exchange.withdraw ('USDT', 100, '0xxxxxxxx', undefined, {
    network: 'ERC20'
})
```
I see that 
```
RequestBody:
{"address":"0xxxxxx","currency":"usdt","chain":"ERC20","amount":100}
 ```
I get an error
` {"status":"error","err-code":"base-currency-chain-error","err-msg":"The current currency chain does not exist","data":null} `
So mapping of `chain` is incorrect. It was all good a few weeks ago, maybe some changes on Huobi.
The correct mapping of ERC20 network is `usdterc20` (but `trc20usd` for TRC20)
Can you please make some workaround of this issue?

**Comment by carlosmiei** [comment]
Hello @ndubel, thanks for letting us know we will take a look.

**Comment by ttodua** [comment]
it's strange. 
what I see, we didn't have any update neither in huobi  class (`fetchCurrencies, withdraw, networkCodeToId` methods) neither in base related to this subject.
So, can you tell how much period could be "few weeks ago"? What I see, the last update for it was made around 8 months ago.
I am checking the issue again at this moment, and will keep you informed.

**Comment by ttodua** [comment]
after digging into it, seems exchange changed response value in one of the fields of `v2/reference/currencies`.
I will be updating the implementation and migrating into another endpoint, as this endpoint become partially useless after that change. I will submit a fix within a few hours.

**Comment by ndubel** [comment]
I've checked that my last succesful USDT withdrawal via API to ERC20 wa made in the end of August. maybe ERC20 was default network so `chain` param was ignored or something like that. I also didn't made any changes in my code

**Comment by ttodua** [comment]
thanks @ndubel again, sure, you were right, as I've checked, it has really been changed in endpoint response. I'm working on it still, PR will be merged  within 24 hours probably
