### ISSUE TITLE
how to get a deal price using php

### ISSUE THREAD

**Issue by 2l1k** [ccxt/ccxt#1938]
I need to get data about my purchases and my sales, how can I get them, could you write a small code on PHP? Thank You!

Мне нужно получить данные о моих покупках и моих продажах, как я могу их получить, не могли бы вы написать небольшой код на PHP? Спасибо!

**Comment by kroitor** [comment]
This is documented here:

- https://github.com/ccxt/ccxt/wiki/Manual#orders
- https://github.com/ccxt/ccxt/wiki/Manual#orders-cache
- https://github.com/ccxt/ccxt/wiki/Manual#trades--transactions--fills--executions

Let us know if it does not help. Thx!
