### ISSUE TITLE
bingx fetchPosition() is not supported yet

### ISSUE THREAD

**Issue by atabakhooshangi** [ccxt/ccxt#19383]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Describe the solution you'd like

Will this method gonna get  implemented in bingx soon?

**Comment by carlosmiei** [comment]
Hello @atabakhooshangi,

As of now bingx does not have a specific endpoint suitable to be used by the `fetchPosition` method, however, you already have the `fetchPositions` implementation that should be capable of replacing it.

**Comment by ZetZ1** [comment]
its simple fetch_positions([SYMBOLhere])[0]
