### ISSUE TITLE
Woo watch_balance on ccxt.pro

### ISSUE THREAD

**Issue by KevinBaudin** [ccxt/ccxt#19381]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Describe the solution you'd like

I imagine something like:

```
    async def watch_balance(self, params=None):
        if params is None:
            params = {}
        await self.exchange.load_markets()
        topic = 'balance'
        messageHash = topic
        request = {
            'event': 'subscribe',
            'topic': topic,
        }
        message = self.exchange.extend(request, params)
        return await self.exchange.watch_private(messageHash, message)
 ```
 
 What do you guys think?
 Based on the existing method found here: https://docs.woo.org/#balance

Thanks for the great work !

**Comment by carlosmiei** [comment]
Hello @KevinBaudin,
Thanks for letting us know, we will try to add `watchBalance` as soon as possible.
