### ISSUE TITLE
Ccxt Exception question

### ISSUE THREAD

**Issue by svax974** [ccxt/ccxt#19396]
### Operating System

Debian 12 / macOS

### Programming Languages

Python

### CCXT Version

4.0.6

### Description

More a question than an issue, I'm getting ccxt.BadRequest exception when trying to set leverage on ByBit when the leverage is already the same as the one I'm asking.
Here is the output :
{"retCode":110043,"retMsg":"Set leverage not modified","result":{},"retExtInfo":{},"time":1695818717824}

I'm just wondering 2 things : 
1) Is it possible to get the actual leverage to avoid calling set_leverage and thus the exception
2) How can I "extract" the retCode from the Exception ? It does not seem to be an object (not subscriptable)

Thanks !

### Code

```
  

```

**Comment by germangar** [comment]
You can fetch the leverage from the server using fetchLeverage, but at the end of the day fetchLeverage and setLeverage are a request of about the same size. IMO it's just better to silently ignore the error. Also, I think they just changed the error to ccxt.noChange for this one in one of the latest PRs.

I'm also interested in the reply to the second one.

**Comment by carlosmiei** [comment]
Hello @svax974  and thanks @germangar for the explanations, as @germangar  mentioned, if the method `fetchLeverage` is available, you can use that, otherwise it's better to use the `setLeverage` and handle the raised exception when the leverage is not modified.
