### ISSUE TITLE
ByBit order with custom TP/SL triggerPrices and TP/SL order type

### ISSUE THREAD

**Issue by svax974** [ccxt/ccxt#19403]
### Operating System

Debian 12 / macOS

### CCXT Version

4.0.6

### Description

Again, more a question, do not hesitate to redirect me to another better place to ask.

Lokking at the unified `create_order` in bybit.py, I understand that API value like `tpOrderType` and `tpLimitPrice` might not be taken into account in the resulting request to the API.
Am I wrong ?
When trying to add them to params I get :
```python
ccxt.base.errors.BadRequest: bybit {"retCode":10001,"retMsg":"Request parameter error.","result":{},"retExtInfo":{},"time":1695900254543}
```
Is there any way to use those parameters ? Because right now, create_order seems to put TP/SL market orders for instance.

Thanks !

**Comment by carlosmiei** [comment]
Hello @svax974, can you show us the code you're using to place the order? Even if you don't see an explicit reference to some field, if you provide it in `params` it will end up in the request because we extend the request with params at the end.

**Comment by carlosmiei** [comment]
Also please bear in mind that if you want to place a full tp+sl only `market` is accepted 
![image](https://github.com/ccxt/ccxt/assets/43336371/02d76c33-94da-4c05-abfa-191fba8e7037)

**Comment by svax974** [comment]
Sure, initially just using the first line of params settings (works ok and set market TP/SL) and here is what I'm trying to do now (just added tpslMode to Partial) and still get the "Request parameter error" :
```
params = { 'stopLoss': trade.sl, 'takeProfit': trade.tp }
params = { **params, 'tpslMode': 'Partial', 'tpOrderType': 'Limit', 'tpLimitPrice': trade.tp, 'slOrderType': 'Limit', 'slLimitPrice': trade.sl }
bybit.create_order('BTC/USDT:USDT', 'limit', 'buy', 0.001, trade.price, params)
```

**Comment by Gorgias26** [comment]
Hello @svax974  and @carlosmiei , I also have this problem.


I'm trying to put 1 SL and 4 TP on my position, but it's impossible. I had tried to split the orders into 4 with each one their TP/SL. The problem is that the last order defines the TP for the whole position... In addition, the TP/SL go to market.


When you look at the documentation, there's everything you need to fix this, but I can't get an order to go through like that either.


https://bybit-exchange.github.io/docs/v5/order/create-order


I'm going to continue testing, if you have a solution I'm interested :)


Good evening to you
amount

**Comment by svax974** [comment]
Hello, I don't have a clue on this yet.
I tried a few things without any success so far. If I ever get something to work I'll share of course.
And if you get further I'm interested too ! :)
Have a nice week-end

**Comment by borovikv** [comment]
Hi I'm getting this error:

```
pybit.exceptions.InvalidRequestError: Request parameter error. (ErrCode: 10001) (ErrTime: 13:33:29).
Request → POST https://api-testnet.bybit.com/v5/order/create: {"category": "linear", "symbol": "BTCUSDT", "side": "Buy", "orderType": "Limit", "qty": "0.001", "price": "27120", "timeInForce": "PostOnly", "isLeverage": 1, "orderFilter": "Order", "triggerBy": "MarkPrice", "positionIdx": 1, "tpslMode": "Partial", "tpLimitPrice": 27391.2, "slLimitPrice": 24408, "tpOrderType": "Limit", "slOrderType": "Limit"}.
```
I'm not sure what is wrong in the request. At least I didn't found anything in the documentation.

**Comment by carlosmiei** [comment]
@borovikv can you show us the ccxt call made?

**Comment by borovikv** [comment]
@carlosmiei My apologies, please disregard my previous question. I realized I made an error by posting it in this repository since I'm interacting with the Bybit API directly. I have now deleted the question.

**Comment by svax974** [comment]
Seems I got it working.

After having played and successfully passed an order directly with the privatePostV5OrderCreate function, I switched back to generic create_order function.

I have no more problem after explicitly converting params prices to string :
params = { 'stopLoss': str(trade.sl), 'takeProfit': str(trade.tp), ... }
params = { **params, 'tpslMode': 'Partial', 'tpOrderType': 'Limit', 'tpLimitPrice': str(trade.tp), 'slOrderType': 'Limit', 'slLimitPrice': str(trade.sl) }

Shouldn't it be handled internally for easier use ?

Have a nice day !
