### ISSUE TITLE
OKEX -- sell order (and buy orders) not executed

### ISSUE THREAD

**Issue by candreacchio** [ccxt/ccxt#1940]
- OS: Ubuntu 17.04
- Programming Language version: Python3
- CCXT version: 1.10.1129
- Exchange: OKEX
Using the following code, it returns an error and doesnt execute
```
import ccxt

site = ccxt.okex({
    'apiKey': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
    'secret': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
})


site.verbose = True
site.create_limit_sell_order("XRP/USDT", 1, 1.75, {'trading_agreement': 'agree'})

```

I have also uploaded a verbose output here https://pastebin.com/Cypv237i

**Comment by candreacchio** [comment]
the error code is 10007 which from https://www.okex.com/rest_request.html means
" Signature does not match "

**Comment by mkutny** [comment]
Does it work without 'trading_agreement'?

**Comment by kroitor** [comment]
@candreacchio, the answer given by @mkutny is correct.

Your code:

```Python
site.verbose = True
site.create_limit_sell_order("XRP/USDT", 1, 1.75, {'trading_agreement': 'agree'})
# why in the world you would add this Kraken-specific param ↑↑↑ to an OKEX request?
```

Try this instead:

```Python
site.verbose = True
site.create_limit_sell_order("XRP/USDT", 1, 1.75)
# no OKEX-specific extra params are needed here ↑↑↑
```

Hope it helps.

**Comment by candreacchio** [comment]
Thanks, didnt realise it was a Kraken Specific param.
