### ISSUE TITLE
Having a hard time getting 'since' to work with fetchOrders - fetchMyTrades - fetchLedger

### ISSUE THREAD

**Issue by respectabiggle** [ccxt/ccxt#19417]
### Operating System

WIn 10

### Programming Languages

JavaScript

### CCXT Version

4.0.109

### Description

repo here:  https://github.com/respectabiggle/since/blob/master/since.js

Hello, thanks for reading.

I''m not sure if I'm doing this wrong or if the Coinbase Pro endpoints are getting old and cranky.

As you can see, I've tried 'since' as an argument in the below commands.  
The response doesn't seem to respect them -- my response is starting with the 1000th most recent transaction.

I am probably formatting this wrong or something.
Any help appreciated!

_No response_

### Code

```
import { log }				from 'console'
import { coinbasepro }			from 'ccxt'
import { config }			from 'dotenv'	; config()	

let pro = new coinbasepro({
	apiKey:		process.env.COINBASE_PRO_API_KEY,
	secret:		process.env.COINBASE_PRO_SECRET,
	password:	process.env.COINBASE_PRO_PASSWORD
})

let sinceTest = async function() {


	let symbol	= undefined
	let since	= pro.parse8601 ('2018-01-01T00:00:00Z')		// 1514764800000		
	let params	= { since : 1514764800000 }
	let foo

	 
	foo		= await pro.fetchOrders(symbol, since)			// 2021-04-18T02:58:10.640Z (symbol == undefined)
	foo		= await pro.fetchOrders('ETH/USD', since)		// 2021-04-17T07:26:33.917Z 
	// foo		= await pro.fetchOrders('ETH/USD', params)		// []
	
	 

	foo		= await pro.fetchMyTrades('ETH/USD')			// 2021-05-27T19:27:08.517Z		
	foo		= await pro.fetchMyTrades('ETH/USD', since)		// 2021-05-27T19:27:08.517Z confirmed	
	

	
	foo		= await pro.fetchLedger('ETH')				// 2021-06-04		
	foo		= await pro.fetchLedger('ETH', since)			// 2021-06-04		
	// foo		= await pro.fetchLedger('ETH', params)			// []		
	

	log(foo[0].datetime) 

}
sinceTest()
```

**Comment by carlosmiei** [comment]
Hello @respectabiggle,

I noticed that we're not sending the `since` parameter in the `fetchMyTrades/fetchOrders` methods, so that could explain the erratic behavior (we were filtering a posteriori).  I will open a PR very soon to fix it. Regarding the `fetchLedger`, we're already sending it in the request, so it is not working correctly, it might be an issue on the exchange side.

**Comment by respectabiggle** [comment]
@carlosmiei That's awesome, thank you for your attention!
