### ISSUE TITLE
Currencies property of any exchange is empty

### ISSUE THREAD

**Issue by parthsaxena** [ccxt/ccxt#1941]
OS: Mac OS
Programming Language: Node.js
CCXT Version: 1.10.1138
Exchange: Binance
Method: Currencies property

When I try to access the currency property of an instantiated Binance exchange object, an empty array 
 ("{}") is printed out.

**Comment by arielorvits** [comment]
try first binance.loadMarkets()

**Comment by kroitor** [comment]
You have to call `await loadMarkets()` on your exchange instance before accessing markets and currencies. This is documented here: https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

Hope it helps.
