### ISSUE TITLE
Bybit amend order issue - InvalidOperation: [<class 'decimal.ConversionSyntax'>]

### ISSUE THREAD

**Issue by Rishirandhawa** [ccxt/ccxt#19412]
### Operating System

MAC OS

### Programming Languages

Python

### CCXT Version

'4.0.110'

### Description

Bybit edit_order method throwing weird exception. 

---------------------------------------------------------------------------
InvalidOperation                          Traceback (most recent call last)
/var/folders/7b/_c1j3w8167s4qch1zxyxl6fw0000gn/T/ipykernel_11251/3482243663.py in <module>
     26 params['stopLoss'] = stop_loss
     27 
---> 28 order = exchange.edit_order(id=id, symbol=symbol, type=type, side=side, amount=amount, price=price, params=params)

~/projects/trading-bot/env/lib/python3.8/site-packages/ccxt/bybit.py in edit_order(self, id, symbol, type, side, amount, price, params)
   4363         elif enableUnifiedMargin and not market['inverse']:
   4364             return self.edit_unified_margin_order(id, symbol, type, side, amount, price, params)
-> 4365         return self.edit_contract_v3_order(id, symbol, type, side, amount, price, params)
   4366 
   4367     def cancel_unified_account_order(self, id: str, symbol: Optional[str] = None, params={}):

~/projects/trading-bot/env/lib/python3.8/site-packages/ccxt/bybit.py in edit_contract_v3_order(self, id, symbol, type, side, amount, price, params)
   4297             'symbol': market['id'],
   4298             'orderId': id,
-> 4299             'qty': self.amount_to_precision(symbol, amount),
   4300             # 'orderLinkId': '',  # User customised order id. Either orderId or orderLinkId is required
   4301             # 'triggerPrice': '',  # Trigger price. Don't pass it if not modify the qty

~/projects/trading-bot/env/lib/python3.8/site-packages/ccxt/base/exchange.py in amount_to_precision(self, symbol, amount)
   3585     def amount_to_precision(self, symbol: str, amount):
   3586         market = self.market(symbol)
-> 3587         result = self.decimal_to_precision(amount, TRUNCATE, market['precision']['amount'], self.precisionMode, self.paddingMode)
   3588         if result == '0':
   3589             raise InvalidOrder(self.id + ' amount of ' + market['symbol'] + ' must be greater than minimum amount precision of ' + self.number_to_string(market['precision']['amount']))

~/projects/trading-bot/env/lib/python3.8/site-packages/ccxt/base/decimal_to_precision.py in decimal_to_precision(n, rounding_mode, precision, counting_mode, padding_mode)
     56     context.rounding = decimal.ROUND_HALF_UP  # rounds 0.5 away from zero
     57 
---> 58     dec = decimal.Decimal(str(n))
     59     precision_dec = decimal.Decimal(str(precision))
     60     string = '{:f}'.format(dec)  # convert to string using .format to avoid engineering notation

InvalidOperation: [<class 'decimal.ConversionSyntax'>]

### Code

```
#Instantiate bybit Exchange and make sure hedge mode is enabled for USDT Perps
exchange_id = 'bybit'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
    'apiKey': "",
    'secret': "",
    'timeout': 30000,
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future',
        'adjustForTimeDifference': True,
    },
})

###### Create order
symbol = 'ETH/USDT:USDT'
type = 'limit'
side = 'sell'
amount = 0.01
price = 2000

params['positionIdx'] = 2 ### 1 Long position and 2 Short position
params['takeProfit'] = 1900
params['stopLoss'] = 2100    
order = exchange.create_order(symbol, type, side, amount, price, params)
id = order['id']

####### Update order to cancel TP and SL that was set in create order
id = id ## generated in create order earlier
symbol = 'ETH/USDT:USDT'
type = 'limit'
side = 'sell'
amount = None
price = None

take_profit = 0
stop_loss = 0

params['takeProfit'] = take_profit
params['stopLoss'] = stop_loss

order = exchange.edit_order(id=id, symbol=symbol, type=type, side=side, amount=amount, price=price, params=params)
```

**Comment by carlosmiei** [comment]
Hello @Rishirandhawa, thanks for letting us know, we will take a look

**Comment by Rishirandhawa** [comment]
@kroitor would you know about this issue? I see you sent in a patch for a similar issue for OKX sometime back. 
https://github.com/ccxt/ccxt/issues/7415

related commit at the time
https://github.com/ccxt/ccxt/commit/dc2b1ef26fea0d9b2afcea68eada19aa203cc200

**Comment by Dan-krm** [comment]
Hi @Rishirandhawa I've opened a pull request that will resolve your issue and allow you to set the stopLoss and takeProfit to zero

**Comment by Rishirandhawa** [comment]
Thanks, @Dan-krm so when SL-Price and TP-Price are set to zero in the background it will pass the same to Bybit's 'amend'  end-point, which in turn will cancel TP/SL associated with the order? Will wait for the merge.

**Comment by Rishirandhawa** [comment]
This one cleared. Thanks. However the method is still not working because of another issue. Will open a new issue for that
