### ISSUE TITLE
Bybit - fetch_positions() is not fully functional for Unified Accounts in Hedge-Mode

### ISSUE THREAD

**Issue by Rishirandhawa** [ccxt/ccxt#19429]
### Operating System

MAC OS

### Programming Languages

Python

### CCXT Version

4.0.112

### Description

Bybit fetch_positions is broken for Unified accounts in hedge mode. Lot of values like contract, avgPrice etc come empty
So I tried the private method and it has the same result. Any ideas ?

### Verbose
fetch Request: bybit GET https://api.bybit.com/v5/position/list?symbol=ETHUSDT&category=linear RequestHeaders: {'Content-Type': 'application/json', 'X-BAPI-API-KEY': 'WvZi6kjVy3KvUj6zf8', 'X-BAPI-TIMESTAMP': '1696218039525', 'X-BAPI-RECV-WINDOW': '5000', 'X-BAPI-SIGN': 'd26a4ffdbeed49737319885a54451c27112ac3f830fb5fb7c669c21d5149301b', 'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bybit GET https://api.bybit.com/v5/position/list?symbol=ETHUSDT&category=linear 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'Date': 'Mon, 02 Oct 2023 03:40:40 GMT', 'X-Bapi-Limit': '50', 'X-Bapi-Limit-Status': '49', 'X-Bapi-Limit-Reset-Timestamp': '1696218040621', 'Ret_code': '0', 'Traceid': '727922b2ac6c0e4e4f1e77d682d69d46', 'Timenow': '1696218040623', 'Server': 'Openresty', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 44c0e54d05452b3ec442713a566a7cbe.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'MAD51-C3', 'X-Amz-Cf-Id': 'ToUswUaSQ6IYqR6KUzrXQOo398tDOiPBbQP3Lmqmgst6AQ5P0ZtKbQ=='} ResponseBody: {"retCode":0,"retMsg":"OK","result":{"nextPageCursor":"ETHUSDT%2C1696212434977%2C1","category":"linear","list":[{"symbol":"ETHUSDT","leverage":"20","autoAddMargin":0,"avgPrice":"0","liqPrice":"","riskLimitValue":"900000","takeProfit":"","positionValue":"0","tpslMode":"Full","riskId":11,"trailingStop":"0","unrealisedPnl":"0","markPrice":"1725.76","adlRankIndicator":0,"cumRealisedPnl":"-0.19493204","positionMM":"0","createdTime":"1696007462411","positionIdx":2,"positionIM":"0","seq":84563617330,"updatedTime":"1696212444706","side":"","bustPrice":"","positionBalance":"0","size":"0","positionStatus":"Normal","stopLoss":"","tradeMode":0},{"symbol":"ETHUSDT","leverage":"20","autoAddMargin":0,"avgPrice":"0","liqPrice":"","riskLimitValue":"900000","takeProfit":"","positionValue":"0","tpslMode":"Full","riskId":11,"trailingStop":"0","unrealisedPnl":"0","markPrice":"1725.76","adlRankIndicator":0,"cumRealisedPnl":"0.2205613","positionMM":"0","createdTime":"1696007462411","positionIdx":1,"positionIM":"0","seq":84563606380,"updatedTime":"1696212434977","side":"","bustPrice":"","positionBalance":"0","size":"0","positionStatus":"Normal","stopLoss":"","tradeMode":0}]},"retExtInfo":{},"time":1696218040623}

### Error Log
{"retCode": "0", "retMsg": "OK", "result": {"nextPageCursor": "ETHUSDT%2C1696212434977%2C1", "category": "linear", "list": [{"symbol": "ETHUSDT", "leverage": "20", "autoAddMargin": "0", "avgPrice": "0", "liqPrice": "", "riskLimitValue": "900000", "takeProfit": "", "positionValue": "0", "tpslMode": "Full", "riskId": "11", "trailingStop": "0", "unrealisedPnl": "0", "markPrice": "1725.76", "adlRankIndicator": "0", "cumRealisedPnl": "-0.19493204", "positionMM": "0", "createdTime": "1696007462411", "positionIdx": "2", "positionIM": "0", "seq": "84563617330", "updatedTime": "1696212444706", "side": "", "bustPrice": "", "positionBalance": "0", "size": "0", "positionStatus": "Normal", "stopLoss": "", "tradeMode": "0"}, {"symbol": "ETHUSDT", "leverage": "20", "autoAddMargin": "0", "avgPrice": "0", "liqPrice": "", "riskLimitValue": "900000", "takeProfit": "", "positionValue": "0", "tpslMode": "Full", "riskId": "11", "trailingStop": "0", "unrealisedPnl": "0", "markPrice": "1725.76", "adlRankIndicator": "0", "cumRealisedPnl": "0.2205613", "positionMM": "0", "createdTime": "1696007462411", "positionIdx": "1", "positionIM": "0", "seq": "84563606380", "updatedTime": "1696212434977", "side": "", "bustPrice": "", "positionBalance": "0", "size": "0", "positionStatus": "Normal", "stopLoss": "", "tradeMode": "0"}]}, "retExtInfo": {}, "time": "1696218040623"}

### Code

```
params = {}
params['symbol'] = 'ETHUSDT'
params['category'] = 'linear'
positions = exchange.privateGetV5PositionList(params)

```

**Comment by sc0Vu** [comment]
@Rishirandhawa

**Comment by Rishirandhawa** [comment]
Thanks. I am going for some workaround. So good for now.
