### ISSUE TITLE
fetch_currencies() does not work on binance (-1002 /You are not authorized to execute this request)

### ISSUE THREAD

**Issue by xibalbas** [ccxt/ccxt#19425]
### Operating System

Linux Ubuntu

### Programming Languages

Python

### CCXT Version

4.0.111

#### **How am I using it?**

```py
import ccxt

ex = ccxt.binance(
    {
        'apiKey': BINANCE_API_KEY,
        'secret': BINANCE_SECRET_KEY,
        'enableRateLimit': True,  # as required by the Manual
    }
)

ex.fetch_currencies()
```

and it returns this exception
`ccxt.base.errors.AuthenticationError: binance {"code":-1002,"msg":"You are not authorized to execute this request."}`

But what is the solution
by adding `?timestamp=1696173230&signature=sd6f56sdf` to URL 

we don't sign and add timestamp

**Comment by xibalbas** [comment]
https://github.com/binance/binance-api-postman/issues/86

**Comment by carlosmiei** [comment]
Hello @xibalbas,

Can you double-check your API keys permissions? I just tested and seems to be working:

```
Python v3.11.5
CCXT v4.0.108
binance.fetchCurrencies()
{'1INCH': {'active': True,
           'code': '1INCH',
           'deposit': True,
           'fee': 7.82,
           'fees': {'BSC': 0.16, 'ETH': 7.82},
           'id': '1INCH',
           'info': {'coin': '1INCH',
                    'depositAllEnable': True,
                    'free': '0',
                    'freeze': '0',
                    'ipoable': '0',
                    'ipoing': '0',
```

**Comment by xibalbas** [comment]
dear @carlosmiei I double-checked my API key permissions and I still got `AuthenticationError: binance {"code":-1002,"msg":"You are not authorized to execute this request."}`

**Comment by carlosmiei** [comment]
@xibalbas hello, are you using testnet keys? If not, I suggest reaching out to Binance and asking why you're getting this error. We have hundreds of users using Binance every day, and they don't have any issues accessing private endpoints.

**Comment by imanmousaei** [comment]
# Operating System
Linux Ubuntu

# Programming Languages
Python 3.10.12

# CCXT Version
4.0.112

# Description
I am having exactly the same issue and I get the same error "You are not authorized to execute this request."

# How I fixed it
```python
import hmac
import time
import hashlib
import requests
from urllib.parse import urlencode


def fetch_currencies():
  url = 'https://api.binance.com/sapi/v1/capital/config/getall'
  headers= {'X-MBX-APIKEY': BINANCE_API_KEY}

  timestamp, signature = get_timestamp_signature()
  url = f'{url}?timestamp={timestamp}&signature={signature}'
  response = requests.get(
        url,
        headers=headers,
  )


def get_timestamp_signature():
    timestamp = int(time.time() * 1000)  # UNIX timestamp in milliseconds

    params = urlencode({
        "timestamp": timestamp,
    })

    secret = BINANCE_SECRET_KEY
    signature = hmac.new(secret.encode('utf-8'), params.encode('utf-8'),
                         hashlib.sha256).hexdigest()

    return timestamp, signature

```

I used this code and I got a response. I think you should add timestamp and signature for binance APIs.

@carlosmiei

**Comment by alm0ra** [comment]
@carlosmiei please open this issue again @imanmousaei  face this issue ...
and we are still pending

**Comment by alm0ra** [comment]
@kroitor
