### ISSUE TITLE
Inquiry on Optimal Practices for Socket Connection Handling

### ISSUE THREAD

**Issue by kvlknctk** [ccxt/ccxt#19427]
### Operating System

Ubuntu

### CCXT Version

4.0.9

### Description

I have been utilizing the `watchOrderBook` method within a `while` loop as shown in the official examples. However, I have concerns regarding the potential strain on system resources and network traffic. An alternative approach I've considered is using `setInterval`. I am interested in understanding the comparative advantages and disadvantages of these two methods in terms of performance, error handling, and reconnect strategies, especially in a high-frequency data handling scenario. Could you provide insights or recommendations on which approach could be more efficient and reliable? Your guidance will be invaluable for optimizing my implementation. Thank you!

### Code

```
   while (true) {
    const test = await ccxt.watchOrderBook("ETH/USDT", 10);
    console.log(test.timestamp);
  }

```

**Comment by frosty00** [comment]
Both `setInterval` and our code are asynchronous and schedule a callback on the main event loop handler in javascript. Using setInterval would be slower because it would wait an arbitrary period of time before checking if any new messages have arrived whereas our code is notified immediately upon a new websocket message arriving.

At the core of the async-code is a node stream that is asynchronous and uses the select system call to read data from multiple network sockets.

> Could you provide insights or recommendations on which approach could be more efficient and reliable?

So the answer is using setInterval makes no difference and would only add latency to your code

**Comment by kvlknctk** [comment]
You seem to be suggesting that using a while loop would be more beneficial in this case, as far as I understand. However, due to the structure of node.js, I don't know how to start and stop a method that has a while loop. I'm using setInterval because I can control it on a variable like below and cancel it when necessary.

````javascript 
async function watchOrderBookSocket(exchange, coin) {
  const exc = new ccxtPro[exchange]({
    nonce: () => nonce++,
  });

  const symbolName = coin + "/USDT";

  intervals.set(
    `${exchange}:${coin}`,
    setInterval(async () => {
      try {
        const sockData = await exc.watchOrderBook(symbolName, limit);
        const savedData = await localStore.setSocketData(
          exchange,
          coin,
          sockData
        );
      } catch (error) {
        stopOrderBookSocket(exchange, coin, error);
      }
    }, 300)
  );
}

async function stopOrderBookSocket(exchange, coin) {
  const intervalKey = `${exchange}:${coin}`;
  const interval = intervals.get(intervalKey);

  if (interval) {
    clearInterval(interval);
    intervals.delete(intervalKey);
  }
  // do backoff
}
````

**Comment by frosty00** [comment]
you can use node events and check if they have fired

https://nodejs.org/api/events.html#events 

```

const EventEmitter = require('node:events');

class MyEmitter extends EventEmitter {}

const myEmitter = new MyEmitter();

myEmitter.emit('event');

async method () {
   let eventNotFired = true;
   myEmitter.on('event', () => {
      eventNotFired = false
   });
   while (eventNotFired) {
      const test = await ccxt.watchOrderBook("ETH/USDT", 10);
      console.log(test.timestamp);
    }
}

method ()
```

**Comment by kvlknctk** [comment]
So, if you were to save the information we obtain within a while loop to a Redis server or a database, what method would you use?
Thank you first for your patience and interest.

**Comment by frosty00** [comment]
any asynchronous method that writes the data to a database, and make sure to use the await keyword

**Comment by kvlknctk** [comment]
I'm sure I'm using it within the standards, but not using await in every loop in a fast socket connection can quickly consume system resources. In this case, I'm actually asking how I can use a method to transfer the data within the while loop to a different location.

I already have a working mechanism for this. I solved it by using setInterval at controlled intervals. However, I see that while loops are used in all of your examples. So, I'm asking how you can manage async connections in this situation.

I apologize if I couldn't express myself.

**Comment by frosty00** [comment]
if you want to do something periodically in a while loop you can use time intervals like so:

```
const interval = 100000 // ten seconds
const start = Math.floor (Date.now () / interval) * interval
let period = start + interval
while (true) {
    const data = await exchange.watchOrderBook ('ETH/USDT')
    const now = Date.now ()
    if (now > period) {
       await functionToSaveDataToDatabase ()
       period += interval
       continue // get fresh data
    }
    // handle the rest of the data here
}
```

**Comment by kvlknctk** [comment]
Sure, is there any difference between using setInterval in this case?
