### ISSUE TITLE
Bitrue fetch_tickers() 'percentage' is off by some factors of 10

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#19428]
### Operating System

Linux Mint

### Programming Languages

Python

### CCXT Version

4.0.112

### Description

`fetch_tickers` 'percentage' values seem to be off by factor of 10000 in Bitrue exchange when compared against their website. 

For some reason ccxt is currently using Bitrue k-line API endpoint instead of this one: 
https://github.com/Bitrue-exchange/Spot-official-api-docs#24hr-ticker-price-change-statistics

As a matter of fact, ccxt doesn't seem to be using https://openapi.bitrue.com/ url in any of the `exchange` methods, even though it is the base endpoint according to the API documentation:
https://github.com/Bitrue-exchange/Spot-official-api-docs#general-api-information

### Code

``` 
exchange = ccxt.bitrue()
exchange.load_markets()
exchange.verbose = True
print(exchange.fetch_tickers())
```
``` 
fetch Request: bitrue GET https://www.bitrue.com/kline-api/public.json?command=returnTicker RequestHeaders: {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: bitrue GET https://www.bitrue.com/kline-api/public.json?command=returnTicker 200 ResponseHeaders: {'Content-Type': 'text/plain;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Sun, 01 Oct 2023 22:19:04 GMT', 'Vary': 'Accept-Encoding', 'X-Frame-Options': 'SAMEORIGIN', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': ..., 'X-Amz-Cf-Pop': ..., 'X-Amz-Cf-Id': ...} ResponseBody: {"code":"200","msg":"success","data":{"OGN_USDT":{"id":635166276,"last":"0.1412","lowestAsk":"0.1417","highestBid":"0.1389","percentChange":"-0.000355","baseVolume":"3255427","quoteVolume":"459490.5050","isFrozen":"0","high24hr":"0.1541","low24hr":"0.1541"}, ...

{'OGN/USDT': {'symbol': 'OGN/USDT', 'timestamp': None, 'datetime': None, 'high': 0.1541, 'low': 0.1541, 'bid': 0.1389, 'bidVolume': None, 'ask': 0.1417, 'askVolume': None, 'vwap': 0.14114600173802086, 'open': None, 'close': 0.1412, 'last': 0.1412, 'previousClose': None, 'change': None, 'percentage': -0.000355, 'average': None, 'baseVolume': 3255427.0, 'quoteVolume': 459490.505, 'info': {'id': '635166276', 'last': '0.1412', 'lowestAsk': '0.1417', 'highestBid': '0.1389', 'percentChange': '-0.000355', 'baseVolume': '3255427', 'quoteVolume': '459490.5050', 'isFrozen': '0', 'high24hr': '0.1541', 'low24hr': '0.1541'}}, ...
```

**Comment by JovianMoon** [comment]
@carlosmiei I think the most reliable way to confirm the bug is just to compare the number against the one in their website:
https://www.bitrue.com/trade/ltc_usdt

It is the same as in the other endpoint as I mentioned:
https://openapi.bitrue.com/api/v1/ticker/24hr?symbol=LTCUSDT

In other words, the number in that k-line endpoint is probably wrong, an error by Bitrue. (I haven't found the documentation for it though to confirm.)

Also if you want to add a test that can systematically found these kind of problems, maybe you could count all the non-zero 'percentage' values in exchange tickers. If let's say, over 90% of those values are under 0.1%, there might be an "off by factors of ten" bug somewhere.

**Comment by carlosmiei** [comment]
> @carlosmiei I think the most reliable way to confirm the bug is just to compare the number against the one in their website: https://www.bitrue.com/trade/ltc_usdt
> 
> It is the same as in the other endpoint as I mentioned: https://openapi.bitrue.com/api/v1/ticker/24hr?symbol=LTCUSDT
> 
> In other words, the number in that k-line endpoint is probably wrong, an error by Bitrue. (I haven't found the documentation for it though to confirm.)
> 
> Also if you want to add a test that can systematically found these kind of problems, maybe you could count all the non-zero 'percentage' values in exchange tickers. If let's say, over 90% of those values are under 0.1%, there might be an "off by factors of ten" bug somewhere.

@JovianMoon, ok I will try to check it on the website.

> Also if you want to add a test that can systematically found these kind of problems, maybe you could count all the non-zero 'percentage' values in exchange tickers. If let's say, over 90% of those values are under 0.1%, there might be an "off by factors of ten" bug somewhere.

thanks, I think that makes sense, it's certainly odd having a percentage smaller than the tick precision.
