### ISSUE TITLE
Bybit amend order issue - InvalidOrder: bybit price of ETH/USDT:USDT must be greater than minimum price precision of 0.01

### ISSUE THREAD

**Issue by Rishirandhawa** [ccxt/ccxt#19421]
### Operating System

MAC OS

### Programming Languages

Python 3.10.13

### CCXT Version

CCXT Version: 4.0.112

### Description

edit_order throwing retCode":10001,"retMsg":"Request parameter error.". Error log below -

### Verbose

fetch Request: bybit POST https://api.bybit.com/v5/order/create RequestHeaders: {'Content-Type': 'application/json', 'X-BAPI-API-KEY': 'WvZi6kjVy3KvUj6zf8', 'X-BAPI-TIMESTAMP': '1696166745238', 'X-BAPI-RECV-WINDOW': '5000', 'X-BAPI-SIGN': '3c98894f4ab8865b4e549beab150cfbdbf558a68bac8c0659efc8620797d4623', 'Referer': 'CCXT', 'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"symbol":"ETHUSDT","side":"Sell","orderType":"Limit","category":"linear","qty":"0.01","price":"2000","stopLoss":"2100","takeProfit":"1900","positionIdx":2}

fetch Response: bybit POST https://api.bybit.com/v5/order/create 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '141', 'Connection': 'keep-alive', 'Date': 'Sun, 01 Oct 2023 13:25:45 GMT', 'X-Bapi-Limit': '10', 'X-Bapi-Limit-Status': '9', 'X-Bapi-Limit-Reset-Timestamp': '1696166745962', 'Ret_code': '0', 'Traceid': '31a6fef6eb77411a028409d2e675bde4', 'Timenow': '1696166745962', 'Server': 'Openresty', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 aa81fe1b9ec90b1088d56da5a82deaae.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'MAD51-C3', 'X-Amz-Cf-Id': 'hyDWh5smuCEqwJXpJhg85F4Icj1wHWX0ORrHGQJNvLFx31gf0xI7xg=='} ResponseBody: {"retCode":0,"retMsg":"OK","result":{"orderId":"4b289ee4-7c86-466d-96fb-72bb0710aabd","orderLinkId":""},"retExtInfo":{},"time":1696166745962}

fetch Request: bybit POST https://api.bybit.com/v5/order/amend RequestHeaders: {'Content-Type': 'application/json', 'X-BAPI-API-KEY': 'WvZi6kjVy3KvUj6zf8', 'X-BAPI-TIMESTAMP': '1696166745966', 'X-BAPI-RECV-WINDOW': '5000', 'X-BAPI-SIGN': '3781e0baa6981c17d5165adf2295bee7d56ff9e590b1918b30d265a535f27713', 'Referer': 'CCXT', 'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"symbol":"ETHUSDT","orderId":"4b289ee4-7c86-466d-96fb-72bb0710aabd","category":"linear","stopLoss":0,"takeProfit":0}

fetch Response: bybit POST https://api.bybit.com/v5/order/amend 200 ResponseHeaders: {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '102', 'Connection': 'keep-alive', 'Date': 'Sun, 01 Oct 2023 13:25:46 GMT', 'Ret_code': '10001', 'Cache-Control': 'no-store', 'Traceid': 'd1288c2d793aac31a5f2f4018c59a24a', 'Timenow': '1696166746317', 'Server': 'Openresty', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 aa81fe1b9ec90b1088d56da5a82deaae.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'MAD51-C3', 'X-Amz-Cf-Id': 'cPWoUW9cfhxs-F91SPHvTiJv67GjASJ9rJSRPfRPPLcKAQlnKYAi0w=='} ResponseBody: {"retCode":10001,"retMsg":"Request parameter error.","result":{},"retExtInfo":{},"time":1696166746317}

### Error Dump
---------------------------------------------------------------------------
BadRequest                                Traceback (most recent call last)
Cell In[22], line 30
     27 params['takeProfit'] = take_profit
     28 params['stopLoss'] = stop_loss
---> 30 order = exchange.edit_order(id=id, symbol=symbol, type=type, side=side, amount=amount, price=price, params=params)

File ~/projects/trading-bot/py310/lib/python3.10/site-packages/ccxt/bybit.py:3867, in bybit.edit_order(self, id, symbol, type, side, amount, price, params)
   3865     request['orderLinkId'] = clientOrderId
   3866 params = self.omit(params, ['stopPrice', 'stopLossPrice', 'takeProfitPrice', 'triggerPrice', 'clientOrderId', 'stopLoss', 'takeProfit'])
-> 3867 response = self.privatePostV5OrderAmend(self.extend(request, params))
   3868 #
   3869 #     {
   3870 #         "retCode": 0,
   (...)
   3878 #     }
   3879 #
   3880 result = self.safe_value(response, 'result', {})

File ~/projects/trading-bot/py310/lib/python3.10/site-packages/ccxt/base/types.py:26, in Entry.__init__.<locals>.unbound_method(_self, params)
     25 def unbound_method(_self, params={}):
---> 26     return _self.request(self.path, self.api, self.method, params, config=self.config)

File ~/projects/trading-bot/py310/lib/python3.10/site-packages/ccxt/base/exchange.py:3058, in Exchange.request(self, path, api, method, params, headers, body, config)
   3057 def request(self, path, api: Any = 'public', method='GET', params={}, headers: Optional[Any] = None, body: Optional[Any] = None, config={}):
-> 3058     return self.fetch2(path, api, method, params, headers, body, config)

File ~/projects/trading-bot/py310/lib/python3.10/site-packages/ccxt/base/exchange.py:3055, in Exchange.fetch2(self, path, api, method, params, headers, body, config)
   3053 self.lastRestRequestTimestamp = self.milliseconds()
   3054 request = self.sign(path, api, method, params, headers, body)
-> 3055 return self.fetch(request['url'], request['method'], request['headers'], request['body'])

File ~/projects/trading-bot/py310/lib/python3.10/site-packages/ccxt/base/exchange.py:654, in Exchange.fetch(self, url, method, headers, body)
    651     else:
    652         raise ExchangeError(details) from e
--> 654 self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
    655 if json_response is not None:
    656     return json_response

File ~/projects/trading-bot/py310/lib/python3.10/site-packages/ccxt/bybit.py:6976, in bybit.handle_errors(self, httpCode, reason, url, method, headers, body, response, requestHeaders, requestBody)
   6974         feedback = self.id + ' ' + body
   6975     self.throw_broadly_matched_exception(self.exceptions['broad'], body, feedback)
-> 6976     self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
   6977     raise ExchangeError(feedback)  # unknown message
   6978 return None

File ~/projects/trading-bot/py310/lib/python3.10/site-packages/ccxt/base/exchange.py:3421, in Exchange.throw_exactly_matched_exception(self, exact, string, message)
   3419 def throw_exactly_matched_exception(self, exact, string, message):
   3420     if string in exact:
-> 3421         raise exact[string](message)

BadRequest: bybit {"retCode":10001,"retMsg":"Request parameter error.","result":{},"retExtInfo":{},"time":1696166746317}

### Code

```
#Instantiate bybit Exchange and make sure hedge mode is enabled for USDT Perps
exchange_id = 'bybit'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
    'apiKey': "",
    'secret': "",
    'timeout': 30000,
    'verbose': True,
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future',
        'adjustForTimeDifference': True,
    },
})

###### Create order

symbol = 'ETH/USDT:USDT'
type = 'limit'
side = 'sell'
amount = 0.01
price = 2000

params = {}
params['positionIdx'] = 2 ### 1 Long position and 2 Short position
params['takeProfit'] = 1900
params['stopLoss'] = 2100    
order = exchange.create_order(symbol, type, side, amount, price, params)
id = order['id']

####### Update order to cancel TP and SL that was set in create order

id = id ## generated in create order earlier
symbol = 'ETH/USDT:USDT'
type = 'limit'
side = 'sell'
amount = None
price = None

take_profit = 0
stop_loss = 0

params = {}
params['takeProfit'] = take_profit
params['stopLoss'] = stop_loss

order = exchange.edit_order(id=id, symbol=symbol, type=type, side=side, amount=amount, price=price, params=params)

```

**Comment by Dan-krm** [comment]
Hi @Rishirandhawa when you open an issue could you set `'verbose': True,` in the options and share the response:
https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

Are you sure you updated the CCXT version? This line in your response:
`-> 3859 request['stopLoss'] = self.price_to_precision(symbol, slTriggerPrice)`
should now be:
`request['stopLoss'] = slTriggerPrice`

I tried recreating your error and everything is working properly for me now:
```
Python v3.8.10
CCXT v4.0.111
bybit.editOrder(78f10118-dc1f-4a13-96c5-832f1d5d88b8,BTC/USDT:USDT,limit,buy,None,None,{'stopLoss': '0', 'takeProfit': '0'})

{'amount': None,
 'average': None,
 'clientOrderId': None,
 'cost': None,
 'datetime': None,
 'fee': None,
 'fees': [],
 'filled': None,
 'id': '78f10118-dc1f-4a13-96c5-832f1d5d88b8',
 'info': {'result': {'orderId': '78f10118-dc1f-4a13-96c5-832f1d5d88b8',
                     'orderLinkId': ''},
          'retCode': '0',
          'retExtInfo': {},
          'retMsg': 'OK',
          'time': '1696110876556'},
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'postOnly': None,
 'price': None,
 'reduceOnly': None,
 'remaining': None,
 'side': None,
 'status': None,
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': None,
 'takeProfitPrice': None,
 'timeInForce': None,
 'timestamp': None,
 'trades': [],
 'triggerPrice': None,
 'type': None}
```

**Comment by Rishirandhawa** [comment]
@Dan-krm  I have logged the verbose output. As you can see first call was successful and there was no verbose for the second call since it was never initiated. I have confirmed I am using the latest CCXT version. Updated same in the issue description.

This is very strange since I clearly see in dump that its applying -  request['stopLoss'] = self.price_to_precision(symbol, slTriggerPrice)

**Comment by Dan-krm** [comment]
@Rishirandhawa Did you try this command:
`pip install ccxt --upgrade`

**Comment by carlosmiei** [comment]
Hello @Rishirandhawa @Dan-krm ,
These changes were not shipped in yesterday's release. They will be available in the next one (4.0.112)

**Comment by carlosmiei** [comment]
@Rishirandhawa 4.0.112 is out can you update and try again?

**Comment by Rishirandhawa** [comment]
@carlosmiei The precision issue is fixed now and edit_order call is going through, however, the exchange is throwing - retCode":10001,"retMsg":"Request parameter error." . I don't see anything wrong in request referring bybit spec, unless I am missing something.

I have updated the verbose, error log in the issue to provide details of the issue.

**Comment by Rishirandhawa** [comment]
Nevermind I am casting them as a string now before passing to exchange params. Works !
Thanks for the help

**Comment by Dan-krm** [comment]
@Rishirandhawa I opened a pull request so that those values are automatically converted to strings

**Comment by Rishirandhawa** [comment]
@Dan-krm fantastic ! Thanks
