### ISSUE TITLE
kraken futures create order not working 

### ISSUE THREAD

**Issue by scoquillaud564** [ccxt/ccxt#19433]
### Operating System

Mac OS

### Programming Languages

Python

### Description

Hello,
I have been trying in many ways to make it work but no luck, I suspect some issue with the create_order function when authenticating but stand to be corrected

I connect in a classic way using the credentials I generated on https://futures.kraken.com/

api_key = ‘myAPIkey'
api_secret = ‘myAPIsecret'

# Create a Kraken API client
exchange = ccxt.krakenfutures({
'apiKey': api_key,
'secret': api_secret,
enableRateLimit': True,
})

It does connect to the API correctly as for instance I get 
exchange.symbols
Out[237]: 
['1INCH/USD:USD',
 'AAVE/USD:USD',
 'ACH/USD:USD',
 'ADA/USD:USD',
 'AGLD/USD:USD',
 'ALGO/USD:USD',
 'ALICE/USD:USD',
 'ALPHA/USD:USD',
 'ANKR/USD:USD',
 'ANT/USD:USD’,
Etc

All the other fetch type functions work correctly, etc

However a simple trade does not work:

exchange.create_order (symbol='BTC/USD:USD', type='market', side='buy', amount=0.01)
Traceback (most recent call last):

  Cell In[238], line 1
    exchange.create_order (symbol='BTC/USD:USD', type='market', side='buy', amount=0.001)

  File ~/anaconda3/lib/python3.11/site-packages/ccxt/krakenfutures.py:827 in create_order
    response = self.privatePostSendorder(self.extend(request, params))

  File ~/anaconda3/lib/python3.11/site-packages/ccxt/base/types.py:26 in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)

  File ~/anaconda3/lib/python3.11/site-packages/ccxt/base/exchange.py:3058 in request
    return self.fetch2(path, api, method, params, headers, body, config)

  File ~/anaconda3/lib/python3.11/site-packages/ccxt/base/exchange.py:3054 in fetch2
    request = self.sign(path, api, method, params, headers, body)

  File ~/anaconda3/lib/python3.11/site-packages/ccxt/krakenfutures.py:2024 in sign
    secret = self.base64_to_binary(self.secret)  # 3

  File ~/anaconda3/lib/python3.11/site-packages/ccxt/base/exchange.py:1277 in base64_to_binary
    return base64.standard_b64decode(s)

  File ~/anaconda3/lib/python3.11/base64.py:106 in standard_b64decode
    return b64decode(s)

  File ~/anaconda3/lib/python3.11/base64.py:88 in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)

Error: Incorrect padding

I have tried many permutations but no luck to send a simple trade, if anybody could help me it would be hugely appreciated.
thanks in advance
stephane

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @scoquillaud564, please double-check if your api-key/secret are valid and properly formatted (no whitespace, etc). I just tested and seems to be working fine so I suspect the problem is with your keys

```
p krakenfutures createOrder "LTC/USD:USD" limit buy 0.1 50 '{"clientOrderId": "mycustomid2"}'
Python v3.11.5
CCXT v4.1.1
krakenfutures.createOrder(LTC/USD:USD,limit,buy,0.1,50,{'clientOrderId': 'mycustomid2'})
{'amount': 0.1,
 'average': None,
 'clientOrderId': 'mycustomid2',
 'cost': 0.0,
 'datetime': '2023-10-02T14:03:46.444Z',
 'fee': None,
 'fees': [],
 'filled': 0.0,
 'id': 'eda8915d-fb8d-4bbd-b3d4-0ff4343bcb87',
 'info': {'cliOrdId': 'mycustomid2',
          'orderEvents': [{'order': {'cliOrdId': 'mycustomid2',
                                     'filled': '0',
                                     'lastUpdateTimestamp': '2023-10-02T14:03:46.444Z',
                                     'limitPrice': '50',
                                     'orderId': 'eda8915d-fb8d-4bbd-b3d4-0ff4343bcb87',
                                     'quantity': '0.1',
                                     'reduceOnly': False,
                                     'side': 'buy',
                                     'symbol': 'pf_ltcusd',
                                     'timestamp': '2023-10-02T14:03:46.444Z',
                                     'type': 'lmt'},
                           'reducedQuantity': None,
                           'type': 'PLACE'}],
          'order_id': 'eda8915d-fb8d-4bbd-b3d4-0ff4343bcb87',
          'receivedTime': '2023-10-02T14:03:46.444Z',
          'status': 'placed'},
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'postOnly': False,
 'price': 50.0,
 'reduceOnly': None,
 'remaining': 0.1,
 'side': 'buy',
 'status': 'open',
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': 'LTC/USD:USD',
 'takeProfitPrice': None,
 'timeInForce': 'gtc',
 'timestamp': 1696255426444,
 'trades': [],
 'triggerPrice': None,
 'type': 'limit'}
```
