### ISSUE TITLE
Class krakenfutures not found. 

### ISSUE THREAD

**Issue by smamet** [ccxt/ccxt#19437]
### Operating System

ubuntu

### Programming Languages

PHP

### CCXT Version

2.5

### Description

Error when implementing kraken futures: 
Class krakenfutures not found

I am trying to setup krakenfutures (using PHP) but the class does not exist in the library. 

I used composer require ccxt/ccxt to install. Here is the version 
 "require": {
        "ccxt/ccxt": "^2.5",

If I try:

 $exchange = '\\ccxt\\krakenfutures';
        $exchange = new $exchange(array(
            'apiKey' => 'my api key',
            'secret' => 'my secret',
        ));

I have: Class krakenfutures not found. 

I checked in the files of ccxt, I have a kraken.php but no krakenfutures.php. 

When I check on the documentation is says it is supported in ccxt pro. 
When I try to go to ccxt.pro I am redirected to github pages saying that ccxt pro is now merged to ccxt. 

Maybe I misunderstood something because I saw some people saying that they implemented it. I tried to search if I could buy ccxt pro but all I found is that it is now merged.

Can you please help ?

Thanks

### Code

```
   $exchange = '\\ccxt\\krakenfutures';
        $exchange = new $exchange(array(
            'apiKey' => 'my api key',
            'secret' => 'my secret',
        ));

```

**Comment by carlosmiei** [comment]
Hello @smamet,
`KrakenFutures` was added at a later version, so you need to update your CCXT version to access it.

**Comment by smamet** [comment]
Oh, I didn't notice that sorry. Thanks for your help !
