### ISSUE TITLE
Why is createDepositAddress disabled on Bittrex exchange?

### ISSUE THREAD

**Issue by parthsaxena** [ccxt/ccxt#1943]
I can't use the method `createDepositAddress` on the Bittrex exchange. The `has` property for the exchange says the method is not available. Why is it not available despite being outlined in the Bittrex API?

**Comment by kroitor** [comment]
> Why is it not available despite being outlined in the Bittrex API?

It is available, it's just that the `has['createDepositAddress']` is lying now. Will fix it shortly.

**Comment by parthsaxena** [comment]
When I try to use the method `createDepositAddress`, it says the method is not defined. Sorry if I am misunderstanding something, I just began to use this library!

**Comment by kroitor** [comment]
Oh, sorry, it is in fact false for Bittrex.

**Comment by kroitor** [comment]
(use fetchDepositAddress to check on that)

**Comment by parthsaxena** [comment]
Will the method be added? The Bittrex API states that generating addresses is supported.

**Comment by kroitor** [comment]
@parthsaxena it is already implemented, you just need to call the fetchDepositAddress and check for status in the return. This will trigger address generation, if it wasn't created earlier.

**Comment by kroitor** [comment]
This is just how Bittrex works, let us know if this does not answer your question or doesn't help. Thx!
