### ISSUE TITLE
Problem with connecting Binance WebSocket

### ISSUE THREAD

**Issue by sumitgautam0101** [ccxt/ccxt#19438]
### Operating System

Windows 11

### Programming Languages

Python

### CCXT Version

2.2.5

### Description

Hi there, I am trying to connect two WebSocket simultaneously, but one of the WebSocket is blocking other one.
WS 1 : `watch_ohlcv()` (public)
WS 2 : `watch_orders()` (private)

I am using multithreading to spawn two separate child threads each with an infinitely loop that contains WebSocket connection and uses asyncio with seperate event loop but my watch_ohlcv() connection is blocking watch_orders().

Is my implementation wrong or I cant connect to two WS feeds simultaneously? 

### Code

```python

# Code where I spawn child processes
stream_kline_thread = threading.Thread(target=bot.data_api_handler, args=())
watch_orders_thread = threading.Thread(target=bot.order_api_handler, args=())

stream_kline_thread.start()
watch_orders_thread.start()

stream_kline_thread.join()
watch_orders_thread.join()

--------------------------------------------------

# Functions for Order WS connection

def order_api_handler(self):
        
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        loop.run_until_complete(self.stream_orders())

async def stream_orders(self):
        while True:
            orders = await self.exchange.watch_orders(self.symbol)
            print("Orders Data : ",orders)
            time.sleep(1)

# Functions for OHLCV WS connection

def data_api_handler(self):

        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        loop.run_until_complete(self.start_streaming())

async def start_streaming(self):
        while True:
            ohlcv = await self.exchange.watch_ohlcv(self.symbol)
            print("Latest OHLCV : ",ohlcv)




```

**Comment by sumitgautam0101** [comment]
I have also tested it with latest CCXT version --> 4.1.2

**Comment by carlosmiei** [comment]
Hello @sumitgautam0101, does the same happen when you run everything in the same thread? 
If you do the same but with different methods (for instance watchTrades/watchOHLCV/watchTicker) do you get the same behavior? (trying to understand if this issue is specific to the aforementioned methods or not)

**Comment by sumitgautam0101** [comment]
One more question! Is there any way to modify stop limit orders just like limit orders? order cancelation and new order placement is the only way for now?

**Comment by pcriadoperez** [comment]
Hi @sumitgautam0101,

>   ohlcv_data = await exch.watch_ohlcv("BTCUSDT", "1m")
  print(f"Last OLHCV : {ohlcv_data}")
  order_data = await exch.watch_balance()
  print(f"Recent Order : {order_data}")

in this example did you execute a trade or something to change the balance after `watch_balance()` is called?

**Comment by sumitgautam0101** [comment]
Hello @pcriadoperez, Yes, It prints the output if the balance is changed but why it's blocking the complete thread?

**Comment by pcriadoperez** [comment]
Hi @sumitgautam0101, that is the expected behavior of using await and watch_balance, it waits until there is an update.
I'll close this issue for now, but feel free to reach out with any questions.
