### ISSUE TITLE
Is margin trading supported for bitget?

### ISSUE THREAD

**Issue by Avarong** [ccxt/ccxt#19440]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

3.1.8

### Description

I have tried the available examples to set an order for margin trading, but none works.

```python
client=ccxtpro.bitget({'enableRateLimit':False,'newUpdates':True,'apiKey':api_key,'secret':api_secret,'password':pswd,})
await client.create_order('BCH/USDT',type='limit',side='buy',amount=0.1,price=245,params={'type':'margin'})
This option gives an error-ccxt.base.errors.NotSupported: bitget margin does not have a value in mapping

await client.create_order('BCH/USDT',type='limit',side='buy',amount=0.1,price=245,params={'margin_trading': '2',})
await client.create_order('BCH/USDT',type='limit',side='buy',amount=0.1,price=245,params={'marginMode':'cross',})
These two conduct the transaction simply on the spot.
```

If margin trading is possible, please write an example of placing an order (preferably with auto-loan / auto-repayment)!

**Comment by Dan-krm** [comment]
Hi @Avarong I've opened a series of pull requests to add margin support to Bitget, once the createOrders PR is merged, this issue will close, margin trading will be fully supported and exchange.has['margin'] will be set to true
