### ISSUE TITLE
No access to getPrivateV5PositionList in Bybit

### ISSUE THREAD

**Issue by Rishirandhawa** [ccxt/ccxt#19441]
### Operating System

MAC

### CCXT Version

4.0.112

### Description

Hi, I would like to have private access to exchange `positions/list` endpoint
Seems `getPrivateV5PositionList` is not exposed.

Could you please expose it ?

Dealing with random 414 errors and want to make direct position list call to rule out issues

**Comment by samgermain** [comment]
I don't exactly know what you mean by exposed, but exposing it doesn't sound like something we can do, and you might have to fix your api keys or set them up.

The endpoint works fine for me though

```
% bybit privateGetV5PositionList '{"category": "linear", "settleCoin": "USDC"}'
2023-10-03T21:22:42.627Z
Node.js: v18.15.0
CCXT v4.0.109
bybit.privateGetV5PositionList ([object Object])
2023-10-03T21:22:47.375Z iteration 0 passed in 763 ms

{
  retCode: '0',
  retMsg: 'OK',
  result: { nextPageCursor: '', category: 'linear', list: [] },
  retExtInfo: {},
  time: '1696368167308'
}
2023-10-03T21:22:47.375Z iteration 1 passed in 763 ms
```

----------------

I recommend just using the [unified `fetchPositions` method](https://docs.ccxt.com/#/README?id=positions) though, it will be easier

**Comment by Rishirandhawa** [comment]
I see bybit's JS file has the described the api in exchange class definition for the endpoint access. I am using Python. Py file doesn't has it described. So when I the private method, it just says invalid. That's what I mean by exposing, unless I am misinterpreting something.

**Comment by sc0Vu** [comment]
@Rishirandhawa  Try this function in bybit "`privateGetV5PositionList`".

**Comment by carlosmiei** [comment]
@Rishirandhawa As @sc0Vu suggested that method exists but under a different name `privateGetV5PositionList`.  However, you can use the unified `fetch_positions` method instead which already uses that endpoint under the hood.

**Comment by Rishirandhawa** [comment]
Thanks guys this works -
params['category'] = 'linear' 
params['symbol'] = 'XRPUSDT' 
pos = exchange.privateGetV5PositionList(params)
json.dumps(pos)

I have been on the unified fetch_positions method so far but am getting random 414 errors like below -

Main loop error exit bot-17
Time (UTC): 2023-10-04 20:03 
Margin Ratio: 1.02417500823395159 
[Errno Expecting value] <html> 
<head><title>414 Request-URI Too Large</title></head> 
<body> 
<center><h1>414 Request-URI Too Large</h1></center> 
<hr><center>nginx</center> 
</body> 
</html> 
: 0
