### ISSUE TITLE
suddenly, exchange.fapiPublic_get_fundingrate() doesn't work.

### ISSUE THREAD

**Issue by BamsoonPapa** [ccxt/ccxt#19453]
### Operating System

Windows Server 2022 English Full Base

### Programming Languages

Python

### CCXT Version

4.1.2

### Description

Below code works well for one year.
(to get fundingrate info. between two timestamps)

result = exchange.fapiPublic_get_fundingrate(~~~)

But suddenly, it doesn't work.
So I tried rename like below code.

~~ fapiPublicGetFundingrate ~~

But it doesn't work.
Help me, please.

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @BamsoonPapa 

Try `fapiPublicGetFundingRate`.

**Comment by BamsoonPapa** [comment]
Hi @sc0Vu 
I'll try it, thanks a lot.
Can I access to CCXT Document for 'fapiPublicGetFundingRate'? Could you give me link?

**Comment by sc0Vu** [comment]
Hi @BamsoonPapa 

Currently, we don't have documentation for implicit methods that transformed from api path automatically. For implicit api, here is the link for documentation https://github.com/ccxt/ccxt/wiki/Manual#api-methods--endpoints.

Let me know if you have other questions.
