### ISSUE TITLE
Yobit fetchOrders inconsistency

### ISSUE THREAD

**Issue by gsdean** [ccxt/ccxt#1945]
Seems like Yobit might not support `fetchOrders` without a symbol param. I get an exchange error _"invalid pair_". For consistency we should consider handling this the same way we do for other exchanges that do not support fetchOrders for all symbols. i.e. for Binance we do the following:

```
        if (!symbol)
            throw new ExchangeError (this.id + ' fetchOrders requires a symbol param');
```

happy to provide a PR, if there is consensus here

- OS: OSX
- Programming Language version: v9.4.0
- CCXT version: 1.10.1138
- Exchange: yobit
- Method: fetchOrders

**Comment by kroitor** [comment]
I've fixed it already, but, your contributions are welcome, feel free to submit your commits, just make sure to read this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

Thx for reporting!

**Comment by gsdean** [comment]
Much better solution, I was going to suggest `fetchOrdersRequiresSymbol` as an enhancement anyway. Right now I'm playing wackamole special casing `fetchOrders`

Also do you ever sleep?

**Comment by kroitor** [comment]
> I was going to suggest fetchOrdersRequiresSymbol as an enhancement anyway. 

I did it in an exchange-specific fashion, so we can't rely on that particular thing to be available everywhere, this comes as a quick adhoc fix to your specific issue. Yet, to fix it in general, we will need to define required args for all methods, and it has to be done in a different, more extendable way... But no worries, we will target this issue, as we of course, are well aware of it. Will address it a little later )
