### ISSUE TITLE
kraken.py: TypeError: object of type 'NoneType' has no len() in parse_order

### ISSUE THREAD

**Issue by rjnrjn** [ccxt/ccxt#19473]
### Operating System

ubuntu 22.04

### Programming Languages

Python

### CCXT Version

4.1.4

### Description

Error is new in 4.1.4 (and 4.1.5)
using kraken create_limit_order
order is executed but error on parsing results.

4.1.3 works ok, so in the mean time i have:
ccxt==4.1.3 in requirements.txt

Error:

```
    order_response = ccxtclt.create_limit_order(symbol=symbol_s, side=side, amount=quantitystr, price=pricestr)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rhttst/rhttst/venv/lib/python3.11/site-packages/ccxt/base/exchange.py", line 3631, in create_limit_order
    return self.create_order(symbol, 'limit', side, amount, price, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rhttst/rhttst/venv/lib/python3.11/site-packages/ccxt/kraken.py", line 1234, in create_order
    return self.parse_order(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rhttst/rhttst/venv/lib/python3.11/site-packages/ccxt/kraken.py", line 1407, in parse_order
    for i in range(0, len(rawTrades)):
                      ^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

```

### Code

using:
symbol_s='SOL/USD'
side='buy'
amount='1.00000000'
price='23.17000000'
```
order_response = ccxtclt.create_limit_order(symbol=symbol_s, side=side, amount=quantitystr, price=pricestr)  

```

**Comment by carlosmiei** [comment]
Hello @rjnrjn, thanks for letting us know, we will fix it asap.

**Comment by rjnrjn** [comment]
Hi @carlosmiei @kroitor ,
Thanks for the quik solution!
I updated to 4.1.6 and it's working again :-)
Best regards,
Ruurd

**Comment by rjnrjn** [comment]
btw, should i set a fixed version in requirements.txt to stay at a stable release?
Are there ga / stable / rc / beta versions, can i see it in the version number?

**Comment by carlosmiei** [comment]
@rjnrjn No we don't have that specificity but unless it's a major version upgrade it should be okay to always have the latest available version, APIs are very dynamic, so we're constantly fixing bugs and implementing new features.
