### ISSUE TITLE
Does CCXT contain this btcalpha exchange？

### ISSUE THREAD

**Issue by qwe231cvb** [ccxt/ccxt#19487]
### Operating System

Ubuntu 18.04

### Programming Languages

Python

### CCXT Version

Version: 4.1.4 

### Description

Does CCXT contain this btcalpha exchange:
https://btc-alpha.com/

If this exchange is included？should the btcalpha exchange API be added to the python code like this？

### Code

```
  import ccxt
import time
from pprint import pprint

btcalpha = ccxt.btcalpha({
    'apiKey': 'my_apikey',
    'secret': 'my_secret',
})
b = 0
amount = 4
symbol = 'XRP/USDT'
order = btcalpha.createOrder(symbol, 'market', 'buy', amount)
order = btcalpha.fetch_order(order['id'], order['symbol'])
order_status = order['status']
print("Order status:", order_status)
while b == 0:
    order = btcalpha.fetch_order(order['id'], order['symbol'])
    order_status = order['status']
    print("Order status:", order_status)
    time.sleep(1)

```

**Comment by carlosmiei** [comment]
Hello @qwe231cvb,

Yes, btcalpha is integrated into CCXT, and yes you can do that to access it.
