### ISSUE TITLE
Bitlish OHLCV formatting

### ISSUE THREAD

**Issue by c006** [ccxt/ccxt#1948]
- OS: Debian 8
- Programming Language version: PHP
- CCXT version:
- Exchange: BITLISH
- Method: fetch_ohlcv('BTC/EUR', '5m')

Currently I get the following.

Array
(
    [list] => Array
        (
            [0] => Array
                (
                    [data] => Array
                        (
                            [btceur] => Array
                                (
                                    [close] => 9294.9000000000000000
                                    [close_ts] => 1516395854009390
                                    [high] => 9294.9000000000000000
                                    [low] => 9294.9000000000000000
                                    [open] => 9294.9000000000000000
                                    [open_ts] => 1516395854009390
                                    [volume] => 0.2048725600000000
                                )

                            [btcrub] => Array
                                (
                                    [close] => 704461.0000000000000000
                                    [close_ts] => 1516396664379117
                                    [high] => 704461.0000000000000000
                                    [low] => 704461.0000000000000000
                                    [open] => 704461.0000000000000000
                                    [open_ts] => 1516396664379117
                                    [volume] => 0.0135157900000000
                                )

                            [btcusd] => Array
                                (
                                    [close] => 11648.4000000000000000
                                    [close_ts] => 1516398826544854
                                    [high] => 11648.4000000000000000
                                    [low] => 11648.4000000000000000
                                    [open] => 11648.4000000000000000
                                    [open_ts] => 1516398107860052
                                    [volume] => 0.1965888700000000
                                )

                            [ethbtc] => Array
                                (
                                    [close] => 0.0901800000000000
                                    [close_ts] => 1516396473571664
                                    [high] => 0.0901800000000000
                                    [low] => 0.0901800000000000
                                    [open] => 0.0901800000000000
                                    [open_ts] => 1516396473571664
                                    [volume] => 0.0510090900000000
                                )

                            [ethusd] => Array
                                (
                                    [close] => 1052.5400000000000000
                                    [close_ts] => 1516399122431664
                                    [high] => 1052.5400000000000000
                                    [low] => 1052.4400000000000000
                                    [open] => 1052.4400000000000000
                                    [open_ts] => 1516399122428704
                                    [volume] => 0.0269267100000000
                                )

                            [ltcbtc] => Array
                                (
                                    [close] => 0.0169200000000000
                                    [close_ts] => 1516396078580853
                                    [high] => 0.0169200000000000
                                    [low] => 0.0169200000000000
                                    [open] => 0.0169200000000000
                                    [open_ts] => 1516396078580853
                                    [volume] => 0.5851063800000000
                                )

                            [ltceur] => Array
                                (
                                    [close] => 171.4600000000000000
                                    [close_ts] => 1516396611564763
                                    [high] => 171.4600000000000000
                                    [low] => 171.4600000000000000
                                    [open] => 171.4600000000000000
                                    [open_ts] => 1516396611564763
                                    [volume] => 0.0333186200000000
                                )

                            [ltcusd] => Array
                                (
                                    [close] => 186.8300000000000000
                                    [close_ts] => 1516399007350891
                                    [high] => 196.3300000000000000
                                    [low] => 186.8300000000000000
                                    [open] => 194.6100000000000000
                                    [open_ts] => 1516396569251747
                                    [volume] => 13.2656133800000000
                                )

                        )

                    [from] => 1516395600
                    [to] => 1516399200
                )

            [1] => Array
                (
                    [data] => Array
                        (
                            [btceur] => Array
                                (
                                    [close] => 9359.9000000000000000
                                    [close_ts] => 1516401226817720
                                    [high] => 9359.9000000000000000
                                    [low] => 9359.9000000000000000
                                    [open] => 9359.9000000000000000
                                    [open_ts] => 1516399718778829
                                    [volume] => 0.8469000000000000
                                )

                            [btcrub] => Array
                                (
                                    [close] => 703654.0000000000000000
                                    [close_ts] => 1516401392545404
                                    [high] => 703654.0000000000000000
                                    [low] => 703654.0000000000000000
                                    [open] => 703654.0000000000000000
                                    [open_ts] => 1516401392545404
                                    [volume] => 0.8130081800000000
                                )

                            [btcusd] => Array
                                (
                                    [close] => 11518.9000000000000000
                                    [close_ts] => 1516401221506098
                                    [high] => 11518.9000000000000000
                                    [low] => 11518.9000000000000000
                                    [open] => 11518.9000000000000000
                                    [open_ts] => 1516401221506098
                                    [volume] => 0.4145000000000000
                                )

                            [dshrub] => Array
                                (
                                    [close] => 51364.0000000000000000
                                    [close_ts] => 1516401276943446
                                    [high] => 51364.0000000000000000
                                    [low] => 51364.0000000000000000
                                    [open] => 51364.0000000000000000
                                    [open_ts] => 1516401276943446
                                    [volume] => 0.0925880000000000
                                )

                            [ethbtc] => Array
                                (
                                    [close] => 0.0907600000000000
                                    [close_ts] => 1516402648439413
                                    [high] => 0.0907600000000000
                                    [low] => 0.0907300000000000
                                    [open] => 0.0907300000000000
                                    [open_ts] => 1516402463062812
                                    [volume] => 0.3926895400000000
                                )

                            [ethusd] => Array
                                (
                                    [close] => 994.9900000000000000
                                    [close_ts] => 1516399234340200
                                    [high] => 995.0900000000000000
                                    [low] => 994.9900000000000000
                                    [open] => 995.0900000000000000
                                    [open_ts] => 1516399234336634
                                    [volume] => 0.0268000000000000
                                )

                            [ltcusd] => Array
                                (
                                    [close] => 196.4000000000000000
                                    [close_ts] => 1516402557038900
                                    [high] => 196.4000000000000000
                                    [low] => 196.3700000000000000
                                    [open] => 196.3700000000000000
                                    [open_ts] => 1516399262864876
                                    [volume] => 4.5896060900000000
                                )

                            [zecbtc] => Array
                                (
                                    [close] => 0.0440000000000000
                                    [close_ts] => 1516400970392385
                                    [high] => 0.0440000000000000
                                    [low] => 0.0440000000000000
                                    [open] => 0.0440000000000000
                                    [open_ts] => 1516400970392385
                                    [volume] => 0.0020000000000000
                                )

                            [zecusd] => Array
                                (
                                    [close] => 521.2000000000000000
                                    [close_ts] => 1516401074640473
                                    [high] => 521.2000000000000000
                                    [low] => 487.8000000000000000
                                    [open] => 487.8000000000000000
                                    [open_ts] => 1516401047664885
                                    [volume] => 3.8610201000000000
                                )

                        )

                    [from] => 1516399200
                    [to] => 1516402800
                )

            [2] => Array
                (
                    [data] => Array
                        (
                            [btceur] => Array
                                (
                                    [close] => 9364.0000000000000000
                                    [close_ts] => 1516405672812614
                                    [high] => 9364.0000000000000000
                                    [low] => 9364.0000000000000000
                                    [open] => 9364.0000000000000000
                                    [open_ts] => 1516402820409954
                                    [volume] => 1.3710961100000000
                                )

                            [btcrub] => Array
                                (
                                    [close] => 703220.0000000000000000
                                    [close_ts] => 1516404782175804
                                    [high] => 703220.0000000000000000
                                    [low] => 703220.0000000000000000
                                    [open] => 703220.0000000000000000
                                    [open_ts] => 1516404782175804
                                    [volume] => 0.3520308000000000
                                )

                            [dshbtc] => Array
                                (
                                    [close] => 0.0735800000000000
                                    [close_ts] => 1516405685987158
                                    [high] => 0.0735800000000000
                                    [low] => 0.0735800000000000
                                    [open] => 0.0735800000000000
                                    [open_ts] => 1516405685987158
                                    [volume] => 1.3835281300000000
                                )

                            [ethbtc] => Array
                                (
                                    [close] => 0.0906500000000000
                                    [close_ts] => 1516405144119132
                                    [high] => 0.0906500000000000
                                    [low] => 0.0906000000000000
                                    [open] => 0.0906000000000000
                                    [open_ts] => 1516404339543133
                                    [volume] => 3.7062000000000000
                                )

                            [ethrub] => Array
                                (
                                    [close] => 63580.0000000000000000
                                    [close_ts] => 1516404520763366
                                    [high] => 63580.0000000000000000
                                    [low] => 63580.0000000000000000
                                    [open] => 63580.0000000000000000
                                    [open_ts] => 1516404371360034
                                    [volume] => 1.1452425100000000
                                )

                            [ltceur] => Array
                                (
                                    [close] => 171.3900000000000000
                                    [close_ts] => 1516405115526663
                                    [high] => 171.3900000000000000
                                    [low] => 171.3900000000000000
                                    [open] => 171.3900000000000000
                                    [open_ts] => 1516405115526663
                                    [volume] => 22.2883000000000000
                                )

                            [ltcusd] => Array
                                (
                                    [close] => 194.1300000000000000
                                    [close_ts] => 1516405091474047
                                    [high] => 194.1300000000000000
                                    [low] => 194.1200000000000000
                                    [open] => 194.1200000000000000
                                    [open_ts] => 1516405091471191
                                    [volume] => 19.6777000000000000
                                )

                            [zecusd] => Array
                                (
                                    [close] => 514.5000000000000000
                                    [close_ts] => 1516404352728304
                                    [high] => 514.5000000000000000
                                    [low] => 514.5000000000000000
                                    [open] => 514.5000000000000000
                                    [open_ts] => 1516404352728304
                                    [volume] => 3.7123420700000000
                                )

                        )

                    [from] => 1516402800
                    [to] => 1516406400
                )

I added this update.

>php/bitlish.php

    public function fetch_ohlcv($symbol, $timeframe = '1m', $since = NULL, $limit = NULL, $params = [])
    {
        $this->load_markets();
        // $market = $this->market ($symbol);
        $now = $this->seconds();
        $start = $now - 86400 * 30; // last 30 days
        $interval = [(string)$start, NULL];
        $result = $this->publicPostOhlcv(array_merge(['time_range' => $interval,
                                                     ], $params));
        return $this->convert_ohlcv($symbol, $result);
    }

    /**
     * @param string $symbol
     * @param array $ohlcv
     * @return array
     */
    protected function convert_ohlcv($symbol = '', $ohlcv = [])
    {
        $symbol = strtolower(str_replace('/', '', $symbol));
        $array = [];

        foreach ($ohlcv['list'] as $item) {

            if (sizeof($item['data'])) {

                if (isset($item['data'][$symbol])) {

                    $array[] = [
                        0 => $item['data'][$symbol]['open_ts'],
                        1 => $item['data'][$symbol]['open'],
                        2 => $item['data'][$symbol]['high'],
                        3 => $item['data'][$symbol]['low'],
                        4 => $item['data'][$symbol]['close'],
                        5 => $item['data'][$symbol]['volume'],
                    ];
                }
            }
        }

        return $array;
    }

>Output

Array
(
    [0] => Array
        (
            [0] => 1516395854009390
            [1] => 9294.9000000000000000
            [2] => 9294.9000000000000000
            [3] => 9294.9000000000000000
            [4] => 9294.9000000000000000
            [5] => 0.2048725600000000
        )

    [1] => Array
        (
            [0] => 1516399718778829
            [1] => 9359.9000000000000000
            [2] => 9359.9000000000000000
            [3] => 9359.9000000000000000
            [4] => 9359.9000000000000000
            [5] => 0.8469000000000000
        )

    [2] => Array
        (
            [0] => 1516402820409954
            [1] => 9364.0000000000000000
            [2] => 9364.0000000000000000
            [3] => 9364.0000000000000000
            [4] => 9364.0000000000000000
            [5] => 1.3710961100000000
        )

    [3] => Array
        (
            [0] => 1516408222590699
            [1] => 9402.5000000000000000
            [2] => 9484.4000000000000000
            [3] => 9402.5000000000000000
            [4] => 9484.4000000000000000
            [5] => 1.4231208100000000
        )

**Comment by kroitor** [comment]
Related: #987

**Comment by kroitor** [comment]
I'd suggest to move this discussion to #987, if you don't mind. Thanks for the proposal, we will definitely take it into consideration when we will be fixing it (hopefully soon). Closing this for now as a duplicate. Thx!

**Comment by c006** [comment]
Hi. I read through the other post and I would not consider it a duplicate. 

This only has to do with formatting, not time back.

Anyways, it looks like you are slammed with requests.
The code is ready to go it you choose to add it in.

Regards
