### ISSUE TITLE
Huobi PRO: fetch_tickers returns no percentage

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [ccxt/ccxt#1949]
Hello. First of all, I thank all people who created and maintaining this lib.

When I try to fetch_tickers by using python lib from huobi.pro it shows that `percentage`, `average` and `change` values are equal to None:

    h.fetch_ticker('ETH/BTC')
    {'symbol': 'ETH/BTC', 'timestamp': 1519020859412, 'datetime': '2018-02-19T06:14:19.412Z', 'high': 
      0.089477, 'low': 0.086222, 'bid': None, 'ask': None, 'vwap': None, 'open': 0.087987
      , 'close': 0.088054, 'first': None, 'last': None, 'change': None, 'percentage': None, 'average': None, 
       'baseVolume': 8926.4305, 'quoteVolume': 785.2704962632, 'info': {'amount': 892
       6.4305, 'open': 0.087987, 'close': 0.088054, 'high': 0.089477, 'id': 2687866643, 'count': 31121, 'low': 
       0.086222, 'version': 2687866643, 'ask': [0.088051, 5.38], 'vol': 785.27049626
       32, 'bid': [0.087955, 0.0011]}}

Does this mean that huobi does not provide that kind of info?

What kind of values should I use in order to calculate percentage manually?

- OS: Windows 10
- Programming Language version: Python
- CCXT version: 1.10.1110
- Exchange: Huobi PRO
- Method: fetch_ticker

**Comment by mkutny** [comment]
What huobi natively provides is stored in the `info` property. Ccxt puts exchange's json-parsed but uninterpreted response there.

If you happen to notice that some of the `info` fields are improperly interpreted then you've found a bug that should be fixed.

**Comment by SuperMasterBlasterLaser** [comment]
@mkutny Well I see that `ask` and `bid` are there and they are improperly interpreted.

Are there some kind of params for `fetch_ticker` in order to get previous days ticker value?

I want to calculate percentage change of currencies in huobi and I'm trying to use this formula:

    current - previousday = change
    percentchange = (change / lastprice) * 100

**Comment by mkutny** [comment]
> Well I see that ask and bid are there and they are improperly interpreted.

You know... you discovered a bug at the very core of ccxt library! )

> Are there some kind of params for fetch_ticker in order to get previous days ticker value?

I'd suggest to use OHLCV for this purpose instead.

**Comment by kroitor** [comment]
Fixed in ccxt 1.10.1153, thx to @mkutny for resolving it! 

@SuperMasterBlasterLaser kwl nickname btw )

**Comment by SuperMasterBlasterLaser** [comment]
@kroitor Than you :)
