### ISSUE TITLE
OKX BrokerId and clientOrderId

### ISSUE THREAD

**Issue by KevinBaudin** [ccxt/ccxt#19506]
### Operating System

Ubuntu 22.04

### Programming Languages

Python

### CCXT Version

4.0.49

### Description

Hi everyone
I was working on OKX and wanted to provide both a client order id and a broker id
I found this in your code that is blocking me, is it intended? 
Thanks in advance

### Code

```
        if clientOrderId is None:
            brokerId = self.safe_string(self.options, 'brokerId')
            if brokerId is not None:
                request['clOrdId'] = brokerId + self.uuid16()
                request['tag'] = brokerId
        else:
            request['clOrdId'] = clientOrderId
            params = self.omit(params, ['clOrdId', 'clientOrderId'])

```

**Comment by carlosmiei** [comment]
Hello @KevinBaudin, What's blocking you exactly? Bear in mind that the values inside `params` override the `request` values.

**Comment by KevinBaudin** [comment]
The fact that I provide a brokerId in options is only read if I do not provide a client order id in the params, right?
But you tell me that I can provide "tag" in params and circumvent it, right?

**Comment by carlosmiei** [comment]
@KevinBaudin 
> But you tell me that I can provide "tag" in params and circumvent it, right?

Exactly

**Comment by KevinBaudin** [comment]
Great ! Also in the "sign" function I would need to provide it in params for the same reason right? But I don't think I would need it, I never used it imo. If you tell me that it would not be blocking, everything is fine for me

**Comment by carlosmiei** [comment]
@KevinBaudin The `params` provided to the unified method will get to `sign` so it should be ok.
