### ISSUE TITLE
ccxt.async.poloniex: IndexError: string index out of range

### ISSUE THREAD

**Issue by stonemonk** [ccxt/ccxt#1950]
Crash when HTTP 500 occurs and body is empty:

<img width="887" alt="screen shot 2018-02-19 at 4 14 09 pm" src="https://user-images.githubusercontent.com/5236934/36370069-314b6dfe-1590-11e8-8524-4a565b0b53d6.png">

**Comment by kroitor** [comment]
Thank you for reporting, fixed by @mkutny in ccxt version 1.10.1146.
