### ISSUE TITLE
Deribit: unified fetch_balance producing error because code from code_from_options method is NoneType

### ISSUE THREAD

**Issue by ryanmccoy** [ccxt/ccxt#19514]
### Operating System

Ubuntu 22.04.2 LTS

### Programming Languages

Python

### CCXT Version

4.1.9

### Description

Since updating to the latest ccxt using the fetch_balance method raises the following Exception:

`TypeError: can only concatenate str (not "NoneType") to str`

Seems like this is because the method `code_from_options()` is returning None now, for reasons I am unsure of.

The stack trace (excerpt):

```
    832 code = self.code_from_options('fetchBalance', params)
--> 833 currency = self.currency(code)
    834 request = {
    835     'currency': currency['id'],
    836 }
    837 response = self.privateGetGetAccountSummary(self.extend(request, params))
```

### Code

```
import ccxt
options = { "apiKey": "REDACTED", "secret": "REDACTED", "options": {"defaultType": "swap", "defaultSubType": "inverse"}}
exch = ccxt.deribit(options)
exch.load_markets()
exch.fetch_balance()
```

**Comment by carlosmiei** [comment]
Hello @ryanmccoy, thanks for reporting it, we will take a look asap.
