### ISSUE TITLE
Binance papi call error

### ISSUE THREAD

**Issue by VadymPoliak** [ccxt/ccxt#19511]
### Operating System

Ubuntu

### Programming Languages

Python

### CCXT Version

4.1.9

### Description

When I call Binance papi, it caused and Unauthorized error. I checked ccxt library and found that it sends a request without signature. So I changed line 7757 in binance.py to include (api == 'papi') and it worked. Please check this issue and update ccxt.

### Code

```
  
elif (api == 'papi') or (api == 'private') or (api == 'eapiPrivate') or (api == 'sapi' and path != 'system/status') or (api == 'sapiV2') or (api == 'sapiV3') or (api == 'sapiV4') or (api == 'wapi' and path != 'systemStatus') or (api == 'dapiPrivate') or (api == 'dapiPrivateV2') or (api == 'fapiPrivate') or (api == 'fapiPrivateV2'):

```

**Comment by VadymPoliak** [comment]
Thank you for your fast fix. I checked it but fixed for ts. And I am using Python. could you fix it, too?

**Comment by carlosmiei** [comment]
@VadymPoliak the Python version derives from the Typescript, so no worries will be updated as well.

**Comment by VadymPoliak** [comment]
And I have found another issue. The endpoint for GET /papi/v1/cm/income in abstract/binance.py file is incorrect. It includes unnecessary space. Like "/papi/v1/cm/income ". Could you please check and fix it?
