### ISSUE TITLE
Bingx gbp/jpy symbol not available in markets

### ISSUE THREAD

**Issue by mmaestrini** [ccxt/ccxt#19522]
### Operating System

OSX

### Programming Languages

JavaScript

### CCXT Version

4.0.3

### Description

Hi everyone,

I'm new to this library and the documentation is great. I am trying to create the foundation for my code to execute some orders for FOREX, which is available in BingX, however when i instantiate my client and I use loadMarkets() I don't get any of the forex, stocks, indices, etc. Why is that? What am I missing? are they just not supported? What would happen if i know the symbol is GBP/JPY and i just create an order with that? would that work?

Cheers and thanks for an awesome project.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @mmaestrini,
Unfortunately I don't think Bingx provides forex trading through the API, so we can't integrate it into ccxt.

**Comment by mmaestrini** [comment]
@carlosmiei Oh damn! I just asked support. That's so insane why they arent allowing that. It's the only reason why i even have an account there. Especially because you can see that we have access to the swap api via the client... Thanks for the prompt response though! appreciate it!

Are you aware of any other exchanges where FOREX/STOCKS are available via API btw?

**Comment by carlosmiei** [comment]
@mmaestrini Right now I don't think any of the listed exchanges support FOREX/STOCKS trading.
