### ISSUE TITLE
Which exchange has the lowest fees for limit orders?

### ISSUE THREAD

**Issue by qwe231cvb** [ccxt/ccxt#19534]
### Programming Languages

Python

### CCXT Version

Version: 4.1.4 

### Description

The handling fee for limit orders on some exchanges is 0.001. Which exchange has a lower handling fee for limit orders than 0.001? Which exchange has the lowest fees for limit orders?

### Code

```
  

```

**Comment by anonFacePalm** [comment]
This depends on many factors including what you are trading, what country you are in (the exchanges available to you), the volume of your trading in the last lookback period (typically 30-days), the amount of exchange-specific tokens you hold, whether you are paying fees with the exchange-specific token, any introductory or special offers, and sometimes whether you have a VIP level on other exchanges.

Most exchanges have a document on their website, support website, or API documentation that describes these factors and how they affect the fees incurred.

If your question is how to use CCXT to find base trading fees on a specified exchange:
Most of the time, you can get the info from the markets property. More info is at:  https://docs.ccxt.com/#/README?id=trading-fees   But if you need more specific data, it looks like most of the exchanges completely implement either 'fetchTradingFee' or 'fetchTradingFees'.  (Only a couple exchanges seem to have 'calculateFee' at present.)

**Comment by pcriadoperez** [comment]
Closing as it looks answered for now, but feel free to reach out with any other questions
