### ISSUE TITLE
BingX's v1 API will be discontinued

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#19533]
https://support.bingx.com/hc/en-001/articles/23799046013593-BingX-s-Open-API-Domain-and-Feature-Upgrade
Until 2023-11-30 all features on V1 interface will be discontinued. I see ccxt uses some v1 endpoints

**Comment by carlosmiei** [comment]
@ndubel Thanks for letting us know, we will update it soon.

**Comment by carlosmiei** [comment]
@sc0Vu @ndubel, I checked with them, and we're not affected by this update.
Thanks anyway!
