### ISSUE TITLE
EXMO exchange USDT/RUB doesn't exits

### ISSUE THREAD

**Issue by Osmyakov** [ccxt/ccxt#19552]
### Operating System

NodeJS

### Programming Languages

JavaScript

### CCXT Version

4.1.11

### Description

When I try to receive data on a pair of USDT/RUB for EXMO, I get a message that such a pair is not on the exchange.
Also this pair is not available if you make a request
`const markets = await exchange.loadMarkets(true);`
The problem looks similar to the one discussed here: https://github.com/ccxt/ccxt/issues/6964

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @Osmyakov, you sure that pair is available? Can you send me a link to it? I can't find it in the Web UI

**Comment by Osmyakov** [comment]
https://exmo.me/trade/USDT_RUB
I also checked with the exchange support, they say that all pairs should be available in the API.

**Comment by carlosmiei** [comment]
@Osmyakov when I open that link it redirects to this market
![image](https://github.com/ccxt/ccxt/assets/43336371/24fd7479-43f1-4d94-a248-4216d7141da2)

Besides that, our markets are loaded dynamically by calling an endpoint, so if that market is not available it means the API is not returning it

**Comment by Osmyakov** [comment]
Thanks, now I understand.
It looks like they have 2 types of exchanges for different markets (exmo.me and exmo.com), and in the exmo.me they do not give away this pair. I'll check it with exchange support.
