### ISSUE TITLE
BingX. fetch order triggerorder/stop order

### ISSUE THREAD

**Issue by ZetZ1** [ccxt/ccxt#19563]
### Operating System

Win11

### Programming Languages

Python

### CCXT Version

Latest

### Description

When status is open fetch order works. after change to close or canceled fetch order give a OrderNotFound error

This occurs from 1 month back aprox. May bingx change their apis?

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @ZetZ1, yeah bingx is not explicit about it but I think that from the moment the order is closed/canceled you have to use the `history` endpoint.

Can you try to do this:

```Python
order = await bingx.fetch_closed_orders(symbol, params = {'orderId': YOUR_oRDER_ID})
```

**Comment by germangar** [comment]
I'm struggling with this too. Their documentation says to use clientOrderID, and that works at making the order, but doesn't work at fetching it. And when fetching all open orders the clientOrderId isn't there even at the info block from the exchange anymore. But on the response of the order placement it was.

**Comment by ZetZ1** [comment]
hi, this is very straign... now i can use again the fetch_order again wiouth extra params for stop orders... all working again as months back....., 

i dont understand why sometimes work with no params, and other times during days or weeks OrderNotFound error when fetch each activation/stop order

**Comment by ZetZ1** [comment]
dosnt work again.,..

lolll

**Comment by ZetZ1** [comment]
dosnt work again.,..

may some problem with timestamp?

lolll

**Comment by ZetZ1** [comment]
i deleted my last message, im confused

dosnt work

fetch order in stop orders only works during status "open" when change to closed or cancelled cant fetch

**Comment by ZetZ1** [comment]
this now works wiouth any change... 

Maybe issue of bingx api... a shit api, many errors

**Comment by ZetZ1** [comment]
UPDATE:

ordernotfound error only after a triggerorder filled.

For limit orders all is ok, for canceled triggerorders also detect, problem is only when a triggerorder is close / filled

using fetch closed orders dosnt work

**Comment by ZetZ1** [comment]
Someone use Bingx? same problem? I think than is a issue or incompatibility from last api update from BingX...
