### ISSUE TITLE
How to Handle Exceptions, Please Help !!!

### ISSUE THREAD

**Issue by rhrahul** [ccxt/ccxt#1956]
Hi,

Can you please help with handling Exception in some methods,
Like See if order has been placed or not.

One more example, 
If I try to make request to load markets , sometimes request timeout, so how can I handle with code that request is timed out.

Please Help !!

Programming Language : Nodejs

Thanks & Regards,
Rahul

**Comment by kroitor** [comment]
Hi! Take a look here:

- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

Let us know if it doesn't help. Thx!

**Comment by rhrahul** [comment]
Yes, I've seen that. But didn't see how to implement in code.
Like can you help me with simple code snippets, that would be great.
Thanks

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/blob/master/examples/js/create-order-handle-errors.js

```JavaScript
"use strict";

// ----------------------------------------------------------------------------

const ccxt = require ('../../ccxt.js')

// ----------------------------------------------------------------------------

;(async () => {

    const exchange = new ccxt.bittrex ({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET_KEY',
        'verbose': false, // set to true to see more debugging output
        'timeout': 60000,
        'enableRateLimit': true, // add this
    })

    // try to load markets first, retry on request timeouts until it succeeds:

    while (true) {

        try {

            await exchange.loadMarkets ();
            break;

        } catch (e) {

            if (e instanceof ccxt.RequestTimeout)
                console.log (Date.now (), e.constructor.name, e.message)
        }
    }

    const symbol = 'ETH/BTC'
    const orderType = 'limit'
    const side = 'sell'
    const amount = 0.321;
    const price = 0.123;

    // try just one attempt to create an order

    try {

        const response = await exchange.createOrder (symbol, orderType, side, amount, price);
        console.log (response);
        console.log ('Succeeded');

    } catch (e) {

        console.log (Date.now(), e.constructor.name, e.message)
        console.log ('Failed');

    }

}) ()

```

**Comment by rhrahul** [comment]
Thank you so much :)

**Comment by mkcity** [comment]
Can you please provide examples for the way we are supposed to handle exceptions during ordering, for example, on timeout for creating an order, we have to: 
- update the .orders cache with a call to fetchOrders, fetchOpenOrders, fetchClosedOrders to check if the request to place the order has succeeded and the order is now open
- if the order is not 'open' the user should fetchBalance to check if the balance has changed since the order was created on the first run and then was filled and closed by the time of the second check

Thank you

**Comment by mkcity** [comment]
Also, for exceptions when canceling orders, we have to "set the order status to 'canceled' manually" if the balance hasn't changed. How do we set this (in python please)? 
Thank you so very much.

**Comment by mkcity** [comment]
This is what I came up with for handling exceptions when creating orders, will it suffice?

```
done = False
while not done:
	try:
                time.sleep(1)
		balances = exchange.fetch_balance()
                time.sleep(1)
		exchange.create_limit_buy_order("BTC/USDT", buy_amount, limit_price)
		done = True
	except (ccxt.ExchangeError, ccxt.AuthenticationError, ccxt.ExchangeNotAvailable, ccxt.RequestTimeout) as error:
		orders = exchange.fetch_orders(symbol="BTC/USDT") #refresh order cache
		open_orders = exchange.fetch_open_orders(symbol="BTC/USDT") #refresh order cache
		closed_orders = exchange.fetch_closed_orders(symbol="BTC/USDT") #refresh order cache
		my_order = [element for element in open_orders if element['amount'] == buy_amount] #not sure about this
		if len(my_order) == 0:
			new_balance = exchange.fetch_balance()
			if new_balance["BTC"]["total"] == balances["BTC"]["total"] and new_balance["USDT"]["available"] == balances["USDT"]["available"]:
				done = False #re attempt the order
```
