### ISSUE TITLE
Bitget Fetch_Order for triggerorders/stop orders OrderNotFound ERROR

### ISSUE THREAD

**Issue by ZetZ1** [ccxt/ccxt#19562]
### Operating System

Win11

### Programming Languages

Python

### CCXT Version

Latest

### Description

What params need for fetch activations/stop/triggers orders? i add stop:true param, and clientorderid param, but dosnt work

**Comment by carlosmiei** [comment]
Hello @ZetZ1, right now bitget does not provide an endpoint that allows fetching a stop order regardless of its state (closed, filled, canceled), so for that reason, `fetchOrder` does not support stop orders. You can however try to fetch it by using `fetch_open_orders/fetch_closed_orders/fetch_canceled_orders` by providing `stop` in `params` upon calling those methods.

**Comment by ZetZ1** [comment]
ok thanks, is nnot possible use another parameter with ID for obtain the exact order from list?

for example
            elif exch == 'bitget':
                params={'orderId': 'order id, 'stop': True}
                orders = self.exch.fetch_open_orders(ticker, params=params)
                if len(orders) == 1: return orders[0]
                orders = self.exch.fetch_closed_orders(ticker, params=params)
                if len(orders) == 1: return orders[0]
                orders = self.exch.fetch_canceled_orders(ticker, params=params)
                if len(orders) == 1: return orders[0]

**Comment by ZetZ1** [comment]
elif exch == 'bitget':
                params={'orderId': order_data['OID'], 'stop': True}
                orders = self.exch.fetch_open_orders(ticker, params=params)
                if len(orders) == 1: return orders[0]
                orders = self.exch.fetch_closed_orders(ticker, params=params)
                if len(orders) == 1: return orders[0]
                orders = self.exch.fetch_canceled_orders(ticker, params=params)
                if len(orders) == 1: return orders[0]

**Comment by ZetZ1** [comment]
is not possible add some parameter for receive exactly the order? for example:
            elif exch == 'bitget':
                params={'orderId': order_data['OID'], 'stop': True}
                orders = self.exch.fetch_open_orders(ticker, params=params)
                if len(orders) == 1: return orders[0]
                orders = self.exch.fetch_closed_orders(ticker, params=params)
                if len(orders) == 1: return orders[0]
                orders = self.exch.fetch_canceled_orders(ticker, params=params)
                if len(orders) == 1: return orders[0]
