### ISSUE TITLE
Bybit: Invalid Order, reduce-only rule not satisfied

### ISSUE THREAD

**Issue by Nitrix321** [ccxt/ccxt#19588]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

4.1.13

### Description

If in a long position, and try to make limit sell order.
The limit order has been placed but the following error message occurs.

InvalidOrder: bybit {"retCode":110017,"retMsg":"Reduce-only rule not satisfied","result":{},"retExtInfo":{},"time":1697464683996}

### Code

```python
symbol = 'ETH/USDT:USDT'

exitprice = 1650  # --> as example

# if I create params without 'reduce_only': True entry the same issue occurs 

params={'reduce_only': True,        
            'close_on_trigger': True,}

pos_size = 0.35

bybit.create_limit_sell_order(symbol, pos_size, exitprice, params=params)

```

**Comment by Nitrix321** [comment]
Hi @carlosmiei, thank you.  It's working now but it was another issue, it was not the wrong format. But I will use the format version you recommend in future. 

Thanks again.

**Comment by carlosmiei** [comment]
@Nitrix321 now, after the V5 migration, the snake_case version is not supported (it was previously but not anymore) so I highly recommend sticking to the camelCase one 🙂
