### ISSUE TITLE
Python fetch_markets() does not return future markets

### ISSUE THREAD

**Issue by Mechatrony** [ccxt/ccxt#19595]
### Operating System

Windows 11

### Programming Languages

Python 3.11.6

### CCXT Version

4.1.14

### Description

I wanna get all Binance Future USDT markets. I think there is 100+ future markets, but most of them are missing in fetch_markets()

### Code
```
binance = ccxt.binance(config={
    'apiKey': config['ACCESS_KEY'],
    'secret': config['SECRET_KEY'],
    'enableRateLimit': True,
    'options': {'defaultType': 'future'}
})

markets = binance.fetch_markets()
count = 0
for coin_info in markets:
    if coin_info['quote'] != 'USDT':
        continue
    if not coin_info['active']:
        continue
    if coin_info['future'] or coin_info['type'] == 'future':
        count += 1

print(f"Count: {count}") # Count: 4
```

**Comment by carlosmiei** [comment]
Hello @Mechatrony,
By `future` do you mean delivery futures or perpetual swaps? At CCXT, we call the latter `swaps`.

Can you try this?
```Python
 markets = await exchange.load_markets()
future_markets = [m for m in markets.values() if m['future']] # 27 markets
swap_markets = [m for m in markets.values() if m['swap']] # 298 swaps
```

**Comment by Mechatrony** [comment]
Hello @carlosmiei 
I meant perpetual swaps. I've been used my code with previous CCXT version(at least 6 months ago) and just updated CCXT. I didn't noted that changed. Your code works good. Thank you.
