### ISSUE TITLE
Support for "NegocieCoins"?

### ISSUE THREAD

**Issue by rtadewald** [ccxt/ccxt#1959]
Hello, guys

Hi,
I first wanted to say that I really like the ccxt library and used it in some of my projects. It's great and your work is honorable!

Just wanna know if you can add the NegocieCoins Exchange.
Here's the API:

https://www.negociecoins.com.br/documentacao-api
Thanks!

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/pull/1118
- #1029

;)

**Comment by rtadewald** [comment]
Oh, sorry for that. 
I'll use it for sure!
