### ISSUE TITLE
BingX fetch_trades() spot trades are mix of 'taker' and 'maker'

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#19607]
### Operating System

Linux Mint

### Programming Languages

Python

### CCXT Version

4.1.14

### Description

`fetch_trades` returns spot trades that have both 'taker' and 'maker' values for 'takerOrMarker' field and additionally 'side' is always `None`. This is the same problem that was already fixed earlier in #18959. The problem probably made a comeback in commit https://github.com/ccxt/ccxt/commit/81982ab8d0d3e86c8a0bad080d58325bc3410701

### Code

```
exchange = ccxt.bingx()
print(exchange.fetch_trades('BTC/USDT'))  
```
```
[{'id': '66027379', 'info': {'id': '66027379', 'price': '28513.17', 'qty': '0.00448', 'time': '1697577503693', 'buyerMaker': True}, 'timestamp': 1697577503693, 'datetime': '2023-10-17T21:18:23.693Z', 'symbol': 'BTC/USDT', 'order': None, 'type': None, 'side': None, 'takerOrMaker': 'maker', 'price': 28513.17, 'amount': 0.00448, 'cost': 127.7390016, 'fee': {'cost': None, 'currency': None, 'rate': None}, 'fees': [{'cost': None, 'currency': None, 'rate': None}]},
...
```

**Comment by carlosmiei** [comment]
Hello @JovianMoon, thanks for letting us know, will be fixed soon.
