### ISSUE TITLE
OKX margin mode / set leverage problem

### ISSUE THREAD

**Issue by ZetZ1** [ccxt/ccxt#19618]
### Operating System

Win11

### Programming Languages

Python

### CCXT Version

Latest

### Description

Impossible to set leverage and isolated mode in hedge mode

i triend all methods like only set margin_mode with all parameters and disable set, leverage, and disable set margin :_mode and add isolated to parameters in  set leverage, but all results in cross margin mode, impossible to set in isolated

### Code

try:
    self.exch.set_position_mode(True)
except: pass
self.exch.set_margin_mode('isolated', ticker, params={'posSide': direction, 'lever': leverage})
params = {'mgnMode': 'isolated', 'posSide': direction}
self.exch.set_leverage(leverage, ticker, params = params)

**Comment by germangar** [comment]
I use oneway mode, so it's probably not the same, but for set_leverage I use these parms:
```
elif( cls.exchange.id == 'okx' ):
                params['marginMode'] = cls.markets[ symbol ]['local']['marginMode']
                params['posSide'] = 'net'
```
I don't remember where I found I had to use 'net' in posSide. It definitely wasn't in okx's documentation. I think that one is specific to oneway mode, anyway. My point is that you could try with 'marginMode' instead of 'mgnMode'.

In any case, don't worry that much about the margin mode, because when you make the order you had to add marginMode as param of the order, and it will override the one set by the method.
These are the params I add to the order: 
```
    if( cls.exchange.id == 'okx' ):
                params['marginMode'] = MARGIN_MODE
                params['leverage'] = order.leverage
```

**Comment by ZetZ1** [comment]
hi, thx for reply

I tried all, with your method  not change leverage and not change to isolated if is set in cross, i try send parameter in set margin_mode and also send these params in create order, no works

with my code change the leverage but not change margin mode. all orders placed as cross margin

 im boring  lol

**Comment by carlosmiei** [comment]
Hello @ZetZ1,

Can you elaborate a bit more? How are you calling `set_margin_mode`?
I just set it to isolated with no issues, example:

```
Python v3.11.5
CCXT v4.1.18
okx.set_margin_mode("isolated","LTC/USDT:USDT",{'lever': 5, 'posSide': 'long'})
{'code': '0',
 'data': [{'instId': 'LTC-USDT-SWAP',
           'lever': '5',
           'mgnMode': 'isolated',
           'posSide': 'long'}],
 'msg': ''}
```

**Comment by carlosmiei** [comment]
@ZetZ1 can you share a verbose log of the set_margin_mode call only? let's avoid posting unrelated code pls.

**Comment by ZetZ1** [comment]
i included params={'mgnMode': 'isolated', 'posSide': direction, 'lev': leverage} in set leverage

**Comment by ZetZ1** [comment]
now works!!!!!!!!!!!!!!!!!

i think than in hedge mode need pass the tdMode instead mgnMode... this night i try several times more,  and if i capacity prepare a request in ccxt for solve this

**Comment by carlosmiei** [comment]
@ZetZ1 I just tested and `marginMode` seems to work:

```
✗ n okx createOrder "LTC/USDT:USDT" limit buy 2 50 '{"stopPrice": 55, "marginMode":"isolated", "posSide":"long"}' --sandbox --verbose
Node.js: v18.18.0
CCXT v4.1.18
okx.createOrder (LTC/USDT:USDT, limit, buy, 2, 50, [object Object])
fetch Request:
 okx POST https://www.okx.com/api/v5/trade/order-algo 
RequestBody:
 {"instId":"LTC-USDT-SWAP","side":"buy","ordType":"trigger","sz":"2","tdMode":"isolated","triggerPx":"55","orderPx":"50","clOrdId":"e847386590ce4dBC0e574d7cb423a661","tag":"e847386590ce4dBC","posSide":"long"} 

ResponseBody:
 {"code":"0","data":[{"algoClOrdId":"e847386590ce4dBC0e574d7cb423a661","algoId":"635260475386888192","clOrdId":"e847386590ce4dBC0e574d7cb423a661","sCode":"0","sMsg":"","tag":"e847386590ce4dBC"}],"msg":""} 

2023-10-19T15:38:19.913Z iteration 0 passed in 365 ms

{
  info: {
    algoClOrdId: 'e847386590ce4dBC0e574d7cb423a661',
    algoId: '635260475386888192',
    clOrdId: 'e847386590ce4dBC0e574d7cb423a661',
    sCode: '0',
    sMsg: '',
    tag: 'e847386590ce4dBC'
  },
  id: '635260475386888192',
  clientOrderId: 'e847386590ce4dBC0e574d7cb423a661',
  timestamp: undefined,
  datetime: undefined,
  lastTradeTimestamp: undefined,
  lastUpdateTimestamp: undefined,
  symbol: 'LTC/USDT:USDT',
  type: 'limit',
  timeInForce: undefined,
  postOnly: undefined,
  side: 'buy',
  price: undefined,
  stopLossPrice: undefined,
  takeProfitPrice: undefined,
  stopPrice: undefined,
  triggerPrice: undefined,
  average: undefined,
  cost: undefined,
  amount: undefined,
  filled: undefined,
  remaining: undefined,
  status: undefined,
  fee: undefined,
  trades: [],
  reduceOnly: false,
  fees: []
}
2023-10-19T15:38:19.913Z iteration 1 passed in 365 ms
```

**Comment by germangar** [comment]
I set it (in oneway) using 'marginMode', but there is that one thing that I had to set 'posSide' to 'net' and it's not referenced in the okx documentation. I think I found it out in a very old ccxt:issue that google returned.

At the end of the ccxt method code there are a bunch of checks for posSide that I'm not sure they handle all the possible combinations.

**Comment by germangar** [comment]
Yeah, but, if the rule is so simple... wouldn't it be better that ccxt did it on its own? My problem was that okx didn't include that bit of info in their documentation.

**Comment by ZetZ1** [comment]
But need first set leverage with all parans abd next create order setting again nargin mode? Right?

**Comment by carlosmiei** [comment]
@germangar The thing is, we don't have a way of knowing for sure the current position mode of the user.

**Comment by ZetZ1** [comment]
i use set position mode hedged True in a try except:for force the mode

**Comment by ZetZ1** [comment]
finally, after tried many combinations this issue is solved passing params={'posSide': direction, 'marginMode': 'isolated'} in set leverage method (this change leverage but not margin mode)

and pass params = {'marginMode': 'isolated', 'posSide': direction} again in create_order method


thanks!!!

**Comment by ZetZ1** [comment]
all ok now but set_position_mode dosnt work , not appears error, but not change

**Comment by litonchen** [comment]
@carlosmiei 
I have similar issue. I cannot set the **leverage** in okx
I have set isolated mode when create orders as below

```
okx = ccxt.okx( my API key)
okx.setLeverage(10,"VELO-USDT-SWAP")
params = {'marginMode': 'isolated','leverage': 10}
response  = okx.createLimitBuyOrder("VELO-USDT-SWAP",1000, last * 0.998,params=params)
```
The order of the response is isolated mode. However,the **leverage** is not my setting. 
How to change the leverage?

**Comment by carlosmiei** [comment]
@litonchen You have to provide `marginMode` upon setting the leverage as well, example:

```
response = await okx.set_leverage(5, "BTC/USDT:USDT", {"marginMode":"isolated"})
```

**Comment by litonchen** [comment]
@carlosmiei  thanks.
I used  createLimitSellOrder & createLimitBuyOrder and  failed .
Now I use okx.create_order(symbol,'limit','buy',pos,4.0001,{'hedged':False,}). It can work with set_leverage now
