### ISSUE TITLE
bybit wrong trading fees with negative fees

### ISSUE THREAD

**Issue by msei99** [ccxt/ccxt#19629]
### Programming Languages

Python

### CCXT Version

4.1.13

### Description

negative trading fees get wrong entries in fee

### Code

      {
        "id": "98d39eab-547e-41fe-bc59-0a4e09e9c4fe",
        "info": {
            "symbol": "VETUSDT",
            "orderId": "1692316800-VETUSDT-76024047-Buy",
            "orderLinkId": "",
            "side": "Buy",
            "orderPrice": "0.00000",
            "orderQty": "0",
            "leavesQty": "0",
            "orderType": "UNKNOWN",
            "stopOrderType": "UNKNOWN",
            **"execFee": "-0.00005586"**,
            "execId": "98d39eab-547e-41fe-bc59-0a4e09e9c4fe",
            "execPrice": "0.01565",
            "execQty": "932",
            "execType": "Funding",
            "execValue": "14.5858",
            "execTime": "1692316800000",
            "isMaker": false,
            "feeRate": "-0.00000383",
            "tradeIv": "",
            "markIv": "",
            "markPrice": "0.01565",
            "indexPrice": "",
            "underlyingPrice": "",
            "blockTradeId": "",
            "closedSize": "0",
            "seq": "36754582922"
        },
        "timestamp": 1692316800000,
        "datetime": "2023-08-18T00:00:00.000Z",
        "symbol": "VET/USDT:USDT",
        "order": "1692316800-VETUSDT-76024047-Buy",
        "type": null,
        "side": "buy",
        "takerOrMaker": "taker",
        "price": 0.01565,
        "amount": 932.0,
        "cost": 14.5858,
        "fee": {
            "**cost": 5.586e-05**,
            "currency": "USDT"
        },
        "fees": [
            {
                "**cost": 5.586e-05**,
                "currency": "USDT"
            }
        ]
    },

The "-" get lost in the fee and fees
correct the fees should be "-5.586e-05"
I don't know why bybit has negative fees, but sometimes they are negative

**Comment by carlosmiei** [comment]
Hello @msei99,
Thanks for letting us know. Maybe they're negative when you receive a cashback in a form of a funding fee or something like that, we will fix it asap.
