### ISSUE TITLE
Phemex hedge mode place a stop order

### ISSUE THREAD

**Issue by ZetZ1** [ccxt/ccxt#19634]
### Operating System

Win11

### Programming Languages

Python

### CCXT Version

Latest

### Description

I need know as place stop/activation orders in Phemex Hedged mode USDT futures. I tried create_stop_order method but dosn work, orders execute directly
also i try to send the necesary params from phemex api stopPxRp, triggerType, ordType -> https://phemex-docs.github.io/#place-order-http-put-prefered-2 
same results, orden execute directly

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @ZetZ1,can you please share with us the exact call made with ccxt and a verbose log? Without it it's hard to debug what went wrong.

**Comment by ZetZ1** [comment]
fetch Request: phemex POST https://api.phemex.com/g-orders RequestHeaders: {'x-phemex-access-token': '-7bfa-4bf2-c4803fa7e804', 'x-phemex-request-expiry': '1697972099', 'Content-Type': 'application/json', 'x-phemex-request-signature': '', 'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: {"symbol":"BTCUSDT","side":"Buy","ordType":"Market","clOrdID":"ccxt2022b416ce3268d21672","posSide":"Long","orderQtyRq":0.005008347245409015,"triggerPrice":29950.0}

fetch Response: phemex POST https://api.phemex.com/g-orders 200 ResponseHeaders: {'Content-Type': 'application/json', 'Content-Length': '741', 'Connection': 'keep-alive', 'Date': 'Sun, 22 Oct 2023 10:53:57 GMT', 'x-phemex-request-tracing': '-e662-46f6-895e-a78592851fc8', 'X-RateLimit-Remaining-CONTRACT': '497', 'X-RateLimit-Capacity-CONTRACT': '500', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'X-XSS-Protection': '1 ; mode=block', 'Referrer-Policy': 'no-referrer', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 ca04ec96459a9e56f99748edca103bbe.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'MAD56-P1', 'X-Amz-Cf-Id': 'vBUIKMsY8PJSaE6nA_te2P_K9GPlZdh1V6noYKVhzW1wvMcL6cK9bQ=='} ResponseBody: {"code":0,"msg":"","data":{"bizError":0,"orderID":"22051c5a-a78b-474a-9d17-cb509dd2646d","clOrdID":"ccxt2022b416ce3268d21672","symbol":"BTCUSDT","side":"Buy","actionTimeNs":1697972037850570781,"transactTimeNs":1697972037850570781,"orderType":"Market","priceRp":"30720.2","orderQtyRq":"0.005","displayQtyRq":"0.0050083","timeInForce":"ImmediateOrCancel","reduceOnly":false,"closedPnlRv":"0","closedSizeRq":"0","cumQtyRq":"0","cumValueRv":"0","leavesQtyRq":"0.005","leavesValueRv":"153.601","stopDirection":"UNSPECIFIED","stopPxRp":"0","trigger":"UNSPECIFIED","pegOffsetValueRp":"0","pegOffsetProportionRr":"0","execStatus":"PendingNew","pegPriceType":"UNSPECIFIED","ordStatus":"Created","execInst":"None","takeProfitRp":"0","stopLossRp":"0"}}

**Comment by ZetZ1** [comment]
i try to send stopDirection":"UNSPECIFIED","stopPxRp":"0" and triggertype params

**Comment by ZetZ1** [comment]
SOOOOLVEDDDD

need send all these params
params['stopDirection'], params['stopPxRp'], params['triggerType'], params['ordType'] = 'Falling', signal_entry['Price'], 'ByMarkPrice', 'Stop'
