### ISSUE TITLE
Coinbasepro implementation of watchBalance 

### ISSUE THREAD

**Issue by fl0wo** [ccxt/ccxt#19645]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

Hi, I was wondering if there is a way to date to stay on top of changes in the balance of a Coinbasepro account.

I guess it is obtainable via `watchBalance` from ccxt.pro but the feature does not exist yet. 

Is there an alternative to opening a WebSocket connection and listening on the balance endpoint?

### Describe the solution you'd like

The watchBalance method on coinbasepro of ccxt.pro to work on the websocket channel of Coinbasepro with balance updates.

But seems that Coinbasepro doesn't have a websocket channel for balances updates yet.

### Describe alternatives you've considered

Any alternative where I could obtain the same watchBalance behavior using other methods?

**Comment by sc0Vu** [comment]
Hi @fl0wo 

I didn't see watch balance channel from their documentation (https://docs.cloud.coinbase.com/), we add this method if exchanges provide the subscription.

IMHO, an alternative way to this might be polling for `fetchBalance` (might need to notice for the ratelimit).

**Comment by fl0wo** [comment]
100% agreed, thank you
