### ISSUE TITLE
Oppening Position in Mexc, Future Position.

### ISSUE THREAD

**Issue by Anrijs77** [ccxt/ccxt#19659]
### Operating System

Python 3

### Programming Languages

Python

### CCXT Version

 ccxt-4.1.24

### Description

I am struggling to open a mexc ccxt position. I am using a code that worked with bybit but due to circumstantial occurrences, i have changed ship to mexc. It has proved to be quite irritating in setting up via basic coder means. Once i change the symbol to MX/USDT it works for spot but future is not working.

### Code

```
  

```
import ccxt

def place_order(entry, stop, profit, quantity, leverage, symbol, type, side):
    exchange = ccxt.mexc3({
    'apiKey': 'mx0vgdfsdfsdifsidfsjdjfjsdjfsdfdfsdfsdfuvusTCyCGnei',
    'secret': '29200442d501a84044329hbfa500923339c9985778',
}) # Replace 'mexc' with the appropriate exchange name
    try:
        order = exchange.create_order(
            symbol=symbol,
            type=type,
            side=side,
            amount=quantity,
            price=entry,
            params={
                'takeProfit': profit,
                'stopLoss': stop,
            }
        )
        # turn this into a final code where I am able to place a trade through the exchange
    except ccxt.BaseError as e:
        print(f"An error occurred: {e}")

place_order(entry=2.7848, stop=2.78, profit=2.79, quantity=2, leverage=1, symbol="MX/USDT:USDT", type="limit", side="buy")

**Comment by Anrijs77** [comment]
An error occurred: mexc3 {"success":false,"code":1002,"message":"Contract not allow place order!"}

**Comment by Anrijs77** [comment]
In addition, i would like to know and probably have a function that cancels opened positioned. Closes the Positions.

**Comment by carlosmiei** [comment]
Hello @Anrijs77 unfortunately mexc disabled futures trading through the API a few months ago, so there's nothing ccxt can do to overcome this issue.

**Comment by carlosmiei** [comment]
@Anrijs77 Sorry, what do you mean by "implementing bingx"? Bingx is already available in CCXT

**Comment by Anrijs77** [comment]
@carlosmiei same manner?
asking ebcause i am not aware if ccxt deals with bingx

**Comment by carlosmiei** [comment]
@Anrijs77 Yes Bingx is available you can trade spot and swap with it.

**Comment by carlosmiei** [comment]
> An error occurred: bingx {"code":80014,"msg":"Mismatch type apiproto.TriggerClose with value number "at index 0: mismatched type with value\n\n\t0.54\n\t^...\n"","data":{}} turned it to xrp and bingx but am getting this

@Anrijs77 can you show us the ccxt call made + a verbose request?

**Comment by carlosmiei** [comment]
@Anrijs77 Yeah that behavior is not full unified yet at bingx, but you can do this:

```Python
    order = await exchange.create_order('LTC/USDT:USDT', 'market', 'buy', 0.1, 50, {
        'takeProfit': "{\"type\": \"TAKE_PROFIT_MARKET\", \"quantity\": 0.1,\"stopPrice\": 100.0,\"price\": 100.0,\"workingType\":\"MARK_PRICE\"}",
        'stopLoss': "{\"type\": \"STOP_MARKET\", \"quantity\": 0.1,\"stopPrice\": 30.0,\"price\": 30.0,\"workingType\":\"MARK_PRICE\"}",
    })
```

**Comment by Anrijs77** [comment]
Is it possible for you to make it work with my code where i can just call it with simple stop and take profit terms

**Comment by carlosmiei** [comment]
@Anrijs77 Right now we have to follow the APi spec precisely because the behavior is not unified in CCXT terms, but it should be very easy to adapt the example I gave:

```Python
    stop_loss_price = YOUR_SL_PRICE
    take_profit_price = YOUR_TP_PRICE
    stop_loss_amount = YOUR_STOP_LOSS_AMOUNT # if you want to close the position entirely, set this to the amount of the position
    take_profit_amount = YOUR_TAKE_PROFIT_AMOUNT # if you want to close the position entirely, set this to the amount of the position
   
    order = await exchange.create_order('LTC/USDT:USDT', 'market', 'buy', 0.1, 50, {
        'takeProfit': f'{{\"type\": \"TAKE_PROFIT_MARKET\", \"quantity\": {stop_loss_amount},\"stopPrice\": {stop_loss_price},\"price\": {stop_loss_price},\"workingType\":\"MARK_PRICE\"\}}',
        'stopLoss': f'{{\"type\": \"STOP_MARKET\", \"quantity\": {take_profit_amount},\"stopPrice\": {take_profit_price},\"price\": {take_profit_price},\"workingType\":\"MARK_PRICE\"}}',
    })
```

**Comment by Anrijs77** [comment]
Hello what do the 0.1 or 50 mean

**Comment by Anrijs77** [comment]
suppose quantity then elverage

**Comment by Anrijs77** [comment]
ok cool thanks

**Comment by carlosmiei** [comment]
@Anrijs77, not here 0.1 is the amount and 50 the price (but yeah that can be ignored in a market order).

**Comment by Anrijs77** [comment]
doesnt seem to be working: 
import ccxt

async def place_order(entry, stop, profit, quantity, leverage, symbol, type, side):
    exchange = ccxt.bingx({
        'apiKey': '',
        'secret': '',
    })
    try:
      stop_loss_price = stop
      take_profit_price = profit
      stop_loss_amount = quantity # if you want to close the position entirely, set this to the amount of the position
      take_profit_amount = quantity # if you want to close the position entirely, set this to the amount of the position
    
      order = await exchange.create_order(symbol, type, side, quantity, entry, {
        'takeProfit': f'{{\"type\": \"TAKE_PROFIT_MARKET\", \"quantity\": {stop_loss_amount},\"stopPrice\": {stop_loss_price},\"price\": {stop_loss_price},\"workingType\":\"MARK_PRICE\"\}}',
        'stopLoss': f'{{\"type\": \"STOP_MARKET\", \"quantity\": {take_profit_amount},\"stopPrice\": {take_profit_price},\"price\": {take_profit_price},\"workingType\":\"MARK_PRICE\"}}',
    })
      print(order)
      return order
    except ccxt.BaseError as e:
        print(f"An error occurred: {e}")
        return None


place_order(entry = 0, stop = 0.65, profit = 0.71, quantity = 4, leverage = 1, symbol = "MINA/USDT:USDT", type = "market", side = "buy")
<coroutine object place_order at 0x7eb0354c4040> is what i get
