### ISSUE TITLE
krakenfutures: cancel_orders(): TypeError

### ISSUE THREAD

**Issue by Hadevmin** [ccxt/ccxt#19658]
### Programming Languages

Python

### CCXT Version

4.1.24

### Description

Hello @carlosmiei ,

For the function krakenfutures.cancel_orders([id1, id2, ...]) with a similar pattern for id = '375e7d55-e39b-43fe-a8ca-b40758832b9a'

I get this error: `TypeError '<' not supported between instances of 'str' and 'int'`

The complete log:
```
+-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "ccxt\async_support\krakenfutures.py", line 984, in cancel_orders
    |     return self.parse_orders(batchStatus)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "ccxt\async_support\base\exchange.py", line 1297, in parse_orders
    |     results = self.sort_by(results, 'timestamp')
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "ccxt\base\exchange.py", line 992, in sort_by
    |     return sorted(array, key=lambda k: k[key] if k[key] is not None else "", reverse=descending)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | TypeError: '<' not supported between instances of 'str' and 'int'
```

I assume that the error occurs when there is an error in the API return. 
To reproduce the error on your side, create 2 orders, delete one of them and then call cancel_orders([id1, id2]). 
You should get the same error as I did.

Thanks you

**Comment by carlosmiei** [comment]
Hello @Hadevmin,
Curiously I think I fixed the exact same issue a few hours ago: https://github.com/ccxt/ccxt/issues/19658 so it should be working on the next release, but I will double check it.

Thanks for reporting it!

**Comment by Hadevmin** [comment]
You solve problems before I can even point them out. It's amazing! 👍 
Thank you very much!
Have a nice day

**Comment by carlosmiei** [comment]
@Hadevmin Sheer luck this time 😅.
Nonetheless, we will release it in a few hours so you should be able to get the fix soon.
