### ISSUE TITLE
Just cex no dex

### ISSUE THREAD

**Issue by bitcoinmeetups** [ccxt/ccxt#19669]
### Operating System

linux

### Programming Languages

Python

### CCXT Version

latest

### Description

Hi,

I'm Mr. WindSurfer, a very friendly guy.

I think I talked to you a few years ago about this and the issue still remains.

Why do you only add CEXes? I h*** cexes, I don't trade on them. Why not add dexes? I specifically only trade on dexes if I can. And to some extent they might be the future. I don't understand why you always only add cexes. 

Please add a couple to begin with at least Uniswap (Polygon), Curve (Polygon) and so on.

### Code

```
  

```

**Comment by kroitor** [comment]
@bitcoinmeetups 

> Please add a couple to begin with at least Uniswap (Polygon), Curve (Polygon) and so on.

We're working on exactly that right now, hold tight! )
Don't miss the news, subscribe to our telegram group: https://t.me/ccxt_chat and discord: https://discord.gg/ccxt

**Comment by bitcoinmeetups** [comment]
It could have a big impact. Please do it Igor : ) Then we just connect ChatGPT to it and everybody in the world can stop working, ha ha : D

**Comment by bitcoinmeetups** [comment]
Ethereum is way too permissioned. It's not really permissionless, the dev tools are super gnarly to work with for normal people. It's permissioned by opaqueness. Frankly I think forge, hardhat, Ethereum core and so on are colluding to keep the mob away from being able to deploy. So high-level CLI's are needed. Ok, yours is not a deployment tool but it could be really useful if it could access dexes. And why stop there? There are heaps of smart contracts that no-one except hard-core coders can understand or interact with. You see what I mean. Interaction must be simplified. Let us Unix fans in too, I don't like JavaScript but if you provide a CLI where I can work with understandable simple Python or better yet Unix one-liners then I'll use it daily most likely.

**Comment by kroitor** [comment]
@bitcoinmeetups we actually have a cli for js, python and php, just don't have that many dexes yet (working on that):
- https://github.com/ccxt/ccxt/blob/master/examples/
- https://github.com/ccxt/ccxt/blob/master/examples/js/cli.js
- https://github.com/ccxt/ccxt/blob/master/examples/py/cli.py
- https://github.com/ccxt/ccxt/blob/master/examples/php/cli.php

**Comment by bitcoinmeetups** [comment]
I need the dexes, not touching cexes if it can be avoided. And they might be kind of doomed, they will just get regulated into boredom. Happy to test the new tools if you add dexes. I joined the chats, you can also post here if you want more feedback or if you have added a dex. There's none at the moment, right?

**Comment by bitcoinmeetups** [comment]
I have tested ccxt in the past and I can kind of work with the tools after I read the documentation a couple of times. But with only cexes I won't use the tools after testing. However with dexes that's another story. At the moment I have to login over and over again with MetaMask and Keplr, and switch accounts manually and worst of all - use GUI's to trade only. It's not a nice experience. You could change that. A brave new hope for humanity : )

**Comment by bitcoinmeetups** [comment]
Oh, one more thing. Trading is one thing but if you could add capability to create pools on dexes that would be really hot. I believe in pooling, there's gonna be a lot of pooling in the future of various types. The ultimate new financial methods have not been found yet but I bet pooling will be a part of it.
