### ISSUE TITLE
Bybit WatchTicker missing updates / incorrect data 

### ISSUE THREAD

**Issue by kingkong404** [ccxt/ccxt#19660]
### Operating System

OSX / Linux

### Programming Languages

Typescript

### CCXT Version

4.1.24

### Description

it seems the bybit watchTicker is not functioning correctly. It seems to produce several updates "onMessage" that dont provide an update via console.log, so its missing price updates, sometimes 6/7 messages go by with no update to my console log . And data does not match the data in the verbose output (ticker.last example in screenshot). 

![image](https://github.com/ccxt/ccxt/assets/4363358/6bd64ae1-5790-40f2-a305-e8864575d463)

Here is an example of skipping an update in the first message last price was 33701.50 and then second message was '33701.60 and I only got a console log after the second message. This also seems to be happening on other values (bid, ask etc)
![image](https://github.com/ccxt/ccxt/assets/4363358/b1e2d5a3-816e-47b6-bf41-cedff075a6f4)

Several updates to last price with no console.log
![image](https://github.com/ccxt/ccxt/assets/4363358/c0d294ef-1d18-4978-9760-a15a17e77840)

### Code

```ts
    while (true) {
      const symbol = 'BTC/USDT:USDT'
      bybit.verbose = true
      const ticker = await bybit.watchTicker(symbol)

      console.log(`Price Update ${symbol}: Last: ${ticker.last}, Ask: ${ticker.ask}, Bid: ${ticker.bid}`)
    }
  

```

**Comment by frosty00** [comment]
@kingkong404 the issue is fixed in the latest version of ccxt. Thanks for reporting it!

**Comment by kingkong404** [comment]
> @kingkong404 the issue is fixed in the latest version of ccxt. Thanks for reporting it!

Thank you!
