### ISSUE TITLE
krakenfutures: fetch_balance()

### ISSUE THREAD

**Issue by Hadevmin** [ccxt/ccxt#19677]
### CCXT Version

4.1.26

### Description

Hello @carlosmiei , it's me again! 

For function krakenfutures.fetch_balance(), it links cash wallet `{'accounts': {'cash': {'balances': asset1, asset2 ...}`
But for kraken futures object, we have to bind flex wallet? `{'accounts': {'flex': {'balances': asset1, asset2 ...}`

And another "problem", look the response of fetch_balance() for the unrealized P&L.
In the function fetch_positions(), 'unrealizedPnl' (ccxt schema) is bind to 'unrealizedFunding' (api response). But this isnot really correct.
I had a quick look at the kraken documentation because my eyes sting. But I couldn't find an endpoint to get the real unrealized P&L. I'll look harder tomorrow if you need more information.

**Comment by Hadevmin** [comment]
@carlosmiei For fetch_balance(), 
I was wondering if it would be more persistent to return the default flex portfolio when using the kraken futures object? 
I have assets in my cash wallet, but I can't find them in the kraken pro GUI (used for futures). I think they must have changed the way they manage portfolios because I remember a different separation of portfolios on the old GUI.
But in any case, to trade perpetual futures, you have to transfer the assets to the "flex" portfolio, hence my question about making it the default portfolio.

For unrealized P&L, it's a shame not to have it when asking for positions, but here it's on the kraken's side. All the more so as lightening the latter point is not the most relevant, as it shouldn't be called for as much as the others. But there's nothing we can do about it.

I've just remembered (a few hours' sleep helps to recover the memory), in the object I created to use the kraken futures API, I did use the log section to obtain the P&L, but it's a gas factory. You're going to go to a lot of trouble for nothing. Kraken should make this data available, especially as it shouldn't be complicated on their side since they make it available on the web interface.
I'm going to contact them and suggest that they improve their API by providing this data. We'll see.

**Comment by Hadevmin** [comment]
@carlosmiei 
I'm taking advantage of the fact that this topic is open (I don't think it's necessary to recreate a issue?)
In bybit object, for fetch_balance() you can bind 'timestamp' (ccxt schema) to {'info': {'time' : timestamp}} (API return).

**Comment by carlosmiei** [comment]
@Hadevmin 
> I was wondering if it would be more persistent to return the default flex wallet when using the kraken futures object?

Yeah, after checking it one more time, I agree with out, the "tradeable" wallet is the Multi-collateral/flex, I turn that the default.

![image](https://github.com/ccxt/ccxt/assets/43336371/3ce62092-264d-4e60-9f5c-a91761561570)

> In bybit object, for fetch_balance() you can bind 'timestamp' (ccxt schema) to {'info': {'time' : timestamp}} (API return).
Will check this one as well, thanks once again.
