### ISSUE TITLE
Undefined timestamp while executing watchOrderBook

### ISSUE THREAD

**Issue by babbarc** [ccxt/ccxt#19674]
### Operating System

Archlinux

### Programming Languages

Javascript

### CCXT Version

4.1.26

### Description

The object returned after the first execution of watchOrderBook always results in an undefined timestamp. The subsequent executions either give correct output or give a stale output depending on the continuity of seqNum & prevSeqNum in the output of onMessage with exchange.verbose = true. I have attached two files, break_sequence.log and continue_sequence.log. 

1. break_sequence file has prevSeqNum different from its actual previous SeqNum on the second output of onMessage with order-book data
2. continue_sequence file has prevSeqNum same as the actual previous SeqNum on the second output of onMessage with order-book data

It is very random when the code results in a break_sequence or continue_sequence. I believe the return object of watchOrderBook depends on the continuity of prevSeqNum (or nonce of the previous request). This would explain the undefined timestamp on every first execution, and the subsequent outputs depend on prevSeqNum's continuity.
[break_sequence.log](https://github.com/ccxt/ccxt/files/13170867/break_sequence.log)
[continue_sequence.log](https://github.com/ccxt/ccxt/files/13170907/continue_sequence.log)

I appreciate any help in understanding this issue.

### Code

```
  

```

**Comment by pcriadoperez** [comment]
Hi @babbarc , thanks for pointing this out, I opend a PR with the fix to include the timestamp in the first orderbook.

Also I am not sure I understand completly the question around sequence numbers.
The timestamp comes from the 'ts' field you see in the verbose message or the inside the 'info' attribute.
The sequence number is used to validate the integrity of the orderbook, and no orderbook is missed.
Let me know if there any more questions I can help with

**Comment by babbarc** [comment]
Hi @pcriadoperez, thanks for looking into the issue.

The issue with break_sequence and continue_sequence is the following:

1. In break_sequence.log, lines 275, 297, 309 and 321 are the output constructed from the return value of watchOrderBook on every tick. The nonce is not changing. The nonce value remains the same as that was received in the response to the initial request (line 242: `seqNum: 83052648`). The subsequent tick on line 287 has `prevSeqNum: 83052651,` which does not match the one from line 242, creating a break in the sequence of nonce. I suspect this break in the sequence of the nonce is the reason for the stale output of the watchOrderBook on lines 297, 309 and 321 and the following ticks.

| line | arrival timestamp | exchange timestamp | latency | nonce | symbol | bid price & amount | ask price & amount |
| ---- | ------------------- | ----------------------- | -------- | ------- | ------- | ----------------------- | --------------------- |
| 275 | 2023-10-25T21:23:29.115Z | undefined | NaN | 83052648 | TRACE/USDT | [ 0.00672, 7329.7473 ] | [ 0.00663, 1510.9575 ] |
| 297 | 2023-10-25T21:23:54.917Z | undefined | NaN | 83052648 | TRACE/USDT | [ 0.00672, 7329.7473 ] | [ 0.00663, 1510.9575 ] |
| 309 | 2023-10-25T21:23:57.242Z | undefined | NaN | 83052648 | TRACE/USDT | [ 0.00672, 7329.7473 ] | [ 0.00663, 1510.9575 ] |
| 321 | 2023-10-25T21:23:57.550Z | undefined | NaN | 83052648 | TRACE/USDT | [ 0.00672, 7329.7473 ] | [ 0.00663, 1510.9575 ] |

2. In continue_sequence.log, lines 273, 285, 296 and 307 are outputs using the same code as above—however, this time nonce updates on subsequent ticks. The first nonce is the same as that received on line 240 (`seqNum: 83053613,`), which also matches the prevSeqNum received on the subsequent tick (line 280:  `prevSeqNum: 83053613,`). In this case, there is no break in the sequence of nonce.

| line | arrival timestamp | exchange timestamp | latency | nonce | symbol | bid price & amount | ask price & amount |
| ---- | ------------------- | ----------------------- | -------- | ------- | ------- | ----------------------- | --------------------- |
| 273 | 2023-10-25T21:45:03.059Z | undefined | NaN | 83053613 | TRACE/USDT | [ 0.00673, 7329.7473 ] | [ 0.00664, 1602.9265 ] |
| 285 | 2023-10-25T21:45:03.441Z | 2023-10-25T21:45:03.321Z | 120 | 83053614 | TRACE/USDT | [ 0.00673, 7329.7473 ] | [ 0.00664, 1602.9265 ] |
| 296 | 2023-10-25T21:45:03.939Z | 2023-10-25T21:45:03.780Z | 159 | 83053617 | TRACE/USDT | [ 0.00673, 7329.7473 ] | [ 0.00664, 1602.9265 ] |
| 307 | 2023-10-25T21:45:04.246Z | 2023-10-25T21:45:04.056Z | 190 | 83053618 | TRACE/USDT | [ 0.00673, 7329.7473 ] | [ 0.00664, 1602.9265 ] |

It is pretty random when the code creates a break in the sequence of nonce, resulting in a stale output from watchOrderBook on subsequent ticks.

**Comment by pcriadoperez** [comment]
Thanks for pointing this out @babbarc , I opened a PR to check for when a missing message is received that doesn't follow the sequence, to throw an error and restart the watchOrderBook
