### ISSUE TITLE
retrieving recent filled orders

### ISSUE THREAD

**Issue by kingofclubstroy** [ccxt/ccxt#1969]
- OS: windows
- Programming Language version: python 2.7
- CCXT version:
- Exchange: any
- Method: fetch_trades ?

Hey there, I have been trying to find a way to receive the most recent filled orders in an exchange and have been coming across some issues, its seems like the responses from fetch_trades (if filled orders is indeed what its giving) are delayed and not showing the most recent filled orders that is shown on the site. I was wondering if you know a way to retrieve these values. It would be much appreciated

**Comment by kroitor** [comment]
Hi! Have you read this: https://github.com/ccxt/ccxt/wiki/Manual#querying-orders ? )

**Comment by kingofclubstroy** [comment]
Thanks, I see that you do have a fetchClosedOrders function, but it doesn't seem to solve my problem. When i run binanceCcxt.fetchClosedOrders("ETH/BTC"), I receive an empty list, is it returning my personal closed orders? What i would like is a list of orders that have been filled so I can get a sense of  whether the coin is selling/buying at the ask or bid price

**Comment by kroitor** [comment]
> When i run binanceCcxt.fetchClosedOrders("ETH/BTC"), I receive an empty list, is it returning my personal closed orders?

Can you please show a minimal but a complete snippet of your code to reproduce it, and your verbose output according to these recommendations: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

> What i would like is a list of orders that have been filled so I can get a sense of whether the coin is selling/buying at the ask or bid price

That method should return exactly what you want. However, if it doesn't, you need to debug it a little (check the above doc to see how). 

Standing by for a follow-up on this from you.

**Comment by kroitor** [comment]
> As you see it returns an empty list

Are you sure you have some closed ETH/BTC orders ?

**Comment by kingofclubstroy** [comment]
I guess I didn't make it clear what I wanted, I would like to see the recently filled orders in a given market, not by me but by others. Would like to see what price a given coin has been selling for in a time frame, to get a sense of if it will sell at a given price and have a sense of recent volume

**Comment by kroitor** [comment]
@kingofclubstroy then you are confusing your personal closed orders with public trades (fills). To fetch public trades (public closed orders), you need to replace the call to `fetchClosedOrders` with a call to `ccxt.fetchTrades ('ETH/BTC')` in your code. 

More about it and the structure of the returned data is here: https://github.com/ccxt/ccxt/wiki/Manual#trades-executions-transactions

Let us know if it does not help.

**Comment by kingofclubstroy** [comment]
Perfect! thank you kindly for you time! You are always a great help and very patient with me!
