### ISSUE TITLE
It seems that the API of lbank exchange cannot be used normally.

### ISSUE THREAD

**Issue by qwe231cvb** [ccxt/ccxt#19697]
### Operating System

Ubuntu 18.04 

### CCXT Version

Version: 4.1.4  

### Description

Has anyone ever used limit orders to trade on lbank exchange? The same code can place orders normally on other exchanges, but cannot place orders on lbank exchange. I suspect there may be a problem with the API of lbank exchange. Has anyone used the API of lbank exchange to trade with limit orders?

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @qwe231cvb 

Would you like to paste verbose log?

**Comment by Dan-krm** [comment]
This has been an issue with creating orders on Lbank and Lbank2 for a while, it seems like they're limiting access to trading through the API and these errors are always returned: `Invalid Trading Pair` or `This currency pair is not supported`

If you look at other issues and pull requests some users mention similar problems and have contacted Lbanks customer service without any success:
#12920
#18970
#18716
