### ISSUE TITLE
Recently introduced: RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by miracle2k** [ccxt/ccxt#1970]
- OS:  Linux
- Programming Language version: Python/Pypy
- CCXT version: 1.10.1156
- Exchange: NA

Since https://github.com/ccxt/ccxt/commit/9d1596d6913cd524fa5931e6c8c22ae113f3f4ac I am getting the following error:

```
Traceback (most recent call last):
  File "/usr/local/site-packages/ccxt/async/base/exchange.py", line 64, in __del__
    self.asyncio_loop.run_until_complete(self.session.close())
  File "/usr/local/lib-python/3/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "/usr/local/lib-python/3/asyncio/base_events.py", line 408, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

I understand why this piece of code was added (I saw the message it is supposed to fix myself), however, in my case the exchange instances are garbage collected, while my code main program loop is still running (I just fetch the markets once, I don't need more than that).

**Comment by kroitor** [comment]
This is fixed in 1.10.1158. Please update your version of ccxt and retry the same code. We will be happy if you report back whether it works normally for you now or not. Thank you for reporting!

**Comment by miracle2k** [comment]
Seems to work for me. Thank you so much!

**Comment by kroitor** [comment]
@miracle2k thx for letting us know ) Cheers! )
