### ISSUE TITLE
How to get token smart contract on exchanges except mexc

### ISSUE THREAD

**Issue by AlwxDavydov** [ccxt/ccxt#19706]
### Operating System

Windows 10 

### CCXT Version

last

### Description

On mexc we just can use mexc.currencies[coin]['info']['networkList'] and inside he got 'contract' with the exact token smart contract. I can’t find an analogue of this action on other exchanges (I’m interested in bybit, gate, binance, kucoin). Maybe you could help me. 

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @AlwxDavydov 

It depends on exchanges, should check their documentation. eg. binance and kucoin use `contractAddress`.

**Comment by AlwxDavydov** [comment]
@sc0Vu Thank you, I thought that it called same everywhere. Found what I was looking for everywhere except the exchange Gate, there are such a method, it called - GET /wallet/currency_chains. But I can t find function that use it in ccxt. Maybe you would be so kind as to tell me.

**Comment by sc0Vu** [comment]
@AlwxDavydov I think ccxt don't use smart contract address for now.

**Comment by rglKali** [comment]
> @AlwxDavydov I think ccxt don't use smart contract address for now.

Can we expect this option to be added in the future? Unified network structure is now a part of ccxt's certification, can we expect something like 'address' field there?

**Comment by remort** [comment]
need that functionality also
