### ISSUE TITLE
how can I get the code for create market order with TP/SL and Trailing Stop(TP) from ccxt?

### ISSUE THREAD

**Issue by PUVl** [ccxt/ccxt#19716]
### Operating System

Window 10

### Programming Languages

Python

### CCXT Version

Latest

### Description

I want to know how can I get the code for create market order with TP/SL at the same time and Trailing Stop(TP) from ccxt.

Is there any examples or manual?

![image](https://github.com/ccxt/ccxt/assets/149218908/dc9dcdf0-5473-4917-95a6-4067ce071761)

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @PUVl 

You can find example here:
 https://github.com/ccxt/ccxt/blob/master/examples/js/create-order-position-with-takeprofit-stoploss.js. To see more information of parameters, please see documentation https://github.com/ccxt/ccxt/wiki/Manual#placing-orders.

**Comment by PUVl** [comment]
> Hi @PUVl
> 
> You can find example here: https://github.com/ccxt/ccxt/blob/master/examples/js/create-order-position-with-takeprofit-stoploss.js. To see more information of parameters, please see documentation https://github.com/ccxt/ccxt/wiki/Manual#placing-orders.

Thanks, by the way, It looks like for js not py. Does it work in py?

**Comment by sc0Vu** [comment]
You can find python example here: https://github.com/ccxt/ccxt/tree/master/examples
