### ISSUE TITLE
Bitbay ccxt Api Login

### ISSUE THREAD

**Issue by Silver40k** [ccxt/ccxt#1971]
Hi, I am trying to log-in via ccxt to bitbay with the following code ...

```
import ccxt
ccxt.bitbay({'apiKey':"bitbay key", secret: "bitbay private key")}
```

Unfortunately it does not work.

Do you know how to log-in to bitbay?

Thanks!

Best
Till

**Comment by hippylover** [comment]
```import ccxt
bitbay = ccxt.bitbay({'apiKey':"bitbay key", secret: "bitbay private key")}
bitbay.createLimitBuyOrder('ETH/BTC', 0.01, 0.000005)```

This is standard options. Perhaps bitbay needs special parameters i don't know. You can try it out. I would check the ccxt manual and perhaps do some python tutorials first?

**Comment by Silver40k** [comment]
Thanks!! I thought somebody has some experience with bitbay? Has somebody already created a bitbay api code?

**Comment by Silver40k** [comment]
Thanks for helping !!! I am still learning python but the log-in into bitbay worked fine ...

**Comment by kroitor** [comment]
@Silver40k ok, thx for reporting back! Let us know if you have any other difficulties with it! Cheers!
