### ISSUE TITLE
BingX perpetual version has changed!

### ISSUE THREAD

**Issue by pybymo** [ccxt/ccxt#19739]
### Operating System

windows

### Programming Languages

Python

### CCXT Version

4.1.16

### Description

Hi, BingX perpetual v1 is deprecated, please upgrade the code!

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @pybymo, Thanks for letting us know. We're aware of this update, and CCXT never used the v1 version of swaps (BingX is a recent addition) so everything should be working as expected.
