### ISSUE TITLE
Binance does not reuse the same socket connection for watchTicker / watchOHLCV

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#19736]
### Operating System

Docker Debian

### Programming Languages

JavaScript

### CCXT Version

CCXT PRO: 4.1.1

### Description

For several calls of watchTicker / watchOHLCV on the same Binance instance,  `onConnected` callback is triggered multiple time. In previous versions, that was not noticed. Now, for each market, a separate socket connection is used?  

### Code

```
  async function run() {
    const ccxt = require('ccxt');

    const pairs = ['BTCUSDT', 'ADAUSDT'];

    const exchange = new ccxt.pro.binance;

    // !!! Triggered 2 times.
    exchange.onConnected = (client, message) => {
        global.logger.warn(`Connected to socket!`);
    };

    for (let pair of pairs) {
        await exchange.watchTicker(pair);
    }

}

run();

```

**Comment by pcriadoperez** [comment]
Hi @wunderb1t ,
This is done on purpose, binance allows for multiple streams to be able to load balance when listening to several topics. If you wish only to use one stream you can do so by setting the streams option to 1

**Comment by wunderb1t** [comment]
From[ Binance docs](https://binance-docs.github.io/apidocs/futures/en/#websocket-market-streams): 

> A single connection can listen to a maximum of 200 streams.

So, how to use only one socket connection to subscribe multiple markets (streams). Where to set this option?

**Comment by carlosmiei** [comment]
Hello @wunderb1t,
If you want to force a single connection, you can do this:

```Python
binance.options['streamLimits'] = {
   'spot': 1,
   'margin':1,
   'future':1,
   'delivery':1
}
```

**Comment by pcriadoperez** [comment]
@wunderb1t , I'll close now the issue, but please feel free to reach out with any other questions.
