### ISSUE TITLE
Incomplete order data with Bitmex

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#19743]
Hello,

After an order is placed in Bitmex the dictionary returned is incomplete. For example in the example below the `amount` `remaining` values are set to `None` whereas `orderQty` and `leavesQty` are present in the `info` sub dictionary.

```python
{'amount': None,
 'average': None,
 'clientOrderId': None,
 'cost': 335.0,
 'datetime': '2023-10-30T17:49:21.373Z',
 'fee': None,
 'fees': [],
 'filled': None,
 'id': '9781e413-7d04-49b0-8a7a-19bec59dc10b',
 'info': {'account': 'abcd',
          'avgPx': None,
          'clOrdID': '',
          'clOrdLinkID': '',
          'contingencyType': '',
          'cumQty': '0',
          'currency': 'USD',
          'displayQty': None,
          'execInst': '',
          'leavesQty': '335',
          'ordRejReason': '',
          'ordStatus': 'New',
          'ordType': 'Limit',
          'orderID': '9781e413-7d04-49b0-8a7a-19bec59dc10b',
          'orderQty': '335',
          'pegOffsetValue': None,
          'pegPriceType': '',
          'price': '23127.5',
          'settlCurrency': 'XBt',
          'side': 'Buy',
          'stopPx': None,
          'symbol': 'XBTUSD',
          'text': 'CCXT',
          'timeInForce': 'GoodTillCancel',
          'timestamp': '2023-10-30T17:49:21.373Z',
          'transactTime': '2023-10-30T17:49:21.373Z',
          'triggered': '',
          'workingIndicator': True},
 'lastTradeTimestamp': 1698688161373,
 'lastUpdateTimestamp': None,
 'postOnly': False,
 'price': 23127.5,
 'reduceOnly': None,
 'remaining': None,
 'side': 'buy',
 'status': 'open',
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': 'BTC/USD:BTC',
 'takeProfitPrice': None,
 'timeInForce': 'GTC',
 'timestamp': 1698688161373,
 'trades': [],
 'triggerPrice': None,
 'type': 'limit'}

```
Regards,
Kinzowa

**Comment by Dan-krm** [comment]
Hi @Kinzowa the order parser on Bitmex returns either the `amount` or the `cost` based on if the market is inverse or not, in this case the market is inverse `BTC/USD:BTC` so the `cost` is returned:
```
        const marketId = this.safeString (order, 'symbol');
        const symbol = this.safeSymbol (marketId, market);
        const qty = this.safeString (order, 'orderQty');
        let cost = undefined;
        let amount = undefined;
        const defaultSubType = this.safeString (this.options, 'defaultSubType', 'linear');
        let isInverse = false;
        if (market === undefined) {
            isInverse = (defaultSubType === 'inverse');
        } else {
            isInverse = this.safeValue (market, 'inverse', false);
        }
        if (isInverse) {
            cost = this.convertFromRawQuantity (symbol, qty);
        } else {
            amount = this.convertFromRawQuantity (symbol, qty);
        }
```
However I'll open a pull request that uses the `leavesQty` so that the `remaining` value is populated for inverse orders.

**Comment by Kinzowa** [comment]
Hi @Dan-krm, shouldn't the cost be expressed in the margin currency?

**Comment by Dan-krm** [comment]
For the unified structure the `amount` should be in the `base` currency and the `cost` should be in the `quote` currency
https://github.com/ccxt/ccxt/wiki/Manual#order-structure
Based on that I'm not sure if the parseOrder logic is correct, I'll ask the CCXT team why they're handling inverse orders like this in parseOrder and I might create another pull request with some changes

**Comment by Kinzowa** [comment]
> @Kinzowa For the unified structure the `amount` should be in the `base` currency and the `cost` should be in the `quote` currency https://github.com/ccxt/ccxt/wiki/Manual#order-structure Based on that I'm not sure if the parseOrder logic is correct, I'll ask the CCXT team why they're handling inverse orders like this in parseOrder and I might create another pull request with some changes

I think with inverse markets the `amount` is always in quote currency. For this reason it would be make sense to have `cost` in `base` currency, because `base` currency is also the `settle` currency.

**Comment by Dan-krm** [comment]
@Kinzowa I reviewed this with the CCXT team and we think it makes sense to have the `cost` in the base currency since you're paying using the base currency and not the quote currency for inverse markets.

I don't think we agree that the `amount` is always in the quote currency. Now that the `remaining` value is used I think this line in safeOrder in the Exchange class will populate the amount value when needed:
```
        if (amount === undefined) {
            // ensure amount = filled + remaining
            if (filled !== undefined && remaining !== undefined) {
                amount = Precise.stringAdd (filled, remaining);
            } else if (status === 'closed') {
                amount = filled;
            }
        }
```
So in this case I don't think any more changes are required at this time
