### ISSUE TITLE
Bitso nonce should be set to miliseconds

### ISSUE THREAD

**Issue by aeroreyna** [ccxt/ccxt#1974]
- OS: Windows
- Programming Language version: Node
- CCXT version: 1.10.1115
- Exchange: Bitso
- Method: Nonce

The bitso Nonce should be set by miliseconds instead of seconds to be able to get several consecutive request to the server. 

Code example: 

bitso.fetchBalance ()

Crash due when markets aren't loaded yet.

**Comment by kroitor** [comment]
Are you sure you are setting the `{`enableRateLimit`: true}` in exchange constructor params and then handling the errors properly?

**Comment by aeroreyna** [comment]
Not really, I'm new on this project, I just set up my keys and try to fetch the balance and get the nonce issue from bitso. Should I modify some setting in order to be able to work with it?

**Comment by kroitor** [comment]
@aeroreyna I'd recommend to read the entire Manual first, as all your questions are covered there: https://github.com/ccxt/ccxt/wiki/Manual You will save yourself tons of time! Really!
