### ISSUE TITLE
Binance: help with price filters, lot size and min_notional

### ISSUE THREAD

**Issue by Technorocker** [ccxt/ccxt#1975]
Hello everyone, I am using windows 7 and programming my bot with binance at the moment.
This is less of a version problem and more of a price filter aggravation at this point. Every time I think I have the price and min notation and lot figured out I start to get more price filter errors.

Is there not a simple way to toss in a quantity and price for a pair of symbols and it will tell me if the account balance is enough? This just seems to be very complicated more then it needs to be. I pretty much been using BTCUSDT as my base to code with.and for that part I think I've covered all my hurdles over the past 2 weeks Ive been playing around with building a bot.
Now that I have a decent algo working for what I want it to do I'm trying to get a few other pairs to to use it and now I'm back to min notation errors, then lot size. 

Does anyone have a snippet of code to please share with me that I can use to conquer this ongoing hassle I've been running into? Or some guidance would be most appreciated. Ive searched through the Issues for this project and any other project through google and I keep finding ways to get the limits or code to produce the limits but have yet to find something tangible to actually give me a yay or nay on whether the order can go through.

Thanks to any and all comments. This has been a pain in my ass and many others as far as I can find on the web.

**Comment by kroitor** [comment]
Hi! Can you show a minimal snippet of your code to reproduce a problem? Also, need a lot more info from, namely your programming language and version number, your ccxt version number, your code, your verbose output according to these recommendations: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Your issues have been covered here many times:

- https://github.com/ccxt/ccxt/issues/1972
- https://github.com/ccxt/ccxt/issues/1516
- https://github.com/ccxt/ccxt/issues/799
- https://github.com/ccxt/ccxt/issues/716
- https://github.com/ccxt/ccxt/issues/663

CCXT Manual:
- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

Binance docs:

- https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#filters
- https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#min_notional
- https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#price_filter
- https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#lot_size

In general, you don't need to format those values by hand, and if you're calling ccxt methods properly, your code should work normally.

Let us know if it does not help, standing by for more info from you.
