### ISSUE TITLE
binance wrong price precision

### ISSUE THREAD

**Issue by szmcdull** [ccxt/ccxt#19765]
### Operating System

windows/linux

### Programming Languages

Python

### CCXT Version

4.0.109/4.1.28

### Description

![image](https://github.com/ccxt/ccxt/assets/2098590/a486fc92-98a1-4731-9b12-d0baedf4756d)

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @szmcdull 

If there is price filter in the response, the market would use that value.

In `RUNE/USDT:USDT` market:
```JS
    {
        tickSize: '0.0010', // 3
        maxPrice: '839',
        minPrice: '0.1720',
        filterType: 'PRICE_FILTER'
      }
```
