### ISSUE TITLE
Add Blocktrail

### ISSUE THREAD

**Issue by thomsonimjd** [ccxt/ccxt#1976]
There is another api for Bitcoin and BitcoinCash. Please see below link to add.
[https://www.blocktrail.com/dev/login](url)

**Comment by kroitor** [comment]
We are going to detach the data aggregators into their own subspace inside ccxt, as blocktrail, blockchain.info and others are not exchanges in common sense, those are just data aggregators (intermediaries). The work on aggregators has been started here: #1162 

Hoe to finish it as soon as possible. Let us know if it does not answer your request. Thx!
