### ISSUE TITLE
BingX swap creat_order and setting tp sl at the same time

### ISSUE THREAD

**Issue by pybymo** [ccxt/ccxt#19773]
### Operating System

windows

### Programming Languages

Python

### CCXT Version

4.1.16

### Description

Hi, I'm trying to set take profit and  stop loss while create BingX swap order with this code below, but it just creates order without tp and sl! If I made any mistake anywhere can you please correct my code?

### Code

```
position = exchange.create_order(symbol=item, type="market", side="buy", amount=vol,
                                 params={
                                         "TAKE_PROFIT_MARKET": {"takeProfitPrice": tp, "price": tp, "workingType": "MARK_PRICE"},
                                         "STOP_MARKET": {"stopLossPrice": sl, "price": sl, "workingType": "MARK_PRICE"}
                                         }
                                 ) 
pprint(position)

```
{'amount': None,
 'average': None,
 'clientOrderId': None,
 'cost': None,
 'datetime': None,
 'fee': {'cost': None, 'currency': None, 'rate': None},
 'fees': [{'cost': None, 'currency': None, 'rate': None}],
 'filled': None,
 'id': '1719727329359429732',
 'info': {'clientOrderID': '',
          'orderId': '1719727329359429732',
          'positionSide': 'LONG',
          'side': 'BUY',
          'symbol': 'SHIB-USDT',
          'type': 'MARKET',
          'workingType': 'MARK_PRICE'},
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'postOnly': None,
 'price': None,
 'reduceOnly': None,
 'remaining': None,
 'side': 'buy',
 'status': None,
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': 'SHIB/USDT:USDT',
 'takeProfitPrice': None,
 'timeInForce': 'IOC',
 'timestamp': None,
 'trades': [],
 'triggerPrice': None,
 'type': 'market'}

**Comment by mahdimsr** [comment]
what api version you are trying?
