### ISSUE TITLE
Bitget: Watch Stop Orders 

### ISSUE THREAD

**Issue by nvrossett** [ccxt/ccxt#19776]
### Operating System

Debian

### Programming Languages

JavaScript

### CCXT Version

4.0.103

### Description

I am connecting websocket to bring order status changes
`const orders = await bitget.watchOrders()
`
What happens on Bitget is that it separates the orders having the orders channel (limt/market orders) and ordersAlgo (stop orders)

I made a second call focusing on this pattern:
`const stopOrders = await bitget.watchOrders(undefined, undefined, undefined, { stop: true, sandboxMode: true })
`
Because I noticed that the main function has this syntax:
`async watchOrders(symbol = undefined, since = undefined, limit = undefined, params = {})
`
I'm using the sandbox trying to use SXRPSUDT_SUMCBL

It's bringing normal orders but not stop orders

The parameters passed into the function within async watchOrders appear to be correct:

**node_modules/ccxt/dist/cjs/src/pro/bitget.js: around line 800**
`const orders = await this.watchPrivate(messageHash, subscriptionHash, args, params);
`
```
{
     messageHash: 'order',
     subscriptionHash: 'order:trades',
     args: { instType: 'SUMCBL', channel: 'ordersAlgo', instId: 'default' },
     params: { sandboxMode: true }
}
```

But it is bringing other information from an opening market order that I placed and not a stop order

Is there something I'm doing wrong?
I debugged the outputs in the CCXT code and as far as I was able to follow the implementation I did, it was on the correct path, but I don't know if there is anything else I need to do that I didn't do.

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @nvrossett 

I can't reproduce, would you like to paste verbose log?

**Comment by nvrossett** [comment]
Of course, one thing I noticed is that programmatically it calls the watchOrders functions

But internally the channel of the first function blocks that of the second, take a look:

In the watchPrivate() function I added this console.log on top of the return to see what each parameter returned:

`console.log('async watchPrivate: ', url, messageHash, message, subscriptionHash);
`
And he gave me this back:

```
async watchPrivate: wss://ws.bitget.com/spot/v1/stream balance:sumcbl {
   op: 'subscribe',
   args: [ { instType: 'SUMCBL', channel: 'account', instId: 'default' } ]
} balance:sumcbl
async watchPrivate: wss://ws.bitget.com/spot/v1/stream order:SXRP/SUSDT:SUSDT {
   op: 'subscribe',
   args: [ { instType: 'SUMCBL', channel: 'orders', instId: 'default' } ]
} order:trades
async watchPrivate: wss://ws.bitget.com/spot/v1/stream order:SXRP/SUSDT:SUSDT {
   op: 'subscribe',
   args: [ { instType: 'SUMCBL', channel: 'ordersAlgo', instId: 'default' } ]
} order:trades
```

Notice that ordersAlgo exists at this moment, as it was executed in the code.

Now the log coming from verbose:

```
2023-11-03T09:54:42.796Z onMessage { event: 'login', code: 0 }
2023-11-03T09:54:42.798Z sending {
   op: 'subscribe',
   args: [ { instType: 'SUMCBL', channel: 'account', instId: 'default' } ]
}
2023-11-03T09:54:42.799Z sending {
   op: 'subscribe',
   args: [ { instType: 'SUMCBL', channel: 'orders', instId: 'default' } ]
}
2023-11-03T09:54:43.091Z onMessage {
   event: 'subscribe',
   arg: { instType: 'sumcbl', channel: 'account', instId: 'default' }
}
2023-11-03T09:54:43.092Z onMessage {
   event: 'subscribe',
   arg: { instType: 'sumcbl', channel: 'orders', instId: 'default' }
}
```

It doesn't display the ordersAlgo, plus this is my code

```
async function watchBitgetOrders(throttling, describe, BTW) {

             while (true) {

                 try {
                     const order = await BTW.EXCHANGE.CCXT.watchOrders('SXRP/SUSDT:SUSDT')
                     BTW.PassiveMode.TRIGGER.orders(order, 'watchOrders:' + describe, BTW)
                     if (throttling >= 0) { await BTW.EXCHANGE.CCXT.sleep(throttling) }

                 } catch (error) {
                     console.full('Error in BTW.PassiveMode.loadOrders - pattern.bitget.js - watchBitgetOrders() | ' + error)
                     if (throttling >= 0) { await BTW.EXCHANGE.CCXT.sleep(throttling) }
                 }
             }

         }


         async function watchBitgetStopOrders(throttling, describe, BTW) {

             while (true) {

                 try {
                     const stopOrders = await BTW.EXCHANGE.CCXT.watchOrders('SXRP/SUSDT:SUSDT', undefined, undefined, { stop: true })
                     BTW.PassiveMode.TRIGGER.orders(stopOrders, 'watchOrdersStop:' + describe, BTW)
                     if (throttling >= 0) { await BTW.EXCHANGE.CCXT.sleep(throttling) }

                 } catch (error) {
                     console.full('Error in BTW.PassiveMode.loadOrders - pattern.bitget.js - watchBitgetStopOrders() | ' + error)
                     if (throttling >= 0) { await BTW.EXCHANGE.CCXT.sleep(throttling) }
                 }

             }

         }



         if (BTW.EXCHANGE.CCXT.has['watchOrders']) {

             watchBitgetOrders(throttling, describe, BTW)
             watchBitgetStopOrders(throttling, describe, BTW)

         } else {
             console.log(`The watchOrders command is not supported by exchange ${BTW.CONFIG.exchangeData.ccxt_exchange}`)
         }
```

I even provisionally separated them into different functions before thinking about verbose, so that each one had its own scope, and it still didn't work.

But when I command the line
watchBitgetOrders(throttling, describe, BTW)

In other words, the function that calls the main code, the verbose shows the ordersAlgo

```
2023-11-03T10:05:00.470Z onMessage { event: 'login', code: 0 }
2023-11-03T10:05:00.473Z sending {
   op: 'subscribe',
   args: [ { instType: 'SUMCBL', channel: 'account', instId: 'default' } ]
}
2023-11-03T10:05:00.474Z sending {
   op: 'subscribe',
   args: [ { instType: 'SUMCBL', channel: 'ordersAlgo', instId: 'default' } ]
}
2023-11-03T10:05:00.764Z onMessage {
   event: 'subscribe',
   arg: { instType: 'sumcbl', channel: 'account', instId: 'default' }
}
2023-11-03T10:05:00.765Z onMessage {
   event: 'subscribe',
   arg: { instType: 'sumcbl', channel: 'ordersAlgo', instId: 'default' }
}
```

In other words, it appears that the code calls the functions, but it is not reading both channels simultaneously!!

It only lets one read, the other doesn't do anything

That's it, thanks for the help

**Comment by carlosmiei** [comment]
Hello @nvrossett, I managed to reproduce this issue, we will fix it asap.

**Comment by nvrossett** [comment]
Oh, excellent!!!
Thanks for the feedback @carlosmiei

**Comment by nvrossett** [comment]
@carlosmiei 
I downloaded the update and the correction was excellent, now it reads both channels!!

But there was a bug with the status that now comes as undefined because the status of this type of order does not come in a status field but in a state field.

**info.state: 'not_trigger'**
**status: undefined** 

I don't know all of your conventions but I don't know if this is the only field that has a problem, but that's what I noticed because it's important in my flow.

I'm going to make the adjustment on my side because I still don't know how the workflow works to collaborate with the project, I've only been using CCXT for a short time and I'm loving the work they've done, but soon I intend to be more in the know and collaborate, you guys They did a fantastic job, congratulations to everyone involved.

And thank you very much for your help

```
{
      info: {
        actualSz: '0.000000000',
        cOid: '2fc336Ss2so-260L6tp51681124-oe',
        cTime: '1699129813555',
        eps: 'api',
        hM: 'double_hold',
        id: '1104796001515413506',
        instId: 'SXRPSUSDT_SUMCBL',
        key: '1104796001515413506',
        ordPx: '0.612300000',
        ordType: 'market',
        planType: 'sl',
        posSide: 'short',
        side: 'buy',
        state: 'not_trigger',
        sz: '42.000000000',
        tS: 'close_short',
        tgtCcy: 'SUSDT',
        triggerPx: '0.612300000',
        triggerPxType: 'last',
        triggerTime: '1699129813555',
        uTime: '1699129813555',
        userId: '6403615997',
        version: 1104796001372807200
      },
      symbol: 'SXRP/SUSDT:SUSDT',
      id: '1104796001515413506',
      clientOrderId: '2fc336Ss2so-260L6tp51681124-oe',
      timestamp: 1699129813555,
      datetime: '2023-11-04T20:30:13.555Z',
      lastTradeTimestamp: undefined,
      type: 'market',
      timeInForce: 'IOC',
      postOnly: undefined,
      side: 'buy',
      price: undefined,
      stopPrice: 0.6123,
      triggerPrice: 0.6123,
      amount: 42,
      cost: undefined,
      average: undefined,
      filled: undefined,
      remaining: undefined,
      status: undefined,
      fee: undefined,
      trades: [],
      fees: [],
      lastUpdateTimestamp: undefined,
      reduceOnly: undefined,
      takeProfitPrice: undefined,
      stopLossPrice: undefined
    } 
```
