### ISSUE TITLE
User report - socks5 misfunctionality

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#19771]
### Operating System

n/a

### Programming Languages

Python

### CCXT Version

n/a

### Description

> I'm having issues with the error being raised because of mismatching IPs. Is there anything I'm doing obviously wrong at first glance? 

### Code

```
import time
import ccxt
proxy_ip_addresss = 'deleted for privacy'
port = 'deleted for privacy'
user = 'deleted for privacy'
password = 'deleted for privacy'
ccxt_binance_settings = {'enableRateLimit': True, 'options': {'createMarketBuyOrderRequiresPrice': False}}
ccxt_binance = ccxt.binance (ccxt_binance_settings)
⁠ccxt_binance.socksProxy = 'socks5://user:password@127.0.0.1:8080'
ccxt_binance.socksProxy = 'socks5://' + user + ':' + password + '@' + proxy_ip_addresss + ':' + port
tested_ip = ccxt_binance.fetch('https://api.ipify.org/')
if tested_ip != proxy_ip_addresss:
    print(tested_ip)
    print(proxy_ip_addresss)
    raise ValueError('Wrong IP on Proxy')
```

**Comment by MrMechanical** [comment]
I'm using MacOS 12.1 and ccxt 300.1.0 and I just realized my version was outdated, so I updated to the most recent version. Now I am receiving a timeout error, (maybe my proxy is too slow)? I have a proxy from US to Asia

venv/lib/python3.11/site-packages/ccxt/base/exchange.py", line 615, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: binance GET https://api.ipify.org/

**Comment by MrMechanical** [comment]
I believe this maybe an issue with the proxy, I will reach out to my provider to see what's up. My apologies I believe this is an issue with the proxy.

**Comment by MrMechanical** [comment]
My apologies this error is on my end 
<img width="592" alt="Screen Shot 2023-11-01 at 7 57 39 AM" src="https://github.com/ccxt/ccxt/assets/28378318/1f60a0f7-46ba-478c-8515-b603b7244657">

**Comment by MrMechanical** [comment]
Update: Proxy restarted itself automatically. Code works now!

**Comment by ttodua** [comment]
@MrMechanical you'r welcome. good luck ✌️
