### ISSUE TITLE
Order cache memory usage

### ISSUE THREAD

**Issue by rdbr** [ccxt/ccxt#1978]
Over time, the order cache gets filled with all orders that were ever created, closed and cancelled. Orders are never dropped from the cache, which I can understand if you want the complete history.

Maybe an option could be added to clean out closed and cancelled orders after a certain amount of time, because the memory usage is increasing a lot over time. Eventually an out of memory could occur without some limits.

**Comment by mkutny** [comment]
An order consumes roughly 300 bytes of memory, so 10k orders would consume roughly 3Mb. Forecasting further if you create/cancel orders with 1 sec ratelimit you'll end up with roughly 45k orders per day or 15Mb/day increase.

It does not imply it's impossible for the cache to exhaust your memory, just curious if you really have any memory issues. Because if you do but your order management strategy is not that aggressive it might indicate a memory leak somewhere else.

**Comment by rdbr** [comment]
One order per second (most exchanges allow for more api calls per second or editOrder) results in 86400 orders. This causes the memory to grow, assuming 300 bytes per order, 25MB per day per exchange.
Orders also store the server result in the `info` property, so order sizes can vary between exchanges.

If the use case is an algorithm that runs 24/7 even with this simple example, a 4GB memory would be exhausted in 163 days on a single exchange, purely with the order cache.

For long running systems, it would be sensible to limit the memory usage.

**Comment by kroitor** [comment]
I'm going to add some info to the Manual on how to purge outdated entries from cache, will update you here asap.

**Comment by kroitor** [comment]
Ok, we have added a non-automatic `purgeCachedOrders(before) / purge_cached_orders(before)` method. The user is responsible for calling it from time to time to purge older orders history. A call to that method will delete from `.orders` cache where `(order['timestamp'] <= before) && (order['status'] != 'open')`. Documented here: https://github.com/ccxt/ccxt/wiki/Manual#purging-cached-orders

Later on we will add an option to the constructor params to control the cache invalidation automatically and purge old orders from cache in background transparently to the user.

Let us know if you have any difficulties or questions with the added method. Thx!

**Comment by rdbr** [comment]
Great solution, thanks!
