### ISSUE TITLE
Whats the issue with BCC and bittrex?

### ISSUE THREAD

**Issue by gerardo15** [ccxt/ccxt#1979]
Error: bittrex does not have market symbol BCC/BTC

When trying to buy and sell.

But the market clearly exist:

https://bittrex.com/Market/Index?MarketName=BTC-BCC

I started to get this problem a few days ago.

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
- https://github.com/ccxt/ccxt/wiki/Manual#naming-consistency
- https://github.com/ccxt/ccxt/wiki/Manual#consistency-of-base-and-quote-currencies

> Whats the issue with BCC and bittrex?

From the Manual:

> BCC → BCH: The Bitcoin Cash fork is often called with two different symbolic names: BCC and BCH. The name BCC is ambiguous for Bitcoin Cash, it is confused with BitConnect. The ccxt library will convert BCC to BCH where it is appropriate (some exchanges and aggregators confuse them).

Absolutely no issues ) How do you think so many people are using it? )

**Comment by gerardo15** [comment]
Hey kroitor.

But it was working fine, thats what i mean.. i am know getting this error like if bittrex changed something.

**Comment by gerardo15** [comment]
![image](https://user-images.githubusercontent.com/12488663/36423283-93d5b83a-163f-11e8-9da4-61a1cac3e33c.png)

Whats even wierder, is that it creates the order, but when i try to sell it, it gives the error.. i mean.. if it is changed.. it will be for buy and sell.. not only for sell...

**Comment by kroitor** [comment]
@gerardo15 

> But it was working fine, thats what i mean.. i am now getting this error like if bittrex changed something.

According to this: it was like that since August 2017, that's six months or more with that behaviour in ccxt (and it was documented from the very beginning, as ccxt appeared almost the same time the BCC fork happened):

- https://github.com/ccxt/ccxt/issues/129

So, maybe you were using some very-very-very old version and updated. Or, maybe you migrated your environment somewhere. Or, tons of other possible guesses... Hard to tell without more info from you, really.

> Whats even wierder, is that it creates the order, but when i try to sell it, it gives the error.. i mean.. if it is changed.. it will be for buy and sell.. not only for sell...

It creates a buy order, but you can't *"sell a buy order"*, so, I don't fully get it... Or did you mean, that you're able to place buy orders, but not sell orders? If the latter is the case, then, please, post your minimal snippet of code with ccxt to reproduce the problem (the shortest possible, but a complete one). 

Standing by for a follow-up on this from you. Thx!

**Comment by gerardo15** [comment]
Ok,

Let me try to explain better.

I was not using BCC market untill a week ago, so probably you are right this is a problem with bittrex that already have time..

So now my question is... how is letting me buy but not letting me sell..

As you can see in the image, i was able to buy BCC by sending BCC/BTC to the API

Later that day i tried selling by BCC/BTC the same amount and now it gets that error..

**Comment by kroitor** [comment]
Later that day i tried selling by BCC/BTC the same amount and now it gets that error..

Ok, I have just answered what to do in that case ) Need more info (your code and your verbose output) ;)

**Comment by gerardo15** [comment]
```
    static fixmercado(mercado){
        let res = mercado.split("-");
        return res[1]+"/"+res[0];
    }
    static async authorize( row ){
        let plataforma = new ccxt.bittrex();
        plataforma.apiKey = functions.decrypt(row.apikey);
        plataforma.secret = functions.decrypt(row.apisecret);
        return plataforma;
    }
    static async buy(row){
        let plataforma = await this.authorize(row);
        let result = {};
        await plataforma.createLimitBuyOrder (functions.fixmercado(row.mercado_compra), row.cantidad_compra, row.precio_compra)
            .then(function(value) {
                result.uuid = value.id;
                result.status = "success";
            }, function(reason) {
                result.status = "error";
                result.error = reason;
            });
        return result;
    }

    static async sell(row){
        let plataforma = await this.authorize(row);
        let result = {};
        await plataforma.createLimitSellOrder (functions.fixmercado(row.mercado), row.cantidad, row.precio_vender)
            .then(function(value) {
                result.uuid = value.id;
                result.status = "success";
            }, function(reason) {
                result.status = "error";
                result.error = reason;
            });
        return result;
    }
```

In my app i have it "BTC-BCC", the function fixmercado change is to BCC/BTC

i will try to get the verbose thing later

Thanks!

**Comment by kroitor** [comment]
> In my app i have it "BTC-BCC", the function fixmercado change is to BCC/BTC

You're not using ccxt properly. 

1. Read from here (really carefully): https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

No need for `fixmercado` at all, no need for fixing the symbol at all, just use:

- `plataforma.createLimitBuyOrder ('BCH/BTC', row.cantidad_compra, row.precio_compra)
- `plataforma.createLimitSellOrder ('BCH/BTC', row.cantidad, row.precio_vender)`

2. Change the way you create the exchange in the `authorize` like so:

```JavaScript
    static async authorize( row ){
        let plataforma = new ccxt.bittrex();
        plataforma.apiKey = functions.decrypt(row.apikey);
        plataforma.secret = functions.decrypt(row.apisecret);
        plataforma.enableRateLimit = true; // ←------------------------- ADD THIS LINE
        return plataforma;
    }
```

**Comment by gerardo15** [comment]
Hello.

I know how the symbols works for CCXT.

so for 1, 2 and 3

is just i have a whole infraestructure working with "BTC-COIN" structure, and it is easier to change that than change all my database and coins for all the exchanges.

What happens if i enable enableRateLimit = true?

**Comment by kroitor** [comment]
> What happens if i enable enableRateLimit = true?

It's explained in (3) about rate limiting ;) Basically, it starts adding microdelays between sending your requests, so that you wouldn't abuse the exchange with too many subsequent calls (otherwise they will ban you for that).
