### ISSUE TITLE
Can't place FOK & IOC orders on Huobi

### ISSUE THREAD

**Issue by Nicoalz** [ccxt/ccxt#19809]
### Operating System

macOS 14

### Programming Languages

JavaScript

### CCXT Version

"ccxt": "^3.0.47",

### Description

I can place FOK or IOC order easily on binance, kucoin, gate but not on Huobi.
I tried huobi and huobi pro
On market ETH/USDT
symbol= market.symbol
side = 'buy'
amount = 1
price = 1500
exchange.createOrder(symbol, "limit", side, amount, price, params);

I tried different params, always as object : 

- timeInForce: "IOC"
- timeInForce: "ioc"
- timeInForce: "FOK"
- timeInForce: "foc"
- order_price_type: "FOK"
- order_price_type: "fok"
- order_price_type: "IOC"
- order_price_type: "ioc"

It always make a GTC limit order, and never FOK or IOC.
No error message

### Code

```
  exchange.createOrder(symbol, "limit", side, amount, price, params);

```

**Comment by carlosmiei** [comment]
Hello @Nicoalz, I noticed that you have a pretty outdated version of ccxt, is it possible to upgrade and try  again with a newer version?

**Comment by carlosmiei** [comment]
@Nicoalz You're right TIF was not unified, I added a PR to unify it. 
We should release it in a few hours and if you update to that it should work so I suggest updating right after the new release (4.1.38)
