### ISSUE TITLE
Cobinhood requires 'secret'

### ISSUE THREAD

**Issue by theolux** [ccxt/ccxt#1980]
- OS: W10
- Programming Language version: Python 3.6.4
- CCXT version: 1.10.1163
- Exchange: Cobinhood
- Method: fetch_balance()

Authorization only requires api key however I'm getting:
ccxt.base.errors.AuthenticationError: cobinhood requires 'secret'

**Comment by kroitor** [comment]
This is a known issue in common implementation and it will be fixed very soon, it has already been addressed by this commit that is the next in the line to be merged: https://github.com/ccxt/ccxt/pull/1957

Let us know if it doesn't answer your issue. Closing it as a duplicate if you don't mind, will notify you on this asap.

**Comment by kasnitski** [comment]
@kroitor looks, like #1957 fix only for JS. But the same problem with python. Could you please take a look?

**Comment by kroitor** [comment]
@kasnitski the python version is generated from js )

**Comment by kasnitski** [comment]
@kroitor ah, I see. Cool. Sorry for the stupid answer )

**Comment by kroitor** [comment]
@kasnitski no worries ) let us know if you have any questions )

**Comment by kasnitski** [comment]
what about check_required_credentials before the setting parameters? I'm not sure, but looks like we will get an error during validation:
<img width="723" alt="screen shot 2018-02-21 at 1 46 08 am" src="https://user-images.githubusercontent.com/849638/36453447-0ec6183c-16a9-11e8-9e9e-4e400b86c2ac.png">

**Comment by kroitor** [comment]
@kasnitski https://github.com/ccxt/ccxt/wiki/Manual#authentication
