### ISSUE TITLE
exchange.create_order_ws

### ISSUE THREAD

**Issue by 89d55d5288** [ccxt/ccxt#19805]
### Operating System

windows

### Programming Languages

Python

### CCXT Version

last

### Description

Could you please tell me how to work with create_order_ws correctly?

Is it necessary to initialize exchange.create_order_ws and keep the connection open?

If it is necessary to keep the connection open, what is the best way to realize it?

For example: the first time exchange.create_order_ws is executed on Binance, it takes 1.8 seconds to send a request to the exchange and receive a response.

When exchange.create_order_ws is called a second time, it takes 0.4 seconds (taking into account network ping).

If the circulation time between requests is more than 1 hour, it takes 1.8 seconds, just like the first time.

The initial call await exchange.load_markets() is made, it has no problems.

### Code

async def set_open_orders(exchange, symbol, type, side, amount, price):
    while True:
        try:
            print(exchange, symbol, datetime.now())           
            st = time.time()
            if exchange.has.get('fetchOrderWs'):
                order = await exchange.create_order_ws(symbol, type, side, amount, price)
            else:
                order = await exchange.create_order(symbol, type, side, amount, price)
            print(exchange, 'order_id = ', order['id'])
            print(f"Ордер с ID {order['id']}  {exchange}  {time.time() - st} {datetime.now()}")
            break     
        except Exception as e:
            print(f"Error {exchange}: {e}")
            await handle_error(e, exchange, 'Open Orders')
    return order

### Code

**Comment by sc0Vu** [comment]
Hi @89d55d5288 

That's necessary to keep the connection. I think you can reduce the sending time by load markets first (`await exchange.load_markets()`).

**Comment by 6642248687** [comment]
> ### Sistema operativo
> ventanas
> 
> ### Lenguajes de programación
> Pitón
> 
> ### Versión CCXT
> último
> 
> ### Descripción
> ¿Podría decirme cómo trabajar correctamente con create_order_ws?
> 
> ¿Es necesario inicializar exchange.create_order_ws y mantener la conexión abierta?
> 
> Si es necesario mantener abierta la conexión, ¿cuál es la mejor forma de realizarlo?
> 
> Por ejemplo: la primera vez que se ejecuta exchange.create_order_ws en Binance, se necesitan 1,8 segundos para enviar una solicitud al intercambio y recibir una respuesta.
> 
> Cuando se llama a exchange.create_order_ws por segunda vez, tarda 0,4 segundos (teniendo en cuenta el ping de red).
> 
> Si el tiempo de circulación entre solicitudes es superior a 1 hora, se necesitan 1,8 segundos, como la primera vez.
> 
> Se realiza la llamada inicial await exchange.load_markets(), no tiene problemas.
> 
> ### Código
> async def set_open_orders(exchange, símbolo, tipo, lado, monto, precio): while True: intente: print(exchange, símbolo, datetime.now()) st = time.time() if exchange.has.get('fetchOrderWs '): pedido = esperar intercambio.create_order_ws(símbolo, tipo, lado, monto, precio) else: pedido = esperar intercambio.create_order(símbolo, tipo, lado, monto, precio) print(exchange, 'order_id = ', pedido[ 'id']) print(f"Ордер с ID {order['id']} {exchange} {time.time() - st} {datetime.now()}") break excepto Excepción como e: print(f "Error {exchange}: {e}") espera handle_error(e, exchange, 'Open Orders') orden de devolución
> 
> ### Código

**Comment by 89d55d5288** [comment]
> The initial call await exchange.load_markets() is made, it has no problems.



> Hi @89d55d5288
> 
> That's necessary to keep the connection. I think you can reduce the sending time by load markets first (`await exchange.load_markets()`).

Earlier I pointed out

The initial call await exchange.load_markets() is made, it has no problems.

I.e., that I perform the initial await exchange.load_markets() operation before execution. And await exchange.load_markets() is not a problem. Because the first call order = await exchange.create_order_ws(symbol, type, side, amount, price) still takes a long time to execute despite the pre-call await exchange.load_markets().

**Comment by 89d55d5288** [comment]
> Hi @89d55d5288
> 
> That's necessary to keep the connection. I think you can reduce the sending time by load markets first (`await exchange.load_markets()`).

**Comment by 89d55d5288** [comment]
> Is it necessary to initialize exchange.create_order_ws and keep the connection open?
> 
> If it is necessary to keep the connection open, what is the best way to realize it?

**Note** that the main question is as follows:

Is it necessary to initialize exchange.create_order_ws and keep the connection open?
If it is necessary to keep the connection open, what is the best way to realize it?

If not difficult, please show a ### **working example of "keep the connection open".**

**Comment by 89d55d5288** [comment]
Enabled exchange.verbose = True
And I observe that during the first call exchange.create_order_ws(symbol, type, side, amount, price)
connecting to wss://ws-api.binance.com:443/ws-api/v3 with timeout 10000 ms takes place.
2023-11-03 16:41:27.064987
**2023-11-03T10:41:27.066Z connecting to wss://ws-api.binance.com:443/ws-api/v3 with timeout 10000 ms
2023-11-03T10:41:28.496Z connected**
2023-11-03T10:41:28.496Z ping loop

Accordingly, with the second call exchange.create_order_ws(symbol, type, side, amount, price) in one cycle there is already a connection and the order is opened quickly.

The question remains open.
How to pre-initialize connecting to wss://ws-api.binance.com:443/ws-api/v3
and how to keep the connection open for subsequent calls?

**Comment by sc0Vu** [comment]
Hi @89d55d5288 

Due to client is cached by message hash in ws implementation, the next call would be faster (no initial connection cost) https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/base/exchange.py#L371 .

I think you can call `watch(...)` with the same parameters we used in `create_order_ws` to pre-initialize and cache the connection, maybe in parallel way if you want to use different watch function.

**Comment by 89d55d5288** [comment]
> Hi @89d55d5288
> 
> Due to client is cached by message hash in ws implementation, the next call would be faster (no initial connection cost) https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/base/exchange.py#L371 .
> 
> I think you can call `watch(...)` with the same parameters we used in `create_order_ws` to pre-initialize and cache the connection, maybe in parallel way if you want to use different watch function.

Hi sc0Vu

Thanks for the information.

I checked the suggested method

exchange.watch(symbol, type, side, amount, price)

order = await exchange.create_order_ws(symbol, type, side, amount, price)

and got the following
2023-11-04-04T07:20:56.578Z connecting to USDT/RUB with timeout 10000 ms
2023-11-04T07:20:56.578Z NetworkError USDT/RUB
2023-11-04-04T07:20:56.578Z on_error USDT/RUB
**2023-11-04T07:20:56.579Z connecting to wss://ws-api.binance.com:443/ws-api/v3 with timeout 10000 ms
2023-11-04T07:20:57.982Z connected**
2023-11-04-04T07:20:57.983Z ping loop

I think I misunderstood your example.

**Comment by sc0Vu** [comment]
It's possible to do, but you'll need to create connection manually, and simulate what we do in the function. Why not create an order ws first (the connection would be created and cached)? BTW, I've created an example to create order through ws, lmk if you have any other issue.

**Comment by 89d55d5288** [comment]
> It's possible to do, but you'll need to create connection manually, and simulate what we do in the function. Why not create an order ws first (the connection would be created and cached)? BTW, I've created an example to create order through ws, lmk if you have any other issue.

Hi sc0Vu
I was looking at your example. It standardly opens the order and creates the first ws-connection, I already wrote about it above.

But the problem is that the time of the first connection is 2 seconds minimum.

And the market situation changes quickly and 2 seconds is a loss. I am interested in the question of initialisation of ws-connection before opening the first order. In advance. For example, when creating a connection via orderbook. And when there will be a situation on the market, the script should immediately open the order, and not wait for the initial ws connection.

**Comment by 89d55d5288** [comment]
new problem
after updating from 4.1.39 to version ccxt 4.1.50 an error appears (in 4.1.39 everything works fine):
Future exception was never retrieved
future: <Future finished exception=DDoSProtection('binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action"}')>
Traceback (most recent call last):
   File "/home//.local/lib/python3.12/site-packages/ccxt/pro/binance.py", line 2218, in load_positions_snapshot
     positions = await self.fetch_positions(None, {'type': type})
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home//.local/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 7242, in fetch_positions
     return await self.fetch_positions_risk(symbols, params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home//.local/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 7294, in fetch_positions_risk
     await self.load_leverage_brackets(False, params)
   File "/home//.local/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 6968, in load_leverage_brackets
     response = await getattr(self, method)(query)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home//.local/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 8029, in request
     response = await self.fetch2(path, api, method, params, headers, body, config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^
   File "/home//.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 1984, in fetch2
     return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home//.local/lib/python3.12/site-packages/ccxt/async_support/base/exchange.py", line 220, in fetch
     self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
   File "/home//.local/lib/python3.12/site-packages/ccxt/async_support/binance.py", line 7989, in handle_errors
     raise DDoSProtection(self.id + ' ' + body)
ccxt.base.errors.DDoSProtection: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action"}
