### ISSUE TITLE
Fatal error ccxt\mb_split()

### ISSUE THREAD

**Issue by 2l1k** [ccxt/ccxt#1981]
Fatal error
: Call to undefined function ccxt\mb_split() in
/home/ccxt-master/php/Exchange.php
on line
650

**Comment by kroitor** [comment]
You need the following PHP extensions installed to work with the PHP version of ccxt:

> It requires common PHP modules:

> - cURL
> - mbstring (using UTF-8 is highly recommended)
> - PCRE
> - iconv

https://github.com/ccxt/ccxt/wiki/Install#php

Alternatively, you can simply install it with Composer and it will satisfy the dependencies automatically.

Let us know if it doesn't answer your question. Thx!
