### ISSUE TITLE
Fail on "pip install ccxt" - Amazon EC2

### ISSUE THREAD

**Issue by rtadewald** [ccxt/ccxt#1983]
I'm having trouble trying to install CCXT on Amazon EC2's Ubuntu (16.04).

When using: `sudo pip install ccxt` i get:

` Could not find a version that satisfies the requirement aiohttp==3.0.1; python_version >= "3.5" (from ccxt) (from versions: 0.1, 0.2, 0.3, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.18.0, 0.18.1, 0.18.2, 0.18.3, 0.18.4, 0.19.0, 0.20.0, 0.20.1, 0.20.2, 0.21.0, 0.21.1, 0.21.2, 0.21.4, 0.21.5, 0.21.6, 0.22.0a0, 0.22.0b0, 0.22.0b1, 0.22.0b2, 0.22.0b3, 0.22.0b4, 0.22.0b5, 0.22.0b6, 0.22.0, 0.22.1, 0.22.2, 0.22.3, 0.22.4, 0.22.5, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.6.post1, 2.0.7, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3.0a1, 2.3.0a2, 2.3.0a4, 2.3.0, 2.3.1a1, 2.3.1, 2.3.2b2, 2.3.2b3, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.3.10, 3.0.0b0)
No matching distribution found for aiohttp==3.0.1; python_version >= "3.5" (from ccxt)
`

Thanks for the help!

**Comment by kroitor** [comment]
You need to update your Python3 version to at least 3.5.2 in order to install aiohttp. Let us know if it does not help. Thx!

**Comment by rtadewald** [comment]
Perfect! Thanks!!

**Comment by selphaware** [comment]
I'm also having a similar issue but with a different error. Any help would be great. Thanks:

pip install ccxt

Collecting ccxt
  Using cached ccxt-1.40.25-py2.py3-none-any.whl (2.0 MB)
Requirement already satisfied: requests>=2.18.4 in ./anaconda3/lib/python3.9/site-packages (from ccxt) (2.25.1)
Requirement already satisfied: setuptools>=38.5.1 in ./anaconda3/lib/python3.9/site-packages (from ccxt) (51.0.0.post20201207)
Requirement already satisfied: certifi>=2018.1.18 in ./anaconda3/lib/python3.9/site-packages (from ccxt) (2020.12.5)
Requirement already satisfied: cryptography>=2.6.1 in ./anaconda3/lib/python3.9/site-packages (from ccxt) (3.3.1)
Requirement already satisfied: yarl==1.1.0 in ./anaconda3/lib/python3.9/site-packages (from ccxt) (1.1.0)
Requirement already satisfied: multidict>=4.0 in ./anaconda3/lib/python3.9/site-packages (from yarl==1.1.0->ccxt) (5.1.0)
Requirement already satisfied: idna>=2.0 in ./anaconda3/lib/python3.9/site-packages (from yarl==1.1.0->ccxt) (2.10)
Collecting aiodns<2.1,>=1.1.1
  Using cached aiodns-2.0.0-py2.py3-none-any.whl (4.8 kB)
Collecting aiohttp<3.8,>=3.7.2
  Using cached aiohttp-3.7.3-cp39-cp39-manylinux2014_x86_64.whl (1.4 MB)
Requirement already satisfied: typing-extensions>=3.6.5 in ./anaconda3/lib/python3.9/site-packages (from aiohttp<3.8,>=3.7.2->ccxt) (3.7.4.3)
Collecting async-timeout<4.0,>=3.0
  Using cached async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting attrs>=17.3.0
  Using cached attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Collecting chardet<4.0,>=2.0
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Requirement already satisfied: cffi>=1.12 in ./anaconda3/lib/python3.9/site-packages (from cryptography>=2.6.1->ccxt) (1.14.4)
Requirement already satisfied: six>=1.4.1 in ./anaconda3/lib/python3.9/site-packages (from cryptography>=2.6.1->ccxt) (1.15.0)
Requirement already satisfied: pycparser in ./anaconda3/lib/python3.9/site-packages (from cffi>=1.12->cryptography>=2.6.1->ccxt) (2.20)
Collecting pycares>=3.0.0
  Using cached pycares-3.1.1.tar.gz (233 kB)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./anaconda3/lib/python3.9/site-packages (from requests>=2.18.4->ccxt) (1.26.2)
Building wheels for collected packages: pycares
  Building wheel for pycares (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t2mjjs87/pycares_88fbf3312da742709d5c92742e73a245/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t2mjjs87/pycares_88fbf3312da742709d5c92742e73a245/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-kwgxvkzj
       cwd: /tmp/pip-install-t2mjjs87/pycares_88fbf3312da742709d5c92742e73a245/
  Complete output (22 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/pycares
  copying src/pycares/__init__.py -> build/lib.linux-x86_64-3.9/pycares
  copying src/pycares/errno.py -> build/lib.linux-x86_64-3.9/pycares
  copying src/pycares/utils.py -> build/lib.linux-x86_64-3.9/pycares
  copying src/pycares/_version.py -> build/lib.linux-x86_64-3.9/pycares
  copying src/pycares/__main__.py -> build/lib.linux-x86_64-3.9/pycares
  running build_ext
  generating cffi module 'build/temp.linux-x86_64-3.9/_cares.c'
  creating build/temp.linux-x86_64-3.9
  building '_cares' extension
  creating build/temp.linux-x86_64-3.9/build
  creating build/temp.linux-x86_64-3.9/build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/deps
  creating build/temp.linux-x86_64-3.9/deps/c-ares
  creating build/temp.linux-x86_64-3.9/deps/c-ares/src
  gcc -pthread -B /home/ubuntu/anaconda3/compiler_compat -Wl,--sysroot=/ -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/ubuntu/anaconda3/include -fPIC -O2 -isystem /home/ubuntu/anaconda3/include -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -I/home/ubuntu/anaconda3/include/python3.9 -Ideps/c-ares/src -Ideps/c-ares/src/config_linux -c build/temp.linux-x86_64-3.9/_cares.c -o build/temp.linux-x86_64-3.9/build/temp.linux-x86_64-3.9/_cares.o
  error: command 'gcc' failed: No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for pycares
  Running setup.py clean for pycares
Failed to build pycares
Installing collected packages: pycares, chardet, attrs, async-timeout, aiohttp, aiodns, ccxt
    Running setup.py install for pycares ... error
    ERROR: Command errored out with exit status 1:
     command: /home/ubuntu/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t2mjjs87/pycares_88fbf3312da742709d5c92742e73a245/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t2mjjs87/pycares_88fbf3312da742709d5c92742e73a245/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vryvjdry/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubuntu/anaconda3/include/python3.9/pycares
         cwd: /tmp/pip-install-t2mjjs87/pycares_88fbf3312da742709d5c92742e73a245/
    Complete output (22 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/pycares
    copying src/pycares/__init__.py -> build/lib.linux-x86_64-3.9/pycares
    copying src/pycares/errno.py -> build/lib.linux-x86_64-3.9/pycares
    copying src/pycares/utils.py -> build/lib.linux-x86_64-3.9/pycares
    copying src/pycares/_version.py -> build/lib.linux-x86_64-3.9/pycares
    copying src/pycares/__main__.py -> build/lib.linux-x86_64-3.9/pycares
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-3.9/_cares.c'
    creating build/temp.linux-x86_64-3.9
    building '_cares' extension
    creating build/temp.linux-x86_64-3.9/build
    creating build/temp.linux-x86_64-3.9/build/temp.linux-x86_64-3.9
    creating build/temp.linux-x86_64-3.9/deps
    creating build/temp.linux-x86_64-3.9/deps/c-ares
    creating build/temp.linux-x86_64-3.9/deps/c-ares/src
    gcc -pthread -B /home/ubuntu/anaconda3/compiler_compat -Wl,--sysroot=/ -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/ubuntu/anaconda3/include -fPIC -O2 -isystem /home/ubuntu/anaconda3/include -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -I/home/ubuntu/anaconda3/include/python3.9 -Ideps/c-ares/src -Ideps/c-ares/src/config_linux -c build/temp.linux-x86_64-3.9/_cares.c -o build/temp.linux-x86_64-3.9/build/temp.linux-x86_64-3.9/_cares.o
    error: command 'gcc' failed: No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ubuntu/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t2mjjs87/pycares_88fbf3312da742709d5c92742e73a245/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t2mjjs87/pycares_88fbf3312da742709d5c92742e73a245/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vryvjdry/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubuntu/anaconda3/include/python3.9/pycares Check the logs for full command output.

conda -V
conda 4.9.2

**Comment by kroitor** [comment]
@selphaware 

> error: command 'gcc' failed: No such file or directory

I think it says you must have `gcc` in order to compile the dependencies, and you don't have it, apparently.

**Comment by selphaware** [comment]
Thanks I just figured it out:

sudo apt install gcc <-- resolved this.

Thank you

**Comment by miharbines** [comment]
Hi my proje transfer to ubuntu but I can't not install ccxi ... 


root@miharbines:/home/miharbines# pip3 install ccxt
Collecting ccxt
  Using cached https://files.pythonhosted.org/packages/1c/52/8b71c8093e94b675626b46aeb5084705431c602f2751cc9cdb3f8a99b8e6/ccxt-2.2.63-py2.py3-none-any.whl
Collecting aiodns>=1.1.1; python_version >= "3.5.2" (from ccxt)
  Using cached https://files.pythonhosted.org/packages/ab/72/991ee33a517df69c6cd6f3486cfe9b6329557cb55acaa8cefac33c2aa4d2/aiodns-3.0.0-py3-none-any.whl
Collecting cryptography>=2.6.1 (from ccxt)
  Using cached https://files.pythonhosted.org/packages/e3/3f/41186b1f2fd86a542d399175f6b8e43f82cd4dfa51235a0b030a042b811a/cryptography-38.0.4.tar.gz
Collecting setuptools>=60.9.0 (from ccxt)
  Could not find a version that satisfies the requirement setuptools>=60.9.0 (from ccxt) (from versions: 0.6b1, 0.6b2, 0.6b3, 0.6b4, 0.6rc1, 0.6rc2, 0.6rc3, 0.6rc4, 0.6rc5, 0.6rc6, 0.6rc7, 0.6rc8, 0.6rc9, 0.6rc10, 0.6rc11, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.8, 0.9, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 1.0, 1.1, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.2, 1.3, 1.3.1, 1.3.2, 1.4, 1.4.1, 1.4.2, 2.0, 2.0.1, 2.0.2, 2.1, 2.1.1, 2.1.2, 2.2, 3.0, 3.0.1, 3.0.2, 3.1, 3.2, 3.3, 3.4, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.5, 3.5.1, 3.5.2, 3.6, 3.7, 3.7.1, 3.8, 3.8.1, 4.0, 4.0.1, 5.0, 5.0.1, 5.0.2, 5.1, 5.2, 5.3, 5.4, 5.4.1, 5.4.2, 5.5, 5.5.1, 5.6, 5.7, 5.8, 6.0.1, 6.0.2, 6.1, 7.0, 8.0, 8.0.1, 8.0.2, 8.0.3, 8.0.4, 8.1, 8.2, 8.2.1, 8.3, 9.0, 9.0.1, 9.1, 10.0, 10.0.1, 10.1, 10.2, 10.2.1, 11.0, 11.1, 11.2, 11.3, 11.3.1, 12.0, 12.0.1, 12.0.2, 12.0.3, 12.0.4, 12.0.5, 12.1, 12.2, 12.3, 12.4, 13.0.1, 13.0.2, 14.0, 14.1, 14.1.1, 14.2, 14.3, 14.3.1, 15.0, 15.1, 15.2, 16.0, 17.0, 17.1, 17.1.1, 18.0, 18.0.1, 18.1, 18.2, 18.3, 18.3.1, 18.3.2, 18.4, 18.5, 18.6, 18.6.1, 18.7, 18.7.1, 18.8, 18.8.1, 19.0, 19.1, 19.1.1, 19.2, 19.3, 19.4, 19.4.1, 19.5, 19.6, 19.6.1, 19.6.2, 19.7, 20.0, 20.1, 20.1.1, 20.2.2, 20.3, 20.3.1, 20.4, 20.6.6, 20.6.7, 20.6.8, 20.7.0, 20.8.0, 20.8.1, 20.9.0, 20.10.1, 21.0.0, 21.1.0, 21.2.0, 21.2.1, 21.2.2, 22.0.0, 22.0.1, 22.0.2, 22.0.4, 22.0.5, 23.0.0, 23.1.0, 23.2.0, 23.2.1, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 24.1.0, 24.1.1, 24.2.0, 24.2.1, 24.3.0, 24.3.1, 25.0.0, 25.0.1, 25.0.2, 25.1.0, 25.1.1, 25.1.2, 25.1.3, 25.1.4, 25.1.5, 25.1.6, 25.2.0, 25.3.0, 25.4.0, 26.0.0, 26.1.0, 26.1.1, 27.0.0, 27.1.0, 27.1.2, 27.2.0, 27.3.0, 27.3.1, 28.0.0, 28.1.0, 28.2.0, 28.3.0, 28.4.0, 28.5.0, 28.6.0, 28.6.1, 28.7.0, 28.7.1, 28.8.0, 28.8.1, 29.0.0, 29.0.1, 30.0.0, 30.1.0, 30.2.0, 30.2.1, 30.3.0, 30.4.0, 31.0.0, 31.0.1, 32.0.0, 32.1.0, 32.1.1, 32.1.2, 32.1.3, 32.2.0, 32.3.0, 32.3.1, 33.1.0, 33.1.1, 34.0.0, 34.0.1, 34.0.2, 34.0.3, 34.1.0, 34.1.1, 34.2.0, 34.3.0, 34.3.1, 34.3.2, 34.3.3, 34.4.0, 34.4.1, 35.0.0, 35.0.1, 35.0.2, 36.0.1, 36.1.0, 36.1.1, 36.2.0, 36.2.1, 36.2.2, 36.2.3, 36.2.4, 36.2.5, 36.2.6, 36.2.7, 36.3.0, 36.4.0, 36.5.0, 36.6.0, 36.6.1, 36.7.0, 36.7.1, 36.7.2, 36.8.0, 37.0.0, 38.0.0, 38.1.0, 38.2.0, 38.2.1, 38.2.3, 38.2.4, 38.2.5, 38.3.0, 38.4.0, 38.4.1, 38.5.0, 38.5.1, 38.5.2, 38.6.0, 38.6.1, 38.7.0, 39.0.0, 39.0.1, 39.1.0, 39.2.0, 40.0.0, 40.1.0, 40.1.1, 40.2.0, 40.3.0, 40.4.0, 40.4.1, 40.4.2, 40.4.3, 40.5.0, 40.6.0, 40.6.1, 40.6.2, 40.6.3, 40.7.0, 40.7.1, 40.7.2, 40.7.3, 40.8.0, 40.9.0, 41.0.0, 41.0.1, 41.1.0, 41.2.0, 41.3.0, 41.4.0, 41.5.0, 41.5.1, 41.6.0, 42.0.0, 42.0.1, 42.0.2, 43.0.0, 44.0.0, 44.1.0, 44.1.1, 45.0.0, 45.1.0, 45.2.0, 45.3.0, 46.0.0, 46.1.0, 46.1.1, 46.1.2, 46.1.3, 46.2.0, 46.3.0, 46.3.1, 46.4.0, 47.0.0, 47.1.0, 47.1.1, 47.2.0, 47.3.0, 47.3.1, 47.3.2, 48.0.0, 49.0.0, 49.0.1, 49.1.0, 49.1.1, 49.1.2, 49.1.3, 49.2.0, 49.2.1, 49.3.0, 49.3.1, 49.3.2, 49.4.0, 49.5.0, 49.6.0, 50.0.0, 50.0.1, 50.0.2, 50.0.3, 50.1.0, 50.2.0, 50.3.0, 50.3.1, 50.3.2, 51.0.0, 51.1.0, 51.1.0.post20201221, 51.1.1, 51.1.2, 51.2.0, 51.3.0, 51.3.1, 51.3.2, 51.3.3, 52.0.0, 53.0.0, 53.1.0, 54.0.0, 54.1.0, 54.1.1, 54.1.2, 54.1.3, 54.2.0, 56.0.0, 56.1.0, 56.2.0, 57.0.0, 57.1.0, 57.2.0, 57.3.0, 57.4.0, 57.5.0, 58.0.0, 58.0.1, 58.0.2, 58.0.3, 58.0.4, 58.1.0, 58.2.0, 58.3.0, 58.4.0, 58.5.0, 58.5.1, 58.5.2, 58.5.3, 59.0.1, 59.1.0, 59.1.1, 59.2.0, 59.3.0, 59.4.0, 59.5.0, 59.6.0)
No matching distribution found for setuptools>=60.9.0 (from ccxt)
root@miharbines:/home/miharbines#

**Comment by yueliulin** [comment]
How did you solve this problem
