### ISSUE TITLE
BUN IO With CCXT

### ISSUE THREAD

**Issue by kenchambers** [ccxt/ccxt#19845]
### Operating System

Mac os big sur 11.4

### Programming Languages

JavaScript

### CCXT Version

"^4.1.39"

## Summary

Hello!

I am running a very simple BUN Server, trying to get CCXT to work with bun.

package json: 

```json
{
  "name": "bot-farms-v5",
  "module": "index.ts",
  "type": "module",
  "devDependencies": {
    "bun-types": "^1.0.9"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  },
  "dependencies": {
    "ccxt": "^4.1.39"
  }
}
```

My tsconfig: 

```json
{
  "compilerOptions": {
    "lib": ["ESNext", "dom"],
    "module": "esnext",
    "target": "esnext",
    "moduleResolution": "bundler",
    "moduleDetection": "force",
    "allowImportingTsExtensions": true,
    "noEmit": true,
    "composite": true,
    "strict": true,
    "downlevelIteration": true,
    "skipLibCheck": true,
    "jsx": "react-jsx",
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "allowJs": true,
    "types": [
      "bun-types" // add Bun global
    ]
  }
}

```

I am getting this error when i try to run `fetchBalance`

```
316 |                 });
317 |                 return;
318 |             }
319 |             // For br
320 |             if (codings === 'br') {
321 |                 body = pump(body, zlib.createBrotliDecompress(), error => {
                                      ^
TypeError: zlib.createBrotliDecompress is not a function. (In 'zlib.createBrotliDecompress()', 'zlib.createBrotliDecompress' is undefined)
      at /Users/ken/Documents/GitHub/bot-farms-v5/node_modules/ccxt/js/src/static_dependencies/node-fetch/index.js:321:34
      at node:http:868:28
      at processTicksAndRejections (:61:76)

```

### Code

```js
  console.log('Hello via Bun!')

import ccxt from 'ccxt'

const server = Bun.serve({
  port: 3000,
  fetch(req) {
    return new Response('Bun!')
  }
})

const config = {
  apiKey: Bun.env.KRAKEN_API_KEY,
  secret: Bun.env.KRAKEN_API_SECRET,
  enableRateLimit: true
}
const exchange = new ccxt.kraken(config)

// console.log(exchange)

async function fetchBalance() {
  exchange.fetchBalance()
}

async function start() {
  const something = await fetchBalance()
  // console.log(something)
}

start()

console.log(`Listening on http://localhost:${server.port} ...`)


```

**Comment by sc0Vu** [comment]
HI @kenchambers 

It seems they didn't implement brotli in bun yet see: https://github.com/oven-sh/bun/issues/267.

Also here: https://bun.sh/docs/runtime/nodejs-apis#node-zlib

> [node:zlib](https://nodejs.org/api/zlib.html)
> 🟡 Missing BrotliCompress BrotliDecompress brotliCompressSync > brotliDecompress brotliDecompressSync createBrotliCompress createBrotliDecompress. Unoptimized.

Can you change accept-encoding in the header (remove br)?

**Comment by RicoCelsius** [comment]
> HI @kenchambers
> 
> It seems they didn't implement brotli in bun yet see: [oven-sh/bun#267](https://github.com/oven-sh/bun/issues/267).
> 
> Also here: https://bun.sh/docs/runtime/nodejs-apis#node-zlib
> 
> > [node:zlib](https://nodejs.org/api/zlib.html)
> > 🟡 Missing BrotliCompress BrotliDecompress brotliCompressSync > brotliDecompress brotliDecompressSync createBrotliCompress createBrotliDecompress. Unoptimized.
> 
> Can you change accept-encoding (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding) in the header (remove br) and see whether it work or not?


Anyone struggling with this:
adding:


```
  headers: {
    "Accept-Encoding": "gzip, deflate",
  },
```

property to the exchange object did the trick!

**Comment by kroitor** [comment]
@RicoCelsius thx for your feedback and for posting the solution here!
