### ISSUE TITLE
Bug in pro/mexc.py

### ISSUE THREAD

**Issue by DVridovic** [ccxt/ccxt#19867]
### Operating System

Linux

### Programming Languages

Python

### CCXT Version

latest

### Description

Line 1021 in an error handler in pro/mexc.py reads

            url = self.urls['api']['ws'] + '?listenKey=' + listenKey

However, self.urls['api']['ws'] is a dictionary:

{'spot': 'wss://wbs.mexc.com/ws', 'swap': 'wss://contract.mexc.com/ws'}

One cannot add dictionaries and strings.

### Code

```
  

```

**Comment by Dan-krm** [comment]
@DVridovic thanks for reporting, I opened a pull request that will fix this issue
