### ISSUE TITLE
How to get a US $ price for all currencies on Binance?

### ISSUE THREAD

**Issue by kamov** [ccxt/ccxt#1986]
Like coinmarketcap, I would to create a table for list all coins from binance with price and info.

I am checking examples, but I can't find (PHP) the one for get price for single coin, or all coins.

Thanks

**Comment by kroitor** [comment]
Check out this example:

https://github.com/ccxt/ccxt/blob/master/examples/php/binance-fetch-tickers.php

Also:

```
php -f examples/php/cli.php binance fetch_tickers 
```

(warning, don't call this more than once in 2 minutes)

Docs: 

- https://github.com/ccxt/ccxt/wiki/Manual#price-tickers
- https://github.com/ccxt/ccxt/wiki/Manual (highly recommended, will save your time and money ;))

**Comment by kamov** [comment]
Thank you. I already try this example, but it not return what I need.

For example this is response for ETH/BTC:

```json
Array
(
    [symbol] => ETH/BTC
    [timestamp] => 1519158814256
    [datetime] => 2018-02-20T20:33:34.256+00:00
    [high] => 0.084711
    [low] => 0.070828
    [bid] => 0.078705
    [bidVolume] => 4.97
    [ask] => 0.078743
    [askVolume] => 1.148
    [vwap] => 0.08184416
    [open] => 0.084683
    [close] => 0.084684
    [first] => 
    [last] => 0.078743
    [change] => -0.00594
    [percentage] => -7.014
    [average] => 
    [baseVolume] => 110275.823
    [quoteVolume] => 9025.43260953
    [info] => Array
        (
            [symbol] => ETHBTC
            [priceChange] => -0.00594000
            [priceChangePercent] => -7.014
            [weightedAvgPrice] => 0.08184416
            [prevClosePrice] => 0.08468400
            [lastPrice] => 0.07874300
            [lastQty] => 0.66600000
            [bidPrice] => 0.07870500
            [bidQty] => 4.97000000
            [askPrice] => 0.07874300
            [askQty] => 1.14800000
            [openPrice] => 0.08468300
            [highPrice] => 0.08471100
            [lowPrice] => 0.07082800
            [volume] => 110275.82300000
            [quoteVolume] => 9025.43260953
            [openTime] => 1519072414256
            [closeTime] => 1519158814256
            [firstId] => 35971032
            [lastId] => 36279008
            [count] => 307977
        )

)
```

I would like to list price in US $ which here don't appear.

Thanks

**Comment by kroitor** [comment]
Price in US $ of what? )

**Comment by kamov** [comment]
In binance there is also price in US$ for each coin, see:

![screen shot 2018-02-20 at 21 44 35](https://user-images.githubusercontent.com/2345000/36448255-4c1f5fd0-1687-11e8-8b13-82cd87e77724.png)


Also coinmarketcap show price in USD for each coin:
https://coinmarketcap.com/exchanges/binance/

So I wonder how to get this using your library.

**Comment by mkutny** [comment]
What binance and coinmarketcap show on the screenshots provided is a cross-rate.

ccxt allows you to get TRX/ETH rate with ease, but if you want TRX/USD rate (which is not directly provided by the exchange) then you need to get ETH/USD and compute TRX/ETH/USD cross-rate yourself.

**Comment by kroitor** [comment]
@kamov the answer of @mkutny is correct, the library won't do rate-conversions (basic divisions and multiplications) for you, it will provide you with data, and you should multiply yourself, like the exchange in question (Binance in this case) does it. This is because the rates you will be converting with are unknown to the library. You can take the USD price rates from coinmarketcap, or from some arbitrary exchange, so there's no single globally-true USD rate, you will have to start diving into the theory of currency and finance. In short, a conversion rate depends on who is converting.

**Comment by kamov** [comment]
>ccxt allows you to get TRX/ETH rate with ease, but if you want TRX/USD rate (which is not directly provided by the exchange) then you need to get ETH/USD and compute TRX/ETH/USD cross-rate yourself.

Thanks for your explanation.
I understand what you mean.
But you suggest to use ETH/USD which don't exist in binance:
https://www.binance.com/trade.html?symbol=ETH_USD

So I am not sure how to that basic divisions/multiplications.

So all price here on coinmarketcap, for example see ethereum:
https://coinmarketcap.com/currencies/ethereum/#markets

this is not coming directly from exchange, but is calculated by coinmarketcap?
Strange, because is very accurate.

But the main question still remain, from where to get the price in USD for start do math..
Because on coinmarketcap all price in USD is different, so they can't get the price of ETH from single source.

If I understand correctly, I need for example:

1) Get price in USD for ETH from coinbase API (I see they provide), now is: 820$ for 1 ETH

2) Get the price in ETH for TRX, now: 0.00005238ETH for 1 TRX

3) Convert price of ETH value of 1 TRX using 820$: 0.00005238 * 820 = 0.0429516$

It's that correct?

For HITBTC would be: 0.0000522 * 820 = 0.042804$
https://hitbtc.com/TRX-to-ETH

Any idea from where binance get the price of USD?
They should start from somewhere..

> or from some arbitrary exchange (like, the USDT rate from Binance itself, or a USD rate from some other exchange)

USDT could be a good solution..
I just hope that will not disappear after implementation as I hear some rumours about.

**Comment by kroitor** [comment]
> It's that correct?

Yes, everything is correct. 

However, on step 1:

> Get price in USD for ETH from coinbase API (I see they provide), now is: 820$ for 1 ETH

Most people would get an *"independent"* rate from CoinMarketCap, because Coinbase = GDAX. When you get USD for ETH from Coinbase, you're actually getting it almost directly from GDAX. And GDAX is an exchange itself, so Coinbase isn't an independent source of price info, it is GDAX-related at the very least.

On step 2:

> price in ETH for TRX

Think: what if you take BTC instead of ETH ? Would it lead to a different result in the end? ;) Turns out the intermediary currency can introduce a difference... ;)

> I just hope that will not disappear after implementation as I hear some rumours about.

Get used to be adaptive )
