### ISSUE TITLE
Missing Console/Table.php in example

### ISSUE THREAD

**Issue by kamov** [ccxt/ccxt#1987]
This is missing https://github.com/ccxt/ccxt/blob/master/examples/php/symbols.php#L6

**Comment by kornrunner** [comment]
That's actually using https://pear.php.net/package/Console_Table/

**Comment by kroitor** [comment]
@kornrunner thanks for answering! )

@kamov let us know if the answer of @kornrunner doesn't clarify it. Basically, you want to install that PEAR package to use that example or just replace the outputting function with a less readable `print_r`...

**Comment by kamov** [comment]
Thanks!
