### ISSUE TITLE
ccxt.pro vs ccxt.async_support

### ISSUE THREAD

**Issue by Hadevmin** [ccxt/ccxt#19887]
Hello,

I usually use the ccxt.async_support library to use ccxt. I thought we could use WS through this object but I was wrong because I found that for krakenfutures and bybit the objects in async_support do not inherit WS methods.
I know the difference between ccxt.exchange and ccxt.async_support.exchange. But what's the difference between ccxt.pro.exchange and ccxt.async_support.exchange?
To know if I can change the constructor of my ccxt object to use WS without modifying all portions of my code.

Thanks

**Comment by sc0Vu** [comment]
Hi @Hadevmin,

ccxt.pro is ws integration for exchanges. async support is async integration for exchanges, eg. we integrated reactPHP in php.

**Comment by Hadevmin** [comment]
Hi @sc0Vu,

Is it possible to wait until my question has been answered before closing my issue? Once closed, even if I tag you, you don't answer anymore...
So to complete my question, ccxt pro supports async. So ccxt.pro has all the features of ccxt.async_support?

Thanks

**Comment by sc0Vu** [comment]
Hi @Hadevmin,

Yes, that's correct. In python, the pro version actually inherit async one (https://docs.python.org/3/tutorial/classes.html#inheritance), eg. `class alpaca(ccxt.async_support.alpaca):`.

**Comment by Hadevmin** [comment]
@sc0Vu thanks you for your answer.
Just out of curiosity, is the split between async_support and pro just for code architecture?
Because then there's no point in using async_support, you might as well use pro to get more functionality?

**Comment by sc0Vu** [comment]
@Hadevmin 

The reason might be that pro was closed source software, and we want to support async feature for the ccxt functions in other languages.

Also, user don't need ws and want to use async feature can use async_support.

**Comment by Hadevmin** [comment]
Great answer, now I can close the issue :)
Sorry I created another issue but I can't reopen the closed issues.
I'm going to change my ccxt objects to create them with ccxt.pro , thanks for the information.
