### ISSUE TITLE
TakeProfit order tied to a position-opening primary order

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#19884]
Hello,

I'm having trouble to implement the feature [StopLoss And TakeProfit Orders Attached To A Position](https://docs.ccxt.com/#/?id=stoploss-and-takeprofit-orders-attached-to-a-position), the following parameters are rejected by Binance : 

```
{'amount': '0.0307',
 'params': {'clientOrderId': '0vou2',
            'takeProfit': {'price': '35389.06',
                           'triggerPrice': '35389.06',
                           'type': 'Limit'}},
 'price': '35318.42',
 'side': 'buy',
 'symbol': 'BTC/FDUSD',
 'type': 'limit'}
```

Error cause :

`Not all sent parameters were read; read '11' parameter(s) but was sent '12'.
`

When I remove the `takeProfit` key the order is placed. Could you please tell if this feature is supported by Binance and if so what could be the reason of the issue ?

Thank you,
Kinzowa

**Comment by carlosmiei** [comment]
Hello @Kinzowa, unfortunately I don't think Binance supports that feature yet through the API (it's not a ccxt limitation).

**Comment by Kinzowa** [comment]
Hi Carlos, thanks for your answer. I will place several orders inline then.
