### ISSUE TITLE
Coinbase Sandbox implementation

### ISSUE THREAD

**Issue by burkaykinik** [ccxt/ccxt#19881]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

Coinbase exchange has a sandbox environment, but it is not implemented in CCXT right now. 

### Describe the solution you'd like

URLS in the [coinbase sandbox page](https://docs.cloud.coinbase.com/exchange/docs/sandbox) needs to be added to the exchange's urls as test.

**Comment by Dan-krm** [comment]
Hi @burkaykinik those URLS are for coinbase pro, I did some testing and that URL doesn't seem to work properly with the endpoints in the coinbase class. If you want to use the coinbase testnet you can use it with the coinbasepro exchange class
