### ISSUE TITLE
Issues #19875 and #19887

### ISSUE THREAD

**Issue by Hadevmin** [ccxt/ccxt#19893]
Hello,

I'm sorry but I have to reopen an issue because sc0Vu doesn't answer my questions and closes the issues and then doesn't answer anymore....

1. https://github.com/ccxt/ccxt/issues/19875
I have a big speed gap between my home library that I was using for kraken futures and using ccxt.async_support.krakenfutures. So I wanted to know a bit more about the ccxt rate limits mechanism as requested in issue #19875 to be able to investigate the speed difference.

2. https://github.com/ccxt/ccxt/issues/19887
I'm aware that ccxt.pro integrates WS and async_support asynchronous calls... As requested in issue #19887 , I did some tests and I wonder if ccxt.pro has all the functionality of ccxt.async_support?

Thanks for your answers,
Regards

**Comment by sc0Vu** [comment]
Hi @Hadevmin 

Can you reopen the issues?

**Comment by Hadevmin** [comment]
Hi @sc0Vu ,

I can't
