### ISSUE TITLE
More implicit api binance portfolio margin conditional order endpoints

### ISSUE THREAD

**Issue by L1nkus** [ccxt/ccxt#19917]
### Description

Hi,

Following up on the last issue, there's some more:

DELETE /papi/v1/um/conditional/allOpenOrders
DELETE /papi/v1/cm/conditional/allOpenOrders

(thx for the prev one btw)

**Comment by frosty00** [comment]
https://binance-docs.github.io/apidocs/pm/en/#cancel-all-um-open-conditional-orders-trade
https://binance-docs.github.io/apidocs/pm/en/#cancel-all-cm-open-conditional-orders-trade
