### ISSUE TITLE
Instantiation ccxt object

### ISSUE THREAD

**Issue by Hadevmin** [ccxt/ccxt#19914]
Hello,

Since I've been using ccxt, I instantiate my objects as shown in the documentation(https://github.com/ccxt/ccxt/wiki/Manual#instantiation), putting a ", }" at the end:` ccxt.exchange({k1: v1, k2: v2, })`
Is this still useful, and if so, how?

Thanks

**Comment by sc0Vu** [comment]
Hi @Hadevmin 

Can you elaborate more about your question?

**Comment by Hadevmin** [comment]
Hi @sc0Vu ,

sorry, for example:
```
exchange = exchange_class({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
```
After `'secret': 'YOUR_SECRET'` you have a `, ` with blank space before close the dictionary.
Is it useful? And if yes, what is the utility of that?

Is this more understandable?
Regards

**Comment by carlosmiei** [comment]
@Hadevmin Hello, that's simply a trailing comma and has no impact whatsoever, you can keep it or remove it.

**Comment by Hadevmin** [comment]
Hello @carlosmiei ,
I hope you're well.
Ok, thanks, it's just that I wasn't used to seeing this in python when declaring a dictionary.

Thanks for the clarification
