### ISSUE TITLE
Phemex Php - g-accounts/positions (Question)

### ISSUE THREAD

**Issue by mtokitt** [ccxt/ccxt#19912]
### Operating System

Apache

### Programming Languages

PHP

### CCXT Version

Latest

### Description

Hi, when trying to get Phemex account positions un-PNL, as suggested in the docs (https://phemex-docs.github.io/#query-account-positions-with-unrealized-pnl) 
I never seem to receive any sort of "unRealisedPnlRv": field returned within the data.

 Have tried all the... GET /g-accounts/positions?currency=<currency> listed methods such as: "private_get_accounts_accountpositions", "private_get_g_accounts_accountpositions", "privateGetAccountsAccountPositions","privateGetGAccountsAccountPositions","privateGetAccountsPositions", "fetch_balance" etc.. but only get back the result withOut the "unRealisedPnlRv": field displayed in docs.
Please could you advise which method to get the "unRealisedPnlRv" ?
(Many thanks for your efforts.)

### Code

```
  [{"userID":"xxx4027","accountID":"xxx40270003","symbol":"SEIUSDT","currency":"USDT","side":"Buy","positionStatus":"Normal","crossMargin":false,"leverageRr":"20","initMarginReqRr":"0.05","maintMarginReqRr":"0.025","riskLimitRv":"25000","size":"10","valueRv":"1.165","avgEntryPriceRp":"0.1165","avgEntryPrice":"0.1165","posCostRv":"0.05891405","assignedPosBalanceRv":"0.06091405","bankruptCommRv":"0.00066284928","bankruptPriceRp":"0.1105","positionMarginRv":"0.06025120072","liquidationPriceRp":"0.1134","deleveragePercentileRr":"0","buyValueToCostRr":"0.05117","sellValueToCostRr":"0.05123","markPriceRp":"0.11845305","estimatedOrdLossRv":"0","usedBalanceRv":"0.06091405","cumClosedPnlRv":"-0.0975","cumFundingFeeRv":"0.00045363071","cumTransactFeeRv":"0.0029607","transactTimeNs":"1699550353088434961","takerFeeRateRr":"0.0006","makerFeeRateRr":"0.0001","term":"2","lastTermEndTimeNs":"1699546026076853302","lastFundingTimeNs":"1699545600000000000","curTermRealisedPnlRv":"-0.000699","execSeq":"3128887732","posSide":"Long","posMode":"Hedged","buyLeavesValueRv":"0","sellLeavesValueRv":"0"}]  //<---- no "unRealisedPnlRv"

```

**Comment by Dan-krm** [comment]
Hi @mtokitt sometimes the response from the exchange is different from what is shown in their API docs, there's also a chance that the unRealisedPnlRv value is only returned in certain conditions like for cross margin positions. You could also try `privateGetAccountsAccountPositions` and check for any unrealizedPNL values.

It looks like the `unrealizedPnl` is being derived for you by CCXT in the `fetchPositions` implementation. So I would try calling `fetchPositions` and see if you can get an `unrealizedPnl` value that way.

closes: #19913
