### ISSUE TITLE
mexc not withdraw

### ISSUE THREAD

**Issue by aliromero** [ccxt/ccxt#19924]
### Operating System

ubuntu

### Exchange Name

Mexc

### Programming Languages

PHP

### CCXT Version

4.0.3

### Description

We have a problem since yesterday, please check

### Code

```
$slug='TRX';
$network = 'Tron(TRC20)';
$params = ["chain" => $network];  
$response = $mexc->withdraw($slug, 200, 'removed', '', $params);

```

```
  mexc {
        "code": 10232,
        "msg": "The currency not exist. Please check coin name and chain is correct.",
        "timestamp": 1699696972491
    }
```

**Comment by sc0Vu** [comment]
It looks like the network value was't uppercase anymore. I'll submit PR to fix this asap.
