### ISSUE TITLE
New Exchange: Commex

### ISSUE THREAD

**Issue by Wannafly7** [ccxt/ccxt#19922]
### Exchange Name

Commex

### URL of the Exchange

https://www.commex.com

### URL of the Exchange's API docs

https://www.commex.com/api-docs/en/#commex-rest-open-api

### Why should this exchange be implemented?

Commex is a new cryptocurrency exchange that spun off from Binance and gained a lot of users.

**Comment by ArpitKRS** [comment]
Please /assign this issue to me and let's discuss over it.

**Comment by kalitvyan** [comment]
Guys, is there any progress on this issue?

**Comment by brarrow** [comment]
I'm really looking forward to commex support. The commex API is almost the same as binance.

**Comment by ttodua** [comment]
Seems exchange was shut down
