### ISSUE TITLE
Coinbase fetchMyTrades - No amount

### ISSUE THREAD

**Issue by BHruska** [ccxt/ccxt#19931]
### Operating System

Windows 11

### Programming Languages

Python

### CCXT Version

4.1.24

### Description

Trying to switch from Coinbase Pro to Coinbase, since they are closing down the former at the EOM.  I have code which fetches trades that's worked for years, for all exchanges, that doesn't work for Coinbase.  It appears the fetchMyTrades() function isn't returning an amount for the number of coins.  

Here's two json responses, one for COINBASE, and one for KRAKEN.

`COINBASE
{
    "info": {
        "entry_id": "5cb90a4640f167ee3c06a8d1e64d978c0d1f7aef16263ac52f42c0979715f4bf",
        "trade_id": "761475a1-210c-4d8a-8c8d-511383a323cb",
        "order_id": "e65843a3-a9b4-47db-ba26-be49c214bf67",
        "trade_time": "2023-10-31T22:10:12.473787913Z",
        "trade_type": "FILL",
        "price": "37.44",
        "size": "0.0802691053677932",
        "commission": "0.0004816146322068",
        "product_id": "SOL-USDC",
        "sequence_timestamp": "2023-10-31T22:10:12.474588Z",
        "liquidity_indicator": "UNKNOWN_LIQUIDITY_INDICATOR",
        "size_in_quote": true,
        "user_id": "1cf3f598-b952-5b98-8b27-9ef247d342fa",
        "side": "BUY"
    },
    "id": "761475a1-210c-4d8a-8c8d-511383a323cb",
    "order": "e65843a3-a9b4-47db-ba26-be49c214bf67",
    "timestamp": 1698790212473,
    "datetime": "2023-10-31T22:10:12.473787913Z",
    "symbol": "SOL/USDC",
    "type": null,
    "side": "buy",
    "takerOrMaker": null,
    "price": 37.44,
    "amount": null,
    "cost": 0.0802691053677932,
    "fee": {
        "cost": 0.0004816146322068,
        "currency": null
    },
    "fees": [
        {
            "cost": 0.0004816146322068,
            "currency": null
        }
    ]
}`

`KRAKEN
{
    "id": "TJNB46-GI77A-MKITHD",
    "order": "OEZO6V-SNEOZ-4PRHCS",
    "info": {
        "ordertxid": "OEZO6V-SNEOZ-4PRHCS",
        "postxid": "TKH2SE-M7IF5-CFI7LT",
        "pair": "SOLUSD",
        "time": "1698163571.0675573",
        "type": "buy",
        "ordertype": "limit",
        "price": "30.36000",
        "cost": "59.99136",
        "fee": "0.09599",
        "vol": "1.97600000",
        "margin": "0.00000",
        "leverage": "0",
        "misc": "",
        "trade_id": "8846515",
        "id": "TJNB46-GI77A-MKITHD"
    },
    "timestamp": 1698163571067,
    "datetime": "2023-10-24T16:06:11.067Z",
    "symbol": "SOL/USD",
    "type": "limit",
    "side": "buy",
    "takerOrMaker": null,
    "price": 30.36,
    "amount": 1.976,
    "cost": 59.99136,
    "fee": {
        "cost": 0.09599,
        "currency": "USD"
    },
    "fees": [
        {
            "cost": 0.09599,
            "currency": "USD"
        }
    ]
}`

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @BHruska,
Thanks for letting us know, we will check it asap.

**Comment by sc0Vu** [comment]
Hi @carlosmiei 

Because the size was for quote, the amount was set to undefined. Can we calculate the amount by `quote size / price`? It would be `0.0802691053677932/37.44=0.00214393978 ` in this trade.

**Comment by carlosmiei** [comment]
> Hi @carlosmiei
> 
> Because the size was for quote, the amount was set to undefined. Can we calculate the amount by `quote size / price`? It would be `0.0802691053677932/37.44=0.00214393978 ` in this trade.

@sc0Vu, yes I think it's one of the fixes required to be done .

**Comment by BHruska** [comment]
Is this going to get into the python version?  How do I get the fix?  I did a pip update and didn't notice any change.

**Comment by carlosmiei** [comment]
@BHruska We released a couple of hours ago, can you update your ccxt version and try again?

**Comment by BHruska** [comment]
Seems to work!  Thanks.
