### ISSUE TITLE
[bitvavo] calculate_fee suddenly returns None as rate / cost

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#19954]
### Operating System

linux

### Programming Languages

Python

### CCXT Version

4.1.46 / 4.1.51

### Description

``` python
import ccxt
exchange = ccxt.bitvavo()
lm = exchange.load_markets()
print(exchange.calculate_fee('BTC/EUR', 'limit', 'buy', 0.1, 1))
``` 

With 4.1.40 - this above script prints 

```
{'type': 'taker', 'currency': 'EUR', 'rate': 0.0025, 'cost': 0.00025}
```

with 4.1.46 (up to 4.1.51) however, the same script returns

```
{'type': 'taker', 'currency': 'EUR', 'rate': None, 'cost': None}
```

Ad hock, i found that the markets structure content between 4.1.40 and 4.1.46 slightly changed, with the later version no lonnger having the fields maker / taker filled - though from looking at the history, i didn't see any commit that seemed to intentionally remove this.

**Comment by sc0Vu** [comment]
Hi @xmatthias 

Thanks, will submit a PR to fix this.
