### ISSUE TITLE
[bitvavo] load-markets seems to call the same endpoint twice

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#19955]
### Operating System

linux

### CCXT Version

4.1.51

### Description

Running the below script seems to make the same call to https://api.bitvavo.com/v2/assets  twice.

``` python
import ccxt
exchange = ccxt.bitvavo()
exchange.verbose = True
lm = exchange.load_markets()

```

### Output

![image](https://github.com/ccxt/ccxt/assets/5024695/5f2e6b9b-47f4-43ff-907f-bdeda009cfdd)

The full output doesn't fit into an issue, therefore as txt file:
[log.txt](https://github.com/ccxt/ccxt/files/13345022/log.txt)

**edit**
interestingly, this seems to not be the case for 4.1.40 - so it might be related to #19954 after all (i intentionally split the issue as i thought it's not related - sorry if they are).

**Comment by sc0Vu** [comment]
Hi @xmatthias,

Interesting finding, I think we call `fetchCurrencies()` twice.
