### ISSUE TITLE
mexc withdraw is not working

### ISSUE THREAD

**Issue by erenyavas** [ccxt/ccxt#19988]
### Operating System

Windows

### Programming Languages

JavaScript

### CCXT Version

4.0.3

### Description

i tried all of these code but i get `mexc {"code":10232,"msg":"The currency not exist. Please check coin name and chain is correct."}`

this code was working until Sunday

### Code

```
  // this one was working until Sunday
   mexc.withdraw(currency, amount, address, params = { 'chain': 'sol' })

  mexc.withdraw(currency, amount, address, params = { 'chain': 'solana(sol)' })

   mexc.withdraw(currency, amount, address, params = { 'chain': 'solana (sol)' })

    mexc.withdraw(currency, amount, address, params = { 'chain': 'Solana(SOL)' })

   mexc.withdraw(currency, amount, address, params = { 'chain': 'Solana (SOL)' })

```

**Comment by Dan-krm** [comment]
@erenyavas A change was made in this pull request #19926 that changed the `'chain'` param handling to use `safeString` instead of `safeStringUpper` to fix an issue a user was having. So basically the param you're setting used to automatically be converted from `sol` to `SOL` but that's no longer the case.

This request should work for you:
```
mexc.withdraw(currency, amount, address, params = { 'chain': 'SOL' })
```

Let me know if it's still not working for you and I can look into it further

**Comment by erenyavas** [comment]
BadSymbol: mexc {"code":10232,"msg":"The currency not exist. Please check coin name and chain is correct."}

**Comment by Dan-krm** [comment]
> not working :/
> 
> BadSymbol: mexc {"code":10232,"msg":"The currency not exist. Please check coin name and chain is correct."}

Okay I'll look into it

**Comment by Dan-krm** [comment]
@erenyavas Which currency are you trying to withdraw?

**Comment by erenyavas** [comment]
actually all of currencies on solana

**Comment by erenyavas** [comment]
i see but i think this is general alert for mexc about solana. maybe the problem is about MEXC API.

**Comment by erenyavas** [comment]
also i can withdraw on website right now

**Comment by Dan-krm** [comment]
This request seems to have worked for me:
```
mexc.withdraw(USDC, 25, my_solana_address, undefined, '{"network":"Solana(SOL)"}')

{
  info: { id: '7b255dab680d410ea4611862f016d37d' },
  id: '7b255dab680d410ea4611862f016d37d',
  txid: undefined,
  timestamp: undefined,
  datetime: undefined,
  network: undefined,
  address: undefined,
  addressTo: undefined,
  addressFrom: undefined,
  tag: undefined,
  tagTo: undefined,
  tagFrom: undefined,
  type: 'withdrawal',
  amount: undefined,
  currency: 'USDC',
  status: undefined,
  updated: undefined,
  comment: undefined,
  internal: undefined,
  fee: undefined
}
```

It could be a combination of setting the tag argument in the withdraw method to undefined then setting the params after that. and setting the chain or network param to Solana(SOL)

Let me know if that works for you

**Comment by erenyavas** [comment]
thank you very much. it works!

**Comment by Dennisco12** [comment]
I have the same problem and this solution didn't work for me. I use python and this is my request:
mexc.withdraw("USDT", 15, "my_address", tag=None, params={"network": "Tron(TRC20)"})

The error I got is:
BadSymbol: mexc {"code":10232,"msg":"The currency not exist. Please check coin name and chain is correct."}

Might not be related but when I checked the ccxt request url I noticed that the query string in the url has been parsed for only the network parameter to "...&network=Tron%28TRC20%29&...". all other parameters seems to be okay, could this be the reason?
