### ISSUE TITLE
Gate FOK : FOK_NOT_FILL : Error

### ISSUE THREAD

**Issue by Nicoalz** [ccxt/ccxt#19981]
### Operating System

macOS 14

### CCXT Version

"ccxt": "4.1.52",

### Description

When make a FOK order on Gate, if the FOK is not filled, it throw an error while on others exchanges like Kucoin it s not throwing an error but an Order with details, like filled 0 , status cancel etc...

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @Nicoalz, is it possible to share a verbose log with us? so we can see exactly what the issue was

**Comment by Nicoalz** [comment]
I didn't save the full error message but it was something like 
```
gate { label:FOK_NOT_FILL, message: .... }

**Comment by carlosmiei** [comment]
@Nicoalz Ok, in that case, it is an exception thrown directly by the exchange and not a crash in CCXT so I think CCXT can't do much about it besides treating the error and bubble it up to the user. Nonetheless, you can easily catch it and treat it accordingly.

**Comment by Nicoalz** [comment]
Hey that's what I did, I catch it in my code. But I thought you could catch it to interpret it as a FOK order non filled, so filled:0 etc...

**Comment by carlosmiei** [comment]
@Nicoalz I understand, but usually we don't suppress the errors thrown by the exchange
