### ISSUE TITLE
how  to  get 1s  k-line  data？

### ISSUE THREAD

**Issue by aboutgov** [ccxt/ccxt#19982]
### Operating System

centos7.9

### CCXT Version

4.0.78

### Description

    time_interval coud not set  1s?      i  set  1m,  the code is  work !!!!!    when i  set   time_interval = '1s',   the  cose run error,  the error is :    how  can  i  get 1s  k line data? 
---------------
(myenv) [root@ali--ecs macd_rsi_TRB-QT-1s]# python3 kline-1s.py 
Traceback (most recent call last):
  File "/opt/QT/dev/macd_rsi_TRB-QT-1s/kline-1s.py", line 30, in <module>
    df = get_okex_candle_data(exchange, symbol, time_interval)
  File "/opt/QT/dev/macd_rsi_TRB-QT-1s/kline-1s.py", line 20, in get_okex_candle_data
    content = exchange.fetch_ohlcv(symbol, timeframe=time_interval, limit=300)
  File "/myenv/lib/python3.9/site-packages/ccxt/okx.py", line 2049, in fetch_ohlcv
    response = getattr(self, method)(self.extend(request, params))
  File "/myenv/lib/python3.9/site-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/myenv/lib/python3.9/site-packages/ccxt/base/exchange.py", line 3058, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/myenv/lib/python3.9/site-packages/ccxt/base/exchange.py", line 3055, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/myenv/lib/python3.9/site-packages/ccxt/base/exchange.py", line 654, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/myenv/lib/python3.9/site-packages/ccxt/okx.py", line 6357, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], code, feedback)
  File "/myenv/lib/python3.9/site-packages/ccxt/base/exchange.py", line 3421, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: okex {"code":"51000","msg":"Parameter bar error","data":[]}
(myenv) [root@ali--ecs macd_rsi_TRB-QT-1s]# 
=================================

### Code

time_interval = '1s'                #it  not work,  but set 1m ,  it work!!  how can i  get 1s  k  line  data？

symbol = 'TRB-USDT-SWAP'

def get_okex_candle_data(exchange, symbol, time_interval):
   
    content = exchange.fetch_ohlcv(symbol, timeframe=time_interval, limit=300)
    df = pd.DataFrame(content, columns=['MTS', 'open', 'high', 'low', 'close', 'volume'])
    df['candle_begin_time'] = pd.to_datetime(df['MTS'], unit='ms')
    df['candle_begin_time_GMT8'] = df['candle_begin_time'] + timedelta(hours=8)  
    df = df[['candle_begin_time_GMT8', 'open', 'high', 'low', 'close', 'volume']]
    return df

df = get_okex_candle_data(exchange, symbol, time_interval)

print(df)

**Comment by carlosmiei** [comment]
Hello @aboutgov, the smallest timeframe that OKX provides is 1 minute (1m) so you can't get 1s candles from the API. 
https://www.okx.com/docs-v5/en/#order-book-trading-market-data-get-candlesticks

**Comment by aboutgov** [comment]
i just ask okex, they said. history k line  , 1s  para could use,  transaction  k line,  1s para coud not use! 
     how  can  i use  ccxt ,get history 1s  k line？

**Comment by carlosmiei** [comment]
@aboutgov CCXT is a wrapper around the exchange API, if the API does not provide the data ccxt has no means of retrieving it.
