### ISSUE TITLE
bybit createOrder returns 90% unfilled response

### ISSUE THREAD

**Issue by danieltorscho** [ccxt/ccxt#19986]
### Operating System

Win10

### Programming Languages

JavaScript

### CCXT Version

4.1.52

### Description

After being forced to indicate a price for bybit when placing a market buy order, my functions changed from A to B:

I'm not sure what to should I do to make it working again as it worked fine previously, before `createMarketBuyOrderRequiresPrice` has been set to true by default for bybit.

### Code

Before `createMarketBuyOrderRequiresPrice`:
```
const order = await exchange.createMarketBuyOrder('BTC/USDT', 1)
```

After `createMarketBuyOrderRequiresPrice`:
```
const order = await exchange.createOrder('BTC/USDT', 'market', 'buy', 1, 30500)
```

Response for `order` now looks like this, which is not OK:

```
order: {
  info: { orderId: '1554690019071910144', orderLinkId: '1700069492638882' },
  id: '1554690019071910144',
  clientOrderId: '1700069492638882',
  timestamp: undefined,
  datetime: undefined,
  lastTradeTimestamp: undefined,
  lastUpdateTimestamp: undefined,
  symbol: 'BTC/USDT',
  type: undefined,
  timeInForce: undefined,
  postOnly: undefined,
  reduceOnly: undefined,
  side: undefined,
  price: undefined,
  stopPrice: undefined,
  triggerPrice: undefined,
  takeProfitPrice: undefined,
  stopLossPrice: undefined,
  amount: undefined,
  cost: undefined,
  average: undefined,
  filled: undefined,
  remaining: undefined,
  status: undefined,
  fee: undefined,
  trades: [],
  fees: []
}
```

**Comment by Dan-krm** [comment]
Hi @danieltorscho we're limited by the exchanges response for what can be returned from the method, this is what is returned by the createOrder endpoint:
```
{
    "retCode": 0,
    "retMsg": "OK",
    "result": {
        "orderId": "1321003749386327552",
        "orderLinkId": "1700069492638882"
    },
    "retExtInfo": {},
    "time": 1672211918471
}
```
If your response was different previously, we may have updated the endpoint used by createOrder to a new version since you last checked, (bybit recently phased out some of their legacy API's)

The response is the same whether `createMarketBuyOrderRequiresPrice` is set to true or not, you can set `createMarketBuyOrderRequiresPrice` to false in the exchange options and provide the quote amount in the amount argument for createOrder if you want.

You can also call `fetchOrder` with the `id` from createOrder to get a more populated response of your order:
```
const order = await exchange.fetchOrder('1554690019071910144', 'BTC/USDT')
```
`fetchOrders` `fetchOpenOrders` `fetchClosedOrders` `fetchCanceledOrders` and `fetchMyTrades` are other unified methods you might consider for retrieving a more detailed response

**Comment by danieltorscho** [comment]
It seems to be out of my intelectual limits, but I really do not know what to do exactly with it:

My request:
```
const symbol = 'BTC/USDT';
const amount = 0.0033;
const price = 29995.50;

const order = await exchange.createOrder(symbol, 'market', 'buy', amount, price, {
  qty: amount
});
```

And response I get is this:

```
bybit {"retCode":10001,"retMsg":"The order remains unchanged as the parameters entered match the existing ones.","result":{},"retExtInfo":{},"time":1700697269339}
```

Is there more details about such message error ?

**Comment by Dan-krm** [comment]
@danieltorscho you don't need to provide the qty in the params, that is handled by the amount argument, if you're creating a spot market buy order on bybit you can follow one of these approaches:

### Allow the quote quantity to be calculated for you:
Provide the base amount and price and the quote quantity will be calculated for you:
```
const order = await exchange.createOrder (symbol, 'market', 'buy', amount, price);
```

### Set createMarketBuyOrderRequiresPrice to false
Provide the quote quantity (USDT value) in the amount argument and set createMarketBuyOrderRequiresPrice to false:
```
const order = await exchange.createOrder (symbol, 'market', 'buy', quoteAmount, undefined, {"createMarketBuyOrderRequiresPrice":false});
```

### Use the cost param
Provide the quote quantity (USDT value) in the cost param:
```
const order = await exchange.createOrder (symbol, 'market', 'buy', undefined, undefined, {"cost":quoteAmount});
```

### Use the createMarketBuyOrderWithCost method
Use the createMarketBuyOrderWithCost method providing only the symbol and cost (USDT value):
```
const order = await exchange.createMarketBuyOrderWithCost (symbol, quoteAmount);
```
