### ISSUE TITLE
Question - ccxt.pro watch_order_book

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#19995]
### Operating System

all

### Programming Languages

Python

### CCXT Version

latest

### Description

Good day. 

I have reviewed the documentation of ccxt.pro and am somewhat confused about the dataset returned by the subscription to watch_order_book. I wrote a simple Python script that calls watch_order_book and then I receive a continuous stream of data for bid and ask in the form of a long list. It's unclear to me whether this list stores incremental values or a snapshot of the orderbook. Can you help me understand this? My goal is to visually display the complete orderbook on a web page (with price grouping) as done by Binance. (In their case, I am dissatisfied with seeing about 20 aggregated bid and ask records with a step of 100 on the website) but I want to see all records with a step of 100. How feasibly can I implement such functionality using the ccxt.pro library?
Can I use watch_order_book to receive only deltas from the exchanges? If yes, how can this be achieved?

### Code

```
  

```

**Comment by pcriadoperez** [comment]
Hi @YuriyTigiev watch methods by defaut return just the updated values received by the exchange, however if you wish for it to return the full order book you can set `newUpdates` to `false` and also in the case of binance you can set the limit to 1000 to receive a large order book, which I believe is what you are looking for.

I'll close this issue for now, but feel free to reach out with any questions you might have.

**Comment by YuriyTigiev** [comment]
Hello. 
I intend to receive only one bid and ask notification per change, but currently, I'm receiving 1,000 records of bids and asks. At the moment, the average price of Bitcoin is around $35,000, and all the records are approximately at this price. However, I would like to be notified of any changes in limit orders for prices below $20,000 or above $50,000 as well.

**Comment by pcriadoperez** [comment]
Unfortunately 1000 is the largest limit allowed by binance API.

**Comment by YuriyTigiev** [comment]
Can you provide an example of using the `watch_orderbook` function for Binance that returns precisely the same amount of data as the Binance WebSocket itself? That is, only the updated records, not the entire snapshot.
