### ISSUE TITLE
Bitget fetchMyTrades with "since" returns empty trade list

### ISSUE THREAD

**Issue by fl0wo** [ccxt/ccxt#20008]
### Operating System

Linux Ubuntu 22LTS

### Programming Languages

JavaScript

### CCXT Version

^4.1.46

### Description

When calling `fetchMyTrades` with a symbol and "since" an empty trade list is returned.

When called the same method without passing the "since" parameter, it returns the trade list.

Even if setting "since" at 0.

### Code

Found a workaround doing this:
```
  async fetchMyTrades(symbol: string, since?: number) {
        if(!since || since===0) {
            return await this._exchange.fetchMyTrades(symbol);
        }
        return await this._exchange.fetchMyTrades(symbol, since);
    }

```
But for some reason even with correct values of since (e.g. Date.now() - 30_days_in_ms) still something wrong seem to happen.

The same is not happening on binance or other exchanges.

Here's the args I'm using when building the ccxt client:

`   

 const args = {
        apiKey: apiKey,
        secret: apiSecret,
        password: apiPassPhrase,

        enableRateLimit: true,
        verbose: false,
        'newUpdates': true,
        'options': {
            'defaultType': 'spot',
            'tradesLimit': 1000,
            'OHLCVLimit': 1000,
            'ordersLimit': 1000,
            'watchTrades': {
                'name': 'aggTrade'
            },
            'streamLimits': {
                'spot': 180
            }
        }
    };

`

**Comment by sc0Vu** [comment]
Hi @fl0wo 

Did you use spot pair? They only have `after` parameter (use orderId) for spot pair (https://bitgetlimited.github.io/apidoc/en/spot/#get-transaction-details). I think you can use order id before we update (only for spot pair and non margin mode).

**Comment by fl0wo** [comment]
Yep, I'm using spot pairs.

I guess I'll just fetch the trades specifing only the symbol, and then filter those i need post-query.

I'm also using the same method for other exchanges and I'd prefer to avoid using exchange-specific fields when fetching informations.

I know in such way I'd carry heavier packages as I'll be fetching more data even when not needed, but I already have some caching solutions that should help in this regard.

**Comment by sc0Vu** [comment]
Hi @fl0wo 

We've removed `after` parameter for spot pair (https://github.com/ccxt/ccxt/pull/20009). You can upgrade ccxt.

> Note: you still can set `after` in params to filter with `orderId`.
