### ISSUE TITLE
Bitmart: status-mapping wrong

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#20005]
### Operating System

linux

### Programming Languages

Python

### CCXT Version

4.1.55

### Description

When fetching a filled order from bitmart, the order state mapping seems wrong, as i get "filled" - but i'd expect "closed".

from the [ccxt docs](https://docs.ccxt.com/#/README?id=orders):

> `    'status':      'open',        // 'open', 'closed', 'canceled', 'expired', 'rejected'`

Based on the [APi docs](https://developer-pro.bitmart.com/en/spot/#query-order-by-id-v4-signed), the following values are possible for "state":
Order status
-new=The order has been accepted by the engine.
-partially_filled=a part of the order has been filled.
-filled=the order has been completed.
-canceled=the order has been canceled by the user.
-partially_canceled=partially filled canceled

### Code

``` python
import ccxt
exchange = ccxt.bitmart({
    'apiKey': '<yourApiKey>', 
    'secret': '<yoursecret>', 
    'uid': 'apiMemo'
    })
res = exchange.fetch_order(order_id, pair)
print(res)
``` 

```
  {'id': '201025407428332391',
 'clientOrderId': None,
 'info': {'orderId': '201025407428332391',
  'clientOrderId': '201025407428332391',
  'symbol': 'ETH_USDT',
  'side': 'buy',
  'orderMode': 'spot',
  'type': 'limit',
  'state': 'filled',
  'price': '1983.61',
  'priceAvg': '1983.61',
  'size': '0.00504',
  'filledSize': '0.00504',
  'notional': '9.99739440',
  'filledNotional': '9.99739440',
  'createTime': '1700160894040',
  'updateTime': '1700160908607'},
 'timestamp': 1700160894040,
 'datetime': '2023-11-16T18:54:54.040Z',
 'lastTradeTimestamp': None,
 'symbol': 'ETH/USDT',
 'type': 'limit',
 'timeInForce': None,
 'postOnly': None,
 'side': 'buy',
 'price': 1983.61,
 'stopPrice': None,
 'triggerPrice': None,
 'amount': 0.00504,
 'cost': 9.9973944,
 'average': 1983.61,
 'filled': 0.00504,
 'remaining': 0.0,
 'status': 'filled',
 'fee': None,
 'trades': [],
 'fees': [],
 'lastUpdateTimestamp': None,
 'reduceOnly': None,
 'takeProfitPrice': None,
 'stopLossPrice': None}

```

**Comment by Dan-krm** [comment]
@xmatthias Thanks for reporting, I opened a pull request to resolve this so the status will return `closed` once it's merged
