### ISSUE TITLE
Transfer from subacc to main on okex

### ISSUE THREAD

**Issue by WhereIsMyMindDL** [ccxt/ccxt#20028]
### Operating System

Linux

### Programming Languages

Python

### CCXT Version

4.1.56

### Description

hi can u help with transfer from subacc to main on okex pls, i try use 2 methods, and got the same error

### Code

#1 
```
exchange.private_post_asset_transfer({"ccy": symbolWithdraw, "amt": str(sub_balance), "from": '6', "to": '6', "type": "2", "subAcct": name_sub})
```
#2 
```
exchange.transfer(code=symbolWithdraw, amount=sub_balance, fromAccount=name_sub, toAccount='main', params={"type": "2", "from": '6', "to": '6'})  
```
#ERROR
```
ccxt.base.errors.ExchangeError: okx {"msg":"This API key doesn't have permission to use this function","code":"50120"}
```

**Comment by kroitor** [comment]
Have you have enabled the transfer permission on your API key in the okx website settings?

**Comment by WhereIsMyMindDL** [comment]
oh shit, sry, its work
