### ISSUE TITLE
Can't retrieve order history for spot margin orders: Bitget

### ISSUE THREAD

**Issue by Remo-W** [ccxt/ccxt#20041]
### Operating System

Ubuntu 22.04-3 LTS

### Programming Languages

Python

### CCXT Version

4.1.55

### Description

I can borrow, repay loans and place spot margin orders but cannot retrieve spot margin related info. I do not have this issue with spot orders - just spot margin orders. Using the REST API directly I have no trouble retrieving the spot margin order details - everything works as expected there. 

The sample below shows the problem I am encountering with ccxt's fetch_order - an empty structure is returned. Clearly I am missing something - maybe related to setting margin mode? Any assistance would be greatly appreciated.

### Code

```
import ccxt

BITGET_PUB_DEV = "xxxxxxxxxxxxxx"
BITGET_PRI_DEV = "yyyyyyyyyyyyyyyy"
BITGET_KEY_PWD = "zzzzzzzzzzzzzz"

# set exchange
s_exchange = ccxt.bitget({
    "enableRateLimit": True,
    "apiKey": BITGET_PUB_DEV,
    "secret": BITGET_PRI_DEV,
    "password": BITGET_KEY_PWD
})
s_exchange.load_markets()

borrow_result = s_exchange.borrow_margin(code="BTC", amount="0.0008", symbol="BTC/USDT",
                                         params={"marginMode": "isolated"})
print(borrow_result)

order_result = s_exchange.create_order(symbol="BTC/USDT", type="market", side="sell", amount=0.0008, price=0,
                                       params={"marginMode": "isolated",
                                               "loanType": "normal",
                                               "timeInForce": "GTC"})
print(order_result)

orderid = order_result["info"]["orderId"]
order_info = s_exchange.fetch_order(orderid, "BTC/USDT")
print(order_info)


CONSOLE OUTPUT SNIPPETS - first two lines are as expected, 3rd one shows the issue
==================================================================================

{'id': None, 'currency': 'BTC', 'amount': 0.0008, 'symbol': 'BTCUSDT'.........
{'info': {'orderId': '11111111111111', 'clientOid': '22222222222222'},..........
{'info': [], 'id': None, 'clientOrderId': None, 'timestamp': None,...........

  

```

**Comment by Dan-krm** [comment]
Hi @Remo-W margin orders aren't supported by fetchOrder on bitget because there is no API endpoint for it, you can use `fetchOpenOrders` and `fetchMyTrades` for margin orders on bitget:
```
order_info = exchange.fetch_open_orders("BTC/USDT", None, None, '{"marginMode":"isolated"}')
```
`fetchCanceledOrders` and `fetchClosedOrders` should be added as well once this v2 upgrade is complete: #19996

**Comment by Remo-W** [comment]
Thank-you @Dan-krm for the quick response. Much appreciated! Keep up the good work!!!!!
