### ISSUE TITLE
Access-Control-Allow-Origin  'no-cors' 

### ISSUE THREAD

**Issue by 2l1k** [ccxt/ccxt#2004]
Failed to load https://api.binance.com/api/v1/exchangeInfo: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://domain.com' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by kroitor** [comment]
```
mbp:ccxt igorkroitor$ node examples/js/cli binance has
{                 CORS:  false, // ←------------------------------------ no CORS for Binance
             publicAPI:  true,
            privateAPI:  true,
           cancelOrder:  true,
          cancelOrders:  false,
  createDepositAddress:  false,
           createOrder:  true,
               deposit:  false,
             editOrder: "emulated",
          fetchBalance:  true,
         fetchBidsAsks:  true,
     fetchClosedOrders:  true,
       fetchCurrencies:  false,
   fetchDepositAddress:  true,
      fetchFundingFees:  false,
      fetchL2OrderBook:  true,
          fetchMarkets:  true,
         fetchMyTrades:  true,
            fetchOHLCV:  true,
       fetchOpenOrders:  true,
            fetchOrder:  true,
        fetchOrderBook:  true,
       fetchOrderBooks:  false,
           fetchOrders:  true,
           fetchTicker:  true,
          fetchTickers:  true,
           fetchTrades:  true,
              withdraw:  true       }
mbp:ccxt igorkroitor$
```

Binance does not offer CORS.

https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin

Let us know if it doesn't help. Thx!

**Comment by 2l1k** [comment]
я создал файл cors.js и вписал в него "let port = (process.argv.length > 2) ? parseInt (process.argv[2]) : 8080; // default
require ('cors-anywhere').createServer ().listen (port, 'localhost')" 
запустил через "node cors.js", мне выдало ошибку:
module.js:557
    throw err;
    ^

Error: Cannot find module 'cors-anywhere'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/upump/public_html/wp-content/themes/theme-by-webbers/cors.js:2:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

**Comment by kroitor** [comment]
`npm install cors-anywhere` ? )

**Comment by kroitor** [comment]
https://docs.npmjs.com/cli/install

**Comment by 2l1k** [comment]
require is not defined

**Comment by kroitor** [comment]
@2l1k do you use it in a browser? If so, then `require` wont work, you need to check these examples: https://github.com/ccxt/ccxt/tree/master/examples/html

**Comment by 2l1k** [comment]
exchange.cancelOrder (id, symbol)
Uncaught (in promise) Object.assign: binance {"code":-2011,"msg":"UNKNOWN_ORDER"}

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/Manual#error-handling
