### ISSUE TITLE
ExchangeError: kucoin request timeout when editing order

### ISSUE THREAD

**Issue by iht76** [ccxt/ccxt#20079]
### Operating System

Win11

### Programming Languages

Js

### Description

When I try to modify limit order, I get this error :

ExchangeError: kucoin request timeout

I can send order, cancel, etc but editing fails for some reason.

### Code

```
const exchange = new ccxt.kucoin ({ enableRateLimit: true });
await exchange.create_order("BTC/USDT",'limit','buy', amount, "20000", {'timeInForce': 'GTC',"clientOrderId" : "B1"})
await exchange.editOrder(orderID, "BTC/USDT", 'limit', 'buy', amount, "10000")  
```

**Comment by carlosmiei** [comment]
Hello @iht76, actually I'm getting the exact same error. We will investigate it and revert asap.
