### ISSUE TITLE
CCXT open an margined position on OKEX 

### ISSUE THREAD

**Issue by lawrence910426** [ccxt/ccxt#20074]
### Operating System

Ubuntu 22.04

### Programming Languages

PHP

### CCXT Version

4.1.58 (Installed via PyPI)

### Description

According to [this example](https://github.com/ccxt/ccxt/blob/master/examples/py/async-okex-create-margin-order.py), running this would open a margin order. But turns out it only opens a normal order.

```python=
order = await exchange.create_order(symbol, type, side, amount, price, {
    'margin_trading': '2',
})
```

The source code provided [here (py)](https://github.com/ccxt/ccxt/blob/8403cb413249cefb55880edd8096aca38920fdfd/python/ccxt/async_support/okx.py#L2459) and [here(javascript)](https://github.com/ccxt/ccxt/blob/510d8d172d56c2d2f1f83cedfd04b2bb08ffaf19/js/src/okx.js#L2538) specifies that the example should be something like this

```python=
exchange.createOrder(
    symbol, 'limit', side, lot_size, price, {
        'margin': True,
        'marginMode': 'cross'
    }
)
```

It would be nice to check the examples and see if they works :D

Thank you all for your contributions. CCXT is great :)

### Code

```
  

```

**Comment by Dan-krm** [comment]
Hi @lawrence910426 thanks for reporting, I opened a pull request that will update CCXT's okx python examples
