### ISSUE TITLE
Use nano instead of xrb

### ISSUE THREAD

**Issue by anandanand84** [ccxt/ccxt#2007]
It was working fine on verion 1.10.482 but not in the latest. Here is the code.

```
var ccxt =require('ccxt');
var binance = new ccxt.binance();
await binance.loadMarkets();
binance.symbols.filter(market=>market === 'NANO/BTC') // returns []
binance.symbols.filter(market=>market === 'XRB/BTC') // returns [ 'XRB/BTC' ]
```

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/issues/1853

**Comment by rthomas6** [comment]
This is not at all clear to me. [CMC shows it as NANO](https://coinmarketcap.com/currencies/nano/#markets)?

**Comment by kroitor** [comment]
@rthomas6 yes, but it is outdated, throughout ccxt we use the newer name `XRB` everywhere, including CMC.

**Comment by rthomas6** [comment]
[NANO is the new name](https://hackernoon.com/nano-rebrand-announcement-9101528a7b76), and XRB is the old name. Nano used to be called Raiblocks with symbol XRB, and they rebranded to Nano, with symbol NANO.

It's not a big deal either way as long as it's consistent, just wanted you to have the info. 

Thanks for maintaining this awesome library.
