### ISSUE TITLE
Bitget Market limit amount filter max set to 0

### ISSUE THREAD

**Issue by fl0wo** [ccxt/ccxt#20097]
### Operating System

Linux Ubuntu 22LTS

### Programming Languages

JavaScript

### CCXT Version

4.1.56

### Description

Hi, when loading markets:
`bitgetExchange.loadMarkets();`

I noticed that the json produced has the "limits"."amount"."max" field set to 0.

E.g.:
`{"id":"BTCUSDT_SPBL","symbol":"BTC/USDT","base":"BTC","quote":"USDT","baseId":"BTC","quoteId":"USDT","type":"spot","spot":true,"taker":0.002,"maker":0.002,"precision":{"amount":0.0001,"price":0.01},"limits":{"leverage":{},"amount":{"min":0,"max":0},"price":{},` ......

As we can see "price" filters are just empty objects, while "amount" seems to have a correct "min" amount set, but not sure the "max" value is correct.

My current work-around for this is checking the filter max value for the amount is actually zero, I set it as undefined (it means there are no limitations on the amount value for this asset pair)

Please let me know if this is the correct behavior or if we should expect to have an undefined set (or not even see the property "max" at all).

### Code

```
  

```

**Comment by Dan-krm** [comment]
Hi @fl0wo thanks for pointing this out, It makes sense to set the max value to undefined if it's zero, I think this will be resolved once we complete our update to v2 for bitget #19996
```
bitget.fetchMarkets ()
...
          BTCUSDT |             BTC/USDT |           BTC |  USDT |           BTC |    USDT |   spot |  true | false |  false |  false |   true |    false |  0.002 |  0.002 |      {"amount":0.0001,"price":0.01} |    {"leverage":{},"amount":{"min":0,"max":10000000000},"price":{},"cost":{"min":5}} |        |          |        |         |              |               | 
```
