### ISSUE TITLE
Unified API convenience method proposal: fillOrder

### ISSUE THREAD

**Issue by Bomper** [ccxt/ccxt#2010]
When programming bots, it's necessary to check when the order that the bot placed, has filled. The usual pattern is `const id = await exchange.create[Market/Limit]BuyOrder()` followed by `order = fetchOrder(id)` then checking if `order.remaining` is 0.

I propose adding 'market' and 'limit' methods to simplify this process, as follows:

```js
exchange.fillMarketBuyOrder (symbol, amount[, params][, pollingInterval = 10][, progressCallback])
exchange.fillLimitBuyOrder (symbol, amount, price[, params][, pollingInterval = 10][, progressCallback])
```

The additional parameters are:
* `pollingInterval`, in seconds, defaulting to 10 seconds. In the future when we implement streams for exchanges supporting WebSocket order updates, we might want to tweak what a non-zero value would mean (perhaps "don't use streams, uses REST"?), or we can ignore the value if present
* `progressCallback(order)` - a function called with the current status of the order (e.g. partial fill) every `pollingInterval` seconds.

Looking forward to thoughts and guidelines on implementing this.

**Comment by mkutny** [comment]
I think that library might benefit from unified poller helper. I don't know what PHP and Pythons guys doing but in JS we (users) end up with `setTimeout` which is renewed after callback is complete. Not that it's hard to do but it's not just one line of code, it usually requires few tweaks before it gets stable, and everybody has to reimplement it in userland.

If we had it users would build any status checkers they like by themselves.

**Comment by mkutny** [comment]
Something like:
```
const poller = new Poller (pollFunc, callbackFunc, timeout)
poller.start()
poller.stop()
```

**Comment by kroitor** [comment]
For now I would focus on building from bottom up, namely, have a stable working thin low-level wrapper first, then build convenience higher-lever wrappers on top of stable basecode.

> @kroitor BTW, how do you solve this task in your projects? DIY or use an existing library?

Mostly DIY, we use a chain of checks and logical assertions, but I can't really disclose the details.

I would close this for now, if you don't mind. Hope to return to this issue later. Feel free to reopen it if needed or just ask questions, if any. Thx!
