### ISSUE TITLE
Websockets with Binance testnet

### ISSUE THREAD

**Issue by pbosch** [ccxt/ccxt#20127]
### Operating System

Windows with WSL2

### Programming Languages

Python

### CCXT Version

4.1.64

### Description

I'm trying to use the `watch_trades_for_symbols` API on Binance testnet and it doesn't appear to be working as expected. The following does not return any trade:

```
import ccxt.pro as ccxt

symbol = 'BTCUSDT' # or BTC/USDT:USDT

exchange = ccxt.binance({'options': {'defaultType': 'future', }})
exchange.set_sandbox_mode(True)

while True:
    trades = await exchange.watch_trades_for_symbols([symbol])
    print(trades)
```

while the following does:

```
import ccxt.pro as ccxt

symbol = 'BTCUSDT' # or BTC/USDT:USDT

exchange = ccxt.binanceusdm()
exchange.set_sandbox_mode(True)

while True:
    trades = await exchange.watch_trades_for_symbols([symbol])
    print(trades)
```

The strange thing is that the first one does return results in normal mode. Although, not sure if that one generally returns aggregated trades because IDs aren't the same as when using fetch_trades.

Watching positions like this does work but does not update new positions. It only reports once on the existing position but gets the right one.

```
import ccxt.pro as ccxt

symbol = 'BTCUSDT' # or BTC/USDT:USDT

exchange = ccxt.binance({'options': {'defaultType': 'future', }})
exchange.set_sandbox_mode(True)

while True:
    positions = await exchange.watch_positions([symbol])
    print(positions)
```

`watch_position_for_symbols` does not work and throws a `watch_positions` wasn't awaited error, though.

`watch_order_book_for_symbols` does work as well and for `watch_ohlcv_for_symbols` I'm not sure as I might have used wrong input. 

Is this expected?

### Code

```
  

```

**Comment by pcriadoperez** [comment]
Hi @pbosch ,

Thanks for reporting, I opened a PR #20136 to fix the `watch_position_for_symbols` error.

For `watchTradesForSymbols` I opened PR #20137 to fix the issue

With respect to receiving new updates when calling watchPositions, do you receive an update if you modify your position?

**Comment by pbosch** [comment]
Hi @pcriadoperez @carlosmiei 

I still encounter these issues in 4.1.67. As well as `watch_positions` only giving a result once and `watch_orders_for_symbols` not being implemented.
