### ISSUE TITLE
Exception in querying and returning empty purchase and sale orders

### ISSUE THREAD

**Issue by iockx** [ccxt/ccxt#20121]
### Operating System

Windows11

### Programming Languages

Python

### CCXT Version

3.0.1

### Description

Everything was normal last night. When running again today, the Huobi interface prompts that the data is empty and abnormal. This is the first time I have encountered this problem. Replacing other exchanges will return to normal

Thank you for your answer

Error prompt：

```py
  File "D:\software\Python38\lib\site-packages\ccxt\huobi.py", line 2033, in fetch_order_book
    self.load_markets()
  File "D:\software\Python38\lib\site-packages\ccxt\base\exchange.py", line 1391, in load_markets
    markets = self.fetch_markets(params)
  File "D:\software\Python38\lib\site-packages\ccxt\huobi.py", line 1433, in fetch_markets
    promises.append(self.fetch_markets_by_type_and_sub_type(type, subType, params))
  File "D:\software\Python38\lib\site-packages\ccxt\huobi.py", line 1568, in fetch_markets_by_type_and_sub_type
    raise NetworkError(self.id + ' fetchMarkets() returned an empty response: ' + self.json(markets))
ccxt.base.errors.NetworkError: huobi fetchMarkets() returned an empty response: []
```

### Code

```
ht_exchange.fetch_order_book('SATS/USDT')
```

**Comment by iockx** [comment]
It has been restored. It may be a problem with the Huobi service. Thank you

**Comment by carlosmiei** [comment]
@iockx I'm glad it is working now, maybe it was a temporary issue. Btw we noticed that you have an outdated version of ccxt, we would suggest updating it to get all the new fixes implementations and improvements. 

Since the original issue is resolved, I will close this issue feel free to re-open it if anything!

Thank you
