### ISSUE TITLE
Error when cancel_orders on bitget

### ISSUE THREAD

**Issue by YVINEE** [ccxt/ccxt#20122]
### Operating System

ubuntu

### Programming Languages

Python

### CCXT Version

4.1.64

### Description

crash when canceling several orders using cancel_orders on bitget spot

### Code

```
  bitget.py

Error when cancel_orders on bitget spot

def cancel_orders(self, ids, symbol: Str = None, params={}):

replace
	request['symbol'] = market['info']['symbolName']  # regular id like LTCUSDT_SPBL does not work here
by
	request['symbol'] = (market['info']['symbolName']) if (marginMode is not None) else (market['id'])

```

**Comment by Dan-krm** [comment]
Hi @YVINEE thanks for reporting, we are currently updating Bitget to their v2 API and the pull request is almost completed and ready for review. I tested `cancel_orders` with the new version and it should work properly for you once the v2 update is merged
