### ISSUE TITLE
okx (spot) method fetch_balance does not return balances

### ISSUE THREAD

**Issue by bgmt** [ccxt/ccxt#20125]
### Operating System

centos7

### Programming Languages

PHP

### CCXT Version

4.1.64

### Description

Greetings to all, on the okx exchange, the fetch_balance method does not return balances
I pass the following parameters
![image](https://github.com/ccxt/ccxt/assets/5442931/2ddc0da6-44c3-426c-b118-65687cc851cf)

I receive an answer, although there are funds in my wallet
![image](https://github.com/ccxt/ccxt/assets/5442931/2d5fbde9-59dd-4355-94e6-c13664c29d75)

What could be the problem, where to dig?

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @bgmt, by default `fetch_balance` returns the spot balance, can you check if your funds are in the "funding" wallet

Example:
```PHP
$funding_wallet = $okx->fetch_balance(array(
        'type' => 'funding'
    ));
```

**Comment by bgmt** [comment]
> Hello @bgmt, by default `fetch_balance` returns the spot balance, can you check if your funds are in the "funding" wallet
> 
> Example:
> 
> ```
> $funding_wallet = $okx->fetch_balance(array(
>         'type' => 'funding'
>     ));
> ```

thank you very much, that's it

**Comment by carlosmiei** [comment]
@bgmt You're welcome.

Since the original question is resolved I'm closing the issue but feel free to re-open it if anything!
