### ISSUE TITLE
 Issue with underscore_notation instead of camelCase

### ISSUE THREAD

**Issue by legitalk** [ccxt/ccxt#20147]
### Operating System

Ubuntu 22

### Programming Languages

PHP 8.1

### CCXT Version

not working since 4.1.66 -> 4.1.75

### Description

Since this version `fetch_balance` and `fetch_markets` stopped working on Coinbase.

It was working fine yesterday on version 4.1.65.

The error is:
_ccxt\ExchangeError
extend method not found, try underscore_notation instead of camelCase for the method being called_

### Code

```
  $balance = self::$exchange->fetch_balance(['v3' => true]);
  $crypto_pairs = self::$exchange->load_markets();
```

**Comment by sc0Vu** [comment]
Hi @legitalk,

It works for me, can you paste verbose log? BTW, we already load_markets in fetch_balance, you can get pairs with `$exchange->markets`.

**Comment by legitalk** [comment]
@sc0Vu still not working in newest version - 4.1.75. I know, you have already markets there, I am just saying after exchange initialization when I can one of the above methods (fetch_balance or load_markets), it is always throwing an error:

_ccxt\ExchangeError
extend method not found, try underscore_notation instead of camelCase for the method being called_

I set up `verbose = true`, how I can send you the logs?

**Comment by legitalk** [comment]
@sc0Vu the PR was closed, so did it not solve the issue?

**Comment by carlosmiei** [comment]
@legitalk We merged a different that fixe the issue, it should be available soon.

**Comment by legitalk** [comment]
@carlosmiei thank you very much

**Comment by legitalk** [comment]
@carlosmiei thank you very much
