### ISSUE TITLE
CCXT Charts

### ISSUE THREAD

**Issue by triosphere** [ccxt/ccxt#2016]
- OS:  Debian 9
- Programming Language version:  Python 2.7.13
- CCXT version:  1.10.1178
- Exchange:  n/a
- Method:  

I realize this question isn't code-specific, so feel free to delete it if this not the proper place for it.  Basically I have ccxt scripts working, specifically candlestick chart data code outputting on my console.  Can someone point me to documentation on how to turn this data into an actual graphic candlestick chart?  I did not find anything in the ccxt docs that addressed this, so I expect it's outside the scope of ccxt and more about graphics software.  Any help is appreciated.

**Comment by kroitor** [comment]
@triosphere have you seen the *See also* section in the examples? ) 

https://github.com/ccxt/ccxt/tree/master/examples#see-also

There's more than several hundreds of examples there, including various charting apps and articles ;) Let me know if it does not help  )
