### ISSUE TITLE
Add `account` to gate private api

### ISSUE THREAD

**Issue by WillPCowan** [ccxt/ccxt#20196]
### Operating System

MacOS

### Programming Languages

Python

### CCXT Version

4.1.73

### Description

For `gate`, `account` needs to be added to the `describe` object.

### Code

```
    def describe(self):
        return self.deep_extend(super(GateExchangeAccountClient, self).describe(), {
            'urls': {
                'api': {
                    'private': {
                        'account': 'https://api.gateio.ws/api/v4',
                    },
                },
            },
        })
```

**Comment by carlosmiei** [comment]
Hello @WillPCowan, you're right thanks for reporting it. We will add it asap.
