### ISSUE TITLE
Binance: createMarketBuyOrder does not return price

### ISSUE THREAD

**Issue by alt3rmann** [ccxt/ccxt#2019]
I completed the buy by createMarketBuyOrder.
I want to know at what price I made a purchase, but createMarketBuyOrder does not return price I bought.
I tried to use fetchOrder, fetchOrders, fetchClosedOrders, but it's does not return price.

For example:

```
{  
   "info":{  
      "symbol":"TNTBTC",
      "orderId":1111111,
      "price":"0.00000000",
      "origQty":"147.00000000",
      "executedQty":"147.00000000",
      "status":"FILLED",
      "timeInForce":"GTC",
      "type":"MARKET",
      "side":"BUY",
      "stopPrice":"0.00000000",
      "icebergQty":"0.00000000",
      "time":1519333749004,
      "isWorking":true
   },
   "id":"1111111",
   "timestamp":1519333749004,
   "datetime":"2018-02-22T21:09:09.004Z",
   "symbol":"TNT/BTC",
   "type":"market",
   "side":"buy",
   "price":0,
   "amount":147,
   "cost":0,
   "filled":147,
   "remaining":0,
   "status":"closed"
}
```

**Comment by kroitor** [comment]
@alt3rmann 

> I tried to use fetchOrder, fetchOrders, fetchClosedOrders

But you haven't tried fetchMyTrades after a market order? )

https://github.com/ccxt/ccxt/wiki/Manual#personal-trades

Let us know if this does not help )
