### ISSUE TITLE
conflicting name gate and gateio

### ISSUE THREAD

**Issue by SnoozeFreddo** [ccxt/ccxt#20204]
### Operating System

-

### Programming Languages

Python

### CCXT Version

1.68.3

### Description

What is the difference between getattr(cctx, 'gate') and getattr(cctx, 'gateio') ?

### Code

```
  

```

**Comment by pcriadoperez** [comment]
There is no difference, gateio is an alias for gate, so you can use them interchangably.

I'll close this issue for now but feel free to reach out with any questions
