### ISSUE TITLE
bingx: calculate_fee returning None

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#20214]
### Operating System

linux

### Programming Languages

Python

### CCXT Version

4.1.75

### Description

calling "calculate_fee" on bingx does not yield any rate, but returns "None" (or undefined on js) instead.

I'd expect to have ccxt return the default fee for bingx (basically the lowest tier available) - as it also does for other exchanges.

### Code

``` python
import ccxt
exchange = ccxt.bingx()
lm = exchange.load_markets()
print(exchange.calculate_fee('BTC/USDT', 'limit', 'buy', 0.1, 1))


{'type': 'taker', 'currency': 'USDT', 'rate': None, 'cost': None}    # this should not be None

```

**Comment by carlosmiei** [comment]
Hello @xmatthias, thanks for reporting it we will take a look.
