### ISSUE TITLE
Bitstamp fetch_ohlcv wrong end time calculation when end_time is not specified

### ISSUE THREAD

**Issue by noel45** [ccxt/ccxt#20222]
### **Operating System**
Windows

### **Programming Languages**
Python

### **CCXT Version**
4.1.75

### **Description**

The CCXT function fetch_ohlcv for exchange bitstamp always default a limit and an end timestamp.
On Bitstamp, when you precise both the start time, end time and the limit, the end time is considered to be the start time of the last candle. 
Example : For start=10, end=20, limit=10, it will send back candles 11 to 20, not 10 to 19.
Real example: 
https://www.bitstamp.net/api/v2/ohlc/1incheur/?step=60&start=1673131800&end=1673191800&limit=1000

### **Code**

`bybit.fetch_ohlcv('1INCH/EUR', '1m', 1673131800000, params={'partial': False})`

This will retrieve 1000 candlesticks from 1673131**86**0000 , not 1673131**80**0000 as specified in parameters.

To avoid this, the end_timestamp should be calculated with (limit - 1) in:

![image](https://github.com/ccxt/ccxt/assets/15633913/f58758ee-7564-4a87-962e-26f91b6fdf9f)

### Code

```
  

```

**Comment by Dan-krm** [comment]
Hi @noel45 thanks for the information, I opened a pull request that will resolve the issue
