### ISSUE TITLE
Bit-Z unhashable type: 'dict'

### ISSUE THREAD

**Issue by pedrito87** [ccxt/ccxt#2022]
- OS: Windows 10
- Programming Language version: Python 3.6.4
- CCXT version: 1.10.1133
- Exchange: Bit-Z
- Method: create_limit_sell_order

Hi,
I am using ccxt for some time and it works great on most exchanges. Incredible work!
However today I tried out Bit-Z exchange and I am running into an error. I tried to figure it out myself but gave up. So consider such a simple code:

```Python
import ccxt
bitz = ccxt.bitz({
    'verbose': True,
    'apiKey': 'myapi',
    'secret': 'mysecret',
    'password': 'mypass',
})
markets = bitz.load_markets()
order = bitz.create_limit_sell_order('BCH/BTC', 0.005, 0.125,)
```
And it produces:

```
POST https://www.bit-z.com/api_v1/tradeAdd 
Request: {'Content-type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} 
 api_key=myapi&coin=bch_btc&nonce=208678&number=0.005&price=0.12500000&timestamp=1519335208&tradepwd=mypass&type=sell&sign=mysecret
POST https://www.bit-z.com/api_v1/tradeAdd 200 
Response: {'Date': 'Thu, 22 Feb 2018 21:33:29 GMT', 'Content-Type': 'application/json;charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d9dd45a77ed4660c9ba026f309cbb05ea1519335209; expires=Fri, 22-Feb-19 21:33:29 GMT; path=/; domain=.bit-z.com; HttpOnly', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '3f1510612a566b07-WAW', 'Content-Encoding': 'gzip'} 
 
{"code":0,"msg":"Success","data":{"id":"132694287"}}
Traceback (most recent call last):
  File "C:/Users/piotr/Desktop/bitztest.py", line 10, in <module>
    order = bitz.create_limit_sell_order('BCH/BTC', 0.005, 0.125)
  File "C:\Python\ccxt\base\exchange.py", line 1097, in create_limit_sell_order
    return self.create_order(symbol, 'limit', 'sell', *args)
  File "C:\Python\ccxt\bitz.py", line 290, in create_order
    self.orders[id] = self.parse_order(order, market)
TypeError: unhashable type: 'dict'
```

It does create and order on the exchange but it immediately crashes afterwards. Is there anything I can do to make it work? I woulf be grateful for any help :)

**Comment by pedrito87** [comment]
Thank you very much for a very fast and accurate answer! 👍 
So in Python code looks like this:

>     def create_order(self, symbol, type, side, amount, price=None, params={}):
        self.load_markets()
        market = self.market(symbol)
        request = {
            'coin': market['id'],
            'type': side,
            'price': self.price_to_precision(symbol, price),
            'number': self.amount_to_string(symbol, amount),
            'tradepwd': self.password,
        }
        response = self.privatePostTradeAdd(self.extend (request, params))
        order = self.parse_order({
            'id': id,
            'price': price,
            'number': amount,
            'type': side,
        }, market)
        self.orders[id] = order
        return order

However, if you create a trade using this script it is impossible to get the order id from the create_order function as you get:

> 'id': <built-in function id>

So I guees it is better if you change the order to:

>         order = self.parse_order({
            'id': response['data'],
            'price': price,
            'number': amount,
            'type': side,
        }, market)

This way you can get access to the id from the create_order function. Thanks again for your help and keep up the good work! :)

**Comment by kroitor** [comment]
@pedrito87 you just need to update ccxt to 1.10.1185 )

https://github.com/ccxt/ccxt/blob/master/python/ccxt/bitz.py#L275

**Comment by suril10** [comment]
I know this thread is closed but I am getting the same error but with exchange.withdraw() function for withdrawing litecoin from livecoin to bitstamp.

**Comment by kroitor** [comment]
@suril10 follow these guides:

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by suril10** [comment]
I know this thread is closed but I am getting the same error but with exchange.withdraw() function for withdrawing litecoin from livecoin to bitstamp.
