### ISSUE TITLE
ERR_INVALID_ARG_TYPE | The "listener" argument must be of type function. Received an instance of Object

### ISSUE THREAD

**Issue by fl0wo** [ccxt/ccxt#20227]
### Operating System

Linux 22.04LTS

### Programming Languages

JavaScript

### CCXT Version

4.1.66+ 

### Description

Starting from version 4.1.66 (included) there's this runtime error when running:

client.loadMarkets(); 

Of any exchange (binance for example) for SPOT markets.

Could not figure out what's happening, but I know it's not persisting on v4.1.65.

Had to revert to 4.1.65 version to have things working.

May has to deal with my tsconfig.json?

I'll paste it anyways.

### Code

```
  {
  "compilerOptions": {
    "rootDir": "src",
    "outDir": "lib",
    "alwaysStrict": true,
    "declaration": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "lib": [
      "es2019"
    ],
    "module": "CommonJS",
    "noEmitOnError": false,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "resolveJsonModule": true,
    "strict": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "stripInternal": true,
    "target": "ES2019"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "cdk.out"
  ]
}


```

**Comment by sc0Vu** [comment]
Hi @fl0wo 

The tsconfig looks fine...... Can you paste code?

BTW, there are bundled common js files in dist directory (`ccxt.cjs` and `ccxt.bundle.cjs`). You can also import that file directly.

**Comment by bharath-rl** [comment]
same error for me

```
const kucoin = new ccxt.kucoin({
  apiKey: "<api-key>",
  secret: "<secret>",
  password: '<password>',
  verbose: true
  });

kucoin.fetchAccounts() 
kucoin.fetchBalance()
```

calling any method throws **TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object**

**Comment by eckozen84** [comment]
Just confirming with others that I see the same error. Rolling back to v4.1.65 fixes it.

**Comment by bolabola** [comment]
same error

**Comment by fl0wo** [comment]
Do you have any idea what we could do to overcome it?

I'll have to do extra work later if another bug gets fixed on the latest version, at least we should understand why that is happening (?)

**Comment by roshsingh** [comment]
Having the same issue. Reverting to 4.1.65 does not help.

**Comment by roshsingh** [comment]
Using the fetchImplementation override approach here worked for me: https://github.com/ccxt/ccxt/issues/2480#issuecomment-379309437

I had to use commonjs version of fetch from https://www.npmjs.com/package/node-fetch-commonjs

strangely:

import fetch from 'node-fetch' works, 
but not 
import fetch from 'node-fetch-commonjs'

wondering if it's picking up node-fetch from another package

**Comment by fistofzen** [comment]
I have the same error. any help ?

**Comment by carlosmiei** [comment]
Hello @roshsingh @fistofzen, do you think it's possible to post a MRE project, that we can run locally to try to debug this issue?

**Comment by fistofzen** [comment]
@carlosmiei How can we post MRE ?

**Comment by carlosmiei** [comment]
@fistofzen A simple folder with the project and all the configs, we don't need to see your entire project just an index file importing ccxt would be enough

**Comment by fistofzen** [comment]
require('dotenv').config({ path: "./.env" });
const ccxt = require('ccxt');
const fs = require('fs');
 
const cron = require("node-cron");
var logger = fs.createWriteStream('3 - Log ADX SELL ' + process.argv[2] + '.txt', {
    flags: 'a'
})
 
const tick = async (exchange, myOpenPositions) => {
    myOpenPositions.forEach(async position => {
        //entered amount : 100
        let operation = "sell";
        if (position.info.positionAmt < 0) { //this is sell
            operation = "buy";
        }
        const profitAmount = (position.initialMargin * 0.06);  //10
        const stopAmount = (position.initialMargin * 0.4);    //40
        try {
            //take profit 
            if (position.unrealizedPnl > profitAmount) {
                const params = {
                    'reduce_only': true,
                }
                const closePositionOrder = await exchange.createOrder(position.info.symbol, 'market', operation, position.contracts, undefined, params);
            } else
                //stop loss
                if (position.unrealizedPnl < -1 * stopAmount) {
                    const params = {
                        'reduce_only': true,
                    }
                    const closePositionOrder = await exchange.createOrder(position.info.symbol, 'market', operation, position.contracts, undefined, params);

                } else {
                    console.log("Profit amount " + profitAmount + " Loss amount " + stopAmount + " Current profit " + position.unrealizedPnl);
                }
        } catch (error) {
            console.log(error);
        }
    })
}

const run = async () => {
    try {
        const binanceClient = new ccxt.binanceusdm({
            enableRateLimit: true,
            apiKey: process.env.API_KEY,
            secret: process.env.API_SECRET,
            hedgeMode: true,
            options: {
                defaultType: 'future',
            },
            
        });
        binanceClient.setSandboxMode(false);
        const myAccount = await binanceClient.fetchPositions();
        let myOpenPositions = myAccount.filter(position => position.contracts > 0)
        await tick(binanceClient, myOpenPositions);
    } catch (error) {
        console.log(error);
    }
}

async function main() {
    cron.schedule('*/3 * * * * *', async () => { // Every minute offset 30 seconds
        console.log("--------------------------------------------------");
        console.log('BOT Task - READ - Time: ' + (new Date()));
        console.log("--------------------------------------------------");
        logger.write("--------------------------------------------------\n");;
        logger.write("STARTED " + (new Date()) + "\n");
        logger.write("--------------------------------------------------\n");;
        try {
            await run();
        } catch (error) {
            console.log(error);
        }
    });
}


main();

**Comment by fistofzen** [comment]
`require('dotenv').config({ path: "./.env" });
const ccxt = require('ccxt');
const fs = require('fs');
 
const cron = require("node-cron");
var logger = fs.createWriteStream('3 - Log ADX SELL ' + process.argv[2] + '.txt', {
    flags: 'a'
})
 
const tick = async (exchange, myOpenPositions) => {
    myOpenPositions.forEach(async position => {
        //entered amount : 100
        let operation = "sell";
        if (position.info.positionAmt < 0) { //this is sell
            operation = "buy";
        }
        const profitAmount = (position.initialMargin * 0.06);  //10
        const stopAmount = (position.initialMargin * 0.4);    //40
        try {
            //take profit 
            if (position.unrealizedPnl > profitAmount) {
                const params = {
                    'reduce_only': true,
                }
                const closePositionOrder = await exchange.createOrder(position.info.symbol, 'market', operation, position.contracts, undefined, params);
            } else
                //stop loss
                if (position.unrealizedPnl < -1 * stopAmount) {
                    const params = {
                        'reduce_only': true,
                    }
                    const closePositionOrder = await exchange.createOrder(position.info.symbol, 'market', operation, position.contracts, undefined, params);

                } else {
                    console.log("Profit amount " + profitAmount + " Loss amount " + stopAmount + " Current profit " + position.unrealizedPnl);
                }
        } catch (error) {
            console.log(error);
        }
    })
}

const run = async () => {
    try {
        const binanceClient = new ccxt.binanceusdm({
            enableRateLimit: true,
            apiKey: process.env.API_KEY,
            secret: process.env.API_SECRET,
            hedgeMode: true,
            options: {
                defaultType: 'future',
            },
            
        });
        binanceClient.setSandboxMode(false);
        const myAccount = await binanceClient.fetchPositions();
        let myOpenPositions = myAccount.filter(position => position.contracts > 0)
        await tick(binanceClient, myOpenPositions);
    } catch (error) {
        console.log(error);
    }
}

async function main() {
    cron.schedule('*/3 * * * * *', async () => { // Every minute offset 30 seconds
        console.log("--------------------------------------------------");
        console.log('BOT Task - READ - Time: ' + (new Date()));
        console.log("--------------------------------------------------");
        logger.write("--------------------------------------------------\n");;
        logger.write("STARTED " + (new Date()) + "\n");
        logger.write("--------------------------------------------------\n");;
        try {
            await run();
        } catch (error) {
            console.log(error);
        }
    });
}


main();`

**Comment by carlosmiei** [comment]
@fistofzen Can you please post a folder with all the necessary files? like package.json/tsconfig/etc

**Comment by fistofzen** [comment]
[untitled folder.zip](https://github.com/ccxt/ccxt/files/13988333/untitled.folder.zip)
@carlosmiei

**Comment by fistofzen** [comment]
Hello @carlosmiei 
I found the issue, it is conflict of different node modules. In my case it is caused by       "node-binance-api": "^0.13.1"

Regards.

**Comment by fistofzen** [comment]
Thank you very much for your helps @carlosmiei

**Comment by carlosmiei** [comment]
@fistofzen No problem, let us know if anything.


@roshsingh @bharath-rl @fl0wo @eckozen84 If you're still facing this issue, do you think that you can share a self-contained project that we can easily run locally?

**Comment by bharath-rl** [comment]
just removed **node-binance-api** package , now its working fine

**Comment by roshsingh** [comment]
@carlosmiei this is all u need. make sure to install node-fetch `node-fetch-commonjs`

```
import ccxt from 'ccxt';
import fetch from 'node-fetch';


const ExchangeClass = ccxt['binance'];
return new ExchangeClass({
  fetchImplementation: fetch,
});

```

**Comment by carlosmiei** [comment]
> @carlosmiei this is all u need. make sure to install node-fetch `node-fetch-commonjs`
> 
> ```
> import ccxt from 'ccxt';
> import fetch from 'node-fetch';
> 
> 
> const ExchangeClass = ccxt['binance'];
> return new ExchangeClass({
>   fetchImplementation: fetch,
> });
> ```

@roshsingh Might I ask why would you need to override the fetchImplementation?

**Comment by roshsingh** [comment]
@carlosmiei - the embedded fetch package doesn't seem compatible with ES6 compatible. I traced the error in the title of this issue to the embedded package.

**Comment by carlosmiei** [comment]
@roshsingh 
>  the embedded fetch package doesn't seem compatible with ES6 compatible.
how did you reach that conclusion? Would like to reproduce it locally

**Comment by roshsingh** [comment]
@carlosmiei - try it with node:16.9.1, ccxt 4.0.3, and possibly with node-binance-api package also installed as someone above mentioned. You should be able to reproduce the error.

**Comment by ttodua** [comment]
> ed. make sure to install node-fetc

it is mandatory to have old nodejs version, which is no longer maintained https://nodejs.org/en/about/previous-releases
does issue happen if you use latest LTS (supported) node version, and also latest CCXT version?

**Comment by YounGio9** [comment]
> Hello @carlosmiei I found the issue, it is conflict of different node modules. In my case it is caused by "node-binance-api": "^0.13.1"
> 
> Regards.

I also remove "node-binance-api": "^0.13.1" and it is working now

**Comment by ko0f** [comment]
Same here. Since 4.1.66 it's not been able to loadMarkets from any exchange.

There seem to have been a big change to Exchange.ts in caf928d74519e6bf64921c2b1ca113c5b1e6ee66

**Comment by fl0wo** [comment]
@ko0f I've personally updated to Node20 and I got the error vanish

**Comment by fl4p** [comment]
`node-binance-api` depends on `socks-proxy-agent`, I had `socks-proxy-agent@4.0.2` installed.

 Upgrading to `socks-proxy-agent@8` fixed this without removing the binance api
