### ISSUE TITLE
EASY FIX: "ERR_MODULE_NOT_FOUND"

### ISSUE THREAD

**Issue by kingkong404** [ccxt/ccxt#20225]
### Operating System

OSX

### CCXT Version

4.1.75

### Description

I am trying to run CCXT through Deno and am getting an error 

`TypeError: Could not resolve 'debug' from 'file:///Users/xxx/Library/Caches/deno/npm/registry.npmjs.org/ccxt/4.1.75/js/src/static_dependencies/proxies/http-proxy-agent/index.js'`

Looking through the npm package it seems CCXT depends on the `debug` package but has not been listed that as a dependency inside the package.json.

This likely only works by accident in node because another dependency might put debug into node_modules which CCXT relies on.

Could you please add debug as a depnedancy in the package.json

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @kingkong404  we will remove `debug` because it is not needed, thanks for reporting it.
