### ISSUE TITLE
more timeframes on gate.io like 2h, 3h

### ISSUE THREAD

**Issue by Deech123** [ccxt/ccxt#20224]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

Hi Guys, on Gate.io it's possible to see 2h and 3h data, what I already use on other platforms. But I have noticed this is not added in the gate.py. Since I want use this data on Freqtrade, and it's not available for download, is it possible to have this update?

### Describe the solution you'd like

adding 2 extra lines in timeframes :
`            'timeframes': {
                '10s': '10s',
                '1m': '1m',
                '5m': '5m',
                '15m': '15m',
                '30m': '30m',
                '1h': '1h',
                '2h': '2h',
                '3h': '3h',
                '4h': '4h',
                '8h': '8h',
                '1d': '1d',
                '7d': '7d',
                '1w': '7d',
            },
`

**Comment by carlosmiei** [comment]
Hello @Deech123,
Thanks for reporting it I will add 2h, but are you sure that gate supports the 3h timeframe? When I try to use it I get this error:

```
BadRequest gate {"label":"INVALID_PARAM_VALUE","message":"Invalid request parameter `interval` value: 3h"}
```
or

**Comment by Deech123** [comment]
I'm sorry, you are 100% right, 3h is not supported.. 2h it is. maybe stupid question, do I need to update something to make it work to get my 2h data?

**Comment by Deech123** [comment]
I tried it, but no luck : 2023-12-04 19:06:19,802 - freqtrade - ERROR - Invalid timeframe '2h'. This exchange supports: ['10s', '1m', '5m', '15m', '30m', '1h', '4h', '8h', '1d', '7d', '1w']

**Comment by carlosmiei** [comment]
@Deech123 Oh sorry forgot you're using it through freqTrade, in that case I think you have to wait a bit for the next release (it should be out in a few hours)
