### ISSUE TITLE
Phemex hedge mode wont let me place a market order

### ISSUE THREAD

**Issue by ClamaBsc** [ccxt/ccxt#20243]
### Operating System

Windows 11

### Programming Languages

Python

### CCXT Version

4.1.75

### Description

Everytime i run the the code i get this error 

**Error placing order: phemex {"code":20004,"msg":"TE_ERR_INCONSISTENT_POS_MODE","data":null}**

### Code

```
exchange = ccxt.phemex({
    'apiKey': api_key,
    'secret': api_secret,
    'enableRateLimit': True,
})

symbol1 = 'BTCUSDT'
exchange.set_position_mode(True, symbol1) # set pos mode to hedge
order = exchange.create_order(symbol1,'market','sell',0.001)





```

**Comment by carlosmiei** [comment]
Hello @ClamaBsc, Phemex requires an explicit `posSIde` parameter to be provided when in hedged mode, so you should do something like this:

```Python
order = exchange.create_order(symbol1,'market','sell',0.001, params = {'posSide': 'Short'}) # or Long
```

**Comment by ClamaBsc** [comment]
@carlosmiei Thank you so much, It works now

I have two more questions.
Is it possible to put SL and TP along with market order ? 
if its not possible then how do i do it after placing order. 

also how to set margin mode to cross i think its different in phemex than other, 

thanks ,

**Comment by ClamaBsc** [comment]
thanks carlosmiei, you the man
