### ISSUE TITLE
TypeError: ccxt.pro[exchangeId] is not a constructor

### ISSUE THREAD

**Issue by suenot** [ccxt/ccxt#20242]
### Operating System

macOs 14.1.1 (23B81)

### Programming Languages

JavaScript

### CCXT Version

4.1.76

### Description

I updated to the latest version of ccxt and my code broke.

error:
```
    parseOrderBooks parseOrderBooksOneExchange {
  exchangeId: 'kucoin',
  pairIds: [ 'ETH/BTC', 'LTC/BTC', 'BTC/USDT', 'ETH/USDT', 'DOGE/USDT' ]
} +1ms
  parseOrderBooks { pairIdsEmpty: false } +0ms
file:///Users/suenot/work_dev/intuition7_js/src/parseOrderBooks.js:22
  const exchangeInstance = new ccxt.pro[exchangeId]({});
                           ^

TypeError: ccxt.pro[exchangeId] is not a constructor
    at parseOrderBooksOneExchange (file:///Users/suenot/work_dev/intuition7_js/src/parseOrderBooks.js:22:28)
    at parseOrderBooks (file:///Users/suenot/work_dev/intuition7_js/src/parseOrderBooks.js:13:5)
    at main (file:///Users/suenot/work_dev/intuition7_js/src/index.js:6:3)
    at file:///Users/suenot/work_dev/intuition7_js/src/index.js:10:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

### Code

I created js sandbox with this problem: https://github.com/suenot/intuition7_js/blob/master/src/parseOrderBooks.js

code with error: 
```
import _ from "lodash";
import ccxt from "ccxt";
import { sleep } from "./sleep.js";
import debug from "debug";
// import { store } from "./db/store/store";
const log = debug("parseOrderBooks");

export const parseOrderBooks = async ({exchangeIds, pairIds}) => {
  log('parseOrderBooks', {exchangeIds, pairIds});
  log('For each exchange we have a separate ws connection with all pairs')
  for (const exchangeId of exchangeIds) {
    log({exchangeId});
    parseOrderBooksOneExchange({exchangeId, pairIds});
    // sleep(5000);
  }
}

export const parseOrderBooksOneExchange = async ({exchangeId, pairIds}) => {
  log('parseOrderBooksOneExchange', {exchangeId, pairIds});
  const pairIdsEmpty = _.isEmpty(pairIds);
  log({pairIdsEmpty});
  const exchangeInstance = new ccxt.pro[exchangeId]({});
  if (exchangeId in ccxt) {
    while (true) {
      if (pairIdsEmpty) {
        console.log('sleep 5s');
        await sleep(5000);
      } else {
        try {
          const orderBookCcxt = await exchangeInstance.watchOrderBookForSymbols(pairIds);
          // const orderBook = orderBookCcxtToCore({orderBookCcxt, exchangeId});
          log({orderBookCcxt});
          // upsertOrderBook(orderBook);
        } catch (e) { log(e) };
      }
    }
  }
}
```

**Comment by carlosmiei** [comment]
Hello @suenot, What's your node version? 

As a workaround, can you try to import it like this?

```Javascript
import { pro } from '../../js/ccxt.js';
const exch = new pro.binance ({});
```

**Comment by suenot** [comment]
in "ccxt": "4.1.19" code works good, problem in ccxt version 4.1.76

**Comment by suenot** [comment]
> Hello @suenot, What's your node version?
> 
> As a workaround, can you try to import it like this?
> 
> ```js
> import { pro } from '../../js/ccxt.js';
> const exch = new pro.binance ({});
> ```

node -v
v18.18.2
npm -v
10.2.4

**Comment by carlosmiei** [comment]
@suenot Hum I can't reproduce the issue, do you have any special config in package.json?
![image](https://github.com/ccxt/ccxt/assets/43336371/dfee9474-5b89-4f04-a54c-769bb0662644)

**Comment by suenot** [comment]
> @suenot Hum I can't reproduce the issue, do you have any special config in package.json? ![image](https://private-user-images.githubusercontent.com/43336371/288039784-dfee9474-5b89-4f04-a54c-769bb0662644.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODAwNjEsIm5iZiI6MTcwMTc3OTc2MSwicGF0aCI6Ii80MzMzNjM3MS8yODgwMzk3ODQtZGZlZTk0NzQtNWI4OS00ZjA0LWE1NGMtNzY5YmIwNjYyNjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDEyMzYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNzU1M2QxYzQzYzUzNTMwZGM3MTQ5YTg2N2EyMWY5ZjhkZTRiMGFlOGM4ZTBlYmMzY2I4NmE1Y2E0MWM0NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3cAdmoYg5hv_hzX3sEREtsLiTQpuQ72I6uWjZgCpzZQ)

What version of ccxt you used?

https://github.com/suenot/intuition7_js/blob/master/package.json I upload sandbox for this issue.

**Comment by suenot** [comment]
4.1.50 - work
--- between versions not tested
4.1.66 - i have bug

**Comment by carlosmiei** [comment]
@suenot Ok I think that I managed to reproduce it using your project, will take a look and let you know when I find anything

**Comment by suenot** [comment]
Wow, thank you for helping so quickly!

**Comment by carlosmiei** [comment]
@suenot You're welcome!
