### ISSUE TITLE
[coinbase] fee currency missing on trades

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#20257]
### Operating System

MacOS

### Programming Languages

JavaScript

### CCXT Version

4.1.77

### Description

The fee object coming from a coinbase `fetchTrades` call is missing a ccy:

```
{
  "info": {
    "entry_id": "xxx",
    "trade_id": "xxx",
    "order_id": "xxx",
    "trade_time": "2023-12-04T01:15:43.840048Z",
    "trade_type": "FILL",
    "price": "31804.2",
    "size": "0.0309",
    "commission": "2.45687445",
    "product_id": "BTC-GBP",
    "sequence_timestamp": "2023-12-04T01:15:43.845400Z",
    "liquidity_indicator": "MAKER",
    "size_in_quote": false,
    "user_id": "xxx",
    "side": "SELL"
  },
  "id": "xxx",
  "order": "xxx",
  "timestamp": 1701652543840,
  "datetime": "2023-12-04T01:15:43.840048Z",
  "symbol": "BTC/GBP",
  "side": "sell",
  "takerOrMaker": "maker",
  "price": 31804.2,
  "amount": 0.0309,
  "cost": 982.74978,
  "fee": {
    "cost": 2.45687445
  },
  "fees": [
    {
      "cost": 2.45687445
    }
  ],
}
  ```
In this example, the fee I was charged was in GBP (according to the coinbase website)

**Comment by carlosmiei** [comment]
Hello @npomfret,
The fee is not there because coinbase didn't provide it explicitly, as you can see inside `info`. Nonetheless, we will check if it is possible to infer it or not.

**Comment by npomfret** [comment]
The pattern is to infer if possible.  Coinbase charge the fee in the quote ccy.

**Comment by carlosmiei** [comment]
@npomfret I added that in the same day of the report, so if you update your ccxt version it should be there now
