### ISSUE TITLE
Market-buy request to CEX is sending a completely different 'amount' value than what was passed in !

### ISSUE THREAD

**Issue by PhlipPhlops** [ccxt/ccxt#2026]
My deets:
- OS: Ubuntu 16.04
- Programming Language version: Node.js v7.10.1
- CCXT version: 1.10.1185
- Exchange: CEX
- Method: createOrder()

My code:
```node.js
let price = toPrecision(BTCtoUSD.price * .0025, 4); // Logs to about 25.38
console.log(await exchange.createOrder('BTC/USD', 'market', 'buy', .0025, price));
```

My Error:
```
{ Error: cex {"error":"There was an error while placing your order: Invalid amount","safe":true}
    at cex.request (/home/PhlipPhlops/Programs/Crypto/Looper/node_modules/ccxt/js/cex.js:481:23)
    at process._tickCallback (internal/process/next_tick.js:109:7) constructor: [Function: ExchangeError] }
```

My.. verbosity?:
```
fetch:
 cex POST https://cex.io/api/place_order/BTC/USD/ 
Request:
 { 'Content-Type': 'application/x-www-form-urlencoded' } 
 key=XXX&signature=XXX&nonce=1519360099330&type=buy&amount=0.541875&order_type=market 

handleRestResponse:
 cex POST https://cex.io/api/place_order/BTC/USD/ 200 OK 
Response:
 { Date: 'Fri, 23 Feb 2018 04:28:19 GMT',
  'Content-Type': 'text/json',
  'Transfer-Encoding': 'chunked',
  Connection: 'close',
  'Set-Cookie': '__cfduid=d04583b18db0245b9529af9fd9bc4a6171519360099; expires=Sat, 23-Feb-19 04:28:19 GMT; path=/; domain=.cex.io; HttpOnly',
  'X-Frame-Options': 'DENY',
  Vary: 'Accept-Encoding',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Cf-Ray': '3f17700d1faa0d25-ATL' } 
 {"error":"There was an error while placing your order: Invalid amount","safe":true} 
```

As you can see, the `amount` value that's actually sent in the http request object doesn't at all seem related to the value that I passed into the `createOrder()` method. The `Invalid amount` error I'm getting off of the exchange I assume is related to invalid precision. I know CEX changed their precision values for some BTC and ETH pairs from 8 decimal places down to 2 and 4 respectively.

Looking forward to some help haha

**Comment by mkutny** [comment]
> As you can see, the amount value that's actually sent in the http request object doesn't at all seem related to the value that I passed into the createOrder() method.

Indeed it does related because of:
https://github.com/ccxt/ccxt/blob/b479862a8a82bcbe3ce979cdbd72ac543325446d/js/cex.js#L314

Basically, *their* amount is *ours* `amount * price` (which should result in `0.06345` but not in `0.541875` as verbose output showed... so I believe you mangled with your inputs somewhere, BTW).

**Comment by kroitor** [comment]
@PhlipPhlops the answer of @mkutny is correct, hope it helps, let us know if you still have difficulties with it.

**Comment by PhlipPhlops** [comment]
Yeah he was absolutely correct ! Thanks for the help I definitely appreciate it.

**Comment by npomfret** [comment]
I've just had a discussion with the CCXT support staff.  It seems like the answer might be to reverse the currencies...

I was trying to understand what was going on and attempted to place a BUY order in ETH/BTC (without using the current ccxt implementation), and as described above I got a weird amount executed.  I raised a ticket to see why it behaves like that, and this was the response:

> Thank you for contacting us.
> 
> I have checked with our Tech team and they told me that our system works in the regular mode, without any glitches. I have also checked your transaction history and logs of your account. 
> 
> So, in order to analyze your query extremely deeply, please provide us with a link of the POST method you have used since I see that you have placed an order on the pair  ETH/BTC, not BTC/ETH. That is why since you have placed a market order it filled immediately 0.001 BTC which was equivalent to 0.049753 ETH. Thus, kindly provide us not only with a method and link but also with the input you have used.
>

**Comment by npomfret** [comment]
ok, I'm getting an array of conflicting and nonsensical answers from the cex support team.  They don't appear to have a clue about how their own API operates.  

It seems apparent to me though that market buy orders are simply not supported (because the amount gets screwed up).  It's clearly a bug in their API that they are unaware of and/or are unable to fix.  Which makes no sense because you can place a market buy order from the website.

Can I suggest we add `has.createMarketOrder = false` to cex?

**Comment by kroitor** [comment]
@npomfret their docs have this snippet:


> #### application/json, market order
> ```JavaScript
> {
>   "symbol2Amount": "10000",
>   "symbol1Amount": "19970000",
>   "time": 1506615736816,
>   "message": "Your order has been completed. Bought 0.19970000 BTC for 100.00 USD",
>   "type": "buy",
>   "id": "88640269"
> }
> ```

It's interesting that in this case the amount/cost are integers, but the values in the message are floats. Maybe it has something to do with precision?

**Comment by npomfret** [comment]
Here is one I did:

```
fetch: 
cex POST https://cex.io/api/place_order/ETH/BTC/ 
Request: 
{ 'Content-Type': 'application/json' } 
{"key":"sLY8tznBCeArkoLMvUfiIJ0zbE","signature":"A0993A3238A384BD664FAEC5DBAE77B9935295FF8B6106DAE369B7C99F5246EA","nonce":"1575975183230","type":"buy","amount":0.001,"order_type":"market"}
```

`{"id":"11077606036","message":"Your order has been completed. Bought 0.04984500 ETH for 0.00099999 BTC","symbol1Amount":"49845","symbol2Amount":"99999","time":1575975183500,"type":"buy"}`

**Comment by kroitor** [comment]
@npomfret apparently, amount 0.001 corresponds to 0.00099999 BTC, so it's the cost sent as the amount if you have `createMarketBuyRequiresPrice` set to false...

- https://github.com/ccxt/ccxt/blob/master/js/cex.js#L543

**Comment by npomfret** [comment]
> This "market-buy requires cost" rule is common to several exchanges.

I didn't know this. Surely that's not a market order though?  That's a limit order.

**Comment by kroitor** [comment]
> That's a limit order.

It would be a limit order, if it was the _"amount to buy"_. But because it's the _"cost to spend"_ –technically this still is a market order.

**Comment by kroitor** [comment]
> I didn't know this.

You cannot miss it because it's a mandatory exception warning that is throw there (it's true by default). So, you've switched it off somewhere in your configs, if it worked for you without a price argument.

**Comment by npomfret** [comment]
So the usage pattern is something like

```
        let price = undefined;
        if(exchange.options.createMarketBuyOrderRequiresPrice) {
            price = await goAndGetASensiblePrice(symbol)
        }
        await exchange.createOrder(symbol, 'market', side, amount, price)
```

??

**Comment by kroitor** [comment]
> So the usage pattern is something like

Yep. 

```JavaScript
        let price = undefined;
        if(exchange.options.createMarketBuyOrderRequiresPrice) {
            price = await goAndGetASensiblePrice(symbol)
        }
        await exchange.createOrder(symbol, 'market', side, amount, price)
```

Or:

```JavaScript
        let cost = await goAndGetASensibleCost(symbol)
        exchange.options.createMarketBuyOrderRequiresPrice = false
        await exchange.createOrder(symbol, 'market', side, amount)
```

**Comment by npomfret** [comment]
@kroitor the logic above doesn't work for okex3 because the `createMarketBuyOrderRequiresPrice` option isn't set. I think it should be.

**Comment by npomfret** [comment]
Cex finally got back to me, they said the following:

> There is only one available currency pair via rest API with ETH and BTC involved: POST: https://cex.io/api/place_order/ETH/BTC/
> 
> Using this pair involves buying ETH for the amount of BTC. This means that if you want to buy for instance 1 ETH, you need first to convert it to BTC amount. You may use
> POST https://cex.io/api/convert/{symbol1}/{symbol2}
> to make the conversion. 
> 
> Thus, to place market order you need to specify the amount of BTC you want to spent to buy ETH. This is how the market order works on this pair


... so they have a special end-point for doing the conversion

**Comment by kroitor** [comment]
@npomfret their answer is a confirmation to the info above, thx!

> ... so they have a special end-point for doing the conversion

That endpoint uses the current orderbook to calculate your conversion rate, so, in short, you will always get a price back in time. In other words, you may want to ask for how long the rate returned by the `convert` endpoint is guaranteed... I think they don't guarantee it at all, and it's basically "for reference". Thus you can end up buying an unexpected amount if the rate is changing quickly and you're not reacting too quickly with serial calls to `convert`.
