### ISSUE TITLE
Bingx fetchOpenOrders

### ISSUE THREAD

**Issue by kiaxseventh** [ccxt/ccxt#20285]
### Operating System

macos

### Programming Languages

JavaScript

### CCXT Version

4.1.79

### Description

Bingx fetchOpenOrders does not work.
it just return a empty array !!!

(i have open order)

### Code

```
  let balance = await exchange.fetchOpenOrders('BTC/USDT');
console.log('==> ', balance);



```

**Comment by Dan-krm** [comment]
Hi @kiaxseventh can you follow these instructions and share your verbose output: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

fetchOpenOrders on bingx is working properly for me:
```
CCXT v4.1.80
bingx.fetchOpenOrders (BTC/USDT)
2023-12-07T23:57:49.680Z iteration 0 passed in 1282 ms

                 id |     timestamp |                 datetime | lastTradeTimestamp | lastUpdateTimestamp |   symbol |  type | side | price | cost | amount | filled | remaining | status |                           fee | trades |                          fees
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1732911955405963264 | 1701993380773 | 2023-12-07T23:56:20.773Z |      1701993380773 |       1701993380773 | BTC/USDT | limit |  buy | 30000 |    0 |  0.001 |      0 |     0.001 |   open | {"currency":"BTC","cost":"0"} |     [] | [{"currency":"BTC","cost":0}]
1 objects
```

**Comment by carlosmiei** [comment]
Hello @kiaxseventh, are you sure the order is still open?

**Comment by Dan-krm** [comment]
@kiaxseventh I'm going to close this issue for now since it looks like `fetchOpenOrders` is working as expected, feel free to reopen the issue and let us know if you are experiencing any problems
