### ISSUE TITLE
BingX watchTicker() is not supported

### ISSUE THREAD

**Issue by grozz97** [ccxt/ccxt#20309]
### Operating System

Ubuntu 20.04.5 LTS

### Programming Languages

Python

### CCXT Version

4.1.36

### Description

Please fix this, the exchange API supports this functionality.

`bingx watchTicker() is not supported yet: Traceback (most recent call last):
  File "./main.py", line 516, in watch_ticker
    await exchange.watch_ticker(symbol)
  File "../ccxt/async_support/base/exchange.py", line 2361, in watch_ticker
    raise NotSupported(self.id + ' watchTicker() is not supported yet')
ccxt.base.errors.NotSupported: bingx watchTicker() is not supported yet`

BingX WebSocket API: https://bingx-api.github.io/docs/#/en-us/swapV2/socket/market.html

### Code

```
  await bingx.watch_ticker(symbol)

```

**Comment by sc0Vu** [comment]
Hi @grozz97 

The ticker is a statistical calculation with the information calculated over the past 24 hours for a specific market (https://docs.ccxt.com/#/README?id=ticker-structure). That topic you pasted is for the order book, and already integrated (`watchOrderBook`).

You can call `watchOrderBook` like this https://docs.ccxt.com/#/ccxt.pro.manual?id=watchorderbook.

**Comment by grozz97** [comment]
@sc0Vu I'll try to pull this off. Thank you for your reply.
