### ISSUE TITLE
fetch_ohlcv does not return any data for the Bitrue Exchange

### ISSUE THREAD

**Issue by juber01** [ccxt/ccxt#20310]
### Operating System

MacOS

### Programming Languages

Python

### CCXT Version

4.1.83

### Description

The call to the fetch_ohlcv function does not return any data.  When traced through debug it can be seen to get data from the exchange but on the final return call all data seems to disappear.

### Code

import ccxt
import pandas as pd
import pandas_ta as ta
import numpy as np
import time

exchange = ccxt.bitrue({
"apiKey": apiKey,
"secret": secret
})

time_now = int(time.time() * 1000)

ohlcv = exchange.fetch_ohlcv(symbol="WTK/USDT", timeframe="1m", since=time_now, limit=10)

**Comment by carlosmiei** [comment]
@juber01 Using since = now just filters out every result  🙂
