### ISSUE TITLE
CCXT PYTHON COINBASE 

### ISSUE THREAD

**Issue by TheSman122333** [ccxt/ccxt#20311]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

LATEST

### Description

Using coinbase and ccxt python, doing coinbase.fetch_positions() doen't work, it says that it isnt supportec yet. it is very crucial to my code and I need some sort of workaround. I could genuinely just rewrite the whole function.

### Code

```
  

```

**Comment by TheSman122333** [comment]
No, I believe that is for their request API system, whereas we are calling a function that just prints data

**Comment by frosty00** [comment]
@TheSman122333 coinbase doesn't support fetch positions since you cannot trade derivatives on coinbase.com. Let us know if that doesn't solve your question!
