### ISSUE TITLE
KeyError: 'XBTUSD'

### ISSUE THREAD

**Issue by jorge0102** [ccxt/ccxt#20323]
### Operating System

Linux

### Programming Languages

Python

### Description

Hello, I have an error when trying to connect to Bitmex with Python. I have made several attempts using different symbols, such as 'btxusd' and 'btcusd', as well as others I have found in the process. Despite my efforts, I always encounter the same error. I have developed specific code for testing and identifying the source of the problem, but so far, I have not been able to resolve it.

Attached to this message, you will find the code I have created for testing. I appreciate in advance any guidance or assistance you can provide to help me overcome this obstacle.

This error: File "/app/bingx_integration/Api/api.py", line 121, in test_buy
    min_amount = exchange.markets[symbol]['limits']['amount']['min']
                 ~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'BTC/USD'

### Code

```
  api_key = '*******************'
api_secret = '**************************************'
symbol = 'XBTUSD'
leverage = 10 

exchange = ccxt.bitmex({
    'apiKey': api_key,
    'secret': api_secret,
    'enableRateLimit': True,
})

def test_buy():
    exchange.load_markets()

    if symbol not in exchange.markets:
        print(exchange.markets)
        return exchange.markets

    min_amount = exchange.markets[symbol]['limits']['amount']['min']

    amount = exchange.amount_to_precision(symbol, min_amount)

    leveraged_amount = amount * leverage

    leveraged_amount_decimal = exchange.decimal_to_precision(leveraged_amount, ccxt.ROUND, ccxt.TRUNCATE, exchange.markets[symbol]['precision']['amount'], False)

    order = exchange.create_market_buy_order(symbol, leveraged_amount_decimal, {'leverage': leverage})

    time.sleep(5)

    closed_order = exchange.create_market_sell_order(symbol, leveraged_amount_decimal, {'leverage': leverage})

    return "OK"

```

**Comment by sc0Vu** [comment]
Hi @jorge0102,

The key for markets is ccxt unified symbol, eg, BTC/USDT.

You can use `market(symbol)` to find market with exchange specified id.
