### ISSUE TITLE
Get OHLCV from OKX

### ISSUE THREAD

**Issue by Elferboy** [ccxt/ccxt#20320]
### Operating System

Windows 10

### Programming Languages

PHP

### CCXT Version

1.53.1

### Description

**fetch_ohlcv()** for okex5 always returns the last OHLCV ignoring $since parameter.
How to get market data from **OKX** for any required period?

### Code

```
$exchange = new \ccxt\okex5();

$symbol    = 'BTC/USDT';
$timeframe = '1h';
$since     = strtotime('2023-10-01 00:00:00') * 1000;
$limit     = 2;

$rates = $exchange->fetch_ohlcv($symbol, $timeframe, $since, $limit);
```
Return:
Array(
	[0] => Array(
		[0] => 1702296000000
		[1] => 42343.1
		[2] => 42392
		[3] => 42271
		[4] => 42333.8
		[5] => 168.42235824
		[6] => 7130508.875938553
		[7] => 7130508.875938553
		[8] => 0
	)
	[1] => Array(
		[0] => 1702292400000
		[1] => 42383.7
		[2] => 42487
		[3] => 42161.1
		[4] => 42343.1
		[5] => 516.17494457
		[6] => 21845216.861334972
		[7] => 21845216.861334972
		[8] => 1
	)
)

**Comment by Elferboy** [comment]
Talked to OKX support, they say to use before and after parameters to get period data. Limit is not needed here.
Need request:
https://www.okx.com/api/v5/market/candles?instId=BTC-USDT&bar=1H&after=1701471600000&before=1701388800000

**Comment by carlosmiei** [comment]
Hello @Elferboy, you can provide the `until` parameter to get a specific range, in this particular case you could do something like this:

```Php
ohlcv = await okx.fetch_ohlcv(symbol, tf, 1701388800000, null,  array("until" => 1701471600000))
```

**Comment by carlosmiei** [comment]
@Elferboy I noticed you have a really old version of ccxt, so I would suggest updating it, because the newest version supports many more features and fixes a lot of issues.

**Comment by Elferboy** [comment]
Thanks for answer. I updated the PHP version and updated the library and the returned result is great.
