### ISSUE TITLE
watchOrders does not always return an array (anymore)

### ISSUE THREAD

**Issue by hodlerhacks** [ccxt/ccxt#20344]
### Operating System

Ubuntu

### Programming Languages

JavaScript

### CCXT Version

4.1.72

### Description

With the following code:

```
const data = await exchange.watchOrders(symbol);
console.log(data);
```

I've always received back an array of orders. However, since a few days, some of the users of my application have been getting errors, consistently, when using Binance. I looked at their logs, and this is what's in 'data' in their case:

```
{
  info: {
    e: 'executionReport',
    E: 1702419340514,
    s: 'PAXGBTC',
    c: 'x-R4BD3S82d01aef415d4d4dc3bda574',
    S: 'BUY',
    o: 'LIMIT',
    f: 'GTC',
    q: '0.00260000',
    p: '0.04764000',
    P: '0.00000000',
    F: '0.00000000',
    g: -1,
    C: '',
    x: 'TRADE',
    X: 'FILLED',
    r: 'NONE',
    i: 123579579,
    l: '0.00260000',
    z: '0.00260000',
    L: '0.04764000',
    n: '0.00001491',
    N: 'BNB',
    T: 1702419340514,
    t: 4512804,
    I: 250979830,
    w: false,
    m: false,
    M: true,
    O: 1702419340514,
    Z: '0.00012386',
    Y: '0.00012386',
    Q: '0.00000000',
    W: 1702419340514,
    V: 'EXPIRE_MAKER'
  },
  symbol: 'PAXG/BTC',
  id: '123579579',
  clientOrderId: 'x-R4BD3S82d01aef415d4d4dc3bda574',
  timestamp: 1702419340514,
  datetime: '2023-12-12T22:15:40.514Z',
  lastTradeTimestamp: 1702419340514,
  lastUpdateTimestamp: 1702419340514,
  type: 'limit',
  timeInForce: 'GTC',
  postOnly: false,
  reduceOnly: undefined,
  side: 'buy',
  price: 0.04764,
  stopPrice: 0,
  triggerPrice: 0,
  amount: 0.0026,
  cost: 0.00012386,
  average: 0.04763846153846154,
  filled: 0.0026,
  remaining: 0,
  status: 'closed',
  fee: { cost: 0.00001491, currency: 'BNB' },
  trades: [
    {
      info: [Object],
      timestamp: 1702419340514,
      datetime: '2023-12-12T22:15:40.514Z',
      symbol: 'PAXG/BTC',
      id: '4512804',
      order: '123579579',
      type: 'limit',
      takerOrMaker: 'taker',
      side: 'buy',
      price: 0.04764,
      amount: 0.0026,
      cost: 0.00012386,
      fee: [Object],
      fees: [Array]
    }
  ],
  fees: [],
  takeProfitPrice: undefined,
  stopLossPrice: undefined
}
```

It's an object, instead of an array of objects, which is causing problems further down my code.

Is this a known issue?

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @hodlerhacks 

Can you set `newUpdates` to false (https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual#newupdates-mode)? The default value is true, and you'll get the latest response from exchange server (it's single order from binance).

**Comment by hodlerhacks** [comment]
Hi @sc0Vu, thanks for your quick response.

Interestingly, this has never been an issue during the past 2.5 years. Also, not everyone has this problem with Binance. I cannot reproduce this myself. Has anything changed?

My application is used with many different exchanges. Can I apply this setting safely with any exchange, or could it affect the proper working? I'm a bit concerned about changing this, because in fact I do want to just receive the latest updates, so that would require newUpdates to be true.

**Comment by sc0Vu** [comment]
Hi @hodlerhacks, I think the default value of newUpdates had been changed a couple of months ago.

If you set this value to flase, the return value would be array or orders, you'll need to loop orders for the updates.

With newUpdates, you only received the updated order (single object).

**Comment by hodlerhacks** [comment]
Hi @sc0Vu, I'm still a bit unsure what to do here. I do only want to receive the most recent updates. This is what's on the link that you shared:

_The result from the newUpdates mode will be one or more updates that have occurred since the last time exchange.watchMethod resolved. CCXT Pro can return one or more orders that were updated since the previous call._

And more:

_The result of calling exchange.watchOrders will look like shown below:_

```
[
    order, // see https://github.com/ccxt/ccxt/wiki/Manual#order-structure
    order,
    order,
    ...
]
```

As documented, an array should be expected as a result. That is exactly the behavior I've always observed, and it is what I want to use moving forward. So changing the setting to false doesn't seem like the way to go.

In addition to that, I'm quite sure there is something weird going on. For some installations, the result from watchOrders is an array, even if there is just one order. Like it has always been, for a wide range of exchanges. However, only some installations do not get an array back. I can't pinpoint what might be the root cause, but I do think there is a bug somewhere that is causing this.

**Comment by hodlerhacks** [comment]
Hi again @sc0Vu, analyzing a bit more with the affected users, it seems the problem appeared for them with the update to v4.1.72. Could the problem be related to https://github.com/ccxt/ccxt/pull/20163 by any chance?

**Comment by sc0Vu** [comment]
Hi @hodlerhacks,

I don't think so, we didn't update response for that PR. It's probably affected by this commit https://github.com/ccxt/ccxt/commit/9fe53def892 (used to return list).  

As document said, with `newUpdates=true`, the value is one or more updates from exchange ws.
> The result from the newUpdates mode will be one or more updates that have occurred since the last time exchange.watchMethod resolved.

**Comment by hodlerhacks** [comment]
Hi @sc0Vu, I understand just one result may be returned. But I would expect it to be always an array. If not, I need to build in logic to first check if it's an array or a single object, and then handle it accordingly. That can't be the intention. Right? This is also not how it works with other exchanges. 

Can't you simply always return an array, even if there is just one order?

**Comment by carlosmiei** [comment]
@hodlerhacks You're right, it should always return a list and not a single order, if that is not happening it's a bug, and we need to fix it asap.

**Comment by hodlerhacks** [comment]
Thanks @carlosmiei!

**Comment by hodlerhacks** [comment]
Hi guys, thanks a lot for the quick fix! Stupid question, but once a fix is merged and closed as completed, is it then immediately available when installing the latest version (4.1.89 in this case)? Or should I wait until the next version number (4.1.90) appears in the list of commits?

**Comment by carlosmiei** [comment]
@hodlerhacks , it it's not a stupid question 🙂  In this case you need to wait for the next release that contains this fix, it should be out shortly and yes, it will be 4.1.90

**Comment by hodlerhacks** [comment]
Excellent, thanks for educating me ;-)

**Comment by carlosmiei** [comment]
@hodlerhacks No problem 🙂, btw 4.1.90 is out, you can update your ccxt version now

**Comment by hodlerhacks** [comment]
I've asked one of the people who experienced this problem to try it out. (I didn't have this problem myself for some reason.) Waiting for the results.

**Comment by hodlerhacks** [comment]
This person updated to the latest version, but then got this problem instead: https://github.com/ccxt/ccxt/issues/20393. Because of that, the application does not place any orders, so I cannot confirm if the fix works. I trust it does. But we'll know for sure once there is a solution for https://github.com/ccxt/ccxt/issues/20393.
