### ISSUE TITLE
How to debuge the POST url

### ISSUE THREAD

**Issue by mostar** [ccxt/ccxt#2035]
Hi, 

My php version is 5.5.9.
ccxt is up to date I "git pull" in now before running.

I'm tryng to compare the URL and the post parameter ccxt use, in order to comper them to the exchange documentation.  Verbose don't display this information, How can I do it?

Failing on

`php  examples/php/cli.php vaultoro createLimitBuyOrder  gld 1 100 --verbose`

> ./keys.json
> 
> Request:
> Array
> (
>     [0] => GET
>     [1] => https://api.vaultoro.com/markets
>     [2] => Array
>         (
>         )
> 
>     [3] => 
> )
> 
> Response:
> Array
> (
>     [0] => GET
>     [1] => https://api.vaultoro.com/markets
>     [2] => 200
>     [3] => 
>     [4] => Array
>         (
>             [server] => Array
>                 (
>                     [0] => nginx
>                 )
> 
>             [date] => Array
>                 (
>                     [0] => Sat, 24 Feb 2018 06:49:00 GMT
>                 )
> 
>             [content-type] => Array
>                 (
>                     [0] => application/json
>                 )
> 
>             [transfer-encoding] => Array
>                 (
>                     [0] => chunked
>                 )
> 
>             [connection] => Array
>                 (
>                     [0] => keep-alive
>                 )
> 
>             [cache-control] => Array
>                 (
>                     [0] => no-store
>                 )
> 
>             [pragma] => Array
>                 (
>                     [0] => no-cache
>                 )
> 
>             [access-control-allow-origin] => Array
>                 (
>                     [0] => *
>                 )
> 
>             [access-control-allow-headers] => Array
>                 (
>                     [0] => Origin, X-Requested-With, Content-Type, Accept
>                 )
> 
>             [vary] => Array
>                 (
>                     [0] => Accept-Encoding
>                 )
> 
>             [content-encoding] => Array
>                 (
>                     [0] => gzip
>                 )
> 
>             [strict-transport-security] => Array
>                 (
>                     [0] => max-age=31536000
>                 )
> 
>         )
> 
>     [5] => {
>   "status": "success",
>   "data": {
>     "MarketCurrency": "GLD",
>     "BaseCurrency": "BTC",
>     "MarketCurrencyLong": "Gold",
>     "BaseCurrencyLong": "Bitcoin",
>     "MinTradeSize": 1e-8,
>     "MarketName": "BTC-GLD",
>     "IsActive": true,
>     "MinUnitQty": 0.0002,
>     "MinPrice": 0.000002,
>     "LastPrice": "0.00451830",
>     "24hLow": "0.00425500",
>     "24hHigh": "0.00470000",
>     "24hVolume": "39129.924"
>   }
> }
> )
> vaultoro->createLimitBuyOrder (gld, 1, 100)
> Exchange Error: vaultoro does not have market symbol gld
> 

According to the exchange documentation it need to post like this:

> https://api.vaultoro.com/1/buy/gld/limit?btc=0.05&price=0.16253&nonce=1429548679&apikey=ayn3eKSEHSIYN9uhtpGn5hqS0CBtestx

**Comment by kroitor** [comment]
Hi! Your question is answered here: https://github.com/ccxt/ccxt/wiki/Manual#placing-orders

> Exchange Error: vaultoro does not have market symbol gld

This error is telling you that you are not using symbols properly:

https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

```
mbp:ccxt igorkroitor$ node examples/js/symbols vaultoro
Instantiating vaultoro exchange

Symbols:

limits | precision | tierBased | percentage | taker | maker | id      | symbol  | base | quote | baseId | quoteId | info
-----------------------------------------------------------------------------------------------------------------------------------
       |           |           |            |       |       | BTC-GLD | BTC/GLD | BTC  | GLD   | BTC    | GLD     | [object Object]

---------------------------------------------------------------

Currencies:

id  | code | precision
----------------------
BTC | BTC  | 8
GLD | GLD  | 8

---------------------------------------------------------------
vaultoro has 1 symbols and 2 currencies

mbp:ccxt igorkroitor$
```

> vaultoro->createLimitBuyOrder (gld, 1, 100)

This is incorrect, the first argument of a call to createOrder is a symbol (a pair). BTC/GLD, for example.

Hope it helps.
