### ISSUE TITLE
I would like to collaborate as a translator to Spanish

### ISSUE THREAD

**Issue by UlisesTJ** [ccxt/ccxt#2036]
... which is my native language could translate the readme, contributing and any other text document as a license among others.

**Comment by knz** [comment]
@UlisesTJ https://github.com/cockroachdb/cockroach/issues/23038#issuecomment-368220870

**Comment by UlisesTJ** [comment]
??

**Comment by kroitor** [comment]
@UlisesTJ your help would be really appreciated! Let us know if you need anything to start. Thank you!
