### ISSUE TITLE
fetch_bids_asks not working for Bitrue exchange

### ISSUE THREAD

**Issue by juber01** [ccxt/ccxt#20372]
### Operating System

MacOS

### Programming Languages

Python

### CCXT Version

4.1.83

### Description

The executing the function call fetch_bids_asks it is throwing an exception error.

Exception has occurred: BadSymbol       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
bitrue does not have market symbol W
  File "/python3.11/site-packages/ccxt/base/exchange.py", line 3905, in market
    raise BadSymbol(self.id + ' does not have market symbol ' + symbol)
  File "/python3.11/site-packages/ccxt/base/exchange.py", line 2979, in market_symbols
    market = self.market(symbols[i])
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/3.11.7/lib/python3.11/site-packages/ccxt/bitrue.py", line 1419, in fetch_bids_asks
    symbols = self.market_symbols(symbols, None, False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/trader_bot/trader_bot.py", line 53, in main
    bids_asks = exchange.fetch_bids_asks("WTK/USDT")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

### Code

# Initialise the ccxt exchange for bitrue
  exchange = ccxt.bitrue({
    "apiKey": bitrue_key,
    "secret": bitrue_secret
  })

#Get bids and asks
    bids_asks = exchange.fetch_bids_asks("WTK/USDT")

**Comment by sc0Vu** [comment]
Hi @juber01 

The symbols is list for fetch_bids_asks, try this: `exchange.fetch_bids_asks(['WTK/USDT'])`

**Comment by juber01** [comment]
Thank you that works.  Can this take this param {"limit":5} to return bids and asks instead of just the latest?

**Comment by carlosmiei** [comment]
@juber01, that is not possible, if you want to get multiple bids/asks you should use fetchOrderBook Instead

**Comment by juber01** [comment]
Thank you for your help.  This is now resolved.
