### ISSUE TITLE
fetch_closed_orders haven't order price

### ISSUE THREAD

**Issue by kasnitski** [ccxt/ccxt#2037]
Price == 0.0 for fetch_closed_orders on the Binance.

Return example:
`
[{'info': {'symbol': 'TRXBTC', 'orderId': 30522566, 'clientOrderId': '0dblJ6QDXUJx8UomweCthB', 'price': '0.00000000', 'origQty': '162.00000000', 'executedQty': '162.00000000', 'status': 'FILLED', 'timeInForce': 'GTC', 'type': 'MARKET', 'side': 'SELL', 'stopPrice': '0.00000000', 'icebergQty': '0.00000000', 'time': 1519426276647, 'isWorking': True}, 'id': '30522566', 'timestamp': 1519426276647, 'datetime': '2018-02-23T22:51:17.647Z', 'symbol': 'TRX/BTC', 'type': 'market', 'side': 'sell', 'price': 0.0, 'amount': 162.0, 'cost': 0.0, 'filled': 162.0, 'remaining': 0.0, 'status': 'closed', 'fee': None}]
`

@kroitor What could you suggest?

- OS: linux
- Programming Language version: python
- CCXT version: 1.10.1178
- Exchange: Binance
- Method: fetch_closed_orders

**Comment by kroitor** [comment]
@kasnitski you are most likely trying to fetch a market order, this has been answered here: https://github.com/ccxt/ccxt/issues/2019 )
Basically, you can get the price(s) of the trades that filled your market order:
https://github.com/ccxt/ccxt/wiki/Manual#personal-trades
Let me know if it does not help. Thx!
