### ISSUE TITLE
Coinbase sending back strange error: circuit breaker open

### ISSUE THREAD

**Issue by pottertech** [ccxt/ccxt#20385]
### Operating System

Ubuntu 20.04

### CCXT Version

CCXT v4.1.85

### Description

Here is the message I am getting:

Coinbase {"error":"unknown","error_details":"circuit breaker open.  See go/circuit-breaker-troubleshooting","message":"circuit breaker open.  See go/circuit-breaker-troubleshooting"}

However the Coinbase API documentation states that Coinbase does not use circuit breakers.
Reference: https://www.coinbase.com/legal/trading_rules

2.5 Flash Crashes and Circuit Breakers

2.51 Coinbase Markets does not use circuit breakers or automated trading halts based on predetermined price bands. As provided in Section 2.22 and 2.31, Coinbase Markets Market Operations may, in its discretion, halt trading.

Does anyone know what this is about, why, or when it would happen?

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @pottertech

Is the market halted (market.active)?

**Comment by pottertech** [comment]
Good questions, I will have to check.

**Comment by sc0Vu** [comment]
Hi @pottertech 

Cool! Let me know if this issue happen again.

**Comment by pottertech** [comment]
I have not gotten the error again after adding in more checking to ensure the market is active before attempting to BUY or SELL.

**Comment by reverendrenegade** [comment]
@pottertech I'm getting the same error, what check are you performing to ensure the market is active?
