### ISSUE TITLE
Bybit load markets are not controlled by self.exchange.options['fetchMarkets']

### ISSUE THREAD

**Issue by Alfavisioner** [ccxt/ccxt#20386]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

4.1.87

### Description

I need to load only spot
I specify exchange.options['fetchMarkets'] = ['spot']
But all markets are loaded in exchange.load_markers, and time is 3 timer higher

Please, fix it in bybit.py

    def fetch_markets(self, params={}):
        """
        retrieves data on all markets for bybit
        :see: https://bybit-exchange.github.io/docs/v5/market/instrument
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: an array of objects representing market data
        """
        if self.options['adjustForTimeDifference']:
            self.load_time_difference()
        promisesUnresolved = [
            self.fetch_spot_markets(params),
            self.fetch_future_markets({'category': 'linear'}),
            self.fetch_future_markets({'category': 'inverse'}),
            self.fetch_option_markets({'baseCoin': 'BTC'}),
            self.fetch_option_markets({'baseCoin': 'ETH'}),
            self.fetch_option_markets({'baseCoin': 'SOL'}),
        ]

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @Alfavisioner,

Oh, the `fetchMarkets` behavior is not the same as binance. I'll push a fix asap.
