### ISSUE TITLE
Poloniex limit buy order is not placed

### ISSUE THREAD

**Issue by Shafayat** [ccxt/ccxt#2038]
- MacOS 10.13.3
- NodeJS v9.4.0
- CCXT version: 1.10.1189
- Exchange: Poloniex
- Method: createLimitBuyOrder

i have placed a limitBuy order which returns this response: 

```
{ info: 
   { timestamp: 1519480276683,
     status: 'open',
     type: 'limit',
     side: 'buy',
     price: 1e-8,
     amount: 10000,
     orderNumber: '19640401965',
     resultingTrades: [] },
  id: '19640401965',
  timestamp: 1519480276683,
  datetime: '2018-02-24T13:51:16.683Z',
  status: 'open',
  symbol: 'DOGE/BTC',
  type: 'limit',
  side: 'buy',
  price: 1e-8,
  cost: 0,
  amount: 10000,
  filled: 0,
  remaining: 10000,
  trades: [],
  fee: undefined }
```

immediately i check for open orders which returns empty array and my full balance also there.

Code i used 

```
let polo = new ccxt.poloniex({
    apiKey: "******",
    secret: "******",
    nonce: () => nonce() * 10, 
});
const symbol = 'DOGE/BTC';
const amount = 10000;
const price = 0.00000001;
polo.createLimitBuyOrder(symbol, amount, price).then(res => console.log(res));
```

**Comment by kroitor** [comment]
Hi! You issue is covered here:
- https://github.com/ccxt/ccxt/wiki/Manual#querying-orders
- https://github.com/ccxt/ccxt/wiki/Manual#orders-cache
- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

> immediately i check for open orders which returns empty array and my full balance also there.

You then have to check if the order is closed successfully. Unfortunately, we don't see the code for checking the order, you only posted the code for order placement. If you then check your orders from a script that is launched in another process, you will most likely have `.orders` cache out of sync.

Let us know if it does not help.
