### ISSUE TITLE
Request to add BloFin exchange to ccxt

### ISSUE THREAD

**Issue by yanni-fe** [ccxt/ccxt#20396]
### Exchange Name

BloFin

### URL of the Exchange

https://blofin.com

### URL of the Exchange's API docs

https://blofin.com/docs

### Why should this exchange be implemented?

Blofin is a rapidly growing exchange that provides users with fast and reliable trading as well as secure asset management.

**Comment by fxsjy** [comment]
https://github.com/ccxt/ccxt/pull/20371

**Comment by ttodua** [comment]
as mentioned in above comment, blofin was integrated in CCXT

**Comment by Flowdefi** [comment]
Blofin promo code "rewards" gets new users 20% off trading fees (those add up fast with 100x leverage) and signup bonuses that you earn as you trade 😎
