### ISSUE TITLE
verbose = False ignored

### ISSUE THREAD

**Issue by AhmMontasser** [ccxt/ccxt#2039]
Hello, 

I am using ccxt with the following information and it looks likeccxt is ignoring the verbose = False flag 

self.market=ccxt.poloniex({'apiKey':'','secret':'','verbose': False,'nonce': ccxt.Exchange.microseconds})
the terminal is floaded with http requests output

i also tried using 
logging.getLogger("requests").setLevel(logging.CRITICAL)
logging.getLogger("urllib3").setLevel(logging.CRITICAL)

and nothing happened

- OS: Ubuntu 16.04
- Programming Language version: python 3.5
- CCXT version: 1.10.1167

update
i installed version 1.10.1036 and it worked, it looks like something is different in version 1.10.1167
- Exchange: Poloniex or bittrex
- Method: fetch_ticker , fetch_ohlcv , fetch_balance 

Regards,

**Comment by kroitor** [comment]
I'm closing this, until we have a follow up further, if you don't mind. Feel free to reopen it if needed, or just ask questions if any. Thx!
