### ISSUE TITLE
Please advise how to correctly set parameters oflags for Kraken exchange

### ISSUE THREAD

**Issue by 89d55d5288** [ccxt/ccxt#20406]
### Operating System

Debian, Windows

### Programming Languages

Python

### CCXT Version

4.1.86

### Description

Please advise how to correctly set parameters oflags for Kraken exchange

Problem:

When params = {} market order execution time is 0.2 seconds

When params = {"oflags": "fciq"} or params = {"oflags": "fcib"}

market order execution time 2.0 seconds 

I suspect that the problem is in passing params = {"oflags": "fciq"} or params = {"oflags": "fcib"}. When passing params = {} there are no problems with time.

### Code

```
             params = {"oflags": "fciq"} if exchange.id == 'kraken' and side == 'sell' else {
                "oflags": "fcib"} if exchange.id == 'kraken' and side == 'buy' else {}

            print(params)

                order = await exchange.create_order_ws(symbol, type, side, amount, price, params=params)

```

**Comment by pcriadoperez** [comment]
hi @89d55d5288 , I don't see why those two flags would cause any longer execution time.
I'm assuming it is something from the exchange side, as from ccxt there should not be any difference.
To confirm, can you provide a verbose output of the script you are running?

**Comment by 89d55d5288** [comment]
> hi @89d55d5288 , I don't see why those two flags would cause any longer execution time. I'm assuming it is something from the exchange side, as from ccxt there should not be any difference. To confirm, can you provide a verbose output of the script you are running?

Hi pcriadoperez

You are right. it is something from the exchange side. Thnks

**Comment by 89d55d5288** [comment]
Good afternoon!

Kindly help with the issue params = {"oflags": "fcib"}. With this key, the commission should be taken from "base" for "buy" operation.
But my commission is taken from "quote".
sending {'event': 'addOrder', 'token': 'iKDrjlnDZqZAtHEF7K___WOjnc', 'reqid': 2467__39, 'ordertype': 'market', 'type': 'buy', 'pair': 'ETH/USDT', 'volume': '0.00373474', 'oflags': 'fcib'}
message {'descr':'buy 0.00373474 ETHUSDT @ market','event':'addOrderStatus','reqid':2467__39,'status':'ok','txid':'OUZMPR-BKYJA-_______'}
{'Symbol':'ETH/USDT','Order ID':'OUZMPR-BKYJA-_____','Status':'Unknown','Price': 2931.49,'Amount': 0.00373474,'Filled': 0,'Cost': 10.9483529626,'Side':'buy','Fee': {'cost': 0.04379, 'currency': 'USDT'}}
What is the error in forming the request and passing the key?

Code
             params = {"oflags": "fciq"} if exchange.id == 'kraken' and side == 'sell' else {
                "oflags": "fcib"} if exchange.id == 'kraken' and side == 'buy' else {}

            print(params)

                order = await exchange.create_order_ws(symbol, type, side, amount, price, params=params)
