### ISSUE TITLE
kucoin fetchOrder requires parameter type=["BUY"|"SELL"]

### ISSUE THREAD

**Issue by AlfredoBB** [ccxt/ccxt#2040]
- OS: Ubuntu 17.10 i386
- Programming Language version: JSnode 9.5.0
- CCXT version: latest
- Exchange: Kucoin
- Method: fetchOrder, cancelOrder
- Code: Code is the following:

m1.fetchOrder (id=global.lastId,symbol=marketToMake,type = 'limit',side=action,params={'type':action=='buy'?"BUY":"SELL"})
m3.cancelOrder(id=global.lastId,symbol=marketToMake,type = 'limit',side=action,params={'type':action=='buy'?"BUY":"SELL"})

- Error: kucoin fetchOrder requires parameter type=["BUY"|"SELL"]

I think that is a bug.

**Comment by kroitor** [comment]
> I think that is a bug.

I think you're using fetchOrder incorrectly )

```JavaScript
;(async () => {

    // ...

    orderId = '123456'
    symbol = 'ETH/BTC'

    // ...

    // this is a proper call to fetchOrder
    await m1.fetchOrder (orderId, symbol, { type: (action === 'buy' ? "BUY" : "SELL") })

    // ...

    // this is a proper signature of cancelOrder
    await m3.cancelOrder (orderId, symbol)

    // ...

}) ()
```

Please, read the Manual very carefully:
- https://github.com/ccxt/ccxt/wiki/Manual#querying-orders
- https://github.com/ccxt/ccxt/wiki/Manual#canceling-orders

Let us know if it does not help.
