### ISSUE TITLE
fetchTicker() rate limit. Binance

### ISSUE THREAD

**Issue by O4karitO** [ccxt/ccxt#2041]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Centos
- Programming Language version: 
- CCXT version: latest
- Exchange: Binance
- Method: fetchticker()

A single fetchticker every second is causing a "too many requests error".

```JavaScript
(async () => {
    let id = binance
    let exchange = new ccxt[id]()
    let symbol = 'TRX/BTC'
    let orderbook = await (exchange.fetchTicker (symbol))
    let bid = orderbook.bid
    let ask = orderbook.ask
    let spread = (bid && ask) ? ask - bid : undefined
    console.log(bid,ask,spread)
}) ();
```

it's requested once per second. Which is just 60 requests per minute.

I need a ticker for a single coin and not sure how is it possible to exceed their limitation by using it.
Thanks

**Comment by kroitor** [comment]
> it's requested once per second.

I'd say, you think that it's requested once per second. But it's not. You're creating an exchange instance everytime you fetch the ticker, which isn't the proper way to work with an exchange instance...

To work with it properly, you need to instantiate the exchange once with enabled built-in rate limiter, and then launch a fetchTicker loop on the same instance, without recreating it upon each call.

This code does work without a problem:

https://github.com/ccxt/ccxt/blob/master/examples/js/live-ticker.js

```JavaScript
"use strict";

const asTable   = require ('as-table')
    , log       = require ('ololog').noLocate
    , ansi      = require ('ansicolor').nice
    , ccxt      = require ('ccxt')

let printSupportedExchanges = function () {
    log ('Supported exchanges:', ccxt.exchanges.join (', ').green)
}

let printUsage = function () {
    log ('Usage: node', process.argv[1], 'exchange'.green, 'symbol'.yellow)
    printSupportedExchanges ()
}

let printTicker = async (id, symbol) => {

    // check if the exchange is supported by ccxt
    let exchangeFound = ccxt.exchanges.indexOf (id) > -1
    if (exchangeFound) {

        log ('Instantiating', id.green, 'exchange')

        // instantiate the exchange by id
        let exchange = new ccxt[id] ({ enableRateLimit: true })

        // load all markets from the exchange
        let markets = await exchange.loadMarkets ()

        if (symbol in exchange.markets) {

            while (true) {

                const ticker = await exchange.fetchTicker (symbol)

                log ('--------------------------------------------------------')
                log (exchange.id.green, symbol.yellow, exchange.iso8601 (exchange.milliseconds ()))
                log (ccxt.omit (ticker, 'info'))
            }

        } else {

            log.error ('Symbol', symbol.bright, 'not found')
        }


    } else {

        log ('Exchange ' + id.red + ' not found')
        printSupportedExchanges ()
    }
}

;(async function main () {

    if (process.argv.length > 3) {

        const id = process.argv[2]
        const symbol = process.argv[3].toUpperCase ()
        await printTicker (id, symbol)

    } else {

        printUsage ()
    }

    process.exit ()

}) ()
```

It does poll tickers approximately twice per second for more than a minute without breaking.
Let us know if it does not help. Thx!

**Comment by kroitor** [comment]
Hi, @alandardic! We need more info from you to be able to help: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

What's your programming language version? Your ccxt version?

**Comment by alandardic** [comment]
Hi @kroitor,
I'm trying to run this example: https://github.com/ccxt/ccxt/blob/master/examples/js/live-ticker.js

I cloned the ccxt repo and tried to run this command:
node live-ticker.js bitfinex "ETH/USD"

my  node version is v9.11.1

after 22~ ticks, I get this error: Error: bitfinex {"error":"ERR_RATE_LIMIT"}

My programming language is node.js - but in this case, it is e-relevant because all I'm trying to do is  to make the 'live-ticker' example work (I didn't change anything)

Thanks again,

**Comment by kroitor** [comment]
@alandardic yep, i've been able to reproduce...

In their docs they say it's 30req/min for the ticker...

![bitfinex-ticker-rate-limit](https://user-images.githubusercontent.com/1294454/40719345-09022470-641c-11e8-9df6-f9b1beaeb86e.jpg)

Well, here's an entire run of me sending 26 requests in one minute and getting banned, with timestamps: https://gist.github.com/kroitor/fb6624fb8465b5f6906862712b33c1a5

Obviously, Bitfinex is not telling their real ratelimits, or they could have changed their actual limits and forgot to update their docs...

I'm going to debug it further to find a reasonable value for it...

**Comment by alandardic** [comment]
Thanks a lot @kroitor!!!

I'm looking forward to an update (regarding this issue)

Good luck!

**Comment by kroitor** [comment]
@alandardic ok, I found that with rateLimit = 4000 msec, their fetchTicker works fine without a ban, that's 15 requests per minutes, two times lower than said in their docs...

I've added a third optional rateLimit argument, so you can launch the same `live-ticker.js` example to see if it works for you with various rateLimit values, like so:

```sh
# runs with default rate limit 1500 msec, trigger a short ban within a minute
mbp:ccxt igorkroitor$ node examples/js/live-ticker.js bitfinex ETH/BTC  

# runs with an overriden rateLimit of 4000 msec, without a ban
mbp:ccxt igorkroitor$ node examples/js/live-ticker.js bitfinex ETH/BTC 4000
```

So, if you're going to poll with `fetchTicker`, then you should instantiate your Bitfinex like so:

```JavaScript
const bitfinex = new ccxt.bitfinex ({ enableRateLimit: true, rateLimit: 4000 })
```

... and you'll be fine. Unfortunately, we can't set the higher default value in the lib right now, as their rate limits vary for different endpoints. So, for now, the user is responsible for tweaking rate limits according to the needs and purposes of the application logic, that is, until we finish our *tokenBucket* integration...

Hope this helps.

**Comment by alandardic** [comment]
@kroitor - It helps a lot 👏👏👏

Thank you very much for your prompt answer - and for your help!!!

You are awesome!!! 💪💪💪
