### ISSUE TITLE
Coinbase Order Fails with unhelpful error message

### ISSUE THREAD

**Issue by jayburston** [ccxt/ccxt#20419]
### Operating System

Linux

### Programming Languages

PHP 8.2

### CCXT Version

4.1.91

### Description

Coinbase trades fail with "coinbase createOrder() has failed, check your arguments and parameters"

When verbose logging is on, the error is pretty clear:
```
{"success":false,"failure_reason":"UNKNOWN_FAILURE_REASON","order_id":"","error_response":{"error":"INSUFFICIENT_FUND","message":"Insufficient balance in source account","error_details":"","preview_failure_reason":"PREVIEW_INSUFFICIENT_FUND"},"order_configuration":{"market_market_ioc":{"quote_size":"10"}}}
```
Not sure if this is intended or not, so thought I would raise it as the actual error is far more useful than the generic one, and other CCXT exchanges seem to give balance errors OK.

### Code

```
  

```

**Comment by Dan-krm** [comment]
Hi @jayburston thanks for pointing this out, I opened a pull request that fixes this so that failed createOrder requests return the actual error instead of a generic one
