### ISSUE TITLE
Binance : fetch_last_prices is not supported yet. 

### ISSUE THREAD

**Issue by leebh12** [ccxt/ccxt#20410]
There is a problem with the fetch_last_prices function call.

When I run the program at home, it works normally.
However, the following problems occur when running on a company computer.

fetch_last_prices is not supported yet.

While looking for the problem, I found a difference between the two places.
ccxt\binance.py
ccxt\base\exchange.py

There is a function called fetch_last_prices in two places, and it is defined in binance.py. It is not defined in exchange.py.

Not supported yet in version 4.1.91. An error occurs.
It operates normally in version 4.1.83 and lower versions. This happened on both my home and work computers.

** In version 4.1.91, I confirmed that the fetch_last_prices function was deleted from the binance.py file. Is this function no longer available in the latest version?

Please check this issue and provide feedback.

**Comment by sc0Vu** [comment]
Hi @leebh12 

Not sure why this function was removed. Before we update binance, can you call these implicit method manually?

```PYTHON
# spot
public_get_ticker_price
# inverse
dapi_public_get_ticker_price
# linear
fapi_public_get_ticker_price
```

**Comment by leebh12** [comment]
I haven't tried calling it manually.

If the ccxt development team has a clear intention to delete that function, I can replace it with another function. There are several other functions that get the current price without having to use that function. However, I used that function because I simply needed current price information.
I was just curious about why that function was deleted and the intention behind it.

pip install --upgrade ccxt==4.1.83
Now I am just using the version after downgrading using the above command.

**Comment by sc0Vu** [comment]
Hi @leebh12 

The functions are public, you can implement `fetch_last_prices` if you want to upgrade ccxt with the same feature (before we unified the function).

https://github.com/ccxt/ccxt/blob/4.1.83/python/ccxt/binance.py#L3029
