### ISSUE TITLE
Bitmex websocket stops receiving data with no exception thrown

### ISSUE THREAD

**Issue by quantitative-technologies** [ccxt/ccxt#20412]
### Operating System

linux

### Programming Languages

Python

### CCXT Version

4.1.91

### Description

I have observed this twice so far:

I call watchOrderBook on the bitmex exchange, and then at exactly 2am UTC it stops receiving order book data but no exception is thrown.  

My application is straightforward, but I have not written an MRE to rule out the possibilities that an exception is being swallowed or the program is failing to respond to the data (though this is highly unlikely, e.g. data continues coming in from binance). 

### Code

NA

```
  

```

**Comment by hi-bingo** [comment]
I also find this problem in bitget (maybe also occur in other exchanges), using python and ccxt=4.1.95. I found the network error becomes uncatchable in the watch_method, while in ccxt=4.1.68, this error is catchable. I think this maybe a bug in the lastest ccxt version? I will later post my test code.

**Comment by hi-bingo** [comment]
> I also find this problem in bitget (maybe also occur in other exchanges), using python and ccxt=4.1.95. I found the network error becomes uncatchable in the watch_method, while in ccxt=4.1.68, this error is catchable. I think this maybe a bug in the lastest ccxt version? I will later post my test code.

I test code on binance/okx/bybit/kucoin/bitget/bitmex. This problem still occurs in ccxt=4.1.98, is it a bug? or am I wrong? Really need your help @pcriadoperez @carlosmiei
