### ISSUE TITLE
Bitget V2 fetch_open_orders with symbol arg

### ISSUE THREAD

**Issue by hi-bingo** [ccxt/ccxt#20411]
### Programming Languages

Python

### CCXT Version

4.1.90

### Description

In bitget v2 doc, seems it support fetch all open orders (symbol is not required for both spot and swap), but ccxt will raise ArgumentsRequired exception if symbol is not given. Maybe it can be fixed?

https://www.bitget.com/api-doc/spot/trade/Get-Unfilled-Orders
### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @hi-bingo 

In bitget, we integrate these apis:
https://www.bitget.com/api-doc/spot/trade/Get-Unfilled-Orders
https://www.bitget.com/api-doc/spot/plan/Get-Current-Plan-Order
https://www.bitget.com/api-doc/contract/trade/Get-Orders-Pending
https://www.bitget.com/api-doc/contract/plan/get-orders-plan-pending
https://www.bitget.com/api-doc/margin/cross/trade/Get-Cross-Open-Orders
https://www.bitget.com/api-doc/margin/isolated/trade/Isolated-Open-Orders

They require symbol argument for these api, others are not:
https://www.bitget.com/api-doc/spot/plan/Get-Current-Plan-Order
https://www.bitget.com/api-doc/margin/cross/trade/Get-Cross-Open-Orders
https://www.bitget.com/api-doc/margin/isolated/trade/Isolated-Open-Orders

I think we can update `fetchOpenOrders` and test those parameters.
