### ISSUE TITLE
Binance fetch_tickers do not work properly with symbols parameter

### ISSUE THREAD

**Issue by Alfavisioner** [ccxt/ccxt#20425]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

4.1.91

### Description

**Wrong behavior**
Binance fetch_tickers do not work properly with symbols parameter.
If we pass symbols=['ETHBTC', 'DOTBTC'], it looses symbols parameter and query all markets like symbols=None
After that function parses 2400+ results, filter them and return necessary tickers according to query. Like in emulation mode.

The main issue is with the time:
When fetch_ticker(symbol) takes 0.3 seconds
fetch_tickers(symbols=['ETHBTC', 'DOTBTC']) takes, 2.5 seconds. Like fetch_tickers(symbols=None) 
And all this time spend on parsing results... 6 time slower. It is unacceptable.

**Solution**
I investigated code
class binance
def fetch_tickers(self, symbols: Strings = None, params={}) -> Tickers:

Symbols param is not passed into query.
But binance natively supports separate markets, **the only trick you have to prepare symbols properly**.
https://binance-docs.github.io/apidocs/spot/en/#symbol-order-book-ticker

I added a few lines of code to show a possible solution.
Now function return only 2 markets as expected.
Time practically the same as fetch_ticker
Please, integrate code and correct according to your library standards

### Code

def fetch_tickers(self, symbols: Strings = None, params={}) -> Tickers:

        self.load_markets()
        type = None
        market = None
        symbols = self.market_symbols(symbols, None, True, True, True)
        if symbols is not None:
            first = self.safe_string(symbols, 0)
            market = self.market(first)
        type, params = self.handle_market_type_and_params('fetchTickers', market, params)
        subType = None
        subType, params = self.handle_sub_type_and_params('fetchTickers', market, params)
        query = self.omit(params, 'type')
        defaultMethod = None
        if type == 'option':
            defaultMethod = 'eapiPublicGetTicker'
        elif self.is_linear(type, subType):
            defaultMethod = 'fapiPublicGetTicker24hr'
        elif self.is_inverse(type, subType):
            defaultMethod = 'dapiPublicGetTicker24hr'
        else:
            defaultMethod = 'publicGetTicker24hr'
        method = self.safe_string(self.options, 'fetchTickersMethod', defaultMethod)

	### New code start
        def symbols_to_binance(symbols: Strings):
            symbols_as_string = '","'.join(symbols)
            return f'["{symbols_as_string}"]'

	# Add code to prepare list of symbols without slashes here
        symbols_str = symbols_to_binance(["ETHBTC", "DOTUSDT"])  
        query.update({'symbols': symbols_str})
	### New code end

        response = getattr(self, method)(query)
        return self.parse_tickers(response, symbols)

**Comment by Alfavisioner** [comment]
Also added screenshot from other library how symbols parameter has to be passed
![Request](https://github.com/ccxt/ccxt/assets/44602189/1d265bd7-6e7e-42b3-b7ff-e025851734c1)

**Comment by carlosmiei** [comment]
Hello @Alfavisioner, thanks for reporting it.
You're right, we can do that for the spot call, so we will update it. 

However we can't do the same for perps/options/futures because the endpoint does not accept a list of symbols

https://binance-docs.github.io/apidocs/spot/en/#24hr-ticker-price-change-statistics
https://binance-docs.github.io/apidocs/futures/en/#24hr-ticker-price-change-statistics 
https://binance-docs.github.io/apidocs/delivery/en/#24hr-ticker-price-change-statistics
https://binance-docs.github.io/apidocs/voptions/en/#24hr-ticker-price-change-statistics

**Comment by Alfavisioner** [comment]
If possible only for spot, let is be at least or spot :)

**Comment by carlosmiei** [comment]
@Alfavisioner Of course 🙂 , opened a PR to add it

**Comment by Alfavisioner** [comment]
> @Alfavisioner Of course 🙂 , opened a PR to add it

Thank you.
For perps/options/futures to improve speed i propose to add prefiltration stage
Because parsing of individual tickers is most consuming:

1. do request
2. prefilter
3. parse tickers

Code:

in binance
def fetch_tickers(self, symbols: Strings = None, params={}) -> Tickers:

before starting to parse: 

        def filter_dicts_by_symbol(input_list, symbols_to_keep):
            symbols_to_keep_cleaned = [symbol.replace('/', '') for symbol in symbols_to_keep]
            return [d for d in input_list if d.get('symbol') in symbols_to_keep_cleaned]

        response = filter_dicts_by_symbol(response, symbols)
        result = self.parse_tickers(response, symbols)

Or even better to place it in     
class Exchange
def parse_tickers(self, tickers, symbols: List[str] = None, params={}):

to save on parsing for other exchanges, like Bybit
Eg on Bybit 0,15 second spent to parse tickers, event if we have few symbols..

**Comment by carlosmiei** [comment]
@Alfavisioner Yeah I agree, when the exchange has a lot of markets the parsing takes some time. Will open a different PR to fix it. Thanks for the suggestion.
