### ISSUE TITLE
python: socks proxy usage in async version

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#20420]
### Operating System

python

### Programming Languages

Python

### CCXT Version

4.1.91

### Description

I'm trying to test usage of a socks-proxy with ccxt.

in the sync version - this is pretty straightforward, and passing `"socksProxy": "socks5://localhost:3128/",` works just fine.
Doing the same with the async version however results in (consistent) errors, like `Unclosed connector`, ...

### Code

Using the [proxy usage](https://github.com/ccxt/ccxt/blob/master/examples/py/proxy-usage.py) example script - reduced to the socks proxy stuff:

``` python
import asyncio
import ccxt.pro as ccxt  # noqa: E402


async def example_socks_proxy():
    my_ex = ccxt.kucoin()
    my_ex.socks_proxy = 'socks5://127.0.0.1:3128'  # from protocols: socks, socks5, socks5h
    print(await my_ex.fetch('https://api.ipify.org/'))
    print("DO SOMETHING" + "-" * 30)
    print(await my_ex.fetch('https://api.ipify.org/'))

    await my_ex.close()

asyncio.run(example_socks_proxy())
```

I've intentionally added the "DO Something" line - to show that the error happens on every individual async call.

```
> python proxy-usage.py 
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f6c0c48ced0>
Unclosed connector
connections: ['[(<aiohttp_socks.connector._ResponseHandler object at 0x7f6c0a351e80>, 226491.54044437)]']
connector: <aiohttp_socks.connector.ProxyConnector object at 0x7f6c0a174450>
152.67.xx.36
DO SOMETHING------------------------------
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f6c0a175f10>
Unclosed connector
connections: ['[(<aiohttp_socks.connector._ResponseHandler object at 0x7f6c0a352200>, 226492.176194274)]']
connector: <aiohttp_socks.connector.ProxyConnector object at 0x7f6c0c48ced0>
152.67.xx.36

```

**Comment by xmatthias** [comment]
@ttodua @carlosmiei 
i'm not sure the PR fixes the issue.

re-runing my test code above with the new version (4.1.94) - i still get the following output:

```
152.67.xx.36
DO SOMETHING------------------------------
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff2fa2b87d0>
Unclosed connector
connections: ['[(<aiohttp_socks.connector._ResponseHandler object at 0x7ff2fa2a4e50>, 266619.726652853)]']
connector: <aiohttp_socks.connector.ProxyConnector object at 0x7ff2fa2b86d0>
152.67.xx.36
```

So essentially, it removed the first occurance - but the 2nd one is still there.

**Comment by carlosmiei** [comment]
@xmatthias Thanks once again, will take a look

**Comment by ttodua** [comment]
@xmatthias let us know if you face any issues again

**Comment by xmatthias** [comment]
Thanks, now it's working fine :+1:
