### ISSUE TITLE
futures with different contracts

### ISSUE THREAD

**Issue by ABO3** [ccxt/ccxt#2043]
When fetching the ticker or order book of BTC/USD (exchange: okex), I can only get the weekly futures contract. How can I get biweekly and quarterly contract? Or it is currently impossible in ccxt api?

Thx.

**Comment by kroitor** [comment]
> Or it is currently impossible in ccxt api?

It is possible:

```JavaScript
// this week
okex.fetchTicker('BTC/USD', {'contract_type': 'this_week'})
okex.fetchOrderBookr('BTC/USD', {'contract_type': 'this_week'})

// next week
okex.fetchTicker('BTC/USD', {'contract_type': 'next_week'})
okex.fetchOrderBookr('BTC/USD', {'contract_type': 'next_week'})

// quarter
okex.fetchTicker('BTC/USD', {'contract_type': 'quarter'})
okex.fetchOrderBookr('BTC/USD', {'contract_type': 'quarter'})
```

Use the `contract_type` extra parameter. Let us know if it does not help.

**Comment by ABO3** [comment]
thx, that's helpful

**Comment by kroitor** [comment]
@ABO3 sorry, there was a typo in my previous answer, I've corrected it, with fetchOrderBook, it's the third argument, the second argument is the order book depth limit (can set to None/undefined if not needed).
