### ISSUE TITLE
when will  watchPositions  be available for exchanges

### ISSUE THREAD

**Issue by williamvgam** [ccxt/ccxt#20439]
### Operating System

window

### Programming Languages

python

### CCXT Version

4.1.14

### Description

ccxt.pro watchPositions not available

### Code

exchange= getattr(ccxt_sync, 'binance')({
    'aiohttp_proxy': 'http://127.0.0.1:8001',
    'enableRateLimit': True,
    'newUpdates': False,
    'apiKey': api['apiKey'],
    'secret': api['secret'],
    'options': {'defaultType': 'swap'},
    })
await exchange.watch_positions()
```
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_17860/2528396026.py in <module>
      5     'options': {'defaultType': 'swap'},
      6     })
----> 7 await exchange.watch_positions()

AttributeError: 'binance' object has no attribute 'watch_positions'  

```

**Comment by sc0Vu** [comment]
Hi @williamvgam 

There's watchPositions in the latest version: https://github.com/ccxt/ccxt/blob/master/python/ccxt/pro/binance.py#L2043.

**Comment by williamvgam** [comment]
> Hi @williamvgam
> 
> There's watchPositions in the latest version: https://github.com/ccxt/ccxt/blob/master/python/ccxt/pro/binance.py#L2043.

Yes ,I updated ccxt ,and it works now.  Thank you so much!
