### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by id7crypto** [ccxt/ccxt#20446]
### Programming Languages

Python

### CCXT Version

4.1.94

### Description

While fetching an order info on Kucoin, responseData is sometimes empty, which leads to `dictionary` being None in `get_object_value_from_key_list` and thus raises an error `TypeError: argument of type 'NoneType' is not iterable` when trying to iterate over it.

Suggestion: add a check for `None` at the beginning of `get_object_value_from_key_list` or set a default return to an empty dict `{}` instead of a default `None` in `responseData = self.safe_value(responseData, 0)` in "...\async_support\kucoin.py", line 2353

Traceback:
```
  File "...\ccxt\async_support\kucoin.py", line 2353, in fetch_order
    return self.parse_order(responseData, market)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\ccxt\async_support\kucoin.py", line 2504, in parse_order
    'id': self.safe_string_n(order, ['id', 'orderId', 'newOrderId']),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\ccxt\base\exchange.py", line 812, in safe_string_n
    value = Exchange.get_object_value_from_key_list(dictionary, key_list)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\ccxt\base\exchange.py", line 874, in get_object_value_from_key_list
    filtered_list = list(filter(lambda el: el in dictionary and dictionary[el] != '' and dictionary[el] is not None, key_list))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\ccxt\base\exchange.py", line 874, in <lambda>
    filtered_list = list(filter(lambda el: el in dictionary and dictionary[el] != '' and dictionary[el] is not None, key_list))
                                           ^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @id7crypto, we will add a protecting to prevent this crash, although I think we will fix it at the exchange level.

One question, do you know the best way of reproducing this error?

**Comment by id7crypto** [comment]
> One question, do you know the best way of reproducing this error?

@carlosmiei Basically, it's just creating a limit order, getting its id as a response, and then immediately try to get details about this order. Though, it is possible that some special circumstances are required, like high load on an exchange, as for example during token listing.
Or maybe it happens only with high frequency orders (use `params={'hf': True}`).
