### ISSUE TITLE
Binance receiving error code -2015 while using API keys

### ISSUE THREAD

**Issue by lenak25** [ccxt/ccxt#2044]
Hi,
 
I have created a new Binance account and set its API keys (read info, enable trading, IP access unrestricted).
While trying to connect to my account programmaticly using CCXT, I get the following authorization error: `ccxt.base.errors.ExchangeError: binance: unknown error code: {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}`
OS: Ubuntu 16 (happens on windows as well)
Programming language: Python 3.5 
CCXT version: 1.10.1178

When using `python-binance` library, I successfully connect to my account.

The code I use:
```
from binance.client import Client
import json
import ccxt

data = json.load(open('binance_auth.json'))

client = Client(
    data['secret'],
    data['key'])

api = {
                'apiKey': data['key'],
                'secret': data['secret'],
                'password': None,
      }
ccxtBinance = ccxt.binance(api)

print("python-binance=", client.get_account()) # succeeds
print ("ccxt=",ccxtBinance.fetchBalance())     # fails
```

Thanks,
Lena

**Comment by mkutny** [comment]
Try the following:

```javascript
api = {
                'apiKey': data['secret'],
                'secret': data['key'],
                'password': None,
      }
```

**Comment by lenak25** [comment]
Thanks @mkutny, it works for this account.
I have another Binance account (which was opened a while ago) and I had no problems to connect to it with my original code. Any reason why for some accounts the API key and secret should be swapped, while for others not? Will there be a common solution for all?
Thanks,
Lena

**Comment by mkutny** [comment]
> Any reason why for some accounts the API key and secret should be swapped, while for others not?

They should NEVER be swapped. You just happened to mix them in your `binance_auth.json`.

> I have another Binance account (which was opened a while ago) and I had no problems to connect to it with my original code.

Your `python-binance` won't work with that pair.

**Comment by lenak25** [comment]
You are correct, my mistake.
Thanks, closing this.
