### ISSUE TITLE
Kraken exchange: Can not load positions or place orders.

### ISSUE THREAD

**Issue by caesar3x** [ccxt/ccxt#20441]
### Operating System

Windows

### Programming Languages

JavaScript

### CCXT Version

4.1.91

### Description

I am using ccxt version 4.1.91 for my Electron project. 

My production app was working fine with Kraken Futures exchange but suddenly my app can not get position list or place orders. 

I got error message: BadSymbol: krakenfutures does not have market symbol BTC/USD:USD

(My app is opening and worked fine in some last hours)

Does anyone get the same issue?

### Code

```
  

```

**Comment by Dan-krm** [comment]
Hi @caesar3x I experienced something similar, it looks like kraken is undergoing maintenance tonight, hopefully everything is running back to normal soon:
https://twitter.com/krakensupport/status/1737321929563111554?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Etweet

**Comment by caesar3x** [comment]
Hi @Dan-krm , thank you for your information.

**Comment by Dan-krm** [comment]
@caesar3x Kraken looks like it's working again:
```
kraken.createOrder (ETH/USD, market, buy, 0.01)
2023-12-21T08:42:23.509Z iteration 0 passed in 1136 ms

{
  id: 'OI466V-5KJWR-Z7Z77I',
  info: {
    txid: [ 'OI466V-5KJWR-Z7Z77I' ],
    descr: { order: 'buy 0.01000000 ETHUSD @ market' }
  },
  symbol: 'ETH/USD',
  type: 'market',
  timeInForce: 'IOC',
  postOnly: false,
  side: 'buy',
  amount: 0.01,
  trades: [],
  fees: []
}
```

**Comment by caesar3x** [comment]
Hi @Dan-krm , it still not working from my app. I still getting the same issues. Are you using JS library with reactjs too?

**Comment by Dan-krm** [comment]
It looks like there was a KYC update recently, so if you haven't already I would recommend checking your eligibility then following these steps to try and get your kraken futures account working:
https://support.kraken.com/hc/en-us/articles/360023786632-Kraken-Futures-eligibility
https://support.kraken.com/hc/en-us/articles/360022618012-How-to-unlock-futures-trading

The kraken futures API says that it's currently operational: https://status.kraken.com/

Here is my test using the krakenfutures sandbox with the JS library:
```
krakenfutures.createOrder (BTC/USD:USD, limit, buy, 0.0001, 35000)
2023-12-21T20:57:37.338Z iteration 0 passed in 782 ms

{
  info: {
    order_id: '073de7ff-ae7f-45bd-9c1a-c9df7a0d5e2c',
    status: 'placed',
    receivedTime: '2023-12-21T20:57:38.272Z',
    orderEvents: [
      {
        order: {
          orderId: '073de7ff-ae7f-45bd-9c1a-c9df7a0d5e2c',
          cliOrdId: null,
          type: 'lmt',
          symbol: 'PF_XBTUSD',
          side: 'buy',
          quantity: '0.0001',
          filled: '0',
          limitPrice: '35000',
          reduceOnly: false,
          timestamp: '2023-12-21T20:57:38.272Z',
          lastUpdateTimestamp: '2023-12-21T20:57:38.272Z'
        },
        reducedQuantity: null,
        type: 'PLACE'
      }
    ]
  },
  id: '073de7ff-ae7f-45bd-9c1a-c9df7a0d5e2c',
  timestamp: 1703192258272,
  datetime: '2023-12-21T20:57:38.272Z',
  symbol: 'BTC/USD:USD',
  type: 'limit',
  timeInForce: 'gtc',
  postOnly: false,
  reduceOnly: false,
  side: 'buy',
  price: 35000,
  amount: 0.0001,
  cost: 0,
  filled: 0,
  remaining: 0.0001,
  status: 'open',
  fees: [],
  trades: []
}
```

### If it's still not working:

If you sign in to https://futures.kraken.com/ Does it show this in the bottom left corner?

![image](https://github.com/ccxt/ccxt/assets/83686770/a5091e52-7640-41af-8552-7fed517c45cd)

If it does your region might be restricted or you might not pass some of their regulatory requirements but you can reach out to their client engagement team for more information

Some exchanges have been preventing trading certain perpetual trading pairs through their API so there's a chance Kraken has started doing that for the live BTC/USD:USD trading pair

Lastly could you share your verbose output following these instructions? https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
