### ISSUE TITLE
Withdraw adress

### ISSUE THREAD

**Issue by artbred** [ccxt/ccxt#2046]
Hello im working on JS.I faced problem with deposit addresses.So if i want to deposit coin for the first time (if i write bittrex.fetchdepositadress()) return empty address. But in bittrex api documentation there is a https://bittrex.com/api/v1.1/account/getdepositaddress?apikey=API_KEY&currency=VTC . Can you please help me and tell if its possible to generate new address using ccxt,thank you

**Comment by kroitor** [comment]
@artbred have you resolved it on your own? We would be happy if you report back for other users to make use of it as well. Thx! )

**Comment by artbred** [comment]
I have no idea how i solved that. If i have these problem for second time gonna report
