### ISSUE TITLE
Coinbase fetchOpenOrders for stops not returning price, stop-price

### ISSUE THREAD

**Issue by BHruska** [ccxt/ccxt#20487]
### Operating System

Windows 11

### Programming Languages

Python

### CCXT Version

CCXT Version: 4.1.95

### Description

When using fetchOpenOrders for coinbase stop orders, the price, stopprice, triggerprice values are not being returned.  I can see the prices in the INFO section, but they aren't being brought down into the ccxt fields.

coinbase - stop on exchange
![coinbase - stop on exchange](https://github.com/ccxt/ccxt/assets/3506963/225a11f3-58cd-480f-a95a-edd8716f18a8)

what i got returned when i placed the stop
![coinbase - what i got when i placed the stop](https://github.com/ccxt/ccxt/assets/3506963/205f6e93-6760-4ff4-8ab2-0db17e11538b)

when i get back from fetchOpenOrders 
![coinbase - looking at info of order](https://github.com/ccxt/ccxt/assets/3506963/8030dfac-bbcc-4ac4-ac9b-8b6a697d5c04)

NOTE:
"price": null,
"stopPrice": null,
 "triggerPrice": null,

second image

### Code

```
  

```

**Comment by Dan-krm** [comment]
Hi @BHruska thanks for reporting, I opened a pull request that will resolve this issue
