### ISSUE TITLE
Delta Exchange close_positions and close_all positions not available

### ISSUE THREAD

**Issue by Vortex1806** [ccxt/ccxt#20498]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

We use delta exchange for algorithms but due to lack of close_positions or atleast close_allpostions it is highly difficult to run the strategy

### Describe the solution you'd like

I would like it to have a close position function in which we can pass the symbol and that position gets closed or atleast a close all position from which we can close all positions it is aldready available on docs but i was unable to figure out how to make a function in cctx.delta 
Here is the documentation
https://docs.delta.exchange/#close-all-positions 

### Describe alternatives you've considered

https://docs.delta.exchange/#close-all-positions

here is the documentation of needed

**Comment by Dan-krm** [comment]
Hey @Vortex1806 I opened a pull request that will add closeAllPositions to Delta
