### ISSUE TITLE
New Exchange: CEX.io Plus

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#20495]
### Exchange Name

CEX.io Plus

### URL of the Exchange

https://plus.cex.io/

### URL of the Exchange's API docs

https://docs.plus.cex.io/#introduction

### Why should this exchange be implemented?

CEX.io Plus looks like new exchange with separated markets from CEX.io and different API
https://blog.cex.io/news/trading-functionality-moved-to-exchange-plus-33467
Probably legacy CEX.io exchange will be deprecated in future

**Comment by ndubel** [comment]
Looks like current API we use in ccxt will be depricated in near future. I can't even find API docs for it.
https://trade.cex.io/docs/#introduction in Latest Changes section:

> REST API, WebSocket API - CEX.IO Exchange Plus product has been rebranded as CEX.IO Spot Trading, accompanied by new REST and WebSocket (WS) API endpoints for both public and private interactions.
> 
> Clients are advised to transition to the new API endpoints, as the old endpoints will be deactivated in the near future. The specific dates for the deactivation will be communicated separately.

@kroitor @frosty00 @carlosmiei

**Comment by carlosmiei** [comment]
@ndubel Thanks for bringing our attention to this, we will try to sort this out.
