### ISSUE TITLE
Error in basic-chart.py

### ISSUE THREAD

**Issue by TomAshley303** [ccxt/ccxt#2050]
I tried to run https://github.com/ccxt/ccxt/blob/master/examples/py/basic-chart.py which gave the error:

Kraken BTC/USD 1h chart:
Traceback (most recent call last):
  File "basic-chart.py", line 46, in <module>
    last = print_chart(kraken, 'BTC/USD', '1h')
  File "basic-chart.py", line 40, in print_chart
    print("\n" + asciichart.plot(series[-120:], {'height': 20}))  # print the chart
AttributeError: module 'asciichart' has no attribute 'plot'

**Comment by kroitor** [comment]
Make sure there's the `asciichart.py` nearby that script: https://github.com/ccxt/ccxt/blob/master/examples/py/asciichart.py
Not from the `asciichart` pip package.
Let me know if it does not help.

**Comment by lvthillo** [comment]
@kroitor I was facing the same issue. Followed your solution but now I have: 
```
    print(plot(series))
NameError: name 'series' is not defined
```
