### ISSUE TITLE
Example PY Page Links To Erroneous Code

### ISSUE THREAD

**Issue by TomAshley303** [ccxt/ccxt#2051]
The page https://github.com/ccxt/ccxt/tree/master/examples/py links to the file https://github.com/co3k/co3k-crypto-currency-note/blob/master/Untitled.ipynb under "See Also." The code in that file no longer works and has been deprecated.

An issue for that has been posted here: https://github.com/co3k/co3k-crypto-currency-note/issues/1

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/commit/d205572eb0c6d6f77fe771b16fc9d6d166dc33a3
