### ISSUE TITLE
Missing time info in Bingx watch_ohlcv response for "swap"

### ISSUE THREAD

**Issue by kadiraltan** [ccxt/ccxt#20515]
### Operating System

Linux/Windows

### Programming Languages

Python

### CCXT Version

4.1.96

### Description

Hi,

I've encountered an issue where the Bingx watch_ohlcv response returns "None" for the time information specifically for 'swap'. For example: 
`[[None, 43982.4, 44000.0, 43830.0, 43870.0, 1002.9271]]`

To cross-check:
1) I ran the same code for "spot", and it worked correctly.
2) I changed the exchange to Binance, and both spot and futures worked well.
Given these, and considering I'm not a professional coder, I assume the issue isn't about a missing Bingx option etc.

While investigating the issue:
1) The WebSocket K-Line Subscription via the Bingx API doc sample code returned "T" for time (unlike "t" used in spot):
`{"code":0,"dataType":"BTC-USDT@kline_1m","s":"BTC-USDT","data":[{"c":"43980.1","o":"43980.1","h":"43980.1","l":"43980.0","v":"1.9033","T":1703290380000}]}
`
2) In ccxt/pro/bingx.py, the watch_ohlcv function uses the parse_ws_ohlcv function, which returns the following:
```
return [
      self.safe_integer(ohlcv, 't')
      ...
]
```
When I changed "t" to "T", the time information appeared in the watch_ohlcv response for "swap".

Thanks in advance.

### Code

```
import ccxt.pro
from asyncio import run

print('CCXT Pro version', ccxt.pro.__version__)
async def main():
    exchange = ccxt.pro.bingx({
        'newUpdates': False,
        'options': {
            'OHLCVLimit': 500,
            'defaultType': 'swap' # swap , spot, margin, future, delivery
        }
    })

    await exchange.load_markets()

    while True:
        try:
            ohlcvs = await exchange.watch_ohlcv('BTC/USDT:USDT', '1h', None, None)
            print(ohlcvs)
        except Exception as e:
            print(type(e).__name__, str(e))
            break
    await exchange.close()

run(main())
```

**Comment by Dan-krm** [comment]
Hi @kadiraltan thanks for bringing our attention to this, I opened a pull request that will resolve the issue
