### ISSUE TITLE
Enhancement/Fix Suggestion for Phemex set_leverage Function

### ISSUE THREAD

**Issue by niewiemczego** [ccxt/ccxt#20513]
### Operating System

Mac OS

### Programming Languages

Python

### CCXT Version

4.0.87

### Description

I am writing to suggest an improvement to the set_leverage function within the Phemex integration of the CCXT library. Currently, the function enforces a leverage range of 1 to 100. This limitation is implemented as follows:

```python
if (leverage < 1) or (leverage > 100):
    raise BadRequest(self.id + ' setLeverage() leverage should be between 1 and 100')
```

However, this range does not accommodate scenarios where a negative leverage value is used to indicate cross margin trading, while a positive value indicates isolated margin trading. This feature is particularly relevant for USDT-based symbols.

I propose adjusting the leverage range to -100 to 100. This change will allow developers to seamlessly switch between cross and isolated margin types for USDT symbols, enhancing the flexibility and efficiency of the function. The revised code snippet would be:

```python
if (leverage < -100) or (leverage > 100):
    raise BadRequest(self.id + ' setLeverage() leverage should be between -100 and 100')
```

This modification would significantly streamline the trading operations and provide a more intuitive interface for developers working with the Phemex API through the CCXT library.

**Comment by samgermain** [comment]
Thank you for letting us know, I linked a PR that will allow this, and will add a way to use cross leverage via `params["marginMode"]` in the future
