### ISSUE TITLE
How to set up a CORS proxy?

### ISSUE THREAD

**Issue by GopiAnnan** [ccxt/ccxt#2052]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:
`  let ex = new ccxt.kraken();
    ex.proxy = 'https://crossorigin.me/';
    console.log(ex.loadMarkets());`

![connection refused](https://user-images.githubusercontent.com/20523260/36654182-b6e860b4-1a88-11e8-8c90-6b600fdef4d8.png)
`let ex = new ccxt.kraken();
    //ex.proxy = 'https://crossorigin.me/';
    ex.proxy = 'https://localhost:8081/';
    console.log(ex.loadMarkets());`
![connection refused1](https://user-images.githubusercontent.com/20523260/36654220-0ab736fc-1a89-11e8-8f12-cc55f941786d.png)

Have tried with both proxy options, in both I am getting 403, that too with all exchanges.

Also, To connect, Bittrext and yobit
Have tried with personall ApiKey and Secret  , but still same the connection refused.

Hope connecting through localhost via proxy should do the trick,  Not sure anything I am missing.

**Comment by kroitor** [comment]
1. `https://crossorigin.me/` never worked for me, I test with `https://cors-anywhere.herokuapp.com/`
2. For `localhost:8081` you have to make sure you're running a node CORS proxy on that port...
3. The easiest way is to learn from this example: https://github.com/ccxt/ccxt/blob/master/examples/html/basic-cors-proxy.html

```html
<!DOCTYPE HTML>
<html>
<head>
    <title>CCXT Basic example for the browser</title>
    <script type="text/javascript" src="https://unpkg.com/ccxt"></script>
    <script>

        document.addEventListener ("DOMContentLoaded", function () {

            alert ('ccxt version ' + ccxt.version + ' supporting '+ ccxt.exchanges.length.toString () + ' exchanges');

            const proxy = 'https://cors-anywhere.herokuapp.com/'
            const exchange = new ccxt.bittrex ({ 'proxy': proxy })
            const symbol = 'ETH/BTC'

            exchange.fetchTicker (symbol).then (ticker => {

                const text = [
                    exchange.id,
                    symbol,
                    JSON.stringify (ticker, undefined, '\n\t')
                ]

                document.getElementById ('content').innerHTML = text.join (' ')
            })

        })
    </script>
</head>
<body>
<h1>Hello, CCXT!</h1>
<pre id="content"></pre>
</body>
</html>
```

Let us know if the above does not help.

**Comment by texxxo** [comment]
My app is running on Port 1337 locally and I have setup Cors like described above, What i'm missing here?

`componentDidMount() {
        (async () => {
            const exchanges = ["poloniex"];
            //const exchanges = ["gdax", "poloniex", "upbit"];
            //const exchanges = ["gdax", "poloniex", "upbit"];
            //const exchanges = ["gdax", "poloniex", "upbit"];

            const proxy = 'https://cors-anywhere.herokuapp.com/';
            const symbol = "ETH/BTC";
            const tickers = {};

            await Promise.all(
                exchanges.map(
                    exchangeId =>
                        new Promise(async (resolve, reject) => {
                            const exchange = new ccxt[exchangeId]({ 'proxy': proxy })({ enableRateLimit: true });

                            while (true) {
                                const ticker = await exchange.fetchTicker(symbol);
                                tickers[exchangeId] = ticker;
                                this.setState({ tickers });
                            }
                        })
                )
            );
        })();
    }`

**Comment by kroitor** [comment]
> What i'm missing here?

Hard to tell without a proper description of what the issue is. Can you elaborate?

> My app is running on Port 1337 locally and I have setup Cors like described above

The above post describes how to set up CORS on your localhost. So if you have set it up with localhost on port 1337, then the proxy URL in your code should be 

```JavaScript
// const proxy = 'https://cors-anywhere.herokuapp.com/'; // wrong
const proxy = 'http://localhost:1337/'; // correct
```

Have you read this: https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin ?

**Comment by texxxo** [comment]
You are right I need to read carefully before asking an question, Thanks anyway I think I can do it now.

**Comment by texxxo** [comment]
Do we need this npm package to get Cors working? https://www.npmjs.com/package/cors-anywhere

**Comment by kroitor** [comment]
@texxxo there's a few options:
- use a publicly available CORS server (can be slow and unreliable) `https://cors-anywhere.herokuapp.com/`
- run your own on `http://localhost:1337/` – for that you need any CORS proxy package, the `cors-anywhere` might do the job, depends on your particular tasks, but, i can't recommend any package in particular, because to me they're all the same mostly.

**Comment by texxxo** [comment]
@kroitor  Thanks maybe you have your favorite package that you use in production and is ok, what would that be?

**Comment by kroitor** [comment]
> Thanks very informative! maybe you have your favorite package that you use in production and is ok, what would that be?

I'd say `cors-anywhere` npm package is ok.

> Ps. can I use https://cors-anywhere.herokuapp.com/ when testing on localhost?_

The question itself isn't really correct. In general, when you use a CORS proxy, the information goes this way and back:

Your "localhost" ←→ CORS proxy ←→ internet ←→ exchange.

So, when you use `https://cors-anywhere.herokuapp.com/`, you're using someone's public CORS proxy server (not the same as `cors-anywhere` npm package). 

Basically `https://cors-anywhere.herokuapp.com/` is a version of `cors-anywhere` taken by somebody and launched as a public service. It isn't a guaranteed 24/7 service, so you should not rely on `https://cors-anywhere.herokuapp.com/` (you can try it for testing and that's it). If you want more control, you should run your own cors proxy (whether on your remote server or on your localhost).

So, your options are:

- Your "localhost" ←→ https://cors-anywhere.herokuapp.com/ ←→ internet ←→ exchange.
- Your "localhost" ←→ `cors-anywhere` package on your server/localhost ←→ internet ←→ exchange.

**Comment by kroitor** [comment]
> Becuese like we talked a time ago above when I use `const proxy = 'http://localhost:1337/'; // correct` I get anywyays cors error....hmm.

In order to use `http://localhost:1337/` you have to do a very certain procedure of several steps (to setup a CORS proxy on your localhost) – did you do that procedure precisely? Because if you haven't done anything but just `const proxy = 'http://localhost:1337/';` – that won't work. The procedures are described here: https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin

**Comment by texxxo** [comment]
**This is the original lines in my app**
`const port = process.env.PORT || "1337";
app.listen(port, () => console.log(`Server listening on port ${port}`));

**This is how I rewrite it to use with cors-anywhere package**
`const port = (process.env.PORT.length > 2) ? parseInt(process.env[2]) : 1337;
require('cors-anywhere').app.listen(port, () => console.log(`Server listening on port ${port}`));`


**Is this the correct direction what I'm trying here?**

**Comment by kroitor** [comment]
> ### Is this the correct direction what I'm trying here?

Not really. You need two things:

1. Get the CORS proxy script from the Install page running on your localhost without editing it at all: https://github.com/ccxt/ccxt/wiki/Install#nodejs-cors-proxy

2. Edit your CCXT code to instantiate the exchange like so:

```JavaScript
const proxy = 'http://localhost:8080/ // your address of your localhost CORS proxy
const id = 'bitmex'
const exchange = new ccxt[id] ({ proxy }) // requests will go via your localhost CORS proxy
```

Let me know if that clarifies it or not. Feel free to ask further questions, if you have more.

**Comment by texxxo** [comment]
Thanks @kroitor now more clear for me how it works! But with React it is a lil bit more tricky because I select the exchange dynamically from an drop-down menu and then it shows up on the browser what I need..I have now the cors-anywhere running on my PORT and also added
 `const proxy = 'http://localhost:1337/'` into my component

This is how the section where the exchange selected in the drop-down is used dynamically I also added `"proxy": proxy` as you can see, for now only the Bittrex  API is hard coded becuese the API's are for now not dynamically but I use bittrex to check and get CORS + API working, here the section I talked about.

`await Promise.all(
                exchanges.map(
                    exchangeId =>
                        new Promise(async (resolve, reject) => {
                            const exchange = new ccxt[exchangeId]({
                                'apiKey': 'MyAPI',
                                'secret': 'MyAPI',
                                'enableRateLimit': true,
                                'proxy': proxy // Here is the proxy variable like described on the one site I added above.
                            });

                            const ticker = await exchange.fetchTicker(symbol);
                            tickers[exchangeId] = ticker;
                            this.setState({ tickers });
                        })
                )
            );`

**Comment by kroitor** [comment]
@texxxo ok, however, from your comment it is not clear if you now have it working or is there still a problem with it?

**Comment by texxxo** [comment]
@kroitor Sorry for being unclear. The problem is now solved I had to run the app like it was on port 1337 and the cors-anywhere separately on 8080. Now it works, Thank you so much!

**Comment by kroitor** [comment]
> The problem is now solved I had to run the app like it was on port 1337 and the cors-anywhere separately on 8080.

The two numbers should be the same, however. I mean:
- your `const proxy = 'http://localhost:1337/` should be `const proxy = 'http://localhost:8080/` if your CORS proxy is running on port 8080
- your `const proxy = 'http://localhost:1337/` should be `const proxy = 'http://localhost:1337/` if your CORS proxy is running on port 1337

**Comment by texxxo** [comment]
Yes that was exactly what fixed my problem. Thanks man! :)
