### ISSUE TITLE
Bitget OHLCV issues after 4.1.87

### ISSUE THREAD

**Issue by x1i4b1x2** [ccxt/ccxt#20521]
### Programming Languages

JavaScript

### Description

After 4.1.87 bitget OHLCV futures “1d” is having problems. 4.1.86 is all good.

if I'm taking a historical 1d like yesterday or any, it doesn't fetch the correct timestamp. this happens starting from 4.1.87. 4.1.86 is working correctly

bitget.fetchOHLCV(BTC/USDT:USDT, 1d, 1702684800000) or bitget.fetchOHLCV(BTC/USDT:BTC, 1d, 1702684800000)

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @x1i4b1x2, thanks for letting us know, we have recently updated bitget to v2 so it might be related to that. We will take a look and let you know asap.

**Comment by carlosmiei** [comment]
Hello again @x1i4b1x2,

Previously, we were using this endpoint:

https://api.bitget.com/api/mix/v1/market/candles?symbol=BTCUSDT_UMCBL&limit=5&granularity=1Dutc&startTime=1702913911222&endTime=1703345911222

Now we're using this one: 

https://api.bitget.com/api/v2/mix/market/candles?symbol=BTCUSDT&granularity=1D&productType=USDT-FUTURES 

And yes the v1 returned the timestamps in the UTC time, and the v2 uses a different format. We will check if we can restore the timestamp format in v2.

**Comment by x1i4b1x2** [comment]
Thank you!

Updated to the last version and bitget BTC/USD:BTC is reporting enormous volume in OHLCV
