### ISSUE TITLE
Bingx watch_ohlcv can not set market type to "swap" successfully

### ISSUE THREAD

**Issue by kadiraltan** [ccxt/ccxt#20533]
### Operating System

not relevant

### Programming Languages

Python

### CCXT Version

4.1.97

### Description

Hi,

The watch_ohlcv function in pro/bingx.py does not provide the "time" value for "swap" in the response, but instead returns None. E.g.,
`[[None, 43725.2, 43894.2, 43719.8, 43831.0, 581.0491]].
`
The root cause is that Bingx sends the OHLCV time in the 'T' parameter for "swap", as opposed to the expected "t" used in "spot". This bug was addressed and fixed in the previous [issue](https://github.com/ccxt/ccxt/issues/20515) I reported.

However, for this fix to work, market['spot'] must be set to false (as seen in the fixed code), which is not the case in the current version.

As far as I can identify, this issue is caused by a mistake in the handle_ohlcv function in pro/bingx.py. The mistake is in the following line:
`marketType = client.url.find('swap') >= 'swap' if 0 else 'spot'
`
It should be corrected to:
`marketType = 'swap' if client.url.find('swap') >= 0 else 'spot'
`
This correction successfully sets market['spot'] to false and returns the correct value in watch_ohlcv:
`[[1703379600000, 43725.2, 43897.6, 43719.8, 43860.1, 916.6858]]
`

Besides the handle_ohlcv function, the exact same line containing the same mistake is also present in handle_order_book and handle_trades within pro/bingx.py. However, I have not tested its impact on these functions, so my explanation is specific to watch_ohlcv.

Thanks

### Code

```
import ccxt.pro
from asyncio import run

print('CCXT Pro version', ccxt.pro.__version__)

async def main():
    exchange = ccxt.pro.bingx({
        'newUpdates': False,
        'options': {
            'OHLCVLimit': 500,
            'defaultType': 'swap', # swap , spot, margin, future, delivery
        }
    })
    print(exchange.options)
    print(exchange.options['defaultType'])

    await exchange.load_markets()
    while True:
        try:
            ohlcvs = await exchange.watch_ohlcv(symbol='BTC/USDT:USDT', timeframe='1h', since=None, limit=None,params={})
            print(ohlcvs)
        except Exception as e:
            print(type(e).__name__, str(e))
            break
    await exchange.close()

run(main())
```

**Comment by Dan-krm** [comment]
Hey @kadiraltan thanks for pointing this out and finding the specific issue, the ternary operator we were using for `marketType` in TypeScript was a bit too complex to be handled and transpiled to python correctly. I opened a pull request that adjusts the implementation so that the python version will work as expected. The new python code will look like this:
```python
isSwap = client.url.find('swap') >= 0
marketType = 'swap' if isSwap else 'spot'
```
