### ISSUE TITLE
Error: binance watchOHLCVForSymbols() is not supported yet

### ISSUE THREAD

**Issue by hodlerhacks** [ccxt/ccxt#20540]
### Operating System

Windows

### CCXT Version

4.1.97

### Description

Using the CCXT sample code (see below), I'm getting the following error:

NotSupported: binance watchOHLCVForSymbols() is not supported yet

### Code

```
const ccxt = require('ccxt');

async function example() {
    const binance = new ccxt.pro.binance({});
    const subscriptions = [
        ['BTC/USDT', '5m'],
        ['ETH/USDT', '5m'],
        ['BTC/USDT', '1h'],
    ];
    while (true) {
        const ohlcv = await binance.watchOHLCVForSymbols(subscriptions);
        console.log(ohlcv);
    }
}

example();
```

**Comment by carlosmiei** [comment]
Hello @hodlerhacks, yeah it seems that it was temporarily removed because it was not working exactly as expected but we will try to restore it soon. Thanks for reporting it and sorry for the inconvenience.

**Comment by hodlerhacks** [comment]
Hi @carlosmiei, no worries and thanks for letting me know.

**Comment by sc0Vu** [comment]
@carlosmiei the has['watchOHLCVForSymbols '] is true in some exchanges, should we set to false?

**Comment by carlosmiei** [comment]
> @carlosmiei the has['watchOHLCVForSymbols '] is true in some exchanges, should we set to false?

@sc0Vu yes will update it

**Comment by suenot** [comment]
Any updates? I have the same message.

**Comment by samgermain** [comment]
> Any updates? I have the same message.

The method is implemented on okx, and deribit, so unless you are using one of those exchanges, then you should be receiving this message, and you will need to use `watchOHLCV` instead or you can look at [calculating your own OHLCVs](https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual#watchohlcv)
