### ISSUE TITLE
BingX create order futures problem

### ISSUE THREAD

**Issue by xerno0om** [ccxt/ccxt#20548]
### Operating System

Windows 11

### Programming Languages

Python

### CCXT Version

4.0.29

### Description

I can't open an order in Perpetual Futures, I use the same (create_market_order) for bybit and kucoin and it worked fine, but when I run the code it tells me ccxt.base.errors.ExchangeError: bingx { "code ": 100004,"msg": "Authorization denied because the API key was created without authorization", "success": false, "timestamp": 1703485688822}
in my API on BingX I only checked "perpetual futures trading", ...so the code wants to open in "Spot trading", how can I make it open in "perpetual futures trading"

### Code

```
  import ccxt

exchange = ccxt.bingx({
    'apiKey': 'apiKey',
    'secret': 'secret',
    'adjustForTimeDifference': True,
})


symbol = 'BTC-USDT'
cost = 10.00
Side = 'SHORT'

order = exchange.create_market_order(symbol, Side, cost, params={'leverage': 74})
print(order)

```

**Comment by xerno0om** [comment]
I tried to do :

```
import ccxt
symbol = 'BTC/USDT:USDT'

exchange = ccxt.bingx({
    'apiKey': 'key',
    'secret': 'secret',
    'options': {
        'adjustForTimeDifference': True,
        'defaultType': 'swap',
    },
})
exchange.verbose = True
order = exchange.create_order(symbol, "market", 'sell', 0.0001, {
    'PositionSide': 'SHORT'
})
print(order)
```

and 

```
order = exchange.create_market_order(symbol, "market", 'sell', 0.0001, {
    'PositionSide': 'SHORT'
})
print(order)
```

and he tells me :
ccxt.base.errors.BadRequest: bingx {"code":80014,"msg":"Invalid parameters, err:Key: 'PlaceOrderRequest.ReqOrderData.PositionSide' Error:Field validation for 'PositionSide' failed on the 'required' tag","data":{}}

I simply want to open an order in market and perpetual futures, help me

**Comment by tbehzad76** [comment]
I think your problem is because of leverage you can set leverage like this
```
bingx.set_leverage(leverage=10, symbol, params={"marginMode": "cross", 'side': 'LONG'})
bingx.set_leverage(leverage=10, symbol, params={"marginMode": "cross", 'side': 'SHORT'})
```

**Comment by xerno0om** [comment]
> I think your problem is because of leverage you can set leverage like this
> 
> ```
> bingx.set_leverage(leverage=10, symbol, params={"marginMode": "cross", 'side': 'LONG'})
> bingx.set_leverage(leverage=10, symbol, params={"marginMode": "cross", 'side': 'SHORT'})
> ```

No when I run the script even without params={'leverage': 74}, it wants to do spot trading, so it tells me
```
{"code":100004,"msg":"Permission denied as the API key was created without the permission","success":false,"timestamp":1703493028133}
```
I must add or modify what for it makes me perpetual futures?

**Comment by sc0Vu** [comment]
Hi @xerno0om 

You can use unified symbol like `BTC/USDT:USDT` to create order. For the position side, the param might be `positionSide`, they probably use different name tag in server data model.

**Comment by xerno0om** [comment]
it's good I found how to open a position in perpetual futures in market :
```
import ccxt

symbol = 'BTC-USDT'
cost = 1.00
Side = 'SHORT'

exchange = ccxt.bingx({
    'apiKey': 'x',
    'secret': 'x',
    'options': {
        'adjustForTimeDifference': True,
        'defaultType': 'swap',
    },
})
exchange.verbose = True
exchange.create_order(symbol, "market", 'sell', 0.0001, 30000, {
    'positionSide':'SHORT',
})
```

I was inspired by this code that I found on another issue, he opens a position in perpetual futures in limit :
```
https://github.com/ccxt/ccxt/issues/19422
```
```
import ccxt

symbol = 'BTC-USDT'
cost = 1.00
Side = 'SHORT'

exchange = ccxt.bingx({
    'apiKey': 'x',
    'secret': 'x',
    'options': {
        'adjustForTimeDifference': True,
        'defaultType': 'swap',
    },
})
exchange.verbose = True
exchange.create_order(symbol, "limit", 'sell', 0.0001, 30000, {
    'triggerPrice': '30000',
    'positionSide':'SHORT',
})
```

**Comment by Asho198967** [comment]
how to make TP and SL?

**Comment by bluecloudfloat** [comment]
Sorry bro, how to close the order then?
I suspect this is make an close order? because you input "sell"
exchange.create_market_order(symbol, 'sell', 0.0001, 30000, {
    'positionSide':'SHORT',
})

**Comment by Dan-krm** [comment]
@bluecloudfloat 
You shouldn't need to set the `positionSide` that is handled by this logic:
```
let positionSide = undefined;
if (reduceOnly) {
    positionSide = (side === 'buy') ? 'SHORT' : 'LONG';
} else {
    positionSide = (side === 'buy') ? 'LONG' : 'SHORT';
}
request['positionSide'] = positionSide;
```
To close a derivative position you should set the `reduceOnly` param to true, this should close the position for you:
```
exchange.create_market_order(symbol, 'buy', 0.0001, 30000, {
    'reduceOnly':true,
})
```
