### ISSUE TITLE
Bitget OHLCV massive coin volume futures

### ISSUE THREAD

**Issue by x1i4b1x2** [ccxt/ccxt#20556]
### Description

Also refer to this: https://github.com/ccxt/ccxt/issues/20521

Updated to the last version and bitget BTC/USD:BTC is reporting enormous volume in OHLCV. Probably is the number of contract instead of the number of coins

### Code

```
  

```

**Comment by samgermain** [comment]
What method are you using (`fetchOHLCV`, `watchOHLCV`)?

**Comment by x1i4b1x2** [comment]
fetchOHLCV

**Comment by carlosmiei** [comment]
@x1i4b1x2 Hello, thanks for reporting it, you're right this is a leftover from the V1 version and we recently migrated bitget to v2. Will be fixed asap.
