### ISSUE TITLE
MEXC BEP20 network update

### ISSUE THREAD

**Issue by marcellinuskristanto** [ccxt/ccxt#20554]
### Operating System

Windows

### CCXT Version

4.1.91

### Description

MEXC network for BEP20 should be `BNB Smart Chain(BEP20)` instead of `BNBSmartChain(BEP20)` in here https://github.com/ccxt/ccxt/blob/4.1.98/js/src/mexc.js#L448

### Code

```
// this works
await exchange.createDepositAddress("BNB", {network: "BNB Smart Chain(BEP20)"})

// this doesn't work, returning {"msg":"coin not exist","code":10232}
await exchange.createDepositAddress("BNB", {network: "BEP20"})
```

**Comment by Dan-krm** [comment]
Hi @marcellinuskristanto I opened a pull request to resolve the issue
