### ISSUE TITLE
bingx close position problem

### ISSUE THREAD

**Issue by tbehzad76** [ccxt/ccxt#20551]
### Operating System

ubuntu

### Programming Languages

Python

### CCXT Version

4.1.98

### Description

hi guys,
I have two positions on a symbol (E.g. BTC/USDT:USDT)
when I want to close one of position (E.g. LONG position)
after run my code close all my position
please help me

### Code

```
bingx = ccxt.bingx({
    'apiKey': config.BINGX_API_KEY,
    'secret': config.BINGX_SECRET_KEY,
})
symbol = 'BTC/USDT:USDT'

close = bingx.close_position(symbol=symbol, side='buy')
print(close)
```

**Comment by carlosmiei** [comment]
Hello @tbehzad76,
In this case `side` is not used by the exchange and closes every position associated with that market. If you want to close only one side of the position, you can do it by placing an order with the `reduceOnly` flag in `params`

**Comment by tbehzad76** [comment]
Please show me how it works with an example
