### ISSUE TITLE
AttributeError 'Retry' object has no attribute 'method_whitelist'

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#20561]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

4.1.99

### Description

For every method I am unable to retrieve any data through various exchanges. It seems to be only the case when api keys are passed into the ccxt class. 

It does seem to be working on my other computer, so also not sure whether it is a local error. 

### Code

```
  
client = ccxt.bybit({'apiKey': "", 'secret': ""})
client.fetch_balance()
```
Traceback (most recent call last):

  Cell In[14], line 1
    client.fetch_balance()

  File ~\anaconda3\lib\site-packages\ccxt\kucoinfutures.py:1761 in fetch_balance
    response = self.futuresPrivateGetAccountOverview(self.extend(request, params))

  File ~\anaconda3\lib\site-packages\ccxt\base\types.py:34 in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:3318 in request
    return self.fetch2(path, api, method, params, headers, body, config)

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:3315 in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File ~\anaconda3\lib\site-packages\ccxt\base\exchange.py:590 in fetch
    response = self.session.request(

  File ~\anaconda3\lib\site-packages\requests\sessions.py:587 in request
    resp = self.send(prep, **send_kwargs)

  File ~\anaconda3\lib\site-packages\requests\sessions.py:701 in send
    r = adapter.send(request, **kwargs)

  File ~\anaconda3\lib\site-packages\requests\adapters.py:487 in send
    resp = conn.urlopen(

  File ~\anaconda3\lib\site-packages\urllib3\connectionpool.py:805 in urlopen
    if retries.is_retry(method, response.status, has_retry_after):

  File ~\anaconda3\lib\site-packages\urllib3\util\retry.py:343 in is_retry
    if not self._is_method_retryable(method):

  File ~\anaconda3\lib\site-packages\urllib3\util\retry.py:331 in _is_method_retryable
    if self.method_whitelist and method.upper() not in self.method_whitelist:

AttributeError: 'Retry' object has no attribute 'method_whitelist'

**Comment by sc0Vu** [comment]
Hi @Tomas-MP 

Weird! The code you paste is using bybit exchange, but the error shows kucoinfutures.

It seems to be a issue with a deprecated method from urllib3 https://stackoverflow.com/questions/65289720/attributeerror-retry-object-has-no-attribute-method-whitelist.

I used 2.28.2 requests and 1.26.14 urllib3 on my laptop, it works good.

**Comment by Tomas-MP** [comment]
Hi, will solve it with updating urllib. Indeed it did not work for both kucoinfutures and bybit, but I pasted the kucoinfutures error code by accident.
