### ISSUE TITLE
Binance SPOT Testnet seems to point to Futures Testnet

### ISSUE THREAD

**Issue by Roh-codeur** [ccxt/ccxt#20577]
### Operating System

Mac

### CCXT Version

4.1.98

### Description

Hi

I am seeing a strange behaviour. I use CCXT to connect to Binance testnet. If I use my Binance testnet futures account API keys it appears to work fine. however, it doesnt work with Spot. if I put exchange verbose = True, it shows me the Urls pointing to futures testnet. 

**fetch Request**: binance GET https://testnet.binancefuture.com/fapi/v1/leverageBracket..... 

**fetch Response**: binance GET https://testnet.binancefuture.com/fapi/v1/leverageBracket?
....

ResponseBody: {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action"}

### Code

```
  
import asyncio

import ccxt.pro

exchange = ccxt.pro.binance({
    'apiKey': 'API_KEY',
    'secret': 'SECRET',
    'options': {
        'defaultType': 'spot',
    },
})
exchange.set_sandbox_mode(True)  # comment if you're not using the testnet
markets = asyncio.get_event_loop().run_until_complete(exchange.load_markets())
exchange.verbose = True  # debug output

balance = asyncio.get_event_loop().run_until_complete(exchange.fetch_balance())  # this runs fine
account_positions = asyncio.get_event_loop().run_until_complete(exchange.fetchAccountPositions())  # this doesnt work
print("")

```

**Comment by carlosmiei** [comment]
Hello @Roh-codeur, that happens because `fetchAccountPositions` is a futures-only method, and it uses these endpoints:

https://binance-docs.github.io/apidocs/futures/en/#account-information-v2-user_data
https://binance-docs.github.io/apidocs/delivery/en/#account-information-user_data

**Comment by Roh-codeur** [comment]
ahh, got it. I was looking for current active positions, open orders, placing orders on Binance. My reference is:

https://github.com/ccxt/ccxt/wiki/Manual

sorry, if I missed it, how do I know which calls point to Spot and which ones to Future pls?

thanks a lot for your help

**Comment by carlosmiei** [comment]
@Roh-codeur No problem, Pretty much all balance/trades/order-related methods are available for both market types (spot and futures).

Methods like fetchPositions/fundingRate/fundingHistory are futures-only because those concepts usually only apply to contracts.

**Comment by Roh-codeur** [comment]
gotcha, thanks a lot mate! and seasons greetings to you!
