### ISSUE TITLE
Python deps should not be locked to a particular version.

### ISSUE THREAD

**Issue by miracle2k** [ccxt/ccxt#2057]
This is broken since https://github.com/ccxt/ccxt/commit/9a3fb891c6e990659801cbdb26352244595f2f4d#diff-8cf6167d58ce775a08acafcfe6f40966 

What is the reason for this change? As a library, ccxt should not be fixed to particular versions of it's dependencies. If there is a certain minimum version requirement, it can specify a `foo>2`, but should not be stricter than that.

**Comment by miracle2k** [comment]
Pinging @kovalevvlad as the author of the change.

**Comment by kroitor** [comment]
> As a library, ccxt should not be fixed to particular versions of it's dependencies.

Nope, it really should have a fixed list and there are strong reasons for that ) 

This is a decision based on security considerations. When a library like this is used by so many people to trade thousands of dollars, security plays a much more important role than, say, convenience. Explained here: #943 

Let us know if it does not answer your question. Thx!

**Comment by miracle2k** [comment]
I appreciate the very, very real problem of ensuring that third party code is trustworthy, in particular for ccxt. We all pull in dependencies all over the place in our projects, and each one is indeed an attack vector.

I do question the approach taken here. While it is admirable that the authors of ccxt would want to audit the third party dependencies before upgrading them and locking them to new versions, you are only pushing the attack surface further down. ccxt depends on `requests`, and `requests ` depends on, say, `certifi` and `urllib3`. If `urllib3` is compromised today, a fresh pip install on my machine will pull in the hacked version despite the version lock in ccxt for `requests`. 

On the other hand, I don't  just see this as a question of convenience. `pipenv` is literally refusing to let me install https://github.com/serathius/sanic-sentry because it requires a different version of `aiohttp`.

As I said, I am very much worried about the security of my dependencies. I don't believe that this is the answer. If you use ``ccxt`` next to a large enough number of other dependencies you are quite likely to run into a version conflict sooner or later.  

If `aiohttp` or `requests` every get compromised, a lot of people are going to have a *really serious* problem, not just ccxt users. I would suggest that if heavily-used core packages such as `requests` or `aiohttp` feel that using  lose version requirements is a fair security trade-off, then ccxt should be able to make that same trade-off.

I just don't think that it is ccxt's job to marginally increase security by guarding against a backdoor in `aiohttp`, at the cost of being a bad citizen of the package ecosystem, when in the end it is the job of the end developer such as myself to be responsible about *all* my dependencies, not just `ccxt`.

**Comment by kroitor** [comment]
>  pipenv is literally refusing to let me install https://github.com/serathius/sanic-sentry because it requires a different version of aiohttp.

Yep, it uses an old one... And for some reason it restrict the aiohttp version to <3.0.0. I don't think we should really change the version number of aiohttp in ccxt for `sanic-sentry`. It is the `sanic-sentry` who is a bad citizen in this case. And apart from aiohttp, I don't know of any other install conflicts. We may relax the version of aiohttp, because it's a known issue...

> If you use ccxt next to a large enough number of other dependencies you are quite likely to run into a version conflict sooner or later.

It depends on how often other packages get updated. It's because python's own package management uses the same `site-packages` for all projects, whereas it should have really used per-project deps to be cross-portable. This is the reason why node users have much less conflicts, and python users practically always have conflicts in a production environment. It boils down to the fact that Python shares the deps-tree among projects. From my perspective, it's a design mistake that ruins the lives of python programmers every day. But we have to live with it.

**Comment by kroitor** [comment]
I'm still keeping the fixed aiohttp version for now, but we will watch it closely, and if too many users report the same problem, we will think of addressing it differently, then. Sorry.

**Comment by kroitor** [comment]
@miracle2k I would suggest to move this discussion to #943 to, maybe, find a reasonable solution that would satisfy everyone. I think it would be interesting to know opinions of other users on the subject as well.

**Comment by kovalevvlad** [comment]
It does seem like we should relax the constraints a bit (aiohttp and requests have looser constraints on their requirements).

At the same time, I don't think that doing so would guarantee a situation where no requirement conflicts occur, it would merely reduce the probability of such scenario. You should be able to deal with requirement conflicts in one way or another (a few good example here - https://medium.com/knerd/the-nine-circles-of-python-dependency-hell-481d53e3e025).

Another potential issue with allowing a variety of major versions of dependencies is it's going to require additional testing.

**Comment by kroitor** [comment]
@kovalevvlad in this particular case, the problem is that `sanic-sentry` indeed requires a different major version of aiohttp < 3.0.0. I don't really think we should do the same in ccxt.

**Comment by miracle2k** [comment]
The sanic-sentry case is a bit of a special case; the whole mess happend because the sentry library for aiohttp does not work with aiohttp>3 (for now).

I'll try to fix my problem a different way, and we'll see when other versioning conflicts happen. I do expect them :)

**Comment by kroitor** [comment]
@miracle2k ok, i'd say the `sanic-sentry` is a minor conflict... Let us know if you have any other difficulties or major conflicts further, we can reconsider this issue once again if we find more. Thank you!
