### ISSUE TITLE
Binance: fetch_balance does not throw exception but generates PHP error when api permission issue is reported

### ISSUE THREAD

**Issue by piotrekkaminski** [ccxt/ccxt#2059]
- OS: MacOS
- Programming Language version: PHP 5.6 or later
- CCXT version: 1.10.1
- Exchange: binance
- Method: fetch_balance()

If API keys in binance are setup for withdrawal, they have to be tied to IP address. When you try then to use method fetch_balance() on another IP, you get the following:

PHP Notice:  Undefined index: balances in ccxt/php/binance.php on line 389

what gets returned from the internal method $response = $this->privateGetAccount ($params);
is
array(2) {
  ["code"]=>
  int(-2015)
  ["msg"]=>
  string(47) "Invalid API-key, IP, or permissions for action."
}
and this error is not handled nor raises an exception.

**Comment by kroitor** [comment]
@piotrekkaminski please update your version of ccxt to the most recent one 1.10.1223.

This issue has already been addressed here, yesterday: 

- https://github.com/ccxt/ccxt/pull/2045
- https://github.com/ccxt/ccxt/issues/2044

As you may know the library is under active development, therefore we ask users to update frequently to stay up-to-date. 

Let us know if it does not help. Thx!
