### ISSUE TITLE
Bitget fetch_ohlcv wrong arguments for Spot historical data

### ISSUE THREAD

**Issue by noel45** [ccxt/ccxt#20591]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.1.80

### Description

Bitget provides 2 endpoints for ohclv data: last month and historical data.

These 2 endpoints take different arguments in parameter. Historical data endpoint requires "endTime" parameter.
However, if trying to "force" to use the historical endpoint for spot in the *params*, the parameters specified in the query are still the same as the last month data endpoint (ie "after" and "before"), causing the request to fail:

`bitget {"code":"40019","msg":"参数 endTime 不能为空","requestTime":1703843779101,"data":null}`

See below how I call the method. Let me know if I should change the way I call it or if it is something you need to correct on your side.

### Code

```
bitget.fetch_ohlcv(symbol, '1m', timestamp, limit=200, params={'partial': False, 'method': 'publicSpotGetSpotV1MarketHistoryCandles'})
```

**Comment by carlosmiei** [comment]
Hello @noel45, 
Recently, we upgraded bitget to v2, so that problem is fixed. Can you please update your ccxt version? Also please bear in mind that after the upgrade, you should use `method:'publicSpotGetV2SpotMarketHistoryCandles'` instead. 


```
✗ n bitget fetchOHLCV "BTC/USDT" 1m 1703848200000 undefined '{"method":"publicSpotGetV2SpotMarketHistoryCandles"}'          
CCXT v4.2.1
bitget.fetchOHLCV (BTC/USDT, 1m, 1703848200000, , [object Object])
2023-12-29T11:29:18.448Z iteration 0 passed in 2287 ms

1703848200000 | 42737.71 |  42753.8 | 42737.71 | 42749.52 |  3.5306
1703848260000 | 42749.52 | 42753.98 | 42749.51 | 42753.98 |  1.9162
1703848320000 | 42753.98 |  42773.7 | 42753.98 | 42773.69 |  5.0772
1703848380000 | 42773.69 |  42773.7 | 42755.24 | 42755.24 |  2.0342
1703848440000 | 42755.24 | 42755.51 |    42742 | 42742.77 |  2.3458
1703848500000 | 42742.77 | 42754.74 | 42742.76 | 42748.48 |  3.9484
1703848560000 | 42748.48 | 42770.84 | 42748.43 |    42770 |  3.2252
1703848620000 |    42770 | 42857.14 | 42769.99 | 42857.14 |   2.248
````

**Comment by noel45** [comment]
Thanks Carlos, I will give it a try

**Comment by noel45** [comment]
Hi Carlos,

I tried to use the method 'publicSpotGetV2SpotMarketHistoryCandles' with a start time only, as it should be usable according to ccxt interface. However the start time is ignored in that case, since Bitget only accepts an endTime in the request. Could we then calculate the end_time based on the start_time and candles limit ? (even if the candles limit was defaulted) That would be more transparent from an end user point of view. 

Example:

![image](https://github.com/ccxt/ccxt/assets/15633913/6086717a-f196-4a1f-86d9-bfc27ca144db)

**Comment by noel45** [comment]
Hi Carlos, do you think that proposal could be implemented ?
