### ISSUE TITLE
fetch_balance still not implemented for Alpaca

### ISSUE THREAD

**Issue by fuzihaofzh** [ccxt/ccxt#20597]
### Operating System

Linux

### Programming Languages

Python

### CCXT Version

4.2.1

### Description

When I create an Alpaca exchange and call with `exchange.fetch_balance()`, it shows:
```
python3.8/site-packages/ccxt/base/exchange.py", line 3521, in fetch_balance
    raise NotSupported(self.id + ' fetchBalance() is not supported yet')
ccxt.base.errors.NotSupported: alpaca fetchBalance() is not supported yet
```

### Code

```
exchange.fetch_balance()

```

**Comment by samgermain** [comment]
There doesn't appear to be an endpoint on the Alpaca api for getting your balance information. The closest is https://docs.alpaca.markets/reference/getfundingwallet but it's only for the sandbox api

**Comment by vd3d** [comment]
Alpaca has the API to get the balance, it is part of the account api, here it is: v2/account.

Here is the doc: https://alpaca.markets/deprecated/docs/api-documentation/api-v2/account/

Then you receive a json, where:

asset: json["currency"]
free: json['cash']
locked: json['portfolio_value']
