### ISSUE TITLE
Need help for add the Stop loss when I create an position on BingX

### ISSUE THREAD

**Issue by xerno0om** [ccxt/ccxt#20606]
### Operating System

Windows 11

### Programming Languages

Python

### CCXT Version

4.0.29

### Description

I need a code to put the Stop loss when I create an position on bingX, I can't do it with my code below, I tried To understand where the problem comes from I haven't found it, please help me I would be grateful.

### Code

I tried this code
```
 order = await exchange.create_order('LTC/USDT:USDT', 'market', 'buy', 0.1, 50, {
        'stopLoss': f'{{\"type\": \"STOP_MARKET\", \"quantity\": {take_profit_amount},\"stopPrice\": {take_profit_price},\"price\": {take_profit_price},\"workingType\":\"MARK_PRICE\"}}',
     'positionSide': 'SHORT'
    })
```

he put me this error code:

```
ccxt.base.errors.AuthenticationError: bingx {"code":100001,"msg":"Signature verification failed due to signature mismatch","success":false,"timestamp":1704013116028}
```

**Comment by xerno0om** [comment]
> Bonjour @xerno0om, je viens de tester quelque chose de très similaire et cela a fonctionné comme prévu:
> 
> Vérifiez ceci:
> 
> ```python
>     params = {
>         "stopLoss": "{\"type\": \"STOP_MARKET\", \"quantity\": 1,\"stopPrice\": 50,\"price\": 51,\"workingType\":\"MARK_PRICE\"}"
>     }
> 
>     order = await exchange.create_order("LTC/USDT:USDT", "market", "buy", 1, None, params)
>     print(order)
> ```

I just do this
```
import ccxt

exchange = ccxt.bingx({
    'apiKey': 'ppp',
    'secret': 'ooo',
    'options': {
        'adjustForTimeDifference': True,
        'defaultType': 'swap',
    },
})

symbol = 'BTC-USDT' 
price = 42532.7
amount = 1.00
leverage = 74
quantity = ((amount / price) * leverage)
print(quantity)

pourcentage = 0.27 / 100
stop_loss = price - (price * pourcentage) 

params = {
    "stopLoss": "{\"type\": \"STOP_MARKET\", \"quantity\": " + str(quantity) + ",\"stopPrice\": " + str(stop_loss) + ",\"price\": " + str(price) + ",\"workingType\":\"MARK_PRICE\"}"
}

order = exchange.create_order(symbol, "market", "buy", quantity, None, params)
print(order)
```

he tell me 
```
ccxt.base.errors.AuthenticationError: bingx {"code":100001,"msg":"Signature verification failed due to signature mismatch","success":false,"timestamp":1704029218040}
```

**Comment by carlosmiei** [comment]
@xerno0om It might be related to your ccxt version, can you update it and try again?

**Comment by xerno0om** [comment]
Hello, it was indeed the version of my ccxt which was the problem, I switched to the latest version of ccxt and the script works well now, thank you
