### ISSUE TITLE
Question about timestamps...

### ISSUE THREAD

**Issue by Oshawk** [ccxt/ccxt#2060]
Hello,

Sorry for not filling in any of the details but my question is not platform specific.

Is it possible to get the timestamp of when a order was closed. I am aware that the order structure has a timestamp property but I am confused on what it represents (I assume when it was placed).

Thanks,
Joseph.

**Comment by kroitor** [comment]
Hi!

> I am aware that the order structure has a timestamp property but I am confused on what it represents (I assume when it was placed).

That is correct, the timestamp represents the moment when the order was placed (created). We don't have a closing timestamp yet. However, as you may know, this library is under active development and we are going to address this aspect as well.

> Is it possible to get the timestamp of when a order was closed.

Sometimes, it is. But most exchanges will not return that data, unfortunately. The fail-proof way of getting the closing timestamp is checking order trades and getting the timestamp of the last trade from there. We are going to rework the timestamp of the order, so there will be several timestamps, but for now, there's no field in the unified API for the closing time. You can still access that data from the non-unified `info` field that is present in each return from ccxt. We will update you when a unified way of accessing the closing timestamp is available.

Your help and contributions would be very much appreciated:
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

Let me know if it does not answer your question. Thx!

**Comment by Oshawk** [comment]
Thanks, this answers my question. I will have to find another way around my issue.

**Comment by kroitor** [comment]
@Oshawk you can look into the `info` field, as it contains all data returned from the exchange, as is. From there you can deduce the closing time, if the exchange in question does provide it. Hope it helps.
