### ISSUE TITLE
fetchMyTradesWs keep application running

### ISSUE THREAD

**Issue by fl0wo** [ccxt/ccxt#20615]
### Operating System

Ubuntu Linux

### CCXT Version

4.1.65

### Description

Hi, when running:

`const trades = await binancePro.fetchMyTradesWs(symbol);
`

What happens is that I successfully receive my trades, but for some reason my process is still "running", while with a rest call (fetchMyTrades), the process ends right after the result is returned.

Maybe is due to the fact that under the hood a watch is created? (and potentially that watch is running recursively?)

Is there a way to "cancel the second promise request" or just let the application die after the result is being processed?

### Code

Code copy from : [ccxt-pro binance](https://github.com/ccxt/ccxt/blob/master/js/src/pro/binance.js)

```
     const subscription = {
            'method': this.handleTradesWs,
        };
        const trades = await this.watch(url, messageHash, message, messageHash, subscription);
        return this.filterBySymbolSinceLimit(trades, symbol, since, limit);

```

**Comment by carlosmiei** [comment]
Hello @fl0wo, yes that happens because a WS connection is established and kept running. This the expected behavior when dealing with WS methods.

To close all the connections and avoid having a hanging process, you just need to call `await exchange.close()` at the end of your script.

**Comment by fl0wo** [comment]
> Hello @fl0wo, yes that happens because a WS connection is established and kept running. This the expected behavior when dealing with WS methods.
> 
> 
> 
> To close all the connections and avoid having a hanging process, you just need to call `await exchange.close()` at the end of your script.
> 
> 

Works perfectly, thank you 🙏🏻
