### ISSUE TITLE
GDAX FetchOrder Exceptions

### ISSUE THREAD

**Issue by tbrent** [ccxt/ccxt#2061]
- OS: macOS 10.13.1
- Programming Language version: Python 2.7
- CCXT version: 1.10.1224
- Exchange: GDAX
- Method: fetchOrder

Hi All,

I've noticed a new behavior for GDAX introduced sometime between ccxt 1.10.1138 and 1.10.1224. It used to be that if you called `fetchOrder` on an order that no longer exists, `ccxt` raised an `OrderNotFound` exception, or at the bare minimum an `ExchangeError` (I'm actually not sure which; my code catches `ExchangeError` which is sufficient to catch either). In 1.10.1224 if you call `fetchOrder` on an order that no longer exists, it throws `ExchangeNotAvailable`, which is a `NetworkError`. Was this intentional? Seems more proper for this behavior to result in an `ExchangeError` than a `NetworkError`. 

Logs
```
gdax https://api.gdax.com/orders/7c883b5c-4f69-4f3a-a848-6bf2a7764bc1 GET 404 Client Error: Not Found for url: https://api.gdax.com/orders/7c883b5c-4f69-4f3a-a848-6bf2a7764bc1 {"message":"NotFound"} gdax https://api.gdax.com/orders/7c883b5c-4f69-4f3a-a848-6bf2a7764bc1 GET 404 Client Error: Not Found for url: https://api.gdax.com/orders/7c883b5c-4f69-4f3a-a848-6bf2a7764bc1 {"message":"NotFound"}
{'message': u'gdax https://api.gdax.com/orders/7c883b5c-4f69-4f3a-a848-6bf2a7764bc1 GET 404 Client Error: Not Found for url: https://api.gdax.com/orders/7c883b5c-4f69-4f3a-a848-6bf2a7764bc1 {"message":"NotFound"}', 'type': 'ExchangeNotAvailable', 'lineno': 110, 'name': 'run', 'filename': 'gdax_binance_bidirectional.py'}
```

Cheers!

**Comment by tbrent** [comment]
Thanks!

**Comment by kroitor** [comment]
@tbrent thx for reporting! Let us know if you have any other difficulties with it.
