### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by ductridev** [ccxt/ccxt#20617]
### Operating System

Window 10

### Programming Languages

JavaScript

### CCXT Version

4.2.1

### Description

Development ReactJS Environment.
Because 'http' package is only available on the server side, not on the client side. So if I install it to go with ReactJS, it will cause the error below:
`TypeError: Class extends value undefined is not a constructor or null`
The root code causes error is:
```
// ----------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
// EDIT THE CORRESPONDENT .ts FILE INSTEAD

import * as http from 'http';
export * from './helpers.js';
function isSecureEndpoint() {
    const { stack } = new Error();
    if (typeof stack !== 'string')
        return false;
    return stack
        .split('\n')
        .some((l) => l.indexOf('(https.js:') !== -1 ||
        l.indexOf('node:https:') !== -1);
}
const INTERNAL = Symbol('AgentBaseInternalState');
export class Agent extends http.Agent {
...
```
Even the fetch request still works. (See attachment screenshots)
![image](https://github.com/ccxt/ccxt/assets/49811496/04b148b8-b0db-415c-a8b1-9672ba9a9254)
![image](https://github.com/ccxt/ccxt/assets/49811496/60985e09-cf4d-4f68-997e-c24271a6d23b)
![image](https://github.com/ccxt/ccxt/assets/49811496/c1b5bbec-0b85-4559-88a1-4379b0716a13)

### Code

```
import ccxt from 'ccxt';
try {
let client = new ccxt.binance()
switch (exchange) {
	case 'Binance': {
		client = new ccxt.binance()
		break;
	}
	case 'bybit': {
		client = new ccxt.bybit()
		break;
	}
	case 'bingx': {
		client = new ccxt.bingx({
			apiKey: '',
			secret: ''
		})
		break;
	}
	case 'bitget': {
		client = new ccxt.bitget()
		break;
	}
	case 'Gateio': {
		client = new ccxt.gateio({
			apiKey: '',
			secret: ''
		})
		break;
	}
	case 'mexc': {
		client = new ccxt.mexc({
			apiKey: '',
			secret: ''
		})
		break;
	}
	case 'Bitstamp': {
		client = new ccxt.bitstamp()
		break;
	}
	default: {
		console.error('Unknow exchange: ' + exchange)
		break;
	}
}
client.enableRateLimit = true;
client.options.returnRateLimits = true
client.options.defaultType = 'spot'
client.options.allowSynchronousEvents = true
client.verbose = true
console.log(client.version)
await client.loadMarkets()
} catch (e) {
console.error("getCCTXClient: ")
console.error(e)
await timer(30000)
}
```

**Comment by carlosmiei** [comment]
Hello @ductridev,
Can you try to load the browserified version instead? 
https://github.com/ccxt/ccxt?tab=readme-ov-file#javascript-for-use-with-the-script-tag

**Comment by ductridev** [comment]
Hi @carlosmiei, I have tried and a new error just happened:
```Couldn't find the requested file /static_dependencies/proxies/http-proxy-agent/index.js in ccxt.```
My scrip tag:
```<script crossorigin="anonymous" type="text/javascript" src="https://cdn.jsdelivr.net/npm/ccxt@4.2.3/dist/ccxt.browser.js"></script>```

**Comment by carlosmiei** [comment]
@ductridev can you temporarily try a lower version? we have an issue right now related to proxies but we're working on it right now.

Can you try for instance this one? https://cdn.jsdelivr.net/npm/ccxt@4.1.1/dist/ccxt.browser.js

**Comment by ductridev** [comment]
Yes, I can see it works with version 4.1.1. I will close the issue and re-open it if needed.

**Comment by carlosmiei** [comment]
@ductridev The issue I mentioned will be fixed very shortly (already opened a PR), so very soon you can bump the version to the latest
