### ISSUE TITLE
Cannot create TP/SL order on Bybit Spot

### ISSUE THREAD

**Issue by Alfavisioner** [ccxt/ccxt#20612]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

4.2.2

### Description

Exchange: Bybit testnet
Market: Spot 

Bybit has strict limitation on order price comparing to market price +- 3%, +- 5%
To get rid of such limitation i need to create TP/SL orders to occupy assets like general order

I pass parameters: 
{'symbol': 'ETHUSDT', 'type': 'limit', 'side': 'buy', 'amount': '0.1', 'price': '1999.0', 'params': {'timeInForce': 'GTC', 'recvWindow': 10000, 'takeProfitPrice': 2100}}

into:
exchange.create_order

Every time conditinal order is created, but TP/SL is not

I investigated code:
bybit:3369 create_order_request
To create TP/SL orders we need to set tpslOrder flag
No chances to set tpslOrder flag, because triggerPrice is specified in the previous block of code

### Code

2 possible fixes on the first glance:

1) bybit:3479
```
  if market['spot']:
      if triggerPrice is not None:
          request['orderFilter'] = 'StopOrder'
      elif stopLossTriggerPrice is not None or takeProfitTriggerPrice is not None or isStopLoss or isTakeProfit:
          request['orderFilter'] = 'tpslOrder'

swap order to 
      if stopLossTriggerPrice is not None or takeProfitTriggerPrice is not None or isStopLoss or isTakeProfit:
          request['orderFilter'] = 'tpslOrder'
      elif triggerPrice is not None:
          request['orderFilter'] = 'StopOrder'

```

or 

2) bybit:3464
```
in this block
        elif isStopLossTriggerOrder or isTakeProfitTriggerOrder:
            if isBuy:
                request['triggerDirection'] = 1 if isStopLossTriggerOrder else 2
            else:
                request['triggerDirection'] = 2 if isStopLossTriggerOrder else 1
            triggerPrice = stopLossTriggerPrice if isStopLossTriggerOrder else takeProfitTriggerPrice
            request['triggerPrice'] = self.price_to_precision(symbol, triggerPrice)
            request['reduceOnly'] = True

triggerPrice variable change to _triggerPrice to not influence next code
```

**Comment by sc0Vu** [comment]
Hi @Alfavisioner,

I think the issue occurred when use spot market, because the `orderFilter` is valid for spot only. Do you use spot market?

Before we make some changes, you can set `tpslOrder` for spot manually with this in params`"orderFilter":"tpslOrder"`. Remember the triggerPrice is required for this kind of order in spot market.

**Comment by Alfavisioner** [comment]
> Hi @Alfavisioner,
> 
> I think the issue occurred when use spot market, because the `orderFilter` is valid for spot only. Do you use spot market?
> 
> Before we make some changes, you can set `tpslOrder` for spot manually with this in params`"orderFilter":"tpslOrder"`. Remember the triggerPrice is required for this kind of order in spot market.

Sure, i use Spot market. I stated that in initial message.
Thank you for clarification. 
I passed  params"orderFilter":"tpslOrder",use triggerPrice and it works. 
Please, close ticket.
