### ISSUE TITLE
Bitpanda PRO -> One Trading: API Domain Change

### ISSUE THREAD

**Issue by mullerpeter** [ccxt/ccxt#20629]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

With the rebranding of Bitpanda Pro to One Trading, the API domains will change on January 4th, 2024.

> Hello One Trader,
> 
> Please note that we have updated our API domains as follows:
> 
> Websocket API: wss://streams.onetrading.com/
> REST API: api.onetrading.com/public/v1
> Support of the existing API domains will cease on January 4th, 2024. If you are an API trader, please ensure that you update your API before this date to continue trading via One Trading.
> 
> You can find more information on our API here: 
> https://docs.onetrading.com
> 
> Have a great day,
> Team One Trading

### Describe the solution you'd like

One of the following:

- Add One Trading Exchange with the correct API domains
- Rename Bitpanda Pro Exchange to One Trading & replace API domains

**Comment by madelmann** [comment]
It looks like the PRs have not yet been merged (Travis CI - Pull Request Failing after 16m — Build Failed). Are there plans to fix this?

**Comment by carlosmiei** [comment]
> rged (Travis CI - Pull Request Failing after 16m — Build Failed). Are there plans to fix this?

@madelmann Just merged a PR that finishes the rename to onetrading and keeps bitpanda as an alias

**Comment by carlosmiei** [comment]
@mullerpeter @madelmann it should be available as of 4.2.19.

**Comment by madelmann** [comment]
Thanks for merging!
