### ISSUE TITLE
CCXT / exchage: Phemex / BTC/USDT:USDT / Limitorder

### ISSUE THREAD

**Issue by halefopw** [ccxt/ccxt#20620]
### Operating System

Win 10

### Programming Languages

Python

### CCXT Version

ccxt-4.2.3

### Description

Hey,
I tryed to set a limitorder for "BTC/USDT:USDT" on the same way I'm setting my orders for "BTC/USD:USD" but for "BTC/USDT:USDT" it dont work. It seems like no sybol with ":USDT" works. Is this normal or a bug? or just i have to set other params or structure for the ":USDT" sybols?
pls help

### Code

exchange = ccxt.phemex({
    "apiKey": API_KEY,
    "secret": API_SECRET,
    "enableRateLimit": True,
    "permissions": ["order"],
})

Here is my code for "BTC/USD:USD" limitorder, it works fine:
order = exchange.create_order(
    symbol="BTC/USD:USD",
    side="buy",
    type="limit",
    price=25000,
    amount=1,
)
print(order)

Here is my code for "BTC/USDT:USDT" limitorder, it works not:
order = exchange.create_order(
    symbol="BTC/USDT:USDT",
    side="buy",
    type="limit",
    price=25000,
    amount=00.1,
)
print(order)

Error code:

....
line 4372, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: phemex {"code":20004,"msg":"TE_ERR_INCONSISTENT_POS_MODE","data":null}
  

```

**Comment by carlosmiei** [comment]
Hello @halefopw,
I think it is related to the position mode, can you please try to provide `posSide` in `params`? 

Example:
```Python
params={'posSide': 'net'}) 
order = exchange.create_order(
symbol="BTC/USD:USD",
side="buy",
type="limit",
price=25000,
amount=1,
params
)
```

**Comment by halefopw** [comment]
Hey thanks for the fast answer,

if I use your example "BTC/USD:USD" still works but "BTC/USDT:USDT" still not works.
If I use:
params={'posSide': 'net'}
order = exchange.create_order(
symbol = "BTC/USDT:USDT",
side = "buy",
type = "limit",
price = 25000,
amount = 0.001,
params = params,
)
The error message chaged to:
line 4372, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: phemex {"code":39999,"msg":"Error in place order","data":null}

**Comment by carlosmiei** [comment]
@halefopw Sorry I made a mistake,actually I think the `posSide` should be either `Long` or `Short` depending on the direction you want to go. Can you try that?

**Comment by halefopw** [comment]
Yes now it works! 

Ty realy mutch!

so the Code shows if it works for "BTC/USDT:USDT" and ather ":USDT":

params={'posSide': 'Long'}
order = exchange.create_order(
symbol = "BTC/USDT:USDT",
side = "buy",
type = "limit",
price = 25000,
amount = 0.001,
params = params,
)

**Comment by 6642248687** [comment]
> ¡Sí, ahora funciona!
> 
> ¡Realmente mucho!
> 
> entonces el Código muestra si funciona para "BTC/USDT:USDT" y otros ":USDT":
> 
> params={'posSide': 'Largo'} orden = exchange.create_order( símbolo = "BTC/USDT:USDT", lado = "comprar", tipo = "límite", precio = 25000, monto = 0.001, params = params , )

👍👍👍👍

**Comment by carlosmiei** [comment]
@halefopw no problem 🙂 In that case, I'm going to close the issue, feel free to re-open it if anything!
