### ISSUE TITLE
Kucoin trade_hf

### ISSUE THREAD

**Issue by iht76** [ccxt/ccxt#20644]
### Description

How do I place an order etc. to Kucoin trade_hf account instead of the default "trade"  ?

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @iht76 

You can set `hf` to true in params.

**Comment by carlosmiei** [comment]
Hello @iht76 , make sure you're providing the argument correctly, in this case it should be:
`exchange.fetchOpenOrders("BTC/USDT", undefined, undefined, {"hf":true})`

**Comment by carlosmiei** [comment]
@iht76 can you enable the verbose mode `exchange.verbose = true` and check which endpoint was used?

**Comment by carlosmiei** [comment]
@iht76 As you can see the hf endpoint is used

**Comment by carlosmiei** [comment]
@iht76 Did you place the order using the hf endpoint as well?
