### ISSUE TITLE
fetch_ohlcv for current timestamp return empty array even the response isn't empty.

### ISSUE THREAD

**Issue by ductridev** [ccxt/ccxt#20646]
### Operating System

Window 10

### Programming Languages

JavaScript

### CCXT Version

4.2.1

### Description

You can try with this link and replace start with the current timestamp at this site: [epochconverter](https://www.epochconverter.com/) and get the current Unix epoch time then multiply for 1000 after that pass the result into start in this URL: https://api.bybit.com/v5/market/kline?symbol=BTCUSDT&start=<here>&limit=1000&interval=1&category=spot

You can see it response at least 1 response with the current timestamp.
Even the response has 2 arrays in the list object. See attachment for more details.
`start=1704292193000`
![image](https://github.com/ccxt/ccxt/assets/49811496/400e92cb-929a-48be-b6af-423d4284ceef)
![image](https://github.com/ccxt/ccxt/assets/49811496/ad3e6810-a2c8-4807-b8be-79959e19a333)

### Code

```
let client = new ccxt.binance()
await client.fetch_ohlcv("BTC/USDT", "1", 1000, <current_timestamp>)
```

**Comment by Dan-krm** [comment]
Hi @ductridev I think this is meant to happen, the smallest timeframe on bybit is `1m` and the responses that don't match the request are filtered out by the base Exchange method `filterBySinceLimit` which is used by `parseOHLCVs`, for example:
```
bybit fetchOHLCV BTC/USDT 1m 1704331179000 1000

ResponseBody:
{"retCode":0,"retMsg":"OK","result":{"category":"spot","symbol":"BTCUSDT","list":[["1704331200000","29423.85","29431.91","29416.18","29431.91","0.121886","3586.34998204"],["1704331140000","29431.79","29431.91","29416.18","29423.85","0.510476","15023.79745986"]]},"retExtInfo":{},"time":1704331213859}

bybit.fetchOHLCV (BTC/USDT, 1m, 1704331179000, 1000)
1704331200000 | 29423.85 | 29431.91 | 29416.18 | 29431.91 | 0.121886
1 objects
```
 In the example the exchange response returns two candlesticks but only one is accepted by the request since value, because of these methods that are used by fetchOHLCV:
```javascript
parseOHLCVs (ohlcvs: object[], market: any = undefined, timeframe: string = '1m', since: Int = undefined, limit: Int = undefined): OHLCV[] {
    const results = [];
    for (let i = 0; i < ohlcvs.length; i++) {
        results.push (this.parseOHLCV (ohlcvs[i], market));
    }
    const sorted = this.sortBy (results, 0);
    return this.filterBySinceLimit (sorted, since, limit, 0) as any;
}
```
```javascript
filterBySinceLimit (array: object[], since: Int = undefined, limit: Int = undefined, key: IndexType = 'timestamp', tail = false): any {
    const sinceIsDefined = this.valueIsDefined (since);
    const parsedArray = this.toArray (array) as any;
    let result = parsedArray;
    if (sinceIsDefined) {
        result = [ ];
        for (let i = 0; i < parsedArray.length; i++) {
            const entry = parsedArray[i];
            const value = this.safeValue (entry, key);
            if (value && (value >= since)) {
                result.push (entry);
            }
        }
    }
    if (tail && limit !== undefined) {
        return this.arraySlice (result, -limit);
    }
    return this.filterByLimit (result, limit, key);
}
```

**Comment by ductridev** [comment]
So is there any solution so I can get that latest candle?
Because without the latest candle, if users try to refresh then the stream data will cause not correct OHLCV candle.

**Comment by Dan-krm** [comment]
@ductridev 

- You can call fetchOHLCV without the since argument and this should retrieve the latest candle:
```
bybit fetchOHLCV BTC/USDT 1m undefined 1 --sandbox

ResponseBody:
 {"retCode":0,"retMsg":"OK","result":{"category":"spot","symbol":"BTCUSDT","list":[["1704333120000","29783.56","29786.81","29774.42","29786.74","0.233303","6948.92049267"]]},"retExtInfo":{},"time":1704333147197}

bybit.fetchOHLCV (BTC/USDT, 1m, , 1)
1704333120000 | 29783.56 | 29786.81 | 29774.42 | 29786.74 | 0.233303
1 objects
```
- You also usually have access to the exchange response by searching ['info'] on the method response, I'm not sure if this is supported on bybit fetchOHLCV though
- There's also the CCXT pro websocket method watchOHLCV

**Comment by ductridev** [comment]
@Dan-krm 
I understand CCXT pro has a method to watch it or trades, but if only watchTrades is supported it will capture the latest trades and calculate the OHLCV from it then the last OHLCV candle will be incorrect.
So I need to combine the latest OHLCV from fetchOHLCVs and then use watchOHLCV to stream it.
