### ISSUE TITLE
Bingx Trigger mode

### ISSUE THREAD

**Issue by salva-imm** [ccxt/ccxt#20643]
### CCXT Version

4.0.88 and 4.2.3

### Description

Hey, I am trying to open `TRIGGER_LIMIT` or `TRIGGER_MARKET` order, but TP and SL is not applying on order!
I tried direct API call as well.. i want to make sure its bingx issue

**Comment by ttodua** [comment]
Hi.
Unless you provide some more info it's hard to assist.
At least, mention which symbol (spot, swap) you are accessing

**Comment by ttodua** [comment]
also, mention from where did you find `TRIGGER_LIMIT or TRIGGER_MARKET` types, as in bingx API docs (https://bingx-api.github.io/docs/#/en-us/swapV2/changelog) there is no mention of them

**Comment by ttodua** [comment]
ah, a messed up docs, found them with different characters - https://bingx-api.github.io/docs/#/en-us/spot/trade-api.html#Create%20an%20Order

**Comment by salva-imm** [comment]
@ttodua 
Hey, thanks for the reply
here is an example of what im doing :
```

params = {
            'positionSide': position_side[side],
            'timeInForce': "GTC",
            "type": "TRIGGER_MARKET",
            }
params['takeProfit'] = json.dumps(
                {
                    "type": "TAKE_PROFIT_MARKET",
                    "quantity": float(amount),
                    "stopPrice": float(take_profit),
                    "price": float(price),
                }
            )
params['stopLoss'] = json.dumps(
                {
                    "type": "STOP_MARKET",
                    "quantity": float(amount),
                    "stopPrice": float(stop_loss),
                    "price": float(price),
                }
            )

exchange.create_order(
                symbol=symbol,
                side=side,
                type=order_type,
                amount=amount,
                price=price,
                params=params,
            )
```

no matter what symbol, its not applying TP and SL .

**Comment by ttodua** [comment]
symbol matters, because SPOT and CONTRACT markets have different API endpoints on bingx. that's why I asked which symbol you were handling. 
I have started checking the issue and will post updates

**Comment by salva-imm** [comment]
@ttodua BTC and BNB , i've tried
for the symbol im sending right format (ex: `BTC/USDT:USDT`)

**Comment by Dan-krm** [comment]
@salva-imm you can use the `'TRIGGER_MARKET'` and `'TRIGGER_LIMIT'` order types in a unified way by setting the `triggerPrice` parameter. These order types are for conditional stop orders (different from stop loss or take profit orders)

If you want to create an order with a `stopLoss` or `takeProfit` attached to the order you can set the parameters like this:
```
bingx createOrder "LTC/USDT:USDT" market buy 1 undefined '{"takeProfit":{"stopPrice":150},"stopLoss":{"stopPrice": 50}}'
```
This was made available in this PR: #20611

If you want to add a stop loss or take profit to a position after the position is already opened you can use the `stopLossPrice` or `takeProfitPrice` parameters

You can read more about the different order types you can place using CCXT here:
https://github.com/ccxt/ccxt/wiki/Manual#placing-orders

**Comment by salva-imm** [comment]
@Dan-krm this is not my answer!!!!!!! why did you close the issue??? i need to add sl and tp to trigger/conditional mode, Im aware how to add SL and TP to LIMIT mode!!! and `stopLossPrice` or `takeProfitPrice` is not doing anything in trigger mode
before you write these, i already tried all things you wrote here.

to make sure you understand what i mean , Im doing this in exchange directly
these are ORDERS!!! not POSITIONS!!!
![image](https://github.com/ccxt/ccxt/assets/32010748/dbddeec7-2951-4bd3-95de-8d66bed51d2c)

![image](https://github.com/ccxt/ccxt/assets/32010748/182c60f6-c30d-4da6-9223-b909abd9a34d)
 :

**Comment by ttodua** [comment]
The PR is on the way, which enhances unified functionality, and will let you know about updates

**Comment by salva-imm** [comment]
@ttodua thanks a lot buddy

**Comment by ttodua** [comment]
I have spent quite much time digging into this and turns out it is an issue at bingx engine side. unfortunately there is nothing we can do in such case.
if there will be any update, i'll try to remind this topic to notify you.

**Comment by salva-imm** [comment]
@ttodua thanks for your time, that's what i suspected , and asked to make sure this is bingx issue. i hope they fix it soon
thank you again

**Comment by ttodua** [comment]
> @ttodua thanks for your time, that's what i suspected , and asked to make sure this is bingx issue. i hope they fix it soon thank you again

as an user, you might try to reach their tech-support to report the issue, who knows, maybe they would listen to users

**Comment by salva-imm** [comment]
@ttodua sure, i will, once i opened a ticket by could get any asnwer, wanted to make sure its not the issue on our side(wrong parameters )(CCXT/API call)
i'll open another ticket and i'll try to contact them

**Comment by Dan-krm** [comment]
> @Dan-krm this is not my answer!!!!!!! why did you close the issue??? i need to add sl and tp to trigger/conditional mode, Im aware how to add SL and TP to LIMIT mode!!! and `stopLossPrice` or `takeProfitPrice` is not doing anything in trigger mode before you write these, i already tried all things you wrote here.
> 
> to make sure you understand what i mean , Im doing this in exchange directly these are ORDERS!!! not POSITIONS!!! ![image](https://private-user-images.githubusercontent.com/32010748/294122929-dbddeec7-2951-4bd3-95de-8d66bed51d2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MDA5MjQsIm5iZiI6MTcwNDQwMDYyNCwicGF0aCI6Ii8zMjAxMDc0OC8yOTQxMjI5MjktZGJkZGVlYzctMjk1MS00YmQzLTk1ZGUtOGQ2NmJlZDUxZDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDIwMzcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNGM3Y2I2MDFkODJhMGVhNjYzYmZjMGYzMWU2ZmQ3ZDg5MzkzYWRiOWIwOTk1OWI3ZTE2ZWU4YzBiYWVjMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eGboWXGqnWOwoEdwGxRR1jIqIzQefkMXt1krDViPL9A)
> 
> ![image](https://private-user-images.githubusercontent.com/32010748/294122774-182c60f6-c30d-4da6-9223-b909abd9a34d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MDA5MjQsIm5iZiI6MTcwNDQwMDYyNCwicGF0aCI6Ii8zMjAxMDc0OC8yOTQxMjI3NzQtMTgyYzYwZjYtYzMwZC00ZGE2LTkyMjMtYjkwOWFiZDlhMzRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDIwMzcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1OWVhYTIwOWJiNTM3NThhZTg4NWMyNGJkYTE5OTFiZDY1ZWIwNzA3Y2ZmNTM3MWZjNDU1ZjA4NGE1YTIzZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2bDVdzCm6aNp49pTnGwu6DQobULJ8XIwuAZ0kFUDwG0) :

That makes it more clear, sorry for misunderstanding the issue
