### ISSUE TITLE
Binance fetch_order method: origClientOrderId instead orderId

### ISSUE THREAD

**Issue by sergeijust** [ccxt/ccxt#2064]
- Programming Language version: Python
- CCXT version: 1.10.1230
- Exchange: Binance
- Method: fetch_order

`orderId` not mandatory for query order from Binance.
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#query-order-user_data

So how I can use `origClientOrderId` instead `orderId` in `fetch_order` method?

**Comment by kroitor** [comment]
The support for that option was added in most recent version.

1. Update to ccxt 1.10.1231
2. Add `origClientOrderId` to `params`:

```Python
order_id = None # ignored
symbol = None # ignored
params = {'origClientOrderId': '1234567890'} # origClientOrderId overrides order_id
order = exchange.fetch_order(order_id, symbol, params)
```

Let us know if it does not help. Thx!
