### ISSUE TITLE
CCXT / exchange: Phemex / exchange.fetch_positions([symbol], params) / double-print, double-defined

### ISSUE THREAD

**Issue by halefopw** [ccxt/ccxt#20653]
### Operating System

Win 10

### Programming Languages

Python

### CCXT Version

ccxt-4.2.4

### Description

Hello,
if I using this funktion: "exchange.fetch_positions([symbol], params)" to getting my positions in this exaple: "XRP/USDT:USDT"
I all ways getting a double-print back. One of the prits telling my correct positionsize and entry. The second print all ways telling size and entry are 0.
for example:
If i use this code: 
symbol = "XRP/USDT:USDT"
params = {"type":"swap","code":"USDT"}
positions = exchange.fetch_positions([symbol], params)
for position in positions:
    if position['symbol'] == symbol:
        entry_price = position['entryPrice']
        size = position['contracts']
        print(f"Entry:{entry_price}")
        print(f"PosSize:{size} ")

I getting this output:

Entry:0.6332
PosSize:0.01 
Entry:0.0
PosSize:0.0

If I using the variable: "size" for a calculation like:
symbol = "XRP/USDT:USDT"
params = {"type":"swap","code":"USDT"}
positions = exchange.fetch_positions([symbol], params)
for position in positions:
    if position['symbol'] == symbol:
        entry_price = position['entryPrice']
        size = position['contracts']
        print(f"Entry:{entry_price}")
        print(f"PosSize:{size} ")
        calcTest = size * 2
        print("calcTest:", calcTest)

I getting this output:

Entry:0.6332
PosSize:0.01 
calcTest: 0.02
Entry:0.0
PosSize:0.0 
calcTest: 0.0

My final problem, in this case is: I cant use the variables like "size" and "entry" for a if-comparison, becurse it seems like this variables are all time double-defined.
I have checked this "bug"/problem on tow different PCs (but both Win10) and both got the same problem.
Some one could help here pls? 

### Code

exchange = ccxt.phemex({
    "apiKey": API_KEY,
    "secret": API_SECRET,
    "enableRateLimit": True,
    "permissions": ["order", "private"],
})

symbol = "XRP/USDT:USDT"

params = {"type":"swap","code":"USDT"}
positions = exchange.fetch_positions([symbol], params)
for position in positions:
    if position['symbol'] == symbol:
        entry_price = position['entryPrice']
        size = position['contracts']
        print(f"Entry:{entry_price}")
        print(f"PosSize:{size} ")  
```
Output:
Entry:0.6332
PosSize:0.01 
Entry:0.0
PosSize:0.0 

Process finished with exit code 0

**Comment by carlosmiei** [comment]
Hello @halefopw, 
depending on your position mode, it might be normal to get two positions associated with the same symbol (the long and the short) and one might be empty so the exchange returns it with the default values (zeros and empty strings), you should be able to tell them apart very easily.

**Comment by halefopw** [comment]
@carlosmiei 
Oh, yes now its clear^^
Thanks!
but how can I save this dubble-otput in two different variables? is there a specific key-word, methode or params to differentiate between log- and shot-position?

And in this case a other question:
If I placeing a order like this: 
params = {'posSide': 'Long'}
buyOrder = exchange.create_order(
    symbol="XRP/USDT:USDT",
    side="buy",
    type="limit",
    price=0.5,
    amount=1,
    params=params,
)

how I can differentiate between set a order to open-positions or to close-positions? (pic.)
![Phemex open or close order](https://github.com/ccxt/ccxt/assets/155201686/bd9ef431-85be-402a-8038-5cdee105f84a)

**Comment by halefopw** [comment]
I found the solution to how I can differentiate between set a order to open-positions or to close-positions.
just using:
params = {'posSide': 'Long',
          'reduceOnly': True}
buyOrder = exchange.create_order(
    symbol="XRP/USDT:USDT",
    side="sell",
    type="limit",
    price=0.7,
    amount=0.01,
    params=params,
)

but how i can save the dubble-otput in two different variables, I still dont know, pls give me a tip if it is possible.

**Comment by halefopw** [comment]
Update...

I still looking for a way to save the dubble-otput from: "exchange.fetch_positions([symbol], params)" in two different variables

I tryed some thing like this, but nothing work, if i wana us both of them:

exchange = ccxt.phemex({
    "apiKey": API_KEY,
    "secret": API_SECRET,
    "enableRateLimit": True,
    "permissions": ["order", "private"],
})

symbol = "XRP/USDT:USDT"

params = {"type": "swap", "code": "USDT"}
positions = exchange.fetch_positions([symbol], params)

long_positions = []
short_positions = []

for position in positions:
    if position['symbol'] == symbol:
        size = position['contracts']
        if position['side'] == 'Long':
            long_positions.append(size)
        elif position['side'] == 'Short':
            short_positions.append(size)

print(f"Long Positions: {long_positions}")
print(f"Short Positions: {short_positions}")

**Comment by halefopw** [comment]
to close this issue here a solution.

I know this way not works for any application and some times it just not work, but in the most of cases it works and if not, so a modification of this finaly. If you have / finde a save way to differate between long and short positions, pls update this comment.

My way to differate, as example "BTC/USDT:USDT"

exchange = ccxt.phemex({
    "apiKey": API_KEY,
    "secret": API_SECRET,
    "enableRateLimit": True,
    "permissions": ["order", "private"],
})

symbol = "BTC/USDT:USDT"
params = {"type": "swap", "code": "USDT"}
positions = exchange.fetch_positions([symbol], params)

long_short_positions = []

for position in positions:
    if position['symbol'] == symbol:
        size = position['contracts']
        long_short_positions.append(size)
long_positions = long_short_positions[0]
short_positions = long_short_positions[1]

print("long_short_positions:", long_short_positions)
print("long_positions:", long_positions)
print("short_positions:", short_positions)

output:

long_short_positions: [0.002, 0.001]
long_positions: 0.002
short_positions: 0.001

Process finished with exit code 0
