### ISSUE TITLE
Plans to standardize currency and balance props in info for fetchBalance

### ISSUE THREAD

**Issue by TotallyKyle** [ccxt/ccxt#2065]
Currently I am getting back this in the info field when doing a fetchBalance from gdax and bittrex:

Bittrex:
info: {[
Available: 0
Balance: 0
CryptoAddress :null
Currency: "1ST"
Pending: 0
]},

Gdax:
info: {[
available: "0.000000000"
balance: "0.000000000"
currency: "BTC"
hold: "0.0000000000000000"
id: "XXXXXXXXXXXXXX"
profile_id: "XXXXXXXXXXXXXX"
]}

As you can see they have different props and different cases. The data returned is also different (string vs. float?). I have only tested these two exchanges but I assume other exchanges are different too.

I am wondering is there are any plans to standardize the props being returned and the type of data returned for all the exchanges? I understand that some exchanges might return more data that a user would need and we can provide those, but can we standardize shared ones like currency, balance, and etc..?

Thanks,
Kyle

- OS: Windows 10
- Programming Language version: JS
- CCXT version: 1.10.123
- Exchange: GDAX, Bittrex, others tbd
- Method: fetchBalance

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/Manual#querying-account-balance

![querying-balance](https://user-images.githubusercontent.com/1294454/36711595-3ab62838-1b95-11e8-99bc-2e7b5e1b2b85.jpg)

Read the Manual ) https://github.com/ccxt/ccxt/wiki/Manual
