### ISSUE TITLE
A non well formed numeric value encountered

### ISSUE THREAD

**Issue by opiy-org** [ccxt/ccxt#2066]
A non well formed numeric value encountered vendor\ccxt\ccxt\php\huobipro.php 183  
`     $average = ($open . $close) / 2;`
should be 
`     $average = ($open + $close) / 2;`

- OS: win 7
- Programming Language version: php 7.2, laravel
- CCXT version: 1.10.1235
- Exchange: huobipro
- Method: parse_ticker

**Comment by LorFor** [comment]
I've found the same error in cryptopia.php
PHP Notice:  A non well formed numeric value encountered in ccxt/php/cryptopia.php on line 243

After, I've looking for the same error in other file and I've found that:
$ grep average * | grep open
bithumb.php:            'average' => ($open . $close) / 2,
bitmex.php:            'average' => ($open . $close) / 2,
cryptopia.php:            'average' => ($last . $open) / 2,
hitbtc2.php:            $average = ($last . $open) / 2;
huobipro.php:            $average = ($open . $close) / 2;

**Comment by kroitor** [comment]
@LorFor you should update your ccxt version, this was already fixed earlier.

**Comment by LorFor** [comment]
I've notice it now 
Thank you Kroitor
