### ISSUE TITLE
Bid-Ask WebSocket Order Book Data Experiencing Random Outages

### ISSUE THREAD

**Issue by sonaalKant** [ccxt/ccxt#20667]
### Operating System

Ubuntu 20.04.6

### Programming Languages

Python

### CCXT Version

latest

### Description

Hi ccxt,
I am reaching out to share an issue we've been encountering with random outages while seeking WebSocket order book data from Binance using ccxt.

To provide more context and seek assistance, I've included a simplified version of a script that we are using to interact with ccxt for Binance WebSocket data. The problem manifests as websockets subscriptions, which are "not working". In other words `watchOrderBook` is called successfully but the data do not start coming in at all or stop coming in after an arbitrary (short) time interval. Usual scenario is that only a handful of symbols (a random subset each time) fail - a script is started, data for all but one/two assets come in as expected. Upon a script restart, it might happen that all symbols start to come in correctly or that another subset starts failing (silently).

We are eager to understand if there might be anything missing from our end or if there are any recommended solutions to prevent these random outages.

Additional information:
- we have tried using a smaller set of symbols per single IP and made sure no other Binance requests/connections are made in order not to abuse the rate limits, without success
- the problem seems to have only appeared several weeks ago, before that the logic was very stable and worked flawlessly
the same logic is used for obtaining OHLCV data, no issues have been observed there.

Your expertise and insights are highly valued, and any assistance you can provide in troubleshooting or optimizing our implementation would be greatly appreciated.

### Code

```
import copy
import time
from typing import Any, Dict, List, Optional, Tuple, Union
import argparse
import asyncio
from datetime import datetime, timedelta

import ccxt
import ccxt.pro as ccxtpro
import pandas as pd
import tqdm


currency_pairs = [
    "ETH/USDT:USDT",
    "BTC/USDT:USDT",
    "SAND/USDT:USDT",
    "STORJ/USDT:USDT",
    "GMT/USDT:USDT",
    "AVAX/USDT:USDT",
    "BNB/USDT:USDT",
    "APE/USDT:USDT",
    "MATIC/USDT:USDT",
    "DOT/USDT:USDT",
    "UNFI/USDT:USDT",
    "LINK/USDT:USDT",
    "XRP/USDT:USDT",
    "RUNE/USDT:USDT",
    "NEAR/USDT:USDT",
    "FTM/USDT:USDT",
    "WAVES/USDT:USDT",
    "AXS/USDT:USDT",
    "OGN/USDT:USDT",
    "DOGE/USDT:USDT",
    "SOL/USDT:USDT"
]

exchange_params: Dict[str, Any] = {}
exchange_params["rateLimit"] = True
exchange_params["options"] = {"defaultType": "future"}
binance = ccxtpro.binance(exchange_params)

async def _download_websocket(stop_time: str) -> None:
    """
    Encapsulate common logic for periodical exchange data download using
    websocket based download.
    """
    stop_time = pd.Timestamp(stop_time)
    tz = stop_time.tz
    subscribe_tasks = []
    for currency_pair in currency_pairs:
        task = binance.watchOrderBook(currency_pair, limit=None)
        subscribe_tasks.append(task)
    await asyncio.gather(*subscribe_tasks)
    print("Subscribed to binance websocket data successfully")
    print(f"Current time {pd.Timestamp.now(tz)}, Stop time {stop_time}")
    while pd.Timestamp.now(tz) < stop_time:
        iter_start_time = pd.Timestamp.now(tz)
        for curr_pair in currency_pairs:
            if binance.orderbooks.get(curr_pair):
                data_point = copy.deepcopy(binance.orderbooks[curr_pair].limit())
                print(f"Downloaded bid_ask data for {curr_pair} at {data_point['datetime']}")
        # sleep for 200ms for next data.
        print("-"*50)
        await binance.sleep(200)
    print("Websocket download finished at %s", pd.Timestamp.now(tz))
    await binance.close()

def _parse() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--stop_time",
        action="store",
        required=True,
        help="Stop time for bid ask websocket download",
    )
    return parser

def main(parser: argparse.ArgumentParser):
    args = parser.parse_args()
    asyncio.run(_download_websocket(args.stop_time))

if __name__ == '__main__':
    main(_parse())
```

**Comment by pcriadoperez** [comment]
Hi @sonaalKant,

I'm seeing with the script it throws a 1008 error. This is due to binance rate limit you see for sending too many requests to binance at the same time.

To avoid you can replace the for loop call and use instead `await watch_book_for_symbols (currency_pairs)` this will allow to subscribe to multiple pairs in one call.

Also as a second recomendation. We usually recommend to put the watch functions in a while loop with a try and catch In the following manner. This allows that if there is any disconnect to reconnect
```python
while true:
    try:
        await watch_order_book_for_symbols (currency_pairs)
    except Exception as e:
```

Please let me know if you have any other questions

**Comment by gpsaggese** [comment]
I had the same problem. Thanks @pcriadoperez
