### ISSUE TITLE
bitz fees issue

### ISSUE THREAD

**Issue by alexsith** [ccxt/ccxt#2067]
- Programming Language version: python
- CCXT version: __version__ = '1.10.1189'
- Exchange: bitz

Hello. Some of structures in bitz have wrong format:
 'funding': {
                    'withdraw': {
                        'BTC': '0.5%',
                        'DKKT': '0.5%',
                        'ETH': 0.01,
.... 

it must be float, not str

Thank you

**Comment by alexsith** [comment]
Oh.. I see it's just because they really have percent-based fee for withdrawal.. The first exchange with percent-based fee..

**Comment by alexsith** [comment]
For my structures about fiat withdraw fee I used list [percentfee,  fixedfee]. I don't know if it helps in this case.

**Comment by kroitor** [comment]
@alexsith looks like you've figured it out. Let me know if we can help with anything else here. Closing it for now, if you don't mind... Feel free to reopen it if needed, or just ask questions, if any. Thx!
