### ISSUE TITLE
Cannot set timeout lower than 1 second

### ISSUE THREAD

**Issue by m-nez** [ccxt/ccxt#20670]
### Operating System

Linux

### Programming Languages

Python

### CCXT Version

4.1.50

### Description

If timeout is set to less than 1000 ms then any method call will crash with "ValueError: Attempted to set connect timeout to 0, but the timeout cannot be set to a value less than or equal to 0."
Example code to replicate this:
```
import ccxt
b = ccxt.binance()
b.timeout = 999
b.public_get_ping()
```
A fix would be to remove "int" from line 600 in https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L600
requests.Session.request can handle float values of the timeout parameter.

### Code

```
  

```

**Comment by ttodua** [comment]
Thanks for reporting!
I'll fix that asap.

**Comment by ttodua** [comment]
when the linked PR will be merged, this issue becomes autoclosed and in around 1+ hours you'll see updated version: https://pypi.org/project/ccxt/#history
then update ccxt in your app, i'll be fixed
