### ISSUE TITLE
I get errors when I try to use proxy with ccxt

### ISSUE THREAD

**Issue by kerimSD** [ccxt/ccxt#20686]
### Operating System

Windows

### Programming Languages

JavaScript

### CCXT Version

4.1.28

### Description

I am trying to connect binance (also tried other exchanges) and retrieve my account balance by using a proxy. I've tested with http, https, socks5 proxies and with different implementations but even I can make any call without proxy, when I use proxy it gives error.

Could anyone help me about it?

### Code

```
const ccxt = require("ccxt");
const binance = new ccxt.binance({
  });
binance.proxyUrl = "https://84.39.112.144:3128/";
const ticker = await binance.fetchTicker('BTC/USDT');
console.log("ticker",ticker)
```
This code gives that error:
![image](https://github.com/ccxt/ccxt/assets/123468571/b5012ab2-335e-4f1b-aa8e-2332cc8bbf5b)

also this one gives the same error
```
 binance.socksProxy = "socks5://199.187.210.54:4145/";
```
I also tried this implementation it doesn't give any error but it seems it doesn't make request via proxy but make the request with my own IP. (I added IP access restriction to my API Key but it still makes the request)
```
 const binance = new ccxt.binance({
            proxies: "http://103.231.78.36:80/"
        });
```

**Comment by carlosmiei** [comment]
@kerimSD Hello, from the log the `proxyUrl` usage seems correct ad you can see it appended the original request to the proxyUrl.

Regarding the socks5 issue, can you double-check if your proxy works as expected outside ccxt?

Also, we have made some updates to the proxies recently, can you update your ccxt version to make if it makes a difference? 

Also, you can read more about the proxies we support here: https://docs.ccxt.com/#/README?id=supported-proxy-types

/cc @ttodua

**Comment by ttodua** [comment]
@kerimSD 
1) have you tried `binance.httpProxy` or `binance.httpsProxy` ( https://docs.ccxt.com/#/README?id=httpproxy-and-httpsproxy )  instead of `binance.proxyUrl`? `.proxyUrl` concept is different than real proxy, you can read to the link above suggested by @carlosmiei 
2) also please update your installed ccxt package to latest version and let us know after you retest with latest version

**Comment by kerimSD** [comment]
@ttodua @carlosmiei 
Thank you for your answers, I updated the ccxt and I tried both binance.httpProxy, binance.socksProxy but still I get the same error. I tried proxies outside the ccxt and it seems like they work fine: 
![image](https://github.com/ccxt/ccxt/assets/123468571/5424256a-44e3-4f5c-bf0e-63c85665d702)

Could you try to use same proxy, to see if there is a problem with proxy or ccxt?
Error:
![image](https://github.com/ccxt/ccxt/assets/123468571/40b5b98c-5eb6-43f1-b200-59b5b7fad953)

**Comment by dooly9931** [comment]
I ran into the same issue. 
### Operating System ###
macOS 14.2.1
### Programming Language ###
Typescript
### CCXT version ###
4.2.9 (latest)
### Description ###
I am getting same error with @kerimSD 

### Code ###
I have put `https://${MY_PROXY_HOST}:80/` and `http://${MY_PROXY_HOST}:80/` at `.proxyUrl`, `.httpProxy`, and `.httpsProxy`, and all of them failed. 
```ts
const proxyUrl = `http://${MY_PROXY_HOST}:80/`;
const okx = new ccxt.okx({ ...this.key, proxyUrl });
const [balances, positions] = await Promise.all([
    (await okx.privateGetAccountBalance())["data"],
    (await okx.privateGetAccountPositions())["data"],
]);
```
```
NetworkError: okx GET http://my-proxy.host:80/https://www.okx.com/api/v5/account/balance fetch failed
```
```
NetworkError: okx GET https://www.okx.com/api/v5/account/balance fetch failed
```
I also tried `HttpsProxyAgent` as `.agent`, but it also failed. 
### Test Proxy out of CCXT ###
```ts
const res1 = await axios.get("https://api.ipify.org?format=json");
console.log(JSON.stringify(res1["data"], undefined, 2));
const res2 = await axios.get("https://api.ipify.org?format=json", { proxy: { protocol: "http", host: MY_PROXY_HOST, port: 80 } });
console.log(JSON.stringify(res2["data"], undefined, 2));
```
This code worked fine. Ouput: 
```
{
  "ip": "43.103.68.0"
}
{
  "ip": "52.77.29.9"
}
```

**Comment by dooly9931** [comment]
Using `.httpAgent` instead of `.proxyUrl`, `.httpProxy`, '.httpsProxy` made my code run successfully. 
```ts
const httpAgent = new HttpProxyAgent(`http://${MY_PROXY_HOST}:80`);
const okx = new ccxt.okx({ ...this.key, httpAgent });
const [balances, positions] = await Promise.all([
    (await okx.privateGetAccountBalance())["data"],
    (await okx.privateGetAccountPositions())["data"],
]);
```
It worked! But I still don't know why `.proxyUrl` and `.httpProxy` don't work.

**Comment by kerimSD** [comment]
@dooly9931 

Yes, it looks like working fine but even though I put an IP access restriction to my API Key, it still makes the request.
Isn't that means it doesn't use the proxy?

**Comment by dooly9931** [comment]
@kerimSD 
You are right. I made a mistake during the proxy setting. I thought it worked, but it just didn't throw error, but still didn't use proxy actually.

**Comment by kerimSD** [comment]
I don't understand that if proxies don't work in ccxt at all? 
or we can't correctly implement it? If that the case whats the issue and how to use proxies correctly, Can you please help @carlosmiei @ttodua

**Comment by dooly9931** [comment]
@kerimSD 
How about trying using `.httpsProxy` with a proxy url starts with `http://`?
I think it worked for my case?
```ts
const httpsProxy = `http://${MY_PROXY_HOST}:80`;
const okx = new ccxt.okx({ ...this.key, httpsProxy });
const [balances, positions] = await Promise.all([
    (await okx.privateGetAccountBalance())["data"],
    (await okx.privateGetAccountPositions())["data"],
]);
```

**Comment by carlosmiei** [comment]
@kerimSD We use proxies daily on our tests pipeline (both for Rest and WS), so I think it is safe to say that they work.

**Comment by kerimSD** [comment]
@dooly9931 Thank you it worked! but I realise that only binance and gateio gives errors while using proxy, other exchanges like okx, kraken, huobi etc. are working fine. 
@carlosmiei I wonder is Binance and Gateio made a protection against? Did you use proxy with these exchanges as well ?

**Comment by carlosmiei** [comment]
@kerimSD We do but for public queries, we are not sure if private ones have some kind of restriction, you might also try to change the proxy location to see if it makes a difference

**Comment by ttodua** [comment]
Guys, to check if proxies work for you, please see an example at https://github.com/ccxt/ccxt/tree/master/examples and find file `proxy-usage.` there you will find how to test your proxies easily.

**Comment by bhdrgkz** [comment]
hi everyone,

### Operating System
macOS 14.2.1

### Programming Language
Javascript

### CCXT version
Latest

### Description

i think i'm missing some points. when i tried @dooly9931's code for binance i got the this error:
`NotSupported: binanceusdm you need to load JS proxy modules with `.loadProxyModules()` method at first to use proxies`

btw okx works fine.

### CODE

```
const httpsProxy = `http://USERNAME:PASSWORD@PROXY_IP:PORT`;
const binance = new ccxt.binanceusdm({ ...this.key, httpsProxy });
const balance = binance.fetchBalance();
console.log(balance)
```
