### ISSUE TITLE
CCXT PRO watch_balance supports all the exchanges. Geeting error while working with Kraken exchange.

### ISSUE THREAD

**Issue by ashishkshah48** [ccxt/ccxt#20692]
### Operating System

Ubuntu

### Programming Languages

JavaScript/Python

### CCXT Version
CCXT PRO

### Code

```
  

```

**Comment by Dan-krm** [comment]
Hi @ashishkshah48 unfortunately kraken doesn't have an endpoint that we can use for `watch_balance`
https://docs.kraken.com/websockets/

![image](https://github.com/ccxt/ccxt/assets/83686770/f877b939-cf2e-4534-8701-37e71f9de6fd)
