### ISSUE TITLE
Bybit - RateLimitExceeded error on fetchPositions() function

### ISSUE THREAD

**Issue by pastanorm** [ccxt/ccxt#20718]
### Operating System

Ubuntu

### Programming Languages

JavaScript

### CCXT Version

4.2.8

### Description

When trying to call fetchPositions() asynchronously with bybit in Node.js, I get a 10006 error (which I assume is due to rate limits). Below you could find my example code and some example output. I don't have this when running the same code for another exchange like Binance.

Code
```
const exchange = new ccxt.bybit ({
'apiKey': '...',
'secret': '...',
'enableRateLimit': true,
});

try {
const [openOrdersResponse, positionResponse, testResp] = await Promise.all([
exchange.fetchOpenOrders(),
exchange.fetchPositions(),
exchange.fetchOrders(req.body.symbol),
]);
res.json({ success: true });
} catch (error) {
console.log('viewOrders error', error);
const errorResponse = { error: error.message };
}

```

### Code

```
RateLimitExceeded: bybit {"retCode":10006,"retMsg":"Too many visits. Exceeded the API Rate Limit.","result":{},"retExtInfo":{},"time":1704663597201}

```

**Comment by carlosmiei** [comment]
Hello @pastanorm, thanks for reporting it, we will take a look at it.

**Comment by Dan-krm** [comment]
Hey @pastanorm according to this documentation the ratelimit weights are set correctly for the endpoints these methods are using: https://bybit-exchange.github.io/docs/v5/rate-limit I tried testing this pretty extensively and was unable to recreate the `RateLimitExceeded` error

Can you share your verbose output? And can you share any other part of your code that might be relevant?
```
const exchange = new ccxt.bybit ({
    'apiKey': '...',
    'secret': '...',
    'enableRateLimit': true,
    'verbose': true,
});
```

**Comment by pastanorm** [comment]
verbose result in backend
`
> backend@1.0.0 start
> node index.js

viewOrders 20
fetch Request:
 bybit GET https://api.bybit.com/v5/asset/coin/query-info? 
RequestHeaders:
 {
  'Content-Type': 'application/json',
  'X-BAPI-API-KEY': 'IQw5ef9MfFcaio8d0V',
  'X-BAPI-TIMESTAMP': '1704768582225',
  'X-BAPI-RECV-WINDOW': '5000',
  'X-BAPI-SIGN': '1a41526f64dae34ed1b9d2fb4ae61c05ddb1a98187219613d97bf9f04e12545c'
} 
RequestBody:
 undefined 

fetch Request:
 bybit GET https://api.bybit.com/v5/asset/coin/query-info? 
RequestHeaders:
 {
  'Content-Type': 'application/json',
  'X-BAPI-API-KEY': 'IQw5ef9MfFcaio8d0V',
  'X-BAPI-TIMESTAMP': '1704768582228',
  'X-BAPI-RECV-WINDOW': '5000',
  'X-BAPI-SIGN': '7beefeedc332e12ec2852fb7e3dcabf4d1f666f7b47320f983972ae06aaa1d27'
} 
RequestBody:
 undefined 

fetch Request:
 bybit GET https://api.bybit.com/v5/asset/coin/query-info? 
RequestHeaders:
 {
  'Content-Type': 'application/json',
  'X-BAPI-API-KEY': 'IQw5ef9MfFcaio8d0V',
  'X-BAPI-TIMESTAMP': '1704768582230',
  'X-BAPI-RECV-WINDOW': '5000',
  'X-BAPI-SIGN': '4758379950a65dba9e89cfd15321ab81f8f6d64a46aa76294200e1654fba55a6'
} 
RequestBody:
 undefined 

handleRestResponse:
 bybit GET https://api.bybit.com/v5/asset/coin/query-info? 200 OK 
ResponseHeaders:
 {
  'Cache-Control': 'no-store',
  Connection: 'keep-alive',
  'Content-Length': '123',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Tue, 09 Jan 2024 02:49:42 GMT',
  Ret_code: '10006',
  Server: 'Openresty',
  Timenow: '1704768582377',
  Traceid: '2a897e167583ef0828e20d80f9c04389',
  Via: '1.1 d25e24c9a13b2767614250566b710590.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'LHU8lIpQcyecsAR3VPDThpFsY6zfmc_USLxH1bPbabAmpVWgZBmdeQ==',
  'X-Amz-Cf-Pop': 'NRT57-P3',
  'X-Bapi-Limit': '2',
  'X-Bapi-Limit-Reset-Timestamp': '1704768583369',
  'X-Bapi-Limit-Status': '0',
  'X-Cache': 'Miss from cloudfront'
} 
ResponseBody:
 {"retCode":10006,"retMsg":"Too many visits. Exceeded the API Rate Limit.","result":{},"retExtInfo":{},"time":1704768582377} 

viewOrders error RateLimitExceeded: bybit {"retCode":10006,"retMsg":"Too many visits. Exceeded the API Rate Limit.","result":{},"retExtInfo":{},"time":1704768582377}
    at bybit.throwExactlyMatchedException (/node_modules/ccxt/dist/cjs/src/base/Exchange.js:3627:19)
    at bybit.handleErrors (/node_modules/ccxt/dist/cjs/src/bybit.js:7637:18)
    at /node_modules/ccxt/dist/cjs/src/base/Exchange.js:886:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async bybit.fetch2 (/node_modules/ccxt/dist/cjs/src/base/Exchange.js:3230:16)
    at async bybit.request (/node_modules/ccxt/dist/cjs/src/base/Exchange.js:3233:16)
    at async bybit.fetchCurrencies (/node_modules/ccxt/dist/cjs/src/bybit.js:1327:26)
    at async bybit.loadMarketsHelper (/node_modules/ccxt/dist/cjs/src/base/Exchange.js:909:26)
    at async bybit.fetchOrders (/node_modules/ccxt/dist/cjs/src/bybit.js:4470:9)
    at async Promise.all (index 2)
handleRestResponse:
 bybit GET https://api.bybit.com/v5/asset/coin/query-info? 200 OK 
ResponseHeaders:
 {
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Tue, 09 Jan 2024 02:49:42 GMT',
  Ret_code: '0',
  Server: 'Openresty',
  Timenow: '1704768582412',
  Traceid: '709b98920f5b897730828386af9b1e62',
  'Transfer-Encoding': 'chunked',
  Vary: 'Accept-Encoding',
  Via: '1.1 9d4586c3d96c296deb0177ba3471c4a4.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'r04q0tiTLu9zoI2S7RniH2QiVHf3eCbzDbqjJ6z_DXxrAkCU-M_4ow==',
  'X-Amz-Cf-Pop': 'NRT57-P3',
  'X-Bapi-Limit': '2',
  'X-Bapi-Limit-Reset-Timestamp': '1704768582369',
  'X-Bapi-Limit-Status': '1',
  'X-Cache': 'Miss from cloudfront'
} 
ResponseBody:
 {"retCode":0,"retMsg":"","result":{"rows":[
      ...
   ]}
 }
`

Here's frontend code.
`
  const getPositionsAndOpenOrders = (symbol) => {
    const storedJwtToken = Cookies.get('jwtToken');
    const headers = {
      'Content-Type': 'application/json', // Example header
      Authorization: `Bearer ${storedJwtToken}`, // Example header for authentication
    };
    return axios
      .post(`${process.env.REACT_APP_PROD_URI}/order/viewOrders`, { symbol }, { headers })
      .then((res) => {
        const response = res.data;
        return response;
      });
  };

  const REFRESH_POSITIONS_OPEN_ORDERS_INTERVAL_SECONDS  = 15;
  useEffect(() => {
    setInterval(async() => {
      const resp = await getPositionsAndOpenOrders("BTCUSDT");
      positions = resp.positions;
      openOrders = resp.openOrders;
    }, REFRESH_POSITIONS_OPEN_ORDERS_INTERVAL_SECONDS * 1000);
  }, [])
`

**Comment by pastanorm** [comment]
@Dan-krm , please check code.

**Comment by ct-taylor** [comment]
@pastanorm you've leaked an API key in that log

**Comment by pastanorm** [comment]
@Dan-krm , do you have any ideas?

**Comment by Dan-krm** [comment]
> @Dan-krm , do you have any ideas?

It looks like it might be triggered from fetchCurrencies because the response is showing this `'X-Bapi-Limit-Status': '0'` for the fetchCurrencies endpoint, I'll do some more testing and let you know

**Comment by pastanorm** [comment]
And another simple question.
binance ccxt has fetchPositionsRisk() function but bybit doesn't seem to have that function.
Which function should I call instead?

**Comment by Dan-krm** [comment]
@pastanorm I opened a pull request that should resolve this `RateLimitExceeded` error for you

As for your other question, binance is the only exchange that has support for `fetchPositionsRisk` which has the same values in it's parser as `fetchPositions` and `fetchPosition`, so I would recommend using either `fetchPosition` or `fetchPositions` instead

**Comment by pastanorm** [comment]
Thank you a lot.
Returning values of fetchBalance() in bybit and binance are different.
```
const viewBalance = async (req, res) => {
  try {
    const response = await exchange.fetchBalance();
    if(exchID === 'binance')
      res.json(response['info']);
    if(exchID === 'bybit') {
      const _data = {...response['info']['result']['list'][0]};
      _data.availableBalance = _data.totalAvailableBalance.length === 0 ? 0 : _data.totalAvailableBalance;
      res.json(_data);
    }
  } catch (error) {
    console.log(error);
    const errorResponse = { error: error.message };
    res.status(500).json(errorResponse);
  }
};
```
Is there any solution to get same value like in binance?

**Comment by Dan-krm** [comment]
> Thank you a lot. Returning values of fetchBalance() in bybit and binance are different.
> 
> ```
> const viewBalance = async (req, res) => {
>   try {
>     const response = await exchange.fetchBalance();
>     if(exchID === 'binance')
>       res.json(response['info']);
>     if(exchID === 'bybit') {
>       const _data = {...response['info']['result']['list'][0]};
>       _data.availableBalance = _data.totalAvailableBalance.length === 0 ? 0 : _data.totalAvailableBalance;
>       res.json(_data);
>     }
>   } catch (error) {
>     console.log(error);
>     const errorResponse = { error: error.message };
>     res.status(500).json(errorResponse);
>   }
> };
> ```
> 
> Am I doing correct? Or is there any solution to get same value like in binance?

`response['info']` will return the exchange specific data that is different for every exchange and method

If you want the CCXT unified data you can just use the `response` without searching for ['info'] or anything

**Comment by Dan-krm** [comment]
@pastanorm you could try:
```javascript
const data = response['info']['result']['list'][0]['totalAvailableBalance']
```
https://bybit-exchange.github.io/docs/v5/account/wallet-balance

**Comment by pastanorm** [comment]
I'm still getting same error. I updated ccxt into 4.2.10

**Comment by pastanorm** [comment]
@Dan-krm , please check my message.

**Comment by Dan-krm** [comment]
> I'm still getting same error. I updated ccxt into 4.2.10

4.2.10 was available yesterday. You'll have to wait until the new version is deployed, I think it happens every 12 hours

You can try to update your version again I think we're on 4.2.11 now

**Comment by pastanorm** [comment]
I updated into 4.2.11 but doesn't work @Dan-krm

**Comment by Dan-krm** [comment]
@pastanorm please post your verbose log

**Comment by Dan-krm** [comment]
> Is there any method to use websocket to fix this API Rate Limit error, @Dan-krm ?

These websocket methods are available on bybit for CCXT pro that might be relevant for you:
`watchBalance`, `watchMyTrades`, `watchOrders` and `watchPositions`
https://docs.ccxt.com/#/ccxt.pro.manual

**Comment by pastanorm** [comment]
@Dan-krm , can you let me know when the fixed version will be available to use?
