### ISSUE TITLE
Kucoin fetchOpenOrders for hf accounts not working 

### ISSUE THREAD

**Issue by iht76** [ccxt/ccxt#20716]
### Description

When I do 

`exchange.fetchOpenOrders("TLOS/USDT", undefined, undefined, {"hf":true}) `

it returns empty array, although there is open limit order.
I traced the problem to here in kucoin.js:

```
const responseData = this.safeValue(response, 'data', {});
const orders = this.safeValue(responseData, 'items', []);
```

it seems there is no 'items' key in the returned object for hf orders - it exists when fetching non hf orders.

**Comment by carlosmiei** [comment]
Hello @iht76,

Thanks for reporting it, we will fix it asap.
