### ISSUE TITLE
how to check on Phemex the midOrderSize of a specific symbol "BTC/USDT:USDT"

### ISSUE THREAD

**Issue by halefopw** [ccxt/ccxt#20719]
### Operating System

Win10

### Programming Languages

Python

### CCXT Version

ccxt-4.2.4

### Description

Hey,

I need a way to check the minOrderSize of a specific symbol for example: "BTC/USDT:USDT"

I tryed some variations of this code:

markets = exchange.fetch_markets()
symbol = 'BTC/USDT:USDT' 
for market in markets:
    if market['symbol'] == symbol:
min_position_size = market.get('info', {}).get('minQty')

I tryed the key-words: "minQty" and "minOrderSize"

Some one know how to get the minOrderSize?

### Code

exchange = ccxt.phemex({
    "apiKey": API_KEY,
    "secret": API_SECRET,
    "enableRateLimit": True,
    "permissions": ["order", "private"],
})
  

```

**Comment by carlosmiei** [comment]
Hello @halefopw,

Actually I don't think that Phemex provides that information on the API, but we will double-check it with them.

**Comment by halefopw** [comment]
@carlosmiei
Thanks a lot for checking this out!

with theyer answere this issue can be closed I think.

just as Idea:
If I make a order and the size is to low I get the error:
ccxt\base\exchange.py", line 3673, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidOrder: phemex {"code":11058,"msg":"TE_QTY_TOO_SMALL","data":null}

maybe its possible to check the minOrderSize by a request... 

I will do some test and post it if I founde a solution.

**Comment by halefopw** [comment]
hey @carlosmiei,

I am afraid that Phemex will say they not provides that information on API.

If they say there is a possibility to get this information by API pls reopen this issue and add it.

But for the moment and to close this issiue, here is a alternativ (not clean!) possibility to get this information.

import time
import ccxt

exchange = ccxt.phemex({
    "apiKey": API_KEY,
    "secret": API_SECRET,
    "enableRateLimit": True,
    "permissions": ["order", "private"],
})

count_list = []
while True:
    print("count_list_len:", len(count_list))
    try:
        if len(count_list) == 0:
            count_mulyplyter = 1
        if len(count_list) == 1:
            count_mulyplyter = 10
        if len(count_list) == 2:
            count_mulyplyter = 100
        if len(count_list) == 3:
            count_mulyplyter = 1000
        if len(count_list) > 3:
            count_mulyplyter = 10000
        amount_ask_base = 0.0001
        amount = amount_ask_base * count_mulyplyter
        symbol = "BTC/USDT:USDT"
        ticker = exchange.fetch_ticker(symbol)
        current_price = ticker['last']
        print(f"price for {symbol}: {current_price}")
        test_price = (current_price * 0.5)
        params = {'posSide': 'Long'}
        buyOrder = exchange.create_order(
            symbol=symbol,
            side="buy",
            type="limit",
            price=test_price,
            amount=amount,
            params=params,
        )
        time.sleep(2)
        print("MinOrderSize:", (count_mulyplyter * amount_ask_base))
        count_list.clear()
        exchange.cancel_all_orders(symbol=symbol)
        break
    except Exception as e:
        count_list.append("1")
        print(f"U Error: {str(e)}")
    time.sleep(1)
