### ISSUE TITLE
Binance fetch_bids_asks do not work properly with symbols parameter 

### ISSUE THREAD

**Issue by Alfavisioner** [ccxt/ccxt#20725]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

4.2.9

### Description

Binance fetch_bids_asks do not work properly with symbols parameter. It ignores symbols and query all markets. Therefore time is huge.
Spot market!

Issue is similar to:
[https://github.com/ccxt/ccxt/issues/20425](https://github.com/ccxt/ccxt/issues/20425)

Could you fix this function too?

### Code

```
        params.update({'type': 'spot'})
        tickers_dict = self.exchange.fetch_bids_asks(symbols=["ETHBTC", "DOTUSDT"] , params=params)
 

```

**Comment by carlosmiei** [comment]
Hello @Alfavisioner, thanks for your suggestion we will apply a similar fix there.

**Comment by carlosmiei** [comment]
@Alfavisioner Can you update your ccxt version to the latest and try again? I think it should be fixed now.
