### ISSUE TITLE
Bitget fetch_ohlcv API v2 : using publicSpotGetV2SpotMarketHistoryCandles ignores 'since' parameter

### ISSUE THREAD

**Issue by noel45** [ccxt/ccxt#20722]
### Operating System

Windows

### Programming Languages

Python

### Description

Hi, this is to follow up on issue [#20591](https://github.com/ccxt/ccxt/issues/20591).

I tried to use the method 'publicSpotGetV2SpotMarketHistoryCandles' for Bitget with a **start time only**, as it should be usable according to ccxt interface. However the start time is ignored in that case, since Bitget only accepts an endTime in the request. Could we then calculate the end_time based on the start_time and candles limit ? (even if the candles limit was defaulted) That would be more transparent from an end user point of view.

Example:

![image](https://github.com/ccxt/ccxt/assets/15633913/bf9715d6-6900-44a3-aa2c-12d5917b14fe)

### Code

```
daily_candlesticks = exchange.fetch_ohlcv(symbol, '1d', since=from_timestamp * msec, limit=None, params={'method': 'publicSpotGetV2SpotMarketHistoryCandles'})

```

**Comment by Dan-krm** [comment]
Hi @noel45 thanks for the suggestion, I opened a pull request that will add the emulated `since` support you're asking for

**Comment by noel45** [comment]
@Dan-krm I see this has been corrected in Typescript, what about Python ?

Also, the python logic is wrong on another point. Even with a 'until' parameter specified, the 'until' variable is ignored and the parameter "endTime" is defaulted to the current time. Putting directly an 'endTime' parameter in the request does not help, since it will also be defaulted to the current time. There is not way to use the historical query.

See issue below:

![image](https://github.com/ccxt/ccxt/assets/15633913/026bdbc7-470b-48e6-bda4-11bca9438871)
