### ISSUE TITLE
Bitrue exchange market order does not return details of completed order

### ISSUE THREAD

**Issue by juber01** [ccxt/ccxt#20727]
### Operating System

MacOS

### Programming Languages

Python

### CCXT Version

4.1.84

### Description

Bitrue Exchange market order successfully places order and fulfils the order but does not return the completed order details.  the return object states the order status=open and amost of the other fields/attributes are null.

### Code

```
  order_buy = exchange.create_market_buy_order('symbol, amount, {"newClientOrderId": clientOrderId})

```

**Comment by carlosmiei** [comment]
Hello @juber01, that's a "normal" behavior, because it takes a few ms to consolidate the information. 
You can always get all the order-related information by calling `fetch_order(id)` afterwards.

**Comment by juber01** [comment]
I don't see this issue with Binance with market orders.

**Comment by carlosmiei** [comment]
@juber01 Each exchange is different and if the information is missing in the exchange's response ccxt has to return those values as undefined/null.

**Comment by juber01** [comment]
OK thanks
