### ISSUE TITLE
new exchange how to create api

### ISSUE THREAD

**Issue by rspadim** [ccxt/ccxt#2073]
hi guys, does anyone have a guide of what should be implemented to start a new exchange integration? i read some exchanges but some doubts persists

**Comment by kroitor** [comment]
@rspadim hi! I'm going to upload a skeleton for a new exchange in a day or two. Please, hold on )

**Comment by kroitor** [comment]
@rspadim sorry for a long wait, working on the skeleton to upload asap. Will update you when it's there. Thx for your patience!

**Comment by samgermain** [comment]
Here's a guide on how to create a new exchange

https://www.youtube.com/watch?v=w4e595TJK60
https://www.youtube.com/watch?v=jJA6zw3f4QI
