### ISSUE TITLE
binance futures' watch_balance (ws and async) method returns empty (None) 'free' and 'used' fields for symbol USDT

### ISSUE THREAD

**Issue by asbeeq** [ccxt/ccxt#20734]
### Operating System

Linux

### Programming Languages

Python

### CCXT Version

ccxt v4.1.54

### Description

1. run binance ws watch_balance 
2. open/close future position
3. watch_balance returns response like {"USDT": {"total": 123, "free": None, "used": None}}

why every time on open/close positions it returns None for "**free**" of balance. P.S. "total" is correct

### Code

```    
while True:
        res = await exchange.watch_balance()
        print(res["USDT"]["free"])  # why it is None?
        print(res["USDT"]["total"])  # this returns correct value
```

**Comment by pcriadoperez** [comment]
Hi @asbeeq, 
Unfortunately this is the information that binance returns. It onyl returns the wallet balance and the cross wallet balance.
https://binance-docs.github.io/apidocs/futures/en/#event-balance-and-position-update

I'll close the issue for now but feel free to reach out with any questions
