### ISSUE TITLE
Order creation issue in HTX : linear_swap : isolated

### ISSUE THREAD

**Issue by vishalsahu2501** [ccxt/ccxt#20764]
### Operating System

Local Environment(windows 11)

### Programming Languages

JavaScript

### CCXT Version

4.2.2

### Description

Hi Team,

**Unable to place linear swap : isolated mode order in htx exchange**

Params sent while placing market buy:
```
{
  direction: 'buy'
  marginMode: 'isolated'
  offset: 'open'
}
```

**Image 1:**
![image](https://github.com/ccxt/ccxt/assets/45059136/0322d856-1ac9-44ac-b212-e63fe3ccc18f)

**Image 2:**
![image](https://github.com/ccxt/ccxt/assets/45059136/94afac18-93ff-4757-8319-ee63eecf1773)

You can check params and values in given images(Image 1, Image 2)

**However, the response received is:**
htx {"status":"error","err_code":1067,"err_msg":"The marginMode field is invalid. Please re-enter.","ts":1xxx9xx09xx31}

It seems that default `marginMode` is set to `'cross'` at line 5094. To address this, I explicitly passed `marginMode: 'isolated'` in the params to call `contractPrivatePostLinearSwapApiV1SwapOrder`.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @vishalsahu2501, thanks for reporting it.

We will take a look asap.
