### ISSUE TITLE
Upgrade bitget API to v2

### ISSUE THREAD

**Issue by kjnh10** [ccxt/ccxt#20773]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Describe the solution you'd like

See below for the detail
https://www.bitget.com/api-doc/common/release-note

**Comment by Dan-krm** [comment]
Hey @kjnh10 this update to v2 was completed last month in this pull request: https://github.com/ccxt/ccxt/pull/19996

**Comment by kjnh10** [comment]
Sorry for bothering. Thanks
