### ISSUE TITLE
PHP Notice:  A non well formed numeric value encountered in /home/{user}/ccxt/php/poloniex.php on line 269

### ISSUE THREAD

**Issue by forexhill** [ccxt/ccxt#2078]
PHP Notice:  A non well formed numeric value encountered in /home/{user}/ccxt/php/poloniex.php on line 269

- OS: Linux Ubuntu 17.10
- Programming Language version: PHP 7.1.11-0ubuntu0.17.10.1
- CCXT version: Version 1.10.1 2017-11-06
- Exchange: Poloniex
- Method: standard retrieval of ask, bid, basevol, quotevol

**Comment by kroitor** [comment]
Fixed in 1.10.1243. Thx for reporting!
