### ISSUE TITLE
Coin Mappings for HMC, MAG

### ISSUE THREAD

**Issue by forexhill** [ccxt/ccxt#2079]
HMC on okex.com ("Hi Mutual Society") is not HMC on coinexchange.io (HarmonyCoin)
https://support.okex.com/hc/en-us/articles/360000439412-Hi-Mutual-Society-HMC-Now-Available
https://www.coinexchange.io/market/HMC/BTC

MAG on okex.com (Maggie) is not MAG on coinexchange.io (Magnet)
https://support.okex.com/hc/en-us/articles/115003874432-OKEx-Launches-SHOW-VIB-MOT-UTK-MAG
https://www.coinexchange.io/market/MAG/BTC

**Comment by kroitor** [comment]
Will fix both shortly. Thx for reporting!

**Comment by dmcdo1221** [comment]
I was trying to learn how the p2p pool worked. Then it threw me back into github.com that i had hard time mining with instructions on here. Apologies. I'm only familiar with buying not mining.  I want to learn how to mine in a pool.

**Comment by dmcdo1221** [comment]
Can tell me exactly what to do instead of ruining people's code.  Or do we have to write our own codes?

**Comment by forexhill** [comment]
@dmcdo1221 this is quite unrelated to ccxt and to this ticket. You may have to ask on another forum like bitcointalk!

**Comment by forexhill** [comment]
Thank you @kroitor for the great quick fix.

**Comment by forexhill** [comment]
Another one in 2083
