### ISSUE TITLE
Update Flowbtc base api url

### ISSUE THREAD

**Issue by roni-castro** [ccxt/ccxt#2080]
FlowBtc updated it's base url according to it's api https://www.flowbtc.com.br/api/. Now the port is 8405 instead of 8400. So it's currently throwing a timeout error. 

- OS: Amazon Linux AMI release 2017.09
- Programming Language version: Javascript
- CCXT version:  1.10.1244
- Exchange: Flowbtc
- Method: fetchTicker

**Comment by kroitor** [comment]
Fixed in 1.10.1247. Thx!
