### ISSUE TITLE
Binance. Is it now possible to send a combined (OTO) limit order?

### ISSUE THREAD

**Issue by Ccon2r** [ccxt/ccxt#20807]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

Binance. Is it now possible to send a combined limit order with t/p and s/l, as can be done through the web interface on Binance on perpetual futures?

### Describe the solution you'd like

I found exchange.private_post_order_oco but it's not have take profit and not for perpetual futures.

**Comment by Immortalion** [comment]
For now, OCO orders are not supported in Binance Futures, you can check their api docs for further information.

**Comment by Dan-krm** [comment]
Thanks @Immortalion

@Ccon2r we can watch the changelog in the binance api documentation for any new support that can be added
