### ISSUE TITLE
Contribuing to CCXT

### ISSUE THREAD

**Issue by babbarc** [ccxt/ccxt#20816]
### Operating System

Archlinux

### CCXT Version

latest

### Description

I am trying to build the CCXT library after making some changes. I have set up the docker image following the contributing guide, and when I run the command 'npm run build', I always get the below error:

### Code

```
PHP Fatal error:  Uncaught Error: Interface "React\Promise\PromiseInterface" not found in /ccxt/php/pro/Future.php:10
Stack trace:
#0 /ccxt/ccxt.php(137): require_once()
#1 /ccxt/php/test/custom/syntax.php(13): include_once('...')
#2 {main}
  thrown in /ccxt/php/pro/Future.php on line 10

```

**Comment by babbarc** [comment]
Please help. I am likely making a novice mistake, but I cannot figure it out.

**Comment by sc0Vu** [comment]
Hi @babbarc 

It looks like php react issue we had solved before. Which ccxt version did you use and how do you build docker container?

**Comment by Vladinho10** [comment]
@sc0Vu I have the same issue with PHP 8.3.2. How can we fix it?

**Comment by mshumilov** [comment]
I have the same issue with the last master build in docker container. I've just disabled check-php-syntax as a temporary solution.

**Comment by laisee** [comment]
Same issue. Is there an earlier working version or a way to set aside PHP code generation?

**Comment by alisalama** [comment]
I have the same issue.  Four commands as below, no changes to anything, build fails:

Using MacOS, using docker 4.29. I have also tried docker 4.24 and 4.31.

```
git clone https://github.com/ccxt/ccxt.git
cd ccxt
docker-compose run --rm ccxt
npm run build
```

**Comment by alisalama** [comment]
> Same issue. Is there an earlier working version or a way to set aside PHP code generation?

A temporary workaround is to go in to the package.json and change the below. This skips the step that causes the php error, but obviously the the checking of the php syntax that occurs within that step will not get run, so it is not an ideal solution.

Change:
`"post-transpile": "npm run check-python-syntax && npm run check-php-syntax",`
to
`"post-transpile": "npm run check-python-syntax",`

**Comment by egorbulat98** [comment]
> I have the same issue. Four commands as below, no changes to anything, build fails:
> 
> Using ccxt@4.3.56, MacOS and docker 4.29. I have also tried docker 4.24 and 4.31.
> 
> PHP Version
> 
> ```
> ccxt# php --version
> PHP 8.1.29 (cli) (built: Jun  6 2024 16:52:57) (NTS)
> Copyright (c) The PHP Group
> Zend Engine v4.1.29, Copyright (c) Zend Technologies
>     with Zend OPcache v8.1.29, Copyright (c), by Zend Technologies
> ```
> 
> Commands Used:
> 
> ```
> git clone https://github.com/ccxt/ccxt.git --depth 1
> cd ccxt
> docker-compose run --rm ccxt
> npm run build
> ```

hi, try again pls on latest commit in master

**Comment by laisee** [comment]
Tried latest version and got error messages below for Mac OSX(Apple silicon) with "git clone ..." and "npm run force-build-slow":

> ccxt@4.3.66 check-php-syntax
> npm run check-rest-php-syntax && npm run check-ws-php-syntax


```
> ccxt@4.3.66 check-rest-php-syntax
> php -f php/test/custom/syntax.php

Checking PHP Syntax...
In case of failure, follow the rules: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

PHP Fatal error:  Uncaught Error: Interface "React\Promise\PromiseInterface" not found in /Users/usernameXXXX/code/ccxt/php/pro/Future.php:10
Stack trace:
#0 /Users/usernameXXXX/code/ccxt/ccxt.php(141): require_once()
#1 /Users/usernameXXXX/code/ccxt/php/test/custom/syntax.php(13): include_once('/Users/gavincos...')
#2 {main}
  thrown in /Users/usernameXXXX/code/ccxt/php/pro/Future.php on line 10
```

Also tried "docker-compose run --rm ccxt" which generated this error messafe

```
[ccxt 25/34] RUN apt-get install -y dotnet-sdk-7.0:                                                                                                                               
0.146 Reading package lists...                                                                                                                                                       
0.583 Building dependency tree...                                                                                                                                                    
0.664 Reading state information...                                                                                                                                                   
0.689 E: Unable to locate package dotnet-sdk-7.0                                                                                                                                     
0.689 E: Couldn't find any package by glob 'dotnet-sdk-7.0'
0.689 E: Couldn't find any package by regex 'dotnet-sdk-7.0'
------
failed to solve: process "/bin/sh -c apt-get install -y dotnet-sdk-7.0" did not complete successfully: exit code: 100
```

**Comment by egorbulat98** [comment]
> Tried latest version and got error messages below for Mac OSX(Apple silicon) with "git clone ..." and "npm run force-build-slow":
> 
> > ccxt@4.3.66 check-php-syntax
> > npm run check-rest-php-syntax && npm run check-ws-php-syntax
> 
> ```
> > ccxt@4.3.66 check-rest-php-syntax
> > php -f php/test/custom/syntax.php
> 
> Checking PHP Syntax...
> In case of failure, follow the rules: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md
> 
> PHP Fatal error:  Uncaught Error: Interface "React\Promise\PromiseInterface" not found in /Users/usernameXXXX/code/ccxt/php/pro/Future.php:10
> Stack trace:
> #0 /Users/usernameXXXX/code/ccxt/ccxt.php(141): require_once()
> #1 /Users/usernameXXXX/code/ccxt/php/test/custom/syntax.php(13): include_once('/Users/gavincos...')
> #2 {main}
>   thrown in /Users/usernameXXXX/code/ccxt/php/pro/Future.php on line 10
> ```
> 
> Also tried "docker-compose run --rm ccxt" which generated this error messafe
> 
> ```
> [ccxt 25/34] RUN apt-get install -y dotnet-sdk-7.0:                                                                                                                               
> 0.146 Reading package lists...                                                                                                                                                       
> 0.583 Building dependency tree...                                                                                                                                                    
> 0.664 Reading state information...                                                                                                                                                   
> 0.689 E: Unable to locate package dotnet-sdk-7.0                                                                                                                                     
> 0.689 E: Couldn't find any package by glob 'dotnet-sdk-7.0'
> 0.689 E: Couldn't find any package by regex 'dotnet-sdk-7.0'
> ------
> failed to solve: process "/bin/sh -c apt-get install -y dotnet-sdk-7.0" did not complete successfully: exit code: 100
> ```

you need delete old container first and recreate it with docker-compose run --rm ccxt

**Comment by laisee** [comment]
Tried removing CCXT docker image and running suggested command ("docker-compose run --rm ccxt") to recreate docker image but still seeing same error:

" => ERROR [ccxt 25/34] RUN apt-get install -y dotnet-sdk-7.0                                                                                                                    0.6s 
------                                                                                                                                                                               
 > [ccxt 25/34] RUN apt-get install -y dotnet-sdk-7.0:                                                                                                                               
0.112 Reading package lists...                                                                                                                                                       
0.506 Building dependency tree...                                                                                                                                                    
0.584 Reading state information...                                                                                                                                                   
0.608 E: Unable to locate package dotnet-sdk-7.0                                                                                                                                     
0.608 E: Couldn't find any package by glob 'dotnet-sdk-7.0'
0.608 E: Couldn't find any package by regex 'dotnet-sdk-7.0'
------
failed to solve: process "/bin/sh -c apt-get install -y dotnet-sdk-7.0" did not complete successfully: exit code: 100_"

**Comment by egorbulat98** [comment]
exit code 100 is the network error
this is not a problem with docker

**Comment by laisee** [comment]
Tried again, replacing the dotnet package with samples like "curl", "git", "python3-pip" and the docker image builds and runs Ok. So its not a network issue, instead it looks like the command for Dotnet SDK works for Linux(amd64) but not for Apple Silicon(arm64) devices. 

Updated the docker-compose.yml file to lnclude target platform ("platform: linux/amd64") and it now builds and runs on Apple Mac(m2) device. Also tested by installing buildx experimental docker feature and able to build using standard Dockerfile.

```
ccxt:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - .:/ccxt
      - /ccxt/node_modules/ # Prevents exposing container's node_modules to the host filesystem
      - /ccxt/vendor/ # Prevents exposing container's vendor to the host filesystem
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
```
