### ISSUE TITLE
kraken spot stop orders broken

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#20814]
### Operating System

linux

### Programming Languages

python

### CCXT Version

4.2.13

### Description

Kraken's stoploss orders did work in the past by manually supplying the "price2" argument (follwing the docs here: https://docs.kraken.com/rest/#tag/Trading/operation/addOrder).

Ignoring the fact that kraken spot  does support / follow the ccxt stoploss unification (neither `stopPrice`, `triggerPrice`, nor `stopLossPrice` work on spot markets and yields "reduce_only only valid for leveraged orders") - it seems like the manual workaround was also broken recently.

ccxt is now omitting the "price" argument - even though it's clearly provided.

### Code

``` python
import ccxt
exchange = ccxt.kraken({
    'apiKey': '<yourApiKey>', 
    'secret': '<yoursecret>', 
    })
pair = 'XRP/EUR'
exchange.verbose = True
params={
    "trading_agreement": "agree", 
    'price2': 0.3
}
order = exchange.create_order(pair, 'stop-loss-limit', 'sell', amount=100, price=0.2, params=params)
# The same happens with order-type "stop-loss".
``` 

This fails with `ExchangeError: kraken {"error":["EGeneral:Invalid arguments:price"]}`.

Verbose response
```
fetch Request: kraken POST https://api.kraken.com/0/private/AddOrder RequestHeaders: {'API-Key': 'xxx', 'API-Sign': 'ccc', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: nonce=1705158256976&pair=XXRPZEUR&type=sell&ordertype=stop-loss-limit&volume=100&trading_agreement=agree&price2=0.3

fetch Response: kraken POST https://api.kraken.com/0/private/AddOrder 200 ResponseHeaders: {'Date': 'Sat, 13 Jan 2024 15:04:17 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'content-encoding': 'gzip', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'cache-control': 'no-store', 'vary': 'accept-encoding', 'x-trace-id': 'xxxxxxx', '0jxctrwzz-pad': 'xxxxx.', 'x-proxy': 'gateway', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'CF-Cache-Status': 'DYNAMIC', 'Set-Cookie': '__cf_bm=6lAJxA9GUWQRTJ8ZRaduFJn_DFCrqFUopnQnBzVlfx0-1705158257-1-AYqDoSVfdcHZbGCzJGwgaynieXeGkoRhDUzdgRvwvxBWRTDpkkZB8OywGLU1Iilgj8Xr+v728aBksydPlMzZZys=; path=/; expires=Sat, 13-Jan-24 15:34:17 GMT; domain=.kraken.com; HttpOnly; Secure; SameSite=None', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '844e87e21a3db3a4-MUC'} ResponseBody: {"error":["EGeneral:Invalid arguments:price"]}
```

**edit**

i can somewhat get around this by using the following syntax - but i don't think that's correct / in the sense of how ccxt aims to unify stop-orders ...

```
params={
    "trading_agreement": "agree", 
    'price': 0.2,
    'price2': 0.3,
}
order = exchange.create_order(pair, 'stop-loss-limit', 'sell', amount=100, price=0.2, params=params)
```

**Comment by carlosmiei** [comment]
Hello @xmatthias, thanks for letting us know, we will take a look

**Comment by carlosmiei** [comment]
@xmatthias We will make some adjustments, like removing the reduceOnly by default and supporting take-profit/stop-loss market orders. However, I would like to highlight that regular stop/trigger orders (type 1) are not unified/available at Kraken, only the type 2 `stopLossPrice/takeProfitPrice` orders.

**Comment by xmatthias** [comment]
> However, I would like to highlight that regular stop/trigger orders (type 1) are not unified/available at Kraken, only the type 2 stopLossPrice/takeProfitPrice orders.

Well currently, neither of the two work on kraken spot (at least i've been unable to get them working).
I'm not particularily concerned about using either stop/trigger orders, or the stopLossPrice ordertypes, as long as either of the 2 works, i'm mostly happy ;) 

will test further if you tell me these should be available.

**Comment by carlosmiei** [comment]
@xmatthias Yeah since we were sending the reduceOnly flag by default, only margined/leveraged orders were working, but after the merge of the PR I expect all the supported order types (regular orders, and type 2 orders) to work correctly.

**Comment by xmatthias** [comment]
@carlosmiei stop order parsing doesn't seem to properly work.

```
params={
    "trading_agreement": "agree",
    'stopLossPrice': 0.3,
}
order = ct.create_order(pair, 'limit', 'sell', amount=100, price=0.2, params=params)
ct.fetch_order(order['id'], pair)

{
'id': 'OPUFRP-ALBQD-XSKSBN',
 'clientOrderId': '0',
 'info': {'id': 'OPUFRP-ALBQD-XSKSBN',
  'refid': None,
  'userref': '0',
  'status': 'open',
  'opentm': '1705256918.6999044',
  'starttm': '0',
  'expiretm': '0',
  'descr': {'pair': 'XRPEUR',
   'type': 'sell',
   'ordertype': 'stop-loss-limit',
   'price': '0.30000',
   'price2': '0.20000',
   'leverage': 'none',
   'order': 'sell 100.00000000 XRPEUR @ stop loss 0.30000 -> limit 0.20000',
   'close': ''},
  'vol': '100.00000000',
  'vol_exec': '0.00000000',
  'cost': '0.00000000',
  'fee': '0.00000000',
  'price': '0.00000000',
  'stopprice': '0.00000000',
  'limitprice': '0.00000000',
  'misc': '',
  'oflags': 'fciq',
  'reason': None},
 'timestamp': 1705256918699,
 'datetime': '2024-01-14T18:28:38.699Z',
 'lastTradeTimestamp': None,
 'status': 'open',
 'symbol': 'XRP/EUR',
 'type': 'stop-loss-limit',
 'timeInForce': None,
 'postOnly': False,
 'side': 'sell',
 'price': 0.3, <-- should be 0.2 - as this is the "limit" price ... 
 'stopPrice': 0.0,
 'triggerPrice': 0.0,
 'cost': 0.0,
 'amount': 100.0,
 'filled': 0.0,
 'average': None,
 'remaining': 100.0,
 'fee': {'cost': '0.00000000', 'rate': None, 'currency': 'EUR'},
 'trades': [],
 'fees': [{'cost': 0.0, 'rate': None, 'currency': 'EUR'}],
 'lastUpdateTimestamp': None,
 'reduceOnly': None,
 'takeProfitPrice': None,
 'stopLossPrice': None  <-- should be 0.3
}
```

![image](https://github.com/ccxt/ccxt/assets/5024695/9c38b5ca-5015-4f54-a92c-86737812f4fe)


You want me to open a new issue for this?

**Comment by carlosmiei** [comment]
@xmatthias no need, I will fix the parsing, thanks once again

**Comment by xmatthias** [comment]
@carlosmiei Great job, now it works as expected :100:
