### ISSUE TITLE
Binance. watch_positions() problems

### ISSUE THREAD

**Issue by Ccon2r** [ccxt/ccxt#20815]
### Operating System

Wndows 10

### CCXT Version

4.2.13

### Description

When working with perpetual futures, I encountered a problem. New positions do not appear, but sometimes they appear.
When I made test code to check the error, I received the error message: "Error in watch_positions: 'future'"

### Code

```python
import ccxt.pro as ccxtpro
import asyncio
from pprint import pprint


async def main():
    exchange_name = 'binance'
    api_key = '==='
    api_secret = '---'

    exchange_class = getattr(ccxtpro, exchange_name)
    exchange = exchange_class({
        'apiKey': api_key,
        'secret': api_secret,
    })

    symbollist = ['BTC/USDT:USDT', 'OP/USDT:USDT']

    # while True:
    try:
        positions = await exchange.watch_positions(symbollist)
        pprint(positions)
        
    except Exception as e:
        print(f"Error in watch_positions: {e}")
        
asyncio.run(main())

```

**Comment by samgermain** [comment]
The websocket methods are supposed to be executed within a loop, like this example from the [ccxt pro manual](https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual) 

Try putting you're coded in a loop with a condition always evaluates to true

```

// a stream-based (WebSocket) orderbook feed loop

while (condition) {

    try {

        // watch some of the public data
        orderbook = await exchange.watchOrderBook (symbol, limit)

        // do something or react somehow based on that data
        // ...

    } catch (e) {

        // handle errors
    }
}
```

**Comment by Ccon2r** [comment]
@samgermain 
Yes, that's right. That's what I did. In the example, I put a comment on the loop. To avoid receiving an endless error message.

`Error in watch_positions: 'future'`

I did the same for bybit. Everything returns correctly there.

**Comment by carlosmiei** [comment]
Hello @Ccon2r, thanks for reporting it. 

Is it possible to share some more details about the issue (stacktrace, how to reproduce, etc)?

**Comment by Ccon2r** [comment]
> Hello @Ccon2r, thanks for reporting it.
> 
> Is it possible to share some more details about the issue (stacktrace, how to reproduce, etc)?

Hello @carlosmiei 
My example immediately encounters an error. Even if there are no open positions. I don’t have enough experience to tell you anything more.

**Comment by pcriadoperez** [comment]
hi @Ccon2r , if you set `exchange.options['defaultSubType'] = 'linear'` or using `binanceusdm` instead of `binance` does it work?

**Comment by Ccon2r** [comment]
> hi @Ccon2r , if you set `exchange.options['defaultSubType'] = 'linear'` or using `binanceusdm` instead of `binance` does it work?
Hi @pcriadoperez 

> using `binanceusdm`
 - Current positions appear and new ones also appear/change

> set `exchange.options['defaultSubType'] = 'linear'`
 - Current positions appear, but new ones and changes do not appear

In both cases no error appears

**Comment by samgermain** [comment]
> Hi @pcriadoperez
> 
> > using: `exchange_name = 'binanceusdm'`
> 
>     * Current positions appear and new ones also appear/change
> 
> 
> > set: `exchange.options['defaultSubType'] = 'linear'`
> 
>     * Current positions appear, but new ones and changes do not appear
> 
> 
> In both cases no error appears

Is your problem solved then?

**Comment by carlosmiei** [comment]
@samgermain No the problem is not solved, and I managed to reproduce the issue.
@Ccon2r We will apply a fix asap, sorry for the delay.
