### ISSUE TITLE
bitget watch_order_book freeze

### ISSUE THREAD

**Issue by interenet** [ccxt/ccxt#20836]
### Operating System

Ubuntu 22

### Programming Languages

Python

### CCXT Version

Ccxt 4.2.13

### Description

I use code like https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/binance-watch-orderbook-watch-balance.py with methods: watch_order_book, watch_balance and watch_orders.
After some time (about 10 hours) watch_order_book freeze with bid > ask.
Exchange: bitget

### Code

```
  

```

**Comment by pcriadoperez** [comment]
Hi @interenet, does it throw any error or it just freezes? Are you able to reproduce it consistently or provide a verbose output?
We do recommend to keep the watch function in a while loop with a try and catch, as disconnects can happen every so often, and that way it can reconnect

**Comment by interenet** [comment]
How can i help you to catch fault? I just start code and after some time see bid > ask.

**Comment by pcriadoperez** [comment]
@interenet  you can do something like this
```
while (true) {
        try {
            const candles = await exchange.watchOHLCV (symbol, timeframe, since, limit, params)
            console.log (new Date (), candles)
        } catch (e) {
            console.log (e)
            // stop the loop on exception or leave it commented to retry
            // throw e
        }
    }
    ```
    
    I'll close this issue for now, but feel free to reach out with any questions
