### ISSUE TITLE
Coin Mapping for BCS, MDT

### ISSUE THREAD

**Issue by forexhill** [ccxt/ccxt#2083]
BCS on okex (=BIP91) vs BCS on Yobit (=BitcoinStake, as can be seen from HTML source)
https://blog.okex.com/2017/07/23/okex-will-support-bitcoin-forksbcc0-fees-of-spot-trading/

MDT on okex (=Measurable Data Token) vs MDT on Yobit (=Midnight, as can be seen from HTML source)
https://support.okex.com/hc/en-us/articles/115003734171-OKEx-Launches-MDT-World-Premiere-

**Comment by forexhill** [comment]
These are fun to do, and will help a lot with trading down the road. Expect more to come :) 👍

**Comment by forexhill** [comment]
Added MDT

**Comment by forexhill** [comment]
@kroitor I see that the first array (common_currency_code) has been updated with these changes but not the second array (currency_id). An oversight?

**Comment by forexhill** [comment]
@kroitor thanks! Is this also applicable for #2079 ?

**Comment by kroitor** [comment]
@forexhill nope, it's yobit-specific. Thx for reporting and for your attention!

**Comment by forexhill** [comment]
Thank you for ultra fast patches, very appreciated!
