### ISSUE TITLE
What is the difference between totalWalletBalance and walletBalance of coin array in fetchBalance result?

### ISSUE THREAD

**Issue by pastanorm** [ccxt/ccxt#20845]
### Operating System

Ubuntu

### Programming Languages

JavaScript

### CCXT Version

4.2.15

### Description

Hi, guys. I'm using fetchBalance() of bybit ccxt.
I'm getting result like this.
Why available balance of USDT is not displayed in totalWalletBalance or totalAvailableBalance?

```
const response = await exchange('bybit').fetchBalance();
const _data = {...response['info']['result']['list'][0]};
res.json(_data);
```

Result:
```
{
    "accountType": "CONTRACT",
    "accountIMRate": "",
    "accountMMRate": "",
    "totalEquity": "",
    "totalWalletBalance": "",
    "totalMarginBalance": "",
    "totalAvailableBalance": "",
    "totalPerpUPL": "",
    "totalInitialMargin": "",
    "totalMaintenanceMargin": "",
    "accountLTV": "",
    "coin": [
        {
            "coin": "USDT",
            "equity": "50.8716035",
            "usdValue": "",
            "walletBalance": "50.8516035",
            "borrowAmount": "",
            "availableToBorrow": "",
            "availableToWithdraw": "39.2875677",
            "accruedInterest": "",
            "totalOrderIM": "0",
            "totalPositionIM": "11.5640358",
            "totalPositionMM": "",
            "unrealisedPnl": "0.02",
            "cumRealisedPnl": "-0.0316965"
        }
    ]
}
```

Thank you.

**Comment by Dan-krm** [comment]
@pastanorm Could you share your verbose response with your API keys removed:
```
const exchange = new ccxt.bybit ({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'verbose': true,  // for debug output
})
```
You may need to check the bybit website and make sure that you have funds transferred to your `CONTRACT` account or update to a unified account.

bybit `fetchBalance` is showing the `totalAvailableBalance` and `totalWalletBalance` for me, notice that my accountType is `UNIFIED`:
```
{
  info: {
    retCode: '0',
    retMsg: 'OK',
    result: {
      list: [
        {
          totalEquity: '10012.65765593',
          accountIMRate: '0',
          totalMarginBalance: '9956.19538445',
          totalInitialMargin: '0',
          accountType: 'UNIFIED',
          totalAvailableBalance: '9956.19538445',
          accountMMRate: '0',
          totalPerpUPL: '0',
          totalWalletBalance: '9956.19538445',
          accountLTV: '0',
          totalMaintenanceMargin: '0',
          coin: [
            {
              availableToBorrow: '',
              bonus: '0',
              accruedInterest: '0',
              availableToWithdraw: '0.00131368',
              totalOrderIM: '0',
              equity: '0.00131368',
              totalPositionMM: '0',
              usdValue: '56.46227148',
              unrealisedPnl: '0',
              collateralSwitch: false,
              spotHedgingQty: '0',
              borrowAmount: '0.000000000000000000',
              totalPositionIM: '0',
              walletBalance: '0.00131368',
              cumRealisedPnl: '-0.00000131',
              locked: '0',
              marginCollateral: true,
              coin: 'BTC'
            },
            {
              availableToBorrow: '',
              bonus: '0',
              accruedInterest: '0',
              availableToWithdraw: '9959.98017692',
              totalOrderIM: '0',
              equity: '9959.98017692',
              totalPositionMM: '0',
              usdValue: '9956.19538445',
              unrealisedPnl: '0',
              collateralSwitch: true,
              spotHedgingQty: '0',
              borrowAmount: '0.000000000000000000',
              totalPositionIM: '0',
              walletBalance: '9959.98017692',
              cumRealisedPnl: '-0.06838372',
              locked: '0',
              marginCollateral: true,
              coin: 'USDT'
            }
          ]
        }
      ]
    },
    retExtInfo: {},
    time: '1705461178576'
  },
  timestamp: 1705461178576,
  datetime: '2024-01-17T03:12:58.576Z',
  BTC: { free: 0.00131368, used: 0, total: 0.00131368, debt: 0 },
  USDT: { free: 9959.98017692, used: 0, total: 9959.98017692, debt: 0 },
  free: { BTC: 0.00131368, USDT: 9959.98017692 },
  used: { BTC: 0, USDT: 0 },
  total: { BTC: 0.00131368, USDT: 9959.98017692 },
  debt: { BTC: 0, USDT: 0 }
}
```

**Comment by Dan-krm** [comment]
@pastanorm this is the endpoint that is being used: https://bybit-exchange.github.io/docs/v5/account/wallet-balance you can follow that link for an explanation of all the returned values

**Comment by Dan-krm** [comment]
@pastanorm from the documentation we can see that when not using unified mode or using unified inverse or unified isolated margin the `totalWalletBalance` and `totalAvailableBalance` fields return an empty string.

`totalWalletBalance` is the balance of your total wallet converted to USD, while `walletBalance` is the balance of each individual coin. the `walletBalance` is what is used for the `total` value in the unified CCXT response.

**totalWalletBalance:**
Wallet Balance of account converted to usd：∑ Asset Wallet Balance By USD value of each asset。In non-unified mode & unified (inverse) & unified (isolated_margin), the field will be returned as an empty string.

**totalAvailableBalance:**
Available Balance of account converted to usd：Regular mode：totalMarginBalance - totalInitialMargin. In non-unified mode & unified (inverse) & unified (isolated_margin), the field will be returned as an empty string.

**walletBalance:**
Wallet balance of current coin

**Comment by pastanorm** [comment]
How can I check if it's non-unified mode & unified (inverse) & unified (isolated_margin)

**Comment by Dan-krm** [comment]
@pastanorm you can read more about the unified trading account here:
https://www.bybit.com/en/help-center/article/FAQ-Unified-Trading-Account

You can read about the different supported account types here:
https://bybit-exchange.github.io/docs/v5/account/wallet-balance

If you're using a unified account and you initialize the exchange with an inverse defaultSubType those fields you mentioned will be empty strings.
