### ISSUE TITLE
Bitget watch_orders issue on BUY

### ISSUE THREAD

**Issue by KevinBaudin** [ccxt/ccxt#20868]
### Operating System

Ubuntu 22.04.1 LTS

### Programming Languages

Python

### CCXT Version

4.2.12

### Description

New day, new me sending you an issue !
Thanks again for all the great work

I've seeing some issues on Bitget watch_orders on BUY orders.

See in my example, amount, filled, remaining are all over the place, because Bitget sends size as quote coin instead of base coin.
Could you point me in the code where `remaining` is computed?
I guess filled is from info_accBaseVolume, amount is from info_size

Please note that for info_accBaseVolume is 0 when opening order

I did contact Bitget concerning this, but they don't plan soon to change it. I don't know if you are in touch with them, but you must have a better weight in negociation than me :)

NB: this issue does not exist on fetch_order, only watch_orders

### Code

```
OPEN STATUS:
[{'info': {'instId': 'DOGEUSDT',
   'orderId': '1131888268910444544',
   'clientOid': '88e103d1-a289-4687-b780-5f78c35b60b6',
   'size': '16.2000',
   'notional': '16.200000',
   'orderType': 'market',
   'force': 'gtc',
   'side': 'buy',
   'accBaseVolume': '0.0000',
   'priceAvg': '0.000000',
   'status': 'live',
   'cTime': '1705589113452',
   'uTime': '1705589113452',
   'feeDetail': [],
   'enterPointSource': 'API'},
  'symbol': 'DOGE/USDT',
  'id': '1131888268910444544',
  'clientOrderId': '88e103d1-a289-4687-b780-5f78c35b60b6',
  'timestamp': 1705589113452,
  'datetime': '2024-01-18T14:45:13.452Z',
  'lastTradeTimestamp': 1705589113452,
  'type': 'market',
  'timeInForce': 'GTC',
  'postOnly': False,
  'side': 'buy',
  'price': None,
  'stopPrice': None,
  'triggerPrice': None,
  'amount': 16.2,
  'cost': 16.2,
  'average': None,
  'filled': 0.0,
  'remaining': 16.2,
  'status': 'open',
  'fee': None,
  'trades': [],
  'fees': [],
  'lastUpdateTimestamp': None,
  'reduceOnly': None,
  'takeProfitPrice': None,
  'stopLossPrice': None}]

##########

CLOSED STATUS
[{'info': {'instId': 'DOGEUSDT',
   'orderId': '1131888268910444544',
   'clientOid': '88e103d1-a289-4687-b780-5f78c35b60b6',
   'size': '16.2000',
   'notional': '16.200000',
   'orderType': 'market',
   'force': 'gtc',
   'side': 'buy',
   'accBaseVolume': '202.3524',
   'priceAvg': '0.080058',
   'status': 'filled',
   'cTime': '1705589113452',
   'uTime': '1705589113646',
   'feeDetail': [{'feeCoin': 'DOGE', 'fee': '-0.2023524'}],
   'enterPointSource': 'API'},
  'symbol': 'DOGE/USDT',
  'id': '1131888268910444544',
  'clientOrderId': '88e103d1-a289-4687-b780-5f78c35b60b6',
  'timestamp': 1705589113452,
  'datetime': '2024-01-18T14:45:13.452Z',
  'lastTradeTimestamp': 1705589113646,
  'type': 'market',
  'timeInForce': 'GTC',
  'postOnly': False,
  'side': 'buy',
  'price': 0.080058,
  'stopPrice': None,
  'triggerPrice': None,
  'amount': 16.2,
  'cost': 16.2,
  'average': 0.080058,
  'filled': 202.3524,
  'remaining': -186.1524,
  'status': 'closed',
  'fee': {'cost': '0.2023524', 'currency': 'DOGE'},
  'trades': [],
  'fees': [{'cost': 0.2023524, 'currency': 'DOGE'}],
  'lastUpdateTimestamp': None,
  'reduceOnly': None,
  'takeProfitPrice': None,
  'stopLossPrice': None}]

```

**Comment by samgermain** [comment]
If you look at the [`parseWsOrder` method,](https://github.com/ccxt/ccxt/blob/1bdff9799c1fd4bd3643f135a6cdd74ae57131f0/ts/src/pro/bitget.ts#L1253) you can see that the response returned calls the method `safeOrder`. [Inside `safeOrder` you can see that remaining is calculated from `amount` and `filled`](https://github.com/ccxt/ccxt/blob/1bdff9799c1fd4bd3643f135a6cdd74ae57131f0/ts/src/base/Exchange.ts#L2616) when it cannot be explicitly read from the exchange response

------------

What issues are you experiencing?

**Comment by KevinBaudin** [comment]
'amount': 16.2,
   'filled': 202.3524,
 'remaining': -186.1524,

Those 3 values don't make any sense here.
Amount is equal to notional, which is not right
filled is correct
remaining is amount - filled which is totally not right

**Comment by samgermain** [comment]
> 'amount': 16.2, 'filled': 202.3524, 'remaining': -186.1524,
> 
> Those 3 values don't make any sense here. Amount is equal to notional, which is not right filled is correct remaining is amount - filled which is totally not right

Thanks for letting us know, I'll look into this and make the necessary changes soon

**Comment by samgermain** [comment]
> Be careful, the amount is only wrong on Buy watch orders. For now I didn't find an easy solution, I'd be glad if you find one

spot markets?
does limit or market make a difference

**Comment by KevinBaudin** [comment]
My test was on spot indeed. I think both Limit and Market don't work

**Comment by KevinBaudin** [comment]
Hi
Coming back here :) 
Do you have any news on this subject?
I'd say that the correct way would be to:
* not infer remaining is "amount - filled"
* not infer that amount is "size"
For open orders, I don't see a better solution than sending empty fields, since there is no usable ones
For closed/partially closed, filled can be grabbed from `accBaseVolume`

**Comment by carlosmiei** [comment]
@KevinBaudin thanks once again, for the detailed report, 

@samgermain are you working on it?

**Comment by KevinBaudin** [comment]
Thanks ! 
I'll check when available in a release, I don't know where will you read baseVolume, maybe I'm missing something
Also, I'm in contact with the bitget team, I'll tell you if they fix their ws

**Comment by carlosmiei** [comment]
@KevinBaudin I ran a few tests locally and seems to be working with this patch, nonetheless please test it after the release and let us know if anything.

**Comment by KevinBaudin** [comment]
Hi
I've tested on 4.2.25 and it returns an issue for me:
```
{'info': {'instId': 'DOGEUSDT',
  'orderId': '1135778018897608713',
  'clientOid': 'fc57eabe-784c-4ef9-b9d7-37014aaacc06',
  'price': '0.078500',
  'size': '15.7000',
  'notional': '15.700000',
  'orderType': 'limit',
  'force': 'gtc',
  'side': 'buy',
  'fillPrice': '0.078257',
  'tradeId': '1135778019336986632',
  'baseVolume': '59.8820',
  'fillTime': '1706516502222',
  'fillFee': '-0.059882',
  'fillFeeCoin': 'DOGE',
  'tradeScope': 'T',
  'accBaseVolume': '200.0000',
  'priceAvg': '0.078256',
  'status': 'partially_filled',
  'cTime': '1706516502117',
  'uTime': '1706516502248',
  'feeDetail': [{'feeCoin': 'DOGE', 'fee': '-0.2'}],
  'enterPointSource': 'API'},
 'symbol': 'DOGE/USDT',
 'id': '1135778018897608713',
 'clientOrderId': 'fc57eabe-784c-4ef9-b9d7-37014aaacc06',
 'timestamp': 1706516502117,
 'datetime': '2024-01-29T08:21:42.117Z',
 'lastTradeTimestamp': 1706516502248,
 'type': 'limit',
 'timeInForce': 'GTC',
 'postOnly': False,
 'side': 'buy',
 'price': 0.0785,
 'stopPrice': None,
 'triggerPrice': None,
 'amount': 59.882,
 'cost': 15.7,
 'average': 0.078256,
 'filled': 200.0,
 'remaining': -140.118,
 'status': 'open',
 'fee': {'cost': '0.2', 'currency': 'DOGE'},
 'trades': [],
 'fees': [{'cost': 0.2, 'currency': 'DOGE'}],
 'lastUpdateTimestamp': None,
 'reduceOnly': None,
 'takeProfitPrice': None,
 'stopLossPrice': None}
```
Remaining is still very suspicious, and amoun{'info': {'instId': 'DOGEUSDT',
  'orderId': '1135778018897608713',
  'clientOid': 'fc57eabe-784c-4ef9-b9d7-37014aaacc06',
  'price': '0.078500',
  'size': '15.7000',
  'notional': '15.700000',
  'orderType': 'limit',
  'force': 'gtc',
  'side': 'buy',
  'fillPrice': '0.078257',
  'tradeId': '1135778019336986632',
  'baseVolume': '59.8820',
  'fillTime': '1706516502222',
  'fillFee': '-0.059882',
  'fillFeeCoin': 'DOGE',
  'tradeScope': 'T',
  'accBaseVolume': '200.0000',
  'priceAvg': '0.078256',
  'status': 'partially_filled',
  'cTime': '1706516502117',
  'uTime': '1706516502248',
  'feeDetail': [{'feeCoin': 'DOGE', 'fee': '-0.2'}],
  'enterPointSource': 'API'},
 'symbol': 'DOGE/USDT',
 'id': '1135778018897608713',
 'clientOrderId': 'fc57eabe-784c-4ef9-b9d7-37014aaacc06',
 'timestamp': 1706516502117,
 'datetime': '2024-01-29T08:21:42.117Z',
 'lastTradeTimestamp': 1706516502248,
 'type': 'limit',
 'timeInForce': 'GTC',
 'postOnly': False,
 'side': 'buy',
 'price': 0.0785,
 'stopPrice': None,
 'triggerPrice': None,
 'amount': 59.882,
 'cost': 15.7,
 'average': 0.078256,
 'filled': 200.0,
 'remaining': -140.118,
 'status': 'open',
 'fee': {'cost': '0.2', 'currency': 'DOGE'},
 'trades': [],
 'fees': [{'cost': 0.2, 'currency': 'DOGE'}],
 'lastUpdateTimestamp': None,
 'reduceOnly': None,
 'takeProfitPrice': None,
 'stopLossPrice': None}
 ```
 Remaining amount and filled are a bit all over the place from the ws watch_orders

(No issue in fetching through rest api)

**Comment by carlosmiei** [comment]
@KevinBaudin, does it happen only with partially filled orders, or all orders?

**Comment by KevinBaudin** [comment]
For open orders, amount and remaining are None.
For closed/finished orders, amount and remaining where correct

So, yes, only issue with partially filled

**Comment by carlosmiei** [comment]
@KevinBaudin We will try to investigate it a bit further, thanks a lot for your patience 🙂

**Comment by KevinBaudin** [comment]
Thanks a lot for yours also ! This is annoying from Bitget in the first place :)

**Comment by KevinBaudin** [comment]
Coming back on this
Bitget added a new field that could be used I think (I think it's correct from my own test):
https://www.bitget.com/api-doc/common/changelog
See the newSize part

would be awesome if you could use it !
Thanks a lot
