### ISSUE TITLE
Binance withdraw function PHP throws an error

### ISSUE THREAD

**Issue by Deusing** [ccxt/ccxt#2087]
- OS: Ubuntu
- Programming Language version: PHP
- CCXT version: latest
- Exchange: Binance
- Method: withdraw

I get: 
In binance.php line 809: 
                                                                          
  Cannot use object of type Proxies\__CG__\App\Entity\Currency as array

**Comment by kroitor** [comment]
@Deusing can you please paste a minimal but complete snippet of your code to reproduce the problem and your verbose output according, following these steps: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

**Comment by kroitor** [comment]
Fixed in ccxt 1.10.1256.
