### ISSUE TITLE
entering a trade with TRAILING_STOP_MARKET

### ISSUE THREAD

**Issue by Aleksey2006** [ccxt/ccxt#20873]
### Operating System

Ubuntu

### Programming Languages

Python

### CCXT Version

4.2.18

### Description

Greetings!
Thank you for your work! Very nice library.

>>> binanceusdm

**Is it possible to create an order and set trailingPercent at once.
I was trying to instantly buy at market price and enter the trade.
But there's no purchase.** 

type_ = 'market' and try set trailingPercent

Exchange return this answer - {'info': {'orderId': '637118004', 'symbol': 'PENDLEUSDT', 'status': 'NEW', 'clientOrderId':                               'x-xcKtGhcuc82f4a731f560d82b5fafe', 'price': '0.0000000', 'avgPrice': '0.00', 'origQty': '25', 'executedQty': '0', 'cumQty': '0', 'cumQuote':
                             '0.0000000', 'timeInForce': 'GTC', 'activatePrice': '1.9808000', 'priceRate': '1.00', 'type': 'TRAILING_STOP_MARKET', 'reduceOnly': True,
                             'closePosition': False, 'side': 'BUY', 'positionSide': 'BOTH', 'stopPrice': '0.00', 'workingType': 'CONTRACT_PRICE', 'priceProtect': False, 'origType':
                             'TRAILING_STOP_MARKET', 'priceMatch': 'NONE', 'selfTradePreventionMode': 'NONE', 'goodTillDate': '0', 'updateTime': '1705614464687'}, 'id': '637118004',
                             'clientOrderId': 'x-xcKtGhcuc82f4a731f560d82b5fafe', 'timestamp': 1705614464687, 'datetime': '2024-01-18T21:47:44.687Z', 'lastTradeTimestamp': None,
                             'lastUpdateTimestamp': 1705614464687, 'symbol': 'PENDLE/USDT:USDT', 'type': 'trailing_stop_market', 'timeInForce': 'GTC', 'postOnly': False,
                             'reduceOnly': True, 'side': 'buy', 'price': None, 'triggerPrice': None, 'amount': 25.0, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 25.0,
                             'status': 'open', 'fee': None, 'trades': [], 'fees': [], 'stopPrice': None, 'takeProfitPrice': None, 'stopLossPrice': None}

**I should probably send a separate order with TRAILING_STOP_MARKET, but when I try to do this I get an error - decimal**
params ={
            'trailingPercent': 1,
            'reduceOnly': True, }
trailing_stop_loss = await exchange.create_order(coin, 'TRAILING_STOP_MARKET', side, None, params=params)

**What am I doing wrong, please help me to understand.** 

### Code

    type_ = 'market'
    amount = coin_quantity

    params ={
                'trailingPercent': 1,
                'reduceOnly': True,}
    side = 'buy'
      try:
          order = await exchange.create_order(coin, type_, side, amount, params=params)
          Exchange_log.info(f"create_buy_order_market - {order}")
          return order
      except Exception as err:
          return None

**Comment by Dan-krm** [comment]
Hey @Aleksey2006 you should send a trailing order after you already have an open position. I've opened a pull request that will provide a python example for creating a trailing percent order on binance. I'm not sure how to resolve the issue you're specifically having without seeing your verbose output or the rest of your code but here is the example summarized:
```python
symbol = 'BTC/USDT:USDT'
type = 'market'
side = 'sell'
amount = 0.1
price = None
order = await exchange.create_order(symbol, type, side, amount, price, {
    'trailingPercent': 5,
    'reduceOnly': True,
    # 'trailingTriggerPrice': 45000,
})
```
Or you can call the create_trailing_percent_order method:
```python
trailing_percent = 5
trailing_trigger_price = 45000
params = {
    'reduceOnly': True,
}
order = await exchange.create_trailing_percent_order (symbol, type, side, amount, price, trailing_percent, trailing_trigger_price, params)
```
Let me know if you are still having any issues

**Comment by Dan-krm** [comment]
@Aleksey2006 you can also refer to this section of the CCXT documentation https://docs.ccxt.com/#/README?id=trailing-orders

**Comment by Aleksey2006** [comment]
> Hey @Aleksey2006 you should send a trailing order after you already have an open position. I've opened a pull request that will provide a python example for creating a trailing percent order on binance. I'm not sure how to resolve the issue you're specifically having without seeing your verbose output or the rest of your code but here is the example summarized:
> 
> ```python
> symbol = 'BTC/USDT:USDT'
> type = 'market'
> side = 'sell'
> amount = 0.1
> price = None
> order = await exchange.create_order(symbol, type, side, amount, price, {
>     'trailingPercent': 5,
>     'reduceOnly': True,
>     # 'trailingTriggerPrice': 45000,
> })
> ```
> 
> Or you can call the create_trailing_percent_order method:
> 
> ```python
> trailing_percent = 5
> trailing_trigger_price = 45000
> params = {
>     'reduceOnly': True,
> }
> order = await exchange.create_trailing_percent_order (symbol, type, side, amount, price, trailing_percent, trailing_trigger_price, params)
> ```
> 
> Let me know if you are still having any issues

Thank you for your help!
I managed to open an order and put trailing.
Everything works perfectly!

One question remains, how to ignore the number of coins in create_trailing_percent_order? Is it possible?
`async def create_buy_order_market(coin, coin_quantity, side):

    type_ = 'market'
    amount = coin_quantity

    order = await exchange.create_order(coin, type_, side, amount)

async def create_order_trailing_stop_loss(coin, coin_quantity, side):

    trailing_percent = 0.2
    type_ = 'market'

    params = {
        'reduceOnly': True,
    }

    order = await exchange.create_trailing_percent_order(coin, type_, side, coin_quantity, None, trailing_percent, None, params)


`
