### ISSUE TITLE
stopLoss triggerPrice not working on binance futures

### ISSUE THREAD

**Issue by fistofzen** [ccxt/ccxt#20885]
### CCXT Version

4.2.18

### Description

Hello,
When I create an order with stopLoss, it is not working on binance futures.

Is there something that I am missing ? 

MY client is as follows;

        const binanceClient = new ccxt.binance({
            enableRateLimit: true,
            apiKey: process.env.API_KEY,
            secret: process.env.API_SECRET,
            hedgeMode: true,
            options: {
                defaultType: 'future',
            },

        });

### Code

```
          const params = {
            'stopLoss': {
                'type': 'market', // or 'market', this field is not necessary if limit price is specified
                'price': stopPrice, // limit price for a limit stop loss order
                'triggerPrice': triggerPrice,
            },
        }

        console.log(params);

        const orderCreate2 = await exchange.createOrder(
            coin.symbol,
            'MARKET',
            TRADE_ACTION.BUY,
            amount,
            undefined, params
        );

```

**Comment by Dan-krm** [comment]
Hey @fistofzen it looks like creating orders with stopLoss or takeProfit attached to the position aren't currently available through the binance API, creating independent stop loss, take profit and conditional orders are supported by using the `stopLossPrice`, `takeProfitPrice`, or `stopPrice` parameters, for example if you just set your parameters like this after you open a position:
```
const params = {
    'stopLossPrice': 1234,
    // 'takeProfitPrice': 1234,
    // 'stopPrice': 1234,
}
```
You can read more about the different orders you can place using CCXT here: https://docs.ccxt.com/#/README?id=placing-orders
