### ISSUE TITLE
Missing precision base/quote values in fetch/parse market

### ISSUE THREAD

**Issue by veejar** [ccxt/ccxt#20887]
### Description

For Binance exchange you added precision base and precision quote values:
https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L2372

Why this information is missing for other exchanges, for example for ByBit???
https://github.com/ccxt/ccxt/blob/master/python/ccxt/bybit.py#L1549
Information about base and quote precision present in API response.

**Comment by carlosmiei** [comment]
Hello @veejar,

Base/Quote precision is used in Binance for specific calculations related to swap positions. Most of the time (to calculate spot/number of contracts amounts and prices), the amount/price precision is used. 

With that said, we will check if we can add them on bybit, but they won't be used on the ccxt side.

**Comment by carlosmiei** [comment]
@veejar That information is available under the `price` and `amount` values, they mean exactly that.
