### ISSUE TITLE
bitstamp - fetchTrades: does not load type and side parameters

### ISSUE THREAD

**Issue by stabilus** [ccxt/ccxt#2088]
- OS: Win 7
- Programming Language version: Python 3.6
- CCXT version: 1.10.1255
- Exchange: bitstamp
- Method: fetchTrades(symbol)

The result returned from the method is:

[{'id': '56709258', 'info': {'date': '1519810392', 'tid': '56709258', 'price': '10549.96', 'type': '0', 'amount': '0.00562569'}, 'timestamp': 1519810392000, 'datetime': '2018-02-28T09:33:12.000Z', 'symbol': 'BTC/USD', 'order': None, 'type': None, 'side': None, 'price': 10549.96, 'amount': 0.00562569, 'cost': 59.35080447239999, 'fee': {'cost': None, 'currency': 'USD'}}, {'id ...

bitstamp uses type to define the side: 0=buy, 1=sell.

While the information is present in the 'info' parameter, the parameter 'side' should be derived from the 'type' and filled accordingly.

**Comment by kroitor** [comment]
This issue is fixed in the most recent version of ccxt. Thx!
