### ISSUE TITLE
Catch errors

### ISSUE THREAD

**Issue by 2l1k** [ccxt/ccxt#2090]
How can I catch errors from the API and display them on the site page?

**Comment by 2l1k** [comment]
try..catch dont working

**Comment by kroitor** [comment]
Here's an example: https://github.com/ccxt/ccxt/blob/master/examples/html/basic.html

Unfortunately, teaching the basics of HTML is beyond the scope of this library, you need to google for "JavaScript exceptions tutorial" (tons of those on the internet).

Hope it helps.
