### ISSUE TITLE
bitopro websocket endpoint must be changed

### ISSUE THREAD

**Issue by j19920816** [ccxt/ccxt#20913]
### Operating System

windows

### Programming Languages

python

### CCXT Version

4.2.19

### Description

bitopro doc has been updated https://github.com/bitoex/bitopro-offical-api-docs/blob/master/ws/summary.md,
and in https://github.com/ccxt/ccxt/blob/master/python/ccxt/pro/bitopro.py, line 32 and 33, the endpoint 9443 must be changed to 443

**Comment by sc0Vu** [comment]
Hi @j19920816 

Thanks, I'm working on it: https://github.com/ccxt/ccxt/pull/20877
