### ISSUE TITLE
Phemex - BUG - Symbol not required for fetch_my_trades [contracts]

### ISSUE THREAD

**Issue by philipperemy** [ccxt/ccxt#20912]
### Operating System

Any

### Programming Languages

Python

### CCXT Version

latest

### Description

As a matter of fact, ccxt does not even send the symbol to Phemex. It is later used to filter the results.

https://github.com/phemex/phemex-api-docs/blob/master/Public-Hedged-Perpetual-API.md
<img width="1048" alt="image" src="https://github.com/ccxt/ccxt/assets/4516927/65ff8e4d-8e52-4f00-9f6c-aec62667a1cb">

<img width="1055" alt="image" src="https://github.com/ccxt/ccxt/assets/4516927/d0e0bd28-ed28-4081-934b-392b108aacf3">

### Code

**Workaround**
```
ccxt.privateGetExchangeOrderV2TradingList(ph.ccxt.extend({'currency': 'USDT', 'limit': 200, 'offset': 0}, {'currency': 'USDT'}))
```

**Comment by sc0Vu** [comment]
Hi @philipperemy 

I think this was fixed https://github.com/ccxt/ccxt/blob/master/python/ccxt/phemex.py#L2899. Can you upgrade and take a look?

**Comment by philipperemy** [comment]
@sc0Vu thank you. I confirm it works. I forgot to update it from last week!
