### ISSUE TITLE
watch_multiple seems still have bug

### ISSUE THREAD

**Issue by hi-bingo** [ccxt/ccxt#20911]
### Operating System

Ubuntu 22.04

### Programming Languages

Python

### CCXT Version

4.2.19

### Description

I want to update ccxt from 4.1.68 -> 4.2.19, but I still have the problem mentioned in https://github.com/ccxt/ccxt/issues/20412
After I re-open the local proxy (simulate the network error), the latest ccxt stop receive the new order_book (but the uncatchable exception has gone).

### Code

```
import asyncio

import ccxt.pro as ccxtpro

print(ccxtpro.__version__)

c = ccxtpro.binance()
c.https_proxy = "http://127.0.0.1:7890"
c.wss_proxy = "socks5://127.0.0.1:7890"


async def main():
    while True:
        try:
            res = await c.watch_order_book_for_symbols(["BTC/USDT", "ETH/USDT"])
            print(res)
        except Exception as e:
            print(e)
            await asyncio.sleep(5)


if __name__ == '__main__':
    asyncio.run(main())

```

**Comment by hi-bingo** [comment]
The older ccxt using watch method, can recevie new order_book after I re-open the proxy in seconds.
But the latest ccxt using watch_multiple method just froze.

**Comment by carlosmiei** [comment]
Hello @hi-bingo, thanks a lot for reporting it it again, we will take a look asap.

**Comment by pcriadoperez** [comment]
Hi @hi-bingo , I was having trouble to reproduce the error. I tried both disconnecting my machine from the internet and raising erorrs at different parts of the code.

When disconnecting from the proxy have you waited for 9 minutes in the case of binance to see if an error is received?
In the case of binance we expect a ping every 3 minutes and allow for 2 missed ping-pongs before throwing an error, so until then the feeling could be that the program is just frozen as it's waiting for a message.

**Comment by hi-bingo** [comment]
@pcriadoperez  I test binance and wait for more than 10 minutes.
I open the verbose and it shows the log like this (after I re-open the proxy)
```
2024-01-23T02:14:46.263Z sending {'method': 'SUBSCRIBE', 'params': ['btcusdt@depth@100ms', 'ethusdt@depth@100ms'], 'id': 2}
Cannot write to closing transport
2024-01-23T02:14:51.517Z sending {'method': 'SUBSCRIBE', 'params': ['btcusdt@depth@100ms', 'ethusdt@depth@100ms'], 'id': 3}
Cannot write to closing transport
... #same message with id increase
2024-01-23T02:27:54.317Z sending {'method': 'SUBSCRIBE', 'params': ['btcusdt@depth@100ms', 'ethusdt@depth@100ms'], 'id': 152}
Cannot write to closing transport

```
I also test for kucoin, but kucoin seems just froze with no more information
```
2024-01-23T02:16:51.081Z message {"topic":"/market/level2:BTC-USDT","type":"message","data":{"changes":{"asks":[],"bids":[["39892.7","0","10550404901"],["39892.9","0.1927016","10550404900"]]},"sequenceEnd":10550404901,"sequenceStart":10550404900,"symbol":"BTC-USDT","time":1705976211011},"subject":"trade.l2update"}
2024-01-23T02:16:51.011Z
2024-01-23T02:17:07.129Z sending {'id': '103', 'type': 'ping'}
```

Other informations:
I run the posted test code on MacOS 10.15.7.
While I first found the problem on ubuntu-jammy-22.04-arm64-server-20231207 in aws machine.
For my situation, I subscribe bunch of symbols in kucoin/bybit/bitget, and I also monitor the lastest updated timestamp from the orderbook. Then my application has triggered an alert, indicating numerous timeout messages. (when I wake up I found the data is expired for more than 20000+ seconds.)

**Comment by pcriadoperez** [comment]
Hi,

It's strange last night, I was not able to reproduce by cutting off my network, but I was able by setting up a local proxy and shutting that down. And it happned both with watchOrderBook and watchOrderBookForSymbols. Therefore I thought it might be related to using a proxy.
When it froze it woould also freeze the event loop and wouldn't perform the ping check which is what I expect to throw the error in the case of a disconnection.
However with the latest version it is not happening anymore. I tried to compare the changes, and I don't see any file changes between versions that might have affected this, but it does seem to be solved.

@hi-bingo , can you try again with the latest version ?

**Comment by hi-bingo** [comment]
I try to use ccxt==4.2.21, and it still have the problem. Looks like it froze the event loop. 
But in my production environment, I did not use any proxies, I run my application in aws tokyo ec2.
Maybe using proxy to simulate the network error is not a good idea.
I will try to directly test the simplest script in my ec2 (without any proxies), and collect the logs to locate the problem.
Thanks for your fast reply!

**Comment by hi-bingo** [comment]
I run this simple script on aws ec2.
I run twice, first run the monitor and  watch_ticker_by_watch , second run the monitor and watch_orderbook_by_watch_multiple. The result shows they will all be freezed after hours of work. 
Looks like some exception are swallowed.

```
import logging
import asyncio
import time
import ccxt.pro as ccxtpro
import sys

logging.basicConfig(format="%(asctime)s:%(levelname)s:%(message)s", level="INFO")

logging.info(sys.version)
logging.info(ccxtpro.__version__)

exchange = ccxtpro.bitget()

last_update_ts = 0.0


async def monitor():
    while True:
        await asyncio.sleep(600)
        now_ts = int(time.time() * 1000)
        elapsed_ts = now_ts - last_update_ts
        if elapsed_ts > 600_000:
            logging.warning("data timeout for {}ms".format(elapsed_ts))


async def watch_ticker_by_watch():
    global last_update_ts
    logging.info("start watch ticker...")
    while True:
        try:
            ticker = await exchange.watch_ticker("BTC/USDT")
            last_update_ts = ticker["timestamp"]
        except Exception as e:
            logging.error(e)
            await asyncio.sleep(5)


async def watch_orderbook_by_watch_multiple():
    global last_update_ts
    logging.info("start watch order book..")
    while True:
        try:
            orderbook = await exchange.watch_order_book_for_symbols(
                ["BTC/USDT"]
            )
            last_update_ts = orderbook["timestamp"]
        except Exception as e:
            logging.error(e)
            await asyncio.sleep(5)


async def main():
    coros = []
    coros.append(monitor())
    coros.append(watch_ticker_by_watch()) 
    coros.append(watch_orderbook_by_watch_multiple())
    await asyncio.gather(*coros)


if __name__ == "__main__":
    asyncio.run(main())

```
The first log 
```
2024-01-26 19:00:18,256:INFO:3.11.5 (main, Sep 11 2023, 13:14:08) [GCC 11.2.0]
2024-01-26 19:00:18,256:INFO:4.2.21
2024-01-26 19:00:18,270:INFO:start watch ticker...
2024-01-27 02:50:18,311:WARNING:data timeout for 606560ms
2024-01-27 03:00:18,313:WARNING:data timeout for 1206562ms
2024-01-27 03:10:18,315:WARNING:data timeout for 1806564ms
2024-01-27 03:20:18,316:WARNING:data timeout for 2406565ms
...
```

The second log
```
2024-01-26 19:00:51,878:INFO:3.11.5 (main, Sep 11 2023, 13:14:08) [GCC 11.2.0]
2024-01-26 19:00:51,878:INFO:4.2.21
2024-01-26 19:00:51,891:INFO:start watch order book..
2024-01-27 02:50:51,933:WARNING:data timeout for 640875ms
2024-01-27 03:00:51,935:WARNING:data timeout for 1240877ms
2024-01-27 03:10:51,937:WARNING:data timeout for 1840879ms
...
```

**Comment by pcriadoperez** [comment]
@hi-bingo , can you confirm if the issue is solved with the latest ccxt version?

**Comment by hi-bingo** [comment]
@pcriadoperez Thanks a lot ! 
I test the ccxt=4.2.26 and run the above test code on bitget
The freeze problem has solved.
But I found that after first network error, the next watch_order_book_for_symbols will always raise InvalidNonce error.
The log look likes:
```
2024-01-29 20:58:33,084:INFO:3.11.5 (main, Sep 11 2023, 13:14:08) [GCC 11.2.0]
2024-01-29 20:58:33,085:INFO:4.2.26
2024-01-29 20:58:33,103:INFO:start watch order book..
2024-01-29 23:30:34,250:ERROR:Cannot write to closing transport
2024-01-29 23:30:39,454:ERROR:bitget invalid checksum
2024-01-29 23:30:44,457:ERROR:bitget invalid checksum
2024-01-29 23:30:49,460:ERROR:bitget invalid checksum
... # raise the same error
```

**Comment by hi-bingo** [comment]
@pcriadoperez  After 2 days running, I'm sure the freeze problem is sloved.
I think the problem about bitget is due to that
![image](https://github.com/ccxt/ccxt/assets/14290851/77aad61e-af13-4b99-8ddd-9583b3d067ff)
After Invalid Nonce, the client.subscriptions[messageHash] is not deleted and it can't receive the snapshot data. So each incremental data will continuously cause the Invalid Nonce error.
Maybe I should open another issue to report this?
