### ISSUE TITLE
Unable to query contract funds from Phemex

### ISSUE THREAD

**Issue by ThatOneCalculator** [ccxt/ccxt#20929]
### Operating System

Linux

### Programming Languages

JavaScript

### CCXT Version

4.2.18

### Description

I'm unable to query funds from the contract. It seems that `/api-data/futures/v2/tradeAccountDetail` isn't wrapped by ccxt yet? https://phemex-docs.github.io/#query-funds-detail

### Code

n/a

**Comment by ThatOneCalculator** [comment]
@sc0Vu @carlosmiei might have to reopen this, seems that despite the docs leading me to think so, this isn't actually the correct method to get total funds, rather, it gets fund history 🤔

**Comment by ThatOneCalculator** [comment]
if that could be documented somewhere that'd be really helpful

**Comment by carlosmiei** [comment]
@ThatOneCalculator Wil that to the method's documentation.

Basically using `code: USD` will call this endpoint `/accounts/accountPositions?currency=USD` (useful if you have USD contracts), where as `code: USDT` uses this one `g-accounts/accountPositions?currency=USDT`

**Comment by ThatOneCalculator** [comment]
Ty for clarifying!
