### ISSUE TITLE
How to check if API Key has trade permission?

### ISSUE THREAD

**Issue by fl0wo** [ccxt/ccxt#20924]
### Operating System

Linux Ubuntu 22LTS

### CCXT Version

4.1.65

### Description

Hi,

i was wondering if there's a way, given a ccxt instance (of any exchange) to check if the provided api keys has TRADE permissions.

For read permission check, its simple, all I need to do is run:
`ccxtInstance.fetchBalance();`
And if I'm able to read the balance, the API Keys has the READ permissions.

Now for TRADE is more complicated, as it's a "write operation", is there a way to place a "fake limit order" and maybe cancel it immediately after? Would that work, or is there a smarter/safer way?

Thanks for any advice.

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @fl0wo,

It depends on exchange, eg. you can use privateGetV5UserQueryApi to check permission in bybit.

To send test order in binance, it only support spot / margin market, and you can set 'test' in params (https://github.com/ccxt/ccxt/blob/master/ts/src/binance.ts#L4519).

**Comment by fl0wo** [comment]
I see,
for my use case, I'd like to find a "general way" to test this behaviour for all exchanges.

Consequently, is there no way (even a work-around) to verify that with a ccxt instance I can place orders?

I was thinking of placing an order in a "safe way" and cancel it immediately after:

Like a limit-order BTC @ 1000$ (impossible order), and place it as IOC (immediate or cancel), and catching the error of that execution.

If the APIs are invalid, I should receive AuthenticationError, instead I should receive the error related to the single order.
Or the other way around?

Is it possible to accomplish such a thing?
Thanks again.
