### ISSUE TITLE
Python asyncio example returns error

### ISSUE THREAD

**Issue by x1rubinho1x** [ccxt/ccxt#2092]
I'm trying the python asyncio example as described in the [documentation](https://github.com/ccxt/ccxt/wiki/Manual#synchronous-vs-asynchronous-calls):
```
async def print_poloniex_ethbtc_ticker():
    poloniex = ccxt.poloniex()
    poloniex.verbose = True
    print(await poloniex.fetch_ticker('ETH/BTC'))
    #await poloniex.close()
```
I call this from my main:
```
asyncio.get_event_loop().run_until_complete(print_poloniex_ethbtc_ticker())
```
This runs once successfully and prints price info but then returns an error:
```
poloniex requires to release all resources with an explicit call to the .close() coroutine.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f191c3ba748>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f1922aac630>, 53794.981069543)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f191c3ba6a0>
```
This also happens using binance as the exchange.  

I added an exchange.close() call which is commented out above.  When this is uncommented the example runs, prints price info once and then exits with no error.  

I'm running cpython 3.6.3 inside Eclipse PyDev under Ubuntu 17.20.  asyncio is 3.4.3 and ccxt is 1.10.1258.  

Is this example out of date?  What needs to be done to correct this?  Thanks!

**Comment by kroitor** [comment]
Have you tried closing it, as it says in the first line of that message? For some reason, your last line is commented out...

```Python
async def print_poloniex_ethbtc_ticker():
    poloniex = ccxt.poloniex()
    poloniex.verbose = True
    print(await poloniex.fetch_ticker('ETH/BTC'))
    await poloniex.close()

asyncio.get_event_loop().run_until_complete(print_poloniex_ethbtc_ticker())
```

↑ Does this work?

**Comment by x1rubinho1x** [comment]
I tried the close line (it's not there at all in the documentation).  When it's executed the error message isn't produced but print_poloniex_ethbtc_ticker() only gets called once before exiting.  I'm expecting it to be called every time a new ticker comes in from the exchange until told otherwise.

**Comment by kroitor** [comment]
@x1rubinho1x 

> I'm expecting it to be called every time a new ticker comes in from the exchange until told otherwise.

You have put there the code to do it just once, so there's no reason to expect that it will do it continuously, unless you specifically tell it to do so.

See these examples on how this is done asynchronously with async generators in python or in basic synchronous modes:

- https://github.com/ccxt/ccxt/blob/master/examples/py/async-generator-ticker-poller.py
- https://github.com/ccxt/ccxt/blob/master/examples/py/basic-rate-limiting.py
- https://github.com/ccxt/ccxt/blob/master/examples/py/

I'd recommend to learn more about Python asyncio concepts and google for "python asyncio tutorial"

**Comment by x1rubinho1x** [comment]
@kroitor OK this is the first time I've used the asyncio model so I must have made an incorrect assumption.  Thanks for your suggestions of where to look next.

**Comment by kroitor** [comment]
@x1rubinho1x 

I've added an example of continuous polling that does just what you want: https://github.com/ccxt/ccxt/blob/master/examples/py/async-generator-basic.py

**Comment by x1rubinho1x** [comment]
@kroitor Yes that works well, thanks very much for your help!

**Comment by wanwu** [comment]
How would I feed this data into something like Dash? Would it be a coroutine or a seperate thread?
