### ISSUE TITLE
A first step for Websockets

### ISSUE THREAD

**Issue by TomAshley303** [ccxt/ccxt#2094]
Let's go ahead and implement websockets for Bitmex. They already have a python and node wrapper:

https://github.com/BitMEX/api-connectors/tree/master/official-ws

**Comment by kroitor** [comment]
> They already have a python and node wrapper:

Yep, we know of it, of course. The thing is knowing all exchange-specific wrappers does not help.
 
I suggest to move this discussion here: https://github.com/ccxt/ccxt/issues/56#issuecomment-358274362

> Let's go ahead and implement websockets for Bitmex.

Yep, feel free to submit your PRs and commits. Thx!

Please, make sure to follow these guides:

- https://gist.github.com/kroitor/aabecc346a5bded6ead7a82205d8ffc1
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
