### ISSUE TITLE
Invalid API Key Bitmex

### ISSUE THREAD

**Issue by kk3nny** [ccxt/ccxt#2096]
- OS: Windows 10
- Programming Language version: Python 2.7.14
- CCXT version: 1.10.1265
- Exchange: Bitmex
- Method: Authentication error

```
print bitmex.fetch_balance()
  File "C:\Python27\lib\site-packages\ccxt\bitmex.py", line 18
3, in fetch_balance
    response = self.privateGetUserMargin({'currency': 'all'})
  File "C:\Python27\lib\site-packages\ccxt\base\exchange.py",
line 291, in request
    return self.fetch2(path, api, method, params, headers, bod
y)
  File "C:\Python27\lib\site-packages\ccxt\base\exchange.py",
line 288, in fetch2
    return self.fetch(request['url'], request['method'], reque
st['headers'], request['body'])
  File "C:\Python27\lib\site-packages\ccxt\base\exchange.py",
line 361, in fetch
    self.handle_errors(response.status_code, response.reason,
url, method, self.last_response_headers, self.last_http_respon
se)
  File "C:\Python27\lib\site-packages\ccxt\bitmex.py", line 48
0, in handle_errors
    raise AuthenticationError(self.id + ' ' + self.json(respon
se))
ccxt.base.errors.AuthenticationError: bitmex {"error":{"messag
e":"Invalid API Key.","name":"HTTPError"}}
```
I'm getting this error, I deleted the old api and generated a new one but still the same error.
The code is below :
```
import ccxt

bitmex = ccxt.bitmex({'apiKey':'keyhere', 'secret':'secrethere'})

print bitmex.fetch_balance()
```

**Comment by kroitor** [comment]
Are you sure that you're not misplacing the API credentials? Also, did you make sure to copy all symbols of the secret precisely?

**Comment by kk3nny** [comment]
Yes I'm sure that the API and the secret both are absolutely accurate.

**Comment by kroitor** [comment]
@kk3nny and you didn't bind it to a CIDR subnet, right? (just trying to rule out possible reasons).

**Comment by kk3nny** [comment]
No it's not binded, any IP is allowed.

**Comment by kroitor** [comment]
@kk3nny do you have a problem with this key:

```Python
import ccxt
bitmex = ccxt.bitmex({
    'apiKey': 'dj6COXW4o1xFIKlVkmbXeF1n',
    'secret':'VDIwt_CYzpAqG6hdrCvU8jqbORK3EVSg0Ccn-VcOCEp5eFk-',
})
print(bitmex.fetch_balance())
```
? 

It does work for me with Python 2.7.

Are you sure your code does not mistakenly override the keys somewhere?

**Comment by kk3nny** [comment]
Thank you for looking into my issue and yes this key worked. I think the problem was that I was using a key generated from testnet.bitmex.com so that I would be able to use testnet bitcoins. I generated keys from bitmex.com this time which worked fine for me. Is there a way that I can run the testnet keys?

**Comment by kroitor** [comment]
@kk3nny 

>  Is there a way that I can run the testnet keys?

Yes, there is:

```Python
import ccxt
exchange = ccxt.bitmex({
    'apiKey': 'YOUR_TESTNET_KEY',
    'secret': 'YOUR_TESTNET_SECRET',
})
if 'test' in exchange.urls:
exchange.urls['api'] = exchange.urls['test'] # ←----- switch the base URL to testnet
print(bitmex.fetch_balance())
```

Let us know if this does not help. Closing it for now, if you don't mind. Feel free to reopen it or just ask questions if you have any. Thx!

**Comment by kk3nny** [comment]
Hello @kroitor ,

I checked with the bitmex.py file but there is no function to close open positions. Can you help me with this please?

**Comment by kroitor** [comment]
@kk3nny you should read this ;) 

https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

```Python
mbp:python igorkroitor$ python
Python 2.7.13 (default, Jun  5 2017, 10:04:07)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> from pprint import pprint
>>> pprint(dir(ccxt.bitmex()))
['__class__',
 '__del__',
 '__delattr__',
 '__dict__',
 '__doc__',
 
 ...
 
 'privatePostOrderCancelAllAfter',
 'privatePostOrderCancelallafter',
 'privatePostOrderClosePosition',   # ←--------------------------------- ?
 'privatePostOrderCloseposition',   # ←--------------------------------- ?
 'privatePostPositionIsolate',
  
 ...
 
 'private_post_order_bulk',
 'private_post_order_cancelallafter', # ←--------------------------------- ?
 'private_post_order_closeposition', # ←--------------------------------- ?
 'private_post_position_isolate',
 
 ...
 
 'withdraw',
 'ymd',
 'ymdhms']
>>>
```

**Comment by kk3nny** [comment]
Thank you so much! I'm very grateful that you created such an amazing library which helps people like me to achieve their desired goal.
