### ISSUE TITLE
Portfolio Margin trading on Binance

### ISSUE THREAD

**Issue by KevinBaudin** [ccxt/ccxt#20977]
### Operating System

Ubuntu 22.04.1 LTS

### Programming Languages

Python

### CCXT Version

4.2.12

### Description

Hi
We would be interested in using the Portfolio Margin from Binance through ccxt.
I found your abstract methods, `papi`
Can you confirm that it's not used in the ccxt code for now?
Do you plan to implement it?

Thanks a lot

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @KevinBaudin,
Yes we do, we're just trying to get a binance account that supports the portfolio margin.

**Comment by KevinBaudin** [comment]
great news ! Thanks a lot

**Comment by carlosmiei** [comment]
Hello @KevinBaudin, just letting you know that as of 4.2.47 the portfolioMargin support is pretty much complete on the REST side. 

You can easily select the porfolioMargin endpoint by providing `porfolioMargin: True` inside `params`, or setting it as a global option:

```Python
exchange.options['portfolioMargin'] = True
```

You can easily check if some unified method has support for `portfolioMargin` by checking our docs, example:
https://docs.ccxt.com/#/exchanges/binance?id=fetchmytrades
![image](https://github.com/ccxt/ccxt/assets/43336371/b68389ae-1f47-4ab7-a8dc-8a69deb01d1d)


Let us know if anything!

**Comment by KevinBaudin** [comment]
Great news ! I'll test it in the near future :)

**Comment by KevinBaudin** [comment]
Hi, I've started to test. 
To trade ETH/USDT in portfolio margin, I must use ETH/USDT:USDT and params portfolioMargin:True in create_order, am I right?
Since the papi endpoint is used only for linear markets
