### ISSUE TITLE
Failed to load https://api.binance.com/api/v1/exchangeInfo: No 'Access-Control-Allow-Origin' header is present on the requested resource. 

### ISSUE THREAD

**Issue by authenticfake** [ccxt/ccxt#2097]
Hi,
- OS: MacOS High Sierra 
- Programming Language version: node.js, javascript
- CCXT version: 1.10.1265
- Exchange: binance
- Method: withdraw, all method behind authentication

Maybe this issue is due my low knowledge on node, js and ui building.
Let me explain the scenario. 
I built a web application based on node.js, socket.io and html/js for managing all my accounts/ wallets via unique portal. Just for simplify some operations on exchanges and apply some rule on trading trades

The problems that I have is on the UI via JS (https://unpkg.com/ccxt) during the invoke on some apis, in particular on the withdraw api on binance I receive the following error 

> Failed to load https://api.binance.com/api/v1/exchangeInfo: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.1.101:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

the unique way to avoid this issue is to apply CORS, it is fine for all other exchanges that support this API w/o any IP restriction on client IP. 
Now I don't know I can invoke the withdraw API  via JS without the error described 
above and how I can avoid the IP restricted requested by binance via CORS. Is it possible?

Thanks for all,
andrea

**Comment by kroitor** [comment]
- Does fetchBalance produce the same result?
- Have you read this: https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin
- Are you sure you're setting up a CORS-proxy properly? Can you post your html-code to reproduce the problem (without the keys), or share a link to a repo maybe?
- Does it happen with any other exchange that `has['CORS'] == true` ?

**Comment by authenticfake** [comment]
Hi,

> Does fetchBalance produce the same result?
Yes for all API invoked via JS (https://unpkg.com/ccxt) without CORS set as proxy in the exchange istance.

> Have you read this: https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin
yes sure, thanks for all documentation you provided so far. I attached my cors node application

> Are you sure you're setting up a CORS-proxy properly?
I hope yes. I set CORS proxy in the following way:
`const exchange =  exchanges["binance"];
//exchange.proxy =exchange.has['CORS']?'http://localhost:8080/':undefined
exchange.proxy ='http://localhost:8080/'`

It seems that via HTML/JS is mandatory set the CORS as proxy for the exchange otherwise I receive 

> No 'Access-Control-Allow-Origin' header is present on the requested resource
Can you post your html-code to reproduce the problem (without the keys), or share a link to a repo maybe?
[cors-aca.js.zip](https://github.com/ccxt/ccxt/files/1771539/cors-aca.js.zip)

[js.code.zip](https://github.com/ccxt/ccxt/files/1771586/js.code.zip)

> Does it happen with any other exchange that has['CORS'] == true ?

Sorry, I didn't try it, I'll keep you updated soon

thanks, let me know if you need all source code

**Comment by kroitor** [comment]
@authenticfake sorry for a long wait, i'm a little overloaded recently...

> how can avoid the issue on binance when I invoke the withdrawal api via browser?

From your description is looks like you should either:
- not bind to the IP at all when using binance via a CORS proxy
- bind to the IP of the CORS proxy, not yours...
- use your own CORS-proxy locally on your machine with a key bound to your IP, more about it here: https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin

There's no other good workarounds for that, unless you're ready to wait until Binance add CORS support to their system... Let me know if it answers your question or not.

**Comment by authenticfake** [comment]
thanks @kroitor for the clarification. Yes you answered to my question...great man;)

**Comment by iliaChinchaladze** [comment]
@authenticfake  Hello from future)) Have u solved the problem regarding 'Access-Control-Allow-Origin' while calling fetchBalance() ?

Thanks in advance

**Comment by kroitor** [comment]
@iliaChinchaladze please, check this link: https://github.com/ccxt/ccxt/wiki/install#cors-access-control-allow-origin
