### ISSUE TITLE
Phemex - fetch_positions() bug

### ISSUE THREAD

**Issue by philipperemy** [ccxt/ccxt#20983]
### Operating System

Any

### Programming Languages

Python

### CCXT Version

latest

### Description

```
perp_list = [a['symbol'] for a in self.ccxt.markets.values() if a['swap'] and a['settle'] == 'USDT' and a['quote'] == 'USDT']
self.ccxt.fetch_positions(symbols=perp_list) # fails!
```

<img width="1127" alt="image" src="https://github.com/ccxt/ccxt/assets/4516927/78ff6d3e-1366-43db-bc6a-24d51fdfed18">

`Positions = {'userID': '5090671', 'accountID': '50906710003', 'symbol': 'ONDOUSDT', 'currency': 'USDT', 'side': 'None', 'positionStatus': 'Normal', 'crossMargin': False, 'leverageRr': '50', 'initMarginReqRr': '0.02', 'maintMarginReqRr': '0.01', 'riskLimitRv': '25000', 'size': '0', 'valueRv': '0', 'avgEntryPriceRp': '0', 'avgEntryPrice': '0', 'posCostRv': '0', 'assignedPosBalanceRv': '0', 'bankruptCommRv': '0', 'bankruptPriceRp': '0', 'positionMarginRv': '0', 'liquidationPriceRp': '0', 'deleveragePercentileRr': '0', 'buyValueToCostRr': '0.021188', 'sellValueToCostRr': '0.021212', 'markPriceRp': '0.22923333', 'estimatedOrdLossRv': '0', 'usedBalanceRv': '0', 'cumClosedPnlRv': '0', 'cumFundingFeeRv': '0', 'cumTransactFeeRv': '0', 'transactTimeNs': '0', 'takerFeeRateRr': '0.0006', 'makerFeeRateRr': '0.0001', 'term': '1', 'lastTermEndTimeNs': '0', 'lastFundingTimeNs': '0', 'curTermRealisedPnlRv': '0', 'execSeq': '0', 'posSide': 'Merged', 'posMode': 'OneWay', 'buyLeavesValueRv': '0', 'sellLeavesValueRv': '0'}`

It should be something like `self.parse_number(position['leverageRr'])`

```
    result.append(self.parse_position(position))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    leverage = self.parse_number(Precise.string_abs((self.safe_string(position, 'leverage', 'leverageRr'))))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return str(Precise(string).abs())
               ^^^^^^^^^^^^^^^
    number, modifier = number.split('e')
    ^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
<img width="1117" alt="image" src="https://github.com/ccxt/ccxt/assets/4516927/b1c52f4b-df3a-4478-bb5e-e5954c6b9c24">
```

### Code

cf. above.

**Comment by carlosmiei** [comment]
Hello @philipperemy, thanks for letting us know, we will fix it asap.

**Comment by carlosmiei** [comment]
@philipperemy Can you please update it to the latest version and try again? 4.2.24

**Comment by philipperemy** [comment]
@carlosmiei I can confirm it works now thanks!
