### ISSUE TITLE
Upbit fetch_deposit_address needs to be changed

### ISSUE THREAD

**Issue by SkyDominator** [ccxt/ccxt#20984]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

latest

### Description

The current syntax for fetch_depsoit_address for Upbit is:
`exchange.fetch_deposit_address('XRP', {'network': 'XRP'})`

But it doesn't work, returning invalid_parameter error.

Please change it into: 
`exchange.fetch_deposit_address('XRP', {'net_type': 'XRP'})`

Also, in the second param, `net_type` is not an optional anymore. It is an required param now. 
So, {'net_type': 'XRP'} itself is an required param now. 

Please check this out and fix this bug.

Ref: https://docs.upbit.com/reference/%EA%B0%9C%EB%B3%84-%EC%9E%85%EA%B8%88-%EC%A3%BC%EC%86%8C-%EC%A1%B0%ED%9A%8C

### Code

```
  

```

**Comment by samgermain** [comment]
This PR will fix this issue once merged, so that you will be able to pass in `{"network": "XRP"}` to `fetchDepositAddress`
