### ISSUE TITLE
ccxt pro close() cause ExchangeClosedByUser: binance closedByUser

### ISSUE THREAD

**Issue by ingtellect** [ccxt/ccxt#20992]
### Operating System

Windows 10

### Programming Languages

JavaScript

### CCXT Version

4.2.25

### Description

I try to close ccxt pro websocket connection when react(next.js) component is unmounted.
But when I call close() on unmount "ExchangeClosedByUser: binance closedByUser" error occurs.
Even if close function is inside try-catch I couldn't handle the error.
I tested binance, okx and bybit and all have same error.

I attach useCcxtPro code here.

And the minimal reproducible example is here
https://github.com/ingtellect/ccxt-close-test

Go to tab 1 and move to home or tab2 then error occurs.

Both dev and production build have same issue.

### Code

```
import { useEffect } from 'react';
import ccxt from 'ccxt';

export const useCcxtPro = (exchange, symbols, onMessage) => {
  let ccxtProExchange = null;

  useEffect(() => {
    if (!ccxtProExchange) {
      ccxtProExchange = new ccxt.pro[exchange];
    }
    console.log("useCcxtPro");

    const watch = async () => {
      const method = ccxtProExchange.has.watchTickers
        ? "watchTickers"
        : "fetchTickers";

      while (true) {
        const response = await ccxtProExchange[method](symbols);
        onMessage(response);
        console.log("ccxt onmessage");
      }
    }

    watch();

    return () => {
      async function close() {
        try {
          await ccxtProExchange.close();
        }
        catch(error) {
        }
      }
      console.log(`useCcxtPro unmount`);
      console.log(`ccxt ${exchange} closed`);
      try {
        close();
      }
      catch(error) {
        console.error(error);
      }
    }

  }, []);
}  

```

**Comment by pcriadoperez** [comment]
Hi @ingtellect , you need to sorround `const response = await ccxtProExchange[method](symbols);` also in a try and catch clause.
This was introduced recently so that you don't have a loop waiting indefinetly once the websocket is closed.
In the repo you provided I sorrounded that line with a try, catch and  I was able to switch between tabs without any raised error.

I'll close this issue for now, but feel free to reach out with any other questions.
