### ISSUE TITLE
btcturk missing marketsymbol

### ISSUE THREAD

**Issue by Esc4pism** [ccxt/ccxt#2099]
the markets in BTCTurk are hardcoded, and contain only BTC/TRY, ETH/TRY and ETH/BTC, but their tickers return 1 more (maybe new?) market: XRPTRY

taking from their docs, i believe that https://www.btcturk.com/api/ticker "should" always return all of their markets, since they also return 24 hour volumes, low/high, and show an example in the docs with 0 volumes and prices. So perhaps this could be used to fetch markets instead of hardcoding.

**Comment by kroitor** [comment]
Fixed in @2100. Thx for reporting!
