### ISSUE TITLE
hitbtc can't add margin for futures

### ISSUE THREAD

**Issue by untoreh** [ccxt/ccxt#21002]
### Programming Languages

Python

### Description

https://github.com/ccxt/ccxt/blob/bd072876c19fc8fff4d5467bdfb8c2551efb1644/python/ccxt/async_support/hitbtc.py#L3019
The conditional always skip futures symbols so it always calls `privatePutMarginAccountIsolatedSymbol` instead of `privatePutFuturesAccountIsolatedSymbol`

**Comment by sc0Vu** [comment]
Hi @untoreh 

It calls `privatePutFuturesAccountIsolatedSymbol` in the else block (https://github.com/ccxt/ccxt/blob/bd072876c19fc8fff4d5467bdfb8c2551efb1644/python/ccxt/async_support/hitbtc.py#L3021). You can use the swap market.

**Comment by untoreh** [comment]
the else block runs if `marginMode is None`, but if you have it set from options
```python
exc.options["defaultMarginMode"] = "isolated"
```
then it will fail
