### ISSUE TITLE
bybit wrong fee side

### ISSUE THREAD

**Issue by untoreh** [ccxt/ccxt#21003]
### Description

https://github.com/ccxt/ccxt/blob/5f77a77b0658f3890d6db9e1d767a5bbad90ca54/ts/src/bybit.ts#L3337
the `feeSide` in bybit is usually `get` so that conditional should be inverted i think

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @untoreh:

What di you mean side would be `get`?

**Comment by carlosmiei** [comment]
Hello @untoreh, I thnk you're right, if side === 'buy' fee is in the base currency 
![image](https://github.com/ccxt/ccxt/assets/43336371/96ee3b8b-dd71-46ec-ab8e-a21c0a7827dd)

**Comment by carlosmiei** [comment]
@untoreh We're already doing that inside `parseTrade` we just need to port the changes to safe Order as well.
