### ISSUE TITLE
Congragulations on 100 exchanges 🎉 🎉 🎉 

### ISSUE THREAD

**Issue by frosty00** [ccxt/ccxt#2101]
A big thanks to @kroitor and all the ccxt contributors that made this possible. We've come a very long way in less than a year. This library is one of kind - nothing else even comes close in terms of code  thoroughness and I have never seen transpillation of the like built from only basic regexes.

We will continue to develop over this next year, and if I am successful with my trading endevours I will be sure to donate to the library. Best of luck with the next hundred!

**Comment by JT102** [comment]
Supporting!!! Are there any announcements on new exchanges?

**Comment by kroitor** [comment]
Thx so much to you, @frosty00! I'd like to say my personal thanks to all users who patiently reported bugs and issues, to all contributors who have helped build this project up, and to all backers who have donated to the development of this library. There's even more to come and it's going to be a very exciting year )
