### ISSUE TITLE
Bit-Z    Limit buy order became sell order

### ISSUE THREAD

**Issue by wntsang4** [ccxt/ccxt#2102]
- OS: Windows 10
- Programming Language version: Python 3.6
- CCXT version: 1.10.1266
- Exchange: Bit-Z
- Method: create_limit_buy_order

Limit buy order became sell order

**Comment by wntsang4** [comment]
Problem solved

**Comment by kroitor** [comment]
@wntsang4 can you please paste your code and verbose output, following these steps: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

Without more info from you, it's very hard to help.

**Comment by wntsang4** [comment]
buy_order = bitz.create_limit_buy_order('SPHTX/BTC', 5, 0.000052)


Request: POST https://www.bit-z.com/api_v1/tradeAdd {'Content-type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} api_key=240b02sdxxxxxef976&coin=sphtx_btc&nonce=694066&number=5.0&price=0.00005150&timestamp=1519952694&tradepwd=xxxxxxx&type=buy&sign=dbc6a0xxxxx2583fhef4bd

Response: POST https://www.bit-z.com/api_v1/tradeAdd 200 {'Content-Type': 'application/json;charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Fri, 02 Mar 2018 01:04:56 GMT', 'Server': 'nginx/1.10.3 (Ubuntu)', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 7cecc1b86d56463b5bf2901955efb2ec.cloudfront.net (CloudFront)', 'X-Amz-Cf-Id': 'AmJHygsVHbZ3fjFQ5ZBKbZYrvzpqeDgudHeZoavjGKsvb3rOnRBtKw=='} 
{"code":0,"msg":"Success","data":{"id":"147083927"}}

**Comment by kroitor** [comment]
> However it will become a sell order.

What do you mean "it will become"? When, where? From your output it cannot be seen anywhere, the output itself looks normal (type=buy indeed). So, if you say "the order will become a sell order", please, elaborate how do you detect it.

**Comment by wntsang4** [comment]
I saw a sell order in Bit-Z website.

**Comment by kroitor** [comment]
@wntsang4 saw it in the order book on the sell side? Or in the trades/orders history?

**Comment by wntsang4** [comment]
![sellorder](https://user-images.githubusercontent.com/24471946/36879067-e0f567ea-1dfc-11e8-9bc6-eb54840b83cb.jpg)

**Comment by wntsang4** [comment]
The sell order appeared in the order book and I canceled it manually.

**Comment by kroitor** [comment]
@wntsang4 should be ok now. Please, update to ccxt 1.10.1269 and retry the same code. We will be happy if you report back, whether it now works normally for you, or not.

**Comment by wntsang4** [comment]
The program throws **KeyError ('type',) Error** when calling
buy_order = bitz.create_limit_buy_order('SPHTX/BTC', 5, 0.000047)

**Comment by kroitor** [comment]
@wntsang4 ok, fixed it in 1.11.4, tested it, works on my side, please, update and retry again. Let us know if you still have difficulties with it. Thx for reporting!
