### ISSUE TITLE
ArgumentsRequired: digifinex safeMarket() requires a fourth argument for DFT_USDT to disambiguate between different markets with the same market id

### ISSUE THREAD

**Issue by MeanSquaredError** [ccxt/ccxt#21045]
### Operating System

Linux

### Programming Languages

JavaScript

### CCXT Version

4.2.29

### Description

A TypeScript application using digifinex, just got the following error when calling `fetchTickers()`
```
file:///usr/local/projects/private/XXXXXXX/node_modules/ccxt/js/src/base/Exchange.js:3565
                            throw new ArgumentsRequired(this.id + ' safeMarket() requires a fourth argument for ' + marketId + ' to disambiguate between different markets with the same market id');
                                  ^

ArgumentsRequired: digifinex safeMarket() requires a fourth argument for DFT_USDT to disambiguate between different markets with the same market id
    at digifinex.safeMarket (file:///usr/local/projects/private/XXXXXXX/node_modules/ccxt/js/src/base/Exchange.js:3565:35)
    at digifinex.safeSymbol (file:///usr/local/projects/private/XXXXXXX/node_modules/ccxt/js/src/base/Exchange.js:4647:23)
    at digifinex.parseTicker (file:///usr/local/projects/private/XXXXXXX/node_modules/ccxt/js/src/digifinex.js:1166:29)
    at digifinex.fetchTickers (file:///usr/local/projects/private/XXXXXXX/node_modules/ccxt/js/src/digifinex.js:1038:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SymbolsHistory.updateHistory (file:///usr/local/projects/private/XXXXXXX/source/history.ts:18:25)

Node.js v21.6.1
```

### Code

```
  

```

**Comment by Dan-krm** [comment]
Hi @MeanSquaredError I wasn't able to exactly reproduce this error but I've seen this happen before so I opened a pull request that should resolve this issue for you.

**Comment by MeanSquaredError** [comment]
@Dan-krm 
I can no longer reproduce that error either. I suspect that the error depends on the exact ticker data that has been fetched from the server at that moment. It happened 5-10 minutes before I posted the bug report, but I am not sure it that information can be of any help, e.g. if it is possible to fetch the history data from Digifinex and try to reproduce the problem with it.

**Comment by MeanSquaredError** [comment]
Thank you for the PR, I will use the modified version and will let you know in about 3 days whether the problem happened again.

**Comment by MeanSquaredError** [comment]
Thank you for fixing this bug. There was also another bug with digifinex - the ticker last/close prices were not updated and repeated calls to `fetchTicker()` returned the same last/close price.

It seems that https://github.com/ccxt/ccxt/pull/21047 fixed that bug as well.
