### ISSUE TITLE
okx.php : fetch_ohlcv only returns 99 candles instead of 100.

### ISSUE THREAD

**Issue by pier0074** [ccxt/ccxt#21049]
### Operating System

MacOS

### Programming Languages

PHP

### CCXT Version

4.2.29

### Description

When fetching OHLC from OKX, I always get one candle less than the limit.
Without limit or with the max limit of 100, I get 99 candles in return.
With limit of 50, I get 49 ...
Could you please have a look into it and tell me if that comes from me or if this is an actual issue?

```
public function testCandleNumbers() {
$okx = new \ccxt\okx();
$candles = $okx->fetch_ohlcv( 'BTC-USDT', '1m', 1689335160000, 100 );
echo 'nb candles: ' . count( $candles );
}

nb candles: 99
```

Based on the [API documentation](https://www.okx.com/docs-v5/en/#public-data-rest-api-get-index-candlesticks)

`Pagination of data to return records newer than the requested ts.` meaning anything after the timestamp but **_not_** included the timstamp.

I would suggest to replace `$request['before'] = $since;` by `$request['before'] = $since - 1;`

### Code

```
  

```

**Comment by Dan-krm** [comment]
@pier0074 it looks like this pull request should resolve this issue: #21040
