### ISSUE TITLE
deribit.php : fetch_ohlcv fails to return first candle.

### ISSUE THREAD

**Issue by pier0074** [ccxt/ccxt#21061]
### Operating System

MacOS

### Programming Languages

PHP

### CCXT Version

4.2.29

### Description

When fetching OHLC from Deribit, I always get the second first candle but not the first.
Could you please have a look into it and tell me if that comes from me or if this is an actual issue?

### Code

```
public function testFirstCandle() {
$exchange = new \ccxt\deribit();
$candles = $exchange->fetch_ohlcv( 'BTC_USDC-PERPETUAL', '1m', 1689335160000, 100 );
echo 'first candles: ' . $candles[0][0];
}

first candles: 1689335220000
```

I would suggest to add `$since = $since - 1;` in the below code

```
}else{
	$since = $since - 1;
	$request['start_timestamp'] = $since;
if( $limit === null ){
	$request['end_timestamp'] = $now;
}else{
	$request['end_timestamp'] = $this->sum( $since, $limit * $duration * 1000 );
}
```

**Comment by carlosmiei** [comment]
Hello @pier0074, thanks for letting us know we will take a look asap

**Comment by Dan-krm** [comment]
@pier0074 I think this only happens in rare cases depending on when you call fetchOHLCV, because when I called it with the same arguments it returned the first candle for me. I opened a pull request that should prevent this from happening as a contingency though

**Comment by pier0074** [comment]
@Dan-krm Thanks for you check it. 
The proposed fix does not solve the issue for me. The `$since` needs to be overriding and not just changed for the `request['start_timestamp']` as it is used in other places in the function.
The cases are not rare. It happens everything you fetch from the exact timestamp (min % 60, hour %1440 ...) hence.. almost always if you use standard pagination.

**Comment by Dan-krm** [comment]
@pier0074 I'll update the PR and just override since. Could you share your verbose output:
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

I'm not able to recreate the issue you're having:
```
deribit->fetchOHLCV(BTC/USDC:USDC, 1m, 1689335160000, 100)
Array
(
    [0] => Array
        (
            [0] => 1689335160000
            [1] => 31214
            [2] => 31214
            [3] => 31200
            [4] => 31202
            [5] => 0.967
        )
...
    [99] => Array
        (
            [0] => 1689341100000
            [1] => 31147
            [2] => 31151
            [3] => 31147
            [4] => 31151
            [5] => 0.111
        )

)
```
```
deribit.fetchOHLCV (BTC/USDC:USDC, 1m, 1689335160000, 100)
2024-02-02T07:27:24.201Z iteration 0 passed in 188 ms

1689335160000 | 31214 | 31214 | 31200 | 31202 | 0.967
1689335220000 | 31202 | 31202 | 31202 | 31202 |     0
1689335280000 | 31208 | 31221 | 31208 | 31221 | 0.208
...
1689340980000 | 31144 | 31144 | 31144 | 31144 |     0
1689341040000 | 31122 | 31151 | 31101 | 31151 | 0.444
1689341100000 | 31147 | 31151 | 31147 | 31151 | 0.111
100 objects
```
