### ISSUE TITLE
Historical Data

### ISSUE THREAD

**Issue by celosotomaior** [ccxt/ccxt#2106]
Hello there,

I'm trying to get the n historical data from Bittrex, Binance, Poloniex, Bitstamp, and Kraken. Does CCXT support this already?

If so, could you please post the link to get this information?

Thanks a lot!

Marcelo

**Comment by kroitor** [comment]
Hi!

Have you read the Manual? ) 

It's here: https://github.com/ccxt/ccxt/wiki

Also, there's a lot of examples, here: https://github.com/ccxt/ccxt/tree/master/examples

Let us know if it does not answer your question ) Thx!

**Comment by celosotomaior** [comment]
Thanks for replying. 

I filtered the ohlcv data and was able to get the past data. However, I'd like to get a from-to date, not only a single date. For example, the historical price of BTC/USD from 26/02/2017 until 26/05/2017.
How do I put these parameters in the code below?

Now I have another problem to solve. When I use console.log(ohlcv.length), it gives me a random number of ohlcv lines for 1m period, depending on the exchange. Bitfinex gives only 120 lines, and others give me 500, 439, 300 etc, depending on the day. It should give me 1440 lines, considering I'm using one day period. I'm using bittrex, poloniex, bitstamp, kraken and bitfinex for the test. 

After correcting this, I will need to put it in the database and calculate some technical indicators, such as MACD, Moving Averages, and others. Is it possible to get some indicators using ccxt library?

Here is the code that I'm using. 

"use strict";

const ccxt       = require ('../../ccxt.js')
const asciichart = require ('asciichart')
const asTable    = require ('as-table')
const log        = require ('ololog').configure ({ locate: false })

require ('ansicolor').nice
//-----------------------------------------------------------------------------
    var mongo = require('mongodb');
    var MongoClient = mongo.MongoClient;
    var dbname = "cryptoshi"
    var url = "mongodb://localhost:27017/" + dbname
    // Connect to the db
    MongoClient.connect(url , function(err, db) {
      if(err) { return console.dir(err); }

      var mydb = db.db(dbname);
      var collection = mydb.collection('testAsset');

  ;(async function main () {

    const index = 4 // [ timestamp, open, high, low, close, volume ]
    const ohlcv = await new ccxt.bitfinex ().fetchOHLCV ('BTC/USD','1m')
    console.log(ohlcv.length)
    // const lastPrice = ohlcv[ohlcv.length - 1][index] // closing price
    // const series = ohlcv.slice (-80).map (x => x[index]) // closing price
    // const bitcoinRate = ('₿ = $' + lastPrice).green
    // const chart = asciichart.plot (series, { height: 15, padding: '            ' })
    // log.yellow ("\n" + chart, bitcoinRate, "\n")
    // process.exit ()    
   
for (var i in ohlcv){
console.log(i)
values.push({'timestamp': ohlcv[i][0], 'open': ohlcv[i][1], 'high': ohlcv[i][2], 'low': ohlcv[i][3], 'close': ohlcv[i][4],'volume': ohlcv[i][5] });

}
console.log(values)
 
   // var collection = db.db('test');
   mydb.collection("testAsset").insertMany(values, function(err, result){
    if (err) throw err
    console.log(result)
  });
 }) ()
     });

Thanks a lot )

**Comment by s-ben** [comment]
In case anyone else is still having this issue, just found this code that implements the logic for gathering historical data from ccxt,
https://backtest-rookies.com/2018/03/08/download-cryptocurrency-data-with-ccxt/

**Comment by kroitor** [comment]
@s-ben thx for the feedback!
