### ISSUE TITLE
Mexc.php : fetch_ohlcv strange behaviour

### ISSUE THREAD

**Issue by pier0074** [ccxt/ccxt#21069]
### Operating System

MacOS

### Programming Languages

PHP

### CCXT Version

4.2.29

### Description

When fetching OHLC from Mexc, I have a strange behaviour and do not always get the right Candles.
I have the feeling the limit parameter is not correctly taken into account and that the pagination is not done at all.
Could you please have a look into it and tell me if that comes from me or if this is an actual issue?

### Code

```
  		$exchange = new \ccxt\mexc();
		$candles = $exchange->fetch_ohlcv( 'BTC/USDT:USDT', '1m', 1689335160000, 4500 );
		echo 'first candle: ' . $candles[0][0] . "\n";
		echo 'count candles: ' . count( $candles ) . "\n";

first candle: 1689335160000
count candles: 2001

		$candles = $exchange->fetch_ohlcv( 'BTC/USDT:USDT', '1m', 1689335160000, 10 );
		echo 'first candle: ' . $candles[0][0] . "\n";
		echo 'count candles: ' . count( $candles ) . "\n";

first candle: 1689454620000
count candles: 10
```

**Comment by samgermain** [comment]
Upgrade your CCXT to the latest version please. The fetching candles starting at since error was fixed in #21040 .

The maximum number of candles that can be fetched from MEXC is 2001 for contract markets, so 4500 candles cannot be fetched
