### ISSUE TITLE
Kucoin spot watchOrderBook - can't listen to top50 bbo

### ISSUE THREAD

**Issue by mrminister** [ccxt/ccxt#21104]
### Operating System

mac

### Programming Languages

Python

### CCXT Version

4.2.35

### Description

Hi team, 
read through the docs but didn't find the answer to this anywhere -  if on Kucoin Spot, I want to use watchOrderBook to listen to[ level2 - 50 best ask/bid orders](https://www.kucoin.com/docs/websocket/spot-trading/public-channels/level2-50-best-ask-bid-orders), rather than t[he full orderbook](https://www.kucoin.com/docs/websocket/spot-trading/public-channels/level2-market-data), can I achieve this by a relatively minor edit? Ideally by feeding the method the params dict which specifies this, but couldn't figure out how

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @mrminister

Thanks, we've added this feature in 4.2.38. Now you can upgrade ccxt and try this feature. Let me know if you have other issues.
