### ISSUE TITLE
Bitfinex2 rateLimitExceeded

### ISSUE THREAD

**Issue by x1i4b1x2** [ccxt/ccxt#21106]
### Description

After a couple of OHLCV requests it returns RateLimitExceeded. The rate limit is enabled but it may be too short.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @x1i4b1x2, thanks for letting us know, we will take a look

**Comment by Dan-krm** [comment]
Hi @x1i4b1x2 I opened a pull request that increases the rate limit weights slightly and should resolve this issue.
Although I wasn't able to trigger the rateLimitExceeded error using fetchOHLCV, could you share some more details about your code? https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by x1i4b1x2** [comment]
It's a fetchOHLCV looping through Markets. It often starts to happen after a lot of fetches.

**Comment by Dan-krm** [comment]
@x1i4b1x2 I opened a pull request to increase the rate limit weights that has been merged. Let me know if you're still experiencing the `rateLimitExceeded` error or if it's okay now.

**Comment by x1i4b1x2** [comment]
Seems fine now
