### ISSUE TITLE
Binance Futures fetch_my_trades() only returning < 7 days of trades

### ISSUE THREAD

**Issue by topchatz** [ccxt/ccxt#21103]
### Operating System

Mac OS

### Programming Languages

Python

### CCXT Version

4.2.35

### Description

Hi guys, not sure if it's something you can do anything about or if it's Binance limiting things, but I'm trying to get trades I've done recently in a certain symbol but I can only get ones from a couple of days ago, despite the fact I traded a lot a week+ ago. I've tried both since= and limit= and neither help. In fact since= makes it worse as I'm using a date nearly 2 weeks ago so I actually get a blank df.

My guess is either Binance limit to 7(?) days per symbol say, or they limit based on all symbols to X trades. I trade quite a lot, but haven't traded much in this specific symbol. Is it possible to get the 'limit' applied to indivdual symbols so regardless how much I trade in other symbols, I can still get trades from a couple of weeks ago in a symbol I don't trade much in?

Many thanks

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @topchatz 

The symbols are filtered in ccxt code, and they have 7 days limit: https://binance-docs.github.io/apidocs/futures/en/#account-trade-list-user_data.
