### ISSUE TITLE
Poblem with method fetch_currencies

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#21100]
Hello,

I'm facing an issue with method `fetch_currencies` on several exchanges (binance, bybit, ...).

What could be the reason ? please find the code example below

I'm runing the latest ccxt-4.2.35 version.

Regards,
Kinzowa

### Code

Work : 

``` python
import ccxt
b = ccxt.binance()
b.load_markets(True)
b.currencies

{'1000BONK': {'info': None,
  'id': '1000BONK',
  'numericId': None,
  'code': '1000BONK',
  'precision': 8,
  'type': None,
  'name': None,
  'active': None,
  'deposit': None,
  'withdraw': None,
...
```
Doesn't work : 

``` python
import ccxt
b = ccxt.binance()
c = b.fetch_currencies()
print(c)

None
```

**Comment by divyanshu-in** [comment]
can you please elaborate about the issue.

**Comment by Kinzowa** [comment]
@divyanshu-in the second code snippet above is supposed to return the currency list.

**Comment by carlosmiei** [comment]
@Kinzowa Some currencies/ endpoints are private so if you don't provide API Keys to the exchange they will just return `undefined`. You can see them after loadMarkets because we emulate currencies from `market` when keys are not available.

**Comment by Kinzowa** [comment]
Hi @carlosmiei thanks for your answer. 

Indeed, authentication is required for retrieving markets with `fetch_markets()` from Coinbase and an `AuthenticationError` is thrown when the CCXT instance isnt authentified. As far as I remember Binance and Bybit don't ask client authentification before returning market data.

In my case, there is no exception so I assume the issue is caused by something else.

**Comment by carlosmiei** [comment]
@Kinzowa Both binance and bybit use private endpoints to retrieve the `fetchCurrencies` information

https://binance-docs.github.io/apidocs/spot/en/#all-coins-39-information-user_data
https://bybit-exchange.github.io/docs/v5/asset/coin-info
