### ISSUE TITLE
Problem of API authentication with Okex

### ISSUE THREAD

**Issue by AoDev** [ccxt/ccxt#2111]
## Context

- OS: __OSX__
- Programming Language version: __javascript (ES6 Babel in Chrome Browser)__
- CCXT version: __1.10.1124__
- Exchange: __Okex__
- Method: __fetchBalance()__

## Problem: unauthorized as reponse

Trying to fetch account info (fetchBalance) with okex. I get `{result: false, error_code: 10017}`
which means [API authentication error](https://www.okex.com/rest_request.html).

The API key has been generated with neither `withdrawal` nor `trade` permissions activated, as it is meant to only get my account info.

I am not too sure about the relation between OKCoin and Okex. Just to be clear, I am using okex, the Chinese exchange at okex.com. I see the code is shared between these. And I also found a [typo for the public api url](https://github.com/ccxt/ccxt/blob/master/js/okcoincny.js#L22).

Checking the request, I see the public key and the signature there. I don't know if the signature is ok though.

## Code used

```
this.okexClient = new ccxt.okex({
  apiKey: 'my key',
  secret: 'secret',
})

this.okexClient.fetchBalance()
  .then((res) => {
    console.log(res)
  })
```

Note: I use ccxt successfully with Kraken exchange, so I have a bit of practice using ccxt.

**Comment by mkutny** [comment]
Thanks for the elaborate explanation, they are rare these days )

I can confirm that signature is ok as fetching balance works for me for okex.

> Trying to fetch account info (fetchBalance) with okex. I get {result: false, error_code: 10017}
which means API authentication error.

Actually, they say this is authorization error, not authentication error. And if their statement is correct it has to do with permissions, not with the signature. If a key/secret is wrong they return 10005/10007.

> The API key has been generated with neither withdrawal nor trade permissions activated, as it is meant to only get my account info.

Try to go with full permissions first, it should work.

> I am not too sure about the relation between OKCoin and Okex.

See this: https://github.com/ccxt/ccxt/issues/485#issuecomment-342738060

**Comment by kroitor** [comment]
@AoDev the answer of @mkutny is correct, you most likely have a problem with key permissions, and in that case, try creating a new key with full permissions, then try switching off the unwanted permissions one by one and see how it affects the authorization, whether the error appears or not. Let us know if it does not help. Feel free to reopen this issue or just ask questions, if any. Thx!

**Comment by AoDev** [comment]
@mkutny @kroitor Thank you. I was able to get the data by enabling the "trade" permission.

That said I've written to Okex, asking if there could be a way to provide "read-only" permission like in other exchanges. Mainly because I want to enable certain monitoring features while not focusing on credential storage security yet.

> Thanks for the elaborate explanation, they are rare these days )

I face the same problem on my side 😄

**Comment by bleotu** [comment]
@AoDev any response from Okex to provide a read-only account? Do you have a ticker number for that?

**Comment by AoDev** [comment]
@bleotu I never got a response. Not sure about having a ticket, I don't find anything in my mails.
