### ISSUE TITLE
Bybit exchange: Positions data always returns marginMode: "cross" on version 4.2.36

### ISSUE THREAD

**Issue by caesar3x** [ccxt/ccxt#21121]
### CCXT Version

4.2.36

### Description

Hello,

As I reported in this issue: https://github.com/ccxt/ccxt/issues/21079, Positions data always returns marginMode: "cross" . I am still getting the same issue on 4.2.36 version. How can I determine a position is Isolated or cross now? I am sorry that I have to create new issue but I can not reopen the old one.

Please help!

### Code

```
  

```

**Comment by samgermain** [comment]
Version 4.2.36 doesn't have the update, but a newer version should be posted within a day or 2. It's not going to help you out much though because the data relating to marginMode was depreciated by Bybit, so it's just going to give `undefined` for this field

**Comment by caesar3x** [comment]
Hello @samgermain,

Thank you very much for quick update.

Please inform us when you have this update.
