### ISSUE TITLE
NotSupported: bybit closePosition() is not supported yet   

### ISSUE THREAD

**Issue by tom-teamcoda** [ccxt/ccxt#21125]
### Description

NotSupported: bybit closePosition() is not supported yet
    at bybit.closePosition (/Users/tom/dev/trabo/trabo-scripts-intern/node_modules/ccxt/dist/cjs/src/base/Exchange.js:4315:15)

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @tom-teamcoda,

It seems there's no api for closePosition (close positions for market) in bybit. We'll implement this function if exchange add the feature.
