### ISSUE TITLE
Southxchange withdraw issue

### ISSUE THREAD

**Issue by alexsith** [ccxt/ccxt#2113]
Hello.
  There is missed tag in withdraw function, it doesn't pass to API

- OS:
- Programming Language version: python
- CCXT version:
- Exchange:
- Method: withdraw

**Comment by kroitor** [comment]
Fixed in 1.10.1274. Thx for reporting!

**Comment by alexsith** [comment]
+        if (typeof tag !== 'undefined')
+            request['currency'] = address + '|' + tag;

I guess, it suppose to be 
              request['address'] = address + '|' + tag;

**Comment by alexsith** [comment]
And where did you get information about paymentID? Cause I can't find it in their documentation on site.

**Comment by kroitor** [comment]
@alexsith 

> And where did you get information about paymentID? Cause I can't find it in their documentation on site.

Reverse-engineered it from createDepositAddress ('XMR')
