### ISSUE TITLE
OKX, fetch_open_orders() not fetching trigger orders

### ISSUE THREAD

**Issue by Ccon2r** [ccxt/ccxt#21131]
### Operating System

Wndows 10

### CCXT Version

4.2.29

### Description

fetch_open_orders() does not fetch trigger orders or SL/TP orders.
Is there a way to get them?

![2024-02-07_01-21-40 (2)](https://github.com/ccxt/ccxt/assets/155516997/da1a5d16-ab31-424b-a008-a8890e1c4ed3)

### Code

```
open_orders = await exchange.fetch_open_orders(symbol)
for order in open_orders:
    pprint(order)
```

**Comment by Ccon2r** [comment]
exchange.watch_orders(symbol) also cant see this type of orders.

**Comment by samgermain** [comment]
To fetch stop orders on OKX, you need to pass `{"stop": true}` via the params argument

-------------------

This is because fetching stop orders requires making a call to a separate endpoint than regular orders, so you can't fetch both without making 2 calls

**Comment by Ccon2r** [comment]
@samgermain
Thanks. Is it the same for watch_orders?
Where can I get more information on this issue?

> To fetch stop orders on OKX, you need to pass `{"stop": true}` via the params argument
> 
> This is because fetching stop orders requires making a call to a separate endpoint than regular orders, so you can't fetch both without making 2 calls

@samgermain
Thanks. Is it the same for watch_orders?
Where can I get more information on this issue?

**Comment by Ccon2r** [comment]
@samgermain 
https://github.com/ccxt/ccxt/blob/9c9fcce1252e6d5756a8e13a7399519b2622c94d/python/ccxt/async_support/okx.py#L3467
I found this condition, but it's not working for me. Only this `{"stop": true}` not enough, I need to set  ordType.
But after this, what if I need more then only one type ("conditional", "oco", "trigger"): 
```
open_orders = await exchange.fetch_open_orders(symbol, params = {'stop': True, 'ordType': 'conditional'} )
for order in open_orders:
     pprint(order)
```

**Comment by algosfox** [comment]
@samgermain @carlosmiei
It's again need to specify order type for fetch OKX algo orders
https://github.com/ccxt/ccxt/blob/9c9fcce1252e6d5756a8e13a7399519b2622c94d/python/ccxt/async_support/okx.py#L3466

setting `params = {'trigger': True}`  or  `params = {'stop': True}` not enought
