### ISSUE TITLE
Bit-Z "ask queue" ordering incorrect

### ISSUE THREAD

**Issue by amtf** [ccxt/ccxt#2114]
- OS: Linux
- Programming Language version: javascript
- CCXT version: 1.10.1273
- Exchange: bit-z
- Method: fetchOrderBook

The "bid queue" ordering is correct, but the "ask queue" ordering is in reverse order.

Ask queue:
0.00547186 |   9.99000000
0.00550000 |   7.51830000
0.00560000 |   3.70130000
0.00600000 |   1.89280000
0.00887592 |  50.00000000
0.02000000 |   1.99800000
0.04000000 | 121.68360000
0.20950000 |   0.90000000
------------------------------------
Bid queue:
0.00314607 |   2.22470000
0.00313975 |   0.86900000
0.00313704 |   1.88610000
0.00313702 |   0.30760000
0.00313665 |   3.77060000
0.00313538 |   1.42410000
0.00313502 | 248.32290000
0.00313476 |  25.56130000

Thanks

**Comment by kroitor** [comment]
@amtf can you please provide a snippet of code to reproduce the problem and your verbose output?

I don't see it with ETH/BTC:

<img width="539" alt="screen shot 2018-03-03 at 12 34 13" src="https://user-images.githubusercontent.com/1294454/36932769-46f942f4-1edf-11e8-975b-2d0f2ba51821.png">

https://github.com/ccxt/ccxt/blob/master/examples/js/live-orderbook.js

**Comment by kroitor** [comment]
> but the "ask queue" ordering is in reverse order.

I think you're misinterpreting the order of asks. It isn't reversed in fact. It is correct, the first element in the ask array is the best market price, the second element is the price after it, and so on...

So it, isn't reversed. It is documented here: https://github.com/ccxt/ccxt/wiki/Manual#order-book

Let us know if it does not answer your question.

**Comment by amtf** [comment]
![image](https://user-images.githubusercontent.com/4770880/36933080-4fe40e88-1f0e-11e8-9552-f901939f4912.png)

This is the exchange problem?

**Comment by kroitor** [comment]
@amtf are you sure you're running the version 1.10.1273? Also, for some reason, the date formatting is different on our systems...
