### ISSUE TITLE
Bitget create_order reduceOnly not working

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#21165]
### Operating System

MacOS

### Programming Languages

Python

### CCXT Version

4.2.39

### Description

I am unable to create a reduceOnly order using the 'close_long' or 'close_short' side. It has been working in older versions. 

### Code

```
  
client = client
ticker = "ETC/USDT:USDT"
side = "close_long"
quantity = 5
price = 25
response = client.create_order(symbol=ticker, type="market", side=side, amount=quantity, price=None, params={'stopPrice': price, 'triggerType': 'fill_price'})

                                                   
```
{
	"name": "ExchangeError",
	"message": "bitget {\"code\":\"400172\",\"msg\":\"Illegal position opening type\",\"requestTime\":1707393365430,\"data\":null}",
	"stack": "---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
File ~/opt/anaconda3/lib/python3.9/site-packages/ccxt/base/exchange.py:622, in Exchange.fetch(self, url, method, headers, body)
    621     self.logger.debug(\"%s %s, Response: %s %s %s\", method, url, http_status_code, headers, http_response)
--> 622     response.raise_for_status()
    624 except Timeout as e:

File ~/opt/anaconda3/lib/python3.9/site-packages/requests/models.py:1021, in Response.raise_for_status(self)
   1020 if http_error_msg:
-> 1021     raise HTTPError(http_error_msg, response=self)

HTTPError: 400 Client Error: Bad Request for url: https://api.bitget.com/api/v2/mix/order/place-plan-order

During handling of the above exception, another exception occurred:

ExchangeError                             Traceback (most recent call last)
Cell In[64], line 6
      4 quantity = 5
      5 price = 25
----> 6 response = client.create_order(symbol=ticker, type=\"market\", side=side, amount=quantity, price=None, params={'stopPrice': price,
      7                                                    'triggerType': 'fill_price'})

File ~/opt/anaconda3/lib/python3.9/site-packages/ccxt/bitget.py:3908, in bitget.create_order(self, symbol, type, side, amount, price, params)
   3906 else:
   3907     if isTriggerOrder or isTrailingPercentOrder:
-> 3908         response = self.privateMixPostV2MixOrderPlacePlanOrder(request)
   3909     elif isStopLossOrTakeProfitTrigger:
   3910         response = self.privateMixPostV2MixOrderPlaceTpslOrder(request)

File ~/opt/anaconda3/lib/python3.9/site-packages/ccxt/base/types.py:34, in Entry.__init__.<locals>.unbound_method(_self, params)
     33 def unbound_method(_self, params={}):
---> 34     return _self.request(self.path, self.api, self.method, params, config=self.config)

File ~/opt/anaconda3/lib/python3.9/site-packages/ccxt/base/exchange.py:3478, in Exchange.request(self, path, api, method, params, headers, body, config)
   3477 def request(self, path, api: Any = 'public', method='GET', params={}, headers: Any = None, body: Any = None, config={}):
-> 3478     return self.fetch2(path, api, method, params, headers, body, config)

File ~/opt/anaconda3/lib/python3.9/site-packages/ccxt/base/exchange.py:3475, in Exchange.fetch2(self, path, api, method, params, headers, body, config)
   3473 self.last_request_body = request['body']
   3474 self.last_request_url = request['url']
-> 3475 return self.fetch(request['url'], request['method'], request['headers'], request['body'])

File ~/opt/anaconda3/lib/python3.9/site-packages/ccxt/base/exchange.py:638, in Exchange.fetch(self, url, method, headers, body)
    636 except HTTPError as e:
    637     details = ' '.join([self.id, method, url])
--> 638     skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
    639     if not skip_further_error_handling:
    640         self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)

File ~/opt/anaconda3/lib/python3.9/site-packages/ccxt/bitget.py:7688, in bitget.handle_errors(self, code, reason, url, method, headers, body, response, requestHeaders, requestBody)
   7686     self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
   7687 if nonZeroErrorCode or nonEmptyMessage:
-> 7688     raise ExchangeError(feedback)  # unknown message
   7689 return None

ExchangeError: bitget {\"code\":\"400172\",\"msg\":\"Illegal position opening type\",\"requestTime\":1707393365430,\"data\":null}"
}

**Comment by Tomas-MP** [comment]
It works, thank you as always @carlosmiei !

**Comment by Tomas-MP** [comment]
@carlosmiei maybe one more question, in case I create an order through  using reduceOnly=True, a reduceOnly 'sell' order will return as a 'buy' when using client.fetch_open_orders and vice versa. 

Is this on purpose or is this a mistake on CCXT's side? Otherwise I will change it on my end.

**Comment by carlosmiei** [comment]
@Tomas-MP I think that's not expected, I will take a look, thanks for letting us know.

> It works
btw this is the unified way of placing reduceOnly orders

**Comment by carlosmiei** [comment]
@Tomas-MP interestingly, the flipped side comes directly from bitget
![image](https://github.com/ccxt/ccxt/assets/43336371/208b7289-5978-454e-8c82-84780a40aaf9)
![image](https://github.com/ccxt/ccxt/assets/43336371/ca9d9305-f92d-4705-bbfd-98411bbcd45b)

**Comment by carlosmiei** [comment]
@Tomas-MP Ok I think it might be related to this: https://github.com/ccxt/ccxt/blob/master/ts/src/bitget.ts#L4211

>                         // on bitget hedge mode if the position is long the side is always buy, and if the position is short the side is always sell

**Comment by carlosmiei** [comment]
If we send the "correct" side for the reduceOnly order, we get this error
```
ExchangeError bitget {"code":"22002","msg":"No position to close","requestTime":1707414538773,"data":null}
---------------------------------------------------
[ExchangeError] bitget {"code":"22002","msg":"No position to close","requestTime":1707414538773,"data":null}

    at handleErrors               Users/cjg/Git/ccxt10/ccxt/js/src/bitget.js:8258         
    at                            Users/cjg/Git/ccxt10/ccxt/js/src/base/Exchange.js:922   
    at processTicksAndRejections  node:internal/process/task_queues:95                    
    at fetch2                     Users/cjg/Git/ccxt10/ccxt/js/src/base/Exchange.js:3438  
    at request                    Users/cjg/Git/ccxt10/ccxt/js/src/base/Exchange.js:3441  
    at createOrder                Users/cjg/Git/ccxt10/ccxt/js/src/bitget.js:4076         
    at async run                  Users/cjg/Git/ccxt10/ccxt/examples/js/cli.js:340        

bitget {"code":"22002","msg":"No position to close","requestTime":1707414538773,"data":null}
```

**Comment by carlosmiei** [comment]
Nonetheless, we will fix the order parsing to return the proper side.

**Comment by Tomas-MP** [comment]
@carlosmiei indeed weird that Bitget handles it like this, thanks for further investigating
