### ISSUE TITLE
Bitget symbol not working for private methods

### ISSUE THREAD

**Issue by Tomas-MP** [ccxt/ccxt#21163]
### Operating System

MacOS/Windows10

### Programming Languages

Python

### CCXT Version

4.2.39

### Description

When I try to retrieve data through running code for a specific symbol. It does not seem to work for a ccxt class with api keys stored in it. It does not seem to work for multiple derivative symbols and methods (e.g. fetch_orders, fetch_ohlcv). 

### Code

```
  
# Working example
client = ccxt.bitget()
ticker = "ADA/USDT:USDT"
ohlc = client.fetch_ohlcv(ticker)

# Not working example
client = ccxt.bitget({'apiKey': '', 'secret': ''})
ticker = "ADA/USDT:USDT"
ohlc = client.fetch_ohlcv(ticker)

```
{
	"name": "ExchangeError",
	"message": "bitget {\"code\":\"40034\",\"msg\":\"Parameter ADAUSDT_UMCBL does not exist\",\"requestTime\":1707382498393,\"data\":null}",
	"stack": "---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
File ~/opt/anaconda3/lib/python3.9/site-packages/ccxt/base/exchange.py:622, in Exchange.fetch(self, url, method, headers, body)
    621     self.logger.debug(\"%s %s, Response: %s %s %s\", method, url, http_status_code, headers, http_response)
--> 622     response.raise_for_status()
    624 except Timeout as e:

File ~/opt/anaconda3/lib/python3.9/site-packages/requests/models.py:1021, in Response.raise_for_status(self)
   1020 if http_error_msg:
-> 1021     raise HTTPError(http_error_msg, response=self)

HTTPError: 400 Client Error: Bad Request for url: https://api.bitget.com/api/v2/mix/market/candles?symbol=ADAUSDT_UMCBL&granularity=1m&endTime=1707382498230&productType=USDT-FUTURES

During handling of the above exception, another exception occurred:

ExchangeError                             Traceback (most recent call last)
Cell In[12], line 1
----> 1 client.fetch_ohlcv(\"ADA/USDT:USDT\")

File ~/opt/anaconda3/lib/python3.9/site-packages/ccxt/bitget.py:3220, in bitget.fetch_ohlcv(self, symbol, timeframe, since, limit, params)
   3218         response = self.publicMixGetV2MixMarketHistoryCandles(self.extend(request, params))
   3219     else:
-> 3220         response = self.publicMixGetV2MixMarketCandles(self.extend(request, params))
   3221 if response == '':
   3222     return []  # happens when a new token is listed

File ~/opt/anaconda3/lib/python3.9/site-packages/ccxt/base/types.py:34, in Entry.__init__.<locals>.unbound_method(_self, params)
     33 def unbound_method(_self, params={}):
---> 34     return _self.request(self.path, self.api, self.method, params, config=self.config)

File ~/opt/anaconda3/lib/python3.9/site-packages/ccxt/base/exchange.py:3478, in Exchange.request(self, path, api, method, params, headers, body, config)
   3477 def request(self, path, api: Any = 'public', method='GET', params={}, headers: Any = None, body: Any = None, config={}):
-> 3478     return self.fetch2(path, api, method, params, headers, body, config)

File ~/opt/anaconda3/lib/python3.9/site-packages/ccxt/base/exchange.py:3475, in Exchange.fetch2(self, path, api, method, params, headers, body, config)
   3473 self.last_request_body = request['body']
   3474 self.last_request_url = request['url']
-> 3475 return self.fetch(request['url'], request['method'], request['headers'], request['body'])

File ~/opt/anaconda3/lib/python3.9/site-packages/ccxt/base/exchange.py:638, in Exchange.fetch(self, url, method, headers, body)
    636 except HTTPError as e:
    637     details = ' '.join([self.id, method, url])
--> 638     skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
    639     if not skip_further_error_handling:
    640         self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)

File ~/opt/anaconda3/lib/python3.9/site-packages/ccxt/bitget.py:7688, in bitget.handle_errors(self, code, reason, url, method, headers, body, response, requestHeaders, requestBody)
   7686     self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
   7687 if nonZeroErrorCode or nonEmptyMessage:
-> 7688     raise ExchangeError(feedback)  # unknown message
   7689 return None

ExchangeError: bitget {\"code\":\"40034\",\"msg\":\"Parameter ADAUSDT_UMCBL does not exist\",\"requestTime\":1707382498393,\"data\":null}"
}

**Comment by divyanshu-in** [comment]
I think the error is self explanatory, ticker for "ADA/USDT:USDT" is not available on that exchange.

**Comment by carlosmiei** [comment]
@Tomas-MP Hum so it is working now?

**Comment by Tomas-MP** [comment]
@carlosmiei somehow it is now, I encountered the issue earlier as well. I will keep you posted and reopen in case it stops working again!

**Comment by fl0wo** [comment]
I have the same issue as well.

Error:
`bitget {"code":"40034","msg":"Parameter UNIUSDT_SPBL does not exist","requestTime":1709035300410,"data":null}`

Args:
`{"amount":78.441,"datetime":"2024-02-27T13:00:47","price":10.938,"side":"sell","symbol":"UNI/USDT","timestamp":1709035247295,"type":"market"}`

Spot Market
Exchange bitget
createOrder

**Comment by carlosmiei** [comment]
@fl0wo Unfortunately I'm not sure this is related to CCXT, for instance I just tested and worked well

```
n bitget createOrder "UNI/USDT" limit buy 5 5  --verbose
CCXT v4.2.52
bitget.createOrder (UNI/USDT, limit, buy, 5, 5)
fetch Request:
 bitget POST https://api.bitget.com/api/v2/spot/trade/place-order 
RequestBody:
 {"symbol":"UNIUSDT","orderType":"limit","price":"5","force":"GTC","side":"buy","size":"5"} 

handleRestResponse:
 bitget POST https://api.bitget.com/api/v2/spot/trade/place-order 200 OK 
ResponseHeaders:
ResponseBody:
 {"code":"00000","msg":"success","requestTime":1709051974801,"data":{"orderId":"1146412562218663947","clientOid":"63ff2cfb-a4e5-43c2-be73-5592deb452d2"}} 

```

**Comment by fl0wo** [comment]
I guess It's an issue on exchange side as well, just contacted bitget on this regard...

Scary to see issues like that from an exchange of their size
