### ISSUE TITLE
Cross exchange Documentation

### ISSUE THREAD

**Issue by kevaundray** [ccxt/ccxt#2116]
What is meant by the normalised data for cross exchange?

This is a feature that i believe I urgently need, however I could not find the documentation on it, so cannot be 100% certain

**Comment by kroitor** [comment]
> What is meant by the normalised data for cross exchange?

It means, that the exchanges are not uniform and don't have a common standard or format, therefore this library exists, which wraps their non-compatible data in a uniform way in a common format that is very convenient for a user. In general the exchanges themselves (as is any technology) aren't ideal. So, *normalised* means "ordered and nicely structured" data, that is easy to work with, despite all their differences.

CCXT will provide both ways of getting data: in exchange-specific format and in a common (*"normalised"* or *"unified"*) format.

> This is a feature that i believe I urgently need, however 

Indeed )

> I could not find the documentation on it, so cannot be 100% certain

There are links to the docs all over the place practically saying it in bold: **[READ THE MANUAL](https://github.com/ccxt/ccxt/wiki)** and I'm not really sure how you could even miss the documentation that covers all of your questions. When you land into a place that is new to you, you need to get a good look around, click links, read texts. This library is used by so many users and there's a lot of info on how to use it, so, imagine: your question is most likely already answered before you even asked it, you just need to look around carefully and pay attention. Also, the link to the docs was there in the input box when you submitted this issue and you skipped it without reading for some reason, that isn't all that clear to me )

I guess, you are distracted. Get focused )

Screenshots:

![screen-shot-2018-03-04-at-14 48 02](https://user-images.githubusercontent.com/1294454/36945211-d264feaa-1fbb-11e8-8434-7832ed2e2346.jpg)

![screen-shot-2018-03-04-at-14 48 09](https://user-images.githubusercontent.com/1294454/36945217-dfbbef8c-1fbb-11e8-82c0-e25f14bf2c88.jpg)

![screen-shot-2018-03-04-at-14 48 16](https://user-images.githubusercontent.com/1294454/36945220-e6441b40-1fbb-11e8-90dc-1a680e3825cb.jpg)

![screen-shot-2018-03-04-at-14 48 21](https://user-images.githubusercontent.com/1294454/36945221-eabd077c-1fbb-11e8-8a58-b99db36f279e.jpg)

![screen-shot-2018-03-04-at-14 52 26](https://user-images.githubusercontent.com/1294454/36945222-f0c672de-1fbb-11e8-99de-d41198b2d0df.jpg)

Welcome ) Let us know if it does not help )

**Comment by kevaundray** [comment]
Thank you for the response. I looked around at the manual before asking my question. 

I was confused as the page said optional normalisation, so I was wondering where exactly in the documentation does it reference the parameter that needs to be set for it. Again, I may have missed it while looking.

Thanks

**Comment by kroitor** [comment]
@kevaundray ok, then, the entire Manual is a description of how each particular piece of data is normalised or unified (the manual basically tells you which unified method return which unified format and how to use exchange-specific methods and formats as well).
