### ISSUE TITLE
Bitget fetchOHLCV 1d issue after updated from 4.2.31 to 4.2.40

### ISSUE THREAD

**Issue by x1i4b1x2** [ccxt/ccxt#21189]
### Programming Languages

Typescript

### Description

Bitget returns ExchangeError when fetchOHLCV futures with '1d' interval.

### Code

```
  bitget.fetchOHLCV(symbol, '1d', timestamp)
```

**Comment by sc0Vu** [comment]
Hi @x1i4b1x2

It works for me. Can you paste the verbose log?

**Comment by x1i4b1x2** [comment]
<img width="1286" alt="Screenshot 2024-02-11 at 11 20 02 AM" src="https://github.com/ccxt/ccxt/assets/100806945/cba52251-168a-4924-9a75-f745636b5d0e">

**Comment by x1i4b1x2** [comment]
This is how the request is done:

`bitget.fetchOHLCV(symbol, '1d', timestamp)`

It has the same problem even if the timestamp is yesterday.

**Comment by edwardchenchen** [comment]
exchange = ccxt.bitget()
    since = int(datetime.datetime(2024, 2, 14, 20, 0, tzinfo=ZoneInfo('Australia/Sydney')).timestamp() * 1000)
    until = int(datetime.datetime(2024, 2, 14, 22, 0, tzinfo=ZoneInfo('Australia/Sydney')).timestamp() * 1000)
  
    data = exchange.fetch_ohlcv(
        symbol="ACE/USDT",
        timeframe='1m',
        limit=1000,
        since=since, params={
            'until': until,
        }
    )

I am also having this issue above is `ccxt==4.2.21` using `params.until`
which sends 
```
https://api.bitget.com/api/v2/spot/market/candles?symbol=ACEUSDT&granularity=1min&limit=1000&startTime=1707901200000&endTime=1707908400000
```
which is stated in the `https://docs.ccxt.com/#/exchanges/bitget?id=fetchohlcv`
with new versions which I have on another machine `ccxt==4.2.45`
it sends
```
   https://api.bitget.com/api/v2/spot/market/candles?symbol=ACEUSDT&granularity=1min&limit=1000&startTime=1707901200000&endTime=1707961259999   
```
and 
to get it working I have to use `params.endTime`

**Comment by sc0Vu** [comment]
@edwardchenchen 

That's interesting. And when I set the right timestamp with until, the data is weird.

```BASH
bitget GET https://api.bitget.com/api/v2/spot/market/candles?symbol=ACEUSDT&granularity=1Dutc&limit=1000&startTime=1707901200000&endTime=1707908400000 200 OK

ResponseBody:
 {"code":"00000","msg":"success","requestTime":1708157298398,"data":[["1707868800000","9.3206","10.9891","9.18","10.7388","29317.75","300355.318193","300355.318193"]]}
```

**Comment by x1i4b1x2** [comment]
Any update on this?

**Comment by ttodua** [comment]
this might be the commit you were referring to - https://github.com/ccxt/ccxt/commit/ce1189ee70a105c9c2922db75cb7aa323fa29168
I'm looking into this problem
