### ISSUE TITLE
Bybit GET 404 Not Found

### ISSUE THREAD

**Issue by WesyHub** [ccxt/ccxt#21190]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.2.41

### Description

Hello, I use the bot I coded with ccxt for 1 years now. But since two I have the impression that there have been changes because I can no longer use ccxt with bybit, I tried to see the permissions api etc I have not found any solution. To reproduce the problem just put its key api and tried a fetch_markets or any other functions enfaite, I will always have the same error..
![2024-02-11 01_50_23-Window CCXT](https://github.com/ccxt/ccxt/assets/35263085/76e4a30e-17c4-478c-8b82-b8271c0ed1a1)
![2024-02-11 01_50_00-Window CCXT](https://github.com/ccxt/ccxt/assets/35263085/f8de6c6f-f723-4faa-9b29-5db54e5040dd)

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @WesyHub 

We already remove fetch usdc markets function in 4.2.41, can you check the version your software load? https://github.com/ccxt/ccxt/blob/4.2.41/python/ccxt/bybit.py

![image](https://github.com/ccxt/ccxt/assets/10494397/af2130f8-afc5-4b88-bdfb-07f1058f6dce)

**Comment by WesyHub** [comment]
Thanks, it solved my issue! 

I used python 3.9 with old version of ccxt but i had the new version on the 3.11. So i had to change interpreter to 3.11. Next time i should use virtual env..
