### ISSUE TITLE
fetch_closed_orders "limit" parameter logic is wrong

### ISSUE THREAD

**Issue by Jabarda** [ccxt/ccxt#21193]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.2.40

### Description
Binance exchange.

In python the call fetch_closed_orders(symbol, limit) becomes
```
orders = self.fetch_orders(symbol, since, limit, params)
return self.filter_by(orders, 'status', 'closed')
```
Orders with a limit are downloaded, they are then filtered by status. 

Based on the name of the function, it seems that if you call it with "limit = 1", it should return the last closed order, but this will not happen if the last order is open due to the logic above.

By increasing the parameter you can get closed orders, but it is not obvious why limit=1 returns nothing, and limit = 25 suddenly returns one closed order (in my case).

Suggestions: change the description of the function/parameter, or implement the correct logic (which is of course more difficult).

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @Jabarda, I agree the problem is that binance does not provide an endpoint to fetch only closed orders, the endpoint used here returns all orders (open, closed, canceled).

Nonetheless, I will try to update our implementation to apply the limit only after fetching the orders.
