### ISSUE TITLE
Supporting some DEXes (the future!)

### ISSUE THREAD

**Issue by spig0t** [ccxt/ccxt#2119]
Some of the biggest+growing DEXes are for example IDEX and Bancor (both hovering around #60 in the top 100 exchanges), and it'd be really useful for CCXT to support them. Imho, DEXes are the future. While integrating them may require more dependencies (i.e. interacting directly with the Ethereum contracts using ethers.js or web3), it would be really useful for CCXT to do this, and going forward these can be expected to grow to bigger+bigger shares of the overall exchange volume.

**Comment by kroitor** [comment]
As for your proposal, we would love to have support for distributed exchanges, of course, your contributions and pull requests are welcome: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code 

So, yes, we are all for it )

We already have plans for integrating some DEXes, here, for example: https://github.com/ccxt/ccxt/issues/715 (EtherDelta) and some other as well ) If you would like to suggest a particular exchange that is missing in open issues, please, submit links to docs ) 

Hope it answers your post. Closing this for now, if you don't mind. Feel free to reopen it or just ask questions if any. Thx)

**Comment by spig0t** [comment]
I would just suggest to aim at the biggest DEXes at the moment and in the future - EtherDelta seems rather dying/dead now (though ForkDelta may have some future, but it's not got much volume at the moment), so it doesn't seem a particularly great candidate for integrating ... 

The bigger DEXes by volume now, which are also growing fast at the moment, are IDEX and Bancor .... so these would seem the most valuable to look to integrate. Bitshares is also sometimes up there in volume.

https://coinmarketcap.com/exchanges/volume/24-hour/ is one site which shows which exchanges have the most volume in the last 24 hours - it can fluctuate a bit, but iDEX+Bancor will typically be #1 + #2 out of the DEXes there.

**Comment by kroitor** [comment]
@spig0t thx for sharing your considerations!

**Comment by myyellowshoe** [comment]
Do you have a central place where you a voting/gathering focus for specific DEX's? Saw the #715 issue for etherDelta but didn't know if you had any others your considering.

**Comment by kroitor** [comment]
@myyellowshoe take a look here: https://github.com/ccxt/ccxt/issues?q=is%3Aopen+is%3Aissue+label%3A%22new+exchange%22

**Comment by myyellowshoe** [comment]
👍
