### ISSUE TITLE
Phemex watchBalance() is not supported yet despite documentation claiming it's supported

### ISSUE THREAD

**Issue by ThatOneCalculator** [ccxt/ccxt#21198]
### Operating System

Linux

### Programming Languages

JavaScript

### CCXT Version

4.2.42

### Description

Despite the documentation having https://docs.ccxt.com/#/exchanges/phemex?id=watchbalance

Calling `const balance = await exchange.watchBalance();` throws
```
42 |     }
43 | }
44 | // Exchange Error errors
45 | class ExchangeError extends Error {
46 |     constructor(message) {
47 |         super(message);
             ^
NotSupported: phemex watchBalance() is not supported yet
      at new ExchangeError (/home/kainoa/Git/BHInsidesAuto/node_modules/ccxt/js/src/base/errors.js:47:9)
      at new NotSupported (/home/kainoa/Git/BHInsidesAuto/node_modules/ccxt/js/src/base/errors.js:197:9)
      at /home/kainoa/Git/BHInsidesAuto/node_modules/ccxt/js/src/base/Exchange.js:3688:15
      at watchBalance (/home/kainoa/Git/BHInsidesAuto/node_modules/ccxt/js/src/base/Exchange.js:3687:24)
      at /home/kainoa/Git/BHInsidesAuto/updatedata.ts:13:23
```

**Comment by samgermain** [comment]
Can you share your full code? It's definitely implemented. I think that you might be importing plain ccxt instead of ccxtpro. [Here's the documentation on importing ccxt pro](https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual#javascript)
