### ISSUE TITLE
KuCoin PARTNER-SIGN wrongly calculated hmac/sha256

### ISSUE THREAD

**Issue by fl0wo** [ccxt/ccxt#21229]
### Operating System

MacOS/Linux

### CCXT Version

4.1.65

### Description

Hi, I think the KC-API-PARTNER-SIGN field is wrongly calculated.

Just had a chat with a KuCoin team, and noticed KC-API-PARTNER-SIGN is differently calculated (between them and the ccxt produced output).

Therefore I'm assuming their version is the one I should rely as source of truth, I guess there's something wrong in the signing function hmac/sha256.

Can anyone double check that the function works as expected please?

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @fl0wo 

Since you created two issues, I closed the previous one #21228.

Is there any code we can reproduce?

**Comment by fl0wo** [comment]
I do have a PDF example given by kucoin, not sure I way I can talk to you separetely (telegram for example)

**Comment by sc0Vu** [comment]
Hi @fl0wo 

It works with these options:

```JS
{
    "apiKey": "xxx",
    "secret": "xxxx",
    "password": "xxxx",
    "options": {
      "partner": {
        "spot": {
          "id": "goodbroker",
          "secret": "xxx"
        }
      }
    }
  }
```

Let me know if it doesn't work.

**Comment by fl0wo** [comment]
Hi, yep! It works now!

My bad, I was setting the "secret" field wrongly.
The "KC-API-PARTNER-SIGN" header is correctly set now.
The "KC-API-SIGN" is still different, is it fine or we should expect the same value for that field as well?

Thanks again.
