### ISSUE TITLE
New Exchange: COSS

### ISSUE THREAD

**Issue by Walodja1987** [ccxt/ccxt#2122]
Hi,

can we add COSS exchange please? https://coss.io/

Best,
Wladi

**Comment by jjhesk** [comment]
@Walodja1987 hey they dont have api documentation supported yet. for the best interest, you need to have connection to their developer to provide the doc for us.

**Comment by kroitor** [comment]
https://api.coss.io/v1/spec

**Comment by kroitor** [comment]
Good news! 

The COSS exchange has been integrated and listed under certified exchanges in CCXT 1.18.52+. 

Please, feel free to test it and let us know if you find any issues or inconsistencies. All feedback is welcome, we will be happy to answer your questions!
