### ISSUE TITLE
poloniex load_markets API fail

### ISSUE THREAD

**Issue by qdztxc** [ccxt/ccxt#2123]
self.p = ccxt.poloniex({'verbose': True})
        self.p_market = self.p.load_markets()
poloniex load_markets API fails with
'403 Client Error: Forbidden for url: https://poloniex.com/public?command=returnTicker'
The other exchanges work well.

I think it may be caused by identifying code check newly added in poloniex.

- OS:  windows 7 64 bit
- Programming Language version: python 2.7
- CCXT version: 1.10.1265
- Exchange: poloniex 
- Method: load_markets

**Comment by kroitor** [comment]
@qdztxc can you, please, post the complete verbose output of that snippet?

**Comment by qdztxc** [comment]
![ccxt](https://user-images.githubusercontent.com/36831344/36953432-a810b802-2055-11e8-9e0f-ca03c14a1bc3.png)

**Comment by kroitor** [comment]
@qdztxc no, I mean the full text output, literally, the screenshot cuts all strings... Anyway, are you able to reach that page with your browser? https://poloniex.com/public?command=returnTicker

**Comment by kroitor** [comment]
@qdztxc also, have you tried the steps from the Troubleshooting section of the Manual https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting ?

**Comment by qdztxc** [comment]
I think it caused by poloniex add identifying code check for IP from some countries.
![ccxt2](https://user-images.githubusercontent.com/36831344/36953554-b2a451b0-2056-11e8-9c4b-354a2c4706cf.png)

I think it could be bypassed by proxy.

**Comment by kroitor** [comment]
Ok, see this example script on how to bypass cloudflare: 

https://github.com/ccxt/ccxt/blob/master/examples/py/bypass-cloudflare.py. 

It may not always work, then you need to use a proxy, indeed, or copy the cloudflare cookie by hand from your browser (solve the captcha in your browser, then use the web inspector to get the cloudflare cookie from browser headers to your python code).

Closing this for now if you don't mind. Feel free to reopen it if needed or just ask questions if you ave any more. Thx!
