### ISSUE TITLE
EXMO - Creating Order - Problem with the parameters when using unified API

### ISSUE THREAD

**Issue by vvinni** [ccxt/ccxt#2124]
- OS: Windows 7
- Programming Language version: Python 3.6
- CCXT version: 1..11.10
- Exchange: EXMO
- Method: create_limit_buy_order()

Hi!

I don´t know if I´m doing something wrong or the API is behaving in an unpredictable way.

I´m trying to open a market order like this:

`buy = self.conn.create_limit_buy_order(PAIR, volume)`

and I got this error:,

> exmo {"result":false,"error":"Error 50049: Parameter is not a number 'price'"} 

Verbose True return this:

> Response: POST https://api.exmo.com/v1/order_create 200 {'Server': 'nginx', 'Date': 'Mon, 05 Mar 2018 01:30:45 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Key, Sign', 'Access-Control-Allow-Methods': 'POST, GET, OPTIONS, PUT, DELETE', 'Strict-Transport-Security': 'max-age=604800', 'Content-Encoding': 'gzip'} {"result":false,"error":"Error 50049: Parameter is not a number 'price'"}

**Comment by kroitor** [comment]
@vvinni for a limit buy order you need to supply at least the symbol, the amount and the price (three arguments to create_limit_buy_order: `buy = self.conn.create_limit_buy_order(PAIR, volume, price)`.

https://github.com/ccxt/ccxt/wiki

Let us know if it does not answer your question.

**Comment by vvinni** [comment]
Sorry man!

What I need is a market order! 

It's time to stop coding! I need some rest! 

Thank you for your reply!
