### ISSUE TITLE
Exchange "bybit"  will not work with Freqtrade. Reason: missing: fetchOrder

### ISSUE THREAD

**Issue by Sommerregen** [ccxt/ccxt#21263]
### Operating System

Linux

### Programming Languages

Python

### CCXT Version

4.2.45

### Description

Hello!

Thank you very much for this wonderful package! However, with the latest **Freqtrade 2024.1** and **CCXT 4.2.45** I have noticed an incompatibility with bybit. When I start freqtrade, I get the following error message

```
freqtrade.exceptions.OperationalException: Exchange "bybit"  will not work with Freqtrade. Reason: missing: fetchOrder
```

I think this is related to the recent API changes, which are also described here (#21167), as the "fetch_order" calls are deprecated (ref: https://github.com/ccxt/ccxt/blob/master/python/ccxt/bybit.py#L4182). Are there any workarounds at the moment?

### Code

```
  

```

**Comment by Sommerregen** [comment]
Sorry, wrong project

**Comment by carlosmiei** [comment]
@Sommerregen The workaround possible is to make two calls now, `fetch_open_order` and `fetch_closed_order`
