### ISSUE TITLE
nonce used error occurs in ccxt/upbit.py

### ISSUE THREAD

**Issue by Looma1116** [ccxt/ccxt#21266]
### Operating System

Windows11

### Programming Languages

Python

### CCXT Version

4.2.27

### Description

When sending rapidly orders with ccxt/upbit.py, it sometimes occurs 'nonce used' error.
It also discovered by Upbit's Developers, so they recommend to assign str(uuid.uuid4()) for nonce, rather than millisenconds.
So I offer to change nonce function of upbit.py to below codes

error response:
```
 "ccxt\upbit.py", line 1043, in create_order  File "ccxt\base\types.py", line 34, in unbound_method  File "ccxt\base\exchange.py", line 3353, in request  File "ccxt\base\exchange.py", line 3350, in fetch2  File "ccxt\base\exchange.py", line 638, in fetch  File "ccxt\upbit.py", line 1750, in handle_errorsccxt.base.errors.ExchangeError: upbit {"error":{"name":"nonce_used","message":"This temporary number has already been used."}}
```
### Code

```
    def nonce(self):
        # return self.milliseconds()
        return str(uuid.uuid4())

```

**Comment by sc0Vu** [comment]
@Looma1116 

Thanks, I saw they set nonce to uuid in example. I'll submit a PR for this.
