### ISSUE TITLE
XT

### ISSUE THREAD

**Issue by RuCatGH** [ccxt/ccxt#21298]
### Exchange Name

XT

### URL of the Exchange

https://www.xt.com/en

### URL of the Exchange's API docs

https://doc.xt.com/#index_overviewresource

### Why should this exchange be implemented?

This exchange is ranked 23rd in coinmarketcap for spot and 10th for derivatives

**Comment by samgermain** [comment]
XT was previously supported and removed for [reasons listed here](https://github.com/ccxt/ccxt/issues/18315)
