### ISSUE TITLE
Fetch Custom Rest API Endpoint

### ISSUE THREAD

**Issue by fl0wo** [ccxt/ccxt#21315]
### Operating System

Mac Os

### CCXT Version

4.1.56

### Description

Hi,

let's say I have a private endpoint I'd like to call using my ccxt instance, with api-key/secret and the rest of the options.

Let's suppose my endpoint is: GET /sapi/v1/account/apiRestrictions
Explained here: https://binance-docs.github.io/apidocs/spot/en/#get-api-key-permission-user_data
Exchange: binance

How could I obtain that?

Thank you.

### Code

```
  

```

**Comment by samgermain** [comment]
You can use the [implicit api](https://docs.ccxt.com/#/?id=implicit-api)

In this case, the method would be `sapiGetAccountApiRestrictions`

**Comment by kroitor** [comment]
```
exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
})
```
