### ISSUE TITLE
Binance WS should save orderbooks in handle_order_book or handleOrderBook

### ISSUE THREAD

**Issue by imty42** [ccxt/ccxt#21310]
### Operating System

macOS 11.7.10

### Programming Languages

JavaScript, Python, PHP

### CCXT Version

4.2.44

### Description

It seems, in this func: `handle_order_book` or `handleOrderBook`, orderbook data should be saved to `self.orderbooks`.

Having checked all language versions:

- python, `handle_order_book`, https://github.com/ccxt/ccxt/blob/master/python/ccxt/pro/binance.py#L319
- js, `handleOrderBook`, https://github.com/ccxt/ccxt/blob/master/js/src/pro/binance.js#L339
- php, `handle_order_book`, https://github.com/ccxt/ccxt/blob/master/php/pro/binance.php#L348
- ts, `handleOrderBook`, https://github.com/ccxt/ccxt/blob/master/ts/src/pro/binance.ts#L346

### Code

For example, in Python

``` python
# [https://github.com/ccxt/ccxt/blob/master/python/ccxt/pro/binance.py#L380](https://github.com/ccxt/ccxt/blob/master/python/ccxt/pro/binance.py#L380)
self.handle_order_book_message(client, message, orderbook)

# after this line, we could add
self.orderbooks[symbol] = orderbook

```

**Comment by carlosmiei** [comment]
Hello @imty42,
`handle_order_book_message` will save the deltas that `handle_order_book` processes. You don't need to reassign it again.
