### ISSUE TITLE
CCXT PRO | ws methods a wsProxy results in Timeout

### ISSUE THREAD

**Issue by fl0wo** [ccxt/ccxt#21336]
### Operating System

MacOS/Linux

### CCXT Version

4.1.66 & 4.2.49 (tried both)

### Description

Hi,
I'm using binance instance of ccxt pro.

```
   const ccxtPro = ... 
   
   const proxy = 'http://my-user:my-pwd@my-domain:80'
    ccxtPro.httpProxy = proxy;
    ccxtPro.wsProxy = proxy;
    
  const res = await ccxtPro.fetchBalanceWs();

```

Resulting:
```
RequestTimeout: Connection to wss://ws-api.binance.com:443/ws-api/v3 failed due to a connection timeout
    at WsClient.onConnectionTimeout (/..../node_modules/ccxt/dist/cjs/src/base/ws/Client.js:112:27)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)
```

Considerations:

1. I know for sure the api-key & secret are correct because I'm using them on REST endpoints
2. I know for sure it's an issue related to the proxy because when I try the same ws call without proxy it works.
2.5 The same proxy for REST calls it works perfectly
3. I think the proxy handles the WS request correctly and returns the result (as I can see it in my Proxy Server logs)
4. I've contacted my Proxy Server provider and they confirmed WebSocket connections are supported

Any idea where I am getting lost?

Any support is greatly appreciated.

# EDIT

Trying this example: https://github.com/ccxt/ccxt/blob/master/examples/js/proxy-usage.js

I get connection timeout even with other exchanges (OKX for example):
RequestTimeout: Connection to wss://ws.okx.com:8443/ws/v5/public failed due to a connection timeout

I guess it's an issue related to my Proxy Server... I'll close this Issue as soon as I'll get the confirmation. Sorry

_No response_

**Comment by ttodua** [comment]
have you tried to use `.httpsProxy = proxy;` instead of `.httpProxy = proxy;` ?

**Comment by fl0wo** [comment]
Noway it worked, how?

Thank you so much, I'm afk right now but surely it's great to see at least I've got a response.

**Comment by fl0wo** [comment]
It worked.
Awesome support thank you.
