### ISSUE TITLE
Withdrawal request on MEXC returns "Signature for this request is not valid"

### ISSUE THREAD

**Issue by fartat** [ccxt/ccxt#21337]
### Operating System

Linux

### Programming Languages

PHP

### CCXT Version

4.2.46

### Description

I am using the php version 4.2.46 of CCXT to connect to Mexc on a linux with php 8.2 and I can succesfully place orders, check orders, cancel orders, but can't withdraw (tried 5 different coins and different networks, USDT included) and I always get the same error "ccxt\AuthenticationError: mexc {"code":700002,"msg":"Signature for this request is not valid."}". I even checked the way the signature is created in the class and it's created the same way as per a place order request.

### Code

```
$exchange_to = '\\ccxt\\mecx';
$bot = new $exchange_to(array(
    'apiKey' => $api_key_public,
    'secret' => $api_key_private,
    'timeout' => 60000,
    'enableRateLimit' => true,
    'options' => array(
        'defaultType' => 'spot'
    )
));

$withdraw = $bot->withdraw('USDT', 100, '0xc7b740e03156e0b1a54e8ca8687a0c79a5046930', NULL, ["network" => 'BEP20']);
```

**Comment by sc0Vu** [comment]
Hi @fartat,

It looks like something wrong happened when generate signature in PHP. I'll fix this.
