### ISSUE TITLE
Mexc support is broken for python with the error: Invalid content Type

### ISSUE THREAD

**Issue by dubisoft-solutions** [ccxt/ccxt#21345]
### Operating System

Cross platform

### Programming Languages

Python

### CCXT Version

Latest

### Description

Mexc recently released an update that breaks ccxt.

This is the update details: 
https://www.mexc.com/support/articles/17827791513387

The error I am getting now looks like this:
```
try:
  trades = await asyncio.wait_for(a.exchange.watch_my_trades(a.m.symbol, a.trade_ts), timeout=1800)
except asyncio.TimeoutError:
  pass
except asyncio.CancelledError:
  logger.warning('waiting for trades canceled')
  raise asyncio.CancelledError
except Exception as e:
  log.critical(str(e))
  raise e

ccxt.base.errors.ExchangeError: mexc {"code":700013,"msg":"Invalid content Type."}

```

It seems something is not right with the headers. Can somebody take a look?

**Comment by carlosmiei** [comment]
Hello @samgermain thanks a lot for letting us know we will take a look asap.

**Comment by carlosmiei** [comment]
@dubisoft-solutions For some reason, I can't reproduce the issue; what's your Python version?
Would you mind sharing a verbose log? `exchange?verbose = True`

**Comment by dubisoft-solutions** [comment]
python version 3.12.1

It is working again, probably there is some underlying logic that in case of retries makes a request and misses the content-type header?

**Comment by dubisoft-solutions** [comment]
@carlosmiei , reproduced again

<img width="1302" alt="image" src="https://github.com/ccxt/ccxt/assets/113454503/01b74a6a-4506-4f68-8ca3-5aa8ecb9b237">

**Comment by grozz97** [comment]
@carlosmiei, 

When using watch_balance() I also get this error. It occurs after about 20-30 minutes of use.

```
...
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/pro/mexc.py", line 947, in watch_balance
    return await self.watch_spot_private(channel, messageHash, params)
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/pro/mexc.py", line 175, in watch_spot_private
    return await self.watch(url, messageHash, self.extend(request, params), channel)
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/pro/mexc.py", line 1027, in keep_alive_listen_key
    await self.spotPrivatePutUserDataStream(self.extend(request, params))
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 753, in request
    return await self.fetch2(path, api, method, params, headers, body, config)
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 750, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 243, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/user/.local/lib/python3.8/site-packages/ccxt/async_support/mexc.py", line 5047, in handle_errors
    raise ExchangeError(feedback)
ccxt.base.errors.ExchangeError: mexc {"code":700013,"msg":"Invalid content Type."}
```

**Comment by kaiqiangh** [comment]
the same problem here

**Comment by Dan-krm** [comment]
I've opened a pull request that should resolve this issue. The Content-Type wasn't being set to application/json for put endpoints and `spotPrivatePutUserDataStream` was being called every 20 minutes through the `keep_alive_listen_key` method.

**Comment by dubisoft-solutions** [comment]
thank you! when the new version will be released and available through pip?

**Comment by carlosmiei** [comment]
@dubisoft-solutions @kaiqiangh @grozz97 We released a new version with the fix. can you please update your ccxt version to the latest and try again?

**Comment by dubisoft-solutions** [comment]
@carlosmiei , thank you so much! everything is working now as expected

**Comment by grozz97** [comment]
@carlosmiei  Everything works, thank you
