### ISSUE TITLE
inconsistent timeframes format 

### ISSUE THREAD

**Issue by ws2367** [ccxt/ccxt#2134]
The issue is that the format of the exchange property timeframes is NOT consistent. 
```
exchange_ids = ['binance', 'bitfinex', 'hitbtc', 'kucoin', 'kraken', 'poloniex', 'gdax', 'gemini', 'huobipro', 'okex']
exchanges = [getattr(ccxt, str.lower())() for str in exchange_ids]
[print(ex.timeframes) for ex in exchanges if hasattr(ex, 'timeframes')]
```

The above code prints out some examples in the following:
```
{'1m': '1m', '3m': '3m', '5m': '5m', '15m': '15m', '30m': '30m', '1h': '1h', '2h': '2h', '4h': '4h', '6h': '6h', '8h': '8h', '12h': '12h', '1d': '1d', '3d': '3d', '1w': '1w', '1M': '1M'}
{'1m': '1m', '5m': '5m', '15m': '15m', '30m': '30m', '1h': '1h', '3h': '3h', '6h': '6h', '12h': '12h', '1d': '1D', '1w': '7D', '2w': '14D', '1M': '1M'}
{'1m': '1', '5m': '5', '15m': '15', '30m': '30', '1h': '60', '8h': '480', '1d': 'D', '1w': 'W'}
{'1m': '1', '5m': '5', '15m': '15', '30m': '30', '1h': '60', '4h': '240', '1d': '1440', '1w': '10080', '2w': '21600'}
{'5m': 300, '15m': 900, '30m': 1800, '2h': 7200, '4h': 14400, '1d': 86400}
{'1m': 60, '5m': 300, '15m': 900, '30m': 1800, '1h': 3600, '2h': 7200, '4h': 14400, '12h': 43200, '1d': 86400, '1w': 604800, '1M': 2592000, '1y': 31536000}
{'1m': '1min', '5m': '5min', '15m': '15min', '30m': '30min', '1h': '60min', '1d': '1day', '1w': '1week', '1M': '1mon', '1y': '1year'}
{'1m': '1min', '3m': '3min', '5m': '5min', '15m': '15min', '30m': '30min', '1h': '1hour', '2h': '2hour', '4h': '4hour', '6h': '6hour', '12h': '12hour', '1d': '1day', '3d': '3day', '1w': '1week'}
```

`timeframes` is a hash and the values of it do not follow a format across exchanges. For example, some are like '1m' or '5m' that are no different from the keys. Some others are the actual duration in seconds which arguably is the desired format. Some others are just more descriptive keys such as '1min', '1day' and etc. 

- OS: 
OSX 10.13.3

- Programming Language version: 
Python 3.6.4

- CCXT version:
1.10.760

- Exchange:
binance
bitfinex
hitbtc
kucoin
kraken
poloniex
gdax
gemini
huobipro
okex

- Method:
the property timeframes

**Comment by kroitor** [comment]
`timeframes` is a hash, where keys are unified and values are exchange-specific, so, I don't see any inconsistencies there. You should not rely on the values under the keys and their formats, as they are exchange-specific. The keys are exchange-agnostic and unified and can be safely used across exchanges, namely, the "1m", "5m", "15m", "1h", and so on – those are standardized. So, I don't see an issue here, it's a matter of interpretation. If you need to get the duration in seconds, use the parseTimeframe/parse_timeframe method. Hope it helps. Let us know if it does not answer your question. Thx!

**Comment by ws2367** [comment]
makes sense. Thanks!
