### ISSUE TITLE
Is fiat deposit() supported in ccxt? 

### ISSUE THREAD

**Issue by jtashiro** [ccxt/ccxt#21375]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Describe the solution you'd like

Using coinbase and would like to automate fiat deposits into my USD account using ccxt.  I can do this with other python API (coinbase_advancedtrade) but would prefer to do this within ccxt.

### Describe alternatives you've considered

Developed deposit() method in coinbase.py modeled off withdraw() method - bit rough but verified it works.

**Comment by carlosmiei** [comment]
Hello @jtashiro, thanks for your suggestion, we will take that into consideration!

**Comment by Dan-krm** [comment]
@jtashiro could you share the alternative deposit method you've tried or the endpoint that you're using for this

**Comment by jtashiro** [comment]
Here is what I've added to my local copy of coinbase.py.  I don't use the tag and I let the existing functions find the proper accountId based on the code (USD) parameter.

```
    def deposit(self,  amount: float, code, payment_method, tag=None, params={}):
        """
        make a deposit
        :see: https://docs.cloud.coinbase.com/sign-in-with-coinbase/docs/api-deposits#deposit-funds
        :param str accountId: coinbase account to deposit into
        :param float amount: the amount to deposit
        :param str currency: the currency to deposit (ie USD)
        :param str payment_method: source of funds (ie id of the bank account registered in Coinbase using get_payment_methods endpoint)
        :returns dict: a transaction structure
        """
        tag,params = self.handle_withdraw_tag_and_params(tag, params)
        self.load_markets()
        currency = self.currency(code)
        accountId = self.safe_string_2(params, 'account_id', 'accountId')
        params = self.omit(params, ['account_id', 'accountId']) 
        if accountId is None:
            if code is None:
                raise ArgumentsRequired(self.id + ' deposit() requires an account_id(or accountId) parameter OR a currency code argument')
            accountId = self.find_account_id(code)
            if accountId is None:
                raise ExchangeError(self.id + ' deposit() could not find account id for ' + code)
        request = {
            'account_id': accountId,
            'amount': amount,
            'currency': code,
            'payment_method': payment_method
        }
        response = self.v2PrivatePostAccountsAccountIdDeposits(self.extend(request, params))
        data = self.safe_value(response, 'data', {})
        return self.parse_transaction(data, currency)

```

Call within a deposit.py script

```
      code = 'USD'
      payment_method = < id from get_payment_methods for the ach account >
      amount = '10'
      params = { 'v3': True }
      deposit = coinbase.deposit(amount, code, payment_method, params=params)
      pprint(deposit)

```

**Comment by jtashiro** [comment]
I’ve posted the code snippet to GitHub for review.

**Comment by Dan-krm** [comment]
@jtashiro I opened a pull request that adds `deposit` and `fetchDeposit` methods to coinbase for fiat deposits, let me know if you have any issues with using them once they are merged

**Comment by jtashiro** [comment]
great, am happy to test it - which version will this be in?

**Comment by carlosmiei** [comment]
@jtashiro If you update your ccxt version you should be able to get it now. Can you give it a shot?

**Comment by jtashiro** [comment]
Thank you - I see the deposit() method and will test later.

However, I need to update the magic number 100 to 250 in fetch_accounts() because that seems to be broken with Coinbase …
