### ISSUE TITLE
Filter markets in C#

### ISSUE THREAD

**Issue by nikky78** [ccxt/ccxt#21372]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Describe the solution you'd like

Hi,

The documentation in C# is quite small compared to python for instance and so I'm trying to transfer my python code into C# but can't find proper way:
Anyone could tell me how I could do that python code in C# please?
    exchange = ccxt.pro.binance({
        'apiKey': 'xxx',
        'secret': 'xxx',
        'options': {
            'defaultType': 'spot', 
        },
    })
    await exchange.load_markets()
    markets = dict(filter(lambda market: market[1]['spot'] and market[1]['active'], exchange.markets.items()))
    symbols = list(markets.keys())

**Comment by carlosmiei** [comment]
Hello @nikky78 I will post a snippet here shortly.

**Comment by carlosmiei** [comment]
@nikky78 Sorry for the delay, if you update your ccxt version you can do something like this
https://github.com/ccxt/ccxt/blob/master/examples/cs/examples/get-active-markets.cs
