### ISSUE TITLE
CCXT.pro watch_orders bug

### ISSUE THREAD

**Issue by deepsoutha** [ccxt/ccxt#21384]
### Operating System

ubuntu

### CCXT Version

ccxt-4.2.51

### Description

ccxt.pro.binanceusdm(), when there are multiple pending orders in my Binance Futures account, I manually cancel all of them with one click on the APP, and find that only one message about order is canceled。so the question is , when I manually cancel an order at once, the order will be missed

### Code

```
main_account = ccxtpro.binanceusdm({
    'apiKey': main_api['apiKey'],
    'secret': main_api['secret'],


})
odata = await main_account.watch_orders()
print(odata)

```

启动 2024-02-26 10:22:30
[{'info': {'s': 'ETHUSDT', 'c': 'ios_TjQvPQy5Za2kpZv1df7b', 'S': 'BUY', 'o': 'LIMIT', 'f': 'GTC', 'q': '0.098', 'p': '3060', 'ap': '0', 'sp': '0', 'x': 'NEW', 'X': 'NEW', 'i': 8389765655692226763, 'l': '0', 'z': '0', 'L': '0', 'n': '0', 'N': 'USDT', 'T': 1708914163765, 't': 0, 'b': '299.87999', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'LIMIT', 'ps': 'LONG', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'NONE', 'pm': 'NONE', 'gtd': 0}, 'symbol': 'ETH/USDT:USDT', 'id': '8389765655692226763', 'clientOrderId': 'ios_TjQvPQy5Za2kpZv1df7b', 'timestamp': 1708914163765, 'datetime': '2024-02-26T02:22:43.765Z', 'lastTradeTimestamp': None, 'lastUpdateTimestamp': 1708914163765, 'type': 'limit', 'timeInForce': 'GTC', 'postOnly': False, 'reduceOnly': False, 'side': 'buy', 'price': 3060.0, 'stopPrice': 0.0, 'triggerPrice': 0.0, 'amount': 0.098, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 0.098, 'status': 'open', 'fee': None, 'trades': [], 'fees': [], 'takeProfitPrice': None, 'stopLossPrice': None}]
ETH/USDT:USDT buy 3060.0 0.098 0.0 8389765655692226763 LONG NEW
限价单
[{'info': {'s': 'ETHUSDT', 'c': 'ios_qnpfuBlRsgWnJnQkMVoM', 'S': 'BUY', 'o': 'LIMIT', 'f': 'GTC', 'q': '0.098', 'p': '3050', 'ap': '0', 'sp': '0', 'x': 'NEW', 'X': 'NEW', 'i': 8389765655692232193, 'l': '0', 'z': '0', 'L': '0', 'n': '0', 'N': 'USDT', 'T': 1708914170532, 't': 0, 'b': '598.78000', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'LIMIT', 'ps': 'LONG', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'NONE', 'pm': 'NONE', 'gtd': 0}, 'symbol': 'ETH/USDT:USDT', 'id': '8389765655692232193', 'clientOrderId': 'ios_qnpfuBlRsgWnJnQkMVoM', 'timestamp': 1708914170532, 'datetime': '2024-02-26T02:22:50.532Z', 'lastTradeTimestamp': None, 'lastUpdateTimestamp': 1708914170532, 'type': 'limit', 'timeInForce': 'GTC', 'postOnly': False, 'reduceOnly': False, 'side': 'buy', 'price': 3050.0, 'stopPrice': 0.0, 'triggerPrice': 0.0, 'amount': 0.098, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 0.098, 'status': 'open', 'fee': None, 'trades': [], 'fees': [], 'takeProfitPrice': None, 'stopLossPrice': None}]
ETH/USDT:USDT buy 3050.0 0.098 0.0 8389765655692232193 LONG NEW
限价单
[{'info': {'s': 'ETHUSDT', 'c': 'ios_qnpfuBlRsgWnJnQkMVoM', 'S': 'BUY', 'o': 'LIMIT', 'f': 'GTC', 'q': '0.098', 'p': '3050', 'ap': '0', 'sp': '0', 'x': 'CANCELED', 'X': 'CANCELED', 'i': 8389765655692232193, 'l': '0', 'z': '0', 'L': '0', 'n': '0', 'N': 'USDT', 'T': 1708914177729, 't': 0, 'b': '299.87999', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'LIMIT', 'ps': 'LONG', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'NONE', 'pm': 'NONE', 'gtd': 0}, 'symbol': 'ETH/USDT:USDT', 'id': '8389765655692232193', 'clientOrderId': 'ios_qnpfuBlRsgWnJnQkMVoM', 'timestamp': 1708914177729, 'datetime': '2024-02-26T02:22:57.729Z', 'lastTradeTimestamp': None, 'lastUpdateTimestamp': 1708914177729, 'type': 'limit', 'timeInForce': 'GTC', 'postOnly': False, 'reduceOnly': False, 'side': 'buy', 'price': 3050.0, 'stopPrice': 0.0, 'triggerPrice': 0.0, 'amount': 0.098, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 0.098, 'status': 'canceled', 'fee': None, 'trades': [], 'fees': [], 'takeProfitPrice': None, 'stopLossPrice': None}]
ETH/USDT:USDT buy 3050.0 0.098 0.0 8389765655692232193 LONG CANCELED

**Comment by algosfox** [comment]
Hello @deepsoutha. Looks like you are only reading once, try reading the data in a loop.

```
    while True:
         orders = await exchange.watch_orders()
```

**Comment by deepsoutha** [comment]
I try ,but failed.
async def watch_bn_order():
    while True:
        try:
            while True:
                odata = await main_account.watch_orders()
                print(odata)
                for x in odata:
                    symbol = x['symbol']
                    side = x['side']
                    filled = x['filled']
                    status = x["info"]['x']
                    posSide = x['info']['ps']
                    p = x['average']

                    id = x['id']
                    otype = x['type']
                    price = x['price']
                    num = x['amount']

                    print(symbol,side,price,num,filled,id,posSide,status)

                    if status == "TRADE" and float(filled) > 0:
                        current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                        tt = time.time()
                        fei.send_text(f"{current_time}  {tt} 主账户 {symbol} {posSide} {side} {filled} 个 价格={p}")
                        tasks = [follow_order_bn(account, symbol, side, filled, posSide, id) for
                                 account in follow_bn_api]
                        await asyncio.gather(*tasks)

                    if status == "CANCELED":
                        tasks = [follow_order_bn_cancel(account, symbol, id) for
                                 account in follow_bn_api]
                        await asyncio.gather(*tasks)

                    if status == "NEW" and otype == "limit":
                        print("限价单")
                        tasks = [follow_order_bn_limit(account, symbol, num, price, posSide, side, id) for
                                 account in follow_bn_api]
                        await asyncio.gather(*tasks)
                    else:
                        pass
        except Exception as e:
            current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            feie.send_text(f"{current_time} BN主账户程序出错了 " + str(e))
            await asyncio.sleep(3)

**Comment by deepsoutha** [comment]
> Hello @deepsoutha. Looks like you are only reading once, try reading the data in a loop.
> 
> ```
>     while True:
>          orders = await exchange.watch_orders()
> ```



I try ,but failed.

```


async def watch_bn_order():
    while True:
        try:
            while True:
                odata = await main_account.watch_orders()
                print(odata)
                for x in odata:
                    symbol = x['symbol']
                    side = x['side']
                    filled = x['filled']
                    status = x["info"]['x']
                    posSide = x['info']['ps']
                    p = x['average']

                    id = x['id']
                    otype = x['type']
                    price = x['price']
                    num = x['amount']

                    print(symbol,side,price,num,filled,id,posSide,status)

                    if status == "TRADE" and float(filled) > 0:
                        current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                        tt = time.time()
                        fei.send_text(f"{current_time}  {tt} 主账户 {symbol} {posSide} {side} {filled} 个 价格={p}")
                        tasks = [follow_order_bn(account, symbol, side, filled, posSide, id) for
                                 account in follow_bn_api]
                        await asyncio.gather(*tasks)

                    if status == "CANCELED":
                        tasks = [follow_order_bn_cancel(account, symbol, id) for
                                 account in follow_bn_api]
                        await asyncio.gather(*tasks)

                    if status == "NEW" and otype == "limit":
                        print("限价单")
                        tasks = [follow_order_bn_limit(account, symbol, num, price, posSide, side, id) for
                                 account in follow_bn_api]
                        await asyncio.gather(*tasks)
                    else:
                        pass
        except Exception as e:
            current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            feie.send_text(f"{current_time} BN主账户程序出错了 " + str(e))
            await asyncio.sleep(3)

```

**Comment by deepsoutha** [comment]
only received one canceled message.

```
启动 2024-02-27 10:04:11
[{'info': {'s': 'HIGHUSDT', 'c': 'ios_o1pgIXTkaE12EOIRdkVV', 'S': 'BUY', 'o': 'LIMIT', 'f': 'GTC', 'q': '11.7', 'p': '1.700000', 'ap': '0', 'sp': '0', 'x': 'NEW', 'X': 'NEW', 'i': 1378597867, 'l': '0', 'z': '0', 'L': '0', 'n': '0', 'N': 'USDT', 'T': 1708999477425, 't': 0, 'b': '19.8900000', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'LIMIT', 'ps': 'LONG', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'NONE', 'pm': 'NONE', 'gtd': 0}, 'symbol': 'HIGH/USDT:USDT', 'id': '1378597867', 'clientOrderId': 'ios_o1pgIXTkaE12EOIRdkVV', 'timestamp': 1708999477425, 'datetime': '2024-02-27T02:04:37.425Z', 'lastTradeTimestamp': None, 'lastUpdateTimestamp': 1708999477425, 'type': 'limit', 'timeInForce': 'GTC', 'postOnly': False, 'reduceOnly': False, 'side': 'buy', 'price': 1.7, 'stopPrice': 0.0, 'triggerPrice': 0.0, 'amount': 11.7, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 11.7, 'status': 'open', 'fee': None, 'trades': [], 'fees': [], 'takeProfitPrice': None, 'stopLossPrice': None}]
HIGH/USDT:USDT buy 1.7 11.7 0.0 1378597867 LONG NEW
限价单
[{'info': {'s': 'HIGHUSDT', 'c': 'ios_kFNqE0kqslld4R5ax7i6', 'S': 'BUY', 'o': 'LIMIT', 'f': 'GTC', 'q': '35.7', 'p': '1.680000', 'ap': '0', 'sp': '0', 'x': 'NEW', 'X': 'NEW', 'i': 1378598064, 'l': '0', 'z': '0', 'L': '0', 'n': '0', 'N': 'USDT', 'T': 1708999485018, 't': 0, 'b': '79.8660000', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'LIMIT', 'ps': 'LONG', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'NONE', 'pm': 'NONE', 'gtd': 0}, 'symbol': 'HIGH/USDT:USDT', 'id': '1378598064', 'clientOrderId': 'ios_kFNqE0kqslld4R5ax7i6', 'timestamp': 1708999485018, 'datetime': '2024-02-27T02:04:45.018Z', 'lastTradeTimestamp': None, 'lastUpdateTimestamp': 1708999485018, 'type': 'limit', 'timeInForce': 'GTC', 'postOnly': False, 'reduceOnly': False, 'side': 'buy', 'price': 1.68, 'stopPrice': 0.0, 'triggerPrice': 0.0, 'amount': 35.7, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 35.7, 'status': 'open', 'fee': None, 'trades': [], 'fees': [], 'takeProfitPrice': None, 'stopLossPrice': None}]
HIGH/USDT:USDT buy 1.68 35.7 0.0 1378598064 LONG NEW
限价单
[{'info': {'s': 'HIGHUSDT', 'c': 'ios_kFNqE0kqslld4R5ax7i6', 'S': 'BUY', 'o': 'LIMIT', 'f': 'GTC', 'q': '35.7', 'p': '1.680000', 'ap': '0', 'sp': '0', 'x': 'CANCELED', 'X': 'CANCELED', 'i': 1378598064, 'l': '0', 'z': '0', 'L': '0', 'n': '0', 'N': 'USDT', 'T': 1708999491998, 't': 0, 'b': '19.8900000', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'LIMIT', 'ps': 'LONG', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'NONE', 'pm': 'NONE', 'gtd': 0}, 'symbol': 'HIGH/USDT:USDT', 'id': '1378598064', 'clientOrderId': 'ios_kFNqE0kqslld4R5ax7i6', 'timestamp': 1708999491998, 'datetime': '2024-02-27T02:04:51.998Z', 'lastTradeTimestamp': None, 'lastUpdateTimestamp': 1708999491998, 'type': 'limit', 'timeInForce': 'GTC', 'postOnly': False, 'reduceOnly': False, 'side': 'buy', 'price': 1.68, 'stopPrice': 0.0, 'triggerPrice': 0.0, 'amount': 35.7, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 35.7, 'status': 'canceled', 'fee': None, 'trades': [], 'fees': [], 'takeProfitPrice': None, 'stopLossPrice': None}]
```

**Comment by deepsoutha** [comment]
@algosfox

**Comment by deepsoutha** [comment]
async def follow_order_bn_cancel(account, symbol, id):
    fbn = follow_bn_api[account]
    oid = bn_id[str(id)]
    print("开始撤单")
    dataf = await fbn.cancel_order(symbol=symbol, id=oid)

    print(dataf)
    bn_id.pop(str(id))
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    fei.send_text(f"{current_time} BN账户{account} 撤单 {symbol} id {oid}")
    print("撤单成功")

**Comment by deepsoutha** [comment]
succeed
