### ISSUE TITLE
How to query prices in orderbook in C#

### ISSUE THREAD

**Issue by nikky78** [ccxt/ccxt#21380]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Describe the solution you'd like

Could you provide some documentation on how to query prices in the orderbook in C#, please.
Like in Python, one could do exchange.orderbook["asks"][0][0]. That would give the first price available in the ask side. 
That method does not work for me in C#.

**Comment by sc0Vu** [comment]
Hi @nikky78 

You can transform the asks to object and list, try this:

```C#
var asks = ((IDictionary<string, object>)resultNew)["asks"];
var firstAskPrice = ((IList<object>)asks)[0];
Console.WriteLine(((IList<object>)firstAskPrice)[0]);
Console.WriteLine(((IList<object>)firstAskPrice)[1]);
```

**Comment by carlosmiei** [comment]
Hello @nikky78 which method are you using? It's not needed to cast your result if you're using the typed function.

**Comment by carlosmiei** [comment]
@nikky78 Example:

```c#
        var orderbook = await this.FetchOrderBook("BTC/USDT");
        var asks = orderbook.asks;
        var bids = orderbook.bids;
        Console.WriteLine(asks[0][0]);
```
