### ISSUE TITLE
Bitvavo watch_orders doesn't work

### ISSUE THREAD

**Issue by apollace** [ccxt/ccxt#21390]
### Operating System

Ubuntu 22.04

### Programming Languages

Python

### CCXT Version

ccxtpro 1.0.1 ccxt 4.2.48

### Description

The `watch_orders` feature for Bitvavo is implemented but never returns. 

Step to reproduce:
 - Run the code below
 - Go to Bitvavo GUI and create/modify an order
 - Nothing happens in the code

Can you help?

### Code

```
  async def main():
    bitvavo_ordering = ccxt.pro.bitvavo({'enableRateLimit': True})

    bitvavo_ordering.apiKey = os.getenv("API_KEY")
    bitvavo_ordering.secret = os.getenv("API_SECRET")
    await bitvavo_ordering.authenticate()
    while True:
        orders = await bitvavo_ordering.watch_orders("BTC/EUR")
        print(orders)


if __name__ == "__main__":
    asyncio.run(main())

```

**Comment by apollace** [comment]
I looks like an issue with the authentication, the `watch_ticker` works without authentication, after the authentication however I observe the same issue.

**Comment by sc0Vu** [comment]
@apollace 

Please remove await bitvavo_ordering.authenticate() from your code. We already call that in watch_orders.

**Comment by apollace** [comment]
it works, thanks for the help
