### ISSUE TITLE
Bitget) Order is not opening.

### ISSUE THREAD

**Issue by PUVl** [ccxt/ccxt#21406]
### Operating System

Window 10

### Programming Languages

Python

### CCXT Version

Latest

### Description

I could place an order until yesterday.
but it doesn't work now. I don't know why.
plz help

here is error

ExchangeError bitget {"code":"400172","msg":"Illegal position opening type","requestTime":1709016661816,"data":null}

### Code

def main():
import os
import sys
import pprint
import math
import pandas as pd
import time

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402

#apiKey, Secret, Password
api_key = ''
api_secret = '
api_password = ''

bitget = ccxt.bitget({
    'apiKey': api_key,
    'secret': api_secret,
    'password': api_password,
    'options': {
        'defaultType': 'swap',
    }
})

    try:

        markets = bitget.load_markets()

        # exchange.verbose = True  # uncomment for debugging purposes if necessary

        # fetching informations  (symbol 거래 종목으로 바꾸기)
        symbol = 'PEPE/USDT:USDT'
        balances = bitget.fetch_balance()
        order_book = bitget.fetch_order_book(symbol)
        bid_1 = order_book['bids'][0][0]
        ask_1 = order_book['asks'][0][0]
        market_price_1 = ((bid_1 + ask_1) / 2)
        usdt_balance = balances['total']['USDT']  # USDT 잔고
        desired_usdt_amount_1 = math.floor(usdt_balance/750)*20*3**(1-1)  # 원하는 거래 금액 (USDT)
        amount_1 = desired_usdt_amount_1 / market_price_1  # USDT 금액을 현재 시세로 계산하여 amount로 설정

        #placing an order(1번째 주문생성)
        type_1 = 'market'
        side_1 = 'open_long'
        size_1 = amount_1

        order_1 = bitget.create_order(symbol, type_1, side_1, size_1)        
    except Exception as e:
        print(type(e).__name__, str(e))

main()

**Comment by sc0Vu** [comment]
@PUVl 

I think the order type was wrong. You can find here: https://github.com/ccxt/ccxt/wiki/Manual#placing-orders. And examples: https://github.com/ccxt/ccxt/tree/master/examples/py

BTW, there is no open_long side in bitget, you can find here: https://www.bitget.com/api-doc/contract/trade/Place-Order

**Comment by PUVl** [comment]
> @PUVl
> 
> I think the order type was wrong. You can find here: https://github.com/ccxt/ccxt/wiki/Manual#placing-orders. And examples: https://github.com/ccxt/ccxt/tree/master/examples/py
> 
> BTW, there is no open_long side in bitget, you can find here: https://www.bitget.com/api-doc/contract/trade/Place-Order

So, 
For open long, fill in"Buy"; tradeSide should be "Open"
For open short, fill in "Sell"; tradeSide should be "Open"
For close long, fill in "Buy"; tradeSide should be "Close"
For close short, fill in "Sell"; tradeSide should be "Close"

for example, how can I know it is close short or open short, it same 'Sell'

**Comment by PUVl** [comment]
how can I fill tradeside?

This is the ccxt,
def create_order(self, symbol: str, type: OrderType, side: OrderSide, amount: float, price: float = None, params={}):
"""
create a trade order
:see: https://www.bitget.com/api-doc/spot/trade/Place-Order
:see: https://www.bitget.com/api-doc/spot/plan/Place-Plan-Order
:see: https://www.bitget.com/api-doc/contract/trade/Place-Order
:see: https://www.bitget.com/api-doc/contract/plan/Place-Tpsl-Order
:see: https://www.bitget.com/api-doc/contract/plan/Place-Plan-Order
:see: https://www.bitget.com/api-doc/margin/cross/trade/Cross-Place-Order
:see: https://www.bitget.com/api-doc/margin/isolated/trade/Isolated-Place-Order
:param str symbol: unified symbol of the market to create an order in
:param str type: 'market' or 'limit'
:param str side: 'buy' or 'sell' or 'open_long' or 'open_short' or 'close_long' or 'close_short'
:param float amount: how much you want to trade in units of the base currency
:param float [price]: the price at which the order is to be fullfilled, in units of the quote currency, ignored in market orders
:param dict [params]: extra parameters specific to the exchange API endpoint
:param float [params.cost]: spot only how much you want to trade in units of the quote currency, for market buy orders only
:param float [params.triggerPrice]: swap only The price at which a trigger order is triggered at
:param float [params.stopLossPrice]: swap only The price at which a stop loss order is triggered at
:param float [params.takeProfitPrice]: swap only The price at which a take profit order is triggered at
:param dict [params.takeProfit]: takeProfit object in params containing the triggerPrice at which the attached take profit order will be triggered(perpetual swap markets only)
:param float [params.takeProfit.triggerPrice]: swap only take profit trigger price
:param dict [params.stopLoss]: stopLoss object in params containing the triggerPrice at which the attached stop loss order will be triggered(perpetual swap markets only)
:param float [params.stopLoss.triggerPrice]: swap only stop loss trigger price
:param str [params.timeInForce]: "GTC", "IOC", "FOK", or "PO"
:param str [params.marginMode]: 'isolated' or 'cross' for spot margin trading
:param str [params.loanType]: spot margin only 'normal', 'autoLoan', 'autoRepay', or 'autoLoanAndRepay' default is 'normal'
:param str [params.holdSide]: contract stopLossPrice, takeProfitPrice only Two-way position: ('long' or 'short'), one-way position: ('buy' or 'sell')
:param float [params.stopLoss.price]: swap only the execution price for a stop loss attached to a trigger order
:param float [params.takeProfit.price]: swap only the execution price for a take profit attached to a trigger order
:param str [params.stopLoss.type]: swap only the type for a stop loss attached to a trigger order, 'fill_price', 'index_price' or 'mark_price', default is 'mark_price'
:param str [params.takeProfit.type]: swap only the type for a take profit attached to a trigger order, 'fill_price', 'index_price' or 'mark_price', default is 'mark_price'
:param str [params.trailingPercent]: swap and future only the percent to trail away from the current market price, rate can not be greater than 10
:param str [params.trailingTriggerPrice]: swap and future only the price to trigger a trailing stop order, default uses the price argument
:param str [params.triggerType]: swap and future only 'fill_price', 'mark_price' or 'index_price'
:param boolean [params.oneWayMode]: swap and future only required to set self to True in one_way_mode and you can leave self in hedge_mode, can adjust the mode using the setPositionMode() method
:returns dict: an order structure <https://docs.ccxt.com/#/?id=order-structure>

**Comment by PUVl** [comment]
then, how can I use 'create order'?
ccxt only provide 'open_long or close_long'
there no choice between open or close juse long for buy, close for short.

**Comment by PUVl** [comment]
> @PUVl buy is for long sell is for short
> 
> It looks like open_long was outdated: https://bitgetlimited.github.io/apidoc/en/mix/#side
> 
> The side is different: https://www.bitget.com/api-doc/contract/trade/Place-Order

Is there any discord or telegram for support?

**Comment by sc0Vu** [comment]
@PUVl 

The unified side to createOrder in ccxt is buy and sell. open_long or close_short is exchange specific parameters, and seems they removed them.

You can create long order with buy side, and create short order with sell side. If you want to close a position you need to create order to the opposite side, eg. close long position (create sell order).

Have you checked manual yet?

**Comment by PUVl** [comment]
> @PUVl
> 
> The unified side to createOrder in ccxt is buy and sell. open_long or close_short is exchange specific parameters, and seems they removed them.
> 
> You can create long order with buy side, and create short order with sell side. If you want to close a position you need to create order to the opposite side, eg. close long position (create sell order).
> 
> Have you checked manual yet?
> 
> There is social section in README.md. https://github.com/ccxt/ccxt?tab=readme-ov-file#social

I already check the manual and create order to oppsite side isn't work. it's future, not spot. 

Creating a sell order to liquidate a long position acts as a short position creation.

So, I think ccxt will update for that.

**Comment by sc0Vu** [comment]
@PUVl 

uh, it should work. Can you paste code and verbose log?

**Comment by PUVl** [comment]
> @PUVl
> 
> uh, it should work. Can you paste code or verbose log?

# -*- coding: utf-8 -*-

import os
import sys
import pprint
import math
import pandas as pd
import time

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402

#apiKey, Secret, Password
api_key = ''
api_secret = ''
api_password = ''

bitget = ccxt.bitget({
    'apiKey': api_key,
    'secret': api_secret,
    'password': api_password,
    'options': {
        'defaultType': 'swap',
    }
})


def start():
    while True:
        variable = 0 
                    
        markets = bitget.load_markets()

        # exchange.verbose = True

        # fetching informations
        symbol = 'PEPE/USDT:USDT'
        balances = bitget.fetch_balance()
        order_book = bitget.fetch_order_book(symbol)

        ohlcv = bitget.fetch_ohlcv(symbol, timeframe='1m', limit=51)  

        df = pd.DataFrame(ohlcv, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])

        df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')

        closing_prices = df['close']

        ema_10 = closing_prices.ewm(span=10, adjust=False).mean()
        ema_20 = closing_prices.ewm(span=20, adjust=False).mean()
        ema_50 = closing_prices.ewm(span=50, adjust=False).mean()

        # print("Last 10 EMA:", ema_10.iloc[-1])
        # print("Last 20 EMA:", ema_20.iloc[-1])
        # print("Last 50 EMA:", ema_50.iloc[-1])

        pepe_ohlcv = bitget.fetch_ohlcv(
        symbol="PEPE/USDT:USDT", 
        timeframe='1m',
        since=None, 

        pepe_close = pepe_ohlcv[0][4] 
        # pprint.pprint(pepe_close)

        ema_10_last = float(ema_10.iloc[-1] * 10**10)
        ema_20_last = float(ema_20.iloc[-1] * 10**10)
        ema_50_last = float(ema_50.iloc[-1] * 10**10)
        pepe_close_last = float(pepe_close * 10**10)

        if ema_10_last > ema_20_last > ema_50_last and pepe_close_last < ema_10_last :

            def pepe_long():
                try:

                    bid_1 = order_book['bids'][0][0]
                    ask_1 = order_book['asks'][0][0]
                    market_price_1 = ((bid_1 + ask_1) / 2)
                    usdt_balance = balances['total']['USDT']  
                    desired_usdt_amount_1 = math.floor(usdt_balance/750)*20*3**(1-1) 
                    amount_1 = desired_usdt_amount_1 / market_price_1  

                    #placing an order
                    type_1 = 'market'
                    side_1 = 'open_long'
                    size_1 = amount_1

                    order_1 = bitget.create_order(symbol, type_1, side_1, size_1)

                    while True:
                        position_check_1 = bitget.fetch_position(symbol)
                        if position_check_1['info']['total'] is not None and position_check_1['info']['averageOpenPrice'] is not None:
                            order_size_1 = float(position_check_1['info']['total'])
                            order_price_1 = float(position_check_1['info']['averageOpenPrice'])
                            break
                        time.sleep(1)



                    # placing an order(TP/SL)
                    type_1_1 = 'market'
                    side_1_1 = 'close_long'
                    size_1_1 = order_size_1
                    price_1_1 = order_price_1
                    params_1_1 = {
                        'triggerPrice':  (math.floor(order_price_1 * 1.012 * 10**10) / 10**10), 
                    }

                    order_1_1 = bitget.create_order(symbol, type_1_1, side_1_1, size_1_1, price_1_1, params_1_1)

                    # placing an order(TP/SL)
                    type_1_2 = 'market'
                    side_1_2 = 'close_long'
                    size_1_2 = order_size_1
                    price_1_2 = order_price_1
                    params_1_2 = {
                        'triggerPrice':  (math.floor(order_price_1 * 0.99 * 10**10) / 10**10),
                    }

                    order_1_2 = bitget.create_order(symbol, type_1_2, side_1_2, size_1_2, price_1_2, params_1_2)

**Comment by sc0Vu** [comment]
Hi @PUVl 

The side should be either buy (long position) or sell (short position) based on the new documentation https://www.bitget.com/api-doc/contract/trade/Place-Order.
