### ISSUE TITLE
BIT-Z fetch balance interface

### ISSUE THREAD

**Issue by jed057** [ccxt/ccxt#2142]
- OS:
- Programming Language version:
- CCXT version:1.11.4
- Exchange: bit-z
- Method: fetch_balance()

bit-z does not claim a api to fetch user balance in official website, i guess that's why there's no fetch_balance implementation in bitz.py. However it does have a way (by private post 'balances'). Dont ask me how I know that, I just tried it out.

**Comment by kroitor** [comment]
@jed057 can you please help us debug it? We need to do the following:
1. update ccxt to version 1.11.28 (just added the "balances" endpoint)
2. run this code and copy the complete verbose output here (without your keys):

```
import ccxt
from pprint import pprint
exchange = ccxt.bitz({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'verbose': True,  # ←-- this line is needed
})
pprint(exchange.fetch_balance())
```

? 

I'm having difficulty with their confirmation emails not coming through to my address right now, can't really recreate the API key to test it. Your help would be really appreciated.

Thx in advance!

**Comment by jed057** [comment]
('\nRequest:', 'POST', 'https://www.bit-z.com/api_v1/balances', {'Content-type': 'application/x-www-form-urlencoded', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'python-requests/2.18.4'}, 'api_key=48e5e01ca50cc6ac722b6502d3cd938e&nonce=559120&timestamp=1520347559&sign=8231afab1bcbbb80a513d52ae3a0c7ad')
('\nResponse:', 'POST', 'https://www.bit-z.com/api_v1/balances', '200', "{'X-Powered-By': 'PHP/7.2.3', 'Transfer-Encoding': 'chunked', 'Server': 'nginx/1.10.2', 'Connection': 'keep-alive', 'Date': 'Tue, 06 Mar 2018 14:46:01 GMT', 'Content-Type': 'application/json;charset=utf-8'}", u'{"code":0,"msg":"Success","data":{"uid":"1431169","btc":"0.00000000","ltc":"0.00000000","mzc":"0.00000000","fct":"0.00000000","lsk":"0.00000000","hxi":"0.00000000","zec":"0.00000000","doge":"0.00000000","eth":"0.00000000","etc":"0.00000000","gxs":"0.00000000","xpm":"0.00000000","ppc":"0.00000000","blk":"0.00000000","xas":"0.00000000","hsr":"0.00000000","nuls":"0.00000000","voise":"0.00000000","pay":"0.00000000","eos":"0.00000000","omg":"0.00000000","ybct":"0.00000000","otn":"0.00000000","usdt":"0.00000000","btx":"0.00000000","qtum":"0.00000000","dash":"0.00000000","game":"0.00000000","bch":"0.00000000","gnt":"0.00000000","sss":"0.00000000","ark":"0.00000000","part":"0.00000000","leo":"0.00000000","dgb":"0.00000000","zsc":"0.00000000","viu":"0.00000000","btg":"0.00000000","arn":"0.00000000","vtc":"0.00000000","bcd":"0.00000000","trx":"0.00000000","etp":"0.00000000","hwc":"0.00000000","unit":"0.00000000","oxy":"0.00000000","mco":"0.00000000","sbtc":"0.00000000","bcx":"0.00000000","etf":"0.00000000","zgc":"0.00000000","pylnt":"0.00000000","xrb":"0.00000000","dkkt":"0.00000000","rebl":"0.00000000","aidoc":"0.00000000","ddn":"0.00000000","put":"0.00000000","pok":"0.00000000","atm":"0.00000000","sphtx":"0.00000000","nkc":"0.00000000","oc":"0.00000000","bnty":"0.00000000","ocn":"0.00000000","ink":"0.00000000","ekt":"0.00000000","btv":"0.00000000","sgcc":"0.00000000","egcc":"0.00000000","pxc":"0.00000000","woc":"0.00000000","qube":"0.00000000","ecom":"0.00000000"}}')
{u'code': 0,
 u'data': {u'aidoc': u'0.00000000',
           u'ark': u'0.00000000',
           u'arn': u'0.00000000',
           u'atm': u'0.00000000',
           u'bcd': u'0.00000000',
           u'bch': u'0.00000000',
           u'bcx': u'0.00000000',
           u'blk': u'0.00000000',
           u'bnty': u'0.00000000',
           u'btc': u'0.00000000',
           u'btg': u'0.00000000',
           u'btv': u'0.00000000',
           u'btx': u'0.00000000',
           u'dash': u'0.00000000',
           u'ddn': u'0.00000000',
           u'dgb': u'0.00000000',
           u'dkkt': u'0.00000000',
           u'doge': u'0.00000000',
           u'ecom': u'0.00000000',
           u'egcc': u'0.00000000',
           u'ekt': u'0.00000000',
           u'eos': u'0.00000000',
           u'etc': u'0.00000000',
           u'etf': u'0.00000000',
           u'eth': u'0.00000000',
           u'etp': u'0.00000000',
           u'fct': u'0.00000000',
           u'game': u'0.00000000',
           u'gnt': u'0.00000000',
           u'gxs': u'0.00000000',
           u'hsr': u'0.00000000',
           u'hwc': u'0.00000000',
           u'hxi': u'0.00000000',
           u'ink': u'0.00000000',
           u'leo': u'0.00000000',
           u'lsk': u'0.00000000',
           u'ltc': u'0.00000000',
           u'mco': u'0.00000000',
           u'mzc': u'0.00000000',
           u'nkc': u'0.00000000',
           u'nuls': u'0.00000000',
           u'oc': u'0.00000000',
           u'ocn': u'0.00000000',
           u'omg': u'0.00000000',
           u'otn': u'0.00000000',
           u'oxy': u'0.00000000',
           u'part': u'0.00000000',
           u'pay': u'0.00000000',
           u'pok': u'0.00000000',
           u'ppc': u'0.00000000',
           u'put': u'0.00000000',
           u'pxc': u'0.00000000',
           u'pylnt': u'0.00000000',
           u'qtum': u'0.00000000',
           u'qube': u'0.00000000',
           u'rebl': u'0.00000000',
           u'sbtc': u'0.00000000',
           u'sgcc': u'0.00000000',
           u'sphtx': u'0.00000000',
           u'sss': u'0.00000000',
           u'trx': u'0.00000000',
           u'uid': u'1431169',
           u'unit': u'0.00000000',
           u'usdt': u'0.00000000',
           u'viu': u'0.00000000',
           u'voise': u'0.00000000',
           u'vtc': u'0.00000000',
           u'woc': u'0.00000000',
           u'xas': u'0.00000000',
           u'xpm': u'0.00000000',
           u'xrb': u'0.00000000',
           u'ybct': u'0.00000000',
           u'zec': u'0.00000000',
           u'zgc': u'0.00000000',
           u'zsc': u'0.00000000'},
 u'msg': u'Success'}

**Comment by kroitor** [comment]
@jed057 the fetchBalance implementation for bitz was added in the most recent version of ccxt 1.11.34, thx to you so much!
