### ISSUE TITLE
Coinbase advanced trader - support for USD to USDC (create_convert_quote, commit_convert_quote)

### ISSUE THREAD

**Issue by jtashiro** [ccxt/ccxt#21431]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

Implemented these 3 methods in coinbase.py and verified working.

```
def create_convert_quote(self,  from_account: str, to_account: str, amount: str, user_incentive_id=None, code_val=None, tag=None, params={}):
def get_convert_trade(self,  trade_id: str, from_account: str, to_account: str,  params={}):
def commit_convert_trade(self,  trade_id: str, from_account: str, to_account: str,  params={}):
```

### Describe the solution you'd like

As a coinbase API user I want the ability to programatically convert USD to USDC.   While I can deposit in USD from my bank via API, I want the ability to convert that to USDC for coinbase API yield. 

### Describe alternatives you've considered

Implemented in coinbase.py the methods provided in coinbase API

**Comment by Dan-krm** [comment]
@jtashiro thanks for the recommendation, can you share the API endpoints that you used? We generally won't create new methods just for one exchange and we guide users to using the CCXT implicit API for using any endpoints that aren't relevant to a unified method: https://docs.ccxt.com/#/README?id=implicit-api

If there is endpoints in other exchange API's for converting between USD and a stable coin we can create some newly unified methods

**Comment by jtashiro** [comment]
These are the endpoints used, they are already documented in the ccxt/abstract/coinbase.py file, I just created methods to call them in coinbase.py

v3PrivatePostBrokerageConvertQuote
v3PrivateGetBrokerageConvertTradeTradeId
v3PrivatePostBrokerageConvertTradeTradeId

**Comment by jtashiro** [comment]
```

    def create_convert_quote(self,  from_account: str, to_account: str, amount: str, user_incentive_id=None, code_val=None, tag=None, params={}):
        """
        create_convert_quote  - convert from USD to USDC and vice versa`
        :see: https://docs.cloud.coinbase.com/advanced-trade-api/reference/retailbrokerageapi_createconvertquote
        :param from_account string required The currency of the account to convert from, e.g. USD
        :param to_account string required The currency of the account to convert to, e.g. USDC
        :param amount string required The amount to convert in the currency of the from_account
        :param user_incentive_id string
        :param code_val string
        :returns dict: a transaction structure
        """
        request = {
            "from_account": from_account,
            "to_account": to_account,
            "amount": amount,
            "trade_incentive_metadata": {
              "user_incentive_id": user_incentive_id,
              "code_val": code_val
            }
        }
        response = self.v3PrivatePostBrokerageConvertQuote(self.extend(request, params))
        data = self.safe_value(response, 'trade', {})
        return self.parse_trade(data)

    def get_convert_trade(self,  trade_id: str, from_account: str, to_account: str,  params={}):
        """
        create_convert_quote  - convert from USD to USDC and vice versa`
        :see: https://docs.cloud.coinbase.com/advanced-trade-api/reference/retailbrokerageapi_getconverttrade
        :param trade_id string required The trade_id from prior call to create_convert_quote
        :param from_account string required The currency of the account to convert from, e.g. USD
        :param to_account string required The currency of the account to convert to, e.g. USDC
        :returns dict: a transaction structure
        """
        request = {
            "trade_id": trade_id,
            "from_account": from_account,
            "to_account": to_account
        }   
        response = self.v3PrivateGetBrokerageConvertTradeTradeId(self.extend(request, params))
        data = self.safe_value(response, 'trade', {})
        return self.parse_trade(data)
            
    def commit_convert_trade(self,  trade_id: str, from_account: str, to_account: str,  params={}):
        """ 
        Commits the conversion create_convert_quote  - convert from USD to USDC and vice versa`
        :see: https://docs.cloud.coinbase.com/advanced-trade-api/reference/retailbrokerageapi_commitconverttrade
        :param trade_id string required The trade_id from prior call to create_convert_quote
        :param from_account string required The currency of the account to convert from, e.g. USD
        :param to_account string required The currency of the account to convert to, e.g. USDC
        :returns dict: a transaction structure
        """     
        request = {
            "trade_id": trade_id,
            "from_account": from_account,
            "to_account": to_account
        }       
        response = self.v3PrivatePostBrokerageConvertTradeTradeId(self.extend(request, params))
        print(response)
        data = self.safe_value(response, 'trade', {})
        return self.parse_trade(data)

```

**Comment by 2361020362** [comment]
Bien

**Comment by jtashiro** [comment]
What is needed to get these methods added formally into the next version of ccxt?  Each time I upgrade ccxt I need to append these into the coinbase.py file and would prefer not to do that ...

**Comment by Dan-krm** [comment]
Hi @jtashiro I would recommend just importing ccxt and adding those methods to your own file. To implement these methods we would need to check and see if we can support them on other exchanges as well then we could create some new unified methods.

**Comment by jtashiro** [comment]
I am thinking to factor these conversion quote methods into the create-order method for coinbase if the currency pair is usd/usdc or usdc/usd to call these internal coinbase specific methods. add a parameter to drive that logic.  that would make it backward compatible and not require new public methods in ccxt.thoughts?Sent from my iPhoneOn Mar 20, 2024, at 1:21 AM, Dan ***@***.***> wrote:﻿
Hi @jtashiro I would recommend just importing ccxt and adding those methods to your own file. To implement these methods we would need to check and see if we can support them on other exchanges as well then we could create some new unified methods.
