### ISSUE TITLE
binance如何获取合约账户余额

### ISSUE THREAD

**Issue by cxfshelter** [ccxt/ccxt#21430]
### Operating System

windows

### Programming Languages

Python

### Description

还有ccxt.binance和ccxt.binancecoinm两者区别是什么，文档也没说，fetch_balance返回的内容是不一样的，其中binance可以返回现货账户资金，但是合约的没有。

### Code

```
  

```

**Comment by carlosmiei** [comment]
@cxfshelter All issues must be written in english.
