### ISSUE TITLE
Please add stock and crypto to trade in alpaca 

### ISSUE THREAD

**Issue by vensilver** [ccxt/ccxt#21467]
### Exchange Name

alpaca.markets

### URL of the Exchange

https://alpaca.markets/

### URL of the Exchange's API docs

https://docs.alpaca.markets/docs/sdks-and-tools

### Why should this exchange be implemented?

can you  add this exchange to.

**Comment by carlosmiei** [comment]
Hello @vensilver,
We already support crypto trading on Alpaca.

**Comment by vensilver** [comment]
> lready support crypto trading on Alpaca.
what about  stocks

**Comment by carlosmiei** [comment]
@vensilver Stocks trading is not unified, but we support most endpoints through the implicit API, so you can probably use that.
