### ISSUE TITLE
Bitget - fetch_open_orders() doesn't work for SL/TP orders

### ISSUE THREAD

**Issue by adamzbier98** [ccxt/ccxt#21470]
### Operating System

Windows 11 Pro

### Programming Languages

Python

### CCXT Version

4.2.50

### Description

CCXT version: 4.2.50
Python version:  3.11

Hey guys, I'm trying to use fetch_open_orders() so I can track the status of my take profit and stop loss orders. Unfortunately it doesn't seem to work for stop loss and take profit orders, no matter what it try it simply returns an empty List. 

after hours of google searches and looking through the ccxt docs and manual, it seems that its either not possible to fetch SL/TP orders or I'm missing a parameter that is not commented in https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/bitget.py#L3233

Does anyone know a potential solution or at the very least whether its possible or not?

### Code

**How I'm attempting to fetch the sl/tp orders:**
import asyncio
import ccxt.async_support as ccxt_pro

exchange = cctx_pro.bitget({
    'apiKey': '   ',  
    'secret': '   ', 
    'password': '   ', 
    'options': {
            'defaultType': 'swap'
     }
})

orders = exchange.fetch_open_orders('BTC/USDT:USDT', params = {
    'stop': True, 
    'planType': 'normal_plan', 
    'isPlan': 'profit_loss'
})

print(orders)

**How I'm opening the position and sl/tp orders:**
                    order = await exchange.create_order(symbol, type = 'limit', side = side, amount = quantity, price = limit_price, params = {
                        'stopLoss': {
                            'triggerPrice': Functions.generate_target(limit_price, signal, sl_roe, leverage),
                            'triggerType': 'mark_price'
                        },
                        'takeProfit': {
                            'triggerPrice': Functions.generate_target(limit_price, signal, tp_roe, leverage),
                            'triggerType': 'mark_price'
                        },
                        'marginMode': 'isolated',
                        'oneWayMode': True
                    })

**Comment by carlosmiei** [comment]
Hello @adamzbier98,

If you place an order with a takeProfit/stopLoss attached, they won't be considered independent SL/TP orders (you can check that in the WEB UI), they will be considered part of the main order.

Due to that, you should fetch the main order and get the information about the attached tp/sl order there.


Example:
```
[
  {
    info: {
      symbol: 'ADAUSDT',
      size: '50',
      orderId: '1147494792649416708',
      clientOid: '1147494792678776845',
      baseVolume: '0',
      fee: '0',
      price: '0.2',
      priceAvg: '',
      status: 'live',
      side: 'buy',
      force: 'post_only',
      totalProfits: '0',
      posSide: 'long',
      marginCoin: 'USDT',
      quoteVolume: '0',
      leverage: '10',
      marginMode: 'crossed',
      enterPointSource: 'api',
      tradeSide: 'open',
      posMode: 'hedge_mode',
      orderType: 'limit',
      orderSource: 'normal',
      presetStopSurplusPrice: '5',
      presetStopLossPrice: '0.1',
      reduceOnly: 'NO',
      cTime: '1709309998673',
      uTime: '1709309998775'
    },
    id: '1147494792649416708',
    clientOrderId: '1147494792678776845',
    timestamp: 1709309998673,
    datetime: '2024-03-01T16:19:58.673Z',
    lastTradeTimestamp: 1709309998775,
    lastUpdateTimestamp: 1709309998775,
    symbol: 'ADA/USDT:USDT',
    type: 'limit',
    side: 'buy',
    price: 0.2,
    amount: 50,
    cost: 0,
    filled: 0,
    remaining: 50,
    timeInForce: 'PO',
    postOnly: true,
    reduceOnly: false,
    takeProfitPrice: 5, <---------- takeProfitPrice
    stopLossPrice: 0.1, <---------- stopLossPrice
    status: 'open',
    fee: { cost: 0, currency: 'USDT' },
    trades: [],
    fees: [ { cost: 0, currency: 'USDT' } ]
  }
]
```

![image](https://github.com/ccxt/ccxt/assets/43336371/6f70f823-27c7-4dfe-bb64-a51d1da6ac96)

**Comment by adamzbier98** [comment]
thank you. 

I assume that means that if I decide to simply create them separately using create_order() I would first have to track when the main limit order is filled before placing the separate stop and take profit? 

also would I have to for example track the tp order and then when its triggered I would have to manually cancel the sl order?

**Comment by adamzbier98** [comment]
I know how to create stop loss and take profit seperatly for phemex but according to the ccxt doc for bitget, create_order() 'type' param only takes 'market' and 'limit'.(Phemex has more types to define like 'stop', 'stop limit' etc)

**Comment by adamzbier98** [comment]
> Hello @adamzbier98,
> 
> If you place an order with a takeProfit/stopLoss attached, they won't be considered independent SL/TP orders (you can check that in the WEB UI), they will be considered part of the main order.
> 
> Due to that, you should fetch the main order and get the information about the attached tp/sl order there.
> 
> Example:
> 
> ```
> CCXT v4.2.56
> bitget.fetchOpenOrders (ADA/USDT:USDT)
> [
>   {
>     info: {
>       symbol: 'ADAUSDT',
>       size: '50',
>       orderId: '1147494792649416708',
>       clientOid: '1147494792678776845',
>       baseVolume: '0',
>       fee: '0',
>       price: '0.2',
>       priceAvg: '',
>       status: 'live',
>       side: 'buy',
>       force: 'post_only',
>       totalProfits: '0',
>       posSide: 'long',
>       marginCoin: 'USDT',
>       quoteVolume: '0',
>       leverage: '10',
>       marginMode: 'crossed',
>       enterPointSource: 'api',
>       tradeSide: 'open',
>       posMode: 'hedge_mode',
>       orderType: 'limit',
>       orderSource: 'normal',
>       presetStopSurplusPrice: '5',
>       presetStopLossPrice: '0.1',
>       reduceOnly: 'NO',
>       cTime: '1709309998673',
>       uTime: '1709309998775'
>     },
>     id: '1147494792649416708',
>     clientOrderId: '1147494792678776845',
>     timestamp: 1709309998673,
>     datetime: '2024-03-01T16:19:58.673Z',
>     lastTradeTimestamp: 1709309998775,
>     lastUpdateTimestamp: 1709309998775,
>     symbol: 'ADA/USDT:USDT',
>     type: 'limit',
>     side: 'buy',
>     price: 0.2,
>     amount: 50,
>     cost: 0,
>     filled: 0,
>     remaining: 50,
>     timeInForce: 'PO',
>     postOnly: true,
>     reduceOnly: false,
>     takeProfitPrice: 5, <---------- takeProfitPrice
>     stopLossPrice: 0.1, <---------- stopLossPrice
>     status: 'open',
>     fee: { cost: 0, currency: 'USDT' },
>     trades: [],
>     fees: [ { cost: 0, currency: 'USDT' } ]
>   }
> ]
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/43336371/309323638-6f70f823-27c7-4dfe-bb64-a51d1da6ac96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMTE5MTIsIm5iZiI6MTcwOTMxMTYxMiwicGF0aCI6Ii80MzMzNjM3MS8zMDkzMjM2MzgtNmY3MGY4MjMtMjdjNy00ZGZlLWJiNjQtYTUxZDFkYTZhYzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDE2NDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMmRhZTAxYWM1YjA5ZTU2YTE2YWE4YmM5ZTI1ZGVhYzEwYmViZmM4NDU1ZjcxYzc5MmRiMmMzMDI1MGFhNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ATJxUaDLPg9XAFw3KgALzVxketDzIL8N4BeVvbtwVvk)

Once the main limit order gets filled the 2 stop orders do appear in the TP/SL tab.

**Comment by adamzbier98** [comment]
> Hello @adamzbier98,
> 
> If you place an order with a takeProfit/stopLoss attached, they won't be considered independent SL/TP orders (you can check that in the WEB UI), they will be considered part of the main order.
> 
> Due to that, you should fetch the main order and get the information about the attached tp/sl order there.
> 
> Example:
> 
> ```
> CCXT v4.2.56
> bitget.fetchOpenOrders (ADA/USDT:USDT)
> [
>   {
>     info: {
>       symbol: 'ADAUSDT',
>       size: '50',
>       orderId: '1147494792649416708',
>       clientOid: '1147494792678776845',
>       baseVolume: '0',
>       fee: '0',
>       price: '0.2',
>       priceAvg: '',
>       status: 'live',
>       side: 'buy',
>       force: 'post_only',
>       totalProfits: '0',
>       posSide: 'long',
>       marginCoin: 'USDT',
>       quoteVolume: '0',
>       leverage: '10',
>       marginMode: 'crossed',
>       enterPointSource: 'api',
>       tradeSide: 'open',
>       posMode: 'hedge_mode',
>       orderType: 'limit',
>       orderSource: 'normal',
>       presetStopSurplusPrice: '5',
>       presetStopLossPrice: '0.1',
>       reduceOnly: 'NO',
>       cTime: '1709309998673',
>       uTime: '1709309998775'
>     },
>     id: '1147494792649416708',
>     clientOrderId: '1147494792678776845',
>     timestamp: 1709309998673,
>     datetime: '2024-03-01T16:19:58.673Z',
>     lastTradeTimestamp: 1709309998775,
>     lastUpdateTimestamp: 1709309998775,
>     symbol: 'ADA/USDT:USDT',
>     type: 'limit',
>     side: 'buy',
>     price: 0.2,
>     amount: 50,
>     cost: 0,
>     filled: 0,
>     remaining: 50,
>     timeInForce: 'PO',
>     postOnly: true,
>     reduceOnly: false,
>     takeProfitPrice: 5, <---------- takeProfitPrice
>     stopLossPrice: 0.1, <---------- stopLossPrice
>     status: 'open',
>     fee: { cost: 0, currency: 'USDT' },
>     trades: [],
>     fees: [ { cost: 0, currency: 'USDT' } ]
>   }
> ]
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/43336371/309323638-6f70f823-27c7-4dfe-bb64-a51d1da6ac96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMTIyMDAsIm5iZiI6MTcwOTMxMTkwMCwicGF0aCI6Ii80MzMzNjM3MS8zMDkzMjM2MzgtNmY3MGY4MjMtMjdjNy00ZGZlLWJiNjQtYTUxZDFkYTZhYzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDE2NTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2Y2Y2Y2ExOGFlOTlkYjcxN2VjMDFhNjkzNTg0MzNhZDZiYjZiYzU5OWZiNGJiZTEwMDQ4NWZjZmM0YTgzYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dhkQDJXtn9qvnbgktRldMLY7KW0s80d3uBjQ-eGUrmU)

Once the main limit order gets filled the 2 stop orders do appear in the TP/SL tab. I made sure to call fetch_open_orders() atleast a minute after the main order gets filled and the 2 stop orders are visible as 2 seperate orders under the tp/sl tab.

**Comment by adamzbier98** [comment]
> @adamzbier98 Let me try to reproduce that scenario then

thank you man, really appreciate the help 

![image](https://github.com/ccxt/ccxt/assets/161854235/2d2a8c2d-d885-4675-8666-64292c9b729c)

**Comment by carlosmiei** [comment]
@adamzbier98 Please do this:

```
open_sl_tp = await exchange.fetch_open_orders(symbol, params = {'trigger': True, 'planType': 'profit_loss')
```

![image](https://github.com/ccxt/ccxt/assets/43336371/edcd7795-f106-4835-b43c-bb532c082ab7)


Nonetheless, I will update the implementation to detect that `planType` was provided and therefore providing `trigger` is not necessary.
