### ISSUE TITLE
Bitget fetchOHLCV 1d "until" doesn't work in new version

### ISSUE THREAD

**Issue by x1i4b1x2** [ccxt/ccxt#21488]
### Description

After updating from 4.2.31 to 4.2.40, "until" doesn't work in Bitget fetchOHLCV for 1d

More info here: https://github.com/ccxt/ccxt/issues/21189

### Code

```
  

```

**Comment by ttodua** [comment]
please do not open multiple topics on same issue ( https://github.com/ccxt/ccxt/issues/21189 ), instead keep discussion there. I'll be handling this problem, but in the mentioned previous topic
