### ISSUE TITLE
parse_bid_ask need use double instead of float

### ISSUE THREAD

**Issue by dice2019** [ccxt/ccxt#2149]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by kroitor** [comment]
Hi! See this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code Thx!
