### ISSUE TITLE
C# FetchBalance for Gate raise error

### ISSUE THREAD

**Issue by nikky78** [ccxt/ccxt#21495]
### Operating System

Linux

### Programming Languages

JavaScript

### CCXT Version

4.2.51

_No response_

### Description

I am trying to fetch the balance in C# for Gate exchange like this:
`Balances balances = await exchange.FetchBalance();`

I am getting the error:
`Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]'.`

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @nikky78, thanks for reporting it, will take a look asap

**Comment by carlosmiei** [comment]
@nikky78 Can you please update your ccxt version and try again? It should be fixed by now

**Comment by nikky78** [comment]
It works indeed ! Thanks !
