### ISSUE TITLE
bybit fetchClosedOrder cannot find only by 'id', different with SPEC

### ISSUE THREAD

**Issue by freeman921** [ccxt/ccxt#21494]
### Operating System

Windows 11

### Programming Languages

Python

### CCXT Version

4.2.45

### Description

API fetchClosedOrder(id) should able to retrieve the order only with 'id'.
But in fact currently we need to specify 'symbol' in order to find the target order.

As mentioned in your code  (https://github.com/ccxt/ccxt/blob/master/python/ccxt/bybit.py)
Only 'id' is the required parameter for fetchClosedOrder(). 

### Code

This does not work (while it's expected to work):
```python
client.fetchClosedOrder(id='xxx')
```

while this works:
```python
client.fetchClosedOrder(id='xxx', symbol='DOGE/USDT')
```

**Comment by carlosmiei** [comment]
Hello @freeman921 thanks for bringing out attention to this, we will take a look!

**Comment by carlosmiei** [comment]
@freeman921 Actually at the moment `symbol` is not required as you can see in the log attached, the thing is if you want to fetch a spot order then you have to provide `type = 'spot'` in `params` because by default it will default to the linear swap branch.

Example:

```Python
order = await ex.fetch_closed_order(id, params = {'type':'spot'})`
```

DEMO

```
 p bybit fetchClosedOrder '1632908760312015104'  None '{"type":"spot"}' --sandbox
Python v3.11.7
CCXT v4.2.57
bybit.fetchClosedOrder(1632908760312015104,None,{'type': 'spot'})
{'amount': 1.0,
 'average': None,
 'clientOrderId': '1632908760312015105',
 'cost': 0.0,
 'datetime': '2024-03-02T15:38:13.218Z',
 'fee': {'cost': '0', 'currency': 'USDT'},
 'fees': [{'cost': 0.0, 'currency': 'USDT'}],
 'filled': 0.0,
 'id': '1632908760312015104',
 'info': {'avgPrice': '',
          'blockTradeId': '',
          'cancelType': 'UNKNOWN',
          'closeOnTrigger': False,
          'createdTime': '1709393893218',
          'cumExecFee': '0',
          'cumExecQty': '0.00000',
          'cumExecValue': '0.0000000',
          'isLeverage': '0',
          'lastPriceOnCreated': '',
          'leavesQty': '0',
          'leavesValue': '0',
          'marketUnit': 'quoteCoin',
          'nextPageCursor': '1632908760312015104%3A1709393893218%2C1632908760312015104%3A1709393893218',
          'orderId': '1632908760312015104',
          'orderIv': '',
          'orderLinkId': '1632908760312015105',
          'orderStatus': 'Cancelled',
          'orderType': 'Market',
          'placeType': '',
          'positionIdx': '0',
          'price': '0',
          'qty': '1.0000000',
          'reduceOnly': False,
          'rejectReason': 'EC_ReachRiskPriceLimit',
          'side': 'Buy',
          'slLimitPrice': '0',
          'slTriggerBy': '',
          'smpGroup': '0',
          'smpOrderId': '',
          'smpType': 'None',
          'stopLoss': '0',
          'stopOrderType': '',
          'symbol': 'LTCUSDT',
          'takeProfit': '0',
          'timeInForce': 'IOC',
          'tpLimitPrice': '0',
          'tpTriggerBy': '',
          'triggerBy': '',
          'triggerDirection': '0',
          'triggerPrice': '0.000',
          'updatedTime': '1709393893222'},
 'lastTradeTimestamp': 1709393893222,
 'lastUpdateTimestamp': 1709393893222,
 'postOnly': False,
 'price': None,
 'reduceOnly': False,
 'remaining': 0.0,
 'side': 'buy',
 'status': 'canceled',
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': 'LTC/USDT',
 'takeProfitPrice': None,
 'timeInForce': 'IOC',
 'timestamp': 1709393893218,
 'trades': [],
 'triggerPrice': None,
 'type': 'market'}
```

**Comment by freeman921** [comment]
> @freeman921 Actually at the moment `symbol` is not required as you can see in the log attached, the thing is if you want to fetch a spot order then you have to provide `type = 'spot'` in `params` because by default it will default to the linear swap branch.

Hi @carlosmiei, yeah that's true.
But when we are checking on how to call this API and we check the definition of this function (python/ccxt/bybit.py)
`def fetch_closed_order(self, id: str, symbol: Str = None, params={}):`
I think it's hard to know that we must give **type**, while **type** is only a optional sub parameter of **params**

**Comment by carlosmiei** [comment]
Hello @freeman921, I understand but ccxt unifies 100+ so our signatures can't be specific to a single exchange. Nonetheless, we highlight these quirks in our docs, so I would suggest taking a look: https://docs.ccxt.com/#/
