### ISSUE TITLE
phemex fetchClosedOrders missing order id

### ISSUE THREAD

**Issue by untoreh** [ccxt/ccxt#21504]
### CCXT Version

4.2.54

### Description

Calling `fetchClosedOrders` without symbols doesn't fill the order id in the returned structure

### Code

```
resp = exc.fetchClosedOrders(None)
resp[0]["id"] # None
resp[0]["info"]["orderId"] # Ok

resp = exc.fetchClosedOrders("BTC/USDT:USDT")
resp[0]["id"] # Ok

```

**Comment by carlosmiei** [comment]
Hello @untoreh, thanks for letting us know, I will take a look asap.
