### ISSUE TITLE
New Exchange: TradeOgre

### ISSUE THREAD

**Issue by amtf** [ccxt/ccxt#2150]
### Exchange Name

TradeOgre

### URL of the Exchange

https://tradeogre.com/

### URL of the Exchange's API docs

https://tradeogre.com/help/api

### Why should this exchange be implemented?

This exchange usually contains low-cap coins and newly introduced Proof-of-Work coins. It would be great for the Proof-of-Work community.

**Comment by pollodigomma** [comment]
Hi all, yesterday I wrote this wrapper for node.js https://github.com/pollodigomma/tradeogre-api use it if you need it!

**Comment by kroitor** [comment]
@pollodigomma hi! Thanks! Will get to it soon! )

**Comment by Seigneur774** [comment]
Hello, here is a link to a TadreOgre python wrapper: https://github.com/Endogen/TradeOgrePy

**Comment by PuNkYsHuNgRy** [comment]
Any word on if TradeOgre will be added?

**Comment by bodcat** [comment]
Is there any line of sight to TradeOgre support? How can I contribute toward this?

**Comment by kroitor** [comment]
@bodcat 

> Is there any line of sight to TradeOgre support?

We hope to add it as soon as we can, hopefully, before the end of this year.

- https://github.com/ccxt/ccxt/wiki/FAQ#when-will-you-add-the-support-for-an-exchange-requested-in-the-issues

> How can I contribute toward this?

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code ;)

**Comment by afterconnery** [comment]
Any idea if this exchange is going to be added?

**Comment by kroitor** [comment]
@afterconnery https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar

**Comment by frosty00** [comment]
not enough volume

**Comment by ttodua** [comment]
implemented
