### ISSUE TITLE
BTC Markets create_order function corner case handling

### ISSUE THREAD

**Issue by scoshil** [ccxt/ccxt#2151]
in the btcmarkets.py create_order function there is:

order['price'] = int(price * multiplier)

However due to python's non-exact ints + BTCM's handling of prices/volumes (using a multiplier) this results in certain order prices being invalid

For example, inserting a buy order with a price of 1.12 is fine, but inserting a buy of 1.13 gives an "invalid amount" error. I dug into this and it appears to be due to the way python handles ints. See below code.

```
multiplier = 100000000
price1 = 1.12
price2 = 1.13
a = int(price1*multiplier)
b = int(price2*multiplier)
print(a,b)
```

As a result I would suggest making a change to the create_order function:
```
        temp_price = int(price * multiplier)
        if str(temp_price)[-1:]=='9':
            temp_price +=1
        elif str(temp_price)[-1:]=='1':
            temp_price -=1
        print(temp_price)
        order['price'] = temp_price
```
I believe the volume parameter would suffer from the same issue, but because it does not happen for all numbers I haven't personally seen this issue for volume yet.

**Comment by kroitor** [comment]
Hi!

Thanks for the suggestion!

Your question is covered here:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support ← this doc explains why we can't really use python-specific code
- https://github.com/ccxt/ccxt/pull/2121 ←  this pull request addresses the above issue and it will be merged soon... having it merged will solve this particular issue for all languages and exchanges

Let us know if it does not answer to your issue. Closing it for now, if you don't mind. I'd suggest to move the discussion to #2121, feel free to ask if you have any further questions. Thx!

**Comment by scoshil** [comment]
@kroitor thanks for the quick reply! 
Any idea how long until it's merged?

**Comment by kroitor** [comment]
@scoshil a couple of days, I think...
