### ISSUE TITLE
wrong position parsing with watchPositions

### ISSUE THREAD

**Issue by untoreh** [ccxt/ccxt#21526]
### Description

https://github.com/ccxt/ccxt/blob/139e8ae040820a16a8f2e776c45c427fad4b702c/ts/src/pro/binance.ts#L2622

There are at least 2 issues here:
- `side` is set to `positionSide` which the endpoint returns _both_ when position is one way, not long or short
- `contracts` is set from the `pa` field. This field is negative for short positions but in ccxt the value should be always >= 0  afaik

so the sign of the `contracts` value should be fixed and use the sign to infer the position side

**Comment by sc0Vu** [comment]
Hi @untoreh

I think negative contracts is an issue, will fix that asap. For the position side, I found the message would be zero when liquidate the position. In that condition, we need to loop the positions cache.....
