### ISSUE TITLE
Binance perp futures - what is the symbol?

### ISSUE THREAD

**Issue by mmehrle** [ccxt/ccxt#21538]
### Operating System

Mac

### Programming Languages

Python

### CCXT Version

4.0.3

### Description

Apologies for dropping this here but I spent an hour googling and could not find this info. Back in the day with FTX the perp futures symbol for e.g. AVAX/USDT was AVAX-PERP. I am having an impossible time finding out the proper designation for perp futures in CCXT for binance, kraken, bitget, etc.. Is it different for each exchange or do we have a generic way of referring it?

FYI - I'm simply trying to compare 15-min spot with their equivalent perp futures contract prices.

Thanks in advance and again apologies for dropping this question here.

### Code

```
  

```

**Comment by pcriadoperez** [comment]
Hi,

All exchanges support ccxt unified symbols. so the linear perpetual for example for AVAX on all exchanges is `AVAX/USDT:USDT`

Ccxt also supports using the naming of each individual exchange, which you can find by calling `exchange.fetchMarkets()`
However if you wish to compare the same market across different exchanges I would recommend using the ccxt unified symbol so you don't have to worry about how each exchange names it.

(You can find more here https://docs.ccxt.com/#/README?id=symbols-and-market-ids)

I'll close the issue for now but feel free to reach out with any more questions
