### ISSUE TITLE
Yobit Errors

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#21531]
### Programming Languages

JavaScript

### CCXT Version

4.2.59

Issue in 4.2.59:
when I try to `fetchBalance`: 
`ExchangeError yobit {"success":1,"return":{"rights":{"info":1,"trade":1,"deposit":1,"withdraw":1},"funds":{"btc":0.00000002,"eth":0,"doge":0,"ethw":0,"frog":0,"dice":0,"zec":0},"funds_incl_orders":{"btc":0.00111278,"eth":0,"doge":0,"ethw":0,"frog":0,"dice":0,"zec":0},"transaction_count":0,"open_orders":0,"server_time":1709654078}}`

when I try to `fetchOpenOrders`:
`ExchangeError yobit {"success":1,"return":{"1007664079458151":{"pair":"zec_btc","type":"buy","amount":2.33622938,"rate":0.00047536,"timestamp_created":"1709653886","status":0}}}`

So I see that Yobit gives correct info but ccxt things it is error. It works normal at ccxt 4.1.95

**Comment by carlosmiei** [comment]
@ndubel It should be fixed now, please update your ccxt version and let us know if anything!

**Comment by ndubel** [comment]
@carlosmiei thank you, works
