### ISSUE TITLE
CCXT pro Bitget

### ISSUE THREAD

**Issue by AvVictoro** [ccxt/ccxt#21542]
### Programming Languages

Python

### Description

How can I send orders to Bitget using ccxt pro(or websocket)?

### Code

```
  

```

**Comment by pcriadoperez** [comment]
Unfortunately Bitget's API does not allow to createOrders through websockets.

Feel free to reach out with any other questions

**Comment by iockx** [comment]
> Unfortunately Bitget's API does not allow to createOrders through websockets.
> 
> Feel free to reach out with any other questions

The document shows that Bitget supports ws connections, but I haven't finished writing the code yet
https://docs.ccxt.com/#/ccxt.pro.manual?id=exchanges
