### ISSUE TITLE
Feature Request: Implement market order for HuobiPro

### ISSUE THREAD

**Issue by atjason** [ccxt/ccxt#2156]
Hi,
As [HuobiPro API Document](https://github.com/huobiapi/API_Docs/wiki/REST_api_reference) shows, it supports market order, which type is `buy-market` and `sell-market`.

I test and find current ccxt doesn't support market order. Please consider to support it for HuobiPro, thanks in advance. Let me know if more information is needed.

BR,
Jason

**Comment by kroitor** [comment]
Hi!

> I test and find current ccxt doesn't support market order.
> Let me know if more information is needed.

Can you please post a minimal snippet of code to reproduce it and your verbose output as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

**Comment by atjason** [comment]
Hi @kroitor 
Thanks for your quick response.

As you can see the [source file of huobipro](https://github.com/ccxt/ccxt/blob/master/js/huobipro.js), there's no `createMarketOrder` in the `has` list, and there's no `createMarketOrder` function in the file.

![](https://user-images.githubusercontent.com/803199/37092322-66b19a28-2246-11e8-8b41-76bebab1b83e.jpg)

Do I still need to provide code snippet?

**Comment by kroitor** [comment]
> As you can see the source file of huobipro, there's no createMarketOrder in the has list, and there's no createMarketOrder function in the file.

As you can see from [this base source file](https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js), the `createMarketOrder` method is implemented in the base class and inherited from there, and the `has['createMarketOrder']` is `true` by default for the same reason.

**Comment by atjason** [comment]
Get it, I will provide code snippet.

**Comment by kroitor** [comment]
@atjason thx, standing by for more info from you ) Please, don't forget to supply your verbose output as well (remove your keys from it as we don't need them, of course).

**Comment by kroitor** [comment]
One of possible reasons (a blind guess): you're probably calling `createOrder` from ccxt with type = `buy-market` or `sell-market`, which is wrong. 

You have to follow the Manual precisely: https://github.com/ccxt/ccxt/wiki/Manual#placing-orders. You need to pay attention to each symbol literally, notice that ccxt does support two unified types of orders (`market` or `limit`) and two sides (`buy` or `sell`). So you need to supply `type = 'market', side = 'buy'` (or `type = 'market', side = 'sell'`, whatever you need)...

Don't know if it solves your particular issue, though, hard to tell without more details from you.

**Comment by atjason** [comment]
@kroitor Sorry, but after I upgrade ccxt to latest version, huobipro could create market order.

Sorry for disturbing you.
