### ISSUE TITLE
Cryptopia: fetchTrades sometimes returns empty json

### ISSUE THREAD

**Issue by Codewyvern** [ccxt/ccxt#2158]
- OS: Windows 7
- Programming Language version: Javascript
- CCXT version: Latest
- Exchange: Cryptopia
- Method: fetchTrades

Something leads me to believe the rateLimits are not set up correctly, even though I don't get any ddosprotection exceptions, I still sometimes get an empty json as a result.

Quick look into it, it could be because ccxt ratelimit is like this:  'rateLimit': 1500,
And the cryptopia forum says its 1000, https://www.cryptopia.co.nz/Forum/Thread/3296

**Comment by kroitor** [comment]
> And the cryptopia forum says its 1000,

1500 is a much more graceful delay, with 1000 it would hit the rate limit even faster... So you're actually saying to make it worse )) I don't really think you want that )

This is not a rate-limit issue, though, from my experience they will throw a null response at you whatever rate limit you choose. So, to me it seems more like a bug of the exchange and their caching midlayer, these bugs are common among exchanges.

You can try various values yourself, by just setting it in your constructor options:

```JavaScript
const exchange = new ccxt.cryptopia ({rateLimit: 1000}) // or whatever you like...
```

Try running a loop with various rateLimits and see if it makes any difference. To me it doesn't.

Let us know if it does not answer your question. Thx!
