### ISSUE TITLE
Unexpected identifier 'params' in Exchange.js - TypeScript..

### ISSUE THREAD

**Issue by morzyns** [ccxt/ccxt#2159]
Hello everyone,
Just found an error in
**ccxt/js/base/Exchange.js:353:26: JS ERROR SyntaxError: Unexpected identifier 'params'. Expected ';' after variable declaration.**

- OS: macOs Sierra
- Programming Language version: Typescript 2.7.2
- CCXT version: ^1.11.41
- Exchange: binance
- Method:
this.binance = new ccxt.binance();
console.log(this.binance);

**Comment by morzyns** [comment]
It came out the issue is related with NativeScript iOS implementation that doesn't support async|await yet.

**Comment by kroitor** [comment]
@morzyns thx for reporting back!
