### ISSUE TITLE
Coinbase 401 Unauthorized with calling fetch_balance() using the example PHP program...

### ISSUE THREAD

**Issue by pottertech** [ccxt/ccxt#21596]
### Operating System

Ubuntu 20.04.6 LTS

### CCXT Version

4.2.64

### Description

I got the 401 unauthorized error when using fetch_balance() function.  To verify I used the coinbase-fetch-all-balances.php in the ccxt/examples/php directory.  I added my API key and ran the program.  It returned with the 401 unauthorized error again.

Here is the stack trace:

PHP Fatal error:  Uncaught ccxt\AuthenticationError: coinbase coinbase https://api.coinbase.com/v2/accounts?limit=100 GET 401 Unauthorized in /root/ccxt/php/Exchange.php:2103
Stack trace:
#0 /root/ccxt/php/Exchange.php(1572): ccxt\Exchange->handle_http_status_code()
#1 /root/ccxt/php/Exchange.php(4397): ccxt\Exchange->fetch()
#2 /root/ccxt/php/Exchange.php(4401): ccxt\Exchange->fetch2()
#3 /root/ccxt/php/abstract/coinbase.php(281): ccxt\Exchange->request()
#4 /root/ccxt/php/coinbase.php(1782): ccxt\abstract\coinbase->v2PrivateGetAccounts()
#5 /root/ccxt/examples/php/coinbase-fetch-all-balances.php(23): ccxt\coinbase->fetch_balance()
#6 {main}
  thrown in /root/ccxt/php/Exchange.php on line 2103
root@ubuntu-1cpu-1gb-de-fra1:~/ccxt/examples/php# vi fetch_balance.log
root@ubuntu-1cpu-1gb-de-fra1:~/ccxt/examples/php# ls *.log
fetch_balance.log
root@ubuntu-1cpu-1gb-de-fra1:~/ccxt/examples/php# rm *.log
root@ubuntu-1cpu-1gb-de-fra1:~/ccxt/examples/php# vi coinbase-fetch-all-balances.php
root@ubuntu-1cpu-1gb-de-fra1:~/ccxt/examples/php# php coinbase-fetch-all-balances.php > fetch_balance.log
PHP Fatal error:  Uncaught ccxt\AuthenticationError: coinbase coinbase https://api.coinbase.com/v2/accounts?limit=100 GET 401 Unauthorized in /root/ccxt/php/Exchange.php:2103
Stack trace:
#0 /root/ccxt/php/Exchange.php(1572): ccxt\Exchange->handle_http_status_code()
#1 /root/ccxt/php/Exchange.php(4397): ccxt\Exchange->fetch()
#2 /root/ccxt/php/Exchange.php(4401): ccxt\Exchange->fetch2()
#3 /root/ccxt/php/abstract/coinbase.php(281): ccxt\Exchange->request()
#4 /root/ccxt/php/coinbase.php(1782): ccxt\abstract\coinbase->v2PrivateGetAccounts()
#5 /root/ccxt/examples/php/coinbase-fetch-all-balances.php(23): ccxt\coinbase->fetch_balance()
#6 {main}
  thrown in /root/ccxt/php/Exchange.php on line 2103

### Code

```
<?php

$root = dirname(dirname(dirname(__FILE__)));

include $root . '/ccxt.php';

date_default_timezone_set('UTC');

$exchange = new \ccxt\coinbase(array(
    'apiKey' => 'xxxxxxxxxxxx',
    'secret' => 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
    'verbose' => true, // uncomment for debugging
));

$exchange->load_markets();

// $exchange->verbose = true; // uncomment for debugging

$result = array();
$params = array();
$loop = true;
do {
    $balance = $exchange->fetch_balance($params);
    $pagination = $exchange->safe_value($balance['info'], 'pagination');
    if ($pagination === null) {
        $loop = false;
    } else {
        $next_starting_after = $exchange->safe_string ($pagination, 'next_starting_after');
        if ($next_starting_after !== null) {
            $params['starting_after'] = $next_starting_after;
        } else {
            $loop = false;
        }
    }
    echo $exchange->iso8601($exchange->milliseconds()) . "\n";
    $result = $exchange->deep_extend($result, $balance);
} while ($loop);

echo "======================================================================\n";
var_dump($result);  

```

**Comment by pottertech** [comment]
The verbose log before the error happened:
[fetch_balance.log](https://github.com/ccxt/ccxt/files/14531211/fetch_balance.log)

**Comment by sc0Vu** [comment]
Hi @pottertech,

Thanks, we'll fix this asap.

**Comment by pottertech** [comment]
> Hi @pottertech,
> 
> Thanks, we'll fix this asap.

Let me know when this makes it into the main branch please.

**Comment by dakkusingh** [comment]
This still doesnt seem to work in the Python CCXT Version: 4.2.65

**Comment by dakkusingh** [comment]
btw: my api format is as outlined here https://github.com/ccxt/ccxt/issues/20827 and here https://github.com/ccxt/ccxt/issues/21226 

```
key_name = 'organizations/hidden/apiKeys/hidden'
key = """-----BEGIN EC PUBLIC KEY-----\nhidden\nhidden==\n-----END EC PUBLIC KEY-----"""
secret = """-----BEGIN EC PRIVATE KEY-----\nhidden\nhidden==\n-----END EC PRIVATE KEY-----"""
```

**Comment by MiladZarour** [comment]
isn't we need to have : 
api_key
api_secret
passphrase 
??

**Comment by carlosmiei** [comment]
Hello @MiladZarour if you're using cloud keys, then the `apiKey` should be the name like `organization/...` and the `secret` the private key in the pem format `-----BEGIN EC PRI....`
