### ISSUE TITLE
 calculate_fee() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by VeilleurTrytoFix** [ccxt/ccxt#21595]
### Operating System

ubuntu 20.04

### Programming Languages

Python

### CCXT Version

4.2.48

### Description

Example to reproduce : 

Traceback (most recent call last):
  File "/home/localuser/calculation.py", line 30, in <module>
    returned=ccxt.binance.calculate_fee(symbol=symbol, type=type, side=side,
TypeError: calculate_fee() missing 1 required positional argument: 'self'

### Code

```
 exchange = ccxt.binance({
    "apiKey": API_KEY,
    "secret": API_SECRET
})

exchange.load_markets()


#BUY BUY SELL
symbol = 'ETH/BTC'
type = 'limit'
side = 'buy'
amount=0.1
price=0.05704
total=float(amount*price)

returned=ccxt.binance.calculate_fee(symbol=symbol, type=type, side=side, amount=amount, price=price)
print(returned) 

```

**Comment by carlosmiei** [comment]
Hello @VeilleurTrytoFix,

You're calling it as a static method (ccxt.binance.calculate_fee) but it's not, you should do it instead

`exchange.calculate_fee(symbol=symbol, type=type, side=side, amount=amount, price=price)`

**Comment by carlosmiei** [comment]
Just tested and worked

```
Python v3.11.7
CCXT v4.2.64
binanceusdm.calculateFee(BTC/USDT:USDT,limit,buy,0.1,50)
{'cost': 4e-05, 'currency': 'USDT', 'rate': 0.0004, 'type': 'taker'}
```

**Comment by VeilleurTrytoFix** [comment]
it works thank guy !
