### ISSUE TITLE
has no attribute 'handleParamString'

### ISSUE THREAD

**Issue by zacra** [ccxt/ccxt#21597]
### Operating System

Amazon Linux

### CCXT Version

From ccxt version 4.2.59

### Description

Starting with ccxt version 4.2.59, the following error occurs. That lower version is fine.
Please give me feedback!!  

File "/home/ec2-user/.local/lib/python3.9/site-packages/ccxt/binance.py", line 3263, in fetch_balance
    subType, params = self.handle_sub_type_and_params('fetchBalance', None, params)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 3898, in handle_sub_type_and_params
    values = self.handle_option_and_params({}, methodName, 'subType', defaultValue)  # no need to re-test params here
  File "/home/ec2-user/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 3829, in handle_option_and_params
    methodName, params = self.handleParamString(params, 'callerMethodName', methodName)
AttributeError: 'binance' object has no attribute 'handleParamString'

### Code

```
  

```

**Comment by sc0Vu** [comment]
@zacra 

It works for me, any script we can reproduce the issue locally?

**Comment by zacra** [comment]
There is simple code as below.

Binance_AccessKey = ""
Binance_ScretKey = ""

binanceX = ccxt.binance(config={
     'apiKey': Binance_AccessKey,
     'secret': Binance_ScretKey,
     'enableRateLimit': True;
     'options': {
         'defaultType': 'future'
     }
})


balance = binanceX.fetch_balance(params={"type": "future"})

An error occurs in the latest versions 4.2.59 or higher, but works well in versions lower than that.

**Comment by sc0Vu** [comment]
@zacra works for me.

The function should be transformed to camel case automatically when initialize. Could you check whether this function is existed: `handle_param_string`?

**Comment by zacra** [comment]
The handle_option_and_params function of the latest version 4.2.59 or higher



    def handle_option_and_params(self, params: object, methodName: str, optionName: str, defaultValue=None):
        # This method can be used to obtain method specific properties, i.e: self.handle_option_and_params(params, 'fetchPosition', 'marginMode', 'isolated')
        defaultOptionName = 'default' + self.capitalize(optionName)  # we also need to check the 'defaultXyzWhatever'
        # check if params contain the key
        value = self.safe_value_2(params, optionName, defaultOptionName)
        if value is not None:
            params = self.omit(params, [optionName, defaultOptionName])
        else:
            # handle routed methods like "watchTrades > watchTradesForSymbols"(or "watchTicker > watchTickers")
            methodName, params = self.handleParamString(params, 'callerMethodName', methodName)
            # check if exchange has properties for self method
            exchangeWideMethodOptions = self.safe_value(self.options, methodName)
            if exchangeWideMethodOptions is not None:
                # check if the option is defined inside self method's props
                value = self.safe_value_2(exchangeWideMethodOptions, optionName, defaultOptionName)
            if value is None:
                # if it's still None, check if global exchange-wide option exists
                value = self.safe_value_2(self.options, optionName, defaultOptionName)
            # if it's still None, use the default value
            value = value if (value is not None) else defaultValue
        return [value, params]




There is a difference in the handle_option_and_params function in the previous version, and this seems to be the cause!


    def handle_option_and_params(self, params: object, methodName: str, optionName: str, defaultValue=None):
        # This method can be used to obtain method specific properties, i.e: self.handle_option_and_params(params, 'fetchPosition', 'marginMode', 'isolated')
        defaultOptionName = 'default' + self.capitalize(optionName)  # we also need to check the 'defaultXyzWhatever'
        # check if params contain the key
        value = self.safe_value_2(params, optionName, defaultOptionName)
        if value is not None:
            params = self.omit(params, [optionName, defaultOptionName])
        else:
            # check if exchange has properties for self method
            exchangeWideMethodOptions = self.safe_value(self.options, methodName)
            if exchangeWideMethodOptions is not None:
                # check if the option is defined inside self method's props
                value = self.safe_value_2(exchangeWideMethodOptions, optionName, defaultOptionName)
            if value is None:
                # if it's still None, check if global exchange-wide option exists
                value = self.safe_value_2(self.options, optionName, defaultOptionName)
            # if it's still None, use the default value
            value = value if (value is not None) else defaultValue
        return [value, params]

**Comment by zacra** [comment]
[ec2-user@ip-172-31-21-143 ~]$ python3 /var/autobot/Binance_BTC_DOM_Bot.py
min_cost:  100.0
min_amount:  0.001
min_price:  556.8
coin_price:  67058.2
--- Target_Coin_Ticker: BTC/USDT | minimun_amount :  0.002
revenue_rate_b  55.726287795292215
min_cost:  5.0
min_amount:  0.001
min_price:  10.0
coin_price:  2132.7
--- Target_Coin_Ticker: BTCDOM/USDT | minimun_amount :  0.003
min_n: 5


The above worked well
If you upgrade to 4.2.59 or higher, you will receive the following error:


[ec2-user@ip-172-31-21-143 ~]$ python3 /var/autobot/Binance_BTC_DOM_Bot.py
Traceback (most recent call last):
  File "/var/autobot/Binance_BTC_DOM_Bot.py", line 127, in <module>
    balance = binanceX.fetch_balance(params={"type": "future"})
  File "/home/ec2-user/.local/lib/python3.9/site-packages/ccxt/binance.py", line 3260, in fetch_balance
    subType, params = self.handle_sub_type_and_params('fetchBalance', None, params)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 3921, in handle_sub_type_and_params
    values = self.handle_option_and_params({}, methodName, 'subType', defaultValue)  # no need to re-test params here
  File "/home/ec2-user/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 3852, in handle_option_and_params
    methodName, params = self.handleParamString(params, 'callerMethodName', methodName)
AttributeError: 'binance' object has no attribute 'handleParamString'


![Uploading 스크린샷 2024-03-08 오후 12.07.07.png…]()

**Comment by sc0Vu** [comment]
@zacra 

The function `handle_param_string` should be in exchange.py.

**Comment by carlosmiei** [comment]
Hello @zacra, we will apply a fix asap, thanks for letting us know.
