### ISSUE TITLE
CoinEx Launches API V2. V1 is expected to be officially discontinued between Jul. to Sep. 2024 (UTC).

### ISSUE THREAD

**Issue by h76oeI6pMxU9g4p8aCpc6Q** [ccxt/ccxt#21615]
### Preliminary Checks

- [x] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

Announcement:
https://www.coinex.com/en/announcements/detail/24081321518612

CoinEx API V2 Docs:
https://docs.coinex.com/api/v2/

"CoinEx API V1 is expected to be officially discontinued between Jul. to Sep. 2024 (UTC). CoinEx recommends a swift transition to API version 2 as soon as possible."

All CoinEx API functions (V1) on CCXT may be broken after such date.

Please consider to update the CCXT source code to keep CoinEx API work.

### Describe the solution you'd like

The primary change is the authorization method (form MD5 to SHA256) and the signing message string structure.

I also checked the docs. The most of API endpoint, method, parameters of V2 is not same as V1.

It look like not a small API change.......need to start the work early to avoid the CoinEx API on CCXT broken after such date.

**Comment by carlosmiei** [comment]
Hello @h76oeI6pMxU9g4p8aCpc6Q, thanks for letting us know, we will work to add v2 as soon as possible.

**Comment by Dan-krm** [comment]
Hi @h76oeI6pMxU9g4p8aCpc6Q thanks for the information, I plan on updating coinex to v2 starting this week

**Comment by grozz97** [comment]
Hello @carlosmiei 
[CoinEx will discontinue API V1 service on September 25, 2024 (UTC+3)](https://announcement.coinex.com/hc/en-us/articles/28718290448404-CoinEx-Will-Discontinue-and-Retire-API-V1-Services-on-September-25-2024-UTC)

**Comment by carlosmiei** [comment]
Hello @grozz97, we're working on the update, thank you.

**Comment by Dan-krm** [comment]
The upgrade to v2 for both REST and Websocket API's is completed now
