### ISSUE TITLE
New Exchange: Coinbene

### ISSUE THREAD

**Issue by arielorvits** [ccxt/ccxt#2162]
BTW - great framework!!

http://www.coinbene.com/#/

great work! (sent 0.2 LTC fot tip :) )

10x!!

**Comment by jjhesk** [comment]
doc: https://github.com/Coinbene/API-Documents-CHN/wiki/0.0.0-Coinbene-API%E6%96%87%E6%A1%A3

**Comment by Cleric334** [comment]
Hello.

I was just wondering if this exchange is still in the plans to be implemented in ccxt?

Would really love to test it out.

**Comment by kroitor** [comment]
> I was just wondering if this exchange is still in the plans to be implemented in ccxt?

Yep. Will add it asap.

**Comment by neuro777** [comment]
Was coinbene ever added? I don’t see a configuration for it in latest ccxt.

**Comment by kroitor** [comment]
@neuro777 not yet, as long as this issue is open – it has not been added yet.

**Comment by neuro777** [comment]
Thanks! I appreciate the clarification. :)

**Comment by bread9** [comment]
any updates?

**Comment by blakelapierre** [comment]
demo js : https://github.com/Coinbene/API-Demo-Nodejs/blob/master/api.js

**Comment by ttodua** [comment]
@kroitor  beware of this exchange. Outright scam, fake volume and fake prices. no real support center, no withdrawals and deposits arrive, and much more. read reviews on other site too.

**Comment by kroitor** [comment]
@ttodua thx! We will read the reviews and will probably close this.

**Comment by ttodua** [comment]
> @ttodua thx! We will read the reviews and will probably close this.
Already a week they suspended everything now on exchange, all coins out there blocked indefinitely, no voices from anyone out there. thanks.

**Comment by ttodua** [comment]
They had had confirmed that already, that exchange was being closed, I've lately found that statement. Pinned message: https://t.me/CB_coinbene/115525 & https://coinbenevip.zendesk.com/hc/en-us/articles/4408776573593-Announcement-on-closing-service-and-settlement-process-of-CoinBene  
actually, in telegram, seems tons of people's wallets were seized and people couldnt withdraw. so, good you've closed this PR.

**Comment by kroitor** [comment]
@ttodua thanks for your feedback, appreciate it!
