### ISSUE TITLE
CCTX bybit fetchPositions only get maximum of 20 positions, how to get all positions which opened?

### ISSUE THREAD

**Issue by tidusho** [ccxt/ccxt#21625]
### Operating System

Window 11

### Programming Languages

JavaScript

### CCXT Version

CCXT Version: 4.2.48

### Description

Please guide me how to get all positions which were opened. By default, it just only shows 20 positions.

### Code

```
  async function cryptoTrade() {
    const currency = 'USDT';
    const balance = await exchange.fetchBalance(); // returns huge object with all balances
    const orders = await exchange.fetchPositions()
    });
    console.log(orders)

```

**Comment by carlosmiei** [comment]
Hello @tidusho, the easiest way is to provide `limit` in `params`, example,

```Python
positions = await bybit.fetch_positions(params = {'limit': 200})
```

**Comment by tidusho** [comment]
Thank you a lot @carlosmiei. I did it successfully. Howerver, info id of position was showed "undefined". I don't why?
const orders = await exchange.fetch_positions(undefined, undefined, params ={'limit': 200})
console.log(orders)
=====================
0:
{info: {…}, id: undefined, symbol: 'EOS/USDT:USDT', timestamp: 1709911972536, datetime: '2024-03-08T15:32:52.536Z', …}
collateral:
0
contracts:
194.5
contractSize:
1
datetime:
'2024-03-08T15:32:52.536Z'
entryPrice:
1.17
id:
undefined

**Comment by carlosmiei** [comment]
@tidusho Can you post here the information inside `info` ?

**Comment by tidusho** [comment]
![Screenshot 2024-03-08 230922](https://github.com/ccxt/ccxt/assets/85289302/a9449525-ff90-4bba-a97b-4e1d259c3461)

**Comment by carlosmiei** [comment]
@tidusho Please post it in text format and not a screenshot

**Comment by tidusho** [comment]
There is a part of array [0]:
collateral:
0
contracts:
194.5
contractSize:
1
datetime:
'2024-03-08T15:32:52.536Z'
entryPrice:
1.17
id:
undefined
info:
{symbol: 'EOSUSDT', leverage: '12', autoAddMargin: '0', avgPrice: '1.17', liqPrice: '', …}
adlRankIndicator:
'2'
autoAddMargin:
'0'
avgPrice:
'1.17'
bustPrice:
''
createdTime:
'1708708901192'
cumRealisedPnl:
'-1.76043258'
curRealisedPnl:
'-0.045513'
isReduceOnly:
false
leverage:
'12'
leverageSysUpdatedTime:
''
liqPrice:
''
markPrice:
'1.1861'
mmrSysUpdatedTime:
''
nextPageCursor:
'ARPAUSDT%2C1709884800031%2C0'
positionBalance:
'0'
positionIdx:
'0'
positionIM:
'19.07848297'
positionMM:
'4.66603145'
positionStatus:
'Normal'
positionValue:
'227.565'
riskId:
'26'
riskLimitValue:
'200000'
seq:
'28076947125'
sessionAvgPrice:
''
side:
'Buy'
size:
'194.5'
stopLoss:
'1.125'
symbol:
'EOSUSDT'
takeProfit:
'1.21'
tpslMode:
'Full'
tradeMode:
'0'
trailingStop:
'0'
unrealisedPnl:
'3.13145'
updatedTime:
'1709911972536'
=================
I can't get id to edit order positions that I need

**Comment by carlosmiei** [comment]
@tidusho Actually bybit does not provide an `id` for the position, even if it did that's not what you should use to the `edit` an `order`, you should always use the order `id` returned by `create_order/edit_order` to edit an order

**Comment by tidusho** [comment]
@carlosmiei Dear sir,
I use 'create_order' to create limit positions as below:

_params = {
                'stopLoss': entry*.97,
                'takeProfit': {
                    'type': 'limit',
                    'price': target3,
                    'triggerPrice': target2,
                },
            }_
const order = await exchange.createOrder(bybitSymbol, 'limit', 'buy', entry, price, params)

Until one position created successful, I use edit_order to add trailing_stop with trailingParams include triggerPrice

_const tralingParams = {
    'trailingPercent': 3.0,
    'trailingTriggerPrice': target,
    'reduceOnly': true,
}_

However I cannot get id to set edit_order, so plz guide me to solve this if fetch_positions of bybit doesn't return id (undefined)

**Comment by tidusho** [comment]
> Hello @tidusho, the easiest way is to provide `limit` in `params`, example,
> 
> ```python
> positions = await bybit.fetch_positions(params = {'limit': 200})
> ```

Hello @carlosmiei, 
Sorry, I've already checked this code again but it still show only 20 positions while I opened 25 positions. Is there other solution to fix it?
