### ISSUE TITLE
response body is right ,but return array is null with 0 length.

### ISSUE THREAD

**Issue by 731315163** [ccxt/ccxt#21637]
### Operating System

linux rocket

### Programming Languages

python3.10

### CCXT Version

4.2.65

### Description

**return response is right ,but return data array is 0 **
fetch Request: binance GET https://fapi.binance.com/fapi/v1/fundingRate?symbol=BTCUSDT&startTime=1709294400000 RequestHeaders: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: None

fetch Response: binance GET https://fapi.binance.com/fapi/v1/fundingRate?symbol=BTCUSDT&startTime=1709294400000 200 ResponseHeaders: {'Date': 'Sat, 09 Mar 2024 11:53:26 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'Tengine', 'vary': 'accept-encoding', 'Content-Encoding': 'gzip', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': '*,clienttype,Content-Type,lang,x-ui-request-trace,bnc-uuid', 'Content-Security-Policy': "default-src 'self'", 'cache-control': 'no-cache, no-store, must-revalidate', 'expires': '0', 'pragma': 'no-cache', 'strict-transport-security': 'max-age=31536000; includeSubdomains', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block'} ResponseBody: [{"symbol":"BTCUSDT","fundingTime":1709308800000,"fundingRate":"0.00046010","markPrice":"61335.40000000"},{"symbol":"BTCUSDT","fundingTime":1709337600000,"fundingRate":"0.00033426","markPrice":"62426.84994681"},{"symbol":"BTCUSDT","fundingTime":1709366400001,"fundingRate":"0.00057174","markPrice":"62071.90000000"},{"symbol":"BTCUSDT","fundingTime":1709395200000,"fundingRate":"0.00056396","markPrice":"61834.60000000"},{"symbol":"BTCUSDT","fundingTime":1709424000000,"fundingRate":"0.00046267","markPrice":"62039.90000000"},{"symbol":"BTCUSDT","fundingTime":1709452800000,"fundingRate":"0.00042989","markPrice":"61641.10000000"},{"symbol":"BTCUSDT","fundingTime":1709481600000,"fundingRate":"0.00044598","markPrice":"62210.70000000"},{"symbol":"BTCUSDT","fundingTime":1709510400000,"fundingRate":"0.00055071","markPrice":"63178.60000000"},{"symbol":"BTCUSDT","fundingTime":1709539200000,"fundingRate":"0.00046833","markPrice":"64120.50000000"},{"symbol":"BTCUSDT","fundingTime":1709568000000,"fundingRate":"0.00063620","markPrice":"66504.19310494"},{"symbol":"BTCUSDT","fundingTime":1709596800000,"fundingRate":"0.00048960","markPrice":"68296.40000000"},{"symbol":"BTCUSDT","fundingTime":1709625600000,"fundingRate":"0.00082969","markPrice":"66223.70000000"},{"symbol":"BTCUSDT","fundingTime":1709654400000,"fundingRate":"0.00088148","markPrice":"66840.70000000"},{"symbol":"BTCUSDT","fundingTime":1709683200000,"fundingRate":"0.00036280","markPrice":"63737.46570213"},{"symbol":"BTCUSDT","fundingTime":1709712000001,"fundingRate":"0.00033876","markPrice":"66733.45835461"},{"symbol":"BTCUSDT","fundingTime":1709740800000,"fundingRate":"0.00049354","markPrice":"66534.41841489"},{"symbol":"BTCUSDT","fundingTime":1709769600000,"fundingRate":"0.00030311","markPrice":"66118.62122727"},{"symbol":"BTCUSDT","fundingTime":1709798400000,"fundingRate":"0.00040984","markPrice":"66447.80000000"},{"symbol":"BTCUSDT","fundingTime":1709827200000,"fundingRate":"0.00054217","markPrice":"67317.10000000"},{"symbol":"BTCUSDT","fundingTime":1709856000000,"fundingRate":"0.00034819","markPrice":"66869.90000000"},{"symbol":"BTCUSDT","fundingTime":1709884800000,"fundingRate":"0.00043497","markPrice":"67302.03139394"},{"symbol":"BTCUSDT","fundingTime":1709913600000,"fundingRate":"0.00062913","markPrice":"67699.70000000"},{"symbol":"BTCUSDT","fundingTime":1709942400000,"fundingRate":"0.00019134","markPrice":"68174.99267730"},{"symbol":"BTCUSDT","fundingTime":1709971200001,"fundingRate":"0.00031281","markPrice":"68336.40000000"}]

### Code

```
  import json
from enum import Enum

import ccxt
import pandas as pd

from libdata import cdownload, timeutil
from libdata.timeutil import TimeUnit


def get_binance() -> ccxt.binance:
    exchange = ccxt.binance(
        {
            "apiKey": "UQOqOx1f0lcckVRwXfAwR4gmzUjV27xeZO4Ph9xu7dnw6vLaceEOlGWmoYNwULJx",
            "secret": "qFbb1BtYfnltVyA35sHxu7xMrOS0C1byDfPqG82lHj6fOgHgGnsiW1S5XEwdl7zM",
            "timeout": 60000,
            "enableRateLimit": True,
        }
    )
    return exchange


def downloadrate():

    time = timeutil.to_unix_timestamp(pd.Timestamp("2024-3-1 12:00:00"), TimeUnit.MS)
    e = get_binance()
    market = e.load_markets()
    e.verbose = True
    #
    # data is null ,there are questions!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    # data is null ,there are questions!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    # data is null ,there are questions!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    # data is null ,there are questions!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    # data is null ,there are questions!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    ##
    data = e.fetch_funding_rate_history("BTC/USDT", time)
    for v in data:
        print(v)



```

**Comment by carlosmiei** [comment]
Hello, @731315163,

First make sure you revoke your API keys immediately since you posted them.

Second, you're using the wrong symbol (that represents the spot market), can you try with `symbol = 'BTC/USDT:USDT')? 

Read more about it here: https://docs.ccxt.com/#/README?id=symbols-and-market-ids

**Comment by 731315163** [comment]
thank you!
