### ISSUE TITLE
Coinbase fetchMyTrades Unauthorized Error 401

### ISSUE THREAD

**Issue by fl0wo** [ccxt/ccxt#21640]
### Operating System

MacOS

### Programming Languages

JavaScript

### CCXT Version

4.2.53

### Description

Using `fetchMyTrades` method of Coinbase returns Unauthorized, even tho I'm sure API-keys are correct.

Other calls such as fetchBalance work perfectly, fetchMyTrades seems to return Unauthorized 401 always.

e.g.:
https://api.coinbase.com/api/v3/brokerage/orders/historical/fills?product_id=BTC-USDT&limit=100

Are we sure we are not including query parameters when generating signature?
https://docs.cloud.coinbase.com/advanced-trade-api/docs/auth#creating-a-signature

To my knowledge that's not the case, but I can't explain eitherway why getting this response.

### Code

```
  

```

**Comment by sc0Vu** [comment]
@fl0wo I think it's fixed. Can you upgrade ccxt and try again?

**Comment by dakkusingh** [comment]
This still doesnt seem to work in the Python CCXT Version: 4.2.65

**Comment by dakkusingh** [comment]
btw: my api format is as outlined here https://github.com/ccxt/ccxt/issues/20827 and here https://github.com/ccxt/ccxt/issues/21226 

```
key_name = 'organizations/hidden/apiKeys/hidden'
key = """-----BEGIN EC PUBLIC KEY-----\nhidden\nhidden==\n-----END EC PUBLIC KEY-----"""
secret = """-----BEGIN EC PRIVATE KEY-----\nhidden\nhidden==\n-----END EC PRIVATE KEY-----"""
```

**Comment by sc0Vu** [comment]
@dakkusingh what error did you see? It works for me, can you check the ccxt version or paste verbose log?

**Comment by fl0wo** [comment]
Thank you so much @sc0Vu seems to be fixed.

I'll do further tests and close this issue asap.

Thanks again for your work.

**Comment by CENQUIRON** [comment]
I'm trying to integrate the Coinbase Advanced Trade API into a Python-based automated trading bot using the ccxt library (version 4.4.82).

I'm connecting to ccxt.coinbaseadvanced and making a basic request to fetch my balance, like this:
exchange = ccxt.coinbaseadvanced({
    'apiKey': 'MY_API_KEY',
    'secret': 'MY_SECRET',
    'enableRateLimit': True
})
exchange.fetch_balance()
But I consistently receive the following error:
coinbaseadvanced GET https://api.coinbase.com/api/v3/brokerage/transaction_summary 401 Unauthorized
Here's what I've already checked:
The API key was generated from https://www.coinbase.com/settings/api.
Permissions for read and trade are enabled.
I'm using the API Key and Secret as provided (no PEM private keys).
Other exchanges (Binance, OKX, KuCoin, Kraken) are working fine in the same bot.
I'm using ccxt.coinbaseadvanced, not the deprecated ccxt.coinbase class.
Questions:
Is there an additional requirement to access /brokerage/ endpoints?
Does Coinbase Advanced Trade require extra headers, JWT tokens, or any custom auth process that ccxt might not be handling?
Is it possible that this endpoint isn't fully available for my account or region?
Any insights or guidance would be greatly appreciated. I'm trying to con
