### ISSUE TITLE
What is execute_and_run ? 

### ISSUE THREAD

**Issue by Ispolin08** [ccxt/ccxt#21644]
### Operating System

docker

### Programming Languages

PHP

### CCXT Version

4.2.60

### Description

Hi
I am trying to play with WS support based on you docs. Is there any idea what is this function ? 
Thanks!

### Code

```
if ($exchange->has['watchTicker']) {
    $exchange::execute_and_run(function() use ($exchange, $symbol, $params) {
        while (true) {
            try {
                $ticker = yield $exchange->watch_ticker($symbol, $params);
                echo date('c'), ' ', json_encode($ticker), "\n";
            } catch (Exception $e) {
                echo get_class($e), ' ', $e->getMessage(), "\n";
            }
        }
    });
}
  

```

**Comment by carlosmiei** [comment]
Hello @Ispolin08,
I think that was the legacy way of dealing with async functions, but that's outdated and is not used anymore. Please check some updated examples here: https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro/php

**Comment by Ispolin08** [comment]
Thanks. I saw it already and was not able to make it works (asked in another issues here) Thanks. This could be closed.

**Comment by arall** [comment]
> Hello @Ispolin08, I think that was the legacy way of dealing with async functions, but that's outdated and is not used anymore. Please check some updated examples here: https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro/php

FYI: The official docs are pointing to the legacy examples.
