### ISSUE TITLE
bigone api php Invalid request parameters

### ISSUE THREAD

**Issue by haitokt** [ccxt/ccxt#21645]
### Operating System

xampp, win10

### Programming Languages

PHP

### CCXT Version

4.2.65 (i've downloaded ccxt  today)

### Description

Hi;
I've made create_order in bigone  exchange but got error:

Fatal error: Uncaught ccxt\BadRequest: bigone {"code":10007,"message":"Invalid request parameters"} in C:\xampp\htdocs\main\ccxt10t3\php\Exchange.php:4881 Stack trace: #0 C:\xampp\htdocs\main\ccxt10t3\php\bigone.php(2192): ccxt\Exchange->throw_exactly_matched_exception(Array, '10007', 'bigone {"code":...') #1 C:\xampp\htdocs\main\ccxt10t3\php\Exchange.php(1570): ccxt\bigone->handle_errors(400, NULL, 'https://big.one...', 'POST', Array, '{"code":10007,"...', Array, Array, Array) #2 C:\xampp\htdocs\main\ccxt10t3\php\Exchange.php(4408): ccxt\Exchange->fetch('https://big.one...', 'POST', Array, Array) #3 C:\xampp\htdocs\main\ccxt10t3\php\Exchange.php(4412): ccxt\Exchange->fetch2('orders', 'private', 'POST', Array, NULL, NULL, Array) #4 C:\xampp\htdocs\main\ccxt10t3\php\abstract\bigone.php(182): ccxt\Exchange->request('orders', 'private', 'POST', Array, NULL, NULL, Array) #5 C:\xampp\htdocs\main\ccxt10t3\php\bigone.php(1517): ccxt\abstract\bigone->privatePostOrders(Array) #6 C:\xampp\htdocs\main\ccxt10t3\bigoneORDER.php(51): ccxt\bigone->create_order('ETH-USDT', 'LIMIT', 'buy', 0.0001, 50000.0, Array) #7 {main} thrown in C:\xampp\htdocs\main\ccxt10t3\php\Exchange.php on line 4881

How can i get this worked? thank for your support!

### Code

```
code to create new order:
include 'ccxt.php';
$poloniex   = new \ccxt\bigone   (array (
    'apiKey' => 'c11d3151xxx',
    'secret' => '7FB25E5BAA1E84553F36Dxxx',
));
$poloniex_markets = $poloniex->load_markets ();
$poloniex->create_order ('BTC-USDT', 'LIMIT', 'buy', 0.0001, 50000, array ('client_order_id' => '123'));  

```

**Comment by carlosmiei** [comment]
Hello @haitokt, we will take a look and revert asap.

**Comment by carlosmiei** [comment]
@haitokt Can you please update to the latest version and try again? Should be working now

**Comment by haitokt** [comment]
thank for your support, it works fine now
