### ISSUE TITLE
BITZ nonce issue

### ISSUE THREAD

**Issue by jed057** [ccxt/ccxt#2165]
- OS:
- Programming Language version: Python
- CCXT version: latest
- Exchange: BIT-Z
- Method: nonce()

In my application I need to periodically query balances and open orders in a relatively high frequency. Then I got an error with 'nonce must be a 6 dig string' or something after several minutes.. it is a 100% reproducible issue. 

When I doing some logging I found the generated nonce was an incremental 6 digits (each time) so I guess it will exceed 999999 finally.

I have tried to use the random lib to generate a random 6 digit string and test again it looks the issue never happen again. (there could be other solutions..)

**Comment by jed057** [comment]
not really sure, what i can provide is the response with the 203 code and msg content : u"Nonce must be a 6 bit string"

**Comment by mkutny** [comment]
Ok, as a temporary fix you may want to change the following line to seconds (or its equivalent in async version):
https://github.com/ccxt/ccxt/blob/ecf82f3fd9f225ebb7f3772c4ca45f4406a7d070/python/ccxt/bitz.py#L342

**Comment by wntsang4** [comment]
I got this error too. "Nonce must be a 6 bit string"

**Comment by kroitor** [comment]
6 bit is a range of 0-64, that is ridiculous for a nonce value )) I guess they really mean 6 digits... which is still a pretty restrictive upper limit... It might demand changing the key once in a quarter...

Anyway, @wntsang4 , @jed057 I'll look into it and will figure a way to make it work smoothly. Hold on, plz.
