### ISSUE TITLE
Does CCTX Bybit support trailing-stop?

### ISSUE THREAD

**Issue by tidusho** [ccxt/ccxt#21650]
### Operating System

Window 11

### Programming Languages

JavaScript

### CCXT Version

CCXT Version: 4.2.48

### Description

Dear, I use createOrder with type 'trailingStop' in bybit but doesn't work. Please help me!

### Code

const specParams = {
        'trailingPercent': 1, // percentage away from the current market price 1.0 is equal to 1%
        'reduceOnly': true,
    };
    const specOrder = await exchange.createOrder('BTCUSDT', 'trailingStop', 'sell', 1.0, undefined, specParams);

**Comment by carlosmiei** [comment]
hello @tidusho, what does not work exactly? Can you post a verbose log of the error?

**Comment by tidusho** [comment]
Hi, after using createOrder with SL/TP:
_const params = {
params = {
                'stopLoss': entry*.95,
                'takeProfit': {
                    'type': 'limit',
                    'price': target3,
                    'triggerPrice': target2,
                },}_
_const order = await exchange.createOrder('BTCUSDT', 'market, 'buy', entry, price, params);_

I used createOrder with trailingStop 
_const specParams = {
'trailingPercent': 1, // percentage away from the current market price 1.0 is equal to 1%
'reduceOnly': true,
};
const specOrder = await exchange.createOrder('BTCUSDT', 'market', 'sell', 1.0, undefined, specParams);

With 'type': 'market' as CCTX wiki guide, order is closed immediately without any trailing_stop trait. So, I try with 'type':'trailingStop' but getting error:
const specParams = {
_'trailingPercent': 1, // percentage away from the current market price 1.0 is equal to 1%
'reduceOnly': true,
};
const specOrder = await exchange.createOrder('BTCUSDT', 'trailingStop', 'sell', 1.0, undefined, specParams);_

Uncaught BadRequest BadRequest: bybit {"retCode":10001,"retMsg":"OrderType invalid","result":{},"retExtInfo":{},"time":1710086704089}

**Comment by tidusho** [comment]
@Dan-krm thank you so much, I did it successfully

**Comment by tidusho** [comment]
@Dan-krm
One more question: Is there any way to get all positions, I use this code but get only 20 positions while opened 25 positions:
_const positions = await exchange.fetchPositions(undefined, undefined, params ={'limit': 200})_

**Comment by tidusho** [comment]
@Dan-krm: Dear,
Is there other way to call close limit position?
Or else is there any way to take profit with 60% qty at triggerPrice. I wrote code below but don't know way to do it:
_const market = exchange.market(bybitSymbol)
            , { base, quote } = market
            , price = entry
            , params = {

                'stopLoss': stoploss1,
                'takeProfit': {
                    'type': 'limit',
                    'price': target3,
                    'triggerPrice': target2,
                },
            }
       
        const order = await exchange.createOrder(bybitSymbol, type, 'buy', amount*leverage/price, price, params);_

**Comment by Dan-krm** [comment]
@tidusho it depends on the exchange but stopLoss and takeProfit orders are usually for the entire position, but they sometimes might support an amount argument parameter inside the stopLoss or takeProfit object. Otherwise you can just create a a `stopLossPrice`, `takeProfitPrice` or `triggerPrice` order while setting the amount argument to 60% of the positions quantity:
https://docs.ccxt.com/#/README?id=trigger-orders
https://docs.ccxt.com/#/README?id=stop-loss-orders
https://docs.ccxt.com/#/README?id=take-profit-orders
