### ISSUE TITLE
Binance apiKey requires Credentials

### ISSUE THREAD

**Issue by Keczek2115** [ccxt/ccxt#21667]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

latest

### Description

i'm putting in the Keys already printed them out made sure they are correct and i cannot make a single trade stayed up for 2 hours trying to find a solution for this problem and was unable to

### Code

```
import ccxt
import time

# Settings
symbol = 'DOT/USDT'  # Asset symbol
short_ma_period = 50  # Short moving average period
long_ma_period = 200  # Long moving average period
amount = 10.00  # Amount to trade

exchange = ccxt.binanceusdm({
    'recvWindow=59999',  # Receive window
    'apiKey': '',  # Binance API key
    'secret': '',  # Binance API secret
    'enableRateLimit': True,  # Enable rate limiting
    'options': {
        'adjustForTimeDifference': True  # Adjust for time difference
    }
})

# Function calculating moving average
def calculate_ma(ohlcv, period):
    closes = [x[4] for x in ohlcv]  # Closing prices
    return sum(closes[-period:]) / period  # Calculate moving average

# Function executing trading strategy
def run_strategy(exchange, symbol, short_ma_period, long_ma_period, amount):
    while True:
        try:
            # Fetching historical data
            ohlcv = exchange.fetch_ohlcv(symbol, timeframe='15m', limit=long_ma_period)

            if len(ohlcv) >= long_ma_period:
                short_ma = calculate_ma(ohlcv, short_ma_period)
                long_ma = calculate_ma(ohlcv, long_ma_period)

                last_candle = ohlcv[-1][4]  # Last closing price

                if short_ma > long_ma:
                    # Buy condition
                    print("Buy condition met. Buying...")
                    order = exchange.create_market_buy_order(symbol, amount)

                    # Setting stop loss
                    if order['info']['status'] == 'FILLED':
                        stop_loss_price = last_candle * 0.95  # 5% stop loss
                        exchange.create_limit_sell_order(symbol, amount, stop_loss_price)
                else:
                    # Sell condition
                    print("Sell condition met. Selling...")
                    exchange.create_market_sell_order(symbol, amount)

                time.sleep(86400)  # Check once a day (1 day = 86400 seconds)
            else:
                print("Not enough data to calculate MA. Waiting...")
                time.sleep(3600)  # Wait an hour before retrying
        except Exception as e:
            print(f"An error occurred: {e}. Waiting a minute before retrying...")
            time.sleep(60)

# Running the strategy
run_strategy(exchange, symbol, short_ma_period, long_ma_period, amount)


```

**Comment by sc0Vu** [comment]
@Keczek2115 maybe the `recvWindow=59999` is wrong?

**Comment by Keczek2115** [comment]
> @Keczek2115 maybe the `recvWindow=59999` is wrong?

I used this line to make sure another problem does not occur which is the `binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}`

**Comment by kroitor** [comment]
> > @Keczek2115 maybe the `recvWindow=59999` is wrong?
> 
> I used this line to make sure another problem does not occur which is the `binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}`

@Keczek2115 the problem with the `Timestamp for this request was 1000ms ahead of the server's time.` error has been covered extensively in this duplicate issue here: #850 , please, read that issue carefully to solve for this problem. In short, you have to synchronize the clock on your system with a reliable time server frequently. 

The `recvWindow=59999` is wrong and should not be there.

When opening issues, please make sure there is no duplicates on the same topic:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

Closing this issue for now, feel free to reopen it if necessary.
