### ISSUE TITLE
Coinbase(Pro) ticker data

### ISSUE THREAD

**Issue by nyannako** [ccxt/ccxt#21664]
### Operating System

Linux

### Programming Languages

JavaScript

### CCXT Version

4.2.64

### Description

Is there a reason why only the "close" and "last" fields are populated from a call to fetchTickers() when using Coinbasepro? I think the "info" object which comes back from the exchange contails the low, high and open prices (in that order). 
Also would be really good to have the Bid and Ask prices as well (these are available through a call to watchTickers() so I am guessing that the exchange should have some way of providing them)

### Code

```
  const anExchange = new ccxt['coinbasepro']();
    const markets = await anExchange.loadMarkets();
    const usdMarkets = Object.values(markets).filter(market => market.quote == 'USD' && !market.swap && market.active);
    anExchange.usdSymbols = usdMarkets.map(m => m['symbol']);
    const allTickers = await anExchange.fetchTickers(anExchange.usdSymbols);
    console.log(allTickers['BTC/USD'].bid, allTickers['BTC/USD'].ask);

```

**Comment by sc0Vu** [comment]
@nyannako I can see last / close with fetchTickers, could you upgrade? We'll set bid or ask if it's in the response.

**Comment by nyannako** [comment]
Hi Peter, last/close has always been there. The response has open/low/high but I don't think it has bid and ask. Can you please let me know what the exact REST Api call is so I can ask Coinbase to add bid and ask?Thanks,Nick
-------- Original message --------From: Peter Lai ***@***.***> Date: 12/03/2024  07:35  (GMT+00:00) To: ccxt/ccxt ***@***.***> Cc: nyannako ***@***.***>, Mention ***@***.***> Subject: Re: [ccxt/ccxt] Coinbase(Pro) ticker data (Issue #21664) 
@nyannako I can see last / close with fetchTickers, could you upgrade? We'll set bid or ask if it's in the response.

**Comment by ttodua** [comment]
@nyannako 
`coinbasepro` exchange API was in process of deprecation. you can use `coinbase` class which uses new API engine.
if you still have some exceptional reason to use `coinbasepro` then note , `fetchTicker` (singular symbol) method does have bid/ask data from API: https://docs.cloud.coinbase.com/exchange/reference/exchangerestapi_getproductticker
but fetchTickers is not possible to be called for multiple symbols together to get that similar data, because ccxt's implemented fetchTickers in `coinbasepro` uses other endpoint (`products/spark-lines`) where there are not bid/ask data present.

this is maximum I could reply at this moment. 
Let me know if you have other notes.

**Comment by nyannako** [comment]
How can I use the "coinbase" class instead of the "coinbasepro" one when I have Coinbase accounts which require 3 keys (API Key, secret and passphrase)? 

Furthermore, I note that creating a new instance of the "coinbase" class and calling fetchTickers() on it, fails with error message "coinbase requires apiKey credential" which effectively means that I can't simply fetch market data from the exchange without keys?

**Comment by nyannako** [comment]
Simply put, the "coinbase" class doesn't work with any of the Coinbase accounts I currently have, only the "coinbasepro" class works

**Comment by ttodua** [comment]
yes, coinbase account needs apikeys (but not 3 keys, instead two, generated here: https://www.coinbase.com/settings/api ) , and it has `fetchBidsAsks` to be used to get bulk bid-ask for multiple symbols in one call. coinbasepro does not seem to have a way to get bids/asks in batch. that's all I can say.
