### ISSUE TITLE
BIT-Z trade password issue

### ISSUE THREAD

**Issue by jed057** [ccxt/ccxt#2167]
- OS:
- Programming Language version: Python
- CCXT version: latest
- Exchange: BIT-Z
- Method: create_order()

BITZ requires a trade password when trading. Accordingly, there's an member self.tradepwd in bitz.py, but no interface to set it.

**Comment by mkutny** [comment]
Did you try to read the Manual?

https://github.com/ccxt/ccxt/wiki/Manual#exchange-structure

**Comment by jed057** [comment]
you mean the password when create the exchange instance? but this is trade password, not login password i mean.. pls let me know if i missed anything.

**Comment by mkutny** [comment]
So look up in the source code how `self.tradepwd` is set.

**Comment by jed057** [comment]
ok, problem solved now.. sorry, pls help to close this one. :)

**Comment by mkutny** [comment]
I'm not a project owner so can't close... Don't you see a 'Close' button below the comment box?

**Comment by tognellap** [comment]
I have the same issue and i set the password together with the key and secret. Anyboody else has this issue.

**Comment by jed057** [comment]
@tognellap you have to ensure the name is exactly same as 'tradepwd'. refer to the code below:

self.api = ccxt.bitz({'apiKey': 'your api key','secret': 'your secret key','tradepwd': 'your trade password'})

**Comment by kroitor** [comment]
@tognellap it should be your trade password, not your general username password... Are you sure your API credentials are correct? Also, when you say *"I have the same issue"* we need you to provide a snippet of code and verbose output to reproduce the issue, or at least, you should point out which particular issue you mean, because this isn't all that clear as it may seem at first... https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Unfortunately, you're not saying any details, not even your programming language, so, I guess, this should do the job:

```Python
exchange = ccxt.bitx ({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'password': 'YOUR_TRADING_PASSWORD,
})

# your calls here...
```

**Comment by tognellap** [comment]
@kroitor You are right i have forgotten the snipped. I am using Python as Language use the following snipped to build the instance:

`exBitZ = ccxt.bitz({
    'apiKey': config['API']['Key'],
    'secret': config['API']['Secret'],
    'password': config['API']['Password']
})`

The correct values cam from the config file and are set correctly

i use the following code to submit a trade:

**Comment by tognellap** [comment]
I found the solution. Ther special chars in the password where wrong.

**Comment by kroitor** [comment]
@tognellap thx for reporting back!

**Comment by belsebob90** [comment]
Call you soon

Den fre 16 mars 2018 19:53Igor Kroitor <notifications@github.com> skrev:

**Comment by belsebob90** [comment]
I have it fexed soon so all 250is on my account

Den fre 16 mars 2018 19:58Niko Tolonen <darkfuneral462@gmail.com> skrev:
