### ISSUE TITLE
Kucoin Issue with private requests

### ISSUE THREAD

**Issue by nikky78** [ccxt/ccxt#21679]
### Programming Languages

Python

### CCXT Version

4.2.68

### Description

The new version has an issue with kucoin with querying 
`await exchange.fetch_balance()`
 for instance. We get an error: 
`TypeError: Cannot serialize non-str key None`

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @nikky78,
thanks for reporting it, we will take a look asap.

**Comment by carlosmiei** [comment]
@nikky78 Can you update your ccxt version to the latest and try again? It should be working now.

**Comment by nikky78** [comment]
Perfect ! yes it works Thanks Carlos!
