### ISSUE TITLE
Bit-Z : Incorrect sorting of OrderBook

### ISSUE THREAD

**Issue by wntsang4** [ccxt/ccxt#2168]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10
- Programming Language version: Python
- CCXT version: 1.11.35
- Exchange: Bit-Z
- Method: fetch_order_book

{'bids': [[3.658e-05, 920.6384], [3.657e-05, 2732.251], [3.65e-05, 190.9632], [3.604e-05, 2000.0], [3.603e-05, 2189.8655], [3.512e-05, 9702.49], [3.511e-05, 324.5694], [3.51e-05, 100.0], [3.5e-05, 560.1849], [3.311e-05, 3020.7838], [3.31e-05, 500.0], [3.301e-05, 105.0], [3.3e-05, 909.0911], [3.2e-05, 3093.75], [3.189e-05, 1000.0], [3.18e-05, 12000.0], [3.113e-05, 500.0], [3.01e-05, 500.0], [3e-05, 1000.0], [2.9e-05, 410.0], [2.5e-05, 1000.0], [2.1e-05, 540.5622], [2e-05, 1463.3164], [1.987e-05, 1299.3292], [1.594e-05, 9275.5883], [1.587e-05, 1610.5545], [1.4e-05, 12142.857], [1.319e-05, 2078.6413], [1.15e-05, 14782.6085], [1.1e-05, 5309.1817], [1.012e-05, 300.0], [1.01e-05, 902.0], [1.06e-06, 3600.0], [1.1e-07, 63005.5399], [1e-07, 235.6039], [1e-08, 4792.9999]], 
'asks': [[0.00011095, 26.7558], [0.00011094, 38.3017], [0.0001109, 8093.2984], [0.00011, 807.2638], [0.00010999, 51.5537], [0.0001099, 80.1342], [0.00010989, 9.6498], [0.0001095, 10149.84], [0.000109, 9915.99], [0.0001084, 15.0], [0.000108, 16.9869], [0.0001073, 5.994], [0.0001072, 14.1764], [0.000107, 932.067], [0.0001061, 15.0], [0.0001056, 15.6348], [0.00010543, 13.763], [0.000105, 20567.6585], [0.00010409, 15.0], [0.000104, 5.994], [0.00010266, 20.0], [0.000102, 19.98], [0.0001019, 29.99], [0.000101, 1000.0], [0.0001, 11771.7664], [9.999e-05, 5970.0313], [9.997e-05, 3244.5814], [9.995e-05, 24.995], [9.98e-05, 544.4597], [9.9e-05, 912.087], [9.896e-05, 20.1855], [9.873e-05, 535.3943], [9.8e-05, 5172.9424], [9.795e-05, 19.0601], [9.7e-05, 20.0], [9.698e-05, 24.935], [9.6e-05, 2500.0], [9.5e-05, 940.3679], [9.222e-05, 19.98], [9.15e-05, 1852.5139], [9e-05, 2007.2617], [8.997e-05, 3965.5994], [8.9e-05, 25.1948], [8.848e-05, 13.1631], [8.7e-05, 33.2544], [8.6e-05, 1385.1175], [8.5e-05, 70.1116], [8e-05, 4898.2494], [7.999e-05, 940.3679], [7.997e-05, 3605.0904], [7.98e-05, 3548.0069], [7e-05, 1026.993], [6.997e-05, 3605.0904], [6.887e-05, 159.0043], [6.768e-05, 1000.0], [6.214e-05, 654.6405], [6e-05, 718.4785], [5.999e-05, 390.75], [5.919e-05, 100.0], [5.915e-05, 9419.7911], [5.905e-05, 150.5878], [5.9e-05, 142.7696], [5.849e-05, 1160.665], [5.599e-05, 933.5488], [5.597e-05, 189.0255], [5.53e-05, 5969.9364], [5.499e-05, 390.75], [5.4e-05, 100.0], [5.35e-05, 799.2], [5.3e-05, 1142.8737], [5.281e-05, 80.0], [5.222e-05, 898.9586], [5.181e-05, 80.0], [5.11e-05, 1567.0586], [5.099e-05, 1213.1051], [5e-05, 1740.8464], [4.991e-05, 498.7737], [4.981e-05, 80.0], [4.881e-05, 80.0], [4.8e-05, 40447.9668], [4.799e-05, 1198.944], [4.798e-05, 1500.0], [4.79e-05, 1490.0], [4.781e-05, 80.0], [4.619e-05, 54.691], [4.6e-05, 3977.479], [4.599e-05, 260.5], [4.521e-05, 437.3789], [4.519e-05, 60.0], [4.518e-05, 778.9215], [4.5e-05, 5000.0], [4.498e-05, 3867.9285], [4.4e-05, 5000.0], [4.3e-05, 5000.0], [4.25e-05, 1003.757], [4.233e-05, 217.235], [4.198e-05, 0.3983], [4.195e-05, 530.5197], [4.1e-05, 28.0], [4.099e-05, 889.5058]], 'timestamp': 1520496388000, 'datetime': '2018-03-08T08:06:28.000Z'}

According to manual, **The asks array is sorted by price in ascending order. The best (lowest) ask price is the first element and the worst (highest) ask price is the last element.**

Code:
print(bitz.fetch_order_book('SPHTX/BTC'))

**Comment by mkutny** [comment]
Is this problem consistent? Can't reproduce on my side.

**Comment by wntsang4** [comment]
Yes, it is consistent.

**Comment by mkutny** [comment]
Oops... Indeed. It's python related.

Curious how happened that no-one encountered it before.
