### ISSUE TITLE
bitget) how can use fetch_positions for checking closed position information?

### ISSUE THREAD

**Issue by PUVl** [ccxt/ccxt#21683]
### Operating System

Window 10

### Programming Languages

Python

### CCXT Version

Latest

### Description

how can use fetch_positions for checking closed position information?
If that is not possible, is there another way to check information about the position that ended just before?

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @PUVl,
What's the exchange? By default, fetch_positions returns only opened positions

**Comment by PUVl** [comment]
> Hello @PUVl, What's the exchange? By default, fetch_positions returns only opened positions

exchange is birget. then how can I get the information about closed position? I want to know closed price and amount.

**Comment by carlosmiei** [comment]
@PUVl In this case I think you can do this:

```Python
bitget.options['fetchPositions']['method'] = 'privateMixGetV2MixPositionHistoryPosition'
all_pos = await bitget.fetch_positions()
```

I will update our documentation to make this more clear.
