### ISSUE TITLE
 probit access token expired

### ISSUE THREAD

**Issue by haitokt** [ccxt/ccxt#21707]
### Operating System

xampp, win10

### Programming Languages

PHP

### CCXT Version

lastest

### Description

Hi;
I've made create_order in probit exchange but got error:

Fatal error: Uncaught ccxt\AuthenticationError: probit access token expired, call signIn() method in C:\xampp\htdocs\main\ccxt11t3\php\probit.php:1777 Stack trace: #0 C:\xampp\htdocs\main\ccxt11t3\php\Exchange.php(4404): ccxt\probit->sign('new_order', 'private', 'POST', Array, NULL, NULL) #1 C:\xampp\htdocs\main\ccxt11t3\php\Exchange.php(4412): ccxt\Exchange->fetch2('new_order', 'private', 'POST', Array, NULL, NULL, Array) #2 C:\xampp\htdocs\main\ccxt11t3\php\abstract\probit.php(92): ccxt\Exchange->request('new_order', 'private', 'POST', Array, NULL, NULL, Array) #3 C:\xampp\htdocs\main\ccxt11t3\php\probit.php(1240): ccxt\abstract\probit->privatePostNewOrder(Array) #4 C:\xampp\htdocs\main\ccxt11t3\probitORDER.php(52): ccxt\probit->create_order('BTC-USDT', 'LIMIT', 'buy', 0.0003, 50000.0) #5 {main} thrown in C:\xampp\htdocs\main\ccxt11t3\php\probit.php on line 1777

How can i get this worked? thank for your support!

### Code

```
  $poloniex   = new \ccxt\probit   (array (
    'apiKey' => 'xxx',
    'secret' => 'xxxx',
));


$poloniex_markets = $poloniex->load_markets ();
$poloniex->create_order ('BTC-USDT', 'LIMIT', 'buy', 0.0001, 50000, array ('client_order_id' => '123'));




```

**Comment by sc0Vu** [comment]
@haitokt I think you can signIn to retrieve another token.

**Comment by haitokt** [comment]
thank you, it worked!
