### ISSUE TITLE
BingX: watchOrders - Authentication expiring after 1 hour

### ISSUE THREAD

**Issue by nvrossett** [ccxt/ccxt#21702]
### Operating System

Debian

### Programming Languages

JavaScript

### CCXT Version

4.2.69

### Description

I'm developing an integration with BingX and I've noticed an instability in watchOrders (at least it always gives me this error)

When this problem occurs, the WatchTicker continues to work normally.

But after EXACTLY 1 hour open the channel, bingx returns this:

```
ExchangeNotAvailable
bingx PUT https://open-api.bingx.com/openApi/user/auth/userDataStream?listenKey=072415ebaec54d6405f6e4f37d8e72ad92d8736671dd7c6446756ead745dd499&timestamp=1710348106142&signature=81ba4519 d429325f007dcb697898e1b0b9cf54cabc63b29a427bd056efa77ba8 404 Not Found
```

This is only in WatchOrders, it is clearly an authentication that has expired and he is unable to continue following the channel.

I believe that any other channel that requires authentication has the same problem since watchTicker is public and does not require authentication.

I started my application and started recording almost at the same time.
Note the video time clock in the lower left corner

https://www.youtube.com/watch?v=EGT-kjrrBNQ

**Comment by sc0Vu** [comment]
@nvrossett the listen key would be refresh automatically in the latest version, could you upgrade and try again?

**Comment by nvrossett** [comment]
@sc0Vu I downloaded version 4.2.72 yesterday and saw that it already had its implementation, I was going to run it yesterday but I needed to pay attention to another feature that affected precisely the behavior of my bot at startup, so I wasn't able to test it yesterday.

I put it to work here at this moment and within an hour I'll tell you if it worked.

I have version 4.2.73 at the moment, and as I marked you in the old post, please add "this.balance[type] ??= {}" in handleBalance
https://github.com/ccxt/ccxt/issues/21685

Every update I do I have to manually access the lib and add it, otherwise it generates this error, this is quite annoying, it only works without error if it declares the object empty before adding the properties if it doesn't exist yet.

As for this update, it is running here, as soon as the expiration time passes.

Once again, thanks for your agility with this key expiration issue.

This is a much more serious problem at the system level here and knowing that they were already solving it helped a lot.

**Comment by nvrossett** [comment]
@sc0Vu  I tested it here and now it works perfectly!!
Thank you very much
