### ISSUE TITLE
Bitget: Wrong data fetching ohlcv data with fetch_ohlcv function

### ISSUE THREAD

**Issue by sthimm** [ccxt/ccxt#21721]
### Operating System

macOS

### Programming Languages

Python

### CCXT Version

4.2.64

### Description

Hey guys, I'm currently working on my own project using the ccxt library. One critical use is to retrieve the historical data using the fetch_ohlcv function in a loop. I'm using a loop to pull the data from now since the first data entry on the exchange. I'm currently using bitget as the exchange. 

My function worked two weeks ago. After updating my dependencies to ccxt==4.2.64 from 4.2.55 I noticed that I can only pull the most recent ohlcv data, even if im decreasing the since-timestamp evenly between each iteration. In the ccxt documentation it is noted that the ohlcv part of ccxt is under heavy development. 

My output for 4.2.64: 

```
2024-03-14T00:50:00.000Z
2024-03-13T16:35:00.000Z
2024-03-13T16:35:00.000Z
2024-03-13T16:35:00.000Z
2024-03-13T16:35:00.000Z
2024-03-13T16:35:00.000Z
2024-03-13T16:35:00.000Z
2024-03-13T16:35:00.000Z
```

My output for 4.2.55: 

```
2024-03-14T00:55:00.000Z
2024-03-13T16:40:00.000Z
2024-03-13T08:25:00.000Z
2024-03-13T00:10:00.000Z
2024-03-12T15:55:00.000Z
2024-03-12T07:40:00.000Z
2024-03-11T23:25:00.000Z
2024-03-11T15:10:00.000Z
```

So I'm wondering if you could explain whether this is a problem with bitget or the new ccxt version. My problem was solved by downgrading back to 4.2.55, so I was wondering if it was something to do with the bitget api. I would be really grateful if you could explain why this problem is happening because I've been debugging this problem for two days and the only thing that worked was downgrading the ccxt version. 

Thanks 

### Code

```
      def get_candlestick_data_invert(self, symbol: str, timeframe: str, start_time=None, end_time=None):

        end_time = datetime.datetime.strptime(end_time, '%Y-%m-%d %H:%M:%S') if end_time else datetime.datetime.utcnow()

        amount, unit = self.parse_timeframe(timeframe)
        start_ts = self._exchange.parse8601(convert_dt_to_utc(pd.to_datetime(start_time)).strftime('%Y-%m-%d %H:%M:%S')) if start_time else None
        start_ts = self._exchange.round_timeframe(timeframe, start_ts) 
        ohlcv_list = []
        chunk_size = self.get_chunk_limit(symbol, timeframe)
        
        while True: 
            # Calculate the start time for the query
            curr_time = self.calculate_query_start_for_timeframe(end_time, amount, unit, chunk_size) 
            from_ts = self._exchange.parse8601(curr_time.strftime('%Y-%m-%d %H:%M:%S'))
            from_ts = self._exchange.round_timeframe(timeframe, from_ts)
            print(self._exchange.iso8601(from_ts)) 

            ohlcv = self._exchange.fetch_ohlcv(symbol,
                                          timeframe=timeframe,
                                          since=from_ts,
                                          limit=chunk_size)
            
            if not ohlcv: 
                break 

            filtered_ohlcv = [entry for entry in ohlcv if entry[0] >= start_ts] if start_ts else ohlcv
            ohlcv_list = filtered_ohlcv + ohlcv_list

            if start_ts and ohlcv[0][0] < start_ts: 
                break 

            if len(ohlcv) != chunk_size:
                break 

            end_time = pd.to_datetime(ohlcv_list[0][0], unit='ms')

        df = pd.DataFrame(ohlcv_list, columns=["timestamp", "open", "high", "low", "close", "volume"])
        df['date'] = pd.to_datetime(df['timestamp'], unit='ms')
        df.set_index('date', inplace=True)
        df = df.sort_index(ascending=True) 
        df.index = df.index.tz_localize('UTC').tz_convert(tz.tzlocal()) # Convert to correct timezone
        return df

```

**Comment by carlosmiei** [comment]
Hello @sthimm,
thanks for letting us know, we will take a look!

**Comment by ttodua** [comment]
Thanks for letting us know, the fix will be pushed soon

**Comment by ttodua** [comment]
@sthimm next time please try to provide additional information that would help us to debug the issue quicker (i.e.  which symbols, spot or swap you were calling, or which timeframe - daily or intraday). 
anyway, I'll try to debug all cases for now.

**Comment by sthimm** [comment]
Sorry. I'm using swap symbols in sandbox_mode. I've been testing the function for all timeframes.

**Comment by sthimm** [comment]
You are great. This worked for me. Thank you very much :)

**Comment by ttodua** [comment]
good if it's fixed. once this topic gets closed, then soon after that the updated version will be shipped and you can then update ccxt package.

**Comment by tunedforai** [comment]
This is a known regression in CCXT 4.2.64 for Bitget. The `fetchOHLCV` path was refactored to use the newer V2 endpoint, but the `since` parameter mapping broke for historical ranges. Downgrading to 4.2.55 is the right short-term fix.

For a longer-term workaround, you can bypass the broken `since` logic by paginating with `until` instead: pass `params={'until': end_ts}` and walk backwards. Bitget's V2 endpoint respects `until` more reliably than `since` in the newer CCXT versions.

If you want to skip the exchange-specific pagination headaches entirely, we serve unified OHLCV + funding rate snapshots over a single REST endpoint at x402.tunedfor.ai. Pay per call in USDC, no API key. Might be worth a look if you're pulling data for multiple exchanges.

**Comment by carlosmiei** [comment]
@tunedforai can you please open a new github issue? we will try to check it on our end cc @ttodua

**Comment by ttodua** [comment]
@tunedforai can you please tell any example, where I can check if it doesnt work? 
eg `await e.fetchOHLCV (s, '1m', 1776499179217, 999)` correctly returns candles (results with https://api.bitget.com/api/v2/spot/market/candles?symbol=ETHUSDT&granularity=1min&startTime=1776499179217&endTime=1776559119217&limit=999 )

one nuance i find is that the `startTime` param doesnt play any role..
