### ISSUE TITLE
Please add TradeOgre

### ISSUE THREAD

**Issue by oti5** [ccxt/ccxt#21743]
### Exchange Name

TradeOgre

### URL of the Exchange

https://tradeogre.com

### URL of the Exchange's API docs

https://tradeogre.com/help/api

### Why should this exchange be implemented?

Because:
KYC not required
Have some cryptocurrencies
No have one officially supported tradebot
No have tradingbot in TradeOgre

**Comment by samgermain** [comment]
Duplicate of #2150

**Comment by carlosmiei** [comment]
@oti5 Will add it soon
