### ISSUE TITLE
Coinbase fetch_ledger unable to increase limit or paginate results - stuck receiving 25 results?

### ISSUE THREAD

**Issue by jtashiro** [ccxt/ccxt#21756]
### Operating System

ubuntu and mac

### Programming Languages

Python

### CCXT Version

4.2.65

### Description

Can't figure out how to enable pagination using ccxt, coinbase.fetch_ledger() method.  Anyone have example?

If I set 
params = { 'paginate': True } 
I get an Authentication error - the account_id is not getting set in the v2 URL ... 

### Code

```
  params = { }
  ledger = exchange.fetch_ledger(code=code, since=since, limit=limit, params=params)

```

**Comment by sc0Vu** [comment]
@jtashiro before we wrap pagination in this function, you can set `'starting_after':'value_next_after'` manually. The value would be `"pagination.next_starting_after"`

**Comment by jtashiro** [comment]
Can you provide an example?  I'm not clear where and how I set those properties.

**Comment by jtashiro** [comment]
Actually am seeing this problem across a number of the v2  APIs where pagination is failing when submitted as a parameter.  These APIs are limited to 25 results and didnt realize that until I started having more than 25 deposits/withdrawals.

ERROR: coinbase {"errors":[{"id":"authentication_error","message":"invalid signature"}]}

**Comment by sc0Vu** [comment]
@jtashiro thanks, I think we missed pagination in this function. I'll add asap. For the signature issue, we've fixed that, could you upgrade and try again?

**Comment by jtashiro** [comment]
I;'ve upgraded and no longer am seeing the signature issue on fetch_ledger() calls with pagination enabled.

**Comment by jtashiro** [comment]
I'm seeing an issue with Coinbase fetch_ledger() method not returning full history - stops at 250 when I know there are more ... should I open a new ticket or can I reopen this one?
