### ISSUE TITLE
Got : PERCENT_PRICE  issue

### ISSUE THREAD

**Issue by kAgotsi** [ccxt/ccxt#21753]
### Programming Languages

Python

### CCXT Version

4.1.68

### Description

Got this error when sell position : `Error closing trade: binance {"code":-4131,"msg":"The counterparty's best price does not meet the PERCENT_PRICE filter limit."}`

How to resolve please

**Comment by samgermain** [comment]
Can you post a minimum [reproducible example please](https://stackoverflow.com/help/minimal-reproducible-example)?
