### ISSUE TITLE
Explain Error Handling

### ISSUE THREAD

**Issue by frosty00** [ccxt/ccxt#2175]
Hi @kroitor and @xpl and all the developers of ccxt.

I'm have a few questions about error handling in ccxt. So there are ~two~ *three* main methods that are in the source of most exchanges for handling errors:

* `handleErrors`
* `throwErrorOnException`
* *`request`*

I gather that handleErrors called in fetch and throwErrorOnException is called pretty much anywhere. However I  also see some errors get thrown in request and I'm not really sure if they should be raised there. 

Could someone explain how these two methods are supposed to work together. Moreover, @kroitor was talking about only parsing JSON once before but I'm not sure where this should take place. Is 

All the best,
frosty

**Comment by mkutny** [comment]
> Could someone explain how these two methods are supposed to work together.

- `throwErrorOnException` I'm not able to find at all... maybe you made a typo.
- error handling in `request` is obsolete, we're in the process of migration from `request` to `handleErrors`. once it's finished all `request`s could be removed.

> Moreover, @kroitor was talking about only parsing JSON once before but I'm not sure where this should take place

Ok, let's recap how the request call chain looks like: `someNativeMethod` -> `request` -> `fetch2` -> `fetch` -> `executeRestRequest` -> `handleRestResponse` -> `handleErrors`

Not long ago all three languages (JS/Python/PHP) parsed JSON in `handleRestResponse` *after* the call to `handleErrors`. This basically required all exchange instances to parse JSON in `handleErrors` one more time.

Recently JS version started to parse JSON in `handleRestResponse` *before* the call to `handleErrors`. It provides parsed json to `handleErrors` in the last argument:
https://github.com/ccxt/ccxt/blob/ecf82f3fd9f225ebb7f3772c4ca45f4406a7d070/js/qryptos.js#L414

Still, we need to parse JSON in this method until Python/PHP versions implement a change similar to JS.

**Comment by frosty00** [comment]
@mkutny I meant to say throwExceptionOnError, and why is kucoin the only exchange that has implemented this method? Surely it would make sense to move the logic to `handleErrors` for consistency?

> error handling in request is obsolete, we're in the process of migration from request to handleErrors. once it's finished all requests could be removed.

Thanks for clarifying. I'll look into relocating some of this code tomorrow. 

> Recently JS version started to parse JSON in handleRestResponse before the call to handleErrors. It provides parsed json to handleErrors in the last argument.

Sorry if I'm being naive but why is 

```let jsonRequired = this.parseJsonResponse && !this.skipJsonOnStatusCodes.includes (response.status)

let json = jsonRequired ? this.parseJson (response, responseBody, url, method) : undefined
```

all this additional logic required? Wouldn't a simple

```
try:
    json.loads(request.body)
except ValueError:
    pass
```

suffice?

**Comment by mkutny** [comment]
> Surely it would make sense to move the logic to handleErrors for consistency?

It's called by `handleErrors` anyway. Feel free to move it, although it either won't be as concise or will parse json twice.

> why is this additional logic required?

Because sometimes we expect json (and we should throw if json is not received) and sometimes we expect plaintext (and should proceed if json is not received). Alternatively, it could be something like:
```python
try:
    json.loads(request.body)
except ValueError:
    if jsonRequired:
        raise
    else:
        pass
```

**Comment by frosty00** [comment]
From what I can see of the python base class it seems that `executeRestRequest` doesn't exist and `handleRestResponse` doesn't get called before `handleErrors`. The Python base class also has another method called  `handle_rest_errors(self, exception, http_status_code, response, url)` which seems to be an old, vestigal version of `handle_rest_response`, I may just outright delete it. 

Furthermore, is there a reason to keep the http status `reason` in the signature of `handleErrors`? I have only seen it used once in the entire codebase, since we check against http status codes like 418 and not strings like "I'm a teapot" because people are likely to misspell them. Since we are adding another argument (the json response) and the signature already quite long, and I think it might be better to remove it. I'll attempt at making a PR but I can't garentee that it will be bug free (:

**Comment by mkutny** [comment]
Callchains among languages may be different indeed.

Agree that `reason` is probably not needed.

**Comment by kroitor** [comment]
> Furthermore, is there a reason to keep the http status reason in the signature of handleErrors? I have only seen it used once in the entire codebase, since we check against http status codes like 418 and not strings like "I'm a teapot" because people are likely to misspell them. Since we are adding another argument (the json response) and the signature already quite long, and I think it might be better to remove it. I'll attempt at making a PR but I can't guarantee that it will be bug free (:

I think this might be a misconception, we can't really throw http codes away easily, because there are exchanges that will report http error codes instead of internal codes, and we really need to differentiate between them sometimes...

**Comment by kroitor** [comment]
The general codepath should be:

1. Make the HTTP request
2. Parse JSON response once, if any, whatever the http response code
3. Pass parsed JSON response to handleErrors along with other data needed for exchange-specific error handling, including the http response code, whatever it is
4. In `handleErrors` any exchange-specific errors signalled either in a JSON-encoded format or with HTTP codes
5. In `handleRestErrors` handle HTTP error codes that were not intercepted in handleErrors...

Now, in different implementations the actual callchain may be different from the above. And current implementation is neither ideal, nor final (subject to change). The goal is not to unify the set of base methods (they will always remain language-specific), the goal is unify the flow:
1. parse JSON just once (not fulfilled yet, namely, we do parse JSON in several places in python and PHP, probably in JS as well..)
2. be flexible in error handling
3. make sure derived classes can override default behaviour

**Comment by frosty00** [comment]
#2295

**Comment by kroitor** [comment]
@frosty00 the problem with #2295 is that it directly contradicts my previous post here )) I mean, it overrides the handleErrors by doing p5 before p4. Moreover, it ignores p3.

**Comment by frosty00** [comment]
I tried again, this time trying to stick closely to the javascript as possible. Let me know your thoughts.

**Comment by kroitor** [comment]
@frosty00 thank you for your understanding! Really appreciate it... I've replied there, would close this issue for now and would propose to move the discussion to #2296, thx again!

**Comment by mkutny** [comment]
> I think this might be a misconception, we can't really throw http codes away easily, because there are exchanges that will report http error codes instead of internal codes, and we really need to differentiate between them sometimes...

As I've got the question was about dropping http status text, not about http status code. The code is needed, indeed. The text (i.e. `reason`) is not used.

What I would actually do (when the flow is unified) is switch `handleErrors` signature to options pattern, it'd make us flexible in args.

**Comment by frosty00** [comment]
I think the issue is that any `reason` is valid, even if it is non-standard. https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

Thus exchanges may put error messages in there (even though they really shouldn't)
