### ISSUE TITLE
FUNCTION fetchOrder for BIT-Z

### ISSUE THREAD

**Issue by Japsus** [ccxt/ccxt#2177]
Good afternoon,

Please, I urgently need the fetchOrder for this exchange.
Could you tell me how I can obtain this information or if you are going to take a long time to publish this function?

I await your response, thank you very much and greetings.

**Comment by kroitor** [comment]
Hi!

> Please, I urgently need the fetchOrder for this exchange.

Bit-z doesn't have means for fetching a single order at all, they offer fetchOpenOrders (all open orders at once). The rest of methods will be emulated via the `.orders` cache soon. 

https://github.com/ccxt/ccxt/wiki/Manual#querying-orders

Let us know if it does not answer your question. Thx!
