### ISSUE TITLE
Binance / Hyperliquid: Timestamp inconsistency in fetch_ohlcv

### ISSUE THREAD

**Issue by GeminonProtocol** [ccxt/ccxt#21783]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

4.2.74

### Description

The timestamp values returned by the fetch_ohlcv() function are inconsistent between exchanges.

For Hyperliquid, the function returns the closing timestamp of the candle, while for Binance it returns the opening timestamp. Most exchanges return the candle opening time. This inconsistency breaks the exchange interoperability that this library intends, I recommend changing the hyperliquid code so that it returns the opening timestamp as well.

Additionally, in the Binance code the timestamp is labeled as the closing of the candle when in reality the parser returns the opening time.

### Code

```
    # BINANCE
  def parse_ohlcv(self, ohlcv, market: Market = None) -> list:
        # when api method = publicGetKlines or fapiPublicGetKlines or dapiPublicGetKlines
        #     [
        #         1591478520000,  # open time
        #         "0.02501300",  # open
        #         "0.02501800",  # high
        #         "0.02500000",  # low
        #         "0.02500000",  # close
        #         "22.19000000",  # volume
        #         1591478579999,  # close time
        #         "0.55490906",  # quote asset volume, base asset volume for dapi
        #         40,            # number of trades
        #         "10.92900000",  # taker buy base asset volume
        #         "0.27336462",  # taker buy quote asset volume
        #         "0"            # ignore
        #     ]
        volumeIndex = 7 if inverse else 5
        return [
            self.safe_integer_2(ohlcv, 0, 'closeTime'), # <- This is openTime, not closeTime
            self.safe_number_2(ohlcv, 1, 'open'),
            self.safe_number_2(ohlcv, 2, 'high'),
            self.safe_number_2(ohlcv, 3, 'low'),
            self.safe_number_2(ohlcv, 4, 'close'),
            self.safe_number_2(ohlcv, volumeIndex, 'volume'),
        ]

    # HYPERLIQUID
    def parse_ohlcv(self, ohlcv, market: Market = None) -> list:
        #
        #     {
        #         "T": 1704287699999,
        #         "c": "2226.4",
        #         "h": "2247.9",
        #         "i": "15m",
        #         "l": "2224.6",
        #         "n": 46,
        #         "o": "2247.9",
        #         "s": "ETH",
        #         "t": 1704286800000,
        #         "v": "591.6427"
        #     }
        #
        return [
            self.safe_integer(ohlcv, 'T'), # <- This should be 't' (open time), not 'T' (close time) for consistency
            self.safe_number(ohlcv, 'o'),
            self.safe_number(ohlcv, 'h'),
            self.safe_number(ohlcv, 'l'),
            self.safe_number(ohlcv, 'c'),
            self.safe_number(ohlcv, 'v'),
        ]
```

**Comment by carlosmiei** [comment]
Hello @GeminonProtocol, thanks for bringing our attention to this. We will try to find a solution.

**Comment by carlosmiei** [comment]
@GeminonProtocol Regarding your suggestion, I'm not sure if 't' represents the opening of the candle (assuming that for instance the daily candle opens at 00:00 but the first trade might be at 00:05) but not sure if this is a problem with the wording in the docs.
![image](https://github.com/ccxt/ccxt/assets/43336371/5b25b0d8-b6ef-435c-b3a1-8eaa7646e75b)

**Comment by carlosmiei** [comment]
@GeminonProtocol We just confirmed and `t` is indeed the correct value, we will merge it shortly.

**Comment by carlosmiei** [comment]
@GeminonProtocol If you update your ccxt version, this issue should be fixed 🙂

**Comment by GeminonProtocol** [comment]
Thank you very much and great job guys!

(I already patched the library code locally, and also downloaded all the symbols to verify that the timestamps diff using 't' was a constant)
