### ISSUE TITLE
Bitstamp deprecated methods

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#21791]
Hello!
I've got an email from Bitstamp a few days ago:

> We are reaching out to you as you are one of our users who is still using our old balance endpoint /api/v2/balance/. We will discontinue this end point in near-to-mid future, so we kindly ask you to move away from it and start using the following (balance and fees have been split into multiple ones):
> https://www.bitstamp.net/api/#tag/Account-balances
> https://www.bitstamp.net/api/#tag/Fees

So we probably need to change endpoints in ccxt to new one

**Comment by carlosmiei** [comment]
@ndubel thanks for letting us know, we will take a look

**Comment by rayBastard** [comment]
There are also a few more methods that need to be fixed. I'll continue to work on this.
