### ISSUE TITLE
Question about fetchdepaddress

### ISSUE THREAD

**Issue by artbred** [ccxt/ccxt#2179]
I am using js and my goal is to check if its possible to deposit token. So the problem is that only few of stocks can create deposit addresses using api. For example if i write poloniex.fetchDepositAddress for a currency that i have never deposited before i will get btc address and my target is to check if its possible to deposit specific tokens without creating it(if its possible).By the way poloniex has method to generate a new address if im right.thanks

**Comment by kroitor** [comment]
> By the way poloniex has method to generate a new address if im right.thanks

We have both fetchDepositAddress (get only) and createDepositAddress (create and get) for poloniex implemented already. You can use whatever function you need right away with current version of ccxt.

https://github.com/ccxt/ccxt/wiki/Manual#funding-your-account

Let us know if it does not answer your question. Thx!

**Comment by artbred** [comment]
So i should write poloniex.createDepositAddress ? If its true i dont have this method. I have the newest version of ccxt

**Comment by kroitor** [comment]
@artbred 

> So i should write poloniex.createDepositAddress ?

yep, you do have to call `poloniex.createDepositAddress(...)`

> If its true i dont have this method. I have the newest version of ccxt

Actually, you do have this method, here it is: https://github.com/ccxt/ccxt/blob/master/js/poloniex.js#L734
