### ISSUE TITLE
Coin Buy Error - Bybit

### ISSUE THREAD

**Issue by azievm** [ccxt/ccxt#21800]
### Code

```
To proceed with trading, users must read through and confirm that they fully understand the project risk disclosure document. For App users, please update your Hybrid App to version 4.16.0 to process.
```

**Comment by Dan-krm** [comment]
I'd recommend logging into the website and attempting to trade the pair that you wanted to trade through CCXT it might guide you through accepting a risk disclosure agreement, then I would create new API keys and try again.

If that doesn't work, you can share your verbose output and I can look into it further:
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
