### ISSUE TITLE
New deposit address generation - not available for all exchanges?

### ISSUE THREAD

**Issue by markono1990** [ccxt/ccxt#2181]
Is it possible to generate new deposit addresses on each exchange? In [Public/Private API ](https://github.com/ccxt/ccxt/wiki/Manual#publicprivate-api) section it is written that Private API is used to create deposit addresses. I looked in the source, particularly for Binance, but found only a method to fetch existing address and didn't find any info how to create new address. As far as I understand only HitBTC, Bitfinex and Poloniex allow to generate new addresses or there are any other exchanges that support such a feature?

**Comment by kroitor** [comment]
> Is it possible to generate new deposit addresses on each exchange? 

To put it shortly, no, it is not possible on **each** exchange. Many exchanges will not allow you to actually do anything with the addresses and will hold control over the addresses themselves.

Binance does not allow that (yet) with their funding API: https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md

However, some exchanges do offer ways of creating new deposit addresses, like those you mentioned in your post. Some of them are already implemented in the unified ccxt API, all of them are already implemented in with ccxt implicit methods.

- https://github.com/ccxt/ccxt/wiki/Manual#unified-api
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

There are some exchanges that do allow creating new funding addresses, but don't have corresponding createDepositAddress methods implemented in ccxt, we hope to add implementations of those asap and we welcome all help and contributions ;))

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#pending-tasks
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#financial-contributions

> or there are any other exchanges that support such a feature?

The answer itself is encoded in the `.has['createDepositAddress` and `.has['fetchDepositAddress']` of each particular exchange. 

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

Having the above info, you can easily generate a table like this:

<img width="1878" alt="screen shot 2018-03-08 at 03 22 46" src="https://user-images.githubusercontent.com/1294454/37178361-40c51bda-2333-11e8-9813-a4a42e199575.png">

This is generated with the following simple script (can be done in any language): https://github.com/ccxt/ccxt/blob/master/examples/js/exchange-capabilities.js

Let us know if it does not answer your question. Thx!
