### ISSUE TITLE
Bybit leverage tiers parsing

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#21818]
### Programming Languages

Python

### CCXT Version

4.2.76

### Description

Based on the ccxt docs, leverage tiers should include minNotional and maxNotional.

```
{
        "tier": 1,                       // tier index
        "notionalCurrency": "USDT",      // the currency that minNotional and maxNotional are in
        "minNotional": 0,                // the lowest amount of this tier // stake = 0.0
        "maxNotional": 10000,            // the highest amount of this tier // max stake amount at 75x leverage = 133.33333333333334
        "maintenanceMarginRate": 0.0065, // maintenance margin rate
        "maxLeverage": 75,               // max available leverage for this market when the value of the trade is > minNotional and < maxNotional
        "info": { ... }                  // Response from exchange
    },
```

https://docs.ccxt.com/#/README?id=leverage-tiers

The new bybit "fetch_leverage_tiers()` is lacking parsing for this, returning for example this:

```
[{'tier': 1,
  'currency': None,
  'minNotional': None,
  'maxNotional': None,
  'maintenanceMarginRate': 0.005,
  'maxLeverage': 100.0,
  'info': {'id': '1',
   'symbol': 'BTCUSDT',
   'riskLimitValue': '2000000',
   'maintenanceMargin': '0.005',
   'initialMargin': '0.01',
   'isLowestRisk': '1',
   'maxLeverage': '100.00'}},
 {'tier': 2,
  'currency': None,
  'minNotional': None,
  'maxNotional': None,
  'maintenanceMarginRate': 0.0056,
  'maxLeverage': 90.0,
  'info': {'id': '2',
   'symbol': 'BTCUSDT',
   'riskLimitValue': '2600000',
   'maintenanceMargin': '0.0056',
   'initialMargin': '0.0111',
   'isLowestRisk': '0',
   'maxLeverage': '90.00'}},
// ...
```

The information to properly parse both currency (symbol - but in CCXT terms) - as well as the min/max notional - which in my understanding, should be comming from `riskLimitValue` (which delimits `maxNotional` - with minNotional being filled with the value from the previous tier, or 0 in case of the initial tier.

The way this endpoint looks currently, it's not usable (not least because it's even missing the currency).

### Code

``` python
import ccxt
exchange = ccxt.bybit({
    'options': {'defaultType': 'swap'} 
    })
lm = exchange.load_markets()

lt = exchange.fetch_leverage_tiers()
print(lt['BTC/USDT:USDT'])

``` 

Now unfortunately - the change to the parsing also broke the use of `exchange.fetch_market_leverage_tiers('BTC/USDT:USDT')` - which was working perfectly fine in prior versions  (e.g. 4.2.67 - essentially anything prior to #21747), and returned the following:

```
[{'tier': 1,
  'currency': 'BTC',
  'minNotional': 0,
  'maxNotional': 2000000.0,
  'maintenanceMarginRate': 0.005,
  'maxLeverage': 100.0,
  'info': {'id': '1',
   'symbol': 'BTCUSDT',
   'riskLimitValue': '2000000',
   'maintenanceMargin': '0.005',
   'initialMargin': '0.01',
   'isLowestRisk': '1',
   'maxLeverage': '100.00'}},
 {'tier': 2,
  'currency': 'BTC',
  'minNotional': 2000000.0,
  'maxNotional': 2600000.0,
  'maintenanceMarginRate': 0.0056,
  'maxLeverage': 90.0,
  'info': {'id': '2',
   'symbol': 'BTCUSDT',
   'riskLimitValue': '2600000',
   'maintenanceMargin': '0.0056',
   'initialMargin': '0.0111',
   'isLowestRisk': '0',
   'maxLeverage': '90.00'}},
//...
]
```

**Comment by sc0Vu** [comment]
@xmatthias thanks, will add maxNotional asap.
@carlosmiei for the minNotional, I'm not sure whether we should use the previous notional value (need to find the previous leverage tier with the same symbol).

**Comment by xmatthias** [comment]
@sc0Vu that's how it worked previously, too - don't see why you should remove that behavior, really.

So to be clear, my expectation is that both minNotional and maxNotional are there - otherwise it's a regression from previous versions.
