### ISSUE TITLE
Positions history

### ISSUE THREAD

**Issue by untoreh** [ccxt/ccxt#21823]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

In order to be able to replay the execution of trades of futures markets it is necessary to know the history of positions updates (in particular leverage and margin changes) for which there isn't a defined method

### Describe the solution you'd like

a method for fetching positions history or a subset of events (like leverage change for symbol or margin change for symbol) maybe using the `fetchLedger` method

**Comment by samgermain** [comment]
You can fetch the orders that you've placed, and determine what your positions were based on those orders. The leverage used here is kind of an illusion, all that really matters in determine your pnl is the size of your trade, and all the exchanges that I've looked at don't even use your leverage in determining what your liquidation price would be. They just use the trade size, and the maintenance margin ratio (which is based off the max leverage allowed I believe), [for example](https://www.gate.io/help/futures/futures/27724/liquidation-price-bankruptcy-price). You would also watch to use `fetch_funding_history` to track the funding fees coming in and out of your account.

Your right about margin changes though, that is a method that we should probably have, and it looks like it's possible for [binance at least](https://binance-docs.github.io/apidocs/futures/en/#get-position-margin-change-history-trade)

**Comment by samgermain** [comment]
From the certified exchanges, these were the [implicit api](https://docs.ccxt.com/#/?id=implicit-api) methods that return the history of positions or margin adjustments, but I'll be making some unified methods that call these endpoints soon

## margin adjustment history

### binance 

- [fapiPrivateGetPositionMarginHistory](https://binance-docs.github.io/apidocs/futures/en/#get-position-margin-change-history-trade)
- [dapiPrivateGetPositionMarginHistory](https://binance-docs.github.io/apidocs/delivery/en/#get-position-margin-change-history-trade)

### okx 

- [privateGetAccountBills](https://www.okx.com/docs-v5/en/#trading-account-rest-api-get-bills-details-last-7-days) with params='{"subType": 160/161/162}'
- [privateGetAccountBillsArchive'](https://www.okx.com/docs-v5/en/#trading-account-rest-api-get-bills-details-last-3-months) with params='{"subType": 160/161/162}
- thats 160 or 161 or 162, only one at a time

### coinex 

- [perpetualPrivateGetPositionMarginHistory](https://viabtc.github.io/coinex_api_en_doc/futures/#docsfutures001_http046_position_margin_history)

## position history

### bitget

- [mixGetMixV2PositionHistoryPosition](https://www.bitget.com/api-doc/contract/position/Get-History-Position)

### coinex

- [perpetualPrivateGetPositionFinished](https://viabtc.github.io/coinex_api_en_doc/futures/#docsfutures001_http033-0_finished_position)

### mexc 

-  [privateGetPositionListHistoryPositions](https://mexcdevelop.github.io/apidocs/contract_v1_en/#get-the-user-s-history-position-information)
