### ISSUE TITLE
[Hyperliquid] Bug on create_order: wrong format of the request

### ISSUE THREAD

**Issue by GeminonProtocol** [ccxt/ccxt#21824]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

4.2.74

### Description

The create_order() function does not work when any additional parameters are included via the 'params' dictionary. For example, this call:

exchange.create_order('BTC/USDT:USDT, 'limit', 'buy', 0.0005, 64000, params={'timeInForce': 'Gtc'})

Raises: 
ExchangeError('hyperliquid POST https://api.hyperliquid.xyz/exchange 422 Unprocessable Entity Failed to deserialize the JSON body into the target type')

The reason is that the create_orders() function uses "extend(request, params)" to add the raw parameters passed by the user to the request, which causes the request body to not conform to the API definition ( https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/exchange-endpoint).

I have solved the problem locally by simply changing "extend(request, params)" to "request".

### Code

```
  # Request sent:
{
    "action": {
        "type": "order",
        "orders": [
            {
                "a": 0,
                "b": true,
                "p": "63874",
                "s": "0.00053",
                "r": false,
                "t": {
                    "limit": {
                        "tif": "Gtc"
                    }
                }
            }
        ],
        "grouping": "na",
        "brokerCode": 1
    },
    "nonce": 1710883653272,
    "signature": {
        "r": "0x...",
        "s": "0x...",
        "v": 28
    },
    "timeInForce": "Gtc" # <- THIS SHOULD NOT BE HERE
}

async def create_orders(self, orders: List[OrderRequest], params={}):
    ...
    ...
    ...
    request = {
        'action': orderAction,
        'nonce': nonce,
        'signature': signature,
        # 'vaultAddress': vaultAddress,
    }
    response = await self.privatePostExchange(self.extend(request, params)) # <- Request should not be extendend with params
    # Replacing with this line makes it work: 
    # response = await self.privatePostExchange(request)
```

**Comment by sc0Vu** [comment]
@GeminonProtocol thanks, will fix this asap.

**Comment by carlosmiei** [comment]
@GeminonProtocol The newly released version fixes the issue so you can update if you want.

Thanks once again for reporting it!
