### ISSUE TITLE
REST BASE URL：https://www.okex.com/api/v1  

### ISSUE THREAD

**Issue by aototo** [ccxt/ccxt#2182]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: ....
- Programming Language version: node v9.2.1
- CCXT version: ccxt@^1.10.1266
- Exchange: okex
- Method: REST BASE URL：https://www.okex.com/api/v1

**Comment by kroitor** [comment]
Sorry?
