### ISSUE TITLE
HUOBIPRO ('Connection aborted.', BadStatusLine("''",))

### ISSUE THREAD

**Issue by jed057** [ccxt/ccxt#2183]
- OS:
- Programming Language version: Python
- CCXT version: latest
- Exchange: HUOBIPRO
- Method: fetch()

actually i am not sure if this is an ccxt issue, but let me try. In my application it's continuously querying account balance in a 1s pace manner, but it will always get an error after a random time, several minutes to couple of hours.

the error is as follow raised by base fetch method:
('Connection aborted.', BadStatusLine("''",))

I have tried to use api.huobipro.com the issue still happen. But it looks with this endpoint it can survive considerable longer.

the problem is, each time when this happen, the application will be stopped because of raising error. is it possible to not stop it (just ignore) ? I have tried to use try except instead, but the outer function will need to be modified as well (the returned value would be the last response and it may not be properly handled by function who called it). 

Could you pls advise how to deal with this problem? thx in advance!

**Comment by kroitor** [comment]
@jed057 this is fixed in #2224. Let us know if it does not help. Thx!

**Comment by jed057** [comment]
thx for the info Kroitor, I will try.

However I dont think simply switching from huobi.pro to huobipro.com can solve the issue reported by me, since that was originally submitted with huobipro.com. But anyway, let me try.
