### ISSUE TITLE
When i am getting private data like fetchMyTrades for bitfinex i am getting same data with keys and without keys so how i can get my private data with keys

### ISSUE THREAD

**Issue by daniyalnagori** [ccxt/ccxt#2184]
const exchangeBitfinex = new ccxt.bitfinex({
      apiKey: '123',
      secret: '123'
    })
    exchangeBitfinex['adjustForTimeDifference'] = true;    
    exchangeBitfinex['useServerTime'] = true;
    exchangeBitfinex.verbose = true;
    exchangeBitfinex.createOrder = true;
    exchangeBitfinex['isNode'] = true;
      exchangeBitfinex.loadMarkets()
      console.log(exchangeBitfinex.loadMarkets());
      exchangeBitfinex.fetchMyTrades('ETH/BTC', 1518983548636 - 2 * 24 * 60 * 60 * 1000).then((data) => {
        console.log('fetchMarkets', data);
      }).catch((err) => {
        console.log('err,', err);
      })

**Comment by kroitor** [comment]
@daniyalnagori can you post you verbose output please?

I'm not able to reproduce your issue:

code:

```JavaScript
'use strict';

const ccxt = require ('./ccxt.js')

const exchange = new ccxt.bitfinex({
    apiKey: '123',
    secret: '123',
});

;(async () => {
    await exchange.loadMarkets ()
    const trades = await exchange.fetchMyTrades ('ETH/BTC', 1518983548636 - 2 * 24 * 60 * 60 * 1000)
    console.log (trades)
}) ();

```

-----

Output:

```
mbp:ccxt igorkroitor$ node
> 'use strict';
'use strict'
>
> const ccxt = require ('./ccxt.js')
undefined
>
> const exchange = new ccxt.bitfinex({
...     apiKey: '123',
...     secret: '123',
... });
undefined
>
> ;(async () => {
...     await exchange.loadMarkets ()
...     const trades = await exchange.fetchMyTrades ('ETH/BTC', 1518983548636 - 2 * 24 * 60 * 60 * 1000)
...     console.log (trades)
... }) ();
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }
>
> (node:5207) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: bitfinex {"message":"Could not find a key matching the given X-BFX-APIKEY."}
(node:5207) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

As you see from the above output, it returns an error for a bad key, as it should. I get the same output with your code. Which version of ccxt do you use?
