### ISSUE TITLE
Gate.io, edit_order for perps

### ISSUE THREAD

**Issue by VinceJ666** [ccxt/ccxt#21856]
### Operating System

Linux

### Programming Languages

Python

### CCXT Version

4.2.78

### Description

I was trying to edit perps order using edit_order function from async_support/gate.py, the price was able to be changed, but the size/amount was not able to be edited.

### Code

```
  

```

**Comment by carlosmiei** [comment]
@VinceJ666 Actually not needed, I managed to reproduce the issue, will be fixed asap, thanks for letting us know.

**Comment by VinceJ666** [comment]
Cool, thanks!

**Comment by carlosmiei** [comment]
@VinceJ666 Can you update your ccxt version and try again? It should be working now

**Comment by VinceJ666** [comment]
With updated version, I can't edit order any more. It gives me the following error: 

 File ~/anaconda3/envs/cta/lib/python3.11/site-packages/ccxt/async_support/gate.py:3972 in edit_order
    response = await self.privateFuturesPutSettleOrdersOrderId(self.extend(request, query))

  File ~/anaconda3/envs/cta/lib/python3.11/site-packages/ccxt/async_support/base/exchange.py:816 in request
    return await self.fetch2(path, api, method, params, headers, body, config)

  File ~/anaconda3/envs/cta/lib/python3.11/site-packages/ccxt/async_support/base/exchange.py:813 in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File ~/anaconda3/envs/cta/lib/python3.11/site-packages/ccxt/async_support/base/exchange.py:243 in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

  File ~/anaconda3/envs/cta/lib/python3.11/site-packages/ccxt/async_support/gate.py:6699 in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], label, feedback)

  File ~/anaconda3/envs/cta/lib/python3.11/site-packages/ccxt/base/exchange.py:3980 in throw_exactly_matched_exception
    raise exact[string](message)

BadRequest: gate {"label":"INVALID_ARGUMENT","detail":"can't amend between bid and ask"}

**Comment by VinceJ666** [comment]
@carlosmiei With updated version, I can't edit order any more. It gives me the following error:

File ~/anaconda3/envs/cta/lib/python3.11/site-packages/ccxt/async_support/gate.py:3972 in edit_order
response = await self.privateFuturesPutSettleOrdersOrderId(self.extend(request, query))

File ~/anaconda3/envs/cta/lib/python3.11/site-packages/ccxt/async_support/base/exchange.py:816 in request
return await self.fetch2(path, api, method, params, headers, body, config)

File ~/anaconda3/envs/cta/lib/python3.11/site-packages/ccxt/async_support/base/exchange.py:813 in fetch2
return await self.fetch(request['url'], request['method'], request['headers'], request['body'])

File ~/anaconda3/envs/cta/lib/python3.11/site-packages/ccxt/async_support/base/exchange.py:243 in fetch
self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)

File ~/anaconda3/envs/cta/lib/python3.11/site-packages/ccxt/async_support/gate.py:6699 in handle_errors
self.throw_exactly_matched_exception(self.exceptions['exact'], label, feedback)

File ~/anaconda3/envs/cta/lib/python3.11/site-packages/ccxt/base/exchange.py:3980 in throw_exactly_matched_exception
raise exact[string](https://github.com/ccxt/ccxt/issues/message)

BadRequest: gate {"label":"INVALID_ARGUMENT","detail":"can't amend between bid and ask"}

**Comment by carlosmiei** [comment]
@VinceJ666 Weird, can you enable the verbose mode and post it please?

**Comment by carlosmiei** [comment]
@VinceJ666 The request seems correct, I think that's a restriction of the exchange, can you try with different sizes/amounts?

**Comment by VinceJ666** [comment]
@carlosmiei I tried different combinations of prices and amounts, it didn't work. I can place an order with exactly the same size and price, so I think edit order should accept these parameters. Are you able to reproduce the error on your end?

**Comment by carlosmiei** [comment]
@VinceJ666 Yes, it works on my end

```
 p gate editOrder "'436539451847'" "LTC/USDT:USDT" limit buy 1 53          
Python v3.11.7
CCXT v4.2.78
gate.editOrder(436539451847,LTC/USDT:USDT,limit,buy,1,53)
{'amount': 1.0,
 'average': None,
 'clientOrderId': 'api',
 'cost': 0.0,
 'datetime': '2024-03-21T12:14:58.918Z',
 'fee': None,
 'fees': [],
 'filled': 0.0,
 'id': '436539451847',
 'info': {'amend_text': '-',
          'biz_info': 'ch:ccxt',
          'contract': 'LTC_USDT',
          'create_time': '1711023298.918',
          'fill_price': '0',
          'iceberg': '0',
          'id': '436539451847',
          'is_close': False,
          'is_liq': False,
          'is_reduce_only': False,
          'left': '1',
          'mkfr': '0.00015',
          'pnl': '0',
          'pnl_margin': '0',
          'price': '53',
          'refr': '0',
          'refu': '0',
          'size': '1',
          'status': 'open',
          'stp_act': '-',
          'stp_id': '0',
          'text': 'api',
          'tif': 'gtc',
          'tkfr': '0.0005',
          'update_id': '5',
          'user': '10406147'},
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'postOnly': False,
 'price': 53.0,
 'reduceOnly': False,
 'remaining': 1.0,
 'side': 'buy',
 'status': 'open',
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': 'LTC/USDT:USDT',
 'takeProfitPrice': None,
 'timeInForce': 'GTC',
 'timestamp': 1711023298918,
 'trades': [],
 'triggerPrice': None,
 'type': 'limit'}
```

**Comment by carlosmiei** [comment]
@VinceJ666 I was running from the branch of the PR (with the outdated tag) but the version is latest, as you can see in the verbose log `size` is sent to the exchange as expected

> {"currency_pair":"SLERF_USDT","account":"futures","size":"700","price":"0.9"}

So I don't think this is a ccxt-issue.

Can you try to edit the order in the WEB UI to check if that is possible?

**Comment by VinceJ666** [comment]
@carlosmiei Web UI works fine. I can edit the order with the same price and amount.

**Comment by carlosmiei** [comment]
@VinceJ666 Hum just tried with the exact same market pair and it worked

```
p gate editOrder "'436696836021'" "SLERF/USDT:USDT" limit buy 150 0.5 --verbose
Python v3.11.7
gate.editOrder(436696836021,SLERF/USDT:USDT,limit,buy,150,0.5)

fetch Request: gate PUT https://api.gateio.ws/api/v4/futures/usdt/orders/436696836021 RequestHeaders: = RequestBody: {"currency_pair":"SLERF_USDT","account":"futures","amount":"150","price":"0.5"}

fetch Response: gate PUT https://api.gateio.ws/api/v4/futures/usdt/orders/436696836021 200 = ResponseBody: {"stp_id":0,"id":436696836021,"biz_info":"ch:ccxt","mkfr":"0.00015","tkfr":"0.0005","tif":"gtc","refu":0,"create_time":1711038017.749,"status":"open","price":"0.5","is_liq":false,"size":100,"refr":"0","iceberg":0,"is_reduce_only":false,"amend_text":"-","left":100,"text":"api","fill_price":"0","user":10406147,"update_id":2,"pnl_margin":"0","pnl":"0","stp_act":"-","is_close":false,"contract":"SLERF_USDT"}
{'amount': 100.0,
 'average': None,
 'clientOrderId': 'api',
 'cost': 0.0,
 'datetime': '2024-03-21T16:20:17.749Z',
 'fee': None,
 'fees': [],
```

**Comment by VinceJ666** [comment]
@carlosmiei I guess something was wrong in my python environment. I rebuild the env, it now works fine. Thanks.

**Comment by VinceJ666** [comment]
@carlosmiei I found the problem. when we edit the buy/long orders everything is fine. But when we edit sell/short order, the size parameter should be negative. I was able to reproduce the error in 4.2.79 when I was trying to edit sell order. And was successfully edit sell order using implicit api method: 
gate.privateFuturesPutSettleOrdersOrderId({'order_id':'436717730422','settle':'usdt','size':-400,'price':'0.89'})
Would you mind to take a look? Thanks.

**Comment by carlosmiei** [comment]
@VinceJ666 Great catch, will patch it and add a test for it asap!

**Comment by VinceJ666** [comment]
@carlosmiei No problem. I will use it as a temporary fix for now. Thanks for your help.
