### ISSUE TITLE
ClosedOrders does not work on Binance Swap - ExchangeError: binance {"code":-4166,"msg":"Search window is restricted to recent 90 days only."}

### ISSUE THREAD

**Issue by tom-teamcoda** [ccxt/ccxt#21862]
### CCXT Version

4.2.79 

### Description

Try to load closed orders but doesn't work for me

### Code

```
fetchCanceledAndClosedOrders('FET/USDT:USDT', 1705857391, 10)
or
fetchClosedOrders('FET/USDT:USDT', 1705857391, 10)

but SPOT pair 
fetchClosedOrders('FET/USDT', 1705857391, 10)
does work

```

**Comment by carlosmiei** [comment]
Hello @tom-teamcoda, unfortunately that's a restriction on the exchange side (spot and swap use different apis so they might have different limits/restrictions).

With that said, there's nothing ccxt can do about it.

**Comment by tom-teamcoda** [comment]
I'm sorry but even with timestamp from 1 day ago it does not work

**Comment by carlosmiei** [comment]
@tom-teamcoda That's because you're providing the timestamp in seconds instead of milliseconds (the unified format accepted by ccxt).

Can you try that?

**Comment by tom-teamcoda** [comment]
Yeah works. Also without Params
