### ISSUE TITLE
P2B ccxt.pro py watchTicker not working correctly

### ISSUE THREAD

**Issue by jonasgitabap** [ccxt/ccxt#21874]
### Operating System

MacOS

### Programming Languages

Python

### CCXT Version

4.2.79

### Description

Hi,

I use watchTicker with the ccxtpro instance of p2b in python with multiple symbols and it only returns always the last subscribed symbol. I use asyncio and for all other exchanges it works fine.

<img width="252" alt="image" src="https://github.com/ccxt/ccxt/assets/85170424/bd2b581c-8a1f-4386-b3c5-f30236a86fdd">

### Code

    self.exchange_id = 'p2b'

    exchange_config = {}
    exchange_config['asyncio_loop'] = asyncio.get_running_loop()
    exchange_config['timeout'] = 2000
    exchange_config['newUpdates'] = False
    exchange_config['enableRateLimit'] = False
    self.exchange: Exchange = getattr(ccxt_ws, self.exchange_id)(exchange_config)
    
    async def symbol_loop(self, symbol: str):
            while True:
                await asyncio.sleep(0)
                ticker: Ticker = await self.exchange.watch_ticker(symbol)
                print(ticker)

    if len(self.symbols_for_subscribe_spot) > 0:
       tasks = [asyncio.create_task(self.symbol_loop(symbol)) for symbol in self.symbols_for_subscribe_spot]
        all_tasks.extend(tasks)
    await asyncio.gather(*all_tasks)

**Comment by carlosmiei** [comment]
Hello @jonasgitabap thanks for letting us know, we will take as soon as possible
