### ISSUE TITLE
WS lbank watchTicker spot + swap not working

### ISSUE THREAD

**Issue by jonasgitabap** [ccxt/ccxt#21884]
### Operating System

MacOS

### Programming Languages

Python

### CCXT Version

4.2.81

### Description

Hey guys

i found a bug which looks like this: 
<img width="437" alt="image" src="https://github.com/ccxt/ccxt/assets/85170424/14209ad3-bde1-407d-b821-c3d6e03f44a9">
lbank: ExchangeError('lbank Invalid order pairs:[btcusdt]')

you can reproduce it if you subscribe BTC/USDT and BTC/USDT:USDT at the same time. Do you can fix this please?

Thanks in advance :)

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @jonasgitabapm thanks for reporting it, we will take a look and let you know asap.

**Comment by carlosmiei** [comment]
@jonasgitabap Right now we don't have swap support on the WS side, but we will try to add it shortly.

**Comment by samgermain** [comment]
It doesn't look like lbank has a websocket api for contract trading
