### ISSUE TITLE
[Hyperliquid] Bad request in fetch_positions when user credentials are not provided

### ISSUE THREAD

**Issue by GeminonProtocol** [ccxt/ccxt#21886]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

4.2.81

### Description

The `fetch_positions()` function returns a bad request error when called without parameters and the user has not provided his credentials (wallet and private key) at the time of instantiating the exchange. The call:

`await exchange.fetch_positions()`

Raise:
`ExchangeError: hyperliquid POST https://api.hyperliquid.xyz/info 422 Unprocessable Entity Failed to deserialize the JSON body into the target type`

When it should raise:
`ArgumentsRequired(Hyperliquid fetch_positions() requires a user parameter inside \'params\' or the wallet address set')`

The problem seems to be at the end of the `handle_public_address()` function. The `ArgumentsRequired` error is raised if the `userWallet` variable is None, but when credentials are not supplied the variable has the value of an empty text string ('') so instead of raising the error an incorrect request is sent to the API.

I can think of possible solutions:
- Fix default value of `userWallet` to be `None` instead of an empty string
- Patch `handle_public_address()` so that the `userWallet == ''` case also raises an error.

### Code

```
    async def fetch_positions(self, symbols: Strings = None, params={}):
        userAddress = None
        userAddress, params = self.handle_public_address('fetchPositions', params)
        symbols = self.market_symbols(symbols)
        request = {
            'type': 'clearinghouseState',
            'user': userAddress,
        }
        response = await self.publicPostInfo(self.extend(request, params))
    
    def handle_public_address(self, methodName: str, params: dict):
        userAux = None
        userAux, params = self.handle_option_and_params(params, methodName, 'user')
        user = userAux
        user, params = self.handle_option_and_params(params, methodName, 'address', userAux)
        if user is not None:
            return [user, params]
        if self.walletAddress is not None: 
            return [self.walletAddress, params]
        raise ArgumentsRequired(self.id + ' ' + methodName + '() requires a user parameter inside \'params\' or the wallet address set')

```

**Comment by carlosmiei** [comment]
Hello @GeminonProtocol, thanks for bringing our attention to this, we will patch it soon.

**Comment by carlosmiei** [comment]
@GeminonProtocol Same here, I believe it is fixed on the latest version, give it a try and let us know how that goes 🙂
