### ISSUE TITLE
Gate.io: fetchOrder not implemented.

### ISSUE THREAD

**Issue by sharmine** [ccxt/ccxt#2189]
- OS: windows
- Programming Language version: Nodejs
- CCXT version: 1.11.53
- Exchange: gateio
- Method: fetchOrder

This method is not emplemented yet; who can help me or if I can fix this issue and commit .
the api is https://api.gate.io/api2/1/private/getOrder

**Comment by kroitor** [comment]
> This method is not emplemented yet; who can help me or if I can fix this issue and commit .

Your contributions are welcome, we appreciate all help, just make sure to read this doc carefully: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

Let us know if you have any questions or if you need any assistance with it. Thank you so much!
