### ISSUE TITLE
Kucoin: Invalid amount increment for createMarketOrderWithCost()

### ISSUE THREAD

**Issue by mjwvb** [ccxt/ccxt#21898]
### Operating System

MacOS

### Programming Languages

JavaScript

### CCXT Version

4.2.80

### Description

When using createMarketOrderWithCost() on the Kucoin exchange with e.g. cost 0.89933212 on BTC/USDT, I get the error "The amount increment is invalid.". I went digging and it seems that ccxt is using the wrong increment property for "funds" (cost) on market orders.

In the ccxt code (->createOrderRequest), it uses amountToPrecision() for the funds param. This method always uses  "baseIncrement" as precision. That's on purpose as there's a comment that says "kucoin uses base precision even for quote values". However, the Kucoin documentation instructs to use the quoteIncrement for the funds parameter when placing market orders, see https://www.kucoin.com/docs/rest/spot-trading/orders/place-order. For BTC/USDT that's a difference between 0.00000001 and 0.000001, so the API rightfully throws an error.

I have a workaround working for now, but would be nice to have this fixed.

### Code

How to reproduce:
```javascript
const cost = 0.8993321164
const order = await exchange.createMarketOrderWithCost("BTC/USDT", "buy", cost);
// --> "Error: The amount increment is invalid."
```

My workaround:
```javascript
const cost = exchange.decimalToPrecision(
  originalCost,
  ccxt.functions.TRUNCATE,
  exchange.market("BTC/USDT").info.quoteIncrement,
  exchange.precisionMode,
  exchange.paddingMode
);

const order = await exchange.createMarketOrderWithCost("BTC/USDT", "buy", cost);
```

**Comment by sc0Vu** [comment]
@mjwvb thanks, we'll fix this asap.
