### ISSUE TITLE
How to use Bybit API native method  get_risk_limit  in CCXT context?

### ISSUE THREAD

**Issue by algosfox** [ccxt/ccxt#21897]
### Operating System

Wndows 10

### CCXT Version

 4.2.45

### Description

Is it possible to use native Bybit API method like  get_risk_limit to get maintenanceMargin in CCXT context?

https://bybit-exchange.github.io/docs/v5/market/risk-limit

### Code

```
  

```

**Comment by sc0Vu** [comment]
@algosfox you can call implicit methods (https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods) or `fetchDerivativesMarketLeverageTiers` to fetch maintenanceMargin.
