### ISSUE TITLE
Withdrawal of exchanged assets to end address

### ISSUE THREAD

**Issue by markono1990** [ccxt/ccxt#2190]
Let's say, I want to exchange BTC to ETH and then withdraw received ETH to my cold wallet (CW) where the CW's ETH address is changed regularly. Can I programmatically withdraw the received ETH to my CW? If yes, where should I store my ETH CW's address? Or maybe there is an example already? 

Please don't ban my question, I'm new here. If I'm doing something wrong just let me know and I will fix everything accordingly 🙂.

**Comment by kroitor** [comment]
> where should I store my ETH CW's address?

In your centralized database (which can be as simple as a local text file). Most often when some information or some resource is changing regularly, a better approach is not to store it, but to fetch it upon launch from a centralized database (online or locally) and keep it in memory from there. Sorry, this question itself is a little beyond the scope of the library itself, though it allows you to do everything you said, it will not design your goals for you, your application of the library is totally up to you, of course. 

The first thing I'd recommend is to read the entire Manual, then read through examples, and other docs, then browser through issues, this will get you on the right track in a few days.

- https://github.com/kroitor/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/tree/master/examples
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md
- https://github.com/ccxt/ccxt/issues

Hope it answers your question, let us know if it does not. Thx!
