### ISSUE TITLE
A quick one to fix: Hardcoded BrokerId on Blofin prevents API transactions (Error code: 152011)

### ISSUE THREAD

**Issue by basedbayes** [ccxt/ccxt#21902]
### Operating System

MacOS

### Programming Languages

Python

### CCXT Version

4.2.48

### Description

There is a hardcoded 'brokerId' on line 284 of blofin.py that prevents orders from being successfully created. If not overridden when sending an order you receive:
ExchangeError: blofin {"code":"152011","msg":"Transaction API Key does not support brokerId"}

Orders can be successfully placed like this: 
exchange.createOrder(symbol='MANTA/USDT:USDT', type='market', side='buy', amount=10, params={'brokerId': None})

Leaving this here since it couldn't be googled.

### Code

```
# doesn't work:
exchange.createOrder(symbol='MANTA/USDT:USDT', type='market', side='buy', amount=10)

# works:
exchange.createOrder(symbol='MANTA/USDT:USDT', type='market', side='buy', amount=10, params={'brokerId': None})

```

**Comment by carlosmiei** [comment]
Hello @basedbayes, 
Thanks for reporting it we will take a look

**Comment by carlosmiei** [comment]
@basedbayes Actually I think you might be using the wrong keys, can you please create a set using these steps and try again?
![image](https://github.com/ccxt/ccxt/assets/43336371/cb939591-718f-4038-9875-451601a3a218)

**Comment by basedbayes** [comment]
Ah, forgot Blofin had CCXT listed as an application. When using 'API Transaction' you can't choose the application btw. Is there any benefit for CCXT compatibility if I switch it to CCXT? Such as more detailed responses etc?

**Comment by carlosmiei** [comment]
> Ah, forgot Blofin had CCXT listed as an application. When using 'API Transaction' you can't choose the application btw. Is there any benefit for CCXT compatibility if I switch it to CCXT? Such as more detailed responses etc?

@basedbayes i don't know if there will be differences in that regard, but we tested all the features using ccxt-keys so I'm not sure if they work properly without it
