### ISSUE TITLE
Cryptopia -> fetchTrades "since" is in hours and floored instead of ceiled

### ISSUE THREAD

**Issue by tonymrakovcic** [ccxt/ccxt#2191]
Cryptopia has a mechanism for ```since``` in their API
However, it uses hours for ```since``` instead of timestamp values when you want new trades
As far as I can see, this hour functionality is implemented in ```cryptopia``` class in the ```fetchTrades``` method, however it rounds to the lower int, and this is not in sync with the "timestamp" semantically since if you set the timestamp of 90 minutes, you will receive only 1 hour of recent trades. In my opinion for 90 minutes 2 hours would be more correct.
Furthermore, if you are using any timestamp that is lower than an hour, it returns 0, and cryptopia returns an empty collection

I have tried it on my side, and it seems this solves the issue:
https://github.com/ccxt/ccxt/blob/master/js/cryptopia.js#L331
Turn this line:
```hours = parseInt(elapsed / hour);```
To this 
```hours = parseInt(Math.ceil(elapsed / hour));```

The python and php version seem straightward too
https://github.com/ccxt/ccxt/blob/master/php/cryptopia.php#L330
https://github.com/ccxt/ccxt/blob/master/python/ccxt/cryptopia.py#L317

I am happy to make a PR if you think this is a valid issue

- OS: MacOS High Sierra
- Programming Language version: nodejs 9.3.0
- CCXT version: 1.10.1014
- Exchange: Cryptopia
- Method: fetchTrades

**Comment by kroitor** [comment]
> I am happy to make a PR if you think this is a valid issue

Thanks for a comprehensive report! Your contributions are welcome, all help is appreciated. The issue you reported indeed seems like an existing issue with Cryptopia, we will be happy if you submit a pull-request. Just make sure to read this first: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

Let us know if you're going to target this bug. Thx!

**Comment by tonymrakovcic** [comment]
I think you might of closed the wrong issue?
I don't see these changes affecting this problem :)

**Comment by kroitor** [comment]
@tonymrakovcic yep, closed accidentally, will fix this one as well, shortly. Thx!
