### ISSUE TITLE
get leverage error

### ISSUE THREAD

**Issue by thisismygitrepo** [ccxt/ccxt#21918]
### Operating System

Any

### Programming Languages

Python

### CCXT Version

4.2

### Description

```python
ExchangeError: binance {"code":-5000,"msg":"GET /fapi/v1/positionRisk is retired, please use GET /fapi/v2/positionRisk"}

```

### Code

```

c.fapiPrivateGetPositionRisk({'symbol': api_perpetual.c.market_id('BNB/USDT')})
# c is binance client.
```

**Comment by carlosmiei** [comment]
Hello @thisismygitrepo, can you try this one instead? `fapiPrivateV2GetPositionRisk`

**Comment by carlosmiei** [comment]
@thisismygitrepo Alternatively, you can use the unified method `fetch_leverage`
