### ISSUE TITLE
Bitfinex v1 and v2 incorrect timestamp for candles

### ISSUE THREAD

**Issue by blackice999** [ccxt/ccxt#2192]
Hello,

I want to return the one minute candles using the Bitfinex class. The problem is that in the case of BTC/USD pair, the timestamp, if converted, indicates the year 2013. april 1 I didn't have any luck with other pairs either, for example, EOS/BTC returns the year 2017, july 1.
The tests have been runned just now, but still, 1 year and 5 years are a lot of time, considering that the bitfinex API returns only the last 100ish candles.
The others methods, like fetch_trades return the correct timestamp.

OS: Windows 7 SP1
Programming Language version: python 3
CCXT version: 1.10.1270
Exchange: Bitfinex
Method: fetch_ohlcv

**Comment by fedecaccia** [comment]
ANS: https://github.com/ccxt/ccxt/issues/2049

**Comment by kroitor** [comment]
Bitfinex will return last N candles starting from some date in time, If you want to get trades from a particular starting date, then you should pass the `since` argument. The same is true for most of exchanges. Hope it answers your question.
