### ISSUE TITLE
Exchange.Close does not complete. C#

### ISSUE THREAD

**Issue by skuvv** [ccxt/ccxt#21924]
### Operating System

Windows 10

### CCXT Version

4.2.80

### Description

Close does not finish internal tasks:
```
Task.Run(async () => await _exchange.close()).Wait();
```

### Code

demo project:
[DemoApp.zip](https://github.com/ccxt/ccxt/files/14748262/DemoApp.zip)

**Comment by carlosmiei** [comment]
@skuvv Close should be working fine as well, please update and let us know how that goes.

**Comment by carlosmiei** [comment]
@skuvv I will check it again and revert

**Comment by carlosmiei** [comment]
@skuvv Same here I think that now close is working as expected regardless of the current state of the task. Please give it a try and let us know.

**Comment by skuvv** [comment]
Tested on 4.2.86, exchange.Close(), now close most part of tasks with ccxt.ExchangeClosedByUser.
At the end I see a list of active clients.
I suppose the list should be empty and every client should be disconnected.

![image](https://github.com/ccxt/ccxt/assets/39260996/e4375899-a54b-42e0-9941-70b0b9b37da0)

![image](https://github.com/ccxt/ccxt/assets/39260996/808e295a-44c9-4532-922a-63e418e944ad)

**Comment by carlosmiei** [comment]
@skuvv Yeah I was expecting that as well, let me double-check it. Thanks for the detailed updated btw

**Comment by carlosmiei** [comment]
@skuvv Weird locally I can't reproduce the issue
![image](https://github.com/ccxt/ccxt/assets/43336371/82044710-a4bb-46a7-83c3-c522927b210f)

**Comment by skuvv** [comment]
I confirm that [DemoApp.zip](https://github.com/ccxt/ccxt/files/14748262/DemoApp.zip) work properly.

I prepared the demo where this problem still actual:
[DemoForDebug.zip](https://github.com/ccxt/ccxt/files/14804334/DemoForDebug.zip)

Thanks!

**Comment by carlosmiei** [comment]
@skuvv Are you sure you're using the latest version of ccxt? Even with the newest project I can't reproduce this :
![image](https://github.com/ccxt/ccxt/assets/43336371/4604a2c7-3e07-49b8-b148-72ae8da547f5)

**Comment by carlosmiei** [comment]
@skuvv I will try to ask a different dev to test it as well.

**Comment by ttodua** [comment]
@skuvv I'll be posting an update soon, but as I saw the repeated minor mistake (not important),  in example snippet you have:
```
 if (symbols.Count == countLimit)
     continue;
```
and I think instead of `continue` you need `break` there, so test results might be more expected

**Comment by skuvv** [comment]
Tested on 4.2.87 - working now.
Close() is finished and all of the tasks are cancelled/closed.
Thanks!

**Comment by carlosmiei** [comment]
@skuvv thanks for confirming it, let us know if anything!
