### ISSUE TITLE
Contract size in trade history

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#21938]
Trade on swap market on OKX exchange:
```
{
    info: {
      side: 'sell',
      fillSz: '12',
      fillPx: '0.03881',
      fillPxVol: '',
      fillFwdPx: '',
      fee: '-0.0023286',
      fillPnl: '-0.12',
      ordId: '692148329514172416',
      instType: 'SWAP',
      fillPxUsd: '',
      instId: 'PEOPLE-USDT-SWAP',
      clOrdId: 'e847386590ce4dBCcbd3c82b54d890a0',
      posSide: 'long',
      billId: '692177188812456048',
      fillMarkVol: '',
      tag: 'e847386590ce4dBC',
      fillTime: '1711299901841',
      execType: 'M',
      fillIdxPx: '0.03874',
      tradeId: '199729834',
      fillMarkPx: '0.03874',
      feeCcy: 'USDT',
      ts: '1711299901843'
    },
    timestamp: 1711299901843,
    datetime: '2024-03-24T17:05:01.843Z',
    symbol: 'PEOPLE/USDT:USDT',
    id: '199729834',
    order: '692148329514172416',
    type: undefined,
    takerOrMaker: 'maker',
    side: 'sell',
    price: 0.03881,
    amount: 12,
    cost: 46.572,
    fee: { cost: 0.0023286, currency: 'USDT' },
    fees: [ [Object] ]
  }
```

So we see `price: 0.03881, amount: 12, cost: 46.572`. `contractSize` is `100` so to get `cost` we need to multiply `price * amount * contractSize`. In https://github.com/ccxt/ccxt/wiki/Manual#trade-structure I see that "The cost of the trade means `amount * price`". So is it normal behaviour and I need to keep in mind `contractSize` by myself or we need to multiply `amount` here directly in ccxt? Can I be sure that behaviour is the same in all exchanges?

**Comment by ndubel** [comment]
@sc0Vu I mean `fetchMyTrades`. We multiply `cost` and I mean `amount`

**Comment by carlosmiei** [comment]
@ndubel We should handle the contract size properly, we will take a look thanks for reporting it.

**Comment by carlosmiei** [comment]
@ndubel Actually I think the value is correct, because 12 contracts = `12 * 100 = 1200 PEOPLE`, if the price is `0.038`  then the cost is `46`

**Comment by ndubel** [comment]
@carlosmiei yes, `cost` is ok but `amount` need to be multiplied by `contractSize`. We don't have `contractSize` in trade response so we need to look at market. 
Is it normal behaviour that `amount` is number of contract in trade response or `amount` should be premultiplied by ccxt (like `cost`)? That's my question

**Comment by carlosmiei** [comment]
@ndubel When trading swaps,  `amount` represents the number of contracts and not the `base amount`, the same thing happens with createOrder, you're expected to provide the number of contracts because that's effectively what we're buying/selling

**Comment by carlosmiei** [comment]
@ndubel No problem 🙂 
I think the main topic is clarified now so I'm going to close the issue, but let us know if anything!
