### ISSUE TITLE
Kucoin Pro: watchMyTrades is leaking trades when getting new updates (+ fix)

### ISSUE THREAD

**Issue by mjwvb** [ccxt/ccxt#21931]
### Operating System

MacOS

### Programming Languages

JavaScript

### CCXT Version

4.2.80

### Description

When using watchMyTrades in a while loop to get the newest updates on Kucoin, I only get one trade fill even though there were more during that tick. At first I thought the Kucoin websocket endpoint was unstable, but when looking at the code I found out that ccxt is only saving the most recent trade. The problem is in /pro/kucoin.js -> handleMyTrade():

```javascript
handleMyTrade(client, message) {
    let trades = this.myTrades;
    if (trades === undefined) {
        const limit = this.safeInteger(this.options, 'tradesLimit', 1000);
        trades = new ArrayCacheBySymbolById(limit);
    }
    // (...)
    trades.append(parsed);
    // (...)
}
```

The new trades array cache is never set to this.myTrades, so it won't reuse that cache for next incoming trade and only resolve with the current trade as received by handleMyTrade(). The fix is to simply set trades to this.myTrades. Applied a dirty patch to my node_modules and now it works fine. 

Would be nice to have this fixed so I can actually use this watcher.

### Code

My test code:
```javascript
while (true) {
  try {
    const trades = await exchange.watchMyTrades();
    trades.forEach((trade) => {
      console.log(new Date(), trade.id, trade.order, trade.symbol);
    });
  } catch (e) {
    console.log(e);
    if (e instanceof ccxt.BadRequest) throw e;
  }
}
```

**Comment by carlosmiei** [comment]
Hello @mjwvb, thanks a lot for reporting it we will fix it asap.
