### ISSUE TITLE
Exmo- fetch_balance Python

### ISSUE THREAD

**Issue by tatianamc** [ccxt/ccxt#2194]
Hello,
I have an issue to fetch balance at Exmo. All is OK with other exchanges. Also, it works with official Exmo API .

- OS: MAC 10.12.6
- Programming Language version: Python 3.6
- CCXT version: 1.11.46
- Exchange: Exmo
- Method:fetch_balance

import ccxt
exmo   = ccxt.exmo({
    'apiKey': 'xxxxx',
    'secret': 'xxxxx',
})
print(exmo.fetch_balance())

I get:
Traceback (most recent call last):
  File "test_balance_exmo_v1.py", line 35, in <module>
    print(exmo.fetch_balance())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/exmo.py", line 136, in fetch_balance
    response = self.privatePostUserInfo()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/exmo.py", line 476, in request
    raise ExchangeError(self.id + ' ' + self.json(response))
ccxt.base.errors.ExchangeError: exmo {"result":false,"error":"40009: The nonce parameter is less or equal than what was used before \"1520608121756\""}

**Comment by kroitor** [comment]
Have you tried a new key? You should try a new key first, as your previous nonce is screwed by the *"official"* client (they set it to milliseconds by default)...

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/Manual#error-handling
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-the-nonce
- https://github.com/ccxt/ccxt/blob/master/wiki/Manual.md#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#authentication

This will work: 

```Python
import ccxt
exmo = ccxt.exmo({
    'apiKey': 'xxxxx',
    'secret': 'xxxxx',
    'enableRateLimit': True,  # add built-in rate-limiting
    'nonce': lambda: self.milliseconds(),  # or a new key...
})
print(exmo.fetch_balance())
```

Let us know if it does not answer your question. Thx!
