### ISSUE TITLE
How to kill/unsubscribe all/all_by_id websocket connections for ws methods in ccxt.pro?

### ISSUE THREAD

**Issue by suenot** [ccxt/ccxt#21959]
### Operating System

macOS 14.2.1

### Programming Languages

JavaScript

### CCXT Version

4.2.82

### Description

How to kill/unsubscribe all/all_by_id websocket connections for ws methods in ccxt.pro?
For example, I use ws method watchCandlesForSymbols.

### Code

```
export const parseCandlesOneExchange = async ({exchangeId, pairIds}: {exchangeId: string, pairIds: string[]}) => {
  log('parseCandlesOneExchange', {exchangeId, pairIds});
  const pairIdsEmpty = _.isEmpty(pairIds);
  log({pairIdsEmpty});
  const exchangeInstance = new (ccxt.pro as any)[exchangeId]({});
  if (exchangeId in ccxt.pro) {
    while (true) {
      if (pairIdsEmpty) {
        log('sleep 5s');
        await sleep(5000);
      } else {
        try {
          const pairIdsWithFrames = _.map(pairIds, pairId => [pairId, '1m']);
          log({pairIdsWithFrames});
          const tradeCcxt: CcxtCandleSubscription = await exchangeInstance.watchCandlesForSymbols(pairIdsWithFrames);
          log({tradeCcxt});
        } catch (e) { log(e) };
      }
    }
  }
}

```
from 
https://github.com/suenot/intuition/blob/808e109ca08cd576be450f82294c529cb82e6886/src/providers/ccxt/parseCandles/parseCandles.ts#L32

**Comment by suenot** [comment]
I found that i used wrong name for method. Need watchOHLCVForSymbols not watchCandlesForSymbols. But question still important for me, because I need write test for this method and kill ws connection after I test method.

**Comment by pcriadoperez** [comment]
Hi @suenot , yes you can use `exchange.close()` to close all the websocket connections.

I'll close the issue for now, but feel free to reach out with any questions
