### ISSUE TITLE
qryptos fetch_balance() not reporting used

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#2195]
- OS: Windows
- Programming Language version: Python
- CCXT version: 1237
- Exchange: Qryptos
- Method: fetch_balance()

`fetch_balance()` does a GET to https://api.qryptos.com/accounts/balance . In the response is only one kind of balance, the 'total'. The 'used' balance (when you have open orders) is not reported back. Snippet of the response:
`[{"currency":"HERO","balance":"0.0"},{"currency":"ENJ","balance":"0.0"},{"currency":"STU","balance":"0.0"},{"currency":"GZE","balance":"0.0"},{"currency":"FSN","balance":"0.0"},{"currency":"SNIP","balance":"0.0"} (..)`

Do you think we can fix this in ccxt ? We could do a fetch_open_orders() and multiply the price * remaining , use that value to get our balance 'used' and deduct it from 'free'.

**Comment by kroitor** [comment]
> Do you think we can fix this in ccxt ?

Yes, we actually have a paragraph on [balance inference](https://github.com/ccxt/ccxt/wiki/Manual#balance-inference) in the Manual. This feature is already implemented for some exchanges (liqui, for example), but still, not all of them, obviously. We are working on it. We are not going to force `fetchOpenOrders`, instead we will use the [`.orders` cache](https://github.com/ccxt/ccxt/wiki/Manual#orders-cache) for that ;) Hope to add support for that in a few days.

Hope this answers your question. Let us know if we can help with anything else here. Thx!

**Comment by gaardiolor** [comment]
@kroitor OK Great! Sorry for missing that. 

If there are open orders in the cache, the cache needs to refresh on each `fetch_balance()`, right ? Because the order might be filled in the meanwhile. Will that happen automatically or should I do so manually running `fetch_open_orders()` before each `fetch_balance()` ? 

If it happens automatically it might be good to add that to the manual (second paragraph of `.orders cache`)

**Comment by kroitor** [comment]
> or should I do so manually by running fetch_open_orders() before each fetch_balance() ?

In the first initial implementation of it you will have to do it manually, but we will add more caching and will improve it further for more automation. And will document it of course. Will let you know asap. In the meantime you can emulate the same approach by just doing `fetch_open_orders()` + `fetch_balance()` in pairs sequentially. Let us know if you have more questions on this. Thx!
