### ISSUE TITLE
Kucoin: fetchBalance doesn't return the balances with marginMode cross

### ISSUE THREAD

**Issue by mjwvb** [ccxt/ccxt#21979]
### Operating System

MacOS

### Programming Languages

JavaScript

### CCXT Version

4.2.84

### Description

When fetching the balances for my cross margin account on Kucoin it returns no currencies at all. My code:
```javascript
const balance = await exchange.fetchBalance({ marginMode: "cross" });
// -->   { ..., "free": {}, "used": {}, "total": {} }
```

I'm pretty certain it has to do with this line:
https://github.com/ccxt/ccxt/blob/921aa4981b5cf8ec1a4190536024fd834fd1b5dc/ts/src/kucoin.ts#L3642

This line assumes an array as response which is true for normal spot accounts retrieved by privateGetAccounts(). But for data that is retrieved by privateGetMarginAccount(), it has an object as response:

```json
{
  "info": {
    "code": "200000",
    "data": {
      "debtRatio": "0.7913",
      "accounts": [...]
    }
  }
}
```

As a result it will never detect any currency balances.

**Comment by mjwvb** [comment]
Also, there seems to be some strange config tangling going on when using marginMode="cross" and/or type="cross".

This returns nothing, and uses privateGetMarginAccount:
```javascript
const balance = await exchange.fetchBalance({ marginMode: "cross" });
```

This returns the balances from my cross margin account, but **without** liabilities/debts as it uses privateGetAccounts:
```javascript
const balance = await exchange.fetchBalance({ type: "cross" });
```
I assume this is also incorrect, and I believe this has to do with the conversion by accountsByType, where "cross" is converted to "margin", and then the cross variable is not set to true and will go the spot account route using privateGetAccounts.

**Comment by carlosmiei** [comment]
Hello @mjwvb, thanks for reporting it, we will take a look

**Comment by Dan-krm** [comment]
@mjwvb thanks for the feedback, I opened a pull request that should fix the issues you've identified

**Comment by mjwvb** [comment]
Nice, thanks!

**Comment by carlosmiei** [comment]
@mjwvb Can you please update your ccxt version and try again? I believe it is working now
