### ISSUE TITLE
Kucoin doesn't work with the watch_order_book socket. 

### ISSUE THREAD

**Issue by Ispolin08** [ccxt/ccxt#21986]
### Operating System

docker

### Programming Languages

PHP

### CCXT Version

latest

### Description

Hi here
Getting error 
Warning: Attempt to read property "cache" on null in /app/vendor/ccxt/ccxt/php/pro/kucoin.php on line 622

Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /app/vendor/ccxt/ccxt/php/pro/kucoin.php:622

### Code

This needs to be added
```
if ($orderbook === null) {
            $orderbook = $this->order_book();
        }  

```

right after 
```

 public function handle_order_book(Client $client, $message) {
        $data = $this->safe_value($message, 'data');
        $subject = $this->safe_string($message, 'subject');
        $topic = $this->safe_string($message, 'topic');
        $topicParts = explode(':', $topic);
        $topicSymbol = $this->safe_string($topicParts, 1);
        $topicChannel = $this->safe_string($topicParts, 0);
        $marketId = $this->safe_string($data, 'symbol', $topicSymbol);
        $symbol = $this->safe_symbol($marketId, null, '-');
        $messageHash = 'orderbook:' . $symbol;
        $orderbook = $this->safe_dict($this->orderbooks, $symbol);

```
in
class kucoin extends \ccxt\async\kucoin {

**Comment by Ispolin08** [comment]
or even
        if ($orderbook === null) {
            $orderbook = $this->orderbooks[$symbol];
        }

**Comment by carlosmiei** [comment]
Hello @Ispolin08 , thanks a lot for reporting it, we will fix it asap.
