### ISSUE TITLE
Bitfinex WS

### ISSUE THREAD

**Issue by fredfortier** [ccxt/ccxt#2199]
Bitfinex has gone overly defensive on rate limits to the point where it's no longer usable to collect data.

I'm planning to use their WebSocket api but I wanted to first check if you had any experimental implementation of this in a separate branch.

**Comment by kroitor** [comment]
Hi!

I have it for JS here, but it... could be better, honestly: https://gist.github.com/kroitor/4d4638c0f6e89602105c6438f5acd057

And for Python we have a draft implementation submitted by @samholt here: 

- - https://github.com/ccxt/ccxt/pull/751
- https://github.com/ccxt/ccxt/pull/751/files#diff-a2d1059e79e4c1e2ad72d61229712de6
- https://github.com/ccxt/ccxt/pull/751/files#diff-46b65e72169bab627c2d5e53a7e82819
- https://github.com/ccxt/ccxt/pull/751/files#diff-5c1919d4d8d9922ea07016036e39d0dd

We are going to start pushing some WS-code after merging #2171 + #2121 + #1635 in several days. Those three pull requests are there to fix the issue you submitted previously on amount_to_lots as well as several other bugs here and there.

Hope it helps. Feel free to reopen it or just let us know if you still have questions on this.
