### ISSUE TITLE
Bitget watchorderbook bug - invalid checksum when watch_order_book

### ISSUE THREAD

**Issue by jparekh28** [ccxt/ccxt#21997]
### Operating System

Ubuntu 22.04

### Programming Languages

Python

### CCXT Version

4.2.85

### Description

Hello,

When watching for order book in Bitget exchange using ccxt pro (ccxt.pro) and watch_order_book function, I am getting the following error 

`bitget invalid checksum`

This was working fine till 4.2.72 to the best of my knowledge. This bug is similar to the closed issue `https://github.com/ccxt/ccxt/issues/18322` which was closed a year ago approximately. 

```python
orderbook = await exchange.watch_order_book(symbol)
```

### Code

```
  orderbook = await exchange.watch_order_book(symbol)

```

**Comment by jparekh28** [comment]
I would like to add that I am seeing this issue sometimes. I just tested the same code after 1 hour and it started working i.e it is not longer throwing me the error `bitget invalid checksum`

**Comment by jparekh28** [comment]
Ahh, again started seeing the issue 

```
ERROR | 2024-03-31 14:41:59,951 | LINE : 376 | - watch_order_book() | Error while watching order book: bitget invalid checksum
```

**Comment by jparekh28** [comment]
The symbol being tested was "BICO/USDT"

**Comment by carlosmiei** [comment]
Hello @jparekh28 thanks for reporting it, we will take a look and revert asap

**Comment by jparekh28** [comment]
Thank you @carlosmiei 

Let me know if you want any more clarity on how to reproduce it.

**Comment by jparekh28** [comment]
Checked today we well and we are still hitting this issue. Just for clarity, our location is India and accordindly our account with Bitget is for Indian region. I am not sure whether other folks from around the world who have account with Bitget in their respective locations are also hitting this issue or not. But we are definitely hitting this issue on "Indian" region - Bitget exchange

**Comment by pcriadoperez** [comment]
hi @jparekh28, 

I'm running it from my side to try and reproduce the error, but it hasn't happened so far.

How often does the error happen? Does it work to wrap the call in a try catch loop? So if the error happens it automatically reconnects?

**Comment by jparekh28** [comment]
Here is my code

```python
from ccxt import pro as ccxt_pro
import asyncio

    async def watch_order_book(self, exchange, symbol):
        try:
            logger.debug(f"Watching order book for exchange : {exchange.id} - symbol {symbol}")
            orderbook = await exchange.watch_order_book(symbol)
            response = {
                "exchange_name": exchange.id,
                "asks": orderbook["asks"][0][0],
                "bids": orderbook["bids"][0][0],
                "symbol": symbol,
            }
            return exchange.id, response
        except Exception as e:
            logger.error(f"Error while watching order book: {e}")
            return  
 
 tasks = []
 final_exchanges = []
 
 
 my_exchanges = ['binance', 'okx', 'bitget'] 
 
 # Exchange instances
 for each in my_exchanges:
      exchange_instance = getattr(ccxt_pro, exchange_name)()
      final_exchanges.append(exchange_instance)
      
  while True:
          for each_exchange in final_exchanges:
                    tasks.append(self.watch_order_book(each_exchange, symbol))

           # Using asyncio.gather to get a list of (exchange_name, result) tuples
           order_book_response = await asyncio.gather(*tasks)
           
           # other stuff .....
           await asyncio.sleep(5)
```

**Comment by jparekh28** [comment]
Hi @pcriadoperez 

We are seeing this issue every now and then (every 15-20 mins it suddenly starts working and suddently stops and starts throwing bitget invalid checksum)

We are using try catch for watch_order_book. 
The above code is working fine for all exchanges except bitget. We have 12 exchanges whose orderbook we try to get every 5 seconds.

**Comment by jparekh28** [comment]
Hi @pcriadoperez 

Were you able to reproduce the issue with my code or something like this ?

**Comment by jparekh28** [comment]
Hi @pcriadoperez 

Yes the code seems fine to reproduce. Let me know if you hit the issue when running for around 10-15 minutes.

**Comment by jparekh28** [comment]
Hi @pcriadoperez 

Were you able to reprroduce the issue ?

**Comment by chazman2** [comment]
I am getting the same issue. For me it begins after approximately 3 hours. Here is the relevant code extract, and the error message:

```
async def watch_orderbook(symbol, ex):
    while True:
        try:
            orderbook = await ex.watch_order_book(symbol)
            now = datetime.datetime.now()

            await asyncio.sleep(0)

        except Exception as e:
            error_msg = f"{datetime.datetime.now()} An error occurred (watch_orderbook({symbol}, {ex.name}, {q}): {e}\n"
            print(error_msg)
```

Error message (this invalid checksum error appeared continuously for about 2.5 hours). Note that it begins after an aiohttp error (cannot write to closing transport), which might be important.

2024-04-29 02:13:44.309010 An error occurred (watch_orderbook(FTM/USDT:USDT, Bitget, 20): Cannot write to closing transport
2024-04-29 02:13:45.348002 An error occurred (watch_orderbook(XRP/USDT:USDT, Bitget, 20): bitget invalid checksum
2024-04-29 02:13:45.348320 An error occurred (watch_orderbook(XRP/USDT:USDT, Bitget, 20): bitget invalid checksum
2024-04-29 02:13:45.348613 An error occurred (watch_orderbook(XRP/USDT:USDT, Bitget, 20): bitget invalid checksum
2024-04-29 02:13:45.348919 An error occurred (watch_orderbook(XRP/USDT:USDT, Bitget, 20): bitget invalid checksum

Then, no errors of any kind for 3 hours, before encountering another "cannot write to closing transport", followed by more invalid checksum errors which continue for 4 hours until I turn off the program.

2024-04-29 07:35:45.707813 An error occurred (watch_orderbook(MATIC/USDT:USDT, Bitget, 20): Cannot write to closing transport
2024-04-29 07:35:46.588027 An error occurred (watch_orderbook(FTM/USDT:USDT, Bitget, 20): bitget invalid checksum
2024-04-29 07:35:46.588063 An error occurred (watch_orderbook(XRP/USDT:USDT, Bitget, 20): bitget invalid checksum

**Comment by chazman2** [comment]
It has happened again. 

This time, the "bitget invalid checksum" error began approx. 9hrs into the script, and again occurred immediately after a "Cannot write to closing transport" error

So I believe this checksum error must be to do with how CCXT manages the Bitget WebSocket connection, and something is going wrong when CCXT closes the connection and attempts to reopen it (perhaps it is mistakenly using the old checksum instead of generating a new one for the new connection?). Again, both of the errors come from watch_orderbook().

**Comment by chazman2** [comment]
Hi Pablo and Carlos, thank you for attempting to fix this in the latest update. I appreciate your work. I am now using 4.3.18. Unfortunately, I am personally still experiencing the issue. Please see a traceback of my error (with my personal details removed):

An error occurred: bitget invalid checksum
Traceback:
Traceback (most recent call last):
  File "<file_path>", line 49, in watch_orderbook
    orderbook = await ex.watch_order_book(symbol)
  File "<file_path>", line 428, in watch_order_book
    return await self.watch_order_book_for_symbols([symbol], limit, params)
  File "<file_path>", line 461, in watch_order_book_for_symbols
    orderbook = await self.watch_public_multiple(messageHashes, topics, params)
  File "<file_path>", line 1554, in watch_public_multiple
    return await self.watch_multiple(url, messageHashes, message, messageHashes)
ccxt.base.errors.InvalidNonce: bitget invalid checksum

I believe this issue needs to be re-opened.
