### ISSUE TITLE
volume requested on bitfinex seems to be incomplete

### ISSUE THREAD

**Issue by fedecaccia** [ccxt/ccxt#2200]
- OS: ubuntu 16.04
- Programming Language version: python
- CCXT version: last
- Exchange: bitfinex
- Method: fetch_ohlcv

Requesting candles on bitfinex I get different values that I can see online on bitfinex platform. For example, I'm getting this candle:
2018-03-09 15:56:00    8869.000000  8869.100000  8862.000000  8862.100000 2.721108
which can be read as (open, high, low, close, volume)
but inspecting online I see:  8869  8869.1  8862  8862.1 5

I mean, volume is wrong (2.72 != 5).
Here is some code:
```
import ccxt, datetime, pandas, numpy
bitfinex = ccxt.bitfinex()
n_data = 100
since = bitfinex.milliseconds() - n_data*60*1000
res = bitfinex.fetch_ohlcv ("BTC/USD",  "1m",  since, n_data)

res = numpy.array(res)
res = res.transpose()
res = {"time": res[0], "open":res[1], "high":res[2], "low":res[3], "close":res[4], "volume":res[5]}
res = pandas.DataFrame(res)
res["time"] = res["time"].apply(lambda x: datetime.fromtimestamp(x/1000.0))
res = res.set_index("time")	
print(res)
```

**Comment by fedecaccia** [comment]
@kroitor don't worry, it's because 15:56 is the last minute. Data is just incomplete.

**Comment by kroitor** [comment]
@fedecaccia i'll add that to the Manual for less confusion, thx!

**Comment by fedecaccia** [comment]
Thanks to repply, but I don't understant  what means the "close" value? Is that just the "last"?

**Comment by kroitor** [comment]
@fedecaccia 

> what means the "close" value in the last candle? Is that just the "last"?

ohlc = prices (quote currency), v = volume (base currency).

**Comment by fedecaccia** [comment]
I get it, but what I don't understand is why, if the last "volume" is incomplete, we get the "close" value.

**Comment by kroitor** [comment]
@fedecaccia because the last volume is the total volume of all trades in that candle, thus, it accumulates over time, while the last price is the price of just one closing trade in that candle, it just jumps from one last price to the next and so on... Does this answer your question?

**Comment by fedecaccia** [comment]
Suppose we are requesting the last candle, for example, 16:41 candle. Right now it is 16:40:45 so that last candle is incomplete. We get (open, high1, low1, close1, volume1). Except for the "open" value, all the other values can be modified in future (I mean, in the next 15 secs). Suppose we request that candle one minute later, we get: (open, high2, low2, close2, volume2). So, I think that "close1" was, indeed, "last" value.
