### ISSUE TITLE
binance fetch_account_positions filters out zero maintenanceMargin positions

### ISSUE THREAD

**Issue by pennymax** [ccxt/ccxt#22005]
### Operating System

Ubuntu 22.04

### Programming Languages

Python

### CCXT Version

4.2.74

## Issue Description
I've observed a change in behavior in the binance fetch_account_positions function where positions with a zero maintenance margin are no longer returned. This behavior was introduced in the commit [29effaaf60d6746cc0db80c9f4115b40a01737a9](https://github.com/ccxt/ccxt/commit/29effaaf60d6746cc0db80c9f4115b40a01737a9), where positions are filtered out if their maintenance margin is '0' or '0.00000000'.

```
         if (maintenanceMargin != '0') and (maintenanceMargin != '0.00000000'):
                # sometimes not all the codes are correctly returned...
                if code in balances:
                    parsed = self.parse_account_position(self.extend(position, {
                        'crossMargin': balances[code]['crossMargin'],
                        'crossWalletBalance': balances[code]['crossWalletBalance'],
                    }), market)
                    result.append(parsed)
```

For certain use cases, including mine, having access to the full list of account positions, regardless of their maintenance margin, is crucial. Specifically, I need to adjust the margin type and leverage for all symbols within an account, which necessitates visibility into all positions, even those with zero maintenance margin.

## Questions
Alternative Functions: Are there alternative functions within CCXT that can be used to retrieve the full list of account positions, including those with a zero maintenance margin, other than resorting to the raw API call (e.g., 'fapiPrivateV2GetAccount')?

Feature Request: If no such alternative exists, could an option be introduced to include positions with zero maintenance margin in the results? This feature would greatly benefit scenarios where comprehensive account analysis is required, regardless of the maintenance margin status.

**Comment by carlosmiei** [comment]
Hello @pennymax,
Thanks for reporting it. Yes, I think we can just return all positions or make that optional through an option. We will check it and let you know as soon as possible.
