### ISSUE TITLE
unable to fetch position

### ISSUE THREAD

**Issue by RyanLiuQ** [ccxt/ccxt#22016]
### Operating System

windows 11

### Programming Languages

Python

### CCXT Version

4.2.87

### Description

using Cryptocom, 

I'm trying to get info on my current position in CRO/USD. I've tried with the code posted here. But I keep getting this error message. The commented code shows other options i've tried. But have gotten the same results. 

File "..\ccxt\cryptocom.py", line 2568, in fetch_position
    return self.parse_position(data[0], market)
                               ~~~~^^^
IndexError: list index out of range

### Code

# symbol = 'CRO/USD:USD'
symbol = 'CRO/USD'


# fetch = exchange.fetch_positions([symbol])
# print(fetch)

fetch = exchange.fetchPosition(symbol)
print(fetch)

**Comment by sc0Vu** [comment]
@RyanLiuQ, thanks, will fix this asap.

**Comment by carlosmiei** [comment]
@RyanLiuQ If you update your ccxt version, it should work now 🙂

**Comment by RyanLiuQ** [comment]
Thanks, I'm not getting the error anymore.

Ryan.
________________________________

**Comment by RyanLiuQ** [comment]
@carlosmiei  , I have another question about the fetchPosition function for Cryptocom. I am not getting an error anymore. But the result is continually empty. for example i am checking my BTC/USD position with the following code : 
symbol = 'BTC/USD'
fetch = exchange.fetchPosition(symbol)
print(fetch)

The result is : 
e', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400'} ResponseBody: {
  "id" : 1712083982400,
  "method" : "private/get-positions",
  "code" : 0,
  "result" : {
    "data" : [ ]
  }

But when I use the following function. I get info on my BTC/USD position. See below :  
balance = exchange.fetch_balance()
print(balance)

part of the result : 
{'quantity': '0.00015996', 'reserved_qty': '0', 'collateral_amount': '9.43996565', 'haircut': '0.1', 'collateral_eligible': True, 'market_value': '10.48885073', 'max_withdrawal_balance': '0.00015996', 'instrument_name': 'BTC', 'hourly_interest_rate': '0'}
