### ISSUE TITLE
Using macro substitution PHP

### ISSUE THREAD

**Issue by cryptonic203** [ccxt/ccxt#2202]
Hello.
I copied and tried to execute your code from Manual. There is an error on the second line of your code. What am I doing wrong?

//--PHP--
require_once 'ccxt/ccxt.php';

$id = 'huobi';
$huobi = new \ccxt\$id ();             //-Error: unexpected '$id' (T_VARIABLE), expecting identifier (T_STRING)
$markets = $huobi.load_markets ();
var_dump ($huobi->id, $markets);

I use a lot of exchanges, so I need this code to work correctly. Besides, only the following code works correctly: 

//--PHP--
require_once 'ccxt/ccxt.php';

$huobi = new \ccxt\huobi();
$markets = $huobi->load_markets ();  //--changed here "." to "->"
var_dump ($huobi->id, $markets);

**Comment by kroitor** [comment]
Hi!

> I copied and tried to execute your code from Manual. There is an error on the second line of your code. 

It's a typo in the Manual, see the [examples folder](https://github.com/ccxt/ccxt/tree/master/examples/php) on how to instantiate by `$id` properly, I'll update the Manual shortly. Let us know if it does not answer your question. Thx!
