### ISSUE TITLE
Invalid price for symbol ETHUSD Gemini

### ISSUE THREAD

**Issue by MP-AAMIR** [ccxt/ccxt#22025]
### Operating System

Linux

### Programming Languages

JavaScript

### CCXT Version

    "ccxt": "^4.2.64",

### Description

data: {
      result: 'error',
      reason: 'InvalidPrice',
      message: 'Invalid price for symbol ETHUSD: 3314.00'
    }
    
    
**This is happening with Gemini createOrder**

Creating order: {
  nonce: '1712059999',
  request: '/v1/order/new',
  symbol: 'ethusd',
  amount: '0.001032',
  price: '3314.00',
  side: 'sell',
  type: 'exchange stop limit',
  stop_price: '3319.00'
}

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @MP-AAMIR, thanks for reporting it, we will take a look 
\cc @ttodua

**Comment by ttodua** [comment]
I'll post an update soon.

**Comment by ttodua** [comment]
@MP-AAMIR can you provide the code that you executed? i.e. `exchange.createOrder (...what params here...)`

**Comment by MP-AAMIR** [comment]
Creating order: {
nonce: '1712059999',
request: '/v1/order/new',
symbol: 'ethusd',
amount: '0.001032',
price: '3314.00',
side: 'sell',
type: 'exchange stop limit',
stop_price: '3319.00'
}
this is the payload @ttodua

**Comment by ttodua** [comment]
what ccxt code do you use?

**Comment by MP-AAMIR** [comment]
await gemini.createOrder('ethusd','limit','sell',0.001032,3300.00,{stopLoss:3327.95})

**Comment by ttodua** [comment]
ok, that's i wanted. please include all such details when opening the issue.
 let me check and I'll post an update.

**Comment by ttodua** [comment]
I'll advise two things:
1) update CCXT to latest version (because you have old version, after that version gemini was updated in ccxt)
2) try to use correct amounts. when sending order for `0.001032` amount, you should get error saying that the minimum amount to trade is `0.01` for that market.

**Comment by ttodua** [comment]
I've edited the above comment a bit, the linked PR would fix amount precison too

**Comment by ttodua** [comment]
@MP-AAMIR the fix was merged, after new package is pushed to npmjs repository (probably in several hours), then update your ccxt and let us know if you face any issues again.
