### ISSUE TITLE
Kucoin Pro: support for top 1 best ask and bid websocket

### ISSUE THREAD

**Issue by mjwvb** [ccxt/ccxt#22038]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Describe the solution you'd like

Kucoin supports subscribing to the best ask and bid of up to 100 symbols per topic, so basically 1 level deep order book. See:
https://www.kucoin.com/docs/websocket/spot-trading/public-channels/level1-bbo-market-data

Ccxt only supports subscribing to best 5, best 50, or the complete order book. The best 5 and 50 websockets are pushed at a 100ms interval. The top 1 best ask and bid are pushed at a 10ms interval, and in some use cases the top 1 is more than enough and thus preferred due to low latency. The format of the output looks the same as the top 5 and 50 so it should be fairly simple to implement based on the others.

**Comment by carlosmiei** [comment]
Hello @mjwvb, thanks for letting us know, we will try to implement it shortly.
cc/ @ttodua

**Comment by ttodua** [comment]
I'll post an update in few mins

**Comment by ttodua** [comment]
@mjwvb the update is on the way, once it gets merged and this issue will be autoclosed, in several hours after that keep an eye for ccxt version update and then download new version, it would be fixed.
