### ISSUE TITLE
Does this work with binance.us? ExchangeError: binanceus {"code":-71012,"msg":"IPv6 not supported"}

### ISSUE THREAD

**Issue by ameshkin** [ccxt/ccxt#22044]
### CCXT Version

4.2.88

### Description

I am getting this error when trying to connect to binance usa. Is that even possible?

ExchangeError: binanceus {"code":-71012,"msg":"IPv6 not supported"}

I've tried 1.38.34 and the very latest one. 4.2.88

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @ameshkin, unfortunately i don't think that binance.us supports requests over ipv6, and that's not related to ccxt, there are multiple reports stating the same, for example:

https://www.reddit.com/r/getdelta/comments/lj8tnx/cant_connect_binanceus_exchange_account/

**Comment by ameshkin** [comment]
> https://www.reddit.com/r/getdelta/comments/lj8tnx/cant_connect_binanceus_exchange_account/

I am not the most technical person. Do I need to use a proxy? How can I fix this?

**Comment by ameshkin** [comment]
Thank you. When I got home I was able to read the reddit comments and I downloaded a vpn.
