### ISSUE TITLE
New Exchange: ox.fun

### ISSUE THREAD

**Issue by followyourfun** [ccxt/ccxt#22054]
### Exchange Name

ox.fun

### URL of the Exchange

https://ox.fun

### URL of the Exchange's API docs

https://docs.ox.fun/

### Why should this exchange be implemented?

As noted from the domain of the exchange, the goal is to have fun. The team at ox.fun has made things simple yet fun like a normal game instead of constantly spamming popups that 'normal' users cannot obtain. I especially like the exchange because my personal email is s@followyour.fun and feel like that the exchange was made for me, which obviously isn't. It's founded by the Three Arrows Capital founders and I truly believe that after their wipe out, they are motivated and almost destined to build the next big thing. Hence, I will be devoting 100% of my time trying to update their CCTX docs, even though I don't know how to do it yet. Their docs were easy to understand for a beginner and I was able to jump from being a Excel VBA programmer to a python/websocket coder. I hope this is my next leg up into becoming an up and coming coder in the space.

**Comment by followyourfun** [comment]
can i just start doing it without anyone's permission?

**Comment by carlosmiei** [comment]
@followyourfun We're working on it right now.
