### ISSUE TITLE
PHP TypeError invalid returntype for Binance

### ISSUE THREAD

**Issue by Trekels** [ccxt/ccxt#22057]
### Operating System

Linux

### Programming Languages

PHP

### CCXT Version

4.2.89

### Description

The return value of null does not match the function signature for `fetch_currencies` only array is allowed.

The return typehint is introduced as of version 4.2.89 

### Code

> /ccxt/php/binance.php::2609

```
      public function fetch_currencies($params = array ()): array {
        /**
         * fetches all available currencies on an exchange
         * @see https://binance-docs.github.io/apidocs/spot/en/#all-coins-39-information-user_data
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} an associative dictionary of currencies
         */
        $fetchCurrenciesEnabled = $this->safe_value($this->options, 'fetchCurrencies');
        if (!$fetchCurrenciesEnabled) {
            return null;
        }
...

```

**Comment by carlosmiei** [comment]
Hello @Trekels, thanks a lot for letting us know we will patch it as soon as possible.

**Comment by maddrid** [comment]
i think  is  related  
  TypeError: ccxt\binance::fetch_currencies(): Return value must be of type array, null returned vendor\ccxt\ccxt\php\binance.php on line 2616
  TypeError: ccxt\bybit::fetch_currencies(): Return value must be of type array, null returned in file  vendor\ccxt\ccxt\php\bybit.php on line 1294

**Comment by carlosmiei** [comment]
@maddrid Thanks for reporting it, we will deploy a fix shortly.
