### ISSUE TITLE
OKX fetchMyTrades parses response as empty list while result contains trades

### ISSUE THREAD

**Issue by fl0wo** [ccxt/ccxt#22053]
### Operating System

MacOs/Linux

### CCXT Version

4.2.88

### Description

Hi,

`okx.fetchMyTrades("ETH/USDC") ` is returning an empty list []

But when logging the HTTP call I can see the data:

```

last_request_url: https://www.okx.com/api/v5/trade/fills-history?instId=ETH-USDC&instType=SPOT&limit%5Binvalid_cache%5D=1712251614247

last_json_response: {
  code: '0',
  data: [
    {
      side: 'sell',
      fillSz: '0.00301',
      fillPx: '3386.56',
      fillPxVol: '',
      fillFwdPx: '',
      fee: '-0.00713548192',
      fillPnl: '0',
      ordId: 'xxx',
      feeRate: '-0.0007',
      instType: 'SPOT',
      fillPxUsd: '',
      instId: 'ETH-USDC',
      clOrdId: 'xxx',
      posSide: 'net',
      billId: 'xxx',
      fillMarkVol: '',
      tag: 'xxx',
      fillTime: '1712247773625',
      execType: 'T',
      fillIdxPx: '3385.79',
      tradeId: '22570701',
      fillMarkPx: '',
      feeCcy: 'USDC',
      ts: '1712247773627'
    },
    {
      side: 'buy',
      fillSz: '0.005316',
      fillPx: '3287.49',
      fillPxVol: '',
      fillFwdPx: '',
      ....
```

But then I get in return of the function:
`
[]`

What I'm doing wrong? The httpcall returns correctly the fields, is there an error on the parsing side?

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @fl0wo, can you please enable the verbose mode (after doing `loadMarkets()`) and post the full HTTP request+response?

**Comment by fl0wo** [comment]
[empty-trades-response-okx.json](https://github.com/ccxt/ccxt/files/14875654/x.json)


Hi, sure, thanks for having a look into this.

**Comment by rayBastard** [comment]
HI @fl0wo, we are checking what the problem at nearest time.

**Comment by rayBastard** [comment]
Hi @fl0wo, I have checked method and everything seems to be ok. Can you demonstrate the code you used?

**Comment by fl0wo** [comment]
Hi @rayBastard , I'm calling the fetchMyTrades functions exactly as in the doc:

`okx.fetchMyTrades('ETH/USDC', new Date('Mon Mar 25 2024 20:03:46 GMT+0000').getTime(), 1000, { invalid_cache: Date.now() })
`
The point is: The api-call is correct, and OKX returns the data correctly, but then for some reason I receive an empty array as returned object...

I'm using 4.2.88 version of ccxt, but also down-grading I see the same behaviour. Maybe something has changed in the OKX response?

I've attatched in the previous comment both request and response.

**Comment by rayBastard** [comment]
@fl0wo I will check it asap and then return with response

**Comment by kroitor** [comment]
@fl0wo please, always post your complete code as documented in the FAQ: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

Run this snippet on your side:

```JavaScript
const ccxt = require('ccxt');
console.log('CCXT Version:', ccxt.version)

async function main() {
    const exchange = new ccxt.okx({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_API_SECRET',
    })
    await exchange.loadMarkets()
    // exchange.verbose = true // uncomment this line for debugging
    const trades = await exchange.fetchMyTrades('ETH/USDC', exchange.parse8601 ('2024-03-25T20:03:46'))
    console.log(trades)
    console.log('Received', trades.length, 'trades')
}

main();
```

If the code snippet above prints `Received 0 trades`, then uncomment the `exchange.verbose = true` line, run it again and copypaste the complete output of this code into this issue.

**Comment by kroitor** [comment]
@fl0wo also, plz don't cut the output, copypaste the complete output as is including the request and the response.

**Comment by fl0wo** [comment]
It was an issue on my side, my bad.

Closing as not an issue.

**Comment by rayBastard** [comment]
@fl0wo no worries! If you have any other issues, please contact.
