### ISSUE TITLE
OKX fetchOrder : TypeError symbol.endsWith is not a function

### ISSUE THREAD

**Issue by fl0wo** [ccxt/ccxt#22051]
### Operating System

MacOs/Linux

### CCXT Version

4.2.88

### Description

Hi, when I run fetchOrder using okx I'm hitting the following error:

To reproduce:
`exchange.fetchOrder(idOrder, "BTC/USDT", params);
`

```
        else if ((symbol.endsWith('-C')) || (symbol.endsWith('-P')) || (symbol.startsWith('C-')) || (symbol.startsWith('P-'))) {
                         ^
TypeError: symbol.endsWith is not a function
    at okx.market (/Users/xx/WebstormProjects/xx/node_modules/ccxt/dist/cjs/src/base/Exchange.js:4560:26)
    at okx.fetchOrder (/Users/xx/WebstormProjects/xx/node_modules/ccxt/dist/cjs/src/okx.js:3517:29)
```

I think the symbol parameter on OKX is passed (otherwise I'd get an undefined error), but seems that js .endsWith might not recognize it as method?

https://stackoverflow.com/questions/18768344/javascript-endswith-function-not-working

Maybe replacing "endsWith" with a in-house regexp check function would do the trick?

Thanks for helping.

### Code

```
  

```

**Comment by fl0wo** [comment]
For reference:

`okx.fetchClosedOrders("BTC/USDT")`
works perfectly.

The main issue is on _**fetchOrder**_ method.

**Comment by fl0wo** [comment]
Ok weird enough, seem I've fixed it doing:

_.fetchOrder(order.id,`${order.symbol}`);_

Seems that my "symbol" object, was not a Javascript String, but serialized as it was.

Therefor it was a problem on my side, closing as not an issue.

**Comment by carlosmiei** [comment]
@fl0wo Thanks for confirming it!
