### ISSUE TITLE
gemini: new '*' appended to market name in https://docs.gemini.com/rest-api/ needs to be trimmed

### ISSUE THREAD

**Issue by blair** [ccxt/ccxt#22064]
### Operating System

macOs

### Programming Languages

JavaScript

### CCXT Version

4.2.90

### Description

https://docs.gemini.com/rest-api/#symbols-and-minimums is used by `fetchMarketsFromWeb()` and it appears the webpage just added a `*` to some markets:

```
usdtusd*	0.1 USDT (1e-1)	0.000001 USDT (1e-6)	0.0001 USD (1e-4)
```

```
*Note: Not available to trade for customers in New York
```

This breaks `#fetchOHLCV` since it tries to get https://api.gemini.com/v2/candles/btcusd*/1m.

The fix appears to be in this code

```
    async fetchMarketsFromWeb (params = {}) {
...
            //     [
            //         '<td>btcusd', // currency
            //         '<td>0.00001 BTC (1e-5)', // min order size
            //         '<td>0.00000001 BTC (1e-8)', // tick size
            //         '<td>0.01 USD', // quote currency price increment
            //         '</tr>'
            //     ]
            const marketId = cells[0].replace ('<td>', '');
```

Adding another `.replace(/\*+$/, '')` to the `marketId`.

### Code

```
  

```

**Comment by sc0Vu** [comment]
@blair thanks, will fix this asap.
