### ISSUE TITLE
BitMex is marked to support watchTradesForSymbols but it doesn't

### ISSUE THREAD

**Issue by hodlerhacks** [ccxt/ccxt#22070]
### Operating System

Windows

### Programming Languages

JavaScript

### CCXT Version

4.2.90

### Description

exchange.has['watchTradesForSymbols'] returns true for BitMex, but when using that function, a 'bitmex watchTradesForSymbols() is not supported yet' exception is thrown.

### Code

```
  

```

**Comment by rayBastard** [comment]
Hello @hodlerhacks, I checked and bitmex.has['watchTradesForSymbols'] returns 'undefined' and is not supported by exchange yet. 
```
  ...
  watchTickers: undefined,
  watchTrades: undefined,
  watchTradesForSymbols: undefined,
  withdraw: true,
  ...
```

Could you show console.log where exchange.has returns true?

**Comment by hodlerhacks** [comment]
Hi @rayBastard, thanks for your quick response! I have a piece of code that I use to check which exchanges have which capabilities:

```
const ccxt = require('ccxt');

supportedExchanges();

function supportedExchanges() {
    const capabilities = [
        'ws',
        'watchTradesForSymbols',
    ];

    let supported = [];

    let exchanges = [];
    let exch = ccxt.pro.exchanges;

    exch.forEach(id => {
        try {
            const e = new ccxt.pro[id];
            exchanges.push(e);
        } catch (err) {
            console.log(`'${id}' is an unknown exchange`);
        }
    });

    exchanges.forEach(exchange => {
        let num = 0;
        capabilities.forEach(key => {
            if (key in exchange.has && exchange.has[key]) {
                num++;
            }
        });

        if (num == capabilities.length) {
            supported.push((exchange.id));
        }
    });

    console.log('Supported exchanges:');
    console.log(supported);

    let notsupported = [];

    exch.forEach(id => {
        if (!supported.includes(id)) notsupported.push(id);
    })

    console.log('Unsupported exchanges:');
    console.log(notsupported);
}
```

And this returns bitmex as a supported exchange:

```
Supported exchanges:
[
  'binance',     'binanceus',
  'binanceusdm', 'bitget',
  'bitmart',     'bitmex',
  'bybit',       'coinbaseinternational',
  'coinbasepro', 'cryptocom',
  'deribit',     'gate',
  'gateio',      'gemini',
  'kucoin',      'kucoinfutures',
  'okx'
]
```

In my production code, I use exchange.has['watchTradesForSymbols'] and if true, I use watchTradesForSymbols(), otherwise watchTrades(). For bitmex, it uses watchTradesForSymbols().

Am I making a mistake somewhere?

**Comment by kroitor** [comment]
@rayBastard @hodlerhacks i've tried with this shorter code and BitMEX indeed has the `watchTradesForSymbols` capability is set to true without an implementation of the corresponding method. This may be a bug, we will fix it shortly.

**Comment by carlosmiei** [comment]
@hodlerhacks We had it in the past yes, but we had to remove it due to a technical issue but we will restore it as soon as possible.

**Comment by hodlerhacks** [comment]
Thanks all!

**Comment by carlosmiei** [comment]
@hodlerhacks Can you update your ccxt version and try again? It should be available now

**Comment by hodlerhacks** [comment]
Thanks for the quick support, and that on a Sunday! :-) I don't have a BitMex account myself, but one of the users of my application does (he found the issue). I've asked him to give it a try. Will report back here as soon as I have his confirmation.

**Comment by carlosmiei** [comment]
@hodlerhacks No problem 🙂 , just let us know if anything!

**Comment by hodlerhacks** [comment]
The good news: the 'not supported' error is gone. The not so good news: I use the function to get the latest price for a range of symbols, but it seems the prices are not being updated. Have you seen this working with continuous updates?

**Comment by hodlerhacks** [comment]
Yes, it's all working now! At first, it seemed that prices where not being updated, but it turns out the volume on BitMex is just very low, and updates are coming in only now and then. Thanks for the quick fix!
