### ISSUE TITLE
`define_rest_api` method missing cause error thrown when unserializing

### ISSUE THREAD

**Issue by Lorca-R** [ccxt/ccxt#22076]
### Operating System

Ubuntu

### Programming Languages

PHP

### CCXT Version

4.2.90

### Description

Hi there, many thanks to this great project.

The [define_rest_api](https://github.com/ccxt/ccxt/blob/6628f54c1c3abee7965d2ae2ac9aa5b408eb0f59/php/Exchange.php#L1703) method no longer exists, causing an error when the instance is unserialized. 

It appears we neglected to remove define_rest_api in this commit https://github.com/ccxt/ccxt/commit/30669190b87041f4bc7e77f2d769dfd80a694688

Also issue https://github.com/ccxt/ccxt/issues/18698 might be related to this bug.

### Code

```php
$obj = new \ccxt\htx();
unserialize(serialize($obj)); // will throw error:  ccxt\ExchangeError  define_rest_api method not found, try underscore_notation instead of camelCase for the method being called.

```

**Comment by sc0Vu** [comment]
@Lorca-R thanks, will fix this asap.
