### ISSUE TITLE
WebSocket feature of ccxtPro

### ISSUE THREAD

**Issue by iockx** [ccxt/ccxt#22074]
### Operating System

windows11

### Programming Languages

Python

### CCXT Version

4.2.82

### Description

CCxt version 4.2.82
CcxtPro version 1.0.1
Python version 3.9.7

I have read the document, but because my English is not very good, I would like to ask if all the WebSocket functions of ccxtpro are now free?
From the document, I believe it was previously paid for, but now it is completely free to use. Is that correct?

Thank you for your answer

### Code

```
  

```

**Comment by sc0Vu** [comment]
@iockx yes it's open sourced. You can find examples here: https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro
