### ISSUE TITLE
CoinEgg supports 'fetchTickers' but 'hasFetchTickers' is false.

### ISSUE THREAD

**Issue by atjason** [ccxt/ccxt#2207]
Hi,
CoinEgg supports `fetchTickers` (as could be found in [coinegg.js](https://github.com/ccxt/ccxt/blob/master/js/coinegg.js)). I test and find it could correctly get prices of all the symbols.

But `exchange.hasFetchTickers` is false. Please help to check. Thanks in advance.

Let me know if I need to provide demo code or other information.

**Comment by kroitor** [comment]
@atjason the `.hasFetchTickers` was deprecated, use `.has['fetchTickers']` instead as well as other fields in the `.has` assoc array. Thx for reporting!

**Comment by atjason** [comment]
@kroitor Thanks for your reply. Sorry but when I test, coinegg's `.has['fetchTickers']` is `false` either, while in fact it could correctly call function `fetchTickers`. Please help to check, thanks.

**Comment by kroitor** [comment]
@atjason have you updated ccxt to the most recent version?

**Comment by atjason** [comment]
@kroitor I just update ccxt from `1.11.58` to `1.11.69`. Now it's `true`. Thanks for your help and swift reply.
