### ISSUE TITLE
Error retrieving open Interest (Binance)

### ISSUE THREAD

**Issue by mmehrle** [ccxt/ccxt#22083]
### Operating System

Mac

### Programming Languages

Python

### CCXT Version

4.2.9

### Description

Please see the example code snippet below:

`
            start_date_str = datetime.utcnow().strftime("%Y/%m/%d")

            start_time = int(datetime.strptime(start_date_str, '%Y/%m/%d').timestamp()) * 1000

            now = exchange.milliseconds()

            oi_series = exchange.fetchOpenInterestHistory(pair, timeframe=timeframe, since=start_time, limit=oi_window, params={'endtime': now})
`
This produces an error: 

> oi_series = exchange.fetch_futures_open_interest(pair, limit=oi_window)
> AttributeError: 'binance' object has no attribute 'fetch_futures_open_interest'

I have not tried any other exchanges but assume that the call is the same no matter which exchange. Thanks for any pointers in advance.

### Code

```
  

```

**Comment by pcriadoperez** [comment]
Hi @mmehrle,

ccxt does not have a function `fetch_futures_open_interest`  did you mean to use `fetch_open_interest` ?

**Comment by mmehrle** [comment]
> Hi @mmehrle,
> 
> ccxt does not have a function `fetch_futures_open_interest` did you mean to use `fetch_open_interest` ?

Not sure how that one slipped in. The code I posted mentioned fetchOpenInterestHistory.

**Comment by mmehrle** [comment]
Okay not sure what/why/how but I got this call to work:

fetchOpenInterestHistory()

Thanks for the help everyone.
