### ISSUE TITLE
Issues with the integration of Bitget exchange ws

### ISSUE THREAD

**Issue by iockx** [ccxt/ccxt#22088]
### Operating System

Windows11

### Programming Languages

Python

### CCXT Version

4.2.86

### Description

Prior to this, we had successfully connected to the Gate exchange, but there were some issues encountered while connecting to the bitgate exchange

So, I think my network proxy is fine

Before asking a question, I saw a friend say that Bitnet Exchange does not support ws, but the document indicates that it is supported, so I am not sure which one is correct

### Code

```
import ccxt.pro as ccxt

bitget_exchange = ccxt.bitget({
    'apiKey': '',
    'secret': '',
    'password': '',
    'timeout': 15000,
    'enableRateLimit': True,
    'proxies': {'https': "http://127.0.0.1:7890", 'http': "http://127.0.0.1:7890"}
})

# This method prints abnormally: bitget GET https://api.bitget.com/api/v2/spot/public/coins
try:
    trades = await bitget_exchange.watch_order_book(symbol)
    print(trades)
except Exception as e:
    print(e)

#  This method prints abnormally:Cannot connect to host ws.bitget.com:443 ssl:default [远程主机强迫关闭了一个现有的连接。]
try:
    balance = await bitget_exchange.watch_balance()
    print(balance)
except Exception as e:
    print(e)
```

**Comment by iockx** [comment]
I tried the watchreorder_book method of Bitmart Exchange again, but the same exception occurred: Bitmart GET https://api-cloud.bitmart.com/spot/v1/currencies ，It feels strange

**Comment by carlosmiei** [comment]
Hello @iockx, yes bitget supports WS.

Can you try to set up the proxy using the unified way: https://docs.ccxt.com/#/README?id=proxy ?

**Comment by iockx** [comment]
> Hello @iockx, yes bitget supports WS.
> 
> Can you try to set up the proxy using the unified way: https://docs.ccxt.com/#/README?id=proxy ?

Supporting ws links is great
Also, when you mention using a unified proxy, do you mean socksProxy and wsSocksProxy?

**Comment by iockx** [comment]
> Hello @iockx, yes bitget supports WS.
> 
> Can you try to set up the proxy using the unified way: https://docs.ccxt.com/#/README?id=proxy ?

I saw the proxy for ws and modified the code according to the documentation. Currently, my code is as follows:

```python
import ccxt.pro as ccxt
bitget_exchange = ccxt.bitget({
    'apiKey': '',
    'secret': '',
    'password': '',
    'timeout': 15000,
    'enableRateLimit': True,
    'proxies': {'https': "http://127.0.0.1:7890", 'http': "http://127.0.0.1:7890"},
    'wsSocksProxy': "socks5://name:password@ip:port",
    'wsProxy': "socks5://name:password@ip:port"
})

trades = await bitget_exchange.watch_order_book(symbol)

```
However, the output exception is:
```
bitget GET https://api.bitget.com/api/v2/spot/public/coins
```
It's not that the link timed out, there's currently no clue
I've been searching for a solution here for a long time

To be honest, I just want to know if there are any issues with my code. If there are no issues, I will replace it with another IP proxy and try replacing it with more IP proxies

**Comment by carlosmiei** [comment]
@iockx the only deprecated option i see is `proxies`, now you should use the property `httpProxy/httpsProxy`

**Comment by iockx** [comment]
> @iockx the only deprecated option i see is `proxies`, now you should use the property `httpProxy/httpsProxy`

Indeed, I have removed the proxies parameter. Thank you for your patience
