### ISSUE TITLE
Mexc can't put a stop loss order

### ISSUE THREAD

**Issue by swiinger** [ccxt/ccxt#22104]
### Operating System

windows 11

### Programming Languages

Python

### CCXT Version

3.1.50

### Description

hello,

I would like to create a Stop-Limit order but it's always a Limit order which is created
I've tried using parameters but mexc is still creating a Limit order with no stop loss and no trigger price
It looks like neither stopPrice nor triggerPrice is taken into account

any thoughts ?

thanks

{'id': 'C02__406344578380128256053', 'clientOrderId': None, 'timestamp': 1712662332869, 'datetime': '2024-04-09T11:32:12.869Z', 'lastTradeTimestamp': None, 'status': None, 'symbol': 'NTX/USDT', 'type': 'limit', 'timeInForce': None, 'side': 'sell', 'price': 0.1, 'stopPrice': None, 'triggerPrice': None, 'average': None, 'amount': 63, 'cost': None, 'filled': None, 'remaining': None, 'fee': None, 'trades': [], 'info': {'symbol': 'NTXUSDT', 'orderId': 'C02__406344578380128256053', 'orderListId': '-1', 'price': '0.1', 'origQty': '63', 'type': 'LIMIT', 'side': 'SELL', 'transactTime': '1712662332869'}, 'fees': [], 'lastUpdateTimestamp': None, 'postOnly': None, 'reduceOnly': None, 'takeProfitPrice': None, 'stopLossPrice': None}

### Code

```
params = {
    'triggerPrice': 0.045,
    'triggerDirection': 'below', # order will be triggered when price is above 1700
    'stopPrice': 0.035,  # your stop loss price
    'stopLoss': {
        'type': 'limit',# or 'market', this field is not necessary if limit price is specified
        'price': 0.035, # limit price for a limit stop loss order
        'triggerPrice': 0.04,
        'stopPrice': 0.035,
    }
    }
```
    
    order = exchange.create_order('NTXUSDT', 'limit','sell', 150, 0.035, params)

**Comment by sc0Vu** [comment]
@swiinger do you create order in spot market? I think mexc doesn't support stop order for spot.

**Comment by swiinger** [comment]
@sc0Vu : thanks for pointing out : yes it's for spot
it's more clear now that this platform is way too restricted...

**Comment by sc0Vu** [comment]
@swiinger yup, the function depends on exchange api. Let me know if you have any other issue.
