### ISSUE TITLE
gemini market parsing code mis-parses paxgusd

### ISSUE THREAD

**Issue by blair** [ccxt/ccxt#22113]
### Operating System

macOS

### Programming Languages

JavaScript

### CCXT Version

4.2.94

### Description

The new market parsing code in https://github.com/ccxt/ccxt/commit/2aefe755aa23cfbbf87fbc1207b3e3020ce84041 will misparse the `PAXGUSD` as `PAX/GUSD` rather than `PAXG/USD`.

This is due to 

```
                    'quoteCurrencies': [ 'USDT', 'GUSD', 'USD', 'DAI', 'EUR', 'GBP', 'SGD', 'BTC', 'ETH', 'LTC', 'BCH' ],
```

listing `GUSD` before `USD`. Unfortunately, changing the order would have `USD` always match before `GUSD` and shadow it.

Are there any actual GUSD spot markets though, so potentially `GUSD` this could be removed?

cc @ttodua

### Code

```
  

```

**Comment by blair** [comment]
```
$ curl -s https://api.gemini.com/v1/symbols/details/paxgusd | python3 -mjson.tool
{
    "symbol": "PAXGUSD",
    "base_currency": "PAXG",
    "quote_currency": "USD",
    "tick_size": 1e-08,
    "quote_increment": 0.01,
    "min_order_size": "0.0001",
    "status": "open",
    "wrap_enabled": false,
    "product_type": "spot",
    "contract_type": "vanilla",
    "contract_price_currency": "USD"
}
```

**Comment by blair** [comment]
Never mind, there's the `btcgusd` market which is `BTC/GUSD`. ```
curl -s curl https://api.gemini.com/v1/symbols/details/btcgusd | python3 -mjson.tool
{
    "symbol": "BTCGUSD",
    "base_currency": "BTC",
    "quote_currency": "GUSD",
    "tick_size": 1e-08,
    "quote_increment": 0.01,
    "min_order_size": "0.00001",
    "status": "open",
    "wrap_enabled": false,
    "product_type": "spot",
    "contract_type": "vanilla",
    "contract_price_currency": "GUSD"
}
```

This looks like a generally hard problem to solve without getting the actual market details.

Maybe the code should try to combine all combinations `quoteCurrencies` and if it matches, then it knows it's a pairing like `BTC/GUSD`, but if not, then it only uses a fiat currency such as `USD`.

**Comment by blair** [comment]
For myself to work around this for now, I'm using a patch like:

```
diff --git a/ts/src/gemini.ts b/ts/src/gemini.ts
index e6e84209b1..77820bf7ae 100644
--- a/ts/src/gemini.ts
+++ b/ts/src/gemini.ts
@@ -261,6 +261,7 @@ export default class gemini extends Exchange {
                 'fetchMarketsFromAPI': {
                     'fetchDetailsForAllSymbols': false,
                     'quoteCurrencies': [ 'USDT', 'GUSD', 'USD', 'DAI', 'EUR', 'GBP', 'SGD', 'BTC', 'ETH', 'LTC', 'BCH' ],
+                    'usdMarkets': [ 'PAXGUSD' ],
                 },
                 'fetchMarkets': {
                     'webApiEnable': true, // fetches from WEB
@@ -686,8 +687,14 @@ export default class gemini extends Exchange {
             const isPerp = (marketIdUpper.indexOf ('PERP') >= 0);
             const marketIdWithoutPerp = marketIdUpper.replace ('PERP', '');
             const quoteQurrencies = this.handleOption ('fetchMarketsFromAPI', 'quoteCurrencies', []);
+            const usdMarkets = this.handleOption ('fetchMarketsFromAPI', 'usdMarkets', []);
             for (let i = 0; i < quoteQurrencies.length; i++) {
                 const quoteCurrency = quoteQurrencies[i];
+                // Support markets like PAXGUSD which is PAXG/USD and
+                // not PAX/GUSD.
+                if (quoteCurrency !== 'USD' && usdMarkets.includes (marketIdWithoutPerp)) {
+                    continue;
+                }
                 if (marketIdWithoutPerp.endsWith (quoteCurrency)) {
                     baseId = marketIdWithoutPerp.replace (quoteCurrency, '');
                     quoteId = quoteCurrency;

```

**Comment by blair** [comment]
Thanks for quickly responding.

#22112  fixes the `USDCUSD` case, but it doesn't solve the case where a symbol ends in 'G' and it's in a USD market.

For example, these two need to parse differently. In the first case, the 'G' is part of the quote currency, in the second, the 'G' is part of the base currency.

- `btcgusd` => `BTC/GUSD`
- `paxgusd` => `PAXG/USD`

**Comment by blair** [comment]
The issue is the eager matching due to this order in `ts/src/gemini.ts`:

```
                    'quoteCurrencies': [ 'USDT', 'GUSD', 'USD', 'DAI', 'EUR', 'GBP', 'SGD', 'BTC', 'ETH', 'LTC', 'BCH' ],
```

Swapping the order of `GUSD` and `USD` won't fix the issue.

**Comment by carlosmiei** [comment]
@blair I just tested and `BTC/GUSD`  /  `PAXGUS` seems to be working 🤔 
```
n gemini fetchTicker "BTC/GUSD"
Debugger attached.
2024-04-12T08:39:16.265Z
Node.js: v18.18.0
CCXT v4.2.95
gemini.fetchTicker (BTC/GUSD)
2024-04-12T08:39:18.524Z iteration 0 passed in 632 ms

{
  symbol: 'BTC/GUSD',
  timestamp: 1712911158000,
  datetime: '2024-04-12T08:39:18.000Z',
  bid: 70756.04,
  ask: 70761.4,
  vwap: 70870.97,
  close: 70870.97,
  last: 70870.97,
  baseVolume: 0.64373428,
  quoteVolume: 45622.0728458516,
  info: {
    bid: '70756.04',
    ask: '70761.40',
    last: '70870.97',
    volume: {
      BTC: '0.64373428',
      GUSD: '45622.0728458
```
```
n gemini fetchTicker "paxgusd" 
Debugger attached.
2024-04-12T08:40:15.152Z
Node.js: v18.18.0
CCXT v4.2.95
gemini.fetchTicker (paxgusd)
2024-04-12T08:40:17.306Z iteration 0 passed in 630 ms

{
  symbol: 'PAX/GUSD',
  timestamp: 1712911217000,
  datetime: '2024-04-12T08:40:17.000Z',
  bid: 2391.75,
  ask: 2392,
  close: 2392,
  last: 2392,
  info: {
    bid: '2391.75',
    ask: '2392.00',
    last: '2392.00',
    volume: {
      PAXG: '111.34037958',
      USD: '266326.18795536',
      timestamp: '1712911217000'
    }
  }
}
```

Are you aware of any other non working symbol?

**Comment by blair** [comment]
@carlosmiei You can see the issue with "paxgusd" by looking only at these lines from the output shown:

```
n gemini fetchTicker "paxgusd" 
...
{
  symbol: 'PAX/GUSD',
...
  info: {
...
    volume: {
      PAXG: '111.34037958',
      USD: '266326.18795536',
...
    }
  }
}
```

The inconsistency between `PAX/GUSD` and `PAXG` and `USD`. `PAXG` + `/` + `USG` != `PAX/GUSD`

**Comment by carlosmiei** [comment]
@blair Oh ok you're right this is Pax Gold and not PAX/GUSD, we will have to find another solution (would be so much easier if gemini clearly separated the base-quote...)

**Comment by ttodua** [comment]
I'll try to address it in few hours

**Comment by carlosmiei** [comment]
@ttodua I'm working on a "quick-fix" with a list of known "conflicting" market ids

**Comment by ttodua** [comment]
i think you could have skipped this issue, your time is more important so I could work on this and you address more important PRs/reviews

**Comment by carlosmiei** [comment]
@blair If you update your ccxt version, I believe the paxg issue is fixed now

**Comment by blair** [comment]
@carlosmiei Thanks, it works perfectly!
