### ISSUE TITLE
Coinbase watchOrderbook promise doesnt resolve.

### ISSUE THREAD

**Issue by Gsuz** [ccxt/ccxt#22114]
### Operating System

mac os 

### CCXT Version

4.2.94

### Description

It seems as if my streamOrderBook function doesnt work for coinbase. Although it does work for Binance. My function is below and I added a verbose flag to see what's going on. I'm getting these logs so I know that we are receiving data from coinbase but it seems that the promise is never resolved so the rest of my code is not excecuted. For instance this line 
```  logger.info(
          `Exchange: ${this.name} - Market: ${market} - bestBid: ${orderbook?.bids[0]?.[0]} - bestAsk: ${orderbook?.asks[0]?.[0]}` 
```
is never triggered. Here are the results in the terminal 
```
connecting to wss://advanced-trade-ws.coinbase.com
2024-04-10T20:34:43.857Z onUpgrade
2024-04-10T20:34:43.858Z onOpen
2024-04-10T20:34:43.860Z sending {
type: 'subscribe',
product_ids: [ 'BTC-USDC' ],
channel: 'level2',
api_key: '40tMgQdFFTPu5INj',
timestamp: '1712781283',
signature: 'ada1d3fb78279eee1e6eceb6dc1fcbb2419a117a130eaebc4a61f15b2ae060a6'
 }
2024-04-10T20:34:43.861Z sending {
type: 'subscribe',
product_ids: [ 'SOL-USDC' ],
channel: 'level2',
api_key: '40tMgQdFFTPu5INj',
timestamp: '1712781283',
signature: 'c35b8b9f6972d0150effb4e71b5af2843e0bdd9a5b5eb42bc360e0d0de9fee55'
}
2024-04-10T20:34:44.837Z onMessage {
channel: 'l2_data',
client_id: '',
timestamp: '2024-04-10T20:34:44.270755693Z',
sequence_num: 0,
events: [ { type: 'snapshot', product_id: 'BTC-USD', updates: [Array] } ]
}
```

### Code

```
    private async streamOrderBook(market: string) {
    while (true) {
      try {
        console.log('watching orderbook from exchange', this.name)
        this.exchange.verbose = true
        const orderbook = await this.exchange.watchOrderBook(market)
        logger.info(
          `Exchange: ${this.name} - Market: ${market} - bestBid: ${orderbook?.bids[0]?.[0]} - bestAsk: ${orderbook?.asks[0]?.[0]}`
        )
      } catch (error: any) {
        console.log('error found')
        logger.error(error)
        process.exit(0)
      }
    }
  }

```

**Comment by sc0Vu** [comment]
@Gsuz looks like the product id was different (BTC-USDC and BTC-USD). Before we update, would you like to use `BTC/USD` symbol instead of `BTC/USDC`?

**Comment by Gsuz** [comment]
Hi, the symbols I'm passing in are "BTC/USDC" and "SOL/USDC" these are the markets that I want to watch. If I switch over to BTC/USD and SOL/USD respectively things work fine. However these are not the markets I want to watch.

**Comment by Gsuz** [comment]
It's dawning on me now.. maybe these are the same markets?

**Comment by carlosmiei** [comment]
Hello @Gsuz, Thanks for reporting it; the problem is that BTC/USDC and BTC/USD are aliases at Coinbase, meaning that they're the same market. So we subscribe to `BTC/USDC`, and Coinbase returns the alias `BTC/USD`. We will try to reach out to them, but in the meantime, you can use `BTC/USD` because it represents the same thing

**Comment by Gsuz** [comment]
thank you. A quick followup are coinbase futures not enabled yet?

**Comment by carlosmiei** [comment]
@Gsuz Not yet, but I'm working on it as we speak, they should be available in a few days, you can follow the progress here:
- https://github.com/ccxt/ccxt/pull/22102

**Comment by carlosmiei** [comment]
@Gsuz If you update your ccxt version I believe you should be able to trade futures there now.

**Comment by Gsuz** [comment]
Great to see! thank you

**Comment by Gsuz** [comment]
fixed.
