### ISSUE TITLE
Portfolio Margin issue on Binance

### ISSUE THREAD

**Issue by KevinBaudin** [ccxt/ccxt#22123]
### Operating System

Ubuntu 22.04.1 LTS

### Programming Languages

python

### CCXT Version

4.2.64

### Description

Hi
I've started to test Portfolio Margin for Binance, it works well, but I find it quite disturbing to use.
![image](https://github.com/ccxt/ccxt/assets/20791331/adb2b9fb-dbda-410c-9946-9551ac7d3869)
See my example,
The prices are fetch as Futures, the only way to use papi is by sending the symbol as "future written", and if used with the regular symbol (spot), it's sending a regular spot order

I'm almost 100% sure that the price should be the one from Spot also

I think the code provided below in create order is at fault, since ETH/USDT market is not linear, it can be considered as isPortfolioMargin even if params portfolioMargin:True

Thanks a lot for  your amazing work :)

### Code

```
        elif market['linear']:
            if isPortfolioMargin:
                if isConditional:
                    response = self.papiPostUmConditionalOrder(request)
                else:
                    response = self.papiPostUmOrder(request)

```

**Comment by carlosmiei** [comment]
Hello @KevinBaudin, thanks a lot for reporting it, we will take a look asap.

**Comment by KevinBaudin** [comment]
Hi and thanks for the quick answers

`fetch_order_book` should indeed fallback to an existing endpoint, since there is none for portfolio margin.
But since it's more related to the spot asset than the future asset, I would prefer to be able to use the spot symbol for those search, otherwise, there would be some conflict/inconsistencies

> If that is the case I think you can achieve it by providing portfolioMargin: True and marginMode: cross in params

I will test it, thanks !

**Comment by carlosmiei** [comment]
@KevinBaudin I'm not sure if I understood the spot vs future symbol issue 😅 , that shouldn't change regardless of the account/mode used.

**Comment by KevinBaudin** [comment]
My only issue was that I couldn't make it work with `ETH/USDT` symbol but I could with `ETH/USDT:USDT`. Now that you provided me the `marginMode: cross` tip, I think I don't have issues anymore :) I'll check it

**Comment by carlosmiei** [comment]
@KevinBaudin cool, just let us know if anything )

**Comment by Dan-krm** [comment]
@KevinBaudin To make the methods a bit more user-friendly, I opened a pull request that will allow you to just set the `portfolioMargin` param to true with a `spot symbol`, so you won't need to set the `marginMode` as well.
