### ISSUE TITLE
ACX changed api. 'fetch_order_book' changed from accepting limit=None to limit=100

### ISSUE THREAD

**Issue by Tehsurfer** [ccxt/ccxt#2213]
Hi there, I am attempting to update the 'fetch_order_book' method of acx.py 

All that needs to be changed is the default parameter for the 'limit' variable.

- OS: Windows 10
- Programming Language version: Python 3.6
- CCXT version: 1.11.68
- Exchange: ACX
- Method: fetch_order_book(self, symbol, limit=None, params={}):

**acx.py line 138**
from: 
`def fetch_order_book(self, symbol, limit=None, params={}):`
to
`def fetch_order_book(self, symbol, limit=1000, params={}):`

Any help for a newbie would be much appreciated :)

**Comment by kroitor** [comment]
@Tehsurfer hi, please read the beginning of `acx.py` and this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
Thx! )

**Comment by kroitor** [comment]
P.S. ACX didn't change their API we just don't want to fetch 1000 trades if the user has omitted that argument, and use the exchange default (which is 300 according to their docs).

<img width="1242" alt="screen shot 2018-03-11 at 05 00 52" src="https://user-images.githubusercontent.com/1294454/37248668-4d4487da-24e9-11e8-81cd-3dbd78d38e0c.png">

**Comment by Tehsurfer** [comment]
Oops sorry kriotor, that makes sense. I derped and forgot that I could just change the 'limit' variable on my side. Thank you so much for you help 😄

**Comment by kroitor** [comment]
@Tehsurfer no worries, let us know if you have any difficulties. See [examples](https://github.com/ccxt/ccxt/tree/master/examples) and [wiki](https://github.com/ccxt/ccxt/wiki) if you want more )
