### ISSUE TITLE
Deribit: fetch_tickers returns an empty dict for non-BTC currencies

### ISSUE THREAD

**Issue by jsilhan** [ccxt/ccxt#22142]
### Operating System

Linux, fedora 38

### Programming Languages

Python

### CCXT Version

4.2.96

### Description

On Deribit `fetch_tickers` works just for BTC, for other currencies it returns an empty dict although the pair is correctly inside `exchange.markets`.

### Code

```python
import ccxt
e = ccxt.deribit()
e.load_markets()
e.fetch_tickers(['ETH/USDT'])
# returns incorrectly an empty dict
e.fetch_tickers(['SOL/USDC'])
# returns incorrectly an empty dict
e.fetch_tickers(['BTC/USDT'])
# returns correctly {'BTC/USDT': ...}
"ETH/USDT" in e.markets
# returns True
"SOL/USDC" in e.markets
# returns True
```

**Comment by carlosmiei** [comment]
Hello @jsilhan, 
Thanks for reporting it, we will take a look asap.

**Comment by carlosmiei** [comment]
@jsilhan Actually we're using an endpoint that requires a currency parameter, so if you want to fetch let's say `ETH/USDT` you should provide `code: ETH` in `params`, and that would fetch all ETH markets at deribit.

We will try to make so adjustments to make this a bit more clear. 

https://docs.deribit.com/#public-get_book_summary_by_currency
