### ISSUE TITLE
Bibox fetch_deposit_address(coin) returns wrong info

### ISSUE THREAD

**Issue by flaeshi** [ccxt/ccxt#2214]
Calling the function fetch_deposit_address(coin) does not return the deposit address of the coin, but rather withdrawal information.

Input:

```import ccxt

bibox = ccxt.bibox()

bibox.verbose = True

bibox.apiKey = '123'
bibox.secret = '456'

response = bibox.fetch_deposit_address('CPC')

print response
```

Output:
```
{'info': {u'cmd': u'transfer/transferOutInfo', u'result': {u'addrList': [], u'usdt_withdraw_max': u'50000.00000000', u'withdraw_fee': 10, u'withdraw_min': 50, u'withdraw_balance': u'0.00000000'}}, 'address': None}
```

**Proposed solution:**
If you change the command in the fetch_deposit_address() function (line 473) in bibox.py from "transferOutInfo" to "transferIn", the correct deposit address will be fetched:

```
def fetch_deposit_address(self, code, params={}):
        [...]
        response = self.privatePostTransfer({
            'cmd': 'transfer/transferOutInfo', --> 'cmd': 'transfer/transferIn'
            'body': self.extend({
                'coin_symbol': currency['id'],
            }, params),
        })
        [...]
```

Output:
```
{'info': {u'cmd': u'transfer/transferIn', u'result': u'0x9b0ed***********************'}, 'address': None}
```

If you change this function, will there be a separate function which returns the withdrawal fees for a coin (returned by transferOutInfo)? The command is quite useful to me.

- OS: Linux Mint 18.3
- Programming Language version: Python 2.7.12
- CCXT version: 1.11.53
- Exchange: Bibox
- Method: fetch_deposit_address()

**Comment by kroitor** [comment]
> If you change this function, will there be a separate function which returns the withdrawal fees for a coin (returned by transferOutInfo)? The command is quite useful to me.

Yes, it's as easy as calling this:

```Python
        currency = exchange.currency('BTC')
        response = exchange.privatePostTransfer({
            'cmd': 'transfer/transferOutInfo',
            'body': self.extend({
                'coin_symbol': currency['id'],
            }, params),
        })
```

This issue is fixed now. Let us know if you still have difficulties with it after updating ccxt to version 1.11.75. Thanks for reporting!
