### ISSUE TITLE
System.ArgumentException for Bitget FetchPositions. C#

### ISSUE THREAD

**Issue by skuvv** [ccxt/ccxt#22143]
### Operating System

Windows 10

### CCXT Version

4.2.93

### Description

Multiple parallel FetchPositions for specific internal request of Bitget cause error:
System.ArgumentException: An item with the same key has already been added.
   в System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   в System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   в System.Net.Http.Headers.HttpHeaders.AddHeaderToStore(String name, HeaderStoreItemInfo info)
   в System.Net.Http.Headers.HttpHeaders.Add(String name, String value)

### Code

Demo project is attached below:
[DemoForDebug.zip](https://github.com/ccxt/ccxt/files/14970675/DemoForDebug.zip)

ps don't forget setup your credentials.

**Comment by carlosmiei** [comment]
Hello @skuvv thanks for reporting it, we will take a look

**Comment by carlosmiei** [comment]
Weird, I get a different error but seems to come directly from `System.Net.HttpClient` 

![image](https://github.com/ccxt/ccxt/assets/43336371/dd71f06e-02d5-40ef-b506-1d8c1d4da272)

**Comment by ttodua** [comment]
@skuvv thanks for helpful feedbacks and reproduceable demos. I have reproduced the exact error you are getting.
We will push the fix in within next hour

**Comment by carlosmiei** [comment]
@ttodua Thank you! will test it and merge it soon

**Comment by carlosmiei** [comment]
@skuvv Sorry it took longer than expected but I think it should be fixed now, can you please update your ccxt version and try again?

**Comment by skuvv** [comment]
Tested on 4.3.30, fixed, Thanks.
