### ISSUE TITLE
PERMISSION_DENIED error_details User has no access to view perps (URGENT)

### ISSUE THREAD

**Issue by pottertech** [ccxt/ccxt#22144]
### Operating System

Ubuntu 20.04

### CCXT Version

4.2.96

### Description

I am now getting PHP Fatal error:  Uncaught ccxt\PermissionDenied: coinbase {"error":"PERMISSION_DENIED","error_details":"User has no access to view perps","message":"User has no access to view perps"} in /root/ccxt/php/Exchange.php:4989

when I use version 4.2.96.  To test I used the coinbase-fetch-all-balances.php in the examples/php directory with my API KEY and SECRET KEY.  

This has my entire system offline so any help is greatly appreciated!

### Code

```
<?php

$root = dirname(dirname(dirname(__FILE__)));

include $root . '/ccxt.php';

date_default_timezone_set('UTC');

$exchange = new \ccxt\coinbase(array(
    'apiKey' => 'xxxxxxxxxxxxxxxxx',
    'secret' => 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
    'verbose' => true, // uncomment for debugging
));

$exchange->load_markets();

// $exchange->verbose = true; // uncomment for debugging

$result = array();
$params = array();
$loop = true;
do {
    $balance = $exchange->fetch_balance($params);
    $pagination = $exchange->safe_value($balance['info'], 'pagination');
    if ($pagination === null) {
        $loop = false;
    } else {
        $next_starting_after = $exchange->safe_string ($pagination, 'next_starting_after');
        if ($next_starting_after !== null) {
            $params['starting_after'] = $next_starting_after;
        } else {
            $loop = false;
        }
    }
    echo $exchange->iso8601($exchange->milliseconds()) . "\n";
    $result = $exchange->deep_extend($result, $balance);
} while ($loop);

echo "======================================================================\n";
var_dump($result);  

```

[error.log](https://github.com/ccxt/ccxt/files/14971127/error.log)

**Comment by carlosmiei** [comment]
Hello @pottertech, thanks for reporting it, that should not happen, we will take a look as soon as possible.

**Comment by carlosmiei** [comment]
@pottertech Can you update your ccxt version and try again? It should be working now

**Comment by pottertech** [comment]
@carlosmiei I installed version 4.2.99 and it seems to work now.  Thanks a ton!
