### ISSUE TITLE
Bitmex: Parse order TypeError with stop loss order

### ISSUE THREAD

**Issue by Dave-Vallance** [ccxt/ccxt#2216]
- OS: Mac
- Programming Language version: Python 3.6
- CCXT version: 1.11.62
- Exchange: Bitmex
- Method: Parse_Order

Hi!
  If I pass a stop loss order for bitmex to the parse_order method, a `TypeError` is raised.

```
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/bitmex.py", line 395, in parse_order
    price = float(order['price'])
TypeError: float() argument must be a string or a number, not 'NoneType'
```

I guess this is because a stop loss is created without a `price` parameter set. Instead,  we need to use the `params` dict to specify a `stopPx` level. 

Perhaps, the line:

```price = float(order['price'])```

could be changed to

``` price = float(order['price']) if order['price'] else None```

What do you think?

**Comment by kroitor** [comment]
Fixed in the most recent version of ccxt. Thx for reporting!
