### ISSUE TITLE
Are users meant to update frequently?

### ISSUE THREAD

**Issue by thisismygitrepo** [ccxt/ccxt#22179]
There is a mapping between CCXT symbols and particular exchanges and it is not clear to me whether this mapping is updated through hardcoding in the library code or dynamically though some server?

If things are hardcoded in library, does this mean we are meant to stay up to date every day or so?

Thanks,

**Comment by fxxxfun** [comment]
thanks @Dan-krm for the insight!

**Comment by thisismygitrepo** [comment]
Thanks.
