### ISSUE TITLE
postOnly does not work for kraken.create_limit_sell_order

### ISSUE THREAD

**Issue by Joshbazz** [ccxt/ccxt#22181]
### Operating System

Mac

### Programming Languages

Python

### CCXT Version

4.2.97

### Description

with `params = {'postOnly': True}`, kraken.create_limit_sell_order does not set postOnly to True

tested against kraken.create_limit_buy_order(), which functions correctly

when running kraken.create_limit_order(symbol, 'sell', price, amount, params=params) with same params as above, postOnly works normally

### Code

```
works => kraken.create_limit_buy_order(symbol, open_size, bp_1_test, params) --> postOnly == True
doesn't work => kraken.create_limit_sell_order(symbol, open_size, sp_1_test, params=params) --> postOnly == False
works => kraken.create_limit_order(symbol, 'sell', sp_1_test, open_size, params=params) --> postOnly == True
```

**Comment by carlosmiei** [comment]
Hello @Joshbazz, thanks for reporting it, we will take a look asap

**Comment by carlosmiei** [comment]
@Joshbazz Actually I just tested and as you can see the `oflags` is `post` (that's the exchange-specific way of saying postOnly order)

```
kraken.createLimitSellOrder (LTC/USDT, 1, 55, [object Object])
fetch Request:
 kraken POST https://api.kraken.com/0/private/AddOrder 
RequestHeaders:
 {
  'API-Key': 'ulyAxzvwj16oZaB7VhpfgOCu+scWl8WHTCIJMRsg9jvp/eR/3IYRcHpP',
  'API-Sign': 'PKFwnSMNYfcX+9Z4s6hje6GyWemEaKvfsFmEcA1ocFFMx8KsrwHV8lrq0jYQ45ZJHQpcgNyoaZUxAYQvH8QGJg==',
  'Content-Type': 'application/x-www-form-urlencoded'
} 
RequestBody:
 nonce=1713340960840&pair=LTCUSDT&type=sell&ordertype=limit&volume=1&price=55&oflags=post 
```

**Comment by yasar456uhyhluih** [comment]
Wall hack
Flying vehicles
all code fo pubg mobil game for iphon

**Comment by Joshbazz** [comment]
great, thank you for that. tested and this works

**Comment by fxxxfun** [comment]
#followyourfun

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
