### ISSUE TITLE
Kraken createOrderWs

### ISSUE THREAD

**Issue by fl0wo** [ccxt/ccxt#22200]
### Operating System

MaCos

### CCXT Version

4.2.88

### Description

More than an Issue is rather a question.

Given a CCXT Kraken client:
I'm using both createOrderWs and createOrder.

In this way:
```
try { 
   createOrderWs(...)
} catch(e) {
   // if fails use 
  createOrder();
}
```

My question is, could be that createOrderWs sometimes fails (and throws an error) **even tho** manages to place the order anyway?

I say this because I'm seeing double orders on Kraken (while all other exchanges (that uses the same exact code)) do not have double orders (and trades).

Please any support is much appreciated.
It's very hard to replicate this issue, if i find some logs I'll try to share it here.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @fl0wo,

Technically yes it is possible, we might be misparsing an error message or something like that but it's very hard to tell without more information such as logs/ stacktrades/ steps to reproduce the issue.

**Comment by carlosmiei** [comment]
I tried to run something like this, but had no luck

```Python
    for i in range(0, 20):
        order = await exchange.create_order_ws('LTC/USDT', 'limit', 'buy', 0.1, 50)
        print('created order', order['id'])
        await exchange.cancel_order(order['id'], 'LTC/USDT')
        print('canceled order', order['id'])

```

**Comment by fl0wo** [comment]
Hi, indeed it's very hard to reproduce.

I have seen this on avg 1 between 200-300 trades. 
And for some reasons it more often when the "amount" is high (almost as if the order is not completed immediately it throws an error, and for smaller orders with lower size that get immediately closed not)

But I'm not sure, for now I just removed the createOrderWs usage, and will monitor this the following days.

I'm closing this as not an issue, will re-open it if possible, when I see again the same in case.

**Comment by fl0wo** [comment]
Regarding your test code, I'd rather do something like:
```
for ... 20 {
 
  try {
        await createOrderWs( LTC... )
  catch(e) {
       await createOrder( LTC... ) // non ws
  }

  await sleep 10sec

  // fetch new orders on LTC
  // if there are 2 new orders on LTC we have a bug (means we placed 2 times the same order)

}

```

**Comment by fl0wo** [comment]
Ok I removed createOrderWs and now i dont see double trades no more.

I confirm createOrderWs errors are weird for Krakne

**Comment by carlosmiei** [comment]
@fl0wo Did you manage to get a verbose log?

**Comment by fl0wo** [comment]
@carlosmiei not yet, I'll have a look and post them here if i find any
