### ISSUE TITLE
Bibox: error code 3024 on create_order

### ISSUE THREAD

**Issue by forexhill** [ccxt/ccxt#2221]
- OS: Linux Ubuntu 17.10
- Programming Language version: PHP 7.1.11-0ubuntu0.17.10.1
- CCXT version: trunk, pulled few hours ago
- Exchange: Bibox
- Method: create_order('LTC/BTC', 'limit', 'sell', 0.00149841, 0.01965457)

Private auth to bibox works fine (can see balances), however, create_order (with varied symbols and input) always gives;

```
exception 'ccxt\ExchangeError' with message 'bibox {"error":{"code":"3024","msg":"apikey\u6743\u9650\u4e0d\u8db3"}}' in /home/{user}/ccxt/php/bibox.php:584
Stack trace:
#0 [internal function]: ccxt\bibox->request('orderpending', 'private', 'POST', Array)
#1 /home/{user}/ccxt/php/Exchange.php(699): call_user_func(Array, 'orderpending', 'private', 'POST', Array)
#2 [internal function]: ccxt\Exchange->ccxt\{closure}(Array)
#3 /home/{user}/ccxt/php/Exchange.php(1661): call_user_func_array(Object(Closure), Array)
#4 /home/{user}/ccxt/php/bibox.php(361): ccxt\Exchange->__call('privatePostOrde...', Array)
#5 /home/{user}/ccxt/php/bibox.php(361): _bibox->privatePostOrderpending(Array)
#6 /home/{user}/ccscripts/my.php(267): ccxt\bibox->create_order('LTC/BTC', 'limit', 'sell', 0.00149841, 0.01965457)
#7 {main}
```

I tried finding a solution, reviewing past issues, changing code, all to no avail. Same code also works fine on Yobit.

**Comment by kroitor** [comment]
Hi!

Can you, please show the full verbose output of the above call?

```PHP
bibox->verbose = true;
bibox->create_order('LTC/BTC', 'limit', 'sell', 0.00149841, 0.01965457);
```
(without the keys)? This would help me solve it a little quicker, thx.

**Comment by forexhill** [comment]
Aha, translating the chinese response gave me a clue of what was wrong;
```{"error":{"code":"3024","msg":"apikey权限不足"}}```
iow;
```Insufficient apikey permissions```
And indeed, after adding trade abilities to the key, it works

Is there a way to equate 3024 with this error in the code?

**Comment by kroitor** [comment]
> Let me know if you still need full output

Nope, looks like you've figured it out. We will add handling for the above error code shortly. Thx for reporting!
