### ISSUE TITLE
"Malformed request" errors using watchOrderBooks on kraken

### ISSUE THREAD

**Issue by ByTheSeaL** [ccxt/ccxt#22220]
### Operating System

Windows 11 and Ubuntu 23.10

### Programming Languages

Python

### CCXT Version

4.3.1

### Description

Hi,

Firstly thank you for your work on ccxt - it's brilliant!

Just starting yesterday the watchOrderBook() method for Kraken alone has started returning a "malformed request" error:

```
2024-04-19T17:56:46.468Z connecting to wss://ws.kraken.com with timeout 10000 ms
2024-04-19T17:56:47.736Z connected
2024-04-19T17:56:47.737Z ping loop
2024-04-19T17:56:47.738Z message {"connectionID":18140194665070909469,"event":"systemStatus","status":"online","version":"1.9.2"}
2024-04-19T17:56:47.738Z sending {'event': 'subscribe', 'reqid': 1, 'pair': ['XBT/USDT'], 'subscription': {'depth': 10}}
2024-04-19T17:56:47.780Z pong WSMessage(type=<WSMsgType.PONG: 10>, data=bytearray(b''), extra='')
2024-04-19T17:56:47.781Z message {"errorMessage":"Malformed request","event":"subscriptionStatus","pair":"XBT/USDT","reqid":1,"status":"error","subscription":{"depth":10}}
```

The fetchOrderBooks and fetchBalance methods work completely fine for the same Kraken ccxt object - aswell as other watch methods like watchOrders - so it doesn't seem an exchange or my-account-at-exchange issue. Plus watchOrderBook is working perfectly fine at the other exchanges I'm using.

I've tried the following trying to isolate it:

- tried on both a Windows 11 home computer and Ubuntu VPS, with different IPs, both returning same error
- Python versions are 3.12 and 3.10 on both machines so guess I've checked across Python versions
- created new API keys on Kraken, in case it was nonce error
- thought it could have been related to recently upgrading to 4.2.100 then 4.3.1 yesterday but downgraded to my previous version (4.2.96) and it was the same.
- kraken API docs do mention "malformed request" but no more details. https://docs.kraken.com/websockets/#message-book
- I had been getting intermittent 'invalid checksum' errors with Kraken so I did temporarily have the "checksum: False" option set. Tried removing it and still same issue.

- In line 1223 of ccxt\async_support\base\kraken.py I was confused why the request is formed this way:
```
request = {
            'event': 'subscribe',
            'reqid': self.request_id(),
            'pair': wsMarketIds,
            'subscription': {
                'name': channelName,
            },
```
But in the error output the 'subscription' key is formed differently:
```
sending {'event': 'subscribe', 'reqid': 1, 'pair': ['XBT/USDT'], 'subscription': {'depth': 10}}
```
Could that be related?

Be grateful for any help with this. I'm using the fetch methods all fine as a workaround for now thought obviously the websocket methods are more responsive.

### Code

```
params = {
    'apiKey': "",
    'secret': "",
    'password': ""
}
symbol = "BTC/USDT"
limit = 10

ccxt_classPro = getattr(ccxtpro, "kraken")
ccxtObjPro = ccxt_classPro(params)
ccxtObjPro.verbose = True

while True:
  try:
      orderbook = await ccxtObjPro.watchOrderBook(symbol, limit)
      result = {"bid": orderbook["bids"][0][0], "ask": orderbook["asks"][0][0]}
      # more code to store data received here
  
  except Exception as e:
      print(f"Error watching orderbook for {exchangeObj.name} {symbol}: {str(e)}")
  
  await asyncio.sleep(0.5)
```

**Comment by carlosmiei** [comment]
Hello @ByTheSeaL, thanks for reporting it! We will take a look and report back asap.

**Comment by carlosmiei** [comment]
Hello @ByTheSeaL , Can you please update your ccxt version and try again? it should be working now.

**Comment by ByTheSeaL** [comment]
Working perfectly now - thank you very much @carlosmiei 

Best wishes
