### ISSUE TITLE
Hyperliquid - fetch_spot_markets() returns nothing

### ISSUE THREAD

**Issue by basedbayes** [ccxt/ccxt#22221]
### Operating System

MacOS

### Programming Languages

Python

### CCXT Version

4.3.2

### Description

Fetch spot markets returns nothing for Hyperliquid, even though spot trading is active for PURR. 

Relevant docs: 
https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/info-endpoint/spot

### Code

```
exchange = ccxt.hyperliquid()
exchange.loadMarkets()
print(ccxt.__version__)
print(exchange.fetch_spot_markets())

>>> 4.3.2
>>> []

```

**Comment by carlosmiei** [comment]
Hello @basedbayes, thanks for reporting it.

`fetchSpotMarkets` is not meant to be used directly, you should use `loadMarkets()` and then `exchange.markets` to get the markets.

With that said, I can confirm that it's only working on the sandbox environment for some reason, we will check it out and revert.

```
n hyperliquid fetchSpotMarkets --sandbox  
2024-04-20T10:06:41.381Z
Node.js: v18.18.0
CCXT v4.3.2
hyperliquid.fetchSpotMarkets ()
2024-04-20T10:06:43.635Z iteration 0 passed in 338 ms

   id |    symbol | base | quote | baseId | quoteId | type | spot |  swap | future | option | index | active | contract | linear | inverse |   taker |  maker |              precision |                                           limits
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
10000 | PURR/USDC | PURR |  USDC |  10000 |    USDC | spot | true | false |  false |  false | false |   true |    false |   true |   false | 0.00035 | 0.0001 | {"amount":1,"price":8} | {"leverage":{},"amount":{},"price":{},"cost":{}}
```

**Comment by carlosmiei** [comment]
@basedbayes I found indeed a difference between both environments but we will fix it asap.

**Comment by carlosmiei** [comment]
@basedbayes, Can you please update your ccxt version and try again? it should be working now.

**Comment by basedbayes** [comment]
Works great now, thanks!
