### ISSUE TITLE
coinex Signature Incorrect

### ISSUE THREAD

**Issue by Tidhy** [ccxt/ccxt#22223]
### Operating System

Windows11

### Programming Languages

Python

### CCXT Version

4.3.1 and 4.3.2

### Description

When I was using ccxtpro to create an order (a market selling order), I received an error message as follows:
```
ccxt.base.errors.AuthenticationError: coinex Signature Incorrect
```

But there is no problem with orders bought at market price

### Code

```
import ccxt.pro as ccxt
params = {
    'createMarketBuyOrderRequiresPrice': False 
}

await coinex_exchange.create_order(symbol=symbol, type='market', side='sell',amount=total_count, params=params)

```

**Comment by carlosmiei** [comment]
Hello @Tidhy,
I just tested and seems to be working:
```
p coinex createOrder "LTC/USDT" market sell 0.1    
Python v3.11.7
CCXT v4.3.2
coinex.createOrder(LTC/USDT,market,sell,0.1)
{'amount': 0.1,
 'average': 82.52,
 'clientOrderId': 'x-167673045-264def25d20c49fa',
 'cost': 8.252,
 'datetime': '2024-04-20T15:02:29.000Z',
 'fee': {'cost': '0.016504', 'currency': 'USDT'},
 'fees': [{'cost': 0.016504, 'currency': 'USDT'}],
 'filled': 0.1,
 'id': '116718681363',
 'info': {'amount': '0.1',
          'amount_asset': 'LTC',
          'asset_fee': '0',
          'avg_price': '82.52',
          'client_id': 'x-167673045-264def25d20c49fa',
          'create_time': '1713625349',
          'deal_amount': '0.1',
          'deal_fee': '0.016504',
          'deal_money': '8.252',
          'fee_asset': None,
          'fee_discount': '1',
          'finished_time': None,
          'id': '116718681363',
          'left': '0',
          'maker_fee_rate': '0',
          'market': 'LTCUSDT',
          'money_fee': '0.016504',
          'order_type': 'market',
          'price': '0',
          'status': 'done',
          'stock_fee': '0',
          'taker_fee_rate': '0.002',
          'type': 'sell'},
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'postOnly': None,
 'price': 82.52,
 'reduceOnly': None,
 'remaining': 0.0,
 'side': 'sell',
 'status': 'closed',
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': 'LTC/USDT',
 'takeProfitPrice': None,
 'timeInForce': 'IOC',
 'timestamp': 1713625349000,
 'trades': [],
 'triggerPrice': None,
 'type': 'market'}
```

**Comment by Tidhy** [comment]
> Hello @Tidhy, I just tested and seems to be working:
> 
> ```
> p coinex createOrder "LTC/USDT" market sell 0.1    
> Python v3.11.7
> CCXT v4.3.2
> coinex.createOrder(LTC/USDT,market,sell,0.1)
> {'amount': 0.1,
>  'average': 82.52,
>  'clientOrderId': 'x-167673045-264def25d20c49fa',
>  'cost': 8.252,
>  'datetime': '2024-04-20T15:02:29.000Z',
>  'fee': {'cost': '0.016504', 'currency': 'USDT'},
>  'fees': [{'cost': 0.016504, 'currency': 'USDT'}],
>  'filled': 0.1,
>  'id': '116718681363',
>  'info': {'amount': '0.1',
>           'amount_asset': 'LTC',
>           'asset_fee': '0',
>           'avg_price': '82.52',
>           'client_id': 'x-167673045-264def25d20c49fa',
>           'create_time': '1713625349',
>           'deal_amount': '0.1',
>           'deal_fee': '0.016504',
>           'deal_money': '8.252',
>           'fee_asset': None,
>           'fee_discount': '1',
>           'finished_time': None,
>           'id': '116718681363',
>           'left': '0',
>           'maker_fee_rate': '0',
>           'market': 'LTCUSDT',
>           'money_fee': '0.016504',
>           'order_type': 'market',
>           'price': '0',
>           'status': 'done',
>           'stock_fee': '0',
>           'taker_fee_rate': '0.002',
>           'type': 'sell'},
>  'lastTradeTimestamp': None,
>  'lastUpdateTimestamp': None,
>  'postOnly': None,
>  'price': 82.52,
>  'reduceOnly': None,
>  'remaining': 0.0,
>  'side': 'sell',
>  'status': 'closed',
>  'stopLossPrice': None,
>  'stopPrice': None,
>  'symbol': 'LTC/USDT',
>  'takeProfitPrice': None,
>  'timeInForce': 'IOC',
>  'timestamp': 1713625349000,
>  'trades': [],
>  'triggerPrice': None,
>  'type': 'market'}
> ```

Okay, you're right. I just deleted the params parameter and tried again, and now it's back to normal. Thank you
