### ISSUE TITLE
ccxtpro bug: the watched ohlcvs cache in OKX exchange not updated 

### ISSUE THREAD

**Issue by eurekawild** [ccxt/ccxt#22228]
### Operating System

centos8

### Programming Languages

Python

### CCXT Version

4.2.100

### Description

The cache of ohlcvs in OKX exchange are not updated after function watch_ohlcv() langched for a while(about 1 hour in my program), however the same code for Binance is well. I tried running it for several times and got the same fault in OKX and the right result in Binance.

### Code

```
   await ex.watch_ohlcv(symbol, timeframe)
   while True:
       ohlcvs = ex.ohlcvs[symbol][timeframe]  # the candles info is not updated after the program running a while
         print(ohlcvs)

```

**Comment by carlosmiei** [comment]
Hello @eurekawild,

What's the best way of reproducing the issue? Do we have to wait an hour?

**Comment by eurekawild** [comment]
> Hello @eurekawild,
> 
> What's the best way of reproducing the issue? Do we have to wait an hour?

I dont have a best way. In my program, the same code for Binance is well. Maybe something is  wrong in OKX, like the  frequency limit etc. Now I restart my program per one hour, It's OK for me.

**Comment by eurekawild** [comment]
async def symbol_loop(ex, symbol, timeframe):
    try:
        await ex.watch_ohlcv(symbol, timeframe)
    except Exception as e:
        traceback.print_exc()
        return
    cur_ohlcvs = await ex.fetch_ohlcv(symbol, timeframe, None,100)
    while True:
        latest_ohlcvs = ex.ohlcvs[symbol][timeframe]
        for ohlcv in latest_ohlcvs:
            last_ohlcv = cur_ohlcvs[-1]
            if ohlcv[0] > last_ohlcv[0]:
                cur_ohlcvs.append(ohlcv)
                cur_ohlcvs.pop(0)
            elif ohlcv[0] == last_ohlcv[0]:
                cur_ohlcvs[-1] = ohlcv
        print("cur ohlcvs:", cur_ohlcvs)
 
 This is the core code in my production environment. I just call the func watch_ohlcv() once,  the func fetch_ohlcv() once. in the loop I just visit the ohlcv cache in ex.

**Comment by makarid** [comment]
I can confirm the same. I am trying OKX watchOrderbook and it doesn't work but the same code for Bybit works. Version 4.3.11

Example code:

const exchange = new pro.okx({
    "enableRateLimit": true,
    "apiKey": okexApiKey,
    "secret": okexSecret,
    "password": okexPass,
});

watchOrderBooks(exchange, ["BTC-USDT-SWAP","ETH-USDT-SWAP"])

async function watchOrderBooks(exchange, perpSymbols) {
    while (true) {
        try {
            for (const symbol of perpSymbols) {
                console.log("Symbol: "+ symbol)
                const orderbook = await exchange.watchOrderBook(symbol, 50)
            }
        } catch (e) {
            logger.error (e.message)
        }
    }
}

If you run this code, the ETH-USDT-SWAP never console.logs.

**Comment by pcriadoperez** [comment]
Hi @makarid , for the apiKey error you can set the params.depth to 'books' and that should fix it. I also opened a PR to default to it

**Comment by pcriadoperez** [comment]
Hi @makarid , I believe I found the problem, I think your api keys don't have VIP4 permission to use the depth channel `books50-l2-tbt` and the library wasn't throwing the error correctly so it appeared to be "stuck"

I opened one PR to default to the public channel and another to properly throw the error in this event. In the meantime the code should work if you use the depth channel `books`

**Comment by makarid** [comment]
Thank you very much @pcriadoperez !
