### ISSUE TITLE
Bingx : Having issues calling setLeverage in one way mode.

### ISSUE THREAD

**Issue by germangar** [ccxt/ccxt#22237]
### Programming Languages

Python

### CCXT Version

4.3.4

### Description

Hello,

When calling setLeverage from oneway mode I'm getting the error:
`bingx {"code":109400,"msg":"In the One-way mode, the 'PositionSide' field can only be set to BOTH.","data":{}} <class 'ccxt.base.errors.ExchangeError'>`

I am setting the param 'side' to 'BOTH'. I also tried adding a new param 'PositionSide' set to 'BOTH'. Didn't work.

When enabling ccxt verbose this is the what the releveant messages say:

```
fetch Request: bingx POST https://open-api.bingx.com/openApi/swap/v2/trade/leverage?leverage=2&side=BOTH&symbol=AGIX-USDT&timestamp=1713782244166&signature=2ecd7dddb54eb2b1a8a9ce98d35b227b7c8620dead0e8d64890f423b96eb837e 
RequestHeaders: {'X-BX-APIKEY': 'dV8cJs51UicOlpvy6aZi3EMaGm3g5n3qsPRQTRbJOwZLYpufEDhVpCKRdc13EwCp1FlGi0CKaQZ1EkOqTiopvg', 'X-SOURCE-KEY': 'CCXT', 'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} 
RequestBody: None
```

```
fetch Response: bingx POST https://open-api.bingx.com/openApi/swap/v2/trade/leverage?leverage=2&side=BOTH&symbol=AGIX-USDT&timestamp=1713782244166&signature=2ecd7dddb54eb2b1a8a9ce98d35b227b7c8620dead0e8d64890f423b96eb837e 200 
ResponseHeaders: {'Date': 'Mon, 22 Apr 2024 10:37:24 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-SOURCE-KEY': 'CCXT', 'CF-Cache-Status': 'DYNAMIC', 'Set-Cookie': '__cf_bm=HMd4KvxCsBOpONR4B8Cv6MAuGqQDLNCXpfXpaETsSUI-1713782244-1.0.1.1-wXi_2U6m.0yQtwn_hs.w8LPkf4BOnBV_P8IGHxrqa0pQflmjLMbE_8Pxj9lCeQssjaeoHnPa5K08lE.POTJaeQ; path=/; expires=Mon, 22-Apr-24 11:07:24 GMT; domain=.bingx.com; HttpOnly; Secure; SameSite=None, _cfuvid=xvRx9g_7X7zgjUjp1vFrtMCktFSJX.JVMlITVpT.B.E-1713782244454-0.0.1.1-604800000; path=/; domain=.bingx.com; HttpOnly; Secure; SameSite=None', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '8784fa7228502d7a-ARN', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400'} 
ResponseBody: {"code":0,"msg":"","data":{"leverage":2,"symbol":"AGIX-USDT","availableLongVol":"0","availableShortVol":"0","availableLongVal":"0.0000","availableShortVal":"0.0000","maxPositionLongVal":"0.0000","maxPositionShortVal":"0.0000"}}
```

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @germangar,
The requests seems well-formed, we will take a look.

**Comment by carlosmiei** [comment]
@germangar Also your last log seems to be from a successful response:

>  ResponseBody: {"code":0,"msg":"","data":{"leverage":2,"symbol":"AGIX-USDT","availableLongVol":"0","availableShortVol":"0","availableLongVal":"0.0000","availableShortVal":"0.0000","maxPositionLongVal":"0.0000","maxPositionShortVal":"0.0000"}}

**Comment by germangar** [comment]
> @germangar Also your last log seems to be from a successful response:
> 
> > ResponseBody: {"code":0,"msg":"","data":{"leverage":2,"symbol":"AGIX-USDT","availableLongVol":"0","availableShortVol":"0","availableLongVal":"0.0000","availableShortVal":"0.0000","maxPositionLongVal":"0.0000","maxPositionShortVal":"0.0000"}}

You're right. It turns out my error was moved from the setLeverage call to the order call but they looked almost the same and I didn't notice. Adding positionSide:BOTH to the order fixed it.

**Comment by iZnogoude** [comment]
@germangar 
Hello, I really like your projet, and it's working very fine. I'm using a tradding bot with tradingview and I use BingX as broker.
I din't know were to post my question, but it's related to the leverage limit :
I have this message in my log :
* WARNING: Leverage out of bounds. Readjusting to 5x
Is this limit is coming from the broker or it's relatedd to the whook script?

Thanks a lot !

**Comment by germangar** [comment]
> @germangar Hello, I really like your projet, and it's working very fine. I'm using a tradding bot with tradingview and I use BingX as broker. I din't know were to post my question, but it's related to the leverage limit : I have this message in my log :
> 
> `* WARNING: Leverage out of bounds. Readjusting to 5x`
> 
> Is this limit is coming from the broker or it's relatedd to the whook script?
> 
> Thanks a lot !

Hello,

The leverage limits are provided by the exchange but 5x doesn't look like a correct value.

But this is not the right place to discuss it. We're generating notifications for carlosmiei which aren't related to ccxt.
Could you please open a new issue [here](https://github.com/germangar/whook/issues) ?
Add in the description what coin you were trading and the margin mode and leverage you were using too, so I can try to reproduce it.

Thanks.
