### ISSUE TITLE
Throttler wrong cost calculation. C#

### ISSUE THREAD

**Issue by skuvv** [ccxt/ccxt#22234]
### Operating System

Windows 10

### CCXT Version

4.3.4

### Description

Wrong cost calculations for Throttler.
Finally, I have found a problem for LoadMarkets 
[https://github.com/ccxt/ccxt/issues/22190](url)

I checked the throttler and found this:
![image](https://github.com/ccxt/ccxt/assets/39260996/d3d2ddc3-2aed-4e8b-aa6e-7af0e4986697)

So next task is waiting for about two hours )
In case of LoadMarkets it's waiting for second request fetchMarkets().
Missed CultureInfo.InvariantCulture for .ToString()

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @skuvv, thanks a lot for reporting it, very weird that we can't see this locally 😅, we will fix it asap.

**Comment by skuvv** [comment]
Looks like working now, thanks. 
It was a bit painful -)
