### ISSUE TITLE
JS ClosePosition and CloseAllPositions For BitGet Missing - In Documentation Not In Code

### ISSUE THREAD

**Issue by dragmecom** [ccxt/ccxt#22231]
### Programming Languages

JavaScript

### CCXT Version

Latest

### Description

The JS CCXT Library seems to be missing the vital feature of closing a trade using the closePosition() or closeAllPositions() per documentation, when querying the bitget market object... these are are the endpoints, neither of the two functions are in it on the JavaScript library, am I crazy or is it actually missing?

 has: {
    publicAPI: true,
    privateAPI: true,
    CORS: undefined,
    spot: true,
    margin: false,
    swap: true,
    future: true,
    option: false,
    addMargin: true,
    cancelAllOrders: true,
    cancelOrder: true,
    cancelOrders: true,
    createDepositAddress: undefined,
    createLimitOrder: true,
    createMarketOrder: true,
    createOrder: true,
    createPostOnlyOrder: undefined,
    createReduceOnlyOrder: false,
    createStopOrder: undefined,
    createStopLimitOrder: undefined,
    createStopMarketOrder: undefined,
    editOrder: true,
    fetchAccounts: false,
    fetchBalance: true,
    fetchBidsAsks: undefined,
    fetchBorrowInterest: undefined,
    fetchBorrowRate: false,
    fetchBorrowRateHistory: false,
    fetchBorrowRatesPerSymbol: false,
    fetchBorrowRates: false,
    fetchCanceledOrders: true,
    fetchClosedOrder: undefined,
    fetchClosedOrders: true,
    fetchCurrencies: true,
    fetchDeposit: undefined,
    fetchDepositAddress: true,
    fetchDepositAddresses: false,
    fetchDepositAddressesByNetwork: undefined,
    fetchDeposits: true,
    fetchTransactionFee: undefined,
    fetchTransactionFees: undefined,
    fetchFundingHistory: true,
    fetchFundingRate: true,
    fetchFundingRateHistory: true,
    fetchFundingRates: false,
    fetchIndexOHLCV: false,
    fetchL2OrderBook: true,
    fetchLastPrices: undefined,
    fetchLedger: true,
    fetchLedgerEntry: undefined,
    fetchLeverageTiers: false,
    fetchMarketLeverageTiers: false,
    fetchMarkets: true,
    fetchMarkOHLCV: false,
    fetchMyTrades: true,
    fetchOHLCV: true,
    fetchOpenInterest: true,
    fetchOpenInterestHistory: false,
    fetchOpenOrder: undefined,
    fetchOpenOrders: true,
    fetchOrder: true,
    fetchOrderBook: true,
    fetchOrderBooks: undefined,
    fetchOrders: false,
    fetchOrderTrades: true,
    fetchPermissions: undefined,
    fetchPosition: true,
    fetchPositions: true,
    fetchPositionsRisk: false,
    fetchPremiumIndexOHLCV: false,
    fetchStatus: 'emulated',
    fetchTicker: true,
    fetchTickers: true,
    fetchTime: true,
    fetchTrades: true,
    fetchTradingFee: true,
    fetchTradingFees: true,
    fetchTradingLimits: undefined,
    fetchTransactions: undefined,
    fetchTransfers: true,
    fetchWithdrawAddresses: undefined,
    fetchWithdrawal: false,
    fetchWithdrawals: true,
    reduceMargin: true,
    setLeverage: true,
    setMargin: undefined,
    setMarginMode: true,
    setPositionMode: true,
    signIn: undefined,
    transfer: true,
    withdraw: false,
    fetchBorrowRateHistories: false,
    fetchLeverage: true,
    fetchMarginMode: undefined,
    fetchPositionMode: false,
    fetchTransfer: false
  }

### Code

```
  var config = require('./config');
var ccxt = require('ccxt');
const fs = require('fs');
const http = require('http');
const https = require('https');
const express = require('express');
const bodyParser = require('body-parser');

const app = express();
const test = false;
app.use(bodyParser.json());

var exchange = new ccxt.bitget({
        'apiKey': config.API_KEY,
        'secret': config.SECRET_KEY,
        'password' : config.PASSPHRASE,
        "options": {'defaultType': 'swap', 'adjustForTimeDifference' : true}
    });
    
    exchange.closePosition("ETH/USDT")
    // or...
    exchange.closeAllPositions()

```

**Comment by carlosmiei** [comment]
Hello @dragmecom, can you please double-check your ccxt version? Bitget definitely has `closePosition` and `closeAllPositions` implemented.
