### ISSUE TITLE
okx {"msg":"Request header OK-ACCESS-PASSPHRASE incorrect.","code":"50105"}

### ISSUE THREAD

**Issue by block98ct** [ccxt/ccxt#22265]
### Operating System

ubuntu

### Programming Languages

JavaScript

### CCXT Version

^4.3.6

### Description

I am passing correct passphrase then also I am getting the same error again and again 
I have check it several times

### Code

```
 const okxExchange = new ccxt.okx({
  apiKey: "my-api-key",
  secret: "my-secret-key",
  password: "my-password",
  passPharse: "Helloworldiamhere@98",
});

```

**Comment by carlosmiei** [comment]
Hello @block98ct,
you should provide the `passphrase` as `password` to ccxt, example

```Javascript
 const okxExchange = new ccxt.okx({
  apiKey: "my-api-key",
  secret: "my-secret-key",
  password: "my-api-passphrase",
});
```

**Comment by block98ct** [comment]
Thanks for the quick response
Is this the same for kucoin also??

**Comment by block98ct** [comment]
@carlosmiei  thanks for your help 
now it's working

**Comment by carlosmiei** [comment]
@block98ct Cool, will close this issue then, let us know if anything!
