### ISSUE TITLE
New Exchange: tidebit

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#2226]
api doc: https://www.tidebit.com/swagger
api doc: https://www.tidebit.com/documents/api/guide
url: https://www.tidebit.com
src: https://gist.github.com/hpyhacking/b13fb1aa4ceb4d0a70371a963673482c#file-trade_data_example-json

**Comment by jjhesk** [comment]
<img width="215" alt="2018-03-13 2 57 34" src="https://user-images.githubusercontent.com/629338/37326862-f836f4de-26ce-11e8-93ac-7003b3e8a280.png">

**Comment by jjhesk** [comment]
<img width="64" alt="2018-03-15 9 25 14" src="https://user-images.githubusercontent.com/629338/37465926-71cf3968-2897-11e8-853f-e2a039649419.png">

**Comment by calvinchankf** [comment]
here is the api doc
https://www.tidebit.com/swagger

**Comment by jjhesk** [comment]
@calvinchankf does it have api key and api secret to offer?

**Comment by calvinchankf** [comment]
@jjhesk yes. once u open an acc, u can generate your `access_key` and `secret_key` in the `settings(profile)` page

![screen shot 2018-03-29 at 12 00 03 pm](https://user-images.githubusercontent.com/5404455/38069452-0a9c18ee-3349-11e8-981e-32eeb0e1c88f.png)

and the i guess the description is the way to sign(i hvn't tried)
![screen shot 2018-03-29 at 12 03 21 pm](https://user-images.githubusercontent.com/5404455/38069541-7e387d1a-3349-11e8-9f93-6426b08a442c.png)

@jjhesk is it what u r looking for?

**Comment by jjhesk** [comment]
yes, im clear now.
