### ISSUE TITLE
Migration to version 4

### ISSUE THREAD

**Issue by uiii** [ccxt/ccxt#22269]
### Programming Languages

JavaScript

### CCXT Version

3

### Description

I have a project which I last worked on in May 2023, so I use ccxt version 3. I tried but haven't find any migration guide from 3 to 4. Are there some things I should be careful about when upgrading? Are there any breaking changes?

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @uiii,
I would say that the transition should be smooth, most of the updates are fixes and API upgrades.
