### ISSUE TITLE
Coinmarketcap ccxt example code fails

### ISSUE THREAD

**Issue by mmehrle** [ccxt/ccxt#22278]
### Operating System

Mac

### Programming Languages

Python

### CCXT Version

4.2.99

### Description

See the simple example below, which now fails with the following:

> AttributeError: module 'ccxt' has no attribute 'coinmarketcap'

Admittedly that was an old example I found in the documentation. What's the latest way of accomplishing this?

FYI - I'm interested in retrieving market cap data on all major crypto coins.

Thanks in advance.

### Code

```
import ccxt
cmc = ccxt.coinmarket ()
cmc.load_products ()
cmc.fetch_tickers () 

```

**Comment by ttodua** [comment]
Coinmarketcap has been delisted from ccxt in the past and is not available. Users are highly recommended to read the CCXT manual (https://docs.ccxt.com/) to find out all things that are supported by CCXT.
Let us know if you have any further issues while using CCXT
