### ISSUE TITLE
xbtce create_order not working in PHP

### ISSUE THREAD

**Issue by JT102** [ccxt/ccxt#2228]
- OS: Linux
- Programming Language version: PHP
- CCXT version: 1.11.80
- Exchange: xbtce
- Method: create_order

Doesn't create order and returns an exception: _[Exchange Error] tapiPostTrade not found (ignoring)_, no other verbose output.
This is at line 285 in xbtce.php and there is no such function really.
Is it not implemented or what?

**Comment by JT102** [comment]
@kroitor can you please comment if it's a bug please?

**Comment by kroitor** [comment]
@JT102 yes, it is a bug, I'll get to it soon, and will let you know upon fixing. Thx for reporting and for your patience.

**Comment by belsebob90** [comment]
Well hope i can bee to help

Den fre 16 mars 2018 19:18Igor Kroitor <notifications@github.com> skrev:
