### ISSUE TITLE
Wrong channel for Watch MyTrades. C#

### ISSUE THREAD

**Issue by skuvv** [ccxt/ccxt#22295]
### Operating System

Windows 10

### CCXT Version

4.3.6

### Description

```
await exchange.WatchMyTrades
```
opens wrong channel 'orders' for trades:
```
Sending message: {"op":"subscribe","args":[{"instType":"SUSDT-FUTURES","channel":"orders","instId":"default"}]}
On message: {"event":"subscribe","arg":{"instType":"SUSDT-FUTURES","channel":"orders","instId":"default"}}
```
From docs:
```
{
    "op": "subscribe",
    "args": [
        {
            "instType": "USDT-FUTURES",
            "channel": "fill",
            "instId": "default"
        }
    ]
}
```

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @skuvv, 

Previously we didn't have the `fill` channel at bitget, but i think we can emulate it with `orders` because an event is sent every time an orders if filled, did you find a weird behavior with the current implementation of `watchMyTrades` ?
![image](https://github.com/ccxt/ccxt/assets/43336371/7c9b1e10-da63-4f79-b564-47073efad0b1)

**Comment by carlosmiei** [comment]
(nonetheless I will try to update it)

**Comment by skuvv** [comment]
At least OrderId is null when it cast raw info to MyTrade

**Comment by skuvv** [comment]
@carlosmiei 
CCXT Version:4.3.13
I see more info now, correct channel, but wrong orderId for trade (Bitget):
![image](https://github.com/ccxt/ccxt/assets/39260996/b47966b2-d041-458f-bd2e-091145508d65)
```
On message: {"action":"snapshot","arg":{"instType":"SCOIN-FUTURES","channel":"fill","instId":"default"},"data":[{"orderId":"1169836950450511873","tradeId":"1169836950740348929","symbol":"SETHSUSD","orderType":"market","side":"buy","price":"2922.03","baseVolume":"0.1","quoteVolume":"292.203","profit":"0","tradeSide":"open","posMode":"hedge_mode","tradeScope":"taker","feeDetail":[{"feeCoin":"SETH","deduction":"no","totalDeductionFee":"0","totalFee":"-0.00006003"}],"cTime":"1714636784253","uTime":"1714636784253"}],"ts":1714636784259}
```

**Comment by carlosmiei** [comment]
@skuvv Thanks for debugging it, will take a look as soon as possible

**Comment by carlosmiei** [comment]
@skuvv You're right, we had a typo in the `Trade` structure, but will be fixed asap
