### ISSUE TITLE
KUCOIN create stop limit doesnt work properly

### ISSUE THREAD

**Issue by incafox** [ccxt/ccxt#22314]
### Operating System
mac

### Programming Languages
python

### CCXT Version

4.2.74

### Description

Hi, when im using Kucoin web I can put a stop - limit order with a trigger condition (enter price, bigger than the current price) but using stop-limit in ccxt always ends buying/entering at the current/last price, how can I put an order with a trigger condition using ccxt?. 

pic: stop - limit order with trigegr condition using kucoin web
<img width="771" alt="image" src="https://github.com/ccxt/ccxt/assets/4401153/425499ca-2a76-4974-a631-f2748709c83d">
 

### Code

```
  
long_price = (1.3) * last 
short_price = (3) * last

result = exchange.create_stop_limit_order(
        "DPET/USDT", 
        side='buy', 
        amount=100,
        price=short_price,
        stopPrice=long_price,
         )

```

**Comment by carlosmiei** [comment]
Hello @incafox,
I don't see that option in the WEB UI, so I think it follows the same logic as the API

If the stopPrice is smaller than the current price then the condition will be trigger <=stopPrice, otherwise >=stopPrice

![image](https://github.com/ccxt/ccxt/assets/43336371/872ef63d-1b7d-4c1b-a6aa-e97d59a5ef97)

**Comment by incafox** [comment]
hello @carlosmiei here in this example using the WEB UI you can see the current price is 0.05396 and I created an Buy Stop-Limit order with stop price->0.06 , price->0.1. So the trigger condition to buy 100 DPET is current price >= 0.06 and sell condition is 0.1, you can see that in advanced orders section (screenshot). 

<img width="281" alt="Place Order x" src="https://github.com/ccxt/ccxt/assets/4401153/a46cc880-8128-4b51-9057-125fe71bb837">
<img width="1176" alt="Pasted Graphic 1" src="https://github.com/ccxt/ccxt/assets/4401153/9a2ba4a0-f5ae-4ec5-a0c9-d6771d80df67">

Im trying to do the same with CCXT-Kucoin :

```
long_price = (1.3) * current_price 
short_price = (3) * current_price

result = exchange.create_stop_limit_order(
        "DPET/USDT", 
        side='buy', 
        amount=100,
        price=short_price,
        stopPrice=long_price
)
``` 

So using my example above the enter price(long_price) should be 1.3 * 0.05396 = 0.0701 and short_price = 3 * 0.05396 = 0.161, but unfortunately create_stop_limit_order is buying instantly at the current price instead of setting a trigger condition correctly.

**Comment by carlosmiei** [comment]
@incafox Ok I think I managed to reproduce the issue, can you please try to provide this in params?

```Python
result = exchange.create_stop_limit_order(
        "DPET/USDT", 
        side='buy', 
        amount=100,
        price=short_price,
        stopPrice=long_price,
        {"stop": "entry"}
)
```

For some reason, if we don't provide it, it executes immediately.

**Comment by incafox** [comment]
thank you @carlosmiei !
