### ISSUE TITLE
ping-pong error

### ISSUE THREAD

**Issue by karambaq** [ccxt/ccxt#22321]
### Operating System

MacOS

### Programming Languages

Python

### CCXT Version

latest

### Description

ccxt.base.errors.RequestTimeout: Connection to wss://stream-testnet.bybit.com/v5/private timed out due to a ping-pong keepalive missing on time

### Code

```
  

```

**Comment by Wihandebeer** [comment]
I also have the same issue, but with MEXC

**Comment by carlosmiei** [comment]
Hello @karambaq @Wihandebeer, what's the best way of reproducing this issue locally?

**Comment by samgermain** [comment]
> ### Operating System
> 
> MacOS
> ### Programming Languages
> 
> Python
> ### CCXT Version
> 
> latest
> ### Description
> 
> ccxt.base.errors.RequestTimeout: Connection to wss://stream-testnet.bybit.com/v5/private timed out due to a ping-pong keepalive missing on time
> ### Code
> 
> ```
>   
> ```

Please share the CCXT version instead of writing latest, there was a fix to this issue merged in https://github.com/ccxt/ccxt/pull/22262

**Comment by karambaq** [comment]
@samgermain 

I'm using version 4.3.19 and still facing this error.

**Comment by samgermain** [comment]
> @samgermain
> 
> I'm using version 4.3.19 and still facing this error.

Can you provide some details? How long is your program running before you receive the error?

**Comment by samgermain** [comment]
> ### Operating System
> 
> MacOS
> ### Programming Languages
> 
> Python
> ### CCXT Version
> 
> latest
> ### Description
> 
> ccxt.base.errors.RequestTimeout: Connection to wss://stream-testnet.bybit.com/v5/private timed out due to a ping-pong keepalive missing on time
> ### Code
> 
> ```
>   
> ```

Sorry for the delay. [This PR](https://github.com/ccxt/ccxt/pull/22585) should fix this issue according to the tests I've been running, and I'll continue to monitor if the error re-occurs and make updates as necessary

**Comment by samgermain** [comment]
> I also have the same issue, but with MEXC

[This PR](https://github.com/ccxt/ccxt/pull/22764) fixes the issue according to the tests I have been running, I'll continue to monitor if the error re-occurs
