### ISSUE TITLE
how could i get the return  when the deal is done after sending the orders with the function  create_limit_sell_order or create_limit_buy_order

### ISSUE THREAD

**Issue by wangjun92** [ccxt/ccxt#2232]
- OS: windows
- Programming Language version:  python 3.6.3
- CCXT version: 1.11.77
- Exchange: binance huobipro
- Method: create_limit_sell_order or create_limit_buy_order

**Comment by wangjun92** [comment]
how to get the return with the deal done

**Comment by kroitor** [comment]
Hi! 

The orders API is documented here: https://github.com/ccxt/ccxt/wiki/Manual#orders

```
order = exchange.create_limit_buy_order(...)
print('create_limit_buy_order result:', order)
# ...
order = exchange.fetch_order(order['id'])
print('fetch_order result:', order)
```

Let us know if it does not help. Thx!

**Comment by wangjun92** [comment]
shoud I call the the following function all the time until I get the return  if the deal is done?
order = exchange.fetch_order(order['id'])
print('fetch_order result:', order)

**Comment by wangjun92** [comment]
@kroitor 
shoud I call the the following function all the time until I get the return if the deal is done?
order = exchange.fetch_order(order['id'])
print('fetch_order result:', order)

**Comment by kroitor** [comment]
@wangjun92 I'd recommend to read the entire Manual as you have to be careful and there's a lot of important info there, you cannot do that as frequently as you would want, unfortunately, or the exchange will ban you. So, you have to limit the rate of your requests or use a built-in rate-limiter. But this is a very wide topic to be explained in a single issue, for that the docs and examples are written:

- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/tree/master/examples

Please read it very carefully and pay attention if you want to use this library effectively. This will save you a lot of time, really. Hope it helps.
