### ISSUE TITLE
python static method parse_date() incorrectly parse for some minutes or hour values with leading zeros

### ISSUE THREAD

**Issue by DelAnt** [ccxt/ccxt#22329]
### Operating System

macos

### Programming Languages

Python

### CCXT Version

4.2.100

### Description

The parse_date static method in exchange.py does not correctly handle minute values in the range 00 through 05. Similar problems are also seen with hour range 00-02
During the conversion process the minutes are converted to values and back to strings and joined. Minutes like 01 are converted to 1. The seconds values from the final concatenated string are than part of the minutes and not seconds.

Example
`exchange.parse_date('Mon, 29 Apr 2024 14:03:17 GMT')
`
Will become:
`1714401067000
`
However
`exchange.iso8601(1714401067000)` is ` '2024-04-29T14:31:07.000Z'`

More examples:
Bad:
```python
exchange.iso8601(exchange.parse_date('Mon, 29 Apr 2024 14:00:17 GMT'))
'2024-04-29T14:01:07.000Z'
```
Good:
```python
exchange.iso8601(exchange.parse_date('Mon, 29 Apr 2024 14:09:17 GMT'))
'2024-04-29T14:09:17.000Z'
```

Same problem seen when hours value is 01:
```python
exchange.iso8601(exchange.parse_date('Mon, 29 Dec 2024 01:01:10 GMT'))
'2024-12-29T11:01:00.000Z'
```

A potential solution is to use str.rjust(2, '0') and add '0' padding.
This solution was quickly tested locally:
OLD
```
In [97]: exchange.iso8601(exchange.parse_date('Mon, 29 Dec 2024 02:11:10 GMT'))
Out[97]: '2024-12-29T21:11:00.000Z'
```
NEW
```
In [15]: exchange.iso8601(exchange.parse_date('Mon, 29 Dec 2024 02:11:10 GMT'))
Out[15]: '2024-12-29T02:11:10.000Z'
```

### Code

```python
--- a/python/ccxt/base/exchange.py
+++ b/python/ccxt/base/exchange.py
@@ -1216,7 +1216,7 @@ class Exchange(object):
             return None
         if 'GMT' in timestamp:
             try:
-                string = ''.join([str(value) for value in parsedate(timestamp)[:6]]) + '.000Z'
+                string = ''.join([str(value).rjust(2, '0') for value in parsedate(timestamp)[:6]]) + '.000Z'
                 dt = datetime.datetime.strptime(string, "%Y%m%d%H%M%S.%fZ")
                 return calendar.timegm(dt.utctimetuple()) * 1000
             except (TypeError, OverflowError, OSError):
```

**Comment by carlosmiei** [comment]
Hello @DelAnt, thanks a lot for reporting it; we will take a look and let you know as soon as possible.

**Comment by ttodua** [comment]
I'll push a fix within a hour. thanks for report.
