### ISSUE TITLE
KeyError: 'fetchConvertTradeHistory' in exchange.has['fetchConvertTradeHistory'] - on phemex

### ISSUE THREAD

**Issue by egabosh** [ccxt/ccxt#22330]
### Operating System

Debian 12

### Programming Languages

Python

### CCXT Version

4.3.11

### Description

Moin,

for my understanding I can use "if exchange.has['fetchConvertTradeHistory']:" to check if there is the wanted method.
Running it on binance where the method exists all workd fine. On phemex I get the following error:
```
Traceback (most recent call last):
  File "/root/fetch-orders.py", line 65, in <module>
    if exchange.has['fetchConvertTradeHistory']: 
       ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'fetchConvertTradeHistory'
```
For my understanding there should be "x" printed.
Any Ideas whats going wrong?

### Code

```
if exchange.has['fetchConvertTradeHistory']:
  print(exchange.fetchConvertTradeHistory(limit=200, since=1685700951930, params={'until': 1685700951932}))
else:
  print('x')
```

**Comment by carlosmiei** [comment]
Hello @egabosh, thanks for reporting it, it is indeed a bug on our side, but we will fix it asap.
