### ISSUE TITLE
how to test a single exchange

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#2234]
@kroitor would you add more doc for how to speed up the development time with `run-tests` to test against a single exchange in the folder of js.

i tried 
`node run-tests --js --myexchange` but it doesnt work.

**Comment by kroitor** [comment]
@jjhesk 

> would you add more doc for how to speed up the development time with run-tests to test against a single exchange in the folder of js.

Yep, will add some more clarifications on that shortly.

> i tried `node run-tests --js --myexchange` but it doesnt work.

You should try `node run-tests --js myexchange` (the exchange id without `--`). Hope it helps. Let us know if not. Thx!

**Comment by jjhesk** [comment]
@kroitor is there a way that i can turn on a watch mode to test against one exchange in realtime? so that people can create exchange with light speed =)

**Comment by kroitor** [comment]
@jjhesk 👍 well, not yet (unfortunately), but mocha can run some tests in "watch mode" and relaunch them upon any change. We hope to migrate to mocha testing soon, after solving the arbitrary precision tasks, probably together with the other pending work. The idea is great, of course, we just didn't have enough time to set up all proper testing settings yet, most of tests are still in progress as well.
