### ISSUE TITLE
Kraken active flag giving false postive

### ISSUE THREAD

**Issue by mayrsascha** [ccxt/ccxt#22341]
### Operating System

macOS Sonoma 14.2.1

### Programming Languages

JavaScript

### CCXT Version

4.3.11

### Description

Some trading pairs have the `active` flag set to true for the Kraken exchange, even though they are in `cancel_only` mode on Kraken, meaning the only thing you can do is cancel existing trades. Actually that's not even true anymore since April 5, see [this](https://support.kraken.com/hc/en-us/articles/notice-of-spot-trading-pairs-removal).

Also according to the [public tradeable assets API](https://api.kraken.com/0/public/AssetPairs) multiple trading pairs, i.e. ZEC/BTC are 'cancel_only', so not sure why the active flag is still true for them.

### Code

```
const kraken = new ccxt.pro.kraken()
console.log(kraken.markets['ZEC/BTC'].active) // true
```

**Comment by carlosmiei** [comment]
Hello @mayrsascha, thanks for reporting it. You're right in that case `active` should be false, we will fix it shortly.
