### ISSUE TITLE
test with --watch mode

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#2235]
from the topic #2234. There should be a watch mode to allow devs to test develop the api with realtime. features should allow the script to clear up the console and reprint the test detail in the console screen. 

 - [ ] mocha integrations
 - [ ] integrations with extra options
 - [ ] cls abilities

**Comment by jjhesk** [comment]
- [ ] mocha integrations
 - [ ] integrations with extra options

**Comment by ttodua** [comment]
@kroitor is this topic still actual? @carlosmiei maybe you have some thoughts?

**Comment by frosty00** [comment]
closing because the question is ambiguous
