### ISSUE TITLE
Docs: wrong reference URL for binance swap in method fetchLastPrices()

### ISSUE THREAD

**Issue by notanymore** [ccxt/ccxt#22379]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.2.14

### Description

Where the problem is: https://docs.ccxt.com/#/exchanges/binance?id=fetchticker
Which URL is wrong (missing a 's' after 'future'): https://binance-docs.github.io/apidocs/future/en/#symbol-price-ticker // swap
What is the correct URL: https://binance-docs.github.io/apidocs/futures/en/#symbol-price-ticker // swap

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @notanymore, thanks a lot for reporting it, we will fix it asap.
