### ISSUE TITLE
load_leverage_brackets returns auth error

### ISSUE THREAD

**Issue by daviidarr** [ccxt/ccxt#22397]
### Operating System

ubunutu

### Programming Languages

Python

### CCXT Version

4.3.16

### Description

response = await self.papiGetUmLeverageBracket(query)
throws
ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action, request ip: ..."}

### Code

```
await ccxt.pro.binance([all api keys]).fetch_leverage_tiers(reload=True,
                                                                                  params={'portfolioMargin': True,
                                                                                          'type': 'swap',
                                                                                          'subtype': 'linear'})
```

**Comment by sc0Vu** [comment]
Hi @daviidarr 

Before use portfolio margin api in binance, please make sure that:

* you're vip1+ and you manually activated the portfolio margin in the binance-futures page
* your API key was created after the activation was completed.

**Comment by daviidarr** [comment]
Ok, so param.portfoliomargin does not override the actual status of my
account.
Thanks for clarification.

**Comment by daviidarr** [comment]
Thanks for clarifying that param does not override actual account status.

**Comment by carlosmiei** [comment]
@daviidarr `params.portfolioMargin` just tells ccxt to use the portfolioMargin endpoint, but your account/API keys need to be properly configured first.
