### ISSUE TITLE
Issue with too many subscriptions using watch_tickers()

### ISSUE THREAD

**Issue by jabranzahid-dev** [ccxt/ccxt#22409]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.3.16

### Description

Hi,
I am trying to pull the prices from binance using watch_tickers() for large number of symbols. As I understand it, I get a new message for each subscription for each symbol whenever the state of the orderbook changes for that symbol, with each message having a different timestamp.
This works for me until I have subscribed to only 10 or 20 symbols, but when I increase it to 50, 100 or 200, I keep getting new messages for all symbols subscribed whenever the orderbook changes (as expected) but the content of the message doesn't change (incl the timestamp). For example, here I had subscribed to 200 symbols and the two messages I got for BTC-USDT are

('BTC/USDT', {'symbol': 'BTC/USDT', 'timestamp': 1715004657528, 'datetime': '2024-05-06T14:10:57.528Z', 'high': 65500.0, 'low': 63343.86, 'bid': 63939.99, 'bidVolume': 4.15377, 'ask': 63940.0, 'askVolume': 1.12973, 'vwap': 64274.38729331, 'open': 63852.32, 'close': 63940.0, 'last': 63940.0, 'previousClose': 63852.31, 'change': 87.68, 'percentage': 0.137, 'average': 63896.16, 'baseVolume': 29775.52971, 'quoteVolume': 1913803928.4439926, 'info': {'e': '24hrTicker', 'E': 1715004657529, 's': 'BTCUSDT', 'p': '87.68000000', 'P': '0.137', 'w': '64274.38729331', 'x': '63852.31000000', 'c': '63940.00000000', 'Q': '0.00156000', 'b': '63939.99000000', 'B': '4.15377000', 'a': '63940.00000000', 'A': '1.12973000', 'o': '63852.32000000', 'h': '65500.00000000', 'l': '63343.86000000', 'v': '29775.52971000', 'q': '1913803928.44399250', 'O': 1714918257528, 'C': 1715004657528, 'F': 3587756579, 'L': 3589030073, 'n': 1273495}})

('BTC/USDT', {'symbol': 'BTC/USDT', 'timestamp': 1715004657528, 'datetime': '2024-05-06T14:10:57.528Z', 'high': 65500.0, 'low': 63343.86, 'bid': 63939.99, 'bidVolume': 4.15377, 'ask': 63940.0, 'askVolume': 1.12973, 'vwap': 64274.38729331, 'open': 63852.32, 'close': 63940.0, 'last': 63940.0, 'previousClose': 63852.31, 'change': 87.68, 'percentage': 0.137, 'average': 63896.16, 'baseVolume': 29775.52971, 'quoteVolume': 1913803928.4439926, 'info': {'e': '24hrTicker', 'E': 1715004657529, 's': 'BTCUSDT', 'p': '87.68000000', 'P': '0.137', 'w': '64274.38729331', 'x': '63852.31000000', 'c': '63940.00000000', 'Q': '0.00156000', 'b': '63939.99000000', 'B': '4.15377000', 'a': '63940.00000000', 'A': '1.12973000', 'o': '63852.32000000', 'h': '65500.00000000', 'l': '63343.86000000', 'v': '29775.52971000', 'q': '1913803928.44399250', 'O': 1714918257528, 'C': 1715004657528, 'F': 3587756579, 'L': 3589030073, 'n': 1273495}})

As you can see, the timestamps are the same and the rest of the content. Any advice appreciated.

Thanks

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @jabranzahid-dev, Does that happen immediately?  the duplicated values

**Comment by jabranzahid-dev** [comment]
> Hello @jabranzahid-dev, Does that happen immediately? the duplicated values

yes immediately. I mean the values do eventually change but after a while, so basically I am not getting prices in realtime, i.e. the frequency at which the values change depend on how many symbols I am subscribed to, for example, if I increase the symbols in the regions of 50-100, the values update every few seconds (for BTC/USDT I expect the values to change in every message right?), but I increase the symbols to 500, the values will change may be after 45 seconds BUT I will keep receiving new messages for every symbol. Hope I have explained correctly :)

**Comment by carlosmiei** [comment]
@jabranzahid-dev I was trying to debug this issue by running the snippet below, but although some messages have the same last price and some other common fields, I don't see duplicated timestamps (which would be a red flag)

```Python
    cache = {}
    markets = await exchange.load_markets(True)
    # exchange.verbose = True
    spot_markets = [market['symbol'] for market in markets.values() if market['spot']][:200]
    while True:
        tickers = await exchange.watch_tickers(spot_markets)
        for ticker_symbol in tickers:
            ticker = tickers[ticker_symbol]
            if ticker_symbol not in cache:
                cache[ticker_symbol] = ticker
            else:
                if ticker['last'] == cache[ticker['symbol']]['last']:
                    print('No change in price for', ticker['symbol'])
                    print('Timestamps:', ticker['timestamp'], cache[ticker['symbol']]['timestamp'])
                if ticker['timestamp'] == cache[ticker['symbol']]['timestamp']:
                    print('No change in timestamp for', ticker['symbol'])
                cache[ticker['symbol']] = ticker
```

**Comment by carlosmiei** [comment]
@jabranzahid-dev Actually after some time I got a duplicated timestamp as well but that was sent by the exchange in two different messages

```
2024-05-07T10:01:54.302Z message {"e":"24hrTicker","E":1715076113164,"s":"XVGETH","p":"0.00000000","P":"0.000","w":"0.00000173","x":"0.00000175","c":"0.00000174","Q":"2091.00000000","b":"0.00000173","B":"40395.00000000","a":"0.00000174","A":"65980.00000000","o":"0.00000174","h":"0.00000177","l":"0.00000170","v":"11705621.00000000","q":"20.27069206","O":1714989713163,"C":1715076113163,"F":11609979,"L":11611339,"n":1361}



2024-05-07T10:01:54.302Z message {"e":"24hrTicker","E":1715076113164,"s":"XVGETH","p":"0.00000000","P":"0.000","w":"0.00000173","x":"0.00000175","c":"0.00000174","Q":"2091.00000000","b":"0.00000173","B":"40395.00000000","a":"0.00000174","A":"65980.00000000","o":"0.00000174","h":"0.00000177","l":"0.00000170","v":"11705621.00000000","q":"20.27069206","O":1714989713163,"C":1715076113163,"F":11609979,"L":11611339,"n":1361}
```

**Comment by jabranzahid-dev** [comment]
yes maybe if you subscribe to 1000 symbols, you will see duplicated messages straight away. So yes, the messages are coming in from the exchanges but with same content in them, do you think this is issue with exchange or ccxt is not able to handle that many messages coming in ? I tested this few months ago and it was fine back then and I recently picked this project(reinstalled ccxt) and facing this issue so I am not sure if something changed on the exchange end or with CCXT library

**Comment by carlosmiei** [comment]
@jabranzahid-dev I don't think this is an issue with ccxt, the exchange is sending those duplicated messages not ccxt. We will reach out to them to try to clarify this scenario.

**Comment by jabranzahid-dev** [comment]
thanks, I will keep an eye on this thread for any updates, in the meanwhile I will test with other exchanges

**Comment by carlosmiei** [comment]
@jabranzahid-dev Yes I can confirm that the duplicated timestamps come from the exchange directly, as you can see using this snippet that just uses the raw `websockets` package:

Nonetheless, the messages are not 100% equal, some of the fields like `A` are different even though the timestamp is the same.

[ws_demo2.txt](https://github.com/ccxt/ccxt/files/15251308/ws_demo2.txt)

**Comment by jabranzahid-dev** [comment]
Hi, Sorry it was an error in my code, I was subscribing to too many symbols too many times (incorrect exchange/symbol loops) so I think there is no issue. Sorry for inconvenience.  Closing the issue. Regards
