### ISSUE TITLE
watch_ohlcv() really not return error when disable internet connection

### ISSUE THREAD

**Issue by Khanhlinhdang** [ccxt/ccxt#22412]
### Operating System

window 10, 64 bit

### Programming Languages

Python

### CCXT Version

4.3.16

### Description

I use the code below to test watch_ohlcv() function of pro python version 4.3.16, when I disable internet connection to catch error or something else but I dont see anything. So I can't catch the error when internet connect has proplem. The same thing happened when I changed the VPN address. I just want to check if internet connection disconnect, then wait ultil the internet connection come back, and re-connect to the exchange. HOW I CAN DO THAT? help, please. 

### Code

```
 import ccxt.pro
from asyncio import run

print('CCXT Pro version', ccxt.pro.__version__)


def table(values):
    first = values[0]
    keys = list(first.keys()) if isinstance(first, dict) else range(0, len(first))
    widths = [max([len(str(v[k])) for v in values]) for k in keys]
    string = ' | '.join(['{:<' + str(w) + '}' for w in widths])
    return "\n".join([string.format(*[str(v[k]) for k in keys]) for v in values])


async def main():
    exchange = ccxt.pro.binanceusdm({
        # 'options': {
        #     'OHLCVLimit': 1000, # how many candles to store in memory by default
        # },
    })
    symbol = 'BTC/USDT'  # or BNB/USDT, etc...
    timeframe = '1m'  # 5m, 1h, 1d
    limit = 10  # how many candles to return max
    method = 'watchOHLCV'
    if (method in exchange.has) and exchange.has[method]:
        max_iterations = 100000  # how many times to repeat the loop before exiting
        for i in range(0, max_iterations):
            try:
                ohlcvs = await exchange.watch_ohlcv(symbol, timeframe, None, limit)
                now = exchange.milliseconds()
                print('\n===============================================================================')
                print('Loop iteration:', i, 'current time:', exchange.iso8601(now), symbol, timeframe)
                print('-------------------------------------------------------------------------------')
                print(table([[exchange.iso8601(o[0])] + o[1:] for o in ohlcvs]))
            except Exception as e:
                print(type(e).__name__, str(e))
                break
        print(exchange.id, method, 'here is not supported or not implemented yet')
        await exchange.close()
    else:
        print(exchange.id, method, 'is not supported or not implemented yet')


run(main())
 

```

**Comment by pcriadoperez** [comment]
Hi @Khanhlinhdang , in the case of watch methods the server and client realizes there has been a disconnect when there is no response after any ping pong. You can change this time by setting exchange['streaming']['keepAlive'] to a small number and you will see an error shortly after disconnecting your connection.

To keep the watch method connected, evering during an internet interruption you don't have to do anything, as long as you have the watch method inside a while loop with a try catch, as every time the watch method is called, if it is disconnected it will reconnect.

I'll close this issue for now, but feel free to reach out with any questions.

**Comment by Khanhlinhdang** [comment]
`def watch(self, url, message_hash, message=None, subscribe_hash=None, subscription=None):
        # base exchange self.open starts the aiohttp Session in an async context
        self.open()
        backoff_delay = 0
        client = self.client(url)
        if subscribe_hash is None and message_hash in client.futures:
            return client.futures[message_hash]
        future = client.future(message_hash)

        subscribed = client.subscriptions.get(subscribe_hash)

        if not subscribed:
            client.subscriptions[subscribe_hash] = subscription or True

        connected = client.connected if client.connected.done() \
            else asyncio.ensure_future(client.connect(self.session, backoff_delay))

        def after(fut):
            # todo: decouple signing from subscriptions
            options = self.safe_value(self.options, 'ws')
            cost = self.safe_value(options, 'cost', 1)
            if message:
                async def send_message():
                    if self.enableRateLimit:
                        await client.throttle(cost)
                    try:
                        await client.send(message)
                    except ConnectionError as e:
                        client.on_error(e)
                    except Exception as e:
                        client.on_error(e)
                asyncio.ensure_future(send_message())
        # if not subscribed:
        #     connected.add_done_callback(after)
        connected.add_done_callback(after)
        return future`
I was try all method you tell me. but all of it not work correctly. I check in file ccxt\async_support\base\exchange.py. Then I have just close these codes "# if not subscribed:
        #     connected.add_done_callback(after)" and put "connected.add_done_callback(after)" out of if codition, and GOD it was working. Thank for your support.
