### ISSUE TITLE
Kucoin precision

### ISSUE THREAD

**Issue by frosty00** [ccxt/ccxt#2241]
So it seems that kucoin has a hardcoded precision of 8. However I think the relevant precision should be the 'tradePrecision' of the quote currency, in this case eth. Unfortunately this is hard to load into the market at runtime until we have the `loadX` methods in place as `fetchMarkets` is called before `fetchCurrencies`

```>>> k.create_order('OMG/ETH', 'limit', 'buy', 0.9, 0.01712312341321234)
kucoin {"success":false,"code":"ERROR","msg":"The precision of price(ETH) is incorrect. The precision of ETH is 7","timestamp":1520939313195,"data":null}
```

```
>>> k.currencies['ETH']
{'id': 'ETH', 'code': 'ETH', 'info': {'withdrawMinFee': 0.01, 'withdrawMinAmount': 0.1, 'withdrawFeeRate': 0.001, 'confirmationCount': 12, 'withdrawRemark': '', 'infoUrl': None, 'name': 'Ethereum', 
```

**'tradePrecision': 7,**

```
'depositRemark': None, 'enableWithdraw': True, 'enableDeposit': True, 'coin': 'ETH'}, 'name': 'Ethereum', 'active': True, 'status': 'ok', 'fee': 0.01, 'precision': 7, 'limits': {'amount': {'min': 1e-07, 'max': 10000000.0}, 'price': {'min': 1e-07, 'max': 10000000.0}, 'cost': {'min': None, 'max': None}, 'withdraw': {'min': 0.1, 'max': 10000000.0}}}
```

**Comment by kroitor** [comment]
> So it seems that kucoin has a hardcoded precision of 8.

Yep, but that is true for markets, not for currencies.

So, from `createOrder` in `kucoin.js`:

```JavaScript
let request = {
            'symbol': market['id'],
            'type': side.toUpperCase (),
            'price': this.priceToPrecision (symbol, price),
            'amount': this.truncate (amount, this.currencies[base]['precision']),
        };
```

↑ this is why we use currency-precisions here, instead of market precisions...

We hope to resolve this as soon as we get those pending market-loading commits merged (in a few days).

Hope it answers your question. Let me if know if not ) Thx! )

**Comment by frosty00** [comment]
This does not solve the issue. If I were to fix it with the same monkey patch you did it would be:

```
let request = {
            'symbol': market['id'],
            'type': side.toUpperCase (),
            'price': this.truncate (price, this.currencies[quote]['precision']),
            'amount': this.truncate (amount, this.currencies[base]['precision']),
        };
```

If you read the error carefully 

```kucoin {"success":false,"code":"ERROR","msg":"The precision of price(ETH) is incorrect. The precision of ETH is 7","timestamp":1520939313195,"data":null}```

It says the **price** precision is incorrect (it should be 7). Since priceToPrecision uses market (hardcoded) precision it only works for pairs in which BTC is the quote, since it also has a precision of 8. Out of all the possible quote currencies this is the highest precision so it will not work with the other quote currencies kucoin offers.

```
>>> for c in ['BTC', 'ETH', 'NEO', 'USDT', 'KCS', 'BCH']:
            print(c, k.currencies[c]['precision'])

BTC 8
ETH 7
NEO 6
USDT 6
KCS 4
BCH 8

```

**Comment by frosty00** [comment]
> We hope to resolve this as soon as we get those pending market-loading commits merged (in a few days).

Is this refering to the `load` and `loadPublic` etc group of methods or something else?

**Comment by azharuniverse** [comment]
For me this request worked. Its opposite of @frosty00 
```
let request = {
            'symbol': market['id'],
            'type': side.toUpperCase (),
            'price': this.truncate (price, this.currencies[base]['precision']),
            'amount': this.truncate (amount, this.currencies[quote]['precision']),
        };
```

**Comment by frosty00** [comment]
@azharuniverse are you sure? I'll look into it, but I've made ~5 successful trades with my precision configuration. 

I do not think you are right - just go to the kucoin website and look at the different quotes and their relative price precisions. It should be obvious from that. All BTC are 8 and ETH are 7. Perhaps you've gotten your quotes and bases mixed up.
