### ISSUE TITLE
watch status for specific order

### ISSUE THREAD

**Issue by iht76** [ccxt/ccxt#22419]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Describe the solution you'd like

Is there a method to monitor the status changes (such as fill, partial fill or cancellation) for a specific order ID? Like watchOrder(orderID)

**Comment by carlosmiei** [comment]
Hello @iht76, no there is no such thing because exchanges do not provide that level of granularity upon subscribing to the `order` stream. Nonetheless, you can easily emulate this behavior locally using `watchOrders`
