### ISSUE TITLE
Bybit withdraw issue. 

### ISSUE THREAD

**Issue by gelono** [ccxt/ccxt#22421]
### Operating System

ubuntu 20.04

### Programming Languages

Python

### CCXT Version

4.2.12

### Description

I'm trying to withdraw funds from my Bybit (Unified) account. I make a request and get an error in the response. The address is whitelisted.

### Code

    params = {
        "network": "Arbitrum One",
    }
    withdraw_result = await all_ex["Bybit"].withdraw(
        code="USDC",
        amount=usdc_amount,
        address=config.get("account_address"),
        params=params
    )
 
Logs:
ccxt.base.errors.ExchangeError: bybit {"retCode":90034,"retMsg":"Withdraw is not allowed for coin USDC and chain ARBITRUM ONE","result":{},"retExtInfo":{},"time":1715088538119}

**Comment by gelono** [comment]
> hello @gelono, This is not directly related to CCXT, bybit has that chain suspended, so there's nothing ccxt can do about it. ![image](https://private-user-images.githubusercontent.com/43336371/328548095-9d338150-ed10-4334-bb13-bc78ac9d77ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTAxMzYsIm5iZiI6MTcxNTA4OTgzNiwicGF0aCI6Ii80MzMzNjM3MS8zMjg1NDgwOTUtOWQzMzgxNTAtZWQxMC00MzM0LWJiMTMtYmM3OGFjOWQ3N2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDEzNTAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyOTZhNTc1MjU5MDRiNzFlNGY1OWQ2OTQ4YTEzMDI1MzNmZDdjMjYzNDQ2ZmNkNDg1M2I2NDMxNjBlNTg4ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WndBGQv4T3R9Z44eKGJ-320K_gKObrxcSQSuvCb2FNE)

Ok, thank you. I didn't see it.

**Comment by carlosmiei** [comment]
@gelono No problem, will close this issue then, feel free to reopen it if anything!

**Comment by carlosmiei** [comment]
@gelono I see, will check it again then

**Comment by carlosmiei** [comment]
@gelono Can you please post a verbose request?

```
await exchange.load_markets()
exchange.verbose = True
```
(please omit the sensitive parts like the apiKey/address/etc)

**Comment by gelono** [comment]
> await exchange.load_markets()

fetch Request: bybit POST https://api.bybit.com/v5/asset/withdraw/create RequestHeaders: {'Content-Type': 'application/json', 'X-BAPI-API-KEY': '****************', 'X-BAPI-TIMESTAMP': '1715092218664', 'X-BAPI-RECV-WINDOW': '5000', 'X-BAPI-SIGN': '***************************', 'Referer': 'CCXT', 'Accept-Encoding': 'gzip, deflate'} RequestBody: {"coin":"USDC","amount":"1.99","address":"0x4Ae*****************************D7E2","timestamp":1715092218643,"chain":"ARBITRUM ONE"}

**Comment by carlosmiei** [comment]
@gelono Thanks, actually the problem might be with the casing of the network, can you try to do

```Python
params = {
    "chain": "Arbitrum One",  # using the exchange-specific id here
}
withdraw_result = await all_ex["Bybit"].withdraw(
    code="USDC",
    amount=usdc_amount,
    address=config.get("account_address"),
    params=params
)
```

**Comment by gelono** [comment]
Where can I find the exchange-specific id?

**Comment by carlosmiei** [comment]
You can check the request field (`chain`) in the docs and the networks per currency inside the `currency` structure.

but you shouldn't need to worry about the exchange-specific id `chain`, `network` is the ccxt-unified one, but we have a small issue with the casing that will be fixed shortly

**Comment by gelono** [comment]
I was able to withdraw USDT on the BSC network. I think that in the case of the Arbitrum One network I am passing the network name incorrectly:
{'network': 'Arbitrum One'}
Or CCTX's uppercase processing makes the name incorrect.

**Comment by gelono** [comment]
I have resolved this issue. The correct name for Arbitrum One network is "ARBI".

**Comment by sc0Vu** [comment]
@gelono cool, actually ccxt had set networks in currency, you can find in `exchange.currency('USDT')`.

Let us know if you have other issue.

**Comment by wassim9944** [comment]
note sure who this helps but i will leave it here :
inoticed there was no withraw option for unifed account in the app , so i moved the crypto to founding and then my problems were fixed , you should also be aware the name of the chain in code is diffrint then the app , for example am using terra china in this code but the name the api given me is this 

python:
response = session.withdraw(
            coin="LUNA",
            chain="LUNANEW",  # Add the appropriate chain network for LUNA
            address=address,
            tag=memo if memo else "",  # Use an empty string if memo is not needed
            amount=str(amount),  # Ensure the amount is a string
            forceChain=1,  # Change to 0 for internal transfer if needed
            accountType="FUND",  # Ensure this matches the wallet type
            timestamp=timestamp,  # Add the current timestamp
            feeType=0,
        )

i recommend you ask chat gpt to write you a function to get the crypto info ,, you will find chain name right next to witherawle fees and minmum withraw info 
meybe its this session.get_coin_info() or this session.get_instruments_info(category="spot") or this session.get_tickers(category="spot")

one of them will give you every crypto and its chains , there you will find thos other names of the chains that you cant find in website or the app , and when you use that name in the order it gets sent
