### ISSUE TITLE
symbols of the exchange vary between Windows 7 and CentOS/Ubuntu

### ISSUE THREAD

**Issue by August-Ghost** [ccxt/ccxt#2243]
- OS: Windows 7 PS1, CentOS 7/Ubuntu
- Programming Language version: Python 3.6.4
- CCXT version: 1.11.84
- Exchange: Binance, Bitfinex. May be more
- Method: exchange.symbols

I am suffering from a strange behavior of ccxt: I get different tradepairs from the same exchange under Windows 7 and CentOS/Ubuntu. Some tradepairs only appear under Windows 7 and some only appear under CentOS 7/Ubuntu. What makes things worse is that some tradepairs have different names under different system. Here is the example, **the left side is Windows 7** and **the right side is CentOS 7/Ubuntu**:

## Binance:

![2](https://user-images.githubusercontent.com/15943189/37342083-81f72fb6-26fe-11e8-9cf0-467a252b95e5.PNG)

![3](https://user-images.githubusercontent.com/15943189/37342091-86373774-26fe-11e8-9e16-3d1a502182b7.PNG)

## Bitfinex:

![4](https://user-images.githubusercontent.com/15943189/37342166-b743b4dc-26fe-11e8-82dd-03e05f142457.PNG)

![5](https://user-images.githubusercontent.com/15943189/37342176-be167290-26fe-11e8-83b8-de75c621b8d6.PNG)

![6](https://user-images.githubusercontent.com/15943189/37342183-c14d1cf2-26fe-11e8-8cff-dc27f6f709e6.PNG)

**Comment by kroitor** [comment]
To me it's obvious that your windows version of ccxt is too old... Make sure you have the same version of ccxt on both systems.

These symbols... ↓

<img width="361" alt="screen shot 2018-03-14 at 01 35 42" src="https://user-images.githubusercontent.com/1294454/37373541-1372558c-2728-11e8-8a9f-6e9d0f8dc041.png">

↑ ... have been removed a few weeks ago, so, your windows version of ccxt is outdated.

Hope it helps. Let us know if it does not. Thx!

**Comment by August-Ghost** [comment]
@kroitor After upgrating ccxt to the latest version, the problem disappeared. I forgot ccxt is updated frequently. Thank you. Hive a nice day.
