### ISSUE TITLE
Phemex: fetchFundingHistory -> amount: null

### ISSUE THREAD

**Issue by egabosh** [ccxt/ccxt#22434]
### Operating System

Debian 12

### Programming Languages

Python

### CCXT Version

4.3.18

### Description

Moin,

Method fetchFundingHistory gives "amount: null" on Phemex.
Seems wrong for me.

### Code

```
print(exchange.fetchFundingHistory('BTC/USDT:USDT'))
```
Example Result:
```
    "info": {
      "symbol": "BTCUSDT",
      "currency": "USDT",
      "execQtyRq": "0.001",
      "side": "Buy",
      "execPriceRp": "64905.93672508",
      "execValueRv": "64.90593673",
      "fundingRateRr": "0.00003809",
      "feeRateRr": "0.00003809",
      "execFeeRv": "0.00247227",
      "createTime": "1713744000000"
    },
    "symbol": "BTCUSDT",
    "code": "USDT",
    "timestamp": 1713744000000,
    "datetime": "2024-04-22T00:00:00.000Z",
    "id": null,
    "amount": null
  }
```
Amount should not be null I think,

**Comment by egabosh** [comment]
I think amount should be value of "execFeeRv"

**Comment by sc0Vu** [comment]
@egabosh we've added in this commit https://github.com/ccxt/ccxt/commit/c47df4ffd86, could you upgrade and try again?

**Comment by egabosh** [comment]
@sc0Vu Didn't change. Amount is still null/None
did a fresh
git clone https://github.com/ccxt/ccxt.git --depth 1
Is this enough?

**Comment by egabosh** [comment]
Don't understand the code completely but maybe it is a typo execFeeEv should be execFeeRv? Or something changed on Phemex?

**Comment by carlosmiei** [comment]
@egabosh I think you're right, we have an issue there. Thanks for bringing our attention to this!

**Comment by egabosh** [comment]
Thanks a lot for your great and fast support!

**Comment by egabosh** [comment]
Works now. Thank you!

**Comment by carlosmiei** [comment]
@egabosh No problem, let us know if anything!
