### ISSUE TITLE
Cancelling orders does not work on OKX

### ISSUE THREAD

**Issue by MrMechanical** [ccxt/ccxt#22447]
### Operating System

Mac OS Sonoma 14.1.1

### Programming Languages

Python

### CCXT Version

4.3.18

### Description

Using the test code to open and cancel an order, it leaves an order uncancelled. Thank you for your help ahead of time.

### Code

```
  
def close_positions():
    # Fetch open orders
    open_orders = exchange.fetch_open_orders()

    # Cancel all open orders
    for order in open_orders:
        exchange.cancel_order(order['id'], order['symbol'])


def test_orders():
    order = exchange.create_order(symbol= symbol, type = "market", side = "buy", amount=10.0)
    time.sleep(10)
    #exchange.cancel_order(order['id'], symbol)
    close_positions()
    print("test complete")

test_orders()
```

**Comment by MrMechanical** [comment]
after debugging I believe the issue is with fetch_open_orders as open_orders is empty during testing
open_orders
[]

**Comment by sc0Vu** [comment]
@MrMechanical because the order type is market, and it would be matched when you create. You can use `fetchClosedOrders` instead.

**Comment by MrMechanical** [comment]
Thanks for the help. My bad for the misunderstanding.
