### ISSUE TITLE
Bitget missing bot-account/ funding-account endpoints

### ISSUE THREAD

**Issue by edwardchenchen** [ccxt/ccxt#22464]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

https://www.bitget.com/api-doc/common/account/Funding-Assets
https://www.bitget.com/api-doc/common/account/Bot-Assets

above two endpoints are not supported currently

### Describe the solution you'd like

1. add support for these two
2. or is there a way you can show me how to use ccxt to sign the request without going through all the steps build signature

**Comment by samgermain** [comment]
These endpoints will be added once https://github.com/ccxt/ccxt/pull/22468 is merged
