### ISSUE TITLE
ccex missing markets/pairs

### ISSUE THREAD

**Issue by Esc4pism** [ccxt/ccxt#2246]
loadMarkets in ccex uses this call: https://c-cex.com/t/api_pub.html?a=getmarkets, but this doesnt return all trading pairs supported by ccex. I looked around and found https://c-cex.com/t/prices.json (which also doesnt return all pairs, even though the documentation says so for both of those calls), but instead https://c-cex.com/t/pairs.json seems to return a plain array with all supported pairs.

Could this call be used additionally for loadMarkets in ccex? Because fetchTickers() also returns data for those otherwise "missing" pairs.

**Comment by kroitor** [comment]
Switched to `pairs.json` in 1.11.88 for c-cex. Thx for reporting!
