### ISSUE TITLE
Bitfinex fetchTickers failed to recognize NECUSD

### ISSUE THREAD

**Issue by lucasgadams** [ccxt/ccxt#2250]
- OS: Ubuntu 16.04
- Programming Language version: python 3.5.2
- CCXT version:  ccxt==1.10.1242
- Exchange: bitfinex
- Method: fetchTickers

Every once in a while I receive the following error using bitfinex fetchTickers : 
  File "/home/ubuntu/env/lib/python3.5/site-packages/ccxt/bitfinex.py", line 387, in fetch_tickers
    raise ExchangeError(self.id + ' fetchTickers() failed to recognize symbol ' + id + ' ' + self.json(ticker))
ccxt.base.errors.ExchangeError: bitfinex fetchTickers() failed to recognize symbol NECUSD {"volume":"2438.6685917","low":"0.86","high":"1.09","ask":"1.0","bid":"0.8523","mid":"0.92615","last_price":"0.86","pair":"NECUSD","timestamp":"1520953076.949080844"}

**Comment by kroitor** [comment]
Duplicate: #2180
