### ISSUE TITLE
Kraken: Support for createMarketOrderWithCost using "viqc" flag

### ISSUE THREAD

**Issue by mjwvb** [ccxt/ccxt#22521]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

In CCXT there's currently no support for createMarketOrderWithCost for Kraken, although there's support for it in the Kraken API.

### Describe the solution you'd like

According to the API docs there seems to be support for a "olflag"  named "viqc": _"order volume expressed in quote currency. This is supported only for market orders."_

See the api docs for addOrder: https://docs.kraken.com/rest/#tag/Spot-Trading/operation/addOrder

I could be wrong, but it sounds like that's what we need to implement market orders with cost / quote size, so we could implement the following functions:

createMarketOrderWithCost() / createMarketBuyOrderWithCost / createMarketSellOrderWithCost

**Comment by carlosmiei** [comment]
@mjwvb Actually I'm testing it and this is only supported for market-buy orders

```
} 
RequestBody:
 nonce=1715879486467&pair=LTCUSDT&type=sell&ordertype=market&volume=10&oflags=viqc 

handleRestResponse:
 kraken POST https://api.kraken.com/0/private/AddOrder 200 OK 
ResponseHeaders:

ResponseBody:
 {"error":["EGeneral:Invalid arguments:viqc"]} 
```
with market sell, throws this error

**Comment by carlosmiei** [comment]
Interesting with`market buy` throws an insufficient funds error when I have enough money to buy it

```
RequestBody:
 nonce=1715879624533&pair=LTCUSDT&type=buy&ordertype=market&volume=5 

handleRestResponse:
 kraken POST https://api.kraken.com/0/private/AddOrder 200 OK 
ResponseHeaders:
} 
ResponseBody:
 {"error":["EOrder:Insufficient funds"]} 

```
I might be missing something

**Comment by carlosmiei** [comment]
hum, market buy also throws an error 🤔 

```
RequestBody:
 nonce=1715880275284&pair=LTCUSDT&type=buy&ordertype=market&volume=5&oflags=viqc 

handleRestResponse:
 kraken POST https://api.kraken.com/0/private/AddOrder 200 OK 

ResponseBody:
 {"error":["EGeneral:Invalid arguments:volume"]} 
```

**Comment by carlosmiei** [comment]
@mjwvb apparently only works with `USD` markets and not `USDT` 🤔 

```
RequestBody:
 nonce=1715880738343&pair=XLTCZUSD&type=buy&ordertype=market&volume=5&oflags=viqc 

handleRestResponse:
 kraken POST https://api.kraken.com/0/private/AddOrder 200 OK 
ResponseHeaders:

ResponseBody:
 {"error":[],"result":{"txid":["OCSKHT-X2QO7-T4WV3L"],"descr":{"order":"buy 5.00000000 LTCUSD @ market"}}} 
```

**Comment by mjwvb** [comment]
@carlosmiei That's very unfortunate. Apparently there's also another version of the docs which says:
viqc: order volume expressed in quote currency. This option is supported only for buy market orders. Also not available on margin orders. See: 
https://docs.kraken.com/api/docs/rest-api/add-order

Interesting how there's two types of api docs?
https://docs.kraken.com/rest/#tag/Spot-Trading/operation/addOrder

It seems that /api/ is officially linked, and that /rest/ can only be found on google. Oh well...

Still weird how it not works for the USDT pair though... Anyway thanks for checking and putting in all the effort! I should have checked the API a bit more, but was a little bit on a rush. So sorry for that :)

**Comment by carlosmiei** [comment]
@mjwvb Yeah the docs and the API are very confusing in this regard. Nonetheless, we will implement the `createMarketBuyOrderWithCost` for the USD market pairs (also very strange not supporting USDT markets)

**Comment by mjwvb** [comment]
@carlosmiei Alright! According to the docs you should also exclude margin orders, but cannot confirm right now.

Also now that you're into the oflags, I saw in the code that when using postOnly on limit orders, the oflags params is always forced set to "post" instead of appending any existing oflags. It means you cannot provide your own oflags in combination with the native postOnly. See:
https://github.com/ccxt/ccxt/blob/9ab59963f780c4ded7cd76ffa9e58b7f3fdd6e79/ts/src/kraken.ts#L1789

**Comment by carlosmiei** [comment]
@mjwvb Yes you're right, I will update it to take that into consideration.

**Comment by mjwvb** [comment]
Thanks! I'll be testing it out in the near future.

By the way, I think USDT markets actually are supported but the minimum order size of LTC/USDT is 10 USDT, and you provided 5 USDT. At least that's what the kraken UI is telling me: "Cannot be smaller than 10 USDT"

**Comment by carlosmiei** [comment]
@mjwvb omg you're right 😅, that was the problem, thanks once again! will be updated shortly

```
 nonce=1715951571837&pair=LTCUSDT&type=buy&ordertype=market&volume=10&oflags=viqc 

handleRestResponse:
 kraken POST https://api.kraken.com/0/private/AddOrder 200 OK 

ResponseBody:
 {"error":[],"result":{"txid":["OVKIAP-DEGPW-MMZK4F"],"descr":{"order":"buy 10.00000000 LTCUSDT @ market"}}} 

```

**Comment by mjwvb** [comment]
@carlosmiei haha, Kraken has ridiculous minimum sizes though...

**Comment by carlosmiei** [comment]
@mjwvb we just released a new version with the fixes, can you please update your ccxt version and try again?

**Comment by carlosmiei** [comment]
@mjwvb turns out we have a small issue with the pipeline so we didn't release yet

**Comment by mjwvb** [comment]
Am I right the release is still pending? Npm can't find 4.3.26

**Comment by carlosmiei** [comment]
@mjwvb Yes the pipeline is not stable yet, unfortunately, but we're trying to fix it right now

**Comment by carlosmiei** [comment]
@mjwvb We just released a nee version, 4.3.27, please let us know if anything

**Comment by mjwvb** [comment]
@carlosmiei using 4.3.27 now and it seems to be working perfectly. Thanks for the effort once again!

**Comment by carlosmiei** [comment]
@mjwvb No problem!
Will close this issue, let us know if anything
