### ISSUE TITLE
Send spot limit order to ByBit, price and amount rounding

### ISSUE THREAD

**Issue by Elferboy** [ccxt/ccxt#22520]
### Operating System

Windows 10

### Programming Languages

PHP

### CCXT Version

4.3.24

### Description

Hi, there. I'm trying to open a spot SELL limit order on ByBit and I'm encountering that CCXT rounds up the variables before sending them to open the limit order. And when I look at markets for this crypto pair, it says that:
```
[precision][amount] => 0.01
[precision][price] => 0.0001
```

The changes happen in `$orderRequest = \ccxt\bybit->create_order_request()` of the method `\ccxt\bybit->create_order()`. Here `$orderRequest` already contains such an array:
```
$orderRequest: Array
(
    [symbol] => RUNEUSDT
    [side] => Sell
    [orderType] => Limit
    [price] => 10.309
    [category] => spot
    [qty] => 5
)
```
which is then sent via API to ByBit. I.e. price from 10.3089 became 10.309, and qty from 5.04 became 5. And on the page https://www.bybit.com/ru-RU/trade/spot/RUNE/USDT itself the price 10.3089 is set and the qty 5.04 is also set.

### Code

```
$account = Account::getOneAsArrayById(2);

$exchange = new \ccxt\bybit([
	'apiKey'          => $account['api_key'],
	'secret'          => $account['api_secret'],
	'password'        => $account['api_password'],
	'enableRateLimit' => true,
]);

$exchange->load_time_difference();

$symbol = 'RUNEUSDT';
$amount = 5.04;
$price  = 10.3089;
$params = [
	'category' => 'spot',
];

$result = $exchange->create_limit_sell_order($symbol, $amount, $price, $params);
```

**Comment by ttodua** [comment]
thanks for the report! i've reproduced this. seems the issue is specific to PHP part, not in other langs.
I'll push a fix soon and let you know

**Comment by ttodua** [comment]
seems i was in wrong direction. the problem is because of symbol id's clash. 
Please try to use unified symbols format: `RUNE/USDT` (the slash between) for spot symbols, and `RUNE/USDT:USDT` format for USDT swap symbols.
```
$symbol = 'RUNE/USDT';
$amount = 5.04;
$price  = 10.3089;
$result = $exchange->create_order($symbol, 'limit', 'sell', $amount, $price);
```
it would work correctly. let us know if you'd face any further issues
