### ISSUE TITLE
Bitget missing GET /api/v2/earn/account/assets

### ISSUE THREAD

**Issue by edwardchenchen** [ccxt/ccxt#22543]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

https://www.bitget.com/api-doc/earn/account/Earn-Assets

to make the whole bitget account structure complete

related
https://github.com/ccxt/ccxt/issues/22464

### Describe the solution you'd like

add support

**Comment by carlosmiei** [comment]
Hello @edwardchenchen, thanks for reporting it, will be added shortly.

**Comment by c0dehunter** [comment]
Hey @carlosmiei, isn't there some missing code in fetch_balance() for "earn"?

https://github.com/ccxt/ccxt/blob/master/php/bitget.php#L3636

        if (($marketType === 'swap') || ($marketType === 'future')) {
            $productType = null;
            list($productType, $params) = $this->handle_product_type_and_params(null, $params);
            $request['productType'] = $productType;
            $response = $this->privateMixGetV2MixAccountAccounts ($this->extend($request, $params));
        } elseif ($marginMode === 'isolated') {
            $response = $this->privateMarginGetMarginV1IsolatedAccountAssets ($this->extend($request, $params));
        } elseif ($marginMode === 'cross') {
            $response = $this->privateMarginGetMarginV1CrossAccountAssets ($this->extend($request, $params));
        } elseif ($marketType === 'spot') {
            $response = $this->privateSpotGetV2SpotAccountAssets ($this->extend($request, $params));
        }

        // ˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇˇ this seems to be missing, no?

        } elseif ($marketType === 'earn') {
            $response = $this->privateEarnGetV2EarnAccountAssets ($this->extend($request, $params));
        } 

        // ^^^^^^^^^^^^^^^

        else {
            throw new NotSupported($this->id . ' fetchBalance() does not support ' . $marketType . ' accounts');
        }
