### ISSUE TITLE
Okex connect timeout 

### ISSUE THREAD

**Issue by gavin369** [ccxt/ccxt#2255]
I have access to the okex feedback error. Please help me to see what the problem is.

```
var ccxt = require ('ccxt');
var async = require('async');
var start = async function () {
    let okex  = new ccxt.okex ({
        apiKey: '',
        secret: '',
        verbose : true
    })
    ticker = await okex.fetchTicker('LTC/BTC');
    console.log (ticker)
};
start();
```

fetch:
 okex GET https://www.okex.com/v2/markets/products.do 
Request:
 {} 
 undefined 

(node:12192) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: okex GET https://www.okex.com/v2/markets/products.do system request to https://www.okex.com/v2/markets/products.do failed, reason: connect ETIMEDOUT 74.86.151.167:443
(node:12192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kroitor** [comment]
Can you open this url in your browser: https://www.okex.com/v2/markets/products.do ?

**Comment by gavin369** [comment]
I can

**Comment by kroitor** [comment]
@gavin369 I mean, from the same system that you're trying that code snippet.

**Comment by kroitor** [comment]
Also, no need for this line: `var async = require('async');`

**Comment by gavin369** [comment]
I've tried 4 exchanges now, huobipro and bittrex have no problem, okex and binance show request timed out (10000 MS)

**Comment by kroitor** [comment]
@gavin369 what's your version of ccxt and your version of node ? Also, have your tried going through the troubleshooting section from the Manual?

**Comment by gavin369** [comment]
But I can open https://www.okex.com/v2/markets/products.do with a browser?

**Comment by kroitor** [comment]
```
var ccxt = require ('ccxt');
var start = async function () {
    let okex  = new ccxt.okex ({
        verbose : true
        proxy: 'https://cors-anywhere.herokuapp.com/', // add this line
    })
    ticker = await okex.fetchTicker('LTC/BTC');
    console.log (ticker)
};
start();
```

Does it work this way?

**Comment by gavin369** [comment]
ccxt@1.11.90
node v8.4.0

```
var ccxt = require ('ccxt');
var start = async function () {
    let okex  = new ccxt.okex ({
        apiKey: '',
        secret: '',
        verbose : true
        proxy: 'https://cors-anywhere.herokuapp.com/',
    })
    ticker = await okex.fetchTicker('LTC/BTC');
    console.log (ticker)
};
start();
```


 proxy: 'https://cors-anywhere.herokuapp.com/',
        ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

**Comment by kroitor** [comment]
There was a missing comma on the previous line:

```
verbose : true,
```

Updated the code above...

**Comment by gavin369** [comment]
Ok，I can see ticker，Thanks！But what is the role of proxy?

**Comment by gavin369** [comment]
Why I don't need to add Huobi and bittrex

**Comment by kroitor** [comment]
@gavin369 it is described here:

- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/Install#proxy
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#ddos-protection-by-cloudflare--incapsula

It means OKEX is blocking your location for some reason, therefore the proxy is used to send the traffic through it. The reason of blocking isn't exactly known to me, but this is most likely a cloudflare protection issue, if that is the case, use the couldscraper to bypass it:

- https://github.com/ccxt/ccxt/blob/master/examples/js/bypass-cloudflare.js (having read the Manual, search for *"cloudflare"* and *"cloudscrape"* in the issues)

Hope it helps.

**Comment by jjxtra** [comment]
That url does not work in the browser anymore, from United States

**Comment by kroitor** [comment]
@jjxtra yep, they changed it as described here: https://github.com/ccxt/ccxt/issues/2972

**Comment by gavin369** [comment]
Recently the proxy is bad, showing ：
```
okex = new ccxt.okex({
                                apiKey: data[i].Access_Key,
                                secret: data[i].Secret_Key,
                                proxy: 'https://cors-anywhere.herokuapp.com/',
                                //proxy: 'https://crossorigin.me/',
                            });
```

` Error: okex GET https://cors-anywhere.herokuapp.com/https://www.okex.com/v2/markets/products.do 429  not accessible from this location at the moment`

**Comment by gavin369** [comment]
If you use crossorigin.me, it will show：
`(node:6832) UnhandledPromiseRejectionWarning: Error: okex GET https://crossorigin.me/https://www.okex.com/v2/markets/products.do request timed out (10000 ms)`

**Comment by kroitor** [comment]
@gavin369 update ccxt version: https://github.com/ccxt/ccxt/search?q=okex+timeout&type=Issues
