### ISSUE TITLE
fetchTrades "since" doesn't work for okx, and bybit

### ISSUE THREAD

**Issue by x1i4b1x2** [ccxt/ccxt#22552]
### CCXT Version

last

### Description

The "since" in fetchTrades only works on Binance.

### Code

```
  

```

**Comment by pcriadoperez** [comment]
Hi @x1i4b1x2,
I tested on both okx and bybit using ts, python and php and worked for me in all cases.
Are you able to provide a snippet of code that reproduces the error?
Thanks!

**Comment by x1i4b1x2** [comment]
Yes with older timestamps it doesn't work, but it might be the exchange that doesn't return older data. For example, it seems that okx returns only the most recent 500 trades, what do you think?

**Comment by carlosmiei** [comment]
Hello @x1i4b1x2, yes that's a limitation on the exchange-side, none of those accept a `since` parameter upon fetching public trades

- OKX: https://www.okx.com/docs-v5/en/#rest-api-market-data-get-trades 
- bybit: https://bybit-exchange.github.io/docs/v5/market/recent-trade
