### ISSUE TITLE
Whitebit: Support for createMarketBuyOrderWithCost

### ISSUE THREAD

**Issue by mjwvb** [ccxt/ccxt#22570]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

In the whitebit implementation of CCXT there is no support for placing a market buy order using its quote currency. However the API does provide an endpoint to place a market buy order with cost:

https://docs.whitebit.com/private/http-trade-v4/#create-market-order

### Describe the solution you'd like

Would be nice to have a whitebit implementation of createMarketBuyOrderWithCost().

**Comment by carlosmiei** [comment]
@mjwvb Thanks for your suggestion, we will try to add it shortly.
