### ISSUE TITLE
Coinbase - provide an option to use the private methods instead of public methods to reduce rate limit errors

### ISSUE THREAD

**Issue by jtashiro** [ccxt/ccxt#22571]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

Using the public methods have a lower rate limit and result in Too Many Request errors from coinbase.

### Describe the solution you'd like

I've replaced all calls to PublicGetBrokerageMarketProducts with PrivateGetBrokerageProducts as a patch,  but it's not a great solution for all users.  Better if this was controlled via an Option in the exchange class.

sed -i "s/v3PublicGetBrokerageMarketProducts/v3PrivateGetBrokerageProducts/g" ~/.local/lib/python3.8/site-packages/ccxt/coinbase.py

**Comment by carlosmiei** [comment]
Hello @jtashiro, we will take that into consideration but those endpoints are only called  "once per instance", to cache and load the markets so it shouldn't have that much impact.

**Comment by jtashiro** [comment]
> Hello @jtashiro, we will take that into consideration but those endpoints are only called "once per instance", to cache and load the markets so it shouldn't have that much impact.

I'm comparing 4.2.51 to 4.3.28 to identify the change that is causing me to encounter 429 Too Many Requests, when running the same python scripts.  4.2.51 works fine, no issue with 429, but 4.3.28 fails in the same spot each time.

**Comment by carlosmiei** [comment]
@jtashiro 

> Question is why was this changed to the public methods in 4.3?

We did this because for accessing public data like markets/candles/tickers/trades it should not be needed to have an account with the exchange, most exchanges provide this information publicly and we wanted to keep the same approach here.

**Comment by jtashiro** [comment]
Given the lower rate limit that is enforced on public apis,  can these wrapper methods use the private methods when apiKeys present?   That would make it transparent and not require an optional setting.

**Comment by carlosmiei** [comment]
@jtashiro I think it would be more "transparent" using the option. Which unified methods do you intend to use the private endpoints? `fetchTicker/OHLCV/Trades` ?

**Comment by ttodua** [comment]
I've linked PR. after it's merged and new package published, you can use `ex.options['usePrivateEndpointsIfApikeysPresent'] = true`, so thereafter all requests will use private endpoints (if api keys are present)

**Comment by carlosmiei** [comment]
@jtashiro Ok we just released a new version (4.3.32) with the changes, you can set `exchange.options['usePrivate'] = True` or provide `usePrivate: True` in `params` upon calling fetchTrades/OHLCV/ticker/Orderbook. 

Let us know if anything!

**Comment by jtashiro** [comment]
This looks good.  

I’ll open a new ticket regarding the exchange name you’ve added for Coinbase Advanced.  Is it possible to revert and preserve the name ‘Coinbase’ and add a new property describing the API or some other technique { API: 'Coinbase Advanced’, API_KEY: “CDP” }.  The rationale here is that the exchange is still ‘Coinbase’ and the method for accessing the exchange is “Coinbase Advanced”.
