### ISSUE TITLE
Biance watch_ticker response value is None

### ISSUE THREAD

**Issue by yyqiekenao** [ccxt/ccxt#22582]
### Programming Languages

Python

### Description

parse_ws_ticker message is None , response 

```python
{"symbol": null, "timestamp": 1716431646502, "datetime": "2024-05-23T02:34:06.502Z", "high": null, "low": null, "bid": null, "bidVolume": null, "ask": null, "askVolume": null, "vwap": null, "open": null, "close": null, "last": null, "previousClose": null, "change": null, "percentage": null, "average": null, "baseVolume": null, "quoteVolume": null, "info": {"result": null, "id": 1}}
```

### Code

```python
   def parse_ws_ticker(self, message, marketType):
        #
        # ticker
        #     {
        #         e: '24hrTicker',      # event type
        #         E: 1579485598569,     # event time
        #         s: 'ETHBTC',          # symbol
        #         p: '-0.00004000',     # price change
        #         P: '-0.209',          # price change percent
        #         w: '0.01920495',      # weighted average price
        #         x: '0.01916500',      # the price of the first trade before the 24hr rolling window
        #         c: '0.01912500',      # last(closing) price
        #         Q: '0.10400000',      # last quantity
        #         b: '0.01912200',      # best bid
        #         B: '4.10400000',      # best bid quantity
        #         a: '0.01912500',      # best ask
        #         A: '0.00100000',      # best ask quantity
        #         o: '0.01916500',      # open price
        #         h: '0.01956500',      # high price
        #         l: '0.01887700',      # low price
        #         v: '173518.11900000',  # base volume
        #         q: '3332.40703994',   # quote volume
        #         O: 1579399197842,     # open time
        #         C: 1579485597842,     # close time
        #         F: 158251292,         # first trade id
        #         L: 158414513,         # last trade id
        #         n: 163222,            # total number of trades
        #     }
        #
        # miniTicker
        #     {
        #         e: '24hrMiniTicker',
        #         E: 1671617114585,
        #         s: 'MOBBUSD',
        #         c: '0.95900000',
        #         o: '0.91200000',
        #         h: '1.04000000',
        #         l: '0.89400000',
        #         v: '2109995.32000000',
        #         q: '2019254.05788000'
        #     }
        #
        event = self.exchange.safe_string(message, 'e', 'bookTicker')
        if event == '24hrTicker':
            event = 'ticker'
        timestamp = None
        now = self.exchange.milliseconds()
        if event == 'bookTicker':
            # take the event timestamp, if available, for spot tickers it is not
            timestamp = self.exchange.safe_integer(message, 'E', now)
        else:
            # take the timestamp of the closing price for candlestick streams
            timestamp = self.exchange.safe_integer(message, 'C', now)
        marketId = self.exchange.safe_string(message, 's')
        symbol = self.exchange.safe_symbol(marketId, None, None, marketType)
        last = self.exchange.safe_float(message, 'c')
        ticker = {
            'symbol': symbol,
            'timestamp': timestamp,
            'datetime': self.exchange.iso8601(timestamp),
            'high': self.exchange.safe_float(message, 'h'),
            'low': self.exchange.safe_float(message, 'l'),
            'bid': self.exchange.safe_float(message, 'b'),
            'bidVolume': self.exchange.safe_float(message, 'B'),
            'ask': self.exchange.safe_float(message, 'a'),
            'askVolume': self.exchange.safe_float(message, 'A'),
            'vwap': self.exchange.safe_float(message, 'w'),
            'open': self.exchange.safe_float(message, 'o'),
            'close': last,
            'last': last,
            'previousClose': self.exchange.safe_float(message, 'x'),  # previous day close
            'change': self.exchange.safe_float(message, 'p'),
            'percentage': self.exchange.safe_float(message, 'P'),
            'average': None,
            'baseVolume': self.exchange.safe_float(message, 'v'),
            'quoteVolume': self.exchange.safe_float(message, 'q'),
            'info': message,
        }
        return ticker

```

**Comment by samgermain** [comment]
What are you asking? The method works fine for me

Python v3.9.6
CCXT v4.3.29

```
binance.watchTicker(BTC/USDT)
```
```
{'ask': 69522.55,
 'askVolume': 0.00583,
 'average': 69501.945,
 'baseVolume': 273.02608,
 'bid': 69522.49,
 'bidVolume': 0.00403,
 'change': 45.67,
 'close': 69524.78,
 'datetime': '2024-05-23T04:58:03.552Z',
 'high': 74739.0,
 'info': {'A': '0.00583000',
          'B': '0.00403000',
          'C': 1716440283552,
          'E': 1716440283553,
          'F': 1461264,
          'L': 1547582,
          'O': 1716353883552,
          'P': '0.066',
          'Q': '0.00014000',
          'a': '69522.55000000',
          'b': '69522.49000000',
          'c': '69524.78000000',
          'e': '24hrTicker',
          'h': '74739.00000000',
          'l': '62098.00000000',
          'n': 86319,
          'o': '69479.11000000',
          'p': '45.67000000',
          'q': '18992345.03476140',
          's': 'BTCUSDT',
          'v': '273.02608000',
          'w': '69562.38405782',
          'x': '69479.11000000'},
 'last': 69524.78,
 'low': 62098.0,
 'open': 69479.11,
 'percentage': 0.066,
 'previousClose': 69479.11,
 'quoteVolume': 18992345.0347614,
 'symbol': 'BTC/USDT',
 'timestamp': 1716440283552,
 'vwap': 69562.38405782}
 ```

**Comment by yyqiekenao** [comment]
> 你问的是什么？这个方法对我来说很有效。
> 
> Python v3.9.6 CCXT v4.3.29
> 
> ```
> binance.watchTicker(BTC/USDT)
> ```
> 
> ```
> {'ask': 69522.55,
>  'askVolume': 0.00583,
>  'average': 69501.945,
>  'baseVolume': 273.02608,
>  'bid': 69522.49,
>  'bidVolume': 0.00403,
>  'change': 45.67,
>  'close': 69524.78,
>  'datetime': '2024-05-23T04:58:03.552Z',
>  'high': 74739.0,
>  'info': {'A': '0.00583000',
>           'B': '0.00403000',
>           'C': 1716440283552,
>           'E': 1716440283553,
>           'F': 1461264,
>           'L': 1547582,
>           'O': 1716353883552,
>           'P': '0.066',
>           'Q': '0.00014000',
>           'a': '69522.55000000',
>           'b': '69522.49000000',
>           'c': '69524.78000000',
>           'e': '24hrTicker',
>           'h': '74739.00000000',
>           'l': '62098.00000000',
>           'n': 86319,
>           'o': '69479.11000000',
>           'p': '45.67000000',
>           'q': '18992345.03476140',
>           's': 'BTCUSDT',
>           'v': '273.02608000',
>           'w': '69562.38405782',
>           'x': '69479.11000000'},
>  'last': 69524.78,
>  'low': 62098.0,
>  'open': 69479.11,
>  'percentage': 0.066,
>  'previousClose': 69479.11,
>  'quoteVolume': 18992345.0347614,
>  'symbol': 'BTC/USDT',
>  'timestamp': 1716440283552,
>  'vwap': 69562.38405782}
> ```
The response sometimes has an None value
{"symbol": null, "timestamp": 1716431646502, "datetime": "2024-05-23T02:34:06.502Z", "high": null, "low": null, "bid": null, "bidVolume": null, "ask": null, "askVolume": null, "vwap": null, "open": null, "close": null, "last": null, "previousClose": null, "change": null, "percentage": null, "average": null, "baseVolume": null, "quoteVolume": null, "info": {"result": null, "id": 1}}

**Comment by samgermain** [comment]
> The response sometimes has an None value

Can you explain how to reproduce this error? I'm not receiving it

**Comment by yyqiekenao** [comment]
> > 响应有时具有 None 值
> 
> 你能解释一下如何重现这个错误吗？我没有收到它

This problem will occur if you subscribe for a long time

**Comment by samgermain** [comment]
> This problem will occur if you subscribe for a long time

can you please set `verbose` to `true` for your exchange object and share the output of that

**Comment by ttodua** [comment]
@yyqiekenao as commented by @samgermain it would be ideal if you try to enable verbose mode and provise us what raw-data is coming in which causes those nulled valued.

**Comment by yyqiekenao** [comment]
> @yyqiekenao as commented by @samgermain it would be ideal if you try to enable verbose mode and provide us what raw-data is coming in which causes those nulled valued.

It's difficult to reproduce, but the log output does contain None.

**Comment by yyqiekenao** [comment]
> > This problem will occur if you subscribe for a long time
> 
> can you please set `verbose` to `true` for your exchange object and share the output of that

2024-05-27T07:06:35.437Z connecting to wss://stream.binance.com:9443/ws/0 with timeout 10000 ms
2024-05-27T07:06:36.062Z connected
2024-05-27T07:06:36.062Z ping loop
2024-05-27T07:06:36.063Z sending {'method': 'SUBSCRIBE', 'params': ['ldousdt@ticker'], 'id': 1}
2024-05-27T07:06:36.303Z pong WSMessage(type=<WSMsgType.PONG: 10>, data=bytearray(b''), extra='')
2024-05-27T07:06:36.303Z message {"result":null,"id":1}

**Comment by carlosmiei** [comment]
@yyqiekenao This message is expected and is received every time, so I don't think it's causing the crash

> 2024-05-27T08:13:08.302Z onMessage { result: null, id: 1 }

**Comment by yyqiekenao** [comment]
> @yyqiekenao此消息是预期的，并且每次都会收到，因此我认为它不是导致崩溃的原因
> 
> > 2024-05-27T08：13：08.302Z onMessage {结果：null，id：1}

tks

**Comment by ttodua** [comment]
@yyqiekenao it would be good if you somehow log the incoming raw data, and whenever that error happens, paste here the related last part of log, it would help us to undersatnd and fix it.
