### ISSUE TITLE
Binance Portfolio Margin `timeInForce` option `PO` results in no TIF parameter in new order (UM) request

### ISSUE THREAD

**Issue by WillPCowan** [ccxt/ccxt#22590]
### Operating System

MacOS

### Programming Languages

Python

### CCXT Version

4.2.99

### Description

When sending create order requests using `ccxt.pro.Binance` and using the portfolio margin account option (`exchange["portfolioMargin"] = True`, placing a create order request with the post only parameter for time in force results in no time in force parameter in the HTTP request. E.g.
```
res = await binance.create_order(
   ...
   params={'timeInForce': 'PO'},
)
```

would result in the request
```
fetch Request: binance POST https://papi.binance.com/papi/v1/um/order RequestHeaders: {'X-MBX-APIKEY': 'abc', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate'} RequestBody: timestamp=1716460685155&symbol=ETHUSDT&side=BUY&newClientOrderId=1&newOrderRespType=RESULT&type=LIMIT&quantity=0.001&price=2274.73&selfTradePreventionMode=EXPIRE_MAKER&recvWindow=10000&signature=abc
```

which yields the response
```
fetch Response: binance POST https://papi.binance.com/papi/v1/um/order 400 ResponseHeaders: {'Date': 'Thu, 23 May 2024 10:38:05 GMT', 'Content-Type': 'application/json', 'Content-Length': '100', 'Connection': 'keep-alive', 'Server': 'Tengine', 'X-MBX-USED-WEIGHT-1M': '50', 'X-MBX-ORDER-COUNT-1M': '1', 'x-response-time': '1ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS'} ResponseBody: {"code":-1102,"msg":"Mandatory parameter 'timeInForce' was not sent, was empty/null, or malformed."}
```

Manually putting the correct timeInForce parameter 'GTX' instead of 'PO' resolves this however, I assume the unified 'PO' parameter should do put this in the request automatically?

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @WillPCowan, can you please provide `postOnly: True` in `params` instead? That's the unified way of setting a postOnly order in the ccxt terminology.

**Comment by carlosmiei** [comment]
@WillPCowan Actually I found a small issue in there, will be fixed shortly. Thanks for bringing our attention to this.

**Comment by WillPCowan** [comment]
Thanks @carlosmiei -- should still use `postOnly: True` instead of `timeInForce: 'PO'`?

**Comment by carlosmiei** [comment]
@WillPCowan that's the unified way yes, but right now will not work for PortfolioMargin orders but I'm working on a fix. Rule of thumb, yes `postOnly` should be the unified way regardless of the exchange.

**Comment by WillPCowan** [comment]
Awesome, will update my code to use that instead. The documentation notes that `timeInForce` is unified with PO though, fyi: https://github.com/ccxt/ccxt/wiki/Manual#timeinforce

**Comment by carlosmiei** [comment]
> Awesome, will update my code to use that instead. The documentation notes that `timeInForce` is unified with PO though, fyi: https://github.com/ccxt/ccxt/wiki/Manual#timeinforce

@WillPCowan We will update the docs as well, this statement is outdated.

**Comment by carlosmiei** [comment]
@WillPCowan If you update your ccxt version it should be working now!
