### ISSUE TITLE
Bitget order subscription duplication. C#

### ISSUE THREAD

**Issue by skuvv** [ccxt/ccxt#22599]
### Operating System

Windows 10

### CCXT Version

4.3.22

### Description

I make several subscriptions for orders. 
Next, when I receive new order status, it pushed for all subscriptions instead of specific one.

**Comment by skuvv** [comment]
Here is the demo solution.
[DemoForDebug.zip](https://github.com/ccxt/ccxt/files/15421022/DemoForDebug.zip)

The counter should always be 1, but it is incremented in other subscriptions.

**Comment by carlosmiei** [comment]
Hello @skuvv, thanks again for reporting it, we will take a look

**Comment by skuvv** [comment]
More info, 
```
        public void resolve(object content, object messageHash2)
        {
            if (this.verbose && (messageHash2 == null))
            {
                Console.WriteLine("resolve received undefined messageHash");
            }
            var messageHash = messageHash2.ToString();
            if ((this.futures as ConcurrentDictionary<string, Future>).TryRemove(messageHash, out Future future))
            {
                future.resolve(content);
            }
        }
```
This method uses messageHash for pushing incoming messages for subscriptions but messageHash is not unique in this case and all subscriptions has the same key = "order"

**Comment by carlosmiei** [comment]
@skuvv Yes we need to change the `messageHash` depending on the market type when the symbol is not provided.

**Comment by skuvv** [comment]
Tested on CCXT Version:4.3.35
fixed now, thanks!
