### ISSUE TITLE
Bitget error OHLCV for delivery futures

### ISSUE THREAD

**Issue by x1i4b1x2** [ccxt/ccxt#22609]
### Description

await bitget.fetchOHLCV('ETH/USD:ETH-240927', '1h')

Fetching coin settled futures with expiration returns this:

ExchangeError: bitget {"code":"40034","msg":"Parameter ETHUSD_D1 does not exist","requestTime":1716560446870,"data":null}

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @x1i4b1x2, thanks for reporting it, we will take a look

**Comment by carlosmiei** [comment]
@x1i4b1x2 It was an issue on the exchange side but I believe it's working now, can you please try again?

**Comment by carlosmiei** [comment]
DEMO

```

2024-05-24T15:41:45.072Z
Node.js: v22.2.0
CCXT v4.3.30
bitget.fetchOHLCV (ETH/USD:ETH-240927, 1h, , 5)
2024-05-24T15:41:49.205Z iteration 0 passed in 2492 ms

1716548400000 | 3881.42 | 3900.29 | 3876.39 |  3895.9 | 10.35
1716552000000 |  3895.9 | 3908.03 |  3880.3 | 3896.37 |  7.18
1716555600000 | 3896.37 | 3908.16 | 3860.29 |  3864.6 | 12.84
1716559200000 |  3864.6 | 3915.23 | 3853.62 | 3890.23 |  7.41
1716562800000 | 3890.23 | 3916.28 | 3888.93 | 3890.49 |  3.41
5 objects
2024-05-24T15:41:49.205Z iteration 1 passed in 2492 ms
```

**Comment by x1i4b1x2** [comment]
Yes now it works

**Comment by carlosmiei** [comment]
@x1i4b1x2 Cool, in that case will close the issue, let us know if anything!
