### ISSUE TITLE
python ccxt fetch_ohlcv on kraken doesnt honor since parameter 

### ISSUE THREAD

**Issue by Simoliv** [ccxt/ccxt#22606]
### Operating System

ubuntu

### Programming Languages

Python

### CCXT Version

4.3.28

### Description

Hey guys, I am wondering if I am making any mistakes or this is expected behaviour.

When using exchange.fetch_ohlcv at least on kraken I always get the full 720 ohlcv's from kraken, no matter if I use a "since" parameter. I had expected to just get 10 when using the since parameters.

When using the API directly like 

`curl -s "https://api.kraken.com/0/public/OHLC?pair=ETHEUR&interval=60&since=$(date +%s)" | jq -r
{   
  "error": [],   
  "result": {   
    "XETHZEUR": [   
      [   
        1716544800,   
        "3401.65",   
        "3412.00",   
        "3401.28",   
        "3408.01",   
        "3405.76",   
        "67.23911980",   
        394   
      ]   
    ],   
    "last": 1716541200   
  }   
}
`

which looks correct to me. (Of course this candle is not closed yet)

When running python ccxt code in DEBUG I see the following request going to kraken API :

`DEBUG:ccxt.base.exchange:GET https://api.kraken.com/0/public/OHLC?pair=XETHZEUR&interval=1&since=1716546459000000, Request: None None
DEBUG:ccxt.base.exchange:GET https://api.kraken.com/0/public/OHLC?pair=XETHZEUR&interval=1&since=1716546459000000, Response: 200`

which to me looks like the since parameter is in ms and not "epoch since", although I try to set it in python : 

`           current_timestamp = int(time.time())
            timestamp_minus_10_seconds = current_timestamp - 10
            print("current timestamp:", current_timestamp)
            print("10 seconds ago:", timestamp_minus_10_seconds)
            ohlcv_data = await exchange.fetch_ohlcv(symbol, 1, timestamp_minus_10_seconds)
`
and I always get a full stack of 720 ohlcv sets.

Of course I can limit the output and the "since" shows me only 10 from the 720, but isnt this a bit overkill to pull this amount of data every time when I need only 10 ?

### Code

```
   current_timestamp = int(time.time())
            timestamp_minus_10_seconds = current_timestamp - 10
            print("current timestamp:", current_timestamp)
            print("10 seconds ago:", timestamp_minus_10_seconds)

            ohlcv_data = await exchange.fetch_ohlcv(symbol, 1, timestamp_minus_10_seconds)

```

**Comment by carlosmiei** [comment]
Hello @Simoliv,
I think the problem here is that you're not providing the timestamp in `milliseconds` (that's the unit accepted by ccxt), if you do the filtering works as expected, example:

```
p kraken fetchOHLCV "BTC/USDT" 1h 1716523348000
Python v3.11.7
CCXT v4.3.29
kraken.fetchOHLCV(BTC/USDT,1h,1716523348000)
[[1716526800000, 67692.8, 67692.8, 67132.0, 67307.3, 20.92610534],
 [1716530400000, 67307.4, 67578.4, 66885.3, 66919.2, 21.12324464],
 [1716534000000, 66885.4, 67264.5, 66885.3, 67146.2, 9.26828411],
 [1716537600000, 67164.0, 67185.3, 66624.9, 67185.3, 7.58390828],
 [1716541200000, 67185.3, 67405.3, 67045.0, 67363.6, 14.83360952],
 [1716544800000, 67363.6, 67484.7, 67316.4, 67341.9, 10.62040474],
 [1716548400000, 67353.6, 67394.9, 67353.6, 67394.9, 0.09642151]]
```

**Comment by Simoliv** [comment]
Hey thanks for taking care ! 
I think I tried that before, all different kinds of timestamps (s, ms) but as far as I see when running in DEBUG mode, it always pulls the maximum of Krakens API of 720 ohlcv data.

**Comment by carlosmiei** [comment]
@Simoliv Sorry you're completely right 🤦 , I will check it again

**Comment by carlosmiei** [comment]
@Simoliv I found an issue in the way we handle timestamps there, it will be fixed shortly; thanks once again.

**Comment by Simoliv** [comment]
De nada, estoy feliz si puedo ayudar.

**Comment by Simoliv** [comment]
Heyo I tested immediately, but I am afraid it still does it ?

I still get 719 items :

`
718 2024-05-24 13:43:00: Open=3414.21, High=3415.55, Low=3412.58, Close=3415.55, Volume=7.95294316
719 2024-05-24 13:44:00: Open=3416.43, High=3416.43, Low=3416.43, Close=3416.43, Volume=0.0056
`

Following code + output 

`            current_timestamp = int(time.time())
            timestamp_minus_10_seconds = current_timestamp - 10
            print("Aktueller Timestamp:", current_timestamp)
            print("Timestamp vor 10 Sekunden:", timestamp_minus_10_seconds)

            ohlcv_data = await exchange.fetch_ohlcv(symbol, timeframe, timestamp_minus_10_seconds)
            print (timestamp_minus_10_seconds)
            print(len(ohlcv_data))
            await exchange.close()
            exit(0)
`

4","3412.55","19.46872018",13],[1716558420,"3413.46","3414.14","3410.80","3412.67","3413.21","0.39661594",16],[1716558480,"3411.95","3411.95","3411.02","3411.22","3411.18","0.75549451",5]],"last":1716558420}}
1716558478
720

**Comment by carlosmiei** [comment]
@Simoliv A new version with the fix was not released yet, will be shortly

**Comment by Simoliv** [comment]
I thought after seeing 4.3.30 this was the new one, since I had 4.3.28 before. And according to pypi it was released just today, so I thought its included already, apologies.

**Comment by carlosmiei** [comment]
@Simoliv We just released, if you update it should be working now
