### ISSUE TITLE
Bitget - increase speed limit on createOrder

### ISSUE THREAD

**Issue by krasnyd** [ccxt/ccxt#22621]
### Operating System

Ubuntu

### Programming Languages

Python

### CCXT Version

4.3.19

### Description

The documentation for [Place Order](https://www.bitget.com/api-doc/contract/trade/Place-Order) on Bitget says the following:

> Speed limit is 10 times/s for average users. Frequency limit imposed according to user ID
> Speed limit is 1 times/s for copy trade traders. Frequency limit imposed according to user ID

The endpoint cost is currently configured to 20, which means, that with the default rateLimit 50 ms, it sends 1 request per second. Would it be possible to switch between the "average user" mode and the "copy trade traders" mode?
https://github.com/ccxt/ccxt/blob/28a13b79c3d67a5db8b85a35067612422868fc08/python/ccxt/abstract/bitget.py#L269

When I tested it, the Bitget API did not have any problems with processing 10 requests per second, so I think this endpoint should be configured as `cost=2` by default. 

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @krasnyd, I think you're right, normal users are the majority here so we can update it and make it cost = 2.
Will do it shortly.
