### ISSUE TITLE
Revert exchange name "Coinbase Advanced" back to "Coinbase" for backward compatibility...

### ISSUE THREAD

**Issue by jtashiro** [ccxt/ccxt#22633]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

I've been using ccxt for crypto trading and reporting and have relied on the exchange name field to report.  By renaming Coinbase to Coinbase Advanced I'm now getting 2 sets of reports based on the API key in use.  This is confusing as the Exchange has not changed, only the method for accessing the Exchange.  

### Describe the solution you'd like

I'd like an option to override the exchange name for Coinbase Advanced back to Coinbase.  Ideally that would be the normal state, and a new property added describing the APIs or other method that differentiates the access path.

### Describe alternatives you've considered

I considered patching coinbase.py to revert the name, or calling setattr(..) as test/test_sync.py does but not sure if that is workable.

**Comment by carlosmiei** [comment]
Hello @jtashiro, I'm not sure I understand what the issue is, `coinbase` represents `coinbase advanced` for a while now.
Besides that, we have
-`coinbaseexchange`
-`coinbaseinternational`
-`coinbaseadvanced`-> this is just an alias for  the `coinbase` class

**Comment by jtashiro** [comment]
Somewhere between 4.2.51 and 4.3.x the exchange name changed from “Coinbase” to “Coinbase Advanced”.  In terms of the Exchange name, it should remain ‘Coinbase’.  “Coinbase Advanced” is the access mechanism to the exchange … that’s what I’m referring to as a separate property of an exchange. 

4.2.15 - coinbase.py

    def describe(self):
        return self.deep_extend(super(coinbase, self).describe(), {
            'id': 'coinbase',
            'name': 'Coinbase’,


4.3.33

    def describe(self):
        return self.deep_extend(super(coinbase, self).describe(), {
            'id': 'coinbase',
            'name': 'Coinbase Advanced',

**Comment by jtashiro** [comment]
> @jtashiro Yes it was renamed recently but it was already representing `Coinbase Advanced`. If needed you can override these values on your end, example:
> 
> ```
> exchange.id = 'new id'
> exchange.name = 'new name'
> ```

That will work for my purposes.
