### ISSUE TITLE
Bitmart error fetching tickers

### ISSUE THREAD

**Issue by SAuKS81** [ccxt/ccxt#22631]
### Operating System

Windows 11

### Programming Languages

Python

### CCXT Version

4.3.34

### Description

Fetching Tickers on exchange Bitmart leads to error: _invalid literal for int() with base 10: ''_

### Code

```
import ccxt

exchange = ccxt.bitmart()

print('CCXT Version: ' + str(ccxt.__version__))
try:
    tickers = exchange.fetch_tickers()
    print(tickers)
except Exception as e:
    print(f"{e}")

```

**Comment by xmatthias** [comment]
Same problem for me - with various / different versions (tested down to 4.3.20).
i know it still worked a few hours ago (according to our CI) - so i suspect this is a change at the bitmart side that's causing this.

**Comment by carlosmiei** [comment]
Hello @xmatthias @SAuKS81, we will check it asap.
