### ISSUE TITLE
Coinbase: Implementing fetch_trading_fees?

### ISSUE THREAD

**Issue by jtashiro** [ccxt/ccxt#22643]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

When do you plan to implement the coinbase fetch_trading_fees be available in the ccxt library?

### Describe the solution you'd like

I'd like to be able to get the current trading fees set for my trading account using ccxt.

### Describe alternatives you've considered

I've added extensions which I need to incorporate into each ccxt update and would like to have these available in the regular ccxt releases.

    def get_fee_tier(self,  params={}):
        """
        :returns dict: a transaction structure
        """
        request = {
        }
        response = self.v3PrivateGetBrokerageTransactionSummary(self.extend(request, params))
        data = self.safe_value(response, 'fee_tier', {})
        return self.parse_trade(data)

    def get_total_fees(self,  params={}):
        """
        :returns dict: a transaction structure
        """
        request = {
        }
        response = self.v3PrivateGetBrokerageTransactionSummary(self.extend(request, params))
        data = self.safe_value(response, 'total_fees', {})
        return self.parse_trade(data)

**Comment by jtashiro** [comment]
thank you let me know if you need help to test.  Sent from my iPhoneOn May 28, 2024, at 11:04 AM, Carlos Gonçalves ***@***.***> wrote:﻿
Hello @jtashiro, thanks for your suggestion, yes I think we can implement fetchTradingFees using v3PrivateGetBrokerageTransactionSummary

**Comment by jtashiro** [comment]
Do you think you can add this as well given your quick turnaround … I’ve provided the working code in the issue.  


https://github.com/ccxt/ccxt/issues/21432￼

**Comment by carlosmiei** [comment]
@jtashiro `fetchTradingFees` should be available in the latest version.

Regarding your question unfortunately that is not a unified method so we can't add it.

**Comment by jtashiro** [comment]
Thanks for feedback on the non-unified method.
