### ISSUE TITLE
ccxt pro bingX watchTrades in swap market return empty list in python

### ISSUE THREAD

**Issue by EricChouEric** [ccxt/ccxt#22657]
### Operating System
macos  

### Programming Languages
python 3.10

### CCXT Version
latest version

### Description

BingX.watch_trades will return [ ] if exchange is BingX but Binance fine

I have dived into deep in the source code. In watch_trades function, marketType, url, messeageHash is correct

### Code

```
symbol = 'PYTH/USDT:USDT'
trade = await BingX.watch_trades(symbol, since=None, limit=1, params={})  

```

**Comment by carlosmiei** [comment]
Hello @EricChouEric, thanks for reporting it, we will take a look asap.

**Comment by carlosmiei** [comment]
@EricChouEric Can you update your ccxt version and try again? should be working now

**Comment by EricChouEric** [comment]
ok, thanks a lot! Have a nice day
