### ISSUE TITLE
Binance watch_order_book silently hangs indefinitely

### ISSUE THREAD

**Issue by colin-nl** [ccxt/ccxt#22662]
### Operating System

Debian 12

### Programming Languages

Python

### CCXT Version

4.3.31

### Description

I am connecting to Binance Sandbox and have async tasks using `watch_order_book`, `watch_orders`, `watch_balance`, etc listening for updates. I am noticing that `watch_order_book` seems to silently hang and stops returning prices after being connected for some time. There is no exception thrown, I just simply get stuck awaiting for `watch_order_book` forever. In my latest test it took about 12 hours for this error to occur. I am running this on AWS so the connection quality should be pretty solid.

I'm listening to the extremely liquid BTC/USDT pair so I expect order book updates several times a second. I tried working around the problem by timing out the await after 30 seconds and calling `watch_order_book` again my loop. Unfortunately, subsequent calls do not return any prices even if I wait several hours. It seems that once the silent disconnection occurs, calling `watch_order_book` again will not trigger any sort of internal reconnect. I need to restart the application to get it to reconnect.

From my reading of the manual, CCXT is supposed to manage the websocket connection internally and reconnect on any failures. Because no exceptions were thrown, I suspect that CCXT does not know that it is disconnected and thus does not try to reconnect upon the next call of `watch_order_book`. I suspect that this could be fixed by an internal heartbeat mechanism to determine connection liveliness even if the websocket doesn't throw an explicit error. Does CCXT have this functionality built in?

Looking at existing issues, it seems that others are experiencing this problem too:
https://github.com/ccxt/ccxt/issues/21731
https://github.com/ccxt/ccxt/issues/20412
https://github.com/ccxt/ccxt/issues/12279 (seems related, but not exactly the same)

### Code

```
async def subscribe(self, exchange, args):
    while True:
        try:
            async with asyncio.timeout(30):
                data = await exchange.watch_order_book(["BTC/USDT", 10])

            print(data)
        except asyncio.CancelledError:
            print(f"Task cancelled: {exchange}")
            raise
        except asyncio.TimeoutError:
            print(f"Task {exchange} timed out. Rescheduling.")
        except ccxt.BaseError as e:
            print(f"Caught ccxt error in task {exchange}: {e}")
        except Exception as e:
            print(f"Exception caught in subscribe: {e}")
            raise
```

When running the code above, I do not see any exceptions when the silent error occurs other than the timeout. If I remove the timeout, it will just hang indefinitely. I would have expected to catch a ccxt exception or any other exception if there were connection issues.

**Comment by WillPCowan** [comment]
Finding Binance market data becoming stale as an issue too

**Comment by ivanmorozwl** [comment]
The same issue I met many times for other exchanges like bitget, gateio for javascript library

**Comment by tuloski** [comment]
Having the same issue.
The problem is that there is no thrown event/error so it becomes difficult to track it and react to it (reconnect, recreate another exchange instance, ...).
Using other Binance JS libraries I don't see the same problem and I keep connections open for many days, so it looks a ccxt problem.
