### ISSUE TITLE
amount_to_string doc

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#2266]
For the future doc, would you address more about how to use `amount_to_string`? @kroitor 

`market. amount_to_string( symbol, raw_amount)` the raw amount is any value given by the base amount.

**Comment by kroitor** [comment]
Yes, sure, we are currently reworking this part of functionality here:

- https://github.com/ccxt/ccxt/pull/1635
- https://github.com/ccxt/ccxt/pull/2121
- https://github.com/ccxt/ccxt/pull/2171

Also related to this:

- https://github.com/ccxt/ccxt/issues/1483

As soon as we merge the above three pull-requests, we are going to write a section of documentation about it.

Hope it answers your question. Thx!
