### ISSUE TITLE
Basic commands from USD market not functional with USDT

### ISSUE THREAD

**Issue by BingBong1234567898765321** [ccxt/ccxt#22671]
### Operating System

Windows 11 - PythonAnywhere.com

### Programming Languages

Python

### CCXT Version

4.3.21

### Description

Since Phemex delisted BTC/USD:USD I have to convert my script to BTC/USDT:USDT.

A lot of the basic functions that have always worked with USD are not functional with USDT markets. For example, when running:
open_order_status = exchange.fetch_order_status(id = new_order_id, symbol= symbol)
Returns error: phemexfetchOrder() is not supported yet for USDT settled swap markets

If I run:
exchange.fetch_open_orders(id = new_order_id, symbol = symbol)
Returns error: unexpected keyword argument 'id'

Again, these functions have always worked with BTC/USD:USD, and the order structure as defined here: [https://docs.ccxt.com/#/?id=order-structure] shows that 'id' is in fact a field.

why does fetch_order_status not work for USDT? Why does fetch_open_orders not recognize the 'id' key?

Thank you!

### Code

```
            try:
                open_order_status = exchange.fetch_order_status(id = new_order_id, symbol= symbol)
                print(f"open order status: {open_order_status}")
            except Exception as e:
                #open_order_status = 'closed'
                print(f"Exception found in new order ID: {e}")

```

**Comment by BingBong1234567898765321** [comment]
Can anyone help with this?

**Comment by carlosmiei** [comment]
Hello @BingBong1234567898765321, sorry I missed this issue.

IF you use `fetch_order` instead of `fetch_order_Status` does that work?

**Comment by carlosmiei** [comment]
@BingBong1234567898765321 oh ok I think I understood now, phemex does not support `fetch_order` for USDT settled swaps.

**Comment by carlosmiei** [comment]
@BingBong1234567898765321 Right now the only alternative you have is to use `fetch_open_orders` and `fetch_closed_orders` to get the order, depending of its state (open/closed)

- https://phemex-docs.github.io/#query-open-orders-by-symbol-2
- https://phemex-docs.github.io/#query-closed-orders-by-symbol-2

**Comment by BingBong1234567898765321** [comment]
So my goal is to determine when the limit order has been fulfilled. With USD previously, I have done this by using exchange.fetch_order_status(id = id, symbol = symbol). And it has always been able to read the status of "open" or "closed", and then proceed with the script accordingly.

With USDT, when I use things like fetch_order_status, or fetch_open_orders, or fetch_closed_orders, it says "unexpected argument found 'id'". When I remove the id param and then print the open orders, it prints data for multiple trading pairs that I don't even have open orders for, and fails to pull an order that I actually have open.

**Returned open order data from fetch_open_orders(symbol = 'BTC/USDT:USDT') while I do in fact have an open order:**

[{'info': {'userID': '4962467', 'accountID': '49624670002', 'symbol': 'uBTCUSD', 'currency': 'USD', 'side': 'None', 'position
Status': 'Normal', 'crossMargin': False, 'leverageEr': '500000000', 'leverage': '5.00000000', 'initMarginReqEr': '20000000', 'initMarginReq': '0.20000000', 'maintMarginReqEr': '500000', 'maintMarginReq': '0.00500000', 'riskLimitEv': '20000000000', 'riskLimit': '2000000.00000000', 'size': '0', 'value': '0E-8', 'valueEv': '0', 'avgEntryPriceEp': '0', 'avgEntryPrice': '0E-8', 'posCostEv': '0', 'posCost': '0E-8', 'assignedPosBalanceEv': '0', 'assignedPosBalance': '0E-8', 'bankruptCommEv': '0', 'bankruptComm': '0E-8', 'bankruptPriceEp': '0', 'bankruptPrice': '0E-8', 'positionMarginEv': '0', 'positionMargin': '0E-8', 'liquidationPriceEp': '0', 'liquidationPrice': '0E-8', 'deleveragePercentileEr': '0', 'deleveragePercentile': '0E-8', 'buyValueToCostEr': '20099000', 'buyValueToCost': '0.20099000', 'sellValueToCostEr': 
'20121000', 'sellValueToCost': '0.20121000', 'markPriceEp': '662495000', 'markPrice': '66249.50000000', 'estimatedOrdLossEv': '0', 'estim
atedOrdLoss': '0E-8', 'usedBalanceEv': '0', 'usedBalance': '0E-8', 'cumClosedPnlEv': '-53027602', 'cumFundingFeeEv': '850616', 'cumTransa
ctFeeEv': '58343059', 'transactTimeNs': '1717056000001416120', 'takerFeeRateEr': '55000', 'makerFeeRateEr': '0', 'term': '780', 'lastTerm
EndTimeNs': '1715294301655529234', 'lastFundingTimeNs': '1717056000000000000', 'curTermRealisedPnlEv': '-290730', 'execSeq': '16439294933
', 'freeQty': '0', 'freeCostEv': '0', 'buyLeavesValueEv': '0', 'sellLeavesValueEv': '0'}, 'id': None, 'symbol': 'BTC/USD:USD', 'contracts
': 0.0, 'contractSize': 0.001, 'unrealizedPnl': 0.0, 'leverage': 5.0, 'liquidationPrice': 0.0, 'collateral': 0.0, 'notional': 0.0, 'markP
rice': 66249.5, 'lastPrice': None, 'entryPrice': 0.0, 'timestamp': None, 'lastUpdateTimestamp': None, 'initialMargin': 0.0, 'initialMargi
nPercentage': None, 'maintenanceMargin': 0.0, 'maintenanceMarginPercentage': 0.005, 'marginRatio': None, 'datetime': None, 'marginMode': 
'isolated', 'side': 'short', 'hedged': False, 'percentage': None, 'stopLossPrice': None, 'takeProfitPrice': None}, {'info': {'userID': '4
962467', 'accountID': '49624670002', 'symbol': 'ETHUSD', 'currency': 'USD', 'side': 'None', 'positionStatus': 'Normal', 'crossMargin': Fa
lse, 'leverageEr': '-1000000000', 'leverage': '-10.00000000', 'initMarginReqEr': '10000000', 'initMarginReq': '0.10000000', 'maintMarginR
eqEr': '500000', 'maintMarginReq': '0.00500000', 'riskLimitEv': '10000000000', 'riskLimit': '1000000.00000000', 'size': '0', 'value': '0E
-8', 'valueEv': '0', 'avgEntryPriceEp': '0', 'avgEntryPrice': '0E-8', 'posCostEv': '0', 'posCost': '0E-8', 'assignedPosBalanceEv': '0', '
assignedPosBalance': '0E-8', 'bankruptCommEv': '0', 'bankruptComm': '0E-8', 'bankruptPriceEp': '0', 'bankruptPrice': '0E-8', 'positionMar
ginEv': '0', 'positionMargin': '0E-8', 'liquidationPriceEp': '0', 'liquidationPrice': '0E-8', 'deleveragePercentileEr': '0', 'deleverageP
ercentile': '0E-8', 'buyValueToCostEr': '10104500', 'buyValueToCost': '0.10104500', 'sellValueToCostEr': '10115500', 'sellValueToCost': '
0.10115500', 'markPriceEp': '36968223', 'markPrice': '3696.82230000', 'estimatedOrdLossEv': '0', 'estimatedOrdLoss': '0E-8', 'usedBalance
Ev': '0', 'usedBalance': '0E-8', 'cumClosedPnlEv': '0', 'cumFundingFeeEv': '0', 'cumTransactFeeEv': '0', 'transactTimeNs': '1717056000001
285340', 'takerFeeRateEr': '55000', 'makerFeeRateEr': '0', 'term': '1', 'lastTermEndTimeNs': '0', 'lastFundingTimeNs': '17170560000000000
00', 'curTermRealisedPnlEv': '0', 'execSeq': '18398781035', 'freeQty': '0', 'freeCostEv': '0', 'buyLeavesValueEv': '0', 'sellLeavesValueE
v': '0'}, 'id': None, 'symbol': 'ETH/USD:USD', 'contracts': 0.0, 'contractSize': 0.005, 'unrealizedPnl': 0.0, 'leverage': 10.0, 'liquidat
ionPrice': 0.0, 'collateral': 0.0, 'notional': 0.0, 'markPrice': 3696.8223, 'lastPrice': None, 'entryPrice': 0.0, 'timestamp': None, 'las
tUpdateTimestamp': None, 'initialMargin': 0.0, 'initialMarginPercentage': None, 'maintenanceMargin': 0.0, 'maintenanceMarginPercentage': 
0.005, 'marginRatio': None, 'datetime': None, 'marginMode': 'isolated', 'side': 'short', 'hedged': False, 'percentage': None, 'stopLossPr
ice': None, 'takeProfitPrice': None}]

**Comment by BingBong1234567898765321** [comment]
Do you have any suggestions on how to get my script to determine when the order has been fulfilled if I can't pull data on the specific order ID?

**Comment by carlosmiei** [comment]
@BingBong1234567898765321 Unfortunately, the only way I see is by either using websockets to detect when the order is filled or by performing 2 different requests (fetch_open_orders/fetch_closed_orders) and see which returns your order.

**Comment by BingBong1234567898765321** [comment]
Do you know when the commands that aren't supported in USDT markets will be available for USDT?

**Comment by carlosmiei** [comment]
@BingBong1234567898765321 Other than `fetch_order` pretty much all the other methods are available for USDT markets

**Comment by BingBong1234567898765321** [comment]
Well it appears fetch_order_status is also not supported, and if the other commands don't allow 'id' to identify the order I've placed, then I won't be able to find which command (fetch_open_orders or fetch_closed_orders) has my order. And I am unfamiliar with websockets. It would be very helpful if fetch_order and fetch_order_status were made available for USDT.

**Comment by carlosmiei** [comment]
@BingBong1234567898765321 We will add `fetchOrders` to USDT swaps here: https://github.com/ccxt/ccxt/pull/22781

**Comment by BingBong1234567898765321** [comment]
> @BingBong1234567898765321 We will add `fetchOrders` to USDT swaps here: https://github.com/ccxt/ccxt/pull/22781

So is this live now?

**Comment by carlosmiei** [comment]
@BingBong1234567898765321 Yes you just need to update your ccxt version

**Comment by BingBong1234567898765321** [comment]
@carlosmiei  Sorry for the delay, I have been traveling for work. I've now updated my CCXT version and ran it again. I'm getting the below lines of errors. Initially, this looks to me like Phemex is having server issues, but the latest messages on the Phemex API Telegram group show people complaining about the "Try Again Later" error and the moderator's response is saying that they are getting this because Phemex delisted USD. Now that I look deeper into this errors, it references a Phemex API endpoint with USD mentioned, but I have changed the symbol and the currency (for things like fetching balances).

Do you think the parameter being set to "swap" has anything to do with this? Or is it something else?

Errors I am getting:

Traceback (most recent call last):
  File "/home/BingBong/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 651, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.phemex.com/accounts/accountPositions?currency
=USD&type=swap
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/BingBong/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3740, in request
  File "/home/BingBong/Atnis.py", line 56, in <module>
    init_positions = exchange.fetch_positions(params=init_fetch_position_params)
  File "/home/BingBong/.local/lib/python3.10/site-packages/ccxt/phemex.py", line 3408, in fetch_positions
    response = self.privateGetAccountsAccountPositions(self.extend(request, params))
  File "/home/BingBong/.local/lib/python3.10/site-packages/ccxt/base/types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/home/BingBong/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3740, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/home/BingBong/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3737, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/BingBong/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 667, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/BingBong/.local/lib/python3.10/site-packages/ccxt/phemex.py", line 4472, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: phemex {"msg":"Please try again later","code":10500}

**Comment by BingBong1234567898765321** [comment]
@carlosmiei hey Carlos, any update on this? I tried addressing it with the Phemex API telegram group and they said it's a CCXT issue so they can't provide any information

**Comment by carlosmiei** [comment]
Hello @BingBong1234567898765321, what's the ccxt you're running?

**Comment by BingBong1234567898765321** [comment]
@carlosmiei  I am running 4.3.48

**Comment by carlosmiei** [comment]
@BingBong1234567898765321 yes but what's the unified call being made here?

**Comment by BingBong1234567898765321** [comment]
@carlosmiei below is the section of code causing this error, specifically the bolded line:

config = dontshare_config
api_key = config.xP_key
api_secret = config.secret
symbol = config.sym
exchange = ccxt.phemex({
    'apiKey': api_key,
    'secret': api_secret,
    'enableRateLimit': True,
    'params': {
        'type': 'swap',
    }
})
init_fetch_position_params={'type':'swap'}
try:
    **init_positions = exchange.fetch_positions(params=init_fetch_position_params)**
except requests.exceptions.HTTPError as err:
    print("HTTP Error occurred:", err)

**Comment by BingBong1234567898765321** [comment]
@carlosmiei  I should note that the config.sym is 'BTC/USDT:USDT'

**Comment by carlosmiei** [comment]
> @carlosmiei below is the section of code causing this error, specifically the bolded line:
> 
> config = dontshare_config api_key = config.xP_key api_secret = config.secret symbol = config.sym exchange = ccxt.phemex({ 'apiKey': api_key, 'secret': api_secret, 'enableRateLimit': True, 'params': { 'type': 'swap', } }) init_fetch_position_params={'type':'swap'} try: **init_positions = exchange.fetch_positions(params=init_fetch_position_params)** except requests.exceptions.HTTPError as err: print("HTTP Error occurred:", err)

@BingBong1234567898765321 both `/USD:USD` and `/USDT:USDT` are swaps, so providing `type=swap` here is not enough to select USDT positions.

In this case you can provide `settle:USDT`, eg: `usdt_swaps = await phemex.fetch_positions(params={'settle':'USDT'})`

**Comment by BingBong1234567898765321** [comment]
@carlosmiei  that seems to have gotten past the error, thank you!

**Comment by carlosmiei** [comment]
@BingBong1234567898765321 No problem 🙂 , in that case I'm going to close this issue let us know if anything!
