### ISSUE TITLE
Bybit CreateOrderWs with bound IP Address

### ISSUE THREAD

**Issue by SAuKS81** [ccxt/ccxt#22695]
### Operating System

Windows 11

### Programming Languages

Python

### CCXT Version

4.3.37

### Description

Hello,

i am experiencing an issue when trying to create an order using the createOrderWs function on Bybit. The error message I receive is: "Unmatched IP, please check your API key's bound IP addresses." However, the createOrder function works fine with the same API key, and using an API key with unbound IP addresses also works fine fo rcreateOrderWs function.
So i am not sure if it is an ccxt related problem or more a problem on the exchange itself.

### Code

```
 async def place_order(exchange):
    
    side = 'buy'
    if side == 'buy':
        idx = 1
    else:
        idx = 2

    order_data = {
        "timeInForce": "GTC",
        "positionIdx": idx,
        "reduceOnly": False
    }

    exchange.verbose = True  

    result = await exchange.createOrderWs('ETH/USDT', 'limit', side, 0.01, 3000, order_data)
    print(result['id']) 

```

**Comment by carlosmiei** [comment]
Hello @SAuKS81,

Hum, in that case, I don't see how this could be related to CCXT. Maybe the IP binding does not work for websocket connections?

**Comment by SAuKS81** [comment]
Hello @carlosmiei ,

I also tested https://github.com/bybit-exchange/api-usage-examples/blob/master/V5_demo/wss_demo/python/ws_trade_api_demo.py and had the same problem.
So no error in ccxt.

**Comment by SAuKS81** [comment]
One additional comment. Sending the order via IPV4 works fo me.
