### ISSUE TITLE
Cannot import functions

### ISSUE THREAD

**Issue by cybzen** [ccxt/ccxt#22693]
### Operating System

MacOS

### Programming Languages

JavaScript

### CCXT Version

"ccxt": "^4.3.37"

### Description

```
"ccxt": "^4.3.37",
"typescript": "^5.4.5",
```

I want to calculate accuracy problems, see the documentation can use functions,

Typescript: https://github.com/ccxt/ccxt/blob/master/ts/src/test/base/functions/test.number.ts

```
// test.ts
import { Precise, functions  } from 'ccxt';
console.log("functions-->", functions);
```

```
✗ ts-node test.ts
functions--> undefined
```

**problem ->>>>>>** `functions is undefined`

-----------

**ts will prompt, mouse click functions to go to the definition function, and, functions. Corresponding functions and variables appear** 

**TypeError: Cannot read properties of undefined (reading 'ROUND')**

![111](https://github.com/ccxt/ccxt/assets/9928645/07caf037-ab81-4c6e-a9b8-440825a5d10f)

### Code

```
  

```

**Comment by cybzen** [comment]
```
import ccxt from 'ccxt';
console.log(ccxt.ROUND);
console.log(ccxt.numberToString(-7.8e-7));
```

```
1
-0.00000078
```

**Comment by carlosmiei** [comment]
@cybzen Did you find a solution for your problem?
