### ISSUE TITLE
Coinbase fetch_accounts_v3 limit of 100 breaks deposit()

### ISSUE THREAD

**Issue by jtashiro** [ccxt/ccxt#22697]
### Operating System

Mac OS Ventura and Ubuntu 22.0

### Programming Languages

python 3.x

### CCXT Version

4.3.35

### Description

fetch_accounts_v3() has internal limit of 100 which is too restrictive for coinbase accounts with more than 100 wallets, resulting in "could not find account ID for USD" when trying to call deposit().  In my case, my USD wallet is #145 resulting in this error...

default limit = 100
ERROR: coinbase deposit() could not find account id for USD. rc=1

Limit change to 250, deposit() works.

### Code

```
      def fetch_accounts_v3(self, params={}) -> List[Account]:
        self.load_markets()
        paginate = False
        paginate, params = self.handle_option_and_params(params, 'fetchAccounts', 'paginate')
        if paginate:
            return self.fetch_paginated_call_cursor('fetchAccounts', None, None, None, params, 'cursor', 'cursor', None, 250)
        request: dict = {
            'limit': 250,
        }
        response = self.v3PrivateGetBrokerageAccounts(self.extend(request, params))

```

**Comment by carlosmiei** [comment]
Hello @jtashiro,
Thanks for reporting it.
We will update the limit.

**Comment by jtashiro** [comment]
Great thank you.  Sent from my iPhoneOn Jun 2, 2024, at 4:57 AM, Carlos Gonçalves ***@***.***> wrote:﻿
Hello @jtashiro,
Thanks for reporting it.
We will update the limit.
