### ISSUE TITLE
HTX: authentication error in C#

### ISSUE THREAD

**Issue by carlosmiei** [ccxt/ccxt#22703]
### Description

- relates to https://github.com/ccxt/ccxt/issues/9189
- reported by @flowerDAI
Context:

![image](https://github.com/ccxt/ccxt/assets/43336371/02cd69c3-27bf-4c90-a7e1-56ef4c51f492)

**Comment by flowerDAI** [comment]
thank you , I  just try python, use fetch_accounts(), it is ok.
but use C#, still showing this error  “Signature not valid: Verification failure [校验失败]”

url :  
https://api.huobi.pro/v1/account/accounts?AccessKeyId=XXXXXXXXXXXXXXXXXXXX&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2024-06-03T07%3a43%3a21&Signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX%3d

**Comment by carlosmiei** [comment]
@flowerDAI Yeah, I found the issue (it's related to the URL encoding of timestamps in C#). Will be fixed shortly.

**Comment by carlosmiei** [comment]
@flowerDAI Can you please update your ccxt version and try again? I believe it should be working now.

**Comment by flowerDAI** [comment]
> @flowerDAI Can you please update your ccxt version and try again? I believe it should be working now.

I just tried it. it's okay. thank you
