### ISSUE TITLE
The order amount must exceed 0.1 USDT while making a trade of 3 USDT

### ISSUE THREAD

**Issue by ShahwaizJerrax** [ccxt/ccxt#22702]
### Operating System

windows

### Programming Languages

PHP

### CCXT Version

4.3.13

### Description

While creating a trade i got an error that the order amount must exceed 0.1 USDT while making a trade of 3 USDT

### Code

// the function where we call it 

$order = $tradeType == 'limit' ? $this->api->create_order($request->symbol . '/' . $request->currency, $tradeType, $side, $request->amount, $request->price) 
            : $this->api->create_order($request->symbol . '/' . $request->currency, $tradeType, $side, $request->amount)

// end function call 

the function body from the package 

public function create_order(string $symbol, string $type, string $side, float $amount, ?float $price = null, $params = array ()) {
        /**
         * Create an order on the exchange
         * @see https://docs.kucoin.com/spot#place-a-new-order
         * @see https://docs.kucoin.com/spot#place-a-new-order-2
         * @see https://docs.kucoin.com/spot#place-a-margin-order
         * @see https://docs.kucoin.com/spot-hf/#place-hf-order
         * @see https://www.kucoin.com/docs/rest/spot-trading/orders/place-order-test
         * @see https://www.kucoin.com/docs/rest/margin-trading/orders/place-margin-order-test
         * @param {string} $symbol Unified CCXT $market $symbol
         * @param {string} $type 'limit' or 'market'
         * @param {string} $side 'buy' or 'sell'
         * @param {float} $amount the $amount of currency to trade
         * @param {float} [$price] ignored in "market" orders the $price at which the order is to be fullfilled at in units of the quote currency
         * @param {array} [$params]  extra parameters specific to the exchange API endpoint
         * @param {float} [$params->triggerPrice] The $price at which a trigger order is triggered at
         * @param {string} [$params->marginMode] 'cross', // cross (cross mode) and isolated (isolated mode), set to cross by default, the isolated mode will be released soon, stay tuned
         * @param {string} [$params->timeInForce] GTC, GTT, IOC, or FOK, default is GTC, limit orders only
         * @param {string} [$params->postOnly] Post only flag, invalid when timeInForce is IOC or FOK
         *
         * EXCHANGE SPECIFIC PARAMETERS
         * @param {string} [$params->clientOid] client order id, defaults to uuid if not passed
         * @param {string} [$params->remark] remark for the order, length cannot exceed 100 utf8 characters
         * @param {string} [$params->tradeType] 'TRADE', // TRADE, MARGIN_TRADE // not used with margin orders
         * limit orders ---------------------------------------------------
         * @param {float} [$params->cancelAfter] long, // cancel after n seconds, requires timeInForce to be GTT
         * @param {bool} [$params->hidden] false, // Order will not be displayed in the order book
         * @param {bool} [$params->iceberg] false, // Only a portion of the order is displayed in the order book
         * @param {string} [$params->visibleSize] $this->amount_to_precision($symbol, visibleSize), // The maximum visible size of an iceberg order
         * $market orders --------------------------------------------------
         * @param {string} [$params->funds] // Amount of quote currency to use
         * stop orders ----------------------------------------------------
         * @param {string} [$params->stop]  Either loss or entry, the default is loss. Requires stopPrice to be defined
         * margin orders --------------------------------------------------
         * @param {float} [$params->leverage] Leverage size of the order
         * @param {string} [$params->stp] '', // self trade prevention, CN, CO, CB or DC
         * @param {bool} [$params->autoBorrow] false, // The system will first borrow you funds at the optimal interest rate and then place an order for you
         * @param {bool} [$params->hf] false, // true for hf order
         * @param {bool} [$params->test] set to true to test an order, no order will be created but the request will be validated
         * @return {array} an @link https://docs.ccxt.com/#/?id=order-structure order structure
         */
        $this->load_markets();
        $market = $this->market($symbol);
        $testOrder = $this->safe_bool($params, 'test', false);
        $params = $this->omit($params, 'test');
        $isHf = $this->safe_bool($params, 'hf', false);
        list($triggerPrice, $stopLossPrice, $takeProfitPrice) = $this->handle_trigger_prices($params);
        $tradeType = $this->safe_string($params, 'tradeType'); // keep it for backward compatibility
        $isTriggerOrder = ($triggerPrice || $stopLossPrice || $takeProfitPrice);
        $marginResult = $this->handle_margin_mode_and_params('createOrder', $params);
        $marginMode = $this->safe_string($marginResult, 0);
        $isMarginOrder = $tradeType === 'MARGIN_TRADE' || $marginMode !== null;
        // don't omit anything before calling createOrderRequest
        $orderRequest = $this->create_order_request($symbol, $type, $side, $amount, $price, $params);
        $response = null;
        if ($testOrder) {
            if ($isMarginOrder) {
                $response = $this->privatePostMarginOrderTest ($orderRequest);
            } else {
                $response = $this->privatePostOrdersTest ($orderRequest);
            }
        } elseif ($isHf) {
            $response = $this->privatePostHfOrders ($orderRequest);
        } elseif ($isTriggerOrder) {
            $response = $this->privatePostStopOrder ($orderRequest);
        } elseif ($isMarginOrder) {
            $response = $this->privatePostMarginOrder ($orderRequest);
        } else {
            $response = $this->privatePostOrders ($orderRequest);
        }
        //
        //     {
        //         "code" => "200000",
        //         "data" => {
        //             "orderId" => "5bd6e9286d99522a52e458de"
        //         }
        //    }
        //
        $data = $this->safe_dict($response, 'data', array());
        return $this->parse_order($data, $market);
    }

**Comment by carlosmiei** [comment]
Hello @ShahwaizJerrax, what was the symbol/side/type/amount/price used?

**Comment by ShahwaizJerrax** [comment]
symbol was  AVA
side was  buy
type was  market 
amount was 4
price was 0.7047
i believe when the type is market the field price is not required 
between thanks for the quick response

**Comment by ShahwaizJerrax** [comment]
> Hello @ShahwaizJerrax, what was the symbol/side/type/amount/price used?

symbol was AVA
side was buy
type was market
amount was 4
price was 0.7047
i believe when the type is market the field price is not required
between thanks for the quick response

**Comment by carlosmiei** [comment]
@ShahwaizJerrax Yes the market is not needed here, and I just tested and seems to be working
```
 ph kucoin createOrder "AVA/USDT" market buy 4
PHP v8.3.7
CCXT version :4.3.38
kucoin->createOrder(AVA/USDT, market, buy, 4)
Array
(
    [info] => Array
        (
            [orderId] => 665da427563a26000739e735
        )

    [id] => 665da427563a26000739e735
    [clientOrderId] => 
    [symbol] => AVA/USDT
    [type] => 
    [timeInForce] => 
    [postOnly] => 
    [side] => 
    [amount] => 
    [price] => 
    [stopPrice] => 
```

Can you share a verbose log? `exchange.verbose = true`

**Comment by ShahwaizJerrax** [comment]
> @ShahwaizJerrax Yes the market is not needed here, and I just tested and seems to be working
> 
> ```
>  ph kucoin createOrder "AVA/USDT" market buy 4
> PHP v8.3.7
> CCXT version :4.3.38
> kucoin->createOrder(AVA/USDT, market, buy, 4)
> Array
> (
>     [info] => Array
>         (
>             [orderId] => 665da427563a26000739e735
>         )
> 
>     [id] => 665da427563a26000739e735
>     [clientOrderId] => 
>     [symbol] => AVA/USDT
>     [type] => 
>     [timeInForce] => 
>     [postOnly] => 
>     [side] => 
>     [amount] => 
>     [price] => 
>     [stopPrice] => 
> ```
> 
> Can you share a verbose log? `$exchange->verbose = true`



Array
(
    [0] => fetch Response:
    [1] => kucoin
    [2] => POST
    [3] => https://api.kucoin.com/api/v1/orders
    [4] => 200
    [5] => 
    [6] => ResponseHeaders:
    [7] => Array
        (
            [Date] => Mon, 03 Jun 2024 11:22:16 GMT
            [Content-Type] => application/json
            [Transfer-Encoding] => chunked
            [Connection] => keep-alive
            [Set-Cookie] => AWSALB=eDVqk1jK5g8ycNym4GG6Ifk9ZuMr4Lk2NGc3L1IZnbTRxo9s0AcEwA4VVvyT8fMtO5ruoRdK6OWDkm2/qaezskk2CsJbg90VlneqGcMMfs8g3po4jD/qtJ75k4dt; Expires=Mon, 10 Jun 2024 11:22:15 GMT; Path=/, AWSALBCORS=eDVqk1jK5g8ycNym4GG6Ifk9ZuMr4Lk2NGc3L1IZnbTRxo9s0AcEwA4VVvyT8fMtO5ruoRdK6OWDkm2/qaezskk2CsJbg90VlneqGcMMfs8g3po4jD/qtJ75k4dt; Expires=Mon, 10 Jun 2024 11:22:15 GMT; Path=/; SameSite=None; Secure, __cf_bm=JVczBTZisowPRwy6jTvfRrTFht8vpEG7MzQqy_6N5s8-1717413736-1.0.1.1-U0K5qmWBGCf.oNn0nGevh_hZg5tKgyHf3afMwlKDD97L.znIjh1PcrsQypNaoNRHkztOr8fdz29fkAfwChWkfA; path=/; expires=Mon, 03-Jun-24 11:52:16 GMT; domain=.kucoin.com; HttpOnly; Secure, _cfuvid=VkszCUT38AUhO6bXfKDwr.zzizmoyt7YcM5n5lNTOkg-1717413736191-0.0.1.1-604800000; path=/; domain=.kucoin.com; HttpOnly; Secure; SameSite=None
            [gw-ratelimit-remaining] => 3998
            [gw-ratelimit-limit] => 4000
            [gw-ratelimit-reset] => 29946
            [Strict-Transport-Security] => max-age=9800; includeSubDomains; preload
            [CF-Cache-Status] => DYNAMIC
            [Server] => cloudflare
            [CF-RAY] => 88df4de85bb93649-FRA
            [Content-Encoding] => br
        )

    [8] => ResponseBody:
    [9] => {"msg":"The order amount must exceed 0.1 USDT.","code":"400760"}
)

**Comment by ShahwaizJerrax** [comment]
> > @ShahwaizJerrax Yes the market is not needed here, and I just tested and seems to be working
> > ```
> >  ph kucoin createOrder "AVA/USDT" market buy 4
> > PHP v8.3.7
> > CCXT version :4.3.38
> > kucoin->createOrder(AVA/USDT, market, buy, 4)
> > Array
> > (
> >     [info] => Array
> >         (
> >             [orderId] => 665da427563a26000739e735
> >         )
> > 
> >     [id] => 665da427563a26000739e735
> >     [clientOrderId] => 
> >     [symbol] => AVA/USDT
> >     [type] => 
> >     [timeInForce] => 
> >     [postOnly] => 
> >     [side] => 
> >     [amount] => 
> >     [price] => 
> >     [stopPrice] => 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can you share a verbose log? `$exchange->verbose = true`
> 
> Array ( [0] => fetch Response: [1] => kucoin [2] => POST [3] => https://api.kucoin.com/api/v1/orders [4] => 200 [5] => [6] => ResponseHeaders: [7] => Array ( [Date] => Mon, 03 Jun 2024 11:22:16 GMT [Content-Type] => application/json [Transfer-Encoding] => chunked [Connection] => keep-alive [Set-Cookie] => AWSALB=eDVqk1jK5g8ycNym4GG6Ifk9ZuMr4Lk2NGc3L1IZnbTRxo9s0AcEwA4VVvyT8fMtO5ruoRdK6OWDkm2/qaezskk2CsJbg90VlneqGcMMfs8g3po4jD/qtJ75k4dt; Expires=Mon, 10 Jun 2024 11:22:15 GMT; Path=/, AWSALBCORS=eDVqk1jK5g8ycNym4GG6Ifk9ZuMr4Lk2NGc3L1IZnbTRxo9s0AcEwA4VVvyT8fMtO5ruoRdK6OWDkm2/qaezskk2CsJbg90VlneqGcMMfs8g3po4jD/qtJ75k4dt; Expires=Mon, 10 Jun 2024 11:22:15 GMT; Path=/; SameSite=None; Secure, __cf_bm=JVczBTZisowPRwy6jTvfRrTFht8vpEG7MzQqy_6N5s8-1717413736-1.0.1.1-U0K5qmWBGCf.oNn0nGevh_hZg5tKgyHf3afMwlKDD97L.znIjh1PcrsQypNaoNRHkztOr8fdz29fkAfwChWkfA; path=/; expires=Mon, 03-Jun-24 11:52:16 GMT; domain=.kucoin.com; HttpOnly; Secure, _cfuvid=VkszCUT38AUhO6bXfKDwr.zzizmoyt7YcM5n5lNTOkg-1717413736191-0.0.1.1-604800000; path=/; domain=.kucoin.com; HttpOnly; Secure; SameSite=None [gw-ratelimit-remaining] => 3998 [gw-ratelimit-limit] => 4000 [gw-ratelimit-reset] => 29946 [Strict-Transport-Security] => max-age=9800; includeSubDomains; preload [CF-Cache-Status] => DYNAMIC [Server] => cloudflare [CF-RAY] => 88df4de85bb93649-FRA [Content-Encoding] => br )
> 
> ```
> [8] => ResponseBody:
> [9] => {"msg":"The order amount must exceed 0.1 USDT.","code":"400760"}
> ```
> 
> )

amount => 0.6
currency => USDT
price => 0.7433
side => buy
symbol => AVA
type => market

ccxt version was 4.3.11 i upgraded it to the latest one

**Comment by ShahwaizJerrax** [comment]
@carlosmiei could you please tell what have i done wrong here your response will be highly appreciated

**Comment by carlosmiei** [comment]
@ShahwaizJerrax Your log does not have the most important part, the request body, so it's hard to debug it.

**Comment by ShahwaizJerrax** [comment]
> @ShahwaizJerrax Your log does not have the most important part, the request body, so it's hard to debug it.

Array
(
    [0] => fetch Request:
    [1] => kucoin
    [2] => POST
    [3] => https://api.kucoin.com/api/v1/orders
    [4] => RequestHeaders:
    [5] => Array
        (
            [KC-API-KEY-VERSION] => 2
            [KC-API-KEY] => 656e3443fd5ee3000198bff6
            [KC-API-TIMESTAMP] => 1717493160986
            [Content-Type] => application/json
            [KC-API-PASSPHRASE] => vtm0u7A3nnx0HVIqyy8wIe1SbtYGwWltTGWdFjgk2Is=
            [KC-API-SIGN] => YnAFjTvOhS7AMH63yaWBxRZYjb8ZiiOOlMzHeRr9qp0=
            [KC-API-PARTNER-SIGN] => LiqISjgbCjNAJrKhM5GDrljHtH3PdOLENmeSjz7Yw8E=
            [KC-API-PARTNER] => ccxt
            [KC-API-PARTNER-VERIFY] => true
        )

    [6] => RequestBody:
    [7] => {"clientOid":"4959a64d-86b4-4402-9299-497f6a4ebb5d","side":"buy","symbol":"AVA-USDT","type":"market","size":"0.6"}
)
Array
(
    [0] => fetch Request:
    [1] => kucoin
    [2] => POST
    [3] => https://api.kucoin.com/api/v1/orders
    [4] => RequestHeaders:
    [5] => Array
        (
            [0] => KC-API-KEY-VERSION: 2
            [1] => KC-API-KEY: 656e3443fd5ee3000198bff6
            [2] => KC-API-TIMESTAMP: 1717493160986
            [3] => Content-Type: application/json
            [4] => KC-API-PASSPHRASE: vtm0u7A3nnx0HVIqyy8wIe1SbtYGwWltTGWdFjgk2Is=
            [5] => KC-API-SIGN: YnAFjTvOhS7AMH63yaWBxRZYjb8ZiiOOlMzHeRr9qp0=
            [6] => KC-API-PARTNER-SIGN: LiqISjgbCjNAJrKhM5GDrljHtH3PdOLENmeSjz7Yw8E=
            [7] => KC-API-PARTNER: ccxt
            [8] => KC-API-PARTNER-VERIFY: true
        )

    [6] => RequestBody:
    [7] => {"clientOid":"4959a64d-86b4-4402-9299-497f6a4ebb5d","side":"buy","symbol":"AVA-USDT","type":"market","size":"0.6"}
)
Array
(
    [0] => fetch Response:
    [1] => kucoin
    [2] => POST
    [3] => https://api.kucoin.com/api/v1/orders
    [4] => 200
    [5] => 
    [6] => ResponseHeaders:
    [7] => Array
        (
            [Date] => Tue, 04 Jun 2024 09:26:01 GMT
            [Content-Type] => application/json
            [Transfer-Encoding] => chunked
            [Connection] => keep-alive
            [Set-Cookie] => AWSALB=bIFafVQKPfTjE4f4iH+q4lSAN0M7SMO76nTN4yJYv2picmEEkuvtH0Thk2ITvQxypDbPRE8TVHEKr+MA5TrWXpRaBqCchtiYoMqTvU2AzjYlIHFU2LRQMpdhiknM; Expires=Tue, 11 Jun 2024 09:26:01 GMT; Path=/, AWSALBCORS=bIFafVQKPfTjE4f4iH+q4lSAN0M7SMO76nTN4yJYv2picmEEkuvtH0Thk2ITvQxypDbPRE8TVHEKr+MA5TrWXpRaBqCchtiYoMqTvU2AzjYlIHFU2LRQMpdhiknM; Expires=Tue, 11 Jun 2024 09:26:01 GMT; Path=/; SameSite=None; Secure, __cf_bm=YL.wMbUGKpw9VR_xs3_RQ_AtBWWETpnpEwP1nOAGJ3Q-1717493161-1.0.1.1-pIF44XhbjgvGYTj0O1b_AsjUx3EaomiQDz9CZxigMNeOWx989vMX9z6c4oW8rOBJYTtsVAWOwcdilHhf9myCDg; path=/; expires=Tue, 04-Jun-24 09:56:01 GMT; domain=.kucoin.com; HttpOnly; Secure, _cfuvid=Ok50HLvx8GrtWNY.GmcUegQZQ3PRc.u9mePTkYz4LJQ-1717493161391-0.0.1.1-604800000; path=/; domain=.kucoin.com; HttpOnly; Secure; SameSite=None
            [gw-ratelimit-remaining] => 3998
            [gw-ratelimit-limit] => 4000
            [gw-ratelimit-reset] => 29977
            [Strict-Transport-Security] => max-age=9800; includeSubDomains; preload
            [CF-Cache-Status] => DYNAMIC
            [Server] => cloudflare
            [CF-RAY] => 88e6e100287e5d8b-FRA
            [Content-Encoding] => br
        )

    [8] => ResponseBody:
    [9] => {"msg":"The order amount must exceed 0.1 USDT.","code":"400760"}
)
this is the complete response let me know if this helps

**Comment by carlosmiei** [comment]
@ShahwaizJerrax Why are you providing `amount = 0.4`? that's too low considering that `AVA/USDT` price is 0.7

**Comment by ShahwaizJerrax** [comment]
> @ShahwaizJerrax Why are you providing `amount = 0.4`? that's too low considering that `AVA/USDT` price is 0.7

Same case for 0.7 still not sure what causing the issue 
and even 1 ava


Array
(
    [0] => fetch Request:
    [1] => kucoin
    [2] => POST
    [3] => https://api.kucoin.com/api/v1/orders
    [4] => RequestHeaders:
    [5] => Array
        (
            [KC-API-KEY-VERSION] => 2
            [KC-API-KEY] => 656e3443fd5ee3000198bff6
            [KC-API-TIMESTAMP] => 1717497474068
            [Content-Type] => application/json
            [KC-API-PASSPHRASE] => vtm0u7A3nnx0HVIqyy8wIe1SbtYGwWltTGWdFjgk2Is=
            [KC-API-SIGN] => zFj4cOIqSzXj/2T/LzPArKlRkp+eeRhRLqR9flYUcJg=
            [KC-API-PARTNER-SIGN] => dHdqZyTmkoiugpb+27VNJR4hMZ/V1dEKz5QDT7mAMnE=
            [KC-API-PARTNER] => ccxt
            [KC-API-PARTNER-VERIFY] => true
        )

    [6] => RequestBody:
    [7] => {"clientOid":"0e35a023-1f70-464c-b0da-3376ef7f0263","side":"buy","symbol":"AVA-USDT","type":"market","size":"0.7"}
)
Array
(
    [0] => fetch Request:
    [1] => kucoin
    [2] => POST
    [3] => https://api.kucoin.com/api/v1/orders
    [4] => RequestHeaders:
    [5] => Array
        (
            [0] => KC-API-KEY-VERSION: 2
            [1] => KC-API-KEY: 656e3443fd5ee3000198bff6
            [2] => KC-API-TIMESTAMP: 1717497474068
            [3] => Content-Type: application/json
            [4] => KC-API-PASSPHRASE: vtm0u7A3nnx0HVIqyy8wIe1SbtYGwWltTGWdFjgk2Is=
            [5] => KC-API-SIGN: zFj4cOIqSzXj/2T/LzPArKlRkp+eeRhRLqR9flYUcJg=
            [6] => KC-API-PARTNER-SIGN: dHdqZyTmkoiugpb+27VNJR4hMZ/V1dEKz5QDT7mAMnE=
            [7] => KC-API-PARTNER: ccxt
            [8] => KC-API-PARTNER-VERIFY: true
        )

    [6] => RequestBody:
    [7] => {"clientOid":"0e35a023-1f70-464c-b0da-3376ef7f0263","side":"buy","symbol":"AVA-USDT","type":"market","size":"0.7"}
)
Array
(
    [0] => fetch Response:
    [1] => kucoin
    [2] => POST
    [3] => https://api.kucoin.com/api/v1/orders
    [4] => 200
    [5] => 
    [6] => ResponseHeaders:
    [7] => Array
        (
            [Date] => Tue, 04 Jun 2024 10:37:54 GMT
            [Content-Type] => application/json
            [Transfer-Encoding] => chunked
            [Connection] => keep-alive
            [Set-Cookie] => AWSALB=AiQ1iy6m3BtppQ+AL8Di4JxzJuiZw1t5QXFOc52DfeTdPzr9T6XiOwbgTlS+B58Hwkq7l0nVEeRaJRn/eWodUVDdnRzYeSXv8cwyajPwMndA3TdKIOxMdxVQYEJ3; Expires=Tue, 11 Jun 2024 10:37:54 GMT; Path=/, AWSALBCORS=AiQ1iy6m3BtppQ+AL8Di4JxzJuiZw1t5QXFOc52DfeTdPzr9T6XiOwbgTlS+B58Hwkq7l0nVEeRaJRn/eWodUVDdnRzYeSXv8cwyajPwMndA3TdKIOxMdxVQYEJ3; Expires=Tue, 11 Jun 2024 10:37:54 GMT; Path=/; SameSite=None; Secure, __cf_bm=g93Q2VQCX6gUzv.PklF5qUU5tqCOb1byw0L0QnQlQpc-1717497474-1.0.1.1-a0TkqmdU0h5SZPY9rH7bBKgIer7QAYCX7CbHF.qHdS1fi5_NjPMlEOBcdhnTZKnZu07Q5O0qX4DwwY.ZUqd_Mw; path=/; expires=Tue, 04-Jun-24 11:07:54 GMT; domain=.kucoin.com; HttpOnly; Secure, _cfuvid=XRpAXqHCrD4RXiI3az4xD.p1rqVFk96JZU5k7C864Ic-1717497474444-0.0.1.1-604800000; path=/; domain=.kucoin.com; HttpOnly; Secure; SameSite=None
            [gw-ratelimit-remaining] => 3998
            [gw-ratelimit-limit] => 4000
            [gw-ratelimit-reset] => 27537
            [Strict-Transport-Security] => max-age=9800; includeSubDomains; preload
            [CF-Cache-Status] => DYNAMIC
            [Server] => cloudflare
            [CF-RAY] => 88e74a4cfbaa1d84-FRA
            [Content-Encoding] => br
        )

    [8] => ResponseBody:
    [9] => {"msg":"The order amount must exceed 0.1 USDT.","code":"400760"}
)
{"success":true,"type":"error","message":"The order amount must exceed 0.1 USDT."}

**Comment by carlosmiei** [comment]
@ShahwaizJerrax That's very weird I can place the order

```
Array
(
    [0] => fetch Request:
    [1] => kucoin
    [2] => POST
    [3] => https://api.kucoin.com/api/v1/orders
    [6] => RequestBody:
    [7] => {"clientOid":"806207a6-9b78-4d49-9f7c-70910184759c","side":"buy","symbol":"AVA-USDT","type":"market","size":"0.4"}
)
Array
(
    [0] => fetch Response:
    [1] => kucoin
    [2] => POST
    [3] => https://api.kucoin.com/api/v1/orders
    [4] => 200
    [5] => ResponseHeaders:

    [7] => ResponseBody:
    [8] => {"code":"200000","data":{"orderId":"665efd296197040007aca449"}}
```

**Comment by ShahwaizJerrax** [comment]
> @ShahwaizJerrax That's very weird I can place the order
> 
> ```
> Array
> (
>     [0] => fetch Request:
>     [1] => kucoin
>     [2] => POST
>     [3] => https://api.kucoin.com/api/v1/orders
>     [6] => RequestBody:
>     [7] => {"clientOid":"806207a6-9b78-4d49-9f7c-70910184759c","side":"buy","symbol":"AVA-USDT","type":"market","size":"0.4"}
> )
> Array
> (
>     [0] => fetch Response:
>     [1] => kucoin
>     [2] => POST
>     [3] => https://api.kucoin.com/api/v1/orders
>     [4] => 200
>     [5] => ResponseHeaders:
> 
>     [7] => ResponseBody:
>     [8] => {"code":"200000","data":{"orderId":"665efd296197040007aca449"}}
> ```

@carlosmiei i get the status closed but with the error as well 
What do you think  ?

**Comment by ShahwaizJerrax** [comment]
> @ShahwaizJerrax That's very weird I can place the order
> 
> ```
> Array
> (
>     [0] => fetch Request:
>     [1] => kucoin
>     [2] => POST
>     [3] => https://api.kucoin.com/api/v1/orders
>     [6] => RequestBody:
>     [7] => {"clientOid":"806207a6-9b78-4d49-9f7c-70910184759c","side":"buy","symbol":"AVA-USDT","type":"market","size":"0.4"}
> )
> Array
> (
>     [0] => fetch Response:
>     [1] => kucoin
>     [2] => POST
>     [3] => https://api.kucoin.com/api/v1/orders
>     [4] => 200
>     [5] => ResponseHeaders:
> 
>     [7] => ResponseBody:
>     [8] => {"code":"200000","data":{"orderId":"665efd296197040007aca449"}}
> ```


{
    "orders": {
        "closed": [
            {
                "id": 154,
                "user_id": 1,
                "order_id": "6659ddb36197040007a53d7d",
                "symbol": "AVA\/USDT",
                "type": null,
                "side": null,
                "price": "0.72210000",
                "stopPrice": "0.00000000",
                "amount": "0.50000000",
                "cost": "0.36105000",
                "average": "0.72210000",
                "filled": "0.50000000",
                "remaining": "0.00000000",
                "status": "closed",
                "fee": "0.00036105",
                "provider": "kucoin",
                "created_at": "2024-05-31T14:24:51.000000Z",
                "updated_at": "2024-05-31T14:24:51.000000Z"
            },
            {
                "id": 153,
                "user_id": 1,
                "order_id": "6633f2490f84ab0007d31a70",
                "symbol": "AVA\/USDT",
                "type": null,
                "side": null,
                "price": "0.64640000",
                "stopPrice": "0.00000000",
                "amount": "0.20000000",
                "cost": "0.12928000",
                "average": "0.64640000",
                "filled": "0.20000000",
                "remaining": "0.00000000",
                "status": "closed",
                "fee": "0.00012928",
                "provider": "kucoin",
                "created_at": "2024-05-02T20:06:34.000000Z",
                "updated_at": "2024-05-02T20:06:34.000000Z"
            }
        ],
        "open": []
    }

**Comment by carlosmiei** [comment]
> > @ShahwaizJerrax That's very weird I can place the order
> > ```
> > Array
> > (
> >     [0] => fetch Request:
> >     [1] => kucoin
> >     [2] => POST
> >     [3] => https://api.kucoin.com/api/v1/orders
> >     [6] => RequestBody:
> >     [7] => {"clientOid":"806207a6-9b78-4d49-9f7c-70910184759c","side":"buy","symbol":"AVA-USDT","type":"market","size":"0.4"}
> > )
> > Array
> > (
> >     [0] => fetch Response:
> >     [1] => kucoin
> >     [2] => POST
> >     [3] => https://api.kucoin.com/api/v1/orders
> >     [4] => 200
> >     [5] => ResponseHeaders:
> > 
> >     [7] => ResponseBody:
> >     [8] => {"code":"200000","data":{"orderId":"665efd296197040007aca449"}}
> > ```
> 
> @carlosmiei i get the status closed but with the error as well What do you think ?

@ShahwaizJerrax what's the error? `"code":"200000","data":{"orderId":"665efd296197040007aca449"}}` this is not an error, it's a successful response

**Comment by ShahwaizJerrax** [comment]
@carlosmiei  that was not  a success response must have been a typing error but i am still facing the same issue this was working fine only perform the update 4.3.11 i hope we find a solution for this
