### ISSUE TITLE
Binance successfully authenticates with the first request, then authentication error comes with the second request

### ISSUE THREAD

**Issue by RaZorForce** [ccxt/ccxt#22712]
### Operating System

Windows 11

### Programming Languages

Python

### CCXT Version

4.3.36

### Description

- OS: Windows 11
- Programming Language version: Python 3.12.3
- CCXT version: 4.3.36
- Exchange: Binance
- Method: fetch_balance, create_limit_buy_order

binance.options['hasAlreadyAuthenticatedSuccessfully'] is initialized with False
When i try to fetch my account balance, after syncronising my local time with the server time,  it works... 
binance.options['hasAlreadyAuthenticatedSuccessfully'] is now True... So far so good...

In the following method, create_limit_buy_order() returns {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
of course i double checked my keys (OK) permissions (OK) IP restriction disabled (OK)
when debugging, i see an HTTPError exception.  then inside of self.handle_errors() i see the a workaround specifically for this error was implemented and since binance.options['hasAlreadyAuthenticatedSuccessfully'] is already True (when fetching balance), the if condition evaluates to True and raises a DDoSProtection.

After carefully reading the manual about DDoS Protection i can confirm that:
- my IP is not temporarily blocked (this my first ever created API - i have not violated any rate limites)
- i dont know if german region is blocked

i do not know how to circumvent this issue, and i see some comments in the code that speak specifically about this topic. so i though i shall get in touch with the developers. much appreciated.

### Code

```
import ccxt
binance = ccxt.binance{
    'apiKey': ds.key,
    'secret': ds.secret,
    'recvWindow': 10000,
    'enableRateLimit': True,
    'adjustForTimeDifference': True,
    })
    
 def sync_time():
    server_time = binance.fetch_time()
    local_time = int(time.time() * 1000)
    time_offset = server_time - local_time
    return int(time.time() * 1000 + time_offset)

# Fetch account balance
balance = binance.fetch_balance({'timestamp': sync_time()})

symbol = 'SOLUSDT'
amount = 1
price = 1
params = {'timeInForce': 'PostOnly'}

print('order submitted at', sync_time())
order=binance.create_limit_buy_order(symbol, amount, price,  params = {'timestamp': sync_time()})
```

**Comment by kroitor** [comment]
@RaZorForce why would you inject the `sync_time()` function?

This should work fine:

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
binance = ccxt.binance{
    'apiKey': ds.key,
    'secret': ds.secret,
    'adjustForTimeDifference': True,
    })
    
# Fetch account balance
balance = binance.fetch_balance()
print('Fetched balance #1')
balance = binance.fetch_balance()
print('Fetched balance #2')
balance = binance.fetch_balance()
print('Fetched balance #3...')

symbol = 'SOLUSDT'
amount = 1
price = 1
params = {'timeInForce': 'PO'}

exchange.verbose = True  # for debugging

order=binance.create_limit_buy_order(symbol, amount, price, params)
print('Order submitted')
print(order)
```

If that does not work, please, post your complete verbose output.

**Comment by kroitor** [comment]
Also, note that `adjustForTimeDifference` must be under the `'options'` key in the exchange instantiation config.

**Comment by RaZorForce** [comment]
> Could you create order directly?
i dont know what you mean by a direct order, could you elaborte

> Also, note that adjustForTimeDifference must be under the 'options' key in the exchange instantiation config.
Thank you for the hint, it does indeed work i no longer need the Sync_time() now. i was wondering why the adjustForTimeDifference  was not doing its job. silly me. 

> If that does not work, please, post your complete verbose output.
unfortunatley , the same error is here here is the verbose. appreciate the help

Fetched balance #1
Fetched balance #2
Fetched balance #3...

fetch Request: binance POST https://api.binance.com/api/v3/order RequestHeaders: {'X-MBX-APIKEY': '37DKkoeWf8teycgJxCopoFzgog9Y4UyZX7z3m1hXMiuXo6P2OjxMYqthnzJ8BaOg', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} RequestBody: timestamp=1717615554618&symbol=SOLUSDT&side=BUY&newClientOrderId=x-R4BD3S82e6991a420d28291d860629&newOrderRespType=FULL&type=LIMIT&quantity=1&price=1&timeInForce=PostOnly&recvWindow=10000&signature=68f34c8e6139d54bc414fd938e4067e50232b46e0e675a572d6f2790f156c25d

fetch Response: binance POST https://api.binance.com/api/v3/order 401 ResponseHeaders: {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '70', 'Connection': 'keep-alive', 'Date': 'Wed, 05 Jun 2024 19:25:55 GMT', 'Server': 'nginx', 'x-mbx-uuid': 'aea909a3-fd4c-4d20-9373-2057b7e39ca7', 'x-mbx-used-weight': '82', 'x-mbx-used-weight-1m': '82', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 2c29bb35ddacc1dc2616fe65bdf5122e.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'FRA56-P4', 'X-Amz-Cf-Id': '4KMZaBdC7hCy7m9m3tFQrGqrQeBSOX_U8eE8IstWb1Ka_l5LqOKvEQ=='} ResponseBody: {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}

Exception has occurred: DDoSProtection
binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

  File "C:\X\Workspaces\BigBangBot\3_algo_orders\placing_order.py", line 36, in <module>
    order=binance.create_limit_buy_order(symbol, amount, price,  params = params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ccxt.base.errors.DDoSProtection: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}

**Comment by kroitor** [comment]
@RaZorForce does your API key have the permission to place orders? Also, have you changed PostOnly to PO in the code as shown above?

**Comment by RaZorForce** [comment]
@kroitor i did make sure that  "Enable Spot & Margin Trading" option is checked in my API before i created the issue. nevertheless i wanted to double down and check once more after you asked me to, to my surprise it was not set! 
I changed it one more time and now placing limit orders is possible. 

I want to thank you for your effort and time. also regarding your hints in my simple code. i for sure learned something new. will try to be tripple carefull i the future. much appreciated.
