### ISSUE TITLE
Bitbay New Cryptocurrency: Ripple

### ISSUE THREAD

**Issue by Felipe-Mangueira** [ccxt/ccxt#2273]
- OS: Linux and Windows
- Programming Language version: Python 3
- CCXT version: 1.11.94
- Exchange: Bitbay
- Method: several

Hello guys!

Bitbay exchange just added another famous cryptocurrency, XRP. Could you deploy this crypto into the existing methods of Unified API?

If you want to seize the opportunity, just if you like, I would like to ask you for deploy the missing fetch_order method, as well.

Thanks and congrats for the amazing work with the library.

**Comment by kroitor** [comment]
The problem with adding XRP support is that those exchanges will not document withdrawal procedures and the parameter name for the XRP **tag/memo/paymentId** in their API documentation... They always announce new currencies but forget to update their docs.

**Comment by Felipe-Mangueira** [comment]
Thank you for your feedback, @kroitor. I didn't notice they have not update the API documentation was outdated, I've just started to trade XRP and I think it was available in the API. Sorry about that. I'll be checking if the docs are ok.

**Comment by Felipe-Mangueira** [comment]
Hi, @kroitor. Just reporting to you... the withdraw method for transfers of XRP from Bitbay is working fine.

Thanks.

**Comment by kroitor** [comment]
@Felipe-Mangueira thank you!
