### ISSUE TITLE
Poloniex Order Cache

### ISSUE THREAD

**Issue by tbrent** [ccxt/ccxt#2275]
- OS: macOS 10.13.1
- Programming Language version: Python 3.5.2
- CCXT version: 1.11.104
- Exchange: Poloniex
- Method: Probably `fetchOrder`

Hi again,

Thanks for your help previously with issues #1801 and #2061! 

I'm having order cache difficulties again. 

Logs
```
INFO:root:------
INFO:root:2018-03-15 21:23:51.988878
INFO:root:2018-03-15 21:23:51.988998:None
INFO:root:2018-03-15 21:23:52.072417:{'timestamp': 1521149015000, 'cost': 0.071325, 'amount': 2500.0, 'side': 'buy', 'status': 'open', 'remaining': 2500.0, 'symbol': 'XLM/BTC', 'fee': None, 'type': 'limit', 'price': 2.853e-05, 'trades': None, 'id': '67784017220', 'filled': 0.0, 'datetime': '2018-03-15T21:23:35.000Z', 'info': {'date': '2018-03-15 21:23:35', 'type': 'limit', 'margin': 0, 'amount': '2500.00000000', 'side': 'buy', 'status': 'open', 'orderNumber': '67784017220', 'total': '0.07132500', 'rate': '0.00002853', 'price': '0.00002853', 'startingAmount': '2500.00000000'}}
INFO:root:2018-03-15 21:23:52.210848:Binance balance
INFO:root:2018-03-15 21:23:52.846710:Poloniex balance
INFO:root:2.7755575615628914e-17|0.0
INFO:root:2018-03-15 21:23:52.973881:Binance orderbook
INFO:root:2018-03-15 21:23:53.038228:Poloniex orderbook
INFO:root:2018-03-15 21:23:53.038434:Ask: 0.9993 - []/1.0035: - 0.0
INFO:root:2018-03-15 21:23:53.038535:Bid: 1.0014 - 1.0032/1.0035: - open:2500.0
INFO:root:------
INFO:root:2018-03-15 21:23:53.039018
INFO:root:2018-03-15 21:23:53.039099:None
INFO:root:2018-03-15 21:23:53.116266:{'timestamp': 1521149015000, 'fee': None, 'type': 'limit', 'cost': 0.071325, 'amount': 2500.0, 'side': 'buy', 'status': 'closed', 'trades': None, 'remaining': 0.0, 'id': '67784017220', 'symbol': 'XLM/BTC', 'price': 2.853e-05, 'filled': 2500.0, 'datetime': '2018-03-15T21:23:35.000Z', 'info': {'date': '2018-03-15 21:23:35', 'type': 'limit', 'margin': 0, 'amount': '2500.00000000', 'side': 'buy', 'status': 'open', 'orderNumber': '67784017220', 'total': '0.07132500', 'rate': '0.00002853', 'price': '0.00002853', 'startingAmount': '2500.00000000'}}
INFO:root:2018-03-15 21:23:53.262088:Binance balance
INFO:root:2018-03-15 21:23:53.395391:Poloniex balance
INFO:root:0.0|0.0
INFO:root:2018-03-15 21:23:53.516148:Binance orderbook
INFO:root:2018-03-15 21:23:53.746400:Poloniex orderbook
INFO:root:2018-03-15 21:23:53.747429:Ask: 0.9993 - []/1.0035: - 0.0
INFO:root:2018-03-15 21:23:53.747575:Bid: 1.001 - 1.0032/1.0035: - closed:2500.0
INFO:root:Quantity 2500.0
INFO:root:Attempting Buy order for 2.852e-05 expecting a sell of 2.862e-05
INFO:root:{'timestamp': 1521149034176, 'cost': 0.0, 'amount': 2500.0, 'side': 'buy', 'status': 'open', 'remaining': 2500.0, 'symbol': 'XLM/BTC', 'fee': None, 'type': 'limit', 'price': 2.852e-05, 'trades': [], 'id': '67784046191', 'filled': 0.0, 'datetime': '2018-03-15T21:23:54.176Z', 'info': {'timestamp': 1521149034176, 'type': 'limit', 'amount': 2500.0, 'status': 'open', 'side': 'buy', 'price': 2.852e-05, 'resultingTrades': [], 'orderNumber': '67784046191'}}
INFO:root:------
```

You can see order `67784046191` goes from `'open'` to `'closed'`, and also thinks it has been filled. This happens around 21:23:53. Looking in Poloniex, I can see that the time the order actually fills is later, at 21:24:44. 

The `INFO:root:0.0|0.0` log is a display of the difference in my BTC and XLM balances in each frame. I have been using this in order to know which trades actually execute and which do not. The issue here is that although the program correctly understands no trade has taken place, the order remains on the orderbook and eventually executes about a minute later, and the program has lost track of it at that point. 

I believe I am following the instructions from [here](https://github.com/ccxt/ccxt/wiki/Manual#orders-cache) but it's always possible I am not. Note no `cancelOrder` calls have been made in the section of the log I show here where the order cache falls out of sync. 

Poloniex was experiencing rampant timeouts (even manually cancelling orders through the UI would fail) during the period I was running this code, but none occurred during the log window I have here. I do wonder if this is a cache issue or the result of degraded service from Poloniex.

**Comment by tbrent** [comment]
Feel free to close this. I can re-open when I have something more actionable. Not sure there's anything to do with this level of information.

**Comment by mkutny** [comment]
Looks like you confused order ids, looks like what you say doesn't match the log.

> You can see order 67784046191 goes from 'open' to 'closed', and also thinks it has been filled.

The order with this id is reported as 'open':
```
INFO:root:{'timestamp': 1521149034176, 'cost': 0.0, 'amount': 2500.0, 'side': 'buy', 'status': 'open', 'remaining': 2500.0, 'symbol': 'XLM/BTC', 'fee': None, 'type': 'limit', 'price': 2.852e-05, 'trades': [], 'id': '67784046191', 'filled': 0.0, 'datetime': '2018-03-15T21:23:54.176Z', 'info': {'timestamp': 1521149034176, 'type': 'limit', 'amount': 2500.0, 'status': 'open', 'side': 'buy', 'price': 2.852e-05, 'resultingTrades': [], 'orderNumber': '67784046191'}}
```

But what's got closed is order 67784017220:

```
INFO:root:2018-03-15 21:23:53.116266:{'timestamp': 1521149015000, 'fee': None, 'type': 'limit', 'cost': 0.071325, 'amount': 2500.0, 'side': 'buy', 'status': 'closed', 'trades': None, 'remaining': 0.0, 'id': '67784017220', 'symbol': 'XLM/BTC', 'price': 2.853e-05, 'filled': 2500.0, 'datetime': '2018-03-15T21:23:35.000Z', 'info': {'date': '2018-03-15 21:23:35', 'type': 'limit', 'margin': 0, 'amount': '2500.00000000', 'side': 'buy', 'status': 'open', 'orderNumber': '67784017220', 'total': '0.07132500', 'rate': '0.00002853', 'price': '0.00002853', 'startingAmount': '2500.00000000'}}
```

- Which order id you checked through Poloniex UI?
- What method did you use to check for order status? Is it `fetchOrder`? You said "probably" that's why I'm asking )
- I see that the sequence you use is `fetchOrder`, `fetchBalance`, `fetchOrderBook`. Do you use a rateLimit? I see all three requests finish on the same second, could it be `fetchBalance` happened to reach the exchange before `fetchOrder` did?

**Comment by tbrent** [comment]
Ah yes, I did confuse order ids. I meant to refer to order id `67784017220`. 

The order I checked through the Poloniex UI was order id `67784017220`. 

I used `fetchOrder` to check for order status. 

All calls are synchronous and blocking.

**Comment by mkutny** [comment]
Ok, the only place I see in the code when an order gets 'closed' status is when it's not found in the cache:
https://github.com/ccxt/ccxt/blob/075f711675b9404347cdc64525daeddde318cfdd/js/poloniex.js#L575

Two possible reasons I can guess:
- Poloniex returned empty result (their bug)
- You fetched an order in another market somewhere in between the calls and this invalidated the cache. Did you trade on several markets when you encountered this?

**Comment by tbrent** [comment]
I actually think it's very plausible Poloniex returned an empty result. I'm
not trading on multiple markets on Poloniex.

The day this occurred there were also rampant RequestTimeouts. Through the
UI you couldn't even cancel trades.

I think you can close this issue. It's on Poloniex's side. The same code
has been running successfully for weeks, and it's running fine today, so I
think Poloniex just had a bad day.

Thanks!
