### ISSUE TITLE
[Typescript] Not all types are being exported 

### ISSUE THREAD

**Issue by ivnnv** [ccxt/ccxt#22766]
### Operating System

All

### Programming Languages

JavaScript

### CCXT Version

4.3.42

### Description

Hi,

There are types defined in [src/base/types](https://github.com/ccxt/ccxt/blob/master/ts/src/base/types.ts) like `OpenInterest` that are not being exported in [ts/ccxt](https://github.com/ccxt/ccxt/blob/master/ts/ccxt.ts#L36) while some others like `FundingRateHistory` are.

Is this intentional? if not, may I open a PR specifying every type that is not being currently exported set to be?

These seems to be all missing right now
```BalanceAccount,
    Account,
    BorrowInterest,
    LeverageTier,
    LedgerEntry,
    DepositWithdrawFeeNetwork,
    DepositWithdrawFee,
    TransferEntry,
    CrossBorrowRate,
    IsolatedBorrowRate,
    FundingRate,
    FundingRates,
    OpenInterest,
    OrderRequest,
    CancellationRequest,
    FundingHistory,
    MarginModification,
    LastPrice,
    LastPrices,
    Currencies,
    TradingFees,
    MarginModes,
    IsolatedBorrowRates,
    CrossBorrowRates,
    TransferEntries,
    LeverageTiers,
    OHLCVC
```
    
or even better, why this is this file importing only the types that are being needed inside to define other types and then
`export * 'from src/base/types'` at the end of the file?

**Comment by carlosmiei** [comment]
Hello @ivnnv, no this is not "intentional", the exported types are out of sync, but we will try to update it asap.

**Comment by ivnnv** [comment]
@carlosmiei thank you for approaching this so fast! 🤝

**Comment by carlosmiei** [comment]
@ivnnv can you please update your ccxt version and try again? All types should be there now.

Thanks once again.

**Comment by ivnnv** [comment]
@carlosmiei yeah just upgraded to `4.3.43` and can import `OpenInterest` and others 🙌🏽 . Thx!
