### ISSUE TITLE
C# WatchOrders Hyperliquid Subscriptions

### ISSUE THREAD

**Issue by JakubMartinovicHusar** [ccxt/ccxt#22779]
### Operating System

Ubuntu 22.04

### CCXT Version

4.3.42

### Description
 
None of following code results in order status being received for Hyperliquid. I am using C#. I am providing walletAddress to exchange in parameters of exchange object. Has this function been tested? Does it work properly? May there be something that I am missing?

### Code

```
  var ordersTask = this.exchange.WatchOrders();
   ordersTask.Wait();
   Logger.Debug($"Orders received: {ordersTask.Result.Count()}.");

   var ordersTask = this.exchange.WatchOrders("SOL/USDC:USDC");
   ordersTask.Wait();
   Logger.Debug($"Orders received: {ordersTask.Result.Count()}.");


```

**Comment by JakubMartinovicHusar** [comment]
I ran the same code for binance futures and it worked just fine.

**Comment by carlosmiei** [comment]
Hello @JakubMartinovicHusar, we will take a look and revert

**Comment by carlosmiei** [comment]
@JakubMartinovicHusar I just tested and it seems to be working

```
 npm run cli.cs -- hyperliquid WatchOrders "SOL/USDC:USDC" --verbose --sandbox

> ccxt@4.3.42 cli.cs
> dotnet run --project "./cs/cli/cli.csproj" hyperliquid WatchOrders SOL/USDC:USDC --verbose --sandbox

[
  "SOL/USDC:USDC"
]
WebSocket connected to wss://api.hyperliquid-testnet.xyz/ws
Sending message: {"method":"subscribe","subscription":{"type":"orderUpdates","user":"0x3B3741c0EFf9C6b556Ec813e70589161F416662A"}}
On message: {"channel":"subscriptionResponse","data":{"method":"subscribe","subscription":{"type":"orderUpdates","user":"0x3b3741c0eff9c6b556ec813e70589161f416662a"}}}
On message: {"channel":"orderUpdates","data":[{"order":{"coin":"SOL","side":"B","limitPx":"183.75","sz":"0.1","oid":9893803368,"timestamp":1718099116378,"origSz":"0.1"},"status":"open","statusTimestamp":1718099116378},{"order":{"coin":"SOL","side":"B","limitPx":"183.75","sz":"0.0","oid":9893803368,"timestamp":1718099116378,"origSz":"0.1"},"status":"filled","statusTimestamp":1718099116378}]}
[
  {
    "id": "9893803368",
    "clientOrderId": null,
    "timestamp": 1718099116378,
    "datetime": "2024-06-11T09:45:16.378Z",
    "lastTradeTimestamp": null,
    "symbol": "SOL/USDC:USDC",
    "type": null,
    "side": "buy",
    "price": 183.75,
    "cost": null,
    "average": null,
    "amount": null,
    "filled": null,
    "triggerPrice": null,
    "stopLossPrice": null,
    "takeProfitPrice": null,
    "remaining": 0.0,
    "status": "closed",
    "reduceOnly": false,
    "postOnly": false,
    "fee": {
      "rate": null,
      "cost": null
    },
    "trades": [],
    "info": {
      "order": {
        "coin": "SOL",
        "side": "B",
        "limitPx": "183.75",
        "sz": "0.0",
        "oid": 9893803368,
        "timestamp": 1718099116378,
        "origSz": "0.1"
      },
      "status": "filled",
      "statusTimestamp": 1718099116378
    }
  }
]
```

@JakubMartinovicHusar If you enable the verbose mode can you check which wallet is being used to subscribe?

**Comment by JakubMartinovicHusar** [comment]
@carlosmiei thank you for answer. 

I have investigated it further as you suggested and it indeed works. I had to add explicit user parameter. I was using only walletAddress parameter when instantiating exchange which is eventual API wallet key. You need to specify user - wallet address to watch orders. 
var ordersTask = this.exchange.WatchOrders(
                        parameters: new Dictionary<string, object>(){{"user", "0x...4"}}
                    );

@carlosmiei thank your for your help!

**Comment by carlosmiei** [comment]
@JakubMartinovicHusar Glad it worked now, but just to make it clear you just need to specify `user` if it's different from the `walletAddress`. Alternatively, you can set it in the options so you don't need to provide it manually every single time, example:

```C#
exchange.options["user"] = "new address"; // will override `walletAddress` whenever it's needed
```

**Comment by JakubMartinovicHusar** [comment]
Even better! Thank you @carlosmiei!

**Comment by carlosmiei** [comment]
@JakubMartinovicHusar No problem! Will close this issue then, feel free to re-open it if needed. 
Thanks!
