### ISSUE TITLE
[Bug][fetchTransfers] Binance - fetchTransfers seems to return only transfers from the Spot account to the Linear (Margin) account but not the other way around

### ISSUE THREAD

**Issue by kazazor** [ccxt/ccxt#22783]
### Operating System

maxOS

### Programming Languages

JavaScript

### CCXT Version

4.3.41

### Description

When using the fetchTransfers API with`binanceusdm` I only get results for internal transfers from the `spot` account to the `linear` margin account, but not the other way around.

I thought maybe it's something with the `since` value, but the missing transfer is actually in between transfers that are being returned. Here is what I get in return:
```js
[
  {
    exchangeId: "binanceusdm",
    marginAccountTxType: "deposit",
    info: {
      timestamp: "1717828412000",
      asset: "USDT",
      amount: "2000",
      type: "MAIN_UMFUTURE",
      status: "CONFIRMED",
      tranId: "177270306444",
    },
    id: "177270306444",
    timestamp: 1717828412000,
    datetime: "2024-06-08T06:33:32.000Z",
    currency: "USDT",
    amount: 2000,
    fromAccount: "spot",
    toAccount: "linear",
    status: "ok",
  },
  {
    exchangeId: "binanceusdm",
    marginAccountTxType: "deposit",
    info: {
      timestamp: "1714803706000",
      asset: "USDT",
      amount: "100",
      type: "MAIN_UMFUTURE",
      status: "CONFIRMED",
      tranId: "171658412739",
    },
    id: "171658412739",
    timestamp: 1714803706000,
    datetime: "2024-05-04T06:21:46.000Z",
    currency: "USDT",
    amount: 100,
    fromAccount: "spot",
    toAccount: "linear",
    status: "ok",
  },
  {
    exchangeId: "binanceusdm",
    marginAccountTxType: "deposit",
    info: {
      timestamp: "1710489166000",
      asset: "USDT",
      amount: "5000",
      type: "MAIN_UMFUTURE",
      status: "CONFIRMED",
      tranId: "160741026002",
    },
    id: "160741026002",
    timestamp: 1710489166000,
    datetime: "2024-03-15T07:52:46.000Z",
    currency: "USDT",
    amount: 5000,
    fromAccount: "spot",
    toAccount: "linear",
    status: "ok",
  },
  {
    exchangeId: "binanceusdm",
    marginAccountTxType: "deposit",
    info: {
      timestamp: "1708848790000",
      asset: "USDT",
      amount: "2518.8677",
      type: "MAIN_UMFUTURE",
      status: "CONFIRMED",
      tranId: "156094028321",
    },
    id: "156094028321",
    timestamp: 1708848790000,
    datetime: "2024-02-25T08:13:10.000Z",
    currency: "USDT",
    amount: 2518.8677,
    fromAccount: "spot",
    toAccount: "linear",
    status: "ok",
  },
]
```

And the missing transfer is from the `linear` account to the `spot` account on April 30th for 3,000 USDT. So basically, it was supposed to be the third item in this array.
I didn't see any setting saying that I'm only fetching one direction of the transfers..

### Code

```js
const exchangeClass = ccxt["binanceusdm"]
this.exchangeInstance = new exchangeClass({
      apiKey,
      secret,
      password,
      timeout: 30000
    })

...

const transfers = await this.exchangeInstance.fetchTransfers("USDT", Date.UTC(2024, 1, 1), undefined)
```

**Comment by sc0Vu** [comment]
Hi @kazazor, the default `fromAccount` is `spot, could you set `fromAccount` eg. `
Operating System
maxOS

Programming Languages
JavaScript

CCXT Version
4.3.41

Description
When using the fetchTransfers API withbinanceusdm I only get results for internal transfers from the spot account to the linear margin account, but not the other way around.

I thought maybe it's something with the since value, but the missing transfer is actually in between transfers that are being returned. Here is what I get in return:

[
  {
    exchangeId: "binanceusdm",
    marginAccountTxType: "deposit",
    info: {
      timestamp: "1717828412000",
      asset: "USDT",
      amount: "2000",
      type: "MAIN_UMFUTURE",
      status: "CONFIRMED",
      tranId: "177270306444",
    },
    id: "177270306444",
    timestamp: 1717828412000,
    datetime: "2024-06-08T06:33:32.000Z",
    currency: "USDT",
    amount: 2000,
    fromAccount: "spot",
    toAccount: "linear",
    status: "ok",
  },
  {
    exchangeId: "binanceusdm",
    marginAccountTxType: "deposit",
    info: {
      timestamp: "1714803706000",
      asset: "USDT",
      amount: "100",
      type: "MAIN_UMFUTURE",
      status: "CONFIRMED",
      tranId: "171658412739",
    },
    id: "171658412739",
    timestamp: 1714803706000,
    datetime: "2024-05-04T06:21:46.000Z",
    currency: "USDT",
    amount: 100,
    fromAccount: "spot",
    toAccount: "linear",
    status: "ok",
  },
  {
    exchangeId: "binanceusdm",
    marginAccountTxType: "deposit",
    info: {
      timestamp: "1710489166000",
      asset: "USDT",
      amount: "5000",
      type: "MAIN_UMFUTURE",
      status: "CONFIRMED",
      tranId: "160741026002",
    },
    id: "160741026002",
    timestamp: 1710489166000,
    datetime: "2024-03-15T07:52:46.000Z",
    currency: "USDT",
    amount: 5000,
    fromAccount: "spot",
    toAccount: "linear",
    status: "ok",
  },
  {
    exchangeId: "binanceusdm",
    marginAccountTxType: "deposit",
    info: {
      timestamp: "1708848790000",
      asset: "USDT",
      amount: "2518.8677",
      type: "MAIN_UMFUTURE",
      status: "CONFIRMED",
      tranId: "156094028321",
    },
    id: "156094028321",
    timestamp: 1708848790000,
    datetime: "2024-02-25T08:13:10.000Z",
    currency: "USDT",
    amount: 2518.8677,
    fromAccount: "spot",
    toAccount: "linear",
    status: "ok",
  },
]
And the missing transfer is from the linear account to the spot account on April 30th for 3,000 USDT. So basically, it was supposed to be the third item in this array.
I didn't see any setting saying that I'm only fetching one direction of the transfers..

Code
const exchangeClass = ccxt["binanceusdm"]
this.exchangeInstance = new exchangeClass({
      apiKey,
      secret,
      password,
      timeout: 30000
    })

...

const transfers = await this.exchangeInstance.fetchTransfers("USDT", Date.UTC(2024, 1, 1), 10, {
  fromAccount: 'future'
})
`?

**Comment by kazazor** [comment]
Thanks @sc0Vu !
I was actually looking for something like that in the documentation and couldn't find it, can you share a link to this option?

And thank you very much for your help :)

**Comment by kazazor** [comment]
@sc0Vu Looking at the Binance documentation, I can't see the option you mentioned: https://docs.ccxt.com/#/exchanges/binance?id=fetchtransfers

And also in the account types I don't see the `linear` option being returned from the Binance API: https://docs.ccxt.com/#/?id=account-types

**Comment by kazazor** [comment]
I just tested it and it works :)
But as I mentioned maybe the documentation needs to change (or maybe I missed it there)
