### ISSUE TITLE
kraken - Possible wrong fetchTickers method URL

### ISSUE THREAD

**Issue by viacheslavvbogdanov** [ccxt/ccxt#2278]
Exception message:
kraken GET https://kraken.zendesk.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-

- OS: fedora 23
- Programming Language version: node
- CCXT version: ccxt@1.11.104 
- Exchange: kraken
- Method: fetchTickers

**Comment by kroitor** [comment]
This is not related to fetchTickers (). This URL is called from loadMarkets (). And loadMarkets gets called from fetchTickers as well. 

This URL is used to load Kraken limits for the order sizes on/in `loadMarkets()`. If it fails, we recommend to go through the troubleshooting section: https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting. Namely, try a different source address, try a proxy, try bypassing the cloudflare protection, all that... That should help you understand their behaviour. If it does not help, then we will need to see the verbose output: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Feel free to reopen it if needed or just ask questions, if any. Thx!
