### ISSUE TITLE
Binance Timestamp for this request is outside of the recvWindow -- again [despite small enough drift]

### ISSUE THREAD

**Issue by nmiculinic** [ccxt/ccxt#2281]
I've already seen multiple posts about this (and I cannot find one right now for some reason), but it's happening to me again, despite drift being small enough:

  | Field | Total | Mean | Minimum | Maximum | Std. deviation | Variance | Sum | Cardinality
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | drift | 436 | 0.82 | 0.11 | 2.27 | 0.5 | 0.25 | 357.74 | 205

And if I put `exchange.options['recvWindow'] = 1000 * 1000  # Seriously binance!!!` I still get the same error:

```
ccxt.base.errors.InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
```

**Comment by mkutny** [comment]
1) What version do you use?
2) Do you enable `adjustForTimeDifference`?
3) Does it happen from time to time? How often? Are you blocked right now?
4) How do you calculate the drift? I mean, what's the procedure for probes? How often, at what moments?
5) `1000 * 1000` is just 16 minutes. If you happened to adjust your clock due to DST change you need `1000 * 3600` )

**Comment by nmiculinic** [comment]
1.) ccxt==1.11.83
2.) Not yet, will do and try again
3). pretty often; and yes I'm blocked right now. It started happening a lot more frequent recently
4.) Upon failure on private Binacne API:
```python
                    our_time = arrow.Arrow.utcfromtimestamp(
                        (await
                         self.exchange.public_get_time())['serverTime'] / 1000
                    )
                    their_time = arrow.Arrow.utcfromtimestamp(
                        self.exchange.milliseconds() / 1000
                    )
                    diff = abs(our_time - their_time)
                    extra['drift'] = diff.total_seconds()

```
5.) hmm isn't everything on UTC? That way, DST shouldn't make an impact.

**Comment by mkutny** [comment]
> hmm isn't everything on UTC?

Nope ) I also see from the the snippet (thanks you provided it) that you probably don't fully grasp how it supposed to work.

```
our_time = arrow.Arrow.utcfromtimestamp(
                        (await
                         self.exchange.public_get_time())['serverTime'] / 1000
                    )
```

The line above is actually about **their** (binance) time, not our (local) time.

And the following is our (local) time, not binance time.
```
                    their_time = arrow.Arrow.utcfromtimestamp(
                        self.exchange.milliseconds() / 1000
                    )
```

Your difference sometimes gets more than 2 secs, that's pretty much, indeed.

**Comment by nmiculinic** [comment]
Yes you're right, somebody mistook the names anyhow.... does ccxt uses UTC time or local time?

**Comment by kroitor** [comment]
Basically, this issue should is usually solved by recipes from one of these two posts:

- https://github.com/ccxt/ccxt/issues/850
- https://github.com/ccxt/ccxt/issues/936

I'd add this to the top of the list of questions from mkutny:
0. Do you synchronize system clock every 10 minutes with a reliable time server? It may seem that you do, but this is worth checking anyway. Syncing every 24 hours won't help, unfortunately.

Let us know if methods proposed above do not solve the issue for you. Thx!

**Comment by mkutny** [comment]
> Yes you're right, somebody mistook the names anyhow...

@nmiculinic , do you mean it's not your code? Did you copypasted it from somewhere?
