### ISSUE TITLE
Hyperliquid: withdraw function is outdated and doesn't use the new withdraw3 schema

### ISSUE THREAD

**Issue by DumplingLife** [ccxt/ccxt#22815]
### Operating System

Ubuntu

### CCXT Version

4.3.45

### Description

Hyperliquid recently changed their withdraw API endpoint, see here: https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/exchange-endpoint#initiate-a-withdrawal-request
CCXT's hyperliquid.withdraw function has not updated to reflect this (can be seen from a quick inspection of withdraw's source code)

To reproduce the issue, call withdraw.

### Code

```
hyperliquid = ccxt.hyperliquid({
    "walletAddress": "...",
    "privateKey": "...",
})
hyperliquid.withdraw("USDC", 10, "...")

```

**Comment by sc0Vu** [comment]
Hi @DumplingLife, thanks. I think we missed transfer and withdraw based on their sdk implementation. We'll fix this asap.

**Comment by carlosmiei** [comment]
@DumplingLife can you please update your ccxt version to the latest (4.3.46) and try again? should be working now

**Comment by DumplingLife** [comment]
Hmm now the withdrawal goes through, but I get this error:
ccxt.base.errors.NotSupported: hyperliquid parseTransaction() is not supported yet

Code:
```
import ccxt

hyperliquid = ccxt.hyperliquid({
    "walletAddress": "0x...",
    "privateKey": private_key,
})

hyperliquid.withdraw("USDC", 10, "0x...")
```

**Comment by carlosmiei** [comment]
@DumplingLife sorry my bad 🤦 , going to fix it asap.

**Comment by carlosmiei** [comment]
@DumplingLife can you please update your ccxt version to the latest and try again? should be working now 4.3.47
