### ISSUE TITLE
`handle_errors()` causes Critical Error while using a wrong types for `$http_status_text` and `$result` params

### ISSUE THREAD

**Issue by AnakinA1** [ccxt/ccxt#22844]
### Operating System

Any

### Programming Languages

PHP

### CCXT Version

4.2+

### Description

In `php/Exchange.php` file in `fetch()` method you have a big mistake of using nulls for params `$http_status_text` and `$result ? $result : null` during the call of `$this->handle_errors()`. Because this method for all exchanges expects to have `string` as a type for this 2 params. And sometimes they can be null which causes a php Critical Error.

### Code

Currently:

```
$skip_further_error_handling = $this->handle_errors($http_status_code, $http_status_text, $url, $method, $response_headers, $result ? $result : null, $json_response, $headers, $body);  
```

Should be:

```
$skip_further_error_handling = $this->handle_errors($http_status_code, (string) $http_status_text, $url, $method, $response_headers, $result ? $result : '', $json_response, $headers, $body);  
```

Or you can use `''` directly for `$http_status_text` instead of using `null`:

```
$http_status_text = count($parts) === 3 ? $parts[2] : '';
```

**Comment by sc0Vu** [comment]
Hi @AnakinA1, I think we can change the default value to empty string ''. Also, could I ask how to get the null situation? The api supposed to send correct response (`HTTP/1.1 STATUS STATUSTEXT`).

**Comment by AnakinA1** [comment]
Hi, for example using `bitget` library it's very often situation when I have `null` in $http_status_text
