### ISSUE TITLE
New Exchange: Bitcoin Trade (bitcointrade.com.br)

### ISSUE THREAD

**Issue by rfcarvalho** [ccxt/ccxt#2284]
Hello, @kroitor!

I've been using your library, especifically the Mercado Bitcoin class for the past three weeks. So, I would like to try another brazilian exchange not implemented yet, Bitcoin Trade. Could you add its available methods into your amazing library, when it's possible?

Below, it's the API docs and the main site:
https://www.bitcointrade.com.br/
https://apidocs.bitcointrade.com.br/

Thanks,
Regards.

**Comment by belsebob90** [comment]
You can try im picking upp the money now

Den fre 16 mars 2018 19:08rfcarvalho <notifications@github.com> skrev:

**Comment by oxydron** [comment]
Any updates on implementing [bitcointrade.com.br](https://www.bitcointrade.com.br)?

**Comment by rodoufu** [comment]
May be related to https://github.com/ccxt/ccxt/pull/4430

**Comment by danielcerdeira** [comment]
Hello guys! Any news on implementing bitcointrade API?
Thanks!

**Comment by ttodua** [comment]
exchange was renamed to ripio, so closed in favor of: https://github.com/ccxt/ccxt/pull/17488
