### ISSUE TITLE
Bybit: cancelAllOrdersAfter support by new DCP api

### ISSUE THREAD

**Issue by mjwvb** [ccxt/ccxt#22869]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

Bybit API has a new feature called "Disconnect Protect", enabled for all product types since 2024-06-18:
https://bybit-exchange.github.io/docs/v5/order/dcp

### Describe the solution you'd like

Would be nice if CCXT can support this new feature by cancelAllOrdersAfter()

**Comment by carlosmiei** [comment]
Hello @mjwvb,
thanks a lot for reporting it, we will try to add it shortly.
