### ISSUE TITLE
BigOne request show 401 Unauthorized

### ISSUE THREAD

**Issue by flowerDAI** [ccxt/ccxt#22863]
### Operating System

windows

### CCXT Version

4.3.48

### Description

I request private api , show 401 or 403；
![image](https://github.com/ccxt/ccxt/assets/25717606/9486ff89-2590-4c63-a618-1be047f890ad)

### Code

```
var bigoneExchange = new ccxt.bigone(new Dictionary<string, object>()
{
    {"apiKey","XXXXX"},
    {"secret","XXXXX"}
});

//var marks = await bigoneExchange.FetchMarkets();
await bigoneExchange.loadMarkets();

var bals = await bigoneExchange.FetchBalance();  //  Unauthorized

var accs = await bigoneExchange.contractPrivateGetAccounts();   // Forbidden

```

**Comment by flowerDAI** [comment]
use C#

**Comment by flowerDAI** [comment]
maybe is jwt of nonce parameter error,  less 8 hours

**Comment by carlosmiei** [comment]
@flowerDAI can you please update your ccxt version and try again? should be working now
