### ISSUE TITLE
Binance Order Closed Date

### ISSUE THREAD

**Issue by polibou** [ccxt/ccxt#2286]
- Programming Language version: PHP
- Exchange: Binance
- CCXT Version: 1.10.712

Hi All, 

Seems like I am missing something fairly obvious.  I can't seem to find the closed date of a trade or order on binance.

I've tried both the fetchMyTrades and fetchClosedOrders but all of the date information returned seems to be the open date.  Is this info available?

**Comment by kroitor** [comment]
Hi! For Binance this is not possible (afaik), according to their current API docs

https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

... they will always report just one timestamp. Very few exchanges will actually report enough info (which is usually available in the `info` field and in the unified fields). We will add support for order closing time to the unified order structure soon. But, I'm afraid, the closing time will still be undefined anyways.

Hope it answers your question. Let us know if not. Thx!

**Comment by polibou** [comment]
Thank you for the detailed answer!
