### ISSUE TITLE
What is the best way to re-connect

### ISSUE THREAD

**Issue by duggar** [ccxt/ccxt#22871]
### Operating System

linux

### Programming Languages

Python

### CCXT Version

All

### Description

When I have any error in a webscoket stream or any forever loop what is the best practice to re-connect with exchange, for eg a network error.
Right Now I am doing this: closing in case of exception and again instantiation ccxt.okx for eg.

### Code

```
      async def stream_balance_update(self, symbol,cb):
        while True:
            bl = None
            try:
                bal = await self.exch.watch_balance(params={"extraParams": '{"updateInterval": 0}'})
                bl = {}
                for d in list(bal["free"].keys()):
                    d = Balance().load(d, bal)
                    bl[d.asset] = d
                # logger.info(bl)
                await cb(bl) if cb else None
            except Exception as e:
                logger.info(type(e).__name__, e)
                logger.info('stream_account_update:', bal)
                logger.info(traceback.format_exc())
                await self.exch.close()
                self.connect()

    def connect(self):
        if self.exchange_name == 'okx':
            self.exch = ccxt.okx({
                'enableRateLimit': True,
                'logger': None,
                'apiKey': self.api_key,
                'secret': self.secret,
                "password": self.passphrase,
            })
        else:
            raise Exception('Exchange not supported')


```

**Comment by carlosmiei** [comment]
Hello @duggar, 

You don't need to call `self.connect` here because you don't need to recreate the instance, `self.exc.close()` should be enough to close all pending WS connections, and then the next iteration of the loop will call `watchX` again and reconnect automatically.

**Comment by duggar** [comment]
> Hello @duggar, 
> 
> You don't need to call `self.connect` here because you don't need to recreate the instance, `self.exc.close()` should be enough to close all pending WS connections, and then the next iteration of the loop will call `watchX` again and reconnect automatically.  

Thanks that is supper helpful
