### ISSUE TITLE
createMarketBuyOrder precision error

### ISSUE THREAD

**Issue by viacheslavvbogdanov** [ccxt/ccxt#2287]
I create order with amount 0.043 but at order amount and filled changed to                   
amount:    0.043000000000000003,
filled:    0.043000000000000003,
and my order is rejected orderRejectReason: "orderExceedsLimit"
(in market.limits.amount.min: 0.001, 
looks like JS float precision error?

- OS:fedora 23
- Programming Language version:node v8.10.0
- CCXT version:ccxt@1.11.116
- Exchange:hitbtc/hitbtc2 may be other too
- Method:createMarketBuyOrder

Order placed {        id:   "1521279518566",
                    info: {           orderId: "N/A",
                                latestOrderId: "N/A",
                                  orderStatus: "rejected",
                                       symbol: "ETHUSD",
                                         side: "buy",
                                     quantity:  43,
                                         type: "market",
                                  timeInForce: "FOK",
                                 lastQuantity:  0,
                                    lastPrice: "",
                               leavesQuantity:  0,
                                  cumQuantity:  0,
                                 averagePrice: "0",
                                      created:  1521279519557,
                               execReportType: "rejected",
                            orderRejectReason: "orderExceedsLimit" },
               timestamp:    undefined,
                datetime:    undefined,
                  status:   "rejected",
                  symbol:   "ETH/USDT",
                    type:   "market",
                    side:   "buy",
                   price:    undefined,
                    cost:    0,
                  amount:    0.043000000000000003,
                  filled:    0.043000000000000003,
               remaining:    0,
                     fee:    undefined                                }

**Comment by kroitor** [comment]
Is it HitBTC v1 or v2? Can you post verbose output according to these instructions? 
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by viacheslavvbogdanov** [comment]
v1 and v2 both. also I've tried to send 0.043 as string. no luck
i found some notes about float precision https://stackoverflow.com/questions/11695618/dealing-with-float-precision-in-javascript 
ok - will post verbose

**Comment by kroitor** [comment]
@viacheslavvbogdanov let's stick to one of them first, i propose to debug hitbtc v2 first.

**Comment by viacheslavvbogdanov** [comment]
my code: await exchange.createMarketBuyOrder( pair, amount)
handleRestResponse:
 hitbtc POST http://api.hitbtc.com/api/1/trading/new_order?nonce=1521280182345&apikey=8b507c75999633f70833920b7b410b83 200 OK 
Response:
 { Server: 'nginx',
  Date: 'Sat, 17 Mar 2018 09:49:43 GMT',
  'Content-Type': 'application/json; charset=utf-8',
  'Content-Length': '399',
  Connection: 'close' } 
 {"ExecutionReport":{"orderId":"N/A","latestOrderId":"N/A","clientOrderId":"1521280182345","orderStatus":"rejected","userId":"user_2370534","symbol":"ETHUSD","side":"buy","quantity":43,"type":"market","timeInForce":"FOK","lastQuantity":0,"lastPrice":"","leavesQuantity":0,"cumQuantity":0,"averagePrice":"0","created":1521280183349,"execReportType":"rejected","orderRejectReason":"orderExceedsLimit"}}

**Comment by viacheslavvbogdanov** [comment]
first I found bug at my side and changed code to use BigNumber library
```
let floor = Math.floor(rawAmount / step.market.lot)
let bn =  new BigNumber(floor)
let amount = bn.times(step.market.lot).toString()
```
because just 
`let amount = Math.floor(rawAmount / step.market.lot) * step.market.lot`
gives 0.043000000000000003 too
where lot = 0.001

**Comment by kroitor** [comment]
> first I found bug at my side and changed code to use BigNumber library

... and then? )

> my code

Was that the code for v1 or v2...

For some reason you've copied just the final portion of it, without the request itself and without the exception stack... we actually need the entire verbose output (without the keys, of course).... Anyways, will figure it out shortly. This issue is already addressed in these updates that are going to be merged soon: 

- https://github.com/ccxt/ccxt/pull/1635
- https://github.com/ccxt/ccxt/pull/2121
- https://github.com/ccxt/ccxt/pull/2171

Will let you know when this is merged and will update you here.

**Comment by viacheslavvbogdanov** [comment]
but then when I send '0.043' to await exchange.createMarketBuyOrder( pair, amount) it converted to 0.043000000000000003 on your side.
There is not exception - hitbtc2 just reply with rejected order

**Comment by kroitor** [comment]
@viacheslavvbogdanov got it, thx for reporting, will get back to you on this issue, hopefully soon. We're working on it.
