### ISSUE TITLE
bybit use fetch_open_orders but can not fetch all order 

### ISSUE THREAD

**Issue by guesshaha** [ccxt/ccxt#22887]
### Operating System

Linux guess 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Programming Languages

Python

### CCXT Version

4.3.51

### Description

I USE fetch_open_orders in bybit but can not fetch all open orders,can only fetch one page , I think the code is not the whole
I think in add_pagination_cursor_to_result just add pagination but not process

### Code

```
  order_info_list = await self.exchange.fetch_open_orders(symbol=self.symbol)

```
```
    def add_pagination_cursor_to_result(self, response):
        result = self.safe_dict(response, 'result', {})
        data = self.safe_value_n(result, ['list', 'rows', 'data', 'dataList'], [])
        paginationCursor = self.safe_string_2(result, 'nextPageCursor', 'cursor')
        dataLength = len(data)
        if (paginationCursor is not None) and (dataLength > 0):
            first = data[0]
            first['nextPageCursor'] = paginationCursor
            data[0] = first
        return data
```

**Comment by sc0Vu** [comment]
Hi @guesshaha it looks like we didn't call fetchOpenOrders recursively, will fix this asap.

**Comment by carlosmiei** [comment]
@guesshaha Can you update your ccxt version and try again? I believe it should be working now

**Comment by guesshaha** [comment]
> @guesshaha Can you update your ccxt version and try again? I believe it should be working now

everything  is good now thank you

~~~
        order_info_list = await self.exchange.fetch_open_orders(symbol=self.symbol, params={"paginate": True})
~~~
