### ISSUE TITLE
Hyperliquid stoploss order question

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#22904]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.3.50

### Description

Hello,

When creating a stoploss order manually in the gui, by editting the TP/SL from the position, the position and order look like this:
![image](https://github.com/ccxt/ccxt/assets/22920143/0b673dac-3609-410f-8997-c204ef45386e)
![image](https://github.com/ccxt/ccxt/assets/22920143/9428a267-bd35-4b3a-ac9b-0a260b2638b7)

When creating a stoploss order with ccxt, I'm forced to enter an amount and price. If I do not enter an amount or price (or enter None), I get this:
```
pprint(await e.create_order('ETH/USDC:USDC', 'STOP_MARKET', 'sell', {'stopLossPrice': 3000, 'reduceOnly': True}))
Traceback (most recent call last):
  File "C:\Users\test\PycharmProjects\Testproject\_test\test_hyperliquid.py", line 61, in tst
    await create_stoploss(e)
  File "C:\Users\test\PycharmProjects\Testproject\_test\test_hyperliquid.py", line 48, in create_stoploss
    pprint(await e.create_order('ETH/USDC:USDC', 'STOP_MARKET', 'sell', {'stopLossPrice': 3000, 'reduceOnly': True}))
  File "C:\Users\test\PycharmProjects\Testproject\venv\lib\site-packages\ccxt\async_support\hyperliquid.py", line 1023, in create_order
    response = await self.create_orders([order], globalParams)
  File "C:\Users\test\PycharmProjects\Testproject\venv\lib\site-packages\ccxt\async_support\hyperliquid.py", line 1086, in create_orders
    px = self.price_to_precision(symbol, price)
  File "C:\Users\test\PycharmProjects\Testproject\venv\lib\site-packages\ccxt\async_support\hyperliquid.py", line 872, in price_to_precision
    result = self.decimal_to_precision(price, ROUND, market['precision']['price'], SIGNIFICANT_DIGITS, self.paddingMode)
  File "C:\Users\test\PycharmProjects\Testproject\venv\lib\site-packages\ccxt\base\decimal_to_precision.py", line 58, in decimal_to_precision
    dec = decimal.Decimal(str(n))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

So, using ccxt my position and stop order looks different:
```
pprint(await e.create_order('ETH/USDC:USDC', 'STOP_MARKET', 'sell', 0.004, 3386.0, {'stopLossPrice': 3000, 'reduceOnly': True}))
```
![image](https://github.com/ccxt/ccxt/assets/22920143/37a7628b-6acf-4e58-8ab8-260ed0916e80)
![image](https://github.com/ccxt/ccxt/assets/22920143/d1625f5e-0d97-4168-b43f-a0e306a96dd4)

The position doesn't seem to be linked to the stop order in the same way. Now, I'm not sure what effect this has. I'm matching the `price` and `amount` to my open position, and setting `stopLossPrice` to the price I want the order to trigger on. Is this the correct way? Is there a way to add a stoploss order in a way that is similar to adding it in an open position in the hyperliquid gui (first image)?

Thanks!

**Comment by sc0Vu** [comment]
Hi @grantweii 

![image](https://github.com/ccxt/ccxt/assets/10494397/c6da356e-ac9f-4853-b882-99c40b782bc0)

When add TP/SL price in their web ui, it would create two more market orders for user, can simulate the behavior by create orders.

**Comment by gaardiolor** [comment]
ok, I think I found how to do it. First to get back to your point @sc0Vu , when I create a stoploss order by 'editing' TP/SL in the position in the webapp, I only see one order in my intercepting proxy. Not sure why you see multiple..

```
{
  "action": {
    "grouping": "positionTpsl",
    "orders": [
      {
        "a": 1,
        "b": false,
        "p": "2944",
        "r": true,
        "s": "0",
        "t": {
          "trigger": {
            "isMarket": true,
            "tpsl": "sl",
            "triggerPx": "3200"
          }
        }
      }
    ],
    "type": "order"
  },
  "isFrontend": true,
  "nonce": 1719699507979,
  "signature": {
    "r": "<snip>",
    "s": "<snip>",
    "v": 27
  },
  "vaultAddress": null
}
```
`"p": "2944"` seems arbitrary, I never entered it. 

The thing that stands out is `"s": "0"` (`s` corresponds to `amount`)

if I create a stoploss order with amount 0 like this: `await e.create_order('ETH/USDC:USDC', 'STOP_MARKET', 'sell', 0, 3000, {'stopLossPrice': 3200, 'reduceOnly': True})` , in the gui that stoploss order is linked to the position just like in the webapp gui.
