### ISSUE TITLE
okx fetch_positions return null

### ISSUE THREAD

**Issue by downdawn** [ccxt/ccxt#22919]
### Operating System

windows10

### Programming Languages

Python

### CCXT Version

4.3.43

### Description

The results of OKX's `fetch_position` method and `fetch_positions` method are different. The `fetch_position` method returns correctly, while the `fetch_positions` method returns an empty list.

### Code

```
import ccxt

exchange = ccxt.okx({
    'apiKey': 'xxx',
    'secret': 'xxx',
    'password': 'xxx',
    'verbose': True,
})
print(exchange.fetch_position(symbol='BTC-USDT-240927'))
print(exchange.fetch_positions(symbols=['BTC-USDT-240927'], params={'instType': 'FUTURES'}))

```

**Comment by carlosmiei** [comment]
Hello @downdawn, thanks for reporting it, we will take a look asap.

**Comment by Dan-krm** [comment]
Hi @downdawn I will look in to adding support for market ID's but in the meantime the `fetch_postions` method should work if you use the unified market symbol, in this case that would be:
```
BTC/USDT:USDT-240927
```
```
print(exchange.fetch_positions(symbols=['BTC/USDT:USDT-240927']))
```
Here is an explanation of the symbol naming conventions in the CCXT documentation:
https://docs.ccxt.com/#/?id=contract-naming-conventions

**Comment by downdawn** [comment]
> Hi @downdawn I will look in to adding support for market ID's but in the meantime the `fetch_postions` method should work if you use the unified market symbol, in this case that would be:
> 
> ```
> BTC/USDT:USDT-240927
> ```
> 
> ```
> print(exchange.fetch_positions(symbols=['BTC/USDT:USDT-240927']))
> ```
> 
> Here is an explanation of the symbol naming conventions in the CCXT documentation: https://docs.ccxt.com/#/?id=contract-naming-conventions

Thanks
