### ISSUE TITLE
Kucoin watchMyTrades uses undocumented API

### ISSUE THREAD

**Issue by colin-nl** [ccxt/ccxt#22915]
### Operating System

Debian 12

### Programming Languages

Python

### CCXT Version

4.3.31

### Description

I am using CCXT Pro to access Kucoin. I am noticing that the `watch_my_trades()` function is not giving me any messages even when fills are happening on account. Looking under the covers, it seems that CCXT is subscribing to the `/spot/tradeFills` topic. I am looking at Kucoin websocket API documentation and I do not see any trade or fills topic. The closest I see is a "Private Order Change" topic that uses `/spotMarket/` instead of `/spot/`.

I am wondering whether is CCXT relying on an undocumented API endpoint? Or am I missing something? Could anyone else using Kucoin verify whether their `watch_my_trades()` works or not?

Some relevant links:

Code in CCXT subscribing to the `/spot/tradeFills` topic: https://github.com/ccxt/ccxt/blob/master/python/ccxt/pro/kucoin.py#L909

Private Order Change topic: https://www.kucoin.com/docs/websocket/spot-trading/private-channels/private-order-change

### Code

```
  

```

**Comment by sc0Vu** [comment]
@colin-nl it's probably a deprecated topic. We'll update asap.

**Comment by colin-nl** [comment]
Thank you so much for the super quick fix @sc0Vu ! I really appreciate it! Could you create a release with the fix so we can use it?
