### ISSUE TITLE
Hyperliquid fetchticker/fetchtickers

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#22927]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

Hello, in hyperliquid, fetchticker/fetchtickers is not supported. Freqtrade seems to require it. Any plans to implement fetchticker/fetchtickers?

### Describe the solution you'd like

Implementation of fetchticker/fetchtickers

### Describe alternatives you've considered

I don't think there is a workaround

**Comment by sc0Vu** [comment]
@gaardiolor We'll add those methods if there are corresponding APIs.

**Comment by ttodua** [comment]
unfortuantely, there does not seem to be "fetchTickers" possible at this moment, however, there is possible to use "watchTickers" and i've linked a PR what would implement it

**Comment by gaardiolor** [comment]
Thanks. My goal is to use this exchange in freqtrade though.. freqtrade needs fetch_ticker & fetch_tickers .

Hyperliquid `metaAndAssetCtxs` and `spotMetaAndAssetCtxs` provide volume, which could be used for fetch_tickers. Most of the rest of the values could be returned as `None` until they provide more data?

fetch_ticker could use the data of fetch_order_book get `bid`, `bidVolume`, `ask`, `askVolume`, `quoteVolume` ?

Especially the fetch_tickers would be a bit minimal, but I think it might be enough for freqtrade..

**Comment by ttodua** [comment]
@gaardiolor I've pushed a PR that implements fetchTickers, however fetchTicker derivation from fetchOrderBook will not be correct implementation from ccxt side. maybe you can ask freqTrade to add an option to feed data from **fOB** when **fT** is not available
