### ISSUE TITLE
Kucoin streamed trade has incorrect price

### ISSUE THREAD

**Issue by colin-nl** [ccxt/ccxt#22925]
### Operating System

Debian 12

### Programming Languages

Python

### CCXT Version

Master

### Description

This is a follow up issue after trying out the fix to Kucoin `watch_my_trades` that resolved this previous issue I raised: https://github.com/ccxt/ccxt/issues/22915

I checked out the master branch to test the fix and found that the price in the trade object is the request price rather than the fill price. I suspect you're using the "price" and "size" fields from the source message rather than the "matchPrice" and "matchSize" message. The "cost" field is also incorrect because of the incorrect source data. Could you please update the fields you're reading from?

See the sample output below for details.

### Code

```
    {
        "info": {
            "clientOid": "<redacted>",
            "feeType": "takerFee",
            "filledSize": "0.1101",
            "liquidity": "taker",
            "matchPrice": "1.00144",
            "matchSize": "0.1101",
            "orderId": "<redacted>",
            "orderTime": 1719597979322,
            "orderType": "limit",
            "price": "0.95138",
            "remainSize": "0",
            "side": "sell",
            "size": "0.1101",
            "status": "match",
            "symbol": "USDC-USDT",
            "tradeId": "<redacted>",
            "ts": 1719597979350000000,
            "type": "match",
        },
        "timestamp": 1719597979350,
        "datetime": "2024-06-28T18:06:19.350Z",
        "symbol": "USDC/USDT",
        "id": "<redacted>",
        "order": "<redacted>",
        "type": "limit",
        "takerOrMaker": "taker",
        "side": "sell",
        "price": 0.95138,
        "amount": 0.1101,
        "cost": 0.104746938,
        "fee": None,
        "fees": [],
    }
```

**Comment by colin-nl** [comment]
Thanks for the quick fix! ❤️

**Comment by carlosmiei** [comment]
@colin-nl Thank you for the report 🙂 ! Let us know if anything!
