### ISSUE TITLE
Different positions and orders attribute names on Bybit and Binance

### ISSUE THREAD

**Issue by seeyoul8r** [ccxt/ccxt#22937]
### Operating System

windows 11

### CCXT Version

last

### Description

Hello! I'm not sure if it is a bug or a feature, but positions and orders attributes on bybit and binance markets are differ from each other.
![Screenshot 2024-06-30 173353](https://github.com/ccxt/ccxt/assets/124713131/774c537f-f745-4587-b61d-8904b4406fce)
![Screenshot 2024-06-30 180319](https://github.com/ccxt/ccxt/assets/124713131/f9dfa9e2-343b-4179-bbc5-67530ef25587)

So I has to make my own renaming dictionary like that. I guess it would be great to have unified attribute naming in this case.

### Code

```
pos_attrs = {'binance_swap': {'avgPrice': 'entryPrice',
                              'size': 'positionAmt',
                              'positionValue': 'notional',
                              'stopOrderType': 'type',
                              'side': 'positionSide',
                              'leavesQty': 'origQty'},
             'bybit_swap': {'avgPrice': 'avgPrice',
                            'size': 'size',
                            'positionValue': 'positionValue',
                            'stopOrderType': 'stopOrderType',
                            'side': 'side',
                            'leavesQty': 'leavesQty'}}  

# Get actual position information
    try:
        position = open_positions[user][market][ticker]
        actual_price = float(position[pos_attrs[market]['avgPrice']])
        actual_amount = float(position[pos_attrs[market]['size']])
        actual_size = float(position[pos_attrs[market]['positionValue']])

```

**Comment by sc0Vu** [comment]
Hi @seeyoul8r, The data should be unified to designed structure, eg market (https://github.com/ccxt/ccxt/wiki/Manual#market-structure):

```
Market{
    'id':      'btcusd',      // string literal for referencing within an exchange
    'symbol':  'BTC/USD',     // uppercase string literal of a pair of currencies
    .....
    'info':      { ... },     // the original unparsed market info from the exchange
}
```

Any code we can reproduce this issue?

**Comment by seeyoul8r** [comment]
Excuse me for my stupidity, I just parse information about orders and positions from ['info'] dictionary inside root position dictionary. I guess it consits of 'natural' attributes. Root dictionary has unified attributes.

**Comment by sc0Vu** [comment]
@seeyoul8r No worries, let us know if you have any other issues.
