### ISSUE TITLE
Retrieving open orders from different markets

### ISSUE THREAD

**Issue by seeyoul8r** [ccxt/ccxt#22930]
### Operating System

windows 11

### CCXT Version

last

### Description

Hello! i'm trying to get open orders from several exchanges, I'm using fetchOpenOrders method. Without ticker it works correctly on Bybit, but on Binance ccxt returns such error: _binance fetchOpenOrders\(\) WARNING: fetching open orders without specifying a symbol is rate-limited to one call per 1525 seconds. Do not call self method frequently to avoid ban. Set binance.options["warnOnFetchOpenOrdersWithoutSymbol"\] \= False to suppress self warning message._ 
On swap market it is not a problem, because I can get currently opened positions tickers and retrieve open stop orders,
```
for ticker in open_positions:
    await update_open_stop_orders(user, market, ticker)
```
 while on spot such decision for limit sell orders obviously doesnt work. How is it better to handle that issue?

**Comment by sc0Vu** [comment]
Hi @seeyoul8r, You can set `options['warnOnFetchOpenOrdersWithoutSymbol']=false` to disable the warning.

**Comment by seeyoul8r** [comment]
> Hi @seeyoul8r, You can set `options['warnOnFetchOpenOrdersWithoutSymbol']=false` to disable the warning.

Yes, but in this case I'm able to be banned due to often requests, right?

**Comment by carlosmiei** [comment]
> > Hi @seeyoul8r, You can set `options['warnOnFetchOpenOrdersWithoutSymbol']=false` to disable the warning.
> 
> Yes, but in this case I'm able to be banned due to often requests, right?

@seeyoul8r Yes, you should minimize the number of requests to that endpoint without providing a symbol. Alternatively you can call it specifying a `symbol`, the rateLimit weight in that case is much lower.

**Comment by seeyoul8r** [comment]
> > > Hi @seeyoul8r, You can set `options['warnOnFetchOpenOrdersWithoutSymbol']=false` to disable the warning.
> > 
> > 
> > Yes, but in this case I'm able to be banned due to often requests, right?
> 
> @seeyoul8r Yes, you should minimize the number of requests to that endpoint without providing a symbol. Alternatively you can call it specifying a `symbol`, the rateLimit weight in that case is much lower.

Thanks! So if i want to get all open limit sell orders on spot exchange I need to devise some logic, for example - receiving recent trades and fetch symbols from it, right?

**Comment by ttodua** [comment]
I've checked this, in real numbers, you can request once per second (without symbol), but with symbol you can request around 10 times per second. 
 `1 call per 1525 seconds` is a bug and we will try to fix it.

**Comment by seeyoul8r** [comment]
@ttodua, thanks for that comprehensive answer! I'll try to use it in my logic
