### ISSUE TITLE
fetch balance doesn't work on bybit inverse account

### ISSUE THREAD

**Issue by materemias** [ccxt/ccxt#22953]
### Operating System

linux

### Programming Languages

Python

### CCXT Version

4.3.55

### Description

fetch_balance() always loads 'unified' wallet's balance. On bybit there is a unified (v5) API, but the inverse pairs have their own wallet, you can query the unified balance with `request['accountType'] = 'UNIFIED'` and the inverse balance with  `request['accountType'] = 'CONTRACT'`. In the latest ccxt code it doesn't work though because the branch which could set type to contract is unreachable if the account is unified.

```
        # from ccxt's bybit.py
        if isUnifiedAccount:
            if isSpot or isSwap:
                type = 'unified'
        else:
            if isSwap:
                type = 'contract'
```

fetch_open_orders() and fetch_positions() handles this properly.

for a quick workaround I can use
`exchange.parse_balance(exchange.privateGetV5AccountWalletBalance({'accountType': 'CONTRACT'}))`

### Code

```
  

```

**Comment by materemias** [comment]
@sc0Vu thanks for the prompt reply, I think it won't solve it. `isSwap` will be `True` (it gets picked up correctly anyways) but since `isUnifiedAccount` is also `True` we never get to set `contract` as type.

![image](https://github.com/ccxt/ccxt/assets/529994/6eee1731-153c-4b8b-9081-99542c1d4c9b)

**Comment by materemias** [comment]
`fetch_balance({'type': 'contract'})` will work though, thanks for the hint! (still the autodetection logic is broken)

**Comment by sc0Vu** [comment]
@materemias I think you're right. The type should be contract for unified account (my test account was non-unified). We'll fix this asap.
