### ISSUE TITLE
Kraken. EAPI:Invalid nonce

### ISSUE THREAD

**Issue by skuvv** [ccxt/ccxt#22971]
### Operating System

Windows 10

### CCXT Version

4.3.49

### Description

After some time of using Kraken I getting an error: "EAPI:Invalid nonce".
I have tried to modify ```public override object nonce() {}``` but with no luck.
Also I have tried API keys with nonce window about 1 sec.
Can you help with this?

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @skuvv,

We also face this issue intermittently, and we haven't been able to pinpoint the issue yet. For instance, I just tested it, and it's working on my end. 

Have you used your API keys with a different application?
Have you tried to create a new set of keys? (usually that fixes it for me)

```
ccxt@4.3.56 cli.cs
> dotnet run --project "./cs/cli/cli.csproj" kraken FetchBalance

[]
{
  "balances": {
    "ADA": {
      "free": 15.0,
      "used": 0.0,
      "total": 15.0
    },
    "USDC": {
      "free": 0.0,
      "used": 0.0,
      "total": 0.0
    },
    "USDT": {
      "free": 107.15231782,
      "used": 5.61,
```

**Comment by skuvv** [comment]
I created a new dedicated API key with window = 1000 and got this problem. The problem occur not immediately.
I can prepare internal ccxt logs for you.
Problem is too crucial for us.

**Comment by carlosmiei** [comment]
@skuvv BUt is there a way of reproducing the issue ? what if you increase the window to let's say 5000?

**Comment by skuvv** [comment]
@carlosmiei I didn't found a clue for this issue -(
I will try to increase the window.

**Comment by carlosmiei** [comment]
@skuvv Hum found an sdk using nanoseconds as the nonce, can you try to override `nonce` to return `nanoseconds` instead?

https://github.com/btschwertfeger/python-kraken-sdk/blob/master/kraken/base_api/__init__.py#L435-L436

**Comment by skuvv** [comment]
Changing nonce() to microseconds didn't help.
Extending nonceWindow to 5000 and above looks much better - two nights without "EAPI:Invalid nonce".

**Comment by carlosmiei** [comment]
@skuvv thanks for letting us know.
