### ISSUE TITLE
Memory leak Python fetch_ohlcv

### ISSUE THREAD

**Issue by ShanSenanayake** [ccxt/ccxt#2297]
I am getting severe memory leaks when fetching data from poloniex with ccxt with the following code:
```
import ccxt
import time
import requests

if __name__ == '__main__':
  while True:
    time.sleep(1)
    exchange = ccxt.poloniex({
      'enableRateLimit': True,
    })
    try:
      print("fetching")
      candlestick_data = exchange.fetch_ohlcv('ETH/BTC')
      print(candlestick_data[-10:])
    except:
      print("failed to fetch")

```
My monitoring produces this image: 
![poloniex](https://user-images.githubusercontent.com/8779685/37565586-1bec2062-2aac-11e8-80bd-eca5fd72883e.png)

As you can see every time a request is being made memory is being reserved but never relased. Am I using ccxt correctly or is this a memory leak in the application? 

Specs:
- OS: Ubuntu 16.04
- Programming language: Python 2.7.12
- CCXT version: 1.11.118
- Exchange: Poloniex

**Comment by mw130** [comment]
@kroitor I think I might be having this same issue - I get portions of OHLCV in a for loop, and my OHLCV var keeps doubling every time.
