### ISSUE TITLE
Exchange ccex returns    'symbol' = None    in python . (should be like 'LTC/BTC')

### ISSUE THREAD

**Issue by garker** [ccxt/ccxt#2298]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by kroitor** [comment]
Any code/verbose output to reproduce your issue according to the rules:
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?
