### ISSUE TITLE
GateIO Futures - cannot create stop loss order with price 0

### ISSUE THREAD

**Issue by krasnyd** [ccxt/ccxt#22989]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.3.23

### Description

According to the [documentation on Gateio](https://www.gate.io/docs/developers/apiv4/en/#create-a-price-triggered-order-2), you can use the parameter `initial.price="0"` to use the market price. But when I try to call the create_order function with parameter `price=0`, I get the error `InvalidOrder gateio price of VET/USDT:USDT must be greater than minimum price precision of 0.00001`, because the CCXT is trying to adjust the price to precision.

I think the problem is right here:
https://github.com/ccxt/ccxt/blob/a2fbfdd945ce7b092f6b8df00c96062d74b75601/python/ccxt/async_support/gate.py#L3887
When I replace this with the `'price': "0"`, it works as I want.

### Code

```python
from asyncio import run, sleep
import ccxt.pro

async def main():
    
    exchange = ccxt.pro.gateio({
        'apiKey': 'xxx',
        'secret': 'xxx',
        'options': {
            'defaultType': 'future',
        }
    })

    try:
        await exchange.load_markets()

        coin_name = "VET_USDT"
        side = "sell"
        amount = 1
        stop_loss_price = 0.02316

        await exchange.create_order(
            symbol=coin_name,
            side=side,
            type="market",
            amount=abs(amount),
            price=0, # According to the API documentation: "Order price. Set to 0 to use market price"
            params={"stopLossPrice": stop_loss_price}
        )
        # returns InvalidOrder gateio price of VET/USDT:USDT must be greater than minimum price precision of 0.00001
        print("order done")

    except Exception as e:
        print(type(e).__name__, str(e))

    await exchange.close()


run(main())


```

**Comment by carlosmiei** [comment]
Hello @krasnyd, thanks a lot for reporting it, we will take a look asap.

**Comment by carlosmiei** [comment]
@krasnyd Can you please update your ccxt version and try again? I believe it should be working now.

**Comment by krasnyd** [comment]
@carlosmiei Thank you for a quick reaction. I have tested it and it works.
