### ISSUE TITLE
OKX: createOrders() causes to break watchOrders() (multiple orders update)

### ISSUE THREAD

**Issue by Tongoko** [ccxt/ccxt#22996]
### Operating System

Ubuntu 22

### Programming Languages

Python

### CCXT Version

4.3.57

### Description

After creating multiple orders with createOrders() and receiving a multi order update on watchOrders(), watchOrders goes into a loop giving the same update over and over in a 1sec interval.
It gives no updates for any future orders after that, but keeps printing the same batch update.

No Errors raised.

```
self.ccxtpro = ccxtpro.okx({})

async def watchOrders():
    while True:
        orders = await self.ccxtpro.watchOrders()
        print(orders)
```

### Code

```
# Creating limit_order -> batch_order -> limit_order

# Limit order 1
res = await self.ccxtpro.create_order()
order_id:   # 12345
time.sleep(10)

# Batch order
orders = [order1, order2]
res = await self.ccxtpro.create_orders()
order_ids:   #23456 #23457
time.sleep(10)

# Limit order 2
res = await self.ccxtpro.create_order()
order_id:   # 34567
time.sleep(10)

--------

watchOrders() prints:
order # 12345 update
# after 10 sec:
order #23456 #23457 update
order #23456 #23457 update
order #23456 #23457 update
order #23456 #23457 update
order #23456 #23457 update
.
.
.
No update for order # 34567

```

**Comment by carlosmiei** [comment]
Hello @Tongoko, thanks for reporting it, this is indeed worrying. If you don't use `createOrders` you don't get the issue?
(we will try to check it shortly)

**Comment by carlosmiei** [comment]
@Tongoko, Can you please update your ccxt version and try again?
