### ISSUE TITLE
UPBIT - cannnot fetch open orders

### ISSUE THREAD

**Issue by bongkook** [ccxt/ccxt#22990]
### Operating System

Max

### Programming Languages

JavaScript

### CCXT Version

4.3.57

### Description

Hello.

Upbit cannot fetch open orders
The following error occurred.
upbit {"error":{"name":"invalid_query_payload","message":"Failed to verify the query of Jwt."}}

please check.
Thank you.

### Code

```
upbit = ccxt.upbit({
'apiKey': API_KEY,
'secret': API_SECRET
})
upbit.fetchOpenOrders('BTC/KRW')

=====result=====
upbit {"error":{"name":"invalid_query_payload","message":"Failed to verify the query of Jwt."}}

```

**Comment by carlosmiei** [comment]
Hello @bongkook, thanks for reporting it, we will try to take a look asap

**Comment by bongkook** [comment]
@carlosmiei, thank you.
Additionally, there was no problem before version 4.3.40, but an error occurs in version 4.3.41 or later.

**Comment by Dan-krm** [comment]
Hi @bongkook it looks like the endpoint we were using for `fetchOpenOrders` is being deprecated:
https://global-docs.upbit.com/changelog/new_get_orders

There were also some recent changes to upbits `sign` method that may have been a factor in causing this issue.

I've opened a pull request that should resolve this issue for you once it's merged
