### ISSUE TITLE
How do I create a pull request for Deposits / Withdrawals

### ISSUE THREAD

**Issue by grandmore** [ccxt/ccxt#2300]
I am doing some work on the unified api fo deposits and withdrawals. Initially fo Binance, Coinbase, Gdax and Poloniex in Javascript.

I found [1896](https://github.com/ccxt/ccxt/issues/1896) but cannot find any docs on the right way to do a pull request.

I can fork the repository and do the work there but it seems more logical to get a pull request in the library itself.

Either way can you point me in the right direction and I will get it done.

**Comment by kroitor** [comment]
1.  https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
2. https://help.github.com/articles/creating-a-pull-request/

Let us know if the above does not help )
