### ISSUE TITLE
bybit buy spot : decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

### ISSUE THREAD

**Issue by vpreparate** [ccxt/ccxt#23017]
### Programming Languages

Python

### CCXT Version

4.0.18

### Description

2.62 7.283
Traceback (most recent call last):
  File "D:\less\bybitPRO100.py", line 120, in <module>
    order = client.create_spot_order(symbol, 'market', 'buy', order_amount, {'cost': order_cost})
  File "C:\Python\lib\site-packages\ccxt\bybit.py", line 3643, in create_spot_order
    priceString = self.number_to_string(price)
  File "C:\Python\lib\site-packages\ccxt\base\decimal_to_precision.py", line 172, in number_to_string
    d = decimal.Decimal(str(x))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

when I sell spot without a parameter cost everything works:
order = client.create_spot_order(symbol, 'market', 'sell', 0.36) it is Good

### Code

```
order_amount = 0.36
order_cost = Decimal(str(order_amount * price))
print(order_cost, price)
order = client.create_spot_order(symbol, 'market', 'buy', order_amount, {'cost': order_cost})

```

**Comment by sc0Vu** [comment]
Hi @vpreparate The fifth parameter would be price.

![image](https://github.com/ccxt/ccxt/assets/10494397/9a41b143-e271-4ba7-aa0d-fbc8614aad92)

**Comment by carlosmiei** [comment]
Hello @vpreparate, if you want to create a spot order using cost, you can use `createMarketBuyOrderWithCost` or `createMarketSellOrderWithCost`

**Comment by vpreparate** [comment]
Thank you are real guys maaaaaans

пн, 8 июл. 2024 г., 11:22 Carlos G ***@***.***>:

**Comment by vpreparate** [comment]
What is the difference between the price and the cost on the exchange?
