### ISSUE TITLE
QUESTION: using of both async and sync versions of ccxt within same app

### ISSUE THREAD

**Issue by ByTheSeaL** [ccxt/ccxt#23018]
### Operating System

Windows 11 / Debian

### Programming Languages

Python

### CCXT Version

4.3.15

### Description

Hi. First thing to say is thank you for ccxt - it's a really brilliant library!

I have an app written in python which is watching or fetching orderbooks at multiple exchanges - using CCXT Pro where available, or async fetch methods where not.

I want to try reconfigure my app with threads for some of orderbook fetching (because, off topic, my UI is running in the same event loop as ccxt and is lagging). This means I need to use the non-async ccxt library.

I still want to use watchOrderBooks for some lookups but also threaded fetches alongside. I'm loathe to create two objects for ccxt and ccxt pro however (plus running load_markets on both). Is there a way to just load the async version but fallback to the non-async method at times? Or will I always need to do both imports and create both objects?

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @ByTheSeaL, The async integration works differently; you'll need to initialize two exchange objects.

**Comment by ByTheSeaL** [comment]
Ok thank you @sc0Vu
