### ISSUE TITLE
Use of 'CCTX' for an inspired Julia library

### ISSUE THREAD

**Issue by dmitrii-doronin** [ccxt/ccxt#23021]
### Description

Hi, I have asked this question on Discord but did not get any response, so I am repeating it here.

We've been working on a Julia implementation of a cryptocurrency exchanges library inspired heavily by the 'CCTX'. Our goal is to contribute to Julia's General registry, which is like 'npm' for Julia users. 

Since the library has such close ties to 'CCTX', we would love to use that name (or something similar like 'CCXT') for our package.

How do you feel about that?

You can find the package here: https://github.com/bhftbootcamp/CryptoAPIs.jl 

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @dmitrii-doronin ,

We really appreciate the inspiration you took from CCXT, and we truly believe your product is doing a great job for the Julia community. Congrats on that!

Nonetheless, it's still a different product run and maintained by a different team, and for that reason, I don't think it's adequate to use CCXT there. 

cc/ @kroitor  @frosty00

**Comment by dmitrii-doronin** [comment]
Thank you very much. I think it resolves my question!

**Comment by femtotrader** [comment]
https://github.com/ccxt/ccxt/issues/15852 seems to be a related issue
