### ISSUE TITLE
Support proxy access

### ISSUE THREAD

**Issue by jackyxie** [ccxt/ccxt#2302]
Excuse me,
      Currently, ccxt only has cros proxy, but donot support use another proxy ip to sendout request in curl. Maybe you can have it configurable in the library. Such as:

      curl_setopt($this->curl, CURLOPT_PROXYTYPE, CURLPROXY_SOCKS5_HOSTNAME);
      curl_setopt($this->curl, CURLOPT_PROXY, '127.0.0.1:1080');
      curl_setopt($this->curl, CURLOPT_SSL_VERIFYPEER, true);
      curl_setopt($this->curl, CURLOPT_SSL_VERIFYHOST, 2);

We can config whether to use proxy ip in a specific market or not.

**Comment by kroitor** [comment]
As of ccxt 1.11.142 you can override all cURL options by defining an array of `$exchange->curl_options` in the constructor or anytime after:

```PHP
$id = 'kraken';
$exchange = '\\ccxt\\' . $id;

$exchange = new $exchange (array (
    'curl_options' => array (
        CURLOPT_PROXYTYPE => CURLPROXY_SOCKS5_HOSTNAME,
        CURLOPT_PROXY => '127.0.0.1:1080',
        CURLOPT_SSL_VERIFYPEER => true,
        CURLOPT_SSL_VERIFYHOST => 2,
    ),
));

// or:
$exchange->curl_options['CURLOPT_PROXYTYPE'] = CURLPROXY_SOCKS5_HOSTNAME;
// ...
```

↑ These `curl_options` are set just before sending the request, after setting all the other defaults.

Let us know if it does not help or if you have difficulties with it. Thanks!
