### ISSUE TITLE
dont understand the error message and what to do with / please help in details

### ISSUE THREAD

**Issue by Bgsolid** [ccxt/ccxt#23034]
### Operating System

Windows 11

### CCXT Version

4.1.78.

### Description

Hello Team!

I use orders, limits, markets, stop limits, stop markets as well.
Somehow I have issue with - not all the time, but sometimes - with simple market order.

The order structure is this:

exchange.createOrder(symbol, 'market', order_side, amount, params={'positionSide': pos_side})

All the referenced variables have proper values that match with exchange requirements.

The error message I receive is this:
  File "C:\Users\Gabor\PycharmProjects\ccxt\venv\lib\site-packages\ccxt\binance.py", line 4279, in create_order
    request = self.create_order_request(symbol, type, side, amount, price, params)
  File "C:\Users\Gabor\PycharmProjects\ccxt\venv\lib\site-packages\ccxt\binance.py", line 4457, in create_order_request
    request['quantity'] = self.amount_to_precision(symbol, amount)
  File "C:\Users\Gabor\PycharmProjects\ccxt\venv\lib\site-packages\ccxt\base\exchange.py", line 3950, in amount_to_precision
    raise InvalidOrder(self.id + ' amount of ' + market['symbol'] + ' must be greater than minimum amount precision of ' + self.number_to_string(market['precision']['amount']))
ccxt.base.errors.InvalidOrder: binanceusdm amount of SOL/USDC:USDC must be greater than minimum amount precision of 2

I use amount precision with this code:
def adjust_amount(symbol, amount):
    exchange.load_markets()
    symbol_formatted = symbol.replace("USDC", "/USDC:USDC")
    market = exchange.markets[symbol_formatted]
    amount_precision = market['precision']['amount']
    # Calculate the power of 10 for the required precision
    power_of_ten = 10 ** amount_precision
    # Adjust the amount using ceil and power of 10
    adjusted_amount = math.ceil(amount * power_of_ten) / power_of_ten
    return adjusted_amount

Can you please help me to understand what I do wrong?
Actually I dont understand the problem exactly.
If you can give me detailed explanation what is the background of the issue, like the concept behind it, I would appreciate so much!

Thank you!

Kind regards,
Gabor

### Code

exchange.createOrder(symbol, 'market', order_side, amount, params={'positionSide': pos_side})

def adjust_amount(symbol, amount):
    exchange.load_markets()
    symbol_formatted = symbol.replace("USDC", "/USDC:USDC")
    market = exchange.markets[symbol_formatted]
    amount_precision = market['precision']['amount']
    # Calculate the power of 10 for the required precision
    power_of_ten = 10 ** amount_precision
    # Adjust the amount using ceil and power of 10
    adjusted_amount = math.ceil(amount * power_of_ten) / power_of_ten
    return adjusted_amount

**Comment by sc0Vu** [comment]
@Bgsolid 

The error represents that the amount should be bigger than the `market['precision']['amount']`. Take `ETH/USDT` market in kucoin as example, the market data is:
```JS
{
  id: 'ETH-USDT',
  symbol: 'ETH/USDT',
  base: 'ETH',
  quote: 'USDT',
  baseId: 'ETH',
  quoteId: 'USDT',
  type: 'spot',
  spot: true,
  margin: true,
  swap: false,
  future: false,
  option: false,
  active: true,
  contract: false,
  taker: 0.001,
  maker: 0.001,
  precision: { amount: 1e-7, price: 0.01 },
  limits: {
    leverage: {},
    amount: { min: 0.0001, max: 10000000000 },
    price: {},
    cost: { min: 0.01, max: 999999999 }
  },
  tierBased: true,
  percentage: true,
  tiers: {
    taker: [
      [ 0, 0.001 ],
      [ 50, 0.001 ],
      [ 200, 0.0009 ],
      [ 500, 0.0008 ],
      [ 1000, 0.0007 ],
      [ 2000, 0.0007 ],
      [ 4000, 0.0006 ],
      [ 8000, 0.0005 ],
      [ 15000, 0.00045 ],
      [ 25000, 0.0004 ],
      [ 40000, 0.00035 ],
      [ 60000, 0.0003 ],
      [ 80000, 0.00025 ]
    ],
    maker: [
      [ 0, 0.001 ],
      [ 50, 0.0009 ],
      [ 200, 0.0007 ],
      [ 500, 0.0005 ],
      [ 1000, 0.0003 ],
      [ 2000, 0 ],
      [ 4000, 0 ],
      [ 8000, 0 ],
      [ 15000, -0.00005 ],
      [ 25000, -0.00005 ],
      [ 40000, -0.00005 ],
      [ 60000, -0.00005 ],
      [ 80000, -0.00005 ]
    ]
  },
  marginMode: { cross: true, isolated: true }
}
```

And the precision of the amount is 1e-7, which means the amount should be bigger than 0.0000001.

**Comment by Bgsolid** [comment]
Im debugging for a while, and test the amount generation for a couple of scenarios. My understanding is that somehow I made amount = 0 orders, which can trigger this kind of error message. Will be back in a couple of days after. Thank you!

**Comment by Bgsolid** [comment]
Tested, and somehow I managed to use order amount = 0, that was the problem. Thank you for explaining the function!
