### ISSUE TITLE
Are exchange.markets base and quote supposed to be used as keys for exchange.currencies?

### ISSUE THREAD

**Issue by gabemahoney** [ccxt/ccxt#2304]
My first post here so let me begin by saying how great this package is and how grateful I am to all of you supporting it!

I didn't see it stated explicitly anywhere, but I have discovered that in most cases you can use the values from `exchange.markets[market]['base']` and `exchange.markets[market]['quote']` as keys into `exchange.currencies` (in the sense that it does not throw a `KeyError`). 

Is this behavior as designed, and is it intended to be reliable? Or is there another value from the markets dict which should be used as the lookup in the currencies dict for a given exchange?

If these keys and values are meant to be used this way then I can report that there are some instances where the base or quote value from `exchange.markets[market]` do not exist as keys in `exchange.currencies`. I can share the list here (or the code I used to generate it), if so. If not, please let me know what the appropriate way is to get currencies for a given market's base and quote.

Thanks!

- OS: Mac
- Programming Language version: Python 3.6.4
- CCXT version: 1.11.135
- Exchange: coinexchange, coinmarketcap, tidex (of those exchanges which do not require accounts to call load_markets)
- Method: exchange.currencies dict

**Comment by kroitor** [comment]
> Is this behavior as designed

Yep, this is by design...

> and is it intended to be reliable?

The reliability is a difficult question, you'll understand this when you get more involved into communicating with exchanges that don't want to communicate whether via docs or by other means )) So, in general, you should treat this library as being under active development, in other words, a a work in progress or a yet unfinished work. The goal is indeed to make it so reliable.

> If these keys and values are meant to be used this way then I can report that there are some instances where the base or quote value from exchange.markets[market] do not exist as keys in exchange.currencies. I can share the list here (or the code I used to generate it), if so.

When dealing with inconsistencies we need to know the pair, the currency, the exchange in question as much as possible... Your code would also help resolve it quicker.

Thank you!

**Comment by gabemahoney** [comment]
Hey Kroitor, thanks very much for your response. Yes, I understand things being in active development. I guess I meant "as reliable as possible given the circumstances" ;)

Here is the code I ran and its results.
```
d = {'base':[],'quote':[]}
for e in ccxt.exchanges:
    exchange = getattr (ccxt, e)()
    try:
        exchange.load_markets()
    except:
        # can't load some exchanges without an API key so skip them
        continue

    for market in exchange.markets:
        base_key = exchange.markets[market]['base']
        try:
            exchange.currencies[base_key]
        except KeyError:
            if base_key not in d['base']:
                d['base'].append(base_key)
                print("Exchange %s missing base %s" % (e, base_key))
        quote_key = exchange.markets[market]['quote']
        try:
            exchange.currencies[quote_key]
        except KeyError:
            if quote_key not in d['quote']:
                d['quote'].append(quote_key)
                print("Exchange %s missing quote %s" % (e, quote_key))
```
OUTPUT:
Exchange coinexchange missing base SYS
Exchange coinexchange missing base BITZ
Exchange coinexchange missing base LOOT
Exchange coinexchange missing base FOOT
Exchange coinexchange missing base PCM
Exchange coinexchange missing base REV
Exchange coinexchange missing base DOLLAR
Exchange coinexchange missing base ALTC
Exchange coinexchange missing base YOC
Exchange coinexchange missing base ANI
Exchange coinexchange missing base CAB
Exchange coinexchange missing base PAL
Exchange coinexchange missing base STRB
Exchange coinexchange missing base HAL
Exchange coinexchange missing base MEA
Exchange coinexchange missing base ORB
Exchange coinexchange missing base XCO
Exchange coinexchange missing base CC
Exchange coinexchange missing base CYT
Exchange coinexchange missing base MNM
Exchange coinexchange missing base COXST
Exchange coinexchange missing base CMT
Exchange coinexchange missing base SCT
Exchange coinexchange missing base HVCO
Exchange coinexchange missing base BLU
Exchange coinexchange missing base SCN
Exchange coinexchange missing base DLC
Exchange coinexchange missing base XBTS
Exchange coinexchange missing base STC_OL
Exchange coinexchange missing base USC
Exchange coinexchange missing base MIU
Exchange coinexchange missing base YOVI
Exchange coinexchange missing base XVE
Exchange coinexchange missing base PULSE
Exchange coinexchange missing base GAM
Exchange coinexchange missing base PRO
Exchange coinexchange missing base CLD
Exchange coinexchange missing base OXY
Exchange coinexchange missing base SICOLD
Exchange coinmarketcap missing quote AUD
Exchange coinmarketcap missing quote BRL
Exchange coinmarketcap missing quote CAD
Exchange coinmarketcap missing quote CHF
Exchange coinmarketcap missing quote CNY
Exchange coinmarketcap missing quote EUR
Exchange coinmarketcap missing quote GBP
Exchange coinmarketcap missing quote HKD
Exchange coinmarketcap missing quote IDR
Exchange coinmarketcap missing quote INR
Exchange coinmarketcap missing quote JPY
Exchange coinmarketcap missing quote KRW
Exchange coinmarketcap missing quote MXN
Exchange coinmarketcap missing quote RUB
Exchange coinmarketcap missing quote USD
Exchange tidex missing base WETT
Exchange tidex missing base EETT
Exchange tidex missing base MGO
Exchange tidex missing base WSUR
Exchange tidex missing base INPAY

**Comment by kroitor** [comment]
Alright, on the coinexchange, you basically listed the inactive markets, but the proper way of listing them would be:

```Python
import ccxt
from pprint import pprint
exchange = ccxt.coinexchange()
exchange.load_markets()
pprint([symbol for symbol in exchange.markets if not exchange.markets[symbol]['active']])
```

Output:

[u'GAM/ETH', u'XYOC/BTC', u'XMRG/ETH', u'STRB/BTC', u'LOOT/BTC', u'USC/BTC', u'HVCO/BTC', u'XBTS/BTC', u'REV/BTC', u'LVPS/ETC', u'WYV/BTC', u'CLD/ETH', u'VONE/ETH', u'STRB/DOGE', u'ANI/BTC', u'BLU/BTC', u'XCS/BTC', u'CMT/BTC', u'ENTRC/ETH', u'PWR/BTC', u'GLTC/BTC', u'HONEY/ETC', u'AI/ETH', u'VOX/ETC', u'DOLLAR/BTC', u'XYOC/LTC', u'MNM/BTC', u'XMRG/BTC', u'KUBO/DOGE', u'SYS/BTC', u'BITZ/BTC', u'CC/BTC', u'MEA/BTC', u'PULSE/BTC', u'B3/BTC', u'ARGUSOLD/BTC', u'CREVA2/BTC', u'CLD/BTC', u'YOC/BTC', u'LTG/ETH', u'STC_OL/BTC', u'FOOT/BTC', u'ERA/ETC', u'SICOLD/BTC', u'AMS/BTC', u'LTG/BTC', u'CAB/BTC', u'HAL/BTC', u'YOVI/BTC', u'XVE/BTC', u'PIE/BTC', u'PCM/BTC', u'DLC/BTC', u'COXST/BTC', u'GAM/BTC', u'AI/BTC', u'GP/ETC', u'SCOREOLD/BTC', u'KUBO/BTC', u'XYOC/ETC', u'ALTC/BTC', u'PRO/BTC', u'PWR/DOGE', u'OXY/BTC', u'SCT/BTC', u'ORB/BTC', u'SCN/BTC', u'XCO/BTC', u'CYT/BTC', u'VONE/BTC', u'GOKUOLD/BTC', u'ENTRC/BTC', u'CHESS/BTC', u'PAL/BTC', u'MIU/BTC']

↑ These are all the same symbols that you've listed above, so there's no wonder they're missing in currencies – those markets aren't active anymore.

**Comment by kroitor** [comment]
The Tidex inconsistencies were fixed in ccxt 1.11.141

**Comment by gabemahoney** [comment]
Thank you, I was not aware of the market `active` key. I modified the script so that it would check for active, and if it was False, disregard the market. The script still finds a number of missing symbols in CoinmarketCap and Tidex (just FYI). Thanks for all the help!

```d = {'base':[],'quote':[]}
for e in ccxt.exchanges:
    exchange = getattr (ccxt, e)()
    try:
        exchange.load_markets()
    except:
        # can't load some exchanges without an API key so skip them
        continue

    for market in exchange.markets:
        try:
            active = exchange.markets[market]['active']
        except KeyError:
            # if 'active' key does not exist, assume active
            active = True
        if active:
            base_key = exchange.markets[market]['base']
            try:
                exchange.currencies[base_key]
            except KeyError:
                if base_key not in d['base']:
                    d['base'].append(base_key)
                    print("Exchange %s missing base %s" % (e, base_key))
            quote_key = exchange.markets[market]['quote']
            try:
                exchange.currencies[quote_key]
            except KeyError:
                if quote_key not in d['quote']:
                    d['quote'].append(quote_key)
                    print("Exchange %s missing quote %s" % (e, quote_key))```

OUTPUT:
Exchange coinmarketcap missing quote AUD
Exchange coinmarketcap missing quote BRL
Exchange coinmarketcap missing quote CAD
Exchange coinmarketcap missing quote CHF
Exchange coinmarketcap missing quote CNY
Exchange coinmarketcap missing quote EUR
Exchange coinmarketcap missing quote GBP
Exchange coinmarketcap missing quote HKD
Exchange coinmarketcap missing quote IDR
Exchange coinmarketcap missing quote INR
Exchange coinmarketcap missing quote JPY
Exchange coinmarketcap missing quote KRW
Exchange coinmarketcap missing quote MXN
Exchange coinmarketcap missing quote RUB
Exchange coinmarketcap missing quote USD
Exchange tidex missing base WETT
Exchange tidex missing base EETT
Exchange tidex missing base MGO
Exchange tidex missing base WSUR
Exchange tidex missing base INPAY

**Comment by kroitor** [comment]
@gabemahoney 

> The script still finds a number of missing symbols in CoinmarketCap and Tidex (just FYI).

As for Tidex, did you update ccxt to version 1.11.141? It should be fixed for the currencies you mentioned...
