### ISSUE TITLE
Kucoin: No fee information in watchMyTrades since 4.3.54

### ISSUE THREAD

**Issue by mjwvb** [ccxt/ccxt#23057]
### Operating System

Ubuntu

### Programming Languages

JavaScript

### CCXT Version

4.3.57

### Description

Since an overhaul of watchMyTrades on Kucoin I don't receive fee information on my trades anymore. The watch method used the /spot/tradeFills websocket topic of kucoin which provides the fee info, in contrary to the /spotMarket/tradeOrders topic which is used now. Is there a reason behind the topic switch?

My trading bot is fully dependent on the fee information, so I have to rollback to 4.3.53 now.

See:
https://github.com/ccxt/ccxt/pull/22918
https://github.com/ccxt/ccxt/commit/d9850ff01b077f9e4301c2bfe3a2749cd1b395fd

**Comment by samgermain** [comment]
We needed to update the endpoint used for retrieving trade data because the old endpoint was no longer documented online, unfortunately, it looks like kucoin no longer provides fee information on the endpoint used for retrieving trade data

As a work around, you could call `fetchMyTrades` every time that you receive an update from `watchMyTrades`, but yes I know that this would be more inconvenient

**Comment by mjwvb** [comment]
It's indeed hard to support an undocumented topic/endpoint, so I understand. Is it an idea to implement an "unsafe" version of watchMyTrades that uses the old topic, as a non-default parameter to the watch method? My bot is dependent on doing quick trades in a very short amount of time. I really cannot afford any additional wait time because of an extra call to fetchMyTrades.

**Comment by mjwvb** [comment]
Also, is there a procedure in place within ccxt to mark and communicate a change as a breaking change? I looked at the changelog to carefully check whether it is safe for me to update, and I assumed so. However the very next transaction of my bot went wrong and everything went in safe mode. All-in-all no losses though, but I can imagine that some ccxt users can get into major trouble. Especially when a trade depends on the result-after-fees of another trade, part of a whole chain of trades.

**Comment by samgermain** [comment]
> Also, is there a procedure in place within ccxt to mark and communicate a change as a breaking change? I looked at the changelog to carefully check whether it is safe for me to update, and I assumed so. However the very next transaction of my bot went wrong and everything went in safe mode. All-in-all no losses though, but I can imagine that some ccxt users can get into major trouble. Especially when a trade depends on the result-after-fees of another trade, part of a whole chain of trades.

There is, we're supposed to mark our commit messages with `fix!` when it's a breaking change, but it looks like that wasn't done in this case

**Comment by mjwvb** [comment]
Ah great, thanks for implementing the alternative method!

**Comment by mjwvb** [comment]
@samgermain @carlosmiei I tested it on 4.3.60 and it doesn't work yet with { method: "/spot/tradeFills" }. The trade result is still the order match version (type = match, etc), so no fee information. I did some console logging in the ccxt code and the topic var really seems to be /spot/tradeFills, so I don't where it goes wrong from there.

Also two things when reviewing the code:
```
        const defaultMethod = this.safeString(params, 'method', '/spotMarket/tradeOrders');
        const topic = (defaultMethod !== undefined) ? defaultMethod : this.safeString(options, 'method');
```
The above code causes the defaultMethod to be always defined due to the default parameter, so you cannot pass the method parameter to the global exchange watchMyTrades options.

Second thing: I looked at the parseWsTrade() function and it looks like it doesn't do a conversion between the two types of trade results. matchPrice/matchSize are not in the /spot/tradeFills trade response and should be price/size in that case.

**Comment by samgermain** [comment]
> @samgermain @carlosmiei I tested it on 4.3.60 and it doesn't work yet with { method: "/spot/tradeFills" }. The trade result is still the order match version (type = match, etc), so no fee information. I did some console logging in the ccxt code and the topic var really seems to be /spot/tradeFills, so I don't know where it goes wrong from there.
> 
> Also two things when reviewing the code:
> 
> ```
>         const defaultMethod = this.safeString(params, 'method', '/spotMarket/tradeOrders');
>         const topic = (defaultMethod !== undefined) ? defaultMethod : this.safeString(options, 'method');
> ```
> 
> The above code causes the defaultMethod to be always defined due to the default parameter, so you cannot pass the method parameter to the global exchange watchMyTrades options.
> 
> Second thing: I looked at the parseWsTrade() function and it looks like it doesn't do a conversion between the two types of trade results. matchPrice/matchSize are not in the /spot/tradeFills trade response and should be price/size in that case.

Sorry, fixed in https://github.com/ccxt/ccxt/pull/23078

**Comment by mjwvb** [comment]
@samgermain ok nice, but that only fixes the defaultMethod issue right?

**Comment by samgermain** [comment]
> @samgermain ok nice thanks! But that only fixes the defaultMethod issue right?

it's fixes both issues
