### ISSUE TITLE
Bitso API changed from api.bitso.com to bitso.com/api

### ISSUE THREAD

**Issue by Velcorn** [ccxt/ccxt#23054]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.3.59

### Description

Title basically says it all, Bitso made a minor change to their API URL which breaks the exchange. Would've created a pull request, but that might've been more work for both sides, lol

### Code

```
  

```

**Comment by carlosmiei** [comment]
@Velcorn How can we reproduce the issue? Locally seems to be working

```
CCXT v4.3.58
bitso.fetchTicker (BTC/USD)
Debugger ending on ws://127.0.0.1:59231/b72233f9-b4be-4236-b021-19b34dfe6f34
For help, see: https://nodejs.org/en/docs/inspector
2024-07-11T13:27:32.335Z iteration 0 passed in 2160 ms

{
  symbol: 'BTC/USD',
  timestamp: 1720704451000,
  datetime: '2024-07-11T13:27:31.000Z',
  high: 59392,
  low: 57101,
  bid: 58710,
  ask: 58748,
  vwap: 57748.4521951256,
  close: 58707,
  last: 58707,
  baseVolume: 23.92917729,
  quoteVolume: 1381872.95080025,
  info: {
    high: '59392',
    last: '58707',
    created_at: '2024-07-11T13:27:31+00:00',
    book: 'btc_usd',
    volume: '23.92917729',
    vwap: '57748.4521951256',
    low: '57101',
    ask: '58748',
    bid: '58710',
    change_24: '1277',
    rolling_average_change: { '6': '0.2374' }
  }
}
```

**Comment by samgermain** [comment]
> @Velcorn How can we reproduce the issue? Locally seems to be working
> 
> ```
> CCXT v4.3.58
> bitso.fetchTicker (BTC/USD)
> Debugger ending on ws://127.0.0.1:59231/b72233f9-b4be-4236-b021-19b34dfe6f34
> For help, see: https://nodejs.org/en/docs/inspector
> 2024-07-11T13:27:32.335Z iteration 0 passed in 2160 ms
> 
> {
>   symbol: 'BTC/USD',
>   timestamp: 1720704451000,
>   datetime: '2024-07-11T13:27:31.000Z',
>   high: 59392,
>   low: 57101,
>   bid: 58710,
>   ask: 58748,
>   vwap: 57748.4521951256,
>   close: 58707,
>   last: 58707,
>   baseVolume: 23.92917729,
>   quoteVolume: 1381872.95080025,
>   info: {
>     high: '59392',
>     last: '58707',
>     created_at: '2024-07-11T13:27:31+00:00',
>     book: 'btc_usd',
>     volume: '23.92917729',
>     vwap: '57748.4521951256',
>     low: '57101',
>     ask: '58748',
>     bid: '58710',
>     change_24: '1277',
>     rolling_average_change: { '6': '0.2374' }
>   }
> }
> ```

[It looks like that's the updated url](https://docs.bitso.com/bitso-api/docs/set-up-your-testing-environment), but the old url still works, it's probably just deprecated and undocumented now

**Comment by carlosmiei** [comment]
@samgermain Ok I think we can update it then, will do it.
