### ISSUE TITLE
Do CCXT support xt.com?

### ISSUE THREAD

**Issue by chaedongyoon** [ccxt/ccxt#23052]
### Operating System

python

### CCXT Version

recent

### Description

I don't know how to start,

import ccxt.pro as ccxtpro
exchange = ccxtpro.xt.com? 
how to use XT.com?
please help me

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @chaedongyoon yes it does, as long as you have an updated version of ccxt.

If you don't know how to start please read our manual top to bottom and check some examples.

- https://docs.ccxt.com/
- https://github.com/ccxt/ccxt/tree/master/examples/py
