### ISSUE TITLE
Bybit /v5/order/cancel-batch api 404 error 

### ISSUE THREAD

**Issue by cozy-hn** [ccxt/ccxt#23050]
### Operating System

IOS

### Programming Languages

JavaScript

### CCXT Version

"ccxt": "^4.3.55"

### Description

HELP ME.... I wanna use bybit cancelOrdersForSymbols method :(

fetch Request:
 bybit POST https://api.bybit.com/v5/order/cancel-batch 
RequestHeaders:
 {
  'Content-Type': 'application/json',
  'X-BAPI-API-KEY': 'X-BAPI-API-KEY',
  'X-BAPI-TIMESTAMP': '1720686123954',
  'X-BAPI-RECV-WINDOW': '5000',
  'X-BAPI-SIGN': 'X-BAPI-SIGN',
  Referer: 'CCXT'
} 
RequestBody:
 {"category":"linear","request":[{"symbol":"BTCUSDT","orderId":"123"}]} 

handleRestResponse:
 bybit POST https://api.bybit.com/v5/order/cancel-batch 404 Not Found 
ResponseHeaders:
 {
  Connection: 'keep-alive',
  'Content-Length': '0',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Thu, 11 Jul 2024 08:22:04 GMT',
  Server: 'Openresty',
  Timenow: '1720686124068',
  Traceid: '0b18d6a7a718ce2651d32343dbb77e8f',
  Via: '1.1 6a573f63f90ae3344d8f988dfdd87c76.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': '8DiC4xk7VMetRwvWkVszV9zkNxi1MbOSKMFM8ooTSQsVrhnSHu21fw==',
  'X-Amz-Cf-Pop': 'ICN51-C2',
  'X-Cache': 'Error from cloudfront',
  'X-Cld-Src': 'Loc-A'
} 

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @cozy-hn,

How are you calling `cancelOrdersForSymbols`?

**Comment by carlosmiei** [comment]
@cozy-hn I just tested it and it worked

```
p bybit cancelOrdersForSymbols '[{"id":"f302e22b-45e7-4449-979a-f1a539480a11", "symbol":"LTC/USDT:USDT"}, {"id":"f302e22b-45e7-4449-979a-f1a539480a11", "symbol":"LTC/USDT:USDT"}]' --sandbox
Python v3.12.3
CCXT v4.3.59
bybit.cancelOrdersForSymbols([{'id': 'f302e22b-45e7-4449-979a-f1a539480a11', 'symbol': 'LTC/USDT:USDT'}, {'id': 'f302e22b-45e7-4449-979a-f1a539480a11', 'symbol': 'LTC/USDT:USDT'}])
[{'amount': None,
  'average': None,
  'clientOrderId': None,
  'cost': None,
  'datetime': None,
  'fee': None,
  'fees': [],
  'filled': None,
  'id': 'f302e22b-45e7-4449-979a-f1a539480a11',
  'info': {'category': 'linear',
           'orderId': 'f302e22b-45e7-4449-979a-f1a539480a11',
           'orderLinkId': '',
           'symbol': 'LTCUSDT'},
  'lastTradeTimestamp': None,
  'lastUpdateTimestamp': None,
  'postOnly': None,
  'price': None,
  'reduceOnly': None,
  'remaining': None,
  'side': None,
  'status': None,
  'stopLossPrice': None,
  'stopPrice': None,
  'symbol': 'LTC/USDT',
  'takeProfitPrice': None,
  'timeInForce': None,
  'timestamp': None,
  'trades': [],
  'triggerPrice': None,
  'type': None},
 {'amount': None,
  'average': None,
  'clientOrderId': None,
  'cost': None,
  'datetime': None,
  'fee': None,
  'fees': [],
  'filled': None,
  'id': 'f302e22b-45e7-4449-979a-f1a539480a11',
  'info': {'category': 'linear',
           'orderId': 'f302e22b-45e7-4449-979a-f1a539480a11',
           'orderLinkId': '',
           'symbol': 'LTCUSDT'},
  'lastTradeTimestamp': None,
  'lastUpdateTimestamp': None,
```

**Comment by cozy-hn** [comment]
```
const Results = await bybit.cancelOrdersForSymbols([{"symbol":"ETHUSDT","id:"da90ef2b-1d84-4ee4-89ab-ff96122a9000"}]);
```
@carlosmiei 
I called the function like this. 
cancelOrder and other functions works, but only this method cancelOrdersForSymbols doesn't work. And I'm using typescript.

**Comment by cozy-hn** [comment]
@carlosmiei 

I tried creating a subaccount that is a UTA account and it works. Non-UTA account can't use this api, why don't you drop the version to v3?

**Comment by carlosmiei** [comment]
@cozy-hn The v3 support will be dropped very soon so I would suggest upgrading to UTA

https://announcements.bybit.com/en/article/important-api-update-transition-from-open-api-v3-to-open-api-v5-blt07c25e4e6f734fee/

**Comment by cozy-hn** [comment]
@carlosmiei 
Oh no... Thanks for the info. But I still think it's problematic that this method doesn't work for non-UTA accounts. I'd like to inform the Bybit team about this issue, do you know where I should go?
