### ISSUE TITLE
Cobinhood Exchange not working

### ISSUE THREAD

**Issue by vidur149** [ccxt/ccxt#2306]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Ubuntu 14.04
- Programming Language version: Javascript
- CCXT version: 1.10
- Exchange: cobinhood
- Method: new ccxt

new ccxt['cobinhood']({enableRateLimit:false, timeout: timeout})

throws an error of constructor not defined.

**Comment by kroitor** [comment]
@vidur149 your version of ccxt is too old...
