### ISSUE TITLE
Bybit watchLiquidations bybit safeMarket() -> disambiguate between different markets with the same market id

### ISSUE THREAD

**Issue by Podolchak** [ccxt/ccxt#23080]
### Operating System

Macos

### CCXT Version

PRO 4.3.61

### Description

bybit safeMarket() requires a fourth argument for BTCUSDT to disambiguate between different markets with the same market id

### Code

```js
const exchange = new exchangeClass({
  apiKey: config.exchange.key,
  secret: config.exchange.secret,
  enableRateLimit: true,
  newUpdates: true,
  options: {
    OHLCVLimit: 15000,
    ws: {
      timeout: 30000,
      pingTimeout: 10000,
      maxListeners: 1000,
    },
    streaming: {
      keepAlive: 18000,
    },
  },
})
  const liq = await exchange.watchLiquidations('BTC/USDT:USDT', undefined,undefined,{ channel_type: 'linear' })
  console.log(liq)
```

**Comment by carlosmiei** [comment]
Hello @Podolchak,

Thanks for reporting it, we will take a look.

**Comment by carlosmiei** [comment]
@Podolchak Can you please update your ccxt version and try again? I believe it should be working now

**Comment by Podolchak** [comment]
> @Podolchak Can you please update your ccxt version and try again? I believe it should be working now

It works, thank you!
