### ISSUE TITLE
TypeError("can't pickle _thread.RLock objects",),)

### ISSUE THREAD

**Issue by craigt1212** [ccxt/ccxt#2308]
- OS: Mac OS Sierra
- Programming Language version: Python3
- CCXT version: 1.11.137
- Exchange: Binance
- Method: load_markets()

Since upgrading from 1.10.1056 to 1.11.137, I am no longer able to serialize binance.load_markets() using pickle. I get the following error:
(TypeError("can't pickle _thread.RLock objects",),)
When I revert the version back to 1.10.1056, it works. 
Here is example code.
```
binance = ccxt.binance()
binance.load_markets()
pickle.dumps(binance))
```

**Comment by frosty00** [comment]
Nothing to do with ccxt, but rather your implementation. Threading is not used in our library. @kroitor  you can close.
