### ISSUE TITLE
cannot find the open interest in option Binance

### ISSUE THREAD

**Issue by ChangeGod** [ccxt/ccxt#23096]
### Programming Languages

Python

### CCXT Version

ccxt.pro

### Description

Hello, I try to get data option open interest from binance, but all fetch is not export anything, could someone please help me?

### Code

<img width="188" alt="Screenshot 2024-07-14 114337" src="https://github.com/user-attachments/assets/d92d0b20-a530-4f8b-b0ee-c83113ac0f78">

**Comment by sc0Vu** [comment]
@ChangeGod Which function did you use?

**Comment by ChangeGod** [comment]
I use fetch_ticker, fetch_option, and fetch_greeks

**Comment by ChangeGod** [comment]
> @ChangeGod Which function did you use?

I use fetch_ticker, fetch_option, and fetch_greeks

**Comment by sc0Vu** [comment]
@ChangeGod It seems there's no openInterest in the api response.

https://developers.binance.com/docs/derivatives/option/market-data/24hr-Ticker-Price-Change-Statistics

https://developers.binance.com/docs/derivatives/option/market-data/Option-Mark-Price

I think you need to call `fetchOpenInterest` function instead.

BTW, is there `BTC-240736-54000-C` in binance (https://www.binance.com/en/eoptions/BTCUSDT)?

**Comment by ChangeGod** [comment]
> @ChangeGod It seems there's no openInterest in the api response.
> 
> https://developers.binance.com/docs/derivatives/option/market-data/24hr-Ticker-Price-Change-Statistics
> 
> https://developers.binance.com/docs/derivatives/option/market-data/Option-Mark-Price
> 
> I think you need to call `fetchOpenInterest` function instead. You need to use unified-symbol in that function for now (I found and fixed a bug in that function: #23099, you can use after we merge and release.).
> 
> BTW, is there `BTC-240736-54000-C` in binance (https://www.binance.com/en/eoptions/BTCUSDT)?

thank you for let me know, I still dont see the option for fetchOpenInterest.
for your question BTC-240736-54000-C, we don't have it, we have BTC-240726-54000-C. I use the symbol from Deribit and change the structure symbol for running ccxt.binance. I'm looking the whole week to find the way get data from open interest, but no result. That make me find ccxt developer in github to figure out what I did wrong!

**Comment by ChangeGod** [comment]
> > @ChangeGod It seems there's no openInterest in the api response.
> > https://developers.binance.com/docs/derivatives/option/market-data/24hr-Ticker-Price-Change-Statistics
> > https://developers.binance.com/docs/derivatives/option/market-data/Option-Mark-Price
> > I think you need to call `fetchOpenInterest` function instead. You need to use unified-symbol in that function for now (I found and fixed a bug in that function: #23099, you can use after we merge and release.).
> > BTW, is there `BTC-240736-54000-C` in binance (https://www.binance.com/en/eoptions/BTCUSDT)?
> 
> thank you for let me know, I still dont see the option for fetchOpenInterest. for your question BTC-240736-54000-C, we don't have it, we have BTC-240726-54000-C. I use the symbol from Deribit and change the structure symbol for running ccxt.binance. I'm looking the whole week to find the way get data from open interest, but no result. That make me find ccxt developer in github to figure out what I did wrong!

Also I try the fetch_open_interest, I got no result :(

**Comment by ChangeGod** [comment]
This is my code
import ccxt
import pandas as pd

cex = ccxt.binance()



ex1 = cex.load_markets()


option_data_date = 'BTC-240726-53000-C' #bianance

ex3 = cex.fetch_open_interest(option_data_date)
df = pd.DataFrame(ex3)
df

**Comment by sc0Vu** [comment]
@ChangeGod There is a bug in current fetchOpenInterest, could you try to use our unified symbol `BTC/USDT:USDT-240726-53000-C`?

**Comment by ChangeGod** [comment]
> @ChangeGod There is a bug in current fetchOpenInterest, could you try to use our unified symbol `BTC/USDT:USDT-240726-53000-C` before we release? `cex.fetch_open_interest('BTC/USDT:USDT-240726-53000-C')`

<img width="744" alt="image" src="https://github.com/user-attachments/assets/e727ade3-36b3-4168-9813-1090d694e8b0">
This is the result after I run the script. In the Deribit, I use fetch_ticker, they show all information at Info

**Comment by ChangeGod** [comment]
> @ChangeGod There is a bug in current fetchOpenInterest, could you try to use our unified symbol `BTC/USDT:USDT-240726-53000-C` before we release? `cex.fetch_open_interest('BTC/USDT:USDT-240726-53000-C')`

Now its work, thanks for your help
<img width="751" alt="image" src="https://github.com/user-attachments/assets/197770ab-981d-4186-870d-f96f20e79a24">
