### ISSUE TITLE
AttributeError when using socks proxy

### ISSUE THREAD

**Issue by qbot955** [ccxt/ccxt#23098]
### Operating System

Windows, Ubuntu

### Programming Languages

Python

### CCXT Version

4.3.61

### Description

connector = ProxyConnector.from_url(
                ^^^^^^^^^^^^^^^^^^^^^^^^

proxy_type, host, port, username, password = parse_proxy_url(url)
                                                 ^^^^^^^^^^^^^^^^^^^^

parsed = urlparse(url)
             ^^^^^^^^^^^^^

    url, scheme, _coerce_result = _coerce_args(url, scheme)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^

    return _decode_args(args) + (_encode_result,)
           ^^^^^^^^^^^^^^^^^^

    return tuple(x.decode(encoding, errors) if x else '' for x in args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    return tuple(x.decode(encoding, errors) if x else '' for x in args)
                 ^^^^^^^^
AttributeError: 'tuple' object has no attribute 'decode'

### Code

```
exchange = ccxtpro.okx({
    'apiKey': '',
    'secret': '',
    'password': ''
})
exchange.socks_proxy = 'socks5://127.0.0.1:8081/',
exchange.ws_socks_proxy = 'socks5://127.0.0.1:8081/',


if __name__ == '__main__':
    asyncio.run(exchange.fetch_positions(exchange))

```

**Comment by sc0Vu** [comment]
@qbot955 Thanks for the report. Before we update, could you update code like we did in this example: https://github.com/ccxt/ccxt/blob/master/examples/py/proxy-asyncio-aiohttp-socks.py?

**Comment by sc0Vu** [comment]
@carlosmiei You're right, and I found the issue. @qbot955 Please remove the suffix *,* in these line.

```PYTHON
exchange.socks_proxy = 'socks5://127.0.0.1:8081/', // remove ,
exchange.ws_socks_proxy = 'socks5://127.0.0.1:8081/', // remove ,
```

**Comment by ttodua** [comment]
let us know if there is any issue. for now, seems to be closed.

**Comment by mr-timo** [comment]
Hi how can I do that in JavaScript am really stuck I try to run my code on a cloud machine but the cloud ip address is base on USA ip address and bybit  as restrict USA from there exchange activie's I there anything I could do that issue am not using ccxt pro am using (ccxt ) normal one can someone show me any examples how to do that

**Comment by ttodua** [comment]
> Hi how can I do that in JavaScript am really stuck I try to run my code on a cloud machine but the cloud ip address is base on USA ip address and bybit as restrict USA from there exchange activie's I there anything I could do that issue am not using ccxt pro am using (ccxt ) normal one can someone show me any examples how to do that

see: https://github.com/ccxt/ccxt/blob/master/examples/ts/proxy-usage.ts
