### ISSUE TITLE
Can't compile ccxt after 4.3.57 version

### ISSUE THREAD

**Issue by cozy-hn** [ccxt/ccxt#23100]
### Operating System

ios

### Programming Languages

typescript

### CCXT Version

4.3.57

### Description

I can't compile ccxt after 4.3.57 ver using nest.js because of this error.
I think because of this #22768 
```
[3:51:38 PM] Starting compilation in watch mode...

node_modules/ccxt/js/src/base/ws/Client.d.ts:8:19 - error TS2314: Generic type 'Dictionary<T>' requires 1 type argument(s).

8     messageQueue: Dictionary<string, any>;
                    ~~~~~~~~~~~~~~~~~~~~~~~

[3:51:41 PM] Found 1 error. Watching for file changes.
```

### Code

```
  

```

**Comment by sc0Vu** [comment]
@cozy-hn Thanks for the report. We'll fix this asap.

**Comment by carlosmiei** [comment]
@cozy-hn Can you please update your ccxt version and try again? should be working now
