### ISSUE TITLE
Kraken watchBalance support

### ISSUE THREAD

**Issue by calvin-nl** [ccxt/ccxt#23106]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

CCXT pro doesn't currently support `watchBalance` with kraken. However, it looks like Kraken's websocket v2 API does have a `balances` channel: https://docs.kraken.com/api/docs/websocket-v2/balances

### Describe the solution you'd like

Would be great if CCXT pro was able to support `watchBalance` for kraken using their v2 websocket API.

**Comment by 1alexbc1** [comment]
Shift u

**Comment by calvin-nl** [comment]
Thanks for the quick turnaround!
