### ISSUE TITLE
fetch wrong data when use fetch_open_interest

### ISSUE THREAD

**Issue by ChangeGod** [ccxt/ccxt#23110]
### Operating System

Window

### Programming Languages

Python

### Description

When I try to fetch_open_interest the data export wrong symbol, this is my code:

<img width="883" alt="image" src="https://github.com/user-attachments/assets/e82ad88d-e7de-487b-9c01-091de565f142">

### Code

```import ccxt
import pandas as pd


# Initialize the Binance exchange
cex = ccxt.binance()


# Load markets to get the available options
ex1 = cex.load_markets()
ex2 = cex.fetch_markets()

option_data_date = 'BTC/USDT:USDT-240719-66000-P' #bianance

ex3 = cex.fetch_open_interest(option_data_date)

df = pd.DataFrame(ex3)
# print(df)
select = ['info']
df_select = df[select]
print(df_select)
  

```

**Comment by sc0Vu** [comment]
@ChangeGod That symbol in the info represents the exchange identifier. And the symbol you used is our unified symbol. It would be the same as `result['symbol']`. Let us know if you have any issues.

**Comment by ChangeGod** [comment]
> @ChangeGod That symbol in the info represents the exchange identifier. And the symbol you used is our unified symbol. It would be the same as `result['symbol']` (https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids).
> 
> Let us know if you have any issues.

Thank you for your support, I just try to figure how to fetch open interest data, for example with the symbol BTC/USDT:USDT-240719-66000-P. Any idea or anyway I can get that data?

**Comment by sc0Vu** [comment]
@ChangeGod You're right, the data symbol supposed to be the symbol of symbol `BTC/USDT:USDT-240719-66000-P`. We'll fix this asap.

**Comment by ChangeGod** [comment]
> @ChangeGod You're right, the data symbol supposed to be the symbol of symbol `BTC/USDT:USDT-240719-66000-P`. We'll fix this asap.

I'm really apricated your help. Looking for the patch update from you guys!

**Comment by ChangeGod** [comment]
Hello @sc0Vu any update?
