### ISSUE TITLE
Please add Bitbank (Japan) Exchange

### ISSUE THREAD

**Issue by unknown12345678** [ccxt/ccxt#2312]
Please add Bitbank exchange.

Bitbank is a Japanese exchange which is a big player much like Bitflyer and Coincheck. They currently have BTC, XRP, ETH, LTC, BCC and MONA listed.

Website
https://bitbank.cc

API Docs
https://docs.bitbank.cc/

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/issues/1252
- https://github.com/ccxt/ccxt/pull/1409

It is already implemented, now in testing stage, your help is appreciated, will be merged to the main branch soon.
