### ISSUE TITLE
Mexc WIthdrawal fail

### ISSUE THREAD

**Issue by chaedongyoon** [ccxt/ccxt#23125]
### Operating System

python, windows11

### CCXT Version

4.3.62

### Description

exchange = ccxt.mexc({
        'apiKey': '',
        'secret': ''})

    currency1 = 'XRP'  
    amount1 = '20000'    
    address1 = ""  
    tag1 = ""  

    result = exchange.withdraw(currency1, amount1, address1, tag1, params={"network": "XRP"})
    print(result)

then,
error msg is below
 File "c:\coding\withdraw.py", line 78, in <module>
    result = exchange.withdraw(currency1, amount1, address1, tag1, params={"network": "XRP"})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CDY\AppData\Roaming\Python\Python311\site-packages\ccxt\mexc.py", line 4925, in withdraw
    response = self.spotPrivatePostCapitalWithdraw(self.extend(request, params))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CDY\AppData\Roaming\Python\Python311\site-packages\ccxt\base\types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CDY\AppData\Roaming\Python\Python311\site-packages\ccxt\base\exchange.py", line 3756, in request
    return self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CDY\AppData\Roaming\Python\Python311\site-packages\ccxt\base\exchange.py", line 3752, in fetch2
    raise e
  File "C:\Users\CDY\AppData\Roaming\Python\Python311\site-packages\ccxt\base\exchange.py", line 3743, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CDY\AppData\Roaming\Python\Python311\site-packages\ccxt\base\exchange.py", line 667, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CDY\AppData\Roaming\Python\Python311\site-packages\ccxt\mexc.py", line 5368, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], responseCode, feedback)
  File "C:\Users\CDY\AppData\Roaming\Python\Python311\site-packages\ccxt\base\exchange.py", line 4138, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: mexc {"code":10232,"msg":"Coin is not exist","timestamp":1721227926981}

But Yes i have 20000xrp
and it is works very well, In old ccxt version

![xrp mexc](https://github.com/user-attachments/assets/58cf99bf-0128-44f7-b715-b7156477185e)

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @chaedongyoon, your ccxt version is slightly outdated. Can you please upgrade and try again?

**Comment by chaedongyoon** [comment]
> Hello @chaedongyoon, your ccxt version is slightly outdated. Can you please upgrade and try again?
my version is  "4.3.62 " 
![ccxt](https://github.com/user-attachments/assets/bca687d1-7d31-44ff-bff3-18067c5fadb3)

**Comment by carlosmiei** [comment]
@chaedongyoon Sorry I misread it, what's the "old" ccxt version that works? I can try to compare both

**Comment by chaedongyoon** [comment]
> @chaedongyoon Sorry I misread it, what's the "old" ccxt version that works? I can try to compare both

version "ccxt-4.3.45 " is posible to withdraw

**Comment by PythMen** [comment]
Hello, i have the same issue with SOL. I have the version 4.3.64.

**Comment by Kerrypinny** [comment]
Hello @PythMen 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID XRP07638
Please see the link below to our dedicated support line:
[XRP Support Requests ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by carlosmiei** [comment]
@chaedongyoon @PythMen Can you please update your ccxt version and try again? it should be working now
