### ISSUE TITLE
Still get the error from the symbol, I believe that is the bug from fetch_open_interest!

### ISSUE THREAD

**Issue by ChangeGod** [ccxt/ccxt#23133]
### Operating System

Window

### Programming Languages

Python

### CCXT Version

6.42

### Description

The issue still happening when I get wrong symbol data from fetch_open_Interest. I try to get data BTC/USDT:USDT-240719-66000-P but the result is BTC/USDT:USDT-240719-59000-P for binance exchange
<img width="904" alt="image" src="https://github.com/user-attachments/assets/94060b84-b6ca-4ae9-a7bd-c89a52f750ab">

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @ChangeGod

The patch PR was merged (https://github.com/ccxt/ccxt/pull/23114), however we don't release the new version yet (https://github.com/ccxt/ccxt/commits/master/). 

You can build the patch locally before we release the next version.

**Comment by ChangeGod** [comment]
Thanks @sc0Vu, I just first time use github so a lot of thing is new for me!
