### ISSUE TITLE
Bitmex: Amend order functionality?

### ISSUE THREAD

**Issue by cyclostationary** [ccxt/ccxt#2313]
Inspecting the editOrder function in ccxt looks like it just cancels and replaces an order - Bitmex (and probably others) have an amend functionality in the api to adjust certain parameters of a placed but not executed order. Is this possible in ccxt or no?

**Comment by cyclostationary** [comment]
I guess this is accomplished with the custom exchange api and i just do the post request manually. closing.

**Comment by ediaz** [comment]
@cyclostationary how would you do it again? Could you post an example?
Thanks

**Comment by cyclostationary** [comment]
@ediaz In python:

Creating the order and then amending it 
`result = bitmex.create_order('BTC/USD','limit',buyorselltype,amount,price)
bitmex.edit_order(result['id'],'BTC/USD','limit',result['side'],price=newprice)
`

For more info on the arguments to these see this https://github.com/ccxt/ccxt/blob/5eebeae82c0ac64c973dfa3e80e211a4ebf038b9/python/ccxt/async/bitmex.py

**Comment by ediaz** [comment]
thanks!
