### ISSUE TITLE
Bitstamp fetch_trades returning few results

### ISSUE THREAD

**Issue by Felipe-Mangueira** [ccxt/ccxt#2314]
- OS: Linux and Windows
- Programming Language version: Python 3.6
- CCXT version: 1.11.108
- Exchange: Bitstamp
- Method: fetch_trades

Hello @kroitor.

I'm facing difficulties to get consistent results from the Bitstamp fetch_trades method. I have debugged this method some hours ago and get just two trades as history from Bitstamp, like this:

´´´
[
    {
        'id': '59380478',
        'info': {'date': '1521511722', 'tid': '59380478', 'price': '8480.54', 'type': '1', 'amount': '0.00793520'},
        'timestamp': 1521511722000,
        'datetime': '2018-03-20T02:08:42.000Z',
        'symbol': 'BTC/USD',
        'order': None,
        'type': None,
        'side': 'sell',
        'price': 8480.54,
        'amount': 0.0079352
    },
    {
        'id': '59380464',
        'info': {'date': '1521511696', 'tid': '59380464', 'price': '8481.12', 'type': '1', 'amount': '0.07688912'},
        'timestamp': 1521511696000,
        'datetime': '2018-03-20T02:08:16.000Z',
        'symbol': 'BTC/USD',
        'order': None,
        'type': None,
        'side': 'sell',
        'price': 8481.12,
        'amount': 0.07688912
    }
]
´´´

However when I try to get the same results by calling requests.get('https://www.bitstamp.net/api/v2/transactions/btcusd/'), like the bitstamp documentation, the response is a very big dictionary. I prefer to use your library to make this sort of request, but I do not understand why the results are different between the two ways of getting the trades history. Am I missing something?

Thank you for your attention!

**Comment by kroitor** [comment]
> I have debugged this method some hours ago and get just two trades as history from Bitstamp

We really need to see full request-response in verbose output, can you please post this:

```Python
bitstamp.verbose = True
trades = bitstamp.fetch_trades(...) # your args
```

?

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by joh90** [comment]
@Felipe-Mangueira i think the issue is that if you call `fetch_trades` without parsing the `time` parameter, CCXT bitstamp defaults it to `minute` value for `time` parameter https://github.com/ccxt/ccxt/blob/master/python/ccxt/bitstamp.py#L346

In order to get the default, which is `hour` specified in their documentation,
you probably have to do something like
```
>>> len(bitstamp.fetch_trades('BTC/USD', params={'time': 'hour'}))
https://www.bitstamp.net/api/v2/transactions/btcusd/?time=hour
1512
>>> len(bitstamp.fetch_trades('BTC/USD'))
https://www.bitstamp.net/api/v2/transactions/btcusd/?time=minute
111```

**Comment by Felipe-Mangueira** [comment]
Hi, guys.

> We really need to see full request-response in verbose output, can you please post this:

@kroitor, it'll not be necessary, because @joh90 solved my problem. Sorry for disturbing you with a so trivial issue.

> CCXT bitstamp defaults it to minute value for time parameter 

I didn't notice the time parameter is setted to minute as default. Anyway, I wasn't setting any parameter, and that was my mistake.
Thanks @joh90 for the help!!

**Comment by joh90** [comment]
@Felipe-Mangueira, @kroitor made a commit here to set the default to `hour`, it should be in any versions after `1.11.143`

**Comment by Felipe-Mangueira** [comment]
Ok, @joh90... Thanks.
