### ISSUE TITLE
'timestamp': None for spot binance book ticker

### ISSUE THREAD

**Issue by Avarong** [ccxt/ccxt#23160]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.3.63

### Description

I get {'BCH/USDT': {'symbol': 'BCH/USDT', 'timestamp': None, 'datetime': None, 'high': None, 'low': None, 'bid': 391.1, 'bidVolume': 27.1, 'ask': 391.2, 'askVolume': 6.983, 'vwap': None, 'open': None, 'close': None, 'last': None, 'previousClose': None, 'change': None, 'percentage': None, 'average': None, 'baseVolume': None, 'quoteVolume': None, 'info': {'u': 7269204590, 's': 'BCHUSDT', 'b': '391.10000000', 'B': '27.10000000', 'a': '391.20000000', 'A': '6.98300000'}}}
when using watch_bids_asks() for spot. How can i get timestamp for spot binance book ticker?

### Code

```
      ex=ccxtpro.binance()
        book=await ex.watch_bids_asks(['BCH/USDT'])
        print(book)

```

**Comment by carlosmiei** [comment]
Hello @Avarong,
Unfortunately the timestamp is not provided by the exchange in this channel as you can see in the raw message

```
{"u":49065292445,"s":"BTCUSDT","b":"66526.00000000","B":"0.18986000","a":"66526.01000000","A":"14.00805000"}
```
