### ISSUE TITLE
Kraken support for fetchStatus

### ISSUE THREAD

**Issue by calvin-nl** [ccxt/ccxt#23177]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

Looks like CCXT doesn't support `fetchStatus` for kraken, although there appears to be a new kraken endpoint that can be used for it: https://docs.kraken.com/api/docs/rest-api/get-system-status

### Describe the solution you'd like

Would be great to see CCXT support `fetchStatus` for kraken.

**Comment by carlosmiei** [comment]
Hello @calvin-nl,

Thanks a lot for reporting it, we will take a look and implement it if possible.
