### ISSUE TITLE
Coins with same symbol across exchanges

### ISSUE THREAD

**Issue by dexter369** [ccxt/ccxt#2318]
Symbol: lux
c-cex : Luxmi
cryptopia : Luxcoin

Symbol: crc
c-cex : CoreCoin
cryptopia : CrowdCoin
livecoin : CryCash

Symbol: gdc
cryptopia : GrandCoin
coinexchange: GoldenCryptoCoin

**Comment by kroitor** [comment]
This is fixed in 1.11.158. Thanks for reporting!
