### ISSUE TITLE
Bybit's fetchBalance can't use the fund type

### ISSUE THREAD

**Issue by cozy-hn** [ccxt/ccxt#23191]
### Operating System

ios

### Programming Languages

JavaScript

### Description

If you are using Bybit's standard account, the current bybit's fetchbalance function changes the type to linear in getBybitType if you pass "params.type = fund" as an argument. To get the balance of a fund account, you need to specify params.subType as fund.

This method(use subtTpe) does not work for UTA accounts, as they have unifiedType specified as unified, making it impossible to check the amount of FUND using the current function.

The required changes involve too much logic and parent functions, which I cannot modify as a junior developer. Please help.

### Code

```
  

```

**Comment by cozy-hn** [comment]
Oh I update ccxt version and It's works thanks for fix about this!

**Comment by carlosmiei** [comment]
@cozy-hn No problem, just let us know if anything!
