### ISSUE TITLE
Binance async method doesn't work, meanwhile its sync version works just fine

### ISSUE THREAD

**Issue by abo-take** [ccxt/ccxt#23238]
### Operating System

Windows 11

### Programming Languages

Python

### CCXT Version

ccxt==4.3.68

### Description

I'm trying to fetch the balance for my account, it works with sync method, but doesn't work with async, why?

In sync version I got valid response, in async I got this error:  {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}

Sync version:
![image](https://github.com/user-attachments/assets/df2deae9-36c7-4117-8701-166015cd6d1d)

Async version:
![image](https://github.com/user-attachments/assets/d86dc620-9993-4409-b2fb-4c928044e342)

### Code

Sync version:
```
import ccxt

def fetch_balance():
    proxy = 'proxy'

    proxies = {
  "http": proxy,
  "https": proxy,
}

    exchange = ccxt.binance({
         'apiKey': 'api_key',
         'secret': 'api_secret',
         'proxies': proxies
    })
    exchange.load_markets()
    balance = exchange.fetch_balance()
    print(balance)

fetch_balance()

```
Async version:
```
import ccxt.async_support as ccxt
import asyncio

async def fetch_balance():
    proxy = 'proxy'

    proxies = {
  "http": proxy,
  "https": proxy,
}
    
    exchange = ccxt.binance({
         'apiKey': 'api_key',
         'secret': 'api_secret',
         'proxies': proxies
    })

    try:
        await exchange.load_markets()
        balance = await exchange.fetch_balance()
        print(balance)
        await exchange.close()
    except Exception as e:
        print(str(e))


asyncio.run(fetch_balance())
```

**Comment by carlosmiei** [comment]
Hello @abo-take,

That's not the unified way of setting up proxies, can you please check this out? https://docs.ccxt.com/#/README?id=proxy

In short you should be using `httpProxy/httpsProxy` in the config dictionary.

**Comment by abo-take** [comment]
Hi @carlosmiei,

Thank you for a quick reply. Appreciate it. 
Now async code works with the new proxy setting as you suggested, so I am closing this issue.

**Comment by carlosmiei** [comment]
@abo-take Awesome, let us know if anything!
