### ISSUE TITLE
Bybit fetchBalance makes call to /v5/asset/coin/query-info

### ISSUE THREAD

**Issue by ricardomatias** [ccxt/ccxt#23232]
### Operating System

Mac OS Ventura 13.6.7

### Programming Languages

JavaScript

### CCXT Version

4.3.68

### Description

As title says, when trying to fetch a balance and having verbose enabled I see a call the following:
`bybit GET https://api-demo.bybit.com/v5/asset/coin/query-info? 200 OK`

And then I get the following error from the exchange:
`{"retCode":10032,"retMsg":"Demo trading are not supported.","result":{},"retExtInfo":{},"time":1722068066612}`

### Code

```ts
const exchangeClass = exchanges[broker];
const exchange = new exchangeClass({
	apiKey,
	secret: apiSecret,
	verbose: true,
	options: {
		fetchBalance: {
			coin: "USDT",
			accountType: "UNIFIED",
		},
	},
});

exchange.setSandboxMode(true);

if (exchange instanceof bybit) {
	exchange.options.defaultType = "future";

	exchange.urls["api"] = {
		spot: "https://api-demo.bybit.com",
		futures: "https://api-demo.bybit.com",
		v2: "https://api-demo.bybit.com",
		public: "https://api-demo.bybit.com",
		private: "https://api-demo.bybit.com",
	};
}

const balance = await exchange.fetchBalance({ type: "future"});
```

**Comment by carlosmiei** [comment]
Hello @ricardomatias 

CCXT initially performs some calls to load and cache the markets and the currencies available at the exchange. In this case,  that endpoint is not available in the demo trading but ccxt it handles it properly as long as you enable the sandbox mode (you don't need to override the `urls`)

Example:

```Python
exchange.set_sandbox_mode(True)
balance = await exchange.fetch_balance()
```

**Comment by ricardomatias** [comment]
Hello @carlosmiei, understood and working!
