### ISSUE TITLE
Correct Wiki Link For Anchor #orders-cache

### ISSUE THREAD

**Issue by adlai** [ccxt/ccxt#23237]
### Operating System

_HTML5_

### Programming Languages

_HTML5_

### CCXT Version

_Not relevant_

### Description

1. Go to the [wiki](https://github.com/ccxt/ccxt/wiki/#how-to-use)
2. Scroll through `Private API -> Orders -> Querying Orders`
3. Click on ` -> .orders cache` ; there is no  corresponding anchor for the link!

Judging by the document structure, the correct anchor is `#understanding-the-orders-api-design`, although I can't fix this due to not having permissions to edit your wiki.

**Comment by sc0Vu** [comment]
Thank, we'll update this asap.

**Comment by adlai** [comment]
I'm not reopening, as the dead link is now gone; however, I'm severely unsure how to proceed, beyond trolling through the entire documentation wiki for innumerable nameless references to cache invalidation!

However, thank you for the prompt removal of the dead link.
