### ISSUE TITLE
Hyperliquid fetch_ohlcv limit issue

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#23243]
### Operating System

N/A

### Programming Languages

Python

### CCXT Version

4.3.67

### Description

Hello,

The Hyperliquid api returns the most recent 5000 candles. However, in ccxt `hyperliquid.py` the default limit is set to 500, which makes it output the first 500 of the most recent 5000. I'm not sure if that is expected behaviour? It makes it difficult to fetch the last 100 candles for example. First I'd have to know the Hyperliquid API limit of 5000 and pass that to fetch_ohlcv, and then I'd have to grab the last 100 candles. A better way would be to raise the `hyperliquid.py` limit to 5000, or to change how the default 'limit' behaves and make it show the latest 500 cancles instead of the first.. although that could maybe have unwanted consequences in other use-cases.

thanks

### Code

```
e = ccxt.hyperliquid()
candles = await e.fetch_ohlcv('PURR/USDC', '1h')
print(datetime.fromtimestamp(candles[-1][0] / 1000, UTC).strftime('%Y-%m-%d %H:%M:%S'), candles[-1])
candles = await e.fetch_ohlcv('PURR/USDC', '1h', limit=5000)
print(datetime.fromtimestamp(candles[-1][0] / 1000, UTC).strftime('%Y-%m-%d %H:%M:%S'), candles[-1])
await e.close()
```

```
2024-05-06 23:00:00 [1715036400000, 0.10898, 0.11004, 0.10896, 0.10897, 187805.0]
2024-07-28 22:00:00 [1722204000000, 0.19948, 0.19948, 0.19947, 0.19948, 30982.0]
```

**Comment by sc0Vu** [comment]
@gaardiolor Thanks for the report. I think they update documentation and api quickly  https://web.archive.org/web/20240321075443/https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/info-endpoint#retrieve-a-users-fills (didn't mention a couple of months ago). The limit probably worked before.

Anyway, we'll update asap.

**Comment by gaardiolor** [comment]
hm, actually their documentation seems to be inconsistent with their api behaviour, and they return more than the documented 5000. For example, the 1m timeframe at 01:14 CEST returns 5104 candles, at 01:20 CEST it returns 5110. 

```
ts=1m
curl -s -X POST https://api.hyperliquid.xyz/info -H "Content-Type: application/json" -H "User-Agent: python-requests/2.30.0" -H "Accept-Encoding: gzip, deflate, br" -H "Accept: */*" -H "Connection: keep-alive" -d '{"type":"candleSnapshot","req":{"coin":"PURR/USDC","interval":"'"$ts"'","startTime":0,"endTime":'`date +%s`'000}}' | jq ".|length"
5104
```

would it be better to by default have no limit at all ? Or to set it to be significantly higher, eg 10000 ?

**Comment by gaardiolor** [comment]
nevermind, the limit was removed in this commit https://github.com/ccxt/ccxt/commit/9d3a9272978de05917d2fa0392ab9f528963d074

**Comment by harvis-alpha** [comment]
Hey @gaardiolor, the CCXT default was fixed but HL still caps at 5,000 candles — which limits backtesting to ~3.5 days of 1m data. We built [TikTape](https://tiktape.xyz) to go beyond that: full OHLCV history from 2025, all markets, all intervals. $19/mo for unlimited candles, up to 10,000 per request. Happy to help!
