### ISSUE TITLE
BTCBox sign changes

### ISSUE THREAD

**Issue by xuetong6** [ccxt/ccxt#23246]
### Programming Languages

JavaScript

### CCXT Version

4.3.68

### Description

Comparison between version 1.76.26 and version 4.3.68 in btcbox.js
In the sign method, sha256.sha256 was added, resulting in an error in comparing with our database

### Code

1.76.26
```
const secret = this.hash (this.encode (this.secret));
query['signature'] = this.hmac (this.encode (request), this.encode (secret));
```
4.3.68
```
const secret = this.hash(this.encode(this.secret), sha256.sha256);
query['signature'] = this.hmac(this.encode(request), this.encode(secret), sha256.sha256);
  
```

**Comment by carlosmiei** [comment]
Hello @xuetong6, what's the issue exactly?

**Comment by xuetong6** [comment]
The values for the new version of ccxt are different
Added sha256.sha256

**Comment by xuetong6** [comment]
![Uploading aa.png…]()

**Comment by xuetong6** [comment]
<img width="1128" alt="image" src="https://github.com/user-attachments/assets/10e75f78-b85d-49b6-87da-e460c822c66e">

**Comment by carlosmiei** [comment]
@xuetong6 But did that break the signature?

**Comment by xuetong6** [comment]
> @xuetong6但这是否破坏了签名？

We want to use the old version of the signature method
<img width="1028" alt="image" src="https://github.com/user-attachments/assets/2b91df35-926d-4912-8943-532226d0a684">

**Comment by carlosmiei** [comment]
@xuetong6 I cannot test this exchange because I don't have apiKeys, so I'm asking if the current implementation is broken or not. We can't go back to the "previous" code because the function was refactored, and now we need to explicitly provide a hash function. So my question is, should we replace sha256, with md5?

**Comment by carlosmiei** [comment]
The docs seem to suggest that 

https://blog.btcbox.jp/en/archives/8762#toc9
![image](https://github.com/user-attachments/assets/efdfa841-788f-4937-bcf4-e120433c5cc2)

**Comment by xuetong6** [comment]
I want to know if changing the hash to md5 is the same as this output result
Or you can tell me how to modify it, I will make the necessary changes locally
<img width="1114" alt="image" src="https://github.com/user-attachments/assets/cd4928f3-79e8-4184-b051-4371dcc956c0">

**Comment by carlosmiei** [comment]
@xuetong6 I just merged a fix to restore the md5 usage. We will release a new version with the patch shortly

**Comment by carlosmiei** [comment]
@xuetong6 if you're building from the source you can already pull the latest version of master

**Comment by xuetong6** [comment]
> @xuetong6 if you're building from the source you can already pull the latest version of master

Okay, thank you very much
