### ISSUE TITLE
error: Event loop is running

### ISSUE THREAD

**Issue by ryarom148** [ccxt/ccxt#2324]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Mac OS: version 10.13
- Programming Language version: python
- CCXT version: ccxt-1.11.147
- Exchange: gdax
- Method: load_markets using ccxt.async 

i am trying to run your example py/async-basic.py
and getting this error:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-78f7195725dd> in <module>()
     11 
     12 
---> 13 print(asyncio.get_event_loop().run_until_complete(test_gdax()))

//anaconda/lib/python3.5/asyncio/base_events.py in run_until_complete(self, future)
    373         future.add_done_callback(_run_until_complete_cb)
    374         try:
--> 375             self.run_forever()
    376         except:
    377             if new_task and future.done() and not future.cancelled():

//anaconda/lib/python3.5/asyncio/base_events.py in run_forever(self)
    338         self._check_closed()
    339         if self.is_running():
--> 340             raise RuntimeError('Event loop is running.')
    341         self._set_coroutine_wrapper(self._debug)
    342         self._thread_id = threading.get_ident()

RuntimeError: Event loop is running.
gdax requires to release all resources with an explicit call to the .close() coroutine.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10e97e908>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x10f8b15c0>, 381.652706104)]']
connector: <aiohttp.connector.TCPConnector object at 0x10e593860>

**Comment by kroitor** [comment]
> gdax requires to release all resources with an explicit call to the .close() coroutine.

You need to follow what it's telling you...

```
# -*- coding: utf-8 -*-

import asyncio
import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt.async as ccxt  # noqa: E402


async def test_gdax():
    gdax = ccxt.gdax()
    markets = await gdax.load_markets()
    await gdax.close ()
    return markets


print(asyncio.get_event_loop().run_until_complete(test_gdax()))
```

Updated the above example as well...

**Comment by ryarom148** [comment]
followed you instructions,
but have the same error, but without request for close the session:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-041721931dd7> in <module>()
     13 
     14 
---> 15 print(asyncio.get_event_loop().run_until_complete(test_gdax()))

//anaconda/lib/python3.5/asyncio/base_events.py in run_until_complete(self, future)
    373         future.add_done_callback(_run_until_complete_cb)
    374         try:
--> 375             self.run_forever()
    376         except:
    377             if new_task and future.done() and not future.cancelled():

//anaconda/lib/python3.5/asyncio/base_events.py in run_forever(self)
    338         self._check_closed()
    339         if self.is_running():
--> 340             raise RuntimeError('Event loop is running.')
    341         self._set_coroutine_wrapper(self._debug)
    342         self._thread_id = threading.get_ident()

RuntimeError: Event loop is running.

**Comment by kroitor** [comment]
@ryarom148 can you, please, clarify:
- are you trying exactly the above code?
- how do you launch it?
- what's your `python --version` ?

**Comment by ryarom148** [comment]
Python 3.5.2 
i am running it through jupyterlab.
Problem is that everything was working two days ago , but after upgrading ccxt, method load_markets() causing the problem. 
By the way: the code in async-gdax-fetch-order-book-continuously.py works fine

**Comment by kroitor** [comment]
> Python 3.5.2

You need to upgrade to at least 3.5.3, with a newer version of asyncio for it to work, actually.

> By the way: the code in async-gdax-fetch-order-book-continuously.py works fine

This is just because that code does not reach execution end, as it works continuously...

**Comment by ryarom148** [comment]
i upgraded Python to Python 3.6.4 :: Anaconda custom (64-bit)
the same error
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-041721931dd7> in <module>()
     13 
     14 
---> 15 print(asyncio.get_event_loop().run_until_complete(test_gdax()))

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py in run_until_complete(self, future)
    452         future.add_done_callback(_run_until_complete_cb)
    453         try:
--> 454             self.run_forever()
    455         except:
    456             if new_task and future.done() and not future.cancelled():

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py in run_forever(self)
    406         self._check_closed()
    407         if self.is_running():
--> 408             raise RuntimeError('This event loop is already running')
    409         if events._get_running_loop() is not None:
    410             raise RuntimeError(

RuntimeError: This event loop is already running

**Comment by kroitor** [comment]
@ryarom148 do you have the same error when running the above sample a standalone script outside of jupyterlab, with pure python:

```
python examples/py/async-basic.py
```

?

**Comment by ryarom148** [comment]
just ran python examples/py/async-basic.py
it works!!
but when ran the code in jupyter I have this 'event loop is already running'
everything was working two days ago.
i guess the problem is with jupyter
Anyway, i appreciate your prompt response!

**Comment by ryarom148** [comment]
Thanks, my problem was different. Somehow after installing ipywidgets, ipkernal starts running the loop. That's why i had this problem. I solved this problem by adding future to the existing loop.
