### ISSUE TITLE
Binance balance, v2 account and position endpoints deprecation notice

### ISSUE THREAD

**Issue by materemias** [ccxt/ccxt#23253]
### Description

As announced on [2024-07-24](https://developers.binance.com/docs/derivatives/change-log#2024-07-24), the following endpoints will be deprecated in the coming months (exact date to be announced later). Please add the new v3/v2 endpoints:
- REST API:
```
GET /fapi/v2/balance
GET /fapi/v2/account
GET /fapi/v2/positionRisk
```
- Websocket API:
```
account.status
account.balance
account.position
```

### Code

```
  

```

**Comment by sc0Vu** [comment]
@materemias Thanks for the report. We'll update asap.
