### ISSUE TITLE
Bitfinex not return all series

### ISSUE THREAD

**Issue by claufox** [ccxt/ccxt#2326]
ATTENTION!!!

- OS: windows
- Programming Language version: php
- CCXT version: last
- Exchange: Bitfinex
- Method: $exchange->fetchOHLCV

Method not returning all data series(5min,15min,30min) after bitfinex maintenance (21-03-2018)

**Comment by kroitor** [comment]
> Method not returning all data series(5min,15min,30min) after bitfinex maintenance (21-03-2018)

Can you elaborate please? What do you do, what result do you get and what do you expect? Would be even better if you post a short snippet of your code to reproduce the problem and your **verbose output** according to these rules: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

In particular, all of the following timeframes work for me:

```
mbp:ccxt igorkroitor$ php -f examples/php/cli.php bitfinex fetch_ohlcv ETH/BTC 5m
mbp:ccxt igorkroitor$ php -f examples/php/cli.php bitfinex fetch_ohlcv ETH/BTC 15m
mbp:ccxt igorkroitor$ php -f examples/php/cli.php bitfinex fetch_ohlcv ETH/BTC 30m
```

You should probably implement proper error handlind as described in the manual and in the troubleshooting section:
- https://github.com/ccxt/ccxt/wiki/Manual#error-handling
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Closing this for now, if you dont mind, feel free to reopen it or just ask questions if needed.

**Comment by claufox** [comment]
It's settled.The bitfinex exchange must have deleted the records for 15min, 30min, last 5min after maintenance .. now it is already returning results.THANK YOU

**Comment by kroitor** [comment]
@claufox thx for reporting back! Let us know if you have further questions )
