### ISSUE TITLE
When I create an order with orderLinkId for Bybit, I get a different clientOrderId in the history

### ISSUE THREAD

**Issue by Podolchak** [ccxt/ccxt#23260]
### Operating System

Macos

### Programming Languages

Javascript

### CCXT Version

4.3.62

### Description

When I create an order with orderLinkId for Bybit, I get a different clientOrderId in the history 

I make an ID like this and when I send the order it comes back with the correct ID
`${symbol.split('/')[0]}-${side}-${action}-${Date.now()}`

`  info: {
    orderId: 'f96453a1-4950-49f7-a820-acce1a4c0dd7',
    orderLinkId: 'BLUR-short-profit-lz8h82t1'
  },
  id: 'f96453a1-4950-49f7-a820-acce1a4c0dd7',
  clientOrderId: 'BLUR-short-profit-lz8h82t1',
`

But when I want to see closed orders I get this
`
const orders = await exchange.fetchClosedOrders(data.symbol, data.position.timestamp)
console.log(orders)`

`clientOrderId: 'BLU_s_24160_75570'`

Is this a bug or am I doing something wrong?

**Comment by Podolchak** [comment]
My mistake, since I was pointing to the wrong one

I would be grateful if you could tell me how to correctly get when a position was opened
I think to search by executed orders, but it may happen that there are too many orders for a position and it may not be in the first 50 orders. Any ideas?

**Comment by carlosmiei** [comment]
Hello @Podolchak, you sned the exchange-specific parameter `orderLinkId` but the unified term for ccxt is `clientOrdeId` (you still have `orderLinkId` inside `info` tho)

> I would be grateful if you could tell me how to correctly get when a position was opened

You can fetch positions information with `fetch_positions`
