### ISSUE TITLE
ccxt function for coinbase /api/v3/brokerage/transaction_summary

### ISSUE THREAD

**Issue by MP-AAMIR** [ccxt/ccxt#23272]
### Operating System

Linux

### Programming Languages

Node Js

### CCXT Version

 "ccxt": "^4.3.67"

### Description

coibase.com/api/v3/brokerage/transaction_summary
ccxt function for this API

### Code

```
  

```

**Comment by sc0Vu** [comment]
@MP-AAMIR You can find how to call api directly in our wiki. https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

The function would be v3PrivateGetBrokerageTransactionSummary for /api/v3/brokerage/transaction_summary.

**Comment by ttodua** [comment]
question was answered. let us know if there are still any issues.
