### ISSUE TITLE
Cryptopia supports trade history. Emulation not necessary?

### ISSUE THREAD

**Issue by MarcelBeining** [ccxt/ccxt#2328]
Hi,
I just saw that Cryptopia meanwhile seems to support retrieving the trade history (GetTradeHistory):
https://www.cryptopia.co.nz/Forum/Thread/256

However, in ccxt it is still handled in emulated mode for Cryptopia (e.g. fetchClosedOrders).

Would be great if you'd implement that. Unfortunately, I am not that into python / your code structure to feel confident enough doing it myself. Thanks for this great package!

- OS: Windows
- Programming Language version: Python 3.5
- CCXT version: 1.11.149
- Exchange: Cryptopia
- Method: fetchClosedOrders

**Comment by kroitor** [comment]
Hi!

It's already implemented...

- https://github.com/ccxt/ccxt/blob/master/js/cryptopia.js#L320
- https://github.com/ccxt/ccxt/blob/master/php/cryptopia.php#L319
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/cryptopia.py#L306

... however, you seem to be confusing `trades` and `orders`, explained here:

- https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades

Also, see my post on Cryptopia forum to understand what exactly their API is missing.

- https://www.cryptopia.co.nz/Forum/Thread/256?postId=12743

↑ The above should give an extensive answer to your question. Thx!

**Comment by MarcelBeining** [comment]
You're right I mixed up trades and orders. Many thanks for the detailed answer/help!
