### ISSUE TITLE
Break exchanges.py into separate files

### ISSUE THREAD

**Issue by jcrubino** [ccxt/ccxt#233]
All in all this library is overwhelmingly impressive in bredth and syntatic niceties.

but exchanges.py is getting quite large

Would it be more ergonomic for developers to work on code files specified for each exchange and use explicit imports or concat through configuration every exchange needed for production environments into an exchanges.py?

This might lead to contributor ownership for individual or sets of exchanges and a standard if limited test suite could be used to score exchange code maturity.

**Comment by kroitor** [comment]
@jcrubino we're planning to refactor for that in the upcoming v2.0 very soon (it will be backward-compatible, though much better organized).

**Comment by kroitor** [comment]
This issue has been finally fixed in 1.9.291. Thx for all your patience!
