### ISSUE TITLE
4.3.71 error  No module named 'ccxt.static_dependencies.starkware'

### ISSUE THREAD

**Issue by jtashiro** [ccxt/ccxt#23307]
### Operating System

ubuntu and mac

### Programming Languages

Python

### CCXT Version

4.3.71

### Description

Getting this error when running python scripts that ran prior to upgrade.  Looks like a module is missing ??

from ..starkware.crypto.signature import grind_key
ModuleNotFoundError: No module named 'ccxt.static_dependencies.starkware'

### Code

```
  

```

**Comment by jtashiro** [comment]
thank you - Mac os Python 3.11,  Ubuntu 3.8.10

looks like the command
pip3 install . 
does not copy the starkware/crypto files into the site-package

**Comment by jtashiro** [comment]
That worked - thanks.

**Comment by carlosmiei** [comment]
@jtashiro Thanks for reporting it, we will release a new version with the fix in a few minutes.

**Comment by jtashiro** [comment]
is there a test suite that I can run after git pull/install to validate the package is working correctly?

**Comment by jtashiro** [comment]
I am picking up nightly builds with automated git pull / pip install to stay up to date automatically.  Would you recommend that or some other technique to pick up stable releases on a less frequent basis?

**Comment by carlosmiei** [comment]
@jtashiro We run thousands of tests (unit/static/live/etc) before releasing, but yeah, we're lacking a test that ensures the pip package is working correctly because, as you saw, we might have some surprises with the packing when we add a lot of files.

I will try to add that test.
