### ISSUE TITLE
WatchTrades - newupdates sends a lot duplicates on ccxt 4.3.57 thru current ccxt 4.3.72

### ISSUE THREAD

**Issue by csotto** [ccxt/ccxt#23310]
### Operating System

Ubuntu / Windows

### Programming Languages

Python

### CCXT Version

4.3.57 and upper thru current 4.2.72

### Description

WatchTrades - newupdates sends a lot duplicates on ccxt 4.3.57 thru ccxt 4.3.72. High percentage of duplicates: Over 60%.
Problem in not present in ccxt prior 4.3.57.
Most tests on Binance but other exchages show the same problem. 
Teste program results:
********************************************************************************
CCXT: 4.3.72  id_count=506 duplicates_cnt=394  Duplicate Percentage=77.9
********************************************************************************
********************************************************************************
CCXT: 4.3.57  id_count=1131 duplicates_cnt=1037  Duplicate Percentage=91.7
********************************************************************************
********************************************************************************
CCXT: 4.3.56  id_count=21 duplicates_cnt=0  Duplicate Percentage= 0.0
********************************************************************************

### Code

```
import ccxt.pro as ccxtpro
from asyncio import run
# CTRL-C to quit and read the duplicate percentage count printed prior unhandled exception
async def main():
    exchange = ccxtpro.binance({'newUpdates': True, "verbose": False})
    last_known_id = 0
    id_count = 0
    duplicates_cnt = 0
    try:
        while True:
            results = await exchange.watch_trades('BTC/USDT')
            for trade in results:
                id_count += 1
                if int(trade["id"]) > last_known_id:
                    last_known_id = int(trade["id"])
                    print(f'{trade}')
                else:
                    duplicates_cnt += 1
                    print(f'{trade["id"]=} <= {last_known_id=} <<<<<< This trade-id is a duplicate <<<<<<<<<<<')
    except Exception as err:
        print(f" {type(err)} {err.args=} {err=} <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<")
    finally:
        print(80*"*")
        print(f"CCXT: {ccxtpro.__version__}  {id_count=} {duplicates_cnt=}  Duplicate Percentage={round(100 * duplicates_cnt / id_count,1):4.1f}")
        print(80*"*")
    await exchange.close()

run(main())
  

```

**Comment by sc0Vu** [comment]
It looks like the known issue in the message queue ccxt/ccxt#23210.

**Comment by carlosmiei** [comment]
Hello @csotto, we will deploy a patch asap.

**Comment by csotto** [comment]
Thanks a lot @sc0vu, ,@pcriadoperez @carlosmiei. 
I evaluated #23210 and made a informed decision that even being duplicated I could add some value  by adding an issue with:
- version were the problem started. to make it easier to track it down
- comparison by IDs instead of timestamps that might be duplicated in normal circustances.
- measure of the level of "duplicateness" by adding percentages.
I appreciate your time and attention.

**Comment by carlosmiei** [comment]
@csotto We released a new version with a patch, can you please upgrade and try again to see if it makes a difference?

**Comment by csotto** [comment]
Ccxt version  4.3.73 completely fixed the problem from my point of view and tests.
Tested in Ubuntu and Windows. Both runs perfectly.

Thanks again @carlosmiei. 
I am closing the issue now.
