### ISSUE TITLE
Use in reactjs, Uncaught (in promise) TypeError: _static_dependencies_qs_index_cjs__WEBPACK_IMPORTED_MODULE_2__.stringify is not a function

### ISSUE THREAD

**Issue by diamond-tiger** [ccxt/ccxt#23328]
### Operating System

window

### Programming Languages

JavaScript

### CCXT Version

4.3.73

### Description

The qt source code was not loaded!

project dependencies:
[
![无标题](https://github.com/user-attachments/assets/ae15fc83-8229-4ea5-aefd-aac35510dfe7)
]

error:
![354951887-7f755aef-a68a-4869-9daf-5c4dd9bb7e0b](https://github.com/user-attachments/assets/ab1ceba0-6499-4620-9046-d71c7af7ca65)

![无标题](https://github.com/user-attachments/assets/27f385e6-a48f-4069-9464-7c8925f15095)
<img width="560" alt="无标题" src="https://github.com/user-attachments/assets/381f047b-e2b6-4dd9-8e5d-62b508aaf32a">

**Comment by sc0Vu** [comment]
@diamond-tiger Did you import as ESM module?

**Comment by diamond-tiger** [comment]
At 2024-08-05 17:23:45, "Peter Lai" ***@***.***> wrote:

@diamond-tiger Did you import as ESM module?

**Comment by diamond-tiger** [comment]
![Uploading 无标题.png…]()

**Comment by diamond-tiger** [comment]
![无标题](https://github.com/user-attachments/assets/f2ac70d7-95b9-4e64-82bc-c60041ba165f)

**Comment by sc0Vu** [comment]
@diamond-tiger Thanks, I can reproduce the issue. It seems webpack didn't load the qs module properly. I'll see how to fix to make ESM work in react.

**Comment by sc0Vu** [comment]
Hi @diamond-tiger,

The root cause is that `qs` is written in cjs, and it required additional configuration for bundler (webpack, rollup).  Could you import our bundled file?

**Comment by diamond-tiger** [comment]
Ok, l try it and give you feedback.

**Comment by diamond-tiger** [comment]
All-in-one browser bundle，it ok!  thank you。
