### ISSUE TITLE
CCXT has recently started manipulating python source code.

### ISSUE THREAD

**Issue by thisismygitrepo** [ccxt/ccxt#23358]
### Operating System

ALL

### Programming Languages

Python, tried 3.11 & 3.12

### CCXT Version

Anything in the last 5 versions, onwards.

### Description

since few releases ago, I notice a failure in compiling pytorch model due to type-hinting related error.

```
    model.compile()
  File "/home/alex/venvs/cry/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2603, in compile
    self._compiled_call_impl = torch.compile(self._call_impl, *args, **kwargs)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/venvs/cry/lib/python3.11/site-packages/torch/__init__.py", line 2111, in compile
    backend = _TorchCompileInductorWrapper(mode, options, dynamic)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/venvs/cry/lib/python3.11/site-packages/torch/__init__.py", line 1901, in __init__
    from torch._inductor.compile_fx import compile_fx
  File "/home/alex/venvs/cry/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 15, in <module>
    import torch._inductor.async_compile  # noqa: F401 required to warm up AsyncCompile pools
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/venvs/cry/lib/python3.11/site-packages/torch/_inductor/async_compile.py", line 17, in <module>
    from torch._inductor.codecache import (
  File "/home/alex/venvs/cry/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 52, in <module>
    from torch._inductor import config, exc, metrics
  File "/home/alex/venvs/cry/lib/python3.11/site-packages/torch/_inductor/metrics.py", line 15, in <module>
    from torch._inductor.utils import get_benchmark_name
  File "/home/alex/venvs/cry/lib/python3.11/site-packages/torch/_inductor/utils.py", line 423, in <module>
    class CachedMethod(Protocol, Generic[P, RV]):
                                 ~~~~~~~^^^^^^^
  File "/usr/lib/python3.11/typing.py", line 379, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/typing.py", line 1874, in __class_getitem__
    return _GenericAlias(cls, params,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/typing.py", line 1383, in __init__
    self.__parameters__ = _collect_parameters(args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/venvs/cry/lib/python3.11/site-packages/ccxt/static_dependencies/typing_extensions/typing_extensions.py", line 3125, in _collect_parameters
    raise TypeError(f'Type parameter {t!r} without a default'
TypeError: Type parameter +RV without a default follows type parameter with a default
Model.compile() failed with error: Type parameter +RV without a default follows type parameter with a default

```

This only happens if I do `import ccxt`. If I don't do that, the error vanished. I reached this far in debugging after hours of work. I further tried to dig in further to ccxt but there was way too much superflous internal imports that prohibitied me from further investigation. So I just wanted to report this recent weird behaviour here.

My best guess is `ccxt` is dynamically manipulating python built-in library causing this failure. Thr traceback showing nothing related to ccxt, but only happens after you import ccxt, meanning that ccxt manipulated something and stepped aside.

PS: I scoured the internet thoroughly looking for someone with same error, but failed to finy anyone reporting it. Hence, I'm failrly confident about my explanation so far. I'm pretty sure Pytorch is not to blame despite the traceback showing otherwise.

Thanks.

### Code

```
import ccxt

```

**Comment by thisismygitrepo** [comment]
Unless I'm very much mistaken, the problem can be easily regenerated with a one-liner simple pytorch 1-layer model accompanied with a ccxt import.

**Comment by thisismygitrepo** [comment]
I managed to make an irreducibly simple code:

```python

import torch
import torch.nn as nn

class SimpleModel(nn.Module):
    def __init__(self, input_size, output_size):
        super(SimpleModel, self).__init__()
        self.linear = nn.Linear(input_size, output_size)

    def forward(self, x):
        return self.linear(x)

model = SimpleModel(input_size=10, output_size=1)
model.compile()
```

That works. Now, repeat with `import ccxt` before everything and the error will be generated.

**Comment by carlosmiei** [comment]
Hello @thisismygitrepo thanks a lot for reporting it and for the detailed explanation, we will take a look.

**Comment by carlosmiei** [comment]
@thisismygitrepo we just released a version with the fix, can you please upgrade your ccxt version and try again?

**Comment by thisismygitrepo** [comment]
@carlosmiei I can confirm the problem is gone with 4.3.77 🚀. Many thanks.

**Comment by carlosmiei** [comment]
@thisismygitrepo no problem, let us know if anything
