### ISSUE TITLE
kraken: incorrect oflag handling

### ISSUE THREAD

**Issue by 89d55d5288** [ccxt/ccxt#23353]
Good afternoon!

Kindly help with the issue params = {"oflags": "fcib"}. With this key, the commission should be taken from "base" for "buy" operation.
But my commission is taken from "quote".

sending {'event': 'addOrder', 'token': 'iKDrjlnDZqZAtHEF7K___WOjnc', 'reqid': 2467__39, 'ordertype': 'market', 'type': 'buy', 'pair': 'ETH/USDT', 'volume': '0.00373474', 'oflags': 'fcib'}
message {'descr':'buy 0.00373474 ETHUSDT @ market','event':'addOrderStatus','reqid':2467__39,'status':'ok','txid':'OUZMPR-BKYJA-_______'}

{'Symbol':'ETH/USDT','Order ID':'OUZMPR-BKYJA-_____','Status':'Unknown','Price': 2931.49,'Amount': 0.00373474,'Filled': 0,'Cost': 10.9483529626,'Side':'buy','Fee': {'cost': 0.04379, 'currency': 'USDT'}}

What is the error in forming the request and passing the key?

Code
             params = {"oflags": "fciq"} if exchange.id == 'kraken' and side == 'sell' else {
                "oflags": "fcib"} if exchange.id == 'kraken' and side == 'buy' else {}

            print(params)

                order = await exchange.create_order_ws(symbol, type, side, amount, price, params=params)

_Originally posted by @89d55d5288 in https://github.com/ccxt/ccxt/issues/20406#issuecomment-2272089814_

**Comment by carlosmiei** [comment]
Hello @89d55d5288,

Thanks for reporting it, one question what is your ccxt version?

**Comment by 89d55d5288** [comment]
> Hello @89d55d5288,
> 
> Thanks for reporting it, one question what is your ccxt version?

Thanks for your question.
Work version cxt 4.1.86
Watched the newer versions, but what I described happens there as well.

**Comment by carlosmiei** [comment]
@89d55d5288 We found indeed a small issue, but will be fixed shortly (we will release a new version with the fix very soon)

**Comment by carlosmiei** [comment]
@89d55d5288 we just released a version with the fix, can you please upgrade your ccxt version and try again?

**Comment by 89d55d5288** [comment]
> sed a version with the fi

    if (flags is not None) and (request['oflags'] is None):
                                ~~~~~~~^^^^^^^^^^
KeyError: 'oflags'

**Comment by carlosmiei** [comment]
@89d55d5288 Sorry we will fix it asap, thanks once again,

**Comment by 89d55d5288** [comment]
> @89d55d5288 Sorry we will fix it asap, thanks once again,

Thanks for answer
In the proposed version, the fix is not formed into an "oflags" request

fetch Request: kraken POST https://api.kraken.com/0/private/AddOrder RequestHeaders: {'API-Key': 'mPuELX99pgczQyNjKRruU8zKidXK1', 'API-Sign': 'xXc0/sg1h0mo+xoHbxeAOb8IZmtndJuEYTJYITw==', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate'} RequestBody: nonce=1723198171244&pair=ETHUSDT&type=buy&ordertype=market&volume=0.003

If it's written like this:
if (flags is not None):
request['oflags'] = flags

Then the request is formed with "oflags"

fetch Request: kraken POST https://api.kraken.com/0/private/AddOrder RequestHeaders: {'API-Key': 'mP9pgczQyNjKRruU8zKidXK1', 'API-Sign': 'W5sbjskGgu3keJ9jzWr5nNtNAdwhQhKTXgFKMNU+jhd0PGkmASJA==', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate'} RequestBody: nonce=1723198668231&pair=ETHUSDT&type=buy&ordertype=market&volume=0.003&oflags=fcib

But the exchange still takes the commission from USDT. When buying ETHUSDT on the market, the commission should be taken from ETH (base currency according tolags = fcib).
