### ISSUE TITLE
Huobi - Insufficient open positions when using stopLossPrice for USDT-M futures

### ISSUE THREAD

**Issue by AlexShashkov** [ccxt/ccxt#23355]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.3.76

### Description

Hi, Im struggling with using stop loss price when making USDT-M futures limit orders. I tried multiple examples, including provided code in https://github.com/ccxt/ccxt/issues/13822, but I always get the same exception raised on createOrder 
```ccxt.base.errors.InsufficientFunds: htx {"status":"error","err_code":1048,"err_msg":"Insufficient open positions to be closed. Please check whether there are open orders under \"Limit Orders\".","ts":1723060692010}```

And I checked - I dont have any open orders. If I comment out row with ```"stopLossPrice": stopLossPrice```, then order is successfully created without any issues. Im not sure what exactly Im doing wrong, I even tried using stopLoss, but it didnt set stop loss price too.

### Code

```
exchange = ccxt.htx({
  'apiKey': api,
  'secret': secret,
  'options': {
      'createMarketBuyOrderRequiresPrice' : False,
      'defaultType': 'future',
      "defaultSubType":'linear',
      'marginMode': 'cross'
  }
})
markets = exchange.load_markets()
capital = 11
symbol = 'LINK/USDT:USDT'

spread_percentage = 0.005
longing = getLastestKlineStatus(exchange, symbol)
print("LONGING:", longing)
bids, asks, price_dec, size_dec = getOrderBook(exchange, symbol)

price = asks[0][0] if longing else bids[0][0]
price = price * (1 + spread_percentage * (-1 if longing else 1))
stopLossPrice = round(price * (1 + 0.05 * (-1 if longing else 1)), price_dec)

amount = asks[0][1] if longing else bids[0][1]

print("stopLossPrice", stopLossPrice))

print(f'Opening order at {price}, capital on position: {price*amount}')
amount = capital / price
print(amount, price)
print(f"ORDERING {amount} {symbol} -> {amount*price}")
order = exchange.createOrder(symbol, "limit", "buy" if longing else "sell", round(amount, size_dec),
        round(price, price_dec), params={
            "offset": 'open',
            "stopLossPrice": stopLossPrice,
            "leverRate": 1
})
print(order)

```

**Comment by ttodua** [comment]
You are probably confused with those two things:
- `stopLossPrice` is a standalone order meant for "closing" an existing position. You can't use `stopLossPrice` together with the entry order in same `createOrder` call.
- `stopLoss` , in opposite, is an embeddable "closing" order which can be used inside `createOrder` together with the primary "entry" order. You can't use `stopLoss` separately.

so, you should decide which one you want to use and whether the exchange supports it (what i see in `huobi`'s createOrder description lines, it does not support `stopLoss`, so you have to open a position at first, and then use separate "closing" order with `stopLossPrice`)

**Comment by AlexShashkov** [comment]
Oh, my bad, you are right. Thank you!
