### ISSUE TITLE
load_markets().keys() differ from fetch_tickers()

### ISSUE THREAD

**Issue by kapedalex** [ccxt/ccxt#23352]
### Operating System

Win 10

### Programming Languages

Python

### CCXT Version

4.3.73

### Description

I expect the code below to produce the same numbers (2542/2542), but it actually prints (2542/437). Why is this happening? It’s particularly strange because the markets from load_markets are currently trading, yet fetch_tickers does not display them. This function (fetch_tickers) should be used for active tickers.

### Code

```
async def debug():
    exchange = ccxt.bybit({logging_data})
    markets = await exchange.load_markets(True)
    tickers = await exchange.fetch_tickers()
    print(len(markets.keys()))
    print(len(tickers))
    await exchange.close()
asyncio.run(debug())

```
result
```
2542
437
```

**Comment by carlosmiei** [comment]
Hello @kapedalex, `loadMarkets/fetchMarkets` is a "special" function that performs several calls to load all the available markets (swap, spot, options, etc) and currencies.  (most of the markets you see are options and delivery futures)

`fetchTicker/fetchTickers` only performs one rest call, so they can only load one part of the markets. If you want to load all of them you need to call `fetch_tickers` multiple types using `type` in `params`, example:


```Python
swap_tickers = await bybit.fetch_tickers() # by default returns linear swaps
spot_tickers = await bybit.fetch_tickers(params = {'type':'spot'})
inverse_tickers = await bybit.fetch_tickers(params = {'subType':'inverse'})
option_tickers = await bybit.fetch_tickers(params = {'type':'option'})
```
(ofc you can use asyncio.gather and do them concurrently)

**Comment by kapedalex** [comment]
Ah, ok, thanks a lot!
