### ISSUE TITLE
more commonCurrencyCodes for ethfinex (& probably also bitfinex since same api)

### ISSUE THREAD

**Issue by Esc4pism** [ccxt/ccxt#2336]
QSH - QASH
YYW - YOYOW
MNA - MANA
SNG - SNGLS
SPK - SPANK (not to be confused with Sparks(SPK) ... )

Taken from https://www.ethfinex.com/token_listings, where they listed SPANK as a supported currency.
Their listed prices also check out with prices for SPANK on other sites, not those for sparks.

**Comment by kroitor** [comment]
Fixed in 1.11.158. Thank you! )
