### ISSUE TITLE
Websockets are not working for demo trading

### ISSUE THREAD

**Issue by karambaq** [ccxt/ccxt#23362]
### Operating System

macos

### Programming Languages

Python

### CCXT Version

4.3.76

### Description

Error:

```
  File "/Users/malter/code/tv_bot/venv/lib/python3.11/site-packages/ccxt/pro/bybit.py", line 151, in get_url_by_market_type
    url = self.urls['api']['ws']
          │    └ {'logo': 'https://user-images.githubusercontent.com/51840849/76547799-daff5b80-649e-11ea-87fb-3be9bac08954.jpg', 'api': {'spo...
          └ ccxt.async_support.bybit()

KeyError: 'ws'
```

### Code

```python
import asyncio

import ccxt.pro as ccxt


async def watch_orders():
    exchange: ccxt.bybit = ccxt.bybit(
        {
            "apiKey": API_KEY,
            "secret": API_SECRET,
        }
    )
    exchange.enable_demo_trading(True)

    while True:
        await exchange.watch_orders()
        
asyncio.run(watch_orders())


```

**Comment by carlosmiei** [comment]
Hello @karambaq, do you want to use what bybit calls "demo trading" or the sandbox/testnet mode? they're different

**Comment by karambaq** [comment]
@carlosmiei Hi, yes, I want to use demotrading

**Comment by carlosmiei** [comment]
@karambaq Got it, we will fix it asap, thanks for reporting it.

**Comment by carlosmiei** [comment]
@karambaq Can you upgrade your ccxt version and try again? We just released a version with the fix

**Comment by karambaq** [comment]
Thank you, it looks like it working.

**Comment by carlosmiei** [comment]
@karambaq no problem, let us know if anything

**Comment by mohdhasnain902** [comment]
which version to use? are you talking about the ccxt version or the bybit version
