### ISSUE TITLE
Bibox createMarketBuyOrder {"error":{"code":"2067","msg":"暂不支持市价单"},"cmd":"orderpending/trade"}

### ISSUE THREAD

**Issue by 2l1k** [ccxt/ccxt#2338]
I have a trouble - bibox {"error":{"code":"2067","msg":"暂不支持市价单"},"cmd":"orderpending/trade"}
I wanna to buy coins TRX/BTC

code - exchange.createMarketBuyOrder (symbol, amount)

**Comment by kroitor** [comment]
Can you please post a minimal code snippet to reproduce it and your complete verbose output (without the keys) according to this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

**Comment by 2l1k** [comment]
let fetchbalance = await (exchange.fetchBalance ())
let balance_val = fetchbalance.BTC.total // balance_val = 0,0016
let orderbook = await (exchange.fetchTicker (TRX/BTC))
let lastPrice = orderbook.info.buy // lastPrice  = 0,000004
let amount = (balance_val * 5/ 100)/lastPrice
exchange.createMarketBuyOrder (TRX/BTC, amount)

**Comment by kroitor** [comment]
@2l1k and your verbose output?

**Comment by 2l1k** [comment]
You could not simply explain what the problem is, or what the error is, and why it appears most often? bibox {"error":{"code":"2067","msg":"暂不支持市价单"},"cmd":"orderpending/trade"}  Thanks.

**Comment by kroitor** [comment]
Anyway, never mind, the problem is: 暂不支持市价单 == "Does not support market orders", so, apparently, we should disable it for Bibox

**Comment by 2l1k** [comment]
The conclusion is what? There is no sense that either output if not a purchase, don't you think?

**Comment by 2l1k** [comment]
And you yourself have not tested buying and selling on the Bibox?

**Comment by kroitor** [comment]
> And you yourself have not tested buying and selling on the Bibox?

We are doing testing, but there may be missing cases. However, this isn't the missing case. 

> The conclusion is what? 

It literally says that bibox does not support market orders. So, apparently, createMarketBuyOrder will return an exception, according to this: https://github.com/ccxt/ccxt/wiki/Manual#error-handling

> There is no sense that either output if not a purchase, don't you think?

This particular I didn't quite get, can you clarify?
