### ISSUE TITLE
Bybit's fetch_ledger() should call different endpoint if inverse

### ISSUE THREAD

**Issue by materemias** [ccxt/ccxt#23389]
### CCXT Version

4.3.79

### Description

ccxt uses the following logic on bybit's `fetch_ledger()`:
```
        if enableUnified[1]:
            response = self.privateGetV5AccountTransactionLog(self.extend(request, params))
        else:
            response = self.privateGetV2PrivateWalletFundRecords(self.extend(request, params))
```
but there is a 3rd option: if the account is UTA but you want to request inverse ledger you need `v5/account/contract-transaction-log` endpoint, see [here](https://bybit-exchange.github.io/docs/v5/account/contract-transaction-log) 

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @materemias, thanks for reporting it, we will add it and make it accessible through the option `subType:inverse` in `params`

**Comment by carlosmiei** [comment]
Hello @materemias can you please upgrade your ccxt version and try again? It should be working now.

**Comment by materemias** [comment]
> Hello @materemias can you please upgrade your ccxt version and try again? It should be working now.

thanks a lot it works perfectly
