### ISSUE TITLE
Kraken takes quoted currency commission when oflags = fcib is enabled

### ISSUE THREAD

**Issue by 89d55d5288** [ccxt/ccxt#23384]
> @89d55d5288 Sorry we will fix it asap, thanks once again,

Then the request is formed with "oflags"

fetch Request: kraken POST https://api.kraken.com/0/private/AddOrder RequestHeaders: {'API-Key': 'mP9pgczQyNjKRruU8zKidXK1', 'API-Sign': 'W5sbjskGgu3keJ9jzWr5nNtNAdwhQhKTXgFKMNU+jhd0PGkmASJA==', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate'} RequestBody: nonce=1723198668231&pair=ETHUSDT&type=buy&ordertype=market&volume=0.003&oflags=fcib

But the exchange still takes the commission from USDT. When buying ETHUSDT on the market, the commission should be taken from ETH (base currency according tolags = fcib).

_Originally posted by @89d55d5288 in https://github.com/ccxt/ccxt/issues/23353#issuecomment-2277635424_

**Comment by 89d55d5288** [comment]
Hi all
Has anyone tested this on Kraken?

**Comment by sc0Vu** [comment]
@89d55d5288 It works for me. Can you test again?

**Comment by 89d55d5288** [comment]
@sc0Vu Hi, thanks for the reply.
It doesn't work for me. I have all transactions sell and buy commission is taken in quota currency.
{‘Symbol’: ‘LTC/BTC’, ‘Side’: ‘buy’, ‘Fee’: {‘cost’: 4.8e-07, ‘currency’: ‘BTC’}}
{‘Symbol’: ‘ETC/BTC’, ‘Side’: ‘buy’, ‘Fee’: {‘cost’: 1.01e-06, ‘currency’: ‘BTC’}}
{‘Symbol’: ‘BCH/BTC’, ‘Side’: ‘sell’, ‘Fee’: {‘cost’: 4.6e-07, ‘currency’: ‘BTC’}}
{‘Symbol’: ‘SOL/BTC’, ‘Side’: ‘sell’, ‘Fee’: {‘cost’: 1.56e-06, ‘currency’: ‘BTC’}}

If it is not difficult to show examples of your buy and sell orders where the commission is taken according to the oflags key (oflags=fcib and oflags=fciq)

**Comment by 89d55d5288** [comment]
> Contributor

If it is not difficult to show examples of your buy and sell orders where the commission is taken according to the oflags key (oflags=fcib and oflags=fciq)

**Comment by 89d55d5288** [comment]
Hey, everybody.
Can anyone show me their trade on the market with (oflags=fcib and oflags=fciq) that works out correctly?
