### ISSUE TITLE
bitget.watchTickers doesn't work, but exists in API Spec

### ISSUE THREAD

**Issue by Wannafly7** [ccxt/ccxt#23387]
### Programming Languages

JavaScript

### Description

I try to watch tickers, but it's unsupported, although it's exists in bitget API Spec https://docs.ccxt.com/#/exchanges/bitget?id=watchtickers

Error:
Error:  5 | // EDIT THE CORRESPONDENT .ts FILE INSTEAD
 6 | 
 7 | /* eslint-disable max-classes-per-file */
 8 | class BaseError extends Error {
 9 |     constructor(message) {
10 |         super(message);
             ^
NotSupported: bitget watchTickers() is not supported yet

### Code

```
  

```
import ccxt from 'ccxt';

const exchange = new ccxt.bitget();

async function startTickerStream() {
    try {
        await exchange.loadMarkets();
        const symbols = exchange.symbols.filter(symbol => symbol.endsWith('/USDT'));

        while (true) {
            const tickers = await exchange.watchTickers(symbols);
            console.log('Tickers:', tickers);
        }
    } catch (error) {
        console.error('Error:', error);
    }
}

startTickerStream();

**Comment by carlosmiei** [comment]
Hello @Wannafly7,
`watchmakers` is definitely available. Can you please check if you're importing/instantiating the `pro` exchange like `new ccx.pro.bitget()` ?

```
2024-08-11T13:09:46.143Z
Node.js: v18.18.0
CCXT v4.3.79
bitget.watchTickers (BTC/USDT,LTC/USDT)
{
  'BTC/USDT': {
    symbol: 'BTC/USDT',
    timestamp: 1723381793564,
    datetime: '2024-08-11T13:09:53.564Z',
    high: 61830.98,
    low: 60233.67,
    bid: 60264.77,
    bidVolume: 3.45036,
    ask: 60264.78,
    askVolume: 0.978797,
    vwap: 60932.26898425262,
    open: 60512.11,
    close: 60264.77,
    last: 60264.77,
    change: -247.34,
    percentage: -0.651,
    average: 60388.44,
    baseVolume: 3257.455098,
    quoteVolume: 198484130.235461,
    info: {
      instId: 'BTCUSDT',
      lastPr: '60264.77',
      open24h: '60512.11',
      high24h: '61830.98',
      low24h: '60233.67',
      change24h: '-0.00651',
      bidPr: '60264.77',
      askPr: '60264.78',
      bidSz: '3.45036',
      askSz: '0.978797',
      baseVolume: '3257.455098',
      quoteVolume: '198484130.235461',
      openUtc: '60902.10',
      changeUtc24h: '-0.01046',
      ts: '1723381793564'
    }
  }
}
{
  'LTC/USDT': {
    symbol: 'LTC/USDT',
    timestamp: 1723381793858,
    datetime: '2024-08-11T13:09:53.858Z',
    high: 62.368,
    low: 60.532,
    bid: 60.743,
    bidVolume: 37.6386,
    ask: 60.744,
    askVolume: 4.116,
    vwap: 61.33461708718244,
    open: 60.969,
    close: 60.744,
    last: 60.744,
    change: -0.225,
    percentage: -0.709,
    average: 60.856,
    baseVolume: 131384.6369,
    quoteVolume: 8058426.3954,
    info: {
      instId: 'LTCUSDT',
      lastPr: '60.744',
      open24h: '60.969',
      high24h: '62.368',
      low24h: '60.532',
      change24h: '-0.00709',
      bidPr: '60.743',
      askPr: '60.744',
      bidSz: '37.6386',
      askSz: '4.116',
      baseVolume: '131384.6369',
      quoteVolume: '8058426.3954',
      openUtc: '61.142',
      changeUtc24h: '-0.00653',
      ts: '1723381793858'
    }
  }
}

```

**Comment by Wannafly7** [comment]
> Hello @Wannafly7, `watchmakers` is definitely available. Can you please check if you're importing/instantiating the `pro` exchange like `new ccx.pro.bitget()` ?
> 
> ```
> 2024-08-11T13:09:46.143Z
> Node.js: v18.18.0
> CCXT v4.3.79
> bitget.watchTickers (BTC/USDT,LTC/USDT)
> {
>   'BTC/USDT': {
>     symbol: 'BTC/USDT',
>     timestamp: 1723381793564,
>     datetime: '2024-08-11T13:09:53.564Z',
>     high: 61830.98,
>     low: 60233.67,
>     bid: 60264.77,
>     bidVolume: 3.45036,
>     ask: 60264.78,
>     askVolume: 0.978797,
>     vwap: 60932.26898425262,
>     open: 60512.11,
>     close: 60264.77,
>     last: 60264.77,
>     change: -247.34,
>     percentage: -0.651,
>     average: 60388.44,
>     baseVolume: 3257.455098,
>     quoteVolume: 198484130.235461,
>     info: {
>       instId: 'BTCUSDT',
>       lastPr: '60264.77',
>       open24h: '60512.11',
>       high24h: '61830.98',
>       low24h: '60233.67',
>       change24h: '-0.00651',
>       bidPr: '60264.77',
>       askPr: '60264.78',
>       bidSz: '3.45036',
>       askSz: '0.978797',
>       baseVolume: '3257.455098',
>       quoteVolume: '198484130.235461',
>       openUtc: '60902.10',
>       changeUtc24h: '-0.01046',
>       ts: '1723381793564'
>     }
>   }
> }
> {
>   'LTC/USDT': {
>     symbol: 'LTC/USDT',
>     timestamp: 1723381793858,
>     datetime: '2024-08-11T13:09:53.858Z',
>     high: 62.368,
>     low: 60.532,
>     bid: 60.743,
>     bidVolume: 37.6386,
>     ask: 60.744,
>     askVolume: 4.116,
>     vwap: 61.33461708718244,
>     open: 60.969,
>     close: 60.744,
>     last: 60.744,
>     change: -0.225,
>     percentage: -0.709,
>     average: 60.856,
>     baseVolume: 131384.6369,
>     quoteVolume: 8058426.3954,
>     info: {
>       instId: 'LTCUSDT',
>       lastPr: '60.744',
>       open24h: '60.969',
>       high24h: '62.368',
>       low24h: '60.532',
>       change24h: '-0.00709',
>       bidPr: '60.743',
>       askPr: '60.744',
>       bidSz: '37.6386',
>       askSz: '4.116',
>       baseVolume: '131384.6369',
>       quoteVolume: '8058426.3954',
>       openUtc: '61.142',
>       changeUtc24h: '-0.00653',
>       ts: '1723381793858'
>     }
>   }
> }
> ```

Thank you!
It works
