### ISSUE TITLE
Binance fetchLedger () supports contract wallets only

### ISSUE THREAD

**Issue by landogarner7** [ccxt/ccxt#23393]
### Operating System

Windows

### CCXT Version

4.3.79

### Description

Using C#, since is timestamp

Calling
```
Dictionary<string, object> paramEx = new Dictionary<string, object>
{ 
    { "paginate", true }
};
ledger = await exchange.fetchLedger(null, since, null, paramEx) as List<object>
```
I receive
ExchangeErrorbinance fetchLedger() supports contract wallets only

Neither in Binance nor in ccxt docs I was able to find what that means or what contract wallets would be. I would require a solution to pull ALL kinds of movements from Binance including funding, deposits, withdrawals and trades. Thank you !

### Code

```
Dictionary<string, object> paramEx = new Dictionary<string, object>
{ 
    { "paginate", true }
};
ledger = await exchange.fetchLedger(null, since, null, paramEx) as List<object>
```

**Comment by sc0Vu** [comment]
@landogarner7 It seems fetchLedger is for contract wallets only (swap or option symbol). Here are other functions you could use `fetchTransfers`, `fetchWithdrawals` and `fetchDeposits`.

**Comment by landogarner7** [comment]
Thanks a lot, I will try these.
So basically it means "smart contracts", right ? Now I understand.
