### ISSUE TITLE
Clarify 'price' property of order object

### ISSUE THREAD

**Issue by cbp123** [ccxt/ccxt#2339]
- CCXT version: 1.11.101
- Language: nodejs

It's not totally clear the meaning of the _price_ property returned by fetchOrder and fetchOrders. Is it the average of the executed prices, or is it the limit price the order was issued with? The current documentation says it's the "float price" but I don't really know what that means.

Based on the documentation (https://github.com/ccxt/ccxt/wiki/Manual#order-structure), it appears to be the average price, because _cost_ is defined as _filled * price_. 

However I believe some exchanges are violating this definition. For example bitfinex (https://github.com/ccxt/ccxt/blob/master/js/bitfinex.js) is adding a separate, undocumented, property called _average_, and putting the limit price in _price_. (Actually I think the problem is mostly with the bitfinex.js code, as it is also missing the _cost_ property which should be straightforward to calculate).

Both values are in fact useful (limit price and average price), so perhaps both should be added and the documentation should be clarified. 

Happy to submit a pull request for some of the issues, although it's my first contribution so would take a while to setup.

**Comment by kroitor** [comment]
>  Is it the average of the executed prices, or is it the limit price the order was issued with?

The initial intent was to make it the issuing price, however, there are two considerations:
- many exchanges only return just *"the price"* (whatever it is, go figure)
- this library is under development, therefore there may be inconsistencies


The latter is related to 

> However I believe some exchanges are violating this definition.

We are happy for all help and we welcome all contributions, but, please, make sure to read this carefully first: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

We are going to change the structure of the order soon to support both prices (both the initial and the actual price). The order API unification is the most difficult part of all, however, more about it here: #71 

Hope it answers your question. Closing it for now, if you don't mind. Feel free to reopen it if needed or just ask questions if any. Thx!

**Comment by cbp123** [comment]
Thanks Igor,

I can try find some time to help by adding the issuedLimitPrice and averageExecutionPrice as separated fields. I think it will make it clearer to contributors, as I've noticed some other exchanges are confused about this field (for example bittrex.js can return either the limit price or the average price in the same field, depending on circumstance).

Would the contribution be better implemented on the current master branch, or do you think there is enough progress on the unified order/trades API that it would be better to work from that branch?

**Comment by kroitor** [comment]
> Would the contribution be better implemented on the current master branch, or do you think there is enough progress on the unified order/trades API that it would be better to work from that branch?

There's no *order/trades API branch* as this is a work in progress, all current code is in the master. Thx!

**Comment by lucasgadams** [comment]
Hi just wanted to continue the discussion here. I'm trying to get the average price a trade was executed at across bittrex and binance and ran into the same problem listed above, different exchanges have a different meaning of price across different endpoints.

For example: 
binance.fetch_my_trades returns a "price" field which is the average price of that trade that i'm looking for.

bittrex.fetch_my_trades isn't implemented but bittrex.fetch_order does work and returns an "averagePrice" field.

binance.fetch_order is implemented but doesn't have the average price field, it only returns the limit order price.

I can help with a PR

**Comment by kroitor** [comment]
> I can help with a PR

Thx! We appreciate all help, just make sure to read this first: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
