### ISSUE TITLE
Huobi error 51 SSL: no alternative certificate

### ISSUE THREAD

**Issue by Bas909** [ccxt/ccxt#2340]
- OS: Linux
- Programming Language version: php
- CCXT version: 1.11.163
- Exchange: huobi.pro
- Method: fetch_balance

> <br /><b>Fatal error</b>:  Uncaught exception 'ccxt\ExchangeNotAvailable' with message 'huobipro GET https://api.huobipro.com/v1/common/symbols 51 SSL: no alternative certificate subject name matches target host name 'api.huobipro.com'' in /home/cctx/php/Exchange.php:746Stack trace:#0 /home/cctx/php/Exchange.php(928): ccxt\Exchange-&gt;raise_error('ExchangeNotAvai...', 'https://api.huo...', 'GET', 51, 'SSL: no alterna...')#1 /home/cctx/php/Exchange.php(771): ccxt\Exchange-&gt;fetch('https://api.huo...', 'GET', NULL, NULL)#2 /home/cctx/php/huobipro.php(573): ccxt\Exchange-&gt;fetch2('common/symbols', 'public', 'GET', Array, NULL, NULL)#3 [internal function]: ccxt\huobipro-&gt;request('common/symbols', 'public', 'GET', Array)#4 /home/cctx/php/Exchange.php(710): call_user_func(Array, 'common/symbols', 'public', 'GET', Array)#5 [internal function]: ccxt\Exchange-&gt;ccxt\{closure}()#6 /home/cctx/php/Exchange.php(1686): call_user_func_array(Object(Closure), Array) in <b>/home/cctx/php/Exchange.php</b> on line <b>746</b><br />

**Comment by Bas909** [comment]
PHP 5.6.34
curl 7.47.0

**Comment by kroitor** [comment]
This is most likely related to certificates installed with your PHP installation... Can you update it and retry with PHP7 to see if it makes a difference?

**Comment by Bas909** [comment]
OK. I'll try.

**Comment by Bas909** [comment]
PHP 7.0.28

> Fatal error: Uncaught exception 'ccxt\ExchangeNotAvailable' with message 'huobipro GET https://api.huobipro.com/v1/common/symbols 7 Failed to connect to api.huobipro.com port 443: Network is unreachable' in /home/cctx/php/Exchange.php:746 Stack trace: #0 /home/cctx/php/Exchange.php(928): ccxt\Exchange->raise_error('ExchangeNotAvai...', 'https://api.huo...', 'GET', 7, 'Failed to conne...') #1 /home/cctx/php/Exchange.php(771): ccxt\Exchange->fetch('https://api.huo...', 'GET', NULL, NULL) #2 /home/cctx/php/huobipro.php(573): ccxt\Exchange->fetch2('common/symbols', 'public', 'GET', Array, NULL, NULL) #3 [internal function]: ccxt\huobipro->request('common/symbols', 'public', 'GET', Array) #4 /home/cctx/php/Exchange.php(710): call_user_func(Array, 'common/symbols', 'public', 'GET', Array) #5 [internal function]: ccxt\Exchange->ccxt\{closure}() #6 /home/cctx/php/Exchange.php(1686): call_user_func_array(Object(Closure), Array) #7 /home/bas/ftp/fil in /home/cctx/php/Exchange.php on line 746

**Comment by kroitor** [comment]
@Bas909 are you able to open this URL in your browser: https://api.huobipro.com/v1/common/symbols ?

**Comment by Bas909** [comment]
yes.

**Comment by kroitor** [comment]
@Bas909 for some reason your cURL installation does not have access to huobipro.com... Might be worth checking and updating your cURL + OpenSSL version as well...

Try this and let us know if it works for you

```PHP
// instantiate the exchange by id
$id = 'huobipro';
$exchange = '\\ccxt\\' . $id;
$exchange = new $exchange (array (
    'api' => 'https://api.huobi.pro', // alternative API base URL
));

// load all markets from the exchange
$markets = $exchange->load_markets ();
var_dump ($markets);
```

**Comment by Bas909** [comment]
http://joxi.ru/a2XE98gFy8aNqA
Access is, but for some reason it is interrupted, although on the local machine (Windows) everything is fine.

**Comment by kroitor** [comment]
This is related to networking setup on your Linux machine, it may have an IP address restricted by Huobi, or whatever... does the alternative URL work for you?

**Comment by Bas909** [comment]
```
// instantiate the exchange by id
$id = 'huobipro';
$exchange = '\\ccxt\\' . $id;
$exchange = new $exchange (array (
    'api' => 'https://api.huobi.pro', // alternative API base URL
));

// load all markets from the exchange
$markets = $exchange->load_markets ();
var_dump ($markets);
``` 
=>
> Warning: Invalid argument supplied for foreach() in /home/bas/ftp/files/cctx/php/Exchange.php on line 686
> 
> Fatal error: Uncaught exception 'ccxt\ExchangeError' with message 'publicGetCommonSymbols not found' in /home/bas/ftp/files/cctx/php/Exchange.php:1689 Stack trace: #0 /home/bas/ftp/files/cctx/php/huobipro.php(103): ccxt\Exchange->__call('publicGetCommon...', Array) #1 /home/bas/ftp/files/cctx/php/huobipro.php(103): ccxt\huobipro->publicGetCommonSymbols() #2 /home/bas/ftp/files/cctx/php/Exchange.php(1083): ccxt\huobipro->fetch_markets() #3 /home/bas/ftp/files/cctx/123.php(11): ccxt\Exchange->load_markets() #4 {main} thrown in /home/bas/ftp/files/cctx/php/Exchange.php on line 1689

**Comment by kroitor** [comment]
@Bas909 sorry, there was a typo there:

```
// instantiate the exchange by id
$id = 'huobipro';
$exchange = '\\ccxt\\' . $id;
$exchange = new $exchange (array (
    'urls' => array (
        'api' => 'https://api.huobi.pro', // alternative API base URL
    ),
));

// load all markets from the exchange
$markets = $exchange->load_markets ();
var_dump ($markets);
```

**Comment by Bas909** [comment]
Yes, it works.
http://joxi.ru/1A5vBl0CKdJ4Mr

**Comment by kroitor** [comment]
@Bas909 well, you should then debug your network connection to huobipro.com or use the overrided alternative API, or, maybe even use both for availability. Sorry, but we can't really consult you on setting up your networking to reach huobipro.com, this isn't related to the ccxt library, but mostly related to your routing tables and your IP/provider. Hope it helps. Closing it for now, if you don't mind, feel free to reopen it if needed, or just ask questions, if any...
