### ISSUE TITLE
Bitbank authentication error

### ISSUE THREAD

**Issue by tuyet130953** [ccxt/ccxt#2342]
OS: Windows
Programming Language version: JS
CCXT version: 1.11.163
Exchange: bitbank
Method: authentication 

Getting API authentication error despite using correct api and secret key. Have also tried resetting keys to make sure.

```
(async () => {
const ccxt = require('ccxt')

//BBANK CT
let exchange = new ccxt.bitbank ({
    apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxx', 
    secret: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
});

let balance = await exchange.fetchBalance ()
console.log(balance)
}) ()     
```

(node:17080) UnhandledPromiseRejectionWarning: Error: API authentication failed
    at bitbank.request (C:\Program Files\nodejs\node_modules\npm\node_modules\ccxt\js\bitbank.js:515:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:17080) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17080) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tuyet130953** [comment]
After fixing/closing issue #2344 , this has now caused the API authentication failed again for fetchBalance.

```
(async () => {
const ccxt = require('ccxt')

let exchange = new ccxt.bitbank ({
    apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxx', 
    secret: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
});

let Order = await exchange.createOrder('XRP/JPY', 'limit', 'sell', 100, 100)
console.log(Order)

let balance = await exchange.fetchBalance ()
console.log(balance)
}) ()    
```



{ id: '24300587',
  datetime: '+050194-05-04T00:56:41.000Z',
  timestamp: 1521813142601000,
  status: 'open',
  symbol: 'XRP/JPY',
  type: 'limit',
  side: 'sell',
  price: 100,
  cost: 0,
  amount: 100,
  filled: 0,
  remaining: 100,
  trades: undefined,
  fee: undefined,
  info:
   { order_id: 24300587,
     pair: 'xrp_jpy',
     side: 'sell',
     type: 'limit',
     start_amount: '100.000000',
     remaining_amount: '100.000000',
     executed_amount: '0.000000',
     price: '100.0000',
     average_price: '0.0000',
     ordered_at: 1521813142601,
     status: 'UNFILLED' } }
(node:7200) UnhandledPromiseRejectionWarning: Error: API authentication failed
    at bitbank.request (C:\Program Files\nodejs\node_modules\npm\node_modules\ccxt\js\bitbank.js:514:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:7200) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7200) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kroitor** [comment]
@tuyet130953 sorry for the inconvenience, finally fixed and uploaded it, the new build version 1.11.167 will arrive in 5-10 minutes. We will be happy if you report back whether it now works normally for you or not. Wait a while for the new version number to appear, then update, then report, plz. Tested locally on our side, should be ok. Thx!

**Comment by tuyet130953** [comment]
@kroitor works great now thanks. Will continue to test other functions and report back if there are any bugs.

**Comment by kroitor** [comment]
@tuyet130953 thx for your feedback!
