### ISSUE TITLE
binance

### ISSUE THREAD

**Issue by b1tboy** [ccxt/ccxt#23427]
### Operating System

windows

### Programming Languages

Python

### CCXT Version

4.3.83

### Description

When projectId contains *, an error is reported：

binance {"code":-1022,"msg":"Signature for this request is not valid."}

### Code

```
  sapi_post_simple_earn_locked_subscribe({'projectId': 'Bnb*60', 'amount': 0.1})

```

**Comment by sc0Vu** [comment]
Hi @b1tboy, Thanks, we'll fix this asap.
