### ISSUE TITLE
southxchange SMT is SmartNode, not SmartMesh

### ISSUE THREAD

**Issue by rsanden** [ccxt/ccxt#2343]
- Programming Language version: Python 3.6
- CCXT version: 1.11.163
- Exchange: southxchange
- Method: fetch_tickers

The CMC winner for SMT is SmartMesh. This is already listed correctly on (for instance) `gateio`.

However on `southxchange` "`SMT`" refers to SmartNode, a different token at a different contract address. I propose a modification something like the following to `southxchange.js`:

```diff
--- a/js/southxchange.js
+++ b/js/southxchange.js
@@ -57,6 +57,9 @@ module.exports = class southxchange extends Exchange {
                     'taker': 0.2 / 100,
                 },
             },
+            'commonCurrencies': {
+                'SMT': 'SMARTNODE',
+            },
         });
     }
```

I did not submit a pull request because I'm not sure how to choose the `SMARTNODE` name here. I looked but did not see this same token listed anywhere else in the codebase, otherwise I would have borrowed that symbol for consistency instead.

**Comment by kroitor** [comment]
Will fix shortly. Thx for reporting!
