### ISSUE TITLE
Inconsistent timestamp format for since/end args in Kraken methods

### ISSUE THREAD

**Issue by ron7684** [ccxt/ccxt#23444]
### Operating System

Ubuntu

### Programming Languages

Python

### CCXT Version

4.3.84

### Description

The timestamp formats for since/end arguments in Kraken methods are inconsistently in seconds or milliseconds.

| Function | since format| end format |
|----------|----------|----------|
| fetchLedger | milliseconds | seconds |
| fetchMyTrades | milliseconds  | seconds |
| fetchDeposits  | seconds | seconds |
| fetchWithdrawals | milliseconds  | seconds |

**Comment by Dan-krm** [comment]
Thanks for reporting I'll look into fixing this

**Comment by Dan-krm** [comment]
@ron7684 I opened a pull request to enable using a milliseconds timestamp for all of the above since and end arguments

**Comment by ron7684** [comment]
My concern is that this is a breaking change and all existing `since` values would now be useless, resulting in all lower bound filters being ignored in existing code.

**Comment by Dan-krm** [comment]
Hi @ron7684 some pull requests were merged so the `since` argument is in milliseconds (the unified approach)
and you can provide the `end` in seconds (exchange specific) or `until/till` in milliseconds
