### ISSUE TITLE
Kraken getMyTrades `takerOrMaker` unfilled

### ISSUE THREAD

**Issue by ron7684** [ccxt/ccxt#23446]
### Operating System

Ubuntu

### Programming Languages

Python

### CCXT Version

8.3.43

### Description

The `takerOrMaker` field in Kraken.getMyTrades() is always `None` despite the native `info` dict containing a boolean `maker` field.

Related to #18986

**Comment by Dan-krm** [comment]
Thanks for pointing this out, I opened a pull request that will populate the `takerOrMaker` field when applicable
