### ISSUE TITLE
Freqtrade no longer working with Mexc due to recent API changes

### ISSUE THREAD

**Issue by rmtucker** [ccxt/ccxt#23467]
### Operating System

Ubuntu 22.04.4

### Programming Languages

Python

### CCXT Version

CCXT 4.3.79

### Description

CCXT has not been working with Mexc for a number of days now due to changes to their API
[https://mexcdevelop.github.io/apidocs/spot_v3_en/#change-log](url)

The change on 16/08/2024 is what seems to have broken it.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @rmtucker, what's broken exactly?

**Comment by rmtucker** [comment]
It can not read the available pairs to begin with.
Unfortunately i shut my freqtrade bot down 3 days ago when the problems started so i can not show logs.
But if it helps i can restart it and give some logs?
Anyone that uses Freqtrade and Mexc is having the same problem.
I raised the issue on Freqtrade github,But they refuse to support it
Here is a copy of the reply from freqtrade support:
Essentially - it's not a problem freqtrade will address - but which needs to be addressed in ccxt.

As it's not a supported exchange - we strongly suggest to use one of the supported exchanges instead.

Alternatively - please do the legwork yourself- which essentially means

    create a reproduction with ccxt code directly
    open an issue against ccxt
    (alternatively, create a Pull Request fixing the issue yourself in ccxt).

For supported exchanges - we're willing and able to take up these points with ccxt.
There's however a reason we have a limited number of supported exchanges - simply because we don't have the capacity to do this for a greater number of exchanges without sacrificing our ability to actually inovate.

Thanks for your understanding.

**Comment by carlosmiei** [comment]
@rmtucker Yes maybe some logs might help, because I just made a few tests and seems to be working, so it's hard to tell what is wrong.

**Comment by carlosmiei** [comment]
@rmtucker Btw if you're talking about this update that impacts the `active` flag inside `market`, that was fixed a few days ago so if you update your ccxt version it should be working as expected:

![image](https://github.com/user-attachments/assets/7545aa25-7c83-4863-99b8-a42fc776a8b5)

**Comment by carlosmiei** [comment]
- relates to https://github.com/freqtrade/freqtrade/issues/10558

**Comment by rmtucker** [comment]
Thank you
v4.3.85 has eventually been pushed through Freqtrade.
Problem solved
