### ISSUE TITLE
Gemini fetchMarkets() return exception

### ISSUE THREAD

**Issue by deltacat** [ccxt/ccxt#2347]
- OS: macOS High Sirrea
- Programming Language version: Nodejs 9.8.0
- CCXT version: 1.11.171
- Exchange: gemini
- Method: fetchMarkets()
- Expect: receive markets info array
- result: always got exception:
>Error: gemini GET https://api.gemini.com/v1/symbols system request to https://api.gemini.com/v1/symbols failed, reason: Parse Error

**Comment by kroitor** [comment]
Can you please post a short snippet of your code to reproduce the issue and the **verbose output** according to this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

**Comment by deltacat** [comment]
Sorry, but it cannot reproduced again.
Not sure what happened. Close it. If it occurred again, will provide more detail report.

One possible reason: that day gemini server cannot reach due to server or network issue.

**Comment by kroitor** [comment]
@deltacat thx for reporting back anyways!
