### ISSUE TITLE
allcoin balances issue

### ISSUE THREAD

**Issue by alexsith** [ccxt/ccxt#2348]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method: fetch_balances

Request: POST https://api.allcoin.com/api/v1/userinfo {'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} api_key=*****&sign=*****

Response: POST https://api.allcoin.com/api/v1/userinfo 200 <CIMultiDictProxy('Cache-Control': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'Date': 'Sat, 24 Mar 2018 06:43:24 GMT', 'Expires': '-1', 'Pragma': 'no-cache', 'Server': 'Microsoft-IIS/8.5', 'X-AspNet-Version': '4.0.30319', 'X-Powered-By': 'ASP.NET', 'Content-Length': '5871', 'Connection': 'keep-alive')> {
  "info": {
    "funds": {
      "free": {
        "a0101": "0.0000000000000000",
        "acc": "0.0000000000000000",
        "act": "0.0000000000000000",
        "aft": "0.0000000000000000",
        "aic": "0.0000000000000000",
        "aicc": "0.0000000000000000",
        "aidoc": "0.0000000000000000",
        "ait": "0.0000000000000000",
        "atn": "0.0000000000000000",
        "awr": "0.0000000000000000",
        "bash": "0.0000000000000000",
        "bcd": "0.0000000000000000",
        "bch": "0.0000000000000000",
        "bec": "0.0000000000000000",
        "bot": "0.0000000000000000",
        "btc": "0.1",
        "bte": "0.0000000000000000",
        "btf": "0.0000000000000000",
        "btg": "0.0000000000000000",
        "btm": "0.0000000000000000",
        "cfs": "0.0000000000000000",
        "cfun": "0.0000000000000000",
        "chp": "0.0000000000000000",
        "ck.usd": "0.0000000000000000",
        "cnet": "0.0000000000000000",
        "dali": "0.0000000000000000",
        "dbc": "0.0000000000000000",
        "dwc": "0.0000000000000000",
        "ent": "0.0000000000000000",
        "eth": "0.0000670000000000",
        "fid": "0.0000000000000000",
        "game": "0.0000000000000000",
        "gnx": "0.0000000000000000",
        "god": "0.0000000000000000",
        "gp": "0.0000000000000000",
        "gram": "0.0000000000000000",
        "gxs": "0.0000000000000000",
        "hlc": "0.0000000000000000",
        "hld": "0.0000000000000000",
        "hpb": "0.0000000000000000",
        "hsr": "0.0000000000000000",
        "icc": "0.0000000000000000",
        "ink": "0.0000000000000000",
        "int": "0.0000000000000000",
        "iqt": "0.0000000000000000",
        "kct": "0.0000000000000000",
        "lbtc": "0.0000000000000000",
        "lmc": "0.0000000000000000",
        "ltc": "0.0000000000000000",
        "mcc": "0.0000000000000000",
        "mda": "0.0000000000000000",
        "mgo": "0.0000000000000000",
        "nas": "0.0000000000000000",
        "neo": "0.0000000000000000",
        "oc": "0.0000000000000000",
        "ont": "0.0000000000000000",
        "pcash": "0.0000000000000000",
        "put": "0.0000000000000000",
        "qbt": "0.0000000000000000",
        "qtum": "0.0000000000000000",
        "sbtc": "0.0000000000000000",
        "sgcc": "50.0000000000000000",
        "she": "0.0000000000000000",
        "sigma": "0.0000000000000000",
        "spc": "0.0000000000000000",
        "tky": "0.0000000000000000",
        "tsl": "0.0000000000000000",
        "ugc": "0.0000000000000000",
        "uip": "0.0000000000000000",
        "walton": "0.0000000000000000",
        "wid": "0.0000000000000000",
        "xkc": "0.0000000000000000",
        "ybct": "0.0000000000000000",
        "yuan": "0.0000000000000000",
        "zec": "0.0000000000000000"
      },
      "freezed": {
        "a0101": "0.0000000000000000",
        "acc": "0.0000000000000000",
        "act": "0.0000000000000000",
        "aft": "0.0000000000000000",
        "aic": "0.0000000000000000",
        "aicc": "0.0000000000000000",
        "aidoc": "0.0000000000000000",
        "ait": "0.0000000000000000",
        "atn": "0.0000000000000000",
        "awr": "0.0000000000000000",
        "bash": "0.0000000000000000",
        "bcd": "0.0000000000000000",
        "bch": "0.0000000000000000",
        "bec": "0.0000000000000000",
        "bot": "0.0000000000000000",
        "btc": "0.0000000000000000",
        "bte": "0.0000000000000000",
        "btf": "0.0000000000000000",
        "btg": "0.0000000000000000",
        "btm": "0.0000000000000000",
        "cfs": "0.0000000000000000",
        "cfun": "0.0000000000000000",
        "chp": "0.0000000000000000",
        "ck.usd": "0.0000000000000000",
        "cnet": "0.0000000000000000",
        "dali": "0.0000000000000000",
        "dbc": "0.0000000000000000",
        "dwc": "0.0000000000000000",
        "ent": "0.0000000000000000",
        "eth": "0.0000000000000000",
        "fid": "0.0000000000000000",
        "game": "0.0000000000000000",
        "gnx": "0.0000000000000000",
        "god": "0.0000000000000000",
        "gp": "0.0000000000000000",
        "gram": "0.0000000000000000",
        "gxs": "0.0000000000000000",
        "hlc": "0.0000000000000000",
        "hld": "0.0000000000000000",
        "hpb": "0.0000000000000000",
        "hsr": "0.0000000000000000",
        "icc": "0.0000000000000000",
        "ink": "0.0000000000000000",
        "int": "0.0000000000000000",
        "iqt": "0.0000000000000000",
        "kct": "0.0000000000000000",
        "lbtc": "0.0000000000000000",
        "lmc": "0.0000000000000000",
        "ltc": "0.0000000000000000",
        "mcc": "0.0000000000000000",
        "mda": "0.0000000000000000",
        "mgo": "0.0000000000000000",
        "nas": "0.0000000000000000",
        "neo": "0.0000000000000000",
        "oc": "0.0000000000000000",
        "ont": "0.0000000000000000",
        "pcash": "0.0000000000000000",
        "put": "0.0000000000000000",
        "qbt": "0.0000000000000000",
        "qtum": "0.0000000000000000",
        "sbtc": "0.0000000000000000",
        "sgcc": "0.0000000000000000",
        "she": "0.0000000000000000",
        "sigma": "0.0000000000000000",
        "spc": "0.0000000000000000",
        "tky": "0.0000000000000000",
        "tsl": "0.0000000000000000",
        "ugc": "0.0000000000000000",
        "uip": "0.0000000000000000",
        "walton": "0.0000000000000000",
        "wid": "0.0000000000000000",
        "xkc": "0.0000000000000000",
        "ybct": "0.0000000000000000",
        "yuan": "0.0000000000000000",
        "zec": "0.0000000000000000"
      }
    }
  },
  "result": "true"
}

returned result:
for BTC: 
{'free': 0.0, 'used': 0.0, 'total': 0.0}

I guess it's because exchange has lower-case currency symbols.

**Comment by kroitor** [comment]
This is fixed in the most recent version, thank you for the feedback!
