### ISSUE TITLE
Binance fetchOrder

### ISSUE THREAD

**Issue by wannesdemaeght** [ccxt/ccxt#2350]
cost is calculated like this: price * filled.
problem is, "price" is not actual price, but bidprice.

using fetchMyTrades, and searching for orderID there does give correct numbers.

Example:

I placed a sell-order for 3.6 LTC @ 0.018825 BTC/LTC

fetchOrder tells me price is 0.018825 BTC, cost is 0.06777 BTC
fetchMyTrades tells me price is 0.018857 BTC, cost is 0.0678852 BTC

**Comment by kroitor** [comment]
Should we set the cost to `undefined` then?

**Comment by wannesdemaeght** [comment]
Don't really know what would be the best way to deal with this.
In userland pepole could just use fetchMyTrades instead to get the dealt orders instead of placed orders.
Problem is, this is not in line with the rest of the exchanges, so not in the spirit of unification...

**Comment by kroitor** [comment]
I'd close this for now, feel free to reopen it if needed. Let us know if we should change the cost to `undefined`. Thx!
