### ISSUE TITLE
[Question]Clarification on `watchOHLCVForSymbols` Minimum Time Frame and Behavior for Multiple Symbol Subscriptions on Binance Pro

### ISSUE THREAD

**Issue by cozy-hn** [ccxt/ccxt#23503]
### Description

It seems that the minimum time frame for the `watchOHLCVForSymbols` function in Binance Pro is `1s` for the Spot market and `1m`  for the Futures market. Is this correct? How can I verify the minimum time unit supported by the exchange?

Also, even when I subscribe to multiple symbols, the function seems to return data for one symbol at a time. Is this the expected behavior? 

Here are some sample outputs:

### Code

```json
{"ETC/USDT":{"1s":[[1724251574000,19.14,19.14,19.14,19.14,0],...]}}

{"BTC/USDT:USDT":{"1m":[[1724251560000,59763.8,59832.4,59723.3,59789.8,409.397]]}}

{"AVAX/USDT":{"1s":[[1724251592000,23.26,23.26,23.26,23.26,0],...]}}

{"BTC/USDT:USDT":{"1m":[[1724251560000,59763.8,59832.4,59723.3,59789.8,409.397]]}}

{"USDC/USDT":{"1s":[[1724251598000,0.9997,0.9997,0.9997,0.9997,0]]}}```

**Comment by carlosmiei** [comment]
Hello @cozy-hn, Yes the exchange streams 1 symbol at a time so `watchOHLCVForSymbols` returns 1 symbol at a time.

**Comment by cozy-hn** [comment]
Thanks for response. I changed fetchOHLCV to this method.
