### ISSUE TITLE
Error with BingX (Place order)

### ISSUE THREAD

**Issue by Ilya243543** [ccxt/ccxt#23510]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.3.50

### Description

I wanted to place market order on BingX and got an error:
How to solve this problem?

### Code

```
symbol = 'FLUXB/USDT'

order = bingx.create_order(
    symbol=symbol,
    type='limit',
    side='buy',
    amount=200,
    price=0.03267,
    params={}
)

logger.info(f"Order created: {order}")

Error
  
bingx {"code":100421,"msg":"The symbol you request is not available to place order currently, please verify symbol's status by api:/openApi/spot/v1/common/symbols","debugMsg":""}
```

**Comment by carlosmiei** [comment]
Hello @Ilya243543, the error message suggests that `FLUXB/USDT` is disabled for trading through the API.

**Comment by Ilya243543** [comment]
> Hello @Ilya243543, the error message suggests that `FLUXB/USDT` is disabled for trading through the API.
Yes, I know, but how can I check it before creating an order. Or can I have a list of coins, that are disabled?

**Comment by carlosmiei** [comment]
Hello @Ilya243543 yes you can check the `active` flag inside `market`, example:

```Python
await exchange.load_markets()
market = exchange.market(symbol)
is_active = market['active']
```

@Ilya243543 Right now, we have a minor issue there and `active` is true when it should not, but we will fix it shortly.

**Comment by Ilya243543** [comment]
> Hello @Ilya243543 yes you can check the `active` flag inside `market`, example:
> 
> ```python
> await exchange.load_markets()
> market = exchange.market(symbol)
> is_active = market['active']
> ```
> 
> @Ilya243543 Right now, we have a minor issue there and `active` is true when it should not, but we will fix it shortly.

Okey, thank you

**Comment by carlosmiei** [comment]
@Ilya243543 If you update your ccxt version the `active` flag should be working as expected now
