### ISSUE TITLE
binance.php: fetchTicker() returns wrong 'timestamp' volume

### ISSUE THREAD

**Issue by cryptonic203** [ccxt/ccxt#2351]
Hello.
fetchTicker() returns:

array (size=20)
  'symbol' => string 'ETH/USDT' (length=8)
  'timestamp' => int 1479512570
  'datetime' => string '1970-01-18T02:58:33.570+00:00' (length=29)
....
1479512570 - is it correct?
How can I get the right timestamp value?
What settings to correct?

Thanks!

**Comment by kroitor** [comment]
Hi!

Can you please provide the following info:
- what's your version of ccxt
- what's the language you're using
- what's the version of that language
- what's your os
- a short snippet of code to reproduce the issue
- verbose output of that snippet

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Without the above we would not be able to help you.

The timestamp is a value in milliseconds, and for Binance this is the full JSON-structure returned:

```
mbp:ccxt igorkroitor$ node examples/js/cli binance fetchTicker ETH/USDT
binance.fetchTicker (ETH/USDT)
{        symbol:   "ETH/USDT",
      timestamp:    1522008688675,
       datetime:   "2018-03-25T20:11:28.675Z",
           high:    540,
            low:    512,
            bid:    526.51,
      bidVolume:    2.63516,
            ask:    527.13,
      askVolume:    7.08158,
           vwap:    521.66797211,
           open:    538.48,
          close:    527.13,
           last:    527.13,
  previousClose:    539.23,
         change:    -11.35,
     percentage:    -2.108,
        average:    undefined,
     baseVolume:    75181.52268,
    quoteVolume:    39219792.4765989,
           info: {             symbol: "ETHUSDT",
                          priceChange: "-11.35000000",
                   priceChangePercent: "-2.108",
                     weightedAvgPrice: "521.66797211",
                       prevClosePrice: "539.23000000",
                            lastPrice: "527.13000000",
                              lastQty: "0.17799000",
                             bidPrice: "526.51000000",
                               bidQty: "2.63516000",
                             askPrice: "527.13000000",
                               askQty: "7.08158000",
                            openPrice: "538.48000000",
                            highPrice: "540.00000000",
                             lowPrice: "512.00000000",
                               volume: "75181.52268000",
                          quoteVolume: "39219792.47659890",
                             openTime:  1521922288675,
                            closeTime:  1522008688675,
                              firstId:  18288068,
                               lastId:  18381528,
                                count:  93461               } }
mbp:ccxt igorkroitor$
```

https://github.com/ccxt/ccxt/wiki/Manual#price-tickers

Closing it for now, feel free to reopen it or just ask questions if any.

**Comment by cryptonic203** [comment]
System info:
cctx: Version 1.10.1 2017-11-06
PHP 5.6
WIndows 10

Code: 
$api=new \ccxt\binance();
$ticker=$api->fetch_ticker('ETH/USDT');
vardump($ticker);

Return:
array (size=20)
'symbol' => string 'ETH/USDT' (length=8)
'timestamp' => int 1844385517
'datetime' => string '1970-01-18T02:58:33.570+00:00' (length=29)
....

'timestamp' => int 1844385517- is it correct?

Full:

array (size=20)
  'symbol' => string 'ETH/USDT' (length=8)
  'timestamp' => int 1844385517
  'datetime' => string '1970-01-22T08:19:46.517+00:00' (length=29)
  'high' => float 466
  'low' => float 440.14
  'bid' => float 450.3
  'bidVolume' => float 0.15361
  'ask' => float 450.62
  'askVolume' => float 1.70037
  'vwap' => float 452.41098246
  'open' => float 453.42
  'close' => float 453.42
  'first' => null
  'last' => float 450.62
  'change' => float -2.8
  'percentage' => float -0.618
  'average' => null
  'baseVolume' => float 94379.11672
  'quoteVolume' => float 42698148.919261
  'info' => 
    array (size=21)
      'symbol' => string 'ETHUSDT' (length=7)
      'priceChange' => string '-2.80000000' (length=11)
      'priceChangePercent' => string '-0.618' (length=6)
      'weightedAvgPrice' => string '452.41098246' (length=12)
      'prevClosePrice' => string '453.42000000' (length=12)
      'lastPrice' => string '450.62000000' (length=12)
      'lastQty' => string '0.05971000' (length=10)
      'bidPrice' => string '450.30000000' (length=12)
      'bidQty' => string '0.15361000' (length=10)
      'askPrice' => string '450.62000000' (length=12)
      'askQty' => string '1.70037000' (length=10)
      'openPrice' => string '453.42000000' (length=12)
      'highPrice' => string '466.00000000' (length=12)
      'lowPrice' => string '440.14000000' (length=12)
      'volume' => string '94379.11672000' (length=14)
      'quoteVolume' => string '42698148.91926070' (length=17)
      'openTime' => float 1522176408301
      'closeTime' => float 1522262808301
      'firstId' => int 18661959
      'lastId' => int 18759586
      'count' => int 97628

**Comment by kroitor** [comment]
@cryptonic203 Your version is too old, please update to most recent one. Thx!
