### ISSUE TITLE
Bybit - exchange.fetch_position_history(symbol) does not work properly

### ISSUE THREAD

**Issue by Karldergrosseausmd** [ccxt/ccxt#23515]
### Operating System

WIN10

### Programming Languages

Python

### CCXT Version

4.3.62

### Description

I opened 4 individual SOL/USDT:USDT contracts at the same time. These then all went into takeprofit. The entire SOL/USDT position is therefore closed.

But when I want to display the position history, CCXT only shows me one position at a time, no matter what limit, params or since I set.

It should show me 4 positions.

### Code

```
exchange = ccxt.bybit({
    'apiKey': xP_j_KEY,
    'secret': xP_j_SEC,
    #'verbose': True,  # for debug output
    'options': {
        'defaultType': 'swap', 
    }
})

exchange.set_sandbox_mode(True)

  def get_pos_history('SOL/USDT:USDT'):    
    params = {}       
    trades = exchange.fetch_position_history(symbol, since=None, limit=None, params=params)
    pprint(trades)

```
{'collateral': None,
 'contractSize': 1.0,
 'contracts': 1.0,
 'datetime': '2024-08-22T14:39:46.079Z',
 'endTime': 1724338637000,
 'entryPrice': 130.863,
 'id': None,
 'info': {'avgEntryPrice': '130.863',
          'avgExitPrice': '144.65',
          'closedPnl': '13.63546785',
          'closedSize': '1',
          'createdTime': '1724337586079',
          'cumEntryValue': '130.863',
          'cumExitValue': '144.65',
          'execType': 'Trade',
          'fillCount': '1',
          'leverage': '10',
          'orderId': 'f6020960-5f20-495b-854b-68859da17bcb',
          'orderPrice': '141.13',
          'orderType': 'Market',
          'qty': '1',
          'side': 'Sell',
          'symbol': 'SOLUSDT',
          'updatedTime': '1724338568665'},
          'fillCount': '1',
          'leverage': '10',
          'orderId': 'f6020960-5f20-495b-854b-68859da17bcb',
          'orderPrice': '141.13',
          'orderType': 'Market',
          'qty': '1',
          'side': 'Sell',
          'symbol': 'SOLUSDT',
          'updatedTime': '1724338568665'},
          'orderType': 'Market',
          'qty': '1',
          'side': 'Sell',
          'symbol': 'SOLUSDT',
          'updatedTime': '1724338568665'},
          'updatedTime': '1724338568665'},
 'initialMargin': 130.863,
 'initialMarginPercentage': 0.9046871759419288,
 'lastPrice': 144.65,
 'lastUpdateTimestamp': 1724338568665,
 'initialMargin': 130.863,
 'initialMarginPercentage': 0.9046871759419288,
 'lastPrice': 144.65,
 'lastUpdateTimestamp': 1724338568665,
 'leverage': 10.0,
 'lastPrice': 144.65,
 'lastUpdateTimestamp': 1724338568665,
 'leverage': 10.0,
 'lastUpdateTimestamp': 1724338568665,
 'leverage': 10.0,
 'leverage': 10.0,
 'liquidationPrice': None,
 'maintenanceMargin': None,
 'maintenanceMarginPercentage': None,
 'marginMode': None,
 'marginRatio': None,
 'markPrice': None,
 'notional': 144.65,
 'percentage': None,
 'realizedPnl': 13.63546785,
 'side': 'long',
 'stopLossPrice': None,
 'symbol': 'SOL/USDT:USDT',
 'takeProfitPrice': None,
 'timestamp': 1724337586079,
 'unrealizedPnl': None}

**Comment by sc0Vu** [comment]
@Karldergrosseausmd Thanks, we'll fix this asap.
