### ISSUE TITLE
Can't get fees for Gemini

### ISSUE THREAD

**Issue by atjason** [ccxt/ccxt#2352]
- OS: Ubuntu 16.04
- Programming Language version: js
- CCXT version: 1.11.172
- Exchange: gemini
- Method: get fees

Please check these code snippet:
```js
    let exchange = new ccxt['gemini']()
    await exchange.loadMarkets()

    console.log(exchange.fees.trading.maker) // undefined
    console.log(exchange.markets['BTC/USD'].maker) // undefined
```

In another side, could get the taker fee. Please help to check, thanks.

[Here](https://gemini.com/trading-fee-schedule/) is the fee document for Gemini.

**Comment by kroitor** [comment]
> `console.log(exchange.fees.trading.maker) // undefined`

This is wrong, therefore `undefined`. There's no reference to that info in the Manual, so you should not rely on it at all.

> Here is the fee document for Gemini.

On the actual fees – we should not hardcode them. Unfortunately, they will not return the fee schedule from their API, just the traded volume itself. We will add default fees to Gemini, but you will have to call their endpoint for traded volumes until we unify the `fees`, more about the work on that is here: https://github.com/ccxt/ccxt/pull/1835

**Comment by atjason** [comment]
@kroitor get it, thanks for your work.

BTW, I also see `exchange.markets[symbol].trading.maker`. Seems it's not documented, but its value is correct. Should not reply on it either, right?

**Comment by kroitor** [comment]
> BTW, I also see exchange.markets[symbol].trading.maker.

*See* where?

```
mbp:ccxt igorkroitor$ node
> const ccxt = require ('./ccxt.js')
undefined
> const exchange = new ccxt.gemini ()
undefined
> ;(async () => { await exchange.loadMarkets(); console.log (exchange.markets['ETH/BTC']); }) ()
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }
> { limits: undefined,
  precision: undefined,
  tierBased: undefined,
  percentage: undefined,
  taker: 0.0025,
  maker: 0.0025,
  id: 'ethbtc',
  symbol: 'ETH/BTC',
  base: 'ETH',
  quote: 'BTC',
  info: 'ethbtc' }
```

**Comment by atjason** [comment]
What I mean is this:

```
const ccxt = require('ccxt')
let exchange = new ccxt['bitfinex']()
await exchange.loadMarkets()
console.log(exchange.markets['ETH/BTC'].maker) // 0.001
console.log(exchange.markets['ETH/BTC'].taker) // 0.002
```

Sometimes, the fee here is more exact, as the fee for different symbol in an exchange may be different.
