### ISSUE TITLE
ErrorException  : Undefined variable: orders in php/Exchange.php: 1263

### ISSUE THREAD

**Issue by vicxyz1** [ccxt/ccxt#2353]
Hello,

After update from 1.10.966 -> 1.11.172, trying to fetch the orders I've got the following error:

 ErrorException  : Undefined variable: orders

  at /home/vagrant/work/cryptobot/vendor/ccxt/ccxt/php/Exchange.php: 1263
  1259:             if (is_array ($grouped) && array_key_exists ($symbol, $grouped))
  1260:                 return $grouped[$symbol];
  1261:             return array ();
  1262:         }
  1263:         return $orders;
  1264:     }
  1265: 
  1266:     public function filterBySymbol ($orders, $symbol = null) {
  1267:         return $this->filter_by_symbol ($orders, $symbol);
  1268:     }

- OS: Ubuntu 16.04
- Programming Language version: PHP
- CCXT version: 1.1.172
- Exchange: Kraken, Bittrex ...
- Method:filter_by_symbol

The fix should be easy, just replacing $orders with $array.

Thanks!

**Comment by kroitor** [comment]
@vicxyz1 thx for reporting! Fixed in 1.12.8.
