### ISSUE TITLE
Minor Wiki documentation error

### ISSUE THREAD

**Issue by cartographer** [ccxt/ccxt#2357]
At the end of the [Loading Markets](https://github.com/ccxt/ccxt/wiki/Manual#loading-markets) section, there is a syntax error with the PHP code.

Currently, it is:

```php
$markets = $huobi.load_markets ();
```

It should use an arrow instead of a period.

```php
$markets = $huobi->load_markets ();
```

**Comment by kroitor** [comment]
Thanks!
