### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib.metadata'

### ISSUE THREAD

**Issue by y0rkl4u** [ccxt/ccxt#23587]
### Operating System

centos7

### Programming Languages

Python

### CCXT Version

4.3.90

### Description

today I upgrade my ccxt to 4.3.90,but when i run my py script ,there is an error: ModuleNotFoundError: No module named 'importlib.metadata',my python verion is 3.7.5

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @y0rkl4u,
Is it possible to update your Python version to at least 3.8? Python 3.7 is not officially supported

**Comment by y0rkl4u** [comment]
After update my python version ,it's work on.
