### ISSUE TITLE
Hyperliquid Fetch_order by clientOrderId

### ISSUE THREAD

**Issue by clemaxique** [ccxt/ccxt#23594]
### Operating System

N/A

### Programming Languages

Python

### CCXT Version

4.3.76

### Description

Hi,

I am unable to retrieve an order by passing clientOrderId in fetch_order due to an issue with self.parse_to_numeric. When I pass clientOrderId (an optional 128-bit hex string, e.g., 0x1234567890abcdef1234567890abcdef), I encounter an InvalidOperation: [<class 'decimal.ConversionSyntax'>] error. This seems to occur because the method expects the ID to be numeric.
https://github.com/ccxt/ccxt/blob/6f62e3363e86ef1d32844a0780fb2955bb645731/python/ccxt/hyperliquid.py#L1683-L1700
According to the Hyperliquid API, you can query order status by either oid or cloid, where oid can represent either order id or clientOrderId. I attempted to monkey patch by removing the parse_numeric method, which resolved the issue.

It's worth noting that order id is numeric, while client order id is a string, yet both are passed from the same parameter, which may cause confusion.

### Code

```


```

**Comment by carlosmiei** [comment]
Hello @clemaxique, thanks for reporting it,we will take a look

**Comment by carlosmiei** [comment]
@clemaxique Managed to reproduce the issue and will be fixed shortly in the linked PR. thanks once again.

**Comment by carlosmiei** [comment]
@clemaxique Can you please upgrade your ccxt version and try again? it should be working now

**Comment by clemaxique** [comment]
It's works well Many thanks @carlosmiei

**Comment by clemaxique** [comment]
It's works well Many thanks @carlosmiei
