### ISSUE TITLE
 How to override end points?

### ISSUE THREAD

**Issue by georgewslee** [ccxt/ccxt#23599]
### Description

I have this create order....
await kucoin.create_order(market, 'market', 'buy', 45000, None, {'hf': True})

the endpoint it uses is: https://api.kucoin.com/api/v1/hf/orders

how can I override it to use https://api.kucoin.com/api/v1/hf/orders/sync instead?

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @georgewslee, right now it is not possible to use that endpoint inside `create_order` but we will add an update that will allow you to do it by providing `sync: true` in `params`

**Comment by carlosmiei** [comment]
@georgewslee Can you upgrade your ccxt version and try again with `sync: true` in `params`? it should be working now

**Comment by georgewslee** [comment]
hello @carlosmiei 

That was quick, thank you very much. I will test it out and come back here if there are any issues.

cheers!
