### ISSUE TITLE
nodejs websocket available ?

### ISSUE THREAD

**Issue by ansonla3** [ccxt/ccxt#2360]
Is it websocket available to use now ?
I saw there was some discussion before, just want to know is it available can use it now ?

ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by kroitor** [comment]
Sorry, not yet. Suggest to move this discussion here: #56
