### ISSUE TITLE
Hyperliquid fetch_balance not correct

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#23601]
### Operating System

n/a

### Programming Languages

Python

### CCXT Version

4.3.92

### Description

Hyperliquid fetch_balance is incorrect, 'free' and 'used' are swapped. 

### Code

```
    from config import config
    e = ccxt.hyperliquid()
    e.aiohttp_proxy = 'http://127.0.0.1:8080'
    e.options['defaultType'] = 'spot'
    await e.load_markets()
    e.walletAddress = config['account']
    e.privateKey = config['privkey']
    pprint((await e.fetch_balance())['USDC'])
    await e.close()

{'free': 11.0, 'total': 24.204227, 'used': 13.204227}
```

From the GUI:
![image](https://github.com/user-attachments/assets/5e3fc4a9-d477-4330-85e4-aa233473f1cd)

**Comment by carlosmiei** [comment]
Hello @gaardiolor, thanks once again, we will take a look shortly.

**Comment by carlosmiei** [comment]
@gaardiolor Can you please upgrade your ccxt version and try again? it should be working now

**Comment by gaardiolor** [comment]
Yes it works, thanks again for the quick fix!
