### ISSUE TITLE
Hyperliquid fetch_tickers - no prices for swap

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#23602]
### Operating System

n/a

### Programming Languages

Python

### CCXT Version

4.3.92

### Description

fetch_tickers returns some prices for spot, but not for swap (hyperliquid api returns the info) 

### Code

```
    e = ccxt.hyperliquid()
    tickers = await e.fetch_tickers()
    for ticker in ['PURR/USDC', 'BTC/USDC:USDC']:
        print(ticker)
        for item in ['close', 'previousClose', 'last']:
            print(f"    {tickers[ticker][item]}")
    await e.close()

PURR/USDC
    0.14032
    0.13383
    0.14032
BTC/USDC:USDC
    None
    None
    None
```

**Comment by carlosmiei** [comment]
Hello @gaardiolor, thanks for reporting it, we will take a look asap.

**Comment by carlosmiei** [comment]
@gaardiolor same thing here, can you upgrade and try again please? I believe this is fixed now

**Comment by gaardiolor** [comment]
Yes it works, thanks!
