### ISSUE TITLE
Python example on thread sync

### ISSUE THREAD

**Issue by kz0** [ccxt/ccxt#2361]
- OS: Linux Ubuntu 16.04 LTS
- Programming Language version: Python 3.5.2
- CCXT version: 1.11.171
- Exchange: HitBTC

Asking if anyone who know his way around python could add an example for thread sync of the exchange instance to avoid the 429.

Regards .

**Comment by kroitor** [comment]
http://lmgtfy.com/?q=python+thread+sync

**Comment by kz0** [comment]
Let me try to explain this better: I instantiate ccxt in the main part of my code and spawn threads each operation to be execute for example a sell. The sell function contains a while true loop that checks the orderbook for the placed order and keeps monitoring the order. Now my problem is since the fetch orderbook call is via the public api and 20 threads calling in parallel cause the rate limit even with the rate limit enabled. That's why i requested an example on how to overcome this issue, what's strange was, i started getting this error only 5 days ago and everything was fine for months before that.

**Comment by kroitor** [comment]
@kz0 basically, the built-in rate limiter is not designed for working from multiple threads, the python3 async version is there for concurrency, with it you don't have to worry about threadsync and all that... I'd recommend to switch to using the async version entirely. However, if, for some reason, you don't want to do that, then you need to add a layer of your code on top of ccxt that would synchronize the rates as you want them for your application, namely:
1. redefine the `nonce()` method
2. redefine the `throttle()` method
2. add atomic increment or a mutex over the nonce value and over the rate limit counters
3. do the locking-unlocking if necessary there
That would help you solve the issue. The library does not have built-in mechanisms for user-specific tasks (multithreading is one of such user-specific tasks), those are usually added on top.

**Comment by kz0** [comment]
@kroitor thank you for taking the time on your reply. i'm not very skilled in python that's why i was using threads instead on async to keep monitoring multiple symbols but per your suggestion i'll port all my code to use async since it gets the same job done.

**Comment by kroitor** [comment]
@kz0 it's not that just switching to `async` will solve it by magic, but, yes, it will be much easier for you to solve the task, because you don't have to worry about all those synchronization primitives. You will still have to do some logic, but the codeflow is usually much more direct if done the `async` way. So, in general, async concurrency mode is easier than thread concurrency.

**Comment by kroitor** [comment]
@kz0 also, I'd recommend to read this: https://github.com/ccxt/ccxt/issues/1399 (all about rate-limiting in ccxt).
