### ISSUE TITLE
Hyperliquid - Couple of issues with fetch_(orders?|closed_orders|open_orders)

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#23617]
### Operating System

n/a

### Programming Languages

Python

### CCXT Version

4.3.93

### Description

Hello,

There are a couple of issues with the various order methods on Hyperliquid.

1: `fetch_closed_orders()` returns all type of orders instead of only closed orders.
```
    orders = await e.fetch_closed_orders()
    statuslist = [order['status'] for order in orders]
    print({item: statuslist.count(item) for item in set(statuslist)})
> {'canceled': 24, 'closed': 21, 'rejected': 8, 'open': 47}
```
Note that the hyperliquid can return the same order multiple times.. An order that was once open but now closed is returned as 'open' and 'closed' with 2 different timestamps.

2: `fetch_open_orders()` returns open orders as status `None`. (`fetch_order()`) does return a correct status)
```
    orders = await e.fetch_open_orders()
    for order in orders:
        print(order['status'])
> None
```

3: `fetch_order()` and `fetch_closed_orders()` doesn't return `filled` correctly. `filled` is always `None`, while it can be calculated as shown below. 
```
    order = await e.fetch_order(order_id, 'PURR/USDC')
    print(f"status_ccxt: {order['status']} filled_ccxt: {order['filled']} remaining_ccxt: {order['remaining']} "
          f"filled_api: {float(order['info']['order']['origSz']) - float(order['info']['order']['sz'])} remaining_api: {order['info']['order']['sz']}")
> status_ccxt: closed filled_ccxt: None remaining_ccxt: 0.0 filled_api: 106.0 remaining_api: 0.0
```

**Comment by sc0Vu** [comment]
Hi @gaardiolor,

Thanks for the report.

1. The data is from their api server, and I think there's no filter parameters for now. I wonder whether it's for our `fetchOrders` api. @carlosmiei hdyt we rename it to `fetchOrders`? Also for the duplicated orders, I'm not sure that we should filter that in the library.

2. There's no status in `fetchOpenOrders` api response. It leads to status: None.

3. I'm not sure about the calculation.

**Comment by gaardiolor** [comment]
Hi @sc0Vu , thanks for your response!

1: I think you could safely filter it in ccxt, by checking for the `status` returned by hyperliquid?
2: Ok, there is a `status` in the hyperliquid api response though, and hyperliquid `openOrders` / `frontendOpenOrders` should only return open orders
3: It's not in their documentation, but I'm pretty sure the calculation is correct, In a while loop I saw `sz` gradually go to 0 as my order got filled, while `origSz` remained the same. But always good to doublecheck.

**Comment by carlosmiei** [comment]
@gaardiolor Thanks a lot for reporting it, we will make the necessary adjustments asap.

**Comment by carlosmiei** [comment]
@gaardiolor regarding 3), I'm not sure if that applies to every order type, for instance I have this open stop-limit order but `sz` is equal to `origSz` in this case 🤔 

```
    order: {
      coin: 'BTC',
      side: 'B',
      limitPx: '50000.0',
      sz: '0.0014',
      oid: '14257696127',
      timestamp: '1725364798705',
      triggerCondition: 'Price above 65000',
      isTrigger: true,
      triggerPx: '65000.0',
      children: [],
      isPositionTpsl: false,
      reduceOnly: false,
      orderType: 'Stop Limit',
      origSz: '0.0014',
      tif: null,
      cloid: null
    },
    status: 'open',
    statusTimestamp: '1725364798705'
  }
```

**Comment by carlosmiei** [comment]
> Note that the hyperliquid can return the same order multiple times.. An order that was once open but now closed is returned as 'open' and 'closed' with 2 different timestamps.

@gaardiolor Regarding this note,  I asked them directly about it because I don't think this is "expected" (I can also see the duplicated orders with different status)

**Comment by carlosmiei** [comment]
@gaardiolor Can you please upgrade and try again? we released a version containing the improvements suggested.

**Comment by gaardiolor** [comment]
Yeah that looks good! didn't test a partially filled order yet, but since everything uses `parse_order()` I trust that will also work, otherwise I'll report back. Thanks!

**Comment by carlosmiei** [comment]
@gaardiolor Yeah everything goes through `parse_order` so it should be working, let us know if anything tho!
