### ISSUE TITLE
hyperliquid fetch_ohlcv behaving wrongly

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#23614]
### Operating System

linux

### CCXT Version

4.3.93

### Description

fetching the latest 50 candles on hyperliquid (50 is an example - it obviously happens on all numbers) - returns not the latest 50 candles - but the earliest available candles.

Aligned with other exchanges, i'd expect ccxt to return the candles "up to now" - not the initial 50 candles.

From the verbose log, it appears like "since" that's sent to the exchange is calculated wrongly...

### Code

``` python
import ccxt
from datetime import datetime, timezone
exchange = ccxt.hyperliquid({
    'options': {'defaultType': 'spot'} 
    })
res = exchange.fetch_ohlcv('PURR/USDC', '1m', limit=50)
print(exchange.iso8601(res[-1][0]))
print(datetime.now(tz=timezone.utc).isoformat())
``` 

output:
```
...
>>> print(exchange.iso8601(res[-1][0]))
2024-08-29T18:22:00.000Z
>>> print(datetime.now(tz=timezone.utc).isoformat())
2024-09-02T04:54:08.513140+00:00

```

**Comment by carlosmiei** [comment]
Hello @xmatthias you're correct it should return the last N candles. we will take a look and let you know

**Comment by carlosmiei** [comment]
@xmatthias Can you upgrade and try again? It should be working as expected now

**Comment by xmatthias** [comment]
Indeed it does :+1:
