### ISSUE TITLE
fetchBalance() no longer works with Kucoin

### ISSUE THREAD

**Issue by hodlerhacks** [ccxt/ccxt#23613]
### Operating System

Windows

### CCXT Version

4.3.91

### Description

After updating from 4.3.24 to 4.3.91, fetchBalance() no longer returns the expected result. This is what I'm getting back:

```
{
  info: { code: '200000', data: [] },
  timestamp: undefined,
  datetime: undefined,
  free: {},
  used: {},
  total: {}
}
```

With other exchanges the code works fine. After rolling back to 4.3.24 it works fine with Kucoin again as well.

### Code

```
  

```

**Comment by sc0Vu** [comment]
@hodlerhacks Why the data is empty list in your result?

**Comment by hodlerhacks** [comment]
@sc0Vu With that change it works. What is this 'hf' parameter? Why wasn't it needed with older CCXT versions?

**Comment by carlosmiei** [comment]
@hodlerhacks Kucoin is migrating some accounts to `high-frequency` and that requires the high frequency API.


Can you please check what `kucoin.privateGetMigrateUserAccountStatus()` returns for you? if it returns 2 it means your acocint is migrated to hf

**Comment by carlosmiei** [comment]
@hodlerhacks If you want to disable the `hf` API completely you can add `exchange.options['hfMigrated'] = False` (CCXT tries to detect this automatically but in your case it seems that it is not working as expected).

If your account returns `status = 2` upon calling `privateGetMigrateUserAccountStatus` please let us know that means kucoin's API is not working as expected and we will escalate it to them.

**Comment by hodlerhacks** [comment]
Hi @carlosmiei, indeed, I get status 2:

```
{ code: '200000', data: { status: 2 } }
```

If I add `exchange.options['hfMigrated'] = false` it works without `{"hf":false}` as well.

As many people use my application in combination with Kucoin, what is my safest option? Stay on v4.3.24 until Kucoin has resolved the issue? Once they have, should my code work again without `exchange.options['hfMigrated'] = false`? (I'm trying to avoid options where possible, to avoid unexpected behavior in the future and/or with other exchanges.)

**Comment by carlosmiei** [comment]
Hello @hodlerhacks, yes for now you can rollback. Can you please share your UID with us (you can ping us on discord/telegram).

**Comment by hodlerhacks** [comment]
Done, pinged you in Discord

**Comment by ttodua** [comment]
unfortunately the frustration comes from the fact that kucoin API seems to be working & responding differently, and we had issues with it. hopefully we would find out & fix soon.

**Comment by hodlerhacks** [comment]
Problem resolved, thanks!
