### ISSUE TITLE
bybit market transaction fee is wrong

### ISSUE THREAD

**Issue by oaixnomis** [ccxt/ccxt#23610]
### Operating System

windows 11

### Programming Languages

JavaScript

### CCXT Version

4.3.93

### Description

taker fee from exchange.markets[symbol] returns 0.006 while from bybit it should be 0.0550 % or 0.0440 % (after discount).

symbol is of any linear perpetual.

### Code

```
  

```

**Comment by sc0Vu** [comment]
@oaixnomis That's the default value. You can get fee with `fetchTradingFees` function.

**Comment by oaixnomis** [comment]
> @oaixnomis That's the default value. You can get fee with `fetchTradingFees` function.

thanks for the explain. is this default behavior just for bybit or for other exchanges as well?

**Comment by carlosmiei** [comment]
@oaixnomis Yes, the fee inside market is the generic one whereas `fetchTradingFees` uses a private endpoint (most of the time) and returns your own fee.
