### ISSUE TITLE
OKX swap order uses currency size instead of contract size

### ISSUE THREAD

**Issue by day-xy** [ccxt/ccxt#23624]
### Operating System

linux

### Programming Languages

python

### CCXT Version

latest

### Description

Hi there,

I have a question if it is possible to place a swap order, e.g., DOGE-USDT-SWAP, using the base currency size instead of the contract size?

If it is not possible, what's the best practice to calculate the contract size based on the currency size for each swap?

**Comment by carlosmiei** [comment]
Hello @day-xy, no you always have to use the contract size because when trading swaps you're buying contracts and not the base currency.

Nonetheless, it's very easy to convert from base currency to the number of contracts, example:

```Python
await exchange.loadMarkets()
symbol = 'XRP/USDT:USDT'
market = exchange.market(symbol)
contract_size = market['contractSize']
base_amount = 100 # amount in XRP
number_of_contracts = base_amount / contract_size
```
