### ISSUE TITLE
how to disable account status check for kucoin hf trade

### ISSUE THREAD

**Issue by georgewslee** [ccxt/ccxt#23627]
### CCXT Version

4.3.94

### Description

I find that my code slowed after updating ccxt to the latest version as it does extra checks.

My code:
await exchange.create_market_buy_order_with_cost( ..., {'hf': True, 'sync': True}  )

made an extra call:
fetch Request: kucoin GET https://api.kucoin.com/api/v3/migrate/user/account/status

before the actual
fetch Request: kucoin POST https://api.kucoin.com/api/v1/hf/orders/sync

Is there a way to disable the call to check account status?

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @georgewslee I think you can set `options['hfMigrated']` to false.

**Comment by carlosmiei** [comment]
@georgewslee Btw, that check is only performed once and the result is cached, you can also preemptively load that check by doing `await kucoin.loadMigrationStatus()` so your `create_order` request is not slowed down by this request.

**Comment by carlosmiei** [comment]
@georgewslee FYI we disabled it by default now to avoid further issues.
