### ISSUE TITLE
Brazilian exchanges not return ohlc?

### ISSUE THREAD

**Issue by claufox** [ccxt/ccxt#2362]
- Exchange: mercado bitcoin, foxbit
- Method: >fetchOHLCV

> fetchOHLCV bitfinex ok
But foxbit (foxbit.php), bitcoin market (mercado.php) does not have this method?

**Comment by kroitor** [comment]
This is a work in progress, some exchanges have that method unified, some don't have it unified yet, but there's always a fallback possibility of using any endpoint available from the exchange via implicit methods: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

So, we do support all their endpoints out of the box, but not all of them have been unified yet. We hope to unify them asap (where possible).

More about it here:
- https://github.com/ccxt/ccxt/wiki/Manual#api-methods--endpoints
- https://github.com/ccxt/ccxt/wiki/Manual#unified-api

Let us know if it does not answer your question. Thx!

**Comment by kroitor** [comment]
<img width="1970" alt="screen shot 2018-03-26 at 22 51 41" src="https://user-images.githubusercontent.com/1294454/37929292-456a7d7e-3148-11e8-8529-384ba4d5b58f.png">

Also, there's a layer of abstraction that emulates missing OHLCV-methods via trades history, until this is unified completely.
