### ISSUE TITLE
fetchLedger Returning 404 Error on Bybit Subaccount (Standard Account, Not UTA)

### ISSUE THREAD

**Issue by henesseye** [ccxt/ccxt#23621]
### Operating System

Debian / Python 3.11.2

### Programming Languages

Python

### CCXT Version

4.3.93

### Description

I am experiencing an issue with the fetchLedger function in the CCXT library when using it with my Bybit account. Although the API key has been correctly issued with the appropriate permissions for a subaccount on Bybit, and other functions like fetch_balance work correctly, fetchLedger consistently returns a 404 error.

Details:
Account Type: Non-unified Trading Account (Standard Subaccount)
API Version: The logs indicate that the fetchLedger function is making requests to Bybit's V2 API.
Error: The API returns a 404 error when attempting to fetch ledger entries.
Working Functions: Functions like fetch_balance work without issues using the same API key.
Question: Is the V2 API endpoint for fetchLedger still operational, or does this function require specific parameters or routes that I might be missing for non-unified accounts on Bybit? If the V2 API is deprecated, what is the correct approach for fetching ledger entries on non-unified Bybit accounts?

Thank you for your assistance in resolving this issue.

Log
Errormessage: bybit GET https://api.bybit.com/v2/private/wallet/fund/records?api_key=*****1Jddqe2PXu&recv_window=5000&timestamp=1725265609966&sign=f36c7c970fa******985b62ea02dbe2bf382de04c71a4b25ed68470853 404 Not Found Not Found

### Code

```
def create_exchange_instance():
    logging.info(f"Create Exchange Instance for {EXCHANGE}")
    exchange_class = getattr(ccxt, EXCHANGE)
    exchange = exchange_class({
        'apiKey': API_KEY,
        'secret': API_SECRET,
        'enableRateLimit': True,
    })
    logging.info(f"Exchange-Instance created: {exchange}")
    return exchange

def calculate_total_pnl(exchange):
    try:
        # Get LedgerEntries for USDT
        ledger_entries = exchange.fetchLedger("USDT")

        logging.info(f"Ledger Entries: {ledger_entries}")

        total_pnl = 0.0
        for entry in ledger_entries:
            if entry['type'] == 'RealisedPNL':  # 
                pnl = entry.get('amount', 0)
                total_pnl += pnl

        logging.info(f"Calc PNL: {total_pnl} USDT")
        return f"PNL: {total_pnl:.2f} USDT"
    except ccxt.BaseError as e:
        logging.error(f"Error Calculating PNL: {e}")
        return f"Error Calculating PNL: {e}"
  


```

**Comment by carlosmiei** [comment]
Hello @henesseye, thanks for letting us know.

Can you please try this to see if it works? `bybit.privateGetV5AccountTransactionLog()`? I think that `https://api.bybit.com/v2/private/wallet/fund/records` was probably deprecated and we will update `fetchLedger` asap.

**Comment by henesseye** [comment]
Hey @carlosmiei 
thank you for your reply. i manually changed it in bybit.py and now the 404 is gone and I get the ledger entries
but i am not sure which params in my case are the suitable ones.
as a mentioned, i'm on a subaccount on a classic account (Non UTA)
i want to fetch my ledger from the derivative account (USDT Margined)

here is what i changed manually in bybit.py

        if enableUnified[1]:
            if subType == 'inverse':
                response = self.privateGetV5AccountContractTransactionLog(self.extend(request, params))
            else:
                response = self.privateGetV5AccountTransactionLog(self.extend(request, params))
        else:
            response = self.privateGetV5AccountContractTransactionLog(self.extend(request, params))

**Comment by henesseye** [comment]
i pulled the newest ccxt version via pip --upgrade ccxt. it shows that i'm on 4.3.95, but in the bybit.py there is still the old V2 endpoint.

**Comment by carlosmiei** [comment]
@henesseye the pr linked above wasn't released yet: https://github.com/ccxt/ccxt/commits/master/ will be in a few hours.

@henesseye Upon calling `privateGetV5AccountContractTransactionLog` what do you get?

**Comment by henesseye** [comment]
@carlosmiei i get something like this. it looks like it's working. now i need to figure out how the pagination / cursor stuff is working on bybit.

Ledger Entries: [{'id': '6176591', 'currency': 'USDT', 'account': None, 'referenceAccount': None, 'referenceId': None, 'status': None, 'amount': 0.0031163, 'before': 28.78626331, 'after': 28.78937961, 'fee': 0.0031163, 'direction': 'out', 'timestamp': 1725028110523, 'datetime': '2024-08-30T14:28:30.523Z', 'type': 'trade', 'info': {'id': '6176591', 'symbol': 'CLOUDUSDT', 'category': 'linear', 'side': 'Sell', 'transactionTime': '1725028110523', 'type': 'TRADE', 'qty': '20', 'size': '-20', 'currency': 'USDT', 'tradePrice': '0.2833', 'funding': '', 'fee': '0.00311630', 'cashFlow': '0.00000000', 'change': '-0.00311630', 'cashBalance': '28.78937961', 'feeRate': '0.00055000', 'bonusChange': '', 'tradeId': '5de98917-122b-5ef5-9b8d-1da422dc15dd', 'orderId': '76747686-1216-455b-9a1d-6a4730dccb57', 'orderLinkId': ''}}, {'id': '6178590', 'currency': 'USDT', 'account': None, 'referenceAccount': None, 'referenceId': None, 'status': None, 'amount': 0.1449651, 'before': 28.78937961, 'after': 28.93434471, 'fee': 0.0030349, 'direction': 'in', 'timestamp': 1725029274888, 'datetime': '2024-08-30T14:47:54.888Z', 'type': 'trade', 'info': {'id': '6178590', 'symbol': 'CLOUDUSDT', 'category': 'linear', 'side': 'Buy', 'transactionTime': '1725029274888', 'type': 'TRADE', 'qty': '20', 'size': '0', 'currency': 'USDT', 'tradePrice': '0.2759', 'funding': '', 'fee': '0.00303490', 'cashFlow': '0.14800000', 'change': '0.14496510', 'cashBalance': '28.93434471', 'feeRate': '0.00055000', 'bonusChange': '', 'tradeId': '1096fb6b-7e8a-5d04-9c96-87e5574594d0', 'orderId': 'b9ade3fe-e956-4c90-9699-1fa1b8df9168', 'orderLinkId': ''}}, {'id': '6197072', 'currency': 'USDT', 'account': None, 'referenceAccount': None, 'referenceId': None, 'status': None, 'amount': 0.0031548, 'before': 28.92803511, 'after': 28.93118991, 'fee': 0.0031548, 'direction': 'out', 'timestamp': 1725034240452, 'datetime': '2024-08-30T16:10:40.452Z', 'type': 'trade', 'info': {'id': '6197072', 'symbol': 'POPCATUSDT', 'category': 'linear', 'side': 'Buy', 'transactionTime': '1725034240452', 'type': 'TRADE', 'qty': '10', 'size': '10', 'currency': 'USDT', 'tradePrice': '0.5736', 'funding': '', 'fee': '0.00315480', 'cashFlow': '0.00000000', 'change': '-0.00315480', 'cashBalance': '28.93118991', 'feeRate': '0.00055000', 'bonusChange': '', 'tradeId': 'bd636890-7917-5416-b860-e0b9eb912d0e', 'orderId': '9fc8a65f-ea4d-4ebc-8cf5-28672270c632', 'orderLinkId': ''}}, {'id': '6199051', 'currency': 'USDT', 'account': None, 'referenceAccount': None, 'referenceId': None, 'status': None, 'amount': 0.119091, 'before': 28.69300791, 'after': 28.81209891, 'fee': 0.003091, 'direction': 'out', 'timestamp': 1725035013488, 'datetime': '2024-08-30T16:23:33.488Z', 'type': 'trade', 'info': {'id': '6199051', 'symbol': 'POPCATUSDT', 'category': 'linear', 'side': 'Sell', 'transactionTime': '1725035013488', 'type': 'TRADE', 'qty': '10', 'size': '0', 'currency': 'USDT', 'tradePrice': '0.5620', 'funding': '', 'fee': '0.00309100', 'cashFlow': '-0.11600000', 'change': '-0.11909100', 'cashBalance': '28.81209891', 'feeRate': '0.00055000', 'bonusChange': '', 'tradeId': '61b5a44a-37e8-5dd8-8baa-284ed31d166d', 'orderId': '58e44bce-f4a2-4a3e-927d-5728be0bc5f9', 'orderLinkId': ''}}, {'id': '6279032', 'currency': 'USDT', 'account': None, 'referenceAccount': None, 'referenceId': None, 'status': None, 'amount': 0.00317007, 'before': 28.80575877, 'after': 28.80892884, 'fee': 0.00317007, 'direction': 'out', 'timestamp': 1725164286956, 'datetime': '2024-09-01T04:18:06.956Z', 'type': 'trade', 'info': {'id': '6279032', 'symbol': 'PEOPLEUSDT', 'category': 'linear', 'side': 'Buy', 'transactionTime': '1725164286956', 'type': 'TRADE', 'qty': '87', 'size': '87', 'currency': 'USDT', 'tradePrice': '0.06625', 'funding': '', 'fee': '0.00317007', 'cashFlow': '0.00000000', 'change': '-0.00317007', 'cashBalance': '28.80892884', 'feeRate': '0.00055000', 'bonusChange': '', 'tradeId': 'e116ec80-71e3-5bbf-a9ae-d66798d7cc2d', 'orderId': '3311f55c-1de7-44fa-babd-c2bf9ae04f99', 'orderLinkId': ''}}, {'id': '6287384', 'currency': 'USDT', 'account': None, 'referenceAccount': None, 'referenceId': None, 'status': None, 'amount': 0.00046343, 'before': 28.80800198, 'after': 28.80846541, 'fee': None, 'direction': 'out', 'timestamp': 1725177600000, 'datetime': '2024-09-01T08:00:00.000Z', 'type': 'trade', 'info': {'id': '6287384', 'symbol': 'PEOPLEUSDT', 'category': 'linear', 'side': 'Buy', 'transactionTime': '1725177600000', 'type': 'SETTLEMENT', 'qty': '87', 'size': '87', 'currency': 'USDT', 'tradePrice': '0.06631', 'funding': '0.00046343', 'fee': '', 'cashFlow': '0.00000000', 'change': '-0.00046343', 'cashBalance': '28.80846541', 'feeRate': '0.00008033', 'bonusChange': '', 'tradeId': 'c8f6391c-080e-4dd1-be91-c2a46f10d725', 'orderId': '', 'orderLinkId': ''}}, {'id': '6300004', 'currency': 'USDT', 'account': None, 'referenceAccount': None, 'referenceId': None, 'status': None, 'amount': 0.11794691, 'before': 28.57257159, 'after': 28.6905185, 'fee': 0.00310691, 'direction': 'out', 'timestamp': 1725197329134, 'datetime': '2024-09-01T13:28:49.134Z', 'type': 'trade', 'info': {'id': '6300004', 'symbol': 'PEOPLEUSDT', 'category': 'linear', 'side': 'Sell', 'transactionTime': '1725197329134', 'type': 'TRADE', 'qty': '87', 'size': '0', 'currency': 'USDT', 'tradePrice': '0.06493', 'funding': '', 'fee': '0.00310691', 'cashFlow': '-0.11484000', 'change': '-0.11794691', 'cashBalance': '28.69051850', 'feeRate': '0.00055000', 'bonusChange': '', 'tradeId': 'fd5b8f34-9e62-5e34-a51e-ff9849975a3b', 'orderId': 'f06a8c31-e7e6-4cbe-aafc-14c90722fe51', 'orderLinkId': ''}}, {'id': '6494416', 'currency': 'USDT', 'account': None, 'referenceAccount': None, 'referenceId': None, 'status': None, 'amount': 0.00238535, 'before': 28.6857478, 'after': 28.68813315, 'fee': 0.00238535, 'direction': 'out', 'timestamp': 1725392915424, 'datetime': '2024-09-03T19:48:35.424Z', 'type': 'trade', 'info': {'id': '6494416', 'symbol': 'AVAXUSDT', 'category': 'linear', 'side': 'Buy', 'transactionTime': '1725392915424', 'type': 'TRADE', 'qty': '0.2', 'size': '0.2', 'currency': 'USDT', 'tradePrice': '21.685', 'funding': '', 'fee': '0.00238535', 'cashFlow': '0.00000000', 'change': '-0.00238535', 'cashBalance': '28.68813315', 'feeRate': '0.00055000', 'bonusChange': '', 'tradeId': '8ac9c942-04eb-5fa7-85a7-6e314447ce31', 'orderId': 'c0cc17d8-7ac7-4b0f-9b0b-a0de55c1c7cc', 'orderLinkId': ''}}, {'id': '6494421', 'currency': 'USDT', 'account': None, 'referenceAccount': None, 'referenceId': None, 'status': None, 'amount': 0.00297486, 'before': 28.68218343, 'after': 28.68515829, 'fee': 0.00297486, 'direction': 'out', 'timestamp': 1725392956680, 'datetime': '2024-09-03T19:49:16.680Z', 'type': 'trade', 'info': {'id': '6494421', 'symbol': 'SUNUSDT', 'category': 'linear', 'side': 'Buy', 'transactionTime': '1725392956680', 'type': 'TRADE', 'qty': '180', 'size': '180', 'currency': 'USDT', 'tradePrice': '0.030049', 'funding': '', 'fee': '0.00297486', 'cashFlow': '0.00000000', 'change': '-0.00297486', 'cashBalance': '28.68515829', 'feeRate': '0.00055000', 'bonusChange': '', 'tradeId': '0d8c760e-9e2b-58a6-910c-a0b68d34374c', 'orderId': '9a8a43ae-b183-437c-9bae-c3b0ff9d6ec0', 'orderLinkId': ''}}, {'id': '6494503', 'currency': 'USDT', 'account': None, 'referenceAccount': None, 'referenceId': None, 'status': None, 'amount': 0.00304358, 'before': 28.67907113, 'after': 28.68211471, 'fee': 0.00304358, 'direction': 'out', 'timestamp': 1725393059346, 'datetime': '2024-09-03T19:50:59.346Z', 'type': 'trade', 'info': {'id': '6494503', 'symbol': 'PEOPLEUSDT', 'category': 'linear', 'side': 'Buy', 'transactionTime': '1725393059346', 'type': 'TRADE', 'qty': '94', 'size': '94', 'currency': 'USDT', 'tradePrice': '0.05887', 'funding': '', 'fee': '0.00304358', 'cashFlow': '0.00000000', 'change': '-0.00304358', 'cashBalance': '28.68211471', 'feeRate': '0.00055000', 'bonusChange': '', 'tradeId': 'af934eda-2a96-5b26-b9fc-87e88517edf7', 'orderId': '5c2b5f84-4015-4f20-aca9-fc7236f62053', 'orderLinkId': ''}}, {'id': '6494531', 'currency': 'USDT', 'account': None, 'referenceAccount': None, 'referenceId': None, 'status': None, 'amount': 0.00282497, 'before': 28.67646477, 'after': 28.67928974, 'fee': 0.00282497, 'direction': 'out', 'timestamp': 1725393115732, 'datetime': '2024-09-03T19:51:55.732Z', 'type': 'trade', 'info': {'id': '6494531', 'symbol': 'POPCATUSDT', 'category': 'linear', 'side': 'Buy', 'transactionTime': '1725393115732', 'type': 'TRADE', 'qty': '9', 'size': '9', 'currency': 'USDT', 'tradePrice': '0.5707', 'funding': '', 'fee': '0.00282497', 'cashFlow': '0.00000000', 'change': '-0.00282497', 'cashBalance': '28.67928974', 'feeRate': '0.00055000', 'bonusChange': '', 'tradeId': '14eb97d3-4ff7-5185-8bac-5b58b1df42be', 'orderId': 'bad0a317-e6d8-4e25-a509-71b78cb6b5ea', 'orderLinkId': ''}}, {'id': '6494532', 'currency': 'USDT', 'account': None, 'referenceAccount': None, 'referenceId': None, 'status': None, 'amount': 0.00282694, 'before': 28.67363586, 'after': 28.6764628, 'fee': 0.00282694, 'direction': 'out', 'timestamp': 1725393121295, 'datetime': '2024-09-03T19:52:01.295Z', 'type': 'trade', 'info': {'id': '6494532', 'symbol': '1000PEPEUSDT', 'category': 'linear', 'side': 'Buy', 'transactionTime': '1725393121295', 'type': 'TRADE', 'qty': '700', 'size': '700', 'currency': 'USDT', 'tradePrice': '0.0073427', 'funding': '', 'fee': '0.00282694', 'cashFlow': '0.00000000', 'change': '-0.00282694', 'cashBalance': '28.67646280', 'feeRate': '0.00055000', 'bonusChange': '', 'tradeId': '90e47736-b9c9-5cfd-9b63-2f65e183637c', 'orderId': 'df081fba-7a30-44d5-85e9-e21a85ef5798', 'orderLinkId': ''}}, {'id': '6497137', 'currency': 'USDT', 'account': None, 'referenceAccount': None, 'referenceId': None, 'status': None, 'amount': 0.10536854, 'before': 28.46572572, 'after': 28.57109426, 'fee': 0.00276854, 'direction': 'out', 'timestamp': 1725399002918, 'datetime': '2024-09-03T21:30:02.918Z', 'type': 'trade', 'info': {'id': '6497137', 'symbol': 'POPCATUSDT', 'category': 'linear', 'side': 'Sell', 'transactionTime': '1725399002918', 'type': 'TRADE', 'qty': '9', 'size': '0', 'currency': 'USDT', 'tradePrice': '0.5593', 'funding': '', 'fee': '0.00276854', 'cashFlow': '-0.10260000', 'change': '-0.10536854', 'cashBalance': '28.57109426', 'feeRate': '0.00055000', 'bonusChange': '', 'tradeId': 'dae03726-dfca-5d62-bdfb-16e98b49c8b4', 'orderId': '0d84564a-17d0-4cea-a66f-85b891106416', 'orderLinkId': ''}}, {'id': '6500772', 'currency': 'USDT', 'account': None, 'referenceAccount': None, 'referenceId': None, 'status': None, 'amount': 0.1197306, 'before': 28.33163306, 'after': 28.45136366, 'fee': 0.0029106, 'direction': 'out', 'timestamp': 1725407214178, 'datetime': '2024-09-03T23:46:54.178Z', 'type': 'trade', 'info': {'id': '6500772', 'symbol': 'SUNUSDT', 'category': 'linear', 'side': 'Sell', 'transactionTime': '1725407214178', 'type': 'TRADE', 'qty': '180', 'size': '0', 'currency': 'USDT', 'tradePrice': '0.029400', 'funding': '', 'fee': '0.00291060', 'cashFlow': '-0.11682000', 'change': '-0.11973060', 'cashBalance': '28.45136366', 'feeRate': '0.00055000', 'bonusChange': '', 'tradeId': 'a1d68898-7886-5920-b28a-b0958cc5a052', 'orderId': '210a07b6-2858-4de4-b089-c48495bca2a9', 'orderLinkId': ''}}, {'id': '6506199', 'currency': 'USDT', 'account': None, 'referenceAccount': None, 'referenceId': None, 'status': None, 'amount': 0.00050845, 'before': 28.45157157, 'after': 28.45208002, 'fee': None, 'direction': 'out', 'timestamp': 1725408000000, 'datetime': '2024-09-04T00:00:00.000Z', 'type': 'trade', 'info': {'id': '6506199', 'symbol': '1000PEPEUSDT', 'category': 'linear', 'side': 'Buy', 'transactionTime': '1725408000000', 'type': 'SETTLEMENT', 'qty': '700', 'size': '700', 'currency': 'USDT', 'tradePrice': '0.0072635', 'funding': '0.00050845', 'fee': '', 'cashFlow': '0.00000000', 'change': '-0.00050845', 'cashBalance': '28.45208002', 'feeRate': '0.00010000', 'bonusChange': '', 'tradeId': 'f593bd3c-3d5e-4060-a5f1-316e47b25ef7', 'orderId': '', 'orderLinkId': ''}}, {'id': '6502765', 'currency': 'USDT', 'account': None, 'referenceAccount': None, 'referenceId': None, 'status': None, 'amount': 0.0017702, 'before': 28.45081827, 'after': 28.45258847, 'fee': None, 'direction': 'in', 'timestamp': 1725408000000, 'datetime': '2024-09-04T00:00:00.000Z', 'type': 'trade', 'info': {'id': '6502765', 'symbol': 'AVAXUSDT', 'category': 'linear', 'side': 'Buy', 'transactionTime': '1725408000000', 'type': 'SETTLEMENT', 'qty': '0.2', 'size': '0.2', 'currency': 'USDT', 'tradePrice': '21.370', 'funding': '-0.00177020', 'fee': '', 'cashFlow': '0.00000000', 'change': '0.00177020', 'cashBalance': '28.45258847', 'feeRate': '-0.00041418', 'bonusChange': '', 'tradeId': '788d1817-e3c8-4a06-a3d7-b1982b2aa75d', 'orderId': '', 'orderLinkId': ''}}, {'id': '6502690', 'currency': 'USDT', 'account': None, 'referenceAccount': None, 'referenceId': None, 'status': None, 'amount': 0.00054539, 'before': 28.45027288, 'after': 28.45081827, 'fee': None, 'direction': 'out', 'timestamp': 1725408000000, 'datetime': '2024-09-04T00:00:00.000Z', 'type': 'trade', 'info': {'id': '6502690', 'symbol': 'PEOPLEUSDT', 'category': 'linear', 'side': 'Buy', 'transactionTime': '1725408000000', 'type': 'SETTLEMENT', 'qty': '94', 'size': '94', 'currency': 'USDT', 'tradePrice': '0.05802', 'funding': '0.00054539', 'fee': '', 'cashFlow': '0.00000000', 'change': '-0.00054539', 'cashBalance': '28.45081827', 'feeRate': '0.00010000', 'bonusChange': '', 'tradeId': 'a0cb11cd-4124-47c8-bb3e-474e7bcf4f97', 'orderId': '', 'orderLinkId': ''}}, {'id': '6509153', 'currency': 'USDT', 'account': None, 'referenceAccount': None, 'referenceId': None, 'status': None, 'amount': 0.10462093, 'before': 28.24283816, 'after': 28.34745909, 'fee': 0.00277093, 'direction': 'out', 'timestamp': 1725411328429, 'datetime': '2024-09-04T00:55:28.429Z', 'type': 'trade', 'info': {'id': '6509153', 'symbol': '1000PEPEUSDT', 'category': 'linear', 'side': 'Sell', 'transactionTime': '1725411328429', 'type': 'TRADE', 'qty': '700', 'size': '0', 'currency': 'USDT', 'tradePrice': '0.0071972', 'funding': '', 'fee': '0.00277093', 'cashFlow': '-0.10185000', 'change': '-0.10462093', 'cashBalance': '28.34745909', 'feeRate': '0.00055000', 'bonusChange': '', 'tradeId': 'b6154d9a-da93-576c-8326-6059634446e6', 'orderId': '39a0248b-778e-4cac-9b63-fe7b349f0180', 'orderLinkId': ''}}, {'id': '6509541', 'currency': 'USDT', 'account': None, 'referenceAccount': None, 'referenceId': None, 'status': None, 'amount': 0.0893375, 'before': 28.16878409, 'after': 28.25812159, 'fee': 0.0023375, 'direction': 'out', 'timestamp': 1725411369285, 'datetime': '2024-09-04T00:56:09.285Z', 'type': 'trade', 'info': {'id': '6509541', 'symbol': 'AVAXUSDT', 'category': 'linear', 'side': 'Sell', 'transactionTime': '1725411369285', 'type': 'TRADE', 'qty': '0.2', 'size': '0.0', 'currency': 'USDT', 'tradePrice': '21.250', 'funding': '', 'fee': '0.00233750', 'cashFlow': '-0.08700000', 'change': '-0.08933750', 'cashBalance': '28.25812159', 'feeRate': '0.00055000', 'bonusChange': '', 'tradeId': 'ad013a55-e8b8-5569-80f4-50db9890291c', 'orderId': '7dbb7002-7fe4-4ebb-8eb8-c27109a2a790', 'orderLinkId': ''}}, {'id': '6510637', 'currency': 'USDT', 'account': None, 'referenceAccount': None, 'referenceId': None, 'status': None, 'amount': 0.11672103, 'before': 28.02467953, 'after': 28.14140056, 'fee': 0.00298103, 'direction': 'out', 'timestamp': 1725411610654, 'datetime': '2024-09-04T01:00:10.654Z', 'type': 'trade', 'info': {'id': '6510637', 'symbol': 'PEOPLEUSDT', 'category': 'linear', 'side': 'Sell', 'transactionTime': '1725411610654', 'type': 'TRADE', 'qty': '94', 'size': '0', 'currency': 'USDT', 'tradePrice': '0.05766', 'funding': '', 'fee': '0.00298103', 'cashFlow': '-0.11374000', 'change': '-0.11672103', 'cashBalance': '28.14140056', 'feeRate': '0.00055000', 'bonusChange': '', 'tradeId': '20ab144f-518e-5d66-af20-31dbbcf4e48f', 'orderId': '32288ca7-3f53-4486-b488-8b0e815e012d', 'orderLinkId': '', 'nextPageCursor': 'cursor_id%3D6176591%26time_e9%3D1725028110523354000%26'}}]

**Comment by carlosmiei** [comment]
@henesseye we will try to add automatic pagination there as well.

**Comment by carlosmiei** [comment]
@henesseye If you. update your CCXT version you can use automatic pagination by providing `paginate: True` in `params` upon calling `fetch_ledger`

**Comment by henesseye** [comment]
@carlosmiei thx for your support. i updated my CCXT version and tried the automatic pagination.
I'm using fetch_ledger with params = {'paginate': True} to retrieve all ledger entries, and I'm passing the since parameter set to an earlier date (e.g., since = 01.01.2024). However, no matter how far back I set the since parameter, the API only returns entries from the last 7 days. For example, even with since set to 01.07.2024, I only receive entries starting from 02.09.2024.

It seems like Bybit is restricting the data to the last 7 days, and I cannot retrieve older ledger entries, even with pagination enabled. Is this a known limitation of the Bybit API? Is there any way to fetch a complete list of entries, or is this restricted to a 7-day window?

**Comment by henesseye** [comment]
@carlosmiei 
### Issue: Incomplete Ledger Entries with Bybit and Pagination

When fetching ledger entries using `fetch_ledger` on Bybit, I initially expected the `paginate: True` parameter to handle the automatic pagination over large datasets. However, I encountered two main issues:

1. **7-Day Time Window Restriction**: Bybit enforces a rule where the time range between `startTime` and `endTime` cannot exceed 7 days. Even with `paginate: True`, the `fetch_ledger` function does not automatically handle this restriction and will return an error if the time window exceeds 7 days.
   
2. **Incomplete Results**: Despite using `paginate: True`, the returned ledger entries were still limited to the 7-day window, and no automatic iteration beyond that timeframe occurred.

### Solution:
To resolve this, I manually iterated through the entire date range in 7-day windows. Here's what I did:
1. **Manual 7-Day Iteration**: I split the entire requested date range into 7-day intervals, making separate `fetch_ledger` calls for each window.
2. **Pagination within Each Window**: For each 7-day window, I passed the `paginate: True` parameter to handle pagination across multiple pages of results.
3. **Combined Results**: I aggregated the ledger entries from all 7-day windows to get the full list of transactions over the desired time period.

This approach successfully fetched all ledger entries without exceeding Bybit's 7-day limit and made use of the `paginate: True` parameter to handle pagination within each time window.
