### ISSUE TITLE
Hyperliquid - Incorrect symbol in fetch_my_trades()

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#23633]
### Operating System

n/a

### Programming Languages

Python

### CCXT Version

4.3.95

### Description

Hello again :)

The `symbol` returned for spot markets in `fetch_my_trades()` (and probably the other trade methods) is not correct. `/USDC:USC` is getting appended here:
https://github.com/ccxt/ccxt/blob/734560bf2310aea0a54d5b4007bc631cf8d5043a/python/ccxt/hyperliquid.py#L2016

but that's not valid for sport markets, because of a couple of reasons:
1) For spot markets it would be /USDC, not /USDC:USDC
2) For spot markets, Hyperliquid returns the id instead of the symbol part before the '/'
    - sometimes the returned id is the same as the name, `PURR/USDC` . I think this is the only example where the id is the same as the name. 
    - in other cases id's are returned, for example `@1` is returned for the market HFUN/USDC
    - in both cases, the id can be converted to the name in the same way, by using `markets_by_id`. So for the exception PURR/USDC converting the id to the name should also work, as this is both the market['name'] and market['id']. 

```
    print(len(await e.fetch_my_trades('PURR/USDC')))  # Correct market, but returns 0
    print(len(await e.fetch_my_trades('PURR/USDC/USDC:USDC')))  # Incorrect market, returns the correct amount of trades
>0
> 15 
```

I think it can be fixed by first checking if the trade returned by hyperliquid is a spot trade or a perps trade. You can distinct between spot and perp trades by looking at the 'dir' field in the trades returned by hyperliquid. 
If it's a spot trade, lookup the name from self.markets_by_id, if not append '/USDC:USDC'. 

If `trade` is a trade returned by the hyperliquid api:
```
spot = True if trade['dir'] in ['Buy', 'Sell'] else False
marketId = self.markets_by_id[trade['coin']]['name'] if spot else trade['coin'] + '/USDC:USDC' 
```

thanks

**Comment by carlosmiei** [comment]
@gaardiolor Hello again :)

Thanks, hyperliquid initially only supported swaps  (hence the blind append) so this is probably a missing implementation but we will update it asap.

**Comment by carlosmiei** [comment]
Hello again, @gaardiolor. Can you please upgrade and try again? should be working now

**Comment by gaardiolor** [comment]
looks like it works, thanks!
