### ISSUE TITLE
Kraken - fetch_open_orders returns []

### ISSUE THREAD

**Issue by lsorin81** [ccxt/ccxt#23635]
### Operating System

mac

### Programming Languages

Python

### CCXT Version

4.3.70

### Description

- kraken always returns empty array when i try to fetch my open orders (I do have a 'custom' 'schedule' order active);
- it works fine for closed orders;
- tried with and without symbol, always empty array returned.

### Code

```
  kraken.fetch_open_orders('BTC/EUR')

```

**Comment by sc0Vu** [comment]
@lsorin81 It works for me. Have you seen the open orders in exchange UI? How did you create orders?

**Comment by lsorin81** [comment]
<img width="541" alt="Screenshot 2024-09-03 at 12 39 51" src="https://github.com/user-attachments/assets/5b58bebe-6c6f-41eb-a9bf-c195c9c188bf">
here it is. this is the open order I'm trying to fetch...

**Comment by lsorin81** [comment]
@sc0Vu here is the open order from my Android kraken app:
![Screenshot_20240904_103445_Kraken](https://github.com/user-attachments/assets/5e1e51c7-0726-4e84-9df8-fc4d8441018d)

**Comment by carlosmiei** [comment]
@lsorin81 Is this a regular order (order that uses the orderbook) or a OTC order? If it is the latter then `fetch_open_orders` won't. work

**Comment by lsorin81** [comment]
@carlosmiei it's a limit order... u set the limit price and it executes if it reaches that price

**Comment by carlosmiei** [comment]
@lsorin81 I understand, but I think these orders are managed differently by kraken. 

Can you try to place a regular trigger order instead? (I think they're basically the same thing)

**Comment by lsorin81** [comment]
@carlosmiei couldn't find 'trigger order' found a new way to exchange from btc to euro by conversion, still the same thing, still empty array when I fetch open orders :(
![Screenshot_20240904_110717_Kraken](https://github.com/user-attachments/assets/b0824086-d83e-414a-ada5-70937172bc1a)

**Comment by carlosmiei** [comment]
@lsorin81 Convert orders do not use the orderbook so they are not returned by `fetch_open_orders`

**Comment by lsorin81** [comment]
it works the other way around too... setting a limit buy order from ccxt works, and it appears in fetch_open_orders but it doesnt show in the app

**Comment by carlosmiei** [comment]
@lsorin81 To see orderbook-related actions I think you need to use kraken pro, regular kraken seems to be only a OTC platform: https://pro.kraken.com/app

**Comment by lsorin81** [comment]
@carlosmiei thank you, found them in pro
