### ISSUE TITLE
Bybit bad symbol `NEIROETHUSDT`

### ISSUE THREAD

**Issue by soranoo** [ccxt/ccxt#23660]
### Operating System

Windows 11

### Programming Languages

JavaScript

### CCXT Version

4.3.97

### Description

Failed to fetch `NEIROETHUSDT`'s data using Bybit while the symbol is valid and exist in market list
![image](https://github.com/user-attachments/assets/a64ef8f7-f147-437e-abc4-9bd7b034a143)

### Code

```ts
  
const exchange = new ccxt.bybit({
  enableRateLimit: true,
  apiKey: env.USE_TESTNET ? env.BYBIT_TESTNET_API_KEY : env.BYBIT_API_KEY,
  secret: env.USE_TESTNET ? env.BYBIT_TESTNET_API_SECRET : env.BYBIT_API_SECRET,
})
exchange.setSandboxMode(env.USE_TESTNET ? true : false)

const symbolToSearch = "NEIROETH/USDT:USDT";
exchange.fetchMarkets({
  category: "linear",
}).then((v)=>{
  const a = v.map(m => {
     return m?.symbol
  });
  if (a.includes(symbolToSearch)) {
    console.log(`Found ${symbolToSearch}`);

    console.log(`Fetch ${symbolToSearch} market...`);
    exchange.fetchMarkets({
      symbol: symbolToSearch,
      category: "linear",
    }).then(console.log).catch(console.error);
  }
}).catch(console.error);

```

**Comment by carlosmiei** [comment]
Hello @soranoo the problem is not the symbol but the request, `fetchMarkets()` with a symbol in params is not valid. Maybe you meant fetchTicker?

**Comment by soranoo** [comment]
Oh yes, I realised the symbol in `fetchMarkets` should be in Biybit format (`NEIROETHUSDT` instead of `NEIROETH/USDT:USDT`)
