### ISSUE TITLE
crypto.com access denied

### ISSUE THREAD

**Issue by landogarner7** [ccxt/ccxt#23661]
### Operating System

windows

### CCXT Version

C# 4.3.91

### Description

With different API keys I have created I always get a 401 from crypto.com
If I use the API keys in a 3rd party crypto tracker they all work fine.

Does it work fine for you ? Do there maybe exists different versions of API keys like in Kucoin that asked me to update the keys to a new version ? Thanks.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @landogarner7 can you please double-check if you have your IP whitelisted?
I just tested it and seems be to working fine

```
2024-09-07T13:44:15.793Z
Node.js: v22.2.0
CCXT v4.3.93
cryptocom.fetchBalance ()
2024-09-07T13:44:16.793Z iteration 0 passed in 400 ms

{
  BTC: { free: 0.0003999, used: 0, total: 0.0003999 },
  USDT: { free: 93.7223939875, used: 0, total: 93.7223939875 },
  CRO: { free: 0.99625, used: 0, total: 0.99625 },
  LTC: { free: 0.07109989, used: 0, total: 0.07109989 },
  XRP: { free: 0.99925, used: 0, total: 0.99925 },
  USD: { free: 50.42708421328634, used: 0, total: 50.42708421328634 },
  free: {
    BTC: 0.0003999,
    USDT: 93.7223939875,
    CRO: 0.99625,
    LTC: 0.07109989,
    XRP: 0.99925,
    USD: 50.42708421328634
  },
  used: { BTC: 0, USDT: 0, CRO: 0, LTC: 0, XRP: 0, USD: 0 },
  total: {
    BTC: 0.0003999,
    USDT: 93.7223939875,
    CRO: 0.99625,
    LTC: 0.07109989,
    XRP: 0.99925,
    USD: 50.42708421328634
  }
}
```

**Comment by landogarner7** [comment]
Carlos, I confirm that fetchBalance works well with my keys.

I got the 401 error using fetchLedger() but I did not suspect this to be the reason as the previous has.ContainsKey("fetchLedger") returned true. Using it ran into the "unautorized" exception which looks misleading so apologies for my misleading issue title.

Instead I have used now fetchMyTrades(symbol,since,null,paramEx) with paramEx {"paginate",true }, {"paginationDirection","forward" },paramEx["until"] = until;

This leads to error 

handleRestResponse:
cryptocom POST https://api.crypto.com/exchange/v1/private/get-trades 400 Bad Request
ResponseHeaders:

ResponseBody:
{
  "id" : 1725745421835,
  "method" : "private/get-trades",
  "code" : 40003,
  "message" : "Invalid limit"
}
Limit in the RequestBody is 1000 which, as I did not give a limit, should be ccxt default.

**Comment by carlosmiei** [comment]
@landogarner7 If you can access `fetchBalance` but not `fetchLedger` I would say the issue might be related to the API KEys permissions, can you check that?

**Comment by landogarner7** [comment]
The potential permissions are very limited : Read Access, Trading or Activate Withdrawal.
I have chosen Read Access.
As you see fetchMyTrades() grants my access, is its permission different to fetchLedger() ?

**Comment by carlosmiei** [comment]
@landogarner7 I'm not sure but that's the only reason i can think of
