### ISSUE TITLE
Independent Reserve place limit orders always returns invalid credentials

### ISSUE THREAD

**Issue by Burtonium** [ccxt/ccxt#2366]
- OS: Ubuntu 
- Programming Language version: javascript
- CCXT version: 1.12.10
- Exchange: IndependentReserve
- Method: PlaceLimitOrder

From my research this is because `let keysorted = this.keysort (params);` on line 240 of independentreserve.js sorts the keys alphabetically whereas the Independent Reserve Documentation states 

> the parameter sequence used to create the signature must match the method documentation.

https://www.independentreserve.com/API#private

**Comment by kroitor** [comment]
Fixed in #2410
