### ISSUE TITLE
Couldn't get timestamp in `fetch_order_book` method

### ISSUE THREAD

**Issue by taish** [ccxt/ccxt#2368]
- OS: mac os
- Programming Language version: python
- CCXT version: 1.12.17 
- Exchange: all exchange
- Method: fetch_order_book

**Comment by kroitor** [comment]
We don't set it if it is not sent by the exchange in question. You can get the last date from headers in the following way:
```Python
import ccxt
exchange = ccxt.kraken()
exchange.fetch_order_book('ETH/BTC')
exchange.last_response_headers['Date']
```
Hope it answers your question.

**Comment by taish** [comment]
thanks!
