### ISSUE TITLE
bitget .markets doesn't include margin markets

### ISSUE THREAD

**Issue by MrMechanical** [ccxt/ccxt#23690]
### Operating System

Mac OS Sonoma 14.1.1

### Programming Languages

Python

### CCXT Version

4.3.80

### Description

print(bitget_ccxt.markets)

search in text output for  'margin': True . This will result in zero results even though Bitget supports margin markets

### Code

```
  

```

**Comment by sc0Vu** [comment]
@MrMechanical Thanks for the report, I'll take a look. Before we made changes, I think you can fetch margin market through this api publicMarginGetV2MarginCurrencies.
