### ISSUE TITLE
okx watchPositions extra parameters not working

### ISSUE THREAD

**Issue by oaixnomis** [ccxt/ccxt#23700]
### Operating System

Windows 11

### Programming Languages

JavaScript

### CCXT Version

4.4.2

### Description

I am using watchPositions to watch swap positions in okx however, the extraParams seams not working. according to the doc https://www.okx.com/docs-v5/zh/#trading-account-websocket-positions-channel I also tried wrapping params inside "args" object but no luck.

### Code

```
  let pes = await cexes[c].exchange.watchPositions(undefined,undefined,undefined,{instType:"SWAP", extraParams: "{\"updateInterval\": \"0\"}" }); // okx
    handlePositionEvents(pes, c);

```

**Comment by sc0Vu** [comment]
@oaixnomis Thanks, we'll fix this asap.
