### ISSUE TITLE
Bitmart - uid should be renamed to memo

### ISSUE THREAD

**Issue by burkaykinik** [ccxt/ccxt#23715]
### Operating System

Mac OS X

### Programming Languages

Python

### CCXT Version

4.4.1

### Description

In the Bitmart credentials, UID is required, whereas it should be memo. When the uid is set to the memo, everything works properly. So, creating an exchange object looks like this at the moment. 
`
  exchange = ccxt.bitmart(
    {
        'apiKey': key,
        'secret': secret,
        'uid': memo,
    }
)
`
Renaming uid to memo would solve this issue

### Code

```
  

```

**Comment by burkaykinik** [comment]
Further information: 
In the following line, it is seen that the string for signature is created using `timestamp + '#' + uid + '#' + queryString`
https://github.com/ccxt/ccxt/blob/f81f803392d7adca7fc0e01e1f38d5361dd8d2ef/python/ccxt/bitmart.py#L4447 
whereas in the [API docs](https://developer-pro.bitmart.com/en/futures/#signature), it is stated that it is created using `X-BM-TIMESTAMP + '#' + Your_api_memo + '#' + queryString`

**Comment by carlosmiei** [comment]
Hello @burkaykinik, thanks. We will take your suggestion into consideration. Right now we use `uid` because we try to unify these values because each exchange has a different name for it.

**Comment by burkaykinik** [comment]
Hello @carlosmiei, I understand. I appreciate your consideration and I'm closing the issue.
