### ISSUE TITLE
hyperliquid create_order params are being ignored 

### ISSUE THREAD

**Issue by ggamer5555** [ccxt/ccxt#23711]
### Operating System

windows 10

### Programming Languages

Python

### CCXT Version

4.3.98

### Description

when using create_order then using params it seems that it isnt being used when creating an order can someone test this please

im trying to trade on my vault account params.vaultAddress. i can get the vaults account balance but dont know how to send a trade 

### Code

```

exchange = ccxt.hyperliquid({
    'walletAddress': vault_address2,
    'privateKey': secret,
    'timeout': 10000,  # 3 seconds
    'enableRateLimit': True,
    'options': {
        'defaultSlippage': 0.002,  # slipage 0.2%
        'defaultType': 'swap',  # Specify the market type if necessary
    },
    'rateLimit': 20,  # Adjust rate limit if necessary
})

            params = {
                'params.timeInForce': 'loc',
                'params.vaultAddress': '0x0479b5ad4d4328ad71ba8c7b8391f43f037f58e8'
            }

            order = exchange.create_order(symbol, 'market', side, amount , price, params)
```

**Comment by sc0Vu** [comment]
@ggamer5555 

Can you try this?

```
params = {
                'timeInForce': 'loc',
                'vaultAddress': '0x0479b5ad4d4328ad71ba8c7b8391f43f037f58e8'
            }
```

**Comment by ggamer5555** [comment]
I have Already tried that and it gives a Json format error 422

**Comment by ggamer5555** [comment]
yes params. was the issue also there was a spelling error causing the JSON error 422 "loc" is meant to be "ioc" 

```
            params = {
                'timeInForce': 'ioc',
                'vaultAddress': '0x0479b5ad4d4328ad71ba8c7b8391f43f037f58e8'
            }
```

**Comment by kkwilllo** [comment]
Hi @ggamer5555 or any other who familiar with ccxt

may i seek some of the advice from you

from above example, is that

- vault_address2  = HYPERLIQUID MAIN ACCOUNT WALLET_ADDRESS
- privateKey = HYPERLIQUID MAIN ACCOUNT PRIVATE KEY
- vaultAddress (in the params) = HYPERLIQUID VAULT_ADDRESS

i do similar thing like you, but no hope to fetch the position / create order to my vault account

the params i pass to the function is 
```
# exchange
exchange = ccxt.hyperliquid({
        "privateKey": HYPERLIQUID_PRIVATE_KEY,
        "walletAddress": HYPERLIQUID_WALLET_ADDRESS,
        "vaultAddress": HYPERLIQUID_VAULT_ADDRESS,
        "enableRateLimit": True,
        "options": {"defaultType": "swap"},
    })

# parmas
    parmas = {
        'vaultAddress': HYPERLIQUID_VAULT_ADDRESS,
    }

```
```
async def cancel_order_for_coin(coin, market, exchange, params={}):
    """Cancel the outstanding order for a given coin, if any."""
    if coin in orders_by_coin:
        order = orders_by_coin[coin]
        try:
            result = await exchange.cancel_order(order["id"], market, params=params)
            print(f"Canceled order for {coin} (ID: {order['id']}). Result: {result}")
        except Exception as e:
            print(f"Error canceling order for {coin}: {e}")
        orders_by_coin.pop(coin, None)

async def get_order_book(symbol, exchange, params={}):
    """Fetch the order book and return bids and asks."""
    try:
        order_book = await exchange.fetch_order_book(symbol, params=params)
        bids = order_book.get("bids", [])
        asks = order_book.get("asks", [])
        return bids, asks
    except Exception as e:
        print(f"Error fetching order book for {symbol}: {e}")
        return None, None

async def get_ilv_position(asset, exchange, params={}):
    """
    Fetch positions from Hyperliquid and return the position for the given asset.
    The function checks if the asset (coin) is contained in the market symbol and parses the 'contracts'.
    """
    try:
        positions = await exchange.fetch_positions(params=params)
        for pos in positions:
            if asset.upper() in pos.get("symbol", "").upper():
                coin = pos.get("info", {}).get("position", {}).get("coin", "").upper()
                if coin != asset.upper():
                    continue
                try:
                    contracts = float(pos.get("contracts", 0))
                except Exception:
                    contracts = 0.0
                side = pos.get("side", "").lower()
                if side == "short":
                    contracts = -abs(contracts)
                else:
                    contracts = abs(contracts)
                pos["parsed_contracts"] = contracts
                return pos
        return None
    except Exception as e:
        print(f"Error fetching Hyperliquid positions for {asset}: {e}")
        return None
```

**Comment by ggamer5555** [comment]
> Hi [@ggamer5555](https://github.com/ggamer5555) or any other who familiar with ccxt
> 
> may i seek some of the advice from you
> 
> from above example, is that
> 
> * vault_address2  = HYPERLIQUID MAIN ACCOUNT WALLET_ADDRESS
> * privateKey = HYPERLIQUID MAIN ACCOUNT PRIVATE KEY
> * vaultAddress (in the params) = HYPERLIQUID VAULT_ADDRESS
> 
> i do similar thing like you, but no hope to fetch the position / create order to my vault account
> 
> the params i pass to the function is
> 
> ```
> # exchange
> exchange = ccxt.hyperliquid({
>         "privateKey": HYPERLIQUID_PRIVATE_KEY,
>         "walletAddress": HYPERLIQUID_WALLET_ADDRESS,
>         "vaultAddress": HYPERLIQUID_VAULT_ADDRESS,
>         "enableRateLimit": True,
>         "options": {"defaultType": "swap"},
>     })
> 
> # parmas
>     parmas = {
>         'vaultAddress': HYPERLIQUID_VAULT_ADDRESS,
>     }
> ```
> 
> ```
> async def cancel_order_for_coin(coin, market, exchange, params={}):
>     """Cancel the outstanding order for a given coin, if any."""
>     if coin in orders_by_coin:
>         order = orders_by_coin[coin]
>         try:
>             result = await exchange.cancel_order(order["id"], market, params=params)
>             print(f"Canceled order for {coin} (ID: {order['id']}). Result: {result}")
>         except Exception as e:
>             print(f"Error canceling order for {coin}: {e}")
>         orders_by_coin.pop(coin, None)
> 
> async def get_order_book(symbol, exchange, params={}):
>     """Fetch the order book and return bids and asks."""
>     try:
>         order_book = await exchange.fetch_order_book(symbol, params=params)
>         bids = order_book.get("bids", [])
>         asks = order_book.get("asks", [])
>         return bids, asks
>     except Exception as e:
>         print(f"Error fetching order book for {symbol}: {e}")
>         return None, None
> 
> async def get_ilv_position(asset, exchange, params={}):
>     """
>     Fetch positions from Hyperliquid and return the position for the given asset.
>     The function checks if the asset (coin) is contained in the market symbol and parses the 'contracts'.
>     """
>     try:
>         positions = await exchange.fetch_positions(params=params)
>         for pos in positions:
>             if asset.upper() in pos.get("symbol", "").upper():
>                 coin = pos.get("info", {}).get("position", {}).get("coin", "").upper()
>                 if coin != asset.upper():
>                     continue
>                 try:
>                     contracts = float(pos.get("contracts", 0))
>                 except Exception:
>                     contracts = 0.0
>                 side = pos.get("side", "").lower()
>                 if side == "short":
>                     contracts = -abs(contracts)
>                 else:
>                     contracts = abs(contracts)
>                 pos["parsed_contracts"] = contracts
>                 return pos
>         return None
>     except Exception as e:
>         print(f"Error fetching Hyperliquid positions for {asset}: {e}")
>         return None
> ```

I used this code instead... 

'''
# Instantiate the Hyperliquid exchange
exchange = ccxt.hyperliquid({
    'walletAddress': wallet_address,
    'privateKey': secret,
    'timeout': 10000,  # 3 seconds
    'enableRateLimit': True,
    'options': {
        'defaultSlippage': 0.002,  # slipage 0.2%
        'defaultType': 'swap',  # Specify the market type if necessary
    },
    'rateLimit': 20,  # Adjust rate limit if necessary
})



def market_order(symbol, price, side, amount):
    #print(f'price={price}, amount={amount}')
    """
    Opens a market order.
    
    :param symbol: Trading pair (e.g., "BTC/USDC:USDC")
    :param side: 'buy' or 'sell'
    :param amount: The amount of the asset to buy/sell

    Market order opened: {'info': {'filled': {'totalSz': '0.0002', 'avgPx': '55121.0', 'oid': '37362107059'}}, 'id': '37362107059', 'clientOrderId': None, 'timestamp': None, 'datetime': None, 'lastTradeTimestamp': None, 'lastUpdateTimestamp': None, 'symbol': None, 'type': None, 'timeInForce': None, 'postOnly': None, 'reduceOnly': None, 'side': None, 'price': None, 'triggerPrice': None, 'amount': 0.0002, 'cost': None, 'average': 55121.0, 'filled': None, 'remaining': None, 'status': None, 'fee': None, 'trades': [], 'fees': [], 'stopPrice': None, 'takeProfitPrice': None, 'stopLossPrice': None}
    {'info': {'filled': {'totalSz': '0.0002', 'avgPx': '55121.0', 'oid': '37362107059'}}, 'id': '37362107059', 'clientOrderId': None, 'timestamp': None, 'datetime': None, 'lastTradeTimestamp': None, 'lastUpdateTimestamp': None, 'symbol': None, 'type': None, 'timeInForce': None, 'postOnly': None, 'reduceOnly': None, 'side': None, 'price': None, 'triggerPrice': None, 'amount': 0.0002, 'cost': None, 'average': 55121.0, 'filled': None, 'remaining': None, 'status': None, 'fee': None, 'trades': [], 'fees': [], 'stopPrice': None, 'takeProfitPrice': None, 'stopLossPrice': None}

    order must be over 10$
    """

    if price*amount > 10:
        try:
            params = {
                'timeInForce': 'ioc',
                'vaultAddress': '0x0479b5ad4d4328ad71ba8c7b8391f43f037f58e8'
            }

            order = exchange.create_order(symbol, 'market', side, amount , price, params)
                        
            print(f"Market order opened: {order}")

            order_info = order['info']['filled']
            # Extract relevant details
            filled_amount = order_info.get('totalSz', 'N/A')
            #average_price = order_info.get('avgPx', 'N/A')
            amount = order_info.get('amount', 'N/A')


        except Exception as e:
            print(f"An error occurred while opening the market order: {e}")
    else:
        print(f"order was less than $10 ", price*amount ) 


'''
