### ISSUE TITLE
ccxt.pro watch_ohlcv for multiple symbols from binance futures

### ISSUE THREAD

**Issue by imanf94** [ccxt/ccxt#23723]
### Operating System

Ubuntu 20

### Programming Languages

Python

### CCXT Version

4.2.21

### Description

Hi, I'm trying to get OHLCV of multiple symbols from binance futures using websocket.
I see that there is a sample here https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/watch-many-exchanges-many-tickers.py which shows that we can use multiple threads to subscribe to the OHLCV of multiple symbols using multiple watch_ohlcv calls; however, this doesn't seem to be an optimum solution especially when calling for 200 symbols.

I was wondering if there is a way around this in ccxt pro since the Binance future API has the capability of subscribing to multiple streams in their Websocket Streams https://developers.binance.com/docs/binance-spot-api-docs/web-socket-streams

**Comment by sc0Vu** [comment]
@imanf94 In binance, we aleady support watch topic for symbols (for now, we use previous specification for symbols, and it works). You can find the message logs with verbose mode.

Example:
```BASH
$ binance.watchOHLCVForSymbols (BTC/USDT,5m,ETH/USDT,5m,BTC/USDT,1h)
2024-09-16T09:22:36.591Z connecting to wss://fstream.binance.com/ws/0
2024-09-16T09:22:38.324Z onUpgrade
2024-09-16T09:22:38.327Z onOpen
2024-09-16T09:22:38.328Z sending {
  method: 'SUBSCRIBE',
  params: [ 'btcusdt@kline_5m', 'ethusdt@kline_5m', 'btcusdt@kline_1h' ],
  id: 1
}
```

**Comment by imanf94** [comment]
Thanks @sc0Vu for your quick reply! I upgraded my ccxt to version 4.4.3 and now I can use the watch_ohlcv_for_symbols
