### ISSUE TITLE
how log all ccxt calls?

### ISSUE THREAD

**Issue by denisdemaisbr** [ccxt/ccxt#23721]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Is your feature request related to a problem? Please describe

I looking for a way to log all calls of ccxt, i.e.,
fetch
buy/sell
{...}

### Describe the solution you'd like

log to file all

**Comment by pcriadoperez** [comment]
Hi @denisdemaisbr,
You have some options here.
You can set verbose to true which prints out all the calls and responses done by ccxt, and then save that print to a file.
For example doing it from the cli: `npm run cli.js binances watchTrades BTC/USDT > out.log`
Another option is every call you make using ccxt you log the response.

Hopefully this answers your questions, I'll close the issue for now, but feel free to reach out with any more questions
