### ISSUE TITLE
Ticker vs depth

### ISSUE THREAD

**Issue by forexhill** [ccxt/ccxt#2372]
Hi. Does anyone know why there is sometimes a difference between the information seen with fetchTicker vs the first array entry of fetchOrderBook? For example, the price may be slightly different.

**Comment by kroitor** [comment]
@forexhill hi! 

> For example, the price may be slightly different.

Can you, plz, be a little more specific?

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by forexhill** [comment]
As an example, on bibox, pair ETH/BTC

Ask price in tickers;  0.07566883
Ask price in order book[0]; 0.07559436
Bid price in tickers; 0.0755943
Bid price in order book[0]; 0.07559440

I guess one answer here may be "very fast trade flow", resulting in a difference between the two calls. I think that answers my question sufficiently for the moment. Thanks!
