### ISSUE TITLE
Memory Leaks in PHP

### ISSUE THREAD

**Issue by indigoram89** [ccxt/ccxt#23756]
### Operating System

MacOS

### Programming Languages

PHP

### CCXT Version

4.4.5

### Description

Hy, guys. I tried a few watch_* funcitons and all of them are constantly using up memory. I don't know how to use it for production? My task is watching 10 exchanges with 1K pairs on each. Any advice, please. Thank you!

### Code

```
  <?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

use function React\Async\await;

class WatchCommand extends Command
{
    protected $signature = 'watch:tickers';

    public function handle()
    {
        $exchange = new \ccxt\pro\binance;

        $pairs = [
            'BTC/USDT',
            'ETH/USDT',
            'XRP/USDT',
            'BNB/USDT',
            'ADA/USDT',
            'DOGE/USDT',
            'MATIC/USDT',
            'DOT/USDT',
            'LTC/USDT',
            'BCH/USDT',
        ];

        while (true) {
            await($exchange->watch_tickers($pairs));

            echo memory().PHP_EOL;
        }
    }
}
```

Result:

135.39 MB
135.45 MB
135.51 MB
135.54 MB
...
150.24 MB
150.26 MB

**Comment by carlosmiei** [comment]
Hello @indigoram89, some memory increase is expected because we cache the results (trades/orderbooks/ohlcv/etc). If you're only using `watchTicker` then it's worrying because we only save the last ticker so the memory should not be affected too much.

**Comment by indigoram89** [comment]
@carlosmiei Thank you for your reply. I'm only using watchTickers for now and memory grows as fast as many symbols I am watching.

**Comment by carlosmiei** [comment]
@sc0Vu @ttodua can you take a look?

**Comment by indigoram89** [comment]
I ran the same code for 70 symbols about 5 minutes ago and I see this result right now:

...
998.56 MB
998.92 MB
999.28 MB
999.54 MB
999.9 MB
1000.26 MB
1000.64 MB
1000.48 MB
1000.1 MB
1000.4 MB
1000.75 MB
1001.09 MB
1001.44 MB
1001.79 MB
...

**Comment by ttodua** [comment]
@carlosmiei as sc0vu self-assigned i'll leave this to him for now, if he pings me, i'll take over

**Comment by sc0Vu** [comment]
Hi @indigoram89 I've watched 70 symbols on my laptop over 10 minutes. The memory didn't grow on my side. I doubt whether it's the usage with laravel command or laravel application.

**Comment by carlosmiei** [comment]
@sc0Vu actually I was running it also on my machine and the memory indeed increased to the point that it crashed the process
```
125531848
125541600
125551352
125561104
125570856
125580608
125590360
125600112
125609864
125619616
125629368
125639120
125648872
125658624
125668376
125678128
125687880
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /Users/cjg/Git/ccxt10/ccxt/vendor/react/promise/src/Promise.php on line 168

```

**Comment by indigoram89** [comment]
@carlosmiei  This is exactly what I encountered on the server and am currently testing on my computer with the same result. 

If I comment the line await($exchange->watch_tickers($pairs)); so it is no memory leak so I don't think the problem in Laravel.

**Comment by sc0Vu** [comment]
@carlosmiei @indigoram89 Here is my log [out.log](https://github.com/user-attachments/files/17083385/out.log), I didn't see it's increasing consistently.

But you can see the memory usage grow when tickers size increase `got tickers 152 before: 113246208 after: 115343360 diff: 2097152`.  I wonder whether it's related to the tickers size, not the issue in ccxt.

```BASH
$ ph binance watchTickers '[BTC/USDT:USDT","ETH/USDT:USDT","BCH/USDT:USDT","XRP/USDT:USDT","EOS/USDT:USDT","LTC/USDT:USDT","TRX/USDT:USDT","ETC/USDT:USDT","LINK/USDT:USDT","XLM/USDT:USDT","ADA/USDT:USDT","XMR/USDT:USDT","DASH/USDT:USDT","ZEC/USDT:USDT","XTZ/USDT:USDT","BNB/USDT:USDT","ATOM/USDT:USDT","ONT/USDT:USDT","IOTA/USDT:USDT","BAT/USDT:USDT","VET/USDT:USDT","NEO/USDT:USDT","QTUM/USDT:USDT","IOST/USDT:USDT","THETA/USDT:USDT","ALGO/USDT:USDT","ZIL/USDT:USDT","KNC/USDT:USDT","ZRX/USDT:USDT","COMP/USDT:USDT","OMG/USDT:USDT","DOGE/USDT:USDT","SXP/USDT:USDT","KAVA/USDT:USDT","BAND/USDT:USDT","RLC/USDT:USDT","MKR/USDT:USDT","SNX/USDT:USDT","DOT/USDT:USDT","DEFI/USDT:USDT","YFI/USDT:USDT","BAL/USDT:USDT","CRV/USDT:USDT","TRB/USDT:USDT","RUNE/USDT:USDT","SUSHI/USDT:USDT","EGLD/USDT:USDT","SOL/USDT:USDT","ICX/USDT:USDT","STORJ/USDT:USDT","BLZ/USDT:USDT","UNI/USDT:USDT","AVAX/USDT:USDT","FTM/USDT:USDT","ENJ/USDT:USDT","FLM/USDT:USDT","REN/USDT:USDT","KSM/USDT:USDT","NEAR/USDT:USDT","AAVE/USDT:USDT","FIL/USDT:USDT","RSR/USDT:USDT","LRC/USDT:USDT","BEL/USDT:USDT","AXS/USDT:USDT","ALPHA/USDT:USDT","ZEN/USDT:USDT","SKL/USDT:USDT","GRT/USDT:USDT","1INCH/USDT:USDT]' > out.log
```

```PHP
$beforeMemoryUsage = memory_get_usage(true);

                    $result = yield call_user_func_array(array($exchange, $member), $args);

                    $afterMemoryUsage = memory_get_usage(true);

                    echo 'got tickers ' . count($result) . ' before: ' . $beforeMemoryUsage . ' after: '. $afterMemoryUsage . ' diff: ' . ($afterMemoryUsage - $beforeMemoryUsage) .PHP_EOL;
```

**Comment by indigoram89** [comment]
I created a new laravel project and it is no memory leaks. Sorry guys and thank you for your time. We may close this issue.

**Comment by carlosmiei** [comment]
@indigoram89 thanks for the update.
