### ISSUE TITLE
I need to know how to resolve KeyError: 'broad'.

### ISSUE THREAD

**Issue by miyazato138** [ccxt/ccxt#23776]
### Operating System

Windows 11

### Programming Languages

Python

### CCXT Version

4.4.5

### Description

Someone help.
I get an error when I run the following Python code.
The error message is as follows
'''
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.bitflyer.com/v1/me/sendchildorder

  File "C:\Users\miyat\anaconda3\Lib\site-packages\ccxt\bitflyer.py", line 1001, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], errorMessage, feedback)

KeyError: 'broad'
'''

How can I resolve the error?

### Code

```
import ccxt
from pprint import pprint
bitflyer = ccxt.bitflyer()
bitflyer.apiKey = '*****'
bitflyer.secret = '**********'
order = bitflyer.create_order(
	symbol = 'BTC/JPY',
	type='limit',
	side='buy',
	price='800000',
	amount='0.01',
	params = { "product_code" : "FX_BTC_JPY" })
pprint( order )
```

**Comment by carlosmiei** [comment]
Hello @miyazato138, thanks for reporting it, we will take a look.

**Comment by carlosmiei** [comment]
@miyazato138 Can you update your ccxt version and try again pls?
