### ISSUE TITLE
MEXC returns BSC instead of BEP20 as a network indicator.

### ISSUE THREAD

**Issue by ywallis** [ccxt/ccxt#23777]
### Operating System

Linux

### Programming Languages

Python

### CCXT Version

4.4.5

### Description

When looking at networks available for a currency, results from MEXC using the unified API show as BSC instead of BEP20.

### Code

```
exchange = ccxt.mexc()
exchange.load_markets()
pprint(mexc_client.currencies['BTC']['networks'])

```

**Comment by carlosmiei** [comment]
Hello @ywallis, thanks for reporting it; we will fix it asap.

**Comment by carlosmiei** [comment]
@ywallis If you update your ccxt version, `BEP20` should be returned now. Thanks once again.
