### ISSUE TITLE
New Exchange: openledger.io

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#2377]
uri: https://openledger.io/welcome
doc: ---

**Comment by An-Net** [comment]
shutdown

- https://dex.openledger.io/news/ol-dex-is-closing-all-activities/

![Снимок экрана 2020-07-20 в 19 11 17](https://user-images.githubusercontent.com/51840849/87960355-de45cc00-cabc-11ea-8c0c-f3e0fc48e461.png)
