### ISSUE TITLE
Why does market order on MEXC requires price to be specified?

### ISSUE THREAD

**Issue by fam04s** [ccxt/ccxt#23784]
### Operating System

windows, linux

### Programming Languages

Python

### CCXT Version

latest

### Description

When I try to  `mexc.create_order("PYTH/USDT", "market", "buy", 4)` I get the 

> createOrder() requires the price argument for market buy orders to calculate the total cost to spend(amount * price), alternatively set the createMarketBuyOrderRequiresPrice option or param to False and pass the cost to spend in the amount argument')

error.

But, [MEXC API](https://mexcdevelop.github.io/apidocs/spot_v3_en/#new-order) does support  regular market buy order without specifying price.  This snippet works perfectly with [mexc_sdk](https://github.com/mexcdevelop/mexc-api-sdk/blob/main/test/python/newOrderTest.py)
```py
client.new_order("PYTHUSDT", "SELL", "MARKET", options={"quantity": 4})
```
why does CCXT requires specifying price in the market buy order?

### Code

```py
mexc.create_order("PYTH/USDT", "market", "buy", 4)
```

**Comment by sc0Vu** [comment]
@fam04s Thanks for the report, I'll take a look.

**Comment by carlosmiei** [comment]
@fam04s I will double-check it, but in your example above using the SDK you have ` "market sell"` order and not a market buy that's why I didn't consider it a problem/

**Comment by carlosmiei** [comment]
@fam04s can you update your ccxt version and try again? It should be working now
