### ISSUE TITLE
Pagination Cursor breaks when receiving multiple entries with the same timestamp, leading to gaps in data

### ISSUE THREAD

**Issue by pascalc23** [ccxt/ccxt#23793]
### Programming Languages

JavaScript

### CCXT Version

4.4.5

### Description

In line 6126 of `Exchange.js` method `fetchPaginatedCallCursor()` tries to retrieve the `cursorValue` from the last element of the result set. 

```
result = this.arrayConcat(result, response);
const last = this.safeValue(response, responseLength - 1);
cursorValue = this.safeValue(last['info'], cursorReceived);
if (cursorValue === undefined) {
    break;
}
 ```

This value is set for example in `bybit.js` method `addPaginationCursorToResult()` in the first entry of the result set with the expectation, that `parseLedger()`, `parseTrades()` and `parseTransactions()` sort the result set by timestamp, therefore moving the cursor to the last position in the result set.

When the results have identical timestamps however, which often happens for accounts with a lot of transactions, this sorting method fails to produce the desired result. 

Attached screenshot displays a scenario when the cursor ended up in array position 44 of 50 - breaking the pagination loop.

<img width="1476" alt="Cursor-in-position-44-noid" src="https://github.com/user-attachments/assets/fa802daf-5e70-4d43-9b00-17f07b983aa0">

Note all entries in the last positions having the same timestamp.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @pascalc23 thanks for reporting it, we will check it asap.

**Comment by carlosmiei** [comment]
@pascalc23 CCXT always tries to return data using the same order (ascending) and has been doing that for a long time, so CCXT users know that regardless of the exchange, they get the data in that order consistently. 

Automatic pagination was added afterwards and to minimize the required changes inside every implementation it uses the final unified result from the unified methods (fetchTrades/Ledger/Orders/etc) so the data inside `fetchPaginatedCallCursor` is already parsed and sorted and it's very hard to change that.

**Comment by pascalc23** [comment]
Okay got it. 
I find that most exchanges these days return data in descending order - which makes sense IMO.

Regarding the pagination, you'll probably have to change the mechanism in which you store the cursor then. 
Or look for it by iterating through the results.
Cause sorting by timestamp can mess everything up.

We've seen several cases where users had 100-200 transactions with the same ms timestamp. 
Sorting by timestamp is tricky with most exchanges.

**Comment by carlosmiei** [comment]
@pascalc23 Yes I opened a PR with the fix, will be released shortly

**Comment by carlosmiei** [comment]
@pascalc23 can you please update your ccxt version and try again? I believe it should be working properly now

**Comment by pascalc23** [comment]
Can confirm fixed for my test cases 👍 

Sorry for the delay in testing - it always takes a while until I can go back and reopen past tickets to test new CCXT versions. 
I generally have to patch them and move on to other Exchange tickets 🙂

**Comment by carlosmiei** [comment]
@pascalc23 thanks for confirming it!
