### ISSUE TITLE
ByBit: parseToNumeric in parseLedgerEntry throws Error for 'FEE_REFUND' ledger entries

### ISSUE THREAD

**Issue by pascalc23** [ccxt/ccxt#23798]
### Programming Languages

JavaScript

### CCXT Version

4.4.5

### Description

Current implementation of `parseLedgerEntry()` calls function `parseToNumeric()` for populating the fee.cost field.
```
'fee': {
    'currency': code,
    'cost': this.parseToNumeric(this.safeString(item, 'fee')),
},
```
This function breaks when ìtem.fee` is empty, which for ledger entries of type 'FEE_REFUND' is the case:

```
{
  "symbol": "",
  "side": "None",
  "funding": "",
  "orderLinkId": "",
  "orderId": "",
  "fee": "",
  "change": "0.0180063",
  "cashFlow": "0.0180063",
  "transactionTime": "1688716432605",
  "type": "FEE_REFUND",
  "feeRate": "",
  "bonusChange": "0",
  "size": "",
  "qty": "",
  "cashBalance": "5.66212577",
  "currency": "USDT",
  "id": "xxxx-xxxxxx-xxxxxxx",
  "category": "",
  "tradePrice": "",
  "tradeId": "",
  "nextPageCursor": "34%3A0%2C12%3A0"
}
```

### Code

```
  

```

**Comment by Dan-krm** [comment]
Thanks for reporting @pascalc23 I've opened a pull request that should resolve this issue!

**Comment by pascalc23** [comment]
Great, looking forward to it - thanks

**Comment by carlosmiei** [comment]
@pascalc23 same thing here, please update and let us know if anything

**Comment by pascalc23** [comment]
Thanks for the quick fix - I'll test it as soon as I can 👍

**Comment by pascalc23** [comment]
Tested several imports and did not encouter issue again 👍
