### ISSUE TITLE
bybit createConvertTrade

### ISSUE THREAD

**Issue by cozy-hn** [ccxt/ccxt#23807]
### Description

Bybit has a Convert API in their V5 version, but it's currently missing in the CCXT Bybit implementation (e.g., createConvertTrade).

I attempted to add this manually but ran into issues calculating the API rate limit weight(I don't know how to calculate it).

Could you please:

Add the Convert API support to Bybit in CCXT.

**Comment by carlosmiei** [comment]
Hello @cozy-hn, thanks for reporting it, we will try to add it as soon as possible.

**Comment by cozy-hn** [comment]
@carlosmiei @Dan-krm 
Thanks a lot :)

**Comment by carlosmiei** [comment]
@cozy-hn can you please update your ccxt version? convert methods should be available now
