### ISSUE TITLE
bybit fetchBalance()

### ISSUE THREAD

**Issue by sv3nnie** [ccxt/ccxt#23816]
### Programming Languages

JavaScript

### CCXT Version

4.4.6

### Description

Hi everyone, I am running into an issue with bybit exchange.fetchBalance().  I am using ccxt v4.4.6. I get the following error: 
PermissionDenied: bybit private api uses /user/v3/private/query-api to check if you have a unified account. The API key of user id must own one of permissions: "Account Transfer", "Subaccount Transfer", "Withdrawal" {"retCode":10005,"retMsg":"Permission denied, please check your API key permissions.","result":{},"retExtInfo":{},"time":1727204252809}

Even after providing the Account Transfer and Subaccount Transfer permissions to the corresponding API key through the Bybit interface, I still get the error. I have another Bybit account that doesn't have these permissions assigned to the API key on that account (only has Spot Trading and order history permissions), and everything works fine on that account. I am not sure what the difference is between the two accounts. Both are using Unified Trading Account.

I saw others reporting similar issues on Github a while ago (in 2023), but none of the solutions works for me. For example, I tried specifying the type in fetchBalance (exchange.fetchBalance({ 'type': 'spot'}) and also tried exchange.privateGetV5AccountWalletBalance({ 'accountType': 'unified' });, but I keep running into this error. 

What would be a possible fix here?

### Code

```            
// Validate the API keys using ccxt
const exchange = new ccxt[bybit]({
    apiKey: apiKey,
    secret: apiSecret,
});

try {
    // Fetch all coins on the account
    const balance = await exchange.fetchBalance({ 'type': 'spot' });
} catch (error) {
    console.log(error);
}
```

**Comment by carlosmiei** [comment]
Hello @sv3nnie,

If even `exchange.privateGetV5AccountWalletBalance({ 'accountType': 'unified' })`  fails,. It means that the problem is not ccxt-related because, in that case, you're calling the endpoint directly. 

Have you tried to create a new set of API Keys to see if that makes a difference?

**Comment by sv3nnie** [comment]
Hi @carlosmiei, 

Yes, I've tried to create new API keys multiple times. Also tinkered with the permissions to see if this might change anything, but unfortunately it didn't.

**Comment by sv3nnie** [comment]
@carlosmiei 
``exchange.isUnifiedEnabled()`` returns ``[ false, false ]``

**Comment by sv3nnie** [comment]
It seems like this was an issue on my side. ``await exchange.fetchBalance({ 'type': 'spot' });``works as expected and fetches the balance. Would I have to manually check if Unified is enabled, and if not, set the type to spot? Because ``fetchBalance()`` works fine without any parameters if Unified is enabled, but apparently it requires ``type: spot`` if Unified is not enabled.
