### ISSUE TITLE
C#: WatchTrades returns really big numbers for Trade amount on some exchanges

### ISSUE THREAD

**Issue by alert101** [ccxt/ccxt#23818]
### Operating System

Windows 10

### CCXT Version

4.4.7

### Description

I'm using the latest (4.4.7) C# version of CCXT and I've noticed that WatchTrades returns weird amounts on trades. As an example reading the trades on futures for the symbol BTC/USDT:USDT, some exchanges like binanceusdm and bitget return expected values like a fraction of one bitcoin (0.002 - 1.0) etc, but eg. mexc and whitebit return amounts in the range of hundreds and thousands or even millions. Here's an excerpt from my log:
```
Timestamp;Symbol;Exchange;Price;Amount;Side
2024-09-25T13:34:01.548000+00:00;BTC/USDT:USDT;binanceusdm;63577;0.009;buy
2024-09-25T13:34:02.311000+00:00;BTC/USDT:USDT;binanceusdm;63583.3;0.011;buy
2024-09-25T13:34:01.583000+00:00;BTC/USDT:USDT;bitget;63576.9;0.008;sell
2024-09-25T13:34:02.290000+00:00;BTC/USDT:USDT;bitget;63577;0.083;buy
2024-09-25T13:34:03.324000+00:00;BTC/USDT:USDT;whitebit;63588.1;1575.0540000011;buy
2024-09-25T13:34:03.523000+00:00;BTC/USDT:USDT;whitebit;63588.5;429.1739999997;buy
2024-09-25T13:34:03.823000+00:00;BTC/USDT:USDT;whitebit;63590.1;2932.2699999985;buy
2024-09-25T13:34:04.025000+00:00;BTC/USDT:USDT;whitebit;63596.9;23188.4790000736;buy
2024-09-25T13:34:04.823000+00:00;BTC/USDT:USDT;whitebit;63597.5;0.438;buy
2024-09-25T13:34:04.542000+00:00;BTC/USDT:USDT;mexc;63597.6;129747354;buy
2024-09-25T13:34:04.731000+00:00;BTC/USDT:USDT;mexc;63597.6;15787920;buy
2024-09-25T13:34:04.877000+00:00;BTC/USDT:USDT;mexc;63597.6;131210000;buy
```
Could this be a bug in how different exchanges return values and ccxt isn't parsing it correctly? Perhaps the local culture makes it misbehave?

**Comment by carlosmiei** [comment]
Hello @alert101, when trading perps you don't get the amount in the base currency (BTC) but in number of contracts.
Maybe this is related to the contract size?


```
CCXT v4.4.7
whitebit.market (BTC/USDT:USDT)
2024-09-25T16:05:33.635Z iteration 0 passed in 0 ms

{
  id: 'BTC_PERP',
  lowercaseId: undefined,
  symbol: 'BTC/USDT:USDT',
  base: 'BTC',
  quote: 'USDT',
  settle: 'USDT',
  baseId: 'BTC',
  quoteId: 'USDT',
  settleId: 'USDT',
  type: 'swap',
  spot: false,
  margin: false,
  swap: true,
  future: false,
  option: false,
  index: undefined,
  active: true,
  contract: true,
  linear: true,
  inverse: false,
  subType: 'linear',
  taker: 0.00035,
  maker: 0.0001,
  contractSize: 0.001,
````
For example at whitebit, the contract size for `BTC/USDT:uSDT` is 0.001, meaning that, in order to buy contracts worth 1 BTC, you need to use amount = 1 / 0.001 = 1000 contracts

**Comment by alert101** [comment]
Ahh. Thank you for the fast reply. I'm pretty much done for today but I will check the contract size tomorrow. Just to make sure, I'm not trading but just reading the actual trades from the exchanges (WatchTrades method). In that case it seems as if some exchanges already take contractSize into account when parsing the amount from the actual response. However with mexc even that seems weird, their contractSize is 0.0001 and you can see in my log that they have values like 131210000. With that contractSize that would be 13121 BTC in a single trade. And there are many such trades, constantly. That would make mexc the largest exchange ever.

I'm checking my own code if it's something I'm messing up but my code is really simple.
```
    List<Trade> trades = await exchange.WatchTrades(pair);

    PastTrade pt;
    foreach (var trade in trades)
    {
        pt = new PastTrade()
        {
            Exchange = exchange.id,
            Symbol = trade.symbol,
            Timestamp = DateTimeOffset.FromUnixTimeMilliseconds(trade.timestamp.Value).UtcDateTime,
            Price = trade.price ?? 0d,
            Amount = trade.amount ?? 0d,
            Side = trade.side ?? string.Empty
        };

        log(pt);
    }
```

**Comment by carlosmiei** [comment]
@alert101 

>  In that case it seems as if some exchanges already take contractSize into account when parsing the amount from the actual response

 some exchanges, like binance, have contractSize = 1, so the number of contracts will be equal to the base currency.


>  However with mexc even that seems weird, their contractSize is 0.0001 and you can see in my log that they have values like 131210000

yeah this is still weird. What's the value inside `info` ?

**Comment by alert101** [comment]
@carlosmiei I'll check tonight after work and get back to you.

**Comment by alert101** [comment]
@carlosmiei Info contains an identical value as Amount. I ran a few tests without any of my own code and I got different resukts, So as usual it's entirely possible that my own code is somehow f'ed. I need to run some more tests.

One question though, based on your previous replies I conclude that when it comes to futures the amount in the Trade struct is the number of contracts and contractSize needs to be taken into account to get the actual size of the trade in base currency?

**Comment by carlosmiei** [comment]
@alert101 

> Info contains an identical value as Amount

the values inside info are the raw values return by the API, so if they're the same it means it is the API reporting that volume.

> is the number of contracts and contractSize needs to be taken into account to get the actual size of the trade in base currency?

this is correct yes

**Comment by alert101** [comment]
Let's close this while I figure out my end. I'll open a new issue if necessary. Thank you for your help!
