### ISSUE TITLE
New Exchange: loopring

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#2381]
uri: https://loopring.io/#/markets
doc: soon

**Comment by krisj** [comment]
This is very much needed and important - just look at their growth! It makes too much sense - gas free swapping and trading, c'mon!

**Comment by jcorriveau23** [comment]
Negative maker fees :O! i'd like to use loopring for my bot! Is this task in development ?

**Comment by frosty00** [comment]
@jcorriveau23 it is currently not in development because we would need to implement their signatures and it is a dex so hard to implement in general (takes a lot of time). if they want to pay us for the integration we would do it.

**Comment by frosty00** [comment]
DEX / not a priority
