### ISSUE TITLE
Binance watch_balance bug

### ISSUE THREAD

**Issue by seeyoul8r** [ccxt/ccxt#23829]
### Operating System

windows 11

### Programming Languages

Python

### CCXT Version

last

### Description

 I'm trying to start watch_balance stream on binance and get KeyError 'swap' on this step
![image](https://github.com/user-attachments/assets/25cd4ce6-a528-4a07-b3fc-0b899ea20bac)

So there (in dictionary 'urls') should be item with 'swap' key 
![image](https://github.com/user-attachments/assets/0f406812-8d58-45a0-ba25-d07528400b98)

### Code

```
  

```

**Comment by sc0Vu** [comment]
@seeyoul8r Thanks for reporing, we'll fix this asap.

**Comment by carlosmiei** [comment]
@seeyoul8r Can you update your ccxt version and try again please? I believe it should be working now

**Comment by seeyoul8r** [comment]
> @seeyoul8r Can you update your ccxt version and try again please? I believe it should be working now

Thanks, everything is great now
