### ISSUE TITLE
okx cancel_order_ws doesn't throw OrderNotFound but cancel_order does

### ISSUE THREAD

**Issue by rpcavalcante** [ccxt/ccxt#23834]
### Operating System

Ubuntu 20.04

### Programming Languages

Python

### CCXT Version

4.4.8

### Description

When I try to cancel an non-existent order at OKX, `okx.cancel_order` calls (via REST) throw the more specific `OrderNotFound` exception, but `okx.cancel_order_ws` calls (via WebSocket) throw the broader `ExchangeError`. Since the messages returned by OKX in both cases have roughly the same structure w.r.t. how they report the error, with just minor / irrelevant differences, the inconsistency is on how CCXT handle the responses coming from each distinct endpoint. Looking into CCXT Pro code I've noticed that `okx.handle_error_message`, which is used to process WebSocket error responses, indeed is significantly different from the `okx.handle_errors` implementation, which processes REST error responses; and the latter, in turn, better aligns with the relevant [section of OKX API docs](https://www.okx.com/docs-v5/en/#overview-general-info):

> **The rules for the returning data are as follows:**
> 
> - `code` and `msg` represent the request result or error reason when the return data has `code`, and has not `sCode`;
> - It is `sCode` and `sMsg` that represent the request result or error reason when the return data has `sCode` rather than `code` and `msg`.

 CCXT team: how do you feel about making `handle_error_message` treat error responses analogously to `handle_errors`?

### Code

```
import asyncio
from ccxt import ExchangeError
from ccxt.pro import okx

async def main():
    exchange = okx({
        'apiKey': 'API-KEY',
        'secret': 'API-SECRET',
        'password': 'PASSPHRASE',
    })
    await exchange.load_markets()
    exchange.verbose = True
    try:
        await exchange.cancel_order(id="999999999", symbol='BTC/USDT')
    except ExchangeError as ee:
        print(f'REST: {type(ee).__name__}')
    try:
        await exchange.cancel_order_ws(id="999999999", symbol='BTC/USDT')
    except ExchangeError as ee:
        print(f'WebSocket: {type(ee).__name__}')
    await exchange.close()

asyncio.run(main())
```

### Output

```
fetch Request: okx POST https://www.okx.com/api/v5/trade/cancel-order RequestHeaders: {'OK-ACCESS-KEY': 'API-KEY', 'OK-ACCESS-PASSPHRASE': 'PASSPHRASE', 'OK-ACCESS-TIMESTAMP': '2024-09-26T16:47:58.048Z', 'Content-Type': 'application/json', 'OK-ACCESS-SIGN': 'SIGNATURE', 'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate'} RequestBody: {"instId":"BTC-USDT","ordId":"999999999"}

fetch Response: okx POST https://www.okx.com/api/v5/trade/cancel-order 200 ResponseHeaders: {'Date': 'Thu, 26 Sep 2024 16:47:58 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'b-locale': 'en_US', 'x-content-type-options': 'nosniff', 'x-xss-protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'x-frame-options': 'SAMEORIGIN', 'x-brokerid': '0', 'strict-transport-security': 'max-age=63072000; includeSubdomains; preload', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '8c94bd23bf51a4d1-GRU', 'Content-Encoding': 'gzip'} ResponseBody: {"code":"1","data":[{"clOrdId":"","ordId":"999999999","sCode":"51400","sMsg":"Order cancellation failed as the order has been filled, canceled or does not exist","ts":"1727369278185"}],"inTime":"1727369278215187","msg":"All operations failed","outTime":"1727369278216590"}
REST: OrderNotFound
2024-09-26T16:47:58.389Z connecting to wss://ws.okx.com:8443/ws/v5/private with timeout 10000 ms
2024-09-26T16:47:59.962Z connected
2024-09-26T16:47:59.962Z ping loop
2024-09-26T16:47:59.962Z sending ping
2024-09-26T16:47:59.962Z sending {'op': 'login', 'args': [{'apiKey': 'API-KEY', 'passphrase': 'PASSPHRASE', 'timestamp': '1727369278', 'sign': 'SIGNATURE'}]}
2024-09-26T16:48:00.386Z message pong
2024-09-26T16:48:00.386Z message {"event":"login","msg":"","code":"0","connId":"3cfb06d3"}
2024-09-26T16:48:00.489Z sending {'id': '17273692803868026', 'op': 'cancel-order', 'args': [{'instId': 'BTC-USDT', 'ordId': '999999999'}]}
2024-09-26T16:48:00.921Z message {"id":"17273692803868026","op":"cancel-order","code":"1","msg":"","data":[{"ts":"1727369280678","ordId":"999999999","clOrdId":"","sCode":"51400","sMsg":"Order cancelation failed as the order has been filled, canceled or does not exist."}],"inTime":"1727369280686597","outTime":"1727369280687483"}
WebSocket: ExchangeError
2024-09-26T16:48:00.921Z closing 1000
2024-09-26T16:48:00.922Z on_close 1000
```

**Comment by case-hub** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@rpcavalcante

**Comment by sc0Vu** [comment]
@rpcavalcante Thanks for the report, we'll fix this asap.

**Comment by carlosmiei** [comment]
@rpcavalcante Can you please check if it is working now?

**Comment by rpcavalcante** [comment]
@sc0Vu, @carlosmiei: as of CCXT 4.4.9, I see okx cancel_order_ws throwing OrderNotFound when appropriate. Thanks for the quick turnaround once again.

**Comment by carlosmiei** [comment]
@rpcavalcante no problem let us know if anything!
