### ISSUE TITLE
kraken trailingLimitAmount should allow a % 

### ISSUE THREAD

**Issue by dakkusingh** [ccxt/ccxt#23833]
### Operating System

MacOS

### Programming Languages

Python

### CCXT Version

CCXT Version: 4.2.95

### Description

```
            if isLimitOrder or (trailingLimitAmount is not None):
                offset = self.safe_string(params, 'offset', '-')
                trailingLimitAmountString = offset + self.number_to_string(trailingLimitAmount)
                request['price'] = trailingAmountString
                request['price2'] = trailingLimitAmountString
                request['ordertype'] = 'trailing-stop-limit'
```

code above does not allow trailingLimitAmount to be a percent
```
        params['trailingAmount'] = '10%'
        params['trailingLimitAmount'] = '0.1%'
```

according to Kraken API and website UI, the trailingLimitAmount can be a percent.
wrapping the value through `number_to_string` is not necessary.

### Code

```
  

```

**Comment by Dan-krm** [comment]
Hi @dakkusingh thanks for reporting this. I've opened a pull request to add support for using `trailingPercent` and `trailingLimitPercent` it looks like using `%` may not be fully supported on the exchange side even though it's in the documentation but we are looking into it.

**Comment by carlosmiei** [comment]
@dakkusingh  Can you please upgrade your ccxt version and try again? It should be working now

**Comment by dakkusingh** [comment]
sadly I just get
```
InvalidOperation([<class 'decimal.ConversionSyntax'>])
```

setting params like
```
        params['trailingPercent'] = 10
        params['trailingLimitPercent'] = 0.01
```

**Comment by dakkusingh** [comment]
issue seems to be related to the incorrect logic relating to:

```
        elif isLimitOrder and not isTrailingAmountOrder:
            request['price'] = self.price_to_precision(symbol, price)
```

setup:
define the order type as "trailing-stop-limit"
and set the params as 
```
params['trailingPercent'] = 10
params['trailingLimitPercent'] = 0.01
```

now the code incorrectly identifies the order type as limit due to
```
isLimitOrder = type.endswith('limit')
```

and now because its flagged as a limit order, its trying to price_to_precision price_to_precision price for NULL. trailing stop limit orders do not have a price.
```
elif isLimitOrder and not isTrailingAmountOrder:
            request['price'] = self.price_to_precision(symbol, price)
```

therefore the implemented logic is partially correct and does not work and results in error
```
InvalidOperation([<class 'decimal.ConversionSyntax'>])
```

**Comment by dakkusingh** [comment]
additional issue is that offsets not being applied correctly. needs to do something like:

```
            if isLimitOrder or (trailingLimitAmount is not None) or (trailingLimitPercent is not None):
                request['ordertype'] = 'trailing-stop-limit'
                if trailingLimitPercent is not None:
                    trailingLimitPercentString = trailingLimitPercent if (trailingLimitPercent.endswith('%')) else (self.number_to_string(trailingLimitPercent) + '%')
                    request['price'] = '+' + trailingPercentString
                    request['price2'] = offset + trailingLimitPercentString
```

**Comment by Dan-krm** [comment]
@dakkusingh I opened a pull request to fix kraken trailingLimitPercent orders here: https://github.com/ccxt/ccxt/pull/23884

Once it's merged you can upgrade your version and everything should be working properly

Let us know if you have any other issues

**Comment by carlosmiei** [comment]
@dakkusingh Can you please upgrade your ccxt version and try again?

**Comment by dakkusingh** [comment]
trying the 4.4.12 version with the following:

```
params['trailingPercent'] = 10
params['trailingLimitPercent'] = 0.01
```

and it seems to be working with a response from Kraken..

```
{'amount': 0.2,
 'average': None,
 'clientOrderId': None,
 'cost': None,
 'datetime': None,
 'fee': None,
 'fees': [],
 'filled': None,
 'id': 'yyyyyyyyy',
 'info': {'descr': {'order': 'sell 0.20000000 SOLGBP @ trailing stop -10.0000% '
                             '-> limit -0.0100%'},
          'txid': ['xxxxxxxx']},
 'lastTradeTimestamp': None,
 'lastUpdateTimestamp': None,
 'postOnly': False,
 'price': None,
 'reduceOnly': None,
 'remaining': None,
 'side': 'sell',
 'status': None,
 'stopLossPrice': None,
 'stopPrice': None,
 'symbol': 'SOL/GBP',
 'takeProfitPrice': None,
 'timeInForce': None,
 'timestamp': None,
 'trades': [],
 'triggerPrice': None,
 'type': 'trailing'}
```

will test a bit further and ping back if there is an issue. Thanks again for getting this fixed.

**Comment by carlosmiei** [comment]
@dakkusingh thanks for confirming it, and let us know if anything
