### ISSUE TITLE
Hyperliquid fetch_my_trades() fee currency is incorrect

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#23852]
### Operating System

n/a

### Programming Languages

Python

### CCXT Version

4.4.9

### Description

Hello,

In the object returned by fetch_my_trades, the fee token is incorrect. It's [hardcoded ](https://github.com/ccxt/ccxt/blob/2ac8eb5ac4a442243904a8669719a72b69d2ef42/python/ccxt/hyperliquid.py#L1987) to 'USDC', which is not correct - it should be set to the `feeToken` value returned by the hyperliquid API. thanks!

### Code

```
    e = ccxt.hyperliquid()
    e.walletAddress = config['hyperliquid']['walletAddress']
    e.privateKey = config['hyperliquid']['privateKey']
    trades = await e.fetch_my_trades('POINTS/USDC')
    print(f"Fee token Hyperliquid api: {trades[-2]['info']['feeToken']}\nFee token ccxt: {trades[-2]['fee']['currency']}")
    await e.close()

Fee token Hyperliquid api: POINTS
Fee token ccxt: USDC
```

**Comment by carlosmiei** [comment]
Hello @gaardiolor thanks for reporting it will be fixed shortly.

**Comment by carlosmiei** [comment]
@gaardiolor Can you please upgrade your ccxt version and try again? It should be working now

**Comment by gaardiolor** [comment]
yeah looks like it's working, thanks!
