### ISSUE TITLE
[binanaceusdm] Add support for watch mark price

### ISSUE THREAD

**Issue by woo-youngpaca** [ccxt/ccxt#23883]
### Preliminary Checks

- [X] I have already searched for [existing issues](https://github.com/ccxt/ccxt/issues) and confirmed that this issue is not a duplicate

### Describe the solution you'd like

https://developers.binance.com/docs/derivatives/usds-margined-futures/websocket-market-streams/Mark-Price-Stream

binanaceusdm has Mark Price Stream, but ccxt doesn't have this feature.
Please add support for watch mark price

**Comment by carlosmiei** [comment]
Hello @woo-youngpaca,

Thanks for your suggestion we will try to add it shortly.

**Comment by carlosmiei** [comment]
@woo-youngpaca If you update your ccxt version now you should have access to `watchMarkPrices/watchMarkPrice/fetchMarkPrices`

Please let us know if anything!

**Comment by woo-youngpaca** [comment]
@carlosmiei 
[watchMarkPrices / watchMarkPrice / fetchMarkPrices]
It works perfectly. I compared the values ​​and they are correct. Thank you so much for adding this feature!

**Comment by carlosmiei** [comment]
@woo-youngpaca you're welcome. 

Will close this issue now, but feel free to reopen it if anything!
