### ISSUE TITLE
CCXT is running very slow

### ISSUE THREAD

**Issue by halocdn** [ccxt/ccxt#23908]
### Programming Languages

PHP

### CCXT Version

4.4

### Description

Hello, ccxt is very nice but it works very slowly, it takes 5 seconds to even withdraw the balance. I am using php 8.2.
Is there a way to speed it up?

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @halocdn,

Are you pre loading the markets? On the first unified call ccxt has to load the markets first so that can introduce some delay.

You can do this after instantiating the exchange `$ex->load_markets();`

**Comment by carlosmiei** [comment]
Alternatively you can also disable the rate limiter by doing `$ex->enable_rate_limit = false;`

**Comment by halocdn** [comment]
`require 'vendor/autoload.php';
$apiKey = 'x';
$secret = 'x';
$exchange = new \ccxt\gateio([
    'apiKey' => $apiKey,
    'secret' => $secret,
    'enableRateLimit' => false
]);
$gateBalance = $exchange->fetch_balance();`

**Comment by halocdn** [comment]
<img width="133" alt="Ekran Resmi 2024-10-04 17 37 26" src="https://github.com/user-attachments/assets/375abbd2-b250-4596-886a-80ce3d5e63cb">

**Comment by carlosmiei** [comment]
@halocdn Are you pre-loading the markets?

**Comment by halocdn** [comment]
No, I do not load the markets first, I use the code I gave above.

**Comment by carlosmiei** [comment]
@halocdn as I said, ccxt needs to warm up the cache (to load currencies, markets, precisions, etc) and that takes a few seconds. If you do not do it before calling `withdraw` that will be done inside withdraw and can delay the first request a bit.

**Comment by halocdn** [comment]
I think it would be best not to use ccxt, it is an extremely slow coding. I can withdraw the balance in 15 seconds, it just takes too long.

**Comment by kroitor** [comment]
@halocdn this is covered in the Manual here: https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

In other words, it is not an issue with CCXT code if you grasp the Manual and understand what is happening in the background during your first call to a unified method. It just depends on how and what exactly you're measuring.
Here's the code that measures just the fetch_balance call (and nothing else but that call):

If you run this code, it should print the actual balance fetching time, which in general should much less than 15 seconds, or even less than a second:

```PHP
<?php
require 'vendor/autoload.php';
$apiKey = 'x';
$secret = 'x';
$exchange = new \ccxt\gateio([ 'apiKey' => $apiKey, 'secret' => $secret, 'enableRateLimit' => false ]); 
$exchange->load_markets();
$start = $exchange->milliseconds()
echo 'Started fetching balance at: ' . $exchange->iso8601($start) . "\n";
$gateBalance = $exchange->fetch_balance();
$end = $exchange->milliseconds()
echo 'Ended fetching balance at: ' . $exchange->iso8601($end) . "\n";
echo 'Total time: ' . ($end - $start) . " milliseconds\n";
?>

Hope that answers your question. Feel free to reopen this issue or just ask further questions if you have any.

**Comment by carlosmiei** [comment]
@halocdn Yeah as Igor suggested please read the manual first you're not understanding where this delay is coming from...
