### ISSUE TITLE
Minimal (Generic or ByBit) Example of how to borrow Base

### ISSUE THREAD

**Issue by PlanetMacro** [ccxt/ccxt#23909]
### Operating System

Ubuntu

### Programming Languages

Python

### CCXT Version

4.4.3

### Description

The example for Binance [margin sell,](https://github.com/ccxt/ccxt/pull/14843) seems to be not applicable to ByBit. Is there a generic example of how to borrow on margin accounts? Or at least one for ByBit.

The following minimal example gives an error: "bybit borrowMargin is deprecated, please use borrowCrossMargin or borrowIsolatedMargin instead"

    async def borrow(self, coin, amount):
        try:
            result = await self.exchange.borrowMargin(coin, amount, self.symbol, {'marginMode': 'isolated'})
            return result
        except Exception as e:
            raise RuntimeError(f"An error occurred in borrow while borrowing {amount} {coin}: {e}") from e

However trying borrowIsolatedMargin instead gives 'bybit borrowIsolatedMargin is not support yet'

-------------------

It is not clear how borrowing/shorting should be done in general, or at least on ByBit.
  

Moreover I could not find API description for borrowIsolatedMargin at all.

**Comment by Dan-krm** [comment]
Hi @PlanetMacro I will open a pull request to update the binance example and the borrow margin documentation.

It doesn't look like bybit will support borrowIsolatedMargin but you should be able to call borrowCrossMargin:
`self.exchange.borrowCrossMargin(coin, amount, self.symbol)`
