### ISSUE TITLE
ERROR:root:Exception while placing trade order: Illegal category (ErrCode: 10001)

### ISSUE THREAD

**Issue by arkad-lang** [ccxt/ccxt#23902]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

4.4.13

### Description

The same errors repeat across several attempts for both `LONG` and `SHORT` orders.

### Steps to Reproduce
1. Use the By bit v5 API to set leverage for the symbol `FLOWUSDT`.
2. Try placing a market order for the same symbol.
3. Observe the errors.

### Expected Behavior
- Leverage should be set successfully.
- Trade orders should be placed without errors.

### Actual Behavior
- Error `Illegal category (ErrCode: 10001)` occurs when placing a trade order.
- Error `leverage not modified (ErrCode: 110043)` occurs when setting leverage.

### Additional Context
I believe the issue may be related to the API's handling of the `category` field or improper leverage settings for the `FLOWUSDT` symbol. Any guidance or clarification on these error codes would be appreciated.  

### Code

```
  

```
import tkinter as tk
from tkinter import scrolledtext, messagebox
import logging
import threading
import imaplib
import email
from email.header import decode_header
import time
import html
from pybit.unified_trading import HTTP

# Настройка логирования
logging.basicConfig(level=logging.INFO)

# Настройки для подключения к почтовому серверу
EMAIL_ACCOUNT = 'your_email@gmail.com'  # Замените на ваш email
EMAIL_PASSWORD = 'your_email_password'    # Замените на ваш пароль
IMAP_SERVER = 'gmail.com'
IMAP_PORT = 

# Настройки Bybit API
API_KEY = "your_api_key"                  # Замените на ваш API ключ
API_SECRET = "your_api_secret"            # Замените на ваш API секрет

# Инициализация Bybit сессии
session = HTTP(
    testnet=False,
    api_key=API_KEY,
    api_secret=API_SECRET
)

# Глобальные переменные
LEVERAGE = 10
POSITION_SIZE = 1  # Размер позиции в USDT
RUNNING = False
CHECK_INTERVAL = 60
MIN_PRICE_STEP = 0.0001
MIN_VOLUME_STEP = 0.1
MIN_VOLUME = 0.1
MAX_LEVERAGE = 25  # Максимальное плечо

def connect_to_mail():
    try:
        mail = imaplib.IMAP4_SSL(IMAP_SERVER, IMAP_PORT)
        mail.login(EMAIL_ACCOUNT, EMAIL_PASSWORD)
        return mail
    except imaplib.IMAP4.error as e:
        logging.error(f"Failed to connect to mail server: {e}")
        raise

def get_email_body(msg):
    if msg.is_multipart():
        for part in msg.walk():
            content_type = part.get_content_type()
            if content_type == 'text/plain':
                return part.get_payload(decode=True).decode('utf-8', errors='ignore')
    else:
        return msg.get_payload(decode=True).decode('utf-8', errors='ignore')
    return ""

def process_trade_info(body):
    try:
        body = html.unescape(body)
        trade_info = {}
        for line in body.split('\n'):
            if 'side' in line:
                trade_info['side'] = clean_string(line.split(': ')[1])
            elif 'entry' in line:
                trade_info['entry'] = clean_string(line.split(': ')[1])
            elif 'tp1' in line:
                trade_info['tp1'] = clean_string(line.split(': ')[1])
            elif 'stop' in line:
                trade_info['stop'] = clean_string(line.split(': ')[1])
        if all(key in trade_info for key in ['side', 'entry', 'tp1', 'stop']):
            logging.info("Trade Info: %s", trade_info)
            return trade_info
        else:
            logging.warning("Incomplete trade info received.")
            return None
    except Exception as e:
        logging.error(f"Error processing trade info: {e}")
        return None

def clean_string(value):
    if isinstance(value, str):
        return value.replace('"', '').replace("'", '').replace(",", "").strip()
    return value

def set_leverage(symbol, leverage):
    try:
        if leverage < 1 or leverage > MAX_LEVERAGE:
            logging.error(f"Leverage must be between 1 and {MAX_LEVERAGE}.")
            return

        leverage_str = str(leverage)
        response = session.set_leverage(
            category="linear",
            symbol=symbol.upper(),
            buyLeverage=leverage_str,
            sellLeverage=leverage_str
        )

        logging.info(f"API Response: {response}")
        if response['retCode'] == 0:
            logging.info(f"Leverage set to {leverage}x for symbol {symbol}")
        else:
            logging.error(f"Failed to set leverage: {response['retMsg']} (retCode: {response['retCode']})")
    except Exception as e:
        logging.error(f"Exception while setting leverage: {e}")

def place_trade_order(trade_info):
    try:
        symbol = "FLOWUSDT"
        set_leverage(symbol, LEVERAGE)

        entry_price = float(clean_string(trade_info.get('entry', 0)))
        tp_price = float(clean_string(trade_info.get('tp1', 0)))
        sl_price = float(clean_string(trade_info.get('stop', 0)))

        tp_price = round(tp_price - (tp_price % MIN_PRICE_STEP), 4)
        sl_price = round(sl_price - (sl_price % MIN_PRICE_STEP), 4)

        position_size = POSITION_SIZE / entry_price

        if position_size < MIN_VOLUME:
            logging.error("Position size is below minimum volume.")
            return None, None

        if position_size % MIN_VOLUME_STEP != 0:
            position_size = round(position_size - (position_size % MIN_VOLUME_STEP), 1)

        response = session.place_order(
            symbol=symbol,
            side=trade_info.get('side', 'Buy'),
            order_type="Market",
            qty=position_size,
            tp=tp_price,
            sl=sl_price
        )
        logging.info(f"Order placed: {response}")
        order_id = response['result']['order_id']
        return order_id, entry_price
    except Exception as e:
        logging.error(f"Exception while placing trade order: {e}")
        return None, None

def fetch_emails(mail):
    try:
        mail.select('"TradingView Alerts"')
        status, data = mail.search(None, '(UNSEEN)')
        if status != 'OK':
            logging.error("Failed to search inbox.")
            return

        email_ids = data[0].split()
        if not email_ids:
            logging.info("No new emails.")
            return

        for num in email_ids:
            status, msg_data = mail.fetch(num, '(RFC822)')
            if status != 'OK':
                logging.error(f"Failed to fetch email ID {num}")
                continue

            msg = email.message_from_bytes(msg_data[0][1])
            body = get_email_body(msg)

            if "side" in body and "entry" in body and "tp1" in body and "stop" in body:
                trade_info = process_trade_info(body)
                if trade_info:
                    order_id, entry_price = place_trade_order(trade_info)
                    
            mail.store(num, '+FLAGS', '\\Seen')
            logging.info(f"Email ID {num} marked as seen.")
    except Exception as e:
        logging.error(f"Exception while fetching emails: {e}")

def start_monitoring():
    global RUNNING
    RUNNING = True
    mail = connect_to_mail()
    while RUNNING:
        fetch_emails(mail)
        time.sleep(CHECK_INTERVAL)

def stop_monitoring():
    global RUNNING
    RUNNING = False

# Настройка интерфейса
root = tk.Tk()
root.title("Торговый монитор")

frame = tk.Frame(root)
frame.pack(pady=10)

technical_log = scrolledtext.ScrolledText(frame, width=80, height=20)
technical_log.pack(padx=10, pady=10)

trade_log = scrolledtext.ScrolledText(frame, width=80, height=10)
trade_log.pack(padx=10, pady=10)

leverage_label = tk.Label(frame, text="Плечо:")
leverage_label.pack()
leverage_entry = tk.Entry(frame)
leverage_entry.insert(0, str(LEVERAGE))
leverage_entry.pack()

position_size_label = tk.Label(frame, text="Размер позиции (USDT):")
position_size_label.pack()
position_size_entry = tk.Entry(frame)
position_size_entry.insert(0, str(POSITION_SIZE))
position_size_entry.pack()

start_button = tk.Button(frame, text="Начать мониторинг", command=lambda: threading.Thread(target=start_monitoring).start())
start_button.pack(pady=5)

stop_button = tk.Button(frame, text="Остановить мониторинг", command=stop_monitoring)
stop_button.pack(pady=5)

root.mainloop()

**Comment by carlosmiei** [comment]
Hello @arkad-lang,

Can you try to use the unified syntax for the symbol?

`FLOW/USDT` : spot
`FLOW/USDT:USDT` : linear perp

if that does not work, can you please provide a verbose log? `exchange.verbose = True`

**Comment by arkad-lang** [comment]
Problem Description

I am trying to enable verbose logging for the Bybit API session using the `pybit` library.

Here’s my code:

python
from pybit.unified_trading import HTTP

api_key = "YOUR_API_KEY"
api_secret = "YOUR_API_SECRET"

session = HTTP(
    testnet=False,
    api_key=api_key,
    api_secret=api_secret
)

session.verbose = True  # Enabling verbose logging

When I run the code, I receive the following error:

TypeError: _V5HTTPManager.__init__() got an unexpected keyword argument 'verbose'

Logs
Also, here are the logs I get after calling the API:

INFO:root:Subject: Notification: (MANUAL, 1, 145, ...)
ERROR:root:Exception while setting leverage: leverage not modified (ErrCode: 110043)
ERROR:root:Exception while placing trade order: Illegal category (ErrCode: 10001)

**Comment by carlosmiei** [comment]
@arkad-lang This is the CCXT repo, if you're not using it then I don't know how to help you 😅

**Comment by arkad-lang** [comment]
@carlosmiei thank you very much. The thing is, I'm a beginner. but I will learn CCXT. and I will try to use FLOW/USDT either 
FLOW/USDT:USDT  . I think you can close the appeal
