### ISSUE TITLE
Error When Setting Stop-Loss and Take-Profit Orders on By bit 

### ISSUE THREAD

**Issue by arkad-lang** [ccxt/ccxt#23913]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

4.4.13

### Description

Issues with Setting Stop-Loss and Take-Profit Orders on Bybit Using CCXT
Description of the Problem:

I am encountering issues when trying to set stop-loss and take-profit orders on the Bybit exchange using the CCXT library. I have explored two approaches, but neither has yielded satisfactory results.

Approach 1: Setting Stop-Loss and Take-Profit as Part of the Position

In this method, I attempted to create a stop-loss and take-profit in the "Part of Position" tab, but I faced difficulties indicating 100% of the position. The parameters for the orders did not allow using the full amount.

Approach 2: Creating Separate Orders for Stop-Loss and Take-Profit

In the second approach, I tried to create separate orders for the stop-loss and take-profit linked to the main order. The take-profit is set successfully, but I am unable to set the stop-loss, and I encounter the following error: Error while setting stop-loss and take-profit orders:  bybit {"retCode":10001,"retMsg":"OrderType invalid","result":{},"retExtInfo":{},"time":1728152048728}

Here’s the relevant code snippet I used for the second approach:
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
# Убедитесь, что amount соответствует минимальному размеру
if amount < min_amount:
    print(f"Указанное количество {amount} меньше минимального размера {min_amount}.")
else:
    # Открываем рынок на покупку
    try:
        # Округляем amount до 1 знака после запятой
        rounded_amount = round(amount, 1)

        # Открываем рыночный ордер
        order = exchange.create_market_order(symbol=symbol, side='buy', amount=rounded_amount)
        print(f"Ответ от создания ордера: {order}")  # Добавляем вывод ответа
        order_id = order['id']

        # Ждем немного, чтобы ордер обработался
        time.sleep(1)

        # Получаем последнюю цену на рынке
        ticker = exchange.fetch_ticker(symbol)
        entry_price = ticker['last']  # Последняя цена на рынке
        print(f'Последняя цена на рынке: {entry_price:.4f}')

        if entry_price is None:
            print("Ошибка: Не удалось получить цену входа.")
        else:
            print(f'Order ID: {order_id}')
            print(f'Цена входа: {entry_price:.4f}')

            # Параметры для стоп-лосса и тейк-профита
            stop_loss_price = round(entry_price * (1 - 0.04), 4)  # 4% ниже
            take_profit_price = round(entry_price * (1 + 0.01), 4)  # 1% выше

            # Устанавливаем стоп-лосс
            try:
                stop_loss_order = exchange.create_order(
                    symbol=symbol,
                    type='stop_market',  # Стоп-ордер
                    side='sell',  # Продаем
                    amount=rounded_amount,  # Используем 100% от позиции
                    params={
                        'stopPrice': stop_loss_price,  # Триггерная цена
                        'triggerDirection': 'below',  # Направление триггера (при падении)
                        'reduceOnly': True  # Закрыть всю позицию
                    }
                )
                print(f"Стоп-лосс установлен на {stop_loss_price:.4f} с ID: {stop_loss_order['id']}.")

            except Exception as e:
                print(f'Ошибка при установке стоп-лосса: {e}')

            # Устанавливаем тейк-профит
            try:
                take_profit_order = exchange.create_order(
                    symbol=symbol,
                    type='limit',  # Лимитный ордер для тейк-профита
                    side='sell',  # Продаем
                    amount=rounded_amount,  # Используем 100% от позиции
                    price=take_profit_price,  # Устанавливаем цену
                    params={
                        'reduceOnly': True  # Закрыть всю позицию
                    }
                )
                print(f"Тейк-профит установлен на {take_profit_price:.4f} с ID: {take_profit_order['id']}.")

            except Exception as e:
                print(f'Ошибка при установке тейк-профита: {e}')

    except Exception as e:
        print(f'Ошибка при создании рыночного ордера: {e}')

print("Orders placed: Stop Loss and Take Profit.")

### Code

```
  

```
import ccxt
import time

# Ваши ключи API
api_key = ''
api_secret = ''

# Создаем экземпляр биржи Bybit
exchange = ccxt.bybit({
    'apiKey': api_key,
    'secret': api_secret,
    'enableRateLimit': True,
})

# Загружаем рынки
markets = exchange.load_markets()

# Укажите параметры вашей сделки
symbol = 'FLOW/USDT:USDT'  # Фьючерсный рынок
amount = 0.1  # Размер позиции (должен быть больше минимального)

# Получаем информацию о минимальном размере ордера
min_amount = markets[symbol]['limits']['amount']['min']
print(f'Минимальный размер ордера для {symbol}: {min_amount}')

# Убедитесь, что amount соответствует минимальному размеру
if amount < min_amount:
    print(f"Указанное количество {amount} меньше минимального размера {min_amount}.")
else:
    # Открываем рынок на покупку
    try:
        # Округляем amount до 1 знака после запятой
        rounded_amount = round(amount, 1)

        # Открываем рыночный ордер
        order = exchange.create_market_order(symbol=symbol, side='buy', amount=rounded_amount)
        print(f"Ответ от создания ордера: {order}")  # Добавляем вывод ответа
        order_id = order['id']

        # Ждем немного, чтобы ордер обработался
        time.sleep(1)

        # Получаем последнюю цену на рынке
        ticker = exchange.fetch_ticker(symbol)
        entry_price = ticker['last']  # Последняя цена на рынке
        print(f'Последняя цена на рынке: {entry_price:.4f}')

        if entry_price is None:
            print("Ошибка: Не удалось получить цену входа.")
        else:
            print(f'Order ID: {order_id}')
            print(f'Цена входа: {entry_price:.4f}')

            # Параметры для стоп-лосса и тейк-профита
            stop_loss_price = round(entry_price * (1 - 0.04), 4)  # 4% ниже
            take_profit_price = round(entry_price * (1 + 0.01), 4)  # 1% выше

            # Устанавливаем ордера со стоп-лоссом и тейк-профитом для закрытия всей позиции
            params = {
                'stopLoss': {
                    'type': 'market',  # или 'limit'
                    'triggerPrice': stop_loss_price,  # Триггерная цена стоп-лосса
                    'price': stop_loss_price,  # Цена исполнения стоп-лосса
                    'reduceOnly': True  # Закрыть всю позицию
                },
                'takeProfit': {
                    'type': 'limit',  # или 'market'
                    'triggerPrice': take_profit_price,  # Триггерная цена тейк-профита
                    'price': take_profit_price,  # Цена исполнения тейк-профита
                    'reduceOnly': True  # Закрыть всю позицию
                }
            }

            try:
                # Открываем лимитный ордер с установленными стоп-лоссом и тейк-профитом
                order_with_sl_tp = exchange.create_order(
                    symbol=symbol,
                    type='limit',
                    side='buy',  # Покупка
                    amount=rounded_amount,
                    price=entry_price,
                    params=params
                )
                print(f"Ордер с установленными стоп-лоссом и тейк-профитом: {order_with_sl_tp}")

            except Exception as e:
                print(f'Ошибка при установке ордера со стоп-лоссом и тейк-профитом: {e}')

    except Exception as e:
        print(f'Ошибка при создании рыночного ордера: {e}')

print("Orders placed: Stop Loss and Take Profit.")

**Comment by arkad-lang** [comment]
@carlosmiei Can you please advise?

**Comment by Dan-krm** [comment]
Hi @arkad-lang 

For approach 1 you can try setting the exchange specific param `"tpslMode":"Full"` and `"slOrderType ":"Market"` to indicate 100% of the position

For approach 2 you could try setting the `"stopLossPrice"` param, instead of `"stopPrice"`

Let me know if those adjustments work for you

Here is the endpoint CCXT is using with it's exchange specific parameters:
https://bybit-exchange.github.io/docs/v5/order/create-order

Here is some information on placing different orders from the CCXT docs:
https://docs.ccxt.com/#/?id=placing-orders

**Comment by arkad-lang** [comment]
approach number 2 worked. and I haven't tried the first one. but here's what's wrong. if I click close a position on the stock exchange. The stop loss order remains. and the tp is deleted along with the order . is there a solution to this? @Dan-krm

**Comment by arkad-lang** [comment]
@Dan-krm  You know what, it doesn't matter. I tried approach number 1 and it works great. Thank you very much. I am very grateful to you. God bless you. Even though I don't believe in hahahahahh. )) I love you.

**Comment by Dan-krm** [comment]
I'm glad that it worked! I'll close this issue now, let us know if there is anything else.
