### ISSUE TITLE
Issue with Opening New Position and Status Return for Bybit Futures Orders

### ISSUE THREAD

**Issue by arkad-lang** [ccxt/ccxt#23922]
### Operating System

Windows 10

### Programming Languages

Python

### CCXT Version

4.4.13

### Description

Description of the Problem:

When attempting to close an order, I receive the error: order not exists or too late to cancel. However, despite the error, the order is eventually closed.
The issue with opening a new position occurs only when I try to open a position in the opposite direction (e.g., switching from long to short or vice versa). If there are no open positions on the exchange, the first position is opened correctly.
After creating a new order, its status remains undefined (status: None), and in the end, the new order is not opened.

The positions should be opened and closed without errors or incorrect statuses.

### Code

```
  

```
import ccxt
import imaplib
import email
import json
import time
from datetime import datetime

# API keys for Bybit
api_key = 'YOUR_API_KEY'
api_secret = 'YOUR_API_SECRET'

# Bybit exchange initialization
exchange = ccxt.bybit({
    'apiKey': api_key,
    'secret': api_secret,
    'enableRateLimit': True,
})

# Email settings
EMAIL_ACCOUNT = 'YOUR_EMAIL@gmail.com'
EMAIL_PASSWORD = 'YOUR_EMAIL_PASSWORD'
IMAP_SERVER = 'imap.gmail.com'
IMAP_PORT = 993

symbol = 'FLOW/USDT:USDT'
amount = 0.1

last_order_id = None

markets = exchange.load_markets()
min_amount = markets[symbol]['limits']['amount']['min']

# Email extraction function
def get_email_body(msg):
    body = ""
    if msg.is_multipart():
        for part in msg.walk():
            content_type = part.get_content_type()
            content_disposition = str(part.get("Content-Disposition"))
            if content_type == "text/plain" and "attachment" not in content_disposition:
                body = part.get_payload(decode=True).decode()
                break
    else:
        body = msg.get_payload(decode=True).decode()
    return body

# Email trading signal function
def get_trade_signal():
    mail = imaplib.IMAP4_SSL(IMAP_SERVER, IMAP_PORT)
    mail.login(EMAIL_ACCOUNT, EMAIL_PASSWORD)
    mail.select('"TradingView Alerts"')

    result, data = mail.search(None, '(UNSEEN)')
    email_ids = data[0].split()

    for e_id in email_ids:
        result, msg_data = mail.fetch(e_id, '(RFC822)')
        raw_email = msg_data[0][1]
        msg = email.message_from_bytes(raw_email)
        body = get_email_body(msg)

        try:
            trade_signal = json.loads(body.strip())
            required_keys = ['side', 'entry', 'stop', 'tp1', 'tp2', 'tp3', 'tp4']
            if all(key in trade_signal for key in required_keys):
                return {
                    'side': trade_signal['side'],
                    'entry': float(trade_signal['entry']),
                    'stop_loss': float(trade_signal['stop']),
                    'take_profit': [
                        float(trade_signal[f'tp{i + 1}']) for i in range(4)
                    ],
                }
            else:
                return None
        except json.JSONDecodeError as e:
            return None
        except Exception as e:
            return None
    mail.logout()
    return None

# Close open orders
def close_open_orders(symbol):
    try:
        open_orders = exchange.fetch_open_orders(symbol)
        if len(open_orders) > 0:
            for order in open_orders:
                cancel_order = exchange.cancel_order(order['id'], symbol)
        else:
            print("No open orders.")
    except Exception as e:
        print(f"Error closing orders: {e}")

# Open new position
def open_new_position(trade_signal, symbol):
    global last_order_id
    side = trade_signal['side'].upper()
    entry_price = trade_signal['entry']
    stop_loss_price = trade_signal['stop_loss']
    take_profit_prices = trade_signal['take_profit']

    try:
        rounded_amount = round(amount, 1)
        order_side = 'buy' if side == 'LONG' else 'sell'

        order = exchange.create_market_order(symbol=symbol, side=order_side, amount=rounded_amount)
        last_order_id = order['id']

        if order['status'] == 'closed':
            print(f"Order with ID {order['id']} already filled.")
        elif order['status'] == 'open':
            print(f"Order with ID {order['id']} is still open.")
        else:
            print(f"Unknown order status: {order['status']}")

        if order_side == 'buy':
            stop_loss_price = round(entry_price * (1 - 0.04), 4)
            take_profit_price = round(entry_price * (1 + 0.01), 4)
        else:
            stop_loss_price = round(entry_price * (1 + 0.04), 4)
            take_profit_price = round(entry_price * (1 - 0.01), 4)

        params = {
            'tpslMode': 'Full',
            'slOrderType': 'Market',
            'tpOrderType': 'Market',
            'stopLoss': {
                'type': 'market',
                'triggerPrice': stop_loss_price,
                'reduceOnly': True
            },
            'takeProfit': {
                'type': 'market',
                'triggerPrice': take_profit_price,
                'reduceOnly': True
            }
        }

        order_with_sl_tp = exchange.create_order(
            symbol=symbol,
            type='market',
            side=order_side,
            amount=rounded_amount,
            params=params
        )
    except Exception as e:
        print(f"Error creating market order: {e}")

while True:
    now = datetime.now()
    if now.second == 0:
        time.sleep(5)
        trade_signal = get_trade_signal()
        if trade_signal is None:
            print("No new signals.")
        else:
            close_open_orders(symbol)
            open_new_position(trade_signal, symbol)
    time.sleep(0.1)

**Comment by arkad-lang** [comment]
Error when closing an order:  bybit {"retCode":110001,"retMsg":"order not exists or too late to cancel","result":{},"retExtInfo":{},"time":1728312068050}

The response from the creation of the order:  {'info': {'orderId': '06086022-7d56-4d96-953a-355530f5e009', 'orderLinkId': ''}, 
'id': '06086022-7d56-4d96-953a-355530f5e009', 
'clientOrderId': None, 
'timestamp': None, 
'datetime': None, 
'lastTradeTimestamp': None, 
'lastUpdateTimestamp': None, 
'symbol': 'FLOW/USDT:USDT', 
'type': None, 
'timeInForce': None, 
'postOnly': None, 
'reduceOnly': None, 
'side': None, 
'price': None, 
'stopPrice': None, 
'triggerPrice': None, 
'takeProfitPrice': None, 
'stopLossPrice': None, 
'amount': None, 
'cost': None, 
'average': None, 
'filled': None, 
'remaining': None, 
'status': None, 
'fee': None, 
'trades': [], 
'fees': []}

**Comment by rayBastard** [comment]
Hi @arkad-lang!
Thanks for your report. We will check it out asap.

**Comment by arkad-lang** [comment]
@rayBastard  thanks . I'll be waiting

**Comment by arkad-lang** [comment]
@carlosmiei Can you help me?

**Comment by rayBastard** [comment]
@arkad-lang and @carlosmiei looks like this is an error on the exchange's side. I've also recieved an error 

`{"retCode":110001,"retMsg":"order not exists or too late to cancel","result":{},"retExtInfo":{},"time":1728482916448}`

but looks like order is closing despite this error.  We'll think what can we do with it.

**Comment by arkad-lang** [comment]
@rayBastard in general, the order is closed, but with an error, if desired, you can leave it that way. but the problem with opening a new order needs to be solved. Thanks for the help

**Comment by arkad-lang** [comment]
@rayBastard  Why was it closed?
