### ISSUE TITLE
New Exchange: ercdex

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#2393]
uri: https://ercdex.com
source kit: https://aqueduct.ercdex.com/
standard api: https://github.com/0xProject/standard-relayer-api
doc: https://github.com/ercdex/aqueduct#overview
api: https://aqueduct.ercdex.com/rest.html

**Comment by An-Net** [comment]
Shutdown since 23 November 2020

- https://medium.com/ercdex/halting-utility-token-trading-and-preparing-for-the-next-chapter-3ee954734716

![Снимок экрана 2020-07-21 в 18 06 14](https://user-images.githubusercontent.com/51840849/88071910-157bb200-cb7d-11ea-9cb8-c6f78fb5c46c.png)
