### ISSUE TITLE
Hyperliquid fetch_open_orders() 'side' and 'collateral' are always None

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#23946]
### Operating System

n/a

### Programming Languages

Python

### CCXT Version

4.4.10

### Description

Hello,

hyperluid fetch_positions() is missing some data:

### `side` is always `None`. 
However, the side can be set by looking at the hyperliquid api response, if `position["szi"]` is negative, it's a short. If it's positive, it's a long.

### `collateral` is always `None` 
I believe this is `position["marginUsed"]` returned by the hyperliquid api, which for an open position changes depending on the positionValue, which changes depending on the price. I tested this:

Long position with leverage 1, fetched 2 times:
`{"assetPositions":[{"type":"oneWay","position":{"coin":"BTC","szi":"0.0002","leverage":{"type":"cross","value":1},"entryPx":"60705.0","positionValue":"12.1406","unrealizedPnl":"-0.0004","returnOnEquity":"-0.00003295","liquidationPx":null,"marginUsed":"12.1406","maxLeverage":50,"cumFunding":{"allTime":"-0.000183","sinceOpen":"0.0","sinceChange":"0.0"}}}]}`
To calculate the collateral, the position opened at price 60705.0 * 0.0002 = 12.141 -0.0004 = 12.1406 , which is equal to `position["marginUsed"]`

`{"assetPositions":[{"type":"oneWay","position":{"coin":"BTC","szi":"0.0002","leverage":{"type":"cross","value":1},"entryPx":"60705.0","positionValue":"12.1468","unrealizedPnl":"0.0058","returnOnEquity":"0.00047772","liquidationPx":null,"marginUsed":"12.1468","maxLeverage":50,"cumFunding":{"allTime":"-0.000183","sinceOpen":"0.0","sinceChange":"0.0"}}}]}`
To calculate the collateral, the position opened at price 60705.0 * 0.0002 = 12.141 + 0.0058 = 12.1468 , which is equal to `position["marginUsed"]`

Long position with leverage 2, fetched 2 times:
`{"assetPositions":[{"type":"oneWay","position":{"coin":"BTC","szi":"0.0002","leverage":{"type":"cross","value":2},"entryPx":"60810.0","positionValue":"12.1598","unrealizedPnl":"-0.0022","returnOnEquity":"-0.00036178","liquidationPx":null,"marginUsed":"6.0799","maxLeverage":50,"cumFunding":{"allTime":"-0.000183","sinceOpen":"0.0","sinceChange":"0.0"}}}]}`
To calculate the collateral, the position opened at price 60810.0 * 0.0002 / 2 (leverage) = 6.081 - 0.0022/2(leverage) = 6.0799 , which is equal to position`["marginUsed"]`

`{"assetPositions":[{"type":"oneWay","position":{"coin":"BTC","szi":"0.0002","leverage":{"type":"cross","value":2},"entryPx":"60810.0","positionValue":"12.1684","unrealizedPnl":"0.0064","returnOnEquity":"0.00105246","liquidationPx":null,"marginUsed":"6.0842","maxLeverage":50,"cumFunding":{"allTime":"-0.000183","sinceOpen":"0.0","sinceChange":"0.0"}}}]}`
To calculate the collateral, the position opened at price 60810.0 * 0.0002 / 2 (leverage) = 6.081 + 0.0064/2(leverage) = 6.0842 , which is equal to `position["marginUsed"]`

Can those values be added? Thanks!

### Code

```
pprint(await e.fetch_positions())

[{'collateral': None,
  'contractSize': 1.0,
  'contracts': 0.0002,
  'datetime': None,
  'entryPrice': 60810.0,
  'hedged': None,
  'id': None,
  'info': {'position': {'coin': 'BTC',
                        'cumFunding': {'allTime': '-0.000183',
                                       'sinceChange': '0.0',
                                       'sinceOpen': '0.0'},
                        'entryPx': '60810.0',
                        'leverage': {'type': 'cross', 'value': '2'},
                        'liquidationPx': None,
                        'marginUsed': '6.0842',
                        'maxLeverage': '50',
                        'positionValue': '12.1684',
                        'returnOnEquity': '0.00105246',
                        'szi': '0.0002',
                        'unrealizedPnl': '0.0064'},
           'type': 'oneWay'},
  'initialMargin': 6.0842,
  'initialMarginPercentage': None,
  'isolated': False,
  'leverage': 2.0,
  'liquidationPrice': None,
  'maintenanceMargin': None,
  'maintenanceMarginPercentage': None,
  'marginMode': None,
  'markPrice': None,
  'notional': 12.1684,
  'percentage': 0.10519049340915815,
  'side': None,
  'symbol': 'BTC/USDC:USDC',
  'timestamp': None,
  'unrealizedPnl': 0.0064}]
```

**Comment by sc0Vu** [comment]
@gaardiolor Thanks for the report. We'll fix this asap.

**Comment by carlosmiei** [comment]
@gaardiolor Can you please upgrade and try again? It should be working now

**Comment by gaardiolor** [comment]
Yes, looks good to me. Thanks!
