### ISSUE TITLE
XT.com does not show any open orders

### ISSUE THREAD

**Issue by AltePfeife** [ccxt/ccxt#23952]
### Operating System

WIN10

### Programming Languages

Python

### CCXT Version

4.4.15

### Description

I have created a stopprice order via API:

    
    def create_order_stopprice(symbol):

    ticker = "XRP/USDT:USDT"
    side = 'buy'
    quantity = 1
    price = 0.7

    response = exchange.create_order(symbol=symbol, type="market", side=side,
                                amount=quantity, price=None,
                                params={'stopPrice': price,
                                        'triggerPriceType': 'LATEST_PRICE',
                                        'timeInForce': 'IOC',
                                        'reduceOnly': True
                                        })

    pprint(response)`

the open order also appears on XT.com under open order -> trigger order:
![grafik](https://github.com/user-attachments/assets/c2e741ea-2709-419d-ba6c-3ef909dbc354)

but it is not output to me with any function. neither fetch_open_order() nor fetch_order() returns a return value.

with other exchanges like bybit, binance or phemex it works. 

### Code

```
def create_order_stopprice(symbol):

ticker = "XRP/USDT:USDT"
side = 'buy'
quantity = 1
price = 0.7


response = exchange.create_order(symbol=symbol, type="market", side=side,
                            amount=quantity, price=None,
                            params={'stopPrice': price,
                                    'triggerPriceType': 'LATEST_PRICE',
                                    'timeInForce': 'IOC',
                                    'reduceOnly': True
                                    })

pprint(response)

```

**Comment by sc0Vu** [comment]
@AltePfeife Usually, you need to use a different API to fetch stop orders. Can you try setting `{'stop': True}` when fetching orders?

**Comment by AltePfeife** [comment]
Thank you, it works. 
{'stop': True} is the solution.
