### ISSUE TITLE
Binance throwing errors recently

### ISSUE THREAD

**Issue by wannesdemaeght** [ccxt/ccxt#2396]
Since 2 days,  binance has been throwing frequent errors (around 2000 per day), that don't really tell much:

> "Error: binance GET https://api.binance.com/api/v1/depth?symbol=BCCBTC system request to https://api.binance.com/api/v1/depth?symbol=BCCBTC failed, reason: connect ECONNREFUSED 54.230.9.209:443\n    at fetchImplementation.catch.e (C:\\Trader\\Logic\\node_modules\\ccxt\\js\\base\\Exchange.js:314:35)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"
> 
> "Error: binance GET https://api.binance.com/api/v3/account?timestamp=1522324283632&recvWindow=5000&signature=4a36edc99232d86ce3291d4a414e1bf46a491934825887f68d5c73b4cc3ca5bd system request to https://api.binance.com/api/v3/account?timestamp=1522324283632&recvWindow=5000&signature=4a36edc99232d86ce3291d4a414e1bf46a491934825887f68d5c73b4cc3ca5bd failed, reason: connect ECONNREFUSED 54.230.9.209:443\n    at fetchImplementation.catch.e (C:\\Trader\\Logic\\node_modules\\ccxt\\js\\base\\Exchange.js:314:35)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"

As you can see, this affects both public and private endpoints.
Any idea what could have started this error? (Script was running for 2 weeks straight before this started happening, no changes at all)

**Comment by kroitor** [comment]
Feel free to reopen this if needed or just ask questions if any. Thx!
