### ISSUE TITLE
Coinbase International subscribe_multiple passing marketId to symbol function

### ISSUE THREAD

**Issue by timborden** [ccxt/ccxt#23963]
### Operating System

MacOS

### Programming Languages

Python

### CCXT Version

4.4.11

### Description

The `symbol` [method](https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L3984-L3986) in Base Exchange class expects the **unified market symbol** but the Coinbase International exchange **market id** is passed by the  `subscribe_multiple` [method](https://github.com/ccxt/ccxt/blob/master/python/ccxt/pro/coinbaseinternational.py#L148) in Coinbase International class

### Code

```
 File ".../site-packages/ccxt/pro/coinbaseinternational.py", line 148, in subscribe_multiple
    symbol = self.symbol(marketId)
             ^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/ccxt/base/exchange.py", line 3965, in symbol
    market = self.market(symbol) 
```

**Comment by sc0Vu** [comment]
@timborden It works in other exchanges, (p coinbase symbol ETH-USDC). Can you paste more log or test script?

**Comment by timborden** [comment]
Thanks for the quick response @sc0Vu!

Comparing the `Coinbase` and `Coinbase International` classes, the `subscribe_multiple` in the `Coinbase` class doesn't pass the `marketId` to the `symbol` method:
![Screenshot 2024-10-11 at 12 31 26 PM](https://github.com/user-attachments/assets/4f2ba24a-0936-43f5-b360-f1bec364c005)

**Comment by sc0Vu** [comment]
@timborden Oh, I see. Does it cause any issues?

**Comment by timborden** [comment]
@sc0Vu It raises a `ccxt.base.errors.BadSymbol: coinbaseinternational does not have market symbol ZRO-PERP` ....when trying to subscribe to `ZRO/USDC`, for example.

**Comment by sc0Vu** [comment]
@timborden Do you try to subscribe `ZRO/USDC:USDC` market?

```BASH
$ p coinbaseinternational symbol ZRO-PERP
Python v3.11.4
CCXT v4.4.11
coinbaseinternational.symbol(ZRO-PERP)
'ZRO/USDC:USDC'
```

**Comment by timborden** [comment]
@sc0Vu you're right! It was something on my end....my bad.  Thanks for your help troubleshooting....sorry for taking your time.
