### ISSUE TITLE
A call to Promise.race() in Exchange.watchMultiple() create a memory leak when watching for trades

### ISSUE THREAD

**Issue by ggecy** [ccxt/ccxt#23972]
### Operating System

MacOS 14.6.1

### Programming Languages

JavaScript/Typescript

### CCXT Version

4.4.17

### Description

I am trying to use `binance` ccxt pro exchange where I split all the binane spot market symbols to batches of up to 200 symbols and then for each batch I launch in a separate function an infinite while(true) loop that awaits `watchTradesForSymbols(batch)` to get the realtime updates as in documentation. This leads to memory leak, which seems to be caused by calling `Future.race()` which in turn calls `Promise.race()` inside the `Exchange.watchMultiple()` function - please refer to this thread about [Promise.race lead to memory leak](https://github.com/nodejs/node/issues/17469) of why it might be happening and possible solution in comments.  It seems that basically awaiting the ` Promise.race()` in infinite loop retains all the promises internally when there is some long lived promise among them even after you delete them from the Client.futures. I was inspecting the memory snapshot of nodejs process through Chrome Developer Tools and there were literally gigabytes of promises from `Client.futures`

Just let the sample run in node.js for a long time and it will crash on out of memory eventually. You see increasing memory usage in console output every 30 seconds.

### Code

```typescript
import ccxt, { Exchange, Trade } from "ccxt";  

function logMemoryUsage() {
    const megaByte = 1024 * 1024;
    let message = "Node.js memory usage:";
    for (const [key,value] of Object.entries(process.memoryUsage())){
        message += `\n\t${key}: ${value/megaByte} MB`
    }
    console.info(message);
}

logMemoryUsage();
setInterval(() => {
    logMemoryUsage();
}, 30000);

let tradesReceived = 0;
let tradesReceivedTotal = 0;

async function streamData() {
    const binance = new ccxt.pro.binance();
    binance.newUpdates = true;
    await binance.loadMarkets();
    const spotMarkets = binance.getSymbolsForMarketType('spot');
    const startTime = Date.now();

    setInterval(() => {
        console.log("Received ", tradesReceived, " trades per second, total run time: ", (Date.now() - startTime) / 1000, " seconds");
        tradesReceived = 0;
    }, 1000);
    
    let batch: string[] = [];
    for (const symbol of spotMarkets) {
        batch.push(symbol);
        if (batch.length % 200 === 0) {
            watchTrades(binance, batch);
            batch = [];
        }
    }
    if (batch.length > 0) {
        watchTrades(binance, batch);
    }
}

async function watchTrades(exchange: Exchange, symbols: string[]) {
    let trades: Trade[];
    while (!shouldStop) {
        try {
            trades = await exchange.watchTradesForSymbols(symbols);
            const simulateSomeWork = JSON.stringify(trades);
            if (simulateSomeWork.length > 0) {
                tradesReceived += trades.length;
                tradesReceivedTotal += trades.length;
            }
        } catch (e) {
            console.error("Error in watchTrades", e);
        }
    }
}

streamData();

```

**Comment by ggecy** [comment]
Update: I have tried to manually edit the 
```
node_modules/ccxt/dist/cjs/src/base/Exchange.js
``` 
(since it's running in node.js), I changed the `watchMultiple` method and replaced the following line:
```javascript
const future = Future.Future.race(messageHashes.map(messageHash => client.future(messageHash)));
```
with `@watchable/unpromise` version of `race()`:
```javascript
const future = unpromise.Unpromise.race(messageHashes.map(messageHash => client.future(messageHash)));
```
and now the memory is released property. Standard version of `Promise.race()` won't release the promises until all of them are resolved, while the `Unpromise.race()` removes the callbacks internally once first of the promises is resolved.

**Comment by carlosmiei** [comment]
Hello @ggecy, thanks a lot for reporting it.

@pcriadoperez can you check this please?

**Comment by pcriadoperez** [comment]
Thanks a lot for the detailed report @ggecy !

Indeed I was able to reproduce the issue.

I'll check with @carlosmiei the best approach to merge.

Here is the analysis:
Current memory usage:
```
timestamp: 1728928826049, heapUsed: 54.920326232910156 MB
timestamp: 1728928836050, heapUsed: 93.84746551513672 MB
...
timestamp: 1728928976047, heapUsed: 993.2449188232422 MB
...
timestamp: 1728929236059, heapUsed: 1670.3614959716797 MB
...
timestamp: 1728929316055, heapUsed: 1320.9106674194336 MB
timestamp: 1728929326055, heapUsed: 1448.8666152954102 MB
timestamp: 1728929336055, heapUsed: 1549.6961288452148 MB
```

### Solution 1: Using unpromise:
Pros: tested solution, 50K weekly downloads on npm, no open issues on functionality
Cons: introducing library dependency
PR: https://github.com/ccxt/ccxt/pull/23984
Memory usage:
```
timestamp: 1728928314915, heapUsed: 54.65647888183594 MB
timestamp: 1728928324917, heapUsed: 82.58887481689453 MB
timestamp: 1728928334915, heapUsed: 234.75003814697266 MB
timestamp: 1728928344916, heapUsed: 135.04785919189453 MB
timestamp: 1728928354916, heapUsed: 237.49298095703125 MB
timestamp: 1728928364915, heapUsed: 189.5373992919922 MB
timestamp: 1728928374914, heapUsed: 148.83470916748047 MB
timestamp: 1728928384922, heapUsed: 108.76705932617188 MB
timestamp: 1728928394920, heapUsed: 183.73666381835938 MB
timestamp: 1728928404929, heapUsed: 215.69203186035156 MB
timestamp: 1728928414935, heapUsed: 402.4666976928711 MB
timestamp: 1728928424934, heapUsed: 217.12704467773438 MB
timestamp: 1728928434938, heapUsed: 134.58478546142578 MB
timestamp: 1728928444946, heapUsed: 282.9020233154297 MB
```

### Solution 2: own weakmap implementation:
Pros: no library dependency
Cons: Introducing complexity and can be more prone to bugs.
PR:  https://github.com/ccxt/ccxt/pull/23986
```
timestamp: 1728927584290, heapUsed: 56.070648193359375 MB
timestamp: 1728927594291, heapUsed: 104.31298065185547 MB
timestamp: 1728927604291, heapUsed: 136.7327880859375 MB
timestamp: 1728927614290, heapUsed: 109.65381622314453 MB
timestamp: 1728927624291, heapUsed: 108.245361328125 MB
timestamp: 1728927634290, heapUsed: 135.9030990600586 MB
timestamp: 1728927644288, heapUsed: 163.15237426757812 MB
...
timestamp: 1728928004286, heapUsed: 383.9420928955078 MB
timestamp: 1728928014285, heapUsed: 423.4413833618164 MB
timestamp: 1728928024285, heapUsed: 433.1940460205078 MB
timestamp: 1728928034284, heapUsed: 463.8117370605469 MB
timestamp: 1728928044284, heapUsed: 160.51446533203125 MB
```

### Solution 3: Using unpromise as a static dependency.
Pros: follow current pattern of dependencies ccxt
Cons: does not follow package.json pattern of dependencies
PR: https://github.com/ccxt/ccxt/pull/23988

**Comment by ggecy** [comment]
> Thanks a lot for the detailed report @ggecy !
> 
No problem, thanks for investigating this quickly.
