### ISSUE TITLE
Bitget watch_orders for all symbols (PHP)

### ISSUE THREAD

**Issue by indigoram89** [ccxt/ccxt#23976]
### Operating System

MacOS

### Programming Languages

PHP

### CCXT Version

4.4.17

### Description

BitGet docs says that we can subscribe on user orders with instId=default parameter which means we want to listen user orders for all pairs.

Screenshot:
![CleanShot 2024-10-13 at 18 15 22@2x](https://github.com/user-attachments/assets/66291939-c697-4027-9e64-e96a56ce5506)

Link: https://www.bitget.com/api-doc/common/websocket-intro#subscribe

When I try to do it with CCXT, I get error something like "Bitget does not have $market $symbol default".

But If i comment CCXT code to disable this symbol validation and manually pass "default":
![CleanShot 2024-10-13 at 18 20 59@2x](https://github.com/user-attachments/assets/5cc79726-1c61-48b8-bfa0-359f4ed2b27f)

For now I successfully subscribed on this channel (my orders for all pairs):
![CleanShot 2024-10-13 at 18 22 54@2x](https://github.com/user-attachments/assets/e8accbdf-60c7-4bd7-a9fd-0c683eff6735)

Also I made an order on bitget and got websockets event for this new order:
![CleanShot 2024-10-13 at 18 24 34@2x](https://github.com/user-attachments/assets/da0fc45e-ecb2-4802-bc8a-9f72ebfe736a)

So we need to have ability to pass symbol=default for bitget or even use this value by default.

### Code

```
use ccxt\pro\bitget;
use function React\Async\await;

$ccxt = new bitget;
$ccxt->apiKey = env('BITGET_API_KEY');
$ccxt->secret = env('BITGET_SECRET');
$ccxt->password = env('BITGET_PASSWORD');

$ccxt->verbose = true;

while (true) {
    // $events = await($ccxt->watch_orders('XRP/USDT'));
    $events = await($ccxt->watch_orders('default'));
    var_dump($events);
}

echo 'ok';
```

**Comment by indigoram89** [comment]
One more thing is I do not get any events from watch_orders using symbol=default, but it has logs from ccxt in verbose mode.

```
// it has log events in any case
$ccxt->verbose = true;

while (true) {
     // it has $events
    $events = await($this->watch('XRP/USDT'));
    // it doesn't have $events
    $events = await($this->watch('default'));

    dump($events);
}
```

I do not know why, but exchange lets us watch user orders for all pairs and it very need us =)

**Comment by indigoram89** [comment]
It looks similar https://github.com/ccxt/ccxt/issues/21444

**Comment by indigoram89** [comment]
Comment this line solves this issue =)

![CleanShot 2024-10-13 at 21 32 17@2x](https://github.com/user-attachments/assets/a50d0aaa-7d8f-46ac-906a-bdfbe180df2c)

**Comment by indigoram89** [comment]
As I see this two changes fix this problem:

1. Comment the exception
![CleanShot 2024-10-13 at 22 17 47@2x](https://github.com/user-attachments/assets/af8b5f8c-3828-426b-9ec3-e0fea965556e)

2. Set $instType to SPOT, because with no symbol it futures now:
![CleanShot 2024-10-13 at 22 18 35@2x](https://github.com/user-attachments/assets/892524ed-0116-4ab2-809a-8b027c2be1b0)

Hope it will help to understand.

**Comment by carlosmiei** [comment]
Hello @indigoram89, thanks for reporting it, we will take a look.

**Comment by carlosmiei** [comment]
@indigoram89 Can you please upgrade your ccxt version and try again? it should be working now

**Comment by indigoram89** [comment]
@carlosmiei it works now, thank you very much!!

**Comment by carlosmiei** [comment]
@indigoram89 Np, just let us know if anything! 🙏
