### ISSUE TITLE
Hyperliquid - Order status not correct

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#23998]
### Operating System

N/A

### Programming Languages

Python

### CCXT Version

4.4.16

### Description

Hello,

The status reported by hyperliquid fetch_order is not always correct:

```
print((await e.fetch_order('41937919369'))['status'])
marginCanceled
```

According to the docs (and the solutions using ccxt), I think this status should be `canceled` . 

(Note that this order got partially canceled because of insufficient margin (related to #23997), it did not get fully rejected.)

**Comment by sc0Vu** [comment]
@gaardiolor Thanks, will fix this asap.
