### ISSUE TITLE
process.version.match property '0' of null

### ISSUE THREAD

**Issue by o-matsuo** [ccxt/ccxt#2400]
- OS: mac osx sierra
- Programming Language version: node.js v9.9.0 ES6 JavaScript
- CCXT version: 1.12.36

i use webpack + javascript(ES6) + Babel.
after webpack build , i run bundle.js . error occured

------------------------------------------------------------------
webpack-internal:///../node_modules/ccxt/js/base/Exchange.js:156
            this.nodeVersion = process.version.match (/\d+\.\d+.\d+/)[0]
                                                                     ^

TypeError: Cannot read property '0' of null
    at new Exchange (webpack-internal:///../node_modules/ccxt/js/base/Exchange.js:156:70)
    at new bitflyer (webpack-internal:///../node_modules/ccxt/js/bitflyer.js:10:18)
------------------------------------------------------------------

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/issues/1916
- https://github.com/ccxt/ccxt/issues/606
Let us know if the above does not answer your question.
