### ISSUE TITLE
Incorrect price and average Calculation for Market Orders on HTX Exchange in parse_order

### ISSUE THREAD

**Issue by Lorca-R** [ccxt/ccxt#24024]
### Operating System

ubuntu

### Programming Languages

PHP

### CCXT Version

4.2.92

### Description

**Description:**
The `parse_order` method does not correctly reflect partial fills for market orders on HTX (Huobi). In cases where a 
 buy market order is partially filled, the method incorrectly calculates the `cost`, `price`, and `average`.

**Example:**
In the code section it is an example of the result of `parse_order` for a partially filled buy market order.

**Problem:**
The current `parse_order` method results in inaccurate `cost`, `price` and `average`.

**Suggested Cause:**
HTX returns a price of 0 for market orders, which leads to calculating the `price` and `average` in `safe_order` with `filled` and `cost`.
But [following logic](https://github.com/ccxt/ccxt/blob/1d18cec977f4c20390e8b8cc3fb55aef3b0c0cad/php/htx.php#L4970)  in parse_order incorrectly calculating the cost:

```php
if (($type !== null) && (mb_strpos($type, 'market') !== false)) {
    // for $market orders $amount is in quote currency, meaning it is the $cost
    if ($side === 'sell') {
        $cost = $this->safe_string($order, 'field-cash-amount');
    } else {
        $cost = $this->safe_string($order, 'amount');
    }
}
```
In this case, for a buy market order, `amount` is used to calculate the `cost`, even though the `field-cash-amount` should be used to represent the true cost of the partial fill.

**Proposed Solution:**
Always using `field-cash-amount` as cost in HTX market orders.

This project has been incredibly helpful, and I truly appreciate your effort in maintaining it. Thank you.

### Code

```
  [
    "info" => [
      "id" => "XXXXXXX",
      "symbol" => "slerfusdt",
      "account-id" => "XXXXXXX",
      "client-order-id" => "XXXXXXXX",
      "amount" => "1494.8",
      "market-amount" => "0",
      "ice-amount" => "0",
      "is-ice" => false,
      "price" => "0",
      "created-at" => "1729260739570",
      "type" => "buy-market",
      "field-amount" => "4131.9039",
      "field-cash-amount" => "844.80533188",
      "field-fees" => "3.71871351",
      "finished-at" => "1729260739864",
      "updated-at" => "1729260739864",
      "source" => "spot-api",
      "state" => "partial-canceled",
      "canceled-at" => "1729260739574",
      "canceled-source" => "410",
      "canceled-source-desc" => "Market order circuit-breaker",
    ],
    "id" => "XXXXXXX",
    "clientOrderId" => "XXXXXXXXXXXX",
    "timestamp" => 1729260739570,
    "datetime" => "2024-10-18T14:12:19.570Z",
    "lastTradeTimestamp" => null,
    "symbol" => "SLERF/USDT",
    "type" => "market",
    "timeInForce" => "IOC",
    "postOnly" => null,
    "side" => "buy",
    "price" => 0.36177027253707,
    "stopPrice" => null,
    "triggerPrice" => null,
    "average" => 0.36177027253707,
    "cost" => 1494.8,
    "amount" => null,
    "filled" => 4131.9039,
    "remaining" => null,
    "status" => "canceled",
    "reduceOnly" => null,
    "fee" => [
      "cost" => "3.71871351",
      "currency" => "SLERF",
    ],
    "trades" => [],
    "fees" => [
      [
        "cost" => 3.71871351,
        "currency" => "SLERF",
      ],
    ],
    "lastUpdateTimestamp" => null,
    "takeProfitPrice" => null,
    "stopLossPrice" => null,
  ]
```

**Comment by sc0Vu** [comment]
@Lorca-R Thanks for the report, I'll take a look.

BTW, I wonder whether the partial filled `$cost = $this->safe_string($order, 'field-cash-amount')` works for swap pairs.

**Comment by Lorca-R** [comment]
Indeed. I have only tested it in the spot market. It needs further testing in other markets to ensure nothing breaks.
