### ISSUE TITLE
Mexc 'until' parameter with fetchtrades

### ISSUE THREAD

**Issue by GuilleSisasGlobal** [ccxt/ccxt#24023]
### Operating System

Windows 11

### Programming Languages

Python

### CCXT Version

4.4.20

### Description

Trying on MEXC to fetch historical trades data with the .fetch_trades method between two specific dates. Here is the code:
while start_timestamp < end_timestamp:
    trades = exchange.fetch_trades(symbol, since = start_timestamp, limit=1000, params={})
    if len(trades) == 0:
        break
Gives me an error message:
ccxt.base.errors.ArgumentsRequired: mexc fetchTrades() requires an until parameter when since is provided

Which is strange because the until parameter does not exist in the ccxt library. Is this a bug or am I doing something wrong?

### Code

```
  while start_timestamp < end_timestamp:
    trades = exchange.fetch_trades(symbol, since = start_timestamp, limit=1000, params={})
    if len(trades) == 0:
        break

```

**Comment by rayBastard** [comment]
Hello! Until is an extra parameter specific to the exchange API endpoint. If since is provided, you should add until parameter to params.

```
while start_timestamp < end_timestamp:
    trades = exchange.fetch_trades(symbol, since = start_timestamp, limit=1000, params={until = end_timestamp})
    if len(trades) == 0:
        break
       ```

**Comment by GuilleSisasGlobal** [comment]
Thank you very much, but it doesn't work, as it keeps giving me the same error message. The "until" extra parameter simply cannot be used at all it seems, even inside the parameter brackets.

**Comment by carlosmiei** [comment]
@GuilleSisasGlobal What's your ccxt version? 

As you can see, i tested it with `until` and seems to be working, example

```
 p mexc fetchMyTrades "ATLAS/USDT" 1727693417000  100 '{"until":1727783452000}' 
Python v3.11.9
CCXT v4.4.25
mexc.fetchMyTrades(ATLAS/USDT,1727693417000,100,{'until': 1727783452000})
[{'amount': 1000.0,
  'cost': 3.407,
  'datetime': '2024-10-01T11:48:16.000Z',
  'fee': {'cost': 0.0006814, 'currency': 'USDT'},
  'fees': [{'cost': 0.0006814, 'currency': 'USDT'}],
  'id': '469766492364255232X1',
  'info': {'clientOrderId': None,
           'commission': '0.0006814',
           'commissionAsset': 'USDT',
           'id': '469766492364255232X1',
           'isBestMatch': True,
           'isBuyer': True,
           'isMaker': False,
           'isSelfTrade': False,
           'orderId': 'C02__469766492364255232043',
           'orderListId': '-1',
           'price': '0.003407',
           'qty': '1000',
           'quoteQty': '3.407',
           'symbol': 'ATLASUSDT',
           'time': '1727783296000'},
  'order': 'C02__469766492364255232043',
  'price': 0.003407,
  'side': 'buy',
  'symbol': 'ATLAS/USDT',
  'takerOrMaker': 'taker',
  'timestamp': 1727783296000,
```

**Comment by rayBastard** [comment]
Perhaps it's my fault and I didn't explain clearly. Of course until is an object parameter and you must enter it like this 
``` 
exchange.fetch_trades(symbol, since = start_timestamp, limit=1000, params={'until': end_timestamp})
```

**Comment by rayBastard** [comment]
Perhaps it's my fault and I didn't explain clearly. Of course until is an object parameter and you must enter it like this

``` 
trades = exchange.fetch_trades(symbol, since = start_timestamp, limit=1000, params={'until': end_timestamp})
```

Here is the example

https://github.com/ccxt/ccxt/blob/master/examples/py/binance-fetch-all-my-trades.py

**Comment by GuilleSisasGlobal** [comment]
Hi Ray and Carlos, thanks for your replies (and sorry for my late response, I have been traveling quite a bit), but there is a small difference : I am talking about fetch_trades, not fetch_my_trades. With fetch_trades, it doesn´t seem to be working, and that is the problem. And the example Ray gave in the link is with fetch_my_trades, as well as the code used by Carlos.
It looks like we have stumbled upon an interesting issue!

**Comment by rayBastard** [comment]
Hi @GuilleSisasGlobal 

Thanks for your response. No need to apologize. I see, let me check it again with fetch_trades method.

**Comment by rayBastard** [comment]
Hi @GuilleSisasGlobal 

I think I found the problem, can you post the code you are using again?
