### ISSUE TITLE
Hyperliquid - fetch_positions unrealizedPnl not correct when shorting

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#24044]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.4.20

### Description

Hello,

Hyperliquid returns the opposite unrealizedPnl for short positions. So when shorting, unrealizedPnl is negative if there's profit. Take the following short position for example (ignore 'side', it's wrong, might be fixed in #24034):

```
{
  "info": {
    "type": "oneWay",
    "position": {
      "coin": "BTC",
      "szi": "-0.00067",
      "leverage": {
        "type": "isolated",
        "value": "2",
        "rawUsd": "68.62046"
      },
      "entryPx": "68295.0",
      "positionValue": "45.83604",
      "unrealizedPnl": "-0.07839",
      "returnOnEquity": "-0.00342631",
      "liquidationPx": "101404.55209103",
      "marginUsed": "22.78442",
      "maxLeverage": "50",
      "cumFunding": {
        "allTime": "0.000156",
        "sinceOpen": "0.0",
        "sinceChange": "0.0"
      }
    }
  },
  "id": "None",
  "symbol": "BTC/USDC:USDC",
  "timestamp": "None",
  "datetime": "None",
  "isolated": true,
  "hedged": "None",
  "side": "long",
  "contracts": 0.00067,
  "contractSize": 1.0,
  "entryPrice": 68295.0,
  "markPrice": "None",
  "notional": 45.83604,
  "leverage": 2.0,
  "collateral": 22.78442,
  "initialMargin": 22.78442,
  "maintenanceMargin": "None",
  "initialMarginPercentage": "None",
  "maintenanceMarginPercentage": "None",
  "unrealizedPnl": -0.07839,
  "liquidationPrice": 101404.55209103,
  "marginMode": "isolated",
  "percentage": -0.34405089091581
}
```

The total position value (notional) is 45.83604 
However contracts * entryPrice + unrealizedPnl = 0.00067 * 68295.0 + -0.07839 = 45.67926 , this does not match
Whereas contracts * entryPrice + - unrealizedPnl = 0.00067 * 68295.0 + 0.07839 = 45.83604 , this matches

(I've tested this with >1000 logged fetch_position outputs, both long and short)

So [here](https://github.com/ccxt/ccxt/blob/6208227eacb12a7b4d333c73cf67151ecb74c78f/python/ccxt/async_support/hyperliquid.py#L2121)  `unrealizedPnl = self.safe_number(entry, 'unrealizedPnl')` should be changed to something like `unrealizedPnl = self.safe_number(entry, 'unrealizedPnl') if side == long else -self.safe_number(entry, 'unrealizedPnl')`

Enhancement:
Additionally, can the markPrice value be populated? Should be: position['MarkPrice'] = position['notional'] / (position['contracts'] * position['contractSize']) 

(contractSize is always 1 in hyperliquid, but like this it's more futureproof)

thanks!

**Comment by carlosmiei** [comment]
Hello @gaardiolor, regarding the `notional` value, we're reading it directly from the API and not computing it ourselves.

I will apply your suggestion to fix the unrealizedPnl, thanks for reporting it.

Regarding the `markPrice` I'm not sure... seems a bit risky to infer it like that. Do you need it to support Hyperliquid at freqTrade?

**Comment by carlosmiei** [comment]
@gaardiolor  Hum I was testing the `unrealizedPnl` thing now and I'm not so sure anymore 
![image](https://github.com/user-attachments/assets/a0e19b06-85a0-4a3b-8810-38bb3024cd0c)

```
        coin: 'DOGE',
        szi: '-100.0',
        leverage: { type: 'cross', value: '20' },
        entryPx: '0.13876',
        positionValue: '13.869',
        unrealizedPnl: '0.007',
        returnOnEquity: '0.01008936',
        liquidationPx: '0.33316764',
        marginUsed: '0.69345',
        maxLeverage: '20',
        cumFunding: { allTime: '0.008552', sinceOpen: '0.0', sinceChange: '0.0' }
```

I'm "profiting" on a short position and the value is positive

**Comment by carlosmiei** [comment]
![image](https://github.com/user-attachments/assets/4db9ea0a-4365-4d32-8620-2476e5d2117b)

```
        coin: 'DOGE',
        szi: '-100.0',
        leverage: { type: 'cross', value: '20' },
        entryPx: '0.13876',
        positionValue: '13.88',
        unrealizedPnl: '-0.004',
        returnOnEquity: '-0.00576535',
        liquidationPx: '0.33316764',
        marginUsed: '0.694',
        maxLeverage: '20',
        cumFunding: { allTime: '0.008552', sinceOpen: '0.0', sinceChange: '0.0' }
```

And when I'm losing I the value is negative

**Comment by gaardiolor** [comment]
Hm yes.. you're right. I got it wrong, and I tested it the wrong way around as well. I should have inverted the negative unrealizedPnl myself so it would be added to the position size, because when shorting an increased position size means it's losing. 

It seems the unrealizedPnl was fine. Can you revert this one? Sorry..

> Regarding the markPrice I'm not sure... seems a bit risky to infer it like that. Do you need it to support Hyperliquid at freqTrade?

No it's ok. I thought I needed it, but it turns out I don't.

**Comment by carlosmiei** [comment]
@gaardiolor I kept the same logic for the unrealizedPNL so it should be ok.

The contracts type should also be ok now and we already released a new version with the fix.


I will close this issue now,  but please let us know if anything! Thank you.
