### ISSUE TITLE
Binance error: Timestamp for this request was 1000ms ahead of the server's time. 

### ISSUE THREAD

**Issue by EMADSHAK** [ccxt/ccxt#2405]
I get this error while using Binance:

binance.exceptions.BinanceAPIException: APIError(code=-1021): Timestamp for this request was 1000ms ahead of the server's time.

how can i solve this problem? I'v already checked my system time.

- OS:
- Programming Language version: python
- CCXT version:
- Exchange:binance
- Method:

**Comment by kroitor** [comment]
#850
