### ISSUE TITLE
fetch_tickers cannot retrieve newly listed cryptocurrencies.

### ISSUE THREAD

**Issue by gochendong** [ccxt/ccxt#24052]
### Programming Languages

Python

### CCXT Version

4.4.21

### Description

**fetch_tickers** cannot retrieve newly listed cryptocurrencies.
I believe this issue has always existed, and it requires restarting the program to retrieve newly listed cryptocurrencies.

**Comment by sc0Vu** [comment]
@gochendong Which exchange did you use? I’m wondering if it’s an issue in CCXT, since the data comes directly from the exchange.

**Comment by gochendong** [comment]
II use Binance, but I don't think that this issue is related to the exchange. I noticed this problem many months ago: before the program restarts, `fetch_tickers` cannot retrieve the newly listed trading pairs. I wonder if this is due to some local caching.

**Comment by gochendong** [comment]
> @gochendong Which exchange did you use? I’m wondering if it’s an issue in CCXT, since the data comes directly from the exchange.
I use Binance, but I don't think that this issue is related to the exchange. I noticed this problem many months ago: before the program restarts, fetch_tickers cannot retrieve the newly listed trading pairs. I wonder if this is due to some local caching.

**Comment by carlosmiei** [comment]
Hello @gochendong if new markets were opened after you loaded the markets initially CCXT won't have them in the cache, you can however call `load_markets(True)` periodically to ensure everything is always up to date.
