### ISSUE TITLE
fetchMyTrades cryptocom paginate: true throws an Error

### ISSUE THREAD

**Issue by fl0wo** [ccxt/ccxt#24061]
### Operating System

MacOs/Linux

### Programming Languages

JavaScript

### CCXT Version

4.4.10

### Description

When fetching my trades using cryptocom and paginate: true feature on I get the following error:

BadRequest: cryptocom 
{
    "id": 1729616878264,
    "method": "private/get-trades",
    "code": 40003,
    "message": "Invalid limit"
}

It should be related to this:
https://exchange-docs.crypto.com/exchange/v1/rest-ws/index.html#private-get-trades

Anything I can do to help?

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @fl0wo,

Thanks for reporting it, we will take a look and get back to you.

**Comment by carlosmiei** [comment]
@fl0wo Can you please upgrade your ccxt version and try again? It should be working now
