### ISSUE TITLE
decimalToPrecision: drops the last digit on numbers without dot

### ISSUE THREAD

**Issue by mkutny** [ccxt/ccxt#2406]
- Programming Language version: node 9.9.0
- CCXT version: 1.12.44
- Method: decimalToPrecision

When the dot is present then it behaves as expected. Without the dot it simply drops the last digit.

```
> const ccxt = require('./ccxt')
undefined
> ccxt.decimalToPrecision('1', ccxt.TRUNCATE, 0)
'0'
> ccxt.decimalToPrecision('12', ccxt.TRUNCATE, 0)
'1'
> ccxt.decimalToPrecision('123', ccxt.TRUNCATE, 0)
'12'
```

**Comment by xpl** [comment]
Hold on, the fix is coming.

**Comment by mkutny** [comment]
Also, what do you think of renaming `AFTER_DOT` to `DECIMAL_PLACES`?

`DECIMAL_PLACES` seems to be like an established term for the precision mode.

**Comment by kroitor** [comment]
I'd agree for `DECIMAL_PLACES` )

**Comment by xpl** [comment]
@mkutny Fixed, renamed.

**Comment by mkutny** [comment]
@xpl , cool, thanks!
