### ISSUE TITLE
decimalToPrecision: rounding for equidistant digits

### ISSUE THREAD

**Issue by mkutny** [ccxt/ccxt#2407]
- Programming Language version: node 9.9.0
- CCXT version: 1.12.46
- Method: decimalToPrecision

It's not explicitly stated but I assume that the rounding mode is "To the nearest neighbor. If equidistant round away from zero", so `1.5` should round up to `2`.

```
> const ccxt = require('./ccxt')
undefined
> ccxt.decimalToPrecision('1.5', ccxt.ROUND, 0)
'1'
> ccxt.decimalToPrecision('1.55', ccxt.ROUND, 0)
'1'
> ccxt.decimalToPrecision('1.56', ccxt.ROUND, 0)
'2'
```

**Comment by xpl** [comment]
@mkutny Should work as expected now:

```javascript
it ('decimalToPrecision: rounding for equidistant digits', () => {

    equal (decimalToPrecision ('12.54', ROUND, 1, DECIMAL_PLACES), '12.5')
    equal (decimalToPrecision ('12.55', ROUND, 1, DECIMAL_PLACES), '12.6')
})
```

**Comment by mkutny** [comment]
Hmm...
It's mostly fixed but how about the following:
```
> ccxt.decimalToPrecision('1.45', ccxt.ROUND, 0)
'2'
```
`1.45` is closer to `1` than to `2`, shouldn't it be rounded down?

**Comment by xpl** [comment]
@mkutny Yep, that's definitely a bug and it was introduced by that equidistant digits fix. Working on it.

**Comment by xpl** [comment]
@mkutny uploaded a fix + a test case for that:

```javascript
    equal (decimalToPrecision ('1.45', ROUND, 0, DECIMAL_PLACES), '1')
```

**Comment by mkutny** [comment]
Great, thanks!
