### ISSUE TITLE
Bitmart Opening an Order with TP and SL

### ISSUE THREAD

**Issue by 3ntr0phy** [ccxt/ccxt#24087]
### Operating System

Linux

### Programming Languages

Python

### CCXT Version

latest

### Description

Hi,
I am trying to create a limit order on bitmart but if the order is a long order I get `Position does not exist` and if I do try to short it I get that `The stop loss price is invalid, needs to be lesser than the order price` .
I tried also to change the `plan_category` but I get `Invalid Type` when I use an `int`
Can you please show me how to create an order with TP and SL on Bitmart?
Thanks

### Code

```
  bitmart.create_order(symbol=symbol,
                                            type='limit',
                                            side=direction,
                                            amount=size,
                                            price=float(entry_price),
                                            params={
                                            'takeProfitPrice': str(tp),
                                            'stopLossPrice': str(sl),
                                            })

```

**Comment by batu3H** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Dan-krm** [comment]
Hi @3ntr0phy on bitmart the `stopLossPrice` and `takeProfitPrice` are trigger prices and the execution price is the `price` argument. These are `reduceOnly` orders that require a position before creating and only one of `stopLossPrice` and `takeProfitPrice` should be defined at a time.

You can learn more about placing different orders on CCXT in this section of the documentation:
https://docs.ccxt.com/#/?id=placing-orders

Here is an example of a stopLossPrice order with the execution price lower than the stopLossPrice:
```
bitmart.create_order(BTC/USDT:USDT, limit, sell, 1, 50000, params={'stopLossPrice': 51000})

{
  id: '3000022583002749',
  clientOrderId: undefined,
  info: { order_id: '3000022583002749', client_order_id: '' },
  timestamp: undefined,
  datetime: undefined,
  lastTradeTimestamp: undefined,
  symbol: 'BTC/USDT:USDT',
  type: 'limit',
  timeInForce: undefined,
  postOnly: undefined,
  side: 'sell',
  price: 50000,
  stopPrice: undefined,
  triggerPrice: undefined,
  amount: 1,
  cost: undefined,
  average: undefined,
  filled: undefined,
  remaining: undefined,
  status: undefined,
  fee: undefined,
  trades: [],
  fees: [],
  lastUpdateTimestamp: undefined,
  reduceOnly: undefined,
  takeProfitPrice: undefined,
  stopLossPrice: undefined
}
```

stopLossPrice and takeProfitPrice orders follow this logic below, so closing a long will require you to set the side to `sell` and closing a short will require you to set the side to `buy`:
```javascript
if (isStopLoss || isTakeProfit) {
    reduceOnly = true;
    request['price_type'] = this.safeInteger (params, 'price_type', 1);
    request['executive_price'] = this.priceToPrecision (symbol, price);
    if (isStopLoss) {
        request['trigger_price'] = this.priceToPrecision (symbol, stopLossPrice);
    } else {
        request['trigger_price'] = this.priceToPrecision (symbol, takeProfitPrice);
    }
} else {
    request['open_type'] = marginMode;
}
if (side === 'buy') {
    if (reduceOnly) {
        request['side'] = 2; // buy close short
    } else {
        request['side'] = 1; // buy open long
    }
} else if (side === 'sell') {
    if (reduceOnly) {
        request['side'] = 3; // sell close long
    } else {
        request['side'] = 4; // sell open short
    }
}
```

Let me know if you have any other questions!

**Comment by Dan-krm** [comment]
@3ntr0phy closing this issue for now, let me know if you have any other problems
