### ISSUE TITLE
Kucoin syntax error (PHP)

### ISSUE THREAD

**Issue by indigoram89** [ccxt/ccxt#24090]
### Operating System

MacOS

### Programming Languages

PHP

### CCXT Version

4.4.23

### Description

Hello! $this->myTrades.append($parsed) must be $this->myTrades->append($parsed) in \ccxt\pro\kucion.php line 1227.

![CleanShot 2024-10-26 at 11 37 14@2x](https://github.com/user-attachments/assets/679f88b2-c965-4552-b4ca-56e45844821b)

### Code

```
  

```

**Comment by indigoram89** [comment]
arrow (->) instead dot (.)

**Comment by carlosmiei** [comment]
Hello @indigoram89, you're right, thanks for reporting it!

We will fix it asap.

**Comment by carlosmiei** [comment]
Hello @indigoram89, we just released a version with the fix, can you please upgrade and try again?

**Comment by indigoram89** [comment]
It is ok now, thank you!

**Comment by batu3H** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
