### ISSUE TITLE
What are the plans to implement watchOrders on Exmo exchange?

### ISSUE THREAD

**Issue by 89d55d5288** [ccxt/ccxt#24095]
### Operating System

Debian, Windows

### Programming Languages

Python

### CCXT Version

last

### Description

Hello, everyone!

Is there a planned solution to this for EXMO exchange:

‘watchOrders’: False, # TODO

class exmo(ccxt.async_support.exmo):

    def describe(self):
        return self.deep_extend(super(exmo, self).describe(), {
            'has': {
                'ws': True,
                'watchBalance': True,
                'watchTicker': True,
                'watchTickers': True,
                'watchTrades': True,
                'watchMyTrades': True,
                'watchOrders': False,  # TODO
                'watchOrderBook': True,
                'watchOHLCV': False,
            },

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @89d55d5288,

Thanks for bringing our attention to this.

I think it should be possible using this stream: https://documenter.getpostman.com/view/10287440/SzYXWKPi#85f7bc03-b1c9-4cd2-bd22-8fd422272825

We will try to implement it as soon as possible.

**Comment by 89d55d5288** [comment]
@carlosmiei 
thank you
