### ISSUE TITLE
Hyperliquid - adjust rate limit endpoint costs

### ISSUE THREAD

**Issue by krasnyd** [ccxt/ccxt#24100]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.3.80

### Description

Currently, the CCXT implementation for Hyperliquid is configured with rateLimit=50, and the cost for both endpoints is set to 1. 
https://github.com/ccxt/ccxt/blob/90a20363412671683eb49922e624e343b2779abc/python/ccxt/abstract/hyperliquid.py#L4-L6

The problem is, that this does not represent the current rate limits on Hyperliquid. [Their documentation](https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/rate-limits) says:

> REST requests share an aggregated weight limit of 1200 per minute. 
> All documented exchange API requests have a weight of 1. 
> ! The following **info requests have weight 2**: l2Book, allMids, clearinghouseState, orderStatus, spotClearinghouseState, exchangeStatus.
> ! **All other documented info requests have weight 20**.

I think the cost of the `publicPostInfo` should be adjusted accordingly.
I ran into issues while calling the `fetch_ohlcv` function, which is calling the info request `candleSnapshot`. With the current configuration, it is really easy to exceed the request limit.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @krasnyd, thanks for reporting it, we will take a look.
