### ISSUE TITLE
Alpaca missing: fetchL2OrderBook. missing opt: fetchMyTrades, fetchL2OrderBook, fetchTicker, fetchTickers.     

### ISSUE THREAD

**Issue by Immortality-IMT** [ccxt/ccxt#24127]
### Exchange Name

Alpaca

### URL of the Exchange

https://alpaca.markets/

### URL of the Exchange's API docs

https://docs.alpaca.markets/reference/authentication-2

### Why should this exchange be implemented?

The functions fetchL2OrderBook, fetchMyTrades, fetchTicker, and fetchTickers—are not directly available in Alpaca's API.

Here’s a look at what Alpaca offers closest to these functions:

- fetchMyTrades: In Alpaca’s API, you can retrieve your executed trades with:

        get_activities(activity_types='FILL'): This returns a list of trade fills, providing details on each executed trade.

- fetchTicker and fetchTickers: For getting the latest quote and trading data for single or multiple tickers:

        get_last_trade(symbol): Gets the last trade for a specific symbol.
        get_snapshot(symbols): This retrieves snapshots, including price and volume, for multiple tickers if you pass a list of symbols.

- fetchL2OrderBook: Alpaca does not provide Level 2 order book data (bid/ask details beyond top-level prices) through its own API. However, for Level 1 (best bid/ask) data, you can use:

        get_snapshot: For a specific symbol’s quote and last trade.
        get_last_quote: To get the latest quote for a symbol.

ccxt Alpaca has fetchOrderBook and fetchL1OrderBook implemented but not FetchL2Orderbook. I will do some investigation on the differences between those, and come back.

CCXT Alpaca already has fetch_ohlcv implemented. I have tested just tested the fetch_ohlcv function, works fine, can grab full history from it.(https://github.com/ccxt/ccxt/blob/be60a09df3a28b10bf8cf243cd3c940e08d08c46/python/ccxt/alpaca.py#L561C9-L561C20). 

We are working with Freqtrade here. freqtrade list-exchanges --all will show you what's missing.

│ Alpaca                 │ alpaca                          │ spot                   │ missing: fetchL2OrderBook. missing opt:               │
│                        │                                 │                        │ fetchMyTrades, fetchL2OrderBook, fetchTicker,         │
│                        │                                 │                        │ fetchTickers. 

Optional things are not necessarily required (but will limit certain functionalities) - but either fetchL2OrderBook or fetchTicker are a must (that's what seems to be missing).

Can we get the necessary things implemented?

**Comment by carlosmiei** [comment]
Hello @Immortality-IMT,

Thanks for bringing our attention to this, we will check if those can be implemented.

**Comment by Immortality-IMT** [comment]
I have opened the issue with Alpaca API,  the thread: https://github.com/alpacahq/alpaca-py/issues/521

**Comment by Dan-krm** [comment]
@Immortality-IMT

I've added support for fetchMyTrades, fetchTicker and fetchTickers

I didn't see any endpoints to support fetchL2OrderBook
