### ISSUE TITLE
Error 100421 with BingX ( createOrder )

### ISSUE THREAD

**Issue by leovergil1808** [ccxt/ccxt#24131]
### Operating System

Ubuntu

### Programming Languages

PHP

### CCXT Version

4.3.87

### Description

I wanted to create swap market order on BingX and got an error:

bingx {"code":100421,"msg":"Null timestamp or timestamp mismatch, try to run our sample code from the link https://bingx-api.github.io/docs/#/en-us/spot/account-api.html#Query%20Assets","timestamp":1730380897367}

![image](https://github.com/user-attachments/assets/b5b2cf9f-f5f1-4dae-bc8c-6d440c63233c)

How to solve this problem?

### Code

```
$controller = new \ccxt\bingx();
$controller->apiKey = API_KEY;
$controller->secret = SECRET;
$options = [
	'takeProfit' => 80000,
	'stoploss' => 65000,
];
$response = $controller->createOrder('BTC/USDT:USDT', 'MARKET', 'buy', '0.001', null, $options);
```

**Comment by sc0Vu** [comment]
@leovergil1808 Hi, I think the time wasn't correct. Can you sync it with ntp server?

**Comment by leovergil1808** [comment]
> @leovergil1808 Hi, I think the time wasn't correct. Can you sync it with ntp server?

I tried sync it with npt server by the following steps:
sudo apt install ntpdate -y
sudo ntpdate time.google.com

It's work for me thank you.
