### ISSUE TITLE
Error Bibox create_order()

### ISSUE THREAD

**Issue by calbertuk** [ccxt/ccxt#2414]
I get an error trying to place an order, it says: 
"接口不支持apikey请求方式" which translates to "Interface does not support apikey request"

I have the right permissions so don't really understand what's happening, any help would be appreciated?

**Comment by kroitor** [comment]
@calbertuk can you plz show a snippet of code to reproduce it and your full verbose output (both the request and response without the keys) ? https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by calbertuk** [comment]
Updating to latest version fixed this

**Comment by kroitor** [comment]
@calbertuk thank you for reporting back! Sorry for a long wait...
