### ISSUE TITLE
Hyperliquid fetch_funding_rate_history not honoring limit parameter

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#24144]
### Operating System

n/a

### Programming Languages

Python

### CCXT Version

4.4.25

### Description

Hello,

Hyperliquid gives max 500 hours of funding_rate history:
```
curl -s -X POST https://api.hyperliquid.xyz/info --json '{"type":"fundingHistory","coin":"BTC","interval":"5m","startTime":1672527600000}' | jq | grep coin | wc -l
500
```

However, when not specifying a since, ccxt gives 100:
```
print(len(await e.fetch_funding_rate_history('BTC/USDC:USDC')))
100
```

Also when specifying limit 500:
```
print(len(await e.fetch_funding_rate_history('BTC/USDC:USDC', limit=500)))
100
```

That's because [here](https://github.com/ccxt/ccxt/blob/7ed1e2d338d58392faf5ac0693b9491804714b0a/python/ccxt/async_support/hyperliquid.py#L1544), ccxt is setting the starttime to 100 hours in the past. Idea to set that to 500?

**Comment by carlosmiei** [comment]
Hello @gaardiolor, thanks for bringing our attention to this. Will take a look asap.

**Comment by carlosmiei** [comment]
@gaardiolor Can you please upgrade your ccxt version and try again? it should be working now

**Comment by gaardiolor** [comment]
yes, works! Thanks!
