### ISSUE TITLE
lbank temparary errors are not handled properly?

### ISSUE THREAD

**Issue by vyahnov** [ccxt/ccxt#24160]
### Operating System

Ubuntu 20.04.6

### Programming Languages

JavaScript

### CCXT Version

4.4.26

### Description

I am using watchOrders and watchOrderBook, both are wrapped in try/catch

But when connection is closed by remote server (closing code 1000), this exception is raised:

Error: WebSocket is not open: readyState 2 (CLOSING)
    at sendAfterClose (/home/apollo/gungnir/node_modules/ws/lib/websocket.js:1134:17)
    at WebSocket.send (/home/apollo/gungnir/node_modules/ws/lib/websocket.js:461:7)
    at WsClient.send (/home/apollo/gungnir/node_modules/ccxt/dist/cjs/src/base/ws/Client.js:281:29)
    at lbank.handlePing (/home/apollo/gungnir/node_modules/ccxt/dist/cjs/src/pro/lbank.js:811:22)
    at Timeout._onTimeout (/home/apollo/gungnir/node_modules/ccxt/dist/cjs/src/base/Exchange.js:859:20)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)

### Code

Typical log:

2024-11-03T22:22:30.304Z onMessage { ping: '789e2d30-407b-4639-ad14-329794f2126e', action: 'ping' }
2024-11-03T22:22:30.305Z sending { action: 'pong', pong: '789e2d30-407b-4639-ad14-329794f2126e' }
2024-11-03T22:22:30.305Z onClose CloseEvent {
  [Symbol(kTarget)]: <ref *1> WebSocket {
    _events: [Object: null prototype] {
      open: [Function],
      message: [Function],
      error: [Function],
      close: [Function],
      ping: [Function: bound onPing],
      pong: [Function: bound onPong],
      upgrade: [Function: bound onUpgrade]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1000,
    _closeFrameReceived: true,
    _closeFrameSent: true,
    _closeMessage: <Buffer >,
    _closeTimer: Timeout {
      _idleTimeout: -1,
      _idlePrev: null,
      _idleNext: null,
      _idleStart: 2628113,
      _onTimeout: null,
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: true,
      [Symbol(refed)]: true,
      [Symbol(kHasPrimitive)]: false,
      [Symbol(asyncId)]: 28495,
      [Symbol(triggerId)]: 8849,
      [Symbol(kAsyncContextFrame)]: undefined
    },
    _errorEmitted: false,
    _extensions: {},
    _paused: false,
    _protocol: '',
    _readyState: 3,
    _receiver: Receiver {
      _events: [Object: null prototype] {},
      _writableState: [WritableState],
      _maxListeners: undefined,
      _allowSynchronousEvents: true,
      _binaryType: 'nodebuffer',
      _extensions: {},
      _isServer: false,
      _maxPayload: 104857600,
      _skipUTF8Validation: false,
      _bufferedBytes: 0,
      _buffers: [],
      _compressed: false,
      _payloadLength: 2,
      _mask: undefined,
      _fragmented: 0,
      _masked: false,
      _fin: true,
      _opcode: 8,
      _totalPayloadLength: 0,
      _messageLength: 0,
      _fragments: [],
      _errored: false,
      _loop: false,
      _state: 0,
      _eventsCount: 0,
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(websocket)]: [Circular *1]
    },
    _sender: Sender {
      _extensions: {},
      _socket: [TLSSocket],
      _firstFragment: true,
      _compress: false,
      _bufferedBytes: 63,
      _queue: [],
      _state: 0,
      onerror: [Function: senderOnError],
      [Symbol(websocket)]: [Circular *1]
    },
    _socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'www.lbkex.net',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 6,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'www.lbkex.net',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _writableState: [WritableState],
      allowHalfOpen: false,
      _maxListeners: undefined,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: null,
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: null,
      timeout: 0,
      write: [Function: writeAfterFIN],
      [Symbol(alpncallback)]: null,
      [Symbol(res)]: null,
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 8849,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: true,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 2202840,
      [Symbol(kBytesWritten)]: 2910,
      [Symbol(connect-options)]: [Object],
      [Symbol(websocket)]: undefined
    },
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _autoPong: true,
    _url: 'wss://www.lbkex.net/ws/V2/',
    _req: null,
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false
  },
  [Symbol(kType)]: 'close',
  [Symbol(kCode)]: **1000**,
  [Symbol(kReason)]: '',
  [Symbol(kWasClean)]: true
}
Error: WebSocket is not open: readyState 2 (CLOSING)
    at sendAfterClose (/home/apollo/gungnir/node_modules/ws/lib/websocket.js:1134:17)
    at WebSocket.send (/home/apollo/gungnir/node_modules/ws/lib/websocket.js:461:7)
    at WsClient.send (/home/apollo/gungnir/node_modules/ccxt/dist/cjs/src/base/ws/Client.js:281:29)
    at lbank.handlePing (/home/apollo/gungnir/node_modules/ccxt/dist/cjs/src/pro/lbank.js:813:22)
    at Timeout._onTimeout (/home/apollo/gungnir/node_modules/ccxt/dist/cjs/src/base/Exchange.js:859:20)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
[22:22:30.08]       watchOrders failed: connection closed by remote server, closing code 1000

**Comment by sc0Vu** [comment]
@vyahnov Thanks, we'll fix this asap.
