### ISSUE TITLE
fetchOHLCV different behavior between exchanges.

### ISSUE THREAD

**Issue by jeffryhartanto** [ccxt/ccxt#2416]
- OS: Windows 10
- Programming Language version: Javascrip
- CCXT version: 1.12.50
- Exchange: Binance, Bittrex, Bitfinex
- Method: fetchOHLCV

I want to fetch the last 15 minutes of data from the exchanges, like below:
```
    let currentDatetime = Date.now()
    let lessDatetime = 15 * 60 * 1000 //15 minutes
    let pastDatetime = currentDatetime - lessDatetime

    let symbol = 'SNT/ETH'
    let tickers = await exchange.fetchOHLCV(symbol, '1m', pastDatetime, 100);
```
If I use binance as the exchange, it returns 15 items (which is correct?). However, if I use bittrex and bitfinex it returns 0 and 2, respectively.  Is there anything wrong with my logic? If not, then why are they behaving this way?

**Comment by MaticConradi** [comment]
Some exchanges behave a bit weird. I had to do extensive error handling to eliminate corrupted data.

**Comment by kroitor** [comment]
Related: #987
