### ISSUE TITLE
Smart-contract adresses

### ISSUE THREAD

**Issue by Ilya243543** [ccxt/ccxt#24174]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.3.50

### Description

Hi everyone, 
I want to get smart-contracts adresses, for example "0x8062AbC286f5e7D9428a0Ccb9AbD71e50d93b935". How can I do it?

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @Ilya243543

Unfortunately, that information is not provided in most exchanges. If they do offer it, you can access it inside `market->info`, but as I said, that's rarely available.

**Comment by Ilya243543** [comment]
> Hello @Ilya243543
> 
> Unfortunately, that information is not provided in most exchanges. If they do offer it, you can access it inside `market->info`, but as I said, that's rarely available.

Ok, thank you,
So how can I differentiate between coins, because some exchanges have coins with the same tickers, e.g. "FUD" on Bitget and "FUD" on Huobi are different coins?

**Comment by carlosmiei** [comment]
@Ilya243543 That might not be easy. I would try to use the price; if the price is similar, then most likely it is the same coin. Alternatively you can manually go to the WEB UI and check if the coin is the same, usually they provide some info about the project there.
