### ISSUE TITLE
Bitvavo editOrderWs deadlock

### ISSUE THREAD

**Issue by apollace** [ccxt/ccxt#24188]
### Operating System

Debian 12

### Programming Languages

JavaScript

### CCXT Version

4.4.27

### Description

Calling multiple times editOrderWs reliably generates a deadlock.

I tried to debug but I did not really understood the reason behind the deadlock. 

Everything looks fine while debugging, the watch function inside looks ok, the state looks ok, there are no pending futures inside the client of the Exchange class but at the end of the watch function the result is a deadlock. 

Can someone help me understanding what is going on?

### Code

```
  (async () => {
    const bitvavo = new ccxt.pro.bitvavo({
        apiKey: apiKey,
        secret: apiSecret,
    });;
    const order = await bitvavo.createOrderWs('GRASS/EUR', 'limit', 'buy', 10, 1);
    await new Promise(resolve => setTimeout(resolve, 2000));
    const editedOrder = await bitvavo.editOrderWs(order.id, 'GRASS/EUR', 'limit', 'buy', 10, 0.98);
    await new Promise(resolve => setTimeout(resolve, 2000));

    // << Here now it will be stuck
    const editedOrder2 = await bitvavo.editOrderWs(editedOrder.id, 'GRASS/EUR', 'limit', 'buy', 10, 0.97); 
    await new Promise(resolve => setTimeout(resolve, 2000));
    await bitvavo.cancelOrderWs(editedOrder2.id, 'GRASS/EUR');
})();

```

**Comment by carlosmiei** [comment]
Hello @apollace,

Thanks for reporting it. We will take a look and get back to you.

**Comment by apollace** [comment]
Hello @carlosmiei, thanks, if you find anything I would be happy to see what was the issue in the PR 👍

**Comment by carlosmiei** [comment]
@apollace Managed to reproduce the issue on my end, working on a fix right now.

**Comment by carlosmiei** [comment]
@apollace can you please upgrade your ccxt version and try again? It should be working as expected now.

**Comment by apollace** [comment]
Thanks I will have a look this afternoon

**Comment by apollace** [comment]
In addition the version 4.4.30 broke the rest API

**Comment by carlosmiei** [comment]
@apollace I will check this, I wasn't aware of the `requestId`, that would make things much easier. 

>  In addition the version 4.4.29 broke the rest API

@apollace Can you elaborate a bit more here please?

**Comment by carlosmiei** [comment]
@apollace I tried adding a requestId/id but as you can see the value is not returned 

```
connecting to wss://ws.bitvavo.com/v2
2024-11-16T10:32:25.227Z onUpgrade
2024-11-16T10:32:25.228Z onOpen
2024-11-16T10:32:25.229Z sending {
  action: 'authenticate',
  key: '6ddbc7adbe112e98db39381e3358779ac735931e170acc65ac56f7d47daebd70',
  signature: '389a1022a455f9de9a44ba2b40c0dbe456e793da43e469eb185317464ca27fc1',
  timestamp: 1731753145027
}
2024-11-16T10:32:25.303Z onMessage { event: 'authenticate', authenticated: true }
2024-11-16T10:32:25.305Z sending {
  market: 'BTC-EUR',
  action: 'privateGetOrdersOpen',
  requestId: '17317531453043618'
}
2024-11-16T10:32:25.377Z onMessage { action: 'privateGetOrdersOpen', response: [] }
2024-11-16T10:32:25.379Z iteration 0 passed in 352 ms

[]
```

**Comment by carlosmiei** [comment]
@apollace Oh Ok it needs to be an int:
```
nMessage { event: 'authenticate', authenticated: true }
2024-11-16T10:34:16.941Z sending {
  market: 'BTC-EUR',
  action: 'privateGetOrdersOpen',
  requestId: 17317532569411208
}
2024-11-16T10:34:17.021Z onMessage {
  action: 'privateGetOrdersOpen',
  requestId: '17317532569411208',
  response: []
}
```

**Comment by carlosmiei** [comment]
@apollace Ok found the issue with the clientorderId as well, going to fix that too

**Comment by apollace** [comment]
@carlosmiei Sorry for the late response, I missed you comments. 
I will test and let you know how it goes. Thanks for the help :) 

I will ask to improve the doc because it doesn't look to be clear enough.

**Comment by carlosmiei** [comment]
@apollace We haven't released yet, but we will do shortly

**Comment by carlosmiei** [comment]
@apollace We just released a new version  4.4.32. Can you please upgrade and try again?

**Comment by apollace** [comment]
@carlosmiei Seems to work, I will let you know if I see more issues

**Comment by apollace** [comment]
@carlosmiei I can confirm that this issue is not present anymore. Thanks for the help!
