### ISSUE TITLE
binance account with portfolioMargin: instantiation and account balancce query issue

### ISSUE THREAD

**Issue by bsauvage1** [ccxt/ccxt#24194]
### Operating System

ubuntu 22.04.5

### Programming Languages

Python

### CCXT Version

4.1.7

### Description

Hello. New to portfolioMargin mode in binance, and I have 2 questions:
1/ when I instantiate the exchange, do I need to specifically add the argument portfolioMargin: True ? As in, how can I properly instantiate an account without knowing whether it's PM mode or not? 
```
ccxt.binance(
                    {
                        "apiKey": keys["api_key"],
                        "secret": keys["api_secret"],
                        "enableRateLimit": True,
                        "options": {
                            "defaultType": "future",
                            "adjustForTimeDifference": True,
                            "portfolioMargin": True  ### this one?
                        },
                        "timeout": 30000,
                    }
                )
```
2/ once instantiated, I try to get the account balance. When in non-PM mode, I used to call method .fapiPrivateV2GetAccount() (or .fetch_balance()). Now, I try with .papiGetAccount() or fetch_balance() and I get an error: 
ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action"}
The key is a new one that's been regenerated since the account has changed mode, is restricted to the correct ip (the exchange instantiates and markets get loaded ok), and has API restrictions: Enable Reading, Enable Spot & Margin Trading, Enable Portfolio Margin Trading. 

What am I doing wrong? 

### Code

```
  

```

**Comment by bsauvage1** [comment]
Hello @carlosmiei  and thank you. I will try and revert. Then, is there a way to know ex-ante whether I should use that option or not when pointing to an account?

**Comment by carlosmiei** [comment]
@bsauvage1 You want to know if there's a way of detecting the account type (normal vs portfolio margin) through the API?

**Comment by bsauvage1** [comment]
> @bsauvage1 You want to know if there's a way of detecting the account type (normal vs portfolio margin) through the API?

yes. 
Also please see my updated comment above, the request doesn't seem to work, points to the fapi endpoint for some reason,

**Comment by bsauvage1** [comment]
@carlosmiei ok will upgrade and retry thank you

**Comment by bsauvage1** [comment]
@carlosmiei I confirm that it works post ccxt lib upgrade. Final question: whether I specify "portfolioMargin": True option or not, I still get the same queries result, so is this not necessary? For example:
```
    exchange = ccxt.binance(
        {
            "apiKey": "xxxxx",
            "secret": "xxxxx",
            "enableRateLimit": True,
            "options": {
                "defaultType": "future",
                "adjustForTimeDifference": True,
                # "portfolioMargin": True  ### this one?
            },
            "timeout": 30000,
        }
    )
    account = exchange.papiGetAccount()
```

**Comment by Dan-krm** [comment]
@bsauvage1 glad that it's working for you
> 
> ```
>     exchange = ccxt.binance(
>         {
>             "apiKey": "xxxxx",
>             "secret": "xxxxx",
>             "enableRateLimit": True,
>             "options": {
>                 "defaultType": "future",
>                 "adjustForTimeDifference": True,
>                 # "portfolioMargin": True  ### this one?
>             },
>             "timeout": 30000,
>         }
>     )
>     account = exchange.papiGetAccount()
> ```

In this example you're calling the endpoint directly so setting portfolioMargin to True is not necessary, you can either call the endpoint directly `papiGetAccount()` or if there is a unified method available you can call it with the portfolioMargin param or option set to true for example when calling `fetchBalance()` it would require you to set portfolioMargin to true for using the portfolio margin endpoint.

I'll close this issue for now, let us know if there is anything else!
