### ISSUE TITLE
Question about the difference between fetchOrderBookWs and watchOrderBook functions

### ISSUE THREAD

**Issue by cozy-hn** [ccxt/ccxt#24191]
### Description

Hello, I noticed that both fetchOrderBookWs and watchOrderBook functions seem to utilize WebSocket to retrieve order book data. However, the specific differences in their purpose or functionality are unclear, and it's a bit confusing.

Could you explain the intended use cases, performance differences, or any other distinctions between these two functions?

Thank you!

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @cozy-hn 

`fetchOrderBookWs` follows the REST request-response model, you request the orderbook and you get it and that's it

`watchOrderBook` is event-based and continuously streams the orderbook every time the exchange broadcasts an update.

**Comment by cozy-hn** [comment]
@carlosmiei 
I have additional questions. I created an instance with `new ccxt.pro.binance()` and although watchOrderBook is said to be an existing method, it says that fetchOrderBookWs doesn't exist even though it's in the Binance folder of pro. Why is that?

I can't see this function in`change.d.ts`, and it seems that some other Binance Pro functions are like that as well.

**Comment by carlosmiei** [comment]
@cozy-hn What's your ccxt version? `fetchOrderBookWs` is available in Binance.

**Comment by cozy-hn** [comment]
@carlosmiei  
ccxt@4.4.26 

I'm using ccxt@4.4.26, and although the `fetchOrderBookWs` method is definitely present in the `binance` file within the `pro` folder, it’s missing in `Exchange.d.ts`, resulting in an error message.

**Comment by carlosmiei** [comment]
@cozy-hn Yeah, the base implementation is probably missing inside `Exchange.ts`, but I will add it shortly.

**Comment by carlosmiei** [comment]
@cozy-hn can you please upgrade and try again? it should be working now
