### ISSUE TITLE
TypeError: can't multiply sequence by non-int of type 'float' in exchange.py

### ISSUE THREAD

**Issue by rwsjsed** [ccxt/ccxt#2419]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Mac 
- Programming Language version: Python
- CCXT version: 1.11.171
- Exchange: Kucoin
- Method: exchange.py

Traceback (most recent call last):
 ...
  File "/usr/local/lib/python3.5/dist-packages/ccxt/kucoin.py", line 525, in create_order
    'price': self.truncate(price, self.currencies[quote]['precision']),
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 450, in truncate
    return math.trunc(num * decimal_precision) / decimal_precision
TypeError: can't multiply sequence by non-int of type 'float'

This happened with the following parameters:
try to create_order BCH/ETH buy kucoin 0.10011 1.76555800

Where 0.10011 is the amount, and 1.76555800 is the price.

**Comment by kroitor** [comment]
Can you show the code to reproduce the issue and your verbose output (without the keys) as described here https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

**Comment by frosty00** [comment]
For now self.truncate and all the other precision methods require amount and price to be a float. If you used a decimal or another object for the price or amount that could not be multiplied by a float you would get this error.
