### ISSUE TITLE
Not a problem but, query for live feed?

### ISSUE THREAD

**Issue by akel94** [ccxt/ccxt#2421]
- OS: Windows
- Programming Language version: python2.7
- CCXT version: 1.12.3
- Exchange: Binance
- Method: exchange.fetchTrades()

I'm having a hard time in obtaining the real time live feed of the prices of symbols due to the minute limit and the speed of the computation. Is there like another way to request a live feed whenever a trade is done or a change in Ohlcv happened? Other than submitting fetchTrades queries all the time?

**Comment by JoshVarty** [comment]
I think you're looking for the streaming API which (as I understand it) is a work in progress.

See: https://gist.github.com/kroitor/aabecc346a5bded6ead7a82205d8ffc1#gistcomment-2335076
Also: https://github.com/ccxt/ccxt/issues/464
#56
