### ISSUE TITLE
Hyperliquid - timeframes are incorrect

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#24230]
### Operating System

n/a

### Programming Languages

Python

### CCXT Version

4.4.29

### Description

Hello :)

The advertised hyperliquid timeframes have a couple of issues:

* 6h is advertised, but is not supported
* 8h is not advertised, but is supported
* the timeframes keys `1m` and `1M` have the same value, `1m`. The value of key `1M` should be `1M` (not sure where this is used though)

So 
* [here](https://github.com/ccxt/ccxt/blob/0254a8fd39a8add7e9c7e1602f08dbce386f4a9f/python/ccxt/async_support/hyperliquid.py#L134) `'6h': '6h',` should be changed to `'8h': '8h',` 
* [here](https://github.com/ccxt/ccxt/blob/0254a8fd39a8add7e9c7e1602f08dbce386f4a9f/python/ccxt/async_support/hyperliquid.py#L139) `'1M': '1m',` should be changed to `'1M': '1M',`

```
    from datetime import UTC
    e = ccxt.hyperliquid()
    e.aiohttp_proxy = 'http://127.0.0.1:8080'
    print(e.timeframes)
    for timeframe in list(e.timeframes.keys()) + ['8h']:
        try:
            await e.fetch_ohlcv('BTC/USDC:USDC', timeframe)
            print(f"timeframe {timeframe} OK")
        except ccxt.ExchangeError:
            print(f"timeframe {timeframe} ERROR")

```

```
{'1m': '1m', '3m': '3m', '5m': '5m', '15m': '15m', '30m': '30m', '1h': '1h', '2h': '2h', '4h': '4h', '6h': '6h', '12h': '12h', '1d': '1d', '3d': '3d', '1w': '1w', '1M': '1m'}
timeframe 1m OK
timeframe 3m OK
timeframe 5m OK
timeframe 15m OK
timeframe 30m OK
timeframe 1h OK
timeframe 2h OK
timeframe 4h OK
timeframe 6h ERROR
timeframe 12h OK
timeframe 1d OK
timeframe 3d OK
timeframe 1w OK
timeframe 1M OK
timeframe 8h OK
```

Thanks!

**Comment by sc0Vu** [comment]
@gaardiolor Thanks. We'll fix this asap.
