### ISSUE TITLE
GateIO - implement fetch_time

### ISSUE THREAD

**Issue by krasnyd** [ccxt/ccxt#24241]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.4.28

### Description

The GateIO API has an endpoint for fetching current server time (https://www.gate.io/docs/developers/apiv4/en/#get-server-current-time) that is not implemented in CCXT. It would be nice to have it.

### Code

```
  

```

**Comment by Dan-krm** [comment]
Thanks for letting us know, I've opened a pull request to implement fetchTime on gate
