### ISSUE TITLE
Set custom BrokerId on gate.io

### ISSUE THREAD

**Issue by fl0wo** [ccxt/ccxt#24251]
### Operating System

MacOS

### Programming Languages

JavaScript

### CCXT Version

latest

### Description

Is there a way to already setup our custom brokerId for a gateio instance on ccxt?

I see here:
https://github.com/ccxt/ccxt/blob/f52d1a9a4a61c4119f227983ad4991628c0055d0/js/src/gate.js#L636

That the header is hard-coded to be "ccxt".

Would be great if I could update that from the "options" as we do for other exchanges:

```
'options': {
        broker: 'my-broker-id-gate-io-code' // fallbacks to 'ccxt' if undefined
}
```

Any alternative otherwise?

Thanks for your work.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @fl0wo,

You can easily override it by doing something like this

```Python
exchange = new ccxt.gate({
    'headers': {
        'X-Gate-Channel-Id': 'code'
    }
}
```

**Comment by fl0wo** [comment]
I see, that's enough then.

Thanks for the quick support, peace.
