### ISSUE TITLE
binance parseTrade  id

### ISSUE THREAD

**Issue by giapnguyen74** [ccxt/ccxt#2428]
```js
    parseTrade (trade, market = undefined) {
        let timestampField = ('T' in trade) ? 'T' : 'time';
        let timestamp = trade[timestampField];
        let priceField = ('p' in trade) ? 'p' : 'price';
        let price = parseFloat (trade[priceField]);
        let amountField = ('q' in trade) ? 'q' : 'qty';
        let amount = parseFloat (trade[amountField]);
        let idField = ('a' in trade) ? 'a' : 'id';
```

I believe that it should be:
```
 let idField = ('t' in trade) ? 't' : 'id';
```
a is Seller Order Id and t is Trade id. I got duplicate id when use ccxt to parse websocket stream.

**Comment by kroitor** [comment]
According to their docs it should be as it is now: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#compressedaggregate-trades-list (uppercase `T`). Let us know if we are missing something. Your [verbose output](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue) might be needed as well to resolve it.

**Comment by giapnguyen74** [comment]
oh sorry my bad, I use @trade channel not @aggTrade which use t as tradeid not a as aggTrade.

**Comment by kroitor** [comment]
@giapnguyen74 no worries, thx for reporting back!
