### ISSUE TITLE
Kucoin: Wrong error type on kucoin when using funds parameter

### ISSUE THREAD

**Issue by mjwvb** [ccxt/ccxt#24286]
### Operating System

MacOS

### Programming Languages

JavaScript

### CCXT Version

4.4.28

### Description

On Kucoin I get the following error when placing a market order using kucoin's funds parameter (marketBuyOrderWithCost):

ExchangeError: kucoin {"msg":"The order funds should more then 0.1 USDT.","code":"600101"}

In ccxt this is mapped as an ExchangeError, but it should be an InvalidOrder. Would be nice to have this one fixed. 
Thanks!

### Code

```javascript
exchange.createMarketBuyOrderWithCost("XMR/USDT", 0.01)
```

**Comment by sc0Vu** [comment]
@mjwvb Thanks, we'll fix this asap.
