### ISSUE TITLE
I'm seeing an issue with Coinbase fetch_ledger() method not returning full history - stops at 250 when I know there are more

### ISSUE THREAD

**Issue by jtashiro** [ccxt/ccxt#24283]
I'm seeing an issue with Coinbase fetch_ledger() method not returning full history - stops at 250 when I know there are more ... should I open a new ticket or can I reopen this one?

_Originally posted by @jtashiro in https://github.com/ccxt/ccxt/issues/21756#issuecomment-2480855851_

**Comment by carlosmiei** [comment]
Hello @jtashiro,

What's your ccxt version?

If you enable the verbose mode can you see the call X+1 using the cursor from the call X?

**Comment by jtashiro** [comment]
CCXT Version: 4.4.31
{'paginate': True, 'until': 1730782800000}

Request:
[2024-11-18 09:25:33] GET https://api.coinbase.com/v2/accounts/eabf2885-45b9-5870-b8f0-e7857e8f13ec/transactions?limit=250&verbose=true&until=1730782800000, Response: 200

Response snippet
......"pagination":{"ending_before":null,"limit":250,"next_starting_after":"dd12489f-49a2-5ca8-bb71-21799d3dda4e","next_uri":"/v2/accounts/eabf2885-45b9-5870-b8f0-e7857e8f13ec/transactions?limit=250\u0026starting_after=dd12489f-49a2-5ca8-bb71-21799d3dda4e","order":"desc","previous_ending_before":null,"previous_uri":null,"starting_after":null}}

Cursor pagination call 1 method fetchLedger response length 250 cursor 
# of ledger entries 250

There are no other Cursor pagination calls after the first call ...

**Comment by jtashiro** [comment]
Thanks, I've looked at your fix coinbase.ts and will pull locally and build to test.  many thanks for quick turnaround.

**Comment by jtashiro** [comment]
I've pulled 4.4.32 and was able to test it out.  Looks much better, now getting > 250 results !  I will cross check against actual coinbase data , but this is clearly an improvement!
