### ISSUE TITLE
Kraken fetch balance not working

### ISSUE THREAD

**Issue by vidur149** [ccxt/ccxt#2430]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Ubunutu 14.04
- Programming Language version: Javascript/NodeJs
- CCXT version: 1.12.60
- Exchange: kraken
- Method: fetchBalance

The fetch balance method is not returning balances.

**Comment by kroitor** [comment]
Have you tried this: https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting ?

**Comment by kroitor** [comment]
Hope this answers your question: https://github.com/ccxt/ccxt/wiki/Manual#balance-inference
Let us know if not. Thx!

**Comment by vidur149** [comment]
Sorry, It didnt answer my question. fetchbalances is not returning anything. Not even partial balance information.

**Comment by kroitor** [comment]
Is it a new account with zero balances?

**Comment by vidur149** [comment]
Yes. It helps. Thanks a lot :dancing_men:

**Comment by kroitor** [comment]
@vidur149 thx for reporting back!
