### ISSUE TITLE
coinbaseexchange difference between publicGetProductsIdTicker and publicGetProductsIdStats

### ISSUE THREAD

**Issue by kilmern** [ccxt/ccxt#24314]
### Operating System

Ubuntu 20.04

### Programming Languages

Python

### CCXT Version

4.4.32

### Description

Both fetch_tickers methods return the same data without any volume. If I'm reading https://github.com/ccxt/ccxt/blob/master/python/ccxt/coinbaseexchange.py#L584 correctly, 'publicGetProductsIdStats' is supposed to return volume. Is this the correct behavior? Am I missing something?

### Code

```
>>> exchange
ccxt.coinbaseexchange()
>>> exchange.has['fetchTickers']
True
>>> exchange.options['fetchTickerMethod'] = 'publicGetProductsIdTicker'
>>> exchange.fetch_tickers()['BTC/USD']
{'symbol': 'BTC/USD', 'timestamp': 1732040299746, 'datetime': '2024-11-19T18:18:19.746Z', 'high': None, 'low': None, 'bid': None, 'bidVolume': None, 'ask': None, 'askVolume': None, 'vwap': None, 'open': None, 'close': 93300.0, 'last': 93300.0, 'previousClose': None, 'change': None, 'percentage': None, 'average': None, 'baseVolume': None, 'quoteVolume': None, 'info': ['1732039200', '92829.01', '93364.24', '92963.12', '93300'], 'indexPrice': None, 'markPrice': None}
>>> exchange.options['fetchTickerMethod'] = 'publicGetProductsIdStats'
>>> exchange.fetch_tickers()['BTC/USD']
{'symbol': 'BTC/USD', 'timestamp': 1732040304149, 'datetime': '2024-11-19T18:18:24.149Z', 'high': None, 'low': None, 'bid': None, 'bidVolume': None, 'ask': None, 'askVolume': None, 'vwap': None, 'open': None, 'close': 93300.0, 'last': 93300.0, 'previousClose': None, 'change': None, 'percentage': None, 'average': None, 'baseVolume': None, 'quoteVolume': None, 'info': ['1732039200', '92829.01', '93364.24', '92963.12', '93300'], 'indexPrice': None, 'markPrice': None}
 

```

**Comment by kilmern** [comment]
Looks like the volume info is provided by the following coinbase api. 

https://api.exchange.coinbase.com/products/volume-summary

Is this utilized anywhere within ccxt?

**Comment by sc0Vu** [comment]
@kilmern Thanks, we'll add this api asap.

**Comment by kilmern** [comment]
Thanks @sc0Vu! Do you know when latest build will be available to test it out?

**Comment by carlosmiei** [comment]
@kilmern We just released a new version 🙂 

> Are you guys planning on integrating this into the unified method any time soon?

Yes we're considering it (@sc0Vu is taking a look at that)
