### ISSUE TITLE
New Exchange: BuyBitcoin

### ISSUE THREAD

**Issue by sumitjaiswl90** [ccxt/ccxt#2431]
uri: https://buybitcoin.org.in
api: https://buybitcoin.org.in/coin/stats/INR
https://buybitcoin.org.in/coin/stats/USD

**Comment by kroitor** [comment]
Do they have any API docs anywhere?

**Comment by jjhesk** [comment]
only ws. wss://buybitcoin.org.in/socket.io/?EIO=3&transport=websocket&sid=eTMUmcH4qbfPI8QcAACh

**Comment by An-Net** [comment]
The website doesn't work anymore:

- https://www.reddit.com/r/CryptoCurrency/comments/8em6ds/buybitcoinorgin_fud_scam_fraud_indian_exchange/
