### ISSUE TITLE
gate loadUnifiedStatus working against the docstring

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#24325]
### Operating System

linux

### Programming Languages

Python

### CCXT Version

4.4.33

### Description

using gate - the "loadUnifiedStatus" docstring suggests that
* the method is called `isUnifiedEnabled` (aligned to bybit)
* the method returns a boolean for unified accounts

Neither of which is true unfortunately, and the method returns nothing - only sets the `options['unifiedAccount']` option internally (that's not wrong - but returning a bool as the docstring suggests would be great and save the user an additional line).

https://github.com/ccxt/ccxt/blob/2c92a09f6265da15b1809044b9fc1bbc25671708/ts/src/gate.ts#L901-L909

### Code

``` python
import ccxt
exchange = ccxt.gate({
    'apiKey': '<yourApiKey>', 
    'secret': '<yoursecret>', 
    })
res = exchange.load_unified_status()
print(res)

res = exchange.is_unified_enabled()  # This fails as the method doesn't exist

```

**Comment by sc0Vu** [comment]
@xmatthias Thanks, we'll fix this asap.
