### ISSUE TITLE
Futures disabled for Spanish accounts

### ISSUE THREAD

**Issue by jmunozvalencia** [ccxt/ccxt#24323]
### Description

It seems that futures are not allowed anymore in Spain, so I can´t access to the fapi anymore. It is possible to configure ccxt to use sapi instead?

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @jmunozvalencia,

sapi should only be used to trade spot markets whereas fapi is the API for futures trading. 

If you can't access it from spain, you have to find an alternative if you still want to trade futures but that alternative is not related to CCXT there's nothing we can do on our side to lift that block.

**Comment by jmunozvalencia** [comment]
It seems that fetch_my_trades uses fapi by the fault and thatś is able to return the spot trades, however it is not longer working. My question is if it is possible to change fetch_my_trades to use sapi instead. Thanks

**Comment by carlosmiei** [comment]
@jmunozvalencia 

If you provide a `spot` symbol, then ccxt will use `sapi`, if you provide a perp/future `symbol` ccxt will use `fapi`

**Comment by carlosmiei** [comment]
@jmunozvalencia Np 🙂
