### ISSUE TITLE
Docs for 'Deposit' - missing / incomplete

### ISSUE THREAD

**Issue by respectabiggle** [ccxt/ccxt#24339]
Docs mention method but then skip ahead and describe 'fetchDeposit'.
Description/example for  'deposit' method is missing.

> https://github.com/ccxt/ccxt/wiki/manual#deposit

Does this method only exist for Coinbase ?

> https://github.com/ccxt/ccxt/pull/21422

Example
> deposit (code, amount, id)  
> deposit ('USD', 10, 'a1b2c3d4-5678-901e-f2gh-3ij45k678901')  <- id for 'ACH payment method'

Returns (deposit transaction) 'id' used for 'fetchDeposit'
> fetchDeposit (id, code)
> fetchDeposit ('ab12c345-d67e-8901-234f-56ghijk78l90', 'USD')

May I request a ccxt method to find ACH account id?  I have mine but it might help other ppl.

> previously at [v2/payment-methods](https://docs.cdp.coinbase.com/coinbase-app/docs/api-payment-methods)  
> replaced by [v3/brokerage/payment_methods](https://docs.cdp.coinbase.com/advanced-trade/reference/retailbrokerageapi_getpaymentmethods)

I would do it but not enough experience with OOP.  But I can get it started if someone would finish it *shrug*

Thanks

**Comment by respectabiggle** [comment]
I've been using the underlying 'deposit' API on Coinbase for some time, and the ccxt method since it was added.  

If I can be helpful at all I will do my best.

**Comment by Dan-krm** [comment]
Hi @respectabiggle 
The deposit method only exists on coinbase because a user requested it for automating fiat deposits.

Generally we only unify methods and add documentation if the method can be supported on multiple exchanges,
The documentation on Deposits is currently just explaining cryptocurrency deposits where you need to `fetchDepositAddress` and call `withdraw` so a deposit method is not needed.

If we support `deposit` on more exchanges we can add documentation

We can also look into adding a `fetchFiatDepositAddress` method and see if it gets approved

I'm not sure if we want fiat specific methods like `deposit` and a new `fetchFiatDepositAddress` or if want to just add a boolean `fiat` param to `withdraw` and `fetchDepositAddress` I'll consult with the CCXT team and see which would be preferred

**Comment by respectabiggle** [comment]
@Dan-krm Ah I see.  Thanks for the explanation.

I think 'depositFiat' would be a valuable addition to the library for all exchanges where it is available, for automating DCA buys.  And a new 'fetchPaymentMethods' method would complement that.  But I understand if that's not top priority right now.  

FWIW here's the ACH portion for the 'payment-methods' endpoint for Coinbase.

```        {
            "id": redacted    <===  this uuid is needed for their 'payments' / POST method
            "type": "ACH",
            "name": "BANK OF AMERICA, N.A. ****6635",
            "currency": "USD",
            "verified": true,
            "allow_buy": true,
            "allow_sell": false,
            "allow_deposit": true,
            "allow_withdraw": true,
            "created_at": "2022-10-09T00:24:42Z",
            "updated_at": "2024-11-21T21:50:50Z"
        }, 
```

**Comment by Dan-krm** [comment]
@respectabiggle I opened a pull request with some of your suggestions here: https://github.com/ccxt/ccxt/pull/24454

**Comment by respectabiggle** [comment]
Cheers - that's so cool 

Can I strongly suggest naming method 'fetchPaymentMethods' and 'fetchPaymentMethod' - that's literally what it does.

and 'fetchDepositId' to me sounds like its trying to fetch a deposit - similar to ccxt 'fetchDeposits'


Maybe can wait until the day 'depositFiat()' is made a unified method - and I have also just now noticed that the needed 'payment method' uuid in question can be found in res at ccxt fetchDeposits('USD')

```{
  info: {..
      payment_method: {
        id: 'xx',  
    },```


For the original Issue - here is a possible docs edit --

```Deposit

   deposit ()

Method to deposit fiat from ACH or other funding source, to exchange fiat balance.

> currently only enabled for Coinbase

Method requires 3 parameters:

- currency code of fiat depositing ex. 'USD'
- amount of deposit in fiat denomination ex. '10'
- uuid of payment method - this can be found at the res for ccxt method 'fetchDeposit()' 

~In order to deposit funds to an exchange you must get an address payment method uuid from the exchange for the currency you want to deposit there. Most of exchanges will create and manage those addresses for the user.~


...Data on deposits made to an account can be retrieved using... (back to orig Docs```

**Comment by Dan-krm** [comment]
@respectabiggle I want to keep deposit in the name for that series of methods, I've opened a pull request to change the name to `fetchDepositMethodId`

**Comment by respectabiggle** [comment]
Cheers @Dan-krm, thanks for the reply
