### ISSUE TITLE
Generating SHA256 signature for Bitbank GET and POST requests

### ISSUE THREAD

**Issue by tuyet130953** [ccxt/ccxt#2433]
Having trouble getting the right signing structure for Bitbank.  Can you point me in the right direction?

API
https://docs.bitbank.cc/

This is an attempt to sign for a POST request
```
var request = require('request');
var crypto = require('crypto');

var key = 'xxxxxxxxxxx'
var secret = 'xxxxxxxxxxxxxxxxxxxxxxx'

var timestamp = '1522660717764'
var body = JSON.stringify({
  "asset": "btc",
  "uuid": "9bf567b0-1b38-11e8-8d5f-fbd4ad6dab2c",
  "amount": "1",
  "otp_token": "440620",
  "sms_token": ""
});


var text = timestamp + body
var sign = crypto.createHmac('sha256', secret).update(text).digest('hex');
```

**Comment by kroitor** [comment]
Hope this helps: https://github.com/ccxt/ccxt/blob/master/js/bitbank.js#L406

**Comment by tuyet130953** [comment]
Thank you. I have looked at it before to try and reverse engineer what you've done, however I am very new to coding and am having a hard time understanding it. If you can point me in the right direction, would much appreciate it.

**Comment by kroitor** [comment]
@tuyet130953 your `nonce` (timestamp) value should be increasing, each new request should have a new unique nonce value (increment it by one or just use the current timestamp in milliseconds). Unfortunately, I can't really consult you beyond ccxt, sorry.

**Comment by tuyet130953** [comment]
Thanks I got it to work! Code above was for testing as I was using a fixed timestamp to attempt to generate a sample signature i got using the demonstration on the API webpage. However when attempting a real request, it works.

**Comment by kroitor** [comment]
@tuyet130953 thx for reporting back! Hope it helps other users as well.
