### ISSUE TITLE
Event loop issue

### ISSUE THREAD

**Issue by SpandexMan1** [ccxt/ccxt#24346]
### Operating System

Windows Server 2022 Datacenter

### Programming Languages

Python

### CCXT Version

4.4.33

### Description

I have started a new vps on windows Datacenter and am using ccxtpro to call a straightforward fetch_ohlcv(). I'm getting raised a runtime error, citing that 'aiodns needs a SelectorEventLoop on windows.
I am using Python 3.13
```Python 3.13
import ccxt.pro as ccxtpro 
import asyncio
  exchange = ccxtpro.binance()
   async def main():     
       ohlcv = await exchange.fetch_ohlcv("BTCUSDT", "5m" )     
       print(ohlcv)
       
    if __name__=="__main__":     
        asyncio.run(main())
```

> C:\Users\Administrator\AppData\Local\Programs\Python\Python313\python.exe C:\Users\Administrator\Documents\FinTech\Exchanges\BinanceHistoric.py 
> Traceback (most recent call last):
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiodns\__init__.py", line 58, in __init__
>     import winloop
> ModuleNotFoundError: No module named 'winloop'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Administrator\Documents\FinTech\Exchanges\BinanceHistoric.py", line 10, in <module>
>     asyncio.run(main())
>     ~~~~~~~~~~~^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
>     return runner.run(main)
>            ~~~~~~~~~~^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete
>     return future.result()
>            ~~~~~~~~~~~~~^^
>   File "C:\Users\Administrator\Documents\FinTech\Exchanges\BinanceHistoric.py", line 6, in main
>     ohlcv = await exchange.fetch_ohlcv("BTCUSDT", "5m" )
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\ccxt\async_support\binance.py", line 4487, in fetch_ohlcv
>     await self.load_markets()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\ccxt\async_support\base\exchange.py", line 287, in load_markets
>     raise e
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\ccxt\async_support\base\exchange.py", line 283, in load_markets
>     result = await self.markets_loading
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\ccxt\async_support\base\exchange.py", line 273, in load_markets_helper
>     markets = await self.fetch_markets(params)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\ccxt\async_support\binance.py", line 3096, in fetch_markets
>     results = await asyncio.gather(*promisesRaw)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\ccxt\async_support\binance.py", line 11235, in request
>     response = await self.fetch2(path, api, method, params, headers, body, config)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\ccxt\async_support\base\exchange.py", line 882, in fetch2
>     raise e
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\ccxt\async_support\base\exchange.py", line 873, in fetch2
>     return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\ccxt\async_support\base\exchange.py", line 201, in fetch
>     self.open()
>     ~~~~~~~~~^^
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\ccxt\async_support\base\exchange.py", line 118, in open
>     self.tcp_connector = aiohttp.TCPConnector(ssl=self.ssl_context, loop=self.asyncio_loop, enable_cleanup_closed=True)
>                          ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 863, in __init__
>     resolver = DefaultResolver(loop=self._loop)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\resolver.py", line 95, in __init__
>     self._resolver = aiodns.DNSResolver(*args, **kwargs)
>                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiodns\__init__.py", line 63, in __init__
>     raise RuntimeError(
>         'aiodns needs a SelectorEventLoop on Windows. See more: https://github.com/saghul/aiodns/issues/86')
> RuntimeError: aiodns needs a SelectorEventLoop on Windows. See more: https://github.com/saghul/aiodns/issues/86
> 
> Process finished with exit code 1
> 
> 

### Code

```Python 3.13
import ccxt.pro as ccxtpro 
import asyncio
  exchange = ccxtpro.binance()
   async def main():     
       ohlcv = await exchange.fetch_ohlcv("BTCUSDT", "5m" )     
       print(ohlcv)
       
    if __name__=="__main__":     
        asyncio.run(main())

```

**Comment by SpandexMan1** [comment]
And yes, I have tried to pip install winloop.

**Comment by carlosmiei** [comment]
@ttodua Can you check this issue pls?

**Comment by ttodua** [comment]
@SpandexMan1 I'll take a look into the issue and post an update within 12 hours

**Comment by ttodua** [comment]
ah, this is a newly emerged issue after aiohttp package was updated. 
as a temporary fix, use :
```
import sys
import asyncio

if sys.platform == 'win32':
	asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

Fixing this in ccxt alone is trickier and we will post an update whether we go one route or another. for now, you can use the above workaround.

**Comment by ttodua** [comment]
let me know if you have further issues.

**Comment by SpandexMan1** [comment]
Brilliant! Thank you

**Comment by Craigkjellknudsen** [comment]
ttodua - Thank you soooo much for this. I am not a developer but I pay chatgpt subscription and it is/has developed me bots. It has been trying to create one for weeks for IG and that was the issue above, which is now sorted thanks to you.
