### ISSUE TITLE
Can't access btcx fetch ticker

### ISSUE THREAD

**Issue by SpaceWhite** [ccxt/ccxt#2434]
- OS: Ubuntu 16.04 LTS
- Programming Language version: Python 3.5.2
- CCXT version: 1.12.59
- Exchange: btcx
- Method: `btcx.fetch_ticker('BTC/USD')`

**Comment by kroitor** [comment]
Have you tried this: https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting ?
If it does not help, we will need your code and verbose output: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue. Feel free to reopen it if needed, or just ask questions, if any. Thx!
