### ISSUE TITLE
Identifying subcategories on the exchange

### ISSUE THREAD

**Issue by azim1399** [ccxt/ccxt#24353]
### Operating System

windos

### CCXT Version

4.4.32

### Description

I want to know if the user who enters his apiKey and secret information is one of my referrals on the exchange.
Is there a function that determines whether the user is in my sub-group on the exchange or not?

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @azim1399,

We don't have any unified method to get that information, but if the exchange provides an endpoint for it, you can always access it through the implicit API.

Please read more about it here: https://docs.ccxt.com/#/README?id=implicit-api
