### ISSUE TITLE
bybit perpetual contract unable to fetch ohlcv

### ISSUE THREAD

**Issue by amiglesia** [ccxt/ccxt#24358]
### Operating System

Windows

### Programming Languages

Python

### Description

Unable to retrieve ohlcv for ticker in linear but no spot.

ticker sample: MAJORUSDT , USUALUSDT
Both ticker was able to extract from exchange.fetch_tickers but getting error "ccxt.base.errors.BadSymbol: bybit does not have market symbol MAJORUSDT"

### Code

```python
import ccxt
import pprint

# Initialize Bybit exchange
exchange = ccxt.bybit({
    'enableRateLimit': True,
})

# Function to get the symbol list ending with USDT
def get_symbol_list():
    try:
        # Fetch all tickers with category 'linear'
        tickers = exchange.fetch_tickers(params={'category': 'linear'})

        processed_symbols = [symbol for symbol in tickers.keys() if symbol.endswith("USDT")]

        return processed_symbols

    except ccxt.NetworkError as e:
        print(f"Network error: {e}")
    except ccxt.ExchangeError as e:
        print(f"Exchange error: {e}")
    except Exception as e:
        print(f"An error occurred: {e}")

# Get the list of linear symbols with USDT
symbols = get_symbol_list()
def get_kline_data(symbol, interval='1m', limit=1):
    exchange.load_markets()
    return exchange.fetch_ohlcv(symbol, timeframe=interval, limit=limit,params={'category': 'linear'})
for symbol in symbols:
    pprint.pprint(get_kline_data(symbol))
```

**Comment by carlosmiei** [comment]
Hello @amiglesia,

First of all I would suggest using the unified symbols instead to avoid clashes

In this case
```
MAJOR/USDT => spot
MAJOR/USDT:USDT => linear perp
```

Regarding your issue, I don't think that bybit provides the spot `MAJOR/USDT` market hence the error you're getting

**Comment by carlosmiei** [comment]
@amiglesia 

Are you sure that your markets are updated? If you have a long running instance can you please try to do `exchange.load_markets(True)` to refresh the cache?

I just tested it and seems to be working as expected

```
 p bybit fetchOHLCV "MAJOR/USDT:USDT" 1h None 5 --no-keys
Python v3.12.3
CCXT v4.4.33
bybit.fetchOHLCV(MAJOR/USDT:USDT,1h,None,5)
[[1732442400000, 1.3969, 1.4178, 1.366, 1.3681, 5493.3],
 [1732446000000, 1.3681, 1.4353, 1.3236, 1.33, 12656.7],
 [1732449600000, 1.33, 1.379, 1.02, 1.13, 130550.8],
 [1732453200000, 1.13, 1.241, 1.13, 1.182, 44810.0],
 [1732456800000, 1.182, 1.1952, 1.1179, 1.1585, 22694.8]]
```

**Comment by gcheng24** [comment]
@amiglesia I got this error too and updating the ccxt module fixed it

**Comment by amiglesia** [comment]
confirm, updating the ccxt module fixed this. thank you.

**Comment by carlosmiei** [comment]
@gcheng24 @amiglesia Thanks for confirming it!
