### ISSUE TITLE
Yobit create order

### ISSUE THREAD

**Issue by ardialamwijaya** [ccxt/ccxt#2435]
- OS: windows
- Programming Language version:
- CCXT version:1.12.62
- Exchange:yobit
- Method: create_order

at this current version, we dont have a create_order. when ccxt will provide it?

**Comment by kroitor** [comment]
It's there from the very beginning:
- https://github.com/ccxt/ccxt/blob/master/js/yobit.js#L10
- https://github.com/ccxt/ccxt/blob/master/js/liqui.js#L361
Inherited from Liqui. All exchanges with a private API have at least `create_order` and `cancel_order`.
Let us know if it does not answer your question. Thx!

**Comment by ardialamwijaya** [comment]
but its in js.. im doing it in PHP

**Comment by kroitor** [comment]
@ardialamwijaya in this library, php code is generated from js: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

**Comment by kroitor** [comment]
@ardialamwijaya 
- https://github.com/ccxt/ccxt/blob/master/php/liqui.php#L364
- https://github.com/ccxt/ccxt/blob/master/php/yobit.php#L8

**Comment by ardialamwijaya** [comment]
ok thx 👍
