### ISSUE TITLE
bithumb /trade/place gives invalid parameter error

### ISSUE THREAD

**Issue by naveenvhegde** [ccxt/ccxt#2436]
- OS: Unix
- Programming Language version: python3.6
- CCXT version: master
- Exchange: bithumb
- Method: trade/place

When I tried to place limit order to bithumb exchange using method ```exchange.create_limit_buy_order('ETH/KRW', 0.1, 400000)```. It gives me error "Exception:bithumb {"status":"5500","message":"Invalid Parameter"}"

below is the request made to bithumb with params, looks like all the params are properly populated

```b'endpoint=%2Ftrade%2Fplace&order_currency=ETH&Payment_currency=KRW&units=0.1&price=400000.0&type=bid'```

```
{
    'Accept': 'application/json', 
    'Content-Type': 'application/x-www-form-urlencoded', 
    'Api-Key': 'hidden', 
    'Api-Sign': 'hidden', 
    'Api-Nonce': 'hidden', 
    'User-Agent': 'python-requests/2.18.4', 
    'Accept-Encoding': 'gzip, deflate'
}
```

**Comment by kroitor** [comment]
Does this work for you?

```
exchange.create_limit_buy_order('ETH/KRW', 0.1, '400000') # price as string here
```

?

**Comment by naveenvhegde** [comment]
{'order_currency': 'ETH', 'Payment_currency': 'KRW', 'units': 0.1, 'price': '400000', 'type': 'bid'}

**Comment by kroitor** [comment]
@naveenvhegde sorry?

**Comment by naveenvhegde** [comment]
I changed price parameter from float to string. Instead of Invalid Parameter, it got 5600 error in some korean language.

**Comment by kroitor** [comment]
> I changed price parameter from float to string. Instead of Invalid Parameter, it got 5600 error in some korean language.

It will be really hard to help, if you don't follow these reporting recommendations precisely: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Whenever you mention an 5600 error and a message – we expect to see at least your full `verbose` output of request-response (without the keys, of course).

**Comment by naveenvhegde** [comment]
Ok. I will enable verbose flag and update detailed log here in an hour time. Sorry.

**Comment by naveenvhegde** [comment]
Hi.

Invalid Parameter error got fixed after we converted price field to int. ```result = bithumb.create_limit_sell_order("ETH/KRW", float(0.1), int(400000))```.

You can close this issue. Many thanks for your help.

**Comment by kroitor** [comment]
@naveenvhegde thx for reporting back! Will add a workaround for this to ccxt shortly.

**Comment by kroitor** [comment]
Looks like it's fixed in the most recent version of ccxt. Closing this. Thx!
