### ISSUE TITLE
BingX incorrect request for some endpoints

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#24379]
### Description

For some endpoints we need to pass parameters using JSON, not query string. Support confirmed to me that I need to use JSON. Now I get error `{"code":100400,"msg":"miss arguments","timestamp":1732276055969}` when try to use `/openApi/subAccount/v1/apiKey/create` for example. I want to ask modify request for these endpoints:

https://bingx-api.github.io/docs/#/en-us/common/sub-account#Create%20sub-account
https://bingx-api.github.io/docs/#/en-us/common/sub-account#Create%20an%20API%20Key%20for%20a%20sub-account
https://bingx-api.github.io/docs/#/en-us/common/sub-account#Reset%20the%20API%20Key%20of%20a%20sub-account
https://bingx-api.github.io/docs/#/en-us/common/sub-account#Delete%20the%20API%20Key%20of%20sub-accounts
https://bingx-api.github.io/docs/#/en-us/common/sub-account#Freeze%20and%20unfreeze%20sub-accounts
https://bingx-api.github.io/docs/#/en-us/common/sub-account#Query%20the%20transferable%20amount%20of%20funds%20in%20the%20parent-child%20account%20(only%20for%20parent%20account%20operations).
https://bingx-api.github.io/docs/#/en-us/common/sub-account#Sub-Account%20Asset%20Transfer%20Interface%20(For%20Master%20Account%20Operations%20Only)

![image](https://github.com/user-attachments/assets/41b1057f-70f6-497c-9c1b-76fb6c39579d)

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @ndubel,

Thanks for reporting it, we will check if we can adjust it.

In the meantime can you try to add it on your end?

You can do something like this before calling the endpoint

```Python
bingx.headers['Content-Type'] = "application/json"
```

**Comment by ndubel** [comment]
@carlosmiei
I've added `Content-Type` in the way you said but `RequestBody` is still empty, all parameters are in URL

```
fetch Request:
 bingx POST https://open-api.bingx.com/openApi/subAccount/v1/apiKey/create?ipAddresses=%5Bxxx.xxx.xxx.xx%5D&note=trade&permissions=%5B1%2C2%2C3%2C4%2C7%5D&subUid=xxx&timestamp=1732647525406&signature=xxx
RequestHeaders:
 {
  'Content-Type': 'application/json',
  'X-BX-APIKEY': 'xxx',
  'X-SOURCE-KEY': 'CCXT'
} 
RequestBody:
 undefined 

handleRestResponse:
 bingx POST https://open-api.bingx.com/openApi/subAccount/v1/apiKey/create?ipAddresses=%5Bxxx.xxx.xxx.xxx%5D&note=trade&permissions=%5B1%2C2%2C3%2C4%2C7%5D&subUid=xxx&timestamp=1732647525406&signature=xxx 200 OK 
ResponseHeaders:
 {
  'Alt-Svc': 'h3=":443"; ma=86400',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': 'xxx',
  Connection: 'keep-alive',
  'Content-Encoding': 'br',
  'Content-Type': 'application/json',
  Date: 'Tue, 26 Nov 2024 18:58:45 GMT',
  Server: 'cloudflare',
  'Set-Cookie': 'xxx; path=/; expires=Tue, 26-Nov-24 19:28:45 GMT; domain=.bingx.com; HttpOnly; Secure; SameSite=None',
  'Strict-Transport-Security': 'max-age=15552000; includeSubDomains; preload',
  'Transfer-Encoding': 'chunked',
  Vary: 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers',
  'X-Content-Type-Options': 'nosniff',
  'X-Ratelimit-Requests-Expire': '1000',
  'X-Ratelimit-Requests-Remain': '4',
  'X-Source-Key': 'CCXT'
} 
ResponseBody:
 {"code":100400,"msg":"miss arguments","timestamp":1732647525631} 

```

**Comment by carlosmiei** [comment]
@ndubel Oh ok, you're right I was assuming the only problem was the content-type missing from headers, we will try to apply a proper fix soon.

**Comment by ndubel** [comment]
@carlosmiei @Dan-krm I still have an issue for example with [Create an API Key for a sub-account](https://bingx-api.github.io/docs/#/en-us/common/sub-account#Create%20an%20API%20Key%20for%20a%20sub-account)
Request body:
`{"ipAddresses":"[xxx.xxx.xxx.xxx]","note":"trade","permissions":"[1,2,3,4,7]","subUid":"xxxx","timestamp":1733140673002,"signature":"xxx"}`
So arrays was transformed to strings. And error is the same:
`{"code":100400,"msg":"miss arguments","timestamp":1733140673309}`

Ok, I've try to keep arrays in request body:
`{"ipAddresses":["xxx.xxx.xxx.xxx"],"note":"trade","permissions":[1,2,3,4,7],"subUid":"xxx","timestamp":1733138965647,"signature":"xxx"}`

But in this case I have some issue with signature:
`{"code":100001,"msg":"Signature verification failed due to signature mismatch,please verify our authentication signature and try to  run our sample code  from the link https://bingx-api.github.io/docs/#/en-us/spot/account-api.html#Query%20Assets","timestamp":1733138965879}`
Maybe you can help to understand how to deal with arrays in signature?
https://bingx-api.github.io/docs/#/en-us/swapV2/authentication.html#Signature%20Description
