### ISSUE TITLE
Historical Data Through LOC Extension?

### ISSUE THREAD

**Issue by Shipwreck** [ccxt/ccxt#2438]
- OS: Ubuntu 16.10
- Programming Language version: 
- CCXT version: 1.9.262
- Exchange: Any
- Method:

Hi guys! I found CCXT through [LOC Extension](https://github.com/walkjivefly/LOC-Extension). I feel like I just discovered a whole new world. Essentially I am trying to work with historical exchange data in spreadsheets. I feel like I am close, but would like confirmation that it's even possible. 

In examples.ods>ccxt I see the CCXT 'datacode' options for 'timestamp' and 'datetime' - looks perfect!

However, I can't get anything returned other than #VALUE!

'datetime' is ISO8601 so I thought just putting '2017-03-12' would fetch the data for a particular pair on a particular exchange on that date.

For example

`=CCXT("BitFinex","BTC/USD","last")` works great to fetch current price but `=CCXT("BitFinex","BTC/USD","2017-03-04")` returns Exception Encountered.

I posted on that [Github](https://github.com/walkjivefly/LOC-Extension/issues/5) and it seems like its possible. Hoping to ask here and get confirmation and a push in the right direction. 

Thanks very much for any advice.

**Comment by kroitor** [comment]
The author of the extension is @walkjivefly , I hope he can clarify the example here. However, in general, whenever you see any example most often you should be prepared to re-engineer its source code for your needs.

> 'datetime' is ISO8601 so I thought just putting '2017-03-12' would fetch the data for a particular pair on a particular exchange on that date.

This is a misconception. That particular extension does not accept dates, it accepts a name of a ticker field: https://github.com/ccxt/ccxt/wiki/Manual#price-tickers. The extension itself is not a readily-available general-purpose solution, it's more a static example of a task-specific implementation, and for your own task you will need to tweak it significantly, add more methods, edit the existing ones, etc...

So you can't just assume that it's possible to do something and then expect that your assumption is correct, unless you checked its source code for that particular functionality.

Hope it helps. Let us know if not. Feel free to reopen this issue if needed, or just ask questions, if any. Thx!

**Comment by kroitor** [comment]
Hi, @RealRageDontQuit !

> Can it be an addition to the source code or will I have to create my own instance of ccxt_mod per se?

We don't merge it if it sends out more than one HTTP request. So, in the library all methods are issuing one HTTP request per call at max, and we'd like to keep it that way. That means, if the users wants to issue multiple requests within one method call – this has to be done in userland. The reasoning behind that is most users want fine-grained control over their rate-limiting and request scheduling.
