### ISSUE TITLE
Kucoin's fetch_order_book yielding response from other symbols in other threads

### ISSUE THREAD

**Issue by slix88** [ccxt/ccxt#2439]
Hi

I am not sure if this is a limitation with the wrapper, with Kucoins API or my code. I will use an example below to explain:

I am fetching the order book for 5 coins simultaneously with each in a separate thread (using multi-threading). I have locks in my function, except for the variables to which the order_book outputs are assigned. However, I have made sure these variable have a unique name so there wouldn't be any overlap between threads (e.g., `kucoin_order_book[j]` where j = 0,1,2,3,4, representing thread number. The single line code is as follows:

`kucoin_order_book[j] = kucoin.fetch_order_book(symbol)`

Assume j = 0 is symbol = "ETH/BTC" and j = 1 is symbol = "LTC/BTC". What is happening is kucoin_order_book[0] is sometimes returning the order book for LTC/BTC. I suspect it is because both requests are going out at the same time and a response for "LTC/BTC" is being received first and being assigned to kucoin_order_book[0]? Is this at all possible?

I have checked the DEBUG logs and the responses from kucoin seem correct based on the request URL.

Is there any way I could fix this or find a workaround? Implementing a lock renders the multi-threading pointless. Also, I would prefer to use multi-threading instead of multiprocessing (based on how I have written my code) - have tested with multiprocessing and I don't get the issue above.

Your help will be greatly appreciated! Thanks

**Comment by frosty00** [comment]
This has nothing to do with ccxt, but rather your faulty threading implementation. Moreover you have provided hardly any code so sorry we cannot help you.

**Comment by kroitor** [comment]
@slix88 if you're using multiple threads for polling the orderbooks, and you're not calling any private methods except for `fetch_order_book`, then you should instantiate one instance of kucoin class per thread. Each thread would then be working with its own instance of the exchange class and there will be no thread-interference. Also, this type of setup does not require thread resource locking. Hope it helps. Let us know, if not.
