### ISSUE TITLE
[Question] Managing Multiple API Keys with WebSocket in ccxt.pro (TypeScript)

### ISSUE THREAD

**Issue by cozy-hn** [ccxt/ccxt#24399]
### Operating System

ios

### Description

Hi ccxt team,
First, I’d like to express my gratitude for your continued hard work and swift updates to this amazing library! 🙏
I’m using TypeScript and exploring a way to calculate PnL for different assets by managing multiple sub-accounts. My approach is to create a new ccxt.pro.binance instance for each sub-account, initializing it with a unique API key and secret.
While calling REST API functions seems to work fine, I’m unsure about the WebSocket-related functions. Will each instance handle WebSocket connections independently and function properly in this setup? Or is there anything specific I should be aware of when managing multiple WebSocket connections using ccxt.pro with different API keys?
Thank you for your time and for maintaining this awesome library!

**Comment by carlosmiei** [comment]
Hello @cozy-hn,

Thanks for your kind words and support.

> Will each instance handle WebSocket connections independently and function properly in this setup?

Yes that's correct, each instance is independent.

**Comment by cozy-hn** [comment]
@carlosmiei  Thanks for answering :) 👍
