### ISSUE TITLE
bitrue wrong listenKey URL

### ISSUE THREAD

**Issue by vyahnov** [ccxt/ccxt#24396]
### Operating System

Ubuntu 20.04

### Programming Languages

JavaScript

### CCXT Version

4.4.34

### Description

To receive the listenKey, a POST request is made to https://open.bitrue.com/private/poseidon/api/v1/listenKey, but the server always responds with "503 Service Temporarily Unavailable ALB ERROR".

This looks like an AWS load balancer error but bitrue support says that "/private" should be removed from the URL.

### Code

```
  

```

**Comment by carlosmiei** [comment]
@vyahnov Thanks for reporting it, we will take a look asap. cc/ @sc0Vu

**Comment by sc0Vu** [comment]
@vyahnov @carlosmiei  The error seems to be related to the exchange's load balancer. I couldn't find any notes about this in their documentation: https://www.bitrue.com/api_docs_includes_file/spot/index.html#user-streams-websocket. Not sure if this is an issue with CCXT

**Comment by vyahnov** [comment]
@sc0Vu If i perform a POST-request without "/private" URL part, then the interface works

**Comment by vyahnov** [comment]
![Screenshot from 2024-11-29 07-50-36](https://github.com/user-attachments/assets/8070b1ab-8cbe-420b-ad3d-5d9e651d2247)

**Comment by sc0Vu** [comment]
@vyahnov Thanks, we'll fix this asap.
