### ISSUE TITLE
Bitpanda or not ?

### ISSUE THREAD

**Issue by Sailman83** [ccxt/ccxt#24391]
### Operating System

Linux

### Programming Languages

Python

### CCXT Version

Latest

### Description

Hello,

I can see Bitpanda in the code repository but not in list exchange.

So, can we use Bitpanda with ccxt or we need to wait something?

Best regards 

### Code

```
  

```

**Comment by sc0Vu** [comment]
Hi @Sailman83 Yes, ccxt have integrated Bitpanda. You can use it.

**Comment by carlosmiei** [comment]
Hello @Sailman83, you can't see it directly, because bitpanda was renamed to `onetrading` so now it's just an alias.
