### ISSUE TITLE
TakeProfit by limit and not market order (Phemex)

### ISSUE THREAD

**Issue by egabosh** [ccxt/ccxt#24409]
### Operating System

Debian 12

### Programming Languages

Python

### CCXT Version

4.4.34

### Description

Moin,

fix in https://github.com/ccxt/ccxt/issues/24247 seems not to work.
Still generating TakeProfit Market and not Limit order.

Thank you
olli

### Code

```
exchange.createOrder(symbol='SOL/USDT:USDT', type='Limit', price=333, amount=3, side='buy', params={'marginMode': 'isolated', 'stopLossPrice': '222', 'takeProfitPrice': '444', })
```

**Comment by ttodua** [comment]
@egabosh
I've referred to this code: https://docs.ccxt.com/#/README?id=stoploss-and-takeprofit-orders-attached-to-a-position
but your code is different, can you try that given example and let me know if you experience issues?

**Comment by ttodua** [comment]
here i've copy-pasted that code and just placed your symbol & amounts:
```
    params = {
        'marginMode': 'cross',
        'stopLoss': {
            'triggerPrice': 202.0,
            'price': 200.00,
        },
        'takeProfit': {
            'triggerPrice': 300.00,
            'price': 320.00,
        }
    }
    result = await exchange.create_order ('SOL/USDT:USDT', 'limit', 'buy', 0.1, 220, params)
```

**Comment by egabosh** [comment]
Ah, OK. Thank you. Seems to work.
