### ISSUE TITLE
Coinmarketcap ACC: ACChain vs Accelerator Network vs AdCoin conflict

### ISSUE THREAD

**Issue by etatto** [ccxt/ccxt#2441]
Latest version of CCXT

The symbol ACC is not unique in Coinmarketcap, 3 coins/tokens share the same:
- ACChain: https://coinmarketcap.com/currencies/acchain/
- Accelerator Network: https://coinmarketcap.com/currencies/accelerator-network/
- AdCoin: https://coinmarketcap.com/currencies/adcoin/

So only the first (ACChain) is present in the output of fetchTickers.

**Comment by kroitor** [comment]
Will fix shortly, thanks for reporting!
