### ISSUE TITLE
Bitso: Invalid Nonce or Invalid Credentials (0215 Incorrect request signature)

### ISSUE THREAD

**Issue by c0dehunter** [ccxt/ccxt#24419]
### Programming Languages

PHP

### CCXT Version

4.4.35

### Description

It seems the [sign()](https://github.com/ccxt/ccxt/blob/master/php/bitso.php#L1741) function for Bitso exchange isn't correctly signing the request. We are getting error:

`[Bitso Exchange Error] {\"success\":false,\"error\":{\"message\":\"Invalid Nonce or Invalid Credentials\",\"code\":\"0215\",\"details\":[],\"errorData\":null}}`

As per [Bitso API docs](https://docs.bitso.com/bitso-api/docs/authentication-error-02-http-401):
`0215 Incorrect request signature`

https://docs.bitso.com/bitso-api/docs/create-signed-requests

We created a fresh API key just to be sure, and it's the same issue.

### Code

```
$id = "\\ccxt\\bitso";
$exchange = new $id();
$exchange->apiKey = $key;
$exchange->secret= $secret;
$exchange->enableRateLimit = true;
$exchange->load_markets();
var_dump($exchange->fetch_balance()));
```

**Comment by yzh-pelle** [comment]
Hi @c0dehunter!
Thank you for your report!
We are working on it.
