### ISSUE TITLE
Issue with auth on Paradex

### ISSUE THREAD

**Issue by Scribulus** [ccxt/ccxt#24442]
### Operating System

widows

### Programming Languages

Python

### CCXT Version

4.3.35

### Description

Paradex on ccxt uses privateKey to auth, create JWT token etc.
Sometimes the starknet privatekey can be 63 length (65 with "0x" prefix). I believe it can causes issues with ccxt code that expects an hexadecimal key : "binascii.Error: Non-base16 digit found" when trying to retrieve balance of the account.

ccxt\async_support\paradex.py", line 914 :
```
    def sign_message(self, message, privateKey):
        return self.sign_hash(self.hash_message(message), privateKey[-64:])
```
you can see the [-64] that doesn't work with 65 len privatekeys
I tried replacing "0x" by "0x0" to have a hexadecimal key but it leads to an error : ccxt.base.errors.BadRequest: paradex {"error":"NOT_ONBOARDED","message":"user has never called the /onboarding endpoint"}
while the paradex account already exists so the user should be already onboarded I guess.

I don't understand everything of this but what I am almost sure is that I get a privateKey with a length of 65 and without any modifications, it may not be suited for the signature fonctions that expects a 66 length:

ccxt\async_support\paradex.py"
```
    def sign_hash(self, hash, privateKey):
        signature = self.ecdsa(hash[-64:], privateKey[-64:], 'secp256k1', None)
        r = signature['r']
        s = signature['s']
        v = self.int_to_base16(self.sum(27, signature['v']))
        return '0x' + r.rjust(64, '0') + s.rjust(64, '0') + v

    def sign_message(self, message, privateKey):
        return self.sign_hash(self.hash_message(message), privateKey[-64:])
```

thank you

**Comment by carlosmiei** [comment]
@Scribulus Btw, can you try to provide the private key of the ETH address and not the paradex private key?

**Comment by carlosmiei** [comment]
@Scribulus Right now we're using the ETH PK to derive the starknet private key, but ideally we should support both and we're checking if that is possible.

**Comment by Scribulus** [comment]
@carlosmiei ok,  I guess the ETH private key is required for "onboarding" to paradex from ccxt.  but if the user onboard manually on the paradex app and can sign transaction with the paradex private key and the ETH wallet address only it could be better for the wallet security.

**Comment by carlosmiei** [comment]
@Scribulus I agree,  we will do our best to support both and avoid having to use the main wallet pk

**Comment by Scribulus** [comment]
thank you for the fast support !

**Comment by carlosmiei** [comment]
@Scribulus Np, just let us know if anything! 🙂

**Comment by Scribulus** [comment]
@carlosmiei Do you know if subaccounts and/or vault are available with ccxt. tried a few keys in options dict  like "account", "subaccount" when connecting or using get balance but nothing.
Is it the right place to ask ?
