### ISSUE TITLE
fetch_order_book response data returning empty timestamp and datetime fields

### ISSUE THREAD

**Issue by TastyFeets** [ccxt/ccxt#2444]
- OS: win 8
- Programming Language version: python
- CCXT version:  ccxt==1.12.72
- Exchange: binance, gdax
- Method:  fetch_order_book
- Issue: 
Data returned from fetch_order_book is successful.  However the timestamp and datetime fields are None

`
import utils_accounts

if __name__ == "__main__":
  symbol    =   'ETH/BTC'
  
  client    =   utils_accounts.binance_trader()
  stream    =   client.fetch_order_book(symbol,5)
  print("binance")
  print(stream)
  
  client    =   utils_accounts.gdax()
  stream    =   client.fetch_order_book(symbol,5)  
  print("gdax")
  print(stream)
`

Sample output

binance
{'bids': [[0.054808, 0.001], [0.054805, 3.8], [0.054803, 0.347], [0.054802, 0.354], [0.054797, 0.056]], 'nonce': 177492815, 'asks': [[0.054865, 0.33], [0.054866, 2.999], [0.054894, 1.75], [0.054906, 0.395], [0.054922, 0.107]], **'timestamp': None, 'datetime': None**}

gdax
{'bids': [[0.05488, 52.6686706], [0.05485, 0.24549401], [0.05484, 22.0], [0.05481, 65.81], [0.05479, 0.5], [0.05478, 20.3], [0.05477, 0.2], [0.05476, 4.9168693], [0.05475, 1.42697849], [0.05474, 53.34], [0.05473, 457.253928], [0.05472, 24.21], [0.05471, 3.5], [0.0547, 24.17833863], [0.05469, 0.060643], [0.05468, 2.9936
], [0.05467, 5.0], [0.05466, 29.110318], [0.05465, 0.23773384], [0.05464, 0.1], [0.05463, 5.0], [0.05462, 0.10380813], [0.05461, 10.0], [0.0546, 8.0892835], [0.05459, 0.77895505], [0.05458, 8.61155], [0.05456, 0.05013871], [0.05455, 1.02018607], [0.0545, 0.03043487], [0.05449, 3.62733], [0.05447, 1.0], [0.05446, 0.38380143], [0.05445, 0.01202204], [0.05443, 0.05013429], [0.05441, 3.683763], [0.0544, 0.02039889], [0.05438, 444.580778], [0.05437, 126.675], [0.05436, 88.0], [0.05434, 0.09919652], [0.05432, 0.2], [0.05431, 20.43510122], [0.0543, 0.08049273], [0.05426, 5.0], [0.05425, 0.02], [0.05423, 0.32501451], [0.05422, 0.09919652],[0.0542, 33.37933084], [0.05419, 0.10101007], [0.05416, 0.77565]], 'nonce': None, 'asks': [[0.05489, 2.79480849], [0.0549, 47.51841894], [0.05491, 1.94], [0.05493, 0.1], [0.05494, 5.60919652], [0.05495, 1.279921], [0.05496, 1.546856], [0.05498, 0.03], [0.05499, 0.07008694], [0.055, 16.75800052], [0.05501, 24.534321], [0.05502, 28.69], [0.05503, 10.0], [0.05504, 19.57105016], [0.05505, 4.41576552], [0.05506, 1.09919652], [0.05507, 1.0], [0.05508, 52.78], [0.05509, 53.58], [0.0551, 58.0], [0.05511, 0.54608068], [0.05514, 50.0], [0.05516, 47.4252], [0.05518, 1.10905552], [0.05519, 0.0444], [0.0552, 7.57839513], [0.05521, 1.0], [0.05525, 100.438], [0.05526, 1.0], [0.05528, 0.0444], [0.05529, 4.359321], [0.0553, 2.35122855], [0.05534, 1.0], [0.05535, 0.02], [0.05537, 1.0], [0.0554, 11.53902], [
0.05541, 126.675], [0.05542, 0.09915752], [0.05545, 11.0], [0.05548, 0.1967629], [0.0555, 162.27049406], [0.05551, 10.53903], [0.05555, 23.0], [0.05556, 0.030321], [0.05558, 0.18755501], [0.0556, 25.77515994], [0.05563, 33.7959127], [0.05565, 45.1], [0.05567, 0.04676108], [0.05568, 0.01]], **'timestamp': None, 'datetime': None**}

**Comment by kroitor** [comment]
This is documented here: https://github.com/ccxt/ccxt/wiki/Manual#order-book

> The timestamp and datetime may be missing (undefined/None/null) if the exchange in question does not provide a corresponding value in the API response.

Let us know if this does not help. Thx!

**Comment by TastyFeets** [comment]
I've had an app running continuously for the last week or so - it has been recording the orderbook and timestamp information every 2 seconds to now.  The timestamp information is valid and not None.  

So this feature was working in a previous version of ccxt and timestamp data is being provided by binance at least.  But the version I just updated to appears to not provide this value.

**Comment by kroitor** [comment]
> I've had an app running continuously for the last week or so - it has been recording the orderbook and timestamp information every 2 seconds to now. The timestamp information is valid and not None.

It was a mistake in the library, and the timestamp was generated on client side. This has been fixed recently, and we don't set the timestamp and datetime on client side anymore. Thus, if the exchange does not send it, the timestamp is expected to be None. Binance does not send the timestamp in an orderbook reply. If you want to get the previous behaviour, you should just generate the timestamp on your side upon receiving the orderbook. They send a nonce number instead of the timestamp. Hope it answers your question.

**Comment by TastyFeets** [comment]
Thanks for your help!
