### ISSUE TITLE
Hyperliquid incorrect baseId for coins on spot

### ISSUE THREAD

**Issue by Ripll** [ccxt/ccxt#24464]
### Operating System

Windows

### Programming Languages

Python

### CCXT Version

4.4.36

### Description

Critical bug, placing an order on one pair leads to placing an order on another pair. How to reproduce: try to buy HYPE/USDC on a spot.

The bug is in the fetch_spot_markets function,

`baseId = self.number_to_string(i + 10000)`

the correct value would be

`baseId = self.number_to_string(index + 10000)`

There may be an error on futures, `i` is used there too

### Code

```
  

```

**Comment by sc0Vu** [comment]
@Ripll Thanks, I'll fix this asap.

**Comment by carlosmiei** [comment]
@Ripll Thanks a lot for your report.

Can you please upgrade your ccxt version (4.4.37) and try again? It should be working as expected now
