### ISSUE TITLE
hello,  How do I download transfer history from spot <-> futures

### ISSUE THREAD

**Issue by pstanek** [ccxt/ccxt#24490]
### Description

hello,

How do I download transfer history from spot <-> futures from 2021? Is it possible...?

thanks

### Code

    async function fetchAllTransfers() {
        try {
     

            const transferTypes = [
                'MAIN_UMFUTURE', 
                'UMFUTURE_MAIN', 
                'MAIN_MARGIN',  
                'MARGIN_MAIN'  
            ];

            let allTransfers = [];
            const now = Date.now();
            const maxInterval = 30 * 24 * 60 * 60 * 1000; 

            for (const type of transferTypes) {
                let params = { type, startTime: 0 };

                while (params.startTime < now) {
                    const transfers = await binance.sapiGetAssetTransfer({
                        ...params,
                        endTime: Math.min(params.startTime + maxInterval, now),
                    });

                    allTransfers.push(...transfers.rows);

                    if (!transfers.rows.length) break;

                    params.startTime = transfers.rows[transfers.rows.length - 1].timestamp + 1;
                }
            }

            console.log('All transfers:', allTransfers);
            return allTransfers;
        } catch (error) {
            console.error('Error fetching transfers:', error);
        }
    }

    fetchAllTransfers();

Error fetching or saving deposits: Error [ExchangeError]: binance {"code":-5026,"msg":"Start time query records range is too large"}

**Comment by sc0Vu** [comment]
@pstanek **The api supports query within the last 6 months only** https://developers.binance.com/docs/wallet/asset/query-user-universal-transfer.

I don't think you can download history data from 2021.

**Comment by pstanek** [comment]
yes there is a 6 month limit..
thanks
