### ISSUE TITLE
Alpaca: wrong URL (for sandbox / paper)

### ISSUE THREAD

**Issue by vd3d** [ccxt/ccxt#24507]
### Programming Languages

JavaScript, Python, PHP

### Description

Hi,

I'm testing CCXT and noticed that in "sandbox" mode it try to reach a URL that does not exists:
https://data.sandbox.alpaca.markets

The right URLs for Alpaca are:

Paper/sandbox: https://paper-api.alpaca.markets/
Live : https://api.alpaca.markets/

For example I try to get the OHCLV and it try to connec to : 

https://data.sandbox.alpaca.markets/v1beta3/crypto/us/bars?symbols=DOGE%2fUSD&limit=200&start=2021-02-09&timeframe=1W

But I got a : 403 Forbidden

**Comment by carlosmiei** [comment]
Hello @vd3d, 

Right now, ccxt uses 3 different endpoints for the sandbox, depending on the API:

```Javascript
                'api': {
                    'broker': 'https://broker-api.{hostname}',
                    'trader': 'https://api.{hostname}',
                    'market': 'https://data.{hostname}',
                },
                'test': {
                    'broker': 'https://broker-api.sandbox.{hostname}',
                    'trader': 'https://paper-api.{hostname}',
                    'market': 'https://data.sandbox.{hostname}',
                },
```

but we will check if the market/data API needs to be updated.

**Comment by carlosmiei** [comment]
@vd3d After testing it, I think that we should still use the mainnet for the `market` API ( 'market': 'https://data.{hostname}',)

**Comment by vd3d** [comment]
Thanks @carlosmiei 

Indeed you're right, sorry for the confusion, the URL I provided are for trading.

So, I do not know why I have such issue with the "sandbox" market data.

Maybe a solution would be to use https://data.alpaca.markets/ in all situations ? (Do we really need to target the sandbox for market data). Because in "non sandbox" mode I do not have such issue!

Any idea ?

**Comment by carlosmiei** [comment]
@vd3d If you update your ccxt version it should be working now.

Ans yes i think that even in the sandbox mode we should use the mainnet URL for data.

**Comment by vd3d** [comment]
Indeed. Thanks a lot @carlosmiei :-)
