### ISSUE TITLE
Unable to fetch few symbols from Binance: YOYO, NANO

### ISSUE THREAD

**Issue by dudycooly** [ccxt/ccxt#2450]
- OS: MacOS 10.12
- Programming Language version: Python 2.7
- CCXT version:  1.12.63
- Exchange: Binance
- Method: fetch_ticker

```
binance.fetch_ticker("YOYO/BTC").get('close')
```
produces the following error:

```
 File ccxt/base/exchange.py", line 281, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeError: binance No market symbol YOYO/BTC
```
Notice this error for pairs : ["YOYO/BTC", "YOYO/ETH", "NANO/BTC", "NANO/ETH"]

May be due to these ...??

```
ccxt/binance.py:262
            'commonCurrencies': {
                'YOYO': 'YOYOW',
                'BCC': 'BCH',
                'NANO': 'XRB',
            },
```

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/2364
