### ISSUE TITLE
Coinbase Advanced Auth

### ISSUE THREAD

**Issue by kenchambers** [ccxt/ccxt#24500]
### Operating System

Mac OS Sonoma 14.2.1

### Programming Languages

Python

### CCXT Version

4.4.37

### Description

After trying everything i could locate about striping/regex parsing the string in all of the issues, I still can't get it to load:

```
-> version 4.4.37
Coinbase Advanced
Balance fetch error: Non-base16 digit found
Error type: <class 'binascii.Error'>
```

### Code

```
  exchange = ccxt.coinbase({
            'apiKey': "organizations/e72f9e93-1dff-457f-/apiKeys/473de34b-4fdb",
            'secret': "\nMHcCAQEEIESKUvu9+QHKHautoAoGCCqGSM49\nAwEHoUpqS+c0CKs4\nwcTyqj3bgtp714l+jGnvX2DmsF0iH5Ob+g==\n-----END EC PRIVATE KEY-----\n",

```

**Comment by sc0Vu** [comment]
@kenchambers Could you please check your key are in this format:

```
'apiKey': 'organizations/xxxxxxx/apiKeys/xxxxxx',
'secret': '-----BEGIN EC PRIVATE KEY-----\xxxxxxxxxxxxxxxx\n xxxxxxxxxxxxxxxx\n xxxxxxxxxxxxxxxx\n-----END EC PRIVATE KEY-----\n'
```

**Comment by kenchambers** [comment]
yes it's in that exact format

**Comment by kenchambers** [comment]
just got it to work, the only thing i did was add python-dotenv , i don't think it could be related maybe i had a typo the first time?
