### ISSUE TITLE
Issues with watch_my_trades() for Bybit

### ISSUE THREAD

**Issue by algosfox** [ccxt/ccxt#24515]
### Operating System

Ubuntu 22

### Programming Languages

Python

### CCXT Version

4.4.38

### Description

When using the `self.exchange.watch_my_trades()` function for Bybit, I observed inconsistent behavior between WebSocket (WS) and REST API. Here are the details:

**Expected Response for Regular Trades:**
For a standard trade, the WebSocket returns a response like this:

```
{
    "id": "aaf2c612-3290-5730-a153-e35fa2667cfb",
    "info": {
        "category": "linear",
        "symbol": "OPUSDT",
        "closedSize": "0",
        "execFee": "0.00055992",
        "execId": "aaf2c612-3290-5730-a153-e35fa2667cfb",
        "execPrice": "2.2219",
        "execQty": "1.8",
        "execType": "Trade",
        "execValue": "3.99942",
        "feeRate": "0.00014",
        "markPrice": "2.2227",
        "leavesQty": "0",
        "orderId": "98616de0-6e77-4019-a689-5d7fa5d4ed34",
        "orderPrice": "2.2219",
        "orderQty": "1.8",
        "orderType": "Limit",
        "side": "Buy",
        "execTime": "1733905369291",
        "isMaker": true
    },
    "timestamp": 1733905369291,
    "datetime": "2024-12-11T08:22:49.291Z",
    "symbol": "OP/USDT:USDT",
    "order": "98616de0-6e77-4019-a689-5d7fa5d4ed34",
    "type": "limit",
    "side": "buy",
    "takerOrMaker": "maker",
    "price": 2.2219,
    "amount": 1.8,
    "cost": 3.99942,
    "fee": {
        "cost": 0.00055992,
        "currency": "USDT",
        "rate": 0.00014
    }
}
```

**Unexpected Response for All Open Positions:**
However, sometimes the WebSocket simultaneously returns data for all open positions that appears related to funding calculations rather than an actual trade. For example:

```
{
    "id": "4534806d-642d-4062-b6e6-7f2c277bff03",
    "info": {
        "category": "linear",
        "symbol": "OPUSDT",
        "execFee": "0.00039244",
        "execId": "4534806d-642d-4062-b6e6-7f2c277bff03",
        "execPrice": "2.1802",
        "execQty": "1.8",
        "execType": "Funding",
        "execValue": "3.92436",
        "feeRate": "0.0001",
        "markPrice": "2.1802",
        "orderId": "f6c6d011-42d6-4d75-bc07-db5117bef3ec",
        "side": "Buy",
        "execTime": "1733904000000",
        "isMaker": false
    },
    "timestamp": 1733904000000,
    "datetime": "2024-12-11T08:00:00.000Z",
    "symbol": "OP/USDT:USDT",
    "order": "f6c6d011-42d6-4d75-bc07-db5117bef3ec",
    "type": None,
    "side": "buy",
    "takerOrMaker": "taker",
    "price": 2.1802,
    "amount": 1.8,
    "cost": 3.92436,
    "fee": {
        "cost": 0.00039244,
        "currency": "USDT",
        "rate": 0.0001
    }
}
```

1. Data Inconsistency Between REST and WebSocket:
These funding-related events are not returned when querying the REST API using `self.exchange.fetch_my_trades(strat['symbol'])`.

2. Nonexistent Trades in WebSocket Data:
The WebSocket seems to treat funding fee calculations (`execType: Funding`) as trades, which introduces confusion since no actual trade occurred.

Issues:
There are inconsistencies between REST and WebSocket data, which complicates consistent trade data processing.
WebSocket responses include events (e.g., execType: Funding) that do not represent actual trades, which can cause processing errors.

Could you confirm if `execType: Funding` events are intentionally included in the `watch_my_trades()` responses?
If this is by design, is there a recommended way to distinguish these events from real trades to prevent misclassification?
It would be helpful to ensure alignment between REST and WebSocket data for trade-related queries.
Thank you for your guidance and support!

### Code

```
  

```

**Comment by algosfox** [comment]
Here is the raw text response without formatting:

{'id': 'aaf2c612-3290-5730-a153-e35fa2667cfb', 'info': {'category': 'linear', 'symbol': 'OPUSDT', 'closedSize': '0', 'execFee': '0.00055992', 'execId': 'aaf2c612-3290-5730-a153-e35fa2667cfb', 'execPrice': '2.2219', 'execQty': '1.8', 'execType': 'Trade', 'execValue': '3.99942', 'feeRate': '0.00014', 'tradeIv': '', 'markIv': '', 'blockTradeId': '', 'markPrice': '2.2227', 'indexPrice': '', 'underlyingPrice': '', 'leavesQty': '0', 'orderId': '98616de0-6e77-4019-a689-5d7fa5d4ed34', 'orderLinkId': '', 'orderPrice': '2.2219', 'orderQty': '1.8', 'orderType': 'Limit', 'stopOrderType': 'UNKNOWN', 'side': 'Buy', 'execTime': '1733905369291', 'isLeverage': '0', 'isMaker': True, 'seq': 201307741610, 'marketUnit': '', 'execPnl': '0', 'createType': 'CreateByUser'}, 'timestamp': 1733905369291, 'datetime': '2024-12-11T08:22:49.291Z', 'symbol': 'OP/USDT:USDT', 'order': '98616de0-6e77-4019-a689-5d7fa5d4ed34', 'type': 'limit', 'side': 'buy', 'takerOrMaker': 'maker', 'price': 2.2219, 'amount': 1.8, 'cost': 3.99942, 'fee': {'cost': 0.00055992, 'currency': 'USDT', 'rate': 0.00014}, 'fees': [{'cost': 0.00055992, 'currency': 'USDT', 'rate': 0.00014}]}


{'id': '4534806d-642d-4062-b6e6-7f2c277bff03', 'info': {'category': 'linear', 'symbol': 'OPUSDT', 'closedSize': '0', 'execFee': '0.00039244', 'execId': '4534806d-642d-4062-b6e6-7f2c277bff03', 'execPrice': '2.1802', 'execQty': '1.8', 'execType': 'Funding', 'execValue': '3.92436', 'feeRate': '0.0001', 'tradeIv': '', 'markIv': '', 'blockTradeId': '', 'markPrice': '2.1802', 'indexPrice': '', 'underlyingPrice': '', 'leavesQty': '0', 'orderId': 'f6c6d011-42d6-4d75-bc07-db5117bef3ec', 'orderLinkId': '', 'orderPrice': '0', 'orderQty': '0', 'orderType': 'UNKNOWN', 'stopOrderType': 'UNKNOWN', 'side': 'Buy', 'execTime': '1733904000000', 'isLeverage': '0', 'isMaker': False, 'seq': 201301404234, 'marketUnit': '', 'execPnl': '0', 'createType': ''}, 'timestamp': 1733904000000, 'datetime': '2024-12-11T08:00:00.000Z', 'symbol': 'OP/USDT:USDT', 'order': 'f6c6d011-42d6-4d75-bc07-db5117bef3ec', 'type': None, 'side': 'buy', 'takerOrMaker': 'taker', 'price': 2.1802, 'amount': 1.8, 'cost': 3.92436, 'fee': {'cost': 0.00039244, 'currency': 'USDT', 'rate': 0.0001}, 'fees': [{'cost': 0.00039244, 'currency': 'USDT', 'rate': 0.0001}]}

**Comment by sc0Vu** [comment]
Hi @algosfox, Thanks for your report. I'll check this and get back to you asap.

**Comment by carlosmiei** [comment]
@algosfox We just released a new version with the fix, can you upgrade and try again?
