### ISSUE TITLE
Question about watchOrderBook Response Behavior and Speed Optimization

### ISSUE THREAD

**Issue by cozy-hn** [ccxt/ccxt#24524]
### Operating System

ios

### Description

Hi,

I've noticed that the response time for watchOrderBook can vary significantly, especially for assets with lower trading volumes. From my observations, it seems like watchOrderBook only responds when there is a change in the order book. Is this correct?

Additionally, are there any recommendations or configurations to improve the response speed of watchOrderBook? Any guidance on this would be greatly appreciated.

Thank you!

### Code

```
  

```

**Comment by yzh-pelle** [comment]
Hi @cozy-hn  !

Response time and update frequency for watch... methods depends on the exchange (could vary greatly from one to another).
Some exchanges send updates periodically (regardless of the changes) while others only after the change in requested data.

There is no way in CCXT to speed up updates from the exchange.
You could close the connection by unWatchOrderBook() (if the exchange has this method) or close() (this method interrupts all connections with the exchange) and then call watchOrderBook() again - new connection will result the message from the exchange.

Also if the orderbook has no changes yet on the exchange's side, you do not need new updates. While connection exists CCXT cashes the data and changes, and you can get them in exchange.orderBooks[symbol].
