### ISSUE TITLE
okex: KeyError: 'avg_price' when fetch_order

### ISSUE THREAD

**Issue by StarsHu** [ccxt/ccxt#2452]
- OS: Mac OS
- Programming Language version: Python 3.6.2
- CCXT version: 1.12.76
- Exchange: okex(future)
- Method: fetch_order

```
File "/Users/my/venv/3.6venv/lib/python3.6/site-packages/ccxt/okcoinusd.py", line 463, in parse_order
    average = order['avg_price']
KeyError: 'avg_price'
```
Refer to [OKEX future API docs](https://github.com/okcoin-okex/API-docs-OKEx.com/blob/master/API-For-Futures-EN/REST%20API%20for%20FUTURES.md), the key of average deal price in okex spot is 'avg_price' but in okex future is 'price_avg'.

**Comment by kroitor** [comment]
![but-why](https://user-images.githubusercontent.com/1294454/38295579-17a0f0d4-37f7-11e8-9a01-8a16986ec9e2.jpg)
