### ISSUE TITLE
fetchOrderBook timestamp

### ISSUE THREAD

**Issue by Showgofar** [ccxt/ccxt#2454]
Hi 
Thank you for your great work.

- OS: Centos
- Programming Language version: PHP
- CCXT version: Latest (from 04.04.2018)
- Exchange: Binance Bittrex Poloniex
- Method: fetchOrderBook 

After update version of CCXT
there is no more timestamp in fetchOrderBook function
it returns
["timestamp"]=>   NULL   ["datetime"]=>   NULL

**Comment by kroitor** [comment]
Hi!

This questions is answered here: https://github.com/ccxt/ccxt/issues/2444

Hope it helps.
