### ISSUE TITLE
Gate.io - subscribing to custom ws channel

### ISSUE THREAD

**Issue by Jekamajor** [ccxt/ccxt#24541]
### Operating System

Windows 11

### Programming Languages

PHP

### CCXT Version

4.4.37

### Description

Hello! Is there a way to subscribe to a custom WebSocket channel through CCXT if this channel is not yet implemented in CCXT?
For example, I would like to subscribe to the "unified.asset_detail" channel with payload ["BTC","ETH"]: https://www.gate.io/docs/developers/unified/ws/en/#asset-detail-api
Thanks

### Code

```
#python example from api docs: 
ws = create_connection("wss://ws.gate.io/v4/ws/unified")
req = {
    "time": 1716796362,
    "channel": "unified.asset_detail",
    "event": "subscribe",
    "payload": ["BTC","ETH"],
    "auth": {
        "method": "api_key",
        "KEY": "xxxx",
        "SIGN": "xxxx"
    }
}
```

**Comment by sc0Vu** [comment]
@Jekamajor To subscribe a custom topic, I think you can extends gate class.

**Comment by Jekamajor** [comment]
@sc0Vu Thank you! I didn’t even think of this right away. The solution works. Here’s the code in case someone needs it.

`
class myGateioWs extends \ccxt\pro\gateio {
    public function __construct($options = array()) {
        parent::__construct($options);
    }
    public function watch_assets($params = array ()): PromiseInterface {
        return Async\async(function () use ($params) {
            Async\await($this->load_markets());
            $type = null;
            $subType = null;
            list($type, $params) = $this->handle_market_type_and_params('watchBalance', null, $params);
            $url = 'wss://ws.gate.io/v4/ws/unified';
            $requiresUid = ($type !== 'spot');
            $channel = 'unified.assets';
            $messageHash = $type . '.balance';
            return Async\await($this->subscribe_private($url, $messageHash, null, $channel, $params, $requiresUid));
        }) ();
    }
}`
