### ISSUE TITLE
Give order parameter "post only aka ParticipateDoNotInitiate" (Bitmex)(Python)

### ISSUE THREAD

**Issue by 4budab1** [ccxt/ccxt#2455]
- OS: Windows 10 x64
- Programming Language version: Python 3.6.4
- CCXT version: 1.12.54
- Exchange: Bitmex
- Method:

My function:
```
resultShort = bitmex.create_order(symbol='BTC/USD', type='limit', side='sell', amount=contracts_amount, price=ask)

```

How to add parameter **ParticipateDoNotInitiate** to my function?

```
```
> "description": "Optional execution instructions. Valid options: 
ParticipateDoNotInitiate, AllOrNone, MarkPrice, 
IndexPrice, LastPrice, Close, ReduceOnly, Fixed. 
'AllOrNone' instruction requires `displayQty` to be 0. 
'MarkPrice', 'IndexPrice' or 'LastPrice' instruction valid for 'Stop',
 'StopLimit', 'MarketIfTouched', and 'LimitIfTouched' orders.",
```

Order: New Order attributes:
Hidden Orders: Send a displayQty, where 0 <= displayQty < orderQty. A displayQty of 0 is a fully hidden order. You may partially hide an order by choosing a non-zero displayQty. When the order is hit, the non-hidden portion will be refilled, up to the order’s total quantity. Note that hidden orders incur the Taker fee.
Post-Only Orders: Any non-Market order may be made “Post-Only” by sending an execInst of ParticipateDoNotInitiate. This will reject the order if it would execute against the market, ensuring your order receives the Maker rebate. To prevent feeling out Hidden Orders, Post-Only Orders will still execute against Hidden Orders, but you will receive the Maker rebate as Hidden Orders always incur the Taker fee.
Time In Force: Valid options: Day, GoodTillCancel, ImmediateOrCancel, FillOrKill. Defaults toGoodTillCancel for Limit and StopLimit orders.
Simple Quantities: Send a simpleOrderQty instead of an orderQty to create an order denominated in the underlying currency. Useful for e.g. opening up a position with 1 XBT of exposure without having to calculate how many contracts it is.
```

**Comment by kroitor** [comment]
```Python
symbol = 'BTC/USD'
type = 'limit'
side = 'sell'
amount = contracts_amount
price = ask
params = {'execInst': 'ParticipateDoNotInitiate'} # ←---------------
#                                                                ↓↓↓
order = bitmex.create_order(symbol, type, side, amount, price, params)
```

Documented here: https://github.com/ccxt/ccxt/wiki/Manual#custom-order-params

Let us know if this does not answer your question.

**Comment by ichiban88** [comment]
hi I have been attempting to make a POST only order to bitmex. Code is:
params = {'execInst': 'ParticipateDoNotInitiate'}
order = bitmex.create_order(symbol, type, side, amount, price, params)
type is 'limit'
even when it is not close to live price it is entered and then bitmex cancels immediately with reason given that I entered an 'execInst' order. It worked previously and I have not knowingly changed anything so I am very puzzled. And btw, thanks for your great work on this project.
