### ISSUE TITLE
binance fetchAccounts() is not supported yet

### ISSUE THREAD

**Issue by cjhqyz** [ccxt/ccxt#24550]
### Operating System

windows 10

### Programming Languages

Python

### CCXT Version

4.4.39

### Description

Binance Exchange: Unable to retrieve account information under the Portfolio Margin mode. Please refer to the following Binance documentation:

https://developers.binance.com/docs/derivatives/portfolio-margin/account/Account-Information

### Code

```
  
exchange = ccxt.binance(
    {
        "apiKey": "xxxxx",
        "secret": "zzzzz",
    }
)
exchange.verbose = True
    
params = {
      "type": "papi",  # 'future', 'delivery', 'savings', 'funding', or 'spot' or 'papi'。papi for portfolio-margin
  }
balance = exchange.fetch_accounts(params=params)
return balance

```

**Comment by carlosmiei** [comment]
Hello @cjhqyz,

For now `fetch_accounts` is not available, but you can always call that endpoint through the implicit API by doing

```Python
response = exchange. papiGetAccount()
```

**Comment by cjhqyz** [comment]
Thank you @carlosmiei . 👍
