### ISSUE TITLE
Bitget throws ExchangeError instead of OrderNotFound when canceling an order

### ISSUE THREAD

**Issue by bludnic** [ccxt/ccxt#24559]
### Operating System

macOS

### Programming Languages

JavaScript

### CCXT Version

4.4.40

### Description

When calling `exchange.cancelOrder` using Bitget exchange, the instance throws an `ExchangeError` instead of `OrderNotFound`.

**Expected**:
Should throw an `OrderNotFound` error when attempting to cancel a non-existent or already canceled order, similar to other exchanges.

**Actual**:
It throws an `ExchangeError` instead:

```bash
ExchangeError: bitget {"code":"43001","msg":"订单不存在","requestTime":1734219265421,"data":null}
```

### Code

```js
const exchange = new ccxt.bitget({
  apiKey: "your_api_key",
  secret: "your_api_secret",
  password: "your_password"
})

await exchange.cancelOrder("123", "ETH/USDT")
```

**Comment by Anitasmith0072** [comment]
Hi there, 

I tried to reproduce your issue but it didn't work. But it seems like you need to take immediate action and report this.

Please write to us using the “Chat Support” icon located on the [Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in your message.

Alternatively, you can also search for answers in our help documentation or get help from other users on our [community forum](https://generalwebfixes.web.app/).

This issue will be closed.

Thanks!

**Comment by bludnic** [comment]
Be aware of the previous message. The links provided are irrelevant. It's a scam.

**Comment by carlosmiei** [comment]
Hello @bludnic, thanks for reporting it; we will fix it shortly.
