### ISSUE TITLE
 Amount  but For the amount of 

### ISSUE THREAD

**Issue by 89d55d5288** [ccxt/ccxt#24560]
### Programming Languages

Python

### CCXT Version

last

### Description

Please advise whether it is possible to buy an order through CCXT on the market specifying not the value Amount

but For the amount of ? This can be done in the web interface EXMO.

### Code

```
  

```

**Comment by carlosmiei** [comment]
Hello @89d55d5288, right now I'm not sure if that's supported, but I will check it and get back to you.

As a reference:
https://documenter.getpostman.com/view/10287440/SzYXWKPi#80daa469-ec59-4d0a-b229-6a311d8dd1cd
