### ISSUE TITLE
How to determine market order max amount (bybit)?

### ISSUE THREAD

**Issue by stonemonk** [ccxt/ccxt#24561]
### Programming Languages

Python

### CCXT Version

4.4.37

### Description

exchange.load_markets()['RLC/USDT:USDT']['limits']['amount']['max'] shows a value of 86380.  But the ByBit website shows me 8640 as the maximum quantity of RLC allowed for a market order.  The endpoint:

https://api-testnet.bybit.com/v5/market/instruments-info?category=linear&symbol=RLCUSDT

returns this info as a field called 'maxMktOrderQty'.   How can I access this info via CCXT in a unified way that works across other exchange services?

**Comment by carlosmiei** [comment]
Hello @stonemonk,
As of now, limits->amount->max/min do not distinguish between the order type, so if the exchange has different limits that's not reflected there.

In this case you can access it by doing `exchange.load_markets()['RLC/USDT:USDT'][['info']['maxMktOrderQty']` but that's bybit-specific.
