### ISSUE TITLE
python  Upgrade from 1.93.1 to 4.4.40 Binance issue

### ISSUE THREAD

**Issue by huyufan** [ccxt/ccxt#24576]
### Programming Languages

Python

### CCXT Version

1.93.1

### Description

use 1.93.1 error  {"code":-5000,"msg":"GET /fapi/v1/positionRisk is retired, please use GET /fapi/v2/positionRisk"}
If use 4.4.40 error  'binance' object has no attribute 'fapiPrivate_get_positionrisk'
Can I solve this problem by only upgrading the ccxt version without changing the code?

thank you

### Code

```
  exchange_class = getattr(ccxt, binance)
    exchange = exchange_class({
        'apiKey': api_key,
        'secret': secret_key,
        'password': passphrase,
        'timeout': 30000,
        'enableRateLimit': True,
        'options': {
            'createMarketBuyOrderRequiresPrice': False,
        },
    })
    infos = exchange.fapiPrivate_get_positionrisk({'symbol': symbol})
  

```

**Comment by carlosmiei** [comment]
Hello @huyufan,

Yes if you upgrade your ccxt version that issue will be fixed. BUt instead of `fapiPrivate_get_positionrisk ` you might need to call `exchange .fapiPrivateGetPositionRisk({'symbol': symbol})`

**Comment by huyufan** [comment]
I have many interfaces affected. What I mean is, can I solve the Binance issue by upgrading to a specific version, such as 2.2.0 (currently I don't know which version works), without upgrading to 4.4.40, and without modifying the code?

**Comment by huyufan** [comment]
I have many interfaces affected. What I mean is, can I solve the Binance issue by upgrading to a specific version, such as 2.2.0 (currently I don't know which version works), without upgrading to 4.4.40, and without modifying the code?

**Comment by carlosmiei** [comment]
@huyufan The thing is, that version is severely outdated and not recommended. I would suggest upgrading to a recent version and get in touch with us if you face any issues with the upgrade.

**Comment by huyufan** [comment]
@carlosmiei  ok. thank you!
