### ISSUE TITLE
Hyperliquid parseWsTrade uses tid instead of oid for id of orders

### ISSUE THREAD

**Issue by Philx0** [ccxt/ccxt#24571]
### Description

Creating an order with exchange.pro.hyperliquid returns an id from oid in  {'info': {'resting': {'oid': xxxxxxxx}}, but watchtrades
uses tid instead of oid, which is also available in the info object. using fetchOrder will work with id==oid, but not with id==tid

### Code
[https://github.com/ccxt/ccxt/blob/master/js/src/hyperliquid.js#L2391
](https://github.com/ccxt/ccxt/blob/master/js/src/hyperliquid.js#L2391
)
_No response_

**Comment by carlosmiei** [comment]
Hello @Philx0,

The tradeId and OrderId are different things right? Not sure what the issue is here. Each order is built using 1 or more trades, but orders and trades are different identities and they need to uniquely identifiable so the `tradeId` needs to be different from the `orderId`.
