### ISSUE TITLE
Coinnest PHP 

### ISSUE THREAD

**Issue by dimonpvt1236** [ccxt/ccxt#2457]
- OS: Linux
- Programming Language version: PHP
- CCXT version: 1.12.79
- Exchange: Coinnest
- Method: fetch_markets

I'm get error:

FatalThrowableErrorCall to undefined function ccxt\split()
--
in coinnest.php (line 78)
at coinnest->fetch_markets()in Exchange.php (line 1106)
at Exchange->load_markets()in TestController.php (line 27)
at TestController->index()

need fix it, please replace split to explode for php version

**Comment by kroitor** [comment]
Fixed in ccxt 1.12.80. Thx!

**Comment by dimonpvt1236** [comment]
Thanks
