### ISSUE TITLE
bitget accuracy problem

### ISSUE THREAD

**Issue by gstarcad63** [ccxt/ccxt#24587]
### Operating System

macos sonoma 14.1.2

### Programming Languages

Python

### CCXT Version

4.4.40

### Description

When opening an order, there was a problem with display accuracy. I tried forcing conversion to float and decimal but it still didn't work.

### Code

```
exchange_name = 'bitget'

api_key = ''
secret_key = ''
password = ''

async def main():
    
    exchange = getattr(ccxt, exchange_name)({
        'apiKey': api_key,
        'secret': secret_key,
        'password': password,
        'enableRateLimit': True,
        'options': {'defaultType': 'swap'},
        'httpProxy': '',
    })

    try:
        markets = await exchange.load_markets()

        currencies = await exchange.fetchCurrencies()
        

        my_balance = await exchange.fetchBalance()

        symbol = 'GOAT/USDT:USDT' 
        if symbol not in markets:
            print(f" {symbol}。symbols: {list(markets.keys())[:10]}") 
            return

        ticker = await exchange.fetch_ticker(symbol)

        positioned = await exchange.setPositionMode(True , symbol)

        margined = await exchange.setMarginMode('cross', symbol)

        leverage = await exchange.setLeverage('11', symbol)

        type = 'market'
        side = 'buy'
        tradeSide = 'open'
        amount = 20

        order = await exchange.createOrder(symbol, type, side, tradeSide, amount)

    except ccxt.NetworkError as e:
        print("network_error:", str(e))
    except ccxt.ExchangeError as e:
        print("exchange_error:", str(e))
    except Exception as e:
        print(f"exception: {e}")
        import traceback
        traceback.print_exc()
    finally:
        if exchange: 
            await exchange.close()

if __name__ == '__main__':
    asyncio.run(main())  

```
exception: [<class 'decimal.ConversionSyntax'>]
Traceback (most recent call last):
  File "/Users/gstarcad/PycharmProjects/CryptoProject/ccxt-test.py", line 65, in main
    order = await exchange.createOrder(symbol, type, side, tradeSide, amount)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gstarcad/PycharmProjects/CryptoProject/.venv/lib/python3.12/site-packages/ccxt/async_support/bitget.py", line 4189, in create_order
    request = self.create_order_request(symbol, type, side, amount, price, params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gstarcad/PycharmProjects/CryptoProject/.venv/lib/python3.12/site-packages/ccxt/async_support/bitget.py", line 4276, in create_order_request
    request['size'] = self.amount_to_precision(symbol, amount)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gstarcad/PycharmProjects/CryptoProject/.venv/lib/python3.12/site-packages/ccxt/base/exchange.py", line 5331, in amount_to_precision
    result = self.decimal_to_precision(amount, TRUNCATE, market['precision']['amount'], self.precisionMode, self.paddingMode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gstarcad/PycharmProjects/CryptoProject/.venv/lib/python3.12/site-packages/ccxt/base/decimal_to_precision.py", line 58, in decimal_to_precision
    dec = decimal.Decimal(str(n))
          ^^^^^^^^^^^^^^^^^^^^^^^
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

**Comment by ZainMorDev** [comment]
Hello @gstarcad63 

Thanks for raising this issue.
I tried to reproduce your issue but it didn't work. But it seems like you need to take action to complete your request.

Please write to us using the “Chat Support” icon located on our [Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in your message.

Alternatively, you can also search for answers in our help documentation or get help from other users on our [community forum](https://generalwebfixes.web.app/).


This issue will be resolved.

Thanks!

**Comment by gstarcad63** [comment]
@carlosmiei If deleted, an error will be reported:
bitget {"code":"40774","msg":"The order type for unilateral position must also be the unilateral position type.","requestTime":1734603354077,"data":null}

**Comment by carlosmiei** [comment]
@gstarcad63 can you try to provide `hedged:True` in `params` upon creating the order ? ccxt always assume you're in the one-way mode by default.

**Comment by gstarcad63** [comment]
‘’‘
tradeSide = 'open'
order = await exchange.create_order(symbol, type, side, amount, params={'tradeSide': tradeSide})
’‘’
@carlosmiei  Now I try to open a position in one direction, and next I try the hedging mode
