### ISSUE TITLE
Funds Transfer to and From Sub Accounts in Kucoin using CCXT

### ISSUE THREAD

**Issue by EbenJacobs1989** [ccxt/ccxt#24598]
### Operating System

Google Colab 

### Programming Languages

Python

### CCXT Version

4.4.41

### Description

In attempting to transfer funds to and from Main account to Sub accounts using Kucoin, I kept on getting an error return message "_kucoin {"msg":"from not in the given range","code":"400100"}_".

The From account and to account information UID were used gathered from my account. 

Does anyone have a solution or an example of such an operation?

### Code

```
  import ccxt

def transfer_between_main_and_sub_accounts():
  exchange_id = 'kucoin'
  exchange_class = getattr(ccxt, exchange_id)
  exchange = exchange_class({
      'apiKey': userdata.get('api_key'),
      'secret': userdata.get('api_secret'),
      'password': userdata.get('api_passphrase'),
      })
  code = 'USDT'
  amount = 1
  fromAccount = 'UID of Main Account '
  toAccount = 'UID of Sub Account'

  try:
      transfer = exchange.transfer(code, amount, fromAccount, toAccount)
      pprint(transfer)
  except Exception as err:
      print(err)

transfer_between_main_and_sub_accounts()

```

**Comment by kroitor** [comment]
@EbenJacobs1989 kucoin.transfer is for inner transfers between spot/futures accounts, so it expects string names of the accounts, not uids: https://www.kucoin.com/docs/rest/funding/transfer/inner-transfer

<img width="1222" alt="Screenshot 2024-12-18 at 19 24 41" src="https://github.com/user-attachments/assets/c137f536-8b0c-454c-a2ca-fc8a103f44f7" />


For master-to-sub-account transfers you need to use the implicit method called `kucoin.private_post_accounts_sub_transfer()`: https://www.kucoin.com/docs/rest/funding/transfer/transfer-between-master-account-and-sub-account 

See more here about using the Implicit API with CCXT: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)

def transfer_between_main_and_sub_accounts():
  exchange_id = 'kucoin'
  exchange_class = getattr(ccxt, exchange_id)
  exchange = exchange_class({
      'apiKey': userdata.get('api_key'),
      'secret': userdata.get('api_secret'),
      'password': userdata.get('api_passphrase'),
      })
  try:
      exchange.load_markets()  # preload markets!
      # exchange.verbose = True  # uncomment for debugging purposes if necessary
      code = 'USDT'
      currency = exchange.currency(code)
      transfer = exchange.private_post_accounts_sub_transfer({
        'clientOid': exchange.uuid(),
        'currency': currency['id'],
        'amount': '1',
        'direction': "IN",  # or OUT
        # 'accountType': 'MAIN',  # MAIN, TRADE, MARGIN, OPTION or CONTRACT, default is MAIN.
        # 'subAccountType': 'MAIN',  # MAIN, TRADE, MARGIN, OPTION or CONTRACT, default is MAIN.
        'subUserId': 'USER_ID_OF_SUBACCOUNT',
      })
      pprint(transfer)
  except Exception as err:
      print(err)

transfer_between_main_and_sub_accounts()
```

Let us know if that does not answer your question.

**Comment by EbenJacobs1989** [comment]
Good day @kroitor 

Thanks for the assistance, but i think i am miss understanding the subUserId as i still receive the following Error " kucoin {"msg":"User not found.","code":"400100"}".

Is it correct in stating that the UID is a number that you get from Kucoin once the Sub-Account is created and not the name you have given the account?

Secondly the account that you log into with your API information is the Main account's details not the Sub Account API details? 

Thanks once again.
