### ISSUE TITLE
OKX create order does not match web info

### ISSUE THREAD

**Issue by litonchen** [ccxt/ccxt#24590]
### Programming Languages

Python

### CCXT Version

4.3.23

### Description

I want to trade  perp isolated in okx, the simplied code is as below
My api order amount is 10, but the order information from the web is 100
The amount of my okx order does not match with the order from the web
How to resolve the problem?
```
okx = ccxt.okx(My API key)  
symbol = 'OM-USDT-SWAP'
okx.set_leverage(20, symbol, {"marginMode":"isolated","posSide":"net"})
response = okx.create_order(
    symbol=,
    type='limit',
    side='buy',
    amount=10,
    price=3.66,
    params={'hedged': False, 'tdMode': 'isolated', 'leverage': 20}
)
open_order  = okx.fetch_open_orders()[0]
print(open_order['amount'])
```
![OM](https://github.com/user-attachments/assets/071cb810-4e2a-4e49-92e2-97fd973dd975)

### Code

```
  

```

**Comment by litonchen** [comment]
I got the problem.
The contract size is 10
```
market = okx.market(symbol)
contractSize = market['contractSize']
```
The order is the the number of contract
If my order  is 10, it's mean 10 * 10 = 100 OM/USDT:USDT

**Comment by carlosmiei** [comment]
@litonchen Exactly, when trading contracts we always have to consider the `contractSize`
