### ISSUE TITLE
Fetching trades from binance gives a reversed list of trades

### ISSUE THREAD

**Issue by kingofclubstroy** [ccxt/ccxt#2460]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version: python 2.7
- CCXT version:
- Exchange: binance
- Method: fetch_trades

When fetching trades from binance it gives a list from oldest to newest trades. The other exchanges I have fetched trades from go from newest to oldest and for the longest time i thought binance just gave delayed data. Just thought you should be aware of that and potentially reverse the ordering. Either way i now compare the timestamps of trades on both ends to know which direction it's ordered

**Comment by kroitor** [comment]
> The other exchanges I have fetched trades from go from newest to oldest and for the longest time i thought binance just gave delayed data.

With current version of ccxt this is the actual correct ordering – from oldest to newest. Documented here: https://github.com/ccxt/ccxt/wiki/Manual#trades-executions-transactions

Hope it answers your question. Thx!

**Comment by kingofclubstroy** [comment]
I may have a older version but I just tested some other exchanges i have been working with, kucoin and kraken are reversed, but bittrex isn't. Just did a simple test comparing which end has the largest timestamp
 ie:  trades = bittrexCcxt.fetch_trades(market)
       if trades[0]['timestamp'] < trades[-1]['timestamp"]:
               print "bittrex is reversed"
       else:
              print "bittrex isn't reversed"

also compared with the exchange to confirm. This may have been resolved already, if so sorry for taking your time

**Comment by kroitor** [comment]
> This may have been resolved already

It is, you should just check your CCXT version and update CCXT first. As you may know this library is under active development, therefore we ask our users to update frequently.
