### ISSUE TITLE
BingX new endpoints

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#24607]
New endpoints, link structure has some difference from current endpoint. Can you add it please?

https://bingx-api.github.io/docs/#/en-us/common/sub-account#Query%20user%20API%20Key%20permissions

GET /openApi/v1/account/apiPermissions
GET /openApi/account/transfer/v1/subAccount/asset/transferHistory
POST /openApi/account/transfer/v1/subAccount/transferAsset/supportCoins
POST /openApi/account/transfer/v1/subAccount/transferAsset

**Comment by carlosmiei** [comment]
Hello @ndubel,

Thanks for reporting it, we will add them shortly.
