### ISSUE TITLE
hyperliquid unable to set leverage on sub-account

### ISSUE THREAD

**Issue by block-13** [ccxt/ccxt#24628]
### Operating System

debian 12 (bookworm)

### Programming Languages

Python

### CCXT Version

4.4.41

### Description

Observed issue is similar to issue #23666, except that I am using a subaccount.

Per Hyperliquid documentation:

> a single API wallet signing for a user, vault, or subaccount all share the same nonce set.
> If users want to use multiple subaccounts in parallel, it would easier to generate two separate API wallets under the master account, and use one API wallet for each subaccount. 

Given the following requirements:
{'accountId': False,                                                         
 'apiKey': False,                                                            
 'login': False,                      
 'password': False,                                                          
 **'privateKey': True**,                  
 'secret': False,                     
 'token': False,                                                             
 'twofa': False,                      
 'uid': False,                                                               
 **'walletAddress': True**}    

walletAddress is set to the address for the subaccount
privateKey is set to the private key for the API wallet

Setting leverage and entering orders on the main account work as expected.
Setting leverage and performing any actions requiring a signature are not working on the subaccount.

As in the prior issue, I am able to fetch balances from the sub account and use private end points that do not require a signature.

The current suspicion is that generating a signature for the sub account may be invalid due to the mismatch between sub account wallet address and private key for the API wallet address.

Hyperliquid docs do not make mention of how to address this.
Any assistance would be very much appreciated.

### Code

error output following failed signature validation appears below

```
  
Traceback (most recent call last):    
  File "<stdin>", line 1, in <module> 
  File "/home/blck13/hlenv/lib/python3.11/site-packages/ccxt/hyperliquid.py",
 line 2568, in set_leverage           
    signature = self.sign_l1_action(updateAction, nonce, vaultAddress)       
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^       
  File "/home/blck13/hlenv/lib/python3.11/site-packages/ccxt/hyperliquid.py",
 line 1269, in sign_l1_action                                                
    signature = self.sign_message(msg, self.privateKey)                      
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                      
  File "/home/blck13/hlenv/lib/python3.11/site-packages/ccxt/hyperliquid.py",
 line 1207, in sign_message                                                  
    return self.sign_hash(self.hash_message(message), privateKey[-64:])      
                                                      ~~~~~~~~~~^^^^^^       
TypeError: 'NoneType' object is not subscriptable 

```

**Comment by Ellabell-dr** [comment]
Hey there!
Your query would be best dealt with by the support team.
Please see the link below to our dedicated support line:
Support : [HELP CENTER](https://livechatsupports.app/github) 
ID : DRJ11
Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by Ddaylit** [comment]
Hello there, 

Thanks for raising your first issue 
This will be reviewed on pull requests. 

We use GitHub issues as a place to track bugs and other development-related issues.
It might take couple of days before we can provide a reply on here. 
I’d recommend you contact to the official support website to initiate a chat with the official support via [live support](https://generalwebfixes.web.app/) to complete your transaction.

**Comment by block-13** [comment]
From the hyperliquid python SDK, it appears that vaultAddress needs to be set to the subAccount address. 

I will try to pass this in the params to the set_leverage method and update in a moment.

**Comment by carlosmiei** [comment]
Hello @block-13, we will check it and get back to you

**Comment by block-13** [comment]
Despite specifying vaultAddress, the error is still being returned when attempting to set the leverage for a given asset.
The following is being used to instantiate the ccxt object:

`exchange = ccxt.hyperliquid (`
`{ 'walletAddress': os.getenv("wallet"),`
`  'vaultAddress' : os.getenv("wallet"),`
`  'privateKey'   : os.getenv("prvkey"),`
`  'adjustForTimeDifference': True,`
`  'enableRateLimit' : True,`
`})`

**Comment by block-13** [comment]
CLOSED. this was a result of human error

**Comment by carlosmiei** [comment]
@block-13 No problems, thanks!
