### ISSUE TITLE
ccxt.pro, watch_ohlcv_for_symbols, watch_ohlcv, limit=, doesn't work, only return 1 bar

### ISSUE THREAD

**Issue by williamyizhu** [ccxt/ccxt#24658]
### Operating System

Ubuntu 22.04.5 LTS

### Programming Languages

Python

### CCXT Version

4.4.43

### Description

limit=10, but only return 1 ohlcv bar, instead of 10 bar.

I have tried **binance** and **bybit**, not sure about other exchanges. 

```
{'BTC/USDT': {'1d': [[1735084800000, 98663.58, 98878.44, 97725.27, 98183.83, 4537.80694]]}}
{'LTC/USDT': {'5m': [[1735120800000, 109.47, 109.5, 109.15, 109.33, 1114.006]]}}
{'ETH/USDT': {'1h': [[1735120800000, 3494.99, 3496.0, 3492.0, 3496.0, 320.6144]]}}
```

### Code

```
import asyncio
import ccxt.pro as ccxtpro

cex = ccxtpro.binance()


async def task():
    await cex.load_markets()

    while True:
        # x = await cex.watch_ohlcv(symbol='ETH/USDT:USDT', timeframe='1h', limit=10)
        x = await cex.watch_ohlcv_for_symbols(symbolsAndTimeframes=[["BTC/USDT", "1d"], ["LTC/USDT", "5m"], ["ETH/USDT", "1h"]], limit=10)
        print(x)

asyncio.run(task())

```

**Comment by sc0Vu** [comment]
@williamyizhu I think the exchange push single kline data after subscribing the websocket stream https://developers.binance.com/docs/binance-spot-api-docs/web-socket-streams#klinecandlestick-streams-for-utc ccxt will cache data (you'll see 10 ohlcv data later).

Instead, you can use fetchOHLCVWs for spot symbol.

**Comment by williamyizhu** [comment]
Ok, fetch_ohlcv_ws works for binance spot symbol only. I think fetch_ohlcv is a more unified solution for both spot and derivatives.
