### ISSUE TITLE
Kucoin fetch_closed_orders

### ISSUE THREAD

**Issue by wybitnygracz** [ccxt/ccxt#2466]
I use newset cctx version. 
 
I recive table fe. 
array( 0=> array('ID' => 'ABC', trades => []), 1 => array('ID' => 'ABC', trades => []);

So there is separate position for every trade, with the same order ID. 

This array should be look like this ? 

array( 0=> array('ID' => 'ABC', trades => [0 => trade 1, 1=> trade2]));

**Comment by kroitor** [comment]
Can you please show your code and your **verbose** output according to these recommendations: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ? Without this info it's hard to actually understand the problem from your description:

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:
- Your code
- Your verbose output
