### ISSUE TITLE
createOrderPositionWithTakeprofitStoploss

### ISSUE THREAD

**Issue by azim1399** [ccxt/ccxt#24665]
### Operating System

windos

### CCXT Version

4.4.32

### Description

I used method "createOrderWithTakeProfitAndStopLoss" but in order objet stopLossPrice and takeProfitPrice and triggerPrice set null value.
If all items are given to it via parameters 

and order created in spot without stopLoss and profit

### Code

```
   Dictionary<string, object> parameters;

 parameters = new Dictionary<string, object>() {
     { "stopLoss", new Dictionary<string, object>() {
         { "triggerPrice", Math.Round(triggerStopPrice, 2) },
         { "stopLossPrice", Math.Round(stopPrice, 2) },
     }},
     { "takeProfit", new Dictionary<string, object>() {
         { "takeProfitPrice", Math.Round(profiteprice, 2) },
             
     }},
 };

 var order = exch.CreateOrder(symbol, orderType, side, amount, price, parameters).GetAwaiter().GetResult();

```

**Comment by carlosmiei** [comment]
Hello @azim1399,

WHat's the exchange?

`stopLoss/takeProfit` are different from `stopLossPrice/takeProfitPrice` the first are the ones used by `createOrderWithTakeProfitAndStopLoss` and it's used to place orders with attached tp+sl whereas the latter is used to place independent takeProfit/stopLoss orders

**Comment by azim1399** [comment]
Hello @carlosmiei 
Coinex Exchange
I want to create an order with a specific stop loss and a specific take profit, what method should I use?

**Comment by carlosmiei** [comment]
Hello @azim1399,

Coinex does not support that, you can see that `exch.Has["createOrderWithTakeProfitAndStopLoss"]` is `false`.


You need to place independent orders that will act as the takeProfit/stopLoss

**Comment by azim1399** [comment]
Hello @carlosmiei 
I used the following code in C# and it returned true for coinex
bool supportsTpSl = this.Exchange.has.ContainsKey("createOrderWithTakeProfitAndStopLoss");

Which of the following exchanges does it support?
Binance
Xt
Kucoin
Bingx

**Comment by carlosmiei** [comment]
@azim1399 

only Bingx supports it for perps
