### ISSUE TITLE
BloFin API - does not support SPOT market?

### ISSUE THREAD

**Issue by AltePfeife** [ccxt/ccxt#24675]
### Operating System

Linux Debian 12

### Programming Languages

Python

### CCXT Version

4.4.33

### Description

unfortunately there is no indication in the API documentation that the API does not support spot markets. when i execute load_markets(), it only returns the SWAP markets.
does anyone know a way to enable spot trading?

### Code

```
  
load_markets()
```

**Comment by carlosmiei** [comment]
Hello @AltePfeife,

No, afaik, blofin only supports swap trading through the API

**Comment by ubaidwazir** [comment]
But it looks like blofin does provide spot trades or maybe they updated their APIs?

**Comment by carlosmiei** [comment]
@ubaidwazir I don' think they support it on the API https://docs.blofin.com/index.html#public-data
