### ISSUE TITLE
Missing v2 account api in binance portfolio margin

### ISSUE THREAD

**Issue by luyiming** [ccxt/ccxt#24678]
### Operating System

Ubuntu

### Programming Languages

Python

### CCXT Version

4.4.43

### Description

Binance portfolio margin has added v2 account endpoint which offers better performance, which is not implemented yet.

https://developers.binance.com/docs/derivatives/change-log

> 2024-08-23
> Portfolio Margin
> 
> New Endpoints to Query Account Information:
> GET /papi/v2/um/account: Compared to GET /papi/v1/um/account, this endpoint only returns symbols that the user has positions or open orders in. Configuration-related fields have been removed and can now be queried from GET /papi/v1/um/symbolConfig and GET /papi/v1/um/accountConfig. The V2 endpoint also offers better performance.

I think the `fetch_account_positions()` method should also be updated to support v2 endpoint if possible.

**Comment by carlosmiei** [comment]
Hello @luyiming,

Thanks for reporting it, we will take a look.
