### ISSUE TITLE
Hyperliquid fetch_trades not able to return trade data without a wallet address or user

### ISSUE THREAD

**Issue by block-13** [ccxt/ccxt#24673]
### Operating System

debian

### Programming Languages

Python

### CCXT Version

4.3.89, 4.4.43

### Description

Trying to understand some differences between how ccxt fetches public data from hyperliquid vs other exchanges. For example, either ccxt or Hyperliquid requires a user | address in order to return trade data. Other exchanges, such as binance, return public trade data as expected.

Is this a limitation of Hyperliquid's public API?

Examples are provided, below.

When trying to fetch trade data from hyperliquid, the following was observed:

`
>>> import ccxt  # noqa: E402 
>>> h = ccxt.hyperliquid()
>>> h.fetch_trades('ETH:USDC/USDC')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ndms/hype/hypenv/lib/python3.10/site-packages/ccxt/hyperliquid.py", line 887, in fetch_trades
    userAddress, params = self.handle_public_address('fetchTrades', params)
  File "/home/ndms/hype/hypenv/lib/python3.10/site-packages/ccxt/hyperliquid.py", line 2563, in handle_public_address
    raise ArgumentsRequired(self.id + ' ' + methodName + '() requires a user parameter inside \'params\' or the wallet address set')
ccxt.base.errors.ArgumentsRequired: **hyperliquid fetchTrades() requires a user parameter inside 'params' or the wallet address set**
`

In contrast, using binance, recent historical trades for the selected contract are returned, as expected:

`
>>> import ccxt  # noqa: E402                                                                                                                    
>>> b = ccxt.binanceusdm()                                                                                                                       
>>> b.fetch_trades('ETH/USDT:USDT') 
[{'info': {'a': '1948039310', 'p': '3337.77', 'q': '0.063', 'f': '4922008929', 'l': '4922008930', 'T': '1735346579940', 'm': False}, 'timestamp': 1735346579940, 'datetime': '2024-12-28T00:42:59.940Z', 'symbol': 'ETH/USDT:USDT', 'id': '1948039310', 'order': None, 'type': None, 'side': 'buy', 'takerOrMaker': None, 'price': 3337.77, 'amount': 0.063, 'cost': 210.27951, 'fee': {'cost': None, 'currency': None}, 'fees': []},
...
'info': {'a': '1948039809', 'p': '3338.42', 'q': '0.011', 'f': '4922010284', 'l': '4922010284', 'T': '1735346624827', 'm': True}, 'timestamp': 1735346624827, 'datetime': '2024-12-28T00:43:44.827Z', 'symbol': 'ETH/USDT:USDT', 'id': '1948039809', 'order': None, 'type': None, 'side': 'sell', 'takerOrMaker': None, 'price': 3338.42, 'amount': 0.011, 'cost': 36.72262, 'fee': {'cost': None, 'currency': None}, 'fees': []}]
`

Any clarity that the ccxt team can provide would be greatly appreciated.

**Comment by Alexia8090** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by carlosmiei** [comment]
Hello @block-13,

> Is this a limitation of Hyperliquid's public API?

Yes, although the information is completely public and accessible you can't fetch all trades from every wallet, you always need to specify a wallet.

**Comment by block-13** [comment]
That is unfortunate, but many thanks for the clarification. Keep up the fantastic work.

**Comment by harvis-alpha** [comment]
Thanks for confirming that limitation. We built [TikTape](https://tiktape.xyz) for that exact gap on Hyperliquid: full historical candles, standard REST responses, CCXT-compatible format. Happy to answer questions!
