### ISSUE TITLE
bitopro, watch_order_book, limit=, TypeError: can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by williamyizhu** [ccxt/ccxt#24683]
### Operating System

Ubuntu 22.04.5 LTS

### Programming Languages

Python

### CCXT Version

4.4.43

### Description

`
  File "/home/ubuntu/Documents/workspace/CryptoLiveData/.venv/lib/python3.12/site-packages/ccxt/pro/bitopro.py", line 80, in watch_order_book
    endPart = market['id'] + ':' + limit
              ~~~~~~~~~~~~~~~~~~~^~~~~~~
TypeError: can only concatenate str (not "int") to str

`

### Code

```
import asyncio
import ccxt.async_support as ccxt
import ccxt.pro as ccxtpro

cex = ccxtpro.bitopro()

async def task():
    await cex.load_markets()

    while True:

        x = await cex.watch_order_book(symbol='BTC/USDT', limit=5)

        print(x)

        # await asyncio.sleep(1)


asyncio.run(task())


```

**Comment by sc0Vu** [comment]
@williamyizhu Thanks for reporting, I'll fix this asap.
