### ISSUE TITLE
Some exchange (e.g., okx, bybit) may fail to load_markets(), when running many coroutines

### ISSUE THREAD

**Issue by williamyizhu** [ccxt/ccxt#24695]
### Operating System

Ubuntu 22.04.5 LTS

### Programming Languages

Python

### CCXT Version

4.4.43

### Description

Some exchanges may fail to `load_markets()` when running many coroutines.

The error message is something like `RequestTimeout`,

`
ccxt.base.errors.RequestTimeout: independentreserve GET https://api.independentreserve.com/Public/GetOrderMinimumVolumes
`

But it works fine with fewer coroutines. 

### Code

```
import asyncio
import datetime as dt
import ccxt.async_support as ccxt
# import ccxt.pro as ccxt


async def load_markets(cex_name):
    cex: ccxt.Exchange = getattr(ccxt, cex_name)()

    try:
        await cex.load_markets()
        await cex.close()
        print(cex.id)

    except Exception as e:
        print(dt.datetime.today(), ">>>> %s <<<<" % cex.id, str(e))
        await cex.close()


async def task():
    exchange = ccxt.exchanges

    exchange.remove("alpaca")
    exchange.remove("idex")
    exchange.remove("kuna")
    exchange.remove("oxfun")
    exchange.remove("lykke")

    loop = []
    for cex_name in exchange:
        loop.append(load_markets(cex_name))

    await asyncio.gather(*loop)


if __name__ == "__main__":
    asyncio.run(task())

```

**Comment by carlosmiei** [comment]
Hello @williamyizhu,

When performing a lot of requests, depending on the network conditions/ server load/etc, some of them might fail, but we have a built-in retry mechanism that will retry automatically if the error is network-related.


You can check how to enable it here: https://docs.ccxt.com/#/README?id=retry-mechanism

**Comment by williamyizhu** [comment]
It works fine with multi threading version.

`
import threading
import ccxt

def task(cex_name: str):
    try:
        cex: ccxt.Exchange = getattr(ccxt, cex_name)()
        cex.load_markets()
        print(cex_name, len(cex.markets))
 
    except Exception as e: 
        print(">>>> %s <<<<" % cex_name, e)

exchange = ccxt.exchanges

dd: list[threading.Thread] = []
for cex_name in exchange:
    t = threading.Thread(target=task, args=(cex_name,))
    t.start()
    dd.append(t)

for t in dd:
    t.join()

`

**Comment by williamyizhu** [comment]
> Hello @williamyizhu,
> 
> When performing a lot of requests, depending on the network conditions/ server load/etc, some of them might fail, but we have a built-in retry mechanism that will retry automatically if the error is network-related.
> 
> You can check how to enable it here: https://docs.ccxt.com/#/README?id=retry-mechanism

This works, thank you.
