### ISSUE TITLE
lakebtc non-unified currencies  issue

### ISSUE THREAD

**Issue by alexsith** [ccxt/ccxt#2469]
Every fetch_balance method return upper-case currencies (BTC,LTC), but lakebtc's method use lower-case letters:

{'info': {'balance': {'btc': '0.0', 'usd': '0.0', 'eth': '0.0', 'ltc': '0.0', 'bch': '0.0', 'xrp': '0.0'}, 'locked': {'btc': '0.0', 'usd': '0.0', 'eth': '0.0', 'ltc': '0.0', 'bch': '0.0', 'xrp': '0.0'}, 'profile': {}, 'btc': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'usd': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'eth': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'ltc': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'bch': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'xrp': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'free': {'btc': 0.0, 'usd': 0.0, 'eth': 0.0, 'ltc': 0.0, 'bch': 0.0, 'xrp': 0.0}, 'used': {'btc': 0.0, 'usd': 0.0, 'eth': 0.0, 'ltc': 0.0, 'bch': 0.0, 'xrp': 0.0}, 'total': {'btc': 0.0, 'usd': 0.0, 'eth': 0.0, 'ltc': 0.0, 'bch': 0.0, 'xrp': 0.0}}

**Comment by kroitor** [comment]
@alexsith what's your version of ccxt? https://github.com/ccxt/ccxt/issues/1663
