### ISSUE TITLE
requests.exceptions.HTTPError: 504 Server Error: Gateway Timeout

### ISSUE THREAD

**Issue by ParleyHey** [ccxt/ccxt#2471]
Hi Igor, 

I keep having this error:

Traceback (most recent call last):
  File "C:\Users\Administrator\venv\lib\site-packages\ccxt\base\exchange.py", line 357, in fetch
    response.raise_for_status()
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Timeout for url: http://api.hitbtc.com/api/1/trading/[MYAPIKEY]

--- And also this one (another script on another computer):

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\base\exchange.py", line 347, in fetch
    response.raise_for_status()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http://api.hitbtc.com/api/1/public/EVXETH/orderbook

--- 

I have increased timeout, used a proxy, enabled nonce and rate limit, but I keep having this. 

I'm using Python 3.6, CCXT 1.12.88 and I have the below call:

hitbtc = ccxt.hitbtc({'verbose': True,
                      'timeout': 30000,
                      'nonce': ccxt.Exchange.milliseconds,
                      'enableRateLimit': True
                      })

What can I do?

Many thanks in advance and keep up your excellent work!

**Comment by kroitor** [comment]
Hi!

http://api.hitbtc.com/api/1/public/EVXETH/orderbook

↑ Is this URL available in your browser from the same machine?

**Comment by ParleyHey** [comment]
I get this: 1.12.31
And my Python version is 3.6.3 (Anaconda)

**Comment by kroitor** [comment]
> I always get this error in my script in less than an hour after it started to run

Ok, I see... you should just add the handling for networking exceptions, as any exchange will return a network error sooner or later. However, most network errors are tolerable and recoverable, so it's usually enough to catch the exception and retry the call later. The above behaviour is not related to rate-limiting, unless you're using the same key with two instances of the exchange class simultaneously. The error handling is documented here: https://github.com/ccxt/ccxt/wiki/Manual#error-handling

I would also recommend to use the built-in rate limiter:
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/tree/master/examples/py/

Let us know if it does not answer your question. Thx!

**Comment by ParleyHey** [comment]
Great thanks, I'll keep you posted
