### ISSUE TITLE
Kraken for Pyhton: lot attribute have been lost in markets in recent versions

### ISSUE THREAD

**Issue by iaverin** [ccxt/ccxt#2472]
- OS: Ubuntu 16.04
- Programming Language version: 3.53
- CCXT version: 1.12.24
- Exchange: kraken
- Method: amount_to_lots

when trying to call amount_to_lost in version 1.12  the following error appears:
 File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 829, in amount_to_lots
    lot = self.markets[symbol]['lot']
KeyError: 'lot'

kraken.py in 1.12 (no 'lot' key) :

https://github.com/ccxt/ccxt/blob/0dee28e5acbc2e2d2b140598a2730a9c6b5e0cf7/python/ccxt/kraken.py#L293 

vs kraken.py 1.10 ( 'lot' key is present) https://github.com/ccxt/ccxt/blob/5ce9bed06a844a7da1088ca8eea1ecae3e829ecb/python/ccxt/kraken.py#L287

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/issues/2465#issuecomment-378919689

> The lot size is not mentioned anywhere in the Manual, it is a deprecated field and it is to be removed, you should not rely on something that is not documented, really. We will use precision settings instead.

Hope this answers your question. Let us know if not. Thx!

**Comment by kroitor** [comment]
The precision functionality is currently being reworked here (partially merged already):

- https://github.com/ccxt/ccxt/pull/1635
- https://github.com/ccxt/ccxt/pull/2121
- https://github.com/ccxt/ccxt/pull/2171

Also related to this:

- https://github.com/ccxt/ccxt/issues/1483

**Comment by iaverin** [comment]
Thanks a lot!

**Comment by kroitor** [comment]
@iaverin more about it: https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits
