### ISSUE TITLE
exmo market_sell None type

### ISSUE THREAD

**Issue by doctord919** [ccxt/ccxt#2476]
- OS: Windows 8.1
- Programming Language version: python 3.6.4
- CCXT version: 1.12.54
- Exchange: exmo
- Method: create_market_sell_order(), may be create_market_buy_order()
Problems:
None type not float !!!
run create_market_sell_order() ...
next:
exchange.py:
    def create_market_sell_order(self, symbol, amount, params={}):
        return self.create_order(symbol, 'market', 'sell', amount, None, params) #None <- problems
next:
exmo.py
    def create_order(self, symbol, type, side, amount, price=None, params={}):
...
...
        request = {
            'pair': market['id'],
            'quantity': self.amount_to_string(symbol, amount),
            'price': self.price_to_precision(symbol, price), #<---- Problema!!! price = None !!!!
            'type': prefix + side,
        }

**Comment by kroitor** [comment]
Fixed in 1.12.95. Thx for reporting!
