### ISSUE TITLE
how to get level api in zb

### ISSUE THREAD

**Issue by haliluyaya** [ccxt/ccxt#2478]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: windows10
- Programming Language version: python3.6
- CCXT version: 1.12.82
- Exchange: zb
- Method:
zb provides some level api to  trade by level. such as [getLeverAssetsInfo api](https://trade.zb.com/api/getLeverAssetsInfo)
but I can not find them in ccxxt? Is it private api?

**Comment by haliluyaya** [comment]
lever api in zb are as follows:
[https://trade.zb.com/api/getLeverAssetsInfo](url)
[https://trade.zb.com/api/getLeverBills](url)
[https://trade.zb.com/api/transferInLever](url)
[https://trade.zb.com/api/transferOutLever](url)
[https://trade.zb.com/api/loan](url)
[https://trade.zb.com/api/cancelLoan](url)
[https://trade.zb.com/api/getLoans](url)
............
where could I find these api in ccxt?

**Comment by kroitor** [comment]
1. Update to ccxt version 1.12.97

2. See below:

```Python
import ccxt
exchange = ccxt.zb()
params = {}
echange.privateGetLoan(params)
echange.privateGetCancelLoan({})
echange.privateGetGetLoans({})

print(dir(exchange)) # prints all methods and properties
```

Documented here: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

Don't forget to update! )

**Comment by haliluyaya** [comment]
@kroitor thank you very much.
