### ISSUE TITLE
Binance Fetching of balances

### ISSUE THREAD

**Issue by SavosRU** [ccxt/ccxt#2479]
Hi!
I'm try to test Binance Balance and getting error...

My code is:
============
```
exchange = ccxt.binance({
    'apiKey': 'myREALapiKEYwasREMOVEDexactly;-)',
    'secret': 'myREALapiKEYwasREMOVEDexactly;-)',
})
try:
    myBalance = exchange.fetch_balance()
    dump(green(exchange.name), 'balance', myBalance)
except ccxt.DDoSProtection as e:
    print(type(e).__name__, e.args, 'DDoS Protection (ignoring)')
except ccxt.RequestTimeout as e:
    print(type(e).__name__, e.args, 'Request Timeout (ignoring)')
except ccxt.ExchangeNotAvailable as e:
    print(type(e).__name__, e.args, 'Exchange Not Available due to downtime or maintenance (ignoring)')
except ccxt.AuthenticationError as e:
    print(type(e).__name__, e.args, 'Authentication Error (missing API keys, ignoring)')
```
Error response is:
============
> ccxt.base.errors.ExchangeError: binance: unknown error code: {"code":-1022,"msg":"Signature for this request is not valid."} -1022

And other info is:
 ====================
- OS: Mac os X 10.13.3
- Programming Language version: Python 3.6.5
- CCXT version: 1.12.96
- Exchange: Binance
- Method: fetch_balance()
=====================

What I'm doing wrong? Thanks!

**Comment by kroitor** [comment]
Hi!

> What I'm doing wrong? 

Not following the [troubleshooting](https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting) section? )

The most likely reason is that your key has been already used with a different software and that software screwed your nonce numbers. The fix is easy: just create a fresh new unused key. Let us know if this does not help. Thx!

**Comment by SavosRU** [comment]
Спасибо! Я так и сделал - и все заработало!

**Comment by kroitor** [comment]
@SavosRU also, I would highly recommend to read the Manual, will save you tons of time in future, really: https://github.com/ccxt/ccxt/wiki/Manual )

**Comment by SavosRU** [comment]
@kroitor Yes, I reading it and will read again and again!
I just started to learn Python and CCXT so my way will be so long...
But I hope finish will be very happy. 
To All Your TEAM: 
Big thanks and regards! Your project - amazing! Nice job!
