### ISSUE TITLE
support of IP/socks/http proxy in node version of the ccxt library

### ISSUE THREAD

**Issue by sajjadhbutt2** [ccxt/ccxt#2480]
kroitor,
First of all, thanks and salute to your great work!!

I am looking for the ways to implement proxying the IP to send concurrent fetchOrderBook requests in node code (using promise.all).

you guided the methods in php (curl_option in #2302 ) and python (python proxing  in #906) versions, but I could not the find the same for node.js.

Currently I know php and node languages, and I will have to learn python for this feature if this is the case.

I don't want to use php either as it does not support asynch/concurrency, so node version is my only option. 

I save "Improved proxy support" and "WebSocket interfaces:" in your pending list, but can't wait for my project, please guide available options.

Highly appreciated

**Comment by kroitor** [comment]
Hi! )

> but can't wait for my project, please guide available options.

Available options:

1. You can pass your fetch implementation to the exchange constructor, and, basically, override everything you want in the networking internals, including proxies, tunnelAgents, etc...

```
const ccxt = require ('ccxt')
const yourImplementationOfFetchInterface = async function (url, options) {
    // you can set all options supported by Node fetch here
}
const exchange = new ccxt.kraken ({'fetchImplementation': yourImplementationOfFetchInterface})
```

2. You can pass the `agent` parameter to constructor to override it partially with just the proxying agent... 

https://www.npmjs.com/package/node-fetch#options

Let us know if this does not answer your question. Thx!

**Comment by kroitor** [comment]
https://www.npmjs.com/package/https-proxy-agent

```JavaScript
const ccxt = require ('ccxt')
const agent = require ('https-proxy-agent')
const proxy = process.env.http_proxy || 'http://168.63.76.32:3128' // HTTP/HTTPS proxy to connect to
const agent = new HttpsProxyAgent (proxy)
const kraken = new ccxt.exchange ({ agent })
```

**Comment by sajjadhbutt2** [comment]
Hello kroitor,

Thanks for the solutions, I am going to work on it as this is really a
life-saving help!

2 items I forgot to ask in the question:

1. Can Socks 5 be used in above solutions?  I don't have detailed
understanding on types of proxies.
2. I need to implement the unique proxy on every fetchOrderBook requests
for the same exchange... ie. Let's say I have 20 pairs in an exchange, I
will be rotating 20 unique/different proxies for each fetchOrderBook
request in for..loop with concurrency (promise.all)... please confirm if I
am correct.

Bunch of thanks.
