### ISSUE TITLE
Exmo: one more commonCurrencies item

### ISSUE THREAD

**Issue by dmig** [ccxt/ccxt#2481]
Exmo exchange lists fiat currency RUR as RUB. Other exchanges have it as RUR

ccxt version 1.12.97

**Comment by kroitor** [comment]
Looks like it's the opposite, most of them use RUB instead of RUR... Which one should prevail? )

<img width="1322" alt="screen shot 2018-04-06 at 20 09 21" src="https://user-images.githubusercontent.com/1294454/38434354-ae5137ec-39d6-11e8-8346-5eedc2534c82.png">

**Comment by kroitor** [comment]
Ok, will fix it shortly. Thx!
