### ISSUE TITLE
exmo market_sell None Type continue

### ISSUE THREAD

**Issue by doctord919** [ccxt/ccxt#2482]
and continue ...
OS: Windows 8.1
Programming Language version: python 3.6.4
CCXT version: 1.12.54
Exchange: exmo
Method: create_market_sell_order(), may be create_market_buy_order()
Problems:
None type not float !!!
run create_market_sell_order() ...
next:
exchange.py:
def create_market_sell_order(self, symbol, amount, params={}):
return self.create_order(symbol, 'market', 'sell', amount, None, params) #None <- problems
next:
exmo.py
def create_order(self, symbol, type, side, amount, price=None, params={}):
...
...
request = {
'pair': market['id'],
'quantity': self.amount_to_string(symbol, amount),
'price': self.price_to_precision(symbol, price), #<---- Problema!!! price = None !!!!
'type': prefix + side,
}
next Problem:
exmo.py:
    def create_order(self, symbol, type, side, amount, price=None, params={}):
        self.load_markets()
        prefix = (type + '_') if (type == 'market') else ''
        market = self.market(symbol)
        request = {
            'pair': market['id'],
            'quantity': self.amount_to_string(symbol, amount),
            'type': prefix + side,
        }
        if type == 'market':
            if price is None:
                request['price'] = 0 <--- ok!!!
        if price is not None:
            request['price'] = self.price_to_precision(symbol, price) <---- ok!!!!!
        response = self.privatePostOrderCreate(self.extend(request, params))
        id = self.safe_string(response, 'order_id')
        timestamp = self.milliseconds()
        price = float(price) <----------- price is None !!!! a nuzhno 0 dlya market_sell !!!
        amount = float(amount)
        status = 'open'
        order = {

**Comment by kroitor** [comment]
Plz update to version 1.12.97. This should be fixed already. Let us know if you still have difficulties with the most recent version of it. Thx!

**Comment by doctord919** [comment]
I update 1.12.97
and saw exmo.py create_order:
    def create_order(self, symbol, type, side, amount, price=None, params={}):
 ...
...
      if type == 'market':
            if price is None:
                request['price'] = 0 !!!ok
        if price is not None:
            request['price'] = self.price_to_precision(symbol, price) !!!ok
        response = self.privatePostOrderCreate(self.extend(request, params))
        id = self.safe_string(response, 'order_id')
        timestamp = self.milliseconds()
        price = float(price) !!! price = None for market_sell !!!!
