### ISSUE TITLE
changelogs

### ISSUE THREAD

**Issue by IlyaSleptsov** [ccxt/ccxt#2483]
Hello, guys! Thank you very much for your work. 
Could you please provide changelogs with new versions?
Last changelog - 10, new version - 12. Thank you.

**Comment by kroitor** [comment]
Yeah, the changelog is outdated, we think we are going to remove it, as we don't have enough time to actually log all the changes that are taking place in the library, therefore it's a tradeoff, and we have to choose between creating new functionality and fixing issues vs logging the changes and doing the paperwork. Unfortunately, the team is small, and just bringing the changelog up to date might require a week of human work...

- https://github.com/ccxt/ccxt/issues/76#issuecomment-361874596

Hope it answers your question. Feel free to reopen this if needed or just ask questions if any...

**Comment by kroitor** [comment]
Actual changelog: https://github.com/ccxt/ccxt/commits/master
