### ISSUE TITLE
fetchMyTrades: takerOrMaker property

### ISSUE THREAD

**Issue by mkutny** [ccxt/ccxt#2486]
I wonder if you find it viable adding `takerOrMaker` property to the trade structure returned by `fetchMyTrades` method.

I see it's used for fee calculation (where available) but its use is implicit, although `takerOrMaker` mode is determined and used for calculation it's never get stored in the trade.

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/1776 ;))
