### ISSUE TITLE
Quick Fix: EXX Exchange referencing a unique function (PrivateGetBalance). 

### ISSUE THREAD

**Issue by karlandoh** [ccxt/ccxt#2497]
Hey guys, another quick one. Thanks for your help.

OS: OSX El Capitan
Programming Language version: Python
CCXT version: 1.12.106
Exchange: EXX

In[0]: exx.fetchBalance()
Out[0]: 

exx.fetchBalance()

Request: GET https://api.exx.com/data/v1/markets {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.exx.com/data/v1/markets 200 {'Date': 'Sat, 07 Apr 2018 23:11:29 GMT', 'Server': 'Tengine/2.2.1', 'Content-Type': 'text/javascript;charset=utf-8', 'Transfer-Encoding': 'chunked', 'CNDServer': 'cache_server_1', 'Content-Encoding': 'gzip', 'X-Via': '1.1 PSxgHK6hx82:3 (Cdn Cache Server V2.0), 1.1 PSjndmtleMON1vm39:10 (Cdn Cache Server V2.0)', 'Connection': 'keep-alive'} {"etc_usdt":{"minAmount":"0.00010","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"ubtc_usdt":{"minAmount":"0.001","amountScale":3,"priceScale":2,"maxLevels":0,"isOpen":true},"sbtc_btc":{"minAmount":"0.00010","amountScale":3,"priceScale":5,"maxLevels":0,"isOpen":true},"chat_btc":{"minAmount":"0.0000010","amountScale":0,"priceScale":8,"maxLevels":0,"isOpen":true},"xuc_btc":{"minAmount":"0.001","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":true},"eos_eth":{"minAmount":"0.001","amountScale":2,"priceScale":5,"maxLevels":0,"isOpen":true},"sexc_eth":{"minAmount":"0.001","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":true},"epc_eth":{"minAmount":"0.00010","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":true},"bds_btc":{"minAmount":"0.0000010","amountScale":0,"priceScale":8,"maxLevels":0,"isOpen":true},"btm_btc":{"minAmount":"0.000010","amountScale":0,"priceScale":8,"maxLevels":0,"isOpen":true},"etc_eth":{"minAmount":"0.001","amountScale":3,"priceScale":5,"maxLevels":0,"isOpen":true},"ink_qc":{"minAmount":"0.00010","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"etc_qc":{"minAmount":"0.00010","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"gram_qc":{"minAmount":"0.000010","amountScale":4,"priceScale":4,"maxLevels":0,"isOpen":true},"gram_eth":{"minAmount":"0.000010","amountScale":0,"priceScale":8,"maxLevels":0,"isOpen":true},"qtum_hsr":{"minAmount":"0.01","amountScale":2,"priceScale":4,"maxLevels":0,"isOpen":true},"etc_hsr":{"minAmount":"0.001","amountScale":3,"priceScale":3,"maxLevels":0,"isOpen":true},"etc_btc":{"minAmount":"0.00010","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":true},"ink_btc":{"minAmount":"0.000010","amountScale":0,"priceScale":8,"maxLevels":3,"isOpen":true},"tsl_qc":{"minAmount":"0.00010","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"eth_hsr":{"minAmount":"0.001","amountScale":3,"priceScale":3,"maxLevels":0,"isOpen":true},"eth_btc":{"minAmount":"0.00010","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":true},"mona_qtum":{"minAmount":"0.001","amountScale":3,"priceScale":3,"maxLevels":0,"isOpen":true},"btc_usdt":{"minAmount":"0.00010","amountScale":4,"priceScale":2,"maxLevels":0,"isOpen":true},"qtum_eth":{"minAmount":"0.001","amountScale":3,"priceScale":5,"maxLevels":0,"isOpen":true},"spc_qc":{"minAmount":"0.01","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"btp_btc":{"minAmount":"0.00010","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":true},"etf_qc":{"minAmount":"0.00010","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"hld_hsr":{"minAmount":"0.001","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":true},"etp_qtum":{"minAmount":"0.01","amountScale":3,"priceScale":5,"maxLevels":3,"isOpen":true},"tv_btc":{"minAmount":"0.00010","amountScale":0,"priceScale":8,"maxLevels":0,"isOpen":true},"ltc_qc":{"minAmount":"0.01","amountScale":3,"priceScale":2,"maxLevels":0,"isOpen":true},"lch_usdt":{"minAmount":"0.00010","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"eth_qc":{"minAmount":"0.00010","amountScale":3,"priceScale":2,"maxLevels":0,"isOpen":true},"bds_qc":{"minAmount":"0.00010","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"vlc_qc":{"minAmount":"0.01","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"qbt_qtum":{"minAmount":"0.01","amountScale":2,"priceScale":5,"maxLevels":0,"isOpen":true},"hpy_hsr":{"minAmount":"0.001","amountScale":2,"priceScale":6,"maxLevels":5,"isOpen":true},"qash_eth":{"minAmount":"0.00010","amountScale":2,"priceScale":5,"maxLevels":0,"isOpen":true},"gram_btc":{"minAmount":"0.000010","amountScale":0,"priceScale":8,"maxLevels":0,"isOpen":true},"qbt_eth":{"minAmount":"0.001","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":true},"hsr_qc":{"minAmount":"0.01","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"spc_eth":{"minAmount":"0.00010","amountScale":0,"priceScale":6,"maxLevels":0,"isOpen":false},"ltc_btc":{"minAmount":"0.00010","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":true},"can_eth":{"minAmount":"0.00010","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":true},"ensa_btc":{"minAmount":"0.00010","amountScale":0,"priceScale":8,"maxLevels":0,"isOpen":false},"tsl_qtum":{"minAmount":"0.0000010","amountScale":2,"priceScale":4,"maxLevels":0,"isOpen":true},"vlc_eth":{"minAmount":"0.000010","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":true},"spc_btc":{"minAmount":"0.0000010","amountScale":0,"priceScale":8,"maxLevels":0,"isOpen":true},"btc_qc":{"minAmount":"0.00010","amountScale":4,"priceScale":2,"maxLevels":0,"isOpen":true},"bck_usdt":{"minAmount":"0.1","amountScale":4,"priceScale":2,"maxLevels":0,"isOpen":true},"qtum_usdt":{"minAmount":"0.01","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"bcc_btc":{"minAmount":"0.00010","amountScale":2,"priceScale":6,"maxLevels":3,"isOpen":true},"etf_btc":{"minAmount":"0.00010","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":true},"xwc_usdt":{"minAmount":"0.001","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"lbtc_btc":{"minAmount":"0.00010","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":true},"xwc_eth":{"minAmount":"0.00010","amountScale":2,"priceScale":5,"maxLevels":0,"isOpen":true},"epc_btc":{"minAmount":"0.00010","amountScale":0,"priceScale":8,"maxLevels":0,"isOpen":true},"xuc_eth":{"minAmount":"0.001","amountScale":3,"priceScale":5,"maxLevels":0,"isOpen":true},"ink_usdt":{"minAmount":"0.01","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":false},"xuc_usdt":{"minAmount":"0.1","amountScale":4,"priceScale":2,"maxLevels":0,"isOpen":true},"tv_qtum":{"minAmount":"0.01","amountScale":2,"priceScale":3,"maxLevels":0,"isOpen":true},"mona_hsr":{"minAmount":"0.001","amountScale":3,"priceScale":3,"maxLevels":0,"isOpen":true},"bck_btc":{"minAmount":"0.00010","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":true},"btm_eth":{"minAmount":"0.00010","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":true},"eth_usdt":{"minAmount":"0.00010","amountScale":3,"priceScale":2,"maxLevels":0,"isOpen":true},"xwc_qc":{"minAmount":"0.01","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"qbt_qc":{"minAmount":"0.01","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"tv_eth":{"minAmount":"0.001","amountScale":2,"priceScale":5,"maxLevels":0,"isOpen":true},"epc_qc":{"minAmount":"0.1","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"qash_qc":{"minAmount":"0.00010","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"ubtc_btc":{"minAmount":"0.00010","amountScale":3,"priceScale":5,"maxLevels":0,"isOpen":true},"cfun_btc":{"minAmount":"0.000010","amountScale":0,"priceScale":8,"maxLevels":0,"isOpen":true},"qbt_usdt":{"minAmount":"0.01","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"eos_btc":{"minAmount":"0.00010","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":true},"qtum_btc":{"minAmount":"0.00010","amountScale":2,"priceScale":6,"maxLevels":3,"isOpen":true},"ubtc_qc":{"minAmount":"0.001","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"ltc_usdt":{"minAmount":"0.01","amountScale":3,"priceScale":2,"maxLevels":0,"isOpen":true},"bot_qtum":{"minAmount":"0.01","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":true},"tsl_btc":{"minAmount":"0.01","amountScale":0,"priceScale":8,"maxLevels":0,"isOpen":false},"sexc_qc":{"minAmount":"0.01","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"mco_eth":{"minAmount":"0.001","amountScale":3,"priceScale":5,"maxLevels":0,"isOpen":true},"bts_btc":{"minAmount":"0.00010","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":false},"bts_eth":{"minAmount":"0.001","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":true},"hsr_btc":{"minAmount":"0.00010","amountScale":2,"priceScale":6,"maxLevels":3,"isOpen":true},"eos_qtum":{"minAmount":"0.001","amountScale":3,"priceScale":3,"maxLevels":0,"isOpen":true},"qtum_qc":{"minAmount":"0.01","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"btp_usdt":{"minAmount":"0.00010","amountScale":3,"priceScale":2,"maxLevels":0,"isOpen":true},"hld_usdt":{"minAmount":"0.01","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"cfun_eth":{"minAmount":"0.00010","amountScale":0,"priceScale":6,"maxLevels":0,"isOpen":false},"cfun_qtum":{"minAmount":"0.001","amountScale":0,"priceScale":6,"maxLevels":0,"isOpen":true},"spc_usdt":{"minAmount":"0.01","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":false},"can_qc":{"minAmount":"0.00010","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"tv_qc":{"minAmount":"0.1","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"xwc_btc":{"minAmount":"0.000010","amountScale":0,"priceScale":8,"maxLevels":0,"isOpen":true},"btg_btc":{"minAmount":"0.00010","amountScale":3,"priceScale":5,"maxLevels":5,"isOpen":false},"chat_eth":{"minAmount":"0.00010","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":true},"bcd_btc":{"minAmount":"0.00010","amountScale":2,"priceScale":6,"maxLevels":5,"isOpen":true},"btw_btc":{"minAmount":"0.000010","amountScale":2,"priceScale":5,"maxLevels":0,"isOpen":false},"hsr_usdt":{"minAmount":"0.01","amountScale":2,"priceScale":2,"maxLevels":0,"isOpen":true},"ink_qtum":{"minAmount":"0.01","amountScale":2,"priceScale":6,"maxLevels":5,"isOpen":true},"mco_btc":{"minAmount":"0.001","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":true},"spc_qtum":{"minAmount":"0.001","amountScale":2,"priceScale":6,"maxLevels":0,"isOpen":true}}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/exx.py", line 228, in fetch_balance
    balances = self.privateGetBalance(params)
AttributeError: 'exx' object has no attribute 'privateGetBalance'

**Comment by kroitor** [comment]
Fixed in 1.12.107, don't forget to update ) Thx for reporting!

**Comment by karlandoh** [comment]
No prob! However I am now getting the same verbose but a different error now. Currently on 1.12.108.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/exx.py", line 228, in fetch_balance
    balances = self.privateGetGetBalance(params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/exx.py", line 349, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/base/exchange.py", line 301, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/exx.py", line 344, in sign
    signature = self.hmac(self.encode(body), self.encode(self.secret), hashlib.sha512)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ccxt/base/exchange.py", line 769, in encode
    return string.encode()
AttributeError: 'NoneType' object has no attribute 'encode'
