### ISSUE TITLE
Leverage Trade on Bitmex

### ISSUE THREAD

**Issue by cinnabarhorse** [ccxt/ccxt#2499]
- OS: Mac OS High Sierra
- Programming Language version: PHP 5.5
- CCXT version: 1.2.11
- Exchange: Bitmex
- Method: $bitmex->createMarketSellOrder and $bitmex->createMarketBuyOrder

Hi, I read through the documentation and looked at PHP examples, but I couldn't find any documentation about using leverage in a Bitmex trade. I tried adding a param array to the method call ('leverage' => 5) but that didn't seem to work either. Could you please clarify how to include margin in a market order on Bitmex? Thanks.

**Comment by SavosRU** [comment]
Yes, this question is very interest to me too!
For python version - am I need to create new fork of this question?

**Comment by kroitor** [comment]
Hi, guys!

FIrst of, please update to ccxt 1.12.124 in 5-10 minutes, bitmex has been edited for better support for leverage order types...

> For python version - am I need to create new fork of this question?

No. )

We don't have leverage/margin trading unified in CCXT yet, as this is the most complex piece of the entire puzzle. We are going to address this after finishing basic spot order APIs, as described in #56. Until then, the leverage trading is supported by CCXT, but not unified yet. Therefore you will have to pass exchange-specific parameters to your margin-trading queries for it to work. You need to consult [the Manual](https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods)  on how to pass exchange-specific extra parameters properly:
- https://github.com/ccxt/ccxt/wiki/Manual#custom-order-params
- https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods
... and [bitmex docs](https://www.bitmex.com/api/explorer/#!/Order/Order_new) on which extra parameters should be passed to your leveraged queries.

<img width="512" alt="screen shot 2018-04-09 at 19 56 09" src="https://user-images.githubusercontent.com/1294454/38511239-35956736-3c30-11e8-9cb9-ff8b8bdd89cf.png">

↑  There's no `leverage` parameter there as you can see. The thing is: whether you are trading with spot orders or with margin/leveraged orders – that depends on the market (a symbol or pair), you are trading with.

Bitmex has the following order types: 
- Market
- Limit
- Stop
- StopLimit
- MarketIfTouched
- LimitIfTouched
- MarketWithLeftOverAsLimit
- Pegged. 

↑ Defaults to 'Limit' when price is specified. Defaults to 'Stop' when stopPx is specified. Defaults to 'StopLimit' when price and stopPx are specified.

@SavosRU , @cinnabarhorse which one of those order types do you want and what would be other parameters of your order?

------------

@cinnabarhorse in PHP:

https://github.com/ccxt/ccxt/blob/master/examples/php/bitmex-create-order.php

```PHP
<?php

$root = dirname (dirname (dirname (__FILE__)));

include $root . '/ccxt.php';

date_default_timezone_set ('UTC');

$exchange = new \ccxt\bitmex (array (
    'apiKey' => 'YOUR_API_KEY', // ←------------ replace with your keys
    'secret' => 'YOUR_SECRET',
    'enableRateLimit' => true,
));

$symbol = 'XBTM18'; // bitcoin contract according to bitmex futures coding
$type = 'StopLimit'; // # or 'market', or 'Stop' or 'StopLimit'
$side = 'sell'; // or 'buy'
$amount = 1.0;
$price = 6500.0; // or None

// extra params and overrides
$params = array (
    'stopPx' => 6000.0, // if needed
);

$order = $exchange->create_order ($symbol, $type, $side, $amount, $price, $params);

print_r ($order);

```

------------

@SavosRU in python:

https://github.com/ccxt/ccxt/blob/master/examples/py/bitmex-create-order.py

```Python
# -*- coding: utf-8 -*-

import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402


exchange = ccxt.bitmex({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
})

symbol = 'XBTM18' # bitcoin contract according to bitmex futures coding
type = 'StopLimit' # or 'market', or 'Stop' or 'StopLimit'
side = 'sell' # or 'buy'
amount = 1.0
price = 6500.0 # or None

# extra params and overrides
params = {
    'stopPx': 6000.0, # if needed
}

order = exchange.create_order(symbol, type, side, amount, price, params)
print(order)

```

------------

I hope the above answers your questions. Closing it for now, feel free to reopen this if needed or just ask questions if any.

**Comment by kroitor** [comment]
P.S. For bitmex positions (leveraged orders) you will have to use their implicit methods, as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

```
console.log (new ccxt.kraken ())   // JavaScript
print(dir(ccxt.hitbtc()))        # Python
var_dump (new \ccxt\okcoinusd ()); // PHP
```

↓

```
...
 'private_post_position_isolate',
 'private_post_position_leverage',
 'private_post_position_risklimit',
 'private_post_position_transfermargin',
...
```

**Comment by cinnabarhorse** [comment]
Thanks. I will try to use the parameters again.

**Comment by aav80** [comment]
Anybody knows, how to get current position in bitmex via ccxt? Is it possible at all?

**Comment by kroitor** [comment]
> Anybody knows, how to get current position in bitmex via ccxt? Is it possible at all?

Sure, just use implicit methods: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
You should call `private_get_position`. Read the Manual for more info about how to use it.

**Comment by LordGomenasai** [comment]
Hello, you can pass an example of how to pass a leverage parameter for php and explain what does these functions pls, I am a nob programmer
'private_post_position_isolate',
 'private_post_position_leverage',
 'private_post_position_risklimit',
 'private_post_position_transfermargin',
Thank you..

**Comment by kroitor** [comment]
@LordGomenasai it has been answered here: 

- https://github.com/ccxt/ccxt/issues/4900

Something like this should work:

```PHP
// https://github.com/ccxt/ccxt/wiki/Manual#instantiation
$id = 'bitmex';
$exchange_class = '\\ccxt\\' . $id;
$exchange = new $exchange_class (array(
    'apiKey' => 'YOUR_API_KEY',
    'secret' => 'YOUR_SECRET',
    'enableRateLimit' => true,
));

// https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
$exchange->load_markets();

$symbol = 'BTC/USD';
$type = 'market';
$side = 'buy';
$amount = 100.0;  
$price = null;
$leverage = '50';  // 50x leverage

$market = $exchange->market($symbol);

// https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
$exchange->private_post_position_leverage(array(
    'symbol' => $market['id'],
    'leverage' => $leverage,
));

// now you should be able to buy maximum amount*leverage contracts
$order = $exchange->create_order($symbol, $type, $side, $amount, $price);
print_r($order);
```

**Comment by Gennttii** [comment]
Hi, I am trying to use this endpoint with nodeJS to add or remove margin in an open position:

private_post_position_transfermargin

Like this:
await bitmex.private_post_position_transfermargin ( symbol = pair , amount = 10000  )

But its showing me this error:
'BadRequest' 'bitmex {"error":{"message":"Unexpected token \\" in JSON at position 0","name":"SyntaxError"}}' 'Failed trade'

How to fix this, I checked in Bitmex API, the required parameters are symbol and amount, but is this private_post_position_transfermargin   correct for NodeJS ? If not , how to call it?

**Comment by kroitor** [comment]
@Gennttii which particular symbol is it? If you're using implicit API methods to call the endpoints directly, then you should handle market ids vs symbols in userland in your code, as described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#sending-market-ids

```JavaScript

await bitmex.loadMarkets ()
const symbol = 'BTC/USD'  // your symbol here
const market = bitmex.market (symbol)
const response = await bitmex.private_post_position_transfermargin ({
    symbol: market['id'],
    amount: 10000,
})
```

**Comment by Gennttii** [comment]
It was for Bitcoin, 'XBTUSD' is working , thanks..
