### ISSUE TITLE
new commonCoins symbol

### ISSUE THREAD

**Issue by dmig** [ccxt/ccxt#2500]
- CCXT version: 1.12.111
- Exchange: Binance/Yobit

AST: Binance (and others) use symbol AST for AirSwap, Yobit for ASTRAL

**Comment by dmig** [comment]
One more: LDC
Cryptopia: LADACoin
Hitbtc: Leadcoin

**Comment by dmig** [comment]
One more: HAV
Kucoin: Havven
Cryptopia: Havecoin

**Comment by dmig** [comment]
One more: MER
Tidex: Mercury
CoinExchange: TheMermaidCoin

**Comment by dmig** [comment]
One more: XIN
Bitbay: Infinity economics
Yobit: XINCoin

**Comment by dmig** [comment]
One more: BLN
CoinExchange (and others): Bolenum
Yobit: Bulleon

**Comment by dmig** [comment]
One more: UP
Bittrex: UpToken https://uptoken.org/
CoinExchange: UpscaleToken https://github.com/upscaletoken/up

**Comment by dmig** [comment]
One more: GTC
CoinExchange: GlobalTourCoin
Gate.io: Game.com GTC

**Comment by kroitor** [comment]
Thank you!

**Comment by dmig** [comment]
Please reopen, as I don't want to create alots of similar issues and I feel, I'll find many of such naming collisions in near future.

One more coin: GTC
Game.com on most markets: https://coinmarketcap.com/currencies/game/#markets
Global Tour Coin on CoinExchange https://coinmarketcap.com/currencies/global-tour-coin/#markets
