### ISSUE TITLE
How to implement this script on cli base php for indodax?

### ISSUE THREAD

**Issue by juragandotid** [ccxt/ccxt#2504]
Can u explain to me how to implement this script on cli base php,

frist setup api->connection to api->check balance->if null return error else load market->load market

make proceess buy sell and close order

because this part of your example and i doesn understand the step how to make like a trading in console.

Thank You.

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/blob/master/examples/php/indodax-fetch-balance-create-order-cancel-order.php

```PHP
<?php

$root = dirname (dirname (dirname (__FILE__)));

include $root . '/ccxt.php';

date_default_timezone_set ('UTC');

$exchange = new \ccxt\indodax (array (
    'apiKey' => 'YOUR_API_KEY', // ←------------ replace with your keys
    'secret' => 'YOUR_SECRET',
    'enableRateLimit' => true,
));

//-----------------------------------------------------------------------------
// querying balance

$balance = $exchange->fetch_balance ();

print_r ($balance);

// do whatever you need here with your balance...

//-----------------------------------------------------------------------------
// placing and canceling orders

$symbol = 'BTC/IDR'; // bitcoin contract according to bitmex futures coding
$type = 'limit';
$side = 'sell'; // or 'buy'
$amount = 1.0;
$price = 6500.0; // or None

// extra params and overrides if necessary
$params = array (
    // ...
);

// buying

$buy_order1 = $exchange->create_limit_buy_order ($symbol, $amount, $price, $params);
echo "Buy order 1:\n";
print_r(buy_order1);

$buy_order2 = $exchange->create_order ($symbol, $type, 'buy', $amount, $price, $params);
//                             order side hardcoded here ↑ for example
echo "Buy order 2:\n";
print_r(buy_order2);

// selling

$sell_order1 = $exchange->create_limit_sell_order ($symbol, $amount, $price, $params);
echo "Sell order 1:\n";
print_r(buy_order1);

$sell_order2 = $exchange->create_order ($symbol, $type, $side, $amount, $price, $params);
//                         order side from a variable here ↑ for example
echo "Sell order 2:\n";
print_r(sell_order2);

// canceling

$exchange->cancel_order($buy_order1['id'], $symbol);
$exchange->cancel_order($buy_order2['id'], $symbol);
$exchange->cancel_order($sell_order1['id'], $symbol);
$exchange->cancel_order($sell_order2['id'], $symbol);

```

Hope it answers your question.

**Comment by juragandotid** [comment]
Thank you i will try :D

Pada tanggal Sen, 9 Apr 2018 19:02, Igor Kroitor <notifications@github.com>
menulis:

**Comment by juragandotid** [comment]
$params = array (
    // ...
);

can u explain the list of params?

Thank you

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods
- https://github.com/ccxt/ccxt/wiki/Manual#custom-order-params

**Comment by juragandotid** [comment]
$amount = 1.0;
$price = 6500.0; // or None

// extra params and overrides if necessary
$params = array (
    // ...
);

// buying

$buy_order1 = $exchange->create_limit_buy_order ($symbol, $amount, $price, $params);
echo "Buy order 1:\n";
print_r ($buy_order1);


what is different of $amount and $price? is not same?

**Comment by kroitor** [comment]
@juragandotid https://github.com/ccxt/ccxt/wiki/Manual#placing-orders

**Comment by juragandotid** [comment]
Can u tell me how to get average currency from OHLCV Candlestick Charts ? i'm used 'BTC/IDR' currency.

Thank you

**Comment by kroitor** [comment]
> Can u tell me how to get average currency from OHLCV Candlestick Charts ?

You should be very precise and specific with financial terms. There's no such thing as *"average currency"* in OHLCV – so I don't really get what kinds of data you want, could you clarify this?

**Comment by juragandotid** [comment]
sorry that i'm mean, average on  Price Ticker.


{
    'symbol':        string symbol of the market ('BTC/USD', 'ETH/BTC', ...)
    'info':        { the original non-modified unparsed reply from exchange API },
    'timestamp':     int (64-bit Unix Timestamp in milliseconds since Epoch 1 Jan 1970)
    'datetime':      ISO8601 datetime string with milliseconds
    'high':          float, // highest price
    'low':           float, // lowest price
    'bid':           float, // current best bid (buy) price
    'bidVolume':     float, // current best bid (buy) amount (may be missing or undefined)
    'ask':           float, // current best ask (sell) price
    'askVolume':     float, // current best ask (sell) amount (may be missing or undefined)
    'vwap':          float, // volume weighed average price
    **'open':          float, // opening price**
    'close':         float, // price of last trade (closing price for current period)
    'last':          float, // same as `close`, duplicated for convenience
    'previousClose': float, // closing price for the previous period
    **'change':        float, // absolute change, `last - open`**
    **'percentage':    float, // relative change, `(change/open) * 100`**
    **'average':       float, // average price, `(last + open) / 2`**
    'baseVolume':    float, // volume of base currency
    'quoteVolume':   float, // volume of quote currency
}

can u explain me to some function in bold text,

what is the mean opening price, btc currncy or IDR currency?

in case i will make some function : 

`
$ticker = $inboxno->fetch_ticker('BTC/IDR');

print "====== IMPORTAN TRADING TICKER INFORMATION ===== \r\n";
print "Trading Crypto : " . $ticker['symbol'] . "\r\n";
print "Time Stamp : " . $ticker['timestamp'] . "\r\n";
print "Date Time : " . $ticker['datetime']. "\r\n";
print "High : " . $ticker['high'] . "\r\n";
print "Low : " . $ticker['low'] . "\r\n";
print "Bid : " . $ticker['bid'] . "\r\n";
print "Bid Volume : " . $ticker['bidVolume'] . "\r\n";
print "Ask : " . $ticker['ask'] . "\r\n";
print "Ask Volume : " . $ticker['askVolume'] . "\r\n";
print "Vwap : " . $ticker['vwap'] . "\r\n"; 
print "Open : " . $ticker['open'] . "\r\n"; 
$open = '10000';
print "Close : " . $ticker['close'] . "\r\n"; 
print "Last : " . $ticker['last'] . "\r\n"; 
print "Previous Close : " . $ticker['previousClose'] . "\r\n"; 
$change = $ticker['last'] - $open;
print "Change : " . $change . "\r\n"; 
$percentage = ($change / $open) * 100;
print "Percentage : " . $percentage . "\r\n"; 
$average = ($ticker['last'] + $open) / 2;
print "Average : " . $average . "\r\n"; 
print "Volume BTC: " . $ticker['baseVolume'] . "\r\n"; 
print "Volume IDR : " . $ticker['quoteVolume'] . "\r\n"; 
print "Server Time : " . $ticker['info']['server_time'] . "\r\n"; 
print "====== IMPORTAN TRADING TICKER CLOSE ===== \r\n\r\n";

$buy = $ticker['bid'] - $average;

if($buy > 2){
	frist -> get last and save as temp.
	second -> function sleep 7m.
	thrithy -> check the last after 7m sleep and save as temp.
	four -> checking if temp last after 7m sleep 50% less than last before 7m. make some buy function.
}

$sell = $average - $ticker['ask'];

if($sell > 2){
	frist -> get last and save as temp.
	second -> function sleep 7m.
	thrithy -> check the last after 7m sleep and save as temp.
	four -> checking if temp last after 7m sleep 30% bigger than last before 7m. make some sell function.
}
`

Help me explain my function :) 

Thank You.

**Comment by juragandotid** [comment]
but if i'm used same as doc

**'average': float, // average price, (last + open) / 2**

` $average = ($ticker['last'] + $open) / 2;`

$sell = $average - $ticker['ask'];

result $sell always negative.

explain it 

Thank You brother :D :D

**Comment by juragandotid** [comment]
![untitled](https://user-images.githubusercontent.com/35671934/38606194-572f1b94-3d43-11e8-9b94-902b3d2dfa50.png)

**Comment by kroitor** [comment]
> what is the mean opening price, btc currncy or IDR currency?

In CCXT library:
- price is always in quote currency
- amount in tickers is designated as baseVolume (base currency, BTC), and quoteVolume (quote currency, IDR)

From the Manual: https://github.com/ccxt/ccxt/wiki/Manual#consistency-of-base-and-quote-currencies

```
base currency ↓
             BTC / USDT
             ETH / BTC
            DASH / ETH
             BTC / IDR
                    ↑ quote currency
```

So, all prices in BTC/IDR ticker are in IDR.

Does this answer your question?

**Comment by juragandotid** [comment]
Please update this doc 

`if ($exchange->has['fetchOHLCV'])
    foreach ($exchange->markets as $symbol => $market) {
        usleep ($exchange.rateLimit * 1000); // usleep wants microseconds
        var_dump ($exchange->fetch_ohlcv ($symbol, '1M')); // one month
    }`

when use `usleep($exchange.rateLimit * 100); //usleep wants microseconds` it will be getting an error like this : `Warning: Use of undefined constant rateLimit - assumed 'rateLimit' (this will throw an Error in a future version of PHP)`

update to : 

'if ($exchange->has['fetchOHLCV'])
    foreach ($exchange->markets as $symbol => $market) {
        usleep ($exchange->rateLimit * 1000); // usleep wants microseconds
        var_dump ($exchange->fetch_ohlcv ($symbol, '1M')); // one month
    }'

Thank you.

**Comment by juragandotid** [comment]
and try review again the class `has[fetchOHLCV] / fetch_ohlcv ` , i got unidentified output like this : 
` float(3.465E-5)`

Thank you

**Comment by kroitor** [comment]
>  i got unidentified output like this : `float(3.465E-5)`

What do you mean exactly by *"unidentified"* ?

**Comment by kroitor** [comment]
> Please update this doc

Docs updated, thank you very much for pointing that out! )

**Comment by juragandotid** [comment]
![untitled](https://user-images.githubusercontent.com/35671934/38615224-ea184a6a-3d5d-11e8-80c6-c92d2477721e.png)

**Comment by juragandotid** [comment]
Please check `$exchange.withdraw (currency, amount, address, tag = undefined, params = {})` 
change to `$exchange->withdraw (currency, amount, address, tag = undefined, params = {})`

**Comment by kroitor** [comment]
@juragandotid that is answered here: https://github.com/ccxt/ccxt/issues/2529#issuecomment-379923894 . You call it *"unidentified"* because you need at least basic Python skills to treat that correctly – that's how float point numbers are printed out in Python print() and pprint() by default, and it's up to you to chose the way you want them. You should read more about Python basics and working with variable types, especially float numbers (docs linked above).

**Comment by juragandotid** [comment]
how do i get the last price if using this class `fetch_ohlcv`

Thank you.

**Comment by kroitor** [comment]
> how do i get the last price if using this class fetch_ohlcv

First of, that is not a class. If you want to be understood, you should not really use the words that you're not familiar with yet ) That is called a `function` or a `method` or `class method, not a `class` ) If you want an advice: better stick to the common terminology )

OHLCV stands for:
- Open (opening price in quote currency for that candle/period)
- High (highest price in quote currency for that candle/period)
- Low (lowest price in quote currency for that candle/period)
- Close (closing price in quote currency for that candle/period)
- Volume (in base currency)
↑ as you can see, the OHLCV data does not contain the "last" price, however, you can get the last price from fetchTicker or from fetchTrades – that will be the price of the last trade, if you want the current last price. Historical OHLCV data does not contain that info.

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts
- https://github.com/ccxt/ccxt/wiki/Manual#price-tickers
- https://github.com/ccxt/ccxt/wiki/Manual#trades-executions-transactions

**Comment by juragandotid** [comment]
can u explain how to sleep in mircrosecond?

`if ($exchange->has['fetchOHLCV'])
    foreach ($exchange->markets as $symbol => $market) {
        **usleep ($exchange->rateLimit * 1000); // usleep wants microseconds**
        var_dump ($exchange->fetch_ohlcv ($symbol, '1M')); // one month
    }`

this is my code 
`usleep($exchange->rateLimit * 180000000);`

igot an error :

`Warning: usleep() expects parameter 1 to be integer`

thank you

**Comment by kroitor** [comment]
The `rateLimit` is already in microseconds, no need to multiply it
```
usleep($exchange->rateLimit);
```

**Comment by kroitor** [comment]
UPD. Corrected the above answer.

**Comment by juragandotid** [comment]
when i use `usleep` in 1 minute what can i do?

**Comment by juragandotid** [comment]
i'm try to make construct, this code : 

`function __construct(){
		echo "Masukan Api Key : ";
		$this->ApiKey = rtrim(fgets(STDIN));
		echo "Masukan Secret Key : ";
		$this->Secret = rtrim(fgets(STDIN));
		$this->inboxno = new \ccxt\indodax (array(
			'apiKey' => $this->ApiKey, // ←------------ replace with your keys
			'secret' => $this->Secret,
			'enableRateLimit' => true
		));
		
	}
	
	public function run(){
				$inboxnoo = $this->inboxno;
				$ticker = $inboxnoo->fetch_ticker('BTC/IDR');
				foreach($ticker as $key => $tickers){
					if(is_array($tickers)){
						$high = $tickers['high'];
						$low = $tickers['low'];
						$bid = $tickers['bid'];
						$ask = $tickers['ask'];
						$open = 10000;
						$close = $tickers['close']; 
						$last = $tickers['last']; 
						$previous = $tickers['previousClose']; }}}`
i can get the result of $high, $low, and $last. But $bid, $ask, $close. $previous error.

i get this error : 

`Notice:  Undefined index: bid in F:\indodax\testing.php on line 34

Notice: Undefined index: bid in F:\indodax\testing.php on line 34
PHP Notice:  Undefined index: ask in F:\indodax\testing.php on line 35

Notice: Undefined index: ask in F:\indodax\testing.php on line 35
PHP Notice:  Undefined index: close in F:\indodax\testing.php on line 37

Notice: Undefined index: close in F:\indodax\testing.php on line 37
PHP Notice:  Undefined index: previousClose in F:\indodax\testing.php on line 39

Notice: Undefined index: previousClose in F:\indodax\testing.php on line 39
1`

what can i do?

Thank you :D

**Comment by juragandotid** [comment]
why cannot get respon from this 
`
$symbol = 'BTC/IDR'; // bitcoin contract according to bitmex futures coding
$type = 'limit';
$side = 'buy'; // or 'buy'
$amount = 0.00022;
$simpan = 94000000;
$buyOrder = $this->inboxno->create_order($symbol, $type, $side, $amount, $simpan);
					print_r($buyOrder);`

**Comment by kroitor** [comment]
@juragandotid https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by juragandotid** [comment]
how to add Exception in php, because i wanna check whats misstack in response

**Comment by juragandotid** [comment]
I think this trobel on indodax source, please check again any mistack or typo or api change.Because i have try no response and no error show.

Thank your.

**Comment by juragandotid** [comment]
And now indodax private api has change to  https://indodax.com/trade_api.

Please check again any api change or partmeter change.

Thank You.

**Comment by juragandotid** [comment]
![apiprtmeter](https://user-images.githubusercontent.com/35671934/42311950-a849c2d2-8004-11e8-877b-3a56bc600c1d.png)

**Comment by juragandotid** [comment]
![api](https://user-images.githubusercontent.com/35671934/42311967-b2b49012-8004-11e8-978b-563a2391e67b.png)

**Comment by juragandotid** [comment]
And once again , i think indodax now has change method authentication api.

Public api = https://indodax.com/api
Private api = https://indodax.com/trade_api

and authenticate api using hmac, and post on https://indodax.com/trade_api.

![auth](https://user-images.githubusercontent.com/35671934/42312750-bc3d8a88-8006-11e8-8d5d-0c8bc6339d17.png)

**Comment by kroitor** [comment]
@juragandotid you'd better start reading around if you want to save your:

- https://github.com/ccxt/ccxt/tree/master/examples
- https://github.com/ccxt/ccxt/tree/master/examples/php
- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure that you have the most recent version of ccxt, this is also written in the docs.
Current CCXT implementation of INDODAX is up to date.

**Comment by juragandotid** [comment]
Mybe the indodax doc typo send request to https://indodax.com/tapi because in doc private api has change to https://indodax.com/trade_api. or there has use https://indodax.com/tapi to authenticate whit api key and sign in with hmac. and https://indodax.com/trade_api for private api supported list partmeter in doc update 2018 and http://indodax.com/api for public api supported list partmeter in doc.

This is my review, and please chek again mybe i'm false review and thingking.

Thank you.

**Comment by kroitor** [comment]
This: https://indodax.com/trade_api is their website page for creating API keys, it requires a user to sign in.

This: https://indodax.com/tapi is their API base URL for integrating with other code, and this is what we are using, as documented in their Manual. If you  change it to https://indodax.com/trade_api it just stops working, obviously, as expected.

> mybe i'm false review and thingking.

Yep.

**Comment by FandyAhmadAzizi** [comment]
How to include api key private on indodax.php ?
