### ISSUE TITLE
AttributeError: 'kuna' object has no attribute 'publicGetK'

### ISSUE THREAD

**Issue by jorijnsmit** [ccxt/ccxt#2506]
- OS: macOS
- Programming Language version: Python
- CCXT version: 1.11.45
- Exchange: kuna
- Method:
```
>>> import ccxt
>>> exchange = ccxt.kuna()
>>> exchange.load_markets()
>>> exchange.fetch_ohlcv('ARN/BTC')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jorijnsmit/anaconda3/lib/python3.6/site-packages/ccxt/acx.py", line 257, in fetch_ohlcv
    response = self.publicGetK(self.extend(request, params))
AttributeError: 'kuna' object has no attribute 'publicGetK'
```

**Comment by kroitor** [comment]
@jorijnsmit your version of ccxt is too old, please update to 1.12.112 or higher. Let us know if you still have difficulties with it after updating, feel free to reopen this issue if needed, or just ask questions if any. Thx!

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by jorijnsmit** [comment]
Problem solved! Sorry I wasn't aware that I was running behind so much already. Thanks a million for your dedication and support to this project 🙏

**Comment by kroitor** [comment]
@jorijnsmit thx for your feedback!
