### ISSUE TITLE
Bitbay: invalid markets

### ISSUE THREAD

**Issue by dmig** [ccxt/ccxt#2508]
- Programming Language version: python 3.6.5
- CCXT version: 1.12.111
- Exchange: Bitbay
- Method: fetchTicker()

Markets info of this exchange is hardcoded. Please remove following markets as they've been unlisted:
```
XIN/USD
bitbay {"code":510,"message":"Invalid market name"}
XIN/EUR
bitbay {"code":510,"message":"Invalid market name"}
XIN/PLN
bitbay {"code":510,"message":"Invalid market name"}
```

**Comment by kroitor** [comment]
Yeah, unfortunately, they don't serve a list of markets from their API yet... We'll see if we can recode them for a website URL for market list...
