### ISSUE TITLE
SouthXchange .fetchOpenOrders() : order.side undefined

### ISSUE THREAD

**Issue by xogoc** [ccxt/ccxt#2510]
- OS: Ubuntu 16.04.3
- Programming Language version: Node.js v8.11.1
- CCXT version: 1.12.97
- Exchange: SouthXchange
- Method: .fetchOpenOrders()

SouthXchange.fetchOpenOrders() returns orders with .side property undefined. Instead it puts 'buy' or 'sell' in .type property.

**Comment by kroitor** [comment]
Fixed in 1.12.120, thx for reporting!
