### ISSUE TITLE
How to realize the active push of the server instead of polling?

### ISSUE THREAD

**Issue by nashse** [ccxt/ccxt#2513]
OS: win10
Programming Language version: python3.6
CCXT version: ccxt-1.11.137
Exchange: okex 、huobipro
Method: fetch_order

question：

> Okex's websocket's acquiring order interface has the function of server's active push. If I use ccxt, how can I realize this function, that is, the subscription mode.

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/56

**Comment by nashse** [comment]
ok
