### ISSUE TITLE
How to recalculate Bitmex 15m OHLCV from 5m timeframe

### ISSUE THREAD

**Issue by bestlinkXx** [ccxt/ccxt#2514]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:Windows 7
- Programming Language version:Python
- CCXT version:1.12.117
- Exchange:Bitmex
- Method:Fetch_ohlc

Hello,

I want to use timeframe for 15m for my strategy, I need to collect kline for MA, RSI, STOCHRSI and BOLLINGER BANDS.

How can I find an alternative way to gather these data ?

Thank you a lot !

**Comment by kroitor** [comment]
> I want to use timeframe for 15m for my strategy, I need to collect kline for MA, RSI, STOCHRSI and BOLLINGER BANDS.

Bitmex supports the following timeframes for querying data:

```
            'timeframes': {
                '1m': '1m',
                '5m': '5m',
                '1h': '1h',
                '1d': '1d',
            },
```

So, you can't fetch 15m timeframe directly. However, you can recreate higher-order timeframes with lower-order timeframes: you can calculate 15m OHLCV from 5m OHLCV, as each 15-minute period consists of three 5m periods. Thus, you have to fetch 5m OHLCV and recalculate 15m OHLCV on your own:

https://github.com/ccxt/ccxt/blob/master/examples/py/bitmex-ohlcv-convert-5m-to-15m.py

```Python
# -*- coding: utf-8 -*-

import os
import sys
from pprint import pprint

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402


bitmex = ccxt.bitmex({
    'enableRateLimit': True,
    # 'verbose': True,
})

# fetch 5m OHLCV

symbol = 'BTC/USD'

ohlcv5 = bitmex.fetch_ohlcv(symbol, '5m')
ohlcv15 = []

# OHLCV key indexes

timestamp = 0
open = 1
high = 2
low = 3
close = 4
volume = 5

# convert 5m → 15m

if len(ohlcv5) > 2:
    for i in range(0, len(ohlcv5) - 2, 3):
        highs = [ohlcv5[i + j][high] for j in range(0, 3) if ohlcv5[i + j][high]]
        lows = [ohlcv5[i + j][low] for j in range(0, 3) if ohlcv5[i + j][low]]
        volumes = [ohlcv5[i + j][volume] for j in range(0, 3) if ohlcv5[i + j][volume]]
        candle = [
            ohlcv5[i + 0][timestamp],
            ohlcv5[i + 0][open],
            max(highs) if len(highs) else None,
            min(lows) if len(lows) else None,
            ohlcv5[i + 2][close],
            sum(volumes) if len(volumes) else None,
        ]
        ohlcv15.append(candle)
else:
    raise Exception('Too few 5m candles')

# do whatever you want with your 15m candles here...

pprint(ohlcv15)
```

Read the docs: https://github.com/ccxt/ccxt/wiki

Hope it answers your question.

**Comment by bestlinkXx** [comment]
Thank you a lot Kroitor !

I add this on my version and will check if all is good !

Have a nice day.

**Comment by bestlinkXx** [comment]
Hello, 
I try to configure since to begin correctly (12h00,12h15...)
Unfortunatly, it doesn't collect correct value too, I'm checking how can I modify this.

If you have time to check it, I'll be very thankful !
