### ISSUE TITLE
create_order arguments- not consistent 

### ISSUE THREAD

**Issue by AvishaiW** [ccxt/ccxt#2515]
- Programming Language version: python
- CCXT version: 1.12.117
- Exchange: gdax, luno, coinsecure, coinspot, paymium
- Method: `create_order`

I noticed the first argument of `create_order` isn't consistent, most exchanges have `symbol` where a few others name it `market`. Is there a reason for this change?

Thanks!

**Comment by kroitor** [comment]
Fixed in 1.12.122. Thanks!
