### ISSUE TITLE
Can't fetchClosedOrders for Poloniex

### ISSUE THREAD

**Issue by atjason** [ccxt/ccxt#2516]
- OS: Ubuntu 16.04
- Programming Language version: js
- CCXT version: 1.12.117
- Exchange: poloniex
- Method: fetchClosedOrders

When open `verbose` and call Poloniex `fetchClosedOrders`, then get the following output:

```
fetch:
 poloniex POST https://poloniex.com/tradingApi
Request:
 { 'Content-Type': 'application/x-www-form-urlencoded',
  Key: '…',
  Sign: '…' }
 command=returnOpenOrders&currencyPair=USDT_ETH&nonce=1523264446294
```

As you can find, `command=returnOpenOrders` means it will only return the `open` orders.

And in fact when I check [Poloniex's API doc](https://poloniex.com/support/api/), seems there's no API to fetch closed orders for Poloninex (which is bad).

Maybe the worst case is delete `fetchClosedOrders` for Poloniex. Please help to check, thanks.

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/wiki/Manual#querying-orders
