### ISSUE TITLE
orderExceedsLimit error appears while selling BCH on hitbtc

### ISSUE THREAD

**Issue by algoscale1** [ccxt/ccxt#2520]
- OS: ubuntu
- Programming Language version: python3.5
- CCXT version: 1.12
- Exchange:hitbtc
- Method: create_limit_sell_order('BCH/BTC',left_vol, bid )

I am trying to sell amount 0.001 BCH/BTC on hitbtc.i have 'BCH': 0.01768375 in my account. So when placing order i get this response:-

{'ExecutionReport': {'userId': 'user_xyz', 'clientOrderId': '1523269248129', 'created': 1523269248067, 'side': 'sell', 'timeInForce': 'GTC', 'quantity': 1, 'cumQuantity': 0, 'latestOrderId': 'N/A', 'symbol': 'BCCFBTC', 'price': '0.095309', 'type': 'limit', 'lastPrice': '', 'lastQuantity': 0, 'orderStatus': 'rejected', 'orderRejectReason': 'orderExceedsLimit', 'execReportType': 'rejected', 'orderId': 'N/A', 'averagePrice': '0', 'leavesQuantity': 0}}

Please help me out, thanks.

**Comment by kroitor** [comment]
Can you please show a minimal but a complete snippet of code to reproduce the issue?

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by kroitor** [comment]
```
{     limits: { amount: { min: 0.001, max: undefined },
                 price: { min: 0.000001, max: undefined },
                  cost: { min: undefined, max: undefined } },
   precision: { amount: 3, price: 6 },
   tierBased:    false,
  percentage:    true,
       taker:    0.001,
       maker:    -0.0001,
          id:   "BCHBTC",
      symbol:   "BCH/BTC",
        base:   "BCH",
       quote:   "BTC",
      baseId:   "BCH",
     quoteId:   "BTC",
         lot:    0.001,
        step:    0.000001,
        info: {               symbol: "BCHBTC",
                                step: "0.000001",
                                 lot: "0.001",
                            currency: "BTC",
                           commodity: "BCH",
                   takeLiquidityRate: "0.001",
                provideLiquidityRate: "-0.0001"   }           }
```

The HitBTC v1 min limit for the order is 0.001 BCH, see here: https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

Hope this answers your question.

**Comment by algoscale1** [comment]
Thanks for your time. Here is the exact paramenters for hitbtc that i am using:

amount = 0.002   (limit is 0.001 and precision on amount is 3)
bid = 0.094566    (price precision is 6 digits )
hitbtc.create_limit_sell_order('BCH/BTC', amount, bid )

**Comment by kroitor** [comment]
@algoscale1 are you using hitbtc v1 or v2?

**Comment by algoscale1** [comment]
hitbtc1

**Comment by kroitor** [comment]
@algoscale1 i'd recomment switching to HitBTC v2, as v1 is deprecated, according to HitBTC, and v2 should not have that precision issue. Hope it helps. Let me know, if not.

**Comment by algoscale1** [comment]
okayi try with v2. thanks

**Comment by algoscale1** [comment]
Hi Kroitor, facing the same issue with hitbtc2, here is what i got:

ccxt.base.errors.InsufficientFunds: hitbtc2 {"error":{"code":20001,"message":"Insufficient funds","description":"Check that the funds are sufficient, given commissions"}}

**Comment by kroitor** [comment]
@algoscale1 can you post verbose output of it, as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

Need to see the request, response and the error stacktracke (without your keys).

Add .verbose = True to your exchange before calling create_limit_sell_order:

```Python
exchange.verbose = True
exchange.create_limit_sell_order('BCH/BTC', amount, bid)
```

Are you sure you have the funds on your trading account, not on your main account? What does `print(exchange.fetch_balance())` tell you?

**Comment by algoscale1** [comment]
fetch_balance gives me this much balance 
'BCH': {'free': 0.01768375, 'total': 0.01768375, 'used': 0.0},

**Comment by kroitor** [comment]
@algoscale1 can you post a minimal, but a complete snippet of code to reproduce your issue (remove everything that isn't necessary, but make it a workable short snippet, we need to see how you link against ccxt, how you create the exchange, and how you then place the order with specific params in verbose mode, avoid one-liners) + your verbose output ? Without precise and complete debug info it will be hard to resolve this.

**Comment by kroitor** [comment]
To clarify: no need for your keys, just the code and verbose output, without the keys.

**Comment by algoscale1** [comment]
okay sure

**Comment by kroitor** [comment]
@algoscale1 their fees are always in quote currency (BTC) in your case, therefore you will have to pay fees in BTC. Is your BTC balance empty?

**Comment by algoscale1** [comment]
`hitbtc = ccxt.hitbtc2({'apiKey': 'xyz',
                      'secret': 'xyz'
                      
})

hitbtc.verbose = True
hitbtc.create_limit_sell_order('BCH/BTC', 0.015, 0.094136'  )
`


here is the request data:
{'clientOrderId': 'cc3349faf0fd458c9c0f2f4cf8b020b1', 'type': 'limit', 'price': '0.094136', 'side': 'sell', 'quantity': 0.015, 'symbol': 'BCHBTC'}

**Comment by kroitor** [comment]
@algoscale1 that is absolutely not even close to https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by algoscale1** [comment]
i have this much BTC
'BTC': {'free': 0.0024, 'total': 0.0024, 'used': 0.0},

**Comment by kroitor** [comment]
@algoscale1 we need you to be very specific and precise in order to get it resolved, can you copy the entire verbose output (request + response + error stacktrace) ?

**Comment by algoscale1** [comment]
Request: POST https://api.hitbtc.com/api/2/order {'Authorization': 'Basic YTVjNjljOGM4Y2Q5ODYxNzQ0ODQ3MzQzODAxYTY0NGQ6OWUwZDIxYWJhZDRmNmJjODFiNWNlZjhhZWM1ZDMxYjY=', 'User-Agent': 'python-requests/2.18.4', 'Content-Type': 'application/json', 'Accept-Encoding': 'gzip, deflate'} {"clientOrderId":"cc3349faf0fd458c9c0f2f4cf8b020b1","type":"limit","price":"0.094136","side":"sell","quantity":0.015,"symbol":"BCHBTC"}

Response: POST https://api.hitbtc.com/api/2/order 400 {'Date': 'Tue, 10 Apr 2018 07:39:54 GMT', 'Server': 'nginx', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '126', 'Connection': 'keep-alive'} {"error":{"code":20001,"message":"Insufficient funds","description":"Check that the funds are sufficient, given commissions"}}
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 363, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.hitbtc.com/api/2/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "test.py", line 198, in sell
    hitbtc.create_limit_sell_order('BCH/BTC',left_vol, bid )
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 1222, in create_limit_sell_order
    return self.create_order(symbol, 'limit', 'sell', *args)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/hitbtc2.py", line 838, in create_order
    response = self.privatePostOrder(self.extend(request, params))
  File "/usr/local/lib/python3.5/dist-packages/ccxt/hitbtc2.py", line 1097, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 302, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 375, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, self.last_response_headers, self.last_http_response)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/hitbtc2.py", line 1091, in handle_errors
    raise InsufficientFunds(self.id + ' ' + body)
ccxt.base.errors.InsufficientFunds: hitbtc2 {"error":{"code":20001,"message":"Insufficient funds","description":"Check that the funds are sufficient, given commissions"}}

**Comment by kroitor** [comment]
Oh... you posted your key, please regenerate it...

**Comment by algoscale1** [comment]
wasnt it encoded in request?

**Comment by kroitor** [comment]
@algoscale1 nope, hitbtc sends it in plaintext (very basic encoding)

**Comment by algoscale1** [comment]
ohkay, will regenrate the keys. thanks

**Comment by kroitor** [comment]
@algoscale1 there's a typo in your posted code that makes me think like you're not posting the code that you're actually running:

```Python
# with that last quote it's a syntx error that shouldn't ↓ even run
hitbtc.create_limit_sell_order('BCH/BTC', 0.015, 0.094136' ) 
```

Let's try this, here's how a complete minimal code snippet should look like, properly formatted according to instructions:

```Python
from pprint import pprint
import ccxt

pprint('ccxt version:')
pprint(ccxt.__version__)  # will need your ccxt exact version number

exchange = ccxt.hitbtc2({
    'apiKey': 'xyz',
    'secret': 'xyz',
})

# this will ensure that this particular account has enough balance:
balance = exchange.fetch_balance()
pprint('BCH balance:')
pprint(balance['BCH']['free'])
pprint('BTC balance:')
pprint(balance['BTC']['free'])

exchange.verbose = True
order = exchange. create_limit_sell_order('BCH/BTC', 0.015, 0.094136)
```

Can you post all the output of the above (substitute the keys, just remove them) ?

**Comment by algoscale1** [comment]
hey issue resolved. thanks for your time

**Comment by kroitor** [comment]
@algoscale1 can you please tell what was the cause? Would be very helpful to others... Thx!
