### ISSUE TITLE
Yobit LOC and LOCX symbol inconsistency

### ISSUE THREAD

**Issue by dmig** [ccxt/ccxt#2521]
- CCXT version: 1.12.117
- Exchange: Yobit/Others

Symbol: LOC
LocoCoin on Yobit
LockChain on others

Please note: Yobit has LockChain under symbol LOCX, so probably this also should be renamed

**Comment by kroitor** [comment]
Most of Yobit tokens are fake. This exchange is famous for giving their ICO shitcoin tokens common names and for confusing users with token abbreviations "spoofed" as if those were actual existing real tokens. With Yobit you can't do funding (deposit/withdraw) for those tokens. So, please, take care.
