### ISSUE TITLE
Bug in set_market() function

### ISSUE THREAD

**Issue by alexsith** [ccxt/ccxt#2524]
Hello.
in def set_markets(self, markets, currencies=None):

self.currencies = self.deep_extend(currencies, self.currencies)
should be changed to
self.currencies = self.deep_extend(self.currencies, currencies)

because updated values has to override older one

p.s.
Actually I have question about it. Why do we try to save previous self.currencies structure? I think if exchange has fetch_currencies method then  it always returns full information in case if we execute load_markets(reload=True)->fetch_currencies()->set_markets(markets, currencies)

**Comment by kroitor** [comment]
Unfortunately, it's a lot more complicated than that...
Some exchanges will provide fees, limits, precision and fee info in currencies, some of them will provide that info info markets, therefore that info has to be preserved and mixed-in appropriately. We are currently reworking the loading callchain, explained here: https://github.com/ccxt/ccxt/pull/1835. I'd suggest to move this discussion to that post, closing this one, if you don't mind.

**Comment by alexsith** [comment]
Ok, I understand the purpose of merging, but anyway, in case if exchange change wallet status, for exa ple, it will not updated in self.currencies if I call load_markets(reload=True) and what I suggest is a simple fix compared with #1835-big-refactoring.
Thank you

**Comment by kroitor** [comment]
@alexsith we can't really put it the way you suggested, because we will lose the ability to override the currencies (which is necessary in a few places), thus it will break a few exchanges. However, we are close to merging the refactored version, hope to resolve it in shortest possible time. Thanks for your involvement!
