### ISSUE TITLE
Bit-z fetchOpenOrders Invalid Date

### ISSUE THREAD

**Issue by ljianyih** [ccxt/ccxt#2530]
Hi, when try to query fetchOpenOrders, Bit-Z is showing RangeError: Invalid Date. This error has been persisted for many days, but create orders and cancel orders has no problem when tested. I've checked the api of bit-z and ccxt, but not sure how to solve this issue, thanks.

bit-z api: https://www.bit-z.com/api.html
ccxt js: https://github.com/ccxt/ccxt/blob/master/js/bitz.js

- OS: Mac
- Programming Language version: javascript
- CCXT version: latest from unpkg
- Exchange: bitz
- Method: fetchOpenOrders

**Comment by kroitor** [comment]
Hi! How do you link against ccxt?

**Comment by ljianyih** [comment]
I'll be more specific next time. Using browser javascript - <script type="text/javascript" src="https://unpkg.com/ccxt"></script>
1.12.130

After initiated bitz, when I call the function
```fetchOpenOrders('HSR/BTC')```
this error appear
```Unhandled Promise Rejection: RangeError: Invalid Date```

**Comment by kroitor** [comment]
@ljianyih can you post your verbose output of the fetchOpenOrders call, according to this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

```JavaScript
// ...
exchange.verbose = true // set .verbose = true on the exchange
orders = await exchange.fetchOpenOrders('HSR/BTC') 
// ...
```

Need full verbose output with request + response + error stacktrace (without your keys) to resolve it.

**Comment by ljianyih** [comment]
Thanks for the verbose guide, and I have figured out the problem. As I use mainly safari, only safari shows that error, but works fine on chrome and mozilla. Here is the verbose details on safari. I'll just switch browser then, thanks a lot for the help~

```[Log] fetch: (ccxt.browser.js, line 1901)
 (8)
"bitz"
"POST"
"http://localhost:8080/https://www.bit-z.com/api_v1/openOrders"
"
Request:
"
{Content-type: "application/x-www-form-urlencoded"}
"
"
"api_key=12345&coin=hsr_btc&nonce=100001&timestamp=1523370772&sign=abcde"
"
"
[Log] handleRestResponse: (ccxt.browser.js, line 2012)
 (10)
"bitz"
"POST"
"http://localhost:8080/https://www.bit-z.com/api_v1/openOrders"
200
"OK"
"
Response:
"
Object

Access-Control-Allow-Origin: "*"

Connection: "close"

Content-Encoding: "gzip"

Content-Type: "application/json;charset=utf-8"

Date: "Tue, 10 Apr 2018 14:32:52 GMT"

Transfer-Encoding: "Identity"

Vary: "Accept-Encoding"

X-Cache: "bypass"

X-Final-Url: "https://www.bit-z.com/api_v1/openOrders"

X-Via-Jsl: "2b67061,-"

Object Prototype
"
"
"
{\"code\":0,\"msg\":\"Success\",\"data\":[{\"id\":\"240608477\",\"price\":\"0.00079000\",\"number\":\"6.0000\",\"numberover\":\"6.0000\",\"flag\":\"sale\",\"status\":\"0\",\"datetime\":\"2018-04-10 22:32:53\"},{\"id\":\"240604661\",\"price\":\"0.00079000\",\"number\":\"6.0000\",\"numberover\":\"6.0000\",\"flag\":\"sale\",\"status\":\"0\",\"datetime\":\"2018-04-10 22:30:47\"}]}"
"
"
[Error] Unhandled Promise Rejection: RangeError: Invalid Date
	(anonymous function) (bitz.html:63)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJob```

**Comment by kroitor** [comment]
@ljianyih got it, thank you for taking time on this, I will fix safari asap, will get to it shortly.
