### ISSUE TITLE
BITZ get balance interface has been updated

### ISSUE THREAD

**Issue by jed057** [ccxt/ccxt#2537]
- OS:
- Programming Language version: all
- CCXT version: latest
- Exchange: bitz
- Method: fetch_balance()

Previously bitz api get balance interface only provide total balance information for each coin. This has been updated recently so frozen and available data are provided as well. Thus the bitz fetch_balance method requires an update accordingly.

**Comment by kroitor** [comment]
FIxed and updated in 1.12.141. Thank you!

**Comment by jed057** [comment]
thanks very much!

**Comment by kroitor** [comment]
@jed057 let us know if you have any difficulties with it. Thx for reporting!
