### ISSUE TITLE
New Exchange: graviex

### ISSUE THREAD

**Issue by crackfoo** [ccxt/ccxt#2538]
uri: https://graviex.net
api: https://graviex.net/api/v2/
guide: https://graviex.net/documents/api_v2?lang=en

**Comment by scottie** [comment]
I would second this vote

**Comment by wiktorglowacki** [comment]
@kroitor Hi Igor, any chance to take another look at Graviex? They have updated API available here: https://graviex.net/documents/api_v3

**Comment by cod3gen** [comment]
> @kroitor Hi Igor, any chance to take another look at Graviex? They have updated API available here: https://graviex.net/documents/api_v3

I have updated to v3 api in my pull request, but i have not cleaned the code up properly yet. Feel free to contribute.. #4548

**Comment by wiktorglowacki** [comment]
@cod3gen all I can offer is some small btc contribution to speed things up as I'm not able to code myself.

**Comment by kroitor** [comment]
@wiktorglowacki pardon for the delays on my side, hope to get to it asap!

**Comment by wiktorglowacki** [comment]
@kroitor you just got yourself a new supporter. I really appreciate your work mate.

**Comment by frosty00** [comment]
no volume
