### ISSUE TITLE
lbank fetchBalance returns lowercase currency codes

### ISSUE THREAD

**Issue by ljianyih** [ccxt/ccxt#2541]
Some of the Lbank functions returns market symbol in lower case (all other ccxt exchanges use upper case i think), i.e. fetchBalance() returns:

```
btc: {free: 0, used: 0, total: 0}
eth: {free: 0, used: 0, total: 0}
```

- OS: MacOS
- Programming Language version: javascript
- CCXT version: 1.12.131
- Exchange: lbank
- Method: fetchBalance

**Comment by kroitor** [comment]
@ljianyih thanks for reporting! Will fix shortly!
