### ISSUE TITLE
KNC is KingN Coin on Yobit, but KyberNetwork everywhere else

### ISSUE THREAD

**Issue by ighunter** [ccxt/ccxt#2545]
Hello,

Coinmarketcap has them both as KNC, but KyberNetwork's market cap is significantly larger.

As far as I can tell, only Yobit has KingN Coin, trading as KNC/BTC, KNC/USD, and KNC/ETH.

Was mentioned in #1330, but not for specific exchange(s).

- OS: Windows 10
- Programming Language version: Javascript (ES6)
- CCXT version: Latest
- Exchange: Yobit
- Method: loadMarkets()

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/issues/2521#issuecomment-379747588
