### ISSUE TITLE
Bibox latest updates on fetchBalance didn't get parsed

### ISSUE THREAD

**Issue by ljianyih** [ccxt/ccxt#2550]
I'm trying bibox and it works well, but just after some latest ccxt update, the fetchBalance didn't get parsed and didn't return the balance array with free, used, and total (nothing return for positive balance), only returning the original object with "info".

The returned info object structure using 0.01 as sample:

```
{"result":[{"result":{"total_btc":"0.01","total_cny":"0.01","total_usd":"0.01",
"assets_list":[{"coin_symbol":"BTC","BTCValue":"0.01","CNYValue":"0.01","USDValue":"0.01","balance":"0.01","freeze":"0.01"},
{"coin_symbol":"BIX","BTCValue":"0.01","CNYValue":"0.01","USDValue":"0.01","balance":"0.01","freeze":"0.01"},
```

- OS: Mac
- Programming Language version: javascript
- CCXT version: 1.12.147
- Exchange: bibox
- Method: fetchBalance()

**Comment by kroitor** [comment]
Can you post verbose output of it, plz?

**Comment by kroitor** [comment]
Nevermind, will fix it shortly. Thx
