### ISSUE TITLE
Southexchange fetchBalance

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#2555]
- OS: Win 7
- Programming Language version: JS
- CCXT version: 1.12.153
- Exchange: Southexchange 
- Method: fetchBalance

Hello! Seems that "used" and "total" balances on Southexchange displayed incorrectly.
Now:
            let free = parseFloat (balance['Available']);
            let used = parseFloat (balance['Unconfirmed']);
            let total = this.sum (free, used);

balance['Unconfirmed'] shows unconfirmed deposits.

Probably it should be:
            let free = parseFloat (balance['Available']);
            let total = parseFloat (balance['Deposited']);
            let used = parseFloat (total-free);

**Comment by kroitor** [comment]
Fixed in 1.12.158. Thanks for your feedback!
