### ISSUE TITLE
XRB should be rewritten to NANO

### ISSUE THREAD

**Issue by jorijnsmit** [ccxt/ccxt#2561]
The manual explains that some symbols get rewritten automatically (e.g. XBT, DSH). I think this should be the case for XRB as wel. RaiBlocks went through a rebranding and are now called NANO. Confusingly enough `binance.fetchBalance()['info']` returns NANO results whereas `binance.fetchBalance()['total']` returns XRB.

Digging through the code I think this pair is actually just defined the wrong way around: https://github.com/ccxt/ccxt/blob/4c5df8e9b70f2cbd4fb2029066a0336fd2eee804/python/ccxt/binance.py#L264

- OS: macOS
- Programming Language version: Python
- CCXT version: 1.12.156
- Exchange: `binance`
- Method: `fetchBalance()`

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/issues/2556

Hope this answers your question )

**Comment by kroitor** [comment]
UPD. Added a few more clarifications to this.

**Comment by kroitor** [comment]
One of the reasons for not using the NANO code is that CoinMarketCap uses XRB, and NANO designates a different token there.

**Comment by arielorvits** [comment]
@kroitor 
not sure u're right regarding CMC
https://coinmarketcap.com/currencies/nano/
https://coinmarketcap.com/search/?q=xrb

**Comment by kroitor** [comment]
<img width="1178" alt="screen shot 2018-04-13 at 06 02 09" src="https://user-images.githubusercontent.com/1294454/38714738-3f8082b4-3ee0-11e8-8758-0158b47dbd56.png">

@arielorvits yep, thank you! Looks like CMC actually uses NANO now, and we will probably use NANO as well starting from 1.13. Will fix it soon and will let you know.
