### ISSUE TITLE
anxpro fetchMarkets() results not wrapped in array

### ISSUE THREAD

**Issue by kyletan7** [ccxt/ccxt#2565]
The anxpro and bitbank exchange returns its markets wrapped in an object instead of an array.  Probably a few other exchanges too, but these are the two I've encountered so far having this issue.

**Comment by kroitor** [comment]
You should use loadMarkets instead, as documented in the Manual: 

- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

And then access then with `.markets` and documented methods.

Let us know if it does not answer your question. Thx!
