### ISSUE TITLE
Independent Reserve createOrder authentication fail

### ISSUE THREAD

**Issue by tuyet130953** [ccxt/ccxt#2567]
OS:  Ubuntu 16.04
Programming Language version: node JS
CCXT version: 1.12.162
Exchange: Independent Reserve
Method: createOrder - authentication error

fetchBalance works however createOrder returns authentication error - my guess is a bug in the sha signing.

```
try {
var order = await IR.createOrder ('BTC/AUD', 'limit', 'buy', 0.1, 15000)   
} 
catch (error) {
console.log (error)
}
```

{ Error: independentreserve POST https://api.independentreserve.com/Private/PlaceLimitOrder 400 Bad Request {"Message":"Invalid credentials"} (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)
    at independentreserve.defaultErrorHandler (/home/smartadmin/Dropbox/CryptoArb/node_modules/ccxt/js/base/Exchange.js:488:15)
    at response.text.then (/home/smartadmin/Dropbox/CryptoArb/node_modules/ccxt/js/base/Exchange.js:513:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: ExchangeNotAvailable] }
Exit: Trade Error

**Comment by kroitor** [comment]
Hi! Sorry for a long wait, will get to this and will debug it soon. Thx for your patience.

**Comment by tuyet130953** [comment]
fetchBalance also no longer works. getting same error as above - "Invalid credentials".

**Comment by kroitor** [comment]
Hope to resolve this shortly, will let you know when it's there. Being a little overloaded now. Sorry for the inconvenience.

**Comment by tuyet130953** [comment]
@kroitor all good mate, just reporting my findings

**Comment by holim** [comment]
@kroitor any updates on this please? keen to get this working on independent reserve
