### ISSUE TITLE
New Exchange: topperex

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#2568]
uri: https://www.topperex.com/
doc: ask around.
country: china/ UK

**Comment by kroitor** [comment]
No API apparently, I'd close this for now, if you don't mind. Feel free to reopen this if needed.

**Comment by jjhesk** [comment]
@kroitor i think their api is confidential for internal use only for now. I will do more research about this exchange..

**Comment by kroitor** [comment]
@jjhesk thank you! Plz let us know if you find anything!

**Comment by jjhesk** [comment]
here is the doc: https://documenter.getpostman.com/view/2597586/topperex/RW1bmyPW

**Comment by An-Net** [comment]
The exchange web site is not available anymore.
