### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by filtr0w** [ccxt/ccxt#2569]
hi guys

trying to install latest version

OS X 10.12.16
CCXT BUILD 1.12.162
NPM

this is what i did

git clone https://github.com/ccxt/ccxt.git
cd ccxt
npm install
npm run build

all went fine until this

> ccxt@1.12.162 qa /Users/filtro/ccxt
> cp package.json LICENSE.txt keys.json python && npm run check-python-syntax && npm run check-php-syntax

> ccxt@1.12.162 check-python-syntax /Users/filtro/ccxt
> cd python && tox -e qa && cd ..

sh: tox: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ccxt@1.12.162 check-python-syntax: `cd python && tox -e qa && cd ..`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ccxt@1.12.162 check-python-syntax script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/filtro/.npm/_logs/2018-04-14T04_25_49_540Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ccxt@1.12.162 qa: `cp package.json LICENSE.txt keys.json python && npm run check-python-syntax && npm run check-php-syntax`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ccxt@1.12.162 qa script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/filtro/.npm/_logs/2018-04-14T04_25_49_562Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ccxt@1.12.162 build: `npm run export-exchanges && npm run vss && npm run pandoc-python-readme && npm run pandoc-doc-readme && npm run pandoc-doc-manual && npm run pandoc-doc-install && npm run pandoc-doc-exchanges && npm run pandoc-doc-exchanges-by-country && npm run check-js-syntax && npm run transpile && npm run qa && npm run update-badges && npm run browserify`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ccxt@1.12.162 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/filtro/.npm/_logs/2018-04-14T04_25_49_577Z-debug.log

log file attached too
[2018-04-14T04_25_49_577Z-debug.log](https://github.com/ccxt/ccxt/files/1910012/2018-04-14T04_25_49_577Z-debug.log)

**Comment by kroitor** [comment]
- If you want to just use the library and you are going to install it from NPM, then you should do it with `npm install ccxt`. That command is enough to start using the library and to build your programs on top of it.
- If you going to develop the library and contribute to its source code then you should clone the repository and install from source. To do it properly you should read this entire CONTRIBUTING doc for installation instructions: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md. In your particular case, the installer tells you that you're missing an installation of `tox` which is required for building the library from source: 
    > sh: tox: command not found

Let us know if this does not help. Thanks!
