### ISSUE TITLE
Timestamp null returned by fetch_l2_order_book

### ISSUE THREAD

**Issue by JT102** [ccxt/ccxt#2575]
- OS: Linux
- Programming Language version: PHP
- CCXT version: 1.12.154
- Exchange: hitbtc/huobipro/all?
- Method: fetch_l2_order_book

After update realised that **timestamp** fields are empty. It was always filled before. Returned variable contains:
```
  }
  ["timestamp"]=>
  NULL
  ["datetime"]=>
  NULL
  ["nonce"]=>
  NULL
}
```
My scripts were relying on timestamps to check for the updates. Is it exchanges that changed output or something changed in ccxt? If 2nd - is there a way (like changes log) to track important changes?

**Comment by kroitor** [comment]
Hi!

Please check this: https://github.com/ccxt/ccxt/issues/2444#issuecomment-378457783

Let us know if this does not answer your question. Thanks!
