### ISSUE TITLE
Python add stoploss to bitmex

### ISSUE THREAD

**Issue by 2803media** [ccxt/ccxt#2577]
Hi 
I try to add a stoploss and a takeprofit in ccxt python for bitmex exchange but can't find any info in the docs, any help?

I try this for market stoploss but it failed..
```
params = {'stopPx': amountstop}
orderstop = bitmex().create_order('BTC/USD', type='market', side='sell', amount=amount,params)
        
```

Thanks

**Comment by kroitor** [comment]
Hi!

Your question is answered here: https://github.com/ccxt/ccxt/issues/2499#issuecomment-379829876

Let us know if it does not help. Thx!

**Comment by 2803media** [comment]
Hi kroitor 
Thanks! It's working, I forget to add the None for price for a StopMarket!

```
    symbol = 'BTC/USD'  # bitcoin contract according to bitmex futures coding
    type = 'Stop'  # or 'market', or 'Stop' or 'StopLimit'
    side = 'sell'  # or 'buy'
    amount = 1.0
    price = None  # or None

    # extra params and overrides
    params = {
       'stopPx': 6000.0,  # if needed
    }

    order = bitmex().create_order(symbol, type, side, amount, price, params)
    print(order)
```

**Comment by kroitor** [comment]
@2803media thanks for reporting back! Let us know if you have any other difficulties with it!
