### ISSUE TITLE
How can I track an order?

### ISSUE THREAD

**Issue by PerterPon** [ccxt/ccxt#2580]
When I create an order, I want to know when my order was complete, I find a user stream method on websocket at Binance and Bitfinex，I can listen the event and I know when my order completed, I checked CCXT's doc, I only found `fetchOrder` method, so, in ccxt, I need to loop `fetchOrder` method for a while before my order was completed? Thank you every much.

- OS: MACOS
- Programming Language version: Nodejs 8.1.1
- CCXT version: 1.12.x
- Exchange: Bitfinex, Binance, Huobi
- Method: fetchOrder

**Comment by kroitor** [comment]
Hi!

From the doc: https://github.com/ccxt/ccxt/wiki/Manual

> Full public and private HTTP REST APIs for all exchanges are implemented. WebSocket and FIX implementations in JavaScript, PHP, Python and other languages coming soon.

More about it here: #56.

So, ...

> I need to loop fetchOrder method for a while before my order was completed?

Yes, with REST you should do polling in a loop. Your practical options:

- either call fetchOrder in a loop
- or add your own layer of ws-support
- or wait until we implement it in ccxt
- or help us implement it ) 

It's all there, linked above. Hope it answers your question. Let us know if not. Thx!

**Comment by PerterPon** [comment]
Got, CCXT is every cool

**Comment by tregismoreira** [comment]
Hi @kroitor, is the websocket already implemented on CCXT?

**Comment by eugenioclrc** [comment]
> Hi @kroitor, is the websocket already implemented on CCXT?

Only in the CCXT.PRO
