### ISSUE TITLE
fetch_my_trades returns invalid feeCurrency

### ISSUE THREAD

**Issue by AnAndrey** [ccxt/ccxt#2586]
- OS: Windows 10
- Programming Language version: Python
- CCXT version: 
- Exchange: kucoin
- Method: fetch_my_trades

I found inconsistency in feeCurrency determination logic.
I have several "ETH/BTC" trades with "SELL" and "BUY" sides. And for all them fetch_my_trades returns "ETH" as feeCurrency. However fetch_closed_orders returns different feeCurrency depends on the side of closed order.

**Comment by kroitor** [comment]
Let us know if you have the same difficulties with the most recent version of it. Thx!

**Comment by AnAndrey** [comment]
hi! Thank you for fast reaction!
I checked '1.12.178' and nothing has changed))
Actually I assumed you will share same feeCurrency determination logic  between fetch_closed_orders and fetch_my_trades, cause it's similar and it works for fetch_closed_orders. But you decided to deprecate problematic fetch_my_trades function without fixing. Oh it's funny and sad at the same time)) 
fetch_my_trades returns trade ID ('oid' field) and order ID ('orderOid' field) and it's very important for our trading system. It helps to distinguish partially filled trades and connect them with initial order.

Is there any chance to have fetch_my_trades with feeCurrency determination logic from fetch_closed_orders?

**Comment by kroitor** [comment]
> Is there any chance to have fetch_my_trades with feeCurrency determination logic from fetch_closed_orders?

Yes, but in order to do so, I will need to see your verbose output. With current version the feeCurrency is expected to be undefined, and what you say above contradicts the expectation, therefore I need your verbose output to debug the parser code. Can you post the output of the fetch_my_trades call?

```Python
exchange.verbose = True
trades = exchange.fetch_my_trades(...) 
```

↑ plz show the entire output of the above: the request and the response (no need for your keys).

**Comment by AnAndrey** [comment]
Verbose output:

Request: GET https://api.kucoin.com/v1/deal-orders?symbol=ETH-BTC {'KC-API-KEY': 'some_key', 'KC-API-NONCE': 'nonce', 'KC-API-SIGNATURE': 'some_signature', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.kucoin.com/v1/deal-orders?symbol=ETH-BTC 200 {'Date': 'Tue, 17 Apr 2018 12:00:50 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Accept-Language', 'Access-Control-Allow-Methods': 'POST, GET, PUT, OPTIONS, DELETE, PATCH', 'Access-Control-Max-Age': '86400', 'KC-NODE': 'localhost'} {"success":true,"code":"OK","msg":"Operation succeeded.","timestamp":1523966450200,"data":{"total":1356,"firstPage":true,"lastPage":false,"datas":[{"coinType":"ETH","createdAt":1523896045000,"amount":0.001,"dealValue":6.322E-5,"fee":6.0E-8,"dealDirection":"BUY","coinTypePair":"BTC","oid":"5ad4ceedb6f51c4d20fe217a","dealPrice":0.063222,"orderOid":"5ad4cea1b6f51c4eb831274b","feeRate":0.001,"direction":"SELL"},{"coinType":"ETH","createdAt":1523895967000,"amount":0.001,"dealValue":6.316E-5,"fee":1.0E-6,"dealDirection":"BUY","coinTypePair":"BTC","oid":"5ad4ce9fb6f51c4d20fe20f3","dealPrice":0.06315832,"orderOid":"5ad4ce9eb6f51c4e0a9e8af7","feeRate":0.001,"direction":"BUY"},{"coinType":"ETH","createdAt":1523891509000,"amount":0.001001,"dealValue":6.322E-5,"fee":6.0E-8,"dealDirection":"SELL","coinTypePair":"BTC","oid":"5ad4bd35b6f51c4d20fe0895","dealPrice":0.06315911,"orderOid":"5ad4bd349dda157b7c429281","feeRate":0.001,"direction":"SELL"},{"coinType":"ETH","createdAt":1523882563000,"amount":0.001,"dealValue":6.33E-5,"fee":1.0E-6,"dealDirection":"SELL","coinTypePair":"BTC","oid":"5ad49a43b6f51c4d20fdd444","dealPrice":0.06330199,"orderOid":"5ad499f3b6f51c4eb831201a","feeRate":0.001,"direction":"BUY"},{"coinType":"ETH","createdAt":1523882226000,"amount":0.001,"dealValue":6.326E-5,"fee":6.0E-8,"dealDirection":"SELL","coinTypePair":"BTC","oid":"5ad498f2b6f51c4d20fdd205","dealPrice":0.06325799,"orderOid":"5ad498f19dda157dd46282b5","feeRate":0.001,"direction":"SELL"},{"coinType":"ETH","createdAt":1523882064000,"amount":0.001,"dealValue":6.326E-5,"fee":1.0E-6,"dealDirection":"SELL","coinTypePair":"BTC","oid":"5ad49850b6f51c4d20fdd159","dealPrice":0.06325798,"orderOid":"5ad49846b6f51c4f5cb6777a","feeRate":0.001,"direction":"BUY"},{"coinType":"ETH","createdAt":1523882058000,"amount":0.001,"dealValue":6.326E-5,"fee":6.0E-8,"dealDirection":"SELL","coinTypePair":"BTC","oid":"5ad4984ab6f51c4d20fdd14c","dealPrice":0.06325799,"orderOid":"5ad49849b6f51c4e0a9e835c","feeRate":0.001,"direction":"SELL"},{"coinType":"ETH","createdAt":1523881664000,"amount":0.001,"dealValue":6.324E-5,"fee":1.0E-6,"dealDirection":"SELL","coinTypePair":"BTC","oid":"5ad496c0b6f51c4d20fdce54","dealPrice":0.06323553,"orderOid":"5ad496479dda157d4011bb62","feeRate":0.001,"direction":"BUY"},{"coinType":"ETH","createdAt":1523880648000,"amount":0.001,"dealValue":6.337E-5,"fee":6.0E-8,"dealDirection":"BUY","coinTypePair":"BTC","oid":"5ad492c8b6f51c4d20fdca09","dealPrice":0.06337058,"orderOid":"5ad492a59dda157d4011bb03","feeRate":0.001,"direction":"SELL"},{"coinType":"ETH","createdAt":1523879114000,"amount":0.001,"dealValue":6.325E-5,"fee":1.0E-6,"dealDirection":"SELL","coinTypePair":"BTC","oid":"5ad48ccab6f51c4d20fdc374","dealPrice":0.06324891,"orderOid":"5ad488939dda157dd46280b2","feeRate":0.001,"direction":"BUY"},{"coinType":"ETH","createdAt":1523878193000,"amount":0.001,"dealValue":6.345E-5,"fee":6.0E-8,"dealDirection":"BUY","coinTypePair":"BTC","oid":"5ad48931b6f51c4d20fdbee5","dealPrice":0.06344925,"orderOid":"5ad48898b6f51c4f5cb675b9","feeRate":0.001,"direction":"SELL"},{"coinType":"ETH","createdAt":1523877928000,"amount":0.001,"dealValue":6.329E-5,"fee":6.0E-8,"dealDirection":"BUY","coinTypePair":"BTC","oid":"5ad48828b6f51c4d20fdbdda","dealPrice":0.063289,"orderOid":"5ad4881db6f51c4d20a23244","feeRate":0.001,"direction":"SELL"}],"currPageNo":1,"limit":12,"pageNos":113}}

**Comment by AnAndrey** [comment]
It works in 1.12.179. 
Thanks for help.
