### ISSUE TITLE
hadax: ccxt\ExchangeError: parseMarkets not found

### ISSUE THREAD

**Issue by LorFor** [ccxt/ccxt#2591]
- OS: Ubuntu 16.04.4 LTS
- Programming Language version: PHP 7.1.16
- CCXT version: 1.12.172
- Exchange: hadax
- Method: parseMarkets

PHP Fatal error:  Uncaught ccxt\ExchangeError: parseMarkets not found in ccxt/php/Exchange.php:1714
Stack trace:
#0 ccxt/php/hadax.php(38): ccxt\Exchange->__call('parseMarkets', Array)
#1 ccxt/php/Exchange.php(1108): ccxt\hadax->fetch_markets()
#2 {main}
  thrown in /home/satori/CryptoCoins/ccxt_lnx/ccxt/php/Exchange.php on line 1714

**Comment by kroitor** [comment]
Fixed in most recent version of ccxt 1.12.178. Thanks for reporting!
