### ISSUE TITLE
Bitstamp returns wrong or outdated orderbook occasionally

### ISSUE THREAD

**Issue by Felipe-Mangueira** [ccxt/ccxt#2593]
- OS: Windows and Linux
- Programming Language version: Python 3
- CCXT version: latest
- Exchange: Bitstamp
- Method: fetch_order_book

Hi,@kroitor. Sorry for disturbing you with a likely unrelated ccxt question, but I notice that in the recent past Bitstamp fetch_order_book method is returning a outdated or a poorly built orderbook, so that I cannot trust in the Bitstamp response. I built some workarounds to ignore the orderbook in these cases, timestamp test included, but I am still facing problems with the response reliability. Do you know any methods or tricks, with ccxt library or not, that I can use to ensure the orderbook requested is trustworthy? Case not, please just ignore and close the topic.

Thanks in advance.

**Comment by kroitor** [comment]
> but I notice that in the recent past Bitstamp fetch_order_book method is returning a outdated or a poorly built orderbook

This is a very strong claim and in order to actually advise any workarounds I would ask you to first show some formal proofs. In other words, you have to demonstrate that there is some Bitstamp or ccxt error (giving faulty data) and not your faulty interpretation of the data.

**Comment by alexsith** [comment]
Hello. Have the same issue. I am sure it is exchange issue, maybe their slave-db server was out-of-sync and periodically they returns old data. It happened also with yobit and hitbtc early. In this case simple solutuion is just turn-off market or exchange for a while.

**Comment by alexsith** [comment]
"Kindly note that we have been experiencing some technical difficulties, however, the issue has now been resolved."  (c) Bitstamp support

**Comment by Felipe-Mangueira** [comment]
Hi, guys.

@kroitor, I'm sure the error is only correlated with Bitstamp, not with ccxt library, however right now is impossible to provide some proofs because the bitstamp apparently is returning real data again and I didn't reserved the JSON returned at the moment of the issue creation. Once the error is noticed again, I'll report back to you. Anyway, the bids and asks returned from BCH/USD market yesterday was clearly out of the market: the last ticker was exactly 758.17 USD/BCH while the best ask from orderbook was around 752~753 USD/BCH, negotiated price of hours ago.

The date (date) returned by the following code is generated by the moment the response is send or is there any relation with the data send? Can I trust this date?
```
bitstamp = ccxt.bitstamp({'nonce': lambda: int(time.time() * 1000)})
date = bitstamp.last_response_headers['Date']
print(date)
```
Or may I trust on this timestamp?
```
bitstamp = ccxt.bitstamp({'nonce': lambda: int(time.time() * 1000)})
time = bitstamp.fetch_order_book('BCH/USD')['timestamp]
print(time)
```


> "Kindly note that we have been experiencing some technical difficulties, however, the issue has now been resolved." (c) Bitstamp support

@alexsith, what is the date of this answer?

**Comment by Felipe-Mangueira** [comment]
I just did one test with the response of the two ways of getting the timestamp in order to compare with the real timestamp:
```
bitstamp = ccxt.bitstamp({'nonce': lambda: int(time.time() * 1000)})
timestamp_from_book = bitstamp.fetch_order_book('BCH/USD')['timestamp']
timestamp_from_response = datetime.datetime.timestamp(datetime.datetime.strptime(bitstamp.last_response_headers['Date'], '%a, %d %b %Y %H:%M:%S %Z'))
timestamp_from_time = time.time()
```
And get the following results:
```
timestamp_from_book = 1523972532000
timestamp_from_response = 1523983334
timestamp_from_time = 1523972534
```

**Comment by Felipe-Mangueira** [comment]
The main doubt is: Even the three timestamps are very close to each other (timestamp_from_response not considering local timezone), should I trust the information returned because of this timestamps are correct?

**Comment by kroitor** [comment]
> The main doubt is: Even the three timestamps are very close to each other (timestamp_from_response not considering local timezone), should I trust the information returned because of this timestamps are correct?

Well, the general answer to that is: it will always take some time to deliver the timestamp in the orderbook response to you, so the timestamp in the response will always have some lag behind the current time on your machine (assuming all clocks are synched). The time it may take (the delay) depends on links, communications, the load on the exchange, the time of day, public interest and many other factors... So the delay between the moment the exchange timestamps the response and the moment you get that response – that delay can vary from several milliseconds to a second or more. 

Thus, whether "correct" or "incorrect" – that depends on your decision: how old an orderbook should be in order for you to discard it?

**Comment by Felipe-Mangueira** [comment]
> Thus, whether "correct" or "incorrect" – that depends on your decision: how old an orderbook should be in order for you to discard it as "not relevant anymore"?

I think up to 2000 miliseconds or something like that. but I'm afraid that I didn't make myself clear. 

I understand there is a lag between the timestamp whose information was generated and the timestamp at which the information arrives to the user.

However, my point is: the timestamp returned from Bitstamp on the orderbook (book['timestamp]) or the timestamp retrieved from bitstamp.last_response_headers['Date'] represents the information inside the orderbook or represents the moment at which this information is sent?

a) Case it represents the information inside the orderbook, that's ok and the user can trust the orderbook is current (plus the lag);

b) Case it represents the moment at which this information is sent, it means nothing beyond the current timestamp, and this measure is no suitable to check the orderbook reliability.

The fact is that Bitstamp was returning orderbooks from hours ago, not seconds or miliseconds, and that is the reason of my worries, not the lag. So, should I use timestamp in order to detect this anomaly?

**Comment by danieldourado** [comment]
@Felipe-Mangueira I think that can only be answered by Bitstamp crew themselves...

**Comment by danieldourado** [comment]
I did a quick test, and the timestamp value from orderbook is always the same as Date.now(), so it means the timestamp value is not from the exchange, but set by ccxt when it gets the response?

This code always prints 0:
console.log((order_book.timestamp-Date.now()))

**Comment by kroitor** [comment]
@danieldourado you should update your version of ccxt, your question is explained here: https://github.com/ccxt/ccxt/issues/2444#issuecomment-378457783

**Comment by kroitor** [comment]
@Felipe-Mangueira 

> the timestamp returned from Bitstamp on the orderbook (book['timestamp]) or the timestamp retrieved from bitstamp.last_response_headers['Date'] represents the information inside the orderbook or represents the moment at which this information is sent?

- `orderbook['timestamp']` is the time when the exchange generated this orderbook response (before sending it to you). This may be missing (`undefined/None/null`), as documented in the Manual, not all exchanges provide a timestamp. If it is defined, then it is the UTC timestamp **in milliseconds** since 1 Jan 1970.
- `.last_response_headers['Date']` is the date-time string of the last HTTP response received (from HTTP headers). The 'Date' parser should respect the timezone designated there. The precision of the date-time is 1 second, 1000 milliseconds. This date should be set by the exchange server when the message originated according to the following standards:
    - https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.18 – , 
    - https://tools.ietf.org/html/rfc1123#section-5.2.14
    - https://tools.ietf.org/html/rfc822#section-5
- **also mind your local `time.time()` precision and timezone**

Hope this answers your question. I would close this issue for now, if you don't mind. Feel free to reopen it if needed or just ask questions, if you have more. We will be happy if you keep reporting any inconsistency you may encounter. Thx!

**Comment by Felipe-Mangueira** [comment]
Thank you for your replies, @kroitor. We could keep this issue closed: I'm satisfied for now, although it's not possible to judge the quality of the received information from Bitstamp . I already ask this question to the Bitstamp's crew. If I have any new relevant reply from them, I'll report back here to the intererested people with a more consistent perspective. I use ccxt libray so often, so if I detect something unusual, I'll let you know. Thanks.

**Comment by langabi** [comment]
Quick follow-up on this:
- I've been seeing same issue; it got especially bad yesterday (25 April) where about a third of calls to fetch_order_book() on bitstamp were at random returning data that was 2-3 hours out of date. So I imagine they have a server pool and one isn't updating right. It's better now, but still occasionally happens
- you CAN detect this looking at the timestamp as returned from bitstamp and included in the fetch_order_book() return structure. I have put a filter to reject all returned results with timestamp return value more than 30 seconds away from my current server time -- this is big enough to handle lag topics, but small enough to mean I'm using recent data only. That solved my problem.

**Comment by kroitor** [comment]
@langabi thank you for the info!
