### ISSUE TITLE
code shows errors

### ISSUE THREAD

**Issue by jackyxie** [ccxt/ccxt#2598]
https://github.com/ccxt/ccxt/blob/da85ed85416723fd3b556d8b9e351da737e41ec5/php/Exchange.php#L1359

PHP code has error in code. $order should be $orders

**Comment by kroitor** [comment]
> $order should be $orders

It's the opposite, $orders should be $order in the line above ;) Thx for reporting, uploaded a fix for it, will be available in the new version in 5-10 minutes.
