### ISSUE TITLE
Cryptopia: order goes through after timeout is reported

### ISSUE THREAD

**Issue by stabilus** [ccxt/ccxt#2599]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Win 7 (64 bit)
- Programming Language version: Python 3.6.4. (32 bit)
- CCXT version: 1.12.179
- Exchange: Cryptopia
- Method: createLimitBuyOrder

I've noticed that Cryptopia is currently very slow responding on both the API and the webbrowser side.
As a consequence, orders placed time out (error: cryptopia POST https://www.cryptopia.co.nz/api/SubmitTrade HTTPSConnectionPool(host='www.cryptopia.co.nz', port=443): Read timed out. (read timeout=10)

Reacting with my code to the timeout, I assume the transaction did not go through and I don't record the transaction. 

It turns out that the transactions sometimes (more often than not) do go through after the timeout has occurred and the limit order is placed.

Since there is no result returned from the function, I don't have access to an order ID, so I cannot check for such a situation.

Is there a way to catch this and deal with it? Or could I increase the timeout limit?

**Comment by kroitor** [comment]
Handling this particular situation is described here: https://github.com/ccxt/ccxt/wiki/Manual#requesttimeout

Let us know if it does not answer your question. Thx!
