### ISSUE TITLE
Help integrating TradingView chart with ccxt

### ISSUE THREAD

**Issue by sbarry50** [ccxt/ccxt#2601]
- OS: macOS High Sierra
- Programming Language version: Laravel 5.6
- CCXT version: latest
- Exchange: Binance, GDAX
- Method: N/A

Hi, I'm just trying to get some TradingView charts working on a project I'm working on with data from a few exchanges, Binance and GDAX to start, and I'm wondering if ccxt would be a good source for the data those charts require if anyone is familiar with setting those up. 

If so, can anyone point me in the right direction for how to go about that besides the TradingView docs? Maybe a walkthrough or tutorial or anything? Or even someone to possibly hire to help with it? The project is being built with Laravel.

Thanks.

**Comment by jjhesk** [comment]
i have been browsing the tools as well. I think you will need to cache or premine the chart data into a cvs or some files before doing the charting.. for realtime charting i think that will have to do with both realtime k-line api and the cvs file of specific market.

**Comment by kroitor** [comment]
>  I'm wondering if ccxt would be a good source for the data those charts require if anyone is familiar with setting those up

We've added support for TradingView format into the library version 1.13.31.

Let us know if this does not help:

- https://github.com/ccxt/ccxt/blob/master/php/Exchange.php#L1458
- https://github.com/ccxt/ccxt/blob/master/examples/php/trading-view.php
- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L596
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L1048

Closing this for now, if you don't mind. Thanks!
