### ISSUE TITLE
Editing a order

### ISSUE THREAD

**Issue by manisharora** [ccxt/ccxt#2603]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: ubuntu 16.01
- Programming Language version: python 3.5
- CCXT version: 1.12.180
- Exchange: bitfinex
- Method: editorder

i am unable to find any way to edit a limit order which is not yet filled or partially filled.

**Comment by kroitor** [comment]
@manisharora use the editOrder / edit_order method, the args are described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#placing-orders

Let us know if this does not answer your question. Thx!

**Comment by xCuri0** [comment]
@kroitor there isn't any documentation there

**Comment by Princeton007** [comment]
I have the same question, still no documentation there, and I can't find any examples elsewhere. Who can help?

**Comment by kroitor** [comment]
@Princeton007 the unified method for this is called `editOrder`:

- https://github.com/ccxt/ccxt/blob/master/js/bitfinex.js#L769

**Comment by Princeton007** [comment]
@kroitor I'm using python, but anyway, I can't make it work to change an order, whatver I tried throws me different errors, I tried variables, and strings, see my 2 examples below. In my case I like to edit the stop price only whils leaving the rest untouched:
order = exchange.edit_order(order_id, 'BTC/USD', 'stop', 'sell', 8000, {'type': 'stop'})
order = exchange.edit_order(order_id, symbol=symbol_existing, type=type_existing, side=side_existing, sl_long, {'type': 'stop'})
leaving the arguments doesn't work  neither.. 
Maybe you can shed some light onto this and give an example of how it should look like correctly...
Many thanks in advance!

**Comment by kroitor** [comment]
@Princeton007 it should look like this (regardless of whether it's Python or JS – because https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support)

```Python
exchange.load_markets()  # preload them by hand (optional)

order_id = YOUR_ORDER_ID_HERE
symbol = 'BTC/USD'
type = 'limit'
side = 'sell'
amount = 123.45 # your new amount or None
price = YOUR_PRICE # your new price or None

# exchange.verbose = True  # uncomment me if you have errors

order = exchange.edit_order(order_id, symbol, type, side, amount, price)
```

↑ Plz try this and if it fails with an error – uncomment the `verbose` mode in the snippet above and paste your verbose request/response here (without your keys, but keeping everything else). Also, plz use [github markdown](https://guides.github.com/features/mastering-markdown/) for readability.

**Comment by Princeton007** [comment]
@koitor thanks, this helped a lot! Actually I am trading on margin so I added 
```python
params = { 'type': 'stop' }
order = exchange.edit_order(order_id, symbol, type, side, amount, price, params)
```

**Comment by kroitor** [comment]
@Princeton007 great! So, this issue resolved for you, right?

**Comment by Princeton007** [comment]
@kroitor Yes, many thanks! If I unterstand it correct, what CCXT is doing is deleting the existing order and placing a new one (the ID changes).

**Comment by kroitor** [comment]
@Princeton007 

>  If I unterstand it correct, what CCXT is doing is deleting the existing order and placing a new one (the ID changes).

In general – yes, that is what CCXT **would do** if the underlying exchange didn't have a specialized endpoint for editing orders – CCXT would then cancel the existing order and create a new one. However, if the underlying exchange offers a special API endpoint for order editing, CCXT uses it, and this is exactly the case with Bitfinex – so, what you see is not what CCXT does, but what the exchange does. In most cases, the default behavior of an exchange is to cancel the order and create a new one (with a new id), thus, CCXT is actually mimicking the behavior of the exchanges. Let me know if it does not answer the question.

**Comment by npomfret** [comment]
@kroitor it would be nice (I think) if ccxt would separate edit order v's cancel & replace order.  The difference being that the latter results in a new order id and the former doesn't.  

A few exchanges implement edit-order, you can typically change the price and amount, but that's it. And only if the order is 100% unfilled.

**Comment by kroitor** [comment]
@npomfret i would agree on cancel vs replace... We will consider adding `replaceOrder` in a non-breaking way... It is likely that we might need a period of migration from older versions with `editOrder` to newer versions with `replaceOrder`.

**Comment by kyjak** [comment]
So was this resolved and now we have a replaceOrder in place?
