### ISSUE TITLE
20 symbols on coinmarketcap representing multiple coins

### ISSUE THREAD

**Issue by OGrowli** [ccxt/ccxt#2604]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10 home
- Programming Language version: Python 3.5.2
- CCXT version: 1.12.160
- Exchange: coinmarketcap
- Method: exchange.load_markets()

There are 20 symbols on coinmarketcap that each represent 2 coins. When you accesss the cmc api through ccxt, only half of the 40 coins make it through.

These are the coins that are missing from the exchange.load_markets()
[('BET', 'dao-casino'), ('BTM', 'bytom'), ('CAN', 'canyacoin'), ('CMS', 'comsa-eth'), ('CMT', 'cybermiles'), ('CPC', 'cpchain'), ('ENT', 'eternity'), ('ETT', 'encryptotel'), ('FAIR', 'faircoin'), ('FID', 'fidelium'), ('GCC', 'global-cryptocurrency'), ('GTC', 'game'), ('HNC', 'helleniccoin'), ('KNC', 'kyber-network'), ('LBTC', 'litebitcoin'), ('PUT', 'profile-utility-token'), ('QBT', 'qbao'), ('RCN', 'ripio-credit-network'), ('XID', 'sphre-air'), ('XIN', 'mixin')]

The are the coins that do have data when exchange.load_markest() is called:
[('BET', 'betacoin'), ('BTM', 'bitmark'), ('CAN', 'content-and-ad-network'), ('CMS', 'comsa-xem'), ('CMT', 'comet'), ('CPC', 'capricoin'), ('ENT', 'entcash'), ('ETT', 'encryptotel-eth'), ('FAIR', 'fairgame'), ('FID', 'bitfid'), ('GCC', 'guccionecoin'), ('GTC', 'global-tour-coin'), ('HNC', 'huncoin'), ('KNC', 'kingn-coin'), ('LBTC', 'lightning-bitcoin'), ('PUT', 'putincoin'), ('QBT', 'cubits'), ('RCN', 'rcoin'), ('XID', 'international-diamond'), ('XIN', 'infinity-economics')]

Here is the code I used to figure this out:

import ccxt
import requests
import json

def rem_dupes(dupes):
    final_list = []
    for elem in dupes:
        if elem not in final_list:
            final_list.append(elem)
    return final_list

cmc = ccxt.coinmarketcap()
data_cx = cmc.load_markets() #cmc data from ccxt
r = requests.get('https://api.coinmarketcap.com/v1/ticker/?start=0&limit=3000')
data_cmc = json.loads(r.text) #all ranked coins from ccxt

#extract ranked coin data from data_cx:
ranked_coins_cx = []
for key,value in data_cx.items():
    ranked_coins_cx.append(value['info'])
ranked_coins_cx = rem_dupes(ranked_coins_cx)

#compare the length to data_cmc:
print('---------------------------------------')
print('full unique coin list from cmc api has ', len(data_cmc), ' coins')#1577
print('full unique coin list from cmc via ccxt api has ', len(ranked_coins_cx), ' coins')#1557
print('-------------------------------------------------')

#there is a difference of 20 coins, there are 20 coin pairs that have the same symbols
#here they are :
missing_coins = []#(symbol, id)
present_coins = []
symbols = []
for d in data_cmc:
    if  d not in ranked_coins_cx:
        missing_coins.append((d['symbol'], d['id']))
        symbols.append(d['symbol'])
for r in ranked_coins_cx:
    if r['symbol'] in symbols:
        present_coins.append((r['symbol'], r['id']))

print('-------------------------------')
print('coins missing from ccxt:')
print(missing_coins)#see above for output
print('missing coin counterparts included on ccxt:')
print(present_coins)#see above for output
print("------------End------------------")

**Comment by jorijnsmit** [comment]
Glad you found this out and put it here, I almost thought I was going crazy!

**Comment by kroitor** [comment]
This is how we resolve conflicts with symbolic names for markets and currencies:

1. When two exchanges have the same currency id for two different currencies or have a conflicting market id for two different markets, we will prefer the one having greatest market cap of the two – the other currency token will be renamed to its name according to CoinMarketCap. Thus `DAO.Casino` replaces `BET` where `BET` represents the DAO Casino, and the other `BET` (BetaCoin) is left as is. Same is true for several other currencies from your list – if you can't find them by a duplicate code (`BET`), then search them by their name (`DAO.Casino`).

2. When CoinMarketCap has two conflicting currency codes, the one with greatest market cap wins, and the other one will be renamed to corresponding CMC name.

Thx for reporting!

**Comment by cicoph** [comment]
The same for TIME
