### ISSUE TITLE
lykke fetchTicker()

### ISSUE THREAD

**Issue by Esc4pism** [ccxt/ccxt#2607]
Currently, lykke is using https://api.lykkex.com/api/AllAssetPairRates to fetch tickers, but this call only returns "bid" and "ask" prices, which i dont find accurate in many cases.

Could you change this to use https://public-api.lykke.com/api/Market instead? this call also returns "lastPrice" and "volume24H" for each pair. And would work for fetchTickers() as well.

docs: https://public-api.lykke.com/swagger/ui/index.html#/

**Comment by kroitor** [comment]
Fixed in #2988. Thanks to @valentinbora . Will be available in a new build within 5-10 minutes.
