### ISSUE TITLE
Bitstamp: fetchBalance() return "{ Error: bitstamp {"status":"error","reason":"API key not found","code":"API0001"}"

### ISSUE THREAD

**Issue by scredii** [ccxt/ccxt#2611]
Hi,

I'm using NodeJs to access the Bitstamp API, and I'm having trouble with the fetchBalance() and fetchMyTrade() function. I've created the API key on the Bitstamp account, and it worked a few days ago. 

However, in the past two days, the same API key has been returning the following error: Error: bitstamp {"status":"error","reason":"API key not found","code":"API0001"

Is this issue unique to this library or does it apply to all Bitstamp API users? 

`		let connect = new ccxt.bitstamp()
		connect.apiKey = exchange.api_key;
		connect.secret = exchange.secret;
		connect.uid = exchange.uid;
		(async () => {
			var ret = await connect.fetchMyTrades();`

**Comment by mkutny** [comment]
`apiKey`, not `api_key`:

```javascript
const connect = new ccxt.bitstamp({
    apiKey: exchange.api_key,
    secret: exchange.secret,
    enableRateLimit: true,
});
```

Not sure what is `exchange` and why would you need to set `uid` from it.

**Comment by kroitor** [comment]
> I've created the API key on the Bitstamp account, and it worked a few days ago.
> However, in the past two days, the same API key has been returning the following error: Error: bitstamp {"status":"error","reason":"API key not found","code":"API0001"

Just create a new one. They had a hard crash couple of days ago exactly, so, your issue is most likely related to this: https://github.com/ccxt/ccxt/issues/2593#issuecomment-381948845

> Is this issue unique to this library or does it apply to all Bitstamp API users?

It does apply to all users most likely.

Let us know if this does not help. Thx!
