### ISSUE TITLE
hitbtc vs. hitbtc2 in Python

### ISSUE THREAD

**Issue by lxj034000** [ccxt/ccxt#2614]
Hi, I am wondering what exactly is the difference between hitbtc and hitbtc2? I tried to compare their python codes and it seemed that  hitbtc2 is an upgrade version that is more consistent to other exchanges. Is that true? 

I would really appreciate your help!

**Comment by kroitor** [comment]
> Hi, I am wondering what exactly is the difference between hitbtc and hitbtc2?

Hi! The hitbtc v1 is the older deprecated version of their API, we have it in CCXT for backward compatibility, however, with newer code we would recommend to stick to v2 from the very beginning.

> I tried to compare their python codes and it seemed that hitbtc2 is an upgrade version that is more consistent to other exchanges. Is that true?

Yes, exactly.

Let us know if this does not answer your question. Thx!
