### ISSUE TITLE
Query open positions with Bitfinex

### ISSUE THREAD

**Issue by manisharora** [ccxt/ccxt#2615]
OS: ubuntu 16.01
Programming Language version: python 3.5
CCXT version: 1.12.180
Exchange: bitfinex
Method: 

Sometimes one need to know what current open positions are and react accordingly but i am unable to find one, we can find open positions by trade history but thats very complicated way

**Comment by kroitor** [comment]
Let us know if this does not help: https://github.com/ccxt/ccxt/issues/1207

**Comment by kroitor** [comment]
@RunningToTheEdgeOfTheWorld :

https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

```Python
print(bitfinex.private_post_positions())
```

**Comment by RunningToTheEdgeOfTheWorld** [comment]
soga, thank you.  I know you reflect string to the method before haha
