### ISSUE TITLE
async.kucoin: async def parse_orders_by_status() -> def parse_orders_by_status()

### ISSUE THREAD

**Issue by HynekBlaha** [ccxt/ccxt#2616]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: MacOs
- Programming Language version: Python 3.6
- CCXT version:1.12.154
- Exchange: Kucoin
- Method: async def parse_orders_by_status()

This function is being returned by fetch_closed_orders() and fetch_open_orders(). Because it is faulty set as async function, a Future is returned instead of wanted result.

**Comment by kroitor** [comment]
Fixed in 1.13.3. Thanks for your feedback! Really appreciated!

**Comment by kroitor** [comment]
@HynekBlaha are you sure that your version is up to date (Anaconda python can lie).

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/kucoin.py#L473
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/async/kucoin.py#L473

**Comment by kroitor** [comment]
```Python
import ccxt
print(ccxt.__version__)
```

```Python
import ccxt.async as ccxt
print(ccxt.__version__)
```

**Comment by HynekBlaha** [comment]
@kroitor You're right. My mistake, sorry for confusion.
