### ISSUE TITLE
bit-z AuthenticationError: Signature mismatch

### ISSUE THREAD

**Issue by kentwind23** [ccxt/ccxt#2617]
HI,I tried to create an order but got the 'AuthenticationError: Signature mismatch'
SYSTEM:MAC OS
CCXT VER.:1.13.1

the code is pretty simple:

bitz=ccxt.bitz({'apiKey':'******','secret':'*******','verbose': True})

order = bitz.create_order(symbol='EKT/BTC',type='limit',side='buy',amount=10,price='0.00000927')

Response: POST https://www.bit-z.com/api_v1/tradeAdd 200 {'Date': 'Wed, 18 Apr 2018 20:18:33 GMT', 'Content-Type': 'application/json;charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'Set-Cookie': 'LANG=en; expires=Thu, 19-Apr-2018 20:18:33 GMT; Max-Age=86400; path=/, __jsluid=fa55653f8944fabb76dc8b606e2df42c; max-age=31536000; path=/; HttpOnly', 'X-Via-JSL': '2b67061,-', 'X-Cache': 'bypass', 'Content-Encoding': 'gzip'} {"code":104,"msg":"Signature mismatch","data":null}
  File "/Users/MSS/PycharmProjects/cccc/venv/lib/python3.6/site-packages/ccxt/bitz.py", line 329, in create_order
    response = self.privatePostTradeAdd(self.extend(request, params))
  File "/Users/MSS/PycharmProjects/cccc/venv/lib/python3.6/site-packages/ccxt/bitz.py", line 398, in request
    raise ErrorClass(message)
ccxt.base.errors.AuthenticationError: Signature mismatch

I tried to use a new api key but didn't work,can anyone help:)

**Comment by kroitor** [comment]
@kentwind23 is this the entire code? 

Does this work for you with a new key:

```Python
import ccxt
bitz = ccxt.bitz({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
})
print(bitz.fetch_balance())
```

?

**Comment by kentwind23** [comment]
Hi kroitor,
thanks for your reply. I am able to fetch the balance but not able to place order.
when I tried to create order it always got the error "AuthenticationError: Signature mismatch".
my entire code is :  

import ccxt

bitz = ccxt.bitz({'apiKey':'6b1b*****b0845','secret':'f1CKaVd****olr3sf314','verbose': False,'enableRateLimit': True})

order = bitz.create_order(symbol='EKT/BTC',type='limit',side='buy',amount=10,price='0.00000927')

**Comment by kentwind23** [comment]
I found this info from the bit-z website but I am beginner I don't know how to use it lol

How to sign a request parameter
User-submitted parameters are required to sign in addition to sign.
First, the signature string is required to be sorted by parameter name (comparing the first letter of all parameter names, in abcd order. If the first letters are the same, then it depends on the second letter, and so on, for each of the parameters).
For example: for the following parameters for the signature:
api_key = 376892265asdad5d12726d8bbfbd8912b3 & id = 302221 & timestamp = 1510235730 & nonce = 309127
For example:
api_key = 376892265asdad5d12726d8bbfbd8912b3 & id = 302221 & timestamp = 1510235730 & nonce = 309127 Apply for stitching secret_key
The "sign" is the must transferred signature parameters.
Finally, the 32-bit md5 algorithm is used to sign the final signature string to get the signature result string (the string is assigned to the parameter sign).

**Comment by kroitor** [comment]
@kentwind23 have you tried with a float (non-string) price?

**Comment by kroitor** [comment]
Anyway, thanks for reporting, I will look into it and will get back to you on this issue.

**Comment by kentwind23** [comment]
just tried a float price,still the same error:(

**Comment by kroitor** [comment]
@kentwind23 yes, most likely a bug in the signing implementation, will fix it and will let you know asap.

**Comment by kentwind23** [comment]
@kroitor   Hi,kroitor,   the log:
Request: POST https://www.bit-z.com/api_v1/tradeAdd {'Content-type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} api_key=6b1b**************0845&coin=ekt_btc&nonce=100001&number=100.0&price=0.00100000&timestamp=1524155966&tradepwd=&type=in&sign=d9998d32a*********4c0bae38353


I found that the "tradepwd" is empty,  it that the problem?

**Comment by kentwind23** [comment]
@kroitor  the problem solved! I didn't know that I need to add the "password" in: bitz = ccxt.bitz({'apiKey':'6b1b*****b0845','secret':'f1CKaVd****olr3sf314','verbose': False,'enableRateLimit': True})    Thank you for your time!

**Comment by kroitor** [comment]
@kentwind23 thx for reporting back!
