### ISSUE TITLE
fetchL2OrderBook a lot slower than before?

### ISSUE THREAD

**Issue by Codewyvern** [ccxt/ccxt#2618]
- OS: Win 7
- Programming Language version: JS
- CCXT version: Latest
- Exchange: Cryptopia, Yobit, Bitfinex
- Method: fetchL2OrderBook

Has anyone noticed that fetchL2OrderBook is a lot slower recentlly? I am having such a headache understanding why, I used to scan each market's order book in an exchange in like 15 minutes and now it takes hours. I am not sure if something changed in the ccxt library or its some other problem, did something change with that function?

**Comment by kroitor** [comment]
I kinda draw these lines:
- crypto more popular → more exchange users → more load on the exchange → slower responses
- more people on earth → more exchange users → ...
- today there's more tokens than ever before → more time to loop through all of them
- ...

So, to me, it's all like *natural*. At least, we haven't changed the `fetchL2OrderBook` recently, and it depends on which time window you mean under *"before"*.

**Comment by Codewyvern** [comment]
Today its working normal again, no idea why, thanks.
