### ISSUE TITLE
Gdax Sandbox Authentication Error

### ISSUE THREAD

**Issue by jebesen** [ccxt/ccxt#2619]
Hi, 
I'm trying to use the api with the Gdax Sandbox, but I get an "Invalid API Key" error.

To use the sandbox I have changed this line in the code (line 478 in gdax.py):

From: 
`url = self.urls['api'] + request `
to:
`url = self.urls['test'] + request `

It's weird because I get the error using the sandbox credentials, but if I put the real credentials I get no error. It is like if my change int he code has no effect at all.

Probably it is just a newbie mistake from me, but I'm stucked with this. 

I'm using python on Ubuntu.

**Comment by kroitor** [comment]
> Probably it is just a newbie mistake from me, but I'm stucked with this.

1. For using your live credentials with the live exchange, you don't need to do anything.
2. For using your sandbox credentials with the exchange sandbox, do the following:

```
gdax = ccxt.gdax({
    'apiKey': 'YOUR_SANDBOX_KEY',
    'secret': 'YOUR_SANDBOX_SECRET',
})
gdax.urls['api'] = gdax.urls['test']

# your code goes
```

GDAX uses different accounting databases for sandbox accounts vs regular accounts, therefore you can't use a sandbox account with a live exchange and vice versa.

Let us know if this does not answer your question. Thx!

**Comment by jebesen** [comment]
Thank you very much.  Problem solved!

**Comment by kroitor** [comment]
@jebesen thx for reporting back! )
