### ISSUE TITLE
Fees currency

### ISSUE THREAD

**Issue by a-fas** [ccxt/ccxt#2622]
Hi ! A small question. Some exchanges take fees in quote coin both for sell and buy (e.g. hitbtc). Others (e.g. binance) take fees in "to" currency, so selling would take in quote and buying in base.
Is there any info about it is exchange master data or "fetchMarkets" info ? I didn't find this in docs and output jsons. This could be quite useful.

- OS: *
- Programming Language version: nodejs-8
- CCXT version: 1.10
- Exchange: e.g. hitbtc2, binance
- Method: ~fetchMarkets

**Comment by kroitor** [comment]
> Is there any info about it is exchange master data or "fetchMarkets" info ? I didn't find this in docs and output jsons. 

Currently, this information is not present in markets and is hardcoded into logic, but we are going to export that info from markets. As you know, this library is a work in progress.

In the meantime you can use the `.calculateFee` function (only works where fee info is available from the exchange):

```JS
calculateFee (symbol, type, side, amount, price, takerOrMaker = 'taker', params = {})
```

- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L994
- https://github.com/ccxt/ccxt/blob/master/js/poloniex.js#L131
- ...

> This could be quite useful.

We hope to add this info as soon as possible.

Let us know if this does not answer your question. Thx!

**Comment by benediamond** [comment]
Hi @kroitor, any progress on the availability of this attribute within `exchange.has` or in `markets` etc.?

Rather than `calculateFee`, etc., I really just need a single exchange-level boolean attribute, indicating whether purchase fees are extracted from quote or base. Thanks.

**Comment by kroitor** [comment]
Hi, @benediamond !

> any progress on the availability of this attribute within exchange.has or in markets etc.?

Not yet, but there's been a good proposal here: https://github.com/ccxt/ccxt/issues/3261#issuecomment-401604350

One remaining thing to decide on it is whether we want to store that property as exchange instance property (exchange-wide) or within markets (specific for each particular market). I think we should store that in markets. And we will start implementing it everywhere, the technical work isn't that hard and can be done in background.

**Comment by benediamond** [comment]
ok, yes, within markets is fine. but how will you extract that information from the exchanges? or will you hard-code it?

Looking forward to this being done, and happy to help.

**Comment by kroitor** [comment]
> but how will you extract that information from the exchanges?

If that info is provided by the API – we will take it from the API, or...

> or will you hard-code it?

... we might hardcode them partially, where necessary. Because exchanges don't change their fee schema too often (they can change the fee percentages, but they rarely change the side of their fees) and also because APIs of most of exchanges don't provide that information anyway – we're ok to hardcode this particular aspect (the fee application/deduction side).

**Comment by benediamond** [comment]
excellent. very interested in this feature---keep me updated.
