### ISSUE TITLE
Calculate Maximum Amount for Buy Limit Order

### ISSUE THREAD

**Issue by morzyns** [ccxt/ccxt#2623]
What's the best way to calculate maximum amount within available balance to have it unified over exchanges?

**Comment by mkutny** [comment]
The maximum amount is `balance / price`. But it's kinda trivial so I suppose you faced a problem which doesn't get solved with this formula.

**Comment by kroitor** [comment]
@morzyns you need:
- current balance
- current prices
- fee rates

All that combined makes up a formula:
order quote cost = base amount * quote price
base balance needed: amount + amount * feeRate
quote balance needed: cost + cost * feeRate

Hope this answers your question. Let us know if not. Thx!

**Comment by morzyns** [comment]
Cool, thanks.

**Comment by adamrg73** [comment]
> @morzyns you need:
> 
> * current balance
> * current prices
> * fee rates
> 
> All that combined makes up these formulas:
> 
> * order quote cost = base amount * quote price
> * base balance needed = amount + amount * feeRate
> * quote balance needed = cost + cost * feeRate
> 
> Hope this answers your question. Let us know if not. Thx!

this formula is not written correctly, please revise for me I need this.
please us definitive variables so I can understand the formula.
