### ISSUE TITLE
Proxy doesn't work.

### ISSUE THREAD

**Issue by dodgervl** [ccxt/ccxt#2624]
_Hello!_ 
First of all thank you for this wonderful tool! 

- OS: Ubuntu 17
- Programming Language version: Python 3.6
- CCXT version: 1.12.174
- Exchange: doesn't matter.
- Method: It's about proxy. For testing i used fetchMarkets()

**Code:**

```
HTTP_PROXY="http://10.10.1.10:3128"
HTTPS_PROXY="http://10.10.1.10:1080"
os.environ['HTTP_PROXY'] = HTTP_PROXY
os.environ['HTTPS_PROXY'] = HTTPS_PROXY

ccxt.bitmex.fetchMarkets()
```
**Error:**

bitmex GET https://www.bitmex.com/api/v1/instrument/activeAndIndices HTTPSConnectionPool(host='www.bitmex.com', port=443): Max retries exceeded with url: /api/v1/instrument/activeAndIndices (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8fc6433160>, 'Connection to 10.10.1.10 timed out. (connect timeout=10)'))

_Thank you for response!_

**Comment by kroitor** [comment]
Hi!

I've added two examples here:

- https://github.com/ccxt/ccxt/blob/master/examples/py/proxy-sync-python-requests-2-and-3.py
- https://github.com/ccxt/ccxt/blob/master/examples/py/proxy-asyncio-aiohttp-python-3.py

---

## Python 2 and 3 sync

```Python
# -*- coding: utf-8 -*-

import os
import sys

from pprint import pprint

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402

exchange = ccxt.poloniex({
    #
    # ↓ The "proxy" property setting below is for CORS-proxying only!
    # Do not use it if you don't know what a CORS proxy is.
    # https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin
    # You should only use the "proxy" setting if you're having a problem with Access-Control-Allow-Origin
    # In Python you rarely need to use it, if ever at all.
    #
    # 'proxy': 'https://cors-anywhere.herokuapp.com/',
    #
    # ↓ On the other hand, the "proxies" setting is for HTTP(S)-proxying (SOCKS, etc...)
    # It is a standard method of sending your requests through your proxies
    # This gets passed to the `python-requests` implementation directly
    # You can also enable this with environment variables, as described here:
    # http://docs.python-requests.org/en/master/user/advanced/#proxies
    # This is the setting you should be using with synchronous version of ccxt in Python 2 and 3
    #
    'proxies': {
        'http': 'http://10.10.1.10:3128',
        'https': 'http://10.10.1.10:1080',
    },
})

# your code goes here...

pprint(exchange.fetch_ticker('ETH/BTC'))
```

----

## Python 3.5+ asyncio

```Python
# -*- coding: utf-8 -*-

import asyncio
import os
import sys

from pprint import pprint

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt.async as ccxt  # noqa: E402


async def test_gdax():

    exchange = ccxt.poloniex({
        #
        # ↓ The "proxy" property setting below is for CORS-proxying only!
        # Do not use it if you don't know what a CORS proxy is.
        # https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin
        # You should only use the "proxy" setting if you're having a problem with Access-Control-Allow-Origin
        # In Python you rarely need to use it, if ever at all.
        #
        # 'proxy': 'https://cors-anywhere.herokuapp.com/',
        #
        # ↓ The "aiohttp_proxy" setting is for HTTP(S)-proxying (SOCKS, etc...)
        # It is a standard method of sending your requests through your proxies
        # This gets passed to the `asyncio` and `aiohttp` implementation directly
        # You can use this setting as documented here:
        # https://docs.aiohttp.org/en/stable/client_advanced.html#proxy-support
        # This is the setting you should be using with async version of ccxt in Python 3.5+
        #
        'aiohttp_proxy': 'http://proxy.com',
        # 'aiohttp_proxy': 'http://user:pass@some.proxy.com',
        # 'aiohttp_proxy': 'http://10.10.1.10:3128',
    })

    # your code goes here...

    ticker = await exchange.fetch_ticker('ETH/BTC')

    # don't forget to free the used resources, when you don't need them anymore
    await exchange.close()

    return ticker

if __name__ == '__main__':
    pprint(asyncio.get_event_loop().run_until_complete(test_gdax()))
```

Let us know if the above does not help. Thx!

**Comment by kroitor** [comment]
P.S. If you're wondering why the env didn't work – those environment variables should be set before importing ccxt (as it imports python-requests inside), as system-wide settings, or you should just use the `proxies` setting.

**Comment by dodgervl** [comment]
Thank you for fast response. I assume you run this code on your machine and everything works fine?

If so i guess there are deeper issues from my side (maybe proxy servers blocked in my country, it's common problem nowadays).

Thanks again and sorry for bothering you.

**Comment by dodgervl** [comment]
I have tried this code and it's worked.

```
import requests

proxies = {"http": "http://10.10.1.10:3128",
           "https": "http://10.10.1.10:1080"}

a=requests.get("https://poloniex.com/public?command=returnTicker")
```

So guess there are no problem with proxy from my side

**Comment by dodgervl** [comment]
Thank you for fast response. I assume you run this code on your machine and everything works fine?

If so i guess there are deeper issues from my side (maybe proxy servers blocked in my country, it's common problem nowadays).

I have tried following code:

import requests

```
proxies = {"http": "http://10.10.1.10:3128",
           "https": "http://10.10.1.10:1080"}

a=requests.get("https://poloniex.com/public?command=returnTicker",proxies=proxies)
```
and program still working (like infinite cycle) guess my idea about proxy block is correct.

Thanks again and sorry for bothering you.

**Comment by kroitor** [comment]
@dodgervl what's the actual address of your proxy?

**Comment by dodgervl** [comment]
@kroitor 
Sorry i didn't  get your question. I am using proxy from your example:
proxies = {"http": "http://10.10.1.10:3128",
           "https": "http://10.10.1.10:1080"}

**Comment by kroitor** [comment]
@dodgervl do you understand how proxies work? You have to have it running somewhere on the internet and you have to know the address of your proxy. The addresses that I've posted are there for example, you can't put them into your program – it won't work (there's no proxy server on those addresses). Therefore I ask what's the address of your own proxy that you are putting into the code.

**Comment by dodgervl** [comment]
Ok got it. Thanks for help.
I was really unlucky, because from many proxies  i used they all didn't get job done. But now i have found working address.

Sorry for mess. 
If someone get same issues this address is working for now:
"http://92.222.79.39:8181"

**Comment by kroitor** [comment]
@dodgervl ok, no worries, thx for reporting back!
