### ISSUE TITLE
Python asyncio coinexchange/gateio fetch_order_book sort_by issue

### ISSUE THREAD

**Issue by alexsith** [ccxt/ccxt#2626]
Hello. After your yesterday updating sort_by function I have 2 issues:

1.     return await self._ccxtexchange.fetch_order_book(symbol)
  File "/Users/user/Documents/Bitcoin//ccxt/async/coinexchange.py", line 679, in fetch_order_book
    return self.parse_order_book(orderbook['result'], None, 'BuyOrders', 'SellOrders', 'Price', 'Quantity')
  File "/Users/user/Documents/Bitcoin//ccxt/base/exchange.py", line 1016, in parse_order_book
    'asks': self.sort_by(self.parse_bids_asks(orderbook[asks_key], price_key, amount_key) if (asks_key in orderbook) and isinstance(orderbook[asks_key], list) else [], 0),
  File "/Users/user/Documents/Bitcoin//ccxt/base/exchange.py", line 556, in sort_by
    return sorted(array, key=lambda k: k[key] if key in k and k[key] else "", reverse=descending)
TypeError: '<' not supported between instances of 'float' and 'str'

2 there is issue with gateio orderbook it looks like it sorted as a string. But when I change sort_by to previous version: return sorted(array, key=lambda k: k[key], reverse=descending)
it works correctly

**Comment by kroitor** [comment]
Hi!

> TypeError: '<' not supported between instances of 'float' and 'str'

Which symbol is it?

> 2 there is issue with gateio orderbook it looks like it sorted as a string. But when I change sort_by to previous version: return sorted(array, key=lambda k: k[key], reverse=descending) it works correctly

Can you please clarify this with a minimalistic snippet of code and verbose output, according to https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ? What exactly is incorrect (compared to the previous version) in the gateio orderbook ? Which symbol, which method, etc... You probably already know our procedure – we need a more formal report and we always ask for one. I would ask for verbose output for both of your issues. Thx!

**Comment by kroitor** [comment]
Also, what's your version of Python ?

**Comment by alexsith** [comment]
I am sorry that I didn't provide full info. Markets are volatile and I have ass on fire because of this :)
Well. I have  Python 3.6.4 (default, Jan  6 2018, 11:51:59) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin

coinexchange market is
Request: GET https://www.coinexchange.io/api/v1/getorderbook?market_id=574 {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://www.coinexchange.io/api/v1/getorderbook?market_id=574 200 <CIMultiDictProxy('Server': 'nginx', 'Date': 'Fri, 20 Apr 2018 02:56:20 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'x-frame-options': 'SAMEORIGIN', 'Cache-Control': 'no-cache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Iinfo': '10-167487490-167471534 SNNN RT(1524192969054 11264) q(0 0 0 -1) r(0 0) U2', 'X-CDN': 'Incapsula', 'Content-Encoding': 'gzip')> {"success":"1","request":"\/api\/v1\/public\/getorderbook","message":"","result":{"SellOrders":[{"Type":"sell","Price":"0.00229999","OrderTime":"2018-04-14 12:35:02","Quantity":"0.30400000"},{"Type":"sell","Price":"0.00230000","OrderTime":"2018-03-27 20:35:07","Quantity":"1.00000000"},{"Type":"sell","Price":"0.00231566","OrderTime":"2018-03-20 15:34:57","Quantity":"0.00000000"},{"Type":"sell","Price":"0.00249999","OrderTime":"2018-04-17 07:26:03","Quantity":"0.59914440"},{"Type":"sell","Price":"0.00250000","OrderTime":"2018-03-16 18:36:14","Quantity":"0.85262769"},{"Type":"sell","Price":"0.00250000","OrderTime":"2018-03-18 13:34:57","Quantity":"4.00000000"},{"Type":"sell","Price":"0.00259000","OrderTime":"2018-04-19 23:17:49","Quantity":"1.00000000"},{"Type":"sell","Price":"0.00270000","OrderTime":"2018-04-03 09:36:24","Quantity":"0.43350928"},{"Type":"sell","Price":"0.00279880","OrderTime":"2018-03-20 06:10:02","Quantity":"0.46698335"},{"Type":"sell","Price":"0.00279889","OrderTime":"2018-03-01 07:01:56","Quantity":"0.10000000"},{"Type":"sell","Price":"0.00279998","OrderTime":"2018-04-17 07:26:32","Quantity":"0.50000000"},{"Type":"sell","Price":"0.00279999","OrderTime":"2018-03-09 15:51:35","Quantity":"0.40000000"},{"Type":"sell","Price":"0.00280000","OrderTime":"2018-03-10 03:22:39","Quantity":"6.00508436"},{"Type":"sell","Price":"0.00291274","OrderTime":"2018-03-26 10:33:47","Quantity":"1.00000000"},{"Type":"sell","Price":"0.00291500","OrderTime":"2018-03-21 07:21:37","Quantity":"20.00000000"},{"Type":"sell","Price":"0.00317998","OrderTime":"2018-02-18 07:22:23","Quantity":"1.26134572"},{"Type":"sell","Price":"0.00322000","OrderTime":"2018-03-21 06:55:35","Quantity":"3.00000000"},{"Type":"sell","Price":"0.00326990","OrderTime":"2018-02-21 03:17:06","Quantity":"1.00000000"},{"Type":"sell","Price":"0.00327000","OrderTime":"2018-02-18 19:57:14","Quantity":"47.13572176"},{"Type":"sell","Price":"0.00335000","OrderTime":"2018-03-24 07:08:38","Quantity":"6.00000000"},{"Type":"sell","Price":"0.00335000","OrderTime":"2018-04-19 02:23:11","Quantity":"0.50000000"},{"Type":"sell","Price":"0.00340000","OrderTime":"2018-02-15 20:38:25","Quantity":"0.01610400"},{"Type":"sell","Price":"0.00355987","OrderTime":"2018-02-14 23:12:38","Quantity":"13.79880902"},{"Type":"sell","Price":"0.00360000","OrderTime":"2018-02-15 14:24:57","Quantity":"2.06734586"},{"Type":"sell","Price":"0.00360000","OrderTime":"2018-02-18 19:56:50","Quantity":"50.00000000"},{"Type":"sell","Price":"0.00360000","OrderTime":"2018-04-17 20:46:20","Quantity":"1.28728499"},{"Type":"sell","Price":"0.00360000","OrderTime":"2018-04-19 14:23:18","Quantity":"3.00000000"},{"Type":"sell","Price":"0.00365000","OrderTime":"2018-02-14 12:40:37","Quantity":"1.47098366"},{"Type":"sell","Price":"0.00366373","OrderTime":"2018-03-07 03:31:50","Quantity":"0.03470000"},{"Type":"sell","Price":"0.00368000","OrderTime":"2018-02-18 04:16:06","Quantity":"1.98219721"},{"Type":"sell","Price":"0.00369150","OrderTime":"2018-02-13 00:00:42","Quantity":"1.04361371"},{"Type":"sell","Price":"0.00378000","OrderTime":"2018-02-09 02:01:46","Quantity":"0.05000000"},{"Type":"sell","Price":"0.00378999","OrderTime":"2018-02-12 06:32:17","Quantity":"1.00000000"},{"Type":"sell","Price":"0.00384680","OrderTime":"2018-02-04 15:53:51","Quantity":"9.68000000"},{"Type":"sell","Price":"0.00388000","OrderTime":"2018-02-18 04:16:30","Quantity":"2.00000000"},{"Type":"sell","Price":"0.00390000","OrderTime":"2018-02-06 09:37:33","Quantity":"32.00000000"},{"Type":"sell","Price":"0.00390000","OrderTime":"2018-02-11 10:51:04","Quantity":"31.00000000"},{"Type":"sell","Price":"0.00398001","OrderTime":"2018-02-20 08:59:25","Quantity":"2.00000000"},{"Type":"sell","Price":"0.00399989","OrderTime":"2018-02-01 23:01:59","Quantity":"0.89119417"},{"Type":"sell","Price":"0.00399990","OrderTime":"2018-01-23 11:52:43","Quantity":"0.55194000"},{"Type":"sell","Price":"0.00399999","OrderTime":"2018-01-23 11:51:58","Quantity":"1.00000000"},{"Type":"sell","Price":"0.00400000","OrderTime":"2018-02-16 19:00:29","Quantity":"10.00000000"},{"Type":"sell","Price":"0.00400012","OrderTime":"2018-02-01 04:45:04","Quantity":"0.06290944"},{"Type":"sell","Price":"0.00400112","OrderTime":"2018-02-01 04:42:17","Quantity":"0.58000000"},{"Type":"sell","Price":"0.00402000","OrderTime":"2018-01-16 15:30:24","Quantity":"0.86211000"},{"Type":"sell","Price":"0.00405000","OrderTime":"2018-01-16 15:27:17","Quantity":"2.00000000"},{"Type":"sell","Price":"0.00410000","OrderTime":"2018-01-25 12:26:55","Quantity":"0.62201964"},{"Type":"sell","Price":"0.00410000","OrderTime":"2018-02-01 09:35:15","Quantity":"0.07000000"},{"Type":"sell","Price":"0.00415000","OrderTime":"2018-01-15 16:07:14","Quantity":"4.46809975"},{"Type":"sell","Price":"0.00415000","OrderTime":"2018-01-30 23:15:27","Quantity":"0.11764671"}],"BuyOrders":[{"Type":"buy","Price":"0.00229500","OrderTime":"2018-04-20 01:27:27","Quantity":"0.95000000"},{"Type":"buy","Price":"0.00223970","OrderTime":"2018-04-19 22:40:52","Quantity":"0.04700000"},{"Type":"buy","Price":"0.00223969","OrderTime":"2018-04-19 15:32:04","Quantity":"0.69510604"},{"Type":"buy","Price":"0.00205570","OrderTime":"2018-04-19 22:38:33","Quantity":"2.43226152"},{"Type":"buy","Price":"0.00205566","OrderTime":"2018-04-19 22:31:02","Quantity":"10.00000000"},{"Type":"buy","Price":"0.00205562","OrderTime":"2018-04-19 21:06:05","Quantity":"3.25909736"},{"Type":"buy","Price":"0.00205560","OrderTime":"2018-04-19 19:47:47","Quantity":"4.56291573"},{"Type":"buy","Price":"0.00205555","OrderTime":"2018-04-19 14:17:10","Quantity":"16.85926361"},{"Type":"buy","Price":"0.00205000","OrderTime":"2018-04-19 12:46:10","Quantity":"243.90243902"},{"Type":"buy","Price":"0.00200015","OrderTime":"2018-04-19 11:46:36","Quantity":"0.12499284"},{"Type":"buy","Price":"0.00197000","OrderTime":"2018-04-19 05:07:51","Quantity":"24.52557653"},{"Type":"buy","Price":"0.00192525","OrderTime":"2018-04-19 06:30:04","Quantity":"15.00000000"},{"Type":"buy","Price":"0.00192502","OrderTime":"2018-04-17 23:29:44","Quantity":"15.58429641"},{"Type":"buy","Price":"0.00192502","OrderTime":"2018-04-18 10:30:07","Quantity":"7.00000000"},{"Type":"buy","Price":"0.00186501","OrderTime":"2018-04-16 14:42:00","Quantity":"10.01000000"},{"Type":"buy","Price":"0.00184010","OrderTime":"2018-04-12 20:49:28","Quantity":"0.55145677"},{"Type":"buy","Price":"0.00165999","OrderTime":"2018-04-09 15:41:57","Quantity":"0.10653939"},{"Type":"buy","Price":"0.00160210","OrderTime":"2018-04-17 00:55:18","Quantity":"249.67766416"},{"Type":"buy","Price":"0.00160203","OrderTime":"2018-04-16 14:42:31","Quantity":"10.00000000"},{"Type":"buy","Price":"0.00160202","OrderTime":"2018-04-14 14:33:35","Quantity":"15.15606846"},{"Type":"buy","Price":"0.00160200","OrderTime":"2018-03-20 00:53:09","Quantity":"42.46081983"},{"Type":"buy","Price":"0.00160147","OrderTime":"2018-03-19 15:31:55","Quantity":"20.00000000"},{"Type":"buy","Price":"0.00158014","OrderTime":"2018-03-31 16:40:42","Quantity":"1.00000000"},{"Type":"buy","Price":"0.00158013","OrderTime":"2018-03-16 16:13:49","Quantity":"0.63285932"},{"Type":"buy","Price":"0.00158000","OrderTime":"2018-03-16 16:11:12","Quantity":"0.63291139"},{"Type":"buy","Price":"0.00154012","OrderTime":"2018-04-16 01:59:19","Quantity":"7.54373454"},{"Type":"buy","Price":"0.00150001","OrderTime":"2018-04-01 15:44:22","Quantity":"1.67571813"},{"Type":"buy","Price":"0.00150000","OrderTime":"2018-03-18 14:23:39","Quantity":"0.50000000"},{"Type":"buy","Price":"0.00120009","OrderTime":"2018-04-08 20:31:24","Quantity":"20.00000000"},{"Type":"buy","Price":"0.00120000","OrderTime":"2018-04-01 19:54:16","Quantity":"420.00000000"},{"Type":"buy","Price":"0.00111112","OrderTime":"2018-03-20 16:48:18","Quantity":"1.03872325"},{"Type":"buy","Price":"0.00100000","OrderTime":"2018-02-22 18:59:52","Quantity":"1.00000000"},{"Type":"buy","Price":"0.00080011","OrderTime":"2018-03-15 16:34:45","Quantity":"1.00000000"},{"Type":"buy","Price":"0.00080000","OrderTime":"2018-01-31 11:42:43","Quantity":"3.15000000"},{"Type":"buy","Price":"0.00073980","OrderTime":"2017-12-14 18:54:46","Quantity":"0.13881552"},{"Type":"buy","Price":"0.00069745","OrderTime":"2017-12-13 02:19:50","Quantity":"1.20902323"},{"Type":"buy","Price":"0.00052700","OrderTime":"2018-01-16 07:35:40","Quantity":"0.99850319"},{"Type":"buy","Price":"0.00052700","OrderTime":"2018-02-22 18:31:18","Quantity":"7.91350091"},{"Type":"buy","Price":"0.00050000","OrderTime":"2018-01-02 11:55:03","Quantity":"1.00000000"},{"Type":"buy","Price":"0.00050000","OrderTime":"2018-01-10 01:58:52","Quantity":"10.69314000"},{"Type":"buy","Price":"0.00036000","OrderTime":"2018-01-24 23:53:00","Quantity":"14.00000000"},{"Type":"buy","Price":"0.00018000","OrderTime":"2018-02-23 19:37:15","Quantity":"50.00000000"},{"Type":"buy","Price":"0.00017000","OrderTime":"2018-01-24 23:53:13","Quantity":"24.00000000"},{"Type":"buy","Price":"0.00016110","OrderTime":"2017-10-31 20:27:24","Quantity":"0.62079454"},{"Type":"buy","Price":"0.00010002","OrderTime":"2018-01-27 07:09:43","Quantity":"50.00000000"},{"Type":"buy","Price":"0.00010001","OrderTime":"2018-01-22 16:55:48","Quantity":"100.00000000"},{"Type":"buy","Price":"0.00010000","OrderTime":"2018-01-19 01:52:56","Quantity":"1.00000000"},{"Type":"buy","Price":"0.00004000","OrderTime":"2018-01-24 23:53:52","Quantity":"84.00000000"},{"Type":"buy","Price":"0.00002874","OrderTime":"2018-04-19 22:29:50","Quantity":"100.00000000"},{"Type":"buy","Price":"0.00002873","OrderTime":"2018-03-16 08:41:41","Quantity":"50.00000000"}]}}

**Comment by alexsith** [comment]
About incorrect sort direction on gateio. I also found the same problem in btctradeim   ETC / BTC,
coinegg   ETH / BTC,  bitz   TRX / BTC. 

my code is using data from ccxt without changing it:

 i = cnt -1
        while i >= 0:
            bid = self.pair.depth['asks'][i]
            price = bid[0]
            vol = bid[1]
            sum += vol*price
            i -= 1

**Comment by alexsith** [comment]
<img width="637" alt="screen shot 2018-04-20 at 10 15 45" src="https://user-images.githubusercontent.com/34489099/39029002-de34f37e-4483-11e8-96c8-c0492f3e6f9e.png">
Here is okex XMR\BTC

**Comment by kroitor** [comment]
@alexsith 

Let's do this one by one. Coinexchange first.

1. You've shown the output of the exchange response now, but I don't see a problem with fetch_order_book there. It will convert those strings normally... The parse_order_book implementation does not throw any errors with that output:

↓ Does this work normally for you?

```Python
import ccxt
import json
from pprint import pprint
coinexchange = ccxt.coinexchange()
response = {
    "success":"1",
    "request":"/api/v1/public/getorderbook",
    "message":"",
    "result":{
        "SellOrders":[
            {"Type":"sell","Price":"0.00229999","OrderTime":"2018-04-14 12:35:02","Quantity":"0.30400000"},
            {"Type":"sell","Price":"0.00230000","OrderTime":"2018-03-27 20:35:07","Quantity":"1.00000000"},
            {"Type":"sell","Price":"0.00231566","OrderTime":"2018-03-20 15:34:57","Quantity":"0.00000000"},
            {"Type":"sell","Price":"0.00249999","OrderTime":"2018-04-17 07:26:03","Quantity":"0.59914440"},
            {"Type":"sell","Price":"0.00250000","OrderTime":"2018-03-16 18:36:14","Quantity":"0.85262769"},
            {"Type":"sell","Price":"0.00250000","OrderTime":"2018-03-18 13:34:57","Quantity":"4.00000000"},
            {"Type":"sell","Price":"0.00259000","OrderTime":"2018-04-19 23:17:49","Quantity":"1.00000000"},
            {"Type":"sell","Price":"0.00270000","OrderTime":"2018-04-03 09:36:24","Quantity":"0.43350928"},
            {"Type":"sell","Price":"0.00279880","OrderTime":"2018-03-20 06:10:02","Quantity":"0.46698335"},
            {"Type":"sell","Price":"0.00279889","OrderTime":"2018-03-01 07:01:56","Quantity":"0.10000000"},
            {"Type":"sell","Price":"0.00279998","OrderTime":"2018-04-17 07:26:32","Quantity":"0.50000000"},
            {"Type":"sell","Price":"0.00279999","OrderTime":"2018-03-09 15:51:35","Quantity":"0.40000000"},
            {"Type":"sell","Price":"0.00280000","OrderTime":"2018-03-10 03:22:39","Quantity":"6.00508436"},
            {"Type":"sell","Price":"0.00291274","OrderTime":"2018-03-26 10:33:47","Quantity":"1.00000000"},
            {"Type":"sell","Price":"0.00291500","OrderTime":"2018-03-21 07:21:37","Quantity":"20.00000000"},
            {"Type":"sell","Price":"0.00317998","OrderTime":"2018-02-18 07:22:23","Quantity":"1.26134572"},
            {"Type":"sell","Price":"0.00322000","OrderTime":"2018-03-21 06:55:35","Quantity":"3.00000000"},
            {"Type":"sell","Price":"0.00326990","OrderTime":"2018-02-21 03:17:06","Quantity":"1.00000000"},
            {"Type":"sell","Price":"0.00327000","OrderTime":"2018-02-18 19:57:14","Quantity":"47.13572176"},
            {"Type":"sell","Price":"0.00335000","OrderTime":"2018-03-24 07:08:38","Quantity":"6.00000000"},
            {"Type":"sell","Price":"0.00335000","OrderTime":"2018-04-19 02:23:11","Quantity":"0.50000000"},
            {"Type":"sell","Price":"0.00340000","OrderTime":"2018-02-15 20:38:25","Quantity":"0.01610400"},
            {"Type":"sell","Price":"0.00355987","OrderTime":"2018-02-14 23:12:38","Quantity":"13.79880902"},
            {"Type":"sell","Price":"0.00360000","OrderTime":"2018-02-15 14:24:57","Quantity":"2.06734586"},
            {"Type":"sell","Price":"0.00360000","OrderTime":"2018-02-18 19:56:50","Quantity":"50.00000000"},
            {"Type":"sell","Price":"0.00360000","OrderTime":"2018-04-17 20:46:20","Quantity":"1.28728499"},
            {"Type":"sell","Price":"0.00360000","OrderTime":"2018-04-19 14:23:18","Quantity":"3.00000000"},
            {"Type":"sell","Price":"0.00365000","OrderTime":"2018-02-14 12:40:37","Quantity":"1.47098366"},
            {"Type":"sell","Price":"0.00366373","OrderTime":"2018-03-07 03:31:50","Quantity":"0.03470000"},
            {"Type":"sell","Price":"0.00368000","OrderTime":"2018-02-18 04:16:06","Quantity":"1.98219721"},
            {"Type":"sell","Price":"0.00369150","OrderTime":"2018-02-13 00:00:42","Quantity":"1.04361371"},
            {"Type":"sell","Price":"0.00378000","OrderTime":"2018-02-09 02:01:46","Quantity":"0.05000000"},
            {"Type":"sell","Price":"0.00378999","OrderTime":"2018-02-12 06:32:17","Quantity":"1.00000000"},
            {"Type":"sell","Price":"0.00384680","OrderTime":"2018-02-04 15:53:51","Quantity":"9.68000000"},
            {"Type":"sell","Price":"0.00388000","OrderTime":"2018-02-18 04:16:30","Quantity":"2.00000000"},
            {"Type":"sell","Price":"0.00390000","OrderTime":"2018-02-06 09:37:33","Quantity":"32.00000000"},
            {"Type":"sell","Price":"0.00390000","OrderTime":"2018-02-11 10:51:04","Quantity":"31.00000000"},
            {"Type":"sell","Price":"0.00398001","OrderTime":"2018-02-20 08:59:25","Quantity":"2.00000000"},
            {"Type":"sell","Price":"0.00399989","OrderTime":"2018-02-01 23:01:59","Quantity":"0.89119417"},
            {"Type":"sell","Price":"0.00399990","OrderTime":"2018-01-23 11:52:43","Quantity":"0.55194000"},
            {"Type":"sell","Price":"0.00399999","OrderTime":"2018-01-23 11:51:58","Quantity":"1.00000000"},
            {"Type":"sell","Price":"0.00400000","OrderTime":"2018-02-16 19:00:29","Quantity":"10.00000000"},
            {"Type":"sell","Price":"0.00400012","OrderTime":"2018-02-01 04:45:04","Quantity":"0.06290944"},
            {"Type":"sell","Price":"0.00400112","OrderTime":"2018-02-01 04:42:17","Quantity":"0.58000000"},
            {"Type":"sell","Price":"0.00402000","OrderTime":"2018-01-16 15:30:24","Quantity":"0.86211000"},
            {"Type":"sell","Price":"0.00405000","OrderTime":"2018-01-16 15:27:17","Quantity":"2.00000000"},
            {"Type":"sell","Price":"0.00410000","OrderTime":"2018-01-25 12:26:55","Quantity":"0.62201964"},
            {"Type":"sell","Price":"0.00410000","OrderTime":"2018-02-01 09:35:15","Quantity":"0.07000000"},
            {"Type":"sell","Price":"0.00415000","OrderTime":"2018-01-15 16:07:14","Quantity":"4.46809975"},
            {"Type":"sell","Price":"0.00415000","OrderTime":"2018-01-30 23:15:27","Quantity":"0.11764671"}
        ],
        "BuyOrders":[
            {"Type":"buy","Price":"0.00229500","OrderTime":"2018-04-20 01:27:27","Quantity":"0.95000000"},
            {"Type":"buy","Price":"0.00223970","OrderTime":"2018-04-19 22:40:52","Quantity":"0.04700000"},
            {"Type":"buy","Price":"0.00223969","OrderTime":"2018-04-19 15:32:04","Quantity":"0.69510604"},
            {"Type":"buy","Price":"0.00205570","OrderTime":"2018-04-19 22:38:33","Quantity":"2.43226152"},
            {"Type":"buy","Price":"0.00205566","OrderTime":"2018-04-19 22:31:02","Quantity":"10.00000000"},
            {"Type":"buy","Price":"0.00205562","OrderTime":"2018-04-19 21:06:05","Quantity":"3.25909736"},
            {"Type":"buy","Price":"0.00205560","OrderTime":"2018-04-19 19:47:47","Quantity":"4.56291573"},
            {"Type":"buy","Price":"0.00205555","OrderTime":"2018-04-19 14:17:10","Quantity":"16.85926361"},
            {"Type":"buy","Price":"0.00205000","OrderTime":"2018-04-19 12:46:10","Quantity":"243.90243902"},
            {"Type":"buy","Price":"0.00200015","OrderTime":"2018-04-19 11:46:36","Quantity":"0.12499284"},
            {"Type":"buy","Price":"0.00197000","OrderTime":"2018-04-19 05:07:51","Quantity":"24.52557653"},
            {"Type":"buy","Price":"0.00192525","OrderTime":"2018-04-19 06:30:04","Quantity":"15.00000000"},
            {"Type":"buy","Price":"0.00192502","OrderTime":"2018-04-17 23:29:44","Quantity":"15.58429641"},
            {"Type":"buy","Price":"0.00192502","OrderTime":"2018-04-18 10:30:07","Quantity":"7.00000000"},
            {"Type":"buy","Price":"0.00186501","OrderTime":"2018-04-16 14:42:00","Quantity":"10.01000000"},
            {"Type":"buy","Price":"0.00184010","OrderTime":"2018-04-12 20:49:28","Quantity":"0.55145677"},
            {"Type":"buy","Price":"0.00165999","OrderTime":"2018-04-09 15:41:57","Quantity":"0.10653939"},
            {"Type":"buy","Price":"0.00160210","OrderTime":"2018-04-17 00:55:18","Quantity":"249.67766416"},
            {"Type":"buy","Price":"0.00160203","OrderTime":"2018-04-16 14:42:31","Quantity":"10.00000000"},
            {"Type":"buy","Price":"0.00160202","OrderTime":"2018-04-14 14:33:35","Quantity":"15.15606846"},
            {"Type":"buy","Price":"0.00160200","OrderTime":"2018-03-20 00:53:09","Quantity":"42.46081983"},
            {"Type":"buy","Price":"0.00160147","OrderTime":"2018-03-19 15:31:55","Quantity":"20.00000000"},
            {"Type":"buy","Price":"0.00158014","OrderTime":"2018-03-31 16:40:42","Quantity":"1.00000000"},
            {"Type":"buy","Price":"0.00158013","OrderTime":"2018-03-16 16:13:49","Quantity":"0.63285932"},
            {"Type":"buy","Price":"0.00158000","OrderTime":"2018-03-16 16:11:12","Quantity":"0.63291139"},
            {"Type":"buy","Price":"0.00154012","OrderTime":"2018-04-16 01:59:19","Quantity":"7.54373454"},
            {"Type":"buy","Price":"0.00150001","OrderTime":"2018-04-01 15:44:22","Quantity":"1.67571813"},
            {"Type":"buy","Price":"0.00150000","OrderTime":"2018-03-18 14:23:39","Quantity":"0.50000000"},
            {"Type":"buy","Price":"0.00120009","OrderTime":"2018-04-08 20:31:24","Quantity":"20.00000000"},
            {"Type":"buy","Price":"0.00120000","OrderTime":"2018-04-01 19:54:16","Quantity":"420.00000000"},
            {"Type":"buy","Price":"0.00111112","OrderTime":"2018-03-20 16:48:18","Quantity":"1.03872325"},
            {"Type":"buy","Price":"0.00100000","OrderTime":"2018-02-22 18:59:52","Quantity":"1.00000000"},
            {"Type":"buy","Price":"0.00080011","OrderTime":"2018-03-15 16:34:45","Quantity":"1.00000000"},
            {"Type":"buy","Price":"0.00080000","OrderTime":"2018-01-31 11:42:43","Quantity":"3.15000000"},
            {"Type":"buy","Price":"0.00073980","OrderTime":"2017-12-14 18:54:46","Quantity":"0.13881552"},
            {"Type":"buy","Price":"0.00069745","OrderTime":"2017-12-13 02:19:50","Quantity":"1.20902323"},
            {"Type":"buy","Price":"0.00052700","OrderTime":"2018-01-16 07:35:40","Quantity":"0.99850319"},
            {"Type":"buy","Price":"0.00052700","OrderTime":"2018-02-22 18:31:18","Quantity":"7.91350091"},
            {"Type":"buy","Price":"0.00050000","OrderTime":"2018-01-02 11:55:03","Quantity":"1.00000000"},
            {"Type":"buy","Price":"0.00050000","OrderTime":"2018-01-10 01:58:52","Quantity":"10.69314000"},
            {"Type":"buy","Price":"0.00036000","OrderTime":"2018-01-24 23:53:00","Quantity":"14.00000000"},
            {"Type":"buy","Price":"0.00018000","OrderTime":"2018-02-23 19:37:15","Quantity":"50.00000000"},
            {"Type":"buy","Price":"0.00017000","OrderTime":"2018-01-24 23:53:13","Quantity":"24.00000000"},
            {"Type":"buy","Price":"0.00016110","OrderTime":"2017-10-31 20:27:24","Quantity":"0.62079454"},
            {"Type":"buy","Price":"0.00010002","OrderTime":"2018-01-27 07:09:43","Quantity":"50.00000000"},
            {"Type":"buy","Price":"0.00010001","OrderTime":"2018-01-22 16:55:48","Quantity":"100.00000000"},
            {"Type":"buy","Price":"0.00010000","OrderTime":"2018-01-19 01:52:56","Quantity":"1.00000000"},
            {"Type":"buy","Price":"0.00004000","OrderTime":"2018-01-24 23:53:52","Quantity":"84.00000000"},
            {"Type":"buy","Price":"0.00002874","OrderTime":"2018-04-19 22:29:50","Quantity":"100.00000000"},
            {"Type":"buy","Price":"0.00002873","OrderTime":"2018-03-16 08:41:41","Quantity":"50.00000000"}
        ]
    }
}
pprint(coinexchange.parse_order_book(response['result'], None, 'BuyOrders', 'SellOrders', 'Price', 'Quantity'))
```

**Comment by kroitor** [comment]
Ok, now I see the error in Python3 async version

**Comment by alexsith** [comment]
File "/Users/user/Documents/Bitcoin/test/test.py", line 116, in <module>
    pprint(coinexchange.parse_order_book(response['result'], None, 'BuyOrders', 'SellOrders', 'Price', 'Quantity'))
  File "/Users/user/Documents/Bitcoin/ccxt/base/exchange.py", line 1016, in parse_order_book
    'asks': self.sort_by(self.parse_bids_asks(orderbook[asks_key], price_key, amount_key) if (asks_key in orderbook) and isinstance(orderbook[asks_key], list) else [], 0),
  File "/Users/user/Documents/Bitcoin/ccxt/base/exchange.py", line 556, in sort_by
    return sorted(array, key=lambda k: k[key] if key in k and k[key] else "", reverse=descending)
TypeError: '<' not supported between instances of 'float' and 'str'

Process finished with exit code 1

The same.  it throw exception with     
@staticmethod
    def sort_by(array, key, descending=False):
        return sorted(array, key=lambda k: k[key] if key in k and k[key] else "", reverse=descending)
   
but fine with
        return sorted(array, key=lambda k: k[key], reverse=descending)

**Comment by kroitor** [comment]
@alexsith yep... debugging it now, thx!
