### ISSUE TITLE
Trigger Order OKEX

### ISSUE THREAD

**Issue by wjbkuper** [ccxt/ccxt#2628]
I want to be able to make a stop-loss order. Because I cannot request the price continuously, I can't place an order when the price drops below a certain threshold, hence the need for the trigger order.  There seems to be no info about this option in the API documentation of the OKEX API. So how does one do it? Thanks in advance.

- OS: Win 8
- Programming Language version: Python
- CCXT version:
- Exchange: Okex
- Method: create_order()

**Comment by kroitor** [comment]
Hi! Sorry for a long wait. Basically, if the exchange in question does not provide a feature that you want, your only option is to implement it in userland with long-polling. Hope this answers your issue. Let us know if now. Thx!
