### ISSUE TITLE
Bittex fetchOrders not supported yet. 

### ISSUE THREAD

**Issue by morzyns** [ccxt/ccxt#2630]
Hi @kroitor,

With updated version i get this error: 
`Bittex fetchOrders not supported yet. `

Some versions ago it was working fine.
Any info?

- OS: 
- Programming Language version: JS
- CCXT version: 1.13.10
- Exchange: Bittrex
- Method: fetchOrders

**Comment by kroitor** [comment]
@morzyns it was emulated earlier, but it used a call to `fetchClosedOrders` or `fetchOpenOrders` internally, so you should use one of the two latter methods. Unfortunately, Bittrex does not have an endpoint to fetch them all in one go, so the earlier implementation for fetchOrders was not working properly and returned just the closed orders instead.

Let us know if this does not answer your question.
