### ISSUE TITLE
PrevDay & PrevDayPercent - Kucoin NaN bug

### ISSUE THREAD

**Issue by morzyns** [ccxt/ccxt#2631]
hi @kroitor,

PrevDay & PrevDayPercent is NaN. Is it possible to calculate it somehow? 

- OS: mac
- Programming Language version: JS
- CCXT version: 1.13
- Exchange: Kucoin
- Method: fetchTickers

**Comment by kroitor** [comment]
Fixed it in the most recent version of CCXT! Let us know if you have any difficulties with it. Thx!
