### ISSUE TITLE
Cobinhood 'is_active' variable does not exist.

### ISSUE THREAD

**Issue by hot-fine-cloth** [ccxt/ccxt#2633]
- OS: Amazon EC2 Instance
- Programming Language version: Python 2.7
- CCXT version: 1.13.11 
- Exchange: Cobinhood
- Method:   fetch_markets(self):

CCXT errors out on cobinhood as of yesterday morning.   The issue is the exchange is looking for the value of "is_active" .  Cobinhood's API mentions this is a variable but it does not exist in practice - 
Documention : https://cobinhood.github.io/api-public/#get-all-currencies
Data: https://api.cobinhood.com/v1/market/currencies

Thank you.

**Comment by limitmove** [comment]
Thank you!
