### ISSUE TITLE
Bit-Z : Incorrect sorting of OrderBook

### ISSUE THREAD

**Issue by wntsang4** [ccxt/ccxt#2634]
- OS: Windows 10
- Programming Language version: 3.6.4
- CCXT version: 1.13.11
- Exchange: Bit-Z
- Method: fetch_order_book

{'bids': [[3.984e-05, 1399.0277], [3.832e-05, 797.7417], [3.83e-05, 1000.0], [3.802e-05, 852.1757], [3.8e-05, 5263.1577], [3.764e-05, 544.155], [3.7e-05, 21621.6212], [3.65e-05, 5479.4519], [3.61e-05, 186.981], [3.6e-05, 13888.8886], [3.5e-05, 6700.001], [3.45e-05, 892.3765], [3.432e-05, 218.3307], [3.43e-05, 1608.338], [3.4e-05, 1000.0], [3.36e-05, 1784.5831], [3.358e-05, 200.0], [3.357e-05, 7281.3293], [3.356e-05, 140.1061], [3.351e-05, 8500.0], [3.33e-05, 512.9423], [3.325e-05, 186.503], [3.322e-05, 326.3014], [3.321e-05, 175.5637], [3.31e-05, 7498.4622], [3.25e-05, 4350.0], [3.242e-05, 611.0494], [3.237e-05, 122.2099], [3.223e-05, 244.4199], [3.196e-05, 366.6298], [3.145e-05, 399.8598], [3.136e-05, 99.8902], [3.124e-05, 499.9001], [3.117e-05, 299.9705], [3.101e-05, 537.8124], [3.1e-05, 5078.9061], [3.099e-05, 199.9307], [3.078e-05, 293.3035], [3.063e-05, 611.0496], [3.043e-05, 366.6296], [3.035e-05, 146.652], [3e-05, 30000.0], [2.998e-05, 219.9783], [2.988e-05, 1968.8757], [2.984e-05, 961.9765], [2.956e-05, 122.2099], [2.953e-05, 297.6738], [2.952e-05, 744.2951], [2.95e-05, 1983.2324], [2.949e-05, 244.4199], [2.946e-05, 637.5656], [2.94e-05, 1133.3732], [2.911e-05, 32.627], [2.909e-05, 842.1965], [2.901e-05, 1000.0], [2.886e-05, 496.1227], [2.881e-05, 16.0519], [2.88e-05, 731.8484], [2.864e-05, 1240.4923], [2.855e-05, 341.2769], [2.829e-05, 992.2451], [2.82e-05, 247.8757], [2.801e-05, 12000.0], [2.8e-05, 1244.3703], [2.764e-05, 244.4197], [2.751e-05, 800.0], [2.75e-05, 1011.3061], [2.723e-05, 199.9801], [2.7e-05, 100.0], [2.643e-05, 325.8925], [2.639e-05, 66.5938], [2.627e-05, 407.3665], [2.611e-05, 209.2554], [2.61e-05, 333.2665], [2.608e-05, 133.2871], [2.57e-05, 2000.0], [2.567e-05, 266.5736], [2.555e-05, 1075.4474], [2.539e-05, 833.1665], [2.518e-05, 195.536], [2.503e-05, 499.9502], [2.5e-05, 4158.0625], [2.48e-05, 166.484], [2.476e-05, 165.868], [2.452e-05, 414.7314], [2.439e-05, 333.2171], [2.414e-05, 666.4335], [2.39e-05, 248.8642], [2.372e-05, 293.3036], [2.369e-05, 331.7357], [2.361e-05, 366.6297], [2.351e-05, 146.6521], [2.343e-05, 73.3262], [2.338e-05, 302.8504], [2.271e-05, 297.6736], [2.259e-05, 148.7253], [2.226e-05, 446.6221], [2.198e-05, 744.2953], [2.182e-05, 595.3471], [2.055e-05, 366.6296]], 'asks': [[5.644e-05, 223.1105], [5.63e-05, 1500.8365], [5.628e-05, 1116.5548], [5.597e-05, 189.0255], [5.561e-05, 329.9996], [5.514e-05, 549.9994], [5.494e-05, 297.6736], [5.474e-05, 439.9997], [5.46e-05, 595.3468], [5.415e-05, 148.7256], [5.387e-05, 110.0003], [5.373e-05, 220.0002], [5.352e-05, 744.2952], [5.35e-05, 799.2], [5.311e-05, 446.6221], [5.287e-05, 669.9998], [5.22e-05, 146.6151], [5.219e-05, 893.1098], [5.218e-05, 1116.5546], [5.206e-05, 223.1105], [5.179e-05, 446.5555], [5.144e-05, 1500.0], [5.074e-05, 293.2303], [5.033e-05, 403.2525], [5.032e-05, 549.9997], [5.013e-05, 366.5931], [5.001e-05, 219.9781], [5e-05, 1962.7542], [4.998e-05, 861.1335], [4.978e-05, 9950.0], [4.943e-05, 220.0], [4.933e-05, 148.7255], [4.925e-05, 297.6738], [4.916e-05, 669.9998], [4.897e-05, 439.9999], [4.868e-05, 110.0002], [4.829e-05, 446.6221], [4.828e-05, 744.2954], [4.822e-05, 446.5552], [4.785e-05, 595.3471], [4.768e-05, 1116.5547], [4.752e-05, 893.11], [4.745e-05, 1537.0], [4.719e-05, 223.1106], [4.715e-05, 293.2302], [4.681e-05, 146.6151], [4.654e-05, 293.2305], [4.62e-05, 169.3976], [4.608e-05, 549.9995], [4.571e-05, 893.1097], [4.556e-05, 366.5932], [4.554e-05, 439.9996], [4.538e-05, 1116.5547], [4.526e-05, 223.1104], [4.52e-05, 223.1101], [4.517e-05, 893.1098], [4.5e-05, 15365.7112], [4.475e-05, 446.5552], [4.473e-05, 670.0001], [4.464e-05, 109.9999], [4.434e-05, 446.555], [4.402e-05, 893.1098], [4.399e-05, 446.5553], [4.379e-05, 1116.5547], [4.378e-05, 223.1105], [4.369e-05, 219.9999], [4.365e-05, 330.0001], [4.362e-05, 670.0001], [4.353e-05, 1116.5549], [4.342e-05, 670.0001], [4.332e-05, 1500.0], [4.318e-05, 329.9998], [4.3e-05, 799.9999], [4.277e-05, 439.8898], [4.271e-05, 110.0], [4.265e-05, 109.8898], [4.25e-05, 2188.497], [4.226e-05, 549.9996], [4.209e-05, 329.9997], [4.208e-05, 549.9448], [4.204e-05, 549.9445], [4.203e-05, 109.8901], [4.194e-05, 220.0], [4.17e-05, 219.9451], [4.168e-05, 329.9999], [4.163e-05, 542.0], [4.158e-05, 669.9999], [4.13e-05, 1398.6293], [4.115e-05, 558.0], [4.101e-05, 1116.5546], [4.1e-05, 49.97], [4.085e-05, 893.1098], [4.045e-05, 446.5553], [4.037e-05, 223.1106], [4.027e-05, 439.9998], [4.022e-05, 2778.4649], [4e-05, 6694.7624], [3.999e-05, 1357.8536], [3.995e-05, 803.1283], [3.991e-05, 795.1929]], 'timestamp': 1524279397000, 'datetime': '2018-04-21T02:56:37.000Z', 'nonce': None}

According to manual, The asks array is sorted by price in ascending order. The best (lowest) ask price is the first element and the worst (highest) ask price is the last element.

Code:
print(bitz.fetch_order_book('SPHTX/BTC'))

**Comment by wntsang4** [comment]
Problem solved after upgrading the lib. Thanks
I close the ticket.

**Comment by kroitor** [comment]
@wntsang4 thx for reporting back! It was fixed approx 24 hours ago:
- #2626 
- https://github.com/ccxt/ccxt/commit/2da8f6f7b37904407f2f12e8b5856a1e6cc66803
Let us know if you have any difficulties with it.
