### ISSUE TITLE
Kucoin is missing common APIs it claims to have

### ISSUE THREAD

**Issue by claudiocabral** [ccxt/ccxt#2635]
Hi,
`kucoin.has` includes the functions `fetchBalance` and `fetchOrderBook`, but when I try to call them in `nodejs`, they seem to be missing. I could help adding them if you'd like that!

- OS: Arch linux
- Programming Language version: nodejs v8.11.1
- CCXT version: 1.10.411
- Exchange: Kucoin
- Method: fetchBalance, fetchOrderBook, has

**Comment by kroitor** [comment]
> CCXT version: 1.10.411

Your version is too old, please update to the most recent one. Let us know if you still have further difficulties after that:

- https://github.com/ccxt/ccxt/blob/master/js/kucoin.js#L300 (fetchBalance)
- https://github.com/ccxt/ccxt/blob/master/js/kucoin.js#L326

**Comment by kroitor** [comment]
PS. Your contributions are welcome, but make sure to read this first, plz: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

Thank you!
