### ISSUE TITLE
poloniex BCC is translated to BCH, while BCH also exists

### ISSUE THREAD

**Issue by beniloew** [ccxt/ccxt#2639]
in Python, self.common_currency_code('BCC') == 'BCH', but BCH is also a currency by itself...

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/Manual#naming-consistency

> BCC → BCH: The Bitcoin Cash fork is often called with two different symbolic names: BCC and BCH. The name BCC is ambiguous for Bitcoin Cash, it is confused with BitConnect. The ccxt library will convert BCC to BCH where it is appropriate (some exchanges and aggregators confuse them).

See also:

- https://github.com/ccxt/ccxt/issues/83
- https://github.com/ccxt/ccxt/issues/129

Let us know if this does not answer your issue! Thx!

**Comment by beniloew** [comment]
i fixed it internaaly by adding 'BCC' : 'BCC' to commonCurrencies

**Comment by kroitor** [comment]
@beniloew ok, now I see it, uploaded a fix for CCXT as well, BCC → BTCtalkcoin, because BCC really stands for BitConnect https://coinmarketcap.com/currencies/bitconnect/ )
The fix will be available in 5-10 minutes in version 1.13.26. Thx for your participation!
