### ISSUE TITLE
BCH on HitBTC

### ISSUE THREAD

**Issue by ivigamberdiev** [ccxt/ccxt#2642]
Hello.
I try to deposit Bitcoin Cash (BCH) on HitBTC, but HitBTC have BitConnect (BCC) too. Because of this, Bitcoin Cash overwrite BitConnect and we don't have opportunity to work with Bitcoin Cash on HitBTC. Can you repair this? Thank you.

- OS: Ubuntu 16.04
- Programming Language version: Python 3.5.2
- CCXT version: 1.13.21
- Exchange: HitBTC
- Method: fetch_deposit_address()

**Comment by kroitor** [comment]
Fixed in 1.13.28. Thanks for reporting!
