### ISSUE TITLE
prompt working in file not working

### ISSUE THREAD

**Issue by joosthoeks** [ccxt/ccxt#2644]
- OS: Ubuntu 16.04.4 LTS
- Programming Language version: Python 3.5.2
- CCXT version: 1.13.32
- Exchange: All
- Method: ccxt.exchanges

I installed it like this:
pip install ccxt

import ccxt
print(ccxt.exchanges)

It's working in a prompt. But not in a Python file.

**Comment by joosthoeks** [comment]
My python --version
Python 2.7.12
My python3 --version
Python 3.5.2
My pip --version
pip 10.0.1 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)
My pip3 --version
pip 10.0.1 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)

If I install it with sudo pip install ccxt it makes no difference. I tried both Python versions.

**Comment by kroitor** [comment]
Ok, when you say it's not working in a file – what output do you see?

**Comment by joosthoeks** [comment]
Output:
Traceback (most recent call last):
  File "ccxt.py", line 1, in <module>
    import ccxt
  File "/home/joost/ccxt.py", line 2, in <module>
    print(ccxt.exchanges)
AttributeError: module 'ccxt' has no attribute 'exchanges'

**Comment by kroitor** [comment]
Did you try renaming ccxt.py to any other filename?

**Comment by joosthoeks** [comment]
Then is output:
Traceback (most recent call last):
  File "testccxt.py", line 1, in <module>
    import ccxt
ImportError: bad magic number in 'ccxt': b'\x03\xf3\r\n'

**Comment by joosthoeks** [comment]
I have removed ccxt.pyc and now it's working! Thanks!
