### ISSUE TITLE
error in function amount_to_lots on exmo

### ISSUE THREAD

**Issue by hamti2018** [ccxt/ccxt#2645]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: windows 7
- Programming Language version: nodejs v8.9.4
- CCXT version: 1.13.32
- Exchange: exmo
- Method: amount_to_lots
```

const ccxt = require('ccxt')
const exmo = new ccxt.exmo();

(async () => {
  await exmo.loadMarkets()
  console.log(exmo.amount_to_lots('ETH/USDT', 2)) // NaN
})()

```
Please add this function, when using multiple exchanges, this error severely hinders.

Thank you!

**Comment by kroitor** [comment]
The `amount_to_lots` function is deprecated, use amountToPrecision or decimalToPrecision instead.

More about it:

- #2121  
- https://github.com/ccxt/ccxt/pull/1635
- https://github.com/ccxt/ccxt/issues/522
- https://github.com/ccxt/ccxt/issues/1483
...

Let us know if this does not answer your question.
