### ISSUE TITLE
HADAX order submit error

### ISSUE THREAD

**Issue by feiyan-cs** [ccxt/ccxt#2646]
Getting this when placing a buy order on hadax

(node:84197) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: hadax {"status":"error","err-code":"base-update-error","err-msg":"data update error","data":null}

- OS: OSX
- Programming Language version: Latest node
- CCXT version: 1.13.32
- Exchange: HADAX
- Method: createLimitBuyOrder

**Comment by kroitor** [comment]
Hi! Sorry for the long wait. Can you please update to the most recent version of CCXT and then, if the issue persists, post a snippet to reproduce the issue (including the instantiation code) and your verbose request/response, as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

**Comment by liwei6797** [comment]
you need to use the url “/v1/hadax/order/orders”

**Comment by feiyan-cs** [comment]
Thank you!
