### ISSUE TITLE
BitMark (BTM) on poloniex + cryptopia

### ISSUE THREAD

**Issue by Esc4pism** [ccxt/ccxt#2648]
BTM (BitMark) Is renamed in commonCurrencies to 'Bitmark' in Poloniex.

MARKS in cryptopia is the same currency, please rename this to 'Bitmark' as well, (or name both MARKS, just use the same symbol for both)

**Comment by kroitor** [comment]
FIxed it in ccxt 1.13.35. Thank you for your involvement!
