### ISSUE TITLE
private_post_order_bulk problem on BITMEX

### ISSUE THREAD

**Issue by echo-ray** [ccxt/ccxt#2649]
@kroitor 
Thanks so much with the extraordinary work you have ever done !

CCXT is really helpful for cryptocurrency trading!

And I`m sorry to disturb you for this issue:

I got some problem when try to create [bulk orders](https://testnet.bitmex.com/api/explorer/#!/Order/Order_newBulk) ( multi orders in one post)
Here is the code:
```python
orders = [{"symbol":"XBTUSD","side":"Sell","orderQty": 10,"price": 9999},
          {"symbol":"XBTUSD","side":"Sell","orderQty": 10,"price": 9977}]
ccxt.bitmex.().private_post_order_bulk(body=f'orders={orders}')
```
I also tried ` body=json.dumps(orders) ` and ` body=urllib.parse.urlencode(orders) `, but it seems does fit the post data format correctly.

__Please help me T_T__

(when I using bitmex api explorer(on testnet), paste the content of the orders list (show in the codes above) to  directly, it works well)

- OS: os x & ubuntu10 & win10
- Programming Language version: Python 3.6.2
- CCXT version:  __version__ = '1.13.32'
- Exchange: Bitmex
- Method: private_post_order_bulk

**Comment by kroitor** [comment]
Hi!

Have you tried this:

```Python
import ccxt
from pprint import pprint

orders = [
    {"symbol":"XBTUSD","side":"Sell","orderQty": 10,"price": 9999},
    {"symbol":"XBTUSD","side":"Sell","orderQty": 10,"price": 9977},
]

bitmex = ccxt.bitmex({
    'apiKey': 'YOUR_API_KEY',  # replace for your credentials
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,  # enable built-in rate limiter
})

result = bitmex.private_post_order_bulk({'orders': orders})
pprint(result)
```

Let us know if this does not help. Thx!

**Comment by kroitor** [comment]
UPD: Minor edits to the above script.

**Comment by echo-ray** [comment]
Yeah!  It worked!
I have being troubled about rate limit & bulk order for several hours...
It really helped me quite a lot !
Thank you , kroitor !!!

**Comment by kroitor** [comment]
@echo-ray thanks for reporting back! Cheers!

**Comment by solocm** [comment]
when I run your code on testnet, got an "access denied." error response. @kroitor

**Comment by kroitor** [comment]
@solocm BitMEX testnet keys are not interchangeable with main keys, have you tried creating a new testnet key first?

**Comment by solocm** [comment]
I creat a new testnet key.  It works! so BitMEX main net key are not interchangeable with testnet, that's the reason. Thx, kroitor!

**Comment by ttodua** [comment]
for future readers: bitmex removed support for bulk endpoint several years ago
