### ISSUE TITLE
okcoinusd connection error

### ISSUE THREAD

**Issue by likso** [ccxt/ccxt#2650]
It did not work for more than 2 weeks, the site address could be moved.

`import ccxt
okcoinusd = ccxt.okcoinusd({'verbose': True})
okcoinusd_markets = okcoinusd.load_markets()`

ccxt.base.errors.RequestTimeout: okcoinusd GET https://www.okcoin.com/v2/markets/products.do HTTPSConnectionPool(host='www.okcoin.com', port=443): Read timed out. (read timeout=10)

- OS: windows 10
- Programming Language version: Python 3.6.5
- CCXT version: 1.12.133
- Exchange: okcoinusd
- Method: load_markets()

**Comment by kroitor** [comment]
We will remove it the next update of minor version number (1.14+). Thanks!

**Comment by Esc4pism** [comment]
Dont remove them yet, it seems they just rebranded from okcoin-ch, okcoin-us, ect. to "okcoin international 2.0" just a few days ago.
https://www.okcoin.com/
https://twitter.com/OKCoin/status/984703630996467712

their api documentation isnt fully updated and has some old or broken links, but atleast v1 is working:

https://support.okcoin.com/hc/en-us/articles/360000697832-REST-API-Reference

https://www.okcoin.com/api/v1/ticker.do?symbol=ltc_usd

**Comment by kroitor** [comment]
@Esc4pism thanks for the notice! Really appreciated!
