### ISSUE TITLE
Binance Historical Info Inaccurate

### ISSUE THREAD

**Issue by ITJusus** [ccxt/ccxt#2651]
- OS:  Windows 7 Pro
- Programming Language version:  VBA wrap
- CCXT version:  Source: https://github.com/krijnsent/crypto_vba
- Exchange: Binance
- Method: Historical EOHLC

When pulling historical prices (via EOHLC method) the prices are way off from the actual exchange requested. For example, when I utilize...

C_ARR_OHLCV("H", "RCN", "BTC", "EOHLC", "60", Now, "Binance")

And then I compare the outputted values to the actual charts on Binance or on TradingView (filtered as Binance)...the TradingView and official Binance site's chart values match perfectly to each other, but the values generated by CryptoCompare API are often not even in the same candle range. Sometimes I see the High price generated from CryptoCompare is below the entire candle itself (looking at Binance/TradingView)...like I said, way off.

Is all of this data being pulled from CryptoCompare perhaps just ignoring the request for "Binance" or perhaps is it returning the wrong exchanges data?

Please let me know if this is the correct place to submit this issue, as I'm hoping this is the official CryptoCompare API issue tracker.  I can provide more technical details as needed.

**Comment by kroitor** [comment]
Unfortunately, we can't really consult you on the repositories that we're not responsible for. I'd recommend to address this question to the author of crypto_vba here: https://github.com/krijnsent/crypto_vba/issues

CCXT does not have EOHLC / methods, it is part of CryptoVBA

Sorry for not being more helpful here.
