### ISSUE TITLE
php error

### ISSUE THREAD

**Issue by MaxieLj** [ccxt/ccxt#2652]
the code is 
$quoine   = new \ccxt\quoine   (); 

but should is 
$quoine   = new \ccxt\quoinex   ();

**Comment by MaxieLj** [comment]
in the demo code
`include 'ccxt.php';

$poloniex = new \ccxt\poloniex ();
$bittrex  = new \ccxt\bittrex  (array ('verbose' => true));
$quoine   = new \ccxt\quoine   ();
$zaif     = new \ccxt\zaif     (array (
    'apiKey' => 'YOUR_PUBLIC_API_KEY',
    'secret' => 'YOUR_SECRET_PRIVATE_KEY',
));

$poloniex_markets = $poloniex->load_markets ();

var_dump ($poloniex_markets);
var_dump ($bittrex->load_markets ());
var_dump ($quoine->load_markets ());

var_dump ($poloniex->fetch_order_book ($poloniex->symbols[0]));
var_dump ($bittrex->fetch_trades ('BTC/USD'));
var_dump ($quoine->fetch_ticker ('ETH/EUR'));
var_dump ($zaif->fetch_ticker ('BTC/JPY'));

var_dump ($zaif->fetch_balance ());

// sell 1 BTC/JPY for market price, you pay ¥ and receive ฿ immediately
var_dump ($zaif->id, $zaif->create_market_sell_order ('BTC/JPY', 1));

// buy BTC/JPY, you receive ฿1 for ¥285000 when the order closes
var_dump ($zaif->id, $zaif->create_limit_buy_order ('BTC/JPY', 1, 285000));

// set a custom user-defined id to your order
$hitbtc->create_order ('BTC/USD', 'limit', 'buy', 1, 3000, array ('clientOrderId' => '123'));`

**Comment by kroitor** [comment]
Fixed in 1.13.35. Thx for reporting!

**Comment by MaxieLj** [comment]
in the **install.md** at  **86** line
var_dump (\cxxt\Exchange::$exchanges);

should is 
var_dump (\ccxt\Exchange::$exchanges);
