### ISSUE TITLE
Problem with creating test order for binance with JavaScript

### ISSUE THREAD

**Issue by borghoffd** [ccxt/ccxt#2653]
Hey man,

i saw your code example to create a test order with python for binance.
I tried to recreate that code with Node.JS but get the following error message

> Binance: unknown error code: {"code":-1104,"msg":"Not all sent parameters were read; read '9' parameter(s) but was sent '10'."}
>     at binance.handleErrors (F:\Programmieren\Cryptobot\ccxt\node_modules\ccxt\js\binance.js:869:35)
>     at response.text.then.responseBody (F:\Programmieren\Cryptobot\ccxt\node_modules\ccxt\js\base\Exchange.js:508:18)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:160:7)

My code is the following:

`let order = exchange.createLimitSellOrder('ETH/BTC', 1.0, 0.060154, {'test': true});`

It's the same as in your manual for [Custom Order Params](https://github.com/ccxt/ccxt/wiki/Manual#custom-order-params). Is it possible to make a Test Order with JavaScript for Binance?

Greetings from Germany,
Dennis

**Comment by borghoffd** [comment]
Thanks for your reply, i hope i now provide you with all information you need.
My Node.js version is v9.3.0, and ccxt@1.11.117. Tested it on Windows 10 and 7. I used the exact code you wrote above.

The output is:
```
fetch:
 binance POST https://api.binance.com/api/v3/order
Request:
 { 'X-MBX-APIKEY': 'my_api_key',
  'Content-Type': 'application/x-www-form-urlencoded' }
 timestamp=1524560177782&recvWindow=5000&symbol=ETHBTC&quantity=1&type=LIMIT&side=SELL&price=0.060154&timeInForce=GTC&test=true&signature=1e72fc9fc943a6e0e872
9a593b982d54431bb1bf0f4572c84eb446093047678b

handleRestResponse:
 binance POST https://api.binance.com/api/v3/order 400 Bad Request
Response:
 { 'Content-Type': 'application/json',
  'Transfer-Encoding': 'chunked',
  Connection: 'close',
  Date: 'Tue, 24 Apr 2018 08:56:18 GMT',
  Server: 'nginx',
  'Strict-Transport-Security': 'max-age=31536000; includeSubdomains',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Xss-Protection': '1; mode=block',
  'X-Content-Type-Options': 'nosniff',
  'Content-Security-Policy': 'default-src \'self\'',
  'X-Content-Security-Policy': 'default-src \'self\'',
  'X-Webkit-Csp': 'default-src \'self\'',
  'Cache-Control': 'no-cache, no-store, must-revalidate',
  Pragma: 'no-cache',
  Expires: '0',
  'X-Cache': 'Error from cloudfront',
  Via: '1.1 c40ee2288a7db28fefd61c3f2ec7ccd7.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'fg9a0beII07smyotWmRb6DD28HfE3WpDp3I-3DLF5lXq5s62CUm5KA==' }
 {"code":-1104,"msg":"Not all sent parameters were read; read '9' parameter(s) but was sent '10'."}

(node:31032) UnhandledPromiseRejectionWarning: Error: binance: unknown error code: {"code":-1104,"msg":"Not all sent parameters were read; read '9' parameter(
s) but was sent '10'."}
    at binance.handleErrors (C:\...\node_modules\ccxt\js\binance.js:869:35)
    at response.text.then.responseBody (C:\...\node_modules\ccxt\js\base\Exchange.js:508:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:31032) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a cat
ch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31032) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate
the Node.js process with a non-zero exit code.
```

**Comment by kroitor** [comment]
@borghoffd please update to the most recent version of ccxt, the test order functionality support was added in 1.13+ two weeks ago, here: https://github.com/ccxt/ccxt/issues/2552

Let us know if this does not solve your issue. Thanks!
