### ISSUE TITLE
Question: Correctly handling exceptions - implementation

### ISSUE THREAD

**Issue by mkcity** [ccxt/ccxt#2663]
Hi, I posted this here https://github.com/ccxt/ccxt/issues/1956 because it was directly relevant, but the issue is closed so not sure if it will get seen/answered. 

It is really important to handle exceptions properly, so I need to make sure I get this right. I have scoured the internet but not found any fully implemented examples of how to handle exceptions in ccxt (in python) properly. Hopefully this will help others searching for the same. 

For example, on timeout exception when creating an order, we have to:

- update the .orders cache with a call to fetchOrders, fetchOpenOrders, fetchClosedOrders to check if the request to place the order has succeeded and the order is now open

- if the order is not 'open' the user should fetchBalance to check if the balance has changed since the order was created on the first run and then was filled and closed by the time of the second check
Thank you

Based on that, here is what I came up with, but not sure if it is correct:

```
tries = 0
done = False
while not done:
	try:
                time.sleep(1)
		balances = exchange.fetch_balance() #this should point to a function that has error handling of it's own
                time.sleep(1)
		exchange.create_limit_buy_order("BTC/USDT", buy_amount, limit_price)
		done = True
                tries++
                if tries > 5:
                        print("giving up after 5 tries")
                        quit()
	except (ccxt.ExchangeError, ccxt.AuthenticationError, ccxt.ExchangeNotAvailable, ccxt.RequestTimeout) as error:
		orders = exchange.fetch_orders(symbol="BTC/USDT") #refresh order cache
		open_orders = exchange.fetch_open_orders(symbol="BTC/USDT") #refresh order cache
		closed_orders = exchange.fetch_closed_orders(symbol="BTC/USDT") #refresh order cache
		my_order = [element for element in open_orders if element['amount'] == buy_amount] #not sure about this, trying to find the order I just tried to submit
		if len(my_order) == 0:
			new_balance = exchange.fetch_balance() #this should point to a function that has error handling of it's own
			if new_balance["BTC"]["total"] == balances["BTC"]["total"] and new_balance["USDT"]["available"] == balances["USDT"]["available"]:
				done = False #re attempt the order
```

Also, second question: for exceptions when canceling orders, we have to "set the order status to 'canceled' manually" if the balance hasn't changed. How do we set this (in python please)?

Thank you very much.

Update: edited code to stop trying after 5 tries, and a couple comments

**Comment by mkutny** [comment]
Well, `RequestTimeout` exceptions do happen occasionally. Still, I believe that if you make up your trading bot/strategy right then timeouts should not noticeably affect your trading.

So my suggestion would be to start from a simplier trading logic which is not fault-tolerant and see how it works. If it shows good results you may add extra layers of protection at exact places you really need them.

It's just a friendly advice in case you haven't yet came up with a profitable strategy but already thinking about how to implement "setting the order status to 'canceled' manually if balance hasn't changed".

It's really advanced topic. Basically, if your strategy is profitable you'll probably never need to think of it... but if it's not then it's probably due to another reason but not because you order was erroneously marked as 'closed' instead of 'canceled'.

Still, here are answers to your questions.

> update the .orders cache with a call to fetchOrders, fetchOpenOrders, fetchClosedOrders to check if the request to place the order has succeeded and the order is now open

Either of those should be enough, no need to call all the three in a row. Just `fetchOpenOrders` and `fetchBalance` in this sequence.

```
time.sleep(1) # This line you don't need. ccxt has it's internal rate limiter built in, you may rely on it.
```



```
tries++ # This line you probably want to move into exceptions block.
```


```
except (ccxt.ExchangeError, ccxt.AuthenticationError, ccxt.ExchangeNotAvailable, ccxt.RequestTimeout) as error: #You mix here recoverable and non-recoverable errors. For example, if you fail to authenticate you probably don't need to repeat.
```

**Comment by mkcity** [comment]
Thank you for the help. 

I have a good strategy that I would like to trade. I'm not worried so much about cancelling orders as much as I am submitting orders. Sometimes the strategy get's in and out of trades really fast (minutes). It works on a universe. 

For example, if you need to close a position - it's very important that that position get's closed, in case the price starts moving against you, and also so that you can free up the BTC so you can get into other trades. The worst thing potentially is if you're holding onto a coin when you shouldn't be (a sell order didn't go through). That is my primary concern. 

I know the exception handling is advanced but I'm trying to up my game, to have more peace of mind when my algo is running and to be able to build even more advanced algos. I want to become better. 

I saw issues of the rate limiter not always working so I thought it might be safer to do this manually? But I will implement this instead. 

Here is my updated code based on your feedback:

```
exchange = ccxt.poloniex ({ 'enableRateLimit':True })

tries = 0
done = False
while not done:
	try:
		balances = exchange.fetch_balance() #this should point to a function that has error handling of it's own
		exchange.create_limit_buy_order("BTC/USDT", buy_amount, limit_price)
		done = True
	except (ccxt.RequestTimeout) as error:
		tries++
		if tries > 5:
			print("giving up after 5 tries")
			quit()
		open_orders = exchange.fetch_open_orders(symbol="BTC/USDT")
		my_order = [element for element in open_orders if element['amount'] == buy_amount] #not sure about this, trying to find the order I just tried to submit
		if len(my_order) == 0:
			new_balance = exchange.fetch_balance() #this should point to a function that has error handling of it's own
			if new_balance["BTC"]["total"] == balances["BTC"]["total"] and new_balance["USDT"]["available"] == balances["USDT"]["available"]:
				done = False #re attempt the order
	except (ccxt.ExchangeError, ccxt.AuthenticationError, ccxt.ExchangeNotAvailable) as error:
		print("Error in create_limit_buy_order: ", error)
```

The part of the code I am most weary about is this part:

```
		my_order = [element for element in open_orders if element['amount'] == buy_amount] #not sure about this, trying to find the order I just tried to submit
		if len(my_order) == 0:
			new_balance = exchange.fetch_balance() #this should point to a function that has error handling of it's own
			if new_balance["BTC"]["total"] == balances["BTC"]["total"] and new_balance["USDT"]["available"] == balances["USDT"]["available"]:
				done = False #re attempt the order
```

Is that the best way to check if my order is pending, and if not if it already went through? 

Thank you very much.

**Comment by mkutny** [comment]
> I know the exception handling is advanced but I'm trying to up my game, to have more peace of mind when my algo is running and to be able to build even more advanced algos.

If you want to dig really deep in it keep in mind that calls in your exceptions block may fail too.


> I saw issues of the rate limiter not always working so I thought it might be safer to do this manually?

Manual implementation is really error-prone. For it to work you need to place delays after **every** call. In the code snippet of your first post, you completely missed delays in exceptions block.

If you have issues with built-in rate limiter I'd recommend to troubleshoot them - it might happen that those issues have roots in your code, not in ccxt.


> Is that the best way to check if my order is pending, and if not if it already went through?

Well, what I immediately see is that you don't set `done` to `True` in the exceptions block.

The rest depends on your setup, actually. In general, checking for just amount is not enough. I can imagine that one can keep both buy and sell orders of the same size. In this case, even if the creation of new order fails you'll get a false positive.

It also depends on whether you close your position with taker or maker order. If you want to place taker order but your order was partially filled then you'll have a false positive too.

Apart from this minor issues, I'd say it's ok... So, if you're comfortable with it I'd give it a try and see how it work in real life )

Still think, if you can infer your current position from your balance alone. Because if you can, I'd say you don't need this elaborate checks at all, just `fetchOpenOrders`, `fetchBalance` and proceed from there.

**Comment by mkcity** [comment]
I realize calls in exceptions could fail too. Not sure how to handle these... For now I will just have every exception give up after 5 tries, so it's possible that the algo could terminante in an exception while trying to handle another exception. I have to start somewhere. 

In the example above, I put the direct call to the exchange, for example to get the balance or get the open orders - I did this for simplicity sake. In practice, each of these calls would be to a function which would make the call and handle the errors. 

`Done` get's set to True in the try block, and only gets assigned as False if I want it to retry the order. 

Perhaps I need to add amount + direction when checking for the order. 

I think I am comfortable enough now to try in real life. 

I don't understand this, could you please elaborate or show me with an example? I would prerfer to keep things simpler where possible.

> Still think, if you can infer your current position from your balance alone. Because if you can, I'd say you don't need this elaborate checks at all, just fetchOpenOrders, fetchBalance and proceed from there.

Thanks again for all your help.

**Comment by mkutny** [comment]
> Done get's set to True in the try block, and only gets assigned as False if I want it to retry the order.

What will happen if in the exception block you realize that the order placement succeded?


> I don't understand this, could you please elaborate or show me with an example?

I don't really know how you calculate your position and how you close it. So this suggestion might just not apply to you.

But let's assume for a moment that you treat your position as open if you have some BTC on your account and closed when your BTC is zero. In such a case your code for closing position could be as simple as:

```python
while position > 0:
    try:
        exchange.cancel_all()
        exchange.create_market_sell_order("BTC/USDT", position, price)
    except:
        exchange.fetch_open_orders() # don't care about result, just to update cache
        balance = exchange.fetch_balance()
        position = balance['BTC']['total]
```

**Comment by mkcity** [comment]
> What will happen if in the exception block you realize that the order placement succeded?

You are right - this is a mistake. `done` will never get set to True if there is an exception. I didn't realize this. What if I move done=True to the top of the try block, so it's always True unless I specifically want to retry:

```
try:
    done = True
    balances = exchange.fetch_balance() #this should point to a function that has error handling of it's own
    exchange.create_limit_buy_order("BTC/USDT", buy_amount, limit_price)
```

Also thank you for the example.

**Comment by mkutny** [comment]
That should work. You might also like this approach (this is how similar functionality is implemented in ccxt:
https://github.com/ccxt/ccxt/blob/ab9998dd5ddbe48231648fd833e38d2b5a05f692/js/test/test.js#L300-L313

**Comment by mkcity** [comment]
Cool, thanks. 

One thing, in your example:

```
while position > 0:
    try:
        exchange.cancel_all()
        exchange.create_market_sell_order("BTC/USDT", position)
    except:
        exchange.fetch_open_orders() # don't care about result, just to update cache
        balance = exchange.fetch_balance()
        position = balance['BTC']['total]
```

I think when you calculate position (final line), you have to get the 'available' amount, not 'total', because if your order has been submitted but not yet filled, your total amount of BTC would be the same.

**Comment by mkcity** [comment]
Can you provide a simple but realistic example of a solution for cancelling open orders? Do we need to update the order cache and set order.status as cancelled if there was a timeout but the order was in fact cancelled? By not doing this, do we risk an adverse affect such as ccxt thinking that we have more/less of BTC (for example) than we actually do because it thinks an order got filled when in fact it got cancelled? I'm not too clear on that.

**Comment by mkcity** [comment]
The simpler the better, thank you very much for all your help I really appreciate it, this helps me tremendously.

**Comment by mkcity** [comment]
I just thought of something. What if you get a timeout and in the time it takes you to retry, the order gets filled. When you retry, you will get an `OrderNotFound` exception, is that correct? 

In this case, we should update the cache with `fetchOpenOrders `and `fetchBalance`, and use the updated balance to confirm the order went through or not.

**Comment by mkutny** [comment]
> In this case, we should update the cache with fetchOpenOrders and fetchBalance, and use the updated balance to confirm the order went through or not.

Exactly!

> What if you get a timeout and in the time it takes you to retry, the order gets filled. When you retry, you will get an OrderNotFound exception, is that correct?

Nope. What exact command do you expect will give you `OrderNotFound`?

**Comment by mkcity** [comment]
Great. This has been really helpful, thanks again.
