### ISSUE TITLE
Yobit fetchDepositAddress - [Exchange Error] yobit does not have currency code BTC?

### ISSUE THREAD

**Issue by rsparrow** [ccxt/ccxt#2664]
- OS: OSX
- Programming Language version: JS
- CCXT version: 1.13.42
- Exchange: yobit
- Method: fetchDepositAddress

What trying to get the deposit address I'm getting an error message with the following:

[Exchange Error] yobit does not have currency code BTC
    at yobit.currency (.../node_modules/ccxt/js/base/Exchange.js:710:15)
    at yobit.fetchDepositAddress (.../node_modules/ccxt/js/yobit.js:164:29)

After looking around a little bit sure enough there is no "BTC" listed when you call loadMarkets then check the exchange.currencies for yobit.

However they do support BTC and I have a deposit address created on the site via the web ui.

**Comment by kroitor** [comment]
@rsparrow can you please show a minimal snippet of your code to reproduce the issue?

**Comment by kroitor** [comment]
Fixed in 1.13.43. Thx!

**Comment by rsparrow** [comment]
Sorry I missed your request. Thank for the quick fix!

**Comment by rsparrow** [comment]
Hey BTW, `withdraw` function has the exact same issue, I'll open a new ticket here and link them.
