### ISSUE TITLE
Different symbols for Different Exchanges

### ISSUE THREAD

**Issue by guil20** [ccxt/ccxt#2665]
Hello
I have been trying to find a solution for different symbols exceptions.
I came across two examples:

YOYO on Binance
The symbol is YOYOW
and NANO
Symbol is XRB even symbol on URL and trading is NANO which is confusing...

Is there any possibility that ccxt correct the symbol for each different symbol before making a buy order ?

I appreciate if you take the time to look into this.
Cheers,

**Comment by kroitor** [comment]
Hi!

Please, read here: 
- https://github.com/ccxt/ccxt/wiki/Manual#naming-consistency
- https://github.com/ccxt/ccxt/issues/2561

Let us know if this does not answer your question. Thx!
