### ISSUE TITLE
Question about weak implementation of ccex

### ISSUE THREAD

**Issue by AnAndrey** [ccxt/ccxt#2668]
- OS: Windows 10
- Programming Language version: Python
- CCXT version: 1.13.44
- Exchange: ccex
- Method: fetch_open_orders, fetch_my_trades, load_markets

Hello! I found that fetch_open_orders and fetch_my_trades methods are not implemented in latest CCXT. But ccex provides required API for that. Also load_markets could be reimplemented over getmarkets, cause it provides more meta data about trading markets.
Any plans to correct this lack of functionality in the nearest future?

Links on mentioned methods:
https://c-cex.com/?id=api#getopenorders
https://c-cex.com/?id=api#mytrades
https://c-cex.com/?id=api#getmarkets

**Comment by kroitor** [comment]
@AnAndrey 

> I found that fetch_open_orders and fetch_my_trades methods are not implemented in latest CCXT.

Those methods are implemented for many exchanges, however, they may be missing with this or that exchange, as this library is a work in progress.

> Any plans to correct this lack of functionality in the nearest future?

Yes: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#pending-tasks

<img width="1505" alt="screen shot 2018-04-26 at 14 46 53" src="https://user-images.githubusercontent.com/1294454/39303952-ae265e5c-4960-11e8-86cc-51341dd92244.png">

More about it here: #71 

Your contributions are welcome, we are happy for all help, just make sure to read this very carefully first: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

Let us know if this does not answer your questions. Thx!

**Comment by kroitor** [comment]
@AnAndrey thx so much for your understanding! )
