### ISSUE TITLE
Need script for exchange like binance

### ISSUE THREAD

**Issue by deepak-india** [ccxt/ccxt#2671]
I want to create a exchange site like binance.com.
i need the script which be used for BUY sell and trading option like binance .
How can i get that script  for developing binance like site.

**Comment by kroitor** [comment]
See here:
- https://github.com/peatio/peatio
- https://github.com/viabtc/viabtc_exchange_server

Unfortunately, your question is way beyond the scope of this library, we can't really consult on this issue, sorry. Let us know if you have questions related to CCXT. Thx!
