### ISSUE TITLE
Kucoin fetchBalance invalid nounce

### ISSUE THREAD

**Issue by morzyns** [ccxt/ccxt#2672]
"kucoin {\"code\":\"UNAUTH\",\"msg\":\"Invalid nonce\",\"success\":false,\"timestamp\":1524741756735}"

- OS: Android / JS
- Programming Language version: JS
- CCXT version: 1.13.10
- Exchange: Kucoin
- Method: fetchBalance

**Comment by kroitor** [comment]
1. Are you using any rate-limiting?
2. Can you show your output in verbose mode?
3. Have you seen this: https://github.com/ccxt/ccxt/wiki/Manual#invalidnonce ?

**Comment by morzyns** [comment]
Verbose returns nothing for fetchBalance unfortunately, just i can just catch error - 
`"kucoin {"code":"UNAUTH","msg":"Invalid nonce","success":false,"timestamp":1524741756735}"`

```
  async fetchBalance(): Promise<any> {
        try {
            const balance = await this.exchange.fetch_balance();

            return balance;
        } catch (e) {
            this.handleErrors(e);
        }
    }
```
Interestingly it was working fine yesterday..

**Comment by kroitor** [comment]
That snippet of code does not tell me a lot... I need it to be a full copy-pastable and runnable-in-my-node program...

Does this work for you:

```JS
'use strict'
const ccxt = require ('ccxt')
;(async () => {
    const kucoin = new ccxt.kucoin ({
        apiKey: 'YOUR_API_KEY',
        secret: 'YOUR_SECRET',
        enableRateLimit: true, // enable rate limiting
    })
    console.log (await kucoin.fetchBalance ())
}) ()
```

?

**Comment by morzyns** [comment]
Hehe, i am on NativeScript/Angular 

initExchange() {
        try {
            this.exchange = this.configService.getActiveExchange();
            this.exchangeName = this.exchange.name;
            const key = this.exchange.key;
            const secret = this.exchange.secret;
            this.exchange = new ccxt[this.exchange.name]({ verbose: true });
            this.exchange.apiKey = key;
            this.exchange.secret = secret;
            this.exchange.userAgent = "Exchange Mobile App";

        } catch (e) {
            this.handleErrors(e);
        }
    }

**Comment by kroitor** [comment]
You don't seem to be
Try this:

```JS
initExchange() {
        const exchange = new ccxt[this.exchange.name]({ verbose: true, enableRateLimit: true })
        exchange.apiKey = key;
        exchange.secret = secret;
        exchange.userAgent = "Exchange Mobile App";
        const exchange = new ccxt[this.exchange.name]({ verbose: true, enableRateLimit: true })
        exchange.fetchBalance ()
            .then (balance => console.log (balance)
            .catch (e => console.log (e.message)
    }
```

Do you see any console.log output ? Can you post the code and output entirely (without your keys) ?

**Comment by kroitor** [comment]
UPD. sorry for the typos, changed the above snippet slightly.

**Comment by morzyns** [comment]
Cool.
Checking with new API credentials.

**Comment by kroitor** [comment]
> Checking with new API credentials.

You'd better follow what I tell you ) Changing the credentials most likely won't help here. You have a rate-limiting or a time-sync problem, obviously.

**Comment by morzyns** [comment]
interesting.. 
```
JS:  undefined
JS: handleRestResponse:
JS:  kucoin GET https://api.kucoin.com/v1/account/balance?limit=20&page=1 200 OK
JS: Response:
JS:  {
JS:   "Null": "HTTP/1.1 200",
JS:   "Access-Control-Allow-Credentials": "true",
JS:   "Access-Control-Allow-Headers": "Origin, X-Requested-With, Content-Type, Accept, Accept-Language",
JS:   "Access-Control-Allow-Methods": "POST, GET, PUT, OPTIONS, DELETE, PATCH",
JS:   "Access-Control-Allow-Origin": "https://www.kucoin.com",
JS:   "Access-Control-Max-Age": "86400",
JS:   "Connection": "keep-alive",
JS:   "Content-Type": "application/json;charset=UTF-8",
JS:   "Date": "Thu, 26 Apr 2018 12:15:56 GMT",
JS:   "Transfer-Encoding": "chunked",
JS:   "X-Android-Received-Millis": "1524744913393",
JS:   "X-Android-Response-Source": "NETWORK 200",
JS:   "X-Android-Selected-Protocol": "http/1.1",
JS:   "X-Android-Sent-Millis": "1524744913108"
JS: }
JS:  {"code":"UNAUTH","msg":"Invalid nonce","success":false,"timestamp":1524744956846}
JS: ERROR TypeError: Cannot read property 'total' of undefined
```

**Comment by kroitor** [comment]
@morzyns is your system clock up to date? Can you verify that your system clock is in sync with the rest of the world?

**Comment by kroitor** [comment]
Also, are you using this single instance of kucoin class, or do you have many of them running?

**Comment by morzyns** [comment]
Checked clock, it's automatically synced.. (and the same as google shows for my timezone)
I instantiate once. The funny thing is that works fine on iOS..  What a pain! ;>

**Comment by kroitor** [comment]
@morzyns thanks for reporting back! Cheers!
