### ISSUE TITLE
ccxt.base.errors.ExchangeError: bittrex Currencies not loaded

### ISSUE THREAD

**Issue by nktzdr** [ccxt/ccxt#2674]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: macOS 10.13.3
- Programming Language version: Python3
- CCXT version: latest
- Exchange: bittrex
- Method: withdraw

bittrex.withdraw('BTC', value, wallet)
im trying to withdraw currency from bittrex, but I have that error:
ccxt.base.errors.ExchangeError: bittrex Currencies not loaded

How it can be fixed?

Also I tried to use bittrex py api, and had currency_not_provided error

**Comment by kroitor** [comment]
You version is way too old, please update to most recent version 1.13.46, this bug was fixed months ago. Thx!
