### ISSUE TITLE
Kraken fetchDepositAddress cacheDepositMethodsOnFetchDepositAddress does not work.

### ISSUE THREAD

**Issue by rsparrow** [ccxt/ccxt#2678]
- OS: OSX
- Programming Language version: JS
- CCXT version: 
- Exchange: Kraken
- Method: fetchDepositAddress

When trying to use the following for Kraken:

`exchange.options["cacheDepositMethodsOnFetchDepositAddress"] = true;`

It does not work because line 812 of js/kraken.js is missing an `await` if you change it from this:

`this.options['depositMethods'][code] = this.fetchDepositMethods (code);`

to this:

`this.options['depositMethods'][code] = await this.fetchDepositMethods (code);`

That way the `method` var is filled before line 813.

I'm not setup to do a pull request at the minute but though I'd let you know.

Thanks Again!

**Comment by rsparrow** [comment]
I'll do a pull request on it later today if it's not fixed by then ;-)

**Comment by kroitor** [comment]
Fixed and merged in #2680, CCXT version 1.13.49 (will be available very soon).
