### ISSUE TITLE
COBINHOOD withdraw not working but capability says it's implemented.

### ISSUE THREAD

**Issue by rsparrow** [ccxt/ccxt#2679]
- OS: OSX
- Programming Language version: JS
- CCXT version: 1.13.48
- Exchange: COBINHOOD
- Method: withdraw

The capabilities call  says `withdraw` is supported for COBINHOOD but when I run it I get:
```
[Exchange Error] cobinhood unauthorized_scope
    at cobinhood.handleErrors (.../node_modules/ccxt/js/cobinhood.js:563:15)
    at response.text.then (.../node_modules/ccxt/js/base/Exchange.js:513:18)
```

It might be useful to know that the API docs do not list list a call for `withdraw` see screenshots. So I don't know if this is an issue with the capabilities call or the withdraw call. I've got every right turned on for my API key that they allow on the current API and made sure there is a withdraw address.

Maybe I'm missing something.

![wallet__em__auth___em__ _cobinhood_exchange_-_api_reference](https://user-images.githubusercontent.com/830045/39334266-d436bdc4-4962-11e8-9701-7affe75e39d5.png)

![cobinhood___cryptocurrency_exchange_without_trading_fees](https://user-images.githubusercontent.com/830045/39334106-32173e4c-4962-11e8-9624-a2ae69a25bb7.png)

**Comment by Temperament** [comment]
Can confirm. I've posted this issue onto the cobinhood public API but they've yet to respond. See https://github.com/cobinhood/api-public/issues/48

**Comment by kroitor** [comment]
@firepol yep, you're absolutely right, restored them as they were mistakenly removed.

**Comment by theodorable1** [comment]
hi im unable to withraw my crypto from cobinhhod and they havent responded to my requests.. it there a way to fix myself ?

**Comment by kroitor** [comment]
@theodorable1 you can try `examples/*/cli.*` with `withdraw()` (see the [Manual](https://github.com/ccxt/ccxt/wiki/Manual#withdraw) for details on withdrawal params).

```
echo '{"cobinhood":{"apiKey":"YOUR_API_KEY","secret":"YOUR_SECRET"}}' > keys.local.json
node examples/js/cli cobinhood withdraw ETH YOUR_AMOUNT YOUR_ADDRESS --verbose
```

In general, we don't control your account or your funds, so, you need to reach out to their techs if the above does not help.

**Comment by theodorable1** [comment]
thank you very much.. im mostly clueless of these operations i do hope they respond to my messages before much longer.. again thanks.. your response is most appreciated.. cheeras . D
