### ISSUE TITLE
OKEX withdraw error 10006

### ISSUE THREAD

**Issue by gitmarkuz** [ccxt/ccxt#2683]
- OS: CentOS
- Programming Language version: PHP 5.6.35
- CCXT version: 1.13.49
- Exchange: OKEX
- Method: withdraw

I am getting error_code 10006 from the OKEX API when attempting to make a withdrawal. Is anyone else having this issue?

Other methods such as placing orders, checking balances etc. work fine with the exact same API key and secret. withdraw_info however also gives error 10006.

I've checked and Withdraw privileges is definitely turned on for the API key in my OKEX account.

I've also contacted OKEX customer support and they've been telling me to change the withdrawal symbol from btc_usd to btc_usdt, and then from btc_usdt back to btc_usd over and over for a couple of days now.

If anyone has had the same problem please do let me know. Thank you very much in advance.

Here is the dump from CCXT:

Fatal error: Uncaught exception 'ccxt\ExchangeError' with message 'okex {"result":false,"error_code":10006}' in /home/php/okcoinusd.php:721
Stack trace:
#0 /home/php/Exchange.php(957): ccxt\okcoinusd->handle_errors(200, '', 'https://www.oke...', 'POST', Array, '{"result":false...')
#1 /home/php/Exchange.php(801): ccxt\Exchange->fetch('https://www.oke...', 'POST', Array, 'api_key=cff1b19...')
#2 /home/php/Exchange.php(805): ccxt\Exchange->fetch2('withdraw', 'private', 'POST', Array, NULL, NULL)
#3 [internal function]: ccxt\Exchange->request('withdraw', 'private', 'POST', Array)
#4 /home/php/Exchange.php(740): call_user_func(Array, 'withdraw', 'private', 'POST', Array)
#5 [internal function]: ccxt\Exchange->ccxt\{closure}(Array)
#6 /home/php/Exchange.php(1752): call_user_func_array(Object(Closure), Array)
#7 /home/php/okcoinusd.php(678): ccxt\Exchange->__call('privatePostWith...', Array)
#8 /home/p in /home/php/okcoinusd.php on line 721

**Comment by kroitor** [comment]
@gitmarkuz can you post a minimal (the smallest possible) snippet of code to reproduce this issue? Please include all your code (make it short), without the keys of course. It would be great if you could also do the simplest debug reporting in verbose mode as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue (need to see the request and the response). Standing by for more info from you.

**Comment by gitmarkuz** [comment]
@kroitor and here is the request and response:

``

Request:
Array
(
    [0] => POST
    [1] => https://www.okex.com/api/v1/withdraw.do
    [2] => Array
        (
            [0] => Content-Type: application/x-www-form-urlencoded
        )

    [3] => api_key=MYKEY&chargefee=0.0005&symbol=btc_usd&target=address&trade_pwd=MYTRADEPWD&withdraw_address=MYBTCADDRESS&withdraw_amount=0.1&sign=MYSIGN
)

Response:
Array
(
    [0] => POST
    [1] => https://www.okex.com/api/v1/withdraw.do
    [2] => 200
    [3] => 
    [4] => Array
        (
            [date] => Array
                (
                    [0] => Fri, 27 Apr 2018 07:28:25 GMT
                )

            [content-type] => Array
                (
                    [0] => text/html;charset=UTF-8
                )

            [transfer-encoding] => Array
                (
                    [0] => chunked
                )

            [connection] => Array
                (
                    [0] => keep-alive
                )

            [set-cookie] => Array
                (
                    [0] => __cfduid=MYCLOUDFLAREID; expires=Sat, 27-Apr-19 07:28:24 GMT; path=/; domain=.okex.com; HttpOnly
                    [1] => coin_session_id_o=MYCOINSESSION; Domain=.okex.com; Path=/; Secure; HttpOnly
                    [2] => language=1; Expires=Fri, 04-May-2018 07:28:25 GMT; Path=/
                )

            [cache-control] => Array
                (
                    [0] => no-store
                )

            [expires] => Array
                (
                    [0] => Thu, 01 Jan 1970 00:00:00 GMT
                )

            [pragma] => Array
                (
                    [0] => no-cache
                )

            [x-frame-options] => Array
                (
                    [0] => SAMEORIGIN
                )

            [expect-ct] => Array
                (
                    [0] => max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
                )

            [server] => Array
                (
                    [0] => cloudflare
                )

            [cf-ray] => Array
                (
                    [0] => 411f927ba893550a-ORD
                )

            [content-encoding] => Array
                (
                    [0] => gzip
                )

        )

    [5] => {"result":false,"error_code":10006}
)

**Comment by gitmarkuz** [comment]
Just tried now and I am also getting error code (10006) with methods cancel_withdraw and as previously mentioned withdraw_info.

The strange thing is that according to OKEX error code 10006 means "Api_key does not exist." But the exact same credentials work fine for all other methods including making trades and checking balances.

Also, if you turn off the WIthdraw permission for a API key and then try a withdrawal it changes from error code 10006 to error code 10017 which means "API authorization error."

It makes no sense that it would say the key does not exist when Withdraw is turned on, and then correctly identify that the key exists but that Withdraw permission is turned off when turned off.

To add more confusion to it OKEX's sister site OKCOIN gives an additional meaning to error code 10006 in their FAQ, saying that you should check the request domain: "For OKCoin international account, use www.okcoin.com. For OKCoin China account use www.okcoin.cn"

Does OKEX withdrawals work for anyone else?

**Comment by kroitor** [comment]
@gitmarkuz are you sure that you are using your trading password, not your login password when you set `exchange->password = ...` ? Those are two different passwords...

**Comment by gitmarkuz** [comment]
@kroitor, yes 100% sure that I am using the trade/fund password and not the login password.

Also, I'm getting the same 10006 error for the cancel_withdraw and withdraw_info methods. And those two methods do not require the trade_pwd parameter at all.

Does the withdraw function work for you?

**Comment by Temperament** [comment]
Can confirm. Have the same issue with response error 10006 after you try and submit a withdrawal.

**Comment by kroitor** [comment]
I will debug this, hopefully, very soon and will get back to you with my findings. Thx for your patience!

**Comment by Porozhnyakov** [comment]
Have the same issue

**Comment by pscott** [comment]
Same issue here!

**Comment by claudiocabral** [comment]
Hi everyone,

I did some investigation and I think the error comes from the way `okex` hashes `trade_pwd`. I was using a randomly generated string with all sorts of special characters and after switching to a plain text, lowercase only password the error disapeared. My guess is that there is some character escaping that is done before calculating the md5 hash.

I'll try to figure out what that is...

**Comment by kroitor** [comment]
> I'll try to figure out what that is...

This is urlencoding and double-quotes escaping.

If you write:

```PHP
echo "23\5$foo"; // prints "23"
```

↑ in PHP, then you'll see that some symbols are missing from the output.

So, never write passwords in double quotes in PHP, use single quotes:

```PHP
echo "23\5$foo"; // outputs "23\5$foo"
```
