### ISSUE TITLE
Issue with Bitmex implicit functions

### ISSUE THREAD

**Issue by MaticConradi** [ccxt/ccxt#2684]
- OS: macOS High Sierra
- Programming Language version: Python 3.6.3
- CCXT version: 1.13.48
- Exchange: Bitmex
- Method: bitmex.private_post_position_leverage()

I want to change my position leverage by doing `bitmex.private_post_position_leverage({"symbol": "XBTUSD", "leverage": 5.0})` but it doesn't work.

I also tried:
`bitmex.private_post_position_leverage({"symbol": "XBTUSD", "leverage": "5.0"})`
`bitmex.private_post_position_leverage({"symbol": "BTC/USD", "leverage": 5.0})`
`bitmex.private_post_position_leverage({"symbol": "BTC/USD", "leverage": "5.0"})`

I always catch an exception: `bitmex {"error":{"message":"Access Denied","name":"HTTPError"}}`

The `bitmex.fetch_balance()` works, my API Key and Secret are correct. Any ideas?

**Comment by wu66213510** [comment]
I have the same promble, but mine is create new order.
`ccxt.base.errors.ExchangeError: bitmex {"error":{"message":"Access Denied","name":"HTTPError"}}`
`requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://testnet.bitmex.com/api/v1/order/bulk?orders=%5B%7B%22symbol%22%3A+%22XBTUSD%22%2C+%22side%22%3A+%22Sell%22%2C+%22orderQty%22%3A+1%2C+%22price%22%3A+9999%7D%2C+%7B%22symbol%22%3A+%22XBTUSD%22%2C+%22side%22%3A+%22Sell%22%2C+%22orderQty%22%3A+1%2C+%22price%22%3A+9977%7D%5D
During handling of the above exception, another exception occurred:`
I think bitmex change the api.
![default](https://user-images.githubusercontent.com/32154231/39617016-a0802e08-4fb0-11e8-9099-303275e96dbd.JPG)

**Comment by kroitor** [comment]
@wu66213510 see https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

1. create new key and try with new key
2. make sure you're using a testnet key with bitmex testnet and not mixing the main keys with the testnet...

**Comment by kroitor** [comment]
@MaticConradi thx for reporting back!

**Comment by wu66213510** [comment]
I figure out this promble. As the same situation of the up one, Created a new one with it enabled and it works.
I am so stupid , due to my operation on `https://testnet.bitmex.com/api/explorer/`. It no need the API key, but still work.
Any way ,tank you so much!!!!

**Comment by kroitor** [comment]
@wu66213510 great, thanks for letting us know!

**Comment by Geo-Joy** [comment]
@MaticConradi 
I tried the following 
```
exchange_i = getattr(ccxt, "bitmex")
        exchange_i({
            'apiKey': #api_key
            'secret': #api_secret
            'verbose': False
        })
print(exchange_i.private_post_position_leverage({"symbol": "XBTUSD", "leverage": "5.0"}))`

```
 **but getting an error as follows.**

```
    print(exchange_i.private_post_position_leverage({"symbol": "XBTUSD", "leverage": "5.0"}))
AttributeError: type object 'bitmex' has no attribute 'private_post_position_leverage'
```
any ideas...

**Comment by kroitor** [comment]
@Geo-Joy 

```Python
exchange_i = getattr(ccxt, "bitmex")
        exchange_i({
            'apiKey': #api_key
            'secret': #api_secret
            'verbose': False
        })
```

↓

```Python
exchange_i = getattr(ccxt, "bitmex") ({
    'apiKey': #api_key
    'secret': #api_secret
    'verbose': False
})
```

**Comment by Geo-Joy** [comment]
@kroitor thanks for the quick response but  beautifying code dint resolve.


> [pylint] E1101:Instance of 'bitmex' has no 'private_post_position_leverage' member



```
        exchange_i = getattr(ccxt, "bitmex") ({
            'apiKey': #api_key,
            'secret': #api_secret,
            'verbose': False
        })

        print(exchange_i.private_post_position_leverage({"symbol": "XBTUSD", "leverage": "5.0"}))
```

**Comment by MaticConradi** [comment]
Try getattr(ccxt, “bitmex”)()

**Comment by kroitor** [comment]
@Geo-Joy something wrong with your ccxt import, inspect the instance that was created: 

```Python
from pprint import pprint
pprint(dir(getattr(ccxt, 'bitmex')()))
```

**Comment by Geo-Joy** [comment]
> @Geo-Joy something wrong with your ccxt import, inspect the instance that was created:
> 
> ```python
> from pprint import pprint
> pprint(dir(getattr(ccxt, 'bitmex')()))
> ```

above does not have **private_post_position_leverage**

`["__class__", "__del__", "__delattr__", "__dict__", "__dir__", "__doc__", "__eq__", "__format__", "__ge__", "__getattribute__", "__gt__", "__hash__", "__init__", "__init_subclass__", "__le__", "__lt__", "__module__", "__ne__", "__new__", "__reduce__", "__reduce_ex__", "__repr__", "__setattr__", "__sizeof__", "__str__", "__subclasshook__", "__weakref__", "account", "aggregate", "aiohttpProxy", "aiohttp_proxy", "amountToPrecision", "amount_to_precision", "api", "apiKey", "arrayConcat", "array_concat", "asyncioLoop", "asyncio_loop", "balance", "base64urlencode", "binaryConcat", "binaryToString", "binary_concat", "binary_to_string", "buildOhlcv", "build_ohlcv", "calculateFee", "calculate_fee", "cancelOrder", "cancel_order", "capitalize", "certified", "checkAddress", "checkRequiredCredentials", "check_address", "check_required_credentials", "commonCurrencies", "commonCurrencyCode", "common_currency_code", "convertOhlcvToTradingView", "convertTradingViewToOhlcv", "convert_ohlcv_to_trading_view", "convert_trading_view_to_ohlcv", "costToPrecision", "cost_to_precision", "countries", "createLimitBuyOrder", "createLimitOrder", "createLimitSellOrder", "createMarketBuyOrder", "createMarketOrder", "createMarketSellOrder", "createOrder", "create_limit_buy_order", "create_limit_order", "create_limit_sell_order", "create_market_buy_order", "create_market_order", "create_market_sell_order", "create_order", "currencies", "currenciesById", "currencies_by_id", "currency", "currencyId", "currencyToPrecision", "currency_id", "currency_to_precision", "decimalToPrecision", "decimal_to_precision", "decode", "decryptAccount", "decryptAccountFromJSON", "decryptAccountFromPrivateKey", "deepExtend", "deep_extend", "defineRestApi", "define_rest_api", "describe", "dmy", "editLimitBuyOrder", "editLimitOrder", "editLimitSellOrder", "editOrder", "edit_limit_buy_order", "edit_limit_order", "edit_limit_sell_order", "edit_order", "enableLastHttpResponse", "enableLastJsonResponse", "enableLastResponseHeaders", "enableRateLimit", "encode", "encodeUriComponent", "encode_uri_component", "exceptions", "extend", "extractParams", "extract_params", "feeToPrecision", "fee_to_precision", "fees", "fetch", "fetch2", "fetchBalance", "fetchBidsAsks", "fetchClosedOrders", "fetchCurrencies", "fetchDepositAddress", "fetchDeposits", "fetchFees", "fetchFreeBalance", "fetchFundingFees", "fetchL2OrderBook", "fetchMarkets", "fetchMyTrades", "fetchOHLCV", "fetchOhlcv", "fetchOpenOrders", "fetchOrder", "fetchOrderBook", "fetchOrderStatus", "fetchOrderTrades", "fetchOrders", "fetchPartialBalance", "fetchTicker", "fetchTickers", "fetchTotalBalance", "fetchTrades", "fetchTransactions", "fetchUsedBalance", "fetchWithdrawals", "fetch_balance", "fetch_bids_asks", "fetch_closed_orders", "fetch_currencies", "fetch_deposit_address", "fetch_deposits", "fetch_fees", "fetch_free_balance", "fetch_funding_fees", "fetch_l2_order_book", "fetch_markets", "fetch_my_trades", "fetch_ohlcv", "fetch_open_orders", "fetch_order", "fetch_order_book", "fetch_order_status", "fetch_order_trades", "fetch_orders", "fetch_partial_balance", "fetch_ticker", "fetch_tickers", "fetch_total_balance", "fetch_trades", "fetch_transactions", "fetch_used_balance", "fetch_withdrawals", "filterBy", "filterByArray", "filterByCurrencySinceLimit", "filterBySinceLimit", "filterBySymbol", "filterBySymbolSinceLimit", "filterByValueSinceLimit", "filter_by", "filter_by_array", "filter_by_currency_since_limit", "filter_by_since_limit", "filter_by_symbol", "filter_by_symbol_since_limit", "filter_by_value_since_limit", "findBroadlyMatchedKey", "findMarket", "findSymbol", "find_broadly_matched_key", "find_market", "find_symbol", "fromWei", "getZeroExOrderHash", "getZeroExOrderHash2", "groupBy", "group_by", "gzipDeflate", "gzip_deflate", "handleErrors", "handleRestErrors", "handleRestResponse", "handle_errors", "handle_rest_errors", "handle_rest_response", "has", "hash", "hashMessage", "headers", "hmac", "hostname", "httpExceptions", "id", "ids", "implodeParams", "implode_params", "inArray", "in_array", "indexBy", "index_by", "isEmpty", "isJsonEncodedObject", "is_empty", "is_json_encoded_object", "iso8601", "json", "jwt", "keysort", "lastHttpResponse", "lastJsonResponse", "lastResponseHeaders", "lastRestPollTimestamp", "lastRestRequestTimestamp", "last_http_response", "last_json_response", "last_response_headers", "limits", "loadFees", "loadMarkets", "loadTimeDifference", "loadTradingLimits", "load_fees", "load_markets", "load_time_difference", "load_trading_limits", "logger", "market", "marketId", "marketIds", "market_id", "market_ids", "markets", "marketsById", "markets_by_id", "microseconds", "milliseconds", "minFundingAddressLength", "msec", "name", "nonce", "omit", "options", "orderbooks", "ordered", "orders", "origin", "parse8601", "parseBalance", "parseBidAsk", "parseBidsAsks", "parseDate", "parseIfJsonEncodedObject", "parseJsonResponse", "parseOhlcv", "parseOhlcvs", "parseOrder", "parseOrderBook", "parseOrderStatus", "parseOrders", "parseTicker", "parseTickers", "parseTimeframe", "parseTrade", "parseTrades", "parseTransaction", "parseTransactionStatusByType", "parseTransactions", "parse_balance", "parse_bid_ask", "parse_bids_asks", "parse_date", "parse_if_json_encoded_object", "parse_ohlcv", "parse_ohlcvs", "parse_order", "parse_order_book", "parse_order_status", "parse_orders", "parse_ticker", "parse_tickers", "parse_timeframe", "parse_trade", "parse_trades", "parse_transaction", "parse_transaction_status_by_type", "parse_transactions", "password", "pluck", "populateFees", "populate_fees", "precision", "precisionFromString", "precisionMode", "precision_from_string", "prepareRequestHeaders", "prepare_request_headers", "priceToPrecision", "price_to_precision", "privateDeleteOrder", "privateGetAccount", "privateGetAllOrders", "privateGetAllorders", "privateGetMyTrades", "privateGetMytrades", "privateGetOpenOrders", "privateGetOpenorders", "privateGetOrder", "privateKey", "privatePostOrder", "privatePostOrderTest", "private_delete_order", "private_get_account", "private_get_allorders", "private_get_mytrades", "private_get_openorders", "private_get_order", "private_post_order", "private_post_order_test", "proxies", "proxy", "publicDeleteUserDataStream", "publicDeleteUserdatastream", "publicGetAggTrades", "publicGetAggtrades", "publicGetDepth", "publicGetExchangeInfo", "publicGetExchangeinfo", "publicGetKlines", "publicGetPing", "publicGetTicker24hr", "publicGetTickerAllBookTickers", "publicGetTickerAllPrices", "publicGetTickerAllbooktickers", "publicGetTickerAllprices", "publicGetTickerBookTicker", "publicGetTickerBookticker", "publicGetTickerPrice", "publicGetTime", "publicPostUserDataStream", "publicPostUserdatastream", "publicPutUserDataStream", "publicPutUserdatastream", "public_delete_userdatastream", "public_get_aggtrades", "public_get_depth", "public_get_exchangeinfo", "public_get_klines", "public_get_ping", "public_get_ticker_24hr", "public_get_ticker_allbooktickers", "public_get_ticker_allprices", "public_get_ticker_bookticker", "public_get_ticker_price", "public_get_time", "public_post_userdatastream", "public_put_userdatastream", "purgeCachedOrders", "purge_cached_orders", "raiseError", "raise_error", "rateLimit", "rateLimitMaxTokens", "rateLimitTokens", "rateLimitUpdateTime", "rawencode", "request", "requiredCredentials", "restPollerLoopIsRunning", "restRequestQueue", "safeEither", "safeFloat", "safeFloat2", "safeInteger", "safeInteger2", "safeString", "safeString2", "safeValue", "safeValue2", "safe_either", "safe_float", "safe_float_2", "safe_integer", "safe_integer_2", "safe_string", "safe_string_2", "safe_value", "safe_value_2", "sec", "seconds", "secret", "session", "setMarkets", "set_markets", "sign", "signHash", "signMessage", "signZeroExOrder", "soliditySha256", "soliditySha3", "solidityTypes", "solidityValues", "sortBy", "sort_by", "substituteCommonCurrencyCodes", "sum", "symbols", "throttle", "tickers", "timeframes", "timeout", "toArray", "toWei", "to_array", "tokenBucket", "trades", "transactions", "truncate", "truncateToString", "truncate_to_string", "twofa", "uid", "unique", "unjson", "url", "urlencode", "urls", "usec", "userAgent", "userAgents", "uuid", "v3GetTickerBookTicker", "v3GetTickerBookticker", "v3GetTickerPrice", "v3_get_ticker_bookticker", "v3_get_ticker_price", "verbose", "version", "walletAddress", "wapiGetAccountStatus", "wapiGetAccountstatus", "wapiGetDepositAddress", "wapiGetDepositHistory", "wapiGetDepositaddress", "wapiGetDeposithistory", "wapiGetGetAllAsset", "wapiGetGetallasset", "wapiGetSystemStatus", "wapiGetSystemstatus", "wapiGetWithdrawFee", "wapiGetWithdrawHistory", "wapiGetWithdrawfee", "wapiGetWithdrawhistory", "wapiPostWithdraw", "wapi_get_accountstatus", "wapi_get_depositaddress", "wapi_get_deposithistory", "wapi_get_getallasset", "wapi_get_systemstatus", "wapi_get_withdrawfee", "wapi_get_withdrawhistory", "wapi_post_withdraw", "web3", "webGetAssetWithdrawGetAllAssetHtml", "webGetAssetwithdrawGetallassetHtml", "webGetExchangePublicProduct", "web_get_assetwithdraw_getallasset_html", "web_get_exchange_public_product", "withdraw", "ymd", "ymdhms"]`

**Comment by Geo-Joy** [comment]
> @Geo-Joy something wrong with your ccxt import, inspect the instance that was created:
> 
> ```python
> from pprint import pprint
> pprint(dir(getattr(ccxt, 'bitmex')()))
> ```
above has 
'private_get_user_margin',
 'private_get_user_minwithdrawalfee',
 'private_get_user_wallet',
 'private_get_user_wallethistory',
 'private_get_user_walletsummary',
 'private_post_apikey',
 'private_post_apikey_disable',
 'private_post_apikey_enable',
 'private_post_chat',
 'private_post_order',
 'private_post_order_bulk',
 'private_post_order_cancelallafter',
 'private_post_order_closeposition',
 'private_post_position_isolate',
 **'private_post_position_leverage',**
 'private_post_position_risklimit',
 'private_post_position_transfermargin',
 'private_post_user_cancelwithdrawal',

**Comment by Geo-Joy** [comment]
@MaticConradi and @kroitor 
It worked  - I was on testnet had to switch api URL to testnet.
any how the error thrown was confusing

**working code**
        ```
exchange_i = getattr(ccxt, "bitmex") ({
            'urls':{
                    'api':'https://testnet.bitmex.com'
                },
            'apiKey': 'uZ3vb_...',
            'secret': 'S0cPup3...',
            'verbose': False
        })

        print(exchange_i.private_post_position_leverage({"symbol": "XBTUSD", "leverage": "5.0"}))
```

Thanks for the support!!!
