### ISSUE TITLE
the problem with fetchorderboook lbank

### ISSUE THREAD

**Issue by hamti2018** [ccxt/ccxt#2690]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: windows 7
- Programming Language version: nodejs 10
- CCXT version:  1.12.176
- Exchange: lbank
- Method: fetchOrderBook
```

const ccxt = require('ccxt')
const lbank = new ccxt.lbank();

(async () => {
  await lbank.loadMarkets()
  console.log(await lbank.fetchOrderBook('ETH/USDT'))
})
```

Data that gives ccxt and data that is on the site is very different, sometimes the difference comes to$50. As through the browser turn https://api.lbank.info/v1/depth.do?symbol=eth_usdt&size=60 (api.lbank.info) data gives normal. Maybe the problem is in the filter?

Thanks!

**Comment by mkutny** [comment]
Try `> node examples/js/cli.js lbank fetchOrderBook ETH/USDT --verbose` and see what the server returns before it gets processed by ccxt.

**Comment by kroitor** [comment]
@hamti2018 Usually the website is the one that lags behind, however, it may as well be the opposite. Basically, the website is usually a less direct path to the exchange engine, than through their API... CCXT does not do any filtering and you get the data how Lbank API sends it towards your machine.

See this video showing the work of [examples/js/live-orderbook.js](https://github.com/ccxt/ccxt/blob/master/examples/js/live-orderbook.js) and use it to compare website against API+ccxt: https://youtu.be/YkJoHR9kwQw

You can also add a userAgent to simulate your browser:

```JavaScript
exchange.userAgent = exchange.userAgents['chrome']
// or any random string 
exchange.userAgent = 'foobar'
const ordersbook = exchange.fetchOrderBook (...
```

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Let us know if it does not help. Thx!
