### ISSUE TITLE
Newb Question: I see that ccxt and catalyst enigma can run together

### ISSUE THREAD

**Issue by Criptical** [ccxt/ccxt#2693]
From a birds eye point of view, what are some things we should be considering when optimizing an algo trader with ccxt and catalyst(or any strategic algo system)?

Backtrader can backtest with ccxt as well. Which do you think is easier for a beginner, who has only learned python and all its packages that are necessary for ccxt, and whatever else is needed to code up the algorithmic strategies. 

I have figured out how to communicate with exchanges (thanks to you guys), python and a little TA. I've also learned what an arbitrage algorithm(code) looks like with catalyst. But ultimately I'm still missing the granular steps to take this whole system to the end (version 1) because I have never done anything like this before. 

I still don't even know where I am going to host this thing, catalyst kept shutting down ATOM ide when running an arbitrage test bot.

I'm close though, I can smell the satoshi's as they bounce back and forth. 

Ultimately, I think I am looking for a community that is working together to backtest and getting these systems up and running. I also learned how to build websites over the past 3 years. And, what I learned from there was to find the community that is working together for a common goal. Similar to how responsive and helpful ccxt has been. Thanks by the way, there is a budding community here and its only going to get stronger.  

any feedback, comments, thoughts, advice, and even a middle finger about any of this helps. :)

negatives are positives, and positives are positives (it is all welcomed to me) 

Thanks 

ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: windows
- Programming Language version: python 3+ current
- CCXT version: latest
- Exchange: none yet
- Method: not sure

**Comment by frosty00** [comment]
ambiguous question
