### ISSUE TITLE
indodax.fetch_balance()

### ISSUE THREAD

**Issue by wahyuhadi** [ccxt/ccxt#2697]
ATTENTION!!!

indodax: unknown error: {"success":0,"error":"Nonce must be greater than 15249487513240000. You provided 1524998484.","error_code":"invalid_nonce"}

**Comment by kroitor** [comment]
Try creating a new unused key, your nonce number is screwed by your previous software package.

More about it: https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Hope this helps.
