### ISSUE TITLE
python bitfinex, huobipro have no attribute 'decimal_to_precision'

### ISSUE THREAD

**Issue by ypetrusha** [ccxt/ccxt#2699]
```
fee = exchange.calculate_fee(symbol, None, side, amount, price, takerOrMaker, params)
  File "/Users/.../venv/lib/python3.6/site-packages/ccxt/async/bitfinex.py", line 390, in calculate_fee
    'cost': float(self.fee_to_precision(market[key], rate * cost)),
  File "/Users/.../venv/lib/python3.6/site-packages/ccxt/async/bitfinex.py", line 379, in fee_to_precision
    return self.decimal_to_precision(fee, ROUND, self.currencies[currency]['precision'], self.precisionMode)
AttributeError: 'bitfinex' object has no attribute 'decimal_to_precision'
```
Problem introduced in 1.12.41. It affects both sync/async implementations
Test to reproduce:

```python
import unittest
from ccxt import *

class FeeTest(unittest.TestCase):

    def test_trading_fee(self):
        _bitfinex = bitfinex()
        _bitfinex.load_markets()
        fee = _bitfinex.calculate_fee('ETH/BTC', None, 'sell', 1, 0.1)
        self.assertEqual({'rate': 0.002, 'type': 'taker', 'currency': 'BTC', 'cost': 0.0002}, fee
```

- OS: Windows/Mac
- Programming Language version: Python 3x
- CCXT version: Latest
- Exchange: Bitfinex, huobipro
- Method: calculate_fee()

**Comment by kroitor** [comment]
@ypetrusha are you sure that your current version of ccxt is up to date?

```Python
import ccxt
print(ccxt.__version__)
```
?

**Comment by ypetrusha** [comment]
@kroitor yes. It prints 1.13.54

**Comment by kroitor** [comment]
Fixed by @frosty00 in #2656 , will merge it shortly.

**Comment by CHANGAIQING** [comment]
Has this bug been fixed?
Why did I come across again?

ccxt version ccxt (1.14.36)

**Comment by frosty00** [comment]
Any chance the transpiled tests will be merged. If i recall correctly that was why you were putting off merging any decimal_to_precision commits

**Comment by kroitor** [comment]
@frosty00 sorry for the delays, yes, i'm still going to merge it, just didn't have a chance to finish my part thoughtfully. Will let you know when it's there. Thx for your patience.
