### ISSUE TITLE
Rate limit exceeded in Bitfinex with enableRateLimit = True

### ISSUE THREAD

**Issue by aking7** [ccxt/ccxt#2700]
- OS: Windows 10
- Programming Language version: Python
- CCXT version: 3.5.3
- Exchange: bitfinex
- Method: Rate limit is exceeded when querying trades for each symbol on the exchange as follows:

 ```
exchange = 'bitfinex'
exchange = getattr(ccxt, exchange)()
exchange.apiKey = ''
exchange.secret = ''
exchange.enableRateLimit = True
exchange.load_markets()
    
trades = {}
for symbol in exchange.symbols:
    trades[symbol] = exchange.fetchMyTrades(symbol)
```
```
DDoSProtection: bitfinex {"error":"ERR_RATE_LIMIT"}
```

P.S. I would be happy to hear if there is a more elegant way to get all my trades from an exchange than querying all possible trading pairs.

**Comment by flavioespinoza** [comment]
This is happening on Bittrex as well.

`const btrx_params = {
  'apiKey': keys.btrx_api_key,
  'secret': keys.btrx_secret_key,
  'enableRateLimit': true,
  'nonce': function () {
    return this.milliseconds()
  }
}
const BTRX = new ccxt.bittrex(btrx_params)`

Result in the console: 

<img width="998" alt="screen shot 2018-04-30 at 10 50 48 am" src="https://user-images.githubusercontent.com/2214913/39439510-11659d6e-4c65-11e8-845b-0abfb4a27107.png">

**Comment by kroitor** [comment]
Hi! This is a known behaviour with some endpoints of particular exchanges. From the Manual:

https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

> **The `exchange.rateLimit` property is set to a safe default which is sub-optimal. Some exchanges may have varying rate limits for different endpoints. It is up to the library user to tweak `rateLimit` according to application-specific purposes.**

There's also an alternative tokenBucket algorithm for precise control over the rate limit per endpoint, however, you it is still experimental on not documented yet, read more about it here: #1399 

Let us know if it does not answer your question. Thx!

**Comment by kroitor** [comment]
Related: https://github.com/ccxt/ccxt/issues/2041#issuecomment-393174567
