### ISSUE TITLE
coinegg fetchMarkets() for "btc" returned => "null"

### ISSUE THREAD

**Issue by MixMe** [ccxt/ccxt#2701]
![firefox_screenshot_2018-04-29t18-20-11 924z](https://user-images.githubusercontent.com/3535911/39409629-22a2f602-4bf3-11e8-8196-d19aef962979.png)

- OS: Ubuntu Server 16.04
- Programming Language version: PHP
- CCXT version: 1.13.54
- Exchange: coinegg 
- Method: fetchMarkets

**Comment by kroitor** [comment]
See this:

- https://github.com/ccxt/ccxt/wiki/Manual#error-handling
- https://github.com/ccxt/ccxt/wiki/Manual#networkerror
- https://github.com/ccxt/ccxt/wiki/Manual#exchangenotavailable

ExchangeNotAvailable is a subclass of NetworkError which is usually recoverable, so a subsequent retry can be enough to resolve this issue. Let us know if it does not help.

**Comment by MixMe** [comment]
AutoRetry system will be great ;)

**Comment by MixMe** [comment]
ok thx

**Comment by kroitor** [comment]
@MixMe on the auto-retry: https://github.com/ccxt/ccxt/issues/961 )
