### ISSUE TITLE
PHP ccxt\ExchangeNotAvailable

### ISSUE THREAD

**Issue by MixMe** [ccxt/ccxt#2702]
allcoin GET https://www.allcoin.com/Home/MarketOverViewDetail/ 51 SSL: no alternative certificate subject name matches target host name 'www.allcoin.com'
![firefox_screenshot_2018-04-29t18-24-29 316z](https://user-images.githubusercontent.com/3535911/39409655-b9085eca-4bf3-11e8-9ee2-83e8ecf13825.png)

- OS: Ubuntu Server 16.04
- Programming Language version: PHP
- CCXT version: 1.13.54
- Exchange: coinegg
- Method: load_markets

**Comment by kroitor** [comment]
Need to verify that your version of OpenSSL is newer than as of January or February of this year, should be 1.0.2c+, can you show your OpenSSL / system ssl library version?

**Comment by MixMe** [comment]
![firefox_screenshot_2018-04-30t10-42-21 550z](https://user-images.githubusercontent.com/3535911/39423805-545f2b64-4c7c-11e8-8371-7020727d4eab.png)

**Comment by MixMe** [comment]
OpenSSL version is 1.0.2g
