### ISSUE TITLE
Bittrex fetchClosedTrades with since filter does not return any orders

### ISSUE THREAD

**Issue by kjanoudi** [ccxt/ccxt#2705]
- OS: Mac High Sierra
- Programming Language version: Javascript
- CCXT version: 1.13.54
- Exchange: Bittrex
- Method: fetchClosedTrades

https://github.com/ccxt/ccxt/blob/master/js/bittrex.js#L530 sets the timestamp based on `Opened` or `Created`, neither of which are returned on the https://bittrex.com/api/v1.1/account/getorderhistory call according to https://support.bittrex.com/hc/en-us/articles/115003723911-Developer-s-Guide-API#apireference

Suggestion: `TimeStamp` is returned as part of the order history endpoint. Instead of only setting lastTradeTimestamp, it should also set timetamp so that the `since` filtering works.

**Comment by frosty00** [comment]
Yes I agree, in situations where only `lastTradeTimeStamp` is populated - (it is not a standard field for all exchange `fetchOrders` response) - we should also populate `timestamp`. This could be achieved easily with

```
if (typeof timestamp === 'undefined')
    timestamp = lastTradeTimestamp
```
