### ISSUE TITLE
Can't execute createMarketBuyOrder due to "insufficient balance" error

### ISSUE THREAD

**Issue by jeffryhartanto** [ccxt/ccxt#2707]
- OS: Windows 7
- Programming Language version: Javascript
- CCXT version: 1.13.19
- Exchange: Binance
- Method: createMarketBuyOrder

I executed the code below:
```
console.log(tradingPairs[BEST_TRADING_PAIR_INDEX][SYMBOL_INDEX], balance.USDT.free)
//above code print out "ETH/USDT 18.87629041"
exchange.createMarketBuyOrder (tradingPairs[BEST_TRADING_PAIR_INDEX][SYMBOL_INDEX], balance.USDT.free)
```

However, I got this error:

```
(node:12940) UnhandledPromiseRejectionWarning: Error: binance {"code":-2010,"msg":"Account has insufficient balance for requested action."}
    at binance.handleErrors (C:\Users\workshop\node_modules\ccxt\js\binance.js:862:31)
    at response.text.then (C:\Users\workshop\node_modules\ccxt\js\base\Exchange.js:513:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:12940) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12940) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any idea why? Is it related to the fee? I ran similar code with market sell order and there is no issue. Thanks in advance.

**Comment by mkutny** [comment]
https://github.com/ccxt/ccxt/blob/942b698649125532a531bdf38ba7a92639b64944/js/base/Exchange.js#L996-L998

**Comment by jeffryhartanto** [comment]
@mkutny Sorry, I don't get it.. can you elaborate please?

**Comment by mkutny** [comment]
What currency and in what amount are you going to buy?

**Comment by jeffryhartanto** [comment]
I want to buy ETH with 18.87629041 USDT.. 

I found the problem, I thought the amount is in USDT... The weird part is that when I want to sell, say ETH to USDT, I need to put the amount of ETH. However, if i want to buy ETH from USDT, I also need to put the amount of ETH. Shouldn't I just need to put the USDT amount? Because if I have to put the ETH amount, then I need to calculate the ETH amount that I can get with certain USDT amount, which so inconvenient. Is it possible to update the market buy method?

**Comment by kroitor** [comment]
> Shouldn't I just need to put the USDT amount when I want to buy ETH?

- When you buy – you buy ETH for USDT.
- When you sell – you sell ETH for USDT.

So all amounts are in base currency, all prices are in quote currency:

https://github.com/ccxt/ccxt/wiki/Manual#consistency-of-base-and-quote-currencies

```
base currency ↓
             BTC / USDT
             ETH / BTC
            DASH / ETH
                    ↑ quote currency
```

This is a normal mode of operation of practically any FX system or crypto exchange. Some exchanges will allow to specify the money to spend in the quote currency, but most of them won't. You need to consult their exchange-specific docs for that.

Hope this answers your questions. Let us know if not.

**Comment by jeffryhartanto** [comment]
Oh.. I see, this is my first experience of using a library for trading.. BTW, any suggestion on the best way to compute the amount of ETH when I want to buy using market buy method?

Currently, I did this:

    let orderbook = await exchange.fetchOrderBook ('ETH/USDT')
    bid = orderbook.bids.length ? orderbook.bids[0][0] : undefined
    let coin = (balance.USDT.free / bid).toFixed(4) - 0.0001
    exchange.createMarketBuyOrder ('ETH/USDT', (balance.USDT.free / bid).toFixed(4) - 0.0001)

**Comment by mkutny** [comment]
It's a bit more involved.

In general, your order is bound by:
- amount/price/cost min/max limits (stored in `market.limits` property)
- your available balance
- precisions for price and amount (stored in `market.precisions` property)

So first, you estimate your target amount with `balance / price`.

Then you truncate amount to the required precision with https://github.com/ccxt/ccxt/blob/334ebc682e9c5139ae5042434e437cadcefebebd/js/base/Exchange.js#L1012

If you take your price from orderbook then it's ready to use. But if it's the result of some calculation then you need to round it up or down (depending on your logic) to the precision... That's a bit tricky as ccxt rounds it to the nearest neighbor with `priceToPrecision`. Maybe guys will make it directional but at the moment you'll need to enforce the direction by yourself.

Then you calculate the cost (i.e. `truncated amount * rounded price`).

Then you check if all three (amount/price/cost) passes the limits.

Then you place your order!

It may sound scary but these are few lines of code in reality.

**Comment by kootenpv** [comment]
@mkutny Thanks for your detailed explanation. I still don't really understand the conditions for it to pass reliably.

Did you mean that you have to manually add up the `volume * price` of the sell orders (when buying) and keep going until the `cumulated (price * amount)` hits how much you have in quote?

If you use the orderbook as a measurement tool, it could still be that by the time you post it, it could still be outdated compared to an order arriving just before you?

**Comment by mkutny** [comment]
> Did you mean that you have to manually add up the volume * price of the sell orders (when buying) and keep going until the cumulated (price * amount) hits how much you have in quote?

While your explanation is correct I didn't mean that, actually. I didn't touch how to come up with price and amount. I was talking about how to make sure your order hits orderbook once you have price and amount calculated. The issue is that if the order is under limits then it will trigger `InvalidOrder` exception. If it exceeds your available balance it will trigger `InsufficientFunds`.

> If you use the orderbook as a measurement tool, it could still be that by the time you post it, it could still be outdated compared to an order arriving just before you

Sure. It happens all the time.

> failing your entire order?

No. The part that hits other orders will get executed immediately. The rest of your order will remain resting in the orderbook. So, technically, your order won't fail, it will be just partly executed.

You may want to read more details here: https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades

**Comment by jeffryhartanto** [comment]
The problem with providing the amount of base currency in marketBuyOrder is that I might  occasionally get an invalidAmount error, because the bid price might increase due to network delay before the order get submitted.. Any workaround for this issue? Should I just use limitBuyOrder, so I won't get the error?

Currently, I subtract the computed amount (USDT / bid price) with market.limits.amount.min, though it only works if there is only a very slight change on the bid price..

**Comment by kootenpv** [comment]
I learned something new about how market orders work and have solved the issue.

When you want to make sure your market order goes through, you have to actually ask for a smaller amount. I was messing with "price" but what matters is that you set the amount so that you have a little space.

E.g: you can buy 10 at current price. I thought I have to increase the price to make it work, but it's opposite. To make sure it goes through you have to lower the amount. You can do 1% for example.
At for example hitbtc you can see that it shows price at 10% higher in your order. I was shocked: am I losing 10% here? It's the default kind of limit they put in a market order. It will still start matching you to the lowest sells on the orderbook, so when you look at average price paid, then it does work out, but that 10% gives you a scare.

**Comment by jeffryhartanto** [comment]
Hi, what will happen if I put a very large market order? Let's say I put an 1000 ETH market sell order or market buy order.. I think this kind of order won't be immediately filled..

**Comment by kroitor** [comment]
Just a quick update: we have added the support for total cost for market orders with Binance here: https://github.com/ccxt/ccxt/issues/6391#issuecomment-576247330
