### ISSUE TITLE
Error handling issues in python 2.7

### ISSUE THREAD

**Issue by tzachshabtay** [ccxt/ccxt#2713]
Occasionally I get these errors when placing an order on gemini (it usually works):

```
  File "/usr/local/lib/python2.7/dist-packages/ccxt/gemini.py", line 213, in create_order
    response = self.privatePostOrderNew(self.extend(order, params))
  File "/usr/local/lib/python2.7/dist-packages/ccxt/gemini.py", line 276, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python2.7/dist-packages/ccxt/base/exchange.py", line 302, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python2.7/dist-packages/ccxt/base/exchange.py", line 380, in fetch
    self.raise_error(ExchangeError, url, method, e, self.last_http_response)
  File "/usr/local/lib/python2.7/dist-packages/ccxt/base/exchange.py", line 287, in raise_error
    raise exception_type(output)
ExchangeError: gemini https://api.gemini.com/v1/order/new POST ('Connection aborted.', BadStatusLine("''",)) {"order_id":"3609682318","id":"3609682318
","symbol":"btcusd","exchange":"gemini","avg_execution_price":"0.00","side":"buy","type":"exchange limit","timestamp":"1525119104","timestampms":1525119104623,"is_live":false,"is_cancelled":true,"is_hidden":false,"was_forced":false,"executed_amount":"0","remaining_amount":"0.2","client_order_id":"1525119104568195","options":["maker-or-cancel"],"price":"9284.11","original_amount":"0.2"}
```

Now, from my understanding, the `BadStatusLine` error is Gemini responding with invalid http, so I don't expect ccxt can fix that.

But, from reporting the error standpoint, several issues stand out to me:
1. The stack trace swallows the actual line the error occurred on. I'm guessing the error came from this line: https://github.com/ccxt/ccxt/blob/deb2fa2ba0ffb648e8fe46d1d0efda5fb1085ffb/python/ccxt/base/exchange.py#L351
But that information was lost due to (I'm guessing) a new exception being thrown instead of rethrowing the old exception.
2. The error message is unfriendly. It writes a bunch of arguments joined with spaces and without explanations, so hard to see where each argument begins and what everything means -> it forces the user to look at the ccxt source code.
3. The last argument in this exception is a response object -> my initial assumption was that this is the response from the server which triggered the error. This does not seem to be the case, though. Assuming my guess for issue 1 is correct, this is actually the http response for the previous request, which is very misleading, especially considering issue 2.
4. I don't know if this one is possible, but specifically for the BadStatusLine exception, it would be very useful to see the raw text returned from the server.

- OS: Ubuntu 16.04 LTS 64 Bits
- Programming Language version:python 2.7
- CCXT version: 1.12.174
- Exchange: Gemini
- Method: create_order

**Comment by frosty00** [comment]
Since it raises an ExchangeError (the error was handled correctly by the ccxt base code) you should catch the error by doing:

```
try:
    gemini.create_order(..
except ccxt.base.errors.BaseException:
   try_again()
```

**Comment by tzachshabtay** [comment]
Yes, I know how to catch exceptions. This is not what this issue is about.

Please read my comments above to see why I think the error handling by ccxt here is lacking.

**Comment by tzachshabtay** [comment]
Oh, and also, I can't retry as I can't be sure if the order went through or not. If it did go through, then I don't want to send another order.
This is why I'm interested in getting the raw text back, it might have a clue.

**Comment by frosty00** [comment]
add `gemini.verbose = True` but it is clearly an ExchangeError

**Comment by tzachshabtay** [comment]
`ExchangeError` is the ccxt thrown exception, which (like I said in section 1) swallows the original stack trace so you lose information. 
Please read this article which might better explain what I mean: https://nedbatchelder.com/blog/200711/rethrowing_exceptions_in_python.html

I can try adding `verbose`, though if my assumption is correct, it's not going to help me as the exception is thrown before the response is printed.

**Comment by frosty00** [comment]
Is you're version of `requests` working with other websites? ('Connection aborted.', BadStatusLine("''",)) inherits from RequestsException

**Comment by tzachshabtay** [comment]
Yes, it is. I'm using ccxt successfully with several other exchanges in the same process. Also, as I said, it does work for gemini usually, this error happens 1-2 times a day on average out of a full trading day. 

I tend to believe the error is coming from gemini and it's not ccxt's fault -> both because of this (https://github.com/requests/requests/issues/2364) and because of the fact that I'm also using their web socket and get a lot of garbage from them which doesn't happen so frequently on the other exchanges.
It's just the error handling which can be improved.

**Comment by frosty00** [comment]
I mean the error handling returns ExchangeError because it has something to do with the http:// connection. TCP is notoriously unreliable so you need to rethink your error handling and wrap all ccxt requests with a decorator if you want it to be more reliable. If it is working sometimes then it cannot be ccxt's fault.
