### ISSUE TITLE
Binance market order price

### ISSUE THREAD

**Issue by XliveStudios** [ccxt/ccxt#2714]
OS: Windows
Programming Language version: Python 3x
CCXT version: Latest
Exchange: Binance
Method: fetch_orders()

How to know market order price on binance with python using ccxt?

```
order = exchange.fetch_orders('EOS/BTC')
print(order)
```

```
[{'amount': 50.82,
  'cost': 0.0,
  'datetime': '2018-04-23T18:40:46.899Z',
  'fee': None,
  'filled': 50.82,
  'id': '36725616',
  'info': {'clientOrderId': 'pc_1fb9a33ae5d0497598a925cc5229fd38',
           'executedQty': '50.82000000',
           'icebergQty': '0.00000000',
           'isWorking': True,
           'orderId': 36725616,
           'origQty': '
           'price': '0.00000000',
           'side': 'SELL',
           'status': 'FILLED',
           'stopPrice': '0.00000000',
           'symbol': 'EOSBTC',
           'time': 1524508845899,
           'timeInForce': 'GTC',
           'type': 'MARKET'},
  'price': 0.0,
  'remaining': 0.0,
  'side': 'sell',
  'status': 'closed',
  'symbol': 'EOS/BTC',
  'timestamp': 1524508845899,
  'type': 'market'}
]
```

You see there **'price': 0.0** in json response. But in binance history prices are showing clearly. 

[https://i.hizliresim.com/gO3JML.png](https://i.hizliresim.com/gO3JML.png)

**Comment by XliveStudios** [comment]
I think the solution is fetchMyTrades().

**Comment by kroitor** [comment]
@XliveStudios if you want the historical market price, then you want `fetchMyTrades`. If you want to precalculate the market price for a market order, then you might want to also check this: https://github.com/ccxt/ccxt/issues/2707.

Hope this answers your question. Let us know if not.
