### ISSUE TITLE
huobipro withdraw error

### ISSUE THREAD

**Issue by nktzdr** [ccxt/ccxt#2716]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: macOS
- Programming Language version: python3
- CCXT version: 1.13.48
- Exchange: huobipro
- Method: withdraw

when im trying to huobi_client.withdraw(coin, amount, adress)
I have:
ccxt.base.errors.ExchangeError: huobipro {"status":"error","err-code":"api-not-support-temp-addr","err-msg":"api withdraw, not support temp address","data":null}

how can I fix it?

**Comment by kroitor** [comment]
Can you please show the shortest possible snippet of code to reproduce it (but a complete program) and the full verbose output, precisely as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue (no need for your keys). ?

**Comment by ray66rus** [comment]
Hi

Have the same issue here :(

- OS: 4.15.0-29-generic #31~16.04.1-Ubuntu SMP
- Programming Language version: Python 3.6.3
- CCXT version: 1.17.66
- Exchange: huobipro
- Method: withdraw

Minimal example:
```
import ccxt
q = ccxt.huobipro({'apiKey': <some key>, 'secret': <some secret>})
q.verbose = True
q.withdraw('ETH', 0.04, '0x77670b90c12943dfde69c73cc4b92c1b9fab7f48')
```

Reply:
```
Request: POST https://api.huobi.pro/v1/dw/withdraw/api/create?AccessKeyId=<some key>&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2018-08-07T12%3A57%3A49&address=0x77670b90c12943dfde69c73cc4b92c1b9fab7f48&amount=0.1&currency=eth&Signature=KTloyQvgPSjlRJIYti6oDQm%2BN0q2ISvztXGGLhnHOMA%3D {'Content-Type': 'application/json', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} {"address":"0x77670b90c12943dfde69c73cc4b92c1b9fab7f48","amount":0.1,"currency":"eth"}

Response: POST https://api.huobi.pro/v1/dw/withdraw/api/create?AccessKeyId=<some key>&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2018-08-07T12%3A57%3A49&address=0x77670b90c12943dfde69c73cc4b92c1b9fab7f48&amount=0.1&currency=eth&Signature=KTloyQvgPSjlRJIYti6oDQm%2BN0q2ISvztXGGLhnHOMA%3D 200 {'Date': 'Tue, 07 Aug 2018 12:57:49 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=df64534e47ca4fabe435521a460fc08ec1533646669; expires=Wed, 07-Aug-19 12:57:49 GMT; path=/; domain=.api.huobi.pro; HttpOnly', 'X-Application-Context': 'dawn-broker-pro:default,prd:8080', 'X-Request-ID': 'fa722081d7207bec50c6141f2b24472a', 'Content-Encoding': 'gzip', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '4469e943aec7bf25-FRA'} {"status":"error","err-code":"api-not-support-temp-addr","err-msg":"api withdraw, not support temp address","data":null}
---------------------------------------------------------------------------
ExchangeError                             Traceback (most recent call last)
<ipython-input-14-502bd63ef4c9> in <module>()
----> 1 q.withdraw('ETH', 0.1, '0x77670b90c12943dfde69c73cc4b92c1b9fab7f48')

~/.virtualenvs/develop/lib/python3.6/site-packages/ccxt/huobipro.py in withdraw(self, code, amount, address, tag, params)
    700         if tag is not None:
    701             request['addr-tag'] = tag  # only for XRP?
--> 702         response = self.privatePostDwWithdrawApiCreate(self.extend(request, params))
    703         id = None
    704         if 'data' in response:

~/.virtualenvs/develop/lib/python3.6/site-packages/ccxt/base/exchange.py in request(self, path, api, method, params, headers, body)
    328 
    329     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):
--> 330         return self.fetch2(path, api, method, params, headers, body)
    331 
    332     @staticmethod

~/.virtualenvs/develop/lib/python3.6/site-packages/ccxt/base/exchange.py in fetch2(self, path, api, method, params, headers, body)
    325         self.lastRestRequestTimestamp = self.milliseconds()
    326         request = self.sign(path, api, method, params, headers, body)
--> 327         return self.fetch(request['url'], request['method'], request['headers'], request['body'])
    328 
    329     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):

~/.virtualenvs/develop/lib/python3.6/site-packages/ccxt/base/exchange.py in fetch(self, url, method, headers, body)
    405             self.raise_error(ExchangeError, url, method, e)
    406 
--> 407         self.handle_errors(response.status_code, response.reason, url, method, None, self.last_http_response)
    408         return self.handle_rest_response(self.last_http_response, url, method, headers, body)
    409 

~/.virtualenvs/develop/lib/python3.6/site-packages/ccxt/huobipro.py in handle_errors(self, httpCode, reason, url, method, headers, body)
    766                     if code in exceptions:
    767                         raise exceptions[code](feedback)
--> 768                     raise ExchangeError(feedback)

ExchangeError: huobipro {"status":"error","err-code":"api-not-support-temp-addr","err-msg":"api withdraw, not support temp address","data":null}
```

**Comment by kroitor** [comment]
@ray66rus can you check if you have "address whitelisting" enabled? https://support.hitbtc.com/hc/en-us/articles/360000800605-Whitelist-of-withdrawal-addresses

**Comment by kroitor** [comment]
@ray66rus with Huobi you should whitelist your withdrawal addresses here: https://www.huobi.com/withdraw_address/ . Let us know if it does not help.

**Comment by ray66rus** [comment]
@kroitor 
Thanks, that helped (though whitelisting more that one address on huobi is a pain in the ass - they want confirmation from both mail and 2fa).

Now I have another problem - it says that the amount is too small. Anyway, it's definetely not the problem of the library. Thanks for you help :)

```
Request: POST https://api.huobi.pro/v1/dw/withdraw/api/create?AccessKeyId=<some key>&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2018-08-07T13%3A31%3A11&address=0xad283e133dad8955d683d46272f0863195e256e5&amount=0.1&currency=eth&Signature=PKxosYql7UYT0xfW5OXLzYoccQ7uKsdTZxVuI%2B16q%2BM%3D {'Content-Type': 'application/json', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} {"address":"0xad283e133dad8955d683d46272f0863195e256e5","amount":0.1,"currency":"eth"}

Response: POST https://api.huobi.pro/v1/dw/withdraw/api/create?AccessKeyId=<some key>&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2018-08-07T13%3A31%3A11&address=0xad283e133dad8955d683d46272f0863195e256e5&amount=0.1&currency=eth&Signature=PKxosYql7UYT0xfW5OXLzYoccQ7uKsdTZxVuI%2B16q%2BM%3D 200 {'Date': 'Tue, 07 Aug 2018 13:31:11 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d92a61e74d6a39ec6dbc6a390de52e0351533648671; expires=Wed, 07-Aug-19 13:31:11 GMT; path=/; domain=.api.huobi.pro; HttpOnly', 'X-Application-Context': 'dawn-broker-pro:default,prd:8080', 'X-Request-ID': '5fd43a8291426860a3e8bc84e8da14cd', 'Content-Encoding': 'gzip', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '446a1a24abcb96be-FRA'} {"status":"error","err-code":"dw-withdraw-min-limit","err-msg":"The withdraw amount is less than the minimum limit.","data":null}
```

**Comment by valeriov382** [comment]
Hello,
  I have the same problem. I have whitelisted the addresses that I am trying to use. I still get this error

>>> import ccxt
>>> exchange = ccxt.huobi()
# I add key and secret
>>> exchange.check_required_credentials()  
True
>>> exchange.withdraw("XRP", 1, 'to_address', '123456789')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/.local/lib/python3.10/site-packages/ccxt/htx.py", line 5995, in withdraw
    response = self.spotPrivatePostV1DwWithdrawApiCreate(self.extend(request, params))
  File "/home/ec2-user/.local/lib/python3.10/site-packages/ccxt/base/types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
  File "/home/ec2-user/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3631, in request
    return self.fetch2(path, api, method, params, headers, body, config)
  File "/home/ec2-user/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3628, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ec2-user/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 673, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ec2-user/.local/lib/python3.10/site-packages/ccxt/htx.py", line 6628, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], code, feedback)
  File "/home/ec2-user/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3998, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.PermissionDenied: huobi {"status":"error","err-code":"api-not-support-temp-addr","err-msg":"API withdrawal does not support temporary addresses","data":null}

**Comment by ttodua** [comment]
late reply, but [alphaex-api.github.io/openapi/spot/v1/en#order-and-trade:~:text=Q1：-,Why the API returns error,-'api-not-support](https://alphaex-api.github.io/openapi/spot/v1/en/#order-and-trade:~:text=Q1%EF%BC%9A-,Why%20the%20API%20returns%20error,-%27api%2Dnot%2Dsupport) says that address should be added in whitelist and also note that uppercase/lowercase might also need to match.
let us know if anyone still has any issues
