### ISSUE TITLE
Add support for new Bitfinex API V2 ledger entries query

### ISSUE THREAD

**Issue by sebastianhaberey** [ccxt/ccxt#2719]
Bitfinex recently introduced [a new endpoint to query ledger entries](https://bitfinex.readme.io/v2/docs/changelog#section-1-new-restv2-ledger-entries-endpoint) in their V2 API. I understand that it will be a while until ledgers find their way into the unified API but it would be great if you could add this query to the .api property, so we can call the endpoint and parse the results ourselves.

- OS: macOS 10.13.4
- Programming Language version: Python 3.6.5
- CCXT version: 1.13.62
- Exchange: bitfinex2
- Method: auth/r/ledgers/{symbol}/hist

**Comment by kroitor** [comment]
Added in 1.13.63. Thx!
