### ISSUE TITLE
[Cryptopia] cryptopia order None not found in cached .orders

### ISSUE THREAD

**Issue by zemen77** [ccxt/ccxt#2722]
- OS: windows7 64bit
- Programming Language version: python 3.6.2
- CCXT version: 1.13.63
- Exchange: cryptopia
- Method: create_limit_buy_order

Hi all,

you can replicate the error setting up a price higher than the lowest sell order price at the market.
Actually the best sell price is `0.00040339`, so I'll go with `0.00041373`.
Here a snippet from my test code:
```python
from pprint import pprint

import ccxt

exchange = getattr(ccxt, 'cryptopia')()
exchange.timeout = 20000
exchange.enableRateLimit = True
exchange.userAgent = False
exchange.load_markets()
exchange.apiKey = '*****************'
exchange.secret = '******************'

symbol = 'XPM/BTC'
amount = 1.44959814
price = 0.00041373

result = exchange.create_limit_buy_order(symbol, amount, price)
pprint(result)
pprint(exchange.fetch_order(result['id'], symbol))
exchange.cancel_order(result['id'], symbol)
pprint(exchange.fetch_order(result['id'], symbol))
```

the first print (note the `'id': None` and the field `'FilledOrders'` where `57796080` it's the right order id):

```python
{'amount': 1.44959814,
 'cost': 0.0005997422384622,
 'datetime': '2018-05-01T20:33:53.454Z',
 'fee': None,
 'filled': None,
 'id': None,
 'info': {'Data': {'FilledOrders': [57796080], 'OrderId': None},
          'Error': None,
          'Success': True},
 'lastTradeTimestamp': None,
 'price': 0.00041373,
 'remaining': 1.44959814,
 'side': 'buy',
 'status': 'open',
 'symbol': 'XPM/BTC',
 'timestamp': 1525206833454,
 'type': 'limit'}
```

and the exception:
```
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    print(exchange.fetch_order(result['id'], symbol))
  File "venv\lib\site-packages\ccxt\cryptopia.py", line 532, in fetch_order
    raise OrderNotCached(self.id + ' order ' + id + ' not found in cached .orders, fetchOrder requires .orders(de)serialization implemented for self method to work properly')
ccxt.base.errors.OrderNotCached: cryptopia order None not found in cached .orders, fetchOrder requires .orders(de)serialization implemented for self method to work properly
```

Everything works if I go with a price higher than the best sell price.
Any idea on how is it?

Thanks in advance :)

**Comment by kroitor** [comment]
Hi!

This is a documented behaviour: https://github.com/ccxt/ccxt/wiki/Manual#querying-orders

1. You're confusing a *market order trade id* with an *order id*:
- https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades

2. When you place the order for a price worse than market, it gets filled immediately, and you see the trades within that order. You won't find that filled order in the list of open orders, as it is not open anymore.

Hope this answers your question.

**Comment by zemen77** [comment]
as an update I cannot fetch any order by id from my trade history list on the website

**Comment by zemen77** [comment]
yep, thanks a lot :)
