### ISSUE TITLE
New Exchange: octaex

### ISSUE THREAD

**Issue by crackfoo** [ccxt/ccxt#2723]
Can you add octaex exchange?

https://octaex.com/index/api

Thanks!

**Comment by kankando** [comment]
thx @kroitor

**Comment by kankando** [comment]
Here the API (originally in Chinese)

GET Get All Market Quotes (updated every 10 seconds)
Https://octaex.com/api/trade/all/

GET get the specified market (updated every 10 seconds)
Https://octaex.com/api/trade/ticker?market=btc_cny

GET gets the depth of the total market (updated every 10 seconds)
Https://octaex.com/api/trade/depth?market=btc_cny

GET Gets Total Station History (Updated every 10 seconds)
Https://octaex.com/api/trade/trades?market=btc_cny


---
POST gets his own account balance
---
Request address :https://octaex.com/api/trade/balance
Calling method :POST
Secret_key : The 32-bit private key provided by the platform (without passing parameters)

Incoming parameters:
---
Key, the 32-bit public key provided by the platform
Nonce, timestamp, in seconds
Signature, using md5 (key & user ID & nonce & secret_key), order can not be reversed

Returns: JSON format
---
Error: {"err":'Error Description'}
Success: {"succ":'balance in JSON format, including all currencies'}


---
POST execution transaction pending order operation
---
Request address: https://octaex.com/api/trade/submit_order
Calling method :POST
Secret_key : The 32-bit private key provided by the platform (without passing parameters)

Incoming parameters:
---
Key, the 32-bit public key provided by the platform
Nonce, timestamp, in seconds
Signature, using md5 (key & user ID & nonce & secret_key), order can not be reversed
Type, 1 is a buy pending order, 2 is a sell pending order and cannot be empty
Market
Price, purchase price
Amount, the number of purchases

Returns: JSON format
---
Error: {"err":'Error Description'}
Success: {"succ":'Order ID'}

 
---
POST to perform transaction withdrawal operation
---
Request address: https://octaex.com/api/trade/cancel_order
Calling method :POST
Secret_key : The 32-bit private key provided by the platform (without passing parameters)

Incoming parameters:
---
Key, the 32-bit public key provided by the platform
Nonce, timestamp, in seconds
Signature, using md5 (key & user ID & nonce & secret_key), order can not be reversed
Order_id, order ID

Returns: JSON format
---
Error: {"err":'Error Description'}
Success: {"succ":'ok'}

 
---
POST gets its own pending record
---
Request address: https://octaex.com/api/trade/list_order
Calling method :POST
Secret_key : The 32-bit private key provided by the platform (without passing parameters)

Incoming parameters:
---
Key, the 32-bit public key provided by the platform
Nonce, timestamp, in seconds
Signature, using md5 (key & user ID & nonce & secret_key), order can not be reversed
Market, trading market (returns to the entire market if not filled)
Page, page turn, 0 is the first page, 30 pages per page, if not, the default is the first page Sort ID from big to small

Returns: JSON format
---
Error: {"err":'Error Description'}
Success: {"succ":'record in JSON format'}

Explanation: deal has volume status 0 in transaction 1 has completed 2 has been revoked

 
---
POST Get Your Transaction History
---
Request address: https://octaex.com/api/trade/list_trade
Calling method :POST
Secret_key : The 32-bit private key provided by the platform (without passing parameters)

Incoming parameters:
---
Key, the 32-bit public key provided by the platform
Nonce, timestamp, in seconds
Signature, using md5 (key & user ID & nonce & secret_key), order can not be reversed
Market, trading market (returns to the entire market if not filled)
Page, page turn, 0 is the first page, 30 pages per page, if not, the default is the first page Sort ID from big to small

Returns: JSON format
---
Error: {"err":'Error Description'}
Success: {"succ":'record in JSON format'}

**Comment by jpfleury** [comment]
This issue should be closed. This exchange no longer exists.
