### ISSUE TITLE
zaif doesn't return its symbols

### ISSUE THREAD

**Issue by jeongmincha** [ccxt/ccxt#2724]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: MacOS High Sierra (10.13.4)
- Programming Language version: Python 3.6.4
- CCXT version: 1.13.64
- Exchange: zaif
- Method: `ccxt.zaif().symbols` doesn't return anything. I know I can fetch ohlcv using 'BTC/JPY', but I think it would be better to get all available symbols of the exchange.

**Comment by kroitor** [comment]
```Python
zaif = ccxt.zaif()
zaif.load_markets() # add this line first before accessing symbols
print(zaif.symbols)
```

Documented here: https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

Let us know if this does not help.

**Comment by jeongmincha** [comment]
@kroitor Thank you for your help, but why should I call the function when I am using this exchange?
Other exchanges didn't require me to do this.
