### ISSUE TITLE
[question] suddenly having problem with nonce and timestamp

### ISSUE THREAD

**Issue by ardialamwijaya** [ccxt/ccxt#2725]
- OS: Win10
- Programming Language version: PHP7
- CCXT version: 1.12.7
- Exchange: binance
- Method: all

hi Igor, up until this afternoon i didnt find any problem using ccxt to my code, but for some reason, after i restart my laptop, and rerun again my code, i have problem with the time syncronization between my laptop and the binance server. i tried ur suggestion to update my internet time (from https://github.com/ccxt/ccxt/issues/936) done that and still not working yet

i also already tried to make a custom nonce like ur suggestion (from https://github.com/ccxt/ccxt/wiki/Manual#overriding-the-nonce)

but still can not get it running, am also attaching my codes

[ccxt_tm.zip](https://github.com/ccxt/ccxt/files/1966392/ccxt_tm.zip)

**Comment by ardialamwijaya** [comment]
sorry.. i accidentally click the submit button.. my question: is it something wrong with the binance server? did i still miss something to fix it?

**Comment by kroitor** [comment]
Hi, @ardialamwijaya !

This is a known issue with Binance, you should make sure that your time sync is working. Unfortunately, just enabling that checkbox in Windows is not enough, more about it here: #850.

Let me know if this does not solve your issue. Thx!

**Comment by ardialamwijaya** [comment]
aha!! thx for ur fast response!! appreciate it a lot!! :) 👍

**Comment by kroitor** [comment]
@ardabeyazoglu we also have a quick workaround for this issue in ccxt, you can enable it like so:

```PHP
$exchange->options['adjustForTimeDifference'] = true; // auto-adjust the time difference
$exchange->fetch_balance (...
```

After setting `$exchange->options['adjustForTimeDifference'] = true`, the issue should be gone as well. However, I would still recommend to set up proper time sync – this will help you avoid problems with other exchanges as well.

**Comment by ardabeyazoglu** [comment]
I think you typed my name instead of @ardialamwijaya :)

**Comment by kroitor** [comment]
@ardabeyazoglu terribly sorry, didn't mean to wake you up ))

**Comment by ardialamwijaya** [comment]
hi Igor@kroitor,  i tried ur suggestion 

`switch(strtolower($this->exchangeName)){
            case "binance":
                $this->exchange = new \ccxt\myBinance(array(
                    "apiKey" => $this->apiKey,
                    "secret" => $this->apiSecret
                ));
                $this->exchange->options['adjustForTimeDifference'] = true; // auto-adjust the time difference
                break;
        }
`
`class myBinance extends binance
{
    public function __construct($options=array()){
        if(file_exists('nonce.dat')){$noncearray=file('nonce.dat',FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES);$nonce=$noncearray[0];$nonce++;}else{$nonce=1;}  // Assume we have new keys if nonce.dat does not exist.
        if(file_exists('nonce.dat')){if(file_exists('nonce.old')){unlink('nonce.old');} rename('nonce.dat','nonce.old');}
        file_put_contents('nonce.dat',$nonce,LOCK_EX);  // File contains latest used nonce.
        parent::__construct(array_merge(array('i'=>$nonce),$options));
    }
    public function nonce(){
        if(file_exists('nonce.dat')){$noncearray=file('nonce.dat',FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES);$nonce=$noncearray[0];$nonce++;}else{$nonce=1;}  // Assume we have new keys if nonce.dat does not exist.
        if(file_exists('nonce.dat')){if(file_exists('nonce.old')){unlink('nonce.old');} rename('nonce.dat','nonce.old');}
        file_put_contents('nonce.dat',$nonce,LOCK_EX);  // File contains latest used nonce.
        $this->i=$nonce;
        return $this->i;
    }
}
`


just now i also downloaded the latest ccxt

and also restarted my laptop, but unfortunatelly im still not going anywhere. the problem still persists. any help will be appreciated

**Comment by ardialamwijaya** [comment]
hi Igor@kroitor, i tried ur suggestion

`switch(strtolower($this->exchangeName)){ `
`case "binance": `
`$this->exchange = new \ccxt\myBinance(`
	`array( "apiKey" => $this->apiKey, "secret" => $this->apiSecret ));` 
	`$this->exchange->options['adjustForTimeDifference'] = true; 	// auto-adjust the time difference `
`break; }`


`class myBinance extends binance`
`{`
   `public function __construct($options=array()){`
        `if(file_exists('nonce.dat')){$noncearray=file('nonce.dat',FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES);$nonce=$noncearray[0];$nonce++;}else{$nonce=1;}  // Assume we have new keys if nonce.dat does not exist.`
        `if(file_exists('nonce.dat')){if(file_exists('nonce.old')){unlink('nonce.old');} rename('nonce.dat','nonce.old');}`
        `file_put_contents('nonce.dat',$nonce,LOCK_EX);  // File contains latest used nonce.`
        `parent::__construct(array_merge(array('i'=>$nonce),$options));`
    `}`
    `public function nonce(){`
        `if(file_exists('nonce.dat')){$noncearray=file('nonce.dat',FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES);$nonce=$noncearray[0];$nonce++;}else{$nonce=1;}  // Assume we have new keys if nonce.dat does not exist.`
        `if(file_exists('nonce.dat')){if(file_exists('nonce.old')){unlink('nonce.old');} rename('nonce.dat','nonce.old');}`
        `file_put_contents('nonce.dat',$nonce,LOCK_EX);  // File contains latest used nonce.`
        `$this->i=$nonce;`
        `return $this->i;`
    `}`
`}`


just now i also downloaded the latest ccxt

and also restarted my laptop, but unfortunatelly im still not going anywhere. the problem still persists. any help will be appreciated

**Comment by kroitor** [comment]
@ardialamwijaya let's first rule out a time-sync issue then. Can you ensure that you have your system clock up to date and that the problem does not reappear with properly synced clocks? Also, do you have a spare account or a different keypair to test against? You can also try creating a new keypair to see if it resolves the issue. If a new key does not work either – this is most likely a timesync issue. Not sure why adjustment for time difference didn't really work in PHP, will debug it a little later. In the meantime, you can try excluding the above possible causes and see if it makes a difference.

**Comment by ardialamwijaya** [comment]
hi Igor @kroitor , thx for the response.. yeap, already tried with the new api keypair,sorry forgot to mention about it earlier, but unfortunatelly its still not working. 

And about the time between binance and my laptop, since i sync my internet time with time.metrologi.lipi.go.id (im from indonesia, and that web its a gov site that also provide time sync), im pretty sure that my laptop time and binance server was alligned, down to the seconds. 

I saw it from my last login time, compare it with my laptop time
`Last login Time: 2018-05-02 16:58:38` -> similar with the time in my laptop (not really sure with the milisecs, but for the seconds, i think its already correct as well)

**Comment by kroitor** [comment]
@ardialamwijaya ok, then please do the following:

```PHP
$exchange->verbose = true;
print_r ($exchange->milliseconds ());
$response = $exchange->public_get_time ();
print_r ($response['serverTime']);
print_r ($exchange->milliseconds ());

# your private request here...
print_r ($exchange->public_get_time ());
```

Can you copy-paste the full verbose output here? (without your keys)

**Comment by ardialamwijaya** [comment]
Hi Igor @kroitor , sorry for the delay replying ur earlier message..
Here's my verbose output

Time before sending the request: 1525265361472
Request:
Array
(
    [0] => GET
    [1] => https://api.binance.com/api/v1/time
    [2] => Array
        (
        )

    [3] =>
)

Response:
Array
(
    [0] => GET
    [1] => https://api.binance.com/api/v1/time
    [2] => 200
    [3] =>
    [4] => Array
        (
            [content-type] => Array
                (
                    [0] => application/json
                )

            [transfer-encoding] => Array
                (
                    [0] => chunked
                )

            [connection] => Array
                (
                    [0] => keep-alive
                )

            [date] => Array
                (
                    [0] => Wed, 02 May 2018 12:49:25 GMT
                )

            [server] => Array
                (
                    [0] => nginx
                )

            [vary] => Array
                (
                    [0] => Accept-Encoding
                )

            [strict-transport-security] => Array
                (
                    [0] => max-age=31536000; includeSubdomains
                )

            [x-frame-options] => Array
                (
                    [0] => SAMEORIGIN
                )

            [x-xss-protection] => Array
                (
                    [0] => 1; mode=block
                )

            [x-content-type-options] => Array
                (
                    [0] => nosniff
                )

            [content-security-policy] => Array
                (
                    [0] => default-src 'self'
                )

            [x-content-security-policy] => Array
                (
                    [0] => default-src 'self'
                )

            [x-webkit-csp] => Array
                (
                    [0] => default-src 'self'
                )

            [cache-control] => Array
                (
                    [0] => no-cache, no-store, must-revalidate
                )

            [pragma] => Array
                (
                    [0] => no-cache
                )

            [expires] => Array
                (
                    [0] => 0
                )

            [content-encoding] => Array
                (
                    [0] => gzip
                )

            [x-cache] => Array
                (
                    [0] => Miss from cloudfront
                )

            [via] => Array
                (
                    [0] => 1.1 6877899d48ba844a34ea4378ce336f06.cloudfront.net (
CloudFront)
                )

            [x-amz-cf-id] => Array
                (
                    [0] => GBzNBQZ7iZmWn0nPceppwhbBTrK_35m02QrPR4z_Mzvv7mpVAPQ1Wa
g==
                )

        )

    [5] => {"serverTime":1525265365024}
)
Server time: 1525265365024Time after sending the request: 1525265367014
Request:
Array
(
    [0] => GET
    [1] => https://api.binance.com/api/v1/time
    [2] => Array
        (
        )

    [3] =>
)

Response:
Array
(
    [0] => GET
    [1] => https://api.binance.com/api/v1/time
    [2] => 200
    [3] =>
    [4] => Array
        (
            [content-type] => Array
                (
                    [0] => application/json
                )

            [transfer-encoding] => Array
                (
                    [0] => chunked
                )

            [connection] => Array
                (
                    [0] => keep-alive
                )

            [date] => Array
                (
                    [0] => Wed, 02 May 2018 12:49:26 GMT
                )

            [server] => Array
                (
                    [0] => nginx
                )

            [vary] => Array
                (
                    [0] => Accept-Encoding
                )

            [strict-transport-security] => Array
                (
                    [0] => max-age=31536000; includeSubdomains
                )

            [x-frame-options] => Array
                (
                    [0] => SAMEORIGIN
                )

            [x-xss-protection] => Array
                (
                    [0] => 1; mode=block
                )

            [x-content-type-options] => Array
                (
                    [0] => nosniff
                )

            [content-security-policy] => Array
                (
                    [0] => default-src 'self'
                )

            [x-content-security-policy] => Array
                (
                    [0] => default-src 'self'
                )

            [x-webkit-csp] => Array
                (
                    [0] => default-src 'self'
                )

            [cache-control] => Array
                (
                    [0] => no-cache, no-store, must-revalidate
                )

            [pragma] => Array
                (
                    [0] => no-cache
                )

            [expires] => Array
                (
                    [0] => 0
                )

            [content-encoding] => Array
                (
                    [0] => gzip
                )

            [x-cache] => Array
                (
                    [0] => Miss from cloudfront
                )

            [via] => Array
                (
                    [0] => 1.1 6877899d48ba844a34ea4378ce336f06.cloudfront.net (
CloudFront)
                )

            [x-amz-cf-id] => Array
                (
                    [0] => xJefFOvGxlgHi47G7Mow4O1QgoMslzEJZ3KGo3V4wMAPg4LzTZ4gEa
w==
                )

        )

    [5] => {"serverTime":1525265366034}
)
Array
(
    [serverTime] => 1525265366034
)


I do a simple checked, the diff between my laptop time and the server time is about 4.562ms  (between time before the sending and the server time)
Maybe i was wrong? Thx!! :) 👍

**Comment by ardialamwijaya** [comment]
hi Igor @kroitor , just want to give a quick update, now i change my internet time to synchronize with pool.ntp.org and the diff down to less than 1000 mili secs (around 800 to 900)

here is the result 

Time before sending the request: 1525319450745
Request:
Array
(
    [0] => GET
    [1] => https://api.binance.com/api/v1/time
    [2] => Array
        (
        )

    [3] =>
)

Response:
Array
(
    [0] => GET
    [1] => https://api.binance.com/api/v1/time
    [2] => 200
    [3] =>
    [4] => Array
        (
            [content-type] => Array
                (
                    [0] => application/json
                )

            [transfer-encoding] => Array
                (
                    [0] => chunked
                )

            [connection] => Array
                (
                    [0] => keep-alive
                )

            [date] => Array
                (
                    [0] => Thu, 03 May 2018 03:50:49 GMT
                )

            [server] => Array
                (
                    [0] => nginx
                )

            [vary] => Array
                (
                    [0] => Accept-Encoding
                )

            [strict-transport-security] => Array
                (
                    [0] => max-age=31536000; includeSubdomains
                )

            [x-frame-options] => Array
                (
                    [0] => SAMEORIGIN
                )

            [x-xss-protection] => Array
                (
                    [0] => 1; mode=block
                )

            [x-content-type-options] => Array
                (
                    [0] => nosniff
                )

            [content-security-policy] => Array
                (
                    [0] => default-src 'self'
                )

            [x-content-security-policy] => Array
                (
                    [0] => default-src 'self'
                )

            [x-webkit-csp] => Array
                (
                    [0] => default-src 'self'
                )

            [cache-control] => Array
                (
                    [0] => no-cache, no-store, must-revalidate
                )

            [pragma] => Array
                (
                    [0] => no-cache
                )

            [expires] => Array
                (
                    [0] => 0
                )

            [content-encoding] => Array
                (
                    [0] => gzip
                )

            [x-cache] => Array
                (
                    [0] => Miss from cloudfront
                )

            [via] => Array
                (
                    [0] => 1.1 fb176da9df72832dd488674f28c0a880.cloudfront.net (CloudFront)
                )

            [x-amz-cf-id] => Array
                (
                    [0] => v60rlARlNe8WPsurri7bxq5FV6DWwVjLsBzezo4Uj2dxMrwOzxBQmw==
                )

        )

    [5] => {"serverTime":1525319449697}
)
Server time: 1525319449697Time after sending the request: 1525319451198
Request:
Array
(
    [0] => GET
    [1] => https://api.binance.com/api/v1/time
    [2] => Array
        (
        )

    [3] =>
)

Response:
Array
(
    [0] => GET
    [1] => https://api.binance.com/api/v1/time
    [2] => 200
    [3] =>
    [4] => Array
        (
            [content-type] => Array
                (
                    [0] => application/json
                )

            [transfer-encoding] => Array
                (
                    [0] => chunked
                )

            [connection] => Array
                (
                    [0] => keep-alive
                )

            [date] => Array
                (
                    [0] => Thu, 03 May 2018 03:50:49 GMT
                )

            [server] => Array
                (
                    [0] => nginx
                )

            [vary] => Array
                (
                    [0] => Accept-Encoding
                )

            [strict-transport-security] => Array
                (
                    [0] => max-age=31536000; includeSubdomains
                )

            [x-frame-options] => Array
                (
                    [0] => SAMEORIGIN
                )

            [x-xss-protection] => Array
                (
                    [0] => 1; mode=block
                )

            [x-content-type-options] => Array
                (
                    [0] => nosniff
                )

            [content-security-policy] => Array
                (
                    [0] => default-src 'self'
                )

            [x-content-security-policy] => Array
                (
                    [0] => default-src 'self'
                )

            [x-webkit-csp] => Array
                (
                    [0] => default-src 'self'
                )

            [cache-control] => Array
                (
                    [0] => no-cache, no-store, must-revalidate
                )

            [pragma] => Array
                (
                    [0] => no-cache
                )

            [expires] => Array
                (
                    [0] => 0
                )

            [content-encoding] => Array
                (
                    [0] => gzip
                )

            [x-cache] => Array
                (
                    [0] => Miss from cloudfront
                )

            [via] => Array
                (
                    [0] => 1.1 fb176da9df72832dd488674f28c0a880.cloudfront.net (CloudFront)
                )

            [x-amz-cf-id] => Array
                (
                    [0] => JNt_4Q-BJo54d5GRj3BBqIJLRJ9hXRmglpNlpbE_zu2Tx6YCAUMWVw==
                )

        )

    [5] => {"serverTime":1525319449830}
)
Array
(
    [serverTime] => 1525319449830
)

**Comment by ardialamwijaya** [comment]
hi Igor @kroitor , i think i found the problem.. for some reason, its because i implement the unique nonce

`namespace ccxt;`
`require_once "php/binance.php";`
`class myBinance extends binance`
`{`
`    public function __construct($options=array()){`
`        if(file_exists('nonce.dat')){$noncearray=file('nonce.dat',FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES);$nonce=$noncearray[0];$nonce++;}else{$nonce=1;}  // Assume we have new keys if nonce.dat does not exist.`
`        if(file_exists('nonce.dat')){if(file_exists('nonce.old')){unlink('nonce.old');} rename('nonce.dat','nonce.old');}`
`        file_put_contents('nonce.dat',$nonce,LOCK_EX);  // File contains latest used nonce.`
`        parent::__construct(array_merge(array('i'=>$nonce),$options));`
`    }`
`    public function nonce(){`
`        if(file_exists('nonce.dat')){$noncearray=file('nonce.dat',FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES);$nonce=$noncearray[0];$nonce++;}else{$nonce=1;}  // Assume we have new keys if nonce.dat does not exist.`
`        if(file_exists('nonce.dat')){if(file_exists('nonce.old')){unlink('nonce.old');} rename('nonce.dat','nonce.old');}`
`        file_put_contents('nonce.dat',$nonce,LOCK_EX);  // File contains latest used nonce.`
`        $this->i=$nonce;`
`        return $this->i;`
`    }`
`}`

thats the code for myBinance.php

and previously, i have the error because i call ccxt\myBinance instead of ccxt\binance

once i changed back to ccxt\binance, the error is gone :) 👍

**Comment by kroitor** [comment]
@ardialamwijaya ok, I see, thanks for reporting back!

**Comment by ardialamwijaya** [comment]
your welcome Igor @kroitor , i hope u will follow up this issue and give us a solution how to implement custom nonce since the current custom nonce still have problem :)

**Comment by ekmg** [comment]
hey only eyes man... kroitor 
i need help on gemini rest private api parameters with python code given in 
https://docs.gemini.com/rest-api/
im getting error on nonce 
Result:”error”, reason:”InvalidNonce”, message:”Nonce has not increased since your last call to the Gemini API”
and how i can create nonce and encode payload 
plzzzz help me with straight way code

**Comment by kroitor** [comment]
@ekmg hey ) why don't you want to use the CCXT Unified API? ;) https://github.com/ccxt/ccxt/wiki/Manual
