### ISSUE TITLE
Indodax: Api endpoint change & new pair

### ISSUE THREAD

**Issue by Xzavaz** [ccxt/ccxt#2729]
Api endpoint change to indodax.com/tapi and indodax.com/api
New pair ADA/IDR and BCD/IDR

**Comment by kroitor** [comment]
> Api endpoint change to indodax.com/tapi and indodax.com/api

Thanks, we know this.

- https://github.com/ccxt/ccxt/issues/2244
- https://github.com/ccxt/ccxt/pull/2267

Please update your ccxt to the most recent version.
