### ISSUE TITLE
Support for directional rounding in decimalToPrecision

### ISSUE THREAD

**Issue by mkutny** [ccxt/ccxt#2733]
- OS: any
- Programming Language version: any
- CCXT version: 1.13.68
- Exchange: any
- Method: `decimalToPrecision`

At the moment ccxt provides only "to the nearest neighbor" rounding mode. Sometimes you need to impose the direction, namely round strictly up or down.

Rounding down can be technically achieved by truncating like we do in `amountToPrecision`. Rounding up is a little bit more tricky. Would love if ccxt handles that natively.

**Comment by frosty00** [comment]
@kroitor any updates on transpilled tests?

**Comment by kroitor** [comment]
@frosty00 Sorry for the delay again, I'll upload the merged version asap, the last few edits...

**Comment by ttodua** [comment]
I think this current issue can be closed as duplicate, as there [as another issue](https://github.com/ccxt/ccxt/issues/6645) which has more discussions and insights. Any further discussion should be continued there.
