### ISSUE TITLE
 curlopt_interface set IP

### ISSUE THREAD

**Issue by Showgofar** [ccxt/ccxt#2737]
- OS: Debian
- Programming Language version: PHP
- CCXT version:  $version = '1.12.78';
- Exchange: All
- Method: curlopt_interface 

Hi Could you please help with curl settings
How to correctly set curlopt_interface IP using function __construct()  ?
Thank you in advance

**Comment by kroitor** [comment]
Hi!

Use $this->curlopt_interface for that, as described here: 

https://github.com/ccxt/ccxt/issues/824

```PHP
$id = 'bittrex';
$exchange = '\\ccxt\\' . $id;

// this way
$exchange = new $exchange (array (
    'curlopt_interface' => YOUR_CURLOPT_INTERFACE_SETTING, // as documented @ php.net/curl
));

// or this way
$exchange->curlopt_interface = YOUR_CURLOPT_INTERFACE_SETTING;
```

Hope this helps.
