### ISSUE TITLE
tests - coverage for createLimit*, createMarket*, withdraw, and deposit methods

### ISSUE THREAD

**Issue by skeller88** [ccxt/ccxt#2739]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: all
- Programming Language version: all
- CCXT version: 1.13.74
- Exchange: all
- Method: [test coverage of createLimit* and createMarket* orders](https://github.com/ccxt/ccxt/blob/master/js/test/test.js#L230)

createLimit* and createMarket* have tests that are commented out. I searched the codebase for both of those methods and found no uncommented tests. How are those methods tested currently?  

Similarly, deposit and withdraw don't have test coverage. 

I recognize that these methods require funds on exchanges in order to execute, which is probably why they aren't being tested. [I followed up on a thread related to exchange mocks](https://github.com/ccxt/ccxt/issues/1677) to see what's being worked on in that vein. But if a mock existed for every exchange, then the corresponding Exchange subclass could run tests against the mock. The mocks themselves could be tested less frequently, perhaps every time a new exchange version was released.

[Kyber Network has done some work](https://github.com/KyberNetwork/exchange-simulator/blob/master/simulator/exchange/binance.py) on simulating exchanges. Perhaps they'd be willing to contribute their code, or their library could be used by ccxt. 

Thoughts?

**Comment by ttodua** [comment]
They are being work on currently, and some progress has been already made, but it's a bit more complex then you might think on first look.  This topic will be left open till that happens.
Beside this, please subscribe to CCXT announcement channel (discord or telegram) for important updates.
