### ISSUE TITLE
New Bittrex Websocket Authentication Node.js Example

### ISSUE THREAD

**Issue by flavioespinoza** [ccxt/ccxt#2742]
Hi everyone!  I recently wrote this node.js  app to connect with the new Bittrex Websocket API.

Perhaps there is a way to integrate it into ccxt for the Bittrex module.  Thoughts?

https://gist.github.com/flavioespinoza/a69dacfac67739c26b30dab4bbddaf6b

**Comment by brucetus** [comment]
This is great! I'm all for it :)

**Comment by kroitor** [comment]
I'd move this discussion to #56. Thx!
