### ISSUE TITLE
ccxt fails on some exchanges when used from server

### ISSUE THREAD

**Issue by laurentiu1981** [ccxt/ccxt#2743]
- OS: Win 10/debian
- Programming Language version: javascript
- CCXT version: 1.13.36
- Exchange: binance
- Method: fetchBalance

It seems that when I try to do private calls to binance (using api key/secret), when using ccxt from server, it fails with this error:
"Signature for this request is not valid.", error code being -1022

**Doing similar calls to kraken works fine.**
Also, if I do the same call from client side it works fine via proxy server (cors-anywhere).

Initially I thought that my node server has some issues... so I tried to use the same proxy even when I used ccxt from my custom server, but same error was returned.

config for ccxt:
`{
      options: {
        adjustForTimeDifference: true,
      },
      proxy: "http://localhost:7799/"
 }`

Any ideas what I'm doing wrong?

**Comment by kroitor** [comment]
This is most likely due to one of these reasons:
- #850 
- #936 

Let us know if that does not help you.

**Comment by laurentiu1981** [comment]
It seems that a wrong secret can generate those errors :(
Sorry for this.
