### ISSUE TITLE
GetBTC return ticker with NaN ask/bid instead of null/undefined

### ISSUE THREAD

**Issue by StErMi** [ccxt/ccxt#2745]
- OS: Windows 10
- Programming Language version: Node v9.6.1
- CCXT version: 1.13.76
- Exchange: getbtc
- Method: fetchTicker

As mentioned in the title, this is a problem because I'm saving raw data from CCXT to Mongo and NaN is not supported. I would expect inside those values (and in other Number values) in the worst case a null/undefined.

**Comment by StErMi** [comment]
The same thing is happening also for virwox exchange. The request should not have failed but I get inconsistent results.

Is it a bug or should I handle NaN with a different meaning?

**Comment by kroitor** [comment]
@StErMi which symbol is it?

**Comment by StErMi** [comment]
Sorry, next time I will also take note of the symbol ;)
