### ISSUE TITLE
Unable to load_markets() :  'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by HornKild** [ccxt/ccxt#2747]
Hello,

I'm unable to replicate this example of load_markets() from the Manual page, am'I missing something ?

```
In [201]: kraken = ccxt.kraken ()
     ...: kraken.load_markets ()
     ...: kraken.markets['BTC/USD']
     ...: 
__main__:2: RuntimeWarning: coroutine 'Exchange.load_markets' was never awaited
Traceback (most recent call last):

  File "<ipython-input-201-bdbc5acb12e2>", line 3, in <module>
    kraken.markets['BTC/USD']

TypeError: 'NoneType' object is not subscriptable
In [202]:
```

Thank you,

- OS: Ubuntu 16.04
- Programming Language version: Python 3.6.4 Anaconda
- CCXT version: 1.13.58
- Exchange: All
- Method: load_markets()

EDIT: change the title with the error instead of warning

**Comment by HornKild** [comment]
I restarted my IDE and problem is solved. Awesome !

**Comment by kroitor** [comment]
@HornKild thx for reporting back!
