### ISSUE TITLE
[bitfinex2] fetch_my_trades() response empty

### ISSUE THREAD

**Issue by sebastianhaberey** [ccxt/ccxt#2758]
Hi, 

first off I apologize for asking this even though the error probably does not lie with ccxt. But I don't really know where else to ask. So I'm using ccxt / bitfinex2 / fetch_my_trades() to poll my trades. The REST call returns OK (200) with an empty response, even though there should be trades:

```Request: POST https://api.bitfinex.com/v2/auth/r/trades/tETHUSD/hist {'bfx-nonce': '1525518366395', 'bfx-apikey': 'removed', 'bfx-signature': 'removed', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} {"limit":25,"end":1525518366}```

```Response: POST https://api.bitfinex.com/v2/auth/r/trades/tETHUSD/hist 200 {'Date': 'Sat, 05 May 2018 11:06:06 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=removed; expires=Sun, 05-May-19 11:06:06 GMT; path=/; domain=.bitfinex.com; HttpOnly', 'Vary': 'Accept-Encoding', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'X-BFX-APIKEY,X-BFX-PAYLOAD,X-BFX-SIGNATURE,Content-Type,X-CSRF-Token,bfx-token,bfx-signature,bfx-apikey,bfx-nonce,bfx-flags', 'Content-Encoding': 'gzip', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '4162bc5e0a2b2d8f-TXL'} []```

The exact same code works fine with bitfinex (API V1) and kraken. Any help would be appreciated.

- OS: macOS 10.13.4
- Programming Language version: Python 3.6.5
- CCXT version: 1.13.62
- Exchange: bitfinex2
- Method: auth/r/trades/tETHUSD/hist

**Comment by kroitor** [comment]
They will require a `since` argument for fetchMyTrades, as described here: https://github.com/ccxt/ccxt/wiki/Manual#recent-trades. Let us know if it does not help.
