### ISSUE TITLE
[Gateio]The exchange【gate.io】has change the url into 【gateio.io】

### ISSUE THREAD

**Issue by zrxpower** [ccxt/ccxt#2759]
The exchange【gate.io】has change the url into 【gateio.io】
so if you need to use the api for gateio.io you can edit the file :【/node_modules/ccxt/js/gateio.js】and replace the【gate.io】 into 【gateio.io】

**Comment by kroitor** [comment]
Their API docs still point to gate.io and it does work, so we will update according to their docs. Thx for the notice, really appreciate your involvement!
