### ISSUE TITLE
CEX can only return historical candles for a certain date

### ISSUE THREAD

**Issue by jorijnsmit** [ccxt/ccxt#2760]
```
>>> import ccxt
>>> x = ccxt.cex()
>>> x.loadMarkets()
>>> x.fetch_ohlcv('BCH/BTC', '1m', x.parse8601('2000-01-01 00:00:00'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jorijnsmit/anaconda3/lib/python3.6/site-packages/ccxt/cex.py", line 216, in fetch_ohlcv
    response = self.publicGetOhlcvHdYyyymmddPair(self.extend(request, params))
  File "/Users/jorijnsmit/anaconda3/lib/python3.6/site-packages/ccxt/cex.py", line 473, in request
    raise ExchangeError(self.id + ' returned ' + self.json(response))
ccxt.base.errors.ExchangeError: cex returned null
```

With all other exchanges my experience has been that `fetch_ohlcv()` can be asked to return candles say from the year 2000 and it will automatically find the first available candle.
```
>>> y = ccxt.binance()
>>> y.loadMarkets()
>>> y.fetch_ohlcv('BCH/BTC', '1m', y.parse8601('2000-01-01 00:00:00'))
[[1501657200000, 0.7, 0.7, 0.082, 0.082, 0.2], .........
>>> y.iso8601(1501657200000)
'2017-08-02T07:00:00.000Z'
```
Returns the requested data (albeit starting from a more realistic starting date).

- OS: macOS `10.13.4`
- Programming Language version: `Python 3.6.4`
- CCXT version: `1.13.51`
- Exchange: `cex`
- Method: `fetch_ohlcv()`

**Comment by whchen8** [comment]
Native `CEX` api only supports historical 1m candles for a certain date in format `YYYYMMDD`. In your case, `ccxt` will fetch the ohlcv for 2000-01-01 only, rather than all the ohlcv **since** 2000-01-01, which might return empty data (it raises `ccxt.base.errors.ExchangeError` as you have noticed).

**Comment by kroitor** [comment]
> shouldn't the function take this into consideration?

I think, you're missing the fact that this library is a public open source work, and it's under development ) I totally agree with you, this is one of over 9000 considerations that this library should take into account. Your pull-requests are welcome ) Just make sure to read this first: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md )
