### ISSUE TITLE
How can I store price series data into MongoDB ?

### ISSUE THREAD

**Issue by HornKild** [ccxt/ccxt#2762]
Hello,

I would like to save price series of crypto from multiple exchanges into a MongoDB database but I can't find any example. This is the list of the exchanges I would like to download and store the data: 

```
ex =    ["binance",
        "bitfinex",
        "bittrex",
        "hitbtc",
        "kraken",
        "kucoin",
        "poloniex",
        "gateio"]
```
These exchanges have +900 symbols with BTC as a quote currency. I can use `fetch_ohlcv (symbol, '1d')` to retrieve the data but it gives me lists inside list, like this :

```
[[1478131200000, 950.0, 1099.98, 179.0, 240.03, 244.57775612],
 [1478736000000, 240.03, 265.89, 89.24, 93.55, 155.50246024],
 [1479340800000, 93.57, 99.72, 55.0, 77.53, 624.65850454]]
```

The problem is that Mongodb wants an instance of dict, so how could I transform this nested lists into a proper dictionary ? Another question is how to design the database to store data from multiple exchanges ?

Any help would be greatly appreciate,

Thanks!

**Comment by mkutny** [comment]
> Another question is how to design the database to store data from multiple exchanges ?

The database table structure for this particular case is pretty straightforward. What you'll eventually end up with is:
- exchange
- symbol
- timestamp
- O
- H
- L
- C
- V

> The problem is that Mongodb wants an instance of dict, so how could I transform this nested lists into a proper dictionary ? 

It should be something like:
```javascript
const exchangeId = 'binance';
const symbol = 'ETH/BTC';
const exchange = new ccxt['binance'] ();
const ohlcvs = await exchange.fetchOHLCV(symbol);

for (let i = 0; i < ohlcvs.length; i++) {
    const ohlcv = ohlcvs[i];
    db.insert(exchange.id, symbol, ohlcv[0], ohlcv[1], ohlcv[2], ...);
}
```

Pay attention that on some of the exchanges `fetchOHLCV` is emulated, on them you'll probably get just a fraction of a day candle. Exchanges with native OHLCV implementation also impose some limits on how far back into history you can go and on number of returned candles.

So I'm afraid that you'll need to fetch raw trades and build OHLCVs by yourself. Hopefully, it's pretty easy to do with ccxt, just prepare to spend few days on that. More on it here: #2596, #2321.

**Comment by kroitor** [comment]
@HornKild closing this for now, if you don't mind. Let us know if @mkutny's answer does not satisfy your question. Thx!

**Comment by HornKild** [comment]
Thank you @mkutny
