### ISSUE TITLE
Is there a way to only get the last price for a symbol?

### ISSUE THREAD

**Issue by klover1** [ccxt/ccxt#2763]
Hello,
I'm wondering  if there is a more basic version of fetchTicker() . I have spent some time looking over the manual and code but can't seem to find one. 

If I run exchange.fetchTicker('ETH/USDT') against I get a big long JSON with lots of additional data which I do not want, all I am looking for is the last price which helps with the rate limit. 

Binance has an API call which returns this single value

`https://api.binance.com/api/v1/ticker/price?symbol=ETHUSDT`

```

symbol | "ETHUSDT"
price | "817.32000000"
```

Is there a CCXT function that calls this ?

using python3, exchange is Binance. 

Thanks!

**Comment by kroitor** [comment]
> I'm wondering if there is a more basic version of fetchTicker() .

There isn't a structure simpler than a ticker. All other structures are usually bigger and have more levels of nesting. So, with 99% of exchanges, the ticker is the simplest atomic piece of data you can get.

> Binance has an API call which returns this single value

It is practically one of a couple of exchanges that does that. We have that method implemented:

```Python
# from ccxt implementation of binance:

def fetch_bid_asks(self, symbols=None, params={}):
        self.load_markets()
        rawTickers = self.publicGetTickerBookTicker(params)
        return self.parse_tickers(rawTickers, symbols)
```


```
bp:ccxt igorkroitor$ python examples/py/cli.py binance fetch_bid_asks ETH/BTC
{u'ETH/BTC': {'ask': 0.0839,
              'askVolume': 66.257,
              'average': None,
              'baseVolume': None,
              'bid': 0.083836,
              'bidVolume': 14.943,
              'change': None,
              'close': None,
              'datetime': None,
              'high': None,
              'info': {u'askPrice': u'0.08390000',
                       u'askQty': u'66.25700000',
                       u'bidPrice': u'0.08383600',
                       u'bidQty': u'14.94300000',
                       u'symbol': u'ETHBTC'},
              'last': None,
              'low': None,
              'open': None,
              'percentage': None,
              'previousClose': None,
              'quoteVolume': None,
              'symbol': u'ETH/BTC',
              'timestamp': None,
              'vwap': None}}
mbp:ccxt igorkroitor$
```

It will return just the 4 pieces you want:
- bid
- bidVolume
- ask
- askVolume

Hope this answers your question.

**Comment by klover1** [comment]
It does. Thanks for the detailed explanation.
