### ISSUE TITLE
Ethfinex doesn't recognize a placing order as margin

### ISSUE THREAD

**Issue by DmitryVil** [ccxt/ccxt#2764]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10 Pro, version 1709
- Programming Language version: Python 3.6.4 
- CCXT version: 1.13.88
- Exchange: Ethfinex 
- Method: createMarketBuyOrder() and createMarketSellOrder()

I have a balance on the Ethfinex:
{'info': [{'type': 'exchange', 'currency': 'btc', 'amount': '0.06521683', 'available': '0.06521683'}, {'type': 'exchange', 'currency': 'eth', 'amount': '0.0', 'available': '0.0'}, {'type': 'trading', 'currency': 'btc', 'amount': '0.04999175', 'available': '0.04999175'}, {'type': 'trading', 'currency': 'eth', 'amount': '0.0', 'available': '0.0'}, {'type': 'trading', 'currency': 'usd', 'amount': '0.91323893', 'available': '0.91323893'}], 'BTC': {'free': 0.06521683, 'used': 0.0, 'total': 0.06521683}, 'ETH': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'free': {'BTC': 0.06521683, 'ETH': 0.0}, 'used': {'BTC': 0.0, 'ETH': 0.0}, 'total': {'BTC': 0.06521683, 'ETH': 0.0}}

It seems that I have enough funds to buy 0.05 ETH.
 
I would like to make a transaction on margin:
ethfinex.createMarketBuyOrder('ETH/USD', 0.05, {'leverage': 3}))

But I got an error:
Error: ethfinex {"message":"Invalid order: not enough exchange balance for 0.05 ETHUSD at 815.68"}

In the same time I did exactly this operation using WEB interface on Ethfinex site

**Comment by kroitor** [comment]
@DmitryVil createOrder methods don't support margin/leverage positions. You should use implicit methods for that: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods. Let us know if it does not answer your question. Thx!

**Comment by DmitryVil** [comment]
I have checked implicits methods:

ethfinex.create_market_sell_order('ETH/USD', 0.05, {'leverage': 3}) and
ethfinex.create_order('ETH/USD', 'market', 'sell', 0.05, None, {'leverage': 3})

They also don't recognaze requests as margin/leverage

**Comment by kroitor** [comment]
> I have checked implicits methods:
> ethfinex.create_market_sell_order('ETH/USD', 0.05, {'leverage': 3}) and
> ethfinex.create_order('ETH/USD', 'market', 'sell', 0.05, None, {'leverage': 3})

Those are not implicit methods...

```Python
mbp:python igorkroitor$ python
Python 2.7.13 (default, Jun  5 2017, 10:04:07)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> from pprint import pprint
>>> pprint(dir(ccxt.ethfinex()))
['__class__',
 '__del__',
 ...

# these are the implicit methods:

 'privatePostAccountFees',
 'privatePostAccountInfos',
 'privatePostBalances',
 'privatePostBasketManage',
 'privatePostCredits',
 'privatePostDepositNew',
 'privatePostFundingClose',
 'privatePostHistory',
 'privatePostHistoryMovements',
 'privatePostKeyInfo',
 'privatePostMarginInfos',
 'privatePostMytrades',
 'privatePostMytradesFunding',
 'privatePostOfferCancel',
 'privatePostOfferNew',
 'privatePostOfferStatus',
 'privatePostOffers',
 'privatePostOffersHist',
 'privatePostOrderCancel',
 'privatePostOrderCancelAll',
 'privatePostOrderCancelMulti',
 'privatePostOrderCancelReplace',
 'privatePostOrderNew',
 'privatePostOrderNewMulti',
 'privatePostOrderStatus',
 'privatePostOrders',
 'privatePostOrdersHist',
 'privatePostPositionClaim',
 'privatePostPositionClose',
 'privatePostPositions',
 'privatePostSummary',
 'privatePostTakenFunds',
 'privatePostTotalTakenFunds',
 'privatePostTransfer',
 'privatePostUnusedTakenFunds',
 'privatePostWithdraw',
 'private_post_account_fees',
 'private_post_account_infos',
 'private_post_balances',
 'private_post_basket_manage',
 'private_post_credits',
 'private_post_deposit_new',
 'private_post_funding_close',
 'private_post_history',
 'private_post_history_movements',
 'private_post_key_info',
 'private_post_margin_infos',
 'private_post_mytrades',
 'private_post_mytrades_funding',
 'private_post_offer_cancel',
 'private_post_offer_new',
 'private_post_offer_status',
 'private_post_offers',
 'private_post_offers_hist',
 'private_post_order_cancel',
 'private_post_order_cancel_all',
 'private_post_order_cancel_multi',
 'private_post_order_cancel_replace',
 'private_post_order_new',
 'private_post_order_new_multi',
 'private_post_order_status',
 'private_post_orders',
 'private_post_orders_hist',
 'private_post_position_claim',
 'private_post_position_close',
 'private_post_positions',
 'private_post_summary',
 'private_post_taken_funds',
 'private_post_total_taken_funds',
 'private_post_transfer',
 'private_post_unused_taken_funds',
 'private_post_withdraw',
 ...
 'publicGetBookSymbol',
 'publicGetLendbookCurrency',
 'publicGetLendsCurrency',
 'publicGetPubtickerSymbol',
 'publicGetStatsSymbol',
 'publicGetSymbols',
 'publicGetSymbolsDetails',
 'publicGetTickers',
 'publicGetToday',
 'publicGetTradesSymbol',
 'public_get_book_symbol',
 'public_get_lendbook_currency',
 'public_get_lends_currency',
 'public_get_pubticker_symbol',
 'public_get_stats_symbol',
 'public_get_symbols',
 'public_get_symbols_details',
 'public_get_tickers',
 'public_get_today',
 'public_get_trades_symbol',
  ...
 'ymd',
 'ymdhms']
>>>
```

**Comment by DmitryVil** [comment]
Great. Thank you very much. I will try.

**Comment by kroitor** [comment]
@DmitryVil please, keep in mind that implicit methods are exchange-specific, so you will have to consult ethfinex docs, that is until we unify leveraged/margin trading within ccxt unified API. Let us know if you have other questions, will be happy to help.

**Comment by DmitryVil** [comment]
Igor, thank you very much.
It really works for bitfinex.
Could you give me an advice about hitbtc2?
Does this exchange also require implicit methods for trading of margin?

**Comment by kroitor** [comment]
> Does this exchange also require implicit methods for trading on margin?

In general, we don't have margin/leveraged trading in the unified CCXT API yet, but we are working on it, hope to add it as soon as possible. In the meantime, you really should use implicit methods if you want to implement a position-trading algo. Hope it answers your questions.

**Comment by terrorizers** [comment]
nor `bitfinex.private_post_position_close({'position_id': 17733587021}` nor `bitfinex.privatePostPositionClose({'position_id': 17733587021})` works, what to do?
