### ISSUE TITLE
GDAX pagination support (for fetch_trades, etc)

### ISSUE THREAD

**Issue by tekr** [ccxt/ccxt#2768]
The GDAX API uses pagination (https://docs.gdax.com/#pagination) to return large data sets; e.g. calling fetch_trades() will not return more than 100 trades at a time, even though more data may be available. 

Fetching additional pages requires parsing the cursor value returned in the response's header, and passing that into the next request along with a before/after parameter to indicate where to move in the result set (details are in the page linked above).

I can't seem to find any reference to or support for this currently in ccxt. Is that correct? Thanks.

- OS: AWS Linux
- Programming Language version: Python 3.6.5
- CCXT version: 1.13.53
- Exchange: GDAX
- Method: fetch_trades

**Comment by kroitor** [comment]
> I can't seem to find any reference to or support for this currently in ccxt. Is that correct? Thanks.

This is currently not supported directly in the unified methods for fetching trades, but you can access the headers after the request via a `exchange.last_response_headers` and use that info for scrolling GDAX pages. Hope this helps.

**Comment by npomfret** [comment]
@tekr did you figure out a nice way to pass the pagination headers to subsequent calls?

**Comment by kroitor** [comment]
@npomfret 

- https://github.com/ccxt/ccxt/blob/master/examples/js/gdax-fetch-trades-pagination.js

```JavaScript
'use strict';


const ccxt = require ('../../ccxt.js')
    , log  = require ('ololog').noLocate

const exchange = new ccxt.gdax ({
    'enableRateLimit': true,  // required by the Manual
})

;(async () => {

    const symbol = 'ETH/BTC'
    const params = {}
    await exchange.loadMarkets ()
    exchange.verbose = true
    while (true) {
        const trades = await exchange.fetchTrades (symbol, undefined, undefined, params)
        if (trades.length) {
            const firstTrade = trades[0]
            const lastTrade = trades[trades.length - 1]
            log.yellow ('Fetched', trades.length, symbol, 'trades from', firstTrade['datetime'], 'to', lastTrade['datetime'])
            if ('Cb-After' in exchange.last_response_headers) {
                params['after'] = exchange.last_response_headers['Cb-After'];
            }
        } else {
            log.green ('Done.')
            break;
        }
    }

}) ()

```

**Comment by npomfret** [comment]
@kroitor is `cursor = this._exchange.last_response_headers['Cb-After'];` still the recommended way to paginate through the CBP stuff?

**Comment by kroitor** [comment]
@npomfret i'd say, a recommended way is to intercept it with a subclass method override (that is until we add a better way for this). However, if you're going to use `last_response_headers`, make sure you understand the implications, namely, you can't paginate asynchronously.

**Comment by npomfret** [comment]
> you can't paginate asynchronously.

yep!
