### ISSUE TITLE
[BitMEX] Getting balance of altcoin positions

### ISSUE THREAD

**Issue by yidkato** [ccxt/ccxt#2774]
- OS: Mac OS X High Sierra
- Programming Language version: Python 3.6
- CCXT version: 1.13.66
- Exchange: BitMEX
- Method: fetch_balance()

After looking through the different exchanges code, it appears that `fetch_balance()` returns whatever the exchange API's response is, without the ability to specify a specific coin. For most exchanges, I can do something like `exchange.fetch_balance()['free']['ETH']`.

But for BitMEX, that only gives works for BTC, so I have to use `bitmex.private_get_position({'symbol':'ETHM18'}[0]['currentQty'])` which is quite troublesome as I have to include a unique case for BitMEX each time.

If this issue only affects BitMEX (I'm not sure if that's the case), are there plans to update `fetch_balance()` in the bitmex class to call `private_get_position()`? That would allow for `fetch_balance()['free']['<symbol>']` to be a unified method of getting altcoin positions.

**Comment by kroitor** [comment]
In general, we don't have margin/leveraged trading in the unified CCXT API yet, but we are working on it, hope to add it as soon as possible. In the meantime, you really should use implicit methods if you want to implement a position-trading algo. 

Hope it answers your questions.
