### ISSUE TITLE
bitstamp1 v1 fetchTicker doesn't support BTC/EUR, use it for BTC/USD only

### ISSUE THREAD

**Issue by StErMi** [ccxt/ccxt#2776]
- OS: Windows 10
- Programming Language version: Node
- CCXT version: 1.13.97
- Exchange: bitstamp1
- Method: fetchTicker 

Message: bitstamp1_cron v1 fetchTicker doesn't support BTC/EUR, use it for BTC/USD only

**Comment by kroitor** [comment]
Well, it says what it says, I cannot really clarify it further than it is. Unfortunately, bitstamp v1 won't support other pairs for now.

**Comment by StErMi** [comment]
it's fine, but why those pairs are in bitstamp markets? (sorry for the stupid question, just wondering)

**Comment by kroitor** [comment]
> it's fine, but why those pairs are in bitstamp markets? (sorry for the stupid question, just wondering)

You can still trade them with bitstamp v2, just cannot use them with v1. The markets are shared between the two. We will decouple them further or will remove v1 completely. Basically, there's almost no reason for using bitstamp1 now, it's here for legacy reasons. Hope this answers your question.

**Comment by StErMi** [comment]
At the moment I'm only interested in gathering data so I will skip trade.
Do I need to configure it in someway bitstamp to use v2 or it's just a
different exchange in ccxt??

**Comment by kroitor** [comment]
> Do I need to configure it in someway bitstamp to use v2 or it's just a different exchange in ccxt??

Just a different exchange without the `1` suffix, just `bitsamp`.
