### ISSUE TITLE
ZAIF POST 502 Server Error: Bad Gateway TRANSACTION ERROR WRONG THE ENDPOINT URL 

### ISSUE THREAD

**Issue by k31ww475** [ccxt/ccxt#2779]
Hi guys.
zaif official page announced the correct endpoint URL 
source
http://techbureau-api-document.readthedocs.io/ja/latest/trade/1_common.html#id2

correct URL
https://api.zaif.jp/tapi

recent ver
now ccxt refer the follow URL
https://api.zaif.jp/tapi

So it occured the error
ccxt.base.errors.ExchangeNotAvailable: zaif https://api.zaif.jp/tapi POST 502 Server Error: Bad Gateway for url: https://api.zaif.jp/tapi <html>

Could you set accurate endpoint url please?

- OS:WIN10
- Programming Language version:
- CCXT version:LATEST
- Exchange:ZAIF

Thanks in advance

**Comment by k31ww475** [comment]
This issue was my misstype that's why it will be closed.

**Comment by kroitor** [comment]
@k31ww475 ok, thx for reporting back!
