### ISSUE TITLE
cryptopia ExchangeError "unrecognized pair id"

### ISSUE THREAD

**Issue by Esc4pism** [ccxt/ccxt#2780]
Could you perhaps change this error to something else or tell me a way to distinguish this error from other possible ExchangeErrors (or perhaps bypass or disable it)?

its in fetchTickers:

if (!recognized)
                throw new ExchangeError (this.id + ' fetchTickers() returned unrecognized pair id ' + id.toString ());

I already implemented a method for all exchanges to automatically detect when fetchTickers returns new symbols/pairs, and handle them through logging and/or automatically re-fetching markets, then im still able to read and update all the other pairs in each request. But this thrown error in cryptopia wont let me update all the other working markets either since the promise is rejected, and all the other data from this request is lost.

**Comment by kroitor** [comment]
1. Update ccxt to most recent version.
2. Add `{ 'options': { 'fetchTickersErrors': false }}` to your constructor params for Cryptopia.
3. Enjoy )
