### ISSUE TITLE
NegocieCoins TradeAPI Issue

### ISSUE THREAD

**Issue by rtadewald** [ccxt/ccxt#2782]
Hello, Guys
I've seen that you had added negociecoins support recently. But I wasn't able to use it's Private API. Is someone facing the same problem?
Something about 403 error.

**Comment by kroitor** [comment]
@rtadewald 

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

↑ can you please follow these steps precisely (we need all that info, **your code and your verbose output** in order to help you):
