### ISSUE TITLE
Any way to store HTTP requests from verbose? (Pretty simple and quick)

### ISSUE THREAD

**Issue by karlandoh** [ccxt/ccxt#2787]
El Capitan
- Programming Language version: Python
- CCXT version: Latest

- Method:
I just need a way to obtain the Request URL, and append it. Is this possible?

For example:
**Request: GET https://api.binance.com/api/v1/exchangeInfo {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None**

This is what I need. 
Thank you.

**Comment by kroitor** [comment]
@karlandoh have you tried built-in python logging? CCXT will log to standard python logging, so you can use it to save that output to a db or to a file. Let us know if it does not answer your question. Thx!

**Comment by karlandoh** [comment]
Will get on it. Thanks!

**Comment by karlandoh** [comment]
Not exactly what I was looking for. Is see that each exchange class has a proxy attribute. However it is just for URLs (lol). Is there a way to use CCXT with a proxy (host and port), without importing any extra modules such as socket?

Thanks!

**Comment by kroitor** [comment]
@karlandoh 

- https://github.com/ccxt/ccxt/issues/2624
- https://github.com/ccxt/ccxt/issues/906#issuecomment-353257840
- https://github.com/ccxt/ccxt/search?q=proxy+python&type=Issues

**Comment by karlandoh** [comment]
Got it. You're the best!
