### ISSUE TITLE
fetchMyTrades Doesn't Respect Limit

### ISSUE THREAD

**Issue by page1** [ccxt/ccxt#2790]
- OS: Ubuntu
- Programming Language version: Python 3.5.3
- CCXT version: 1.13.67
- Exchange: Poloniex & Kraken
- Method: fetchMyTrades

Hi CCXT! 
I noticed that the limit parameter of fetchMyTrades doesn't actually get passed to the api call
https://github.com/ccxt/ccxt/blob/593ec4371ea1a9063de581b5d32d8c0c91b5ddb4/python/ccxt/poloniex.py#L434

This means only the most recent 500 trades in poloniex are fetched or 50 in kraken's case.

I can kludge around this in poloniex if I have less than 10k trades on a market with:
`params={"limit": 10000}`

I can't figure out a way to get around this in kraken.

I'm hoping to be able to ingest trades, starting from oldest to newest, in manageable blocks.
Any ideas?
Thanks

**Comment by kroitor** [comment]
Unfortunately, Kraken does not provide a parameter for limiting the trade count, so we are limiting on client side as well. We re-enabled the limit for poloniex, available in version 1.13.101. Thx!

**Comment by page1** [comment]
Thanks @kroitor 
Updated to new version and Poloniex accepts limit :) 

Kraken on the other hand seems to give 50 latest trades from the general ledger... for example:
`exchanges['kraken'].fetchMyTrades(since=0, symbol='LTC/BTC', limit=10000)`
gives me trades from various symbols including but not limited to LTC/BTC

Thanks for the help on Poloniex front.
