### ISSUE TITLE
Possible to change endpoint url?

### ISSUE THREAD

**Issue by whchen8** [ccxt/ccxt#2791]
For a unified ccxt API, I'm wondering if its possible to modify the endpoint url?
Say API `fetch_order()` requests url `/api/v1/order` in ccxt, later I find its unpublished **v2** api, like `/api/v2/order`. Assume that they return the results in the same format, ccxt would then still work if I can change the endpoint url to the new one.
Is it possible? If so, how?

**Comment by kroitor** [comment]
@whchen8 yes, it's possible, you just need to redefine the private part of the `api` property of the exchange in question, and the `urls` property as well, if needed, then, after instantiation, a new implicit method will be available to you. See the implementation of your exchange in question from ccxt for more details.

Also described here:

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

Let us know if it does not answer your question. Thx!
