### ISSUE TITLE
New Exchange: Coinsquare

### ISSUE THREAD

**Issue by lukespeng** [ccxt/ccxt#2794]
The implementation for "Quoinex" seems to be incomplete. The Quoinex exchange now supports all public and private APIs for market prices, orders, trades, balances, etc. It will be great to have the implementation completed.

In addition, the Coinsquare exchange has public APIs for market data, though no APIs for order requests yet. But it is good to add it in.

Overall great job on the project and glad to see that you guys work on it actively.

**Comment by kroitor** [comment]
https://coinsquare.com/

**Comment by kroitor** [comment]
> The implementation for "Quoinex" seems to be incomplete. The Quoinex exchange now supports all public and private APIs for market prices, orders, trades, balances, etc. It will be great to have the implementation completed.

Answered here: https://github.com/ccxt/ccxt/wiki/FAQ

> In addition, the Coinsquare exchange has public APIs for market data, though no APIs for order requests yet. But it is good to add it in.

Can't really find any real exchange API there, will have to reconsider it again later, when they add some links to docs somewhere.
