### ISSUE TITLE
Running Composer  only updates ccxt to 1.13.87 and not 1.13.105

### ISSUE THREAD

**Issue by HarshRajat** [ccxt/ccxt#2796]
Steps to reproduce:
- Check if composer.json has 1.* in the installation
- run composer update

Alternate methods tried:
- Deleting vendor and composer.lock
- running composer install

**Comment by kroitor** [comment]
Sorry, I didn't really get the issue, the current version of CCXT is 1.13 and it is perfectly available with Composer:

```
mbp:test-composer-installation igorkroitor$ composer init


  Welcome to the Composer config generator



This command will guide you through creating your composer.json config.

Package name (<vendor>/<name>) [igorkroitor/test-composer-installation]:
Description []:
Author [Igor Kroitor <igor.kroitor@gmail.com>, n to skip]:
Minimum Stability []:
Package Type (e.g. library, project, metapackage, composer-plugin) []:
License []:

Define your dependencies.

Would you like to define your dependencies (require) interactively [yes]? yes
Search for a package: ccxt

Found 15 packages matching ccxt

   [0] ccxt/ccxt
   [1] kornrunner/ccxt
   [2] skajdo/crc16-ccit
   [3] notrix/crc
   [4] kittinan/php-crc
   [5] cct-marketing/rest-exception-handler
   [6] theapi/cctvbundle
   [7] theapi/cctvblindfoldbundle
   [8] marcelovani/cctv-mate
   [9] havvg/php-cctrl
  [10] cctool/cctool
  [11] havvg/cloudcontrol-bundle
  [12] cct-marketing/rest
  [13] cct-marketing/kong-php-sdk
  [14] cct-marketing/collections

Enter package # to add, or the complete package name if it is not listed: 0
Enter the version constraint to require (or leave blank to use the latest version):
Using version ^1.13 for ccxt/ccxt
Search for a package: ccxt
```

<img width="656" alt="screen shot 2018-05-08 at 23 13 43" src="https://user-images.githubusercontent.com/1294454/39780635-93ef334c-5315-11e8-8de1-e15c38e80e21.png">

See versions here: https://packagist.org/packages/ccxt/ccxt

Hope this help. Let us know if not.

**Comment by kroitor** [comment]
@HarshRajat not sure if we are looking at the same page...
Mine shows this:

![screen-shot-2018-05-08-at-23 24 16](https://user-images.githubusercontent.com/1294454/39781213-3b7f4132-5317-11e8-9e71-5437751cfde7.jpg)

Do you use any caching proxies? Tried refreshing that page with ctrl+R or cmd+R or ctrl+shift+R or cmd+shift+R ?

**Comment by kroitor** [comment]
Ok, nevermind my previous post. The problem is most likely related to the following:

<img width="754" alt="screen shot 2018-05-08 at 22 33 21" src="https://user-images.githubusercontent.com/1294454/39781459-e3b2cd60-5317-11e8-8b5b-3e61202e5901.png">


We are investigating...

**Comment by HarshRajat** [comment]
Thanks for the quick response :).. sorry for screwing up the versions before.

**Comment by kroitor** [comment]
Contacted Packagist support on this issue. Standing by for their reply.

**Comment by kroitor** [comment]
Packagist answered:

```
Hey,

Indeed your package seems to be hitting our update job timeout limits. 
This is probably due to the gazillion tags you have as the update 
process has to loop through them all..

This is only getting worse and worse with time unfortunately. I will 
have to look if I can improve the situation but probably won't have much 
time until next week.

Best,
Jordi
```

**Comment by HarshRajat** [comment]
Damn... Seems like we are stuck till they solve it from their end :(

**Comment by HarshRajat** [comment]
Maybe we can reduce the tags for packagist till they solve the issue as an alternate??

**Comment by kroitor** [comment]
```
Hi, Jordi!

Thanks for answering!

Sorry for the trouble, we didn't expect that tagging patch, minor and major versions would be a problem. We have to tag them frequently due to the nature of our project – it's a big library with thousands of users, that is actively maintained "live" and "in real time". Our community will be really happy if you could help us resolve it as soon as possible.

Is there something we can do about it on our side?

Really looking forward to getting it resolved.

Best wishes,
Igor Kroitor
CCXT Dev Team
```

**Comment by kroitor** [comment]
@HarshRajat I'm not sure if we can prune the old tags from the repo – not even sure if this is possible without breaking something. In other words, it does not work backwards. Correct me if I'm wrong.

**Comment by kroitor** [comment]
@HarshRajat you don't have to wait, actually, can clone the repository, run `php composer.phar install`  in it and use the cloned folder until this is resolved.

**Comment by HarshRajat** [comment]
@kroitor You are right. It would be better for them to respond as to what is the best way rather than trying something like this and end it breaking for other users who are on older versions.

**Comment by HarshRajat** [comment]
@kroitor Thanks for providing the alternate, I will do that and disable the autoupdate cron for now :).

**Comment by HarshRajat** [comment]
@kroitor On a lighter note, Kudos on the development of the project... you guys broke packagist!!!

**Comment by kroitor** [comment]
@kornrunner thanks for your help! Really helpful! Will clean up older versions today, hope it will be enough until they fix it on their side )

**Comment by kroitor** [comment]
Cleaned up some old tags from packagist, and looks like it resumed updating versions... for now... ))
