### ISSUE TITLE
okex market order returns 0 total amount and negative filled amount

### ISSUE THREAD

**Issue by whchen8** [ccxt/ccxt#2799]
- OS: macOS 10.13.3
- Programming Language version: Python 3.6.5
- CCXT version: 1.13.97
- Exchange: okex
- Method: `fetch_orders()`

When fetching **market** orders from **okex**, it seems that the unparsed returned info is like:

```python
'info': {
    'amount': 0,
    'avg_price': ...,
    'create_date': ...,
    'deal_amount': 1.247,
    ...
    'symbol': ...,
    'type': 'buy_market'
}
```

while **ccxt** parses the results as:

```python
amount = order['amount']
filled = order['deal_amount']
remaining = amount - filled
```

That's why it returns **0** total amount and **negative** remaining amount.

**Comment by kroitor** [comment]
Fixed in 1.13.109. Thx for reporting!
