### ISSUE TITLE
Cryptopia python fetch_balance params

### ISSUE THREAD

**Issue by yamontv** [ccxt/ccxt#2800]
- OS: Ubuntu 16.04
- Programming Language version: Python
- CCXT version: 1.13.110
- Exchange: Cryptopia
- Method: fetch_balance
Params is not added to request. Please fix

**Comment by yamontv** [comment]
Please fix python version too. Not only js

**Comment by kroitor** [comment]
@yamontv it's fixed automatically by our build system (python code is generated): https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

Will be available in the upcoming version 1.13.112 in 5-10 minutes.

**Comment by yamontv** [comment]
Oh thank you. I dont know this

**Comment by kroitor** [comment]
@yamontv alright, it's there ) Let us know if you have any other difficulties with it. Thx for reporting!
