### ISSUE TITLE
Huge amount of BTC in orderbook of Bitmex for symbol BTC/USD

### ISSUE THREAD

**Issue by DmitryVil** [ccxt/ccxt#2808]
- OS: Windows
- Programming Language version: python 3.6.5
- CCXT version: 1.13.88
- Exchange: Bitmex
- Method: fetchL2OrderBook()

Igor, good morning,

I am analysing orderbook that I fetched form Bitmex for BTC/USD.
I each bids and asks order I got I saw unreal amount of BTC currency.
Like this : [[9361.5, 883992], [9361, 45566], [9360.5, 316415], [9360, 391828], [9359.5, 303333]....
May it is a mistake

**Comment by kroitor** [comment]
Bitmex returns the amounts in Satoshi: 

> Note that all Bitcoin quantities are returned in Satoshis: 1 XBt (Satoshi) = 0.00000001 XBT (Bitcoin).

I'll fix it shortly.

**Comment by DmitryVil** [comment]
Thank you, Igor

**Comment by pcriadoperez** [comment]
Completed as mentioned in #3199
