### ISSUE TITLE
Binance: too many requests despite using

### ISSUE THREAD

**Issue by stabilus** [ccxt/ccxt#2810]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Win 7 64
- Programming Language version: Python 3.6.4 32
- CCXT version: 1.13.123
- Exchange: binance
- Method: various

I am getting "binance 429" errors (too many requests, current limit is 1200 requests per minute) despite using .enableRateLimit=True

This is most likely due to the fact that I am calling .fetchTickers() which apparently weighs heavier than other API calls.
quote: _Each route has a weight which determines for the number of requests each endpoint counts for. Heavier endpoints and endpoints that do operations on multiple symbols will have a heavier weight._

Given that I am receiving 429 errors, I assume that ccxt currently does not consider weight cost for various API end points.

Two thinkable approaches:

1) include the weighing system into the .enableRateLimit= True logic

2) react to 429 errors from binance -> reduce rate -> sporadically increase rate to probe for errors

Can you do something on your side, or do we have to somehow react to these exchange errors?

**Comment by kroitor** [comment]
> include the weighing system into the .enableRateLimit= True logic

The variable costs are not completely unified yet, but we have a tokenBucket algo implemented, but this is not documented yet, and it is experimental, you can use it to set proper costs for the methods you're calling, however, this will require some overrides on your side as well. 

Let us know if these posts do not answer your question: 
- #1399
- https://github.com/ccxt/ccxt/issues/297
- https://github.com/ccxt/ccxt/pull/373

Thx!

**Comment by stabilus** [comment]
Thanks for that fast feedback!
I looked at the posts you suggested but seem to fall over my "non-programmer" background.

Would you mind giving some pointers as to how to implement this tokenBucket algo (python)?
