### ISSUE TITLE
cancelOrder bithumb errors

### ISSUE THREAD

**Issue by vlad-tokarev** [ccxt/ccxt#2813]
- OS:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Programming Language version:
Python 3.6

- CCXT version: __version__ = '1.13.101'
- Exchange: bithumb
- Method: cancelOrder

Problem 1: logic error at lines 264-267 in file async/bithumb.py. "side" variable cast to bool type for check that it is not null, but then the same variable is compared with ''buy" string. Therefore control flow is always is gone by the same path of execution. More precisely "sales" value is assigned to variable in any case.

Problem 2: The same module and place in code. The same variable side is used for parametrizing request query. But not correct string values are assigned to it. 
Documentation quote: `transaction type(bid : purchase, ask : sales)`
In ccxt "purchase" and "sales" string are assigned to parameter, but correct parameters are "bid" and "ask" as I figure out.

P.S. I'm sorry if I fill issue form not correct
P.P.S. I can fix this issues when I find time to see into ccxt build process, but I suppose that probably someone can fix them quickly. (I hotfix them in my project code)

**Comment by kroitor** [comment]
Will get to it soon. Thx for reporting!

**Comment by kroitor** [comment]
JFYI: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code )
