### ISSUE TITLE
Cointiger.com Public API not returning values for price and volume

### ISSUE THREAD

**Issue by Cleric334** [ccxt/ccxt#2820]
Hello. It looks like public API for Cointiger.com does not return any values, be it ask, bid or volume (base, quote)

I am using the same script, and it works for all the other exchanges through, but not for Cointiger for some reason.

I am doing something wrong?

**Comment by Cleric334** [comment]
Update: 

Looks like Cointiger labels "bids" as "buys", ask are labeled properly. My buddy managed to fix it by using this code

`async fetchOrderBook (symbol, limit = undefined, params = {}) {
        await this.loadMarkets ();
        let market = this.market (symbol);
        let response = await this.publicGetDepth (this.extend ({
            'symbol': market['id'], // this endpoint requires a lowercase market id
            'type': 'step0',
        }, params));
        let data = response['data']['depth_data'];
        if ('tick' in data) {
            if (!data['tick']) {
                throw new ExchangeError (this.id + ' fetchOrderBook() returned empty response: ' + this.json (response));
            }
            let orderbook = data['tick'];
            orderbook.bids = orderbook.buys;           
            let timestamp = data['ts'];
            return this.parseOrderBook (orderbook, timestamp);
        }
        throw new ExchangeError (this.id + ' fetchOrderBook() returned unrecognized response: ' + this.json (response));
    }`

I don't know if it's a good fix, but works for us.

**Comment by yummish** [comment]
There is a parameter in Exchange.py to specify the key for this field. So, just adding the "buys" key to self.parseOrderBook function call should be good enough.
