### ISSUE TITLE
pip install ccxd fails on some compilation errors

### ISSUE THREAD

**Issue by denis-imaev** [ccxt/ccxt#2824]
OS: MacOS 
Anaconda3
CCXT 1.13

When running "pip install ccxt" encountered the following, and the package does not install.

gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/denis/anaconda3/include -arch x86_64 -I/Users/denis/anaconda3/include -arch x86_64 -Isrc/ext/uchardet/src -I/Users/denis/anaconda3/include/python3.6m -c src/cchardet/_cchardet.cpp -o build/temp.macosx-10.7-x86_64-3.6/src/cchardet/_cchardet.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cchardet
  Running setup.py clean for cchardet
  Running setup.py bdist_wheel for pycares ... error
  Complete output from command /Users/denis/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/jl/mjl_gg457cd6n9btv70n20l40000gn/T/pip-install-a6byn14x/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/jl/mjl_gg457cd6n9btv70n20l40000gn/T/pip-wheel-teljhkks --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.6
  creating build/lib.macosx-10.7-x86_64-3.6/pycares
  copying pycares/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/pycares
  copying pycares/__main__.py -> build/lib.macosx-10.7-x86_64-3.6/pycares
  copying pycares/_version.py -> build/lib.macosx-10.7-x86_64-3.6/pycares
  copying pycares/errno.py -> build/lib.macosx-10.7-x86_64-3.6/pycares
  running build_ext
  building 'pycares._core' extension
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/src
  creating build/temp.macosx-10.7-x86_64-3.6/deps
  creating build/temp.macosx-10.7-x86_64-3.6/deps/c-ares
  creating build/temp.macosx-10.7-x86_64-3.6/deps/c-ares/src
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/denis/anaconda3/include -arch x86_64 -I/Users/denis/anaconda3/include -arch x86_64 -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE=1 -I/Users/denis/anaconda3/include/python3.6m -Ideps/c-ares/src -Ideps/c-ares/src/config_darwin -c src/pycares.c -o build/temp.macosx-10.7-x86_64-3.6/src/pycares.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pycares
  Running setup.py clean for pycares
Failed to build cchardet pycares
Installing collected packages: pycares, aiodns, cchardet, setuptools, ccxt
  Running setup.py install for pycares ... error
    Complete output from command /Users/denis/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/jl/mjl_gg457cd6n9btv70n20l40000gn/T/pip-install-a6byn14x/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/jl/mjl_gg457cd6n9btv70n20l40000gn/T/pip-record-rchk1k7e/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/pycares
    copying pycares/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/pycares
    copying pycares/__main__.py -> build/lib.macosx-10.7-x86_64-3.6/pycares
    copying pycares/_version.py -> build/lib.macosx-10.7-x86_64-3.6/pycares
    copying pycares/errno.py -> build/lib.macosx-10.7-x86_64-3.6/pycares
    running build_ext
    building 'pycares._core' extension
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/src
    creating build/temp.macosx-10.7-x86_64-3.6/deps
    creating build/temp.macosx-10.7-x86_64-3.6/deps/c-ares
    creating build/temp.macosx-10.7-x86_64-3.6/deps/c-ares/src
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/denis/anaconda3/include -arch x86_64 -I/Users/denis/anaconda3/include -arch x86_64 -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE=1 -I/Users/denis/anaconda3/include/python3.6m -Ideps/c-ares/src -Ideps/c-ares/src/config_darwin -c src/pycares.c -o build/temp.macosx-10.7-x86_64-3.6/src/pycares.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/denis/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/jl/mjl_gg457cd6n9btv70n20l40000gn/T/pip-install-a6byn14x/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/jl/mjl_gg457cd6n9btv70n20l40000gn/T/pip-record-rchk1k7e/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/jl/mjl_gg457cd6n9btv70n20l40000gn/T/pip-install-a6byn14x/pycares/

**Comment by kroitor** [comment]
Do you have Apple CommandLineTools installed in your XCode ?

**Comment by denis-imaev** [comment]
I don't have Xcode at all... I'm actually surprised that its trying to build something. I'm just used to anaconda for its data analytics tools, but I don't have to use it in this instance. Should I switch to built-in python for ccxt?

**Comment by kroitor** [comment]
@denis-imaev I'm working on a Mac and don't have a build issue with both default py2.7 and default 3.6 on OS X High Sierra 10.13.1. I'm not sure yet, but, I have a gut feeling that this may be related.

**Comment by kroitor** [comment]
@denis-imaev when you type `pip3 install ccxt` it will launch the Anaconda-version of pip. You will have to deinstall it, I'm afraid. This was solved here: https://github.com/ccxt/ccxt/issues/1764
Let us know if it does not help. Thx!

**Comment by denis-imaev** [comment]
Thanks, this is how I ended up solving this: by using anaconda, but not condo environment (at least I think so):

1. switch back to anaconda python by adding its path 
2. pip install ccxt 
3. use ~/anaconda3/bin/python3.6   as interpreter

thanks again!

**Comment by kroitor** [comment]
@denis-imaev thx for reporting back!
