### ISSUE TITLE
[Bittrex] DUST_TRADE_DISALLOWED_MIN_VALUE_50K_SAT exception

### ISSUE THREAD

**Issue by giv13** [ccxt/ccxt#2825]
- OS: Windows 8
- Programming Language version: php 7.1
- CCXT version: 1.13.125
- Exchange: Bittrex
- Method: create_order

Bittrex has 2 types of exceptions when the currency is not enough:
- INSUFFICIENT_FUNDS
- DUST_TRADE_DISALLOWED_MIN_VALUE_50K_SAT

Could you add a second type of exception:
```
'exceptions': {
	...
	'DUST_TRADE_DISALLOWED_MIN_VALUE_50K_SAT': InsufficientFunds,
	...
}
```

Thanks!

**Comment by giv13** [comment]
Before you add this line, Igor, please check your email igor.kroitor@gmail.com. I asked a question there)

**Comment by kroitor** [comment]
It has been there before you opened this issue: https://github.com/ccxt/ccxt/blob/master/js/bittrex.js#L728 ;)
