### ISSUE TITLE
No fetch_order() for Gemini

### ISSUE THREAD

**Issue by ws2367** [ccxt/ccxt#2828]
Gemini has API for checking order status and it returns an order object: 
https://docs.gemini.com/rest-api/#order-status

CCXT does not support fetch_order() for Gemini yet. It's technically feasible and should be built.

**Comment by kroitor** [comment]
<img width="1966" alt="screen shot 2018-05-14 at 02 46 48" src="https://user-images.githubusercontent.com/1294454/39972939-191ff56a-5721-11e8-9821-53668bf2a94b.png">

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/FAQ
