### ISSUE TITLE
recent_trade: Doesnt work the same

### ISSUE THREAD

**Issue by ilampirai** [ccxt/ccxt#2831]
recent_trade works well in bitmex which I have tested and able to fetch the trade done with in last 5 min. But the same function is not working with Hitbtc. The return result has the trade occurred on 11th May 2018(which is 3 days old).

code:
bitmex.fetch_trades("ADAM18") // loads proper result
hitbtc.fetch_trades("DBET/ETH") // last trade is from 11th of May 

// timeStamp is my timestamp(in UTC) for NOW()-300 seconds to get the trades happen in last 5 min 
bitmex.fetch_trades("ADAM18",timeStamp)  // result matches 100%
hitbtc.fetch_trades("DBET/ETH",timeStamp) // empty result, Even tried NOW() - 4 days still empty.

- OS: Windows
- Programming Language version: Python 3.6
- CCXT version: 1.11.172
- Exchange: Bitmex (works very well) / Hitbtc (shows outdated info)
- Method: recent_trade

Thanks.

**Comment by mkutny** [comment]
Try to use hitbtc2 instead of hitbtc, it should work.

**Comment by rspadim** [comment]
at ccxt api side what we could do to make a "homogeneous" call of since/limit without params?
