### ISSUE TITLE
Chinese Manual development

### ISSUE THREAD

**Issue by bilibilihuangyifan** [ccxt/ccxt#2832]
We are a group of Chinese young man using CCXT. We are looking forward to translating the manual into the Chinese version so more Chinese user would like to use it.  We would like to begin with:
http://ccxt.readthedocs.io/en/latest/
and want some suggestions about how to start it.

**Comment by kroitor** [comment]
> and want some suggestions about how to start it.

Read this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md
The docs sources are here: https://github.com/ccxt/ccxt/tree/master/wiki

If you could commit the Chinese version alongside in the same directory, say, call those files `CN-Manual.md`, `CN-Install.md`, etc – we can work it out form there. That would be awesome!)

**Comment by bilibilihuangyifan** [comment]
okay！ We will submit CN-Manual.md soon!

**Comment by bilibilihuangyifan** [comment]
Hi, now we finished the README.md translation. see [CN-README.md](https://github.com/bilibilihuangyifan/ccxtcn/blob/CN-TRANSLATION/CN-README.md)
Here we keep all the English words unchanged and add Chinese translation below. Do you think we should delete all the translated English words and only remain corresponding Chinese translation in the final version of  CN-README.md? @kroitor

**Comment by kroitor** [comment]
> Do you think we should delete all the translated English words and only remain corresponding Chinese translation in the final version of CN-README.md?

Yep, we will have the docs separated by language for convenience. So, no need to keep the English duplicates in the Chinese version. Thank you! Looking forward for your pull-requests )

**Comment by bilibilihuangyifan** [comment]
Hi, we just add the CN-README.md file and send a pr #2887

**Comment by ttodua** [comment]
This issue can be closed and any further discussion continued under PR.
