### ISSUE TITLE
HitBTC fetch_ohlcv() dependent on limit parameter

### ISSUE THREAD

**Issue by ChriPo92** [ccxt/ccxt#2833]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Linux 16.04 LTS
- Programming Language version: Python 3.6
- CCXT version: 1.13.142
- Exchange: HitBTC v2
- Method: fetch_ohlcv()

While working with the HitBTC exchange I noticed a bad behavior (in my opinion) of the exchange when fetching ohlcvs. I know it's still in development, so I figured out where the problem lies and thought I would share it with you. Hopefully, I am not posting something that is already known and it actually is unwanted behavior. The code, where the problem occurs is as follows:

```
import ccxt.async as ccxt
import asyncio
from datetime import datetime

ex_markets = [["binance", "ETH/BTC"], ["kraken", "ETH/BTC"],
            ["hitbtc2", "ETH/BTC"], ["hitbtc2", "ZSC/ETH"], ["hitbtc2", "XRP/USDT"]]

start = int(datetime.strptime("01.01.2018", "%d.%m.%Y").timestamp())
end = datetime.today().timestamp()
period = 3600 * 24
limit = int(end - start) // period + 1

correct_results = {}
wrong_results = {}
async def work(ex_markets):
	for row in ex_markets:
		exchange = getattr(ccxt, row[0])()
		exchange.verbose = True
                data_wrong = await exchange.fetch_ohlcv(row[1], timeframe="1d",
		                                  since=start*1000)
		data_correct = await exchange.fetch_ohlcv(row[1], timeframe="1d",
		                                  since=start*1000, limit=limit)
		wrong_results[row[0]+row[1]] = data_wrong
                correct_result[row[0]+row[1]] = data_correct
loop = asyncio.get_event_loop()
loop.run_until_complete(work(ex_markets))
```
Here I'm using the async version of ccxt, but the result is the same in the standard version, at least for me. The problem is that the HitBTC api for fetching ohlcvs includes a limit parameter that is set to a default value of 100 candles per request. If the number of candles required for historic data is larger than said 100 candles (as in the example above, where 134 candles are required), a lot of data goes missing, and the initial timestamp is incorrect for the HitBTC candles, when compared to other exchanges (this is the case in the `wrong_results`). By calculating the number of candles beforehand, this bad behavior can be prevented, as is the case for the `correct_results` up to a maximum amout of 1000 candles. 

I hope that can be of help to anyone.

EDIT: When working with UTC Timestamps (which is the preferred way I guess), another unexpected behavior arises for the kraken exchange, since for kraken's api the `since` parameter is exclusive. That means if the exact timestamp of the beginning of a candle is chose for `since`, this candle is not included.

**Comment by kroitor** [comment]
From your code it seems that you're not using the arguments for fetchOHLCV correctly and do not understand how `limit` works.

First of, the default of limit = 100 means that HitBTC will return up to 100 candles at max to you, whatever timeframe you choose. If you choose `1d`, they will return up to last 100 days of OHLCV data to you. If you choose `1m` they will return up to a hundred last minutes of OHLCV.

So, the `limit` is the max count of candles to return.

From your code:

```Python
limit = int(end - start)
```

This line sets limit to a difference between start and end which is more than 100 candles. This is incorrect and HitBTC will still return up to 100 at max.

```
mbp:ccxt igorkroitor$ node examples/js/cli hitbtc2 fetchOHLCV ETH/BTC 1d 2018-01-01T00:00:00 --no-details --iso8601

hitbtc2.fetchOHLCV (ETH/BTC, 1d, 1514764800000)

2018-02-17T00:00:00.000Z  0.092219  0.093032  0.087688  0.087794  45601.445
2018-02-18T00:00:00.000Z  0.087794  0.089235  0.086273  0.087761  45276.578
2018-02-19T00:00:00.000Z  0.087761  0.08868   0.083857  0.084228  43187.635

... 100 days (3 months) in total ...

2018-05-25T00:00:00.000Z  0.079463  0.080987  0.077382  0.0785    17537.487
2018-05-26T00:00:00.000Z  0.078506  0.080355  0.077889  0.079956  35103.772
2018-05-27T00:00:00.000Z  0.079953  0.080411  0.077636  0.077859  29554.729
mbp:ccxt igorkroitor$
```

When used with `limit`:

```
mbp:ccxt igorkroitor$ node examples/js/cli hitbtc2 fetchOHLCV ETH/BTC 1d 2018-01-01T00:00:00 3 --no-details --iso8601

hitbtc2.fetchOHLCV (ETH/BTC, 1d, 1514764800000, 3) ←--------- give me last 3 candles

2018-05-25T00:00:00.000Z  0.079463  0.080987  0.077382  0.0785    17537.487
2018-05-26T00:00:00.000Z  0.078506  0.080355  0.077889  0.079956  35103.772
2018-05-27T00:00:00.000Z  0.079953  0.080411  0.077636  0.077864  29608.084

mbp:ccxt igorkroitor$
```

The usage of `fetchOHLCV` is documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts

Let me know if this does not answer your issue.

**Comment by ChriPo92** [comment]
Well to me it is not really clear which parameter takes precedence in the `fetch_ohlcv` method. So maybe my problem is not with the HitBTC exchange but with the fetch_ohlcv method in itself. Comparing the HitBTC exchange with other exchanges (which I chose to be kraken and binance in my original post), HitBTC performs different. The code 
```
import ccxt
from datetime import datetime, timezone
start = datetime.strptime("01.01.2018", "%d.%m.%Y").replace(
           tzinfo=timezone.utc).timestamp()
binance = ccxt.binance()
hitbtc = ccxt.hitbtc2()
kraken = ccxt.kraken()

hitbtc_ohlcv = hitbtc.fetch_ohlcv("ETH/BTC", timeframe="1d", since=int(start*1000))
binance_ohlcv = binance.fetch_ohlcv("ETH/BTC", timeframe="1d", since=int(start*1000))
kraken_ohlcv = kraken.fetch_ohlcv("ETH/BTC", timeframe="1d", since=int(start*1000))
```
delivers different results for each of the exchanges. For the binance and kraken more than 100 ohlcv candles are returned (where kraken has one less, because of the behavior I also explained in my original post). HitBTC on the other hand puts the precedence on the `limit` parameter of 100 candles overe the `since` parameters, which lies further in the past than 100 days. Kraken and Binance have the priority on the `since` parameter, which is the 01.01.2018. My problem was with the non-uniform behavior of the exchanges, when it comes to the same input `since`. I thought the `fetch_ohlcv` would take the `since` as starting point in time and collects `limit` candles from this point in time. This is the behavior the kraken  and binance exchanges have, when supplied with a `since` & `limit`. Hopefully this example explains my problem better than before. I still believe that the HitBTC exchange is faulty here, as the exchange with a different behavior than the other 2 exchanges. I haven't tried this with every exchange, so maybe overall HitBTC's behavior is correct, which would make binance and kraken exchanges faulty when uniform behavior of the `fetch_ohlcv` method is wanted. Maybe the wanted behavior should also be explained a little bit better in the documentation, as I could not seem to find an exact way it is supposed to work.

**Comment by kroitor** [comment]
@ChriPo92 you did explain it perfectly, no worries, I'll add a few workarounds for unification and will make sure to inform the user about it ) Will upload the fixes for HitBTC asap. The precedence is in the order of the arguments for `fetchOHLCV / fetch_ohlcv`, so: `symbol` first, then `timeframe`, then `since`, then `limit`.
