### ISSUE TITLE
lbank fetchOHLCV() not working for certain markets

### ISSUE THREAD

**Issue by kyletan7** [ccxt/ccxt#2835]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version: nodeJS 8.9.3
- CCXT version: 1.13.138
- Exchange: lbank
- Method: fetchOHLCV()

```
    let ohlcData = await new ccxt.lbank().fetchOHLCV('BCH/BTC', '1d');
```
does not work, but works for other pairs. I tried BCC for good measure, but no luck. Same case with VET. Could it be a naming conflict somewhere, since both coins have ambiguous names among various exchanges?

**Comment by kroitor** [comment]
This is an internal problem with lbank. I've double-checked and there's no symbol conflict.
They simply reply with ` {"result":"false","error_code":10008}` for BCH/BTC and some other pairs when you try to access their OHLCV. Code 10008 means *"This currency pair is not supported"*. You should address your request to lbank support. Hope this answers your question.
