### ISSUE TITLE
fetch all trades

### ISSUE THREAD

**Issue by rspadim** [ccxt/ccxt#2836]
hi guys, today we have fetch_trades() call that just call some method to return some trades
that's not nice, we should have a function to get trades from a date and to a date, something like

fetch_trades(2010-01-01 00:00:00, 2018-01-01 00:00:00)

this issue is to create a per exchange function to execute this kind of method

ideas:

def copy_trades(self, symbol, start, end):
    return a list of trades

**Comment by kroitor** [comment]
Hi! All methods fetching trades and orders have a `since` argument and a ` limit` argument – this is the most common set of arguments for pagination across exchanges, documented in the Manual: https://github.com/ccxt/ccxt/wiki

Let us know if it does not answer your question.

**Comment by rspadim** [comment]
but i'm checking some exchanges and since and limit don't send parameters correctly to exchanges api, it just "slice" the result from standard api call, example bitstamp

`

    def fetch_trades(self, symbol, since=None, limit=None, params={}):

        self.load_markets()

        market = self.market(symbol)

        response = self.publicGetTransactionsPair(self.extend({

            'pair': market['id'],

            'time': 'minute',

        }, params))

        return self.parse_trades(response, market, since, limit)
`

**Comment by rspadim** [comment]
hum, at ccxt side, what could be done to execute a "homogeneous" call to fetch_trades without using params and being exchange specific?

**Comment by rspadim** [comment]
hum fetch_Trades is not what i'm talking about if manual is ok:

"You can call the unified fetchTrades / fetch_trades method to get the list of most recent trades for a particular symbol."

most recent trades != explicit period of time

**Comment by kroitor** [comment]
*"most recent trades"* means the same as *"how the exchange in question defines what should be considered a recent trade"*.

**Comment by rspadim** [comment]
the "problem" is not filtering, the problem is more related to "please copy all trades from start of world to today" instead of "copy recent trades and filter it"

**Comment by kroitor** [comment]
Sorry, didn't quite get the last one, can you clarify, please?

**Comment by rspadim** [comment]
for example, we have trades starting at 2010-01-01, and ending "now()"

I want to copy trades from 2011-01-01 to 2012-01-01

**Comment by kroitor** [comment]
@rspadim 

> I want to copy trades from 2011-01-01 to 2012-01-01

Then you should start fetching with `limit` = 100-1000 trades `since` = `exchange.parse8601 ('2011-01-01 00:00:00'). If you have lots of trades, then you might need more than one fetch call (fetch sequentially) to paginate them all and "copy" them all to your storage or db. When the exchange does not support `since`, then your only option is to define an exchange-specific override with `params`.

**Comment by rspadim** [comment]
that's the idea, but today it's exchange specific (i must check if api have this option reading documentation)

**Comment by kroitor** [comment]
> i must check if api have this option reading documentation

You should really do that anyway ;)

> that's the idea, but today it's exchange specific

Yep, this is because we are a work in progress, so not all desired features can be supported right now and that is mostly due to exchanges' limitations, unfortunately.

**Comment by rspadim** [comment]
yeap i know it, the idea is make it predefined at ccxt api and with time make things work. that's why i'm considering a diferente function name "copy" instead of "fetch"

**Comment by kroitor** [comment]
> that's why i'm considering a diferente function name "copy" instead of "fetch"

We believe this function should be implemented in userland, because how you want to treat your rate limits depends on your user-specific tasks. Some users do not want multiple fetching calls, some other users are absolutely ok with it. So we can't decide for the user on how to implement this better for his user-specific needs. We avoid sending more than one HTTP request per ccxt call at all costs. One HTTP request = one fetch call. This would be impossible with the "copy" method to make it work uniformly in one call (one http request) for all exchanges because of their limitations.

**Comment by rspadim** [comment]
well probably we will have many implementations of this at userland

a "global" (generic) method could be done with these considerations explained in ccxt documentation, i don't see many calls as a problem if you explain that in documentation

this could be done at exchange base class:
"Then you should start fetching with limit = 100-1000 trades since = exchange.parse8601 ('2011-01-01 00:00:00'). If you have lots of trades, then you might need more than one fetch call (fetch sequentially) to paginate them all and "copy" them all to your storage or db. When the exchange does not supportsince, then your only option is to define an exchange-specific override withparams`."

using throttle() at each function call and return on errors, that's ok to make this something like 'interable'

i'm sure it will have exchange specific code to make it work (or return a NotSupported exception)

anyway useland apps will need this someday, making this inside ccxt or outside is more related to maintain the code at api side (i think it's possible to have this kind of stuff at api side, like many stock/futures/options marketdata/trading apis)

**Comment by jurgenmela28** [comment]
Hello, is there possible to fetch all my trades without passing any symbol param? I want to fetch all them in once

**Comment by kroitor** [comment]
@jurgenmela28 hi! In general CCXT does not require a `symbol` argument for `fetchMyTrades`, some exchanges will allow to fetch all trades without a symbol, and if it requires a symbol – the exchange will throw an `ArgumentsRequired` exception. This requirement is coming from the exchange APIs themselves, unfortunately, so we can't workaround this with a single HTTP request.

**Comment by frosty00** [comment]
It depends on the exchange, some exchanges let you fetch all your trades using `exchange.fetchMyTrades ()` without a symbol param. Other exchanges have an endpoint which requires a symbol so therefore ccxt throws an error if you try to call it without a symbol.
