### ISSUE TITLE
Is there any OTC supported exchange here?

### ISSUE THREAD

**Issue by XavierXIEXIN** [ccxt/ccxt#2841]
When I read the manual, I saw this:

>Besides making basic market and limit orders, some exchanges offer margin trading (leverage), various derivatives (like futures contracts and options) and also have dark pools, OTC (over-the-counter trading), merchant APIs and much more.

But I didn't find any exchange with OTC APIs supported, wonder if there any.
However, I did find huobipro OTC APIs somehow by checking it's website, it's like this:

[OTC_API_example](https://otc-api.huobi.pro/v1/otc/trade/list/public?country=0&currency=1&payMethod=0&currPage=1&merchant=1&coinId=1&tradeType=1)

Is there any OTC supported APIs like this here?

- OS: Windows 10
- Programming Language version: Python (Annaconda)
- CCXT version: 1.13.142
- Exchange: huobipro (OTC)
- Method: ticker (OTC)

**Comment by ttodua** [comment]
Some of the exchanges might have OTC, and even though they are not unified under our regular structure, they can be still used with our [implicit api](https://docs.ccxt.com/en/latest/manual.html#implicit-api). 
You can either search OTC-supported exchanges manually over google or etc, or also search for `otc` keyword throughout CCXT lib, to find out which exchanges support `otc`-related endpoints.
