### ISSUE TITLE
DSX fetch_order(orderID) error nodejs

### ISSUE THREAD

**Issue by vuivenao** [ccxt/ccxt#2842]
Hi @kroitor @blair 
Today I create a js script to make order in DSX.uk exchange. And I want to get status of my order for knowing filled or pending. I'm using node v10.0.0, ccxt v1.13.147
My code:
```
const order = await exchangeTrade.fetchOrder (uuid_1)
log (order)
```

And this is error:
```
UnhandledPromiseRejectionWarning: TypeError: this.privatePostOrderInfo is not a function
    at dsx.fetchOrder (/Users/macbook/node_modules/ccxt/js/liqui.js:714:35)
    at process._tickCallback (internal/process/next_tick.js:178:7)
```

Please help me! thanks!

**Comment by vuivenao** [comment]
Hi, DSX cancel order is error too.
```
let testCancelOrderDSX = async () => {
	const responseCancel = await exchangeTrade.cancelOrder (123456789)
	log (responseCancel)
}
```
Error: missing order_id

Please help me to resolve dsx problems. Thanks!

**Comment by ialpay** [comment]
I have the same issue with DSX cancel order. Please help us to resolve the issue. Best Regards.

**Comment by ongkhua** [comment]
Dear Devs, pls change the get_order_id_key to return "order_id" instead of "orderId".  This will fix this issue.

**Comment by ongkhua** [comment]
Dear devs,  I notice when calling create_order, the returned array orderId key is "order_id" instead of "orderId" as stated in their documentation.
Below is the actual returned array I got when calling create_order:

Array
(
    [info] => Array
        (
            [success] => 1
            [return] => Array
                (
                    [received] => 0
                    [remains] => 0.0001
                    [funds] => Array
                        (
                            [BTC] => 0
                            [USD] => xxxx
                            [EUR] => 0
                            [LTC] => 0
                            [RUB] => 0
                            [ETH] => 0
                            [GBP] => 0
                            [BCC] => 0
                            [BTG] => 0
                            [EURS] => 0
                            [USDT] => 0
                        )

                    [total] => Array
                        (
                            [BTC] => 0
                            [USD] => xxxx
                            [EUR] => 0
                            [LTC] => 0
                            [RUB] => 0
                            [ETH] => 0
                            [GBP] => 0
                            [BCC] => 0
                            [BTG] => 0
                            [EURS] => 0
                            [USDT] => 0
                        )

                    [order_id] => 210410969
                )

        )

    [id] => 
    [timestamp] => 1534569330254
    [datetime] => 
    [lastTradeTimestamp] => 
    [status] => open
    [symbol] => BTC/USD
    [type] => limit
    [side] => buy
    [price] => 5290.824
    [cost] => 0
    [amount] => 0.0001
    [remaining] => 0.0001
    [filled] => 0
    [fee] => 
)

**Comment by ongkhua** [comment]
DSX class does not have private-post-OrderInfo defined in the api array.  I cannot find DSX v1 api documents anymore, in v2 the end-point is /tapi/v2/order/status , but I can't add this endpoint as ccxt still uses v1 endpoints.  Anyone implementing v2 api for DSX ?

**Comment by kroitor** [comment]
@ongkhua yeah, DSX support is currently broken, because we don't have v2 yet. Afaik, nobody is working on it yet.

**Comment by ongkhua** [comment]
@kroitor I'm willing to contribute, but I'm more of a PHP guy than JS.  I understand that your code has to be written in JS then transpiled toPHP and Python, is that right ?

**Comment by ongkhua** [comment]
@kroitor I have implemented a bunch of basic functions for DSX v2, I have run lint and npm build, and tested js, and the generated php and python using your run-tests.js script, all testing show OK.

Here comes the noob question, sorry I haven't used Github before.
How do I create a branch?  I should have a branch then create a pull request, right ?

**Comment by kroitor** [comment]
@ongkhua 

- https://github.com/ccxt/ccxt/issues/824#issuecomment-350720844
- https://github.com/ccxt/ccxt/issues/2300#issuecomment-374008877

The workflow is:

1. You fork this repository on GitHub
2. Clone your fork from your GitHub to your working directory
3. Add your edits there
4. Push your edits to your GitHub fork
5. You will see a "Create a pull request" button in your forked repo on GitHub, from there it should be straightforward ;)

**Comment by ongkhua** [comment]
@kroitor I managed to fork, commit and made a pull request, but I just realized the API key for dsx in your keys.json is not working, I was using my own key for development.  It is also marked "skip" in keys.json.  How should I go about this?

**Comment by kroitor** [comment]
> How should I go about this?

You just commit a dsx.js, and no worries about the keys – we will use our own keys for testing upon merging. Thx so much!
