### ISSUE TITLE
New Exchange: bitpoint

### ISSUE THREAD

**Issue by k31ww475** [ccxt/ccxt#2843]
Hi plz add exchange bitpoint.
api url is here.

~~https://public.bitpoint.co.jp/bpj-api/api#~~ https://www.bitpoint.co.jp/

**Comment by kroitor** [comment]
https://www.coindesk.com/japanese-exchange-bitpoint-hacked-by-32-million-worth-in-cryptocurrencies

**Comment by frosty00** [comment]
cannot access
