### ISSUE TITLE
huobipro market order failed

### ISSUE THREAD

**Issue by jackyxie** [ccxt/ccxt#2848]
- OS: Ubuntu 16.04
- Programming Language version: PHP
- CCXT version: 1.13.147
- Exchange:huobipro
- Method:create_order
huobipro market buy order, the amount explain as total money to be buy, but ccxt will modify amout as type of amout.

**Comment by jackyxie** [comment]
Hope to support market order and IOC order

**Comment by kroitor** [comment]
> the amount explain as total money to be buy

Can you please help us translate this properly?

https://github.com/huobiapi/API_Docs/wiki/REST_api_reference#post-v1orderordersplace-pro%E7%AB%99%E4%B8%8B%E5%8D%95

> 限价单表示下单数量，市价买单时表示买多少钱，市价卖单时表示卖多少币

<img width="449" alt="screen shot 2018-05-15 at 18 23 54" src="https://user-images.githubusercontent.com/1294454/40066601-2ce4d604-586d-11e8-9018-5e86d73b9dbe.png">

Google translate says this:

<img width="1121" alt="screen shot 2018-05-15 at 18 26 25" src="https://user-images.githubusercontent.com/1294454/40066772-86cc6a6a-586d-11e8-9075-6e4dd12dd1f7.png">

Thx!

**Comment by jackyxie** [comment]
amount：
Limit order represents the number of coins you want to buy or sell. 
Market order,  in buy side, amount represent the total cost you want to buy; sell side, amount represents the total coins you want to sell.
