### ISSUE TITLE
CCXT v1.14, Bitfinex USD → USDT

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#2851]
Hi!

Due to multiple requests from users of Bitfinex, we have unified their `USD` ←→ `USDT` symbolic name. This was `USD` in CCXT 1.13, now it's `USDT` in CCXT 1.14 for Bitfinex. 

Because Bitfinex is one of major exchanges and this change might affect many users, please, note that starting from CCXT 1.14 all Bitfinex pairs are switched to `USDT`. `BTC/USD` is now `BTC/USDT`, `ETH/USD` is now `ETH/USDT` and so on...

This is a backward-incompatible change, please make sure to update your code accordingly.

Thx for using this library!

**Comment by Patafix** [comment]
Do you have a way to not have this feature ? (usd is not usdt...)

**Comment by kroitor** [comment]
@Patafix sure, add the following to the exchange in question:

```
const bitfinex = new ccxt.bitfinex ({
    'commonCurrencies': {
        'USDT': 'USDT',
        'USD': 'USDT',
    },
})
```

**Comment by Patafix** [comment]
Oh great thx ! Continue the greatwork

**Comment by kroitor** [comment]
@Patafix 

> (usd is not usdt...)

On Bitfinex, it is...

**Comment by Patafix** [comment]
USDT is not exactly one dollar

**Comment by kroitor** [comment]
> USDT is not exactly one dollar

Right, but Bitfinex does not tell you that they actually mean USDT under their USD symbol. So, even though it is not exactly one dollar, you're actually trading a USDT price, not a USD price there.

**Comment by Patafix** [comment]
Anyway i dont like the change but you're conception is so great that we can be both happy. So thank you

**Comment by kroitor** [comment]
That's just because they decided to use 3-symbol codes, their own fault... Most modern tokens won't fit in 3 symbols... So they have to abbreviate to their own nonstandard uncommon 3-letter codes. Why? Go figure.

**Comment by atisharma** [comment]
> Right, but Bitfinex does not tell you that they actually mean USDT under their USD symbol. So, even though it is not exactly one dollar, you're actually trading a USDT price, not a USD price there.

I don't agree that bitfinex USD should be USDT. You can actually withdraw / deposit USD with bitfinex.
There may be a market for USD/USDT (e.g. on Kraken). While you can convert freely to USDT, you are trading USD liabilities.

**Comment by kroitor** [comment]
@atisharma 

> I don't agree that bitfinex USD should be USDT.

We never said that.

> You can actually withdraw / deposit USD with bitfinex.

Yep, but you can only trade USDT there.

> There may be a market elsewhere for USD/USDT (e.g. on Kraken).

Kraken has both USDT and USD and those are not equal. You can trade USDT/USD pair there.

> But on bitfinex, you can convert freely to USDT, and you are trading USD liabilities.

Bitfinex uses USDT only for trading and can withdraw USD or USDT. Equalling USD to USDT is there not because we want it so, but for two reasons:
- bitfinex cannot have 4-letter symbols in their engine, thus they have to show USD for USDT
- because our users asked to do so, to actually reflect the reality with Bitfinex

So, we only do that in cases where this is true.

**Comment by zhouw** [comment]
Hello,

Bitfinex recently added a usdt/usd trading pair. How to deal with this?

I think it’s better to keep btc/usd as it is.

**Comment by kroitor** [comment]
@zhouw yep, because of that we will have to revert the mapping back in one of the upcoming versions.
https://support.bitfinex.com/hc/en-us/articles/360010505034-Fiat-on-Bitfinex
We will let you know when that happens.

**Comment by zhouw** [comment]
@kroitor thanks for the quick response! Looking forward to the update.

**Comment by kroitor** [comment]
Ok, please, be informed that starting from CCXT 1.18 all Bitfinex pairs are switched back to USD. BTC/USDT is now back to BTC/USD, ETH/USDT is now ETH/USD and so on...

This is a backward-incompatible change, please make sure to update your code accordingly.

If you want to keep the old substitution with the new version of the library, please do the following:

```
const bitfinex = new ccxt.bitfinex ({
    'commonCurrencies': {
        'USD': 'USDT',  # will not work for the USDT/USD pair
    },
})
```

Thx for using this library!

https://github.com/ccxt/ccxt/issues/4285

**Comment by siberianguy** [comment]
@kroitor Honestly, the current solution looks like a hack to me. They trade USDT on Bitfinex, there's no way around it, so a previous solution was right. We just needed to introduce a special mapping for USD/USDT. May be it's beyond of what ccxt is capable of now but it would be a right solution

**Comment by Gennttii** [comment]
Hi guys,

I am trying to trade USDT/USD OR UST/USD

With nodejs, in windows it works with USDT/USD and gives error if I use UST: 
`bitfinex does not have market symbol UST/USD`

But in my raspberry, Debian OS it says: 
`bitfinex does not have market symbol USDT/USD` , but it works with UST/USD

I was confused about this, maybe you can fix this, to make same in Windows and Linux...

**Comment by Gennttii** [comment]
Hi guys,

I am trying to trade USDT/USD OR UST/USD

With nodejs, in windows it works with USDT/USD and gives error if I use UST:
bitfinex does not have market symbol UST/USD

But in my raspberry, Debian OS it says:
bitfinex does not have market symbol USDT/USD , but it works with UST/USD

I was confused about this, I didn't have the same version, but now I have same version of nodejs in both devices, v10.15.3 and still this problem, maybe you can fix this, to make same in Windows and Linux...

**Comment by Gennttii** [comment]
Hi guys,

I am trying to trade USDT/USD OR UST/USD

With nodejs, in windows it works with USDT/USD and gives error if I use UST:
`bitfinex does not have market symbol UST/USD`

But in my raspberry, Debian OS it says:
`bitfinex does not have market symbol USDT/USD`
 but it works with UST/USD

I was confused about this, I didn't have the same version, but now I have same version of nodejs in both devices, v10.15.3 , also updated ccxt to latest version 1.18.475 to both , and still this problem, I have no idea why, but maybe you can fix this, to make same in Windows and Linux...

**Comment by kroitor** [comment]
> I have no idea why, but maybe you can fix this, to make same in Windows and Linux...

1. Make sure your version is up to date (1.18.473+) with the system you're testing with.
2. Use the proper `USDT/USD` symbol.

```JavaScript
const ccxt = require ('ccxt')
console.log (ccxt.version) // 1.18.473 or higher
const bitfinex = new ccxt.bitfinex ({ enableRateLimit: true })
;(async () => { await bitfinex.loadMarkets (); console.log (bitfinex.markets['USDT/USD']) }) ()
```
```
> { limits:
   { amount: { min: 10, max: 100000 },
     price: { min: 0.00001, max: 100000 },
     cost: { min: 0.0001, max: undefined } },
  precision: { price: 5, amount: 5 },
  tierBased: true,
  percentage: true,
  taker: 0.002,
  maker: 0.001,
  tiers:
   { taker:
      [ [Array],
        [Array],
        [Array],
        [Array],
        [Array],
        [Array],
        [Array],
        [Array],
        [Array],
        [Array],
        [Array] ],
     maker:
      [ [Array],
        [Array],
        [Array],
        [Array],
        [Array],
        [Array],
        [Array],
        [Array],
        [Array],
        [Array],
        [Array] ] },
  id: 'USTUSD',
  symbol: 'USDT/USD',
  base: 'USDT',
  quote: 'USD',
  baseId: 'UST',
  quoteId: 'USD',
  active: true,
  info:
   { pair: 'ustusd',
     price_precision: 5,
     initial_margin: '30.0',
     minimum_margin: '15.0',
     maximum_order_size: '100000.0',
     minimum_order_size: '10.0',
     expiration: 'NA',
     margin: true } }
```

**Comment by Gennttii** [comment]
I have latest version, and ratelimit
1.18.475
2019-04-18T14:57:50.976Z ExchangeError bitfinex does not have market symbol USDT/USD

I am using the symbol like this :
let symbol = 'USDT/USD' ;
let ticker = await bitfinex.fetchTicker ( symbol )

So I have same code in Windows 10 and Raspberry, but as I said, in Windows works with USDT/USD and in Raspberry works with UST/USD. All same code, all same versions of nodejs, ccxt...

**Comment by kroitor** [comment]
@Gennttii can you show your verbose request/response sequence from the Raspberry system?

**Comment by Gennttii** [comment]
Its working now man, sorry for bothering you, I didn't reload pm2 last time I changed the code  ..! Its working in both with USDT ..

**Comment by kroitor** [comment]
@Gennttii glad to know you've nailed it, thx for reporting back.
