### ISSUE TITLE
okCoin RequestTimeout, [Network Error] 502 not accessible from this location...

### ISSUE THREAD

**Issue by claufox** [ccxt/ccxt#2863]
- OS: Windows
- Programming Language version: PHP
- CCXT version: 1.13.102
- Exchange: OKcoin (USD)

- Method: fetch_ticker

Hi. I'm trying to use the following code:

```
try {

$key = 'xxx...'; 
$secret = 'xxx...';
$symbol = 'BTC/USD';

		$exchangescript = '\\ccxt\\okcoinusd';

		$exchange = new $exchangescript(array (
				'enableRateLimit' => false,					
				'apiKey' => $key,
				'secret' => $secret,					
				'origin' => 'foobar',
				'userAgent' => 'foobar',
				'verbose' => true
		));
		//$exchange->proxy = 'https://cors-anywhere.herokuapp.com/';
		$result = $exchange->fetch_ticker ($symbol);
	

} catch (\ccxt\NetworkError $e) {
    echo '[Network Error] ' . $e->getMessage () . "\n";
} catch (\ccxt\ExchangeError $e) {
    echo '[Exchange Error] ' . $e->getMessage () . "\n";
} catch (Exception $e) {
    echo '[Error] ' . $e->getMessage () . "\n";
}
```

**Note:
the keys and secret are set correctly**

but the message I get is this: 

> Operation timed out after 10000 milliseconds with 0 bytes received

bitfinex, kraken, bitstamp work ok.

only **okcoin (usd)** has this error.

**Comment by claufox** [comment]
No
Brazil

**Comment by claufox** [comment]
different kind of error: [Network Error] okcoinusd GET https://www.okcoin.com/v2/markets/products.do 502 not accessible from this location at the moment

**Comment by kroitor** [comment]
@claufox does it work normally in your browser from the same location?

**Comment by claufox** [comment]
Surfing https://www.okcoin.com/v2/markets/products.do logged
![www okcoin com 502 bad gateway](https://user-images.githubusercontent.com/37624951/40175280-fe83010e-59ad-11e8-879f-eabe6f29bf73.png)

**Comment by kroitor** [comment]
@claufox does their website work normally for you when you are simulating normal user behaviour (login, browse the exchange rates, logout)? I mean, not just the https://www.okcoin.com/v2/markets/products.do URL, but other pages as well ?

**Comment by claufox** [comment]
Yes. website work normally for normal user behaviour.

**Comment by valvesss** [comment]
Hey, @kroitor , could you please point me which code have you add to make it work?? I'm no long user of ccxt, I have created my own but I'm having this exactly issue. And the problem just happens with "withdraw.do", "userinfo.do" works fine. Thanks (From Brazil)

**Comment by kroitor** [comment]
@valvesss they changed their web urls:

Old https://www.okcoin.com/v2/markets/products.do 
↓
New https://www.okcoin.com/v2/spot/markets/products.do

**Comment by valvesss** [comment]
@kroitor thanks!!
