### ISSUE TITLE
missing withdrawHistory for Binance

### ISSUE THREAD

**Issue by plingampally** [ccxt/ccxt#2866]
Hi, could we add the `/wapi/v3/withdrawHistory.html` for Binance? The library currently exposes the `/wapi/v3/withdraw.html` but not the withdrawHistory. 

https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md

Thanks!

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L78
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L88
- https://github.com/ccxt/ccxt/blob/master/php/binance.php#L79
