### ISSUE TITLE
Cobinhood Invalid nonce

### ISSUE THREAD

**Issue by wahid** [ccxt/ccxt#2867]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10
- Programming Language version: Python 2.7 latest ccxt
- CCXT version:
- Exchange: Cobinhood
- Method: create_market_buy_order("PLY-BTC", 300)

`('\nRequest:', 'POST', 'https://api.cobinhood.com/v1/trading/orders', {'nonce': '1526520490', 'Content-type': 'application/json charset=UTF-8', 'Accept-Encoding': 'gzip, deflate', 'Authorization': '', 'User-Agent': 'python-requests/2.18.4'}, '{"trading_pair_id":"PLY-BTC","type":"market","side":"bid","size":"300.0"}')`

`ccxt.base.errors.ExchangeError: cobinhood {"request_id":"5c868f7da93fa47f","success":false,"error":{"error_code":"invalid_nonce"}}`

**Comment by kroitor** [comment]
Can you post a snippet of code that I can copypaste and launch to reproduce your problem (a short, but a complete program) ?
