### ISSUE TITLE
Duplicate asset symbol: EPC on Cryptopia and Exx

### ISSUE THREAD

**Issue by gabemahoney** [ccxt/ccxt#2869]
EPC is a ccxt symbol that exists on Cryptopia and Exx (and perhaps others). On Cryptopia EPC refers to ExperienceCoin. On Exx, EPC refers to Electronic PK Chain. 

Expected: CCXT asset symbols should refer to the same coin across exchanges.

OS: Mac
Programming Language version: Python 3.6.5
CCXT version: v1.13.125
Exchange: Cryptopia and Exx
Method: N/A

**Comment by frosty00** [comment]
make a PR:

add 

```
commonCurrencies: {
    'EPC': 'ExperienceCoin'
}
```

to cryptopia.js

_**YOU CAN MAKE A DIFFERENCE TOO**_
