### ISSUE TITLE
NodeJs proxy setting not works

### ISSUE THREAD

**Issue by kelvinkuo** [ccxt/ccxt#2876]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:centos6.8
- Programming Language version:nodejs 8.11.1
- CCXT version:1.14.10
- Exchange:huobipro okex binance
- Method:all

nodejs proxy not works, my code like below

```JS
let huobipro = new ccxt.huobipro({
    'proxies': {
        'http': 'http://127.0.0.1:1087',
        'https': 'http://127.0.0.1:1087',
    },
});

//...

try {
     let ticker = await huobipro.fetchTicker('BTC/USDT');
} catch (e) {
     console.error("fetchPairs err=%s", e.message);
}

```
and I get error message like
```
huobipro GET https://api.huobipro.com/v1/common/symbols request timed out (10000 ms)
```

But the python version works well on the same machine\same os\same proxy port

**Comment by kelvinkuo** [comment]
Anyone can help me?

**Comment by kelvinkuo** [comment]
@kroitor please help me

**Comment by kroitor** [comment]
```
let huobipro = new ccxt.huobipro({
    'proxies': {
        'http': 'http://127.0.0.1:1087',
        'https': 'http://127.0.0.1:1087',
    },
});
```

↑ This type of syntax is for Python only.

For Node you should use the fetch `agent`, as was answered here: https://github.com/ccxt/ccxt/issues/2480#issuecomment-379311459

**Comment by kelvinkuo** [comment]
Thanks.
