### ISSUE TITLE
WEX - createMarketSellOrder doesn't work

### ISSUE THREAD

**Issue by DmitryVil** [ccxt/ccxt#2878]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:Windows 10
- Programming Language version: python 3.6.5.
- CCXT version:1.14.10
- Exchange:WEX
- Method: createMarketSellOrder

Igor, good evening,

I tried to use createMarketSellOrder on the WEX and got answer "wex allows limit orders only"

Thx,
Dmitry

**Comment by kroitor** [comment]
https://wex.nz/tapi/docs#Trade

> You can only create limit orders using this method, but you can emulate market orders using rate parameters. E.g. using rate=0.1 you can sell at the best market price.

<img width="1158" alt="screen shot 2018-05-18 at 01 56 39" src="https://user-images.githubusercontent.com/1294454/40207742-c6f5fa70-5a3e-11e8-8abd-01c4a0dfe4ad.png">

**Comment by kroitor** [comment]
Also explained here: https://github.com/ccxt/ccxt/issues/1664#issuecomment-361933241
