### ISSUE TITLE
withdraw - [Exchange Error] cryptopia does not have currency code BTC

### ISSUE THREAD

**Issue by rsparrow** [ccxt/ccxt#2883]
- OS: OSX
- Programming Language version: JS
- CCXT version: 1.14.19
- Exchange: cryptopia
- Method: withdraw

Simalar to issue #2882 need to add `await this.loadMarkets ();` above line 615 of crypto-is.js.

**Comment by kroitor** [comment]
@rsparrow this was fixed in #2882 along the way ;)

**Comment by rsparrow** [comment]
Sorry thought I pull the latest... my bad.
