### ISSUE TITLE
parse_order_book causing TypeError

### ISSUE THREAD

**Issue by biotep** [ccxt/ccxt#2885]
- OS: Ubuntu
- Programming Language version: Python 3.6.4 |Anaconda
- CCXT version: __version__ = '1.14.10'
- Exchange: Kucoin
- Method: parse_order_book

Since some recent updates my script randomly failing at parse_order_book with kucoin:

```Traceback (most recent call last):
  File "test.py", line 449, in <module>
    loop.run_until_complete(main())
  File "/home/aries/anaconda3/envs/test/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "test.py", line 345, in main
    async for orderbook in poll():
  File "test.py", line 106, in poll
    k[exchange] = await exchange.fetch_order_book(symbol)
  File "/home/aries/anaconda3/envs/test/lib/python3.6/site-packages/ccxt/async/kucoin.py", line 333, in fetch_order_book
    return self.parse_order_book(orderbook, None, 'BUY', 'SELL')
  File "/home/aries/anaconda3/envs/test/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1029, in parse_order_book
    'bids': self.sort_by(self.parse_bids_asks(orderbook[bids_key], price_key, amount_key) if (bids_key in orderbook) and isinstance(orderbook[bids_key], list) else [], 0, True),
TypeError: argument of type 'NoneType' is not iterable
Exception ignored in: <bound method Exchange.__del__ of <ccxt.async.kucoin.kucoin object at 0x7fdd73b8afd0>>```

Can you please check?

thanks

**Comment by biotep** [comment]
...and my code snippet is here:

`async def poll():
    while True:
        k = {}
        await asyncio.sleep(2)
        try:
            for exchange in exchanges[:]:
                k[exchange] = await exchange.fetch_order_book(symbol)
        except (errors.ExchangeNotAvailable, errors.ExchangeError):
            log.error(' Ooops! %s', exchange.name, ' is not available.')
            k = {}
            yield k
        except errors.RequestTimeout:
            log.error("Exchange %s Timeout: ", exchange.name)
            k = {}
            yield k
        yield k`

**Comment by biotep** [comment]
```async def poll():
    while True:
        k = {}
        await asyncio.sleep(1.5)
        try:
            for exchange in exchanges[:]:
                k[exchange] = await exchange.fetch_order_book(symbol)
        except (errors.ExchangeNotAvailable, errors.ExchangeError):
            log.error(' Ooops! %s', exchange.name, ' is not available.')
            k = {}
            yield k
        except errors.RequestTimeout:
            log.error("Exchange %s Timeout: ", exchange.name)
            k = {}
            yield k
        yield k
```

**Comment by biotep** [comment]
Investigating further, I've noticed this occurring when 
```orderbook = response['data']```
returns with ```nul```

**Comment by Minege** [comment]
Just found that the same is happening with Kraken in Python

**Comment by kroitor** [comment]
@Minege plz check: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
