### ISSUE TITLE
How to create stoploss orders?

### ISSUE THREAD

**Issue by idokleinman** [ccxt/ccxt#2889]
I want to create stoploss (sell stop-limit) orders using the ccxt unified API, couldn't find how to do it.
Specifically in:
BitTrex, Binance, Kucoin, Poloniex

Any idea?

Thanks!

**Comment by kroitor** [comment]
- The Bittrex exchange does not support stop-loss orders
- The Kucoin exchange does not support stop-loss orders
- The Poloniex exchange does not support stop-loss orders
- For Binance you will have to call it with exchange-specific overrides:
  - https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods or
  - https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

Let us know if it does not answer your question.

**Comment by idokleinman** [comment]
AFAIK BitTrex do support stoploss they just have different terminology:
"conditional orders"
you have to set `CONDITION_TYPE` to `LESS_OR_EQUAL_TO` and define `TARGET` as the stop price. and the regular price as the limit price.
Is this not supported in ccxt?

**Comment by kroitor** [comment]
@idokleinman they do not offer any conditional orders with their official API: https://support.bittrex.com/hc/en-us/articles/115003723911

**Comment by tregismoreira** [comment]
@kroitor do you think it's already possible to create conditional orders via API for Bittrex? Look at the Order schema definition in their [api v1.1](https://bittrex.github.io/api/v1-1). There's a `conditional` parameter.

**Comment by kroitor** [comment]
@tregismoreira i don't see any mentions of how to place a conditional order in that doc... It's in the definition of historical data, but there's no such param in any method for creating orders. So, I don't know of such a possibility at the moment.

**Comment by tregismoreira** [comment]
@kroitor what would be a good approach to bypass this limitation? Listen the ticker through websocket then, once the price hits, place the sell order (at market price)?

**Comment by kroitor** [comment]
@tregismoreira to be honest, i don't think you can emulate it on the user side as well as it can be done by the exchange engine itself, because there will be price slippages due to networking latencies regardless of the underlying protocols, be it rest or ws. But if you can tolerate some errors, you can then listen to a ws orderbook deltas and act when the depth is good for you.

**Comment by tregismoreira** [comment]
@kroitor yes, I know the risks. In fact I've been trying to find the most safe/guaranteed way to do this for awhile. This is the closest I could get to it. If you have any other suggestion, I appreciate. Thanks for your feedback.
