### ISSUE TITLE
How to use cctx with dynamic exchange name?

### ISSUE THREAD

**Issue by smartDex** [ccxt/ccxt#2894]
Hi, All.
I am using cctx 1.10.944 for my portfolio page.
programming language Typescript 2.6.2

It's really great library for me.
But I have an issue when I try to use it with a dynamic exchange name.
It needs for the portfolio page.

for example:
const exchangeName = 'binance';
let cctx = new cctx.exchangeName({
     apiKey:  "...",
     secret:  "..."
});

Is it possible?
Can I initialize the cctx exchange with dynamic name?
I've tried like this:
const opt = {
     apiKey:  "...",
     secret:  "..."
};
 const exchange = Object.create(window[exchangeType].prototype);
      exchange.constructor.apply(exchange, opt);
      // const hotExchange = new DynamicClass(exchangeType, opt);
      // withdraw
      const withdrawResult = await exchange.withdraw (token, amountFromExchange, addressTo);

I hope to take a look at my code and let me know your idea.

**Comment by kroitor** [comment]
Thanks, @jvandenaardweg !

**Comment by Atem18** [comment]
FYI in Python, you do:
```
exchange_name = 'binance'
exchange = getattr(ccxt, exchange_name)

ccxt_ex = exchange({
  apiKey: "...",
  secret: "..."
})
```

**Comment by glencjones** [comment]
const CCXT = ccxt as any; // Hack!        
const exchange = new CCXT[id]({ 'enableRateLimit': true }) as ccxt.Exchange;

See ts examples in git.
