### ISSUE TITLE
Is it possible to associate CCXT and AmpPHP to achieve HTTP concurrency call?

### ISSUE THREAD

**Issue by DaveMG3** [ccxt/ccxt#2895]
Hi,

It is not an issue but a question asked also on SO : 
https://stackoverflow.com/questions/50427385/achieve-concurrent-http-call-with-ccxt-in-php

Is it possible to associate CCXT and AmpPHP to achieve HTTP concurrency call?

**Comment by kroitor** [comment]
> Is it possible to associate CCXT and AmpPHP to achieve HTTP concurrency call?

In general, yes. However, we also have this related proposal: https://github.com/ccxt/ccxt/issues/1435
The thing is: there's 100500 other frameworks like AmpPHP, and we are not sure which one is better yet. Adding async support to the PHP version is on our roadmap.

**Comment by kroitor** [comment]
P.S. We are mostly looking into Promise-based interfaces like this one:https://github.com/guzzle/promises

**Comment by DaveMG3** [comment]
Ok so for now calling different exchanges in parallel is easier by turning to Javascript otherwise we need to modify CCXT library?...it was my fear , i thought we could associate it some concurrency code for our ForEach Loop

**Comment by kroitor** [comment]
@DaveMG3 

> Ok so for now calling different exchanges in parallel need use to to Javascript otherwise we need to modify CCXT library from what i understand?

Well, not really. You need to subclass the exchange in question and override the fetch method to use your own async implementation in PHP. You can also use multiple instances of CCXT classes in your threads/async routines concurrently, so it all boils down to how you sync your concurrent requests in userland. But you're right, the async functionality is not built into the PHP version at the moment. We're working on it.

**Comment by DaveMG3** [comment]
@kroitor , sorry to ask but can you give me some insight on your idea of creating different threads with different CCXT instances?

I would like to create a different thread for each exchange instance , each will call their different markets in parallel but digging into it for the last 4h i only see the solution of going to modify the fetch method of CCXT library with curl_multi, xampp or guzzle for having different concurrent http calls. 
PHP natively doesnt enable multithreading and I cannot find in the litterature a non heavy solution for putting my ForEach loop on multithread.
Maybe a custom promise wrapping my CCTX call, which can be provided then to a library like AmpPhP or React?

 As these call are managed by my server i was thinking PHP version was ok to use but i am now wondering if the quickest is not switching to the python or javascript ones.

**Comment by viktorius007** [comment]
I have had some success using the amphp/parallel-functions library, and whilst it does work, both memory and CPU usage go through the roof (6 cores 50% busy vs almost no CPU usage, memory 6+Gb vs <1Gb) which I believe might be duplication of the PHP environment for each thread.

There are many limitations such as having to use closures which need to be serializable, and the big problem comes when trying to pass an array of instantiated exchange objects.  That basically froze the system when not done right (60Mb array).  Interestingly, amphp/parallel-functions will use either processes or pthreads under the hood without any user intervention, however I found the results to be identical (I was secretly hoping that installing php-zts and activating pthreads would solve my problems)

I am still not happy with my solution and am wondering how many of the difficulties are from using the amphp library that might be solved by just going direct to pthreads or something else instead.

@kroitor The other issue I'm wondering is whether the instantiated exchanges can honour the rateLimit if they are being duplicated for each pthread?

I'm really a beginner, I have less than 6 weeks of tinkering experience with PHP and CCXT and am still struggling with the whole idea of async vs parallel, so if anyone has made progress in this area of using ccxt to make multiple simultaneous calls I would be very happy to hear about your experience.

**Comment by kroitor** [comment]
Hey, sorry for not replying too often. 

> @kroitor, sorry to ask but can you give me some insight on your idea of creating different threads with different CCXT instances?

Yep, will add a few examples on this asap.

> @kroitor The other issue I'm wondering is whether the instantiated exchanges can honour the rateLimit if they are being duplicated for each pthread?

See what a `mutex` or `atomic increment` is.

I'll look into what could be done in the library with concurrency + PHP and will get back to you on this subject with some general solution for this. Hopefully, soon.

**Comment by langabi** [comment]
I've just submitted PR #7079 which adds async support to ccxt library, modelled on the Python async support, and compatible with the ccxt.pro approach. It uses ReactPHP+RecoilPHP which uses the 'yield' keyword behave similarly to 'await' in Python. Hopefully gets the job done -- benefit is that the changes are fairly minimal compared with base ccxt, unlike rewriting the entire library in promises.
