### ISSUE TITLE
huobipro withdraw return api-signature-not-valid error

### ISSUE THREAD

**Issue by radarxc** [ccxt/ccxt#2896]
- OS: Win10
- Programming Language version: Python 3.5.4
- CCXT version: 1.14.25
- Exchange: huobipro
- Method: withdraw

When I tested huobipro withdraw, I got 'signature not valid' response as below:

> ccxt.base.errors.ExchangeError: huobipro {"err-msg":"Signature not valid: \u6821\u9a8c\u5931\u8d25","status":"error","data":null,"err-code":"api-signature-not-valid"}

Meanwhile, huobipro fetch_balance worked fine. So I think it is not a key pair issue. And I also tested withdraw same target address by other market, it also worked fine. So the address should be good.

Attach my testing code below, hope it will help:

    f_m = "huobipro"
    t_m = "okex" 
    currency = "ZEC"

    exchange = getattr(ccxt, f_m)({'apiKey': apiconfig['key'], 'secret': apiconfig['secret'], 'nonce': ccxt.Exchange.milliseconds})
    addresses = get_market_addresses(t_m) #get addresses map
    exchange.load_markets()
    response = exchange.fetch_balance()
    print(response) #fetch balance, worked
    response = exchange.withdraw(currency, 1, addresses[currency]['address'], 'Test withdraw', {})
    print(response) #withdraw, failed

Attach traceback:

> Traceback (most recent call last):
  File "testing2.py", line 36, in <module>
    withdraw_test()
  File "testing2.py", line 33, in withdraw_test
    response = exchange.withdraw(currency, 1, addresses[currency]['address'], 'Test withdraw', {})
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\ccxt\huobipro.py", line 661, in withdraw
    response = self.privatePostDwWithdrawApiCreate(self.extend(request, params))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\ccxt\base\exchange.py", line 306, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\ccxt\base\exchange.py", line 303, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\ccxt\base\exchange.py", line 383, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, None, self.last_http_response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\ccxt\huobipro.py", line 727, in handle_errors
    raise ExchangeError(feedback)
ccxt.base.errors.ExchangeError: huobipro {"err-msg":"Signature not valid: \u6821\u9a8c\u5931\u8d25","data":null,"err-code":"api-signature-not-valid","status":"error"}

**Comment by radarxc** [comment]
I find when I change withdraw's 'tag' parameter as None, this issue is fixed. I am not sure what happen, but it works fine on other market with tag parameter.

**Comment by kroitor** [comment]
@radarxc you're not using the withdraw method properly. The `tag` is not an arbitrary user string, it is a wallet identifier which should only be set if you're withdrawing a currency that requires the tag for addressing. Let us know if it does not answer your question.

**Comment by radarxc** [comment]
@kroitor 
got you. Thank you very much. I should read document more carefully.
