### ISSUE TITLE
Why timeInForce cannot be set?

### ISSUE THREAD

**Issue by standup75** [ccxt/ccxt#2905]
I am surprise to see that, although a lot of exchange offer the timeInForce setting, the code is always setting a default for it, shouldn't it be an argument, or at least an option to put in params?

    /github/ccxt/js/binance.js:
      649              order = this.extend (order, {
      650                  'price': this.priceToPrecision (symbol, price),
      651:                 'timeInForce': 'GTC', // 'GTC' = Good To Cancel (default), 'IOC' = Immediate Or Cancel
      652              });
      653          } else if (type === 'limit_maker') {

    /github/ccxt/js/hitbtc.js:
      728              order['price'] = this.priceToPrecision (symbol, price);
      729          } else {
      730:             order['timeInForce'] = 'FOK';
      731          }
      732          let response = await this.tradingPostNewOrder (this.extend (order, params));

    /github/ccxt/js/hitbtc2.js:
      848              request['price'] = this.priceToPrecision (symbol, price);
      849          } else {
      850:             request['timeInForce'] = 'FOK';
      851          }
      852          let response = await this.privatePostOrder (this.extend (request, params));

    /github/ccxt/php/binance.php:
      650              $order = array_merge ($order, array (
      651                  'price' => $this->price_to_precision($symbol, $price),
      652:                 'timeInForce' => 'GTC', // 'GTC' = Good To Cancel (default), 'IOC' = Immediate Or Cancel
      653              ));
      654          } else if ($type === 'limit_maker') {

    /github/ccxt/php/hitbtc.php:
      729              $order['price'] = $this->price_to_precision($symbol, $price);
      730          } else {
      731:             $order['timeInForce'] = 'FOK';
      732          }
      733          $response = $this->tradingPostNewOrder (array_merge ($order, $params));

    /github/ccxt/php/hitbtc2.php:
      849              $request['price'] = $this->price_to_precision($symbol, $price);
      850          } else {
      851:             $request['timeInForce'] = 'FOK';
      852          }
      853          $response = $this->privatePostOrder (array_merge ($request, $params));

    /github/ccxt/python/ccxt/binance.py:
      629              order = self.extend(order, {
      630                  'price': self.price_to_precision(symbol, price),
      631:                 'timeInForce': 'GTC',  # 'GTC' = Good To Cancel(default), 'IOC' = Immediate Or Cancel
      632              })
      633          elif type == 'limit_maker':

    /github/ccxt/python/ccxt/hitbtc.py:
      718              order['price'] = self.price_to_precision(symbol, price)
      719          else:
      720:             order['timeInForce'] = 'FOK'
      721          response = self.tradingPostNewOrder(self.extend(order, params))
      722          return self.parse_order(response['ExecutionReport'], market)

    /github/ccxt/python/ccxt/hitbtc2.py:
      842              request['price'] = self.price_to_precision(symbol, price)
      843          else:
      844:             request['timeInForce'] = 'FOK'
      845          response = self.privatePostOrder(self.extend(request, params))
      846          order = self.parse_order(response)

    /github/ccxt/python/ccxt/async/binance.py:
      629              order = self.extend(order, {
      630                  'price': self.price_to_precision(symbol, price),
      631:                 'timeInForce': 'GTC',  # 'GTC' = Good To Cancel(default), 'IOC' = Immediate Or Cancel
      632              })
      633          elif type == 'limit_maker':

    /github/ccxt/python/ccxt/async/hitbtc.py:
      718              order['price'] = self.price_to_precision(symbol, price)
      719          else:
      720:             order['timeInForce'] = 'FOK'
      721          response = await self.tradingPostNewOrder(self.extend(order, params))
      722          return self.parse_order(response['ExecutionReport'], market)

    /github/ccxt/python/ccxt/async/hitbtc2.py:
      842              request['price'] = self.price_to_precision(symbol, price)
      843          else:
      844:             request['timeInForce'] = 'FOK'
      845          response = await self.privatePostOrder(self.extend(request, params))
      846          order = self.parse_order(response)

    12 matches across 12 files

**Comment by standup75** [comment]
I would be happy to submit a pr with

    order['timeInForce'] = params.timeInForce || 'FOK'

**Comment by kroitor** [comment]
> I would be happy to submit a pr with

We welcome all contributions, however, please make sure to read this first: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

> I am surprise to see that, although a lot of exchange offer the timeInForce setting, the code is always setting a default for it, shouldn't it be an argument, or at least an option to put in params?

If you look carefully enough a few lines below, you'll see that you can override the defaults with an option in params, exactly, as described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L656

Duplicate: https://github.com/ccxt/ccxt/pull/1894
