### ISSUE TITLE
New Exchange: CoinStock

### ISSUE THREAD

**Issue by EarlVadim** [ccxt/ccxt#2909]
**CoinStock**

WEB - https://coinstock.me
API  - https://coinstock.me/documents/api_v2#
Logo black - https://www.dropbox.com/s/x8q5hldmp6sfoxz/logo-CS.png?dl=0
Logo white - https://www.dropbox.com/s/rnxocc504o9brht/logo-50px.png?dl=0
Country - Seychelles, Lithuania

Our API is fully clone of **yunbi.com** and **graviex** #2538
Tnx.

**Comment by EarlVadim** [comment]
Info updated.

**Comment by kroitor** [comment]
The exchange website is down by now. Sorry.
