### ISSUE TITLE
Incorrect cost for cobinhood

### ISSUE THREAD

**Issue by danieldourado** [ccxt/ccxt#2913]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Ubuntu
- Programming Language version: Python
- CCXT version: 1.13.38
- Exchange: Cobinhood
- Method: parseTrade

The 'price' parameter Cobinhood returns is the price you sent to the exchange. But the real price the order was filled may not always be the price you proposed to the order. The real price for the order executed is the parameter 'eq_price'.

https://github.com/ccxt/ccxt/pull/2912

**Comment by kroitor** [comment]
Fixed in #2912. Thank you so much!
