### ISSUE TITLE
Buy and sell-order in Javascript with node.js - A beginners question to ccxt

### ISSUE THREAD

**Issue by Lorias** [ccxt/ccxt#2917]
A question about how to use ccxt with node.js and the HitBTC exchange.

How can I use ccxt to just place a simple buy and sell-order in Javascript with node.js?
Are there any node.js examples here in the ccxt repository that I've maybe missed (because I could
not find any detailed code-snippets that can make a newbee to ccxt like I am, to accomplish
it easy).

As far as I could figure out a code should look like similar to:
_____________________________________________________________________

const ccxt      = require ('../../ccxt.js');
async function simpleTrade(checkCase, ThisAmount, ThisPrice, ThisCurrency){

    // instantiate the exchange
    let exchange = new ccxt.hitbtc2  ({
        "apiKey": "b6aad581670b30fb25d1c91cdbe8ca5c",
        "secret": "fa394ced37a488f9b5826a2d9ce39ae3",
        "enableRateLimit": true,
    }) //-- exchance end

    try {
       if(checkCase == "SELL"){
           let SellOrder = await exchange.HERE_MUST_BE_THE_SELL_OBJECT();
       }
       if(checkCase == "BUY"){
           let BuyOrder = await exchange.HERE_MUST_BE_THE_BUY_OBJECT();
       }
    } //--try end
} //--function end
//--SELL--
simpleTrade("SELL", 300, 0.75, XRP/USDT);
//--BUY--
simpleTrade("BUY", 820, 0.68, XRP/USDT);

_____________________________________________________________________

Any help
that can make this or a similar code work
is highly appreciated!!!

Many thanks in advance!!!

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki/Manual#trading
- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders
- https://github.com/ccxt/ccxt/tree/master/examples

Let us know if it does not help.

**Comment by kroitor** [comment]
```JavaScript
const ccxt = require ('ccxt')

// no need to create it upon every call to simpleTrade

// instantiate the exchange
let exchange = new ccxt.hitbtc2  ({
    "apiKey": "b6aad581670b30fb25d1c91cdbe8ca5c",
    "secret": "fa394ced37a488f9b5826a2d9ce39ae3",
    "enableRateLimit": true,
}) //-- exchance end

async function simpleTrade(checkCase, ThisAmount, ThisPrice, ThisCurrency) {

    const symbol = ThisCurrency
    const type = 'limit'
    const amount = ThisAmount
    const price = ThisPrice
    const side = checkCase.toLowerCase () // side is lowercase 'buy' or 'sell'

    try {
        let order = await exchange.createOrder (symbol, type, side, amount, price);
    } catch (e) {
        console.log (e.constructor.name, e.message)
        throw e
    }
} //--function end

//--SELL--
simpleTrade("SELL", 300, 0.75, XRP/USDT);
//--BUY--
simpleTrade("BUY", 820, 0.68, XRP/USDT);
```

**Comment by kroitor** [comment]
P.S. Please recreate your API keys and delete the old keys, otherwise you might have lose funds. Do not publish your credentials.

**Comment by Lorias** [comment]
WOW, kroitor this was a response in nearly lightspeed!!!!!!!!!!!!!
I'm deeply impressed!!!!!!!
Thank you veeeeery much!
I'll try this code later!
