### ISSUE TITLE
What methods are used to get order history for OKEX?

### ISSUE THREAD

**Issue by DaniilLeksin** [ccxt/ccxt#2919]
- OS: OS X 10.13
- Programming Language version: python 3.6
- CCXT version: 1.14.25
- Exchange: Okex
- Method: fetchOrders

I'm trying to get order history with `fetch_ohlcv()` and `fetch_orders()` but it returns an empty list. (I've created some orders before).
Also, I was trying to mokeypatch methods `fetch` and `fetch2` from `Exchanges` class. Result is the same - an empty list.

In my current okex account I've found that web version uses `GET 'https://www.okex.com/v2/spot/order/history'` endpoint to get the order history.

I've used API v1 endpoints for the work, maybe this API is not actual for now. 
Does anybody knows about API V2 documentation? OR How can I check my order History via CCXT?

Many thanks.

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki/Manual#querying-orders
