### ISSUE TITLE
Binance rateLimit is ignored

### ISSUE THREAD

**Issue by timsazon** [ccxt/ccxt#2922]
- OS: Ubuntu 18.04
- Programming Language version: Python 3.6.5
- CCXT version: 1.14.48
- Exchange: Binance (maybe more)

There is a problem with rateLimit in Binance class. Probably it has been ignored and therefore DDoS Protection occurs.

Based on the example: https://github.com/ccxt/ccxt/blob/master/examples/py/async-generator-basic.py
```
import asyncio
import os
import sys
import ccxt.async as ccxt

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

exchange = ccxt.binance({
    'enableRateLimit': True
})


async def poll():
    while True:
        yield await exchange.fetch_tickers()


async def main():
    async for ticker in poll():
        print(ticker)


asyncio.get_event_loop().run_until_complete(main())
```

**Comment by kroitor** [comment]
Duplicate:
- https://github.com/ccxt/ccxt/issues/2810
- https://github.com/ccxt/ccxt/issues/1223
- https://github.com/ccxt/ccxt/issues/1855
- https://github.com/ccxt/ccxt/issues/1027
- https://github.com/ccxt/ccxt/issues/1365
- https://github.com/ccxt/ccxt/issues/870
