### ISSUE TITLE
ccxt doesn't support market orders for Poloniex

### ISSUE THREAD

**Issue by DmitryVil** [ccxt/ccxt#2927]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10
- Programming Language version: python 
- CCXT version:1.14.44
- Exchange: Poloniex
- Method: createOrder()

Dear Igor,

I tried to use createOrder method for market order for Poloniex.
As a result of createOrder() I got an answer that Poloniex doesn't support market-type orders.
I wrote to Poloniex support and it explained that: **"Trades can either be made by a maker or a taker, meaning the maker would be someone who has made an order available for purchase or sell, and the taker would be the person who is fulfilling that order. Any user on Poloniex can be either a maker or taker."**
So it looks like a mistake.

Thank you in advance,
Dmitry

**Comment by kroitor** [comment]
Hey) This is not your first time posting ) You should know that for whatever problem you think it is, we always ask for your code + verbose request + response ;)

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties
- https://github.com/ccxt/ccxt/wiki/Manual#market-orders

```
mbp:ccxt igorkroitor$ python examples/py/cli.py poloniex has
{'CORS': False,
 'cancelOrder': True,
 'cancelOrders': False,
 'createDepositAddress': True,
 'createLimitOrder': True,
 'createMarketOrder': False, ←---------------------------- ooops
 'createOrder': True,
 'deposit': False,
 'editOrder': True,
 'fetchBalance': True,
 'fetchClosedOrders': 'emulated',
 'fetchCurrencies': True,
 'fetchDepositAddress': True,
 'fetchFundingFees': False,
 'fetchL2OrderBook': True,
 'fetchMarkets': True,
 'fetchMyTrades': True,
 'fetchOHLCV': True,
 'fetchOpenOrders': True,
 'fetchOrder': 'emulated',
 'fetchOrderBook': True,
 'fetchOrderBooks': False,
 'fetchOrders': 'emulated',
 'fetchTicker': True,
 'fetchTickers': True,
 'fetchTrades': True,
 'fetchTradingFees': True,
 'privateAPI': True,
 'publicAPI': True,
 'withdraw': True}
mbp:ccxt igorkroitor$
```

**Comment by DmitryVil** [comment]
Thank you for your answer Igor,
I used createOrder method:
_________________________________________________________________________________________
    try:
        msg = asyncio.get_event_loop().\
            run_until_complete(poloniex.createOrder(poloniex.symbols[0], 'market', 'sell', 100, None))
    except BaseException as err:
        print(poloniex.name, '!!!!!!!!!!!!!!!!', err)
    finally:
        pass
_________________________________________________________________________________________
I got a response:  **poloniex allows limit orders only**

**Comment by kroitor** [comment]
> I got a response: poloniex allows limit orders only

Well, it's a sad response, but true. 

I guess, this issue is resolved now, right? )

**Comment by kroitor** [comment]
@DmitryVil but hey, here's the good news: you can emulate market orders with limit orders as described here: https://github.com/ccxt/ccxt/issues/1664#issuecomment-361933241

**Comment by DmitryVil** [comment]
Yes, Igor thank you for your advice.
But if it possible to fix this method, I would wait for it.
What do you think?

**Comment by kroitor** [comment]
> But if it possible to fix this method, I would wait for it.

It is not possible to fix it, they just don't have it. But you can workaround that limitation. Yet still, waiting for it is not your best option – you should not wait – you should do it )

> What do you think?

I think you should read the comment linked above very carefully to realize that whatever purpose you needed market orders for – you can do that same thing successfully having just the limit orders and limit orders are supported everywhere. ;)

**Comment by DmitryVil** [comment]
Igor, please clarify me,
Do you mean that API of Poloniex doesn't support market orders? Correct?

**Comment by kroitor** [comment]
> Do you mean that API of Poloniex doesn't support market orders? Correct?

Yep. They don't have market orders in their API at all. But you can do all the same things with limit orders, so it's not a very big deal.
