### ISSUE TITLE
OS: Python   CCXT Version: 1.14.52   Exchange: Bitmex   Method: Fetch_ticker 

### ISSUE THREAD

**Issue by Iolheal** [ccxt/ccxt#2928]
First of all massive fan of your work.

Fetch_ticker isn't currently working for Bitmex and I think "quotes = self.publicGetQuoteBucketed(request)" is the cause of the problem.
I've ran through the code line by line and filtering out all references to quotes with placeholder variables seems to work.

Cheers

**Comment by kroitor** [comment]
Hi! )

https://github.com/ccxt/ccxt/wiki/FAQ#i-am-calling-a-method-and-i-get-an-error-what-am-i-doing-wrong ;)

**Comment by kroitor** [comment]
I'm receiving 403 from that endpoint at the moment.

These do not work:
- https://www.bitmex.com/api/v1/quote/bucketed?symbol=XBTUSD&binSize=1d&partial=true&count=1&reverse=true
- https://www.bitmex.com/api/v1/quote/bucketed?symbol=XBTUSD&binSize=1d

**Comment by kroitor** [comment]
https://twitter.com/mana_community/status/998445501484707840

20 May 2018:

> Share information gained in the community regarding API errors confirmed in BitMEX! What is going on is a Quote error, only the "fetch_ticker" is affected by CCXT, it has no effect on "fetch_ohlcv"! Also, it is said that these restrictions are temporary measures against obstacles and are ready for cancellation!

<img width="582" alt="screen shot 2018-05-23 at 12 32 33" src="https://user-images.githubusercontent.com/1294454/40416254-8022ddd4-5e85-11e8-9a6c-c18e670d3384.png">

**Comment by Iolheal** [comment]
Thanks for the swift reply, Ill add the verbose request and response next time.
I guess waiting this one out is probably the best thing as it hopefully reverts to normal.

**Comment by kroitor** [comment]
@lolheal no need to wait, I've added a `fetchTickerQuotes` option to it, it is true by default, to be consistent with the old behaviour, but if you don't care about current bid and ask, then you set `bitmex.options['fetchTickerQuotes'] = false`, and it will work normally, but without bid and ask prices. That is, starting from ccxt version 1.14.56 (will be available in 5-10 minutes)
