### ISSUE TITLE
Response for preflight is invalid (redirect)

### ISSUE THREAD

**Issue by rhrahul** [ccxt/ccxt#2931]
Hello,

I am geting this error,
Response for preflight is invalid (redirect)

while calling private methods in bittrex.

- OS: Windows 10
- Programming Language version: Angular 4
- CCXT version: Latest
- Exchange: Bittrex
- Method: All Private Methods (For Example Placing Order, Fetching Balance)

Please help !!!

Thanks

**Comment by rhrahul** [comment]
![error](https://user-images.githubusercontent.com/35340981/40428496-127c13ca-5ebe-11e8-8715-63cb92e9e059.png)

**Comment by kroitor** [comment]
You don't need to use the CORS proxy with Bittrex, because they support CORS in their API by default.
Let us know if removing the CORS proxy for Bittrex does not help.

**Comment by rhrahul** [comment]
Hi,
I tried with removing proxy, and now I am getting this error,

![error2](https://user-images.githubusercontent.com/35340981/40478455-b8da7d3a-5f66-11e8-99a5-48b76e35b46c.png)

**Comment by kroitor** [comment]
<img width="254" alt="screen shot 2018-05-24 at 22 33 04" src="https://user-images.githubusercontent.com/1294454/40509514-74939b0c-5fa2-11e8-83f0-567245e96a35.png">

↑ This particular piece of URL somehow got appended by your framework to the actual requested URL, it does not actually belong there, you're probably using some kind of proxying or tunelling on port 8100, this can ruin the access patterns. Looks like the ionic platform catches the XHR calls from your browser. Can you check on that?
