### ISSUE TITLE
Cancel requests use case

### ISSUE THREAD

**Issue by morzyns** [ccxt/ccxt#2936]
In general: I do pooling lets say every 2 sec for fetchTickers, then i cancel and do fetchTicker.
I see some request coming up more time then timeout (maybe because of retry policy). 

Is this a good idea to add additional parameter to the methods with cancel signal object?

**Comment by kroitor** [comment]
Sorry, I didn't really get the question, can you clarify, please? Which *cancel signal object* do you mean?

>  I do pooling lets say every 2 sec for fetchTickers,

Exchanges will not like it, btw. You should either poll fetchTicker for a particular pair, or they might impose strict rate limits on fetchTickers call. For example, Binance will ban you if you poll fetchTickers once every two seconds, as they allow not more than once in approx 1 minute, explained here: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#limits

**Comment by morzyns** [comment]
So if you do 
`
exchange.enableRateLimit = true;`
it will just delay / defer the function calls, but if you do polling as i do the rate limit option will queue the function calls right?. That's what i observed in practice. I understand it's quite necessary to have it but at some point i think i need to do rate limit manually because it's putting additional calls to wait in the queue, and the queue calls will be executing as long as the queue of the requests exists.

If i could cancel already made function calls / empty the queue it would be more efficient for the described use case.

**Comment by kroitor** [comment]
> So if you do `exchange.enableRateLimit = true;` it will just delay / defer the function calls, but if you do polling as i do the rate limit option will queue the function calls right?

Yep... but not quite ;) If you enableRateLimit it will do the basic rate limiting as you described, however, it is built on top of tokenBucket which is a much more flexible approach, with bursts of requests,  variable request costs and much more. More about it here: https://github.com/ccxt/ccxt/issues/2810#issuecomment-388117106

> If i could cancel already made function calls / empty the queue it would be more efficient for the described use case.

Yep, this is possible, however, this is mostly done in userland now, you will have to override a few methods for that and will have to define your rate-limiting strategy. Hope this answers your question.

**Comment by morzyns** [comment]
Thanks @kroitor. That's what i need to know.
