### ISSUE TITLE
Significant price discrepancy between GDAX API & GDAX front-end

### ISSUE THREAD

**Issue by flavioespinoza** [ccxt/ccxt#2938]
Note the price discrepancy shown between GDAX API and their trading platform.

API using CCXT
![screen shot 2018-05-23 at 12 18 50 pm](https://user-images.githubusercontent.com/2214913/40443805-a413f06c-5e84-11e8-9bbd-84b32ecfee90.png)

https://www.gdax.com/orders/fills/BTC-USD
![screenshot-www gdax com-2018 05 23-12-23-29](https://user-images.githubusercontent.com/2214913/40443828-b801199c-5e84-11e8-88c1-8c3b42848165.jpeg)

I placed a LIMIT SELL order @ $7369, but because it was a limit order it sold at the higher/better price of  $7446.  My balance reflects this, so it did sell at the better price, but it is not coming through when I fetch order history. 

This is the order object returned in my gdax.fetchOrderHistory() array.

```javascript

let order = {
               "id": "86b82b5d-7224-4daa-9b9f-04800c558e3d",
               "info": {
                 "id": "86b82b5d-7224-4daa-9b9f-04800c558e3d",
                 "price": "7369.09000000",
                 "size": "0.01357000",
                 "product_id": "BTC-USD",
                 "side": "sell",
                 "type": "limit",
                 "time_in_force": "GTC",
                 "post_only": false,
                 "created_at": "2018-05-23T17:48:07.939614Z",
                 "done_at": "2018-05-23T17:48:09.793Z",
                 "done_reason": "filled",
                 "fill_fees": "0.3031376517000000",
                 "filled_size": "0.01357000",
                 "executed_value": "101.0458839000000000",
                 "status": "done",
                 "settled": true
               },
               "timestamp": 1527097687939,
               "datetime": "2018-05-23T17:48:07.939Z",
               "status": "closed",
               "symbol": "BTC/USD",
               "type": "limit",
               "side": "sell",
               "price": 7369.09,
               "cost": 101.0458839,
               "amount": 0.01357,
               "filled": 0.01357,
               "remaining": 0,
               "fee": {
                 "cost": 0.3031376517
               }
             }

```
Note: If I divide the cost by the filled I get what is shown on Gdax.

```javascript

let average = order.cost / order.filled  
// output => 7446.27

```

Thoughts?

**Comment by salihkilic** [comment]
I'm not sure what's wrong with this? Your order is filled at the given price or better. That doesn't change your order, it changes the result of that order. That's why it says excecuted value, it's the total value at time of excecution. Your asking price is what's described as "price".

**Comment by kroitor** [comment]
@flavioespinoza basically, the `info` field (and all the fields inside it) contains the data as is from the exchange, untouched, unedited. The other fields around `info` substructure contain parsed data. So, if you see a problem with the unparsed untouched data as it is from GDAX – you should probably contact GDAX on this issue. We don't change their data and we serve it as is. Hope this answers your question. The comment fo @salihkilic is also a correct answer to this issue. Let us know if it does not help. Thx!
