### ISSUE TITLE
Binance Exchange referral code.

### ISSUE THREAD

**Issue by sshchmod777** [ccxt/ccxt#2940]
I'm not sure if it was intended but the links on telegram won't redirect to the coin since there was a referral code inserted on binance.py.

Commit ID: https://github.com/ccxt/ccxt/commit/e9db3f896a850cc5a53168ef91fc207c06e7567d
![capture](https://user-images.githubusercontent.com/38970077/40462519-e313c652-5f42-11e8-82a7-17e8a6f74390.JPG)

**Comment by kroitor** [comment]
This is a problem with the code of the telegram bot that you're using, not really related to CCXT. You just need to handle the URL params properly (concat the url query). Hope this answers your question.

**Comment by sshchmod777** [comment]
Nope. It's not the telegram. The old version doesn't have any referral code inserted on binance.py. 👎 

Anyway, thanks for being open sourced.

**Comment by sshchmod777** [comment]
Here's the changes made by Travis.

https://github.com/ccxt/ccxt/commit/3cfe847d1e8af3240ceae1063fda01289556e569#diff-2368da134370a9c9f9349239cea82cfd

**Comment by kroitor** [comment]
> The old version doesn't have any referral code inserted on binance.py.
This is still a valid URL, we don't integrate with telegram, so it is some software or bot that you're using that is failing to handle the URLs properly. Anyway, I removed the referral codes from web urls and moved them to the referral urls, so that dumber software can survive.

**Comment by sshchmod777** [comment]
LOL. Look at the commit i have posted.
![capture](https://user-images.githubusercontent.com/38970077/40463180-43f31e7a-5f46-11e8-9f83-3ca401fec6f6.JPG)


[self.txt](https://github.com/ccxt/ccxt/files/2033721/self.txt)

**Comment by kroitor** [comment]
I saw that even before you posted, but you're not getting what I tell you. We have added referral URLs on purpose, and it's not our fault that some other people cannot handle that in their software. That is still a valid URL, either way. The only thing is that someone cannot handle it.

**Comment by kroitor** [comment]
This issue has been resolved anyway, the web URLs were reverted, so the poor software should work again now, it's just sad that programmers don't bother to handle the URLs properly.

**Comment by mkutny** [comment]
I'd reverted it back to '.web'... This way one would be forced to fix the real issue )
