### ISSUE TITLE
how to check order status

### ISSUE THREAD

**Issue by k31ww475** [ccxt/ccxt#2941]
Hi. 
I want to compare order "status" every 3 exchanges.But I can't.
How can I compare the **order status** against 3 exchanges???
status'contents is open or closed.

target exchange
bitflyer,zaif,bitbank

At first when I use create_order() and it works against all 3 exchanges
```
         limit_ordered_info_bid = exchange[0].create_order(
             symbol=target_currency,
               type="limit",
               side="buy",
             amount=set_bid_volume,
              price=best_bid_price
        )

```

But the contents is different per exchange
`   limit_ordered_info_bid = exchange[0].create_order(
`
I want to compare "ORDER STATUS" every 3 exchanges that I ordered.

For example,Bitbank's result is including result of **status** like that.So I can check it.

```
**bitbank**
 "id": "123456789",
 "datetime": "2018-05-24T03:50:42.501Z",
 "timestamp": 1527133841501,
 "lastTradeTimestamp": null,
 "status": "open", **>>>>>>>>>>>>>>>>>>>>>>>>>>>>> HERE WE CAN CHECK**
 "symbol": "BTC/JPY",
 "type": "limit",
 "side": "buy",
 "price": 760000.0,
 "cost": 0.0,
 "amount": 0.001,
 "filled": 0.0,
 "remaining": 0.001,
 "trades": null,
 "fee": null,
 "info": {
  "order_id": 123456789,
  "pair": "btc_jpy",
  "side": "buy",
  "type": "limit",
  "start_amount": "0.00100000",
  "remaining_amount": "0.00100000",
  "executed_amount": "0.00000000",
  "price": "760000.0000",
  "average_price": "0.0000",
  "ordered_at": 123456789,
  "status": "UNFILLED"
 }
}
```
But zaif isn't include "status" from result.What more it including the error like that.

```
zaif
**we cannot check status open or closed**
{
 "info": {
  "success": 1,
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\pydevd.py", line  1664, in <module>**<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< the error**
  "return": {
   "received": 0.0,
   "remains": 0.001,
   "order_id": 12345789,
   "funds": {
    "jpy": 12345789,
    "btc": 0.00100404,
    "xem": 12345789.0495,
    "mona": 0.0,
    "ETH": 0.0
   }
  }
 },
 "id": "12345789"
}

```

bit flyer's order information is too short.I can't check the order status from this result

```
bit flyer

{
 "info": {
  "child_order_acceptance_id": "JRF20180524-123456789-123456789"
 },
 "id": "JRF20180524-123456789-123456789"
}
```

Thanks in advance @Kroitor

**Comment by kroitor** [comment]
Hi!

in general, it is as documented in the Manual – create_order is not guaranteed to return any fields except `id` and `info`. This is not because we don't want it, it's because the exchanges themselves will not return order status immediately in response to create_order. Basically, they don't serve that info in their API. You can see the response from the exchange in the `info` field (untouched, as is). No status info there, obviously. If you find an exchange that does serve status, and ccxt does not – let us know and we will add it. 

Instead, the exchanges return an order id and you should use it to query the order status after creating it. This is the general pattern of working with orders. All of the above is documented in the Manual, here:
- https://github.com/ccxt/ccxt/wiki/Manual#querying-orders

Let us know if this does not answer your question.

**Comment by k31ww475** [comment]
I read the manual and I can't understand the command line.
In the status confirmation, which command should I type in this case??
or we can't search status ,I mean we only seach the order(like open or closed) ORDER ID???

    'fetchOrder': 
    'fetchOrders':
    'fetchOpenOrders':
    'fetchClosedOrders':'

Let me know concrete code. I already know the manual.
Thanks in advance

**Comment by kroitor** [comment]
> or we can't search status ,I mean we only seach the order(like open or closed) ORDER ID???

You **fetch the order** or all orders or open orders or closed orders, depending on which method is supported by the exchange. It returns the complete order structure, including the status of the order and all other fields of the order according to the Manual: https://github.com/ccxt/ccxt/wiki/Manual#order-structure

```Python
create_order_response = exchange.create_order (symbol, type, side, amount, price)
order_id = create_order_response['id']

if exchange.has['fetchOrder']:
    order = exchange.fetch_order (create_order_response['id'], symbol)
    print(order['status'])
elif exchange.has['fetchOrders']:
    orders = exchange.fetch_orders (symbol)
    orders_by_id = exchange.index_by (orders, 'id')
    if order_id in orders_by_id:
        order= orders_by_id[order_id]
        print(order['status'])
    else:
        print('Order ' + order_id + ' not found')
elif exchange.has['fetchOpenOrders']:  # the order can be open at this point in time
    # ... do your homework ;) ...
    ...
elif exchange.has['fetchClosedOrders']:  # the order can closed at this point in time
    # ... you should code at least some part of it and experiment yourself ;) ...
    ...
```

Hope this answers your question.

**Comment by k31ww475** [comment]
Thanks.Plz implemente fetch_order of zaif ASAP........

＞＞＞ccxt.base.errors.NotSupported: zaif fetch_order() is not implemented yet


2018-05-24 16:00 GMT+09:00 Igor Kroitor <notifications@github.com>:
