### ISSUE TITLE
Detect token access level?

### ISSUE THREAD

**Issue by Stas-Buzunko** [ccxt/ccxt#2944]
How to check access level on key and secret user entered?

I need users to enter only Read access token and want to prevent from entering Write access tokens

Didn't find in docs, is there an easy way to do it?

**Comment by kroitor** [comment]
> How to check access level on key and secret user entered?

75% of exchanges do not provide that info from their API. So, i guess, you should just show a clearly visible warning in bold. You can try placing a zero-amount order or a dummy-order using the keypair in question to see if the system will respond with Permission Denied, or with some order error. That can be an indication of your actual access rights. We hope to unify this aspect soon.

Let me know if this does not answer your question.

**Comment by Stas-Buzunko** [comment]
@kroitor thanks!

**Comment by Antonhansel** [comment]
I'm raising this issue from the dead @kroitor to check if you guys ever implemented this 😬
If not I'll try to use a bold message like suggested ;)
