### ISSUE TITLE
precision issue

### ISSUE THREAD

**Issue by alexsith** [ccxt/ccxt#2946]
- OS: mac os high sierra, ubuntu 16.04
- Programming Language version: python 3.6
- CCXT version: latest
- Exchange: exmo and others 
- Method: Exchange.truncate_to_string

This code:
from ccxt.base.exchange import Exchange
print(Exchange.truncate_to_string(0.37560392, 8))
result:
0.375604

So. this function uses, for example, in create_order in exmo (I am sure also in other exchanges too).
So, if I have only 0.37560392 coins I am not able to pass this value to create_order for sell order, because :
create_order failed exmo {"result":false,"error":"Error 50052: Insufficient funds"}

Precision of markets is correct - 8.

**Comment by alexsith** [comment]
I found that decimal_to_precision(0.37560392, TRUNCATE,8) works much better:
0.37560391

**Comment by kroitor** [comment]
The `truncate_to_string` is now deprecated and we are migrating to `decimal_to_precision`.
