### ISSUE TITLE
bitfinex fetchOrder "No such order found" for orders older than 24 hours

### ISSUE THREAD

**Issue by cristianm** [ccxt/ccxt#2947]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows
- Programming Language version: js
- CCXT version: 1.14.63
- Exchange: bitfinex
- Method: fetchOrder

bitfinex fetchOrder return "No such order found" and the order is valid. Same with ccxt 1.13 works fine.

**Comment by kroitor** [comment]
Can you please show a minimal snippet of code to reproduce the issue (including the instantiation code) and your verbose request and response, as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

**Comment by cristianm** [comment]
The code with the correct key, secret and order_id is

"use strict";

const ccxt      = require ('ccxt')
const asTable   = require ('as-table')
const log       = require ('ololog').configure ({ locate: false })

require ('ansicolor').nice

let sleep = (ms) => new Promise (resolve => setTimeout (resolve, ms))

;(async () => {

    // instantiate the exchange
    let exchange = new ccxt.bitfinex  ({
        "apiKey": "xx",
        "secret": "xx",

    })


    try {

        let order = await exchange.fetchOrder(11111)

        // output the result
        log (exchange.name.green, 'order', order)

    } catch (e) {

        if (e instanceof ccxt.DDoSProtection || e.message.includes ('ECONNRESET')) {
            log.bright.yellow ('[DDoS Protection] ' + e.message)
        } else if (e instanceof ccxt.RequestTimeout) {
            log.bright.yellow ('[Request Timeout] ' + e.message)
        } else if (e instanceof ccxt.AuthenticationError) {
            log.bright.yellow ('[Authentication Error] ' + e.message)
        } else if (e instanceof ccxt.ExchangeNotAvailable) {
            log.bright.yellow ('[Exchange Not Available Error] ' + e.message)
        } else if (e instanceof ccxt.ExchangeError) {
            log.bright.yellow ('[Exchange Error] ' + e.message)
        } else if (e instanceof ccxt.NetworkError) {
            log.bright.yellow ('[Network Error] ' + e.message)
        } else {
            throw e;
        }
    }

}) ()


and the result is
handleRestResponse:
 bitfinex POST https://api.bitfinex.com/v1/order/status 404 Not Found
Response:
 { Date: 'Thu, 24 May 2018 21:25:20 GMT',
  'Content-Type': 'application/json; charset=utf-8',
  'Content-Length': '34',
  Connection: 'close',
  'Set-Cookie': '__cfduid=db879a9ab99a1534a9166286f49b535ad1527197120; expires=Fri, 24-May-19 21:25:20 GMT; path=/; domain=.bitfinex.com; HttpOnly',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Xss-Protection': '1; mode=block',
  'X-Content-Type-Options': 'nosniff',
  'Cache-Control': 'no-cache',
  'X-Request-Id': 'c58f3dbe-ab33-49bf-85fc-9150f5c5f89b',
  'X-Runtime': '0.012676',
  'Strict-Transport-Security': 'max-age=31536000',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Cf-Ray': '4202d593db6367bb-EZE' }
 {"message":"No such order found."}

[Exchange Error] bitfinex {"message":"No such order found."}

**Comment by kroitor** [comment]
The order id must be a string.

Does this work:

```
        let order = await exchange.fetchOrder('YOUR_ORDER_ID_AS_STRING')
```

?

**Comment by cristianm** [comment]
The issue happen when upgrade to the last version.

**Comment by kroitor** [comment]
@cristianm can you tell the last version number that does work?

**Comment by cristianm** [comment]
I upgrade from 1.13.134 to 1.14.63

**Comment by kroitor** [comment]
@cristianm since 1.13.134 to 1.14.63 there were no changes in js/bitfinex.js neither in `fetchOrder` nor `sign` methods, and there were no related or significant changes in `Exchange.js` base class... So, it must have something to do with your order. Does it work if you revert back and install 1.13.134 now?

**Comment by cristianm** [comment]
Wow, the issue is with bitfinex. I can´t fetchOrder for orders more than 24hs old....

**Comment by kroitor** [comment]
@cristianm you can try their v2 API to see if it makes any difference. It is supported in ccxt as well. Hope you don't mind if I close this issue now?

**Comment by cristianm** [comment]
The v2 don't have fetchOrder.

**Comment by kroitor** [comment]
Yeah, you're right, it's not supported yet, however, with v1 you can call fetchOpenOrders / fetchClosedOrders to see if it's there. Hope this helps.
