### ISSUE TITLE
Exmo

### ISSUE THREAD

**Issue by Calambuuur** [ccxt/ccxt#2948]
### ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: win 10
- Programming Language version: Python 3.6.5
- CCXT version:1.14.50
- Exchange:exmo
- Method: ohlcv

import ccxt
import time

from datetime import datetime, timedelta

exchange = ccxt.exmo()
symbol = 'BTC/USD'
exchange.fetch_ohlcv(symbol, '1m', since=int(((datetime.utcnow() - timedelta(minutes=1)) - datetime(1970, 1, 1)).total_seconds() * 1000), limit=1)
if exchange.has['fetchOHLCV']:
    for symbol in exchange.markets:
        time.sleep (exchange.rateLimit / 1000) # time.sleep wants seconds 
        print (symbol, exchange.fetch_ohlcv (symbol, '1d')) # one day
=====================================================
Return:
BTC/USD [[1527120000000, 7600.0, 7627.99999999, 7579.49096789, 7609.99929999, 9.610295380000004]]
BTC/EUR [[1527120000000, 6454.5150818, 6521.24, 6454.5150818, 6476.5, 9.064882469999992]]
BTC/RUB [[1527120000000, 463207.3825362, 465216.27012872, 461765.91113543, 463840.0, 9.216818009999994]]
BTC/UAH [[1527120000000, 199016.4408158, 201010.279429, 198400.0, 199920.0001, 1.5040555899999994]]
BTC/PLN [[1527120000000, 28527.0, 29273.999997, 27223.57823022, 28301.4646439, 5.8142004300000005]]
BCH/BTC [[1527120000000, 0.13914, 0.14, 0.13902898, 0.13959973, 15.868039879999998]]
EOS/BTC [[1527120000000, 0.00160648, 0.00161999, 0.00159705, 0.00160554, 249.2314995899999]]
EOS/USD [[1527120000000, 12.230001, 12.38769029, 12.151, 12.1816, 432.70546885000016]]
BTG/BTC [[1527120000000, 0.0061501, 0.00618, 0.00606424, 0.00606424, 99.42987340999998]]
BTG/USD [[1527120000000, 46.46, 46.98, 46.081, 46.1, 115.25092717999996]]
BCH/USD [[1527120000000, 1064.0, 1068.57816336, 1059.97076529, 1060.56100058, 22.692825910000003]_
=======================================================
How to get history OHLCV for exchange.markets

**Comment by kroitor** [comment]
There's several mistakes in your code:

1. First, you call 
```
exchange.fetch_ohlcv(symbol, '1m', since=int(((datetime.utcnow() - timedelta(minutes=1)) - datetime(1970, 1, 1)).total_seconds() * 1000), limit=1)
``` 

2. Then you call it again in a loop without any delay after the first call.

3. You forgot to load the markets, as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

4. Your loop is iterating over markets, whereas you should've iterated over symbols.

5. Exmo exchange does not support OHLCV in their API directly, their fetch_ohlcv method is emulated as described here: https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-emulation
That means that their OHLCV is based on recent trades, thus you will get one or two 1d-candles per each symbol, as their trade history is limited.

```
import ccxt
exchange = ccxt.exmo({'enableRateLimit': True})
symbol = 'BTC/USD'
if exchange.has['fetchOHLCV']:  # 'emulated', based on trades
    for symbol in exchange.symbols:
        print (symbol, exchange.fetch_ohlcv(symbol, '1d')) # one day
```

Hope this answers your question. Thx!
