### ISSUE TITLE
What is the best way to keep up-to-date a database with OHLCV data ?

### ISSUE THREAD

**Issue by HornKild** [ccxt/ccxt#2952]
Hello,

I would like to build a database with OHLCV data (1d, 4h, 1h) from multiple exchanges and this is a lot of data to collect periodically.

A solution could be to calculate 1d and 4h candles from the 1h data to limit the number of query but still it will take a very long time to fetch thousand of candles in 1h. Do you think there is an alternative option to do this ? For example `fetch_tickers()` returns symbols details including OHLCV for every symbols of an exchange in a single API call, but unfortunnatly there are exchanges that do not support this function, and I'm not not sure what is the timeframe of this OHLCV and if it is consistent for every exchanges.

Thanks,

**Comment by kroitor** [comment]
> A solution could be to calculate 1d and 4h candles from the 1h data to limit the number of query 

Yep )

> but still it will take a very long time to fetch thousand of candles in 1h.

Nope ) Just do a quick calculation: 1h candle = 24 candles per day = 720 / month = 8640 / year.
I doubt that you will ever need to operate on a whole year at once. For modern dbs fetching 8k rows is a piece of cake.

**Comment by HornKild** [comment]
Hi Igor, ye but is there are 1000+ symbols to fetch every hour (multiple exchanges) and this is a lot of API requests.

**Comment by kroitor** [comment]
> but is there are 1000+ symbols to fetch every hour 

1. No need to fetch them every hour. You can fetch the entire 24 hours of 1h-candles in one call per day. 1000 calls per day is a piece of cake. Moreover, with most of adequate exchanges you can fetch a month of 1h-candles in one call. And you're not going to trade the inadequate exchanges. Also, you're probably not going to have enough funding for trading all those pairs, and you will meet all sorts of restrictions along the way, so with very little brainwork you can filter and reduce your list of pairs by a factor of 2 to 10. That's just 100 pairs of your interest. 864000 rows per year. Any modern PC can handle this easily.

**Comment by kroitor** [comment]
I'd close this for now if you don't mind. Feel free to reopen it if needed or just ask questions. Thx!

**Comment by HornKild** [comment]
The idea is to backtest trading strategies so yes I'll need all those pairs. Another constraint I have is fast trading decisions so any solution that takes too much time to fecth all the data is not suitable, even with a minimum timeframe of 4h. I think I'll try a combination of the two methods with `fetch_ohlcv()` to get proper 4h candles and `fetch_tickers()` to retrieve the latest price available of every symbols in one call, every 1h or every 4h.
