### ISSUE TITLE
`npm run build` in `create-react-app` causes build failure

### ISSUE THREAD

**Issue by tiddle** [ccxt/ccxt#2955]
- OS: Xubuntu
- Programming Language version: Javascript
- CCXT version: 1.14.65
- Exchange: N/A
- Method: N/A

importing ccxt into my react app and attempting to compile it for production causes issues.

The error is as follows:
```
> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/ccxt/js/base/errors.js:44 

Read more here: http://bit.ly/2tRViJ9
```

It points to this url: 
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

Where it suggests raises an issue to suggest compiling the code to es5 when publishing to npm.

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/issues/1916
- https://github.com/ccxt/ccxt/pull/2852
- https://github.com/ccxt/ccxt/issues/299
- https://github.com/ccxt/ccxt/pull/612
