### ISSUE TITLE
OKEX fetch_ticker

### ISSUE THREAD

**Issue by archangellin** [ccxt/ccxt#2959]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

Hey, Guys
While using fetch_ticker() with OKEX, I found that tick arrives not as fast as it shows at OKEX's website...

**Comment by kroitor** [comment]
You should use websockets with OKEX then (not supported in ccxt yet). However, it depends on your code and on the way you do the polling. All about ws here: #56. 
P.S. OKEX WS is known to be throttled even more than REST.
Hope this answers your question.
