### ISSUE TITLE
fetch_open_orders 's count is shift by one.

### ISSUE THREAD

**Issue by k31ww475** [ccxt/ccxt#2961]
Hi.
fetch_open_orders 's count is shift by one.
create_order 's process works well.no problm.
for instance,
after I used create_order function,I typed fetch_open_orders like that.
Amount is 700000jpy that's why the order's status will be open absolutely.
But dummy0's contents is dummy0 [].This is print of result.

And I used same process again ,I mean work the create_order one more time(second),
then fetch_open_orders function works well.So fetch_open_orders 's count is shift by one.
I could confirmed dummy0's contents,when I used fetch_open_orders over 2times.(like 3,4,5times)

```
        limit_ordered_info_bid = exchange[0].create_order(
             symbol=target_currency,
               type="limit",
               side="buy",
             amount=0.001
              price=700000
        )
        dummy0 = exchange[0].fetch_open_orders(target_currency)
        print("dummy0",dummy0)

```

result at first time using fetch_open_orders
`dummy0 []
`
Regards.

**Comment by k31ww475** [comment]
SELF RESOLVE
Add the code
time.sleep(1)

Thnx

**Comment by kroitor** [comment]
Thx for reporing back! Cheers!

**Comment by k31ww475** [comment]
Sorry Kroitor It doesn't work the resolve plan.The matter still open.

wrong resolve
>time.sleep(1)

**Comment by kroitor** [comment]
> when I used fetch_open_orders over 2times

1. Have you tried checking for it in the closed orders?
2. Also, which response do you get in limit_ordered_info_bid ?
3. Have you tried fetching that order by its id ?

**Comment by k31ww475** [comment]
Sorry for miswriting Kroitor.I resolve the solution.
I add the sleep not only fetch order ,but also cancel order.
Do you know the sleep problem the other process of ccxt?

**Comment by kroitor** [comment]
> I add the sleep not only fetch order ,but also cancel order.
> Do you know the sleep problem the other process of ccxt?

You should not use `sleep` at all. Instead, use the built-in rate-limiting without `sleep`. The sleeping will be done by CCXT then.

```Python
import ccxt
exchange = ccxt.bittrex({
    'enableRateLimit': True,  # ←------------------ add this here
})
create_order_response = exchange.create_order (
    symbol=target_currency,
    type="limit",
    side="buy",
    amount=0.001
    price=700000)  # your params here

# time.sleep (1)  # ←---------------------- delete this line, you don't need it

fetch_open_orders_response = exchange.fetch_open_orders (target_currency)  # your params here

# time.sleep (1)  # ←---------------------- delete this line, you don't need it
```

**Comment by kroitor** [comment]
More about it:
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/blob/master/examples/py/basic-rate-limiting.py
- https://github.com/ccxt/ccxt/blob/master/examples/py/builtin-rate-limiting-long-poller.py
- https://github.com/ccxt/ccxt/blob/master/examples/py/async-basic-rate-limiter.py

**Comment by k31ww475** [comment]
＞You should not use sleep at all. Instead, use the built-in rate-limiting without sleep. 

ok.thank you for early response.Actually I have a trouble what I use to  sleep func.Because the order process will be super late, if I use the sleep func.
I will try what you write.Thanx.Give me a second.

**Comment by k31ww475** [comment]
Hi Mr.kroitor.
I tried your code that you wrote above.And the run result was quite staylable.
Thank you for literally kindy explain.It worked well.

Thank lots.

**Comment by k31ww475** [comment]
Also I read the manual.

**Comment by k31ww475** [comment]
Hi Kroitor
Thank you for your code.
I created code while referring to homework from you.
This code is the way how to confirm the order(fetchorder,fetch
orders,openorder,closeorder)
Let me know the answer please.

    # priority1
    if exchange_get.has['fetchOrder']:

        survey_time = 1
        while survey_time <= 5:

            print("survey_time", json.dumps(survey_time, indent=True))

            order =
exchange[index[ask_exchange]].fetch_order(limit_ordered_info_bid['id'],
target_currency)
            time.sleep(0.1)

            if order['status'] == "closed":
                ring_sound(1)
                bid_order_successed_flag = 1
                break
            else:
                survey_time += 1

    # priority2
    elif exchange_get.has['fetchOrders']:

        survey_time = 1
        while survey_time <= 5:

            print("survey_time", json.dumps(survey_time, indent=True))

            orders =
exchange[index[ask_exchange]].fetch_orders(target_currency)
            time.sleep(0.1)
            orders_by_id = exchange[index[ask_exchange]].index_by(orders,
'id')

            if order_id in orders_by_id:
                order = orders_by_id[order_id]

                if order['status'] == "closed":
                    ring_sound(1)
                    bid_order_successed_flag = 1
                    break
                else:
                    survey_time += 1
            else:
                print(' fetchOrders Order ' + order_id + ' not found')

    # priority3
    elif exchange_get.has['fetchOpenOrders']:  # the order can be open at
this point in time

        survey_time = 1
        while survey_time <= 5:

            print("survey_time", json.dumps(survey_time, indent=True))

            all_open_orders_data =
exchange[index[ask_exchange]].fetch_open_orders(target_currency)
            time.sleep(0.1)

            if all_open_orders_data == []:
                ring_sound(1)
                bid_order_successed_flag = 1
                break
            else:
                survey_time += 1

    # priority4
    elif exchange_get.has['fetchClosedOrders']:

        survey_time = 1
        while survey_time <= 5:

            print("survey_time", json.dumps(survey_time, indent=True))

            orders =
exchange[index[ask_exchange]].fetch_closed_orders(target_currency)
            orders_by_id = exchange[index[ask_exchange]].index_by(orders,
'id')
            time.sleep(0.1)

            if order_id in orders_by_id:
                ring_sound(1)
                bid_order_successed_flag = 1
                break
            else:
                survey_time += 1
    else:
        print('can't confirm')

Thanks in advance



2018-05-26 13:29 GMT+09:00 Igor Kroitor <notifications@github.com>:
