### ISSUE TITLE
warning : OKEx fetchOHLCV with 1h timeframe gives exploded volume

### ISSUE THREAD

**Issue by DaveMG3** [ccxt/ccxt#2964]
Hi,
There is an error on implementation with OKEx
OKEx has a daily volume of around 1.4bd and doent seem to have a pair BTC/USD
But when calling fetchmarket and fetohlcv from OKEx on a 1h timeframe we received : 
example : BTC/USD volume 132818 , price 7435$ which is around 987millions $ in 1h

- Programming Language version: PHP
- CCXT version: 1.14.47
- Exchange: OkEx

**Comment by kroitor** [comment]
> and doent seem to have a pair BTC/USD

Are you sure about that?

- https://github.com/ccxt/ccxt/blob/master/examples/js/symbols.js

They do have a BTC/USD future market:

![okex-btc-usd](https://user-images.githubusercontent.com/1294454/40584894-f3342722-61b1-11e8-85df-bdabad3f6065.jpg)

> But when calling fetchmarket

`fetchMarkets` is not returning the volume info, it is designed to return just the market meta info (settings). The volumes should be fetched with `fetchOHLCV` / `fetchTicker` / `fetchOrderBook` / `fetchTrades`, depending on the purpose of the query.

> example : BTC/USD volume 132818 , price 7435$ which is around 987millions $ in 1h

We don't change their values, this is exactly what they report.

![okex-ohlcv-volume](https://user-images.githubusercontent.com/1294454/40584979-7bf46fa8-61b3-11e8-9e07-c8836bc3d7ee.jpg)

<img width="1329" alt="screen shot 2018-05-27 at 13 37 51" src="https://user-images.githubusercontent.com/1294454/40584980-8256920e-61b3-11e8-9f7e-d198284a26ad.png">

Read this: 

- https://github.com/okcoin-okex/API-docs-OKEx.com/blob/master/API-For-Futures-EN/REST%20API%20for%20FUTURES.md
- https://medium.com/@sylvainartplayribes/chasing-fake-volume-a-crypto-plague-ea1a3c1e0b5e
- https://github.com/ccxt/ccxt/tree/master/examples

Hope this answers your questions.

**Comment by DaveMG3** [comment]
@kroitor , 
sorry i was unclear in formulating the issue.
 OkEx FetchOHLCV 1h used with pair BTC/USD gives: 
-  volume 132818 , price 7435$ which is around 987millions $ in 1h. 
- The hour after it sends volume 93645 equivalent to 697millions$....
-> so for one day we will approx  15-20billions$ while OkEx report a 1.4 billion $ daily volume.

The data sent by OkEx OHLCV 1h surely doesnt relate to their 1h BTC/USD candle volume.
From the link you sent, we could suspect the pair BTC/USD is sending the 24h volume of the OkEx Exchange (...without considering the discussion on their artificial volumes)
Forwarding their error in CCXT is discutable and up to the creator but at least should be flagged to user i think.

**Comment by DaveMG3** [comment]
oh yeah i was starting suspecting that too.. i put this explanation below for potential reader to understand the fix.Thks 
![image](https://user-images.githubusercontent.com/32598581/40586849-07d753aa-61c8-11e8-8860-db66101be718.png)
