### ISSUE TITLE
bitstamp.js fetchOpenOrders this.market_by_id is undefined when not specifying symbol

### ISSUE THREAD

**Issue by khkwan0** [ccxt/ccxt#2970]
Fails on attempting to fetchOpenOrders() when not specifying parameters (leaving everything undefined).    Works find when specifiying a symbol.

this.market_by_id is undefined when attempting to parseOrder.  I dug through the code and added a fix so that this.loadMarkets() is called.  It works, but not sure if that is the most efficient approach without spending much more time tracing the code.

I can branch if you would like.

- Ubuntu 16.04
- node 8,9.1
- ccxt v1.14.76
- async fetchOpenOrders(...)

**Comment by kroitor** [comment]
> I can branch if you would like.

Your contributions are welcome! Just make sure to read this first: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

Thank you!

**Comment by kroitor** [comment]
@khkwan0 actually, your version might be not 1.14.76.

- https://github.com/ccxt/ccxt/blob/master/js/bitstamp.js#L537
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/bitstamp.py#L514
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/async/bitstamp.py#L514
- https://github.com/ccxt/ccxt/blob/master/php/bitstamp.php#L538

You might want to check your node_modules versions first ) Anyway, thanks for your involvement. Closing this for now, if you don't mind.

**Comment by khkwan0** [comment]
Ahh, but indeed it is version 1.14.76 (or at least that's what that package.json tells me), and I think I found an easier solution...

if you look at that line of code you showed here

- https://github.com/ccxt/ccxt/blob/master/js/bitstamp.js#L536

it has 

`if (typeof symbol !== 'undefined')`

it should be

`if (typeof symbol === 'undefined')`

i believe (or maybe i'm crazy). sorry to reopen a closed issue.  but i believe this is pertinent.

**Comment by khkwan0** [comment]
err almost...

more like

`if (typeof symbol === 'undefined')`
`  await this.loadMarkets()`
`else`
`  market = this.market(symbol)`

**Comment by kroitor** [comment]
Nope ;) 

Actually, it should be like this:

```JavaScript
// ...
let market = undefined;
await this.loadMarkets () // load them anyway
if (typeof symbol !== 'undefined') {
    market = this.market (symbol);
}
// ...
```

I've uploaded another fix for it, it will be available in version 1.14.81 in 5-10 minutes. Thx for your involvement!

**Comment by khkwan0** [comment]
ahh! so that was my original hack lol.  I wasn't sure if it was necessary to always load it.  Okay, thanks!

**Comment by kroitor** [comment]
@khkwan0 great) This should be ok by now ) Let me know if you have any other difficulties with it )
