### ISSUE TITLE
OKex future trade not support in v1.14.77

### ISSUE THREAD

**Issue by jackyxie** [ccxt/ccxt#2973]
- OS: Linux
- Programming Language version: PHP
- CCXT version: 1.14.77
- Exchange: OKex
- Method: create_order

Excuse me, in the latest version of ccxt, future coin info don't able to create_order.

**Comment by kroitor** [comment]
Which particular market?

**Comment by kroitor** [comment]
> future coin info don't able to create_order.

Can you please post your output?

**Comment by jackyxie** [comment]
I'm sorry I make a misstake in code. It's ok now

**Comment by kroitor** [comment]
Ok, no worries, let me know if you have any difficulties with it. Thx!
