### ISSUE TITLE
load_markets can't get okex future coin list

### ISSUE THREAD

**Issue by jackyxie** [ccxt/ccxt#2974]
- OS:Linux
- Programming Language version:PHP
- CCXT version:1.14.77
- Exchange:OKEx
- Method:load_markets

As the okex api change, v1.14.77 of ccxt can't get the coin list of future in okex.

**Comment by jackyxie** [comment]
future coin list api: 
https://www.okex.com/v2/futures/pc/market/futuresCoin.do

**Comment by kroitor** [comment]
> future coin list api:
> https://www.okex.com/v2/futures/pc/market/futuresCoin.do

That URL gives me 404, unfortunately...

> can't get the coin list of future in okex.

- CCXT version 1.14.77
- PHP version 7.17

```PHP
php > include_once ('ccxt.php');
php > $exchange = new \ccxt\okex ();
php > $exchange->load_markets ();
php > foreach ($exchange->markets as $market) { if ($market['future']) echo $market['symbol'] . "\n"; }
BTC/USD
LTC/USD
ETH/USD
ETC/USD
BCH/USD
BTG/USD
EOS/USD
XRP/USD
php > echo PHP_VERSION;
7.1.7
```

**Comment by jackyxie** [comment]
`php > $result = $okex->load_markets();
php > foreach ($result as $item) {}

$result valuable do not contain future info
`

**Comment by jackyxie** [comment]
Thanks, I get it. I search this_week for keyword, and missing the usd info.
