### ISSUE TITLE
loadMarkets issue - okex

### ISSUE THREAD

**Issue by AwooOOoo** [ccxt/ccxt#2977]
Hi,
   Since yesterday I've started having issues with loadMarkets(), but just for okex. 

**OS:** Ubuntu
**Programming language version:** Node v9.11.1
**ccxt version:** 1.14.20 (current)
**exchange:** okex
**Method:** loadMarkets

**Output:**

> >node node_modules/ccxt/examples/js/symbols.js okex
> Instantiating okex exchange
> (node:25157) UnhandledPromiseRejectionWarning: Error: okex GET https://www.okex.com/v2/markets/products request timed out (10000 ms)
>     at timeout.catch.e (/home/paul/Documents/hopscotch/node_modules/ccxt/js/base/Exchange.js:326:27)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:182:7)
> (node:25157) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:25157) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 

Sincerely, Paul.

**Comment by AwooOOoo** [comment]
It works fine for other markets I try. Also, I'm executing these calls from Europe.

**Comment by gub176** [comment]
I have the same problem with okex running program on a server in hongkong

**Comment by jvandenaardweg** [comment]
The endpoint https://www.okex.com/v2/markets/products seems broken/down/offline, so that's the problem. Probably a good thing to contact okex about it, don't know if they are aware of this 👍

**Comment by wangyongguiokcoin** [comment]
your can try  this    https://www.okex.com/api/v1/tickers.do

**Comment by florentweiler** [comment]
Here is the new equivalent endpoint : [https://www.okex.com/v2/spot/markets/products](url), 

moreover you can use this endpoint [https://www.okex.com/v2/spot/markets/index-tickers?limit=100000000&quoteCurrency=0](url) where the quoteCurrency can be incremented but I don't know the actual mapping behind this :  0 seems to be btc and 2 eth but I don't have a clue on how to have the complete set apart from just trying

**Comment by egorFiNE** [comment]
okex is down more than it's up and running, unfortunately. Not a problem of ccxt.

**Comment by AwooOOoo** [comment]
Could someone tell me where in the ccxt codebase I change the okex endpoint as was suggested above? I'm not yet familiar enough with the codebase.

**Comment by kroitor** [comment]
Guys, just update your version and use the search, this was fixed yesterday:
- https://github.com/ccxt/ccxt/issues/2972
- https://github.com/ccxt/ccxt/issues/2982
- https://github.com/ccxt/ccxt/issues/2980
