### ISSUE TITLE
PLEASE BUILD BITBANK FUNCTION

### ISSUE THREAD

**Issue by k31ww475** [ccxt/ccxt#2978]
HI,ALTHOUGH BITBANK IS VERY FAMOUS EXC IN JAPAN,
MAIN FUNC DON'T STILL BUILD YET.
PLEASE BUILD THE FOLLOW FUNCTION ASAP.

BITBANK FUNCTION
 "fetchClosedOrders": false,
 "fetchOrder": false,
 "fetchOrders": false,

THANKS IN ADVANCE

**Comment by kroitor** [comment]
This is answered here: https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar
