### ISSUE TITLE
Exchange KEY/SECRET Support

### ISSUE THREAD

**Issue by araa47** [ccxt/ccxt#2979]
Hi, is there any way to identify which of the exchanges support logging in to the private API with just API key and API secret. I am trying to make a list of the exchanges that only need key and secret since some exchanges in the library require uid and password too.

**Comment by Esc4pism** [comment]
check requiredCredentials for each exchange.

default values (in Exchange.js):
`'requiredCredentials': {
    'apiKey':   true,
    'secret':   true,
    'uid':      false,
    'login':    false,
    'password': false,
    'twofa':    false, // 2-factor authentication (one-time password key)
},`

**Comment by kroitor** [comment]
> sry, cant get it formatted nicely here

Plz, read this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

> - surround code and output with triple backticks: &#096;&#096;&#096;YOUR_CODE&#096;&#096;&#096;
> - don't confuse the backtick symbol (&#096;) with the quote symbol ('), &#096;&#096;&#096;GOOD&#096;&#096;&#096;, '''BAD'''
> - don't confuse a single backtick with triple backtick, &#096;&#096;&#096;GOOD&#096;&#096;&#096;, &#096;BAD&#096;

;)

@araa47 

> Hi, is there any way to identify which of the exchanges support logging in to the private API with just API key and API secret.

Yes, as @Esc4pism has pointed out, you should check the `requiredCredentials` and the `has` property, all documented here: https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

Hope this answers your question.
