### ISSUE TITLE
Okex V1

### ISSUE THREAD

**Issue by wybitnygracz** [ccxt/ccxt#2980]
There is support for OKex.com v1? 

v2 stop working since yesterday.   

"Uncaught ccxt\RequestTimeout: okex GET https://www.okex.com/v2/markets/products.do 28 Operation timed out after 7000 milliseconds with ...."

**Comment by wybitnygracz** [comment]
I changed and get: 
RequestTimeout: okex POST https://www.okex.com/api/v2/userinfo 28 Operation timed out after

**Comment by kroitor** [comment]
Guys, just update your version and use the search, this was fixed yesterday:
- https://github.com/ccxt/ccxt/issues/2972
- https://github.com/ccxt/ccxt/issues/2982
