### ISSUE TITLE
Bitfinex cancel_order() fails if order-ID isn't integer

### ISSUE THREAD

**Issue by ykgoon** [ccxt/ccxt#2981]
https://github.com/ccxt/ccxt/blob/acefa93d80c41389f9957195b3db221eedd47bc5/python/ccxt/bitfinex.py#L568

Is there a reason to expect Bitfinex order ID to be integer when cancelling order?

In my case an alphanumeric string-ID is passed and the function failed.

**Comment by kroitor** [comment]
> Is there a reason to expect Bitfinex order ID to be integer when cancelling order?

Yes:

![bitfinex-cancel-order-integer-id](https://user-images.githubusercontent.com/1294454/40662585-698689f2-635f-11e8-9a6e-5915826b4059.jpg)

https://docs.bitfinex.com/v1/reference#rest-auth-cancel-order

Hope this answers your question.
