### ISSUE TITLE
fix okcoinusd fetch_markets() server backend error

### ISSUE THREAD

**Issue by lyn716** [ccxt/ccxt#2982]
- OS:any
- Programming Language version:any
- CCXT version:any
- Exchange:okcoinusd
- Method: fetch_markets

![image](https://user-images.githubusercontent.com/12389937/40651076-6c9c411a-6367-11e8-8fd9-bf7c9d291125.png)

![image](https://user-images.githubusercontent.com/12389937/40651094-77247b02-6367-11e8-949c-3cb50480b49b.png)

**Comment by lyn716** [comment]
refer to https://github.com/ccxt/ccxt/issues/2977

**Comment by kroitor** [comment]
@lyn716 just update your version, this was fixed yesterday: https://github.com/ccxt/ccxt/issues/2972
