### ISSUE TITLE
Huobi Pro, Is Withdraw-Deposit history implemented?

### ISSUE THREAD

**Issue by devWaleed** [ccxt/ccxt#2989]
I just want to know if in PHP, Huobi Pro withdraw deposit is implemented? 

In file: ccxt/php/huobipro.php on line 697 i see the following code:

` public function withdraw ($code, $amount, $address, $tag = null, $params = array ()) { }`

which looks like it will create a withdraw, is there a method to fetch past withdraw/deposit history for any given account?

**Comment by kroitor** [comment]
> is there a method to fetch past withdraw/deposit history for any given account?

Not yet, but we are working on it. More about it here: https://github.com/ccxt/ccxt/issues/1896. I'd suggest to move this discussion to that linked post as this is a duplicate somewhat. Hope this answers your question. Thx!

**Comment by kroitor** [comment]
P.S. You contributions are welcome: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
