### ISSUE TITLE
Incorrect or missing ticker "change" field in some exchanges

### ISSUE THREAD

**Issue by alex-karo** [ccxt/ccxt#2990]
Gate.io, BtcTrade.im, Lbank: percentage value in change field
Quoinex: No change, but we can calc via "last_price_24h" field

- OS: Arch Linux
- Programming Language version: node.js v9.11.1
- CCXT version: 1.14.20
- Exchange: gateio, quoinex, btctradeim, lbank
- Method: fetchTicker / fetchTickers

**Comment by kroitor** [comment]
Your contributions are welcome: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code ;) Thx )

**Comment by alex-karo** [comment]
Too early closed =)
One problem with BtcTrade.im - I can't find docs for the exchange.
btctradeim class extends from coinegg. On the documentation coinegg doesn't have change field (i can't check api because CF rejects). Btctradeim exactly has.
Should I implement 'parseTicker' method in btctradeim class?

**Comment by kroitor** [comment]
> Should I implement 'parseTicker' method in btctradeim class?

Alternatively you can just tweak the base implementation like this:

```
let change = this.safeFloat (trade, changeFieldName);
if (typeof change === 'undefined') {
    // deduce it and other fields if possible
} 
// otherwise it is already taken from the exchange itself, deduce the rest if needed
```
