### ISSUE TITLE
Accurately establish min trade limit for both base and quote

### ISSUE THREAD

**Issue by phoenix-violeus** [ccxt/ccxt#2996]
I am creating a bot (testing with Cryptopia) that starts with one currency (BTC per my development thus far) and trades amongst every market for said currency regardless of whether the currency is the base or quote. In order to establish the minimum reserve needed for at least one trade in each market I need to sum up the minimum limits. For each market I need to determine whether the min amount or min cost is larger. For example:

BSTY/BTC
MinAmount: 1.0E-8 BSTY
MinCost:   0.0005 BTC

BTC/USDT
MinAmount: 1.0E-8 BTC
MinCost:   1 USDT

The first market has a quote of BTC, whereas the second a base of BTC. I have been struggling to find the most accurate way to estimate the BTC value of the non-BTC amount/cost. Would I use the most current price? Per the manual:

```
# Get current best price (query market price) and calculate bid/ask spread
$orderbook = $exchange->fetch_order_book ($exchange->symbols[0]);
$bid = count ($orderbook['bids']) ? $orderbook['bids'][0][0] : NULL;
$ask = count ($orderbook['asks']) ? $orderbook['asks'][0][0] : NULL;
$spread = ($bid && $ask) ? $ask - $bid : NULL;
```

If so, would the estimated BTC equivalent of the minimum amount (before fees) in the first example be established via the following?

`$btcMinAmountEquiv = $minAmount * $bid;`

The above seems logical to me yet the return is such so far below the minimum cost that I can't help to think that my reasoning is flawed. It's worth noting that there will be several points in my script in which I need to estimate the BTC equivalent for a non-BTC cryptocurrency.

Thank you very much for your help.

- OS: ubuntu0.16.04.1
- Programming Language version: PHP 7.0.30-0
- CCXT version: 10.1 2017-11-06
- Exchange: Cryptopia
- Method: N/A

**Comment by PhoenixVioleus** [comment]
Essentially what I'm asking:
What's the most logical way to estimate the current value of an amount in one currency in terms of the second currency?

**Comment by samgermain** [comment]
Here's a python solution to get the minimum stake amount based on both the base or the quote

```
import ccxt
import sys

print('python', sys.version)
print('CCXT Version:', ccxt.__version__)

exchange=ccxt.your_exchange({
    'apiKey': '...',
    'secret': '...',
})
exchange.load_markets()

symbol = '...'
market = exchange.market(symbol)
price = exchange.fetchTicker(symbol)['close']

min_stake_amounts = []
limits = market['limits']
if (limits['cost']['min'] is not None):
    min_stake_amounts.append(limits['cost']['min'])
    
if (limits['amount']['min'] is not None):
    min_stake_amounts.append(limits['amount']['min'] * price)
    
if not min_stake_amounts:
    min_stake_amount = None
else:
    # The value returned should satisfy both limits: for amount (base currency) and
    # for cost (quote, stake currency), so max() is used here.
    min_stake_amount = max(min_stake_amounts)
 ```
 
 And here's a Javascript solution
 
 ```
 const ccxt = require("ccxt");

console.log ('CCXT Version:', ccxt.version)

const exchange = new ccxt.your_exchange({
    'apiKey': '...',
    'secret': '...',
})
exchange.load_markets()

const symbol = '...'
const market = exchange.market(symbol)
const price = exchange.fetchTicker(symbol)['close']

const min_stake_amounts = []
const limits = market['limits']

if (limits['cost']['min'] !== undefined) {
    min_stake_amounts.append(limits['cost']['min'])
}

if (limits['amount']['min'] !== undefined) {
    min_stake_amounts.append(limits['amount']['min'] * price)
}

let min_stake_amount = undefined
if (min_stake_amounts.length > 0) {
    // The value returned should satisfy both limits: for amount (base currency) and
    // for cost (quote, stake currency), so max() is used here.
    min_stake_amount = Math.max(min_stake_amounts)
}
```
