### ISSUE TITLE
How to confirm my order's status used create_order

### ISSUE THREAD

**Issue by k31ww475** [ccxt/ccxt#2997]
Hi
After I order using create_order like that,

```
        limit_ordered_info_bid = exchange[index[ask_exchange]].create_order(
                symbol = target_currency,
                type = "limit",
                side = "buy",
                amount = set_ask_volume,
                price = best_ask_price
                )

        >>>>>>>>>>>>>>>>>>>>>>   and I want to check order status here open or close
```
How can I check the order's id that I ordered using create_order ?????
Now I check old order like that 
```
all_open_orders_data = exchange[index[ask_exchange]].fetch_open_orders(target_currency)
if all_open_orders_data == []:

```
But it is unsure way sometimes and its danger.  I want to check the status(open or closed) from order id.
target exchange is bitflyer,bitbank,zaif and quioinex.
Requirement from japannese must be many.Many ppl must be wait that solution.
Give me your smart wisdom.

and I already check the func 
```
 print(json.dumps(ccxt.bitflyer().has, indent=True))
 print(json.dumps(ccxt.zaif().has, indent=True))
print(json.dumps(ccxt.bitbank().has, indent=True))
print(json.dumps(ccxt.quoinex().has, indent=True))

```
Thanks in advance.

**Comment by kroitor** [comment]
> How can I check the order's id that I ordered using create_order ?????

For order id, it is documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#placing-orders

<img width="739" alt="screen shot 2018-05-30 at 18 39 56" src="https://user-images.githubusercontent.com/1294454/40731046-e3c93a32-6438-11e8-95b4-373c9065f548.png">


```Python
limit_ordered_info_bid = exchange[index[ask_exchange]].create_order(
                symbol = target_currency,
                type = "limit",
                side = "buy",
                amount = set_ask_volume,
                price = best_ask_price
                )

# your order id
print('My order id:', limit_ordered_info_bid['id'])
```

For status you will have to fetch the order structure by id after creating the order. Very few exchanges will actually return the order status right away.

- https://github.com/ccxt/ccxt/wiki/Manual#by-order-id
- https://github.com/ccxt/ccxt/wiki/Manual#all-orders

Hope this answers your question.

**Comment by k31ww475** [comment]
Thank you .I will try it

2018-05-31 0:43 GMT+09:00 Igor Kroitor <notifications@github.com>:
