### ISSUE TITLE
New Exchange: trade by trade 

### ISSUE THREAD

**Issue by arielorvits** [ccxt/ccxt#2998]
https://app.tradebytrade.com
api: https://support.tradebytrade.com/en-us/category/6-api

**Comment by An-Net** [comment]
The exchange is not operating anymore.

- https://www.cryptowisser.com/exchange/trade-by-trade/

- <img width="1440" alt="Снимок экрана 2021-05-17 в 23 13 12" src="https://user-images.githubusercontent.com/51840849/118550559-7f48f600-b765-11eb-8434-50878ecd8ae1.png">
