### ISSUE TITLE
cobinhood withdrawal - 403 error

### ISSUE THREAD

**Issue by Fcl69** [ccxt/ccxt#3005]
Hello,

ccxt version - ccxt (1.14.104)

```
import ccxt

exch = ccxt.cobinhood({
    'apiKey': key,
    'secret': sec,
    # 'password': passphrase,
    'enableRateLimit': True,
    'verbose': True,
    })

order = exch.withdraw('BTC', 1, '341rrvMstf7zh6TLdzo8YwGpfvXgwSC8bP')

print(order)
```

When trying to withdraw from cobinhood, I get the following error:

> $ python3 tmp_withdraw.py 
> 
> Request: POST https://api.cobinhood.com/v1/wallet/withdrawals {'nonce': '1528156541', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Content-type': 'application/json charset=UTF-8', 'Authorization': 'key'} {"address":"341rrvMstf7zh6TLdzo8YwGpfvXgwSC8bP","amount":1,"currency":"BTC"}
> 
> Response: POST https://api.cobinhood.com/v1/wallet/withdrawals 403 {'CF-RAY': '425e54ef7acdbc7a-SEA', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Content-Type': 'application/json; charset=utf-8', 'Date': 'Mon, 04 Jun 2018 23:55:41 GMT', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains; preload', 'Via': '1.1 google', 'Server': 'cloudflare', 'Content-Encoding': 'gzip', 'Set-Cookie': '__cfduid=d0b613b739830b8080146ed769d4572731528156541; expires=Tue, 04-Jun-19 23:55:41 GMT; path=/; domain=.cobinhood.com; HttpOnly; Secure', 'Transfer-Encoding': 'chunked', 'Alt-Svc': 'clear', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': 'https://cobinhood.com', 'X-Content-Type-Options': 'nosniff'} {"success":false,"error":{"error_code":"unauthorized_scope"},"request_id":"e60a3d2f642bc6b0"}
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 366, in fetch
>     response.raise_for_status()
>   File "/home/fcl/.local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.cobinhood.com/v1/wallet/withdrawals
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "tmp_withdraw.py", line 11, in <module>
>     order = exch.withdraw('BTC', 1, '341rrvMstf7zh6TLdzo8YwGpfvXgwSC8bP')
>   File "/usr/local/lib/python3.5/dist-packages/ccxt/cobinhood.py", line 506, in withdraw
>     }, params))
>   File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 308, in request
>     return self.fetch2(path, api, method, params, headers, body)
>   File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 305, in fetch2
>     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
>   File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 378, in fetch
>     self.handle_errors(response.status_code, response.reason, url, method, self.last_response_headers, self.last_http_response)
>   File "/usr/local/lib/python3.5/dist-packages/ccxt/cobinhood.py", line 541, in handle_errors
>     raise ExchangeError(feedback)
> ccxt.base.errors.ExchangeError: cobinhood {"request_id":"e60a3d2f642bc6b0","error":{"error_code":"unauthorized_scope"},"success":false}

PS API keys are ok - I can trade & fetch balances

**Comment by kroitor** [comment]
Hi )

https://github.com/ccxt/ccxt/wiki/FAQ#i-am-calling-a-method-and-i-get-an-error-what-am-i-doing-wrong )

**Comment by kroitor** [comment]
Your code to reproduce the issue (with clearly visible constant values) and your verbose request and response would be really helpful )

**Comment by Fcl69** [comment]
I'm so sorry... I've updated the original topic to match the criteria.

**Comment by kroitor** [comment]
@Fcl69 

from this:

> `{"success":false,"error":{"error_code":"unauthorized_scope"},"request_id":"e60a3d2f642bc6b0"}`

It looks like they key you're using does not have the necessary permission to withdraw funds. Can you check for that?

**Comment by Fcl69** [comment]
I've doubled checked, created a new API key and run the same code (with new API keys though). The error I get is the following:

> Request: POST https://api.cobinhood.com/v1/wallet/withdrawals {'Authorization': 'key', 'nonce': '1528217158', 'Content-type': 'application/json charset=UTF-8', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'python-requests/2.18.4'} {"address":"341rrvMstf7zh6TLdzo8YwGpfvXgwSC8bP","amount":1,"currency":"BTC"}
> 
> Response: POST https://api.cobinhood.com/v1/wallet/withdrawals 400 {'Content-Length': '90', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Set-Cookie': '__cfduid=cookie; expires=Wed, 05-Jun-19 16:45:58 GMT; path=/; domain=.cobinhood.com; HttpOnly; Secure', 'Server': 'cloudflare', 'Date': 'Tue, 05 Jun 2018 16:45:59 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Connection': 'keep-alive', 'Alt-Svc': 'clear', 'Via': '1.1 google', 'CF-RAY': '42641cdb895bbb1e-SEA', 'X-Content-Type-Options': 'nosniff', 'Access-Control-Allow-Origin': 'https://cobinhood.com', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains; preload'} {"success":false,"error":{"error_code":"invalid_payload"},"request_id":"323166dadb026e01"}
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 366, in fetch
>     response.raise_for_status()
>   File "/home/fcl/.local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.cobinhood.com/v1/wallet/withdrawals
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "tmp_withdraw.py", line 11, in <module>
>     order = exch.withdraw('BTC', 1, '341rrvMstf7zh6TLdzo8YwGpfvXgwSC8bP')
>   File "/usr/local/lib/python3.5/dist-packages/ccxt/cobinhood.py", line 506, in withdraw
>     }, params))
>   File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 308, in request
>     return self.fetch2(path, api, method, params, headers, body)
>   File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 305, in fetch2
>     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
>   File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 378, in fetch
>     self.handle_errors(response.status_code, response.reason, url, method, self.last_response_headers, self.last_http_response)
>   File "/usr/local/lib/python3.5/dist-packages/ccxt/cobinhood.py", line 541, in handle_errors
>     raise ExchangeError(feedback)
> ccxt.base.errors.ExchangeError: cobinhood {"success":false,"request_id":"323166dadb026e01","error":{"error_code":"invalid_payload"}}

**Comment by kroitor** [comment]
Ok, so it's a different error code now, so, we're definitely making progress! ) Now I'll have to debug their `invalid_payload` a little to see what might go wrong there. Will get back to you on this soon.

**Comment by Fcl69** [comment]
Progress... Yey! ;)
Thanks, Igor, waiting to hear back from you.

**Comment by Fcl69** [comment]
Hi Igor, no progress yet?

V
