### ISSUE TITLE
kraken.fetchBalance() doesn't depict the balance

### ISSUE THREAD

**Issue by DmitryVil** [ccxt/ccxt#3008]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10
- Programming Language version: python 3.6.4
- CCXT version:1.14.97
- Exchange: kraken
- Method: fetchBalance()

Igor, good evening,

I am using the code to fetch balance from the kraken:

getBalance = True
if getBalance == True:
            balance = asyncio.get_event_loop().run_until_complete(flr.fetchBalance())
            print('fetchBalance() reports: ', balance )

Previously I sent to kraken some bitcoin and got the confirmation from the kraken:
![image](https://user-images.githubusercontent.com/35109659/40809731-230ea55a-6534-11e8-90a1-0b88f70f1202.png)

But I can't see the right balance as a result of fetchBalance() method:
![image](https://user-images.githubusercontent.com/35109659/40809874-a0039d36-6534-11e8-9431-d9d2441fc647.png)

What would you advice?

Thank you in advance,
Dmitry

**Comment by kroitor** [comment]
Because your transaction is still *`confirming`*, it is not credited to your balance yet. You should wait for it to clear.

**Comment by kroitor** [comment]
https://support.kraken.com/hc/en-us/articles/203325283-How-long-do-digital-assets-cryptocurrency-deposits-take-

Hope this answers your question.

**Comment by DmitryVil** [comment]
Thanks, you are absolutely right
