### ISSUE TITLE
isNode value is wrong in some case (false negative)

### ISSUE THREAD

**Issue by AoDev** [ccxt/ccxt#3009]
### Env
- OS: OSX 
- Programming Language version: JS
- CCXT version: 1.14.106
- Method: isNode value in ccxt/js/base/functions/platform.js

### Context

I am writing unit tests with `jest`.
The app itself is a client side SPA (with Electron) but the tests run in node.

One test breaks with the following exception: `ReferenceError: fetch is not defined
`

### Issue

I checked the value of isNode and discovered it was `false`. I was expecting it to be true.
I suppose that the exception would disappear after that.

### Other details
* The tests run locally with `node v8.9.1`.
* I am using `"babel-jest": "23.0.1"`

**Comment by kroitor** [comment]
This is probably related: https://github.com/ccxt/ccxt/pull/2852

**Comment by AoDev** [comment]
Yes probably. I saw the issue but I thought it might be something else. If the fix proposed there works, then we could close this issue at the same time.
Thanks.

**Comment by kroitor** [comment]
Merged #2852, this should be fixed as of CCXT 1.14.201. Let us know if you still have difficulties with it after updating. Thx!

**Comment by AoDev** [comment]
I confirm it works after updating to ccxt 1.14.205. Thank you for the fix :)

**Comment by kroitor** [comment]
@AoDev all thx for the fix to @standup75 and to you for the feedback )
