### ISSUE TITLE
parse_order() takes at most 3 arguments (4 given)

### ISSUE THREAD

**Issue by nazargulov** [ccxt/ccxt#3010]
I review your commit https://github.com/ccxt/ccxt/commit/2402eaa45308e4b7c2afcc3fe4867416593b751e#diff-1d55d99612e0bff0014e23cc3b26fe74R390
Good job.

But after this commit 'create_limit_buy_order' doesn't work in gateio.py.
Wrong arguments for parse_order.

    return self.create_order(symbol, 'limit', 'buy', *args)
  File "/python2.7/site-packages/ccxt/gateio.py", line 397, in create_order
    }), response, market)
TypeError: parse_order() takes at most 3 arguments (4 given)

please, fix this!

**Comment by frosty00** [comment]
Here's the fix - just more the closing bracket over one argument to the right:

```
        return this.parseOrder (this.extend ({
            'status': 'open',
            'type': side,
            'initialAmount': amount,
        }, response), market);
    }
```
