### ISSUE TITLE
How to make async data fetching work with multi-threading

### ISSUE THREAD

**Issue by cowboyjj** [ccxt/ccxt#3011]
I have been following the async examples and been fetching market data and order book data successfully. I now have a problem with threading. I struggle to make async code work with threading. A snippet of my code is like this where loadGDAX() will work perfectly when invoked on its own but not in a thread:

def loadGDAX():
    exchange = ccxt.gdax({
        'enableRateLimit': True,  # this option enables the built-in rate limiter
    })
    asyncio.get_event_loop().run_until_complete(loadTickerImpl(exchange, 'ETH/USD', 'GDAX.txt'))
    
def test1():
    print(datetime.datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d %H:%M:%S'))

number=7
p1 = threading.Thread(target=loadGDAX)
p2 = threading.Thread(target=test1)
p1.start()
p2.start()
p1.join()
p2.join()

I don't think this is a very difficult problem but my limited python knowledge is not helping.
I will greatly appreciate it if anybody can help.

**Comment by frosty00** [comment]
Async python and multithreading often break each other. 

Your problem is that you are using asyncio.get_event_loop() inside a thread (you will get an error saying no event loop found or something like that). Define the event loop outside of the multithreaded function to fix this.

**Comment by cowboyjj** [comment]
I apologize since I realize I may not have provided a good context to my question. Basically I want to have one function fetching data non-stop and writing data to a file, and another function loading back those data from file and performing some data analysis on the data. There is a third function which should handle the trade (buy/sell) transactions with the exchange. I want to have all these three functions running in parallel on three different threads but I am not able to get it working.

**Comment by frosty00** [comment]
Define three functions that do that and start them in different threads?

> I struggle to make async code work with threading. 

could you post the error at least..

**Comment by cowboyjj** [comment]
Hello frosty, thanks a lot for replying. 

The error was exactly as you described in your first post, 'no event loop found' (or something like that. Having seen your first comment I've been trying to define the loop outside. Also I've been trying to use 'concurrent.futures.ThreadPoolExecutor' which seem to work in some google search results. However as we speak I am still struggling to put these things together ...

**Comment by frosty00** [comment]
Define the event loop outside the async function and reference it directly instead of using asyncio.get_event_loop. Also you need to use `asyncio.run_coroutine_threadsafe(coro(), loop=loop)` to wrap future tasks if you want it to work (trust me on this it will save a headache down the line)

**Comment by cowboyjj** [comment]
Cool. Thanks Frosty.

I will try. If you or any helper can provide some skeleton code or code snippet so that I see how things are put together it will be most helpful.

**Comment by frosty00** [comment]
```
def close_all():
    if not network.EVENT_LOOP.is_running():
        threading.Thread(target=network.EVENT_LOOP.run_forever).start()
    for ex in abstract_exchanges:
        asyncio.run_coroutine_threadsafe(ex.async.close(), network.EVENT_LOOP).result()
    network.EVENT_LOOP.call_soon_threadsafe(network.EVENT_LOOP.stop)
    logging.critical('Requested to stop event loop soon and closing event loop')
    while network.EVENT_LOOP.is_running():
        time.sleep(0.1)
    network.EVENT_LOOP.close()
```

This is the code I use to close all the async exchanges (to avoid the  "exchange requires to release all resources with an explicit call to the .close() coroutine")

**Comment by araa47** [comment]
@frosty00 , I currently use sys.exit() to close all my exchange coroutines. I tried using your function but get the following error: 
```
Traceback (most recent call last):
  File "app.py", line 710, in <module>
    close_all()
  File "app.py", line 691, in close_all
    if not network.EVENT_LOOP.is_running():
NameError: name 'network' is not defined
```
So I tried installing the network module and now I get this error: 
```
Traceback (most recent call last):
  File "app.py", line 711, in <module>
    close_all()
  File "app.py", line 692, in close_all
    if not network.EVENT_LOOP.is_running():
AttributeError: module 'network' has no attribute 'EVENT_LOOP'
```

**Comment by frosty00** [comment]
Yeah sorry network is just a file I have in my project. 

EVENT_LOOP is the same as `asyncio.get_event_loop()` or `asyncio.new_event_loop()`

**Comment by kroitor** [comment]
Closing this for now, feel free to reopen it if needed, or just questions if you have more. Thx to @frosty00 for the support!
