### ISSUE TITLE
limit debug size

### ISSUE THREAD

**Issue by rspadim** [ccxt/ccxt#3014]
hi guys, debug is a big to some exchanges, could be implement a limit of response size at debug?

python code for def fetch()  at exchange.py

instead of:

self.logger.debug("%s %s, Response: %s %s %s", method, url, response.status_code, response.headers, self.last_http_response)

do:
            if hasattr(self, "max_debug_size"):
                if len(self.last_http_response) > self.max_debug_size and self.max_debug_size > 0:
                    self.logger.debug(
                        "%s %s, Response-Truncated: %s %s %s", method, url, response.status_code, response.headers,
                        self.last_http_response[0:self.max_debug_size])
                else:
                    self.logger.debug(
                        "%s %s, Response: %s %s %s", method, url, response.status_code, response.headers,
                        self.last_http_response)
            else:
                self.logger.debug("%s %s, Response: %s %s %s", method, url, response.status_code, response.headers, self.last_http_response)

**Comment by kroitor** [comment]
Hi!

Actually, standard built-in python logging already has that feature in it. Let us know if this does not help: https://stackoverflow.com/questions/16799075/in-a-python-logging-is-there-a-formatter-to-truncate-the-string
