### ISSUE TITLE
Referral IDs

### ISSUE THREAD

**Issue by frosty00** [ccxt/ccxt#3016]
I would like to support ccxt and I noticed many exchanges provide an option for referral IDs or urls that give the referrer some benefits, like reduced trading fees or a percentage of fees as commission. Perhaps we should have a list of referal IDs (not urls but unique strings) somewhere in the wiki where people can optionally copy and paste them?

Also I am all for editting the .url attribute for the main table on the front page of ccxt when the url is non-intrusive and is transparent to the user, take `https://gate.io/ref/1486602` which leads users to the home page of the exchange, and if they sign up you or whoever will get a 30% cut of the trading fees. I have over $200k traded on gateio in the last thirty days and I can imagine most ccxt users will be doing lots of trading anyway.

**Comment by frosty00** [comment]
PS. just referred you on cointiger (:

**Comment by kroitor** [comment]
> I would like to support ccxt and I noticed many exchanges provide an option for referral IDs or urls that give the referrer some benefits, like reduced trading fees or a percentage of fees as commission. Perhaps we should have a list of referal IDs (not urls but unique strings) somewhere in the wiki where people can optionally copy and paste them?

We are adding them in the `urls` section under the `referral` key ) 

- https://github.com/ccxt/ccxt/blob/master/js/huobipro.js#L49 
- https://github.com/ccxt/ccxt/blob/master/js/exmo.js#L35
- ...

Hopefully, will get them all fulfilled asap ) Going to add gate.io ref shortly ) Thx for being so helpful! )

**Comment by Showgofar** [comment]
But its good idea to add it here
https://github.com/ccxt/ccxt#ccxt--cryptocurrency-exchange-trading-library
I registered several accounts from that page

**Comment by kroitor** [comment]
> But its good idea to add it here

We are already adding the URLs there ) Thx! )

**Comment by kroitor** [comment]
@Showgofar @frosty00 if you know of exchanges that have referral programs, let us know, will be happy if you just list them here ) thx a lot )
