### ISSUE TITLE
Is there a faster way to get tickers for all exchanges?

### ISSUE THREAD

**Issue by jraicr** [ccxt/ccxt#3023]
Hi guys, I need some help regarding this library. I'm a bit new at programming in the javascript world and I'm tring this to build some backend data calculation.

![](https://thumbs.gfycat.com/TastyAntiqueBluetonguelizard-max-14mb.gif)

I'm trying to go through all the exchanges and download their tickers. In the loop I'm building a json structure where I can go through all the data to do calculations. I would like to do this fetching more faster since I'm planning to build a web client with some services, starting with a realtime coin marketcap. Websocket fetching will be available for ccxt? 

Is it viable to do it this way? You can [check the source here](https://gist.github.com/jraicr/1855b19dc4ec920a1c267e0e67abddd3).

**Comment by kroitor** [comment]
> Websocket fetching will be available for ccxt?

I'd suggest to move this discussion here: #56, if you don't mind. Thx!
