### ISSUE TITLE
Bitmex Fetch Account Balance - Points to wrong RestApi call?

### ISSUE THREAD

**Issue by Iolheal** [ccxt/ccxt#3024]
- OS: Windows
- Programming Language version: Python 3.6
- CCXT version:  ccxt-1.14.123
- Exchange: Bitmex
- Method: fetch_Balance()

Hi,

Bitmex's Fetch_balance function currently points to "https://www.bitmex.com/api/v1/user/margin?currency=all", but I think it should be pointing to "https://www.bitmex.com/api/v1/position" with a possible arg asking for the desired currency (main fault of user/margin is that it doesn't state the live position only how much BTC is used).

I think the whole .../user/... api functionality struggles with handling multiple currencies on their end (even setting currency : all in their rest api explorer isn't returning multiple currencies).

Cheers

**Comment by kroitor** [comment]
> but I think it should be pointing to "https://www.bitmex.com/api/v1/position" with a possible arg asking for the desired currency

Actually, not. The `position` endpoint is the margin/positional/leveraged equivalent for `fetchOrder` (that should be a separate `fetchPosition` method, that is yet to be implemented in CCXT). The `fetchOrder` does accept a symbol argument and `fetchPosition` will accept one as well. So, `fetchBalance` does not correspond to position stats with leveraged trading. Hope this answers your question.
