### ISSUE TITLE
Invalid nonce KuCoin Php

### ISSUE THREAD

**Issue by koushik72** [ccxt/ccxt#3026]
- OS: Windows 10
- Programming Language version: Php
- CCXT version:1.14.123
- Exchange: KuCoin
- Method: fetchBalance()

Hi, I am having a problem making any private request be it balance or anything. 
It says invalid nonce all the time
`kucoin {"code":"UNAUTH","msg":"Invalid nonce","success":false,"timestamp":1528096040110}`
I saw that KuCoin actually has the 13 digit micro sec format but they call it milliseconds in their doc.
So, I also created a subclass and modified the nonce

`
`<?php

namespace App\Http\Controllers\API\Exchange;

class KuCoinExt extends \ccxt\kucoin
{
    public function __construct($options = array())
    {
        parent::__construct(array_merge(array('i' => 1), $options));
    }

    public function nonce()
    {
        return $this->microseconds();
    }
}`

`$kucoin = new KuCoinExt([
            'apiKey' => $apiKey,
            'secret' => $apiSecret,
            'verbose' => true
        ]);
return $kucoin->fetchBalance();`
I also tried miliseconds and it was same.
Please help. I am really confused.
Thank you.

**Comment by frosty00** [comment]
do a `kucoin.load_time_difference` equivalent in php to fix

**Comment by kroitor** [comment]
@koushik72 does this help? ↓

```PHP
$kucoin = new KuCoinExt([
    'apiKey' => $apiKey,
    'secret' => $apiSecret,
    'verbose' => true,
    'adjustForTimeDifference' => true,
]);
return $kucoin->fetchBalance();
```

**Offtopic Warning**: the way you create the exchange instance before doing the fetchBalance call and then immediately destroying the instance by issuing `return` – that makes me think that you are instantiating a new exchange everytime you make a call to the exchange – that is a very bad and inefficient way of working with an exchange class instance. I hope that you're not doing it this way and that is just a debug code that you posted above. You should reuse the same class instance for all calls, until you don't need it anymore.

**Comment by koushik72** [comment]
Hi, thank you for the reply. I am not doing it that way. That was just a small piece of code for debugging. 
Mostly, I create an instance and make calls as many as required and then destroy. 
Thank you for your valuable input, btw.

**Comment by koushik72** [comment]
HI, I tried adding `'adjustForTimeDifference' => true,` but it's the same. 
The error still now shows as invalid nonce.
Please help as this is the work for my client and I have the deadline coming soon.
Thank you in advance.

**Comment by frosty00** [comment]
.verbose = True and show output

**Comment by koushik72** [comment]
Hi, I tried and it's worked. Thank you so much for helping me out here.
One thing I noticed. I also tried executing the same code on my Ubuntu server and it worked. 
But on my Windows local machine, it was giving that timestamp error. 
Any idea?

**Comment by kroitor** [comment]
> Any idea?

This is definitely due to time difference, use the verbose mode as described in the [Troubleshooting](https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting) section to compare the values sent and modify the code accordingly. Try without overriding the `nonce`. Hope this answers your question. Closing this for now if you don't mind.

**Comment by koushik72** [comment]
Yes, it's because of the time difference. I noticed one thing which is adding `adjustTimeDifference` and using the microseconds for nonce solved almost all of such problems that I had with any exchange.
