### ISSUE TITLE
Huobi place limit order not working

### ISSUE THREAD

**Issue by ssithuxz** [ccxt/ccxt#3035]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10
- Programming Language version: Python 3.6.2
- CCXT version: 1.14.124
- Exchange: Huobi
- Method: 

```
# -*- coding: utf-8 -*-

import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402


exchange = ccxt.huobipro({
    'apiKey': 'xxx',
    'secret': 'xxx',
    'enableRateLimit': True,
})

symbol = 'zrxbtc'
type = 'limit'  # or 'market'
side = 'buy'  # or 'buy'
amount = 55.0
price = 0.00002357  # or None

# extra params and overrides if needed
params = {
    'test': False,  # test if it's valid, but don't actually place it
}

order = exchange.create_order(symbol, type, side, amount, price, params)

print(order)

```

i am using this code and error is 

`ccxt.base.errors.ExchangeError: huobipro No market symbol zrxbtc`

im pretty sure this is the right symbol for ZRX

**Comment by jvandenaardweg** [comment]
CCXT uses `baseId/quoteId` symbol naming, so the symbol should be `symbol = 'ZRX/BTC'`

**Comment by kroitor** [comment]
```Python
symbol = 'zrxbtc'  # ←--------- should be ZRX/BTC here, as commented by @jvandenaardweg  
type = 'limit'  # or 'market'
side = 'buy'  # or 'buy'
amount = 55.0
price = 0.00002357  # or None
```

**Comment by kroitor** [comment]
@ssithuxz more about it here: 
- https://github.com/ccxt/ccxt/wiki/Manual#markets
- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
