### ISSUE TITLE
Can the library determine if a coin or trading pair is in maintenance mode?

### ISSUE THREAD

**Issue by CatherineGracey** [ccxt/ccxt#3036]
Exchanges will sometimes suspend trading on a coin pair or deposits and withdrawals. Is there a way to determine what is currently suspended or in maintenance mode from the library? I'm working in Node.

**Comment by kroitor** [comment]
Yes, this is currently not very well documented, but we have an `active` flag in `.markets` and a `status` flag in `.currencies` of the exchange, where available. 

Note, that this library is still a work in progress and it is developed actively, so not all markets and not exchange classes have this implemented, moreover, not all exchanges bother to provide that info from their API. So, this entire subject is an ongoing work, these flags and properties may be missing here and there. Just to let you know.

- In `.markets` the `active` boolean flag tells if the market is available for trading (`true`) or not (`false`).
- In `.currencies` the `active` flag tells if the currency is available for funding (`true`) or not (`false`). Funding means both depositing and withdrawing. So, if `exchange.currencies['BTC']['active']` is `false`, you can't deposit or withdraw `BTC` to that exchange.
- **All of the above is available only after loading the market info, as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#loading-markets**

So... in Node:

https://github.com/ccxt/ccxt/blob/master/examples/js/market-status-and-currency-status.js

```JavaScript
'use const'

const ccxt = require ('ccxt')
    , log = require ('ololog')
    , asTable = require ('as-table')

;(async function main () {

    let kraken = new ccxt.kraken ({ enableRateLimit: true })
    await kraken.loadMarkets ()

    const markets = Object.values (kraken.markets).map (market => ({
        symbol: market.symbol,
        active: market.active,
    }))

    log.bright.green.noLocate ('Markets:')
    log.green.noLocate (asTable (markets), '\n')

    const currencies = Object.values (kraken.currencies).map (currency => ({
        code: currency.code,
        active: currency.active,
        status: currency.status,
    }))

    log.bright.yellow.noLocate ('Currencies:')
    log.yellow.noLocate (asTable (currencies))

}) ()
```

<img width="438" alt="screen shot 2018-06-05 at 09 24 37" src="https://user-images.githubusercontent.com/1294454/40958529-4df9e1b4-68a2-11e8-9a53-8d83d8b5051d.png">

If you find that some exchange from our list does provide the necessary info and we don't have it in CCXT, we will be thankful if you let us know, will add it asap.

**Comment by arielorvits** [comment]
Hi,

what is the difference between currency.active and currency.status?

10x!

**Comment by kroitor** [comment]
> what is the difference between currency.active and currency.status?

- `.markets[symbol]['active']` indicates whether you can trade with that symbol
- `.currencies[code]['active']` indicates whether you can fund (deposit and withdraw) your account with that currency
- `.currencies[code]['status']` is an additional string that might indicate the reason for inactivity (`'maintenance'` or some other value, not unified yet).
