### ISSUE TITLE
invalid OHLCV structure (bitlish exchange)

### ISSUE THREAD

**Issue by mkryshchuk** [ccxt/ccxt#3038]
- OS: Ubuntu 18 LTS
- Programming Language version: node.js 10.1.0
- CCXT version: 1.14.102
- Exchange: bitlish
- Method: fetchOHLCV

The response not a flat array. But object
Example:
{"list": [{"to": "1527613200", "data": {"bchbtc": {"low": "0.1322500000000000", "high": "0.1322500000000000", "open": "0.1322500000000000", "close": "0.1322500000000000", "volume": "0.1884688100000000", "open_ts": 1527611602151636, "close_ts": 1527611602151636}, "btceur": {"low": "6400.0000000000000000", "high": "6400.0000000000000000", "open": "6400.0000000000000000", "close": "6400.0000000000000000", "volume": "2.7878937500000000", "open_ts": 1527611523535851, "close_ts": 1527611523535851}, "btcusd": {"low": "7573.4900000000000000", "high": "7573.4900000000000000", "open": "7573.4900000000000000", "close": "7573.4900000000000000", "volume": "0.0320064600000000", "open_ts": 1527611525353030, "close_ts": 1527611748376882}}, "from": "1527609600"}, {"to": "1527616800", "data": {"btceur": {"low": "6410.0000000000000000", "high": "6445.0000000000000000", "open": "6435.0000000000000000", "close": "6443.0000000000000000", "volume": "44.0000000000000000", "open_ts": 1527614696904241, "close_ts": 1527616018897824}, "btcrub": {"low": "418238.0000000000000000", "high": "462842.0000000000000000", "open": "418238.0000000000000000", "close": "462842.0000000000000000", "volume": "0.0001883200000000", "open_ts": 1527613580572367, "close_ts": 1527614380978196}, "btcusd": {"low": "7571.9900000000000000", "high": "7573.2900000000000000", "open": "7571.9900000000000000", "close": "7573.2900000000000000", "volume": "0.0253721400000000", "open_ts": 1527613818399160, "close_ts": 1527614306157632}, "btgbtc": {"low": "0.0056500000000000", "high": "0.0056500000000000", "open": "0.0056500000000000", "close": "0.0056500000000000", "volume": "0.0701000000000000", "open_ts": 1527613328089149, "close_ts": 1527613328089149}, "ethbtc": {"low": "0.0746600000000000", "high": "0.0746600000000000", "open": "0.0746600000000000", "close": "0.0746600000000000", "volume": "0.0242000000000000", "open_ts": 1527613264386646, "close_ts": 1527613264386646}, "hbzbtc": {"low": "0.0000023500000000", "high": "0.0000023500000000", "open": "0.0000023500000000", "close": "0.0000023500000000", "volume": "33.6170572800000000", "open_ts": 1527615149760729, "close_ts": 1527615192653104}}, "from": "1527613200"}, {"to": "1527620400", "data": {"btceur": {"low": "6450.0000000000000000", "high": "6450.0000000000000000", "open": "6450.0000000000000000", "close": "6450.0000000000000000", "volume": "1.0000000000000000", "open_ts": 1527618633803855, "close_ts": 1527618633803855}, "ethusd": {"low": "577.3300000000000000", "high": "577.3300000000000000", "open": "577.3300000000000000", "close": "577.3300000000000000", "volume": "0.0502532300000000", "open_ts": 1527617144520344, "close_ts": 1527617144520344}, "hbzbtc": {"low": "0.0000018000000000", "high": "0.0000021100000000", "open": "0.0000021100000000", "close": "0.0000018000000000", "volume": "59714.1412000000000000", "open_ts": 1527619999757211, "close_ts": 1527619999765414}, "zecusd": {"low": "257.0000000000000000", "high": "257.0000000000000000", "open": "257.0000000000000000", "close": "257.0000000000000000", "volume": "0.0003491400000000", "open_ts": 1527617174254737, "close_ts": 1527617174254737}}, "from": "1527616800"}, {"to": "1527624000", "data": {"ethrub": {"low": "35258.0000000000000000", "high": "35258.0000000000000000", "open": "35258.0000000000000000", "close": "35258.0000000000000000", "volume": "0.0263798700000000", "open_ts": 1527623489433919, "close_ts": 1527623489433919}, "xrpeur": {"low": "0.5458300000000000", "high": "0.5460200000000000", "open": "0.5458300000000000", "close": "0.5460200000000000", "volume": "189.0000000000000000", "open_ts": 1527621456842147, "close_ts": 1527621675877891}}, "from": "1527620400"}, {"to": "1527627600", "data": {"ethrub": {"low": "35262.0000000000000000", "high": "35262.0000000000000000", "open": "35262.0000000000000000", "close": "35262.0000000000000000", "volume": "0.1079775100000000", "open_ts": 1527624275729958, "close_ts": 1527624275729958}, "hbzeth": {"low": "0.0000310000000000", "high": "0.0000310000000000", "open": "0.0000310000000000", "close": "0.0000310000000000", "volume": "3463.7709677400000000", "open_ts": 1527624308848897, "close_ts": 1527624308848897}}, "from": "1527624000"}, {"to": "1527631200", "data": {"ltcusd": {"low": "118.0000000000000000", "high": "122.9300000000000000", "open": "118.0000000000000000", "close": "122.9300000000000000", "volume": "0.0038709800000000", "open_ts": 1527628146905234, "close_ts": 1527628422862210}, "xrpbtc": {"low": "0.0000811100000000", "high": "0.0000811100000000", "open": "0.0000811100000000", "close": "0.0000811100000000", "volume": "8.0000000000000000", "open_ts": 1527631045486671, "close_ts": 1527631045486671}, "zecbtc": {"low": "0.0328600000000000", "high": "0.0328600000000000", "open": "0.0328600000000000", "close": "0.0328600000000000", "volume": "0.0013000000000000", "open_ts": 1527629327834478, "close_ts": 1527629327834478}}, "from": "1527627600"}, {"to": "1527634800", "data": null, "from": "1527631200"}, {"to": "1527638400", "data": {"ethusd": {"low": "579.1200000000000000", "high": "579.1200000000000000", "open": "579.1200000000000000", "close": "579.1200000000000000", "volume": "0.4177717900000000", "open_ts": 1527634846439779, "close_ts": 1527634846439779}}, "from": "1527634800"}, {"to": "1527642000", "data": {"hbzeth": {"low": "0.0000273300000000", "high": "0.0000273400000000", "open": "0.0000273400000000", "close": "0.0000273300000000", "volume": "1000.0000000000000000", "open_ts": 1527638932088746, "close_ts": 1527638932100541}}, "from": "1527638400"}, {"to": "1527645600", "data": null, "from": "1527642000"}, {"to": "1527649200", "data": null, "from": "1527645600"}, {"to": "1527652800", "data": null, "from": "1527649200"}, {"to": "1527656400", "data": {"btcrub": {"low": "430000.0000000000000000", "high": "430000.0000000000000000", "open": "430000.0000000000000000", "close": "430000.0000000000000000", "volume": "0.0325581300000000", "open_ts": 1527656387203928, "close_ts": 1527656387203928}, "ethusd": {"low": "580.9900000000000000", "high": "580.9900000000000000", "open": "580.9900000000000000", "close": "580.9900000000000000", "volume": "0.0233394700000000", "open_ts": 1527655064161057, "close_ts": 1527655064161057}, "ltcusd": {"low": "117.3300000000000000", "high": "117.3300000000000000", "open": "117.3300000000000000", "close": "117.3300000000000000", "volume": "0.1160000000000000", "open_ts": 1527655039452398, "close_ts": 1527655039452398}}, "from": "1527652800"}, {"to": "1527660000", "data": null, "from": "1527656400"}, {"to": "1527663600", "data": {"btcrub": {"low": "430000.0000000000000000", "high": "430000.0000000000000000", "open": "430000.0000000000000000", "close": "430000.0000000000000000", "volume": "0.0174000000000000", "open_ts": 1527661087577260, "close_ts": 1527661087577260}, "hbzbtc": {"low": "0.0000018000000000", "high": "0.0000018000000000", "open": "0.0000018000000000", "close": "0.0000018000000000", "volume": "4333.3333333300000000", "open_ts": 1527662089623326, "close_ts": 1527662089623326}, "hbzeth": {"low": "0.0000305000000000", "high": "0.0000305000000000", "open": "0.0000305000000000", "close": "0.0000305000000000", "volume": "9.8065573800000000", "open_ts": 1527661122764779, "close_ts": 1527661122764779}}, "from": "1527660000"}, {"to": "1527667200", "data": {"hbzeth": {"low": "0.0000305000000000", "high": "0.0000305000000000", "open": "0.0000305000000000", "close": "0.0000305000000000", "volume": "131.1475409800000000", "open_ts": 1527667084512393, "close_ts": 1527667084512393}}, "from": "1527663600"}, {"to": "1527670800", "data": {"btceur": {"low": "6439.0000000000000000", "high": "6439.0000000000000000", "open": "6439.0000000000000000", "close": "6439.0000000000000000", "volume": "9.0000000000000000", "open_ts": 1527669563158673, "close_ts": 1527670440092885}, "etheur": {"low": "503.2600000000000000", "high": "503.2600000000000000", "open": "503.2600000000000000", "close": "503.2600000000000000", "volume": "0.0198108300000000", "open_ts": 1527669047121253, "close_ts": 1527669047121253}, "ethrub": {"low": "35260.0000000000000000", "high": "35260.0000000000000000", "open": "35260.0000000000000000", "close": "35260.0000000000000000", "volume": "0.4075723100000000", "open_ts": 1527670451982291, "close_ts": 1527670451982291}, "ltcbtc": {"low": "0.0160700000000000", "high": "0.0160700000000000", "open": "0.0160700000000000", "close": "0.0160700000000000", "volume": "0.0499000000000000", "open_ts": 1527668239072495, "close_ts": 1527668239072495}, "xdgeur": {"low": "0.0025000000000000", "high": "0.0025000100000000", "open": "0.0025000100000000", "close": "0.0025000000000000", "volume": "4000.0000000000000000", "open_ts": 1527669020407403, "close_ts": 1527669020409328}}, "from": "1527667200"}, {"to": "1527674400", "data": {"bchbtc": {"low": "0.1334900000000000", "high": "0.1334900000000000", "open": "0.1334900000000000", "close": "0.1334900000000000", "volume": "0.0227000000000000", "open_ts": 1527673156493086, "close_ts": 1527673256922550}, "btceur": {"low": "6450.0000000000000000", "high": "6465.0000000000000000", "open": "6450.0000000000000000", "close": "6465.0000000000000000", "volume": "7.0000000000000000", "open_ts": 1527674057516894, "close_ts": 1527674197085980}, "hbzbtc": {"low": "0.0000023100000000", "high": "0.0000023400000000", "open": "0.0000023100000000", "close": "0.0000023400000000", "volume": "200.0000000000000000", "open_ts": 1527670851119954, "close_ts": 1527671747309567}, "hbzeur": {"low": "0.0150000000000000", "high": "0.0150000000000000", "open": "0.0150000000000000", "close": "0.0150000000000000", "volume": "100.0000000000000000", "open_ts": 1527672541375347, "close_ts": 1527672541375347}}, "from": "1527670800"}, {"to": "1527678000", "data": {"btceur": {"low": "6440.0000000000000000", "high": "6465.0000000000000000", "open": "6465.0000000000000000", "close": "6445.0000000000000000", "volume": "15.0000000000000000", "open_ts": 1527674463125011, "close_ts": 1527675441213781}, "btcusd": {"low": "7351.0000000000000000", "high": "7648.9900000000000000", "open": "7648.9900000000000000", "close": "7351.0000000000000000", "volume": "0.0279781300000000", "open_ts": 1527674474244185, "close_ts": 1527676954292706}}, "from": "1527674400"}, {"to": "1527681600", "data": {"btceur": {"low": "6429.3000000000000000", "high": "6440.0000000000000000", "open": "6440.0000000000000000", "close": "6429.3000000000000000", "volume": "15.0334716000000000", "open_ts": 1527678677420449, "close_ts": 1527679449118000}, "ethbtc": {"low": "0.0762100000000000", "high": "0.0762100000000000", "open": "0.0762100000000000", "close": "0.0762100000000000", "volume": "8.6980000000000000", "open_ts": 1527678255402495, "close_ts": 1527678255402495}, "hbzbtc": {"low": "0.0000023000000000", "high": "0.0000023400000000", "open": "0.0000023400000000", "close": "0.0000023000000000", "volume": "699800.0000000000000000", "open_ts": 1527678064651944, "close_ts": 1527680757834127}, "xrpbtc": {"low": "0.0000821500000000", "high": "0.0000821500000000", "open": "0.0000821500000000", "close": "0.0000821500000000", "volume": "787.0000000000000000", "open_ts": 1527679587478631, "close_ts": 1527679587478631}}, "from": "1527678000"}, {"to": "1527685200", "data": {"ethbtc": {"low": "0.0765300000000000", "high": "0.0765300000000000", "open": "0.0765300000000000", "close": "0.0765300000000000", "volume": "1.8326000000000000", "open_ts": 1527683358502983, "close_ts": 1527683358502983}, "hbzbtc": {"low": "0.0000023000000000", "high": "0.0000023100000000", "open": "0.0000023100000000", "close": "0.0000023000000000", "volume": "300000.0000000000000000", "open_ts": 1527681911622043, "close_ts": 1527684504099036}, "xrpbtc": {"low": "0.0000820300000000", "high": "0.0000820400000000", "open": "0.0000820300000000", "close": "0.0000820400000000", "volume": "1703.0000000000000000", "open_ts": 1527681961937166, "close_ts": 1527683916195769}}, "from": "1527681600"}, {"to": "1527688800", "data": {"btceur": {"low": "6437.0000000000000000", "high": "6445.0000000000000000", "open": "6440.0000000000000000", "close": "6445.0000000000000000", "volume": "16.5000000000000000", "open_ts": 1527687094652670, "close_ts": 1527688784895451}}, "from": "1527685200"}, {"to": "1527692400", "data": {"btceur": {"low": "6439.9000000000000000", "high": "6444.0000000000000000", "open": "6440.0000000000000000", "close": "6439.9000000000000000", "volume": "14.0995000000000000", "open_ts": 1527689009110700, "close_ts": 1527691576297450}, "ethbtc": {"low": "0.0756600000000000", "high": "0.0760500000000000", "open": "0.0756600000000000", "close": "0.0760500000000000", "volume": "3.8039000000000000", "open_ts": 1527689469699768, "close_ts": 1527690458668457}, "hbzbtc": {"low": "0.0000023000000000", "high": "0.0000023000000000", "open": "0.0000023000000000", "close": "0.0000023000000000", "volume": "400000.0000000000000000", "open_ts": 1527689374866120, "close_ts": 1527690839425144}, "hbzeth": {"low": "0.0000299000000000", "high": "0.0000300000000000", "open": "0.0000300000000000", "close": "0.0000299000000000", "volume": "2403.0000000000000000", "open_ts": 1527689500207380, "close_ts": 1527689833056956}, "xrpbtc": {"low": "0.0000816500000000", "high": "0.0000816500000000", "open": "0.0000816500000000", "close": "0.0000816500000000", "volume": "911.0000000000000000", "open_ts": 1527689918461032, "close_ts": 1527689918461032}, "zecrub": {"low": "14144.0000000000000000", "high": "14144.0000000000000000", "open": "14144.0000000000000000", "close": "14144.0000000000000000", "volume": "0.1886137800000000", "open_ts": 1527690091742590, "close_ts": 1527690165342226}}, "from": "1527688800"}, {"to": "1527696000", "data": {"btceur": {"low": "6350.0000000000000000", "high": "6350.0000000000000000", "open": "6350.0000000000000000", "close": "6350.0000000000000000", "volume": "5.0000000000000000", "open_ts": 1527694863247897, "close_ts": 1527694863247897}, "btcusd": {"low": "7333.0000000000000000", "high": "7655.9000000000000000", "open": "7655.9000000000000000", "close": "7333.0000000000000000", "volume": "0.4504277400000000", "open_ts": 1527692891307896, "close_ts": 1527694791140859}, "etheur": {"low": "493.0500000000000000", "high": "493.0900000000000000", "open": "493.0500000000000000", "close": "493.0900000000000000", "volume": "3.0157000000000000", "open_ts": 1527694868282930, "close_ts": 1527695151636698}, "hbzeth": {"low": "0.0000270000000000", "high": "0.0000277000000000", "open": "0.0000277000000000", "close": "0.0000270000000000", "volume": "289197.6344000000000000", "open_ts": 1527694520439616, "close_ts": 1527695805717289}, "hbzeur": {"low": "0.0100000000000000", "high": "0.0200000000000000", "open": "0.0150000000000000", "close": "0.0100000000000000", "volume": "117195.5486000000000000", "open_ts": 1527694849822604, "close_ts": 1527695144465494}, "ltcrub": {"low": "7619.0000000000000000", "high": "7619.0000000000000000", "open": "7619.0000000000000000", "close": "7619.0000000000000000", "volume": "0.0000175600000000", "open_ts": 1527693709951501, "close_ts": 1527693709951501}}, "from": "1527692400"}, {"to": "1527699600", "data": {"btceur": {"low": "6310", "high": "6320.1", "open": "6320", "close": "6320.1", "volume": 10.66866029, "open_ts": 1527696561665637, "close_ts": 1527699490102371}, "etheur": {"low": "491.78", "high": "491.78", "open": "491.78", "close": "491.78", "volume": "1.96197486", "open_ts": 1527697456971222, "close_ts": 1527697456971222}, "ethrub": {"low": "34240", "high": "34240", "open": "34240", "close": "34240", "volume": "0.001423", "open_ts": 1527699168901580, "close_ts": 1527699168901580}, "ethusd": {"low": "563.76", "high": "563.76", "open": "563.76", "close": "563.76", "volume": "1.8", "open_ts": 1527696585604700, "close_ts": 1527696585604700}, "hbzeth": {"low": "0.000026", "high": "0.0000265", "open": "0.0000265", "close": "0.000026", "volume": 10697.47444844, "open_ts": 1527696376502487, "close_ts": 1527698665403418}, "ltcrub": {"low": "7339", "high": "7340", "open": "7339", "close": "7340", "volume": 3.05917182, "open_ts": 1527698769363121, "close_ts": 1527699008461534}}, "from": "1527696000"}]}

**Comment by kroitor** [comment]
This is a known bug with bitlish: 

- https://github.com/ccxt/ccxt/issues/1948
- https://github.com/ccxt/ccxt/issues/2937

Hope to fix it soon.
