### ISSUE TITLE
marketsell and buy

### ISSUE THREAD

**Issue by hippylover** [ccxt/ccxt#3045]
Hi. Just wondering if marketsell and buy order will be(if possible) implemented on:

bitfinex2
bittrex
bleutrade
cryptopia
kucoin
liqui
poloniex
tidex
yobit

or if it's possible to just set a low ask or high bid and get the same functionality on these exchanges? I can test it myself of course just wondering if anyone remember already or have tested.

Au revoir!

**Comment by kroitor** [comment]
>  Just wondering if marketsell and buy order will be(if possible) implemented on:

This is shown in the following table:

<img width="1508" alt="screen shot 2018-06-05 at 16 56 29" src="https://user-images.githubusercontent.com/1294454/40980599-72ce49a0-68e1-11e8-8522-8483f075d460.png">

> or if it's possible to just set a low ask or high bid and get the same functionality on these exchanges?

Yep, this is possible, as documented here:

https://github.com/ccxt/ccxt/wiki/Manual#market-orders

Let us know if this does not answer your questions. Thx!

**Comment by hippylover** [comment]
But it's on account of that table i surmised that marketorder is not supported on the exchanges i listed!

**Comment by kroitor** [comment]
> But it's on account of that table i surmised that marketorder is not supported on the exchanges i listed!

Yes, but this is the question you've asked in the first place: whether those exchange have a market order capability or not. The table shows that they don't have it, it answers to your first question. Then you asked the second question if it is possible to emulate it with a low price or high price, and that question is also answered positively – all about it in the Manual. So, I guess, at this point, both of your questions are answered? ) Let us know if not )

**Comment by hippylover** [comment]
I thought the table showed whether or not ccxt supported marketorders not whether or not the exchange supported the functionality. I didn't realize ccxt was so far along with support(?)

And the manual says be careful if you are to emulate a market order but i suppose this is meant for decentralized exchanges with no order matching...(?)

**Comment by kroitor** [comment]
> I thought the table showed whether or not ccxt supported marketorders not whether or not the exchange supported the functionality. I didn't realize ccxt was so far along with support(?)

The table shows both – whether the exchange does support it or not, and whether CCXT does support it or not. For market orders, the `has['createMarketOrder']` is `true` by default, and we explicitly set it to `false`, if the exchange in question does not offer that order type at all. So for `has['createMarketOrder'] the table shows whether the exchanges support it, and we in ccxt tend to support as many methods as offered by the exchange. If CCXT does not support it in the unified API, you can still get away with CCXT implicit API, as described in the Manual, here: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

> And the manual says be careful if you are to emulate a market order but i suppose this is meant for decentralized exchanges with no order matching...(?)

Nope, this has nothing to do with DEXes, more with the price slippage. If you don't choose your low price or high price carefully enough, you can get your order filled accidentally for an undesireable price. You want to make sure that your price is well beyond the market price.
