### ISSUE TITLE
New exchange: Robinhood

### ISSUE THREAD

**Issue by ahonnecke** [ccxt/ccxt#3049]
Robinhood allows for trading BTC and ETH now, although the wallets remain held by robinhood, you can buy and sell crypto:
https://crypto.robinhood.com/

**Comment by omidkrad** [comment]
Robinhood provides commission-free crypto trading, I wonder why there is not enough interest/request for supporting the exchange here! Even though there is no official API, but people have reverse engineered it and already using it.

https://github.com/aurbano/robinhood-node

**Comment by nuaimat** [comment]
@achillesrasquinha unofficial APIs are better than nothing for sure

**Comment by omidkrad** [comment]
Unofficial APIs are basically undocumented official APIs, so I guess they should be fine.

**Comment by frosty00** [comment]
not planned / not a crypto exchange
