### ISSUE TITLE
Cryptopia fetch OHLCV not working with 1 or 5 minutes

### ISSUE THREAD

**Issue by AmFreaks** [ccxt/ccxt#3052]
Seems like cryptopia changed their fetchOHLCV settings as referenced here:
https://github.com/ccxt/ccxt/issues/2815

Now the following is true for dataRange:
0 or 1 = 1 month
2 or 3 = 3 months
3 or 4 = 6 months
5 or 6 = 12 months
7 =  574 days
8 or higher = 1 month

dataGroup can be anything from 1 (=1 minute) to anything in range (so upto 574 days * minutes).
I saw that 1 minute and 5 minutes is currently missing so would be nice if it could be added in the next version.

Examples
3 months in day (1440 min) candles;
https://www.cryptopia.co.nz/Exchange/GetTradePairChart?tradePairId=4369&dataRange=3&dataGroup=1440
1 month in 345 min candles:
https://www.cryptopia.co.nz/Exchange/GetTradePairChart?tradePairId=4369&dataRange=1&dataGroup=345
1 month in 1 min candles (BEWARE- will take a while):
https://www.cryptopia.co.nz/Exchange/GetTradePairChart?tradePairId=4369&dataRange=1&dataGroup=1

**Comment by kroitor** [comment]
The exchange has been closed down: https://github.com/ccxt/ccxt/issues/5151
