### ISSUE TITLE
Is there a way to get historical data like this...

### ISSUE THREAD

**Issue by djporterco** [ccxt/ccxt#3059]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: MAC High Sierra 10.13.4
- Programming Language version:  Python 3.6.5 :: Anaconda
- CCXT version:  ccxt (1.0.1)
- Exchange: Binance
- Method: .fetch_tickers() thats the question...

I need this information but historically.. Any chance it's available with another method or an added parameter?

`{
symbol: "ETHBTC",
priceChange: "0.00055500",
priceChangePercent: "0.700",
weightedAvgPrice: "0.07937355",
prevClosePrice: "0.07921700",
lastPrice: "0.07979000",
lastQty: "0.00100000",
bidPrice: "0.07972000",
bidQty: "0.00100000",
askPrice: "0.07979000",
askQty: "0.45800000",
openPrice: "0.07923500",
highPrice: "0.08050000",
lowPrice: "0.07769500",
volume: "120545.66600000",
quoteVolume: "9568.13732981",
openTime: 1528164315989,
closeTime: 1528250715989,
firstId: 66731510,
lastId: 66930310,
count: 198801
},`

**Comment by kroitor** [comment]
You're probably looking for OHLCV data: https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts

`OHLCV` means historical data for `open, high, low, close, volume`.

If you want to save current market prices as well, then you will have to build a system that will poll the exchanges and will save the data to your database continuously.

Let us know if this does not answer your question. Thx!

**Comment by djporterco** [comment]
thanks
