### ISSUE TITLE
Extra headers and Keep-Alive supports

### ISSUE THREAD

**Issue by atjason** [ccxt/ccxt#3068]
Hi,

1. Is there any way to set extra headers for an exchange?
2. If not, suggest add Keep Alive support for [BitMex](https://github.com/ccxt/ccxt/blob/master/js/bitmex.js): 

```js

    sign (path, api = 'public', method = 'GET', params = {}, headers = undefined, body = undefined) {
///
            headers = {
///
                'Connection': 'Keep-Alive',
                'Keep-Alive': '90',
            };
        }
///
    }

```

Related doc: [BitMex REST API HTTP-Keep-Alive](https://www.bitmex.com/app/restAPI#HTTP-Keep-Alive)

- OS: Ubuntu 16.04
- Programming Language version: js
- CCXT version: 1.14.152
- Exchange: bitmex
- Method: fetchOrder

**Comment by kroitor** [comment]
Hi!

> Is there any way to set extra headers for an exchange?

Yes. To set extra headers... use the `.headers` property of the exchange ))

```JavaScript
exchange.headers = {
    'User-Agent': 'foobar',
    ...,
}
```

... or via the constructor params:

```Javascript
exchange = new ccxt.bitmex ({
    headers: {
        'Foobar': '1234567890',
    },
})

This is documented here: https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

However, for the fetch API + keep-alive, you don't really want to set the `.headers`, instead, you should use the `.agent` property, as described here: https://github.com/bitinn/node-fetch/issues/423#issuecomment-372188655

Hope this answers your question.

**Comment by atjason** [comment]
@kroitor Thanks for your swift response.
