### ISSUE TITLE
Nonce has already been used for this request - Cryptopia

### ISSUE THREAD

**Issue by rhrahul** [ccxt/ccxt#3070]
Hi,
I can't share whole code, because it's bit messy.
But I can show you function calling structure.

```
setInterval(()=>{
      let orderstat = cryptopia.fetchOrder(orderid, pair);
      if(orderstat['remaining'] > 0){
             setTimeout(()=>{
                   cryptopia.cancelOrder(orderid);
             }, cryptopia.rateLimit);
      }
},30000)
```

and in output i am getting this error,
`Error: cryptopia {"Success":false,"Error":"Nonce has already been used for this request."}`

Please help me.
Thanks

- OS: Windows 10
- Programming Language version: Angular 4
- CCXT version: latest
- Exchange: Cryptopia
- Method: All Private Methods

**Comment by kroitor** [comment]
> i am getting this error,

↓

> because it's bit messy.

Usually, when I make my code less messy, it suddenly starts to work ;)

Let's start with the simple questions: do you use the built-in rate-limiting? Because if you don't and you're trying to do manual rate-limiting – it's very easy to screw up and miss exception handling like you did in your example, and to also make a lot of other logical mistakes with timing as well... Moreover, you're not using fetchOrder properly, as it returns a [JavaScript Promise](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise).

So, I'd recommend to learn to use the promises properly in an Angular ES5 / ES6 environment and also use built-in CCXT rate-limiting:

```JavaScript

// ...
// ...
// ...

cryptopia.enableRateLimit = true // somewhere before calling the next construct

function fetchOrderAndCancelIfRemaining (cryptopia, orderId) {
    cryptopia.enableRateLimit = true
    cryptopia.fetchOrder (orderId, pair).then (order => {
        if (order['remaining'] >0) {
            cryptopia.cancelOrder (orderId).catch (error => {
                console.log ('cancelOrder error:', error.constructor.name, error.message)
            })
        }
    }).catch (error => {
        console.log ('createOrder error:', error.constructor.name, error.message)
    })
}

fetchOrderAndCancelIfRemaining ()
```

Does this answer your question?

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki/Manual#invalidnonce
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

> Check your request rate if you are getting nonce errors. Your private requests should not follow one another quickly. You should not send them one after another in a split second or in short time. The exchange will most likely ban you if you don't make a delay before sending each new request. In other words, you should not hit their rate limit by sending unlimited private requests too frequently. Add a delay to your subsequent requests, like show in the long-poller [examples](https://github.com/ccxt/ccxt/tree/master/examples).

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#authentication

**Comment by rhrahul** [comment]
I thought you would ignore that promising.
Sorry, let me give you proper code,

`setInterval(async()=>{
      let orderstat = await cryptopia.fetchOrder(orderid, pair);
      if(orderstat['remaining'] > 0){
             setTimeout(()=>{
                   await cryptopia.cancelOrder(orderid);
             }, cryptopia.rateLimit);
      }
},30000)`

is this ok ??

**Comment by kroitor** [comment]
```JavaScript
// ...
// ...
// ...

cryptopia.enableRateLimit = true // somewhere before calling the next construct

async function fetchOrderAndCancelIfRemaining (cryptopia, orderId) {
    let order = undefined
    try {
        order = await cryptopia.fetchOrder (orderId, pair)
    } catch (e) {
        console.log ('createOrder error:', error.constructor.name, error.message)
        alert ('createOrder error: ' + error.constructor.name + error.message)
    }
    if (order['remaining'] >0) {
        try {
            await cryptopia.cancelOrder (orderId)
        } catch (e) {
            console.log ('cancelOrder error:', error.constructor.name, error.message)
            alert ('cancelOrder error: ' + error.constructor.name + error.message)
        }
    }
}

fetchOrderAndCancelIfRemaining ()
```

**Comment by kroitor** [comment]
I'd close this for now, as this nonce issue is documented here and in links above, also, there's a lot of dupes in the closed issues already. Let me know if you still have difficulties with it after reading the above.

**Comment by rhrahul** [comment]
Ok, thanks :)
I'll check it, I am sure it will work.
