### ISSUE TITLE
TypeError: fetch_order_book() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by Roibal** [ccxt/ccxt#3072]
- OS: Windows 10
- Programming Language version: Python 3.6
- CCXT version: Latest
- Exchange: Binance (Any)
- Method: fetch_order_book()
Hello All,

when I try to run 'fetch_order_book()' for some reason it is giving me the error in the title. I've never had this challenge before (usually self is implied/default)? I've tried switching exchanges, etc. For some reason this function is just not working for me.

**Comment by Roibal** [comment]
```
import ccxt
depth = ccxt.anxpro.fetch_order_book('BTC/AUD')
print(depth)
```

Result:
**depth = ccxt.anxpro.fetch_order_book('BTC/AUD')

TypeError: fetch_order_book() missing 1 required positional argument: 'symbol'**

**Comment by kroitor** [comment]
Looks like you don't have Python experience at all...

```
anxpro → anxpro()
```

↓

```Python
import ccxt
depth = ccxt.anxpro().fetch_order_book('BTC/AUD')
print(depth)
```

or

```Python
import ccxt
print(ccxt.anxpro().fetch_order_book('BTC/AUD'))
```

**Comment by Roibal** [comment]
Wow, that was quite rude. To be fair, I've never seen a function being able to be called like that (with a following method). Don't worry man, you won't be seeing much of me.

**Comment by kroitor** [comment]
> Wow, that was quite rude.

Sorry, didn't mean anything offensive.

> To be fair, I've never seen a function being able to be called like that (with a following method).

```Python
print(ccxt.anxpro().fetch_order_book('BTC/AUD'))
```

is lexically/logically the same as

```Python
anxpro = ccxt.anxpro()
print(anxpro.fetch_order_book('BTC/AUD'))
```

> Don't worry man, you won't be seeing much of me.

Don't take it too seriously, but pay attention to the docs first.

**Comment by kroitor** [comment]
@Roibal btw, i'm watching the course you're creating, and you're doing a great job reviewing it. Do you mind if we add links to your videos into our examples section? If not, can you plz post an ordered/structured list of links to your youtube series? As far as I get, there's many of them in parallel, and the list would help a lot, as I got lost a bit in what's where on reddit. Anyways, let me know if that would be interesting to you. Thx! )

**Comment by Roibal** [comment]
@kroitor hi my friend, thank you for your kind comments, here is a pretty good playlist, feel free to add it wherever, thanks for the code, very great.

https://www.youtube.com/playlist?list=PLIFBTFgFpoJ-xGRz3v_2nF7f9HKZrfSpj&playnext=1&index=1

also please feel to join my telegram for discussing crypto trading bots, we cover ccxt fairly often:

https://t.me/joinchat/JL3rUw3EHmrPP0Nl355tgA

**Comment by Roibal** [comment]
@kroitor the playlist I linked basically discusses converting a basic binance bot to CCXT, then added functionality, etc.

**Comment by Roibal** [comment]
@kroitor also I have many examples of bots (TRI ARB, Basic bot) which utilize CCXT, you may be interested in those as well.

**Comment by Princeton007** [comment]
@Roibal Hi, I tried to join the group but it seems not to exist, can you post a fresh link?
