### ISSUE TITLE
Bibox fetchOrder, order id and trade id relation

### ISSUE THREAD

**Issue by Showgofar** [ccxt/ccxt#3073]
- OS: Debian
- Programming Language version: Php
- CCXT version: latest
- Exchange: bibox
- Method: create_order, fetch_open_orders fetch_closed_orders fetch_my_trade

Hi
When i create order on bibox with "market price" (sell cheaper than current price)
its impossible to find out real price and fee

Is there any way to find out corresponding trades by orderID like on binance for example?
Thank you

**Comment by benediamond** [comment]
@Showgofar @kroitor I believe another way of saying this is that `fetch_order` is currently `NotSupported` by bibox---yes?

Are you aware of any obstacles to adding this support? If not, I might attempt to write an implementation.

**Comment by kroitor** [comment]
@benediamond 

> I believe another way of saying this is that fetch_order is currently NotSupported by bibox---yes?

Yep, `fetch_order` / `fetch_order_trades` is not yet implemented for Bibox.

> Are you aware of any obstacles to adding this support?

The one and only main obstacle is their very vague and unclear docs.

>  If not, I might attempt to write an implementation.

That would be awesome! Just make sure to read this: 
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

Thx!

**Comment by benediamond** [comment]
@kroitor what about this...?
```javascript
// obtain pending order by id
cmd: "orderpending/order"
body: {
    id,           //pending order id 
}
Return result：
{
    "result":{
        "id":159,
        "createdAt": 1512756997000,
        "account_type":0,                       //account type 0-regular account，1-margin account
        "pair":"LTC_BTC",                       //pair
        "coin_symbol":"LTC",                    //coin type
        "currency_symbol":"BTC",                //currency type
        "order_side":2,                         //order side，1-bid，2-ask
        "order_type":2,                         //order type，1-market order，2-limit order
        "price":0.009,                          //price，market order is 0
        "amount":1,                             //amount，market order buy is 0
        "money":0.009,                          //money，market order sell 0
        "deal_amount":0,                        //deal amount
        "deal_price":"0.00900000",              //deal price
        "deal_money":"0.00900000",              
        "deal_percent":"0.00%",                 //deal percentage
        "status":3                              //status，1-pending，2-part completed，3-completed，4-part canceled，5-canceled，6-canceling
    },
    "cmd":"orderpending/order"
}
```
from https://github.com/Biboxcom/api_reference/wiki/home_en

**Comment by kroitor** [comment]
@benediamond 

> @kroitor what about this...?

It's ok ) However, the original question was about the relation of `trade id` to `order id` (see `fetchOpenOrders` vs `fetchMyTrades`)... I guess, current Bibox implementation in CCXT s confusing personal trades with closed order history. Whereas the closed order history is split on Bibox on two types "pending/active closed order" and "historical closed order"... This is what is really confusing here.

**Comment by kroitor** [comment]
@benediamond also related: https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades

**Comment by benediamond** [comment]
@kroitor yes, understood. but if we're only interested in checking the status/size/amount for a particular _order_ id, then this can be done, using this information?

what's the difference between pending/active closed order and historical closed order on bibox?

**Comment by benediamond** [comment]
@kroitor:

> Yes, but only if we're interested in just the order info. However, sometimes we are also interested in trade info per order. And this is what the author of this issue is actually interested in and was asking about in the first place.

Ok, maybe I should raise a separate issue. Personally, I'm only interested in if my order filled, etc. An implementation of `fetch_order` could be done pretty easily using that endpoint above, yes?

**Comment by kroitor** [comment]
> Ok, maybe I should raise a separate issue.

No need for it, as these two are really related, almost duplicate.

> An implementation of fetch_order could be done pretty easily using that endpoint above, yes?

Yep.

**Comment by kroitor** [comment]
Bibox `fetchOrder` added in #3094, thx @benediamond , will be available in CCXT 1.14.168 shortly.

**Comment by Showgofar** [comment]
But it doesn't solve the problem =)
There is no way to find related trades from the order

**Comment by kroitor** [comment]
> There is no way to find related trades from the order

We will query Bibox on this. At least, we now have a way to deduce more order fields ;)

**Comment by benediamond** [comment]
@Showgofar yes, there are two separate problems here---querying orders and querying trades. However, https://github.com/ccxt/ccxt/pull/3096 may be helpful to you? this won't tie trades to a particular order, but at least it will dump _all_ of them.

**Comment by Showgofar** [comment]
hmm...
fetch_my_trades and fetch_closed_orders returns the same\identical response now ..
I had checked and there is no trades anymore (usually trades has different timestamps than orders if it is not market trade)

**Comment by benediamond** [comment]
@Showgofar yes, good catch... But help me out, which of the two is correct? Are you saying that these are orders, not trades?

**Comment by benediamond** [comment]
how could "price" and "deal_price" be different? if it's a market order there is no "price", and if it's a limit order the prices should be the same.

**Comment by Showgofar** [comment]
Price is ask price or initial price, deal_price is real trade price.
Simple example if you try to buy 1eth for 1 btc
you will see something like that
"price": "1",
"deal_price": "real_market_price"

\\ so that fetch_closed_orders is correct
yes
\\but fetch_my_trades is not?
yes

**Comment by benediamond** [comment]
@kroitor this has become a rabbit hole. but, I as I understand @Showgofar:

the problem is that, after executing a _market_ order, we want to go back and figure out the (average) price (or cost) it executed at. but, on bibox, the trades returned by `fetchMyTrades` contain no `order` value that would indicate the order they came from. thus it's hard to find this value.

Correct me if i'm wrong: the same problem is present in Huobi? I'm seeing that `trade['order'] == None` for each trade returned by `fetch_my_trades`.

**Comment by Showgofar** [comment]
but cost and price deal_price and  deal_money are quite ok

**Comment by kroitor** [comment]
> the problem is that, after executing a market order, we want to go back and figure out the (average) price (or cost) it executed at. but, on bibox, the trades returned by fetchMyTrades contain no order value that would indicate the order they came from. thus it's hard to find this value.

Exactly.

> Cost and price from deal_price and deal_money are quite ok

@Showgofar do you still have a problem with it with the current version? If so, could you please post your verbose request and verbose response, precisely as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?
