### ISSUE TITLE
Coin symbol inconsistencies list

### ISSUE THREAD

**Issue by dmig** [ccxt/ccxt#3077]
- Programming Language version: python 3.6.5
- CCXT version: 1.14.138
- Method: fetchCurrencies

I made a check for 2 types of symbol inconsistencies between some supported exchanges:
- different coins under same symbol
- different symbols of one coin

Major downside of this check: it depends on `fetchCurrencies` method. For yobit I parsed coins info page.
So, Yobit symbols are private, other exchange's symbols are common.

Here are 2 lists with found problems.
[different-names.txt](https://github.com/ccxt/ccxt/files/2080980/different-names.txt)
[name-collisions.txt](https://github.com/ccxt/ccxt/files/2080981/name-collisions.txt)

**Comment by dmig** [comment]
Tools used: https://gist.github.com/dmig/0a9ef224561b515f44d4710cc82863d1

1. run `ccxt-coins-dump.py > coins.tsv`
2. run `yobit-coins-dump.py >> coins.tsv`
3. `sort coins.tsv > coins-sorted.tsv`
4. run `coins-reduce.py coins-sorted.tsv > coins-reduced.tsv`
5. manually look thru `coins-reduced.tsv`:
   - on 1st column for same symbol inconsistencies
   - on 2nd column for different symbol inconsistencies (this can be automated a little)

**Comment by frosty00** [comment]
>  For yobit I parsed coins info page.

This ignores the `commonCurrencies` we have already populated for yobit, so pretty much all your references to yobit in this list are already taken into account during automatic symbol conversion.

**Comment by dmig** [comment]
I thing I noticed about Poloniex: `fetchCurrencies` reports some currencies, that are dead for a long time and likely were delisted.

Sometimes exchange doesn't have API for `fetchCurrencies`, but reports coin names with some other method. Is `fetchCurrencies` emulated in this case?

**Comment by frosty00** [comment]
`.currencies` are generated by `fetchMarkets` which splits the symbol to make a base and quote currency. Unfortunately currencies made via this method lack a `name` field and but may have other metadata loaded in. Poloniex is a shady exchange I would be careful with them until they get their act together.

**Comment by dmig** [comment]
One more collision for PLC symbol: Cryptopia has Polcoin, not PlusCoin as many others

**Comment by dmig** [comment]
One more not included:
```
SCT	ScryptToken	yobit
SCT	Soma	coinmarketcap, cryptopia
SCT	SpaceCoin	livecoin
```

**Comment by dmig** [comment]
One more, is in list, discovered new exchange info -- EDR is for 'Endor Protocol' on Kucoin

**Comment by frosty00** [comment]
@kroitor I would keep this open as it has some useful python scripts to check for `commonCurrencies`

**Comment by dmig** [comment]
I'll make another check with latest library version. Also'll try to get coin names for more exchanges.
