### ISSUE TITLE
[Question] Improving API secrets security with ccxt?

### ISSUE THREAD

**Issue by AoDev** [ccxt/ccxt#3080]
- OS: any
- Programming Language version: JS

Hello, I am trying to secure API secrets.

I am not too knowledgeable about security best practices in this case. but my goal is to do the best that can be done.

Right now ccxt holds the API's credentials in any instance. 
like ` const client = new ccxt.kraken({apiKey, secret})` -> can read `client.secret`.

There are a few circumstances in which these could be revealed wrongly. (dev tools, logs, stacktraces, etc)

* First, is this an actual problem?
* If yes, is there anything we could do to improve?

eg: in my app, I store encrypted API credentials and I decrypt them at run time, before calling methods. In other situations, I keep the secret in a closure so that the variable isn't exposed (Javascript)

For eg: I wouldn't want the secrets to be sent to a service like [sentry.io](https://sentry.io/welcome/) by mistake.

**Comment by cartercarlson** [comment]
Hey AoDev,

I had a similar question not too long ago.  Hope this helps.

https://github.com/ccxt/ccxt/issues/3492

-Carter
