### ISSUE TITLE
ccxt.base.errors.ExchangeError: allcoin

### ISSUE THREAD

**Issue by venomx6** [ccxt/ccxt#3091]
- OS: Win 10
- Programming Language version: Python 3.6
- CCXT version: 1.14.165
- Exchange: Allcoin
- Method: https://github.com/ccxt/ccxt/blob/master/examples/py/arbitrage-pairs.py

Trying to compare any exchange pairs with Allcoin pairs returns :
`ccxt.base.errors.ExchangeError: allcoin GET https://www.allcoin.com/Home/MarketOverViewDetail/ Expecting value: line 1 column 1 (char 0) <html xmlns="http://www.w3.org/1999/xhtml">`
![1234](https://user-images.githubusercontent.com/39489983/41192389-97a23d82-6c05-11e8-8abf-393d9593879a.jpg)

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/2962
