### ISSUE TITLE
Request to read /api/v1/exchangeInfo for information on rate limits

### ISSUE THREAD

**Issue by tomastelensky** [ccxt/ccxt#3093]
Don't know how general this is among exchanges, but Binance offers the possibility to read details on rate limits:

As noted in the [Binance API docs](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md):

> The /api/v1/exchangeInfo rateLimits array contains objects related to the exchange's REQUESTS and ORDER rate limits.

By sending this request, you can [get very useful info](https://www.reddit.com/r/binance/comments/7h9exv/api_request_rate_limits/):

```json
"rateLimits": [{
    "rateLimitType": "REQUESTS",
    "interval": "MINUTE",
    "limit": 1200
  },
  {
    "rateLimitType": "ORDERS",
    "interval": "SECOND",
    "limit": 10
  },
  {
    "rateLimitType": "ORDERS",
    "interval": "DAY",
    "limit": 100000
  }
]
```

Is it possible to send this request via some ccxt method? (Without doing it in the raw REST API). I haven't found this in the docs. If not, please take this as a feature request :-)

- Exchange: Binance

**Comment by kroitor** [comment]
> Is it possible to send this request via some ccxt method?

Sure!

1. This info is propagated as market properties:

- https://github.com/ccxt/ccxt/wiki/Manual#markets
- https://github.com/ccxt/ccxt/wiki/Manual#market-structure
- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

```JavaScript
// JavaScript
const ccxt = require ('ccxt')
const binance = new ccxt.binance ()
(async () => {
    await binance.publicGetExchangeInfo ();
    const symbol = 'ETH/BTC' // or any other binance symbol
    // console.log (binance.symbols) // uncomment to see them all
    console.log ('Binance rate limits and other info for', symbol)
    console.log (binance.markets[symbol]['info'])
}) ()

```

2. With implicit methods (not recommended):

https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

```JavaScript
// JavaScript
const ccxt = require ('ccxt')
const binance = new ccxt.binance ()
(async () => {
    const response = await binance.publicGetExchangeInfo ();
    // parse per symbol it yourself
}) ()
```
