### ISSUE TITLE
How to calculate profit/loss with fetchMyTrades?

### ISSUE THREAD

**Issue by Stas-Buzunko** [ccxt/ccxt#3101]
I need to calculate profit/loss (difference in price is USD) of coins hold over the time. 
As I understand, the only way to do it is by fetching all account trades for this coin pair? Is it even possible to get all trades?

As I understand, fetchMyTrades is not fully implemented? I'm interested in Coinbase (thanks for adding it), Bittrex, Binance and Bitfinex.

P.S. Is it possible to find out pair coin that was used for purchase? In Balance we have X BTC for example, can I know how it was purchased?

**Comment by kroitor** [comment]
> As I understand, the only way to do it is by fetching all account trades for this coin pair? Is it even possible to get all trades?

Yep, it is possible, however, this cannot be done without some proper logic on your side: 

- https://github.com/ccxt/ccxt/wiki/Manual

> As I understand, fetchMyTrades is not fully implemented? 

Exactly. However...

> I'm interested in Coinbase (thanks for adding it), Bittrex, Binance and Bitfinex.

From your list:
- Coinbase is not an exchange at all, it's more a wallet service
- Bittrex does not offer fetchMyTrades at all (they offer closed orders history instead)
- Binance has fetchMyTrades implemented
- Bitfinex has fetchMyTrades implemented

> P.S. Is it possible to find out pair coin that was used for purchase?

You will have to fetch personal trades, closed orders and then traverse that info how you need.

- https://github.com/ccxt/ccxt/wiki/Manual#personal-trades

Hope this answers your question.
