### ISSUE TITLE
fetch_open_orders in coinegg didn't work

### ISSUE THREAD

**Issue by quantminer22** [ccxt/ccxt#3102]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:
The fetch_open_orders method encounters an anti-DPOS. 
Is it a problem with the encapsulation?
input:
import ccxt
Exchange = ccxt.coinegg()
AITtoBTCopenOrders = Exchange.fetch_open_orders(symbol='AIT/BTC')

return:
DDoSProtection: coinegg https://www.coinegg.com/coin/btc/allcoin?t=1528716585483 GET 503 Server Error: Service Temporarily Unavailable for url: https://www.coinegg.com/coin/btc/allcoin?t=1528716585483 <!DOCTYPE HTML>
<html lang="en-US">

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:windows
- Programming Language version:pyhon3.6
- CCXT version:1.14.172
- Exchange:coinegg
- Method:fetch_open_orders
![_20180611193748](https://user-images.githubusercontent.com/40168779/41229534-f6723614-6dae-11e8-94af-2688bfcce579.png)

**Comment by kroitor** [comment]
Use the cloudscraper to bypass it:

- https://github.com/ccxt/ccxt/blob/master/examples/py/bypass-cloudflare-with-cookies.py
- https://github.com/ccxt/ccxt/blob/master/examples/py/bypass-cloudflare.py

Let us know if it does not help.
