### ISSUE TITLE
How to read data which in API's headers

### ISSUE THREAD

**Issue by deltacat** [ccxt/ccxt#3103]
- OS: Ubuntu 16.04
- Programming Language version: Nodejs v10
- CCXT version: 1.14.169
- Exchange: bitmex
- Method: Any

Some useful information is returned by API response headers. such as: 
https://testnet.bitmex.com/app/restAPI#Viewing-Your-Request-Rate-Limit

I cannot find where can I read these data from ccxt unified API. Any solution for such case?

**Comment by kroitor** [comment]
You can use `exchange.last_respone_headers` property of your exchange class instance to get the most recent headers replied to you. That property changes over time as you make more and more requests. This is not the best way to access headers, but you can use it until we come up with a better design for this aspect. Hope it answers your question, let us know if not.

**Comment by vsmelov** [comment]
you have a typo
```exchange.last_response_headers
```
not 
```exchange.last_respone_headers
```
spent 1 hour trying to find out the error just by copy paste :-)

**Comment by kroitor** [comment]
@vsmelov oops, pardon... %)
