### ISSUE TITLE
New Exchange: FCoin

### ISSUE THREAD

**Issue by xiangzz159** [ccxt/ccxt#3107]
FCoin allows for trading main symbol.You can buy and sell crypto:
https://www.fcoin.com/

**Comment by kroitor** [comment]
Do they have an API ?

**Comment by xiangzz159** [comment]
doc：https://developer.fcoin.com/zh.html

**Comment by CHANGAIQING** [comment]
When will it be released FCoin?

**Comment by cloudseasail** [comment]
Vote for this :)
there is simple api here. [https://github.com/weiliuv/fcoin-python-sdk](https://github.com/weiliuv/fcoin-python-sdk)

Looking forward to integration with ccxt
thanks!

**Comment by ChenLi0830** [comment]
+1

**Comment by xiangzz159** [comment]
https://github.com/xiangzz159/ccxt/blob/master/python/ccxt/fcoin.py

**Comment by kroitor** [comment]
> now ccxt could support fcoin?

Yep, however, it will need a bit of code conversion and merging. But, yeah, this isn't really a problem, more like a routine, so it's just a matter of time now.

**Comment by kroitor** [comment]
Added in 1.15.8. Thx for your patience!
