### ISSUE TITLE
Indodax New Coins

### ISSUE THREAD

**Issue by santos-sabanari** [ccxt/ccxt#3108]
Please add new market coins in indodax, like:
'ACT/IDR',
'ADA/IDR',
'TRX/IDR',

etc.

and, please check again amount when create_order function (php)
http://prntscr.com/jtympu --> i change to this one, because the previous its wrong

Thank You

**Comment by kroitor** [comment]
> and, please check again amount when create_order function (php)
> http://prntscr.com/jtympu --> i change to this one, because the previous its wrong

It is not wrong, it requires the amount to be in base currency for the buy side, according to their docs:

<img width="1068" alt="screen shot 2018-06-12 at 12 26 21" src="https://user-images.githubusercontent.com/1294454/41282081-d7c7f9aa-6e3b-11e8-9a3e-0d3daa1ff733.png">

So we calculate total cost with `amount * price` there. Everything is correct. And you should supply `price` for `buy` orders with INDODAX.

**Comment by santos-sabanari** [comment]
sorry, but i think, the amount of rupiah isn't like that.
ex:
if i want to buy Rp. 1.000.000 to BTC when the price is Rp. 100.000.000

so, with your formula is like 1.000.000 x 100.000.000 = 100.000.000.000.000 (it is a lot of money in rupiah)

therefore, my formula is:
price = 100.000.000
amount = 1.000.000 (it a "normal" money in rupiah)

Thank you

**Comment by kroitor** [comment]
> so, with your formula is like 1.000.000 x 100.000.000 = 100.000.000.000.000 (it is a lot of money in rupiah)

It isn't really my formula, it is what the exchange itself says ) I mean, it's in their docs.

If you want to buy 0.01 BTC for the price of 100.000.000 Rp, then you put these values:

```
price = 100.000.000 (Rp)
amount = 0.01 (BTC)
--------------------
the cost of the order will be 100.000.000 * 0.01 = 1.000.000Rp.
```

**Comment by santos-sabanari** [comment]
Thank you, I understood 😁
