### ISSUE TITLE
quadrigaCX fetchTickers

### ISSUE THREAD

**Issue by Esc4pism** [ccxt/ccxt#3112]
taken from the returned result of: https://api.quadrigacx.com/v2/ticker?book=xxx

(should be one of [**all**, btc_cad, btc_usd, eth_cad, eth_btc, ltc_cad, ltc_btc, bch_cad, bch_btc, btg_cad, btg_btc])

so it supports fetching multiple/all tickers as well: https://api.quadrigacx.com/v2/ticker?book=all

**Comment by kroitor** [comment]
@Esc4pism your contributions are welcome: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code ;)
