### ISSUE TITLE
Issue about Bitmex's parseOrder

### ISSUE THREAD

**Issue by atjason** [ccxt/ccxt#3113]
When Bitmex's limit order is closed, the message has no attribute of `ordType` and `side`. And then [Bitmex's parseOrder](https://github.com/ccxt/ccxt/blob/master/js/bitmex.js) will throw error of `Cannot read property 'toLowerCase' of undefined`.

```js
    parseOrder (order, market = undefined) {
        let result = {
///
            'type': order['ordType'].toLowerCase (),
            'side': order['side'].toLowerCase (),
///
        };
        return result;
    }
```

BTW, it's better keep `partiallyfilled` status. Now ccxt treat it as open, which bring trouble when work based on order status.

```js
    parseOrderStatus (status) {
        let statuses = {
///
            'partiallyfilled': 'open',
///
        };
    }
```

Please help to check, thanks.

**Comment by kroitor** [comment]
> When Bitmex's limit order is closed, the message has no attribute of ordType and side. 

Can you please post your verbose request and response, as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

**Comment by atjason** [comment]
@kroitor In fact I used Bitmex WebSocket to monitor order changes, and then use ccxt/bitmex.js to parse raw order info responded from Bitmex, and then meet this problem.

Seems REST will not meet this issue, close it.

**Comment by kroitor** [comment]
@atjason if you post the structure itself, I'll see what I can do to make it survive this... )
