### ISSUE TITLE
coinbase: vault and wallet balances should be summed

### ISSUE THREAD

**Issue by bendemott** [ccxt/ccxt#3117]
OS: linux (ubuntu 18)
programming version: python 3.6
CCXT version: 1.14.148
Exchange: coinbase
Method: sign

**The balances response from coinbase can contain multiple entries for the same CURRENCY code (ETH)**
```
United States Do fiat      0.0
Bitcoin Cash     wallet    1115.42411242
Litecoin         vault     0.0
Ethereum         vault     6447.23828149
Bitcoin          vault     845.91526239
Litecoin         wallet    0.0
Ethereum         wallet    0.0
Bitcoin          wallet    0.0
```
To properly represent balances, we sum currency codes together for the various types of wallets and vaults that share the same currency code.

**Comment by ryancwalsh** [comment]
This was helpful. Thank you! 

I found at https://github.com/ccxt/ccxt/blob/82e17f71cf897704825013ff6471ff21e5ea36c9/js/coinbase.js#L160 that there is a 'vault' type of account supported but not enabled by default.

Then I learned at https://ccxt.readthedocs.io/en/latest/manual.html#overriding-exchange-properties-upon-instantiation that I could pass these options when instantiating the Coinbase exchange, and it works:

```
options: {
      accounts: ['wallet', 'fiat', 'vault'], 
    }
````
