### ISSUE TITLE
fetchTickers() itself eating the rate limit on Binance?

### ISSUE THREAD

**Issue by tomastelensky** [ccxt/ccxt#3120]
I am just calling exchange.fetchTickers() (manually from node console or from script), once per cca two seconds... and I get too many requests! How is it possible? Does fetchTickers() send more than one request? I initialize Binance like this:

```
cm = new ccxt.binance ({
// keys deleted
rateLimit: 120, 
enableRateLimit: true
});
```
And normally, this rate limit is perfectly ok - i use it in scripts where I issue more request. Therefore I am very much surprised that issuing just one call - fetchTickers() - would result in too many requests.

The error dump:

```
(node:5744) UnhandledPromiseRejectionWarning: Error: binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API."}
    at binance.handleErrors (c:\tomas\js\node_modules\ccxt\js\binance.js:846:19)
    at response.text.then (c:\tomas\js\node_modules\ccxt\js\base\Exchange.js:568:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:5744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5744) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

- OS: Windows 10
- Programming Language version: 8.11.2
- CCXT version: not sure how to find out, pulled 8.6.2018
- Exchange: Binance
- Method: ?

**Comment by kroitor** [comment]
Duplicate: 
- https://github.com/ccxt/ccxt/issues/1855
- https://github.com/ccxt/ccxt/issues/1027
- https://github.com/ccxt/ccxt/search?q=binance+fetchtickers&type=Issues
