### ISSUE TITLE
Coinegg problem

### ISSUE THREAD

**Issue by archangellin** [ccxt/ccxt#3123]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:win 2008 R2
- Programming Language version: Python
- CCXT version: 
- Exchange: CoinEgg
- Method: fetch_tick('FREC/ETH'),

hey guys, 
when I try to use the function fetch_tick('FREC/ETH'), the below happens....

<class 'Exception'> : coinegg https://www.coinegg.com/coin/btc/allcoin?t=1528851
294077 GET 503 Server Error: Service Temporarily Unavailable for url: https://ww
w.coinegg.com/coin/btc/allcoin?t=1528851294077 <!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-sc
ale=1" />
  <title>Just a moment...</title>
  <style type="text/css">
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; font-family: Helvetica, Arial, sans-serif;
font-size: 100%;}
    h1 {font-size: 1.5em; color: #404040; text-align: center;}
    p {font-size: 1em; color: #404040; text-align: center; margin: 10px 0 0 0;}
    #spinner {margin: 0 auto 30px auto; display: block;}
    .attribution {margin-top: 20px;}
    @-webkit-keyframes bubbles { 33%: { -webkit-transform: translateY(10px); tra
nsform: translateY(10px); } 66% { -webkit-transform: translateY(-10px); transfor
m: translateY(-10px); } 100% { -webkit-transform: translateY(0); transform: tran
slateY(0); } }
    @keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform:
translateY(10px); } 66% { -webkit-transform: translateY(-10px); transform: trans
lateY(-10px); } 100% { -webkit-transform: translateY(0); transform: translateY(0
); } }
    .bubbles { background-color: #404040; width:15px; height: 15px; margin:2px;
border-radius:100%; -webkit-animation:bubbles 0.6s 0.07s infinite ease-in-out; a
nimation:bubbles 0.6s 0.07s infinite ease-in-out; -webkit-animation-fill-mode:bo
th; animation-fill-mode:both; display:inline-block; }

**Comment by kroitor** [comment]
Use the cloudscraper to bypass it:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/blob/master/examples/py/bypass-cloudflare-with-cookies.py
- https://github.com/ccxt/ccxt/blob/master/examples/py/bypass-cloudflare.py
