### ISSUE TITLE
Data fetching stops when PC goes into sleep mode. Is this normal?

### ISSUE THREAD

**Issue by cowboyjj** [ccxt/ccxt#3132]
Hi,

I've noticed that data fetching stops when PC goes into sleep mode. As soon as the PC wakes up the data fetching will resume. This is not a problem with any specific exchanges as I've tried a few already and they all suffer from it.

Is this normal? I obviously can stop this issue by making my PC never go to sleep, but I wonder if there is a more efficient way to deal with this problem?

Many thanks

**Comment by kroitor** [comment]
> Is this normal?

Yes.

> I obviously can stop this issue by making my PC never go to sleep, but I wonder if there is a more efficient way to deal with this problem?

This isn't a problem. This is the behaviour expected from a PC in a sleep mode. Your questions isn't actually related to this particular library and answered on google a gazillion times:

https://www.vistax64.com/threads/keep-a-program-running-during-sleep.192207/

Closing this if you don't mind.

**Comment by cowboyjj** [comment]
Thank you Kroior. This is very helpful.
