### ISSUE TITLE
$exchange->symbols returns NULL (huoby)

### ISSUE THREAD

**Issue by coresh** [ccxt/ccxt#3134]
- OS: Linux
- Programming Language version: php -v -> PHP 7.2.6
- CCXT version: 1.14.196
- Exchange: huoby
- Method: $exchange->symbols
- Api data filled properly (balance provided properly)

$exchange->symbols returns NULL
instead of an expected array with a result

**Comment by kroitor** [comment]
You forgot to load the markets: https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
Let us know if it does not answer your question.
