### ISSUE TITLE
coinbase: minor bugfix

### ISSUE THREAD

**Issue by bendemott** [ccxt/ccxt#3135]
OS: linux (ubuntu 18)
programming version: python 3.6
CCXT version: 1.14.148
Exchange: coinbase
Method: sign

**accounts misspelled**
https://github.com/ccxt/ccxt/blob/master/js/coinbase.js#L145
```
Traceback (most recent call last):
  File "ccxt-coinbase.py", line 17, in <module>
    balance = coinbase.fetch_balance()
  File "/usr/local/lib/python3.6/dist-packages/ccxt/coinbase.py", line 252, in fetch_balance
    accounts = self.safe_value(params, 'type', self.options['accounts'])
KeyError: 'accounts'
```

Also, was it intentional to exclude `vault` from the types:
https://github.com/ccxt/ccxt/blob/master/js/coinbase.js#L148

I guess you wanted to the default behavior to include only `fiat` and `wallets`?

@kroitor - thanks for the detailed reply about this feature.

**Comment by kroitor** [comment]
> I guess you wanted to the default behavior to include only fiat and wallets?

Yep, afaik, fiat + wallet is the *active* money, where `vault` is the *cold-storage, inactive* money. If you want vault balances summed, then just add `vault` to `this.options['accounts']`:

```Python
coinbase.options['accounts'] += [ 'vault' ]
balance = coinbase.fetch_balance()
```
