### ISSUE TITLE
huobipro  create_market_buy_order not use

### ISSUE THREAD

**Issue by CHANGAIQING** [ccxt/ccxt#3136]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version: python
- CCXT version:1.14.178
- Exchange:huobipro
- Method:create_market_buy_order

**Comment by CHANGAIQING** [comment]
[Traceback (most recent call last):,   File sync_asset_callback.py, line 49, in sync_asset_callback,     print buy_obj.create_market_buy_order(TRADE_SYMBOL, buy_qty, buy_price),   File /usr/lib/python2.7/site-packages/ccxt/base/exchange.py, line 1314, in create_market_buy_order,     return self.create_order(symbol, market, buy, amount, None, params),   File /usr/lib/python2.7/site-packages/ccxt/huobipro.py, line 579, in create_order,     raise InvalidOrder(self.id +  market buy order requires price argument to calculate cost(total amount of quote currency to spend for buying, amount * price). To switch off self warning exception and specify cost in the amount argument, set .options[createMarketBuyOrderRequiresPrice] = False. Make sure you know what youre doing.), InvalidOrder: huobipro market buy order requires price argument to calculate cost(total amount of quote currency to spend for buying, amount * price). To switch off self warning exception and specify cost in the amount argument, set .options[createMarketBuyOrderRequiresPrice] = False. Make sure you know what youre doing.]

**Comment by kroitor** [comment]
> To switch off self warning exception and specify cost in the amount argument, set .options[createMarketBuyOrderRequiresPrice] = False. Make sure you know what youre doing.

**Comment by runrun88** [comment]
market_price_buy = float(ticker_base['bid'])
        order_result = self.huobi.create_market_buy_order('EOS/BTC', market_buy_size, market_price_buy)

it's wrong too.
the error:
InvalidOrder(self.id + " market buy order requires price argument to calculate cost(total amount of quote currency to spend for buying, amount * price). To switch off self warning exception and specify cost in the 

How can I use huobi   create_market_buy_order

**Comment by evgen-y2k** [comment]
Hi Kroitor.
I have same problem with Huobi pro market BUY order. I tried many variants and now made wrapper around Limit Buy that works as Market.
 Help please. How to create market BUY order?

**Comment by kroitor** [comment]
@runrun88 , @evgen-y2k you should not use `create_market_buy_order` base method because it omits the price, use `create_order` with `huobipro` instead:

```Python
market_price_buy = float(ticker_base['bid'])
#                                               ↓ 'market' and ↓ 'buy' as arguments here
order_result = self.huobi.create_order('EOS/BTC', 'market', 'buy', market_buy_size, market_price_buy)
```

**Comment by evgen-y2k** [comment]
aaa, ok! I forgot about "create_order" method and tried only "create_market_buy_order". Ok, today will try it. THX
