### ISSUE TITLE
Coinbase fetchBalance error Cannot read property includes of undefined

### ISSUE THREAD

**Issue by Stas-Buzunko** [ccxt/ccxt#3138]
- OS: Ubuntu
- Programming Language version: JS
- CCXT version: 1.14.196
- Exchange: Coinbase
- Method: fetchBalance
Cannot read property includes of undefined
![screenshot_2018-06-14-22-53-01-649_com bull dev](https://user-images.githubusercontent.com/12331100/41434988-1ee0baac-7026-11e8-9f1a-3a5d41571efa.png)

P.S. I know you don't make any promises about feature implementations, but approximately when are you going to add fetchOHLCV for coinbase?

**Comment by kroitor** [comment]
Duplicate: #3135 

> P.S. I know you don't make any promises about feature implementations, but approximately when are you going to add fetchOHLCV for coinbase?

This week, maybe.
