### ISSUE TITLE
Bittrex fetch_markets issue : Base & Quote are swaped

### ISSUE THREAD

**Issue by pitzlabs** [ccxt/ccxt#3143]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Linux
- Programming Language version: Python
- CCXT version: 
- Exchange: bittrex
- Method: fetch_markets

>> The issue is that base and Quote currencies are interchanged, line 190 & 191
   baseId = market['MarketCurrency']
   quoteId = market['BaseCurrency']

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/wiki/Manual#consistency-of-base-and-quote-currencies

**Comment by pitzlabs** [comment]
Yes, Bittrex exchange has reversed data.
Thanks.
