### ISSUE TITLE
kucoin precision values ignored

### ISSUE THREAD

**Issue by miracle2k** [ccxt/ccxt#3147]
kucoin exposes the precision for each currency, and it is loaded in `fetchCurrencies`:

https://github.com/ccxt/ccxt/blob/master/js/kucoin.js#L266

However, calling `fetchMarkets` does *not*  read the precision and sets it to a default instead:

https://github.com/ccxt/ccxt/blob/master/js/kucoin.js#L205

How can this be fixed? Should `fetchMarkets` first call `fetchCurrencies`?

**Comment by kroitor** [comment]
> kucoin precision values ignored

They aren't actually ignored )

> How can this be fixed? Should fetchMarkets first call fetchCurrencies?

This is already fixed – if you look into createOrder family, you'll notice that it is using the currency precision, not the market precision...

https://github.com/ccxt/ccxt/blob/master/js/kucoin.js#L599

> How can this be fixed? Should fetchMarkets first call fetchCurrencies?

In this particular case – yes. However, this is a lot more involved, see these discussions:

- https://github.com/ccxt/ccxt/pull/1669
- https://github.com/ccxt/ccxt/pull/1814
- https://github.com/ccxt/ccxt/pull/1835
- ...

Hope this answers your question, let us know if not ) Thx!
