### ISSUE TITLE
coinmarketcap only loads first 100 currencies

### ISSUE THREAD

**Issue by miracle2k** [ccxt/ccxt#3148]
It seems this is the maximum allowed. 

To get all of them, we have to paginate. But how do we best to this? `publicGetTicker` is called from many different places; we only want to implement the pagination once. 

Maybe we even want to call it only once, and then have it cached. After all, at 1600 currencies, that is at least 16 calls.

**Comment by miracle2k** [comment]
Ok, someth

**Comment by npomfret** [comment]
@kroitor https://api.coinmarketcap.com/v1/ticker/ only returns 100 items.  I'm trying to do some symbol mapping stuff, is there a place in CMC that I can get them all?

**Comment by kroitor** [comment]
@npomfret you probably want to add [params overrides](https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params) to paginate over them: https://coinmarketcap.com/api/documentation/v1/#operation/getV1CryptocurrencyListingsLatest (see `start`, `limit`, `sort`, `sort_dir`)

**Comment by npomfret** [comment]
Sorry, I should have been clearer.  I saw that but it needs an API (which I have), but thought for some reason there was an endpoint that doesn't require one.
