### ISSUE TITLE
First try to get the balance of an exchange

### ISSUE THREAD

**Issue by Elmit2015** [ccxt/ccxt#3149]
I try to get the balance of my coins on an exchange. In my example I used Bittrex with php.

First I fetched the tickers, to get the multiplier:
$tickers = $exchange->fetchTickers ();
Next I get the balance:
$result = $exchange->fetch_balance ();

I calculated the balance of one coin with:
$t1 = $result['info'][$x]['Currency'] . "/BTC";
$b1 = $result['info'][$x]['Available'] * $tickers[$t1]['info']['Last'];

However, if I compare the result with that on the exchange, I get different results. Am I doing the right thing?

**Comment by kroitor** [comment]
Nope )

These posts will shed some light:
- https://github.com/ccxt/ccxt/issues/1986
- https://github.com/ccxt/ccxt/issues/2547
- https://github.com/ccxt/ccxt/issues/105

Let us know if the above info does not answer your question.

**Comment by kroitor** [comment]
P.S. You should not really use exchange-specific `info` field, use the unified balance structure instead:  https://github.com/ccxt/ccxt/wiki/Manual#querying-account-balance

**Comment by Elmit2015** [comment]
I am blind, ...

I think you want to guide me to use ['total'] instead of ['info']

```
   [total] => Array
        (
            [1ST] => 52.77176691

```
echo $result['total']['1ST']. "\n";
brings the result, but 
echo $result['total'][0];
gives me undefined offset.

**Comment by kroitor** [comment]
> echo $result['total']['1ST']. "\n";
> brings the result, but

Yep, because it's an associative array

> echo $result['total'][0];
> gives me undefined offset.

Yep, because it's an associative array. You need to understand the difference between an assoc array and an integer-index array in PHP (this is a question not related to this library). 

https://www.oreilly.com/library/view/programming-php-3rd/9781449361068/ch05s01.html

In short, you can not use integer indexes on associative (string-keyed) arrays like that (why would you want to loose the info?). However, if you insist, you can do this:

```PHP
 // will print the first currency in your balance, whatever it is
// the order might change over time, so this code isn't safe
echo array_values($result['total'])[0];
```

Why wouldn't you use `$result['total']['1ST']` and `$result['1ST']['total']` instead ?

**Comment by kroitor** [comment]
> then I must know which coins are there

This is easy:

```PHP
$balance = $exchange->fetch_balance ();
$currency_codes = array_keys ($balance['total']);

// $currency_codes now contains an integer-indexed list of all coins that were there

// iterate them one by one, how you want them...
foreach ($i = 0; $i < count ($currency_codes); $i++) {
    $currency_code = $currency_codes[i];
    $currency_total_balance = $balance['total'][$currency_code];
    echo $currency_code . ': ' . $currency_total_balance;
}
```

>  to get the same result as the exchange

The posts I linked above are explaining why you will rarely get the same result (if ever at all). This is due to price slippage, networking latency and many other factors that you should take into account.

**Comment by Elmit2015** [comment]
First of all, thanks for your patent with me. I appreciate that!
I tried in the meantime this:
```
foreach($result['total'] as $x => $x_value) {
    echo "Coin=" . $x . ", Coinvalue=" . $x_value;
    echo "\n";
}

```
which gave me also the result.

Still the question of the factor. We got in the tickers: high, low, bid, ask, close, last, info-high, info-low, info-last, info-bid, info-ask. Which one is the best suitable factor?

**Comment by kroitor** [comment]
> Which one is the best suitable factor?

- If you are going to sell later for that price-rate, then you should take the bid price (worse) or should accumulate the volume of your order from the orderbook price+amounts (much better).

- If you are going to buy later for that price-rate, then you should take the ask price (worse) or should accumulate the volume of your order from the orderbook price+amounts (much better).

- If you don't know yet what you will be doing with that price-rate, then then you should take the last price (worse) or should average the volume of your order from the orderbook price+amounts, with respect to market depth (much better).

**Comment by kroitor** [comment]
@Elmit2015 you really want to read this section as of the Manual as well: https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades

**Comment by Elmit2015** [comment]
I do read a lot, ... Thank you very much. You helped me a lots. Thank you again.

**Comment by Gautham-GM** [comment]
a
