### ISSUE TITLE
A way to convert for PRICE_FILTER, LOT_SIZE and MIN_NOTATION

### ISSUE THREAD

**Issue by springjben** [ccxt/ccxt#3153]
Is there a built in function that takes my quantity/price and converts it for me?

I know there is **amountToLots**, but is there a generic function that will convert my quantity/price all for me?

**Comment by kroitor** [comment]
Use the `decimalToPrecision` / `decimal_to_precision`:

- https://github.com/ccxt/ccxt/blob/master/js/test/base/functions/test.number.js
- https://github.com/ccxt/ccxt/blob/master/python/test/test_decimal_to_precision.py
- https://github.com/ccxt/ccxt/blob/master/php/test/decimal_to_precision.php

The above function is string-based, so you should convert to and from a float, where needed.

Hope this answers your question.

**Comment by springjben** [comment]
Wait, do I have to convert both the price and units to be able to place a market order?

**Comment by kroitor** [comment]
> Wait, do I have to convert both the price and units to be able to place a market order?

Nope, don't know about *"units"*, but you don't have to convert neither price nor units for a market order. The only thing you need to convert for a market order is the order amount.

**Comment by springjben** [comment]
Okay thank you.
I am getting this error sometimes though:

lot = self.markets[symbol]['lot']
KeyError: 'lot'

Its ARDR on Poloniex

**Comment by springjben** [comment]
I get the same error for HitBTC

**Comment by springjben** [comment]
I know HitBTC has lot limits, but the API doesn't return anything for the LOT field, causing it to break

**Comment by kroitor** [comment]
@springjben without your code and your verbose request and response it will be really hard to help you. If you can, please report the errors and follow the rules precisely as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue. We will be able to help much quicker then. Otherwise you're not helping us to help you )

**Comment by springjben** [comment]
I do apologize. I will write a more detailed report.

`ccxt.bittrex().amountToLots('ANT/BTC', 23.231)` - Running this command returns an error as there is no LOT size value to go by. 

You can see this by:
`ccxt.bittrex().load_markets()['ANT/BTC']`
The object returned does not have a info ->lot number. This is causing the amountToLots to break.

**Comment by kroitor** [comment]
> `ccxt.bittrex().amountToLots('ANT/BTC', 23.231)`
> Running this returns an error as there is no LOT size value to go by.

The `amountToLots` method is deprecated, you should use `decimalToPrecision` instead, as described in my comment above: https://github.com/ccxt/ccxt/issues/3153#issuecomment-397849022

**Comment by springjben** [comment]
But decimalToPrecision wont use something like HitBTC lot size to convert the number to a valid number?

For example, on some HitBTC values it needs to be divisible by 1000.

**Comment by kroitor** [comment]
> But decimalToPrecision wont use something like HitBTC lot size to convert the number to a valid number?

With proper arguments – it will.

> For example, on some HitBTC values it needs to be divisible by 1000.

See examples of doing it with decimalToPrecision in the linked files above.

**Comment by springjben** [comment]
I have looked at the examples. I am sorry I am still a little confused.

If we are doing for example:
`assert(decimal_to_precision('9.999', ROUND, 2, DECIMAL_PLACES, PAD_WITH_ZERO) == '10.00'))`

We have to specify it needs to be 2 digits rounded. Its not going to make it suitable for an order (like amountToLots would have presumably done)

**Comment by kroitor** [comment]
@springjben 

> I was hoping there would be a function (exactly like amountToLots) that works for every exchange and coin

There is such a function. It is called amountToPrecision:

```
amountToPrecision ('ETH/BTC', amount)
```

**Comment by springjben** [comment]
Brilliant, thank you very much!
