### ISSUE TITLE
How to get the order Id ,after I ordered to use create_order function  EXCHANGE:ZAIF 

### ISSUE THREAD

**Issue by k31ww475** [ccxt/ccxt#3154]
Hi.I created the code below and it works.
But I can't get the order id that I ordered in ZAIF.
Please let me know the code how to get the order I'd that I ordered right now.

limit_ordered_info_ask = exchange[index[ask_exchange]].create_order(
                symbol = TARGET_CURRENCY,
                type = "limit",
                side = "buy",
                amount = set_ask_volume,
                price = best_ask_price
                )

ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:win10
- CCXT version:
- Exchange:zaif
- Method:create_order

**Comment by kroitor** [comment]
Documented here: https://github.com/ccxt/ccxt/wiki/Manual#placing-orders

```
limit_ordered_info_ask = exchange[index[ask_exchange]].create_order(
symbol = TARGET_CURRENCY,
type = "limit",
side = "buy",
amount = set_ask_volume,
price = best_ask_price
)

# your order id:

print(limit_ordered_info_ask['id'])
```

**Comment by k31ww475** [comment]
At first,I already read it and I already try the code before you write.
But zaif don't return the id that it why I tell you about it.
The problem is not close.Back to the status open please.

**Comment by k31ww475** [comment]
{'info': {'success': 1, 'return': {'received': 0.001, 'remains': 0.0, 'order_id': 0, 'funds': {'jpy': 0.0, 'btc': 0.0, 'xem': 0, 'mona': 0.0, 'ETH': 0.0}}}, 'id': '0'}

**Comment by k31ww475** [comment]
It's zaif' response.it written id:0 at llast part.I understood that zaif can't response directly that we ordered now.But we absolutely need to order id that we ordered. 

Thanks in advance.

**Comment by k31ww475** [comment]
It's just a bug of ccxt

**Comment by kroitor** [comment]
@k31ww475 

> It's just a bug of ccxt

To me this does not look like a bug of ccxt. Zaif replies with a zero id in certain cases, and this is not a bug of ccxt. This is the way this particular exchange works.

Taker orders are closed immediately and don't have an id with zaif, in other words, if your order is buyng for a price that can be satisfied right away, then zaif will not respond with an order id.

Instead, what you should do is check for closed orders:

```
exchange_instance = exchange[index[ask_exchange]]
symbol = TARGET_CURRENCY
type = "limit"
side = "buy"
amount = set_ask_volume
price = best_ask_price
limit_ordered_info_ask = exchange_instance.create_order(symbol, type, side, amount, price)

if not limit_ordered_info_ask['id']:
    closed_orders = exchange_instance.fetch_closed_orders(symbol)
    sorted_by_timestamp = exchange_instance.sort_by(closed_orders, 'timestamp', true)
    order = sorted_by_timestamp[0]
    print(order['id'])
else:
    print(limit_ordered_info_ask['id'])
```

Does this answer your question?

**Comment by kroitor** [comment]
The `info` field is the field containing the raw untouched reply from the exchange, as is. This is written everywhere in the Manual. From your own output, in the `info` field you can see what the Zaif exchange replied exactly:

```Python
{
    'info': {                         # this is what the exchange replied, as is
        'success': 1,                 # this is what the exchange replied, as is
        'return': {                   # this is what the exchange replied, as is
            'received': 0.001,        # this is what the exchange replied, as is
            'remains': 0.0,           # this is what the exchange replied, as is
            'order_id': 0,            # this is what the exchange replied, as is
            'funds': {                # this is what the exchange replied, as is
                'jpy': 0.0,           # this is what the exchange replied, as is
                'btc': 0.0,           # this is what the exchange replied, as is
                'xem': 0,             # this is what the exchange replied, as is
                'mona': 0.0,          # this is what the exchange replied, as is
                'ETH': 0.0            # this is what the exchange replied, as is
            }                         # this is what the exchange replied, as is
        }                             # this is what the exchange replied, as is  
    }, 
    'id': '0'             # this is what ccxt found from exchange's reply
}
```

**Comment by k31ww475** [comment]
At first Thank you lots Kroitor.
I understood what you said about bug or responsibility.
But we love the ccxt and this problem is very big one because the order id is most important info against ccxt's info.

Certainly zaif don't response the id directly.But ccxt user should not use close order every time to get the id.Because it must be everybody use every time,so frequencies of order id are very high.So I think it will be better to build this code ccxt.

Of course zaif sys is really bad,As  principle of ccxt we should use the same code in ccxt in every exchange.right?

**Comment by kroitor** [comment]
> As principle of ccxt we should use the same code in ccxt in every exchange.right?

Right, but the general principle is to check the order status after placing the order anyway. In this particular case, we cannot make up an id, because Zaif does not return it for taker orders. So, despite that we really want to, we are not able to actually give you an order id, if Zaif itself does not give it in their response. I guess you should understand the difference between maker and taker orders, as this behaviour is common with a lot of exchanges in CCXT, including Liqui, Cryptopia, and some others...

> So I think it will be better to build this code ccxt.

If you can show how to build something from nothing – we will do this.

**Comment by k31ww475** [comment]
Ok Kroitor.We have to trade many exchange that sys API is poor like zaif.I need your help from now on.
 I'll try the code that you wrote.

Thanks
