### ISSUE TITLE
Binance cancelOrder  error

### ISSUE THREAD

**Issue by morzyns** [ccxt/ccxt#3160]
Hi,
I've experienced the error when canceling the order
`

>  [Exchange Error] binance: unknown error code: {"code":-1102,"msg":"Mandatory parameter 'symbol' was not sent, was empty/null, or malformed."} -1102

`

The orderId is Valid, and provided symbol 'VEN/BTC'

- OS: mac
- Programming Language version: JS
- CCXT version: 1.13.45
- Exchange: Binance
- Method: cancelOrder

**Comment by kroitor** [comment]
Hi! Do you have the same problem with the most recent version of CCXT?

**Comment by morzyns** [comment]
Hi @kroitor,
unfortunately on 1.14.205 the same message. 
I've been on the same working code for few months, I guess they have changed something.

I get the order.id, within the same symbol and it works. I've checked on inspector for HTTP Request and it's translating to VENBTC as it should be.

**Comment by kroitor** [comment]
> unfortunately on 1.14.205 the same message.

Can you please show your code and verbose request / response precisely as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

```JavaScript
exchange.verbose = true
const cancelResponse = await exchange.cancelOrder (orderId, symbol)
```

Also, can you ensure that your current version is up to date?

```JavaScript
console.log (require ('ccxt').version)
```

?

**Comment by morzyns** [comment]
> fetch:
>  binance DELETE https://api.binance.com/api/v3/order 
> Request:
>  {
>   "User-Agent": "Trader2",
>   "X-MBX-APIKEY": "OFLqpcl9GVeGW98TzAonURATc639bngxSPbZn4B6n5sH4aKAXZfylNZ9CYh5IXSy",
>   "Content-Type": "application/x-www-form-urlencoded"
> } 
>  timestamp=1529268922406&recvWindow=10000000&symbol=VENBTC&orderId=34089239&signature=2c5839fae5b1b0225dffe16d3c03197ff225fcdf7943744665414fbdc13e1761 
> 
> Exchange.js:565 handleRestResponse:
>  binance DELETE https://api.binance.com/api/v3/order 400 Bad Request 
> Response:
>  {
>   "Null": "HTTP/1.1 400 Bad Request",
>   "Cache-Control": "no-cache, no-store, must-revalidate",
>   "Connection": "keep-alive",
>   "Content-Security-Policy": "default-src 'self'",
>   "Content-Type": "application/json",
>   "Date": "Sun, 17 Jun 2018 20:55:23 GMT",
>   "Expires": "0",
>   "Pragma": "no-cache",
>   "Server": "nginx",
>   "Strict-Transport-Security": "max-age=31536000; includeSubdomains",
>   "Transfer-Encoding": "chunked",
>   "Via": "1.1 a4d3aef54e3eaf5d348e3ce53a19b36f.cloudfront.net (CloudFront)",
>   "X-Amz-Cf-Id": "pTyCQCw87wM3otl5xETz45gwzVQllcDNyOUKPR1KGgRrpmJchWFrBA==",
>   "X-Android-Received-Millis": "1529268923451",
>   "X-Android-Response-Source": "NETWORK 400",
>   "X-Android-Selected-Protocol": "http/1.1",
>   "X-Android-Sent-Millis": "1529268923149",
>   "X-Cache": "Error from cloudfront",
>   "X-Content-Security-Policy": "default-src 'self'",
>   "X-Content-Type-Options": "nosniff",
>   "X-Frame-Options": "SAMEORIGIN",
>   "X-Webkit-Csp": "default-src 'self'",
>   "X-Xss-Protection": "1; mode=block"
> } 
>  {"code":-1102,"msg":"Mandatory parameter 'symbol' was not sent, was empty/null, or malformed."} 
> 
> core-exchange.service.ts:87 [Exchange Error] binance: unknown error code: {"code":-1102,"msg":"Mandatory parameter 'symbol' was not sent, was empty/null, or malformed."} -1102
> core.umd.js:1487 ERROR Error: [Exchange Error] binance: unknown error code: {"code":-1102,"msg":"Mandatory parameter 'symbol' was not sent, was empty/null, or malformed."} -1102
> Exchange.js:565 handleRestResponse:

**Comment by kroitor** [comment]
> Mandatory parameter 'symbol' was not sent, was empty/null, or malformed.

This is strange, because it was sent, as shown in the request body:

> ```
> timestamp=1529268922406&recvWindow=10000000&symbol=VENBTC&orderId=34089239&signature=2c5839fae5b1b0225dffe16d3c03197ff225fcdf7943744665414fbdc13e1761
> ```

Will debug this and will get back to you asap.

**Comment by kroitor** [comment]
Does it work for you this way? ↓ (this may look like a lot of code, but this is just for debugging, to see if this solves the problem)

```JavaScript

// override the sign() call for debugging purposes

exchange.sign = function (path, api = 'public', method = 'GET', params = {}, headers = undefined, body = undefined) {
        let url = this.urls['api'][api];
        url += '/' + path;
        if (api === 'wapi')
            url += '.html';
        // v1 special case for userDataStream
        if (path === 'userDataStream') {
            body = this.urlencode (params);
            headers = {
                'X-MBX-APIKEY': this.apiKey,
                'Content-Type': 'application/x-www-form-urlencoded',
            };
        } else if ((api === 'private') || (api === 'wapi')) {
            this.checkRequiredCredentials ();
            let query = this.urlencode (this.extend ({
                'timestamp': this.nonce (),
                'recvWindow': this.options['recvWindow'],
            }, params));
            let signature = this.hmac (this.encode (query), this.encode (this.secret));
            query += '&' + 'signature=' + signature;
            headers = {
                'X-MBX-APIKEY': this.apiKey,
            };
            if ((method === 'GET') || (method === 'DELETE') || (api === 'wapi')) {
                url += '?' + query;
            } else {
                body = query;
                headers['Content-Type'] = 'application/x-www-form-urlencoded';
            }
        } else {
            if (Object.keys (params).length)
                url += '?' + this.urlencode (params);
        }
        return { 'url': url, 'method': method, 'body': body, 'headers': headers };
    }

// retry cancelOrder

const cancelResponse = exchange.cancelOrder (orderId, symbol)

```

**Comment by morzyns** [comment]
> JS: handleRestResponse:
> JS:  binance GET https://api.binance.com/api/v3/openOrders?timestamp=1529271575037&recvWindow=10000000&symbol=VENBTC&signature=b87d5748effd6eaa3cc4d2e3918dbe74c240b91f4d14cb014ac4885c016562b4 200 OK 
> JS: Response:
> JS:  {
> JS:   "Null": "HTTP/1.1 200 OK",
> JS:   "Cache-Control": "no-cache, no-store, must-revalidate",
> JS:   "Connection": "keep-alive",
> JS:   "Content-Security-Policy": "default-src 'self'",
> JS:   "Content-Type": "application/json",
> JS:   "Date": "Sun, 17 Jun 2018 21:39:36 GMT",
> JS:   "Expires": "0",
> JS:   "Pragma": "no-cache",
> JS:   "Server": "nginx",
> JS:   "Strict-Transport-Security": "max-age=31536000; includeSubdomains",
> JS:   "Transfer-Encoding": "chunked",
> JS:   "Via": "1.1 95a4581bed116b6338fc42595fee6f43.cloudfront.net (CloudFront)",
> JS:   "X-Amz-Cf-Id": "Bnedb-THZA_FkI3CGWwgbXGS__YDXb9hNPQdFng-o2wGDegFIB6INQ==",
> JS:   "X-Android-Received-Millis": "1529271576288",
> JS:   "X-Android-Response-Source": "NETWORK 200",
> JS:   "X-Android-Selected-Protocol": "http/1.1",
> JS:   "X-Android-Sent-Millis": "1529271575002",
> JS:   "X-Cache": "Miss from cloudfront",
> JS:   "X-...
> JS: handleRestResponse:
> JS:  binance DELETE https://api.binance.com/api/v3/order 400 Bad Request 
> JS: Response:
> JS:  {
> JS:   "Null": "HTTP/1.1 400 Bad Request",
> JS:   "Cache-Control": "no-cache, no-store, must-revalidate",
> JS:   "Connection": "keep-alive",
> JS:   "Content-Security-Policy": "default-src 'self'",
> JS:   "Content-Type": "application/json",
> JS:   "Date": "Sun, 17 Jun 2018 21:39:36 GMT",
> 
> JS:   "Pragma": "no-cache",
> JS:   "Server": "nginx",
> JS:   "Strict-Transport-Security": "max-age=31536000; includeSubdomains",
> JS:   "Transfer-Encoding": "chunked",
> JS:   "Via": "1.1 f9c202cf95d0b7b21ec116a51d1b9bea.cloudfront.net (CloudFront)",
> JS:   "X-Amz-Cf-Id": "o0Xm1vSsfDpUZK9TpoJtnOReToprAKihaD5ezmqvUyYo2zCzhDCAuA==",
> JS:   "X-Android-Received-Millis": "1529271576448",
> JS:   "X-Android-Response-Source": "NETWORK 400",
> JS:   "X-Android-Selected-Protocol": "http/1.1",
> JS:   "X-Android-Sent-Millis": "1529271576151",
> JS:   "X-Cache": "Error from cloudfront",
> JS:   "X-Content-Security-Policy": "default-src 'self'",
> JS:   "X-Content-Type-Options": "nosniff",
> JS:   "X-Frame-Options": "SAMEORI...
> JS: ERROR Error: binance: unknown error code: {"code":-1102,"msg":"Mandatory parameter 'symbol' was not sent, was empty/null, or malformed."} -1102
> JS: handleRestResponse:
> JS:  binance DELETE https://api.binance.com/api/v3/order 400 Bad Request 
>

**Comment by kroitor** [comment]
@morzyns for some reason you didn't include the request for the order cancel endpoint, instead you posted two respones (one from fetchOpenOrders call that you are doing somewhere in your code – not relevant to this problem), and the order one is the response for the cancel call – we need to see the request for it, with the sign method as posted above.

Also, you didn't answer this:

> Also, can you ensure that your current version is up to date?

```
console.log (require ('ccxt').version)
```

How do you run your code? Are you running it from within Node.js (which version?) or a browser (which one?) ?

**Comment by morzyns** [comment]
Eh, sorry

> fetch:
>  binance DELETE https://api.binance.com/api/v3/order 
> Request:
>  {
>   "User-Agent": "Trader2",
>   "X-MBX-APIKEY": "OFLqpcl9GVeGW98TzAonURATc639bngxSPbZn4B6n5sH4aKAXZfylNZ9CYh5IXSy",
>   "Content-Type": "application/x-www-form-urlencoded"
> } 
>  timestamp=1529306968894&recvWindow=10000000&symbol=VENBTC&orderId=34089239&signature=70f38cd29a127ea2ed9448efc2ccf95d8f8d929c34e9d4c110537627b61756d6 
> 
> Exchange.js:454 fetch:
>  binance DELETE https://api.binance.com/api/v3/order 
> Request:
>  {
>   "User-Agent": "Trader2",
>   "X-MBX-APIKEY": "OFLqpcl9GVeGW98TzAonURATc639bngxSPbZn4B6n5sH4aKAXZfylNZ9CYh5IXSy",
>   "Content-Type": "application/x-www-form-urlencoded"
> } 
>  timestamp=1529306968918&recvWindow=10000000&symbol=VENBTC&orderId=34089239&signature=c0b10bdf0b65a19558103a681b83f8b33a3f6a7b502c1a40db6b487a80d6f0cf 
> 
> Exchange.js:565 handleRestResponse:
>  binance DELETE https://api.binance.com/api/v3/order 400 Bad Request 
> Response:
>  {
>   "Null": "HTTP/1.1 400 Bad Request",
>   "Cache-Control": "no-cache, no-store, must-revalidate",
>   "Connection": "keep-alive",
>   "Content-Security-Policy": "default-src 'self'",
>   "Content-Type": "application/json",
>   "Date": "Mon, 18 Jun 2018 07:29:29 GMT",
>   "Expires": "0",
>   "Pragma": "no-cache",
>   "Server": "nginx",
>   "Strict-Transport-Security": "max-age=31536000; includeSubdomains",
>   "Transfer-Encoding": "chunked",
>   "Via": "1.1 7d5a4639eb3f9650e3b7b916f1261d8a.cloudfront.net (CloudFront)",
>   "X-Amz-Cf-Id": "BTdj9RAmy8yaZK_pHGVyfA6pnIhcanGf5avGyNgCpvEohsoEEKya4A==",
>   "X-Android-Received-Millis": "1529306969574",
>   "X-Android-Response-Source": "NETWORK 400",
>   "X-Android-Selected-Protocol": "http/1.1",
>   "X-Android-Sent-Millis": "1529306968974",
>   "X-Cache": "Error from cloudfront",
>   "X-Content-Security-Policy": "default-src 'self'",
>   "X-Content-Type-Options": "nosniff",
>   "X-Frame-Options": "SAMEORIGIN",
>   "X-Webkit-Csp": "default-src 'self'",
>   "X-Xss-Protection": "1; mode=block"
> } 
>  {"code":-1102,"msg":"Mandatory parameter 'symbol' was not sent, was empty/null, or malformed."} 
> 
> Exchange.js:565 handleRestResponse:
>  binance DELETE https://api.binance.com/api/v3/order 400 Bad Request 
> Response:
>  {
>   "Null": "HTTP/1.1 400 Bad Request",
>   "Cache-Control": "no-cache, no-store, must-revalidate",
>   "Connection": "keep-alive",
>   "Content-Security-Policy": "default-src 'self'",
>   "Content-Type": "application/json",
>   "Date": "Mon, 18 Jun 2018 07:29:29 GMT",
>   "Expires": "0",
>   "Pragma": "no-cache",
>   "Server": "nginx",
>   "Strict-Transport-Security": "max-age=31536000; includeSubdomains",
>   "Transfer-Encoding": "chunked",
>   "Via": "1.1 349c46633ec261f652c266dcd21e9fc2.cloudfront.net (CloudFront)",
>   "X-Amz-Cf-Id": "FAkDu7hwkp0STUpvUZn34-gCogAhqhZ2PecNFIahBhDDLVGCfdnyBw==",
>   "X-Android-Received-Millis": "1529306969576",
>   "X-Android-Response-Source": "NETWORK 400",
>   "X-Android-Selected-Protocol": "http/1.1",
>   "X-Android-Sent-Millis": "1529306968998",
>   "X-Cache": "Error from cloudfront",
>   "X-Content-Security-Policy": "default-src 'self'",
>   "X-Content-Type-Options": "nosniff",
>   "X-Frame-Options": "SAMEORIGIN",
>   "X-Webkit-Csp": "default-src 'self'",
>   "X-Xss-Protection": "1; mode=block"
> } 
>  {"code":-1102,"msg":"Mandatory par

ameter 'symbol' was not sent, was empty/null, or malformed."}

**Comment by kroitor** [comment]
@morzyns are you sure that you did add the `.sign` override from my snippet above? Because the request should look differently with that override added. The query params should be in the URL and the content-type should not be set. However, in your request section, the query params are in the body of the request, not in the URL, and the content-type header is still there. Need you to confirm this.

**Comment by morzyns** [comment]
CCXT version: 1.14.205

**Comment by kroitor** [comment]
@morzyns can you plz paste the minimal working snippet of your code (including the instantiation) to reproduce the issue? I mean, just a single file (an entire small Node program, 10 to 15 lines) that can be used to reproduce it, (without your keys, of course)? Because we are not seeing the same issue on our side, need to debug this further. We need to make sure that nothing is adding some interference here, therefore need to make it the smallest possible, but a complete runnable program.

**Comment by morzyns** [comment]
Sure,
        ```
    this.exchange = this.configService.getActiveExchange();
            this.exchangeName = this.exchange.name;
            const key = this.exchange.key;
            const secret = this.exchange.secret;
            this.exchange = new ccxt[this.exchange.name]({
                'options': {
                    'adjustForTimeDifference': true,
                    'verbose': true,
                     'recvWindow': 10000000,
                 }
            });
            this.exchange.apiKey = key;
            this.exchange.verbose = true;
            this.exchange.secret = secret;
            this.exchange.timeout = 5000;
            this.exchange.userAgent = "Trader2";
        } catch (e) {
            this.handleErrors(e);
    }
```

then:



```
  async uniCancelOrder(id, symbol) {
        let confirmation;
        try {
                confirmation = await this.exchange.cancelOrder(id, symbol, []);
            return confirmation;
        } catch (e) {
            this.handleErrors(e);
        }
    }

    cancelOrder(id, symbol) {
        return Observable.fromPromise(this.uniCancelOrder(id, symbol));
    }
```

**Comment by morzyns** [comment]
Sorry, full code looked like this : 
```
initExchange() {
        this.exchange = this.configService.getActiveExchange();
        try {
            this.exchange.sign = function (path, api = 'public', method = 'GET', params = {}, headers = undefined, body = undefined) {
                let url = this.urls['api'][api];
                url += '/' + path;
                if (api === 'wapi')
                url += '.html';
                // v1 special case for userDataStream
                if (path === 'userDataStream') {
                    body = this.urlencode (params);
                    headers = {
                        'X-MBX-APIKEY': this.apiKey,
                        'Content-Type': 'application/x-www-form-urlencoded',
                    };
                } else if ((api === 'private') || (api === 'wapi')) {
                    this.checkRequiredCredentials ();
                    let query = this.urlencode (this.extend ({
                        'timestamp': this.nonce (),
                        'recvWindow': this.options['recvWindow'],
                    }, params));
                    let signature = this.hmac (this.encode (query), this.encode (this.secret));
                    query += '&' + 'signature=' + signature;
                    headers = {
                        'X-MBX-APIKEY': this.apiKey,
                    };
                    if ((method === 'GET') || (method === 'DELETE') || (api === 'wapi')) {
                        url += '?' + query;
                    } else {
                        body = query;
                        headers['Content-Type'] = 'application/x-www-form-urlencoded';
                    }
                } else {
                    if (Object.keys (params).length)
                    url += '?' + this.urlencode (params);
                }
                return { 'url': url, 'method': method, 'body': body, 'headers': headers };
            }

            this.exchangeName = this.exchange.name;
            const key = this.exchange.key;
            const secret = this.exchange.secret;
            this.exchange = new ccxt[this.exchange.name]({
                'options': {
                    'adjustForTimeDifference': true,
                    'verbose': true,
                    'recvWindow': 10000000,
                  }
                });
            this.exchange.apiKey = key;
            this.exchange.verbose = true;
            // this.exchange.enableRateLimit = true;
            this.exchange.secret = secret;
            this.exchange.timeout = 5000;
            this.exchange.userAgent = "Trader2";
        } catch (e) {
            this.handleErrors(e);
        }
    }

async uniCancelOrder(id, symbol) {
let confirmation;
try {
confirmation = await this.exchange.cancelOrder(id, symbol, []);
return confirmation;
} catch (e) {
this.handleErrors(e);
}
}

cancelOrder(id, symbol) {
    return Observable.fromPromise(this.uniCancelOrder(id, symbol));
}
```

**Comment by kroitor** [comment]
Ok, now I see why my override didn't work for you – you should place it after initializing the exchnage class, below this like 

```
            this.exchange = new ccxt[this.exchange.name]({
                'options': {
                    'adjustForTimeDifference': true,
                    'verbose': true,
                    'recvWindow': 10000000,
                  }
                });
```

So, see here your edited script with the `sign` override moved below the exchange instantiation line:

```
initExchange() {
        this.exchange = this.configService.getActiveExchange();
        try {

            this.exchangeName = this.exchange.name;
            const key = this.exchange.key;
            const secret = this.exchange.secret;
            this.exchange = new ccxt[this.exchange.name]({
                'options': {
                    'adjustForTimeDifference': true,
                    'verbose': true,
                    'recvWindow': 10000000,
                  }
                });
            this.exchange.apiKey = key;
            this.exchange.verbose = true;
            // this.exchange.enableRateLimit = true;
            this.exchange.secret = secret;
            this.exchange.timeout = 5000;
            this.exchange.userAgent = "Trader2";
            this.exchange.sign = function (path, api = 'public', method = 'GET', params = {}, headers = undefined, body = undefined) {
                let url = this.urls['api'][api];
                url += '/' + path;
                if (api === 'wapi')
                url += '.html';
                // v1 special case for userDataStream
                if (path === 'userDataStream') {
                    body = this.urlencode (params);
                    headers = {
                        'X-MBX-APIKEY': this.apiKey,
                        'Content-Type': 'application/x-www-form-urlencoded',
                    };
                } else if ((api === 'private') || (api === 'wapi')) {
                    this.checkRequiredCredentials ();
                    let query = this.urlencode (this.extend ({
                        'timestamp': this.nonce (),
                        'recvWindow': this.options['recvWindow'],
                    }, params));
                    let signature = this.hmac (this.encode (query), this.encode (this.secret));
                    query += '&' + 'signature=' + signature;
                    headers = {
                        'X-MBX-APIKEY': this.apiKey,
                    };
                    if ((method === 'GET') || (method === 'DELETE') || (api === 'wapi')) {
                        url += '?' + query;
                    } else {
                        body = query;
                        headers['Content-Type'] = 'application/x-www-form-urlencoded';
                    }
                } else {
                    if (Object.keys (params).length)
                    url += '?' + this.urlencode (params);
                }
                return { 'url': url, 'method': method, 'body': body, 'headers': headers };
            }
        } catch (e) {
            this.handleErrors(e);
        }
    }

async uniCancelOrder(id, symbol) {
let confirmation;
try {
confirmation = await this.exchange.cancelOrder(id, symbol, []);
return confirmation;
} catch (e) {
this.handleErrors(e);
}
}

cancelOrder(id, symbol) {
    return Observable.fromPromise(this.uniCancelOrder(id, symbol));
}
```

Can you try this edited version now and tell if it makes a difference for you?

**Comment by morzyns** [comment]
Hi @kroitor,
- in fact, I overlooked;!
Amazingly with this override, it works fine.
Could you elaborate a little on this magic snippet?

**Comment by kroitor** [comment]
> Could you elaborate a little on this magic snippet?

Sure ) Binance error message says that their server does not see a required parameter in the request:

```
{"code":-1102,"msg":"Mandatory parameter 'symbol' was not sent, was empty/null, or malformed."}
```

Though, the `symbol` parameter is right there present in the body, as we saw in your verbose log:

```
binance DELETE https://api.binance.com/api/v3/order
Request:
...
                                              ↓ here is the symbol
timestamp=1529306968894&recvWindow=10000000&symbol=VENBTC&orderId=34089239&signature=70f38cd29a127ea2ed9448efc2ccf95d8f8d929c34e9d4c110537627b61756d6
```

So, in this case we've been sending it in the request body, but Binance did not see it.

Basically my guess was that DELETE requests work for Node.js, Python and PHP people, but not for browser people. I needed to find a way to make Binance see those params. So, what I did is I went to Binance docs and noticed that they can handle DELETE params in two ways: 

- when params are passed in the HTTP request body
- when params are passed in the URL query

So, I took the default sign implementation for binance and changed the following line:

```JavaScript
//                             ↓ added this ↓
if ((method === 'GET') || (method === 'DELETE') || (api === 'wapi')) {
```

This tells the CCXT to send all DELETE request parameters to binance via HTTP url query instead of the default HTTP request body. And it worked, from your own words. Surprise-suprise. So, now I want to thank you for helping me debug this, and I'm going to upload a fix that would not require any `sign` overrides on your side (you can safely delete that snippet after you update to the upcoming fixed version). Hope this answers your question.

**Comment by kroitor** [comment]
@morzyns this is now fixed in CCXT version 1.14.215. Thx for reporting!

**Comment by ccasselman** [comment]
I just download version `1.14.216` and getting the following error: `{"code":-1104,"msg":"Not all sent parameters were read; read '5' parameter(s) but was sent '6'."}` 

I'm using PHP.

Appears to be the same problem?

**Comment by kroitor** [comment]
@ccasselman need your verbose request and verbose response, as described by the link above in order to be able to help you.

**Comment by ccasselman** [comment]
If this is not the same error, I can repost as a new issue.

Version: `1.14.126`
Language: `PHP`

```
Request:
Array
(
    [0] => GET
    [1] => https://api.binance.com/api/v3/order?timestamp=15293358005&recvWindow=5000&symbol=SKYBTC&orderId=55716&type=BUY&signature=*****
    [2] => Array
        (
            [0] => X-MBX-APIKEY: *****
        )

    [3] => 
)

Response:
Array
(
    [0] => GET
    [1] => https://api.binance.com/api/v3/order?timestamp=1529339558005&recvWindow=5000&symbol=SKYBTC&orderId=5578916&type=BUY&signature=*****
    [2] => 400
    [3] => 
    [4] => Array
        (
            [content-type] => Array
                (
                    [0] => application/json
                )

            [transfer-encoding] => Array
                (
                    [0] => chunked
                )

            [connection] => Array
                (
                    [0] => keep-alive
                )

            [date] => Array
                (
                    [0] => Mon, 18 Jun 2018 16:32:38 GMT
                )

            [server] => Array
                (
                    [0] => nginx
                )

            [strict-transport-security] => Array
                (
                    [0] => max-age=31536000; includeSubdomains
                )

            [x-frame-options] => Array
                (
                    [0] => SAMEORIGIN
                )

            [x-xss-protection] => Array
                (
                    [0] => 1; mode=block
                )

            [x-content-type-options] => Array
                (
                    [0] => nosniff
                )

            [content-security-policy] => Array
                (
                    [0] => default-src 'self'
                )

            [x-content-security-policy] => Array
                (
                    [0] => default-src 'self'
                )

            [x-webkit-csp] => Array
                (
                    [0] => default-src 'self'
                )

            [cache-control] => Array
                (
                    [0] => no-cache, no-store, must-revalidate
                )

            [pragma] => Array
                (
                    [0] => no-cache
                )

            [expires] => Array
                (
                    [0] => 0
                )

            [x-cache] => Array
                (
                    [0] => Error from cloudfront
                )

            [via] => Array
                (
                    [0] => 1.1 f7d8a115683fdcb08e026f9afb821e4c.cloudfront.net (CloudFront)
                )

            [x-amz-cf-id] => Array
                (
                    [0] => *****
                )

        )

    [5] => {"code":-1104,"msg":"Not all sent parameters were read; read '5' parameter(s) but was sent '6'."}
)
```

**Comment by kroitor** [comment]
@ccasselman 

Looks like you're fetching and order by id and for some reason you are sending the extra `'type': 'BUY'` parameter in the third argument to `fetchOrder / fetch_order`. The `type` param is not support by / not compatible with Binance.

**Comment by ccasselman** [comment]
Dang it, some require it some do not, guess I'll have to build that logic wrapping CCXT.

Sorry about posting something stupid like that.

**Comment by kroitor** [comment]
@ccasselman no worries...

> some require it some do not, guess I'll have to build that logic wrapping CCXT.

Yeah, we will add more to this aspect, hopefully soon... Until then you will have to choose extra params carefully, cause those are exchange-specific, contrary to the other (unified) arguments of a method.

**Comment by morzyns** [comment]
Good to hear that,
Thanks for the explanation and the support for this case too.

**Comment by pelagicBKK** [comment]
was this fixed in mexc V3?  I am getting this error when indeed i am sending the symbol.. " ccxt.base.errors.ArgumentsRequired: mexc3 cancelOrder() requires a symbol argument"
