### ISSUE TITLE
btctradeim fetchOpenOrders

### ISSUE THREAD

**Issue by wahid** [ccxt/ccxt#3167]
> btctradeim https://api.btctrade.im/api/v1/trade_list/eth POST 500 Server Error: Internal Server Error for url: https://api.btctrade.im/api/v1/trade_list/eth

`api.fetchOpenOrders(market)`

- OS: Windows 10
- Programming Language version: Python
- CCXT version: Latest
- Exchange: btctradeim
- Method: fetchOpenOrders

**Comment by kroitor** [comment]
Which market is it? Are you sure that your credentials are correct?

```Python
exchange = ccxt.btctradeim({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'apiKey': 'YOUR_SECRET',
})

exchange.fetch_balance()
```

↑ Does this work?

**Comment by wahid** [comment]
All markets give this errors, fetch_balance works perfectly.

**Comment by kroitor** [comment]
@wahid can you please post your verbose request and response for that call? (need them both, but without your keys)

```Python
exchange = ccxt.btctradeim({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

exchange.load_markets ()

symbol = 'ETH/BTC'
exchange.verbose = True
print(exchange.fetch_open_orders(symbol))
```

?

**Comment by wahid** [comment]
`('\nRequest:', 'POST', 'https://api.btctrade.im/api/v1/trade_list/btc', {'Content-type': 'application/x-www-form-urlencoded', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'python-requests/2.18.4'}, 'nonce=1529289850599&coin=eth&type=open&key=key&signature=signature')
('\nResponse:', 'POST', 'https://api.btctrade.im/api/v1/trade_list/btc', '500', '{\'Expect-CT\': \'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"\', \'Transfer-Encoding\': \'chunked\', \'Set-Cookie\': \'__cfduid=uid; expires=Tue, 18-Jun-19 02:44:12 GMT; path=/; domain=.btctrade.im; HttpOnly, lang=zh_CN; expires=Thu, 15-Jun-2028 02:44:12 GMT; Max-Age=315360000; path=/\', \'Server\': \'cloudflare\', \'Connection\': \'keep-alive\', \'Date\': \'Mon, 18 Jun 2018 02:44:12 GMT\', \'CF-RAY\': \'?-AMS\', \'Content-Type\': \'text/html; charset=UTF-8\'}', u'')
Traceback (most recent call last):
  File "tt.py", line 13, in <module>
    print exchange.fetch_open_orders(symbol)
  File "C:\Python27\lib\site-packages\ccxt\coinegg.py", line 444, in fetch_open_orders
    }, params))
  File "C:\Python27\lib\site-packages\ccxt\coinegg.py", line 438, in fetch_orders
    orders = self.privatePostTradeListQuote(self.extend(request, params))
  File "C:\Python27\lib\site-packages\ccxt\btctradeim.py", line 41, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Python27\lib\site-packages\ccxt\base\exchange.py", line 304, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Python27\lib\site-packages\ccxt\base\exchange.py", line 378, in fetch
    self.handle_rest_errors(e, response.status_code, self.last_http_response, url, method)
  File "C:\Python27\lib\site-packages\ccxt\base\exchange.py", line 407, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File "C:\Python27\lib\site-packages\ccxt\base\exchange.py", line 289, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeNotAvailable: btctradeim https://api.btctrade.im/api/v1/trade_list/btc POST 500 Server Error: Internal Server Error for url: https://api.btctrade.im/api/v1/trade_list/btc`

**Comment by kroitor** [comment]
Looks like they are changing their API...

<img width="1343" alt="screen shot 2018-06-18 at 09 33 36" src="https://user-images.githubusercontent.com/1294454/41521409-bde015ba-72da-11e8-9400-92b7e8603b24.png">

**Comment by kroitor** [comment]
> No, because when you added the exchange it had the same page.

Right, however, without any proper docs from them it will be quite hard to actually fix it...

**Comment by wahid** [comment]
It seems they have added documentation in chinese. https://www.btctrade.im/help.api.html

**Comment by pcriadoperez** [comment]
Closing as btctradeim has been delisted https://github.com/ccxt/ccxt/pull/7273
