### ISSUE TITLE
react-starter-kit isNode = true within a browser

### ISSUE THREAD

**Issue by imhazige** [ccxt/ccxt#3171]
- OS:
ALL
- Programming Language version:
javascript
- CCXT version:
v1.14.2xx
- Exchange:
okex
- Method:
Exchange.js

after upgrade version from v1.14.180 to greater version, the working script will throw error.
`TypeError: Cannot read property '0' of null` when invoke new ccxt.okex(), after build with ccxt v1.14.180, it works again. I am not sure which version made the bug.

when use develop mode, it will point to this line at Exchange.js
```javascript
        if (isNode)
            this.nodeVersion = process.version.match (/\d+\.\d+.\d+/)[0]
```

I am using [react-starter-kit](https://github.com/kriasoft/react-starter-kit).

**Comment by kroitor** [comment]
Most likely related: https://github.com/ccxt/ccxt/pull/2852

**Comment by imhazige** [comment]
the script is running on browser. somehow, the start kit will make it like running in node, but actually it is not.

**Comment by kroitor** [comment]
@imhazige does 1.14.209 make a difference for you?

**Comment by imhazige** [comment]
yes, it works now, thank your quick response.
