### ISSUE TITLE
FlowBTC timeout

### ISSUE THREAD

**Issue by claufox** [ccxt/ccxt#3173]
- OS: Windows, XAMPP 3.2.2
- Programming Language version:
- CCXT version:  1.14.79
- Exchange: FlowBTC
- Method: etch_order_book ; GetProductPairs

flowbtc ->[Network Error] flowbtc POST https://api.flowbtc.com:8405/ajax/v1/GetProductPairs 28 Connection timed out after 10000 milliseconds

**Comment by claufox** [comment]
I think exchange changed the url api

**Comment by kroitor** [comment]
Not just the API URL, but their entire API specification is now completely different: https://www.flowbtc.com.br/api.html. Consider FlowBTW support in CCXT broken until we reimplement it.
