### ISSUE TITLE
Bitfinex : ByPass Cloudflare solutions :still throwing DDOS protection

### ISSUE THREAD

**Issue by DaveMG3** [ccxt/ccxt#3175]
In order to use Clouscrape in my PHP code for fetching OHLCVs, I implemented code to interact, for each pair symbol of my list, with a Python script callable via the command line using symphony process. (in the PHP code, there is a` usleep($ccxt_exchange->rateLimit  * 1000);` between each symbol call)
But with cfscrape activated and even with rate limit set on ccxt exchange object, after fetching more than 10 candles, i still have the DDOS protection error with error: ERR_RATE_LIMIT .

To test what i was doing i simplified my code as per below and still see with that the DDOS error : 
Could  you tell what i am doing wrong or if the cfscrape solution is always reliable?

For now, only when i multiply ccxt exchange rate limit *3 (which mean 4500ms) that i can bypass DDOS error

```
#!/usr/bin/env python`

import sys
import json
import cfscrape
import ccxt

def print_supported_exchanges():
    print('Supported exchanges:')
    print(', '.join(ccxt.exchanges))


try:
	x=sys.argv[1]
	data=json.loads(x)

	ccxt_id = data['ccxt_id'];
	#symbol = data['symbol'];
	timeframe = data['timeframe'];
	since_ms = int(data['since_ms']);

	  # check if the exchange is supported by ccxt
	exchange_found = ccxt_id in ccxt.exchanges
	
	if exchange_found:

		#print('Instantiating ' + ccxt_id + ' exchange')

		# instantiate the exchange by id
		exchange = getattr(ccxt, ccxt_id)({
			'timeout': 20000,
			'session': cfscrape.create_scraper(),
		})
		exchange.enableRateLimit = True  # enable
		
		#print('Load OHLCVs...')
		
		try:

			# load all markets from the exchange
			markets = exchange.load_markets()
			
			symbols = exchange.symbols  
			for symbols in symbol:
				ohlcvs = exchange.fetch_ohlcv(symbol, timeframe, since_ms)
				print(json.dumps(ohlcvs))#loop for test
			
			#print('Succeeded.')
			#print(json.dumps(ohlcvs))
			
		except ccxt.DDoSProtection as e:

			print(type(e).__name__, str(e))
			print('DDoSProtection.')	
			
		except ccxt.BaseError as e:

			print(type(e).__name__, str(e))
			print('Failed.')

	else:

		print('Exchange ' + ccxt_id + ' not found')
		print_supported_exchanges()

 
except Exception as e:
	print('[' + type(e).__name__ + ']', str(e))
	print('Usage: python ' + sys.argv[0] + ' ccxt')
	
```
	

- OS: Windows
- Programming Language version: PHP and Python
- CCXT version: 1.14.211
- Exchange: Bitfinex
- Method: FetchOHLCV

**Comment by kroitor** [comment]
> But with cfscrape activated and even with rate limit set on ccxt exchange object, after fetching more than 10 candles, i still have the DDOS protection error with error: ERR_RATE_LIMIT .

First of, there are two types of DDoSProtection errors:

- from cloudflare/incapsula
- from the exchange itself

I've just added a few clarifications on this to the Manual.

> Could you tell what i am doing wrong or if the cfscrape solution is always reliable?

In your particular case, your Cloudflare-things are fine, the Bitfinex itself is not letting you query their OHLCV endpoint more frequently than 10 times per minute.

If you open their docs, you'll notice their rate-limits varying for different endpoints:

![bitfinex-rate-limit](https://user-images.githubusercontent.com/1294454/41561868-b1de89da-7353-11e8-8357-d2601a07747c.jpg)

However, if you're going to try those rate limits, you'll often find that their actual rate limit is set two times lower than the documented threshold, like it was already noted here: 

- https://github.com/ccxt/ccxt/issues/2041 (highly recommended to read)

Unfortunately, their rate limit for the OHLCV endpoint is not documented at all. So, assuming that the actual rate limit is set at 10 requests per minute, your task is to:

- either do manual rate limiting
- use the built-in rate-limiter properly

If you would do the manual rate limiting, you should do approximately this:

```PHP
// PHP
$rateLimit = 60 / 10; // 10 requests per minute (60 seconds) = every 6th second
usleep (rateLimit * 1000000); // sleep for 6 seconds in microseconds between the calls
```

However, the recommended way of doing this is to use the built-in rate-limiter like so:

```Python
# Python 
exchange = ccxt.exchange ({
    'enableRateLimit': True,
    'rateLimit': 60 / 10 * 1000, // in milliseconds
})
```

```PHP
// PHP
$exchange = new \ccxt\bitfinex (array (
    'enableRateLimit' => true,
    'rateLimit' => 60 / 10 * 1000, // in milliseconds
));
```

+ remove your `usleep` calls (not needed when the built-in rate-limiter is enabled).

Hope this answers your question. Let us know if not.

**Comment by DaveMG3** [comment]
I thought having
` 'enableRateLimit' => true`  was enough to activate ccxt native rate limiter.
 But in fact I understand we need to add this additional code  `   'rateLimit' => 60 / 10 * 1000, // in milliseconds`.
The manual, section Rate Limit, has only explanation of the 1st parameter to be set. The need of 2nd parameter to be set might need to be expressed too.

PHP code calling Python script for each symbol causes same mistake as in your  https://github.com/ccxt/ccxt/issues/2041, i.e creating each time an instance of exchange in python. To avoid that, i would like to retrieve only 'session or 'cookie' from python script and set in on PHP exchange instance, is there already a undocumented method for that?
