### ISSUE TITLE
LBank :VET/BTC throw error  This currency pair is not supported

### ISSUE THREAD

**Issue by DaveMG3** [ccxt/ccxt#3179]
Hi,

For Lbank  Exchange.market provide VET/BTC in list of pair but this pair throws following error when trying to fetch OHLCV:
`Exchange Error This currency pair is not supported`

Nota : the usual symbol of VET is VEN (as on CMC) so I tested also with VEN/BTC
 but =>`Exchange  Error No market symbol VEN/BTC`

- Programming Language version: Python and PHP
- CCXT version: 1.14.211
- Exchange: Lbank
- Method:FetchOHLCV

**Comment by kroitor** [comment]
> Exchange Error This currency pair is not supported

If you see an exchange error like that, that is the message coming from the exchange, so in this case, it's the failure on the side of LBank...

From their API endpoint here https://api.lbank.info/v1/currencyPairs.do you can clearly see in their response, the VET symbols present there:

> ["pch_usdt","dax_usdt","btc_usdt","eth_usdt","bch_usdt","neo_usdt","vet_usdt","qtum_usdt","zec_usdt","pch_btc","pnt_btc","dax_btc","eth_btc","bch_btc","ltc_btc","neo_btc","dash_btc","vet_btc","etc_btc","qtum_btc","btg_btc","zec_btc","sc_btc","bts_btc","bcd_btc","cmt_btc","abt_btc","cpx_btc","xwc_btc","sbtc_btc","fil6_btc","fil12_btc","fil36_btc","btf_btc","ptt_eth","wicc_eth","tac_eth","qkc_eth","afc_eth","idhub_eth","sead_eth","ssc_eth","skm_eth","pch_eth","iic_eth","ply_eth","ext_eth","dax_eth","bch_eth","eos_eth","trx_eth","vet_eth","qtum_eth","zec_eth","bts_eth","btm_eth","mith_eth","nas_eth","man_eth","cmt_eth","dbc_eth","bto_eth","abt_eth","ddd_eth","cpx_eth","cs_eth","iht_eth","ink_eth","tky_eth","ocn_eth","dct_eth","yoyow_eth","zsc_eth","zpt_eth","eko_eth","mda_eth","pst_eth","xwc_eth","put_eth","tgc_eth","pnt_eth","aac_eth","fil6_eth","fil12_eth","fil36_eth","uip_eth","lch_eth","seer_eth","bsb_eth","cdc_eth","grams_eth","ddm_eth","eai_eth","inc_eth","ply_qtum","mith_qtum","ink_qtum","bot_qtum","qbt_qtum","put_qtum","ent_qtum","chat_qtum","aac_qtum","ext_neo","dbc_neo","cpx_neo","tky_neo","zpt_neo","yoyow_bts","seer_bts"]

So, in this case, Lbank reported first with "here are the symbols that are ok to trade with", and then, when you're trying to fetch one of them – it will say "this currency pair is not supported". So, it is obviously an error on lbank side, if they themselves list the symbol that they do not support for trading. I guess, you should query Lbank support on this issue.

**Comment by DaveMG3** [comment]
You right. I contacted them. I will post there feedback when i get it.

**Comment by kroitor** [comment]
@DaveMG3 Hey ) Did you get any response from them on this issue? )

**Comment by Cleric334** [comment]
Hey, I have the same issue with Lbank, but with BCH pairs. 
The API returns them as normal, but when I am trying to trade them, I get 
"This currency pair is not supported" message

**Comment by DaveMG3** [comment]
Hi both,
I contacted them 2 days ago but no feedback yet.
Indeed the following BCH/BTC, BCH/ETH, BCH/USDT , VET/BTC, VET/ETH of Lbank raise the same error message.
@Cleric334 , you might drop them a line also, to stress the customer impact
