### ISSUE TITLE
User-agent cannot have 'JavaScript'. Will refuse 403.

### ISSUE THREAD

**Issue by stalllllllker** [ccxt/ccxt#3181]
User-agent cannot have 'JavaScript'. Will refuse 403.
I have tested ,without 'JavaScript' can work well.

URL:/api/v1/ticker/24hr?
Host: www.binance.com
User-agent: ccxt/1.7.105 (+https://github.com/kroitor/ccxt) Node.js/8.6.0 (JavaScript)

- OS: centos7
- Programming Language version: en
- CCXT version: Node.js/8.6.0 (JavaScript)
- Exchange: Binance
- Method: GET

**Comment by kroitor** [comment]
@stalllllllker your version is way too old... The current version is 1.14.224, and I'd really recommend you to update your installation of the library. Hope this answers your question.
