### ISSUE TITLE
Kraken - fetchBalance - Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by bohdanz1997** [ccxt/ccxt#3182]
Unhandled error

- OS: Linux
- Programming Language version: nodejs 9.7.0
- CCXT version: 1.14.208
- Exchange: Kraken
- Method: fetchBalance

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at kraken.fetchMarkets (/home/dev/work/project/node_modules/ccxt/js/kraken.js:246:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)

**Comment by kroitor** [comment]
Need to see your code to reproduce the issue (without your keys) + your **verbose request** and **verbose response**, precisely as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by kroitor** [comment]
I'd close this for now until we have a follow up. Feel free to reopen this if needed or just questions if any.
