### ISSUE TITLE
Kucoin fetch all orders

### ISSUE THREAD

**Issue by Umbralith** [ccxt/ccxt#3183]
With the current implementation for Kucoin, getting orders require a symbol, but if you pass a blank string, it will return all orders for all symbols. Can we get an official implementation for this so we don't have to ovverride the function?

**Comment by kroitor** [comment]
> Can we get an official implementation for this so we don't have to ovverride the function?

Sure, your pull requests are welcome: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
