### ISSUE TITLE
Exchange gateio incorrect timestamp handling in fetchTrades API.

### ISSUE THREAD

**Issue by ggicci** [ccxt/ccxt#3184]
- OS: macOS High Sierra (Version 10.13.5)
- Programming Language version: Python 2.7.14 [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
- CCXT version: 1.14.161
- Exchange: gateio
- Method: fetch_trades

Return data sample of my call to `fetch_trades`:

```json
[
  {
    "amount": 0.10014019,
    "datetime": "2018-06-17T18:32:34.000Z",  // should be "2018-06-18T02:32:34.000Z"
    "id": "68749647",
    "info": {
      "amount": "0.10014019",
      "date": "2018-06-18 02:32:34",
      "rate": "0.1299",
      "timestamp": "1529289154",
      "total": "0.013008210681",
      "tradeID": "68749647",
      "type": "buy"
    },
    "price": 0.1299,
    "side": "buy",
    "symbol": "BCH/BTC",
    "timestamp": 1529260354000,  // should be 1529289154000
    "type": null
  }
]
```
The unified fields `timestamp` and `datetime` do not match `info.timestamp`. In deed we expect them to represent a same time point.

See source code file [gateio.js#L321](https://github.com/ccxt/ccxt/blob/d6469e022c18831d9888c83e2f572e3639559644/js/gateio.js#L321). It's better to parse `info.timestamp` but not `info.date`, since `info.date` is a string and it doesn't contain timezone info. This code assumes it is in `+08:00` zone, but actually the `info.date` in the sample above is in zero zone.

Because of the incorrect parse of timestamp, call to `fetch_trades` with `since` parameter (filter) will produce wrong results.

**Comment by kroitor** [comment]
Thx for reporting and fixing it in #3185 !
