### ISSUE TITLE
BITMEX: fetchOHLCV does not work correct way

### ISSUE THREAD

**Issue by aav80** [ccxt/ccxt#3191]
Hello, does bitmex correcly support fetchOHLCV ?
when I do `fetchOHLCV (Symbol, "1m" , undefined, neededhistory )`, it gives somethig like:
`1462420860000,,,,,0,1462420920000,,,,,0`
it is exactly not what I receive from binance, which works correct way

**Comment by kroitor** [comment]
> Hello, does bitmex correcly support fetchOHLCV ?

It should.

> it is exactly not what I receive from binance, which works correct way

Without knowing the values of `Symbol` and `neededhistory` it's really hard to tell. But, please, don't post just those two values. Instead, please, read this very carefully:

- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it
- https://github.com/ccxt/ccxt/wiki/FAQ#i-am-calling-a-method-and-i-get-an-error-what-am-i-doing-wrong
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

↑ If you can, please post your code and verbose request and verbose response, following precisely the rules from the CONTRIBUTING doc. Otherwise it will be really hard to help you without proper info from you.  Standing by for a followup from you.

**Comment by aav80** [comment]
`"use strict";
const ccxt = require ('ccxt')
const BITMEX_API_DATA = require ('a:/API/bitmex_testnet.js')
let exchange = new ccxt.bitmex ({
    'apiKey': BITMEX_API_DATA.BITMEX_TESTNET_API_KEY,
    'secret': BITMEX_API_DATA.BITMEX_TESTNET_API_SECR,
    enableRateLimit: true 
})

;(async function main () {
    if ('test' in exchange.urls) exchange.urls['api'] = exchange.urls['test'] // ----- switch the base URL to testnet
    let ohlcv = await exchange.fetchOHLCV ("BTC/USD", "1m" , undefined, 5 )
    console.log (ohlcv )
    return
}) ()`

And here is console command and response:
`C:\Users\user\www\candle>node bitmex-test.js
[ [ 1462420860000, null, null, null, null, 0 ],
  [ 1462420920000, null, null, null, null, 0 ],
  [ 1462420980000, null, null, null, null, 0 ],
  [ 1462421040000, null, null, null, null, 0 ],
  [ 1462421100000, null, null, null, null, 0 ] ]`

Can you please tell, what's wrong?

**Comment by kroitor** [comment]
Their testnet does not have any OHLCV trading data (no trading is going on there).

```JavaScript
"use strict";
const ccxt = require ('ccxt')
const BITMEX_API_DATA = require ('a:/API/bitmex_testnet.js')
let exchange = new ccxt.bitmex ({
   'apiKey': BITMEX_API_DATA.BITMEX_TESTNET_API_KEY,
   'secret': BITMEX_API_DATA.BITMEX_TESTNET_API_SECR,
   enableRateLimit: true 
})

;(async function main () {

   // ↓↓↓ remove this line ↓↓↓

   if ('test' in exchange.urls) exchange.urls['api'] = exchange.urls['test'] // ----- switch the base URL to testnet

  // ↑↑↑ remove this line ↑↑↑

   let ohlcv = await exchange.fetchOHLCV ("BTC/USD", "1m" , undefined, 5 )
   console.log (ohlcv )
   return
}) ()
```

Let us know if this does not help.

**Comment by kroitor** [comment]
P.S. don't forget to switch from testnet apikeys to actual main api credentials.

**Comment by aav80** [comment]
Done as you told, now it works, but writes incorrect values:
```
C:\Users\user\www\candle>node bitmex-test.js
[ [ 1483228800000, 968.29, 968.29, 968.29, 968.29, 0 ],
  [ 1483228860000, 968.29, 968.76, 968.49, 968.7, 12993 ],
  [ 1483228920000, 968.7, 968.7, 967.2, 968.43, 73800 ],
  [ 1483228980000, 968.43, 968, 967.21, 967.21, 3500 ],
  [ 1483229040000, 967.21, 967.21, 966.74, 966.97, 15969 ] ]
```

It seems not like bitcoin/usd values near 967

**Comment by kroitor** [comment]
```
mbp:ccxt igorkroitor$ node examples/js/cli bitmex fetchOHLCV BTC/USD 1m undefined 5
bitmex.fetchOHLCV (BTC/USD, 1m, , 5)
-------------------------------------------
[1483228740000, 968.29, 968.29, 968.29, 968.29, 0]
-------------------------------------------
[ 1483228800000,
  968.29,
  968.76,
  968.49,
  968.7,
  12993          ]
-------------------------------------------
[ 1483228860000,
  968.7,
  968.7,
  967.2,
  968.43,
  73800          ]
-------------------------------------------
[1483228920000, 968.43, 968, 967.21, 967.21, 3500]
-------------------------------------------
[ 1483228980000,
  967.21,
  967.21,
  966.74,
  966.97,
  15969          ]
1483228740000  968.29  968.29  968.29  968.29  0
1483228800000  968.29  968.76  968.49  968.7   12993
1483228860000  968.7   968.7   967.2   968.43  73800
1483228920000  968.43  968     967.21  967.21  3500
1483228980000  967.21  967.21  966.74  966.97  15969
mbp:ccxt igorkroitor$ node
> new Date (1483228800000)
2017-01-01T00:00:00.000Z
>
```

↑ You're watching at prices starting from 1st of January 2017, that's more than one year old, of course they will be different. In order to fetch a more recent history, you should pass the `since` argument to it as well (`undefined` in your example).

```JavaScript
   let since = exchange.parse8601('2018-06-01T00:00:00')
   let ohlcv = await exchange.fetchOHLCV ("BTC/USD", "1m" , since, 5 )
   console.log (ohlcv)
```

Does this solve your issue?

**Comment by kroitor** [comment]
```
> mbp:ccxt igorkroitor$ node examples/js/cli bitmex fetchOHLCV BTC/USD 1m 2018-06-01T00:00:00 5
bitmex.fetchOHLCV (BTC/USD, 1m, 1527811200000, 5)
-------------------------------------------
[ 1527811200000,
  7485.5,
  7485,
  7481.5,
  7482,
  790223         ]
-------------------------------------------
[1527811260000, 7482, 7484, 7481.5, 7484, 1224253]
-------------------------------------------
[1527811320000, 7484, 7484, 7483.5, 7484, 291226]
-------------------------------------------
[1527811380000, 7484, 7484, 7483.5, 7484, 152956]
1527811200000  7485.5  7485  7481.5  7482  790223
1527811260000  7482    7484  7481.5  7484  1224253
1527811320000  7484    7484  7483.5  7484  291226
1527811380000  7484    7484  7483.5  7484  152956
mbp:ccxt igorkroitor$
```

**Comment by aav80** [comment]
Now works perfect. Thank you.

BTW, don't you know, does BitMEX allow to get last N bars? (for example, binance allows) Or I need to calculate date and time and then access fetchOHLCV ?

**Comment by kroitor** [comment]
> Or I need to calculate date and time and then access fetchOHLCV ?

This is exchange-specific, so if you want to make sure that you're getting a period of history you want exactly – then you really should specify the `since` argument to it. Hope this answers your question. Closing it for now, if you don't mind. Thx!
