### ISSUE TITLE
Coinfloor: python's fetch_balance returns 'requires a symbol param' when one is present

### ISSUE THREAD

**Issue by asiva** [ccxt/ccxt#3192]
Using python 3.5.2 on Linux Mint, with ccxt 1.14.172, and trying to use Coinfloor's interface from the following:
```
cf = ccxt.coinfloor()
cf.verbose = True
cf.uid = snip
cf.apiKey = snip
cf.password = snip
cf.fetch_open_orders('BTC/GBP')
```
fetch_open_orders succeeds, so the authentication is correct. However trying:
```
cf.fetch_balance('BTC/GBP') 
```
returns:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "snip/env/lib/python3.5/site-packages/ccxt/coinfloor.py", line 77, in fetch_balance
    raise NotSupported(self.id + ' fetchBalance requires a symbol param')
ccxt.base.errors.NotSupported: coinfloor fetchBalance requires a symbol param
```
fetch_balance() and fetch_open_orders() (i.e. without the string 'BTC/GBP') also return the same error. Any help would be most appreciated.

**Comment by kroitor** [comment]
>ccxt.base.errors.NotSupported: coinfloor fetchBalance requires a symbol param
> fetch_balance() and fetch_open_orders() (i.e. without the string 'BTC/GBP') also return the same error.

Right, the error message may not be very clear there, but whenever you see:

- `requires a Blabla argument` – that means that it is missing the necessary method argument
- `requires a Blabla parameter` – that means that it is missing the necessary extra method parameter (passed in the last argument to the `fetchBalance`).

All extra parameters in CCXT are passed in the following way:

```
extraParams = {
    'param1': 'value1',
    'param2': 'value2',
}

methodName (arg1, arg2, extraPrams)
```

Now, the signature of `fetchBalance` is:

```
fetchBalance (params = {}) // empty extra params by default
```

So it does not have any args, except the last extra params argument, and the call should look like:

```
cf.fetchBalance ({
    'symbol': 'BTC/USD',
})
```

All of the above is documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
