### ISSUE TITLE
CORS Limitations and ES6 import of specific exchanges

### ISSUE THREAD

**Issue by GoChartingAdmin** [ccxt/ccxt#3193]
While playing with the browser version of ccxt on binance, I realized that ccxt relies on proxies to bypass CORS on certain exchanges such as binance.  I like the solutions provided but would like to know your views around using JSONP.  The proxies provided are sometimes unreliable and they timeout during peak loads.  I am new to this world so please consider it as a naive query rather than a strong implementation/enhancement suggestion.  User can choose whether he wants to go for a jsonp fetch or a normal fetch based on his use case.

Also, for people interested in using the package over web (browsers), how can I import only those exchanges that I need rather than the entire bulky module - similar to how we import certain lodash functions

https://github.com/camsong/fetch-jsonp

Appreciate your thoughts

- OS: Linux
- Programming Language version: JS
- CCXT version: 1.14.230
- Exchange: Binance
- Method: Web/Browser

**Comment by frosty00** [comment]
we will investigate the use of jsonp to avoid cross origin issues in the brower

**Comment by frosty00** [comment]
jsonp needs to be supported server side so it cannot help us
