### ISSUE TITLE
bittrex fetchOpenOrders and fetchClosedOrders return empty array

### ISSUE THREAD

**Issue by Stas-Buzunko** [ccxt/ccxt#3195]
- OS: ios
- Programming Language version: js
- CCXT version: 1.14.231
- Exchange: bittrex
- Method: fetchOpenOrders / fetchClosedOrders

I've tried both specifying symbol and without.

There are 30 coins returned in fetchBalance and I couldn't get any order on any of them. All I get is empty array.

I've even tried iterating over each coin that makes a pair and pass it to fetchOpenOrders / fetchClosedOrders. (Like if I have BTC on balance, take all pairs from markets that have BTC and iterate over each of them and pass it fetchOpenOrders / fetchClosedOrders)

Any ideas?

**Comment by kroitor** [comment]
Let's make sure that we understand each other properly – you did create orders with a certain Bittrex market (aka *pair* or *symbol*) previously and you when you are fetching open or closed orders from that market – you're getting an empty array right? The purpose of `fetchOpenOrders` and `fetchClosedOrders` is to fetch your own orders from the exchange history, is that what you're trying to do?

**Comment by kroitor** [comment]
> yes, I need order history

It's not very clear which particular order history you want, do you mean the history of orders made from that user account previously?

> need to display cost and profit/loss

You have to be very specific, namely, cost of what? Cost of some past trades / orders made from that account? Or the actual cost of current orders in the orderbook for that pair? Or the cost of some currency in terms of another currency?

**Comment by Stas-Buzunko** [comment]
A user has 1 BTC on Balance. I need to display price it was bought for (converted into USD) and a difference with a current price (profit/loss)

Is it clear now? I need past trades on BTC, I was able to do this with fetchMyTrades on other exchanges, but I cannot get past trades from bittrex

https://github.com/ccxt/ccxt/issues/3101

**Comment by kroitor** [comment]
I'd recommend to start with something basic first. Let's pick a pair and let's make sure that you can get at least the order history for the chosen pair first. Then you will move to multiple symbols from there. So, pick a symbol that you know is having some order history for sure, and put it along with your api keys into the following example script:

https://github.com/ccxt/ccxt/blob/master/examples/js/bittrex-fetch-closed-orders-history.js

```JavaScript
'use strict';

const ccxt = require ('../../ccxt')
    , log = require ('ololog').noLocate
    , asTable = require ('as-table')
    , exchange = new ccxt.bittrex ({
        'enableRateLimit': true,
        'apiKey': 'YOUR_API_KEY', // ←---------------- your keys here
        'secret': 'YOUR_API_SECRET', // ←---------------- your keys here
    })

;(async () => {

    await exchange.loadMarkets ()

    const symbol = 'ETH/BTC' // ←------------------- chosse your symbol

        , market = exchange.markets[symbol]
        , startingDate = '2017-01-01T00:00:00'
        , now = exchange.milliseconds ()

    log.bright.green ('\nFetching history for:', symbol, '\n')

    let allOrders = [];
    let since = exchange.parse8601 (startingDate)

    while (since < now) {

        try {

            log.bright.blue ('Fetching history for', symbol, 'since', exchange.iso8601 (since))
            const orders = await exchange.fetchClosedOrders (symbol, since)
            log.green.dim ('Fetched', orders.length, 'orders');

            allOrders = allOrders.concat (orders)

            if (orders.length) {

                const lastOrder = orders[orders.length - 1];
                since = lastOrder['timestamp'] + 1;

            } else {

                break; // no more orders left for this symbol, move to next one
            }

        } catch (e) {

            log.red.unlimited (e)

        }
    }

    // omit the following keys for a compact table output
    // otherwise it won't fit into the screen width
    const omittedKeys = [
        'info',
        'timestamp',
        'lastTradeTimestamp',
        'fee',
    ]

    log.yellow (asTable (allOrders.map (order => exchange.omit (order, omittedKeys))))
    log.green ('Fetched', allOrders.length, symbol, 'orders in total');

    // do whatever you want to do with them, calculate profit loss, etc...

}) ()

```

Documented here:

- https://github.com/ccxt/ccxt/wiki/Manual#querying-orders
- https://github.com/ccxt/ccxt/wiki/Manual#closed-orders

Does this work for one symbol?

**Comment by kroitor** [comment]
After launching the above script you should see something similar to this, depending on your actual history for that symbol...

![bittrex-order-history](https://user-images.githubusercontent.com/1294454/41687130-45eb0be8-74ef-11e8-8522-20395ca23d62.jpg)

**Comment by Stas-Buzunko** [comment]
ok, will try soon, thanks

**Comment by Stas-Buzunko** [comment]
It worked and I didn't even change my code, only updated to latest version. I didn't pay enough attention when updated and I thought it was the same.

Not sure whether  1.14.163 had this bug or it was my imagination.

Sorry for your time.

**Comment by kroitor** [comment]
@Stas-Buzunko thx for reporting back!

**Comment by Stas-Buzunko** [comment]
@kroitor I have no idea how and why I thought that I saw trades in response. no idea.

I went on and found out that some people say that Bittrex returns trades only for last 28-30 days. Do you have such info?

Here are some links

https://www.reddit.com/r/BitcoinMarkets/comments/87v35w/is_there_a_way_to_fetch_trading_history_from/
https://cointracking.info/import/bittrex_api/
https://github.com/ericsomdahl/python-bittrex/issues/87#issuecomment-344716765

This would explain why I receive empty trades.

**Comment by kroitor** [comment]
> Do you have such info?

Yep, we do. They will limit it to a month, so you have to do this continuously. Does this answer your question?

**Comment by Stas-Buzunko** [comment]
I see, no it makes sense. And the only way to get older than 1 month is via CSV export from the account, correct?

**Comment by kroitor** [comment]
> And the only way to get older than 1 month is via CSV export from the account, correct?

Exactly.

**Comment by CHEYULIU** [comment]
> 
> 
> After launching the above script you should see something similar to this, depending on your actual history for that symbol...
> 
> ![bittrex-order-history](https://user-images.githubusercontent.com/1294454/41687130-45eb0be8-74ef-11e8-8522-20395ca23d62.jpg)

Is there an example of python?

**Comment by kroitor** [comment]
@CHEYULIU will add it shortly

**Comment by kroitor** [comment]
@CHEYULIU please, see the python version here: https://github.com/ccxt/ccxt/blob/master/examples/py/bittrex-fetch-closed-orders-history.py
