### ISSUE TITLE
Bitmex BTC/USD gives exploded volume 

### ISSUE THREAD

**Issue by DaveMG3** [ccxt/ccxt#3199]
Hello Kroitor,
It seems ohlcv Bitmex gives some exploded volumes for all base/quote type BTC/USD as BTC/USD, XBTM18, XBTU18 as per below screenshot.
Looking at Bitmex API results, it might be that the received volume of ccxtis in quote USD instead of base BTC.
- OS:
- Programming Language version: PHP and Python
- CCXT version: 1.14.211
- Exchange: Bitmex
- Method:
![image](https://user-images.githubusercontent.com/32598581/41687052-ac03fc68-74e6-11e8-9948-32b7a5d2ab62.png)

**Comment by kroitor** [comment]
Hi) 

Duplicate: https://github.com/ccxt/ccxt/issues/2808
