### ISSUE TITLE
Bitrrex wallet status not good fetchCurrencies

### ISSUE THREAD

**Issue by fonzmeister** [ccxt/ccxt#3206]
- Ubuntu
- Python: 3.5
- CCXT version: 1.14.189
- Exchange: bittrex
- Method: fetchCurrencies()

For example

```bit.fetchCurrencies()['CANN']``` has de following output: 

``` {'code': 'CANN', 'fee': 0.2, 'status': 'ok', 'precision': 8, 'limits': {'amount': {'max': 100000000.0, 'min': 1e-08}, 'withdraw': {'max': 100000000.0, 'min': 0.2}, 'price': {'max': 100000000.0, 'min': 1e-08}, 'cost': {'max': None, 'min': None}}, 'info': {'MinConfirmation': 300, 'Notice': 'Automated Maintenance.', 'Currency': 'CANN', 'TxFee': 0.2, 'IsActive': False, 'CurrencyLong': 'CannabisCoin', 'BaseAddress': None, 'CoinType': 'BITCOIN'}, 'address': None, 'type': 'BITCOIN', 'active': False, 'name': 'CannabisCoin', 'id': 'CANN'} ```

As you can see the wallet is in Automated Maintance and 'IsActive'  is False while the unified status is 'ok'

I would expect that the status would change to 'disabled' because you cannot withdraw or deposit this coin at the moment

**Comment by kroitor** [comment]
> I would expect that the status would change to 'disabled' because you cannot withdraw or deposit this coin at the moment

The `status` is deprecated there, so you should look into the `active` flag instead:

```Python
{'active': False,  # ←----------------------------- this one
 'address': None,
 'code': 'CANN',
 'fee': 0.2,
 'id': 'CANN',
 'info': {'BaseAddress': None,
          'CoinType': 'BITCOIN',
          'Currency': 'CANN',
          'CurrencyLong': 'CannabisCoin',
          'IsActive': False,
          'MinConfirmation': 300,
          'Notice': 'Automated Maintenance.',
          'TxFee': 0.2},
 'limits': {'amount': {'max': 100000000.0, 'min': 1e-08},
            'cost': {'max': None, 'min': None},
            'price': {'max': 100000000.0, 'min': 1e-08},
            'withdraw': {'max': 100000000.0, 'min': 0.2}},
 'name': 'CannabisCoin',
 'precision': 8,
 'status': 'ok',
 'type': 'BITCOIN'}
```

Let us know if it does not answer your question. Thx!

**Comment by fonzmeister** [comment]
Thank you, that works perfectly.
However, I don't think it works on poloniex though

for example:
```polo.fetchCurrencies()['STEEM']```

gives as output: 
```{'name': 'STEEM', 'active': True, 'fee': 0.01, 'info': {'disabled': 1, 'name': 'STEEM', 'txFee': '0.01000000', 'frozen': 0, 'delisted': 0, 'minConf': 50, 'depositAddress': 'poloniex', 'id': 281}, 'code': 'STEEM', 'id': 'STEEM', 'limits': {'withdraw': {'max': 100000000.0, 'min': '0.01000000'}, 'price': {'max': 100000000.0, 'min': 1e-08}, 'amount': {'max': 100000000.0, 'min': 1e-08}, 'cost': {'max': None, 'min': None}}, 'precision': 8}```

The wallet is disabled as is shown in the info part of the dict. however. Active is True

**Comment by kroitor** [comment]
@fonzmeister thx for pointing that out, will fix Poloniex as well, shortly.
