### ISSUE TITLE
PHP Error Handling

### ISSUE THREAD

**Issue by Umbralith** [ccxt/ccxt#3208]
I can't seem to pull the error message. I've read through the manual and examples, but nothing seems to work. I'm using PHP and I've updated ccxt to the newest version

**Comment by Umbralith** [comment]
I've tried

```catch (Exception $e) {
      $message = $e->message;
      $message = $e['message'];
      $message = $e->getMessage();
    }```

and none of them give me output

**Comment by kroitor** [comment]
See the example here:

- https://github.com/ccxt/ccxt/blob/master/examples/php/basic-error-handling.php

The above example is launched like so (in the CCXT folder):

```sh
php -f examples/php/basic-error-handling.php
```

See also: 
- https://github.com/ccxt/ccxt/tree/master/examples/php
- https://github.com/ccxt/ccxt/tree/master/examples



```PHP
<?php

$root = dirname (dirname (dirname (__FILE__)));

include $root . '/ccxt.php';

date_default_timezone_set ('UTC');

$exchange = new \ccxt\bittrex ();

$message = null;

try {

    $result = $exchange->fetch_ticker ('NONEXISTENT_SYMBOL');
    var_dump ($result);

} catch (Exception $e) {

    // print it
    echo $e->getMessage () . "\n";

    // save to $message (for whatever needs)
    $message = $e->getMessage ();
}

?>
```

Hope this answers your question.

**Comment by Umbralith** [comment]
When I do 

```
$e->getMessage()

```
I get

```
kucoin {"success":false,"code":"NO_BALANCE","msg":"Insufficient balance: BTC","timestamp":1529591993018,"data":{"coinType":"BTC","expect":1,"actual":0.00439439}}

```
How do I get the msg from that? Every attempt results in null

**Comment by Umbralith** [comment]
Thank you so much. Kinda new to PHP as well, so I'm sure that's not helping me either
