### ISSUE TITLE
New Exchange: Coinbase Pro

### ISSUE THREAD

**Issue by hbeckeri** [ccxt/ccxt#3210]
Are there any plans to add support for coinbase pro? I believe the api is exactly the same as GDAX except that the endpoint is now `api.pro.coinbase.com` instead of `api.gdax.com`. The GDAX api won't go down til December 31st 2018. I'd be willing to make a PR

**Comment by kroitor** [comment]
> Are there any plans to add support for coinbase pro?

Yep.

> I believe the api is exactly the same as GDAX except that the endpoint is not api.pro.coinbase.com instead of api.gdax.com. 

If that is the case, then adding it is just a matter of copying a template from another existing derived exchange and editing a few urls indeed. 

> I'd be willing to make a PR

That would be awesome! Just make sure to read this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

An example of an exchange who's interface is derived from another exchange is here: 

https://github.com/ccxt/ccxt/blob/master/js/quoinex.js (Quoinex derived from Qryptos)

**Comment by kroitor** [comment]
Related: #466

**Comment by hbeckeri** [comment]
Rad, ill start working on this
