### ISSUE TITLE
mean execution price

### ISSUE THREAD

**Issue by rspadim** [ccxt/ccxt#3211]
hi guys, what's the api method to get the execution price of an order

for example, market is selling at 10000
i send a buy order at 11000, what the mean price of my executed volume? for example 10121 ?
i`m using fetch_order() method

**Comment by kroitor** [comment]
```JavaScript
order = await exchange.fetch_order (orderId)
if (typeof order['filled'] !== 'undefined' && order['filled'] > 0)
    price = order['price']  // this should be the filling price if order['filled'] > 0
```

Hope this answers your question.
