### ISSUE TITLE
Symbols are not unified?

### ISSUE THREAD

**Issue by guimwill** [ccxt/ccxt#3212]
OS: Windows
Programming Language version: Python/JS
CCXT version: 1.14.230
Exchange: Kraken, Bitstamp

The manual says the symbols are unified, but I realized some differences between the exchanges.

Example: for the symbol "BTC/USDT", some exchanges like Kraken and Bitstamp have the symbol  "BTC/USD", and others like Bitfinex and Binance have "BTC/USDT. Is There a way to Unified these symbols?

Thanks.

**Comment by kroitor** [comment]
- this is a work in progress
- https://github.com/ccxt/ccxt/issues/182#issuecomment-327997331
- https://github.com/ccxt/ccxt/issues/2851
- https://github.com/ccxt/ccxt/issues/1083

> for the symbol "BTC/USDT", some exchanges like Kraken and Bitstamp have the symbol "BTC/USD"

Kraken has a "USDT/USD" market, does it tell you anything? ) USDT isn't the same as USD.

Hope this answers your question.

**Comment by guimwill** [comment]
@kroitor thats true, my mistake.

Thanks again.
