### ISSUE TITLE
GDAX Migration to Coinbase Pro

### ISSUE THREAD

**Issue by oppure** [ccxt/ccxt#3216]
- Exchange: GDAX

gdax users have recently received an email advising that:
"On Friday June 29, we say goodbye to GDAX and hello to Coinbase Pro
....
There will be no disruption to the gdax.com API during this time. GDAX APIs will continue to function until December 31, 2018.
    We encourage Coinbase Pro users to begin migrating their API usage away from api.gdax.com to api.pro.coinbase.com."

In view of this change urls should be updated and probably some files, classes, variables renamed?

**Comment by kroitor** [comment]
@oppure you're a bit late, coinbase pro was added just about an hour ago... sorry )

Duplicate:
- https://github.com/ccxt/ccxt/pull/3214
- https://github.com/ccxt/ccxt/issues/3210

**Comment by oppure** [comment]
Good!
