### ISSUE TITLE
Coinbase fetchOHLCV and fetchMyTrades

### ISSUE THREAD

**Issue by Stas-Buzunko** [ccxt/ccxt#3217]
I need these 2 methods and I'm ready to try to help with their implementation.

1) Is there any work currently being done on any of them so that I/you don't waste our time?
2) If not, which one is easier to implement first?

I can only implement in js, is it ok?

**Comment by kroitor** [comment]
> Is there any work currently being done on any of them so that I/you don't waste our time?

Can't tell for everybody, but I'm currently not implementing fetchOHLCV / fetchMyTrades for Coinbase.

> If not, which one is easier to implement first?

Both require one fetch method (`fetchOHLCV` / `fetchTrades`) + one parse method (`parseOHLCV` or `parseTrade`), so implementing either of them should be quite straightforward and easy.


> I can only implement in js, is it ok?

Yep. Just make sure to read this doc very carefully: 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

**Comment by Stas-Buzunko** [comment]
@kroitor 
I've got a few questions, actually, it would be easier to ask on telegram or something like this.

1) I don't see ANY way to get a historical price from coinbase, I see it's possible on gdax (https://docs.gdax.com/#get-historic-rates), but don't see any info about coinbase, do you have any info whether it's possible?

2) speaking of fetchMyTrades, I see that they have 2 methods instead of 1 sells and buys. So, I guess I fetch both for each accountId and combine them. But there is a new problem appears, turns out it's possible that API key can have only one read scope from sells/buys, which means we can fetch only one side which is useless. What to return in this case?

**Comment by kroitor** [comment]
> I don't see ANY way to get a historical price from coinbase, I see it's possible on gdax (https://docs.gdax.com/#get-historic-rates), but don't see any info about coinbase, do you have any info whether it's possible?

I'm afraid, they don't have it. The only practical way to store historical data from Coinbase is to just poll continuously and aggregate into your local db for later processing (this is beyond the scope of this library).

> peaking of fetchMyTrades, I see that they have 2 methods instead of 1 sells and buys. So, I guess I fetch both for each accountId and combine them. But there is a new problem appears, turns out it's possible that API key can have only one read scope from sells/buys, which means we can fetch only one side which is useless. 

Well, it isn't necessarily useless. However, I'd make this optional anyways.

> What to return in this case?

If `this.options['fetchMyTrades']['buy'] == true`, fetch the buys, if `this.options['fetchMyTrades['sell']` == true` then fetch the sells. If both are true (they should be, by default), then fetch both. If the apiKey does not permit access to either buy or sell and both of them are true – then throw a `PermissionDenied` exception (if necessary).

**Comment by Stas-Buzunko** [comment]
@kroitor could you please show me how I can extend coinbase class locally to have my custom fetchOHLCV method to fetch from another service?

I'd like to keep the syntax look the same.

**Comment by kroitor** [comment]
There's more than 3 ways to do this in JS:

1.

```JavaScript

// overwriting the method in the prototype

ccxt.coinbase.prototype.fetchOHLCV = async function (symbol = undefined, timeframe = '1m', since = undefined, limit = undefined, params = {}) {

    // your custom method to fetch from another service

}

const coinbase = new ccxt.coinbase (/* ... your options ... */)
```

2. 

```JavaScript

// inheriting your own class from ccxt base class and overriding the inherited method

class MyCoinbase extends ccxt.coinbase {
    async fetchOHLCV (symbol = undefined, timeframe = '1m', since = undefined, limit = undefined, params = {}) {

        // your custom method to fetch from another service

    }
}
```

3.

```JavaScript

// overwriting the method just for one particular instance, leaving the coinbase class itself as is

const coinbase = new ccxt.coinbase (/* ... your options ... */)

coinbase.fetchOHLCV = (async function (symbol = undefined, timeframe = '1m', since = undefined, limit = undefined, params = {}) {
    
    // your custom method to fetch from another service

}).bind (coinbase)

```

4. ...

**Comment by Stas-Buzunko** [comment]
@kroitor thanks! :)
