### ISSUE TITLE
Huobipro "orderamount-precision-error" on cross-pairs

### ISSUE THREAD

**Issue by Cleric334** [ccxt/ccxt#3218]
Hello.

Huobipro returns this error message when trying to market buy cross-pairs (non-USDT, like ETH/BTC)

"order amount precision error, scale : '4' "

Same order parameters work just fine on USDT pairs.

What can be the case here?

Thanks in advance.

**Comment by kroitor** [comment]
> What can be the case here?

Could be anything. Without **your code** and **your verbose request and response** it's really hard to tell at this point: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue.

**Comment by kroitor** [comment]
I'm closing this if you don't mind until we have a follow up on the issue with a verbose report. Feel free to reopen it if needed. Thx!!
