### ISSUE TITLE
Cryptopia not returning any open orders

### ISSUE THREAD

**Issue by procloud** [ccxt/ccxt#3223]
- OS:
ubuntu 18.04
- Programming Language version:
php
- CCXT version:
1.14.254
- Exchange:
cryptopia
- Method:
->fetchOpenOrders() or ->fetchOpenOrders($pair)

when i turn verbose on, i can see the json data, but a blank array is returned from the call

**Comment by kroitor** [comment]
@procloud please read the manual very carefully, as it is all documented there:

- https://github.com/ccxt/ccxt/wiki/Manual#querying-orders 
- https://github.com/ccxt/ccxt/wiki/Manual#orders-cache
- https://github.com/ccxt/ccxt/wiki/Manual

**Comment by kroitor** [comment]
P.S. If the above info does not solve your question and you still think it's a problem in the lib, then, plz, **post your code to reproduce the issue and your verbose request / response**, precisely as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
