### ISSUE TITLE
Gemini new transfers endpoint

### ISSUE THREAD

**Issue by TotallyKyle** [ccxt/ccxt#3224]
There is an endpoint offered by Gemini that isn't in the definition:

https://docs.gemini.com/rest-api/#transfers
POST https://api.gemini.com/v1/transfers

This returns a history of all of your deposits and withdraws.

To add this to the implicit api methods, do we just have to change here?:

'private': {
                    'post': [
                        'order/new',
                        'order/cancel',
                        'order/cancel/session',
                        'order/cancel/all',
                        'order/status',
                        'orders',
                        'mytrades',
                        'tradevolume',
                        'balances',
                        'deposit/{currency}/newAddress',
                        'withdraw/{currency}',
                        'heartbeat',
                        _'transfers'_
                    ],
                },

**Comment by kroitor** [comment]
> To add this to the implicit api methods, do we just have to change here?:

Yep. 

Already added it. Thx for pointing that out.
