### ISSUE TITLE
TypeError: unsupported operand type(s) for - : 'NonType' and 'float'

### ISSUE THREAD

**Issue by pebble8888** [ccxt/ccxt#3227]
"ccxt/bitmex.py" line 281, in fetch_orders
return self.parse_orders(response, market, since, limit)
"ccxt/base/exchange.py", line 1197, in parse_orders
array = [self.parse_order(order, market) for order in array]
"ccxt/baseexchange.py", line 1197, in <listcomp>
array - [eslf.parse_order(order, market) for order in array]
"ccxt/bitmex.py", line 438, in parse_order
remaining = max(amount - fille, 0.0)
TypeError: unsupported operand type(s) for - : 'NonType' and 'float'

- OS:
ubuntu 18.04
- Programming Language version:
python3.6
- CCXT version:
1.14.254
- Exchange:
bitmex (testnet)
- Method:
fetch_orders

**Comment by pebble8888** [comment]
@kroitor 

Your fix seems like javascript.
How about python3 ?

**Comment by kroitor** [comment]
@pebble8888 it is generated automatically, thus fixed in python as well, more about it here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

So, the most recent version of it from PIP has a fix in it already and I don't need to fix all languages one by one.

**Comment by pebble8888** [comment]
@kroitor
I got it. Thank you.
