### ISSUE TITLE
hitbtc.fetchMyTrades      NotSupported    fetch_my_trades() is not implemented yet'

### ISSUE THREAD

**Issue by Mantas779** [ccxt/ccxt#3232]
- OS: Win 10
- Programming Language version: Python 3.4
- CCXT version: 1.14.257
- Exchange: HitBTC
- Method: fetchMyTrades

AltCoinTrades = hitbtc.fetchMyTrades(AltCoin) 
 self.raise_error(NotSupported, details='fetch_my_trades() is not implemented yet')

openorder = hitbtc.fetchOpenOrders('ARDR/BTC')
print(openorder)        works fine 

btc = hitbtc.fetchBalance()['BTC']['free']
print('Free BTC To Trade', btc)                        also works fine 

I have i full version working on Poloniex and Cryptopia

Or is HitBTC  not yet fully usable?

**Comment by kroitor** [comment]
@Mantas779 their v1 API is outdated, just use `hitbtc2` instead of `hitbtc` and you should be ok ) Let us know if it does not answer your question. Thx!

**Comment by SteCrypto** [comment]
Hi Kroitor
sorry for the silly question, how can I use the new hitbtc API?

I tried hitbtc3.fetch_ticker(CryptoPair) and hitbtc2.fetch_ticker(CryptoPair) but it's not working

Thanks
