### ISSUE TITLE
Bittrex: Not Available

### ISSUE THREAD

**Issue by morzyns** [ccxt/ccxt#3240]
For few days i get this error while trying to get balance.
My Location: London/UK

> Exchange Not Available Error] bittrex GET https://bittrex.com/api/currencies 404 Error: 404 not accessible from this location at the moment

- OS: Mac
- Programming Language version: JS
- CCXT version: 1.14.205
- Exchange: Bittrex
- Method: GetBalance

**Comment by kroitor** [comment]
@morzyns need **your code to reproduce the issue** and **your verbose request and response**: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ...

**Comment by kroitor** [comment]
Closing this for now, if you don't mind, until we have a follow up on this. Feel free to reopen it or just ask further questions, if any. Thx!
