### ISSUE TITLE
Binance v3 => GET /api/v3/allOrders returns no price value for the order with type MARKET

### ISSUE THREAD

**Issue by raman424** [ccxt/ccxt#3241]
Hi,

I am trying to get the list of all orders using api GET /api/v3/allOrders. I usually get the list of orders from Binance exchange. It gives me the correct information for order type limit but for order type MARKET, I am getting one of the following objects which returns no price and no final amount (which can be used for reverse calculate the price).

{"symbol":"ETHUSDT","orderId":orderId,"clientOrderId":"soMEclIENTid","price":"0.00000000","origQty":"0.56000000","executedQty":"0.56000000","status":"FILLED","timeInForce":"GTC","type":"MARKET","side":"BUY","stopPrice":"0.00000000","icebergQty":"0.00000000","time":1529412245382,"isWorking":true}

Any suggestions how to get the price for all the orders of market type.

**Comment by kroitor** [comment]
Duplicate:

- https://github.com/ccxt/ccxt/issues/2019
- https://github.com/ccxt/ccxt/issues/2714
- https://github.com/ccxt/ccxt/issues/1011
