### ISSUE TITLE
New Exchange: CoinBig

### ISSUE THREAD

**Issue by xiangzz159** [ccxt/ccxt#3242]
web: https://www.coinbig.com/index.html

doc: https://github.com/489405826/coinbigapi/wiki/API%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3

https://github.com/xiangzz159/ccxt/blob/master/python/ccxt/coinbig.py

**Comment by kroitor** [comment]
The exchange is inaccessible.
