### ISSUE TITLE
Failed when install using 'pip install git+https://....'

### ISSUE THREAD

**Issue by futurehome** [ccxt/ccxt#3243]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Win7
- Programming Language version: Python 3
- CCXT version: Latest
- Exchange: 
- Method:

When I try to install CCXT using the following command, it always failed with error code 128,  can you please help to figure it out? Thanks.

pip install --upgrade git+https://github.com/ccxt/ccxt.git@master

**Collecting git+https://github.com/ccxt/ccxt.git@master
  Cloning https://github.com/ccxt/ccxt.git (to revision master) to c:\users\wangb2\appdata\local\temp\2\pip-req-build-ch9wo1ix
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Command "git clone -q https://github.com/ccxt/ccxt.git C:\Users\wangb2\AppData\Local\Temp\2\pip-req-build-ch9wo1ix" failed with error code 128 in None**

**Comment by kroitor** [comment]
@futurehome why not just `pip install ccxt` and `pip install --upgrade ccxt` ?

**Comment by futurehome** [comment]
I found sometimes the version in Pypi is older than in github, so I want to use this way to get the latest version quickly.

**Comment by kroitor** [comment]
@futurehome max difference between github and pypi is about 10 minutes. That is the amount of time needed for the new version to propagate everywhere. So, if you don't see it in PyPI yet, you can just retry once again and it should appear there in very short time. Basically, this is all synchronized automatically, so, you don't have to worry about it, just use the pip version and you'll be ok. Does this help?

**Comment by futurehome** [comment]
It's good to hear that, it really helps. Thanks for the responsive feedback.

**Comment by futurehome** [comment]
One other question is what's the reason for not supporting this method? I just want to understand why some repo can install in this way.

**Comment by kroitor** [comment]
@futurehome i'll check for that, however, I guess, this is related to your local configuration. Will test anyways, thx for pointing that out.

**Comment by futurehome** [comment]
But I can install other repo using this way on my computer.

**Comment by kroitor** [comment]
Does updating the pip itself resolve the issue?

```
pip install --upgrade pip
```

After that, it should work fine. Let us know if it does not help.

https://www.google.ru/search?q=pip+install+git+clone+failed+with+error+code+128+in+None

**Comment by futurehome** [comment]
I'm using pip 10.0.1, the error output shows below:

_

> pip install git+https://github.com/ccxt/ccxt.git@master
> 
> Collecting git+https://github.com/ccxt/ccxt.git@master
>   Cloning https://github.com/ccxt/ccxt.git (to revision master) to c:\users\wangb2\appdata\local\temp\2\pip-req-build-gfgc1buo
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "d:\continuum\anaconda3\lib\tokenize.py", line 452, in open
>         buffer = _builtin_open(filename, 'rb')
>     FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\wangb2\\AppData\\Local\\Temp\\2\\pip-req-build-gfgc1buo\\setup.py'

_

I found one thread for same issue in the link below, hope it may help.
https://github.com/pypa/pip/issues/5358

**Comment by kroitor** [comment]
@futurehome the thing is, Anaconda python uses its own pip... This might help resolving the issue as well: https://github.com/ccxt/ccxt/issues/2824#issuecomment-388647914

**Comment by futurehome** [comment]
Anyway, I'll use 'pip install ccxt' directly. Thanks.
