### ISSUE TITLE
 TypeError: object of type 'NoneType' has no len()TypeErr

### ISSUE THREAD

**Issue by araa47** [ccxt/ccxt#3244]
In trying to load markets in python3.6.3, once in a while, my program detects an error in the following function. I have only gotten this issue once every 5 days. 

market = await exchange.load_markets(reload=True)

My program currently loads the markets under all exchanges in ccxt to keep track of all the coins. 

I think it should be handled as ccxt.ExchangeError

![typeerror](https://user-images.githubusercontent.com/22760261/41857246-a07c96f2-78c9-11e8-9de6-e69cbc84e48b.png)

**Comment by kroitor** [comment]
I'd move this discussion to #3245 if you don't mind, as these might be related.
