### ISSUE TITLE
JSONDecodeError: Unterminated string starting at: line 1 column 1436 (char 1435)

### ISSUE THREAD

**Issue by araa47** [ccxt/ccxt#3245]
In trying to load markets in python3.6.3, my program detects an error in the following function. I have only managed to capture this issue once. 

market = await exchange.load_markets(reload=True)

My program currently loads the markets under all exchanges in ccxt to keep track of all the coins.

I think it should be handled as ccxt.ExchangeError

![jsondecodeerror](https://user-images.githubusercontent.com/22760261/41857643-973e3a40-78ca-11e8-8eb6-91aea2869701.png)

**Comment by araa47** [comment]
Found another similar issue I have managed to capture 9 times. 

![screen shot 2018-06-25 at 10 55 48 pm](https://user-images.githubusercontent.com/22760261/41857842-fa2e2318-78ca-11e8-8604-a624df371862.png)

**Comment by kroitor** [comment]
@araa47 unfortunately, those images don't help to help you. Can you please paste your **code to reproduce the issue** + your **verbose request and response** (in text), precisely as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

**Comment by araa47** [comment]
@kroitor , yep I'm trying to capture the verbose issues but haven't managed to stumble upon it yet. Will upload the code and verbose output as soon as I can recreate it again.

**Comment by araa47** [comment]
@kroitor , is the above information enough to re-open the issue?

**Comment by kroitor** [comment]
@araa47 it's up to you whether you want to reopen it or not, I'm working on the fix anyway, will upload asap.

**Comment by araa47** [comment]
@kroitor , will just keep it closed then, just wanted to make sure you had enough information

**Comment by kroitor** [comment]
@araa47 what's your version of ccxt btw?

**Comment by araa47** [comment]
ccxt = "==1.14.52"

**Comment by kroitor** [comment]
@araa47 can you verify it with the following script:

```Python
import ccxt
print(ccxt.__version__)
```

sorry for asking this, just need to make sure. Just to let you know, throwing an ExchangeError on JsonDecodeError exception should've worked, because we have code to intercept it... If it does not throw an ExchangeError, this might indicate an outdated package version.

**Comment by araa47** [comment]
```
bash-3.2$ python3 app.py 
1.14.52
```

**Comment by kroitor** [comment]
Let us know if you still have difficulties with the most recent version 1.18.300+. Thx!
