### ISSUE TITLE
Binance Error 1022

### ISSUE THREAD

**Issue by Larz321** [ccxt/ccxt#3246]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: windows 8
- Programming Language version: node.js
- CCXT version: 1.14.267
- Exchange: Binance
- Method: FetchBalance

Code:``` let binance = new ccxt.binance({
      'apiKey': RegularKey,
      'secret': SecretKey,
       'verbose': true ,
       'adjustForTimeDifference': true
    })
   
    let binanceBalance = await binance.fetchBalance ({'recvWindow': 10000000})```

Error: ``` fetch:
 binance GET https://api.binance.com/api/v3/account?timestamp=1529945260039&recv
Window=10000000&signature=95eb0b059fae755d21263286146689e4e9cb1fbcbe74ea8a96628b
de402141d5
Request:
 { 'X-MBX-APIKEY': 'i deleted this ' }
 undefined

handleRestResponse:
 binance GET https://api.binance.com/api/v3/account?timestamp=1529945260039&recv
Window=10000000&signature=95eb0b059fae755d21263286146689e4e9cb1fbcbe74ea8a96628b
de402141d5 400 Bad Request
Response:
 { 'Content-Type': 'application/json',
  'Transfer-Encoding': 'chunked',
  Connection: 'close',
  Date: 'Mon, 25 Jun 2018 16:47:41 GMT',
  Server: 'nginx',
  'Strict-Transport-Security': 'max-age=31536000; includeSubdomains',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Xss-Protection': '1; mode=block',
  'X-Content-Type-Options': 'nosniff',
  'Content-Security-Policy': 'default-src \'self\'',
  'X-Content-Security-Policy': 'default-src \'self\'',
  'X-Webkit-Csp': 'default-src \'self\'',
  'Cache-Control': 'no-cache, no-store, must-revalidate',
  Pragma: 'no-cache',
  Expires: '0',
  'X-Cache': 'Error from cloudfront',
  Via: '1.1 8c1b1d3bc72fa37d10089ae804d74c7e.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': '8Q1bE_k8T4PNXqjMj9kOedhuAw5HxuEIS4toQhYLeu7x2XMnr230tw==' }
 {"code":-1022,"msg":"Signature for this request is not valid."}

{ Error: binance: unknown error code: {"code":-1022,"msg":"Signature for this re
quest is not valid."} -1022```

I have read many issue solutions on the site and read through the manual and troubleshooting section, nothing seems to be working for me.

Thank you so much.

**Comment by kroitor** [comment]
@Larz321 let's start with something basic:

```JavaScript
const ccxt = require ('ccxt')

let binance = new ccxt.binance({
    'apiKey': RegularKey,
    'secret': SecretKey,
})

;(async () => {
    let binanceBalance = await binance.fetchBalance ()
    console.log (binanceBalance);
}) ()
```

↑ Does this work?

**Comment by Larz321** [comment]
Thank you for the quick response. Same error, I already deleted and renewed my keys multiple times.

Here is the error: 
``` handleRestResponse:
 binance GET https://api.binance.com/api/v3/account?timestamp=1529945260039&recv
Window=10000000&signature=95eb0b059fae755d21263286146689e4e9cb1fbcbe74ea8a96628b
de402141d5 400 Bad Request
Response:
 { 'Content-Type': 'application/json',
  'Transfer-Encoding': 'chunked',
  Connection: 'close',
  Date: 'Mon, 25 Jun 2018 16:47:41 GMT',
  Server: 'nginx',
  'Strict-Transport-Security': 'max-age=31536000; includeSubdomains',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Xss-Protection': '1; mode=block',
  'X-Content-Type-Options': 'nosniff',
  'Content-Security-Policy': 'default-src \'self\'',
  'X-Content-Security-Policy': 'default-src \'self\'',
  'X-Webkit-Csp': 'default-src \'self\'',
  'Cache-Control': 'no-cache, no-store, must-revalidate',
  Pragma: 'no-cache',
  Expires: '0',
  'X-Cache': 'Error from cloudfront',
  Via: '1.1 8c1b1d3bc72fa37d10089ae804d74c7e.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': '8Q1bE_k8T4PNXqjMj9kOedhuAw5HxuEIS4toQhYLeu7x2XMnr230tw==' }
 {"code":-1022,"msg":"Signature for this request is not valid."}

{ Error: binance: unknown error code: {"code":-1022,"msg":"Signature for this re
quest is not valid."} -1022```

I already had async in the first line just forgot to add it to the issue documentation. ``` async index (RegularKey, SecretKey) {
const ccxt = require ('ccxt')
try{
let binance = new ccxt.binance({
    'apiKey': RegularKey,
    'secret': SecretKey,
    'adjustForTimeDifference':true
})

;(async () => {
    let binanceBalance = await binance.fetchBalance ()
    console.log (binanceBalance);
}) ()
  }```

Thank you.

**Comment by kroitor** [comment]
@Larz321 then we will need to make sure that your system clock is in synch with the rest of the world. Unfortunately, this cannot be done just by enabling the internet time synch checkbox in system clock windows settings... Most often you have to reboot after that, and it also has to be supplemented with a tweak to the registry: https://www.thewindowsclub.com/change-internet-time-update-interval-windows. You need to make sure that your system clock is synched once in 10 minutes or less, otherwise the system won't synch it too often. Let me know if it does not help.

**Comment by Larz321** [comment]
would it work then if i did it on a server like heroku?

**Comment by kroitor** [comment]
> would it work then if i did it on a server like heroku?

Nope. I think, for some reason your clock is 1 hour behind the UTC time and minutes are out of sync... I guess, a time sync for your system is what you need. Another common pitfall is misplacing apiKey with secret and vice versa.

Related: 

- https://github.com/ccxt/ccxt/issues/850
- https://github.com/ccxt/ccxt/issues/936

Is your system clock synced at all?

**Comment by kroitor** [comment]
@Larz321 

> binance GET https://api.binance.com/api/v3/account?timestamp=1529945260039&recv
Window=10000000&signature=95eb0b059fae755d21263286146689e4e9cb1fbcbe74ea8a96628b
de402141d5 400 Bad Request

Looks like you're still overriding the `recvWindow` somewhere and the output you posted is not from the snippet that I've replied with, above. Namely, the `recvWindow` should be 5000 by default, whereas in your output it is 10000000. See the `fetchBalance()` call in my example, I'm not sending any extra params with it.

**Comment by Larz321** [comment]
I set up the timesync and restarted it is working now. I will keep track if that changes. Thank you for your VERY quick support.

**Comment by kroitor** [comment]
@Larz321 thx for the feedback! Feel free to reopen this if needed or just ask questions if you have any.

**Comment by mortezae** [comment]
Hi, I have the same problem...
Also I synced my time but no difference.
Code:
```javascript
var exchange = new ccxt.binance(settings['binance'])
async function test () {
  await exchange.loadMarkets () 
  console.log (await exchange.fetchBalance ())
}
test ()
```
Output:
```
(node:11324) UnhandledPromiseRejectionWarning: Error: binance: unknown error code: {"code":-1022,"msg":"Signature for this request is not valid."} -1022
    at binance.handleErrors (/home/morteza/.nvm/versions/node/v9.3.0/lib/node_modules/ccxt/js/binance.js:870:31)
    at response.text.then (/home/morteza/.nvm/versions/node/v9.3.0/lib/node_modules/ccxt/js/base/Exchange.js:513:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:11324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kroitor** [comment]
@mortezae you need to update ccxt and make sure that you have rate limiting enabled and your time is in sync with the rest of the world (in UTC). Read the posts linked above, all answered there.

**Comment by mortezae** [comment]
@kroitor Sorry I deleted my comment as it was occured by some other problem. My fault! Thank you man.
