### ISSUE TITLE
Bit-Z DDoSProtection: Request too often

### ISSUE THREAD

**Issue by interenet** [ccxt/ccxt#3248]
I get error "ccxt.base.errors.DDoSProtection: Request too often" with " 'enableRateLimit': True" after Bit-Z API upgrade. Please correct. Thanks.

**Comment by kroitor** [comment]
@interenet have you tried setting a lower rateLimit?

**Comment by interenet** [comment]
No, I dont set on milluseconds
Only default paremetres

**Comment by kroitor** [comment]
@interenet can you show the shortest possible but a complete snippet (10-20) of code to reproduce it? What's your programming language?

**Comment by kroitor** [comment]
@interenet it would really help if you could read this carefully: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue and follow the steps from there precisely.

**Comment by interenet** [comment]
Python3

`
# coding=utf-8

import ccxt
exchange = ccxt.bitz({
    'apiKey': 'XXXXXXXXXXXXX',
    'secret': 'YYYYYYYYYYYYY',
    'enableRateLimit': True,
    'password': 'ZZZZZZZZZZZZ'
})
moneta = 'ETH'
exchangeMarkets = exchange.loadMarkets()
myorders = exchange.fetch_open_orders(moneta+'/BTC')
print(myorders)
for item in myorders:
    try: 
        print(item['id'])
 #       exchange.cancel_order(item['id'], moneta+'/BTC')
        print('1')
    except Exception:
        print('!')
        continue
exchangeBalance = exchange.fetch_balance()
stakan = exchange.fetch_order_book(moneta+'/BTC')
print(stakan['bids'][0])
print(stakan['asks'][0])

while True:
    exchangeBalance = exchange.fetch_balance()
    myorders = exchange.fetch_open_orders(moneta+'/BTC')
    stakan = exchange.fetch_order_book(moneta+'/BTC')
    print('!!!')

`

**Comment by kroitor** [comment]
You can resolve it in two ways:

```Python
# coding=utf-8

import ccxt
exchange = ccxt.bitz({
    'apiKey': 'XXXXXXXXXXXXX',
    'secret': 'YYYYYYYYYYYYY',
    'enableRateLimit': True,
    'password': 'ZZZZZZZZZZZZ',

    # ---------------------------------------------------------------------------------
    'rateLimit': 2000,  # ←---------------------------------- ADD THIS
    # ---------------------------------------------------------------------------------

})
moneta = 'ETH'
exchangeMarkets = exchange.loadMarkets()
myorders = exchange.fetch_open_orders(moneta+'/BTC')
print(myorders)
for item in myorders:
    try: 
        print(item['id'])
 #       exchange.cancel_order(item['id'], moneta+'/BTC')
        print('1')
    except Exception:
        print('!')
        continue
exchangeBalance = exchange.fetch_balance()
stakan = exchange.fetch_order_book(moneta+'/BTC')
print(stakan['bids'][0])
print(stakan['asks'][0])

while True:
    exchangeBalance = exchange.fetch_balance()
    myorders = exchange.fetch_open_orders(moneta+'/BTC')
    stakan = exchange.fetch_order_book(moneta+'/BTC')
    print('!!!')
```

... or wait 5-10 minutes until the new version build 1.14.269 arrives and just update ccxt without changing your code. If it does not help, try setting a higher rateLimit value (3000, 4000 and so on) and  let us know if the problem persists. Thx!

**Comment by interenet** [comment]
Updated

build 1.14.269

Working. Thank you

**Comment by SavostinVladimir** [comment]
Could anybody say actual rate limit in msecs for bitZ??

**Comment by kroitor** [comment]
@SavostinVladimir since their private signing timestamp is in seconds, you can't really use it much more frequently than that, unless you don't use the private API at all and only call it for public market data. Unfortunately their rate-limits are not documented in their docs...
