### ISSUE TITLE
Instantiating an exchange in PHP by exchange name variable

### ISSUE THREAD

**Issue by presence35** [ccxt/ccxt#3260]
In PHP how come this isn't working as expected?

```
$name = "binance"
$exchange = new \ccxt\{$name}();
```

**Comment by presence35** [comment]
Nope.  And I tried variations with the \\

PHP Parse error:  syntax error, unexpected ''\\ccxt\\binance'' (T_CONSTANT_ENCAPSED_STRING)

**Comment by kroitor** [comment]
@presence35 can you show your code with double slashes again? 

Here's my output from an interactive PHP session:

```PHP
mbp:ccxt igorkroitor$ php -a
Interactive shell

php > include_once ('ccxt.php');
php > $name = '\\ccxt\\binance';
php > $e = new $name ();
php > echo $e->id . "\n";
binance
php > echo PHP_VERSION . "\n";
7.1.7
```

**Comment by kroitor** [comment]
Does any of these examples work for you: https://github.com/ccxt/ccxt/tree/master/examples/php ?
For example, have you tried launching the `symbols.php` example with an exchange argument? Because it has code to instantiate the exchange from a variable name in it.

**Comment by presence35** [comment]
Nevermind, I got it working as above. Stupidness on my part.

Thank you :)

**Comment by kroitor** [comment]
@presence35 thx for reporting back! Cheers!
