### ISSUE TITLE
How to handle exceptions in Python?

### ISSUE THREAD

**Issue by dyphen12** [ccxt/ccxt#3262]
Hello! I have this code to load a OHLCV dataset from exchanges

def get_params(token, ex, timestep):
    while True:
        try:
            exc = ccxt.exchanges
            exchange = getattr(ccxt, ex)()
            exchange.load_markets()
            sym = exchange.markets.keys()
            if exchange.has['fetchOHLCV']:
                ohlcv = exchange.fetch_ohlcv(token, timestep)
                break
            else:
                print('Does not have OHLCV API')
                break
        except (KeyError, Exception):
            print('Invalid input')
            print('Exchange examples: ', exc)
            print('Symbol examples: ', sym)
            break
    return ohlcv

The script runs well, but shows this 

Exception ignored in: <bound method binance.__del__ of <ccxt.binance.binance object at 0x7f99c96e5080>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/ccxt/base/exchange.py", line 237, in __del__
    self.session.close()
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 707, in close
    for v in self.adapters.values():
  File "/usr/lib/python3.4/_collections_abc.py", line 512, in __iter__
    for key in self._mapping:
  File "/usr/lib/python3.4/collections/__init__.py", line 91, in __iter__
    curr = root.next
ReferenceError: weakly-referenced object no longer exists

what could it be the problem? 

I'm a cryptoenthusiast and I apologize if I break some rules while posting this

- OS: Ubuntu 14.04
- Programming Language version: Python 3.4
- CCXT version: 1.10.1042
- Exchange: All
- Method: fetchOHLCV

**Comment by kroitor** [comment]
> what could it be the problem?

You're ignoring the exception:

> Exception ignored in: <bound method binance.del of <ccxt.binance.binance object at 0x7f99c96e5080>>

Sorry, but you really have to understand the very basic of python loops, error handling (google for tutorials on how to handle exceptions in Python, there's a ton of videos on youtube for that). It is all too generic and isn't related to the library itself, more related to the learning curve of learning the basics of Python programming. It isn't even possible to explain all this in a single Github issue. The library has a high entry threshold, you need to become very confident with Python (or JS or PHP) first if you want to use it efficiently.

Also, in your code you don't use any rate limiting, and you're completely ignoring the entire Manual and the guidelines on troubleshooting and debugging and the examples...

- https://github.com/ccxt/ccxt/wiki/Manual 
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/tree/master/examples/py
- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

The general recommendation in this case is to start reading around ) This isn't hard if you're a true enthusiast ) Read everything, not just what's in your focus, but also all the text around on your screen. If you read your screen carefully, then you will quickly notice the links to the docs and examples on how to do this or that. If you ever meet a coder who does not do the same – tell him to do so as well.

```Python
import ccxt

def get_ohlcv(exchange_id, symbol, timeframe):
    try:
        
        # instantiating one instance per each call IS A BAD DESIGN !

        exchange = getattr(ccxt, exchange_id)({
            'enableRateLimit': True,
        })
        
        if symbol not in exchange.markets:
            raise Exception(exchange.id + ' does not have symbol ' + symbol)
        
        if not exchange.has['fetchOHLCV']:
            raise Exception(exchange.id + ' does not support the fetchOHLCV method')
        
        return exchange.fetch_ohlcv(symbol, timeframe)

    except Exception as e:
        print(type(e).__name__, e.args)

```

Hope it answers your question. Will be happy to help on the library itself.
