### ISSUE TITLE
Setting API and Secret Key in PHP version havig no effect

### ISSUE THREAD

**Issue by DaveMG3** [ccxt/ccxt#3263]
Hi,
After creating account and keys for 1Broker, bitbox , coinspot and cointiger exchanges,  I followed the manual for setting these Api key and secret  but still receive the error message from API asking for API key.
For quick testing I set it like below...Is there a known issue on Php or i am missing something?

       $string_exchange = '\\ccxt\\' . $id;
        $ccxt_exchange = new $string_exchange();

        $exchangeAPI = new ExchangeAPIKey();
        $apiKey = $exchangeAPI->getApiKey($id);
        $secretKey = $exchangeAPI->getSecretKey($id);
        echo ' ApiKey '.$apiKey;
        echo ' SecretKey '.$secretKey;
        if(!empty($apiKey) && !empty($secretKey)){
            $ccxt_exchange->apiKey = $apiKey;
            $ccxt_exchange->secret = $secretKey;
        }else if(!empty($apiKey)){
            $ccxt_exchange->apiKey = $apiKey;
        }

Setting my keys this way seems having no effect on loadmarket call...or maybe i miss some sleep

- OS:
- Programming Language version:
- CCXT version: 1.44.211
- Method: loadmarket

**Comment by kroitor** [comment]
```PHP
$id = '_1broker';
$onebroker = '\\ccxt\\' . $id;
$exchange = new $onebroker ();
$exchange->apiKey = 'YOUR_API_KEY';
// $exchange->secret = 'YOUR_SECRET'; // _1broker requires apiKey only
$exchange->load_markets();
echo print_r ($exchange->symbols, true) . "\n";
```

↑ If this does work and your code does not, then the reason is in your code, not in the library...

**Comment by kroitor** [comment]
@DaveMG3 i'd close this for now, feel free to reopen this if needed, or just questions if any, or if you have further difficulties with it.

**Comment by DaveMG3** [comment]
Indeed i setup a test case, it works so the blame should be in my code. 
Issue is not coming from ccxt
