### ISSUE TITLE
Python code uses {} or [] as default parameters in most functions

### ISSUE THREAD

**Issue by graeme-hattan** [ccxt/ccxt#3265]
This is a fairly standard python gotcha. Basically the default value persists between calls, so if it is modified during the call, the modifications will persist. See https://stackoverflow.com/questions/26320899/why-is-the-empty-dictionary-a-dangerous-default-value-in-python

I did some searching through the code, in the vast majority of cases it is the `params` argument which defaults to an empty dictionary (1110 counts excluding the `async` directory).

Here are the cases where `params` gets modified. As far as I can see, most of these are actual bugs:
```
binance.py:645:            params = self.omit(params, 'test')
bitflyer.py:318:        params['child_order_state'] = 'ACTIVE'
bitflyer.py:322:        params['child_order_state'] = 'COMPLETED'
bitso.py:269:            params = self.extend(params, {
bitso.py:357:            params = self.extend(params, {
coinexchange.py:683:            params = self.urlencode(params)
ice3x.py:379:            params = self.urlencode(params)
itbit.py:163:        params = {
kucoin.py:788:            params = self.omit(params, 'type')
kucoin.py:814:            params = self.omit(params, 'type')
okcoinusd.py:426:        params = self.omit(params, 'cost')
okcoinusd.py:622:            params = self.omit(params, ['type', 'status'])
qryptos.py:379:            params = self.omit(params, 'status')
```
I only found a couple of cases where a variable other than `params` defaults to a dictionary:
```
base/exchange.py:198:    def __init__(self, config={}):
base/exchange.py:258:    def define_rest_api(self, api, method_name, options={}):
```
And a few cases of empty lists:
```
kraken.py:319:    def append_inactive_markets(self, result=[]):
livecoin.py:227:    def append_fiat_currencies(self, result=[]):
poloniex.py:527:    def parse_open_orders(self, orders, market, result=[]):
```

**Comment by kroitor** [comment]
`self.omit()` and `self.extend()` do the deep copying, so these lines are not bugs:

```
binance.py:645:            params = self.omit(params, 'test')
bitso.py:269:            params = self.extend(params, {
bitso.py:357:            params = self.extend(params, {
kucoin.py:788:            params = self.omit(params, 'type')
kucoin.py:814:            params = self.omit(params, 'type')
okcoinusd.py:426:        params = self.omit(params, 'cost')
okcoinusd.py:622:            params = self.omit(params, ['type', 'status'])
qryptos.py:379:            params = self.omit(params, 'status')
```

These may be bugs:

```
itbit.py:163:        params = {
bitflyer.py:318:        params['child_order_state'] = 'ACTIVE'
bitflyer.py:322:        params['child_order_state'] = 'COMPLETED'
coinexchange.py:683:            params = self.urlencode(params)
ice3x.py:379:            params = self.urlencode(params)
```

Will look into that and will add fixes where appropriate.

**Comment by kroitor** [comment]
`itbit.py:163` is not a but either, if you look closer at it: https://github.com/ccxt/ccxt/blob/master/python/ccxt/itbit.py#L163

**Comment by graeme-hattan** [comment]
Yes, right enough. I think the bitflyer ones are though.

Given the number of people contributing to this, is it better to put something in the transpiler to avoid this? It is an easy mistake to make, especially if you are not necessary thinking of the python code as you add to it.

**Comment by kroitor** [comment]
> Yes, right enough. I think the bitflyer ones are though.

FIxed them, the fixed build should be there in 5-10 minutes.

> Given the number of people contributing to this, is it better to put something in the transpiler to avoid this? It is an easy mistake to make, especially if you are not necessary thinking of the python code as you add to it.

You're absolutely right, totally agree on this, will consider adding some guards to the transpiler.

**Comment by graeme-hattan** [comment]
Wow that was quick!

Don't know if you checked the list ones already, but livecoin and poloniex are bugs. Kraken would be if part of the code wasn't commented out.

**Comment by kroitor** [comment]
> Don't know if you checked the list ones already, but livecoin and poloniex are bugs. Kraken would be if part of the code wasn't commented out.

Fixed them as well, the updated version coming shortly.
