### ISSUE TITLE
Can't figure out how to `createOrder` in okex

### ISSUE THREAD

**Issue by ChenLi0830** [ccxt/ccxt#3268]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: MacOS 10.13.4
- Programming Language version: Node v8.4.0
- CCXT version: 1.14.286
- Exchange: okex
- Method: createOrder

I've been using ccxt for multiple exchanges and it has been working as a charm. However, I can't seem to figure out how to use `createOrder` for futures in okex and keeps getting this error `{"result":false,"error_code":20007}`

Not sure if it's caused by an update in OKEX's [api](https://github.com/okcoin-okex/API-docs-OKEx.com/blob/master/API-For-Futures-EN/REST%20API%20for%20FUTURES.md). 

Here is what I've tried: 
```
await exchange.createOrder(symbol, 'market', 1, '0.1', '450')
await exchange.createOrder(symbol, 'market', 'buy', '0.1', '450')
await exchange.createOrder(symbol, 'limit', 'buy', 0.1, 450, {contract_type: 'quarter', match_price: 1, type: 1})
```

Error output
```
fetch:
 okex POST https://www.okex.com/api/v1/future_trade.do 
Request:

amount=0.1&api_key=188a96b3-ca47-4c6a-9ed3&contract_type=quarter&lever_rate=10&match_price=0&price=450&symbol=eth_usd&type=1&sign=FAF51120E3D394863E0BAC2A9C0003FB 
Exchange.js:452
handleRestResponse:
 okex POST https://www.okex.com/api/v1/future_trade.do 200 OK 
Response:
Exchange.js:563
Object {Date: "Tue, 26 Jun 2018 23:51:40 GMT", Content-Type: "application/json", Content-Length: "35", Connection: "close", Set-Cookie: "locale=en_US; Expires=Tue, 03-Jul-2018 23:51:40 GM…", …}
Exchange.js:563

 {"result":false,"error_code":20007} 
```

**Comment by ChenLi0830** [comment]
Never mind, got it working now
```
await exchange.createOrder(symbol, 'market', 1, '1', '435.0')
```

**Comment by kroitor** [comment]
@ChenLi0830 thx for reporting back!

**Comment by ChenLi0830** [comment]
Thank **you** for the awesome work!

**Comment by kroitor** [comment]
When you say

> i'm facing the same issue, how do i place the limit order?

do you mean that you get `{"result":false,"error_code":20007} ` ?

**Comment by saikatharryc** [comment]
@kroitor Sorry, my bad,
for this one:

> @ChenLi0830 & @kroitor
> i'm facing the same issue, how do i place the limit order?
> i'm trying like this:
> 
> ```
>    try {
>         let data;
> 
>         const curMar = await getCurrentMarket(platForm, symbol);  // gives {data:{ask:212,bid:212} ,symbol:"ETH/USDT"}
>         if (symbol === fromSymbol + '/' + toSymbol) {
>           try {
>             data = await name.createOrder(symbol, 'limit', 'sell', Number(amount), curMar.data.ask);
>           } catch (error) {
>             console.log(error);
>             data = await name.createOrder(symbol, 'limit', 'buy', Number(amount), curMar.data.ask);
>           }
> 
>           console.log('sell order placed', symbol, fromSymbol, toSymbol);
>         } else if (symbol === toSymbol + '/' + fromSymbol) {
>           try {
>             data = await name.createOrder(symbol, 'limit', 'buy', Number(amount), curMar.data.ask);
>           } catch (error) {
>             console.log(error);
>             data = await name.createOrder(symbol, 'limit', 'sell', Number(amount), curMar.data.ask);
>           }
> 
>           console.log('buy order placed', symbol, fromSymbol, toSymbol);
>         }
>         return data;
>       } catch (error) {
>         console.log(name.iso8601(Date.now()), error.constructor.name, error.message);
>         console.log(error.constructor.name);
>       }
> ```
 i'm getting error: `AuthenticationError .    "okex {"result":false,"error_code":10007}"`

but when i'm trying to do 
 `data = await name.createOrder(symbol, 'market', 'buy', Number(amount));`
getting `{"result":false,"error_code":20007}`

**Comment by kroitor** [comment]
> i'm getting error: AuthenticationError . "okex {"result":false,"error_code":10007}"

This is most likely related to the key pair. OKEX have recently added version 3 of their API. And old keys don't work with it. And new API keys don't work with the old v1 version. So, if you created that particular keypair recently, then it won't work with v1, unfortunately. We're working on the v3. More about it here: https://github.com/ccxt/ccxt/issues/4063#issuecomment-438168627

Let us know if that is not the case / does not answer the question.

**Comment by saikatharryc** [comment]
Noted, Thanks for letting me know.
