### ISSUE TITLE
BitZ : OHLCV candles dont have volume for selected timeframe but 24h volume

### ISSUE THREAD

**Issue by DaveMG3** [ccxt/ccxt#3271]
Hi @kroitor ,
Noticed that for exchange BitZ, the volume fetched with OHLCV 1h is a 24h volume as per screenshot : 
Call with Ccxt : 
![image](https://user-images.githubusercontent.com/32598581/41975698-b6dda2ee-7a1b-11e8-86f7-8019a3be391c.png)
Bitz browser api call : 
![image](https://user-images.githubusercontent.com/32598581/41975715-c4a1dca6-7a1b-11e8-9969-bdc7c3455239.png)
Bitz api description:
![image](https://user-images.githubusercontent.com/32598581/41975997-2aaf0db6-7a1c-11e8-8748-f9b2c12fb0bc.png)

- Programming Language version: PHP and Python
- CCXT version: 1.44.249
- Exchange:  BitZ
- Method:fetchOHLCV

**Comment by JimAmuro** [comment]
I didn't understand 'fetchOHLCVWarning' because there was no problem with response of kline api, hence I found this post. The last picture of OP is actually api for tickers instead of klines. So there is no problem...

**Comment by kroitor** [comment]
@JimAmuro will look into it once again.

**Comment by JimAmuro** [comment]
omg, you are so fast...
BTW, the real problem might be the 'limit' parameter, since it get the first <limit> klines, not the latest <limit> klines. Will work on my version and try to contribute.

**Comment by DaveMG3** [comment]
@JimAmuro , @kroitor sorry for late reply

I made people confused with last picture. 
At the time of writing what was interesting was the 1st picture with kline from ccxt for 1h timeframe : BTC/USDT Price 6000$, Volume 10000 => 60M$ in 1 hour (cannot be). 
It seems it was an issue from bitz api cause today, having not changed my code and ccxt version during my holidays, i got following :
 Price 7000$, Volume 200 => 1.4M$ 
![image](https://user-images.githubusercontent.com/32598581/43641046-772ca856-9722-11e8-9f30-b35e72ac6236.png)
Which extrapolated to 24h is more in line with the 40M$ for 24h volume given by CoinMarketCap : 
![image](https://user-images.githubusercontent.com/32598581/43641083-a2300d36-9722-11e8-80ec-e91960447121.png)
