### ISSUE TITLE
Bitmex fetchTicker gives a 403 rejection error. (but fetchTickers working fine)

### ISSUE THREAD

**Issue by kitt-th** [ccxt/ccxt#3273]
- OS: MACOS 10.10.5 (14F2511)
- Programming Language version: Javascript
- CCXT version: current
- Exchange: Bitmex
- Method: exchange.fetchTicker

Hello, something that's puzzling me when trying to fetch the ticker for BTC/USD on bitmex. It gets rejected with "403 forbidden" but a call to fetchTickers for all ticker data works fine and I receive all the traded tickers' data. I'm guessing it's something simple I'm missing - any pointers?

Here is the code and I've included the verbose output below that. Thanks in advance.

===========================================================================
"use strict"

const ccxt = require ('ccxt')
const keys    = require ('../insideBars/access.json')

;(async function main () {

  let exchange = new ccxt.bitmex ({
     'apiKey': keys.thbitmexApiKey,
     'secret': keys.thbitmexApiSecret,
     'verbose' : true,
     enableRateLimit: true
  })
  
  try {

      console.log( await exchange.fetchTicker("BTC/USD") )
      console.log ('Succeeded.')

  } catch (e) {

      console.log ('--------------------------------------------------------')
      console.log (e.constructor.name, e.message)
      console.log ('--------------------------------------------------------')
      console.log ('Failed.')
  }

  return
}) ()

===========================================================================

Uni-Sound:bitmex brianmay$ node bitmexTicker.js 
fetch:
 bitmex GET https://www.bitmex.com/api/v1/instrument/activeAndIndices 
Request:
 {} 
 undefined 

handleRestResponse:
 bitmex GET https://www.bitmex.com/api/v1/instrument/activeAndIndices 200 OK 
Response:
 { Date: 'Wed, 27 Jun 2018 17:28:03 GMT',
  'Content-Type': 'application/json; charset=utf-8',
  'Transfer-Encoding': 'chunked',
  Connection: 'close',
  'Set-Cookie': 'AWSALB=I78ZsvkdQ6Mk2Fy0b4I3rYQ7ZwWj0u0zm4ghUwzEdmLNTPOX/wvP64/ghlmK0w79MsrUMMIShIJRzriPr/AX9Em9qy9xXv/mBzCcD7jhdin1/0D+HA71FrUeKIvK; Expires=Wed, 04 Jul 2018 17:28:03 GMT; Path=/',
  'X-Ratelimit-Limit': '150',
  'X-Ratelimit-Remaining': '149',
  'X-Ratelimit-Reset': '1530120484',
  'X-Powered-By': 'Profit',
  Etag: 'W/"23c5f-gjce9YKi0tXQCULRcxScTA6dTxA"',
  'Content-Encoding': 'gzip',
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains' } 
 [{.....I have not included ticker data from the ccxt auto loadmarkets call  ....}] 

fetch:
 bitmex GET https://www.bitmex.com/api/v1/quote/bucketed?symbol=XBTUSD&binSize=1d&partial=true&count=1&reverse=true 
Request:
 {} 
 undefined 

parseJson:
 bitmex GET https://www.bitmex.com/api/v1/quote/bucketed?symbol=XBTUSD&binSize=1d&partial=true&count=1&reverse=true 403 error SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at bitmex.parseJson (/Users/brianmay/node_modules/ccxt/js/base/Exchange.js:473:53)
    at response.text.then (/Users/brianmay/node_modules/ccxt/js/base/Exchange.js:550:44)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) response body:
'<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
</body>
</html>
'

--------------------------------------------------------

ExchangeNotAvailable bitmex GET https://www.bitmex.com/api/v1/quote/bucketed?symbol=XBTUSD&binSize=1d&partial=true&count=1&reverse=true 403 403 Forbidden not accessible from this location at the moment

--------------------------------------------------------

Failed.

**Comment by joncinque** [comment]
Hi there, I just ran into this issue myself, and found this response on the bitmex api repo: https://github.com/BitMEX/api-connectors/issues/141 -- looks like we'll have to wait until they re-enable it!

**Comment by kitt-th** [comment]
thanks john.
seems weird as fetching all tickers puts a greater load (well, more data) than fetching an individual ticker. Ah well!
