### ISSUE TITLE
Bitmex current candle data

### ISSUE THREAD

**Issue by sergejmueller** [ccxt/ccxt#3275]
Hello.

Is it possible to get data of the _current_ timeframe candle (low, hight, close)? 1H for example.

`fetchOHLCV()` returns last/closed candles, but not the current one.
`market()` returns values for the current _day_.

Any idea? Thx!

**Comment by kroitor** [comment]
Hi! Let us know if this does not help: https://github.com/ccxt/ccxt/issues/2254
