### ISSUE TITLE
Binance - issue pulling from API using Python

### ISSUE THREAD

**Issue by cartercarlson** [ccxt/ccxt#3285]
I've been running this same code, and the past few days I've been getting an error when it runs:

```
binance = ccxt.binance({
     'apiKey': 'key'
     'secret': 'secret'
})

balance = binance.fetchBalance()
```

HTTPError: 400 Client Error: Bad Request for url
InvalidNonce                              Traceback (most recent call last)
InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}

Any ideas why this error is coming up?

Thanks,
Carter

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/search?q=1000ms+ahead&type=Issues

**Comment by kroitor** [comment]
Answered and solved here: https://github.com/ccxt/ccxt/issues/850
