### ISSUE TITLE
Crazy gate.io fees (80%) [not a ccxt issue]

### ISSUE THREAD

**Issue by miracle2k** [ccxt/ccxt#3290]
This is not an issue in ccxt (I am pretty sure), but soley with gate.io, I am just wondering if any person here has some experience. I also contacted gate.io support, but did not hear back from them yet.

Here are two responses from the gate.io API (from `https://api.gate.io/api2/1/private/getOrder`):

```
{
        "orderNumber": "867728721",
        "status": "closed",
        "currencyPair": "eos_usdt",
        "type": "sell",
        "rate": "11.51",
        "left": 0,
        "amount": "0.00000000",
        "initialRate": "11.51",
        "initialAmount": "34.53543",
        "filledAmount": "34.53543",
        "filledRate": 11.509999999967,
        "feePercentage": 0.18,
        "feeValue": "0.795005598597698",
        "feeCurrency": "EOS",
        "fee": "0.795005598597698 EOS",
        "timestamp": 1528683928
    }
```

Notice the fee given here (0.79 EOS) is more than 2% of the amount.

Or this one:

``` 
{
        "orderNumber": "927083684",
        "status": "closed",
        "currencyPair": "eth_usdt",
        "type": "sell",
        "rate": "471",
        "left": 0,
        "amount": "0.00000000",
        "initialRate": "471",
        "initialAmount": "0.06005078",
        "filledAmount": "0.06005078",
        "filledRate": 471.47999921486,
        "feePercentage": 0.18,
        "feeValue": "0.0509629350730536",
        "feeCurrency": "ETH",
        "fee": "0.0509629350730536 ETH",
        "timestamp": 1529758567
    }
````

A fee of 0.05 ETH on a 0.06 trade? That would be 85%! 

Just wondering if any one had similar experiences before.

**Comment by kroitor** [comment]
1.

```
filledRate = 11,509999999967
filledAmount = 34,53543
filledAmount * feePercentage = 0,062163774 EOS
cost = 397,502799298860331
cost * feePercentage = 397,502799298860331 * 0,0018 = 0,715505038737949 USDT
```

So, in the first example I would expect the fee to be either of 
- 0,062163774 EOS or
- 0,715505038737949 USDT ←----- gateio shows approximately this value, but the difference is more than 10% of the value, and the currency is different

-----------------

2. 

```
filledRate = 471,47999921486
filledAmount = 0,06005078
filledAmount * feePercentage = 0,000108091404 ETH
cost = 28,312741707251731
cost * feePercentage = 28,312741707251731 * 0,0018 = 0,050962935073053 USDT
```

In the second example I would expect the fee to be either of
- 0,000108091404 ETH
- 0,050962935073053 USDT ←----- gateio shows exactly this value, but in ETH currency (which is a mistake, obviously)

-----------------------

To me all of the above looks like gateio has a wrong indication of the fee currency and most likely a wrong calculation for the fee value.

**Comment by miracle2k** [comment]
Good catch. I did the math for the first case and when neither the amount nor the currency matched I concluded that the fee must be totally wrong.

But the second example tells us that the fee currency is wrong.

I hope the fee that they take from their user's balances is the right one! Difficult to trust them.

**Comment by miracle2k** [comment]
This is what they say:

> Thank you for your feedback. 
> We checked it and find the error.
> The fee  charged is in USDT, not eth for the second order. The 0.0509629350730536 ETH" should be display as  0.0509629350730536 USDT instead.
> There is an error in the returned fee currency. 
> 
> As to the first example, the fee is deducted as 0.2%. 
> May you please calculate the difference of the fee for the first order and we will add it to you?
>

**Comment by mkutny** [comment]
How long did it take them to answer? Surprised that they answered at all, I was pretty sure that this is a dead exchange.

**Comment by kroitor** [comment]
@mkutny 

> How long did it take them to answer? Surprised that they answered at all

Looks like a day or two.

@miracle2k thx for reporting! At this point, the issue is clear, I believe. Do you mind if I close this or do you want me to keep this open for a while?

**Comment by miracle2k** [comment]
Sure, we can close it. I asked them to fix it. If anything else happens here I will comment.

**Comment by miracle2k** [comment]
```
hi,
Thank you for your feeback. Our dev team has fixed it. 
```

It seems fixed in my experiments.

**Comment by kroitor** [comment]
@miracle2k great news, thx so much for the info!
