### ISSUE TITLE
Getting deposit address for HitBTC and Poloniex?

### ISSUE THREAD

**Issue by springjben** [ccxt/ccxt#3295]
How do I get my deposit address from a site? If its not created, I need it created. I see there is an unfinished method called: fetchDepositAddress, however it doesn't work with HitBTC or Poloniex.

You have any ideas on how to pull my deposit address?

I am using Python

**Comment by springjben** [comment]
There is nothing about it in the documentation, apart from createMarketOrder. But these 2 exchanges don't support that.

**Comment by kroitor** [comment]
@springjben let us know if this does not help: https://github.com/ccxt/ccxt/wiki/Manual#funding-your-account

**Comment by springjben** [comment]
^ yeah I am using fetchDepositAddress... However HitBTC and Poloniex do not support them. 



hitbtcAPI.fetchMarkets()
print(hitbtcAPI.fetchDepositAddress('DGB'))

Gives this error
![capture](https://user-images.githubusercontent.com/32540273/42136649-6943e96e-7d57-11e8-83b0-0ac378be3966.PNG)

**Comment by kroitor** [comment]
> However HitBTC and Poloniex do not support them.

- HitBTC v2 does support it, use hitbtc2 instead of hitbtc (v1 is deprecated):

https://github.com/ccxt/ccxt/blob/master/js/poloniex.js#L788

- Poloniex does support it:

https://github.com/ccxt/ccxt/blob/master/js/hitbtc2.js#L1061

Make sure your version of the library is up to date:

```Python
import ccxt
print(ccxt.__version__)
```

**Comment by springjben** [comment]
I am on CCXT version 1.14.50. Also your links above are the wrong way around :)

**Comment by springjben** [comment]
I get an error install CCXT now:

![image](https://user-images.githubusercontent.com/32540273/42136695-702b4550-7d58-11e8-857a-a2524ad8a9b3.png)

**Comment by kroitor** [comment]
```
pip3 install --upgrade ccxt
```

**Comment by springjben** [comment]
Just updated my ccxt.

The HitBTC deposit addressnow works. But Poloniex does not.

Code:

poloniexAPI = ccxt.poloniex ({
'apiKey': '...',
'secret': '...',
})

print(poloniexAPI.fetchDepositAddress('DGB'))

Response:
![image](https://user-images.githubusercontent.com/32540273/42136756-4c499a78-7d59-11e8-9748-1d1264deaeff.png)

Do I need to load the currencies for this? I tried. but the same error occurs.

**Comment by springjben** [comment]
With Poloniex I have to do:
```

    poloniexAPI.loadMarkets()
    poloniexAPI.fetchMarkets()
    poloniexAPI.fetchCurrencies()
    print(poloniexAPI.fetchDepositAddress('DGB'))
```

To get it to work. But I do NOT have to do this with the others.

**Comment by kroitor** [comment]
@springjben i've added the fix for the `loadMarkets()`, so if you update ccxt once again (to version 1.14.305) you won't have to call it manually for Poloniex.

**Comment by springjben** [comment]
Can confirm that its fixed.

Thanks for the quick reply.
