### ISSUE TITLE
Gdax deposit / withdraw history

### ISSUE THREAD

**Issue by scredii** [ccxt/ccxt#3299]
Hi !

How i can get deposit and withdrawal history with gdax api please ?

I didn't see endpoint for that and i don't get deposit/withdraw history with fetchMyTrades() or fetchClosedOrder() endpoint;

Thanks !

**Comment by kroitor** [comment]
See this:

- https://github.com/ccxt/ccxt/issues/1896
- https://github.com/ccxt/ccxt/pull/2610

Will merge the above soon. In the meantime, you can clone the above branch and use it on your side for testing (google for it, if needed). Let us know if this does not answer your question.
