### ISSUE TITLE
HitBTC fetch_order implementation

### ISSUE THREAD

**Issue by JSRossiter** [ccxt/ccxt#3304]
- Exchange: hitbtc
- Method: fetch_order

When calling fetch_order for a market order on hitbtc cost appears to be calculated by multiplying the price and cumQuantity amounts together. The problem with this is that price is just a number they use to lock funds before execution and is ~10% higher than the executed price. Since this number is so inaccurate I find it worse than useless and would prefer it to be a None value.

You might not want to do anything about this since it possibly affects other people but I thought I'd share my thoughts anyway.

If you do keep it you may want to consider rounding the value, or using a decimal type as I've seen values such as 0.006624550000000001

**Comment by kroitor** [comment]
Hi! Does this answer your issue? https://github.com/ccxt/ccxt/issues/798

**Comment by JSRossiter** [comment]
That seems to say the opposite? The order isn't cached, I ran this query in the console using an ID from my database. Did you make a change in response to that issue?

Regardless, this isn't a big deal, thanks for your work.
