### ISSUE TITLE
Cancle Order on OKEX

### ISSUE THREAD

**Issue by MarkPatzelt** [ccxt/ccxt#3305]
This is my first post, so I might be asking the wrong question at the wrong place, but maybe somebody can help me:

- OS: Windows 10
- Programming Language version: Python 3.6.4
- CCXT version: 1.14.288
- Exchange: OKEX
- Method: cancle_order

Trying to cancle limit sell orders but cannot find the right method to do so. There is a method called cancle_order which seems to relate to OKCOINUSD instead of EXCHANGE.

Did I overlook anything something? I tried to find the solution myself but failed so far.

Thank you
Mark

**Comment by kroitor** [comment]
Hi!

1. Read the Manual: https://github.com/ccxt/ccxt/wiki/Manual
2. How to cancel orders: https://github.com/ccxt/ccxt/wiki/Manual#canceling-orders
3. OKEX is a class derived from OKCoinUSD: https://github.com/ccxt/ccxt/tree/master/python

Hope this answers your question.

**Comment by MarkPatzelt** [comment]
Thanx, it required the orderID AND the symbol, in this sequence...
