### ISSUE TITLE
Can I buy and sell altcoins?

### ISSUE THREAD

**Issue by rstrapasson** [ccxt/ccxt#3306]
Hi. Is it possible to buy and sell altcoins using this script?

ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by kroitor** [comment]
Hi!

> Is it possible to buy and sell altcoins using this script?

Yes! https://github.com/ccxt/ccxt/wiki/Manual#placing-orders
