### ISSUE TITLE
Endpoint request: QuadrigaCX fetchOrder

### ISSUE THREAD

**Issue by JSRossiter** [ccxt/ccxt#3309]
- CCXT version: latest
- Exchange: QuadrigaCX
- Method: fetchOrder

Not sure when they implemented this but I notice in their API docs (https://www.quadrigacx.com/api_info) it's labelled new still.

Quadriga isn't my highest priority right now but I might take a look at adding this if someone else doesn't soon

Thanks.

**Comment by kroitor** [comment]
> Quadriga isn't my highest priority right now but I might take a look at adding this if someone else doesn't soon

That would be awesome! Just make sure to read this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
