### ISSUE TITLE
Cryptopia candles

### ISSUE THREAD

**Issue by viniciussvl** [ccxt/ccxt#3310]
Where do you look for the cryptopia candles? In their API they have no endpoint that returns the data of the candles.

**Comment by kroitor** [comment]
It's in the source code of our implementation for Cryptopia:

- https://github.com/ccxt/ccxt/blob/master/js/cryptopia.js#L191
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/cryptopia.py#L203
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/async/cryptopia.py#L203
- https://github.com/ccxt/ccxt/blob/master/php/cryptopia.php#L192
