### ISSUE TITLE
What is the order of the clues in the return of the OHLCV candles?

### ISSUE THREAD

**Issue by viniciussvl** [ccxt/ccxt#3311]
Hello, sorry to bother again is that I found nothing in the documentation that could answer my question. I need to know what indices are being returned, it returns an array of 0 to 5, but what is the open price? price close? high, volume? just looking like that I could not identify.

```

[0]=>
  array(6) {
    [0]=>
    float(1527969927487)
    [1]=>
    float(0.0161)
    [2]=>
    float(0.01612083)
    [3]=>
    float(0.01607015)
    [4]=>
    float(0.01612083)
    [5]=>
    float(0.69812253115276)
  }
  [1]=>
  array(6) {
    [0]=>
    float(1527971727487)
    [1]=>
    float(0.01608979)
    [2]=>
    float(0.01614542)
    [3]=>
    float(0.01607339)
    [4]=>
    float(0.01611157)
    [5]=>
    float(0.42589696985619)
  }
```

**Comment by kroitor** [comment]
the order is the OHLCV abbreviation itself...
https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-structure

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki
