### ISSUE TITLE
New Exchange: BitForex

### ISSUE THREAD

**Issue by JoshVarty** [ccxt/ccxt#3313]
Similar to #1392 

I'm not sure if this is a new exchange but I noticed it today in CoinMarketcap's [top ten exchanges by volume](https://coinmarketcap.com/exchanges/volume/24-hour/).

Website: https://bitforex.com

It doesn't appear to have a public API yet, but I figured I would create an issue as I couldn't find any other issues or code that mentioned this exchange.

**Comment by valentinbora** [comment]
I had a chat with them, they said a Public API is not available at the moment but that some of their 'customers' do have access to it. To be continued 😄

**Comment by Showgofar** [comment]
Yes they had added API with all required functions

**Comment by JoshVarty** [comment]
I'll give this a shot if no one else has started yet.

**Comment by kroitor** [comment]
Merged in #3634 thx and respect to @JoshVarty ! )
