### ISSUE TITLE
async nonce function

### ISSUE THREAD

**Issue by hems** [ccxt/ccxt#3315]
- Programming Language version: node.js
- CCXT version: latest
- Method: Overriding nonce

Is it possible to use an async nonce() function?

This way the nonce could be persisted in a database and shared among multiple instances in different machines.

**Comment by mkutny** [comment]
Hey,

I understand what you want to achieve but I'm not sure it's a feasible/realiable way to accomplish it.

I don't know what are your constraints but if they are not strict then for low frequency (e.g. few per second) requests timestamp will do just fine. Using DB for holding a (similar to timestamp) counter will surely be an overkill. Moreover, some exchanges (like binance) just force you to use a real synched timestamp, an arbitrary incremental function won't pass their authentication.

As for high-frequency requests (tens per second or more), you'll be constantly thrown out of sync. At least in my experience, if I happen to send several requests per second then it's not a rare case when the first originated request (with lower nonce) arrives at an exchange later then the second one (with higher nonce). As a result, the first request gets rejected.

Now add one more level of asynchronicity (i.e. `await this.nonce()`) and you'll see that even your multiple instances may fall out of sync even before they have a chance to talk to an exchange.

So, unless you have some serious constraints that forbid you from using timestamps I'd rather suggest sticking to them as this will make your life much easier.

**Comment by hems** [comment]
If you want to scale a service you will need sooner or later to split the work among different machines running taking jobs from a job queue.

As you can imagine things can get funny once you have different machines generating nonces and processings loads of jobs at the same time, race conditions can happen and then storing nonces on a database might be the ideal solution.

Of course there are other work arounds that could be done, but this could actually be a good solution for multi-processes / multi-machine setups.

**Comment by kroitor** [comment]
@hems we will add an option for it, but we can't promise when.

**Comment by hems** [comment]
thanks

**Comment by hems** [comment]
@kroitor we ended up having to hack the library by creating a new instance and passing a "nonce" function as argument every time.

Is there a better solution you guys could recommend or implement?

Thank You.

**Comment by kroitor** [comment]
> Is there a better solution you guys could recommend or implement?

A generic-enough solution would be to make all the `sign()` implementations `async`, and then just use `await` on whatever the `nonce` function is, as `await` will work for promises and plain functions.
That feature is on our roadmap and we might actually add it soon.

**Comment by npomfret** [comment]
I'm attempting the same thing.  I've managed to do it by replacing the `fetch2` method with one of my own inside of which it replaces the call to `sign` with once that makes an asnc call to my server.  The server handles the nonce de-duplication issue and returns a signed request.

It works, but in reality I have a distributed system and sometimes it looks like the signed requests hit the exchange in an unpredictable order (when 2 requests are issued at roughly the same time they can _overtake_ each other).  So even though the generated nonces are unique, they aren't always ascending (as far as the exchange is concerned) which some exchanges don't allow.

I'm wondering now if actually the best solution is to just try the request again in the event of a nonce-based error. Having a centralised nonce-service might not be possible (depending on the exchanges you use).

**Comment by kroitor** [comment]
> I'm wondering now if actually the best solution is to just try the request again in the event of a nonce-based error. Having a centralised nonce-service might not be possible (depending on the exchanges you use).

In general, a centralized server will help resolve many nonce conflicts, but not all of them, so you will have to add a retry-logic to make the system redundant. As you properly noted, a centralized nonce doesn't protect you from the very nature of the underlying REST-over-HTTP communication – it will still be out of order occasionally. The only way to overcome this entirely is to have just one "talker to the exchange" with all requests and responses scheduled via a single point of control depending on which rate-limiting is implemented on this or that exchange. The "talker" would only have one http-over-tcp connection with `keep-alive` option or will use http/2 where supported by the exchange, this way you can guarantee ordering as much as possible. It won't protect you for 100%, because there may be latencies in the exchange infrastructure itself, so, you will never get the ideal 100%, you can only approach it as much as you can.

**Comment by frosty00** [comment]
not planned in the near future
