### ISSUE TITLE
binance order price exceeds allowed price precision or invalid, use this.priceToPrecision 

### ISSUE THREAD

**Issue by alexgpark** [ccxt/ccxt#3324]
- OS: macOS High Sierra
- Programming Language version: NodeJS v8.9.1 
- CCXT version: ccxt@1.14.172
- Exchange: Binance
- Method: createOrder

I get the following error...

> Error: binance order price exceeds allowed price precision or invalid, use this.priceToPrecision (symbol, amount) {"code":-1013,"msg":"Filter failure: PRICE_FILTER"}

when attempting to create Stop Loss with the following code:

```
function precisionRound(num, precision) {
  precision = Math.pow(10, precision)
  return Math.round(num * precision) / precision
}

var buyLimitPrice = precisionRound((lowestPriceExchange.askPrice * 1.005), 8);
const stopPrice = precisionRound((buyLimitPrice * 0.9), 8);
const limitPrice = precisionRound((buyLimitPrice * 0.89), 8);

lowestPriceExchange.exchange.createOrder(coinPair, 'stop_loss_limit', 'sell', quantity, limitPrice, { 'stopPrice' : stopPrice })

```
Initially I had
`
const stopPrice = buyLimitPrice * 0.9;
const limitPrice = buyLimitPrice * 0.89;
`

and got that same error above.

I interpreted the error to mean I didn't have the correct number of decimal places, which is why I added the rounding function with a precision of 8 places after decimal point. 

But now even with the rounding function, I still get the same error and struggling to identify what the root issue is.

Any code examples of using the recommended `this.priceToPrecision (symbol, amount)` in the context of setting a Stop Loss order?

**Comment by kroitor** [comment]
@alexgpark 

1. Please, read this:

- https://github.com/ccxt/ccxt/wiki/Manual#market-structure
- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

2. > But now even with the rounding function, I still get the same error and struggling to identify what the root issue is.

```JavaScript

/*

// ------ not needed ----------------

function precisionRound(num, precision) {
  precision = Math.pow(10, precision)
  return Math.round(num * precision) / precision
}

// ------ not needed ----------------

*/

// ------ edited this ↓ ----------------
var buyLimitPrice = lowestPriceExchange.askPrice * 1.005;
const limitPrice = buyLimitPrice * 0.89;
const stopPrice = buyLimitPrice * 0.9;

// ------ added this ↓ ----------------
stopPriceToPrecision = lowestPriceExchange.exchange.priceToPrecision (coinPair, stopPrice);

lowestPriceExchange.exchange.createOrder(coinPair, 'stop_loss_limit', 'sell', quantity, limitPrice, { 'stopPrice' : stopPrice })
```

Let us know if it still does not work like this, and if it does not, please make sure to read this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

P.S. I'd also recommend to update your ccxt version.

**Comment by kroitor** [comment]
Feel free to reopen it if needed or just ask further questions if any, i'd close it for now, if you don't mind. Thx!
