### ISSUE TITLE
Fetch Ticker (Bittrex) - Error: bad operand type for unary -: 'dict'

### ISSUE THREAD

**Issue by valvesss** [ccxt/ccxt#3329]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Fedora 27
- Programming Language version: Python 3.X
- CCXT version: 1.15.18
- Exchange: Bittrex
- Method: Fetch Ticker

CODE:

#!/usr/bin/python3
import ccxt

bittrex = ccxt.bittrex()

print(bittrex.fetch_ticker('BTC/USD'))

RESPONSE:

Error: bad operand type for unary -: 'dict'

What should I do? Thanks!

**Comment by kroitor** [comment]
Sorry, this was my bad, a leftover bug. I've uploaded a fix and you should be fine if you update to new version 1.15.19 (will be available for downloading in 5-10 minutes).

**Comment by valvesss** [comment]
Thanks!
