### ISSUE TITLE
Bitmex returning None on bid and ask prices with fetch_ticker(BTC/USD)

### ISSUE THREAD

**Issue by salihkilic** [ccxt/ccxt#3337]
- OS: Windows 10
- Programming Language version: Python 
- CCXT version: 1.15.25
- Exchange: Bitmex

Hey there, I'm building a small script to retrieve BTC to USD/USDT prices from several exchanges. Bitmex seems to be only returning tickers with None bid and ask values. Here is an example:

```
{   'ask': None,
    'askVolume': None,
    'average': 6592.5,
    'baseVolume': 68269.88704205,
    'bid': None,
    'bidVolume': None,
    'change': -14.0,
    'close': 6585.5,
    'datetime': '2018-07-07T12:15:39.063Z',
    'high': 6617.5,
    'info': {   'close': 6585.5,
                'foreignNotional': 449483304,
                'high': 6617.5,
                'homeNotional': 68269.88704205,
                'lastSize': 723,
                'low': 6558.5,
                'open': 6599.5,
                'symbol': 'XBTUSD',
                'timestamp': '2018-07-08T00:00:00.000Z',
                'trades': 139169,
                'turnover': 6826988704205,
                'volume': 449483304,
                'vwap': 6584.1454},
    'last': 6585.5,
    'low': 6558.5,
    'open': 6599.5,
    'percentage': -0.21213728312750968,
    'previousClose': None,
    'quoteVolume': 449483304.0,
    'symbol': 'BTC/USD',
    'timestamp': 1530965739063,
    'vwap': 6584.1454}

```

**Comment by kroitor** [comment]
@salihkilic the problem with Bittrex is that they will return just the OHLCV or just the bid and the ask, but not both (in a single call)... We're looking for better workarounds. In the meantime, I guess, you should fetchOrderBook or fetchMarkets if you want their current bidask. Let us know if it does not answer your question. Your suggestions are also welcome. Thx!

**Comment by salihkilic** [comment]
Hey Kroitor, I was talking about Bitmex (not Bittrex like you mentioned) and they do provide both ask and bid in one call with load_markets()but not in fet_ticker().

**Comment by kroitor** [comment]
@salihkilic yeah, sorry, it was a typo in my answer, Bitmex, of course.

**Comment by proeng** [comment]
I am not sure if this is proper place to ask, but it follows the original question. 
I am building a trading bot and i have a problem with btimex returning None on bid+ask, as you answered above, but i am confused how to solve the issue. 
Problem is if i use fetch_markets, or order_books, i will run out of my allowed data to fetch per minute real quickly, i need to be able to fetch specific data about 1 coin at a time. I am limiting myself to fetching 5 coin tickers per exchange at a single time. 

Is there a way to calculate bid and ask from OHLCV, or how should i approach this?
I want the price that is displayed on the actual exchange, when you trade there, or the price that is displayed in tradeview on that exchange. Is there something i misunderstand, is there a better way to get this data without getting to much data per second so i get banned?
