### ISSUE TITLE
Python aiohttp raises an RuntimeError with Jupyter

### ISSUE THREAD

**Issue by cloudseasail** [ccxt/ccxt#3338]
The following code in Jupyter will raise RuntimeError:

```
async def _test_ticker():
    api = ccxt.coinex()
    print(await api.fetch_ticker('BTC/USDT'))
def test_ticker():
    asyncio.get_event_loop().run_until_complete(_test_ticker())

```

> File "c:\programdata\miniconda3\lib\site-packages\ccxt\async\coinex.py", line 208, in fetch_ticker
>     await self.load_markets()
>   File "c:\programdata\miniconda3\lib\site-packages\ccxt\async\base\exchange.py", line 156, in load_markets
>     markets = await self.fetch_markets()
>   File "c:\programdata\miniconda3\lib\site-packages\ccxt\async\coinex.py", line 135, in fetch_markets
>     response = await self.webGetResMarket()
>   File "c:\programdata\miniconda3\lib\site-packages\ccxt\async\coinex.py", line 474, in request
>     response = await self.fetch2(path, api, method, params, headers, body)
>   File "c:\programdata\miniconda3\lib\site-packages\ccxt\async\base\exchange.py", line 102, in fetch2
>     return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
>   File "c:\programdata\miniconda3\lib\site-packages\ccxt\async\base\exchange.py", line 124, in fetch
>     proxy=self.aiohttp_proxy) as response:
>   File "c:\programdata\miniconda3\lib\site-packages\aiohttp\client.py", line 843, in __aenter__
>     self._resp = await self._coro
>   File "c:\programdata\miniconda3\lib\site-packages\aiohttp\client.py", line 317, in _request
>     with timer:
>   File "c:\programdata\miniconda3\lib\site-packages\aiohttp\helpers.py", line 662, in __enter__
>     raise RuntimeError('Timeout context manager should be used '
> RuntimeError: Timeout context manager should be used inside a task

I think it is same issue with tornado one below,  anyone knows how to workaround this?
[https://github.com/aio-libs/aiohttp/issues/877](https://github.com/aio-libs/aiohttp/issues/877)

**Comment by frosty00** [comment]
Latest version works normaly on python3.6:

```
test_ticker()
{'symbol': 'BTC/USDT', 'timestamp': 1531226414350, 'datetime': '2018-07-10T12:40:14.350Z', 'high': ...
```

Are you sure that you did:

```
import ccxt.async as ccxt
```

or

```
api = getattr(ccxt, 'async')
```

"async" is now a reserved keyward so `ccxt.async.exchange` doesn't work

**Comment by kroitor** [comment]
Closing this for now due to inactivity, fee free to reopen it if needed or just ask further questions, if any. We will be happy if you report back if you managed to solve it (and how). Thx!
