### ISSUE TITLE
New exchange: Deribit

### ISSUE THREAD

**Issue by md0101** [ccxt/ccxt#334]
Hi, could you include this derivatives exchange?
Their API can be found here
https://www.deribit.com/main#/help?scrollTo=api&page=api

**Comment by kroitor** [comment]
Hi, sure! Thx for your proposal! We'll take a deep look into it and will integrate hopefully, soon!

**Comment by kroitor** [comment]
Almost there ;)

**Comment by md0101** [comment]
superb thanks for this

**Comment by jjhesk** [comment]
great! when its the repo ready? this is the api. https://www.deribit.com/main#/pages/docs/api

**Comment by kroitor** [comment]
@jjhesk almost there, hope to finish it in a couple of days.

**Comment by jjhesk** [comment]
@kroitor cant wait to see it done! a big thanks!

**Comment by jjhesk** [comment]
@kroitor is that done? where is the draft?

**Comment by kroitor** [comment]
@jjhesk here: https://gist.github.com/kroitor/401930432963fda2285a5bb51aefe890

**Comment by jjhesk** [comment]
<img width="142" alt="2018-01-24 2 13 15" src="https://user-images.githubusercontent.com/629338/35326678-d005069c-0110-11e8-8a4c-8c8e201da2a2.png">

**Comment by kroitor** [comment]
@jjhesk making them by hand in Photoshop to make each one of them fit into 85x25, <5kb.

**Comment by kmarkt** [comment]
great work...
do you have any plans creating python code?

**Comment by kroitor** [comment]
@kmarkt 

> do you have any plans creating python code?

Python code is created automatically upon building: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

**Comment by kmarkt** [comment]
@kroitor Thanks very much for so quick response. will try it out.

**Comment by SergeGardien** [comment]
Is Deribit really available?

I don't see it listed in [Supported Cryptocurrency Exchange Markets](https://github.com/ccxt/ccxt#supported-cryptocurrency-exchange-markets).

Moreover`exchange = ccxt.deribit()` gives `AttributeError: 'module' object has no attribute 'deribit'`.

**Comment by kroitor** [comment]
> Is Deribit really available?

Not yet. This thread is about adding it.

**Comment by SergeGardien** [comment]
Thanks for the reply Igor. By reading the thread I had the impression it was already implemented, hence the question.

Keep up the good work!
