### ISSUE TITLE
btctradeim load_markets error

### ISSUE THREAD

**Issue by jackyxie** [ccxt/ccxt#3343]
- OS:Linux
- Programming Language version: PHP
- CCXT version:1.15.28
- Exchange:btctrade.im
- Method:load_markets
btctradeim fetchMarkets() for "usdt" returned => "null" (ignoring)

**Comment by jackyxie** [comment]
It is ok to use https://api.btctrade.im  instead of  https://www.btctrade.im with some of the api.

**Comment by kroitor** [comment]
@jackyxie didn't quite understand your comment, can you clarify, please?

**Comment by jackyxie** [comment]
www.btctrade.im is protecting by cf, and api.btctrade.im is ok to get data normally.

**Comment by kroitor** [comment]
> www.btctrade.im is protecting by cf, and api.btctrade.im is ok to get data normally.

Which endpoint from api.btctrade.im would you suggest for a list of their markets? The problem is that they don't have a documented endpoint for this. So, this is the only thing that we're using www.btctrade.im for. Most other endpoints are fetched from api.btctrade.im.

**Comment by jackyxie** [comment]
As btctradeim do not has usdt trading pairs. Error show up as below when fetchMarkets.

>  btctradeim fetchMarkets() for "usdt" returned => "null" (ignoring)"

**Comment by kroitor** [comment]
> As btctradeim do not has usdt trading pairs. Error show up as below when fetchMarkets.

Exactly, this is why `usdt` was deleted from btctradeim here: https://github.com/ccxt/ccxt/issues/3292

Are you sure that your version of CCXT is up to date?

**Comment by jackyxie** [comment]
Yeah, I update ccxt first and then run my program. version num in Exchange.php is 
`php
$version = '1.15.28';
`

**Comment by jackyxie** [comment]
@kroitor  btctrade.im implement from coinegg. And coinegg quoteIds has usdt.
