### ISSUE TITLE
KRAKEN: Private Deposit Method & Deposit Address endpoints not working.

### ISSUE THREAD

**Issue by creativegeniusod** [ccxt/ccxt#3344]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by kroitor** [comment]
Have you read this? ↓

> MUST READ THIS BEFORE SUBMITTING ISSUES:
> https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it
