### ISSUE TITLE
New signature calculation at Huobi

### ISSUE THREAD

**Issue by vmish** [ccxt/ccxt#3345]
- OS: all
- Programming Language version: all
- CCXT version: all
- Exchange: huobipro
- Method: sign

New **PrivateSignature** is on today at [Huobi](https://github.com/huobiapi/API_Docs_en/wiki/Signing_API_Requests).

Parallel Run Period: July 9th, 2018, 14:00:00 - July 23rd, 2018 23:59:59 (GMT+8 Beijing）

**Comment by kroitor** [comment]
@vmish thx for the notice!

**Comment by Iliker** [comment]
When to support?

**Comment by kroitor** [comment]
@Iliker we already do support it, no changes in the code are needed, just recreate the keys and that's it.

**Comment by obsidianart** [comment]
@kroitor How is the ssh public key called? Huobi now expects 3 parameters if I understand the update correctly.

**Comment by kroitor** [comment]
@obsidianart 

1. create private and public key (follow the link in the original post and links from there)
2. upload your public key to huobi to get apiKey + secret
3. put your new apiKey + secret into your exchange config, nothing else is needed.

**Comment by Iliker** [comment]
@kroitor 

huobipro api docs   
https://github.com/huobiapi/API_Docs/wiki/REST_authentication

> 请求结构中需同时包括Signature 和PrivateSignature，其他流程不变。

no need PrivateSignature?

**Comment by kroitor** [comment]
@Iliker oh, right, I'll add the PrivateSignature there shortly, missed it somehow.

**Comment by zsyh** [comment]
@kroitor  huobipro canceled the signature update just now, there document also rolled back

**Comment by kroitor** [comment]
Yeah, they deleted their example code 11 hours ago because it didn't really work.

**Comment by obsidianart** [comment]
They changed their mind and decided not to update their API, we can close this
