### ISSUE TITLE
exx volumes

### ISSUE THREAD

**Issue by Esc4pism** [ccxt/ccxt#3355]
All marketpairs on exx with CNYT (CNY Tether) seem to have inversed base/quote volumes.

I checked https://api.exx.com/data/v1/tickers and it seems the volume they send is usually the base-volume, but for all their CNYT-pairs its the quote-volume (otherwise those volumes would be in the Trillions of $)

**Comment by kroitor** [comment]
```
mbp:ccxt igorkroitor$ node examples/js/cli exx fetchTicker ETH/CNYT
exx.fetchTicker (ETH/CNYT)
{        symbol:   "ETH/CNYT",
      timestamp:    1531230304825,
       datetime:   "2018-07-10T13:45:04.825Z",
           high:    3230,
            low:    2910.01,
            bid:    3050,
      bidVolume:    undefined,
            ask:    3110,
      askVolume:    undefined,
           vwap:    undefined,
           open:    undefined,
          close:    3050,
           last:    3050,
  previousClose:    undefined,
         change:    -4.38,
     percentage:    undefined,
        average:    undefined,
     baseVolume:    37222581.473,
    quoteVolume:    undefined,
           info: {          high: "3230.0",
                             vol: "3.7222581473E7",
                   monthRiseRate:  -19.31,
                            last: "3050.000000000",
                             low: "2910.01",
                             buy: "3050.00",
                            sell: "3110.00",
                    weekRiseRate:  -2.49,
                        riseRate:  -4.38            } }
```

The problem is actually a bit different... The values are in their proper places, however, they report scientific notation in uppercase (`vol: "3.7222581473E7"`) which is not parsed correctly.

**Comment by kroitor** [comment]
I'm a bit confused...

Not sure how these 24 volume-values can differ by several orders of magnitude for BTC / ETH in such a particular way:

<img width="1239" alt="screen shot 2018-07-10 at 16 56 06" src="https://user-images.githubusercontent.com/1294454/42514469-2cd6dc18-8462-11e8-97ad-4729223bd3f3.png">

<img width="1335" alt="screen shot 2018-07-10 at 16 55 42" src="https://user-images.githubusercontent.com/1294454/42514519-48dd3e34-8462-11e8-9833-5b9f0a39e3f5.png">

**Comment by Esc4pism** [comment]
I didnt quite get it either... from what ive seen, coinlib.io calculates the volume as "quote"-volume for the CNYT pairs (but not for all of those pairs...). And Coinmarketcap doesnt list any of the CNYT pairs at all.

I think they are just inconsistent and should clarify it in their docs, or update their api.

**Comment by Esc4pism** [comment]
![image](https://user-images.githubusercontent.com/30901436/42558045-5ff1c700-84f0-11e8-8073-81fab49931f7.png)

Seems they fixed something on their side, those numbers today check out more believably, although there are still a few pairs which could still be inverted, but those arent major coins or amounts that would totally skew averages.
