### ISSUE TITLE
Fetching candles from Bitfinex

### ISSUE THREAD

**Issue by geraldvandergrijn** [ccxt/ccxt#3358]
OS: macOS High Sierra 10.13.5
Programming Language version: Python 3.6.6 :: Anaconda, Inc.
CCXT version: ccxt 1.15.7
Exchange: Bitfinex
Method: fetch_ohlcv

It seems that Bitfinex does not store candle data from before 19 May 2017.

This is what I do:
from_datetime = '2017-01-01 00:00:00'
from_timestamp = exchange.parse8601(from_datetime)
ohlcvs = exchange.fetch_ohlcv(symbol='BTC/EUR', timeframe='1d', since=from_timestamp)

This is what is returned:
_1531254457310 Fetching candles starting from 2017-01-01T00:00:00.000Z
1531254457369 Fetched 100 candles
First candle epoch 1495152000000 2017-05-19T00:00:00.000Z
Last candle epoch 1504569600000 2017-09-05T00:00:00.000Z_

Is this a known issue?

**Comment by kroitor** [comment]
> Is this a known issue?

Their BTC/EUR trading was announced in Nov 2017...

https://twitter.com/bitfinex/status/933134086289453056

<img width="552" alt="screen shot 2018-07-11 at 10 41 46" src="https://user-images.githubusercontent.com/1294454/42557441-3cc9a9bc-84f7-11e8-8cc0-3df21ffaec26.png">

You can't really fetch OHLCV for non-existing history, sorry ) Let us know if this does not answer your question.

**Comment by geraldvandergrijn** [comment]
It sure does 👍
