### ISSUE TITLE
Request: Programmatically Display CCXT Version

### ISSUE THREAD

**Issue by ccasselman** [ccxt/ccxt#3361]
Due to recent deployment issues - I'd like a way to programmatically display the installed/local version of CCXT in PHP.

It is set on line 33 but gets overwritten in the constructor.

Thanks!

**Comment by kroitor** [comment]
```PHP
mbp:ccxt igorkroitor$ php -a
Interactive shell

php > include_once ('ccxt.php');
php > echo \ccxt\Exchange::VERSION;
1.15.41
php >
```

**Comment by ccasselman** [comment]
Thank you!
