### ISSUE TITLE
dup coin: FAIR in coinexchange is FairCoin

### ISSUE THREAD

**Issue by arielorvits** [ccxt/ccxt#3364]
in okex and hadax FAIR is FairGame 

(CMC)

**Comment by arielorvits** [comment]
@kroitor, 
I think you meant to change in coinexchange, 
but u changed in hadax

**Comment by arielorvits** [comment]
@kroitor 
so, u should do 'FAIR': 'FairGame' in hadax

what u actually did is 'FAIR': 'FairCoin' in hadax

**Comment by kroitor** [comment]
@arielorvits right, thx for pointing that out for me, the fix is on the way!
