### ISSUE TITLE
withdraw for hitbtc2 not working 

### ISSUE THREAD

**Issue by asociadoC** [ccxt/ccxt#3366]
Hi there, I am having huge difficulties to get withdraws from hitbtc to run.

First I found that I tried to withdraw inactive currencies, but I know that -- for example -- STQ is active on hitbtc, I checked with the .currencies method, too. But when I am trying to withdraw something, I only see 

[Exchange Error] hitbtc2 does not have currency code STQ

I just found, that it seems that the amount - withdraw-fee seems to be too small, but in this case we definetely need a better error message for that. It took me several hours to at least find that the currency is inactive (while it was able to buy/sell .. ) and now again that the funds can not pay the fees to withdraw ..

- OS: Ubuntu 16.04.4 LTS
- Programming Language version: 
- CCXT version: nodejs v8.11.3
- Exchange: hitbtc2
- Method: withdraw

Besides that, I really appreciate this project and the great work on it, please keep up that good work !

best regards, Simon

**Comment by kroitor** [comment]
Looks like you forgot to load markets....

https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

For some reason autoloading for hitbtc2 withdraw was missing, but anyways, if you update to most recent version of ccxt 1.15.43, the issue should be resolved. Let us know if not. Thx!

**Comment by asociadoC** [comment]
Hi there, 

thanks for your quick reply ! 

I just updated ccxt again to now 
+ ccxt@1.15.45
and will try immediately. But do I really have to loadMarkets before a withdraw !? If so, this would be new to me, maybe I did by mistake somewhere before, but I never loaded markets before  a withdraw by intention ..

Will try anyways and report back !
