### ISSUE TITLE
Getting rid of /public/ inside an API endpoint.

### ISSUE THREAD

**Issue by benjover** [ccxt/ccxt#3374]
- OS: Windows 10
- Lang: JavaScript (Node.js)
- CCXT 1.15.45

I'm finishing the .JS files for 2 brazilian exchanges and I found some problems when implementing the the `api` propriety of an `Exchange` instance.

My Node.js exchange file is:
```js
...
'urls': {
   ...
   'api': 'https://profitfy.trade/api/',
   ...
},
'api': {
   'public':{
      'get':[
         'ticker/{coinfrom}/{cointo}',
         'orderbook/{coinfrom}/{cointo}',
         'trades/{coinfrom}/{cointo}/{tid}'
      ]
   }
}
...
```
The exchange URL for the API that I am trying to implement is the following:`https://profitfy.trade/api/v1/orderbook/{coinfrom}/{cointo}`. When I try running the script, `fetchOrderBook()` tryies to make a request to:

```Error: profitfy GET https://profitfy.trade/api/public/orderbook/BRL/BTC 404```

Notice that it adds a **/public/** at the request. I am trying to get rid of it. I've already tried to remove the `public` propriety, but the API starts to iterate over the strings inside the `get[]` members. 

According to the [documentation](https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties):

>  A public HTTPS GET https://api.exchange.com/market/ticker/{pair} endpoint would result in the corresponding method named .publicGetTickerPair()/.public_get_ticker_pair(), and so on. 

There is no example that reproduces the behavior previously mentioned. I am assuming that the code for the exemple was the following:

```js
...
'urls': {
   ...
   'api': 'https://api.exchange.com/',
   ...
},
'api': {
   'public':{
      'get':[
         '/market/ticker/{pair}',
      ]
   }
}
...
```
The correct behavior of `.publicGetTickerPair()` is a `HTTPS GET https://api.exchange.com/public/market/ticker/{pair}`, adding the **/public/** to the URL.

Am I missing something? Is there a way that I can get rid of the `/public/`? What can I do to access that URL that I mentioned?

**Comment by kroitor** [comment]
Can you post your implementation of the `sign()` method?
