### ISSUE TITLE
bithumb fetchOrder  api missing

### ISSUE THREAD

**Issue by insoochoo** [ccxt/ccxt#3377]
- Programming Language version: js
- CCXT version: newest
- Exchange: BITHUMB
- Method: fetchOrder

**Comment by kroitor** [comment]
@insoochoo your contributions are welcome:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/issues/71

**Comment by kroitor** [comment]
<img width="1505" alt="screen shot 2018-07-12 at 11 37 13" src="https://user-images.githubusercontent.com/1294454/42622012-f24c3540-85c7-11e8-94d3-114b72f43207.png">

**Comment by kroitor** [comment]
In the meantime, you might want to also take a look here: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
