### ISSUE TITLE
wrong percentage

### ISSUE THREAD

**Issue by srfaytkn** [ccxt/ccxt#3378]
- CCXT version:1.15.39
- Exchange: bitfinex, kucoin
- Method: percentage (fetchBalance)

balance change percentage is incorrect. for example bitfinex balance change percentage real value 1.2 but the ccxt value is 0.012.

**Comment by kroitor** [comment]
Sorry, which particular balance change do you mean? We don't return anything like balance change from fetchBalance call.

https://github.com/ccxt/ccxt/wiki/Manual#querying-account-balance

I order to be able to help you, we need your code to reproduce the issue and your verbose request and response (everything usually becomes clear from there):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Let us know if you have more details on this. Feel free to reopen it if needed or just ask further questions, if any.

**Comment by srfaytkn** [comment]
sorry I have written wrong, ticker change percentage is incorrect. for example bitfinex ticker change percentage real value 1.2 but the ccxt value is 0.012.
