### ISSUE TITLE
Bitfinex, Kucoin fetchTickers incorrect percentage

### ISSUE THREAD

**Issue by srfaytkn** [ccxt/ccxt#3379]
CCXT version:1.15.39
Exchange: bitfinex, kucoin
Method: percentage (fetchTickers)
ticker change percentage is incorrect. for example bitfinex ticker change percentage real value 1.2 but the ccxt value is 0.012.

**Comment by kroitor** [comment]
@srfaytkn yet still, we need your code and your verbose output, as was described here: https://github.com/ccxt/ccxt/issues/3378#issuecomment-404441444
If you just go do that, you will probably see everything yourself. Otherwise, just post your code and your verbose output that you suspect as incorrect, here.

**Comment by srfaytkn** [comment]
ccxt:
Bitfinex:
{"symbol":"ETH/USDT","timestamp":1531389546000,"datetime":"2018-07-12T09:59:06.000Z","high":445.590744,"low":429.5,"bid":433.15,"ask":434.073639,"open":443.21133399999997,"close":433.15,"last":433.15,"change":-10.061334,"percentage":-0.0227,"baseVolume":2842.4737387,"quoteVolume":1241553.6294766,"info":{"coinType":"ETH","trading":true,"symbol":"ETH-USDT","lastDealPrice":433.15,"buy":433.15,"sell":434.073639,"change":-10.061334,"coinTypePair":"USDT","sort":100,"feeRate":0.001,"volValue":1241553.6294766,"plus":true,"high":445.590744,"datetime":1531389546000,"vol":2842.4737387,"low":429.5,"changeRate":-0.0227}}

Real:
ETHUSD | 433.27 | -1.3% | 447.13 | 428.00 | 49,129,500 USD

Bittrex:
{"symbol":"ETH/USDT","timestamp":1531389873947,"datetime":"2018-07-12T10:04:33.947Z","high":447.26,"low":429.56,"bid":433.65,"ask":433.9999995,"open":436.563,"close":433.99,"last":433.99,"change":-2.572999999999979,"percentage":-0.5893765619166029,"baseVolume":2040.77896595,"quoteVolume":898361.57661667,"info":{"MarketName":"USDT-ETH","High":447.26,"Low":429.56,"Volume":2040.77896595,"Last":433.99,"BaseVolume":898361.57661667,"TimeStamp":"2018-07-12T10:04:33.947","Bid":433.65,"Ask":433.9999995,"OpenBuyOrders":743,"OpenSellOrders":1297,"PrevDay":436.563,"Created":"2017-04-20T17:26:37.647"}}

Real: 

Ethereum
 433.66000000
LAST
 433.31000000
BID
 433.65999900
ASK
 895769.27000000
VOLUME
 447.26000000
24H HIGH
 429.56000000
24H LOW
Percentage:
-0.8%

bittrex is almost correct but bitfinex is wrong.

**Comment by kroitor** [comment]
This is not how bitfinex output should look like, are you sure that your instances are not screwed up?

```
Bitfinex:
{"symbol":"ETH/USDT","timestamp":1531389546000,"datetime":"2018-07-12T09:59:06.000Z","high":445.590744,"low":429.5,"bid":433.15,"ask":434.073639,"open":443.21133399999997,"close":433.15,"last":433.15,"change":-10.061334,"percentage":-0.0227,"baseVolume":2842.4737387,"quoteVolume":1241553.6294766,"info":{"coinType":"ETH","trading":true,"symbol":"ETH-USDT","lastDealPrice":433.15,"buy":433.15,"sell":434.073639,"change":-10.061334,"coinTypePair":"USDT","sort":100,"feeRate":0.001,"volValue":1241553.6294766,"plus":true,"high":445.590744,"datetime":1531389546000,"vol":2842.4737387,"low":429.5,"changeRate":-0.0227}}
```

↑ This output is not from bitfinex. You're not showing your verbose output. Bitfinex (v1) does not return change at all.

Here's how the correct bitfinex ticker should look like:

```
bitfinex.fetchTicker (ETH/USDT)
{        symbol:   "ETH/USDT",
      timestamp:    1531391035138.687,
       datetime:   "2018-07-12T10:23:55.138Z",
           high:    447.12823584,
            low:    428,
            bid:    430.24,
      bidVolume:    undefined,
            ask:    430.25,
      askVolume:    undefined,
           vwap:    undefined,
           open:    undefined,
          close:    430.25,
           last:    430.25,
  previousClose:    undefined,
         change:    undefined,
     percentage:    undefined,
        average:    430.245,
     baseVolume:    116603.41054484002,
    quoteVolume:    undefined,
           info: {        mid: "430.245",
                          bid: "430.24",
                          ask: "430.25",
                   last_price: "430.25",
                          low: "428.0",
                         high: "447.12823584",
                       volume: "116603.41054484002",
                    timestamp: "1531391035.1386871"  } }
```

Code:

```Python
import ccxt
from pprint import pprint
bitfinex = ccxt.bitfinex({
    'verbose': True ←----- add this
})
pprint(bitfinex.fetch_ticker('ETH/USDT'))
```

So it looks like in your code you have something deeply messed up with instantiation and references to instantiated exchanges, thus when you think you're calling bitfinex fetchTicker, that's some different exchange, not bitfinex.

Unfortunately, I told you two times already and you're not following what I tell you, namely, you're not posting your code to reproduce the issue and not posting the verbose output as was described above.

Hope this helps, let us know if not.

**Comment by kroitor** [comment]
> Bitfinex:
> {"symbol":"ETH/USDT","timestamp":1531389546000,"datetime":"2018-07-12T09:59:06.000Z","high":445.590744,"low":429.5,"bid":433.15,"ask":434.073639,"open":443.21133399999997,"close":433.15,"last":433.15,"change":-10.061334,"percentage":-0.0227,"baseVolume":2842.4737387,"quoteVolume":1241553.6294766,"info":{"coinType":"ETH","trading":true,"symbol":"ETH-USDT","lastDealPrice":433.15,"buy":433.15,"sell":434.073639,"change":-10.061334,"coinTypePair":"USDT","sort":100,"feeRate":0.001,"volValue":1241553.6294766,"plus":true,"high":445.590744,"datetime":1531389546000,"vol":2842.4737387,"low":429.5,"changeRate":-0.0227}}

↑ That actually looks like Kucoin output, not Bitfinex.

**Comment by srfaytkn** [comment]
please check bitfinex v2

**Comment by kroitor** [comment]
<img width="811" alt="screen shot 2018-07-12 at 14 17 17" src="https://user-images.githubusercontent.com/1294454/42630112-552faa1e-85de-11e8-92f6-132647f713c1.png">

↑ This screenshot shows correct values, check your code.

**Comment by kroitor** [comment]
Here's another one, with a better synched timing (shows exactly the same values):

<img width="811" alt="screen shot 2018-07-12 at 14 20 21" src="https://user-images.githubusercontent.com/1294454/42630253-c78ba2ca-85de-11e8-9bfa-96f31cdae1d3.png">

**Comment by kroitor** [comment]
@srfaytkn ok, now I think I got what you're talking about, to clarify: you mean that the orders of those percentage values are different, right? Like 3.49 = 100 x 0.0349. Indeed, it looks like an inconsistency in the library, will do something about it shortly.

**Comment by srfaytkn** [comment]
thank you :)
