### ISSUE TITLE
Bean Cash / Bitbean naming issue.

### ISSUE THREAD

**Issue by tbbw** [ccxt/ccxt#3380]
- OS: All
- Programming Language version: All
- CCXT version: 1.15.45
- Exchange: Bleutrade, Bittrex, Cryptopia, Coinmarketcap, Upbit, Yobit, CoinExchange
- Description:
Bitbeans got renamed to "Bean Cash" instead of "Bitbeans" Source: http://www.bitbean.org/
This has caused some confusion with some exchanges.

Examples:
Bleutrade uses the symbol "BITB" and calls them "Bitbean". https://bleutrade.com/exchange/BITB/BTC
Bittrex uses the symbol "BITB" and calls them "Bitbean" https://bittrex.com/Market/Index?MarketName=BTC-BITB
Cryptopia uses the symbol "BEAN" and calls them "Bean Cash". https://www.cryptopia.co.nz/Exchange?market=BEAN_BTC
Coinmarketcap uses the symbol "BITB" but calls them "Bean Cash" . https://coinmarketcap.com/currencies/bean-cash/
CryptoID has started using the new Symbol and coin name "Bean" and "Bean cash". https://chainz.cryptoid.info/bean/

**Comment by kroitor** [comment]
> CryptoID has started using the new Symbol and coin name "Bean" and "Bean cash". https://chainz.cryptoid.info/bean/

Because we're using CMC as the oracle for symbols, and because CMC still lists it as BITB, we're going to stick to BITB until they change it as well.

**Comment by tbbw** [comment]
Call it what ever as long as there is consistency i'm happy :)
