### ISSUE TITLE
CoinFalcon fetch Order

### ISSUE THREAD

**Issue by markhorner123** [ccxt/ccxt#3382]
Hey

On Coinfalcon there's no fetch order implemented, but it appears in the last 24h or so CoinFalcon have updated their API docs to include the ability to retrieve a specific order by ID. Would it be possible to have this implemented?

https://docs.coinfalcon.com/#get-order

**Comment by kroitor** [comment]
Hi!

> Would it be possible to have this implemented?

Yes )

Your contributions are welcome ;)

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/issues/71 
- https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar
- https://github.com/ccxt/ccxt/issues/3377

<img width="1505" alt="screen shot 2018-07-12 at 11 37 13" src="https://user-images.githubusercontent.com/1294454/42622012-f24c3540-85c7-11e8-94d3-114b72f43207.png">

Let us know if the above does not answer your question.

**Comment by kroitor** [comment]
In the meantime, you might want to also take a look here: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
