### ISSUE TITLE
New Exchange: Neraex

### ISSUE THREAD

**Issue by valentinbora** [ccxt/ccxt#3388]
API Docs: https://neraex.pro/docs/api

Tickers: https://neraex.pro/api/v2/tickers

**Comment by An-Net** [comment]
Shutdown:

- https://www.forexbrokerz.com/reviews/scam-of-neraex_pro-of-japan-and-688ex_com-of-hong-kong

- https://bitcointalk.org/index.php?topic=4563206.0
