### ISSUE TITLE
Deposit with TAG or MEMO?

### ISSUE THREAD

**Issue by springjben** [ccxt/ccxt#3394]
Is there a way to inform my if a TAG or MEMO is needed in order to send a coin?

For example, binance with XRP requires a TAG. If its not sent with a TAG, my despot will be lost.
With STEEM is NEEDS to be sent with a MEMO.

Is there a way to check that is NEEDS to be send with a TAG/MEMO?

**Comment by springjben** [comment]
https://github.com/ccxt/ccxt/wiki/Manual#withdraw

There is a TAG parameter I get that, so that contains the correct characters to be sent?

**Comment by kroitor** [comment]
> Is there a way to check that is NEEDS to be send with a TAG/MEMO?

Currently, nope, but we will add that flag to the `.currencies` property, hopefully soon.

> There is a TAG parameter I get that, so that contains the correct characters to be sent?

Yep, however, you should first check that in verbose mode, as not all exchanges have it unified completely yet. Hope you understand that this library is a work in progress.

Let us know if it does not answer your question.

**Comment by springjben** [comment]
Thank you for replying. 

When I withdraw, sending the tag (whatever it is) isn't a bad thing surely?

Also, how do I check in verbose mode when fetching the deposit? The last thing I want is to send my funds to a blackhole because it needed a tag but didn't have one.

Thanks again!

**Comment by springjben** [comment]
Do I need to check manually whether certain coins need to be sent with a tag or not, incase their API doesn't allow it?

The only exchanges I am using so far are:

Bittrex, Binance, Poloniex, HitBTC and Cryptopia.

**Comment by springjben** [comment]
Wait, is it or isn't it a bad idea to send it the tag??

**Comment by kroitor** [comment]
> Wait, is it or isn't it a bad idea to send it the tag??

It is a good idea to send the tag.

**Comment by springjben** [comment]
Poloniex doesn't have a TAG on certain coins that need it. For example, XRP:

poloniexAPI = ccxt.poloniex ({
    'apiKey': '...',
    'secret': '...',
})

apiCall = api.fetchDepositAddress('XRP')

{'currency': 'XRP', 'address': '...', 'tag': None, 'info': {'BTC': '1AhznvNGqhaFqc8.....

The Binance exchange requests it needs a TAG otherwise deposits will be lost.

**Comment by kroitor** [comment]
@springjben 

> Poloniex doesn't have a TAG on certain coins that need it. For example, XRP:

They just don't return it from their API. But it would be helpful, if you could post your verbose output according to these rules: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue, without your keys of course... If you can, do that, please.

The `withdraw` method still does support the tag anyway.

> The Binance exchange requests it needs a TAG otherwise deposits will be lost.

Right. But if you submit it, you should not lose it.
