### ISSUE TITLE
New Exchange: IDAX

### ISSUE THREAD

**Issue by valentinbora** [ccxt/ccxt#3406]
Official website: https://www.idax.mn/
CMC: https://coinmarketcap.com/exchanges/idax/

I couldn't really find an API reference page, but here are some preliminary findings for fetching tickers:

`curl -s -X POST --data '' https://www.idax.mn/api/Signalr/GetAllOpenMarkets`

**Comment by Legogris** [comment]
API documentation: https://github.com/DigiFinex/api

**Comment by Legogris** [comment]
API documentation: https://github.com/idax-exchange/idax-official-api-docs

**Comment by hbus12** [comment]
This would be nice!

**Comment by kroitor** [comment]
- https://idax.zendesk.com/hc/en-us/articles/360037327571-Urgent-announcement-about-current-situation-of-IDAX-Global
- https://www.coindesk.com/little-known-crypto-exchange-with-ties-to-a-shanghai-firm-halts-services-says-ceo-missing

**Comment by An-Net** [comment]
Scam allegations:

- https://www.globalcryptopress.com/2019/07/idax-exchange-accused-of-stealing.html?=story

- https://bitcointalk.org/index.php?topic=5205272.0

- https://www.change.org/p/shenzhen-financial-regulatory-bureau-we-want-our-funds-back-idax

- https://news.8btc.com/china-based-idax-crypto-exchange-vanishes-with-20-billion-as-capital-strand-breaks
