### ISSUE TITLE
Raspberry PI having trouble with ccxt

### ISSUE THREAD

**Issue by Rkubinski** [ccxt/ccxt#3412]
- OS: Raspberry Debian for Raspberry Pi
- Programming Language version: Python3
- CCXT version: Newest

Did pip3 install ccxt, then when trying to run my script, one of my first lines is:

`import ccxt.async as ccxt`

The error I get when running the code: 

> No Module named ccxt.async

**Comment by kroitor** [comment]
It was renamed to `async_support` recently, due to Python 3.7 update. Let us know if this does not help: https://github.com/ccxt/ccxt/issues/3376

**Comment by Rkubinski** [comment]
@kroitor yes it worked thank you very much
