### ISSUE TITLE
How to best implement Kraken fetchOrderTrades?

### ISSUE THREAD

**Issue by miracle2k** [ccxt/ccxt#3414]
Kraken has an API called QueryTrades: https://www.kraken.com/help/api#query-trades-info

By my experiments, `txid` must be a trade id, and the `trades` parameter seems to have no effect at all. In other words, this API does not allow us to query the trades for a given order id.

However, the "fetch order" api knows the trade ids (but only the ids). So to implement `fetchOrderTrades` we'd have to do:

- Fetch the order
- Use the trade ids with `QueryTrades` to get the trade details.

Is this something we should do? We'd have to do two queries (at least). Also, the user likely already did a `fetchOrder` by themselves already, and now for the trades, another one would happen implicitly.

Alternative options:

- A special parameter for `fetchOrder`, `includeTrades`, which will call the `QueryTrades` API, and the trades would then be included under the `trades`  key (the way Bitstamp includes the trades directly in a fetchOrder response).

- Do not do anything, Kraken-users can just call `QueryTrades` manually.

**Comment by kroitor** [comment]
The general approach is:

- If the exchange in question outputs trades within an order – use them to fill the `trades` property of the order, derive fees, etc...
- If it does not support that in the order API, but offers a standalone fetchOrderTrades endpoint that will output an array of trades by an order id (and a symbol, if required by the exchange).

However, with Kraken QueryTrades, the intent and the meaning of `txid` parameter is to query their trades database by trade ids, something that only makes sense in case you are building a history-retrieving app... Indeed, neither ledger ids nor order ids work for `txid`, just the trade ids.

Also, note that `txid` is actually a *"comma delimited list of transaction ids to query info about (20 maximum)"*, so you can query any set of trades, whether they belong to the same order or to different orders. 

If I were to align it with the CCXT structure, I would add fetchMyTrades with a required `txid` extra param and a proper exception if that param is not set. That would correspond to the functional intent behind QueryTrades which is to fetch your trades (despite that Kraken only does that by trade ids). Does this answer your question?

**Comment by kroitor** [comment]
@miracle2k ok, i'd close this for now, if you don't mind, feel free to reopen it if needed or just ask further questions, will answer asap. Thx!
