### ISSUE TITLE
Cryptopia changed TradePairId's causing cctx to trade wrong pairs

### ISSUE THREAD

**Issue by ildarmgt** [ccxt/ccxt#3421]
- OS: ubuntu 18.04
- Programming Language version: Node
- CCXT version: 1.14.165
- Exchange: cryptopia
- Method: * / api

The api calls suddenly started trading wrong pairs with very detrimental results on account. 

My Node code: I made the calls directly via pair names as strings that in no way included the new coins or pairs that started trading. There have been many months without issues. I do not believe my calls are an issue.

Native cryptopia api: allows to make buy and sell orders via either market symbol of the trade (e.g. 'XMR/BTC') or via TradePairId. 

see: https://support.cryptopia.co.nz/csm?id=kb_article&sys_id=a75703dcdbb9130084ed147a3a9619bc

I believe cctx was placing orders via TradePairId which changed over time on the exchange instead of more precise market symbol of the trade.

It should be changed from using TradePairID to use market symbol of the trade as string and not pair id as randomly changing tradepairid's on exchange back end have devastating effects on algorithms.

I did not provide TradePairID in any manner, thus it must be inferring those from past exchange initialization call.

**Comment by kroitor** [comment]
> My Node code: I made the calls directly via pair names as strings that in no way included the new coins or pairs that started trading. There have been many months without issues. I do not believe my calls are an issue.

That's right, you should have been using CCXT unified symbols, as [described in the Manual](https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids). So if you stick to unified symbols everywhere, there won't be a problem, even if they switch their market ids, because those are loaded and reload in `loadMarkets()` by the user upon starting the app and when needed (also described in the Manual).

> I believe cctx was placing orders via TradePairId which changed over time on the exchange instead of more precise market symbol of the trade.

> The api calls suddenly started trading wrong pairs with very detrimental results on account.

I don't really get how you can run into a problem if you're using unified symbols everywhere, then even the constantly changing TradePairIds should not be a problem. Can you elaborate with code, plz?

**Comment by ildarmgt** [comment]
Standard symbols were used. 

codebase: https://github.com/ildarmgt/arbot

Specifically, for buy orders, from https://github.com/ildarmgt/arbot/blob/master/bot/runBuyOrder.mjs 

```
          await st.lib[job.exchange].createLimitBuyOrder(
            pair,
            buyOrderAmountUnit1,
            buyOrderPrice
          );
```

where `pair` was always a string that could only be equal (in my case) to 'XMR/BTC', 'ETH/BTC', or 'LTC/BTC' while active trades observed on exchange were 'XZC/LTC', 'ETH/LTC', 'XMR/LTC', 'LTC/BTC', 'ETH/BTC' from what seems like several changes to specific id's on back end. No effort was done to make calls by id or even read the market id on my part.

`st.lib[job.exchange]` was variable holding `new ccxt.cryptopia` that also underwent `.load_markets()`

I suspect I might be required to do equivalent to `let reloadedMarkets = await kraken.load_markets (true) // force HTTP reload = true` between every order to avoid this issue.

**Comment by kroitor** [comment]
Ok, so they reused the ids for different pairs? It kinda explains the issue then. Will add a workaround for this, so that createOrder would always use their symbolic pair names, instead of their TradePairIds.
