### ISSUE TITLE
cancelOrder does not work on hitbtc2, binance

### ISSUE THREAD

**Issue by vnikolaich** [ccxt/ccxt#3425]
- OS: windows
- Programming Language version: typescript 2.9.1
- CCXT version: 1.16.36
- Exchange: hitbtc2, binance
- Method: cancelOrder

Hi! There seems to be a bug in cancelOrder by id on hitbtc2.
In responce we receive order with status "open". And order is still active after this.
The same problem is on binance.

verbose info:
fetch:
 hitbtc2 DELETE https://api.hitbtc.com/api/2/order/36488c94a4e2496c8c5878eabb81abe3
Request:
 { Authorization:
   'Basic',
  'Content-Type': 'application/json' }
 undefined

handleRestResponse:
 hitbtc2 DELETE https://api.hitbtc.com/api/2/order/36488c94a4e2496c8c5878eabb81abe3 200 OK
Response:
 { Server: 'nginx',
  Date: 'Fri, 13 Jul 2018 16:11:32 GMT',
  'Content-Type': 'application/json; charset=utf-8',
  'Content-Length': '286',
  Connection: 'close' }
 {"id":"39618408712","clientOrderId":"36488c94a4e2496c8c5878eabb81abe3","symbol":"HVNBTC","side":"buy","status":"new","type":"limit","timeInForce":"GTC","quantity":"120","price":"0.00000304","cumQuantity":"0","createdAt":"2018-07-02T08:24:52.290Z","updatedAt":"2018-07-02T08:24:52.290Z"}

**Comment by mkutny** [comment]
It looks more like hitbtc temporary issue, not ccxt bug. I see that the request is valid but for some reason, hitbtc didn't execute it.

Is the order still open? Can you try one more time? And can you try to cancel it through GUI?


What you say re binance is quite weird too, verbose output is needed.

**Comment by kroitor** [comment]
Indeed, we take the status as is from HitBTC itself, so if it responds with an `"open"` status to a `cancelOrder` call, it means the order is being canceled, but not yet canceled (still open). You have to prepared for this and you have to check the status of the order, and, maybe even issue another fetchOrder call later to actually check if it is closed already or not.

As for Binance, it's hard to tell without verbose request/response and code to reproduce the issue: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Feel free to reopen it or just ask further questions, if any. Will be happy to answer.
