### ISSUE TITLE
Is there a possibility to fetch OHLCV for all symbols at exchange at once?

### ISSUE THREAD

**Issue by viogull** [ccxt/ccxt#3426]
It is mean that if exchange has 300 markets and 1s ratelimit, i must spend as minimum 300 seconds to load OHLCV for all market?

**Comment by kroitor** [comment]
Not really, very few exchanges will allow that. 

> It is mean that if exchange has 300 markets and 1s ratelimit, i must spend as minimum 300 seconds to load OHLCV for all market?

Yes. But you can parallelise that, have 30 computers each issuing a call at 1s ratelimit, thus it will take 10 seconds... 300 computers = 1 second... and so on...
