### ISSUE TITLE
Fcoin market buy order

### ISSUE THREAD

**Issue by Cleric334** [ccxt/ccxt#3427]
Hello. As many other exchanges, Fcoin wants trade volume to be sent in USDT, when trading USDT pairs like BTC/USDT with Market buy orders.

The problem is that when I try to send a 0.001 BTC buy order, I convert it in USDT with trade_volume*ask, which work fine for all the other exchanges, but Fcoin, for some reason sends an 3024 error "4 is greater than maximum order size of 2.0"

There is no way 0.001 BTC * ask price would give 4. 

What could be the problem here?

Thanks in advance.

**Comment by Cleric334** [comment]
createMarketBuyOrder(ticket_1.ticket, TRADE_VOLUME*ticket_1.ask*1.001);

TRADE_VOLUME is my volume in BTC and I multiply it with ask price of the orderbook, and then I factor in the commission. 
This works on other exchanges just fine, but Fcoin thinks I'm sending some rediculous amounts like 4 BTC.

Limit orders work fine, since they don't require sending in the volume in USDT

**Comment by mkutny** [comment]
Ok, I've got an account there and am able to reproduce.

Actually, I see several issues here.

#### 1) Error messages are misleading (this is exchange issue, not ccxt issue).

Here I assume here that the result of `TRADE_VOLUME*ticket_1.ask*1.001` is somewhat around 7.

```
> node examples/js/cli.js fcoin createMarketBuyOrder 7
fcoin.createMarketBuyOrder (BTC/USDT, 7)
InsufficientFunds fcoin {"status":1016,"msg":"account balance insufficient"}
```

```
> node examples/js/cli.js fcoin createMarketBuyOrder 7.1
fcoin.createMarketBuyOrder (BTC/USDT, 7.1)
InsufficientFunds fcoin {"status":1016,"msg":"account balance insufficient"}
```

```
> node examples/js/cli.js fcoin createMarketBuyOrder 7.11
fcoin.createMarketBuyOrder (BTC/USDT, 7.11)
InsufficientFunds fcoin {"status":1016,"msg":"account balance insufficient"}
```

```
> node examples/js/cli.js fcoin createMarketBuyOrder 7.111
fcoin.createMarketBuyOrder (BTC/USDT, 7.111)
ExchangeError fcoin {"status":3012,"msg":"3 is greater than the max order amount 2.0"}
```

```
> node examples/js/cli.js fcoin createMarketBuyOrder 7.1111
fcoin.createMarketBuyOrder (BTC/USDT, 7.1111)
[ExchangeError] fcoin {"status":3012,"msg":"4 is greater than the max order amount 2.0"}
```

I guess they mean that the precision of amount should be 2.


#### 2) This error is misleading too but I'm not sure how to interpret it:

```
> node examples/js/cli.js fcoin createMarketBuyOrder 4.1111
fcoin.createMarketBuyOrder (BTC/USDT, 4.1111)
ExchangeError fcoin {"status":3014,"msg":"4.1111 is less than the min market buy order amount 5"}
```

Curious what this `5` would mean.


#### 3) You say that "Fcoin wants trade volume to be sent in USDT, when trading USDT pairs like BTC/USDT with Market buy orders".

How do you know this? It's not obvious from reading their docs.

Disregarding of the answer look at the signature of the call:
https://github.com/ccxt/ccxt/blob/b92d5a5dace5dee849a3e09ae8a0d10d42ab0306/js/base/Exchange.js#L1065-L1067

Even if you put 'cost' as the first param (i.e. 'volume * price'), ccxt still sends it as an amount (that's why I asked for a verbose output):
```
> node examples/js/cli.js fcoin createMarketBuyOrder BTC/USDT 4.1111 --verbose
...
fetch:
 fcoin POST https://api.fcoin.com/v2/orders 
Request:
...
 {"amount":4.1111,"side":"buy","symbol":"btcusdt","type":"market"} 
```

I guess someone needs to play with different params to reverse-engineer how it should work with market orders.

**Comment by kroitor** [comment]
> I guess they mean that the precision of amount should be 2.

Yeah, it looks like so...

> Curious what this 5 would mean.

I guess, they mean min order cost of 5 USDT here.

> How do you know this? It's not obvious from reading their docs.

+1 for this question, not obvious at all.

**Comment by mkutny** [comment]
>> Curious what this 5 would mean.

> I guess, they mean min order cost of 5 USDT here (just a guess).

You know, you're right. I just didn't play enough with various combinations.

So your guess completes the puzzle: for a market order, they indeed treat `amount` param as `cost`. The `price` param is ignored:

```
> node examples/js/cli.js fcoin createMarketBuyOrder BTC/USDT 4 2
fcoin.createMarketBuyOrder (BTC/USDT, 4, 2)
ExchangeError fcoin {"status":3014,"msg":"4 is less than the min market buy order amount 5"}
```

```
> node examples/js/cli.js fcoin createLimitBuyOrder BTC/USDT 4 2
fcoin.createLimitBuyOrder (BTC/USDT, 4, 2)
InsufficientFunds fcoin {"status":1016,"msg":"account balance insufficient"}
```



> As many other exchanges, Fcoin wants trade volume to be sent in USDT, when trading USDT pairs like BTC/USDT with Market buy orders

Now I wonder if this is indeed a widespread approach to market orders? Because it's quite orthogonal to the the way market orders are implemented in unified API.

**Comment by kroitor** [comment]
> Now I wonder if this is indeed a widespread approach to market orders? 

Not really a widespread approach. But yeah, we have a few exchanges that behave that way (they are the minority though). I'd say, it's common to asian exchanges, though I don't think this is a good approach. 

Namely, these exchanges:
- indodax
- fcoin
- cointiger
- huobipro (has practically the same API as huobipro, except different method names)
- cex
- btcturk
- okcoinusd, okex

Also, like the above is not enough, in most cases that is applicable to **market buy** orders only, market-sells require an amount in base currency.

> But it would be nice if we have a per-exchange flag which says if the second param to createMarketOrder is expected to be amount or cost.

We usually approach it differently: overloading `price` argument with `cost` value in `createOrder` will definitely make much more trouble than asking for both `price` and `amount` and calculating `cost` from there.

Example: https://github.com/ccxt/ccxt/blob/master/js/huobipro.js#L642

**Comment by mkutny** [comment]
> Also, like the above is not enough, in most cases that is applicable to market buy orders only, market-sells require an amount in base currency.

Ah, yeah, this does make sense, indeed. With this approach, you're concerned with the quantity to spend disregarding of the trade direction. So you're spending quote to buy, base to sell. Just didn't think about the sell side at all.


> We usually approach it differently: overloading price argument with `cost` value in `createOrder` will definitely make much more trouble than asking for both `price` and `amount` and calculating cost from there.

I didn't mean to overload the `price`, I meant to overload the `amount`. Nevertheless, requiring the `price` is much more unified than the proposed flag. Obviously.

Thanks for clearing things up!

**Comment by Cleric334** [comment]
I can confirm that the sell side works fine everywhere. 

So, anyone have any idea how could I actually use fcoin's market buy? Should I try to send the amount in USDT, but round it down to the whole number?

**Comment by kroitor** [comment]
> So, anyone have any idea how could I actually use fcoin's market buy? Should I try to send the amount in USDT, but round it down to the whole number?

Nope. Instead you should round it to two decimals and make sure it's greater than 5, explained here:
- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

Their USDT currency has precision of 2 and a limit of 5.00.

```
mbp:ccxt igorkroitor$ node examples/js/symbols.js fcoin --debug
Instantiating fcoin exchange
{     limits: { amount: { min: 0.001, max: 1000 },
                 price: { min: 0.01, max: 100 }    },
   precision: { price: 2, amount: 4 },
   tierBased:    false,
  percentage:    true,
       taker:    0.001,
       maker:    0.001,
          id:   "btcusdt",
      symbol:   "BTC/USDT",
        base:   "BTC",
       quote:   "USDT",
      baseId:   "btc",
     quoteId:   "usdt",
      active:    true,
        info: {           name: "btcusdt",
                 base_currency: "btc",
                quote_currency: "usdt",
                 price_decimal:  2,
                amount_decimal:  4         }          }
```

We will add a workaround for fcoin market buys shortly.
