### ISSUE TITLE
Lbank Exchange Withdraw Feature

### ISSUE THREAD

**Issue by ghost** [ccxt/ccxt#3434]
- Programming Language version: Python
- CCXT version: Latest
- Exchange: Lbank
- Method: Withdraw

https://github.com/LBank-exchange/lbank-official-api-docs/blob/master/API-For-Spot-CN/币币交易REST%20API(交易).md
Lbank lately implemented withdraw feature(the link above). There are two new methods 
`GET http://api.lbank.info/v1/withdrawConfigs.do` and 
`POST http://api.lbank.info/v1/withdraw.do`. Could you implement this?

**Comment by ttodua** [comment]
Both of them have been implemented. Users can look into [`lbank2`](https://github.com/ccxt/ccxt/blob/master/js/lbank2.js)
