### ISSUE TITLE
php okex error on fetch_tickers

### ISSUE THREAD

**Issue by kasus** [ccxt/ccxt#3436]
- OS: mac os x 10.13.5
- Programming Language version: php
- CCXT version: 1.16.67
- Exchange: okex
- Method: fetch_tickers

There is an error because options array has only method described in camelCase, but method in underscore notation only exists.

```
ccxt\ExchangeError: fetchTickersFromApi method not found, try underscore_notation instead of camelCase for the method being called in /vendor/ccxt/ccxt/php/Exchange.php:1851
```

**Comment by kroitor** [comment]
Fixed in 1.16.69. Thx for reporting!
