### ISSUE TITLE
FCoin daily timestamps have inconsistent time scales

### ISSUE THREAD

**Issue by nathankjer** [ccxt/ccxt#3440]
- OS: Mac OS X
- Programming Language version: Python 3.6.5
- CCXT version: 1.16.71
- Exchange: fcoin
- Method: fcoin.fetch_ohlcv("BTC/USDT",timeframe=1d)

FCoin's timestamps are as high as 14545707100000 and as low as 4198217200000. Not sure what's going on here.

**Comment by kroitor** [comment]
Well-well... Maybe, they just had a long working day? ) Or... maybe... just maybe... they're located somewhere beyond the arctic circle, where days can last for 6 months, you know... Actually, it was the `seq` number, not the timestamp, looks like the timestamp in seconds is the `id` field in their candle structure. Added a fix for it, will be available for downloading in 5-10 minutes.
