### ISSUE TITLE
Why loadFees return differs with and without API keys?

### ISSUE THREAD

**Issue by fonzmeister** [ccxt/ccxt#3443]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version: python
- CCXT version: 1.16.57
- Exchange: Binance
- Method: loadFees()

I run into this on Binance, might be the same for other exchanges though. But the output of the loadfees method on binance is different if you supply an apiKey. I understand that the fees might change with the volume you trade, but the amount of coins returned is different as well.
For example the coin AGI is not returned if you do binance.loadFees(), but is if you do binance.loadFees(APIKEY, SECRETKEY). Why is this? 

```
a = binanceWithApiKey.loadFees()
b= binanceWithoutApiKey.loadFees()
len(a['funding']['withdraw'].keys()) #output is 151
len(b['funding']['withdraw'].keys()) #output is 109

```

**Comment by kroitor** [comment]
Hi! Sorry for a long wait... this is because your actual personal fees may differ from the common fees, depending on your trading volume and other factors. CCXT will load those fees where possible, however, this is not completely unified yet. Hope this answers your question. Let us know if not.
