### ISSUE TITLE
New exchange: HBUS

### ISSUE THREAD

**Issue by procloud** [ccxt/ccxt#3445]
website: hbus.com
api docs: https://hbus.readme.io/

**Comment by kroitor** [comment]
JFYI, it's basically a Huobi/CoinTiger clone.

**Comment by clu8** [comment]
HBUS has now rebranded to Huobi:  https://www.huobi.com/
Meanwhile, the current exchange ID `huobipro` for Huobi Pro is HBG: https://www.hbg.com/

**Comment by kroitor** [comment]
@clu8 thx for the update, we will add the necessary edits on our side!

**Comment by clu8** [comment]
It looks like the two exchanges share liquidity. Not sure if API keys from Huobi (HBUS) can be used with the existing code--will test when I get a chance.

**Comment by newsum** [comment]
any update on this?

**Comment by kroitor** [comment]
@newsum nope, not yet, but we hope we will have a chance to look into it asap.

**Comment by spmcelrath** [comment]
Would also like to see HBUS support on CCXT. Any updates?

**Comment by kroitor** [comment]
https://twitter.com/HBUSofficial/status/1203894768561901568

> HBUS Cease to Operate: We regret to inform you that HBUS will need to cease operations so that it can return in a more integrated and impactful fashion as part of its ongoing strategic layout. Please refer to our FAQ and contact support@hbus.com

**Comment by kroitor** [comment]
https://twitter.com/HBUSofficial/status/1203894768561901568

> HBUS Cease to Operate: We regret to inform you that HBUS will need to cease operations so that it can return in a more integrated and impactful fashion as part of its ongoing strategic layout. Please refer to our FAQ and contact support@hbus.com
