### ISSUE TITLE
for nodejs, ccxt can export all class of base, make it easy for developers to extend.

### ISSUE THREAD

**Issue by arden** [ccxt/ccxt#3448]
for nodejs, ccxt can export all class of base, make it easy for developers to extend.

**Comment by kroitor** [comment]
@arden sorry? Have you read this: https://github.com/ccxt/ccxt/wiki/Manual? I didn't really get your question / proposal, to be honest... All classes are exported from the ccxt lib namespace, including the exchanges and the base Exchange class. See how this is linked against in the source of any of the exchange files. Hope this answers your question.
