### ISSUE TITLE
Javascript, Failed to execute 'fetch' on 'Window': Illegal invocation

### ISSUE THREAD

**Issue by santos-sabanari** [ccxt/ccxt#3450]
- OS: Windows 10
- Programming Language version: Javascript
- CCXT version:  1.16.78
- Exchange: Indodax
- Method: fetchticker

Screenshot
http://prntscr.com/k9503i

Error while using fetchticker

Thank You

**Comment by kroitor** [comment]
@santos-sabanari this has been broken a bit here: https://github.com/ccxt/ccxt/issues/3439, i've uploaded a fix for it, will be available in 5-10 minutes, just refresh your browser window. Thx for reporting!
