### ISSUE TITLE
Incorrect precision data in markets object. amountToPrecision(), amountToLots() not working correctly.

### ISSUE THREAD

**Issue by azharuniverse** [ccxt/ccxt#3452]
`this.markets[formatPair(order.coin)].lot` returns incorrect lot size. 
(Eg. For DBC/BTC precision is 4 it returns 8)
`this.currencies[getCoinFromPair(order.coin)].precision` returns correct precision. (Eg:DBC/BTC - 4)

Suggested line of code to debug the issue /ccxt/js/kucoin.js -

```
390: let precision = {
                'amount': 8,
                'price': 8,
393:           };
```

- OS: ALL
- Programming Language version: NODE v8.9.4
- CCXT version: 1.16.36
- Exchange: KUCOIN
- Method: amountToLots()

**Comment by kroitor** [comment]
`market.lot` and amountToLots are deprecated. We are using the `precision` and we are moving to decimalToPrecision instead. Hope this answers your question.
