### ISSUE TITLE
binance.fetchDepositAddres() throws an exception for "BCC" but works with "BCH"

### ISSUE THREAD

**Issue by merklegroot** [ccxt/ccxt#3453]
- OS: Windows 10
- Programming Language version: Node.JS 10.6.0
- CCXT version: 1.16.80
- Exchange: Binance
- Method: fetchDepositAddress('BCC')

Summary: binance.fetchDepositAddres() throws an exception for "BCC" but works with "BCH"

Description:
  When I attempt to get the deposit address for Bitcoin Cash using code "BCC", it throws an exception (see bottom).
If I use "BCH", it works.
On Binance, the code for Bitcoin Cash is BCC.

Workaround:
  This works fine if I pass it BCH. 
However, I expect that means I'll eventually have to adapt the code that calls this method when the issue is corrected.

Related Issues:
  https://github.com/ccxt/ccxt/pull/539
  https://github.com/ccxt/ccxt/issues/402

Exception:
{ Error: binance does not have currency code BCC
    at binance.currency (C:\repo\trade-node\node_modules\ccxt\js\base\Exchange.js:763:15)
    at binance.fetchDepositAddress (C:\repo\trade-node\node_modules\ccxt\js\binance.js:807:29)
    at process._tickCallback (internal/process/next_tick.js:68:7) constructor: [Function: ExchangeError] }

**Comment by kroitor** [comment]
> On Binance, the code for Bitcoin Cash is BCC.

In ccxt Bitcoin Cash has code BCH everywhere, as described in the Manual: 

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
- https://github.com/ccxt/ccxt/wiki/Manual#naming-consistency

> However, I expect that means I'll eventually have to adapt the code that calls this method when the issue is corrected.

This isn't an issue, you should just stick to `BCH`:

- https://github.com/ccxt/ccxt/issues/83
- https://github.com/ccxt/ccxt/issues/129
