### ISSUE TITLE
Bittrex / python fetch_orders() method gone ..?

### ISSUE THREAD

**Issue by skeebuzz** [ccxt/ccxt#3455]
Language: Python 3.6
CCXT version: 1.12+ (including newest version 1.16.80)
Exchange: Bittrex

The fetch_orders method for Bittrex seems to have disappeared at some point after v1.11.180 (I tried to upgrade). Seems like a pretty important method for a fairly well-used exchange...

**Comment by kroitor** [comment]
@skeebuzz they didn't have it from the very beginning, the old `fetchOrders` was only returning closed orders, so it was removed in favor of `fetchClosedOrders`. Bittrex has fetchOpenOrders and fetchClosedOrders, and the `has` property, according to the Manual. Hope this answers your question.

**Comment by skeebuzz** [comment]
Damn that was fast, and it's Saturday... Thanks very much. You've just earned this project an ETH tip.

Cheers
