### ISSUE TITLE
Huobi Pro BAT invalid amount

### ISSUE THREAD

**Issue by zn8ae** [ccxt/ccxt#3457]
- OS: Mac OSX
- Programming Language version: Python 3
- CCXT version: 1.16.85
- Exchange: Huobi Pro
- Method: createMarketOrder

Hi, I was trying to use Huobi Pro to make a market order for symbol 'BAT/BTC'. I turned off the 'createMarketBuyOrderRequiresPrice' option and tried to buy 10 BAT using BTC. However, the function gives an error saying my amount is invalid. 

I then checked the market info, I noticed that for Huobi Pro's market, symbol 'BAT/BTC', the limit amount is incorrect:

'limits': {'amount': {'max': 1.0, 'min': 1.0}

I believe the amount limit prevents any order from happening... Please help me check. 

I was trying to make an order like this:
huobi.create_market_buy_order('BAT/BTC', 10 * market_price)

Thanks!

**Comment by kroitor** [comment]
@zn8ae use `.fetchTradingLimits ()` and `.loadTradingLimits ()` before accessing the limit values and before placing the orders:

```JavaScript
mbp:ccxt igorkroitor$ node examples/js/cli huobipro fetchTradingLimits '["BAT/BTC"]'
huobipro.fetchTradingLimits (BAT/BTC)
{ limits: { 'BAT/BTC': { amount: { min: 1, max: 5000000 } } },
    info: { 'BAT/BTC': { status:   "ok",
                           data: {                                  symbol: "batbtc",
                                                'buy-limit-must-less-than':  1.1,
                                            'sell-limit-must-greater-than':  0.9,
                                           'limit-order-must-greater-than':  1,
                                              'limit-order-must-less-than':  5000000,
                                      'market-buy-order-must-greater-than':  0.0001,
                                         'market-buy-order-must-less-than':  100,
                                     'market-sell-order-must-greater-than':  1,
                                        'market-sell-order-must-less-than':  500000,
                                         'circuit-break-when-greater-than':  10000,
                                            'circuit-break-when-less-than':  10,
                                   'market-sell-order-rate-must-less-than':  0.1,
                                    'market-buy-order-rate-must-less-than':  0.1      } } } }
```

```Python
from pprint import pprint
symbols = [
    'BAT/BTC',
    # ...
]
exchange.load_trading_limits (symbols)
pprint(exchange.markets['BAT/BTC']['limits'])
```

Let us know if the above does not help or does not answer your question.
