### ISSUE TITLE
Bigone invalid nonce

### ISSUE THREAD

**Issue by Cleric334** [ccxt/ccxt#3458]
Hi all.

I am getting the following error from Bigone when I try to create an order :

{""errors"":[{""message"":""invalid nonce, nonce should be a 19bits number"",""code"":10030}],

I was unable to find this error in their API docs or the ccxt file.

And here is another one without a code 

{""errors"":[{""message"":""Argument \""input\"" has invalid value {marketUuid: $market_id, price: $price, amount: $amount, side: $side}.\nIn field \""marketUuid\"": Expected type \""String!\"", found $market_id.\nIn field \""side\"": Expected type \""OrderSide!\"", found $side."",""locations"":[]},{""message"":""Variable \""market_id\"": Expected non-null, found null."",""locations"":[{""line"":1,""column"":0}]},{""message"":""Variable \""side\"": Expected non-null, found null."",""locations"":[{""line"":1,""column"":0}]}],""data"":null}"

I am using the same calls and the same parameters as with every other exchange.

**Comment by kroitor** [comment]
@Cleric334 can you show the smallest possible, but a complete working snippet of code to reproduce the issue with the first error? I mean, make it a short but runnable program, so that we could debug it, starting from the library import, including the instantiation, and order creation code, without your keys... 

Basically for whatever issue you have you should post this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue. Can't cut the corner here ) You should already get used to it, as we ask for code and output most of the time, and this is not the first time you're asking a question or reporting an issue (thanks for reporting, btw!). We can skip this prelude next time, if you just post code and output form the very beginning, in the starting post )

**Comment by Cleric334** [comment]
Thanks for your reply.
The thing is, I am not a programmer, and I use the code written by somebody else. Most of that code works just fine with most of ccxt's exchanges, but sometimes, especially for new exchanges, I would get different errors. 

So, it's nearly impossible for me to provide anything more than error responses I get in my log.  I do what I can, and if I could do I more I would. Feel free to delete my messages if they are too spammy or useless. Otherwise, I hope I can at least point to the direction in which the competent among you could dig in order to make ccxt better.

**Comment by kroitor** [comment]
@Cleric334 ok, no worries, I'll look into it and will get back to you on this issue. Will need some time to test for it extensively.

**Comment by karlandoh** [comment]
Hello, 

Also confirming that this issue is still existent.

Thanks.

**Comment by kroitor** [comment]
@karlandoh can you post a short but complete snippet of code to reproduce it here? 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

**Comment by karlandoh** [comment]
bigone.fetchBalance()

```
Request: GET https://big.one/api/v2/viewer/accounts {'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiT3BlbkFQSSIsInN1YiI6ImVlYzA2NTNiLWQ4OTUtNDJiZi05NDFlLWVmZGEyMTczOGM2NyIsIm5vbmNlIjoxNTM3MzkwODI3MDAwMDAwMDAwfQ.eCOKiyXGIEf2Nlc5UsgWAJWYrsQuhGgXMz6iyr3AEKw', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://big.one/api/v2/viewer/accounts 200 {'Date': 'Wed, 19 Sep 2018 17:00:15 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d5075a16c576c5570a6c9a4176c257ebc1537376415; expires=Thu, 19-Sep-19 17:00:15 GMT; path=/; domain=.big.one; HttpOnly; Secure', 'cache-control': 'max-age=0, private, must-revalidate', 'x-request-id': '2latnd3bbhe1fmj5dk080hkt', 'Via': '1.1 google', 'Alt-Svc': 'clear', 'Strict-Transport-Security': 'max-age=2592000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '45cd9b85de96ab96-YYZ', 'Content-Encoding': 'gzip'} {"errors":[{"message":"invalid nonce, nonce should be a 19bits number","code":10030}],"data":null}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/ccxt/bigone.py", line 337, in fetch_balance
    response = self.privateGetAccounts(params)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 362, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 359, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 457, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, None, http_response)
  File "/usr/local/lib/python3.7/site-packages/ccxt/bigone.py", line 642, in handle_errors
    raise ExchangeError(feedback)
ccxt.base.errors.ExchangeError: bigone {"errors":[{"message":"invalid nonce, nonce should be a 19bits number","code":10030}],"data":null}
```

Language: Python
Version: 1.17.320
