### ISSUE TITLE
Option to set .options['createMarketBuyOrderRequiresPrice'] = false

### ISSUE THREAD

**Issue by azharuniverse** [ccxt/ccxt#3460]
Just like huobipro & coinex having same requirement in Market Buy order.

`For market buy orders cex requires the amount of quote currency to spend, to calculate proper costs call createOrder (symbol, 'market', 'buy', amount, price)`

we should be able to disable it and pass amount = amount * price manually using
`.options['createMarketBuyOrderRequiresPrice'] = false`

- OS: ALL
- Programming Language version: NODE v8.9.4
- CCXT version: 1.16.36
- Exchange: CEX.IO
- Method: marketBuy()

**Comment by azharuniverse** [comment]
I would call it a bug because currently there is no possible way of placing a marketBuy order on cex.io using createMarketBuyOrder() function. I understand that I can use createOrder() function. but that defeats the advantage of unification we get from CCXT. I use multiple exchanges and I don't wish to call a different function for all exchanges. 
Please have support for `.options['createMarketBuyOrderRequiresPrice'] = false`

**Comment by kroitor** [comment]
It's really time-consuming to explain, why this isn't a bug and why adding this option or having the support for **cost** in the **amount** argument would lead to even more bugs that you would *"fix"* that way. I tried to explain the reasoning behind it here: https://github.com/ccxt/ccxt/issues/3427
So, it's easier for me to actually add the feature you requested, but we warned you ;)

**Comment by azharuniverse** [comment]
Support for this option has been a great relief for me. 
I have created a wrapper function for createMarketBuy() to handle this issue.

`MARKET_BUY_WPRICE: ['huobipro', 'coinex', 'okex']`

```
const currentPrice = exchanges[order.exchange].getMarketSummary(order.coin).Ask; //only for history log
    let additionalParams = {};
    if(CONSTANTS.MARKET_BUY_WPRICE.includes(userExchange.id)) {
        order.order_volume = order.order_volume * currentPrice;
        userExchange.options['createMarketBuyOrderRequiresPrice'] = false;
        userExchange.options['marketBuyPrice'] = false; 
        additionalParams['cost'] = order.order_volume; 
        order.order_volume = adjustPricePrecision.call(this, userExchange, order);
    }
    else {
        order.order_volume = adjustAmountPrecision.call(this, userExchange, order);
    }

    userExchange.createMarketBuyOrder(
        symbol = formatPair(order.coin), //symbol:
        amount = order.order_volume, //amount:
        params = additionalParams //cost
    )
   .then(response => { }
   .catch(e){}
```
