### ISSUE TITLE
Livecoin currency code vs symbol inconsistency

### ISSUE THREAD

**Issue by phantomaslord** [ccxt/ccxt#3463]
Hi there, I found some pair and currency names incosistency during working with Livecoin exchange.

- OS: Windows 7
- Programming Language version: python 3.5.3
- CCXT version: 1.16.86
- Exchange: Livecoin, CoinMarketCap

I do following:

```Python
exch = ccxt.livecoin()
exch.apiKey = API_KEY
exch.secret = SECRET
markets = exch.load_markets()
balances = exch.fetch_balance()
tickers = exch.fetch_tickers()
currencies = exch.fetch_currencies()
```

And then perform checking:

```Python
damaged_pairs = []
for i in markets:
    cur = markets[i]['base']; pair = markets[i]['symbol']
    if ((cur not in balances) or (cur not in currencies) or (pair not in tickers)):
        damaged_pairs.append(pair)
```
So list of damaged pairs is

['VEN/BTC', 'ORE/BTC', 'BTCH/BTC', 'SCT/BTC', 'EDR/BTC', 'FirstBlood/BTC', 'CPC/BTC', 'eETT/BTC', 'TPI/BTC', 'wETT/BTC', 'CRC/BTC', 'MTCoin/BTC', 'FORTYTWO/BTC', 'XBT/BTC']

If I change keys 'base' to 'baseId' and 'symbol' to 'id' I get the same list.

If I try to compare Livecoin pair names with Coinmarketcap:

```Python
ref = ccxt.coinmarketcap()
stat = ref.fetch_currencies()

damaged_pairs = []
for i in markets:
    cur = markets[i]['base']; pair = markets[i]['symbol']
    if ((cur not in balances) or (cur not in currencies) or (pair not in tickers) or (cur not in stat)):
        damaged_pairs.append(pair)
```

I get following inconsistency pairs:

['MTCoin/BTC', 'XMS/BTC', 'ECIO/BTC', 'PELO/BTC', 'FNC/BTC', 'PIN/BTC', 'DANC/BTC', 'FU/BTC', 'BPC/BTC', 'HB/BTC', 'PISH/BTC', 'OD/BTC', 'ECHO/BTC', 'FORTYTWO/BTC', 'NAM/BTC', 'wETT/BTC', 'CNB/BTC', 'IFAN/BTC', 'SHPING/BTC', 'GOAL/BTC', 'TPI/BTC', 'FLOT/BTC', 'EURN/BTC', 'CBR/BTC', 'SPA/BTC', 'RST/BTC', 'ETHP/BTC', 'ELI/BTC', 'eETT/BTC', 'KAPU/BTC', 'BPTN/BTC', 'RTB/BTC', 'SCT/BTC', 'VIEW/BTC', 'XBT/BTC', 'MTRc/BTC', 'CRBIT/BTC', 'CPC/BTC', 'NOKU/BTC', 'GYC/BTC', 'JOY/BTC', 'EDR/BTC', 'ORE/BTC', 'RBM/BTC', 'CARB/BTC', 'ESR/BTC', 'ADL/BTC', 'ARTE/BTC', 'PLN/BTC', 'BTCH/BTC', 'MCR/BTC', 'HNR/BTC', 'KPL/BTC', 'SKCH/BTC', 'TWC/BTC', 'LTT/BTC', 'UNC/BTC', 'THS/BTC', 'MRP/BTC', 'CLPC/BTC', 'FirstBlood/BTC', 'CRC/BTC', 'VEN/BTC']

Hope you will help.
Thank you for great work on this amazing library.

**Comment by kroitor** [comment]
First of all, let's clarify the initial section of the code:


```
    #  ↓ can be missing in balances, so this isn't a correct check, and there's no "damage"
    #  ↓                                        ↓ this check should always yield true, so it is not needed
    #                                                                    if not in tickers ↓ the pair may be missing in tickers as well
    if ((cur not in balances) or (cur not in currencies) or (pair not in tickers)):
        damaged_pairs.append(pair)
```

So, I don't really get the logic behind this check, can you clarify, why do you suppose that those pairs are "damaged" ? Asking this, because neither of the above conditions indicate a "damage"... or, I don't get the meaning behind that collection name within the above two lines. Need more comments from you.

You verbose output would be helpful: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by phantomaslord** [comment]
Ok, may be my explonation isn't clear or may be I miss something, but let's see it on example. After executing my code I have variables 'markets', 'balances', 'tickers' and 'currencies'. Let's take the 'CRC/BTC' pair. It's represented in 'markets' like this:

>>> markets['CRC/BTC']
{'baseId': 'CRC', 'limits': {'amount': {'min': 4.0354, 'max': 100000000.0}, 'price': {'min': 1e-08, 'max': 100000000.0}}, 'quote': 'BTC', 'id': 'CRC/BTC', 'symbol': 'CRC/BTC', 'active': True, 'precision': {'amount': 8, 'price': 8, 'cost': 8}, 'tierBased': False, 'fee_loaded': False, 'info': {'low': 2.6e-05, 'vwap': 2.601e-05, 'volume': 608.26009803, 'cur': 'CRC', 'min_ask': 2.6e-05, 'high': 2.602e-05, 'max_bid': 2.603e-05, 'symbol': 'CRC/BTC', 'best_bid': 2.603e-05, 'best_ask': 2.75e-05, 'last': 2.602e-05}, 'quoteId': 'BTC', 'base': 'CryCash', 'percentage': True, 'maker': 0.0018, 'taker': 0.0018}

So 'base' is 'CryCash', 'baseId' is 'CRC', 'symbol' is 'CRC/BTC' and 'id' is 'CRC/BTC'. Now I want to see balance, ticker and currency iformation for it. In this example the problem is in different keys for 'balances' and 'currencies' dictionaries.

>>> balances['CRC']
{'free': 0.0, 'total': 0.0, 'used': 0.0}
>>> tickers['CRC/BTC']
{'bid': 2.603e-05, 'askVolume': None, 'high': 2.602e-05, 'timestamp': 1532357616492, 'symbol': 'CRC/BTC', 'vwap': 2.601e-05, 'bidVolume': None, 'info': {'low': 2.6e-05, 'vwap': 2.601e-05, 'volume': 608.26009803, 'cur': 'CRC', 'min_ask': 2.6e-05, 'high': 2.602e-05, 'max_bid': 2.603e-05, 'symbol': 'CRC/BTC', 'best_bid': 2.603e-05, 'best_ask': 2.75e-05, 'last': 2.602e-05}, 'baseVolume': 608.26009803, 'average': None, 'low': 2.6e-05, 'percentage': None, 'change': None, 'last': 2.602e-05, 'datetime': '2018-07-23T14:53:36.492Z', 'quoteVolume': 0.0158208451497603, 'open': None, 'previousClose': None, 'ask': 2.75e-05, 'close': 2.602e-05}
>>> currencies['CRC']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'CRC'

but

>>> currencies['CryCash']
{'active': True, 'fee': 161, 'name': 'CryCash', 'code': 'CryCash', 'precision': 8, 'id': 'CRC', 'limits': {'amount': {'min': 4.0354, 'max': 100000000.0}, 'withdraw': {'min': 0.01, 'max': 100000000.0}, 'deposit': {'min': 0, 'max': None}, 'price': {'min': 1e-08, 'max': 100000000.0}, 'cost': {'min': 4.0354, 'max': None}}, 'info': {'minWithdrawAmount': 0.01, 'difficulty': None, 'name': 'CryCash', 'minOrderAmount': 4.0354, 'walletStatus': 'normal', 'symbol': 'CRC', 'minDepositAmount': 0, 'withdrawFee': 161}}

Why it's needed to use 'CRC' in 'balances', but 'CryCash' in 'currencies'? I read 'Symbols And Market Ids' section of Manual about naming consistency and supposed that keys for currencies within at least one exchange must be the same. But first running of my program showed that it's not true so special check was introduced. I roughly called pairs that have such inconsistency 'damaged_pairs'.

    #  ↓ can be missing in balances, so this isn't a correct check, and there's no "damage"
    #  ↓                               ↓ this check should always yield true, so it is not needed
    #  ↓                               ↓                         ↓ the pair may be legally missing in tickers as well
    if ((cur not in balances) or (cur not in currencies) or (pair not in tickers)):
        damaged_pairs.append(pair)

I take currencies from 'markets' so, I suppose, they cannot be missing in 'balances', 'tickers' or 'currencies'. It's hard to imagine that market of any currency is present but balance, ticker or info are absent. May be you are right and 'cur' is aways in 'currencies' so condition is not needed but it's not obviously.

I'm sorry but verbose output contains my private information (oders, balances, api-key etc).

Thank you very much for your reply.

**Comment by kroitor** [comment]
> So 'base' is 'CryCash', 'baseId' is 'CRC', 'symbol' is 'CRC/BTC' and 'id' is 'CRC/BTC'. Now I want to see balance, ticker and currency iformation for it. In this example the problem is in different keys for 'balances' and 'currencies' dictionaries.

Yep, that's definitely an inconsistency in the library, thanks for your clarifications! Will fix the ones you pointed out as soon as possible. Thx again!

**Comment by phantomaslord** [comment]
Good news) thank you!

May I expect that there will be consistency with the CoinMarketCap too?
