### ISSUE TITLE
OpenSSL.SSL.WantReadError

### ISSUE THREAD

**Issue by brucewong0516** [ccxt/ccxt#3464]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:windows
- Programming Language version:python 3.6
- CCXT version: '1.15.12'
- Exchange:okex

when i run my code,this problem will happend,
and then another problem will happend:
                                                             socket.timeout: select timed out

and then another problem will happend:
                                                             urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.okex.com', port=443): Max retries exceeded with url: /v2/spot/markets/products (Caused by ProxyError('Cannot connect to proxy.', timeout('select timed out',)))

and then another problem will happend:
                                                             requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.okex.com', port=443): Max retries exceeded with url: /v2/spot/markets/products (Caused by ProxyError('Cannot connect to proxy.', timeout('select timed out',)))

and then another problem will happend:ccxt.base.errors.ExchangeError: okex https://www.okex.com/v2/spot/markets/products GET HTTPSConnectionPool(host='www.okex.com', port=443): Max retries exceeded with url: /v2/spot/markets/products (Caused by ProxyError('Cannot connect to proxy.', timeout('select timed out',)))

so ,i dont know where is it wrong?

because the last traceback was happended when ：
                                                                       File "偏度单线程策略.py", line 39, in <module>
    OKB_balance = okexinfo.fetch_balance()  
but i just annonced it at firt in my code and then it will not be excute later,so i cant know why?

**Comment by kroitor** [comment]
This is caused by your Proxy settings, as described in the error callstack. Sorry, but it is not related to ccxt, make sure you're using the proxies properly.

https://github.com/ccxt/ccxt/wiki/Install#proxy

**Comment by brucewong0516** [comment]
thx dude,i will try this later.

**Comment by brucewong0516** [comment]
@kroitor 
i'd tryed to do like this:
import ccxt
exchange = ccxt.poloniex()
exchange.proxies = {
  'http': 'http://10.10.1.10:3128',
  'https': 'http://10.10.1.10:1080',
}
it will not done:
RequestTimeout: okex GET https://www.okex.com/v2/spot/markets/products HTTPSConnectionPool(host='www.okex.com', port=443): Max retries exceeded with url: /v2/spot/markets/products (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000002E2F5B34630>, 'Connection to 115.28.148.137 timed out. (connect timeout=10)'))

**Comment by kroitor** [comment]
```Python
exchange.proxies = {
  'http': 'http://10.10.1.10:3128',
  'https': 'http://10.10.1.10:1080',  # ←--------- why not HTTPS here? https://...
}
```
