### ISSUE TITLE
How to show specific market bid price by php

### ISSUE THREAD

**Issue by codiblog** [ccxt/ccxt#3465]
I used php version to my site, How can i display only specific market bid price only in php. 

Example: I want to display BTC/USDT bid price 6563 etc in my specific market by php version.

**Comment by kroitor** [comment]
Use fetchTicker: 

- https://github.com/ccxt/ccxt/wiki/Manual#price-tickers
- https://github.com/ccxt/ccxt/wiki/Manual#individually-by-symbol

Also see examples here:
- https://github.com/ccxt/ccxt/tree/master/examples/php

Hope this answers your question.

**Comment by kroitor** [comment]
```PHP
$ticker = $bitfinex->fetch_ticker ('BTC/USDT')
var_dump ($ticker['bid']);
```

http://www.learn-php.org/
