### ISSUE TITLE
BTCTurk's BTC/USD values are inflated

### ISSUE THREAD

**Issue by nathankjer** [ccxt/ccxt#3469]
- OS: Mac OS X
- Programming Language version: Python
- CCXT version: 1.16.89
- Exchange: BTCTurk
- Method: ccxt.btcturk().fetch_ohlcv('BTC/USD')

Values are inflated by a consistent ~4x while such inflation is not present on coinmarketcap which leads me to believe it's not just server side

**Comment by kroitor** [comment]
Yeah, but... we don't really multiply those values, so if it's not in CCXT, then it's on the side of BTCTurk?

- https://github.com/ccxt/ccxt/blob/master/js/btcturk.js#L218
- https://github.com/BTCTrader/broker-api-docs#ohcl-data-daily

I guess, you should forward this to their support. Hope this answers your question. Let us know if not.
