### ISSUE TITLE
Binance loadFees issue (with VEN)

### ISSUE THREAD

**Issue by fonzmeister** [ccxt/ccxt#3472]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:puthon
- CCXT version:1.16.86
- Exchange:binance
- Method:loadFees

I get the following error using binance.loadFees()
```
ExchangeError: binance: success value False: {"msg":"The coin does not exist.","success":false}
```

Verbose output:
```
Response: GET https://api.binance.com/wapi/v3/withdrawFee.html?timestamp=1532424806470&recvWindow=5000&asset=VEN&signature=xxx 200 {'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Tue, 24 Jul 2018 09:33:27 GMT', 'Server': 'nginx', 'Vary': 'Accept-Encoding', 'Set-Cookie': 'JSESSIONID=C25F749041128140BCD07A5F3DF16535; Path=/; Secure; HttpOnly', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1cloudfront.net (CloudFront)', 'X-Amz-Cf-Id': 'qLUTO1MT7ubWXZkiH0gSgM-4Zv43TkaW_xWYB5kuFLx_RVsLVLYblQ=='} {"msg":"The coin does not exist.","success":false}
```

Probably has something to do with the tokenswap.

**Comment by kroitor** [comment]
> Probably has something to do with the tokenswap.

- https://github.com/ccxt/ccxt/issues/3239#issuecomment-403149285
- https://www.reddit.com/r/Vechain/comments/7m76yb/is_ven_an_erc20_token/
- https://medium.com/@vechainofficial/vechain-apotheosis-the-beginning-d9f0fdbdc910

VEN is being rebranded to VET. Might be related.

**Comment by fonzmeister** [comment]
It is working again. As you and I thought it was because of the VEN rebranding. Still this will happen every know and then with a mainnet launch, maybe it is nice to put in some error handling if possible? If not this issue can be closed

**Comment by kroitor** [comment]
> maybe it is nice to put in some error handling if possible?

Yep, we hope to add some layer of protection for these situations soon. Closing this for now if you don't mind. Let us know if you have updates on this. Thx!
