### ISSUE TITLE
`cost_to_precision()` uses `markets[symbol]['precision']['price']`?

### ISSUE THREAD

**Issue by mkoistinen** [ccxt/ccxt#3479]
Is this a typo on line 903 of `ccxt/python/ccxt/base/exchange.py`?

```
    def cost_to_precision(self, symbol, cost):
        return ('{:.' + str(self.markets[symbol]['precision']['price']) + 'f}').format(float(cost))

```
I would have expected it to be:

```
    def cost_to_precision(self, symbol, cost):
        return ('{:.' + str(self.markets[symbol]['precision']['cost']) + 'f}').format(float(cost))
```

This is a genuine question. I could imagine scenarios where it could be intentional.

**Comment by mkoistinen** [comment]
```
    costToPrecision (symbol, cost) {
        return parseFloat (cost).toFixed (this.markets[symbol].precision.price)
    }
```
Same in the JS version (not surprisingly)

**Comment by kroitor** [comment]
No it's not a typo, because exchanges will very rarely provide cost precision. Think logically, cost is `amount * price` that is the same units as price.

**Comment by mkoistinen** [comment]
OK. Thanks.
