### ISSUE TITLE
Stable Releases

### ISSUE THREAD

**Issue by timolson** [ccxt/ccxt#3481]
I'd love to have some kind of stable release.  Currently you just build a new release for every push, and I have know way of knowing whether it's untested development work or a critical fix.  My application works, then I update ccxt, then it's broken.  Then I update it again, and it works.  Pretty frustrating to not be able to trust whether any specific release of ccxt will work or not.

Can we have some kind of stability to releases?  Or perhaps at least a tag on certain releases that are thought to be relatively stable and not under active dev-level changes?

**Comment by kroitor** [comment]
@timolson 

> Can we have some kind of stability to releases? 

Yep, gotcha, however

> My application works, then I update ccxt, then it's broken.

this may not always depend on the release. 

> Or perhaps at least a tag on certain releases that are thought to be relatively stable and not under active dev-level changes?

We will think of adding a more specific and differentiated "stable" branching or tagging to it. You should be pretty safe if you update from minor to minor version, though you will most likely miss an update or two this way. We will also thing of bumping the minor version on stable releases for differentiation. 

Suggestions on setting this up would be appreciated as well )

**Comment by timolson** [comment]
You have a fast-moving project, so I wouldn't want to burden it with a heavy release process.  I think the main thing would be to separate changes into maybe two categories:

A) bug fixes and updates to _existing_ exchanges.  These diffs should be pushed to stable branches.
B) ongoing development work for new features & exchanges.  These should be excluded from the stable channel.

Currently it seems as though _all_ development work is getting pushed to `master`.

Ideally, all diffs get pushed to a development branch, but category A's are also backported to stable/master if necessary.  This does create more admin work for releases and PR's, though.

Maybe the easiest thing is to have a `dev` branch that only gets merged into master near the end of the minor version chain?  Or maybe promote certain dot-releases which don't have (many) known bugs against them.  Or maybe the devs can at least hand-tag certain dot-releases which they think are in a stable zone.  It's far from perfect but it would at least give users like me a way to search for a find a stable release to pin in pip.  I don't mind doing something like `ccxt==1.17.4` but currently have no way of finding a good release among the _many_ offered.

**Comment by kroitor** [comment]
Ok, we get the pros, of course. The bigs of cons here is time, of course. Will do something about it ;)

**Comment by timolson** [comment]
Easiest option is to put "Latest Stable: 1.16.x / Latest: 1.17.x" in the README until we get enough patches into the 17 release.  It doesn't help nearly as much, though, as having a dev branch vs master branch.  It's pretty low effort to now-and-then merge to master when you as lead dev sense that the codebase is in a good place.  Plus, end-users get the "right" updates automatically through their package manager.  It doesn't have to be a complicated process if you manually add your seal-of-approval now and then with a merge-to-master from dev.

**Comment by timolson** [comment]
P.S. There can be an issue with making sure PR's go against `dev` instead of `master`... not sure what is the best practice to enforce that

**Comment by timolson** [comment]
> When a new exchange is implemented it does not impact existing code. It just goes to a separate file in 'ccxt' folder. Exceptions to this are extremely rare. Thus merging new exchanges into unstable branch won't make the code more stable.

Yes that makes sense for new exchanges that don't need to update any existing core functionality.

> When the bug is fixed this may break existing code. And it happened quite a few times in my experience. Fixing bugs sometimes introduce new bugs, indeed. Hence, fixing bugs in a separate stable branch won't make it more "stable" than the current master.

Do you really mean that?  Backporting bugfixes to a stable branch is a common best practice in many projects.  Even if your ratio is 1 new bug in 5 patches, your bug-fix efficiency is still 5/6 or 83%.  That's adding stability.  In a corporate project there wouldn't even be a question about it, but for an open-source project the extra effort may not be worth it...

> Actually, what tells the trusty and untrusty code apart is testing and this is what ccxt already does.
> [...]
> Public API coverage is good - every public method gets tested.


Totally agree unit tests are helpful, along with system and functional tests, human QA, code reviews, end-user tests with staged rollouts, etc.  Don't let a few unit tests lead to overconfidence, however.

> What I've found practical in this project - is to run unit tests on live exchanges on my side with my keys and my data.

Yes, good wisdom for anyone relying on this project for trading live!
My own testing revealed bug #3480, missed by ccxt's testing, which is what led me to create this ticket in the first place.

Since 1.17.x introduced new functionality which doesn't have much time and eyeballs behind it yet, I would consider 1.16.89 to currently be the "most stable" release.  It would be nice to have the package managers track 1.16.x until 1.17.x has had more people use it over a longer period of time.

Personally, I'm pinning `ccxt==1.16.89` in my `requirements.txt` and will wait before deploying 1.17 to prod.  If there are any future exchange updates I need, I'll be faced with A) going live with new functionality in 1.17 or B) fork 1.16 and backport the patch myself.

**Comment by kroitor** [comment]
I would agree with @mkutny here.

@timolson let's imagine a practical situation: say, for a few months we have a stable master branch that is only updated between minor version bumps, and a dev branch that accumulates all fixes. To me all fixes are critical, if *"critical"* means *"not working how it should or breaking the app"*. So, if the lib is not working how it should – then a fix for it is a critical fix. 

Let's say, someone reports a bug-case when the library is not working as expected. And we add a critical fix to the dev branch. And that critical fix might or might not have introduced new bugs. The master branch still does not have the fix in it. Now the original reporter of the bug wants to use the fix. 
At this point we have these choices:

- tell him to switch to the dev branch and have all the bugs in that might have been introduced by other fixes
- merge that critical fix along with all the bugs it might have newly-introduced – to the master branch.

In both cases the author ends up having to either use an outdated master version without a fix, or to use an unstable version whatever it is – an "unstable dev" or a so called "stable merged master" with critical fix + new bugs (which is **hardly more stable** than the dev branch, when you merge frequently, if you think of).

How do we resolve this?

**Comment by mkutny** [comment]
@timolson 

> Since 1.17.x introduced new functionality which doesn't have much time and eyeballs behind it yet, I would consider 1.16.89 to currently be the "most stable" release. It would be nice to have the package managers track 1.16.x until 1.17.x has had more people use it over a longer period of time.

Yeah, I understand very much what you mean.

Still, don't see how this could be achieved with this particular project. It's not that we don't want to have stable branches, it's just hardly achievable from practical standpoint.

**Comment by timolson** [comment]
I can’t agree that every push is a critical fix that needs to be
immediately released, but if it’s too burdensome to have a second branch or
at least tag/bless certain revisions, then there’s probably nothing to talk
about. ¯\_(ツ)_/¯ Guess I’ll manage ccxt versioning myself.

**Comment by kroitor** [comment]
Sorry if this is not something you expected for. We will reconsider the above anyway, and will do something about it, hopefully. Anyways, we will be happy to see more proposals and reports from you in future. Let us know if anything. Thx!
