### ISSUE TITLE
Is it possible to get Braziliex candlesticks?

### ISSUE THREAD

**Issue by viniciussvl** [ccxt/ccxt#3482]
I have been analyzing the braziliex code but I have not found anything related to candle, there really is no way to know which candles to do the RSI, MACD, etc analysis?

- OS: Windows 10
- Programming Language version: PHP
- CCXT version: 1.10.1 2017-11-06
- Exchange: Braziliex
- Method: OHLCV

**Comment by kroitor** [comment]
@viniciussvl they don't have such an endpoint in their API, unfortunately. You can still do this by polling frequently enough and merging emulated candles built from trades like so: https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-emulation. You should rather ask Braziliex when they are going to add OHLCV ) We'd love to, but they make it as hard as possible. Hope this answers your question. Let us know if not. )

**Comment by viniciussvl** [comment]
Another solution would be to examine the candles of another exchange that has a close quote, do you think a good one?

**Comment by kroitor** [comment]
> Another solution would be to examine the candles of another exchange that has a close quote, do you think a good one?

If you can determine which exchange has "close" quote and how "close it is" and can systematically prove this, then you'll be a billionaire shortly. Don't forget to tip this project then )
