### ISSUE TITLE
New Exchange: coinall.com

### ISSUE THREAD

**Issue by jackyxie** [ccxt/ccxt#3483]
- Exchange: https://www.coinall.com
- Api Doc: https://www.coinall.com/docs/

**Comment by jackyxie** [comment]
coinall is the first exchange of OKEx 100+ project

**Comment by jaggedsoft** [comment]
👍

**Comment by kroitor** [comment]
This exchange is shut down:
- https://coinquora.com/cryptocurrency-exchange-coinall-to-shut-down/
