### ISSUE TITLE
how to add new exchange to ccxt

### ISSUE THREAD

**Issue by hwanghakbeom** [ccxt/ccxt#3489]
Hello. 

I want to add new exchange upbit.

Is there any process or document for it?

**Comment by d4vidadams** [comment]
Open a new issue and include the following info:

API Doc: 
URL: 
Fee: --
Volume: --
Address: Canada
Company Info: NDAX
TNC: --
Registration: --
Based Country: Canada
Whitepaper: --
Priority: normal
Github group: --
Note: ranked top : NA
Type: Centrailzed Ex
Discussion: --

**Comment by kroitor** [comment]
@hwanghakbeom 

If you want to submit a proposal to add a new exchange name, then you should just follow the advice of @d4vidadams . However, if you mean to add the code, the issue on adding new exchange implementations is here: https://github.com/ccxt/ccxt/issues/2073 (wip)

One important note, @hwanghakbeom: we're already working on Upbit. So you might want to choose a different exchange to implement, just to split the workload among developers and to avoid confusion and duplication. Hope this answers your question, let us know if not.

**Comment by samgermain** [comment]
Here's a guide on how to create a new exchange

https://www.youtube.com/watch?v=w4e595TJK60
https://www.youtube.com/watch?v=jJA6zw3f4QI
