### ISSUE TITLE
Storing API secret

### ISSUE THREAD

**Issue by cartercarlson** [ccxt/ccxt#3492]
Hello,

Is there a convenient way to store an API key/secret on a forked repository?  I want to keep a file with all of my keys/secrets in the same repo so my first idea was to include the file in the primary .gitignore.  However, my concern is that if I keep my fork in sync with this repo, changes I made in .gitignore will be overwritten every time I sync, unhiding my key/secret file.

Sincerely,
Carter

**Comment by mkutny** [comment]
`keys.local.json` is in .gitignore already.

Additionally, if you make it an alias then you're pretty safe even in case it gets removed from .gitignore and you accidentally commit it.

**Comment by kroitor** [comment]
Thx, @mkutny for the correct answer!

@cartercarlson let us know if the above does not help! Feel free to reopen it if needed or just ask further questions, if you have more )
