### ISSUE TITLE
Critical dependency: the request of a dependency is an expression + increased bundle size

### ISSUE THREAD

**Issue by AoDev** [ccxt/ccxt#3493]
## Environment
- OSX
- Javascript
- ccxt v1.17.11
- webpack

## Issue
When I updated from 1.14.295, I started to get this **warning**: 
```
Critical dependency: the request of a dependency is an expression
```

Investigating the matter I found the following:

> This error should not be ignored. It usually means that every file below a certain path will be included into the bundle (which should certainly not be ignored).

from [webpack issues](https://github.com/webpack/webpack/issues/196#issuecomment-71917456).

So I checked my bundle size and I see I got almost **500kb** added to the bundle compared to the bundle size with `ccxt@1.14.295`! To be fair, this could be new features of ccxt but I doubt it.

I also get tons of warning from node-gyp rebuild when `npm installing`.

I don't know if it's really an issue that should be resolved on ccxt side, the app still works, but something seems off.

### Long warning log

```shell
WARNING in ./node_modules/bindings/bindings.js 81:22-40
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/keccak/bindings.js
 @ ./node_modules/keccak/index.js
 @ ./node_modules/ethereumjs-util/dist/index.js
 @ ./node_modules/ccxt/js/base/Exchange.js
 @ ./node_modules/ccxt/ccxt.js
```

**Comment by kroitor** [comment]
> To be fair, this could be new features of ccxt but I doubt it.

Actually, 1.14.295 is way too old. And 500kb of added code is there indeed.

> I don't know if it's really an issue that should be resolved on ccxt side, the app still works, but something seems off.

To me it does not look like an issue with CCXT. But we will look into it to see what can be done in this regard. Thx for reporting!

**Comment by kroitor** [comment]
In addition to the above, you can also take a look here on making a reduced bundle of exchanges when building: https://github.com/ccxt/ccxt/issues/3332

**Comment by AoDev** [comment]
@kroitor 
While I still have the warning, your answer gave me the idea to create a `webpack loader` that filters the exchanges. Do you think it would be useful to share this loader?

Configuration looks like this:

```js
{
  test: /\.js$/,
  use: [
    {
      loader: path.resolve('tools', 'filterExchangesLoader.js'),
      options: {
        exchanges: [
          'binance',
          'coinbase',
          'cryptopia',
          'huobipro',
          'kraken',
          'okex',
          'bittrex'
        ]
      }
    }
  ],
  include: /node_modules\/ccxt/,
},
```

Result: (317KB stat size)
<img width="1104" alt="screen shot 2018-08-15 at 18 34 10" src="https://user-images.githubusercontent.com/1526150/44160246-1fa3f480-a0ba-11e8-9acb-202a5f0d5642.png">

Compared to before: (2 MB stat size; biggest module of all vendors)
<img width="1147" alt="screen shot 2018-08-15 at 18 32 41" src="https://user-images.githubusercontent.com/1526150/44160259-2894c600-a0ba-11e8-986a-92a4c18562bf.png">

**Comment by kroitor** [comment]
@AoDev 

> Do you think it would be useful to share this loader?

Sure, why not. We can put it into our examples and add links to it to the docs. Also, check out this related PR: https://github.com/ccxt/ccxt/pull/3399

**Comment by AoDev** [comment]
@kroitor I released a first version.  
You can find it: https://github.com/Cryptovista/ccxt-exchanges-loader.

It's doing its job. It will simplify people's life for "custom" builds (if they use Webpack). :)
I'll add some safeguards later in case someone uses an exchange id that does not exist.

**Comment by kroitor** [comment]
@AoDev thx so much! I'll add links to it shortly!
