### ISSUE TITLE
currency_id() and BTC BCH DRK

### ISSUE THREAD

**Issue by yamontv** [ccxt/ccxt#3494]
- OS: Ubuntu 16.04
- Programming Language version: Python 3.6.5
- CCXT version: 1.17.11
- Exchange: Bittrex, Cryptopia and maybe others
- Method: currency_id()
I want to get real exchange coin names from ccxt exchange symbols. I use currency_id() and iterate through all symbols. All coins except BTC BCH and DRK names are right. Here is the code:

>def get_active_symbols(exchange):
    return [
        symbol for symbol in exchange.symbols
        if is_active_symbol(exchange, symbol)
    ]

> def is_active_symbol(exchange, symbol):
    return ('.' not in symbol) and (('active' not in exchange.markets[symbol])
                                    or (exchange.markets[symbol]['active']))

> def get_market_coins(exchange, quote):
    assets_list = []
    active_symbols = get_active_symbols(exchange)
    for data in active_symbols:
        mar = exchange.market(data)
        if mar['quote'] == quote:
            assets_list.append(exchange.currency_id(mar['base']))
    return assets_list

I checked this on Bittrex and Cryptopia. For example it returns BCC but there BCH listed. Is this a bug or I'm doing something wrong?

**Comment by kroitor** [comment]
> All coins except BTC BCH and DRK names are right.

Can you clarify what's exactly wrong with them?

> For example it returns BCC but there BCH listed. Is this a bug or I'm doing something wrong?

Most likely, you're confusing BCC with BCH:

- https://github.com/ccxt/ccxt/wiki/Manual#naming-consistency
- https://github.com/ccxt/ccxt/issues/83
- https://github.com/ccxt/ccxt/search?q=bcc+bch&type=Issues

Let us know if the above does not answer your question. Thx!

**Comment by kroitor** [comment]
> But if I do THE SAME operation with exchange.symbol "BCH/BTC" it return "BCC" that is wrong! It should return BCH!

Got it, uploaded a fix for it, should arrive shortly.
