### ISSUE TITLE
Add Swap.DEP https://swap.online

### ISSUE THREAD

**Issue by caffeinum** [ccxt/ccxt#3495]
I am a developer of the decentralized exchange protocol https://swap.online. There is an open-source implementation in Javascript, yet in alpha stage: https://github.com/swaponline/swap.core. The website runs this implementation.

All the communication happens peer-to-peer between clients. We have no backend and no control over exchange process. We use:
- atomic swap algorithm for exchanging coins,
- ipfs and ipfs-pubsub-room for messaging
- bitcoin-js, web3 for atomic swaps.

I presume it would be convenient to add our library to your project. It has big opportunities for arbitrage and private keys directly on client. The fees are **only** blockchain miner fees.

My main concern is that the lib will add extra dependencies, and that is it's currently in Babel, thus not easy to add to vanilla JS.

What do you think about that?

**Comment by kroitor** [comment]
The exchange website is unreachable.
