### ISSUE TITLE
New Exchange: NDAX.io

### ISSUE THREAD

**Issue by d4vidadams** [ccxt/ccxt#3496]
API Doc: https://www.ndax.io/api-info.html
URL: https://www.ndax.io
Fee: --
Volume: --
Address: Canada
Company Info: NDAX
TNC: --
Registration: --
Based Country: Canada
Whitepaper: --
Priority: normal
Github group: --
Note: ranked top : NA
Type: Centrailzed Ex
Discussion: --

**Comment by diwenshi61** [comment]
Was added to both ccxt and ccxtpro. Can close this.
