### ISSUE TITLE
fetch balance key error

### ISSUE THREAD

**Issue by clu8** [ccxt/ccxt#3497]
RFR is a listed coin on Bittrex, but it is not showing up as a key in balances. 

- OS: Ubuntu 16.04 LTS
- Programming Language version: Python 3.6
- CCXT version: 1.17.11
- Exchange: Bittrex
- Method: fetch_balance

```
In [1]: import ccxt

In [2]: key = {...}

In [3]: b = ccxt.bittrex(key)

In [4]: b.verbose = True

In [5]: ccxt.__version__
Out[5]: '1.17.11'

In [6]: bal = b.fetch_balance()

Request: GET https://bittrex.com/api/v2.0/pub/Markets/GetMarketSummaries {'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} None

... (removed for privacy)

In [7]: 'RFR' in bal.keys()
Out[7]: False

In [8]: bal['RFR']
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-8-1762a7d4ba3b> in <module>()
----> 1 bal['RFR']

KeyError: 'RFR'
```

**Comment by kroitor** [comment]
If you look carefully into their verbose response, you'll see that they didn't return within your balances:

<img width="617" alt="screen shot 2018-07-26 at 04 38 06" src="https://user-images.githubusercontent.com/1294454/43236414-b76ea590-908d-11e8-91dd-5abfaa3fc6a0.png">

You should probably forward this question to Bittrex, as this is obviously somewhere on their side. Hope this answers your question, let us know if not. Feel free to reopen it if needed or just write further questions here, will be happy to answer. Also we would be very thankful if you report back whether you managed to reach out for Bittrex and to get a response from them on the above. Thx!

**Comment by clu8** [comment]
I just reported the issue to Bittrex.

**Comment by clu8** [comment]
Bittrex responded and said they are looking into the issue. Also, this particular problem with RFR appears to be fixed.

**Comment by kroitor** [comment]
@clu8 thx so much for letting us know!
