### ISSUE TITLE
Sometimes TypeError in fetchOHLCV (kraken)

### ISSUE THREAD

**Issue by NikolayKrishchuk** [ccxt/ccxt#3500]
- OS: Ubuntu 18 lts
- Programming Language version: node.js 10.5
- CCXT version: 1.17.17
- Exchange: kraken
- Method: fetchOHLCV

Hardly ever, but fetchOHLCV can raise an error

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at kraken.fetchMarkets (/node_modules/ccxt/js/kraken.js:248:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by kroitor** [comment]
This should work normally in the current version 1.18.300+. Let us know if you still have issues with it after upgrading to the most recent version. Thx!
