### ISSUE TITLE
Howto/guide for websockets (WIP) branch

### ISSUE THREAD

**Issue by firepol** [ccxt/ccxt#3502]
Hi,

I was tempted to post this request in the issue #56, but 140 replies are quite intimidating, also because that post is about implementation, this is a request of guiding/write an example/howto/documentation.

I know that websockets is still work in progress and not implemented in the master branch.
From my understanding, the main work in progress is in the: https://github.com/lfern/ccxt/tree/feature/websockets-multiple branch from @lfern

In the issue #56 I've seen that @skeller88 is providing support for python (maybe you can help me?).

I'm developing in python and I'm using CCXT in my project, now I'd like to use websockets to fetch the order books for these exchanges: bitstamp, binance, bitfinex, cexio, gdax. Instead of reinventing the wheel I'd like to use what's available in the community. Also I'm quite new to WS, so if I have to do do it from scratch I'd use aiohttp as described in [this tutorial](https://mmquant.net/replicating-orderbooks-from-websocket-stream-with-python-and-asyncio/). But I'd be happy to use the CCXT way, so to be ready for the future release when it's going to be implemented for good.

This is a **feature request**: can somebody write a little guide for python, on how I could use the actual work in progress by @lfern in python?

I'd like to have multiple websockets for multiple markets working at the same time and, say for sake of simplicity `print('do something here')` on each change (I mean every time there is a new update in the asks and bids). For the sake of simplicity I'd say I'm interested to get the top 5 order books (5 best bids and 3 bets asks - binance has a limit of at least 5 or multiple of 5). If somebody can help me to get started, that would be awesome. Who knows @lfern maybe I can be tester of your work done so far and give some feedback.

I've seen that CCXT now has twitter and a blog, I've seen a sort of programming tutorial in the blog. Maybe this "preview" before websockets are release in the master branch could be an interesting article there?

Thank you.

**Comment by kroitor** [comment]
@firepol 

> but 140 replies are quite intimidating, also because that post is about implementation, this is a request of guiding/write an example/howto/documentation.

I'm afraid, there's no guide that could be written at this point, except for those 140 answers in this issue: #56 + the answer of @lfern here. Basically, if anyone could provide that guide to you, WS would be implemented already. This is an R&D subject, so if you want to help or if you want to get something working on your side, you will have to get through those 140 comments + append 100-150 of your own comments there ) 

Closing this for now, feel free to reopen it if needed, or just ask further questions (here, or, better in #56).
