### ISSUE TITLE
npm install error v1.17.x on windows

### ISSUE THREAD

**Issue by yakisuzu** [ccxt/ccxt#3504]
- OS: win10
- CCXT version: 1.17.x
- npm version: 5.6.0

`npm install` is errored.
I think so you should write install caution for windows user on somewhere.

The 1.17.1 added web3 package is depends on web3-eth, web3-eth-accounts, scrypt.js, scrypt.
The scrypt require node-gyp.
https://github.com/barrysteyn/node-scrypt/blob/master/package.json#L49
https://github.com/nodejs/node-gyp

> On Windows
> Install all the required tools and configurations using Microsoft's windows-build-tools using npm install --global --production windows-build-tools from an elevated PowerShell or CMD.exe (run as Administrator).

This implicit dependency is not sure.

**Comment by kroitor** [comment]
Actually, I think is isn't a CCXT issue, more an issue with the dependency package, but thanks anyway, I've added a note of it to the Install guide.
