### ISSUE TITLE
Binance market doesnt exist

### ISSUE THREAD

**Issue by AdvaithD** [ccxt/ccxt#3508]
I've got a simple Node script which pulls OHLCV data periodically.

This error pops up:
![](https://i.gyazo.com/f964d3d9e4c1fe3bea2a2c3f69137a8c.png)

**Comment by kroitor** [comment]
That's right, all symbols on Binance should have a slash in them, as documented in the Manual: 

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
- https://github.com/ccxt/ccxt/wiki/Manual#naming-consistency
- https://github.com/ccxt/ccxt/wiki/Manual#consistency-of-base-and-quote-currencies

Let us know if the above does not answer your question.

**Comment by kroitor** [comment]
<img width="1118" alt="screen shot 2018-07-28 at 07 16 00" src="https://user-images.githubusercontent.com/1294454/43353005-1a592b72-9236-11e8-9b6a-b5c0fb967b9d.png">

**Comment by AdvaithD** [comment]
Yep, I figured a while back. It was my code formatting the query string. My bad
