### ISSUE TITLE
LBank withdraw API

### ISSUE THREAD

**Issue by ohyahu** [ccxt/ccxt#3509]
LBank announced that they support API for withdrawing. https://github.com/LBank-exchange/lbank-official-api-docs/blob/master/API-For-Spot-CN/币币交易REST%20API(交易).md
 Wondering if we could implement that?

```
GET http://api.lbank.info/v1/withdrawConfigs.do
POST http://api.lbank.info/v1/withdraw.do
(post params: api_key, sign, account, assetCode, amount, memo, mark, fee)
```

**Comment by frosty00** [comment]
I'll implement this later today (:
