### ISSUE TITLE
Failure update to the newest ccxt version

### ISSUE THREAD

**Issue by bohdanz1997** [ccxt/ccxt#3520]
- OS: Linux Mint 18.3 64-bit
- Programming Language version: js, node v9.11.2, npm v5.6.0
- CCXT version: 1.15.39

I have ccxt version 1.15.39 in my project, so i decided to update it up to 1.17.49. After running: npm install
i received thoose errors:

> scrypt@6.0.3 preinstall /home/dev/work/mass/bitcoin/node_modules/scrypt
> node node-scrypt-preinstall.js

Error: Error: Command failed: ./configure
configure: error: in `/home/dev/work/mass/bitcoin/node_modules/scrypt/scrypt/scrypt-1.2.0':
configure: error: C compiler cannot create executables
See `config.log' for more details

> keccak@1.4.0 install /home/dev/work/mass/bitcoin/node_modules/keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."

> keccak@1.4.0 rebuild /home/dev/work/mass/bitcoin/node_modules/keccak
> node-gyp rebuild

make: Entering directory '/home/dev/work/mass/bitcoin/node_modules/keccak/build'
  CXX(target) Release/obj.target/keccak/src/addon.o
make: g++: Command not found
keccak.target.mk:113: recipe for target 'Release/obj.target/keccak/src/addon.o' failed
make: *** [Release/obj.target/keccak/src/addon.o] Error 127
make: Leaving directory '/home/dev/work/mass/bitcoin/node_modules/keccak/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/dev/.nvm/versions/node/v9.11.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.10.0-38-generic
gyp ERR! command "/home/dev/.nvm/versions/node/v9.11.2/bin/node" "/home/dev/.nvm/versions/node/v9.11.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dev/work/mass/bitcoin/node_modules/keccak
gyp ERR! node -v v9.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dev/.npm/_logs/2018-07-30T08_44_06_600Z-debug.log
Keccak bindings compilation fail. Pure JS implementation will be used.

> scrypt@6.0.3 install /home/dev/work/mass/bitcoin/node_modules/scrypt
> node-gyp rebuild

make: Entering directory '/home/dev/work/mass/bitcoin/node_modules/scrypt/build'
  SOLINK_MODULE(target) Release/obj.target/copied_files.node
make: g++: Command not found
copied_files.target.mk:22: recipe for target 'Release/obj.target/copied_files.node' failed
make: *** [Release/obj.target/copied_files.node] Error 127
make: Leaving directory '/home/dev/work/mass/bitcoin/node_modules/scrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/dev/.nvm/versions/node/v9.11.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.10.0-38-generic
gyp ERR! command "/home/dev/.nvm/versions/node/v9.11.2/bin/node" "/home/dev/.nvm/versions/node/v9.11.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dev/work/mass/bitcoin/node_modules/scrypt
gyp ERR! node -v v9.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.0.0-beta.3 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@2.1.0 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-with-socket@0.0.4 requires a peer of react@^15.6.1 but none is installed. You must install peer dependencies yourself.
npm WARN The package eslint-config-airbnb is included as both a dev and production dependency.
npm WARN The package eslint-plugin-import is included as both a dev and production dependency.
npm WARN The package eslint-plugin-jsx-a11y is included as both a dev and production dependency.
npm WARN The package eslint-plugin-react is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dev/.npm/_logs/2018-07-30T08_44_10_263Z-debug.log

**Comment by kroitor** [comment]
From this:

> Error: Error: Command failed: ./configure
> configure: error: in `/home/dev/work/mass/bitcoin/node_modules/scrypt/scrypt/scrypt-1.2.0':
> configure: error: C compiler cannot create executables

Do you have the permissions to write to that folder? Have you tried doing that as root? This is most likely an issue with your setup... And you might want to upgrade your npm to 6.0.0 as well.

Also, have you tried a clean install in a separate folder? Does it work for you? A lot has passed since 1.15.39... so there may be some conflict we don't know of yet )

**Comment by bohdanz1997** [comment]
i have updated npm version to `6.2.0` and tried `npm install ccxt` in a separate folder but installation failed with same errors

**Comment by kroitor** [comment]
Looks like this is not an issue with CCXT, but most likely an issue with your installation/configuration of Linux Mint:

- https://forums.linuxmint.com/viewtopic.php?t=161122
- https://unix.stackexchange.com/questions/216856/c-compiler-cannot-create-executables
- https://github.com/skycocker/chromebrew/issues/142
- https://www.google.ru/search?q=configure+error+C+compiler+cannot+create+executables
- https://askubuntu.com/questions/647583/how-to-fix-configure-error-c-compiler-cannot-create-executables
- https://unix.stackexchange.com/questions/367465/c-compiler-cannot-create-executables-when-installing-gcc-and-binutils
- https://forums.xilinx.com/t5/Embedded-Linux/Configure-error-C-compiler-cannot-create-executables-when-i-used/td-p/795996

Let me know if installing/reinstalling scrypt and/or node from scratch does not help. Unfortunately, this is beyond the scope of our source code, so there's little we can do to fix it inside the CCXT package.

**Comment by bohdanz1997** [comment]
Thx, i will try it soon and notify you

**Comment by kroitor** [comment]
@bohdanz1997 ok, i'm closing this for now until we have further feedback on this. Feel free to reopen it if needed or ask questions, if you have more. We will be happy if you report back whether you managed to solve it or not. Thx!

**Comment by kroitor** [comment]
@bohdanz1997 a somewhat related issue here: https://github.com/ccxt/ccxt/issues/3539. We will be happy if you let us know, whether you managed to solve it in your case. Thx!

**Comment by bohdanz1997** [comment]
Hey, i googled for a long time and found solution. I run this command in terminal
`sudo apt-get install build-essential g++`
and ccxt has been installed successfully

**Comment by kroitor** [comment]
@bohdanz1997 thx for reporting back! We have received a few other similar reports and will add thr above instructions to the build script to make it more friendly. Cheers!

**Comment by phamhere** [comment]
OS: macOS HIgh Sierra 10.13.16
Programming Language version: js, node v8.11.3, npm v6.4.0

```
I had the same error as bohdanz1997 with:
Error: Error: Command failed: ./configure
configure: error: in `/Users/peterpham/Desktop/practice/apollo-project/node_modules/scrypt/scrypt/scrypt-1.2.0':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

There is something odd with my configuration I guess and I'm not sure how to fix it. I'll keep looking around but if there are any solutions for mac instead of linux, please feel free to help me out.

**Comment by kroitor** [comment]
@phamhere https://stackoverflow.com/a/10358412/5055465

**Comment by phamhere** [comment]
@kroitor Thank you for the link! I checked it out and installed Xcode and made sure the command line tools were there just like in the stackoverflow link. I changed the following:
```
cd /Applications/Xcode.app/Contents/Developer/Toolchains
sudo ln -s XcodeDefault.xctoolchain OSX10.8.xctoolchain
```
Still I keep having that error. I think I might have messed up things more with that command but I don't know. I'll keep looking around for more solutions. If this helps I'll post the full error:
```
Peters-MacBook-Air:apollo-project peterpham$ sudo npm install --save ccxt
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support

> scrypt@6.0.3 preinstall /Applications/Xcode.app/Contents/Developer/Toolchains/node_modules/scrypt
> node node-scrypt-preinstall.js

Error: Error: Command failed: ./configure
configure: error: in `/Applications/Xcode.app/Contents/Developer/Toolchains/node_modules/scrypt/scrypt/scrypt-1.2.0':
configure: error: C compiler cannot create executables
See `config.log' for more details


> keccak@1.4.0 install /Applications/Xcode.app/Contents/Developer/Toolchains/node_modules/keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."


> keccak@1.4.0 rebuild /Applications/Xcode.app/Contents/Developer/Toolchains/node_modules/keccak
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Command failed: /Users/peterpham/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:557:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Applications/Xcode.app/Contents/Developer/Toolchains/node_modules/keccak
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/peterpham/.npm/_logs/2018-08-30T04_11_28_370Z-debug.log
Keccak bindings compilation fail. Pure JS implementation will be used.

> scrypt@6.0.3 install /Applications/Xcode.app/Contents/Developer/Toolchains/node_modules/scrypt
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Command failed: /Users/peterpham/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:557:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Applications/Xcode.app/Contents/Developer/Toolchains/node_modules/scrypt
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/Applications/Xcode.app/Contents/Developer/Toolchains/package.json'
npm WARN Toolchains No description
npm WARN Toolchains No repository field.
npm WARN Toolchains No README data
npm WARN Toolchains No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/peterpham/.npm/_logs/2018-08-30T04_11_29_259Z-debug.log
```

**Comment by kroitor** [comment]
@phamhere 

> gyp ERR! stack Error: Command failed: /Users/peterpham/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];

↑ This is strange. Looks as if Anaconda Python overrides the built-in system python... You should check the env PATH to see if the path to the anaconda python comes before the built-in. Also, you can try installing `sudo npm install scrypt` first (can make a difference sometimes depending on the env setup).

**Comment by phamhere** [comment]
Thank you for the fast response again @kroitor. I tried the `sudo npm install scrypt` which gave the same error unfortunately. I'll try to look into the Anaconda Python pathing but I really don't know what I'm doing when it comes to env PATH.
