### ISSUE TITLE
PHP Fatal error:  Uncaught ccxt\AuthenticationError:

### ISSUE THREAD

**Issue by juragandotid** [ccxt/ccxt#3522]
`PHP Fatal error:  Uncaught ccxt\AuthenticationError: indodax {"success":0,"error":"Invalid credentials. Bad sign.","error_code":"bad_sign"} in E:\indodax\vendor\ccxt\ccxt\php\indodax.php:449`

**Comment by juragandotid** [comment]
i'm have to delete an create again api key, but an error. Whats problems

**Comment by juragandotid** [comment]
`PHP Fatal error:  Uncaught ccxt\AuthenticationError: indodax {"success":0,"error":"Invalid credentials. Bad sign.","error_code":"bad_sign"} in E:\indodax\vendor\ccxt\ccxt\php\indodax.php:448
Stack trace:
#0 E:\indodax\vendor\ccxt\ccxt\php\Exchange.php(1023): ccxt\indodax->handle_errors(200, '', 'https://indodax...', 'POST', Array, '{"success":0,"e...')
#1 E:\indodax\vendor\ccxt\ccxt\php\Exchange.php(868): ccxt\Exchange->fetch('https://indodax...', 'POST', Array, 'method=trade&no...')
#2 E:\indodax\vendor\ccxt\ccxt\php\Exchange.php(872): ccxt\Exchange->fetch2('trade', 'private', 'POST', Array, NULL, NULL)
#3 [internal function]: ccxt\Exchange->request('trade', 'private', 'POST', Array)
#4 E:\indodax\vendor\ccxt\ccxt\php\Exchange.php(807): call_user_func(Array, 'trade', 'private', 'POST', Array)
#5 [internal function]: ccxt\Exchange->ccxt\{closure}(Array)
#6 E:\indodax\vendor\ccxt\ccxt\php\Exchange.php(1848): call_user_func_array(Object(Closure), Array)
#7 E:\indodax\vendor\ccxt\ccxt\php\indodax.php(331): ccxt\Exchange->__call(' in E:\indodax\vendor\ccxt\ccxt\php\indodax.php on line 448

Fatal error: Uncaught ccxt\AuthenticationError: indodax {"success":0,"error":"Invalid credentials. Bad sign.","error_code":"bad_sign"} in E:\indodax\vendor\ccxt\ccxt\php\indodax.php:448
Stack trace:
#0 E:\indodax\vendor\ccxt\ccxt\php\Exchange.php(1023): ccxt\indodax->handle_errors(200, '', 'https://indodax...', 'POST', Array, '{"success":0,"e...')
#1 E:\indodax\vendor\ccxt\ccxt\php\Exchange.php(868): ccxt\Exchange->fetch('https://indodax...', 'POST', Array, 'method=trade&no...')
#2 E:\indodax\vendor\ccxt\ccxt\php\Exchange.php(872): ccxt\Exchange->fetch2('trade', 'private', 'POST', Array, NULL, NULL)
#3 [internal function]: ccxt\Exchange->request('trade', 'private', 'POST', Array)
#4 E:\indodax\vendor\ccxt\ccxt\php\Exchange.php(807): call_user_func(Array, 'trade', 'private', 'POST', Array)
#5 [internal function]: ccxt\Exchange->ccxt\{closure}(Array)
#6 E:\indodax\vendor\ccxt\ccxt\php\Exchange.php(1848): call_user_func_array(Object(Closure), Array)
#7 E:\indodax\vendor\ccxt\ccxt\php\indodax.php(331): ccxt\Exchange->__call(' in E:\indodax\vendor\ccxt\ccxt\php\indodax.php on line 448`

**Comment by kroitor** [comment]
Does this work for you:

```PHP
$id = "\\ccxt\\indodax";
$exchange = new $id (array (
    "apiKey" => "OEJGH4SX-5AKKDJUL-FXS0WTM8-NLLGG0FK-S52DHUJJ",
    "secret" => "9c0d8c88c3d4f121cfe6279ca4276f2519b59a39369781b378034d608460a9c2591ea6e64e604807"
));
print_r($exchange->fetch_balance());
```

? 

If it doesn't work, then we need you to report the issue properly:

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Hope this answers your question.

**Comment by juragandotid** [comment]
i use construct like this

`public function __construct()
    {
        print "Masukan Api Key : ";
        $this->ApiKey = rtrim(fgets(STDIN));
        print "Masukan Secret Key : ";
        $this->Secret = rtrim(fgets(STDIN));
        $this->inboxno = new \ccxt\indodax (array(
            'apiKey' => $this->ApiKey,
            'secret' => $this->Secret,
            'enableRateLimit' => true
        ));

    }`

any problem ?

**Comment by kroitor** [comment]
@juragandotid you didn't answer my question, actually ) You should first try with your credentials written in text inside the code. If it works, then you are not typing the credentials correctly. I've provided my keys to you, have you tried them? Because, from there it should be clear, that this is not an issue inside CCXT. This has something to do with the way you set the keys. Once again, does my snippet above work for you?

**Comment by juragandotid** [comment]
@kroitor didn't work man

**Comment by kroitor** [comment]
> @kroitor didn't work man

Sorry, but *"didn't work"* doesn't work ) You gotta start being very precise, namely dump your output and debug info, versions, code, numbers, all that, otherwise it will take an eternity to help you. It's written everywhere. Make sure to read the following first to paste it all in a readable way:

- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it
- https://github.com/ccxt/ccxt/wiki/FAQ#i-am-calling-a-method-and-i-get-an-error-what-am-i-doing-wrong

**What we expect to see from you, exactly:**

```
mbp:ccxt igorkroitor$ php --version
PHP 7.2.8 (cli) (built: Jul 19 2018 12:15:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.8, Copyright (c) 1999-2018, by Zend Technologies
```

```
mbp:ccxt igorkroitor$ cat test-indodax.php
```

```PHP
<?php

date_default_timezone_set ('UTC');

include_once ('./ccxt.php');

$id = "\\ccxt\\indodax";
$indodax = new $id (array (
	'apiKey' => 'OEJGH4SX-5AKKDJUL-FXS0WTM8-NLLGG0FK-S52DHUJJ',
	'secret' => '9c0d8c88c3d4f121cfe6279ca4276f2519b59a39369781b378034d608460a9c2591ea6e64e604807',
));

print_r($indodax->fetch_total_balance());
```

```sh
mbp:ccxt igorkroitor$ php -f test-indodax.php
Array
(
    [BTC] => 0
    [ACT] => 0
    [ADA] => 0
    [BCD] => 0
    [BCH] => 0
    [BTG] => 0
    [ETH] => 0
    [ETC] => 0
    [IGNIS] => 0
    [LTC] => 0
    [STQ] => 0
    [NXT] => 0
    [TEN] => 0
    [TRX] => 0
    [WAVES] => 0
    [XLM] => 0
    [XRP] => 0
    [XZC] => 0
    [BTS] => 0
    [DASH] => 0
    [DOGE] => 0
    [XEM] => 0
    [IDR] => 0
)
mbp:ccxt igorkroitor$
```

**Comment by kroitor** [comment]
If the above doesn't work, then we expect to see your verbose output, as written here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue, here: https://github.com/ccxt-dev/ccxt/wiki/Manual#troubleshooting and here: https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

**Comment by kroitor** [comment]
Also, make sure your timezone is defaulting to UTC, as documented in the Manual, see `date_default_timezone_set ('UTC');` above.

**Comment by juragandotid** [comment]
the error show when i'm create custom order. When fecth balance no problem. i'm think the problem on function sign.

**Comment by kroitor** [comment]
> the error show when i'm create custom order. When fecth balance no problem. i'm think the problem on function sign.

Ok, I'll look into it and will get back to you on this.

**Comment by kroitor** [comment]
@juragandotid can you post your code for the order call?

**Comment by kroitor** [comment]
Actually, no need for it, as I can see the error in your code right away. You're passing the price as a string that has a space appended to it.

```
                                             this %0D%0A should not be here ↓

[3] => method=trade&nonce=1532996100&pair=btc_idr&type=buy&price=100451532%0D%0A&idr=5022576600000&btc=50000
```

If you're using the user input to parse the price, make sure you trim it and convert it to a float number first. Case solved at this point, I guess. Here's the answer you should have:

```PHP
<?php

date_default_timezone_set ('UTC');

include_once ('./ccxt.php');

$id = "\\ccxt\\indodax";
$indodax = new $id (array (
	'apiKey' => 'OEJGH4SX-5AKKDJUL-FXS0WTM8-NLLGG0FK-S52DHUJJ',
	'secret' => '9c0d8c88c3d4f121cfe6279ca4276f2519b59a39369781b378034d608460a9c2591ea6e64e604807',
	// 'verbose' => true,
));

$price_with_space = "100451532 ";
$price = (float) trim ($price_with_space);
print_r($indodax->create_order('BTC/IDR', 'limit', 'buy', 50000, 100451532));
```

```
mbp:ccxt igorkroitor$ php -f test-indodax.php
PHP Fatal error:  Uncaught ccxt\InsufficientFunds: indodax {"success":0,"error":"Insufficient balance."} in /Users/igorkroitor/ccxt/php/indodax.php:439
Stack trace:
#0 /Users/igorkroitor/ccxt/php/Exchange.php(1072): ccxt\indodax->handle_errors(200, '', 'https://indodax...', 'POST', Array, '{"success":0,"e...')
#1 /Users/igorkroitor/ccxt/php/Exchange.php(917): ccxt\Exchange->fetch('https://indodax...', 'POST', Array, 'method=trade&no...')
#2 /Users/igorkroitor/ccxt/php/Exchange.php(921): ccxt\Exchange->fetch2('trade', 'private', 'POST', Array, NULL, NULL)
#3 [internal function]: ccxt\Exchange->request('trade', 'private', 'POST', Array)
#4 /Users/igorkroitor/ccxt/php/Exchange.php(846): call_user_func(Array, 'trade', 'private', 'POST', Array)
#5 [internal function]: ccxt\Exchange->ccxt\{closure}(Array)
#6 /Users/igorkroitor/ccxt/php/Exchange.php(1923): call_user_func_array(Object(Closure), Array)
#7 /Users/igorkroitor/ccxt/php/indodax.php(331): ccxt\Exchange->__call('privatePostTrad...', Array)
#8 /Users/igorkroitor/ccxt/test-ind in /Users/igorkroitor/ccxt/php/indodax.php on line 439
```

**Comment by juragandotid** [comment]
@kroitor this is my code : https://pastebin.com/raw/QqdMDeYc

**Comment by kroitor** [comment]
@juragandotid it just so happens that we posted at the same time, see my previous response for the answer. Your `price` contains a space.

**Comment by juragandotid** [comment]
how to remove the spcae? i'm just parse the last price and than like be lastprice * 15 /100, i don't know the last price is contains space. i'm just parse from last price.

Any solution to remove last price contains space?

Thank you.

**Comment by kroitor** [comment]
@juragandotid 

Error in this line:

```PHP

             $hasil = ($dapat) . PHP_EOL; // don't append PHP_EOL to it, wrong

             $hasil = ($dapat); // don't append PHP_EOL to it, correct
```

You should really learn string concatenation and output in PHP, because those are the very basics and fundamentals otherwise it will be very hard to use this library efficiently. In other words, you have to learn the programming language first. Read this entire page even despite it's a lot of reading:

- http://php.net/manual/en/language.types.string.php

----

P.S.
Post your code here next time, with **triple backticks**

&#096;&#096;&#096;
good
&#096;&#096;&#096;

---

&#096;bad&#096;

\'bad\'

**Comment by kroitor** [comment]
> Any solution to remove last price contains space?

Don't add it, then you will not have to remove it.

```PHP

            // ...

            $harga =  ($ticker) . PHP_EOL; // ←---- this is also an error most likely, remove EOL from here
            $cari = ($harga * 7) / 100;
            $dapat = ($harga + $cari + rand(99000, 1100000));

            $hasil = ($dapat); // PHP_EOL ↓ moved to output, no need to append it to the price
            print "Price is : " . $hasil . PHP_EOL . "\r\n";

            // ...
```

Sorry, but I can't really teach programming, don't have time for this, tutorials are everywhere on the Internet. I've shown above that this is not an issue with the library, but an issue with your understanding of your own code.

**Comment by juragandotid** [comment]
PHP Fatal error:  Uncaught ccxt\ExchangeError: indodax => unknown error => {"success":0,"error":"Nonce must be greater than 1533011122. You provided 1533011122.","error_code":"invalid_nonce"} in E:\indodax\vendor\ccxt\ccxt\php\indodax.php:451

what the meaining on nonce?

**Comment by kroitor** [comment]
On your previous question, alternatively, you can do the following:

```
$buy = $this->inboxno->create_order($symbol, $type, $side, $amount, $hasil);

// ↓ change the above line to the following

$buy = $this->inboxno->create_order($symbol, $type, $side, (float) trim($amount), (float) trim($hasil));

// ...

$sell = $this->inboxno->create_order($symbol, $type, $side, $amount, $hasil);

// ↓ change the above line to the following

$sell = $this->inboxno->create_order($symbol, $type, $side, (float) trim($amount), (float) trim($hasil));
```

---

> what the meaining on nonce?

It is documented here: 

- https://github.com/ccxt/ccxt/wiki/Manual#authentication
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-the-nonce
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/Manual#invalidnonce

If you're issuing multiple requests simultaneously in parallel threads, your nonces can cross. You have to sync them between the threads.

**Comment by kroitor** [comment]
https://en.wikipedia.org/wiki/Cryptographic_nonce
