### ISSUE TITLE
Cryptopia fetch OHLCV error ccxt\DDoSProtection

### ISSUE THREAD

**Issue by viniciussvl** [ccxt/ccxt#3523]
Hello, before it was working normally, now it is generating this error of DDoS protection, I tested with 3 different IPs and always returns the error:

Type: ccxt\DDoSProtection
Message: cryptopia GET https://www.cryptopia.co.nz/Exchange/GetTradePairChart?tradePairId=4948&dataRange=0&dataGroup=30 200 not accessible from this location at the moment

- OS: Windows 10
- Programming Language version: PHP 5.6
- CCXT version: 1.10.1 2017-11-06
- Exchange: Cryptopia
- Method: OHLCV

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/3052

**Comment by viniciussvl** [comment]
@kroitor I have read about this issue where cryptopia changes the parameters, I changed the CCXT code and still get the DDoSProtection error, but if I put the url in the browser the api returns the candles normally in a JSON.

**Comment by kroitor** [comment]
@viniciussvl you will have to use a cloudscraper then, this, however, can be quite tricky with PHP... Search for "bypass cloudflare in php", like this one, for example: https://github.com/stackoverflowin/CloudFlare-PHP-Bypass (2yr old, not sure if it works now).

**Comment by kroitor** [comment]
@viniciussvl alternatively, you can try a CORS proxy: https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin, despite the name, this can help test if this is indeed the case with Cloudflare:

```PHP
$id = "\\ccxt\\cryptopia";
$exchange = new $id (array (
    'origin' => 'foobar', // a random string
    'proxy' => 'https://cors-anywhere.herokuapp.com/',  // last slash critical
));

print_r ($exchange->fetch_ohlcv ...
```

Let us know if that does not help.

**Comment by viniciussvl** [comment]
Hello, the second option did not work, I'll test the first lib you submitted.
