### ISSUE TITLE
Yobit is creating Liqui

### ISSUE THREAD

**Issue by presence35** [ccxt/ccxt#3524]
- OS: Linux
- Programming Language version: PHP
- CCXT version: Latest

```
$exchange = new \ccxt\yobit (array (
		    'apiKey' => $this->getExchangeInfo("Yobit","API"),
		    'secret' => $this->getExchangeInfo("Yobit","Secret")
		));

		$orders = json_encode($exchange->fetchBalance());
```

It returns the following:

[30-Jul-2018 18:31:44 Europe/Kiev] PHP Fatal error:  Uncaught ccxt\AuthenticationError: yobit requires `apiKey` in /home/of/public_html/ccxt-master/php/Exchange.php:645
Stack trace:
#0 /home/of/public_html/ccxt-master/php/**liqui**.php(661): ccxt\Exchange->check_required_credentials()
#1 /home/of/public_html/ccxt-master/php/Exchange.php(916): ccxt\liqui->sign('getInfo', 'private', 'POST', Array, NULL, NULL)
#2 /home/of/public_html/ccxt-master/php/Exchange.php(921): ccxt\Exchange->fetch2('getInfo', 'private', 'POST', Array, NULL, NULL)
#3 [internal function]: ccxt\Exchange->request('getInfo', 'private', 'POST', Array)
#4 /home/of/public_html/ccxt-master/php/Exchange.php(846): call_user_func(Array, 'getInfo', 'private', 'POST', Array)
#5 [internal function]: ccxt\Exchange->ccxt\{closure}()
#6 /home/of/public_html/ccxt-master/php/Exchange.php(1923): call_user_func_array(Object(Closure), Array)
#7 /home/of/public_html/ccxt-master/php/yobit.php(155): ccxt\Exchange->__call('privatePostGetI...', Array)
 in /home/of/public_html/ccxt-master/php/Exchange.php on line 645

**Comment by presence35** [comment]
I should have been calling my own exchange name as

getExchangeInfo("YoBit","API")  (capital B)

But that still doesn't explain why CCXT wanted to default to liqui.

**Comment by kroitor** [comment]
@presence35 it is not defaulting to Liqui. They both use the ex BTC-e clone API, thus in the code of CCXT, Yobit is a class derived from Liqui class. The class inheritance is one of the basic fundamental concepts of OOP. You should learn about it in order to use this library efficiently. Hope this answers you question.
