### ISSUE TITLE
Cryptopia: Can not get rid of "HTTP Error 400. The request has an invalid header name" error on private API

### ISSUE THREAD

**Issue by dmittal3** [ccxt/ccxt#3525]
Hi @kroitor ,

While trying to fetch Cryptopia data, I am always getting Error 400. ie. invalid header.
I am exactly doing what is written into js and converting it to unix at:
https://github.com/ManuCart/Cryptocurrency-Portfolio/blob/master/API_Cryptopia.js
or https://github.com/thebotguys/cryptopia-api-python/blob/master/cryptopia_api.py
[may be certainly I am missing something stupid here]

Can you please help by linking me to a working code online where I can check and correct my code.
_I was trying to do the same for Yobit.net exchange as well, but haven't been able to put sufficient energy there though to figure out the issue._

cryptopiaAPIkey=19xxxxxxxxxxxx
cryptopiaSecretKey=zi7SFpvxxxxxxxxxxxxx=

nonce=$(($(date +%s)))
uri="https://www.cryptopia.co.nz/api/getbalance"
post_parameters="{"Currency":"BTC"}"
param=$(printf "$post_parameters")
payloadMD5=$(printf "$param" | md5sum)
#echo $payloadMD5
payloadB64=$(printf "$payloadMD5" | base64)
#echo $payloadB64
param_hash=$payloadB64
#param_hash=CryptoJS.MD5(param).toString(CryptoJS.enc.Base64);
post="POST"
reqSignature=$cryptopiaAPIkey$post$uri$nonce$param_hash
#echo $reqSignature

hmacsignature=$(printf "$reqSignature" | openssl dgst -sha256 -hmac "$cryptopiaSecretKey" | sed 's/^.*= //')
#var hmacsignature = CryptoJS.HmacSHA256(reqSignature,cryptopiaSecretKey).toString(CryptoJS.enc.Base64);
echo $hmacsignature

hmacsignatureB64=$(printf "$hmacsignature" | base64)
echo=$hmacsignatureB64

AUTH=$(printf "amx $cryptopiaAPIkey:$hmacsignatureB64:$nonce")
echo $AUTH
curl -H "$AUTH" -X POST 'https://www.cryptopia.co.nz/api/getbalance'

Error:
"<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid Header</h2>
<hr><p>HTTP Error 400. The request has an invalid header name.</p>
</BODY></HTML>"

- OS: Ubuntu
- Programming Language version: Unix
- Exchange: Cryptopia

**Comment by kroitor** [comment]
> Can you please help by linking me to a working code online where I can check and correct my code. I was trying to do the same for Yobit.net exchange as well, but haven't been able to put sufficient energy there though to figure out the issue.

- https://github.com/ccxt/ccxt/blob/master/php/cryptopia.php#L732
- https://github.com/ccxt/ccxt/blob/master/php/yobit.php (derived from https://github.com/ccxt/ccxt/blob/master/php/liqui.php#L657)

Hope this helps. Sorry, but I can't really help you debug the code that isn't CCXT code, as I mentioned earlier. Hope for your understanding.

**Comment by dmittal3** [comment]
HI @kroitor ,
I installed the library and checked it for Cryptopia. For the moment, I am happy that I was able to do this config without any trouble.
Now, there is a small issue that output of function "fetch_balance()" is coming with extra "NULL" appended in the very last of entire data. Kindly check if this is known bug.

Since, instead of raw data, I required exporting data to json. For this, I made below amendments to function: **public function fetch_balance**

        //return $this->parse_balance($result); --commented by me
        echo json_encode($response, JSON_FORCE_OBJECT); --Added by me

But still the extra "NULL" is appearing in the last of JSON data.
Moreover, above commenting/editing is done to a auto generated file (cryptopia.php), is there any other place in the library where I can permanently set-up desired output format? ie. in current case JSON file

**Comment by kroitor** [comment]
@dmittal3 can you please post your **verbose output** for the fetchBalance call? (without your keys). 

```PHP
$exchange->verbose = true;
$exchange->fetch_balance();
```

Please make it readable, examples:

&#096;&#096;&#096;PHP
excellent
&#096;&#096;&#096;

&#096;&#096;&#096;
good
&#096;&#096;&#096;

&#096;
bad
&#096;

\'
bad
\'

\`bad\`

\'bad\'

**Comment by dmittal3** [comment]
PFA the files. I have generated this for Yobit as it was smaller data set. Same issue as Cryptopia here.
_One file was generated as json output, while other was normal._

If I understood correctly, this is what I did to get the output:
Added (in file which I created to execute Yobit data) 
sample taken: https://github.com/ccxt/ccxt/blob/master/examples/php/huobi-fetch-balance.php
$exchange->verbose = true; //added in line 16
_before_  
$balance = $exchange->fetch_balance ();

Please let me know if this is not what you needed.

[yobit_balances_(json format fetched instead of normal output).txt](https://github.com/ccxt/ccxt/files/2245588/yobit_balances_.json.format.fetched.instead.of.normal.output.txt)
[yobit_balances_(usual function).txt](https://github.com/ccxt/ccxt/files/2245589/yobit_balances_.usual.function.txt)

**Comment by kroitor** [comment]
With this snippet: https://github.com/ccxt/ccxt/blob/master/examples/php/huobi-fetch-balance.php
I don't have any NULL there:

```
mbp:ccxt igorkroitor$ cat examples/php/huobi-fetch-balance.php
<?php

$root = dirname (dirname (dirname (__FILE__)));

include $root . '/ccxt.php';

date_default_timezone_set ('UTC');

$exchange = new \ccxt\cryptopia (array (
    "apiKey" => "YOUR_API_KEY,
    "secret" => "YOUR_SECRET"
));

try {

    $balance = $exchange->fetch_balance ();
    var_dump ($balance);

} catch (\ccxt\NetworkError $e) {
    echo '[Network Error] ' . $e->getMessage () . "\n";
} catch (\ccxt\ExchangeError $e) {
    echo '[Exchange Error] ' . $e->getMessage () . "\n";
} catch (Exception $e) {
    echo '[Error] ' . $e->getMessage () . "\n";
}

?>
```

![example-with-cryptopia-001](https://user-images.githubusercontent.com/1294454/43465903-0a7ff696-94e7-11e8-81aa-e7f75d08c500.jpg)

![example-with-cryptopia-002](https://user-images.githubusercontent.com/1294454/43465909-0db5bc88-94e7-11e8-8760-f8d7529aa668.jpg)

The NULL from here is added or coming from somewhere inside your code:

![example-with-cryptopia-003](https://user-images.githubusercontent.com/1294454/43466226-b9595bb2-94e7-11e8-9c42-27ada60f8e01.jpg)

**Comment by dmittal3** [comment]
yes indeed, NULL appears only when below json call is made:

        //return $this->parse_balance($result);
        echo json_encode($result, JSON_FORCE_OBJECT);
However, its a simple json call and should normally be handled the same way as parse_balance. (just assumption).

**Just few questions:**
1. Is there any other ways I can extract JSON data out of it? 
    May be I am not able to find it yet, but couldn't see anything in the documents till now.

2. I see that keys are read only if they are present main exchange_name.php file, then what is the use of keys.json file under the root path?

3. Is there any way I can parameterize the keys (security reasons) and send them via POST method eg. something similar to : 
curl -s -H "YOUR_API_KEY: $apiKey" -H "YOUR_SECRET: $secret" -X GET 'https://ukrblockchains.com/ccxt/ccxt/examples/php/yobit-fetch-balance.php'
and these keys variables are just passed to show appropriate data for the users?

**Comment by kroitor** [comment]
> 1. Is there any other ways I can extract JSON data out of it?
> May be I am not able to find it yet, but couldn't see anything in the documents till now.

Sorry, can you clarify, please, extract JSON out of what?

> 2. I see that keys are read only if they are present main exchange_name.php file, then what is the use of keys.json file under the root path?

Those are used for testing (our build are automated with Travis CI): 

- https://github.com/ccxt/ccxt/blob/master/php/test/test.php
- https://travis-ci.org/ccxt/ccxt/builds/410399360

> 3. Is there any way I can parameterize the keys (security reasons) and send them via GET/POST method eg. something similar to :
curl -s -H "YOUR_API_KEY: $apiKey" -H "YOUR_SECRET: $secret" -X GET 'https://example.com/ccxt/examples/php/yobit-fetch-balance.php'
and these keys variables are just passed to show appropriate data for the users?

Yes, there are several approaches to choose from:

- use the getopt function: http://php.net/manual/en/function.getopt.php
- use the http://php.net/manual/en/reserved.variables.argc.php + http://php.net/manual/en/reserved.variables.argv.php (google `php argv tutorial` or search the same on youtube)
- read raw commandline input and parse it in your code
- use environment variables http://php.net/manual/enfunction.getenv.php
- ...

**Comment by dmittal3** [comment]
1. By JSON export I meant, I want to get data returned from public function fetch_balance() into JSON format directly rather than array format which is currently the case with this function.
By using json_encode($result, JSON_FORCE_OBJECT); I was trying to convert this array data into JSON.
 **Is there any way available, so that I could get outcome of this function into JSON format?**

_For temporarily, I found a solution to remove last NULL, but it would be great if CCXT library itself had it in built as JSON format is much needed nowadays._
_Temporary Solution, working fine (might help someone):_

_curl -s -X GET 'https://example.com/ccxt/examples/php/yobit-fetch-balance.php' -o $URL_yobit_balances_
_sed -i 's/NULL*$//'  $URL_yobit_balances_

2. For automated part, I will check it soon. For the moment its (Travis-CI) going over my head.

3. Thanks, will see how it can be passed via curl shell command.

**Comment by kroitor** [comment]
> Is there any way available, so that I could get outcome of this function into JSON format?

```PHP
<?php

$root = dirname (dirname (dirname (__FILE__)));

include $root . '/ccxt.php';

date_default_timezone_set ('UTC');

$exchange = new \ccxt\cryptopia (array (
    "apiKey" => "YOUR_API_KEY",
    "secret" => "YOUR_SECRET",
));

try {

    $balance = $exchange->fetch_balance ();
    echo json_encode ($balance, JSON_FORCE_OBJECT) . "\n";

} catch (\ccxt\NetworkError $e) {
    echo '[Network Error] ' . $e->getMessage () . "\n";
} catch (\ccxt\ExchangeError $e) {
    echo '[Exchange Error] ' . $e->getMessage () . "\n";
} catch (Exception $e) {
    echo '[Error] ' . $e->getMessage () . "\n";
}
```

↑ this script, when launched with `php -f examples/php/filename.php` does not output any NULL strings and does output the response of fetch_balance in JSON format.

> but it would be great if CCXT library itself had it in built as JSON format is much needed nowadays.

It comes in the JSON format from the exchange already, you can see it in 
`$exchange->last_http_response`.

**Comment by dmittal3** [comment]
thanks @kroitor 
The solution above works well. However, I figured out the what was appending extra NULL into the JSON file:

    $balance = $exchange->fetch_balance ();
    echo json_encode ($balance, JSON_FORCE_OBJECT) . "\n";
    //**var_dump ($balance);**

I commented var_dump and it worked well now. It was present in 'example/php/huobi-fetch-balance.php' file, which I copied for Cryptopia and Yobit. Seems this has not much requirement in this section.

Cheers!!!
