### ISSUE TITLE
Python asyncio multiple exchange order book polling

### ISSUE THREAD

**Issue by venomx6** [ccxt/ccxt#3532]
- OS: Win 10
- Programming Language version: 3.6
- CCXT version: 1.17.57
- Exchange: See screenshot
- Method: asyncio

Any idea why I keep getting these errors :
"xxx requires to release all resources with an explicit call to the .close() coroutine.
Unclosed client session"
![capture](https://user-images.githubusercontent.com/39489983/43470640-bbe4d74e-94f1-11e8-8b40-9ee096143932.JPG)

My code is :

```
import asyncio
import os
import sys
from time import time



root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt.async_support as ccxt  # noqa: E402


limit = 5
exchanges = ['binance','bitbank','bitbay','bitfinex','bitkk','bitlish','bitstamp','bittrex','ccex','cex','coinexchange',
            'dsx','ethfinex','exmo','exx','fybse','fybsg','gdax','gemini','indodax','lakebtc','lbank','liqui','luno',
            'lykke','poloniex','quadrigacx','southxchange','therock','tidex','vaultoro','virwox','yobit','zb']

async def poll():
    while True:
        for ex in exchanges:
            exchange = getattr(ccxt, ex)({'timeout': 200000,'enableRateLimit': True})
            yield await exchange.fetch_order_book('ETH/BTC', limit)

async def main():
    async for order_book in poll():
        print(order_book)


asyncio.get_event_loop().run_until_complete(main())
```

**Comment by kroitor** [comment]
> Any idea why I keep getting these error

If you are creating the exchange instance from within your async coroutine, you need to free all resources you might have created and used from within that coroutine. Add `exchange.close()` to a place in your code where you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine). 

```Python
async def poll():
    while True:
        for ex in exchanges:
            exchange = getattr(ccxt, ex)({'timeout': 200000,'enableRateLimit': True})
            yield await exchange.fetch_order_book('ETH/BTC', limit)
            exchange.close()  # ←---------------------- here
```

↑ I've added a clarification to that message to avoid further confusion. Let us know if it does not answer your question or doesn't help.

**Comment by venomx6** [comment]
I've added the line, didn't help. I'm getting the exact errors as before.
Thanks for trying

**Comment by wardbradt** [comment]
Igor forgot to add `await` before `exchange.close()`. The below should work.
```
async def poll():
    while True:
        for ex in exchanges:
            exchange = getattr(ccxt, ex)({'timeout': 200000,'enableRateLimit': True})
            yield await exchange.fetch_order_book('ETH/BTC', limit)
           await exchange.close()  # ←---------------------- here
```

**Comment by venomx6** [comment]
Latest solution provided fixes the problem. This issue may be closed.
Thank you very much guys

**Comment by hugmin42** [comment]
Sorry to post here, but not sure where else. I'm trying to get a grip on async. In the code sample above what is the advantage of using async as it seems that the orderbooks from each exchange is still retrieved consequentially and not simultaneously. How would one use async to retrieve orderbooks from different exchanges at the same time?

**Comment by kroitor** [comment]
@hugmin42 https://github.com/ccxt/ccxt/blob/master/examples/py/async-orderbooks-from-multiple-exchanges-at-once.py (same as with tickers, just changed the method names)

**Comment by hugmin42** [comment]
Great thanks, will see if I can get that to work.
