### ISSUE TITLE
How to place IOC orders on Binance?

### ISSUE THREAD

**Issue by wardbradt** [ccxt/ccxt#3533]
- Programming Language version: Python 3.6.3
- CCXT version: 1.14.301
- Exchange: Binanace
- Method: `create_order` and `Binance.options`

I noticed the below line in binance.py:
```
'defaultTimeInForce': 'GTC',  # 'GTC' = Good To Cancel(default), 'IOC' = Immediate Or Cancel
```
Is IOC implemented for binance? Would the following place an IOC order?
```
import ccxt.async as ccxt
import asyncio

binance = ccxt.binance()
binance.options['defaultTimeInForce'] = 'IOC'
asyncio.get_event_loop().run_until_complete(binance.create_order('ETH/BTC', 'limit', 'sell', 1, 434))
```
Is Binance the only exchange which offers this functionality?
Note that I am using an older version of ccxt (1.14.301) as do not yet use 3.7. If the functionality is different in a newer version of ccxt, how so?

**Comment by kroitor** [comment]
> Is IOC implemented for binance? 

Yep.

> Would the following place an IOC order?

Yes, it would. However, I'd recommend this instead (it's a bit shorter and does not have side-effects):

```
... binance.create_order('ETH/BTC', 'limit', 'sell', 1, 434, {'timeInForce': 'IOC'}) ...
```

> Is Binance the only exchange which offers this functionality?

No, there are other exchanges that offer timeInForce as well, however, we didn't have a chance to unify this aspect yet, so, the parameter name is exchange-specific, and you should look it up in docs for your particular exchange(s). We hope to unify timeInForce asap.

> Note that I am using an older version of ccxt (1.14.301) as do not yet use 3.7. If the functionality is different in a newer version of ccxt, how so?

It was added in 1.14.36: https://github.com/ccxt/ccxt/commit/8e016613d74b3d87c2121892854749673e538594
