### ISSUE TITLE
Foxbit changed their API

### ISSUE THREAD

**Issue by rspadim** [ccxt/ccxt#3534]
please remove foxbit exchange, the api changed

**Comment by rspadim** [comment]
now the API only works with websocket

**Comment by phillipescofield** [comment]
I'm using ccxt to recover foxbit BTC / BRL prices, but the prices I got from ccxt are not the same as they appear on the Foxbit platform. Is there still a problem with Foxbit in the ccxt library?

**Comment by hanelore** [comment]
@phillipescofield are you using the new API?

**Comment by phillipescofield** [comment]
I'm using the last version of ccxt.

**Comment by hanelore** [comment]
@phillipescofield Foxbit changed the API. Now they use Websocket:

 wss://apifoxbitprodlb.alphapoint.com/WSGateway

Documentation: https://docs.foxbit.com.br/EN/index.html

**Comment by wesleysiqueira** [comment]
it's true

**Comment by danielcerdeira** [comment]
I had the same problem than phillipescofield. How can I use CCXT with the Foxbit Websocket? 
The values that I see on the website are different from CCXT.

**Comment by frosty00** [comment]
foxbit has been removed from ccxt already
