### ISSUE TITLE
CCXT / HITBTC - BTCUSDT

### ISSUE THREAD

**Issue by jevdiego** [ccxt/ccxt#3538]
Hi,

- OS: Windows 10
- Programming Language version: Node v8.11.3
- CCXT version: 6.2.0
- Exchange: HitBTC
- Method: loadMarkets

The CCXT library seems to pull BTCUSDT from HitBTC, but I'm confused as to how. If I query what currency pairs are supported with the HitBTC APIs (https://api.hitbtc.com/api/2/public/symbol), 'BTCUSDT' isn't there, so where is CCXT getting this data from?

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/issues/2851
- https://github.com/ccxt/ccxt/issues/3212
- https://github.com/ccxt/ccxt/issues/1083

HitBTC names it `USD` in their listing but it's actually `USDT`. Let us know if the above does not answer your question.

**Comment by kroitor** [comment]
P.S. By setting the keys in `.commonCurrencies` you can override the ccxt defaults how you want for your specific needs. Hope this helps.

**Comment by jevdiego** [comment]
Ah, thanks very much for the prompt response. Much appreciated!
