### ISSUE TITLE
Question about "unified" API

### ISSUE THREAD

**Issue by rueiwoqp** [ccxt/ccxt#3542]
What does unified mean exactly? I would expect that it means requests and responses are the same across exchanges but the responses do not have the same format.  This means that you must customize your code to parse a unique response from each exchange. Doesn't that defeat the purpose of a "unified" API? Is there something I'm missing?  I haven't analyzed every API call across many exchanges but trying the same code with just 2 different exchanges yields incompatibilities.  I'm not trying to be critical, I'm just trying to understand the intent behind the unified API.

**Comment by kroitor** [comment]
It's quite hard to explain shortly, but in general, this means "unified arguments and responses". However, this is a work in progress, so you might find some inconsistencies there (you can find a lot of them if you want). 

More about it here: https://github.com/ccxt/ccxt/wiki/Manual#unified-api. 

Hope this answers your question. Let us know if not.
