### ISSUE TITLE
Could you give an example about websocket

### ISSUE THREAD

**Issue by lmkhang** [ccxt/ccxt#3549]
I want to get last price by websocket. Do not use while and sleep. I mean there is anychange of price from pair and then it will push. I dont want to request continuously.

- Programming Language version: nodejs
- CCXT version: latest(02-08-2018)
- Exchange: binance
- Method: get last price by websocket

**Comment by kroitor** [comment]
@lmkhang see here: #56

**Comment by lmkhang** [comment]
when do You support for ws?
that post was posted a year ago. a long time :(. what problems have u been getting?

**Comment by Gennttii** [comment]
Will wss be supported soon? Cause I am getting banned by binance .. Hope you will add it soon, it will be great !

**Comment by kroitor** [comment]
> when do You support for ws?
> Will wss be supported soon?

https://github.com/ccxt/ccxt/wiki/FAQ#when-will-you-add-feature-foo-for-exchange-bar--whats-the-estimated-time-when-should-we-expect-this

> Cause I am getting banned by binance

If you're getting bans with Binance, it means that you're not respecting their rate limits... you're probably trying to poll `fetchTickers`, which has known issues with Binance, as described here:

- https://github.com/ccxt/ccxt/issues/3120
- https://github.com/ccxt/ccxt/issues/1855
- https://github.com/ccxt/ccxt/issues/1027
- ...
- https://github.com/ccxt/ccxt/search?q=binance+fetchTickers&type=Issues
