### ISSUE TITLE
[Binance] 1000ms Ahead of Server Time Error Handling Try/Catch Still Exits with UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by TotallyKyle** [ccxt/ccxt#3554]
- OS: Windows
- Programming Language version: Node 9.4
- CCXT version:  1.16
- Exchange: Binance
- Method: fetchMyTrades

After following the fixes in:
#850
#936

I have my time sync every 1024 seconds and a large recv window. The goal of the code is to try every market and fetch the trades you may or may not have made in those markets to get all of the trades you have made on binance. I am following strict rate limits of 1200 requests / min with the fetchMyTrades weight of 5 per call.

Here is a snippet of my catch try block following #1956:

```
while(true) {
                try {
                    trades = await exchangeClient.fetchMyTrades(market, undefined, undefined, {
                        fromId: latestId,
                        recvWindow: 10000000
                    });
                    break;
                }
                catch (error) {
                    console.log('Error caught here');
                    console.log(error);
                };
}
```

Yet I still hit upon these errors:

 UnhandledPromiseRejectionWarning: Error: binance {"msg":"{\"code\":-1021,\"msg\":\"Timestamp for this request was 1000ms ahead of the server's time.\"}","success":false}

I thought that if I wrapped my fetchMyTrades calls with try catch blocks and just kept retrying them when they failed, my time sync should work. However this is not the case and it seems these rejected promises aren't caught. What am I doing wrong? 

Thanks for any help or insight you can give!

**Comment by kroitor** [comment]
@TotallyKyle can you please show your instantiation code?

**Comment by TotallyKyle** [comment]
```
const initExchangeClient = (exchange, walletConfig) =>
    new ccxt[exchange]({
    apiKey: walletConfig.apiKey,
    secret: walletConfig.secretKey,
    password: walletConfig.passphrase,
    'options': { 'adjustForTimeDifference': true }
});
```

**Comment by kroitor** [comment]
Does adding the following line solve your issue?

```JavaScript
const initExchangeClient = (exchange, walletConfig) =>
    new ccxt[exchange]({
    apiKey: walletConfig.apiKey,
    secret: walletConfig.secretKey,
    password: walletConfig.passphrase,
    'options': { 'adjustForTimeDifference': true },
    enableRateLimit: true, // ←---------------------------------- this one
});
```

**Comment by kroitor** [comment]
Ok, thx for reporting back! Feel free to reopen it or just ask further questions if you have more.

**Comment by TotallyKyle** [comment]
With the enableRateLimit option set to true, I am getting errors with Gemini:

(node:50468) UnhandledPromiseRejectionWarning: Error: gemini POST https://api.gemini.com/v1/transfers 400 Bad Request {"result":"error","reason":"InvalidNonce","message":"Nonce '1533308261' has not increased since your last call to the Gemini API.

```
for (const market of markets) {
        console.log('Starting market: ' + market);
        let trades = [];
        let lastTimestamp = beginTimestamp;
        do {
            trades = await exchangeClient.fetchMyTrades(market, undefined, undefined, {
                timestamp: lastTimestamp,
                limit_trades: 500,
            });
            if (trades.length === 0) {
                break;
            }

            data = _.unionWith(data, trades, _.isEqual);
            lastTimestamp = trades[trades.length - 1].timestamp + 1;
            // Implemented delay after every API Call to ensure we stay under rate limit, 
            // without this we get error thrown above
            await new Promise(resolve => setTimeout(resolve, delay));
        } while (trades.length !== 0);
    }
```

If I implement actual delays (~.7s) between each API call, this error goes away. However, this delay is much much higher than the rate limit that their API describes ( whih is about 5 req/sec or a delay of .2s between each call). Due to the error message we are getting, I think it may have something to do with how ccxt is generating new nonces for each call for Gemini?

**Comment by kroitor** [comment]
@TotallyKyle if you update to 1.17.70, the issue with Gemini nonce should be resolved.
