### ISSUE TITLE
Poloniex fetch_tickers() starts to fail when a new asset is listed

### ISSUE THREAD

**Issue by booxter** [ccxt/ccxt#3559]
I am running a bot that relies on ccxt poloniex implementation, fetching tickers every 5 minutes and using this information to model / execute some trades.

Recently, a long running bot instance started to fail when executing fetch_tickers(), as follows:

```
Traceback (most recent call last):
  File "/usr/src/app/ct/main.py", line 376, in run_loop
    rates = trade_cycle(ex, rates)
  File "/usr/src/app/ct/main.py", line 69, in trade_cycle
    coins_to_rate = ex.get_tradable_coins()
  File "/usr/src/app/ct/exchange.py", line 220, in get_tradable_coins
    for coin in coins
  File "/usr/src/app/ct/exchange.py", line 221, in <setcomp>
    if coin == self.gold or self.get_symbol(coin) in self.ticker
  File "/usr/src/app/ct/exchange.py", line 467, in ticker
    return self._ticker
  File "/usr/local/lib/python3.6/site-packages/cached_property.py", line 112, in __get__
    value = self.func(obj)
  File "/usr/src/app/ct/exchange.py", line 460, in _ticker
    return self.api.fetch_tickers()
  File "/usr/local/lib/python3.6/site-packages/ccxt/poloniex.py", line 340, in fetch_tickers
    market = self.markets_by_id[id]
KeyError: 'BTC_EOS'
```

This started to happen on Aug 1 when the exchange listed EOS: https://poloniex.com/press-releases/2018.07.31-Introducing-EOS-markets-to-Poloniex/

Brief inspection of the code suggests that the issue may be specific to Poloniex; and that probably calling load_markets(reload=True) before calling to fetch_tickers() would mitigate the issue.

Versions:
```
ct@cryptobot:~$ docker exec -it bb2638ea0b57 pip freeze | grep ccxt
ccxt==1.16.43
ct@cryptobot:~$ docker exec -it bb2638ea0b57 cat /etc/redhat-release
Fedora release 28 (Twenty Eight)
```

**Comment by kroitor** [comment]
Thx for reporting!

> Brief inspection of the code suggests that the issue may be specific to Poloniex; and that probably calling load_markets(reload=True) before calling to fetch_tickers() would mitigate the issue.

Yep, basically, you're required to reload them regularly, otherwise your snapshot of their markets may be outdated. Will look into it and will add a workaround to avoid the crash.

**Comment by booxter** [comment]
@kroitor I don't think this fixes the issue because I am using Python bindings not JS.

**Comment by booxter** [comment]
Wow. Also, embarrassed. Thanks for your work!
