### ISSUE TITLE
okex future fetch balance failed

### ISSUE THREAD

**Issue by stedong** [ccxt/ccxt#3560]
failed to fetch balance using privatePostUserInfo, error code of 10004, changed method to privatePostFutureUserinfo and privatePostFutureUserinfo4fix error code of 20019
full error message:
failed to fetch balance message=okex {"result":false,"error_code":20019}, stack=Error: okex {"result":false,"error_code":20019}

**Comment by kroitor** [comment]
@stedong try resetting your (there's a standalone button that allows resetting it within okex interface) and then try fetching balance again with code unchanged. Then try issuing `privatePostFutureUserinfo`. Let us know if resetting the key does not help.

**Comment by stedong** [comment]
It does not work, same error

**Comment by kroitor** [comment]
Yeah, same on my side, resetting does not help anymore. 10004 == Request failed, whereas it worked for several months without a problem. Looks like some issue with the OKEX API engine to me. Investigating further into this.

**Comment by kroitor** [comment]
@stedong can you try creating a new key and retrying again with it? I just did the same on my side and it seems to have worked.

**Comment by stedong** [comment]
new Key worked for me as well, but how does the original okex future fetch the future balance, the implicit function always fetch spot balance

**Comment by kroitor** [comment]
@stedong we don't support position / margin trading with unified API for now, so you will have to use implicit API methods as documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods (`privatePostFutureUserinfo`, `privatePostFutureUserinfo4fix`, etc...)

```
                        'future_batch_trade',
                        'future_cancel',
                        'future_devolve',
                        'future_explosive',
                        'future_order_info',
                        'future_orders_info',
                        'future_position',
                        'future_position_4fix',
                        'future_trade',
                        'future_trades_history',
                        'future_userinfo',
                        'future_userinfo_4fix',
```

Hope this answers your question. Feel free to ask if you have more. Closing it for now as it seems like an issue with the API key on the OKEX side.
