### ISSUE TITLE
coinegg has new API for kline

### ISSUE THREAD

**Issue by yufeng0528** [ccxt/ccxt#3562]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: centos
- Programming Language version: python3
- CCXT version: 1.14
- Exchange: coinegg 
- Method: fetch_ohlcv

https://www.coinegg.com/explain.api.html#three-four

[kline](https://api.coinegg.im/api/v1/kline/region/usdt/?coin=eth&since=1530374400)

**Comment by ttodua** [comment]
Coinegg is no longer integrated in ccxt.

**Comment by DiOmaya** [comment]
can we get a clone ?
