### ISSUE TITLE
Huobi IOC order type

### ISSUE THREAD

**Issue by Showgofar** [ccxt/ccxt#3566]
Hello
Huobi support buy-ioc, sell-ioc, order types

https://github.com/huobiapi/API_Docs_en/wiki/REST_Reference

Is it possible to implement it via params? 
Thank you

**Comment by kroitor** [comment]
@Showgofar we already do support all endpoints and params intrinsically, as documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

```PHP
$symbol = 'FOO/BAR';
$type = 'limit';
$side = 'buy';
$amount = 123;
$price = 321;
$overrides = array ( 'type' => 'buy-ioc' ); // ←------------------- ↓↓↓
$exchange->create_order ($symbol, $type, $side, $amount, $price, $overrides);
```

Let us know if it does not answer your question. Thx!
