### ISSUE TITLE
SyntaxError: 'yield' inside async function in examples/py/async-bittrex-orderbook.py

### ISSUE THREAD

**Issue by fedecaccia** [ccxt/ccxt#3569]
https://github.com/ccxt/ccxt/blob/397a29d723effcc3d991adee0787919c69e5f7e6/examples/py/async-bittrex-orderbook.py#L17

Running code I have the following error:

python3 orderbook.py 
  File "orderbook.py", line 17
    yield await exchange.fetch_order_book('BTC/USDT')
           ^
SyntaxError: 'yield' inside async function

**Comment by mrasband** [comment]
@fedecaccia What version of python3 are you running? This feature isn't available until [3.6 via PEP525](https://www.python.org/dev/peps/pep-0525/) and works on 3.6+.

**Comment by fedecaccia** [comment]
@mrasband python3.5, ok I didn't know
