### ISSUE TITLE
gateio fetch_open_orders and fetch_closed_orders

### ISSUE THREAD

**Issue by stephenkarl** [ccxt/ccxt#3575]
Any reason why these 2 methods are not implemented yet?
The API is available for them.

**Comment by kroitor** [comment]
@stephenkarl sorry? what's your ccxt version and programming language?

JS:

- https://github.com/ccxt/ccxt/blob/master/js/gateio.js#L26
- https://github.com/ccxt/ccxt/blob/master/js/gateio.js#L530

Python:

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/gateio.py#L42
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/gateio.py#L504

PHP:

- https://github.com/ccxt/ccxt/blob/master/php/gateio.php#L27
- https://github.com/ccxt/ccxt/blob/master/php/gateio.php#L531

**Comment by kroitor** [comment]
<img width="1511" alt="screen shot 2018-08-06 at 18 52 08" src="https://user-images.githubusercontent.com/1294454/43727146-d734b8f4-99a9-11e8-8a31-de5563d0fd5b.png">

**Comment by stephenkarl** [comment]
my mistake. my code was searching in the old ccxt folder rather than the new one.
You may close this ticket.
