### ISSUE TITLE
okex future, can not change lever_rate to 20 when creating order

### ISSUE THREAD

**Issue by stedong** [ccxt/ccxt#3577]
when I create new order, I can change contract type by pass the contract type in the 'params', but lever_rate is always default to 10, can not change to 20 if I simply pass 'lever_rate': 20 to the params
```
async function run () {
  await fure.createOrder('BTC/USD', 'limit', 1, 1, 5000, {'contract_type': 'next_week', 'lever_rate': 20})
}

run()
```
this is a simple version of my code
function: createOrder:
Exchange: okex
method: POST
ccxt version: 1.16.32

Issue: placed order of next week but lever_rate is 10, should be 20

**Comment by kroitor** [comment]
@stedong can you please post your verbose request and response, precisely as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

**Comment by stedong** [comment]
sorry, I added some description, is this better to understand?

**Comment by kroitor** [comment]
Also, note:

https://github.com/okcoin-okex/API-docs-OKEx.com/blob/master/API-For-Futures-EN/REST%20API%20for%20FUTURES.md#contract-trade-api

OKEX API doc says:

> lever_rate | Leverage settings have to be adjusted on the trading page before creating an order. If you currently have 10x open order(s) or holding position(s), you cannot create a new 20x order.

@stedong will you post your code and verbose request/response? Or should we close this? I mean, do you still have a question with it?

**Comment by stedong** [comment]
I posted a simple version code of it, and I thought modify the create order will work, it does not work, and also, I do not have any 10X lev open. it still place as 10x lev

**Comment by kroitor** [comment]
@stedong let's try again, we need your verbose request and response, do this:

```JavaScript
const fure = new okexFuture({
  apiKey: 'API_KEY',
  secret: 'SECRET',
  verbose: true, // ←-------------------------- ADD THIS LINE
})
async function run () {
  await fure.createOrder('BTC/USD', 'limit', 1, 1, 5000, {'contract_type': 'next_week', 'lever_rate': 20})
}

run()
```

Add the above line then post your verbose request and response here.

**Comment by stedong** [comment]
thank you for fixing the serious mistake I made

**Comment by kroitor** [comment]
@stedong 

```
await fure.createOrder('BTC/USD', 'limit', 1, 1, 5000, {'contract_type': 'next_week', 'lever_rate': 20})
```

↑ yep, this line is missing the side...

Do you have it working now?

**Comment by stedong** [comment]
no, it is 10x, 1 is open long, it has side

**Comment by kroitor** [comment]
@stedong we will need your verbose request/response, this is the 4th time I'm telling you this )

**Comment by stedong** [comment]
```
const fure = new okexFuture({
  apiKey: 'apikey',
  secret: 'apiSecret',
  verbose: true, // ←-------------------------- ADD THIS LINE
  enableRateLimit: true,  // ←---- this line is also required, as documented in the Manual, btw
})
async function run () {
  await fure.createOrder('BTC/USD', 'limit', 1, 1, 5000, {'contract_type': 'next_week', 'lever_rate': 20})
}

run()
```

**Comment by kroitor** [comment]
@stedong *"to post your verbose output"* means add that line and run that code and then post the output from your screen here, that would contain the request sent towards OKEX and their response send back to you. Can you do that? You've posted your code twice already, I guess, that should be enough ) But we still need to see your verbose request and response. C'mon, it's not that hard.

**Comment by stedong** [comment]
There is the response u want

**Comment by kroitor** [comment]
@stedong can you try switching to 20x in your account (for next week) and run that code again?

![screen-shot-2018-08-07-at-02 17 59](https://user-images.githubusercontent.com/1294454/43746023-7ea9574e-99ea-11e8-9408-4e11247be9d3.jpg)

**Comment by stedong** [comment]
thank you, that solve the problem
