### ISSUE TITLE
BTCBOX fetchTickers

### ISSUE THREAD

**Issue by Esc4pism** [ccxt/ccxt#3582]
The url used for btcbox for fetchTickers is https://www.btcbox.co.jp/api/v1/allticker this returns an error 301. The correct url for this is now https://www.btcbox.co.jp/api/v1/ticker/

~https://www.btcbox.co.jp/help/asm#three-one~

Update: just found another better documentation explaining parameters: https://www.btcbox.co.jp/api/doc/v1

btcbox has 1 hardcoded marketpair BTC/JPY, but they also offer ETH/JPY, LTC/JPY and BCH/JPY, the parameter coin=<> should be used for fetchTicker now.

https://www.btcbox.co.jp/api/v1/ticker?coin=ltc

**Comment by xeno14** [comment]
I can take this issue. 

BTCBOX now serves ticker for a currency and all tickers is no longer available. In this case, should we remove fetchTickers method? Or could we call fetchTicker for each currency (I don't see such implementation though).

**Comment by kroitor** [comment]
> In this case, should we remove fetchTickers method?

Yep, unfortunately.

> Or could we call fetchTicker for each currency (I don't see such implementation though).

No, we stick to one http request per unified method call at most, so, in this case it is much better to set `fetchTickers` to false explicitly, and let the user call `fetchTicker` as many times as he wants for as many pairs as needed, in userland.

**Comment by kroitor** [comment]
Fixed in #3771, thx to @xeno14 !
