### ISSUE TITLE
SSL verify fail using ccxt asyncio, works using toy aiohttp script

### ISSUE THREAD

**Issue by creslinux** [ccxt/ccxt#3589]
### Long story short - catch 22.
We wrap our bots within and behind a varnish cache to prevent api blacklisting and outboud leaks (keys) to unwanted destinations.  We SSL terminate at our internal hitch to do this. 

For synchronous CCXT calls using `requests`  everything is perfectly. 
We set an environment variables to help `requests` along its way: 
```
REQUESTS_CA_BUNDLE=/home/creslin/freqcache/cert/ca.pem
export REQUESTS_CA_BUNDLE
```
Using CCXT asyncio  the error is ran into: 
`ssl:None [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)]` 

Our CA root certificate is added to our host OS key-store. 
Creating a toy aiohttp script and executing within the same environment/shell/directory works, and gets the time from binance.  
Removing the cert from the key store, predictably breaks the toy, but demonstrates the keystore is being used by aiothttp. 

toy script working - `a.py`:
```python
import aiohttp
import asyncio

async def main():
    session = aiohttp.ClientSession()
    async with session.get('https://api.binance.com/api/v1/time') as response:
        print(await response.text())
    await session.close()

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```
```
python3 a.py 
{"serverTime":1533729699098}
```

however when using aiohttp via ccxt i get SSL errors:
This is true is the root cert is in our keystore, or environment variables are set or not. 

Are you aware of any other locations I should be looking for placing our root certificate so CCXT async methods can make us of it? 

CCXT asyncio script - `1.py`
```python
import ccxt
import asyncio
import ccxt.async_support as ccxt_async

exchange = ccxt.binance({
    "apiKey": "123",
    "secret": "abc",
})

exchange_async = ccxt_async.binance({ 'verbose': True,
    "apiKey": "123",
    "secret": "abc",
})


async def fetch_closed_order(exchange_async, symbol):
    closedOrder = await exchange_async.fetchClosedOrders(symbol=symbol, since="", limit=500 , params={})
    return closedOrder

async def get_closed_orders(exchange_async, symbols):
    input_coroutines = [fetch_closed_order(exchange_async, symbol) for symbol in symbols]
    closedOrders = await asyncio.gather(*input_coroutines, return_exceptions=True)

    for closedOrder, symbol in zip(closedOrders, symbols):
        if not isinstance(closedOrder, list):
            print(exchange.id, symbol, 'error')
        else:
            print(exchange.id, symbol, 'ok')

    await exchange_async.close()
    return closedOrders


symbols=['ETH/BTC']

closedOrders = asyncio.get_event_loop().run_until_complete\
    (get_closed_orders(exchange_async, symbols))

for order in closedOrders:
	print(order)
```
```
Request: GET https://api.binance.com/api/v1/exchangeInfo {'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} None
binance ETH/BTC error
binance https://api.binance.com/api/v1/exchangeInfo GET Cannot connect to host api.binance.com:443 ssl:None [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)]
```

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: ubuntu 18.04
- Programming Language version: Python 3.6
- CCXT version: Version: 1.17.45
- Exchange: binance 
- Method: Any

**Comment by creslinux** [comment]
To add to this, through process of elimination i added my ca-root into requests bundled ca-store. 

At this point asyncio/aiohttp via ccxt started working

The following *seems true 

- Requests will use a customer CA if pointed to via` REQUESTS_CA_BUNDLE=` env variable
- Natural aiohttp/asyncio will only use the hosts system store, per python does
- ccxt aiohttp/asyncio will ignore system store and REQUESTS_CA_BUNDLE, but will use the bundled requests certificate store

**Comment by kroitor** [comment]
@creslinux basically, CCXT async does not use `requests`, because of their incompatibility. So, with asyncio you will have to add your certs as documented in asyncio docs: 

With asyncio we're using the `certifi`package for newer certificates (the system default is often outdated).

```Python
if self.own_session:
            # Create out SSL context object with our CA cert file
            context = ssl.create_default_context(cafile=certifi.where())
            # Pass this SSL context to aiohttp and create a TCPConnector
            connector = aiohttp.TCPConnector(ssl_context=context, loop=self.asyncio_loop)
            self.session = aiohttp.ClientSession(loop=self.asyncio_loop, connector=connector)
```

↑ This is why `certifi` is there.

From your last message it looks like you've figured it out yourself already. Thanks for reporting back btw! Hope you don't mind if I close this now. Feel free to ask further questions, if you have more.

**Comment by creslinux** [comment]
Hi Kroitor,
 
Thanks for the confirmation, always good to know its not environmental issue on my side. 
It would be really handy to be able to use an ENV to point to a custom CA.root file.

I know requests.adaptor is only used on ccxt sync calls, those guys are  also on certifi.
 
`requests`  adapters supports the ENV `REQUESTS_CA_BUNDLE` for using a pem outside of certifi;  a similar such as `CCXT_CA_BUNDLE` would be a big help to those like myself with custom CAs. 

My work-around at the moment is to append into certifi/cacert.pem. This is not as portable as flipping an ENV var as move ccxt-dockers between environments and production. We're trying to backtest/dry test many hundreds of instances - thus the need to our api-cache to not hit api-limits.

**Comment by kroitor** [comment]
@creslinux got it, will add support for env vars to asyncio certs, hopefully soon.

**Comment by creslinux** [comment]
super awesome - thanks!

**Comment by kroitor** [comment]
@creslinux a quick workaround for you would be create a new session like so:

```Python
import ccxt
import asyncio
import ccxt.async_support as ccxt_async

exchange = ccxt_async.binance({
    "apiKey": "123",
    "secret": "abc",
    "session": asyncio.ClientSession (),  # ←------- add me to use your system default certificates
})
```

@creslinux does this solve your issue?

**Comment by creslinux** [comment]
ill test - thanks for this.

**Comment by creslinux** [comment]
this one didnt work out, returns an error on start
```
"session": asyncio.ClientSession (),
AttributeError: module 'asyncio' has no attribute 'ClientSession'
```

**Comment by kroitor** [comment]
Pardon, that;s my fault, I made a typo there, should be `aiohttp.ClientSession`, of course.

Try this:

```Python
```

**Comment by creslinux** [comment]
id tried that, no joy 

```
    "session": aiohttp.ClientSession (),
NameError: name 'aiohttp' is not defined
```

**Comment by creslinux** [comment]
sorry thats my fault  - i missed the import

**Comment by kroitor** [comment]
@creslinux does it solve the initial issue with certificates for you?

**Comment by creslinux** [comment]
That allows me to use the main certificate store, its about the same for me to append my pem into `certifi` cert.pem or add into a containers `ca-certificates`.

The ideal is how `curl`, `requests`, and `openssl` manage it by allowing an ENV to point to a file or directory.  The mozilla and OS stores then remain intact, updating or unsetting the VAR lets an install be portable between test environments and live. 

aiohttp does not follow any off the usual suspects for using a custom CA cert. 
```
CURL_CA_BUNDLE=/home/creslin/freqcache/cert/ca.pem
REQUESTS_CA_BUNDLE=/home/creslin/freqcache/cert/ca.pem
SSL_CERT_DIR=/home/creslin/freqcache/cert/
SSL_CERT_FILE=/home/creslin/freqcache/cert/ca.pem
```

**Comment by creslinux** [comment]
could a target be passed through this `aiohttp.ClientSession ()` ?

**Comment by kroitor** [comment]
@creslinux yes, by means of TCPConnector, as was shown above:

```Python
import asyncio
import aiohttp
import ssl
import ccxt.async_support as ccxt_async

# ↓ your path here, instead of certifi.where()
# you can take from your ENV vars here:
path_to_cafile = certifi.where()  

context = ssl.create_default_context(cafile=path_to_cafile)
connector = aiohttp.TCPConnector(ssl_context=context)
session = aiohttp.ClientSession(connector=connector)

exchange = ccxt_async.binance({
    "apiKey": "123",
    "secret": "abc",
    "session": session),  # pass the session from above to exchange constructor
})
```

See docs here:

- https://docs.python.org/3/library/ssl.html#ssl.create_default_context
- https://docs.aiohttp.org/en/stable/client_advanced.html#connectors

↑ Does that answer your question?

**Comment by creslinux** [comment]
thats perfect, thank you!
