### ISSUE TITLE
Type error method name fetchOLHVC 

### ISSUE THREAD

**Issue by justmeonthegit** [ccxt/ccxt#3592]
On: windows 10 64bits, Python 3.6.5, ccxt-1.17.88, binance I experience troubles with the fetcholhvc method naming.

>>>ccxtcode = binance

According to universal documentation the call should be

            tmp2 = getattr(ccxt,self.ccxtcode)()
            data = getattr(tmp2,"fetchOHLCV")()

which is not working. Introspection on the object shows that;

            tmp2 = getattr(ccxt,self.ccxtcode)()
            data = getattr(tmp2,"fetchOhlcv")()

IS working.

**Comment by kroitor** [comment]
I'd recommend to stick to PEP8 underscore notation and method naming in Python, so the method name is `fetch_ohlcv`, as shown here:
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L485

Let us know if that does not answer your question.

**Comment by justmeonthegit** [comment]
I understand.  Do you agree that :

The Unified CCXT API says to use fetchOHLCV and binance is a CCXT/certified exchange ?

So therefore in my opinion it is not correct to close the issue but to implement the correct method name as these are our own guidelines. :-)

**Comment by kroitor** [comment]
@justmeonthegit

> Do you agree that: The Unified CCXT API says to use fetchOHLCV and binance is a CCXT/certified exchange ?

Sure! I've added a special case for it, because `fetchOHLCV` isn't a camelCase name, so if you update to 1.17.89 (it will arrive in 5-10 minutes) the above code should work with `fetchOHLCV` now )

**Comment by justmeonthegit** [comment]
You are great !
