### ISSUE TITLE
Problem with calling to binance.fetch_olhvc

### ISSUE THREAD

**Issue by justmeonthegit** [ccxt/ccxt#3593]
With python 3.6.5. on win10/64b I try to get the following code running:

>> ccxtcode = binance

  ```

              current_exchange = getattr(ccxt,self.ccxtcode)
              print (dir (current_exchange))
              data = current_exchange.fetch_ohlcv(current_exchange,"ETHBTC")
```

Which follows in the following

introspection of the loaded exchange (in this case binance)

['__class__', '__del__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'account', 'aggregate', 'aiohttp_proxy', 'amount_to_precision', 'amount_to_string', 'api', 'apiKey', 'array_concat', 'asyncio_loop', 'balance', 'base64urlencode', 'binary_concat', 'binary_to_string', 'build_ohlcv', 'calculate_fee', 'cancel_order', 'capitalize', 'certified', 'check_address', 'check_required_credentials', 'commonCurrencies', 'common_currency_code', 'convert_ohlcv_to_trading_view', 'convert_trading_view_to_ohlcv', 'cost_to_precision', 'create_limit_buy_order', 'create_limit_order', 'create_limit_sell_order', 'create_market_buy_order', 'create_market_order', 'create_market_sell_order', 'create_order', 'currencies', 'currencies_by_id', 'currency', 'currency_id', 'decode', 'decryptAccount', 'decryptAccountFromJSON', 'decryptAccountFromPrivateKey', 'deep_extend', 'define_rest_api', 'describe', 'dmy', 'edit_limit_buy_order', 'edit_limit_order', 'edit_limit_sell_order', 'edit_order', 'enableRateLimit', 'encode', 'encode_uri_component', 'exceptions', 'extend', 'extract_params', 'fee_to_precision', 'fees', 'fetch', 'fetch2', 'fetch_balance', 'fetch_bids_asks', 'fetch_closed_orders', 'fetch_currencies', 'fetch_deposit_address', 'fetch_fees', 'fetch_free_balance', 'fetch_funding_fees', 'fetch_l2_order_book', 'fetch_markets', 'fetch_my_trades', 'fetch_ohlcv', 'fetch_open_orders', 'fetch_order', 'fetch_order_book', 'fetch_order_status', 'fetch_order_trades', 'fetch_orders', 'fetch_partial_balance', 'fetch_ticker', 'fetch_tickers', 'fetch_total_balance', 'fetch_trades', 'fetch_used_balance', 'filterBy', 'filter_by', 'filter_by_array', 'filter_by_since_limit', 'filter_by_symbol', 'filter_by_symbol_since_limit', 'find_market', 'find_symbol', 'fromWei', 'getZeroExOrderHash', 'getZeroExOrderHash2', 'groupBy', 'group_by', 'gzip_deflate', 'handle_errors', 'handle_rest_errors', 'handle_rest_response', 'has', 'hash', 'hashMessage', 'headers', 'hmac', 'id', 'ids', 'implode_params', 'in_array', 'index_by', 'is_empty', 'iso8601', 'json', 'jwt', 'keysort', 'lastRestPollTimestamp', 'lastRestRequestTimestamp', 'last_http_response', 'last_json_response', 'last_response_headers', 'limits', 'load_fees', '**load_markets**', 'load_time_difference', 'load_trading_limits', 'logger', 'market', 'market_id', 'market_ids', 'markets', 'marketsById', 'markets_by_id', 'microseconds', 'milliseconds', 'minFundingAddressLength', 'msec', 'nonce', 'omit', 'options', 'orderbooks', 'ordered', 'orders', 'origin', 'parse8601', 'parseJsonResponse', 'parse_balance', 'parse_bid_ask', 'parse_bids_asks', 'parse_date', 'parse_ohlcv', 'parse_ohlcvs', 'parse_order', 'parse_order_book', 'parse_order_status', 'parse_orders', 'parse_ticker', 'parse_tickers', 'parse_timeframe', 'parse_trade', 'parse_trades', 'password', 'pluck', 'populate_fees', 'precision', 'precisionMode', 'precision_from_string', 'prepare_request_headers', 'price_to_precision', 'privateKey', 'proxies', 'proxy', 'purge_cached_orders', 'raise_error', 'rateLimit', 'rateLimitMaxTokens', 'rateLimitTokens', 'rateLimitUpdateTime', 'rawencode', 'request', 'requiredCredentials', 'restPollerLoopIsRunning', 'restRequestQueue', 'safe_either', 'safe_float', 'safe_float_2', 'safe_integer', 'safe_integer_2', 'safe_string', 'safe_string_2', 'safe_value', 'safe_value_2', 'sec', 'seconds', 'secret', 'session', 'set_markets', 'sign', 'signHash', 'signMessage', 'signZeroExOrder', 'soliditySha256', 'soliditySha3', 'solidityTypes', 'solidityValues', 'sort_by', 'substituteCommonCurrencyCodes', 'sum', 'symbols', 'throttle', 'tickers', 'timeout', 'toWei', 'to_array', 'trades', 'transactions', 'truncate', 'truncate_to_string', 'twofa', 'uid', 'unique', 'unjson', 'url', 'urlencode', 'usec', 'userAgent', 'userAgents', 'uuid', 'verbose', 'version', 'walletAddress', 'web3', 'withdraw', 'ymd', 'ymdhms']

Traceback (most recent call last):
  File "C:\www\tb\modules\custom\tb\tb_python\src\traderbot.py", line 106, in <module>
    main()
  File "C:\www\tb\modules\custom\tb\tb_python\src\traderbot.py", line 91, in main
    commandline_datacollect()
  File "C:\www\tb\modules\custom\tb\tb_python\src\traderbot.py", line 37, in commandline_datacollect
    dc.update_olhc()
  File "C:\www\tb\modules\custom\tb\tb_python\src\datacollector.py", line 36, in update_olhc
    e.update_olhc()
  File "C:\www\tb\modules\custom\tb\tb_python\src\allexchanges.py", line 14, in update_olhc
    e.fetchOHLCV()
  File "C:\www\tb\modules\custom\tb\tb_python\src\exchanges\tbexchange.py", line 67, in fetchOHLCV
    data = current_exchange.fetch_ohlcv(self,"ETHBTC")
  File "C:\Users\Justme\Anaconda3\lib\site-packages\ccxt\binance.py", line 486, in fetch_ohlcv
    self.load_markets()

**AttributeError: 'binance' object has no attribute 'load_markets'**

I checked the symbol which according to my knowlegde is oke, 

The code in the CCXT is

    def fetch_ohlcv(self, symbol, timeframe='1m', since=None, limit=None, params={}):

So now I'm  a little bit confused. I do not think it is an issue in the ccxt but I do not know what I'm doing wrong..

**Comment by kroitor** [comment]
The problem is with your particular code, unfortunately, you're not showing the snippet that I could copy-paste into my python interpreter to reproduce it without reconstructing your code on my side... From your report and from the pieces of code you posted, it looks like there's some substitution of `self` happening within your class.

Let's try this:

```Python
import ccxt
from pprint import pprint
exchange_id = 'binance'
exchange = getattr(ccxt, exchange_id)()
pprint(exchange.fetch_ohlcv('ETH/BTC'))
```

<img width="474" alt="screen shot 2018-08-09 at 01 26 30" src="https://user-images.githubusercontent.com/1294454/43867764-446154bc-9b73-11e8-9cc4-9ecff2f085b8.png">

That's a complete program that shows that the above is not an issue inside CCXT, but somewhere in your code. You should always post your code like shown in the example above, that will save you tons time, really ;) Read this **VERY** carefully:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ

People usually quickly find the bug when they are trying to make the shortest possible snippet to reproduce the issue, so the issue itself gets resolved even before it is posted. ;)

**Comment by kroitor** [comment]
In your code the pair is named `ETHBTC` instead of `ETH/BTC` for some reason, that is against the Manual: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

**Comment by justmeonthegit** [comment]
Thxs, you are totally correct. As I said in the beginning this is not an issue in CCXT.

The problem in my code was the call
`current_exchange = getattr(ccxt,self.ccxtcode)

should be
`current_exchange = getattr(ccxt,self.ccxtcode)()`

and indeed the symbol, not the marketid.

Thxs
