### ISSUE TITLE
How to fetch current positions on Bitmex?

### ISSUE THREAD

**Issue by pigslayer12** [ccxt/ccxt#3596]
Hi,

I am using the latest python version, but can't seem to find any function that would return my current positions on Bitmex. I am hoping there is something. 

Thanks for any help in advance.

**Comment by kroitor** [comment]
Duplicate (solved below):
- https://github.com/ccxt/ccxt/issues/2499
- https://github.com/ccxt/ccxt/search?q=private_get_position&type=Issues
