### ISSUE TITLE
Bitmex create order reminds the previous leverage ...

### ISSUE THREAD

**Issue by p0nt** [ccxt/ccxt#3597]
So I have something weird over here, in the documentation of Bitmex they state that every order/position initiated will defaultly receive the cross leverage.

https://www.bitmex.com/app/isolatedMargin

"Note that, by default all positions are initially set to “Cross Margin”."

But for some reason If I have ever made a trade with leverage for example 5, it does not matter if this have been initiated with the api or the webinterface, the next order I initiate will automatically create a position with leverage 5.

This results in the following issue:

- If I would create the position with more value that I actually have it would still go through since the leverage is 5x by default, if I would like to switch back to a lower leverage (which I actually wanted from the start) it will show insufficient funds because I dont have enough BTC to put it on 1x....

I understand why it is not possible to add leverage into an order, but this seems to be a big bug here ....

**Comment by kroitor** [comment]
@p0nt shouldn't this question be forwarded to BitMEX instead of CCXT? We don't change those values in the library, so if there's an issue with the above, that's on the BitMEX side. You should probably reach out for their tech support. Hope this answers your question.

**Comment by p0nt** [comment]
yes I was not able to close this for some reason, sorry to disturb

**Comment by kroitor** [comment]
@p0nt no worries... unfortunately, it's beyond the scope of the library, and we can't really fix it on our side in any way, sorry. We will be happy to answer on the library, if you have difficulties with it. But, as I said above, we don't substitute values for implicit methods, so, whatever values you get from their – those come directly from BitMEX.
