### ISSUE TITLE
bitsane error

### ISSUE THREAD

**Issue by stephenkarl** [ccxt/ccxt#3600]
While calling 'fetch_balance' or 'fetch_open_orders', i got the following error message:
**a bytes-like object is required, not 'str'**

- OS: windows
- Programming Language version: python
- CCXT version: latest
- Exchange: bitsane
- Method: fetch_balance / fetch_open_orders

**Comment by kroitor** [comment]
@stephenkarl can you please post your output and your ccxt version number?
