### ISSUE TITLE
Getting Bad request on cancelling the order in Binance

### ISSUE THREAD

**Issue by Abhishekoodles1** [ccxt/ccxt#3601]
using **api /api/v3/order**    when i am trying to cancel my order with orderId = **190427013**, for market **ETHBTC** i am getting response of BAD REQUEST.

**Comment by kroitor** [comment]
@Abhishekoodles1 unfortunately, from your report it's very hard to tell what could be causing the issue, we need your code and verbose request/response **precisely as documented here**: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue. Can you please post proper debug info and your version numbers?

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/FAQ#i-am-calling-a-method-and-i-get-an-error-what-am-i-doing-wrong

**Comment by Abhishekoodles1** [comment]
@kroitor  this is how i am making the request
 
`  Long timeStamp =new Date().getTime();
          Long orderId = Long.valueOf(id);
          String data = "symbol=ETHBTC&orderId="+190465050+"&timestamp="+timeStamp;
        try {
            String signature = GenericUtils.encode(envConfig.getBinanceSecretKey(), data);

            String url ="https://api.binance.com/api/v3/order";

            UriComponentsBuilder builderClient = UriComponentsBuilder.fromUriString(url).queryParam("symbol",marketName).queryParam("orderId", 190465050).queryParam("timestamp", timeStamp).queryParam("signature", signature);

            HttpHeaders httpHeaders = new HttpHeaders();
            httpHeaders.set("X-MBX-APIKEY", envConfig.getBinanceApiKey());
            JSONObject dataAccount = new JSONObject();
            HttpEntity<String> requestEntity = new HttpEntity<String>(dataAccount.toString(), httpHeaders);
            RestTemplate restTemplate = GenericUtils.getRestTemplate();
            ResponseEntity<String> response = restTemplate.exchange(builderClient.build().toUri().toString().trim(), HttpMethod.DELETE, requestEntity, String.class);
            logger.info("response after cancel order in binance"+response);
        }
        catch(Exception ex){
            ex.printStackTrace();
        }`

**Comment by kroitor** [comment]
@Abhishekoodles1 sorry, but this is really beyond the scope of this library. We can't really help with code that wasn't invented here. Check the sources for this library to see how this is working within CCXT. Hope this helps: https://github.com/ccxt/ccxt/blob/master/js/binance.js. Closing this for now.
