### ISSUE TITLE
Gemini fetchBalance

### ISSUE THREAD

**Issue by frankhucek** [ccxt/ccxt#3603]
- OS: High Sierra v10.13.6
- Programming Language version: Node v8.11.3
- CCXT version: 1.17.94
- Exchange: Gemini
- Method: fetchBalance

Issue:
When fetching balance from Gemini with valid API keys, receiving 400 Bad Request. Invoking the Gemini API directly with the same API key works perfectly fine. GDAX and Binance are responding correctly when invoked the exact same way as Gemini through ccxt. Rate limiting should not be an issue here, as I am sending out only single requests at a time, but either way, the enableRateLimit property has been set.

Code:
```
  let exchangegem = new ccxt.gemini({
    enableRateLimit: true,
    apiKey: gemApiKey.key,
    secret: gemApiKey.secret
  });
  let balancegem = await exchangegem.fetchBalance();
  console.log('GEMINI BALANCE');
  console.log(balancegem);
```

Response:
```
{ Error: gemini POST https://api.gemini.com/v1/balances 400 Bad Request {"result":"error","reason":"InvalidNonce","message":"Nonce '1533831705' has not increased since your last call to the Gemini API."} (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)
```

**Comment by kroitor** [comment]
@frankhucek from your output it looks like your Gemini instance is sending the nonce in seconds, whereas it should be in milliseconds with current code: https://github.com/ccxt/ccxt/blob/master/js/gemini.js#L346

So, the number should've been 1533831705000 instead of 1533831705...
Are you sure that the gemini file has not been tampered with on your system? Does the above happen with a clean reinstall?

**Comment by frankhucek** [comment]
Fresh install of ccxt yielded same results.

```
$ npm view ccxt version
1.17.95
```

**Comment by kroitor** [comment]
@frankhucek can you show/verify the runtime version as well?

```JavaScript
console.log (require ('ccxt').version)
```

**Comment by frankhucek** [comment]
```
console.log (require ('ccxt').version)
```
Returned an older runtime. This was due to some issues with upgrading because of a system config, I but managed to do it, and that solved this particular issue with Gemini. Thank you for the help!

**Comment by kroitor** [comment]
@frankhucek thx for reporting back!
