### ISSUE TITLE
'filled' exception while placing orders, without them being executed at all

### ISSUE THREAD

**Issue by dbzalpha** [ccxt/ccxt#3607]
Dears, what is this 'filled' exception knowing that both orders where placed and not executed at all?
Thanks!

- OS: MacOS 10.13.1
- Programming Language version: Python 3.6
- CCXT version: 1.14.224
- Exchange: bitstamp, kraken
- Method: create_limit_sell_order / create_limit_buy_order

```
func = self.exchanges[exchange].create_limit_sell_order
try:
    response = await func(pair, qty, price)```
except Exception as e:
    print('we got an Unhandled Exception (%s) on %s at %s' %(e, func.__name__, time.time()))
```
Result in:
##on Bitstamp
{'id': '1971608317',
 'info': {'amount': '0.00300000',
          'datetime': '2018-08-09 17:52:56.572236',
          'id': '1971608317',
          'price': '5313.50',
          'type': '0'}}
we got an Unhandled Exception (**'filled'**) on create_limit_buy_order at 1533837176.702532
##on KRAKEN
{'id': 'OX54NY-XTNM2-OVGIQM',
 'info': {'error': [],
          'result': {'descr': {'order': 'sell 0.00300000 XBTEUR @ limit '
                                        '5919.8'},
                     'txid': ['OX54NY-XTNM2-OVGIQM']}}}
we got an Unhandled Exception (**'filled'**) on create_limit_sell_order at 1533837177.48041

**Comment by kroitor** [comment]
@dbzalpha can you please post your verbose request/response (without your keys), as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

```Python
self.exchanges[exchange].verbose = True # ←------------------ add this
func = self.exchanges[exchange].create_limit_sell_order
response = await func(pair, qty, price)```
```

Post both the request and response here, plz.

**Comment by kroitor** [comment]
@dbzalpha i'd recommend to start with a basic example: https://github.com/ccxt/ccxt/blob/master/examples/py/async-bitstamp-create-limit-buy-order.py

```Python
# -*- coding: utf-8 -*-

import asyncio
import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt.async_support as ccxt  # noqa: E402


async def test():

    exchange = ccxt.bitstamp({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET',
        'enableRateLimit': True,
    })

    response = None

    try:

        await exchange.load_markets()
        exchange.verbose = True  # for debugging

        symbol = 'BTC/USD'  # change for your symbol
        amount = 1.0        # change the amount
        price = 6000.00     # change the price

        try:

            response = await exchange.create_limit_buy_order(symbol, amount, price)

        except Exception as e:
            print('Failed to create order with', exchange.id, type(e).__name__, str(e))

    except Exception as e:
        print('Failed to load markets from', exchange.id, type(e).__name__, str(e))

    await exchange.close()
    return response

if __name__ == '__main__':
    print(asyncio.get_event_loop().run_until_complete(test()))
```

Does that work for you with your values? ANyways, we will need to see your verbose request/response (without the keys), please make sure to post is as described in the CONTRIBUTING doc linked above.

**Comment by dbzalpha** [comment]
Dear @kroitor, I'm now familiar with placing orders  asynchronously, even if my code is surely not very clean, I'm still a newbie. Here it is with better information I guess:

Request: POST https://api.kraken.com/0/private/AddOrder {'API-Key': 'edited', 'API-Sign': 'edited', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} nonce=1533850894968&pair=XXBTZEUR&type=sell&ordertype=limit&volume=0.003&price=6039.7

Response: POST https://api.kraken.com/0/private/AddOrder 200 <CIMultiDictProxy('Date': 'Thu, 09 Aug 2018 21:41:36 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '447d633d98144b1b-GRU')> {"error":[],"result":{"descr":{"order":"sell 0.00300000 XBTEUR @ limit 6039.7"},"txid":["OL2PUP-XZWOO-7HPP2Z"]}}
{'id': 'OL2PUP-XZWOO-7HPP2Z',
 'info': {'error': [],
          'result': {'descr': {'order': 'sell 0.00300000 XBTEUR @ limit '
                                        '6039.7'},
                     'txid': ['OL2PUP-XZWOO-7HPP2Z']}}}
we got an Unhandled Exception ('filled') on create_limit_sell_order at 1533850896.093801

**Comment by kroitor** [comment]
@dbzalpha i suggest to try my example first, does it work for you?

**Comment by kroitor** [comment]
Also, your version seems to be **VERY OLD**. You should update to the most recent one.

**Comment by dbzalpha** [comment]
OK, will update to the last version tomorrow and will keep you posted!
Cheers

**Comment by kroitor** [comment]
@dbzalpha ok, then, I'd close this for now, feel free to reopen this if needed, or just ask further questions... We'll be happy to hear from you tomorrow. However, when posting, please, pay attention to the above instructions.
