### ISSUE TITLE
New Exchange: Huobi Australia

### ISSUE THREAD

**Issue by aeberr** [ccxt/ccxt#3615]
API Doc: https://huobiaustralia.readme.io/docs/getting-started
URL: https://www.huobi.com.au/
Fee: --
Volume: --
Address: Australia
Company Info: Huobi Australia
TNC: --
Registration: --
Based Country: Australia
Whitepaper: --
Priority: normal
Github group: --
Note: ranked top : NA
Type: Centrailzed Ex
Discussion: --

**Comment by An-Net** [comment]
https://www.huobi.com.au/notice/detail/#id=972
<img width="1440" alt="Снимок экрана 2021-05-18 в 00 21 34" src="https://user-images.githubusercontent.com/51840849/118558263-0cdd1380-b76f-11eb-840b-f7f03a25a0f1.png">
