### ISSUE TITLE
Retrieve response headers

### ISSUE THREAD

**Issue by p0nt** [ccxt/ccxt#3616]
Is it possible to retrieve the response headers on both good and false api calls you make for Bitmex?

```
{
  "date": "Fri, 10 Aug 2018 09:54:59 GMT",
  "content-encoding": "gzip",
  "x-powered-by": "Profit",
  "etag": "W/\"2-l9Fw4VUO7kr8CvBlt4zaMCqXZ0w\"",
  "x-ratelimit-remaining": "149",
  "content-type": "application/json; charset=utf-8",
  "status": "200",
  "x-ratelimit-reset": "1533894900",
  "x-ratelimit-limit": "150",
  "strict-transport-security": "max-age=31536000; includeSubDomains"
}
```

**Comment by creslinux** [comment]
I think the response headers are available for the last request in your exchange object. 

Take a look in, if named your object exchange object `ccxt`: 
`ccxt.last_response_headers._store`

**Comment by p0nt** [comment]
Thank you Thank you!

**Comment by kroitor** [comment]
@creslinux thx so much for your help! )
