### ISSUE TITLE
How to check if deposits/withdrawals are enabled on a coin ?

### ISSUE THREAD

**Issue by xCuri0** [ccxt/ccxt#3618]
There doesn't seem to be a way to do this currently. My arbitrage bot requires this because currencies with a large price difference often have deposits/withdrawals disabled

**Comment by frosty00** [comment]
You could log in to the exchange. Some websites have scrapable stuff like https://hitbtc.com/system-health. 

The active flag in `.currencies` and `.markets` should be checked but exchange's provide a limited amount of info from their API's usually. 

Binance has a really hard captcha, but by trying `fetch_deposit_address` on all the currencies you can usually filter out the ones whose deposit is disabled.

**Comment by kroitor** [comment]
@xCuri0 as @frosty00 correctly noted, not all exchanges will serve that info from their API, but for the ones that do serve it, you can check the currencies' `active` flag, which is false if funding (both deposits and withdrawals) is disabled, `true` if funding is enabled.

```
exchange.loadMarkets ()
console.log (exchange.currencies['BTC']['active'])
```

Let us know if that does not answer your question. Thx!

**Comment by npomfret** [comment]
@kroitor i want to update the currencies in wex as all withdrawals are disabled and have been for months.  Struggling to see the _right_ way to do it though... The implementation extends liqui, which doesn't directly update the currencies.  Could you please suggest where in the wex implementation I can add the `'active' = false` flag to each currency?

**Comment by npomfret** [comment]
@kroitor same question for ANX pro... a lot of their fiat currencies have no deposits or withdrawals.  Although this data might be available from their api

**Comment by kroitor** [comment]
@npomfret 

>  Could you please suggest where in the wex implementation I can add the 'active' = false flag to each currency?

Wex will need it's own implementation of `fetchCurrencies` in this case.

> Although this data might be available from their api

Do you mean, their API v2? Will check for that.

**Comment by npomfret** [comment]
> Do you mean, their API v2?

I can't quite remember which API call this information is in, but I'm sure I've seen it.  From memory, they have quite a lot of detail in their _metadata_ api endpoints.

**Comment by npomfret** [comment]
@kroitor rearing the ANX metadata: https://anxpro.com/api/3/currencyStatic

**Comment by npomfret** [comment]
@kroitor is it possible to mix calls from different versions of the API in a single implementaiton?
