### ISSUE TITLE
Is there a way to do a reverse lookup of a currency symbol?

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#3622]
I want to know what the exchange symbol is for a common currency symbol.  I can't use the `exchange.commonCurrencies` map because it contains defaults (such as `XBT: 'BTC'`) which aren't correct for say _binance_ exchange.  Is there a method that provides this?

- Programming Language version: js
- CCXT version: 1.17.87
- Exchange: binance

**Comment by creslinux** [comment]
In your ccxt exchange object there is commonCurrencies which is a dict of this information

**Comment by npomfret** [comment]
as I said, i can't use `commonCurrencies` because it gets merged with some incorrect defaults.

However, i have now found a method that is supposed to do it `exchange.currencyId`.  Doesn't seem to be working 100% of the time, I guess because some currencies are missing from `commonCurrencies`.  Specifically...

coinfloor :
`exchange.currencyId('BTC')` returns _BTC_, but should return _XBT_.

dsx:
The EURS markets are mapped incorrectly.  For example the _ltceurs_ market is mapped to _LTC/EUR_, when it should be _LTC/EURS_:

```
{ ...
  id: 'ltceurs',
  symbol: 'LTC/EUR',
  base: 'LTC',
  quote: 'EUR',
  info:
   { ...
     quoted_currency: 'EURS',
     base_currency: 'LTC' } }

```

**Comment by creslinux** [comment]
Apologies, I didn't read your questions fully. 

You may later run in to other challenges where the same symbol is used on different exchanges for different tokens.  The classic example is bitcoin-cash and bitconnect 

`BCH` and `BCC` are aliases of `bitcoin-cash` tokens
`BCC` can also be  `Bitconnect` tokens

**Comment by npomfret** [comment]
I unserstand.  The problem is some missing mappings.  How do I report them?  On here I guess.

**Comment by creslinux** [comment]
Here is perfect the place.  
@kroitor  is super responsive, he's usually online later in the evening, to my time zone.  
Im Kyiv, Ukraine. +3

**Comment by kroitor** [comment]
@npomfret 

> I want to know what the exchange symbol is for a common currency symbol. I can't use the exchange.commonCurrencies map because it contains defaults (such as XBT: 'BTC') which aren't correct for say binance exchange. Is there a method that provides this?

```
await binance.loadMarkets ();
console.log (binance.currencies['BTC']['id']); // print the exchange id for "BTC"
console.log (binance.markets['BTC/USDT']['id']); // print the exchange id for "BTC/USDT"
```

- https://github.com/ccxt/ccxt/blob/master/examples/js/symbols.js

<img width="824" alt="screen shot 2018-08-11 at 17 52 03" src="https://user-images.githubusercontent.com/1294454/43992977-663f172c-9d8f-11e8-8ee7-01c03f8d78ee.png">

<img width="518" alt="screen shot 2018-08-11 at 17 52 22" src="https://user-images.githubusercontent.com/1294454/43992981-6a0f0254-9d8f-11e8-8360-cd543833344a.png">

Let us know if it does not answer your question.
