### ISSUE TITLE
missing metatadata

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#3624]
Hi

I'm new to this project.  Just testing it out and finding a few things that don't seem right.  I assume this is the place to report them as I go.

both DSX and Coinfloor appear to have some missing currency mappings (maybe?). Details are here https://github.com/ccxt/ccxt/issues/3622, but basically, coinfloor should have XBT mapped to BTC, and dsx doesn't seem to model USDT and EURS markets correctly.

**Comment by kroitor** [comment]
@npomfret hi! 

- Coinfloor: https://github.com/ccxt/ccxt/issues/3622 (how to get the mappings for an exchange)
- DSX is currently broken (they've updated their API, which is not reflected in CCXT yet)

Let us know if it does not answer your question:

**Comment by kroitor** [comment]
P.S. This may also be a misunderstanding of "missing metadata", it is not missing as was answered here: https://github.com/ccxt/ccxt/issues/3622#issuecomment-412280219

**Comment by npomfret** [comment]
@kroitor thanks for the reply.

I've looked at the source for examples/js/symbols.js and it uses the `exchange.currencies` to map between symbols.  However, for coinfloor it still has ` BTC:  { id: 'BTC', ...`, which is wrong it think?  Coinfloor uses _XBT_ for bitcoin.

**Comment by kroitor** [comment]
> which is wrong it think? Coinfloor uses XBT for bitcoin.

Yep, there might still be some inconsistencies there, I'll look into it and will add a patch for it. Thx for pointing that out!

**Comment by npomfret** [comment]
Thanks @kroitor 

Have you guys ever discussed moving the static data (that can't be got from an api call) out into a separate project so that it can be updated without needing to do a release?

**Comment by kroitor** [comment]
> Have you guys ever discussed moving the static data (that can't be got from an api call) out into a separate project so that it can be updated without needing to do a release?

We did, but that would require a scalable infrastructure to serve the data 24/7/365. And a ton of extra requests. Ultimately, this is way less robust.

**Comment by npomfret** [comment]
@kroitor understood.  Thanks.  So what's the release process?

**Comment by kroitor** [comment]
@npomfret on the release process itself, see this issue in particular: https://github.com/ccxt/ccxt/issues/3481 ) Hope it answers the question )

**Comment by npomfret** [comment]
Regarding

> We did consider that, but that would require a scalable infrastructure to serve the data 24/7/365

Did you consider putting the metadata into a stand alone npm package?

**Comment by npomfret** [comment]
@kroitor did you get round to fixing the mapping of BTC/XBT in the coinfloor implementation?

**Comment by kroitor** [comment]
@npomfret sorry for a long wait, I've uploaded a fix for it, the currency id should now be ok as of 1.17.249. Thx again for your help!
