### ISSUE TITLE
Bitmex Leverage Fetch

### ISSUE THREAD

**Issue by TensorTom** [ccxt/ccxt#3627]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version: php7
- CCXT version: latest
- Exchange: bitmex
- Method: $exchange->fetch_balance ();

I need to query and get what the current account's leverage is set to (1,3,5,50,100) so I thought it might be in the balance query. I do see a value there called `["marginLeverage"]` but it's always set to `int(0)`

How can get him leverage?

**Comment by kroitor** [comment]
1. Read about working with implicit methods: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

2. Read BitMEX docs: https://www.bitmex.com/api/explorer/#!/Position/Position_get

![screen-shot-2018-08-12-at-01 07 18-001](https://user-images.githubusercontent.com/1294454/43996517-ecdb82ce-9dcc-11e8-9b2f-cf504a3b8dae.jpg)

3. Read BitMEX docs: https://www.bitmex.com/api/explorer/#!/User/User_getMargin

![screen-shot-2018-08-12-at-01 10 37-002](https://user-images.githubusercontent.com/1294454/43996519-f29a8c28-9dcc-11e8-8ba5-c76e518fc6fc.jpg)

4. Call it in PHP with proper arguments:

```PHP
$exchange_id = 'bitmex';
$exchange_class = "\\ccxt\\$exchange_id";

$exchange = new $exchange_class (array (
    'apiKey' => 'YOUR_API_KEY',
    'secret' => 'YOUR_SECRET',
    'enableRateLimit' => true,
});

echo print_r ($exchange->private_get_user_margin(array ('currency' => 'XBt')), true) . "\n";
```

5. Let us know if the above does not help )

**Comment by TensorTom** [comment]
thanks. Consider making a unified leverage method? I think most exchanges either have leverage or plan to add it.

**Comment by kroitor** [comment]
@TensorTom there's just so many aspects of it to consider )) we do this gradually, unification of most common things (spot trading) first, then the more complex margin/positional/leveraged trading, futures, etc... Your contributions are welcome: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md ;)

**Comment by TensorTom** [comment]
Actually, that didn't return what leverage is set to either. I'm starting to think it can't be done. I went looking through those bitmex API methods. nothing jumping out at me. Will have my users specify for now and continue looking I suppose.

**Comment by kroitor** [comment]
Well, the leverage is nothing more than a ratio of the size of your position to your initial margin with that position or vice versa (whatever is more convenient for your application). And the initial margin of a position is set to the greater of initial margin or maintenance margin.

**Comment by cryptoflipper** [comment]
Isn't it in private_get_position?

    {
        "account": 170548,
       ...
        **"leverage": 10,**
}
