### ISSUE TITLE
Bitmex Ticker Forbidden

### ISSUE THREAD

**Issue by TensorTom** [ccxt/ccxt#3629]
This was quickly marked closed/duplicate but the wrong version number was placed in the issue.

- OS: nix
- Programming Language version: php7
- CCXT version: latest
- Exchange: bitmex
- Method: $exchange->fetch_ticker()

Trying to get the ticker for BTC/USDT and I get this exception

`bitmex GET https:\/\/www.bitmex.com\/api\/v1\/quote\/bucketed?symbol=XBTUSD&binSize=1d&partial=1&count=1&reverse=1 403 <html>\r\n<head><title>403 Forbidden<\/title><\/head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden<\/h1><\/center>\r\n<\/body>\r\n<\/html>\r\n"}`

```
$exchangeName = 'bitmex';
$objName = "\ccxt\\$exchangeName";

				date_default_timezone_set('UTC');
				$exchange = new $objName (array (    // $exchange = new \ccxt\bitmex (array (
					// 'verbose' => true, // for debugging
					'apiKey' => $keyO->key,
					'secret' => $keyO->secret,
					'timeout' => 30000,
					'enableRateLimit' => true
				));
				//var_dump($exchange->private_get_user_margin(array ('currency' => 'XBt') ));
				try{
					var_dump ($exchange->fetch_ticker ('BTC/USD') );
				}catch (\ccxt\NetworkError $e) {
					returnError($e->getMessage () );
				} catch (\ccxt\ExchangeError $e) {
					returnError($e->getMessage () );
				} catch (Exception $e) {
					returnError($e->getMessage () );
				}
```

**Comment by kroitor** [comment]
I suggest that we proceed here: https://github.com/ccxt/ccxt/issues/3628 (duplicate issue) ;)
