### ISSUE TITLE
Bitfinex wallet transfer needs to pass Decimal

### ISSUE THREAD

**Issue by lellywang** [ccxt/ccxt#3637]
- OS: Mac
- Programming Language version: Python 3.6
- CCXT version: 1.13.2
- Exchange: bitfinex
- Method: privatePostTransfer

When i try to transfer from exchange to margin, which is 'trading' wallet, I have to pass in the Json: `client.privatePostTransfer({'amount': '.01','currency': 'btc', 'walletfrom': 'exchange', 'walletto': 'trading'})`

but the endpoint only takes Decimal objects, which I can't pass through in the json, for the amount as given by this error:

`ccxt.base.errors.InvalidOrder: bitfinex {"message":"Key amount should be a decimal number, e.g. \"123.456\""}`

**Comment by kroitor** [comment]
@lellywang have you tried `'amount': '0.01'` instead of `'.01'` ?

**Comment by lellywang** [comment]
Oh that fixed it, thank you, now I'm getting 

`[{'status': 'error', 'message': 'BTC cannot be used for Margin Trading. Transfer to Margin wallet not possible.'}]`

but I'm assuming that's some kind of issue on bitfinex end, let me know please if you've seen this before

**Comment by lellywang** [comment]
I solved it by using capitalized form 'BTC' instead of 'btc'! if anyone is looking around

**Comment by kroitor** [comment]
@lellywang thx for reporting back!
