### ISSUE TITLE
Bitfinex BTCUSD Longs/Shorts

### ISSUE THREAD

**Issue by AdvaithD** [ccxt/ccxt#3648]
How do I get BTCUSD shorts/longs data from Bitfinex?

- OS: Mac
- Programming Language version: Node v8.11.3
- CCXT version: 1.17.122
- Exchange: Bitfinex
- Method: Longs/shorts

**Comment by kroitor** [comment]
You can call any of their methods with implicit API methods, as documented here: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods, thus you can call any of their endpoints from here: https://bitfinex.readme.io/v1/reference. CCXT does support all of them. So you simply find the info you need for "longs" and "shorts" in the docs for a corresponding endpoint and issue an implicit call from there. Let us know if that does not answer your question.
