### ISSUE TITLE
Bit-Z api upgraded to v2

### ISSUE THREAD

**Issue by rjruigrok** [ccxt/ccxt#3650]
Bit-Z has upgraded its api to v2. 

The old documentation for v1 is removed, but I can confirm the code still works. V1 lacks some trading functionality, like retrieving your own trade history. v2 supports this. 
 
https://support.bit-z.pro/hc/en-us/articles/360007423294-Bit-Z-API-Upgrade-Introduction

**Comment by Zyn0423** [comment]
The API failed on March 31

**Comment by Zyn0423** [comment]
The API lapsed on August 31 @kroitor

**Comment by Zyn0423** [comment]
The new API request is invalid
![image](https://user-images.githubusercontent.com/39515741/44376885-07562e80-a52d-11e8-8b20-1006425dd8a7.png)

![image](https://user-images.githubusercontent.com/39515741/44376920-37053680-a52d-11e8-9bd3-ee782265c4fe.png)
![image](https://user-images.githubusercontent.com/39515741/44376929-497f7000-a52d-11e8-9e0e-1ce74298378b.png)

**Comment by toooni** [comment]
@kroitor trades do not seem to work yet. I tried with just changing to `tradePostAddEntrustSheet` on https://github.com/ccxt/ccxt/blob/master/js/bitz.js#L770 but it seems like there's an other issue as well. I do get error code `-105` (`Invalid api signature`).

**Comment by kroitor** [comment]
@toooni yep, that's a minor leftover, will add one more fix right away.

**Comment by kroitor** [comment]
@toooni ok, should work normally from 1.17.225. Thx!
