### ISSUE TITLE
truncate_to_string issue

### ISSUE THREAD

**Issue by orikalinski** [ccxt/ccxt#3652]
Hi, 

There is an issue in truncate_to_string method in exchange.py
`'%f' % Decimal(num)`
![image](https://user-images.githubusercontent.com/18344939/44118772-e0056a88-a01f-11e8-9035-ca2b0f3e8cbc.png)

you might want to consider to replace it with 
`("{0:.%df}" % precision).format(Decimal(num))`
![image](https://user-images.githubusercontent.com/18344939/44119548-40baf4c2-a022-11e8-9510-9e4dd47a9759.png)

This one causes an issue with precision in BitMEX exchange for example.

btw, can you explain if there is any reason that you're converting num into Decimal?

**Comment by kroitor** [comment]
> This one causes an issue with precision in BitMEX exchange for example.

Thx so much for reporting! Uploaded a fix for it, should be available in 5-10 minutes as of version 1.17.125. The `truncate_to_string` method itself is deprecated, it was a rudimentary solution, but we now have decimal_to_precision instead, and we're migrating to it everywhere. The `truncate_to_string` is used in BitMEX only. And yes, as you correctly noted in the neighboring issue, it has a yet-unsolved issue with non-decimal precisions with lot sizes not being powers of ten, like 0.5, 0.2, etc... 

> btw, can you explain if there is any reason that you're converting num into Decimal?

Oh, that's just because:

```
mbp:python igorkroitor$ python
Python 2.7.13 (default, Jun  5 2017, 10:04:07)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from decimal import Decimal
>>> ("{0:.%df}" % 8).format('123')  ←----------------- format does not like strings
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Unknown format code 'f' for object of type 'str'
>>> ("{0:.%df}" % 8).format(Decimal('123'))
'123.00000000'
>>>
```

**Comment by orikalinski** [comment]
Thanks for the quick push!

> btw, can you explain if there is any reason that you're converting num into Decimal?

Maybe I haven't myself well, I asked why did you use Decimal instead of float convertion. Decimal has some unexpected behavior in some cases

`In [25]: 1e-08
Out[25]: 1e-08

In [26]: Decimal(1e-08)
Out[26]: Decimal('1.0000000000000000209225608301284726753266340892878361046314239501953125E-8')

In [27]: float(1e-08)
Out[27]: 1e-08
` 
both of them convert string into number

**Comment by kroitor** [comment]
@orikalinski yep, good point, indeed, we could've used float() there, I don't really recall why we put Decimal there, I guess it was during the times when we were trying to quickfix those nasty precision-formatting issues and did shuffle the code around... So, I will look into it more closely a bit later and will cut the Decimal out if it does not belong there.
