### ISSUE TITLE
New Exchange: CryptalDash 

### ISSUE THREAD

**Issue by jackfitzgerald** [ccxt/ccxt#3662]
URL: https://www.cryptaldash.com/
API: https://api.cryptaldash.com/index.html

**Comment by kroitor** [comment]
https://www.cryptowisser.com/exchange/cryptaldash/
<img width="970" alt="Screenshot 2021-11-07 at 20 11 30" src="https://user-images.githubusercontent.com/1294454/140654709-62f9e362-60ba-448a-b373-e2429ced6abf.png">
