### ISSUE TITLE
New Exchange: profitfy (https://profitfy.trade/)

### ISSUE THREAD

**Issue by htadashi** [ccxt/ccxt#3664]
api doc: https://profitfy.trade/Home/Api
url: https://profitfy.trade/
fees: https://profitfy.trade/Home/TaxasPrazos
based country: Brazil

Still has low volumes, but the negative maker fee should interest some. I can help if translation of the documentation is needed.

**Comment by htadashi** [comment]
PR https://github.com/ccxt/ccxt/pull/4430/commits/12910a80a881634fe057a4766efe902699bc004e seems to close this issue. Could it be merged to the main branch or it needs further review?

**Comment by frosty00** [comment]
exchange cannot be reached via the url
