### ISSUE TITLE
BTCMarkets API upgrade

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#3666]
BTCMarkets are upgrading their API by the look of it. There are 3 new /v2 end points available.  Previously I only ever managed to get the most recent 200 items - they claim that's fixed now.

https://github.com/BTCMarkets/API/issues/145#issuecomment-413374596

**Comment by ahmohamed** [comment]
I am in the process of implementing that. Hopefully, I make a pull request sometime next week.

**Comment by npomfret** [comment]
@ahmohamed I've bene contacted by the BTCMarkets team recently to let me know that the API has been updated again.  Looks like you can get all open orders now in a single call:

https://github.com/BTCMarkets/API/wiki/Trading-API#open-orders-1

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/pull/3705

**Comment by kroitor** [comment]
Replaced with v3: https://github.com/ccxt/ccxt/pull/7372
