### ISSUE TITLE
Bitbay (zonda) and TheRockTrading hasn't methods^ fetchOrder, fetchOrders

### ISSUE THREAD

**Issue by bohdanz1997** [ccxt/ccxt#3668]
- CCXT version: 1.17.134
- Exchange: Bitbay, TheRockTrading
- Method: fetchOrder, fetchOrders

Both exchanges provide api endpoints for fetching list of orders:
Bitbay: https://bitbay.net/en/private-api
TheRockTrading: https://api.therocktrading.com/doc/v1/index.html#api-Trading_API-ListOrders

So we need to add this method to each exchange implementation

**Comment by kroitor** [comment]
Your contributions and PRs are welcome! )

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#pending-tasks
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

<img width="1505" alt="screen shot 2018-08-17 at 13 46 59" src="https://user-images.githubusercontent.com/1294454/44262520-08811600-a224-11e8-907f-5f22a9ae5895.png">

**Comment by pcriadoperez** [comment]
Closing this issue as support has been added
