### ISSUE TITLE
Binance get all order history

### ISSUE THREAD

**Issue by ilman** [ccxt/ccxt#3675]
- OS: Windows 10
- Programming Language version: PHP 7.1.11
- CCXT version: 1.13.78
- Exchange: Binance

Hi, first of all, thanks for this wonderful repo!

Though I am wondering whats the best way to get all my recent orders, or all my previous orders using ccxt.

I tried using fetch_closed_orders and fetch_my_trades, but both only work if the symbol specified. Is there any method similiar as fetch_open_orders which require no symbol for this?

Best Regards

**Comment by alvaroyanes** [comment]
Hi ilman!

You can try: 

`exchange.options["warnOnFetchOpenOrdersWithoutSymbol"] = false;`

Then will be possible to call  `fetch_open_orders` without specifying the symbol.

**Comment by kroitor** [comment]
> Is there any method similiar as fetch_open_orders which require no symbol for this?

No. Half of the exchanges will require a symbol for those calls. You will have to remember which orders you have placed, and then you have to check those particular symbols for updates in the orders with `fetch`-methods. In other words, you will have to fetch them one-by-one for all symbols of your interest, therefore you will either fetch the data for all binance symbols sequentially, or filter all markets  and fetch only the data for the filtered ones (according to your own filtering rules).

Let us know if that does not answer your question.
