### ISSUE TITLE
can't find module assert or crypto on react native 

### ISSUE THREAD

**Issue by elanpang** [ccxt/ccxt#3679]
- OS:MacOs
- Programming Language version: React Native 0.56-iOS
- CCXT version:1.17.140
- Exchange:N/A
- Method:N/A

Before I used ccxt with react native(old version is 1.15.9), it works well, but recently after I updated ccxt to the last version(1.17.140), a issue happened that I can't use it in React Native anymore.
It reported can't find module 'assert' or module 'crypto' , I tried all the steps that suggested in the red issue report page, but still not work. 

Is there anyone else having the same issue or Is there anyone could help me ?

![screen shot 2018-08-19 at 00 08 26](https://user-images.githubusercontent.com/6789154/44301102-1cbc3480-a344-11e8-9ab6-4ae1c729f11e.png)
![screen shot 2018-08-19 at 00 09 41](https://user-images.githubusercontent.com/6789154/44301116-51c88700-a344-11e8-913a-8bc0f90a8f27.png)

**Comment by elanpang** [comment]
add more info:

I tried to create a new react native project in different macbook, the issue still happened.

**Comment by elanpang** [comment]
It seems I found a solution,

First I tried to install 'assert' by npm i assert -s, 
then it report module 'crypto' issue, but install 'crypto' not work, I think the module 'crypto' is not the real need.

Then I found this link: 
[web3.js crypto` from `node_modules/web3-eth-accounts/src/index.js`: Module does not exist in the module map](https://github.com/ethereum/web3.js/issues/1095)

It seems the issue caused by web3, and below is the solution:

[How to set up web3.js with CRNA](https://gist.github.com/dougbacelar/29e60920d8fa1982535247563eb63766)

Now ccxt works for me again.

**Comment by kroitor** [comment]
@elanpang thx so much for reporting back!

**Comment by elanpang** [comment]
It reproduced in RN 0.57.1, I reported it to Web3       T.T
