### ISSUE TITLE
Fiat currencies in OKEX markets - maybe mistakable

### ISSUE THREAD

**Issue by DmitryVil** [ccxt/ccxt#3680]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10
- Programming Language version: python 3.7.0
- CCXT version: 1.17.132
- Exchange: okex
- Method: load_markets()

Good evening,
Could you please help with an unclear situation:

when I trying to load markets for okex by:

okexE = ccxt.okex()
okexMarkets = okexE.load_markets()

I got a dictionary of 586 markets (trade pairs). Some of them are pairs with fiat currency as a quote currency, like BTG/USD.
In the same time, web interface of okex exchange doesn't allow to trade such symbols.
When I asked in support, they confirmed that this exchange doesn't work with fiat currency at all.

Thank you in advance,
Dmitry

**Comment by DmitryVil** [comment]
Thank you very much, Igor

**Comment by kroitor** [comment]
@DmitryVil thx to @viktorius007 for explaining this ) I'd close this as a duplicate for now until we upload a cleaner workaround for OKEX markets (this should be soon). Will let you know, of course.
