### ISSUE TITLE
New Exchange - TheCoin.pw

### ISSUE THREAD

**Issue by daygle** [ccxt/ccxt#3682]
Hi,

Could you please add the following new exchange.

URL: https://trade.thecoin.pw
API: https://trade.thecoin.pw/API

**Comment by daygle** [comment]
Well not https://trade.multicoins.org/ - that's another exchange, rather https://trade.thecoin.pw.

**Comment by daygle** [comment]
We made some changes and we are no longer running on opentrade. New website is https://exchange.thecoin.pw

**Comment by An-Net** [comment]
Shutdown

- http://thecoin.pw/

![Снимок экрана 2020-07-22 в 14 34 17](https://user-images.githubusercontent.com/51840849/88171696-77452600-cc28-11ea-83e9-1414acf0f96a.png)
