### ISSUE TITLE
Poloniex minimun amount

### ISSUE THREAD

**Issue by JeanChai** [ccxt/ccxt#3688]
- OS: Win10
- Programming Language version: python 3.6
- CCXT version: 1.16.89
- Exchange: Poloniex  ETH/USDT
- Method: create_order

Amount is equal to minimun limit of ETH/USDT : 0.00000001
Price is 296.71716899303
Total = amount * price = 2.96e-06
But I get the following error: {"error":"Amount must be at least 0.000001."}. Obviously my total is larger than 1e-6.

**Comment by kroitor** [comment]
Dupes:

- https://github.com/ccxt/ccxt/pull/3029
- https://github.com/ccxt/ccxt/issues/2706#issuecomment-385627433

Let us know if this isn't resolved after upgrading to most recent version of CCXT.
