### ISSUE TITLE
Yobit - fetch_markets method do not return complete list of all tickers

### ISSUE THREAD

**Issue by nstoichkov7** [ccxt/ccxt#3690]
Hello,
First I want to congratulate ccxt team for the good work. You are the best dudes!

I just found that when I try to fetch all markets from yobit exchange I do not receive all tickers in the response. There are a couple of missing tickers I will illustrate the issue with one of them "BTS "

This is the code that I run:
In [1]: import ccxt                                                                                                                                                           
In [2]: yobit = ccxt.yobit()                                                                                                                                                  
In [3]: mkts = yobit.fetch_markets()                                                                                                                                          
In [4]: [x['symbol'] for x in mkts if 'BTS' in x['symbol']]                                                                                                                   
Out[4]: ['XBTS/BTC', 'XBTS/ETH', 'XBTS/DOGE', 'XBTS/WAVES', 'XBTS/USD', 'XBTS/RUB']  

BTS and XBTS are two different coins on yobit

When I try to fetch all currencies directly from the yobit api at:
https://yobit.net/api/3/info
I get a response both for BTS and XBTS

- OS: Arch Linux 4.13.12.1
- Programming Language version: Python 3.6
- CCXT version: 1.17.153
- Exchange: Yobit
- Method: fetch_markets()   

Thank you

**Comment by kroitor** [comment]
Hi!

With yobit BTS is not a true BTS symbol, it actually stands for Bitshares2, which has `Bitshares2` symbol with Yobit, as described in the following duplicate issue, as well as in the Manual:

- https://github.com/ccxt/ccxt/issues/302
- https://github.com/ccxt/ccxt/search?q=yobit+bts&type=Issues
- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
- https://github.com/ccxt/ccxt/wiki/Manual#naming-consistency

```Python
mbp:python igorkroitor$ python
Python 2.7.13 (default, Jun  5 2017, 10:04:07)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> yobit = ccxt.yobit({'enableRateLimit': True})
>>> markets = yobit.fetch_markets()
>>> [x['symbol'] for x in markets if 'Bitshares' in x['symbol']]
[u'Bitshares2/USD', u'Bitshares2/ETH', u'Bitshares2/DOGE', 'Bitshares2/RUB', u'Bitshares2/WAVES', u'Bitshares2/BTC']
```

Let us know if it doesn't answer your question.
