### ISSUE TITLE
question about symbol mapping

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#3693]
As I understand it we are using coinmarketcap as  arbiter for sorting out which coin owns which 3/4 letter symbol.  The one with the highest market cap wins, the other uses its name as its symbol.

My concern is that a coin that is competing for a symbol with another, may at some point rise up the coinmarketcap ranks forcing the ccxt code to swap symbols around.  Worse still, if they have a similar rank, but go up and down slightly the symbols assigned to the currencies might repeatedly reverse.

Would using coin names ('e' Bitcoin instead of BTC) not be a more stable solution?  I know coins have been known to change names, so this isn't a perfect solution either.  But it's rare.

**Comment by kroitor** [comment]
> As I understand it we are using coinmarketcap as arbiter for sorting out which coin owns which 3/4 letter symbol. The one with the highest market cap wins, the other uses its name as its symbol.

Right.

> My concern is that a coin that is competing for a symbol with another, may at some point rise up the coinmarketcap ranks forcing the ccxt code to swap symbols around. 

We have had a couple of these issues earlier. However, this is still a pretty rare occasion when two coins have the same token and the market cap switch takes place (effectively making one of the CMC tokens overtake the unified symbol).

> Worse still, if they have a similar rank, but go up and down slightly the symbols assigned to the currencies might repeatedly reverse.

Never had this before with duplicate symbols. The situation is still possible, theoretically. But, practically, it rarely occurs, if ever. We haven't seen this (yet).

> Would using coin names ('e' Bitcoin instead of BTC) not be a more stable solution? I know coins have been known to change names, so this isn't a perfect solution either. But it's rare.

We've seen them renaming XRB←→NANO, DRK←→DASH, BCC←→BCH, but yeah, this is quite rare. The chances for a renaming are approximately the same as with dupe-symbols overtaking the marketcap, I think. Yet still, I think switching symbols from 3/4 codes to token names would add to confusion among traders and would make maintaining and debugging much harder – you'll have to map them back-and-forth, which is hard when your codenaming system differs from the rest of the world.

Let me know if this does not answer your question!

**Comment by npomfret** [comment]
Thanks @kroitor
