### ISSUE TITLE
stupid question - how do I PR the WIKI?

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#3694]
Ugh, feeling stupid. How do I contribute to the wiki?  I found a typo but couldn't figure out how to submit a PR for it.

`const deposits = await exchange.fetchWithdrawals (code, since, limit, params)`

should be:

`const withdrawals = await exchange.fetchWithdrawals (code, since, limit, params)`

... in all 3 code examples.

**Comment by kroitor** [comment]
All here: https://github.com/ccxt/ccxt/tree/master/wiki )

**Comment by npomfret** [comment]
But how do I edit/contribute to the wiki?  If I clone this repo I don't get the wiki content.  I can't figure out how to fork the project wiki (the github fork button forks the main repo)

**Comment by kroitor** [comment]
> But how do I edit/contribute to the wiki? If I clone this repo I don't get the wiki content.

If you fork this repo – do you see a "wiki" folder inside it? You can push your edits to it, and those will be uploaded to GitHub wiki by our build system automatically. So we have the "source of all truth for docs" in the wiki folder, and we never change anything in the docs outside of the wiki folder – all our edits go there, and those are propagated from there to GitHub wiki, RTD, etc... did I make it clearer now? Let me know if not )

**Comment by npomfret** [comment]
Sorry, must have had a filter hiding the files on or something.  All sorted.
