### ISSUE TITLE
ccxt.async_support with aiocfscrape

### ISSUE THREAD

**Issue by Mandelbr0t** [ccxt/ccxt#3697]
How can we use ```aiocfscrape``` with ```ccxt.async_support``` ?

Like so:

```
for name in exchange_names:
     exchange[name] = getattr(ccxt_async, name)({
               'timeout': 20000,
               'session': aiocfscrape.create_scraper(),
     })
```

aiocfscrape does not implement a ```create_scraper()``` method.
An example like in https://github.com/ccxt/ccxt/blob/master/examples/py/bypass-cloudflare.py would help alot. 

Best, Mandelbr0t

- OS: Mac Os Yosemite
- Programming Language version: Python 3.6
- CCXT version: 1.17.125
- Exchange: all
- Method: getattr with aiocfscrape

**Comment by kroitor** [comment]
Let us know if this does not help:

https://github.com/ccxt/ccxt/blob/master/examples/py/bypass-cloudflare-with-aiocfscrape.py

```Python
# -*- coding: utf-8 -*-

from aiocfscrape import CloudflareScraper
import asyncio
import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt.async_support as ccxt  # noqa: E402


def print_supported_exchanges():
    print('Supported exchanges:')
    print(', '.join(ccxt.exchanges))


async def test(id):

    print('Instantiating ' + id + ' exchange')

    session = CloudflareScraper(loop=asyncio.get_event_loop())

    # instantiate the exchange by id
    exchange = getattr(ccxt, id)({
        'timeout': 20000,
        'session': session,
    })

    markets = None

    try:

        # load all markets from the exchange
        markets = await exchange.load_markets()

    except ccxt.BaseError as e:

        print(type(e).__name__, str(e))
        print('Failed.')

    await exchange.close ()
    await session.close ()

    return markets


if __name__ == '__main__':

    try:

        id = sys.argv[1]  # get exchange id from command line arguments

        # check if the exchange is supported by ccxt
        exchange_found = id in ccxt.exchanges

        if exchange_found:

            print(asyncio.get_event_loop().run_until_complete(test(id)))

        else:

            print('Exchange ' + id + ' not found')
            print_supported_exchanges()

    except Exception as e:
        print('[' + type(e).__name__ + ']', str(e))
        print('Usage: python ' + sys.argv[0] + ' id')
        print_supported_exchanges()
```

**Comment by kroitor** [comment]
@Mandelbr0t do you have certifi installed or py packages containing `ssl` in `pip3 list` ? This is now a different issue with your local SSL setup.

**Comment by Mandelbr0t** [comment]
@kroitor certifi 2018.4.16 is installed and idna-ssl 1.1.0
It was working up until yesterday.

**Comment by kroitor** [comment]
@Mandelbr0t 

> It was working up until yesterday.

With aiohttp?

Can you try deinstalling idna-ssl 1.1.0 and/or certifi to see if makes a difference? Also, would be great if you could post your system openssl version number.

Most often this is somewhere beyond CCXT, see these issues as well:
- https://github.com/ccxt/ccxt/search?q=CERTIFICATE_VERIFY_FAILED&type=Issues
- https://www.google.com/search?q=python+CERTIFICATE_VERIFY_FAILED

**Comment by Mandelbr0t** [comment]
@kroitor  ok seems like my ssl certificates were messed up somehow between yesterday and today. I reinstalled them with ```open /Applications/Python\ 3.6/Install\ Certificates.command```
Thank you for the help!

**Comment by kroitor** [comment]
@Mandelbr0t so, the ssl issue is resolved now and everything works again, right?

**Comment by Mandelbr0t** [comment]
yep
