### ISSUE TITLE
Add tokens.net exchange

### ISSUE THREAD

**Issue by ZigaTokens** [ccxt/ccxt#3698]
URL: https://www.tokens.net
API documentation: https://www.tokens.net/api/

**Comment by JohnnySheffield** [comment]
Whats the status with this issue? I would like to contribute some development time to get this done if it will help to speed things up

**Comment by kroitor** [comment]
@JohnnySheffield your contributions are welcome!

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

**Comment by JohnnySheffield** [comment]
Here is an early wip tokens.net implementation with some of the private and public methods implemented: https://github.com/DAPowerPlay/ccxt/blob/tokens/js/tokens.js 

with an example usage here: https://github.com/DAPowerPlay/ccxt/blob/tokens/examples/js/tokens-net-example.js

@kroitor  @ZigaTokens  can i kindly ask you to provide feedback on current implementation before i go and create a pull request with more methods implemented?

**Comment by kroitor** [comment]
@JohnnySheffield Hey!) Thx for the implementation! And pardon for the delay with my reply! Would you be so kind to submit it in a standalone PR ? It would help review and merge it quicker. Thx so much for your involvement and participation, really appreciate that!

**Comment by JohnnySheffield** [comment]
@kroitor Thanks for the feedback! I'll try to have a PR ready this week - i'm still working out some details - PR coming soon™

Cheers!

**Comment by JohnnySheffield** [comment]
@kroitor soon™ is right meow! :D

**Comment by JohnnySheffield** [comment]
Oops got some changes with kraken bundled in this commit, let me fix this

**Comment by JohnnySheffield** [comment]
![tokens](https://user-images.githubusercontent.com/4224211/52278879-67fcea80-2958-11e9-9cec-94a7333a9d7e.png)

**Comment by kroitor** [comment]
https://twitter.com/TokensNet/status/1356572079718600704
