### ISSUE TITLE
Async all order books from multiple exchanges

### ISSUE THREAD

**Issue by thomas-leeee** [ccxt/ccxt#3703]
Hi I need some help regarding how to approach this issue. I am looking for an implementation that is as fast as possible.

Input: list of exchange name
Output: all order books

So I thought here is a good way:
- async coroutines for instantiating exchanges from list
- for each exchange async coroutines for all symbols

Is this the right way do do things based on the api and organization of ccxt?

**Comment by kroitor** [comment]
Hi! Let us know if this does not answer your question: https://github.com/ccxt/ccxt/blob/master/examples/py/async-orderbooks-from-multiple-exchanges-at-once.py ;)

**Comment by kroitor** [comment]
> Do you have suggestions? I have tried to create individual coroutine for different symbols, but I dont get any output from the following:

It is written in the Manual that exchanges won't allow you  to fetch all the market data in too many simultaneous code. So, if the exchange has 1000 symbols and you're trying to fetch 1000 orderbooks at once – this won't work due to rate limits: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit. So, they might ban you if you're too aggressive on their API – let's first make sure that you do understand the limitations coming from the exchanges themselves, do you?

**Comment by kroitor** [comment]
Second, there's a syntax error here:

```Python
async def GetAllOrderBooks(exchange):
    print('Fetching all order books on %s',exchange)
    client = getattr(ccxt, exchange)({'enableRateLimit': True,})
    await client.load_markets() 

    #                  ↓↓↓↓ no need for this await keyword here if you're creating coroutines
    input_coroutines = [await client.fetch_l2_order_book(symbol) for symbol in client.symbols]

    AllOrderBooks = await asyncio.gather(*input_coroutines, return_exceptions=True)
    print(AllOrderBooks)
    await client.close()
    return None
```

**Comment by thomas-leeee** [comment]
Yes I am aware of this limitation coming from exchange. But the i am trying to get the fastest rate possible: let say exchange give me 1200 calls per minute and has 1200 coins I should be able to fetch all in about a minute???

Currently my async method with the for loop is not really async if you know what I mean.

But in any case, rate limiting issue should be handled by ccxt and not by me. And I still dont understand why this is not working

` input_coroutines = [client.fetch_l2_order_book(symbol) for symbol in client.symbols]`

(I suppose the execution of this is that asyncio will execute the first

`client.fetch_l2_order_book(symbol1)`

then while waiting for the result to arrive it moves on to dispatch

`client.fetch_l2_order_book(symbol2)`

and so on up to 

`client.fetch_l2_order_book(symbolN)`

where N is controlled by ccxt rate limiting. Then after say orderbook of symbol1 has arrived another 

`client.fetch_l2_order_book(symbolN+1)`

can be dispatched.)

**Comment by kroitor** [comment]
> let say exchange give me 1200 calls per minute and has 1200 coins I should be able to fetch all in about a minute???

Yes. 

> But in any case, rate limiting issue should be handled by ccxt and not by me.

It is handled either by CCXT or by you – the choice for it is optional and also up to you. The built-in rate-limiter in CCXT works as described in the docs. Moreover, the same Manual describes controls for the built-in rate limiter that does that handling for you, like `enableRateLimit`, `rateLimit` options and even `tokenBucket`. However, without a proper configuration for rate-limiter settings according to the docs, your results will be sub-optimal, and this is again documented in the Manual for the `rateLimit` exchange property (it is set to a safer/higher sub-optimal value by default).
