### ISSUE TITLE
new Exchange BitMart

### ISSUE THREAD

**Issue by jackyxie** [ccxt/ccxt#3716]
- Exchange: BitMart
- URL: https://www.bitmart.com
-API: https://github.com/bitmartexchange/api-docs

**Comment by devsi** [comment]
See - #4913 for implementation.

**Comment by ndubel** [comment]
where I can get 'uid' on there site?

**Comment by kroitor** [comment]
@ndubel good question )) I was wondering as well... Turns out, `uid` is actually the name of the API keypair that you've entered upon creating it.

**Comment by ndubel** [comment]
don't helped for me...

**Comment by kroitor** [comment]
@ndubel try a second keypair, didn't work for me the first time either (signature error), but it worked on the second attempt with a second keypair (i found that strange as well, but didn't pay too much attention). If that doesn't help, then I have no ideas.

**Comment by kroitor** [comment]
@ndubel 

- https://github.com/bitmartexchange/bitmart-official-api-docs/blob/master/rest/authenticated/oauth.md#hmac-sha256-signature

> mymemo (memo is the name that user gave when the API was created, you can check the name by logging into bitmart.com and check API List under Account)

`uid` = `memo` in this implementation.

**Comment by ndubel** [comment]
I tried with different keys even with binded IP, but still not helps  
`bitmart wallet endpoint requires an accessToken option or a prior call to signIn()`

**Comment by kroitor** [comment]
@ndubel oh, that's a different thing, you have to call the `signIn()` method to acquire the HTTP auth bearer token, because Bitmart requires HTTP auth :\

**Comment by ndubel** [comment]
oh, yes, thank you, it helps!

**Comment by kroitor** [comment]
@ndubel 

> it helps

For 900 seconds... and then you have to call it again... every 15 minutes. We will look into calling it on demand... Your help with that is very much appreciated ;)

**Comment by karlandoh** [comment]
Apologizes for rekindling this issue but the uid has to be the keypair? Is it just the apiKey attribute? Im having trouble inputting correct uid parameters.

Thanks.

**Comment by aneudysamparo** [comment]
> @ndubel
> 
> * https://github.com/bitmartexchange/bitmart-official-api-docs/blob/master/rest/authenticated/oauth.md#hmac-sha256-signature
> 
> > mymemo (memo is the name that user gave when the API was created, you can check the name by logging into bitmart.com and check API List under Account)
> 
> `uid` = `memo` in this implementation. Let me know if that does not help.

That Worked for me

`constructor() {
    this.bitmart = new ccxt.bitmart({
      apiKey: this.key,
      secret: this.secret,
      uid: this.memo,
    });
  }`

**Comment by ryu878** [comment]
If you are using ccxt it works this way:
exchange = ccxt.bitmart({'apiKey':api_key,'secret':api_secret, 'uid':memo})

**Comment by nextmarte** [comment]
actualy, memo is the name you define when creating the api 

![image](https://github.com/ccxt/ccxt/assets/26266722/b87d5eec-83a1-40b5-bebd-537d845dece6)
