### ISSUE TITLE
question about hitbtc withdrawal fees

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#3717]
@kroitor @adi90x I notice you both have updated the hitbtc deposit fees.  I see that 2 currencies (ETH and BTC) have deposit fees.  Where did you get this info from?  Is it available from some sort of API call.

Also, I see that all deposit and withdrawal fees are coded into the exchange implementations.  I think the withdrawal fee's are available via [this](url
https://api.hitbtc.com/api/2/public/currency) api call - perhaps we could remove the hard coded ones?

**Comment by kroitor** [comment]
> I notice you both have updated the hitbtc deposit fees. I see that 2 currencies (ETH and BTC) have deposit fees.

Personally, I'm against hardcoding ) We have deprecated this approach.

> Where did you get this info from?

Most often it's coming from their withdrawal dialogs from their website.

> Also, I see that all deposit and withdrawal fees are coded into the exchange implementations.

Yep, for some exchanges they are hardcoded now. Having them like that is a bad idea. And we have to do something about it.

> I think the withdrawal fee's are available via [this](url
https://api.hitbtc.com/api/2/public/currency) api call - perhaps we could remove the hard coded ones?

Yep, we already use that info, here:

- https://github.com/ccxt/ccxt/blob/master/js/hitbtc2.js#L634
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/hitbtc2.py#L645
- https://github.com/ccxt/ccxt/blob/master/php/hitbtc2.php#L635

So, those hardcoded fees effectively get overwritten. In other words, your confusion probably comes from looking at the `fees` property in `describe()`, however, you should not rely on that property at all, as it is not documented. All fees are properties of corresponding markets and currencies, not a property of the exchange. So, we will remove those predefined fees from there soon. Let us know if that does not answer your question.
