### ISSUE TITLE
Newer versions of ccxt on x86

### ISSUE THREAD

**Issue by Cleric334** [ccxt/ccxt#3737]
Hello.

I have been having troubles recently running newer versions of ccxt on a x86 (win 7) machine.
Using a JS version, running node.js

What could be the case here? Maybe ccxt uses a newer version of node, which is not supported on x86 architecture anymore? 

Is there a way I still can run ccxt on x86?

Thanks in advance.

**Comment by kroitor** [comment]
> Is there a way I still can run ccxt on x86?

Unfortunately, not at this time, because the timestamp/nonce is in milliseconds in most cases. A milliseconds timestamp doesn't fit in 32 bits.
