### ISSUE TITLE
Multiple URLs on the website used for API

### ISSUE THREAD

**Issue by xCuri0** [ccxt/ccxt#3744]
Hi I'm trying to add unofficial trading support for CoinExchange. I have found out the trade API is at https://coinexchange.io/ like (https://www.coinexchange.io/delete/market/order) while the public API is at https://www.coinexchange.io/api/v1/ (like https://www.coinexchange.io/api/v1/getorderbook?market_id=1).

What should I do like this as I need to support both in my unofficial implementation ? You can only add one URL afaik

**Comment by kroitor** [comment]
Hi! See these examples and links on combining official APIs with unofficial web endpoints: 

- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L52
- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L68
- https://github.com/ccxt/ccxt/blob/master/js/kraken.js#L47
- https://github.com/ccxt/ccxt/blob/master/js/kraken.js#L141
- https://github.com/ccxt/ccxt/blob/master/js/bittrex.js#L42
- https://github.com/ccxt/ccxt/blob/master/js/bittrex.js#L58

↑ same in Python and PHP...

Docs:

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-structure
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#implicit-api-methods

So, CCXT does support multiple base urls as shown above. Let us know if that does not answer your question.
