### ISSUE TITLE
New Exchange: https://pro.coins.asia

### ISSUE THREAD

**Issue by AlekFranco** [ccxt/ccxt#3747]
Exchange: Coins Pro Ph
URL: https://exchange.coins.asia   or   https://pro.coins.asia/

it's the only local crypto exchange currently operating in the philippines. including it in your great api would help a lot of developers in the country.

much appreciated.

**Comment by lathanbritz** [comment]
no public trade information on this API?

**Comment by ttodua** [comment]
exchange was implemented in ccxt an year ago (https://github.com/ccxt/ccxt/pull/17217)
