### ISSUE TITLE
install error ENOGIT

### ISSUE THREAD

**Issue by steeply** [ccxt/ccxt#3748]
- OS:  Windows
- Programming Language version: node.Js 10.9
- CCXT version: 1.17.*

Installation error appeared

```
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t git://github.com/frozeman/WebSocket-Node.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.
```
In version 1.16.*, this was not

**Comment by kroitor** [comment]
You will need `git` installed: https://www.google.ru/search?q=npm+enogit, basically, the question is answered on Google a gazillion times. )
