### ISSUE TITLE
DSX exchange using NodeJS 8.x raises SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure error

### ISSUE THREAD

**Issue by ongkhua** [ccxt/ccxt#3751]
- OS: Windows 10
- Programming Language version: JS
- CCXT version: 1.17.199
- Exchange: DSX
- Method: run-test.js

When using nodejs version 8.9 , 8.10, 8.11 (LTS), running run-test.js on dsx will raise "SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure" error.  This error does not happen when using the latest version 10.x of nodejs.

I'm posting this so that anyone trying to work on DSX exchange and hits this error knows the work-around.  Update to NodeJS 10.x will solve this issue.

Should I mark this closed ?

**Comment by damian87x** [comment]
Hello, getting the same error on Dsx. Tried with Binance and works without problems. @kroitor issue is resolved? or is something with my libs

CCXT version: 1.17.378
method: loadMarkets()
node: v8.11.3

` FAIL  test/helpers/exchange.test.js
  ● Exchange adapter › when wants fetch currencies with prices

    FetchError: request to https://dsx.uk/mapi/info failed, reason: write EPROTO 140735605830528:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:

      at ClientRequest.<anonymous> (../libs/ccxt/node_modules/node-fetch/index.js:133:11)`

when trying with curl works.

Thanks

**Comment by kroitor** [comment]
@damian87x Unfortunately, it's outside of the scope of this library – it's an issue with Node 8 + SSL (and it depends on the environment and setup): https://github.com/nodejs/node/issues/16196 ← hope this helps. Alternatively, you can try upgrading to Node 9 to see if it fixes the issue.

**Comment by damian87x** [comment]
@kroitor updated node to 10.13.0 and is working now thanks!

**Comment by kroitor** [comment]
@damian87x thx for reporting! Appreciate your feedback!

**Comment by npomfret** [comment]
Solved by adding this line `require("tls").DEFAULT_ECDH_CURVE = "auto"`

> https://github.com/nodejs/node/issues/16196#issuecomment-393091912

**Comment by kroitor** [comment]
@npomfret thank you!
