### ISSUE TITLE
HitBTC fetchMyTrades returns negative value for cost 

### ISSUE THREAD

**Issue by cristianm** [ccxt/ccxt#3755]
- OS: Windows / Linux
- Programming Language version: Node 10.8.0
- CCXT version: 1.16.21
- Exchange: hitbtc2
- Method: fetchMyTrades

HitBTC returns negative value for cost {"cost":-0.0020361,"currency":"USDT"}

**Comment by adi90x** [comment]
Hello , 
I am not sure it is an error, on Hitbtc maker fees are negative : You earn money instead of paying a cost !

**Comment by kroitor** [comment]
Indeed, @adi90x is right:

<img width="1067" alt="screen shot 2018-09-01 at 13 45 15" src="https://user-images.githubusercontent.com/1294454/44945243-8d0b9100-aded-11e8-8bbb-b43691bde9bc.png">
