### ISSUE TITLE
suspect ticker volume for ZB exchange is not in base currency 

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#3760]
I noticed that the volumes presented in the ticker results for zb exchange are extremely high.   The example below for _QTUM/BTC_ shows a volume of 6854783.  I was under the impression that ticker volumes were all _supposed_ to be in the unit of the base currency, and if so then this exchange is trading like 41 billion dollars with of QTUM per day.  Which doesn't sound right.  Maybe we need to multiply the volume by the last price or something?  

Or have I misunderstood?  If so, how do you tell the currency that the volume is in?

Also, the `close` field is populated but there doesn't look to be a value for `close` in the `info` section.  Maybe this could be removed.

```
{ symbol: 'QTUM/BTC',
  timestamp: 1535531116527,
  datetime: '2018-08-29T08:25:16.527Z',
  high: 0.000694,
  low: 0.000654,
  bid: 0.000668,
  bidVolume: undefined,
  ask: 0.000669,
  askVolume: undefined,
  vwap: undefined,
  open: undefined,
  close: 0.000668,
  last: 0.000668,
  previousClose: undefined,
  change: undefined,
  percentage: undefined,
  average: undefined,
  baseVolume: 6854783.43,
  quoteVolume: undefined,
  info:
   { vol: '6854783.43',
     last: '0.000668',
     sell: '0.000669',
     buy: '0.000668',
     high: '0.000694',
     low: '0.000654' } }
```

Checking on [coinmarketcap](https://coinmarketcap.com/currencies/dash/#markets), and with a little basic math this does look to be the case

_396535DASH * 0.02777DASH/BTC * 7000BTC/USD = ~77M USD_

**Comment by kroitor** [comment]
In the code section you have QTUM/BTC, then you say:

> 396535DASH * 0.02777DASH/BTC * 7000BTC/USD = ~77M USD

Which is a bit confusing. We should first decide which one it is, QTUM or DASH )

> I was under the impression that ticker volumes were all supposed to be in the unit of the base currency

Yep, the `baseVolume` shows the volume in base currency, `quoteVolume` shows the volume in quote currency.

But anyways, if we look at the output for QTUM above, it shows a base volume of 6854783.43 QTUM:

https://github.com/ccxt/ccxt/wiki/Manual#consistency-of-base-and-quote-currencies

```
base currency ↓
             BTC / USDT
             ETH / BTC
            DASH / ETH
                    ↑ quote currency
```

https://coinmarketcap.com/currencies/qtum/

The price for QTUM is:
- 4.86 USD
- 0.000668 BTC

24 base volume turnover is:

- 6854783.43 QTUM * 4.86 = 33'314'247.46 USD = 33 million dollars, which looks ok, no?
- 6854783.43 QTUM * 0.000668 = 4578,99533124 BTC, which also looks ok, no?

<img width="780" alt="screen shot 2018-08-30 at 03 40 22" src="https://user-images.githubusercontent.com/1294454/44822990-76571580-ac06-11e8-915a-6c18a434cbff.png">



Let me know if that does not answer the question )
