### ISSUE TITLE
1broker commonCurrency DOW (crypto, forex, index & stock markets)

### ISSUE THREAD

**Issue by Esc4pism** [ccxt/ccxt#3766]
https://1broker.com/?c=de/content/api-documentation

"DOW": "Dow Jones" (or "Dow Jones 30 Industrial"?) should be added to commonCurrencies for 1broker. Could be mistaken with the DowCoin (DOW) https://coinmarketcap.com/de/currencies/dowcoin/.

https://1broker.com/?c=de/content/markets
They list crypto, forex, stock and index prices, in the current implementation there is no distinction between those categories. There might be several other pairs that could also be mistakenly named aswell, out of 74 pairs only 1 of them is a crypto-currency pair (BTC-USD), all others are forex, stocks or stock-indexes.

**Comment by Esc4pism** [comment]
possibly important update on their BTC/USD market:
https://1broker.com/api/v2/market/details.php?token=YOUR_API_KEY&pretty=true&symbol=BTCUSD

"*** NOTE: This market was moved to 1fox.com and is in watch-only mode on 1Broker. ***"



Seems like 1broker doesnt have any crypto-markets at all now, as for myself ill just disable them in my application for now, I leave the rest up to you on what to do with it, as its not really a crypto-exchange anymore.

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/issues/4072

> _1broker has been seized by FBI https://1broker.com/
