### ISSUE TITLE
Library doesn't work at js webworker context

### ISSUE THREAD

**Issue by alexsharabayko** [ccxt/ccxt#3767]
When you try to require ccxt at the webworker context, there is an error "window is not defined"

**Comment by kroitor** [comment]
@alexsharabayko can you plz make a snippet that I could use to reproduce the bug or a demo-repo with a showcase of the issue? That would be very helpful, we could then resolve it sooner.

**Comment by alexsharabayko** [comment]
@kroitor when i include ccxt in webworker bundle:
`import {binance, bitfinex, bitmex, bittrex, cex, coinbase, cryptopia, Exchange, hitbtc, huobipro, kraken, okex, poloniex} from "ccxt";`
There are a lot of places with 'window' word like these:
`if(typeof window === "object")
		g = window;`
or 
`module.exports = window.crypto`
or
`if(typeof window.Promise === 'undefined'){`
and code like this throw an exception inside webworker context.

Regards

**Comment by alexsharabayko** [comment]
Now exception throws in place
`module.exports = __webpack_require__(271)(window, loadImplementation)`

**Comment by alexsharabayko** [comment]
I also noticed, that `window` comes from third party libraries. For example **web3** use window keyword and it uses **any-promise** library that use window too.

**Comment by alexsharabayko** [comment]
Hi, i decided this problem by replacing at the final bundle all 'window' to 'self'. It can be done by webpack plugin or something similar.

**Comment by kroitor** [comment]
@alexsharabayko thx for reporting back!

**Comment by psytron** [comment]
it would be cool if ccxt.browser.js would be WebWorker safe.
Now it still gives window error.

**Comment by kroitor** [comment]
@psytron plz provide the details: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
