### ISSUE TITLE
Ability to fetch transaction history php page (similar to 'binance-fetch-balance.php')

### ISSUE THREAD

**Issue by dmittal3** [ccxt/ccxt#3769]
Hi @kroitor ,
I see that under the hood 'fetchTransactions' functions are being built. 
Is the work on fetching entire transaction history completed now for all the exchanges?

How can I fetch transaction history from any exchange via php page?
Reason is, I will be loading this from unix command prompt using:
'php -f /home/var/www/html/websiteaddress/**binance-fetch-transactions.php**'

I want to use similar method to fetch transactions as I did for balances eg. using below page under example folder:
'binance-fetch-balance.php' 

ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:Unix
- Programming Language version:php
- CCXT version:latest
- Exchange:all
- Method:

**Comment by klemensz** [comment]
Any plans to support `fetchTransactions` for Binance (JS)?

**Comment by kroitor** [comment]
@klemensz binance does not have `fetchTransactions` (deposits+withdrawals), but they have `fetchDeposits` and `fetchWithdrawals`.

**Comment by klemensz** [comment]
Ah OK. I found this and thought it might be the endpoint for fetchTransactions, but maybe it's something different... https://binance-docs.github.io/apidocs/spot/en/#get-future-account-transaction-history-list-user_data

**Comment by kroitor** [comment]
> Ah OK. I found this and thought it might be the endpoint for fetchTransactions, but maybe it's something different... https://binance-docs.github.io/apidocs/spot/en/#get-future-account-transaction-history-list-user_data

Those are not really transactions, but transfers between the accounts within the same exchange, we are adding `fetchTransfers` for those.
