### ISSUE TITLE
Deribit - Stop-Limit Orders

### ISSUE THREAD

**Issue by icehacker33** [ccxt/ccxt#3780]
- OS: Linux
- Programming Language version: JavaScript
- CCXT version: 1.17.221
- Exchange: Deribit
- Method: createOrder

Is it possible to create "stop_limit" orders in Deribit? I tried using type = "stop_limit" without success.

I tried to use something alon the lines of the code below and did not work.

```
const deribit = new ccxt.deribit({
  apiKey: XXXXXXX,
  secret: XXXXXXX
});

deribit.createOrder('BTC-PERPETUAL',"stop_limit","sell",1,"8500",{
                        "stopPx": "8600",
                        "post_only": true
                        })
```

Thanks

**Comment by vladozc** [comment]
I was facing the same issue. It looks like Deribit requires to explicitly set `execInst` option. In your case:

> deribit.createOrder('BTC-PERPETUAL',"stop_limit","sell",1,"8500",{
>                        "stopPx": "8600",
>                        "post_only": true,
>                        "execInst": "index_price"
>                        })`

https://docs.deribit.com/rpc-endpoints.html#buy

**Comment by kroitor** [comment]
Check out the new deribit v2 implementation that has been added in CCXT 1.23.88+: https://github.com/ccxt/ccxt/issues/6602
