### ISSUE TITLE
fetchOHLCV for different date ranges? 

### ISSUE THREAD

**Issue by thezoug** [ccxt/ccxt#3781]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10
- Programming Language version: Python 3
- CCXT version: 3.5.2
- Exchange: bitmex
- Method: fetchOHLCV

Goal: populate a database with historical granular OHLCV data - I would prefer to have data by the hour going back as long as I can, really.

I understand that bitmex requires a `since` parameter in the `fetchOHLCV` function in order for it to pull the most recent data, where since looks something like
`since = bitmex_market.parse8601('2018-06-31 00:00:00')
`
and
```
    candles = bitmex_market.fetch_ohlcv(symbol, timeframe, 
                                         since = since,
                                        limit = limit)
```
 but how should I go about looping thru date ranges to pull the historical data? Is there a method for that? My sense is that there should probably be some kind of 'start' 'end' parameter that we can query the API on. Couldn't find anything in the manual similar to that.

Relevant manual sections for context:
"There's a limit on how far back in time your requests can go. Most of exchanges will not allow to query detailed candlestick history (like those for 1-minute and 5-minute timeframes) too far in the past. They usually keep a reasonable amount of most recent candles, like 1000 last candles for any timeframe is more than enough for most of needs. You can work around that limitation by continuously fetching (aka REST polling) latest OHLCVs and storing them in a CSV file or in a database."

**Comment by kroitor** [comment]
Hi!

The above aspect is documented here:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
- https://github.com/ccxt/ccxt/wiki/Manual#pagination

Basically, you will have to either use datetime-based pagination or use other types of pagination + params overrides to traverse the available history of OHLCVs. 

Let us know if that along with other mentions of OHLCV in the Manual does not answer your question. Feel free to reopen it if needed or just ask further questions if you have more.
