### ISSUE TITLE
Binance, error -1104

### ISSUE THREAD

**Issue by alexeymarunin** [ccxt/ccxt#3784]
- OS: MacOS
- Programming Language version: JavaScript
- CCXT version: 1.17.222
- Exchange: Binance
- Method: createOrder

```
binance: unknown error code: {"code":-1104,"msg":"Not all sent parameters were read; read '8' parameter(s) but was sent '9'."} -1104
```
  
Just for remember, it is quite specific error

**Comment by alexeymarunin** [comment]
It happens when uses unknown fields in `params` parameter in `createOrder`
Allowed fields - https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-order--trade

**Comment by fccoelho** [comment]
> It happens when uses unknown fields in `params` parameter in `createOrder`
> Allowed fields - https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-order--trade

Such as `{'test': False}`?
