### ISSUE TITLE
Poloniex editOrder crashes if remaining is less than minimum trade amount

### ISSUE THREAD

**Issue by xCuri0** [ccxt/ccxt#3786]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Ubuntu 16.04
- Programming Language version: Python 3.5.2
- CCXT version: master
- Exchange: Poloniex
- Method: editOrder

Error is ```ccxt.base.errors.InvalidOrder: poloniex {"success":0,"error":"Total must be at least 1."}```

**Comment by kroitor** [comment]
This is the issue with Polo limits, as described here:

- https://github.com/ccxt/ccxt/issues/2706#issuecomment-390529874

Duplicate:

- https://github.com/ccxt/ccxt/issues/3706

I suggest to move this discussion to #3706, if you don't mind.

**Comment by xCuri0** [comment]
@kroitor I set amount to None though and looking at the ccxt source it doesn't send amount if its None so I think its an issue on Poloniex's end
