### ISSUE TITLE
bitz  502 not accessible 

### ISSUE THREAD

**Issue by maverickPIG** [ccxt/ccxt#3787]
**bitz has change api url, all method return 502 not accessible ...**

ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: centos 7.4
- Programming Language version: php
- CCXT version: 1.17.214
- Exchange: bitz
- Method: all method

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/3650
