### ISSUE TITLE
OkCoin - error in fetching transaction information - fetchOrder()

### ISSUE THREAD

**Issue by DmitryVil** [ccxt/ccxt#3790]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: windows 10
- Programming Language version: python 3.7
- CCXT version: 1.17.225
- Exchange: okcoinusd
- Method: fetchOrder()

Good night,

I can't fetch information about successful transactions I did.
I suppose this problem exists only for a few days.

I made a transaction and got the answer from the OkCoin:
{"info": {"result": true, "order_id": 59509}, "id": "59509", "timestamp": 1535990406564, "datetime": "2018-09-03T16:00:06.564Z", "lastTradeTimestamp": null, "status": null, "symbol": "ETH/BTC", "type": "market", "side": "buy", "price": 0.001108931254206929, "amount": 0.028, "filled": null, "remaining": null, "cost": null, "trades": null, "fee": null}

For fetching TX info I use the code:
-----------------------------------------------------------------------------
id = '59509'
    symbol = 'ETH/BTC'
    type = 'BUY'

    flrID = 'okcoinusd'
    flr = getattr(ccxt, flrID)()
    ......
    flr.verbose = True

    sg = asyncio.get_event_loop().run_until_complete(flr.fetchOrder(
        id,
        symbol=symbol,
        params={'type': type}))
-----------------------------------------------------------------------------
And got the answer:
okcoinusd {\"result\":false,\"error_code\":10007}

Verbose info:
Request: GET https://www.okcoin.com/v2/spot/markets/products {'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://www.okcoin.com/v2/spot/markets/products 200 <CIMultiDictProxy('Date': 'Mon, 03 Sep 2018 21:39:57 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=dd04e8f81c6cc731383676332f6c94c371536010797; expires=Tue, 03-Sep-19 21:39:57 GMT; path=/; domain=.okcoin.com; HttpOnly', 'Vary': 'Accept-Encoding', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY', 'Set-Cookie': 'locale=en_US; Max-Age=604800; Expires=Mon, 10-Sep-2018 21:39:57 GMT; Path=/', 'X-Kong-Upstream-Latency': '1', 'X-Kong-Proxy-Latency': '0', 'Via': 'kong/0.12.3', 'Content-Encoding': 'gzip', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '454b5f3cc9b856f3-IAD')> {"code":0,"data":[{"baseCurrency":0,"brokerId":0,"callNoCancelSwitchTime":1527581481000,"collect":"0","continuousSwitchTime":{},"isMarginOpen":true,"listDisplay":0,"marginRiskPreRatio":1.3,"marginRiskRatio":1.1,"marketFrom":0,"maxMarginLeverage":3,"maxPriceDigit":2,"maxSizeDigit":4,"mergeTypes":{},"minTradeSize":0.00100000,"online":1,"productId":16,"quoteCurrency":3,"quoteIncrement":"0.01","quotePrecision":4,"sort":0,"symbol":"btc_usd","tradingMode":3},{"baseCurrency":1,"brokerId":0,"callNoCancelSwitchTime":1526290902000,"collect":"0","continuousSwitchTime":{},"isMarginOpen":false,"listDisplay":0,"marginRiskPreRatio":0,"marginRiskRatio":0,"marketFrom":3,"maxMarginLeverage":0,"maxPriceDigit":2,"maxSizeDigit":4,"mergeTypes":{},"minTradeSize":0.10000000,"online":1,"productId":17,"quoteCurrency":3,"quoteIncrement":"0.01","quotePrecision":4,"sort":1,"symbol":"ltc_usd","tradingMode":3},{"baseCurrency":2,"brokerId":0,"callNoCancelSwitchTime":1526290902000,"collect":"0","continuousSwitchTime":{},"isMarginOpen":true,"listDisplay":0,"marginRiskPreRatio":1.3,"marginRiskRatio":1.1,"marketFrom":36,"maxMarginLeverage":3,"maxPriceDigit":2,"maxSizeDigit":4,"mergeTypes":{},"minTradeSize":0.01000000,"online":1,"productId":18,"quoteCurrency":3,"quoteIncrement":"0.01","quotePrecision":4,"sort":2,"symbol":"eth_usd","tradingMode":3},{"baseCurrency":4,"brokerId":0,"callNoCancelSwitchTime":1526290902000,"collect":"0","continuousSwitchTime":{},"isMarginOpen":false,"listDisplay":0,"marginRiskPreRatio":0,"marginRiskRatio":0,"marketFrom":39,"maxMarginLeverage":0,"maxPriceDigit":2,"maxSizeDigit":4,"mergeTypes":{},"minTradeSize":0.10000000,"online":1,"productId":1,"quoteCurrency":3,"quoteIncrement":"0.01","quotePrecision":4,"sort":3,"symbol":"etc_usd","tradingMode":3},{"baseCurrency":5,"brokerId":0,"callNoCancelSwitchTime":1526290902000,"collect":"0","continuousSwitchTime":{},"isMarginOpen":false,"listDisplay":0,"marginRiskPreRatio":0,"marginRiskRatio":0,"marketFrom":106,"maxMarginLeverage":0,"maxPriceDigit":2,"maxSizeDigit":4,"mergeTypes":{},"minTradeSize":0.00100000,"online":1,"productId":15,"quoteCurrency":3,"quoteIncrement":"0.01","quotePrecision":4,"sort":4,"symbol":"bch_usd","tradingMode":3},{"baseCurrency":7,"brokerId":0,"callNoCancelSwitchTime":1534926000000,"collect":"0","continuousSwitchTime":1534926000000,"isMarginOpen":false,"listDisplay":0,"marginRiskPreRatio":0,"marginRiskRatio":0,"marketFrom":119,"maxMarginLeverage":0,"maxPriceDigit":4,"maxSizeDigit":8,"mergeTypes":{},"minTradeSize":1.00000000,"online":1,"productId":31,"quoteCurrency":3,"quoteIncrement":"0.0001","quotePrecision":4,"sort":30000,"symbol":"usdt_usd","tradingMode":3},{"baseCurrency":258,"brokerId":0,"callNoCancelSwitchTime":1534910489000,"collect":"0","continuousSwitchTime":1533889200000,"isMarginOpen":false,"listDisplay":0,"marginRiskPreRatio":0,"marginRiskRatio":0,"marketFrom":107,"maxMarginLeverage":0,"maxPriceDigit":8,"maxSizeDigit":8,"mergeTypes":{},"minTradeSize":0.01000000,"online":1,"productId":19,"quoteCurrency":3,"quoteIncrement":"0.001","quotePrecision":4,"sort":6,"symbol":"tusd_usd","tradingMode":3},{"baseCurrency":1,"brokerId":0,"callNoCancelSwitchTime":1534910509000,"collect":"0","continuousSwitchTime":1534494000000,"isMarginOpen":false,"listDisplay":0,"marginRiskPreRatio":0,"marginRiskRatio":0,"marketFrom":110,"maxMarginLeverage":0,"maxPriceDigit":8,"maxSizeDigit":8,"mergeTypes":{},"minTradeSize":0.01000000,"online":1,"productId":22,"quoteCurrency":0,"quoteIncrement":"0.00000001","quotePrecision":4,"sort":10000,"symbol":"ltc_btc","tradingMode":3},{"baseCurrency":2,"brokerId":0,"callNoCancelSwitchTime":1534910497000,"collect":"0","continuousSwitchTime":1534494000000,"isMarginOpen":false,"listDisplay":0,"marginRiskPreRatio":0,"marginRiskRatio":0,"marketFrom":108,"maxMarginLeverage":0,"maxPriceDigit":8,"maxSizeDigit":8,"mergeTypes":{},"minTradeSize":0.01000000,"online":1,"productId":20,"quoteCurrency":0,"quoteIncrement":"0.00000001","quotePrecision":4,"sort":10000,"symbol":"eth_btc","tradingMode":3},{"baseCurrency":4,"brokerId":0,"callNoCancelSwitchTime":1534906981000,"collect":"0","continuousSwitchTime":1534494000000,"isMarginOpen":false,"listDisplay":0,"marginRiskPreRatio":0,"marginRiskRatio":0,"marketFrom":109,"maxMarginLeverage":0,"maxPriceDigit":8,"maxSizeDigit":8,"mergeTypes":{},"minTradeSize":0.01000000,"online":1,"productId":21,"quoteCurrency":0,"quoteIncrement":"0.00000001","quotePrecision":4,"sort":10000,"symbol":"etc_btc","tradingMode":3},{"baseCurrency":5,"brokerId":0,"callNoCancelSwitchTime":1534910512000,"collect":"0","continuousSwitchTime":1534494000000,"isMarginOpen":false,"listDisplay":0,"marginRiskPreRatio":0,"marginRiskRatio":0,"marketFrom":111,"maxMarginLeverage":0,"maxPriceDigit":8,"maxSizeDigit":8,"mergeTypes":{},"minTradeSize":0.01000000,"online":1,"productId":23,"quoteCurrency":0,"quoteIncrement":"0.00000001","quotePrecision":4,"sort":10000,"symbol":"bch_btc","tradingMode":3},{"baseCurrency":7,"brokerId":0,"callNoCancelSwitchTime":1534926000000,"collect":"0","continuousSwitchTime":1534926000000,"isMarginOpen":false,"listDisplay":0,"marginRiskPreRatio":0,"marginRiskRatio":0,"marketFrom":116,"maxMarginLeverage":0,"maxPriceDigit":8,"maxSizeDigit":8,"mergeTypes":{},"minTradeSize":1.00000000,"online":1,"productId":28,"quoteCurrency":0,"quoteIncrement":"0.00000001","quotePrecision":4,"sort":10000,"symbol":"usdt_btc","tradingMode":3},{"baseCurrency":258,"brokerId":0,"callNoCancelSwitchTime":1534926000000,"collect":"0","continuousSwitchTime":1534926000000,"isMarginOpen":false,"listDisplay":0,"marginRiskPreRatio":0,"marginRiskRatio":0,"marketFrom":115,"maxMarginLeverage":0,"maxPriceDigit":8,"maxSizeDigit":8,"mergeTypes":{},"minTradeSize":1.00000000,"online":1,"productId":27,"quoteCurrency":0,"quoteIncrement":"0.00000001","quotePrecision":4,"sort":10000,"symbol":"tusd_btc","tradingMode":3},{"baseCurrency":1,"brokerId":0,"callNoCancelSwitchTime":1534910517000,"collect":"0","continuousSwitchTime":1534494000000,"isMarginOpen":false,"listDisplay":0,"marginRiskPreRatio":0,"marginRiskRatio":0,"marketFrom":113,"maxMarginLeverage":0,"maxPriceDigit":8,"maxSizeDigit":8,"mergeTypes":{},"minTradeSize":0.01000000,"online":1,"productId":25,"quoteCurrency":2,"quoteIncrement":"0.00000001","quotePrecision":4,"sort":20000,"symbol":"ltc_eth","tradingMode":3},{"baseCurrency":4,"brokerId":0,"callNoCancelSwitchTime":1534910515000,"collect":"0","continuousSwitchTime":1534494000000,"isMarginOpen":false,"listDisplay":0,"marginRiskPreRatio":0,"marginRiskRatio":0,"marketFrom":112,"maxMarginLeverage":0,"maxPriceDigit":8,"maxSizeDigit":8,"mergeTypes":{},"minTradeSize":0.01000000,"online":1,"productId":24,"quoteCurrency":2,"quoteIncrement":"0.00000001","quotePrecision":4,"sort":20000,"symbol":"etc_eth","tradingMode":3},{"baseCurrency":5,"brokerId":0,"callNoCancelSwitchTime":1534910520000,"collect":"0","continuousSwitchTime":1534494000000,"isMarginOpen":false,"listDisplay":0,"marginRiskPreRatio":0,"marginRiskRatio":0,"marketFrom":114,"maxMarginLeverage":0,"maxPriceDigit":8,"maxSizeDigit":8,"mergeTypes":{},"minTradeSize":0.01000000,"online":1,"productId":26,"quoteCurrency":2,"quoteIncrement":"0.00000001","quotePrecision":4,"sort":20000,"symbol":"bch_eth","tradingMode":3},{"baseCurrency":7,"brokerId":0,"callNoCancelSwitchTime":1534926000000,"collect":"0","continuousSwitchTime":1534926000000,"isMarginOpen":false,"listDisplay":0,"marginRiskPreRatio":0,"marginRiskRatio":0,"marketFrom":118,"maxMarginLeverage":0,"maxPriceDigit":8,"maxSizeDigit":8,"mergeTypes":{},"minTradeSize":1.00000000,"online":1,"productId":30,"quoteCurrency":2,"quoteIncrement":"0.00000001","quotePrecision":4,"sort":20000,"symbol":"usdt_eth","tradingMode":3},{"baseCurrency":258,"brokerId":0,"callNoCancelSwitchTime":1534926000000,"collect":"0","continuousSwitchTime":1534926000000,"isMarginOpen":false,"listDisplay":0,"marginRiskPreRatio":0,"marginRiskRatio":0,"marketFrom":117,"maxMarginLeverage":0,"maxPriceDigit":8,"maxSizeDigit":8,"mergeTypes":{},"minTradeSize":1.00000000,"online":1,"productId":29,"quoteCurrency":2,"quoteIncrement":"0.00000001","quotePrecision":4,"sort":20000,"symbol":"tusd_eth","tradingMode":3}],"detailMsg":"","msg":""}

**Comment by kroitor** [comment]
You don't want to supply the params overrides to `fetchOrder`, it does not require `type`...

Have you tried this:

```Python
flr.verbose = True
sg = asyncio.get_event_loop().run_until_complete(flr.fetchOrder(
    id,
    symbol=symbol))
```

?

**Comment by kroitor** [comment]
Also, in your instantiation code:

```
flr = getattr(ccxt, flrID)()
```

You're not using the built-in rate-limiting, are you sure that you don't hit the rate limit as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit ?

**Comment by DmitryVil** [comment]
Igor, good evening,
I did nothing, but this problem disappeared.
I think it was a bug of the OkCoin exchange.
I will watch the problem.
I think you can close the issue for now.
Sorry for disturb
Dmitry
