### ISSUE TITLE
kucoin fetch_markets() is_active parameter is missing

### ISSUE THREAD

**Issue by eatbas** [ccxt/ccxt#3794]
- OS: Windows 10
- Programming Language version: Pyhton 3.6.5
- CCXT version: 1.17.212
- Exchange: gateio 
- Method: fetch_markets()

As far as I understand from gateio api there is no inactive coin markets if there is the are delisting in the api as well therefore in ccxt library is_active parameter is missing in json. Coud you please add is_active=true on ccxt library?

**Comment by kroitor** [comment]
Sorry, but it's there already, called `active` (not `is_active`, read the Manual carefully:

- https://github.com/ccxt/ccxt/wiki/Manual#market-structure
- https://github.com/ccxt/ccxt/blob/master/js/kucoin.js#L415
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/kucoin.py#L421
- https://github.com/ccxt/ccxt/blob/master/php/kucoin.php#L415

We'd love to add it the second time, but, not sure if it's possible %)

**Comment by eatbas** [comment]
Sorry for the edit it should be gate.io and active 

output is below:

{
  "id": "mdt_eth",
   "symbol":  "MDT/ETH",
   "base":  "MDT",
   "quote":  "ETH",
   "info":  {
    "mdt_eth":  {
      "decimal_places":  8,
       "min_amount":  0.0001,
       "fee":  0.2
    }
  },
   "maker":  0.002,
   "taker":  0.002,
   "precision":  {
    "amount":  8,
     "price":  8
  },
   "limits":  {
    "amount":  {
      "min":  0.0001,
       "max":  null
    },
     "price":  {
      "min":  1e-08,
       "max":  null
    },
     "cost":  {
      "min":  0.001,
       "max":  null
    }
  }
}

**Comment by eatbas** [comment]
https://github.com/ccxt/ccxt/blob/master/python/ccxt/gateio.py
There is no active in fetch_markets() at gateio
