### ISSUE TITLE
Issue understanding limit (example)

### ISSUE THREAD

**Issue by MaxCCC** [ccxt/ccxt#3795]
I've issues to understand the `limit` option of ccxt. I've read the docs but it's still not very clear for me. I try to understand it using the example below.

I don't really understand this line:
`since = bitmex.milliseconds() - limit * 60 * 1000`
Based on what is the since calculation?

and this line:
`time.sleep(bitmex.rateLimit * 5)`
Why sleeping and how can I interpret these values?

```
# -*- coding: utf-8 -*-

import os
import sys
import time

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402

bitmex = ccxt.bitmex()

# params:
symbol = 'BTC/USD'
timeframe = '1m'
limit = 100
params = {'partial': False}  # ←--------  no reversal

while True:

    # pay attention to since with respect to limit if you're doing it in a loop
    since = bitmex.milliseconds() - limit * 60 * 1000

    candles = bitmex.fetch_ohlcv(symbol, timeframe, since, limit, params)
    num_candles = len(candles)
    print('{}: O: {} H: {} L:{} C:{}'.format(
        bitmex.iso8601(candles[num_candles - 1][0]),
        candles[num_candles - 1][1],
        candles[num_candles - 1][2],
        candles[num_candles - 1][3],
        candles[num_candles - 1][4]))
    time.sleep(bitmex.rateLimit * 5)
```

**Comment by kroitor** [comment]
> I don't really understand this line:
> `since = bitmex.milliseconds() - limit * 60 * 1000`
> Based on what is the since calculation?

```Python
now = bitmex.milliseconds()  # current timestamp in milliseconds
duration_of_one_minute = 60 * 1000  # in milliseconds
num_minutes = 100  # how many one-minute candles

# alltogether
since_one_hour_in_the_past = now - num_minutes * duration_of_one_minute
```

> and this line:
> `time.sleep(bitmex.rateLimit * 5)`
> Why sleeping and how can I interpret these values?

That sleeping is called "throttling" and it is required to avoid sending too many requests to the exchange in short time – the exchange won't like it if you're requesting too often and can ban you if you don't respect their rate limit, as documented in the Manual: https://github.com/kroitor/ccxt/wiki/Manual#rate-limit

Hope this answers your questions, let us know if not.

**Comment by MaxCCC** [comment]
@kroitor  Thanks, great answer. 
I do understand the first part, and the second I would expect: time.sleep (exchange.rateLimit / 1000) (or is this just a random customized value now because of the * 5 (and without /1000)?)

**Comment by kroitor** [comment]
> I do understand the first part, and the second I would expect: time.sleep (exchange.rateLimit / 1000) (or is this just a random customized value now because of the * 5 (and without /1000)?)

The sleeping time for `exchange.sleep` is in milliseconds as well, thus no need to divide it by a thousand. However, for certain methods some exchanges may have very specific rate-limits that may differ from their other methods, thus we just multiply the default rate limit by 5 to make it a distinct delay and to avoid too much load on the exchange. The multiplication by 5 here is indeed optional and may be exchange-specific. Basically, all of this is explained in the Manual, and I'd really recommend to read it from the very beginning to the very end – it might save you a lot of time in future ;)

**Comment by kroitor** [comment]
@lvthillo actually, you're absolutely right, there's a mistake in the example. I've added a fix for it, but then I saw that you added it as well, no worries will merge them both )) Thx for your attention! Indeed, the standard `time()` method takes it in seconds (can accept fractional seconds).
