### ISSUE TITLE
Kraken issue with fetchMinOrderSizes

### ISSUE THREAD

**Issue by standup75** [ccxt/ccxt#3797]
there is an issue with setting a variable like this and restoring it after the call in an async environment

            this.parseJsonResponse = false;
            html = await this.zendeskGet205893708WhatIsTheMinimumOrderSize ();
            this.parseJsonResponse = oldParseJsonResponse;

While I am waiting for the response to this call, I might very well make another request that does require JSON parsing, but it would not parse it. That happened to me, and this is not a very easy bug to pin down. I'd suggest making a separate fetch here using this.fetchImplementation directly to avoid this tricky issue

- OS: MacOSX
- Programming Language version: js
- CCXT version: 1.17.231
- Exchange: Kraken
- Method: fetchMinOrderSizes

**Comment by standup75** [comment]
I don't even think we should make that http call all together. Just hard code those information directly, that would speed things up. This is not a reliable way to get the min order size anyway, but it's better than nothing

**Comment by kroitor** [comment]
> I don't even think we should make that http call altogether. 

Yeah, I don't think so either, but they don't serve it from their API... And that's the only "official" source apart from their API. We're still in search for better solutions.

> Just hard code those information directly, that would speed things up. This is not a reliable way to get the min order size anyway, but it's better than nothing

Unfortunately, we had it hardcoded earlier, but it changes too often and it gets outdated quickly, so it's very hard to maintain it and keep hardcoded data up-to-date, and ultimately, you only want to trust Kraken, you don't really want to trust any info that is not served from Kraken directly. 

As for the above bug, it's a known issue with the `parseJsonResponse` flag, and I'll add a fix or a workaround for it shortly.

**Comment by standup75** [comment]
kk
I didn't know that page got updated. Weird for a dated article...

**Comment by standup75** [comment]
Thanks for the update! Looking at the code, it seems that exmo.js line 117 and coinigi.js line 96 (coinigy?) could potentially run into the same issue. I can clean it up and make a PR if you want

**Comment by jamshut76** [comment]
Hey guys,

I'm facing something similar while trying to fetch markets from Kraken on AWS.

OS: Ubuntu (on AWS)
Programming Language version: python 2.7
CCXT version: ccxt-1.17.556
Exchange: Kraken
Method: zendeskGet205893708WhatIsTheMinimumOrderSize()

Code:
```
            self.client = ccxt.kraken()
            test = self.client.load_markets()
```

Fails with:

> Traceback (most recent call last):
>   File "/home/ubuntu/quant/quant_python_data_collector.py", line 189, in <module>
>     platform = platform_module.platform(start_date, finish_date, frequency, event_horizon)
>   File "/home/ubuntu/quant/quant_python_platform_kraken.py", line 20, in __init__
>     CryptoGenericPlatform.__init__(self, start_dt, finish_dt, frequency, event_horizon)
>   File "/home/ubuntu/quant/quant_python_platform_crypto_generic.py", line 357, in __init__
>     self.priceDataProviders.append(ccxtRealtimePriceDataProvider(self, self.frequency, self.api_key, self.secret_key, self.start_dt, self.finish_dt))
>   File "/home/ubuntu/quant/quant_python_platform_crypto_generic.py", line 179, in __init__
>     test = self.client.load_markets() #fetch_tickers()
>   File "/usr/local/lib/python2.7/dist-packages/ccxt/base/exchange.py", line 1021, in load_markets
>     markets = self.fetch_markets(params)
>   File "/usr/local/lib/python2.7/dist-packages/ccxt/kraken.py", line 266, in fetch_markets
>     limits = self.fetch_min_order_amounts()
>   File "/usr/local/lib/python2.7/dist-packages/ccxt/kraken.py", line 244, in fetch_min_order_amounts
>     html = self.zendeskGet205893708WhatIsTheMinimumOrderSize()
>   File "/usr/local/lib/python2.7/dist-packages/ccxt/kraken.py", line 1119, in request
>     response = self.fetch2(path, api, method, params, headers, body)
>   File "/usr/local/lib/python2.7/dist-packages/ccxt/base/exchange.py", line 361, in fetch2
>     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
>   File "/usr/local/lib/python2.7/dist-packages/ccxt/base/exchange.py", line 457, in fetch
>     self.raise_error(ExchangeError, url, method, e)
>   File "/usr/local/lib/python2.7/dist-packages/ccxt/base/exchange.py", line 346, in raise_error
>     raise exception_type(output)
> ccxt.base.errors.ExchangeError: kraken https://support.kraken.com/hc/en-us/articles//205893708-What-is-the-minimum-order-size- GET HTTPSConnectionPool(host='support.kraken.com', port=443): Max retries exceeded with url: /hc/en-us/articles//205893708-What-is-the-minimum-order-size- (Caused by SSLError(CertificateError("hostname 'support.kraken.com' doesn't match either of 'ssl385002.cloudflaressl.com', '*.zdorigin.com', 'zdorigin.com'",),))

Same code runs fine on my local machine. Apparently this is not a connectivity issue because 
`curl https://support.kraken.com/hc/en-us/articles//205893708-What-is-the-minimum-order-size- `
works just fine

**Comment by kroitor** [comment]
@jamshut76 please, read this thread: https://github.com/ccxt/ccxt/issues/2522. Let us know if that doesn't help.

**Comment by jamshut76** [comment]
> @jamshut76 please, read this thread: #2522. Let us know if that doesn't help.

@kroitor thanks! Yes, may be this is what I'm facing cause I have openssl v1.0.2g locally and  1.0.1f on the server. Can't really check if upgrading openssl solves the issue, since it requires rebuilding the library (which is yet beyond my comprehension - I'm pretty novice to Ubuntu and don't want to ruin everything). 

However, #2526 is related to binance exchange. This is suspicious because binance (and gateio) run absolutely fine both locally and remotely in my case.
