### ISSUE TITLE
socket not open error when invoke websocketSubscribe

### ISSUE THREAD

**Issue by imhazige** [ccxt/ccxt#3798]
@lfern 

at branch https://github.com/lfern/ccxt/tree/feature/websockets-multiple

this is like to happen in a slow network when connect to okex.

it is strange, that the socket is still not open when invoke websocketSubscribe.

Error Stack:

`
Error: not opened
I20180905-18:02:28.011(8)?     at WebSocket.send (node_modules/ws/lib/WebSocket.js:360:18)
I20180905-18:02:28.011(8)?     at WebsocketConnection.send (ccxt-websocket/js/base/websocket/websocket_connection.js:77:28)
I20180905-18:02:28.012(8)?     at WebsocketConnection.sendJson (cxt-websocket/js/base/websocket/websocket_base_connection.js:37:14)
I20180905-18:02:28.012(8)?     at okex.websocketSendJson (ccxt-websocket/js/base/Exchange.js:1866:31)
I20180905-18:02:28.012(8)?     at okex._websocketSubscribe (ccxt-websocket/js/okex.js:295:14)
I20180905-18:02:28.012(8)?     at Promise.asyncApply (ccxt-websocket/js/base/Exchange.js:2092:14)
`

this is not going to be easy reproduced.

**Comment by kroitor** [comment]
@imhazige sorry, but I think you should rather reopen this issue here in the relevant branch here: https://github.com/lfern/ccxt or repost it in the relevant existing issue here: #56
