### ISSUE TITLE
decimal_to_precision critical error

### ISSUE THREAD

**Issue by beniloew** [ccxt/ccxt#3800]
- OS: ubuntu
- Programming Language version:
- CCXT version: latest
- Exchange:
- Method: decimal_to_precision

issue:
decimal_to_precision(0.0000001, TRUNCATE, 8, DECIMAL_PLACES) will give 9.999999
So, if you place a buy order at kucoin for example, and you want a price of 0.0000001, the price that will be sent is actually 9.99999, which is a serious bug IMO.
This happens since the decimal.Decimal(n) used in the decimal_to_precision function will give:
```
>>> decimal.Decimal(0.0000001)
Decimal('9.99999999999999954748111825886258685613938723690807819366455078125E-8')
```
Now, looking at it as a string and cutting the most of it without taking into account the 'E' notation, will give you this undesired behaviour

**Comment by beniloew** [comment]
could be solved dirty like this:
```
expSplit = string.split('E-')
if len(expSplit == 2):
  exp = int(explSplit[1])
  newString =  '0.' + ''.join(((8 - 1) * '0' + string).split('.'))
```

**Comment by beniloew** [comment]
Hmmm.
Not completely solving, will return 0.00000009

**Comment by beniloew** [comment]
Another better solution, but need to make sure it works...
Set the prec of the decimal context to our precision
`
decimal.getcontext().prec = precision #(8 in our case)
a = decimal.Decimal(0.000001).normalize().__str__() == '0.000001'
`

With smaller numbers it still works without loosing precision, however, it'll use scientific notation

**Comment by beniloew** [comment]
In order to get rid of the scientific notation, we can just use the first bit of code

**Comment by kroitor** [comment]
@beniloew 

Thx for a comprehensive report! Will do out best to fix it asap.

See these related issues and files:

- https://github.com/ccxt/ccxt/blob/master/js/test/base/functions/test.number.js
- https://github.com/ccxt/ccxt/blob/master/python/test/test_decimal_to_precision.py (the test is ranspiled from js)
- https://github.com/ccxt/ccxt/blob/master/php/test/decimal_to_precision.php (the test is ranspiled from js)
- https://github.com/ccxt/ccxt/pull/3663/commits/aba0c944511afb4e44a26e9a8d16edc89dd858c1
- https://github.com/ccxt/ccxt/issues/3799
- https://github.com/ccxt/ccxt/pull/1635 (js)
- https://github.com/ccxt/ccxt/pull/2171 (php)
- https://github.com/ccxt/ccxt/pull/2397 (py)
- https://github.com/ccxt/ccxt/pull/2317
- https://github.com/ccxt/ccxt/issues/1034
- https://github.com/ccxt/ccxt/issues?q=precision
- https://github.com/ccxt/ccxt/issues?q=precision+is%3Aclosed
- https://github.com/ccxt/ccxt/pulls?q=precision
- https://github.com/ccxt/ccxt/pulls?q=precision+is%3Aclosed

Your help is very much appreciated!

**Comment by beniloew** [comment]
Will try to push a fix shortly

**Comment by beniloew** [comment]
https://github.com/ccxt/ccxt/pull/3801

**Comment by frosty00** [comment]
Wow I was not expecting that error...

Great find, I'll push out a fix later today (im on american time now)

**Comment by kroitor** [comment]
@frosty00 no worries, @beniloew has already submitted it, so i'm going to merge it together with your branch (and with tests for those cases as well). But thanks anyways, as always )

**Comment by kroitor** [comment]
@frosty00 but still, if you have a better/shorter solution or a proposal, we'd be interested in everything ;)

**Comment by frosty00** [comment]
Ok, could you hold off on merging the fix because I think I can do it cleaner, just for future maintenance of this library.

Basically I had assumed that str(Decimal) did not return any E-7 notation which was wrong.

Will post in a bit (;

**Comment by frosty00** [comment]
Well here was the bug:

https://stackoverflow.com/a/27053722/4802441

Thank you to @beniloew for finding this (:
@beniloew
