### ISSUE TITLE
Invalid quantity

### ISSUE THREAD

**Issue by Elmit2015** [ccxt/ccxt#3804]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Ubuntu 18.04
- Programming Language version: php7.2
- CCXT version: 
- Exchange: binance
- Method: buy/sell

with 
`$exchange->verbose = true; `
I get 

> [5] => {"code":-1013,"msg":"Invalid quantity."}

From my ticker (BNB/BTC) I learned:
precision_base3: 8
precision_quote3: 8
precision_amount3: 2
precision_price3: 7
limits_amount_min3: 0.01
limits_amount_max3: 90000000
limits_price_min3: 0.0001487
limits_price_max3: 0.014864
limits_cost_min3: 0.001
limits_cost_max3: 99999999
Original amount: 1.8885249196141 - original price: 0.0014928
=> precision fixed: amount: 1.88 price: 0.0014928 (quote1_trade_3 * price = ) 0.002806464 BNB
=> amount, price and cost are in limits

I try to execute 
`$buy_order3 = $exchange->create_limit_buy_order($symbol, $base1_trade_3, $price, $params);`
( according to: $buy_order3 = $exchange->create_limit_buy_order (BNB/BTC, 1.88, 0.0014928, Array))

The respond is very large, but the important part I guess are only:
 

> {
"symbol":"BNBBTC",
"status":"TRADING",
"baseAsset":"BNB",
"baseAssetPrecision":8,
"quoteAsset":"BTC",
"quotePrecision":8,
"orderTypes":["LIMIT","LIMIT_MAKER","MARKET","STOP_LOSS_LIMIT","TAKE_PROFIT_LIMIT"],
"icebergAllowed":true,
"filters":[
	{"filterType":"PRICE_FILTER","minPrice":"0.00014870","maxPrice":"0.01486400","tickSize":"0.00000010"},
	{"filterType":"LOT_SIZE","minQty":"0.01000000","maxQty":"90000000.00000000","stepSize":"0.01000000"},
	{"filterType":"MIN_NOTIONAL","minNotional":"0.00100000"},{"filterType":"ICEBERG_PARTS","limit":10},

...
[5] => {"code":-1013,"msg":"Invalid quantity."} 

I cannot see why its an "invalid quantity"

**Comment by kroitor** [comment]
Can you show your verbose request/response (without your keys, but with the body)?

```
$exchange->verbose = true;
$buy_order3 = $exchange->create_limit_buy_order($symbol, $base1_trade_3, $price, $params);
```

Then copypaste the request and response as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue. If the body of your request has proper values (it should), then we would forward this to Binance tech support, I think.

**Comment by Elmit2015** [comment]
Sorry, I found the error! I accidentally used a wrong variable name for that trade. Now it works.
