### ISSUE TITLE
Wrong type of exception

### ISSUE THREAD

**Issue by Stock84-dev** [ccxt/ccxt#3807]
- OS: Windows 7
- Programming Language version: Python 3.7
- CCXT version: 1.17.236
- Exchange: binance, hitbtc/hitbtc2
- Method: fetch_withdrawals, fetch_deposits

I know that ccxt.binance doesn't have API for those methods, but then it should thorw NotSupported exception, instead it throws AttributeError. Exception might happen on other exchanges, haven't tested.

If someone is willing to implement, you can find API here: https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#deposit-history-user_data

**Comment by kroitor** [comment]
The fix is already on the way: https://github.com/ccxt/ccxt/pull/2526
