### ISSUE TITLE
 Calls from many users and different APIs from node server

### ISSUE THREAD

**Issue by digither** [ccxt/ccxt#3808]
Hi friends . First of all, thanks for the wonderful project. 
I'm looking at the possibilities of the ccxt library. I started with a project in node and angular 6 to read the balance and make some graphs. I wanted to upload it to a server in Digital Ocean for everyone.

Before starting the production, I wanted to ask them. If a server calls binance to read the balance of many users from the same ip, but with different APIs, any problem with 'enableRateLimit': true,? 

Maybe not allow 100 users reading the balance in the same minute. The scrip makes calls to fetchBalance() and fetchTicker() with Promise.all for each currency in the balance.

Sistem:
- OS: Debian
- Programming Language version: Node v8.11.3 - angular 6.0.9
- CCXT version: 1.17.180
- Exchange: Binance
- Method: getTicker

Apologies but my English is not very good

**Comment by digither** [comment]
Thanks for the reply. It gives me many possibilities. I usually mix async / await and promise.all. something like that:
`let sleep = (ms) => new Promise (resolve => setTimeout (resolve, ms))
const favoritas = {
    'bittrex': ['BTC/USD', 'SHIFT/BTC', 'LSK/BTC'],
    'binance': ['BTC/USDT', 'LSK/BTC','CLOAK/BTC', 'ETC/BTC'] 
}
const exchangesId = Object.keys(favoritas)
let getTicker = async (exchange) => {
    try {   
        const tickersExchange = await Promise.all (favoritas[exchange.id].map(async(par)=>{
            let _ticker = await exchange.fetchTicker (par)
            grabarTicker(_ticker, exchange.id, par)
          }   
        )) 
        return tickersExchange

      } catch (error) {
        console.log(error)
        }  
}
// save function for database
function grabarTicker(_ticker, _exchangeId, _symbol) { 
}
;(async () => {
    var exchages=[];
    exchangesId.forEach ( id => { 
        exchages.push( new ccxt[id] ({ enableRateLimit: true }) )   
    });   
    while (true) {         
                await sleep (5000)
                try {   
                      const result = await Promise.all (exchages.map(getTicker))  
                      console.log(result)               
                    } catch (error) {
                      console.error(error)
                      }      
    }
}) ()`

**Comment by ttodua** [comment]
Basically, it depends on specific exchange. on private endpoints, some exchanges have rate-limits binded to api-keys, while others have rate-limits based against IP address. So , you have to check out the specific exchange's api docs for full information.

On the other hand, CCXT's internal rate-limiter tries to solve the problem on behalf of user, so even if you try to fetch balance or whatever for 50 users at the same time, it will throttle calls and put them in queue to meet the rate-limit requirements (if that exchange has been coded well enough in ccxt with regard to rate-limit logic, and CCXT is always a "work-in-progress").
If you cant get assured with built-in rate-limiter, then I can say that about balance, you will be ok if you make requests like "one call in every 200 ms" for same exchange.
About tickers (as almost all exchanges set rate-limites against IP address for public endpoints)  i would suggest to use `fetchTicker**s**`, that you just make one `fetchTickers` to get all tickers at once, and then grab the each pair data for specific user from that response. 

For now, I'll set this issue as closed.
