### ISSUE TITLE
Qryptos is now Liquid.com

### ISSUE THREAD

**Issue by procloud** [ccxt/ccxt#3809]
please update url to

api.liquid.com

https://developers.quoine.com/v2

**Comment by arielorvits** [comment]
liquid - quoinex+qryptos, 
so should remove quoinex, 
and change qryptos to liquid.

**Comment by y-clps** [comment]
Liquid adds new currency pairs (XRP/JPY, XRP/BTC, etc).
So please add these pairs to ccxt.

**Comment by ndubel** [comment]
any updates?
