### ISSUE TITLE
Unable to call privatePostHistory()

### ISSUE THREAD

**Issue by anik-jagtap** [ccxt/ccxt#3811]
- OS: Windows 7
- Programming Language version: Javascript
- CCXT version: 1.17.240
- Exchange: Bitfinex
- Method: privatePostHistory()

Hi,
I am working on some project for which i am calling privatePostHistory() using CCXT. I am able to call privatePostMytrades() which is used in fetchMyTrades() method. Similar way i want to call privatePostHistory(). Can you please help me in this?

**Comment by kroitor** [comment]
> Similar way i want to call privatePostHistory(). Can you please help me in this?

Can you show a snippet of your code that isn't working, or what is the problem with it?

**Comment by anik-jagtap** [comment]
Hi, Sorry for the late response.
And thank you for your help; got success in calling method. But now i am facing another issue.
I am trying to make this request,
`await this.privatePostHistoryMovements(this.extend ({
            'currency': 'litecoin',
            'since': 0,
            'until': this.seconds ()
        }, params));`
I am having withdraw and deposit history in Bitfinex, but in turn it is returning me empty array response with OK header.

**Comment by kroitor** [comment]
@anik-jagtap if you update your ccxt to most recent version, then you can use this unified API to fetch your funding history with Bitfinex: 

- https://github.com/ccxt/ccxt/wiki/Manual#transactions
- https://github.com/ccxt/ccxt/wiki/Manual#all-transactions

```
'use strict';

const ccxt = require ('ccxt')

const exchange = new ccxt.bitfinex ({
    enableRateLimit: true,
    apiKey: 'YOUR_API_KEY',
    secret: 'YOUR_SECRET',
})

;(async () => {
    await exchange.loadMarkets ();

    // comment or uncomment the following line to see more or less info
    // compare what it does with what you do
    exchange.verbose = true;

    const transactions = await exchange.fetchTransactions ('LTC' /* , add pagination params later... */ );
    console.log (transactions)
    console.log ('Fetched ', transactions.length, 'transactions')

}) ()
```

Then read this: https://github.com/ccxt/ccxt/wiki/Manual#pagination and add proper pagination params if necessary. Let us know if it does not help. Closing this for now if you don't mind. Feel free to reopen it if needed.

**Comment by anik-jagtap** [comment]
Hi @kroitor ,
Sorry to bother again.
I am working on some exchanges and i would like to contribute some code. Please let me know if i can and how.

**Comment by kroitor** [comment]
> Please let me know if i can and how.

Sure, you can! The only thing you have to do is to read the CONTRIBUTING doc carefully: 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#what-you-need-to-know
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

Let me know if you have questions, we appreciate all help, your PRs are welcome! )
