### ISSUE TITLE
HitBTC: Negative precision is not yet supported

### ISSUE THREAD

**Issue by giv13** [ccxt/ccxt#3816]
- OS: Windows 8
- Programming Language version: php 7.1
- CCXT version: 1.17.252
- Exchange: HitBTC
- Methods: create_order and edit_order

This error began to appear when I trying to create an order. I think this is due to the `amount_to_precision` function, and also to the fact that HitBTC returns a negative value for `$market['any']['precision']['amount']`.

In general, several exchanges (HitBTC, BitZ, EXX, ...) stopped working correctly after the update from 1.17.229 to the latest version, so I rolled back to version 1.17.229. Is it because of the implementation of the decimalToPrecision?

**Comment by kroitor** [comment]
>  Is it because of the implementation of the decimalToPrecision?

In short, yes, most likely... The lack of support for negative precision is a known issue. See this PR for more info on the subject: https://github.com/ccxt/ccxt/pull/3741. Basically, we need to port #3741 to JS and PHP. Your help with adding the missing part in PHP is very much appreciated. The original PHP-implementation was authored by @kornrunner in PHP in https://github.com/ccxt/ccxt/pull/2171.

**Comment by kroitor** [comment]
I suggest to move this discussion to #3741 if you don't mind. Let me know there if you have more questions on this issue. We hope to add a workaround for it asap.
