### ISSUE TITLE
FetchTrades at HitBTC with node.js (CCXT version Version 1.10.1 2017-11-06) -- A beginners question

### ISSUE THREAD

**Issue by Lorias** [ccxt/ccxt#3823]
A question about how to use ccxt with node.js and the HitBTC exchange.

In short:
I just want to use the fetchTrades()-Method in node.js for the HitBTC-exchange.
As in the CCXT-Documentation (Release 1.17.226) explained the Method should
return the trades starting from a specific date and fetching a previously set amount of data.

But somehow, I'm experiencing difficulties with the timestamp!
When I use the variable "since" or place a timestamp manualy, then don't receive any data at all.
I just get an empty array.

The output in the console does look like this:
request was made: //infoPackage?currency=XRP/USDT&amountOfData=1

> { currency: 'XRP/USDT', amountOfData: '1' }
> since = 1536529416389
> tickerData = []

As soon as I put some random numbers in the "since" parameter, I receive 1000 datasets
of the current coin, starting with "2017-12-06T16:50:46.291Z" and ending with "2017-12-08T00:39:06.836Z".

I don't know what to do, or how to fix this issue.
Any hint or code is highly appreciated.

Currently my code does look like this:

`//-----BEGIN----`
`const http = require("http");`
`const url = require("url");`

`var ServerPort = 3710;`

`"use strict";`
`const ccxt = require ("ccxt");`
`let hitbtc = new ccxt.hitbtc ();`

`var Request = require("request");`

`var jsn_Content;
var myContent;
var currency;`
`var std_404 = "I do not know what to do!";`

`function StartServer(){`
`    console.log("Server did start!");`
	
`    var server = http.createServer(async function(req, res){`
`        thisURL = req.url;`
 `       console.log("request was made: " + thisURL);`

`        if(thisURL.indexOf("infoPackage")>0){` 
`                var query = url.parse(thisURL,true).query;`
`                console.log(query);`
`                currency = query.currency;`
`                var amountOfData = query.anzahl;`

`                 //https://api.hitbtc.com//api/1/public/XRPUSDT/trades/recent?max_results=100&` 
` 		  jsn_Content = await getTheTrades(currency, amountOfData)` 

`                 myContent =  jsn_Content;` 
`                 thisType = "application/json";` 
`             }` 
        
`         else{` 
`             thisType = "text/html";` 
`             myContent = std_404;` 
 `        }` 

`         res.setHeader('X-Frame-Options', 'ALLOWALL');` 
`         res.setHeader('Access-Control-Allow-Origin', '*');` 
`         res.setHeader('Access-Control-Allow-Methods', 'POST, GET');` 
`         res.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Authorization');` 

`         res.writeHead(200, {'Content-Type': thisType});` 
`         res.end(myContent);` 

`     });` 
`     server.listen(ServerPort, '127.0.0.1');` 
` }` 

` StartServer();` 

`async function getTheTrades(chosenCurrency, amountOfData){` 
`     try {` 
`         //let since = hitbtc.milliseconds () - 8640000 // -1 day from now` 
 `        let since = hitbtc.parse8601 ("2018-09-09T21:43:36.389Z")` 
` 	console.log("since = "+since);` 
		
`         //trades = await exchange.fetchTrades (symbol, since, limit)` 
		
`         //chosenCurrency = "XRP/USDT";` 
` 		tickerData = await hitbtc.fetchTrades (chosenCurrency, since, amountOfData);` 
` //Timestamp 1518983548636` 
`         tickerData = JSON.stringify(tickerData);` 
`     console.log("tickerData = " + tickerData);` 
`         return tickerData;` 
 `      }` 
 `      catch(err) {` 
 `        console.log("----------getTheTrades() - ERROR----------" );`   
 `        console.log(err);` 
 `      }` 
`     }`

`process.on("uncaughtException", (err) => {`
`    console.log("Error: ${err.message}")`
`  })`

` //------END-----` 

________________________________________________________________________
- OS: Win10
- Programming Language version:  Node 8.11.1
- CCXT version: 1.10.1 2017-11-06
- Exchange: hitbtc
- Method: fetchTrades

**Comment by kroitor** [comment]
First of, you will have to update your CCXT version, as yours is almost a year-old, it gets outdated quickly, and a lot has changed with HitBTC since then. For example, they no have moved to version 2 (hitbtc2). So, if you update to most recent version 1.17.261, then it should work fine from there.

```
mbp:ccxt igorkroitor$ node examples/js/cli hitbtc fetchTrades XRP/USDT 2018-09-09T21:43:36.389Z 5
hitbtc.fetchTrades (XRP/USDT, 1536529416389, 5)
       id |     timestamp |                 datetime |   symbol | type | side |  price | amount
-----------------------------------------------------------------------------------------------
360469084 | 1536529420541 | 2018-09-09T21:43:40.541Z | XRP/USDT |      |      | 0.2828 |   3490
360469212 | 1536529443446 | 2018-09-09T21:44:03.446Z | XRP/USDT |      |      | 0.2828 |     80
360469345 | 1536529463647 | 2018-09-09T21:44:23.647Z | XRP/USDT |      |      | 0.2828 |   1541
360469448 | 1536529482632 | 2018-09-09T21:44:42.632Z | XRP/USDT |      |      | 0.2828 |      2
360469528 | 1536529494634 | 2018-09-09T21:44:54.634Z | XRP/USDT |      |      | 0.2828 |    188
5 objects
```
```
mbp:ccxt igorkroitor$ node examples/js/cli hitbtc2 fetchTrades XRP/USDT 2018-09-09T21:43:36.389Z 5
hitbtc2.fetchTrades (XRP/USDT, 1536529416389, 5)
       id | order |     timestamp |                 datetime |   symbol | type | side |  price | amount |               cost | fee
----------------------------------------------------------------------------------------------------------------------------------
360469084 |       | 1536529420541 | 2018-09-09T21:43:40.541Z | XRP/USDT |      |  buy | 0.2828 |   3490 |            986.972 |
360469212 |       | 1536529443446 | 2018-09-09T21:44:03.446Z | XRP/USDT |      |  buy | 0.2828 |     80 |             22.624 |
360469345 |       | 1536529463647 | 2018-09-09T21:44:23.647Z | XRP/USDT |      |  buy | 0.2828 |   1541 |           435.7948 |
360469448 |       | 1536529482632 | 2018-09-09T21:44:42.632Z | XRP/USDT |      | sell | 0.2828 |      2 |             0.5656 |
360469528 |       | 1536529494634 | 2018-09-09T21:44:54.634Z | XRP/USDT |      | sell | 0.2828 |    188 | 53.166399999999996 |
5 objects
mbp:ccxt igorkroitor$
```

**Comment by kroitor** [comment]
Let me know if that does not help, feel free to reopen this issue if needed or just ask further questions, if any.

**Comment by kroitor** [comment]
@Lorias if you're willing to support what we do and want to help us continue this and develop it further, we'll be happy for all contributions, your donation is welcome:

XRP Deposit address: rLHzPsX6oXkzU2qL12kHCH8G8cnZv1rBJh
XRP Destination tag: 1062046264

Thank you!

**Comment by kroitor** [comment]
> Please let me know, if the 100.491 XRP did arrive as they should be!!!!

Yes it did, thx so much! Appreciate your contribution! Let us know if you have more questions on the lib ;)

**Comment by Lorias** [comment]
Thx for your response.
Very good to know, that the XRP did arrive safely!
Yes, I'll ask for your support again I think.
Currently I'm running into other issues witch selling in hitbtc.
But first I'll try to fix these issues myself. When I should get stuck again, 
I'll most likely have no chance as asking for your service again.
Thx and read about you soon!

**Comment by kroitor** [comment]
@Lorias I'd really recommend to read the entire Manual once again from the beginning to the very end, though this may seem like a very long read, it will definitely save a ton of debugging time, trust me. Moreover it explains some of the concepts that you definitely want to get comfortable with for your algorithmic trading in future. Hope it helps, let me know if not. ;)
