### ISSUE TITLE
Lack margin_infos api of bitfinex

### ISSUE THREAD

**Issue by Jay54520** [ccxt/ccxt#3824]
- OS: All
- Programming Language version: Python
- CCXT version: 1.17.260
- Exchange: Bitfinex
- Method: [margin_infos](https://docs.bitfinex.com/v1/reference#rest-auth-margin-information)

Lack [margin_infos](https://docs.bitfinex.com/v1/reference#rest-auth-margin-information) api of bitfinex.

We can get `margin_balance`(The USD value of all your trading assets (based on last prices)) from this API.

Suppose we have 10 symbols in bitfinex margin wallet, if without this API, we must request 10 order books of the 10 symbols to get the USD value.

The api version is v1 according to the URL: `https://api.bitfinex.com/v1/margin_infos`, but I haven't found the API in `bitfinex.describe.has`:

```
            'has': {
                'CORS': False,
                'createDepositAddress': True,
                'deposit': True,
                'fetchClosedOrders': True,
                'fetchDepositAddress': True,
                'fetchTradingFees': True,
                'fetchFundingFees': True,
                'fetchMyTrades': True,
                'fetchOHLCV': True,
                'fetchOpenOrders': True,
                'fetchOrder': True,
                'fetchTickers': True,
                'fetchTransactions': True,
                'fetchDeposits': False,
                'fetchWithdrawals': False,
                'withdraw': True,
            },
```

But exist in `ccxt/async_support/bitfinex.py:110`

```
                    'post': [
                        'account_fees',
                        '...'
                        'margin_infos',
```

**Comment by kroitor** [comment]
@Jay54520 please, read this:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://github.com/ccxt/ccxt/blob/master/js/bitfinex.js#L97
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/bitfinex.py#L110
- https://github.com/ccxt/ccxt/blob/master/php/bitfinex.php#L97

```Python
import ccxt
from pprint import pprint

bitfinex = ccxt.bitfinex({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

pprint(bitfinex.private_post_margin_infos())
```

Let us know if that does not answer your question.

**Comment by Jay54520** [comment]
It solved my problem.

But `private_post_margin_infos` only exist in bitfinex v1 but not bitfinex v2: `{AttributeError}'bitfinex2' object has no attribute 'private_post_margin_infos'`. It confuse me because bitfinex2 inherit bitfinex: `class bitfinex2 (bitfinex):`.
