### ISSUE TITLE
Get response status_code in exception

### ISSUE THREAD

**Issue by sgtStrom** [ccxt/ccxt#3825]
Hi there! I have a question about Python library.
When I get an exception, how can I get HTTP status code from underlying requests library? I need to filter out only 4xx or 5xx codes. Or only a particular code sometimes. Is there a way to do it without inheriting ccxt.base.Exchange or its subclasses methods?

**Comment by kroitor** [comment]
Hi!

I've added the following overrideable `httpExceptions` property with a mapping of http status codes to exception classes, this should resolve your issue:

- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L159
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L141
- https://github.com/ccxt/ccxt/blob/master/php/Exchange.php#L761

Let us know if that does not help. Thx!

**Comment by sgtStrom** [comment]
Great work, comrade!
I will test this tomorrow and write back to you.

**Comment by sgtStrom** [comment]
Yes, `httpExceptions` property fully suits me. Thanks again!
