### ISSUE TITLE
Kraken error message

### ISSUE THREAD

**Issue by mariodantas** [ccxt/ccxt#3826]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Ubuntu 18
- Programming Language version: PHPv7
- CCXT version: last
- Exchange: Kraken
- Method: fetchBalance

Hello fellows, receiving malformed response from Kraken since a few days

Notice: Undefined variable: body in /home/vhosts/trader/vendor/ccxt/ccxt/php/Exchange.php on line 634

Notice: Undefined variable: body in /home/vhosts/trader/vendor/ccxt/ccxt/php/Exchange.php on line 634

Warning: Illegal string offset 'result' in /home/vhosts/trader/vendor/ccxt/ccxt/php/kraken.php on line 241

Notice: Undefined variable: body in /home/vhosts/trader/vendor/ccxt/ccxt/php/Exchange.php on line 634

Warning: Illegal string offset 'result' in /home/vhosts/trader/vendor/ccxt/ccxt/php/kraken.php on line 331

Notice: Undefined variable: body in /home/vhosts/trader/vendor/ccxt/ccxt/php/Exchange.php on line 634
kraken fetchBalance failed due to a malformed $response "{\"error\":[],\"result\":{\"ZEUR\":\"0.4923\",\"XXBT\":\"0.0000037200\",\"BCH\":\"0.0000000000\"}}"

**Comment by kroitor** [comment]
@mariodantas hi! Thx so much for your attention and for reporting this, I've uploaded a fix for it, it should arrive in version 1.17.270 in 5-10 minutes. Let me know if you still have difficulties with it after upgrading to 1.17.270.

**Comment by mariodantas** [comment]
array(3) { ["EUR"]=> float(0.4923) ["BTC"]=> float(3.72E-6) ["BCH"]=> float(0) }

PERFECT Fellow, many thanks
