### ISSUE TITLE
New Exchange: https://www.excraft.com

### ISSUE THREAD

**Issue by caojq9902** [ccxt/ccxt#3833]
Exchange: ExCraft
URL: https://www.excraft.com

it's the only local crypto exchange currently operating in the HongKong. including it in your great api would help a lot of developers in the country.

much appreciated.

**Comment by kroitor** [comment]
Related PR: https://github.com/ccxt/ccxt/pull/3963

**Comment by An-Net** [comment]
The exchange has been inactive since 2019.
