### ISSUE TITLE
New Exchange: Bitibu

### ISSUE THREAD

**Issue by bitibu** [ccxt/ccxt#3834]
Hello,

**Bitibu Exchange** establish on january 2018 in **Cyprus**. Currently, Bitibu supports 18 currencies with BTC, ETH and USD pairs. We will really appreciate if you add Bitibu Exchange on CCXT library.

- Homepage: https://bitibu.com
- API Document: https://bitibu.com/documents/api_v2

We send some BTB coin to your ETH address.

Thanks for your greate work and ccxt library.

![bitibuexchange](https://user-images.githubusercontent.com/41238823/45436641-f0ce6d80-b6bb-11e8-9c49-dc6ac9985ea0.jpg)

**Comment by greo2017** [comment]
Bitibu uses same API with ACX and Tidebit.

**Comment by muradoviz** [comment]
Hello @kroitor,

We will use ccxt library for bot. If you accept, we can add Bitibu on ccxt?

**Comment by kroitor** [comment]
@muradoviz sorry, I probably didn't get your initial intent correctly, to clarify: if you're willing to submit the code – we'd be happy to accept it if it does conform to our docs, and if you're asking for us to implement and add Bitibu, then we'll prioritize it and will add it if nobody else does that before we do.

**Comment by kroitor** [comment]
@greo2017 

> Bitibu uses same API with ACX and Tidebit.

I'll see if I can add it shortly.

**Comment by kroitor** [comment]
We have added it in 1.17.280, let us know if you have difficulties with it. Thx!

**Comment by muradoviz** [comment]
Thank you! @kroitor

**Comment by kroitor** [comment]
@muradoviz thx for using this library!
@bitibu we'll be happy for all contributions, your donations are welcome: https://github.com/ccxt/ccxt#support-developer-team

**Comment by muradoviz** [comment]
@kroitor payment for what? And how much you want?

**Comment by kroitor** [comment]
@muradoviz we don't really want anything, will add it soon after we test it, free, in the meantime you can use the versions published above.

**Comment by muradoviz** [comment]
@kroitor You already added it. It is not hard for you. I will be happy if you add. But we will never ask you to add it again. Thanks for your time.

**Comment by kroitor** [comment]
- https://bitcointalk.org/index.php?topic=5095994.0
- https://bitcointalk.org/index.php?topic=4612714.msg45062779#msg45062779

The exchange website seems to be broken at this point, twitter and reddit closed, we're delisting bitibu, sorry.
