### ISSUE TITLE
deployment error in a google / firebase cloud function

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#3840]
I'm unable to use ccxt in a cloud function.  When I start locally the deployment dies if I add the line `const cctx = require('cctx');`.  The same does not happen for other dependencies such as `const uuid = require('uuid');`

I've added (both) packages to my _package.json_ file, run `npm install` and I can see them both in my _node_modules_ directory.  I've tried cleaning the cache.

 ```
 "dependencies": {
    "ccxt": "^1.17.283",
    "firebase-admin": "^6.0.0",
    "firebase-functions": "^2.0.5",
    "uuid": "^3.3.2"
  },
```

Here's the error:

```
$ firebase serve  --only functions

=== Serving from '/Users/crypro/projects/CrypPro-marketdata/firebase'...

i  functions: Preparing to emulate functions.
⚠  functions: Failed to load functions source code. Ensure that you have the latest SDK by running npm i --save firebase-functions inside the functions directory.
⚠  functions: Error from emulator. Error parsing triggers: Cannot find module 'cctx'

Try running "npm install" in your functions directory before deploying.
```

I'm using:

```
$ node --version
v6.11.5
$ npm --version
6.4.1
$ firebase --version
4.2.1
```

I'm guessing there's something different between the _uuid_ npm package and the _ccxt_ one, but I've no idea what.

**Comment by kroitor** [comment]
```JavaScript
const cctx = require('cctx');
// ↑↑↑↑ cctX → ccXt ↑↑↑↑ 
```

**Comment by npomfret** [comment]
haha - I'm an idiot.  Been looking at this for an hour.

**Comment by npomfret** [comment]
... as s side question, i get another error from firebase which looks like a javascript versioning issue.  Is the following syntax for a very modern version of javascript:

```
firebase/functions/node_modules/ccxt/js/base/Exchange.js:438
                    let partial = async params => this[methodName] (path, type, uppercaseMethod, params || {})
                                        ^^^^^^

SyntaxError: Unexpected identifier

```

**Comment by kroitor** [comment]
@npomfret the async syntax won't work with Node version < 7, unfortunately. Version 6 is too old. I suggest updating it, if possible.

**Comment by npomfret** [comment]
Thanks!
