### ISSUE TITLE
Showing symbols of Bitmex shows strange result

### ISSUE THREAD

**Issue by lvthillo** [ccxt/ccxt#3842]
Info:

- OS: MacOs
- Programming Language version: Python3
- CCXT version: 1.17.231
- Exchange: Bitmex
- Method: instantiate

This is the issue:

```
bitmex = getattr(ccxt, 'bitmex')({
    'enableRateLimit': True,
})
```

And I use it to call the function to get the symbols:
```
def get_symbols(input):
    input.load_markets()
    all_symbols = input.symbols
    print(all_symbols)

get_symbols(bitmex)
```

and suddenly the output is:
`['.ADAXBT', '.ADAXBT30M', '.BCHXBT', '.BCHXBT30M', '.BETH', '.BETH30M', '.BVOL', '.BVOL24H', '.BVOL7D', `

What is wrong here or am I missing something?
I would expect something like ETH/BTC etc.

**Comment by lvthillo** [comment]
I see:
`Market ids are used during the REST request-response process to reference trading pairs within exchanges. The set of market ids is unique per exchange and cannot be used across exchanges. For example, the BTC/USD pair/market may have different ids on various popular exchanges, like btcusd, BTCUSD, XBTUSD, btc/usd, 42 (numeric id), BTC/USD, Btc/Usd, tBTCUSD, XXBTZUSD. You don't need to remember or use market ids, they are there for internal HTTP request-response purposes inside exchange implementations.`

**Comment by kroitor** [comment]
> What is wrong here or am I missing something?

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
- https://github.com/ccxt/ccxt/issues/3540

<img width="869" alt="screen shot 2018-09-13 at 19 10 53" src="https://user-images.githubusercontent.com/1294454/45501033-cdbdbf80-b788-11e8-868d-26fef9c4645d.png">

Basically, BitMEX markets are mostly futures contracts as explained in #3540. Let us know if the above does not answer the question.

**Comment by kroitor** [comment]
@lvthillo the symbols starting with the dot symbol `.` are actually the names of BitMEX indices.
