### ISSUE TITLE
Php Errors

### ISSUE THREAD

**Issue by Showgofar** [ccxt/ccxt#3846]
- OS: Centos
- Programming Language version: php
- CCXT version:  1.17.142
- Exchange: All
- Method: Fetch order book and all others

Hi
On php version 5.5 

Here are some warnings
```
Notice: Use of undefined constant ARRAY_FILTER_USE_KEY - assumed 'ARRAY_FILTER_USE_KEY' in /home/admin/www/ccxt/php/Exchange.php on line 1991

Warning: array_filter() expects at most 2 parameters, 3 given in /home/admin/www/ccxt/php/Exchange.php on line 1991

Warning: array_change_key_case() expects parameter 1 to be array, null given in /home/admin/www/ccxt/php/Exchange.php on line 1991

Warning: array_key_exists() expects parameter 2 to be array, null given in /home/admin/www/ccxt/php/Exchange.php on line 1994
```

**Comment by kroitor** [comment]
@Showgofar do you have the same issue with the most recent version of CCXT?

**Comment by kroitor** [comment]
- http://php.net/manual/en/array.constants.php

> ARRAY_FILTER_USE_KEY (integer)
> ARRAY_FILTER_USE_KEY is used with array_filter() to pass each key as the first argument to the given callback function. Added in PHP 5.6.0.

Looks like ARRAY_FILTER_USE_KEY requires PHP 5.6+, I'd recommend to upgrade PHP, that should solve the issue. I'm going to add a workaround for earlier versions soon.

Hope this answers your question, let us know if not.

**Comment by kroitor** [comment]
I'll add a workaround for it to make it backward compatible with 5.5

**Comment by kroitor** [comment]
@Showgofar this should work in PHP 5.5 as of version 1.17.292

**Comment by Showgofar** [comment]
also there is no compatibility with php 5.4 because of curl_reset() function
so you should update manual))
