### ISSUE TITLE
HitBTC v2 support for negative precision and lot sizes > 1

### ISSUE THREAD

**Issue by adi90x** [ccxt/ccxt#3847]
Hello, 

I cannot find when, but between ccxt 1.17.206 and now, there were a change to create order and edit order, it remove the lot units check ( and the appropriate error that was throw), plus the use of amountToPrecision create an error as soon as lot size is > 1, is it possible to correct it ?
Or implement decimalToPrecision with negative value + reimplement the lotsize error ? 

Regards

**Comment by adi90x** [comment]
Hello,
Isn't it possible to just multiply by 10e numPrecisionDigits ? In cas numPrecision < 0 ?

**Comment by kroitor** [comment]
Hi!

> Isn't it possible to just multiply by 10e numPrecisionDigits ? In cas numPrecision < 0 ?

https://github.com/ccxt/ccxt/pull/3741

**Comment by kroitor** [comment]
@ndubel 

> in ccxt 1.17.225 hitbtc2 works fine. 

Nope, it doesn't... It actually puts zeroes there... So it looks as if it was working, but it breaks in certain edge-cases.

> how to make it work now? (JS)

As a temporary workaround you can set the amount precision to zero on the market of interest to revert it to the old behavior:

```JavaScript
const exchange = new ccxt.hitbtc2 ({ ... })
;(async () => {
    await exchange.loadMarkets ();
    exchange.markets['IPL/ETH'].precision.amount = 0;
    // your code goes here ...
```

The above is explained in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

**Comment by adi90x** [comment]
Any update on this issue ?
