### ISSUE TITLE
Nonce error on CEX

### ISSUE THREAD

**Issue by mw130** [ccxt/ccxt#3848]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: macOS High Sierra
- Programming Language version: Python 3
- CCXT version: 1.17.291
- Exchange: CEX
- Method: fetch_closed_orders()
Code:
```
client = ccxt.cex({
        'uid' : "",

        'apiKey': ""
        ,
        'secret': "",
        'nonce': lambda: int(time.time() * 1000), // or ccxt.Exchange.milliseconds() (neither works)
        'enableRateLimit': True,
        'ratelimit': 10
    }) 
```

Traceback:
`Traceback (most recent call last):
  File "/Users/mwaldman/PycharmProjects/Algorithms/Lambda/test.py", line 59, in <module>
    orders  = client.fetch_closed_orders(market, since=time_period * 60, limit=10)
  File "/Users/mwaldman/PycharmProjects/Bina/venv/lib/python3.6/site-packages/ccxt/cex.py", line 453, in fetch_closed_orders
    response = getattr(self, method)(self.extend(request, params))
  File "/Users/mwaldman/PycharmProjects/Bina/venv/lib/python3.6/site-packages/ccxt/cex.py", line 500, in request
    raise ExchangeError(self.id + ' ' + self.json(response))
ccxt.base.errors.ExchangeError: cex {"error":"Nonce must be incremented"}`

**Comment by kroitor** [comment]
@mw130 does it work without the nonce override?

**Comment by mw130** [comment]
Hey Igor, it does not. It still complains it must be incremented even without override.

**Comment by kroitor** [comment]
@mw130 does fetchBalance work with the following snippet:

```Python
import ccxt
from pprint import pprint
client = ccxt.cex({
    'uid' : "YOUR_UID",
    'apiKey': "YOUR_API_KEY",
    'secret': "YOUR_SECRET",
    'enableRateLimit': True,
}) 
pprint(client.fetch_balance ())
```
? 

If the above snippet does not work, then let us know if it's a new key or not.

**Comment by mw130** [comment]
I ran the exact code you just gave, and it complained of the same error. it is not a new key. Unfortunately, I cannot generate a new key at the moment.

**Comment by kroitor** [comment]
> I ran the exact code you just gave, and it complained of the same error. it is not a new key.
> Unfortunately, I cannot generate a new key at the moment.

Then you should ask the person who owns the key, for their algorithm of nonce generation, because, obviously, that key has already been used with a nonce greater than you're sending. Most likely, it has been used with a microseconds-value, which is 1000 times greater than ms, though, I'm not sure. Your snippet works for me with a new key, both with and without the override (the override actually does nothing, because cex has the same implementation of ms-nonce by default).

**Comment by mw130** [comment]
Ah. I see. It is my key, but I cannot access the account currently because my 2fa device got lost. I will wait for a reset and generate a new key. Thanks for looking into it.

**Comment by kroitor** [comment]
@mw130 if that key is yours, you can try to multiply the value by a thousand, like so:

```Python
client = ccxt.cex({
    ...
    'nonce': lambda: int(time.time() * 1000000), // or ccxt.Exchange.microseconds()
    ...
}) 
```

And see if it works...

**Comment by kroitor** [comment]
I'd close this for now if you don't mind, feel free to reopen it if needed, or just ask more questions, if any...

**Comment by mw130** [comment]
Thanks

**Comment by mw130** [comment]
@kroitor I do have another question, is asking through here the best way? I don't want to open another issue. The question/issue is, in working with coinbase pro, I made a call `client.fetch_closed_orders(market, since=time.time() - 600)` which according to the docs should return orders that were closed in the last ten minutes. However, that does not work and it returns orders closed as far as 2017. I cannot for any reason figure out why, but if it helps the limit parameter does indeed work, and will return from the beginning up to whatever limit I pass it. Thanks so much.

**Comment by kroitor** [comment]
`since=time.time() - 600` ← this is a value in seconds. While all CCXT unified methods accept milliseconds for time-values. This is documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#pagination, let me know if that does not answer your question

**Comment by mw130** [comment]
@kroitor amazing! Thank you so much.
