### ISSUE TITLE
How to close position on bitmex?

### ISSUE THREAD

**Issue by neatek** [ccxt/ccxt#3850]
- OS: Windows 10 Pro
- Programming Language version: Python 3.6.3 (v3.6.3:2c5fed8)
- CCXT version: 1.17.295
- Exchange: bitmex
- Method: ?

Hello, everyone, i have simple question about `**positions**`, how to `**close position**` on bitmex via ccxt?

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/issues/2096#issuecomment-377768695

**Comment by enriquepiatti** [comment]
Here it says it is deprecated:  
https://www.bitmex.com/api/explorer/#!/Order/Order_closePosition  
we should use private_post_order then? I'm not sure how to send the parameters there
