### ISSUE TITLE
coinex res/market api restriction

### ISSUE THREAD

**Issue by ngugc** [ccxt/ccxt#3861]
- OS: all
- Programming Language version: all
- CCXT version: 1.17.302
- Exchange: CoinEx
- Method:

CCXT uses https://www.coinex.com/res/market to retrieve market info, but it has two problems:
* Not officially public, may be changed in the future.
* It's restricted very frequently, Per my experience, the maximum access frequency is about 1 time every 3 seconds.

As the data is not changed frequently, is it possible to write down the data to a local file, and update it every day?

**Comment by kroitor** [comment]
> As the data is not changed frequently, is it possible to write down the data to a local file, and update it every day?

Yes, but, we believe, this type of caching should be done in userland, outside of the library. You can save and restore the `.markets` property how you like, setting that property will effectively turn off loading markets from the exchange. Just google for *"serialize / deserialize json file"* and you'll get a ton of results for your language on stackoverflow, reddit or elsewhere. Hope this answers your question.
