### ISSUE TITLE
Kucoin price precision issue in PHP

### ISSUE THREAD

**Issue by Umbralith** [ccxt/ccxt#3862]
When placing an order to Kucoin, if I sell 0.001 BTC @ 10001 USDT, it sends the request just fine. But if I set the price to 10000, it strips the trailing 0's and sends the request as 0.001 BTC @ 1 USDT, resulting in a failed request because the price is too low.

**Comment by Umbralith** [comment]
This seems critical as it ruins placing orders for kucoin. It might have something to do with the decimal_to_precision funciton. I saw there was a fix to that function 12 days ago and I pulled the most recent version of ccxt, but it still happens, so I guess this issue is unrelated to the previous issue

**Comment by kroitor** [comment]
Related: #3857

**Comment by Umbralith** [comment]
So I found the error, IT seems to be a php error. The rtrim method in decimal_to_precision doens't work as expected.

**Comment by Umbralith** [comment]
rtrim("100.000", "0.") should trim anything, because "0." isn't at the end of that string, but it trims everything until the 1.  If I do rtrim ("100.000", "."), it return "100.000" as expected.

As another example, I did
```
rtrim("shshsh", "sh.")
```
and it returns an empty string

**Comment by Umbralith** [comment]
https://stackoverflow.com/questions/52370727/why-does-rtrim-remove-things-that-arent-on-the-right

**Comment by Umbralith** [comment]
Solution I think would be to run rtrim twice like this
```
$price = "100.000";
$price = rtrim($price, "0");
$price = rtrim($price, ".");
```
I can't get to it right this second, but if this is still open later tonight I can put in a PR

**Comment by kroitor** [comment]
@Umbralith can you please show your verbose request/response? 

```PHP
$exchange->load_markets ();
$exchange->verbose = true;
$exchange->create_order (...
```

Also, what's your version of PHP?

**Comment by kroitor** [comment]
```
mbp:ccxt igorkroitor$ php -a
Interactive shell

php > include_once ('./ccxt.php');
php > $id = '\ccxt\kucoin';
php > $exchange = new $id ();
php > $exchange->load_markets();
php > print_r($exchange->currency('USDT'));
Array
(
    [id] => USDT
    [code] => USDT
    [info] => Array
        (
            [withdrawMinFee] => 3.2
            [coinType] =>
            [withdrawMinAmount] => 20
            [withdrawRemark] =>
            [orgAddress] =>
            [txUrl] => http://omniexplorer.info/lookuptx.aspx?txid={txId}
            [userAddressName] =>
            [withdrawFeeRate] => 0.001
            [confirmationCount] => 3
            [infoUrl] =>
            [enable] => 1
            [name] => USDT
            [tradePrecision] => 6
            [depositRemark] =>
            [enableWithdraw] => 1
            [enableDeposit] => 1
            [coin] => USDT
        )

    [name] => USDT
    [active] => 1
    [fee] => 3.2
    [precision] => 6
    [limits] => Array
        (
            [amount] => Array
                (
                    [min] => 1.0E-6
                    [max] => 1000000
                )

            [price] => Array
                (
                    [min] => 1.0E-6
                    [max] => 1000000
                )

            [cost] => Array
                (
                    [min] =>
                    [max] =>
                )

            [withdraw] => Array
                (
                    [min] => 20
                    [max] => 1000000
                )

        )

)
php > print_r($exchange->decimal_to_precision (10000, 0, 6, 0));
10000
php > print_r($exchange->decimal_to_precision ('10000', 0, 6, 0));
10000
php > print_r($exchange::VERSION);
1.17.305
php >
```
