### ISSUE TITLE
coin base info

### ISSUE THREAD

**Issue by Labradors** [ccxt/ccxt#3865]
Whether api contains basic currency information, such as release time, total amount of distribution, introduction, etc.

**Comment by kroitor** [comment]
Sorry? Didn't quite get it, what's your question or issue? Can you, please, clarify/elaborate ?

**Comment by Labradors** [comment]
how to get the coin information? such as release time, total amount of distribution, introduction, etc.

**Comment by kroitor** [comment]
> how to get the coin information? such as release time, total amount of distribution, introduction, etc.

Exchanges won't provide that info in full sense. They will provide some partial description and a name, and, basically, that's it. You can grab some of that info from CoinMarketCap using implicit methods (https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods) or using other explorer-sites. Let us know if that does not answer the question. Feel free to ask, if you have more.
