### ISSUE TITLE
Async edit_order emulation

### ISSUE THREAD

**Issue by cfytrok** [ccxt/ccxt#3869]
- OS: Windows 10
- Programming Language version: Python
- CCXT version: 1.17.269
- Exchange: Okex
- Method: edit_order, cancel_order, create_order

Default implementation of edit_order waits cacel_order return.
```
def edit_order(self, id, symbol, *args):
    if not self.enableRateLimit:
        self.raise_error(ExchangeError, details='edit_order() requires enableRateLimit = true')
    self.cancel_order(id, symbol)
    return self.create_order(symbol, *args)
```
Is there a good way to do simultaneous cancel and create requests?

I tried to call cancel_order and create_order in different threads. Create_order sometimes returns id of order, that I tryied to cancel. 
It seems Exchange.fetch is not thread safe because it saves response to last_http_response attribute and handles this attribute instead of handling response directly.

Verbose output:
<details>
Request: POST https://www.okex.com/api/v1/cancel_order.do {'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} 
Request: POST api_key=XXX&order_id=497180332&symbol=ltc_btc&sign=XXX
https://www.okex.com/api/v1/trade.do {'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} amount=0.003849&api_key=XXX&price=0.00816920&symbol=ltc_btc&type=buy&sign=XXX

Response: POST https://www.okex.com/api/v1/trade.do
Response: POST https://www.okex.com/api/v1/cancel_order.do 200 {'Date': 'Tue, 18 Sep 2018 10:36:04 GMT', 'Content-Type': 'application/json', 'Content-Length': '38', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=dc832e73b187839662bc11e4728adc2951537266963; expires=Wed, 18-Sep-19 10:36:03 GMT; path=/; domain=.okex.com; HttpOnly, locale=en_US; Max-Age=604800; Expires=Tue, 25-Sep-2018 10:36:03 GMT; Path=/', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY', 'X-RateLimit-Limit': '20', 'X-RateLimit-Remaining': '19', 'X-RateLimit-Used': '1', 'X-RateLimit-Reset': '1537266965946', 'X-Kong-Upstream-Latency': '28', 'X-Kong-Proxy-Latency': '0', 'Via': 'kong/0.12.3', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '45c32b5bbe7b4f50-DME'} {"result":true,"order_id":"497180332"} 
200 {'Date': 'Tue, 18 Sep 2018 10:36:04 GMT', 'Content-Type': 'application/json', 'Content-Length': '36', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d06c875237c37068840892dd3bad2fa5a1537266963; expires=Wed, 18-Sep-19 10:36:03 GMT; path=/; domain=.okex.com; HttpOnly, locale=en_US; Max-Age=604800; Expires=Tue, 25-Sep-2018 10:36:03 GMT; Path=/', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY', 'X-RateLimit-Limit': '20', 'X-RateLimit-Remaining': '19', 'X-RateLimit-Used': '1', 'X-RateLimit-Reset': '1537266965951', 'X-Kong-Upstream-Latency': '36', 'X-Kong-Proxy-Latency': '0', 'Via': 'kong/0.12.3', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '45c32b5bda757612-ARN'} {"result":true,"order_id":497180459}
</details>

**Comment by kroitor** [comment]
> Is there a good way to do simultaneous cancel and create requests?

Have you looked into the async version of the library? https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/base/exchange.py#L243

You can redefine this method to `asyncio.gather` the end-result of those two calls almost simultaneously, however, because those are two private requests, you will have to manage the rate limits and nonce, as documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#authentication
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-the-nonce

Let us know if that does not answer your question.

**Comment by kroitor** [comment]
@cfytrok I've fixed it a couple of days ago: https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/base/exchange.py#L116
