### ISSUE TITLE
Bitmex loadMarkets() 403 error

### ISSUE THREAD

**Issue by mgarsteck** [ccxt/ccxt#3875]
- OS: OSX 10.12.6
- Programming Language version: JS
- CCXT version: 1.17.232
- Exchange: Bitmex
- Method: loadMarkets*

I am getting a 403 error on Bitmex when I try to call loadMarkets() or fetchOHLCV.  In fact I am only able to call the the methods like privateGetUserWallet.  Im able to retrieve my account data and history from that, but why am I not able to use the other methods like OHLCV?  I have looked through the repo and documentation but am stuck here.

**Comment by lvthillo** [comment]
@mgarsteck 
For me it seems to work. Can you share your code?

const ccxt = require ('ccxt')
```

function test() {
(async () => {
    // Instantiate the exchange
    let exchange = new ccxt.bitmex ()
    // In order to load markets manually beforehand call the loadMarkets () / load_markets () method on an exchange instance
    let markets = await exchange.load_markets ()
    // Print output
    console.log (exchange.id, markets)
}) ()
}
```

Part of output:
```
  ...
  XBTU18:
   { limits: { amount: [Object], price: [Object] },
     precision: { amount: 0, price: 1 },
     tierBased: undefined,
     percentage: undefined,
     taker: 0.00075,
     maker: -0.00025,
     id: 'XBTU18',
     symbol: 'XBTU18',
     base: 'BTC',
     quote: 'USD',
     baseId: 'XBT',
     quoteId: 'USD',
     active: true,
     type: 'future',
     spot: false,
     swap: false,
     future: true,
     prediction: false,
     info:
      { symbol: 'XBTU18',
        rootSymbol: 'XBT',
        state: 'Open',
        typ: 'FFCCSX',
        listing: '2018-03-31T06:00:00.000Z',
        front: '2018-07-27T12:00:00.000Z',
        expiry: '2018-09-28T12:00:00.000Z',
        settle: '2018-09-28T12:00:00.000Z',
        relistInterval: null,
        inverseLeg: '',
        sellLeg: '',
        buyLeg: '',
        optionStrikePcnt: null,
        optionStrikeRound: null,
   ...
```

**Comment by mgarsteck** [comment]
`async componentDidMount() {
    let nonce = 1;
    // let ids = await ccxt.exchanges.filter (id => id in this.state.exchanges);
    let bitmex = new ccxt.bitmex({
      'apiKey': "**************",
      'secret': "hZrEcCaN9Td2fbRSNR5IraK5UYkK_VfoQcLQzHs7xf0zo60C",
      'enableRateLimit': true,
      'proxy': 'https://cors-anywhere.herokuapp.com/',
      'nonce': Date.now,
    });

    console.log(bitmex);
    // WORKS FINE
    let wallet = await bitmex.private_get_user_wallet();
    let margin = await bitmex.private_get_user_margin();
    let position = await bitmex.private_get_position();
    let exechistory = await bitmex.private_get_execution_tradehistory();
    // console.log(margin);
    

    // RETURNS ERROR
    let markets = await bitmex.load_markets();
    console.log(markets);
    

    this.setState({
      wallet: wallet,
      current: margin.walletBalance,
      position: position,
      margin: margin.availableMargin,
    });
    // console.log(this.state.wallet);
    // console.log(this.state.position);
  }`


<img width="350" alt="screen shot 2018-09-19 at 3 06 06 pm" src="https://user-images.githubusercontent.com/8356522/45784450-9bdfa980-bc1d-11e8-8ac1-aa5b2b77877b.png">

**Comment by kroitor** [comment]
@mgarsteck remove the proxy and the nonce override from your instantiation code:

```JavaScript
let bitmex = new ccxt.bitmex({
  'apiKey': "**************",
  'secret': "hZrEcCaN9Td2fbRSNR5IraK5UYkK_VfoQcLQzHs7xf0zo60C",
  'enableRateLimit': true,

  //------------------------------------------------------------------------------
  // REMOVE THE FOLLOWING TWO LINES
  // 'proxy': 'https://cors-anywhere.herokuapp.com/',
  // 'nonce': Date.now,
});
```

Let us know if that does not help.

https://github.com/ccxt/ccxt/wiki

**Comment by mgarsteck** [comment]
@kroitor I removed the two lines, one at a time and got this CORS error. 

<img width="381" alt="screen shot 2018-09-19 at 6 29 25 pm" src="https://user-images.githubusercontent.com/8356522/45790494-fa1a8580-bc39-11e8-8741-bcc7a6358f4e.png">

**Comment by kroitor** [comment]
@mgarsteck oh, I see, you're running it from a browser... when using a CORS proxy, you should also define the origin header:

```JavaScript
let bitmex = new ccxt.bitmex({
  'apiKey': "**************",
  'secret': "*******************",
  'enableRateLimit': true,

  // RESTORE THIS LINE

  'proxy': 'https://cors-anywhere.herokuapp.com/',

  // AND ADD THIS LINE

  'origin': 'foobar', // ←---------------- any unique arbitrary string you like
});
```

Let us know whether it solves the issue for you or not.

**Comment by mgarsteck** [comment]
@kroitor I changed the code and I still get the same 403 error as before.

**Comment by kroitor** [comment]
@mgarsteck sure! Actually, you'd better install it with Node and try outside of a browser, because browsers have their own limitations (like the need for CORS, proxies, etc...). In a Node environment (be it on your local machine or a remote server) you won't have to deal with the above issues and BitMEX will work normally... Unfortunately, it doesn't want to work from a browser, I'm going to investigate into it further.

**Comment by mgarsteck** [comment]
@kroitor Thanks for clearing things up.  Will give it a shot and let you know what I find.
