### ISSUE TITLE
bibox fetch_order_book() requires apiKey while the api doc says it does not 

### ISSUE THREAD

**Issue by zjingpopo** [ccxt/ccxt#3879]
https://github.com/Biboxcom/API_Docs_en/wiki/REST_Request_Response
according to the api doc example, "cmd": "api/depth", and "cmd": "api/ticker",  does not need an apiKey. 
I can get the result through a http request without any apikey and secret.
ubuntu:~$ curl 'https://api.bibox.com/v1/mdata?cmd=depth&pair=BTC_USDT&size=20'
{"result":{"pair":"BTC_USDT","update_time":1537493887054,"bids":[{"volume":"0.516","price":"6493.1204"},{"volume":"0.0007","price":"6493.1201"},{"volume":"0.0001","price":"6488.01"},{"volume":"0.0661","price":"6486.1343"},{"volume":"1.927","price":"6480.0002"},{"volume":"0.0258","price":"6480"},{"volume":"0.0759","price":"6474.6264"},{"volume":"0.0241","price":"6474.5477"},{"volume":"0.0533","price":"6465.272"},{"volume":"0.0092","price":"6327.2427"},{"volume":"0.0083","price":"6314.1156"},{"volume":"0.03","price":"6311.9353"},{"volume":"0.1213","price":"6310"},{"volume":"0.05","price":"6301.5426"},{"volume":"0.03","price":"6289.9353"},{"volume":"0.1915","price":"6270"},{"volume":"0.2013","price":"6250"},{"volume":"0.0002","price":"6215"},{"volume":"0.0085","price":"6214.1156"},{"volume":"0.1232","price":"6210"}],"asks":[{"volume":"0.0148","price":"6513.2933"},{"volume":"0.4292","price":"6515.5389"},{"volume":"0.0435","price":"6515.54"},{"volume":"0.288","price":"6522.3531"},{"volume":"0.5113","price":"6522.3532"},{"volume":"0.2058","price":"6549.998"},{"volume":"0.3914","price":"6550"},{"volume":"0.2537","price":"6566"},{"volume":"0.1281","price":"6590"},{"volume":"0.3585","price":"6590.0003"},{"volume":"0.0069","price":"6593.3258"},{"volume":"0.0074","price":"6597.2297"},{"volume":"0.1","price":"6600"},{"volume":"0.15","price":"6650"},{"volume":"0.1399","price":"6768"},{"volume":"0.0439","price":"6797.5576"},{"volume":"0.0122","price":"7073.526"},{"volume":"0.0175","price":"7078.17"},{"volume":"0.0144","price":"7092.7057"},{"volume":"0.003","price":"7130"}]},"cmd":"depth"}

Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> bibox = ccxt.bibox()
>>> bibox.fetch_order_book('BTC/USDT', limit=20)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ccxt/bibox.py", line 299, in fetch_order_book
    self.load_markets()
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 1036, in load_markets
    currencies = self.fetch_currencies()
  File "/usr/local/lib/python3.6/dist-packages/ccxt/bibox.py", line 333, in fetch_currencies
    'body': {},
  File "/usr/local/lib/python3.6/dist-packages/ccxt/bibox.py", line 677, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 358, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/bibox.py", line 648, in sign
    self.check_required_credentials()
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 922, in check_required_credentials
    self.raise_error(AuthenticationError, details='requires `' + key + '`')
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 344, in raise_error
    raise exception_type(output)
ccxt.base.errors.AuthenticationError: bibox requires `apiKey`
>>> bibox.fetch_tickers()
[{'symbol': 'BIX/BTC', 'timestamp': None, 'datetime': None, 'high': 6.617e-05, 'low': 6.231e-05, 'bid': None, 'bidVolume': None, 'ask': None, 'askVolume': None, 'vwap': None, 'open': 6.482e-05, 'close': 6.546e-05, 'last': 6.546e-05, 'previousClose': None, 'change': 6.4e-07, 'percentage': 0.99, 'average': None, 'baseVolume': 27938102.0, 'quoteVolume': 1797.21, 'info': {'id': 1, 'is_hide': 0, 'coin_symbol': 'BIX', 'currency_symbol': 'BTC', 'last': '0.00006546', 'high': '0.00006617', 'low': '0.00006231', 'change': '+0.00000064', 'percent': '+0.99%', 'vol24H': '27938102', 'amount': '1797.21', 'last_cny': '2.9117', 'high_cny': '2.9433', 'low_cny': '2.7716', 'last_usd': '0.4252', 'high_usd': '0.4298', 'low_usd': '0.4048'}}, {'symbol': 'BIX/ETH', 'timestamp': None, 'datetime': None, 'high': 0.00202552, 'low': 0.0018616, 'bid': None, 'bidVolume': None, 'ask': None, 'askVolume': None, 'vwap': None, 'open': 0.00197716, 'close': 0.00191795, 'last': 0.00191795, 'previousClose': None, 'change': -5.921e-05, 'percentage': -2.99, 'average': None, 'baseVolume': 18917228.0, 'quot

Can I get a version that doesn't need apiKey for fetch_ticker and fetch_order_book? Just like the fetch_tickers(). Thanks.

- OS: ubuntu 18.04
- Programming Language version: python3.6.5
- CCXT version: '1.17.327'
- Exchange: bibox
- Method: fetch_order_book, fetch_ticker

**Comment by kroitor** [comment]
> according to the api doc example, "cmd": "api/depth", and "cmd": "api/ticker", does not need an apiKey.


Yes, but it has to loading markets and currencies before accessing other data, in order to parse further info properly. Unfortunately the 'transfer/coinList' endpoint for currencies is private with Bibox. We will try to workaround that limitation.

**Comment by zjingpopo** [comment]
> > according to the api doc example, "cmd": "api/depth", and "cmd": "api/ticker", does not need an apiKey.
> 
> Yes, but it has to load markets and currencies before accessing other data in order to parse further info properly. Unfortunately the `transfer/coinList` endpoint for currencies is private with Bibox. We will try to workaround that limitation.

I do have bibox apiKey by the way, the real problem is if I use apiKey I'll get error code 2091 (yes I know I exceed the rateLImit but for market api this should be fine). So my workaround is:
bibox = ccxt.bibox()
bibox.has[''fetchCurrencies] = False # so the load_market doesn't call the fetch_currencies method which we don't need.
I just hope ccxt has an option to not use apiKey for those requests that don't need it. 
Thanks for the reply.

**Comment by kroitor** [comment]
I've added a more friendly warning about the apiKeys and fetchCurrencies according to your comment, so, if you update to version 1.18.437+, and set `has['fetchCurrencies'] = False`, it will skip loading the currency details and won't ask for authentication.
