### ISSUE TITLE
Ambiguous coins, BOX: ContextBox vs BOX Token

### ISSUE THREAD

**Issue by tangopium** [ccxt/ccxt#3881]
The issue is more or less generic and already somehow addressed in ccxt. The problem is that there are a lot of ambiguous currencies. I just lost 50€ because I transfered ContentBox (BOX) tokens to BOX Token (BOX). And there are apparently more BOX currencies. Is there any list/maxtrix you maintain to kind of unify the currency names? If not, I would propose to build one.

**Comment by tangopium** [comment]
Would you mind linking the issue to which this one is a duplicate? I searched for it but didn't find it

**Comment by kroitor** [comment]
> The issue is more or less generic and already somehow addressed in ccxt. The problem is that there are a lot of ambiguous currencies. I just lost 50€ because I transfered ContentBox (BOX) tokens to BOX Token (BOX). And there are apparently more BOX currencies. Is there any list/maxtrix you maintain to kind of unify the currency names?

This is documented here:

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
- https://github.com/ccxt/ccxt/wiki/Manual#naming-consistency
- https://github.com/ccxt/ccxt/wiki/Manual#notes-on-naming-consistency
- https://github.com/ccxt/ccxt/issues/3077 ←---- duplicate
- https://github.com/ccxt/ccxt/issues?page=1&q=author%3Aarielorvits+is%3Aclosed ←----- tons of duplicates
- use search...

We will be happy if you report the inconsistencies you found (the exchanges and their symbolic conflict)

> If not, I would propose to build one.

Thanks for the proposal! Your contributions are welcome! ;) Read more about it here:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

Also, see these examples:

- https://github.com/ccxt/ccxt/blob/master/examples/js/arbitrage-pairs.js
- https://github.com/ccxt/ccxt/blob/master/examples/js/cli.js
- https://github.com/ccxt/ccxt/blob/master/examples/js/exchange-capabilities.js
- https://github.com/ccxt/ccxt/blob/master/examples/js/symbols.js
- https://github.com/ccxt/ccxt/blob/master/examples/js/search-all-exchanges.js

Let us know if the above does not answer your question. Thx!

**Comment by kroitor** [comment]
```
Currencies: (test @ search-all-exchanges.js:114)

id    numericId  code  exchange       name                     active  fee   status  type
-------------------------------------------------------------------------------------------
BOX              BOX   bitfinex
fBOX             BOX   bitfinex2
box              BOX   bitz
BOX              BOX   coinmarketcap  ContentBox               true
BOXX             BOXX  coinmarketcap  BOXX Token [Blockparty]  true
BOXX             BOXX  cryptopia      Boxx                     true    0.01  ok
BOX              BOX   ethfinex
box              BOX   fcoin
box              BOX   huobipro       BOX                      true                  crypto
BOX              BOX   uex                                                                  (test @ search-all-exchanges.js:126)

--------------------------------------------------------------- (test @ search-all-exchanges.js:128)

88 markets and 10 currencies (test @ search-all-exchanges.js:131)
```

We will fix the conflict with BOX asap.

**Comment by kroitor** [comment]
@tangopium can you tell which of the exchanges are in conflict?

**Comment by tangopium** [comment]
The following exchanges are trading BOX Token (https://etherscan.io/token/0xe1A178B681BD05964d3e3Ed33AE731577d9d96dD):

- Bit-Z

The following ContentBox (https://etherscan.io/token/0x63f584fa56e60e4d0fe8802b27c7e6e3b33e007f):

- huobipro
- coinmarketcap
- ethfinex
- bitfinex
- uex

And I cannot find BOX on the following platforms listed by you(r script):

- fcoin

**BOXX** is another currency and I didn't find **fBOX** anywhere.

**Comment by kroitor** [comment]
@tangopium 

Thx for reporting it! I've uploaded a fix for Bit-Z. It is now recoded to its name (`BOX Token`) according to the Manual as of CCXT 1.17.329. 

Sorry for the inconvenience with conflicting symbols and for your loss of money. We're a library under development, as we tried to explain in the doc. I'd recommend to read it from top to bottom first to understand the inner workings of it as well as risks and implications. That will help save your time and money, really.

> And I cannot find BOX on the following platforms listed by you(r script): fcoin

```
mbp:ccxt igorkroitor$ node examples/js/symbols fcoin
Instantiating fcoin exchange

Symbols:

tierBased | percentage | taker | maker | id           | symbol        | base     | quote    | baseId   | quoteId  | active
--------------------------------------------------------------------------------------------------------------------------
...
false     | true       | 0.001 | 0.001 | boxeth       | BOX/ETH       | BOX      | ETH      | box      | eth      | true
...
---------------------------------------------------------------

Currencies:

id       | numericId | code     | precision
-------------------------------------------
...
bnb      |           | BNB      | 2
boc      |           | BOC      | 2
box      |           | BOX      | 2 ←------------- IN THEIR LIST
brm      |           | BRM      | 2
btc      |           | BTC      | 8
...

---------------------------------------------------------------
fcoin has 252 symbols and 212 currencies
```

> I didn't find fBOX anywhere.

This is because `fBOX` is an exchange-specific **id**, and `BOX` is its unified common currency **code**, the difference is explained in the Manual (links above on ids and symbols).

Let us know if you have further questions, will be happy to help.

**Comment by Poldarn** [comment]
Sorry to reopen this again. I have had the same issue with GST. In some exchanges this symbol is GrEARN  (Hitbtc) and in other is Game Star (Yobit).

It looks like every token has a particular contract id, so perhaps this could be used to unequivocally identify the token?

e.g. 
For GrEARN it has this contract:
https://etherscan.io/token/0x3afa1902b1f8a802abc18e5ad982d1bcd34afe22

And this is the one for Game Stars
https://etherscan.io/token/0x67a9099f0008c35c61c00042cd9fb03684451097
