### ISSUE TITLE
Scripts can't run on multiple exchanges because data returned isn't standardized

### ISSUE THREAD

**Issue by mw130** [ccxt/ccxt#3882]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: OS X
- Programming Language version: Python 3
- CCXT version: 1.
- Exchange: Binance
- Method: cancel_order

I'm trying to run an algorithm that involves placing buys and cancelling those buys, repeatedly. I wrote it based on coinbasepro, where I ran 
`for order in client.fetch_open_orders(market)
      client.cancel_order(order['id'])`
(basic idea) 
same issue with something like 
             `for i in closed_orders:
                          if i['info']['done_reason'] == 'filled':
                                       filled_amt += 1`
, essentially I will run into multiple KeyError exceptions because the data that is returned isn't standardized - in coinbasepro, I can index into the order dictionary with ['id'] but cannot do the same in Binance. I am not sure how to work around this other than adding several if clauses for each data style used by each exchange API. Please advise, thank you.

**Comment by kroitor** [comment]
> if i['info']['done_reason']

Don't use the `info` field, it contains the raw response from the exchange as is, in exchange-specific format (differs from exchange to exchange). Please read the Manual from top to bottom to understand how the Unified API works. 

- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/Manual#unified-api
- https://github.com/ccxt/ccxt/wiki/Manual#order-structure

Let us know if that does not answer your question.

**Comment by kroitor** [comment]
> Is cancelling orders by ID not translatable from cbp to Binance?

Approx 50% of exchanges will require a symbol for canceling the order by a known id even despite that id is already known. So, in general, you want to always supply a symbol to cancelOrder.
