### ISSUE TITLE
Get orderbook url for a symbol

### ISSUE THREAD

**Issue by abhishekgahlot** [ccxt/ccxt#3887]
Hi,

I want to get orderbook url for a symbol. I understand you change it internally to match with other symbols. So what I am looking for is for eg symbol BTC/ETH where does ccxt send the request to, of course I can log them and I tried logging to in `fetch` function.

For eg lets say: BTC/ETH url looks like:
```
'https://api.binance.com/api/v1/depth?symbol=ETHBTC' ,
'https://api.hitbtc.com/api/2/public/orderbook/ETHBTC' ,
```

But for few exchange like kraken and bittrex the symbol reverses:
```
'https://poloniex.com/public?command=returnOrderBook&currencyPair=ETH_BTC&depth=20' ,
'https://api.kraken.com/0/public/Depth?pair=XETHXXBT' ,

```

Though how do you do it internally in codebase is I am looking it. Any help to code link will be real helpful. **Basically I need to extract out that function which maps ccxt symbols to the one used in actual api url.**

Thanks

**Comment by xCuri0** [comment]
Verbose mode can print all requests

**Comment by kroitor** [comment]
> Basically I need to extract out that function which maps ccxt symbols to the one used in actual api url.

@abhishekgahlot that function is documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids. 

Also, if you want to intercept the URL itself, you will have to look into and/or override one of the following methods: `request()`, `fetch()` or `sign()`, see how those are implemented in most of exchanges.

Let us know if the above does not answer your question.
