### ISSUE TITLE
Kraken MARKET order returns error

### ISSUE THREAD

**Issue by mariodantas** [ccxt/ccxt#3892]
- OS: Ubuntu 18.04
- Programming Language version: PHP 7.0
- CCXT version: Last
- Exchange: Kraken
- Method: create_market_sell_rder

Kraken returns this:

kraken {"error":["EGeneral:Invalid arguments:volume"]}

When I use this:
$oOrder = $oExchanger->create_market_sell_order($cPair, $nOrder_amount);

$cPair is I.E. "BTC-EUR" (string)
$nOrder_amount is I.E. 5627 (float)

**Comment by kroitor** [comment]
> $cPair is I.E. "BTC-EUR" (string)

We don't have symbols with a dash. Most of our symbols have a slash instead, as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

> $nOrder_amount is I.E. 5627 (float)

You don't really want to buy 5627 Bitcoin. Throughout this entire lib, amount is **always** in base currency, price is in quote currency.

- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders
- https://github.com/ccxt/ccxt/wiki/Manual#market-orders
- https://github.com/ccxt/ccxt/wiki/Manual#consistency-of-base-and-quote-currencies

I'd really recommend to read the entire Manual from top to bottom at least once, it will save you a lot of time, really... Hopefully this answers your question, let us know if not.

**Comment by mariodantas** [comment]
Sorry fellow, I did a mistake, of course $cPair is "BTC/EUR" (slash and not dash)

And

$nOrder_amount is 0.034245000 (float)

**Comment by kroitor** [comment]
@mariodantas can you show your verbose output?

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

```PHP
$oExchanger->load_markets();
echo "CCXT Version: " . $exchange::VERSION . "\n";
$oExchanger->verbose = true;
$oOrder = $oExchanger->create_market_sell_order($cPair, $nOrder_amount);
```

↑ Post your CCXT version and your verbose request/response, plz.
