### ISSUE TITLE
Kucoin fetch_open_orders loses returned values

### ISSUE THREAD

**Issue by MigzuASD** [ccxt/ccxt#3893]
I'm using CCXT 1.17.221 on Ubuntu 16.04 and Python 3.5.1-3. And I seem to have problems with fetch_open_orders.

I've tested this by opening a buy order on LTC/BTC-pair (trough the site). The exchange returns this order trough the api call to CCXT, but CCXT seems to lose it along the way and return me an empty array (no orders). I'm calling the method with symbol = "LTC/BTC" and rest of the parameters set to None (params = empty dict)

Here is what verbose shows for the request:
`GET https://api.kucoin.com/v1/order/active-map?symbol=LTC-BTC {'Accept-Encoding': 'gzip, deflate', 'KC-API-KEY': '<removed>', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'KC-API-NONCE': '<removed>', 'KC-API-SIGNATURE': '<removed>'} None`

and for the response:

`Response: GET https://api.kucoin.com/v1/order/active-map?symbol=LTC-BTC 200 {'KC-NODE': 'localhost', 'Access-Control-Max-Age': '86400', 'Content-Type': 'application/json;charset=UTF-8', 'Connection': 'keep-alive', 'Transfer-Encoding': 'chunked', 'Access-Control-Allow-Methods': 'GET,PUT,DELETE,POST', 'Date': 'Sun, 23 Sep 2018 01:22:21 GMT', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Origin': 'https://www.kucoin.com', 'Access-Control-Allow-Headers': '*'} {"success":true,"code":"OK","msg":"Operation succeeded.","timestamp":1537665741436,"data":{"SELL":[],"BUY":[{"oid":"<removed>","userOid":"<removed>","coinType":"LTC","coinTypePair":"BTC","direction":"BUY","price":0.006,"dealAmount":0.0,"pendingAmount":0.071208,"dealValue":0.0,"dealAveragePrice":0.0,"createdAt":1537665056000,"updatedAt":1537665056000}]}}`

However the fetch_open_orders-call returns me just with "[]"

This exchange object instance of kucoin is init'd with adjustForTimeDifference and ratelimits true. All other calls seem to work as supposed to.

**Comment by MigzuASD** [comment]
My bad. I had two installations of ccxt. Ancient one for user, the current one for root. Deleting the ancient one fixed my problem. My apologizations.

**Comment by kroitor** [comment]
@MigzuASD thx for reporting back!
