### ISSUE TITLE
Binance errors

### ISSUE THREAD

**Issue by mealesbia** [ccxt/ccxt#3897]
I'm facing errors like these:

```
 raise exception_type(output)
ccxt.base.errors.RequestTimeout: binance GET https://api.binance.com/api/v1/ticker/24hr?symbol=KEYBTC HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)
```
```
ccxt.base.errors.NetworkError: binance https://api.binance.com/api/v1/klines?symbol=ARNBTC&interval=30m&startTime=1535950423603&limit=1000 GET ('Connection aborted.', ConnectionResetError(104, 'Connection  reset by peer'))
```

Are this errors because I'm doing to many calls or just glitches from binance?  I have set `'enableRateLimit': True`, for binance.

**Comment by kroitor** [comment]
> Are this errors because I'm doing to many calls or just glitches from binance? 

This could be for two possible reasons:

1. You're have either sent too many requests already – in that case Binance may ban you for periods from 10 minutes to an hour on average, but may be up to a day if you were too aggressive
2. Or you have a networking issue reaching Binance from your location, you can check if that is the case that by using a public proxy, or a vpn or trying from another computer / address.

> I have set 'enableRateLimit': True, for binance.

It will be very hard to help you f you don't report the issue you precisely as described here (need a short complete snippet to reproduce the issue): 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

For now I suggest waiting for a reasonable time before retrying again. Let us know if that does not resolve itself or if you have any progress with reason 2.
