### ISSUE TITLE
CoinMarketCap API V1 deprecated December 2018

### ISSUE THREAD

**Issue by viktorius007** [ccxt/ccxt#3899]
This December, the current free CoinMarketCap API supported by ccxt will be deprecated.

A new, professional API supporting new endpoints, larger API call credits, historical data, OHLC data is currently live. 

This feature matrix has more comparative information:  [https://pro.coinmarketcap.com/faq](url)

The API documentation is located here:   [https://pro.coinmarketcap.com/api/v1](url)

There is a free tier as well as paid professional tiers: [https://pro.coinmarketcap.com/pricing](url)

I believe migrating to the new API would be of benefit to the ccxt community and would like to encourage the devs to consider this feature request.

Gratitude.

**Comment by mrmetech** [comment]
Right forcing them to pay for the data i think coingecko or coinlib are a better solution just my opinion though

**Comment by mrmetech** [comment]
The free tier doesn't give shit imo and ya

**Comment by TechupBusiness** [comment]
To be honest: I dont understand the pro free tier... is it missing even the current crypto prices?

Indeed there are anyway good alternatives. I knew CryptoCompare, thanks for the other two. So we have:
- https://www.cryptocompare.com/api
- https://www.coingecko.com/api/docs/v3
- https://coinlib.io/api/docs

**Comment by kroitor** [comment]
@mrmetech , @TechupBusiness your help with testing https://github.com/ccxt/ccxt/pull/3565 is really appreciated! )

More about it:
 
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-build--run-tests-on-your-local-machine

**Comment by mrmetech** [comment]
Ya am working on a site like coinmarketcap i will be sure i add it when am done it

**Comment by karlandoh** [comment]
Would like to add that the currencies and symbols information is inaccurate. The max API call of the new currencies is 100. As a result, only the first 100 currencies are retrieved upon:

```
cmc.currencies
```
(The load_markets() module has been successfully implemented into the object (ccxt.coinmarketcap()), named **cmc**).

```
Request: GET https://api.coinmarketcap.com/v1/ticker/?limit=0 {'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.coinmarketcap.com/v1/ticker/?limit=0 200 {'Date': 'Sat, 29 Dec 2018 13:36:20 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d340b2b1aed61766555b48e82fd4c4eae1546090580; expires=Sun, 29-Dec-19 13:36:20 GMT; path=/; domain=.coinmarketcap.com; HttpOnly; Secure', 'Access-Control-Allow-Origin': '*', 'CF-Cache-Status': 'HIT', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '490ca7ad8a09ab7e-YYZ', 'Content-Encoding': 'gzip'}
```
The market information is quite lengthy, and I felt as if it was not necessary to put. However, keep in mind that the currencies stop at 100. Small bug, but it would be great if we can load up all 2000+ currencies.

Thanks.

**Comment by karlandoh** [comment]
Not sure what the like means, I guess you've acknowledged. By next month ccxt will not support coinmarketcap. Unsure whether you will remove support or not. Any verbal update would be appreciated.

**Comment by kroitor** [comment]
@karlandoh we will add support for their new API version asap.

**Comment by nifflerco** [comment]
We really dislike the fact that free trier is for personal use only. We do not need many calls. Like 24 calls per day or so. Would love to see some other alternatives to be implemented.

**Comment by TechupBusiness** [comment]
@kroitor There is a very interesting new API out there: https://coinpaprika.com/api/

See https://medium.com/coinpaprika/coinpaprika-release-upgraded-api-e71cb69536a2

**Comment by karlandoh** [comment]
> @kroitor There is a very interesting new API out there: https://coinpaprika.com/api/
> 
> See https://medium.com/coinpaprika/coinpaprika-release-upgraded-api-e71cb69536a2

I think you struck gold on this one. I will be using this quite a bit!

**Comment by nifflerco** [comment]
> @kroitor There is a very interesting new API out there: https://coinpaprika.com/api/
> 
> See https://medium.com/coinpaprika/coinpaprika-release-upgraded-api-e71cb69536a2

Would love to see this implemented in ccxt

**Comment by robegamesios** [comment]
thanks for the coinpaprika api info!

**Comment by kroitor** [comment]
Continued here: https://github.com/ccxt/ccxt/issues/6580
