### ISSUE TITLE
New version ccxt install with errors (Windows 7 SP1)

### ISSUE THREAD

**Issue by gokuflashdev** [ccxt/ccxt#3901]
- OS: windows 7 sp1
node v8.11.4 
npm v5.6.0
python 2.7.15 and 3.7.0
- CCXT version: 1.17.350 

I try to update old ccxt library. I had a problem with node-gyp so i do Option 1 from site 

> https://github.com/nodejs/node-gyp#on-windows
`npm install --global --production windows-build-tools`
and install node-gyp 

After that I try to install ccxt and i get the error:

> G:\Windows\system32>npm install -g ccxt
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Suppor
t
npm WARN deprecated tar.gz@1.0.7: ??  WARNING ?? tar.gz module has been deprecat
ed and your application is vulnerable. Please use tar module instead: https://np
mjs.com/tar

> scrypt@6.0.3 preinstall G:\Users\goku\AppData\Roaming\npm\node_modules\ccxt\no
de_modules\scrypt
> node node-scrypt-preinstall.js

> keccak@1.4.0 install G:\Users\goku\AppData\Roaming\npm\node_modules\ccxt\node_
modules\keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementat
ion will be used."

> keccak@1.4.0 rebuild G:\Users\goku\AppData\Roaming\npm\node_modules\ccxt\node_
modules\keccak
> node-gyp rebuild

>G:\Users\goku\AppData\Roaming\npm\node_modules\ccxt\node_modules\keccak>if not d
efined npm_config_node_gyp (node "G:\Program Files\nodejs\node_modules\npm\node_
modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js"
 rebuild )  else (node "G:\Program Files\nodejs\node_modules\npm\node_modules\no
de-gyp\bin\node-gyp.js" rebuild )
Projekty w tym rozwiązaniu są tworzone po kolei. Aby umożliwić tworzenie równole
głe, dodaj przełącznik "/m".
**G:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\V
CTargets\Microsoft.CppCommon.targets(423,5): error MSB6006: Polecenie "CL.exe"
zakończone przez kod -1073741515. [G:\Users\goku\AppData\Roaming\npm\node_modul
es\ccxt\node_modules\keccak\build\keccak.vcxproj]**
gyp ERR! build error
gyp ERR! stack Error: `G:\Program Files (x86)\Microsoft Visual Studio\2017\Build
Tools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (G:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "G:\\Program Files\\nodejs\\node.exe" "G:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd G:\Users\goku\AppData\Roaming\npm\node_modules\ccxt\node_modules\ke
ccak
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     G:\Users\goku\AppData\Roaming\npm-cache\_logs\2018-09-25T12_57_50_1
31Z-debug.log
"Keccak bindings compilation fail. Pure JS implementation will be used."

> scrypt@6.0.3 install G:\Users\goku\AppData\Roaming\npm\node_modules\ccxt\node_
modules\scrypt
> node-gyp rebuild

>G:\Users\goku\AppData\Roaming\npm\node_modules\ccxt\node_modules\scrypt>if not d
efined npm_config_node_gyp (node "G:\Program Files\nodejs\node_modules\npm\node_
modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js"
 rebuild )  else (node "G:\Program Files\nodejs\node_modules\npm\node_modules\no
de-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
G:\Users\goku\AppData\Roaming\npm\node_modules\ccxt\node_modules\scrypt\build\..
\scrypt\win\include\config.h
Projekty w tym rozwiązaniu są tworzone po kolei. Aby umożliwić tworzenie równole
głe, dodaj przełącznik "/m".
  Copying scrypt/win/include/config.h to scrypt/scrypt-1.2.0/config.h
  Nie można odnaleźć określonego pliku.
G:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\V
CTargets\Microsoft.CppCommon.targets(423,5): error MSB6006: Polecenie "CL.exe"
zakończone przez kod -1073741515. [G:\Users\goku\AppData\Roaming\npm\node_modul
es\ccxt\node_modules\scrypt\build\copied_files.vcxproj]
G:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\V
CTargets\Microsoft.CppCommon.targets(423,5): error MSB6006: Polecenie "CL.exe"
zakończone przez kod -1073741515. [G:\Users\goku\AppData\Roaming\npm\node_modul
es\ccxt\node_modules\scrypt\build\scrypt_wrapper.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `G:\Program Files (x86)\Microsoft Visual Studio\2017\Build
Tools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (G:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "G:\\Program Files\\nodejs\\node.exe" "G:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd G:\Users\goku\AppData\Roaming\npm\node_modules\ccxt\node_modules\sc
rypt
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

>npm ERR! A complete log of this run can be found in:
npm ERR!     G:\Users\goku\AppData\Roaming\npm-cache\_logs\2018-09-25T12_57_55_6
78Z-debug.log

If i write in cmd:

>G:\Windows\system32>node -v
v8.11.4

>G:\Windows\system32>node-gyp -v

>G:\Windows\system32>if not defined npm_config_node_gyp (node "G:\Program Files\n
odejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modul
es\node-gyp\bin\node-gyp.js" -v )  else (node "" -v )
module.js:549
    throw err;
    ^

>Error: Cannot find module 'G:\Program Files\nodejs\node_modules\npm\node_modules
\node_modules\node-gyp\bin\node-gyp.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

I have installed:
 .Net 2.0 SDK,
 .Net 4.7.2,
Visual C++ 2005, 2008, 2013, 2017 redistributable,
Visual studio Build Tools 2017

What can i do with this problem, old ccxt works fine.

**Comment by kroitor** [comment]
> What can i do with this problem, old ccxt works fine.

This is the requirement of web3, we can't avoid it, unfortunately...
What's the "old" version number? Also, have you tried the second option with installing MSVC Build Tools 17 manually? Also, you said you have Visual studio Build Tools 2017 installed, that should come with a bat file for windows, and you should launch that bat file that would set up necessary environment variables for you – can you locate that bat file and try installing ccxt from within that running bat cmd shell?

**Comment by gokuflashdev** [comment]
hmm directly in path ..\Microsoft Visual Studio\2017\BuildTools are not any bat files. But if i try to find *.bat i get 22 bat files like:
cmake,
dotnet,
launchDevCmd,
msbuild,
netfxsdk,
parse_cmd,
roslyn,
Squish4RunTestCase,
SquishRunTestCase,
testwindow,
vcvars,
vcvars32,
vcvars64,
vcvars140,
vcvarsall,
vcvarsamd64_x86,
vsdevcmd,
vsdevcmd_end,
vsdevcmd_start,
VsMSBuildCmd,
winsdk

U think about some specific bat? 
I install windows_build_tools without --globaly to see the files like this:

> D:\testVSBuildTools>npm install --production windows-build-tools

> windows-build-tools@5.0.0 postinstall D:\testVSBuildTools\node_modules\windows
-build-tools
> node ./dist/index.js



Downloading vs_BuildTools.exe
[>                                            ] 0.0% (0 B/s)
Downloaded vs_BuildTools.exe. Saved to G:\Users\goku\.windows-build-tools\vs_Bui
ldTools.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
Successfully installed Visual Studio Build Tools.
------------------- Python --------------------
Python 2.7.15 is already installed, not installing again.

Now configuring the Visual Studio Build Tools..

All done!

npm WARN saveError ENOENT: no such file or directory, open 'D:\testVSBuildTools\
package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.

npm WARN enoent ENOENT: no such file or directory, open 'D:\testVSBuildTools\pac
kage.json'
npm WARN testVSBuildTools No description
npm WARN testVSBuildTools No repository field.
npm WARN testVSBuildTools No README data
npm WARN testVSBuildTools No license field.

+ windows-build-tools@5.0.0
added 144 packages in 22.126s

D:\testVSBuildTools>

And i get file package-lock.json and directory calld: node_modules. But there is any *.bat files. 

I dont tried the second option :/ I try it now and give feedback how it works :)

**Comment by gokuflashdev** [comment]
Ok i used option two its mean:
in visual studio installer i pick install  for Visual Studio 2017 Community in this community i pick (I have other language in vs installer so i try to translate) "programming classic applications in C++ language" 

there is components like:
Debugger just in time,
VC++ 2017 v4.15
profiling tools for C++,
Windows 10 SDK
Visual C++ Tools for CMake
ATL libbrary for Visual C++
Tests adapters...

I install and set in npm config python 2.7
I Launch cmd, npm config set msvs_version 2017
I type:

> D:\testVSBuildTools>npm install -g node-gyp
G:\Users\goku\AppData\Roaming\npm\node-gyp -> G:\Users\goku\AppData\Roaming\npm\
node_modules\node-gyp\bin\node-gyp.js
+ node-gyp@3.8.0
updated 1 package in 6.052s

> D:\testVSBuildTools>

And if i type node-gyp -v i get:

> D:\testVSBuildTools>node-gyp -v

> D:\testVSBuildTools>if not defined npm_config_node_gyp (node "G:\Program Files\n
odejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modul
es\node-gyp\bin\node-gyp.js" -v )  else (node "" -v )
module.js:549
    throw err;
    ^

> Error: Cannot find module 'G:\Program Files\nodejs\node_modules\npm\node_modules
\node_modules\node-gyp\bin\node-gyp.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

> D:\testVSBuildTools>

I dont define some config file? 
If i type
> npm install -g web3 --unsafe-perm=true --allow-root
i get the same error :/ 

> D:\testVSBuildTools>npm install -g web3 --unsafe-perm=true --allow-root
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Suppor
t
npm WARN deprecated tar.gz@1.0.7: ??  WARNING ?? tar.gz module has been deprecat
ed and your application is vulnerable. Please use tar module instead: https://np
mjs.com/tar

> scrypt@6.0.3 preinstall G:\Users\goku\AppData\Roaming\npm\node_modules\web3\no
de_modules\scrypt
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install G:\Users\goku\AppData\Roaming\npm\node_modules\web3\node_
modules\scrypt
> node-gyp rebuild


> G:\Users\goku\AppData\Roaming\npm\node_modules\web3\node_modules\scrypt>if not d
efined npm_config_node_gyp (node "G:\Program Files\nodejs\node_modules\npm\node_
modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js"
 rebuild )  else (node "G:\Program Files\nodejs\node_modules\npm\node_modules\no
de-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
G:\Users\goku\AppData\Roaming\npm\node_modules\web3\node_modules\scrypt\build\..
\scrypt\win\include\config.h
Projekty w tym rozwiązaniu są tworzone po kolei. Aby umożliwić tworzenie równole
głe, dodaj przełącznik "/m".
  Copying scrypt/win/include/config.h to scrypt/scrypt-1.2.0/config.h
  Nie można odnaleźć określonego pliku.
G:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\V
CTargets\Microsoft.CppCommon.targets(423,5): error MSB6006: Polecenie "CL.exe"
zakończone przez kod -1073741515. [G:\Users\goku\AppData\Roaming\npm\node_modul
es\web3\node_modules\scrypt\build\copied_files.vcxproj]
G:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\V
CTargets\Microsoft.CppCommon.targets(423,5): error MSB6006: Polecenie "CL.exe"
zakończone przez kod -1073741515. [G:\Users\goku\AppData\Roaming\npm\node_modul
es\web3\node_modules\scrypt\build\scrypt_wrapper.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `G:\Program Files (x86)\Microsoft Visual Studio\2017\Build
Tools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (G:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "G:\\Program Files\\nodejs\\node.exe" "G:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd G:\Users\goku\AppData\Roaming\npm\node_modules\web3\node_modules\sc
rypt
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

> npm ERR! A complete log of this run can be found in:
npm ERR!     G:\Users\goku\AppData\Roaming\npm-cache\_logs\2018-09-26T12_20_31_0
48Z-debug.log

damn it:/

**Comment by gokuflashdev** [comment]
First of all i hadto uninstall node with node-gyp, next I install node with node-gyp again and then finnally when i type node-gyp -v i get version: 3.8.0

I find this file and do this:
>PS G:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build> .\vcvarsall.bat
[ERROR:vcvarsall.bat] Error in script usage. The correct usage is:
Syntax:
    vcvarsall.bat [arch] [platform_type] [winsdk_version] [-vcvars_ver=vc_version]
where :
    [arch]: x86 | amd64 | x86_amd64 | x86_arm | x86_arm64 | amd64_x86 | amd64_arm | amd64_arm64
    [platform_type]: {empty} | store | uwp
    [winsdk_version] : full Windows 10 SDK number (e.g. 10.0.10240.0) or "8.1" to use the Windows 8.1 SDK.
    [vc_version] : {none} for default VS 2017 VC++ compiler toolset |
                   "14.0" for VC++ 2015 Compiler Toolset |
                   "14.1x" for the latest 14.1x.yyyyy toolset installed (e.g. "14.11") |
                   "14.1x.yyyyy" for a specific full version number (e.g. 14.11.25503)

>The store parameter sets environment variables to support Universal Windows Platform application
development and is an alias for 'uwp'.

>For example:
    vcvarsall.bat x86_amd64
    vcvarsall.bat x86_amd64 10.0.10240.0
    vcvarsall.bat x86_arm uwp 10.0.10240.0
    vcvarsall.bat x86_arm onecore 10.0.10240.0 -vcvars_ver=14.0
    vcvarsall.bat x64 8.1
    vcvarsall.bat x64 store 8.1

>Please make sure either Visual Studio or C++ Build SKU is installed.

So I type this:
>PS G:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build> .\vcvarsall.bat x86
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
>[vcvarsall.bat] Environment initialized for: 'x86'

After that I try to install ccxt and get this same error:/

>G:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(423
,5): error MSB6006: Polecenie "CL.exe" zakończone przez kod -1073741515. [G:\Program Files (x86)\Microsoft Visual Studi
o\2017\BuildTools\VC\Auxiliary\Build\node_modules\scrypt\build\copied_files.vcxproj]
G:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(423
,5): error MSB6006: Polecenie "CL.exe" zakończone przez kod -1073741515. [G:\Program Files (x86)\Microsoft Visual Studi
o\2017\BuildTools\VC\Auxiliary\Build\node_modules\scrypt\build\scrypt_wrapper.vcxproj]

**Comment by kroitor** [comment]
@gokuflashdev 

> After that I just stay in same folder and cmd (powershell as an administrator) and try to install ccxt but I get this same error:/

I actually said that you should be in the same window, but you **should go to a working dir or to a temporary folder**, instead you stayed in the same folder... You should pay more attention, because you seem to be in a kind of a hurry and don't focus on what is written above in the output and... it actually has a lot of clues that you're missing.

> I find this file (vcvarsall.bat) and do this:
> PS G:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build> .\vcvarsall.bat

This is correct. However, the rest of the actions are not.

First, note to this:

> [winsdk_version] : full Windows 10 SDK number (e.g. 10.0.10240.0) or "8.1" to use the Windows 8.1 SDK.

So, it means that you have to have either of the above two SDKs (10 or 8). If you don't have it, you should install it. But don't do this yet, read this to the end first.

Next, you should know whether your system is x86 or amd64 architecture (it is 64 bit most likely):

> [arch]: x86 | amd64 | x86_amd64 | x86_arm | x86_arm64 | amd64_x86 | amd64_arm

So, you might want to choose a different architecture here.

Also, note this:

> [vc_version] : {none} for default VS 2017 VC++ compiler toolset |
> "14.0" for VC++ 2015 Compiler Toolset |
> "14.1x" for the latest 14.1x.yyyyy toolset installed (e.g. "14.11") |
> "14.1x.yyyyy" for a specific full version number (e.g. 14.11.25503)

You should use a different vc_version if you're on Windows7+VC2015 instead of 2017.

Then, you say:

> There is just something wrong maybe with this visual studio:
> G:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build
> node install --msvs_version=2017
> module.js:550
> throw err;

The reason for this is because you did a typo in the command. There's **`npm config -g set msvs_version 2015`**. There's no such command as `node install`, and this is exactly what your system is telling you:

> Error: Cannot find module 'G:\Program Files (x86)\Microsoft Visual Studio\2017\C
ommunity\VC\Auxiliary\Build\install'

↑ The `node` launched by `node install` cannot find `install.js` file or `install` module to execute. Because this is a wrong command in the first place. You used node instead of npm here with wrong keys. 

--------------------------------------------------------

Anyways, let's not retry the actions taken previously, instead, you should be able to resolve this whole issue quickly if you follow **very precisely** through this solution (make sure to avoid typos and read each line of text very carefully):

- https://github.com/nodejs/node-gyp/issues/802

Let us know if that does not help. Closing this for now, if you don't mind, as seems to be a machine-specific issue with your particular setup. Feel free to reopen it if needed or just ask further questions, if any.

**Comment by gokuflashdev** [comment]
Its impossible to follow very precisely after this issue. There is not available any of VS 2015 include Technical Preview. All of links to VS2015 (including this ones from TEAM BLOG) try to install VS community 2017. VS community 2017 have to be install with Windows SDK 10.0

IDK that it should work with community 2017 and windows SDK 10. I install one more time community 2017 with C++/CLI  component (7.16 GB to download) and write what is the effect.

**Comment by gokuflashdev** [comment]
Ok I finnaly resole this issue. .NET framework 4.5.1 is too old and .NET framework 4.7.2 is "too new"... 
When I uninstall .net 4.7.2 and install .net 4.6.0 and going to a separate folder to install in empty folder ccxt, its end successfull on visual studio community 2017. 
Now I have the same problem with scrypt but scrypt need windows sdk 7.1 and visualStudio 2010 so... Get some melisa, nervosol, nervomix or relanium and go to work...

**Comment by kroitor** [comment]
@gokuflashdev Thx for reporting back! We got some good news for you as well... We're actually going to make most of those dependencies optional shortly... More about it here: https://github.com/ccxt/ccxt/issues/3921

**Comment by munrocket** [comment]
This happens because web3 have an one outdated dependency https://github.com/ethereum/web3.js/issues/1908

**Comment by munrocket** [comment]
Node-gyp is outdated and works only with Python 2.

**Comment by munrocket** [comment]
If you still have a problem with ccxt installation, try googling "node-gyp windows install"

**Comment by gokuflashdev** [comment]
Now I fight with scrypt who also use node-gyp. It`s some dependency for ccxt or web3:>

**Comment by kroitor** [comment]
@gokuflashdev if you're not using DEXes, then you can just `pip install ccxt` from... The most recent version of it does not require web3 (it's optional, required for DEXes only).

**Comment by gokuflashdev** [comment]
But this is python module so if I install ccxt like this I have to use some node module to allow me to communicate with python library, something like python.node?

**Comment by kroitor** [comment]
> But this is python module so if I install ccxt like this I have to use some node module to allow me to communicate with python library, something like python.node?

@gokuflashdev nope, I mean, `npm install ccxt` in your case, of course... We ship 3 flavors of it, python, php and javascript, all of them are independent of each other. So, no, you don't have to install any python software if you're using npm, node and javascript.

**Comment by gokuflashdev** [comment]
U mean 1.17.365 version? 
But this version have support for TheOcean and this exchange is Decentralized Exchange (DEX) am I right?

**Comment by kroitor** [comment]
I mean the current, 1.17.369 or higher. However, if you want DEXes, then you will still need web3, so there's no workaround for that, unfortunately.

**Comment by gokuflashdev** [comment]
On ubuntu works fine ccxt will install without errors. But on windows I get errors :>

>G:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VC
Targets\Microsoft.CppCommon.targets(423,5): error MSB6006: Polecenie "CL.exe" z
akończone przez kod -1073741701. [G:\node_modules\keccak\build\keccak.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1

IDK why 3 days ago I installed it but its not work anyway cos was problem with scrypt:>
