### ISSUE TITLE
ccxt install fail due to lru-dict library

### ISSUE THREAD

**Issue by MarcelBeining** [ccxt/ccxt#3902]
- OS: Windows 10 64bit
- Programming Language version: Python 3.6.4
- CCXT version: 1.17.350
- Exchange: -
- Method: -

Hi,
when trying to install the new ccxt version on Windows, I ran into huge problems (previous version had worked), because the new library lru-dict is built during install, which failed because the compiler cl.exe was missing. This made it necessary to install Microsoft's 5 GB large Visual Studio environment and run pip with their command prompt. Is there any possible for you to come around the lru-dict or that you have to build it during install?

**Comment by kroitor** [comment]
> Is there any possible for you to come around the lru-dict or that you have to build it during install?

It is required by the web3 imports, so we can't cut it out easily, therefore it is required. But anyways, we'll consider adding a workaround soon. Hope this answers your question, let us know if not.
