### ISSUE TITLE
Bitfinex BTCUSD KeyError

### ISSUE THREAD

**Issue by p0nt** [ccxt/ccxt#3903]
I seem to be getting a KeyError on the python side of ccxt every time I try to create a BTCUSD trade ...

I have tried the following strings as symbol:

- BTCUSD
- BTC/USD
- tBTCUSD
- tbtcusd
- btcusd

None of the above work...

tried the following:

create_market_buy_order('BTCUSD', 0.1, {'type': 'market'})

Can anybody tell me the proper command to buy on the BTCUSD symbol on margin?

**Comment by kroitor** [comment]
@p0nt 

> I have tried the following strings as symbol:

> BTCUSD
> BTC/USD
> tBTCUSD
> tbtcusd
> btcusd

> tried the following:
> create_market_buy_order('BTCUSD', 0.1, {'type': 'market'})

Please, read the following carefully:

- https://github.com/ccxt/ccxt/issues/2851
- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

```

id              symbol          base            quote
...
BNTUSD          BNT/USDT        BNT             USDT
BOXETH          BOX/ETH         BOX             ETH
BOXUSD          BOX/USDT        BOX             USDT
BTCEUR          BTC/EUR         BTC             EUR
BTCGBP          BTC/GBP         BTC             GBP
BTCJPY          BTC/JPY         BTC             JPY
BTCUSD          BTC/USDT        BTC             USDT ←---------------- symbol = BTC/USDT
...
```

Let us know if that does not answer your question.

**Comment by p0nt** [comment]
Thank you very much!
