### ISSUE TITLE
Create Order - price exceeds allowed price precision or invalid - Binance

### ISSUE THREAD

**Issue by itsmemittal** [ccxt/ccxt#3906]
OS: Windows
Programming Language version: Js
Exchange: binance

Hi,
I am trying to create a Limit buy order on binance for 
symbol : HOT/ETH
price: 0.00054

When placing this order on Binance giving me the following response.

Binance order price exceeds allowed price precision or invalid, use this.priceToPrecision (symbol, amount) {\"code\":-1013,\"msg\":\"Filter failure: PRICE_FILTER\"} { exchange: 'binance' }

**Comment by kroitor** [comment]
Hi! What’s your version of CCXT? Have you tried with the most recent version? Also, can you post your code to reproduce it? Need your *code* and *verbose request/response*. 

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/Manual#market-structure
https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

![screen-shot-2018-09-27-at-20 24 25](https://user-images.githubusercontent.com/1294454/46163362-ad672800-c293-11e8-8378-61197d8b5ffa.jpg)

For `HOT/ETH` min price is 0.00000046, max price is 0.0000458. Your value of 0.00054 is way beyond max price for that symbol.

**Comment by itsmemittal** [comment]
Thank you it helps me.
Would you please answer me on the following query?

I am trying to place the withdraw order for ETH of amount 0.2686212057254691277485705514
and getting following error.
"Place withdraw from Gdax to any other exchange with the amount as more than 8 digits after the decimal."

I found withdraw code implementation and there we using parseFloat for the amount. Hence whatever amount we are passing that amount sending to exchange and causing the error.
In case "create order" CCXT using priceToPrecision then why CCXT not considering price precision for withdrawing.

**Comment by kroitor** [comment]
> In case "create order" CCXT using priceToPrecision to restrict precision length. then why CCXT not considering price precision length for withdrawing as the exchange has that restriction.

Sure, withdraw methods should also follow precision rules, the reason here is that withdraw methods and funding precision is still a work in progress, as you may know this library is still under development. We will unify that aspect with withdraw as well, hopefully very soon.
