### ISSUE TITLE
bitmex No market symbol XBTUSD

### ISSUE THREAD

**Issue by terrorizers** [ccxt/ccxt#3914]
- OS: ubuntu
- Programming Language version: python3
- CCXT version: 1.17.356
- Exchange: bitmex
- Method: create order

https://github.com/ccxt/ccxt/blob/master/examples/py/bitmex-create-order.py I'm just trying to using that one, I dont get how to set if testnet api or not, (so first question is how to do so?), but the problem I get is:

```
Traceback (most recent call last):
  File "bitmex-create-order.py", line 28, in <module>
    order = exchange.create_order(symbol, type, side, amount, price, params)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/bitmex.py", line 474, in create_order
    'symbol': self.market_id(symbol),
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 1481, in market_id
    market = self.market(symbol)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 1475, in market
    self.raise_error(ExchangeError, details='No market symbol ' + str(symbol))
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 344, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeError: bitmex No market symbol XBTUSD
```
why is this? (I use 'XBTUSD' as symbol with testnet or normal keys is same result)

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

**Comment by terrorizers** [comment]
thanks now it works in real mode! :D

how can I use in testnet? (feedback: in the error maybe you could link that one, I was like 100% symbols were the ones used by bitmex, but actually it's better like so)

**Comment by kroitor** [comment]
> how can I use in testnet?

Like so: https://github.com/ccxt/ccxt/issues/2096#issuecomment-370186689

**Comment by terrorizers** [comment]
wow thanks a lot you are awesome! super fast and perfect answers!
