### ISSUE TITLE
can't install ccxt MacOs

### ISSUE THREAD

**Issue by zizou86** [ccxt/ccxt#3917]
- OS: MacOs High Sierra 10.13.6
- Programming Language version: node v8.12.0, npm v6.4.1
- CCXT version:
- Exchange:
- Method:

Please, i need your help.
I try to install ccxt but i have an issue about scrypt

> npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar

> scrypt@6.0.3 preinstall /Applications/MAMP/htdocs/twirexTests/node_modules/scrypt
> node node-scrypt-preinstall.js

> scrypt@6.0.3 install /Applications/MAMP/htdocs/twirexTests/node_modules/scrypt
> node-gyp rebuild

  SOLINK_MODULE(target) Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  LIBTOOL-STATIC Release/scrypt_wrapper.a
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/scrypt_wrapper.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Applications/MAMP/htdocs/twirexTests/node_modules/scrypt
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN twirextests@1.0.0 No description

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by zizou86** [comment]
i noticed that path not exist 
> scrypt@6.0.3 install /Applications/MAMP/htdocs/twirexTests/node_modules/scrypt

i find /Applications/MAMP/htdocs/twirexTests/node_modules/scryptsy

**Comment by kroitor** [comment]
@zizou86 Have you tried any options that come up when googling for *"LIBTOOL-STATIC Release/scrypt_wrapper.a* ? Does any of the following solutions resolve the issue for you?

- https://github.com/barrysteyn/node-scrypt/issues/113 
- https://github.com/barrysteyn/node-scrypt/issues/83
