### ISSUE TITLE
No market symbol XBTUSD

### ISSUE THREAD

**Issue by Kalltech** [ccxt/ccxt#3920]
- OS:Linux
- Programming Language version:Python 2.7
- CCXT version: exchange.py '1.17.132'
- Exchange:bitmex
- Method:create_order
Hi,
I'm sure it's something I'm doing wrong but I tried a lot of things
order = exchange.create_order("XBTUSD", type, side, amount, price, params)
I got the error: bitmex No market symbol XBTUSD
I tried with another API and it works.
Someboby can help me?
Thanks

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/issues/3914
- https://github.com/ccxt/ccxt/issues?utf8=%E2%9C%93&q=No+market+symbol+XBTUSD
- https://github.com/ccxt/ccxt/search?q=No+market+symbol+XBTUSD&type=Issues
