### ISSUE TITLE
Heaviest object in the universe?

### ISSUE THREAD

**Issue by munrocket** [ccxt/ccxt#3921]
CCXT bundle become ridiculusly heavy. It's bigger than angular+react+vue+ember combined in 2 times!

> This library is shipped as an all-in-one module implementation with minimalistic dependencies and requirements:

I suggest deleting these lines from wiki. Also to split library in two parts one for centralized exchanges without web3/ethereumjs and another for decentralized exchanges like babel-core and babel-stuff. It's clear that we need modularity and save minimalistic design. Main target audience of this library use it in smartphones and python arbitrage bots and both need to be fast.

As i already say it will be cool to support website for custom bundle compilation like in [highlight.js](https://highlightjs.org/) or at least better promote this approach in documentation. Since you have 'ccxt certified' exchange it can be the case for 'certified' bundle.

![](https://habrastorage.org/webt/ib/yb/be/ibybberflkdvp1xjaha01zgvkts.png)

**Comment by AoDev** [comment]
@munrocket I have a partial solution for my own project. It is a Webpack loader and thus works only if you use JS / Webpack. In my case, I managed to reduce ccxt weight to 15% of its original weight. (it depends on what you load)

https://github.com/Cryptovista/ccxt-exchanges-loader

**Comment by munrocket** [comment]
@AoDev Yep we already implemented [custom bundle](https://github.com/ccxt/ccxt/blob/dfc5d3b7b914a30bd8bbcd075ba278ab09616be2/exchanges.cfg) compiler in official repository. But I think it's become more serious problem and just shrink number of stock exchanges not helps now. Sometimes we need to get rid of heavy dependencies.

**Comment by kroitor** [comment]
We will make most of those heavy dependencies optional very soon.

**Comment by AoDev** [comment]
One thing I noted is that in my app, and probably other people as well, I share some dependencies with ccxt. 

`bignumber.js, web3, crypto-js` 

But the dependencies in ccxt are locked. So it means that for most people, these libraries (dependencies) will be duplicated. You could consider using semver ranges if possible. I know locking deps is more robust but usually it's recommended to do that at app level.
