### ISSUE TITLE
 New Exchange - Coin Asset Exchange

### ISSUE THREAD

**Issue by KeeZEE** [ccxt/ccxt#3926]
Please support to add Coin Asset Exchange. We're exchange with operations in Bangkok, Thailand.

Website: https://coinasset.co.th/
API Doc: https://coinasset.co.th/api

Thanks you :)

**Comment by An-Net** [comment]
It's dead:

- https://news.bitcoin.com/thai-cryptocurrency-exchange-sec-orders-shutdown/

- https://twitter.com/CoinAssetX/status/1085557824246042624

![Снимок экрана 2020-07-22 в 16 14 06](https://user-images.githubusercontent.com/51840849/88180705-72876e80-cc36-11ea-8ea3-4d60254f796c.png)
