### ISSUE TITLE
cannot get quoinex (liqui) private api working

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#3927]
Hi

Using version _1.17.363_ I'm unable to get my balances from quoinex.  Can someone confirm that the current implementation is working?  Maybe I have done something wrong.

The error is get is ` {"success":0,"code":0,"error":"invalid api key"}`.  I've tried the same api key in my personal project and it does work.  I then looked at the ccxt code and it looks quite different to mine which implements jwt (see below).

The ccxt code make no mention of jwt, even the signing algo is different (sha512 instead of SHA-256).  

```
    sign (path, api = 'public', method = 'GET', params = {}, headers = undefined, body = undefined) {
...
            let nonce = this.nonce ();
            body = this.urlencode (this.extend ({
                'nonce': nonce,
                'method': path,
            }, query));

            let signature = this.signBodyWithSecret (body);
            headers = {
                'Content-Type': 'application/x-www-form-urlencoded',
                'Key': this.apiKey,
                'Sign': signature,
            };
...
    }

    signBodyWithSecret (body) {
        return this.hmac (this.encode (body), this.encode (this.secret), 'sha512');
    }

```

My code:

```
        const nonce = this.millisSecondTime();
        const jwtClaimSet = {
            path: path,
            token_id: this.apiKey,
            nonce: nonce.toString()
        };

        const jwtHeader = JSON.stringify({alg: 'HS256'});
        const payload = btoa(jwtHeader) + '.' + btoa(JSON.stringify(jwtClaimSet));
        const signed = await this.sign(payload);// just delegates to a SHA-256 / base-64 signer 

        const jwt = payload + '.' + BaseExchange.webSafe64(signed);

        const headers = {
            "X-Quoine-Auth": jwt,
            "X-Quoine-API-Version": 2,
            "Content-Type": "application/json"
        };

        const body = params ? JSON.stringify(params) : null;

        const httpData = await this.httpExecutor.execute2(`${this._baseUri}${path}`, method, headers, body);
```

**Comment by kroitor** [comment]
Hi! They moved to liquid.com... you're a bit late ) 

- https://github.com/ccxt/ccxt/pull/3876
- https://github.com/ccxt/ccxt/issues/3809

The exchange can drop all old keys or just turn off old domains and api servers, can change signing procedures if they want to switch to a different engine or whatever, you should at least be grateful to them for not dropping all accounts and all your funds, lol )) 

But in this particular case, they actually haven't changed their signing procedure, they renamed the exchange and moved it to a new domain. 

Hope that answers your question. Why do you hate the search, btw? ;)

**Comment by npomfret** [comment]
Hey, thanks @kroitor.  I did search but I didn't see what I was looking for.  The present of the quoinex exchange confused me. It's doesn't work at all it seems, I wonder if there's any reason to keep it around? 

Perhaps we could at least comment out of date exchanges.  It's not always obvious which to use.

**Comment by kroitor** [comment]
>  I wonder if there's any reason to keep it around?

You're right, no reason to keep them, will drop them in one of the upcoming releases. Thx!
