### ISSUE TITLE
contributing issues with tox

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#3932]
I'm having some trouble running `npm run build`, speficially with the python stuff.  The guide says i need to have _Python 3.5.3+ and Python 2.7+_.  I think OS X has 2.7 pre-installed, and I manually downloaded and installed the latest version from the link supplied:

```
$ python --version
Python 2.7.10
$ which python
/usr/bin/python

$ python3.7 --version
Python 3.7.0
$ which python3.7
/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7
```
 
Running the build I get an error about `tox` being missing (`sh: tox: command not found
`). 

Are there some additional steps I need to perform to get the build running on a mac?  I've never used python before, I don't know what _tox_ is, and I'm not sure what's a sensible way of getting these executables in my path.  I would have assumed the installer would have done this job.  

Python 3.7 does come with a script called `/Applications/Python\ 3.7/Update\ Shell\ Profile.command` which is supposed to do the job, but it doesn't work - at least it didn't for me.  It adds the new python installation to the front of my path but _tox_ still isn't present.

I ended up installed tox manually using `brew install tox`, which seemed to work.  Maybe this could be clarified in the instructions.

**Comment by lacksfish** [comment]
I got it working by running the following command in the docker:

`sudo -H pip3 install --upgrade setuptools pip wheel requests pyopenssl six tox twine setuptools web3 aiohttp requests cryptography pyopenssl`

**Comment by kroitor** [comment]
@lacksfish thx so much for the followup!
