### ISSUE TITLE
Getting more than one pair using the Order Book method

### ISSUE THREAD

**Issue by mrHaiker** [ccxt/ccxt#3933]
I need to get more that one currency pair, and for that I shoud send:
Array of pairs for EXMO: `https://api.exmo.com/v1/order_book/?pair=${pairs}`
Key 'all' for Poloniex: `https://poloniex.com/public?command=returnOrderBook&currencyPair=all`
etc.
But I can't do that by provided methods

- OS: Windows 10
- Programming Language version: JavaScript
- CCXT version: 1.15.38
- Exchange: all
- Method: fetchOrderBook

**Comment by kroitor** [comment]
> But I can't do that by provided methods

Why not? Use implicit methods + unified param overrides:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

Let us know if that does not answer your question.

**Comment by kroitor** [comment]
We have added support for `fetchOrderBooks` to exchanges that have it.
