### ISSUE TITLE
BitMEX privateDeleteOrderAll - fiters seem do not work correclty

### ISSUE THREAD

**Issue by aav80** [ccxt/ccxt#3937]
When I try to use filters in bulk order cancelation, exchange anyway cancels all orders, filter doesn't matter.
Is it ccxt mistake issue?

Code is below. 
All executes correctly, no errors, but cancels all.

```
"use strict";
const ccxt = require ('ccxt')
const BITMEX_API_DATA = require ('a:/API/bitmex_vladimir.js')
let exchange = new ccxt.bitmex ({
	'apiKey': BITMEX_API_DATA.KEY,
	'secret': BITMEX_API_DATA.SECR,
	"nonce": Date.now, 
    enableRateLimit: true 
})
;(async function main () {

	await exchange.privateDeleteOrderAll( 'BTC/USD',  {"side": "Sell" } )
	return
}) ()
```
- OS: Windows 10
- Programming Language version: Node JS v.8.10.0
- CCXT version: 1.10.1 2017-11-06
- Exchange: BitMEX
- Method: privateDeleteOrderAll

**Comment by kroitor** [comment]
> Is it ccxt mistake issue?

Nope, it's yours. You're using an implicit API method `privateDeleteOrderAll` and, according to the Manual, all implicit methods have the same signature and accept just one params argument, so you can't pass `BTC/USD` and `{"side": "Sell"}` to that method. It has to be just one object.

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

Let us know if that does not answer your question.
