### ISSUE TITLE
Bibox function fetch_tickers not working correctly

### ISSUE THREAD

**Issue by mkang1234** [ccxt/ccxt#3938]
- OS: Windows 7
- Programming Language version:  Python 3.6
- CCXT version: 1.17.365
- Exchange: Bibox
- Method: fetch_tickers

fetch_tickers function is not returning ask and bid prices and qty.

**Comment by kroitor** [comment]
Some fields may be missing and this is expected according to the Manual – not all exchanges will return all fields, so we just use what's available. I guess, you should forward this question to developers of Bibox API.
