### ISSUE TITLE
[Livecoin] partially filled and cancelled orders

### ISSUE THREAD

**Issue by giv13** [ccxt/ccxt#3945]
- OS: Windows 8
- Programming Language version: php 7.1
- CCXT version: 1.17.229
- Exchange: Livecoin
- Methods: parse_order_status

Just a question about row `'PARTIALLY_FILLED_AND_CANCELLED' => 'canceled',` in method `parse_order_status`. Is it right to assume that partially filled and cancelled orders are cancelled (not closed)? Livecoin considers these orders closed and I agree with it)

**Comment by kroitor** [comment]
@giv13 In CCXT an order has a `closed` status if it has been filled completely. Otherwise, it will have a status of `canceled` and `filled` >= 0 and `remaining` > 0. Let us know if that doesn't answer the question.
