### ISSUE TITLE
Poloniex returning wrong hardcoded transaction fees

### ISSUE THREAD

**Issue by femelo** [ccxt/ccxt#3946]
- OS: Ubuntu 16.04
- Programming Language version: Python 2.7
- CCXT version: 1.17.368
- Exchange: Poloniex
- Method: load_markets()

Issue:
The code below returns a taker fee of 0.0025 and a maker fee of 0.0015 (they should be 0.002 and 0.001) 

import ccxt
exch = ccxt.poloniex()
exch.load_markets()
market = exch.markets['BTC/USDT']
print market['taker'], market['maker']

Where are these fees hardcoded?
Apparently, in "ccxt/python/ccxt/poloniex.py" line 119, the fees appear to be set correctly as

'fees': {
   'trading': {
       'maker': 0.001,
       'taker': 0.002,
   },
'funding': {},

Did I miss anything?

**Comment by kroitor** [comment]
> The code below returns a taker fee of 0.0025 and a maker fee of 0.0015 (they should be 0.002 and 0.001)

In my case it returns proper values:

```
mbp:ccxt igorkroitor$ python examples/py/cli.py poloniex market BTC/USDT
{'active': True,
 'base': u'BTC',
 'fee_loaded': False,
 'id': u'USDT_BTC',
 'info': {u'baseVolume': u'4111004.65232156',
          u'high24hr': u'6642.00000000',
          u'highestBid': u'6600.00000000',
          u'id': 121,
          u'isFrozen': u'0',
          u'last': u'6600.00000000',
          u'low24hr': u'6455.00000000',
          u'lowestAsk': u'6605.16782695',
          u'percentChange': u'0.02066758',
          u'quoteVolume': u'628.08424215'},
 'limits': {'amount': {'max': None, 'min': 1e-06},
            'cost': {'max': None, 'min': 1.0},
            'price': {'max': None, 'min': 1e-08}},
 'maker': 0.001,
 'percentage': True,
 'precision': {'amount': 6, 'price': 8},
 'quote': u'USDT',
 'symbol': u'BTC/USDT',
 'taker': 0.002}
```

Let's check your actual ccxt version first. What does the code below say?

```Python
import ccxt
print(ccxt.__version__)
```

?

**Comment by femelo** [comment]
It says 1.14.71

**Comment by femelo** [comment]
That is odd. Running exactly the same command as you run, I get:

{'active': True,
 'base': u'BTC',
 'fee_loaded': False,
 'id': u'USDT_BTC',
 'info': {u'baseVolume': u'4105585.15822753',
          u'high24hr': u'6642.00000000',
          u'highestBid': u'6581.03304324',
          u'id': 121,
          u'isFrozen': u'0',
          u'last': u'6581.01652162',
          u'low24hr': u'6455.00000000',
          u'lowestAsk': u'6584.50269749',
          u'percentChange': u'0.01371328',
          u'quoteVolume': u'626.63222578'},
 'limits': {'amount': {'max': 1000000000, 'min': 1e-08},
            'cost': {'max': 1000000000, 'min': 0.0},
            'price': {'max': 1000000000, 'min': 1e-08}},
 'maker': 0.0015,
 'percentage': True,
 'precision': {'amount': 8, 'price': 8},
 'quote': u'USDT',
 'symbol': u'BTC/USDT',
 'taker': 0.0025}

**Comment by femelo** [comment]
I am using Python 2.7.14 :: Anaconda custom (64-bit)

**Comment by femelo** [comment]
It is ok. I see now, I had a ccxt installed via pip. Thank you for your answer. It is solved now

**Comment by kroitor** [comment]
> It is ok. I see now, I had a ccxt installed via pip. Thank you for your answer. It is solved now

Yep, that's a known issue with anaconda python – it has it's own package installer / package management. Thx for reporting back anyways!
