### ISSUE TITLE
Bitsane - Price is required field for market orders

### ISSUE THREAD

**Issue by murcialito** [ccxt/ccxt#3947]
OS: macOS High Sierra
Programming Language version: node 10.1.0
CCXT version: 1.17.367
Exchange: Bitsane
Methods: createOrder

Hi,

I am using bitsane.js to insert new orders in Bitsane exchange. I was facing an issue inserting market orders, error message was "price is a required field".

When I removed the if condition (pasted below) from the createOrder method in bitsane.js in ccxt code it started working, could it be an issue for this specific exchange as it does not makes too much sense to send a price for a market order?

```
if (type !== 'market')
            order['price'] = price;
```

Thanks!

**Comment by kroitor** [comment]
> could it be an issue for this specific exchange as it does not makes too much sense to send a price for a market order?

That if-conditional literally says: *"set price only if type is **not** market"*... Not sure if I get the question...

**Comment by murcialito** [comment]
Sure, but the exchange requires the field even for market orders.

**Comment by kroitor** [comment]
@murcialito oh, I see... We'll fix it then... however, to fix it properly, we need your help with the following quick question: does the actual filling price for that order match the market price indeed after the settlement? In other words, which values do you use for the price of your market orders?

**Comment by kroitor** [comment]
Ok, got it, thx for reporting... will see if they do support market orders at all

**Comment by kroitor** [comment]
This exchange has been shutdown: #5396.
Closing this for now.
