### ISSUE TITLE
Liquid: various fixes

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#3950]
I believe the `fetchMyTrades` method in Liquid could be improved.  It is currently calling the [/executions/me](https://developers.quoine.com/#get-your-executions) endpoint, but this doesn't provide the order id - it's just a list of fills.  

The [/orders](https://developers.quoine.com/#get-orders) call will return the fills for each order in the `executions` element.  Additionally, this call does not force the user to specify a market AND the ccxt `type` field can be determined using the `order_type` element.

**Comment by npomfret** [comment]
Ignore this. The existing api call has the order id - it's just being ignored.  Maybe because it's not documented properly.

**Comment by kroitor** [comment]
> The parseTrade method just needs to use the order_id field.

Would you want to submit a PR for it? Or do you want us to upload it? (asking just to sync the effort properly)

**Comment by npomfret** [comment]
I can do it.  But what about my other PR?  Shall I roll back the changes?  (Don't have the mental  bandwidth to deal with more than one branch right now).

**Comment by kroitor** [comment]
> I can do it.

That's great to hear! ) 

> But what about my other PR? Shall I roll back the changes?

Nope, because this edit is basically a one-liner, I guess it would be easier if you can just push one more commit to the same branch and i'll merge the edits all together in your PR very soon. Thanks so much for the report and for your help, your activity is really appreciated!

**Comment by npomfret** [comment]
https://github.com/ccxt/ccxt/pull/3931/commits/032efcddbc09235f4b66e8179146abc925ec0fa4

**Comment by npomfret** [comment]
Also, the  fee currency in orders is _undefined_.  From my data it looks like the currency is always expressed in the quote currency (example below).  I've checked around 100 of my own orders covering buys, sells, fiat pairs, crypto only pairs, partially and fully executed orders.

eg:

```
{ id: 85044564,
     order_type: 'limit',
     quantity: '1.0',
     disc_quantity: '0.0',
     iceberg_total_quantity: '0.0',
     side: 'buy',
     filled_quantity: '0.85',
     price: 0.07872,
     created_at: 1502117104,
     updated_at: 1502117104,
     status: 'cancelled',
     leverage_level: 1,
     source_exchange: 0,
     product_id: 37,
     product_code: 'CASH',
     funding_currency: 'BTC',
     crypto_account_id: null,
     currency_pair_code: 'ETHBTC',
     average_price: '0.078',
     target: 'spot',
     order_fee: '0.00016575',
     source_action: 'manual',
     unwound_trade_id: null,
     trade_id: null,
     settings: null,
     trailing_stop_type: false,
     trailing_stop_value: false,
     executions: [ [Object] ],
     stop_triggered_time: null } }
```

The [website](https://news.quoinex.com/fees/) says:

> 0.25% (BTC and BCH pairs)

So for this _ETHBTC_ trade I make:
_amountInQuoteCcy_ = 0.85 * 0.078 = 0.0663
_feePercent_ = 100 * (0.00016575 / 0.0663) = **0.25**

**Comment by npomfret** [comment]
https://github.com/npomfret/ccxt/commit/8409cc25b47960b7b9fd897b09c00e630dd3bdab

**Comment by npomfret** [comment]
@kroitor have also added a private get /transactions endpoint.  It's undocumented, but can be used to get deposits and withdrawals... will implement soon
