### ISSUE TITLE
Liqui fetchTickers throws error due to exceeded max URL length

### ISSUE THREAD

**Issue by schuma7** [ccxt/ccxt#3953]
Executing the following code:

```
const exchangeApi = new ccxt.liqui();
await exchangeApi.loadMarkets();
const tickers = await exchangeApi.fetchTickers();
```

throws the following error:

```
Error: liqui has 241 symbols exceeding max URL length, you are required to specify a list of symbols in the first argument to fetchTickers
    at liqui.fetchTickers (/Users/_/git/_/node_modules/ccxt/js/liqui.js:291:23)
    at process._tickCallback (internal/process/next_tick.js:68:7) constructor: [Function: ExchangeError] }
```
- OS: Mac OS 10.13.6
- Programming Language version: Node.js v10.5.0
- CCXT version: 1.17.352
- Exchange: Liqui
- Method: fetchTickers

**Comment by kroitor** [comment]
> Error: liqui has 241 symbols exceeding max URL length, you are required to specify a list of symbols in the first argument to fetchTickers

Yep, this is by design, and to overcome it you need to do what it says... or... which part of that message is not clear to you? %)

**Comment by schuma7** [comment]
I was following the manual and that didn't specify that this method takes any parameters, so I assumed it's an internal library error.

Since other methods such as loadMarketData also pull in all the information at once, I assumed that the library takes care of the data loading for fetchTickers as well. It might help to emphasise this behaviour in the manual.
