### ISSUE TITLE
BitMex fetch_trades giving old trades?

### ISSUE THREAD

**Issue by allback122** [ccxt/ccxt#3955]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

Hello! I'm tryin to use CCXT to get a stream of the trades happening on Bitmex every second, i'm using fetch_trades for it but it looks like i'm getting trades from August 28 instead of getting the most recent trades, what can i do to get them in real time? I'm using Python 2.7 on Win10. Thanks in advance!

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki/Manual#pagination
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
