### ISSUE TITLE
How can I use a customized http request function to solve CORS issue for Cordova/Ionic?

### ISSUE THREAD

**Issue by ourarash** [ccxt/ccxt#3956]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: iOS
- Programming Language version: nodejs
- CCXT version:latest
- Exchange: binance
- Method: fetchMyTrades

I'm using Cordova, which allows [native http calls](https://github.com/silkimen/cordova-plugin-advanced-http) that don't have CORS issue. I would like to use this function instead of nodeJS http requests.

Is there any way that I can pass Cordova's http request function to ccxt so that all http requests use that function instead of what ccxt uses by default?

**Comment by ourarash** [comment]
In case somebody else run into this problem, here is the solution that worked for me:

`let exchange = new ccxt["poloniex"]({
      enableRateLimit: true,
      apiKey: options.apiKeySecret.apiKey,
      secret: options.apiKeySecret.secret,
      fetchImplementation:ccxtFetchImplementation //Overloaded function that uses Native http calls
    });
`

And:

`ccxtFetchImplementation(url, options) {

    let headers = options.headers || undefined;

    return new Promise(async (resolve, reject) => {

        //Cordova's native http.get call that doesn't have CORS issue
         cordova.plugin.http.get(url, {}, headers, function (response) {

        //CCXT needs this function to match npm Fetch
        response.text = () => {
          return new Promise((resolve, reject) => {
            resolve(response.data);
          })
        }

        //Use Map to mimic npm Fetch that is used by ccxt
        response.headers = new Map(Object.entries(response.headers));
        response.statusText = response.statusMessage;
        resolve(response);
      }, function (response) {
        console.log('response.error: ', response.error);
        reject(response);
      });
    })
  }`

**Comment by kroitor** [comment]
@ourarash thx for reporting back, appreciate that!
