### ISSUE TITLE
Okex does not have market symbol OCP/BTC

### ISSUE THREAD

**Issue by AadaEa** [ccxt/ccxt#3958]
Hi

- OS: Linux
- Programming Language version: PHP 7
- CCXT version: 1.17.369
- Exchange: Okex

OCP/BTC exists on Okex : https://www.okex.com/market?product=ocp_btc
OCP/BTC is getting successfully fetched by CCXT when using fetchTickers()
OCP is not subject to any name change in CCXT https://github.com/ccxt/ccxt/search?q=ocp&unscoped_q=ocp

OCP/BTC returns an error when trying to get market info like last trades.
Replacing OCP/BTC by a working pair like ETH/BTC, and it works perfectly.
Maybe there's a missing name substitution somewhere.

```
try{
$orderbook = $exchange->fetchOrderBook('OCP/BTC', '50');
}
catch (\ccxt\BaseError $err){
echo $err;
$err = str_replace("'", "\'", $err);
}
// Prints ExchangeError: okex does not have market symbol OCP/BTC
```

**Comment by kroitor** [comment]
For some reason `OCP` not listed here: https://www.okcoin.com/v2/spot/markets/products. In other words, they do return `OCP` tickers, but they don't return `OCP` market descriptions anywhere. Can't find `OCP/BTC` here either: https://www.okex.com/marketList#market=btc. Until we resolve this, you should not really submit a symbol to `fetchOrderBook` that was not received from `fetchMarkets` or `loadMarkets` in the first place. Why it got into tickers while not being listed in their markets – that's still an open question.

**Comment by AadaEa** [comment]
You're right, if an exchange provides data with `fetchTickers` and not with `fetchOrderBook` then it means that we can't trust the exchange totally. The problem appears to come from Okex so I don't think we should count this as an issue.

I contacted Okex customer support and they said that they don't have the OCP/BTC market available, then they said that they'll make the api team aware of the problem. So the fact that this is into the global ticker is probably not intended and a bug from them.

Always controlling if a pair is valid with `loadMarkets` seems to be mandatory. Maybe writing something about it in the manual.
```
$loadMarkets = $exchange->loadMarkets();
$pair = 'ETH/BTC';
if(array_key_exists($pair,$loadMarkets)){
	echo 'Found'; // do stuff
}
```

**Comment by kroitor** [comment]
> Always controlling if a pair is valid with loadMarkets seems to be mandatory. Maybe writing something about it in the manual.

We basically do that check upon your call to fetchOrderBook and throw an exception in case you're supplying an unrecognized symbol like this one. So, the check is already there, you just want to add proper exception handling for that case, or just skip that symbol entirely like you did in your snippet above. We will add additional clarifications to the Manual. Closing this for now if you don't mind. Feel free to reopen it if needed.
