### ISSUE TITLE
BitMex Testnet API Keys Not Working?

### ISSUE THREAD

**Issue by thezoug** [ccxt/ccxt#3960]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10
- Programming Language version: Python 3.6
- CCXT version: latest
- Exchange: Bitmex
- Method:

I am trying to connect to the BitMex TestNet account, but the API keys do not appear to be working. I have tried to create new keys, copying and pasting, typing in manually and nothing seems to work. I am certain that the api keys have been written correctly. What else can I try?

here is the traceback:

```
AuthenticationError: bitmex {"error":{"message":"Invalid API Key.","name":"HTTPError"}}
```

**Comment by kroitor** [comment]
> I am trying to connect to the BitMex TestNet account, but the API keys do not appear to be working.

You can't use mainnet API keys for testnet and vice versa, those aren't interchangeable. You should use testnet keys with testnet, mainnet keys with the mainnet.

https://github.com/ccxt/ccxt/issues/2649#issuecomment-418241249

**Comment by kroitor** [comment]
> I keep getting the authentication traceback...

https://github.com/ccxt/ccxt/wiki/FAQ#i-am-calling-a-method-and-i-get-an-error-what-am-i-doing-wrong

Which permissions have you used to create the testnet key? And which method are you trying to call? If you could follow issue opening guides precisely, that would help resolving it quicker...

If you're trying to create an order and you created your API keys with wrong permissions, you will get auth errors. More about Bittrex permissions on keys here:

- https://github.com/ccxt/ccxt/issues/2684#issuecomment-386692088
- https://github.com/ccxt/ccxt/issues/3758#issuecomment-416827161

**Comment by kroitor** [comment]
@thezoug does my previous comment solve the issue for you?
