### ISSUE TITLE
Implement stop loss on not supported exchanges

### ISSUE THREAD

**Issue by xcvb74** [ccxt/ccxt#3964]
Hi,

This is more about a question than an issue.
I'm trying to implement stop losses orders (or take profits/trailing) on exchanges that don't support it natively (for example on Kucoin).
I was thinking that I'll create a function to continuously monitore (every 30s/1min to not get API limit or IP ban) a ticker with : 
```
orderbook = exchange.fetch_order_book (exchange.symbols[0])
bid = orderbook['bids'][0][0] if len (orderbook['bids']) > 0 else None
ask = orderbook['asks'][0][0] if len (orderbook['asks']) > 0 else None
spread = (ask - bid) if (bid and ask) else None
print (exchange.id, 'market price', { 'bid': bid, 'ask': ask, 'spread': spread })
```
This function would run in the background of my Python script and as soon as a price condition is met, I would place an order on that exchange.

I'm having trouble to figure out how I would implement such a background task within my main script. Should I go for an infinite loop with a secondary script that I'd call from the main one?
Or is it better to go with asyncio? Or Subprocess popen? Or a combination of those?

What are your thoughts?

Thanks

PS : Don't know how to tag this as a question, not an issue

**Comment by xcvb74** [comment]
Okay so I'm progressing little by little on this. How would you modify this code to replace fetch_ticker by fetch_order_book and combine with the above to retrieve bid, ask & spread?
```
# -*- coding: utf-8 -*-

import asyncio
import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt.async_support as ccxt  # noqa: E402

kraken = ccxt.kraken({
    'apiKey': "hEvQNMDIeoCJbr7W/ZBb5CGOrx3G0lWF5B3zqa1JBxdZlEaL8EK+D0Mw",
    'secret': "JaE9wI6Nwgh5oRxiHcVxurwzwBxwc05W/qv/k1srGg4s3EYuXPpNkLLM5NYbbWpM8rCyijIeDavRuqWbU0ZV9A==",
    # 'verbose': True, # switch it to False if you don't want the HTTP log
})


async def poll():
    while True:
        yield await kraken.fetch_ticker('BTC/USD')
        await asyncio.sleep(kraken.rateLimit / 1000)


async def main():
    async for ticker in poll():
        print(ticker)


asyncio.get_event_loop().run_until_complete(main())
```
And add a condition event to trigger an alert when bid reaches a specific value?
Thanks for any help

**Comment by kroitor** [comment]
```Python
async def poll():
    while True:
        try:
            orderbook = await kraken.fetch_order_book('BTC/USD')
        catch ...: # DON'T FORGET ERROR HANDLING, AS PER MANUAL
            ... # add reaction to errors here (or somewhere, at least)
        if len(orderbook['bids']) < 1:
            throw ... # you have to specify what you want to do if bids are empty (and do it)
        elif len(orderbook['asks']) < 1:
            throw ... # # you have to specify what you want to do if asks are empty (and do it)
        else:
            topmost_bid = orderbook['bids'][0]
            bid_price = topmost_bid[0]
            topmost_ask = orderbook['asks'][0]
            ask_price = topmost_ask[0]
            spread = ask_price - bid_price
            if meets_condition(bid_price): # implement the meets_condition function how you want it
               ... # add some reaction here, like triggering an alert via whatever alerting system it is
        yield orderbook
        await asyncio.sleep(kraken.rateLimit / 1000)


async def main():
    async for orderbook in poll():
        print(orderbook)
```

**Comment by xcvb74** [comment]
Thanks, it is working!

**Comment by tredondo** [comment]
This could also be done more easily with the [watch* methods](https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual#market-data) in CCXT Pro.

**Comment by SmartManoj** [comment]
>  'apiKey': "hEvQNMDIeoCJbr7W/ZBb5CGOrx3G0lWF5B3zqa1JBxdZlEaL8EK+D0Mw",
>  'secret': "JaE9wI6Nwgh5oRxiHcVxurwzwBxwc05W/qv/k1srGg4s3EYuXPpNkLLM5NYbbWpM8rCyijIeDavRuqWbU0ZV9A==",

Invalid key

**Comment by kroitor** [comment]
@SmartManoj thx, but I wouldn't expect those keys to work since 2018 )
