### ISSUE TITLE
Cobinhood fetch order price

### ISSUE THREAD

**Issue by Showgofar** [ccxt/ccxt#3966]
hello)

- OS: debian
- Programming Language version: php
- CCXT version: latest
- Exchange:Cobinhood
- Method: fetch order

Could you please fix 
$price = $this->safe_float($order, 'eq_price');
if eq_price is zero or undefined

price should be set from info->price

```
Response:

{
    "id": "03ed73a1-4241-4987-9876-7c24e3d3030a",
    "datetime": "2018-10-08T06:59:41-04:00",
    "timestamp": 1538996380734,
    "lastTradeTimestamp": null,
    "status": "canceled",
    "symbol": "BTC\/USDT",
    "type": "limit",
    "side": "buy",
    "price": 0,
    "cost": 0,
    "amount": 0.043632,
    "filled": 0,
    "remaining": 0.043632,
    "trades": null,
    "fee": null,
    "info": {
        "id": "03ed73a1-4241-4987-9876-7c24e3d3030a",
        "trading_pair_id": "BTC-USDT",
        "side": "bid",
        "type": "limit",
        "price": "6615",
        "size": "0.043632",
        "filled": "0",
        "state": "cancelled",
        "timestamp": 1538996380734,
        "eq_price": "0",
        "completed_at": "2018-10-08T11:04:43.320627Z",
        "source": "exchange"
    }
}


```

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/blob/master/php/cobinhood.php#L460

↑ This is the current latest version... From your code it looks like your version is not the latest, despite that you wrote that it is the latest. So, I wonder what's your version of CCXT ?

**Comment by kroitor** [comment]
```PHP
mbp:ccxt igorkroitor$ php -a
Interactive shell
php > include_once ('./ccxt.php');
php > $id = '\\ccxt\\cobinhood';
php > $exchange = new $id ();
php > print_r ($exchange::VERSION);
1.17.370
```

**Comment by Showgofar** [comment]
version was
$version = '1.17.369';

**Comment by kroitor** [comment]
> version was
> $version = '1.17.369';

Nope, I don't want you to look up that variable in the Exchange.php file. I want to actually execute that code to make sure that no other installation of a previous version of the library is interfering with your actual runtime environment, therefore you have to run the above script in your php, include ccxt and print_r the version as shown above. Let us know which number it is.

**Comment by Showgofar** [comment]
Here is my mistake... i see that in version from 4th of October it was fixed.. 
seems that exactly that working script wasnt restarted after update.
