### ISSUE TITLE
The API returns the tag address even if it does not exist.

### ISSUE THREAD

**Issue by DevAza** [ccxt/ccxt#3967]
Greetings
I attach screenshots:
1) /public/getcurrencies
/account/getdepositaddress
![2018-10-08_15-19-49](https://user-images.githubusercontent.com/26380555/46612538-86251c00-cb19-11e8-975d-bdca19acfa5e.png)
2) Screenshot Deposit LSK
![2018-10-08_15-20-04](https://user-images.githubusercontent.com/26380555/46612539-86251c00-cb19-11e8-93d1-a12c5387c77a.png)
3) Screenshot Deposit XRP
![2018-10-08_15-22-55](https://user-images.githubusercontent.com/26380555/46612541-86bdb280-cb19-11e8-91cc-2aecc012aef3.png)

When there is "BaseAddress" and "Address" (XRP), then "BaseAddress" (API) => "Address", "Address" (API) => "Tag".
But when there is no "Tag" and there is only "Address" (LSK), then "Address" (API) => "Address". A "BaseAddress" (API) is not empty.

How to determine the exact address?

Thank you!

**Comment by kroitor** [comment]
Which exchange is it?

**Comment by DevAza** [comment]
> Which exchange is it?
This not exchange. This is withdraw

**Comment by kroitor** [comment]
> This not exchange. This is withdraw

This is an exchange. The Bittrex exchange to be precise. Didn't see it, as it was only mentioned on one of the screenshots with very little grey letters...

Anyways, the proper way would be to:

1. update to version 1.17.374.
2. use `fetchDepositAddress` according to the Manual: 

Let us know if that does not answer your question.

P.S.

> I attach screenshots:

Don't post screenshots next time please, follow these guides precisely: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
