### ISSUE TITLE
Bitmex and JavaScript (browser) - Can't fetch orders

### ISSUE THREAD

**Issue by SavosRU** [ccxt/ccxt#3968]
- OS:  Mac OS 10.13.6 High Sierra
- Programming Language version:   Javascript, Google Chrome 69.0.3497.100 (64-bit)
- CCXT version:   '1.17.369' (ccxt.browser.js)
- Exchange:   Bitmex
- Method: fetch_orders() and fetchOrders()

Hi!
I can't get any orders via fetch_orders() or fetchOrders(). My code is:
```
async function test(symbol) {
	try{
            var params = {};
	    var orders = await exchange.fetch_orders(symbol, params);
	    return orders;
	} catch (e) {
	    var msg = "Exception at test(): " + e;
	    console.log(msg);
	    alert(msg);
	    return -1;
	}	
}
test("BTC/USD").then(result => {
	alert(JSON.stringify(result));
});
```
And result is BAD:
![image](https://user-images.githubusercontent.com/6779356/46615911-12d3d800-cb22-11e8-9c80-c84fd5adddb5.png)

When I try almost the same on PHP - all worked fine! Code is:
```
function test($symbol) {
	try {
            $params = array();
	    $orders = $exchange->fetch_orders($symbol, $params);
	    return $orders;
	} catch (Exception $e) {
            echo "getAllOrders(): \n".$e->getMessage ();
	    return -1;
	}	
}
var_dump(test("BTC/USD"));
```

And result is OK:

![image](https://user-images.githubusercontent.com/6779356/46616338-fd12e280-cb22-11e8-837d-0e6f5a8c0656.png)

What I'm doing wrong? Help me to understand. 
Thanks and regards

**Comment by kroitor** [comment]
I can't get any orders via fetch_orders() or fetchOrders(). My code is:

```JavaScript
// this is a mistake:
var orders = await exchange.fetch_orders(symbol, params);

// this is correct:
var orders = await exchange.fetch_orders(symbol, undefined, undefined, params);
```

See the declaration of fetchOrders in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#querying-orders it has 4 arguments, not 2, and `params` is the last one (4th argument).

> When I try almost the same on PHP - all worked fine

Yep, but that was just by a lucky coincidence.

**Comment by SavosRU** [comment]
omg! My mistake - you are right!

![image](https://user-images.githubusercontent.com/6779356/46622816-7109b680-cb34-11e8-9bd2-6df6cabbb0b8.png)

Thanks again
