### ISSUE TITLE
New exchange - https://www.zg.top

### ISSUE THREAD

**Issue by ZGTOP** [ccxt/ccxt#3979]
Please support to add Exchange

Website: https://www.zg.top
API Doc: https://www.zg.top/api

Thanks!

**Comment by An-Net** [comment]
The exchange is not operating anymore.
https://www.cryptowisser.com/exchange/zgtop/
<img width="1440" alt="Снимок экрана 2021-05-20 в 21 17 40" src="https://user-images.githubusercontent.com/51840849/119029056-d7c00380-b9b0-11eb-9dab-d51b96050dac.png">
