### ISSUE TITLE
How can I give a stop market order in bitmex?

### ISSUE THREAD

**Issue by so2liu** [ccxt/ccxt#3980]
- OS: Ubuntu
- Programming Language version: Python 3
- CCXT version: newest
- Exchange: Bitmex
- Method: 

How can I give a stop market order in Bitmex? Because of overloading probability, stop market order is better than watching and giving order in time. 

Thank you very much.

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/blob/master/examples/py/bitmex-create-order.py

**Comment by YuriyTigiev** [comment]
Hello, 

Could you share code for a Stop Market order?
I'm getting an error

pair = 'BTC/USD'
buyAmount = 326
price = '7419'

order = self.exchange.createOrder(pair, "StopMarket", "buy", buyAmount, price)

[2020-01-03 18:33:31,691] ERROR - CreateStopLossBuyOrder, bitmex {"error":{"message":"Invalid price","name":"HTTPError"}}

**Comment by kroitor** [comment]
@YuriyTigiev hi)

> Could you share code for a Stop Market order?

Unfortunately, there's no such order type as `StopMarket`. You want `StopLimit`, if your price is defined. Market orders are only applicable in cases where the price is not defined. See order types, supported by BitMEX here:

- - https://www.bitmex.com/api/explorer/#!/Order/Order_new

**Comment by YuriyTigiev** [comment]
Thank you for your support 

Now code works properly. Just a qustion for the second parameter  'ReduceOnly' should I use string 'true' or Python True?

`order = self.exchange.createOrder(pair, "Stop", "buy", buyAmount, params={'stopPx': price, 'ReduceOnly': 'true'})`

**Comment by kroitor** [comment]
@YuriyTigiev for `ReduceOnly` orders your params should look as follows in both js and py, according to the BitMEX docs from here: https://www.bitmex.com/api/explorer/#!/Order/Order_new

```
params = {
    'stopPx': price,
    'execInst': 'ReduceOnly',  # ←------------ execInst param here
}
order = exchange.createOrder (..., params=params)
```
