### ISSUE TITLE
Poloniex Precision

### ISSUE THREAD

**Issue by Showgofar** [ccxt/ccxt#3986]
- OS:debian
- Programming Language version: php
- CCXT version: 1.17.375
- Exchange: Poloniex
- Method: all

Hi
Could you please check what happens with poloniex amount precision (why its capped?)
            $precision = array (
                'amount' => 6,
                'price' => 8,
            );

Poloniex support 8 digits in amount precision
Thank you

**Comment by vicxyz1** [comment]
Same issue discovered. 
Trying to sell max available, I still remain with some useless amount in balances as it truncates the units to sell.

**Comment by Showgofar** [comment]
thank you
