### ISSUE TITLE
How to share rate limit between multiple scripts?

### ISSUE THREAD

**Issue by bitnom** [ccxt/ccxt#3994]
Versions not really relevant. This could be a feature request except that I'm not asking for that. I want some input on how this might be done. The rate limiter in CCXT is good but what if I have multiple scripts using CCXT? They need to share the same rate limit. Where in the code should I look to make a cache or constant? How would you do it?

**Comment by TensorTom** [comment]
I come across this error when trying to submit a new order using `create_order()`. Verbose output:

`Request: Array ( [0] => GET [1] => https://www.bitmex.com/api/v1/instrument/activeAndIndices [2] => Array ( ) [3] => ) Response: Array ( [0] => GET [1] => https://www.bitmex.com/api/v1/instrument/activeAndIndices [2] => 403 [3] => [4] => Array ( [server] => Array ( [0] => awselb/2.0 ) [date] => Array ( [0] => Sun, 14 Oct 2018 21:39:55 GMT ) [content-type] => Array ( [0] => text/html ) [content-length] => Array ( [0] => 134 ) [connection] => Array ( [0] => keep-alive ) ) [5] =>`

**Comment by 7013145** [comment]
It will depend on what exactly you are trying to achieve. Almost definitely, the solution is not extending ccxt library functionality.

Maybe you can thread your scripts and use a global variable to hold last request timestamps, then everytime you make a request in your code (any script) you lock the variable so other scripts cannot proceed with queries before the lock is released from the first call (i.e request is done)

This could be done in Python with the threading module.

**Comment by pcriadoperez** [comment]
Closing this issue for now, but feel free to reach out for any other questions
