### ISSUE TITLE
Bitmex Rate Limiter Not Working Good I think

### ISSUE THREAD

**Issue by TensorTom** [ccxt/ccxt#3995]
- OS: Centos 7
- Programming Language version: PHP 7.2
- CCXT version: 1.17.379
- Exchange: Bitmex
- Method: $exchange->fetch_balance();

I keep getting banned from the Bitmex API. I run fetch_balance in a loop once every 10 minutes for each of my users with a saved API key. `enableRateLimit` is set to `true`

**Comment by TensorTom** [comment]
I come across this error when trying to submit a new order using `create_order()`. Verbose output:

`Request: Array ( [0] => GET [1] => https://www.bitmex.com/api/v1/instrument/activeAndIndices [2] => Array ( ) [3] => ) Response: Array ( [0] => GET [1] => https://www.bitmex.com/api/v1/instrument/activeAndIndices [2] => 403 [3] => [4] => Array ( [server] => Array ( [0] => awselb/2.0 ) [date] => Array ( [0] => Sun, 14 Oct 2018 21:39:55 GMT ) [content-type] => Array ( [0] => text/html ) [content-length] => Array ( [0] => 134 ) [connection] => Array ( [0] => keep-alive ) ) [5] =>`

**Comment by kroitor** [comment]
This should be working normally as of 1.18.300+, let us know if not. Thx for reporting!
