### ISSUE TITLE
bitfinex2 implementation misses /order/id/trades endpoint

### ISSUE THREAD

**Issue by siberianguy** [ccxt/ccxt#4005]
It looks like Bitfinex v2 implementation lacks an [order trades endpoint ](https://docs.bitfinex.com/v2/reference#rest-auth-order-trades). Or am I missing something?

**Comment by kroitor** [comment]
> It looks like Bitfinex v2 implementation lacks an order trades endpoint .

Nope, it doesn't look like that: 

- https://github.com/ccxt/ccxt/blob/master/js/bitfinex2.js#L101
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/bitfinex2.py#L106
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/bitfinex2.py#L106
- https://github.com/ccxt/ccxt/blob/master/php/bitfinex2.php#L102

> Or am I missing something?

The Manual, I guess: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
