### ISSUE TITLE
Version Diff between 1.11.147 and 1.17.388.

### ISSUE THREAD

**Issue by itsmemittal** [ccxt/ccxt#4006]
- OS: Windows
- Programming Language version: JS
- CCXT version: 1.11.147
- Exchange: Poloniex, Bitfinex
- Method: CreateOrder,fetchMarkets

I am comparing the methods between 1.11.147 and 1.17.388 and found difference would you please help why it is done?

Bitfinex-
CreateOrder Method
PriceToPrecision and AmountToPrecision is commented in 1.11.147 but uncommented in 1.17.388 

Poloniex -
FetchMarket Method
amount and price precision set to 8 in 1.11.147 but in 1.17.388 amount precision set to 6.

Gdax-
PriceToPrecision and amountToPrecision are not used in both versions.

**Comment by kroitor** [comment]
> Bitfinex-
> CreateOrder Method
> PriceToPrecision and AmountToPrecision is commented in 1.11.147 but uncommented in 1.17.388

We've switched to a new method for precision formatting, namely, `decimalToPrecision / decimal_to_precision`:

- https://github.com/ccxt/ccxt/search?q=decimal_to_precision&type=Issues

> Poloniex -
> FetchMarket Method
> amount and price precision set to 8 in 1.11.147 but in 1.17.388 amount precision set to 6.

- https://github.com/ccxt/ccxt/issues/3986
- https://github.com/ccxt/ccxt/issues/3706
- https://github.com/ccxt/ccxt/issues/3688
- https://github.com/ccxt/ccxt/issues/2706

> Gdax-
> PriceToPrecision and amountToPrecision are not used in both versions.

Same reason as for Bitfinex.
