### ISSUE TITLE
how to get future ohlcv data in exchange okex?

### ISSUE THREAD

**Issue by czonghui** [ccxt/ccxt#4012]
how to get future ohlcv data in exchange okex?

**Comment by helldragonx** [comment]
seems only the token historic price or OHLV data,

**Comment by kroitor** [comment]
@czonghui @helldragonx it was answered here:
- https://github.com/ccxt/ccxt/issues/4172#issuecomment-438940451
- https://github.com/ccxt/ccxt/issues/2043#issuecomment-368320255
