### ISSUE TITLE
Longs and shorts on bitfinex 

### ISSUE THREAD

**Issue by Arrmlet** [ccxt/ccxt#4015]
- Ubuntu 16.04:
-Python 3.6
- newest :
- Bitfinex:
- fetchTicker:

Hi everyone, I have question which can’t give me sleep. How I can count longs and shorts on bitfinex like on tradingview BTCUSDLONGS(or others) charts. I have tried all methods with ccxt library, but can’t find the answer.
Thank you for attention:)

**Comment by kroitor** [comment]
@Arrmlet have you tried implicit methods? https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

**Comment by Arrmlet** [comment]
@kroitor  I can't find this info in implicit methods

**Comment by kroitor** [comment]
@Arrmlet that section of the Manual has an example showing how to list all implicit methods for an exchange instance – have you tried running that snippet of code and looking for the method you want in the output? 

```Python
import ccxt
from pprint import pprint
pprint(dir(ccxt.bitfinex()))  # v1
pprint(dir(ccxt.bitfinex2()))  # v2
```

You're looking for the following methods:

```
 'public_get_stats1_key_size_symbol_long_hist',
 'public_get_stats1_key_size_symbol_long_last',
 'public_get_stats1_key_size_symbol_section',
 'public_get_stats1_key_size_symbol_short_hist',
 'public_get_stats1_key_size_symbol_short_last',
```

See the arguments for them here: https://docs.bitfinex.com/v2/reference#rest-public-stats (you should read it)

The Manual also shows how to call those implicit methods and how to pass your arguments to them.

Hope this answers your question.

**Comment by Arrmlet** [comment]
@kroitor Thank you very match:)
