### ISSUE TITLE
HitBTC order not found

### ISSUE THREAD

**Issue by presence35** [ccxt/ccxt#4018]
- OS: linux
- Programming Language version: php
- CCXT version:  1.17.393
- Exchange: HitBTC
- Method: fetchOrder

Hey. Thanks for your work. I'm getting  "order not found" even tho the order exists. In the verbose mode it spits out the orders at the bottom of the log.  I've tried looking thru some other examples but I can't figure out what is wrong. The has['FetchOrder'] returns true. Any help would be appreciated. Thanks.

$order = $exchange->fetchOrder($o['id'],$o['symbol'],array("type" => strtoupper($o['side'])));

Response: Array ( [0] => GET [1] => http://api.hitbtc.com/api/1/trading/order?nonce=1539871482270&apikey=XXX&clientOrderId=XXX&type=SELL [2] => 200 [3] => [4] => Array ( [server] => Array ( [0] => nginx ) [date] => Array ( [0] => Thu, 18 Oct 2018 14:04:42 GMT ) [content-type] => Array ( [0] => application/json; charset=utf-8 ) [content-length] => Array ( [0] => 17 ) [connection] => Array ( [0] => keep-alive ) ) [5] => {"orders":[null]} ) 17:04:42: ccxt\OrderNotFound: hitbtc fetchOrder() error => in /home/public_html/ccxt-master/php/hitbtc.php:850 Stack trace: #0 /home/public_html/ccxt-master/php/Exchange.php(1602): ccxt\hitbtc->fetch_order('...', 'SCC/BTC', Array) #1 /home/public_html/coinsnap/coinsnap.php(552): ccxt\Exchange->fetchOrder('...', 'SCC/BTC', Array) #2 /home/public_html/coinsnap/tickers.php(34): COINSNAP->getOrders(Object(ccxt\OrderNotFound)) #3 {main}

**Comment by presence35** [comment]
How do I change ccxt to check v2 of Hit api?

**Comment by kroitor** [comment]
> How do I change ccxt to check v2 of Hit api?

```PHP
$id = '\\ccxt\\hitbtc'; // ←--------------- change this line 
exchange = new $id (array(
    'enableRateLimit': true, // this is required
))
```

↓

```PHP
$id = '\\ccxt\\hitbtc2';
...
```

**Comment by presence35** [comment]
Awesome.  That worked!  Thx man.
