### ISSUE TITLE
Binance exhange instance all markets have 'active' flag marked  False

### ISSUE THREAD

**Issue by DmitryVil** [ccxt/ccxt#4022]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows server 2016
- Programming Language version: Python
- CCXT version: 1.17.394
- Exchange: Binance
- Method: binance.loadMarkets()

Good morning,

All markets in binance exchange have flag 'active' = False.

![image](https://user-images.githubusercontent.com/35109659/47206321-0c9af280-d391-11e8-8855-ebc98cb8d8b3.png)

Thank you advance,

Dmitry

**Comment by kroitor** [comment]
> Closed. It was the problem of Binance

Right: https://support.binance.com/hc/en-us/articles/360018425891
