### ISSUE TITLE
Wrong sell price for cheap currencies on Binance via freqtrade

### ISSUE THREAD

**Issue by gryffus** [ccxt/ccxt#4025]
- OS: Linux (tested on Centos and SUSE)
- Programming Language version: Python 3.6.3 and Python 3.6.5
- CCXT version: ccxt==1.17.363 and ccxt==1.17.376
- Exchange: Binance
- Method: create_limit_sell_order()

I am using freqtrade and i hit stoploss, but the bot tries to sell at a price higher than current price.

    Price of the bid posted on market was 4e-06
    Price of the bid posted on market should be 3.73e-06

I am still trying to investigate this together with freqtrade maintainer @xmatthias and up until create_limit_sell_order, the price seems to be correct, but on the market it isn't. However i was not able to reproduce this directly in freqtrade, so i am asking for help here.

More details (test case used, debug logs) can be found in https://github.com/freqtrade/freqtrade/issues/1289

Debug log:
I am calling create_limit_sell_order with this parameters:
`2018-10-20 17:26:52,468 - freqtrade.exchange - DEBUG - Parameters for create_limit_sell_order. pair: POE/BTC, amount: 5549.445, rate: 1.77e-06`

Code:
```
        try:
            # Set the precision for amount and price(rate) as accepted by the exchange
            logger.debug("Rate for sell in exchange/__init__py: %s",rate)
            amount = self.symbol_amount_prec(pair, amount)
            rate = self.symbol_price_prec(pair, rate)
            logger.debug("Rate for sell in exchange/__init__py: %s",rate)

            logger.debug("Parameters for create_limit_sell_order. pair: %s, amount: %s, rate: %s",pair,amount,rate)
            logger.debug("type(rate): %s",type(rate))
            ret = self._api.create_limit_sell_order(pair, amount, rate)
            logger.debug("ccxt return: %s", ret)
            return ret

```

but get this output and response from ccxt:

```
2018-10-20 18:07:12,287 - freqtrade.exchange - DEBUG - Rate for sell in exchange/__init__py: 1.78e-06
2018-10-20 18:07:12,288 - freqtrade.exchange - DEBUG - Price in symbol_price_prec 1.78e-06
2018-10-20 18:07:12,288 - freqtrade.exchange - DEBUG - Rate for sell in exchange/__init__py: 1.78e-06
2018-10-20 18:07:12,288 - freqtrade.exchange - DEBUG - Parameters for create_limit_sell_order. pair: POE/BTC, amount: 5549.445, rate: 1.78e-06
2018-10-20 18:07:12,288 - freqtrade.exchange - DEBUG - type(rate): <class 'float'>
2018-10-20 18:07:12,793 - freqtrade.exchange - DEBUG - ccxt return: {'info': {'symbol': 'POEBTC', 'orderId': 21744127, 'clientOrderId': '', 'transactTime': 1540051632660, 'price': '0.00000200', 'origQty': '5549.00000000', 'executedQty': '0.00000000', 'cummulativeQuoteQty': '0.00000000', 'status': 'NEW', 'timeInForce': 'GTC', 'type': 'LIMIT', 'side': 'SELL'}, 'id': '21744127', 'timestamp': 1540051632660, 'datetime': '2018-10-20T16:07:12.660Z', 'lastTradeTimestamp': None, 'symbol': 'POE/BTC', 'type': 'limit', 'side': 'sell', 'price': 2e-06, 'amount': 5549.0, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 5549.0, 'status': 'open', 'fee': None, 'trades': None}

Request: POST https://api.binance.com/api/v3/order {'X-MBX-APIKEY': '', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} timestamp=1540051632520&recvWindow=5000&symbol=POEBTC&quantity=5549&type=LIMIT&side=SELL&newOrderRespType=RESULT&price=0.000002&timeInForce=GTC&signature=

Response: POST https://api.binance.com/api/v3/order 200 {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Sat, 20 Oct 2018 16:07:12 GMT', 'Server': 'nginx', 'Content-Encoding': 'gzip', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 2e8f70eb03b681aa6bd8c18fff081f80.cloudfront.net (CloudFront)', 'X-Amz-Cf-Id': ''} {"symbol":"POEBTC","orderId":21744127,"clientOrderId":"","transactTime":1540051632660,"price":"0.00000200","origQty":"5549.00000000","executedQty":"0.00000000","cummulativeQuoteQty":"0.00000000","status":"NEW","timeInForce":"GTC","type":"LIMIT","side":"SELL"}

```

**Comment by kroitor** [comment]
@gryffus in order to help we need your verbose request/response and the code to reproduce the issue. Unfortunately, we're not responsible for freqtrade, but we can help with CCXT though. Anyways, to be able to help you,  we need you to follow these guides literally: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by gryffus** [comment]
@kroitor request/response was provided, but i was not able to reproduce this so far with a test case

**Comment by kroitor** [comment]
@gryffus you're trying to sell 5549.445 POE for a price of 0.0000177 POE/BTC.

If you take the info on market precision into consideration https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits and run the following example, then it should show the following:

```
mbp:ccxt igorkroitor$ python examples/py/cli.py binance market POE/BTC
```
```Python
{'active': True,
 'base': u'POE',
 'baseId': u'POE',
 'fee_loaded': False,
 'id': u'POEBTC',
 'info': {u'baseAsset': u'POE',
          u'baseAssetPrecision': 8,
          u'filters': [{u'filterType': u'PRICE_FILTER',
                        u'maxPrice': u'0.00001780',
                        u'minPrice': u'0.00000018',
                        u'tickSize': u'0.00000001'},
                       {u'filterType': u'LOT_SIZE',
                        u'maxQty': u'90000000.00000000',
                        u'minQty': u'1.00000000',
                        u'stepSize': u'1.00000000'},
                       {u'filterType': u'MIN_NOTIONAL',
                        u'minNotional': u'0.00100000'},
                       {u'filterType': u'ICEBERG_PARTS', u'limit': 10},
                       {u'filterType': u'MAX_NUM_ALGO_ORDERS',
                        u'maxNumAlgoOrders': 5}],
          u'icebergAllowed': True,
          u'orderTypes': [u'LIMIT',
                          u'LIMIT_MAKER',
                          u'MARKET',
                          u'STOP_LOSS_LIMIT',
                          u'TAKE_PROFIT_LIMIT'],
          u'quoteAsset': u'BTC',
          u'quotePrecision': 8,
          u'status': u'TRADING',
          u'symbol': u'POEBTC'},
 'limits': {'amount': {'max': 90000000.0, 'min': 1.0},
            'cost': {'max': None, 'min': 0.001},
            'price': {'max': 1.78e-05, 'min': 1.8e-07}},
 'maker': 0.001,
 'percentage': True,
 'precision': {'amount': 0, 'base': 8, 'price': 8, 'quote': 8},
 'quote': u'BTC',
 'quoteId': u'BTC',
 'symbol': u'POE/BTC',
 'taker': 0.001,
 'tierBased': False}
```

So, that particular POE/BTC market has the following limits and precision:

```
 'precision': {'amount': 0, 'base': 8, 'price': 8, 'quote': 8},
 'limits': {'amount': {'max': 90000000.0, 'min': 1.0},
            'cost': {'max': None, 'min': 0.001},
            'price': {'max': 1.78e-05, 'min': 1.8e-07}},
```

Note, that the limit on amount is 1 and precision of amount is zero decimal digits, that effectively only allows integer amounts in increments of one. 5549 and 5550 are ok, but not 5549.445. In the latter case the value will be truncated to the precision accepted by the exchange. Truncation is used for amounts, because this it generates the preferred outcome for the user in most cases. In other words, if you ordered 5549.445 POE, and the exchange does not allow that, then you will most likely want 5549 POE, not 5550 POE. Therefore the amount is set to a whole integer number, we can see that from your verbose request:

```
...&quantity=5549&...
```

That should explain the difference in the amount submitted to createOrder and the amount actually ordered.

Now, back to your initial question on the price, your value of 0.0000177 is well within limits according to Binance market info above. And this is the value that gets sent towards the exchange, if you execute the following example:

```
mbp:ccxt igorkroitor$ python examples/py/cli.py binance createOrder POE/BTC limit sell 5549.445 0.00000177 --verbose
```
```
('\nRequest:', 'POST', 'https://api.binance.com/api/v3/order', {'Content-Type': 'application/x-www-form-urlencoded', 'X-MBX-APIKEY': ..., 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'python-requests/2.18.4'}, 'newOrderRespType=RESULT&timestamp=1540052955306&symbol=POEBTC&side=SELL&timeInForce=GTC&recvWindow=5000&type=LIMIT&price=0.00000177&quantity=5549&signature=...')
```

↑ This shows it clearly: `&price=0.00000177&quantity=5549&` is the value that gets sent towards the exchange on my side. Now, you should have the same request with the above example command, can you confirm? If that is the case, then the error is outside of CCXT. At this point we need you to follow the above instructions and post your results.

**Comment by gryffus** [comment]
I have actually already tried this:

Python 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> ct = ccxt.binance({'apiKey': '',
...             'secret': ''
...                   })
>>> mark = ct.loadMarkets()
>>> pair='VET/BTC'
>>> amount=5555
>>> price=0.00000178
>>> print(ct.amountToPrecision(pair, amount))
5555
>>> from math import floor, ceil
>>> def symbol_price_prec(pair, price):
...     if ct.markets[pair]['precision']['price']:
...         symbol_prec = ct.markets[pair]['precision']['price']
...         big_price = price * pow(10, symbol_prec)
...         price = ceil(big_price) / pow(10, symbol_prec)
...     return price
... 
>>> print(ct.price_to_precision(pair, price))
0.00000178
>>> print(symbol_price_prec(pair, price))    
1.78e-06
>>> 
>>> ct.create_limit_buy_order(pair, amount, price)
{'info': {'symbol': 'VETBTC', 'orderId': 8882953, 'clientOrderId': '', 'transactTime': 1540036365145, 'price': '0.00000178', 'origQty': '5555.00000000', 'executedQty': '0.00000000', 'cummulativeQuoteQty': '0.00000000', 'status': 'NEW', 'timeInForce': 'GTC', 'type': 'LIMIT', 'side': 'BUY'}, 'id': '8882953', 'timestamp': 1540036365145, 'datetime': '2018-10-20T11:52:45.145Z', 'lastTradeTimestamp': None, 'symbol': 'VET/BTC', 'type': 'limit', 'side': 'buy', 'price': 1.78e-06, 'amount': 5555.0, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 5555.0, 'status': 'open', 'fee': None, 'trades': None}
>>> ct.create_limit_sell_order(pair, amount, price)
{'info': {'symbol': 'VETBTC', 'orderId': 8882977, 'clientOrderId': '', 'transactTime': 1540036426869, 'price': '0.00000178', 'origQty': '5555.00000000', 'executedQty': '5555.00000000', 'cummulativeQuoteQty': '0.00988790', 'status': 'FILLED', 'timeInForce': 'GTC', 'type': 'LIMIT', 'side': 'SELL'}, 'id': '8882977', 'timestamp': 1540036426869, 'datetime': '2018-10-20T11:53:46.869Z', 'lastTradeTimestamp': None, 'symbol': 'VET/BTC', 'type': 'limit', 'side': 'sell', 'price': 1.78e-06, 'amount': 5555.0, 'cost': 0.0098879, 'average': 1.78e-06, 'filled': 5555.0, 'remaining': 0.0, 'status': 'closed', 'fee': None, 'trades': None}
>>> 
```

That confirms that it should not be inside ccxt. But what are other possible reasons (configuration, ...) that the price gets truncated, or rather rounded? Because it seems that i put send parameters to the create_limit_sell_order()

**Comment by kroitor** [comment]
> I have actually already tried this:

No you haven't... We need your verbose request/response which is not shown in the above message. From the request it should be clear which particular values got sent towards Binance and which particular values they replied with – that in turn would show where the the issue is – either on CCXT side or Binance side.

**Comment by kroitor** [comment]
Basically, we need you to simply add this line to the above code in the instantiation section in the very beginning of it:

```Python
ct = ccxt.binance({
    'apiKey': '',
    'secret': '',
    'verbose': True,  # ←---------- this one
})
```

Keep the rest of the above snippet unchanged and rerun it again and dump the output here (without your keys of course).

**Comment by kroitor** [comment]
Sorry, I have misread your response, I thought you said the opposite, please ignore my two previous comments.

**Comment by kroitor** [comment]
Your output actually shows no issue to me now: we asked for 5555 @ 0.00000178 and we got 5555 for that price in both cases (buy and sell).

**Comment by gryffus** [comment]
My code actually created orders with correct price, that's the point... It only happens in the snippet in description.

**Comment by kroitor** [comment]
> My code actually created orders with correct price, that's the point... It only happens in the snippet in description.

Right. Sorry again, I've misinterpreted your answer, ignore my two comments above.

As for you question: 

> But what are other possible reasons (configuration, ...) that the price gets truncated, or rather rounded? Because it seems that i put send parameters to the create_limit_sell_order()

This is explained here: https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits.
Truncation is applied to amounts, rounding is applied to prices. This is true for all exchanges, most of them have at least some limits on amount/price values and precisions.

So, if that snippet above created the order with proper values, then you should check the logic on your side, because, as you've shown yourself, the values you submitted get through CCXT, so, if you get a different result with different code – check that code for mistakes or side-effects.

**Comment by gryffus** [comment]
How can i get current runtime precision for a price of a market?
Is it possible to overwrite this, or is it always fetched live from market?

**Comment by kroitor** [comment]
> How can i get current runtime precision for a price of a market?

```Python
from pprint import pprint
import ccxt
exchange = ccxt.binance(...)
exchange.load_markets()  #  https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
pprint(exchange.markets['POE/BTC']['limits'])  # https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits
pprint(exchange.markets['POE/BTC']['precision'])  
```

> Is it possible to overwrite this, 

Yes, just set those values to what you want after loading the markets.

> or is it always fetched live from market?

And yes )

Let me know if that answers your question.

**Comment by xmatthias** [comment]
i'm looking at this puzzled ... 
running sample code does work - but real code produces odd results.

amount is expected to change (that's part of how binance applies fees) - but the price should not.
i've tried to run `ct.price_to_precision(pair, price)` in any combination i could immagine (for the pair/price in question) - but i can't figure out what's causing this.

what's the expected type for price of `create_limit_sell_order`? we're passing in float - but i did that in the tests too so i assume that's correct ?

**Comment by gryffus** [comment]
I have added this:
```
        try:
            # Set the precision for amount and price(rate) as accepted by the exchange
            logger.debug("Rate for sell in exchange/__init__py: %s",rate)
            amount = self.symbol_amount_prec(pair, amount)
            rate = self.symbol_price_prec(pair, rate)
            logger.debug("Rate for sell in exchange/__init__py: %s",rate)

            logger.debug("Parameters for create_limit_sell_order. pair: %s, amount: %s, rate: %s",pair,amount,rate)
            logger.debug("type(rate): %s",type(rate))
            ret = self._api.create_limit_sell_order(pair, amount, rate)
            logger.debug("ccxt return: %s", ret)
            logger.debug("Current price precision for POE/BTC: %s",self._api.markets['POE/BTC']['precision']['price'])
            logger.debug("Current price limits for POE/BTC: %s",self._api.markets['POE/BTC']['limits']['price'])
            return ret
```

But still getting this:

```
2018-10-20 19:22:28,630 - freqtrade.exchange - DEBUG - Rate for sell in exchange/__init__py: 1.77e-06
2018-10-20 19:22:28,630 - freqtrade.exchange - DEBUG - Price in symbol_price_prec 1.77e-06
2018-10-20 19:22:28,630 - freqtrade.exchange - DEBUG - Rate for sell in exchange/__init__py: 1.77e-06
2018-10-20 19:22:28,630 - freqtrade.exchange - DEBUG - Parameters for create_limit_sell_order. pair: POE/BTC, amount: 5549.445, rate: 1.77e-06
2018-10-20 19:22:28,630 - freqtrade.exchange - DEBUG - type(rate): <class 'float'>

Request: POST https://api.binance.com/api/v3/order {'X-MBX-APIKEY': '', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} timestamp=1540056146646&recvWindow=5000&symbol=TRXBTC&quantity=2702&type=LIMIT&side=SELL&newOrderRespType=RESULT&price=0.000004&timeInForce=GTC&signature=

Response: POST https://api.binance.com/api/v3/order 200 {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Sat, 20 Oct 2018 17:22:26 GMT', 'Server': 'nginx', 'Content-Encoding': 'gzip', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 50f21cb925e6471490e080147e252d7d.cloudfront.net (CloudFront)', 'X-Amz-Cf-Id': ''} {"symbol":"TRXBTC","orderId":74954950,"clientOrderId":"","transactTime":1540056146788,"price":"0.00000400","origQty":"2702.00000000","executedQty":"0.00000000","cummulativeQuoteQty":"0.00000000","status":"NEW","timeInForce":"GTC","type":"LIMIT","side":"SELL"}
2018-10-20 19:22:29,140 - freqtrade.exchange - DEBUG - Current price precision for POE/BTC: 8
2018-10-20 19:22:29,140 - freqtrade.exchange - DEBUG - Current price limits for POE/BTC: {'min': 1.8e-07, 'max': 1.77e-05}
```

**Comment by kroitor** [comment]
CCXT works normally with those values on my side with the examples/py/cli.py:

```
mbp:ccxt igorkroitor$ python examples/py/cli.py binance createLimitSellOrder POE/BTC 5549.445 0.00000177 --verbose
('\nRequest:', 'POST', 'https://api.binance.com/api/v3/order', {'Content-Type': 'application/x-www-form-urlencoded', 'X-MBX-APIKEY': u'dzEPWDVXnMTNSzv0PwuiazKUiERfolUkbrc5c5l39oKRsC211bF1pKjal9csgM9h', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'python-requests/2.18.4'}, 'newOrderRespType=RESULT&timestamp=1540057194423&symbol=POEBTC&side=SELL&timeInForce=GTC&recvWindow=5000&type=LIMIT&price=0.00000177&quantity=5549&signature=3cdda1f5a8cd2dcfee038bceea826c3d49bdb6c439c64c158c5e9ac4dc78ae4e')
mbp:ccxt igorkroitor$
```

However, in your request we see:

```
...price=0.000004...
```

If verbose output shows that, then it means that a value of 0.000004 or very close to 0.000004 was actually submitted to the createLimitSellOrder call.

To me it looks like an issue with how the values get submitted from freqtrade, because you did show above that with proper values CCXT works normally for you as well. So if you get the price of 0.00004 then it is the price that was actually submitted to createLimitSellOrder call. The method itself does not change the value that much and it can't change drastically due to rounding. You can't submit 0.00000177 and get 0.000004 from CCXT. If you get 0.000004, then you (or freqtrade) submitted 0.000004 or something close to that. In order to resolve it you will have to isolate the issue in a simplest possible form to see what may be causing that weird behavior, but, at this point I'm pretty sure it's beyond CCXT. I do make mistakes, though, so, if you can show that it is an issue with CCXT, we will surely fix it.

**Comment by xmatthias** [comment]
I do agree - however struggle to see where freqtrade submits something wrong - as @gryffus added debug-statements to the variable right before the ccxt call - my only suspicion is on the data-type passed in - but float should work just fine - as the "independent" script does prove.

without beeing able to recreate the issue independently i agree that's it's not a problem in ccxt...

**Comment by kroitor** [comment]
Here's an isolated test:

```
mbp:ccxt igorkroitor$ python examples/py/cli.py binance price_to_precision POE/BTC 0.00000177
'0.00000177'
```

To me it looks like something has happened:

```
 try:
            logger.debug("Parameters for create_limit_sell_order. pair: %s, amount: %s, rate: %s",pair,amount,rate)
            logger.debug("type(rate): %s",type(rate))

            #  ------------- HERE ---------------------

            ret = self._api.create_limit_sell_order(pair, amount, rate)
            logger.debug("ccxt return: %s", ret)
            logger.debug("Current price precision for POE/BTC: %s",self._api.markets['POE/BTC']['precision']['price'])
            logger.debug("Current price limits for POE/BTC: %s",self._api.markets['POE/BTC']['limits']['price'])
            return ret
```

```Python
mbp:ccxt igorkroitor$ python3
Python 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> binance = ccxt.binance()
>>> markets = binance.load_markets()
>>> rate = 1.77e-06
>>> print("Parameters for create_limit_sell_order. pair: %s, amount: %s, rate: %s" % ("POE/BTC", 123, rate))
Parameters for create_limit_sell_order. pair: POE/BTC, amount: 123, rate: 1.77e-06
>>> binance.price_to_precision('POE/BTC', rate)
'0.00000177'
>>> print(ccxt.__version__)
1.17.393
```

**Comment by gryffus** [comment]
What exactly  "precision = min(context.prec - 2, precision)" in https://github.com/ccxt/ccxt/blob/5a3fa3961472d80a5eb24e8a54a57f877d5cae78/python/ccxt/base/decimal_to_precision.py#L37 is supposed to do?

**Comment by gryffus** [comment]
I seem to be able to reproduce this.
Is it possible that decimal.getcontext().prec can be set to 8? If yes, then following code, will show the issue (it is made from https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/decimal_to_precision.py ) :

```
import decimal
import numbers

# rounding mode
TRUNCATE = 0
ROUND = 1

# digits counting mode
DECIMAL_PLACES = 2
SIGNIFICANT_DIGITS = 3

# padding mode
NO_PADDING = 4
PAD_WITH_ZERO = 5

n=1.77e-06
precision=8

rounding_mode=ROUND
counting_mode=8
padding_mode=NO_PADDING
counting_mode=DECIMAL_PLACES

assert precision is not None and isinstance(precision, numbers.Integral)
assert rounding_mode in [TRUNCATE, ROUND]
assert counting_mode in [DECIMAL_PLACES, SIGNIFICANT_DIGITS]
assert padding_mode in [NO_PADDING, PAD_WITH_ZERO]

context = decimal.getcontext()

# If decimal.getcontext().prec is set to 8:
context.prec=8

precision = min(context.prec - 2, precision)

context.traps[decimal.Underflow] = True
context.rounding = decimal.ROUND_HALF_UP  # rounds 0.5 away from zero

dec = decimal.Decimal(str(n))
string = '{:f}'.format(dec)  # convert to string using .format to avoid engineering notation
precise = None

def power_of_10(x):
  return decimal.Decimal('10') ** (-x)

'{:f}'.format(dec.quantize(power_of_10(precision))) # ROUND_HALF_EVEN is default context
```

This produces result: '0.000002'

**Comment by gryffus** [comment]
Confirmed by @xmatthias , the issue is caused by changing context precision in freqtrade persistence api.

Thanks @kroitor and @xmatthias for help

**Comment by kroitor** [comment]
@gryffus thx for reporting back!
