### ISSUE TITLE
Okex fetchBalance returns 0 and v3 api

### ISSUE THREAD

**Issue by AadaEa** [ccxt/ccxt#4029]
Hi,
Using the okex class. okex always returns 0 as balance (including inside the `info` fields). The request seems to work but it returns 0 while it should return the right amount.

I tried to get the data through url but couldn't make it work for some reason : https://www.okex.com/api/v1/userinfo.do?api_key=XXXXX&sign=XXXXX

using a valid api key and secret returns the same message.

Maybe it has something to do with the v3. Which will become mandatory soon :

![okex](https://user-images.githubusercontent.com/43556802/47272297-0b7de700-d584-11e8-890a-d1ff6d99c9d1.png)

https://www.okex.com/docs/en/

**Comment by kroitor** [comment]
Answered here: https://github.com/ccxt/ccxt/pull/3911#issuecomment-425209458
