### ISSUE TITLE
Signature does not match request parameters for cryptopia

### ISSUE THREAD

**Issue by gamebak** [ccxt/ccxt#4032]
The issue is that I can't send the api key and secret in cryptopia for a private
```GOOD
// api key and secret from cryptopia
const apiKey = 'my_api_key_from_cryptopia'
const apiSecret = 'my_secret_from_cryptopia'
```
```javascript
let cryptopia = new ccxt.cryptopia({
  'apiKey': apiKey,
  'secret': apiSecret,
  'timeout': 30000,
})
```

**Error:**
```BAD
(node:1711) UnhandledPromiseRejectionWarning: Error: cryptopia Signature does not match request parameters.
    at cryptopia.handleErrors (.../node_modules/ccxt/js/cryptopia.js:790:31)
    at response.text.then (.../node_modules/ccxt/js/base/Exchange.js:647:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:1711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

```
- OS: MacOs
- Programming Language version:
- CCXT version: 1.17.368
- Exchange: Cryptopia
- Method: new ccxt.cryptopia

**Comment by kroitor** [comment]
Have you tried the troubleshooting sequence from the Manual?

- https://github.com/ccxt/ccxt/wiki#troubleshooting

Also, make sure that your apiKey is 32 characters and secret is 44 characters. The secret may have an equality sign at the end of it (`=`) and can contain slashes, therefore copy-pasting by double-clicking is a common pitfall. The other common pitfall is trying to use keys that have already been used with another software. Make sure you're using the newly created fresh keypair and that you've copypasted your credentials properly.

Which method/call are you trying to execute?

**Comment by gamebak** [comment]
You were right, checking the secret, it had 40 characters instead of 44 and that fixed the issue.

**Comment by gamebak** [comment]
You were right, checking the secret, it had 40 characters instead of 44 and that fixed the issue.

**Comment by kroitor** [comment]
@gamebak thx for reporting back, appreciate it!
