### ISSUE TITLE
Liquid exchange does not correctly report average execution price

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#4034]
The `average_price` field on my orders is not always correct.  It sometimes has the value _0.0_ when the order has traded (see below).  This can be fixed by parsing the `executions` array which contains the trade data.  (I'll try to fix)

```
{
    "id": 227673885,
    "order_type": "limit",
    "quantity": "0.5",
    "disc_quantity": "0.0",
    "iceberg_total_quantity": "0.0",
    "side": "sell",
    "filled_quantity": "0.5",
    "price": 0.07935,
    "created_at": 1520759544,
    "updated_at": 1520759544,
    "status": "filled",
    "leverage_level": 1,
    "source_exchange": null,
    "product_id": 37,
    "product_code": "CASH",
    "funding_currency": "BTC",
    "crypto_account_id": null,
    "currency_pair_code": "ETHBTC",
    "average_price": "0.0", <-- this is wrong
    "target": "spot",
    "order_fee": "0.0",
    "source_action": "manual",
    "unwound_trade_id": null,
    "trade_id": null,
    "settings": null,
    "trailing_stop_type": false,
    "trailing_stop_value": false,
    "executions": [
        {"id": 30493260, "quantity": "0.007677", "price": "0.07997", "taker_side": "sell", "created_at": 1520759544, "my_side": "sell"}, 
        {"id": 30493261, "quantity": "0.492323", "price": "0.07935", "taker_side": "sell", "created_at": 1520759544, "my_side": "sell"}],
    "stop_triggered_time": null
}
```

**Comment by kroitor** [comment]
> I'll try to fix

That's great! Your help is really welcome! For examples, see how parsing order trades is done with `parseTrade` in other exchanges as well:

- https://github.com/ccxt/ccxt/blob/master/js/poloniex.js#L553
- https://github.com/ccxt/ccxt/blob/master/js/kucoin.js#L688
- ...

**Comment by npomfret** [comment]
@kroitor the trade fees on Liquid only appear on the order.  It would be nice if they were proportially attributed to each trade.  Are per-trade fees allowed in the ccxt model?

**Comment by kroitor** [comment]
@npomfret yes, the fee is present in the trade structure as well. In fact, by pure logic, the order fee is the sum of trade fees of all trades inside that order. )

https://github.com/ccxt/ccxt/wiki/Manual#trade-structure

**Comment by npomfret** [comment]
I'll hold off on attributing the fees to the orders for now.  I'm concerned that there might be different fees for taker / maker trades which I'm not currently sure how to model.
