### ISSUE TITLE
Withdraw / Deposit History?

### ISSUE THREAD

**Issue by exzib** [ccxt/ccxt#4041]
Is there any way to see which exchanges on ccxt supports fetchMyWithdrawals?

Or is there any way to see which exchanges supports fetching withdraws and deposits in general?

**Comment by kroitor** [comment]
> Is there any way to see which exchanges on ccxt supports fetchMyWithdrawals?

Yes:

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata
- https://github.com/ccxt/ccxt/blob/master/examples/js/exchange-capabilities.js

<img width="1505" alt="screen shot 2018-10-24 at 17 36 58" src="https://user-images.githubusercontent.com/1294454/47438649-8da02280-d7b3-11e8-9412-7e3f2902a645.png">
