### ISSUE TITLE
Use ccxt in NodeJS with promise

### ISSUE THREAD

**Issue by ne0c0de** [ccxt/ccxt#4043]
Hello,

I seaarch my question in both issues on here and also on google but couldn't find an example.

Is it possible to use ccxt nodejs library with Promise?

I know that it's working with await syntax but i wish to use it with promise library (actually i wish to use with regular callbacks but i couldn't)

Is someone here that's using ccxt with promise?

**Comment by kroitor** [comment]
JSYI, `async` syntax is just a syntax sugar over promises (`async` uses promises under the hood).

Async:

```JavaScript
const ccxt = require ('ccxt')

;(async () => {
    let exchange = new ccxt.bittrex ({ enableRateLimit: true })
    let symbol = 'ETH/BTC'
    try {
        let result = await exchange.fetchOrderBook (symbol)
        console.log (result)
    } catch (error) {
        console.log (e.constructor.name, e.message)
    }
}) ()
```

Promise:

```JavaScript
const ccxt = require ('ccxt')
let exchange = new ccxt.bittrex ({ enableRateLimit: true })
let symbol = 'ETH/BTC'
exchange.fetchOrderBook (symbol).then (result => {
    console.log (result)
}).catch (error => {
    console.log (e.constructor.name, e.message)
})
```
