### ISSUE TITLE
new Liquid edit order functionality throwing wrong type of error (I think)

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#4044]
The error message _'Can not update partially filled order'_ results in an `OrderNotFound`.  But I don't think this makes sense.  What would be a more suitable error though?

**Comment by kroitor** [comment]
> What would be a more suitable error though?

InvalidOrder ?

**Comment by npomfret** [comment]
https://github.com/ccxt/ccxt/pull/4048

**Comment by kroitor** [comment]
@npomfret thank you!
