### ISSUE TITLE
Dictionary & Object dynamic type conversion error IronPython

### ISSUE THREAD

**Issue by SandersAlex** [ccxt/ccxt#4045]
- OS: Win 10
- Programming Language version: IronPython 2.7, Python 2.7, C# 4.7.2
- CCXT version: 1.17.392
- Exchange: All, Base Functional - exchange.py
- Method: **to_array**
```
@staticmethod  
def to_array(value):  
        return list(value.values()) if type(value) is dict else value

def load_markets(self, reload=False):
        if not reload:
            if self.markets:
                if not self.markets_by_id:
                    return self.set_markets(self.markets)
                return self.markets
        markets = self.fetch_markets()
        currencies = None
        if self.has['fetchCurrencies']:
            currencies = self.fetch_currencies()
        return self.set_markets(markets, currencies)

def fetch_markets(self):
        # markets are returned as a list
        # currencies are returned as a dict
        # this is for historical reasons
        # and may be changed for consistency later
        return self.to_array(self.markets)
```

An exception was thrown: "IronPython.Runtime.Exceptions.TypeErrorException" in Microsoft.Dynamic.dll
An unhandled exception of type "IronPython.Runtime.Exceptions.TypeErrorException" in Microsoft.Dynamic.dll
Additional information: **expected string, got str Type**

Question:
Is it possible to measure this function so that it returns Type for "IronPython" in any case, or has it already hit a certain type, for example, a dictionary or a list, as is done for "currencies"?
Worked example:
```
private ScriptEngine engine { get; set; }
private ScriptScope scope { get; set; }

string pathPython = @"d:\Python27";
string pathIronPython = @"d:\IronPython 2.7";

engine = Python.CreateEngine();
var paths = engine.GetSearchPaths();
paths.Add(String.Format(@"{0}\Lib\site-packages\", pathPython));
paths.Add(String.Format(@"{0}\", pathPython));
paths.Add(String.Format(@"{0}\Lib\", pathIronPython));
engine.SetSearchPaths(paths);

scope = engine.CreateScope();
engine.Execute("import sys", scope);
engine.Execute("import ccxt", scope);

dynamic exchange = engine.Execute(@"ccxt.binance({'apiKey': 'thisAPIKey', 'secret': 'thisSecretKey'})", scope);

IronPython.Runtime.PythonDictionary currencies = exchange.currencies; // is not null
```
Examle with markets:
```
var markets = exchange.markets; // is null
// var fm = exchange.fetch_markets(); // is error
```

**Comment by kroitor** [comment]
@SandersAlex can you please post the error callstack for that exception? We would then be able to fix it quickly.

**Comment by SandersAlex** [comment]
> 
> 
> @SandersAlex can you please post the error callstack for that exception? We would then be able to fix it quickly.

This all info: :(
An exception was thrown: "IronPython.Runtime.Exceptions.TypeErrorException" in Microsoft.Dynamic.dll
An unhandled exception of type "IronPython.Runtime.Exceptions.TypeErrorException" in Microsoft.Dynamic.dll
Additional information: expected string, got str Type

[http://pichost.org/image/TxFT7](url)

**Comment by kroitor** [comment]
You should not really call `fetch_markets` directly, the much better approach is to load markets as described in the Manual and then use the `.markets` and `.currencies` on the exchange instance.

https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

Does that solve the issue for you?

**Comment by SandersAlex** [comment]
> 
> 
> You should not really call `fetch_markets` directly, the much better approach is to load markets as described in the Manual and then use the `.markets` and `.currencies` on the exchange instance.
> 
> https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
> 
> Does that solve the issue for you?

[http://pichost.org/image/TxOAQ](http://pichost.org/image/TxOAQ)

**Comment by kroitor** [comment]
Can you copy those details by clicking "Копировать подробности" and paste them here? Is it the same text as well? If it is, then, I think I will have to install IronPython on a windows vm to test it...

**Comment by kroitor** [comment]
Also, just for the sake of experiment, let's try this:

```
import ccxt
exchange = ccxt.bittrex()
exchange.load_markets()
pprint(exchange.symbols)
```

↑ This is a complete program for launching in IronPython, make sure no other code is interfering with it. Does it throw the same exception as well?

**Comment by SandersAlex** [comment]
> 
> 
> Can you copy those details by clicking "Копировать подробности" and paste them here? Is it the same text as well? If it is, then, I think I will have to install IronPython on a windows vm to test it...

[http://pichost.org/image/TxezL](http://pichost.org/image/TxezL)
Вызвано исключение: "IronPython.Runtime.Exceptions.TypeErrorException" в Microsoft.Dynamic.dll
Дополнительные сведения: converting to unicode: need string, got bytes, произошло

**Comment by kroitor** [comment]
@SandersAlex ok, I see... I was just trying to understand which particular line in CCXT caused the exception. Will have to install IronPython to do some testing...

**Comment by SandersAlex** [comment]
> @SandersAlex ok, I see... I was just trying to understand which particular line in CCXT caused the exception. Will have to install IronPython to do some testing...

Ok. I wait you decision :)

**Comment by gelormendi** [comment]
I have the same problem. Any new about this?

**Comment by ttodua** [comment]
I suppose IronPython might no longer be needed, as ccxt has not port [for C#](https://github.com/ccxt/ccxt/issues/17953).
but if anyone has any comments, feel free to re-raise this issue.
