### ISSUE TITLE
ccxt python, hitbtc market order error

### ISSUE THREAD

**Issue by lampardlb** [ccxt/ccxt#4047]
- OS: windows
- Programming Language version: python
- CCXT version: 1.17.412
- Exchange: hitbtc
- Method: order = hitbtc.createMarketSellOrder()

whenever I execute the command, the order itself is executed, but the parsing order info process encounters an error:

File "\Python\Python37-32\lib\site-packages\ccxt\hitbtc.py", line 792, in parse_order
    cost = price * filled
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

which I think is due to unassigned variables. I'd be very grateful if a dev could kindly fix this, thanks very much!

**Comment by lampardlb** [comment]
sorry t

**Comment by lampardlb** [comment]
Sorry this works okay by using hitbtc2 instead of hitbtc. Thanks.

**Comment by lampardlb** [comment]
Thanks for the fix. To follow up: I found that by using hitbtc2: 
1. the returned order info is not unified as Binance's, specifically, the order['price'] is always None;
1. It does not have the function of moving funds between main and trading accounts, like hitbtc does, which would be a worthwhile addition imho.

**Comment by kroitor** [comment]
> the returned order info is not unified as Binance's, specifically, the order['price'] is always None;

If you can paste the verbose output of it, we can probably add a workaround for this quickly. They don't always return the price for market orders. Or there may be some issue with the parser.

> It does not have the function of moving funds between main and trading accounts, like hitbtc does, which would be a worthwhile addition imho.

See this section: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

**Comment by kroitor** [comment]
@lampardlb to paste `verbose` output: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by lampardlb** [comment]
I tried to run the verbose output but every time it kills the python IDLE (sorry I'm not a serious coder...)

**Comment by kroitor** [comment]
```Python
from pprint import pprint
import ccxt
exchange = ccxt.hitbtc2 ({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,  # required according to the Manual, which you should read first, if you haven't already
})
exchange.load_markets()


symbol = 'ETH/BTC'  # YOUR SYMBOL
amount = 123.45  # YOUR AMOUNT

exchange.verbose = True  # add this line before the call to that method

order = exchange.create_market_sell_order(symbol, amount)
pprint(order)
```

Feel free to reopen it if the above does not answer your question.

**Comment by lampardlb** [comment]
> @lampardlb anyways, if the exchange does not return the settlement price for market orders, we can't really invent it out of thin air... This is the nature of a market order, I'm afraid.

it does return, but in hitbtc orders, its contained in: order['info']['tradesReport'][0]['price'] as a string, where as in binance orders, it's in order['price'], as a float. So what I meant was whether the output format could be unified.

**Comment by kroitor** [comment]
> it does return, but in hitbtc orders, its contained in: order['info']['tradesReport'][0]['price'] as a string, where as in binance orders, it's in order['price'], as a float. So what I meant was whether the output format could be unified.

It could, if you could post your verbose output, that's the whole point of posting the above snippet ) It means: you run it and paste your output here, and we fix it ) This is an open-source collaboration )

**Comment by lampardlb** [comment]
Thanks, yes I understood. I'm really sorry that I could not run the verbose for some reason, but I ran the same sell orders on binance and hitbtc, the outputs are below. Hope this could help. I really appreciate the help and am deeply grateful for this project.

Binance:
{'info': {'symbol': 'XRPUSDT', 'orderId': 35447199, 'clientOrderId': 'whUhQRXN1G7TWTWCThGjqC', 'transactTime': 1540485334243, 'price': '0.00000000', 'origQty': '1.00000000', 'executedQty': '1.00000000', 'cummulativeQuoteQty': '0.46518000', 'status': 'FILLED', 'timeInForce': 'GTC', 'type': 'MARKET', 'side': 'SELL'}, 'id': '35447199', 'timestamp': 1540485334243, 'datetime': '2018-10-25T16:35:34.243Z', 'lastTradeTimestamp': None, 'symbol': 'XRP/USDT', 'type': 'market', 'side': 'sell', 'price': 0.46518, 'amount': 1.0, 'cost': 0.46518, 'average': 0.46518, 'filled': 1.0, 'remaining': 0.0, 'status': 'closed', 'fee': None, 'trades': None}

hitbtc:
{'id': '61f37efc4846450fb2d7d32f2467403a', 'timestamp': 1540485376885, 'datetime': '2018-10-25T16:36:16.885Z', 'lastTradeTimestamp': 1540485376885, 'status': 'closed', 'symbol': 'XRP/USDT', 'type': 'market', 'side': 'sell', 'price': None, 'amount': 1.0, 'cost': None, 'filled': 1.0, 'remaining': 0.0, 'fee': None, 'info': {'id': '66798475374', 'clientOrderId': '61f37efc4846450fb2d7d32f2467403a', 'symbol': 'XRPUSDT', 'side': 'sell', 'status': 'filled', 'type': 'market', 'timeInForce': 'FOK', 'quantity': '1', 'cumQuantity': '1', 'createdAt': '2018-10-25T16:36:16.885Z', 'updatedAt': '2018-10-25T16:36:16.885Z', 'tradesReport': [{'id': 386392621, 'quantity': '1', 'price': '0.4645', 'fee': '0.0004645', 'timestamp': '2018-10-25T16:36:16.885Z'}]}}

**Comment by lampardlb** [comment]
I've now done the verbose output as well. Thanks very much again.
hitbtc:

Request: POST https://api.hitbtc.com/api/2/order {'Authorization': 'Basic NmJlNDMyYWZjMzBkNDJlNGQxYWVkMzUwZjU4MGY1ODY6MGQyM2YyNjUzYmVkOTRiZWE4ZjdjNTcwNDQxNjlkNzM=', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} {"clientOrderId":"fe36aa5e190149bf9985fb673bbb2ea0","symbol":"XRPUSDT","side":"sell","quantity":"1","type":"market","timeInForce":"FOK"}

Response: POST https://api.hitbtc.com/api/2/order 200 {'Server': 'nginx', 'Date': 'Thu, 25 Oct 2018 16:41:44 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '392', 'Connection': 'keep-alive'} {"id":"66799540063","clientOrderId":"fe36aa5e190149bf9985fb673bbb2ea0","symbol":"XRPUSDT","side":"sell","status":"filled","type":"market","timeInForce":"FOK","quantity":"1","cumQuantity":"1","createdAt":"2018-10-25T16:41:44.780Z","updatedAt":"2018-10-25T16:41:44.780Z","tradesReport":[{"id":386394956,"quantity":"1","price":"0.4644","fee":"0.0004644","timestamp":"2018-10-25T16:41:44.780Z"}]}
{'amount': 1.0,
 'cost': None,
 'datetime': '2018-10-25T16:41:44.780Z',
 'fee': None,
 'filled': 1.0,
 'id': 'fe36aa5e190149bf9985fb673bbb2ea0',
 'info': {'clientOrderId': 'fe36aa5e190149bf9985fb673bbb2ea0',
          'createdAt': '2018-10-25T16:41:44.780Z',
          'cumQuantity': '1',
          'id': '66799540063',
          'quantity': '1',
          'side': 'sell',
          'status': 'filled',
          'symbol': 'XRPUSDT',
          'timeInForce': 'FOK',
          'tradesReport': [{'fee': '0.0004644',
                            'id': 386394956,
                            'price': '0.4644',
                            'quantity': '1',
                            'timestamp': '2018-10-25T16:41:44.780Z'}],
          'type': 'market',
          'updatedAt': '2018-10-25T16:41:44.780Z'},
 'lastTradeTimestamp': 1540485704780,
 'price': None,
 'remaining': 0.0,
 'side': 'sell',
 'status': 'closed',
 'symbol': 'XRP/USDT',
 'timestamp': 1540485704780,
 'type': 'market'}

binance:

Request: POST https://api.binance.com/api/v3/order {'X-MBX-APIKEY': 'UsEAl4Avz0hWSsgbvVCniB7KQ9WvRmnojmiWURqNjyHcq9RzrbzxBJWy981VWw8A', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} timestamp=1540485792308&recvWindow=5000&symbol=XRPUSDT&quantity=1&type=MARKET&side=SELL&newOrderRespType=RESULT&signature=dcc952707b1c0fa7a14725460eb58074f35845567f8b87698ec36256b0f0680b

Response: POST https://api.binance.com/api/v3/order 200 {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Thu, 25 Oct 2018 16:43:12 GMT', 'Server': 'nginx', 'Content-Encoding': 'gzip', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 52e28d5e88c0c05ef6f40e101df14cab.cloudfront.net (CloudFront)', 'X-Amz-Cf-Id': 'mnseaVOvJPnImg8MSEjbhTWrgZnPrA2qhvwXbfNUZ3xQdvTmWE72Fg=='} {"symbol":"XRPUSDT","orderId":35448136,"clientOrderId":"z3bQBr0Vz58ZxU8soe1wMx","transactTime":1540485792626,"price":"0.00000000","origQty":"1.00000000","executedQty":"1.00000000","cummulativeQuoteQty":"0.46460000","status":"FILLED","timeInForce":"GTC","type":"MARKET","side":"SELL"}
{'amount': 1.0,
 'average': 0.4646,
 'cost': 0.4646,
 'datetime': '2018-10-25T16:43:12.626Z',
 'fee': None,
 'filled': 1.0,
 'id': '35448136',
 'info': {'clientOrderId': 'z3bQBr0Vz58ZxU8soe1wMx',
          'cummulativeQuoteQty': '0.46460000',
          'executedQty': '1.00000000',
          'orderId': 35448136,
          'origQty': '1.00000000',
          'price': '0.00000000',
          'side': 'SELL',
          'status': 'FILLED',
          'symbol': 'XRPUSDT',
          'timeInForce': 'GTC',
          'transactTime': 1540485792626,
          'type': 'MARKET'},
 'lastTradeTimestamp': None,
 'price': 0.4646,
 'remaining': 0.0,
 'side': 'sell',
 'status': 'closed',
 'symbol': 'XRP/USDT',
 'timestamp': 1540485792626,
 'trades': None,
 'type': 'market'}

**Comment by kroitor** [comment]
Oh... please, when someone posts a link to answer your question, you should first go read that link VERY-VERY CAREFULLY. Don't ever post your api keys again (i've edited your snippet above), please, go and reset that key (delete it and create a new one for your own safety and always remove your keys from the output, as described in that doc that you should've read in the first place).

**Comment by kroitor** [comment]
Thx for the output and for your involvement anyways, we'll add a workaround for HitBTC shortly.

**Comment by lampardlb** [comment]
> Oh... please, when someone posts a link to answer your question, you should first go read that link VERY-VERY CAREFULLY. Don't ever post your api keys again (i've edited your snippet above), please, go and reset that key (delete it and create a new one for your own safety and always remove your keys from the output, as described in that doc that you should've read in the first place).

Sorry for the hustle caused, I'm an idiot... Thanks for your help.

**Comment by kroitor** [comment]
@lampardlb np, but you should learn to be careful when dealing with crypto ) It's easy to lose money on the internet and crypto makes it even easier. Hopefully, you don't make that mistake again ) It's your money after all )

**Comment by lampardlb** [comment]
> @lampardlb np, but you should learn to be careful when dealing with crypto ) It's easy to lose money on the internet and crypto makes it even easier. Hopefully, you don't make that mistake again ) It's your money after all )

Yes, lesson learnt. Thanks.

**Comment by kroitor** [comment]
> did i do anything wrong please?

Nope, that's my bad, a minor leftover in the `parseTrade()` method. My apologies. If you update once again to 1.17.419 (5-10 minutes for the build to arrive) – that will be fixed as well. Apart from that, we don't expect any more issues, but still will be very thankful if you report back, whether it works for you or not.

**Comment by lampardlb** [comment]
Yes it's working like a charm, thank you so much!

**Comment by lampardlb** [comment]
@kroitor sorry to bother you again, but could you kindly fix the same issue for huobipro please? The verbose is below. I'm posting here because it's the same issue , but please let me know if I should open a new thread. Many thanks again in advance!

Request: GET https://api.huobi.pro/v1/account/accounts? {'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.huobi.pro/v1/account/accounts? {'Date': 'Sat, 27 Oct 2018 21:48:09 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d63b0bbfc72adbe53a7e47f35ce8ed42b1540676889; expires=Sun, 27-Oct-19 21:48:09 GMT; path=/; domain=.api.huobi.pro; HttpOnly', 'X-Application-Context': 'dawn-broker-pro:default,prd:8080', 'X-Request-ID': '9280bf4a49b61f8914b0a456723f0909', 'Content-Encoding': 'gzip', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '47085d7ea8e3bc38-LHR'} {"status":"ok","data":[{"id":2021825,"type":"spot","subtype":"","state":"working"}]}

Request: POST https://api.huobi.pro/v1/order/orders/place?A {'Content-Type': 'application/json', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} {"account-id":2021825,"amount":"0.15","symbol":"btcusdt","type":"sell-market"}

Response: POST https://api.huobi.pro/v1/order/orders/place?{'Date': 'Sat, 27 Oct 2018 21:48:10 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d63b0bbfc72adbe53a7e47f35ce8ed42b1540676889; expires=Sun, 27-Oct-19 21:48:09 GMT; path=/; domain=.api.huobi.pro; HttpOnly', 'X-Application-Context': 'dawn-broker-pro:default,prd:8080', 'X-Request-ID': 'c4ce6d6ba4c5859b4778bfe5f086f016', 'Content-Encoding': 'gzip', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '47085d820b81bc38-LHR'} {"status":"ok","data":"15503203604"}
{'amount': 0.15,
 'cost': None,
 'datetime': '2018-10-27T21:48:10.350Z',
 'fee': None,
 'filled': None,
 'id': '15503203604',
 'info': {'data': '15503203604', 'status': 'ok'},
 'lastTradeTimestamp': None,
 'price': None,
 'remaining': None,
 'side': 'sell',
 'status': None,
 'symbol': 'BTC/USDT',
 'timestamp': 1540676890350,
 'trades': None,
 'type': 'market'}

**Comment by kroitor** [comment]
> could you kindly fix the same issue for huobipro please?

Yes, will do that shortly.

> I'm posting here because it's the same issue , but please let me know if I should open a new thread. 

We can keep it within this thread, I do receive and read every message on CCXT GitHub whether the issue is closed or still open, so, no need for a new thread, I think. ) Will let you know, once it's there...

**Comment by lampardlb** [comment]
May I kindly enquire about the huobipro fix please? Thanks.

**Comment by kroitor** [comment]
@lampardlb will add a workaround for it as well, hopefully, today.

**Comment by kroitor** [comment]
@lampardlb after looking closely into it, the issue with huobipro is that they don't return any price for ф market order immediately from their createOrder endpoint (`order/orders/place`), so, in order to get the actual executed price, you will have to fetch that order by id https://github.com/ccxt/ccxt/wiki/Manual#querying-orders

Let me know if I missed something.

**Comment by lampardlb** [comment]
@kroitor Thank you so much for your time. I see, I'll update my codes accordingly. Cheers.
