### ISSUE TITLE
[ASK]Transfer coin from binance to indodax

### ISSUE THREAD

**Issue by ardialamwijaya** [ccxt/ccxt#4052]
- OS: Win 10
- Programming Language version: PHP
- CCXT version: 1.17
- Exchange: Binance and Indodax

Hi Kroitor, 
I would like to know, is it possible to transfer BTC from Binance to Indodax? 

Thx.

**Comment by kroitor** [comment]
Hi! 

> I would like to know, is it possible to transfer BTC from Binance to Indodax?

Sure! You can do that with the `withdraw` method of Binance, more about it in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#withdraw. I'd recommend to read it from top to bottom, as it has all the explanations and quite a lot of useful info that will save you a ton of time (trust me).

Hope this answers your questions, feel free to reopen it if not )
