### ISSUE TITLE
EOS transfer from cobinhood to poloniex ?

### ISSUE THREAD

**Issue by xCuri0** [ccxt/ccxt#4053]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: elementary OS Juno
- Programming Language version: Python 3.6
- CCXT version: Latest from pip
- Exchange: cobinhood/poloniex
- Method: fetchDepositAddress/withdraw

```
    try:
        deposit = _exchange2.fetchDepositAddress(coin)
    except ccxt.InvalidAddress:
        deposit = _exchange2.createDepositAddress(coin)
    print(deposit)
    try:
        _exchange1.withdraw(coin, _exchange1.fetch_balance()[coin]['free'], deposit['address'], deposit['tag'])
    except (KeyError, TypeError):
        _exchange1.withdraw(coin, _exchange1.fetch_balance()[coin]['free'], deposit['address'])
```

```
ccxt.base.errors.ExchangeError: cobinhood {"success":false,"error":{"error_code":"invalid_address"},"request_id":"c957e72e5b3dc6c3"}
```

**Comment by xCuri0** [comment]
@kroitor poloniex seems to return an incorrect deposit ```'currency': 'EOS', 'address': 'dce9d30102dec67f', 'tag': None,```. The memo should be in tag and the address (poloniexeos1) should be in address

**Comment by kroitor** [comment]
@xCuri0 can you paste your verbose output of the fetchDepositAddress call? Just to make sure we do proper parser edits.

**Comment by xCuri0** [comment]
@kroitor 
```
Request: POST https://poloniex.com/tradingApi {'Content-Type': 'application/x-www-form-urlencoded', 'Key': 'removed', 'Sign': 'removed', 'User-Agent': 'python-requests/2.20.0', 'Accept-Encoding': 'gzip, deflate'} command=returnDepositAddresses&nonce=1540618559554

Response: POST https://poloniex.com/tradingApi 200 {'Date': 'Sat, 27 Oct 2018 05:36:01 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=dee64a4da575c8c7ae9a9810103c482201540618560; expires=Sun, 27-Oct-19 05:36:00 GMT; path=/; domain=.poloniex.com; HttpOnly', 'Cache-Control': 'private', 'Content-Encoding': 'gzip', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '4702cd709b657f31-CMB'} {"DOGE":"D8am8qNrGybr1gN2mACZKydaiJq52A4YuD","EOS":"dce9d30102dec67f","ETC":"0xeafbc400b65d9fcd3695ba0a357f78264491c1f0","GNT":"0xf3a3a2fb04d70442d03c26ae676c623eecfb659f","USDT":"1GtzWWNCpBBC2is3LVMYZ4poZrrnyFm1vD"}
{'currency': 'EOS', 'address': 'dce9d30102dec67f', 'tag': None, 'info': {'DOGE': 'D8am8qNrGybr1gN2mACZKydaiJq52A4YuD', 'EOS': 'dce9d30102dec67f', 'ETC': '0xeafbc400b65d9fcd3695ba0a357f78264491c1f0', 'GNT': '0xf3a3a2fb04d70442d03c26ae676c623eecfb659f', 'USDT': '1GtzWWNCpBBC2is3LVMYZ4poZrrnyFm1vD'}}
```

**Comment by xCuri0** [comment]
@kroitor tried withdraw using the function to poloniex. but transaction didn't go and it shows as invalid
![error](https://user-images.githubusercontent.com/29529557/47600327-44cbb200-d9dd-11e8-820e-073b8b8f54e1.png)

**Comment by kroitor** [comment]
@xCuri0 however, the address and the memo are both ok, is there any other info available on the actual reason of failure? Cobinhood requires 2fa and a standalone call to an implicit method for confirming the transaction, have you sent the request to it? Was it successful? 

- https://cobinhood.github.io/api-public/#create-withdrawal

> Response
> 2fa: object
> token: JWT for /v1/account/confirm_two_factor_authentication [POST]
> string
> type: 2FA type
> enum [totp, sms, none]

**Comment by kroitor** [comment]
@xCuri0 can you reach out to cobinhood tech support for them to explain the confirmation process? They don't have it documented, unfortunately. The general approach is to take their totp token and use it to generate the JWT with a signature inside it and submit that to their account/confirm_two_factor_authentication endpoint. However, because it's not documented it's hard to tell at this point how to submit it properly... At this point, without getting any word from cobinhood, the only thing left is to do a bit of experimenting and reverse-engineering. Your help with that would be very much appreciated. If you find out more info from cobinhood, please, let us know.

**Comment by xCuri0** [comment]
@kroiter I will try

**Comment by kroitor** [comment]
@xCuri0 the reverse-engineering can be done if you use web-inspector against their website to see how the twofa is submitted in XHR.

**Comment by xCuri0** [comment]
@kroitor I could but I can't currently as the transaction shows as invalid and the b
