### ISSUE TITLE
New exhange : COSS

### ISSUE THREAD

**Issue by centdix** [ccxt/ccxt#4059]
Hi, please add support for COSS.

Website : https://www.coss.io/
API doc : https://api.coss.io/v1/spec

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/2122

**Comment by kroitor** [comment]
Good news! 

The COSS exchange has been integrated and listed under certified exchanges in CCXT 1.18.52+. 

Please, feel free to test it and let us know if you find any issues or inconsistencies. All feedback is welcome, we will be happy to answer your questions!
