### ISSUE TITLE
Rate limit on Binance's OpenOrders

### ISSUE THREAD

**Issue by presence35** [ccxt/ccxt#4060]
Hi.  I'm getting the warning about $symbols being empty. Even when I turn on rate limiting it won't work. If I manually call the native /v3/openOrders function using cUrl I get the orders 100% of the time....even if I call it more than once very 200 seconds.  Am I missing something? Thanks.

- OS: linux
- Programming Language version: PHP
- CCXT version: 2 weeks old
- Exchange: binance
- Method: fetchOpenOrders()

**Comment by kroitor** [comment]
> I'm getting the warning about $symbols being empty.

Can you please post your code to reproduce it (make it a short but a complete snippet) and your verbose request/response (without your keys, of course) according to this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

> Am I missing something?

https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

Markets (and symbols) should have been preloaded automatically, so, if they are empty in your case, then we definitely need to see the code.

```PHP
<?php

$root = dirname (dirname (dirname (__FILE__)));

include $root . '/ccxt.php';

date_default_timezone_set ('UTC');

$exchange = new \ccxt\binance (array (
    'verbose' => true, // for debugging
    'timeout' => 30000, // just in case
    'apiKey' => 'YOUR_API_KEY',
    'secret' => 'YOUR_SECRET',
    'enableRateLimit' => true, // required by the Manual
));

try {

    $symbol = 'ETH/BTC';
    $result = $exchange->fetch_open_orders ($symbol);

    var_dump ($result);

} catch (\ccxt\NetworkError $e) {
    echo '[Network Error] ' . $e->getMessage () . "\n";
} catch (\ccxt\ExchangeError $e) {
    echo '[Exchange Error] ' . $e->getMessage () . "\n";
} catch (Exception $e) {
    echo '[Error] ' . $e->getMessage () . "\n";
}

?>
```

**Comment by presence35** [comment]
//I use this as a way to check when orders have filled. I get the open orders, save it to a file, and the next time I run the function if anything has changed I process it.

$exchange = new \ccxt\binance (array (
				'apiKey' => xx,
				'secret' => yy,
				'enableRateLimit' => false (even when true it fails),
			));
	
			//Get orders from the file that was saved during previous call
			$orders = json_decode(file_get_contents('binance.txt'),true);
	
//I have about 20 orders and this always works perfectly, no rate limit issues.
foreach($orders as $o) {
			$order = $exchange->fetchOrder($o['orderId'],$o['symbol']);
			.....
}

//Then I run this at the end of processing those orders.  I had to revert to an unrelated class that uses simple cUrl 
			if($e == 'Binance') {
				//I don't know why CCXT can't get this properly without a rate limit error.
				$binance = new Binance ($API,$Secret);
				$orders = $binance->openOrders();
			} else
				$orders = $exchange->fetchOpenOrders(); //This works for other exchanges

//Save 'em
	file_put_contents($filename,json_encode($orders));

**Comment by presence35** [comment]
Anyway, please don't spent more than a few seconds on this, it's not a huge priority.  Thanks for your efforts so far.

**Comment by ttodua** [comment]
I assume this issue is fixed in recent version of CCXT, as this is 4 years old topic and it was fixed a long ago.
if anyone has any similar issue, let us know details.
