### ISSUE TITLE
OKEX v3 update

### ISSUE THREAD

**Issue by pkoukk** [ccxt/ccxt#4063]
okex update api version to V3,here is new api doc
 https://www.okex.com/docs/en/

**Comment by gudlc** [comment]
I apparently can't authenticate on OKEx through ccxt and I don't know why, it raises this exception:
ccxt.base.errors.AuthenticationError: okex {"result":false,"error_code":10007}
Is it due to the API update ? My keys are new ones.

**Comment by kroitor** [comment]
@gudlc 

> Is it due to the API update ? 

Nope, it's not.

In order to tell the exact reason, we need the following:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ

**Comment by kroitor** [comment]
@gudlc one common pitfall is using login password instead of trading password for OKEX, so, you might want to check that as well.

**Comment by gudlc** [comment]
Thanks @kroitor, this password is the Passphrase that I created along with the API. I really can't understand where's the problem with my code as I'm really used to CCXT, already using it for 5 other exchanges and never got any problem like this one.

**Comment by kroitor** [comment]
@gudlc in order to help you, we need you to provide the following info, precisely: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue, namely, need your version of CCXT, your programming language version, and your verbose request/response (without your keys, of course). Can you post it here?

**Comment by kroitor** [comment]
@gudlc also, jfyi, it is required to enable at least some rate-limiting, as decribed in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

**Comment by liberman08** [comment]
@kroitor I'm facing the same issue. I've contacted Okex support and it seems that the problem is using V3 api key with V1 api (ccxt implement V1 api). V1 api key creation is not supported anymore. It looks like at the moment that ccxt is not compatible with okex untill ccxt will implement V3 api.  Is there an estimation for V3 implementation?
Thanks for your great work!

**Comment by kroitor** [comment]
@liberman08 thx for reporting! Can't promise it unfortunately, but hope to do v3 ASAP. Will let you know once it's there, of course.

**Comment by joethong** [comment]
OKEX made a total upgrade to v3 few days ago..  This is actually quite important.

**Comment by GenesisGupta** [comment]
> @liberman08 thx for reporting! Can't promise it unfortunately, but hope to do v3 ASAP. Will let you know once it's there, of course.

Hi Kroitor , i would like to know if Okex V3 has been updated and we can use the same to trade it via CCXT

**Comment by kroitor** [comment]
@GenesisGupta the OKEX v3 is currently not implemented in CCXT yet, but we have some sample implementations here: https://github.com/ccxt/ccxt/pull/4186 (not tested). We will add the "official" implementation of OKEX v3 as soon as we can.

**Comment by nbouscal** [comment]
OKEx has just announced end of life for V1 websocket API on Feb 20. They didn't mention the REST API, but reasonable to think it might follow soon after. (Not trying to rush you, just a heads up. Thanks for all your work @kroitor.)

https://support.okex.com/hc/en-us/articles/360021935351

**Comment by kroitor** [comment]
@nbouscal thx for the update! We will do our best to move to v3 before Feb 20.

**Comment by sushiparlour** [comment]
@kroitor Hi - just curious on the timeline on this? Thanks!

**Comment by luopeng36** [comment]
@kroitor Hi - just curious on the timeline on this? Thanks!

**Comment by nulldust** [comment]
just curious on the timeline on this? Thanks!

**Comment by nulldust** [comment]
> @nbouscal thx for the update! We will do our best to move to v3 before Feb 20.

How did things go?

**Comment by NeverLanded** [comment]
still waiting for the V3

**Comment by fogflute** [comment]
WAIT FOR OKEX V3 UPDATE

**Comment by fogflute** [comment]
> @nbouscal thx for the update! We will do our best to move to v3 before Feb 20.

thanks for your great work!

**Comment by rkingy** [comment]
I've created a pull request here for some work I did on this. Have only tested the fees end point but shouldn't take much to get the rest of the functionality going. 
https://github.com/ccxt/ccxt/pull/4802

**Comment by sacummings91** [comment]
@rkingy Is there anything I/We can do to expedite this process?

**Comment by rkingy** [comment]
@sacummings91  Sorry man, I've actually been completely roadblocked from working on this recently. If you need it asap I'd recommend you grab what I've started on in pull request 4802 and create a new pull request.

I was thinking also that as I haven't really tested any of the other functionality it would be a bit average committing this update to master branch in such a limited state.

**Comment by sacummings91** [comment]
@rkingy No problem! I'll take a look at it and see what I can do

**Comment by bnskumar** [comment]
If V3 updated.  

I keep getting this error:

ccxt.base.errors.ExchangeError: okex {"result":false,"error_code":20024}

--**Code**:

exchange = ccxt.okex({
'apiKey': '***',
'secret': '***',
'enableRateLimit': True,
})

instrument='BTC/USD'
ord_qty=0.002

exchange.create_limit_buy_order(instrument,{'amount':ord_qty, 'price':3950, 'contract_type': 'next_week'})

**Comment by saurabBajgain** [comment]
can i still use:- (1) https://www.okex.com/api/v1/userinfo.do  ?
will it work???
in my case i am getting :-{"result":false,"error_code":10007} as a responce.
(2) https://www.okex.com/v2/spot/markets/products :- this one works for me with responce of 628 data.
