### ISSUE TITLE
okcoinusd, allcoin: usage of null array in for loop

### ISSUE THREAD

**Issue by WoK-E** [ccxt/ccxt#4064]
- OS: all
- Programming Language version: php
- CCXT version: 1.17.433
- Exchange: ~~okcoinusd~~, allcoin
- Method: fetch_markets()

~~PHP Warning:  count(): Parameter must be an array or an object that implements Countable in ...../php/okcoinusd.php on line 334~~
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in ...../php/allcoin.php on line 66

When the exchange returns no markets, the for loop fails.
I've seen it happening when the host cannot be resolved (allcoin)~~, and when the exchange returns a 404 error (okcoinusd)~~
Seems like allcoin is down, ~~and okcoinusd has changed its endpoints~~

Edit regarding striketrough'd items:
okcoinusd works fine with PHP 7.2.11-2+0~20181015120801.9+stretch~1.gbp8105e0

**Comment by davemg3** [comment]
- On 1.17.465 Php version, i got successul response from okcoinusd, maybe u should give it a try again
- About AllCoin, seems they have new endpoint since July : https://www.allcoin.ca/Api_Order/ticker?symbol=ltc2btc ( even still some availibility issue)

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/issues/2962
