### ISSUE TITLE
ACX no fetch_orders function in Python

### ISSUE THREAD

**Issue by stevexiong77** [ccxt/ccxt#4068]
OS: Windows 10 pro 64bit
Programming Language version: Python v3.7
CCXT version: 1.17.436
Exchange: ACX
Method: fetch_orders

Currently, there is no fetch_orders private function for ACX in Python. Can you get it implemented so that I can get list of open/closed/cancelled orders? Assume returned result include Order ID, which I can use to call function e.g. cancel_order.

ACX API v2 does support Get Orders function
https://acx.io/documents/api_v2#!/orders/GET_version_orders_format

Alternatively, is there an existing private function I can call to get list of Open orders including Order ID?

**Comment by kroitor** [comment]
@stevexiong77 

Yes, we can, as answered here: https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar
In the meantime, your contributions are welcome, please read this doc carefully, if you want to give it a try: 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#transpiled-generated-files
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

> Alternatively, is there an existing private function I can call to get list of Open orders including Order ID?

Yes, there is, you can do that out of the box with implicit methods, as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

```Python
mbp:ccxt igorkroitor$ python3
Python 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> acx = ccxt.acx()
>>> [print(method) for method in dir(acx)]
  ...
 'privateGetOrder',
 'privateGetOrders',
...
 'privatePostOrderDelete',
 'privatePostOrders',
 'privatePostOrdersClear',
 'privatePostOrdersMulti',
 ...
 'private_get_order',
 'private_get_orders',
  ...
 'private_post_order_delete',
 'private_post_orders',
 'private_post_orders_clear',
 'private_post_orders_multi',
  ...
```

Hope this answers your question.

**Comment by kroitor** [comment]
Feel free to reopen it if needed, we will add the unified wrappers to it hopefully soon.

**Comment by stevexiong77** [comment]
Having trouble to use the privateGetOrders method.

import ccxt

exchange = ccxt.acx ({
  'enableRateLimit': True,
  'apiKey': '[API key]',
  'secret': '[Secret key]',
})

orders = exchange.privateGetOrders()
print(orders)

**Get the following error:**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "CCXT_ACX_Test.py", line 115, in <module>
    orders = exchange.privateGetOrders()
  File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 362, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 359, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 447, in fetch
    self.handle_rest_errors(e, response.status_code, http_response, url, method)
  File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 469, in handle_rest_errors
    self.raise_error(error, url, method, exception if exception else http_status_code, response)
  File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 344, in raise_error
    raise exception_type(output)
ccxt.base.errors.ExchangeNotAvailable: acx https://acx.io/api/api/v2/orders.json?access_key=[]&tonce=1540962516822&signature=[] GET 400 Client Error: Bad Request for url: https://acx.io/api/api/v2/orders.json?access_key=[]&tonce=1540962516822&signature=[] {"error":{"code":1001,"message":"market is missing, market does not have a valid value"}}

**Comment by stevexiong77** [comment]
Also, tried the following code:

import ccxt

exchange = ccxt.acx ({
  'enableRateLimit': True,
  'apiKey': '[API key]',
  'secret': '[Secret key]',
})


symbol = 'BTC/AUD'
orders = exchange.privateGetOrders(symbol)
print(orders)

**Get the following error:**

Traceback (most recent call last):
  File "CCXT_ACX_Test.py", line 115, in <module>
    orders = exchange.privateGetOrders(symbol)
  File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 362, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 358, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "C:\Program Files\Python37\lib\site-packages\ccxt\acx.py", line 373, in sign
    request = '/api' + '/' + self.version + '/' + self.implode_params(path, params)
  File "C:\Program Files\Python37\lib\site-packages\ccxt\base\exchange.py", line 667, in implode_params
    string = string.replace('{' + key + '}', str(params[key]))
TypeError: string indices must be integers

**Comment by stevexiong77** [comment]
Thanks again, I figured out params for privateGetOrders method.

Below is my working code;


params = {
    'market':'xrpaud',
}
orders = exchange.privateGetOrders(params)
pprint(orders)
