### ISSUE TITLE
request timed out 

### ISSUE THREAD

**Issue by aimdreamboy** [ccxt/ccxt#4070]
ATTENTION!!!

code:
 let huobi = new ccxt.huobipro({
        verbose: true,
        proxy: 'https://crossorigin.me/'
    })

- Exchange:huobipro\bitfinex\OKEX...

problem：

(node:3246) UnhandledPromiseRejectionWarning: Error: huobipro GET https://crossorigin.me/https://api.huobi.pro/v1/common/symbols request timed out (10000 ms)
    at timeout.catch.e (@/node_modules/ccxt/js/base/Exchange.js:436:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3246) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3246) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

but
let kraken = new ccxt.kraken()

is work!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:mac
- Programming Language version:
- CCXT version:the last
- Exchange:huobipro\bitfinex\OKEX...
- Method:

thanks

**Comment by kroitor** [comment]
I guess you should forward this question to the CORS proxy server that you use (crossorigin.me). Either don't use it or check your connectivity with it, if you're going to keep it. Hope this answers your question.

**Comment by aimdreamboy** [comment]
use code:
let huobi = new ccxt.huobipro({
verbose: true,
})

Exchange:huobipro\bitfinex\OKEX...

the same err

**Comment by kroitor** [comment]
@aimdreamboy 

```JavaScript

'use strict';

const ccxt = require ('ccxt')
const exchange = new ccxt.huobipro ({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': true, // required by the Manual which you should read from top to bottom
})

;(async () => {
    try {
        await exchange.loadMarkets ();
    } catch (e) {
        console.log ('Could not load markets')
        console.log (e.constructor.name)
        console.log (e)
        process.exit ();
    }
    try {
        const ticker = await this.fetchTicker ('ETH/BTC');
        console.log (ticker)
    } catch (e) {
        console.log ('Could not fetch the ticker')
        console.log (e.constructor.name)
        console.log (e)
        process.exit ();
    }
}) ()
```

https://github.com/ccxt/ccxt/tree/master/examples

**Comment by aimdreamboy** [comment]
Thanks for your reply

run equest timed out

Could not load markets
RequestTimeout
{ Error: huobipro GET https://api.huobi.pro/v1/common/symbols request timed out (10000 ms)
    at timeout.catch.e (@/node_modules/ccxt/js/base/Exchange.js:436:27) constructor: [Function: RequestTimeout] }

I can open  https://api.huobi.pro/v1/common/symbols  with a browser

**Comment by aimdreamboy** [comment]
node -v --> v11.0.0

ccxt version  -->1.17.437
