### ISSUE TITLE
Unable to place stop limit order on hitbtc api thorough ccxt

### ISSUE THREAD

**Issue by gj315** [ccxt/ccxt#4077]
{ exchange: 'HitBTC',
  symbol: 'XRP/BTC',
  type: 'stopLimit',
  side: 'sell',
  amount: '85.76591382197805',
  price: '0.00006389',
  stopPrice: '[stopPrice: xxxx, 'stop': 'loss']' }

I am getting this as error
hitbtc2 {"error":{"code":10001,"message":"\"price\" is required","description" }}

**Comment by kroitor** [comment]
@gj315 can you follow these guides precisely: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue (literally, to each particular word) ? We need your code to reproduce the issue and your verbose request/response without the keys. Follow those guides to make it all readable, plz. Standing by for a followup from you.
