### ISSUE TITLE
How do I add api keys?

### ISSUE THREAD

**Issue by chovy** [ccxt/ccxt#4078]
I want to get a list of my trades from a few apis I have api keys for, but I don't see in the readme how to authenticate with an api given an api key.

Is this method and how to pass keys documented somewhere?

**Comment by kroitor** [comment]
> Is this method and how to pass keys documented somewhere?

Yes, and the link to it is placed in multiple places on our GitHub page, not really sure how you could miss it, but here it is again:

- https://github.com/ccxt/ccxt/wiki/Manual#authentication
- https://github.com/ccxt/ccxt/wiki/Manual#api-keys-setup

I really recommend to read the entire Manual from top to bottom, it will help save you a ton of time, trust me: https://github.com/ccxt/ccxt/wiki/

Hope this answers your question, let us know if you have any difficulties with it. Closing this for now if you don't mind. Feel free to reopen it if needed.
