### ISSUE TITLE
Workflow to add exchange functions to integration

### ISSUE THREAD

**Issue by milesalex** [ccxt/ccxt#4088]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: MacOS
- Programming Language version: 8.11.1
- CCXT version: 1.17.449
- Exchange: Coinbase
- Method: `fetchMyTrades`

---

Hello,

I'm trying to add `fetchMyTrades` to the coinbase integration but I can't seem to get the tests to run and or figure out the workflow for testing the function

When running the js tests for coinbase it's continually skipped

```
➜  ccxt git:(master) ✗ yarn fast-test coinbase
yarn run v1.9.4
$ node run-tests --js coinbase
Testing { exchanges: ["coinbase"], symbol: "all", keys: { '--js': true, '--php': false, '--python': false, '--python2': false, '--python3': false } } (run-tests.js:235)
[100%] Testing coinbase [Skipped] (testExchange @ run-tests.js:152)
WARN ["coinbase"] (run-tests.js:252)
All done, 1 warnings (run-tests.js:256)
✨  Done in 0.40s.
```

Sorry for the noob questions, but this seems like something that we can add to the docs... Potentially a tutorial for adding and testing an exchange. I saw coding best practices, but not workflow suggestions.

cc: @buddylindsey who worked on the original coinbase integration. What was your testing workflow?

**Comment by buddylindsey** [comment]
@milesalex TBH I didn't run unit tests for coinbase. I haven't dug into the tests in ccxt as to how they work. I just call the API directly and change code until it all works as expected. All the exchange API's I have worked with never work fully as documented so I don't try to dev much based solely on the docs then agaist the API. I just write some stuff and call the API from the first time I run.

As to a work flow. I have a `runner.js` that I use to test. I have a lot of stuff in it as I don't ever delete anything from it so I can test later, but here are the basics.

```
function executePromise(pr) {
	pr.then(result => {
		console.log(result)
	}).catch(error => {
		console.log(error)
	})
}
var coinbase = new ccxt.coinbase({ apiKey: '', secret: '' })
executePromise(coinbase.fetchMyTrades())
```

I just expand on that as I need to.

Also once I have what I want and it "works" then I do the `npm run build` step to build the rest and modify for eslint and transpile errors. Then I submit it as a PR and @kroitor changes everything, heh, generally he tests, refactors, and adds docs to keep it up to snuff with the rest of the project.

**Comment by milesalex** [comment]
hahah yeah, I just figured that out and did the same via the examples folder. It would be nice if we could run unit tests for each function.

```js
"use strict";

// ----------------------------------------------------------------------------

const ccxt = require ('../../ccxt.js')
    , log  = require ('ololog')
    , asTable = require ('as-table').configure ({ delimiter: ' | ' })

// ----------------------------------------------------------------------------

;(async () => {

    const exchange = new ccxt.coinbase ({
        'verbose': process.argv.includes ('--verbose'),
        'timeout': 60000,
    })

    try {
        const response = await exchange.fetchTicker ('BCH/USD')
        log (response)
        log.green ('Succeeded.')

    } catch (e) {

        log.dim ('--------------------------------------------------------')
        log (e.constructor.name, e.message)
        log.dim ('--------------------------------------------------------')
        log.dim (exchange.last_http_response)
        log.error ('Failed.')
    }

}) ()
```

**Comment by kroitor** [comment]
@milesalex thx! We do have some tests here:

- https://github.com/ccxt/ccxt/tree/master/js/test
- https://github.com/ccxt/ccxt/tree/master/python/test
- https://github.com/ccxt/ccxt/tree/master/php/test

Yet we agree, that may be an incomplete set, as we're still working on them... The most developed part of the tests is in JS, but it doesn't make any significant difference, because of our multilanguage nature – in mosts cases running tests in JS should yield same results as testing those methods with Py/PHP.

@buddylindsey thx for your involvement and for the correct answer! Appreciate your help!
