### ISSUE TITLE
Implementing coinbase fetchMyTrades

### ISSUE THREAD

**Issue by milesalex** [ccxt/ccxt#4091]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Mac
- Programming Language version: Node 8
- CCXT version: Latest
- Exchange: Coinbase
- Method: fetchMyTrades

----

I'm starting to implement `fetchMyTrades` for coinbase but it's rather challenging because the api is quite different from the ccxt api. A few questions I have...

1. Where do we put the logic? SHould I get accounts in fetch my trades or pass the accountId to the fetch my trades function
2. Pagination: they give you urls for pagination in each response. How should we integrate this?

See attached PR #4092

**Comment by milesalex** [comment]
#4092

**Comment by kroitor** [comment]
Hi!

> I'm starting to implement fetchMyTrades for coinbase but it's rather challenging because the api is quite different from the ccxt api. 

Thanks for your participation, you're absolutely right, the whole point of this lib is to unify those differences in a convenient and standardized API.

> Where do we put the logic? SHould I get accounts in fetch my trades or pass the accountId to the fetch my trades function

We'd rather keep one http call per one method call, therefore, if a method requires some piece of data from another endpoint, those should be two separate methods in most cases, and the user should supply the return of the first one in the arguments to the second one. Basically, we try to keep the logic in the userland as much as possible. That is to avoid managing their requests and rate-limits (very specific to a particular task). Also explained here: https://github.com/ccxt/ccxt/issues/2836#issuecomment-388973364

> Pagination: they give you urls for pagination in each response. How should we integrate this?

Afaik, they provide those values in headers, so the user will have to take the page number from `last_response_headers` and supply it in the extra `params` override for the `fetchMyTrades` call:

- https://github.com/ccxt/ccxt/wiki/Manual#pagination
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

I suggest to move this discussion to #4092, closing this for now, if you don't mind. Will be happy to answer further questions there ) 

Thx again!
