### ISSUE TITLE
Margin Call and Liquidation for Kraken

### ISSUE THREAD

**Issue by ceaser1996** [ccxt/ccxt#4094]
How to Calculate Margin Call and Liquidation for Kraken or any exchange which supports shorting? Is there any formula or any specific method is available?
- OS: Ubuntu 
- Programming Language version: PHP 7.1
- CCXT version: 1.13
- Exchange: Kraken

**Comment by kroitor** [comment]
> Is there any formula or any specific method is available?

There's no specific formula, your available margin will depend on how the exchange engine calculates it, so, there's no universal formula for that, this isn't unified in CCXT yet, so it is usually done in exchange-specific fashion with https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods. Hope this answers the question, let us know if not.
