### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by suril10** [ccxt/ccxt#4095]
- OS: Windows 10
- Programming Language version: 3.7.0
- CCXT version: version 1.17.455
- Exchange: livecoin
- Method: exchange.withdraw()

I am trying to use the exchange.withdraw method and getting the unhashable type: 'dict' error.

code:

import ccxt

b = getattr(ccxt, 'livecoin')({'uid': 'user id',
                         'api_key': 'user api key',
                         'secret': 'secret api key',
                         })
b.load_markets()
b.withdraw('LTC', 0.15, 'address')

Error:
withdraw(self, code, amount, address, tag, params)
    562             wallet += '::' + tag
    563         request = {
--> 564             'amount': self.decimal_to_precision(amount, TRUNCATE, self.currencies[currency]['precision'], DECIMAL_PLACES),
    565             'currency': currency['id'],
    566             'wallet': wallet,

TypeError: unhashable type: 'dict'

**Comment by suril10** [comment]
I am still getting the error.

**Comment by kroitor** [comment]
@suril10 right, we have to wait till this build passes and update to CCXT 1.17.456 (should arrive in 5-10 minutes).

**Comment by kroitor** [comment]
Ok, it's there, please retry with the updated version. Let us know if you have further difficulties with it. Thx for reporting!

**Comment by suril10** [comment]
print(b.withdraw('LTC', 0.15, 'MGanpgm7sg2Ttw7R25GyNj81RYwMvYjjRR'))

c:\users\thake\appdata\local\programs\python\python37\lib\site-packages\ccxt\livecoin.py in withdraw(self, code, amount, address, tag, params)

TypeError: unhashable type: 'dict'

**Comment by kroitor** [comment]
First of, there's a typo in the code you posted above:

```Python
b = getattr(ccxt, 'livecoin')({
    'uid': 'user id',
    'api_key': 'user api key',   # ←---------------------- should be apiKey, not api_key
    'secret': 'secret api key',
})
```

Second, let's make sure that your version of ccxt is up to date:

```Python
import ccxt
# pip list might show a different version number than this line,
# so we print the actual runtime version of ccxt here
print(ccxt.__version__)  
```

↑ What does it say?

**Comment by suril10** [comment]
import ccxt
# pip list might show a different version number than this line,
# so we print the actual runtime version of ccxt here
print(ccxt.__version__)  

output:
1.17.449

I changed the api_key to apiKey but still the same thing.

**Comment by kroitor** [comment]
> 1.17.449

Looks like an old version to me. How about you? )

**Comment by suril10** [comment]
Sorry my mistake! I read it as 1.17.449! I updated it again and its working!! Sorry for the silly error. Thanks for all the help! You guys are doing a great job!
