### ISSUE TITLE
BCEX incomplete candles

### ISSUE THREAD

**Issue by davemg3** [ccxt/ccxt#4101]
- Programming Language version: PHP
- CCXT version: 1.17.459
- Exchange: bcex
- Method: FetchOHLCV

Hi, https://github.com/ccxt/ccxt/issues/1577
On CMC : 
for example, BTC/CKUSD  is around 33M$ for 24hvolume
![image](https://user-images.githubusercontent.com/32598581/47955831-fd759080-df9d-11e8-93e2-c1b74af9c1ee.png)

On CCXT:
BTC/CKUSD 1h candles will provide less than 24k$/1h-> less than 0.5M$ for 24hvolume
![image](https://user-images.githubusercontent.com/32598581/47955818-d8811d80-df9d-11e8-91eb-b8d341567b77.png)

Is it cause 1h candles are not complete as for Bithumb limitation and  so, it is needed to fetch continuously trades to build oneself periodic candles? 
(was wondering if an asterisk or sth similar could indicate when an exchange cannot build full set of data for some methods, for us to consider immediately a work around to get the desired data...for example seems here, fetching trades has to be done)

**Comment by kroitor** [comment]
Hi! 

It's basically due to the same reason as explained here: https://github.com/ccxt/ccxt/issues/3178#issuecomment-410272004

> (was wondering if an asterisk or sth similar could indicate when an exchange cannot build full set of data for some methods, for us to consider immediately a work around to get the desired data...for example seems here, fetching trades has to be done)

We will think of adding such an indication.
