### ISSUE TITLE
hitbtc balance main broken ?

### ISSUE THREAD

**Issue by asocanari** [ccxt/ccxt#4108]
Hi, it was referenced here already how to get the main balance from hitbtc, but it seems broken maybe ? 

https://github.com/ccxt/ccxt/issues/288#issuecomment-335549106

> 
> ```
> hitbtc.fetch_balance()  # returns trading account balance by default
> hitbtc.fetch_balance({'type': 'trading'})  # returns trading account balance
> hitbtc.fetch_balance({'type': 'payment'})  # returns main account balance
> ```
> 
> Please update to v.1.9.96+ in order to use that (will be available in 5 minutes).

is this functionality maybe broken ? I am trying to do 

```
        let ex = await exchange.getExchangeObject('hitbtc2');   
        balances = await ex.fetchBalance({'type': 'trading'});   
```
which works fine so far, but 

```
        let ex = await exchange.getExchangeObject('hitbtc2');   
        balances = await ex.fetchBalance({'type': 'payment'});   
```
returns 
```

(node:28915) UnhandledPromiseRejectionWarning: TypeError: this[method] is not a function
    at hitbtc2.fetchBalance (/srv/XXX/node_modules/ccxt/js/hitbtc2.js:666:43)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:28915) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28915) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

On version ccxt: '1.17.461'

Have any hint whats going wrong here ? Or do I use it wrong ?

best regards, Simon 

_Originally posted by @asocanari in https://github.com/ccxt/ccxt/issues/288#issuecomment-435658917_

**Comment by kroitor** [comment]
Hi!

> it was referenced here already how to get the main balance from hitbtc, but it seems broken maybe ?

Nope, the above examples were for hitbtc v1 (which is deprecated). 

And in your case, you're using hitbtc2 (v2). 

With v2, this should be done in the following way:

```JavaScript
let ex = await exchange.getExchangeObject('hitbtc2');  // ←-------------- v2 here
balances = await ex.fetchBalance({'type': 'account'});   
```

Hope this answers your question.

**Comment by asocanari** [comment]
Thats awesome ! Thanks a lot !

best regards, Simon
