### ISSUE TITLE
ccxt-1.17.464 okex RequestTimeout

### ISSUE THREAD

**Issue by andyesi** [ccxt/ccxt#4110]
- OS: macOS MoJave 10.14
- Programming Language version: Python
- CCXT version: ccxt-1.17.464
- Exchange: Okex

error: 
ccxt.base.errors.RequestTimeout: okex GET https://www.okex.com/v2/spot/markets/products HTTPSConnectionPool(host='www.okex.com', port=443): Max retries exceeded with url: /v2/spot/markets/products (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x102876550>, 'Connection to www.okex.com timed out. (connect timeout=10)'))

**Comment by kroitor** [comment]
Same question answered here https://github.com/ccxt/ccxt/issues/4104#issuecomment-435659141
Also, check if you can access it from a different location/under vpn/using proxy or CORS, as described in the Manual.
Hope this helps.
