### ISSUE TITLE
New Exchanges : DobiTrade

### ISSUE THREAD

**Issue by davemg3** [ccxt/ccxt#4114]
Hi,

These 2 high volume exchanges got some API docs : 

DIGIFINEX (BTC volume > 162Millions/24h)
 https://github.com/DigiFinex/api

DobiTrade (BTC volume > 285Millions/24h)
 https://api.dobitrade.com/#api_block

---addition:
IDAX( CMC BTC volume > 124Millions/24h)
https://github.com/idax-exchange/idax-official-api-docs/blob/master/open-api_en.md

**Comment by kroitor** [comment]
@davemg3 IDAX is here: https://github.com/ccxt/ccxt/issues/3406 (we usually open one request per exchange to keep discussions on their aspects apart).

**Comment by Gennttii** [comment]
Did you add Digifinex?

**Comment by Gennttii** [comment]
Looks like Digifinex has fake volume ..!

**Comment by kroitor** [comment]
@Gennttii can you please provide a bit more details, what do you mean exactly?

**Comment by Gennttii** [comment]
Look at this pair 
https://www.digifinex.com/en-ww/trade/TUSD/USDT

It says 24h volume 3458.89K USDT which means 3.4 Million USDT.

But look at the trades, last trades have been made at 10 AM, now is 3:33 PM, I made a trade at 2:30 PM, and followed the market, no trade was made since then..

**Comment by kroitor** [comment]
> But look at the trades, last trades have been made at 10 AM, now is 3:33 PM, I made a trade at 2:30 PM, and followed the market, no trade was made since then

I see several trades each minute, most recent of them "just now" and that looks normal to me...

<img width="1440" alt="Screen Shot 2019-03-17 at 19 09 35" src="https://user-images.githubusercontent.com/1294454/54494131-417f8700-48e8-11e9-8dab-3cae68830bdc.png">

Could that be due a dropped websocket connection in your browser?

**Comment by Gennttii** [comment]
there were no trades from 10 AM to 16 PM, if you think thats normal okay..

**Comment by kroitor** [comment]
> there were no trades from 10 AM to 16 PM, if you think thats normal okay..

That's interesting... I do not insist at all, could be an issue on the exchange side. But could be normal as well. Have you tried asking the exchange support about it?

**Comment by Gennttii** [comment]
![2019-03-20](https://user-images.githubusercontent.com/3110966/54679400-7584c300-4b07-11e9-8f8f-0c24a0110596.png)
Just to confirm, look at this, some trades at 7 AM all of size 116.00, then after 3 hours some trades at 10 AM, and the clock now is 11:56 AM, the volume for last 24H says 2 M, it can't be...
In Binance you have 3 or 4 M 24H volume for the same pair, but there you have trades every second..

**Comment by kroitor** [comment]
@Gennttii have you reached out to their support with that question?

**Comment by silert** [comment]
The true trading volume on DigiFinex is only 1% from reported volume according to https://www.blockchaintransparency.org/

**Comment by Gennttii** [comment]
Yes that should be true, 99 % from API, when did Digifinex start? I believe all exchanges faked volumes in their start..

**Comment by XavierXIEXIN** [comment]
Fake vol or not, 99% of the crypto exchanges are wash trading now to maintain their rank and draw more attention, the report just pointed out the most obvious ones. From what I observed, the digifinex exchange was just not wash trading constantly like others, the USDT/TUSD pair for instance, discontinuous tradings with several occasionally trades of relatively large amount could make the suspicious scene above. Anyway, an exchange with decent liquidity and API is worth adding for ccxt.

**Comment by kroitor** [comment]
DigiFinex merged: https://github.com/ccxt/ccxt/pull/4993

**Comment by VictorLux** [comment]
Hi,
Any progress on the last one, Dobitrade ? API doc could be find here : https://api.dobiexchange.com/

**Comment by kroitor** [comment]
@VictorLux it's on our list of exchanges to be integrated, however, we can't really promise an ETA due to reasons explained in the FAQ:

- https://github.com/ccxt/ccxt/wiki/FAQ#when-will-you-add-feature-foo-for-exchange-bar--whats-the-estimated-time-when-should-we-expect-this

**Comment by kroitor** [comment]
Dobitrade is closed, the website is inaccessible, and the volumes are zeroed:

- https://www.cointelligence.com/exchanges_list/dobitrade/
- https://www.coingecko.com/ru/%D0%BE%D0%B1%D0%BC%D0%B5%D0%BD/dobitrade
