### ISSUE TITLE
Bitstamp authentication and nonce error.

### ISSUE THREAD

**Issue by suril10** [ccxt/ccxt#4115]
- OS: Windows 10
- Programming Language version: Python 3.7.0
- CCXT version: 1.17.457
- Exchange: Bitstamp
- Method: fetch_deposit_address(); fetchTransactions()

I am just trying to access the transactions and also the deposit address and I am getting the authentication error and nonce error as well. This started happening for the past week. I also added rate limiter. It was working fine previously but now I am continuously getting the same error.

Code:

import ccxt

b = getattr(ccxt, 'bitstamp')({'uid': '',
                         'apiKey': '',
                         'secret': '',
                        })
b.load_markets()
b.enableRateLimiter = True
print(b.fetch_balance()['LTC'])
x = b.fetchTransactions('LTC')
for a in x:
    print('\n'+str(a))

Output:

{'free': 0.10590517, 'used': 0.0, 'total': 0.10590517}
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
~\AppData\Roaming\Python\Python37\site-packages\ccxt\base\exchange.py in fetch(self, url, method, headers, body)
    433             self.logger.debug("%s %s, Response: %s %s %s", method, url, response.status_code, headers, http_response)
--> 434             response.raise_for_status()
    435 

c:\users\thake\appdata\local\programs\python\python37\lib\site-packages\requests\models.py in raise_for_status(self)
    938         if http_error_msg:
--> 939             raise HTTPError(http_error_msg, response=self)
    940 

HTTPError: 403 Client Error: Authentication Failed for url: https://www.bitstamp.net/api/v2/user_transactions/

During handling of the above exception, another exception occurred:

ExchangeError                             Traceback (most recent call last)
<ipython-input-4-e26ffccde0fd> in <module>()
     11 #print(b.fetchOrder('2327109020'))
     12 #print(b.create_market_sell_order('LTC/USD',0.001))
---> 13 x = b.fetchTransactions('LTC')
     14 for a in x:
     15     print('\n'+str(a))

~\AppData\Roaming\Python\Python37\site-packages\ccxt\bitstamp.py in fetch_transactions(self, code, since, limit, params)
    469         if limit is not None:
    470             request['limit'] = limit
--> 471         response = self.privatePostUserTransactions(self.extend(request, params))
    472         #
    473         #     [

~\AppData\Roaming\Python\Python37\site-packages\ccxt\base\exchange.py in request(self, path, api, method, params, headers, body)
    360 
    361     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):
--> 362         return self.fetch2(path, api, method, params, headers, body)
    363 
    364     @staticmethod

~\AppData\Roaming\Python\Python37\site-packages\ccxt\base\exchange.py in fetch2(self, path, api, method, params, headers, body)
    357         self.lastRestRequestTimestamp = self.milliseconds()
    358         request = self.sign(path, api, method, params, headers, body)
--> 359         return self.fetch(request['url'], request['method'], request['headers'], request['body'])
    360 
    361     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):

~\AppData\Roaming\Python\Python37\site-packages\ccxt\base\exchange.py in fetch(self, url, method, headers, body)
    444 
    445         except HTTPError as e:
--> 446             self.handle_errors(response.status_code, response.reason, url, method, headers, http_response)
    447             self.handle_rest_errors(e, response.status_code, http_response, url, method)
    448             self.raise_error(ExchangeError, url, method, e, http_response)

~\AppData\Roaming\Python\Python37\site-packages\ccxt\bitstamp.py in handle_errors(self, httpCode, reason, url, method, headers, body)
    745                     if code == 'API0005':
    746                         raise AuthenticationError(self.id + ' invalid signature, use the uid for the main account if you have subaccounts')
--> 747                 raise ExchangeError(self.id + ' ' + body)

ExchangeError: bitstamp {"status": "error", "reason": "Invalid nonce", "code": "API0004"}

It prints the balance but other than that I cant access anything.

**Comment by kroitor** [comment]
@suril10 have you tried the same snippet with a new API keypair?

**Comment by suril10** [comment]
So do I need to generate new apis?

**Comment by kroitor** [comment]
> So do I need to generate new apis?

Yes, and you should read this: https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by suril10** [comment]
I had a mistake. I had written enableRateLimiter instead of enableRateLimit. Sorry and thanks for the help.Keep up the good work.

**Comment by kroitor** [comment]
@suril10 thx for reporting back!
