### ISSUE TITLE
Bitstamp create order limit instead of market

### ISSUE THREAD

**Issue by fedecaccia** [ccxt/ccxt#4116]
- OS: Ubuntu 16
- Programming Language version: Python3
- CCXT version: Last
- Exchange: Bitstamp
- Method: create_order

Using 
```
import ccxt
keys = ...
bitstamp = ccxt.bitstamp(keys)
client.create_order("XRP/USD", "market", "buy", 205.3388)
```

returns

{'info': {'datetime': '2018-11-05 16:16:39.532897', 'price': '0.45701', 'id': '2344851866', 'amount': '205.33880000', 'type': '0'}, 'id': '2344851866'}

when real market prices are between 0.485 and 0.486

**Comment by kroitor** [comment]
@fedecaccia need to see the verbose request/response for that call, without your keys. Basically, for market orders it should be a different endpoint, we need to make sure that it sends a proper call...

```Python
import ccxt
keys = ...
bitstamp = ccxt.bitstamp(keys)
bitstamp.load_markets()
bitstamp.verbose = True   # ←------------- add this
client.create_order("XRP/USD", "market", "buy", 205.3388)
```

**Comment by fedecaccia** [comment]
```
Request: GET https://www.bitstamp.net/api/v2/trading-pairs-info/ {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://www.bitstamp.net/api/v2/trading-pairs-info/ 200 {'Last-Modified': 'Mon, 05 Nov 2018 16:43:42 GMT', 'Cache-Control': 'max-age=0', 'Vary': 'Authorization,Accept-Language', 'Content-Type': 'application/json', 'Set-Cookie': 'visid_incap_99025=GSb+7WNgRka5nlV5b+058T1z4FsAAAAAQUIPAAAAAACMt6mLNMGfkzgUqmMFF4ZN; expires=Tue, 05 Nov 2019 10:07:00 GMT; path=/; Domain=.bitstamp.net, nlbi_99025=VfddP9OMYUVuRsjA8F1n9AAAAACtd3+7E65KrxInPgX9uwp5; path=/; Domain=.bitstamp.net, incap_ses_785_99025=W8I2YSYz7xXGKnRF+uHkCj5z4FsAAAAAL+0KL9wdY4JXuasoylmvJA==; path=/; Domain=.bitstamp.net, ___utmvmmzumyLc=KYDeXTZbDlF; path=/; Max-Age=900, ___utmvamzumyLc=ZDK\x01Zjuc; path=/; Max-Age=900, ___utmvbmzumyLc=oZv\r\n    XmyOFalp: rtD; path=/; Max-Age=900', 'Date': 'Mon, 05 Nov 2018 16:43:42 GMT', 'X-Iinfo': '9-9802477-9799976 PNNN RT(1541436221830 84) q(0 0 0 0) r(2 2) U2', 'Access-Control-Allow-Methods': 'POST, GET', 'Connection': 'keep-alive', 'transfer-encoding': 'chunked', 'Access-Control-Allow-Headers': 'x-requested-with, Content-Type, origin, accept, cache-control', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains', 'Server': 'Apache', 'X-Frame-Options': 'SAMEORIGIN', 'Access-Control-Allow-Origin': '*', 'Content-Language': 'en', 'X-CDN': 'Incapsula', 'Content-Encoding': 'gzip', 'Expires': 'Mon, 05 Nov 2018 16:43:42 GMT'} [{"base_decimals": 8, "minimum_order": "5.0 USD", "name": "LTC/USD", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "ltcusd", "description": "Litecoin / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "5.0 USD", "name": "ETH/USD", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "ethusd", "description": "Ether / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "5.0 EUR", "name": "XRP/EUR", "counter_decimals": 5, "trading": "Enabled", "url_symbol": "xrpeur", "description": "XRP / Euro"}, {"base_decimals": 8, "minimum_order": "5.0 USD", "name": "BCH/USD", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "bchusd", "description": "Bitcoin Cash / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "5.0 EUR", "name": "BCH/EUR", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "bcheur", "description": "Bitcoin Cash / Euro"}, {"base_decimals": 8, "minimum_order": "5.0 EUR", "name": "BTC/EUR", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "btceur", "description": "Bitcoin / Euro"}, {"base_decimals": 8, "minimum_order": "0.001 BTC", "name": "XRP/BTC", "counter_decimals": 8, "trading": "Enabled", "url_symbol": "xrpbtc", "description": "XRP / Bitcoin"}, {"base_decimals": 5, "minimum_order": "5.0 USD", "name": "EUR/USD", "counter_decimals": 5, "trading": "Enabled", "url_symbol": "eurusd", "description": "Euro / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "0.001 BTC", "name": "BCH/BTC", "counter_decimals": 8, "trading": "Enabled", "url_symbol": "bchbtc", "description": "Bitcoin Cash / Bitcoin"}, {"base_decimals": 8, "minimum_order": "5.0 EUR", "name": "LTC/EUR", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "ltceur", "description": "Litecoin / Euro"}, {"base_decimals": 8, "minimum_order": "5.0 USD", "name": "BTC/USD", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "btcusd", "description": "Bitcoin / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "0.001 BTC", "name": "LTC/BTC", "counter_decimals": 8, "trading": "Enabled", "url_symbol": "ltcbtc", "description": "Litecoin / Bitcoin"}, {"base_decimals": 8, "minimum_order": "5.0 USD", "name": "XRP/USD", "counter_decimals": 5, "trading": "Enabled", "url_symbol": "xrpusd", "description": "XRP / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "0.001 BTC", "name": "ETH/BTC", "counter_decimals": 8, "trading": "Enabled", "url_symbol": "ethbtc", "description": "Ether / Bitcoin"}, {"base_decimals": 8, "minimum_order": "5.0 EUR", "name": "ETH/EUR", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "etheur", "description": "Ether / Euro"}]

Request: POST https://www.bitstamp.net/api/v2/buy/market/xrpusd/ {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Content-Type': 'application/x-www-form-urlencoded'} signature=0174568ED4A09B8D2982C0B8E8D90C813F3B7271936FD0A05927552D7A5F1134&nonce=1541436222&amount=205.3388&key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Response: POST https://www.bitstamp.net/api/v2/buy/market/xrpusd/ 200 {'Last-Modified': 'Mon, 05 Nov 2018 16:43:43 GMT', 'Cache-Control': 'max-age=0', 'Vary': 'Authorization,Accept-Language', 'Content-Type': 'application/json', 'Set-Cookie': 'visid_incap_99025=GSb+7WNgRka5nlV5b+058T1z4FsAAAAAQUIPAAAAAACMt6mLNMGfkzgUqmMFF4ZN; expires=Tue, 05 Nov 2019 10:07:00 GMT; path=/; Domain=.bitstamp.net, incap_ses_785_99025=4A1daBoJ+FHGKnRF+uHkCj5z4FsAAAAAWVTAtJeudcPmt/BFzCH+ZA==; path=/; Domain=.bitstamp.net, ___utmvmmzumyLc=QzSCqSYABGk; path=/; Max-Age=900, ___utmvamzumyLc=YDx\x01RRQS; path=/; Max-Age=900, ___utmvbmzumyLc=dZn\r\n    XNXOvalc: atX; path=/; Max-Age=900', 'Date': 'Mon, 05 Nov 2018 16:43:43 GMT', 'X-Iinfo': '9-9802477-9799976 SNNN RT(1541436221830 343) q(0 0 0 0) r(5 5) U6', 'Access-Control-Allow-Methods': 'POST, GET', 'Connection': 'keep-alive', 'transfer-encoding': 'chunked', 'Access-Control-Allow-Headers': 'x-requested-with, Content-Type, origin, accept, cache-control', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains', 'Server': 'Apache', 'X-Frame-Options': 'SAMEORIGIN', 'Access-Control-Allow-Origin': '*', 'Content-Language': 'en', 'X-CDN': 'Incapsula', 'Content-Encoding': 'gzip', 'Expires': 'Mon, 05 Nov 2018 16:43:43 GMT'} {"price": "0.45701", "amount": "205.33880000", "type": "0", "id": "2344915356", "datetime": "2018-11-05 16:43:43.355250"}
{'info': {'type': '0', 'id': '2344915356', 'amount': '205.33880000', 'price': '0.45701', 'datetime': '2018-11-05 16:43:43.355250'}, 'id': '2344915356'}
```

**Comment by fedecaccia** [comment]
To read it easier:

Request: GET https://www.bitstamp.net/api/v2/trading-pairs-info/ {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://www.bitstamp.net/api/v2/trading-pairs-info/ 200 {'Last-Modified': 'Mon, 05 Nov 2018 16:43:42 GMT', 'Cache-Control': 'max-age=0', 'Vary': 'Authorization,Accept-Language', 'Content-Type': 'application/json', 'Set-Cookie': 'visid_incap_99025=GSb+7WNgRka5nlV5b+058T1z4FsAAAAAQUIPAAAAAACMt6mLNMGfkzgUqmMFF4ZN; expires=Tue, 05 Nov 2019 10:07:00 GMT; path=/; Domain=.bitstamp.net, nlbi_99025=VfddP9OMYUVuRsjA8F1n9AAAAACtd3+7E65KrxInPgX9uwp5; path=/; Domain=.bitstamp.net, incap_ses_785_99025=W8I2YSYz7xXGKnRF+uHkCj5z4FsAAAAAL+0KL9wdY4JXuasoylmvJA==; path=/; Domain=.bitstamp.net, ___utmvmmzumyLc=KYDeXTZbDlF; path=/; Max-Age=900, ___utmvamzumyLc=ZDK\x01Zjuc; path=/; Max-Age=900, ___utmvbmzumyLc=oZv\r\n    XmyOFalp: rtD; path=/; Max-Age=900', 'Date': 'Mon, 05 Nov 2018 16:43:42 GMT', 'X-Iinfo': '9-9802477-9799976 PNNN RT(1541436221830 84) q(0 0 0 0) r(2 2) U2', 'Access-Control-Allow-Methods': 'POST, GET', 'Connection': 'keep-alive', 'transfer-encoding': 'chunked', 'Access-Control-Allow-Headers': 'x-requested-with, Content-Type, origin, accept, cache-control', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains', 'Server': 'Apache', 'X-Frame-Options': 'SAMEORIGIN', 'Access-Control-Allow-Origin': '*', 'Content-Language': 'en', 'X-CDN': 'Incapsula', 'Content-Encoding': 'gzip', 'Expires': 'Mon, 05 Nov 2018 16:43:42 GMT'} [{"base_decimals": 8, "minimum_order": "5.0 USD", "name": "LTC/USD", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "ltcusd", "description": "Litecoin / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "5.0 USD", "name": "ETH/USD", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "ethusd", "description": "Ether / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "5.0 EUR", "name": "XRP/EUR", "counter_decimals": 5, "trading": "Enabled", "url_symbol": "xrpeur", "description": "XRP / Euro"}, {"base_decimals": 8, "minimum_order": "5.0 USD", "name": "BCH/USD", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "bchusd", "description": "Bitcoin Cash / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "5.0 EUR", "name": "BCH/EUR", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "bcheur", "description": "Bitcoin Cash / Euro"}, {"base_decimals": 8, "minimum_order": "5.0 EUR", "name": "BTC/EUR", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "btceur", "description": "Bitcoin / Euro"}, {"base_decimals": 8, "minimum_order": "0.001 BTC", "name": "XRP/BTC", "counter_decimals": 8, "trading": "Enabled", "url_symbol": "xrpbtc", "description": "XRP / Bitcoin"}, {"base_decimals": 5, "minimum_order": "5.0 USD", "name": "EUR/USD", "counter_decimals": 5, "trading": "Enabled", "url_symbol": "eurusd", "description": "Euro / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "0.001 BTC", "name": "BCH/BTC", "counter_decimals": 8, "trading": "Enabled", "url_symbol": "bchbtc", "description": "Bitcoin Cash / Bitcoin"}, {"base_decimals": 8, "minimum_order": "5.0 EUR", "name": "LTC/EUR", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "ltceur", "description": "Litecoin / Euro"}, {"base_decimals": 8, "minimum_order": "5.0 USD", "name": "BTC/USD", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "btcusd", "description": "Bitcoin / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "0.001 BTC", "name": "LTC/BTC", "counter_decimals": 8, "trading": "Enabled", "url_symbol": "ltcbtc", "description": "Litecoin / Bitcoin"}, {"base_decimals": 8, "minimum_order": "5.0 USD", "name": "XRP/USD", "counter_decimals": 5, "trading": "Enabled", "url_symbol": "xrpusd", "description": "XRP / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "0.001 BTC", "name": "ETH/BTC", "counter_decimals": 8, "trading": "Enabled", "url_symbol": "ethbtc", "description": "Ether / Bitcoin"}, {"base_decimals": 8, "minimum_order": "5.0 EUR", "name": "ETH/EUR", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "etheur", "description": "Ether / Euro"}]

Request: POST https://www.bitstamp.net/api/v2/buy/market/xrpusd/ {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Content-Type': 'application/x-www-form-urlencoded'} signature=0174568ED4A09B8D2982C0B8E8D90C813F3B7271936FD0A05927552D7A5F1134&nonce=1541436222&amount=205.3388&key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Response: POST https://www.bitstamp.net/api/v2/buy/market/xrpusd/ 200 {'Last-Modified': 'Mon, 05 Nov 2018 16:43:43 GMT', 'Cache-Control': 'max-age=0', 'Vary': 'Authorization,Accept-Language', 'Content-Type': 'application/json', 'Set-Cookie': 'visid_incap_99025=GSb+7WNgRka5nlV5b+058T1z4FsAAAAAQUIPAAAAAACMt6mLNMGfkzgUqmMFF4ZN; expires=Tue, 05 Nov 2019 10:07:00 GMT; path=/; Domain=.bitstamp.net, incap_ses_785_99025=4A1daBoJ+FHGKnRF+uHkCj5z4FsAAAAAWVTAtJeudcPmt/BFzCH+ZA==; path=/; Domain=.bitstamp.net, ___utmvmmzumyLc=QzSCqSYABGk; path=/; Max-Age=900, ___utmvamzumyLc=YDx\x01RRQS; path=/; Max-Age=900, ___utmvbmzumyLc=dZn\r\n    XNXOvalc: atX; path=/; Max-Age=900', 'Date': 'Mon, 05 Nov 2018 16:43:43 GMT', 'X-Iinfo': '9-9802477-9799976 SNNN RT(1541436221830 343) q(0 0 0 0) r(5 5) U6', 'Access-Control-Allow-Methods': 'POST, GET', 'Connection': 'keep-alive', 'transfer-encoding': 'chunked', 'Access-Control-Allow-Headers': 'x-requested-with, Content-Type, origin, accept, cache-control', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains', 'Server': 'Apache', 'X-Frame-Options': 'SAMEORIGIN', 'Access-Control-Allow-Origin': '*', 'Content-Language': 'en', 'X-CDN': 'Incapsula', 'Content-Encoding': 'gzip', 'Expires': 'Mon, 05 Nov 2018 16:43:43 GMT'} {"price": "0.45701", "amount": "205.33880000", "type": "0", "id": "2344915356", "datetime": "2018-11-05 16:43:43.355250"}
{'info': {'type': '0', 'id': '2344915356', 'amount': '205.33880000', 'price': '0.45701', 'datetime': '2018-11-05 16:43:43.355250'}, 'id': '2344915356'}

**Comment by fedecaccia** [comment]
I don't even understand why it is setting that lower price

**Comment by kroitor** [comment]
What's interesting, here we see that is does supply a market order to the proper endpoint without specifying the price:

- Request: POST https://www.bitstamp.net/api/v2/buy/market/xrpusd/
- signature=...&nonce=1541436222&amount=205.3388&key=XXXXXXXXXXXXXXX

... and we receive back the execution price 0.45701, while their website is showing XRP/USD 0.48313...

I'd say Bitstamp support should be able to explain this... 

Also, they have *"market"* orders and *"instant"* orders...

... and the difference between the two isn't clear for me at all as I personally don't trade there – their descriptions in API docs are the same – a copypasted text saying:

> By placing a market order you acknowledge that the execution of your order depends on the market conditions and that these conditions may be subject to sudden changes that cannot be foreseen.

> By placing an instant order you acknowledge that the execution of your order depends on the market conditions and that these conditions may be subject to sudden changes that cannot be foreseen.

**Comment by fedecaccia** [comment]
There is a little bit more explanation in the Buy/Sell section on their exchagne front end: 
_When you place an instant order, we add an order at the current bid or ask price (depending on the type of the order). If there is not enough XRP available at that price, our trading engine will then reposition your order every second to the current order book offer._

But for me neither it's not clear at all.

I'm going to write to Bitstamp support.
Thanks for your time!

**Comment by kroitor** [comment]
> When you place an instant order, we add an order at the current bid or ask price (depending on the type of the order). If there is not enough XRP available at that price, our trading engine will then reposition your order every second to the current order book offer.

Cool. I guess, they're saying that your order will be closed for best price available filling the orderbook top-down... That filling procedure is partially covered here as well:

- https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades

In other words, that is how a *"market"* order is expected to behave (at least, to my understanding).
And if they call that an *"instant"* order – what's a *"market"* order in their terms then?

> But for me neither it's not clear at all.

Absolutely!

**Comment by fedecaccia** [comment]
@kroitor Just for the records, Bitstamp support wrote me recognizing an error of their API.
