### ISSUE TITLE
How to cancel all pending orders in Okex via ccxt ? 

### ISSUE THREAD

**Issue by GenesisGupta** [ccxt/ccxt#4118]
okex.privateDeleteOrderAll() does not work 

okex.privatePostOrderCancelAll() does not work 

ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10
- Programming Language version: python 3.6 
- CCXT version: 1.17.394
- Exchange: Okex
- Method: Cancelorder

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

**Comment by kroitor** [comment]
They have added an endpoint for canceling all orders in v3, the work on it is currently in progress: https://github.com/ccxt/ccxt/issues/4063
