### ISSUE TITLE
Possible to show if Withdraw enabled?

### ISSUE THREAD

**Issue by Newar417** [ccxt/ccxt#412]
In the overview table, is it possible to show whether withdrawal is possible via API?

**Comment by kroitor** [comment]
Did you mean this table? 

<img width="1574" alt="screen shot 2017-10-28 at 13 20 51" src="https://user-images.githubusercontent.com/1294454/32133546-e125c592-bbe2-11e7-82fa-f324ac0ba157.png">

See the rightmost column ↑

Each exchange has a 'hasWithdraw' flag, which is either true (green on the above image), or false (dim red on the above image). True means it's implemented, False means it's either not available at all (not offered by the exchange API itself) or not implemented yet. Does this answer your question?

**Comment by Newar417** [comment]
That is cool! I meant the table on https://github.com/ccxt/ccxt , but this will do just fine. Thank you!
