### ISSUE TITLE
Proposal: unify fetchTransactionFees

### ISSUE THREAD

**Issue by firepol** [ccxt/ccxt#4128]
I've seen in the binance class, and others, huge hardcoded list of funding fees, not up to date.

I see that some exchanges support the method fetchTransactionFees.

Similarly to `fetchMarkets` and `fetchCurrencies`, I think that fees should not be hardcoded but loaded on demand (like markets & currencies).

Some exchanges also specify:
- minimum withdrawal amount
- deposit fee or small deposit fee (e.g. bitfinex if you deposit less than 1000 USD in crypto you are subject to that fee)
- deposit/withdrawal active? true/false (e.g. in binance e.g. `DENT: {'minWithdrawAmount': 966.0, 'depositStatus': True, 'withdrawFee': 483.0, 'withdrawStatus': True}`it's called `depositStatus` and `withdrawStatus`: this is useful e.g. when a wallet is under maintenance and the exchange temporarily doesn't allow to withdraw or deposit a specific currency, e.g. when a currency is switching to mainnet or so

So I believe those infos should be part of the standard response object. Now the response contains
- withdraw: dictionary of currencies as key, fee as value
- deposit: dictionary of currencies as key, fee as value
- info

I think that each key should contain, instead of just the fee, an object with the details as listed above. If the exchange does not provide them, leave them undefined.

Some exchanges unluckily do not have a  `fetchTransactionFees` method and one should e.g. go to their website and check fees there. So for this reason, a follow up idea could be to host these fees in here or in a separate repo that CCXT should refer to.

E.g. I was thinking I or somebody with more free time could code a side project that scrapes pages for those exchanges not providing the API and save the result as JSON. CCXT could just load the json for those exchanges. With Trevis you can have a pipeline regularly calling the scraping script and committing automatically the changes in the git repo.

I've seen this in the [zenbot](https://github.com/DeviaVir/zenbot) project, see e.g. update.products.sh here: https://github.com/DeviaVir/zenbot/tree/unstable/extensions/exchanges/binance

See how the history of commits is full of such automated updates: https://github.com/DeviaVir/zenbot/commits/unstable

I don't like that these files are together with the main repo, somehow they pollute the git history. Also I think a separate repo specific only for this, could be a reference for other projects as well.

The repo could be under ccxt as "ccxt/exchanges-info" or something like that.

Then the exchange could have inside 'has' a new property called e.g. has['exchangeInfo'] = true and by convention CCXT will know a base URL + echangeId + .json or so (e.g. exchanges with api + api v2 should refer to the same file, or having it duplicated for those).

What do you think?

**Comment by kroitor** [comment]
Hi!

> I've seen in the binance class, and others, huge hardcoded list of funding fees, not up to date.

Yep, we were initially against hardcoding those (and we still are, as you can see from numerous comments around those values):
- https://github.com/ccxt/ccxt/blob/2fc5c5bd09da6e7452b27829f9a3435cbb11b7f5/python/ccxt/async_support/rightbtc.py#L97
- https://github.com/ccxt/ccxt/blob/ce8bb0465877fe1a83fa873d53ef7e3a8bebdae4/php/bigone.php#L74
- https://github.com/ccxt/ccxt/blob/ad89fc81b11840371f5bb0e91b612e44b85343aa/js/bcex.js#L95

Some users insisted on adding hard values until we implement fetching methods where missing. So, that hardcode is there mostly for historical reasons, but it is to be removed, of course. And, yes, it's outdated, that's the main reason for not documenting them in the Manual yet.

> I see that some exchanges support the method fetchFundingFees.
> Similarly to fetchMarkets and fetchCurrencies, I think that fees should not be hardcoded but loaded on demand (like markets & currencies).

It's far more complicated than that, I'm afraid...
The reality is:
- some exchanges return funding fees from endpoints corresponding to `fetchCurrencies`
- some exchanges return trading fees from endpoints corresponding to `fetchMarkets`
- some exchanges return funding fees from a separate endpoint (`fetchFundingFees`)
- some exchanges return trading fees from a separate endpoint (`fetchTradingFees`)
- some exchanges return funding and trading fees from a single endpoint (`fetchFees` ?)
- in some cases funding fees depend on the funding method
- we need `loadTradingFees`, `loadFundingFees` and `loadFees`
- we need `loadMarketsCurrenciesAndFees`

All of the above, including some insights and discussions in detail, is here:

- https://github.com/ccxt/ccxt/pull/1669
- https://github.com/ccxt/ccxt/pull/1814

> E.g. I was thinking I or somebody with more free time could code a side project that scrapes pages for those exchanges not providing the API and save the result as JSON. CCXT could just load the json for those exchanges. With Trevis you can have a pipeline regularly calling the scraping script and committing automatically the changes in the git repo.

> What do you think?

Yep, the idea is clear, it's basically in the air, the only reason for not having it done yet is the lack of time, basically, it's hard to find a window to tackle some external aspects of it while maintaining the current codebase with our limited resources. But we hope to implement something similar to what you described sooner or later.

Thx for your participation!

**Comment by firepol** [comment]
Thx for your reply @kroitor 

but would it make sense if I have some spare time, to try to code something, as suggested in the other discussions you mentioned?

First priority try to implement this method for a few exchanges that actually include the info in some api, I just have to find out on each exchange, where is it hidden, as you said sometimes it's in the markets, sometimes in currencies etc. so basically it's different for each exchange.

It's something I'm working on these days, so why not doing it in CCXT instead of doing it externally ;) I'll send some updates here before submitting a PR. Will do a separate branch in my fork and add my changes there.
