### ISSUE TITLE
New exchange - https://satowallet.com

### ISSUE THREAD

**Issue by satowallet** [ccxt/ccxt#4129]
Please support to add Exchange

Website: https://satowallet.com
API Doc: https://satowallet.com/?__wallets_exchange_action=get_market_summaries

Thanks!

**Comment by An-Net** [comment]
The website doesn't work anymore:

- https://cointelegraph.com/news/users-of-nigeria-based-crypto-wallet-lose-1m-in-alleged-exit-scam

- https://twitter.com/satowallet

- https://forklog.com/polzovateli-koshelka-satowallet-obvinili-proekt-v-ekzit-skame-i-prisvoenii-1-mln/
