### ISSUE TITLE
DDoSProtection: binance 429 Too Many Requests only on server

### ISSUE THREAD

**Issue by Arrmlet** [ccxt/ccxt#4137]
- Ubuntu:
- Python 3.6:
- CCXT version newest:
- Exchange: binance:
- Method: fetch_order_book:

Hello everyone, I have a problem when I start my bot on Amazon Instance I'm getting this error:
```
    raise DDoSProtection(self.id + ' ' + str(code) + ' ' + reason + ' ' + body)
ccxt.base.errors.DDoSProtection: binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API."}
```
 What interesting when I start my script on my PC, this error is not occur.
A couple of my code:

```
def get_prices():
	pairs = ['XRP/BTC', 'XRP/ETH', 'ETH/BTC']#bid - bid - ask
	bid_ask = ['bids', 'bids', 'bids']
	prices = []
	for i in range(0, len(pairs)):

		a = binance.fetch_order_book(symbol=pairs[i])[bid_ask[i]]
		price = a[0][0]
		prices.append(price)
	return prices 
```

**Comment by kroitor** [comment]
@Arrmlet Hi! Can you show your code for instantiating the exchange class? The most common pitfall is not using the rate-limiter properly, as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit. Need to see how you create the exchange object, to resolve it.

**Comment by Arrmlet** [comment]
@kroitor  Thx for fast request , I created my exchange object like this:
```

binance = ccxt.binance({
    'apiKey': 'myApi',
    'secret': 'Mysecret',
})
```

**Comment by kroitor** [comment]
@Arrmlet looks like you missed it: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

> **WARNING: users are responsible for at least some type of rate-limiting: either by implementing a custom algorithm or by doing it with the built-in rate-limiter..**

See examples by that link. That should solve the issue. Let us know if not. Closing it for now, if you don't mind.

**Comment by kroitor** [comment]
> As I understood I need to create my object like this?:

Yep.

**Comment by Arrmlet** [comment]
@kroitor Its help thank you :) Спасибо большое
