### ISSUE TITLE
Bittrex International

### ISSUE THREAD

**Issue by clu8** [ccxt/ccxt#4138]
Requesting support for Bittrex International - should be a simple change to Bittrex, but using international.bittrex.com for endpoints, e.g. https://international.bittrex.com/api/v2.0/auth/balance/GetBalances

More info: https://support.bittrex.com/hc/en-us/articles/360001426066-FAQs-Bittrex-International-Trading-Platform-

**Comment by larsCrypto** [comment]
Yup, currently attempting to trade on certain coins such as ZIL gives the error "does not have market symbol" because there's no option to trade using the international APIs

**Comment by rdbr** [comment]
The Bittrex implementation uses `v2GetMarketsGetMarketSummaries` in `fetchMarkets`:
`https://bittrex.com/api/v2.0/pub/Markets/GetMarketSummaries`
This call doesn't have the new markets yet.

The official url does include the new markets such as `MOC` and `ZIL`:
`https://bittrex.com/api/v1.1/public/getmarkets`

So maybe switching to the correct url is enough? There is no official `international.bittrex.com` API endpoint.
