### ISSUE TITLE
How to get currency names and exchanges by volume from CoinMarketCap?

### ISSUE THREAD

**Issue by lampardlb** [ccxt/ccxt#4140]
- OS: Windows
- Programming Language version: python
- CCXT version: 1.17.480
- Exchange:
- Method: coinmarketcap

Hi,
  Sorry this is a question rather than an issue, but i could not find the answer from the relevant manuals. What I'm wondering is for a given full name of a currency (e.g. 'Bitcoin'), how I can obtain information for the following from ccxt.coinmarketcap():
  1. the short name of the currency (e.g. 'BTC');
  2. the exchanges that have the largest volume for the coin (e.g. 'Binance')

Thank you very much in advance!

**Comment by npomfret** [comment]
This is documented [here](https://github.com/ccxt/ccxt/wiki/Manual#notes-on-naming-consistency) in the manual I believe.  To map from symbols to names you can construct a `coinmarketcap` instance of ccxt and call it's `fetchCurrencies` method - the resulting data has both the name and id.

**Comment by lampardlb** [comment]
@npomfret Thank you very much for your reply Nick. I've tried the fetchCurrencies method, but it seems to load all the currencies on coinmarketcap, which is obviously a lot of data and it freezes python entirely. Is there a 'lite' way just to load the currency of interest please?

Here're the codes I used:
import ccxt
cmc = ccxt.coinmarketcap()
cmc.fetchCurrencies()

**Comment by npomfret** [comment]
That's odd that it takes so long.  I'm not using python unfortunately but the js call takes only 199ms.

You could make the call and then cache the data perhaps?  But in answer to your question I don't know another way to get a mapping of currency name to symbol / id.

**Comment by lampardlb** [comment]
@npomfret yes I'm planning to cache the data. I'll try to find out why it takes long. Thanks for your help!

**Comment by lampardlb** [comment]
@kroitor Thank you Igor as always!

**Comment by lampardlb** [comment]
Just to give some feedback on how to get the name of exchanges where a given coin is available, there may be two ways:
1. coinmarketcap Professional API, where you can request the coin-BTC pair:
https://pro.coinmarketcap.com/api/v1#operation/getV1CryptocurrencyMarketpairsLatest
unfortunately this endpoint does not seem to be available for free users, and this may not be compatible with ccxt which uses the public API;

2. crypto compare API endpoint, e.g.:
https://min-api.cryptocompare.com/data/top/exchanges?fsym=BTC&tsym=USDT&limit=50

These are perhaps not related to ccxt development, just posting in case there are other people having similar needs. Thanks again for all who helped.

**Comment by electic** [comment]
It would be great if we could support a more open community driven method to keep a list of currencies and their attributes:

https://github.com/Blockmodo/coin_registry

Happy to work with everyone who is willing to help.

**Comment by tmlee** [comment]
Our CoinGecko API can do that, for example http://api.coingecko.com/api/v3/coins/bitcoin
just replace the coin name with other coin names and you will be able to obtain information and largest volume ticker as well.

Full docs at https://www.coingecko.com/api and there I noticed pending integration at https://github.com/ccxt/ccxt/pull/3565

**Comment by lampardlb** [comment]
@tmlee Thanks, this is a wonderful feature. Though I tend to think using code names instead of full names for the enquiry would perhaps make things easier for the end users.

**Comment by tmlee** [comment]
@lampardlb we avoid using code names because there are many coins that shares the same symbols.
full name reduces that risks, thus allows end user to easily pass in intuitively the name of the coin to lookup.

**Comment by gnsawant** [comment]
> 

I tried this way but error encounters 'ccxt has no coinmarketcap attribute
