### ISSUE TITLE
Exchange: Coinbase - full methods support

### ISSUE THREAD

**Issue by koltsovml** [ccxt/ccxt#4141]
Hello ccxt team!
I'm going to use your library and I'm particularly interested in Coinbase exchange. As I've found out, it doesn't have the create_order method. DO you have any plans in regards to implementing full Coinbase support in the nearest time, perhaps you're already working on it?
Looking forward to hearing from you soon!

- OS: Windows 10
- Programming Language version: PHP 7.2
- CCXT version: 1.17.481
- Exchange: Coinbase
- Method: create_order

**Comment by kroitor** [comment]
Hi! 

Let's clarify: are you asking about Coinbase (which isn't an exchange, more like a wallet service) or Coinbase Pro (which is an exchange, formerly known as GDAX) ?

**Comment by koltsovml** [comment]
To my knowledge Coinbase is a simplified version of Coinbase Pro, am I right?

**Comment by kroitor** [comment]
> To my knowledge Coinbase is a simplified version of Coinbase Pro, am I right?

Well, it's not really guaranteed that your orders with Coinbase will be executed via Coinbase Pro orderbooks, so, to me these are separate systems. Anyways, we will do our best to add `create_order` to Coinbase as well.

**Comment by kroitor** [comment]
@koltsovml btw, in the meantime, you can still place orders there with CCXT with https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods ;)

**Comment by RetGal** [comment]
@kroitor pro.coinbase has begun to genlty push their customers to use the coinbase API (gently by deactivating their pro API-keys). I guess the pro API will therefore rapidly lose its importance in favor to the coinbase API - which is supported by ccxt still in a rather basic fashion ;)

**Comment by kroitor** [comment]
@RetGal thanks, we will update the sources asap!

**Comment by jtseven** [comment]
Any news on this issue?

**Comment by ttodua** [comment]
For future readers - please refer to [this issue](https://github.com/ccxt/ccxt/issues/12999) to get notified about updates with regard to Coinbase integratio updates.
