### ISSUE TITLE
Any way to get the rate limit for each public API on ccxt?

### ISSUE THREAD

**Issue by mw130** [ccxt/ccxt#4143]
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: mojave
- Programming Language version: python 3 
- CCXT version: latest (as of 11/8/18)
- Exchange: all
- Method: get rate limit
Is there some method for getting the rate limit without manually looking it up for each exchange?

**Comment by kroitor** [comment]
```Python
import ccxt
from pprint import pprint
rate_limits_by_exchange_id = {}
for id in ccxt.exchanges:
    exchange = getattr('ccxt', id)()
    rate_limits_by_exchange_id[exchange.id] = exchange.rateLimit
pprint(rate_limits_by_exchange_id)
```

Let us know if that does not answer the question )
