### ISSUE TITLE
Show order response create_market_buy_order

### ISSUE THREAD

**Issue by nerfherder1** [ccxt/ccxt#4145]
Trying to see the response from create_market_buy_order but I am not sure how.  I have tried a print | pprint | and custom logging.  I do not want to turn on verbose for all http.  Id like to get just the response from this query.  I have tried with and without params.  My code appears to skip over the "market_buy" when trying to get output from it. Other logging | pprint and print statements work just fine.  It is only this one.

```
params = {
            'test': True,  
        }
market_buy = binance.create_market_buy_order(symbol, buy_amount, params)     

pprint(market_buy)
log_buy.debug(market_buy) 
```

- OS: WIN 10 + UBUNTU 18.04 + 18.10
- Programming Language version: PYTHON
- CCXT version: 1.17.485
- Exchange: BINANCE
- Method: CREATE_MARKET_BUY_ORDER

**Comment by kroitor** [comment]
One of possible ways:

```Python
binance = ccxt.binance ({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,  # as required by the Manual
})
params = {
'test': True,
}
# preload markets in non-verbose mode
binance.load_markets()

# verbose output for just the request/response of create_market_buy_order
binance.verbose = True

# do the call (and save the output)
market_buy = binance.create_market_buy_order(symbol, buy_amount, params) pprint(market_buy)

# switch it back off
binance.verbose = False
```

That isn't the only way to achieve the same, though... So it depends on the purpose of saving it in the first place. Let us know if that does not answer your question.
