### ISSUE TITLE
inhibit nonce generation?

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#4147]
I've just noticed that bleutrade have made it optional to use a nonce in their API:

> nonce is a number that should never be repeated and always greater than the previous number. Is used to increase your safety, is optional, but if it is first used, it becomes mandatory. Max = 2147483647.

This is particularly interesting because they don't allow multiple api keys, so it's very difficult having more than one app running.

https://classic.bleutrade.com/help/API

It there a way to inhibit the inclusion of a nonce in the API calls?

**Comment by kroitor** [comment]
> It there a way to inhibit the inclusion of a nonce in the API calls?

There's no unified way to do that yet, but I've added a `disableNonce` option to Bleutrade specifically, as of version 1.17.489.

https://github.com/ccxt/ccxt/blob/master/js/bleutrade.js#L98
