### ISSUE TITLE
Cross over or some back-end confusion here?

### ISSUE THREAD

**Issue by DeveloperOnCall** [ccxt/ccxt#4148]
- OS: Ubuntu 16
- Programming Language version: node 10
- CCXT version: current
- Exchange: Binance
- Method: fetchTickers

**Here's a puzzle....** 

When calling fetchTickers I am randomly receiving this error.. which is strange because I am not working with the ACX exchange.  'Getting Binance Ticks' is logged to the console moments before getting the error - just wanted to make sure the problem wasn't on my end.

Any ideas would be great, thanks.

```js
Getting binance Ticks
(node:1483) UnhandledPromiseRejectionWarning: Error: acx GET https://acx.io/api/api/v2/tickers.json request timed out (10000 ms)
    at timeout.catch.e (/home/bitnami/natfeeder/node_modules/ccxt/js/base/Exchange.js:438:27)
    at _tickCallback (internal/process/next_tick.js:43:7)
    at processTimers (timers.js:265:7)

```

**Comment by kroitor** [comment]
Can you paste a short, but a complete snippet (10-20 lines), including instantiation, to reproduce it (without your keys, of course) ? I mean, if you reduce your test case to the shortest possible form, it would help resolve the issue quickly.

**Comment by kroitor** [comment]
Follow these guides as closely as you can: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by DeveloperOnCall** [comment]
@kroitor Thanks - I figured it out - turns out we had set a default as acx and the app was using that in err.

D.
