### ISSUE TITLE
hard coded bleutrade fees could be replaced by parsing webpage

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#4149]
https://bleutrade.com/help/fees_and_deadlines

Some more is available from the API v2:

https://classic.bleutrade.com/help/API

* https://bleutrade.com/api/v2/public/getcurrencies
* https://bleutrade.com/api/v2/public/getmarkets

**Comment by kroitor** [comment]
I'd merge this with the following duplicate issue: https://github.com/ccxt/ccxt/issues/4128 ) I suggest that we move this particular discussion there, if you don't mind. Thx!

**Comment by npomfret** [comment]
@kroitor looks like the withdrawal fees are in the [api](https://bleutrade.com/api/v2/public/getcurrencies) under `TxFee` so no need to parse the web page and the hard coded values can be removed.

**Comment by kroitor** [comment]
@npomfret yep, we already parse it here: 

- https://github.com/ccxt/ccxt/blob/master/js/bittrex.js#L325
- https://github.com/ccxt/ccxt/blob/master/js/bleutrade.js#L10

**Comment by npomfret** [comment]
I think we can delete the hard coded values then
