### ISSUE TITLE
GDAX, how to return error from try catch

### ISSUE THREAD

**Issue by flavioespinoza** [ccxt/ccxt#415]
Hi, all!
I have this async function to place orders on GDAX, but how do I return the error message to the client?

```javascript
const ___place_limit_buy_order = async function (__buy_order) {
  try {
    let order = await X.create_limit_buy_order(__buy_order.market, __buy_order.amount, __buy_order.price)
    return order
  } catch (__err) {
    return __err.message
  }
}

```

**Comment by kroitor** [comment]
Hi, @flavioespinoza !

Currently the error message may contain too much technical info, that will not be very useful to your client, so you can use the .message as shown in your code, but most of the time it is recommended to write human-readable short messages:

```
 try {

     // ccxt call

} catch (e) {

    if (e instanceof ccxt.RequestTimeout) {
        return '[Request Timeout] Request Timed Out'
    } else if (e instanceof ccxt.AuthenticationError) {
        return '[Authentication Error] Invalid API Keys'
    } else {
        // ...
    }
}
```

CCXT currently distinguishes between [some types of errors](https://github.com/ccxt/ccxt/wiki/Manual#error-handling) but not all of them have been completely unified yet. Does this answer your question?

**Comment by flavioespinoza** [comment]
Thanks for the quick response!

Great advice.  I'll definitely do that, but how do I handle the promise returned from gdax

```javascript
io.on('connection', socket => {

  console.log('New client connected'), setInterval(() => getApiAndEmit(socket), __interval)
  /** Place Limit Buy Order */
  socket.on('Place Buy Order', function (__order) {
    let place_order = ___place_limit_buy_order(__order) // returns promise
    socket.emit('Order Placed Confirmation', __order)
  })

})
```

**Comment by kroitor** [comment]
```
io.on('connection', socket => {

  console.log('New client connected'), setInterval(() => getApiAndEmit(socket), __interval)
  /** Place Limit Buy Order */
  socket.on('Place Buy Order', async function (__order) {
    try {
        let place_order = await ___place_limit_buy_order(__order)
        socket.emit('Order Placed Confirmation', place_order)
    } catch (e) {

        // handle errors here, emit other events/errors in socket.io or whatever framework you use

    }
  })
})
```

Does this help?

**Comment by flavioespinoza** [comment]
I think this solves it.  I will try in the morning, as I have been coding
all day.

Thanks, Igor!! +_+

**Comment by kroitor** [comment]
Ok, I'm closing this for now, feel free to reopen it or ask questions if you still have difficulties with it. Thx!
