### ISSUE TITLE
Error 404 when loading binance fees

### ISSUE THREAD

**Issue by Arrmlet** [ccxt/ccxt#4159]
- Ubuntu
- python 3.6
- newest
- Binance
- LoadFees, fetchFees, loadwapifees
Hello everybody, when Im trying to load fees on binance Im getting the error 404 url not found, when implement the same method on other exchanges(Poloniex, kraken) its working correctly 

Cheers

**Comment by Arrmlet** [comment]
Hi, I update ccxt version and it start working. Sorry for my incompetence

**Comment by kroitor** [comment]
@Arrmlet thx for reporting back!
