### ISSUE TITLE
Possible to fetch coincheck margin balance as bitfinex2?

### ISSUE THREAD

**Issue by hogehogemon** [ccxt/ccxt#416]
Thanks to #394
It would be great if coincheck "fetch_balance" can fetch Leverage Balance like bitfinex2 can return.
https://coincheck.com/documents/exchange/api#account-leverage-balance
Thank you,

**Comment by kroitor** [comment]
Hi, we will look into adding that to unified fetchBalance API, in the meantime, you can already do that with ccxt custom API for coincheck, like so:

```Python
exchange = ccxt.coincheck ({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
print(exchange.private_get_accounts_leverage_balance())
```

Does this answer your question?

**Comment by hogehogemon** [comment]
I confirmed that worked! and well answered my question. Thank you!
