### ISSUE TITLE
coinbase pagination params result in invalid signature error

### ISSUE THREAD

**Issue by Syn3x** [ccxt/ccxt#4167]
- OS: Ubuntu 16.04
- Programming Language version: nodejs 8
- CCXT version: 1.17.494
- Exchange: coinbase
- Method: fetchDeposits, fetchWithdrawals

When I use `fetchDeposit` (for example) with pagination params like `starting_after`, `order=asc` or `limit=100` I always get the following error:

```
{ Error: coinbase {"errors":[{"id":"authentication_error","message":"invalid signature"}]}
```

Call example:
```
const params = { order: 'asc', account_id: accountId, limit: 100 };
const deposits = await ccxt.fetchDeposits(undefined, undefined, undefined, params)
```

The variable `what` for the signature looks like this (account id removed):
`1542197705GET/v2/accounts/ACCOUNTID/deposits?order=asc&limit=100`

Part of the verbose output (api key removed):
```
fetch:
 coinbase GET https://api.coinbase.com/v2/accounts/ACCOUNTID/deposits?order=asc&limit=100 
Request:
 { 'CB-VERSION': '2018-05-30',
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36',
  'CB-ACCESS-KEY': 'APIKEY',
  'CB-ACCESS-SIGN': '53c293ef3e789ad5d892eb343b6761e55fe7a1c26642e605a53c85c0c6bb34fc',
  'CB-ACCESS-TIMESTAMP': '1542198806',
  'Content-Type': 'application/json' } 
 undefined 

handleRestResponse:
 coinbase GET https://api.coinbase.com/v2/accounts/ACCOUNTID/deposits?order=asc&limit=100 401 Unauthorized 
```

**I do not get this error with `fetchMyTrades` and the above params.**

Can someone reproduce this or tell me if I'm doing something wrong?
Thanks!

**Comment by npomfret** [comment]
I'm seeing the same problem.  Was this resolved?

**Comment by npomfret** [comment]
@kroitor found a bug in the Coinbase sign method.  Will submit a fix

**Comment by npomfret** [comment]
It's not really a bug actually.  If you pass a null or undefined parameter (and no other parameters) then the sign method will create an invalid signature.

**Comment by phips28** [comment]
@npomfret is there a fix for that?

**Comment by kroitor** [comment]
Coinbase requires an `account_id` or `accountId` param:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

Make sure the value you pass is not `undefined`/`None`/`null`.
