### ISSUE TITLE
fetch_trades reply structure across exchanges

### ISSUE THREAD

**Issue by vonpupp** [ccxt/ccxt#417]
Hi again Kroitor,

I have noticed that when calling the `fetch_trades` method the result doesn't have the same structure across exchanges:

```
In [1]: import ccxt
   ...: print(ccxt.bittrex().fetch_trades('BTC/USDT')[0])
{'id': '21765375', 'info': {'Id': 21765375, 'TimeStamp': '2017-10-29T17:55:37.15', 'Quantity': 0.16484899, 'Price': 5968.58810856, 'Total': 983.91572142, 'FillType': 'PARTIAL_FILL', 'OrderType': 'SELL'}, 'timestamp': 1509299737000, 'datetime': '2017-10-29T17:55:37.000Z', 'symbol': 'BTC/USDT', 'type': 'limit', 'side': 'sell', 'price': 5968.58810856, 'amount': 0.16484899}
                                                                                                                                                                         
In [2]: import ccxt
   ...: print(ccxt.gdax().fetch_trades('BTC/USD')[0])                                                                                                                                                           
{'time': '2017-10-29T17:56:01.703Z', 'trade_id': 22715331, 'price': '5961.83000000', 'size': '0.00000167', 'side': 'sell'}
```

When I switch the exchange I am having an exception due to the different hashes (camelcase vs. lowercase). Is this intentional? I guess ccxt does not process the response, but return it in raw, right?

**Comment by kroitor** [comment]
Hi, @vonpupp! Thanks for opening this issue. Looks like GDAX is not parsing the trade result. It will be fixed in 5-10 minutes. Stay tuned!

**Comment by vonpupp** [comment]
Cool, thank you very much for being so responsive. That is just awesome! Kudos.

**Comment by kroitor** [comment]
It was fixed in 1.9.284+. Don't forget to update it. Thx!

**Comment by vonpupp** [comment]
Great, thanks a lot! I will give it a try and if needed provide some feedback. If you are into algo-trading/bots I would love to share some ideas with you in the future and keep in touch. We are apparently into similar stuff :)

**Comment by vonpupp** [comment]
Is it ok for the data within the `info` hash section to be different between exchanges, right?

**Comment by kroitor** [comment]
@vonpupp , yes, the info contains a raw response from the exchange, untouched, unparsed, unconverted, as is. The other fields contain the same info, but parsed into a common format.

**Comment by vonpupp** [comment]
Great. Thanks!

**Comment by kroitor** [comment]
The format and fields recognized for trades are described here: https://github.com/ccxt/ccxt/wiki/Manual#trades-orders-executions-transactions

**Comment by vonpupp** [comment]
Awesome, I saw that a while ago and forgot about it. That helped me out thanks!
