### ISSUE TITLE
HitBTC parseOrder fails with "TypeError: Cannot read property 'symbol' of null"

### ISSUE THREAD

**Issue by obsidianart** [ccxt/ccxt#4171]
Hitbtc return an array of null from http://api.hitbtc.com/api/1/trading/orders/recent?...
<img width="180" alt="screen shot 2018-11-14 at 23 42 44" src="https://user-images.githubusercontent.com/272280/48520015-005a6600-e867-11e8-91e8-8ec9f5839f30.png">

This cause parseOrder to fail with the error "TypeError: Cannot read property 'symbol' of null" when trying to perform order['symbol']

It looks like a bug on hitbtc but I don't think I can fix it without changing ccxt itself, what do you do in this scenarios?

- OS: React native
- Programming Language version: Javascript
- CCXT version: 1.17.498
- Exchange: Hitbtc (v1 and v2)
- Method: fetchClosedOrders

**Comment by kroitor** [comment]
> It looks like a bug on hitbtc but I don't think I can fix it without changing ccxt itself, what do you do in this scenarios?

In that case we usually ask the user to try following these guides a bit more precisely: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue and post a short but a complete snippet of **code to reproduce the issue** including the instantiation code but without your api keys of course, and **verbose request + response** of that snippet. From there it's usually obvious where the error is. ) And from there it's just one small step to fix it. ;)

**Comment by obsidianart** [comment]
I understand, feel free to close this ticket, I think the bug is due to the specific API keys situation (which I can't test anymore as they weren't mine).
I thought submitting code when it is a direct call to the library wasn't necessary, since the issue is with the server response itself, but I understand you do get many ticket and you don't know me.
Thank you for your fast response, I'm suppressing the error for now on my side.
