### ISSUE TITLE
OKEX Future sample wrong, how to fetch the okex future historic data?

### ISSUE THREAD

**Issue by helldragonx** [ccxt/ccxt#4172]
- OS:
   Mac OS
- Programming Language version:
   Python 3.x
- CCXT version:
   Latest
- Exchange:
   OKEX
- Method:
   exchange.fetch_ohlcv
   exchange.fetch_ticker

in sample:
    https://github.com/ccxt/ccxt/blob/master/examples/py/fetch-okex-futures.py
the run result:
   ETH/USD {'symbol': 'ETH/USD', 'timestamp': 1542264475000, 'datetime': '2018-11-15T06:47:55.000Z', 'high': 204.937, 'low': 142.215, 'bid': 171.54, 'bidVolume': None, 'ask': 171.574, 'askVolume': None, 'vwap': None, 'open': None, 'close': 171.478, 'last': 171.478, 'previousClose': None, 'change': None, 'percentage': None, 'average': None, 'baseVolume': 47467928.0, 'quoteVolume': None, 'info': {'high': 204.937, 'vol': 47467928.0, 'day_high': 0, 'last': 171.478, 'low': 142.215, 'contract_id': 201811160020060, 'buy': 171.54, 'sell': 171.574, 'coin_vol': 0, 'day_low': 0, 'unit_amount': 10, 'timestamp': 1542264475000}}
   **The question is that each ETH has three futures, week, bi-week, and quanterly, but in the return result, seems only the token price?? **

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/okcoinusd.py#L496
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/okcoinusd.py#L563

```Python
# example 1
params = {
    'contract_type': 'next_week', # this_week, next_week, quarter
}
okex.fetch_ohlcv(futures_market['symbol'], timeframe, since, limit, params)

# example 2
okex.options['defaultContractType'] = 'quarter'
okex.fetch_ticker (futures_market['symbol'])
```

Let us know if that does not answer your questions.

**Comment by kroitor** [comment]
@helldragonx also, see this, jfyi: https://github.com/ccxt/ccxt/issues/4063

**Comment by helldragonx** [comment]
Seems in OKEX the most early BAR data we can get is 2889 bar before, 1m bar?

Candles Num: 2889 , From  2018-11-13T16:28:00Z
Candles Num: 2889 , From  2018-11-13T16:28:00Z
Candles Num: 2893 , From  2018-11-13T16:25:00Z
Candles Num: 2893 , From  2018-11-13T16:25:00Z

**Comment by Poeticphysicist** [comment]
When i fetch the future's symbols like that:
''''    
    import ccxt
    ok=ccxt.okex()
    symbols=[]
    ok.load_markets()
    mar=ok.markets
    for i in mar:
        market=mar[i]
        if market['future']:
            symbols.append(i)
''''
I get 20 pairs totally. But actually pair like 'NEO/USD' doesn't exist. I want to get the data about pair like 'BSV/USD' et al which doesn't exit ,neither. Anybody knows how to get the right future pairs data ? Please help me. Thanks!
