### ISSUE TITLE
OKEX historic OHLC data only two days are available.

### ISSUE THREAD

**Issue by helldragonx** [ccxt/ccxt#4178]
OS:
-Mac OS
Programming Language version:
-Python 3.x
-CCXT version:
Latest
-Exchange:
OKEX
-Method:
exchange.fetch_ohlcv
exchange.fetch_ticker

Sorry to interrupt again, but I'm using the fetch_ohlcv, seems only two days available, I'm not sure whether that the exchange only provide the two days data? 

Seems in OKEX the most early BAR data we can get is 2889 bar before, 1m bar?

Candles Num: 2889 , From 2018-11-13T16:28:00Z
Candles Num: 2889 , From 2018-11-13T16:28:00Z
Candles Num: 2893 , From 2018-11-13T16:25:00Z
Candles Num: 2893 , From 2018-11-13T16:25:00Z

**Comment by kroitor** [comment]
@helldragonx check the answer here: https://github.com/ccxt/ccxt/issues/4136#issuecomment-437136014, that's common to most of exchanges, as documented in our Manual: https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts
