### ISSUE TITLE
Bitmex trade size

### ISSUE THREAD

**Issue by vsmelov** [ccxt/ccxt#4180]
In bitmex, when I fetch trades via HTTP, I see size and amount in usd, not btc (for BTC/USD symbol). For others exchanges I see size and amount in BTC

bitmex trade example:
```
{'id': '8027a7a0-5961-160d-a9cc-a6188c457883', 'info': {'timestamp': '2018-11-16T15:54:52.233Z', 'symbol': 'XBTUSD', 'side': 'Sell', 'size': 400, 'price': 5531, 'tickDirection': 'ZeroMinusTick', 'trdMatchID': '8027a7a0-5961-160d-a9cc-a6188c457883', 'grossValue': 7232000, 'homeNotional': 0.07232, 'foreignNotional': 400}, 'timestamp': 1542383692233, 'datetime': '2018-11-16T15:54:52.233Z', 'symbol': 'BTC/USD', 'order': None, 'type': None, 'side': 'sell', 'price': 5531, 'amount': 400}
```

gdax trade example:
```
{'id': '53900383', 'order': None, 'info': {'time': '2018-11-16T15:54:57.173Z', 'trade_id': 53900383, 'price': '5535.88000000', 'size': '0.00548390', 'side': 'sell'}, 'timestamp': 1542383697173, 'datetime': '2018-11-16T15:54:57.173Z', 'symbol': 'BTC/USD', 'type': None, 'side': 'buy', 'price': 5535.88, 'amount': 0.0054839, 'fee': {'cost': None, 'currency': 'USD', 'rate': None}}
```

- OS:
vsmelov@blocktech-008:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bioni
- Programming Language version:
Python 3.6.6 (default, Sep 12 2018, 18:26:19) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
- CCXT version:
ccxt==1.17.86
- Exchange:
bitmex
- Method:
fetch_trades

**Comment by kroitor** [comment]
Hi!

Please, see the answer in the following duplicate issues:

- https://github.com/ccxt/ccxt/pull/3779
- https://github.com/ccxt/ccxt/issues/3540
