### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: kucoin does not have market symbol 

### ISSUE THREAD

**Issue by Gennttii** [ccxt/ccxt#4181]
Hi, I am doing loops and trying to get tickers for each exchange with each coin.
But some of exchanges don't have the pair that is looped and it shows me this error: 

`(node:28800) UnhandledPromiseRejectionWarning: Error: kucoin does not have market symbol XRP/BTC
    at kucoin.market (C:\Users\gesav\OneDrive\Desktop\Development\projects\arbApp\v5\node_modules\ccxt\js\base\Exchange.js:924:15)
    at kucoin.fetchTicker (C:\Users\gesav\OneDrive\Desktop\Development\projects\arbApp\v5\node_modules\ccxt\js\kucoin.js:1116:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:28800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28800) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

How can I handle this..!

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/blob/master/examples/js/looping-over-all-symbols-of-specific-exchanges.js
- https://github.com/ccxt/ccxt/blob/master/examples/js/looping-over-specific-symbols-of-all-exchanges.js
- https://github.com/ccxt/ccxt/wiki/Manual#error-handling
- https://github.com/ccxt/ccxt/wiki/Manual#markets
