### ISSUE TITLE
Kraken fetchMinOrderAmounts HTML page markup has changed

### ISSUE THREAD

**Issue by tommuhm** [ccxt/ccxt#4187]
It seems that Kraken has changed the markup of the html page https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size 

on executing: `loadMarkets()` for the Kraken exchange

the following error is thrown: 
Error: kraken fetchMinOrderAmounts HTML page markup has changed: https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-
    at kraken.fetchMinOrderAmounts (/mnt/daemon/dev/mine/coindock/backend/node_modules/ccxt/js/kraken.js:240:27)

Server response: correct html page from - https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size

ccxt version: ccxt@1.17.509
node version: v10.2.1

**Comment by kroitor** [comment]
> It seems that Kraken has changed the markup of the html page

Lol, 3rd time in a year )) They should've added a corresponding API endpoint already... Will fix it shortly.
