### ISSUE TITLE
PHP async

### ISSUE THREAD

**Issue by Newar417** [ccxt/ccxt#419]
The manual mentions that for PHP all API methods are synchronous. Are you aware of http://docs.guzzlephp.org/en/stable/ ? Would this be useful?

> Guzzle is a PHP HTTP client that makes it easy to send HTTP requests and trivial to integrate with web services.
[...]
Can send both synchronous and asynchronous requests using the same interface.

**Comment by kroitor** [comment]
@Newar417 we know of existing PHP libs for async networking, and we are going to integrate something like that into ccxt as well, so, the answer to your questions is: yes, thanks for the hint, we will take a look into it soon ;)
