### ISSUE TITLE
PHP version mismatch

### ISSUE THREAD

**Issue by sauronezio** [ccxt/ccxt#4190]
- OS: Ubuntu 14.04
- Programming Language version: php 5.5
- CCXT version: 1.17.511

I cannot upgrade ccxt to the latest release due to my php version being lower than 7.1 because
ccxt/ccxt requires PHP version >= 5.4 and some kornrunner packages but
kornrunner/secp256k1 requires PHP version >= 7.1.

**Comment by kornrunner** [comment]
Well, PHP 5.5 is no longer supported, and both 5.6 and 7.0 will be without support as well soon enough: http://php.net/supported-versions.php

My code requires at least 7.1, updating composer requirements would allow installation but it would produce runtime errors (if ran with wrong version of PHP). I'd advise to upgrade to a supported version of PHP. Even 7.1 active support will end soon (but it will continue to receive security patches for a while).

If not, then you can possibly switch my package to some fork that were adjusted to run on older PHP versions (but I wouldn't say that's a good thing to do).

**Comment by kroitor** [comment]
@sauronezio I'd agree with @kornrunner here, I guess, we will advise to update to 7.1 or higher, and will update our docs to actualize requirements and versions. Even if we try to fix the backward-compatibility issue here, the fix itself will be most likely be very ugly (and may be unstable). We'd better stick to consistency with version number requirements. Let us know if we can help with anything else. Closing it for now, if you don't mind, feel free to reopen it if needed or just ask further questions, if any.

@kornrunner thx so much for clarifications!
