### ISSUE TITLE
Kraken: error fetch_min_order_amounts

### ISSUE THREAD

**Issue by edirr1** [ccxt/ccxt#4192]
Since two hours there is an exeption when using exchange Kraken

- OS: Windows
- Programming Language version: Python
- CCXT version: 1.17.432
- Exchange: Kraken
- Method: fetch_min_order_amounts

**Comment by kroitor** [comment]
@edirr1 already fixed here (earlier today): https://github.com/ccxt/ccxt/issues/4187

please update CCXT version to 1.17.509 or higher.

**Comment by edirr1** [comment]
thanks!
