### ISSUE TITLE
hitbtc seems removed at async version

### ISSUE THREAD

**Issue by qraftec** [ccxt/ccxt#420]
I have version 1.9.268 and hitbtc was supported. 
But now at 1.9.284, it seems that hitbtc is not supported. 
Can somebody check this?

**Comment by kroitor** [comment]
Hi, @qraftec ! We're working on it, will be fixed very soon.

**Comment by kroitor** [comment]
This is fixed in 1.9.285. Let us know if it's working normally for you or not. Thx again!
