### ISSUE TITLE
HitBTC v1 unable to pull my trades

### ISSUE THREAD

**Issue by mattfilippone** [ccxt/ccxt#4200]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: windows
- Programming Language version: node js
- CCXT version: latest
- Exchange: hitbtc
- Method: fetchMyTrades

The fetchMyTrades method is not defined for this exchange but it does appear that the exchange supports it.  In the hitbtc.js file there appears to be some code relevant to what i need but I don't know how to use us.  specifically, at the beginning of the file there is 'api': { 'trading': { 'get' : [ 'trades' ] } }  that's the function that exists at the exchange but how do i call it?  There is no fetchTradingTrades or something similar.  Also, the ccxt docs for this exchange make it seem like you can call this endpoint but no examples or existing function exists.  (https://github.com/hitbtc-com/hitbtc-api/blob/master/APIv1.md#api1tradingtrades)

please advise

**Comment by kroitor** [comment]
I suggest switching to HitBTC v2 (use `ccxt.hitbtc2` instead of `ccxt.hitbtc`) as version 1 of their API is deprecated. Let us know if switching to v2 does not resolve the issue for you. Thx!
