### ISSUE TITLE
takerOrMaker property not set for binance.fetchTrades

### ISSUE THREAD

**Issue by tommuhm** [ccxt/ccxt#4201]
The `takerOrMaker` property ist not set for the `fetchTrades` method of `binance`.

`fetchTrades` of `binance` uses the `aggTrades` endpoint which returns:
```
{
    "a": 26129,         // Aggregate tradeId
    "p": "0.01633102",  // Price
    "q": "4.70443515",  // Quantity
    "f": 27781,         // First tradeId
    "l": 27781,         // Last tradeId
    "T": 1498793709153, // Timestamp
    "m": true,          // Was the buyer the maker?
    "M": true           // Was the trade the best price match?
  }
```

`parseTrade [binance.js:545]` sets `takerOrMaker`based on the `isMaker` property but not on the `m` property.

Also: is `side` (buy/sell) correct for fetchTrades?, it is set based on the `m` (Was the buyer the maker) property. A taker can buy/sell and a maker can buy/sell - so this might be incorrect?

node version: v10.2.1
ccxt version: 1.17.518
exchange: binance
method: fetchTrades + parseTrade

**Comment by tommuhm** [comment]
I found the answer to my second question: https://github.com/zoeyg/binance/issues/55 and https://money.stackexchange.com/questions/90686/what-does-buyer-is-maker-mean so `buy/sell` is set correctly. 
I guess takerOrMaker is not set because every aggTrade includes both a taker and a maker.
If this is correct then the issue can be closed.

**Comment by kroitor** [comment]
Yep, basically, you've answered your both questions

> I guess takerOrMaker is not set because every aggTrade includes both a taker and a maker.
> If this is correct then the issue can be closed.

That's correct, both sides are represented there, so we simply can't (or don't need to?) determine the maker side for public trades, therefore undefined.

**Comment by asuiu** [comment]
Hi @kroitor,

I think there might be a misunderstanding regarding the interpretation of the `m` field in Binance's aggTrade data and its relation to the `takerOrMaker` field in CCXT.

The `m` field in the aggTrade data (`"m": true/false`) specifically indicates whether the buyer in the trade was the maker. This detail opens up the possibility of deriving the `takerOrMaker` value based on the `m` field, considering the role of the buyer in each trade.

To elaborate:
- If `"m": true` (meaning the buyer is the maker), then for a sell order, the `takerOrMaker` should be 'taker', and for a buy order, it should be 'maker'.
- Conversely, if `"m": false` (indicating the buyer is the taker), then for a sell order, `takerOrMaker` would be 'maker', and for a buy order, it would be 'taker'.

Given this interpretation, it seems that setting the `takerOrMaker` field to None in these cases is not accurate and could be considered a bug.

Would it be possible to revisit this aspect and perhaps look into a fix? I believe adjusting the implementation to reflect this understanding could enhance the accuracy of the data representation in CCXT.

Thank you for considering this perspective, and I'm looking forward to any further thoughts or discussions on this!

Best regards, Andrei
