### ISSUE TITLE
New Exchange: altilly.com

### ISSUE THREAD

**Issue by mrmikeo** [ccxt/ccxt#4204]
- Exchange: https://www.altilly.com
- api: https://www.altilly.com/page/api

The altilly api is modeled after HitBTC V2 api

**Comment by An-Net** [comment]
Shutdown
https://www.altilly.com/index.html
<img width="1440" alt="Снимок экрана 2021-05-20 в 21 31 40" src="https://user-images.githubusercontent.com/51840849/119030652-db548a00-b9b2-11eb-94c5-d3516388b8a6.png">
