### ISSUE TITLE
API Keys Setup - Any function to know exactly what parameter to pass

### ISSUE THREAD

**Issue by rohit1290** [ccxt/ccxt#4211]
I have read the API Keys Setup wiki and understood there are parameters like apiKey, secret, uid and password, but not all exchange require all the parameter.
Is there any function or method that will tell me exactly which parameter to pass for each exchange.

Something like:
```
$quoinex = new \ccxt\quoinex ();
$quoinex->getParam(); // ------> This will return apiKey and secret
$1btcxe = new \ccxt\1btcxe ();
$1btcxe->getParam(); // -------> This will return only apiKey
```

**Comment by kroitor** [comment]
See the property named `requiredCredentials` on the exchange instance:
https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

```PHP
$exchange = new \ccxt\quoinex ();
var_dump ($exchange->requiredCredentials);
```

Let us know if that does not answer your question.

**Comment by rohit1290** [comment]
Thank you, I can work on $exchange->requiredCredentials and covert it to my required format.
Thanks :)
