### ISSUE TITLE
Fixed point variables

### ISSUE THREAD

**Issue by donaldinho** [ccxt/ccxt#4212]
Are there any plans to move to storing numbers with some sort of fixed point representation internally in CCXT? At the moment precision is lost by storing balances etc as floats

**Comment by kroitor** [comment]
> Are there any plans to move to storing numbers with some sort of fixed point representation internally in CCXT?

Yep, this is something we're going to add, hopefully soon, the work is on and we're making progress on it.

I suggest to move this discussion here: https://github.com/ccxt/ccxt/issues/522
