### ISSUE TITLE
Error: Cryptopia fetchDeposits not supported yet

### ISSUE THREAD

**Issue by saikatharryc** [ccxt/ccxt#4215]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: OSX
- Programming Language version: Node.js 8.10
- CCXT version:1.17.432
- Exchange: Cryptopia
- Method: fetchDeposits
While trying to use method fetchDeposits on cryptopia  getting error:
`Error: Cryptopia fetchDeposits not supported yet`

**Comment by kroitor** [comment]
@saikatharryc update to most recent version, this functionality was added a few days ago: https://github.com/ccxt/ccxt/pull/4176
