### ISSUE TITLE
not able to edit orders 

### ISSUE THREAD

**Issue by GenesisGupta** [ccxt/ccxt#4216]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10
- Programming Language version: Python
- CCXT version: 1.17.481
- Exchange: Okex
- Method: Edit Order

BasicBid = orderbookLong['bids'][0][0] # Current Best Bid of the Orderbook 
BasicAsk = orderbookLong['asks'][0][0]# Current Best Ask of the Orderbook

if (CurrentBestBidPriceOS != BasicBid): # if my placed bid is not equal to best bid 
    
     site.edit_limit_buy_order(resultLong['id'],symbol , BasicBid+0.00000001)
    

if (CurrentBestAskPriceOS != BasicAsk):
    
     site.edit_limit_sell_order(resultShort['id'],symbol , BasicAsk+0.00000001)

this throws a error : 

okex edit_order() requires enableRateLimit = true

which comes from here : 

Line 1438 - Line 1442 in 

C:\AnacondaPython3_6\DeepLearning_Udemy\lib\site-packages\ccxt\base\exchange.py in edit_limit_buy_order(self, id, symbol, *args)
   1426 
   1427     def edit_limit_buy_order(self, id, symbol, *args):
-> 1428         return self.edit_limit_order(id, symbol, 'buy', *args)
   1429 
   1430     def edit_limit_sell_order(self, id, symbol, *args):

C:\AnacondaPython3_6\DeepLearning_Udemy\lib\site-packages\ccxt\base\exchange.py in edit_limit_order(self, id, symbol, *args)
   1432 
   1433     def edit_limit_order(self, id, symbol, *args):
-> 1434         return self.edit_order(id, symbol, 'limit', *args)
   1435 
   1436     def edit_order(self, id, symbol, *args):

C:\AnacondaPython3_6\DeepLearning_Udemy\lib\site-packages\ccxt\base\exchange.py in edit_order(self, id, symbol, *args)
   1436     def edit_order(self, id, symbol, *args):
   1437         if not self.enableRateLimit:
-> 1438             self.raise_error(ExchangeError, details='edit_order() requires enableRateLimit = true')
   1439         self.cancel_order(id, symbol)
   1440         return self.create_order(symbol, *args)

C:\AnacondaPython3_6\DeepLearning_Udemy\lib\site-packages\ccxt\base\exchange.py in raise_error(self, exception_type, url, method, error, details)
    342             error = str(error)
    343         output = ' '.join([self.id] + [var for var in (url, method, error, details) if var is not None])
--> 344         raise exception_type(output)
    345 
    346     def throttle(self):

ExchangeError: okex edit_order() requires enableRateLimit = true

it is asking to do : enableRateLimit = true , where would this be done ?

**Comment by kroitor** [comment]
> it is asking to do : enableRateLimit = true , where would this be done ?

- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
