### ISSUE TITLE
Is there a method to get the transaction time from Exchange A to B?

### ISSUE THREAD

**Issue by Arrmlet** [ccxt/ccxt#4218]
Hi everyone, I'm enjoying ccxt  library. 
Is exist a method which can count a transaction time from Exchange A to B, or something similar?
- Ubuntu:
- Python:
- newest:
- All:
- I don't know:

**Comment by kroitor** [comment]
Hi!

> Is exist a method which can count a transaction time from Exchange A to B, or something similar?

Inside CCXT – no, but CCXT gives you the right tools to create such a method )

**Comment by Arrmlet** [comment]
Thank you for the fast response :)
