### ISSUE TITLE
Cannot pip install ccxt on MacOS X Mojave 10.14.1

### ISSUE THREAD

**Issue by Tilanthi** [ccxt/ccxt#4220]
Hi there - could you please help me to understand why my system is not able to complete installing ccxt on a Mac Powerbook running MacOS Mojave 10.14.1 - gcc is complaining that various files are missing. I add a grep of my path at the end. Many thanks

MCL279061:~ gjw255$ sudo -H pip install ccxt
Password:
Collecting ccxt
  Downloading https://files.pythonhosted.org/packages/73/4f/61b49d9088d70b61cf30ec6bd621f0b6f90221f876d8f78d6c7a94241662/ccxt-1.17.535-py2.py3-none-any.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 3.2MB/s 
Requirement already satisfied: aiohttp>=3.0.1; python_version >= "3.5.2" in ./anaconda3/lib/python3.6/site-packages (from ccxt) (3.4.4)
Requirement already satisfied: yarl==1.1.0; python_version >= "3.5.2" in ./anaconda3/lib/python3.6/site-packages (from ccxt) (1.1.0)
Requirement already satisfied: certifi>=2018.1.18 in ./anaconda3/lib/python3.6/site-packages (from ccxt) (2018.1.18)
Requirement already satisfied: requests>=2.18.4 in ./anaconda3/lib/python3.6/site-packages (from ccxt) (2.18.4)
Requirement already satisfied: setuptools>=38.5.1 in ./anaconda3/lib/python3.6/site-packages (from ccxt) (40.4.3)
Collecting aiodns==1.1.1; python_version >= "3.5.2" (from ccxt)
  Downloading https://files.pythonhosted.org/packages/bd/f5/b69cb930fd5ab0569396659afe3f3c0d37d4098e5d0ba6afdf6fd9388cb0/aiodns-1.1.1-py2.py3-none-any.whl
Requirement already satisfied: multidict<5.0,>=4.0 in ./anaconda3/lib/python3.6/site-packages (from aiohttp>=3.0.1; python_version >= "3.5.2"->ccxt) (4.4.2)
Requirement already satisfied: async-timeout<4.0,>=3.0 in ./anaconda3/lib/python3.6/site-packages (from aiohttp>=3.0.1; python_version >= "3.5.2"->ccxt) (3.0.1)
Requirement already satisfied: attrs>=17.3.0 in ./anaconda3/lib/python3.6/site-packages (from aiohttp>=3.0.1; python_version >= "3.5.2"->ccxt) (17.4.0)
Requirement already satisfied: idna-ssl>=1.0; python_version < "3.7" in ./anaconda3/lib/python3.6/site-packages (from aiohttp>=3.0.1; python_version >= "3.5.2"->ccxt) (1.1.0)
Requirement already satisfied: chardet<4.0,>=2.0 in ./anaconda3/lib/python3.6/site-packages (from aiohttp>=3.0.1; python_version >= "3.5.2"->ccxt) (3.0.4)
Requirement already satisfied: idna>=2.0 in ./anaconda3/lib/python3.6/site-packages (from yarl==1.1.0; python_version >= "3.5.2"->ccxt) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in ./anaconda3/lib/python3.6/site-packages (from requests>=2.18.4->ccxt) (1.22)
Collecting pycares>=1.0.0 (from aiodns==1.1.1; python_version >= "3.5.2"->ccxt)
  Downloading https://files.pythonhosted.org/packages/89/5c/3a7e1a52d6abb52b9ca1a56d2df699936e89d8b98f75cfd60d03363e7c10/pycares-2.3.0.tar.gz (224kB)
    100% |████████████████████████████████| 225kB 1.3MB/s 
Building wheels for collected packages: pycares
  Running setup.py bdist_wheel for pycares ... error
  Complete output from command /Users/gjw255/anaconda3/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-462b0ob_/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/tmp/pip-wheel-k_9k694r --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.6
  creating build/lib.macosx-10.7-x86_64-3.6/pycares
  copying pycares/errno.py -> build/lib.macosx-10.7-x86_64-3.6/pycares
  copying pycares/_version.py -> build/lib.macosx-10.7-x86_64-3.6/pycares
  copying pycares/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/pycares
  copying pycares/__main__.py -> build/lib.macosx-10.7-x86_64-3.6/pycares
  running build_ext
  building 'pycares._core' extension
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/src
  creating build/temp.macosx-10.7-x86_64-3.6/deps
  creating build/temp.macosx-10.7-x86_64-3.6/deps/c-ares
  creating build/temp.macosx-10.7-x86_64-3.6/deps/c-ares/src
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/gjw255/anaconda3/include -arch x86_64 -I/Users/gjw255/anaconda3/include -arch x86_64 -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE=1 -I/Users/gjw255/anaconda3/include/python3.6m -Ideps/c-ares/src -Ideps/c-ares/src/config_darwin -c src/pycares.c -o build/temp.macosx-10.7-x86_64-3.6/src/pycares.o
  In file included from /opt/local/lib/gcc6/gcc/x86_64-apple-darwin16/6.3.0/include-fixed/syslimits.h:7:0,
                   from /opt/local/lib/gcc6/gcc/x86_64-apple-darwin16/6.3.0/include-fixed/limits.h:34,
                   from /Users/gjw255/anaconda3/include/python3.6m/Python.h:11,
                   from src/pycares.h:7,
                   from src/pycares.c:2:
  /opt/local/lib/gcc6/gcc/x86_64-apple-darwin16/6.3.0/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
   #include_next <limits.h>  /* recurse down to the real one */
                                                               ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pycares
  Running setup.py clean for pycares
Failed to build pycares
Installing collected packages: pycares, aiodns, ccxt
  Running setup.py install for pycares ... error
    Complete output from command /Users/gjw255/anaconda3/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-462b0ob_/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-x8e7r682/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/pycares
    copying pycares/errno.py -> build/lib.macosx-10.7-x86_64-3.6/pycares
    copying pycares/_version.py -> build/lib.macosx-10.7-x86_64-3.6/pycares
    copying pycares/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/pycares
    copying pycares/__main__.py -> build/lib.macosx-10.7-x86_64-3.6/pycares
    running build_ext
    building 'pycares._core' extension
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/src
    creating build/temp.macosx-10.7-x86_64-3.6/deps
    creating build/temp.macosx-10.7-x86_64-3.6/deps/c-ares
    creating build/temp.macosx-10.7-x86_64-3.6/deps/c-ares/src
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/gjw255/anaconda3/include -arch x86_64 -I/Users/gjw255/anaconda3/include -arch x86_64 -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE=1 -I/Users/gjw255/anaconda3/include/python3.6m -Ideps/c-ares/src -Ideps/c-ares/src/config_darwin -c src/pycares.c -o build/temp.macosx-10.7-x86_64-3.6/src/pycares.o
    In file included from /opt/local/lib/gcc6/gcc/x86_64-apple-darwin16/6.3.0/include-fixed/syslimits.h:7:0,
                     from /opt/local/lib/gcc6/gcc/x86_64-apple-darwin16/6.3.0/include-fixed/limits.h:34,
                     from /Users/gjw255/anaconda3/include/python3.6m/Python.h:11,
                     from src/pycares.h:7,
                     from src/pycares.c:2:
    /opt/local/lib/gcc6/gcc/x86_64-apple-darwin16/6.3.0/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
     #include_next <limits.h>  /* recurse down to the real one */
                                                                 ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/gjw255/anaconda3/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-462b0ob_/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-x8e7r682/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-462b0ob_/pycares/

MCL279061:~ gjw255$ env | grep ^PATH
PATH=/Users/gjw255/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/Users/glenn/astrodata/+GETSOURCES/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/miriad/darwin_x86_64/bin:/Users/glenn/astrodata/Montage/montage/bin:/usr/local/gcc/usr/local/bin:/mopex:/usr/local/gcc/bin:/Applications/exelis/idl83/bin:/Applications/CASA.app/Contents/MacOS:/star-2016A/bin/startcl:/star-2016A/bin:/star-2016A/starjava/bin

**Comment by kroitor** [comment]
Hope this answers your question: https://github.com/ccxt/ccxt/issues/4020
Let us know if not.
