### ISSUE TITLE
Unable to fetch all trades  from Binance  without sending symbol

### ISSUE THREAD

**Issue by gj315** [ccxt/ccxt#4228]
Hi,
I am unable to fetch all my trades from binance exchange

OS: ubuntu 16
Programming Language version: Node.js (10.13.0)
CCXT version:1.17.458
Exchange:Binance
Method: fetchMyTrades
my call is this like -
req.exchange.fetchMyTrades();

I am getting this error can you please help me,

![image](https://user-images.githubusercontent.com/37790362/48992486-f46f7d80-f15d-11e8-82f8-815150108155.png)

**Comment by kroitor** [comment]
Hi!

You have to add a symbol argument to it, literally, as the error message is telling you (most exchanges will require it).

```JavaScript
const symbol = 'ETH/BTC'
req.exchange.fetchMyTrades(symbol);
```

https://github.com/ccxt/ccxt/wiki/Manual#recent-trades

**Comment by SimonEast** [comment]
Yes, I was just trying to do the same thing. It doesn't seem possible to fetch ALL trades/orders, regardless of symbol. 

A *LOT* of developers have been complaining (rightfully) about this limitation of the Binance API, see https://dev.binance.vision/t/fetch-all-account-orders/279/61

**Comment by kroitor** [comment]
@SimonEast thx for your feedback!
