### ISSUE TITLE
ccxt base project for backtest strategies?

### ISSUE THREAD

**Issue by lfern** [ccxt/ccxt#4229]
Do you know any project based on ccxt for backtesting strategies??

**Comment by kroitor** [comment]
I know of *backtrader*: https://community.backtrader.com/topic/623/anyone-use-backtrader-to-do-live-trading-on-bitcoin-exchange but apart from that, don't know if there's any other package that does backtesting on crypto. Backtesting is often a part of some larger bot framework.

**Comment by kroitor** [comment]
Also: https://backtest-rookies.com/2018/03/08/download-cryptocurrency-data-with-ccxt/

**Comment by samgermain** [comment]
There is also [freqtrade](https://github.com/freqtrade/freqtrade)
