### ISSUE TITLE
Fetching Orders for last one day on okex ? 

### ISSUE THREAD

**Issue by GenesisGupta** [ccxt/ccxt#4230]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10
- Programming Language version: Python 3.6.7
- CCXT version: 1.17.482
- Exchange: Okex
- Method: FetchMyTrades || FetchClosedOrders

import random

import time

import ccxt

import pandas as pd 

market = ""

site = ccxt.okex({
   
    "apiKey": "",
    "secret" : "",
    
    'enableRateLimit': True,    
    
})

# exchange = okex

yesterdaytrades = site.fetchClosedOrders(market,limit = 20000)

# print(yesterdaytrades)

yesterdaytradesDF = pd.DataFrame.from_dict(yesterdaytrades)
# OpenOrderDF = OpenOrderDF[['price']]*10000

print("________________________________________________________________")

print(yesterdaytradesDF[['datetime','id','side','price','amount']])

# print(OpenOrderDF.columns)

print("________________________________________________________________")

this only gives last 200 orders , how do i make it fetch all orders from yesterday.

**Comment by kroitor** [comment]
Please, use triple backticks to format the code for readability next time... 

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by kroitor** [comment]
> how do i make it fetch all orders from yesterday.

Please read this section of the Manual carefully: https://github.com/ccxt/ccxt/wiki/Manual#pagination
This should answer the question, let us know if not.

**Comment by GenesisGupta** [comment]
`import random

import time

import ccxt

import pandas as pd 

from datetime import datetime

limit = 10

market = ""

site = ccxt.okex({
   
    "apiKey": "",
    "secret" : "",
    
    'enableRateLimit': True,    
    
})

# Python
if site.has['fetchOrders']:
    since = site.milliseconds () - 86400000  # -1 day from now
    # alternatively, fetch from a certain starting datetime
    # since = exchange.parse8601('2018-01-01T00:00:00Z')
    all_orders = []
    while since < site.milliseconds ():
        symbol = None  # change for your symbol
        limit = 20  # change for your limit
        orders = await site.fetch_orders(symbol, since, limit)
        if len(orders):
            since = orders[len(orders) - 1]
            all_orders += orders
        else:
            break

print(all_orders)

"""
# exchange = okex

yesterdaytrades = site.fetchClosedOrders(market,limit = 20000)

# print(yesterdaytrades)

yesterdaytradesDF = pd.DataFrame.from_dict(yesterdaytrades)
# OpenOrderDF = OpenOrderDF[['price']]*10000

print("________________________________________________________________")

print(yesterdaytradesDF[['datetime','id','side','price','amount']])

# print(OpenOrderDF.columns)

print("________________________________________________________________")

"""
`

this does not work 

can you please provide a example how to draw orders for one day ... an example would really help

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/blob/master/examples/py/okex-fetch-closed-orders-pagenumber-pagination.py
- https://github.com/ccxt/ccxt/wiki/Manual#pagenumber-based-cursor-pagination

```Python
# -*- coding: utf-8 -*-

import os
import sys
from pprint import pprint

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402

'''
This is an example of pagenumber-based pagination as described here:
https://github.com/ccxt/ccxt/wiki/Manual#pagenumber-based-cursor-pagination
'''

symbol = 'ETH/BTC'

exchange = ccxt.okex({

    'apiKey': 'YOUR_API_KEY',  # put your values here
    'secret': 'YOUR_SECRET',

    'enableRateLimit': True,  # or add .enableRateLimit = True later
})

def get_all_closed_orders_since_to (exchange, symbol, since, to):
    result = []
    page = 1
    min_timestamp = to
    print('Fetching all orders since', exchange.iso8601(since), since)
    while min_timestamp > since:
        try:
            print('Fetching page', page)
            params = { 'current_page': page }
#            if page == 6:
#                exchange.verbose = True
            orders = exchange.fetch_closed_orders(symbol, since, None, params)
            if len(orders):
                min_timestamp = orders[0]['timestamp']
                print('Fetched', len(orders), 'orders, the oldest order as of', exchange.iso8601(min_timestamp), min_timestamp)
                result += orders
                page += 1
            else:
                min_timestamp = since
        except ccxt.ExchangeNotAvailable as e:
            pass # retry
    return result

one_day = 24 * 60 * 60 * 1000  # in milliseconds
since = exchange.parse8601 ('2018-11-26T00:00:00')  # 0:00 AM UTC in milliseconds
# or
since = exchange.milliseconds () - one_day # last 24 hours in milliseconds

to = since + one_day

all_orders = get_all_closed_orders_since_to(exchange, symbol, since, to)

all_orders = exchange.sort_by(all_orders, 'timestamp')

print('Fetched all', len(all_orders), 'orders')
print('The oldest order as of', exchange.iso8601(all_orders[0]['timestamp']))
print('The youngest order as of', exchange.iso8601(all_orders[-1]['timestamp']))
print('Done.')

```

**Comment by GenesisGupta** [comment]
But this only gives orders for the last 2 days no matter if i say 

since = exchange.parse8601 ('2018-11-20T00:00:00')  # 0:00 AM UTC in milliseconds

to = since + (one_day*5)

this also gives orders from current time going back just 2 days.... 

is it a okex problem since when we try to download bills from it website , it partitions them for last 2 days , 2 + days ?

**Comment by kroitor** [comment]
> But this only gives orders for the last 2 days no matter if i say

This is a known limitation of OKEX

https://github.com/okcoin-okex/API-docs-OKEx.com/blob/master/API-For-Spot-EN/REST%20API%20for%20SPOT.md

![okex-limitations](https://user-images.githubusercontent.com/1294454/49086563-ddb44e00-f265-11e8-9f17-d2f8ce402725.jpg)
