### ISSUE TITLE
Fetching Closed orders from Okex via CCXT ? 

### ISSUE THREAD

**Issue by GenesisGupta** [ccxt/ccxt#4232]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10
- Programming Language version: Python 3.6.7
- CCXT version: 1.17.482
- Exchange: Okex
- Method: FetchMyTrades

`import random

import time

import ccxt

import pandas as pd

from datetime import datetime

limit = 10

market = ""

site = ccxt.okex({

"apiKey": "",
"secret" : "",

'enableRateLimit': True,    
})

if site.has['fetchOrders']:
since = site.milliseconds () - 86400000 # -1 day from now
# alternatively, fetch from a certain starting datetime
# since = exchange.parse8601('2018-01-01T00:00:00Z')
all_orders = []
while since < site.milliseconds ():
symbol = None # change for your symbol
limit = 20 # change for your limit
orders = await site.fetch_orders(symbol, since, limit)
if len(orders):
since = orders[len(orders) - 1]
all_orders += orders
else:
break

this gives an error at await ? 

this does not work

can you please provide a example how to draw orders for one day ... an example would really help

**Comment by kroitor** [comment]
See the answer here: https://github.com/ccxt/ccxt/issues/4230#issuecomment-441748691
