### ISSUE TITLE
How to close a stop loss order on Bitmex? 如何在平掉止损

### ISSUE THREAD

**Issue by 317459062** [ccxt/ccxt#4234]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:windows 10
- Programming Language version:
- CCXT version:lastest
- Exchange:bitmex
- Method:

**Comment by frosty00** [comment]
you can call `cancelOrder (orderId)`
