### ISSUE TITLE
fetch_ohlcv determine limit per exchange

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#4236]
- OS: LInux
- Programming Language version: python3.7
- CCXT version: '1.17.363'
- Exchange: multiple
- Method: fetch_ohlcv

when using the following code, i get different results depending on the exchange.
I understand that it's exchange-dependent what the upper limit is, but is there a way to know what this limit is (and the default parameter) for the exchange i'm currently querying before making the first call?

```
import ccxt
from datetime import datetime, timezone
start = datetime.strptime("01.10.2018", "%d.%m.%Y").replace(
           tzinfo=timezone.utc).timestamp()
timeframe='1h'
limit=None
binance = ccxt.binance()
hitbtc = ccxt.hitbtc2()
kraken = ccxt.kraken()

hitbtc_ohlcv = hitbtc.fetch_ohlcv("ETH/BTC", timeframe=timeframe, since=int(start*1000), limit=limit)
binance_ohlcv = binance.fetch_ohlcv("ETH/BTC", timeframe=timeframe, since=int(start*1000), limit=limit)
kraken_ohlcv = kraken.fetch_ohlcv("ETH/BTC", timeframe=timeframe, since=int(start*1000), limit=limit)

print(f"hitbtc: {len(hitbtc_ohlcv)}")
print(f"binance: {len(binance_ohlcv)}")
print(f"kraken: {len(kraken_ohlcv)}")

```

Output
```
hitbtc: 1000
binance: 1000
kraken: 720
```

in addition to that, the default seems to vary - using `limit=None` in the above code returns a different output for hitbtc:
```
hitbtc: 100
binance: 500
kraken: 720
```

**Comment by kroitor** [comment]
> is there a way to know what this limit is (and the default parameter) for the exchange i'm currently querying before making the first call?

Currently – without looking into the code – nope, unfortunately, it's just one of the aspects that is not unified completely yet, but we surely want to unify it as well. We have plans on proposing a much better approach to pagination, hopefully, soon. 

Let us know if that does not answer your question, feel free to reopen it if needed.
