### ISSUE TITLE
python fetchWithdrawals / fetchDeposits on Cryptopia not working (newest version)

### ISSUE THREAD

**Issue by MarcelBeining** [ccxt/ccxt#4237]
- OS: Windows
- Programming Language version: Python 3.6
- CCXT version: 1.17.543
- Exchange: Cryptopia
- Method: fetchWithdrawals / fetchDeposits

When trying to execute fetchWithdrawals or fetchDeposits I get the following error:
```
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\cryptopia.py", line 484, in fetch_withdrawals
    return self.fetch_transactions_by_type('deposit', code, since, limit, params)

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\cryptopia.py", line 481, in fetch_transactions_by_type
    return self.parseTransactions(response['Data'], code, since, limit)

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1322, in parse_transactions
    array = [self.parse_transaction(transaction, currency) for transaction in array]

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1322, in <listcomp>
    array = [self.parse_transaction(transaction, currency) for transaction in array]

TypeError: parse_transaction() takes 2 positional arguments but 3 were given
```

Replacing 
`def parse_transaction(self, transaction):
`with
`def parse_transaction(self, transaction,currency=None):`

in cryptopia.py at line 394 fixes it, but I did not check if this would harm any other call to that function.

**Comment by MarcelBeining** [comment]
Thanks for fast fix, but you only fixed it in JS in [2c34c4c](https://github.com/ccxt/ccxt/commit/2c34c4c1cf38c3a4aef83ebee20f74446afe220d) so far, not python :-)

**Comment by kroitor** [comment]
We've anticipated this question: https://github.com/ccxt/ccxt/wiki/FAQ#hey-the-fix-youve-uploaded-is-in-js-would-you-fix-python--php-as-well-please )

**Comment by kroitor** [comment]
@MarcelBeining PS it usually takes 5-10 minutes for the new version to arrive to pypi...
