### ISSUE TITLE
Better endpoint for fetchDeposits/fetchWithdrawals

### ISSUE THREAD

**Issue by MarcelBeining** [ccxt/ccxt#4238]
OS: Windows
Programming Language version: Python 3.6
CCXT version: 1.17.543
Exchange: Kraken
Method: fetchWithdrawals / fetchDeposits

Currently, the fetchDeposits (fetchWithdrawals is analog) method seem to use the [DepositStatus](https://www.kraken.com/en-us/help/api#deposit-status) endpoint of the kraken API, however this only returns the very recent deposits! To get the full deposit/withdrawal history, could you please marke use of the [Ledgers](https://www.kraken.com/en-us/help/api#get-ledgers-info) endpoint and use deposit / withdrawal as "type" input parameter?

**Comment by kroitor** [comment]
Related: https://github.com/ccxt/ccxt/pull/4179#discussion_r234382095

**Comment by bmcheewing** [comment]
“Type”? Help

**Comment by MarcelBeining** [comment]
> “Type”? Help

What do you mean? Concerning what "Type" can be, see kraken API documentation:

![image](https://user-images.githubusercontent.com/1278660/49140642-13544800-f2f5-11e8-9415-a997bb24dc01.png)

**Comment by MarcelBeining** [comment]
Here is what I got from the Kraken support, maybe the info helps:

If you are interested in returning historical deposits and withdrawals, one way for you to do so would be to use the Ledgers endpoint:
https://www.kraken.com/help/api#get-ledgers-info
With this call you will be able to filter your ledger history for all deposits, withdrawals, trades or margin trades by using the 'type' parameter.

Please note, the Ledgers endpoint will only return 50 results at one time. To return data past the initial 50 results, the 'ofs', or offset parameter should be used. 
You can review an example of this in the following support article. 
https://support.kraken.com/hc/en-us/articles/360000912103-Trade-History

Additionally, you may use the DepositStatus and WithdrawalStatus endpoints to return data about recent deposits and withdrawals respectively. However this call will only provide information on funding activity made within the last ~90 days.

**Comment by MarcelBeining** [comment]
any news on that? getting all deposits/withdrawals is crucial for tax calculation

**Comment by kroitor** [comment]
@MarcelBeining yep, we had some progress on this issue here: https://github.com/ccxt/ccxt/pull/4256#issuecomment-447682884 and we are about to finally have a breakthrough on this aspect! Will upload those initial edits for Kraken very soon.

**Comment by kroitor** [comment]
Kraken `fetchLedger` has been added here: https://github.com/ccxt/ccxt/pull/4603
