### ISSUE TITLE
** unexpected token when start app. it looks like not compatible

### ISSUE THREAD

**Issue by jj0012006** [ccxt/ccxt#4249]
https://github.com/ccxt/ccxt/blob/7d3e563806746ae83110948447ac6e6edf13b745/js/base/Exchange.js#L1338

**Comment by Matoran** [comment]
Hello, why you do not use the default template ? We need more data to solve your problem.

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by kroitor** [comment]
@jj0012006 please follow the guides posted by @Matoran precisely (literally, to a word), we can't really help, unless you provide the necessary info.

- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

**Comment by kroitor** [comment]
@jj0012006 closing this for until we have a followup from you. Feel free to reopen it if needed or just ask further questions, we will be happy to answer, if you provide the necessary info as described above.
