### ISSUE TITLE
how to fetch price for market orders

### ISSUE THREAD

**Issue by ceaser1996** [ccxt/ccxt#4250]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:ubuntu
- Programming Language version:php 7.2
- CCXT version:latest
- Exchange:coinbasepro/kraken
- Method:
how to fetch price for market orders, I am  always getting it null .

**Comment by kroitor** [comment]
Duplicate: #4251
