### ISSUE TITLE
how to fetch price for market orders

### ISSUE THREAD

**Issue by ceaser1996** [ccxt/ccxt#4251]
- OS:Ubuntu
- Programming Language version:Php 7.2
- CCXT version:Latest
- Exchange:Coinbase/Kraken
- Method:_

how to fetch a price for market orders. I always get the price as null if I fetch the order using 
$gdax->fetchOrder('orderid')

**Comment by Matoran** [comment]
You need to use id returned by `createOrder` then use it in `fetchOrder($id)`. Otherwise you can use `fetchOrders` if you don't know the id.

You can read more about that in manual https://github.com/ccxt/ccxt/wiki/Manual#querying-orders

**Comment by caeser1996** [comment]
Always I am getting null in return

**Comment by caeser1996** [comment]
Status is closed and it was a buy order with order type market still I am getting it null in price wheareas in coinbase account m able to see a proce why so

**Comment by caeser1996** [comment]
I am creating the order using createMarketOrder

**Comment by caeser1996** [comment]
I know the id still i get an array of all data mentioned like fees and all but price is null always

**Comment by Matoran** [comment]
I do not have this problem, please give us some output and active verbose mod.

**Comment by kroitor** [comment]
@ceaser1996 we need you to follow these guides precisely (to a word):

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

Namely, we need a short snippet of complete code (not just one line, but 10-20 lines) to reproduce the issue (without your keys) and your verbose request/response for the problematic call.

**Comment by kroitor** [comment]
Closing this until we have a followup, feel free to reopen it if needed or just ask further questions, if any. Thx to @Matoran for the help!
