### ISSUE TITLE
How to withdraw coins with memo id?

### ISSUE THREAD

**Issue by Arrmlet** [ccxt/ccxt#4253]
- Ubuntu:
- Python3.6:
- newest:
- Poloniex and Binance:
- withdraw:

Hi, how I can withdraw a coins which need extra infomation(memo/text id) like EOS or stellar, with withdraw function

**Comment by kroitor** [comment]
Hi!

> Hi, how I can withdraw a coins which need extra infomation(memo/text id) like EOS or stellar, with withdraw function

You can do that by supplying the tag argument to the withdraw function as described here: 

- https://github.com/ccxt/ccxt/wiki/Manual#deposit
- https://github.com/ccxt/ccxt/wiki/Manual#withdraw

Let us know if that does not answer your question.
