### ISSUE TITLE
Bithumb fetch_balance() Auth Data Error in php

### ISSUE THREAD

**Issue by ztlj521** [ccxt/ccxt#4255]
When i use bithumb in php, it come up an error. next is my code.

$exchange = new \ccxt\bithumb (array(
    'apiKey' => '***', // ←------------ replace with your keys
    'secret' => '****',
    'verbose' => true, // uncomment if debug output is needed
));
$balance = $exchange->fetch_balance ();
var_dump ($balance);

Error:
 {"status":"5100","message":"Bad Request.(Auth Data)"} ) 

( ! ) Fatal error: Uncaught exception 'ccxt\ExchangeError' with message 'bithumb {"status":"5100","message":"Bad Request.(Auth Data)"}' in D:\soft\WWW\ccxt\php\bithumb.php on line 377
--
1 | 0.0040 | 134248 | {main}( ) | ...\huobi-fetch-balance.php:0
2 | 0.0380 | 879456 | ccxt\bithumb->fetch_balance( ) | ...\huobi-fetch-balance.php:23
3 | 7.0454 | 1259792 | privatePostInfoBalance ( ) | ...\bithumb.php:120
4 | 7.0454 | 1259992 | ccxt\Exchange->__call( ) | ...\bithumb.php:120
5 | 7.0454 | 1260024 | call_user_func_array:{D:\soft\WWW\ccxt\php\Exchange.php:2035} ( ) | ...\Exchange.php:2035
6 | 7.0454 | 1260224 | ccxt\Exchange->ccxt\{closure}( ) | ...\Exchange.php:2035
7 | 7.0454 | 1260472 | call_user_func:{D:\soft\WWW\ccxt\php\Exchange.php:930} ( ) | ...\Exchange.php:930
8 | 7.0454 | 1260496 | ccxt\bithumb->request( ) | ...\Exchange.php:930
9 | 7.0454 | 1260560 | ccxt\Exchange->fetch2( ) | ...\bithumb.php:387
10 | 7.0454 | 1262024 | ccxt\Exchange->fetch( ) | ...\Exchange.php:1001
11 | 7.4764 | 1216056 | ccxt\bithumb->handle_errors( ) | ...\Exchange.php:1180

I'm looking for your help, Thank you!

**Comment by ztlj521** [comment]
I  tried the cli.php file, but it doesn't work.  Bithumb exchange can't use the method get_blance in this way?

$exchange = new \ccxt\bithumb (array(
'apiKey' => '', // ←------------ replace with your keys
'secret' => '*',
'verbose' => true, // uncomment if debug output is needed
));
$balance = $exchange->fetch_balance ();
var_dump ($balance);

if this code need add same rection， so that i can use it. thank you ,I'm a novice. sorry to trouble you.

**Comment by kroitor** [comment]
@ztlj521 unfortunately, bithumb does not recognize my account anymore, and it does not want to let me in even after signing up the second time – it just says:

<img width="528" alt="screen shot 2018-12-01 at 06 10 36" src="https://user-images.githubusercontent.com/1294454/49323659-dc1dab00-f52f-11e8-8471-004463f9624b.png">

or

<img width="520" alt="screen shot 2018-12-01 at 06 02 43" src="https://user-images.githubusercontent.com/1294454/49323661-e0e25f00-f52f-11e8-8b46-7c71a8436045.png">

Something is deeply broken with their signup/signin procedure...

@ztlj521 can you send me an api keypair (the api key and the secret) with zero balance for testing and debugging purposes to igor@ccxt.trade? If you can, that would be very helpful. We don't need your money or your information, just want to fix the fetchBalance code, so you will then delete the API key as soon as we finish fixing it. If you can not do that, no worries, we will find other ways to get there.

**Comment by ZerglingGo** [comment]
@kroitor It looks like you haven't API keypair yet. I sent keypair to your mail.

**Comment by kroitor** [comment]
Ok, we have found the cause and fixed it in CCXT version 1.18.61+ (it was PHP-specific). Many thanks to @ZerglingGo who has provided the key for debugging, we really appreciate your help! Let us know if you encounter any other difficulties with it ) Your feedback is welcome!
