### ISSUE TITLE
How to check is the coin can be withdrawn from binance

### ISSUE THREAD

**Issue by Arrmlet** [ccxt/ccxt#4257]
- ubuntu:
- python:
- newest:
- binance:
- idk:

Hi, how I can check is the coin can be withdrawn from binance. For example on poloniex I use this command
`poloniex.currencies['coin']['active']`

**Comment by kroitor** [comment]
We currently don't have this aspect fully unified, but we have plans on adding the support for their assetDetail WAPI endpoint (https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#asset-detail-user_data).

In the meantime, you can fetch the status like so:

```Python
exchange = ccxt.binance ({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
})
exchange.load_markets()
response = exchange.wapi_get_assetdetail()
code = 'ETH'
currency = exchange.currency(code)
currency_id = currency['id']
withdraw_status = response['assetDetail'][currency_id]['withdrawStatus']  # True or False
if withdraw_status:
    print('We can withdraw', code)
else:
    print('We cannot withdraw', code)
```

**Comment by Arrmlet** [comment]
@kroitor thx for fast responce. Your library is the best in crypto sphere;)
