### ISSUE TITLE
async_support cann't work 

### ISSUE THREAD

**Issue by tomcatren2018** [ccxt/ccxt#4258]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: window 10
- Programming Language version: python3.6
- CCXT version:  ccxt	1.17.134	
- Exchange:okex
- Method:N/A

when I use async_support, the code run wrong, how to slove it ! can you help me? I am use python 3.6 on windows 10 .The test code is below:

import asyncio
import ccxt.async_support as ccxt

async def getticker():
    exchange = ccxt.okex({'proxy': 'https://cors-anywhere.herokuapp.com/'})  # ←------- added proxy here
    ticker = await exchange.fetch_order_book('BTC/USDT', 1)['bids'][0][0]
    await exchange.close()
    print(ticker)
asyncio.get_event_loop().run_until_complete(getticker())

and the result is 👍 

  File "D:/newtest/test03.py", line 6, in getticker
    ticker = await exchange.fetch_order_book('BTC/USDT', 1)['bids'][0][0]
TypeError: 'coroutine' object is not subscriptable
okex requires to release all resources with an explicit call to the .close() coroutine. If you are creating the exchange instance from within your async coroutine, add exchange.close() to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x04C03650>

but i already use exchange.close() when i don't need the exchange

**Comment by kroitor** [comment]
Let us know if this does not answer the question:

- https://github.com/ccxt/ccxt/blob/master/examples/py/async-basic-orderbook.py

```Python
# -*- coding: utf-8 -*-

import asyncio
import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt.async_support as ccxt  # noqa: E402


async def test():

    exchange = ccxt.okex({

        # 'proxy': 'https://cors-anywhere.herokuapp.com/',
        # 'origin': 'foobar',  # when using CORS proxies, set this to some random string

        'enableRateLimit': True,  # required accoding to the Manual
    })

    try:
        orderbook = await exchange.fetch_order_book('BTC/USDT')
        await exchange.close()
        return orderbook
    except ccxt.BaseError as e:
        print(type(e).__name__, str(e), str(e.args))
        raise e


if __name__ == '__main__':
    print(asyncio.get_event_loop().run_until_complete(test()))
```

**Comment by wmltyq** [comment]
I don't add proxy, but report the same error.

**Comment by kroitor** [comment]
@wmltyq can you provide any details? Code to reproduce it? Your **verbose request/response** (without your keys, of course)? Have you tried the snippet above: https://github.com/ccxt/ccxt/issues/4258#issuecomment-443407409 ? Have you tried going through the troubleshooting section? https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

**Comment by wmltyq** [comment]
@kroitor Thank you very much. I come from China. I'm not good at English. Thank you for your patient guidance!
