### ISSUE TITLE
function edit_order on cobinhood throws Precision must be an integer

### ISSUE THREAD

**Issue by tradingbase** [ccxt/ccxt#4260]
Using Cobinhood and PHP, ccxt version 1.17.559
calling edit_order throws "Precision must be an integer"

Digging into the code, the problem is at:
file: Exchange.php
function: public function price_to_precision ($symbol, $price)

That function returns `$this->markets[$symbol]['precision']['price']` but `this->markets` is not set at that moment.
Adding `$this->load_markets ();` first solves the problem, but I am not sure, you would expect to fix it that way or another. This is, how it works for me however:

`public function price_to_precision ($symbol, $price) {
	$this->load_markets ();
        return self::decimal_to_precision ($price, ROUND, $this->markets[$symbol]['precision']['price'], $this->precisionMode);
    }`

Beside that: This library ccxt is amazing and so easy to understand and to use, thank you so much for the great work, you did!

**Comment by kroitor** [comment]
Hi!

You are required to load markets according to the Manual before calling those methods, otherwise it won't have the necessary info to work with. More about it here: https://github.com/ccxt/ccxt/wiki/Manual#loading-markets. Hope this answers your questions.

**Comment by kroitor** [comment]
I've uploaded a fix for Cobinhood's `editOrder` and `cancelOrder`, both were indeed missing the market preloading call, if you update CCXT to version 1.17.569 the issue should be resolved. Anyways, we will be happy if you let us know, whether it now works for you normally or not. Thx for reporting!

**Comment by tradingbase** [comment]
I tested the new version and the problem is solved. Many thanks for such a fast and reliable solution and all your efforts for this project!
