### ISSUE TITLE
zb fetchBalance { "code": 3005, "message": "无效癈参数" }

### ISSUE THREAD

**Issue by jackingyang** [ccxt/ccxt#4263]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:mac
- Programming Language version:python
- CCXT version:
- Exchange:zb
- Method:fetch_balance()
![2018-12-02 6 21 30](https://user-images.githubusercontent.com/6406480/49338670-8516f380-f65f-11e8-87cb-334aa948a364.png)

**Comment by kroitor** [comment]
There's a few mistakes in your code, namely, you're not using any rate-limiting, despite that it is required by the Manual: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

```
import ccxt
zb = ccxt.zb({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',  # 36 characters
    'secret': 'YOUR_SECRET',  # 36 characters
})
print(zb.fetch_balance())
```

↑ This works on my side with current version of CCXT 1.17.571. Unfortunately, you haven't mentioned your version number...

Have you tried following the troubleshooting steps literally?

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Have you used this keypair previously with any other software? Have you tried with a new keypair?

**Comment by kroitor** [comment]
I'd close this for now until we have a followup from you, feel free to reopen it if needed or just ask further questions, if any.

**Comment by jackingyang** [comment]
> There's a few mistakes in your code, namely:
> 
> * it should be api**K**ey, not api**k**ey (uppercase letter K)
> * you're not using any rate-limiting, despite that it is required by the Manual: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
> 
> ```python
> import ccxt
> zb = ccxt.zb({
>     'enableRateLimit': True,
>     'apiKey': 'YOUR_API_KEY',  # 36 characters
>     'secret': 'YOUR_SECRET',  # 36 characters
> })
> print(zb.fetch_balance())
> ```
> 
> ↑ This works on my side with current version of CCXT 1.17.571. Unfortunately, you haven't mentioned your version number... And you ignored the steps from https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
> 
> Have you tried following the troubleshooting steps literally?
> 
> * https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
> 
> Have you used this keypair previously with any other software? Have you tried with a new keypair?
> 
> * https://github.com/ccxt/ccxt/wiki/FAQ

thank you verymuch ,it's work

**Comment by kroitor** [comment]
@jackingyang thx for reporting back!
