### ISSUE TITLE
How to get deposit status from ethfinex?

### ISSUE THREAD

**Issue by vanshtah** [ccxt/ccxt#4265]
successfully got the deposit address of from ETH
but cannot get if the deposit is completed or not
please help

**Comment by kroitor** [comment]
@vanshtah have you tried calling `fetchTransactions`? 

- https://github.com/ccxt/ccxt/wiki/Manual#transactions
- https://github.com/ccxt/ccxt/wiki/Manual#all-transactions

Can you follow these guides: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

**Comment by vanshtah** [comment]
no i have'nt tried that 
will try thanks for the help.
