### ISSUE TITLE
async_support is very slowly

### ISSUE THREAD

**Issue by tomcatren2018** [ccxt/ccxt#4267]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

OS: window 10
Programming Language version: python3.6
CCXT version: ccxt	1.17.134
Exchange:okex
Method:N/A

First thank you very much to help me answer question  'async_support cann't work #4258'  but i have another problem. i find that async_support is very slow.The time to get results in the way of 'async' is more than in the way of ‘threading’,is 'proxy' the reason ?Is the ' proxy' affecting efficiency? does the ' proxy' need to spend more time?

1.the 'async' code (the exchange is using proxy) is

 exchange = ccxt.okex({

         'proxy': 'https://cors-anywhere.herokuapp.com/',
         'origin': '666666'
        'foobar': '666668'
        'enableRateLimit': True,  # required accoding to the Manual
    })

async def MainRange(firstExchange ,stop):
   row_data = sh1.row_values(stop)
   firstPair = row_data[0]
   secondPair = row_data[1]
   try:
     highBtUf = await firstExchange.fetch_order_book(secondPair, 1)
     highBtUs = await firstExchange.fetch_order_book(firstPair, 1)
     lowBtUf = await firstExchange.fetch_order_book(secondPair, 1)
     lowBtUs = await firstExchange.fetch_order_book(firstPair, 1)
     highxrow_data = [firstExchange, firstPair,secondPair,highBtUf['bids'][0][0], highBtUs['asks'][0][0],      lowBtUf['asks'][0][0], lowBtUs['bids'][0][0]]
    q.put(highxrow_data)
   except:
     pass
.....
tasks1 = []
for i in range(191):
task1 = MainRange(firstExchange, i)
tasks1.append(asyncio.ensure_future(task1))
loop = asyncio.get_event_loop()
loop.run_until_complete(asyncio.wait(tasks1))
.....

2.the ' threading' code(the exchange is not using 'proxy' ) is

 exchange = ccxt.okex({
        'enableRateLimit': True,  # required accoding to the Manual
    })
def MainRange(resultbidask,start,stop):
   firstExchange = resultbidask[0]
   for i in range(start,stop):
   row_data = sh1.row_values(i)
   firstPair = row_data[0]
   secondPair = row_data[1]
  try:
     highBtU = float(firstExchange.fetch_order_book(secondPair, 1)['bids'][0][0]) /          float(firstExchange.fetch_order_book(firstPair, 1)['asks'][0][0])
    lowBtU = float(firstExchange.fetch_order_book(secondPair, 1)['asks'][0][0]) /       float(firstExchange.fetch_order_book(firstPair, 1)['bids'][0][0])
   highxrow_data = [firstExchange, firstPair,secondPair,highBtU, lowBtU]
   q.put(highxrow_data)
except:
   pass
....
nrows = 191
mid = int(nrows/14)
threads = []
resultbidask =tuple([firstExchange])
t1 = threading.Thread(target=MainRange, args=(resultbidask,0,mid ))
threads.append(t1)
t2 = threading.Thread(target=MainRange, args=(resultbidask,mid,mid*2))
threads.append(t2)
t3 = threading.Thread(target=MainRange, args=(resultbidask, mid*2,mid*3))
threads.append(t3)
t4 = threading.Thread(target=MainRange, args=(resultbidask, mid*3, mid*4))
threads.append(t4)
t5 = threading.Thread(target=MainRange, args=(resultbidask, mid*4, mid*5))
threads.append(t5)
t6 = threading.Thread(target=MainRange, args=(resultbidask, mid*5, mid*6))
threads.append(t6)
t7 = threading.Thread(target=MainRange, args=(resultbidask, mid * 6, mid * 7))
threads.append(t7)
t8 = threading.Thread(target=MainRange, args=(resultbidask, mid * 7, mid * 8))
threads.append(t8)
t9 = threading.Thread(target=MainRange, args=(resultbidask, mid * 8, mid * 9))
threads.append(t9)
t10 = threading.Thread(target=MainRange, args=(resultbidask, mid * 9, mid * 10))
threads.append(t10)
t11 = threading.Thread(target=MainRange, args=(resultbidask, mid * 10, mid * 11))
threads.append(t11)
t12 = threading.Thread(target=MainRange, args=(resultbidask, mid * 11, mid * 12))
threads.append(t12)
t13 = threading.Thread(target=MainRange, args=(resultbidask, mid * 12, mid * 13))
threads.append(t13)
t14 = threading.Thread(target=MainRange, args=(resultbidask, mid * 13, mid * 14))
threads.append(t14)
t15 = threading.Thread(target=MainRange, args=(resultbidask, mid * 14,nrows))
threads.append(t15)
for t in threads:
    t.setDaemon(True)
    t.start()
for t in threads:
    t.join()

**Comment by kroitor** [comment]
>  i find that async_support is very slow.

That is due to rate-limiting, as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

> The time to get results in the way of 'async' is more than in the way of ‘threading’,is 'proxy' the reason ? Is the ' proxy' affecting efficiency? does the ' proxy' need to spend more time?

The proxy is influencing the speed of it, of course. But that is only a partial explanation. So, it does have to spend more time, but ultimately, the main cause of the difference is related to rate-limiting.

In your threading code you're not respecting the rate-limits. If you keep using that particular code the exchange might ban you at some point in future (if they find your multiple threaded requests too aggressive). The built-in rate-limiter is not designed to work in the threaded environment. It will only work in the async-environment. So, if you want to do proper rate-limiting to stay below limits for any particular exchange - you need to implement your own throttle that will limit the amount of threaded requests per minute in userland.

Let me know if that does not answer the question.
