### ISSUE TITLE
GDAX price too precise

### ISSUE THREAD

**Issue by anandanand84** [ccxt/ccxt#427]
Below error is thrown as Network error, but actual error should be Invalid Order.

gdax POST https://api.gdax.com/orders 400 Bad Request {\"message\":\"price too precise (309.9557461094684)\"} (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)"

Also currently there is no way to parse the exchange response, make sure always add the exchange response at first or at last of the message so parsing of the exchange response is possible.

Here https://github.com/ccxt/ccxt/blob/master/ccxt.js#L688 400 is considered Network error which is wrong, 400 is bad request and it can be caused for any type of invalid input.

**Comment by kroitor** [comment]
Hi, @anandanand84 ! Thank you for opening this issue! I will take a look into it asap.

**Comment by kroitor** [comment]
@anandanand84 

> Here https://github.com/ccxt/ccxt/blob/master/ccxt.js#L688 400 is considered Network error which is wrong, 400 is bad request and it can be caused for any type of invalid input.

This isn't really wrong, because whenever we encounter 400, it means we had a HTTP error, which is a Network Error, not any other type of logic error. What other type of error would you suggest for HTTP 400?

**Comment by anandanand84** [comment]
@kroitor Anything above 3XX is errors and 4XX errors are basically client errors and in particular 400 is consider an bad request data from the client and it doesn't necessarily mean it is a network error and it is definitely not caused by the information in possible reasons invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting. I would say 400 is bad request.

**Comment by kroitor** [comment]
@anandanand84 

> @kroitor Anything above 3XX is errors and 4XX errors are basically client errors and in particular 400 is consider an bad request data from the client and it doesn't necessarily mean it is a network error and it is definitely not caused by the information in possible reasons invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting. I would say 400 is bad request.

In the terms of the library, there's no Bad Request error, so, of the errors left, we aligned the NetworkError to stand for any error that is related to a bad HTTP status code. In other words, if I asked you, what other type of error should we assign to it, what should it be (of currently existing types, without adding a new one)?

**Comment by anandanand84** [comment]
InvalidOrder

**Comment by kroitor** [comment]
@anandanand84 for all 400 codes? Or for GDAX only?

**Comment by anandanand84** [comment]
@kroitor I mean it depends right, if 400 comes from exchange during openOrders request then you cannot say it as InvalidOrder, it is invalidrequest for open orders.

**Comment by anandanand84** [comment]
I would recommend https://github.com/ccxt/ccxt/commit/b124f5799f81a34aa949190501b2ff5808da186e#diff-9453f5a8dee427abd6a1b4a0aed6a819R458 fix. Because there is a whole bunch of errors here is another one for instance "size must be greater than zero (0.00000000)", May be I am wrong when you ask what 400 corresponds to you in your scenario it should be ExchangeError and let the user handle the exchange error and not InvalidOrder.

**Comment by kroitor** [comment]
@anandanand84 the GDAX should now return InvalidOrder for that error starting from 1.9.293. 

See: https://github.com/ccxt/ccxt/commit/bcaebcdfc7fc1433787ffeaba80a28384629e7af
We have a special method for error handling since recently.

As for the other exchanges and cases – we're still unifying it (in progress). Let us know if you have any other questions or difficulties with it. Thx again for your feedback. Cheers!

**Comment by kroitor** [comment]
@anandanand84 sorry, there's a small problem on Travis uploading to PyPI, it will be there shortly.
