### ISSUE TITLE
fetchWithdrawals from kraken throws permission denied error

### ISSUE THREAD

**Issue by milesalex** [ccxt/ccxt#4273]
for every set of keys I try kraken throws this error for `fetchWithdrawals`

```
{ Error: kraken {"error":["EGeneral:Permission denied"]}
    at kraken.handleErrors (/Users/alexmiles/dev/tokentax/integrations/node_modules/ccxt/js/kraken.js:1184:31)
    at response.text.then (/Users/alexmiles/dev/tokentax/integrations/node_modules/ccxt/js/base/Exchange.js:650:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: ExchangeError] }
```

Any idea?

**Comment by kroitor** [comment]
@milesalex have you checked the permissions on that keypair?

**Comment by kroitor** [comment]
<img width="928" alt="screen shot 2018-12-04 at 05 50 00" src="https://user-images.githubusercontent.com/1294454/49415680-7a0bb280-f788-11e8-87c0-c3b904ba7353.png">

**Comment by npomfret** [comment]
@milesalex did you figure this out?  I get the same problem

**Comment by milesalex** [comment]
No, kraken sucks

**Comment by npomfret** [comment]
Indeed.

**Comment by kroitor** [comment]
@npomfret have you checked for permissions and withdrawal limits?

**Comment by npomfret** [comment]
Yes, I even created a new API and give it all the permissions.  It won't be a limit problem as I've not done any for a while - plus I'm just trying to query my recent withdrawals... it shouldn't error.

**Comment by kroitor** [comment]
https://github.com/leishman/kraken_ruby/pull/20/files#diff-04c6e90faac2675aa89e2176d2eec7d8R218

> due to a bug in Kraken's API, this endpoint requires an API token that has "Withdraw funds" Key Permission instead of "Query funds", otherwise an "EGeneral:Permission denied" Error will be raised.

Do you have 2FA enabled on the account and can you try with it temporarily switched off (for the sake of testing) ? (then switch it back on)

**Comment by npomfret** [comment]
I do have 2fa on.  I'll try and test this another time.  For now I'll just have to use the ledger entries.

**Comment by kroitor** [comment]
Yeah, because they have separate checkboxes for login 2fa and withdrawal 2fa, you want to test with the latter one temporarily disabled (even if you are not withdrawing, but just fetching a list of withdrawals) – https://twitter.com/krakensupport/status/979143097849298944, let us know about your results.

**Comment by npomfret** [comment]
FYI - I created a key with "Withdraw Funds" enabled and the `fetchWithdrawals` call started working.

**Comment by npomfret** [comment]
Do we know how long items are kept in the deposit and withdrawal endpoints?  The docs just say 

> Get status of *recent* withdrawals

**Comment by ethanbrown3** [comment]
It looks like this is still an issue. I’m needing to be able to fetch withdrawal history without authorization to withdraw funds. Is my best bet to just use kraken’s ledger endpoint?

**Comment by kroitor** [comment]
>  I’m needing to be able to fetch withdrawal history without authorization to withdraw funds. Is my best bet to just use kraken’s ledger endpoint?

I guess so, we don't really control this, so you're limited to whatever combination of Kraken switches you have on the website:

<img width="898" alt="Screen Shot 2020-01-19 at 23 31 04" src="https://user-images.githubusercontent.com/1294454/72687934-cabca700-3b13-11ea-9e96-d0c530c44492.png">

So, yes, if there's no withdraw permission, you're most likely limited to using just the ledger.

**Comment by ethanbrown3** [comment]
Thanks! @kroitor
