### ISSUE TITLE
Bitmex fetch_balance() returns Signature not valid.

### ISSUE THREAD

**Issue by philipperemy** [ccxt/ccxt#4279]
# Bitmex fetch_balance() returns Signature not valid.

## CCXT version
```
ccxt                      1.17.582 (latest as of Wed Dec 5)
```

## Snippet
```
credentials = {...}
import ccxt
bitmex = ccxt.bitmex(credentials)
bitmex.fetch_balance()
```

## Output (error)
```
{ExchangeError}bitmex {"error":{"message":"Signature not valid.","name":"HTTPError"}}
```

## References 
https://www.bitmex.com/app/apiKeysUsage > Troubleshooting section)

If you are receiving "Signature Not Valid" messages, check the following:
- Check that your signatures match the sample signatures above.
- If there is a request body, make sure your Content-Length and Content-Type are valid.
- Ensure your request body is being properly sent. Try a few sample requests against httpbin.
- Ensure you are signing the exact string that is being sent to the server. Certain JSON serializers have unstable key ordering, so serialize to a string first, sign that string, and then send the same string in the request body.

**Comment by kroitor** [comment]
@philipperemy Hi! Have you tried going through the troubleshooting section step-by-step? 

https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

```
import ccxt
credentials = {
    'apiKey': '8P6n3dtJ6QOytmmja62ryO9Y',
    'secret': 'ZLVY7RQ5gEFFHSxD-wQKfKs5-bv0UOUJzYCrkA87mM63wg0Z',
    'enableRateLimit': True,
}
exchange = ccxt.bitmex(credentials)
print(exchange.fetch_balance())
print(ccxt.__version__) # 1.17.582
```

↑ This works on my side

- Is your apiKey correct? Should be 24 characters long and your secret should be 48 characters long... - Have you used that keypair with any other software before?
- ...

Let me know if that does not help. Feel free to reopen it or just ask further questions, if any...

**Comment by philipperemy** [comment]
@kroitor thanks will try that. Keep up the good work :)

**Comment by philipperemy** [comment]
@kroitor just for information it was the API key that were problematic. They were not 24 char and 48 char long. My friend gave them to me so I have no idea of where he got them. Also bitmex did not complain that they were invalid. FYI!

**Comment by kroitor** [comment]
@philipperemy ok, thx for the feedback! We will see if we can add some more handling for this type of errors to be more user-friendly than bitmex ))

**Comment by philipperemy** [comment]
No problem. It's a low priority ))
