### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by aking7** [ccxt/ccxt#428]
I'd like to suggest annotating your release tags with a short description of the changes for that version. This is useful when running `git tag -n`. Right now they all show `[ci skip]`, which makes it difficult to navigate to a previous version if needed.

**Comment by kroitor** [comment]
@aking7 we actually have releasing tagging by version number. Or did you mean something different? It's actually very hard to make up a short description different from the commit message, because we sometimes do hundreds of releases daily. Most of the time you can checkout a specific version by its version tag. Does this answer your question?

**Comment by kroitor** [comment]
<img width="320" alt="screen shot 2017-10-31 at 22 16 14" src="https://user-images.githubusercontent.com/1294454/32244301-2cf9dd70-be89-11e7-988f-13d10f961f59.png">

**Comment by aking7** [comment]
Yes, the releases by version number are good :) It's just good practice to add a description of the changes as well using `git tag -a v1.0.0 -m "Description of version"`. By default, this description is the commit message (this is the case now). Unfortunately Travis-ci makes it's own commit for each version, where the commit message is simply `[ci skip]`, which tells us nothing of what was changed. If I want to have an idea of what was changed, I have to go to that version and then look at the previous commit.

The preferred workflow for finding a previous version using git tags is: run `git tag --sort=v:refname -n` in the command line, giving a list of all the available versions, along with a description. Then we can easily find what we are looking for.

**Comment by kroitor** [comment]
@aking7 we will add the message as well, thx!

**Comment by kroitor** [comment]
It has been finally fixed, thx again for your feedback!
