### ISSUE TITLE
ccxt have any 【Withdraw deposit 】api?

### ISSUE THREAD

**Issue by jackingyang** [ccxt/ccxt#4280]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:mac
- Programming Language version:python
- CCXT version:1.17.565
- Exchange:zb
- Method:

**Comment by kroitor** [comment]
@jackingyang 

> ccxt have any 【Withdraw deposit 】api? #4280

Yes! You can do that as described here: https://github.com/ccxt/ccxt/wiki/Manual#funding-your-account. Though, it's still a work in progress and those methods may be missing depending on the exchange, but we already have that part of API implemented for some of exchanges.

I really recommend to read the entire manual from top to bottom if you want to work with this lib effectively, that will save you a ton of time in future ;)

Let me know if that does not answer the question.

**Comment by jackingyang** [comment]
thanks a lot....i will read the entire manual
