### ISSUE TITLE
why zb have no withdraw method?

### ISSUE THREAD

**Issue by jackingyang** [ccxt/ccxt#4281]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:mac
- Programming Language version:phthon3.7
- CCXT version:1.17.565
- Exchange:zb
- Method:withdraw

**Comment by kroitor** [comment]
This question has been answered here:

- https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#pending-tasks

**Comment by jackingyang** [comment]
r=zb.withdraw('BTS', 1, 'dog2', tag='567174')


Traceback (most recent call last):
  File "/Users/jacking 1/Desktop/test.py", line 22, in <module>
    r=zb.withdraw('BTS', 1, 'bts-dog2', tag='894174')
AttributeError: 'zb' object has no attribute 'withdraw'
