### ISSUE TITLE
CCXT v1.18, Bitfinex USDT is now switched back to USD

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#4285]
Hi!

Due to multiple requests from users of Bitfinex, their USD ←→ USDT symbolic name has been unified previously. This was USD in CCXT 1.13, and since CCXT 1.14 it became USDT for Bitfinex. In other words, their USD currency code was mapped to USDT everywhere. 

This did work up until the point they added a new USDT/USD pair, so Bitfinex now has both of the currencies therefore keeping the USD → USDT substitution in code is not desirable anymore. We do understand, that migrating to new codes isn't easy, but, ultimately, this is something all users will have to do to support for both of the currencies involved.

Related links: 

- https://github.com/ccxt/ccxt/issues/2851
- https://support.bitfinex.com/hc/en-us/articles/360010505034-Fiat-on-Bitfinex

Because Bitfinex is one of major exchanges and this change might affect many users, please, note that **starting from CCXT 1.18 all Bitfinex pairs are switched back to USD**. BTC/USDT is now back to BTC/USD, ETH/USDT is now ETH/USD and so on... The same is true for EURT pairs, they're all back to EUR now.

This is a backward-incompatible change, please make sure to update your code accordingly.

If you want to keep the old substitution with the new version of the library, please do the following:

```JavaScript
const bitfinex = new ccxt.bitfinex ({
    'commonCurrencies': {
        'USD': 'USDT',  // will not work for the USDT/USD pair
    },
})
```

Thx for using this library!

**Comment by npomfret** [comment]
Will this change effect my trade history?  Will USDT trades and USD trades carried out in the past have the correct market?

**Comment by kroitor** [comment]
> Will this change effect my trade history?

Yes – all occurrences of symbol are affected.

> Will USDT trades and USD trades carried out in the past have the correct market?

Yes, and the correct market will be USD in this case.

**Comment by Gennttii** [comment]
Hi, 

In fact USDt is UST in bitfinex API and not USD as I know, I tried to make a trade with pair UST/USD but it shows me this error : 
`{"message":"This pair cannot be traded on margin."}`

Can you add this pair for trading with all types of orders, market limit, trailing stop etc..?

**Comment by kroitor** [comment]
> it shows me this error :
> {"message":"This pair cannot be traded on margin."}
> Can you add this pair for trading with all types of orders, market limit, trailing stop etc..?

This message `{"message":"This pair cannot be traded on margin."}` is not coming from CCXT – it is from Bitfinex. 

> In fact USDt is UST in bitfinex API and not USD as I know

As for the UST → USDT – you're right, we will add this mapping shortly.
