### ISSUE TITLE
CAUTION! Binance changed output of /exchangeInfo !

### ISSUE THREAD

**Issue by MarcelBeining** [ccxt/ccxt#4286]
- Exchange: Binance
- Method: e.g. markets[limits]

In the last days binance has changed without warning or increasing API version the output of /exchangeInfo. This now e.g. leads to the problem that maxPrice of a Symbol on binance is returned as 0.0 by ccxt!!! I attach an image and the mail from them:

![unknown](https://user-images.githubusercontent.com/1278660/49567968-b6c5de00-f92f-11e8-92b1-104904017b05.png)

Hello,

Thank you for your inquiry.

About your question, We have made changes to the PRICE_FILTER in the trading rules. We have used PERCENT_PRICE instead of PRICE_FILTER. You can adjust the price of your order by referring to the parameters of multiplierUp and multiplierDown in the PERCENT_PRICE section of the document.

https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

So you don't need to worry about that. We recommend that you check our API documentation frequently, and we will update it in GitHub as soon as we have any changes.

Thank you for your understanding.

**Comment by kroitor** [comment]
@MarcelBeining because it now depends on the history of trades, we can't really set any meaningful value for price min/max except `undefined`/`None`/`null`. Does that sound ok?

**Comment by MarcelBeining** [comment]
well that's the only thing that makes sense by now...hopefully binance will change it again in some future version... thanks
