### ISSUE TITLE
Python build not working

### ISSUE THREAD

**Issue by aking7** [ccxt/ccxt#430]
The python build is not working. Last stable version is 1.9.289

**Comment by kroitor** [comment]
This should be resolved now (working on it).

**Comment by kroitor** [comment]
Looks like there's still an issue with async, fixing it as well.

**Comment by aking7** [comment]
Thank you!! Love your fast response time. I was trying to investigate it myself but to no avail. I might suggest making a development branch for merging major changes before pushing to the master branch. Perhaps just have meaningful 1.x versions on master ;)
