### ISSUE TITLE
Can't use privatePostOrderCloseposition on Bitmex

### ISSUE THREAD

**Issue by mererere** [ccxt/ccxt#4302]
Hello,

I try to Close a Position with ccxt wenn I run privatePostOrderCloseposition I receive the following error:

close = client.privatePostOrderCloseposition('XBTUSD')
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 364, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 361, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 452, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/bitmex.py", line 575, in handle_errors
    raise BadRequest(feedback)
ccxt.base.errors.BadRequest: bitmex {"error":{"message":"Unexpected token \" in JSON at position 0","name":"SyntaxError"}}

Can you help?

Kind regards
René

- OS: Raspian
- Programming Language version: Python 3.5
- CCXT version: latest
- Exchange: Bitmex
- Method: privatePostOrderCloseposition

**Comment by kroitor** [comment]
@mererere can you please provide your verbose request/response for it (without your keys)?

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

**Comment by mererere** [comment]
Something like this?:

DEBUG:ccxt.base.exchange:POST https://www.bitmex.com/api/v1/order/closePosition?XBTUSD, Request: {'api-nonce': '1544363195374', 'Accept-Encoding': 'gzip, deflate', 'Content-Type': 'application/json', 'api-signature': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'api-key': 'xxxxxxxxxxxxxxxxxxxxxxxxx'} "XBTUSD"
DEBUG:urllib3.connectionpool:https://www.bitmex.com:443 "POST /api/v1/order/closePosition?XBTUSD HTTP/1.1" 400 86
DEBUG:ccxt.base.exchange:POST https://www.bitmex.com/api/v1/order/closePosition?XBTUSD, Response: 400 {'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Content-Length': '86', 'Set-Cookie': 'AWSALB=p9uV5rTbRBdLL8PCc71vgKOxjC+yv/zbYWCikfdvuvkGd1+07flzk3d9Sf/7f7Gq/qtOhiBiT1zD5yTaiZ5tE7RoBL7g3oL10jJ7rhEYnFN9eQUfKRys3Dn1a0vn; Expires=Sun, 16 Dec 2018 13:46:35 GMT; Path=/', 'Content-Type': 'application/json; charset=utf-8', 'Date': 'Sun, 09 Dec 2018 13:46:35 GMT', 'Connection': 'keep-alive', 'ETag': 'W/"56-ClBa+ONjQwDiPDbsrZZF0fLcWX4"'} {"error":{"message":"Unexpected token \" in JSON at position 0","name":"SyntaxError"}}
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 440, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.bitmex.com/api/v1/order/closePosition?XBTUSD

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "json2sql2.py", line 109, in <module>
    close = client.privatePostOrderCloseposition('XBTUSD')
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 364, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 361, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 452, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/bitmex.py", line 575, in handle_errors
    raise BadRequest(feedback)
ccxt.base.errors.BadRequest: bitmex {"error":{"message":"Unexpected token \" in JSON at position 0","name":"SyntaxError"}}

**Comment by kroitor** [comment]
@mererere ok, for some reason you're passing a string `XBTUSD` to `client.privatePostOrderCloseposition('XBTUSD')` (sorry, I missed it when I read your initial post for the first time, and now I noticed it). This is a wrong way to call implicit methods. Here's the correct way:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods
- https://www.bitmex.com/api/explorer/#!/Order/Order_closePosition

So the correct syntax for that implicit method is:

```Python
close = client.privatePostOrderCloseposition({'symbol': 'XBTUSD'})
```

Let us know if that doesn't answer your question.

**Comment by mererere** [comment]
Thanks! It worked!

**Comment by cryptoflipper** [comment]
Just getting this over the finish line. Closing open positions and closing open orders are handled differently it seems.
You need to find the symbol from each open position (using private_get_position()) and then close that symbol explicitly as kroitor says.  Closing open orders uses a different mechanism. There you use exchange.fetch_open_orders(symbol) and then pick up the order order['id'] and use exchange.cancel_order(order['id'], symbol) to close each order.

def close_open_positions(exchange, symbol):
    positions = exchange.private_get_position()
    for position in positions:
        exchange.private_post_order_closeposition(
                {'symbol': position['symbol']})

def close_open_orders(exchange, symbol):
    orders = exchange.fetch_open_orders(symbol)
    for order in orders:
        exchange.cancel_order(order['id'], symbol)

*exchange in the above example is an instance of ccxt.bitmet

**Comment by kroitor** [comment]
@cryptoflipper thx for the followup on this and for the example!
