### ISSUE TITLE
Bitmex API signature deprecated nonce

### ISSUE THREAD

**Issue by StanleyDing** [ccxt/ccxt#4307]
- CCXT version: 1.18.9
- Exchange: Bitmex

I encountered this error from bitmex:
```json
{
  "error": {
    "message":"Nonce is not increasing. This nonce: 1544409251038, last nonce: 1544409251075",
    "name":"HTTPError"
  }
}
```

As stated in [API Keys Usage](https://www.bitmex.com/app/apiKeysUsage#Authenticating-with-an-API-Key), using `nonce` in no longer recommended; instead, `api-expires` should be used in place of `nonce`. 

I could submit a PR that fix this problem, but what value should we use for `api-expires`? 5 seconds? 30 seconds? 1 minute? There seems no definite answer for this problem.

**Comment by kroitor** [comment]
> I could submit a PR that fix this problem, but what value should we use for api-expires? 5 seconds? 30 seconds? 1 minute? There seems no definite answer for this problem.

Well, whenever you're designing a library and encounter something that depends on user-specific settings and you can't decide a good default value universally for all users, then you should not set the default at all – it is better to add an option to exchange-specific `.options` instead:

```JavaScript
// once upon a time in a bitmex implementation far, far away...

// ... this is just pseudocode for example...

describe () {
    // ...
    return {
        // ...
        'options': {
            'apiExpires': undefined, // set to an integer number of seconds to enable it
        },
    },
}

sign (...) {
    // ...
    let apiExpires = this.safeInteger (this.options, 'apiExpires');
    if (apiExpires !== undefined) {
        headers['api-expires'] = this.sum (this.seconds(), apiExpires);
    } else {
        headers['api-nonce'] = this.nonce ();
    }
    // ...
}
```

How does that sound to you?

**Comment by StanleyDing** [comment]
Sounds alright. But I think without explicit documentation, users can easily overlook this setting, unless they look into the source code.

I'll work on this enhancement as soon as I got time.

**Comment by kroitor** [comment]
Related: https://github.com/ccxt/ccxt/issues/4307
