### ISSUE TITLE
How can i trade XRP future in okex by ccxt

### ISSUE THREAD

**Issue by clovergame** [ccxt/ccxt#4308]
- OS:Windows 7
- Programming Language version: python 3.6
- CCXT version: 1.18.15
- Exchange:okex
- Method:exchange.create_limit_buy_order

hello, I can't trade XRP/USD future in okex, and  i use this code to print okex future support
https://github.com/ccxt/ccxt/blob/master/examples/py/fetch-okex-futures.py

then i find there is No market symbol named 'XRP/USD', but in https://www.okex.com/future/trade#15_1 , i can trade XRP future.  

how can i trade XRP future in okex by ccxt , thank you very much!

**Comment by kroitor** [comment]
@clovergame hi! I've added a workaround for this issue, that is, [until we implement their v3](https://github.com/ccxt/ccxt/issues/4063), so if you upgrade to 1.18.16 it should work, let us know if not. Thx for reporting!

**Comment by clovergame** [comment]
> @clovergame hi! I've added a workaround for this issue, that is, [until we implement their v3](https://github.com/ccxt/ccxt/issues/4063), so if you upgrade to 1.18.16 it should work, let us know if not. Thx for reporting!

Thank you for answer and fix rapidly ,it worked when i upgraded to 1.18.16,really appreciate!
