### ISSUE TITLE
bitmex fetch_ohlcv limit返回数量不对

### ISSUE THREAD

**Issue by 317459062** [ccxt/ccxt#4309]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:windows10
- Programming Language version:
- CCXT version:lastest
- Exchange: bitmex
- Method:fetch_ohlcv

**Comment by kroitor** [comment]
@317459062 can you follow these guides? https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

**Comment by 317459062** [comment]
ccxt.bitmex().fetch_ohlcv(symbol='BTC/USD',limit=50,timeframe='1m')我需要50条数据，但是返回值只有48条数据

**Comment by 317459062** [comment]
ccxt version：1.17.372
fetch_ohlcv(symbol='BTC/USD',limit=50,timeframe='1m')

**Comment by kroitor** [comment]
```
mbp:python igorkroitor$ python3
Python 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> print(ccxt.__version__)
1.18.15
>>> exchange = ccxt.bitmex({'enableRateLimit': True})
>>> candles = exchange.fetch_ohlcv('BTC/USD', '1m', None, 50)
>>> print(len(candles))
50
>>>
```

↑ what's your output?

**Comment by 317459062** [comment]
the same with you but use this code the output is
1544428320000
49

`def get_bitmex_data(exchange,time_interval,symbol="BTC/USD",limit=50):
now = exchange.milliseconds()
    since = now - limit * int(time_interval.split('m')[0]) * 60 * 1000  # 当前时间之前多少毫秒数的K线,时间为UTC时间,与中国时间差8h
    print(since)
    data=exchange.fetch_ohlcv(symbol=symbol, timeframe=time_interval, limit=limit, since=since)
    print(len(data))
    df = pd.DataFrame(data)
    df.rename(columns={0: 'MTS', 1: 'open', 2: 'high', 3: 'low', 4: 'close', 5: 'volume'}, inplace=True)
    df['candle_begin_time'] = pd.to_datetime(df['MTS'], unit='ms')
    df['candle_begin_time_GMT8'] = df['candle_begin_time'] + timedelta(hours=8)
    df = df[['candle_begin_time_GMT8', 'open', 'high', 'low', 'close', 'volume']]`

**Comment by 317459062** [comment]
`
def get_bitmex_data(exchange,time_interval,symbol="BTC/USD",limit=50):
    '''

    :param exchange: 实例化的交易所
    :param time_interval: 分钟数  m结尾
    :param symbol: 品种
    :param limit: 数据条数
    :return:
    '''
    now = exchange.milliseconds()
    since = now - limit * int(time_interval.split('m')[0]) * 60 * 1000  # 当前时间之前多少毫秒数的K线,时间为UTC时间,与中国时间差8h
    print(since)
    data=exchange.fetch_ohlcv(symbol=symbol, timeframe=time_interval, limit=limit, since=since)
    print(len(data))
    df = pd.DataFrame(data)
    df.rename(columns={0: 'MTS', 1: 'open', 2: 'high', 3: 'low', 4: 'close', 5: 'volume'}, inplace=True)
    df['candle_begin_time'] = pd.to_datetime(df['MTS'], unit='ms')
    df['candle_begin_time_GMT8'] = df['candle_begin_time'] + timedelta(hours=8)
    df = df[['candle_begin_time_GMT8', 'open', 'high', 'low', 'close', 'volume']]
    # print(df)
    return df


`

**Comment by kroitor** [comment]
Ok, I've been able to reproduce it, so I've uploaded a fix for it and tested it on my side, and it works, let me know if you still have issues with after upgrading to CCXT version 1.18.17. Thx for reporting!

**Comment by 317459062** [comment]
我升级了之后已经能拿到50条数据了 数据完整

**Comment by kroitor** [comment]
@317459062 thx for reporting back!
