### ISSUE TITLE
Let CCXT Read from a credentials.js file

### ISSUE THREAD

**Issue by cklester** [ccxt/ccxt#431]
I would like to enable CCXT to read from a credentials.js file when needing exchange credentials instead of having to put the credentials inside the source.

For example, instead of (this is from the instantiate-all-at-once.js example):

```
"use strict";

const ccxt = require ('../../ccxt');

async function test () {

    let exchanges = { 
        "bittrex": {
            "apiKey": "60f38a5818934fc08308778f94d3d8c4", 
            "secret": "9d294ddb5b944403b58e5298653720c1",
        },
        "bitfinex": { 
            "apiKey": "02YsRDRAFwqt9JXfFKPIEw82mgmNbZtfpwvt8q5WK5a", 
            "secret": "IummLrCfcZ9d9NPEtMg6chCpO8hugCvsDIscNm1F3pE"
        },
    }

    let ids = ccxt.exchanges.filter (id => id in exchanges)
```

we could do something like:

```
"use strict";

const ccxt = require ('../../ccxt');
const exchanges = require('credentials.js').credentials;

async function test () {

    let ids = ccxt.exchanges.filter (id => id in exchanges)

```

**Comment by kroitor** [comment]
Hi, @cklester !

See how we do exactly that here:
https://github.com/ccxt/ccxt/blob/master/test/test.js#L46

Let us know if it answers your question or not. Thx!

**Comment by kroitor** [comment]
```
const ccxt = require ('ccxt')
const keysFile = './keys.json'
const settings = JSON.parse (fs.readFileSync (keysFile, 'utf8'))[exchangeId]
const exchanges = ccxt.indexBy (ccxt.exchanges.map (id => ccxt[id] (settings[id])), 'id')
```

**Comment by cklester** [comment]
Thanks, @kroitor !

I don't see the `keys.json` file.

**Comment by kroitor** [comment]
It's in the [root of the repo](https://github.com/ccxt/ccxt): [https://github.com/ccxt/ccxt/blob/master/keys.json](https://github.com/ccxt/ccxt/blob/master/keys.json) ← those are temporary keys for testing only...

The format of the file is very simple:
{
    "kraken": { "apiKey": "...", "secret": "...", "someOtherOptionOfYourChoice": "..." },
    "gdax": { "apiKey": "...", "secret": "..." },
    ...
    "livecoin": { "apiKey": "...", "secret": "...", "proxy": "..." }
}

**Comment by xpl** [comment]
@cklester Actually, you can use `require` to load JSON:

```javascript
const keys = require ('./keys.json')
```

**Comment by cklester** [comment]
That seems to be the way to go... right? 🥇
