### ISSUE TITLE
How to get the quote volume with fetchOHLCV in OKEX  

### ISSUE THREAD

**Issue by clovergame** [ccxt/ccxt#4319]
- OS: WIN 7
- Programming Language version: python
- CCXT version: 1.18.16
- Exchange: OKEX
- Method: exchange.fetch_ohlcv

Hello, I used fetch_ohlcv method to get the volume data，
when request url which okex api offer:
https://www.okex.com/api/v1/future_kline.do?symbol=eos_usd&type=15min&contract_type=this_week
it return every kline like this [1544581800000,1.808,1.821,1.798,1.806,306520,1692669.45421517] 
notice that ,306520 and 1692669.45421517 are both volume in different types.
I want get 306520 , but fetch_ohlcv method show me 1692669.45421517 instead. 
Could you help me to get the other volume in OKEX，Thanks!

**Comment by kroitor** [comment]
Currently, we return just the base volume everywhere from fetchOHLCV. We will add support for both the base and the quote volume to fetchOHLCV soon, in the meantime, you can get the other (quote) volume like so:

```Python
import ccxt
from pprint import pprint
exchange = ccxt.okex({

    'enableRateLimit': True,  # required by the Manual

    # an override to get volume in quote currency for OKEX
    'parse_ohlcv': lambda ohlcv, market, timeframe, since, limit: [
        ohlcv[0],  # timestamp
        float(ohlcv[1]),  # Open
        float(ohlcv[2]),  # High
        float(ohlcv[3]),  # Low
        float(ohlcv[4]),  # Close
        float(ohlcv[5]),  # for futures markets: 5 = quote volume, 6 = base volume 
    ]
})

candles = exchange.fetch_ohlcv('EOS/USD', '1m')
```

Let us know if that doesn't answer your question.

**Comment by clovergame** [comment]
It worked, Thank you very much
