### ISSUE TITLE
Add Example "instantiate-all-at-once.js" Using JSON Credentials File

### ISSUE THREAD

**Issue by cklester** [ccxt/ccxt#432]
Can you update or provide separately an example script using the JSON import of credentials?

Ultimately, it would be great to update all examples to utilize this method, so all examples could be easily run with our own set of credentials.

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/blob/master/examples/js/instantiate-all-from-json.js

**Comment by cklester** [comment]
@kroitor Thank you!
