### ISSUE TITLE
Websocket + Okex

### ISSUE THREAD

**Issue by GenesisGupta** [ccxt/ccxt#4321]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10
- Programming Language version: Python 3.6
- CCXT version: 1.17.482
- Exchange: Okex 
- Method:

I would like to know if websocket is implemented for Okex , if Yes , is there a sample to run it and place orders ?

**Comment by kroitor** [comment]
@GenesisGupta 

> I would like to know if websocket is implemented for Okex

Not yet, but the development is going on here: #56
