### ISSUE TITLE
cryptotia GetDepositAddress  error on some coins

### ISSUE THREAD

**Issue by petitcoin22450** [ccxt/ccxt#4323]
Hello, 
When i query  https://www.cryptopia.co.nz/api/GetDepositAddress depending on the Currency, 
answer is not the same, could be a configuration issue, but everything look normal on my account, if you have any clue, it would be great thanks

Body...: {"Currency":"DIVI"} 
Result.: {"Success":true,"Error":null,"Data":{"Currency":"DIVI","Address":"XXXXBbapqQFroZYwEGpUur6nhZhaCxL","BaseAddress":""}} 

working query 
Body...: {"Currency":"ONT"} 
Result.: {"Success":true,"Error":null,"Data":{"Currency":"ONT","Address":"XXXXJ7mvzpysjpMUsxuch3DCFghiwTdqV","BaseAddress":"XXXXC4dQwguYXtrK5NrLzeKshoZgjVvPh"}} 

BaseAddress is empty for some coins 

OS: debian 9
Programming Language version: PHP
CCXT version: 1.17
Exchange: cryptotia
 Method: GetDepositAddress 

Thx for help.

**Comment by julienphilippe** [comment]
thx

**Comment by petitcoin22450** [comment]
thx !

**Comment by kroitor** [comment]
@petitcoin22450 thx to you for reporting!
