### ISSUE TITLE
Missing Cryptopia market pair CAN/BTC

### ISSUE THREAD

**Issue by crypto-ali** [ccxt/ccxt#4331]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Win 10 64
- Programming Language version: Node.js v10.14.2
- CCXT version: 1.18.33
- Exchange: Cryptopia
- Method: Post

Trying to post a limit buy order for Canya coin on Cryptopia. Market: https://www.cryptopia.co.nz/Exchange/?market=CAN_BTC

Getting the following error.

```limit buy NaN CAN/BTC at NaN each
(node:9756) UnhandledPromiseRejectionWarning: Error: cryptopia does not have market symbol CAN/BTC
    at cryptopia.market (C:\Users\****\####\node_modules\ccxt\js\base\Exchange.js:932:15)
    at cryptopia.createOrder (C:\Users\****\####\node_modules\ccxt\js\cryptopia.js:598:27)```

**Comment by kroitor** [comment]
Let us know if this does not answer your question:

- https://github.com/ccxt/ccxt/issues/3165
- https://github.com/ccxt/ccxt/wiki/Manual#notes-on-naming-consistency
- https://github.com/ccxt-dev/ccxt/wiki/Manual#symbols-and-market-ids
- https://github.com/ccxt/ccxt/blob/master/examples/js/symbols.js

```
mbp:ccxt igorkroitor$ node examples/js/cli cryptopia symbols
[ "$$$/BTC",
  "$$$/DOGE",
  "$$$/LTC",
  "$PAC/BTC",
  "$PAC/DOGE",
  "$PAC/LTC",
  "$PAC/USDT",
  "1337/DOGE",
  "1337/LTC",
  "300/BTC",
  "300/DOGE",
...
  "CTL/BTC",
  "CTL/DOGE",
  "CTL/LTC",
  "CXT/BTC",
  "CXT/DOGE",
  "CXT/LTC",
  "CanYaCoin/BTC", // ←----------------------------- 
  "CanYaCoin/LTC", // ←----------------------------- 
  "Comet/BTC",
  "Comet/DOGE",
  "Comet/LTC",
  "Cubits/BTC",
  "Cubits/DOGE",
  "Cubits/LTC",
  "D/BTC",
  "D/DOGE",
  "D/LTC",
  "DAPS/BTC",
  "DAPS/DOGE",
...
  "ZTX/DOGE",
  "ZTX/LTC"                       ]
1571 objects
mbp:ccxt igorkroitor$
```
