### ISSUE TITLE
New exchange: Onederx

### ISSUE THREAD

**Issue by mrvlasyuk** [ccxt/ccxt#4332]
Onederx is crypto derivative trading platform launched in December 2018. The main trading instrument is BTCUSD_P which is Perpetual contract with a leverage up to 20x.

website: https://onederx.com
API: https://docs.onederx.com/

**Comment by ZlD238749725** [comment]
ฉนใม่รู้ว่าต้องทำใงแต่ฉันอยากบอกว่าฉันอยากถอนเงินที่ฉันถอนได้

**Comment by mrvlasyuk** [comment]
Hi again! Is there any way to motivate contributors to add support for Onederx?

**Comment by mrvlasyuk** [comment]
Hi @kroitor! Is there any way to motivate contributors to add support for Onederx? We have a very well written and documented API. Cпасибо :)

**Comment by kroitor** [comment]
Hey @mrvlasyuk! ) If you're the Onederx exchange and you want to speed up the work on this integration, please, send us a message: info@ccxt.trade. Пожалуйста ;)

**Comment by ttodua** [comment]
Exchange no longer available. closing the issue.
