### ISSUE TITLE
huobipor bid and ask datas are None using fetch_tickers while you can get them when using fetch_ticker

### ISSUE THREAD

**Issue by zjingpopo** [ccxt/ccxt#4334]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:ubuntu 18.04
- Programming Language version: python3.6.7
- CCXT version:1.18.37
- Exchange:huobipro
- Method:fetch_tickers()
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> ccxt.__version__
'1.18.37'
>>> hbp = ccxt.huobipro()
>>> tks = hbp.fetch_tickers()
>>> tks['ETH/BTC']
{'symbol': 'ETH/BTC', 'timestamp': 1544861697657, 'datetime': '2018-12-15T08:14:57.657Z', 'high': 0.026318, 'low': 0.025854, 'bid': None, 'bidVolume': None, 'ask': None, 'askVolume': None, 'vwap': 0.026065172481112255, 'open': 0.026229, 'close': 0.026111, 'last': 0.026111, 'previousClose': None, 'change': -0.00011800000000000005, 'percentage': -0.44988371649700737, 'average': 0.02617, 'baseVolume': 285602.7274000003, 'quoteVolume': 7444.284350757093, 'info': {'open': 0.026229, 'close': 0.026111, 'low': 0.025854, 'high': 0.026318, 'amount': 285602.7274000003, 'count': 50707, 'vol': 7444.284350757093, 'symbol': 'ethbtc'}}
>>> tks['ETH/BTC']['bid']
>>> tk = hbp.fetch_ticker('ETH/BTC')
>>> tk
{'symbol': 'ETH/BTC', 'timestamp': None, 'datetime': None, 'high': 0.026318, 'low': 0.025854, 'bid': 0.026076, 'bidVolume': 5.7011, 'ask': 0.026089, 'askVolume': 0.0858, 'vwap': 0.02606544794006059, 'open': 0.026046, 'close': 0.026076, 'last': 0.026076, 'previousClose': None, 'change': 2.9999999999998778e-05, 'percentage': 0.11518083390923281, 'average': 0.026061, 'baseVolume': 285194.6513000004, 'quoteVolume': 7433.7263362438935, 'info': {'amount': 285194.6513000004, 'open': 0.026046, 'close': 0.026076, 'high': 0.026318, 'id': 32360729844, 'count': 50647, 'low': 0.025854, 'version': 32360729844, 'ask': [0.026089, 0.0858], 'vol': 7433.7263362438935, 'bid': [0.026076, 5.7011]}}
>>> tk['bid']
0.026076

The bid and ask datas are None in fetch_tickers while you can get them using fetch_ticker on single symbol pair. 
I'm not sure if it is because of the exchange itself or a ccxt bug, just point it out.

**Comment by kroitor** [comment]
You can see that yourself if you read the docs and checkout the examples, then apply a verbose flag:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties
- https://github.com/ccxt/ccxt/tree/master/examples/py/cli.py

```Python
mbp:ccxt igorkroitor$ python3 examples/py/cli.py huobipro fetch_tickers --verbose

Request: GET https://api.huobi.pro/market/tickers {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None

...
 'ZEC/BTC': {'ask': None,
             'askVolume': None,
             'average': 0.015314000000000001,
             'baseVolume': 117084.19661207612,
             'bid': None,
             'bidVolume': None,
             'change': -0.0001860000000000004,
             'close': 0.015221,
             'datetime': '2018-12-15T15:29:31.766Z',
             'high': 0.015606,
# -------- info contains the raw response as is ↓ no bid ask here
             'info': {'amount': 117084.19661207612,    
                      'close': 0.015221,
                      'count': 5822,
                      'high': 0.015606,
                      'low': 0.015073,
                      'open': 0.015407,
                      'symbol': 'zecbtc',
                      'vol': 1788.9969180888972},
# -------- info contains the raw response as is ↑ no bid ask here
             'last': 0.015221,
             'low': 0.015073,
             'open': 0.015407,
             'percentage': -1.20724346076459,
             'previousClose': None,
             'quoteVolume': 1788.9969180888972,
             'symbol': 'ZEC/BTC',
             'timestamp': 1544887771766,
             'vwap': 0.015279576320758383},
...
```

https://api.huobi.pro/market/tickers ← they don't return bids/asks here for multiple tickers...

... but they do return them here for one ticker: https://api.huobi.pro/market/detail/merged?symbol=zecbtc:

```Python
mbp:ccxt igorkroitor$ python3 examples/py/cli.py huobipro fetch_ticker ZEC/BTC --verbose

Request: GET https://api.huobi.pro/market/detail/merged?symbol=zecbtc {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.huobi.pro/market/detail/merged?symbol=zecbtc 200 {'Date': 'Sat, 15 Dec 2018 15:33:02 GMT', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d3127761ad5b25b64cf594fac9441d6a71544887981; expires=Sun, 15-Dec-19 15:33:01 GMT; path=/; domain=.api.huobi.pro; HttpOnly', 'X-Request-ID': '83fed821975bf861036127ca140d1291', 'Content-Encoding': 'gzip', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '4899f75a3e124f3e-DME'} {"status":"ok","ch":"market.zecbtc.detail.merged","ts":1544887982151,"tick":{"amount":117419.30691207612,"open":0.015312,"close":0.015211,"high":0.015606,"id":32397835116,"count":5815,"low":0.015073,"version":32397835116,"ask":[0.015232,0.14],"vol":1794.0847920514973,"bid":[0.015204,0.6]}}
{'ask': 0.015232,
 'askVolume': 0.14,
 'average': 0.0152615,
 'baseVolume': 117419.30691207612,
 'bid': 0.015204,
 'bidVolume': 0.6,
 'change': -0.00010099999999999866,
 'close': 0.015211,
 'datetime': None,
 'high': 0.015606,
 'info': {'amount': 117419.30691207612,
          'ask': [0.015232, 0.14],
          'bid': [0.015204, 0.6],
          'close': 0.015211,
          'count': 5815,
          'high': 0.015606,
          'id': 32397835116,
          'low': 0.015073,
          'open': 0.015312,
          'version': 32397835116,
          'vol': 1794.0847920514973},
 'last': 0.015211,
 'low': 0.015073,
 'open': 0.015312,
 'percentage': -0.6596133751306078,
 'previousClose': None,
 'quoteVolume': 1794.0847920514973,
 'symbol': 'ZEC/BTC',
 'timestamp': None,
 'vwap': 0.015279299795176893}
mbp:ccxt igorkroitor$
```

> I'm not sure if it is because of the exchange itself or a ccxt bug, just point it out.

From the above it's obvious, that it's because of the exchange itself. Hope it answers your question.
