### ISSUE TITLE
Is there any modifyOrder method?

### ISSUE THREAD

**Issue by Gennttii** [ccxt/ccxt#4337]
Hi, 

There are openOrder , cancelOrder, but I can't find a modifyOrder method..

Is there any modifyOrder in CCXT?

Regards

**Comment by kroitor** [comment]
> Is there any modifyOrder in CCXT?

Yes, it is called `editOrder` and we use the endpoint from the exchange, if the exchange in question provides such an endpoint for editing orders, and if not – it falls back to a default implementation in the base class that will do two calls – cancel the first order and create a new one. Let us know if that does not answer your question.
