### ISSUE TITLE
OKCoinUSD's fetchTrades function returns integer id

### ISSUE THREAD

**Issue by hrtshu** [ccxt/ccxt#434]
I found that fetchTrades function of OKCoinUSD returns integer id.
According to the documentation, this function must return string id.

Python: https://github.com/ccxt/ccxt/blob/cf675184f57e79449b00e23d020ad55f1990e952/python/ccxt/okcoinusd.py#L191
JavaScript: https://github.com/ccxt/ccxt/blob/cf675184f57e79449b00e23d020ad55f1990e952/js/okcoinusd.js#L200
PHP: https://github.com/ccxt/ccxt/blob/cf675184f57e79449b00e23d020ad55f1990e952/php/okcoinusd.php#L197

**Comment by kroitor** [comment]
This issue was fixed in 1.9.305. Thx!
