### ISSUE TITLE
No market symbol error for BCHSV with new version of CCXT. Old version works

### ISSUE THREAD

**Issue by laci06** [ccxt/ccxt#4342]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Win 10 / Ubuntu 18.04
- Programming Language version: Python 3.7
- CCXT version: 1.17.86 vs 1.18.39
- Exchange: Binance
- Method: fetch_trades / fetch_open_orders / send / cancel_order

It seems that in the newer (1.18.39) version of CCXT I cannot send for example BCHSV orders for Binance. The problem is not there for all instruments (ADA and XLM are fine), but BCHSV fetch_trades, fetch_open_orders etc returns the following error:
ccxt.base.errors.ExchangeError: binance No market symbol BCHSV/BTC
It might exist also for other symbols, have not checked all, but it is weird. The old version (1.17.86) handles BCHSV without any error.

**Comment by kroitor** [comment]
@laci06 in v1.18+, after the BCH fork, we have aligned the symbols with CMC, so it's now BCH and BSV, more about it here: https://github.com/ccxt/ccxt/issues/4311
