### ISSUE TITLE
Is there an api abstraction for FUTURE?

### ISSUE THREAD

**Issue by ngugcx** [ccxt/ccxt#4344]
The ccxt SPOT api abstraction is awesome!
There are more and more exchanges which support FUTURE.
Is there a plan to support FUTURE?

**Comment by kroitor** [comment]
> Is there a plan to support FUTURE?

Currently, we implement implicit methods around all http endpoints, including the ones for trading futures contracts. However, you're right, it's not unified yet, it's a work in progress. We have plans to  unify the following aspects:
- margin trading (including leveraged positions)
- futures trading
- perpetual contracts

Let us know if that does not answer your question.
