### ISSUE TITLE
Bitfinex trailing stop

### ISSUE THREAD

**Issue by Gennttii** [ccxt/ccxt#4347]
Hi,

I saw only this about trailing orders, but no explanations, bitfinex asks for distance of trailing, where to set the distance?

bitfinex.createLimitSellOrder ('BTC/USD', 1, 10, { 'type': 'trailing-stop' })

**Comment by max00x** [comment]
เชฟเข้ากระเป๋ายังไง

**Comment by kroitor** [comment]
@Gennttii i'd close this for now until we have a followup from you, please paste the debugging info as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue. Feel free to reopen it if needed or just ask further questions.
