### ISSUE TITLE
Add CCXT Future Position query

### ISSUE THREAD

**Issue by helldragonx** [ccxt/ccxt#4368]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
  lastest
- Exchange:
   OKEX Future
- Method:
   FuturePosition

  Hope add Fetch OKEX Future Fetching Function , I added but seems response failed(200)
  Could you help me to check or point out where's wrong?    

def UpdatePosition(self):

        post_link = self.url + 'future_position.do'

        post_str = 'symbol=' + self.market['id'] +'&contract_type=' + self.future \
                    + '&api_key=' + self.apiKey
        sign_str =  post_str + '&secret_key=' + self.secret
        sign = self.exchange.hash(self.exchange.encode(sign_str)).upper()
        post_str += '&sign='+sign
        post_str = post_str.encode()
        #headers = {'Content-Type': 'application/x-www-form-urlencoded'}
        headers = {'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.18.4',
         'Accept-Encoding': 'gzip, deflate'}

        self.exchange.session.request(
                'POST',
                post_link,
                data=post_str,
                headers=headers,
                timeout=int(self.exchange.timeout / 1000),
                proxies=self.proxies
        )
        response = requests.post( url=post_link, data=post_str, proxies=self.proxies, headers=headers)

        print (response)

**Comment by kroitor** [comment]
You can do that with CCXT by using implicit methods as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

**Comment by kroitor** [comment]
```Python
from pprint import pprint
import ccxt
exchange = ccxt.okex({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,  # as required by the Manual
})
exchange.load_markets()
market = exchange.markets['XRP/USD']
response = exchange.private_post_future_position({
    'symbol': market['id'],
    'contract_type': exchange.options['defaultContractType'],
})
pprint(response)
```
