### ISSUE TITLE
coss fetch_open_orders

### ISSUE THREAD

**Issue by blaaaaaaa** [ccxt/ccxt#4371]
fetch_open_order(symbol) on coss not working I think. I think we get order on response, then something goes wrong. toUppercase is js code?!

Request: POST https://trade.coss.io/c/api/v1/order/list/open {'Signature': 'xxx', 'Authorization': 'xxx', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} {"timestamp":1545514978712,"symbol":"LALA_ETH"}

Traceback (most recent call last):
  File "C:/Users/Administrator/IdeaProjects/ccxt_trading_bot/ccxt_coss_maker_bot.py", line 111, in <module>
    main()
  File "C:/Users/Administrator/IdeaProjects/ccxt_trading_bot/ccxt_coss_maker_bot.py", line 104, in main
    coss_maker_bot.mkr_ex.fetch_open_orders("LALA/ETH")
  File "C:\Users\Administrator\IdeaProjects\ccxt_trading_bot\venv\lib\site-packages\ccxt\coss.py", line 685, in fetch_open_orders
    return self.fetch_orders_by_type('Open', symbol, since, limit, params)
Response: POST https://trade.coss.io/c/api/v1/order/list/open 200 {'Server': 'Apache-Coyote/1.1', 'X-Frame-Options': 'SAMEORIGIN', 'X-Content-Type-Options': 'nosniff', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Date': 'Sat, 22 Dec 2018 21:42:58 GMT', 'Via': '1.1 google', 'Alt-Svc': 'clear'} {"total":1,"list":[{"hex_id":null,"order_id":"758870b8-eb35-4a53-beb6-884a9e60d14d","account_id":"15dc0ed3-05c4-4f20-947e-803dbd492c3f","order_symbol":"LALA_ETH","order_side":"BUY","status":"open","createTime":1545508902637,"type":"limit","timeMatching":0,"order_price":"0.00000220","order_size":"40355.8","executed":"0","stop_price":"0.00000000","avg":"0.00000220","total":"0.08878276 ETH"}]}
  File "C:\Users\Administrator\IdeaProjects\ccxt_trading_bot\venv\lib\site-packages\ccxt\coss.py", line 676, in fetch_orders_by_type
    return self.parse_orders(orders, market, since, limit)
  File "C:\Users\Administrator\IdeaProjects\ccxt_trading_bot\venv\lib\site-packages\ccxt\base\exchange.py", line 1337, in parse_orders
    array = [self.parse_order(order, market) for order in array]
  File "C:\Users\Administrator\IdeaProjects\ccxt_trading_bot\venv\lib\site-packages\ccxt\base\exchange.py", line 1337, in <listcomp>
    array = [self.parse_order(order, market) for order in array]
  File "C:\Users\Administrator\IdeaProjects\ccxt_trading_bot\venv\lib\site-packages\ccxt\coss.py", line 755, in parse_order
    marketId = marketId.toUppercase()
AttributeError: 'str' object has no attribute 'toUppercase'

- OS: win
- Programming Language version: python 
- CCXT version: 1.18.61
- Exchange: coss
- Method:fetch_open_orders(symbol)

**Comment by kroitor** [comment]
@blaaaaaaa thx for reporting, it was a minor transpiler typo, fixed in 1.18.62! Appreciate the feedback from you!

**Comment by blaaaaaaa** [comment]
Now with 1.18.64 it returns for fetch_open_orders(symbol) as empty list, but in the response we get the open orders:

Request: POST https://trade.coss.io/c/api/v1/order/list/open {'Signature': 'xxx', 'Authorization': 'xxx', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} {"timestamp":1545580775678,"symbol":"XRP_ETH"}
Response: POST https://trade.coss.io/c/api/v1/order/list/open 200 {'Server': 'Apache-Coyote/1.1', 'X-Frame-Options': 'SAMEORIGIN', 'X-Content-Type-Options': 'nosniff', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Date': 'Sun, 23 Dec 2018 15:59:36 GMT', 'Via': '1.1 google', 'Alt-Svc': 'clear'} {"total":1,"list":[{"hex_id":null,"order_id":"5f8b69fb-0613-4479-8b00-f4b709d99f7c","account_id":"15dc0ed3-05c4-4f20-947e-803dbd492c3f","order_symbol":"XRP_ETH","order_side":"SELL","status":"open","createTime":1545558663520,"type":"limit","timeMatching":0,"order_price":"0.00320800","order_size":"4.98","executed":"0","stop_price":"0.00000000","avg":"0.00320800","total":"0.01597584 ETH"},{"hex_id":null,"order_id":"9b57a012-f54f-4ec2-abfc-a813b98708eb","account_id":"15dc0ed3-05c4-4f20-947e-803dbd492c3f","order_symbol":"XRP_ETH","order_side":"BUY","status":"open","createTime":1545507730263,"type":"limit","timeMatching":0,"order_price":"0.00300200","order_size":"333.75","executed":"10.59","stop_price":"0.00000000","avg":"0.00300200","total":"1.00191750 ETH"}]}
[]   # printout from the resulting list of fetch_open_orders(symbol)

**Comment by interenet** [comment]
Fetch_open_orders(symbol) returns empty list. Ver 1.18.64, python.

**Comment by interenet** [comment]
Create_order('SELL', 'limit',.....) returns title html page

1.18.66, python

**Comment by kroitor** [comment]
@interenet can you paste your code to reproduce it and your verbose request/response here?
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by interenet** [comment]
CCXT returns the html code page instead of the error code when there is a lack of balance

thank

**Comment by kroitor** [comment]
@interenet looks like the order of the arguments in your create_order call does not correspond to the Manual: https://github.com/ccxt/ccxt/wiki/Manual#placing-orders... Should be:

```Python
symbol = 'ETH/BTC'
type = 'limit'
side = 'sell'  # or 'buy', lowercase
amount = 123.45
price = 0.02
create_order(symbol, type, side, amount, price)
```

> CCXT returns the html code page instead of the error code when there is a lack of balance

We have reported that to the tech team of COSS and will let you know when this is resolved.
