### ISSUE TITLE
Python ujson has much better performance than the std json

### ISSUE THREAD

**Issue by ngugcx** [ccxt/ccxt#4374]
Is it possible to use ujson(or yajl) instead of the std json in CCXT?
Thanks!

**Comment by kroitor** [comment]
> Is it possible to use ujson(or yajl) instead of the std json in CCXT?

Sure!

Let me know if this does not answer your question:

```Python
import ccxt
import ujson
from pprint import pprint
exchange = ccxt.binance({
    'parse_json': ujson.loads
})
pprint(exchange.fetchTicker('ETH/BTC'))
```

**Comment by ngugcx** [comment]
Thanks! This works for normal exchanges.
Exchanges like cryptopia whose responses need to be normalized  before json-parsing will fail.

**Comment by kroitor** [comment]
> Exchanges like cryptopia whose responses need to be normalized before json-parsing will fail.
Yep, but you can do a cryptopia-specific override in the same manner and fix the json before calling `loads`, basically, as long as you can override everything – this isn't an issue in CCXT )
