### ISSUE TITLE
create OKEX future Order failed

### ISSUE THREAD

**Issue by helldragonx** [ccxt/ccxt#4375]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:
exchange. InserOrder

-- code:
exchange = ccxt.okex({
    'apiKey': '**',
    'secret': '**',
    'enableRateLimit': True,
})
exchange.proxies = {"http": "socks5h://127.0.0.1:1080", "https": "socks5h://127.0.0.1:1080"}

exchange.create_order('BTC/USD', 'limit', 'sell', 1, 4200, {'contract_type': 'next_week', 'lever_rate': 20}  )

--------
The return is okex {"result":false,"error_code":20007} 

2007 in OKEX is parameter error, but I had checked these, no error seems, plz check your code,
thanks.

**Comment by kroitor** [comment]
@helldragonx can you paste your verbose request/response?

**Comment by kroitor** [comment]
I think you should also provide the `type` argument, according to their v1 docs:

https://github.com/okcoin-okex/API-docs-OKEx.com/blob/master/API-For-Futures-CN/%E5%90%88%E7%BA%A6%E4%BA%A4%E6%98%93REST%20API.md

![okex-future-trade](https://user-images.githubusercontent.com/1294454/50394906-c9cf0f80-0771-11e9-88a3-2c663acf7e18.jpg)

Let us know whether this solves the issue or not:

```Python
params = {
    'contract_type': 'next_week',
    'lever_rate': 20,
    'type': 1,  # 1:开多 2:开空 3:平多 4:平空
}
exchange.create_order('BTC/USD', 'limit', 'sell', 1, 4200, params)
```

**Comment by helldragonx** [comment]
thanks, got it. solved.
