### ISSUE TITLE
New exchange : Bitcoin Trade

### ISSUE THREAD

**Issue by danielcosta-ca** [ccxt/ccxt#4379]
BitcoinTrade is another brazilian exchange very stable e innovative. They currently support Bitcoin, Ethereum and Litecoin.

website: https://bitcointrade.com.br/
API: https://apidocs.bitcointrade.com.br/

**Comment by dinamic** [comment]
The URLs provided seem to be in Spanish. Is there English language support?

**Comment by kroitor** [comment]
@dinamic )

> Is there English language support?

No real need for that since we have Google Translate:

![br01](https://user-images.githubusercontent.com/1294454/50870847-c8852000-13ca-11e9-9179-40f92f456904.jpg)

![br02](https://user-images.githubusercontent.com/1294454/50870850-cc18a700-13ca-11e9-91c4-9679bf300f3b.jpg)

**Comment by viniciussvl** [comment]
Hello, I was also looking for this exchange, if adding it will be a maximum, thank you!

**Comment by An-Net** [comment]
Duplicate:

- https://github.com/ccxt/ccxt/issues/2284
