### ISSUE TITLE
exmo fetchTradingFees format has changed

### ISSUE THREAD

**Issue by omoxyron** [ccxt/ccxt#4381]
```
import ccxt
api = ccxt.exmo()
api.fetchTicker('BTC/USD')
```

fails with error:

> ---------------------------------------------------------------------------
> ExchangeError                             Traceback (most recent call last)
> <ipython-input-1-760913e48ee8> in <module>()
>       1 import ccxt
>       2 api = ccxt.exmo()
> ----> 3 api.fetchTicker('BTC/USD')
> 
> ~\Anaconda3\envs\py36\lib\site-packages\ccxt\exmo.py in fetch_ticker(self, symbol, params)
>     456 
>     457     def fetch_ticker(self, symbol, params={}):
> --> 458         self.load_markets()
>     459         response = self.publicGetTicker(params)
>     460         market = self.market(symbol)
> 
> ~\Anaconda3\envs\py36\lib\site-packages\ccxt\base\exchange.py in load_markets(self, reload, params)
>    1030                     return self.set_markets(self.markets)
>    1031                 return self.markets
> -> 1032         markets = self.fetch_markets(params)
>    1033         currencies = None
>    1034         if self.has['fetchCurrencies']:
> 
> ~\Anaconda3\envs\py36\lib\site-packages\ccxt\exmo.py in fetch_markets(self, params)
>     323 
>     324     def fetch_markets(self, params={}):
> --> 325         fees = self.fetch_trading_fees()
>     326         markets = self.publicGetPairSettings()
>     327         keys = list(markets.keys())
> 
> ~\Anaconda3\envs\py36\lib\site-packages\ccxt\exmo.py in fetch_trading_fees(self, params)
>     133         numParts = len(parts)
>     134         if numParts != 2:
> --> 135             raise ExchangeError(self.id + ' fetchTradingFees format has changed')
>     136         rest = parts[1]
>     137         parts = rest.split('</td>')
> 
> ExchangeError: exmo fetchTradingFees format has changed

- OS: win10
- Programming Language version: python 3.6
- CCXT version: ccxt-1.18.69
- Exchange: exmo
- Method: fetchTicker('BTC/USD')

**Comment by kroitor** [comment]
Are you sure that your version is 1.18.69? Because if I check it on my side it does work normally.

```
mbp:ccxt igorkroitor$ python3 examples/py/cli.py exmo fetch_ticker ETH/BTC
{'ask': 0.03412132,
 'askVolume': None,
 'average': 0.03365165,
 'baseVolume': 7474.67931736,
 'bid': 0.03405714,
 'bidVolume': None,
 'change': None,
 'close': 0.03418713,
 'datetime': '2018-12-25T18:57:24.000Z',
 'high': 0.03454478,
 'info': {'avg': '0.03365165',
          'buy_price': '0.03405714',
          'high': '0.03454478',
          'last_trade': '0.03418713',
          'low': '0.03291948',
          'sell_price': '0.03412132',
          'updated': 1545764244,
          'vol': '7474.67931736',
          'vol_curr': '255.53783353'},
 'last': 0.03418713,
 'low': 0.03291948,
 'open': None,
 'percentage': None,
 'previousClose': None,
 'quoteVolume': 255.53783353,
 'symbol': 'ETH/BTC',
 'timestamp': 1545764244000,
 'vwap': None}
mbp:ccxt igorkroitor$
```

So, I suggest that you check your runtime version of CCXT by running the following in your interpreter:

```Python
import ccxt
exchange = ccxt.exmo()
print(exchange.fetch_ticker('BTC/USD'))
print('CCXT version:', ccxt.__version__)  #  ←-------------- what does this line say?
```

**Comment by kroitor** [comment]
> Can this be solved and what are the best approaches to tackle this problem? Thanks

There's many options...

1. It depends whether you want to trade with it or not, because if not, you can simply switch of `fetchTradingFees` for that exchange via the constructor config

2. If you want to trade, but it blocks you for some reason – you can ask their admins to whitelist your IP

3. Alternatively, you can try a [CORS proxy or a proxy in general](https://github.com/ccxt/ccxt/wiki/Install#proxy), just to check if it makes a difference:

```Python
import ccxt
exchange = ccxt.exmo({
    'enableRateLimit': True,
})

exchange.proxy = 'https://cors-anywhere.herokuapp.com/'
exchange.origin = 'foobar123'  # random string

exchange.load_markets()

# restore them back to their defaults, you won't need it anymore if load_markets succeeds
exchange.proxy = ''
exchange.origin = '*'
```

4. You can try a VPN or a standard HTTPS proxy, also described on the `Install` page linked above...

5. If that doesn't help, we can probably improvise a few other workarounds...

Does that answer your question? )

**Comment by omoxyron** [comment]
Got it
Thank you for detailed answer
