### ISSUE TITLE
Script that works on Binance but get an error after couple of hours on bitstamp and Cex

### ISSUE THREAD

**Issue by ASAllon** [ccxt/ccxt#4386]
Hello,

I have a script that i'm running on Cex, Bitstamp and binance same script copied to different python files.

My system:
- OS: Ubuntu
- Programming Language version: Python
- CCXT version: 18.60
- Exchange: Cex and Bitstamp
- Method: fetch_order_book

The program run on binance for hours without any problem, but on it runs on Cex and especially on Bitstamp it get an error after 1-3 hours of runing...
I tried to understand the error without successes...
Maybe the script run on Binance without problems because it's library is more updated? (last commit 5 hours ago), and the Cex and Bitstamp library are older (1 month ago)?

Any help will be appreciated!

Great library!!

Thanks 

This is the main function from the script that raise the errors:

```
def check_tri(exchange, markets, balance, symbols_list, place_order=True):
    try:
        async def get_orderbook(exchange, symbols):
            asyncio.sleep(0.001)
            if exchange.id == 'cex':
                return await exchange.fetch_order_book(symbols, 1)
            else:
                return await exchange.fetch_order_book(symbols)

        start = time.time()
        loop = asyncio.get_event_loop()
        # result_list = [asyncio.ensure_future(exchange.fetch_order_book(symbols_list[sym], 1)) for sym in range(3)]
        result_list = [asyncio.ensure_future(get_orderbook(exchange, symbols_list[sym])) for sym in range(3)]

        pending = asyncio.Task.all_tasks()
        loop.run_until_complete(asyncio.gather(*pending))
        price1 = float(result_list[0].result()['asks'][0][0])
        price1volume = float(result_list[0].result()['asks'][0][1])

```

The error on bitstamp:

> (Error occurred:
> Traceback (most recent call last):
>   File "/home/ec2-user/.virtualenvs/lxmltest/local/lib/python3.6/dist-packages/ccxt/async_support/base/exchange.py", line 138, in fetch
>     proxy=self.aiohttp_proxy) as response:
>   File "/home/ec2-user/.virtualenvs/lxmltest/local/lib/python3.6/dist-packages/aiohttp/client.py", line 855, in __aenter__
>     self._resp = await self._coro
>   File "/home/ec2-user/.virtualenvs/lxmltest/local/lib/python3.6/dist-packages/aiohttp/client.py", line 469, in _request
>     break
>   File "/home/ec2-user/.virtualenvs/lxmltest/local/lib/python3.6/dist-packages/aiohttp/helpers.py", line 673, in __exit__
>     raise asyncio.TimeoutError from None
> concurrent.futures._base.TimeoutError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "bitstamp_2.06.py", line 562, in main
>     rate_list, reverse_rate_list = check_tri(exchange, markets, balance, sym, place_order=place_order)
>   File "bitstamp_2.06.py", line 64, in check_tri
>     loop.run_until_complete(asyncio.gather(*pending))
>   File "/usr/lib64/python3.6/asyncio/base_events.py", line 468, in run_until_complete
>     return future.result()
>   File "bitstamp_2.06.py", line 562, in main
>     rate_list, reverse_rate_list = check_tri(exchange, markets, balance, sym, place_order=place_order)
>   File "bitstamp_2.06.py", line 64, in check_tri
>     loop.run_until_complete(asyncio.gather(*pending))
>   File "/usr/lib64/python3.6/asyncio/base_events.py", line 468, in run_until_complete
>     return future.result()
>   File "bitstamp_2.06.py", line 562, in main
>     rate_list, reverse_rate_list = check_tri(exchange, markets, balance, sym, place_order=place_order)
>   File "bitstamp_2.06.py", line 64, in check_tri
>     loop.run_until_complete(asyncio.gather(*pending))
>   File "/usr/lib64/python3.6/asyncio/base_events.py", line 468, in run_until_complete
>     return future.result()
>   File "bitstamp_2.06.py", line 562, in main
>     rate_list, reverse_rate_list = check_tri(exchange, markets, balance, sym, place_order=place_order)
>   File "bitstamp_2.06.py", line 64, in check_tri
>     loop.run_until_complete(asyncio.gather(*pending))
>   File "/usr/lib64/python3.6/asyncio/base_events.py", line 468, in run_until_complete
>     return future.result()
>   File "bitstamp_2.06.py", line 562, in main
>     rate_list, reverse_rate_list = check_tri(exchange, markets, balance, sym, place_order=place_order)
>   File "bitstamp_2.06.py", line 64, in check_tri
>     loop.run_until_complete(asyncio.gather(*pending))
>   File "/usr/lib64/python3.6/asyncio/base_events.py", line 468, in run_until_complete
>     return future.result()
>   File "bitstamp_2.06.py", line 562, in main
>     rate_list, reverse_rate_list = check_tri(exchange, markets, balance, sym, place_order=place_order)
>   File "bitstamp_2.06.py", line 64, in check_tri
>     loop.run_until_complete(asyncio.gather(*pending))
>   File "/usr/lib64/python3.6/asyncio/base_events.py", line 468, in run_until_complete
>     return future.result()
>   File "bitstamp_2.06.py", line 55, in get_orderbook
>     return await exchange.fetch_order_book(symbols)
>   File "/home/ec2-user/.virtualenvs/lxmltest/local/lib/python3.6/dist-packages/ccxt/async_support/bitstamp.py", line 229, in fetch_order_book
>     }, params))
>   File "/home/ec2-user/.virtualenvs/lxmltest/local/lib/python3.6/dist-packages/ccxt/async_support/base/exchange.py", line 116, in fetch2
>     return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
>   File "/home/ec2-user/.virtualenvs/lxmltest/local/lib/python3.6/dist-packages/ccxt/async_support/base/exchange.py", line 156, in fetch
>     self.raise_error(RequestTimeout, method, url, e, None)
>   File "/home/ec2-user/.virtualenvs/lxmltest/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 348, in raise_error
>     raise exception_type(output)
> ccxt.base.errors.RequestTimeout: bitstamp GET https://www.bitstamp.net/api/v2/order_book/bchbtc/ )

The error on CEX:

> Error occurred:
> Traceback (most recent call last):
>   File "/home/ec2-user/.virtualenvs/lxmltest/local/lib/python3.6/dist-packages/ccxt/async_support/base/exchange.py", line 138, in fetch
>     proxy=self.aiohttp_proxy) as response:
>   File "/home/ec2-user/.virtualenvs/lxmltest/local/lib/python3.6/dist-packages/aiohttp/client.py", line 855, in __aenter__
>     self._resp = await self._coro
>   File "/home/ec2-user/.virtualenvs/lxmltest/local/lib/python3.6/dist-packages/aiohttp/client.py", line 391, in _request
>     await resp.start(conn)
>   File "/home/ec2-user/.virtualenvs/lxmltest/local/lib/python3.6/dist-packages/aiohttp/client_reqrep.py", line 770, in start
>     self._continue = None
>   File "/home/ec2-user/.virtualenvs/lxmltest/local/lib/python3.6/dist-packages/aiohttp/helpers.py", line 673, in __exit__
>     raise asyncio.TimeoutError from None
> concurrent.futures._base.TimeoutError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "CEX_2.06.py", line 562, in main
>     rate_list, reverse_rate_list = check_tri(exchange, markets, balance, sym, place_order=place_order)
>   File "CEX_2.06.py", line 64, in check_tri
>     loop.run_until_complete(asyncio.gather(*pending))
>   File "/usr/lib64/python3.6/asyncio/base_events.py", line 468, in run_until_complete
>     return future.result()
>   File "CEX_2.06.py", line 53, in get_orderbook
>     return await exchange.fetch_order_book(symbols, 1)
>   File "/home/ec2-user/.virtualenvs/lxmltest/local/lib/python3.6/dist-packages/ccxt/async_support/cex.py", line 198, in fetch_order_book
>     orderbook = await self.publicGetOrderBookPair(self.extend(request, params))
>   File "/home/ec2-user/.virtualenvs/lxmltest/local/lib/python3.6/dist-packages/ccxt/async_support/cex.py", line 487, in request
>     response = await self.fetch2(path, api, method, params, headers, body)
>   File "/home/ec2-user/.virtualenvs/lxmltest/local/lib/python3.6/dist-packages/ccxt/async_support/base/exchange.py", line 116, in fetch2
>     return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
>   File "/home/ec2-user/.virtualenvs/lxmltest/local/lib/python3.6/dist-packages/ccxt/async_support/base/exchange.py", line 156, in fetch
>     self.raise_error(RequestTimeout, method, url, e, None)
>   File "/home/ec2-user/.virtualenvs/lxmltest/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 348, in raise_error
>     raise exception_type(output)
> ccxt.base.errors.RequestTimeout: cex GET https://cex.io/api/order_book/BCH/EUR/?depth=1

**Comment by kroitor** [comment]
A `RequestTimeout` – is a normal thing and it is a recoverable error, however, in your script you're completely ignoring the error handling, have you read the corresponding section of the Manual? 

- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

If you're not familiar with the concept of python exceptions and handling errors in general – I'd recommend googling for "python exceptions tutorial" or searching for youtube videos.

In general, you will occasionally get a `RequestTimeout` due to reasons that depend on the quality of your connection, it's quite hard to list all factors here, there's a ton of them. But you should expect to get it from time to time from all exchanges, including Binance. So instead of avoiding it – you should catch it and ignore it, then simply retry again – and it will work.

An example code ↓ you might want to fix it where necessary

```Python
async def retry_to_fetch_orderbook(exchange, symbol):
    while True:
        response = None
        try:
            response = await exchange.fetch_order_book(symbol)
            return response
        except ccxt.RequestTimeout as e:
            pass #  ignore RequestTimeout, raise all other exceptions

def check_tri(exchange, markets, balance, symbols_list, place_order=True):
    try:
        async def get_orderbook(exchange, symbols):
            asyncio.sleep(0.001)
            response = await retry_to_fetch_orderbook(exchange, symbols)
            return response

        start = time.time()
        loop = asyncio.get_event_loop()
        # result_list = [asyncio.ensure_future(exchange.fetch_order_book(symbols_list[sym], 1)) for sym in range(3)]
        result_list = [asyncio.ensure_future(get_orderbook(exchange, symbols_list[sym])) for sym in range(3)]

        pending = asyncio.Task.all_tasks()
        loop.run_until_complete(asyncio.gather(*pending))
        price1 = float(result_list[0].result()['asks'][0][0])
        price1volume = float(result_list[0].result()['asks'][0][1])
```

Hope this answers your question. Let us know if not. Feel free to reopen this issue, or just ask further questions if any.

**Comment by ASAllon** [comment]
Thank very much! Ill try to adopt the error handling
