### ISSUE TITLE
Huobi fee field

### ISSUE THREAD

**Issue by alexeymarunin** [ccxt/ccxt#4387]
- OS: MacOS 10.14.1
- Programming Language version: Node.js
- CCXT version: 1.18.71
- Exchange: Huobi Global
- Method: fetchOrder

Я saw similar issues (#1349, #3672), but real fee is value of `field-fees` of `info` оbject

```
{
  "info": {
    "id": 20395337822,
    "symbol": "ethbtc",
    "account-id": 5685075,
    "amount": "0.001000000000000000",
    "price": "0.0",
    "created-at": 1545831584023,
    "type": "buy-market",
    "field-amount": "0.029100000000000000",
    "field-cash-amount": "0.000999788700000000",
    "field-fees": "0.000058200000000000",
    "finished-at": 1545831584181,
    "source": "spot-api",
    "state": "filled",
    "canceled-at": 0
  },
  "id": "20395337822",
  "timestamp": 1545831584023,
  "datetime": "2018-12-26T13:39:44.023Z",
  "symbol": "ETH/BTC",
  "type": "market",
  "side": "buy",
  "price": 0,
  "average": 0.034357,
  "cost": 0.0009997887,
  "amount": 0.001,
  "filled": 0.0291,
  "remaining": -0.0281,
  "status": "closed"
}
```

I checked - value `"0.000058200000000000"` is the same that I see in my orders list - 0.00005820 ETH

PS
Look at `remaining` field - is it correct calculation?

**Comment by kroitor** [comment]
> I checked - value "0.000058200000000000" is the same that I see in my orders list - 0.00005820 ETH

Will add that to the order structure there!

> Look at remaining field - is it correct calculation?

Nope, doesn't look correct to me – somehow the `amount` is less than the `filled`... I guess, for `market`+`buy` they put the order cost `cost` into the `amount`... Will add a workaround for that as well.

**Comment by alexeymarunin** [comment]
Sorry for my late)
This is market sell order

```
{
  "info": {
    "status": "ok",
    "data": "20417030197"
  },
  "id": "20417030197",
  "timestamp": 1545850970061,
  "datetime": "2018-12-26T19:02:50.061Z",
  "symbol": "ETH/BTC",
  "type": "market",
  "side": "sell",
  "amount": 0.0890994
}
```

**Comment by alexeymarunin** [comment]
I suppose `field-fees` may be an array in limit orders when order has a few trades to close
I will send you order structure if I find that case

**Comment by kroitor** [comment]
> This is market sell order

I mean `fetchOrder('20417030197')` in that case ) Can you (re-)fetch that order and show the structure of it here?

> I will send you order structure if I find that case

Great! Thx so much for reporting it and for your help!

**Comment by alexeymarunin** [comment]
> I mean fetchOrder('20417030197')

```
{
  "info": {
    "id": 20417030197,
    "symbol": "ethbtc",
    "account-id": 5685075,
    "amount": "0.089000000000000000",
    "price": "0.0",
    "created-at": 1545850969573,
    "type": "sell-market",
    "field-amount": "0.089000000000000000",
    "field-cash-amount": "0.002991468000000000",
    "field-fees": "0.000005982936000000",
    "finished-at": 1545850969734,
    "source": "spot-api",
    "state": "filled",
    "canceled-at": 0
  },
  "id": "20417030197",
  "timestamp": 1545850969573,
  "datetime": "2018-12-26T19:02:49.573Z",
  "symbol": "ETH/BTC",
  "type": "market",
  "side": "sell",
  "price": 0,
  "average": 0.033612,
  "cost": 0.002991468,
  "amount": 0.089,
  "filled": 0.089,
  "remaining": 0,
  "status": "closed"
}
```

**Comment by kroitor** [comment]
@alexeymarunin thx, it does confirm my assumption, for market-buys the `amount` represents the `cost` in quote currency, and for all other types – it represent the actual ordered `amount` in base currency.

**Comment by alexeymarunin** [comment]
> for market-buys the amount represents the cost in quote currency
That's right. And it's so sad me, because it breaks main idea of CCXT - unified interaction with all exchanges

So, let me know if you need something extra information about Huobi

**Comment by kroitor** [comment]
> because it breaks main idea of CCXT - unified interaction with all exchanges

Well, we still have a workaround for it, so, it was fixed in https://github.com/ccxt/ccxt/commit/4fdf3124f00bd54f96227fc22d95fb46cb76b368 and if you update to version 1.18.74 – it should work, including the fees and the proper amount/filled/remaining values. Let me know if you still have difficulties with it. )
