### ISSUE TITLE
No module named 'ccxt.async'

### ISSUE THREAD

**Issue by ironexmaiden** [ccxt/ccxt#4388]
No module named 'ccxt.async' error message appears when importing ccxt.async i have checked the python version is 3.6.6

- OS:linux
- Programming Language version:python3.6
- CCXT version:1.18.71
- Exchange:
- Method:

**Comment by kroitor** [comment]
It was renamed from `ccxt.async` to `ccxt.async_support` for Python 3.7+, here:

- https://github.com/ccxt/ccxt/pull/3281
- https://github.com/ccxt/ccxt/issues/3376

```Python
import ccxt.async_support as ccxt
```

**Comment by ironexmaiden** [comment]
Thank you I 've solved it
