### ISSUE TITLE
Binance: Trades and fees are not available on fetched orders

### ISSUE THREAD

**Issue by TechupBusiness** [ccxt/ccxt#4390]
Because this line overrides the default behavior:
https://github.com/ccxt/ccxt/blob/f761d6001cd813754735c93eb85d8354309223f2/js/binance.js#L272

It should be FULL instead of RESULT.

See binance API: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#user-content-new-order--trade

**Comment by kroitor** [comment]
> It should be FULL instead of RESULT.

Nope, it should be the exchange default (`RESULT`), and it should only differ from the exchange's default if the user wants to override it.

The override is easily done in one of two ways:

1. With constructor options:

```JavaScript
const exchange = new ccxt.binance ({
    'enableRateLimit': true,
    'options': {
        'newOrderRespType': 'FULL',
    },
})
```

2. With `params` overrides: https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

```JavaScript
const params = {
    'newOrderRespType': 'FULL',
}
const order = await exchange.createOrder (symbol, type, side, amount, price, params);
```

So, you have at least two ways of specifying the default behavior that you want.

Let us know if that doesn't answer your question.

**Comment by TechupBusiness** [comment]
@kroitor unforuntaley its NOT exchange default (please see linked docs in the first post): 

> Set the response JSON. ACK, RESULT, or FULL; **MARKET and LIMIT order types default to FULL, all other orders default to ACK.**
Limit orders return RESULT because its overriden in the ccxt!

And even if it would be default behavior: whats the purpose of "unifying" an API (and objects) if each exchange is returning different returns? Isn't it the goal that each exchange can be called exactly the same and returns the same structure "unified"? Without the need to implement a special behavior for each ccxt exchange in a third party application? I'm confused...

**Comment by kroitor** [comment]
The answer from Binance:

```
Igor Kroitor, [27.12.18 13:35]
Hello! A quick question on the newOrderRespType: does setting it always to FULL add any overhead on the exchange's side (apart from a more lengthy response) ? I mean, for example, for limit orders – is it true or false that a reply will be received faster in case of using ACK or RESULT instead of FULL ? In other words, what are the reasons for having anything except FULL ?

Ninj0r, [27.12.18 13:36]
Yes, ACK > RESULT > FULL in terms of speed.

Ninj0r, [27.12.18 13:37]
ACK only has to read 1 execution report, RESULT reads 2. FULL has to read all of them.

Ninj0r, [27.12.18 13:37]
Now how much faster? I am not sure.

Igor Kroitor, [27.12.18 13:38]
Ok, that answers my question, I understand that it cannot be measured directly and depends on varying factors

Ninj0r, [27.12.18 13:38]
Yeah it would be a function of the number of fills the order has. So a limit order that doesn't trade immediately, all 3 should be the same.

Ninj0r, [27.12.18 13:38]
But if that order has 50 trades or something, then RESULT is going to be slower.

Ninj0r, [27.12.18 13:38]
Plus the bigger payload and the time required to make the bigger payload, etc.

Igor Kroitor, [27.12.18 13:39]
👍
```

So, I guess, for market orders we will default to `FULL` and for limit orders we will default to `RESULT`. I think that fulfills the purpose of `createOrder` with respect to order type in the first place. @TechupBusiness How does that sound to you?

**Comment by TechupBusiness** [comment]
@kroitor Thanks. Hm I would simply follow the binance defaults and return FULL for market and limit orders, as it doesnt make sense to me to return it for market order but not for limit orders. It would be better to introduce a ccxt function which doesnt return the trades (and cut the trades then also for all exchanges that would return the trades) to have this performance benefit unified (IMHO this makes only sense if more exchange are offering this). Usually wrapper cost some performance but they increase the usability instead (less and better maintainable application code to write). 

If I - as an application developer - want to really profit from a library, all exchange-implementations should return the same objects. If no trades are existing, but instead a filled amount exist, this should be an inconsistent object then and is a bug to fix (I started writing a consistency checker for ccxt objects to find and reject these IMHO "bad" exchange implementations in my application). I really start missing this consistency in ccxt, the more I try using it. Because the current implementation doesn't allow me to simply change credentials and then use another exchange. Instead I need to carefully analyse each exchange, which properties are filled and if I need to submit additional settings to work properly (like a different nonce). Or if I need to have a cache and "fix" the object myself to become "unified" again (if you remember our bitstamp discussion), which IMHO should be the goal and output of ccxt. It's already hard to deal with acknowledged bugs, and I would really like to contribute. But if the philosophy of ccxt differs from what I expect it to be (a unifying library instead of a REST wrapper), then it's hard for me to contribute.

**Comment by kroitor** [comment]
> I would simply follow the binance defaults and return FULL for market and limit orders

Yeah, but their defaults are FULL for `market` orders and ACK for `limit` orders, so it's already a bit more unified then the raw API )

But, anyways, you're totally right – the goal of the library is to provide means of unification, yet, in the current version, the design is such that would return the order structure (without trades) and for order trades one would call `fetchOrderTrades` to get them separately.  The response time is a real concern here, not really our fault, just think: why would Binance set `ACK` for limit by default? That particular reason might be more important than pure convenience.

Also, you can still work with it in a unified manner, by doing something like

```JavaScript
// pseudocode
;(async () => {
    const overrides = {
        binance: { 'options': { newOrderResptType: { market: 'FULL', limit: 'FULL' }}},
        bitfinex: { ... },
        bittrex: { ... },
    }
    id = 'binance'
    exchange = new ccxt[id](overrides[id] || {})
    const order = await exchange.createOrder (...)
    console.log (order)
}) ()
```

But we will consider switching to FULL for `limit` orders as well, need more feedback from the users on this matter. Hope that sounds ok to you.

**Comment by TechupBusiness** [comment]
@kroitor I see the issue now, also that limit orders will often not have all trades in it. Especially since I noticed that even querying the order doesnt return the trades either. And its not possible to return the trades by orderId. Hm.

Could it make sense to allow lazy-loaded properties? But this would be a change from a POCO/simple object to one with some more business logic included. Is this a problem with the transpiler for all other languages?

Or it must be defined in the docs which special properties (like trades, as these seems to be the pain points that can't be solved by using a cache) needs eventually to be "lazy"-loaded by using a specific function. The example is still keeping the POCO/Plain Object architecture.

```javascript
;(async () => {
  let order = await exchange.fetchOrder (...)
  if(exchange['has']['fetchOrderTrades'] === true) {
    order = await exchange.fetchOrderTrades(order)
  }
  // -------------------------------
  let order = await exchange.createOrder (...)
  if(exchange['has']['fetchOrderTrades'] === true) {
    order = await exchange.fetchOrderTrades(order)
  }
}) ()
```
As far as I can see, we would be able to create order objects properly by:
1) using cache more extensively (which should be stored somewhere, I'm just saving it as Json to disk)
2) get new order information from exchange and update order accordingly (recalculate/emulate some values eventually by using the cache)
3) optional if has.getOrderTrades is true: get trades for the order and (eventually) recalculate other order values like fee etc in the `fetchOrderTrades` method. 

For binance we may need to cache all trades and reconstruct them for a specific order from cache, as its not possible to fetch trades for a single orderId from binance.

**Comment by omidkrad** [comment]
I have a question about `newOrderRespType`. Looks like this parameter is only for creating new order 
([API docs](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-order--trade)). So I assume if it's set to FULL then the order will include related trades only if it is a market order or limit order with immediate fills. But I cannot find a way to `fetchOrder` that includes trades with binance. Is it not possible and do I have to always make separate `fetchMyTrades` request to get the trade details?

**Comment by kroitor** [comment]
@omidkrad as far as I understand, you have to `fetchMyTrades` to get those fills, and there is no other way to do this.
