### ISSUE TITLE
market symbols are not common across exchanges

### ISSUE THREAD

**Issue by nimad** [ccxt/ccxt#4396]
The ccxt documentation states: "market symbols are common across exchanges which makes them suitable for arbitrage and many other things." Therefore for any combination of market.base and market.quote, we should have a unique market.symbol. However, there are over three hundred examples in CCXT where this is not the case.  For the markets where base = XRP and quote = BTC, most markets use XRP/BTC as a symbol. However, Bitmex has 4 entries for this market with 4 symbols:
.BXRPXBT
.BXRPXBT30M
XRPH19
XRPZ18
which are also the keys for these markets.

As a matter of fact, there are over 300 examples (see attachment ) where the same base and quote pairs are represented by multiple markets in the same exchange with different keys and different symbols.
[badSymbols.txt](https://github.com/ccxt/ccxt/files/2713504/badSymbols.txt)

.

- OS: Windows 10
- Programming Language version: Python 3.6
- CCXT version: 1.18.70
- Exchange: many
- Method: data issue

**Comment by kroitor** [comment]
> The ccxt documentation states: "market symbols are common across exchanges which makes them suitable for arbitrage and many other things."

That's right )

> Therefore for any combination of market.base and market.quote, we should have a unique market.symbol.

That isn't right, unfortunately. As explained in the Manual, a market symbol doesn't necessarily have a slash in it: 

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
- https://github.com/ccxt/ccxt/wiki/Manual#naming-consistency

> - Sometimes the user might notice a symbol like 'XBTM18' or '.XRPUSDM20180101' or some other "exotic/rare symbols". The symbol is not required to have a slash or to be a pair of currencies. The string in the symbol really depends on the type of the market (whether it is a spot market or a futures market, a darkpool market or an expired market, etc). Attempting to parse the symbol string is highly discouraged, one should not rely on the symbol format, it is recommended to use market properties instead.

> However, Bitmex has 4 entries for this market with 4 symbols:

This was answered in detail here: https://github.com/ccxt/ccxt/issues/3540. 

You're confusing the terminology: you can't have 4 different symbols for the same market – you can only have 4 different symbols for 4 different markets. So, what you see with BitMEX – those are different markets, not the same market, therefore different symbols to designate those markets.

Hope this answers your question, let us know if not.
