### ISSUE TITLE
coinmarketcap fetch_ticker('TUBE/USD') stopped working

### ISSUE THREAD

**Issue by nifflerco** [ccxt/ccxt#4397]
The following code used to work fine until few days ago it started to throw the following exception:

> coinmarketcap does not have market symbol TUBE/USD

```
<?php

namespace App\Model\Services\TradeSubsystem;

date_default_timezone_set('UTC');

use App\Model\Contracts\Interfaces\Services\TradeSubsystem\CryptoCurrencyServiceInterface;
use ccxt;
use ccxt\coinmarketcap;

class CryptoCurrencyService implements CryptoCurrencyServiceInterface
{

    public function updateGraphData($timeFrame, $limit)
    {

        $cmc = new coinmarketcap;
        dd($cmc->fetch_ticker('TUBE/USD'));

    }

}
```

PHP 7.2.10
Laravel 5.6
CCXT version is 1.18.76
Ubuntu 16.04
CoinMarketCap

I wonder whether it could be a problem with limits in fetch_ticker. Cause everything below first 100 crypto currency pairs throws same exception, while others from 1 to 100 work fine.

I made sure that https://github.com/ccxt/ccxt/commit/87bc69398a58a752520b8e564130cfc5936b59af
this fix is applied in my project, but it did not help.

**Comment by kroitor** [comment]
Looks like they've migrated to their PRO API: https://coinmarketcap.com/api/documentation/v1/#section/Version-History

Duplicate: https://github.com/ccxt/ccxt/issues/3899 ← I suggest to move this discussion there, if you don't mind, just to keep it all in one place. Thx!
