### ISSUE TITLE
asyncio - lower rateLimit not applying

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#4398]
- OS: Linux
- Programming Language version: python 3.7
- CCXT version: ccxt-1.18.78
- Exchange: binance

If I understand the usage of "rateLimit" correctly, then I should be able to get ccxt to speed up (I am aware that this could block my IP from the exchange) by modifying `"rateLimit"` to a lower number.

binance defaults to 500 - so I compared `500` with `10`, `10000` and `1`.

All apart from 10000 complete within 10-11 seconds, the setting seems to have no effect.
based on math, with 500 I would expect ~ 2 calls per second (so total runtime on default should be 5-6s, but it's 10s instead).

If I instead disable the rate-limiter (`enableRateLimit=False`), then the script is completing in ~4.5s.

Going lower with rateLimit seems impossible (with async), which i don't see documented anywhere (how to properly use rateLimit is not really well documented i think).

### comparison to sync rate-limiting script
Funnily enough, by using `basic-rate-limiter.py` and changing that to binance, i get the script to complete the 10 calls in 5s. The script does technically the same ... but apparently different limits (0.5s vs. 1s) are applied.

### sample code
using the sample async-basic-rate-limiter.py with 'binance' and 'ETH/BTC'

running the code with `time python async-basic-rate-limiter.py`.

```python
# -*- coding: utf-8 -*-

import asyncio
import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt.async_support as ccxt  # noqa: E402

async def main(exchange):
    for i in range(0, 10):
        print(await exchange.fetch_ticker('ETH/BTC'))
exchange = ccxt.binance({
    'enableRateLimit': True,  # this option enables the built-in rate limiter
    'rateLimit': 1
})

asyncio.get_event_loop().run_until_complete(main(exchange))
```

**Comment by kroitor** [comment]
> If I understand the usage of "rateLimit" correctly, then I should be able to get ccxt to speed up (I am aware that this could block my IP from the exchange) by modifying "rateLimit" to a lower number.

That's correct, and there was a typo in the default config for tokenBucket, so, instead of waiting for 0.001s it did wait for 1s between checking and sending again...

I've fixed it now so, is you update to version 1.18.79, it should work normally. Let me know if you still have issues with it after updating. Thx for reporting!
