### ISSUE TITLE
fetch_currencies method problem

### ISSUE THREAD

**Issue by ironexmaiden** [ccxt/ccxt#4400]
fetch_currencies method on binance and other exchanges returns empty array

-OS:Linux
-Programming Language version:Python
-CCXT version:1.18.79
-Exchange:binance and others
-Method:fetch_currencies

**Comment by kroitor** [comment]
Now, that's strange, can you show your code and verbose request/response?

**Comment by ironexmaiden** [comment]
def binance_currencies_with_min_conf():
	curs = ccxt.binance().fetch_currencies()
	print("Currencies:" + str(curs))
	print("binance Confs per Coin:")
	for key, value in curs.items():
		if float(value['info']['MinConfirmation']) <= 20:
		    print("Coin:" + key + "--------Confs:" + str(value['info']['MinConfirmation']))

**Comment by kroitor** [comment]
@ironexmaiden 

What do you see:

```Python
import ccxt
exchange = ccxt.binance({
    'verbose': True,
    'enableRateLimit': True,
})
currencies = exchange.fetch_currencies()
print(len(currencies), 'currencies')
```

?

**Comment by ironexmaiden** [comment]
output:0 currencies

**Comment by kroitor** [comment]
@ironexmaiden please read this carefully:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

I've posted a snippet that should have output a ton of info for debugging (`'verbose': True,`) – for some reason you've skipped it and you only pasted the last line of the entire output. We need it in order to tell the cause of the issue. Can you paste it here?

**Comment by kroitor** [comment]
@ironexmaiden also, please do this:

```Python
import ccxt
print(ccxt.__version__)
```

... and make sure it prints out the most recent version 1.18.83. If not – please, update to 1.18.83+. Let us know if that does not resolve the issue for you:

**Comment by ironexmaiden** [comment]
@kroitor both 1.18.83 and 1.18.84 return <<0 currencies>>

**Comment by kroitor** [comment]
@ironexmaiden can you please show the **verbose output** as described above?

**Comment by ironexmaiden** [comment]
1.18.84
0 currencies

**Comment by kroitor** [comment]
@ironexmaiden once again, please **read very carefull**, we need the verbose output:

```Python
import ccxt
exchange = ccxt.binance({
    'verbose': True,  # ←----------------- !!!
    'enableRateLimit': True,
})
currencies = exchange.fetch_currencies()
```

**Comment by kroitor** [comment]
Actually, it returns a dictionary of currencies:

```Python
import ccxt
exchange = ccxt.binance({
    # 'verbose': True,
    'enableRateLimit': True,
})
currencies = exchange.fetch_currencies()
codes = currencies.keys()
print(len(codes), 'currencies')
print(codes)
```

**Comment by ironexmaiden** [comment]
1.18.84
0 currencies
dict_keys([])

**Comment by kroitor** [comment]
@ironexmaiden 

- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

```Python
import ccxt
exchange = ccxt.binance({
    # 'verbose': True,
    'enableRateLimit': True,
})
exchange.load_markets()
codes = exchange.currencies.keys()
print(len(codes), 'currency codes')
print(codes)
```

**Comment by ironexmaiden** [comment]
@kroitor 
dict_keys(['ADA', 'ADX', 'AE', 'AGI', 'AION', 'AMB', 'APPC', 'ARDR', 'ARK', 'ARN', 'AST', 'BAT', 'BCD', 'BCH', 'BCN', 'BCPT', 'BLZ', 'BNB', 'BNT', 'BQX', 'BRD', 'BSV', 'BTC', 'BTG', 'BTS', 'CDT', 'CHAT', 'CLOAK', 'CMT', 'CND', 'CVC', 'DASH', 'DATA', 'DCR', 'DENT', 'DGD', 'DLT', 'DNT', 'DOCK', 'EDO', 'ELF', 'ENG', 'ENJ', 'EOS', 'ETC', 'ETH', 'EVX', 'FUEL', 'FUN', 'GAS', 'GNT', 'GO', 'GRS', 'GTO', 'GVT', 'GXS', 'HC', 'HOT', 'HSR', 'ICN', 'ICX', 'INS', 'IOST', 'IOTA', 'IOTX', 'KEY', 'KMD', 'KNC', 'LEND', 'LINK', 'LOOM', 'LRC', 'LSK', 'LTC', 'LUN', 'MANA', 'MCO', 'MDA', 'MFT', 'MITH', 'MOD', 'MTH', 'MTL', 'NANO', 'NAS', 'NAV', 'NCASH', 'NEBL', 'NEO', 'NPXS', 'NULS', 'NXS', 'OAX', 'OMG', 'ONT', 'OST', 'PAX', 'PHX', 'PIVX', 'POA', 'POE', 'POLY', 'POWR', 'PPT', 'QKC', 'QLC', 'QSP', 'QTUM', 'RCN', 'RDN', 'REN', 'REP', 'REQ', 'RLC', 'RPX', 'RVN', 'SALT', 'SC', 'SKY', 'SNGLS', 'SNM', 'SNT', 'STEEM', 'STORJ', 'STORM', 'STRAT', 'SUB', 'SYS', 'THETA', 'TNB', 'TNT', 'TRIG', 'TRX', 'TUSD', 'USDC', 'USDT', 'VEN', 'VET', 'VIA', 'VIB', 'VIBE', 'WABI', 'WAN', 'WAVES', 'WINGS', 'WPR', 'WTC', 'XEM', 'XLM', 'XMR', 'XRP', 'XVG', 'XZC', 'YOYOW', 'ZEC', 'ZEN', 'ZIL', 'ZRX'])

**Comment by kroitor** [comment]
> It outputs more but I cant post it due to message size

It's not necessary as it is working, obviously.

**Comment by ironexmaiden** [comment]
@kroitor it there any workaround to take the MinConfirmation from these keys?

**Comment by kroitor** [comment]
> it there any workaround to take the MinConfirmation from these keys?

You can do that with [implicit methods](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods):

```Python
import ccxt
exchange = ccxt.binance({'enableRateLimit': True})
exchange.load_markets()
response = exchange.web_get_assetwithdraw_getallasset_html()
for currency in response:
    code = exchange.commonCurrencyCode (currency['assetCode'])
    print(code, 'min confirmations:', currency['confirmTimes'])
```

**Comment by ironexmaiden** [comment]
thank you @kroitor

**Comment by ironexmaiden** [comment]
@kroitor web_get_assetwithdraw_getallasset_html function is not a common function for every exchange right?

**Comment by kroitor** [comment]
> @kroitor web_get_assetwithdraw_getallasset_html function is not a common function for every exchange right?

That's correct, we don't have the `minConf` logic unified yet, so in most cases you will have to do that in exchange-specific way, that is, until we unify it completely. Also, on OKEX, you might want to read this: https://github.com/ccxt/ccxt/issues/4063

**Comment by ironexmaiden** [comment]
Can I contribute in order to fix this bug?

**Comment by alsano3** [comment]
-OS:Ubuntu, and Windows10
-Programming Language version:Python 3.8.9 64-bit
-CCXT version: 1.50.16
-Exchange:binance 
-Method:fetch_currencies

I have a same problem. 
fetch_currencies, this return "None"

**Comment by kroitor** [comment]
@alsano3 

1. don't do `fetch_currencies`, do `load_markets()` instead as documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

The answer to this is in the source code:

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L690

```Python
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'options': {
        'fetchCurrencies': True,
    }
})

markets = exchange.load_markets()

pprint(exchange.currencies)
```

Let us know if that does not help.
