### ISSUE TITLE
[bitfinex2] publicGetStats1KeySizeSymbolLongHist() responce empty  

### ISSUE THREAD

**Issue by Arrmlet** [ccxt/ccxt#4401]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- Ubuntu:
- Python3:
- 1.18.83:
- Bitfinex:
- publicGetStats1KeySizeSymbolLongHist():

Hello everyone, I have a problem when I calling this function:
`bitfinex2.publicGetStats1KeySizeSymbolLongHist({'key':'pos.size', 'size':'1m', 'symbol':'tXRPBTC' })`
It's return me a nice list filled by data, but when I trying  to change the time for example to 5m,10m,15m,1h,4h,1d and so on this function return me the empty list .
i.e. this will return me a empty list
`bitfinex2.publicGetStats1KeySizeSymbolLongHist({'key':'pos.size', 'size':'5m', 'symbol':'tXRPBTC' })`

Happy New Year

**Comment by kroitor** [comment]
Hi!

> but when I trying to change the time for example to 5m,10m,15m,1h,4h,1d and so on this function return me the empty list

- https://docs.bitfinex.com/v2/reference#rest-public-stats

![bitfinex2-stats1-timeframes](https://user-images.githubusercontent.com/1294454/50532790-96083700-0b2f-11e9-8da4-3724b204ae20.jpg)

That endpoint only accepts the `1m` timeframe size. Hope that answers your question.
