### ISSUE TITLE
python: res_query.c:258: __libc_res_nquery: Assertion `hp != hp2' failed. Aborted

### ISSUE THREAD

**Issue by wmltyq** [ccxt/ccxt#4402]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: CentOS 6.8 64位
- Programming Language version: Python 3.6.3
- CCXT version: 1.18.23
- Exchange: itbit, gdax, bitstamp, bitfinex, gemini, kraken
- Method: fetch_ticker()

When I use ubuntu os is right, but when I use centos is return this error a few hours later. Why?

**Comment by frosty00** [comment]
something is wrong with your libcurl installation, nothing to do with ccxt

**Comment by wmltyq** [comment]
@frosty00 I don't need to change my code? How do I fix it?
