### ISSUE TITLE
Bitmex - private_put_order_bulk - php code sample - Question

### ISSUE THREAD

**Issue by darito21** [ccxt/ccxt#4411]
Hi, this is not an issue, It is mostly a question.
I need to create some instruction to place bulk orders, this is the only function until now I can not make work.

Can someone please give me a sample code for php use? 
Thank you.

- OS: Ubuntu 16.06
- Programming Language version: PHP 7.2
- CCXT version: 1.18.87
- Exchange: Bitmex
- Method: private_put_order_bulk 

---
Edit: Update on some tests...

```
$exchange = new \ccxt\bitmex (array (
'apiKey' => 'api',
'secret' => 'api',
'enableRateLimit' => true,
));

$bulk = $exchange->private_put_order_bulk ($orders);
print($bulk);
```

Problem with this code is the $orders array. I sent data in array format but I get errors like "data must be array". Also if I use json format:

`{"orders":[{"symbol":"XBTUSD","side":"Sell","orderQty":"10","price":5000},{"symbol":"XBTUSD","side":"Sell","orderQty":"15","price":5001}]};`

I get this error... problem is when the instruction is constructed, it tries to escape all " with \\
Is it a bug or Im doing something wrong.

```
PHP Fatal error:  Uncaught ccxt\BadRequest: bitmex {"error":{"message":"Unexpected token \" in JSON at position 0","name":"SyntaxError"}} in /root/ccxt/php/bitmex.php:601
Stack trace:
#0 /root/ccxt/php/Exchange.php(1198): ccxt\bitmex->handle_errors(400, '', 'https://www.bit...', 'PUT', Array, '{"error":{"mess...', Array)
#1 /root/ccxt/php/Exchange.php(1012): ccxt\Exchange->fetch('https://www.bit...', 'PUT', Array, '"{\\"orders\\":[{...')
#2 /root/ccxt/php/Exchange.php(1016): ccxt\Exchange->fetch2('order/bulk', 'private', 'PUT', '{"orders":[{"sy...', NULL, NULL)
#3 [internal function]: ccxt\Exchange->request('order/bulk', 'private', 'PUT', '{"orders":[{"sy...')
#4 /root/ccxt/php/Exchange.php(941): call_user_func(Array, 'order/bulk', 'private', 'PUT', '{"orders":[{"sy...')
#5 [internal function]: ccxt\Exchange->ccxt\{closure}('{"orders":[{"sy...')
#6 /root/ccxt/php/Exchange.php(2073): call_user_func_array(Object(Closure), Array)
#7 /root/bmts/test.php(25): ccxt\Exchange->__call('private_put_ord...', Array)
#8 {main}
  thrown in /root/ccxt/php/bitmex.php on line 601
```

Can someone give me a tip on how to construc the $orders array correctly? 
Thank you and happy new year!

**Comment by frosty00** [comment]
https://github.com/ccxt/ccxt/tree/master/examples/php

**Comment by darito21** [comment]
> https://github.com/ccxt/ccxt/tree/master/examples/php

Hmm, I checked before and there is nothing for "bulk orders", only standard ones.
Thanks

**Comment by darito21** [comment]
Edited my original post with some php code tests. It looks like a bug, please take a look and correct me if Im wrong.
Thanks

**Comment by kroitor** [comment]
@darito21 can you show how you set the `$orders` variable?

```PHP
$exchange = new \ccxt\bitmex (array (
'apiKey' => 'api',
'secret' => 'api',
'enableRateLimit' => true,
));

// ------------------ the most significant part of your code is missing here -----------

$bulk = $exchange->private_put_order_bulk ($orders);
print($bulk);
```

**Comment by darito21** [comment]
> @darito21 can you show how you set the `$orders` variable?
> 
> ```
> $exchange = new \ccxt\bitmex (array (
> 'apiKey' => 'api',
> 'secret' => 'api',
> 'enableRateLimit' => true,
> ));
> 
> // ------------------ the most significant part of your code is missing here -----------
> 
> $bulk = $exchange->private_put_order_bulk ($orders);
> print($bulk);
> ```

$orders = '{"orders":[{"symbol":"XBTUSD","side":"Sell","orderQty":"10","price":5000},{"symbol":"XBTUSD","side":"Sell","orderQty":"15","price":5001}]};';

The above code, without the var set, only the json data, works perfect in the api explorer of Bitmex, and after reading errors it looks like ccxt is trying to escape all quotes with \\" and post it to Bitmex, then Bitmex respond with an error of unexpected token \

Any input?
Thanks

**Comment by kroitor** [comment]
```PHP
$orders = '{"orders":[{"symbol":"XBTUSD","side":"Sell","orderQty":"10","price":5000},{"symbol":"XBTUSD","side":"Sell","orderQty":"15","price":5001}]};';
```

↑ This is a wrong way of doing it. You're passing in a string, whereas all implicit methods actually accept JSON-structures (objects).

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

So the proper way is:

```PHP
$orders = array (
    "orders" => array (
         array ("symbol" => "XBTUSD", "side" => "Sell" "orderQty" => "10", "price" => 5000),
         array ("symbol" => "XBTUSD", "side" => "Sell", "orderQty" => "15", "price" => 5001),
    )
);

$bulk = $exchange->private_put_order_bulk ($orders);
print($bulk);
```

Let us know if that does not help. Feel free to reopen this issue or just ask further questions if any.

**Comment by darito21** [comment]
Thank you, it works! But I needed to correct two things, the code below is working fine:

```
$orders = array (
    "orders" => array (
         array ("symbol" => "XBTUSD", "side" => "Buy", "orderQty" => 10, "price" => 3000),
         array ("symbol" => "XBTUSD", "side" => "Buy", "orderQty" => 15, "price" => 3001),
    ),
);

$bulk = $exchange->private_post_order_bulk ($orders);
print_r($bulk);
```
Corrections:
Method is "private_post_order_bulk" for orders creation. (private_put_order_bulk is for editing).
I removed quotes from "orderQty" values, since they are not needed and they generated errors.
print($bulk) replaced by print_r($bulk) 

Thanks again for your reply.

**Comment by kroitor** [comment]
@darito21 thx to you for the feedback as well!
