### ISSUE TITLE
Exmo balance for FIATs

### ISSUE THREAD

**Issue by christiangoltz** [ccxt/ccxt#4421]
Hi, when requesting my balances from exmo, the FIAT currencies are missing.

- OS: Ubuntu 18.04
- Programming Language version: NodeJS v10.14.1
- CCXT version:  1.10.1 2017-11-06
- Exchange: Exmo
- Method: fetchBalance

The actual response from the exmo api contains the FIAT balances. I checked the code of `fetchBalance` and that one filters for the currencies that have been previously fetched. The currency fetching seems to be based on withdrawal fees. My exmo account however is not verified and the exmo api answer for the withdrawal fees does not contain the FIAT currencies, probably because you cannot withdraw them with an unverified account.

I will verify my account to check if that changes the situation.

The exmo API has a method `currencies` that would get a list of the currencies, not sure if that already existed at the time the ccxt exmo part was done.

I can try to provide a fix for this later on if you can confirm that this is an issue and I am not doing it wrong ;)

**Comment by kroitor** [comment]
Looks like fiat currencies are reported by EXMO, but the handling for them is missing here:

- https://github.com/ccxt/ccxt/blob/master/js/exmo.js#L231

Nothing to do with your account.
Do you want to give it a try and fix it?

**Comment by christiangoltz** [comment]
Ah alright, didn't look that deep yet. Yes let me try to make a fix!

**Comment by kroitor** [comment]
@christiangoltz great, just make sure to read this first: 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

:)

**Comment by kroitor** [comment]
Your fix is merged in #4422! The new build of CCXT version 1.18.93 will arrive in 5-10 minutes. Thx for the contribution and for your involvement!
