### ISSUE TITLE
CCXT BitMex HTTP Keep Alive

### ISSUE THREAD

**Issue by vcreddy22** [ccxt/ccxt#4424]
- OS: Windows
- Programming Language version: Python 3.7
- CCXT version: latest version 1.18
- Exchange: BitMex
- Method:

I was wondering how to do a HTTP keep alive connection in python for BitMex using the CCXT library

**Comment by kroitor** [comment]
Let us know if this does not answer the question: http://docs.python-requests.org/en/master/user/advanced/#keep-alive
