### ISSUE TITLE
Support OAuth2 API for Coinbase Exchange

### ISSUE THREAD

**Issue by oaramirez89** [ccxt/ccxt#4425]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: N/A
- Programming Language version: JS
- CCXT version: Future
- Exchange: Coinbase
- Method: Initialization (ccxt.coinbase(apiKey, secret)

Are there plans to add OAuth2 support for the Coinbase exchange, and have a signature accepting accessToken and/or refreshToken when initializing a connection to Coinbase through ccxt?

**Comment by kroitor** [comment]
> Are there plans to add OAuth2 support for the Coinbase exchange, and have a signature accepting accessToken and/or refreshToken when initializing a connection to Coinbase through ccxt?

If you have an access token then it should work as is, like so:

```JavaScript
const accessToken = '6915ab99857fec1e6f2f6c078583756d0c09d7207750baea28dfbc3d4b0f2cb80'

const exchange = new ccxt.coinbase ({
    'apiKey': 'ANY_KEY', // required, but doesn't matter
    'secret': 'ANY_SECRET', // required, but doesn't matter
    'headers': {
        'Authorization': 'Bearer ' + accessToken,
    },
})
```

You will have to refresh it manually when it expires, though. We will more code to get and refresh those  OAuth2 tokens automatically in the future, but we don't have an ETA on that yet. Hope that answers the question. Let us know if not.

**Comment by oaramirez89** [comment]
Thank you for the quick response. Yes, indeed this answers my question.

**Comment by oaramirez89** [comment]
@kroitor With the code you provided I was able to create a client successfully but when I try to use that client to fetch balances I get an authentication error. Are all APIs supported with OAuth? 

Call
`client.fetchBalance()...`

Error returned
`{ Error: coinbase {"errors":[{"id":"authentication_error","message":"invalid api key"}]}
[Node]     at coinbase.handleErrors (/Users/oaramirez64/GoogleDrive/Cha-Ching/Back-End/node_modules/ccxt/js/coinbase.js:606:39)
[Node]     at response.text.then (/Users/oaramirez64/GoogleDrive/Cha-Ching/Back-End/node_modules/ccxt/js/base/Exchange.js:663:18)
[Node]     at process._tickCallback (internal/process/next_tick.js:68:7) constructor: [Function: AuthenticationError] }`

**Comment by kroitor** [comment]
@oaramirez89 looks like we will have to add a few workarounds into the lib to make it work properly, hope to get to it asap. Will let you know when it's there.

**Comment by oaramirez89** [comment]
Hello @kroitor wondering whether you got a chance to think about this ticket and if you could provide an estimated implementation time. Thank you.

**Comment by kroitor** [comment]
@oaramirez89 https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar )

**Comment by oaramirez89** [comment]
Thank you for the quick response @kroitor. In a way I wish you would have sent me that link in your original response. I certainly agree with it. I only misunderstood when you mentioned you'd get back to me. I will discuss with my team what approach to take. Cheers.

**Comment by kroitor** [comment]
@oaramirez89 pardon if i wasn't clear at first, but, yeah, I will be happy to see a PR from you, let me know if you have any questions... I hope to get to it as soon as I can, if nobody else does that first.

**Comment by oaramirez89** [comment]
@kroitor Quick question regarding Coinbase definition in js/coinbase.js lines 22-50 where it is defined which functionality is supported. How is it determined which are true and which are false? For example we use fetchDepositAddress and withdraw. Both of these are set to false in the coinbase.js definition. 
Also, if you could point me to the code where OAuth was implemented previously so I can get an idea how to contribute the changes I need? Thank you for your time.

**Comment by oaramirez89** [comment]
@kroitor Just following up on my last question above. Any guidance for me to start working on a PR would be appreciated.

**Comment by TotallyKyle** [comment]
I have implemented a workaround on my local version but I would like to ask @kroitor some questions on the approach before I submit the PR.

One approach is to solve this specifically for coinbase:
We can do this by skipping the checkRequiredCredentials call and headers generation in the coinbase sign method. We just apply whatever headers we specified from the class directly.

The second approach is to solve this for all exchanges using the token property of the base class. We would write some overrides into the base Exchange checkRequiredCredentials to check for token property before checking for the other requiredCredentials specified in each exchange. Finally it would require work on all exchange specific sign methods to create the appropriate Authorization header from the token.

Which approach would you prefer, I can provide some snippets if it helps?

**Comment by kroitor** [comment]
@TotallyKyle we would prefer the second approach. At this time we already have some exchanges implementing the support for `token` and the `signIn` method:

- https://github.com/ccxt/ccxt/blob/master/js/adara.js#L1212
- https://github.com/ccxt/ccxt/blob/master/js/bitmart.js#L871
- https://github.com/ccxt/ccxt/blob/master/js/bitmart.js#L167
- https://github.com/ccxt/ccxt/blob/master/js/stex.js#L1413

However, at this time the above is done in an exchange-specific way and it has to be unified. The most important aspect in all of this is not how to make sure it works when everything is ok, but how to properly handle exceptions without producing garbage on the exchange instance in the async environment, including token expiration times and other related things. In other words, we pay 90% of attention to cases when something might not go well.
