### ISSUE TITLE
sh: opencollective: command not found  when install by npm

### ISSUE THREAD

**Issue by elanpang** [ccxt/ccxt#4426]
- OS:MacOS 10.14.1
- Programming Language version:es6,react native
- CCXT version:1.18.95

I installed last version ccxt(1.18.95) with command 
npm install -save
But it failed,details see the picture below:

![b13c793d-29cf-4f70-af25-65fcb9e0673d](https://user-images.githubusercontent.com/6789154/50629411-6dd96780-0f77-11e9-9f42-3d21964b6d75.png)

**Comment by xpl** [comment]
@elanpang

What is your version of npm? Try upgrading it to the latest version. Also, does the `npm install ccxt` command work from another project folder? Try creating an empty folder, run `npm init` and then `npm install ccxt` — does that work?

**Comment by elanpang** [comment]
@xpl  
npm 6.5.0

I tried install in a new empty folder, then it works, so strange

**Comment by elanpang** [comment]
@xpl 

What should I do in my project folder, do you have any idea?

**Comment by kroitor** [comment]
@elanpang you said you did `npm install -save` with one dash (`-save`), however, the proper syntax is `npm install --save` (two dashes `--save`). Does it work with two dashes? 

Also, do you have a `package.json` file in your project folder?

**Comment by elanpang** [comment]
@kroitor 
two dashes --save also not work, It still reports `opencollective: command not found`
I have package.json in my project , installed many other packages and works . 
I tried install ccxt with a new project and it works.
I also tried `npm cache clean -f`  and `npm cache verify`, still not worked.

**Comment by kroitor** [comment]
@elanpang i'd suggest to remove the `node_modules` folder and reinstalling the modules again from scratch:

```bash
# in your project folder
rm -rf node_modules
npm install
npm install ccxt --save
```

Does that work?

**Comment by elanpang** [comment]
good news, the issue was solved!

I deleted node_modules folder and re-install all , then the ccxt was installed.

@xpl @kroitor   Thank you very much.
