### ISSUE TITLE
askVolume and betVolume for exchanges

### ISSUE THREAD

**Issue by kobej1** [ccxt/ccxt#4432]
Hello,

I only get the askVolume and betVolume for Binance when using the price ticker method is this normal? If yes is there a way to get these values? 
(I used the exchanges: binance, bittrex, bitfinexcrex24, hitbtc and kraken.)

Thank you in advance!

**Comment by kroitor** [comment]
`askVolume` and `bidVolume` will only be defined if the underlying exchange provides that information from the ticker endpoint. If not – those will be undefined. Not all exchanges provide that information in the ticker call. So, yes, that is normal. If you want the bid and ask volume for each exchange universally – you should call fetchOrderBook and get values from there.
