### ISSUE TITLE
Undefined Index Time Gdax PHP

### ISSUE THREAD

**Issue by ceaser1996** [ccxt/ccxt#4440]
It Gives this error I am attaching the full stack trace please look at it.

`[2019-01-04 12:59:22] local.ERROR: Undefined index: time {"exception":"[object] (ErrorException(code: 0): Undefined index: time at /var/www/html/cryptosigresponsive/vendor/ccxt/ccxt/php/gdax.php:215)
[stacktrace]
#0 /var/www/html/cryptosigresponsive/vendor/ccxt/ccxt/php/gdax.php(215): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/html/c...', 215, Array)
#1 /var/www/html/cryptosigresponsive/vendor/ccxt/ccxt/php/Exchange.php(1636): ccxt\\gdax->fetch_ticker('CVC/USDC', Array)
#2 /var/www/html/cryptosigresponsive/app/Services/ExchangeService.php(99): ccxt\\Exchange->fetchTicker('CVC/USDC')
#3 /var/www/html/cryptosigresponsive/app/Services/ExchangeService.php(103): App\\Services\\ExchangeService::marketJob(4, Object(App\\Services\\ccxt\\gdax), Array, 1, NULL)
#4 /var/www/html/cryptosigresponsive/app/Jobs/MarketJob.php(58): App\\Services\\ExchangeService::marketJob(4, Object(App\\Services\\ccxt\\gdax), Array, 1)
#5 [internal function]: App\\Jobs\\MarketJob->handle()
#6 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#7 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#9 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#10 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#11 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\MarketJob))
#12 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\MarketJob))
#13 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#14 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\MarketJob), false)
#15 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\RedisJob), Array)
#16 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\\Queue\\Jobs\\Job->fire()
#17 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#18 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#19 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon('redis', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#20 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'default')
#21 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#22 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#23 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#25 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#26 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#27 /var/www/html/cryptosigresponsive/vendor/symfony/console/Command/Command.php(252): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#28 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#29 /var/www/html/cryptosigresponsive/vendor/symfony/console/Application.php(938): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 /var/www/html/cryptosigresponsive/vendor/symfony/console/Application.php(240): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 /var/www/html/cryptosigresponsive/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 /var/www/html/cryptosigresponsive/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 /var/www/html/cryptosigresponsive/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#35 {main}
"} `

*What is the reason is the any issue with the pair or any issue from coinbase side .Please provide me the sollution to solve this .

- OS:Ubuntu 16.04
- Programming Language version:Php 7.2
- CCXT version:Latest
- Exchange:Gdax
- Method:Public

**Comment by kroitor** [comment]
@ceaser1996 can you show your code to reproduce the issue? Please follow these guides precisely: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by kroitor** [comment]
@ceaser1996 @emersonboyd there was a minor issue with the `market['active']` flag not being properly set there, so i've uploaded a quickfix and if you update to version 1.18.114 this should work:

```Python
import ccxt

exchange = ccxt.gdax({
    'enableRateLimit': True,
})
exchange.load_markets()  # instead of fetch_markets
symbol = 'MKR/USDC'
if exchange.markets[symbol]['active']:
    print(exchange.fetch_ticker(symbol))
else:
    print(exchange.id, symbol, 'is inactive')
```

Docs:

- https://github.com/ccxt/ccxt/wiki/Manual#market-structure
- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
- https://github.com/ccxt/ccxt/wiki/Manual#market-cache-force-reload

Hope this helps, let us know if not.

**Comment by ceaser1996** [comment]
1.18.114 version is not present in Packagist please update there or let me know how to install the version u mentioned into my project as I am installing composer for maintaining package dependency.
Please let me know as soon as possible.

**Comment by kroitor** [comment]
@ceaser1996 please check Packagist again, should be ok now, all versions should be there.
