### ISSUE TITLE
Bitfinex fetch OHLCV issue

### ISSUE THREAD

**Issue by Andi1990** [ccxt/ccxt#4442]
OS: -
Programming Language version: Python 3.6
CCXT version: Latest
Exchange: Bitfinex
Methods (below)

def fetch_ohlcv(self, symbol, timeframe='1m', since=None, limit=None, params={}):
self.load_markets()
        if limit is None:
            limit = 100
        market = self.market(symbol)
        v2id = 't' + market['id']
        request = {
            'symbol': v2id,
            'timeframe': self.timeframes[timeframe],
            'sort': 1,
            'limit': limit,
        }
        if since is not None:
            request['start'] = since
        response = self.v2GetCandlesTradeTimeframeSymbolHist(self.extend(request, params))
return self.parse_ohlcvs(response, market, timeframe, since, limit)

The input parameters of method _fetch_ohlcv_ are hardcoded (timeframe='1m'). However, the parameters need to be modifiable.

Suggestion: Change to fetch_ohlcv(self, symbol, timeframe, since, limit, params={})

**Comment by kroitor** [comment]
> The input parameters of method fetch_ohlcv are hardcoded (timeframe='1m').

That's not hardcode, those are default argument values: https://www.google.com/search?q=python+default+function+arguments

> However, the parameters need to be modifiable.

Yep, and they are. Hope this answers your question.
