### ISSUE TITLE
Referral link embedded in code

### ISSUE THREAD

**Issue by fqlx** [ccxt/ccxt#4444]
Is there any reason for someone's referral link to be included?  

https://github.com/ccxt/ccxt/blob/80c4837d91ac06c0fb3197f20a45e91d4a95d409/python/ccxt/async_support/kucoin.py#L67

**Comment by kroitor** [comment]
Yep, that's the ref id of the CCXT Dev Team – helps sustain the ongoing development, you know )
You can use `www` instead of `referral` if you don't want it. Hope this answers the question, let us know if not.

**Comment by fqlx** [comment]
Is using the referral ID enabled by default or will I need to opt-in? I don't mind supporting the CCXT dev team.

**Comment by kroitor** [comment]
> Is using the referral ID enabled by default or will I need to opt-in? I don't mind supporting the CCXT dev team.

It's not used for anything except linking to exchanges from our webpage here: 

- https://github.com/ccxt/ccxt#supported-cryptocurrency-exchange-markets

![kucoin-ref](https://user-images.githubusercontent.com/1294454/50789143-752ca800-12cc-11e9-9544-4db7c72901ab.jpg)

So, for it to work, the user has to click that link and then sign up with Kucoin with our refid – in that case we will get a reward. The ref id is not involved when you're using CCXT. It is only involved in the account signup process.

But hey, thanks anyway, we welcome all contributions! )

- https://github.com/ccxt/ccxt#support-developer-team
