### ISSUE TITLE
Add fetchMyTrades() method for livecoin

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#4445]
- Exchange: livecoin
- Method: fetchMyTrades()

Would be nice to add fetchMyTrades() method for livecoin, as I understand they have API for this. https://www.livecoin.net/api/userdata#exchangetrades

**Comment by goushijie** [comment]
Does bitmex implement fetchMyTrades?

**Comment by kroitor** [comment]
@goushijie 

<img width="1505" alt="screen shot 2019-01-24 at 19 15 17" src="https://user-images.githubusercontent.com/1294454/51691740-67855b00-200c-11e9-9b3e-deb5f1cfdd1c.png">

**Comment by kroitor** [comment]
Fixed by the author: https://github.com/ccxt/ccxt/pull/4965. Thx @ndubel !
