### ISSUE TITLE
New exchange e-juno

### ISSUE THREAD

**Issue by rodoufu** [ccxt/ccxt#4458]
Brazilian exchange, I'm thinking about adding it myself, I just haven't been able to do that yet.

URL:
https://www.e-juno.com.br/home

API:
https://www.e-juno.com.br/docs

**Comment by An-Net** [comment]
Latoex (ex E-juno) shutdown since 16 March 2020:

- https://latoex.com/home

![Снимок экрана 2020-03-25 в 20 50 41](https://user-images.githubusercontent.com/51840849/77568844-51a64b00-6eda-11ea-98eb-79b5591ac797.png)
