### ISSUE TITLE
New exchange 3xbit

### ISSUE THREAD

**Issue by rodoufu** [ccxt/ccxt#4459]
Brazilian exchange, I'm thinking about adding it myself, I just haven't been able to do that yet.

URL:
https://3xbit.com.br/

**Comment by An-Net** [comment]
The website doesn't work anymore:

- https://portaldobitcoin.com/investidor-processa-3xbit-apos-ter-r-300-mil-transferidos-de-sua-conta-para-negociecoins/

- https://livecoins.com.br/corretora-de-bitcoin-3xbit-sai-do-ar/

- https://cointelegraph.com.br/news/justica-determina-bloqueio-de-r-200-mil-em-contas-da-3xbit-exchange-esta-fora-do-ar-e-sem-pagar-clientes
