### ISSUE TITLE
New exchange modiax

### ISSUE THREAD

**Issue by rodoufu** [ccxt/ccxt#4465]
Brazilian exchange, I'm thinking about adding it myself, I just haven't been able to do that yet.

URL:
https://www.modiax.com/

API:
https://app.modiax.com/documents/api/v2

**Comment by An-Net** [comment]
Shutdown since 28 March 2021
https://foxbit.com.br/central-de-ajuda-modiax/
<img width="1440" alt="Снимок экрана 2021-05-20 в 23 13 06" src="https://user-images.githubusercontent.com/51840849/119042776-f6c69180-b9c0-11eb-91a1-897d307fc546.png">
