### ISSUE TITLE
hitbtc and hitbtc2 market BCH is converted to BCC

### ISSUE THREAD

**Issue by lidancheng** [ccxt/ccxt#447]
hi, I found a bug in version '1.9.321'.
the hitbtc.com has BCH and BCC, in the moudle loadMarkets, automatic convert the BCC to BCH, so I can't get the BCH ticker forever.
If it's a bug, please fix it.
thanks for your bset work!

**Comment by kroitor** [comment]
Hi! Sorry, can you please post your code?
Use triple backticks for readability:

&#96;&#96;&#96;
your code
&#96;&#96;&#96;

**Comment by kroitor** [comment]
If you mean this: https://blog.hitbtc.com/alert-on-bitcoin-cash-ticker-change/
I'll fix for it shortly. Thx!

**Comment by kroitor** [comment]
This is fixed in 1.9.341+. Both BCH and BCC tickers are available since they renamed Bitcoin Cash to BCH (as the majority of exchanges call it). Let us know if it works for you or not (it should). Thx again!
