### ISSUE TITLE
New exchagne bitcointoyou

### ISSUE THREAD

**Issue by rodoufu** [ccxt/ccxt#4473]
Brazilian exchange, I'm thinking about adding it myself, I just haven't been able to do that yet.

URL:
https://pt.bitcointoyou.com/

API:
https://pt.bitcointoyou.com/universo-bitcoin/api-b2u/

**Comment by rodoufu** [comment]
Already been done at https://github.com/ccxt/ccxt/issues/2284

**Comment by ah2020b** [comment]
Could you update to the new domain?

https://api_v1.bitcointoyou.com/METHOD

More information here
https://pt.bitcointoyou.com/universo-bitcoin/api-b2u/
