### ISSUE TITLE
how can I get  timestamp when use fetch_order_book

### ISSUE THREAD

**Issue by liuhuanshuo** [ccxt/ccxt#4474]
- OS: macOS Mojave
- Programming Language version:py3.6

```
import ccxt
symbol = 'BTC/USD'
bitmex = ccxt.bitmex()
orderbook = bitmex.fetch_order_book(symbol)

```
result：{'bids': [[4008.5, 519915], [4008, 197548], [4007.5, 94714], [4007, 14827], [4006.5, 81134], [4006, 29989], [4005.5, 67601], [4005, 107184], [4004.5, 62835], [4004, 207348], [4003.5, 91251], [4003, 117546], [4002.5, 88448], [4002, 84713], [4001.5, 224204], [4001, 329222], [4000.5, 406324], [4000, 799556], [3999.5, 39650], [3999, 148904], [3998.5, 320356], [3998, 428553], [3997.5, 93238], [3997, 125765], [3996.5, 104556]], 'asks': [[4009, 832410], [4009.5, 87945], [4010, 322760], [4010.5, 266710], [4011, 319420], [4011.5, 581732], [4012, 77349], [4012.5, 180479], [4013, 585900], [4013.5, 24620], [4014, 123190], [4014.5, 58735], [4015, 147574], [4015.5, 42812], [4016, 236615], [4016.5, 29030], [4017, 31317], [4017.5, 43490], [4018, 126330], [4018.5, 77122], [4019, 147639], [4019.5, 24460], [4020, 129076], [4020.5, 361014], [4021, 144792]], 'timestamp': None, 'datetime': None, 'nonce': None}

timestamp is None.
Why
how can I get timestamp?

**Comment by kroitor** [comment]
> timestamp is None.

BitMEX does not serve it from the orderbook endpoint.

> how can I get timestamp?

Call `milliseconds()` after calling the `fetch_order_book()`:

```Python
import ccxt
symbol = 'BTC/USD'
bitmex = ccxt.bitmex()
orderbook = bitmex.fetch_order_book(symbol) 
timestamp = bitmex.milliseconds ()
```

Hope this answers your question. Let us know if not.

**Comment by liuhuanshuo** [comment]
> > timestamp is None.
> 
> BitMEX does not serve it from the orderbook endpoint.
> 
> > how can I get timestamp?
> 
> Call `milliseconds()` after calling the `fetch_order_book()`:
> 
> ```python
> import ccxt
> symbol = 'BTC/USD'
> bitmex = ccxt.bitmex()
> orderbook = bitmex.fetch_order_book(symbol) 
> timestamp = bitmex.milliseconds ()
> ```
> 
> Hope this answers your question. Let us know if not.

 thx!
but getting the depth data and getting the timestamp are not completed at the same time, which may cause errors....

**Comment by kroitor** [comment]
> but getting the depth data and getting the timestamp are not completed at the same time, which may cause errors....

That's right, but if the exchange in question does not report the timestamp – we can't invent it out of thin air... I guess, you should forward this question to BitMEX.

You can also access the timestamp in HTTP response headers as described in this post: https://github.com/ccxt/ccxt/issues/2593

Hope this helps.
