### ISSUE TITLE
New Exchange - Globitex

### ISSUE THREAD

**Issue by Vitazema** [ccxt/ccxt#4476]
Hi! There is very interesting exchange market called Globitex, but it missed in ccxt. Would it possible to add it support? 
The thing is there are not so many futures exchange markets that high in quality.
The benefit is that Globitex supports wide amount of trading tools and perform good connection stability, as compared with ex. Bitmex.

WEB: https://globitex.com/
API: https://globitex.com/api/

**Comment by frosty00** [comment]
dead exchange
