### ISSUE TITLE
MarketSellOrder Unified label:"code proposal"

### ISSUE THREAD

**Issue by Seigneur774** [ccxt/ccxt#4477]
Hello, would it be interesting to add this snippet to create a unified marketSellOrder:
`def MarketSell(exchange, symbol, amount):
    orderBook = exchange.fetch_l2_order_book(symbol)
    i=0
    while amount !=0:
        i+=1
        if orderbook['bids'][i][1]>amount:
            #Limit_order (    price=orderbook['bids'][i][0],    amount_of-this-order=orderbook['bids'][i][1])
            amount-=orderbook['bids'][i][1]
        else:
            #Limit_order (    price=orderbook['bids'][i][0],    amount_of-this-order=amount)
            amount=0`

If there is any problem with it tell, it's my first time that I do this type of proposal

- Programming Language version: python 3.7
- Exchange: All

**Comment by kroitor** [comment]
> If there is any problem with it tell, it's my first time that I do this type of proposal

Sorry, but we have already unified `createMarketSellOrder` in cases where the exchange in question does support it. If you emulate a market order with `fetchOrderBook` + `createLimitOrder` – this is not a market order anymore, unfortunately. 

Please, read more about it here:

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata
- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

Hope this answers your questions. Feel free to reopen it or just ask further questions if any. Will be happy to see contributions from you in the future!
