### ISSUE TITLE
Reduce only bitfinex

### ISSUE THREAD

**Issue by odeelol** [ccxt/ccxt#4479]
How in the sweet name of fuck do i make reduce only on bitfinex

i used the create order shell from my bitmex version 

                finex.create_order(symbol=symbol3, type='trailing-stop', side='buy',price=abs(ticker['last']-price), amount=value,
                                   params={
                                    'type': 'trailing-stop',
                                    'execInst': 'ReduceOnly'
                                    })

but any permuation of execinst doesnt work, and none of my stops or trail types will reduce only

**Comment by kroitor** [comment]
> 'execInst': 'ReduceOnly'

There's no execInst argument for Bitfinex endpoint for placing orders... I recommend to read the entire Manual from top to bottom in order to be able to use this library.

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://docs.bitfinex.com/v1/reference#rest-auth-new-order

Hope this answers your question.

**Comment by odeelol** [comment]
Thanks for your response. 

yea i understand theres no arguement for it. Ive been using this api for over a  year now.
I cant find anything pertaining to this in either the bitfinex API docs, or the CCXT manual or even the bitfinex php https://github.com/ccxt/ccxt/blob/master/python/ccxt/bitfinex.py#L646

so im reaching out here now

**Comment by kroitor** [comment]
> I cant find anything pertaining to this in either the bitfinex API docs, or the CCXT manual

Well, if you can't find the term you're searching for anywhere in the Bitfinex docs, and there's no word about it anywhere there – then there's several possibilities:
- either Bitfinex does not have that functionality at all (why do you think they have it in the first place?)
- or they have it but they call it differently
- or they have an alternative that works differently and is named differently

**Comment by odeelol** [comment]
Thank you for  your response.

I assume they have the functionality because their web client does as does every other exchange on the planet and every other api covered by CCXT 

I've tried all the parameters i can see to no avail, i was hoping that someone using this library has conquered the same problem either by finding what i cant or a workaround.

Could you at least leave this topic open? my question is far from answered

**Comment by kroitor** [comment]
> Could you at least leave this topic open? my question is far from answered

You're free to reopen it when needed )

> I assume they have the functionality because their web client does as does every other exchange on the planet and every other api covered by CCXT

How does their web client call that functionality ? Is there a mention of `reduceOnly` in the GUI in their web client? ;)

**Comment by frosty00** [comment]
https://github.com/bitfinexcom/bitfinex-api-node

does it work in this library?

**Comment by odeelol** [comment]
thanks for the response!

looks like it does, using js though. have any solutions in python?
im trying to find a working web socket api as it appears you need to use their version 2 api for this

> https://github.com/bitfinexcom/bitfinex-api-node
> 
> does it work in this library?

**Comment by kroitor** [comment]
Ok, found the details here:

- https://support.bitfinex.com/hc/en-us/articles/360006390533--Reduce-Only-Order
- https://support.bitfinex.com/hc/en-us/articles/115003451049-Bitfinex-Order-Types

![screen-shot-2019-01-16-at-08 02 14](https://user-images.githubusercontent.com/1294454/51227455-7d888100-1965-11e9-9b68-c7228335d47d.jpg)

Indeed it's v2-only, and in their v2 API only accepts orders by WS... Unfortunately, we don't support WS yet, more about it here: #56
