### ISSUE TITLE
how to get the market depth data of huobi???

### ISSUE THREAD

**Issue by liuhuanshuo** [ccxt/ccxt#4480]
- OS:macos
- Programming Language version:python 
- CCXT version:latest

my code:

huobipro = ccxt.huobipro()
orderbook = huobipro.fetch_order_book('BTC')

but it doesn't work. I need ask1,ask2..........

**Comment by kroitor** [comment]
Let us know if this does not answer your question: https://github.com/ccxt/ccxt/wiki/Manual#order-book. I'd recommend to read the entire Manual from top to bottom, it will save you a lot of time. )

```Python
import ccxt
from pprint import pprint
exchange = ccxt.huobipro({
    'enableRateLimit': True,  # required by the Manual
})
symbol = 'ETH/BTC'
orderbook = exchange.fetch_order_book(symbol)
pprint(orderbook)
```

Hope this answers your question.

**Comment by liuhuanshuo** [comment]
> Let us know if this does not answer your question: https://github.com/ccxt/ccxt/wiki/Manual#order-book. I'd recommend to read the entire Manual from top to bottom, it will save you a lot of time. )
> 
> ```python
> import ccxt
> from pprint import pprint
> exchange = ccxt.huobipro({
>     'enableRateLimit': True,  # required by the Manual
> })
> symbol = 'ETH/BTC'
> orderbook = exchange.fetch_order_book(symbol)
> pprint(orderbook)
> ```
> 
> Hope this answers your question.

ths！
but i need the quarterly contract data for bitcoin depth data
what's the symbol?

**Comment by kroitor** [comment]
> BTC_CQ doesn't work

Huobipro doesn't have that symbol... Have you read the Manual on how to work with symbols ?

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

**Comment by daniaoren** [comment]
> 
> 
>     * https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

I've read the doc. However huobi is a bit different on the contract symbol. They have a different API for getting contract. Not sure if anyone has successfully get contract ticker on huobipro
