### ISSUE TITLE
Issue in kraken.php

### ISSUE THREAD

**Issue by ceaser1996** [ccxt/ccxt#4483]
Whenever I am trying to fetch balance using ccxt is showing an error 
Undefined Offset 1
`[stacktrace] #0 /var/www/html/cryptosig/vendor/ccxt/ccxt/php/kraken.php(219): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined offse...', '/var/www/html/c...', 219, Array) #1 /var/www/html/cryptosig/vendor/ccxt/ccxt/php/kraken.php(240): ccxt\\kraken->fetch_min_order_sizes() `
I fixed the same by replacing  $ul = $parts[1] to $ul = $parts[0];
*Now its shoing me the balance .

**Here is the previous code 
` public function fetch_min_order_sizes () {
        $html = $this->zendeskGet205893708WhatIsTheMinimumOrderSize ();
        $parts = explode ('ul>', $html);
        $ul = $parts[1];// changed to $parts[0]
        $listItems = explode ('</li', $ul);
        $result = array ();
        $separator = '):' . ' ';
        for ($l = 0; $l < count ($listItems); $l++) {
            $listItem = $listItems[$l];
            $chunks = explode ($separator, $listItem);
            $numChunks = is_array ($chunks) ? count ($chunks) : 0;
            if ($numChunks > 1) {
                $limit = floatval ($chunks[1]);
                $name = $chunks[0];
                $chunks = explode ('(', $name);
                $currency = $chunks[1];
                $result[$currency] = $limit;
            }
        }
        return $result;
    }`

**Please fix this issue as soon as possible.

- OS: Ubuntu
- Programming Language version:php 7.2
- CCXT version: Latest
- Exchange: Kraken
- Method: private

**Comment by kroitor** [comment]
@ceaser1996 looks like your version of CCXT is very old, which number is it?

**Comment by kroitor** [comment]
This issue was fixed in September, so, if you update to most recent version there should be no problem with it. As you know, this is still a work in progress, so we add updates on regular basis, and we ask users to update frequently. Let us know if you still have difficulties with after upgrading to 1.18.120. Hope this helps.

Duplicate: https://github.com/ccxt/ccxt/issues/3797
