### ISSUE TITLE
[itbit] new feature available

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#4485]
itbit have added cryptocurrency deposits to their rest api: https://api.itbit.com/docs#trading-new-cryptocurrency-deposit-post

I'll try and get it implemented...

**Comment by npomfret** [comment]
Actually, it doesn't really fit into this api - it's really for creating new addresses

**Comment by kroitor** [comment]
> Actually, it doesn't really fit into this api - it's really for creating new addresses

In fact, it does fit into this API – we have `createDepositAddress` and `fetchDepositAddress` as well ;)

- https://github.com/ccxt/ccxt/wiki/Manual#deposit

So, thx for letting us know, we will unify those endpoints anyway.
