### ISSUE TITLE
Bitstamp returns FetchError for loadMarkets - HPE_INVALID_HEADER_TOKEN

### ISSUE THREAD

**Issue by tommuhm** [ccxt/ccxt#4486]
Update:
Bitstamp returns `FetchError` for `loadMarkets` (https://www.bitstamp.net/api/v2/trading-pairs-info/) 

Exception:
message: request to https://www.bitstamp.net/api/v2/trading-pairs-info/ failed, reason: Parse Error
code/errno: HPE_INVALID_HEADER_TOKEN
Stack:
```
FetchError: request to https://www.bitstamp.net/api/v2/trading-pairs-info/ failed, reason: Parse Error
    at ClientRequest.<anonymous> (/.../node_modules/fetch-ponyfill/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:188:13)
    at TLSSocket.socketOnData (_http_client.js:455:9)
    at TLSSocket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:145:17)
```

The request works fine in the browser and other exchanges I currently use are also working fine: binance, bitfinex, kraken, coinbasepro

OS: manjaro
node-version: v11.6.0
ccxt-version: 1.18.120
exchange: bitstamp
method: loadMarkets

**Comment by kroitor** [comment]
That's not an issue with ccxt but more like an issue with your version of node fetch or an issue with SSL compatibility.

- https://stackoverflow.com/questions/36628420/nodejs-request-hpe-invalid-header-token
- https://github.com/node-red/node-red/issues/974#issuecomment-300595000
- https://www.google.com/search?q=HPE_INVALID_HEADER_TOKEN

Hope this answers the question, let us know if not.

**Comment by tommuhm** [comment]
Thanks for the infos!, Unfortunately none of the mentioned solutions worked and I went deep into the node lib itself while debugging. 

But now everything works again!, seems that Bitstamp fixed the Headers on their side.
