### ISSUE TITLE
exchange.market() recently updated? Stopped working as usual

### ISSUE THREAD

**Issue by Fcl69** [ccxt/ccxt#449]
So recently exch.market() started to return a different value, which I assume was a part of the bugfix. Since it works as expected now. But I missed that bugfix, which made my code working incorrectly. So I guess no question here, just a memo, that output has changed.

```
import ccxt
exch = ccxt.bitfinex()
exch.market('BTC/USD')
```

**Comment by Fcl69** [comment]
Code:

import ccxt 

```
exch = ccxt.bitfinex()
orders = exch.fetch_order_book(exch.market('BTC/USD'))
print(orders)
```

Result:

> Traceback (most recent call last):
>   File "ob_small.py", line 4, in <module>
>     orders = exch.fetch_order_book(exch.market('BTC/USD'))
>   File "/home/fcl/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 800, in market
>     raise ExchangeError(self.id + ' markets not loaded')
> ccxt.base.errors.ExchangeError: bitfinex markets not loaded

**Comment by Fcl69** [comment]
So this one would work:

```
import ccxt
exch = ccxt.bitfinex()
orders = exch.fetch_order_book('BTC/USD')
print(orders)
```

I wonder if this fix was a part of a bug fix or anything

**Comment by kroitor** [comment]
Thank you for pointing that out!
