### ISSUE TITLE
ZB changed their public API base URL (again!)

### ISSUE THREAD

**Issue by WoK-E** [ccxt/ccxt#4493]
- OS: -
- Programming Language version: -
- CCXT version: 1.18.121
- Exchange: ZB
- Method: -

ZB have changed the access URL for the public endpoints.  Pls. see https://www.zb.com/i/developer
The new base API URL is http://api.zb.cn/v1/data
The private base URL has not changed

**Comment by kroitor** [comment]
That's strange, but the old URL still does work for me. Can you tell the source of the info plz? Was there an announcement somewhere?

**Comment by WoK-E** [comment]
I did not see any announcement. I just had an error in my logs and researched it.
The old URL does not work for me. For example, http://api.zb.cn/data/allTicker returns

welcome!
ZB API INTERFACE

**Comment by kroitor** [comment]
@WoK-E 

> For example, http://api.zb.cn/data/allTicker returns
> welcome!
> ZB API INTERFACE

Yeah, but... we don't really use that URL...

If you do a simple check – you will see that it calls for `http://api.zb.cn/data/v1/allTicker` (this one works in current version 1.18.122).

**Comment by kroitor** [comment]
@WoK-E 

```Python
import ccxt
exchange = ccxt.zb({'enableRateLimit': True})
exchange.load_markets()
exchange.verbose = True
tickers = exchange.fetch_tickers()
```

**Comment by kroitor** [comment]
@WoK-E are you sure that the issue you've encountered in your logs is necessarily related to the public API base URL ? That could be a temporary availability issue which is common to most of exchanges... Does fetch_tickers actually work on your side at the moment?

**Comment by WoK-E** [comment]
@kroitor I'm not sure, but as soon as I changed the public API base URL, I stopped having errors in my logs.
I'll revert to the old base URL, check, and report back

**Comment by WoK-E** [comment]
Reverted back to public API base URL (as is in 1.18.121), and everything worked find, i.e. no errors.
I was having errors for more than a day, hence my report.

I think it's safe to close the issue - no changes necessary.
