### ISSUE TITLE
how to get okex depth data?

### ISSUE THREAD

**Issue by liuhuanshuo** [ccxt/ccxt#4497]
- OS:macos
- Programming Language version:py3.6

I want this week ask1.. bid1.... from okex.
please help me.

**Comment by kroitor** [comment]
> how to get okex depth data? #4497

This is documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#market-depth

I'd recommend to read the entire Manual from top to bottom in order to be able to work with this library efficiently.
