### ISSUE TITLE
bsv_cad pair is missing in Quadrigacx

### ISSUE THREAD

**Issue by jshoude** [ccxt/ccxt#4501]
as seen on https://www.quadrigacx.com/api_info: 

The current order books on QuadrigaCX are:

btc_cad
btc_usd
eth_cad
eth_btc
ltc_cad
ltc_btc
bch_cad
bch_btc
*bsv_cad*
btg_cad
btg_btc

thanks!
also, is there a way to add/override the market list?

**Comment by kroitor** [comment]
Thx for reporting! Added `BSV/CAD` in 1.18.133. Unfortunately, they don't serve a list of markets from their API, so it has to be hardcoded for now... We might add scraping the list from their website later.

Those are defined here: - https://github.com/ccxt/ccxt/blob/master/js/quadrigacx.js#L69

> also, is there a way to add/override the market list?

Yes, those markets are stored in exchange properties described here:

- https://github.com/ccxt/ccxt/wiki/Manual#markets
- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

You can add a new market to `quadrigacx` without having to update the library, by doing the following upon instantiation:

```JavaScript
const exchange = new ccxt.quadrigacx ({
    'markets': {
        'BSV/CAD': { 'id': 'bsv_cad', 'symbol': 'BSV/CAD', 'base': 'BSV', 'quote': 'CAD', 'baseId': 'bsv', 'quoteId': 'cad', 'maker': 0.005, 'taker': 0.005 },
    },
})
```

Let us know if that does not answer your question.
