### ISSUE TITLE
Properties with empty values, like exchange.orderbooks, exchange.balance

### ISSUE THREAD

**Issue by vladiscripts** [ccxt/ccxt#4502]
Are the properties with empty values (like `exchange.orderbooks`, `exchange.balance`, and such in `exchange .__ init__`) occupied for future use? Is it planned that some CCXT methods will automatically write data to them?

Or are they open to users for use as a data containers? Like:
```
exch.orderbooks = exch.fetch_order_books()
exch.balance = exch.fetch_balance()
```
If so, could you add comments about this to the code for these properties.

**Comment by kroitor** [comment]
> Are the properties with empty values (like exchange.orderbooks, exchange.balance, and such in exchange .__ init__) occupied for future use? 

Yep, however, in some exchange implementations we already do use some of them, for example, we might use `orders` for caching as described here: https://github.com/ccxt/ccxt/wiki/Manual#orders-cache

> Is it planned that some CCXT methods will automatically write data to them?

Yes, exactly.

> Or are they open to users for use as a data containers?

Currently, those are open, for example, if the user wants to examine the order cache, but still, those are reserved for the purposes of the library, so, you don't really want the interference.

> If so, could you add comments about this to the code for these properties.

Yep, will do. Thx!
