### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by 317459062** [ccxt/ccxt#4508]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:windows10
- Programming Language version:
- CCXT version:1.18.76
- Exchange:binance
- Method:exchange.fetch_balance()

我用shadowsockes设置了全局变量，但是出现了以下错误

import ccxt
import os
from binance import config

exchange=ccxt.binance({'apiKey': config.accessKey, 'secret': config.secretkey})
print(exchange.fetch_ticker(symbol='RVN/BTC'))
def ticker(symbol='RVN/BTC'):
    tickers=exchange.fetch_ticker(symbol=symbol)
    return tickers
def place(side,price,amout,symbol,type):
    '''

    :param side: buy sell
    :param price: 价格
    :param amout: 数量
    :param symbol: 交易对
    :param type: limit market
    :return:
    '''
    return exchange.create_order(side=side,price=price,amount=amout,type=type,symbol=symbol)
def cancel(orderId,symbol):
    '''

    :param orderId: 订单id
    :param symbol: 交易对
    :return:
    '''
    return exchange.cancel_order(id=orderId,symbol=symbol)
def orderInfo(symbol):
    return exchange.fetch_open_orders(symbol=symbol)
def account():
    return exchange.fetch_balance()

print(account())

错误：
{'symbol': 'RVN/BTC', 'timestamp': 1547776175341, 'datetime': '2019-01-18T01:49:35.341Z', 'high': 3.58e-06, 'low': 3.34e-06, 'bid': 3.48e-06, 'bidVolume': 18164.0, 'ask': 3.49e-06, 'askVolume': 8143.0, 'vwap': 3.45e-06, 'open': 3.38e-06, 'close': 3.48e-06, 'last': 3.48e-06, 'previousClose': 3.37e-06, 'change': 1e-07, 'percentage': 2.959, 'average': None, 'baseVolume': 119250323.0, 'quoteVolume': 411.75757861, 'info': {'symbol': 'RVNBTC', 'priceChange': '0.00000010', 'priceChangePercent': '2.959', 'weightedAvgPrice': '0.00000345', 'prevClosePrice': '0.00000337', 'lastPrice': '0.00000348', 'lastQty': '16676.00000000', 'bidPrice': '0.00000348', 'bidQty': '18164.00000000', 'askPrice': '0.00000349', 'askQty': '8143.00000000', 'openPrice': '0.00000338', 'highPrice': '0.00000358', 'lowPrice': '0.00000334', 'volume': '119250323.00000000', 'quoteVolume': '411.75757861', 'openTime': 1547689775341, 'closeTime': 1547776175341, 'firstId': 2745215, 'lastId': 2754146, 'count': 8932}}
Traceback (most recent call last):
  File "D:\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 442, in fetch
    response.raise_for_status()
  File "D:\Python\Python36\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/account?timestamp=1547776186175&recvWindow=5000&signature=26814a44f8a6b8843b169805c5d1f7e55cec8424372664be531642d4cbb448fd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/workfile/quant/binance/util.py", line 34, in <module>
    print(account())
  File "E:/workfile/quant/binance/util.py", line 32, in account
    return exchange.fetch_balance()
  File "D:\Python\Python36\lib\site-packages\ccxt\binance.py", line 410, in fetch_balance
    response = self.privateGetAccount(params)
  File "D:\Python\Python36\lib\site-packages\ccxt\binance.py", line 1129, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "D:\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 363, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "D:\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 454, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "D:\Python\Python36\lib\site-packages\ccxt\binance.py", line 1122, in handle_errors
    raise exceptions[error](self.id + ' ' + body)
ccxt.base.errors.InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}

**Comment by kroitor** [comment]
Duplicate:

- https://github.com/ccxt/ccxt/issues/850
- https://github.com/ccxt/ccxt/issues/773
- https://github.com/ccxt/ccxt/wiki/Manual#error-handling
