### ISSUE TITLE
Allcoin does not have market symbol ETH/BTC

### ISSUE THREAD

**Issue by mazertwo** [ccxt/ccxt#451]
With ccxt version 1.9.346 i get error "ccxt.base.errors.ExchangeError: allcoin does not have market symbol ETH/BTC"

Same for ZEC/BTC pair.

But if i install older version (1.9.230), all fine.

**Comment by kroitor** [comment]
@mazertwo thx! I'll take a look into it and will get back to you asap.

**Comment by kroitor** [comment]
This was fixed in 1.9.349. It was a minor bug introduced by the recent source split. Thx for reporting! Respect!

**Comment by mazertwo** [comment]
Last version work correctly. Thank you! Brilliance work and support!
