### ISSUE TITLE
KuCoin new API / Platform 2.0 upgrade

### ISSUE THREAD

**Issue by wybitnygracz** [ccxt/ccxt#4514]
"Dear KuCoin User,

 
On January 21, 2019, at approximately 08:00 AM UTC+8, KuCoin will be performing a system upgrade for Platform 2.0. The new Platform 2.0 will support more order types, while providing more efficient, stable brand new APIs trading, along with other new services. 
 ... After the upgrade of platform 2.0 is done in near future, the **old version of the API will no longer be available** "

Do you plan make integration with new kucoin api?

**Comment by calbertuk** [comment]
lol at Kucoin giving people four days notice to upgrade all of their code to the new API without even providing SDKs.

**Comment by kroitor** [comment]
```
Important Update: KuCoin Postpones the Upgrade to Platform 2.0
 
Dear KuCoin User,
 
We have received a lot of feedbacks from our API community since last notification was released about the new API upgrade. After reviewing all the feedbacks, we have decided to postpone Platform 2.0 launch time for at least 10 days in order to give our API traders more time to set up their programs with KuCoin 2.0 API. The new launch date will be some day after 30th Jan(UTC +8). We will be notifying you three days before the launch date. Meanwhile, KuCoin will be developing official SDKs and helping communities to develop 3rd party SDKs. 
```

**Comment by calbertuk** [comment]
Kucoin has also said they would reach out to you to have the wrapper ready by the time 2.0 launches which is good news.

**Comment by kroitor** [comment]
This is the official update: https://github.com/ccxt/ccxt/issues/4579
