### ISSUE TITLE
New Exchange - TOKOK

### ISSUE THREAD

**Issue by huoHUO520** [ccxt/ccxt#4518]
Hi! There is very interesting exchange market called TOKOK, but it missed in ccxt. Would it possible to add it support?
It provides a place to trade and liquidity for the roadmap clarity technology, and a great trading scene for a large number of digital currency enthusiasts.

WEB: https://www.tokok.com/
API: https://www.tokok.com/api/tokok_api_cn.pdf

**Comment by joao-jeronimo** [comment]
Hello.
Is there a bounty for implementing this?
Thank you.

**Comment by ttodua** [comment]
Exchange seems [to become unavailable](https://help.tokok.io/hc/en-us/articles/7732749230105)
