### ISSUE TITLE
Bitstamp Nonce Error

### ISSUE THREAD

**Issue by kostanjsek** [ccxt/ccxt#4520]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: UBUNTU 18.04.1 LTS
- Programming Language version: Python 3.6
- CCXT version: 1.17.480
- Exchange: Bitstamp
- Method: fetch_balance, fetchOrder

Erased all API keys on Bitstamp and created new. I only use them on this computer within this app. 
I read all other posts regarding Nonce error, tried with setting enableRateLimit to True (verbose output below) but am unable to figure out why the error is still there, even if Nonce number seams to be OK (itterating) as you can see in the debug output... (I can send you also the code...)

Response: GET https://www.bitstamp.net/api/v2/trading-pairs-info/ 200 {'Access-Control-Allow-Headers': 'x-requested-with, Content-Type, origin, accept, cache-control',
'Access-Control-Allow-Methods': 'POST, GET', 'Access-Control-Allow-Origin': '*', 'Cache-Control': 'max-age=0', 'Content-Language': 'en', 'Content-Type': 'application/js
on', 'Date': 'Mon, 21 Jan 2019 13:34:28 GMT', 'Expires': 'Mon, 21 Jan 2019 13:34:28 GMT', 'Last-Modified': 'Mon, 21 Jan 2019 13:34:28 GMT', 'Server': 'Apache', 'Strict-
Transport-Security': 'max-age=63072000; includeSubDomains', 'Vary': 'Authorization,Accept-Language', 'X-Frame-Options': 'SAMEORIGIN', 'transfer-encoding': 'chunked', 'C
onnection': 'keep-alive', 'Set-Cookie': 'visid_incap_99025=L+l/Qk87T16Qp5PwmwEoPmPKRVwAAAAAQUIPAAAAAADyKfrGyvwt9tyRpQcQvbTR; expires=Tue, 21 Jan 2020 11:13:50 GMT; path
=/; Domain=.bitstamp.net, nlbi_99025=FviqdZSSM0kFG/rL8F1n9AAAAAAnoD/Zaq35LLMu5rDC2NA6; path=/; Domain=.bitstamp.net, incap_ses_408_99025=YosJWFMBrzNXjMSnTYOpBWPKRVwAAAA
AD9jJaob9EUd5pT8ZeivYBg==; path=/; Domain=.bitstamp.net, ___utmvmXvumyLc=lPajJidVMaW; path=/; Max-Age=900, ___utmvaXvumyLc=MFL\x01ohzX; path=/; Max-Age=900, ___utmvbXvu
myLc=EZA\r\n    XAkOwald: btG; path=/; Max-Age=900', 'X-Iinfo': '6-152919912-152910720 PNNN RT(1548077667687 69) q(0 0 0 -1) r(0 0) U2', 'X-CDN': 'Incapsula', 'Content-
Encoding': 'gzip'} [{"base_decimals": 8, "minimum_order": "5.0 USD", "name": "LTC/USD", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "ltcusd", "descriptio
n": "Litecoin / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "5.0 USD", "name": "ETH/USD", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "ethusd", "description": "Ether / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "5.0 EUR", "name": "XRP/EUR", "counter_decimals": 5, "trading": "Enabled", "url_symbol": "xrpeur", "description": "XRP / Euro"}, {"base_decimals": 8, "minimum_order": "5.0 USD", "name": "BCH/USD", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "bchusd", "description": "Bitcoin Cash / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "5.0 EUR", "name": "BCH/EUR", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "bcheur", "description": "Bitcoin Cash / Euro"}, {"base_decimals": 8, "minimum_order": "5.0 EUR", "name": "BTC/EUR", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "btceur", "description": "Bitcoin / Euro"}, {"base_decimals": 8, "minimum_order": "0.001 BTC", "name": "XRP/BTC", "counter_decimals": 8, "trading": "Enabled", "url_symbol": "xrpbtc", "description": "XRP / Bitcoin"}, {"base_decimals": 5, "minimum_order": "5.0 USD", "name": "EUR/USD", "counter_decimals": 5, "trading": "Enabled", "url_symbol": "eurusd", "description": "Euro / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "0.001 BTC", "name": "BCH/BTC", "counter_decimals": 8, "trading": "Enabled", "url_symbol": "bchbtc", "description": "Bitcoin Cash / Bitcoin"}, {"base_decimals": 8, "minimum_order": "5.0 EUR", "name": "LTC/EUR", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "ltceur", "description": "Litecoin / Euro"}, {"base_decimals": 8, "minimum_order": "5.0 USD", "name": "BTC/USD", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "btcusd", "description": "Bitcoin / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "0.001 BTC", "name": "LTC/BTC", "counter_decimals": 8, "trading": "Enabled", "url_symbol": "ltcbtc", "description": "Litecoin / Bitcoin"}, {"base_decimals": 8, "minimum_order": "5.0 USD", "name": "XRP/USD", "counter_decimals": 5, "trading": "Enabled", "url_symbol": "xrpusd", "description": "XRP / U.S. dollar"}, {"base_decimals": 8, "minimum_order": "0.001 BTC", "name": "ETH/BTC", "counter_decimals": 8, "trading": "Enabled", "url_symbol": "ethbtc", "description": "Ether / Bitcoin"}, {"base_decimals": 8, "minimum_order": "5.0 EUR", "name": "ETH/EUR", "counter_decimals": 2, "trading": "Enabled", "url_symbol": "etheur", "description": "Ether / Euro"}]

Request: POST https://www.bitstamp.net/api/v2/balance/ {'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.21.0', 'Accept-Encoding': 'gzip, deflate'} key=123&signature=123&nonce=1548077668

Response: POST https://www.bitstamp.net/api/v2/balance/ 403 {'Access-Control-Allow-Headers': 'x-requested-with, Content-Type, origin, accept, cache-control', 'Access-Control-Allow-Methods': 'POST, GET', 'Access-Control-Allow-Origin': '*', 'Cache-Control': 'max-age=0', 'Content-Language': 'en', 'Content-Type': 'application/json', 'Date': 'Mon, 21 Jan 2019 13:34:28 GMT', 'Expires': 'Mon, 21 Jan 2019 13:34:28 GMT', 'Last-Modified': 'Mon, 21 Jan 2019 13:34:28 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains', 'Vary': 'Authorization,Accept-Language', 'X-Frame-Options': 'SAMEORIGIN', 'transfer-encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': 'visid_incap_99025=Xd1JKn9wQdylN5npQ9dUAmPKRVwAAAAAQUIPAAAAAACVKAOlOkRUTzW65ze0Y4rg; expires=Tue, 21 Jan 2020 11:13:50 GMT; path=/; Domain=.bitstamp.net, incap_ses_408_99025=uC/ED5wBBBRtjMSnTYOpBWPKRVwAAAAAxeuA2eLE7y0QZEsAYhp5+A==; path=/; Domain=.bitstamp.net, ___utmvmXvumyLc=hzzogMUaocL; path=/; Max-Age=900, ___utmvaXvumyLc=GDr\x01HeBq; path=/; Max-Age=900, ___utmvbXvumyLc=SZg\r\n    XBUOwalv: tti; path=/; Max-Age=900', 'X-Iinfo': '6-152919912-152910720 SNNN RT(1548077667687 107) q(0 0 0 -1) r(1 1) U6', 'X-CDN': 'Incapsula', 'Content-Encoding': 'gzip'} {"status": "error", "reason": "Invalid nonce", "code": "API0004"}

Request: POST https://www.bitstamp.net/api/v2/order_status/ {'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.21.0', 'Accept-Encoding': 'gzip, deflate'} key=123&signature=123&nonce=1548077670&id=2765602167

Response: POST https://www.bitstamp.net/api/v2/order_status/ 200 {'Access-Control-Allow-Headers': 'x-requested-with, Content-Type, origin, accept, cache-control', 'Access-Control-Allow-Methods': 'POST, GET', 'Access-Control-Allow-Origin': '*', 'Cache-Control': 'max-age=0', 'Content-Language': 'en', 'Content-Type': 'application/json', 'Date': 'Mon, 21 Jan 2019 13:34:30 GMT', 'Expires': 'Mon, 21 Jan 2019 13:34:30 GMT', 'Last-Modified': 'Mon, 21 Jan 2019 13:34:30 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains', 'Vary': 'Authorization,Accept-Language', 'X-Frame-Options': 'SAMEORIGIN', 'transfer-encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': 'visid_incap_99025=zqCtJq6STjKcMf17G7nvumXKRVwAAAAAQUIPAAAAAAAXEa49KBwGw52a+6QoTRET; expires=Tue, 21 Jan 2020 11:13:50 GMT; path=/; Domain=.bitstamp.net, incap_ses_408_99025=539GDura03ooj8SnTYOpBWXKRVwAAAAAcOI+SFMMCNliWKV96yI2gw==; path=/; Domain=.bitstamp.net, ___utmvmXvumyLc=QEQEOFteUmx; path=/; Max-Age=900, ___utmvaXvumyLc=Huy\x01zoZY; path=/; Max-Age=900, ___utmvbXvumyLc=gZI\r\n    XVUOnalB: Ztl; path=/; Max-Age=900', 'X-Iinfo': '2-172647250-172644299 SNNN RT(1548077595965 73351) q(0 0 0 -1) r(0 0) U6', 'X-CDN': 'Incapsula', 'Content-Encoding': 'gzip'} {"status": "Open", "id": 2765602167, "transactions": []}

Response: POST https://www.bitstamp.net/api/v2/cancel_order/ 403 {'Access-Control-Allow-Headers': 'x-requested-with, Content-Type, origin, accept, cache-control', 'Access-Control-Allow-Methods': 'POST, GET', 'Access-Control-Allow-Origin': '*', 'Cache-Control': 'max-age=0', 'Content-Language': 'en', 'Content-Type': 'application/json', 'Date': 'Mon, 21 Jan 2019 13:34:30 GMT', 'Expires': 'Mon, 21 Jan 2019 13:34:30 GMT', 'Last-Modified': 'Mon, 21 Jan 2019 13:34:30 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains', 'Vary': 'Authorization,Accept-Language', 'X-Frame-Options': 'SAMEORIGIN', 'transfer-encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': 'visid_incap_99025=S1aK29cdS4mnlv3x46hW/WXKRVwAAAAAQUIPAAAAAADv1T/5jfI3S6nvmd/gb8vL; expires=Tue, 21 Jan 2020 11:13:50 GMT; path=/; Domain=.bitstamp.net, incap_ses_408_99025=5xrndQJKvBo8j8SnTYOpBWXKRVwAAAAAEJvnRIzbLrxRzED0bf8b4w==; path=/; Domain=.bitstamp.net, ___utmvmXvumyLc=XfthNAseQmf; path=/; Max-Age=900, ___utmvaXvumyLc=LCL\x01UaYx; path=/; Max-Age=900, ___utmvbXvumyLc=jZd\r\n    XxEOgalI: xtd; path=/; Max-Age=900', 'X-Iinfo': '2-172647250-172644299 SNNN RT(1548077595965 73398) q(0 0 0 -1) r(0 0) U6', 'X-CDN': 'Incapsula', 'Content-Encoding': 'gzip'} {"status": "error", "reason": "Invalid nonce", "code": "API0004"}
Error, in selling process, could not cancell order to get new bid: bitstamp {"status": "error", "reason": "Invalid nonce", "code": "API0004"} W

**Comment by kostanjsek** [comment]
Igor thank you for your quick reply.
I checked my code and it was a typo with enableRatelimit instead of
enableRateLimit.

There is no Nonce error anymore.

Thank you for your help.

Janez

**Comment by kroitor** [comment]
@kostanjsek thx for reporting back! )
