### ISSUE TITLE
hitbtc decimal

### ISSUE THREAD

**Issue by hbus12** [ccxt/ccxt#4521]
- Programming Language version: PHP 7
- CCXT version: 1.18.131
- Exchange: HitBTC v2
- Method: create_market_order()

Hi,

I am testing a bit with CCXT, but got an issue with placing a marketorder on the hitbtc2 API. When trying to do the order:

ccxt\hitbtc2->create_order('DCN/ETH', 'market', 'buy', 79365.07936508, NULL, Array) 

I am getting a precision error. I am aware of the precision problem at hitbtc, where it is impossible to buy this amount, but I thought ccxt would round it for me.

I am getting this error when trying to buy the DCN/ETH:
Fatal error: Uncaught Error: Call to undefined function ccxt\decimal_to_precision() 
ccxt\Exchange->amount_to_precision('DCN/ETH', 79365.07936508) 

Looks like something is missing or not right there. Anyone know a fix for this? I can manually round the number of DCN, but I'm affraid is it a bug that excists at multiple currencies.

**Comment by kroitor** [comment]
> I thought ccxt would round it for me.

That's right, it would, however, it's not rounding, but truncation, to be precise: `79365.07936508` will be truncated to `70000`.

> Looks like something is missing or not right there. Anyone know a fix for this?

It was a minor leftover bug, indeed. I've just uploaded a fix for it and tested it on my side, so it it should work normally as soon as the build of the new version 1.18.142 arrives in 5-10 minutes. If you upgrade your version and try again after that – it should be fine. Let us know if you still have difficulties with it after the update. Thx for reporting!

**Comment by hbus12** [comment]
Wow hero! That worked indeed, thanks!
