### ISSUE TITLE
coinfalcon ticker

### ISSUE THREAD

**Issue by hbus12** [ccxt/ccxt#4523]
- Programming Language version: PHP 7.1
- CCXT version: 1.18.142
- Exchange: coinfalcon
- Method: fetch_tickers

When doing the fetch_tickers() function, the bid/ask are empty.

**Comment by kroitor** [comment]
> When doing the fetch_tickers() function, the bid/ask are empty.

That is documented – not all of exchanges will return all the info. Most of them will return a subset of the documented fields (others will be empty, if not provided by the exchange in question). Some of them, like Coinfalcon, will provide just the bare minimum (24hr volume data). So, in general, it's normal with some exchanges, and if the exchange does not provide the data you want – we can't really invent it for you from nothing (that wouldn't be fair to you in the first place). So what you see is what you actually get from the exchange. 

Hope this answers your question, let us know if not.
