### ISSUE TITLE
TypeError: string indices must be integers in ccxt/async_support/kraken.py

### ISSUE THREAD

**Issue by twmeggs** [ccxt/ccxt#4524]
- OS: Windows
- Programming Language version: Python 3.6 under Anaconda
- CCXT version: 1.18.118
- Exchange: Kraken
- Method: fetch_order and create_order

Not sure this is an issue with ccxt at all, given it looks to be thrown as a result of a 502 Bad Gateway error.  However, I thought I'd put it up in case anyone else was experiencing the same.  

Have experienced intermittent TypeError with the above two methods against Kraken today.  Doing a little debugging myself, the response that the method is trying to use is as per the excerpt below.  From my understanding, this is an issue on the Kraken side (?) and it would be best to error-handle in my code appropriately?

Thanks

<head>
<title>api.kraken.com | 502: Bad gateway</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>
</head>
<body>
<div id="cf-wrapper">
<div id="cf-error-details" class="cf-error-details-wrapper">
<div class="cf-wrapper cf-error-overview">
<h1>
<span class="cf-error-type">Error</span>
<span class="cf-error-code">502</span>
<small class="heading-ray-id">Ray ID: 49d38f21ca141fb2 &bull; 2019-01-22 16:57:22 UTC</small>
</h1>
<h2 class="cf-subheadline">Bad gateway</h2>
</div>
<div class="cf-section cf-highlight cf-status-display">
<div class="cf-wrapper">
<div class="cf-columns cols-3">
<div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status ">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-browser"></i>
<i class="cf-icon-status cf-icon-ok"></i>
</div>
<span class="cf-status-desc">You</span>
<h3 class="cf-status-name">Browser</h3>
<span class="cf-status-label">Working</span>
</div>
<div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status ">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-cloud"></i>
<i class="cf-icon-status cf-icon-ok"></i>
</div>
<span class="cf-status-desc">Dallas</span>
<h3 class="cf-status-name">Cloudflare</h3>
<span class="cf-status-label">Working</span>
</div>
<div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-server"></i>
<i class="cf-icon-status cf-icon-error"></i>
</div>
<span class="cf-status-desc">api.kraken.com</span>
<h3 class="cf-status-name">Host</h3>
<span class="cf-status-label">Error</span>
</div>
</div>
</div>
</div>
<div class="cf-section cf-wrapper">
<div class="cf-columns two">
<div class="cf-column">
<h2>What happened?</h2>
<p>The web server reported a bad gateway error.</p>
</div>
<div class="cf-column">
<h2>What can I do?</h2>
<p>Please try again in a few minutes.</p>
</div>
</div>
</div>
<div class="cf-error-footer cf-wrapper">
<p>

**Comment by kroitor** [comment]
This is a duplicate issue and it has been already fixed not so long ago, so if you update to the most recent version, it should work fine. In general, because this library is still a work in progress, we are doing updates and hotfixes every day, so you should be upgrading the version first, and if that doesn't help – then search for dupes... Basically, follow the guides from here as precisely as you possibly can...

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

... and if you follow those guides precisely, you will almost certainly find the answer even before you ask the question ;)

Explained and fixed here:

- https://github.com/ccxt/ccxt/issues/4295#issuecomment-446223698
- https://github.com/ccxt/ccxt/issues/4268

**Comment by twmeggs** [comment]
Thanks - sorry

**Comment by kroitor** [comment]
@twmeggs no worries and welcome )
