### ISSUE TITLE
Issue and fix

### ISSUE THREAD

**Issue by pinpins** [ccxt/ccxt#4525]
Sorry, dont have time to make pull request

**Exchange.php**
Before
        // Special handling for negative precision
        if ($numPrecisionDigits < 0) {
            $toNearest = 10 ** abs ($numPrecisionDigits);
            if ($roundingMode === ROUND) {
                $result = (string) ($toNearest * decimal_to_precision ($x / $toNearest, $roundingMode, 0, DECIMAL_PLACES, $paddingMode));
            }
            if ($roundingMode === TRUNCATE) {
                $result = decimal_to_precision ($x - $x % $toNearest, $roundingMode, 0, DECIMAL_PLACES, $paddingMode);
            }
            return $result;
        }

After

        // Special handling for negative precision
        if ($numPrecisionDigits < 0) {
            $toNearest = 10 ** abs ($numPrecisionDigits);
            if ($roundingMode === ROUND) {
                $result = (string) ($toNearest * static::decimal_to_precision ($x / $toNearest, $roundingMode, 0, DECIMAL_PLACES, $paddingMode));
            }
            if ($roundingMode === TRUNCATE) {
                $result = static::decimal_to_precision ($x - $x % $toNearest, $roundingMode, 0, DECIMAL_PLACES, $paddingMode);
            }
            return $result;
        }

**Comment by kroitor** [comment]
Thx for reporting, however, we fixed it 22 hours ago here: https://github.com/ccxt/ccxt/issues/4521 ;) Just update your version and it should work fine )
