### ISSUE TITLE
I want to know about the web socket of all exchanges.

### ISSUE THREAD

**Issue by AlexanderIvan** [ccxt/ccxt#4527]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by kroitor** [comment]
Please, follow here: #56
