### ISSUE TITLE
Error TheOcean: create_order 

### ISSUE THREAD

**Issue by Maha-Blaze** [ccxt/ccxt#4528]
I am using ccxt - 1.18.141 & node - v8.10.0. While creating order with their endpoints in js langugae its shows TypeError: BigNumber is not a constructor in Exchnage.js soliditySha3 function.Kindly help me to rectify my issue.

**Comment by kroitor** [comment]
Looks like you're missing the web3 deps and BigNumber, run this in your project folder:

```
npm install web3 ethereumjs-util ethereumjs-abi bignumber.js --save
```

... and you should be fine. Let us know if that doesn't help.
