### ISSUE TITLE
Gate.io withdraw issue

### ISSUE THREAD

**Issue by dascbh** [ccxt/ccxt#4529]
- OS: MacOS
- Programming Language version: Python
- CCXT version: 1.18.72
- Exchange: gateio
- Method: withdraw

Hi there,

I have been trying to withdraw from gateio to any other exchange and it is definitely no working. I noticed they have a different (btw very unusual pattern) pattern, they require the Address + [SPACE] + Tag as address for withdrawing coins like XRP.

I tried the most different approach but ccxt doesn't seem to be considering this pattern when building the request. Plus, Gateio require the address to be previously added on their address book before withdrawing through the API, then that makes the function even more restrict.

So, If I try using the default ccxt approach (address, key) I got this error:

gateio {"message":"Error: only used addresses are allowed for api withdrawal","code":103,"result":"false"}

I assumed it is not concatenating the two pieces (address and tag) and putting the space in between.

If I try forcing the whole value as string (like this "rhL5Va5tDbUUuozS9isvEuv12k1uuJaY1T 1595447228"), I got the following error:

gateio address is invalid or has less than 1 characters: "rhL5Va5tDbUUuozS9isvEuv12k1uuJaY1T 1595447228"

P.s: The address is properly added in the address book, I double checked with the support and did withdraw thru the console before.

**Comment by dascbh** [comment]
Hi @kroitor, were you able to reproduce the issue ?

**Comment by kroitor** [comment]
@dascbh do be honest, not yet, i didn't yet have the time to look into it, but will do my best to fix it shortly.

**Comment by kroitor** [comment]
> I tried the most different approach but ccxt doesn't seem to be considering this pattern when building the request.

↑ Indeed it was ignores in CCXT, because upon implementing it, this aspect was not documented properly in their docs, but i've added the proper handling, so you should not do the concatenation by hand anymore, instead, do this:

```Python
code = 'XRP'
address = '...'
tag = 'foobar'
amount = 1.0
exchange.withdraw (code, amount, address, tag)
```

Let us know if you still have difficulties with it after upgrading CCXT to version 1.18.153

**Comment by dascbh** [comment]
Hi Igor,

I have updated to version 1.18.154 and it is now returning the following
message:

gateio {"message":"Error: invalid data  ","code":6,"result":"false"}


I tried using the regular structure (code, amount, address, tag) and also
fixing the attributes, still no luck.

**Comment by kroitor** [comment]
@dascbh hi, can you please paste your verbose request/response output for it?

```
exchange.load_markets()
exchange.verbose = True
code = 'XRP'
address = '...'
tag = 'foobar'
amount = 1.0
exchange.withdraw (code, amount, address, tag)
```

(without your keys or sensitive data, of course)

**Comment by dascbh** [comment]
hi Igor, heres the output:

('Request:', 'POST', 'https://data.gate.io/api2/1/private/withdraw',
{'User-Agent': 'python-requests/2.19.1', 'Content-Type':
'application/x-www-form-urlencoded', 'Accept-Encoding': 'gzip, deflate',
'Key': '', 'Sign': ''},
'nonce=1548588877&currency=xrp&amount=317.8&address=rhL5Va5tDbUUuozS9isvEuv7Uk1uuJaY1T+1595447118')

('Response:', 'POST', 'https://data.gate.io/api2/1/private/withdraw', 200,
{'X-Powered-By': 'CF ()', 'Transfer-Encoding': 'chunked',
'Content-Encoding': 'gzip', 'Server': 'openresty/1.13.6.1', 'Connection':
'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache,
must-revalidate', 'Date': 'Sun, 27 Jan 2019 11:34:37 GMT',
'X-Frame-Options': 'SAMEORIGIN', 'Content-Type': 'application/json'},
u'{"result":"false","code":6,"message":"Error: invalid data  "}')


gateio {"message":"Error: invalid data  ","code":6,"result":"false"}

**Comment by kroitor** [comment]
@dascbh for some reason your tag contains a plus symbol `address=...JaY1T+1595447118'` ... and no space... that's very interesting. Let me test that on my side once again, will get back to you shortly.

**Comment by kroitor** [comment]
@dascbh looks like their API does not support the address + space + tag format at all (no word about it in their api docs), so, despite that the format corresponds to their website exactly – their API won't accept it. I guess, you should forward this question to their support and ask gate.io how to withdraw XRP + tag with their API. We will be thankful, if you manage to help us resolve it.

**Comment by dascbh** [comment]
Sure, I will work on it. I have an open ticket about this, as soon as I
have an update I will get back to you.

Thanks Igor

**Comment by kroitor** [comment]
@dascbh thx so much for your help as well, Daniel! I'll keep this issue open for now (hopefully, will get some answers from the community). Have you tried withdrawing a currency that does not require a tag, btw? Can you test ETH, for example? If that works, then I'm almost sure that the cause of trouble with XRP tag is on the exchange's side in this case.

**Comment by dascbh** [comment]
Hi Igor,

Regarding the problem, they replied saying we should encode the data
according this PHP example: https://gateio.io/api2#example

That makes some sense, what you think ?

Em , 27 de jan de 2019 às 11:13, Igor Kroitor <notifications@github.com>
escreveu:

**Comment by kroitor** [comment]
@dascbh I will upload a workaround for it, would you be willing to help me test it out (plz ;)) ? As I don't have a funded account with a currency involving a tag with gate.io currently, and it requires the address to be in the list as you know...

**Comment by dascbh** [comment]
Hi igor,

Sure, just let me know when you merge the fix and I will test it out.

Em seg, 28 de jan de 2019 às 12:07, Igor Kroitor <notifications@github.kcom>
escreveu:

**Comment by kroitor** [comment]
@dascbh alright, i will update you as soon as it's there, in a few hours most likely

**Comment by kroitor** [comment]
@dascbh after looking more carefully into it...

> Regarding the problem, they replied saying we should encode the data according this PHP example: https://gateio.io/api2#example

> That makes some sense, what you think ?

... no, it doesn't make any sense at all. Looks like an answer that is absolutely ignorant of the problem you're having. Because, I've checked, we encode the data **exactly according to that link.**

Moreover, if you try their other "official" wrappers, for example, this one, in python – it won't allow you to withdraw to XRP to an address with a space in it – try that yourself:

- https://github.com/gateio/rest/tree/master/python

↑ I suggest that you:

1. download their official archive
2. unpack it
3. edit `Client.py` for your credentials
4. uncomment withdraw in `Client.py` and change it for your arguments
5. run it with `python Client.py`
6. try to get balance with the same code to make sure this is a withdraw-only issue

Do you have any success with it?

**Comment by dascbh** [comment]
hey man, I'm back. Here's the answer I got from Gateio's team:

[image: Captura de Tela 2019-03-01 às 23.56.07.png]

**Comment by kroitor** [comment]
Hi, @dascbh ! Good to hear again from you! ) Unfortunately, can't see the attached image... Can you copy-paste it here in text, plz?

**Comment by dascbh** [comment]
hey man, sorry about that. the answer wasn't good anyway:


*Gate.io Support* (gate.io)

Feb 28, 20:22 CST
hi
Our dev team tried with XRP withdrawal in Python and it works well


Please make sure you urldecode when you  Sign  as well

The paramters in Sign must be  urldecode processed

*2252800*

Feb 25, 18:12 CST

I've checked, we encode the data exactly according to that link.

Moreover, if you try their other "official" wrappers, for example, this
one, in python – it won't allow you to withdraw to XRP to an address with a
space in it – try that yourself:

* https://github.com/gateio/rest/tree/master/python

↑ I suggest that you:

1. download their official archive
2. unpack it
3. edit Client.py for your credentials
4. uncomment withdraw in Client.py and change it for your arguments
5. run it with python Client.py
6. try to get balance with the same code to make sure this is a
withdraw-only issue

Do you have any success with it?

**Comment by kroitor** [comment]
@dascbh have you tried their official python client as i suggested here: https://github.com/ccxt/ccxt/issues/4529#issuecomment-458426178 ?

**Comment by phoonks** [comment]
hi i get the same error message, have any solution now? i new with this

**Comment by kroitor** [comment]
@phoonks have you tried to do the test with their own implementation: https://github.com/ccxt/ccxt/issues/4529#issuecomment-458426178 ? I suggest to also reach out to their support, the more users report it the sooner they acknowledge the issue...

**Comment by yusufmendes** [comment]
@kroitor @dascbh  You should add   body = querystring.unescape(body);  to sign method inside  gateio.js and it will fix "gateio {"message":"Error: invalid data  ","code":6,"result":"false"}" error.We should unescape space character  for Address + [SPACE] + Tag structure.I tried XRP withdrawal using following sign method and it worked correctly.

    sign(path, api = 'public', method = 'GET', params = {}, headers = undefined, body = undefined) {
        const prefix = (api === 'private') ? (api + '/') : '';
        let url = this.urls['api'][api] + this.version + '/1/' + prefix + this.implodeParams(path, params);
        const query = this.omit(params, this.extractParams(path));
        if (api === 'public') {
            if (Object.keys(query).length) {
                url += '?' + this.urlencode(query);
            }
        } else {
            this.checkRequiredCredentials();
            const nonce = this.nonce();
            const request = {'nonce': nonce};
            body = this.urlencode(this.extend(request, query));
            body = querystring.unescape(body); //newly added code
            const signature = this.hmac(this.encode(body), this.encode(this.secret), 'sha512');
            headers = {
                'Key': this.apiKey,
                'Sign': signature,
                'Content-Type': 'application/x-www-form-urlencoded',
            };
        }
        return {'url': url, 'method': method, 'body': body, 'headers': headers};
    }

**Comment by kroitor** [comment]
@yusufmendes thank you very much for your feedback, will add that to the master branch shortly.
