### ISSUE TITLE
Kraken, zero balance

### ISSUE THREAD

**Issue by mazertwo** [ccxt/ccxt#453]
Kraken dont send 0 (zero), if balance 0. This is for all cryptocurrencies. 
Ccxt gets None and make error.

**Comment by kroitor** [comment]
Thx! Will fix it very soon!

**Comment by kroitor** [comment]
Can you please post the output?

**Comment by mazertwo** [comment]
I need to post output after update ccxt? Last version?

**Comment by kroitor** [comment]
@mazertwo any version you have difficulties with. But, yes, possibly, the last one. Though this functionality has not changed for a long time.

**Comment by mazertwo** [comment]
With last version:

import ccxt

kraken = ccxt.kraken()
kraken.apiKey = 'xxxxxxxxxxxxxxxxxxxxx'
kraken.secret = 'xxxxxxxxxxxxxxxxxxxxx'
kraken.enableRateLimit = True

exch1balance = kraken.fetch_balance()
print(exch1balance)
print(exch1balance['LTC']['free'])

Error:

C:\Python\python.exe C:/Users/1/Desktop/test1.py
{'info': {'XXBT': '0.0000000000', 'XETH': '0.0000000000', 'XZEC': '0.0000082500'}, 'BTC': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'ETH': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'ZEC': {'free': 8.25e-06, 'used': 0.0, 'total': 8.25e-06}, 'free': {'BTC': 0.0, 'ETH': 0.0, 'ZEC': 8.25e-06}, 'used': {'BTC': 0.0, 'ETH': 0.0, 'ZEC': 0.0}, 'total': {'BTC': 0.0, 'ETH': 0.0, 'ZEC': 8.25e-06}}
Traceback (most recent call last):
  File "C:/Users/1/Desktop/test1.py", line 10, in <module>
    print(exch1balance['LTC']['free'])
KeyError: 'LTC'

Process finished with exit code 1

**Comment by mazertwo** [comment]
It happen, if you never deposit LTC or any other cruptocurrency to Kraken.
Kraken get nothing in this case. (See all fetch balance output)

**Comment by kroitor** [comment]
@mazertwo but... this is not an error... from [the Manual](https://github.com/ccxt/ccxt/wiki/Manual#querying-account-balance):

> Some exchanges may not return full balance info. Many exchanges do not return balances for your empty or unused accounts. In that case some currencies may be missing in returned balance structure.

> Also, some exchanges cannot return certain fields and are only capable of telling a total balance (without details). Therefore some or all of the free, used and total amounts may be undefined, None or null. So, it's a normal behaviour, and you need to account for that when working with returned balances.

Basically, a missing LTC tells the user that this balance was never used before, so we can't override it or set it explicitly with any other value if Kraken does not return it. So you need to check it when you access it:

```Python
print(exch1balance['LTC']['free'] if 'LTC' in exch1balance else 'Zero LTC balance')
```

Does this answer your question?

**Comment by mazertwo** [comment]
Yes. Thank you! 
But, my opinion, better if ccxt gets 0 (zero) in cases like this (if requested cryptocurrency is supported by exchange). Its standartise ccxt fetch balance.

**Comment by kroitor** [comment]
@mazertwo we had a big discussion on this... 
Initially, it was not set by default, if it was missing.
Then @achievement008 came with this: https://github.com/ccxt/ccxt/issues/166
We made it 0 by default.
After that @mkutny cam with this: https://github.com/ccxt/ccxt/issues/235
We agreed and reverted it back to how it was initially (not setting it by default)...
Now we are in this post, discussing if we should set it to 0 again...
So, this time, I guess, we should say sorry, but, no, if you think/read carefully about it in #235 , you will agree (I hope) that is should be as is now. ;)

**Comment by mazertwo** [comment]
Ok, shure, better if balance can have 3 states: 0, !=0, and "undefined"
