### ISSUE TITLE
bchabc binance

### ISSUE THREAD

**Issue by hbus12** [ccxt/ccxt#4530]
- Programming Language version: PHP 7
- CCXT version: 1.18.142
- Exchange: Binance
- Method: create_market_order

When trying to create a BCHABC marketorder, getting this error: binance does not have market symbol BCHABC/

But that is a legit symbol for Binance, am I right?

**Comment by kroitor** [comment]
> But that is a legit symbol for Binance, am I right?

Nope ) It's `BCH` for BCHABC and `BSV` for BCH SV.

Explained here:

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
- https://github.com/ccxt/ccxt/wiki/Manual#naming-consistency
- https://github.com/ccxt/ccxt/issues/4311

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/blob/master/examples/php/symbols.php

**Comment by mw130** [comment]
@kroitor Sorry I realized it's on my end because when I'm writing the data into a db it's using the name used by the exchange, so I guess then my question would be if there's any table struct that maps the actual name used on the exchange to the Symbol name used by ccxt, so that I could use that to fix this error.

**Comment by kroitor** [comment]
@mw130 

> I guess then my question would be if there's any table struct that maps the actual name used on the exchange to the Symbol name used by ccxt, so that I could use that to fix this error

Uhmm... ) Let me scratch my head ) Do you mean, like this one )

<img width="932" alt="screen shot 2019-01-28 at 21 37 20" src="https://user-images.githubusercontent.com/1294454/51858094-ec41e300-2344-11e9-92cc-39f49e2680c8.png">

You see, the very purpose of this library was to solve that problem. So, yes, if you look into examples and read through the Manual, you will quickly notice, that all the mappings of symbols to markets and ids are stored in exchange properties for your convenience:

- https://github.com/ccxt/ccxt/blob/master/examples/php/symbols.php 
- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids ← read this and make sure you understand the examples from text, really )

```PHP
<?php

date_default_timezone_set ('UTC');

$exchange = new \ccxt\binance ();
$exchange->load_markets (); // as documented in the Manual

// id == exchange-specific 
for ($exchange->markets_by_id as $id => $market) {
    echo 'market id: ' . $market['id'] . '; symbol: ' . $market['symbol'] . "\n"; 
}

// symbol = universal across exchanges
for ($exchange->markets as $symbol => $market) {
    echo 'market id: ' . $market['id'] . '; symbol: ' . $market['symbol'] . "\n"; 
}
?>
```

**Comment by mw130** [comment]
@kroitor This is what I was looking for, sorry that I missed it. Thanks so much!
