### ISSUE TITLE
Exmo PHP fetchOrder bug

### ISSUE THREAD

**Issue by elcryptoninja** [ccxt/ccxt#4534]
- OS:
- Programming Language version: PHP
- CCXT version: 1.18.144
- Exchange: Exmo
- Method: fetchOrder and fetchOrderTrades

In the php version exmo.php line 746:

```
                    $filled .= $trade['amount'];
                    if ($feeCost === null) {
                        $feeCost = 0.0;
                    }
                    $feeCost .= $trade['fee']['cost'];
                    if ($cost === null) {
                        $cost = 0.0;
                    }
                    $cost .= $trade['cost'];
```

The .= is wrong, it should be +=

The result is when I call fetchOrder on some order, I get the
"Notice: A non well formed numeric value encountered"
And it ends with exception fetchOrder order not found in cache.

**Comment by kroitor** [comment]
Fixed in 1.18.145. Appreciate your feedback!
