### ISSUE TITLE
FetchOpenOrders impls for Exchanges?

### ISSUE THREAD

**Issue by michaeljohnbennett** [ccxt/ccxt#4535]
- OS: OSX
- Programming Language version: Node/Typescript/JS
- CCXT version: 1.18.145
- Exchange: independentreserve
- Method: fetchOpenOrders

Hi,

Just been testing out this API and wondered what is your roadmap for implementing the private functions for a bunch of exchanges, I was trying Independent reserve and all the private order methods aren't in place yet. 

Any ETA on these features being implemented?

**Comment by kroitor** [comment]
@michaeljohnbennett 

- https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar
- https://github.com/ccxt/ccxt/wiki/FAQ#when-will-you-add-feature-foo-for-exchange-bar--whats-the-estimated-time-when-should-we-expect-this

**Comment by kroitor** [comment]
<img width="1505" alt="screen shot 2019-01-24 at 19 15 17" src="https://user-images.githubusercontent.com/1294454/51691740-67855b00-200c-11e9-9b3e-deb5f1cfdd1c.png">

**Comment by kroitor** [comment]
More about it here: #71

**Comment by michaeljohnbennett** [comment]
Thanks for the info, I didn't see this on my travels.

I just implemented the missing functions locally in an extended version of the Exchange class.

Very cool package, I realise it takes time to fill in all the blanks in your matrix above for some of the smaller exchanges.

**Comment by kroitor** [comment]
@michaeljohnbennett 

Oh, yeah ) 

Here's one approx a year ago, for comparison:

<img width="1638" alt="screen shot 2018-02-10 at 03 34 07" src="https://user-images.githubusercontent.com/1294454/36056192-592dcddc-0e13-11e8-9ce8-3d0cb82a18f1.png">

So, there's been some progress )

> I just implemented the missing functions locally in an extended version of the Exchange class.

We will be happy to see PRs and contributions from you! ) More about it here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md ;)
