### ISSUE TITLE
Just in case you are interested: Binance API Coding Competition

### ISSUE THREAD

**Issue by vonpupp** [ccxt/ccxt#454]
Hi @kroitor,

I wanted to let you know in case you might be interested. Binance is hosting a [competition] rewarding for integrations on their API. It could be a reward for your work :).

Unfortunately I saw that late, submissions are by Nov 4th.

Best regards.

[competition]: https://support.binance.com/hc/en-us/articles/115001909972

**Comment by kroitor** [comment]
@vonpupp hi, @vonpupp ! Thx for the notice. I've submitted the ccxt twice a couple of weeks ago, but got no answer, I guess it means "no". Thx anyway. Respect!

**Comment by vonpupp** [comment]
Sorry to hear that. Don't worry anyway man, ccxt rocks and we know it :)
