### ISSUE TITLE
Python HTTPSConnectionPool Max retries exceeded with url

### ISSUE THREAD

**Issue by SKhakhulin** [ccxt/ccxt#4540]
```
import ccxt

exchange_name = 'exmo'
exchange = getattr(ccxt, exchange_name)({
         "enableRateLimit": True,
})
market="MNX/BTC"
exchange.fetch_order_book(market)

```
`RequestTimeout: exmo GET https://exmo.me/en/docs/fees HTTPSConnectionPool(host='exmo.me', port=443): Max retries exceeded with url: /en/docs/fees (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10bad4da0>, 'Connection to exmo.me timed out. (connect timeout=10)'))`

**Comment by epcorona** [comment]
I had a similar issue using django as server and postman to make POST requests. The problem occurred to me only when I was behind a proxy. So I set proxy settings on the same command prompt where I run django
>set https_proxy=http://proxy:port
>set http_proxy=http://proxy:port
>python manage.py runserver
