### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by Maha-Blaze** [ccxt/ccxt#4543]
Hi i am trying with new exchange idex in ccxt. In that,for cancel_order i need to call a function 'signZeroExOrder' to calculate a ecsignature from Exchange file. I will send two args for cancel_order, 1.orderHash(uint256) and 2.nonce(uint256), its shows  ValueError: invalid literal for int() with base 10 for orderHash value. Cancel_order is working fine in js and php. Its's shows error in python,kindly help me to rectify my issue. Thank you

**Comment by kroitor** [comment]
Hi! Check out this PR: https://github.com/ccxt/ccxt/pull/4545
