### ISSUE TITLE
I want to know how to get the profit via this library

### ISSUE THREAD

**Issue by AlexanderIvan** [ccxt/ccxt#4551]
Hello. Support.
Your library is really amazing.
I appreciate with your library.
I am trying to get the profit in various exchanges via ticker api.
but I don't know well.
If you help me, I will appreciate very well.
Thanks.

**Comment by kroitor** [comment]
@AlexanderIvan I'd recommend to start by reading the Manual (https://github.com/ccxt/ccxt/wiki) from top to bottom first, it already has answers to a lot of questions you might have in the process. 

Also: https://github.com/ccxt/ccxt/tree/master/examples#see-also

Let us know if that does not help. Feel free to reopen this if needed or just ask further questions if any.
