### ISSUE TITLE
How to read exchange API errors in JavaScript?

### ISSUE THREAD

**Issue by viniciussvl** [ccxt/ccxt#4552]
How do I get them to read them correctly in JavaScript? I like to save the error messages in a log file but I am not getting the msg item from the error object, it simply accuses the variable is undefined

I'm using try catch as follows, I give a console in e.message and it returns me an object but when I try to get only the undefined message, can anyone help me?

`try {
            data = await this.exchange.createOrder(symbol, type, side, amount, price, params);
        } catch (e) {
            console.log(e.message.msg);
}`

- OS: Windows 10
- Programming Language version: JavaScript / Node.js
- CCXT version: 1.18.133
- Exchange: Binance
- Method: createOrder or others

**Comment by kroitor** [comment]
```JavaScript
try {
    data = await this.exchange.createOrder(symbol, type, side, amount, price, params);
} catch (e) {
    console.log(e.constructor.name, e.message);
}
```

Let us know if that does not answer your question.

**Comment by viniciussvl** [comment]
> ```js
> try {
>     data = await this.exchange.createOrder(symbol, type, side, amount, price, params);
> } catch (e) {
>     console.log(e.constructor.name, e.message);
> }
> ```
> 
> Let us know if that does not answer your question.

So, it shows me a string for example: "binance {code: 202, msg: 'Account ......'}, I want to just get msg: 'Account'

**Comment by kroitor** [comment]
@viniciussvl 

```JavaScript
try {
    data = await this.exchange.createOrder(symbol, type, side, amount, price, params);
} catch (e) {
    // for binance only!
    const [ exchangeId, errorString ] = e.message.split (' ')
    const error = JSON.parse (errorString)
    console.log (error.msg)
}
```

**Comment by viniciussvl** [comment]
> @viniciussvl
> 
> ```js
> try {
>     data = await this.exchange.createOrder(symbol, type, side, amount, price, params);
> } catch (e) {
>     // for binance only!
>     const [ exchangeId, errorString ] = e.message.split (' ')
>     const error = JSON.parse (errorString)
>     console.log (error.msg)
> }
> ```
> 
> **Oops. this one has an error in it, will post one more shortly**

I thought I'd do something like this, make a helper to read the error of each exchange, what do you suggest?

**Comment by kroitor** [comment]
@viniciussvl 

> what do you suggest?

We have unification for error messages on our roadmap, but the issue can be solved in a simpler way – instead of parsing those errors and trying to get the message – we will return that as a standalone field for convenience, so no parsing will be required at all. Hope to do that soon.
