### ISSUE TITLE
CryptoTradingBot Development using ccxt

### ISSUE THREAD

**Issue by TrustyMan** [ccxt/ccxt#4553]
I'm creating cryptocurrency Trading Bot using node.js.
I'm getting realtime data using ccxt fetchTrades() method.
I wanna know about how bot app exchanges using ccxt.

**Comment by kroitor** [comment]
@TrustyMan I'd recommend to check this out: https://github.com/ccxt/ccxt/tree/master/examples#see-also. Hope it helps. If it doesn't, let us know which particular questions you have remaining. Feel free to reopen this issue if needed.
