### ISSUE TITLE
GDAX (Coinbase Pro) fetch_transactions throws error

### ISSUE THREAD

**Issue by WoK-E** [ccxt/ccxt#4557]
- OS: any
- Programming Language version: PHP
- CCXT version: 1.18.159
- Exchange: Coinbase Pro
- Method: fetch_transactions()

The last line of the function throws an exception, as parseTransactions expects at least 2 arguments
Please replace
return $this->parseTransactions ($response);
with return $this->parseTransactions ($response, $currency, $since, $limit);

Also, the for loop immediately preceding the line above, throws an error if $response is not an array.
Please add some checking before the for loop, e.g.
if (!is_array($response))
  $response = array();

**Comment by kroitor** [comment]
@WoK-E 

> Also, the for loop immediately preceding the line above, throws an error if $response is not an array.

Can you please elaborate in which particular cases that happens? Your verbose output would really help a lot.

**Comment by WoK-E** [comment]
The problem ($response is not an array) occurs when there are no transactions for a given currency.
The wallet (account) is there, a correct $accountId is returned, but 
$this->privateGetAccountsIdTransfers() returns a string:
var_dump($response) returns **string(2) "[]"**

**Comment by WoK-E** [comment]
Hi Igor,

Just a reminder that this problem still exists.

PHP Warning:  count(): Parameter must be an array or an object that implements Countable in vendor/ccxt/ccxt/php/gdax.php on line 607
PHP Fatal error:  Uncaught Error: Cannot use string offset as an array in vendor/ccxt/ccxt/php/gdax.php:608
Stack trace:
#0 vendor/ccxt/ccxt/php/Exchange.php(1681): ccxt\gdax->fetch_transactions('MKR', '1540192460', NULL, Array)
<snip>
#3 {main}
  thrown in vendor/ccxt/ccxt/php/gdax.php on line 608
