### ISSUE TITLE
Liqui Closure

### ISSUE THREAD

**Issue by marcuswin** [ccxt/ccxt#4559]
Proof: https://bitcoinschannel.com/breaking-liqui-exchange-the-end-users-are-requested-to-withdraw-their-funds/

**Comment by wybitnygracz** [comment]
there is no possibility to withdrawl usdt from liqui.io. Their support does not work, when you try to create a ticket, you will log out. You can not contact them. It is exit scam. 
Anyone know how to contact with liqui support?

**Comment by kroitor** [comment]
@wybitnygracz it's the same for all users, it says *"Unable to verify if address correct."* and this is also confirmed on reddit

> Anyone know how to contact with liqui support?

Nope, unfortunately, we can't really do anything about it on our side.

**Comment by wybitnygracz** [comment]
; /
