### ISSUE TITLE
Bitfinex fiat (USD) withdraw()

### ISSUE THREAD

**Issue by Fcl69** [ccxt/ccxt#456]
code:

```
import ccxt 
exch = ccxt.bitfinex({
    'apiKey': 'key',
    'secret': 'sec',
    'enableRateLimit': True,
    'verbose': True,
    })
order = exch.withdraw('USD', '100', 'wallet')
print(order)
```

output:

> https://api.bitfinex.com/v1/symbols_details GET https://api.bitfinex.com/v1/symbols_details
>Bad Request  {"message":"Key swift was not present."}

**Comment by kroitor** [comment]
Hi! Basically, it tells you the reason:

> {"message":"Key swift was not present."}

What it is saying is that if you want to do fiat withdrawals (USD), then they require SWIFT bank code, as long as several other params, described here: https://bitfinex.readme.io/v1/reference#rest-auth-transfer-between-wallets

<img width="1013" alt="screen shot 2017-11-03 at 08 00 00" src="https://user-images.githubusercontent.com/1294454/32361193-96165e46-c06e-11e7-97de-7b4689e2ff82.png">


You can pass them in the last argument of the withdraw call like so:

```Python
exch.withdraw('USD', '100', 'wallet',{
    'swift': 'YOUR_SWIFT',
    'bank_name': 'YOUR_BANK_NAME',
    # all other required params...
})
```

Does this help?

**Comment by Fcl69** [comment]
Hm... Yes, you're right. I thought it was USDT. I guess, they're using another symbol for that.

**Comment by Fcl69** [comment]
F$%^ Bitfinex won't do "USDT", nor "tether"
Do you happen to know which symbol I should specify for tethers?

**Comment by kroitor** [comment]
@Fcl69 yeah, just one sec we will try adding USDT support. I'll get back to you with an update in 5 minutes.

**Comment by kroitor** [comment]
@Fcl69 can you please try it with version 1.9.356 and `USDT`?

**Comment by Fcl69** [comment]
Hello!

Looks like it accepted the symbol:

>  [{"status":"error","message":"Min 100 USD","withdrawal_id":0,"fees":"5.0"}]
> {'info': {'message': 'Min 100 USD', 'fees': '5.0', 'withdrawal_id': 0, 'status': 'error'}, 'id': 0}

**Comment by kroitor** [comment]
@Fcl69 Yes it did, but it requires >100USD. I guess you can carry on from here. Thx!

**Comment by Fcl69** [comment]
I've tested the full cycle, and it worked. Thanks again!

**Comment by Tsuihao** [comment]
Hi all, 

Just wanna ask, I faced problem when I trying to withdraw at "Kraken".
I obtained the following message
`Kraken requires 'key' to withdraw`.

Is this 'key' referring to: **1**. 2-factor authentication **2**. apiKey or **3**. secretKey
I have checked [Manual](https://github.com/ccxt/ccxt/wiki/Manual#withdraw)
However, there is no clearly state which information do the 'key' referring to.

Regards,
Hao

**Comment by kroitor** [comment]
@Tsuihao can you show the code and verbose output? (set .verbose = true on the exchange, then call withdraw)

**Comment by Tsuihao** [comment]
@kroitor,

verbose set.
And here is the output

![image](https://user-images.githubusercontent.com/16992390/34665882-2bb84a6e-f462-11e7-97d7-5c2bd710c942.png)

**Comment by kroitor** [comment]
@Tsuihao this is either your withdrawal address name or withdrawal address (often set to the same value):

![kraken-withdraw](https://user-images.githubusercontent.com/1294454/34666379-1e894c18-f475-11e7-8282-6bcdc67a7201.jpg)

**Comment by Tsuihao** [comment]
@kroitor, Thanks for the info. 
I will test and report to you.
