### ISSUE TITLE
how to use createDepositAddress

### ISSUE THREAD

**Issue by TrustyMan** [ccxt/ccxt#4562]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:
I'm working on createDepositAddress.
How can I deposit 1000usdt using ccxt?

**Comment by kroitor** [comment]
> How can I deposit 1000usdt using ccxt?

1. if you have the deposit address for USDT with the exchange in question (if the address was created earlier) – you can fetch it for USDT by using `fetchDepositAddress ('USDT')`, if the exchange `has['fetchDepositAddress'] = true` in [exchange metadata](https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata).


2. if you don't have the deposit address for USDT yet – you can try creating one, if the exchange `has['createDepositAddress'] = true` in [exchange metadata](https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata).

3. after fetching the deposit address – you can send the money there from whatever wallet you use to manage your USDT or from another exchange with the `withdraw` method, also described in the Manual.

The CCXT won't handle wallet operations outside of exchanges for you, because that would require blockchain unification.

Hope it answers your questions.

**Comment by kroitor** [comment]
<img width="1505" alt="screen shot 2019-01-24 at 19 15 17" src="https://user-images.githubusercontent.com/1294454/51691740-67855b00-200c-11e9-9b3e-deb5f1cfdd1c.png">

**Comment by TrustyMan** [comment]
It seems the binance exchange site doesn't support createDepositAddress() function.
how can I deposit on binance exchange site?

**Comment by kroitor** [comment]
> It seems the binance exchange site doesn't support createDepositAddress() function.

Please, pay attention to everything, not just the first point of my previous comment ) Because i've put conditionals everywhere in that comment like: `if has['fetchDepositAddress'] = true` ← you should check if the exchange has that method first.

**Comment by TrustyMan** [comment]
I want to deposit on binance. Is there any other function like createDepositAddress.
fetchDepositAddress is a function to get deposit address. right?
I want to create a new deposit.

**Comment by kroitor** [comment]
> fetchDepositAddress is a function to get deposit address. right?

Right, it's the function that will return you the address you want to deposit to. But it will not deposit for you.

> I want to create a new deposit.

Yeah, that's clear, and, in order to deposit money, you need to:

1. Obtain the address to deposit to, by either `fetchDepositAddress` or `createDepositAddress`
2. Send your money there, like you would normally deposit to your Binance account (ccxt won't send the deposit there for you).

**Comment by TrustyMan** [comment]
To create new order, should I deposit first?

**Comment by kroitor** [comment]
> To create new order, should I deposit first?

Yes.

**Comment by TrustyMan** [comment]
const depositAddress = await exchange.createDepositAddress(symbol)
  const depositAddress = await binance.deposit(symbol, { 'renew' : 1 })
  //Send funds to address
  const balances = await exchange.fetchBalance()
  const balanceToCommit = data.amountinvested
  //const balanceToCommit = balances[symbol].free
  console.log(balances)
  console.log('Balances to commit: ' + balanceToCommit )
  //Commit a balance to a specific market
  const market = data.symbol
  await exchange.commit(symbol, balanceToCommit, market)

This is my past code for deposit.
If I use fetchDepositAddress() function, is this a correct way to deposit on binance?

**Comment by kroitor** [comment]
@TrustyMan 

> "top up"?

<img width="1309" alt="screen shot 2019-01-29 at 05 29 22" src="https://user-images.githubusercontent.com/1294454/51880050-e0771080-2386-11e9-910a-82d5545e3691.png">

Yep, you *top up* your balance, *fund* your balance, *deposit to* your balance or *send money to* your balance – those are almost synonyms.

> This is my past code for deposit.
> If I use fetchDepositAddress() function, is this a correct way to deposit on binance?

Not really. There's no such method as `exchange.commit` where did you take it from?

>  a correct way to deposit on binance

```JavaScript
let response = undefined
const currencyCode = 'ETH'
const amount = 1.2345
try {
    if (exchange.has['fetchDepositAddress']) {
        response = await exchange.fetchDepositAddress (currencyCode)
    } else if (exchange.has['createDepositAddress']) {
        response = await exchange.createDepositAddress (currencyCode)
    }
} catch (e) {
    console.log (e.constructor.name, e.message)
}
console.log (
    'In order to deposit ' + amount.toString () + ' ' + currencyCode + ' to ' + exchange.id + 
    ', please send your ' + amount.toString () + ' ' + currencyCode + ' to the address provided by the ' +
    exchange.id + ' exchange for depositing: ' + response['address'] + (response['tag'] || ''))
```

**Comment by TrustyMan** [comment]
thanks

**Comment by TrustyMan** [comment]
https://sparkswap.com/docs/integration/ccxt
Here, I got a commit function.

**Comment by kroitor** [comment]
> Here, I got a commit function.

As far as I know, sparkswap isn't integrated yet. Moreover, you were asking about Binance initially. SO you kinda pivoted here ) 

Also, please make sure you understand the difference between this:
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
and this:
- https://github.com/ccxt/ccxt/wiki/Manual#unified-api

**Comment by kroitor** [comment]
> https://sparkswap.com/docs/integration/ccxt
> Here, I got a commit function.

A unified analogue of a `commit` implicit method is the `withdraw` method:

- https://github.com/ccxt/ccxt/wiki/Manual#withdraw

**Comment by TrustyMan** [comment]
To create order, we need to deposit.
By the way, I can't see any parameter of deposit  address in createOrder() function.
where do we use deposit address for creating order?

**Comment by kroitor** [comment]
@TrustyMan 

> where do we use deposit address for creating order?

We don't use deposit addresses for creating orders. We use deposit addresses to send money to those addresses, so that your balance get funded with the exchange and then you can use those arrived deposited funds to place orders with the exchange. Placing orders doesn't involve any deposit addresses. Putting money to the exchange for placing orders does involve deposit addresses. If you have some balance with the exchange already – you don't have to deposit to that exchange anymore to be able to place orders.

**Comment by TrustyMan** [comment]
![image](https://user-images.githubusercontent.com/29589220/51903211-a2b1d080-23f6-11e9-884b-ea9048b1ce1b.png)
![image](https://user-images.githubusercontent.com/29589220/51903279-c83eda00-23f6-11e9-90a7-41c9dd1df8ed.png)

**Comment by TrustyMan** [comment]
There aren't any fetchDepositAddress() and createDepositAddress() function.
The error occured.

**Comment by kroitor** [comment]
@TrustyMan if you changed the code i posted above how you posted on the screenshot – that won't work. You've basically skipped all the checks. 

I've asked you to never paste your code as images – use the text instead. You're not using ASCII art to store your photos right? So why would you use images to store and show your text )) The point is: I can't really do anything with that screenshot, can't copypaste, cannot run it, you're not showing a small reproducible snippet of code as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ← you should follow these rules PRECISELY and EXACTLY (literally to each word and symbol) for us to be able to help you and resolve this quickly.

**Comment by TrustyMan** [comment]
![image](https://user-images.githubusercontent.com/29589220/51904110-c5dd7f80-23f8-11e9-9765-bfa5d93d8a42.png)

**Comment by kroitor** [comment]
@TrustyMan those are commented out on your previous screenshot

**Comment by TrustyMan** [comment]
//new Bot configuration
router.post("/newbot", async (req, res, next) =>{
  let data = req.body
  /*
  data.name
  data.licensekey
  data.apikey
  data.symbol
  data.actualprice
  data.entryprice
  data.increase
  data.amountinvested
  data.equivalent
  data.tradingtime
  data.arrivaltime
  data.salesprice
  data.presaleprice
  data.gain
  */
  // let result = botdao.save(data)

  //--------------------------------------------------------------------------------------
  //create deposit
  let exchangeId = 'binance'
  , exchangeClass = ccxt[exchangeId]
  , exchange = new exchangeClass ({
    'apiKey': data.apikey,
    'secret': data.secret,
    'timeout': 30000,
    'enableRateLimit': true,
    'test': true
  })
  let response = undefined
  const currencyCode = data.symbol.split('/')[0]
  const amount = data.amountinvested
  const market = data.symbol
  //fetch deposit address
  try {
    if (exchange.hasFetchDepositAddress == true) {
      console.log('fetch')
        response = await exchange.fetchDepositAddress (currencyCode)
    } else if (exchange.hasCreateDepositAddress == true) {
      console.log('create')
        response = await exchange.createDepositAddress (currencyCode)
    }
    console.log (
        'In order to deposit ' + amount.toString () + ' ' + currencyCode + ' to ' + exchange.id + 
        ', please send your ' + amount.toString () + ' ' + currencyCode + ' to the address provided by the ' +
        exchange.id + ' exchange for depositing: ' + response['address'] + (response['tag'] || ''))

  } catch (e) {

      console.log (e.constructor.name, e.message)
  }
  //--------------------------------------------------------------------------------------
  botlist.push(data)
  res.send("xxxx")
})

**Comment by TrustyMan** [comment]
Error message says "TypeError exchange.fetchDepositAddress is not a function"

**Comment by kroitor** [comment]
@TrustyMan how do you import ccxt and what's your version?

**Comment by TrustyMan** [comment]
I'm using 1.9.65

**Comment by kroitor** [comment]
@TrustyMan oh, you're living in stone age – that's a very old version. And you should update, really, your version is almost year-old already...

**Comment by TrustyMan** [comment]
how can I update it?

**Comment by kroitor** [comment]
@TrustyMan 

> how can I update it?

https://stackoverflow.com/questions/16525430/npm-check-and-update-package-if-needed

Also, you need to change your code slightly to use the new metainfo format... Look closer here:

My code:

```JavaScript
if (exchange.has['fetchDepositAddress']) {
```

Your code:

```
if (exchange.hasFetchDepositAddress == true) {
```

**Comment by TrustyMan** [comment]
working, thanks
by the way, I fetched depositAddress, but I didn't use this
why do we need depositAddress? where can we use this?

**Comment by kroitor** [comment]
> why do we need depositAddress? where can we use this?

In order to place orders to buy or sell currency for another currency, you should have at least some currency on your account balance with the exchange. The fetched address is used by you to send the money from your crypto wallet to your crypto exchange account, so that you could trade your money with the exchange. You can also send money (withdraw) from one exchange to another.
