### ISSUE TITLE
ccxt thinks BCH/BTC is a pair in Binance (but doesn't exist)

### ISSUE THREAD

**Issue by mw130** [ccxt/ccxt#4563]
@kroitor 
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: OS X Mojave
- Programming Language version: Python 3
- CCXT version: 1.18.164
- Exchange: Binance
- Method:
```import ccxt
client = ccxt.binance()
df = client.load_markets()
print('BCH/BTC' in df)
```

This returns true, although BCH is not available on Binance. 
Binance only has BCHABC and BCHSV. I'm a bit concerned why this might be, because I assumed ccxt would always make a direct query to Binance's endpoint. Might this be a binance issue and not ccxt?

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/4530 ;)
