### ISSUE TITLE
New Kraken Websocket API

### ISSUE THREAD

**Issue by spcfran** [ccxt/ccxt#4568]
Kraken is releasing a new websocket API as [announced in their blog](https://blog.kraken.com/post/2019/websockets-public-api-launching-soon/). Documentation is [here](https://www.kraken.com/en-gb/help/websocket-api).

Any plans to implement it?

**Comment by kroitor** [comment]
All about WS in this post: https://github.com/ccxt/ccxt/issues/56#issuecomment-457905834 Let us know if that doesn't answer the question.
