### ISSUE TITLE
Poloniex market order

### ISSUE THREAD

**Issue by Arrmlet** [ccxt/ccxt#4575]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- Ubuntu:
- Python3:
- newest:
- Poloniex:
- market_sell_order:

Hello, I want to create market order on poloniex but this exchange is not supporting market orders, and I try to set very low price, but it without results. My code
```
def load_balances(exch, coin):
	a= exch.fetch_balance()[coin]['free']
	a = a/100
	return a * 99
	
def sell_order(exch,coin,pair):
	bal = load_balances(exch,coin)
	try:
		exch.create_market_sell_order(pair, bal)
	except:
		exch.create_limit_sell_order(pair, bal, 0.00000001)
```
This code return me the error which look like this
`ccxt.base.errors.InvalidOrder: poloniex {"error":"Total must be at least 0.0001."}`

If you have any suggestions how to implement market sell or buy order on poloniex, I'll be very grateful.

**Comment by kroitor** [comment]
Duplicate, see the answers here: 

- https://github.com/ccxt/ccxt/search?q=Total+must+be+at+least&type=Issues
- https://github.com/ccxt/ccxt/issues/3688
- https://github.com/ccxt/ccxt/issues/3706
- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

... and check out further links. Let us know if that does not answer the question.
