### ISSUE TITLE
Bittrex API v2

### ISSUE THREAD

**Issue by marcuswin** [ccxt/ccxt#4577]
Now Bittrex API v2 doesn't work, because they make API v3. Proof: https://bittrex.github.io/api/v3

**Comment by lampardlb** [comment]
It's NOT open to the public though, I've checked with Bittrex. 'The V3-Alpha API is available on an invite-only basis (for high-volume corporate clients) at this time. Later releases will be made publicly available to the community.'

**Comment by kroitor** [comment]
Merged in #5219
