### ISSUE TITLE
Missing Payment ID when withdrawing BCN on Hitbtc

### ISSUE THREAD

**Issue by froseppl** [ccxt/ccxt#4582]
- OS: Debian
- Programming Language version: Python
- CCXT version: 1.18.133
- Exchange: hitbtc (V1 API)
- Method: withdraw

Hi, I've tried to withdraw BCN from my Hitbtc account using the CCXT withdraw method:
```hitbtc.withdraw('BCN', amount, address='BCN wallet address', tag='BCN Payment ID')```.
The transaction shows up in my Hitbtc account correctly but the Payment ID is missing. 

I expected that the payment ID should be provided in the 'tag' parameter as stated in the CCXT manual for deposits:
'With certain currencies, like AEON, BTS, GXS, NXT, SBD, STEEM, STR, XEM, XLM, XMR, XRP, an additional argument tag is usually required by exchanges. Other currencies will have the tag set to undefined / None / null. The tag is a memo or a message or a payment id that is attached to a withdrawal transaction. The tag is mandatory for those currencies and it identifies the recipient user account.'

Could you please give any hints how to withdraw BCN correctly?

Thanks!

**Comment by kroitor** [comment]
> Could you please give any hints how to withdraw BCN correctly?

This was bug in the implementation of hitbtc v1. Apologies for the inconvenience. You already do that the proper way, but because of the bug, it failed. I've uploaded a fix for it, so, if you update to version 1.18.189 it will work as documented. The build 1.18.189 will arrive in 5-10 minutes. We will be happy if you let us know whether this solves the issue for you or not.

**Comment by froseppl** [comment]
Hi Igor, unfortunately the issue still persists. I've once again tried to withdraw BCN as described above but the Payment ID is still missing, I've checked it in a BCN block explorer. I used CCXT version 1.18.237, all other details as described in my first post.

**Comment by kroitor** [comment]
Hi, @froseppl ! We will need your *verbose request/response* then, can you please follow these guides precisely and paste the verbose output and the code you used to reproduce it here in this post?

- https://www.coindesk.com/enterprise-ethereum-alliance-is-forming-a-token-task-force
