### ISSUE TITLE
how to create a margin order on huobipro?

### ISSUE THREAD

**Issue by woshiopqt** [ccxt/ccxt#4586]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/issues/2872#issuecomment-451049294
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

↑ Does that help?

**Comment by woshiopqt** [comment]
exchange.private_post_margin_orders(params={'symbol' : 'bchusdt' ,'currency' : 'bch','price' : 110 ,'amount' : 1 , 'type' : 'buy-limit' , 'source' : 'margin-api'})  
i used this mothed ,it's right ?

**Comment by kroitor** [comment]
@woshiopqt nope, you should use createOrder with proper params-overrides...

```Python
import ccxt
from pprint import pprint
exchange = ccxt.huobipro({
    'apiKey': 'YOUR_API_KEY',    # ←--------------- change for your credentials here
    'secret': 'YOUR_SECRET',
})
exchange.load_markets()
exchange.load_accounts()
margin_accounts = [account for account in this.accounts if account['type'] == 'margin']
print('All margin accounts:')
pprint(margin_accounts)
pprint('-------------------------------------------------------------')
symbol = 'BCH/USDT'
price = 110
amount = 1
side = 'buy'
type = 'limit'
params = {
    'account-id': 'YOUR_MARGIN_ACCOUNT_ID', # ←----- change for your 'margin' accountId here
    'source': 'margin-api,
}
order = exchange.create_order(symbol, type, side, amount, price, params)
pprint(order)
```

Hope it helps )

**Comment by woshiopqt** [comment]
thanks
