### ISSUE TITLE
HitBTC Order creation Failed

### ISSUE THREAD

**Issue by kpchand** [ccxt/ccxt#4587]
Version: ccxt==1.18.188
Language: Python

I create an order with the following parameters:

side = buy
price = 3448.59
symbol = BTC/TUSD
amount = 52.7222

```
self.exchange.create_order(symbol, ord_type, side, amount, price=price)
```

The error is:
ccxt.base.errors.InvalidOrder: hitbtc order was rejected by the exchange {"id":"1548911740564","info":{"orderId":"N/A","latestOrderId":"N/A","clientOrderId":"1548911740564","orderStatus":"rejected","participateDoNotInitiate":false,"userId":"user_3178015","symbol":"BTCTUSD","side":"buy","price":"3448.59","quantity":527222,"type":"limit","timeInForce":"GTC","lastQuantity":0,"lastPrice":"","leavesQuantity":0,"cumQuantity":0,"averagePrice":"0","created":1548911740689,"execReportType":"rejected","orderRejectReason":"orderExceedsLimit"},"timestamp":null,"datetime":null,"lastTradeTimestamp":null,"status":"rejected","symbol":"BTC/TUSD","type":"limit","side":"buy","price":3448.59,"cost":181817.251698,"amount":52.7222,"filled":52.7222,"remaining":0.0,"fee":{"cost":null,"currency":"TUSD","rate":null}}

As can be been that the quanity is being sent as 52722 instead of 52.722. I am assuming that it's dividing/multiplying by the lots? If so, the new version of HitBTC API docs doesn't mention this.

**Comment by kroitor** [comment]
@kpchand can you post your `verbose` output?https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue


```
self.exchange.load_markets()
self.exchange.verbose = True  # ←---------- add before `create_order`
self.exchange.create_order(symbol, ord_type, side, amount, price=price)
```

**Comment by kpchand** [comment]
@kroitor 

Response: POST http://api.hitbtc.com/api/1/trading/new_order?nonce=1548913738926&apikey=myapikey 200 {'Server': 'nginx', 'Date': 'Thu, 31 Jan 2019 05:48:59 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '454', 'Connection': 'keep-alive'} {"ExecutionReport":{"orderId":"N/A","latestOrderId":"N/A","clientOrderId":"1548913738926","orderStatus":"rejected","participateDoNotInitiate":false,"userId":"user_3178015","symbol":"BTCTUSD","side":"buy","price":"3443.29","quantity":519048,"type":"limit","timeInForce":"GTC","lastQuantity":0,"lastPrice":"","leavesQuantity":0,"cumQuantity":0,"averagePrice":"0","created":1548913739072,"execReportType":"rejected","orderRejectReason":"orderExceedsLimit"}}

**Comment by kpchand** [comment]
The arguments this time were:

buy 3443.29 BTC/TUSD 51.9048

**Comment by kroitor** [comment]
@kpchand do you have the same result with `hitbtc2` (v2) instead of `hitbtc` as the exchange class?

**Comment by kroitor** [comment]
@kpchand looks like you can't really buy or sell 50 BTC with hitbtc v1... For that you will need to have the funds on your account. 50 BTC * 3450 = $172500. Are you sure you want to place such a big order? Have you tried any smaller amounts? 1 BTC? 5 BTC? 10 BTC ?

**Comment by cod3gen** [comment]
Looks like api thinks he is trying to sell 519048BTC, and not 50BTC

> D","side":"buy","price":"3443.29","quantity":519048,"type":

**Comment by kroitor** [comment]
@cod3gen that's right, according to their Manual (and it worked previously):

- https://github.com/hitbtc-com/hitbtc-api/blob/master/APIv1.md#neworder

![screen-shot-2019-01-31-at-18 13 25](https://user-images.githubusercontent.com/1294454/52063689-251bcb00-2584-11e9-8c9f-fb43bacea588.jpg)

![screen-shot-2019-01-31-at-18 14 21](https://user-images.githubusercontent.com/1294454/52063695-28af5200-2584-11e9-8fb9-bb419daf17c5.jpg)


@kpchand i'd recommend to try the v2 instead and see if it makes a difference. HitBTC has deprecated the v1 API: https://hitbtc.com/api

Feel free to reopen this issue if it does not help.

**Comment by kpchand** [comment]
Thanks for the help.
Is there a way to make ccxt use HitBTC v2? 
I have observed that some things don't work in the v1. For ex: A market symbol like BCCHTUSD isn't available in v1.

**Comment by kroitor** [comment]
> Is there a way to make ccxt use HitBTC v2?

CCXT supports both... Just use `hitbtc2` instead of `hitbtc` when instantiaing the exchange:

```Python
import ccxt

exchange = ccxt.hitbtc ({ ... })

#  ↑ change this to this ↓

exchange = ccxt.hitbtc2 ({ ... })
```

**Comment by kpchand** [comment]
Thanks a lot for the help.

**Comment by kroitor** [comment]
@kpchand we will be happy if you report back whether switching to `hitbtc2` did solve the issue for you or not )

**Comment by kpchand** [comment]
It did solve it for me. Along with that I also noticed that some symbols like BCCHTUSD are missing from the v1 AP in ccxt but available in v2.

**Comment by kpchand** [comment]
Hi Kroitor, I noticed that I may be wrong. 
It seems like BCHABC and BCHSV are not listed in hitbtc v2 of ccxt.
If I remember correctly, BCHABC/TUSD is represented by BCCHTUSD in hitbtc official API.

**Comment by kroitor** [comment]
Use the search to avoid duplicates ) This has been answered already:

- https://github.com/ccxt/ccxt/issues/4311
- https://github.com/ccxt/ccxt/wiki/Manual#naming-consistency

**Comment by kpchand** [comment]
There is one confusion:
There are two markets in HitBTC: BCH/BTC and BCHABC/BTC (using the exchange names)
So ccxt will convert BCH/BTC to BCH/BTC and BCHABC/BTC to BCH/BTC, so how does one differentiate between the two?

**Comment by kpchand** [comment]
So if I understand correctly, we cannot reference the BCH/USDT market in hitbtc without passing custom args param because ccxt will always convert BCHABC to BCH.
That explains that when I buy BCH/BTC, I get output as BCHABC.

**Comment by kroitor** [comment]
> So if I understand correctly, we cannot reference the BCH/USDT market in hitbtc without passing custom args param because ccxt will always convert BCHABC to BCH.

HitBTC has BCH/USDT for historical reasons ave the BCH/USDT market – the rest of the world, including CoinMarketCap and others have now migrated to BCH ABC, so everybody now calls the new BCH ABC simply BCH. 

Compare volumes here:

- https://api.hitbtc.com/api/2/public/ticker/BCHUSD
- https://api.hitbtc.com/api/2/public/ticker/BCHABCUSD

So, nobody really trades BCH/USDT anymore. We may add a workaround to not overwrite it, but it's pretty much useless at this point.

**Comment by kpchand** [comment]
Thanks mate. HitBTC really confused me here. I will find a workaround for the thing I want to do.

**Comment by kpchand** [comment]
You are awesome for taking the time and helping!

**Comment by Hororohoruru** [comment]
Hello. I have run into a problem when placing a buy order with the HITBTC2 API. The amount is incorrect, but the market does not return a lot amount for me to correct it, like I did with the HITBTC API. What can I do?

This is what I get for the BTC/USDT market in hitbtc2:

    {'percentage': True,
     'tierBased': False,
     'maker': 0.001,
     'taker': 0.002,
     'precision': {'price': 2, 'amount': 5},
     'limits': {'amount': {'min': 1e-05, 'max': None},
      'price': {'min': 0.01, 'max': None},
      'cost': {'min': 1.0000000000000001e-07, 'max': None}},
     'info': {'id': 'BTCUSD',
      'baseCurrency': 'BTC',
      'quoteCurrency': 'USD',
      'quantityIncrement': '0.00001',
      'tickSize': '0.01',
      'takeLiquidityRate': '0.002',
      'provideLiquidityRate': '0.001',
      'feeCurrency': 'USD'},
     'id': 'BTCUSD',
     'symbol': 'BTC/USDT',
     'base': 'BTC',
     'quote': 'USDT',
     'baseId': 'BTC',
     'quoteId': 'USD',
     'active': True}

Whereas in the hitbtc API I get:

    {'percentage': True,
     'tierBased': False,
     'maker': 0.001,
     'taker': 0.002,
     'precision': {'amount': 5, 'price': 2},
     'limits': {'amount': {'min': 1e-05, 'max': None},
      'price': {'min': 0.01, 'max': None},
      'cost': {'min': None, 'max': None}},
     'info': {'symbol': 'BTCUSD',
      'step': '0.01',
      'lot': '0.00001',
      'currency': 'USD',
      'commodity': 'BTC',
      'takeLiquidityRate': '0.002',
      'provideLiquidityRate': '0.001'},
     'id': 'BTCUSD',
     'symbol': 'BTC/USDT',
     'base': 'BTC',
     'quote': 'USDT',
     'baseId': 'BTC',
     'quoteId': 'USD',
     'lot': 1e-05,
     'step': 0.01,
     'active': True}

My best guess is that it is the parameter 'quantityIncrement', but could you confirm? Thank you!

**Comment by kroitor** [comment]
Hi!

> but could you confirm?

Nope, we can't confirm, because the value is there.
That information is stored in `limits`, and this is documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#market-structure
- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

Let us know if that does not help. If you still have difficulties with it, we will need the following from you:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
