### ISSUE TITLE
Question: Is it possible to add a request to the top of the rateLimiter-Queue?

### ISSUE THREAD

**Issue by tommuhm** [ccxt/ccxt#4589]
I currently have a ton of rest requests to download historic data and I would like to add some other requests at the top of the rateLimiter-queue. Is this supported atm? or is there an easy way to achieve such a thing?

**Comment by kroitor** [comment]
Adding requests on top means sending them out of order, right, so you want an out-of-band message to be sent prior to proceeding with other calls. That essentially means that you want to send your requests immediately, without waiting for the queue to flush first. The current built-in rate-limiter implementation is flexible enough for that (we use the tokenBucket algorithm for that), but it currently has no unified interface for controlling that specific behavior, it's a work in progress. 

However, there are possible workarounds:

- override the `.throttle()` method by implementing your rate-limiting logic
- set `enableRateLimit = false` before issuing an oob message, then set it back to `true` immediately after (this effectively overrides the waiting queue, but the downside is that it disables the rate-limiter, so your oob message won't always wait for the next nonce)
- use a second instance of the exchange class with and share a rate-limiter logic between them

Anyways, currently it doesn't have a unified convenient option for oob requests, so it implies adding some custom code on user side. We'll do our best to add more flexibility to it asap. Let me know if that does not answer the question. Thx!
