### ISSUE TITLE
how to repay the margin on huobipro?

### ISSUE THREAD

**Issue by woshiopqt** [ccxt/ccxt#4590]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/FAQ

**Comment by woshiopqt** [comment]
thanks

**Comment by kroitor** [comment]
We need something substantial to be able to help you on this, some of your code that you've tried already, some output from the API, version numbers, pretty much everything that is described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue and in the FAQ. Feel free to reopen this if needed or just ask further questions if any.
