### ISSUE TITLE
WEX is down

### ISSUE THREAD

**Issue by marcuswin** [ccxt/ccxt#4592]

**Comment by kroitor** [comment]
- https://twitter.com/wexnz?lang=en
- https://github.com/ccxt/ccxt/pulls?utf8=%E2%9C%93&q=wex

Yeah, that was pretty much expected... They've been changing mirrors for the past two months, but, apparently, that didn't help...

**Comment by Legogris** [comment]
AFAIK they haven't been up since mid-December.
