### ISSUE TITLE
javascript calls are slow

### ISSUE THREAD

**Issue by Morriz** [ccxt/ccxt#4600]
Hi, I started refactoring my app to use ccxt instead of [kraken-api](https://github.com/nothingisdead/npm-kraken-api). But now I notice almost all my calls take maybe 4x longer than before. I am wondering why. Any suggestions to optimize?

- OS: OSX 10.14.2
- Programming Language version: es6
- CCXT version: 1.18.190
- Exchange: kraken
- Method: fetchMarkets, fetchCurrencies, fetchOrders, fetchMyTrades

**Comment by kroitor** [comment]
Hi! 

Can you plz post 10-20 lines of code for a test-case and define *"slow"* a bit more precisely? ) We need something substantial to start with.

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by Morriz** [comment]
I am sorry to have bothered you, I just set `enableRateLimit` to false and it started going...my bad!

**Comment by Morriz** [comment]
But I want to be able to do bursts of more than 1 request. I can't imagine any dev settling for a timeout of 1 second when the initial load is at least 3 requests. Would be ideal if your throttling would support that. A combination of `rateLimitMax` (number of requests) and `rateLimitInterval` (in seconds) would be sufficient.

**Comment by Morriz** [comment]
Btw, I am using the library client side, so rate limiting should not be such an issue if I don't make a mess in the code...right?

**Comment by kroitor** [comment]
> Would be ideal if your throttling would support that. A combination of rateLimitMax (number of requests) and rateLimitInterval (in seconds) would be sufficient.

It does support that (we use the toketBucket algorithm), and it is specifically designed to handle bursts and variable "costs" heuristics for method calls, but it's not documented yet and requires skills to control it: https://github.com/ccxt/ccxt/issues/1399

> Btw, I am using the library client side, so rate limiting should not be such an issue if I don't make a mess in the code...right?

Yes, however, there's no set up in regard of rate-limits that would be universally-good for all, so the user has to do something with it if he wants to tweak it for his needs. Basically, we are in the process of unifying that aspect as well, so you won't have to bother (hopefully, soon).
