### ISSUE TITLE
fetchMinOrderAmounts is used in wrong location

### ISSUE THREAD

**Issue by Morriz** [ccxt/ccxt#4601]
You scrape the minOrderAmounts nicely fro kraken, but they are per currency, not per pair. As such I would expect them to be populated when I do a call to `fetchCurrencies`, and not in `fetchMarkets`.

- Programming Language version: es6
- CCXT version: 1.18.190
- Exchange: kraken
- Method: fetchMarkets

**Comment by kroitor** [comment]
@Morriz min order amount is actually a property of a market, if you think of it, this is more flexible than having min order amount per currency. 

Some exchanges have min order amount that varies for the same currency in different pairs. It is really a per-market property, not a per-currency property, therefore we load it for markets, not for currencies.

You can't trade (place orders) with a single currency – orders are not compatible with currencies logically. You can trade with a pair of currencies only. In that pair you order one currency for a promise to pay another currency. So min order amount always involves a pair of currencies (logically). And putting min order amount into the currency structure would be a structural mistake that would allow to handle Kraken, but no other exchange. 

We choose to go another way and we have min order amount in the market structure, which covers Kraken as well as the other exchanges, so it's more generic and versatile to have that property in the market structure, not in the currency structure. 

Hope this answers your question, let me know if not.

**Comment by Morriz** [comment]
understood...thanks for another swift reply :)
