### ISSUE TITLE
Rate limit on Upbit?

### ISSUE THREAD

**Issue by lampardlb** [ccxt/ccxt#4604]
Hi, 
Just wondering about this, since it’s not documented on their docs. Do the devs have an idea plz? Thx.

**Comment by kroitor** [comment]
https://docs.upbit.com/v1.0/docs/%EC%9A%94%EC%B2%AD-%EC%88%98-%EC%A0%9C%ED%95%9C

<img width="1393" alt="screen shot 2019-02-03 at 03 32 18" src="https://user-images.githubusercontent.com/1294454/52170918-581cb500-2764-11e9-9c24-72fd56ff8904.png">

**Comment by lampardlb** [comment]
@kroitor, sorry to bother you again - any idea about Bittrex’s rate limit plz? Cheers.
