### ISSUE TITLE
How to exceed the limit of exchanges requests?

### ISSUE THREAD

**Issue by viniciussvl** [ccxt/ccxt#4605]
Hello, is there any way to go beyond the limit of requests that some exchanges have? Is there any way to define which IP will make the request in the exchange? For example, I have a server with 16 different IPs, in PHP I can do this in Binance by passing those IPs in CURLOPT_INTERFACE, so each request uses an IP.

- OS: Windows 10
- Programming Language version: JS
- CCXT version: 1.18.133
- Exchange: Binance
- Method: N/A

**Comment by kroitor** [comment]
> is there any way to go beyond the limit of requests that some exchanges have? 

Yes, tons of different ways, either by controlling the tokenBucket, or by tweaking the rateLimit, or by writing a custom rate limiter, etc... You could have 16 instances of the same exchange each configured to use its own external ip address...

> Is there any way to define which IP will make the request in the exchange?

Yes:

- https://github.com/ccxt/ccxt/issues/3770

Also:

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/issues/1399

Let us know if that does not answer the question.

**Comment by viniciussvl** [comment]
Once again, thank you for the quick reply in the middle of Saturday, it helped me a lot!

> Hi!
> 
> > is there any way to go beyond the limit of requests that some exchanges have?
> 
> Yes, tons of different ways, either by controlling the tokenBucket, or by tweaking the rateLimit, or by writing a custom rate limiter, etc... You could have 16 instances of the same exchange each configured to use its own external ip address...
> 
> > Is there any way to define which IP will make the request in the exchange?
> 
> Yes:
> 
> * #3770
> 
> Also:
> 
> * https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
> * #1399
> 
> Let us know if that does not answer the question.

Once again, thank you for the quick reply in the middle of Saturday, it helped me a lot!
