### ISSUE TITLE
fetch_tickers incorrect placement of base/quote currencies in 'symbol'

### ISSUE THREAD

**Issue by TheLetterJ** [ccxt/ccxt#4606]
I just used fetch_tickers on Bittrex and received ADA/ETH as a symbol. This should be ETH/ADA and is confusing when I have to identify base and quote currencies based on the symbol.

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki/Manual#markets
- https://github.com/ccxt/ccxt/wiki/Manual#market-structure
- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
- https://github.com/ccxt/ccxt/wiki/Manual#naming-consistency
- https://github.com/ccxt/ccxt/wiki/Manual#consistency-of-base-and-quote-currencies

**Comment by kroitor** [comment]
> when I have to identify base and quote currencies based on the symbol

You don't have to, if you follow the guides from the Manual on how to work with symbols, markets and their properties.

**Comment by TheLetterJ** [comment]
So ADA is the base currency of the ETH and ADA pair on Bittrex according to ccxt? That makes no sense.

**Comment by kroitor** [comment]
@TheLetterJ it makes perfect financial sense to the rest of the world, if you take a look at the volumes and prices here and compare them with other exchanges (same pair):

- https://bittrex.com/api/v1.1/public/getmarketsummary?market=ETH-ADA

```
mbp:ccxt igorkroitor$ node examples/js/cli bittrex fetchTicker ADA/ETH
bittrex.fetchTicker (ADA/ETH)
{        symbol:   "ADA/ETH",
      timestamp:    1549239540520,
       datetime:   "2019-02-04T00:19:00.520Z",
           high:    0.0003579,
            low:    0.00035285,
            bid:    0.000354,
      bidVolume:    undefined,
            ask:    0.00035633,
      askVolume:    undefined,
           vwap:    undefined,
           open:    0.00035524,
          close:    0.0003541,
           last:    0.0003541,
  previousClose:    undefined,
         change:    -0.000001140000000000006,
     percentage:    -0.32090980745411724,
        average:    undefined,
     baseVolume:    777028.18087854,
    quoteVolume:    275.57716049,
           info: {     MarketName: "ETH-ADA",
                             High:  0.0003579,
                              Low:  0.00035285,
                           Volume:  777028.18087854,
                             Last:  0.0003541,
                       BaseVolume:  275.57716049,
                        TimeStamp: "2019-02-04T00:19:00.52",
                              Bid:  0.000354,
                              Ask:  0.00035633,
                    OpenBuyOrders:  1320,
                   OpenSellOrders:  1133,
                          PrevDay:  0.00035524,
                          Created: "2017-11-28T17:28:32.077" } }
mbp:ccxt igorkroitor$
```
