### ISSUE TITLE
bitstamp trades only reported as buys

### ISSUE THREAD

**Issue by stabilus** [ccxt/ccxt#4607]
- OS: Win 7 64
- Programming Language version: python 3.6
- CCXT version: 1.18.195
- Exchange: bitstamp
- Method: fetchTrades

trades are returned with side='buy' for all trades. info contains the necessary distinction in the type attribute. type = 1 should be "sell" not buy.

Thanks
Urs

**Comment by stabilus** [comment]
This is still pending, right?

**Comment by kroitor** [comment]
@stabilus yep, will get to it asap.

**Comment by kroitor** [comment]
Fixed by @Legogris in #4310, thanks!
