### ISSUE TITLE
Kraken returns negative balance

### ISSUE THREAD

**Issue by DmitryVil** [ccxt/ccxt#4615]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: windows server 2016
- Programming Language version: python
- CCXT version: 1.18.198
- Exchange: Kraken
- Method: fetchBalance()

Good evening,

Today I noticed that Kraken returns some amounts in its balance as negative.

Thank you in advance

![kraken_balance](https://user-images.githubusercontent.com/35109659/52353988-80880600-2a27-11e9-80bb-bd797782b4bd.PNG)

**Comment by kroitor** [comment]
Hi @DmitryVil ! Can you please post the *verbose output* for it?

```Python
exchange.load_markets()
exchange.verbose = True
exchange.fetch_balance()
```

↑ Copy and paste the entire output in text here, plz. Use triple backticks (&#096;&#096;&#096;) to format the output:

&#096;&#096;&#096;
your output
&#096;&#096;&#096;

**Comment by kroitor** [comment]
Closing this for now until we hear back from you. Feel free to reopen this if needed or just post the verbose request/response in text here / ask further questions if any.
