### ISSUE TITLE
itBit FetchOrder should provide unified response

### ISSUE THREAD

**Issue by gRittyKitty** [ccxt/ccxt#4620]
Currently itBit fetchOrder is providing the raw response from itBit. Bittrex and GDAX filter through parseOrder prior to returning the order information. If I understand correctly, all that needs to be done is to filter through parseOrder.

I've made the change locally and it appears to work appropriately. I've also made a pull request with the changed code. Please be patient, this is the first time I've done a pull request for an open source project.

Please confirm that my analysis is correct and that my code is appropriate.

**Comment by kroitor** [comment]
You analysis is correct, however, it has to be confirmed with itBit docs or tests. It may seem like it does work, but in some cases there are tiny details like missing fields or different field names in the response format (we've seen a lot of that), so we need to make sure that it goes through the parsing chain and generates a correctly parsed orders with as many defined fields as possible. Can you post your *verbose output* for the call? 

```
exchange.verbose = true
exchange.fetchOrder (...)
```

**Comment by gRittyKitty** [comment]
fetch:
 itbit GET https://api.itbit.com/v1/wallets/blah/orders/73f00bf4-b7df-452b-8acf-c44c1fccacd3 
Request:
 { Authorization:
   ‘blah blah blah’,
  'Content-Type': 'application/json',
  'X-Auth-Timestamp': '1549483932164',
  'X-Auth-Nonce': '1549483932164' } 
  

handleRestResponse:
 itbit GET https://api.itbit.com/v1/wallets/blah/orders/73f00bf4-b7df-452b-8acf-c44c1fccacd3 200 OK 
Response:
 { 'Access-Control-Allow-Headers':
   'authorization,content-type,x-auth-nonce,x-auth-timestamp,x-requested-with',
  'Access-Control-Allow-Methods': 'GET,HEAD,PUT,POST,DELETE',
  'Access-Control-Expose-Headers': 'X-Requested-With',
  'Content-Type': 'application/json; charset=utf-8',
  'X-Ratelimit-Limit': '20000',
  'X-Ratelimit-Remaining': '19998',
  'X-Ratelimit-Reset': '1549483992',
  Vary: 'Accept-Encoding',
  'Content-Encoding': 'gzip',
  'Content-Length': '280',
  Date: 'Wed, 06 Feb 2019 20:12:12 GMT',
  Connection: 'close',
  'Content-Security-Policy':
   "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' data: *.hubspot.net *.itbit.com *.hs-analytics.net *.hsforms.net *.hs-scripts.com *.desk.com *.newrelic.com *.linkedin.com *.twitter.com *.facebook.com *.hsleadflows.net *.hubspot.com *.hsstatic.net *.interssl.com *.geotrust.com *.jquery.com oss.maxcdn.com *.googleapis.com *.google-analytics.com *.googleadservices.com *.google.com https://chart.googleapis.com/chart https://www.google.com/ads https://fonts.googleapis.com/ https://fonts.gstatic.com/ https://themes.googleusercontent.com/ *.googleusercontent.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ *.cloudflare.com; img-src 'self' data: *.interssl.com *.geotrust.com *.jquery.com oss.maxcdn.com stats.g.doubleclick.net *.google-analytics.com *.googleadservices.com *.google.com https://chart.googleapis.com/chart https://www.google.com/ads https://fonts.googleapis.com/ https://fonts.gstatic.com/ https://themes.googleusercontent.com/ *.googleusercontent.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ *.cloudflare.com; style-src 'self' 'unsafe-inline' *.hubspot.net *.itbit.com *.hs-analytics.net *.hsforms.net *.hs-scripts.com *.desk.com *.newrelic.com *.linkedin.com *.twitter.com *.facebook.com *.hsleadflows.net *.hubspot.com *.hsstatic.net *.interssl.com *.googleapis.com *.jquery.com oss.maxcdn.com stats.g.doubleclick.net *.google-analytics.com *.googleadservices.com *.google.com https://chart.googleapis.com/chart https://www.google.com/ads https://fonts.googleapis.com/ https://fonts.gstatic.com/ https://themes.googleusercontent.com/ *.googleusercontent.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ *.cloudflare.com; child-src 'self' *.interssl.com *.jquery.com oss.maxcdn.com stats.g.doubleclick.net *.google-analytics.com *.googleadservices.com *.google.com https://chart.googleapis.com/chart https://www.google.com/ads https://fonts.googleapis.com/ https://fonts.gstatic.com/ https://themes.googleusercontent.com/ *.googleusercontent.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ *.cloudflare.com; frame-src 'self' *.hubspot.net *.itbit.com *.hs-analytics.net *.hsforms.net *.hs-scripts.com *.desk.com *.newrelic.com *.linkedin.com *.twitter.com *.facebook.com *.hsleadflows.net *.hubspot.com *.hsstatic.net *.interssl.com *.paypal.com  *.jquery.com *.google-analytics.com *.googleadservices.com *.google.com https://chart.googleapis.com/chart https://www.google.com/ads https://fonts.googleapis.com/ https://fonts.gstatic.com/ https://themes.googleusercontent.com/ *.googleusercontent.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ *.cloudflare.com; form-action 'self' products.geotrust.com *.interssl.com *.jquery.com *.cloudflare.com; font-src 'self' data: *.hubspot.net *.itbit.com *.hs-analytics.net *.hsforms.net *.hs-scripts.com *.desk.com *.newrelic.com *.linkedin.com *.twitter.com *.facebook.com *.hsleadflows.net *.hubspot.com *.hsstatic.net *.interssl.com interssl.com https://fonts.googleapis.com/ https://fonts.gstatic.com/ https://themes.googleusercontent.com/ *.googleusercontent.com fonts.gstatic.com;",
  'Referrer-Policy': 'no-referrer-when-downgrade',
  'Access-Control-Allow-Origin': '*',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Download-Options': 'noopen',
  'X-Content-Type-Options': 'nosniff',
  'X-Xss-Protection': '1; mode=block',
  'Strict-Transport-Security': 'max-age=15768000 ; includeSubDomains ; preload' } 
 {"id":"73f00bf4-b7df-452b-8acf-c44c1fccacd3","walletId”:”blah”,”side":"buy","instrument":"XBTUSD","type":"limit","amount":"0.00100000","displayAmount":"0.00100000","price":"5.00000000","volumeWeightedAveragePrice":"0.00000000","amountFilled":"0","createdTime":"2019-02-05T19:52:18.9670000Z","status":"cancelled","metadata":{},"clientOrderIdentifier":null} 

{ id: '73f00bf4-b7df-452b-8acf-c44c1fccacd3',
  info:
   { id: '73f00bf4-b7df-452b-8acf-c44c1fccacd3',
     walletId: ‘blah’,
     side: 'buy',
     instrument: 'XBTUSD',
     type: 'limit',
     amount: '0.00100000',
     displayAmount: '0.00100000',
     price: '5.00000000',
     volumeWeightedAveragePrice: '0.00000000',
     amountFilled: '0',
     createdTime: '2019-02-05T19:52:18.9670000Z',
     status: 'cancelled',
     metadata: {},
     clientOrderIdentifier: null },
  timestamp: 1549396338967,
  datetime: '2019-02-05T19:52:18.967Z',
  lastTradeTimestamp: undefined,
  status: 'cancelled',
  symbol: 'BTC/USD',
  type: 'limit',
  side: 'buy',
  price: 5,
  cost: 0,
  amount: 0.001,
  filled: 0,
  remaining: 0.001,
  fee: undefined }

**Comment by kroitor** [comment]
@gRittyKitty yep, looks like we'll be ok ) Thx!
