### ISSUE TITLE
nova create order not enough balance

### ISSUE THREAD

**Issue by hbus12** [ccxt/ccxt#4622]
- OS: CentOS 
- Programming Language version: PHP7+
- CCXT version: 1.18.198
- Exchange: nova
- Method: create_order / create_limit_order

Having some troubles creating a limitorder on novaexchange. It is giving me this error:
nova {"message":"Not enough balance for the wanted trade.","status":"error"

function i'm trying:
create_limit_order(EFL/BTC, buy, 3557.14915838, 0.00000872)

the create_order() is giving me the same problems.

BTW: The balance is not the problem. Got 2 BTC there, this trade would take 0.031 BTC. Selling gives me the same problem. Could be a problem on nova's side also.

**Comment by kroitor** [comment]
Need your *verbose request/response output* for that:

```PHP
$exchange->load_markets();
$exchange->verbose = true;
$exchange->create_limit_order('EFL/BTC', 'buy', 3557.14915838, 0.00000872);
```

**Comment by kroitor** [comment]
Closing this until we have a followup with verbose request/response on this issue from you. Feel free to ask further questions, if you have any.

**Comment by dotai2012** [comment]
Hi, I had the same issue :( :

`fetch:
 nova POST https://novaexchange.com/remote/v2/private/trade/LTC_OCUL/?nonce=1560821262
Request:
 { 'Content-Type': 'application/x-www-form-urlencoded' }
 apikey=xxxxxxxxxxxxx&signature=WHv4gDIsEuQIiJMJqZEfSCCgRwFatwSNTtymSPF8iSxg7fi0D5%2B2y%2Fs8gWtjvvz0YlLfaoVQZCoYC3L37yjYVw%3D%3D&tradetype=BUY&tradeamount=1.6464866&tradeprice=0.00000004&tradebase=1

handleRestResponse:
 nova POST https://novaexchange.com/remote/v2/private/trade/LTC_OCUL/?nonce=1560821262 200 OK
Response:
 { 'Cf-Ray': '4e897b611fced203-HKG',
  Connection: 'close',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json',
  Date: 'Tue, 18 Jun 2019 01:27:38 GMT',
  'Expect-Ct':
   'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Set-Cookie':
   '__cfduid=dcc8e8e2a8b0ad3401e7d15e26a81e1661560821258; expires=Wed, 17-Jun-20 01:27:38 GMT; path=/; domain=.novaexchange.com; HttpOnly; Secure, session=f14aab15-050f-4d3c-9728-67aa4295f0ed; Domain=.novaexchange.com; Expires=Tue, 18-Jun-2019 11:27:38 GMT; HttpOnly; Path=/; secure; HttpOnly',
  'Strict-Transport-Security': 'max-age=15552000; preload',
  'Transfer-Encoding': 'chunked',
  Vary: 'Accept-Encoding',
  'X-Frame-Options': 'SAMEORIGIN' }
 {"message":"Not enough balance for the wanted trade.","status":"error"}`

**Comment by dotai2012** [comment]
I guess it is because of "tradebase"

Note: from Nova Api docs:

> tradetype: BUY or SELL
> tradeamount: 8000.00000000
> tradeprice: 0.00000008
> tradebase: 0 (Set as 0 for market currency or 1 for basecurrency as tradeamount)

**Comment by kroitor** [comment]
@dotai2012 we always use the base currency for the amount, as explained here: 

- https://github.com/ccxt/ccxt/wiki/Manual#order-structure
- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders

So it requires 0.000019283054021 LTC to buy 482.07635052 OCUL. Make sure you have that much quote currency (LTC) on your balance.
