### ISSUE TITLE
Coinfloor support for ETH/GBP ticker

### ISSUE THREAD

**Issue by lukewestoby** [ccxt/ccxt#4623]
Coinfloor now supports ETH/GBP - could this be added to possible tickers for the public HTTP call?

https://blog.coinfloor.co.uk/post/182606456091/coinfloor-lists-ethereum-to-pound-sterling-pair

- OS: https://aws.amazon.com/amazon-linux-ami/2018.03-release-notes/
- Programming Language version: python 2.7
- CCXT version: 1.10.579
- Exchange: coinfloor
- Method: exchange.fetch_ticker( "ETH/GBP" )

**Comment by kroitor** [comment]
It has been added in 1.18.207. Thx for reporting!

**Comment by lukewestoby** [comment]
Works like a dream. Thanks for such quick turnaround and sorry I didn't
pull request it to you myself!

Luke
