### ISSUE TITLE
Error running the build (flake8)

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#4624]
Did the build change recently?

`FileNotFoundError: [Errno 2] No such file or directory: '...ccxt.fork/python/.tox/qa/bin/flake8': '.../ccxt.fork/python/.tox/qa/bin/flake8'
`

**Comment by kroitor** [comment]
> Did the build change recently?

Not really... Can you elaborate?

**Comment by npomfret** [comment]
Um, also not really.  When I used to run `npm run build` it worked fine.  Nothing that I know of on my side has changed.  And now I reliably get this error about flake8.

**Comment by kroitor** [comment]
> And now I reliably get this error about flake8.

Need some more output at the very least, namely, this can be related to the version change in some of the underlying dependencies... Can you `pip list` and paste some more output around the error?

**Comment by kroitor** [comment]
Also, if you `python -m pip install --upgrade` before trying a clean install – does that help?

**Comment by npomfret** [comment]
```
python -m pip install
/usr/bin/python: No module named pip

```

**Comment by kroitor** [comment]
@npomfret we will be resolving this for many years if you will be posting one line at a time ) Obviously, we need much more – your version numbers for python, pip, all the packages, the OS, all that... And as much of the output as you can show, not just one line with an error statement.

**Comment by npomfret** [comment]
Apologies, I just ran the command you said and pasted the only line of output.


I found the problem anyway.  I needed to upgrade _tox_ (from 3.3.0 to 3.7.0).

**Comment by kroitor** [comment]
@npomfret thx for reporting back! Appreciate it!

**Comment by npomfret** [comment]
Ugh, this `tox` thing went wrong again today after updating homebrew.  I had to run `brew reinstall tox` to get it working.
