### ISSUE TITLE
Exposing exchanges "metadata" (currently added through "describe")

### ISSUE THREAD

**Issue by AoDev** [ccxt/ccxt#4625]
It would be useful to have the **exchanges "metada"** exposed at class or module level.
This data is currently available only by creating an instance of an exchange client and is encapsulated in the "describe function".

I can help with a PR once we have defined how it should look like.

**Example use case**
I'd like to be able to create a whitelist of urls for a proxy to fix the CORS issue.
I'll probably publish the proxy as open source.

Something like: 

```javascript
ccxt.exchanges.reduce((whitelist, exchange) => {
    if (!exchange.has.CORS) {
       addApiUrlsToWhitelist(whitelist)
    }
    return whitelist
}, [])
```

**Comment by ttodua** [comment]
closed in favor of https://github.com/ccxt/ccxt/issues/6772
