### ISSUE TITLE
Bitmex.py: convert ohlcv data to float

### ISSUE THREAD

**Issue by hroff-1902** [ccxt/ccxt#4626]
It's stated in the manual (OHLCV Structure section) that components of ohlcv are to be floats. For BitMEX, however, the 'value' is always integer, OHLC components are also integers frequently (since the minimal price increment is 0.5 at this exchange).

Implement conversion to float for all OHLCV data in fetch_ohlcv() in bitmex.py, similar to as it's done in kraken.py.

TA-lib indicators require floats (doubles) and fail without conversion. It's better to make this conversion right in ccxt since manual states these values should be float.

maybe safe_float() from base/exchange.py should be used instead of float()...

**Comment by kroitor** [comment]
Your PRs are welcome! 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

;)

**Comment by frosty00** [comment]
yeah a `.map` to float here would be cool. Will add it when i have time.

**Comment by kroitor** [comment]
@frosty00 let's make sure it's not literally a call to `.map`, though, six `safeFloat`s will work much better )
