### ISSUE TITLE
Does the JS version using KeepAlive, i.e. keep connections open if there are none queued?

### ISSUE THREAD

**Issue by runvnc** [ccxt/ccxt#4628]
This is related to Node.js/JavaScript only and the question is about the latest CCXT version.  I am wondering if the connections to APIs are persistent in any way, for example with a KeepAlive option for an Agent (https://nodejs.org/api/http.html#http_new_agent_options).  I think that it uses `node-fetch` so then it would do whatever `node-fetch` does (depending on how its configured)?

**Comment by kroitor** [comment]
> I think that it uses `node-fetch` so then it would do whatever `node-fetch` does (depending on how its configured)?

Exactly. Basically, you've answered your question yourself ) See an example here: https://github.com/ccxt/ccxt/issues/3770. Let us know if that doesn't help.

**Comment by runvnc** [comment]
I'm not asking you to re-open this but I guess I was hoping for a hint about what would happen with `node-fetch` with the normal configuration used by ccxt with exchange APIs.  In case anyone else searches for something similar: from my initial investigation, it seems like in normal circumstances there isn't any special ccxt config for `node-fetch` and it comes down to the headers sent by the exchange like the `connection:` header and what the exchange actually does. In most circumstances what I _think_ is happening is connections are being held open for a short period and you may often end up re-using a connection depending upon the exchange's server's settings and how long its been since you sent a request.

**Comment by kroitor** [comment]
> it seems like in normal circumstances there isn't any special ccxt config

That's correct.

> In most circumstances what I _think_ is happening is that header makes it so connections are being held open for a short period and you may often end up re-using a connection depending upon the exchange's server's settings and how long its been since you sent a request.

That's right, and this is how keep-alive headers work.

CCXT will not configure it for you, but it will provide all the necessary means for you to enable and configure that:

```JavaScript
const ccxt = require ('./ccxt')
    , https = require ('https')

// custom source IPs...
const ip1 = '192.168.0.1' 
const ip2 = '192.168.0.2'

// keep-alive
keepAlive = true

// other options
// ...

const exchange1 = new ccxt.binance ({ agent: new https.Agent ({ localAddress: ip1, keepAlive }) })
const exchange2 = new ccxt.binance ({ agent: new https.Agent ({ localAddress: ip2 }) })
```

**Comment by runvnc** [comment]
Thank you for pasting that example from the other thread. I did see it.  From looking at a `node-fetch` issue and the behavior of my systems, what I believe is happening is `node-fetch` sees a Keep-Alive in a response Connection header and so usually keeps it alive, without any config on my side.  I think the HTTP servers are set up that way because new connections are expensive for them also. I may do some testing to verify that is the case with some APIs and see what the typical timeouts are.

**Comment by kroitor** [comment]
@runvnc you might be interested in HTTP/2 as well – it is far more advanced in terms of connection management and more and more exchanges add support for that.

**Comment by darciusal16** [comment]
this approach stopped working after upgrading the nodejs from v16 to v18.  wondering what should we do instead
