### ISSUE TITLE
historic trades broken for binance - aggTrades vs trades

### ISSUE THREAD

**Issue by tommuhm** [ccxt/ccxt#4635]
A recent change switched the rest endpoint `fetchTrades` for the binance exchange from `aggTrades` to `trades` see: https://github.com/ccxt/ccxt/issues/4618

This change breaks any historic dataloader for binance since `trades` only supports the last 1000 trades.

Is there any advantage of using `trades` over `aggTrades`?, `aggTrades` only aggregates trades for the same order and the same timestamp which should not really matter for the user of the ccxt library.

**Comment by kroitor** [comment]
> Is there any advantage of using `trades` over `aggTrades`?

Yes, as explained in #4618 the `aggTrades` don't have a real trade `id` so you can't match that with a live feed of public trades whether you receive it over REST or WS. `aggTrades` has an aggregate `id` instead.

However, we have saved an option that allows you to switch from one to another, so you can add that to switch back to the old behavior, like so:

```JavaScript
const exchange = new ccxt.binance ({
    'options': {
        'fetchTradesMethod': 'publicGetAggTrades',
    },
})
```

Let us know if that does not help.

**Comment by tommuhm** [comment]
Thanks this helps alot!

Regarding the live feed: there is also a `aggTrades` live feed for rest and ws.

**Comment by kroitor** [comment]
Due to a bug in #4643 the default was reverted back to aggregate trades as version 1.18.224 – this will allow to fetch historical trades by a time-range (to align it with the rest of exchanges):

```JavaScript
const exchange = new ccxt.binance ({
    'options': {
        'fetchTradesMethod': 'publicGetAggTrades', // default
        // 'fetchTradesMethod': 'publicGetTrades', // non-default
    },
})
```

**Comment by caiusCitiriga** [comment]
> Thanks this helps alot!
> 
> Regarding the live feed: there is also a `aggTrades` live feed for rest and ws.

@kroitor how can I configure ccxtPro to use the `aggTrades` live feed instead of the default one? 😊

**Comment by caiusCitiriga** [comment]
> > Thanks this helps alot!
> > Regarding the live feed: there is also a `aggTrades` live feed for rest and ws.
> 
> @kroitor how can I configure ccxtPro to use the `aggTrades` live feed on Binance instead of the default one? 😊 I've been able to configure it for the `fetchTrades` method, but I'm not sure on how to do it on the WS part 😞

I think I've figured it out... By watching the source code I've noticed that we can pass an object like this when instantiating the exchange:

```
'watchTrades': {
    'name': 'trade', // 'trade' or 'aggTrade'
},
```

Am I right?
