### ISSUE TITLE
Gemini fetchMyTrades requires symbol

### ISSUE THREAD

**Issue by gRittyKitty** [ccxt/ccxt#4637]
Most exchanges use fetchMyTrades to obtain trades for all symbols. Gemini does not: a symbol is required. fetchMyTrades ought to behave uniformly for all exchanges.

I've updated Gemini.js in two ways. First, the current fetchMyTrades has become fetchMyTradesBySymbol. I'm reasonably certain that is not a naming convention that will stay but its my initial suggestion. Second, I've created a new fetchMyTrades that iterates over the symbols at Gemini and calls fetchMyTradesBySymbol for each one. 

This may not be ideal behavior as it will send in a number of REST API requests. I looked at the Gemini API specs here. It does indicate to provide a symbol but I have not tested out whether it works without one or not. I do have my own Gemini api js library so I can test it independently, but I may not be able to get to it too soon. 

@kroitor -- please advise if I ought to be raising issues for any/every potential pull request. I have a few more as I'm trying to get uniform access (esp via fetchMyTrades) for the exchanges that I use. Until I hear otherwise, I will raise as an issue first.

**Comment by frosty00** [comment]
Hi @gRittyKitty,

> Most exchanges use fetchMyTrades to obtain trades for all symbols. Gemini does not: a symbol is required. fetchMyTrades ought to behave uniformly for all exchanges.

Nope, sometimes `fetchMyTrades` requires a symbol. If you want to write code that is exchange agnostic you need to provide a symbol. 

>  Second, I've created a new fetchMyTrades that iterates over the symbols at Gemini and calls fetchMyTradesBySymbol for each one.

This is not allowed in the library because it breaks the rule "one request per unified method". The reason for this rule is that it allows people to write async python code that can do other stuff while it is waiting. Having 100 calls in one method would mean python would have to evaluate them all synchronously.

**Comment by gRittyKitty** [comment]
Thanks, @frosty00. Appreciate the explanation of the async. I won't do the pull request.
Is there a way to tell programmatically if fetchMyTrades needs a symbol or gets data for all symbols?

**Comment by kroitor** [comment]
Thx @frosty00 !

@gRittyKitty 

> Is there a way to tell programmatically if fetchMyTrades needs a symbol or gets data for all symbols?

We don't have a full description of the schema yet, but we will have it hopefully soon. In the meantime the method will throw an `ArgumentsRequired` exception if it needs a symbol, so, you can catch that exception and try with a symbol then.

```JavaScript
let trades = undefined
try {
    trades = await exchange.fetchMyTrades ()
} catch (e) {
    if (e instanceof ccxt.ArgumentsRequired) {
        trades = await exchange.fetchMyTrades (symbol)
    } else {
        throw e
    }
}
```

Hope this helps.

**Comment by jurgenmela28** [comment]
> Thx @frosty00 !
> 
> @gRittyKitty
> 
> > Is there a way to tell programmatically if fetchMyTrades needs a symbol or gets data for all symbols?
> 
> We don't have a full description of the schema yet, but we will have it hopefully soon. In the meantime the method will throw an `ArgumentsRequired` exception if it needs a symbol, so, you can catch that exception and try with a symbol then.
> 
> ```js
> let trades = undefined
> try {
>     trades = await exchange.fetchMyTrades ()
> } catch (e) {
>     if (e instanceof ccxt.ArgumentsRequired) {
>         trades = await exchange.fetchMyTrades (symbol)
>     } else {
>         throw e
>     }
> }
> ```
> 
> Hope this helps.

come on mate, we do not have problem how to handle errors...we want to fetch all them at the same time not by symbol param? any solution

**Comment by kroitor** [comment]
> we want to fetch all them at the same time not by symbol param?

You should forward that question to the API devs of the exchange you're asking about. Because this is a requirement of the underlying exchange API, not a requirement of CCXT. Some exchanges will allow querying without all symbols (all trades) at once, others will not tolerate that and will throw an error.
