### ISSUE TITLE
Bitmex: fix broken fetch_ticker

### ISSUE THREAD

**Issue by hroff-1902** [ccxt/ccxt#4639]
Returning back to: https://github.com/ccxt/ccxt/issues/2928#issuecomment-391559546

fetch_ticker (bid and ask values) was disabled for BitMEX with the "'fetchTickerQuotes': False" option, okay, I found an issue...

However, these values are perfectly available in the instrument data.
See bidPrice and askPrice in https://www.bitmex.com/api/v1/instrument?symbol=XBTUSD&count=1&reverse=true

(I would make a Pull Request by myself, probably, but how to make it on github? No problem with making a commit and pulling it from the commandline git, but how to make a PR and link that commit to a new PR? Sorry, too much experience with old cvs etc...)

**Comment by kroitor** [comment]
> I would make a Pull Request by myself, probably, but how to make it on github?

Read this:

1. https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md
2. https://help.github.com/articles/creating-a-pull-request/
3. https://www.google.com/search?q=how+to+pull+request+github

Editing a file in the repository will create a fork of it in your github, after that, you can submit a pull request from your edited for to this repo (github will show that to you). Alternatively, you can fork the repo first, then navigate in your github and add changes to your fork, then submit a pull request.

**Comment by kroitor** [comment]
Related: https://github.com/ccxt/ccxt/pull/4640
