### ISSUE TITLE
Streaming/Real-time public APIs

### ISSUE THREAD

**Issue by flesler** [ccxt/ccxt#464]
Are you by chance considering doing the same thing for the streaming/real-time public APIs? Namely the websockets and sockets APIs. Maybe as a different project.

There's probably less re-utilized code because it's not all HTTP but the APIs are usually just `Trades` and `OrderBook`

**Comment by kroitor** [comment]
Yes, we are doing the same thing for streaming, see here: 

https://github.com/ccxt/ccxt/issues/56
https://github.com/ccxt/ccxt/search?q=websocket&type=Issues&utf8=%E2%9C%93

I would close this issue as a duplicate, if you don't mind. Feel free to reopen it or ask your questions, if any. Thx!
