### ISSUE TITLE
how to get future ohlcv data in huobipro?

### ISSUE THREAD

**Issue by woshiopqt** [ccxt/ccxt#4641]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by kroitor** [comment]
What have you tried already?

**Comment by woshiopqt** [comment]
OK,thanks. I hope to support it soon .

**Comment by hfsam** [comment]
p2p
