### ISSUE TITLE
Method "fetch_trades" is broken to BINANCE...

### ISSUE THREAD

**Issue by kebnekaise-io** [ccxt/ccxt#4643]
- OS: Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
- Programming Language version: Python 3.5.3
- CCXT version: 1.18.223
- Exchange: poloniex (OK) binance (FAIL)
- Method: fetch_trades

Hi! I'm trying to run this code: 

##################################################

def history(exchange_obj, symbol, cutoff=None, hours=1):
    """
    """

    try:
        if cutoff is None:
            cutoff = time()

        t_end = cutoff - cutoff % 60
        t_start = t_end - 3600 * hours
        t_pointer, data = t_start, {}

        while t_pointer < t_end:
            _delay()

            logg()
            logg('web.history.t_pointer = ' + str(t_pointer))

            tmp = {int(d['id']): (
                d['timestamp'] / 1E3,
                [1, -1][d['side'] == 'sell'] * d['amount'],
                d['price']
            )
                for d in exchange_obj.fetch_trades(
                symbol, since=int(1E3 * t_pointer))
            }

            logg()
            logg('web.history.tmp = ' + str(tmp))

            if len(tmp) > 0 and max(tmp) not in data:
                data.update(tmp)
                t_pointer = max(tmp.values())[0]
            else:
                t_pointer = t_end

            logg()
            logg('web.history.data = ' + str(data))

        return np.array([(e, a, p) for t, (e, a, p) in sorted(
            data.items()) if t_start <= e < t_end])
    except:
        logg(format_exc())

##################################################

And it's running fine on POLONIEX, but in BINANCE I'm getting this messages:

(2019.02.10.UTC.16.36.38) Traceback (most recent call last):
  File "/home/trader/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 478, in fetch
    response.raise_for_status()
  File "/home/trader/.local/lib/python3.5/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v1/trades?symbol=ASTETH&startTime=1549557360000&endTime=1549560960000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/trader/bot101/src/include/web.py", line 67, in history
    symbol, since=int(1E3 * t_pointer))
  File "/home/trader/.local/lib/python3.5/site-packages/ccxt/binance.py", line 632, in fetch_trades
    response = getattr(self, method)(self.extend(request, params))
  File "/home/trader/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 373, in inner
    return entry(_self, **inner_kwargs)
  File "/home/trader/.local/lib/python3.5/site-packages/ccxt/binance.py", line 1218, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/trader/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 398, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/trader/.local/lib/python3.5/site-packages/ccxt/base/exchange.py", line 490, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "/home/trader/.local/lib/python3.5/site-packages/ccxt/binance.py", line 1213, in handle_errors
    raise ExchangeError(self.id + ' ' + body)
ccxt.base.errors.ExchangeError: binance {"code":-1101,"msg":"Too many parameters; expected '2' and received '3'."}

**Comment by kebnekaise-io** [comment]
P.S.:
Apparently, this is a problem in the latest versions, because the code runs perfectly in ccxt==1.18.193 (both exchanges).

**Comment by kroitor** [comment]
@kebnekaise-io thx for reporting, that was a bug introduced in #4618, it should work fine as of 1.18.224. We will be happy if you let us know whether it resolved the issue for you or not. Thx!

**Comment by kebnekaise-io** [comment]
Oh, now it's working perfectly. Thank you!
