### ISSUE TITLE
Problem with: const ccxt = require('ccxt');

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#4644]
- OS: Windows 10
- Programming Language version: Visual Studio 2017 (Universal Windows Javascript App)
- CCXT version: #465
- Exchange: Bitfinex
- Node.js 11.9.0 installed
- Method: const ccxt = require('ccxt');

Hello!

I succeed to return all exchanges in chrome console with below code:
console.log(ccxt.exchanges);

But I think that I don't want to run the library in a browser. But instead in Visual Studio Debugger.
Now comes the problem. When I run it in the debugger instead and NOT in a browser, I receive below commented error. 

So const ccxt = require('ccxt'); seems to have a problem here because 'require' is not defined somehow. I don't know how to implement this correctly?
Please see more comments in the code snippets below.

                //const Exchange = require('./js/base/Exchange')
                //Unhandled exception at line 33, column 1 in ms - appx://6b49fdc7-ae95-44f8-9223-0bfbb5025163/ccxt-master/ccxt.js
                //0x800a1391 - JavaScript runtime error: 'require' is not defined
                const ccxt = require('ccxt');

`<body onload="myFunction();">
    <script src="ccxt-master/ccxt.js"></script>
    <script src="js/require.js"></script>
    <script type="text/javascript" src="https://unpkg.com/ccxt"></script>
    <script type="text/javascript">
        function myFunction() {

                //This code returns this error when NOT running in a browser (But running in Visual Studio directly)
                //const Exchange = require('./js/base/Exchange')
                //Unhandled exception at line 33, column 1 in ms - appx://6b49fdc7-ae95-44f8-9223-0bfbb5025163/ccxt-master/ccxt.js
                //0x800a1391 - JavaScript runtime error: 'require' is not defined
                const ccxt = require('ccxt');

                /*-------------------------------------------------------------*/
                //This code returns all exchanges in chrome console
                console.log(ccxt.exchanges);

                /*-------------------------------------------------------------*/
                //This code returns this error in chrome console
                //Access to fetch at 'https://api.bitfinex.com/v1/symbols_details' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin'
                //header is present on the requested resource.If an opaque response serves your needs, set the request's mode to 'no - cors' 
                //to fetch the resource with CORS disabled.
                let exchange = new ccxt.bitfinex();
                exchange.verbose = true;
                console.log(exchange.loadMarkets());
        }
    </script>
</body>`

**Comment by kroitor** [comment]
The non-browser JavaScript version is designed to work within the NPM / Node.js infrastructure, not with Visual Studio, so you need to install `npm` and `node` on your system: https://nodejs.org/en/download/

**Comment by jackpotcityco** [comment]
> The non-browser JavaScript version is designed to work within the NPM / Node.js infrastructure, not with Visual Studio, so you need to install `npm` and `node` on your system: https://nodejs.org/en/download/

I have installed this from that link today already. I have also installed 'npm install ccxt' from the command promt.
So this is installed. I am not sure how you mean. Is it not possible to use Visual Studio for programming in javascript which I do right now. Is something not compatible there?

Can you please tell or explain what the "NPM / Node.js infrastructure" means exactly. How and where will I do the programming in javascript?

**Comment by jackpotcityco** [comment]
I found this link. Is this where the coding should take place when using NPM/Node.js ?

https://www.google.com/search?ei=ndpgXK-oO-qJmwWgxbuQDg&q=how+to+program+in+Node.js&oq=how+to+program+in+Node.js&gs_l=psy-ab.3.0.0j0i22i30l9.8897.13853..14072...2.0..0.147.1962.18j4......0....1j2..gws-wiz.......0i71j0i7i30j0i30j35i39j0i67j0i203j0i20i263.g6fY5Xsi7x0#kpvalbx=1

**Comment by kroitor** [comment]
> Is this where the coding should take place when using NPM/Node.js ?

Yes, basically, you should search for "how to start programming with Node.js" tutorials. The link you posted should help. However, I'd also recommend this one: https://www.google.com/search?q=how+to+node+js+windows

**Comment by jackpotcityco** [comment]
Thank you kroitor, that was a big help. Then I know where to start so I am in the correct environment with all javascript etc.
