### ISSUE TITLE
How will I put ccxt-master folder in relation to my app.js file? (Error: cannot find module 'ccxt')

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#4650]
- OS: Windows 10
- Programming Language version: 6.5.0
- CCXT version: #465
- Exchange: Get all exchanges
- Node.js 11.9.0 installed
- Method: const ccxt = require('ccxt'); console.log (ccxt.exchanges);

Hello!

I am getting started with the Node.js. I try to execute the first command to show all exchanges to know I set everything up correctly.

**var ccxt = require ('ccxt')
console.log (ccxt.exchanges) // print all available exchanges**

However in cmd, I get an error here: "Error: cannot find module 'ccxt'". I am not sure I have all files in correct places. I am not sure that the app.js file finds the library files correctly. 

**How will I put the app.js file(_my programming file_) in relation to ccxt-master folder?**

**1. app.js is the file containing the code. 
2. app.js is located like this: C:\Users\Andreas\Desktop\NODE\ccxt-master\app.js**

**This image shows how I have put the library and app.js which contains my code/application:**
![image](https://user-images.githubusercontent.com/47510843/52603025-3d81c480-2e65-11e9-996c-cd38dd917aba.png)

Thank you!

**Comment by kroitor** [comment]
> I am not sure I have all files in correct places. I am not sure that the app.js file finds the library files correctly.
> **How will I put the app.js file(_my programming file_) in relation to ccxt-master folder?**

1. create a new directory for your project `mkdir myproject`
2. go inside that directory `cd myproject`
3. initialize the npm project `npm init` + follow the instructions on the screen
4. after initialization, install ccxt: `npm install ccxt`
5. once ccxt is installed, create your main file in your project folder `echo '"" index.js`
6. add this code to that file, save and close:
```JavaScript
var ccxt = require ('ccxt')
console.log (ccxt.exchanges)
```
7. from your project folder run you main file: `node index.js`

More about it: https://docs.npmjs.com/using-npm-packages-in-your-projects

Let us know if that does not help.

**Comment by jackpotcityco** [comment]
Thank you

I am not sure what to do on this step:
"3. initialize the npm project `npm init` and follow the instructions on the screen"

As seen in the cmd prompt I have 'npm init' and got this information. I tried both below commands but they didn't do anything. It is a bit unclear what to do there I think?
- npm install <pkg>
- npm install ccxt

![image](https://user-images.githubusercontent.com/47510843/52604743-6fe2f000-2e6c-11e9-91bb-4f342db4a974.png)

**Comment by kroitor** [comment]
> As seen in the cmd prompt I have 'npm init' and got this information. I tried both below commands but they didn't do anything. It is a bit unclear what to do there I think?

When you type `npm init` it will ask a few questions, you can ignore that safely for now and just hit `enter` until it stops asking and returns you back to the shell prompt. ) Hitting the enter button is the same as "accepting the default setting".

**Comment by jackpotcityco** [comment]
> > As seen in the cmd prompt I have 'npm init' and got this information. I tried both below commands but they didn't do anything. It is a bit unclear what to do there I think?
> 
> When you type `npm init` it will ask a few questions, you can ignore that safely for now and just hit `enter` until it stops asking and returns you back to the shell prompt. ) Hitting the enter button is the same as "accepting the default setting".

That was great. This worked out very well :)
Thank you very much for your help kroitor!

![image](https://user-images.githubusercontent.com/47510843/52605328-a588d880-2e6e-11e9-9f2b-12019ea1305b.png)
