### ISSUE TITLE
 Kraken Av Balances api are showing the total balance on Kraken, not the available balance.

### ISSUE THREAD

**Issue by gj315** [ccxt/ccxt#4651]
- OS: Ubuntu
- Programming Language version: Node.js (9.9.0)
- CCXT version:1.17.498
- Exchange: Kraken
- Method: POST
The Kraken Av Balances are showing the total balance on Kraken, not the available balance.

**Comment by kroitor** [comment]
@gj315 need your *verbose request/response*, as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by kroitor** [comment]
@gj315

```JavaScript
'use strict'
const ccxt = require ('ccxt')
console.log ('CCXT v.', ccxt.version)
const exchange = new ccxt.kraken ({
    'apiKey': 'YOUR_API_KEY', // don't show this
    'secret': 'YOUR_SECRET', // don't show this
    'enableRateLimit': true, // as required in the Manual
})
;(async () => {
    await exchange.loadMarkets ()
    exchange.verbose = true
    const balance = await exchange.fetchBalance ()
}) ()
```

**Comment by kroitor** [comment]
@gj315 I'd recommend to update to the most recent version first. Let us know if that or the above does not help.
