### ISSUE TITLE
create standard objects

### ISSUE THREAD

**Issue by frosty00** [ccxt/ccxt#4652]
The list of standardised fields is growing quickly. This issue serves to discuss how we should go about populating all fields in the standard structure. 

`parseX` functions could return

```
return this.deepExtend (defaultTransaction, {
    'amount': 12.3,
})
```

* is there any reason to *not* change to this style?
* where should we store standard objects?

a standard object is the just the expected object but with `undefined`/ empty container type for all it's fields.

**Comment by frosty00** [comment]
another benefit to doing this is that if we decide to change X structure it should change everywhere

**Comment by kroitor** [comment]
> * is there any reason to _not_ change to this style?

To me this is a strong argument for changing to this style:

> another benefit to doing this is that if we decide to change X structure it should change everywhere

I agree, this is more convenient in regard of new fields. So, +1 for **ease of adding new fields and massive updates**. And in terms of automated testing, it simplifies consistency on the user end, so +1 for **consistency**. 

However, I also see these reasons not to do this:

- -1 for **speed**: If we do `return this.deepExtend (defaultTransaction, { 'amount': 12.3 })` from inside each object being parsed, then, we're introducing a loop into every call to a `parse*` method, which makes all the call chain much slower and, what's more important, that effectively raises the requirements for ram, especially if you're running, say, a few dozens of exchange classes on each node of your system.
- -1 for **completeness**: To me making those declarations of unified structures implicit means more errors in contributions or more incomplete contributions – if it is not required to list them all out and list all their values, including the undefined ones, then the devs will tend to skip as much as they can defaulting to the predefined values, and we don't really want to have a lot of "partial implementations", our goal is to be as complete as possible. I would rather restrict those rules even further to stop producing new incomplete implementations.
- -1 for **ease of maintenance**: The structure is easier for keeping in mind, understanding and editing if all of it is on the same screen. Despite that this might seem like an insignificant point, it becomes really critical when it comes to merging code written by a lot of different people.

As an alternative solution, we could also add a quick script to check and validate those structures for consistency and even highlight them in transpile-time, before actually transpiling them. We would still use regexes to do massive adjustments to the code for updates, but doing consistency in transpile-time would help save the mem and speed.
