### ISSUE TITLE
Trying to load markets for Kraken

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#4654]
* OS: Windows 10
* Programming Language version: 6.5.0
* CCXT version: #465
* Exchange: Kraken
* Node.js 11.9.0 installed
* Method: kraken.load_markets ()

Hello!

I have set up everything and are able to load exchanges. 

I am now trying to follow the manual to load the markets for the kraken exchange but receive an error in CMD.
**- TypeError: require(...) is not a function**
I have attached a screenshot to show the complete scenario. I wonder what could be wrong?
(The command I do in cmd is in the red triangle)

Thank you

![image](https://user-images.githubusercontent.com/47510843/52649701-0f45c880-2ee9-11e9-9f41-28d773a6532d.png)

**Comment by jackpotcityco** [comment]
I noticed that I should have a ";" after the first line so I beleive it is solved:

`var ccxt = require('ccxt');`

Thank you!

**Comment by kroitor** [comment]
Change your first line to the following two lines (pay attention to each symbol):

```JavaScript
'use strict';
const ccxt = require ('ccxt');
```

P.S.

> I have attached a screenshot

Next time, please, don't post text as screenshots. Post code and text as text and format it for readability as described here (read and follow the guides literally to a word):

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ
- https://guides.github.com/features/mastering-markdown/

**Comment by jackpotcityco** [comment]
Yes I will post code and text next time as you said then. Thanks for that info.

I see, is 'use strict'; only used before declaring an instance of ccxt?

**Comment by kroitor** [comment]
> I see, is 'use strict'; only used before declaring an instance of ccxt?

Not really, 'use strict' is only used as the first line of the file, and isn't related to ccxt. This is a too-general js-programming question to be explained in a short post, basically, `use strict` enables a special syntax substandard of JS. More about it here:

https://www.google.com/search?q=what+is+use+strict+for

**Comment by jackpotcityco** [comment]
That is great, then I follow. I will put that in all .js files I do the programming in then.

Thank you for the link also!
