### ISSUE TITLE
ohlcv structure enhancement: add both open and close timestamps

### ISSUE THREAD

**Issue by hroff-1902** [ccxt/ccxt#4655]
I thought about an issue with Bitmex (it returns closing timestamps for ohlcv candles) and how to workaround it on a most proper manner...

One possibility, as I already stated somewhere, would be adding a marker into the exchange options, something like "candles_are_close_timestamped: True"... This marker is to be specified explicitly somewhere in the manual so that all such exchanges would use same name.

However, I run though APIs of some exchanges and found that a few of them return both timestamps for candles in their REST responses: both open and close timestamps for each candle.

So, another and probably more interesting enhancement seem to be the following: add both close_timestamp and open_timestamp values into ohlcv structure and remove current timestamp value. Exchanges shall fill at least one of them with actual data.

This is easy to implement: at first step, simply rename current 'timestamp' into 'open_timestamp' and all exchanges will fill this field with actual values; change implementation for Bitmex so that it fill the 'close_timestamp' value as intended; finally, if same bahaviour will be found for any other exchange -- make same change into its code; plus for exchanges that return both values, second one may also be filled rather than ignored.

The application using ccxt will then decide by itself, how it handles these two values -- either fill open_timestamp using close_timestamp and timeframe value if it needs so, or simply modify some behaviour without filling second timestamp if it handle it this way.

**Comment by hroff-1902** [comment]
P.S. Another, more lazy possibility: leave 'timestamp' field *but* add 'close_timestamp' field. Allow (in the interface description) exchange fill only one of them.

**Comment by kroitor** [comment]
Let's align the terminology a bit, I think you're talking about the [ticker structure](https://github.com/ccxt/ccxt/wiki/Manual#ticker-structure) (it has ` timestamp` field), not of the [ohlcv structure](https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-structure) (which doesn't have fields, because it's an array). Is that correct?

**Comment by kroitor** [comment]
However, BitMEX indeed serves the closing timestamp in the OHLCV structure, so I'm a bit confused on which one it is you mean )

**Comment by hroff-1902** [comment]
No, I'm talking here on the ohlcv structure. On bitmex, timestamps for candles are closing timestamps. As I seen in the APIs, some exchanges provide both timestamps. Application need to know somehow which one is actually goes with candles for particular exchange to modify its behavior, for example (how it's implemented in the freqtrade), for opening timeframes in candles it could be:
```
if (last_tick_timestamp + timeframe_interval) > now:
    fetch_new_candle()
```
while for closing timestamps in candles:
```
if (last_tick_timestamp) > now:
    fetch_new_candle()
```

One of the approaches to let the application know what timestamps go along with the candles is a global flag in the exchange options which is set for exchanges that provide closing timestamps, while another possibility is as described here -- simply use and fill different fields in the ohlcv structure (or both).

**Comment by hroff-1902** [comment]
I mean, InteractiveBrokers, Metatrader and Oanda return open candle time in ohlcv data, while Ninjatrader -- returns ohlcvs with candle close time. Ccxt currently return ohlcvs with timestamps as it was returned by the exchange. The application interacting with an exchange by means of ccxt may either get unified data or at least have an ability to find out what timestamps are returned in ohlcvs.

There are several approaches, how this unclarity can be eliminated:
* add a common flag for exchanges in describe() indicating what timestamps are returned in the ohlcv;
* specify exactly in the ccxt Unified API manual that ohlcvs returned to the application SHALL contain open timestamps and adjust timestamp for each returned candle in the parse_ohlcv() for particular exchange that will need such adjustment. There may be issues with the "since" parameter in fetchOhlcv()...
* calculate both timestamps (using one returned by the exchange) for each candle and return both to the application in the ohlcv structure (or in the ohlcv list, which is monopenesual...) That's what proposed in this PR...

**Comment by kroitor** [comment]
@hroff-1902 pardon for the delays on my side, i mostly agree with you, just need some time to wrap my head around this problem in order to come up with a good and flexible design that would work for all users... We might also need baseVolume/quoteVolume in ohlcv, and, probably, some other data as well... I will get back to you on this subject asap.

**Comment by hroff-1902** [comment]
Fine, thanks alot.

It may be interesting (and usefull) to run through all the exchanges with their fetch_ohlcv using, say, 1h timeframe and compare the timestamps to find all exchanges that return close timestamps for handles. I've heard somewhere that some exchanges may return timestamps for 1m timeframe that differ from timestamps for longer, 1h or 1d timeframes. Take please this into consideration as well (not sure that there are actually such the exchanges in the list of supported by ccxt...)

**Comment by kroitor** [comment]
@hroff-1902 it has been fixed this way: https://github.com/ccxt/ccxt/issues/5641
