### ISSUE TITLE
New Exchange: Coinbase

### ISSUE THREAD

**Issue by CptanPanic** [ccxt/ccxt#466]
Not a exhange per-se, but you can buy/sell cryptos, and  api seems similar to the GDAX one.  https://developers.coinbase.com/api/v2#introduction

Thanks.

**Comment by kroitor** [comment]
Hi, @CptanPanic ! Coinbase owns GDAX. Your link points to their merchant API, which, as you noted yourself isn't an exchange in common sense. I guess, you should trade with GDAX if you want a trading service from Coinbase... Or do I miss something?

**Comment by blak3r** [comment]
While coinbase isn't a traditional exchange, I think support should be added for fetchBalance and completedTrades... Use case: making a dashboard to show your current balance of crypto coins across all services.

**Comment by kroitor** [comment]
@blak3r we will consider adding support for Coinbase. Thx for the feedback!

**Comment by Bomper** [comment]
@blak3r: I'm working on such a dashboard. Have you seen existing work?

**Comment by blak3r** [comment]
@Bomper see https://github.com/blak3r/crypto-balance it does a bit more than the README example shows.  It pulls transactions from coinbase to calculate your investment amount and get coin balance using the coinbase api.

**Comment by kroitor** [comment]
Reopened due to https://github.com/ccxt/ccxt/issues/1086#issuecomment-357500816

**Comment by jamespfarrell** [comment]
How would i go about implementing this? Do it in JS, then it's transpiled to Python and PHP? Or I need to implement it in 3 languages?

**Comment by kroitor** [comment]
> How would i go about implementing this?

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

> Do it in JS, then it's transpiled to Python and PHP?

Yep )

> Or I need to implement it in 3 languages?

Nope )

**Comment by valourus** [comment]
Any progress on this topic?

Im interested because on gdax the minimun order is 10usd and on coinbase its 2 usd. Thats a big difference :)

**Comment by ccasselman** [comment]
Very interested in this being added too since Coinbase is how most of the US adds fiat to the markets.  It would be great to pull deposits and balances.

**Comment by ezhukovskiy** [comment]
+1

**Comment by rsparrow** [comment]
+1

**Comment by amarvin** [comment]
+1

**Comment by Stas-Buzunko** [comment]
@kroitor @jamespfarrell any update on this?

**Comment by buddylindsey** [comment]
hah I just spent the last 10 minutes looking for coinbase in ccxt. I thought it was already implemented. Would be cool to see this.

That said what would need to be here to have a minimal addition that would be useful so others can help to contribute?

My thought is `loadMarkets`, `fetchBalance`, and maybe `fetchMyTrades`?

**Comment by kroitor** [comment]
@buddylindsey 

> That said what would need to be here to have a minimal addition that would be useful so others can help to contribute?

We usually add this set in an initial integration:

- Public API:
  - fetchMarkets
  - fetchCurrencies (if any)
  - fetchTicker
  - fetchTickers (if any)
  - parseTicker
  - fetchTrades
  - parseTrade
  - fetchOrderBook
  - fetchOrderBooks (if any)
  - fetchOHLCV (if any)
  - parseOHLCV
- Private API:
  - fetchBalance
  - createOrder
  - cancelOrder
  - one of fetchOrder, fetchOrders or fetchOpenOrders

> My thought is loadMarkets, fetchBalance, and maybe fetchMyTrades?

Which methods you want to implement is up to you, we will be happy for all contributions ) Just read our contributing guidelines to make the code transpileable. Though, I'm sure you read them already )

Also, we have started the work on a skeleton for new exchange integrations so to help other coders stick to rules adopted in CCXT. This is on a separate `skeleton` branch. However, this is still a work in progress (not finished yet, done by 20% or so, copypasted from binance and started editing...): https://github.com/ccxt/ccxt/blob/skeleton/examples/js/skeleton.js (wip, just for reference)

**Comment by buddylindsey** [comment]
Okay. I was just thinking maybe some of those might not be available since it is coinbase.

Thanks for pointing me at the skeleton. I wasn't really sure on some of it what was common between most of the exchanges as I have most of my experience looking at gemini and gdax code.

**Comment by ccasselman** [comment]
btw: Coinbase is closing GDax and going to open a full exchange named Coinbase Pro.

**Comment by buddylindsey** [comment]
So I did some reading of a few articles and poked around coinbase pro. As best as I can tell pro is going to be kept separate from coinbase. So we probably need to have a separate exchange file. Also if the doc links are correct then the API is going to be the same as gdax, will probably just change urls you point at.

**Comment by bgins** [comment]
It looks like the the Private API methods for working with orders have not been implemented. Would it be possible to add these methods or is there some constraint specific to Coinbase that would make this infeasible?

**Comment by kroitor** [comment]
@bgins you probably want Coinbase Pro. Coinbase is not an exchange, it's a wallet service with some rich functions. It has been added by request of the users. However, if you want to trade, you want Coinbase Pro, which is in exchange (formerly known as GDAX) belonging to Coinbase now. Let me know if that does not answer your question.

**Comment by bgins** [comment]
@kroitor yep, that makes sense. Thank you for the clarification.
