### ISSUE TITLE
Poloniex fetchOHLCV API changes

### ISSUE THREAD

**Issue by rdbr** [ccxt/ccxt#4660]
The Poloniex `fetchOHLCV` function doesn't work correctly anymore when only specifying a `since` parameter. [returnChartData](https://docs.poloniex.com/#returnchartdata) expects a `start` and `end` parameter. Currently, only the `start` parameter is sent.

When omitting the `end` parameter, multi-megabytes of candle data is returned.

Here is a suggestion for a fix:
```
if (limit !== undefined) {
    request['end'] = this.sum (request['start'], limit * this.timeframes[timeframe]);
} else {
    request['end'] = this.seconds ();
}
```

**Comment by kroitor** [comment]
@rdbr can you please show a short but complete snippet of code (10-20 lines) that does not work as expected? Also, need your CCXT version.

**Comment by rdbr** [comment]
```
import ccxt from 'ccxt';

(async function main () {

  let polo = new ccxt.poloniex({ enableRateLimit: true, verbose: true });
  let since = Date.now() - 60 * 60 * 1000; // 60 minutes

  // Limit 50
  const ohlcv1 = await polo.fetchOHLCV('BTC/USDT', '5m', since, 50);
  console.log(ohlcv1.length);

  // Without limit
  const ohlcv2 = await polo.fetchOHLCV('BTC/USDT', '5m', since);
  console.log(ohlcv2.length);
}) ();
```
