### ISSUE TITLE
No bid/ask prices for Kraken

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#4662]
* OS: Windows 10
* Programming Language version: Node.js
* CCXT version: #465
* Exchange: Kraken
* Node.js 11.9.0 installed
* Method: kraken.load_markets

Hello!

I am trying to run below code for Kraken. But I can't find any bid or ask prices for the symbols. Why is no bid/ask prices shown here for Kraken and how can I do that?

`'use strict';
var ccxt = require('ccxt');

(async () => {
    let kraken = new ccxt.kraken ()
    let markets = await kraken.load_markets ()
    console.log(kraken, markets)
}) ()`

Thank you!

**Comment by kroitor** [comment]
Please, read this:

- https://github.com/ccxt/ccxt/wiki/Manual#price-tickers

```JavaScript
'use strict';
const ccxt = require ('ccxt')

;(async () => {

    const exchange = new ccxt.kraken ({ enableRateLimit: true })
    const tickers = await exchange.fetchTickers ()
    console.log (tickers)

}) ()
```

Let us know if that does not answer your questions.

**Comment by jackpotcityco** [comment]
Thanks Kroitor,

I just got confused I think as I started out some examples with lakeBTC and Kraken where lakeBTC did show bid/ask for the market structure. 

Then I understand and thank you for the code. It looks like I got it working with that code.

Thank you for your help!
