### ISSUE TITLE
Error while placing limit order on HITBTC for BMH/BTC

### ISSUE THREAD

**Issue by gj315** [ccxt/ccxt#4664]
- OS: Ubuntu
- Programming Language version: Node.js (11)
- CCXT version:1.17.498
- Exchange: Hitbtc
- Method: createOrder

exchange=HitBTC
symbol=BMH/BTC
type=limit
side=buy
amount=3252.798082148666
price=0.00000114378

Response -- negative precision is not yet supported

**Comment by kroitor** [comment]
Use `hitbtc2` instead of `hitbtc`.

**Comment by kroitor** [comment]
P.S. I'd also recommend to update the version of CCXT as well, as your version seems a bit outdated.
