### ISSUE TITLE
Kraken Available balance not correct

### ISSUE THREAD

**Issue by gj315** [ccxt/ccxt#4665]
* OS: Ubuntu
* Programming Language version: Node.js (11)
* CCXT version:1.17.498
* Exchange: Kraken
* Method: fetchBalance

request - const exchange = new ccxt.kraken ({
    'apiKey': 'YOUR_API_KEY', 
    'secret': 'YOUR_SECRET', 
    'enableRateLimit': true
});
await exchange.loadMarkets ()
    exchange.verbose = true
    const balance = await exchange.fetchBalance ()

Response -- ETH: {free: 0.03, used: 0, total: 0.03}
free: 0.03
total: 0.03
used: 0

But I have create the new order with amount that order is untouched till now but it's still showing free balance as total ?

**Comment by kroitor** [comment]
Yeah, Kraken does not report distinct values for free and used amounts, just the total, which is also put into `free` in this case. However, we couldn't really put anything else but an `undefined` value there. We will consider changing it to `undefined` in one of the upcoming versions. Let us know if that doesn't answer the question.
