### ISSUE TITLE
Not able to place  limit order for BMH/BTC on HITBTC exchange

### ISSUE THREAD

**Issue by gj315** [ccxt/ccxt#4666]
* OS: Ubuntu
* Programming Language version: Node.js (11)
* CCXT version:1.17.498
* Exchange: Hitbtc2
* Method: createOrder

exchange=HitBTC2
symbol=BMH/BTC
type=limit
side=buy
amount=3252.798082148666
price=0.00000114378

Response -- negative precision is not yet supported

**Comment by kroitor** [comment]
This was fixed in a later version, please update to the most recent one.

Duplicates: https://github.com/ccxt/ccxt/issues?utf8=%E2%9C%93&q=negative+precision
