### ISSUE TITLE
Is it possible to speed up exchange.fetchTickers()

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#4669]
* OS: Windows 10
* Programming Language version: Node.js
* CCXT version: #465
* Exchange: Bitfinex, Binance etc
* Node.js 11.9.0 installed
* Method: exchange.fetchTickers()

Hello!

I just have a general question for: exchange.fetchTickers()
I am doing some tests and exchange.fetchTickers() for 60 exchanges. This can take about 10 minutes before all code has run. I beleive this should depend on that HTTP requests are "slow"?

My question is if there is any solution to speed up this code in Node.js?
I have tried to create 60 threads in parallell but that does not make it faster though.

The approach I use is with the below code. I know that I create files which could take some time (I/O) but apart from that if there is a better approach to this?

I run the program with the command: node workerTickersCreator.js

**Below .js file starts 2 threads where each thread has its own .js file seen after this code:**

**workerTickersCreator.js**
```JavaScript
var cluster = require('cluster');
var threads = 2;

for (var i = 0; i < threads; i++)
{
       //There are 133 exchanges in this loop normally
       if(i == 0) { cluster.setupMaster({ exec: 'workerTickersbinance.js', }); cluster.fork(); }
       if(i == 1) { cluster.setupMaster({ exec: 'workerTickersbitfinex.js', }); cluster.fork(); }
}
```

Above code calls the below 2 other .js files which: "exchange.fetchTickers()"

**workerTickersbinance.js**
```JavaScript
'use strict';
const ccxt = require ('ccxt');

(async () => {
            try{
       const exchange = new ccxt.binance({ enableRateLimit: true })
       const tickers = await exchange.fetchTickers()
       const obj = { tickers }
       const fs = require('fs');
       fs.writeFile("/myproject/markets/binanceTickers.txt", JSON.stringify(obj), function(err) { });
       }catch{}
}) ()
process.exitCode = 1;
```

**workerTickersbitfinex.js**
```JavaScript
'use strict';
const ccxt = require ('ccxt');

(async () => {
            try{
       const exchange = new ccxt.bitfinex({ enableRateLimit: true })
       const tickers = await exchange.fetchTickers()
       const obj = { tickers }
       const fs = require('fs');
       fs.writeFile("/myproject/markets/bitfinexTickers.txt", JSON.stringify(obj), function(err) { });
       }catch{}
}) ()
process.exitCode = 1;
```

Thank you!

**Comment by kroitor** [comment]
Hi!

> I beleive this should depend on that HTTP requests are "slow"?

Most often, this is not the case. It depends on how you set up the rate limiting and how you poll the exchanges in general.

> My question is if there is any solution to speed up this code in Node.js?

Sure. If only we could see the code. Can you make a short but a complete program of 10-20 lines and paste it **precisely and exactly** as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ? It says what you should do, literally. So, when posting an issue you should post your code. It doesn't really work otherwise. We can't guess it from nowhere. So...

Also, note, that the link i posted has other instructions on how you should format the code, and we expect you to follow those instructions literally and precisely. The time it takes to resolve the issue depends on your ability to read and execute the guides, so, mostly depends on you )

Waiting for a followup from you on this )

**Comment by jackpotcityco** [comment]
Yes ofcourse I did edit my first post adding the complete program as simple as I could do it. I have put the code in the "insert code" but I am not sure if the code looks at it should anyway. I hope I have posted this correctly as I have red the guidelines. Otherwise please tell me.

**Comment by kroitor** [comment]
> I have put the code in the "insert code" but I am not sure if the code looks at it should anyway.

There should be three (3) backticks before and after each code block:

---------------------

&#096;&#096;&#096;  
↑ three of them 

your code

↓ three of them
&#096;&#096;&#096;

---------------------

;)

Also, if you add `JavaScript` keyword right after the opening three backticks, it will highlight the code syntax very nicely:

---------------------

&#096;&#096;&#096;JavaScript

your javascript code

&#096;&#096;&#096;

**Comment by jackpotcityco** [comment]
That is great! Thanks now the code looks better :)

**Comment by fqlx** [comment]
I'm not sure if I understand your intent. You need to execute all network requests asynchronously to answer your question.  There was many ways to achieve faster lag time and whole industries are built optimizing trade.  From colocating to stripping down the network  stack to low lag FPGAs. If that interests you I'd suggest reading Dark Pools by Scott Patterson.  If you are trying a HFT approach on major exchanges, you're going to get beat out by trading companies.

**Comment by jackpotcityco** [comment]
That is true, there are many different ways to achieve faster speeds. I normally code in C# and there I know how to create threads correctly to "speed up" the process, not neccessary beat trading companies. 

I simply wonder how to execute my code in my first question faster. It seems that I have not put the code entire correct. I beleive I need to execute the requests asynchronously but are not sure how to put the code in that way?

**Comment by jackpotcityco** [comment]
I did try this code which actually executes the code a lot faster than my original approach above.

I wonder if it is possible to do it even more efficient by open up more ports for HTTP or any other type of bottlenecks when it comes to HTTP requests?

```javascript
'use strict';
const ccxt = require ('ccxt');

(async () => {
            try{
       const exchange = new ccxt.bitfinex({ enableRateLimit: true })
       const tickers = await exchange.fetchTickers()
       const obj = { tickers }
       const fs = require('fs');
       fs.writeFile("/myproject/markets/bitfinexTickers.txt", JSON.stringify(obj), function(err) { });
       }catch{}
}) ();
(async () => {
            try{
       const exchange = new ccxt.binance({ enableRateLimit: true })
       const tickers = await exchange.fetchTickers()
       const obj = { tickers }
       const fs = require('fs');
       fs.writeFile("/myproject/markets/binanceTickers.txt", JSON.stringify(obj), function(err) { });
       }catch{}
}) ();
```

**Comment by fqlx** [comment]
You should use websockets if performance is an issue

**Comment by jackpotcityco** [comment]
I see, can websockets improve the speed of my last posted code and can code be added for websockets to that code. I am not sure how to do this?

**Comment by kroitor** [comment]
@fqlx 

> You should use websockets if performance is an issue

Not in this case. In this case the user should just write a proper code to handle the async calls correctly, – it will take much faster than 10 mins to execute then, 10x faster or even faster than that. 

I will post an example here soon.

**Comment by kroitor** [comment]
@jackpotcityco 

Check out this example:

- https://github.com/ccxt/ccxt/blob/master/examples/js/fetch-all-tickers-to-files.js

```JavaScript
'use strict';

const ccxt      = require ('ccxt')
    , log       = require ('ololog').noLocate // npm install ololog
    , fs        = require ('fs')

    // the numWorkers constant defines the number of concurrent workers
    // those aren't really threads in terms of the async environment
    // set this to the number of cores in your CPU * 2
    // or play with this number to find a setting that works best for you
    , numWorkers = 8

;(async () => {

    // make an array of all exchanges
    const exchanges = ccxt.exchanges

        // filter coinmarketcap and theocean
        // coinmarketcap isn't really an exchange
        // theocean requires web3 dependencies to be installed

        .filter (id => ![ 'coinmarketcap', 'theocean' ].includes (id))

        // instantiate each exchange and save it to the exchanges list

        .map (id => new ccxt[id] ({
            'enableRateLimit': true,
        }))

    // the worker function for each "async thread"
    const worker = async function () {

        // while the array of all exchanges is not empty
        while (exchanges.length > 0) {

            // pop one exchange from the array
            const exchange = exchanges.pop ()

            // check if it has the necessary method implemented
            if (exchange.has['fetchTickers']) {

                // try to do "the work" and handle errors if any
                try {

                    // fetch the response for all tickers from the exchange
                    const tickers = await exchange.fetchTickers ()

                    // make a filename from exchange id
                    const filename = exchange.id + '.json'

                    // save the response to a file
                    fs.writeFileSync (filename, JSON.stringify ({ tickers }));

                    // print out a message on success
                    log.green (exchange.id, 'tickers saved to', filename)

                } catch (e) {

                    // in case of error - print it out and ignore it further
                    log.red (e.constructor.name, e.message)
                }

            } else {

                log.red (exchange.id, "has['fetchTickers'] = false");
            }
        }
    }

    // create numWorkers "threads" (they aren't really threads)
    const workers = [ ... Array (numWorkers) ].map (_ => worker ())

    // wait for all of them to execute or fail
    await Promise.all (workers)

}) ()
```

**Comment by kroitor** [comment]
@jackpotcityco i've tested it on my system and it works and returns within 30 seconds. That's 20 times faster. And it also handles the errors properly.

**Comment by jackpotcityco** [comment]
Thank you for this code. That really executes fast, about 30 seconds here also on my 4 core processor. I do have a server with 24 cores that I will use later and as you say it could be possible to optimize the code even more then.

If I understand async/await in this case "aren't really threads". When optimizing this even more to for example run in about 3 seconds. Are we talking about doing this code approach splitting the work up on different cores using for example "cluster" ?

**Comment by kroitor** [comment]
> Are we talking about doing this code approach splitting the work up on different cores using for example "cluster" ?

Nope, not really... first of, you don't want to add the overhead that you don't completely understand. The mere fact that you're asking this question kinda tells that you don't. In that case, I suggest that you first obtain the necessary skills with modern ES6 JavaScript (find out what is ES6 – that is a big self-educational task already), learn about Promises and how to use async/await. 

You can shrink the execution time down to 3 seconds with proper management of async promises and with a bit smarter caching, so this is possible, if you:

- understand the language very well
- understand the Manual for this lib very well
- understand the examples for this lib very well

I can do that script for you, but if I do – you won't learn as much as you want, really. And tbh, I don't have the time to teach everyone personally, that's physically impossible, hope for your understanding. All I can give is just a clue on where to dig deeper ;)

**Comment by jackpotcityco** [comment]
> I don't have the time to teach everyone personally
Yes I completely understand that I have the same problem with C# to learn everyone. There is no time for that ;)

I am really greatful for where I should start looking in order to learn more about the javascript language and where to dig deeper. It helps to know on what area to focus. Thank you! :)

**Comment by jackpotcityco** [comment]
I have tried to put up another code where I cach as much memories I can think of and then use the cached memories to execute the: exchange.fetchTickers();
I did it with a stopwatch for the for the folder where the files were created and it got more than 50 exchanges in 5.6 seconds.

I might wonder if I have done it more or less correctly or any more idéa can be said?

**1. Cache some memories first
2. Use cached memories to do the "fetchTickers()" as fast as possible**
```javascript
'use strict';
const ccxt = require('ccxt');
const fs = require('fs');
const path = require('path');

//Cache some memories first
var exchangesArray = [];
var exchangesArray2 = [];
(async () => {
  const allexchanges = ccxt.exchanges.filter((id) => !['coinmarketcap', 'theocean'].includes(id))
        .map(async (id) => {
            const Exchange = ccxt[id];
            const exchange = new Exchange({ enableRateLimit: true });
            if (exchange.has['fetchTickers']) {

                exchangesArray.push(exchange);
                exchangesArray2.push(id);
            }
        });

    await Promise.all(allexchanges);
})();




//Cached Memories
const exchanges = exchangesArray; //Holds exchange object
const exchangesnames = exchangesArray2; //Holds exchange name
var i;




//Use cached memories to do the "fetchTickers()" as fast as possible
(async () => {
    console.log(`start`);
    const start = Date.now();


    //Use cached memories to do the "fetchTickers()" as fast as possible
    var tickersPromises = []
    for (i = 0; i < exchanges.length; i++) {

        // pop one exchange from the array
        const exchange = exchanges[i]
        const exchangename = exchangesnames[i]

        try {
            let tickerProcessing = new Promise(async (resolve) => {
                // probably do a try catch in here
                const tickers = await exchange.fetchTickers();
                const dumpFile = path.join(__dirname, 'tickers', `${exchangename}Tickers.json`);
                await fs.promises.writeFile(dumpFile, JSON.stringify(tickers));
                resolve()
            })
            tickersPromises.push(tickerProcessing)

        } catch (e) {
            console.error(e);
        }
    }

    // wait for all of them to execute or fail
    await Promise.all(tickersPromises)


    const end = Date.now();
    console.log(`Done in ${(end - start) / 1000} seconds`);
})();
```
