### ISSUE TITLE
New Exchange - Huobi Russia

### ISSUE THREAD

**Issue by alexeymarunin** [ccxt/ccxt#4672]
ID: huobiru
Name: Huobi Russia
Country: Russia
URL: https://www.huobi.com.ru
API docs: https://github.com/cloudapidoc/API_Docs_en
Logo: https://huobi-1253283450.cos.ap-beijing.myqcloud.com/bb66f5918e_logo.svg
Fee: https://www.huobi.com.ru/ru-ru/about/fee/
Referral: https://www.huobi.com.ru/invite?invite_code=2ph54

REST API baseUrl: `https://www.huobi.com.ru/api/v1/`
WebSocket API baseUrl: `wss://www.huobi.com.ru/api/ws/` 

Exchange has totally the same functionality as [Huobi Pro](http://huobi.pro) except urls above.

I use simple class (Node.js) in our project:
```
class huobiru extends ccxt.huobipro {
  describe() {
    return this.deepExtend(super.describe(), {
      'id':        'huobiru',
      'name':      'Huobi Russia',
      'countries': ['RU'],
      'hostname':  'www.huobi.com.ru',
      'urls':      {
        'logo':     'https://huobi-1253283450.cos.ap-beijing.myqcloud.com/bb66f5918e_logo_footer.svg',
        'api':      {
          'market':  'https://www.huobi.com.ru/api',
          'public':  'https://www.huobi.com.ru/api',
          'private': 'https://www.huobi.com.ru/api',
          'zendesk': 'https://huobiglobal.zendesk.com/hc/en-us/articles',
        },
        'www':      'https://www.huobi.com.ru/ru-ru',
        'referral': 'https://www.huobi.com.ru/invite?invite_code=2ph54',
        'doc':      'https://github.com/cloudapidoc/API_Docs_en',
        'fees':     'https://www.huobi.com.ru/ru-ru/about/fee/',
      },
    })
  }
}
```

**Comment by kroitor** [comment]
I think we should simply parameterize the hostname for huobipro... Like we did with bittrex and bleutrade... @alexeymarunin how does that sound to you?

**Comment by alexeymarunin** [comment]
Ok, let's try it)

**Comment by kroitor** [comment]
@alexeymarunin after taking a closer look, i decided to do it your way, because it has non-interchangeable keys and works like a standalone exchange anyway. Thx for your help!
