### ISSUE TITLE
[Binance] Incorrect `cost` value in parseTrade()

### ISSUE THREAD

**Issue by alexeymarunin** [ccxt/ccxt#4673]
- OS: macOS 10.14.2
- Programming Language version: Node.js v9.10.1
- CCXT version: 1.18.224
- Exchange: Binance
- Method: parseTrade

Seems it's [JS's "feature"](https://stackoverflow.com/questions/9993266/javascript-multiply-not-precise), not ccxt

I have trade:

```json
{
  "info": {
    "symbol": "ETHBTC",
    "id": 72022262,
    "orderId": 176453748,
    "price": "0.07138800",
    "qty": "0.02600000",
    "commission": "0.00045678",
    "commissionAsset": "BNB",
    "time": 1530881610951,
    "isBuyer": true,
    "isMaker": false,
    "isBestMatch": true
  },
  "timestamp": 1530881610951,
  "datetime": "2018-07-06T12:53:30.951Z",
  "symbol": "ETH/BTC",
  "id": "72022262",
  "order": "176453748",
  "takerOrMaker": "taker",
  "side": "buy",
  "price": 0.071388,
  "cost": 0.0018560879999999997,
  "amount": 0.026,
  "fee": {
    "cost": 0.00045678,
    "currency": "BNB"
  }
}
```
It has cost=0.0018560879999999997, but real cost=0.001856088.

Maybe should use `Number.toFixed()` (or similar ccxt-native function):
```js
let cost =(price * amount).toFixed(8)
```

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L272
- https://github.com/ccxt/ccxt/pull/2557

```JavaScript
const exchange = new ccxt.binance ({
    'enableRateLimit': true,
    'options': {
        'parseOrderToPrecision': true,
    }
})
```

;))

**Comment by kroitor** [comment]
Use the search, Luke! ))

**Comment by alexeymarunin** [comment]
Yep, I have `parseOrderToPrecision=true`, but it doesn't matter because cost is calculated directly, without any options

Look https://github.com/ccxt/ccxt/blob/master/js/binance.js#L607
```js
return {
            'info': trade,
            'timestamp': timestamp,
            'datetime': this.iso8601 (timestamp),
            'symbol': symbol,
            'id': id,
            'order': order,
            'type': undefined,
            'takerOrMaker': takerOrMaker,
            'side': side,
            'price': price,
            'cost': price * amount,
            'amount': amount,
            'fee': fee,
        };
```

PS I find your lack of faith disturbing ))

**Comment by kroitor** [comment]
@alexeymarunin oh, that doesn't apply to parseTrade, but I'll add it shortly and will let you know )
