### ISSUE TITLE
zaif fees

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#4675]
@redindian I think you might have been the last person to update the trading frees of zaif exchange (to `'taker': -0.0001, 'maker': -0.0005`).

It looks like these values are no longer correct, see: https://zaif.jp/fee?lang=en - do you agree?

**Comment by redindian** [comment]
Yes, correct, this promo ended. Now they have 0 fees like the links says.

**Comment by npomfret** [comment]
https://github.com/ccxt/ccxt/pull/4679

**Comment by kroitor** [comment]
Merged #4679
