### ISSUE TITLE
Missing Payment ID when withdrawing BCN on Hitbtc

### ISSUE THREAD

**Issue by froseppl** [ccxt/ccxt#4682]
* OS: Debian
* Programming Language version: Python
* CCXT version: 1.18.237
* Exchange: hitbtc (V1 API)
* Method: withdraw

Hi, I've tried to withdraw BCN from my Hitbtc account using the CCXT withdraw method:
`hitbtc.withdraw('BCN', amount, address='BCN wallet address', tag='BCN Payment ID')`.
The transaction shows up in my Hitbtc account correctly but the Payment ID is missing.

I expected that the payment ID should be provided in the 'tag' parameter as stated in the CCXT manual for deposits:
'With certain currencies, like AEON, BTS, GXS, NXT, SBD, STEEM, STR, XEM, XLM, XMR, XRP, an additional argument tag is usually required by exchanges. Other currencies will have the tag set to undefined / None / null. The tag is a memo or a message or a payment id that is attached to a withdrawal transaction. The tag is mandatory for those currencies and it identifies the recipient user account.'

Could you please give any hints how to withdraw BCN correctly?

Thanks! 

Hint: This is a duplicate of Issue #4582 as the bug still exists in CCXT 1.18.237

**Comment by kroitor** [comment]
@froseppl hi! 

Can you post *verbose request/response* output for the withdraw call?

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

```Python
hitbtc.verbose = True
hitbtc.withdraw('BCN', amount, address='BCN wallet address', tag='BCN Payment ID')
```

**Comment by kroitor** [comment]
I suggest moving to `hitbtc2`, the v1 is deprecated and we will drop it soon.
