### ISSUE TITLE
Add fetchBalance on trade account Kucoin2

### ISSUE THREAD

**Issue by calbertuk** [ccxt/ccxt#4684]
At the moment fetchBalance() on Kucoin2 (newly released platform) returns balance from main account with no option to get balance from the trade account. Could this be added please?

**Comment by MarcelBeining** [comment]
+1

**Comment by kroitor** [comment]
@calbertuk you can choose whatever it is:

```JavaScript
fetchBalance ({'type': 'trade'}) // this is the default as of version 1.18.248
```

or

```JavaScript
fetchBalance ({'type': 'main'}) // this is the default prior to version 1.18.248
```

Let us know if that does not help.

**Comment by calbertuk** [comment]
That's perfect, thanks.

**Comment by MarcelBeining** [comment]
Oh, no wonder, on pip, latest version is 1.18.247 ^^
