### ISSUE TITLE
kucoin2 Invalid KC-API-SIGN

### ISSUE THREAD

**Issue by MarcelBeining** [ccxt/ccxt#4685]
- Programming Language version: python3.7
- CCXT version: 1.18.249
- Exchange: kucoin api version 2.0
- Method: fetchOpenOrders and more

On calling that method I get a "kucoin2 Invalid KC-API-SIGN", however the apiKey and secret is correct (created new after the update as all keys had been deleted). Also applied the correct api passphrase password which is now necessary..

**Comment by kroitor** [comment]
@MarcelBeining you're not using a sandbox keypair with the production, right?

**Comment by MarcelBeining** [comment]
No I havent produced any sandbox keypair  :-)

**Comment by MarcelBeining** [comment]
Haha ok, I just saw I used the wrong keypair (the readonly one). However with the right keypair and password I get

> ct.fetchOpenOrders('BTC/USDT')
> Traceback (most recent call last):
> 
>   File "<ipython-input-51-0a5dc934797b>", line 1, in <module>
>     ct.fetchOpenOrders('BTC/USDT')
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\kucoin2.py", line 455, in fetch_open_orders
>     return self.fetch_orders_by_status('active', symbol, since, limit, params)
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\kucoin2.py", line 446, in fetch_orders_by_status
>     response = self.privateGetOrders(self.extend(request, params))
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 373, in inner
>     return entry(_self, **inner_kwargs)
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 402, in request
>     return self.fetch2(path, api, method, params, headers, body)
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 398, in fetch2
>     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 491, in fetch
>     self.handle_rest_errors(e, response.status_code, http_response, url, method)
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 516, in handle_rest_errors
>     self.raise_error(error, url, method, exception if exception else http_status_code, response)
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 383, in raise_error
>     raise exception_type(output)
> 
> ExchangeNotAvailable: kucoin2 https://openapi-v2.kucoin.com/api/v1/orders?symbol=BTC-USDT&status=active GET 502 Server Error: Bad Gateway for url: https://openapi-v2.kucoin.com/api/v1/orders?symbol=BTC-USDT&status=active <html>
> <head><title>502 Bad Gateway</title></head>
> <body bgcolor="white">
> <center><h1>502 Bad Gateway</h1></center>
> <hr><center>openresty</center>
> </body>
> </html>

**Comment by MarcelBeining** [comment]
Hmpf and with

**Comment by kroitor** [comment]
> Something is terribly wrong, could also be kucoin. Do you get similar issues?

Yep, we have reported this and we will keep you updated. KuCoin has just updated the API to Platform 2.0, so, this is probably related, so it might not be stable right away. I will let you know as soon as I get a follow up on this.

**Comment by kroitor** [comment]
@MarcelBeining it does work for me now. The password is the API key password (the password for the keypair), not an API trading passphrase (6 digits).

```
mbp:ccxt igorkroitor$ python3 examples/py/cli.py kucoin2 fetchBalance --verbose

Request: GET https://openapi-v2.kucoin.com/api/v1/accounts?type=main {'KC-API-KEY': '5c6ad928134ab726d08eff05', 'KC-API-TIMESTAMP': '1550508181108', 'KC-API-PASSPHRASE': 'cy7QE9fDDtc2LbrK', 'KC-API-SIGN': b'n5f6+NBfc65XbsMwlZVw9k+kh7ntqIPyDu+5r14abA0=', 'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://openapi-v2.kucoin.com/api/v1/accounts?type=main 200 {'Date': 'Mon, 18 Feb 2019 16:43:01 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=dc15fba80cbc26efc5b3634e3ebcd34591550508181; expires=Tue, 18-Feb-20 16:43:01 GMT; path=/; domain=.kucoin.com; HttpOnly; Secure, X-TRACE=i+qblq60IxiVkrBFRsT4Z9kiOhe+f9mntP40DAUMqGQ=; Path=/, SESSION=MmJiODEwYTctOTAxYi00YWMzLWFlYTEtOTMzODNhNWQ0OGRk; Max-Age=604800; Expires=Mon, 25-Feb-2019 16:43:01 GMT; Path=/; HttpOnly, __cfruid=0eeb15b673bb0a853475bd5439b7fec2b2e10d8b-1550508181; path=/; domain=.kucoin.com; HttpOnly', 'X-TRACE-ID': '9dbf820c684ac901', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Expires': '0', 'X-Frame-Options': 'DENY', 'Strict-Transport-Security': 'max-age=2592000; includeSubDomains; preload', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '4ab1f3441c7dc2f1-FRA', 'Content-Encoding': 'gzip'} {"code":"200000","data":[]}
{'free': {}, 'info': [], 'total': {}, 'used': {}}
mbp:ccxt igorkroitor$ python3 --version
Python 3.6.2
mbp:ccxt igorkroitor$
```

@MarcelBeining what about you?

**Comment by kroitor** [comment]
@MarcelBeining let me know if it doesn't work for you now with the new api keys.

**Comment by RomainBlindy** [comment]
Hello, 
Sorry to bother you,  i have the same type of issue and can't explain why.

`Traceback (most recent call last):
  File "C:\Users\BlindyXXX\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\base\exchange.py", line 478, in fetch
    response.raise_for_status()
  File "C:\Users\BlindyXXX\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error:  for url: https://openapi-v2.kucoin.com/api/v1/accounts?type=main

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Bureau\PYTHON API\tradeArbitrage_kucoin2_tradeogre_LOKI_BTC.py", line 129, in <module>
    Datas[Exch1]['Balance'][Curr1] = Connect1.fetchBalance()["BTC"]["free"]
  File "C:\Users\BlindyXXX\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\kucoin2.py", line 809, in fetch_balance
    response = self.privateGetAccounts(self.extend(request, params))
  File "C:\Users\BlindyXXX\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\base\exchange.py", line 373, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\BlindyXXX\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\base\exchange.py", line 402, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\BlindyXXX\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\base\exchange.py", line 398, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\BlindyXXX\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\base\exchange.py", line 490, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "C:\Users\BlindyXXX\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\kucoin2.py", line 866, in handle_errors
    raise Exception(self.id + ' ' + message)
ccxt.base.errors.AuthenticationError: kucoin2 Invalid KC-API-PASSPHRASE`

I put in "password" the "secret" from the key, in "secret" my 6-digit code for trading on the platform.
Can you help ?
Thanks,

Romain

**Comment by RomainBlindy** [comment]
I've found my error. 
I was confused between passphrase and secret from the key.
Thanks a lot

**Comment by kroitor** [comment]
@RomainBlindy thx for reporting and for the feedback!

**Comment by mablue** [comment]
> I've found my error. I was confused between passphrase and secret from the key. Thanks a lot

me too :))
this exchange have 3 defferent password :|

**Comment by JimLynchCodes** [comment]
hmmm I am using the correct phrases and keys but still getting a "Invalid KC-API-SIGN" message on every call... 🤔

**Comment by kroitor** [comment]
@JimLynchCodes make sure you're not using the login password, and using the API password instead.
