### ISSUE TITLE
 Error: kucoin2 KC-API-KEY not exists

### ISSUE THREAD

**Issue by mattfilippone** [ccxt/ccxt#4688]
- OS: Windows 7
- Programming Language version: node js v8.11.3
- CCXT version: "^1.18.247",
- Exchange: kucoin2
- Method: every one - fetchBalance 

tried to switch over to the new kucoin api today and I can't get it to work.  Upgraded the ccxt version and added the additional password.  The previous version had worked fine with these api key / secret pair prior to the platform upgrade.  please help.

let exchange = new ccxt['kucoin2']({
          'apiKey' : acct_info.apikey,
          'secret' : acct_info.secret,
          'password': acct_info.password,
          'nonce': function() { return this.milliseconds(); },
          'adjustForTimeDifference' : true,
          'recvWindow' : 10000000,
          'useServerTime' : true });

let balance = await exchange.fetchBalance();

**Comment by kroitor** [comment]
@mattfilippone have you re-created the keys? Also, can you post your **verbose request/response**? https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by mattfilippone** [comment]
I did recreate the keys - turns out the issue was I was using the trading passcode not the apikey set password.  so it's working now.  Just a very misleading error message.
