### ISSUE TITLE
Kucoin2 fetch_deposit_address returns NULL

### ISSUE THREAD

**Issue by calbertuk** [ccxt/ccxt#4689]
- OS: Windows
- Programming Language version: PHP
- CCXT version: Latest
- Exchange: Kucoin2
- Method: fetch_deposit_address returns ['address'] => NULL for every currency

**Comment by calbertuk** [comment]
Could be because of issues with their wallets out of sync

**Comment by kroitor** [comment]
@calbertuk can you please post your **verbose request/response** ? https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by calbertuk** [comment]
Okay figured out the issue. If the address hasn't been generated by visiting the site manually and actually going to deposit a coin, then the function returns a success code without the address.

Does that make sense?

**Comment by kroitor** [comment]
> Does that make sense?

It does, but can you post the response structure, though?

**Comment by calbertuk** [comment]
`Request: Array ( [0] => GET [1] => https://openapi-v2.kucoin.com/api/v1/deposit-addresses?currency=NULS [2] => REMOVED [3] => ) Response: Array ( [0] => GET [1] => https://openapi-v2.kucoin.com/api/v1/deposit-addresses?currency=NULS [2] => 200 [3] => [4] => Array ( [date] => Array ( [0] => Mon, 18 Feb 2019 19:16:06 GMT ) [content-type] => Array ( [0] => application/json;charset=UTF-8 ) [transfer-encoding] => Array ( [0] => chunked ) [connection] => Array ( [0] => keep-alive ) [set-cookie] => Array ( [0] => __cfduid=dd93e11f8f3dfd16ffa3b2b76fdd979791550517366; expires=Tue, 18-Feb-20 19:16:06 GMT; path=/; domain=.kucoin.com; HttpOnly; Secure [1] => X-TRACE=JaLZ05cy4/9VmuKCq+G+nqPl58icNHu3tP40DAUMqGQ=; Path=/ [2] => SESSION=M2E3Njc4MzQtNWVkZC00YWFmLWE2ZjAtYmZlNWJkZTFlNTFk; Max-Age=604800; Expires=Mon, 25-Feb-2019 19:16:06 GMT; Path=/; HttpOnly [3] => __cfruid=d6d7ea0999019f2862d597a9369cc7ead72ec0d6-1550517366; path=/; domain=.kucoin.com; HttpOnly ) [x-trace-id] => Array ( [0] => 4aa66df03c272d58 ) [x-content-type-options] => Array ( [0] => nosniff ) [x-xss-protection] => Array ( [0] => 1; mode=block ) [cache-control] => Array ( [0] => no-cache, no-store, max-age=0, must-revalidate ) [expires] => Array ( [0] => 0 ) [x-frame-options] => Array ( [0] => DENY ) [strict-transport-security] => Array ( [0] => max-age=2592000; includeSubDomains; preload ) [expect-ct] => Array ( [0] => max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct" ) [server] => Array ( [0] => cloudflare ) [cf-ray] => Array ( [0] => 4ab2d3828de8bfcc-MAN ) [content-encoding] => Array ( [0] => gzip ) ) [5] => {"code":"200000"} ) array(1) { ["code"]=> string(6) "200000" } array(2) { ["address"]=> NULL ["tag"]=> NULL }  `


I've let Kucoin know as well.

**Comment by kroitor** [comment]
@calbertuk i've added a check that will throw an `InvalidAddress` on getting null-responses, so that you could catch it and handle the situation properly. Obviously, it depends on the Kucoin engine, so we can't do much beyond that on our side. So, if the system reports a NULL address, then the best thing we could do is to signal you about it. But we can't guess the address there for obvious reasons. Let us know if you have a followup on this. Hope this answers the issue.

**Comment by calbertuk** [comment]
I think I may have been wrong. Verbose of a request below on 1.18.247
`
[5] => {"code":"200000","data":{"address":"0xad82d8ada6276b4e4d410f85ac7e3168f3a203b9","memo":""}} ) array(2) { ["address"]=> NULL ["tag"]=> NULL }  `

Looks like JSON may not be parsed properly?

**Comment by kroitor** [comment]
@calbertuk looks like you're right. I've added one more fix for it, so it should be ok as of 1.18.249. Thx for your feedback!
