### ISSUE TITLE
Kucoin v1 API is broken

### ISSUE THREAD

**Issue by AnCh7** [ccxt/ccxt#4696]
Hi, 

In the latest changes in Kucoin's API they changed URLS and endpoins.
For example:
'market/open/symbols' ----------> 'api/v1/symbols'

- OS: MacOS
- Programming Language version: python
- CCXT version: ccxt-1.18.257.dist-info
- Exchange: kucoin
- Method: fetch_markets and others

**Comment by AnCh7** [comment]
It seems that now we have to use kucoin2...

**Comment by kroitor** [comment]
@AnCh7 

Hi!

> It seems that now we have to use kucoin2...

Yep, exactly!

- https://github.com/ccxt/ccxt/issues/4579
- https://news.kucoin.com/en/24hr-notice-kucoin-platform-2-0-upgrade-scheduled-for-0800-am-utc8-18-feb-19/
