### ISSUE TITLE
Kucoin V2 fetchTickers not supported

### ISSUE THREAD

**Issue by kyletan7** [ccxt/ccxt#4697]
"hasFetchTickers": false for kucoinv2 but the following API still works:

https://openapi-v2.kucoin.com/api/v1/symbols

**Comment by kroitor** [comment]
@kyletan7 please update to most recent version. Duplicate: https://github.com/ccxt/ccxt/pull/4693

**Comment by kyletan7** [comment]
@kroitor Im on the latest version. Title was a typo, I meant fetchTickers() not fetchBalances

**Comment by kroitor** [comment]
@kyletan7 if you looks carefully at the output of https://openapi-v2.kucoin.com/api/v1/symbols – those are not tickers, those are symbols and markets, which are handled in `fetchMarkets` / `loadMarkets`:

- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

**Comment by maliayas** [comment]
Why is this issue closed? Does `kucoin2` currently have `fetchTickers()`?

**Comment by kroitor** [comment]
> Does `kucoin2` currently have `fetchTickers()`?

Looks like it, will add it shortly.

**Comment by kroitor** [comment]
Ok, fetchTickers is added in 1.18.264 and it will be available for downloading in 5-10 minutes. Thx for reporting, @maliayas , @kyletan7 !

**Comment by maliayas** [comment]
Confirmed working. Thanks very much!
