### ISSUE TITLE
OKEX can not get the XRP/USD Future markets

### ISSUE THREAD

**Issue by helldragonx** [ccxt/ccxt#4698]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
  MAC Pro
- Programming Language version:
  Python
- CCXT version:
- Exchange:
- Method:
  load_markets()

- OKEX has XRP/USD future contracts, but from the API load_markets(), can not fetch the XRP/USD market but ETH , BTC or others can be fetched, thanks.

 - Code:
            self.exchange = ccxt.okex({
                'apiKey': self.apiKey,
                'secret': self.secret,
                'enableRateLimit': True,
            })

            self.exchange.proxies = self.proxies
            self.markets = self.exchange.load_markets()

**Comment by kroitor** [comment]
Duplicate:

- #4602 
- #4636

**Comment by helldragonx** [comment]
@kroitor  hello, I'm using Python API, but seems this fix only covers the JS code, so ...

**Comment by kroitor** [comment]
@helldragonx 

https://github.com/ccxt/ccxt/wiki/FAQ#hey-the-fix-youve-uploaded-is-in-js-would-you-fix-python--php-as-well-please
