### ISSUE TITLE
Announcement: changes in fetchTrades, fetchMyTrades, fetchOrders, fetchClosedOrders, fetchOpenOrders

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#470]
Hi, everyone!

The above methods have been changed and their signatures were transformed from

```
fetchTrades (symbol = undefined, params = {})
```

to

```
fetchTrades (symbol = undefined, since = undefined, limit = undefined, params = {})
```

New `since` and `limit` params were added. These params are mostly obvious but we will soon document them in the Manual as well. These new params were just added so they may not work here and there right away, but we will debug all related issues anyway. Feel free to report if you have any... 

The above changes are not backward-compatible, so, be sure to update your code in case you use these methods as of version 1.10.1. Let us know if you have any difficulties with them. Thx!

**Comment by nmiculinic** [comment]
Could you please organize Changelog into more detail/structure. For example, I love
https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md changelog & releases since I can easily see what are bugfixes, Breaking changes (really important), known issues, major improvements etc. 

Also, I'd love to see per exchange which features are implemented in which versions (similar to the README.md showcasing which exchanges are available)

**Comment by kroitor** [comment]
@nmiculinic sure, we will try to organize it and structure it even better, we are steadily making progress. Thx for your suggestion!

**Comment by kroitor** [comment]
@nmiculinic this table may be of some help, while we are doing a comprehensive reference...

<img width="1554" alt="screen shot 2017-11-06 at 16 04 23" src="https://user-images.githubusercontent.com/1294454/32442381-4a63e734-c30c-11e7-9cd5-559fd623672b.png">

**Comment by saianwork** [comment]
Hi can you help me with the fetch_ticker for cryptopia. 
i do this 
for market in btccoins:
    ticker = topia.fetch_ticker(market)
    print(ticker)
can I introduce the timeframe I need somewhere here topia.fetch_ticker(market, here? and how?)

**Comment by kroitor** [comment]
@saianwork 

```Python
hours = 8  # ← your timeframe
topia.load_markets()
for symbol in btccoins:
    market = topia.market(symbol)
    response = topia.publicGetMarketIdHours(topia.extend({
        'id': market['id'],
        'hours': hours,
    }, params))
    print(topia.parse_ticker(response['Data'], market))

```

**Comment by saianwork** [comment]
Hi, it actually works like this

hours = 8  # ← your timeframe
topia.load_markets()
for symbol in btccoins:
    market = topia.market(symbol)
    response = topia.publicGetMarketIdHours(topia.extend({
        'id': market['id'],
        'hours': hours,
    }, params)) #**← without params otherwise it pops an error "undefined" maybe I don't understand what it means? but if i delete params your code works.**
    print(topia.parse_ticker(response['Data'], market))

**Comment by kroitor** [comment]
@saianwork yeah, that `params` should not be there, sorry, my bad, and thx for reporting back!

**Comment by saianwork** [comment]
OK look I actually wana do this

for symbol in btccoins:
        # suffix '.d' means 'darkpool' on some exchanges
                time.sleep(delay)
                symb = symbol
                ticker = topia.fetch_ticker(symbol, **TIMEFRAME I MISS**)
                datetime = ticker['datetime']
                open = ticker['open']
                close = ticker['close']
etc...  so then I can use the OHLCV separately in TA indicators 

With your syntax fetching how can decompose my Response structure? 

hours = 8  # ← your timeframe
topia.load_markets()
for symbol in btccoins:
    market = topia.market(symbol)
    response = topia.publicGetMarketIdHours(topia.extend({
        'id': market['id'],
        'hours': hours,
    }))
    print(topia.parse_ticker(response['Data'], market))

**Comment by kroitor** [comment]
@saianwork :

1. Look at the code snippet above, the answer is there...
    
    `topia.parse_ticker(response['Data'], market)` returns a ticker:

    ```
    hours = 8  # ← your timeframe
    topia.load_markets()
    for symbol in btccoins:
        market = topia.market(symbol)
        response = topia.publicGetMarketIdHours(topia.extend({
            'id': market['id'],
            'hours': hours,
        }))
        ticker = topia.parse_ticker(response['Data'], market) # returns the timeframe you miss
        print(ticker) # don't know if you need to print it here
        # do whatever you need with the ticker...
        datetime = ticker['datetime']
        open = ticker['open']
        close = ticker['close']
        ...
    ```


2. Please read carefully and don't hijack the announcement. The subject of this issue is not related to tickers. This issue is a different story, you should have opened a new issue in the first place (but please don't do it now, that is not necessary anymore, because your question is already answered).

3. When posting code, read triple backticks for readability (more about it: https://guides.github.com/features/mastering-markdown/ ):

    &#96;&#96;&#96;
    your code
    &#96;&#96;&#96;

**Comment by orkenstein** [comment]
I think `fetchOrders` lacks support of multi-page responses:
```
    fetchOrders (symbol = undefined, since = undefined, limit = undefined, params = {}) {
```
Say, we have **Livecoin** api, which returns 10000 orders max per request, and want to fetch all orders for a long period. We won't be able to iterate through pages.

**Comment by kroitor** [comment]
@orkenstein what would you suggest? We have two options:
- redesign it (how?)
- wrap it into a method like fetchPagedOrders () and use extra `params` for control?

**Comment by orkenstein** [comment]
@kroitor I think page handling must be controlled on higher level. `ccxt`should just provide an access to such functionality:
```
fetchOrders (symbol = undefined, since = undefined, startRow = undefined, endRow = undefined, params = {})
```
Also, `since` should be extended to `issuedFrom` and `issuedTo` or something like this.

**Comment by kroitor** [comment]
@orkenstein , unfortunately, most exchanges don't allow any pagination whatsoever. This is why we lifted only the most common subset of arguments to that method. And some exchanges don't accept a timestamp in `since`, they accept an order id or a trade id (to start from). I guess we should add another method or, maybe, even a set of methods, for paginated access...

**Comment by orkenstein** [comment]
@kroitor, yep, understand. For example, on **Livecoin** there's a limit of 10k records per orders request. That's where the pagination starts to work. How does it work on other exchanges?

**Comment by kroitor** [comment]
@orkenstein in general, an exchange might or might not have the following arguments to any of `fetch*Orders/fetch*Trades` endpoints:

- `start` the timestamp to start from (some return exclusive sets, others return inclusive sets)
- `end` the timestamp to end with (same story with exclusive/inclusive)
- an order id / trade id to start from
- an order id / trade id to end with
- a limit of entries to output

But most of the time, they only support for one or two arguments from the above list. Their choice for their arguments is mostly random, but i'd put it this way:
50% of exchanges support since and limit
20% of exchanges support end/to or some other set of pagination params
30% of exchanges don't support any filtering at all

Also, if you set a limit = 10000, most of exchanges will still return 100 entries at max... So, in fact, there's a lot of detail to this, we can't just throw some exchange-specific implementation into it and hope it will work the same with others... Order API is the hardest part of unification.

**Comment by kroitor** [comment]
@orkenstein also, note that you can still pass exchange-specific pagination params to all exchanges, where supported, via the extra `params` argument that goes last into any unified/non-unified API call. So you can still use their pagination, but currently you will have to account for exchange-specifics in userland, because this aspect is not completely unified yet. 

As for the Livecoin, you should see this, btw: https://github.com/ccxt/ccxt/issues/467

**Comment by orkenstein** [comment]
@kroitor, yes, you're right. Better live it at exchange-specific parameters.
