### ISSUE TITLE
kucoin2 withdraw failed

### ISSUE THREAD

**Issue by davidinsuomi** [ccxt/ccxt#4702]
- OS: Ubuntu 18.10 (Cosmic Cuttlefish)
- Programming Language version: nodejs  v8.11.4
- CCXT version: 1.18.258
- Exchange: kucoin2
- Method:withdraw

When I using withdraw in kucoin2 api, it throws following exceptions:
(node:27522) UnhandledPromiseRejectionWarning: TypeError: this.privatePostWithdrawal is not a function
    at kucoin2.withdraw (/node_modules/ccxt/js/kucoin2.js:767:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by kroitor** [comment]
Thank you for reporting, it was a typo/bug, fixed in 1.18.261 (will be available for downloading in 5-10 minutes). We will be happy if you let us know whether it helped or not.

**Comment by davidinsuomi** [comment]
Hi, I have updated the ccxt library to version 1.18.261, but it throws parameter error

(node:32317) UnhandledPromiseRejectionWarning: Error: kucoin2 Parameter error
    at kucoin2.handleErrors (/node_modules/ccxt/js/kucoin2.js:980:19)
    at response.text.then (/node_modules/ccxt/js/base/Exchange.js:686:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by kroitor** [comment]
@davidinsuomi can you post your **verbose request/response**?

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

```Javascript
await exchange.loadMarkets ()
exchange.verbose = true
const response = await exchange.withdraw (...
```

**Comment by kroitor** [comment]
@davidinsuomi nevermind, i think I found it and nailed it, can you please retry with 1.18.262 in 5-10 minutes again? Thx!

**Comment by davidinsuomi** [comment]
let request = {
            'currency': currency,
            'address': address,
        };
I guess the request missing amount, and the key 'currency' should change to 'amount' as kucoin api2 describes https://kucoinapidocs.docs.apiary.io/#reference/0/assets-operation/create-withdrawal-apply

**Comment by kroitor** [comment]
@davidinsuomi yeah, a leftover, i've uploaded the edit, let us know if it resolved the issue for you. Thx again!

**Comment by davidinsuomi** [comment]
now it works fine thanks

**Comment by kroitor** [comment]
@davidinsuomi awesome! Feel free to ask if you have any issues or difficulties with it, your feedback is welcome!

**Comment by davidinsuomi** [comment]
HI, Sorry to reopen this issue, when using the withdraw api, the sever does not return any error, but it could not proceed withdraws, it shows Assets freezing failed.

I ask kucoin team, because new api has concept with trading account and main account, if you want to withdraw tokens, you have to inner transfer to main account, then proceed withdraw. as document describes.
https://docs.kucoin.com/#inner-tranfer 
some guys from telegram also quote "I found why my withdrawal failed. The main and trade account separation sucks, every time I want withdraw, I need to issue inner transfer to main account then issue the real withdrawal.

Same thing happens on deposit. It deposit to main account, before I could trade, I need to issue inner transfer to trade account."

how ccxt lib with integrate with the withdraw method in kucoin(concept with trading account and main account)?

**Comment by frosty00** [comment]
@davidinsuomi 

We don't have a unified method for transfering between accounts yet. However we recently added the `loadAccounts` endpoint. You can look at the list of accounts by checking the `.accounts` attribute. For now you can use the generate methods to interact with accounts, for kucoin it is `privatePostAccountsInnerTransfer`

**Comment by kroitor** [comment]
@davidinsuomi you can do that with [implicit methods](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods) like shows in this example for `hitbtc`: https://github.com/ccxt/ccxt/issues/1216#issuecomment-357194336 (it's the same for `kucoin2` but you will want to change the names of those implicit methods and their params),
