### ISSUE TITLE
Binance changed country to Malta

### ISSUE THREAD

**Issue by marcuswin** [ccxt/ccxt#4705]
Proof: https://medium.com/binanceexchange/binance-the-worlds-largest-crypto-exchange-announces-investment-in-malta-4c7e51136563

**Comment by kroitor** [comment]
The article says that Binance is very involved with Malta, but there's no mention of Binance actually relocating to Malta, or am I wrong?

**Comment by marcuswin** [comment]
Firstly, Binance had a [troubles with Japanese regulator](https://www.bitrates.com/news/p/binance-moves-to-malta-amid-fears-of-a-japanese-crackdown).
Secondly, we have a lot of news about activity Binance in Malta, such as [partnership with exchange](https://www.ccn.com/binance-partners-malta-stock-exchange-to-launch-new-digital-exchange) and [forming bank](https://www.bloomberg.com/news/articles/2018-07-12/binance-backs-plan-for-bank-in-malta-with-digital-coin-investors).
