### ISSUE TITLE
QuadrigaCX doesn't work

### ISSUE THREAD

**Issue by marcuswin** [ccxt/ccxt#4707]
Proof: https://www.quadrigacx.com/

**Comment by kroitor** [comment]
@marcuswin this was in the news:

- https://www.straight.com/tech/1197591/ceo-crypto-exchange-quadrigacx-dies-freezing-access-investors-250-million
- http://fortune.com/2019/02/04/cryptocurrency-quadrigacx-gerald-cotten-frozen-funds/

We will delist it soon.
