### ISSUE TITLE
Function amountToLots is undefined HitBTC

### ISSUE THREAD

**Issue by viniciussvl** [ccxt/ccxt#4709]
Hello, my friends, I'm getting the error order amount should be evenly divisible by lot size of 0.01 (X value), right, I have to make the amount divisible by the lot so I understood by searching the old issues I saw that you used the method amountToLots to do a "conversion", does this method still exist? I tried to use it and got the error that the function is undefined

```
this.class = new ccxt.hitbtc({
    apiKey: params.api_key,
    secret: params.api_secret,
 });

console.log(this.class.amountToLots(symbol, amount))
```

----------------------------------------------------
- OS: Windows 10
- Programming Language version: Javascript / Node
- CCXT version: 1.18.133
- Exchange: HitBTC
- Method: amountToLots

**Comment by viniciussvl** [comment]
I'm sorry, I just found out that the amountToLots method was deprecated and now we use the amountToPrecision, I was able to solve the HitBTC problem!

**Comment by kroitor** [comment]
@viniciussvl thx for reporting back!
