### ISSUE TITLE
https://unpkg.com: Cannot find module "build/ccxt.browser.js" in package ccxt

### ISSUE THREAD

**Issue by jrix** [ccxt/ccxt#471]
when I try to include <script> from https://unpkg.com/ccxt - error: Cannot find module "build/ccxt.browser.js" in package ccxt - is it unpgg error or something in the ccxt code?

**Comment by kroitor** [comment]
Thx for reporting this, @jrix ! We will take a look and will fix this asap.

**Comment by kroitor** [comment]
@jrix can you please retry it now? I checked it with my browser by following that link and it reported 1.10.3 to me. Let us know if this issue is now solved as seen from your side. Thx!

**Comment by jrix** [comment]
Thank you! I can confirm, it is It is working now. This problem  was for at least several days.  I hope you have indeed found a permanent fix.

**Comment by kroitor** [comment]
@jrix yep, thx a lot for reporting back!
