### ISSUE TITLE
Bittrex INVALID_SIGNATURE error

### ISSUE THREAD

**Issue by masalinas** [ccxt/ccxt#4711]
- OS: Ubuntu 16.04
- Programming Language version: nodeJS 8.5.X
- CCXT version: 1.18.247
- Exchange: Bittrex
- Method: account_get_balance with this params: {"currency": "BTC"}

**The Error obtain is**: "bittrex {"success":false,"message":"INVALID_SIGNATURE","result":null}"

I checked the same API with my account using the same APIKey and secret but witth this other nodeJS package node-bittrex-api v0.8.3 without any problem

Testing your package over the same exchange but with public API I not have any error, but using this private API I obtain the error above.

What happend

**Comment by kroitor** [comment]
@masalinas

- have you tried with a new key? (retry with a new keypair)
- have you tried going through the troubleshooting sequence? 
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Most often, the issue with using the same key with two packages is due to one of the packages messing up the nonce. The second most often issue is forgetting to enable proper rate-limiting, according to the Manual.

**Comment by kroitor** [comment]
```
mbp:ccxt igorkroitor$ node examples/js/cli bittrex account_get_balance '{"currency":"BTC"}'
bittrex.account_get_balance ([object Object])
{ success:    true,
  message:   "",
   result: {      Currency: "BTC",
                   Balance:  0.00000736,
                 Available:  0.00000736,
                   Pending:  0,
             CryptoAddress: "1cL5M4HjjoGWMA4jgHC5v6GqcjfxeeNMy" } }
```
---

```
mbp:ccxt igorkroitor$ python examples/py/cli.py bittrex account_get_balance '{"currency":"BTC"}'
{u'message': u'',
 u'result': {u'Available': 7.36e-06,
             u'Balance': 7.36e-06,
             u'CryptoAddress': u'1cL5M4HjjoGWMA4jgHC5v6GqcjfxeeNMy',
             u'Currency': u'BTC',
             u'Pending': 0.0},
 u'success': True}
```

**Comment by masalinas** [comment]
Hi Igor,

Thanks for your response. and this great library. I developed a **node-RED node** wrapping around CCXT library and published it in [IBM node-RED marketplace](https://flows.nodered.org/node/node-red-contrib-ccxt). I was testing some Exchanges but in Bittrex I have this problem. I followed this topics:

* have you tried with a new key? (retry with a new keypair)
   Yes. Remove two times my secrets and create new ones. Try with them and the result was the same. Today for example I tryed again with the same error.
* have you tried going through the troubleshooting sequence?
   Yes I read all the steps from troubleshooting link. For example:
   - I tested adding a milliseconds nonce in the request, but the response it's the same error.
   - I activated the vervose flag to watch more error details, but I not observed anything extra information
   - I used these keys with my node-RED node and with the other package explained before **node-bittrex-api v0.8.3** in this last one without any error.
   - Off course the connectivity is correct, etc

My conclusions are:

* With Kraken Exchange for example and my credits I not have any error in any API.
* The public APIs with Bittrex Exchange no error.
* **The private APIs with credentials in Bittrex I have errors in all private APIs.**
* Using the **node-bittrex-api v0.8.3** and the same credits in Bittrex Exchange NO errors.

Regards

**Comment by kroitor** [comment]
Hello Miguel ) Thanks for your feedback! And also for sharing the link, it's really cool to see the node-RED ccxt-wrapper project! Let us know if you have any questions or difficulties with the lib, will be happy to help asap )
