### ISSUE TITLE
Bitmex : order

### ISSUE THREAD

**Issue by md0101** [ccxt/ccxt#472]
Hi, I am seeing an error whilst placing an order to Bitmex.
eg.
`order = bitmex.create_limit_sell_order('XBTZ17', 10, 6800)`

throws this error
```
ccxt.errors.ExchangeNotAvailable: bitmex POST https://www.bitmex.com/api/v1/order?symbol=XBTZ17&side=Sell&orderQty=10&ordType=Limit&rate=6800 400 Bad Request  (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting, {"error":{"message":"Invalid price","name":"HTTPError"}})
```

I  suspect, but not certain, it is to do with assigning `order['rate'] = price` in the ccxt/exchanges.py  since I can successfully enter an order using this line and assigning a 'price' to the order
```
order = bitmex.privatePostOrder({'symbol': 'XBTZ17', 'side': 'Sell', 'orderQty': 10, 'price': 6800})
```

**Comment by kroitor** [comment]
@md0101 hi! Good to hear again from you! Thank you for reporting this, will look into it and fix right away! Hold on, plz!

**Comment by md0101** [comment]
Sure, thanks for your quick attention!

**Comment by kroitor** [comment]
@md0101 sorry, but... what's your version of ccxt? We don't have exchanges.py anymore, and in current version, the field is called `price`, not `rate`:

https://github.com/ccxt/ccxt/blob/master/python/ccxt/bitmex.py#L296

**Comment by md0101** [comment]
@kroitor appologies it was an older version - have updated and works

**Comment by kroitor** [comment]
@md0101 ok, good to know it works for you! Thx for reporting back! Let us know if you have any other difficulties with it. Cheers!
