### ISSUE TITLE
Kucoin ticker API changes

### ISSUE THREAD

**Issue by rdbr** [ccxt/ccxt#4720]
- Programming Language version: JavaScript
- CCXT version: 1.18.269
- Exchange: kucoin2
- Method: fetchTickers, fetchTicker, parseTicker

When testing, I noticed tickers weren't getting parsed anymore. Kucoin changed the ticker format to include `buy` and `sell` (bid and ask) and removed the `open` and `close` properties.

The data format also changed a bit in `fetchTickers`.

```
https://openapi-v2.kucoin.com/api/v1/market/stats?symbol=LOOM-BTC

{
	"code": "200000",
	"data": {
		"symbol": "LOOM-BTC",
		"high": "0.0000123",
		"vol": "45161.5073",
		"datetime": 1550654614376,
		"last": "0.00001204",
		"low": "0.00001109",
		"buy": "0.00001186",
		"sell": "0.00001197",
		"changePrice": "0.00000065",
		"changeRate": "0.057"
	}
}
```

```
https://openapi-v2.kucoin.com/api/v1/market/allTickers

{
	"code": "200000",
	"data": {
		"date": 1550654263910,
		"ticker": [{
			"symbol": "LOOM-BTC",
			"high": "0.0000123",
			"vol": "45161.5073",
			"last": "0.00001204",
			"low": "0.00001109",
			"buy": "0.00001184",
			"sell": "0.00001196",
			"changePrice": "0.00000065",
			"changeRate": "0.057"
		},
```

**Comment by MarcelBeining** [comment]
Can confirm. What is even worse, right now the 'last' key is not parsed anymore from the kucoin json by ccxt, see here

```
exchange = ccxt.kucoin()
exchange.fetch_ticker('LOOM/BTC')

Out[6]: 
{'ask': None,
 'askVolume': None,
 'average': None,
 'baseVolume': 44399.5669,
 'bid': None,
 'bidVolume': None,
 'change': -1.8e-07,
 'close': None,
 'datetime': None,
 'high': 1.23e-05,
 'info': {'buy': '0.00001168',
  'changePrice': '-0.00000018',
  'changeRate': '-0.0151',
  'datetime': 1550661146316,
  'high': '0.0000123',
  'last': '0.00001169',
  'low': '0.00001159',
  'sell': '0.00001182',
  'symbol': 'LOOM-BTC',
  'vol': '44399.5669'},
 'last': None,
 'low': 1.159e-05,
 'open': None,
 'percentage': -0.0151,
 'previousClose': None,
 'quoteVolume': None,
 'symbol': 'LOOM/BTC',
 'timestamp': None,
 'vwap': None}
```

This completely breaks my app :-( 
Kucoin devs are full-time botchers!

**Comment by kroitor** [comment]
Will fix shortly. Thx for reporting!

**Comment by MarcelBeining** [comment]
Guess this is also the reason why fetch_tickers, is breaking, too, atm.

```
exchange.fetch_tickers()
Traceback (most recent call last):

  File "<ipython-input-6-7d47a95e0153>", line 1, in <module>
    self.exchange.fetch_tickers()

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\kucoin2.py", line 413, in fetch_tickers
    ticker = self.parse_ticker(data[i])

KeyError: 0
```

**Comment by rdbr** [comment]
Thanks for the fast fix!

The recent commits reverted some of the changes related to https://github.com/ccxt/ccxt/issues/4715 so now `percentage` is wrong again.

**Comment by rdbr** [comment]
Since the ticker format changed, maybe it is now better to use: `/market/orderbook/level1?symbol=<symbol>` for `fetchTicker` instead of `/market/stats?symbol=<symbol>`

The API docs got updated, so you can check it out.

I know it is a lot of issues, but thanks for the fast responses!

**Comment by kroitor** [comment]
> The recent commits reverted some of the changes related to #4715 so now `percentage` is wrong again.

Ouch. Pardon, my bad, will upload a refix shortly
