### ISSUE TITLE
Kucoin_v2: parse_order() is not returning 'cost' value 

### ISSUE THREAD

**Issue by Djusk8** [ccxt/ccxt#4724]
- OS: MS Win 10 x64
- Programming Language version: Python 3.7.2
- CCXT version: 1.18.270
- Exchange: Kucoin
- Method: fetchClosedOrders / parse_order function

There is no 'cost' value returned by parse_order() function in kucoin_v2.py

Is it possible to add following code to parse_order() like it was in Kucoin v1:

```
cost =  self.safe_float(order, 'dealFunds')

return {
           .....
           .....
           'cost': cost,
        }

```

**Comment by kroitor** [comment]
@Djusk8 can you please post the [*verbose request/response*](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue) structure? Just to check the other fields for consistent as well...

```Python
exchange.load_markets()
exchange.verbose = True
exchange.fetch_closed_orders (...
```

**Comment by Djusk8** [comment]
Request: GET https://openapi-v2.kucoin.com/api/v1/orders?status=done&symbol=ETH-BTC&startAt=1550662761146 {'KC-API-KEY': 'xxxxxxxxxxxxxx', 'KC-API-TIMESTAMP': '1550675888988', 'KC-API-PASSPHRASE': 'xxxxxxx', 'KC-API-SIGN': 'xxxxxxxxxxxxxxxxxx', 'User-Agent': 'python-requests/2.21.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://openapi-v2.kucoin.com/api/v1/orders?status=done&symbol=ETH-BTC&startAt=1550662761146 200 {'Date': 'Wed, 20 Feb 2019 15:18:11 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=dc4ea4721a1820033ac8be91efa158e861550675891; expires=Thu, 20-Feb-20 15:18:11 GMT; path=/; domain=.kucoin.com; HttpOnly; Secure, X-TRACE=ubhZKfeYZvx6NLJXJ88uWrRrDVOB/sXTtP40DAUMqGQ=; Path=/, SESSION=YjMwMDA2YzEtZWMzOC00NWRmLWIyYTgtN2VjYmE0OTQxM2Uz; Max-Age=604800; Expires=Wed, 27-Feb-2019 15:18:11 GMT; Path=/; HttpOnly, __cfruid=831aa74d98fc8eb320a303d40d3283aee975b4f6-1550675891; path=/; domain=.kucoin.com; HttpOnly', 'X-TRACE-ID': '867fa6912b4e29ab', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Expires': '0', 'X-Frame-Options': 'DENY', 'Strict-Transport-Security': 'max-age=2592000; includeSubDomains; preload', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '4ac1f1c0f9af8667-ARN', 'Content-Encoding': 'gzip'} {"code":"200000","data":{"totalNum":2,"totalPage":1,"pageSize":50,"currentPage":1,"items":[{"symbol":"ETH-BTC","hidden":false,"opType":"DEAL","fee":"0","channel":"WEB","feeCurrency":"BTC","type":"limit","isActive":false,"createdAt":1550667932000,"visibleSize":"0","price":"0.03823583","iceberg":false,"stopTriggered":false,"funds":"0","id":"5c6d509c89fc841cf19722db","timeInForce":"GTC","side":"sell","dealSize":"0","cancelAfter":0,"dealFunds":"0","stp":"","postOnly":false,"stopPrice":"0","size":"0.0000001","stop":"","cancelExist":true},{"symbol":"ETH-BTC","hidden":false,"opType":"DEAL","fee":"0","channel":"API","feeCurrency":"BTC","type":"limit","isActive":false,"createdAt":1550662779000,"visibleSize":"0","price":"0.03696558","iceberg":false,"stopTriggered":false,"funds":"0","id":"5c6d3c7bc788c611c8d3ce56","timeInForce":"GTC","side":"buy","dealSize":"0.013526","cancelAfter":0,"dealFunds":"0.00049999643508","stp":"","postOnly":false,"stopPrice":"0","size":"0.013526","stop":"","cancelExist":false,"clientOid":"3ce5c538-b144-45ce-9ae9-57cd53549a8e"}]}}

**Comment by kroitor** [comment]
@Djusk8 the `cost` has been added (plz, update your version), thx for reporting!
