### ISSUE TITLE
Add Kraken Futures

### ISSUE THREAD

**Issue by fonzmeister** [ccxt/ccxt#4727]
Kraken has enabled futures trading on their platform.

It uses a different API endpoint e.g.  https://futures.kraken.com/derivatives/api/v3/tickers

documentation: https://support.kraken.com/hc/en-us/categories/360001456652-Futures-API

**Comment by hivemall** [comment]
I would welcome making this a priority. Kraken futures starts to get traction. Yet i cant find a puplic endpoint and doc

**Comment by kroitor** [comment]
@hivemall we'll get kraken asap)

**Comment by manster829** [comment]
Has this been implemented?

**Comment by nomad5am** [comment]
any update?

**Comment by PierreRochard** [comment]
Is anyone working on this? If not I’ll give it a pass

**Comment by JDJoe** [comment]
Hello. What is the status with adding Kraken futures?

**Comment by kroitor** [comment]
@JDJoe it's still not implemented yet, but we will prioritize this ASAP.

**Comment by caa1982** [comment]
That would be a great addition... Looking fwd to it! :)

**Comment by mark-sch** [comment]
@kroitor Yes, important exchange ...any schedule for it?

**Comment by kroitor** [comment]
@mark-sch plz read here: https://github.com/ccxt/ccxt/issues/6332

**Comment by kroitor** [comment]
@mark-sch we will get to it this month, immediately after the release of CCXT Pro.

**Comment by Nicour** [comment]
Hello.
Is there any news regarding this?

Thank you!

**Comment by kroitor** [comment]
@Nicour hi! Not yet, but we are going to address this very soon and will hopefully add the support for Kraken futures shortly. Will keep you updated here. Thx!

**Comment by caa1982** [comment]
Hi @kroitor, How is the implementation going, any timeline? Thanks

**Comment by kroitor** [comment]
@caa1982 we're working on it atm, hope to get it listed very soon: 

- https://github.com/ccxt/ccxt/issues/6697
- https://github.com/ccxt/ccxt/wiki/FAQ#whats-your-progress-on-adding-the-feature-foo-that-was-requested-earlier-how-do-you-do-implementing-exchange-bar

**Comment by the-spice-must-flow** [comment]
@kroitor anything I could do to help progress on this issue? I see it's in the roadmap for this month. I've got a bit of time and am a big Kraken user so would be happy to pitch in on this one.

**Comment by kroitor** [comment]
@the-spice-must-flow i have it implemented by approx 50%, however, we're still working on the properly unified formats... I'll upload my code in a PR within a few days, and it would be great if you could help implement the missing methods then. Thx for your involvement!

**Comment by 2803media** [comment]
Any update on the kraken futures implementation?

**Comment by Nicour** [comment]
> Any update on the kraken futures implementation?

I made this a few months ago but i don't know if it works for you: https://github.com/Nicour/Kraken-Futures-API-V3

**Comment by 2803media** [comment]
Thanks I will have a test ;)

**Comment by dwightschrute-aarm** [comment]
Hello, any update on the python kraken futures? Kraken futures are getting traction it would be super nice to have it in ccxt.

**Comment by bigcountry-scav** [comment]
@kroitor any update on implementing this?

**Comment by kamisan118** [comment]
@kroitor really need this functionality, would very appreciate if you could prioritize this.

**Comment by qtmspin** [comment]
I've posted a $100 bounty for this :)  Dinner's on me :)
https://www.bountysource.com/issues/70379858-add-kraken-futures

**Comment by kyjak** [comment]
Is there any progress on this?

**Comment by tjomarens** [comment]
Any news on Kraken futures?

**Comment by samgermain** [comment]
> Any news on Kraken futures?

It's not merged, but you can pull [this PR](https://github.com/ccxt/ccxt/pull/11920) and use it if you want

**Comment by quuentin** [comment]
Hi any update for kraken futures with PHP ?

**Comment by samgermain** [comment]
@kroitor Krakenfutures was added, but was later removed

**Comment by dwightschrute-aarm** [comment]
Hello, any update for kraken futures with Python ?

**Comment by youknowone** [comment]
@samgermain @kroitor could you please re-open this issue for #15133?
