### ISSUE TITLE
Kucoin v2: different 'since' types in fetchClosedOrders() and fetchMyTrades()

### ISSUE THREAD

**Issue by Djusk8** [ccxt/ccxt#4728]
* Programming Language version: Python 3.7.2
* CCXT version: 1.18.280
* Exchange: Kucoin (v2)
* Method: fetchClosedOrders / fetchMyTrades

In similar functions I need to use different types of 'since' parameter:
```
ex.fetchClosedOrders(pair, str(since))
ex.fetchMyTrades(pair, int(since))
```
I found that Kucoin returns order timestamp parametr ('createdAt') as `int`, but during parsing the order timestamp converted to `str`

```
def parse_order( .....
        timestamp = self.safe_string(order, 'createdAt')
```

while Trade leave timestamp as `Int`:

```
def parse_trade( ......
        timestamp = self.safe_integer(trade, 'time')
        if timestamp is not None:
            timestamp = int(timestamp / 1000000)
        else:
            timestamp = self.safe_integer(trade, 'createdAt')
```

In general this is not a problem as long as everyone can convert `timestamp ` while calling a function, but it seems to me that the uniformity of data types will simplify development and debugging.

Also I can't find any information about 'time' parametr in fills section at 
[https://docs.kucoin.com/#list-fills](https://docs.kucoin.com/#list-fills)

so can you remove unnecessary code from `parse_trade()` if it acceptable:

```
def parse_trade( ......
     timestamp = self.safe_integer(trade, 'createdAt')
```

**Comment by kroitor** [comment]
Fixed in 1.18.281. Thank you!
