### ISSUE TITLE
KuCoin Platform 2.0 upgrade complete!

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#4731]
Hello everyone! )

Great news!

Now **KuCoin** has **[completed the Platform 2.0 upgrade](https://www.kucoin.com/news/en-KuCoin-Platform-V2-Upgrade-Complete)**. 

With this upgrade, **KuCoin** will be able to provide brand new API, various order types, reliable security solutions, more attractive fee program, more convenient self-service management features, efficient notification module, improved user experience and feature optimizations etc. 

Hope you enjoy your new and improved trading experience with brand new **[KuCoin](https://www.kucoin.com)**!

**Comment by frosty00** [comment]
https://www.kucoin.com/news/771-20

**Comment by xpl** [comment]
<img src="https://assets.kcsfile.com/cms/media/2myLbtDc4QgDjEBDJueB3Wvl3CdVNiNMQesu9a18O.png">
