### ISSUE TITLE
Kucoin2 price and amount precision in createOrder

### ISSUE THREAD

**Issue by rdbr** [ccxt/ccxt#4738]
- Programming Language version: JavaScript
- CCXT version: 1.18.289
- Exchange: kucoin2
- Method: createOrder

The `createOrder` function doesn't use the `priceToPrecision` and `amountToPrecision` functions to force a correct precision. Without these functions, Kucoin can return errors with incorrectly supplied amounts or prices.

Example:
```
kucoin2 Order size increment invalid.
```

**Comment by KaptKos69** [comment]
Won't let me sell, "order size increment invalid"

**Comment by kroitor** [comment]
@KaptKos69 it has been fixed in the most recent version. If it doesn't work for you, then we will need your *verbose request/response* in oder to be able to help you.

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
