### ISSUE TITLE
Struggling to get LBank signed properly.

### ISSUE THREAD

**Issue by hanyoonLDA** [ccxt/ccxt#4741]
- OS: Ubuntu 16
- Programming Language version: Python 3.5
- CCXT version: 1.18.281
- Exchange: LBank
- Method: GET

I've been trying to get private endpoints working with LBank, which requires a signature, but I'm going to be honest here and say that I am struggling. Their API docs weren't much help. Anyone have experience with trying to get it signed properly w/ Python?

**Comment by kroitor** [comment]
@hanyoonLDA can you share a pair of empty-balance keys for us to test on our side (you could safely delete it later after we resolve this)?

Unfortunately, Lbank does not allow me to create a new API key without ID verification... So i have to wait for the account to be verified first...

**Comment by hanyoonLDA** [comment]
Sure @kroitor I'll send you an email shortly.

**Comment by kroitor** [comment]
Fixed in CCXT version 1.18.721
