### ISSUE TITLE
How to know the hours where there is most trades?

### ISSUE THREAD

**Issue by andrelimao** [ccxt/ccxt#4742]
Anyone knows how to see the hours of the day and the days of the week that some pair is most traded? Do I have to use OHCLV?

**Comment by kroitor** [comment]
> that some pair is most traded?

Depends on how you define "most traded". By which metric/criteria? By volume? By number of trades? By price volatility? By market depth?  ;)

> Do I have to use OHCLV?

If you're going to decide based on volumes, then yes, most likely, you will need `fetchOHLCV` or `fetchTickers` or `fetchOrderBook` or `fetchTrades`.

I suggest that you start from here: https://github.com/ccxt/ccxt/wiki. 

Let us know if that does not answer the question.
