### ISSUE TITLE
Implement Saturn Network exchange (ETC DEX)

### ISSUE THREAD

**Issue by magichatsam** [ccxt/ccxt#4749]
url: https://saturn.network
full API documentation: https://ticker.saturn.network

Saturn Network is the first multi chain decentralized exchange and currently the only DEX operating on Ethereum Classic.

Thanks!

**Comment by max00x** [comment]
ในวันที่ อ. 26 ก.พ. 2019 21:50 น. sam <notifications@github.com> เขียนว่า:

**Comment by An-Net** [comment]
The exchange has joined the OKEX network
https://www.okex.com/academy/en/saturn-joins-okexchain-ecosystem
