### ISSUE TITLE
Bittrex system upgrade

### ISSUE THREAD

**Issue by lampardlb** [ccxt/ccxt#4754]
Bittrex is upgrading their system from 21:00 UTC 27th Feb [(link here)](https://bittrex.zendesk.com/hc/en-us/articles/360024542691-Bittrex-Technology-Update-What-You-Need-to-Know) and among other changes, there are two notable ones:
1. 'after the upgrade, your orders will be processed at a rate 20 times faster than before';
2. 'New order types and options, including Market Orders'

They did not release a new API documentation, but as they are a certified exchange on ccxt, could the devs please check with them about integrating such improvements? Thank you very much!

**Comment by mykolasmith** [comment]
This broke fetch_balances for us

**Comment by kroitor** [comment]
@mykolasmith which version? Have you tried the most recent one?

**Comment by mykolasmith** [comment]
Upgrading worked for us (1.18.300 => 1.18.307)
Sorry for the false alarm.

**Comment by kroitor** [comment]
@mykolasmith no worries, let us know if you notice anything suspicious! Thx!
