### ISSUE TITLE
Kucoin2 : Inner transfer between internal accounts

### ISSUE THREAD

**Issue by RomainBlindy** [ccxt/ccxt#4756]
Hi,

I don't find a way to transfer my funds from Main Account to Trade Account and vis versa on Kucoin 2.
I saw on their docs there is an endpoint for this (https://docs.kucoin.com/#inner-tranfer), but I'm not enough great to find how to make it possible with ccxt.

Can someone help ? 

Thanks a lot,

Romain

**Comment by kroitor** [comment]
Hi!

Have you read the section of the Manual on how to use implicit methods?

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

Let me know if that doesn't answer the question.

**Comment by RomainBlindy** [comment]
Thanks for the link. 
I will read it and try to figure it out. I come back to close the question if i find the solution.
Thanks a lot,

**Comment by kroitor** [comment]
@RomainBlindy I'd really recommend to read the entire Manual from top to bottom thoroughly at least once – it has most of the answers you need and it will really save you a ton of time, trust me ;) 

- https://github.com/ccxt/ccxt/wiki

**Comment by saikatharryc** [comment]
@kroitor  for this, the api:
https://github.com/ccxt/ccxt/blob/master/js/kucoin.js#L97
added here.
docs: https://docs.kucoin.com/#inner-tranfer
but never used,  any special reason?
Functionality: moves funds from main account to the trading account.

**Comment by kroitor** [comment]
@saikatharryc have you read this: https://github.com/ccxt/ccxt/issues/4756#issuecomment-467855324 ?

**Comment by Mantas779** [comment]
Stock with same problem, 
did :   print(dir(ccxt.kucoin()))   but noting about inner_Transfer 
I tried but  'kucoin' object has no attribute 'create_inner_transfer' 

I know Kucoin has the: create_inner_transfer(from_account_id, to_account_id, amount, order_id=None)

**Comment by kroitor** [comment]
@Mantas779 have you read this? https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

**Comment by samgermain** [comment]
You can use the unified `tranfer` method now

-------------------

# JavaScript

```
const ccxt = require("ccxt");

console.log ('CCXT Version:', ccxt.version)

const exchange = new ccxt.kucoin({
    'apiKey': '...',
    'secret': '...',
})

const code = 'USDT';
const amount = 1;
const from = 'main';
const to = 'trade';

exchange.transfer(code, amount, from, to)
```

-------------

# Python

```
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.kucoin({
    'apiKey': '...',
    'secret': '...',
})

code = 'USDT';
amount = 1;
from = 'main';
to = 'trade';

exchange.transfer(code, amount, from, to)
```
