### ISSUE TITLE
Is there any way fetch logo for exchanges or markets .

### ISSUE THREAD

**Issue by caeser1996** [ccxt/ccxt#4757]
Does ccxt provide any scope for logo or icons for markets or exchanges.

**Comment by kroitor** [comment]
@caeser1996 

Yes, see the `urls` property of the exchange, it has a `logo` field there: 

```Python
# in Python for example, but almost the same in JS and PHP as well:
import ccxt
exchanges = ['binance', 'kucoin2', 'bittrex']
for id in exchanges:
    exchange = getattr(ccxt, id)()
    print(exchange.id + ': ' + exchange.urls['logo'])
```

However, the logo there is not for use within the apps, but mostly for generating docs for the CCXT. Use at your own risk. 

Let us know if that does not answer your question.

**Comment by ceaser1996** [comment]
is there any option to get a market currency logo?

**Comment by kroitor** [comment]
@caeser1996 nope, this is beyond the scope of CCXT for now.

**Comment by ceaser1996** [comment]
can you just help me with equivalent code in php.

**Comment by kroitor** [comment]
@caeser1996 

```PHP
// PHP
$exchanges = array ('binance', 'kucoin2', 'bittrex');
foreach ($exchanges as $id) {
    // instantiate the exchange by id
    $exchange = '\\ccxt\\' . $id;
    $exchange = new $exchange ();
    echo $exchange->id . ':' . $exchange->urls['logo'] . "\n";  
}
```
