### ISSUE TITLE
Binance Closed Order Fee

### ISSUE THREAD

**Issue by IMikhelson** [ccxt/ccxt#4758]
- OS: Windows 10 Pro
- Programming Language version: Python 3.7
- CCXT version: 1.18.300
- Exchange: Binance
- Method: fetch_closed_orders

For Binance, the fee is not included in the 'cost' field, and the 'fee' field is None.  Is there a way to fetch the fee that was charged?

**Comment by xpl** [comment]
@IMikhelson You can `fetchMyTrades` and then derive the order fees from its output, by looking at the trades associated with an order you have (and summing up their fees).

**Comment by kroitor** [comment]
@IMikhelson some exchanges will not serve the `fee` info from orders and will serve it within executed fills (private trades). 

- https://github.com/ccxt/ccxt/wiki/Manual#order-structure
- https://github.com/ccxt/ccxt/wiki/Manual#trade-structure
- https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades

Let us know if that doesn't help.
