### ISSUE TITLE
Python bittrex fetch_balance() TypeError on cast of balance to float

### ISSUE THREAD

**Issue by mrjingles41** [ccxt/ccxt#4770]
- OS: Ubuntu 18.04 LTS within WSL of Windows 10
- Programming Language version: 3.6.7
- CCXT version: 1.17.538
- Exchange: Bittrex
- Method: fetch_balance

The response of bittrex apparently can contain "None" values instead of floats, so the conversion to float within the fetch_balance() method fails. Example:

`import ccxt, configparser
`config = configparser.ConfigParser()
`config.read('./config.ini')
`exchange = ccxt.bittrex({
`    "apiKey": config['bittrexAPI']['key'],
`    "secret": config['bittrexAPI']['secret'],
`    "enableRateLimit": True,
`})
`print(exchange.fetch_balance())

Output:

> Traceback (most recent call last):
> File "test_rest.py", line 12, in <module>
>  print(exchange.fetch_balance())
>  File "/usr/local/lib/python3.6/dist-packages/ccxt/bittrex.py", line 256, in fetch_balance
>  free = float(balance['Available'])
>  TypeError: float() argument must be a string or a number, not 'NoneType'

Wrapping the type cast in line 256 in bittrex.py in in a try/except block helps but doesn't really seem like a good solution.

Besides that, aawesome project, thank you very much for your efforts!

**Comment by kroitor** [comment]
@mrjingles41 this is fixed in version 1.18.313.

Duplicate: 
- https://github.com/ccxt/ccxt/issues/4754
- https://github.com/ccxt/ccxt/pull/4760

Let us know if upgrading to the most recent version doesn't resolve the issue for you.

**Comment by mrjingles41** [comment]
darn, I walked right into that ...
resolved, thanks!

**Comment by kroitor** [comment]
@mrjingles41 great! Thx for reporting back! ) Don't hesitate if you notice anything suspicious, just make sure that your version is up to date first ;)
