### ISSUE TITLE
Cannot find "/dist/ccxt.browser.js" in ccxt@1.18.315

### ISSUE THREAD

**Issue by crossx4real** [ccxt/ccxt#4773]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by kroitor** [comment]
But it's there: https://github.com/ccxt/ccxt/blob/master/dist/ccxt.browser.js

**Comment by crossx4real** [comment]
> But it's there: https://github.com/ccxt/ccxt/blob/master/dist/ccxt.browser.js

not why the error. I was able to run queries all of yesterday until late last night. wondering if you guys pushed some updates now getting a 404 error

**Comment by kroitor** [comment]
@crossx4real will check that and will get back to you on this.

**Comment by crossx4real** [comment]
error msg: "GET https://unpkg.com/ccxt@1.18.315/dist/ccxt.browser.js 404"

**Comment by kroitor** [comment]
@crossx4real ok, it should work fine now, let us know if you still have difficulties with it (version .18.317). Thx for reporting!

**Comment by crossx4real** [comment]
thanks!

i will donate a fraction of my proceeds once i'm up and running.
