### ISSUE TITLE
Docker image fails ccxt@1.18.321

### ISSUE THREAD

**Issue by cod3gen** [ccxt/ccxt#4775]
- OS: Ubuntu 18.04 Docker
- CCXT version: CCXT version: ccxt@1.18.321 AND ccxt@1.18.320

Was trying to update CCXT to try the changes that where made during the night related to git --ignore-generated-files, but it seems that it fails and complains about missing dependencies;

(This is on a clean repo, and a clean docker image)

> /ccxt/js/base/Exchange.js:1392
>             throw new ExchangeError ('The following npm modules are required:\nnpm install web3 ethereumjs-util ethereumjs-abi bignumber.js --no-save');
>             ^
> 
> Error: The following npm modules are required:
> npm install web3 ethereumjs-util ethereumjs-abi bignumber.js --no-save
>     at theocean.checkRequiredDependencies (/ccxt/js/base/Exchange.js:1392:19)
>     at theocean.describe (/ccxt/js/theocean.js:8:14)
>     at new Exchange (/ccxt/js/base/Exchange.js:361:41)
>     at new theocean (/ccxt/js/theocean.js:6:18)
>     at createExchange (/ccxt/build/export-exchanges.js:107:30)
>     at Array.map (<anonymous>)
>     at Object.<anonymous> (/ccxt/build/export-exchanges.js:108:37)
>     at Module._compile (internal/modules/cjs/loader.js:738:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
>     at Module.load (internal/modules/cjs/loader.js:630:32)

After manually installing the missing libs with "npm install web3 ethereumjs-util ethereumjs-abi bignumber.js --no-save" with an end result like this:

> added 282 packages from 222 contributors and audited 1741 packages in 38.81s
> found 26 vulnerabilities (15 low, 9 moderate, 2 high)
>   run `npm audit fix` to fix them, or `npm audit` for details

While trying to run build again it now fails at JS syntax checks;

> ✖ 1618 problems (1615 errors, 3 warnings)
>   1594 errors, 0 warnings potentially fixable with the `--fix` option.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! ccxt@1.18.321 check-js-syntax: `eslint 'js/*.js'`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ccxt@1.18.321 check-js-syntax script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2019-03-03T08_35_43_967Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! ccxt@1.18.321 build-without-docs: `npm run export-exchanges && npm run vss && npm run check-js-syntax && npm run browserify && npm run transpile && npm run qa && npm run git-ignore-generated-files`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ccxt@1.18.321 build-without-docs script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2019-03-03T08_35_43_985Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! ccxt@1.18.321 build: `npm run build-without-docs && npm run pandoc-all && npm run update-badges`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ccxt@1.18.321 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2019-03-03T08_35_44_003Z-debug.log

**Comment by kroitor** [comment]
@cod3gen pardon, my bad, a leftover after fixing the previous one. Should work in ccxt@1.18.322, can you, please, help test it as well?

**Comment by cod3gen** [comment]
Perfect @kroitor, it now builds as supposed to on a clean repo.
But it seems that it may also have been some changes to expected linebreaks in JS syntax checks, this have worked before on the exchanges i have been working on. The errors is as following;

> Expected linebreaks to be 'LF' but found 'CRLF'

Any way to fix this or should i switch over linebreaks to LF?

**Comment by kroitor** [comment]
> Any way to fix this or should i switch over linebreaks to LF?

In this particular case the easiest fix is to change the linebreaks in the source files. We will later add an auto-correction stage.
