### ISSUE TITLE
brazilex made a slight API change

### ISSUE THREAD

**Issue by grummerd** [ccxt/ccxt#4776]
- OS: n/a
- Programming Language version: python
- CCXT version: current master version
- Exchange: brazilex
- Method: fetch_currencies

In [braziliex.py](https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/braziliex.py) the exchange has made a change to their API

Previously they have the key `minAmountTrade`.

Which has now become three keys

- minAmountTradeBTC

- minAmountTradeFIAT

- minAmountTradeUSDT

Line 112

    - 'min': self.safe_float(currency, 'minAmountTrade'),
    + 'min': self.safe_float(currency, 'minAmountTradeBTC'),

Also i don't understand the design decision to allow a crash on a dict KeyError. When `dict.get(key, 'None')` is available to mitigate the Exception. This case illustrates this issue perfectly. I don't care about the `minAmountTrade`. Sure someone might. But the \(non-\)cure is worse than the disease. Any exchange makes even the slightest API change and ccxt will crash. Should users reinstall daily?! Especially when hardening ccxt is super easy. /rant

**Comment by grummerd** [comment]
Suspect these slight API changes is a daily occurrence.

Here is yet another small API change.

- what those changes were
- exactly how to modify the code

**Comment by kroitor** [comment]
> Also i don't understand the design decision

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

> Any exchange makes even the slightest API change and ccxt will crash.

It's a work in progress. If we fix it – it won't crash. However, from your report, it's not clear where in particular the crash occurs. If you could follow these guides precisely, that would help fix it: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

> Should users reinstall daily?! 

If the exchange changes its API daily, then, yes, most likely, users will want to update frequently.

**Comment by kroitor** [comment]
We will add a proper fix for `minAmountTradeBTC`, `minAmountTradeFIAT`, `minAmountTradeUSDT` soon.
