### ISSUE TITLE
Как добавить файл биржи к вам в проект?

### ISSUE THREAD

**Issue by garik-code** [ccxt/ccxt#4778]
Есть файл биржи midex, как ее добавить в ccxt?

**Comment by kroitor** [comment]
> как ее добавить в ccxt?

Начать можно вот отсюда:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

И далее, нужно убедиться, что код в точности соответствует всем правилам, которые перечислены вот тут:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes
- https://github.com/ccxt/ccxt/wiki/Requirements 

В качестве примеров можно посмотреть на реализации бирж, которые были добавлены недавно. Самое основное, это https://github.com/ccxt/ccxt/wiki/Manual. Там есть ответы и на многие вопросы по архитектуре тех или иных аспектов. Если в процессе возникнут какие-то конкретные вопросы, на которые ответа не найдётся — всегда можно спросить )
