### ISSUE TITLE
Question about: enableRateLimit': true

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#4779]
OS: Windows 10
Programming Language version: Node.js
CCXT version: #465
Exchange: Binance
Node.js 11.9.0 installed
Method: exchange.fetchOrderBook

Hello!

I have a working code below to get the orderbooks for 3 symbols in a loop at Binance.

My question is about the ratelimit. I know Binance has 1200 requests/minute but I am a bit confused when I see the below ratelimit information.

**Should I in my code use: 'enableRateLimit': true ?**

enableRateLimit': true (Takes 3 seconds)
**enableRateLimit': false (Takes 1 second) This is not a good idéa to do?**

Assume that I only would run this code once every minute which would be clearly below 1200 requests/minute. Is there Also a limit as the manual says to ONLY do 1 HTTP requests per 2000 milliseconds as this also can get ones IP banned?

`**"rateLimits": [{
    "rateLimitType": "REQUESTS",
    "interval": "MINUTE",
    "limit": 1200
  },**

### _"rateLimit: A request rate limit in milliseconds. Specifies the required minimal delay between two consequent HTTP requests to the same exchange"_`

```javascript
'use strict';
const ccxt = require('ccxt');
const fs = require('fs');
const path = require('path');


var i;
const exchangename = "binance";
const exchange = new ccxt.binance({
    'enableRateLimit': true
});

(async () => {
    console.log(`start`);
    const start = Date.now();


    var orderbookPromises = []
    var symbols = ['ETH/BTC', 'LTC/BTC', 'ZRX/ETH']
    for (i = 0; i < symbols.length; i++) {

        const symbol = symbols[i]
        
        try {
                let tickerProcessing = new Promise(async (resolve) => {
                    const orderbook = await exchange.fetchOrderBook(symbol, 5);

                    const exchangename2 = exchangename + '#' + symbol.replace("/", "")
                    const dumpFile = path.join(__dirname, 'orderbooks', `${exchangename2}Orderbook.txt`);
                await fs.promises.writeFile(dumpFile, JSON.stringify(orderbook));
                resolve()
            })
            orderbookPromises.push(tickerProcessing)

        } catch (e) {
            console.error(e);
        }
    }

    // wait for all of them to execute or fail
    await Promise.all(orderbookPromises)


    const end = Date.now();
    console.log(`Done in ${(end - start) / 1000} seconds`);
})();

```

**Comment by kroitor** [comment]
> Should I in my code use: 'enableRateLimit': true ?

Depends on what your code does, of course. We can't answer what your code should do )

> enableRateLimit': false (Takes 1 second) This is not a good idéa to do?

It's ok as long as you know what you're doing.

> Assume that I only would run this code once every minute which would be clearly below 1200 requests/minute. 

In that case, the above idea is ok.

> Is there Also a limit as the manual says to ONLY do 1 HTTP requests per 2000 milliseconds as this also can get ones IP banned?

No, there is no such limit defined in the Manual. The Manual says that there's a limit, but the actual threshold value depends on the exchange in question. Each exchange has its own rate-limits. So, you should treat that value in a flexible way. The Manual also says that the default will be sub-optimal, so the user should tweak those values for the needs of his application.

Let us know if that doesn't answer the question.

**Comment by jackpotcityco** [comment]
It was the perfect answer. It was a good confirmation to be on the sure side.
So it is a default value and I should tweak it according the the different exchanges  and usecases then.

Thank you for your help!
