### ISSUE TITLE
Not the same results on 2 different systems

### ISSUE THREAD

**Issue by RomainBlindy** [ccxt/ccxt#4781]
***Config 1
- OS: Windows 10
- Programming Language version: Python 3.7.2
- CCXT version: last
- Exchange: kucoin2
- Method: fetchAccounts

***Config 2
- OS: Raspbian 4.14
- Programming Language version: Python 3.5.3
- CCXT version: last
- Exchange: kucoin2
- Method: fetchAccounts

I have some issues to use my code which works great on "Config1" but not on "Config2".
The main issue is some calls does not return the same.

For example 

`account1=Connect1.fetchAccounts({'currency':Curr1})
 print (account1)`

on Config1 the print gives
`{'trade': {'accountId': 'trade', 'type': 'trade', 'currency': None, 'info': {'balance': '0', 'available': '--------', 'holds': '0', 'currency': 'DACC', 'id': '-------------------', 'type': 'trade'}}, 'main': {'accountId': 'main', 'type': 'main', 'currency': None, 'info': {'balance': '0', 'available': '------', 'holds': '0', 'currency': 'ZPT', 'id': '---------------', 'type': 'main'}}}`

on Config2 i have
`[{'id': '-------------------------', 'info': {'available': --------------', 'holds': '0', 'balance': '----------', 'currency': 'LOKI', 'id': '-----------', 'type': 'trade'}, 'type': 'trade', 'currency': 'LOKI'}, {'id': '-----------', 'info': {'available': '------', 'holds': '0', 'balance': '0', 'currency': 'LOKI', 'id': '--------', 'type': 'main'}, 'type': 'main', 'currency': 'LOKI'}]`

So i have a dict on Config1, a list on Config2 with different constructions.
I'm a newbie in Python and Linux and i'm wondering where it comes from.

Different version of Python ? Different environment ? 

Thanks for help,

Romain

**Comment by kroitor** [comment]
There were some changes towards the unification of accounts recently, so, I suggest to first check that you are really comparing the most recent versions against each other.

Let's add a few lines (and run on both of your systems or both Python versions):

```Python
import sys
# ...
print('Python version:', sys.version_info)
print('CCXT version:', ccxt.__version__)
account1=Connect1.load_accounts({'currency':Curr1})
print (account1)
```

**Comment by kroitor** [comment]
Also: https://www.quora.com/Can-a-Raspberry-Pi-3-run-a-64-bit-OS-or-is-it-limited-to-32-bit

**Comment by RomainBlindy** [comment]
> There were some changes towards the unification of accounts recently, so, I suggest to first check that both systems really have the same version of CCXT.
> 
> Let's add a few lines (and run on both of your systems or both Python versions):
> 
> ```python
> import sys
> # ...
> print('Python version:', sys.version_info)
> print('CCXT version:', ccxt.__version__)
> account1=Connect1.load_accounts({'currency':Curr1})
> print (account1)
> ```

The results : 
**** Config1
```
Python version: sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)
CCXT version: 1.18.247
```

*****Config2
```
Python version: sys.version_info(major=3, minor=5, micro=3, releaselevel='final', serial=0)
CCXT version: 1.18.323
```

**Comment by kroitor** [comment]
These results clearly show that you have different versions of CCXT, and the change was in between, and it kinda answers the question. In other words, you can't compare two different versions for an aspect of functionality (`accounts`) that isn't completely unified or documented in the Manual yet. It is a work in progress. The version 1.18.323 is the format we will adopt for the future, most likely. Let us know if that doesn't resolve the issue.

**Comment by RomainBlindy** [comment]
Thanks a lot, it works.
I definitively have a closer attention to the versions i use.
Have a good day
