### ISSUE TITLE
GDAX API will be fully deprecated on May 15

### ISSUE THREAD

**Issue by marcuswin** [ccxt/ccxt#4782]
I think that it will be good, if we have issue for this. Proof: https://docs.pro.coinbase.com/?r=1

**Comment by kroitor** [comment]
>  Calls to api.gdax.com will now automatically redirect to api.pro.coinbase.com. 

We will keep it listed up to the complete shutdown, for backward compatibility.

**Comment by marcuswin** [comment]
@kroitor API redirect works but redirect on API docs and Coinbase Pro site not working. Check in supported exchanges list.

**Comment by kroitor** [comment]
@marcuswin yep, it is going to be delisted in a matter of a few days. Thx!
