### ISSUE TITLE
Bez coin and eot wallet 

### ISSUE THREAD

**Issue by ALLBITNoCOINS** [ccxt/ccxt#4788]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:windows
- Programming Language version:1
- CCXT version:1
- Exchange:bez and eot had their own
- Method:pretended to have an update going on their site but never came back. ..both exchanges closed and took everyone's crypto from the wallets and never air dropped the coin ..who do I go to for help? Or maybe someone can help me with the guys that were in charge of either one

**Comment by kroitor** [comment]
@ALLBITNoCOINS sorry for your loss, but we're not responsible for those two projects. We would be happy to help, but, I'm afraid, we can't help in this case... It's beyond the scope of this library.
