### ISSUE TITLE
BitMEX api-nonce will not be supported after 12 March 2019.

### ISSUE THREAD

**Issue by mazmex7** [ccxt/ccxt#4789]
- OS: Any
- Programming Language version: Python version Any
- CCXT version: latest
- Exchange: BitMEX
- Method: All of auth methods

Hi, BitMEX has announced that api-nonce will not be supported after 12 March 2019, in their blog.（Now in Korean and Japanese and Russian, not yet in English and Chinese.）
https://blog.bitmex.com/?lang=ja

And in official doc, they wrote `This scheme(nonce), while still supported, has significant problems with multithreaded clients and should not be used. Do not use it for new applications`.

https://www.bitmex.com/app/apiKeysUsage#Authenticating-with-an-API-Key

So, I think that this Lib should support `api-expires` as default, and `milliseconds()` is preferred than `seconds()` to make expires.
Please take care of the code below.

https://github.com/ccxt/ccxt/blob/master/python/ccxt/bitmex.py#L722-L735

```Python
            expires = self.safe_integer(self.options, 'api-expires')
            nonce = str(self.nonce())
            headers = {
                'Content-Type': 'application/json',
                'api-key': self.apiKey,
            }
            if expires is not None:
                expires = self.sum(self.seconds(), expires)
                expires = str(expires)
                auth += expires
                headers['api-expires'] = expires
            else:
                auth += nonce
                headers['api-nonce'] = nonce
```

**Comment by mazmex7** [comment]
Sample fix for above.
```
            headers = {
                'Content-Type': 'application/json',
                'api-key': self.apiKey,
            }
            expires = str(self.milliseconds())
            auth += expires
            headers['api-expires'] = expires
```

**Comment by kroitor** [comment]
> So, I think that this Lib should support api-expires as default, 

I totally agree – we just need to pick a reasonable default value.

> and milliseconds() is preferred than seconds() to make expires.

Because their API expects it in seconds, I don't think an additional arithmetic conversion is unnecessary there, so I would keep it in seconds, if you don't mind. Let me know if I'm missing something.

**Comment by mazmex7** [comment]
Hi, Thanks for your reply 🙂 

`seconds()` is also OK, I suppose.
BitMEX's official implementation is here. 🙂  (`+ 5` is important.)
https://github.com/BitMEX/api-connectors/blob/master/official-http/python-swaggerpy/BitMEXAPIKeyAuthenticator.py#L30

I just care in case that same `api-expires` has sent by multi-threaded clients.

**Comment by kroitor** [comment]
This is now the default as of 1.18.335. We will remove the `nonce`-code on March 12.

**Comment by mazmex7** [comment]
@kroitor Thank you for your commits!

**Comment by kroitor** [comment]
In case someone needs to override it, this is how it's done:

```JavaScript
// JavaScript
const exchange = new ccxt.bitmex ({
    'options': {
        'api-expires': 10, // in seconds
    }
})
```

```Python
# Python
exchange = ccxt.bitmex({
    'options': {
        'api-expires': 10,  # in seconds
    }
})
```

```PHP
// PHP
$id = 'bitmex';
$exchange = '\\ccxt\\' . $id;
$exchange = new $exchange (array (
    'options' => array (
        'api-expires' => 10, // in seconds
    )
));
```
