### ISSUE TITLE
allcoin loadMarkets TypeError 

### ISSUE THREAD

**Issue by NikolayKrishchuk** [ccxt/ccxt#4792]
example:
const ccxt = require('ccxt');

async function main() {
    try {
        const ex = new ccxt['allcoin']()
        await ex.loadMarkets()
    } catch (e) {
        console.log(e)
    }
}

main()

- OS: Ubuntu 16
- Programming Language version: node.js 10.5
- CCXT version: 1.18.338
- Exchange: allcoin
- Method:loadMarkets

**Comment by kroitor** [comment]
Duplicate:

- https://github.com/ccxt/ccxt/issues/2962
- https://github.com/ccxt/ccxt/issues?q=allcoin+is%3Aopen
