### ISSUE TITLE
How is it possible to return JSON for "Exchange Structure" and "Market Structure"

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#4793]
OS: Windows 10
Programming Language version: Node.js
CCXT version: #465
Exchange: All Exchanges
Node.js 11.9.0 installed
Method: Manual#exchange-structure -and- Manual#markets

Hello!

I wonder about those links:
https://github.com/ccxt/ccxt/wiki/Manual#exchange-structure
https://github.com/ccxt/ccxt/wiki/Manual#markets

When looking at those links. There are alot of useful information about each exchange/market.
I have looked in the Manual but are not sure if I can find any way to return a JSON string with any API call to retreive all the information that is shown in the above 2 links?

If that is possible what code can I use to return JSON for this information or is it only possible to return this information from the properties like below?
```javascript
    bitfinex.id;
    bitfinex.name;
    bitfinex.has;

```

Thank you!

**Comment by frosty00** [comment]
```
b = new ccxt.bitfinex()
(async function () {
    console.log(await b.loadMarkets())
) ()
```

**Comment by jackpotcityco** [comment]
> b = new ccxt.bitfinex ()
> (async function () {
>     console.log(await b.loadMarkets ())
> }) ()
> 
> console.log (b.describe ())

Thank you that code worked out well!
