### ISSUE TITLE
can't install ccxt on macos pycares issue

### ISSUE THREAD

**Issue by fuzunspm** [ccxt/ccxt#4798]
- OS: macOS 10.14.3 (18D109)
- Programming Language version: Python 3.7
- CCXT version: none, can't install

i'm getting these errors about pycares during `pip install ccxt'

```
build/temp.macosx-10.14-x86_64-3.7/_cares.c:2573:55: error: too many arguments to function call, expected 6, have 7
      return ares_parse_ptr_reply(x0, x1, x2, x3, x4, x5, x6);
             ~~~~~~~~~~~~~~~~~~~~                         ^~
    /usr/local/include/ares.h:581:14: note: 'ares_parse_ptr_reply' declared here
    CARES_EXTERN int ares_parse_ptr_reply(const unsigned char *abuf,
build/temp.macosx-10.14-x86_64-3.7/_cares.c:4316:14: error: no member named 'ttl' in 'struct ares_mx_reply'
      (void)((p->ttl) | 0);  /* check that 'struct ares_mx_reply.ttl' is an integer */
              ~  ^
    build/temp.macosx-10.14-x86_64-3.7/_cares.c:4332:14: error: no member named 'ttl' in 'struct ares_naptr_reply'
      (void)((p->ttl) | 0);  /* check that 'struct ares_naptr_reply.ttl' is an integer */
              ~  ^
    build/temp.macosx-10.14-x86_64-3.7/_cares.c:4372:14: error: no member named 'ttl' in 'struct ares_soa_reply'
      (void)((p->ttl) | 0);  /* check that 'struct ares_soa_reply.ttl' is an integer */
              ~  ^
    build/temp.macosx-10.14-x86_64-3.7/_cares.c:4386:14: error: no member named 'ttl' in 'struct ares_srv_reply'
      (void)((p->ttl) | 0);  /* check that 'struct ares_srv_reply.ttl' is an integer */
              ~  ^
    build/temp.macosx-10.14-x86_64-3.7/_cares.c:4399:14: error: no member named 'ttl' in 'struct ares_txt_ext'
      (void)((p->ttl) | 0);  /* check that 'struct ares_txt_ext.ttl' is an integer */
              ~  ^
    build/temp.macosx-10.14-x86_64-3.7/_cares.c:4411:14: error: no member named 'ttl' in 'struct ares_txt_reply'
      (void)((p->ttl) | 0);  /* check that 'struct ares_txt_reply.ttl' is an integer */
              ~  ^
    build/temp.macosx-10.14-x86_64-3.7/_cares.c:4666:12: error: no member named 'ttl' in 'ares_mx_reply'
      { "ttl", offsetof(struct ares_mx_reply, ttl),
               ^                              ~~~
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include/stddef.h:120:24: note: expanded from macro 'offsetof'
lots of errors with same output and then

 fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    error: command 'clang' failed with exit status 1
```

**Comment by kroitor** [comment]
Duplicate:

- https://github.com/ccxt/ccxt/issues/4220
- https://github.com/ccxt/ccxt/issues/4020
- https://github.com/ccxt/ccxt/issues/3317
- https://github.com/ccxt/ccxt/search?q=pycares&type=Issues

Basically, the solution is to try a clean reinstall of pycares or another dependent package listed there, due to a version conflict in the environment (probably, multiple pythons installed in parallel). Let us know if that doesn't help.

**Comment by fuzunspm** [comment]
i did read all of them but i don't have conda, so should i install it ?

**Comment by Queeq** [comment]
I have the same issue. Just normal Python 3.7 venv without conda. MacOS 10.14.3 Mojave.

**Comment by kroitor** [comment]
@fuzunspm 

> i did read all of them but i don't have conda, so should i install it ?

No, you should try reinstalling the packages according to the posts above. Or post more info here.

**Comment by kroitor** [comment]
@Queeq 

> I have the same issue. Just normal Python 3.7 venv without conda. MacOS 10.14.3 Mojave.

Need more info, an install log or something to see the issue or to be able to reproduce it. Just the version numbers doesn't tell much. Or describe the steps you've tried already to resolve it. Have you tried updating XCode Dev Tools, for example?

**Comment by Queeq** [comment]
Found this solution: https://github.com/saghul/aiodns/issues/55#issuecomment-456330612

> uninstall c-ares from /usr/local. pycares depends on the bundled version

Had to force uninstall as there are other dependables (e.g. Wireshark): `brew uninstall --ignore-dependencies c-ares` and it solved the issue. Wireshark still works though :)

**Comment by kroitor** [comment]
@Queeq thanks for the feedback, it will be very helpful to others!
