### ISSUE TITLE
loadMarkets incorrectly shows limits for Poloniex

### ISSUE THREAD

**Issue by burzakovskiy** [ccxt/ccxt#4800]
- OS: Ubuntu
- Programming Language version: Node.js 11.10.0
- CCXT version: 1.18.347
- Exchange: Poloniex
- Method: loadMarkets

After upgrade from 1.18.304 to 1.18.347 loadMarkets started to show limits incorrectly for Poloniex
```const ccxt = require('ccxt')

const exchange = new ccxt['poloniex']()

exchange.loadMarkets().then(()=>{
	console.log(exchange.markets['BTC/USDT'].limits)
})
```

1.18.347 Output
```
{ amount: { min: 0.000001, max: 1000000000 },
  price: { min: 1e-8, max: 1000000000 },
  cost: { min: 0, max: 1000000000 } }

```
 1.18.304 Output
```
{ limits:
   { amount: { min: 0.000001, max: undefined },
     price: { min: 1e-8, max: undefined },
     cost: { min: 1, max: undefined } }
```
As you see old version shows correct costs while newer shows 0

**Comment by kroitor** [comment]
Please, follow here: https://github.com/ccxt/ccxt/pull/4777. Those cost minimums were deduced from precision in previous versions which is semantically incorrect, that post explains why.
