### ISSUE TITLE
code":-1021,"msg":"Timestamp for this request is 1000ms ahead of the server's time

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#4801]
OS: Windows 10
Programming Language version: Node.js
CCXT version: #465
Exchange: Binance
Node.js 11.9.0 installed
Method: exchange.fetchBalance()

Hello!

I have a question about the: recvWindow when for example requesting fetchBalance():
```javascript
binance.fetch_balance({'recvWindow': 10000000})
```
I have red this thread:
https://github.com/ccxt/ccxt/issues/773

I wonder if this only works for binance or is there a list of exchanges that support this?
I did get this error message before I looked into a solution:
**code":-1021,"msg":"Timestamp for this request is 1000ms ahead of the server's time**

However the solution that I have ONLY implemented so far are the below:
```javascript
            const adjustForTimeDifference = true
            const options = { adjustForTimeDifference }
            const Exchange = ccxt["binance"];
            const exchange = new Exchange({ options });
```
I also syncronise the computer clock every 10 minutes with:
time.nist.gov

It might be a diffus area but can't help to wonder if my approach that I do should be a good way.
I beleive if I want to send an order within 5 seconds it "could also be dangerous" to use recvWindow with 10000000 if you want the order to be filled in a few seconds?

**Comment by kroitor** [comment]
> It might be a diffus area but can't help to wonder if my approach that I do should be a good way.

Yes, it will work.

> I beleive if I want to send an order within 5 seconds it "could also be dangerous" to use recvWindow with 10000000 if you want the order to be filled in a few seconds?

Not really, that has nothing to do with order filling time, it's more about the time it takes to break the cryptographic security behind your signature, quite hard to explain this in a short post on GitHub. I've tried to explain it here: https://github.com/ccxt/ccxt/issues/850#issuecomment-382787816. Let us know if that doesn't answer your questions. Feel free to reopen this if needed or just ask further questions, if you have more.

**Comment by jackpotcityco** [comment]
Then I understand, I red the link you posted and got a good understanding of your explanation.
Thank you for your help!
