### ISSUE TITLE
Cryptopia loadMarkets returns DDOSProtection exception

### ISSUE THREAD

**Issue by MarcelBeining** [ccxt/ccxt#4805]
- OS: Windows 10 64bit
- Programming Language version: Python 3.6
- CCXT version: 1.18.353
- Exchange: cryptopia
- Method: all methods

Cryptopia only returns these Cloudflare errors when fetching/loading something. I did not change any API keys or settings since last time when it worked (~2 months ago).
Methods tested: fetchBalance, loadMarkets, loadFees, fetchOpenOrders, fetchOrderbook

**Comment by kroitor** [comment]
I'm getting the same results from whatever location I try around the globe... Looks like this **documented** endpoint is being blocked by their Cloudflare protection: https://www.cryptopia.co.nz/api/GetTradePairs

<img width="1193" alt="Screen Shot 2019-03-09 at 22 53 14" src="https://user-images.githubusercontent.com/1294454/54076562-2a281480-42be-11e9-88be-7f194a97074f.png">

Also, there were news that Cryptopia was hacked earlier in January this year:

- https://www.ccn.com/crypto-exchange-cryptopia-hack-reopen-nz
- https://cointelegraph.com/news/analysis-hackers-liquidated-32-million-in-tokens-from-cryptopia-hack
- https://www.chepicap.com/en/news/7157/cryptopia-hack-timeline-as-it-happened.html

So, I'm not sure if users can rely on Cryptopia API, can confirm or disconfirm, their support never replied to us, not even once. Have you tried reaching out to their tech support? Maybe, you will have a better luck that us?

**Comment by cod3gen** [comment]
They're trading servers seems offline or disabled at the moment, which probably is the reason for <Access denied>. Give them some days to get the exchange back online properly.

**Comment by kroitor** [comment]
https://www.coindesk.com/cryptopia-exchange-resumes-crypto-trading-amid-banking-issues

**Comment by MarcelBeining** [comment]
Yep, same for me...

**Comment by kroitor** [comment]
Finally, it works )

**Comment by kroitor** [comment]
Now it's shutdown again: https://github.com/ccxt/ccxt/issues/5151
