### ISSUE TITLE
How to retrieve all symbols/orders with fetchClosedOrder()

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#4810]
OS: Windows 10
Programming Language version: Node.js
CCXT version: #465
Exchange: Binance
Node.js 11.9.0 installed
Method: exchange.fetchClosedOrder

Hello!

I use this code to fetchClosedOrder() for: ETH/BTC on binance. I am not sure how it would be possible to retreive ALL closed orders since the startingdate. Which will include all symbols/orders that has been closed since that startingDate?
```javascript
const symbol = 'ETH/BTC'
const startingDate = '2017-01-01T00:00:00';
let since = exchange.parse8601(startingDate) //binance exchange here
const closedorders = await exchange.fetchClosedOrders(symbol, since)
```
Thank you!

**Comment by kroitor** [comment]
Hi!

> I am not sure how it would be possible to retreive ALL closed orders since the startingdate.

First of, please, read this: https://github.com/ccxt/ccxt/wiki/Manual#pagination

Exchanges will not allow to get **all** orders for all pairs and all dates at once – that's a very heavy request, and they will not serve it. However, they will allow you to fetch your closed orders by symbol if you specify the date range. Thus, if you know your starting date and you want to iterate over your traded symbols. 

Here's a pseudocode example:

```JavaScript
const symbols = [
    'ETH/BTC',
    'BTC/USDT',
    // add more or retrieve non-zero balances and symbols
]
// alternatively, iterate over all symbols supported by the exchange
// const symbols = exchange.symbols

const result = {};

// traverse each symbol
for (let symbol of symbols) {

     result[symbol] = []

    // paginatiate over date ranges, as described in the Manual and in the examples...

    let since = exchange.parse8601('2017-01-01T00:00:00')
    const limit = 50 // or whatever the exchange will accept

    while (since < exchange.millisecons ()) {

        // 1. fetch the orders
        const orders = await exchange.fetchClosedOrders (symbol, since, limit)

        // 2. append them to your current results
        result[symbol].concat (orders)

        // 3. shift the since to start from the last order received
        if (orders[orders.length - 1]['timestamp'] > since) {
            since = orders[orders.length - 1]['timestamp']
        } else {
            break
        }
    }
}
```

↑ This is not supposed to be launched as is, more for the demonstration purposes. The actual traversion algorithm and values will depend on your business logic, but, anyways, from here you can add the edits to handle your application tasks where necessary. Hope this answers the question.

See also:

- https://github.com/ccxt/ccxt/tree/master/examples

**Comment by jackpotcityco** [comment]
Yes then I understand, it was good to be on the sure side. Then I will need to use the pagination technique.
Thank you also for the pseudocode example. It gave a very good example of how to do it.

Thank you!
