### ISSUE TITLE
method to return v1 trade history from kucoin

### ISSUE THREAD

**Issue by MarcelBeining** [ccxt/ccxt#4814]
- OS: Windows 10 64 bit
- Programming Language version: Python 3.6
- CCXT version: 1.18.353
- Exchange: kucoin
- Method: fetchMyTrades

Unfortunately, kucoin is distinguishing between trades since API v2 (endpoint `/api/v1/orders`) and trades from old kucoin version (endpoint `/api/v1/hist-orders`). It seems ccxt has only implemented the first url in `fetchMyTrades`. Could you please also implement the other one? Does not have to be an additional method, simply use endpoint `/api/v1/hist-orders` if `since` is earlier than 2019-02-18 (the day the kucoin platform changed) and concatenate with results from the other endpoint.

**Comment by kroitor** [comment]
Will fix this shortly. The `hist-orders` endpoint was added not very long ago. We will restore the old parser from v1 and will add a patch asap. Will let you know immediately, of course.

**Comment by MarcelBeining** [comment]
Actually the same is true for the withdrawal and deposit endpoint!
See
https://docs.kucoin.com/#get-v1-historical-withdrawals-list
and
https://docs.kucoin.com/#get-v1-historical-deposits-list

**Comment by kroitor** [comment]
@MarcelBeining thank you! I'll do both trades and transactions today and will update you here when the edits arrive.

**Comment by MarcelBeining** [comment]
any news on that? :-)

**Comment by MarcelBeining** [comment]
Hi @kroitor , I guess you're quite busy with a lot of stuff but can you give an estimate on when the changes will be released? Need the history for my current tax report and would try to find a workaround if it will take longer than a week. Thanks!

**Comment by kroitor** [comment]
@MarcelBeining i really hope to get to it practically any day, probably even today, and i'm sure i'll close this issue before the end of the week. Pardon for the delay again, i know the wait is frustrating. Will do my best to resolve this soon, it's high among my priorities.
