### ISSUE TITLE
huobiru - couldn't to fetch balance

### ISSUE THREAD

**Issue by DmitryVil** [ccxt/ccxt#4818]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10
- Programming Language version: python
- CCXT version: ccxt-1.18.354
- Exchange: huobiru
- Method:fetch_balance()

Hey,

I couldn't fetch balance after initiation.
Please see an attachment.

Thank you,

Dmitry

![HuobiRu](https://user-images.githubusercontent.com/35109659/54201754-58784080-44c6-11e9-97f3-60b7793d9d20.PNG)

**Comment by kroitor** [comment]
I think, Huobi Ru keys are not interchangeable with Huobi keys. Are you sure that your keys are correct?

**Comment by DmitryVil** [comment]
I think the keys are OK.
I signed up on Huobi Russia

**Comment by kroitor** [comment]
@DmitryVil you've signed up with huobi pro and created the keys there – is that correct? If that is the case, then make sure your credentials are indeed correct.

You can try my keys as well:

```Python
import ccxt
from pprint import pprint
exchange = ccxt.huobiru({
        "apiKey": "47189c8b-a200b3e3-45e94a36-41130",
        "secret": "5b0fdf41-20ccb96e-07284ad3-1fb2f"
        "enableRateLimit": True,
})
pprint(exchange.fetch_balance())
```

**Comment by kroitor** [comment]
Let me know if that doesn't help.

**Comment by DmitryVil** [comment]
Please look at this:
![HuobiRu](https://user-images.githubusercontent.com/35109659/54228985-3d73f380-44fb-11e9-9a52-9b0a58f63559.PNG)
