### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#4825]
```
npm run build
...

> ccxt@1.18.361 update-badges /Users/nickpomfret/projects/ccxt.fork
> node build/update-badges

Preparing for PyPI → ./python/README.rst (<anonymous> @ update-badges.js:18)
/Users/nickpomfret/projects/ccxt.fork/build/update-badges.js:30
let rstExchangeTableLines = match[2].split ("\n")
                                 ^

TypeError: Cannot read property '2' of null
    at Object.<anonymous> (<...>/ccxt/build/update-badges.js:30:34)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ccxt@1.18.361 update-badges: `node build/update-badges`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ccxt@1.18.361 update-badges script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

- OS: os x
- Programming Language version: node 8.14.0
- CCXT version: "1.18.361"

**Comment by kroitor** [comment]
Try
 
```
git pull
git checkout origin/master -- python/README.rst
```

And then rebuild again – does that help?

**Comment by npomfret** [comment]
It didn't work.

**Comment by kroitor** [comment]
@npomfret that's interesting... I'm on OSX as well... But my node version is 9.2.0. Can you post a gist with your current `python/README.rst` ? Or, maybe, upload a compacted version of your repo with just a couple of exchange files for debugging?

**Comment by npomfret** [comment]
https://gist.github.com/npomfret/a462e9305b77fc5eb6986853e189f685

This is my fork: https://github.com/npomfret/ccxt

**Comment by kroitor** [comment]
@npomfret i've cloned it into a clean directory, did `npm install && npm run build` in it, and it worked... Could this be an issue with the node version? Can you check if Node 9 or 10 makes a difference?

**Comment by kroitor** [comment]
@npomfret actually, after thinking more on this, I suppose the issue is caused by a difference in pandoc versions... Can you tell which pandoc version is it? 

```
mbp:ccxt igorkroitor$ pandoc --version
pandoc 1.19.2.1
```

Should be 1.19+, not 1.12. Can you verify?

**Comment by npomfret** [comment]
```
 pandoc --version
pandoc 2.7

```

**Comment by kroitor** [comment]
@npomfret can you check if rebuilding with pandoc 1.19.2.1 makes a difference on your side? If it does, then we will add workarounds for this. Your help is much appreciated!

**Comment by npomfret** [comment]
I tried to downgrade using homebrew, but when searching for earlier versions to install I got this (which I didn't really understand)

```
brew search pandoc
==> Formulae
pandoc ✔                                                                       pandoc-citeproc                                                                pandoc-crossref

If you meant "pandoc" specifically:
It was migrated from homebrew/cask to homebrew/core.
```

... I was expecting to see a bunch of different versions of pandoc.

Any ideas?

**Comment by xpl** [comment]
@npomfret Sorry for not responding for too long. Just curious — did you figure how to solve the issue? 

We suggest to use Docker for building/testing/developing CCXT, to avoid the need of installing all the dependencies to your dev machine — which can be really troublesome in some cases.

If you're using OSX it is easy:

1. Install Docker for Mac: https://download.docker.com/mac/stable/Docker.dmg
2. Clone the CCXT repo, `cd` to it, then run ```docker-compose run --rm ccxt```

After some minutes of downloading and building the dependencies, you will get into the bash shell where you can run CCXT's build scripts without problem.

**Comment by npomfret** [comment]
Hi, sorry for the very slow reply.

I didn't resolve it.  In fact just tried installing on a new machine and got the same error:

```
Preparing for PyPI → ./python/README.rst (<anonymous> @ update-badges.js:18)
/Users/nickpomfret/projects/ccxt.fork/build/update-badges.js:30
let rstExchangeTableLines = match[2].split ("\n")
                                 ^

TypeError: Cannot read property '2' of null
    at Object.<anonymous> (/Users/nickpomfret/projects/ccxt.fork/build/update-badges.js:30:34)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
```

All I've done is install node12 (via nvm), tox and pandoc.

```
$ python --version
Python 2.7.10
$ node --version
npv12.1.0
$ npm --version
6.9.0
```

I have run the build successfully in the past so I suspect something has changed.

One question I have: the manual says 

> Python 3.5.3+ and Python 2.7+

What does this mean?

**Comment by frosty00** [comment]
what command are you using to install?

**Comment by npomfret** [comment]
`npm run build`

**Comment by frosty00** [comment]
that's not an installation issue, that's an issue with the built script. 

```
> ccxt@1.18.509 update-badges /Users/carlorevelli/Documents/important/code/ccxt
> node build/update-badges

Preparing for PyPI → ./python/README.rst (<anonymous> @ update-badges.js:18)
Updating exchange count → ./README.md (updateExchangeCount @ update-badges.js:65)
Updating exchange count → ./python/README.rst (updateExchangeCount @ update-badges.js:65)
Badges updated successfully. (<anonymous> @ update-badges.js:80)
```

And it's working on my end...

**Comment by npomfret** [comment]
I suspect my version of pandoc is causing the problem and generating something that the regular expressions in `update-badges` cannot parse.  Downgrading with homebrew doesn't appear to be an option for some reason.

I'm surprised no-one else is seeing the same thing as I'm installing the only version of pandoc that seems to be available on a Mac.

**Comment by xpl** [comment]
@npomfret Try `npm run build-without-docs` instead of `npm run build`, it does exactly what it says :)

Also, did you try Docker?

**Comment by o3o3o** [comment]
I meet the same problem too.

node: v11.14.0
npm: 6.9.0
python: 3.6.5
pandoc 2.7.2

I just run `npm run build` on master, which generate different files, include: `python/README.rst`.

Below are the difference of `python/README.rst`, the left is origin master file and the right is the new generated file.
![image](https://user-images.githubusercontent.com/4308542/60162496-3c599e80-982c-11e9-96c5-48c60bb2dc06.png)

**Comment by kroitor** [comment]
@o3o3o thx for the followup! We will switch to md `long_description_format` for the python package in the coming days, so the README.rst will be excluded from the build.

**Comment by gizlu** [comment]
Same problem here despite using docker.
`npm run build-without-docs` builds without errors.

**Comment by kroitor** [comment]
@gizlu what's your version of CCXT? The docker image in the repo has been updated a few days ago – are you using the new docker file, or the old one?

**Comment by gizlu** [comment]
Update to 1.27.89 changed nothing.

**Comment by kroitor** [comment]
@gizlu nope, i don't mean updating the ccxt version inside the running image, i mean updating the docker image itself. If you still have issues with – let me know, I will do my best to get to it asap.

**Comment by gizlu** [comment]
> i mean updating the docker image itself.
I have pulled from upstream master and rebuilded docker image

**Comment by kroitor** [comment]
@gizlu will get this resolved shortly: https://github.com/ccxt/ccxt/issues/4195#issuecomment-629855887
