### ISSUE TITLE
The "percentage" is not returned for all exchanges in loadMarkets()

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#4828]
OS: Windows 10
Programming Language version: Node.js
CCXT version: #465
Exchange: All Exchanges
Node.js 11.9.0 installed
Method: exchange.loadMarkets()

Hello!

I have a question about the **"percentage"** parameter when requesting:
```javascript
const markets = await exchange.loadMarkets()
```
I could see that for some exchanges **"percentage"** is present in the returnd JSON and other exchanges not. If looking at the below example binance has **"percentage"** and coinex doesn't.

For coinex, this information is shown. Then I wonder how to think. Is this **"percentage"** or not. I am bit confused there?
**"taker":0.001,"maker":0.001**

**JSON for binance and coinex:**
**coinex**
"BBN/BCH":{"limits":{"amount":{"min":1},"price":{"min":1e-8}},"precision":{"amount":8,"price":8},"taker":0.001,"maker":0.001,"id":"BBNBCH","symbol":"BBN/BCH","base":"BBN","quote":"BCH","baseId":"BBN","quoteId":"BCH","active":true

**binance**
"ETH/BTC":{"limits":{"amount":{"min":0.001,"max":100000},"price":{},"cost":{"min":0.001}},"precision":{"base":8,"quote":8,"amount":3,"price":6},"tierBased":false,"percentage":true,"taker":0.001,"maker":0.001,"id":"ETHBTC","symbol":"ETH/BTC","base":"ETH","quote":"BTC","baseId":"ETH","quoteId":"BTC"

**Comment by kroitor** [comment]
> Then I wonder how to think. Is this "percentage" or not. I am bit confused there?

In general, it's always a percentage, unless percentage is defined (not undefined) and has a value of `false`. If you don't see it defined anywhere or it has a value different from `false`, then it's true. 

So, in this particular case you can assume percentages safely.

Let us know if that doesn't answer the question. We will unify this aspect with coinex and other exchanges, thx for reporting!

**Comment by jackpotcityco** [comment]
> In general, it's always a percentage, unless percentage is defined (not undefined) and has a value of false. If you don't see it defined anywhere or it has a value different from false, then it's true.

Thank you for the clarification. I will go with percentages then. 
That is great to find something that can help out for the library!
