### ISSUE TITLE
New Exchange: chaoex

### ISSUE THREAD

**Issue by 317459062** [ccxt/ccxt#4829]
OS:windows
Programming Language version:python3.5
CCXT version:1.18.76
Exchange:chaoex
Method:all

website:https:   www.chaoex.info/home
chaoex api:  https://github.com/chaoexUser?tab=repositories

thanks

**Comment by An-Net** [comment]
> The cryptocurrency exchange ChaoEX is currently closed and its website is offline.

- https://www.cryptowisser.com/exchange/chaoex/?lang=ru

- https://cryptogeek.info/en/exchanges/chaoex

- ![Снимок экрана 2020-09-27 в 22 54 25](https://user-images.githubusercontent.com/51840849/94374360-73e08600-0114-11eb-9a2f-73ab68487ece.png)
