### ISSUE TITLE
itbit fees changing on 14th march

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#4830]
Just had a slightly confusing email from itbit.  But it looks like from the 14th March (today) they are offering a -0.03% maker fee (a rebate).

But, their taker fee is going up to 0.35% (from 0.25%), although this isn't reflected on their website.  I have asked them for clarification.

**Comment by kroitor** [comment]
They've updated the fee schedule on their website on 6PM March 14, i've uploaded the edit that reflects this. Thx for reporting!
