### ISSUE TITLE
gatecoin exchange is down

### ISSUE THREAD

**Issue by jjhesk** [ccxt/ccxt#4831]
As you may know, following our issues with our banking partners in September last year, we started working with a Payment Service Provider (“PSP”) which is a fully regulated payment institution by the French regulator. However, that PSP failed to process most of the transfers in a timely manner which in turn almost paralyzed our operation for many months and caused substantial loss on our side.

Even after we managed to mitigate our loss by replacing that PSP with more reliable alternatives to process our clients’ transfers in September 2018, the situation did not improve because that PSP retained a large part of our funds. After months spent trying to recover those funds, we commenced legal action against that PSP but were advised that it is unlikely that we would be able to recover the funds from them in full.

In light of the circumstances, we have suffered financial difficulty over a period time to an extent that we are no longer able to support our operation. On 13 March 2019, the court has granted a winding-up order against our company. A provisional liquidator has been appointed and we have to cease operation with immediate effect.  Please rest assured that we will assist the liquidation process in order to expedite the realization and redistribution of our assets to the creditors.

Once again, we thank you for your support over the years and apologize for the inconvenience that may cause
The Gatecoin Team

**Comment by kroitor** [comment]
@jjhesk thank you for reporting! Will have to take it down...
