### ISSUE TITLE
Deribit v2 API

### ISSUE THREAD

**Issue by fonzmeister** [ccxt/ccxt#4833]
Deribit released a new API. V1 will be phased out in time, there is no date set.
So it has no hurry (for now)

API doc: https://docs.deribit.com/v2/#deribit-api-v2-0-0

**Comment by kroitor** [comment]
Thanks for the update, will add the updates it as soon as we can. 

Your contributions are welcome )

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

**Comment by fonzmeister** [comment]
Thanks. And honestly I gave it a go for the kraken futures, but I'm an experienced python dev. Nodejs is not my thing at all

**Comment by kroitor** [comment]
>  but I'm an experienced python dev. Nodejs is not my thing at all

Because of how our multi-language support is structured, you can code a new integration within our js framework, if you know python very well.

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

Our transpilation framework is made very readable to coders coming from different programming camps – that is by design, in other words, we tried to simplify it as much as possible for that reason. 

So, if you open:

- https://github.com/ccxt/ccxt/blob/master/js/kraken.js
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/kraken.py
- https://github.com/ccxt/ccxt/blob/master/php/kraken.php

... and compare them briefly – you will immediately notice that they correspond line-to-line literally. And, all of a sudden you will find yourself being able to code in three or more languages at once. In other words, you may think that your knowledge is limited to Python, but if you know Python well, then, all of a sudden it turns out that you can read and code in other languages also )))

**Comment by V-kik** [comment]
Hi guys,

I see that deribit Rest API v1 is implemented in ccxt. You are using the sha256 signature method and put the signature into the header of every request. 

I am currently trying to sign HTTP GET requests on the api v2 (see docs here: https://docs.deribit.com/v2/?shell#authentication). Deribit has changed the signature to hmac-sha256. I don't manage to get the signature working. My sample python code is below. Probably you can fix this and then use the signature method to use API v2 in ccxt?

import hmac
import hashlib 
import binascii
import random
import time
import requests

def generate_nonce(length=8):
    """Generate pseudorandom number."""
    return ''.join([str(random.randint(0, 9)) for i in range(length)])

def create_sha256_signature(ClientSecret, StringToSign):
    signature_computed = hmac.new(
        key=ClientSecret.encode('utf-8'),
        msg=StringToSign.encode('utf-8'),
        digestmod=hashlib.sha256
    ).hexdigest()
    return signature_computed

ClientId ="XXX"
ClientSecret = "XXX"
timestamp = str(int(time.time()* 1000))
nonce = generate_nonce(length=10)
endpoint= "/api/v2/private/get_account_summary?currency=BTC"
HTTP_METHOD = "GET"

RequestData = HTTP_METHOD + "\n" + endpoint + "\n" + ""
StringToSign = timestamp + "\n" + nonce + "\n" + RequestData.upper()

signature = create_sha256_signature(ClientSecret, StringToSign)
headers = {"Authorization": "deri-hmac-sha256 id="+ClientId+",ts="+timestamp+",sig="+signature+",nounce="+nonce+""}
print("Headers:" + str(headers))
print("\n")
r=requests.get("https://test.deribit.com/api/v2/private/get_account_summary?currency=BTC",headers=headers)
print("Response:" + str(r.json()))

**Comment by kroitor** [comment]
@V-kik i'm afraid, it's not possible to switch from v1 to v2 just by changing the signing procedure - their API endpoint names and formats have changed, so, it requires a complete overhaul. We hope to get to it asap.

**Comment by TensorTom** [comment]
Bump to this. Very much need v2 api because v1 can't do $1 contracts. I'd contribute but this sort of javascript isn't really my bag.

**Comment by CryptoGnome** [comment]
I am also bumping, excited to see v2 get added. Thank you to everyone contributing!

**Comment by yanis7774** [comment]
how to get /public/get_tradingview_chart_data from deribit through ccxt?

**Comment by kroitor** [comment]
@yanis7774 deribit does not have that endpoint. To see the list of all available endpoints, please, read the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

**Comment by mattou78400** [comment]
Not sure how far it got here, but bumping as Deribit just announced the deprecation of their API V1 early October

How can I help if I only know a bit of python?

**Comment by kroitor** [comment]
>  How can I help if I only know a bit of python?

Start with reading the CONTRIBUTING doc and make sure you understand it: 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

According to our fundamental principles regarding portability, you don't have to know multiple languages to contribute code, because we encourage designing the code to be easily-readable by any programmer, check out the details on [Multilanguage support](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support) ) Thx! )

**Comment by lacksfish** [comment]
I'm working on the v2 upgrade for ccxt already. Mostly done, couple more days.

**Comment by kroitor** [comment]
@lacksfish awesome! Thx for letting us know! Looking forward! )

**Comment by lacksfish** [comment]
https://github.com/ccxt/ccxt/pull/5546

Still have some issues with the transpiled python tests, the JS tests run through a-ok. Any tips?

**Comment by blakdragan7** [comment]
@lacksfish how's this coming along ?

**Comment by p0nt** [comment]
1 month until the v1 API deprecates.

**Comment by orikalinski** [comment]
If someone is interested in working python version, I adjusted the code that @lacksfish kindly added here.
https://github.com/orikalinski/ccxt_lite/blob/deribit/python/ccxt/deribit2.py

**Comment by acrabb** [comment]
@orikalinski what is the difference?

**Comment by orikalinski** [comment]
@acrabb 
precisionMode,
symbols unification
fetch markets precision and limits
added new methods
different sign method
small fixes such as cost which is multiplied by price although need to be divided (the amount is in contracts and the cost is in BTC/ETH)
slight changes in handle errors
python formatting conventions

**Comment by mattou78400** [comment]
> If someone is interested in working python version, I adjusted the code that @lacksfish kindly added here.
> https://github.com/orikalinski/ccxt_lite/blob/deribit/python/ccxt/deribit2.py

Hi,

All the functions have the same names and parmeters, it has only been adjusted to APIv2, correct?

Thanks for that!

**Comment by XhrCkYsSgZokJL** [comment]
> @acrabb
> 
> 1. precisionMode,
> 2. symbols unification
> 3. fetch markets precision and limits
> 4. added new methods
> 5. different sign method
> 6. small fixes such as cost which is multiplied by price although need to be divided (the amount is in contracts and the cost is in BTC/ETH)
> 7. slight changes in handle errors
> 8. python formatting conventions

For some reason the hmac library was spitting out invalid hashes for deribit. 

Replacing the sig gen with 

`import hmac, hashlib`

`signature = hmac.new(self.encode(self.secret), self.encode(string_to_sign), hashlib.sha256).hexdigest()` 

fixed it for me.

**Comment by Maximilian10** [comment]
Hi, so there will be V2 deribit support on ccxt?

**Comment by vladyosifov** [comment]
any implementation for the PHP library on V2 ? Until when we can use ccxt php v1 ?

**Comment by riaworks** [comment]
When will we have Deribit V2 for PHP?
Anything I can help with?
Thanks!

**Comment by kroitor** [comment]
@riaworks 

> When will we have Deribit V2 for PHP?

We hope to resolve the backlog of integrations very soon after releasing CCXT Pro, that is expected any day now.

> Anything I can help with?

Yes, you can try and submit a complete and working transpilable integration, based on the work by @lacksfish and @orikalinski from this issue using the following guidelines: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code .

**Comment by etiennez0r** [comment]
Hello, wanted to know if Deribit V2 will be out soon? i'm wanting it for using the /private/get_position endpoint.

Also would like to know about ccxt pro.

Thanks

**Comment by kroitor** [comment]
@etiennez0r hi!

> Hello, wanted to know if Deribit V2 will be out soon?

Yes, we hope to get it resolved soon after releasing CCXT Pro.

- https://github.com/ccxt/ccxt/pull/5546

> Also would like to know about ccxt pro.

Please, check out the following:

- https://github.com/ccxt/ccxt/issues/56#issuecomment-507290536
- https://github.com/ccxt/ccxt/issues/6332

**Comment by kroitor** [comment]
Deribit v2 has been added in CCXT 1.23.88+: https://github.com/ccxt/ccxt/issues/6602
