### ISSUE TITLE
Unified Margin/Position/Leverage Trading via CCXT

### ISSUE THREAD

**Issue by lampardlamps** [ccxt/ccxt#4834]
Can I margin trade on OKEX/Gate.io/Bibox through ccxt please? The operations involved are:
1. find pair - e.g. EOS/USDT
2. transfer coins into the account of the specific pair;
3. borrow money;
4. market order buy/sell using the coins owned+borrowed.

I did not manage to find relevant functions by print(dir(ccxt._okex/gateio_)), and would be grateful for any advice, thank you!

**Comment by lampardlb** [comment]
update: contact Gate.io customer service and apparently borrowing cannot be done via API, so no bother. No sure about OKEX though.

**Comment by alexeymarunin** [comment]
And I'm interested in [BitMEX](https://www.bitmex.com/) margin trading too

**Comment by kroitor** [comment]
@lampardlb 

> Can I margin trade on OKEX/Gate.io/Bibox through ccxt please? The operations involved are:

@alexeymarunin 

> And I'm interested in BitMEX margin trading too

Because CCXT library supports all their endpoints with corresponding API versions, you can actually margin-trade with those exchanges using CCXT implicit methods, as described here: 

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

So, the answer to your questions is: yes, you can margin-trade with those exchanges using CCXT in exchange-specific way.

However, I believe, you're not really asking if you can do margin/positional trading, but more about the *unified margin trading* with CCXT. And that aspect isn't unified yet. We will write out a proposal for the unification of margin/positional/leveraged trading here soon.

Actually, the help of the community would be very much appreciated! So, we have a relative set of methods, the unified order methods, and I suggest that the unified API for positional trading should be derived from the existing order APIs:

```JavaScript
async fetchPosition (id, symbol = undefined, params = {})
async fetchPositions (symbol = undefined, since = undefined, limit = undefined, params = {})
async fetchOpenPositions (symbol = undefined, since = undefined, limit = undefined, params = {})
async fetchClosedPositions (symbol = undefined, since = undefined, limit = undefined, params = {})
async fetchPositionTrades (id, symbol = undefined, since = undefined, limit = undefined, params = {})
async fetchPositionStatus (id, symbol = undefined, params = {})
...
```

And we need to derive a unified `position` structure:

```JavaScript
{
    'info': { ... }, // raw response from the exchange
    'id': '1a2b3c', // position id, string
    'symbol': 'ETH-BTC-INDEX', 
    'timestamp': 123124234, // opening timestamp
    'datetime': '2019-03-...', // ISO8601
    'status': 'open', // 'closed', 'canceled', other?
    'amount': 123.45, // position volume?
    'filled': 54.321, // traded volume?
    'profit': ?, // ?
    'margin': ?, // ?
    'leverage': ?, // ?
    'fee': {
        // ?
    }, 
    'trades': [ 
        { ... unified trade structure },
        { ... unified trade structure }, 
        ...,
    ],
    ... ?
}
```

↑ We need to work through all the above question marks. Suggestions, proposals, opinions and comments are welcome.

**Comment by lampardlb** [comment]
Thank you for the useful information @kroitor

**Comment by brandsimon** [comment]
@kroitor 
Could another status be liquidated?
You can only determine the profit after a position is closed. (So you probably need to return None, if this is not the case). I think a simple ROI calculation is enough here, but since you need the Profit for this, you can return it anyway.

Isnt a position only an abstraction of multiple trades with the same symbol (where start and end balance is zero)?
So maybe before providing an API for this abstraction, focus on plain margin trading first?

**Comment by kroitor** [comment]
> Could another status be liquidated?

Technically, we can do just about anything ) But wouldn't that make it actually harder to distinguish between an open or closed position? I'm thinking in terms of current positions and historical positions. Or do I miss something?

> You can only determine the profit after a position is closed. (So you probably need to return None, if this is not the case).

Sure.

> Isnt a position only an abstraction of multiple trades with the same symbol (where start and end balance is zero)? So maybe before providing an API for this abstraction, focus on plain margin trading first?

Yep, I think we can approach this gradually, I'm all for it ) Should we cut it that structure down or... ?

Thx for your comments, they're always helpful, really appreciate your participation! Don't hesitate if you have more considerations on this matter.

**Comment by brandsimon** [comment]
@kroitor
> Technically, we can do just about anything ) But wouldn't that make it actually harder to distinguish between an open or closed position? I'm thinking in terms of current positions and historical positions. Or do I miss something?
If we already have closed/canceled, we need to check if the status is not open, to check if it is closed.
Liquidated does not change anything or do I miss something? (It would be different if we add another status indicating open)
If I miss something, does it make sense, to provide two fields? One is just a bool, the other is more descriptive?

> Should we cut it that structure down or... ?
Personally I would begin with the margin order functions.
create margin limit/market/stop orders, cancel/get margin orders. (Is there an exchange supporting margin trading, but not supporting stop orders?)

I think, create/cancel bulk operations are important.
To support this, there should probably a method to create an order object, then you can call it several times and pass the results in an array to something like create_margin_order_bulk.
 
> Thx for your comments, they're always helpful, really appreciate your participation! 
Great to hear that, thank you! It is also a pleasure to work with you.

**Comment by kroitor** [comment]
> If we already have closed/canceled, we need to check if the status is not open, to check if it is closed.

Right.

> Liquidated does not change anything or do I miss something? (It would be different if we add another status indicating open)

I'd say when a position is liquidated, it gets closed or canceled by the exchange, depending on the exchange in question.

> If I miss something, does it make sense, to provide two fields? One is just a bool, the other is more descriptive?

Yes, in fact, we've been planning to add more to the unified structured, namely, the `closed`, `canceled`, `opened` flags, but we were thinking of following the more general approach, those won't be booleans, but will be integer timestamps in milliseconds or `undefined/None/null`. Which technically works as boolean flags, but can also be used to designate the state. And we will keep the status string as well.

> Personally I would begin with the margin order functions.
> create margin limit/market/stop orders, cancel/get margin orders. (Is there an exchange supporting margin trading, but not supporting stop orders?)

I'll need to review their APIs to answer, but, thx for the suggestion!

> I think, create/cancel bulk operations are important.
> To support this, there should probably a method to create an order object, then you can call it several times and pass the results in an array to something like create_margin_order_bulk.

Alternatively, we could accept an array of unified order structures, and build the array of values in exchange-specific format inside the `create_orders`. We actually think of switching to a new schema for method signatures, where each method would accept an object with key-value arguments instead of passing the arguments separately, so, we will augment `createOrder (symbol, type, side, amount, ...` with `createOrder ({ symbol: ..., type: ... })` ← and taking it further from there – the user would simply compile an array of those and pass them into `createOrders`. In general, bulk orders aren't really a feature of margin trading, many exchanges allow placing plain immediate orders in bulk. But, you're right, we'll have to add those as well. Will do my best to address that soon. Thx again!

**Comment by alexeymarunin** [comment]
> We actually think of switching to a new schema for method signatures, where each method would accept an object with key-value arguments instead of passing the arguments separately, so, we will augment createOrder (symbol, type, side, amount, ... with createOrder ({ symbol: ..., type: ... }) 

Finally)

**Comment by brandsimon** [comment]
@kroiter:
Both alternatives sound great, agreed! :)
Do you already have an interface definition for that, so it is possible to start implementing some margin functions?

**Comment by kroitor** [comment]
@brandsimon 

> Do you already have an interface definition for that, so it is possible to start implementing some margin functions?

Not yet, got buried in the maintenance a bit, but will be happy if you share your thoughts and considerations here! )

**Comment by alexeymarunin** [comment]
I made websocket interfaces for 3 exchange (Binance, Bitmex, Huobi) and tried to make for 2 (Bitfinex, Deribit).

There are generally two ways
* create connection (public or private with user apiKey/secret) -> subscribe to events -> listen events
* create connection with static settings -> listen events

So, I think CCXT WebSocket API should be like that (JS):
```js
const WebSocketCcxt = require('cctx/ws')
const ws = new WebSocketCcxt(options) // WebSocket-based class?
if (ws.describe().has('subscribe') {
  ws.on('open', () => {
    ws.subscribe('trade|kline|order_execution|balance_update|...', data => { /* something useful */ })
  })
}
else {
  ws.on('trade|kline|order_execution|balance_update|...', data => { /* something useful */ })
}

```

**Comment by kroitor** [comment]
@alexeymarunin nope, i mean the unification for Margin/Position/Leverage Trading, not the WS unification, which is discussed here #56 ) Wrong issue )

**Comment by Gabri** [comment]
Hello all, any updates about this really nice feature? Thanks

**Comment by acrabb** [comment]
Still no ability to short?

**Comment by deanab27** [comment]
Quit running projects on my emails including deanab27@gmail.com, your
ruining my life  I cannot even get into my own email anymore,  I don't who
you people think I are but I'm about to get the police involved  pull your
projects close this account and give me back my emails,is this something my
husband did? Matthew gadola??? Wtf stop fucking with me

**Comment by kroitor** [comment]
The following is moved from [this issue](https://github.com/ccxt/ccxt/issues/7129), as posted by @monk-after-90s:

> Thanks for guiding me to regard a 'BTC/USD' contract as one thing called "BTC/USD" instead of a pair of something. I have something ideas about unification about the unification of contracts orders, which maybe could be extended to the scope of leverage.

> For simplification, lets say such a kind of contract, 'BTCUSD', whose value is expressed as 'BTC', which means that one contract could be compared to one BTC, while the profit is calculated in USD. To talk about the margin, I prefer it to be freed back to the wallet after the position is closed then the profit of the position is transfered across the wallet which is mostly be no more than the margin because of the burst mechanism. So I think the margin is always in the account.

> As when a contract is just opened, the price of the market is just the price where the contract is targeted lets say 9000, I prefer the 'price' or 'average' to be 0, the 'filled' 1 for buy contract and -1 for sell contract, for simplification, then 'cost' 0. Please note, I am not talking about the position but the order.

> The previous order produced one asset which valued 0, the only influence is that some currencies in your wallet is freezed for margin, but not gone. When the asset is exchanged in the market(position or contract closed ), lets say it is targeted at price 8000, the result is processed by another order, a new order will do this and this order which closes positions has a 'average' different from 0! This order will has a 'filled' of 1 for buy contract and -1 for sell contract, 'average' of 8000-9000=-1000, so the cost will be -1000 for buy contract and 1000 for sell contract.

> To be simple, the closed order to open contract positions values 0 while the closed order to close contract position values positive or negative or 0 if any.

> Wish for reply

**Comment by kroitor** [comment]
@monk-after-90s:

> For simplification, lets say such a kind of contract, 'BTCUSD', whose value is expressed as 'BTC', which means that one contract could be compared to one BTC, while the profit is calculated in USD.

This is a little more complicated. There are different types of contracts:

- Options contract
- Futures contract
- Futures perpetual/swap contract

In all cases, the values for fields like `filled`, `cost`, `amount`, `average` can have varying meanings, depending on the types of the contract, the funding conditions, the settlement conditions and other factors. The contracts themselves could be either _"inverse"_ or _"linear"_, also depending on how they're settled. We will have to stick to some common adopted terms in order to make progress on this issue.

**Comment by monk-after-90s** [comment]
> @monk-after-90s:
> 
> > For simplification, lets say such a kind of contract, 'BTCUSD', whose value is expressed as 'BTC', which means that one contract could be compared to one BTC, while the profit is calculated in USD.
> 
> This is a little more complicated. There are different types of contracts:
> 
>     * Options contract
> 
>     * Futures contract
> 
>     * Futures perpetual/swap contract
> 
> 
> In all cases, the values for fields like `filled`, `cost`, `amount`, `average` can have varying meanings, depending on the types of the contract, the funding conditions, the settlement conditions and other factors. The contracts themselves could be either _"inverse"_ or _"linear"_, also depending on how they're settled. We will have to stick to some common adopted terms in order to make progress on this issue (we have to be very precise with terms when describing the unification ideas, otherwise it will be very hard to brainstorm it in sync).

Thanks for your reply. Sorry for my typing without checking. I have updated my comment, and show it below:

> Thanks for guiding me to regard a 'BTC/USD' swap contract as one thing called "BTC/USD" instead of a pair of something. I have some ideas about the unification of swap contract orders for share, which maybe could be extended to the scope of leverage.
> 
> For simplification, lets say such a kind of swap contract, 'BTCUSD', whose value is expressed as 'BTC', which means that one swap contract could be compared to one BTC, while the profit is calculated in USD. To talk about the margin, I prefer it to be freed back to the wallet after the position is closed then the profit of the position is transfered across the wallet which is mostly no more than the margin if the profit is negative because of the burst mechanism. So I think the margin is always in the account which is separated from the profit.
> 
> As when a swap contract is just opened, the price of the market is exactly the price where the swap contract is targeted lets say 9000, I prefer the order 'price' or 'average' to be 0, the 'filled' 1 for buy swap contract and -1 for sell swap contract, for simplification, then 'cost' 0. Please note, I am not talking about the position but the order.
> 
> The previous order produced one asset which valued 0, the only influence is that some currencies in my wallet is freezed for margin, but not gone. When the asset is exchanged in the market(position or contract closed ), lets say it is targeted at price 8000, the result is processed by another order, a new order will do this and this order which closes the position has a 'average' different from 0! This order will has a 'filled' of 1 for buy swap contract and -1 for sell swap contract, 'average' of 8000-9000=-1000, so the cost will be -1000USD for buy swap contract and 1000USD for sell swap contract.
> 
> To be simple, the closed order which opened the swap contract position increases the USD wallet by 0 while the closed order which closed the swap contract position increases the USD wallet by positive or negative or 0 if any.
> 
> Wish for reply.

**Comment by binares** [comment]
> The contracts themselves could be either "inverse" or "linear", also depending on how they're settled.

I may be mistaken here somewhat, but I understand the "common" contracts have 4 main variables:
1. linear (future?) / inverse (swap)
2. perpetual / settled
3. normal / quanto
4. isolated / cross

This doesn't include options, which I don't know much about.
Also, can a linear contract be quanto? https://www.investopedia.com/terms/q/quantoswap.asp

**Comment by kroitor** [comment]
@binares I'm also not a specialist on derivatives, however, as far as I understand, the type of the contract does not necessarily have a meaning you described, namely:

> * linear (future?) / inverse (swap)

↑ The relationship here may be different.

A futures contract is a contract that has a settlement (expiry) date, for example, a week ahead (weekly), a month ahead (monthly), a quarter ahead (quarterly). When a futures contract expires the exchanges usually replace it with another contract of the same type, for the upcoming period.

A futures contract can either be linear or inverse. 
Take BTC/USDT futures, for example. 

Linear futures contracts are quoted in quote currency (the price of a contract is in USDT) and settled in the quote currency upon expiry (you either give USDT or receive USDT depending on the buy/sell side).

Inverse futures contracts are quoted in quote currency (the price of a contract is in USDT) and settled in the base currency upon expiry (you either give BTC or receive BTC depending on the buy/sell side).

A swap contract is practically the same as perpetual contract. You can think of a perpetual/swap as a kind of a futures contract (if you will) that does not have an expiry date. Instead, it is settled more frequently than a regular futures contract, say, every 4 hours, every 8 hours or every 12 hours. When the settlement happens, you give or get the value difference in the settlement currency for the contract you have, but you still keep having the contract for the next period, and so on. In other words, it's a frequently-swapped contract.

> * isolated / cross

↑ These two terms have nothing to do with the contract types in general. "Isolated" and "cross" are terms that define your margin-trading mode. They're related to the way your ow+borrowed funds are risk-managed. 

When you margin-trade in isolated mode, your margin is defined per each position separately (your positions are isolated from one another). Thus, if you get an isolated margin-call on one position, that does not affect your other positions.

When you margin-trade in cross mode, your margin is defined for all positions at once. In other words, your margin is "shared" across all positions that you might have. A margin-call in cross mode means that all your positions might be liquidated, if you run out of margin.

I may be totally wrong on the above, if someone can correct it or add more to it, it would be really appreciated.

**Comment by binares** [comment]
@kroitor You might be entirely right, all I have observed is the contracts specs of different exchanges, and many of them probably don't know what it exactly is they're doing (they just buy the platform and name things).

> A futures contract is a contract that has a settlement (expiry) date, for example, a week ahead (weekly), a month ahead (monthly), a quarter ahead (quarterly)

For example, Binance calls their contracts _perpetual futures_ (no expiry date). Kraken has  _futures_inverse_ (you own quote currency) and _futures_vanilla_ (you own base currency), both of which may or may not have a settlement date.

**Comment by kroitor** [comment]
@binares yep, their naming is not standardized at all, Binance has recently introduced "delivery" API (which is basically a classic futures contract) in addition to their "futures" API (which is basically a perpetual swap). That kind of chaotic naming doesn't help the unification of course, but after some investigation, we can still unify that properly. Thx for your involvement!

**Comment by genesst** [comment]
Bump, is there a roadmap for this feature? 
How can we contribute and what needs to be done?

**Comment by frosty00** [comment]
@genesst you can look at binanceusdm and binancecoinm exchanges for examples of unified margin trading, unfortunately the space is quite new and the apis are changing faster than we can keep up

**Comment by quantfor** [comment]
Anyone working on this issue?

**Comment by Markounz** [comment]
This whole subject looks really interesting....

I was wondering how to define the leverage on MarketOrder on Binance Coin-M exchange.... 

trying to get my head around.... and for the leverage trading with bots, there is not so much information...

Every tip is appreciated.

Thank in advance!

**Comment by kroitor** [comment]
@Markounz use `setLeverage` for it: https://github.com/ccxt/ccxt/blob/master/js/binance.js#L4592

**Comment by Markounz** [comment]
> @Markounz use `setLeverage` for it: https://github.com/ccxt/ccxt/blob/master/js/binance.js#L4592

Thank you very much kroitor!

**Comment by kroitor** [comment]
Please, follow this announcement from here: #10931

**Comment by joshh71390** [comment]
you guys really dropped the ball with margin trading sofar 2 days in and i cant figure out how to simply list a order in margin... why do i need to calculate the square root of the sun when the atmepshperic temperature in tokyo is 35000 kelvin but my moms going to the grocery store so i need to also make sure i can count the baldes of grass in the entire city in order to just say i want to open a buy order for 10 tokens at 1 dollar each... on this market... why thye fuck do i need to spend 40 plus hours figuring it out... you guys have way too much time on your hands trying to force people to create some unified positioning module that monitors every little aspect... why is this needed? why not just throw an error if the ballanc isnt there? im getting so sick of the fucking dead ends everyone seems to code into their programs... just dont include margin if its not someonting that you can do why do you make a unified api that isnt real...

**Comment by joshh71390** [comment]
i shouldnt need 50 lines of code and 2 months worth of research to list an order its ufkcing rediculous

**Comment by Markounz** [comment]
@joshh71390 

there is a documentation about margin trading which could help you out with listing orders on margin.

https://docs.ccxt.com/en/latest/manual.html

check this out, maybe you find your solution!
