### ISSUE TITLE
coinbasepro trade fees (and other stuff) changing on 22nd March

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#4835]
https://blog.coinbase.com/coinbase-pro-market-structure-update-fbd9d49f43d7

Taker will be 0.25%, maker will be 0.15%.

Tick sizes will be changing too (https://pro.coinbase.com/markets), although I don't think these are modelled in ccxt, no?

**Comment by kroitor** [comment]
Thanks for reporting! Will add the necessary updates on the date.

> although I don't think these are modelled in ccxt, no?

They correspond to precision as long as they are all powers of ten.
