### ISSUE TITLE
cex.io missing price & amount for market orders

### ISSUE THREAD

**Issue by firepol** [ccxt/ccxt#4836]
- OS: Linux
- Programming Language version: python 3.6
- CCXT version: 1.18.361
- Exchange: cex.io
- Method: fetchClosedOrders

I'm fetching my trade history on cex.io. I noticed that many orderes with status "closed" have price: null and amount: 0. I thought ok if price is null (market order: makes sense) then I could derive it using the amount * cost... but the amount is also to 0 in such cases, and this is a bug.

See e.g. here the response of one these not parsed properly orders:

```
  {
    "id": "7609054087",
    "datetime": "2018-11-19T19:26:06.461Z",
    "timestamp": 1542655566461,
    "lastTradeTimestamp": null,
    "status": "closed",
    "symbol": "BTC/USD",
    "type": null,
    "side": "buy",
    "price": null,
    "cost": 249.36,
    "amount": 0.0,
    "filled": 0.0,
    "remaining": 0.0,
    "trades": null,
    "fee": {
      "currency": "USD",
      "rate": 0.0025,
      "cost": 0.63
    },
    "info": {
      "id": "7609054087",
      "type": "buy",
      "time": "2018-11-19T19:26:06.461Z",
      "lastTxTime": "2018-11-19T19:26:06.461Z",
      "lastTx": "7609054097",
      "pos": null,
      "status": "d",
      "symbol1": "BTC",
      "symbol2": "USD",
      "amount": "0.00000000",
      "amount2": "250.00",
      "remains": "0.00000000",
      "tfa:USD": "0.63",
      "tta:USD": "249.36",
      "a:BTC:cds": "0.04982417",
      "a:USD:cds": "250.00",
      "f:USD:cds": "0.63",
      "tradingFeeTaker": "0.25",
      "tradingFeeUserVolumeAmount": "19111256",
      "orderId": "7609054087"
    }
  }
```

In the cex.io ui the order looks like this:

![image](https://user-images.githubusercontent.com/1702718/54461121-00626800-476c-11e9-8965-df136aedb85f.png)

Unluckily via API they don't provide the price, but the "filled" amount should be used to set the amount. See in the `info` property with the original response:

`"a:BTC:cds": "0.04982417",`

So, once you got the amount, also the price should be set with this calculation: amount_filled / cost... which in my case -> 250 / 0.04982417 = 5017.645050585
But cex.io shows `Avg. Execution price`: 5004.8

So I wonder what's going on here. Either I calculated wrongly or cex.io doesn't show data correctly. 5004 vs 5017 is quite a big difference...

Also, the parsing is not done properly for filled & amount, as these values should be always positive, but I noticed in many cases (for sell orders, seems this happens for market orders where the price is missing) that they are negative. See e.g. here:

```
  {
    "id": "7669027383",
    "datetime": "2018-11-26T12:19:30.777Z",
    "timestamp": 1543234770777,
    "lastTradeTimestamp": null,
    "status": "closed",
    "symbol": "XLM/USD",
    "type": null,
    "side": "sell",
    "price": null,
    "cost": 34.41,
    "amount": -200.0,
    "filled": -200.0,
    "remaining": 0.0,
    "trades": null,
    "fee": {
      "currency": "USD",
      "rate": 0.0025,
      "cost": 0.09
    },
    "info": {
      "id": "7669027383",
      "type": "sell",
      "time": "2018-11-26T12:19:30.777Z",
      "lastTxTime": "2018-11-26T12:19:30.777Z",
      "lastTx": "7669027411",
      "pos": null,
      "status": "d",
      "symbol1": "XLM",
      "symbol2": "USD",
      "amount": "-200.00000000",
      "remains": "0.0000000",
      "tfa:USD": "0.09",
      "tta:USD": "34.41",
      "a:USD:cds": "34.41",
      "a:XLM:cds": "200.0000000",
      "f:USD:cds": "0.09",
      "tradingFeeTaker": "0.25",
      "tradingFeeUserVolumeAmount": "44365067",
      "orderId": "7669027383"
    }
  }
```

I'm also a bit tired to investigate further, @kroitor I leave this to you ;) sorry (for not fixing it myself) & thx for looking at it.

**Comment by kroitor** [comment]
> So, once you got the amount, also the price should be set with this calculation: amount_filled / cost... which in my case -> 250 / 0.04982417 = 5017.645050585
> But cex.io shows Avg. Execution price: 5004.8
> So I wonder what's going on here. Either I calculated wrongly or cex.io doesn't show data correctly. 5004 vs 5017 is quite a big difference...

- `249.36 / 0.04982417 = 5004.799879255389503` (with fees subtracted from cost first)
- `250.00 / 0.04982417 = 5017.645050584886813` (without accounting for fees)

**Comment by kroitor** [comment]
They don't even mention `amount2` anywhere in the docs, heh...

<img width="761" alt="Screen Shot 2019-03-24 at 17 14 22" src="https://user-images.githubusercontent.com/1294454/54880682-54e6a100-4e58-11e9-806a-c9a6b2483d3b.png">

**Comment by firepol** [comment]
Hi @kroitor is there anything you could do about this? I have another example of wrongly parsed transaction:

```
  {
    "id": "7609054087",
    "datetime": "2018-11-19T19:26:06.461Z",
    "timestamp": 1542655566461,
    "lastTradeTimestamp": null,
    "status": "closed",
    "symbol": "BTC/USD",
    "type": null,
    "side": "buy",
    "price": null,
    "cost": 249.36,
    "amount": 0.0,
    "filled": 0.0,
    "remaining": 0.0,
    "trades": null,
    "fee": {
      "currency": "USD",
      "rate": 0.0025,
      "cost": 0.63
    },
    "info": {
      "id": "7609054087",
      "type": "buy",
      "time": "2018-11-19T19:26:06.461Z",
      "lastTxTime": "2018-11-19T19:26:06.461Z",
      "lastTx": "7609054097",
      "pos": null,
      "status": "d",
      "symbol1": "BTC",
      "symbol2": "USD",
      "amount": "0.00000000",
      "amount2": "250.00",
      "remains": "0.00000000",
      "tfa:USD": "0.63",
      "tta:USD": "249.36",
      "a:BTC:cds": "0.04982417",
      "a:USD:cds": "250.00",
      "f:USD:cds": "0.63",
      "tradingFeeTaker": "0.25",
      "tradingFeeUserVolumeAmount": "19111256",
      "orderId": "7609054087"
    }
  }
```

The parsed amount is: 0.0.
Expected: 0.04982417

The amount should have been taken from this property: `"a:BTC:cds": "0.04982417"`

**Comment by kroitor** [comment]
@firepol i'll try to fix it in a day or two. Need to rework the order parser for `cex`, hope to resolve it shortly.

**Comment by npomfret** [comment]
I've done a bunch of work on cex.  I'll submit work work so far...

**Comment by carlosmiei** [comment]
Does not apply anymore

```
 {'amount': 0.14,
  'average': 81.055,
  'clientOrderId': None,
  'cost': 11.3477,
  'datetime': '2022-12-05T15:12:04.124Z',
  'fee': {'cost': 0.028299, 'currency': 'USDT', 'rate': 0.0025},
  'fees': [{'cost': 0.028299, 'currency': 'USDT', 'rate': 0.0025}],
  'filled': 0.14,
  'id': '62335655175',
  'info': {'a:LTC:cds': '0.14000000',
           'a:USDT:cds': '11.347700',
           'amount': '-0.14000000',
           'f:USDT:cds': '0.028299',
           'id': '62335655175',
           'lastTx': '62335655185',
           'lastTxTime': '2022-12-05T15:12:04.124Z',
           'orderId': '62335655175',
           'pos': None,
           'remains': '0.00000000',
           'status': 'd',
           'symbol1': 'LTC',
           'symbol2': 'USDT',
           'tfa:USDT': '0.028299',
           'time': '2022-12-05T15:12:04.124Z',
           'tradingFeeTaker': '0.25',
           'tradingFeeUserVolumeAmount': '2491',
           'tta:USDT': '11.347700',
           'type': 'sell'},
  'lastTradeTimestamp': None,
  'lastUpdateTimestamp': None,
  'postOnly': None,
  'price': 81.055,
  'reduceOnly': None,
  'remaining': 0.0,
  'side': 'sell',
  'status': 'closed',
  'stopLossPrice': None,
  'stopPrice': None,
  'symbol': 'LTC/USDT',
  'takeProfitPrice': None,
  'timeInForce': 'IOC',
  'timestamp': 1670253124124,
  'trades': [],
  'triggerPrice': None,
  'type': 'market'},
```
