### ISSUE TITLE
Help tx_fee MErcado Bitcoin

### ISSUE THREAD

**Issue by murillomrocha** [ccxt/ccxt#4841]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- windows 10
- JS
- 1.18.292
- Mercado Bitcoin:
- withdraw:

I need help, I'm trying to make a transfer from one exchange to another but I can not.  Below the error:

 UnhandledPromiseRejectionWarning: Error: mercado requires tx_fee parameter to withdraw BTC
    at mercado.withdraw (C:\Users\Valepay\Documents\kryptoo\node_modules\ccxt\js\mercado.js:334:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise
 which was not handled with .catch(). (rejection id: 1)
(node:6452) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero
 exit code.

**Comment by kroitor** [comment]
Please, read here how to pass parameter overrides to unified methods:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

Also, you might want to read this to handle the errors properly:

- https://github.com/ccxt/ccxt/wiki/Manual#error-handling 

I would recommend to browse through the [examples](https://github.com/ccxt/ccxt/tree/master/examples) and read the entire [Manual](https://github.com/ccxt/ccxt/wiki/Manual) from top to bottom – it has the answers to these questions and will really save you a ton of time.

Let us know if that doesn't answer the question.
