### ISSUE TITLE
(itBit) rebate vs fee

### ISSUE THREAD

**Issue by gRittyKitty** [ccxt/ccxt#4842]
This is related to issue #4074 
You answered regarding hitBtc and showed that the fee is shown as negative. I don't connect to hitbtc and am not familiar with that. However, itBit started rebates for maker. But itBit is funky (I guess) and has a category for both fees and rebates. That is, for a trade with a rebate, the fee is returned as 0 but there is also a separate field for rebate where the rebate is contained. 
Please confirm that rebates ought to be parsed by parseTrade as negative fees, eg, a $10 rebate would show up after parseTrade as USD -10.00. Right now that is not happening for itBit. I can attempt a fix but need to confirm proper behavior first.
Thanks

**Comment by kroitor** [comment]
Fixed in 1.18.369, thank you for reporting!

**Comment by gRittyKitty** [comment]
Daaaaang.
Igor, you crushin' it.
