### ISSUE TITLE
Apply to join the organization

### ISSUE THREAD

**Issue by ericjjj** [ccxt/ccxt#4846]
I am a developer from Beijing and a user of ccxt. I have submitted two pull requests. After practice, I learned the principles of ccxt and hope to continue to improve it. 
Can I join the organization?

**Comment by ericjjj** [comment]
#2792 #4844

**Comment by ericjjj** [comment]
@kroitor

**Comment by kroitor** [comment]
Hi! )

We are a very small team for now, but we are open to all types of collaboration and we sometimes invite new members. If you consistently submit good quality code – we will be happy to take you on board with us.

The key indicators to us are: the quality of your code, the level of your understanding of the code, and most importantly, your pedantic skills and the ability to follow literally and precisely all the guides from the CONTRIBUTING doc as they are.

You might want to check out these stats: https://github.com/ccxt/ccxt/graphs/contributors and you want to be in the topmost committers to qualify, members of the organization take responsibilities as well.

When you show a high level of understanding of the inner workings and the design principles of the lib by submitting good clean code and you help us solve our pending tasks and open issues, then we will return to this discussion ) Thank for your contributions and for your help, we really appreciate it!

Let us know if that doesn't answer your question.
