### ISSUE TITLE
New Exchange: Huobi Japan

### ISSUE THREAD

**Issue by y-clps** [ccxt/ccxt#4856]
Huobi Japan has begun to provide API. 
It seems to be like Huobi Pro API system. 
Please someone make a patch supporting Huobi Japan.

API documentation: https://github.com/cloudapidoc/API_Docs_en/blob/master/rest_api_en.md
exchange url: https://www.huobi.co.jp/

**Comment by kroitor** [comment]
@y-clps there's no mention of Huobi Japan in the doc you've linked. And I can't access huobi.co.jp from my location... Can you post their API base URL for their JP site or the url to the API docs that mention Huobi Japan?

**Comment by kroitor** [comment]
Hmm... I still can't find the base URL anywhere, tried these, they don't work:

- https://www.huobi.co.jp/api/market/tickers
- https://www.huobi.co.jp/market/tickers
- https://api.huobi.co.jp/api/market/tickers
- https://api.huobi.co.jp/market/tickers

@y-clps What's the base URL?

**Comment by y-clps** [comment]
Thank you for your response and patience.
I also can't find explicit description of {HOST} url, but there are some examples that seem to work well.
And this seems to be like Huobi Pro API system (https://github.com/huobiapi/API_Docs_en). 

tickers: https://www.huobi.co.jp/-/x/pro/market/tickers
symbols: https://www.huobi.co.jp/-/x/pro/v1/common/symbols

**Comment by kroitor** [comment]
> tickers: https://www.huobi.co.jp/-/x/pro/market/tickers
> symbols: https://www.huobi.co.jp/-/x/pro/v1/common/symbols

Yeah, but these aren't the official API base urls, these are their web api urls (for their website), therefore these paths are not guaranteed to work anywhere in their docs... We need to know their `{HOST}` somehow...

**Comment by y-clps** [comment]
I have just understood what you mean. I'm sorry to bother you.
If there is an official additional announcement about {HOST} URL, I will report it here.
Thanks.

**Comment by kroitor** [comment]
@y-clps thanks to you too, let us know if you find out anything. We will also post here, will probably have to reach out to their tech support and ask them to add that to their docs...

**Comment by alexeymarunin** [comment]
@kroitor I think base url is `https://www.huobi.co.jp/-/x/pro/`
See #4672 also

**Comment by kroitor** [comment]
@alexeymarunin i don't think it is, because:

![Screen-Shot-2019-03-19-at-16 50 15](https://user-images.githubusercontent.com/1294454/54611094-60585780-4a67-11e9-949b-d35ce1a89b73.jpg)

**Comment by y-clps** [comment]
The api reference has been renewed, and host url has been published as below.
REST: https://api-cloud.huobi.co.jp
websocket: wss://api-cloud.huobi.co.jp/ws

The api reference is here. https://api-doc.huobi.co.jp/#api

This is written in Japanese, so I'm sorry for inconvenience. However, this api structure seems like huobi global.

**Comment by kroitor** [comment]
@y-clps thx for the followup on this!

**Comment by kroitor** [comment]
Huobi Japan has been added here: https://github.com/ccxt/ccxt/pull/7184
