### ISSUE TITLE
[Binance] ExchangeError while checking account status

### ISSUE THREAD

**Issue by alexeymarunin** [ccxt/ccxt#4857]
- OS: macOS 10.14.3
- Programming Language version: Node.js
- CCXT version: 1.18.333
- Exchange: Binance
- Method: wapiGetAccountStatus

To check account status I use [accountStatus](https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#account-status-user_data) endpoint. And when I specify incorrect apiKey/secret I get `Exchange` error with message `{"msg":"API key does not exist","success":false}`

I think `AuthenticationError` error will be more prefer in that case.

A little example:
```js
const account = new ccxt.binance({apiKey: APIKEY, secret: SECRET});
try {
  const accountStatus = await account.wapiGetAccountStatus();
  // accountStatus.success === true - account available
  // accountStatus.success === false - account banned
} 
catch (error) {
  if (error instanceof ccxt.AuthenticationError) {
    console.error('Authentication failed')
  }
}
```
I know it's specific case, but it will help in my app to make error handling more unified 

PS. I found cool issue #4071

**Comment by kroitor** [comment]
@alexeymarunin can you please post your verbose response for the above error?

**Comment by alexeymarunin** [comment]
```js
{
  "msg": "API key does not exist",
  "success": false
}
```

**Comment by alexeymarunin** [comment]
Seems ccxt tries to get `code` in response and create suitable error class

**Comment by kroitor** [comment]
@alexeymarunin i've uploaded a fix to this 30 minutes ago, so it should be recognized as AuthenticationError as of version 1.18.377. Let me know if that doesn't work for you.

**Comment by alexeymarunin** [comment]
@kroitor All work correct, thanks!
