### ISSUE TITLE
Wrong price limits on kucoin

### ISSUE THREAD

**Issue by MarcelBeining** [ccxt/ccxt#4858]
- OS: Windows 10 64 bit
- Programming Language version: Python 3.6
- CCXT version: 1.18.375
- Exchange: kucoin
- Method: loadMarkets

When I load the market for KCS/USDT, ccxt gives me this:
```
{'active': True,
 'base': 'KCS',
 'baseId': 'KCS',
 'fee_loaded': False,
 'id': 'KCS-USDT',
 'info': {'baseCurrency': 'KCS',
  'baseIncrement': '0.0001',
  'baseMaxSize': '10000000000',
  'baseMinSize': '0.01',
  'enableTrading': True,
  'market': 'SC',
  'name': 'KCS-USDT',
  'priceIncrement': '0.00001',
  'quoteCurrency': 'USDT',
  'quoteIncrement': '0.000001',
  'quoteMaxSize': '99999999',
  'quoteMinSize': '0.05',
  'symbol': 'KCS-USDT'},
 'limits': {'amount': {'max': 10000000000.0, 'min': 0.01},
  'cost': {'max': 99999999.0, 'min': 0.05},
  'price': {'max': 9999999900.0, 'min': 5.0}},
 'maker': 0.001,
 'percentage': True,
 'precision': {'amount': 4, 'price': 5},
 'quote': 'USDT',
 'quoteId': 'USDT',
 'symbol': 'KCS/USDT',
 'taker': 0.001,
 'tierBased': False}
```

telling me that the min KCS/USDT price has to be `5.0`. However this is wrong, as the current price is at 0.96 and I have no problems in creating a order with this price and longer. Thus it seems something is wrong in how ccxt calculates the min (and max?) price on kucoin. This might be related to #4767

**Comment by kroitor** [comment]
Fixed in 1.18.380, let us know if you still have issues with it. Thx for your help!
