### ISSUE TITLE
Binance: publicGetMarketIdHours

### ISSUE THREAD

**Issue by saianwork** [ccxt/ccxt#486]
````
hours = 8  # ← your timeframe
topia.load_markets()

for symbol in btccoins:
    market = topia.market(symbol)
    response = topia.publicGetMarketIdHours(topia.extend({
        'id': market['id'],
        'hours': hours,
    }))
    time.sleep(delay)
    ticker = topia.parse_ticker(response['Data'], market)  # How to be sure it returns the 8h past hour market?
    # do whatever you need with the ticker...
    datetime = ticker['datetime']
    timestamp = ticker['timestamp']
    open = ticker['open']
    close = ticker['close']
    print(close, datetime, timestamp)
````
that's the result: -> timestamp is not 8h ago so how can I know it actually represents the 8h past hours timeframe?

1.814e-05 2017-11-07T12:32:59.000Z 1510057979383
1.209e-05 2017-11-07T12:33:01.000Z 1510057981017
4.15e-05 2017-11-07T12:33:02.000Z 1510057982474
1.07e-06 2017-11-07T12:33:04.000Z 1510057983791
0.00105061 2017-11-07T12:33:05.000Z 1510057985092

I'm sorry if I did something wrong in advance. I'm really trying to get this sorted out. thanks

**Comment by kroitor** [comment]
If you look at the timestamps you are getting, you will immediately see that those represent currenct datetime in UTC. When the ticker is returned, the timestamp shows the time when it was generated, not the start of your timeframe. So it will always show approximately current time. Your ticker was generated now, and its values show last 8 hours of history. The beginning of your timeframe isn't indicated anywhere.

> so how can I know it actually represents the 8h past hours timeframe?

Ask Binance if they really report true data for the last 8 hours or not? We don't change it on the fly. You get it as is. I hope it answers your question.

**Comment by saianwork** [comment]
Thank you! yes it does answer my question. many thanks for your time. and thanks for the great work.

cheers
