### ISSUE TITLE
question about meaning of precision

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#4862]
Apologies if this is a duplicate.

Regarding the `precision` values.  The docs say '_number of decimal digits "after the dot"_'.  But my understanding of the precision of a number was that it's another of way of saying how many significant figures there are.  In javascript, the `toFixed` function sets the number of decimal digits after the dot, and `toPrecision` sets the number to n significant digits, eg:

```
(12345.6).toFixed(5) => "12345.60000"
(12345.6).toPrecision(5) => "12346"
```

In the bitfinex implementation agrees with this definition: it's API specifies a _precision_ of 5 for the BTC/EUR market for example (`3000.5` is a valid price, `30000.5` is not).  And so prices must have a maximum of 5 numbers (ignoring trailing zeros), regardless of where the decimal point lies in that price.

I don't really know what my question is!  I'm just asking because I've just added some missing markets to coinmate in this [PR](https://github.com/ccxt/ccxt/pull/4824) and got confused.

**Comment by xpl** [comment]
@npomfret Our library supports both the modes you've just described, they are called `DECIMAL_PLACES` and `SIGNIFICANT_DIGITS`. See the `decimalToPrecision` function usage:

https://github.com/ccxt/ccxt/blob/master/js/test/base/functions/test.number.js

In the bitfinex implementation, we specify the precision mode in that line:

https://github.com/ccxt/ccxt/blob/master/js/bitfinex.js#L306

```
            'precisionMode': SIGNIFICANT_DIGITS,
```

**Comment by kroitor** [comment]
@npomfret let us know if the above does not answer your question )

**Comment by npomfret** [comment]
I see, thank you.
