### ISSUE TITLE
okex {"result":false,"error_code":20024}

### ISSUE THREAD

**Issue by bnskumar** [ccxt/ccxt#4868]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

---code:

exchange = ccxt.okex({
'apiKey': '***',
'secret': '***',
'enableRateLimit': True,
})

instrument='BTC/USD'
ord_qty=0.002

exchange.create_limit_buy_order(instrument,{'amount':ord_qty, 'price':3950, 'contract_type': 'next_week'})

result:

ccxt.base.errors.ExchangeError: okex {"result":false,"error_code":20024}

Strange thing:
**exchange.create_order('BTC/USD', 'limit', 1, 1, 3950, {'contract_type': 'next_week', 'lever_rate': 10} )**
This is working.

Thanks.

**Comment by kroitor** [comment]
Hi!

This is a bit of a duplicate issue:

- https://github.com/ccxt/ccxt/issues/4206
- #4063  ← I suggest to move this discussion here.
