### ISSUE TITLE
New Exchange: StellarX

### ISSUE THREAD

**Issue by sergethompson** [ccxt/ccxt#4871]
StellarX has [zero trading fees](https://stellarx.zendesk.com/hc/en-us/articles/360006190074-Are-there-fees-), decent volume, decentralized and would love to see on ccxt. 
https://www.stellarx.com/ 

Some quick start info I gathered is in the following urls:
https://www.stellar.org/developers/horizon/reference/endpoints/assets-all.html

base url for stellarx is "https://horizon-stellarx.stellar.org"
Ex: curl "https://horizon-stellarx.stellar.org/assets?limit=200&order=desc"

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/1376
