### ISSUE TITLE
Question about: active, cost min, amount min, precision amount

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#4874]
OS: Windows 10
Programming Language version: Node.js
CCXT version: #465
Exchange: All Exchanges
Node.js 11.9.0 installed
Method: active, cost min, amount min, precision amount

Hello!

I have a question when looking at for example the below 2 JSON responses as an example:

**southexchange**
**"MLM/BTC":{"tierBased":false,"percentage":true,"taker":0.002,"maker":0.002,"id":"MLM/BTC","symbol":"MLM/BTC","base":"MLM","quote":"BTC","baseId":"MLM","quoteId":"BTC"**

**binance**
**{"ETH/BTC":{"limits":{"amount":{"min":0.001,"max":100000},"price":{},"cost":{"min":0.001}},"precision":{"base":8,"quote":8,"amount":3,"price":6},"active":true}**

How should one think about the below parameters, - if that information is missing like it does in southexchange in order to create the correct order to not let it be rejected?

**cost min
amount min
precision amount**

Specifically, I like to ask about the below parameter:
**active**

If that is missing like in MLM/BTC how should one think then. Is the symbol active or not?
Second part of that question is. Sometimes exchanges do "Freeze" a symbol for trading for a certain time for any reason, it could be 1 hour etc. Does the active status reflect that particular scenario?

Thank you!

**Comment by kroitor** [comment]
Hi!

Your first question about the `active` flag was answered here:

- https://github.com/ccxt/ccxt/issues/4075
- https://github.com/ccxt/ccxt/pull/4573

> If that is missing like in MLM/BTC how should one think then. Is the symbol active or not?

It's active, if the `active` flag isn't explicitly set to `false`. If it's missing or `true` then it's true. If it's `undefined`, then it's most likely true, but not 100% )

```
mbp:ccxt igorkroitor$ node examples/js/cli southxchange market ETH/BTC
southxchange.market (ETH/BTC)
{     limits: { amount: { min: undefined, max: undefined },
                 price: { min: undefined, max: undefined },
                  cost: { min: undefined, max: undefined }  },
   precision: {  },
   tierBased:    false,
  percentage:    true,
       taker:    0.002,
       maker:    0.002,
          id:   "ETH/BTC",
      symbol:   "ETH/BTC",
        base:   "ETH",
       quote:   "BTC",
      baseId:   "ETH",
     quoteId:   "BTC",
      active:    undefined,  // ←--------------------------- here
        info: ["ETH", "BTC"]                                   }
mbp:ccxt igorkroitor$
```

> Second part of that question is. Sometimes exchanges do "Freeze" a symbol for trading for a certain time for any reason, it could be 1 hour etc. Does the active status reflect that particular scenario?

It should. If you find a case when it doesn't reflect that scenario or if you find something suspicious, don't hesitate and please let us know.

Feel free to ask if that doesn't answer the questions.

P.S. when you post pieces of code and JSON-structured, please use github markdown for readability.

**Comment by jackpotcityco** [comment]
Thank you, then I understand better about the "active" status for the symbol how to think there.
I did also wonder about the below fields, how to think when those are missing when it comes to create an order, in order to: 
Send minimum amount, precision amount, cost minimum to prevent an order to be rejected. Like below all of that is undefined or missing?:
```javascript
{     limits: { amount: { min: undefined, max: undefined },
                 price: { min: undefined, max: undefined },
                  cost: { min: undefined, max: undefined }  },
   precision: {  },
```
_(Yes I will put JSON in markdown also)_

**Comment by kroitor** [comment]
> Send minimum amount, precision amount, cost minimum correctly, to prevent an order to be rejected. Like below all of those are undefined or missing?:

That looks like a strange structure to me (if all of it is empty), can you post the code you used to obtain it? Which exchange/method is it?

**Comment by jackpotcityco** [comment]
I did just copy your info from your post there. I was not sure if you refered to my question there.

But the code and response I get is the below then. It is for the southexchange in this case:
```javascript
'use strict';
var ccxt = require('ccxt');

(async () => {
    let southxchange = new ccxt.southxchange()
    let markets = await southxchange.load_markets()
    console.log(southxchange, markets)
    const obj = { southxchange, markets }

    const fs = require('fs');
    fs.writeFile("/myproject/markets/southxchange2.txt", JSON.stringify(obj), function (err) {
        if (err) {
            return console.log(err);
        }

        console.log("The file was saved!");
    });
})()
``` 
The response is this:
```javascript
MLM/BTC":{"tierBased":false,"percentage":true,"taker":0.002,"maker":0.002,"id":"MLM/BTC","symbol":"MLM/BTC","base":"MLM","quote":"BTC","baseId":"MLM","quoteId":"BTC","info":["MLM","BTC"]}
```

**Comment by kroitor** [comment]
If you mean `southxchange`, then the above structure is expected, because the `sountexchange` API does not provide the indication whether the market is active or not and does not specify precision or limits. So you could stick to a default of precision 8 for amount and price and if your values are somehow out of limits, the exchange should throw an exception, which you will then be able to catch as described in the [error handling](https://github.com/ccxt/ccxt/wiki/Manual#error-handling) section in the Manual. Let me know if that doesn't clarify it.

**Comment by jackpotcityco** [comment]
> So you could stick to a default of precision 8 for amount and price and if your values are somehow out of limits, the exchange should throw an exception, which you will then be able to catch

Then I understand, I was not sure about it so thought it was good to ask to know how to do with those scenarios. I will try to use precision 8 for amount and price as a default then and create a catch error log for realtime use to see what scenarios that could happen there.

Thank you very much for this help!
