### ISSUE TITLE
KuCoin market buy order types

### ISSUE THREAD

**Issue by lampardlb** [ccxt/ccxt#4876]
- OS: Windows
- Programming Language version: python
- CCXT version: 3.18.387
- Exchange: Kucoin
- Method: create market buy order

Kucoin's API allows two types of market orders ([link here](https://docs.kucoin.com/#place-a-new-order)) by specify either one of the two (not both): 
1. specify 'size' = base currency amount, e.g. how much BTC one wants to buy in the BTC/USDT pair;
2. specify 'funds' = quote currency amount, e.g how much USDT one wants to spend to buy BTC.

The latter is very handy in creating market buy orders, since one does not need to analyse the order book to find out how much base currency he is able to buy, with the quote currency he's got.  But the option seems to be not enabled in the kucoin.py code (from line 542), i.e. one can only specify 'size':

```
    def create_order(self, symbol, type, side, amount, price=None, params={}):
        self.load_markets()
        marketId = self.market_id(symbol)
        # required param, cannot be used twice
        clientOid = self.uuid()
        request = {
            'clientOid': clientOid,
            'side': side,
            'size': self.amount_to_precision(symbol, amount),
            'symbol': marketId,
            'type': type,
        }
```
 would be great to enable the second market order type as well, thanks very much!

**Comment by kroitor** [comment]
@lampardlb yep, this is how we approach these types:

- https://github.com/ccxt/ccxt/blob/master/js/huobipro.js#L796
- https://github.com/ccxt/ccxt/blob/master/js/cex.js#L329

Also, covered here:

- https://github.com/ccxt/ccxt/issues/3460
- https://github.com/ccxt/ccxt/issues/3427

Your help with that would me much appreciated, otherwise I will get to it after fixing #4814.

**Comment by lampardlb** [comment]
@kroitor Thanks for your reply - you should take some rest in the weekend mate!
I'm a bit embarrassed to say that I do not know how to run github properly, and do not know js... I've modified the python codes in kucoin.py (by just removing 'size' out of 'request' initialisation to allow 'funds' in params), hope these can somehow help a little:

   ```
 def create_order(self, symbol, type, side, amount=None, price=None, params={}):
        self.load_markets()
        marketId = self.market_id(symbol)
        # required param, cannot be used twice
        clientOid = self.uuid()
        request = {
            'clientOid': clientOid,
            'side': side,
            'symbol': marketId,
            'type': type,
        }

       if amount is not None:
           request['size']= self.amount_to_precision(symbol, amount),

        if type != 'market':
            request['price'] = self.price_to_precision(symbol, price)
        response = self.privatePostOrders(self.extend(request, params))
        responseData = response['data']
        return {
            'id': responseData['orderId'],
            'symbol': symbol,
            'type': type,
            'side': side,
            'status': 'open',
            'clientOid': clientOid,
            'info': responseData,
        }
```

**Comment by kroitor** [comment]
@lampardlb no worries, will resolve it anyway, thx for your reports, really appreciate your reporting!

**Comment by atabakhooshangi** [comment]
this issue didn't solve yet! this is for 2019 omg . kucoin market order has a huge buuuuuuuug

**Comment by aghering23** [comment]
Is this correct that the 'funds' param bug is not resolved, running into some issues trying to send market order in qoute amount on kucoin spot.

**Snippet**
-----
     try:
        print(amount)
        order_response = exchange.createOrder(symbol, orderType, side, amount, limitprice, {'funds': str(amount)})
    except ccxt.NetworkError as e:
        order_response = {'createOrder': str(e)}
        # retry or whatever
    except ccxt.ExchangeError as e:
        order_response = {'createOrder': str(e)}
        # retry or whatever
    except Exception as e:
        order_response = {'createOrder': str(e)}
    except:
        order_response = {'createOrder': 'Failed'}
    print(order_response, '\n')

    return order_response 
-----



**Output**
-----
Base BTC, Qoute USDT

Base {'free': 0.0, 'used': 0.0, 'total': 0.0} | Qoute {'free': 24.19336668, 'used': 0.0, 'total': 24.19336668}

Base Free 0.000000000 | Qoute Free 24.193366680

2.419336668
{'createOrder': 'kucoin Funds increment invalid.'}

-----
