### ISSUE TITLE
Thank you, then I understand better about the "active" status for the symbol how to think there.

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#4877]
Thank you, then I understand better about the "active" status for the symbol how to think there.

I did also wonder about the below fields, how to think when those are missing when it comes to create an order, when it comes to: 
Send minimum amount, precision amount, cost minimum correctly, to prevent an order to be rejected. Like below all of those are undefined or missing?:
```javascript
{     limits: { amount: { min: undefined, max: undefined },
                 price: { min: undefined, max: undefined },
                  cost: { min: undefined, max: undefined }  },
   precision: {  },
```
_(Yes I will put JSON in markdown also)_

_Originally posted by @jackpotcityco in https://github.com/ccxt/ccxt/issues/4874#issuecomment-475901786_

**Comment by kroitor** [comment]
I suggest that we keep this discussion in the original post here: https://github.com/ccxt/ccxt/issues/4874#issuecomment-475901786

**Comment by jackpotcityco** [comment]
(Yes, sorry, I did by mistake create a new issue)
