### ISSUE TITLE
Implement fetchLedger on kucoin

### ISSUE THREAD

**Issue by MarcelBeining** [ccxt/ccxt#4880]
- CCXT version: 1.18.395
- Exchange: kucoin
- Method: fetchLedger

Just saw that kucoin now also has an endpoint for getting the ledger entries which is much more convenient than fetching trades/withdrawals/deposits separately. As some of your other exchange implementations (e.g. kraken) already have the fetchLedger method, might be supercool if you could also implement it for kucoin :-)

**Comment by MarcelBeining** [comment]
Actually this would also be very good to implement soon because the other endpoints do not provide information on the received airdrops/bonuses etc

**Comment by MarcelBeining** [comment]
any news on that?

**Comment by kroitor** [comment]
@MarcelBeining yep, will get to it this week.
