### ISSUE TITLE
Orderbook Tickers

### ISSUE THREAD

**Issue by kobej1** [ccxt/ccxt#4881]
For binance it's possible to get the first bid and ask entry in the order book for all markets. I've searched in the user manual but didn't find this functionality. Is this functionality available in the ccxt library or not?

**Comment by kroitor** [comment]
> For binance it's possible to get the first bid and ask entry in the order book for all markets. I've searched in the user manual but didn't find this functionality. 

That's right.

> Is this functionality available in the ccxt library or not?

Yes, just use the `fetchBidsAsks` method.

Duplicates:

- https://github.com/ccxt/ccxt/issues/1177
- https://github.com/ccxt/ccxt/issues/1855
- https://github.com/ccxt/ccxt/issues/2893

Let us know if that doesn't answer the question.
