### ISSUE TITLE
javascript lib kucoin call issues promise error and CORB

### ISSUE THREAD

**Issue by chrouzz** [ccxt/ccxt#4885]
- OS: Mac OSX
- Programming Language version: javascript web browser (chrome)
- CCXT version: 1.18.387
- Exchange: Kucoin
- Method: fetchBalance, fetchTrades

I get this original error with a  promise call, here is the error stack.

kucoin.js:259 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at kucoin2.fetchCurrencies (kucoin.js:259)
    at async kucoin2.loadMarkets (Exchange.js:761)
    at async kucoin2.fetchBalance (kucoin.js:1021)
fetchCurrencies @ kucoin.js:259
Promise.then (async)
kucoinGetToken @ bibox.vue?./node_modules/babel-loader/lib??ref--3!./node_modules/vue-loader/lib??vue-loader-options:99
invokeWithErrorHandling @ vue.runtime.esm.js:1853
invoker @ vue.runtime.esm.js:2178
invokeWithErrorHandling @ vue.runtime.esm.js:1853
Vue.$emit @ vue.runtime.esm.js:3864
handleClick @ element-ui.common.js:9141
invokeWithErrorHandling @ vue.runtime.esm.js:1853
invoker @ vue.runtime.esm.js:2178
original._wrapper @ vue.runtime.esm.js:6884
Exchange.js:469 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://openapi-v2.kucoin.com/api/v1/currencies with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.

  | fetchCurrencies | @ | kucoin.js:259
-- | -- | -- | --
  | Promise.then (async) |   |  
  | kucoinGetToken | @ | bibox.vue?./node_mod…e-loader-options:99
  | invokeWithErrorHandling | @ | vue.runtime.esm.js:1853
  | invoker | @ | vue.runtime.esm.js:2178
  | invokeWithErrorHandling | @ | vue.runtime.esm.js:1853
  | Vue.$emit | @ | vue.runtime.esm.js:3864
  | handleClick | @ | element-ui.common.js:9141
  | invokeWithErrorHandling | @ | vue.runtime.esm.js:1853
  | invoker | @ | vue.runtime.esm.js:2178
  | original._wrapper | @ | vue.runtime.esm.js:6884

  | fetchCurrencies | @ | kucoin.js:259
-- | -- | -- | --
  | Promise.then (async) |   |  
  | kucoinGetToken | @ | bibox.vue?./node_mod…e-loader-options:99
  | invokeWithErrorHandling | @ | vue.runtime.esm.js:1853
  | invoker | @ | vue.runtime.esm.js:2178
  | invokeWithErrorHandling | @ | vue.runtime.esm.js:1853
  | Vue.$emit | @ | vue.runtime.esm.js:3864
  | handleClick | @ | element-ui.common.js:9141
  | invokeWithErrorHandling | @ | vue.runtime.esm.js:1853
  | invoker | @ | vue.runtime.esm.js:2178
  | original._wrapper | @ | vue.runtime.esm.js:6884

So first it's a javascript error and then it's a warmining saying CORB issue

Cross-Origin Read Blocking (CORB) blocked cross-origin response https://openapi-v2.kucoin.com/api/v1/currencies with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.

I already spent 1 full day to try to figure out the issue.
I tested other exchange and it was fine. I Really need some advices please.

**Comment by chrouzz** [comment]
regarding my understand, all come from the CORB issue which at the origin is a protection that google do one receives a response.
In this case CORB policy will set the return data to null. So the javascript lib can't continue.
I am working from my computer and testing using chrome with a dev web server at localhost:9000

**Comment by kroitor** [comment]
Please, read here on how to bypass CORS issues:

- https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin
- https://github.com/ccxt/ccxt/search?q=cors&type=Issues

Let us know if that doesn't answer your questions. Feel free to ask, if you have more.

**Comment by chrouzz** [comment]
This is not CORS issues, this is CORB issue, that's not a typo from me.
I know how to solve CORS issue.
I give up to use the javascript lib within a webapplication. Too much issues, I will try a different approach.
PS: I only had issue with kucoin, bibox was fine.

**Comment by kroitor** [comment]
@chrouzz the workaround for CORB is exactly the same as a workaround for CORS, because it involves a CORS proxy. The Install docs describes how to set up a CORS proxy to avoid CORS/CORB issues.

**Comment by chrouzz** [comment]
I spent a whole day trying to fix that issue.
I am usually solving CORS issue with a chrome plugin.
According to chrome itself it's a different problem.
 https://www.chromestatus.com/feature/5629709824032768 
CORB is a security embedded within the browser, to protect from some kind of attack.
I am tired, don't want to give it another shoot, I will use python.

**Comment by jansgreen** [comment]
That's what CORS is for: to prevent people from sending requests to you client-side. Without CORS, it would be very easy to overload peoples' servers with a popular website.
