### ISSUE TITLE
Implement fetchLedger on Coinbase 

### ISSUE THREAD

**Issue by MarcelBeining** [ccxt/ccxt#4886]
As of now it seems this has not been implemented on Coinbase (not Pro).
This feature is documented here:
https://developers.coinbase.com/api/v2#list-transactions
a bit confusing that they call it list-transactions, because when I understand it correctly this is what other exchanges call `ledger entries `(history of buys, sells, withdrawals, deposits etc)

**Comment by kroitor** [comment]
The work on it is going on here: https://github.com/ccxt/ccxt/pull/4179 (i suggest to move this discussion to that PR, if you don't mind).
