### ISSUE TITLE
Implement binance dust conversion history in fetchMyTrades

### ISSUE THREAD

**Issue by MarcelBeining** [ccxt/ccxt#4887]
- CCXT version: 1.18.397
- Exchange: binance 
- Method: fetchMyTrades

I just wondered why in my ccxt trade history I could sell some BNB that I did not have bought before and found out that this BNB came from a `dust-to-BNB` conversion, which ccxt does not fetch during fetchMyTrades.
There is an endpoint to get these conversion data from binance:
https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#dustlog-user_data
The price and fee can be deducted from `"amount"/"transferredAmount"` and `"serviceChargeAmount"`

Would be very convenient to have these mini-trades also in the trade history, as otherwise the calcualted coin balances are not correct, and these trades are missing for tax report.

**Comment by kroitor** [comment]
We will most likely not add the second call to `fetchMyTrades`, because it will break the pagination. So we will think of how to add a unified method for dust logs instead.

**Comment by kroitor** [comment]
In the meantime, you can use the private endpoint wapi_get_userAssetDribbletLog to fetch them manually as described here: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

**Comment by MarcelBeining** [comment]
Ok maybe you leave a note in here if you implemented it in some way
