### ISSUE TITLE
bitmex.fetchOHLCV

### ISSUE THREAD

**Issue by mrktmr** [ccxt/ccxt#4889]
I am not able to get OHLCV data from https://bitmex.com. It works fine with https://testnet.bitmex.com. I have successfully downloaded the entire OHLCV data from the testnet several times, but can't get a single good response from the main net??? Here is the troubled code:

base_url='https://bitmex.com'
bitmex = ccxt.bitmex({'verbose': True, 'enableRateLimit': True, 'apiKey':apiKey, 'secret':apiSecret,
'urls':{'www':base_url, 'api':base_url,}})

'''
The 'since' time was derived from candle data going back as for as the chart would. Also, times from 2014, 2017 have been tried, none work on the main net.
'''
since = bitmex.parse8601('2015-09-26T00:00:00Z')
...
ohlcv_data = bitmex.fetchOHLCV('BTC/USD','1h', since, 750)

Here is the error code:
BadRequest: bitmex {"error":{"message":"binSize is invalid.","name":"HTTPError"}}

Please help!

- OS: windows 7 pro
- Programming Language version: python 3.7.1rc1
- CCXT version: 1.18.152
- Exchange: bitmex
- Method: fetchOHLCV

**Comment by kroitor** [comment]
Can you please show your verbose request/response exactly as described here:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

?

(and use the markup to format it for readability:

```Python
bitmex.load_markets()

bitmex.verbose = True  # ←----------- add this after loading the markets

bitmex.fetch_ohlcv(symbol, timeframe, since, limit)
```

**Comment by mrktmr** [comment]
The code is the same as before with loop so

```
since = bitmex.parse8601('2015-09-26T00:00:00Z')

with open('filepath/filename', 'w') as f:
    while since < utcTime:
        ohlcv_data = bitmex.fetchOHLCV('BTC/USD','1h', since, 750)
        print(ohlcv_data)
        
        if len(ohlcv_data):
            since = ohlcv_data[len(ohlcv_data)-1][0]
            since += 360000#Add 1 hour
            f.write(str(ohlcv_data))
            time.sleep(1)
        else:
            break
```
response
```
DEBUG:ccxt.base.exchange:GET https://bitmex.com/api/v1/trade/bucketed?symbol=XBTUSD&binSize=1h&partial=True&count=750&startTime=2015-09-26+00%3A00%3A00, Request: {'Accept-Encoding': 'gzip, deflate'} None

Request: GET https://bitmex.com/api/v1/trade/bucketed?symbol=XBTUSD&binSize=1h&partial=True&count=750&startTime=2015-09-26+00%3A00%3A00 {'Accept-Encoding': 'gzip, deflate'} None
DEBUG:urllib3.connectionpool:https://bitmex.com:443 "GET /api/v1/trade/bucketed?symbol=XBTUSD&binSize=1h&partial=True&count=750&startTime=2015-09-26+00%3A00%3A00 HTTP/1.1" 301 0
DEBUG:urllib3.connectionpool:https://www.bitmex.com:443 "GET /api/v1/trade/bucketed HTTP/1.1" 400 62
DEBUG:ccxt.base.exchange:GET https://bitmex.com/api/v1/trade/bucketed?symbol=XBTUSD&binSize=1h&partial=True&count=750&startTime=2015-09-26+00%3A00%3A00, Response: 400 {'Date': 'Tue, 26 Mar 2019 01:30:00 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '62', 'Connection': 'keep-alive', 'Set-Cookie': 'AWSALB=Tkz0dcPJhGZeuLrBc7fzKkx7WM80iVYLyifeAlA9ER4sysKQs3zL6TfPnP9nh0ydGOGFHBEdCVLtMWSMaHpg52Xo0Cs0RKWpcgAe8UwChdAlwGp0Z098szIm4uGc; Expires=Tue, 02 Apr 2019 01:30:00 GMT; Path=/', 'X-RateLimit-Limit': '150', 'X-RateLimit-Remaining': '148', 'X-RateLimit-Reset': '1553563801', 'X-Powered-By': 'Profit', 'ETag': 'W/"3e-SPtO6/Zf3slFmE++bSi+xCO4Qqs"', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'} {"error":{"message":"binSize is invalid.","name":"HTTPError"}}

Response: GET https://bitmex.com/api/v1/trade/bucketed?symbol=XBTUSD&binSize=1h&partial=True&count=750&startTime=2015-09-26+00%3A00%3A00 400 {'Date': 'Tue, 26 Mar 2019 01:30:00 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '62', 'Connection': 'keep-alive', 'Set-Cookie': 'AWSALB=Tkz0dcPJhGZeuLrBc7fzKkx7WM80iVYLyifeAlA9ER4sysKQs3zL6TfPnP9nh0ydGOGFHBEdCVLtMWSMaHpg52Xo0Cs0RKWpcgAe8UwChdAlwGp0Z098szIm4uGc; Expires=Tue, 02 Apr 2019 01:30:00 GMT; Path=/', 'X-RateLimit-Limit': '150', 'X-RateLimit-Remaining': '148', 'X-RateLimit-Reset': '1553563801', 'X-Powered-By': 'Profit', 'ETag': 'W/"3e-SPtO6/Zf3slFmE++bSi+xCO4Qqs"', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'} {"error":{"message":"binSize is invalid.","name":"HTTPError"}}
```

**Comment by kroitor** [comment]
@mrktmr for some reason the url that is being called is 

- https://bitmex.com/api/v1/trade/bucketed?symbol=XBTUSD&binSize=1h&partial=True&count=750&startTime=2015-09-26+00%3A00%3A00

↑ which doesn't work... whereas the proper URL should be:

- https://www.bitmex.com/api/v1/trade/bucketed?symbol=XBTUSD&binSize=1h&partial=True&count=750&startTime=2015-09-26+00%3A00%3A00

↑ which works.

How do you initialize the exchange class?

**Comment by kroitor** [comment]
> I am not able to get OHLCV data from https://bitmex.com. 

So, the answer is: Don't expect anything from `https://bitmex.com` at all. It's not the correct URL to be used with BitMEX.

Either use `https://www.bitmex.com` or just use the default URL as is from CCXT (don't override it at all in the exchange constructor). Let us know if that doesn't answer the question.

**Comment by mrktmr** [comment]
Yes that is the problem, many thanks for review the issue. I should have seen that!
