### ISSUE TITLE
fetch_ohlcv candle size

### ISSUE THREAD

**Issue by Arrmlet** [ccxt/ccxt#4892]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- Ubuntu:
- Python:
- 1.18.400:
- Bitmex:
- fetch_ohlcv:

Hi why I can't fetch OHLCV data for 15m 30m, 4h, candles?
My code:
```
def get_close_prices(exch, pair,candle):
	ohlcv = exch.fetch_ohlcv(pair,candle)
	close_prices =[]
	[close_prices.append(x[4]) for x in ohlcv]
	return close_prices
```
I get the error which look like this
```
'binSize': self.timeframes[timeframe],
KeyError: '4h'
```

**Comment by kroitor** [comment]
Hi!

```Python
import ccxt
id = 'bitmex'
exchange = getattr(ccxt, id)()
print(exchange.id, 'has fetchOHLCV:', exchange.has['fetchOHLCV'])
print(exchange.id, 'supports timeframes:', exchange.timeframes)
```

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

Let us know if that doesn't answer the question.

**Comment by Arrmlet** [comment]
Hi, thank you for fast response, I have one more question why fetch_ohlcv() returns only 100 datapoints. Thanks

**Comment by kroitor** [comment]
@Arrmlet

> I have one more question why fetch_ohlcv() returns only 100 datapoints

This question is answered here: 

- https://github.com/ccxt/ccxt/wiki/Manual#pagination
- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts

In general, there's a limit of data that the exchanges will return, so you should fetch it iteratively.

**Comment by Arrmlet** [comment]
@kroitor 
Thanks, Its looks too complicated, I cant imagine how to get for example 2000 '5m' ohlcv datapoints :(

**Comment by kroitor** [comment]
@Arrmlet see the examples here: https://github.com/ccxt/ccxt/tree/master/examples

**Comment by Arrmlet** [comment]
@kroitor 
Wow, thank you very much:))

**Comment by Arrmlet** [comment]
```
import ccxt
from pprint import pprint
from datetime import datetime
import itertools

exchange = ccxt.bitmex()

dt_obj = datetime.strptime('20.03.2019 00:00:00,00',
                           '%d.%m.%Y %H:%M:%S,%f')
millisec = dt_obj.timestamp() * 1000
const = 30000000 # 500 minutes into milisecond
dat = datetime.now() 
ml = dat.timestamp() * 1000
iterator = 0
a = (ml - millisec)/const +1

ohlcv_data = []
for i in range(0, int(a)):
    data = exchange.fetch_ohlcv('BTC/USD', '5m', since =millisec + iterator)
    ohlcv_data.append(data)
    iterator += const
    print(iterator)

merged = list(itertools.chain(*ohlcv_data))

pprint(merged)
```
Maybe its will be useful for someone.

**Comment by kroitor** [comment]
@Arrmlet thx for the feedback, I'm sure it will help!
