### ISSUE TITLE
Question about cancelOrder

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#4893]
OS: Windows 10
Programming Language version: Node.js
CCXT version: #465
Exchange: All Exchanges
Node.js 11.9.0 installed
Method: await cancelOrder()

Hello!

I have a question about the cancelOrder call. I will ask about the below that I find in the manual:
It says that when cancel the order, one should **retry** to call cancelOrder again to let the cache to not fall out of sync.

I think I understand what is written but the detail I specifically wonder about is this:
If one calls cancelOrder and in the first response returns that the status of the order is Cancelled.
Do one still need to retry the call once more even that we know that it was cancelled(Is there any extra mechanics in the cache to Anyway retry the cancelOrder call to let everything be in sync)?

```javascript
var returnedvalue = await cancelOrder(exchange, exchangename, id, symbol);
var obj = JSON.parse(returnedvalue);
//obj.status == "Canceled"
```

```javascript
for a request to cancelOrder a user is required to retry the same call the second time. If instead 
of a retry a user calls a fetchOrder, fetchOrders, fetchOpenOrders or fetchClosedOrders right 
away without a retry to call cancelOrder, this may cause the .orders cache to fall out of sync. 
A subsequent retry to cancelOrder will return one of the following possible results:

1. a request is completed successfully, meaning the order has been properly canceled now
2. an OrderNotFound exception is raised, which means the order was either already 
canceled on the first attempt or has been executed (filled and closed) in the meantime 
between the two attempts.
```

**Comment by kroitor** [comment]
> If one calls cancelOrder and in the first response returns that the status of the order is Cancelled.
Do one still need to retry the call once more even that we know that it was cancelled(Is there any extra mechanics in the cache to Anyway retry the cancelOrder call to let everything be in sync)?

In short: **no**.

> If one calls cancelOrder and in the first response returns that the status of the order is Cancelled.

All of the above is written for a situation when multiple conditions meet:
- the exchange is using the `.orders` cache (does not have `fetchOrder` or `fetchOrders`, `fetchClosedOrders`) – that is 3-4 exchanges of more than 130+ exchanges
- your first call to `cancelOrder` fails – even more rare

The above conditions are very rare, so, for example, if your exchange is not using the `.orders` cache – you can work with the orders normally. Or, if your first call to `cancelOrder` did not fail – you can proceed to working with the orders normally as well. So, the text you cited from the Manual is describing a situation when all of those conditions are met: your first call to `cancelOrder` fails on an exchange that is using the `.orders` cache.

So, in general, there's two scenarios for the first call:

- The exchange is using `.orders` cache and your first `cancelOrder` succeeds. If it succeeded (your question) – you don't have to call it the second time.
- The exchange is using `.orders` cache and your first `cancelOrder` fails.  It could fail for different reasons, as described here: 
  - https://github.com/ccxt/ccxt/blob/master/js/base/errors.js#L29
  - https://github.com/ccxt/ccxt/wiki/Manual#error-handling
  - https://github.com/ccxt/ccxt/wiki/Manual#orders-cache

The reasons could be:

- `CancelPending` – this one is easy, it means the order is already being canceled. You might want to check your trades later. Or you might want to try and cancel it again to see if it was finally canceled or not. Depends on what you want your application to do.
- `OrderNotFound` – the order has been canceled and the exchange doesn't see it anymore.
- `OrderNotCached` – you're trying to cancel the order that CCXT hasn't seen after the instance was created. It means you probably forgot to restore your `.orders` cache or mismanaged it somehow. How to react – depends on what you want the program to do. It could tolerate these errors if you catch and handle them properly or it could show a big red warning and crash at your discretion.
- `InvalidOrder` – a generic superset error meaning one of the above (it's up to you to figure out what exactly, by observing trades, balances and as much of the other data as you can get or did know to this point about that specific order, whether you've seen it being open or not previously, etc, etc...)

So, a more explicit answer to your question is: if your first call to `cancelOrder` succeeds, there's probably nothing to worry about. 

Hope this clarifies it a bit... Feel free to reopen this or just ask further questions if you have more.

**Comment by jackpotcityco** [comment]
Thank you very much for that detailed answer. That really explains good.
Now I understand when to retry a cancelOrder call.
