### ISSUE TITLE
Gate.io load market error

### ISSUE THREAD

**Issue by lampardlb** [ccxt/ccxt#4894]
- OS: windows/linux
- Programming Language version: python 3.6
- CCXT version:0.18.387
- Exchange: Gate.io
- Method: load_markets()

when trying to load market, this error emerges:

Traceback (most recent call last):
    gateio.load_markets()
  File "Python\Python37-32\lib\site-packages\ccxt\base\exchange.py", line 1082, in load_markets
    markets = self.fetch_markets(params)
  File "Python\Python37-32\lib\site-packages\ccxt\gateio.py", line 159, in fetch_markets
    baseId, quoteId = id.split('_')
ValueError: too many values to unpack (expected 2)

**Comment by kroitor** [comment]
Oh... I guess, they've introduced a currency with an underscore in its code...

**Comment by lampardlb** [comment]
Thanks man. Yes I guess so - these exchanges always give headaches...

**Comment by kroitor** [comment]
What the fuck. Seriously...

- https://data.gate.io/api2/1/marketinfo

**Comment by kroitor** [comment]
<img width="1121" alt="Screen Shot 2019-03-27 at 01 59 48" src="https://user-images.githubusercontent.com/1294454/55039127-10aff800-5034-11e9-807e-6a4e472e63d8.png">

**Comment by lampardlb** [comment]
Probably gate.io can't afford half-decent developers...

**Comment by kroitor** [comment]
> Probably gate.io can't afford half-decent developers...

Yeah, but at the same time, they can afford taking decent fees from users of their API, can they?... The two facts somehow disagree in my head.

Anyways, I've uploaded a workaround for it. So, we should be ok as of 1.18.402 (401 has a minor mistake).
