### ISSUE TITLE
Documentation should include instructions on vulnerability reporting

### ISSUE THREAD

**Issue by DylanKojiCheslin** [ccxt/ccxt#4896]
I may have found a vulnerability, and I don't think that announcing it in the pubic issues is a good idea.   

The contributing guide or readme should give direction on what to do in this situation.

**Comment by kroitor** [comment]
Added the instructions here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#reporting-vulnerabilities-and-critical-issues. Feel free to contact us at info@ccxt.trade. Thanks for your help in advance!
