### ISSUE TITLE
Question about "cost" in different orders

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#4899]
OS: Windows 10
Programming Language version: Node.js
CCXT version: #465
Exchange: All Exchanges
Node.js 11.9.0 installed
Method: createOrder, cancelOrder, fetchOrder, fetchClosedOrders

Hello!

I have a general question about the below methods when implementing correct mathematics:
```javascript
createOrder(exchange, exchangename, symbol, type, side, amount, price);
cancelOrder(exchange, exchangename, id, symbol);
fetchOrder(exchange, exchangename, id, symbol);
fetchClosedOrders(symbol, since)
```
The question is about the "cost" response like below:
```javascript
{
    'id':                '12345-67890:09876/54321', // string
    'datetime':          '2017-08-17 12:42:48.000', // ISO8601 datetime of 'timestamp' with milliseconds
    'timestamp':          1502962946216, // order placing/opening Unix timestamp in milliseconds
    'lastTradeTimestamp': 1502962956216, // Unix timestamp of the most recent trade on this order
    'status':     'open',         // 'open', 'closed', 'canceled'
    'symbol':     'ETH/BTC',      // symbol
    'type':       'limit',        // 'market', 'limit'
    'side':       'buy',          // 'buy', 'sell'
    'price':       0.06917684,    // float price in quote currency
    'amount':      1.5,           // ordered amount of base currency
    'filled':      1.1,           // filled amount of base currency
    'remaining':   0.4,           // remaining amount to fill
    'cost':        0.076094524,   // 'filled' * 'price' (filling price used where available)
    'trades':    [ ... ],         // a list of order trades/executions
    'fee': {                      // fee info, if available
        'currency': 'BTC',        // which currency the fee is (usually quote)
        'cost': 0.0009,           // the fee amount in that currency
        'rate': 0.002,            // the fee rate (if available)
    },
    'info': { ... },              // the original unparsed order structure as is
}
```
As seen in above example, it shows: "0.076094524" (filled' * 'price)
What I wonder in this example: 

**- We do Buy ETH for BTC.**

I wonder if it is true that we actually then do have Exactly **0.076094524 ETH** in the account or do one need to take any fee into considiration (0.2%(0.002)).
I mean, if the trade ends here. Would it be safe to for example then Sell Exactly or Maximum **0.076094524 ETH** to another currency? (Taking correct rounding into acccount)

I wonder if this is safe to do this for all the methods: <br />
**createOrder, cancelOrder, fetchOrder, fetchClosedOrders** ?

Thank you

**Comment by tankakatan** [comment]
@jackpotcityco first, let me please correct your formulation to prevent a possible confusion. When we talk about exchange orders/trades, we assume that we want to buy or sell an `amount` (that may or may not be `filled`) of base asset (i.e. ETH in your case) at `price` (and for `cost`) of the quote asset (i.e. BTC in your case).

It means that in your example 0.076094524 is the value of BTC that you pay for 1.1 ETH and 0.0009 BTC is the fee that you pay on top of it.

Now regarding your question (if i get it right). Let us assume that the fee currency is the same as the one you want to earn in via your order. You want to know whether the fee will reduce your earning or not. If i understood you correctly, then the answer is **yes** – the `fee.cost` will always be commissioned from the `fee.currency` account regardless the order `side`.

To clarify the above let's run through all possible combinations:

* after your _buy_ order of X ETH at price of Y BTC with fee of Z BTC filled, your ETH balance will be _replenished_ by X while your BTC balance will be _diminished_ by (Y*X)+Z

* after your _sell_ order of X ETH at price of Y BTC with fee of Z BTC filled, your ETH balance will be _diminished_ by X while your BTC balance will be _replenished_ by (Y*X)-Z

* after your _buy_ order of X ETH at price of Y BTC with fee of Z ETH filled, your ETH balance will be _replenished_ by X-Z while your BTC balance will be _diminished_ by Y*X

* after your _sell_ order of X ETH at price of Y BTC with fee of Z ETH filled, your ETH balance will be _diminished_ by X+Z while your BTC balance will be _replenished_ by Y*X

The above rules are true for all exchanges and will be applied to all methods that you have mentioned
> createOrder, cancelOrder, fetchOrder, fetchClosedOrders

Does this answer your question?

**Comment by kroitor** [comment]
@jackpotcityco let us know if you have further questions.
