### ISSUE TITLE
Bitfinex tickers

### ISSUE THREAD

**Issue by orrelln** [ccxt/ccxt#490]
Currently, there isn't a way to fetch all bitfinex tickers while there is an API call that allows this: https://api.bitfinex.com/v1/tickers

**Comment by kroitor** [comment]
Thanks, @orrelln ! We will add support for all tickers to Bitfinex asap!

**Comment by kroitor** [comment]
This feature was added as of version 1.10.52. Thx!

**Comment by orrelln** [comment]
I appreciate the fast addition, thank you!
