### ISSUE TITLE
Leverage Order bitmex

### ISSUE THREAD

**Issue by Arrmlet** [ccxt/ccxt#4900]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- Ubuntu:
- Python3:
- 1.18.400:
- Bitmex:
- idk:

Hi there, I have a trouble with placing orders with leverage on bitmex.

Lets say I have avaible 0.1 XBT on my bitmex account, and I want to place a market buy order with 50 leverage, how I can do it?

I'm try to use implicit methods but it without results.

**Comment by Arrmlet** [comment]
I'm trying to run this but its opened a position with margin 50x. I'm don't know where I can set up leverage. How I can create a order for 5% of my balance with margin(leverage) 5
```
import ccxt  


exchange = ccxt.bitmex({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
})

symbol = 'BTC/USD' 
type = 'Market'  
side = 'buy'  
amount = 100.0
price =  None

# extra params and overrides
params = {
    'leverage': 6000.0,  # if needed
}

order = exchange.create_order(symbol, type, side, amount, price, params)
print(order)
```

**Comment by lampardlb** [comment]
> I'm trying to run this but its opened a position with margin 50x. I'm don't know where I can set up leverage. How I can create a order for 5% of my balance with margin(leverage) 5
> 
> ```
> import ccxt  
> 
> 
> exchange = ccxt.bitmex({
>     'apiKey': 'YOUR_API_KEY',
>     'secret': 'YOUR_SECRET',
>     'enableRateLimit': True,
> })
> 
> symbol = 'BTC/USD' 
> type = 'Market'  
> side = 'buy'  
> amount = 100.0
> price =  None
> 
> # extra params and overrides
> params = {
>     'leverage': 6000.0,  # if needed
> }
> 
> order = exchange.create_order(symbol, type, side, amount, price, params)
> print(order)
> ```
Hi,
  You need to post leverage first and separately before you create buy order. The code should be something like:

```
import ccxt  


bitmex = ccxt.bitmex({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
})

symbol = 'BTC/USD' 
type = 'Market'  
side = 'buy'  
amount = 100.0     # this should be the base currency amount, in this case XBT. 
price =  None

# set up leverage level:
lev = 50  # 50x leverage

# If you want to buy with fixed amount of USD, say, amt, you need to calculate the XBT you are able to buy from the order book first, the leverage level allows you to calculate the XBT with amt*lev.

bitmex.private_post_position_leverage(
                            {"symbol": "XBTUSD", "leverage": str(lev)})

order = exchange.create_order(symbol, type, side, amount, price)
print(order)
```
 This structure works for me, hope these help you.

**Comment by Arrmlet** [comment]
@lampardlb  Thank you a lot.
