### ISSUE TITLE
How to actually catch Error Handling with code

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#4901]
OS: Windows 10
Programming Language version: Node.js
CCXT version: #465
Exchange: All Exchanges
Node.js 11.9.0 installed
Method: Error Handling

Hello!

I am looking at the Error Handling in the Manual.
https://github.com/ccxt/ccxt/wiki/Manual#error-handling

I might wonder how you actually create code to catch the error in practic. I beleive it is a code question. If we have this cancelOrder like below and we do get an error. How do I actually catch this in code correctly? I am not sure how to set it up.
```javascript
// JavaScript
(async () => {
	var returnedvalue = await cancelOrder(exchange, exchangename, id, symbol);

	//Let us assume that this produces an Error. How to catch this?
 })()

class BaseError extends Error {
    constructor () {
        super ()
        // a workaround to make `instanceof BaseError` work in ES5
        this.constructor = BaseError
        this.__proto__   = BaseError.prototype
    }
}
```
Thank you!

**Comment by kroitor** [comment]
Hi!

I've added a small section to the Manual showing how to catch the exceptions:

- https://github.com/ccxt/ccxt/blob/master/wiki/Manual.md#error-handling (will be on the main wiki shortly)

And I've added an example in JS here:

- https://github.com/ccxt/ccxt/blob/master/examples/js/error-handling.js

Unfortunately, exception handling is a topic too wide to be explained briefly and is mostly beyond the scope of this Manual. The concept of **exception** is a general way of handling errors, if you understand how it works in one language, you can quickly find it in most of other object-oriented languages as well.

If you're not sure how to handle exceptions with JavaScript, then you definitely need more practice with basic concepts of your programming language first. Google (literally type in the following keywords) and search on YouTube for articles and videos explaining:

- exception handling in JavaScript
- how to handle exceptions in JavaScript
- what is exception handling
- what is an exception
- how to catch exceptions in JavaScript
- JavaScript error handling
- JavaScript exception handling

... and mix these keywords in different order... do your homework research ;P

Also, read and understand the examples, for instance:

- https://github.com/ccxt/ccxt/blob/master/examples/js/looping-over-all-symbols-of-specific-exchanges.js

Hope that answers your question.

**Comment by jackpotcityco** [comment]
Thank you very much that was perfect, the example in the manual you added:
https://github.com/ccxt/ccxt/blob/master/wiki/Manual.md#error-handling

I am used to use try{}catch{} blocks to catch errors but the example you added to the manual was very good showing the below for example to distinguish the errors.
```javascript
(e instanceof ccxt.NetworkError) 
and 
(e instanceof ccxt.ExchangeError)
```
Thank you :)
