### ISSUE TITLE
Hitbtc fetch_markets do not return all markets

### ISSUE THREAD

**Issue by cenyG** [ccxt/ccxt#4903]
Hi, I'm trying to figure out why when I fetch markets from **HitBTC** using CCXT it doesn't return me all markets.    
This question is actually about `BCHABCBTC`, `BCHABCUSD`, `BCHSVBTC`, `BCHSVUSD` and other `BCH`. CCXT returns only `BCHABC` pairs and named them as `BCH`.     
Why it is working in this way?

**Comment by kroitor** [comment]
Hi!

> Why it is working in this way?

This question has been answered here, they're all accessible under corresponding names, and the naming schema is explained here:

- https://github.com/ccxt/ccxt/wiki/Manual#naming-consistency
- https://github.com/ccxt/ccxt/wiki/Manual#notes-on-naming-consistency
- https://github.com/ccxt/ccxt/issues/4311
- https://github.com/ccxt/ccxt/blob/master/js/hitbtc.js#L487

```JavaScript
886 objects
mbp:ccxt igorkroitor$ node examples/js/symbols.js hitbtc2
Instantiating hitbtc2 exchange

Symbols:

tierBased | percentage | taker | maker   | id        | symbol            | base         | quote | baseId | quoteId | active
---------------------------------------------------------------------------------------------------------------------------
...
false     | true       | 0.002 | 0.001   | BCHABCBTC | BCH/BTC           | BCH          | BTC   | BCHABC | BTC     | true
false     | true       | 0.002 | 0.001   | BCHABCUSD | BCH/USDT          | BCH          | USDT  | BCHABC | USD     | true
...
false     | true       | 0.002 | 0.001   | BCHSVBTC  | BSV/BTC           | BSV          | BTC   | BCHSV  | BTC     | true
false     | true       | 0.002 | 0.001   | BCHSVUSD  | BSV/USDT          | BSV          | USDT  | BCHSV  | USD     | true
...
false     | true       | 0.002 | 0.001   | BCHBTC    | Bitcoin Cash/BTC  | Bitcoin Cash | BTC   | BCH    | BTC     | true
false     | true       | 0.002 | 0.001   | BCCFDAI   | Bitcoin Cash/DAI  | Bitcoin Cash | DAI   | BCH    | DAI     | true
false     | true       | 0.002 | 0.001   | BCHETH    | Bitcoin Cash/ETH  | Bitcoin Cash | ETH   | BCH    | ETH     | true
false     | true       | 0.002 | 0.001   | BCCFEURS  | Bitcoin Cash/EURS | Bitcoin Cash | EURS  | BCH    | EURS    | true
false     | true       | 0.002 | 0.001   | BCCFTUSD  | Bitcoin Cash/TUSD | Bitcoin Cash | TUSD  | BCH    | TUSD    | true
false     | true       | 0.002 | 0.001   | BCHUSD    | Bitcoin Cash/USDT | Bitcoin Cash | USDT  | BCH    | USD     | true

---------------------------------------------------------------

Currencies:

id      | code         | type   | payin | payout | transfer | name                          | active | fee       | precision
----------------------------------------------------------------------------------------------------------------------------
...
BCHABC  | BCH          | crypto | true  | true   | true     | Bitcoin Cash ABC              | true   | 0.0201    | 8
...
BCHSV   | BSV          | crypto | true  | true   | true     | Bitcoin Cash SV               | true   | 0.1701    | 8
...
BCH     | Bitcoin Cash | crypto | false | false  | true     | Bitcoin Cash                  | false  | 0.0018    | 8

---------------------------------------------------------------
hitbtc2 has 886 symbols and 540 currencies

mbp:ccxt igorkroitor$
```

↑ Let us know if that doesn't resolve the issue for you.

**Comment by npomfret** [comment]
I'm sorry, I bet you're all very bored of this problem, but I'm still a little confused.  Is it not the case that BCHABC is just a new name for pre fork BCH and they are fungible / interchangeable assets?  If so, should they not both map to the common code of BCH?

**Comment by kroitor** [comment]
> Is it not the case that BCHABC is just a new name for pre fork BCH and they are fungible / interchangeable assets?

It is. With most of exchanges. But not with HitBTC – they've decided to keep both the old BCH and the new BCH (the ABC one). So, in order to distinguish between the two, the `BCH` unified code maps to the new one (the one that has the `BCHABC` id), but you also have the access to the old one (which has id `BCH` and unified code `Bitcoin Cash`, hitbtc-specific).

> If so, should they not both map to the common code of BCH?

When you withdraw – it's a reverse mapping from `BCH` to ... what? ) Which one would you want to withdraw if you specify `BCH`? Most likely, you'd want to withdraw the new `BCH` in that case.

**Comment by npomfret** [comment]
Ah I see (I think), so they are not strictly interchangeable on hitbtc.  One can have a BCH wallet and a BCHABC wallet on this exchange.  But they can both be withdrawn to any bitcoin cash address.

**Comment by kroitor** [comment]
@npomfret 

> But they can both be withdrawn to any bitcoin cash address.

Yep, because the address space is common. Same as with the original Bitcoin.
