### ISSUE TITLE
[BCEX] Inability to get balances

### ISSUE THREAD

**Issue by auloff** [ccxt/ccxt#4907]
- OS: Windows
- Programming Language version: Python 3.6.6
- CCXT version: 1.18.410
- Exchange: BCEX
- Method: "/fetchBalance"
**Description:** "GET 404 Client Error: Not Found for url: https://www.bcex.top/Api_Market/getPriceList"

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/4365
