### ISSUE TITLE
binance {"code":-1013,"msg":"Invalid price."}

### ISSUE THREAD

**Issue by odemolliens** [ccxt/ccxt#4911]
- OS: macosx
- Programming Language version: python
- CCXT version: 1.18.412
- Exchange: binance
- Method: create_limit_sell_order

Cxxt is working **very well** (limit buy/sell orders) on many pairs (with different price precisions) but I have issues with some pairs like BTT/BTC SC/BTC.

So I tried to harcode the price I provide to ccxt in order to see where this {"code":-1013,"msg":"Invalid price."} error is coming from

With harcoded price: 0.00000125

Price is truncated in the request: price=0.000001 **(working but wrong price)**
`
Request: POST https://api.binance.com/api/v3/order {'X-MBX-APIKEY': ‘xxxx’, 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} timestamp=xxxx&recvWindow=5000&symbol=BTTBTC&quantity=6491&type=LIMIT&side=SELL&newOrderRespType=RESULT&price=0.000001&timeInForce=GTC&signature=xxxxx
`

With harcoded price: 0.00000025

Price is truncated in the request: price=0 **(failing)**
`
Request: POST https://api.binance.com/api/v3/order {'X-MBX-APIKEY': ‘xxx’, 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} timestamp=xxxx&recvWindow=5000&symbol=BTTBTC&quantity=6491&type=LIMIT&side=SELL&newOrderRespType=RESULT&price=0&timeInForce=GTC&signature=xxxx
`
`
Response: POST https://api.binance.com/api/v3/order 400 (...) {"code":-1013,"msg":"Invalid price."}
`

it's looks like `price_to_precision` is not working correctly. What you see in the two request is what is return by this method (I tested manually myself)

EDIT: orders are now working by changing part of this ccxt code: https://github.com/0slab/ccxt/blob/master/python/ccxt/binance.py#L799

**Comment by kroitor** [comment]
Hi!

Unfortunately, your link points not to the CCXT repository, but to your own copy, which looks outdated. 

If you look into current CCXT code, there's no such lines there anymore in that place:

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L785

You should update your fork by merging the main CCXT repo into it. Or just use the main repo, not your own fork, to stay in synch. Current Python version of CCXT doesn't have that bug.

Hope that answers your question, let us know if not.

**Comment by odemolliens** [comment]
Hello @kroitor,

You right my fork was not up to date. This is now the case, I tried again without my fix and this is what I get (as proof, I added a printed value "test_416 in my fork to check that I'm using the last version"):

`2019-03-30 18:12:56,736 - BOT - INFO - API call: Sell amount 8312.0 at price 0.00000020.
test_416`

`Request: POST https://api.binance.com/api/v3/order {'X-MBX-APIKEY': 'xxx', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} timestamp=xxxx&recvWindow=5000&symbol=BTTBTC&quantity=8312&type=LIMIT&side=SELL&newOrderRespType=RESULT&price=0&timeInForce=GTC&signature=xxxx
`

`Response: POST https://api.binance.com/api/v3/order 400 (...) {"code":-1013,"msg":"Invalid price."}
2019-03-30 18:12:57,250 - BOT - WARNING - Unable to sell trade: Could not create limit sell order on market BTT/BTC.Tried to sell amount 8312.0 at rate 0.00000020 .Message: binance {"code":-1013,"msg":"Invalid price."}`


So to make my code working, I need to remove this line:
`order['price'] = self.price_to_precision(symbol, price)`
Per this one, and it's works: https://github.com/0slab/ccxt/blob/master/python/ccxt/binance.py#L800

**Comment by kroitor** [comment]
Hi @odemolliens !

> So to make my code working, I need to replace this line:
> https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L799
> With that: https://github.com/0slab/ccxt/blob/master/python/ccxt/binance.py#L800

Not really... There was also another bug in CCXT related to #4286. And I've uploaded one more fix for it. So, to make your code work, please, update to version 1.18.417 and retry again (with default code from the repo – it should work without your edit). Let me know if you still have difficulties with 1.18.417. Will be happy if you report whether it solved the issue or not. Thx!

**Comment by odemolliens** [comment]
Issue still present for me in **1.18.417**

API call: Sell amount 3571.0 at price 0.00000020

```
Request: POST https://api.binance.com/api/v3/order {'X-MBX-APIKEY': 'xxxx', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} timestamp=xxxx&recvWindow=5000&symbol=BTTBTC&quantity=3571&type=LIMIT&side=SELL&newOrderRespType=RESULT&price=0&timeInForce=GTC&signature=xxxxx
```


```
Response: POST https://api.binance.com/api/v3/order 400 (...) {"code":-1013,"msg":"Invalid price."}
2019-03-30 21:07:08,656 - freqtrade.freqtradebot - WARNING - Unable to create trade: Could not create limit sell order on market BTT/BTC.Tried to sell amount 3571.0 at rate 3.5000000000000004e-07 (total 0.00124985).Message: binance {"code":-1013,"msg":"Invalid price."}
```

**Comment by kroitor** [comment]
@odemolliens are you sure that

1. you've removed the `.format` (your edits don't overwrite the lib files now)?
2. and that your version is 1.18.417 ? 

Let's check this:

```Python
import ccxt
print(ccxt.__version__)
```

↑ Is it up to date on your system now?

**Comment by kroitor** [comment]
@odemolliens looks like you're still using your old file: https://github.com/0slab/ccxt/blob/master/python/ccxt/binance.py#L799. You should replace the entire repo with the new one, otherwise your code will still call the outdated versions. `Test_416` doesn't show your real version, because it's a hardcoded string. To show your actual version, use `print(ccxt.__version__)`. Should be 1.18.417.

**Comment by odemolliens** [comment]
Hello @kroitor,

`2019-03-31 11:28:00,684 - BOT - INFO - Using Exchange "Binance" with ccxt version:"1.18.417"`

I'm not using my fork. My fork is just to show my trouble and what is my hotfix to have a working bot.

**Comment by kroitor** [comment]
@odemolliens let's run this short test:

```Python
import ccxt
print(ccxt.__version__)
exchange = ccxt.binance({ 'enableRateLimit': True })
markets = exchange.load_markets()
print('Formatted price', exchange.price_to_precision ('BTT/BTC', 0.00000020))
```

My results are:

```Python
Last login: Sun Mar 31 12:37:47 on ttys003
mbp:python igorkroitor$ python3
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> print(ccxt.__version__)
1.18.417
>>> exchange = ccxt.binance({ 'enableRateLimit': True })
>>> markets = exchange.load_markets()
>>> print('Formatted price', exchange.price_to_precision ('BTT/BTC', 0.00000020))
Formatted price 0.0000002
>>>
```

If your results are different with version 1.18.417 – then it means something is wrong with the version setup, or some other files have been changed and left outdated since then. Let's make sure that you have the same output first.

**Comment by odemolliens** [comment]
On my side, If I execute your code at the start of my bot I get this:
**1.18.417**
**Formatted price 0.0000002**

If I execute your code later, when I trying to sell my positions
**1.18.417**
**Formatted price 0**

**Comment by kroitor** [comment]
> If I execute your code later, when I trying to sell my positions

I'm not sure how does that code relate to your positions at all. I mean, the snippet I posted above does not involve any positions whatsoever, it's a complete program that doesn't have any hidden parts in it, so, if you launch it once or twice, the result should be consistent (same result each time). If it differs, that you're either not running my code (running some other code) or some other kind of interference happens. 

When you say:

> On my side, If I execute your code at the start of my bot I get this:
> If I execute your code later, when I trying to sell my positions

If you run just my code at any instant in time (and nothing else around it, just my code in a .py file) – your result should always be the same. If that is the case, then, I guess, you should check your bot's code? The bot's code can overwrite markets for whatever reason, if it's not working correctly. So, we need to localize the issue – whether it is in ccxt or in the code outside of ccxt.

**Comment by odemolliens** [comment]
When I init my Exchange object

```
        self._api = self._init_ccxt(exchange_config)
        self._api.verbose = False
        print('Formatted price STEP1', self.price_to_precision('BTT/BTC', 0.00000020))
        
        print(ccxt.__version__)
        exchange_test_init = ccxt.binance({'enableRateLimit': True})
        exchange_test_init.load_markets()
        print('Formatted price STEP1.1', exchange_test_init.price_to_precision('BTT/BTC', 0.00000020))
```

Console:
```
Formatted price STEP1 0.0000002
1.18.417
Formatted price STEP1.1 0.0000002
```

Later in my code

```
        print(ccxt.__version__)
        exchange_test = ccxt.binance({'enableRateLimit': True})
        exchange_test.load_markets()
        print('Formatted price STEP2', exchange_test.price_to_precision('BTT/BTC', 0.00000020))
```

Console:
```
1.18.417
Formatted price STEP2 0
```

🤷‍♂️

**Comment by kroitor** [comment]
> Later in my code
> 🤷‍♂️

I suggest to compare the bytesize of files then:

Do this in your repo root:

```
ls -al python/ccxt/binance.py
ls -al python/ccxt/base/*.py
```

My results:

```
mbp:ccxt igorkroitor$ ls -al python/ccxt/binance.py
-rw-r--r--  1 igorkroitor  staff  52296 Mar 31 12:33 python/ccxt/binance.py
mbp:ccxt igorkroitor$ ls -al python/ccxt/base/*.py
-rw-r--r--  1 igorkroitor  staff   3046 Nov 21 18:44 python/ccxt/base/__init__.py
-rw-r--r--  1 igorkroitor  staff   4453 Dec 12 00:59 python/ccxt/base/decimal_to_precision.py
-rw-r--r--  1 igorkroitor  staff   5158 Nov 21 18:44 python/ccxt/base/errors.py
-rw-r--r--  1 igorkroitor  staff  75787 Mar 31 04:32 python/ccxt/base/exchange.py
mbp:ccxt igorkroitor$
```

Also, what's your version of Python ? How do you install CCXT? How do you switch between your repo version and your the original version?

**Comment by odemolliens** [comment]
```
-rw-r--r--  1 xxx  admin  52296 Mar 31 11:55 ccxt/binance.py
-rw-r--r--  1 xxx  admin   3046 Mar 30 21:04 ccxt/base/__init__.py
-rw-r--r--  1 xxx  admin   4453 Mar 30 21:04 ccxt/base/decimal_to_precision.py
-rw-r--r--  1 xxx  admin   5158 Mar 30 21:04 ccxt/base/errors.py
-rw-r--r--  1 xxx  admin  75787 Mar 30 21:04 ccxt/base/exchange.py
```

> What's your version of Python ?
```
python3.6 -V
Python 3.6.5
```

>How do you install CCXT?

I install CCXT using pip3 through requirement.txt file

> How do you switch between your repo version and your the original version?

I don't really use my repo. I just pushed my local change in your library, located in `/usr/local/lib/python3.6/site-packages`

Each time I want to come back to your repo, I just delete ccxt folder in `/usr/local/lib/python3.6/site-packages` and execute again `pip3.6 install -r requirements.txt`

**Comment by kroitor** [comment]
@odemolliens ok, can you show the contents of `requirements.txt` ? Also, does my code (if you run it in a separate file) always shows consistent results on your side?

**Comment by odemolliens** [comment]
```
ccxt==1.18.417
SQLAlchemy==1.2.10
python-telegram-bot==10.1.0
arrow==0.12.1
cachetools==2.1.0
requests==2.19.1
urllib3==1.22
wrapt==1.10.11
pandas==0.23.3
scikit-learn==0.19.2
scipy==1.1.0
jsonschema==2.6.0
numpy==1.14.5
TA-Lib==0.4.17
pytest==3.6.3
pytest-mock==1.10.0
pytest-cov==2.5.1
tabulate==0.8.2
coinmarketcap==5.0.3

# Required for hyperopt
scikit-optimize==0.5.2

# Required for plotting data
#plotly==3.0.0

```


> Also, does my code always show consistent (repeatable) results on your side if you run it in a separate file?

`ccxt_test.py` contains your sample code 

```
#!/usr/bin/env bash
for i in {1..50}; do
    python3.6 ccxt_test.py
done
```

Console:
```
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
1.18.417
Formatted price 0.0000002
(...)
```

**Comment by kroitor** [comment]
Let's add a bit more to my code snippet and do the following:

```Python
import ccxt
print(ccxt.__file__)  # ←----------------- let's add this
print(ccxt.__version__)
exchange = ccxt.binance({ 'enableRateLimit': True })
markets = exchange.load_markets()
print('Formatted price', exchange.price_to_precision ('BTT/BTC', 0.00000020))
```

Can you run this at the start of your bot and also run this like you did before – within your code as well, and paste the results here?.. If you're running the same module, those filenames should be consistent at the very least...

**Comment by odemolliens** [comment]
```
Formatted price STEP1 0.0000002
3.6.5
/usr/local/lib/python3.6/site-packages/ccxt/__init__.py
1.18.417
Formatted price STEP1.1 0.0000002
```


```
3.6.5
/usr/local/lib/python3.6/site-packages/ccxt/__init__.py
1.18.417
Formatted price STEP2 0
```

**Comment by kroitor** [comment]
@odemolliens can you make a snippet in 10-20 lines to reproduce it? I mean, can you start reducing the code (by just cutting away big junks of it temporarily in a tmp copy folder) – so that we could reproduce it on our side without having to dig through your business logic (you probably wouldn't want to disclose it anyway) ? Because we don't know what happens between STEP1.1 and STEP2 – we can only guess what might be the cause, hope for your understanding... So, at this point, it's clear that the issue isn't a simple version conflict, and in order to proceed on this issue we need something more substantial, not just the printouts, but the actual code. It would help resolve this issue quickly if you reduce the size of it to the smallest possible snippet to reproduce it.

**Comment by odemolliens** [comment]
@kroitor ok but I will take me some time to create this snippet.

Anyway, we recreate a fresh ccxt object at each print in the console so...

Is their any debug log when you instantiated CCXT ? Maybe I can compare the two instances

**Comment by kroitor** [comment]
> Anyway, we recreate a fresh ccxt object at each print in the console so...

Right, but we don't see how ccxt is imported just from that code alone, so we need to make it a short but a complete program that we would be able to run without editing, or at least something close to that. That isn't really our requirement, it is needed in order to be able to help you, because, otherwise it will be much harder, obviously...

> Is their any debug log available when you instantiated CCXT ? Maybe I can compare the two instances

Apart from what you've already seen – nope, there's no more logging (nothing to log there, really).

> Maybe I can compare the two instances

Yeah, that's what you did with the above short snippet printout-test and its output says "same instance". So, there's something more complicated going on here...

**Comment by odemolliens** [comment]
```
    def price_to_precision(self, symbol, price):
        print("price_to_precision:",price,"  ROUND:",ROUND, "   market",self.markets[symbol]['precision']['price'], "     precision:",self.precisionMode )
        return self.decimal_to_precision(price, ROUND, self.markets[symbol]['precision']['price'], self.precisionMode)
```

I added a log in `base/exchange.py` and looks like your internal parameters are always good
`price_to_precision: 0,0000002   ROUND: 1    market 8      precision: 2`


```
price_to_precision: 0,0000002   ROUND: 1    market 8      precision: 2
Formatted price STEP1 0.0000002
price_to_precision: 0,0000002   ROUND: 1    market 8      precision: 2
Formatted price STEP1.1 0.0000002
price_to_precision: 0,0000002   ROUND: 1    market 8      precision: 2
Formatted price STEP2 0
```

I will work on the snippet in coming days, it require some works ;)

**Comment by kroitor** [comment]
@odemolliens ok, looking forward to hear from you!

**Comment by odemolliens** [comment]
Looks like the issue is coming due to the fact i'm using this:

```
from decimal import Decimal, getcontext
# ccxt working well
getcontext().prec = 8
# ccxt return 0
```

**Comment by kroitor** [comment]
@odemolliens You probably don't want to do `getcontext().prec = 8` when working with exchanges (most of them require values up to 64 bits), otherwise you will start losing precision, and that's exactly what is happening.
