### ISSUE TITLE
gateio no fech_ohlcv!for gateio is emulated

### ISSUE THREAD

**Issue by yazhou8** [ccxt/ccxt#4915]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:
In ccxt, endpoint fetch_ohlcv() for gateio is emulated, which requests /api2/1/tradeHistory/. Weird thing is that in its Chinese version API docs, it does provide an OHLCV API, which is missing in the English version docs. The API is:

http://data.gateio.io/api2/1/candlestick2/[CURR_A]_[CURR_B]?group_sec=[GROUP_SEC]&range_hour=[RANGE_HOUR]

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/2801

(We will add the missing method as soon as possible).

**Comment by kroitor** [comment]
@yazhou8 We have added it in CCXT 1.18.416. Note that it doesn't support the `since` argument. Let us know if you have any questions.

**Comment by yazhou8** [comment]
Thank you! The OHLCV value obtained by fetch_ohlcv seems to be within 24 hours! Https://data.gateio.co/api2/1/candlestick2/btc_usdt?group_sec=60&range_hour=1, the official api parameter range_hour is how many hours! Equivalent to the ccxt since parameter

**Comment by kroitor** [comment]
> the official api parameter range_hour is how many hours! Equivalent to the ccxt since parameter
It's not equivalent to `since`, it's equivalent to `limit` because they will not give you more than 1001 candles, so you can't get minute history for a year ago.

**Comment by yazhou8** [comment]
I understand! Then I got 15 days of 1d 16 sets of data is no way to get through fetch_ohlcv?

**Comment by yazhou8** [comment]
I can convert 2019-03-15 00:00:00 into a timestamp, which will satisfy the multiples of the gateio api within 24 hours to get the data.

**Comment by kroitor** [comment]
@yazhou8 

> Then I got 15 days of 1d 16 sets of data is no way to get through fetch_ohlcv?

Yeah, unfortunately, it is the limit on the exchange side, we can't workaround it, and they don't accept anything close to `since`. In other words, you don't need to specify `since` at all, if you want to get 15 days of 1d candles, you just call it like `exchange.fetch_ohlcv ('ETH/BTC', '1d', None, 1001)`. That's the gateio maximum.

**Comment by yazhou8** [comment]
I understand! thank you
