### ISSUE TITLE
New exchange: Bitmax

### ISSUE THREAD

**Issue by eburnette** [ccxt/ccxt#4916]
Exchange home: bitmax.io
Api doc: https://github.com/bitmax-exchange/api-doc
Endpoint: https://bitmax.io/1/api/v1

Relatively new exchange, has cash and margin trading.

**Comment by hanyoonLDA** [comment]
Patiently waiting :) This exchange is 🔥 right now.

**Comment by Gennttii** [comment]
Hope you add this exchange, and also Hotbit and Bitmart
