### ISSUE TITLE
kucoin NEO withdrawal raises invalid address error via API but not via website

### ISSUE THREAD

**Issue by MarcelBeining** [ccxt/ccxt#4917]
- CCXT version: '1.18.400'
- Exchange: kucoin
- Method: withdraw

When I want to withdraw 1 NEO from kucoin with this code:
`client.withdraw('NEO', 1.0, 'AFtKSGZhxKt8bY9VSwGr4FcgGkBERcMrta', '1553951507')`

I get the following error:

```
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\kucoin.py", line 957, in withdraw
    response = self.privatePostWithdrawals(self.extend(request, params))

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 388, in inner
    return entry(_self, **inner_kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 417, in request
    return self.fetch2(path, api, method, params, headers, body)

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 413, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 516, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\kucoin.py", line 1248, in handle_errors
    raise ExceptionClass(self.id + ' ' + message)

ArgumentsRequired: kucoin Incorrect withdrawal address
```

However, the address is correct and working when I perform the same withdrawal on the kucoin website. Any idea what the problem is? Has it something to do with main/trading account?

**Comment by kroitor** [comment]
Does it work this way:

```
tag = '1553951507'
overrides = { 'remark': tag }
client.withdraw('NEO', 1.0, 'AFtKSGZhxKt8bY9VSwGr4FcgGkBERcMrta', tag, overrides)
```

? (If it does, then we will add an edit to the `withdraw()` implementation quickly, otherwise we will have to reach out to the KuCoin team to resolve this)

**Comment by kroitor** [comment]
@MarcelBeining you're specifying the `tag` argument, but is it required for `NEO` ? (sorry, don't know much about it)

**Comment by MarcelBeining** [comment]
Hi @kroitor 
I just talked to the kucoin support (recomendation: always talk to them via telegram kucoin group, there they are very much faster!) and when I do the withdraw without the tag it works! 
However this is a kucoin API bug then because does not make sense to raise a address error! Also I thought a transaction can always have a tag/data/whatever entry.

**Comment by MarcelBeining** [comment]
> tag = '1553951507'
> overrides = { 'remark': tag }
> client.withdraw('NEO', 1.0, 'AFtKSGZhxKt8bY9VSwGr4FcgGkBERcMrta', tag, overrides)
> 

Your suggested code also raises `ArgumentsRequired: kucoin Incorrect withdrawal address`

**Comment by kroitor** [comment]
> Also I thought a transaction can always have a tag/data/whatever entry.

Not really. The `tag` is a special addressing bit that identifies you from other users when using currencies that share the common base address for all users of an exchange (XRP, XLM, etc). So the `tag` is not your arbitrary "comment for the transaction" and you can't use it in that way. That is all described here: https://github.com/ccxt/ccxt/wiki/Manual#address-structure

So, it's not an API bug of KuCoin, and it's not a bug in CCXT (it doesn't recognize all specifics of all currencies – there's too many of them to even try), it's more like a bug in your calling code, namely, you should not pass the `tag` if it's not required by the underlying currency blockchain, and vice versa, you should pass the `tag` along with the `address` only if the underlying currency blockchain requires it. Does that clarify anything?

**Comment by MarcelBeining** [comment]
Ok did not know, thanks!
