### ISSUE TITLE
Please fix symbol collision for BitTorrent (BTT) and Blocktrade Token(BTT)

### ISSUE THREAD

**Issue by minaseem** [ccxt/ccxt#4919]
- OS: All
- Programming Language version:Nodejs
- CCXT version:1.18.265

**Comment by kroitor** [comment]
@minaseem can you help list out the conflicting exchanges? We will be able to resolve this quicker then. Thx!

**Comment by minaseem** [comment]
This is not about conflicting symbol across exchanges. Here is my scenario:

I am getting the list of currencies from coinmarketcap and fetching markets for those currencies (using symbol) from different exchanges. Since BitTorrent and BlockTrade Token have same symbol (BTT), I am not sure which how can prevent exchanges from getting confused between these symbols since I am passing BTT in both scenarios.

I understand that in such cases, currency with higher market cap (as per coinmarketcap) takes precedence. So, May be I can use BTT for Bittorrent, but what should I use for BlockTrade Token?

**Comment by kroitor** [comment]
@minaseem 

I've added a mapping for Blocktrade Token to `coinmarketcap`, it is available in 1.18.422. I highly recommend to update to it. 

> So, May be I can use BTT for Bittorrent, but what should I use for BlockTrade Token?

You should use the `'Blocktrade Token'` currency literal. This is explained here: https://github.com/ccxt/ccxt/wiki/Manual#notes-on-naming-consistency

Let us know if that doesn't help.

**Comment by minaseem** [comment]
Thanks @kroitor !

Proposed solution works when I want to fetch something for a particular currency.

My scenario is a bit different. I have the list of all the markets from an exchange and I want to filter out all the markets for BitTorrent and BlockTrade Token separately. Is there a way I can do this?

**Comment by kroitor** [comment]
> My scenario is a bit different. I have the list of all the markets from an exchange and I want to filter out all the markets for BitTorrent and BlockTrade Token separately. Is there a way I can do this?

Yes, it is explained here:

- https://github.com/ccxt/ccxt/wiki/Manual#notes-on-naming-consistency
- https://github.com/ccxt/ccxt/blob/master/examples/js/search-all-exchanges.js
- https://github.com/ccxt/ccxt/tree/master/examples/js/symbols.js

```JavaScript
const blocktradeMarkets = []
const bittorentMarkets = []
await exchange.loadMarkets()
for (symbol in exchange.symbols) {
    const market = exchange.markets[symbol]
    const base = market['base']
    if (base === 'BTT') {
        bittorentMarkets.push (market) // BTT/BTC, BTT/ETH, BTT/*
    } else if (base === 'Blocktrade Token') {
        blocktradeMarkets.push (market) // Blocktrade Token/BTC, Blocktrade Token/ETH, Blocktrade Token/* ...
    }
}
``` 

> Normally I compare compare base currency of market with symbol of currency. However, this logic breaks whenever symbol of two coins are same.

It doesn't break, your base currency will be equal to either `BTT` (for bittorent) or `Blocktrade Token` (for blocktrade token), depending on which currency it is.

**Comment by minaseem** [comment]
Thanks for making it more clear to me. You rock!
