### ISSUE TITLE
Coinspot js - empty order book

### ISSUE THREAD

**Issue by rokanost** [ccxt/ccxt#492]
Hey,
Function fetchOrderBook returns empty bids/ask arrays.

**Comment by kroitor** [comment]
Hi, @rokanost! Can you show your code? Empty bidasks are ok, if the exchange returns empty arrays, unless there's a bug somewhere, it means "no bids" or "no asks" on the orderbook stack.

**Comment by rokanost** [comment]
```
    let exchange = new ccxt.coinspot({apiKey: coinspot_key, secret: coinspot_secret});
    let markets = exchange.fetchOrderBook('BTC/AUD').then(res => console.log(res));
```

**Comment by kroitor** [comment]
@rokanost please, add `verbose = true` and post the output here:

```
let exchange = new ccxt.coinspot({
    apiKey: coinspot_key, 
    secret: coinspot_secret,
    verbose: true,
});
let markets = exchange.fetchOrderBook('BTC/AUD').then(res => console.log(res));
```
Thx!

**Comment by rokanost** [comment]
`{"status":"invalid"}`

**Comment by kroitor** [comment]
@rokanost can you post the entire output? (remove your keys if necessary)... We need to see the full request-response.

**Comment by rokanost** [comment]
I20171108-15:51:30.674(11)? coinspot POST https://www.coinspot.com.au/api/orders 
I20171108-15:51:30.751(11)? Request:
I20171108-15:51:30.752(11)?  { 'Content-Type': 'application/json',
I20171108-15:51:30.752(11)?   key: 'XXX',
I20171108-15:51:30.753(11)?   sign: 'XXXX' } {"nonce":1510116690,"cointype":"BTC"}
I20171108-15:51:31.061(11)? coinspot POST https://www.coinspot.com.au/api/orders 
I20171108-15:51:31.061(11)? Response:
I20171108-15:51:31.062(11)? {"status":"invalid"}
I20171108-15:51:31.063(11)? { bids: [],
I20171108-15:51:31.063(11)?   asks: [],
I20171108-15:51:31.064(11)?   timestamp: 1510116691061,
I20171108-15:51:31.064(11)?   datetime: '2017-11-08T04:51:31.061Z' }

**Comment by kroitor** [comment]
@rokanost, ok... did you use these API keys with any other software before?

**Comment by rokanost** [comment]
Yeah, i've used https://github.com/rtw/npm-coinspot-api to test, works fine.

**Comment by kroitor** [comment]
@rokanost can you recreate the keys and try again?

**Comment by kroitor** [comment]
@rokanost it should work if you recreate the keypair. If you cannot recreate it for some reason, there's an alternative way to redefine the nonce to milliseconds, to match the nonce generated by `npm-coinspot-api` previously:

```JavaScript
let exchange = new ccxt.coinspot({
    apiKey: coinspot_key, 
    secret: coinspot_secret,
    verbose: true,
    nonce: Date.getTime,  // ← adding this line will make it work, tho, better recreate the keys
});
let markets = exchange.fetchOrderBook('BTC/AUD').then(res => console.log(res));
```

**Comment by rokanost** [comment]
I've just tried that.
`this.nonce is not a function`

**Comment by kroitor** [comment]
@rokanost can you show the edited code?

**Comment by rokanost** [comment]
I've just tried with newly generated keys and it worked, however, your previous example does not work.

**Comment by kroitor** [comment]
@rokanost the previous example should also work as well, if you copied it without adding the brackets after `Date.getTime`. So, I guess, this issue is solved now?

**Comment by rokanost** [comment]
I've copied without brackets, but still no go. I've also tried new Date().getTime, but still no dice.

**Comment by kroitor** [comment]
@rokanost ok, and this?

```
let exchange = new ccxt.coinspot({
    apiKey: coinspot_key, 
    secret: coinspot_secret,
    verbose: true,
    nonce: function () { return Date.getTime () },  // ← try changing it like so
});
let markets = exchange.fetchOrderBook('BTC/AUD').then(res => console.log(res));
```

This should definitely work... does it?

**Comment by rokanost** [comment]
`new ccxt.coinspot({apiKey: coinspot_key, secret: coinspot_secret, verbose: true, nonce: () => new Date().getTime()});`

Did the trick. Thanks mate! 
Happy coding hehe

**Comment by kroitor** [comment]
@rokanost ok, cool. I'm closing this if you don't mind. Feel free to ask if you have any other questions or difficulties with it. Cheers!
