### ISSUE TITLE
multiprocessing.Process fetch_trade: 'luno' object has no attribute 'publicGetTickers'

### ISSUE THREAD

**Issue by ErnstDinkelmann** [ccxt/ccxt#4921]
Hi
I'm trying to spawn a process for each of a number of exchanges, and testing with a single one for now, just to get the Multiprocessing working. However, it is failing.
```python
import ccxt
import multiprocessing

if __name__ == '__main__':
    exchange_class = getattr(ccxt, 'luno')
    exchange = exchange_class()
    a_process = multiprocessing.Process(target=exchange.fetch_trades, args=('BTC/ZAR', 1553983200000))
    a_process.start()
````
fails with 
```
AttributeError: 'luno' object has no attribute 'publicGetTickers'
```
Any way to fix this?
If not, any alternatives?

Environment info:
- OS: Win 10, 64 bit
- Programming Language version: Python 3.7.2
- CCXT version: 1.18.398
- Exchange: luno
- Method: fetch_trades(), via multiprocessing.Process()

**Comment by kroitor** [comment]
I can't reproduce it on MacOS Mojave 10.14.4:

```Python
mbp:python igorkroitor$ python3
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> import multiprocessing
>>>
>>> exchange_class = getattr(ccxt, 'luno')
>>> exchange = exchange_class()
>>> a_process = multiprocessing.Process(target=exchange.fetch_trades, args=('BTC/ZAR', 1553983200000))
>>> a_process.start()
>>>
```

↑ works as a standalone script as well:

```
import ccxt
import multiprocessing

if __name__ == '__main__':
    exchange_class = getattr(ccxt, 'luno')
    exchange = exchange_class()
    def test(*args):
        result = exchange.fetch_trades(*args)
        print(result)
    a_process = multiprocessing.Process(target=test, args=('BTC/ZAR', 1553983200000))
    a_process.start()
```

```
mbp:python igorkroitor$ python3 test_multiprocess.py
[{'info': {'sequence': 6241988, 'timestamp': 1553983277690, 'price': '62200.00', 'volume': '0.01463', 'is_buy': True}, 'id': None, 'timestamp': 1553983277690, 'datetime': '2019-03-30T22:01:17.690Z', 'symbol': 'BTC/ZAR', 'order': None, 'type': None, 'side': 'buy', 'takerOrMaker': None, 'price': 62200.0, 'amount': 0.01463, 'cost': None, 'fee': {'cost': None, 'currency': None}}, {'info': {'sequence': 6241989, 'timestamp': 1553983391447, 'price': '62200.00', 'volume': '0.005483', 'is_buy': True}, 'id': None, 'timestamp': 1553983391447, 'datetime': '2019-03-30T22:03:11.447Z', 'symbol': 'BTC/ZAR', 'order': None, 'type': None, 'side': 'buy', 'takerOrMaker': None, 'price': 62200.0, 'amount': 0.005483, 'cost': None, 'fee': {'cost': None, 'currency': None}}, {'info': {'sequence': 6241990, 'timestamp': 1553983391450, 'price': '62200.00', 'volume': '0.0052', 'is_buy': True}, 'id': None, 'timestamp': 1553983391450, 'datetime': '2019-03-30T22:03:11.450Z', 'symbol': 'BTC/ZAR', 'order': None, 'type': None, 'side': 'buy', 'takerOrMaker': None, 'price': 62200.0, 'amount': 0.0052, 'cost': None, 'fee': {'cost': None, 'currency': None}}, {'info': {'sequence': 6241991, 'timestamp': 1553983391453, 'price': '62200.00', 'volume': '0.037388', 'is_buy': True}, 'id': None, 'timestamp': 1553983391453, 'datetime': '2019-03-30T22:03:11.453Z', 'symbol': 'BTC/ZAR', 'order': None, 'type': None, 'side': 'buy', 'takerOrMaker': None, 'price': 62200.0, 'amount': 0.037388, 'cost': None, 'fee': {'co...
```

Can someone confirm it? 
Will need some time to test it on Windows...

**Comment by ErnstDinkelmann** [comment]
Just tested on my Ubuntu 18.04.1 LTS and it works.

Not sure if this gives any clue, but I use pycharm and when I ctrl+click on the "fetch_trades" function, a dropdown is presented listing the function within the different exchanges. I choose the luno one. Then when I ctrl+click on the "publicGetTickers", to navigate to it, it does not even underline it and no action is performed - not "clickable". So it is not "resolved" as a recognisable object/attribute of the exchange, at least in the code.

However, this is the case in Win and Ubuntu and yet it runs in Ubuntu.

Why this happens, I could not figure out - beyond my python ability. But perhaps it's something that can just resolve at run-time when other objects have been created.

**Comment by kroitor** [comment]
> Not sure if this gives any clue, but I use pycharm and when I ctrl+click on the "fetch_trades" function, a dropdown is presented listing the function within the different exchanges. I choose the luno one. Then when I ctrl+click on the "publicGetTickers", to navigate to it, it does not even underline it and no action is performed - not "clickable". So it is not "resolved" as a recognisable object/attribute of the exchange, at least in the code.

↑ This is by design and it's explained here:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#implicit-api-methods

So, you cannot inspect those methods, because they are generated in runtime – that's ok.

However, the Windows error is a mystery. One question: is it an Anaconda Python or not on your Windows machine?

**Comment by ErnstDinkelmann** [comment]
OK, makes sens.

Yes, it's a miniconda install - both Windows and Ubuntu.

I tried on another windows 10 machine => same error.
I also installed a clean python, non-anaconda based, changed interpreter to it => same error.

**Comment by kroitor** [comment]
@ErnstDinkelmann ok, I got you... I will have to run it on a virtual machine with Windows to test it, and will get back to you with my results, if you find out something before that – let us know, don't hesitate, if anything.

**Comment by ErnstDinkelmann** [comment]
@kroitor I found a solution. It turns out multiprocessing is handled differently between WINDOWS and *NIX.

In short, as I understand it, in windows, child processes will not inherit variables created in its parent. It starts a new process from scratch, hence any objects created in the ```if __name__ == '__main__'``` is unknown to the child process, because when it imports the module for the child process, it does not run that section.

Good explanations:
https://stackoverflow.com/questions/42148344/python-multiprocessing-linux-windows-difference
https://docs.python.org/2/library/multiprocessing.html#windows

Hence, the following solves this scenario.
```python
import ccxt
import multiprocessing

exchange_class = getattr(ccxt, 'luno')
exchange = exchange_class()

def test(*args):
    result = exchange.fetch_trades(*args)
    print(result)

if __name__ == '__main__':
    multiprocessing.freeze_support()
    a_process = multiprocessing.Process(target=test, args=('BTC/ZAR', 1553983200000))
    a_process.start()
```
Note the exchange object created within the main body and not in the protected area. Whether this will always be desirable in an actual project, I'll have to see. But it's a start.

Perhaps with your much deeper understanding, you could suggest better code, which creates the variables in the protected area, and is passed to the child process via arguments. Mention of this is made in the reading, but quickly trying to do this, I did not succeed.

**Comment by frosty00** [comment]
We suggest to use a https://en.wikipedia.org/wiki/Singleton_pattern when interacting with CCXT exchanges. That is, you only want to instantiate one of each exchange because rate-limiting is done on a per exchange basis, not on the class level.

**Comment by ErnstDinkelmann** [comment]
@frosty00 
My original intent was to iterate over a number of exchange_idS (strings), say in a list, creating one exchange instance of each, and then creating a process for each to say retrieve trades.

The way it seems, this is is only possible in Windows if one now creates a (say) list of exchange instances, ie the actual instantiated classes within a list, then iterate over that list within the ```if __name__ == '__main__'``` block, to kick of the individual processes. Code to do something like this:

```python
def func_print_my_trades(exchange, *args):
    result = exchange.fetch_trades(*args)
    print(result)

lst_exchanges = []
for exchange_id in lst_exchangeids:
    lst_exchanges.append(getattr(ccxt, exchange_id)())

if __name__ == '__main__':
    lst_processes = []
    for exchange in lst_exchanges:
        lst_processes.append(multiprocessing.Process(target=func_print_my_trades, args=(exchange, 'BTC/USD', 1553983200000)))

    for one_process in lst_processes:
        one_process.start()
```
But that will certainly break you "singleton" suggestion, as the list of exchanges will be created multiple times. It does feel ugly, but I suppose, each exchange will only be used once, so no issues of rate-limiting should come into play. And the memory overhead of reloading all exchanges so many times, seems small, from what I can determine.

Can you confirm that the above will not break your rate-limiting (or other stuff) since only one instance of any class used at any one time?

Or are you in fact suggesting that it's not possible in Windows?

What about multi-threading? Some limitations, but could be a viable alternative for some.

**Comment by kroitor** [comment]
> Can you confirm that the above will not break your rate-limiting (or other stuff) since only one instance of any class used at any one time?

The above code doesn't use the rate-limiter, it is off by default and has to be enabled as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

If you're creating one process per exchange, i'd suggest that you rather pass the exchange name to the process, and create the exchange instance inside the child process:

```Python
def worker_function(exchange_id, *args):
    exchange = getattr(ccxt, exchange_id)({'enableRateLimit': True})
    result = exchange.fetch_trades(*args)
    print(result)

if __name__ == '__main__':
    lst_processes = []
    for exchange_id in lst_exchangeids:
        lst_processes.append(multiprocessing.Process(target=worker_function, args=(exchange_id, 'BTC/USD', 1553983200000)))

    for one_process in lst_processes:
        one_process.start()
```

Does that work for you?

**Comment by ErnstDinkelmann** [comment]
Yes, aware of default being false, sorry, just removed that code in the example.

I'm happy with the solution provided.

I guess some further thinking would be required if one wants to fetch trade data with multiple processes, and at the same time execute trades on one or more of the exchanges. I guess this would require rate-limiting to be implemented in the application to be safe.

You are welcome to close this issue. Thank you both.
