### ISSUE TITLE
Unable to create order on NegocieCoins

### ISSUE THREAD

**Issue by guiscaranse** [ccxt/ccxt#4924]
- OS: Windows 10
- Programming Language version: Python 3.7
- CCXT version: 1.18.422
- Exchange: NegocieCoins
- Method: createMarketSellOrder()

I am unable to create a sell order into NegocieCoins, I am keeping getting this exception: `decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]` 

I think there is a problem in [using price_to_precision method](https://github.com/ccxt/ccxt/blob/4a38204d49a5398dd8b1033bf463d4a4c36e082e/python/ccxt/negociecoins.py#L249-L254)
![Hyper_5G1mtFZ3HL](https://user-images.githubusercontent.com/4432205/55363830-d66fac00-54b4-11e9-8c21-dee33fb99eca.png)

**Comment by kroitor** [comment]
@guiscaranse `negociecoins` does not support `market` orders (only `limit` orders are supported), and for a `limit` order a price is required. I've added the missing metainfo flag to negociecoins:

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata
- https://github.com/ccxt/ccxt/wiki/Manual#market-orders

Let us know if that doesn't answer the question.

**Comment by guiscaranse** [comment]
Oh, I see. But `negociecoins.has['createMarketOrder']` returns True. 
![Hyper_xb9BT967vX](https://user-images.githubusercontent.com/4432205/55404905-576b8980-552f-11e9-8f9e-ce0e4d2c74be.png)

**Comment by kroitor** [comment]
@guiscaranse if you update to version 1.18.423, then i will return false:

```Python
import ccxt
print(ccxt.__version__)
ccxt.negociecoins().has['createMarketOrder']
```

Let us know if that doesn't help.
