### ISSUE TITLE
loadMarkets vs fetchMarkets

### ISSUE THREAD

**Issue by mkutny** [ccxt/ccxt#493]
When starting a new code I always try to remember whether I should call fetch or load and revert to Manual.

My understanding is that fetchMarkets() always goes to an exchange while loadMarkets() may return the cached copy (still with the option to go to an exchange).

But do we really need the two? Having both is a bit confusing.

**Comment by mkutny** [comment]
This also a source if this kind of weird effects (I guess that Jubi has been shut down but it still gets markets from btcbox):

```
> jubi.fetchMarkets()
Promise {
  <pending>,
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }
> (node:65026) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: jubi {"result":false,"code":"405"}
(node:65026) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> jubi.loadMarkets()
Promise {
  { 'BTC/JPY': { id: 'BTC/JPY', symbol: 'BTC/JPY', base: 'BTC', quote: 'JPY' } },
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }
> 
```

**Comment by kroitor** [comment]
> When starting a new code I always try to remember whether I should call fetch or load and revert to Manual.

You are not required to preload them manually anymore. This should be handled by ccxt. Let me know if you find a case where it's not.

> But do we really need the two? Having both is a bit confusing.

The original idea was to have load* family (a caching layer) for external API, and fetch* family for inter-library things. So, basically, we have been missing the whole set of loadTickers(), loadOrderBook(), loadOHLCV, loadOrders, etc... You're right, there's no point to mix the two in userland code and we might drop the loadMarkets completely. Now that we have all classes separated, we think of moving hardcoded market definitions to their corresponding `fetchMarkets()` implementations (that method will return hardcode). This way we could simplify and decouple it a little and also make it uniform across all languages, and then we will abandon the unnecessary methods eventually.

This is also related to solving *the "currency" problem*: https://github.com/ccxt/ccxt/pull/473

We are about to do a revision of that code.

**Comment by mkutny** [comment]
Clear now.

> You are not required to preload them manually anymore. This should be handled by ccxt. Let me know if you find a case where it's not.

I just looped over all exchanges and all tickers and have got a bunch of exceptions (as you might have guessed having my stream of PRs and issues).

And once I've got an exception I do a manual introspection, something like:
```
> const exchange = new ccxt['exchange']
> exchange.markets['symbol']
undefined
```


This is not a big problem, though.
