### ISSUE TITLE
Problems with the NegocieCoins exchange class

### ISSUE THREAD

**Issue by guiscaranse** [ccxt/ccxt#4931]
- OS: Windows 10
- Programming Language version: Python 3.7
- CCXT version: 1.18.425
- Exchange: NegocieCoins
- Method: sign

I've first created #4924 but then noticied some other problems with the Exchange class (negociecoins.py) around NegocieCoins. 

1. `requests.exceptions.InvalidHeader: Value for header {Content-Length: 71} must be of type str or bytes, not <class 'int'>`
The origin of this error is the sign method that sends `Content-Lenght` on post requests. It should be fixed by replacing `len(body)` with `str(len(body))`.

2. `TypeError: sequence item 5: expected str instance, bytes found`
This error is from 
https://github.com/ccxt/ccxt/blob/d24723056d969b5f63114c8944a16b0ddee1562d/python/ccxt/negociecoins.py#L328
It should work if replacing it with
`payload = ''.join([self.apiKey, method, uri, timestamp, nonce, str(content)])`

But then even fixing both errors it is impossible to create an order because it keeps getting
`ccxt.base.errors.AuthenticationError: negociecoins https://broker.negociecoins.com.br/tradeapi/v1/user/order POST 401 Client Error: Unauthorized for url: https://broker.negociecoins.com.br/tradeapi/v1/user/order`

I've already checked both api key and secret, it seems mostly a problem with CCXT request than the Exchange itself

**Comment by alexazevedo** [comment]
hey guys, any news on this?!

**Comment by kroitor** [comment]
Sorry for the delay, will get to it asap.

**Comment by guiscaranse** [comment]
After talking with NegocieCoins about their API, they told me that the trading endpoints are not working at the moment, so that is the reason why I was getting so many errors in CCXT. It is not a CCXT problem so this issue should be closed.

**Comment by kroitor** [comment]
@guiscaranse thx for reporting back, really appreciate it!
