### ISSUE TITLE
kucoin fetch_my_trade fails with recent timestamps

### ISSUE THREAD

**Issue by MarcelBeining** [ccxt/ccxt#4933]
- OS: Windows 10 64 bit
- Programming Language version: Python 3.6
- CCXT version: 1.18.430
- Exchange: kucoin
- Method: fetchMyTrades

When I do fetchMyTrades without a since parameter (just `kucoin.fetchMyTrades( )` ) I get my trades from after 2019-02-18 (last recent one was today).
However, when I give a timestamp that is inbetween 2019-02-18 and now, e.g.
`exchange.fetchMyTrades(since=1551448000000)`

I get:
`[]`

PS: When I provide some timestamp before 2019-02-18, e.g. 1540048000000, it works again as expected.

**Comment by kroitor** [comment]
@MarcelBeining can you post your verbose request/response, pls?

**Comment by MarcelBeining** [comment]
Request: GET https://openapi-v2.kucoin.com/api/v1/fills?startAt=1550448000000&currentPage=1 {'KC-API-KEY': 'XXXXXXXX', 'KC-API-TIMESTAMP': '1554297811451', 'KC-API-PASSPHRASE': 'XXXXXXXXXXX', 'KC-API-SIGN': 'XXXXXXXXXX', 'User-Agent': 'python-requests/2.19.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://openapi-v2.kucoin.com/api/v1/fills?startAt=1550448000000&currentPage=1 200 {'Date': 'Wed, 03 Apr 2019 13:23:31 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d69728ea21f73d67fc70c84659db4be1f1554297811; expires=Thu, 02-Apr-20 13:23:31 GMT; path=/; domain=.kucoin.com; HttpOnly; Secure, AWSALB=TDMM6/EO9IeVyt7gNYK5eES8yvmgHmI1ZEilaBQT59dG0b3E29GyZd8fid63ZWg5Qezk0OMcTgGzgCAWPf3f8hiN0kSOVcFoqvsaTa9qKqsLH8vmivsr3FDxJHRG; Expires=Wed, 10 Apr 2019 13:23:31 GMT; Path=/, X-TRACE=4nLmGzSJltSjur8G6MUeSiATepjIxYWgtP40DAUMqGQ=; Path=/, SESSION=Y2FhMzliNDAtY2I3Zi00NTMzLWIwOTgtZGJhZmYzNzY2Nzc3; Max-Age=604800; Expires=Wed, 10-Apr-2019 13:23:31 GMT; Domain=kucoin.com; Path=/; Secure; HttpOnly, __cfruid=3d0e15a42bd0a045595871c0fe4d7e7cd0013cd2-1554297811; path=/; domain=.kucoin.com; HttpOnly', 'X-TRACE-ID': '329222025b9bd21f', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Expires': '0', 'X-Frame-Options': 'DENY', 'Weight-Interval': 'SECOND', 'Weight-Expire': '1553501645', 'Weight-Limit': '100', 'Weight-Remain': '81', 'Strict-Transport-Security': 'max-age=2592000; includeSubDomains; preload', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '4c1b5b89a935c279-FRA', 'Content-Encoding': 'gzip'} {"code":"200000","data":{"totalNum":0,"totalPage":0,"pageSize":50,"currentPage":1,"items":[]}}

**Comment by MarcelBeining** [comment]
I am a bit confused that ccxt uses some the kucoin endpoint "fills" which sounds to me like it is an endpoint for general non user-specific fills (https://docs.kucoin.com/#list-fills)
There's another endpoint https://docs.kucoin.com/#list-orders which seems to be more similar to the historical order endpoint

**Comment by kroitor** [comment]
@MarcelBeining 

> I am a bit confused that ccxt uses some the kucoin endpoint "fills" 

Are you confusing `fetchMyTrades` with `fetchClosedOrders` ? The difference is explained here: 

- https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades

> which sounds to me like it is an endpoint for general non user-specific fills (https://docs.kucoin.com/#list-fills)

It is a list of user-specific fills (the `fills` endpoint requires authentication).

> There's another endpoint https://docs.kucoin.com/#list-orders which seems to be more similar to the historical order endpoint

Yes, and it is used for `fetchClosedOrders` / `fetchOpenOrders` (for a different purpose). A historical order is not the same thing as a historical trade.

>  https://openapi-v2.kucoin.com/api/v1/fills?startAt=1550448000000&currentPage=1

From your request it looks like you're adding a `currentPage` parameter, which is not accepted by the `fills` endpoint. However, I don't see that argument anywhere in your initial post, so where `currentPage` comes from is currently a mystery to me, can you clarify it a bit?

**Comment by MarcelBeining** [comment]
Oh sorry, seems I forgot to remove the params which had the page argument in it. 
However, still if I do

`exchange.fetchMyTrades(since=1551448000000 )`
I get:


Request: GET https://openapi-v2.kucoin.com/api/v1/fills?startAt=1551448000000 {'KC-API-KEY': '5c6acdc538300c74d1d743d1', 'KC-API-TIMESTAMP': '1554301377611', 'KC-API-PASSPHRASE': 'Kaskucoin.com666!', 'KC-API-SIGN': 'kDmxRb6kNQu2LD0vpmLfNDC2pmicIfa86X1s+Fq9ypk=', 'User-Agent': 'python-requests/2.19.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://openapi-v2.kucoin.com/api/v1/fills?startAt=1551448000000 200 {'Date': 'Wed, 03 Apr 2019 14:22:57 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d1c5f9b80f7096a2c5c4f81b9bd448fbd1554301377; expires=Thu, 02-Apr-20 14:22:57 GMT; path=/; domain=.kucoin.com; HttpOnly; Secure, AWSALB=uBsdr3lYrgOkDcsaTD1Yzalmzda05bogx6SGzUehQiLRvcRCQqijQxWQs4KyWKr7RywywJy5G9zvo2v4gWpn63IpwxYdExS2ktghwqVoj4J7VHZJB7pi8dMgOzs7; Expires=Wed, 10 Apr 2019 14:22:57 GMT; Path=/, X-TRACE=4nLmGzSJltSjur8G6MUeSiATepjIxYWgtP40DAUMqGQ=; Path=/, SESSION=ZmJjMzU1NjgtN2ZmZS00YmY0LWEyOWEtM2Y1ZmJlMmFjOGE2; Max-Age=604800; Expires=Wed, 10-Apr-2019 14:22:57 GMT; Domain=kucoin.com; Path=/; Secure; HttpOnly, __cfruid=b08ef774149c784fead1cb6e068426039ff849b4-1554301377; path=/; domain=.kucoin.com; HttpOnly', 'X-TRACE-ID': '87f21d8bea3cf5be', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Expires': '0', 'X-Frame-Options': 'DENY', 'Weight-Interval': 'SECOND', 'Weight-Expire': '1553501645', 'Weight-Limit': '100', 'Weight-Remain': '81', 'Strict-Transport-Security': 'max-age=2592000; includeSubDomains; preload', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '4c1bb29a29d02744-FRA', 'Content-Encoding': 'gzip'} {"code":"200000","data":{"totalNum":0,"totalPage":0,"pageSize":50,"currentPage":1,"items":[]}}

**Comment by MarcelBeining** [comment]
Hm sorry, forgot the params parameter with the page argument..
Still, if I do `exchange.fetchMyTrades(since=1551448000000 )`
I get
Request: GET https://openapi-v2.kucoin.com/api/v1/fills?startAt=1551448000000 {'KC-API-KEY': 'XXXXX', 'KC-API-TIMESTAMP': '1554301377611', 'KC-API-PASSPHRASE': 'XXXXXX', 'KC-API-SIGN': 'XXXXXX', 'User-Agent': 'python-requests/2.19.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://openapi-v2.kucoin.com/api/v1/fills?startAt=1551448000000 200 {'Date': 'Wed, 03 Apr 2019 14:22:57 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d1c5f9b80f7096a2c5c4f81b9bd448fbd1554301377; expires=Thu, 02-Apr-20 14:22:57 GMT; path=/; domain=.kucoin.com; HttpOnly; Secure, AWSALB=uBsdr3lYrgOkDcsaTD1Yzalmzda05bogx6SGzUehQiLRvcRCQqijQxWQs4KyWKr7RywywJy5G9zvo2v4gWpn63IpwxYdExS2ktghwqVoj4J7VHZJB7pi8dMgOzs7; Expires=Wed, 10 Apr 2019 14:22:57 GMT; Path=/, X-TRACE=4nLmGzSJltSjur8G6MUeSiATepjIxYWgtP40DAUMqGQ=; Path=/, SESSION=ZmJjMzU1NjgtN2ZmZS00YmY0LWEyOWEtM2Y1ZmJlMmFjOGE2; Max-Age=604800; Expires=Wed, 10-Apr-2019 14:22:57 GMT; Domain=kucoin.com; Path=/; Secure; HttpOnly, __cfruid=b08ef774149c784fead1cb6e068426039ff849b4-1554301377; path=/; domain=.kucoin.com; HttpOnly', 'X-TRACE-ID': '87f21d8bea3cf5be', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Expires': '0', 'X-Frame-Options': 'DENY', 'Weight-Interval': 'SECOND', 'Weight-Expire': '1553501645', 'Weight-Limit': '100', 'Weight-Remain': '81', 'Strict-Transport-Security': 'max-age=2592000; includeSubDomains; preload', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '4c1bb29a29d02744-FRA', 'Content-Encoding': 'gzip'} {"code":"200000","data":{"totalNum":0,"totalPage":0,"pageSize":50,"currentPage":1,"items":[]}}

**Comment by kroitor** [comment]
@MarcelBeining 1551448000000 corresponds to 2019-03-01T13:46:40.000Z – do you have trades after that date?

**Comment by kroitor** [comment]
@MarcelBeining here's what KuCoin doc says about the arguments:

> Data time range
> You can retrieve data within time range of one week (default is latest week, the start and end time range cannot exceed 24*7 hours, 604800000 milliseconds). If it exceeds one week, the system will prompt you exceed the time limit.If you pass the start time when querying fills and do not pass the end time, the system will automatically construct the end time as the start time + 24*7 hours, and vice versa.

Looks like the request is ok and it should return the trades, right?

**Comment by kroitor** [comment]
@MarcelBeining actually, the `currentPage` is also supported by the `fills` endpoint, it is documented in a different section of the API doc. But anyways, from your words, it doesn't make a difference... I will try to reach out to KuCoin to check if this is an issue on the exchange side.

**Comment by MarcelBeining** [comment]
Ok thank you. This data time range is weird, why don't they just use paging as for any other endpoint? =/
Your ccxt class already implements going through all the weeks one after the other?

**Comment by kroitor** [comment]
@MarcelBeining a quick question, do you have trades within a week after 2019-03-01T13:46:40.000Z? Because if you don't the empty result is expected and documented, no?

**Comment by MarcelBeining** [comment]
Indeed, between 12th Feb and 19th March I had no trades....
But the way kucoin returned results was very different a few weeks (or days??) ago and usually how the ccxt "since" works is that it provides everything since this time point until a limit from which on you have to do paging, right?? This here unfortunately is totally different =(

**Comment by kroitor** [comment]
> Indeed, between 12th Feb and 19th March I had no trades....
> But the way kucoin returned results was very different a few weeks (or days??) ago and usually how the ccxt "since" works is that it provides everything since this time point until a limit from which on you have to do paging, right?? This here unfortunately is totally different =(

Yeah, we will add a warning to inform the users about that, it will be acknowledgeable and you will be able to suppress it. I guess, at this point, we can consider this issue closed?

**Comment by MarcelBeining** [comment]
Yes I'll close. I will start complaining @ kucoin as long as they do not make this as simple as the other endpoint paginations :-D

**Comment by kroitor** [comment]
We are going to add a new option that changes this behavior for fetchMyTrades: 

- https://github.com/ccxt/ccxt/issues/5443
- https://github.com/ccxt/ccxt/pull/5448

```Python
import ccxt
exchange = ccxt.kucoin({
    'options': {
        // ← default, also: 
        'fetchMyTradesMethod': 'private_get_fills', // 'private_get_limit_fills', 'private_get_hist_orders'
    }
})
```
