### ISSUE TITLE
[Binance] Incorrect trade's side detection

### ISSUE THREAD

**Issue by alexeymarunin** [ccxt/ccxt#4935]
- OS: macOS 10.14.4
- Programming Language version: Node.js
- CCXT version: 1.18.230
- Exchange: Binance
- Method: parseTrade

```javascript
  parseTrade (trade, market = undefined) {
    // ...
        if ('m' in trade) {
            side = trade['m'] ? 'sell' : 'buy'; // this is reversed intentionally
   // ...
}
```
Field `m` appears only in [aggTrades](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#compressedaggregate-trades-list) endpoint.

I think if trade['m'] is true side should be 'buy', not 'sell'

Sample (real) trade
```json
{
  "info": {
    "symbol": "RVNBTC",
    "id": 5712910,
    "orderId": 26487252,
    "price": "0.00001578",
    "qty": "71.00000000",
    "quoteQty": "0.00112038",
    "commission": "0.00019939",
    "commissionAsset": "BNB",
    "time": 1554112186131,
    "isBuyer": false,
    "isMaker": true,
    "isBestMatch": true
  },
  "timestamp": 1554112186131,
  "datetime": "2019-04-01T09:49:46.131Z",
  "symbol": "RVN/BTC",
  "id": "5712910",
  "order": "26487252",
  "takerOrMaker": "maker",
  "side": "sell",
  "price": 0.00001578,
  "cost": 0.00112038,
  "amount": 71,
  "fee": {
    "cost": 0.00019939,
    "currency": "BNB"
  }
}
```
The side is 'sell' and it corresponds to trades list in Binance user's profile

In my app I listen [trades websocket](https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#trade-streams) and trade has similar (like aggTrades trade) structure - with `m` field:

```json
{
  "e": "trade",
  "E": 123456789,
  "s": "BNBBTC",
  "t": 12345,
  "p": "0.001",
  "q": "100",
  "b": 88, 
  "a": 50,
  "T": 123456785,
  "m": true,
  "M": true
}
```
I parse incoming trades like it makes ccxt, then store to local storage. That trade (id=5712910) was stored as 'buy' and it's incorrect.

I checked some other trades - the same case.

**Comment by kroitor** [comment]
> I think if trade['m'] is true side should be 'buy', not 'sell'
> was stored as 'buy' and it's incorrect.

Can you, please, clarify why it's incorrect?

Please, see duplicate issues and answers here:

- https://github.com/ccxt/ccxt/issues/4618#issuecomment-461157777
- https://github.com/ccxt/ccxt/pull/538

Let us know if those ↑ posts don't resolve the issue. Feel free to reopen it if needed, or just ask further questions, if any.

**Comment by alexeymarunin** [comment]
I answered in https://github.com/ccxt/ccxt/issues/4618#issuecomment-479899265
