### ISSUE TITLE
Bitstamp : Not handing errors properly

### ISSUE THREAD

**Issue by devsi** [ccxt/ccxt#4937]
When Bitstamp throws an error, it often returns it like so:

```
array:1 [▼
  "error" => array:2 [▼
    "amount" => array:1 [▼
      0 => "You have only 0.00100000 BTC available. Check your account balance for details."
    ]
    "address" => array:1 [▼
      0 => "Ensure this value has at least 25 characters (it has 4)."
    ]
  ]
]
```

Currently in `handleErrors()` Bitstamp errors are accessed like this:
```
let error = this.safeString (response, 'error');
```

This is bad, as the errors aren't strings (maybe sometimes if they're inconsistent?)

This most likely needs to be changed to:
```
let error = this.safeValue (response, 'error');
```

Happy to make this change for you guys in the morning if you don't get to it first.

**Comment by devsi** [comment]
Infact, looks like the whole function is pretty wrong to me. It's checking to see if the exception exists in an array of exceptions that doesn't cover all the available messages from Bitstamp. Additionally, if it's not found it assumes a "status" is set to "error" which is not true either, and so will still just exit the `handleErrors()` function without throwing an Exception

**Comment by kroitor** [comment]
> Would rather see the error handling fixed first personally!

I'll do my best to get to it asap. Your contributions are welcome )
