### ISSUE TITLE
Responses of fetchWithdrawals have type 'deposit' on kucoin

### ISSUE THREAD

**Issue by MarcelBeining** [ccxt/ccxt#4939]
ATTENTION!!!
- OS: Windows 10
- Programming Language version: Python 3.6
- CCXT version: 1.18.430
- Exchange: kucoin 
- Method: fetchWithdrawals

The type of the withdrawals that you get via fetchWithdrawals have falsely  the type 'deposit'.
When I do 
`[val['type']  for val in exchange.fetchWithdrawals(since=1550448000000)]`
I get
```
Out=
['deposit',
 'deposit',
 'deposit',
 'deposit',
 'deposit',
 'deposit',
 'deposit',
 'deposit',
 'deposit',
 'deposit',
 'deposit',
 'deposit']
```
The since parameter can also be left out. When I retrieve older withdrawal history by e.g. making `since=0` the type is correctly "withdrawal"

**Comment by kroitor** [comment]
@MarcelBeining can you please show the response format in verbose mode?

**Comment by MarcelBeining** [comment]
` [val['type'] for val in exchange.getSuper('fetch_withdrawals')()]
`
Request: GET https://openapi-v2.kucoin.com/api/v1/withdrawals {'KC-API-KEY': 'XXXXX', 'KC-API-TIMESTAMP': '1554373742633', 'KC-API-PASSPHRASE': 'XXXXX', 'KC-API-SIGN': 'XXXXXX', 'User-Agent': 'python-requests/2.19.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://openapi-v2.kucoin.com/api/v1/withdrawals 200 {'Date': 'Thu, 04 Apr 2019 10:29:02 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d67f59a71c778a84969d460b49f7fc37d1554373742; expires=Fri, 03-Apr-20 10:29:02 GMT; path=/; domain=.kucoin.com; HttpOnly; Secure, AWSALB=iMmHw2iiSOwG+3E/mqI9Jm/lLb1ycWzkCsuVg+JfIOqnOwQAhgp41f0APQERtFmk7oG2CN2iy5ito3kMJO/F8rVe745FaQetap76sxcq4lIWwbioFqooMUj4kt1y; Expires=Thu, 11 Apr 2019 10:29:02 GMT; Path=/, X-TRACE=4nLmGzSJltSjur8G6MUeSiATepjIxYWgtP40DAUMqGQ=; Path=/, SESSION=MGMyMDBlYTgtODFjZC00YTZhLWJlNDItZjVkYzdjZmZiNTUx; Max-Age=604800; Expires=Thu, 11-Apr-2019 10:29:02 GMT; Domain=kucoin.com; Path=/; Secure; HttpOnly, __cfruid=34480b91381993e631c2967aa1fffc96b133088e-1554373742; path=/; domain=.kucoin.com; HttpOnly', 'X-TRACE-ID': 'd80560cc1081e6f4', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Expires': '0', 'X-Frame-Options': 'DENY', 'Strict-Transport-Security': 'max-age=2592000; includeSubDomains; preload', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '4c229952ea4096e8-FRA', 'Content-Encoding': 'gzip'} {"code":"200000","data":{"totalNum":14,"totalPage":1,"pageSize":50,"currentPage":1,"items":[{"createdAt":1554326277000,"amount":"4.00000000","address":"AFtKSGZhxKt8bY9VSwGr4FcgGkBERcMrta","fee":"0.00000000","memo":"","currency":"GAS","id":"5ca52305240e4c70dd79ccde","walletTxId":"0x49456cb2445d30604d9f61eb1d6e14f85ecb1e3de168603eabea987bd767c64f","status":"SUCCESS","isInner":false,"updatedAt":1554326486000},{"createdAt":1554313570000,"amount":"1.000000000","address":"AFtKSGZhxKt8bY9VSwGr4FcgGkBERcMrta","fee":"0.000000000","memo":"","currency":"NEO","id":"5ca4f162240e4c70dd79c216","walletTxId":"0x186a8437f9510b8396082a55cf3c41788889edf837eb170ceabac332f4b55338","status":"SUCCESS","isInner":false,"updatedAt":1554313777000},{"createdAt":1554310894000,"amount":"1.000000000","address":"AFtKSGZhxKt8bY9VSwGr4FcgGkBERcMrta","fee":"0.000000000","memo":"","currency":"NEO","id":"5ca4e6ee240e4c70dd79bf37","walletTxId":"0xf8c5597f503b12789c485955b304d83de658d3fbbfacd65ca2f42e9a64853c5e","status":"SUCCESS","isInner":false,"updatedAt":1554311105000},{"createdAt":1554308796000,"amount":"1.000000000","address":"AFtKSGZhxKt8bY9VSwGr4FcgGkBERcMrta","fee":"0.000000000","memo":"","currency":"NEO","id":"5ca4debc1e73585c140b6c9c","walletTxId":"0x58cd862489b3400eb8d872bf48ca297c1671e9587760dadc1c5ef57dd816c246","status":"SUCCESS","isInner":false,"updatedAt":1554309014000},{"createdAt":1554283433000,"amount":"1.000000000","address":"AFtKSGZhxKt8bY9VSwGr4FcgGkBERcMrta","fee":"0.000000000","memo":"","currency":"NEO","id":"5ca47ba9240e4c70dd796c22","walletTxId":"0x28ed0ed7f6aa09cabde17cee8dbf1fe8f49a274b6cecec8a3a070b4160605845","status":"SUCCESS","isInner":false,"updatedAt":1554283653000},{"createdAt":1554274242000,"amount":"1.000000000","address":"AFtKSGZhxKt8bY9VSwGr4FcgGkBERcMrta","fee":"0.000000000","memo":"","currency":"NEO","id":"5ca457c21e73585c140b196c","walletTxId":"0x0af224420294545beab0bc68d684e48b7b2db319f7c6728ffdb8732829a6326a","status":"SUCCESS","isInner":false,"updatedAt":1554274457000},{"createdAt":1554225681000,"amount":"1.000000000","address":"AFtKSGZhxKt8bY9VSwGr4FcgGkBERcMrta","fee":"0.000000000","memo":"","currency":"NEO","id":"5ca39a11240e4c70dd793756","walletTxId":"0x6d77b49c043597c19118a0a17916c9491764c56144164eb147740ce6c77d62e8","status":"SUCCESS","isInner":false,"updatedAt":1554225920000},{"createdAt":1554215683000,"amount":"1.000000000","address":"AFtKSGZhxKt8bY9VSwGr4FcgGkBERcMrta","fee":"0.000000000","memo":"","currency":"NEO","id":"5ca37303240e4c70dd7929e1","walletTxId":"0x8404101ad75db0bdd57d1afaa48b65da4500d804f3651ab0ed9efd3aa40641ea","status":"SUCCESS","isInner":false,"updatedAt":1554215895000},{"createdAt":1554203952000,"amount":"1.000000000","address":"AFtKSGZhxKt8bY9VSwGr4FcgGkBERcMrta","fee":"0.000000000","memo":"","currency":"NEO","id":"5ca34530240e4c70dd791fef","walletTxId":"0xfeb47fbb4116adcd5bd8b9be9b2656577e341c0142de43e6343c79977eb7f91e","status":"SUCCESS","isInner":false,"updatedAt":1554204158000},{"createdAt":1554201405000,"amount":"2.00000000","address":"AFtKSGZhxKt8bY9VSwGr4FcgGkBERcMrta","fee":"0.00000000","memo":"","currency":"GAS","id":"5ca33b3d1e73585c140addae","walletTxId":"0x0bac6fcd824743833dddd072900dd7f69617eb384dd8c53e017f157d7d92f83e","status":"SUCCESS","isInner":false,"updatedAt":1554201626000},{"createdAt":1553952915000,"amount":"1.000000000","address":"AFtKSGZhxKt8bY9VSwGr4FcgGkBERcMrta","fee":"0.000000000","memo":"","currency":"NEO","id":"5c9f70931e7358500579bc67","status":"FAILURE","isInner":false,"updatedAt":1553952974000},{"createdAt":1553952784000,"amount":"1.000000000","address":"AFtKSGZhxKt8bY9VSwGr4FcgGkBERcMrta","fee":"0.000000000","memo":"","currency":"NEO","id":"5c9f7010240e4c54afe3863c","status":"FAILURE","isInner":false,"updatedAt":1553952964000},{"createdAt":1553952694000,"amount":"1.000000000","address":"AFtKSGZhxKt8bY9VSwGr4FcgGkBERcMrta","fee":"0.000000000","memo":"","currency":"NEO","id":"5c9f6fb61e7358500579bc54","status":"FAILURE","isInner":false,"updatedAt":1553952876000},{"createdAt":1553951336000,"amount":"1.000000000","address":"AFtKSGZhxKt8bY9VSwGr4FcgGkBERcMrta","fee":"0.000000000","memo":"","currency":"NEO","id":"5c9f6a68240e4c54afe385b9","walletTxId":"0x48c4518a9da296764c49c8d3ed3e98f9cc235138531034cf295a63ab12ca1817","status":"SUCCESS","isInner":false,"updatedAt":1553951541000}]}}
```
Out[23]: 
['deposit',
 'deposit',
 'deposit',
 'deposit',
 'deposit',
 'deposit',
 'deposit',
 'deposit',
 'deposit',
 'deposit',
 'deposit',
 'deposit',
 'deposit',
 'deposit']
```

**Comment by kroitor** [comment]
@MarcelBeining thx so much! Will fix shortly.
