### ISSUE TITLE
creating order issue for  bitsane

### ISSUE THREAD

**Issue by baotaizhang** [ccxt/ccxt#4945]
- OS: window
- Programming Language version: python 3.6.4 
- CCXT 1.18.433:
- Exchange: bitsane
- Method: create_order,create_limit_sell_order

Now  I am using  2 kinds of function for creating order to bitsane, but I received the same error message.
This is my sample code in python
```Python
import ccxt
def market_authentication(id):
    if(id == 'bittrex'):
        return {'apikey': '': ''}
    elif(id == 'bitsane'):
        return {'apikey': '5xxx', 'secretkey': '5Dxx'}    
def main():
    id = 'bitsane'
    x = market_authentication(id)
    api_key = x['apikey']  
    secret_key = x['secretkey']
    exchange = getattr(ccxt, id)({
        'apiKey': api_key,
        'secret': secret_key,
        'enableRateLitmit': True
    })
    exchange.create_order('BTC/USD', 'sell',0.001, 4900,)
    exchange.create_limit_sell_order('BTC/USD', 0.001, 4900)  
main()
```
```
Error message: 
ccxt.base.errors.InvalidNonce: bitsane {"statusCode":8,"statusText":"The nonce should be greater than the previous","result":[]}

```

**Comment by kroitor** [comment]
@baotaizhang is that a new API key? Have you used it before with any other software?

**Comment by baotaizhang** [comment]
Yeah, this is new key for me. 
And I never used this key with another software.

**Comment by kroitor** [comment]
Does this work for you:

```Python
import ccxt
def market_authentication(id):
    if(id == 'bittrex'):
        return {'apikey': '': ''}
    elif(id == 'bitsane'):
        return {'apikey': '5xxx', 'secretkey': '5Dxx'}    
def main():
    id = 'bitsane'
    x = market_authentication(id)
    api_key = x['apikey']  
    secret_key = x['secretkey']
    exchange = getattr(ccxt, id)({
        'apiKey': api_key,
        'secret': secret_key,
        'enableRateLitmit': True,
        'nonce': ccxt.Exchange.milliseconds,  # ←------------------------ add this line
    })
    exchange.create_order('BTC/USD', 'sell',0.001, 4900,)
    exchange.create_limit_sell_order('BTC/USD', 0.001, 4900)  
main()
```

?

**Comment by baotaizhang** [comment]
No , this code return this error
a. in case using create_limit_sell_order fucntion

File "t.py", line 27, in <module>
    main()
  File "t.py", line 26, in main
    exchange.create_limit_sell_order('BTC/USD', 0.001, 4900)
  File "C:\Users\baota\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\base\exchange.py", line 1549, in create_limit_sell_order
    return self.create_order(symbol, 'limit', 'sell', *args)
  File "C:\Users\baota\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\bitsane.py", line 351, in create_order
    order = self.parse_order(order, market)
  File "C:\Users\baota\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\bitsane.py", line 313, in parse_order
    if order['is_cancelled']:
KeyError: 'is_cancelled'

b. in case using create_order function
File "t.py", line 27, in <module>
    main()
  File "t.py", line 24, in main
    exchange.create_order('BTC/USD', None , 'sell', 0.001 , 4900)
  File "C:\Users\baota\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\bitsane.py", line 351, in create_order
    order = self.parse_order(order, market)
  File "C:\Users\baota\AppData\Local\Programs\Python\Python36\lib\site-packages\ccxt\bitsane.py", line 313, in parse_order
    if order['is_cancelled']:
KeyError: 'is_cancelled'

**Comment by kroitor** [comment]
@baotaizhang ok, i've uploaded some fixes for that, can you please update to the most recent version of CCXT 1.18.434 and retry with the same code (keep the `milliseconds` line) – does that resolve the issue?

**Comment by baotaizhang** [comment]
I will update the ccxt version. Thanks so much for you.

**Comment by kroitor** [comment]
@baotaizhang let us know if that doesn't help.
