### ISSUE TITLE
Query Products from BitMEX

### ISSUE THREAD

**Issue by hansen7** [ccxt/ccxt#4946]
Thanks for developing this module, I am particularly in the BitMEX exchanges due to its products of futures and high fluidity.

However, I do find the API of BitMEX is slightly different from the others.

- OS: MacOS 10.14.4 (18E226)
- Programming Language version: Python 3.7
- CCXT version: .118.433
- Exchange: BitMEX
- Method: fetch_orderbook()

**Comment by kroitor** [comment]
@hansen7 hi! Do you have a question or an issue with it?

**Comment by frosty00** [comment]
```ccxt.bitmex().fetch_order_book('BTC/USD')```
