### ISSUE TITLE
New v3 for Bleutrade API

### ISSUE THREAD

**Issue by bread9** [ccxt/ccxt#4947]
Api v2 will be discontinued soon. When will v3 be available for Bleutrade exchange?

https://app.swaggerhub.com/apis-docs/bleu/white-label/3.0.0

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/FAQ#when-will-you-add-feature-foo-for-exchange-bar--whats-the-estimated-time-when-should-we-expect-this

**Comment by npomfret** [comment]
I've had a look at the V3 API and it appears to be pretty bad.  I've tried to get in touch with the dev team to ask them to make some improvements.  Fingers crossed.

**Comment by rdebourbon** [comment]
Did you ever get any reply from their dev team regarding their new API. IMHO its missing some pretty fundamental functions, and my support tickets have gone unanswered.

**Comment by kroitor** [comment]
@rdebourbon you may want to check this related PR: https://github.com/ccxt/ccxt/pull/6371

**Comment by npomfret** [comment]
@rdebourbon I have a load of unanswered questions sitting with their support team.  I've done what I can with the new API, and agree with you that it could do with some improvements.  For now, I won't trade with them - I just get such a bad vibe from the exchange I don't trust them at all.

**Comment by npomfret** [comment]
Still no answers.  Still no way to get your trade history, not even by using the ledger.
