### ISSUE TITLE
Kucoin api doesn't return recent trades if 'since' is more than a week ago

### ISSUE THREAD

**Issue by rfortiz** [ccxt/ccxt#4949]
When using the argument 'since', trades only up to a week from since are returned. --> If since is more than a week old, recent trades are not returned. 

This is documented in their API: https://docs.kucoin.com/#list-fills --> "Data time range". IMO there are at least 3 ways to go around it, but in any case, it would be nice to get some form of warning.

1) Issue a warning/error when 'since' is more than a week ago
2) In the backend call Kucoin API with 'endAt' = current time --> should get an error message from kucoin API if range > 1 week (not tested)
3) Generate multiple queries of 1 week range. --> probably won't fit in unified API. User should still get a warning indicating multiple requests are made and rate limit might be exceeded...

- OS: unbuntu
- Programming Language version: python 3.6.7
- CCXT version: 1.18.418
- Exchange: Kucoin
- Method: fetch_my_trades

**Comment by kroitor** [comment]
@rfortiz I suggest that we move this discussion here if you don't mind: https://github.com/ccxt/ccxt/issues/4814
