### ISSUE TITLE
binance load_markets() and fetch_markets() error

### ISSUE THREAD

**Issue by hunsnowboarder** [ccxt/ccxt#495]
When I call binance.load_markets() or binance.fetch_markets() I get Exchange not available error.
Error details:
ExchangeNotAvailable: binance GET https://www.binance.com/exchange/public/product <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)> 

c:\python27\lib\site-packages\ccxt\base\exchange.pyc in raise_error(self, exception_type, url, method, error, details)
    239                 method,
    240                 url,
--> 241                 details,
    242             ]))
    243         else:

Thank you.

**Comment by kroitor** [comment]
@hunsnowboarder can you open that link from your browser tab?

See here: 

https://github.com/ccxt/ccxt/issues/452
https://github.com/ccxt/ccxt/issues/227

**Comment by kroitor** [comment]
I'm closing this as a duplicate, if you don't mind. Feel free to ask questions if you still have any. Thx!
