### ISSUE TITLE
kucoin2: fetchOrder() return zero result of price and cost of a order

### ISSUE THREAD

**Issue by DmitryVil** [ccxt/ccxt#4954]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10
- Programming Language version: python
- CCXT version: 1.18.437
- Exchange: kucoin2
- Method: fetchOrder()

fetchOrder() method returns, as a result:  
{"id": "5cab45ea054b46124e0761ea", "symbol": "ETH/USDT", "type": "market", "side": "buy", "amount": 0.11574, "price": 0.0, "cost": 0.0, "filled": 0.11574, "remaining": 0.0, "timestamp": 1554728426000, "datetime": "2019-04-08T13:00:26.000Z", "fee": {"currency": "USDT", "cost": 0.0203088978}, "status": "closed", "info": {"symbol": "ETH-USDT", "hidden": false, "opType": "DEAL", "fee": "0.0203088978", "channel": "API", "feeCurrency": "USDT", "type": "market", "isActive": false, "createdAt": 1554728426000, "visibleSize": "0", "price": "0", "iceberg": false, "stopTriggered": false, "funds": "0", "id": "5cab45ea054b46124e0761ea", "timeInForce": "GTC", "side": "buy", "dealSize": "0.11574", "cancelAfter": 0, "dealFunds": "20.3088978", "stp": "", "postOnly": false, "stopPrice": "0", "size": "0.11574", "stop": "", "cancelExist": false, "clientOid": "fa721e3b-2ffb-47b9-86b0-8e933fbdd3ce"}}

With ```"price": 0.0, "cost": 0.0```

**Comment by MarcelBeining** [comment]
This was a market order and for market orders the price and cost always returns zero because you could have filled different prices with your market order. Use fetchMyTrades to find the prices and costs for your executed market order and build the average of it.

**Comment by DmitryVil** [comment]
> This was a market order and for market orders the price and cost always returns zero because you could have filled different prices with your market order. Use fetchMyTrades to find the prices and costs for your executed market order and build the average of it.

I think you are wrong. Please look at the results of the same method for binance exchange:

{"info": {"symbol": "ETHUSDT", "orderId": 226599064, "clientOrderId": "16bfZiwAlehp8m4ioCyT0W", "price": "0.00000000", "origQty": "0.16667000", "executedQty": "0.16667000", "cummulativeQuoteQty": "29.62559250", "status": "FILLED", "timeInForce": "GTC", "type": "MARKET", "side": "BUY", "stopPrice": "0.00000000", "icebergQty": "0.00000000", "time": 1554764476631, "updateTime": 1554764476631, "isWorking": true}, "id": "226599064", "timestamp": 1554764476631, "datetime": "2019-04-08T23:01:16.631Z", "lastTradeTimestamp": null, "symbol": "ETH/USDT", "type": "market", "side": "buy", **"price": 177.74999999999997, "amount": 0.16667, "cost": 29.625592499999996**, "average": 177.74999999999997, "filled": 0.16667, "remaining": 0.0, "status": "closed", "fee": null, "trades": null}

**Comment by xpl** [comment]
Seems that for Binance we rebuild the price from the reported cost:

https://github.com/ccxt/ccxt/blob/master/js/binance.js#L741

```javascript
if (type === 'market') {
    if (price === 0.0) {
        if ((cost !== undefined) && (filled !== undefined)) {
            if ((cost > 0) && (filled > 0)) {
                price = cost / filled;
            }
        }
    }
}
```

@frosty00 What do you think, can we do the same for Kucoin? Seems that in the `info` there is a sufficient data to do that:

```
"dealSize": "0.11574", "cancelAfter": 0, "dealFunds": "20.3088978"
```

**Comment by xpl** [comment]
@DmitryVil The fix should be already there. Let us know if that doesn't help.

**Comment by DmitryVil** [comment]
Thank you very much, Vitaliy
