### ISSUE TITLE
kucoin withdraw raises  internal ccxt error

### ISSUE THREAD

**Issue by MarcelBeining** [ccxt/ccxt#4957]
- Programming Language version: Python 3.6
- CCXT version: 1.18.444
- Exchange: kucoin
- Method: withdraw

Since today I get that error roughly every second attempt:
```
client.withdraw(symbol,amountToSend,self.addresses[symbol]['binance']))

  File "/usr/local/lib/python3.7/site-packages/ccxt/kucoin.py", line 964, in withdraw
    responseData = response['data']
KeyError: 'data'

```

**Comment by kroitor** [comment]
@MarcelBeining can you please post your verbose request/response?

**Comment by MarcelBeining** [comment]
sorry for late response, but it seems you found the reason :-)
