### ISSUE TITLE
Vaultoro exchange stop work after ccxt upgrade

### ISSUE THREAD

**Issue by mostar** [ccxt/ccxt#4962]
OS:
Ubuntu 14.04

Programming Language version:
php -v

PHP 5.5.9-1ubuntu4.27 (cli) (built: Mar 5 2019 18:56:49)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

CCXT version:
Last

I'm using old version on ccxt 1.11.171. Upgrade ccxt break Vaultoro exchange on:

`ccxt\ExchangeError: vaultoro does not have market symbol BTC/GLD`

For example the output of the command in the last version of ccxt:

`php examples/php/cli.php vaultoro createLimitBuyOrder BTC/GLD 1 100`

give this error:

```
vaultoro->createLimitBuyOrder (BTC/GLD, 1, 100)
ccxt\ExchangeError: vaultoro does not have market symbol BTC/GLD
```

When moving back to the old ccxt version 1.11.171

`git branch -b fromoldcommite20b7fe668d14c4ff338d99dfba3d1d8422c9cbd e20b7fe668d14c4ff338d99dfba3d1d8422c9cbd
`
The same command give proper message from the exchange:

```
./keys.json
vaultoro->createLimitBuyOrder (BTC/GLD, 1, 100)
Exchange Error: vaultoro POST https://api.vaultoro.com/1/buy/gld/limit?nonce=1554824019&apikey=CEwxqNb3GzixcrhzrPkn47JkdsDpff6z&gld=1&price=1 401 {
  "status": "error",
  "data": {
    "message": "Authentication failed"
  }
}

```

**Comment by kroitor** [comment]
Does this work for you:

```PHP
<?php

date_default_timezone_set ('UTC');

$id = 'vaultoro';

// instantiate the exchange by id
$exchange = '\\ccxt\\' . $id;
$exchange = new $exchange (array(
    'enableRateLimit' => true,  // as required by the Manual
));

$exchange->load_markets(); // as required by the Manual

print_r ($exchange->market('BTC/GLD')); // does this work here?
print_r ($exchange->markets['BTC/GLD']); // or this? 

?>
```

**Comment by kroitor** [comment]
Oh, pardon, there was a unification change in Vaultoro GLD, because it conflicts with the GLD token.
The edit was here: https://github.com/ccxt/ccxt/pull/2602

So, GLD is now renamed to `Gold` with vaultoro.

I've uploaded another fix for it, because it currently shows the markets reversed. If you update to version 1.18.448 in 10 minutes – everything should work ok from there. And you will be able to access it again with:

```PHP
php examples/php/cli.php vaultoro createLimitBuyOrder BTC/Gold 1 100
```
