### ISSUE TITLE
[Kucoin] AuthenticationError: kucoin Invalid request ip

### ISSUE THREAD

**Issue by dimytr** [ccxt/ccxt#4969]
- OS: Windows 10
- Programming Language version: Python 3.6
- CCXT version: 1.18.416
- Exchange: Kucoin
- Method: fetch_total_balance

During a private method call I get an error.
'''HTTPError: 403 Client Error:  for url: https://openapi-v2.kucoin.com/api/v1/accounts?type=trade'''

**Comment by kroitor** [comment]
That endpoint requires the "General" permission. Do you have it set on that keypair?

**Comment by frosty00** [comment]
working on my end

**Comment by kroitor** [comment]
@frosty00 works on my side in py/js as well...

**Comment by kroitor** [comment]
> Invalid request ip

@dimytr Looks like you've tied your apiKey to a wrong IP address...

**Comment by kroitor** [comment]
@dimytr let us know if the above does not help... Feel free to reopen this or just ask further questions if any.

**Comment by dimytr** [comment]
Thanks for taking part in the solution of my problem. Strange but everything already works. I changed nothing. All as before.

**Comment by kroitor** [comment]
@dimytr it could also be a result of a temporary block, if you're don't stay below request rate limits: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit. Thx for reporting back anyways!
