### ISSUE TITLE
Cryptocurrency Market Index

### ISSUE THREAD

**Issue by aking7** [ccxt/ccxt#497]
This isn't exactly related to the ccxt code (have you thought about starting a Slack team?) but I thought you guys may be able to help. I'm looking for an API with access to some sort of cryptocurrency market index, similar to the S&P 500 for the stock market. Does anyone know of something like this?

I recently came across https://www.mvis-indices.com/indices/digital-assets, which is creating a variety of crypto index funds, but you need to create an account and then download the data as a text file. Perhaps it could still be incorporated into ccxt?

**Comment by kroitor** [comment]
> have you thought about starting a Slack team?

Welcome to our gitter chatroom: 

[![Gitter](https://badges.gitter.im/ccxt-dev/ccxt.svg)](https://gitter.im/ccxt-dev/ccxt?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

> I'm looking for an API with access to some sort of cryptocurrency market index, similar to the S&P 500 for the stock market. Does anyone know of something like this?

You may want to look at aggregators and those types of services:

- https://www.coinigy.com
- https://coinmarketcap.com
- https://www.cryptocompare.com

Practically every cryptotrading site has its own index, as well as most of exchanges do. Apart from that, I don't know of any globally-unified indexes on crypto assets (yet).

> Perhaps it could still be incorporated into ccxt?

Sorry, but we don't integrate aggregators anymore, most of them have a very different API structure than that of the majority of exchanges. I would close this for now, if you don't mind.

**Comment by aking7** [comment]
Ok thanks :)

**Comment by jjhesk** [comment]
@kroitor there is a wrong line form marketcap - https://github.com/ccxt/ccxt/blob/master/js/coinmarketcap.js#L29 please remove this line
