### ISSUE TITLE
itBit is missing some market pairs

### ISSUE THREAD

**Issue by markerdmann** [ccxt/ccxt#4970]
- OS: ubuntu 18
- Programming Language version: node 10
- CCXT version: 1.18.192
- Exchange: itbit
- Method: symbols()

This is what I'm seeing in ccxt:
```
> itbit.symbols
[ 'BTC/EUR', 'BTC/SGD', 'BTC/USD' ]
```

It's missing some market pairs. For example, this API URL fetches ticker data for the ETHUSD market pair:

https://api.itbit.com/v1/markets/ETHUSD/ticker

**Comment by kroitor** [comment]
@markerdmann thx for reporting! They're missing not just the markets, but the entire API endpoint to serve the list of their markets, that's the root of the problem in the first place – when they add new pairs there's no other option to automatically react to that via the API apart from scraping the list of markets from their webpage... I've added the missing ETH pairs, so, if you update to version 1.18.458 (it will be available in 5-10 minutes), those pairs will be available. Let us know if anything. Thx again!

**Comment by markerdmann** [comment]
@kroitor Thanks for the quick update!
