### ISSUE TITLE
Kraken advanced orders

### ISSUE THREAD

**Issue by iuvbio** [ccxt/ccxt#4972]
- OS: Linux
- Programming Language version: Python 3.7.2
- CCXT version: 1.18.456
- Exchange: Kraken
- Method: create_order

I'm trying to create a stoploss limit order, but I get the following error: `ExchangeError: kraken {"error":["EGeneral:Invalid arguments:ordertype"]}`

This is my setup:
```python
pair = "BTC/EUR"
ordertype = "stop-loss-limit"
amount = 0.005
price = 4000
price2 = 0.99 * 4000
params = {"trading_agreement": "agree", "validate": True, "price2": price2}

krk.create_order(pair, ordertype, "sell", amount, price, params=params)
```

Market and limit orders work fine, just like "normal" `stop-loss` orders. Any idea why this could be? Other types, like `stop-loss-profit`, throw the same error. Seems any order type that has more than one hyphen.

**Comment by kroitor** [comment]
Can you please show your verbose request/response? https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

```Python
pair = "BTC/EUR"
ordertype = "stop-loss-limit"
amount = 0.005
price = 4000
price2 = 0.99 * 4000
params = {"trading_agreement": "agree", "validate": True, "price2": price2}

krk.load_markets()  # ←---------- add this
krk.verbose = True  # ←---------- add this

krk.create_order(pair, ordertype, "sell", amount, price, params=params)

**Comment by iuvbio** [comment]
Thanks for getting back to me kroitor.

Here's the verbose output:
```bash
Request: POST https://api.kraken.com/0/private/AddOrder {'API-Key': 'xxx', 'API-Sign': 'xxx', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.21.0', 'Accept-Encoding': 'gzip, deflate'} nonce=1555021703467&pair=XXBTZEUR&type=sell&ordertype=stop-loss-limit&volume=0.005&price=4000&trading_agreement=agree&validate=True&price2=3960.0

Response: POST https://api.kraken.com/0/private/AddOrder 200 {'Date': 'Thu, 11 Apr 2019 22:28:23 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=xxx; expires=Fri, 10-Apr-20 22:28:23 GMT; path=/; domain=.kraken.com; HttpOnly', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '4c6064ace9ae9c7d-AMS'} {"error":["EGeneral:Invalid arguments:ordertype"]}
```

**Comment by kroitor** [comment]
> `nonce=1555021703467&pair=XXBTZEUR&type=sell&ordertype=stop-loss-limit&volume=0.005&price=4000&trading_agreement=agree&validate=True&price2=3960.0`

> `{"error":["EGeneral:Invalid arguments:ordertype"]}`

This is very interesting, indeed. It complains about the ordertype despite that it is documented ) 

However, I think, here's the timeline of the story:

- Aug 2017: https://blog.kraken.com/post/1234/announcement-delisting-pairs-and-temporary-suspension-of-advanced-order-types/

- Feb 2018: https://blog.kraken.com/post/1494/kraken-enables-advanced-orders-and-adds-10-currency-pairs/

So, despite that it is in the docs, I think it may be unavailable right now. Have you tried reaching out to Kraken tech support on this matter?

**Comment by iuvbio** [comment]
Damn, seems like you're right. I was only going off the Kraken docs, assuming they were correct..

> Have you tried reaching out to Kraken tech support on this matter?

Will do that..

**Comment by kroitor** [comment]
@iuvbio ok, i'd close this for now, if you don't mind, feel free to reopen it if needed, or just ask further questions if any. We'll be happy if you followup with your findings here )
