### ISSUE TITLE
Getting order history issue for bittrex, bitsane, okex,yobit

### ISSUE THREAD

**Issue by baotaizhang** [ccxt/ccxt#4973]
Now i am building a python script for auto trading bot between bittrex, bitsane, okex, yobit by using ccxt.
By the way, I faced the following problems.
I am trying to get order history from yobit, okex, bitsane and bittrex with ccxt.
I have used fetchClosedOrders (), fetchOpenOrders (), and fetch_orders () functions, but I am receiving unsupported  error message.
So I looked at the api documentation for each site.
Each site definitely provides order history data with  REST api format.
However, if I use the CCXT module, I  need to use each function for each site, and there is no solution to uniformly fetch order history data like ticker() function.
Is there any solution?

**Comment by kroitor** [comment]
> Is there any solution?

Yes, just update to the most recent version of CCXT and use the exchange metadata as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

Let us know if that doesn't answer your question.

I'd recommend to read the entire Manual from top to bottom to help save your time. If you have any difficulties, feel free to ask, however, make sure to follow these guidelines very precisely: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
