### ISSUE TITLE
issue with gateio min order size.

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#4977]
The mi order size for AT/USDT is...

```
"AE/USDT": {
      "limits": {
        "amount": {
          "min": 0.0001
        },
        "price": {
          "min": 0.0001
        },
        "cost": {
          "min": 1
        }
      },
```

When placing a small test order for 1 AE i get this error:
 
`{"result":"false","message":"Your order size is too small. The minimum is 1 USDT","code":20}`

The `marketinfo` api call shows this:

`{"ae_usdt":{"decimal_places":4,"min_amount":0.0001,"min_amount_a":0.0001,"min_amount_b":1,"fee":0.2,"trade_disabled":0}}`

... looks like `min_amount_b` gives the right value in this case.

https://www.gate.io/api2/public/marketinfo

**Comment by xpl** [comment]
@npomfret `min_amount_b` is the minimal order _cost_, which is 1 USDT, which is what their error message tells about (`The minimum is 1 USDT`).

It looks like that we have the correct value in the market info:

```
"cost": {
    "min": 1
}
```

> When placing a small test order for 1 AE i get this error:

Try placing an order that is 1 USDT in cost, not 1 AE. For example, if the current AE/USDT price is $0.5, then it should be at least 2 AE (2*0.5 = 1).

**Comment by kroitor** [comment]
Yeah, exchanges often call the total cost you *"order size"*. So this is a warning about min cost. We should handle this as described in the Manual here: https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

@npomfret let us know if that doesn't help.

**Comment by npomfret** [comment]
I thought in limits the `cost.min` was simply the minimum order size expressed in the quote currency, and the `amount.min` was the same but in the base currency.

Am I right in thinking that it's not as simple as this and we are required to do per-exchange logic to figure out what a min order size is?  Some exchanges may express the min always in base, or always in quote, some may specify it based on if it's a buy v's sell order?

**Comment by kroitor** [comment]
> I thought in limits the cost.min was simply the minimum order size expressed in the quote currency, and the amount.min was the same but in the base currency.

This is how it's meant to work. So, the above is correct.

> Am I right in thinking that it's not as simple as this and we are required to do per-exchange logic to figure out what a min order size is?

No, the min limits should reflect the truth, if the exchange in question provides them via API. So, it should be that simple – `cost.min` is the minimum order cost in quote currency.

**Comment by npomfret** [comment]
> "Min in base" is limits.min.amount. "Min in quote" is limits.min.cost.

Do you mean `limits.amount.min` and `limits.cost.min`?...

```
"AE/USDT": {
      "limits": {
        "amount": {
          "min": 0.0001
        },
        "price": {
          "min": 0.0001
        },
        "cost": {
          "min": 1
        }
      },
```

**Comment by npomfret** [comment]
Sorry if I'm being stupid, but I can't quite get this correct.  I tried placing a small sell order (for 1 AE/USDT) on gateio (and got the same error _Your order size is too small. The minimum is 1 USDT_).  Now the min order `amount` is 0.0001, so my 1AE should be well over this limit.  

It looks to me like the cost is the only limit that  I should be taking into account on this exchange.

Perhaps when calculating the min order size we should take into account both the amount AND the cost, making sure our order satisfies both requirements if they are present.

So when making a order, the min order size must satisfy...

 * `amount * price` must be > `limits.cost.min`
 * `amount` must be >`limits.amount.min`

**Comment by kroitor** [comment]
> It looks to me like the cost is the only limit that I should be taking into account on this exchange.

This is not a complete picture ) You should always account for **ALL** limits with **ANY** exchange. So you should make sure that both all values are within limits: amount is within limits.min.amount and cost within limits.min.cost.

> Perhaps when calculating the min order size we should take into account both the amount AND the cost, making sure our order satisfies both requirements if they are present.

That's right. Always account for all limits.

> So when making a order, the min order size must satisfy...
> - amount * price must be > limits.cost.min
> - amount must be >limits.amount.min

That's correct and you also have to account for limits.min.price as well! And that is all documented in the Manual here: https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

Does that answer your question?

**Comment by npomfret** [comment]
Yes, thank you again.
