### ISSUE TITLE
Bitmex fetch ticker not working / noob question / js

### ISSUE THREAD

**Issue by smallio** [ccxt/ccxt#4979]
Language - JS

Hi guys,

Quite new to this so sorry for the nooby question!

I simply want to fetch prices of things & console log them out for a little bit of practice. Not sure what to put in params or if I even need to but I'm getting these errors:

<img width="493" alt="Screen Shot 2019-04-12 at 15 04 12" src="https://user-images.githubusercontent.com/32819971/56043010-42170c00-5d34-11e9-8187-448c7eb04c59.png">

Again sorry, this is so obvious but I'm not quite understanding.
Thx :)

```
'use strict';

const ccxt = require ('ccxt');

(async function () {
    let bitmex = new ccxt.bitmex ({
        "enableRateLimit": true,
        'apiKey': 'xxxxxxxxxxxx',
        'secret': 'yyyyyyyyyyyy',
        'proxy': 'https://cors-anywhere.herokuapp.com/',
    });

    console.log( await bitmex.fetchTicker("XBT/USD"));
    console.log(bitmex.fetchTickers(['XBT/USD', 'ETH/USD']));

}) ();
```

**Comment by kroitor** [comment]
Hi! 

First, a question to you: are you trying to launch it in a browser or in Node.js ? 

If this is your JavaScript code that you want to run in a browser, then, i'm afraid, it won't work with BitMEX and this is a BitMEX-specific issue. They do not allow proxied CORS requests via public proxies.

If you're working from a browser, then you could try any other exchange instead of BitMEX to check if that is the case:

```JavaScript
'use strict';

const ccxt = require ('ccxt');

(async function () {
    let bitmex = new ccxt.gdax ({
        "enableRateLimit": true,
        'proxy': 'https://cors-anywhere.herokuapp.com/',
    });

    console.log( await bitmex.fetchTicker("XBT/USD"));
}) ();
```

 ↑ This should work, for example. Alternatively, you can run it with BitMEX in Node.js with no issues, or, if you still want to use BitMEX from a browser, you could run your own CORS-proxy as described in the Install doc here: https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin

The second issue in your code is that you're not awaiting the second call to `fetchTickers`, should be:

```JavaScript
// before
    console.log(bitmex.fetchTickers(['XBT/USD', 'ETH/USD']));

// after
    console.log(await bitmex.fetchTickers(['XBT/USD', 'ETH/USD']));
```

Duplicates: 

- https://github.com/ccxt/ccxt/issues/4093
- https://github.com/ccxt/ccxt/issues/3875
- https://github.com/ccxt/ccxt/issues/2052
- https://github.com/ccxt/ccxt/issues/955
- https://github.com/ccxt/ccxt/search?q=bitmex+cors&type=Issues

Let us know if the above doesn't answer your questions. Feel free to reopen this if needed or just ask further questions, if any.

**Comment by smallio** [comment]
@kroitor Wow thank you for the lightning fast response. 

Thank you so much for the help. Yup running in the browser, I thought this might be able to get around the pesky bitmex UI but I guess I have to go the node.js route! 

Do you know of or have included in the documentation any working examples of node.js with ccxt? It would be cool to see some working examples before I delve in the deep end!

Once again thank you :)

**Comment by kroitor** [comment]
> Do you know of or have included in the documentation any working examples of node.js with ccxt?

Sure, just check this out: 

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/tree/master/examples

Here's your code that will work in Node.js:

```JavaScript
'use strict';

const ccxt = require ('ccxt');

(async function () {
    let bitmex = new ccxt.bitmex ({ enableRateLimit: true });
    console.log( await bitmex.fetchTicker('XBT/USD'));
}) ();
```

↑ Same as the browser, but without having to define the proxy... If you want more on Node.js in general, get started here: https://nodejs.org/es/docs/guides/getting-started-guide/

**Comment by smallio** [comment]
@kroitor Fabulous. You are one helpful person, that's for sure!

I've been reading through the wiki & finding it very helpful.

So last question running my own CORS proxy I can do with just  a webpack/npm setup & then the server will technically be through node.js I can still use it in the browser? 

Planning on making this a long project to understand crypto APIs & eventually use. I'm a huge bitmex user & so that's really the key for me. I'd like stay as front end as possible in the project so I don't get out of my depth with tons of websocket connections etc.

Would you say making my own proxy as described in the guide is good way forward? I'm just wondering if it's slightly makeshift & will cause problems later. If so I'll grit my teeth & do it the other way.

**Comment by kroitor** [comment]
> So last question running my own CORS proxy I can do with just a webpack/npm setup & then the server will technically be through node.js I can still use it in the browser?

Yep, exactly! This is how it is expected to work - your browser requests will go through your local node.js. There may still be bugs with some exchange-specifics, but now you know how to check against that – just try a different exchange name to see if it makes a difference.

> Would you say making my own proxy as described in the guide is good way forward? I'm just wondering if it's slightly makeshift & will cause problems later. If so I'll grit my teeth & do it the other way.

Developers will only want to send exchange-requests from the browser if they don't have an option to run a full-scale Node.js setup (for example, not owning the website or for similar reasons). For a long-term project, I would suggest to not try sending requests from the browser. Instead, the classic architecture would be to have your javascript split into two:

1. server-side – this will run in your Node.js and will make an exchange instance and will send and receive exchange input-output over http via ccxt. And it will serve the html-pages for the client-side.

2. client-side – is just the html with the interface that you want, as soon as you click the button, your interface should trigger your server-side to send the request and propagate the response back to the user... 

↑ once you have the basics working – you go a step further and automate series of requests and entire strategies on the serverside with the ordering of requests and rate-limits in mind, as described in the Manual.. you then use the client-side to control what your serverside is doing with the exchange.

**Comment by smallio** [comment]
@kroitor 

Thank you endlessly for the kind & detailed responses. This is why the coding community is so incredible. Can't wait to get good with ccxt & for what it's worth (from a noob) the code is awesome & clean.

I'll give all of that a shot & read the whole manual, although I may be back once or twice to ask a question or two. ;)

Have a great weekend man!

**Comment by kroitor** [comment]
> I'll give all of that a shot & read the whole manual, although I may be back once or twice to ask a question or two. ;)

Feel free to ask if anything, however, if you want a precise and quick answer, i suggest that you don't post screenshots of text in the future ) It's hard to work with text on images, can't copy it and it doesn't get indexed by search engines, so other people won't find this issue if they search for a similar thing. 

So, when asking a question, make sure to follow these guides as precisely as you possible can as if your life depends on how precise you are ))) 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Following those guides will help you get the right answer quickly.

We will usually ask for code and verbose request/response in the first place. Also, use the search – many of starting questions have already been answered there. This project is currently a work in progress, there may still be bugs around...

Apart from the above, don't hesitate to ask if you have any difficulties )

**Comment by smallio** [comment]
@kroitor Awesome I'll treat that like a bible 👍 

One more question to get me started, if that's ok? What's the best way to display what the ticker has fetched to the html updating constantly?

I was thinking something like this, but no cigar as of yet:

```
    gdax.addEventListener('message', (message) => {
        let msg = JSON.parse(message.data)
        msg.data.forEach(e => {
            console.log(e.last_price)
            btcPrice.textContent = e.last_price
        })
    });
```
Any idea why that does not work?

**Comment by kroitor** [comment]
> Any idea why that does not work?

Depends which environment you're using...

If it's a web browser, then see this example:

- https://github.com/ccxt/ccxt/blob/master/examples/html/basic-poller.html

If it is Node.js, then see *"polling"* examples here:

- https://github.com/ccxt/ccxt/blob/master/examples/js

If it's a React environment in a browser, then see this example:

- https://codesandbox.io/s/zknjq18w13

Hope that answer the question )

**Comment by boppleton** [comment]
@smallio for a local CORS proxy you can have this saved to a file in your project:

`let port = (process.argv.length > 2) ? parseInt (process.argv[2]) : 8080; // default`
`require ('cors-anywhere').createServer ().listen (port, 'localhost')`

run with `node cors.js` and then your proxy is `http://localhost:8080/`
