### ISSUE TITLE
timestamp issue on 32 bit systems

### ISSUE THREAD

**Issue by babjak** [ccxt/ccxt#4982]
- OS: Linux Debian 4.9.0-8-686-pae #1 SMP Debian 4.9.144-3.1 (2019-02-19) i686 GNU/Linux
- Programming Language version: Python 2.7.13
- CCXT version: 1.18.466
- Exchange: NA
- Method: iso8601

On 32 bit systems the timestamp in milliseconds is NOT an int but a long, so I propose the following modification in base/exchange.py line 835. Instead of:
```
if not isinstance(timestamp, int):
    return None
```

The code should read:
```
if not isinstance(timestamp, (int, long)):
    return None
```

I've not looked for it, but type checking done the original way may be an issue at other places in the code as well.

**Comment by kroitor** [comment]
>  I propose the following modification in base/exchange.py line 835

Your contributions are welcome! https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
