### ISSUE TITLE
Russian ruble can be both 'RUB' and 'rur' on Yobit.

### ISSUE THREAD

**Issue by dmitriano** [ccxt/ccxt#4983]
- OS: ubuntu 16.04
- Programming Language version: nodejs v8.12.0
- CCXT version: ccxt@1.18.395
- Exchange: yobit
- Method: exchange.markets

exchange.markets contains this:

BTC/RUB  ->  btc / rur

where BTC/RUB is the key, 'btc' is exchange.markets['BTC/RUB'].baseId and 'rur' is exchange.markets['BTC/RUB'].quoteId.

Is this a normal behaviour?

Why the key is 'RUB' but quoteId is 'rur'?

**Comment by kroitor** [comment]
> Is this a normal behaviour?

Yes:

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

> Why the key is 'RUB' but quoteId is 'rur'?

Because of symbol unification as explained in the Manual.

Let us know if that doesn't answer the question.
