### ISSUE TITLE
Download JS browser CCXT with only selected exchanges

### ISSUE THREAD

**Issue by enriquepiatti** [ccxt/ccxt#4986]
This is more a feature request than an issue.
Is possible to download CCXT for JS browser with only some selected exchanges? not the full list which is huge and maybe we need only two or three?

**Comment by frosty00** [comment]
If you've ever downloaded an image or watched a video online then you probably have enough bandwidth / space on your computer.

https://arve0.github.io/npm-download-size/#ccxt

**Comment by kroitor** [comment]
Hi @enriquepiatti !

> Is possible to download CCXT for JS browser with only some selected exchanges? not the full list which is huge and maybe we need only two or three?

We don't serve custom builds yet, but you can make your own custom build with just the exchanges you need:

- https://github.com/ccxt/ccxt/blob/master/exchanges.cfg
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#what-you-need-to-have

We will create an online configuration tool for that same purpose as soon as we can.

**Comment by shuxiuhuayuan** [comment]
Download JS browser CCXT with only selected exchanges

**Comment by ttodua** [comment]
TS & ESM update for CCXT probably solved this issue, as users can easier import only desired module.
