### ISSUE TITLE
Precision error in coinbasepro

### ISSUE THREAD

**Issue by azharuniverse** [ccxt/ccxt#4991]
Order Description:
LIMIT BUY, VOLUME=41.68273866, PRICE=0.00006222,
ERROR =

>  coinbasepro size is too accurate. Smallest unit is 1.00000000

Order gets successfully placed if I use only VOLUME=41
This issue is present with other pairs also.

Coinbasepro product description API returns this

```
{
id: "XRP-BTC",
base_currency: "XRP",
quote_currency: "BTC",
quote_increment: "0.00000001",
display_name: "XRP/BTC",
}
```

`And markets[XRP/BTC].precision.volume = 8 `

But placing an order with that precision causes error
 

- OS: WINDOWS 10
- Programming Language version: JS
- CCXT version: "^1.18.425",
- Exchange: COINBASEPRO
- Method: amountToPrecision()

**Comment by azharuniverse** [comment]
Above commit(https://github.com/ccxt/ccxt/commit/54a8c6f301d7879623da1a7565a6622f30ac8dc3) is certainly not a solution of this problem. 

I was already using both the precisionFunctions before placing the order.

and even after using amountToPrecision() it doesn't solve the issue.

I just took this latest pull and verified that its still not working.

**Comment by kroitor** [comment]
@azharuniverse can you please post your verbose request/response for the order in question?

**Comment by kroitor** [comment]
@azharuniverse nevermind, I've reproduced it: 

```
coinbasepro.createOrder (XRP/BTC, limit, buy, 41.68273866, 0.00006222)
fetch:
 coinbasepro POST https://api.pro.coinbase.com/orders
Request:
 { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36',
  'CB-ACCESS-KEY': '434c3987143b80a02bbe0fd580b9a309',
  'CB-ACCESS-SIGN': 'ySrnIUkwIrEDTQqYjJ/soUTvS7Q/ml7c7dyPbxE6HB4=',
  'CB-ACCESS-TIMESTAMP': '1555498871',
  'CB-ACCESS-PASSPHRASE': '4xh7mokamyq',
  'Content-Type': 'application/json' }
 {"product_id":"XRP-BTC","side":"buy","size":"41.68273866","type":"limit","price":"0.00006222"}

handleRestResponse:
 coinbasepro POST https://api.pro.coinbase.com/orders 400 Bad Request
Response:
 { Date: 'Wed, 17 Apr 2019 11:01:12 GMT',
  'Content-Type': 'application/json; charset=utf-8',
  'Content-Length': '63',
  Connection: 'close',
  'Set-Cookie': '__cfduid=dce652eafc4faab250549b8f38e4749721555498871; expires=Thu, 16-Apr-20 11:01:11 GMT; path=/; domain=.pro.coinbase.com; HttpOnly',
  'Access-Control-Allow-Headers': 'Content-Type, Accept, cb-session, cb-fp',
  'Access-Control-Allow-Methods': 'GET,POST,DELETE,PUT',
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Expose-Headers': 'cb-before, cb-after, cb-gdpr',
  'Access-Control-Max-Age': '7200',
  'Cache-Control': 'no-store',
  Etag: 'W/"3f-b0zrjznf83LAexMYYfKMIIBM1p4"',
  'Strict-Transport-Security': 'max-age=15552000; includeSubDomains',
  'X-Content-Type-Options': 'nosniff',
  'X-Dns-Prefetch-Control': 'off',
  'X-Download-Options': 'noopen',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Xss-Protection': '1; mode=block',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Cf-Ray': '4c8de64bf966cada-ARN' }
 {"message":"size is too accurate. Smallest unit is 1.00000000"}

ExchangeError coinbasepro size is too accurate. Smallest unit is 1.00000000
```

**Comment by kroitor** [comment]
@azharuniverse 

https://docs.pro.coinbase.com/#products

> The `base_min_size` and `base_max_size` fields define the min and max order size. The `quote_increment` field specifies the min order price as well as the price increment.

↑ Nothing about `base_increment` here, so we can't guess the amount precision before actually getting the error message from them. What would you suggest to resolve this? 

To be clear from their docs it follows that `base_min_size` has nothing to do with precision, but it is about min limit on the volume of the order, so, it won't work if derive it from `base_min_size` for other currencies.

**Comment by azharuniverse** [comment]
I can't see any accurate solution to this. Its third iteration of coinbase after gdax. they should have done better job.

For now I think I will go forward with `base_min_size` precision. I will lose a small amount in each trade like < $0.2 (evaluated from several tests on random coins. not all cases) . 
But at least orders will go through successfully.

**Comment by kroitor** [comment]
@azharuniverse ok, at this point i don't see a reasonable solution either, so, closing this for now, let us know if anything, feel free to reopen it if needed.

**Comment by azharuniverse** [comment]
Since its not possible to use coinbasepro without fixing this so I am pasting a dirty hack if someone wish to go ahead anyhow.

```
function adjustVolumePrecision(userExchange, order) {
    let order_volume = order.order_volume;
    try {
        console.log('order_volume before format - ', order_volume);
        if(userExchange.id === 'coinbasepro') {
            const minAmount = userExchange.markets[formatPair(order.coin)].limits.amount.min;
            const precision = (minAmount + '.').split('.')[1].length;
            return userExchange.truncate(order.order_volume, precision);
        }
        order_volume = userExchange.amountToPrecision(formatPair(order.coin), order_volume);
        console.log('order_volume after format - ', order_volume);
    }catch (err) {
        console.log(err);
    }
    return order_volume;
}
```

Here userExchange is the context of ccxt  
`let userExchange = new ccxt[context.id](ccxtOptions);`

Use it like this before placing an order
`formatedOrderParams = adjustVolumePrecision(userExchange, orderParams)`


**Warning:** This function truncates precision which may be supported by that pair. Good thing is its not loosing much precision atleast in my test. some samples.

> BCH: 0.04248086 -> 0.04
> XRP: 40.62279564 -> 40 
> ETC: 2.11259071 -> 2.1

**Comment by acreux** [comment]
it seems that they now provide `base_increment` information (tested) for every market:
```
{
            "id": "BTC-USD",
            "base_currency": "BTC",
            "quote_currency": "USD",
            "base_min_size": "0.001",
            "base_max_size": "70",
            "base_increment": "0.00000001",
            "quote_increment": "0.01",
            "display_name": "BTC/USD",
            "status": "online",
            "status_message": null,
            "min_market_funds": "10",
            "max_market_funds": "1000000",
            "post_only": false,
            "limit_only": false,
            "cancel_only": false
        }
```
An example in the [status channel section](https://docs.pro.coinbase.com/?r=1#the-status-channel) says so,
but not officially in the [Products section](https://docs.pro.coinbase.com/?r=1#products)

**Comment by kroitor** [comment]
@acreux thx for reporting! Will add to the parser shortly!
