### ISSUE TITLE
DSX does not throw InvalidNonce when it should

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#4995]
Instead I see an `ExchangeError` with `{"success":0,"error":"Parameter: nonce is invalid"}`

**Comment by kroitor** [comment]
This exchange doesn't have a properly implemented `handleErrors` with `exact` and `strict` matching, it is considered broken since they changed their API to v2. Let me know if you're willing to fix it.

**Comment by npomfret** [comment]
Ok, I will take a look.

**Comment by kroitor** [comment]
@npomfret thx! see `liqui` or `bitfinex` for reference.
