### ISSUE TITLE
poloniex fetchMyTrades id – globalTradeID vs tradeID

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#4999]
https://docs.poloniex.com/#returntradehistory-private

Looks like poloniex trades inexplicably have 2 ids:

> globalTradeID - The globally unique identifier of this trade. 
> tradeID - The identifier of this trade unique only within this trading pair.

ccxt uses `tradeID`.  I'm wondering what the reason was to choose this one over the globally unique one.

**Comment by kroitor** [comment]
> I'm wondering what the reason was to choose this one over the globally unique one.

The `globalTradeID` was missing in the old docs when it was implemented initially. We can most likely switch to `globalTradeID`, if we are sure that it works seamlessly across pairs and different timeranges. If you could help investigate that – we'll be very thankful.

**Comment by npomfret** [comment]
There's no way to _interact_ with the exchange using the trade id as far as I can see.  So I don't see any reason that switching could cause a problem.

As a use of ccxt, having a unique trade id (within an exchange) is very useful.

**Comment by kroitor** [comment]
@npomfret the only thing is that we might break the old history, if we just substitute one for another, so, maybe, we should make this an option, defaulting to the old behaviour? Lmk what you think.

**Comment by npomfret** [comment]
Personally I wouldn't bother.  Or if you did then the default would be the new way.

I appreciate this is _kind of_ a breaking change, and if people have their own records of exchange ids they might see double the number of trades.

However, I always think with APIs that the number of people affected in the future will be great than the number of people affected in the past.  What I mean by that is more and more people will be using ccxt going forward, and if we don't give them the new _more correct_ trade ids for Poloniex then we are impacting them in favour of keeping a smaller number of people happy who have already downloaded their trade history.

This particular change is addressable for those people because the exchange allows you to re-download your entire history in (pages of size 10000).  

Do you have a way to publicise _breaking changes_ like this?

**Comment by kroitor** [comment]
> Do you have a way to publicise breaking changes like this?

Yep, we have `announcements` for that.

**Comment by kroitor** [comment]
This has been changed in 1.18.490 – CCXT will now default to `globalTradeID`.

**Comment by npomfret** [comment]
@kroitor 

Annoyingly, the trade-id in the polonium websocket feed uses the tradeId, not the globalTradeId.

**Comment by kroitor** [comment]
@npomfret thx, will get to fixing it shortly.

**Comment by npomfret** [comment]
I'm not sure a fix is the right thing to do...

**Comment by kroitor** [comment]
@npomfret yeah, currently it only serves the trade id and no globalTradeId.
