### ISSUE TITLE
loadTradingLimits() results lost after loadMarkets(true)

### ISSUE THREAD

**Issue by Pmant** [ccxt/ccxt#5005]
- OS: Windows/Linux
- Programming Language version: node.js 10
- CCXT version: latest
- Exchange: all / huobipro
- Method: loadTradingLimits

After using loadMarkets(true) all trading limits that were fetched by loadTradingLimits() are lost until you call loadTradingLimits(symbols, **true**) to force update them again. I think it would be better to cache the results of loadTradingLimits() after first execution and reapply them on loadMarkets() calls.

**Comment by kroitor** [comment]
Totally agree with you! I'm working on the architecture for loaded and hardcoded fees, limits and all that, need to resolve a few differences across exchanges, hope to come with a proposal on this soon.

**Comment by ttodua** [comment]
in loadMarkets we fill trading limits, and will probably soon deprecate the separate `loadTradingLimits` method, so i'll close this issue
