### ISSUE TITLE
OKex market not found

### ISSUE THREAD

**Issue by joshuaeitan** [ccxt/ccxt#5008]
- OS: AWS Linux
- Programming Language version: Python 3.7.1
- CCXT version: whatever pip installs by default
- Exchange: OKex
- Method: Ticker/Orderbook

When I attempt to load the AE/ETH or AE/BTC ticker or orderbook from OKex through CCXT on my AWS instance I get the error message that the market does not exist. However, when I load the ticker manually using requests on the AWS instance, or using CCXT on my personal computer, it loads fine. Anyone have an idea why this is happening and/or how I can fix it? It's not a big deal that just AE doesn't load, but I'm worried it might affect other markets as well. 
![image](https://user-images.githubusercontent.com/14827856/56436985-cb39c000-62ab-11e9-8369-03e3218732b2.png)

**Comment by kroitor** [comment]
@joshuaeitan just use `AET`, see this issue by @npomfret : https://github.com/ccxt/ccxt/issues/4981

**Comment by joshuaeitan** [comment]
Oh ok, thanks for the quick reply. Appreciate all of your hard work!

**Comment by npomfret** [comment]
@joshuaeitan we spotted a symbol mapping error, the token and the mainnet currency were both using AE so we changed okex to AET
