### ISSUE TITLE
How  can I get the information about the swap contract(perpetual contract)

### ISSUE THREAD

**Issue by 47898077** [ccxt/ccxt#5012]
OS: Ubuntu 18.10
Programming Language version: Python 3.7
CCXT version: Last
Exchange: Okex
Method: private_post_positions() and filter_by(positions, 'symbol', currency)
Could you please tell me how  I can get the information about the swap contract(perpetual contract) with ccxt?
In addition，is it possible to further optimize the symbol format？
Because every time I get information about futures with code like:
exchange.fetchTrades(' BTC / USD '，{ ' contract_type '： ' this_week ' })
It's more convenient with code like
exchange.fetchTrades(' BTC / USD_CW ')
CW means current week (just a simple example ：D)
I look forward to your reply.

**Comment by kroitor** [comment]
Hi, this is in progress, here: https://github.com/ccxt/ccxt/pull/4636 ← you can clone this PR and help test it, we'd be happy for all help. Let us know if that doesn't answer the question.
