### ISSUE TITLE
Fetch orderID

### ISSUE THREAD

**Issue by tezeug** [ccxt/ccxt#5013]
OS Kubuntu 19.04
Python3.7
CCXT 1.18.482

Hello.
How can I fetch an order ID of an submitted order (to work with the order later)?
Something like:

order1 = binance.create_order(...)
ord1id = order1.fetch_orderID

**Comment by kroitor** [comment]
Hi!

The order `id` is contained inside the structure returned by the `create_order` method.

```Python
 #↓  the id is is returned in this structure
order1 = binance.create_order(...)
 #↑  the id is is returned in this structure

# see the contents of that structure:
print(order1)

# your order id:
print(order1['id'])

# ...
```

Please read the Manual in order to understand how to work with this lib efficiently: https://github.com/ccxt/ccxt/wiki/Manual

Hope that answers your question.

**Comment by tezeug** [comment]
Thank you a lot, it helped.
