### ISSUE TITLE
Fetch an order status

### ISSUE THREAD

**Issue by tezeug** [ccxt/ccxt#5015]
- OS: Kubuntu 19.04
- Programming Language version: Python3.7
- CCXT version: 1.18.482
- Exchange: BitMEX
- Method: unknown

Hello.
How can I fetch the order status by the order ID?
Something like:

if(BitMEX.fetch_order_status(id = orderid) == 'filled'):
   ...

I've found only parse_order_status inside and do not understand this. Thanks.

**Comment by kroitor** [comment]
Hi!

> How can I fetch the order status by the order ID?

You can do it like so:

```Python
#                   put your order id here ↓
if exchange.fetch_order_status(id=your_order_id) == 'filled':
    # your code for this status here...
```

Also, please, read this: https://github.com/ccxt/ccxt/wiki/Manual#querying-orders

And check the examples here: 

- https://github.com/ccxt/ccxt/tree/master/examples
- https://github.com/ccxt/ccxt/tree/master/examples/py

Let us know if that doesn't answer your question.

**Comment by tezeug** [comment]
Fixed. + I have to and definitely will check the readMe and the documentation further too. Thanks.
