### ISSUE TITLE
Kucoin async cancel_order() not working

### ISSUE THREAD

**Issue by slix88** [ccxt/ccxt#5016]
- OS: Windows 10 (Using PyCharm IDE)
- Programming Language version: Python 3.6
- CCXT version: 1.18.484
- Exchange: KuCoin
- Method: async def cancel_order()

Hi

The asynchronous function for Kucoin's cancel order (async def cancel_order) is returning me the following error: "RuntimeWarning: coroutine 'Exchange.fetch2' was never awaited"

I'm running the following code:

    async def test():
        symbol = 'NANO/BTC'
        direction = 'buy'
        qty = 1
        price = 0.00001068

        kucoin_order = await kucoin.create_order(symbol, 'limit', direction, qty, price)
        last_order_ID_kucoin = kucoin_order['id']
        await kucoin.cancel_order(last_order_ID_kucoin, symbol)

    if __name__ ==  '__main__':
        loop = asyncio.get_event_loop()
        loop.run_until_complete(test())

**Comment by kroitor** [comment]
Hi!

>  is returning me the following error: "RuntimeWarning: coroutine 'Exchange.fetch2' was never awaited"

Can you paste the full error stack, plz?

**Comment by slix88** [comment]
Hi @kroitor 

I have included the full error below. Please note that I am able to successfully run the cancel method for Binance without errors (except for the unclosed client session errors which shouldn't be a problem)

Thanks

`C:/scratch_46.py:74: RuntimeWarning: coroutine 'Exchange.fetch2' was never awaited
  await kucoin.cancel_order(last_order_ID_kucoin, symbol)
binance requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add exchange.close() to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000018AC31F24E0>
kucoin requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add exchange.close() to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000018AC320A128>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000018AC31E7D68>, 195522.218)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000018AC320A2B0>`

**Comment by kroitor** [comment]
@slix88 ok, I've added a fix for this, so, if you update your ccxt version to 1.18.485+ it should work from there, let us know if not. The new build will arrive in 5-10 minutes. Thx for reporting!
