### ISSUE TITLE
hitbtc - fetch_open_orders does not filter market correctly

### ISSUE THREAD

**Issue by carels** [ccxt/ccxt#5018]
In PHP version (current build as on 2019-04-22):

Exchange: hitbtc

Calling fetch_open_orders results are not filtered by market correctly, e.g.

$hitbtc->fetch_open_orders('KBC/BTC'), results in:

Array
  | (
  | [0] => Array
  | (
  | [id] => ******************
  | [info] => Array
  | (
  | [orderId] => ******************
  | [orderStatus] => new
  | [lastTimestamp] => 1553858735358
  | [orderPrice] => 4016.00
  | [orderQuantity] => 99
  | [avgPrice] => 0
  | [quantityLeaves] => 99
  | [type] => limit
  | [timeInForce] => GTC
  | [cumQuantity] => 0
  | [clientOrderId] => ******************
  | [symbol] => BTCUSD .  <- should not be listed
  | [side] => buy
  | [execQuantity] => 0
  | )
  |  
  | [timestamp] => 1553858735358
  | [datetime] => 2019-03-29T11:25:35.358Z
  | [lastTradeTimestamp] =>
  | [status] => open
  | [symbol] => KBC/BTC      <- incorrectly shows KBC/BTC here
  | [type] => limit
  | [side] => buy
  | [price] => 0                               
  | [cost] => 0
  | [amount] => 99
  | [filled] => 0
  | [remaining] => 99
  | [fee] => Array
  | (
  | [cost] =>
  | [currency] => BTC
  | [rate] =>
  | )
  |  
  | )
 

- OS: Linux
- Programming Language version: php 7.1
- CCXT version: current pulled from github (2019-04-22)
- Exchange: hitbtc
- Method: fetch_open_orders

**Comment by kroitor** [comment]
HitBTC v1 is deprecated, please use HitBTC v2 API instead, just change `$e = \ccxt\hitbtc()` to `$e = \ccxt\hitbtc2()` in your code. Let us know if that doesn't help.

Duplicates:

- https://github.com/ccxt/ccxt/issues/4996#issuecomment-484179389
- https://github.com/ccxt/ccxt/issues/4840#issuecomment-473710082

**Comment by cod3gen** [comment]
There have been many questions around this @kroitor, obviously the v1 api is deprecated - why not remove it? I compared the two, and it seems that v2 can be a dropin replacement for v1. v2 states `'fetchOrderTrades': false, // not implemented yet` which seems to be incorrect, there is  a function fetchOrderTrades. I could create a pull request if needed.

**Comment by kroitor** [comment]
@cod3gen 

> obviously the v1 api is deprecated - why not remove it?

We will remove it in one of nearest builds.

>  I could create a pull request if needed.

Your help is always welcome, thx! )
