### ISSUE TITLE
hitbtc2 - paging issue (php)

### ISSUE THREAD

**Issue by carels** [ccxt/ccxt#5019]
hitbtc2 seems to have some paging issues:

According to API Docs: https://api.hitbtc.com/#trading-history

"from | Datetime or Number | Interval initial value (optional parameter) If sorting by timestamp is used, then Datetime, otherwise Number of index value."

It seems when $since is set the default is to return orders in descending order which means a lot of fun when trying to get a full list (or more than 100 entries) of orders.

Fix:
hitbtc2.php (around line 1270):

1270c1270,1272
<         if ($since !== null)
---
>         if ($since !== null) {
>             $request['sort'] = 'ASC';
>             $request['by'] = 'timestamp';
1271a1274
>       }

seems to fix the problem, but I'm not sure if it will break things elsewhere in the code.

- OS: linux
- Programming Language version: php
- CCXT version: current (2019-04-22)
- Exchange: hitbtc2
- Method: fetch_my_trades

**Comment by carels** [comment]
btw, the ccxt documentation (Date-based pagination section) is wrong:

// PHP
if ($exchange->has['fetchMyTrades']) {
    $since = exchange->milliseconds () - 86400000; // -1 day from now
    // alternatively, fetch from a certain starting datetime
    // $since = $exchange->parse8601 ('2018-01-01T00:00:00Z') . <- missing semicolon
    $all_trades = array ();
    while (since < exchange->milliseconds ()) {
        $symbol = null; // change for your symbol
        $limit = 20; // change for your limit
        $trades = $exchange->fetchMyTrades ($symbol, $since, $limit);
        if (count($trades)) {
            $since = $trades[count($trades) - 1]; <- should this be: since = $bot->parse8601($trades[count($trades) - 1]['datetime'])-1; 
            $all_trades = array_merge ($all_trades, $trades);
        } else {
            break;
        }
    }
}

**Comment by carels** [comment]
fetch_closed_orders has the same issue, but doesn't look like hitbtc v2 api supports paging by date/time?

**Comment by kroitor** [comment]
@carels 

> It seems when $since is set the default is to return orders in descending order which means a lot of fun when trying to get a full list (or more than 100 entries) of orders.

First of, if you mean the unified `fetchMyTrades` method – it sorts the results by timestamp in ascending order, and the sorting is done on the client side after receiving the exchange response. This is the default with all unified paginated method throughout the entire lib, so changing this to a different order for one specific method with one specific exchange isn't what we want to do. Instead, you just need to take the last trade if you want to paginate backwards in time. Unfortunately, from your code in your initial post  it's hard to tell the actual problem that you have (you've screwed the [markdown](https://guides.github.com/features/mastering-markdown/) there, you should follow these guides very precisely when posting the issue: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue). Can you please paste the code to reproduce the issue and your verbose request/response corresponding to that call?

> btw, the ccxt documentation (Date-based pagination section) is wrong:

Will fix this shortly, thx for pointing that out!

> fetch_closed_orders has the same issue, but doesn't look like hitbtc v2 api supports paging by date/time?

Need the complete short code snippet, including the instantiation (but without your keys, of course) and your verbose request/response to be able to resolve this quickly.

**Comment by carels** [comment]
@kroitor, fetchMyTrades didn't provide the info I was looking for (basically looking for complete order history on my account) and fetchMyTrades seems to only return the trades (/api/2/history/trades call) instead of the orders (/api/2/history/order).

I couldn't get pagination by using timestamps to work on hitbtc2 with the fetch_closed_orders call, but it does work with offsetting so that solved the problem for me.

**Comment by kroitor** [comment]
> @kroitor, fetchMyTrades didn't provide the info I was looking for (basically looking for complete order history on my account) and fetchMyTrades seems to only return the trades (/api/2/history/trades call) instead of the orders (/api/2/history/order).

Yeah, for that we have a family of `fetch_*_orders`... See here: https://github.com/ccxt/ccxt/wiki/Manual#querying-orders

> I couldn't get pagination by using timestamps to work on hitbtc2 with the fetch_closed_orders call, but it does work with offsetting so that solved the problem for me.

Ok, i'd close this for now then, let us know if you have further questions, feel free to reopen this if needed.
