### ISSUE TITLE
yobit returns does not parse fetchClosedOrders correctly (returns no orders)

### ISSUE THREAD

**Issue by carels** [ccxt/ccxt#5020]
@kroitor hopefully I get this one submitted correctly :)

sample code:
`$orders = $exchange->fetchClosedOrders('KBC/BTC');
`
returns:
```

Array
  | (
  | )
```

Verbose mode indicates the json string is returned:
```
Request:
  | Array
  | (
  | [0] => POST
  | [1] => https://yobit.net/tapi
  | [2] => Array
  | (
  | [0] => Content-Type: application/x-www-form-urlencoded
  | [1] => Key: **********************
  | [2] => Sign: **********************
  | [User-Agent] => Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
  | )
  |  
  | [3] => nonce=**********************&method=ActiveOrders&pair=kbc_btc&offset=0
  | )
 
Response:
  | Array
  | (
  | [0] => POST
  | [1] => https://yobit.net/tapi
  | [2] => 200
  | [3] =>
  | [4] => Array
  | (
  | [date] => Array
  | (
  | [0] => Mon, 22 Apr 2019 16:07:48 GMT
  | )
  |  
  | [content-type] => Array
  | (
  | [0] => text/html; charset=utf8
  | )
  |  
  | [transfer-encoding] => Array
  | (
  | [0] => chunked
  | )
  |  
  | [connection] => Array
  | (
  | [0] => keep-alive
  | )
  |  
  | [set-cookie] => Array
  | (
  | [0] => __cfduid=*********************; expires=Tue, 21-Apr-20 16:07:48 GMT; path=/; domain=.yobit.net; HttpOnly; Secure
  | [1] => locale=en; expires=Sun, 22-Apr-2029 16:07:48 GMT; path=/
  | )
  |  
  | [vary] => Array
  | (
  | [0] => Accept-Encoding
  | )
  |  
  | [x-frame-options] => Array
  | (
  | [0] => SAMEORIGIN
  | )
  |  
  | [x-content-type-options] => Array
  | (
  | [0] => nosniff
  | )
  |  
  | [x-xss-protection] => Array
  | (
  | [0] => 1; mode=block;
  | )
  |  
  | [x-download-options] => Array
  | (
  | [0] => noopen
  | )
  |  
  | [expect-ct] => Array
  | (
  | [0] => max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
  | )
  |  
  | [server] => Array
  | (
  | [0] => cloudflare
  | )
  |  
  | [cf-ray] => Array
  | (
  | [0] => *********************-FRA
  | )
  |  
  | [content-encoding] => Array
  | (
  | [0] => gzip
  | )
  |  
  | )
  |  
  | [5] => {"success":1,"return":{"*********************":{"pair":"kbc_btc","type":"buy","amount":****,"rate":****,"timestamp_created":"1555947804","status":0},
....
"*********************":{"pair":"kbc_btc","type":"sell","amount":****,"rate":****,"timestamp_created":"1554560912","status":0}}}

```

- OS: linux
- Programming Language version: php7.1
- CCXT version: current
- Exchange: yobit
- Method: fetch_open_orders

Couple of side notes:
- yobit seems to return that annoying "nonce already used" error when rateLimit < 1000. Not sure if there's a better way to determine the nonce since millisecond numbers are too big and invalidates the whole api key. 
- I see order statuses across the code uses "canceled" instead of "cancelled" which is more commonly used. Every time I use "canceled" a little bit of britishness dies inside of me...  🤣

**Comment by carels** [comment]
It appears the wrong api call is being made. From the yobit API:

```
ActiveOrders
Method returns list of user's active orders

{
	"success":1,
	"return":{
		"100025362":{
			"pair":"ltc_btc",
			"type":"sell",
			"amount":21.615,
			"rate":0.258,
			"timestamp_created":1418654530,
			"status":0 .             <- I'm seeing this in the raw json when in verbose
		},
		...
	}
}

TradeHistory
Method returns transaction history

{
	"success":1,
	"return":{
		"24523":{
			"pair":"ltc_btc",
			"type": "sell",
			"amount":11.4,
			"rate":0.145,
			"order_id":100025362,
			"is_your_order":1,
			"timestamp":1418654530  
		}
		...
	}
}
```
what I can see in liqui.php line 820:

`$orders = $this->fetch_orders($symbol, $since, $limit, $params);`

This returns all the open orders, not closed orders, hence when `return $this->filter_by($orders, 'status', 'closed');` is called an empty array is returned.

I've played with using `fetch_my_trades` instead of `fetch_orders`, but there is an issue with the trade id being returns as id rather than the order id (which I need for the rest of my code).

**Comment by carels** [comment]
I have made a patch for yobit.php:

```
17c17
<             'rateLimit' => 3000, // responses are cached every 2 seconds
---
>             'rateLimit' => 1005, // responses are cached every 2 seconds
227a228,245
>     public function fetch_closed_orders ($symbol = null, $since = null, $limit = null, $params = array ()) {
>         $orders = $this->fetch_my_trades($symbol, $since, $limit, $params);
>       $fixedOrders = array();
>       foreach ($orders as $o) {
>               $o['trade'] = $o['id'];
>               $o['id'] = $o['order'];
>               $o['status'] = 'closed';
>               $o['filled'] = $o['amount'];
> 
>               if (isset($fixedOrders[$o['id']]['id'])) {              // In case we have multiple trades on the same order id !!! UNTESTED !!!
>                       $fixedOrders[$o['id']]['filled'] += $o['amount'];       // May need to use bcadd instead, don't have any real life test cases to test with
>               } else {
>                       $fixedOrders[$o['id']] = $o;
>               }
>       }
>         return $this->filter_by($fixedOrders, 'status', 'closed');
>     }
> 
```

This includes:
- reduced rateLimit to 1005ms (1.005 seconds) which seems to be the safest and lowest number to avoid nonce duplication errors
- added fetch_closed_orders function to yobit.php which uses fetch_my_trades and builds closed orders from there. !! Contains some untested code !! Should probably also warn you I'm not a coder by trade ;)

I'm not sure if it will break something else, will probably find out as I go along :)

**Comment by kroitor** [comment]
Hi @carels !

> This returns all the open orders, not closed orders, hence when return $this->filter_by($orders, 'status', 'closed'); is called an empty array is returned.

Have you read this: https://github.com/ccxt/ccxt/wiki/Manual#orders-cache ?

> added fetch_closed_orders function to yobit.php which uses fetch_my_trades and builds closed orders from there.

We should not do the above, we don't invent methods if they are missing in the exchange API, instead we designate the presence of those methods with the exchange metainfo as described here: https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties. 
The reasoning behind this is also partially explained here: https://github.com/ccxt/ccxt/pull/4256

The proper unified way to do this is:

```JavaScript

    // inside describe ()
    'has': {
        'fetchMyTrades': true,
        'fetchClosedOrders': false, // ← or 'emulated' if you're using the .orders cache
    },
```

Also, your PRs and contributions are welcome, we are happy for all help, however, we need to make sure to follow the guidelines: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code ← due to reasons explained in the [multilanguage section](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support) all changes go to a single-sourced version.

**Comment by carels** [comment]
Hi @kroitor,

> Have you read this: https://github.com/ccxt/ccxt/wiki/Manual#orders-cache ?

Yes, it makes a lot of sense as to why we're not getting closed orders on yobit. I need data across sessions and different scripts which covers almost every shortcoming on the cache :)

> We should not do the above, we don't invent methods if they are missing in the exchange API, instead we designate the presence of those methods with the exchange metainfo as described here: https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties.

This function was present in hitbtc2.php which is why I used that particular function, but I get what you're saying about not "inventing methods". 

> The reasoning behind this is also partially explained here: #4256
gotcha

> The proper unified way to do this is:
>         'fetchMyTrades': true,
>         'fetchClosedOrders': false, // ← or 'emulated' if you're using the .orders cache

I see neither are set in yobit.php. Are you suggesting changing the code to:
- Add fetchMyTrades & fetchClosedOrders to 'has' in yobit.php so your sample below will be suitable for yobit
- rather use the unmodified fetchMyTrades in yobit.php to pull the historic trades?

my main issue with doing this is that fetchMyTrades don't return the order id, but only the trade id (in the 'id' field) which I then have to cater for as an exception elsewhere in my code. In my use case orders will be done from multiple locations (directly on the exchange, via API, multiple scripts, etc) so the cache will not be of any benefit. This is why it makes more sense for me to use fetchClosedOrders function and modify the output in the library than to do it from the client code (since the next exchange might have different issues/output). 

> ↑ It is up to the user to choose which behavior he wants, and not all users want to replace `fetchClosedOrders` with `fetchMyTrades`, due to reasons explained here: https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades. So, the suggest use-case would be to do the following on the userside:

Makes perfect sense, which is why I'm trying to merge multiple trades into a single order if there are multiple trades related to the same order:
```
if (isset($fixedOrders[$o['id']]['id'])) {              // In case we have multiple trades on the same order id !!! UNTESTED !!!
           $fixedOrders[$o['id']]['filled'] += $o['amount'];       // May need to use bcadd instead, don't have any real life test cases to test with
} else {
           $fixedOrders[$o['id']] = $o;
}
```

> Also, your PRs and contributions are welcome, we are happy for all help, however, we need to make sure to follow the guidelines: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code ← due to reasons explained in the [multilanguage section](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support) all changes go to a single-sourced version.

I'm not a developer by trade. While I understand the language, the admin side is lost on me. I've barely mastered git push and git pull (after ignoring git for over a decade and sticking to cvs purely because I know 1 more csv command than with git) so this is waaay above my pay grade 🤣 I'm more likely to break something badly if I try to commit code!

**Comment by kroitor** [comment]
> I'm not a developer by trade. While I understand the language, the admin side is lost on me. I've barely mastered git push and git pull (after ignoring git for over a decade and sticking to cvs purely because I know 1 more csv command than with git) so this is waaay above my pay grade 🤣 I'm more likely to break something badly if I try to commit code!

No worries)) Appreciate your involvement anyway ) We will add the edits to the proper place and they're propagated to the PHP files from there.

> I see neither are set in yobit.php. Are you suggesting changing the code to:
> - Add fetchMyTrades & fetchClosedOrders to 'has' in yobit.php so your sample below will be suitable for yobit
> - rather use the unmodified fetchMyTrades in yobit.php to pull the historic trades?

Nope, that was more of my attempt to explain it, less of a suggestion )) You don't see those constants set in the `yobit.php` file, because `yobit` is derived from `liqui`, which in its turn `.has` every constant defined. Upon instantiation, your `yobit` instance will inherit those from `liqui` and in the `yobit` file we only specify the constants that we want to override, rather than all of them. Liqui, in its turn will inherit the constants from defaults in the base `Exchange.php` class. So, ultimately, the instantiated yobit will have proper values in the `.has` property. If you update your CCXT version to 1.18.487+, this should work (didn't work with the previous versions due to a minor issue in the accessor, which i've fixed):

```shell
# in your shell
mbp:ccxt igorkroitor$ php -f examples/php/cli.php yobit has
yobit->has ()
Array
(
    [cancelAllOrders] =>
    [cancelOrder] => 1
    [cancelOrders] =>
    [CORS] =>
    [createDepositAddress] => 1
    [createLimitOrder] => 1
    [createMarketOrder] =>
    [createOrder] => 1
    [deposit] =>
    [fetchBalance] => 1
    [fetchClosedOrders] => emulated
    [fetchCurrencies] =>
    [fetchDepositAddress] => 1
    [fetchDeposits] =>
    [fetchFundingFees] =>
    [fetchL2OrderBook] => 1
    [fetchLedger] =>
    [fetchMarkets] => 1
    [fetchMyTrades] => 1
    [fetchOHLCV] => emulated
    [fetchOpenOrders] => 1
    [fetchOrder] => 1
    [fetchOrderBook] => 1
    [fetchOrderBooks] => 1
    [fetchOrders] => emulated
    [fetchTicker] => 1
    [fetchTickers] => 1
    [fetchTrades] => 1
    [fetchTradingFee] =>
    [fetchTradingFees] =>
    [fetchTradingLimits] =>
    [fetchTransactions] =>
    [fetchWithdrawals] =>
    [privateAPI] => 1
    [publicAPI] => 1
    [withdraw] => 1
)
```

> which is why I'm trying to merge multiple trades into a single order if there are multiple trades related to the same order

So, should we close it or is there anything we should do inside the lib on this issue? )
