### ISSUE TITLE
Wrong high low values from fetchTickers

### ISSUE THREAD

**Issue by webparadoxer** [ccxt/ccxt#5021]
- OS: ubuntu 16.04
- Programming Language version: php, js
- CCXT version: 1.18.486
- Exchange: binance
- Method: fetchTickers

I request data once a minute. Only for these parameters(high low), the data may not change long enough. 
But if the data is requested by another fetchOHLCV method, I see everything in the history correctly.

**Comment by kroitor** [comment]
Can you elaborate, please? Not sure what your issue is and what exactly is wrong... https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by webparadoxer** [comment]
node examples/js/cli binance fetchTicker ETH/USDT 
execute one per minute - 10 times
and node examples/js/cli binance fetchOHLCV ETH/USDT

**Comment by kroitor** [comment]
@webparadoxer we need the code to reproduce it, otherwise we will be mostly guessing.

**Comment by webparadoxer** [comment]
https://api.binance.com/api/v1/klines?symbol=ETHUSDT&interval=1m
[1556037780000,"172.93000000","172.95000000","172.90000000","172.90000000","24.79601000",1556037839999,"4288.22568720",8,"20.40743000","3529.31465200","0"]]

node examples/js/cli binance fetchTicker ETH/USDT
binance.fetchTicker (ETH/USDT)
{        symbol:   "ETH/USDT",
      timestamp:    1556037777001,
       datetime:   "2019-04-23T16:42:57.001Z",
           high:    175.83,
            low:    168.38,
            bid:    172.92,
      bidVolume:    0.18661,
            ask:    172.97,
      askVolume:    4,
           vwap:    172.5707998,
           open:    168.55,
          close:    172.93,
           last:    172.93,
  previousClose:    168.55,
         change:    4.38,
     percentage:    2.599,
        average:    undefined,
     baseVolume:    363124.86706,
    quoteVolume:    62664748.7345123,
           info: {             symbol: "ETHUSDT",
                          priceChange: "4.38000000",
                   priceChangePercent: "2.599",
                     weightedAvgPrice: "172.57079980",
                       prevClosePrice: "168.55000000",
                            lastPrice: "172.93000000",
                              lastQty: "0.50080000",
                             bidPrice: "172.92000000",
                               bidQty: "0.18661000",
                             askPrice: "172.97000000",
                               askQty: "4.00000000",
                            openPrice: "168.55000000",
                            highPrice: "175.83000000",
                             lowPrice: "168.38000000",
                               volume: "363124.86706000",
                          quoteVolume: "62664748.73451230",
                             openTime:  1555951377001,
                            closeTime:  1556037777001,
                              firstId:  70151889,
                               lastId:  70275099,
                                count:  123211              } }

**Comment by webparadoxer** [comment]
stored data from fetchTickers
![image](https://user-images.githubusercontent.com/5503366/56599922-437fe880-6600-11e9-99c7-4ccc546c0c36.png)

**Comment by webparadoxer** [comment]
https://api.binance.com//api/v1/ticker/24hr?symbol=BTCUSDT and here.
I think this is a bug api of the exchange itself. For quite a while high and low don't change
