### ISSUE TITLE
Signature does not match for CoinEgg

### ISSUE THREAD

**Issue by domainbank** [ccxt/ccxt#5023]
The issues is that:
import ccxt
coinegg   = ccxt.coinegg({
    'apiKey': 'my_api_key_from_CoinEgg',
    'secret': 'my_secret_from_CoinEgg',
})
coinegg.create_limit_sell_order('XRP/ETH',1, 0.0001)

Error:
ccxt.base.errors.AuthenticationError: coinegg Signature does not match
<img width="659" alt="Snipaste_2019-04-23_23-00-38" src="https://user-images.githubusercontent.com/19573010/56591639-ab8ff800-661b-11e9-972a-8d97d67a9aa4.png">

I tried the demo and it worked.
https://github.com/coinegg/api-docs/blob/master/demo/python/ceapi.py
I tried OKEX and it worked.

- OS: Win10 64
- Programming Language version: Python 2.7
- CCXT version: 1.18.466
- Exchange: CoinEgg
- Method: coinegg.create_limit_sell_order

**Comment by kroitor** [comment]
@domainbank does `fetch_balance` work for you?

**Comment by kroitor** [comment]
@domainbank it looks like you're not using the rate-limiter...

```Python
import ccxt
exchange = ccxt.coinegg({
    'apiKey': 'my_api_key_from_CoinEgg',
    'secret': 'my_secret_from_CoinEgg',
    'enableRateLimit': True, # this is required by the Manual
})
print(exchange.fetch_balance())
```

↑ Does this work ?

**Comment by kroitor** [comment]
@domainbank it means that your apikeys are wrong. Does this work:

```Python
import ccxt
exchange = ccxt.coinegg({
    'apiKey': 's9xp2-p1n6s-a3awz-zd5bw-d5jzv-hp5zz-yb4i7',
    'secret': 'xd1p,-ZFsgL-7ref^-K4NQQ-}gpJw-[MitI-iZ/RT',
    'enableRateLimit': True, # this is required by the Manual
})
print(exchange.fetch_balance())
```

↑ This works on my side with Python 2.7. Should work for you as well. If this works, and your keypair doesn't – check your keypair. Will be happy if you report back whether it worked for you or not.

**Comment by kroitor** [comment]
Let us know if the above does not help.

**Comment by domainbank** [comment]
> Let us know if the above does not help.

Thank you. I tried with a new key and add 'enableRateLimit".
Now It's working. Thanks
