### ISSUE TITLE
Bitforex returns wrong maker and taker fee

### ISSUE THREAD

**Issue by mjzarrin** [ccxt/ccxt#5032]
- OS: macOS High Sierra
- Programming Language version: Python
- CCXT version: 1.18.471
- Exchange: Bitforex
- Method: load_markets()

the load_markets return all makers fee equal to zero and takers fee are 0.0005 but as it says in below link the real value for both makers and takers are 0.001 .

https://support.bitforex.com/hc/en-us/articles/360006824872-Trading-Fees

**Comment by kroitor** [comment]
@mjzarrin thx for reporting! Fixed in 1.18.492+.
