### ISSUE TITLE
New Exchange: WazirX

### ISSUE THREAD

**Issue by denarioresearch** [ccxt/ccxt#5035]
https://github.com/WazirX/wazirx-api

**Comment by test2a** [comment]
any updates on this exchange?

**Comment by dhruvv90** [comment]
I am willing to take this if it has'nt started yet..

**Comment by kroitor** [comment]
@dhruvv90 that would be awesome! Check out the guidelines (plz make sure to follow them literally to a word)

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#new-exchange-integrations

**Comment by dhruvv90** [comment]
@kroitor : PR raised for this :  #7397
