### ISSUE TITLE
FetchOpenOrders - Side

### ISSUE THREAD

**Issue by tezeug** [ccxt/ccxt#5036]
- OS: Kubuntu 19.04 64-bit
- Programming Language version: Python 3.7
- CCXT version: 1.18.492
- Exchange: BitMEX
- Method: fetch_open_orders(symbol = 'BTC/USD', params={'side':'sell'})

Hello, why does not this code work (check the method)? I've tried it but it always just print the orders and does not matter whether it is BUY or SELL.
Thank you.

**Comment by tezeug** [comment]
Whole tomorrow I will be reading and learning everything in the manual but so far I could not find anything about this there. When I tried to put there (side = ‘buy’) I got an error.

**Comment by tezeug** [comment]
@kroitor Update
I’ve looked into the source code and fixed it with that.

bit = BitMEX.fetch_orders(symbol=S1, params = {"filter": {"open":True, "side":"buy"}})

**Comment by kroitor** [comment]
@tezeug thx for reporting back! Good to know you've figured it out!
