### ISSUE TITLE
New exchange: Huobi Korea

### ISSUE THREAD

**Issue by ofstiker** [ccxt/ccxt#5039]
Another Huobi-based exchange in Korea please.

API Doc: https://github.com/alphaex-api/BAPI_Docs_ko/wiki
URL: https://www.huobi.co.kr
Fee: https://support.huobi.co.kr/hc/ko/articles/360002213031-%EC%88%98%EC%88%98%EB%A3%8C-%EC%95%88%EB%82%B4
Volume: https://coinmarketcap.com/exchanges/huobi-korea/
Address: 1F/2F Metlife Tower, 316, Teheran-ro, Gangnam-gu, Seoul, Republic of Korea. 
Registration: 420-87-00883 
Based Country: South Korea

Thanks in advance.

**Comment by frosty00** [comment]
not sure if the exchange still exists
