### ISSUE TITLE
"ERR_RATE_LIMIT" with bitfinex

### ISSUE THREAD

**Issue by DmitryVil** [ccxt/ccxt#5043]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10
- Programming Language version: python
- CCXT version: 1.18.466
- Exchange: bitfinex
- Method: fetch_order_book()

Good morning,

Exchange bitfinex has a rateLimit = 1500.
In the same time, when I keeping this restriction, I receive the error: "ERR_RATE_LIMIT"
Also have the same problem if I fetching with time interval 1700.

Thank you in advance,

Dmitry

**Comment by tezeug** [comment]
Just do this:

try:
   ***your code, e. g. place an order***
except ccxt.errors.rateLimit:
   print ("rate limit error")

Here you can put what to do then when the error occurs. Hope this helps you.

**Comment by kroitor** [comment]
@DmitryVil hi! This is a known feature of Bitfinex – their rate-limits are defined per endpoint, so it will depend on not only the frequency, but also on the destination of your requests. See the following answers for more explanations:

- https://github.com/ccxt/ccxt/issues/3738#issuecomment-415999336
- https://github.com/ccxt/ccxt/issues/2700
- https://github.com/ccxt/ccxt/issues/2166#issuecomment-371392384
- https://github.com/ccxt/ccxt/search?q=bitfinex+rateLimit&type=Issues

Let us know if that doesn't answer the question.
