### ISSUE TITLE
[exmo] fetchOrders is misleading

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5052]
exmo doesn't really support fetch orders.  It has `user_open_orders` and `user_cancelled_orders`, but you cannot get a list of closed orders for some reason.

The implementation of `fetchOrders` calls `privatePostUserOpenOrders`, and so will only return the open orders.  I suggest this code be moved to `fetchOpenOrder` and `has['fetchOrders']` be set to `false`.

The exchange support `fetchOrder` (singular) for closed orders, so the desired behaviour can be achieved through multiple api calls.

See https://exmo.com/en/api

**Comment by kroitor** [comment]
> exmo doesn't really support fetch orders. It has user_open_orders and user_cancelled_orders, but you cannot get a list of closed orders for some reason.

This is a common pitfall with some exchanges that don't have means for fetching order history, as explained in the [`.orders` cache](https://github.com/ccxt/ccxt/wiki/Manual#orders-cache) section in the Manual.

> I suggest this code be moved to fetchOpenOrder 

It's in the `fetchOpenOrders` already.

> and has['fetchOrders'] be set to false.

This may be tricky, but, yeah, we will consider this.

Let me know if the above does not answer the question.

**Comment by npomfret** [comment]
> It's in the fetchOpenOrders already.

The code in question is called from `fetchOpenOrders`, but lives in `fetchOrders`.  My suggestion is to remove `fetchOrders` completely (because I think it's misleading).

**Comment by kroitor** [comment]
@npomfret have you checked the link on the `.orders` cache? )

**Comment by npomfret** [comment]
@kroitor I am aware of the orders cache.  I also have a slight issue with it! But that's for a different discussion (basically it's a fine idea, but I think it's too ambitious and probably doesn't belong in the core product).

In my use case the orders cache doesn't work because I don't have a long running process that keeps the CCXT object around forever, and I don't persist the orders cache to disk between startup and shutdown of ccxt instances (which I assume you need to do).

**Comment by kroitor** [comment]
@npomfret you can then inspect the `.has['fetchOrders']` property and avoid calling it in the logic if it's anything but `True` (if it's `'emulated'` or False – fallback to `fetchMyTrades` or other means). But yeah, we will think of detaching the cache out of CCXT into a separate repo, probably.
