### ISSUE TITLE
BitMEX WebSocket

### ISSUE THREAD

**Issue by tezeug** [ccxt/ccxt#5053]
- OS: Kubuntu 19.04 64-bit
- Programming Language version: Python 3.7
- CCXT version: 1.18.497
- Exchange: BitMEX
- Method: none

Hi,
do you plan to add a WS support for BitMEX?

**Comment by kroitor** [comment]
Hi! Sorry, but this issue is a duplicate. Please, read through this post (all about WS there): #56
