### ISSUE TITLE
Bitforex - rate limiting

### ISSUE THREAD

**Issue by carels** [ccxt/ccxt#5054]
Bitforex has the following rate limits:

```
      /api/v1/market/symbols 10 seconds /time
      /api/v1/market/ticker 10 seconds / 5 times
      /api/v1/market/depth 10 seconds / 5 times
      /api/v1/market/trades 10 seconds /time
      /api/v1/market/kline 10 seconds /time

      /api/v1/fund/mainAccount seconds / 2times
      /api/v1/fund/allAccount 30seconds / 2times
      /api/v1/trade/placeOrder 10 seconds / 20 times
      /api/v1/trade/placeMultiOrder 10 seconds / 2times
      /api/v1/trade/cancelOrder 10 seconds / 20times
      /api/v1/trade/cancelMultiOrder 10 seconds /time
      /api/v1/trade/cancelAllOrder 10 seconds /time
      /api/v1/trade/orderInfo 10 seconds / 20times
      /api/v1/trade/multiOrderInfo 10 seconds / 2times
```

I've noticed some other exchanges have similar rate limits (i.e. on a per call basis) so I'm not sure if there's already code to work with this? If there's anything that's been done or already some time spent on solving the problem please let me know. If not, I'm thinking (php):

```
- add variable $this->rateLimitCalls = array('fetchTicker' => 2000, 'createOrder' => 500); etc
- in each fetch call, set  $this->callName = 'fetchTicker' (or createOrder, etc depending on the call)
- in rateLimit, check if $this->callName is set, if so check $this->lastRestRequestTimestampCalls[$this->callName]. 
- when done in rateLimit unset $this->callName (so any subsequent "normal" calls are running off the generic rateLimit)
```

Regards,
Carel

**Comment by kroitor** [comment]
> I've noticed some other exchanges have similar rate limits (i.e. on a per call basis) so I'm not sure if there's already code to work with this?

All about rate limiting is here (a discussion on token bucket and per-endpoint costs): https://github.com/ccxt/ccxt/issues/1399#issuecomment-359233015

In JS and Python the token bucket is already implemented. However, in PHP the current rate-limiting implementation is sync and naive, so, it will sleep regular intervals and doesn't support bursts. So, if you think you can implement token bucket in PHP – your PRs and contributions are welcome ) After that, coding for per-endpoint costs in a unified manner will become straightforward and we will start filling up their rateLimits in derived exchange files... 

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

If you don't mind I suggest to move this discussion here: #1399 just to keep it all in one place ) Feel free to ask if you have questions there ) Thx )
