### ISSUE TITLE
kraken withdrawal id format

### ISSUE THREAD

**Issue by denarioresearch** [ccxt/ccxt#5058]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: ubuntu
- Programming Language version: nodejs
- CCXT version:1.18.459
- Exchange: kraken
- Method: withdraw

As a withdrawal id instead of string kraken provides an object in the following format _{ refid: 'AITDDNJ-5XXAN6-4KAC2J' }_

**Comment by kroitor** [comment]
@denarioresearch sorry, didn't quite get the issue you're having... can you, please, elaborate? The best way to report it is to post your code and verbose request/response for the call, as described here https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by denarioresearch** [comment]
My question is about id format. Here is a code example

`kraken.withdraw (code, amount, address, tag,  {key:alias}).then(data=>{console.log(data)})`

and output 
`{
    'info' { ... }, 
    'id': { refid: 'AITDDNJ-5XXAN6-4KAC2J' }
}`

But most of the exchanges provide id value as a string (ie 'id': '34587345395') instead of object.

**Comment by kroitor** [comment]
@denarioresearch you're confusing unified CCXT structures with the `info` subfield. In general, each response you get from this exchange will contain objects, and each object will consist of unified fields (including the `id`, `amount`, `currency`, and so on) and also the `info` field that will contain the raw untouched response object from the exchange as is:

```JavaScript
    {
            'info': {
                method: "Ether",
                aclass: "currency",
                asset: "XETH",
                refid: "A2BF34S-O7LBNQ-UE4Y4O",  // ←----- you're looking here
                ....
            },
            'id': 'A2BF34S-O7LBNQ-UE4Y4O',  // ←----- you should be looking here
            'currency': 'ETH',
            'amount': amount,
            'address': address,
            'tag': undefined,
            'status': status,
            'type': type,
            'updated': undefined,
            'txid': txid,
            ...
        }
```

↑ This is explained in the Manual, here: https://github.com/ccxt/ccxt/wiki/Manual#transaction-structure. Let us know if that doesn't answer your question.

**Comment by denarioresearch** [comment]
I've just tested withdrawal. Here is ouput
`{ info: { error: [], result: { refid: 'AIB74FE-32PVPJ-ENCPXM' } },
  id: { refid: 'AIB74FE-32PVPJ-ENCPXM' } }
`

As you see id is an object. I use ccxt v1.18.459. Let me know if id is a string in future versions

**Comment by denarioresearch** [comment]
kraken.js withdraw function returns object
`{
    'info': response,
    'id': response['result'],
}`
`response['result'] = { refid: 'AIB74FE-32PVPJ-ENCPXM' }` in my case

**Comment by kroitor** [comment]
@denarioresearch checking this, will get back to you shortly.

**Comment by kroitor** [comment]
@denarioresearch I'm getting this format in response with version 1.18.500+

```JavaScript
-------------------------------------------
{      info: {   type: "withdrawal",
               method: "Ripple XRP",
               aclass: "currency",
                asset: "XXRP",
                refid: "AIBFAV7-YKK66Y-UBXLYJ",
                 txid:  null,
                 info: "rUocf1ixKzTuEe34kmVhRvGqNCofY1NJzV",
               amount: "24.980000",
                  fee: "0.020000",
                 time:  1556818143,
               status: "Initial"                             },
         id:   "AIBFAV7-YKK66Y-UBXLYJ",
   currency:   "XRP",
     amount:    24.98,
    address:   "rUocf1ixKzTuEe34kmVhRvGqNCofY1NJzV",
        tag:    undefined,
     status:   "pending",
       type:   "withdrawal",
    updated:    undefined,
       txid:    undefined,
  timestamp:    1556818143000,
   datetime:   "2019-05-02T17:29:03.000Z",
        fee: { currency: "XRP", cost: 0.02 }                    }
```

↑ So, the refid is correctly parsed... Can you please post your **full verbose output** output as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue?

```JavaScript
;(async () => {
    await exchange.loadMarkets ()
    exchange.verbose = true
    const withdrawals = exchange.fetchWithdrawals ('XRP') // ←--- your currency here
```

**Comment by kroitor** [comment]
@denarioresearch also, do you have the same issue with the most recent version of the lib?

**Comment by denarioresearch** [comment]
upgraded to 1.18.501 and still have the same format of callback message. Will test verbose mode later today.
