### ISSUE TITLE
CoinBase Pro  fetchMarkets missing information

### ISSUE THREAD

**Issue by firepol** [ccxt/ccxt#5061]
- OS: Linux
- Programming Language version: Python 3.6
- CCXT version: 1.18.500
- Exchange: coinbasepro
- Method: fetchMarkets

See what I get as response (I took the first element in the list):

```
{
	'fee_loaded': False,
	'percentage': True,
	'tierBased': True,
	'maker': 0.0,
	'taker': 0.003,
	'id': 'REP-USD',
	'symbol': 'REP/USD',
	'base': 'REP',
	'quote': 'USD',
	'precision': {
		'amount': 8,
		'price': 2
	},
	'limits': {
		'amount': {
			'min': 0.1,
			'max': 5000.0
		},
		'price': {
			'min': 0.01,
			'max': None
		},
		'cost': {
			'min': 10.0,
			'max': 30000.0
		}
	},
	'active': True,
	'info': {
		'id': 'REP-USD',
		'base_currency': 'REP',
		'quote_currency': 'USD',
		'base_min_size': '0.1',
		'base_max_size': '5000',
		'base_increment': '0.000001',
		'quote_increment': '0.01',
		'display_name': 'REP/USD',
		'status': 'online',
		'margin_enabled': False,
		'status_message': '',
		'min_market_funds': '10',
		'max_market_funds': '30000',
		'post_only': False,
		'limit_only': False,
		'cancel_only': False
	}
}
```

Issue: the object structure looks very different from the one documented in the manual: https://github.com/ccxt/ccxt/wiki/Manual#markets

Maybe baseId and quoteId are optional (I've seen them in binance and bitfinex) but seeing:
- fee_loaded
- tierBased
- maker
- taker

confused me, because they are not documented... maybe this needs cleanup?
If you think it's ok like this, then feel free to close this. Just wanted to clarify... thx

**Comment by Rajeshinu** [comment]
Hi ,
i want to know what is "fee_loaded" in the exchange.fees 
fee_loaded = false and fee_loaded = true...
