### ISSUE TITLE
Real-time ticker across all markets.

### ISSUE THREAD

**Issue by dmitriano** [ccxt/ccxt#5062]
OS: ubuntu 16.04
Programming Language version: nodejs v8.12.0
CCXT version: ccxt@1.18.395
Exchange: binance
Method: exchange.fetchTickers(), exchange.fetchOrderBook()

Is there a way to get all the prices of all the markets of an exchange in real-time (once a few seconds)? Or at least not all, but some wide subset.

1. Calling exchange.fetchOrderBook() for each market symbol is not an option, because if the exchange rate limit is enabled it takes a long time.
2. exchange.fetchTickers() is not real-time as far as see.

Could you comment this please?
Is there some alternatives? Does using [proxies](https://github.com/ccxt/ccxt/blob/master/examples/js/arbitrage-pairs.js) help? Do native exchange APIs allow this?

**Comment by xCuri0** [comment]
@dmitriano Use Websocket

**Comment by dmitriano** [comment]
What is the status of Websocket API implementation in ccxt?

**Comment by xCuri0** [comment]
@dmitriano @lfern has a fork of ccxt with websocket support. It's kinda buggy tho

**Comment by fonzmeister** [comment]
I think you're better of pulling this data from a different source, for example coingecko, coinmarketcap or coinpaprika and many others

**Comment by dmitriano** [comment]
@fonzmeister Are they realtime? What is the refresh rate? The data from what exchanges they provide?

**Comment by fonzmeister** [comment]
@dmitriano It differs from site too site. There are tons of sites like that. Coinpaprika and coingecko offer most of the stuff for free. Coinmarketcap is the most popular, but you'll probably need too pay if you want real info. (messari is another one, offers only data for the top100 coins though. But if you need BTC only it is a good pick)

But they calculate price from a lot of sources, you should refer to their documentation. They probably do all the calculations you want.

Another thing you could try is too stream the index from for example bitmex. Exchanges that offer fututres (okex, bitmex, deribit, kraken and others), have an index too calculate the bitcoin price.

It consists usually of 4 exchanges only, depends on the exchange. So it is not the calculated from every exchange, but it might suite your need

**Comment by dmitriano** [comment]
@fonzmeister  I am interested in exact real-time prices on a given exchange line 'binance' for example.

**Comment by fonzmeister** [comment]
oh, sorry then I misunderstood.

If that is your requirement the only option I guess is too use websockets as adviced earlier.

**Comment by kroitor** [comment]
Real-time WS APIs are supported in [CCXT Pro](https://ccxt.pro) (including tickers and orderbooks). Closing this for now. Feel free to reopen it or just ask further questions if any.
