### ISSUE TITLE
Kraken fetchTickers([ 'ETH/BTC', 'LTC/BTC' ]) gives all markets

### ISSUE THREAD

**Issue by nwocykra** [ccxt/ccxt#5068]
I see that kraken fetchTickers doesn't support the subset argument and falls back to returning all available market ticker data.

As in docs: fetchTickers([ 'ETH/BTC', 'LTC/BTC' ])
Returns all market tickers.

This however is not necessary seen as the kraken API does indeed support the feature of a limited subset of tickers.

- OS: OSX
- Programming Language version: NodeJS
- CCXT version: 1.18.508
- Exchange: Kraken
- Method: fetchTickers

**Comment by kroitor** [comment]
Yeah, some implementations don't have the filtering implemented, this is a known issue, and we will add the necessary base methods soon. Will let you know when it's there.

**Comment by nwocykra** [comment]
Great to hear! Thank you.
