### ISSUE TITLE
Bitfinex JS symbols.map is not a functiom

### ISSUE THREAD

**Issue by ahmedbodi** [ccxt/ccxt#5069]
- OS: Javascript
- Programming Language version: v11.13.0
- CCXT version: latest
- Exchange: bitfinex
- Method: fetchTickers

Error: TypeError: symbols.map is not a function

**Comment by kroitor** [comment]
@ahmedbodi can you please show your code to reproduce it? a full error stack and your verbose request/response? Can't reproduce it with the following code:

```JavaScript
const ccxt = require ('ccxt')
const exchange = new ccxt.bitfinex ({ enableRateLimit: true })
;(async () => {
    const tickers = await exchange.fetchTickers ()
   console.log (tickers)
}) ()
```

**Comment by ahmedbodi** [comment]
`const ccxt = require ('ccxt')

let clients = {}

async function fetchTickers(client, market)
{
    if (client.has['fetchTickers'])
    {
        try {
            console.log("[" + client.name + "] Fetch " + market + " Tickers");
            ticker = await client.fetchTickers(market);
        } catch (e) {
            console.log("[" + client.name + "] Error Fetching " + market + " Tickers: " + e);
        }
    }
}

async function fetchOHLCVs(client, market)
{
    if (client.has['fetchOHLCV'])
    {
        try {
            console.log("[" + client.name + "] Fetch " + market + " OHLCV");
            ohlcv = await client.fetchOHLCV(market);
        } catch (e) {
            console.log("[" + client.name + "] Error Fetching " + market + " OHLCV: " + e);
        }
    }
}

async function fetchOrderBooks(client, market)
{
    if (client.has['fetchOrderBook'])
    {
        try {
            console.log("[" + client.name + "] Fetch " + market + " OrderBook");
            orderbook = await client.fetchOrderBook(market);
        } catch (e) {
            console.log("[" + client.name + "] Error Fetching " + market + "OrderBooks: " + e);
        }
    }
}

async function main()
{
    for (i in ccxt.exchanges)
    {
        // Create Exchange Client
        exchange = ccxt.exchanges[i];
        clients[exchange] = new ccxt[exchange]({'enableRateLimit': true});
    }

    // Setup Loops
    while(true)
    {
        for (i in clients)
        {
            client = clients[i];

            try {
                // Load All Markets and currencies
                markets = await client.loadMarkets();
                currencies = client.currencies;
            } catch (e) {
                console.log("[" + client.name + "] Error: " + e)
            }

            for (market in markets)
            {
                // Fetch Tickers
                //await new Promise(resolve => setTimeout(() => resolve(fetchTickers(client, market)), 60));

                // Fetch OHLCV
                //await new Promise(resolve => setTimeout(() => resolve(fetchOHLCVs(client, market)), 60));

                // Fetch OrderBook
                //await new Promise(resolve => setTimeout(() => resolve(fetchOrderBooks(client, market)), 60));
                await Promise.all([fetchTickers(client, market), fetchOHLCVs(client, market), fetchOrderBooks(client, market)]);
            }
        }
    }
}

main()
`

**Comment by kroitor** [comment]
@ahmedbodi can you remove all the unnecessary parts?

Does this work for you

```
const ccxt = require ('ccxt')
const exchange = new ccxt.bitfinex ({ enableRateLimit: true })
;(async () => {
    const tickers = await exchange.fetchTickers ()
   console.log (tickers)
}) ()
```

?

**Comment by ahmedbodi** [comment]
Strange. that works fine

**Comment by kroitor** [comment]
@ahmedbodi there's an error in your code, you're passing `market` to `fetchTickers` as the first argument, but it doesn't accept a `market` in the first argument:

```JavaScript
            ticker = await client.fetchTickers(market); //  ← here
```

**Comment by ahmedbodi** [comment]
ah good catch. fixed.  testing now

**Comment by kroitor** [comment]
@ahmedbodi ok, let me know if that doesn't resolve the issue for you. Feel free to reopen this or just ask further questions if any.
