### ISSUE TITLE
Where can bybit publish a bounty so a developer implements their API in CCXT?

### ISSUE THREAD

**Issue by firepol** [ccxt/ccxt#5070]
Hi there,

I've recently started using a new exchange, [bybit](https://www.bybit.com/app/register?ref=RlpA0) (use this link to register and we both get 10 USD referral bonus). The exchange seems nice and a very good alternative to bitmex.

They have REST & WebSocket API: https://github.com/bybit-exchange/bybit-official-api-docs

I checked CCXT and didn't see the API implemented yet. So I thought to help bybit speeding up this kind of thing by creating a bounty. They already invest a lot of money in marketing, so I'm sure they can spare a few hundred dollars for this, which will help their exchange get even more popularity.

I'm sure that @kroitor or other developers like @lfern (for websockets) would appreciate to receive a bounty for implementing the API and websockets.

I tweeted about it: https://twitter.com/JosephImb/status/1125651622762147841

But the guy asked where could a bounty be published. I'm honestly new to bounties, I've just read somewhere that it's common to offer bounties for features to be added to existing open source projects.

@kroitor any advise for a reply or can you maybe answer the tweet directly?
Thanks and cheers

**Comment by CryptoGnome** [comment]
Bump This!

**Comment by kroitor** [comment]
Hi @firepol !

Thanks for your proposal and for the offer!

Unfortunately, I already have a backlog of work that I'm trying to resolve, so, I can't promise to implement it right away. 

We would be happy to merge it if someone is willing to take the bounty and submit a PR according to these guides:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md
- https://github.com/ccxt/ccxt/wiki/Requirements

> @kroitor any advise for a reply or can you maybe answer the tweet directly?

To offer a reward, there's currently two options:

1. either declare a bounty here and wait for someone to implement it (as soon as it is merged – transfer the funds to the developer)
2. use [gitcoin](https://gitcoin.co/) to set the bounty on this issue, so, when it gets merged and closed the person who resolves it gets the reward (i hope @owocki will help us with that, see an example of a gitcoin-enabled issue here: https://github.com/ccxt/ccxt/issues/4457)

----

We've been thinking and planning the reward eco system for developers and contributors here: https://github.com/ccxt/ccxt/issues/1302 and we hope to put it on rails in the coming weeks.

**Comment by ahmedbodi** [comment]
If you Shoot me an email to ahmedbodi@crypto-expert.com with the details of the bounty amount. i would be willing to pick up the bounty

**Comment by lacabra** [comment]
@firepol: check out https://gitcoin.co

**Comment by owocki** [comment]
i'm like 2 weeks late to the party whoops.. here are some examples of gitcoin bounties => https://github.com/gitcoinco/Gitcoin-Exemplars

hit me up if you have any questions.  you can post a bounty anytime at gitcoin.co/new

**Comment by firepol** [comment]
So, it's already almost 2 months. Did anybody do anything? Did any bounty show up?

**Comment by ahmedbodi** [comment]
I received partial payment for the work, however the ByBit is lacking most of the required API's. Upon speaking to the team, they told me they'll get back in touch with me once theyve added them

**Comment by doftorul** [comment]
@ahmedbodi what do you mean by "lacking most of the required API's " ? Are you sure you've got in contact with the right people ?

Please take a looky here:
https://github.com/Haehnchen/crypto-trading-bot/blob/master/exchange/bybit.js

**Comment by ahmedbodi** [comment]
There's no API's in there to get the markets or the symbols

**Comment by firepol** [comment]
@ahmedbod a pragmatical approach, hardcode the markets, there are only 4, easy peasy: BTC, ETH, XTP, EOS

Cool, now assuming you implemented all the rest of the APIs, you can release something, right?

@kroitor will review the code, if something absolutely needed is missing he'll give you feedback and it can be added or ignored for now.

Better have something working and some features missing than the entire api missing and waiting for weeks to be done. Don't you think?

If you received partial payment I think it would be nice that you release something asap... you'd make some people happy if you add at least something. Thank you.

**Comment by kroitor** [comment]
> Better have something working and some features missing than the entire api missing and waiting for weeks to be done. Don't you think?

I would partially agree with you. However, tbh, personally, I think if you're launching an exchange that is going to turn over capital, then you make sure to have an endpoint for markets at the very least, please, thank you very much )) We're not even speaking of a complete API with withdrawal history, blackjack and stuff.

**Comment by firepol** [comment]
You are right, the bybit API seems incomplete or done quick and dirty: order & trade history and other essential endpoints are missing. The dev team behind it could have at least tried to copy the bitmex API...

My point was that if there is some progress, submit a PR for it. Else whoever wants to use this exchange (or at least the few available endpoints) with CCXT has to implement it himself? It would be a waste of time if someone has already coded something...

**Comment by firepol** [comment]
Some endpoints are just not available in rest but only via websockets by design: https://github.com/bybit-exchange/bybit-official-api-docs/blob/master/en/websocket.md#execution

Does CCXT support such things? I mean if the balance can be fetched via websocket, would it be possible to subscribe to the balance channel the first time a user makes such a call, let it subscribed for x amount of seconds, save in memory the last update, so next time a call to fetch balance is done CCXT can return just the last (updated) value? Same for the other endpoints (order book).

Alternatively for such endpoints CCXT can subscribe to the WS, fetch data, unsubscribe, return the result. But I guess this has much more overhead than a standard rest api call, right?

**Comment by ahmedbodi** [comment]
i'll see if i can find the code ive done so far and push it when i get some time. i've pushed it somewhere to github just not sure where

**Comment by Crypto2legit** [comment]
Bump

**Comment by ahmedbodi** [comment]
https://github.com/ccxt/ccxt/commit/a5a9a2977106ed12c804454e145f96530318f78f <- that is what's been done so far. i'll check up on it some time this week and update it with any new endpoints

**Comment by JoseCarlosDaSilva** [comment]
@ahmedbodi any updates on this project? Thanks for any reply.

**Comment by xiandong79** [comment]
any updates on this project?

**Comment by kroitor** [comment]
@xiandong79 we have this PR submitted yesterday and going to review it asap: https://github.com/ccxt/ccxt/pull/5985

**Comment by xiandong79** [comment]
Did anybody do anything?

**Comment by sloth456** [comment]
@kroitor Will this fork be merged into the main project?

**Comment by kroitor** [comment]
@sloth456 yes, will merge as soon as I get to it: https://github.com/ccxt/ccxt/wiki/FAQ

**Comment by sloth456** [comment]
@kroitor The reason I ask is because in order to get this fork to work, I had to uninstall the ccxt module I already had and then manually install this forked version.  I could not find a way to install both the main version of CCXT (for my other projects) and this forked version, they both exist under the same python module name 'ccxt'

I'm pretty new to python so I don't know how to install this forked version under a different module name, for example 'ccxt_bybit' so that I could just do 'import ccxt_bybit' when I want to use this version.

I know it's outside of the scope of this thread, but maybe you can point me in the right direction in regards to installing this forked version under a different module name? It would really help me.

Thank you for everything so far.

**Comment by kroitor** [comment]
@sloth456 as far as I understand, Python and pip cannot really do that natively, so, without changing the package itself, you can't install it under a different name. However, obviously, developers of those packages are working with multiple versions, so this issue is addressed by special packages for virtualization. You can have two packages installed in two parallel, but separate virtual environments, one for your _"standard ccxt from pypi"_ and another one for your _"experimental ccxt with bybit"_. One of the most frequently used packages for virtualization with Python is virtualenv.

- https://stackoverflow.com/a/50348830/5055465

Unfortunately, explaining how to configure and run virtualenv is beyond the scope of this lib. There are much better resources for more info on that, including the virtualenv's docs and numerous tutorials on google and youtube – i'd recommend to try it, play with it for a week, get used to it, and then configure it how you want for yourself.

There is also a bunch of alternatives to virtualenv:

- https://stackoverflow.com/questions/41573587/what-is-the-difference-between-venv-pyvenv-pyenv-virtualenv-virtualenvwrappe

Hope it helps.

**Comment by sloth456** [comment]
@kroitor Thanks for that, I appreciate your detailed reply!

**Comment by GoChartingAdmin** [comment]
Hi @kroitor, any chance this exchange can be merged into the main branch in 2019 :)

**Comment by kroitor** [comment]
@GoChartingAdmin https://github.com/ccxt/ccxt/pull/6256#issuecomment-568288755

> we are going to review and run the private tests on our side and will hopefully merge it soon and also resolve the integration backlog after releasing CCXT Pro which is just around corner now. Hope to get to is asap.

**Comment by gkarmas** [comment]
Hello any updates on implementing ByBit ?

**Comment by kroitor** [comment]
Bybit is now available in CCXT 1.24.4+ https://github.com/ccxt/ccxt/issues/6612
