### ISSUE TITLE
New Exchange: Tux Exchange

### ISSUE THREAD

**Issue by algomate-jp** [ccxt/ccxt#5073]
https://www.tuxexchange.com/

**Comment by dnlsngr** [comment]
https://github.com/ccxt/ccxt/pull/5176/commits/a61bcf902adca6964be36969465e6f3998e03e80

**Comment by kroitor** [comment]
PR: https://github.com/ccxt/ccxt/pull/5176

**Comment by kroitor** [comment]
https://www.tuxexchange.com/closing

> **Tux Exchange will be closing July 6th, 2019**
>
> Hello Everyone,
>
> Tux Exchange is terminating operations on July 6th 2019, largely due to unfavorable regulatory conditions.
>
> All funds must be withdrawn before July 6th 2019. After that time, we will provide best effort services via support ticket until July 15th 2019 when all services will cease.
> 
> - New signups and deposits are terminated effective immediately.
> - Trading and withdraws will terminate July 6th 2019.
> - Support services will cease July 15 2019.
> 
> It has been a pleasure serving the community and this was not an easy decision.
>
> Thank you for your support and loyalty over the years.
>
> Sincerely,
> Tux Exchange
