### ISSUE TITLE
Workaround when no fetch_ohlcv method available?

### ISSUE THREAD

**Issue by yohplala** [ccxt/ccxt#5076]
Hi,
I would like retrieving historical data from Bitstamp (BTC/USD pair, OHLCV data).
I have actually started by using the python script available on backtest-rookies website:
https://backtest-rookies.com/2018/03/08/download-cryptocurrency-data-with-ccxt/

In this script, fetch_ohlcv method is used to retrieve this data.
However, this function is not available for Bitstamp exchange. (be it bitstamp, or bitstamp1)
I have been through the examples from CCXT Github site, but I have not found one that would suit my need (but maybe I am not really sure what I should look at as workaround on the other hand).
Please, when no fetch_ohlcv is available, what is the recommended solution to get OHLCV data (and more particularly with regard to Bitstamp exchange)?

I thank you in advance for your help.
Best regards,
Yoh

**Comment by kroitor** [comment]
Hi!

Please, check the answers (everything regarding OHLCV emulation) here:

- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-emulation
- https://github.com/ccxt/ccxt/issues/4356
- https://github.com/ccxt/ccxt/issues/3178#issuecomment-410340912
- https://github.com/ccxt/ccxt/issues/3482#issuecomment-407572905
- https://github.com/ccxt/ccxt/issues/2596#issuecomment-381983403
- https://github.com/ccxt/ccxt/issues/4277#issuecomment-449606196
- https://github.com/ccxt/ccxt/search?q=emulation+ohlcv&unscoped_q=understand+emulation+ohlcv&type=Issues

In general, you can build your own OHLCV by reading/receiving recent trades continuously, storing that data and building candles from there.

Let us know if the above does not help )

**Comment by yohplala** [comment]
Hi Igor, ok thanks, I will dive into this and come back if encountering too much troubles.
Thanks for your quick reply. Have a good day. Bests, Yoh
