### ISSUE TITLE
How to launch Python examples properly?

### ISSUE THREAD

**Issue by doepat** [ccxt/ccxt#5080]
hi, just got ccxt installed again. So I downloaded the whole git repo and I changed to the examples forder. try to call an example. yesterday that worked. today i receive:

> pi@raspberrypi:~/Documents/ccxt/examples/py $ python3.6
Python 3.6.3 (default, May  7 2019, 14:39:06) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> arbitrage-pairs.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'arbitrage' is not defined
>>> 

please assist. thank you!

**Comment by frosty00** [comment]
welcome to ccxt kiddo
