### ISSUE TITLE
gateio typo

### ISSUE THREAD

**Issue by nicman23** [ccxt/ccxt#5082]
https://github.com/ccxt/ccxt/blob/87dcaec42343c5fb5c0354d1293d5d9116fe4118/php/gateio.php#L684

should be :
`$response = $this->privatePostDepositsWithdrawals (array_merge ($request, $params));`

**Comment by kroitor** [comment]
Pardon? ) Don't see a typo...

**Comment by kroitor** [comment]
Ah... now I see it...
