### ISSUE TITLE
EthFinex Unknown Markets BTC/USD, LTC/USD, BTC/LTC

### ISSUE THREAD

**Issue by ahmedbodi** [ccxt/ccxt#5085]
- OS: Ubuntu 18.03
- Programming Language version: Node v10
- CCXT version: Latest
- Exchange: Ethfinex
- Method: LoadMarkets

`
Exchange Name: ethfinex
Exchange Markets: [
           'BTC/USD',          'LTC/USD',          'LTC/BTC',          'ETH/USD',
           'ETH/BTC',          'ETC/BTC',          'ETC/USD',          'RRT/USD',
           'RRT/BTC',          'ZEC/USD',          'ZEC/BTC',          'XMR/USD',
           'XMR/BTC',         'DASH/USD',         'DASH/BTC',          'BTC/EUR',
           'BTC/JPY',          'XRP/USD',          'XRP/BTC',         'IOTA/USD',
          'IOTA/BTC',         'IOTA/ETH',          'EOS/USD',          'EOS/BTC',
           'EOS/ETH',          'SAN/USD',          'SAN/BTC',          'SAN/ETH',
           'OMG/USD',          'OMG/BTC',          'OMG/ETH',          'NEO/USD',
           'NEO/BTC',          'NEO/ETH',          'ETP/USD',          'ETP/BTC',
           'ETP/ETH',         'QTUM/USD',         'QTUM/BTC',         'QTUM/ETH',
           'AVT/USD',          'AVT/BTC',          'AVT/ETH',          'EDO/USD',
           'EDO/BTC',          'EDO/ETH',          'BTG/USD',          'BTG/BTC',
          'DATA/USD',         'DATA/BTC',         'DATA/ETH',         'QASH/USD',
          'QASH/BTC',         'QASH/ETH',        'YOYOW/USD',        'YOYOW/BTC',
         'YOYOW/ETH',          'GNT/USD',          'GNT/BTC',          'GNT/ETH',
           'SNT/USD',          'SNT/BTC',          'SNT/ETH',         'IOTA/EUR',
           'BAT/USD',          'BAT/BTC',          'BAT/ETH',         'MANA/USD',
          'MANA/BTC',         'MANA/ETH',          'FUN/USD',          'FUN/BTC',
           'FUN/ETH',          'ZRX/USD',          'ZRX/BTC',          'ZRX/ETH',
           'TNB/USD',          'TNB/BTC',          'TNB/ETH',        'SPANK/USD',
         'SPANK/BTC',        'SPANK/ETH',          'TRX/USD',          'TRX/BTC',
           'TRX/ETH',          'RCN/USD',          'RCN/BTC',          'RCN/ETH',
           'RLC/USD',          'RLC/BTC',          'RLC/ETH',          'AID/USD',
           'AID/BTC',          'AID/ETH',        'SNGLS/USD',        'SNGLS/BTC',
         'SNGLS/ETH',          'REP/USD',          'REP/BTC',          'REP/ETH',
  ... 267 more items
]
ethfinex fetchTicker failed due to exchange error: ethfinex {"message":"Unknown symbol"} BTC/USD
`

**Comment by ahmedbodi** [comment]
Code to reproduce it 
https://gist.github.com/ahmedbodi/2a524f2522c9a49ef2fcfe315186b066

**Comment by Legogris** [comment]
Addressed in #5115
