### ISSUE TITLE
Request timed out (60000 ms) Binance

### ISSUE THREAD

**Issue by viniciussvl** [ccxt/ccxt#5088]
- OS: Windows 10
- Programming Language version: Node.js
- CCXT version: 1.18.507
- Exchange: Binance
- Method: v1/exchangeInfo

Hello everyone, sometimes this timeout error appears, I have already increased to 60 seconds in the exchange options and even then it did not work, does anyone know what it could be? Look at the logs of my robot:

I forgot to mention, my robot is making over 1000 requests per minute using 4 different IPs.

- # Erro Exchange Data
- 4586158 QKC - binance GET https://api.binance.com/api/v1/exchangeInfo request timed out (60000 ms) Binance 09/05/2019 08:46:35
- 4586149 IOTA - binance GET https://api.binance.com/api/v1/exchangeInfo request timed out (60000 ms) Binance 09/05/2019 08:46:34
- 4586138 EOS - binance GET https://api.binance.com/api/v1/exchangeInfo request timed out (60000 ms) Binance 09/05/2019 08:46:33
- 4586137 ZEC - binance GET https://api.binance.com/api/v1/exchangeInfo request timed out (60000 ms) Binance 09/05/2019 08:46:33
- 4586132 OMG - binance GET https://api.binance.com/api/v1/exchangeInfo request timed out (60000 ms) Binance 09/05/2019 08:46:33
- 4586131 WAVES - binance GET https://api.binance.com/api/v1/exchangeInfo request timed out (60000 ms) Binance 09/05/2019 08:46:23
- 4586129 LTC - binance GET https://api.binance.com/api/v1/exchangeInfo request timed out (60000 ms) Binance 09/05/2019 08:46:19
- 4586127 ARDR - binance GET https://api.binance.com/api/v1/exchangeInfo request timed out (60000 ms) Binance 09/05/2019 08:46:18
- 4586097 VIBE - binance GET https://api.binance.com/api/v1/exchangeInfo request timed out (60000 ms) Binance 09/05/2019 08:44:50
- 4586094 WAVES - binance GET https://api.binance.com/api/v1/exchangeInfo request timed out (60000 ms) Binance 09/05/2019 08:44:21
- 4586092 BCD - binance GET https://api.binance.com/api/v1/exchangeInfo request timed out (60000 ms) Binance 09/05/2019 08:44:21
- 4586086 VIBE - binance GET https://api.binance.com/api/v1/exchangeInfo request timed out (60000 ms) Binance 09/05/2019 08:44:19
- 4586078 DGD - binance GET

**Comment by xCuri0** [comment]
@viniciussvl Why would you need over 1000 requests per minute ? It's probably triggering the DDOS protection causing the timeouts

**Comment by xCuri0** [comment]
Why can't you use Websocket instead ?

**Comment by viniciussvl** [comment]
I haver a bot for many users, a loop to check the orders

**Comment by xCuri0** [comment]
@viniciussvl To check the order book ?

**Comment by viniciussvl** [comment]
> @viniciussvl Para verificar o livro de ofertas ?

No, it does not check the book of offers, just search the ticker, candles, analyze the indicators and create or cancel orders. Sorry for the delay in answering.

**Comment by xCuri0** [comment]
@viniciussvl websocket can do that too. You really should be using websocket to do this instead of these weird hacks

**Comment by alexeymarunin** [comment]
Binance returns 429 HTTP-code to alert application/bot about DDOS and 418 HTTP-code to inform about ban ([see](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#general-api-information))

I think that error (timed out) is related to [hacker attack](https://binance.zendesk.com/hc/en-us/articles/360028031711-Binance-Security-Breach-Update) at 7th May. Maybe Binance's servers went down for maintenance 

And yes, @viniciussvl you should use [WebSocket Streams](https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md) to monitor trades or [UserData Streams](https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md) to monitor users orders
