### ISSUE TITLE
Python - Bitfinex V1 edit_limit_sell_order triggers assertion error on precision

### ISSUE THREAD

**Issue by dave7280** [ccxt/ccxt#5090]
- OS: Windows 10
- Programming Language version: Python 3.7.3
- CCXT version: 1.18.514
- Exchange: Bitfinex V1
- Method: edit_limit_sell_order

1. I'm using bitfinex V1
2. I try to create order on BTC/USD using create_limit_sell_order(). Works great, order is added.
3. I try to edit the order by ID using edit_limit_sell_order(self.id, self.asset_symbol, amount, price)
4. I get assertion exception while calling:

```
decimal_to_precision()
assert precision is not None and isinstance(precision, numbers.Integral)
```

The function decimal_to_preicison is receiving "None" as precision argument, therefore assertion is triggered.

https://i.imgur.com/IOdHlOU.png

I traced the place where "precision" variable should come from:

`self.markets[symbol]['precision']['amount']`

Below entire call stack:

https://i.imgur.com/r8Y6SxZ.png

**Comment by benspring** [comment]
Was this ever fixed?
