### ISSUE TITLE
binance api call wapiGetAssetDetail contains useful information

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5104]
I just noticed that the `wapiGetAssetDetail` contains information about the currencies that cloud be added.   Specifically if a currency is suspended or not: 

```
...
NAV:
      { minWithdrawAmount: 0.4,
        depositStatus: false,
        withdrawFee: 0.2,
        withdrawStatus: false,
        depositTip: 'Wallet Maintenance, Deposit and Withdrawal Suspended' },
...
BTM:
      { minWithdrawAmount: 10,
        depositStatus: false,
        withdrawFee: 5,
        withdrawStatus: false,
        depositTip: 'Delisted, Deposit Suspended' },
...
     ATD:
      { minWithdrawAmount: 200,
        depositStatus: false,
        withdrawFee: 100,
        withdrawStatus: false,
        depositTip: 'Contract Frozen, Waiting for Upgrade' },
...
     ETF:
      { minWithdrawAmount: 2,
        depositStatus: false,
        withdrawFee: 1,
        withdrawStatus: false,
        depositTip: 'Waiting for wallet development of ETF team' },
...
     ZIL:
      { minWithdrawAmount: 10,
        depositStatus: false,
        withdrawFee: 0.01,
        withdrawStatus: false,
        depositTip:
         'Mainnet Token Swap, Mainnet coin Deposit and Withdrawl Suspended. If you need to deposit ERC20 ZIL tokens, please send to your existing ETH deposit address. Tokens will be automatically converted to Mainnet.' }
```

**Comment by kroitor** [comment]
@npomfret yep, we have it wrapped in [`fetchTradingFees`](https://github.com/ccxt/ccxt/blob/master/js/binance.js#L1154), but not this particular flag yet, will unify this under some helper. Unfortunately, it requires apiKeys, so, it has to be unified in the private part, so we can't add it to `fetchCurrencies` right away (it's public-only), but we will figure it out, i hope.

**Comment by npomfret** [comment]
Perhaps we augment the currency data if the API keys are present.

**Comment by kroitor** [comment]
@npomfret 

> Perhaps we augment the currency data if the API keys are present.

With key-specific permissions it won't work seamlessly across all exchanges. So, we think a better way would be to provide `loadTradingFees` just like we do with `loadTradingLimits` (as well as `loadFundingFees`, `loadFundingLimits`, etc.).

**Comment by frosty00** [comment]
deprecated api
