### ISSUE TITLE
New Exchange: Btron

### ISSUE THREAD

**Issue by rayston92** [ccxt/ccxt#5105]
Btron is an exchange based in UK.

API Doc: https://www.btron.com/docs
URL: https://www.btron.com
Fee: https://btron.zendesk.com/hc/en-us/articles/360008011374
Volume: https://www.feixiaohao.com/exchange/btron/
Based Country: UK

**Comment by rayston92** [comment]
Please let me know if there is anything I should do to help support Btron.com API.
DM me or send email to me: wl@btron.com

**Comment by rayston92** [comment]
@kroitor

**Comment by An-Net** [comment]
Shutdown:

- https://twitter.com/btron19/status/1148807819375697920
