### ISSUE TITLE
Implement fetchDepositAddress for Okex

### ISSUE THREAD

**Issue by denarioresearch** [ccxt/ccxt#5113]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by kroitor** [comment]
@denarioresearch hitbtc2 (v2) has `fetchDepositAddress` implemented already.
