### ISSUE TITLE
bitstamp parse order incorrect amount

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5121]
The fetchOrder call produces:

```
{
  "id": 468646390,
  "status": "Canceled",
  "transactions": [
    {
      "eth": "0.23000000",
      "fee": "0.09",
      "tid": 25810126,
      "usd": "69.8947000000000000",
      "type": 2,
      "price": "303.89000000",
      "datetime": "2017-11-11 07:22:20.710567"
    }
  ]
}
```

or

```
{
  "id": 469546793,
  "status": "Finished",
  "transactions": [
    {
      "eth": "0.50000000",
      "eur": "128.9000000000000000",
      "fee": "0.17",
      "tid": 25842725,
      "type": 2,
      "price": "257.80000000",
      "datetime": "2017-11-11 13:34:39.936271"
    }
  ]
}
```

The `parseOrder` method fills in an amount field for the "Finished" order only, the other is _undefined_.

This api call doesn't show the order amount, they should both be _undefined_ IMO.

Also, it is possible to calculate the _average_ price from the transactions.

**Comment by kroitor** [comment]
It depends on the callchain, their responses differ depending on the endpoint in question, can you please post the code to reproduce it? Which unified method is it?
