### ISSUE TITLE
Bitfinex ETP/BTC CreateOrder Error

### ISSUE THREAD

**Issue by turnyay** [ccxt/ccxt#5125]
ETP/BTC recently reached an exchange rate of < 0.0001 BTC/ETP, and PHP converts to scientific notation causing the following error:
```
ccxt\bitfinex->create_order('ETP/BTC', 'limit', 'sell', 12.86404443, '0.00009864')
...
ccxt\InvalidOrder: bitfinex {"message":"Key price should be a decimal number, e.g. \"123.456\""}
```

Has anyone else encountered this issue? I have a temporary patch on my local version, but it would be great if this could be fixed in the next release. Thanks

- OS: linux
- Programming Language version: PHP
- CCXT version: 1.18.497
- Exchange: Bitfinex
- Method: create_order

**Comment by kroitor** [comment]
@turnyay hi! Can you please post your [**verbose request/response**](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue)?
