### ISSUE TITLE
hitbtc2 hard coded withdrawal fees can be replaced

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5134]
hitbtc2 hard coded withdrawal fees can be replaced using this: https://api.hitbtc.com/api/2/public/currency, eg:

```
{
id: "DDF",
fullName: "DDF",
crypto: true,
payinEnabled: false,
payinPaymentId: false,
payinConfirmations: 2,
payoutEnabled: true,
payoutIsPaymentId: false,
transferEnabled: true,
delisted: false,
payoutFee: "646",
}
```

**Comment by kroitor** [comment]
We're using the above info here https://github.com/ccxt/ccxt/blob/master/js/hitbtc2.js#L643 and we are going to drop hardcoded fees for `hitbtc2` soon. 

Let us know if that doesn't answer the issue. Thx!
