### ISSUE TITLE
Please remove  var_dump ($params);

### ISSUE THREAD

**Issue by lexaboss** [ccxt/ccxt#5136]
Please remove 
```
var_dump ($params);
```
from Exchange.php line:L1571

- OS: Debian GNU/Linux 9.9 (stretch)
- Programming Language version:PHP 7.1.29-1+0~20190503101539.18+stretch~1.gbp946c98 (cli) (built: May  3 2019 10:15:39) ( NTS )
- CCXT version: 1.18.489
- Exchange: Binance
- Method: Withdraw

**Comment by kroitor** [comment]
Fixed in 1.18.533, thx for reporting and for your attention!
