### ISSUE TITLE
Question Is there a way to have multiple accounts on node.js? 

### ISSUE THREAD

**Issue by amigoni** [ccxt/ccxt#5139]
Hi,
I'm trying to run multiple accounts for orders. Specifically with Binance on Node.js. Is there a way to have multiple instances of ccxt running? Is this trivial or there will be some issues? 

Thanks

**Comment by xpl** [comment]
You would need to create a wrapper that will manage multiple accounts — one ccxt class instance per apikey+secret pair. I can see no issues except rate limiting, as most exchanges limit API calls rate per IP address and not [only] per keypair.

**Comment by xpl** [comment]
@amigoni Let us know if that didn't help, I'm closing the issue for now.
