### ISSUE TITLE
Kucoin createDepositAddress typeError

### ISSUE THREAD

**Issue by denarioresearch** [ccxt/ccxt#5145]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES:

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: ubuntu 
- Programming Language version: nodejs
- CCXT version: 1.18.545
- Exchange: kucoin
- Method: createDepositAddress
```
kucoin.createDepositAddress(coin).then(data=>{
	console.log(data)
}).catch(e=>{console.log(e)})
```

Output
_TypeError: Cannot read property 'replace' of undefined
    at kucoin.createDepositAddress (/home/node/Projects/test/node_modules/ccxt/js/kucoin.js:511:27)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)_

This error happens for the most of coins

**Comment by kroitor** [comment]
@denarioresearch can you please post your verbose output as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

```
kucoin.loadMarkets ().then (() => {
    kucoin.verbose = true // ←----- add this before calling createDepostAddress
    kucoin.createDepositAddress(coin).then(data=>{
        console.log(data)
    }).catch(e=>{console.log(e)})
})
```


})

**Comment by denarioresearch** [comment]
It works with loadMarkets first. In the first case I did not add loadMarkets
```
fetch:
 kucoin GET https://openapi-v2.kucoin.com/api/v1/deposit-addresses?currency=CXO 
Request:
 { 'KC-API-KEY': '<KEY>',
  'KC-API-TIMESTAMP': '1558335380918',
  'KC-API-PASSPHRASE': '<password>',
  'KC-API-SIGN': '<SIGN>' } 
 undefined 

handleRestResponse:
 kucoin GET https://openapi-v2.kucoin.com/api/v1/deposit-addresses?currency=CXO 200 OK 
Response:
 { Date: 'Mon, 20 May 2019 06:56:24 GMT',
  'Content-Type': 'application/json;charset=UTF-8',
  'Transfer-Encoding': 'chunked',
  Connection: 'close',
  'Set-Cookie':
   'SESSION=<Session>; Max-Age=604800; Expires=Mon, 27-May-2019 06:56:24 GMT; Domain=kucoin.com; Path=/; Secure; HttpOnly',
  Server: 'nginx',
  'X-Trace-Id': 'efabd14f84ac800',
  'X-Content-Type-Options': 'nosniff',
  'X-Xss-Protection': '1; mode=block',
  'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
  Expires: '0',
  'X-Frame-Options': 'DENY',
  'Weight-Interval': 'SECOND',
  'Weight-Expire': '1558335432',
  'Weight-Limit': '1800',
  'Weight-Remain': '1794',
  'Strict-Transport-Security': 'max-age=9800; includeSubDomains; preload' } 
 {"code":"200000","data":{"address":"<ADDR>","memo":""}} 

```
Thanks

**Comment by kroitor** [comment]
> It works with loadMarkets first. In the first case I did not add loadMarkets

It has the `loadMarkets()` inside, so you should not have added it...

- https://github.com/ccxt/ccxt/blob/master/js/kucoin.js#L502
- https://github.com/ccxt/ccxt/blob/master/js/kucoin.js#L525

Therefore this must be some different reason. Are you sure that the version, you've been using previously was 1.18.545?
