### ISSUE TITLE
okex3 code bug

### ISSUE THREAD

**Issue by selfrefresh** [ccxt/ccxt#5146]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: centos
- Programming Language version: python 3.*
- CCXT version:1.18.547
- Exchange: okex3
- Method: 1461 row。it should be “ futures”，be from load_markets() result.

**Comment by selfrefresh** [comment]
File /usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py, line 1542, in create_limit_buy_order,     return self.create_order(symbol, limit, buy, *args),   File /usr/local/lib/python3.7/site-packages/ccxt/okex3.py, line 1461, in create_order,     if market[future] or market[swap]:, KeyError: future]

**Comment by kroitor** [comment]
Thank you for reporting! This is fixed in 1.18.548, the new build will arrive in 5-10 minutes. Let us know if you have further difficulties with it. Thx!

**Comment by selfrefresh** [comment]
Waiting for your upgrade, relying on your upgrade
