### ISSUE TITLE
okex code bug

### ISSUE THREAD

**Issue by selfrefresh** [ccxt/ccxt#5147]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:centos 
- Programming Language version: python 3.*
- CCXT version: 1.18.548
- Exchange: okex3
- Method: parse_order

amount = self.safe_float(order, 'size')
        filled = self.safe_float_2(order, 'filled_size', 'filled_qty')
        amount = max(amount, filled)

Max will report an error when both the amount and the filled are none

![image](https://user-images.githubusercontent.com/4022594/58007873-c3c13d00-7b1d-11e9-987a-e755bb988cec.png)

**Comment by selfrefresh** [comment]
File /usr/local/lib/python3.7/site-packages/ccxt/okex3.py, line 1906, in fetch_open_orders,     return self.fetch_orders_by_state(6, symbol, since, limit, params),   File /usr/local/lib/python3.7/site-packages/ccxt/okex3.py, line 1894, in fetch_orders_by_state,     return self.parse_orders(orders, market, since, limit),   File /usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py, line 1409, in parse_orders,     array = [self.parse_order(order, market) for order in array],   File /usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py, line 1409, in <listcomp>,     array = [self.parse_order(order, market) for order in array],   File /usr/local/lib/python3.7/site-packages/ccxt/okex3.py, line 1690, in parse_order,     amount = max(amount, filled), TypeError: > not supported between instances of NoneType and NoneType]

**Comment by selfrefresh** [comment]
@kroitor When will the new version be released

**Comment by kroitor** [comment]
@selfrefresh as always, the automatic build takes 5-10 minutes.
