### ISSUE TITLE
okex create_order error_code 10008

### ISSUE THREAD

**Issue by selfrefresh** [ccxt/ccxt#5148]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:centos
- Programming Language version: python 3.*
- CCXT version: 1.18.550
- Exchange: okex
- Method: spot create_order Place the order failed

**Comment by selfrefresh** [comment]
File /home/centos/blockchain_spot_trade/common/util.py, line 651, in set_buy_order,     buy_set_rst = obj.create_limit_buy_order(symbol, qty, price),   File /usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py, line 1542, in create_limit_buy_order,     return self.create_order(symbol, limit, buy, *args),   File /usr/local/lib/python3.7/site-packages/ccxt/okcoinusd.py, line 746, in create_order,     response = getattr(self, method)(self.extend(request, params)),   File /usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py, line 404, in inner,     return entry(_self, **inner_kwargs),   File /usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py, line 433, in request,     return self.fetch2(path, api, method, params, headers, body),   File /usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py, line 429, in fetch2,     return self.fetch(request[url], request[method], request[headers], request[body]),   File /usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py, line 532, in fetch,     self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response),   File /usr/local/lib/python3.7/site-packages/ccxt/okcoinusd.py, line 1016, in handle_errors,     raise ExceptionClass(message), ccxt.base.errors.ExchangeError: okex {
esult:false,error_code:10008}]

**Comment by kroitor** [comment]
@selfrefresh can you please post the verbose output precisely as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

**Comment by selfrefresh** [comment]
Request: POST https://www.okex.com/api/v1/trade.do {'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} amount=10&api_key=9b1666da-f33a-47dc-a1f5-82bb40dc5507&price=5.8536&symbol=eos_usdt&type=False&sign=1B259D7E73EAAC0AE49F1F687CA10440


type = False?

Is there a problem with the code here？

![image](https://user-images.githubusercontent.com/4022594/58020211-14469380-7b3a-11e9-8bb9-b013e5708487.png)

**Comment by selfrefresh** [comment]
![image](https://user-images.githubusercontent.com/4022594/58020234-288a9080-7b3a-11e9-8cd0-ce574da28ad1.png)

**Comment by kroitor** [comment]
> Is there a problem with the code here？

Yes, there was a problem, due to how transpilation works in this project: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support. I've added a fix for it, the new build will arrive in 10 minutes. We will be happy if you report back whether it resolves the issue for you not. Thank you!
