### ISSUE TITLE
[bibox] bibox does not have market symbol ...

### ISSUE THREAD

**Issue by bjatwork** [ccxt/ccxt#5150]
I started receiving messages like 
[Exchange Error] bibox does not have market symbol ATOM/ETH 
... for all symbols. 

Something broke down on that exchange?

**Comment by ndubel** [comment]
yes. same here. They have some system upgrade, may be it's related. https://twitter.com/Bibox365

**Comment by kroitor** [comment]
A few more links:

- https://medium.com/@biboxexchange/explanations-on-bibox-system-upgrade-issues-b1ed2261a010
- https://twitter.com/Bibox365/status/1130392134329090048

**Comment by kroitor** [comment]
I suggest to move this discussion here: https://github.com/ccxt/ccxt/issues/5150
