### ISSUE TITLE
dx exchange fetch_order_book not working

### ISSUE THREAD

**Issue by blaaaaaaa** [ccxt/ccxt#5160]
dx fetch_order_book not working/broken
>>> import ccxt
>>> dx = ccxt.dx()
>>> dx.fetch_order_book("ADA/BTC")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'dx' object has no attribute 'fetch_order_book'

- OS:win10
- Programming Language version:python 3.6.6
- CCXT version:1.18.558
- Exchange:dx
- Method:fetch_order_book

**Comment by kroitor** [comment]
@blaaaaaaa it is designated in the [`has` metadata](https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata):

```
import ccxt
from pprint import pprint
pprint(ccxt.dx().has)
``` 

They don't have a corresponding endpoint due to how the exchange works. I think @brandsimon can add more to this. Let us know if that doesn't answer the question.

**Comment by blaaaaaaa** [comment]
So in the doc it states it is not implemented, but in the telegram chat they said API is complete, and the example code is working. so this works for me on win10 command line: 
curl --location --request POST "https://acl.dx.exchange" --header "Content-Type: application/json-rpc" --data "{\"jsonrpc\": \"2.0\",\"id\" : 1,\"method\": \"OrderManagement.GetOrderBook\",\"params\": [{\"instrumentId\": 1026}]}"

this is the result:
{"id":"1","result":{"sell":[{"price":{"value":1061,"decimals":8},"qty":{"value":2177,"decimals":1}},{"price":{"value":948,"decimals":8},"qty":{"value":28312,"decimals":1}},{"price":{"value":987,"decimals":8},"qty":{"value":32084,"decimals":1}},{"price":{"value":1034,"decimals":8},"qty":{"value":92831,"decimals":1}},{"price":{"value":1054,"decimals":8},"qty":{"value":55538,"decimals":1}},{"price":{"value":968,"decimals":8},"qty":{"value":31507,"decimals":1}},{"price":{"value":1,"decimals":5},"qty":{"value":2000,"decimals":0}},{"price":{"value":1002,"decimals":8},"qty":{"value":32733,"decimals":1}},{"price":{"value":1023,"decimals":8},"qty":{"value":95756,"decimals":1}}],"buy":[{"price":{"value":1182,"decimals":8},"qty":{"value":10319,"decimals":1}},{"price":{"value":126,"decimals":7},"qty":{"value":2000,"decimals":0}},{"price":{"value":1115,"decimals":8},"qty":{"value":10891,"decimals":1}},{"price":{"value":115,"decimals":7},"qty":{"value":2000,"decimals":0}},{"price":{"value":1122,"decimals":8},"qty":{"value":20118,"decimals":1}},{"price":{"value":1136,"decimals":8},"qty":{"value":7739,"decimals":1}},{"price":{"value":1164,"decimals":8},"qty":{"value":3652,"decimals":1}},{"price":{"value":117,"decimals":7},"qty":{"value":1000,"decimals":0}},{"price":{"value":1207,"decimals":8},"qty":{"value":12244,"decimals":1}},{"price":{"value":1087,"decimals":8},"qty":{"value":3552,"decimals":1}},{"price":{"value":11,"decimals":6},"qty":{"value":1000,"decimals":0}}]},"error":null}

so it should translate to: 
ccxt_style_price = price[value] * 10^price[decimals]
ccxt_style_amount = amount[value] * 10^amount[decimals]

So I think it is possible for a capable coder to implement that, unfortuantely I am not capable.
Open Orders might be possible as well? https://apidocs.dx.exchange/?version=latest#146f4cb0-eb05-4866-9aec-c5184f749427

**Comment by kroitor** [comment]
@blaaaaaaa got it, thx for the followup on this! We will add it asap! 

@brandsimon your help on that would be appreciated a lot! )

**Comment by brandsimon** [comment]
@blaaaaaaa @kroitor 
Yes, I will implement the order book, I think I have time for this next week.
fetchOpenOrders is already implemented, the information in has is not correct, I will fix it.

**Comment by kroitor** [comment]
@brandsimon thx so much for getting back to us! That's some great news!) Let me know if anything.
