### ISSUE TITLE
Bibox service unavailable after the upgrade on the exchange side

### ISSUE THREAD

**Issue by Krisonerrr** [ccxt/ccxt#5164]
Bibox just finished a system upgrade and now all /transfer requests are returning: ccxt.base.errors.ExchangeNotAvailable: bibox https://api.bibox.com/v1/transfer POST 503 Server Error: Service Unavailable for url: https://api.bibox.com/v1/transfer
Basically, now all /transfer requests need to use version "v2", while all other requests use "v1"

**Comment by kroitor** [comment]
Hi! Thx for the feedback! We'll move to their v2 as soon as we can.

**Comment by bjatwork** [comment]
@kroitor can you say if you are working on that integration ? I don't know if  exclude this change or wait for integration .

**Comment by kroitor** [comment]
@bjatwork https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar

**Comment by kroitor** [comment]
I've just tested bibox with the most recent version and it works from my location. Let us know if you still have difficulties with it, however, in case of a problem, please, make sure to include a complete report: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
