### ISSUE TITLE
Binance missing method

### ISSUE THREAD

**Issue by ibesora** [ccxt/ccxt#5168]
- Programming Language: JS
- CCXT version: Latest
- Exchange: Binance
- Method: - 

The API documentation points to a method to [get historical trades](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#old-trade-lookup-market_data) but it's nowhere to be found on CCXT.

**Comment by kroitor** [comment]
Hi!

Thx for reporting! We have it added it )

1. Wait 10 minutes for the new build to arrive
2. Update to the most recent version 1.18.565
3. Run this:

```JavaScript
const ccxt  = require ('ccxt')
const exchange = new ccxt.binance ({
    'options': {
        'fetchTradesMethod': 'publicGetHistoricalTrades'
    },
})

;(async () => {
    // these args are optional
    // const limit = 500 // max 1000
    // params = {
    //     'fromId': 'some-id'
    // }
    const trades = exchange.fetchTrades ('ETH/BTC')
    // const trades = exchange.fetchTrades (symbol, undefined, limit, params)
}) ()
```

Let us know if that doesn't answer the question ;)
