### ISSUE TITLE
Bitmex Rate Limit changes

### ISSUE THREAD

**Issue by p0nt** [ccxt/ccxt#5179]
Based on the following blog page it looks like BitMEX have changed their rate limit policy, due to this the build in ccxt rate limit function is not working properly anymore.

https://blog.bitmex.com/api_announcement/upcoming-change-in-rate-limits/

The rate limit does not start at 300 anymore, but at 60.

Tried finding the issue in the code, couldnt find it yet.

**Comment by kroitor** [comment]
> Tried finding the issue in the code, couldnt find it yet.

This is configured here: https://github.com/ccxt/ccxt/blob/master/js/bitmex.js#L18

Also, check out this: 

- https://github.com/ccxt/ccxt/issues/1399#issuecomment-359233015
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

Let me know if that doesn't answer the question.
