### ISSUE TITLE
Transaction fees – net or gross?

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5181]
Should the amount in the transfer (for withdrawals) be equal to the amount the receiver receives (ie net of withdrawal fees), or should it be the gross amount (so the receiver should receive `amount - fee.cost`)?

**Comment by npomfret** [comment]
Regardless of what the answer is, there may be a bug in polonium.  In this XRp withdrawal example the data is:

```
amount: 501.10000007,
info:
      { fee: '0.15000000',
        type: 'withdrawal',
        amount: '501.25000007',
        status:
         'COMPLETE: 1419A5E5D66AE500DE8CF7BB1255B954C71C17F21E07CB9D031C9ABC2FB317ED',
        address: 'rK1MAqAbK6S64rQZCcfQnWSR9cCvotSC5u',
```

But the receiver received `501.25`... so more was receive than was sent.

**Comment by kroitor** [comment]
@npomfret 

> be equal to the amount the receiver receives (ie net of withdrawal fees)

The balance of the sender should be deduced by the `amount` and the `fee` and the receiver should receive the `amount`.

Is it so for all your withdrawals or for this particular one? It looks like a very old one Jan 2018, and the arithmetics for fees may have changed over time. We will review Poloniex again though.

**Comment by npomfret** [comment]
> Is there a problem with all your withdrawals or for this particular one?

Good question.  Poloniex looks inconsistent.  Here's a more recent one:

```
{
  "fee": "0.01000000",
  "type": "withdrawal",
  "amount": "10.44581161",
  "status": "COMPLETE: 0x16ec0102bcade18fe5e7c4b5e0b03562c5be91e2b6a926738215bbd75c89c0b0",
  "address": "0x15c9f7Cfcee1696FaF58528E8aBd740908b8e830",
  "currency": "ETH",,...
```

And the _correct_ amount (10.43581161) was received.  I've looked a load more examples and other than rounding issues I can't find another one that looks wrong.

**Comment by kroitor** [comment]
@npomfret thx for reporting back! Really appreciate your comments, always very helpful!

**Comment by npomfret** [comment]
@kroitor  I just wanted to check what the net/gross fee *should* be for withdrawals, as I think we still have inconsistencies.

So we have fee and a fee...

Does the user's balance reduce by `amount + fee`?  Which implies the destination receives the `amount`.

Or, does the user's balance reduce by `amount`?  Which implied the destination receives the `amount - fee`.

I thought it was the latter.

**Comment by kroitor** [comment]
> Does the user's balance reduce by `amount + fee`? Which implies the destination receives the `amount`.
> Or, does the user's balance reduce by `amount`? Which implied the destination receives the `amount - fee`.
> I thought it was the latter (but from what i've checked today, the former appears to be more common)

This is not fully unified yet. Some exchanges will deduce the fee from the amount, other exchanges will charge the fee on top of the amount. I think it's better to make transaction `amount` reflect the value that will be deposited on the receiving side – that helps match withdrawals with deposits across exchanges. However, in case of exmo and poloniex we deduce the fee cost from the amount, that depends on which specific value is returned from the exchange in the `amount` field.

**Comment by npomfret** [comment]
Ok thanks

So we need to subtract the fee cost from the amount for btcmarkets too then.  Currently they don't add up.
