### ISSUE TITLE
php btcalpha error on fetch_tickers

### ISSUE THREAD

**Issue by crackfoo** [ccxt/ccxt#5182]
- OS: ubuntu 16.04
- Programming Language version: php
- CCXT version: 1.18.569
- Exchange: btcalpha
- Method: fetch_ticker

`` fetch_ticker method not found, try underscore_notation instead of camelCase for the method being called``

Seeing this error trying to use btc-alpha exchange.

**Comment by frosty00** [comment]
Look in:

```
$btcaphla->has['fetchTicker']
```

In other words it's not implemented...

**Comment by kroitor** [comment]
@crackfoo more info about it here: https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata. Let us know if that doesn't help.
