### ISSUE TITLE
Coinbase Pro/GDAX fetchDepositAddress is actually createDepositAddress

### ISSUE THREAD

**Issue by evan-coygo** [ccxt/ccxt#5183]
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Linux Mint
- Programming Language version: JS
- CCXT version: 1.18.570
- Exchange: Coinbase Pro/GDAX
- Method: fetchDepositAddress

Coinbase Pro method `fetchDepositAddress` actually creates a new address each time its called. I believe this should be the implementation of `createDepositAddress` (which is not currently implemented on Coinbase Pro), and `fetchDepositAddress` should retrieve the existing address.

**Comment by evan-coygo** [comment]
here is the api docs for listing addresses https://developers.coinbase.com/api/v2#list-addresses
and creating addresses (which is what's currently being done) https://developers.coinbase.com/api/v2#create-address

it looks like some Coinbase Pro docs just delegate to regular Coinbase methods as they share some of the same API

**Comment by kroitor** [comment]
@evan-coygo thx for the info, and for reporting this! Will fix it shortly!

**Comment by evan-coygo** [comment]
hey @kroitor, I'm trying to use this on the latest release 1.18.678 and I'm getting a 403. Other methods work fine with my current API key (fetch balances, fetch order history, get ticker) but getDepositAddress gives:

```
coinbasepro GET https://api.pro.coinbase.com/coinbase-accounts/<my btc account id>/addresses 403 Forbidden {"message":"Forbidden"} (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)
```

the Coinbase Pro status page doesn't show any issues related to this at the moment, and the same API key was working with the previous implementation

**Comment by kroitor** [comment]
Hi @evan-coygo ! Please, see the discussion here: https://github.com/ccxt/ccxt/issues/5233#issuecomment-498855312
