### ISSUE TITLE
'publicGetKlines' exchange method

### ISSUE THREAD

**Issue by wajihmsedi** [ccxt/ccxt#5188]
- OS: windows 7
- Programming Language version: python 3.5
- CCXT version: 1.18.572
- Exchange:binance 
- Method: 'publicGetKlines'

Hello I am passing an exchange to a method to Pull data in a multiprocessing wrapper :

def pull_data_init(exchange,crypto) :
    dayofworkms = 1523937720000
    header = ['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume']
    data = exchange.fetch_ohlcv(crypto,'1m',since=dayofworkms,limit=None)

But I keep getting the same error :

AttributeError: 'binance' object has no attribute 'publicGetKlines'

**Comment by kroitor** [comment]
@wajihmsedi hi!

Does it work this way?:

```Python
import ccxt
from pprint import pprint
exchange = ccxt.binance({
    'enableRateLimit': True,
})
symbol = 'ETH/BTC'
ohlcv = exchange.fetch_ohlcv(symbol, '1m', 1523937720000)
pprint(ohlcv)
pprint('CCXT ' + ccxt.__version__)
```

↑ If that works and your code doesn't, then make sure that there is no error in the code that you haven't posted (the code around `pull_data_init`).

Let us know if that doesn't answer the question. Feel free to reopen this if needed or just ask further, will be happy to help.

**Comment by wajihmsedi** [comment]
No It does not.
Actually here is what happen.
I generate first a tuple sequence with exchange and currency pairs :

seq = tuple((exchanges[id],crypto) for id in exchanges.keys() for crypto in exchanges[id].symbols )

And I pass it then to pool :

pool.starmap(pull_data_init, seq)

If I pick an instance from seq fetch_ohlcv still does work so the problem intervene only when it is passed to pull_data_init.

**Comment by wajihmsedi** [comment]
@kroitor I can't reopen the issue.

**Comment by kroitor** [comment]
@wajihmsedi can you please post a complete program 5-20 lines to reproduce it? Without seeing the entire code we can only guess... We need it to be a complete short snippet, please make it as short as possible and remove all the irrelevant parts from it leaving just the minimal code to reproduce it (but please make it a complete short program, don't throw away the parts of the code that is relevant – the easiest way to do it to cut away lines one by one until you're left with a single small script that demonstrates the issue). Please use markup formatting for readability and follow the guides from here precisely: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by kroitor** [comment]
> No It does not.

Are you sure that this ↓ does not work? Because it does work on my system:

```Python
import ccxt
exchange = ccxt.binance({
    'enableRateLimit': True,
})
symbol = 'ETH/BTC'
ohlcv = exchange.fetch_ohlcv(symbol, '1m', 1523937720000)
print(len(ohlcv), 'candles')
print('CCXT ' + ccxt.__version__)
```

<img width="485" alt="Screen Shot 2019-05-24 at 17 36 44" src="https://user-images.githubusercontent.com/1294454/58335573-8674ec00-7e4a-11e9-9a3a-eaf8eda7c144.png">

**Comment by wajihmsedi** [comment]
import time
import numpy as np
import ccxt
import pandas as pd
from multiprocessing import Pool
import multiprocessing
import math
import pprint as pp

def pull_data_init(exchange,crypto) :
    dayofworkms = 1523937720000
    header = ['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume']
    try:
        data = exchange.fetch_ohlcv(crypto,'1m',since=dayofworkms,limit=None)
        df = pd.DataFrame(data, columns=header)
        df['Timestamp'] = pd.to_datetime(df['Timestamp'], unit='ms')
        df['Timestamp'] = df['Timestamp'].dt.strftime('%Y%m%d %H%M')
        df.to_csv(r'E:\\CRYPTO\\' + exchange.name + '\\' + crypto.split('/')[0] + '\\' + 'data_' + crypto.split('/')[
            1] + '.csv', index=False)
    except:
        pass

if __name__ == "__main__":
    start = time.time()
    exchanges = {}
    excluded_exchanges =['FCoin','BTC-Alpha','KuCoin','Ethfinex','Huobi Pro','Bit-Z','Bitlish','ZB','Bitfinex','HitBTC','Upbit','Bittrex']
    for id in ccxt.exchanges:
        pp.pprint('EXCHANGE '+id)
        exchange = getattr(ccxt, id)
        try :
            exchange=exchange()
        except :
            pp.pprint('NO () FOR ' + id)
            continue
        if exchange.has["fetchOHLCV"]==True & hasattr(exchange,'name'):
            if exchange.name in 'Binance':
                try:
                    exchange.load_markets()
                    exchange.enableRateLimit = True
                    exchanges[id] = exchange
                except:
                    pp.pprint('NO LOAD MARKETS FOR '+exchange.name)
                continue
            # exchange.enableRateLimit = True
            # exchange.rateLimit = 2*exchange.rateLimit
            # exchange.timeout = 10000
    pool = Pool(processes=multiprocessing.cpu_count())
    seq = tuple((exchanges[id],crypto) for id in exchanges.keys() for crypto in exchanges[id].symbols )
    pool.starmap(pull_data_init, seq)
    pool.close()
    pool.join()
    print('Done in ' + str(time.time() - start) + ' seconds!')

**Comment by wajihmsedi** [comment]
import time
import numpy as np
import ccxt
import pandas as pd
from multiprocessing import Pool
import multiprocessing
import math
import pprint as pp

def pull_data_init(exchange,crypto) :
    dayofworkms = 1523937720000
    header = ['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume']
    try:
        data = exchange.fetch_ohlcv(crypto,'1m',since=dayofworkms,limit=None)
        df = pd.DataFrame(data, columns=header)
        df['Timestamp'] = pd.to_datetime(df['Timestamp'], unit='ms')
        df['Timestamp'] = df['Timestamp'].dt.strftime('%Y%m%d %H%M')
        df.to_csv(r'E:\\CRYPTO\\' + exchange.name + '\\' + crypto.split('/')[0] + '\\' + 'data_' + crypto.split('/')[
            1] + '.csv', index=False)
    except:
        pass

if __name__ == "__main__":
    start = time.time()
    exchanges = {}
    excluded_exchanges =['FCoin','BTC-Alpha','KuCoin','Ethfinex','Huobi Pro','Bit-Z','Bitlish','ZB','Bitfinex','HitBTC','Upbit','Bittrex']
    for id in ccxt.exchanges:
        pp.pprint('EXCHANGE '+id)
        exchange = getattr(ccxt, id)
        try :
            exchange=exchange()
        except :
            pp.pprint('NO () FOR ' + id)
            continue
        if exchange.has["fetchOHLCV"]==True & hasattr(exchange,'name'):
            if exchange.name in 'Binance':
                try:
                    exchange.load_markets()
                    exchange.enableRateLimit = True
                    exchanges[id] = exchange
                except:
                    pp.pprint('NO LOAD MARKETS FOR '+exchange.name)
                continue
            # exchange.enableRateLimit = True
            # exchange.rateLimit = 2*exchange.rateLimit
            # exchange.timeout = 10000
    pool = Pool(processes=multiprocessing.cpu_count())
    seq = tuple((exchanges[id],crypto) for id in exchanges.keys() for crypto in exchanges[id].symbols )
    pool.starmap(pull_data_init, seq)
    pool.close()
    pool.join()
    print('Done in ' + str(time.time() - start) + ' seconds!')

**Comment by wajihmsedi** [comment]
@kroitor I pasted the code.
Yes the snippet work if I replace pprint by print for the candles.
I have got 500 candles and CCXT 1.18.572 for the version.

**Comment by kroitor** [comment]
@wajihmsedi you should create the exchange instance inside the thread worker function, not outside of it (don't pass it into the other process, because the memory is not shared that easily – google more about shared memory with processes).

Also, you cannot launch a parallel scan over all symbols at once without adding rate-limiting synchronized between your processes, otherwise the exchange will ban you out quickly for making too many simultaneous requests at once. The rate-limiter in CCXT is still experimental and it does not support the multiprocess mode. More about it here: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit and here: #1399

So, I suggest to read a bit more about multiprocessing and how the memory and objects are shared between processes and then somewhat rethink your design and architecture.

There's also very little sense in outputting all results unsorted to the screen while they come with varying response lags and networking delays. You will get a mess of info on the screen very quickly.

So, the proper way to do it, is to either learn more about the multiprocessing stuff or drop it from this snippet and do it in sequential mode like so:

Here's a working and a properly rate-limited example:

```Python
import time
import ccxt
import math
import numpy as np
import pprint as pp
import pandas as pd
from multiprocessing import Pool, cpu_count


def pull_data_init(exchange_id, exchange_id2):
    exchange = getattr(ccxt, exchange_id) ({ 'enableRateLimit': True })
    if exchange.has["fetchOHLCV"]!=True:
        return
    exchange.load_markets ()
    dayofworkms = 1523937720000
    header = ['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume']
    for symbol in exchange.symbols:
        market = exchange.markets[symbol]
        try:
            data = exchange.fetch_ohlcv(symbol,'1m',since=dayofworkms)
            print(exchange_id, symbol, 'done')
            df = pd.DataFrame(data, columns=header)
            df['Timestamp'] = pd.to_datetime(df['Timestamp'], unit='ms')
            df['Timestamp'] = df['Timestamp'].dt.strftime('%Y%m%d %H%M')
            df.to_csv(r'E:\\CRYPTO\\' + exchange.name + '\\' + market['base'] + '\\' + 'data_' + market['quote'] + '.csv', index=False)
        except:
            pass


if __name__ == "__main__":
    start = time.time()
    exchanges = [ 'binance', 'bittrex' ]
    seq = tuple((id, id) for id in exchanges)
    pool = Pool(processes=cpu_count())
    pool.starmap(pull_data_init, seq)
    pool.close()
    pool.join()
    print('Done in ' + str(time.time() - start) + ' seconds!')
```

<img width="1502" alt="Screen Shot 2019-05-24 at 20 43 58" src="https://user-images.githubusercontent.com/1294454/58346850-d2cd2580-7e64-11e9-9355-a3fe44e43d37.png">

See this duplicate issue: https://github.com/ccxt/ccxt/issues/4921

**Comment by wajihmsedi** [comment]
Thanks @kroitor for your reply. Not related question. Is there a list of exchange which implements margin trading in their api ?

**Comment by hubuser3976** [comment]
> Thanks @kroitor for your reply. Not related question. Is there a list of exchange which implements margin trading in their api ?

Hi @wajihmsedi 

I saw your post and wonder if you are still after that list.
Try [coinmarketcap derivative exchange list](https://coinmarketcap.com/rankings/exchanges/derivatives/)

Derivative exchanges may also provide margin trading.
