### ISSUE TITLE
How to send Poloniex margin order via ccxt python?

### ISSUE THREAD

**Issue by vladimircity** [ccxt/ccxt#5189]
Hello, ccxt team!
How can i send Poloniex margin order?

Is this right?
`poloniex.privatePostMarginSell({
    'currencyPair': 'BTC/USDT',
    'rate': 7200,
    'amount': 1
})`
or
`poloniex.privatePostMarginSell(currencyPair='BTC/USDT', rate=7200, amount=1)`

- OS: Win10x64
- Programming Language version: Python 3.7
- Exchange: Poloniex
- Method: privatePostMarginSell

**Comment by kroitor** [comment]
Hi!

> poloniex.privatePostMarginSell({ 'currencyPair': 'BTC/USDT', 'rate': 7200, 'amount': 1 })

Should be this first one ) 

Also, check out:

```
poloniex.load_markets()
poloniex.verbose = True  # to see which request is being actually sent and which response is received

# native underscore notation works in Python
poloniex.private_post_margin_sell({ 'currencyPair': 'BTC/USDT', 'rate': 7200, 'amount': 1 })
```

Also: https://github.com/ccxt/ccxt/wiki/Manual

Let us know if the above does not answer the question.

**Comment by kroitor** [comment]
@vladimircity updated the above answer ↑ check out the details on symbols vs market ids.
