### ISSUE TITLE
New Exchange API development

### ISSUE THREAD

**Issue by Xequium** [ccxt/ccxt#5196]
- OS: ALL
- Programming Language version: ALL
- CCXT version: ALL
- Exchange: Xequium
- Method: ALL

Hello, i've been a user of ccxt for a while now, great job guys! Recently i have been developing my own exchange and now i want to create a good functional and easily used API. I noticed that some exchanges get the CCXT certified tag and since you guys would probably know best, i was wondering what the best API you have seen is , if there are any tools/guidelines for development and how to get my exchange supported in ccxt as well as certified.

**Comment by kroitor** [comment]
@Xequium hi! 

First of, thx for the kind words! )

> Recently i have been developing my own exchange and now i want to create a good functional and easily used API.

That's great! )

> I noticed that some exchanges get the CCXT certified tag and since you guys would probably know best, i was wondering what the best API you have seen is , if there are any tools/guidelines for development and how to get my exchange supported in ccxt

Check out this set of docs for general guidelines:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md
- https://github.com/ccxt/ccxt/wiki/Requirements
- https://github.com/ccxt/ccxt/wiki/Manual

> as well as certified.

On getting certified, please, reach out to me at igor@ccxt.trade )
