### ISSUE TITLE
Invalid api key for binance, on ccxt PHP while already using the latest ccxt version

### ISSUE THREAD

**Issue by ardialamwijaya** [ccxt/ccxt#5202]
got this error while i run the php ccxt,

_In binance.php line 1302:_
  **binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for a
ction
  ."}**

here is my composer.json:
"require": {
        "php": ">=7.0.15",
        "ccxt/ccxt": "1.18.578",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/orm": "^2.5",
        "friendsofsymfony/rest-bundle": "^2.2",
        "guzzlehttp/guzzle": "~6.0",
        "incenteev/composer-parameter-handler": "^2.0",
        "jms/serializer-bundle": "^2.1",
        "nelmio/api-doc-bundle": "^2.13",
        "sensio/distribution-bundle": "^5.0.19",
        "sensio/framework-extra-bundle": "^5.0.0",
        "symfony/monolog-bundle": "^3.1.0",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/swiftmailer-bundle": "^2.6.4",
        "symfony/symfony": "3.4.*",
        "twig/twig": "^1.0||^2.0",
        "whiteoctober/tcpdf-bundle": "^1.0",
      "ext-json": "*"
    },

ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: windows
- Programming Language version: php
- CCXT version: 1.18.578
- Exchange: binance
- Method: handle_errors (binance.php line 1302)

**Comment by kroitor** [comment]
@ardialamwijaya they have [dropped the keys recently](https://www.binance.com/en/support/articles/360027851252-Security-Update-API-Key-Reset), maybe, this is the cause? Also, have you checked the permissions on the api keys that you're using? Is it a new key (created today?). Have you tried with a new key?

**Comment by ardialamwijaya** [comment]
hi kroitor,
just update my api key and secret from binance. it runs perfectly if i want to retrieve all the markets from binance but for some reason i still got the same error message if i want to have a market buy or market sell process. 

i already debug each line of my code and still it didnt work at either market buy, market sell, limit buy or limit sell

**Comment by ardialamwijaya** [comment]
hi @kroitor, am wondering if is it a bug or just me who need to do some settings to handle the "bug"?

**Comment by kroitor** [comment]
@ardialamwijaya 

> it runs perfectly if i want to retrieve all the markets 

When you retrieve public data like markets – your keys are not used, therefore it works, but the private calls for your personal info require a working key, therefore your private requests fail.

Have you checked the apiKey permissions on Binance website?

<img width="993" alt="Screen Shot 2019-05-30 at 09 22 05" src="https://user-images.githubusercontent.com/1294454/58612815-8b0f2980-82bc-11e9-9308-aca2487f0fbc.png">

**Comment by kroitor** [comment]
@ardialamwijaya also, make sure that you're using the correct key and there's no mistake there.

**Comment by ardialamwijaya** [comment]
hi @kroitor , sorry i just reach u by today, since yestd im very busy with seminars n workshops at programming events..

attached below is screenshot from api in binance

![apibin](https://user-images.githubusercontent.com/6219924/58671983-4ac0b180-8377-11e9-8637-dbc57ca7d61b.png)

![apibin2](https://user-images.githubusercontent.com/6219924/58672129-0d105880-8378-11e9-9873-bb5c825cedaa.png)


do i need to make a new issue or u can reopen this issue?

**Comment by kroitor** [comment]
> do i need to make a new issue or u can reopen this issue?

No need to duplicate it, we can continue here )
Have you tried creating a new api key? Have you tried printing them out just before the call?

```PHP
echo 'API key: ' . $exchange->apiKey . ' ; Secret: ' . $exchange->secret . "\n";
$exchange->create...
```

Alternatively, you can add verbose mode just before the call to createOrder:

```PHP
$exchange->load_markets();
$exchange->verbose = true;
$exchange->create...
```

You will see a lot of info, including request and response headers and data

Check that your credentials in runtime inside those requests indeed correspond to the API keys from Binance.

**Comment by ardialamwijaya** [comment]
Hi @kroitor, yes thats the screenshot from my new api today. Will try the verbose tonight after i finish my seminars
