### ISSUE TITLE
Bitfinex assert precision is not None

### ISSUE THREAD

**Issue by benspring** [ccxt/ccxt#5203]
- OS: Linux Mint
- Programming Language version: Python
- CCXT version: 1.18.527
- Exchange: Bitfinex
- Method: 

I am doing: `float(exchange1.amountToPrecision(symbol + '/BTC', buyCoinAmount))`

And its getting an error with the precision: `assert precision is not None and isinstance(precision, numbers.Integral)`

This is happening on all trades with Bitfinex using CCXT. Any ideas?

**Comment by kroitor** [comment]
Fixed here 18 days ago: https://github.com/ccxt/ccxt/issues/5090
Please update to the most recent version and let us know if you still have this issue afterwards. Thx!

**Comment by benspring** [comment]
> Fixed here 18 days ago: #5090
> Please update to the most recent version and let us know if you still have this issue afterwards. Thx!

Hey, I updated to the latest version and it still broke.

It was running the function on the number: 340.9573975417407

Bitfinex: exchange2.amountToPrecision('GNT/BTC', 340.9573975417407)

Threw the same error: `340.9573975417407`

**Comment by kroitor** [comment]
@benspring hi, can you please post the verbose output?

```Python
exchange2.load_markets()

exchange2.verbose = True  # ←-- add this

exchange2.amountToPrecision('GNT/BTC', 340.9573975417407)
```

We need to see both the verbose request and verbose response.

**Comment by benspring** [comment]
The output was so large I decided to put it into pastebin:

https://pastebin.com/raw/tQBmtfb0

Again, thanks for speedy response.

**Comment by kroitor** [comment]
@benspring yep, basically, bitfinex doesn't have the `amount` precision, see here: https://github.com/ccxt/ccxt/issues/5090

> I am doing: float(exchange1.amountToPrecision(symbol + '/BTC', buyCoinAmount))

So, you should do:

```Python
# ... your code ...

symbol = symbol+'/BTC'
amount = float(buyCoinAmount)
if exchange1.markets[symbol]['precision']['amount']:
    amount = float(exchange1.amountToPrecision(symbol, amount))

# ... your code ...
```

Let us know if that doesn't help. We will add a workaround for it shortly.

**Comment by benspring** [comment]
Hey,

Sorry so none of bitfinex amountToPrecision will work? Or it doesn't need it?

Thanks,
Ben

**Comment by kroitor** [comment]
> Sorry so none of bitfinex amountToPrecision will work? Or it doesn't need it?

Yep, it doesn't need amount precision: https://docs.bitfinex.com/docs/readme (no amount precision here). We'll add a workaround for the above exception soon.

**Comment by benspring** [comment]
Oh right, thank you for the temp fix, letting me know and such a quick response. Appreciate it.
