### ISSUE TITLE
Return data from fetch_trades call

### ISSUE THREAD

**Issue by stevebdh** [ccxt/ccxt#5206]
I am using Python 3.7.2, CCXT 1.18.359, and calling against the Binance exchange.  The question is with the fetch_trades() call.  According to the CCXT  manual, the return data from executing the call includes a field named 'side'.  This field can have a value of either 'buy' or 'sell'.  The comment states, "// direction of the trade, 'buy' or 'sell'." 

My understanding is that a trade doesn't have a side.  Every actual trade has both a buyer and a seller.  Why does fetch_trade() return such a field?  Where is it coming from, since the Binance API for getting an aggregate trade doesn't return such a field?

**Comment by alexeymarunin** [comment]
@stevebdh IMHO this field should have 'buy' or 'sell' side according to order the trade belongs. So if order is buy then all its trades should have side 'buy' and if order is sell then all its trades are 'sell' side. But it does not true for Binance (#4618 lastest comments)

Binance REST API
* [Recent trades list](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#recent-trades-list), field `isBuyerMaker`
* [Aggregate trades list](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#compressedaggregate-trades-list), field `m`

But you're right - public trade is 'buysell' side in general (see @kroitor [comment](https://github.com/ccxt/ccxt/issues/4618#issuecomment-461157777))

**Comment by kroitor** [comment]
@alexeymarunin thx a lot for your answer! 

@stevebdh let us know if that does not help ) Feel free to ask further questions if you have more )
