### ISSUE TITLE
npm install error(postinstall.js)

### ISSUE THREAD

**Issue by jkjin7** [ccxt/ccxt#5207]
- OS: ubuntu 18.04
- PL version: nodejs v10.13.0
- CCXT version: 1.18.586
- method: npm install ccxt

I was using ccxt without any problem until today.
Got some errors when I install ccxt in a new project today.
It seems like some files is missing on npm, postinstall.js is likely.

error description is below
```
> ccxt@1.18.586 postinstall /home/user/project/node_modules/ccxt
> node build/postinstall.js

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '/home/user/project/node_modules/ccxt/build/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm WARN trades@1.0.0 No description
npm WARN trades@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ccxt@1.18.586 postinstall: `node build/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ccxt@1.18.586 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-05-29T04_10_53_356Z-debug.log
```

**Comment by kroitor** [comment]
@jkjin7 this is due to merging #5192 , will fix shortly, plz hold on.

**Comment by yandreiy** [comment]
still valid btw

**Comment by kroitor** [comment]
@yandreiy works on my system and on Travis, though... Can you provide more details?

<img width="558" alt="Screen Shot 2019-05-29 at 10 50 43" src="https://user-images.githubusercontent.com/1294454/58539273-a9631f80-81ff-11e9-9f4e-c36d00965406.png">

**Comment by yandreiy** [comment]
![ccxt](https://user-images.githubusercontent.com/5003085/58540322-761d9200-81f9-11e9-90f9-d6efa59f3c00.png)

**Comment by kroitor** [comment]
@yandreiy plz try:

```
rm -rf node_modules/ccxt
npm install ccxt
```

**Comment by MRDNZ** [comment]
I have the same issue with ccxt@1.18.587. Removed node_modules, cleared cache and reinstalled the package but keeps failing at the postinstall script.

**Comment by frosty00** [comment]
getting the same error

```
> ccxt@1.18.587 postinstall /Users/carlorevelli/Documents/important/code/playground/node_modules/ccxt
> node build/postinstall

internal/modules/cjs/loader.js:611
    throw err;
    ^

Error: Cannot find module '/Users/carlorevelli/Documents/important/code/playground/node_modules/ccxt/build/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.Module._load (internal/modules/cjs/loader.js:535:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)
```

It seems that ccxt is not loaded to node_modules when the script is being run

**Comment by frosty00** [comment]
https://krasimirtsonev.com/blog/article/Fun-playing-with-npm-dependencies-and-postinstall-script

guess who shows up in the comments. we have come full circle 🐙

**Comment by frosty00** [comment]
https://stackoverflow.com/questions/34781630/how-to-automatically-copy-files-from-package-to-local-directory-via-postinstall

**Comment by frosty00** [comment]
@MRDNZ it works if you `git clone` and then `npm install` working for a fix for `npm install ccxt` now

**Comment by MRDNZ** [comment]
@frosty00 Great thanks for the workaround! For now i just downgraded but will upgrade ASAP when the fix is available.
