### ISSUE TITLE
New Exchange: ByBit

### ISSUE THREAD

**Issue by Tezeug** [ccxt/ccxt#5215]
Hello,
check this exchange, please, and possibly and a support for it.
Thank you.

ByBit.com
https://github.com/bybit-exchange/bybit-official-api-docs

**Comment by kroitor** [comment]
See also: https://github.com/ccxt/ccxt/issues/5070

**Comment by kroitor** [comment]
Bybit is now available in CCXT 1.24.4+ https://github.com/ccxt/ccxt/issues/6612
