### ISSUE TITLE
Support fixed-point math

### ISSUE THREAD

**Issue by stonemonk** [ccxt/ccxt#522]
You want the most precision possible when dealing with a users money.  In particular, methods for placing orders and doing deposits/withdrawals should accept decimal.Decimal for the relavant arguments, return values and should be used internally for any calculations they perform.

**Comment by kroitor** [comment]
Thanks, for your suggestion! We agree completely! As you may know, this library is under active development. Switching to fixed point math is in our roadmap. Related issue: https://github.com/ccxt/ccxt/issues/393. 

By the way, your PRs and contributions are welcome! We will be happy if you could help us with that, but please note that apart from Python we support a few other languages as well, so we have to make it portable, therefore this is a little more involved than just switching to decimal.Decimal ([more about it](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md)). 

We hope to deliver it soon. Will let you know as soon as fixed-point math is integrated into it.
Stay tuned!

**Comment by stonemonk** [comment]
So I was proposing that CCXT switches from python float (which being backed by C double type, is 64bit on nearly every platform) to decimal.Decimal which is 128bit and would be suffient precision for working with currencies and is a more natural way of working with inherently floating point amounts (compared to trying to convert to fixed point).

I take it that you have a preference for using fixed point math, but this seems like it could be challenging if any calculations are required and because different symbols may require a different base unit.  For BTC based symbols, you could use https://en.bitcoin.it/wiki/Satoshi_(unit) ints for example, but then what about symbols based on ETH or USD?

Wondering about your general thoughts about how to approach this topic.  I dunno about the transpiling and other langs, but to use decimal.Decimal in the native python version would be pretty simple to switch to.

**Comment by kroitor** [comment]
> I take it that you have a preference for using fixed point math, but this seems like it could be challenging if any calculations are required and because different symbols may require a different base unit. For BTC based symbols, you could use https://en.bitcoin.it/wiki/Satoshi_(unit) ints for example, but then what about symbols based on ETH or USD?

We avoid rate conversions inside the library, therefore we don't really care about the base unit. I think we should approach it mathematically, not financially. Therefore a fixed-point solution seems to fit our needs better than big integers. Whatever way we resolve this, we still believe that the fix should be independent of any particular currency.

> I dunno about the transpiling and other langs, but to use decimal.Decimal in the native python version would be pretty simple to switch to.

Not really, because there's a lot of exchanges (up to a half) that do return fp-numbers in JSON... So we will have to convert from float to decimal.Decimal, and that in itself introduces some problems due to float-rounding and precision issues.

**Comment by stonemonk** [comment]
> Therefore a fixed-point solution seems to fit our needs better than big integers.

I don't understand this, "fixed-point" and "big integer" are the same to me.  Fixed-point normally refers to use of integer math by working with numbers at a certain scale. e.g. multipling all prices and quantities by 10 million, so you can represent it as a big integer and thus avoid using floating points and thereby avoiding float precision issues.  I was suggesting that this would be difficult because you might not be able to find an appropriate base scale for all currencies (and for the quanitity/amount field for orders!)

Personally I would stick to a floating point solution, but just upgrade the datatype from a 64bit `float` to 128bit `decimal.Decimal`.

> Not really, because there's a lot of exchanges (up to a half) that do return fp-numbers in JSON... So we will have to convert from float to decimal.Decimal, and that in itself introduces some problems due to float-rounding and precision issues.

You can work around this easily. The standard JSON parser has a way of customizing the float handling, specifically:

`response.json(parse_float=lambda f: f)`

This tells it to not try to parse unquoted floats as float, but rather just return it as a string.  Then you can just call float(dec_field) or decimal.Decimal(dec_field) to preserve the original precision. Or if you want fixed point math, something like this: 

`
scale = decimal.Decimal("100000000")
int_field = int(decimal.Decimal(dec_field) * scale)
`

If you wanted, you could also do that with string manipulation (detect and shift the decimal point character in the string, then convert directly to int) to avoid the use of decimal.Decimal completely. But again I would urge you to stick with floating point math and just upgrade the precision by using a 128bit floating point type.

**Comment by kroitor** [comment]
> I don't understand this, "fixed-point" and "big integer" are the same to me. 

I may be using the wrong term here, but what I mean under "fixed-point" is being able to do the following string-wise operation:
```
"0.0000000000000000000000000000000000000000000000000000000001"
x
"1234567891234567891234567891234567891234567891234567891234.0"
```

So we don't have to choose the base unit or to convert to integers or whatever. The only thing we need is an arbitrary-precision arithmetics util. We don't really care whether it stores those values as integers inside the util or not, the only thing we care about is getting adequate string representations of arbitrary-precision floats and having the ability to do basic arithmetics with those representations. To me, the underlying mechanics looks like something that isn't based on integers solely. We don't need BigInts, we want BigNumbers.

> Fixed-point normally refers to use of integer math by working with numbers at a certain scale. e.g. multipling all prices and quantities by 10 million, so you can represent it as a big integer and thus avoid using floating points and thereby avoiding float precision issues.

We believe, that mathematically, having a solution for arbitrary-precision numbers, we don't have to choose the scaler. This **really** should be currency-agnostic. The added complexity for arithmetics will definitely slow us down, so our main concern here is the efficiency of the math-util in question.

**Comment by stonemonk** [comment]
Ahh I see, I hadn't even considered that option.  Well that would certainly work if you can find a suitable library.  But using 128bit decimals would also be sufficient and is a built in native for python so it seems like a more natural choice.  I guess JS and PHP do not have 128bit float support built in though.  

Maybe this is a suitable JS lib which could be transpiled?:  https://github.com/MikeMcl/big.js/

It might be best to always use strings for CCXT API input/output as to hide the underlying details, thus allowing the user to chose a suitable representation in their own code.

You mention efficiency, but I don't think its a concern as you only really want to use it when dealing with a users money (create orders, fetch orders, fetch balances). For tickers, candles, etc there is no real reason to use higher precision.

**Comment by stonemonk** [comment]
Just want to say that I was incorrect when I said that Python's built in decimal.Decimal type was 128bit (I was thinking about the mongo Decimal type).  

decimal.Decimal is in fact arbitrary precision, and would thus be a more reasonable choice for Python version of CCXT than using a third party library.

**Comment by kroitor** [comment]
@stonemonk , we have a concern on decimal.Decimal, because from Py2 docs it looks like it uses a global context in a dirty manner, if there's no other way to specify rounding/truncation rules, that global context might be a showstopper:

<img width="892" alt="screen shot 2017-11-15 at 19 50 37" src="https://user-images.githubusercontent.com/1294454/32848803-7309b360-ca3e-11e7-8d24-511f6047af56.png">

What do you think of the above?

**Comment by stonemonk** [comment]
I am not working in Py2, but I don't think it's a problem. Any body else's code using decimal should be setting precision already prior to use. But if you are concerned about this you can always save the original precision first then restore it afterwards.

If the quantitize() method works in Py2, you might be better off using the default context precision of 28 decimals and only quantitizing down when needed..

**Comment by kroitor** [comment]
@stonemonk looks like we can use decimal.Decimal in both Pythons with default precision, it should cover all values, hopefully. Thx!

**Comment by Bomper** [comment]
Have you considered using BigNum for the JavaScript library? Floats are dangerous (precision loss) and strings lead to concatenation instead of addition (e.g. `order.size + 10` may be "3010" if `order.size` was `"30"`).

**Comment by kroitor** [comment]
@Bomper yes, in fact, this is all the same subject in all languages, so we are preparing a generalized solution to this issue. Will let you know upon progress.

**Comment by gaardiolor** [comment]
Would realy like this to be implemented too, using float all my calculations go wrong. Now I have to cast al floats to decimals, and back to float again when trading...

**Comment by gaardiolor** [comment]
python module simplejson supports decimal import / exports. Easy workaround:
```
import ccxt
import simplejson as json

e = ccxt.bittrex()
decimal_order_book = json.loads(json.dumps(e.fetch_order_book('ETH/BTC')), use_decimal=True)
```
@kroitor this should be pretty easy to implement in ccxt (at least for python sync / async) ?
- use simplejson instead of json
- make use_decimal configurable

**Comment by kroitor** [comment]
@gaardiolor if I do this without changing all the code that works with precision for order submission, withdrawal submission, not only the parsing, but also all other aspects of the library, this would mostly break it unusable. There isn't an "easy one-liner" to fix for this, otherwise I would have done it three times already. It requires a more thorough design, and this is the core code of the lib, therefore it has to be designed with double care. We need to have base methods for arbitrary precision arithmetics first.

**Comment by gaardiolor** [comment]
OK, totally trust your judgement of course, I'm pretty new to programming. Awesome piece of work this library.

**Comment by timolson** [comment]
This is such a common error in libraries outside the financial world, and I appreciate that most exchanges do it wrong, making your job harder.

In my CoinTrader project, we handled this by creating a class which keeps two integers, the amount and the basis.  Basis is the number of units which add up to 1.0, so in Bitcoin's case the basis would be 100 million.  Of course, back then there were no currencies with "infinite" precision, and I'm not sure how to handle that without reverting to a float-like approximation of mantissa + exponent.  Anyway, this class can easily produce a float value when needed without losing precision.  When converting _from_ a float, we can round or truncate to the nearest amount.  It's important to consider both rounding _and_ truncation for different purposes.  For example, if you are computing the maximum amount of something to buy, you need to use truncation rather than rounding.  However, if you are trying to fix a brain-dead exchange's use of floats, you'll want rounding.

Note that not all currencies have a power-of-ten basis.  The Swiss Franc, for example, trades in quantities of 0.05 (nickels)

Hope this helps

**Comment by timolson** [comment]
P.S. I'd be happy to help with implementation.

**Comment by kroitor** [comment]
@timolson 

We're about to merge it shortly (almost there, currently working on it right now):
- https://github.com/ccxt/ccxt/pull/2397
- https://github.com/ccxt/ccxt/pull/1635
- https://github.com/ccxt/ccxt/pull/2408
- https://github.com/ccxt/ccxt/issues?q=decimalToPrecision+is%3Aclosed
- https://github.com/ccxt/ccxt/issues/2733

This is almost a finished job now. Thanks to @xpl, @mkutny, @frosty00 and others.

Anyway, thanks for your proposal. In fact, we appreciate all help and contributions, so, we will be really happy if you help us with some of our pending tasks, just make sure to read this:
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

Thanks!

**Comment by Legogris** [comment]
Even with the proposed changes there is still a fundamental problem remaining: `JSON.parse` will parse any numbers to `Numbers`, resulting in lost precision for exchanges which don't wrap their prices and amounts in strings. The limitations of number precision in ES aren't present in the JSON specification, so it is even technically valid for exchanges to do so. This breaks expectations that `info` objects will contain unmodified data.

Unfortunately the already used `bignumber.js` package does not save the input value (losing e.g. any trailing zeroes).

@kroitor I made a PR here with an initial attempt to address this here: #4266

**Comment by damian123** [comment]
Floats should never be used for money but ccxt forces it, will this task be finished?

**Comment by timolson** [comment]
Note that some *_exchanges_* send (and use!) floats, and the conversion to
e.g. Decimal still does not guarantee correct accounting in such cases.

**Comment by kroitor** [comment]
@pietrodn it's more about the performance of native JSON parsers like JSON.parse() vs a custom parser that would be required to treat JSON numbers as text-strings, which is why we just quote long numbers and feed them into the native parser as quoted strings.

**Comment by timolson** [comment]
>The REST APIs use JSON numbers, that can be (de)serialized as Numeric,
maintaining precision.

A JSON number is either an integer or a float, so there is the possibility
of roundoff error if there is any use of JSON Number anywhere at all, from
the exchange, to the transmitted packet, to ccxt.  Any cast to float will
poison the data with inaccuracy. My point was that there are cases when
this isn't even ccxt's fault.  IIRC Bittrex, for example, was computing
their fees using floats last time I checked. If you try to match their
calculations locally, there's a dependence on the rounding mode of IEEE
floats :clownface: If the exchange sends the price as a float, for example,
you might end up with 1234.5599999999999999998 instead of 1234.56, for
example. You can't fix the exchanges but you can use ccxt's metadata about
market precisions to round prices, amounts, etc. to the correct values.

**Comment by frosty00** [comment]
@timolson the exchanges sends a json string that contains numbers. At this point the numbers are still strings, we simply feed those strings to the `.number` constructor without parsing it as a float first, hope that clears things up for you !

**Comment by gshpychka** [comment]
@kroitor would it make sense to adjust that check to support Decimal?

**Comment by gshpychka** [comment]
@ttodua what's required to progress this issue? Right now the error above is the only thing that's keeping me with using Decimal in Python.

**Comment by samgermain** [comment]
> @ttodua what's required to progress this issue? Right now the error above is the only thing that's keeping me with using Decimal in Python.

I'll push a PR later today that does a lot of the changes, and after that, for all the exchanges that you want to use, I would make sure that all the arithmetic on prices uses methods like `Precise.stringAdd`, `Precise.stringMul`... instead of `+`,`*` ...

**Comment by samgermain** [comment]
Changes like the ones in [this PR](https://github.com/ccxt/ccxt/pull/14706) need to be made across all exchanges. I can get all the one that use `Math.` pretty easily by using a search, but catching all the `+`, `-`, `*` `/` could be a bit tricky and might require some Beta use

**Comment by gshpychka** [comment]
@samgermain not sure I understand completely - assigning `Decimal` to `exchange.number` already means that number operations will be fixed-point, doesn't it? It seems to work fine, but the error I posted above is what's still broken.

**Comment by gshpychka** [comment]
@samgermain can you explain?

**Comment by samgermain** [comment]
> @samgermain can you explain?

Don't worry about it, I've been working on adding [string math across the library,](https://github.com/orgs/ccxt/projects/52) should hopefully be done soonish

**Comment by gshpychka** [comment]
> > @samgermain can you explain?
> 
> Don't worry about it, I've been working on adding [string math across the library,](https://github.com/orgs/ccxt/projects/52) should hopefully be done soonish

Can you address my question above - assigning `Decimal` to `exchange.number` already enables fixed-point math, but the error I posted above is still broken.

**Comment by gshpychka** [comment]
@samgermain can you please address the question?

**Comment by samgermain** [comment]
> > @damian123 you can use `exchange.number = str` or `exchange.number = decimal.Decimal` it is almost finished
> 
> I've tried it, but I'm getting an error when trying to create an order with Decimal price and size:
> 
> ```
> File "/usr/local/lib/python3.9/site-packages/ccxt/okcoin.py", line 2071, in create_order
>     request['price'] = self.price_to_precision(symbol, price)
>   File "/usr/local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 2952, in price_to_precision
>     return self.decimal_to_precision(price, ROUND, market['precision']['price'], self.precisionMode, self.paddingMode)
>   File "/usr/local/lib/python3.9/site-packages/ccxt/base/decimal_to_precision.py", line 39, in decimal_to_precision
>     assert(isinstance(precision, float) or isinstance(precision, numbers.Integral))
> AssertionError
> ```
> 
> @frosty00 passing this function without the assertions to exchange seems to work. Maybe a good idea to remove them, or account for Decimal?

I created a [pull request](https://github.com/ccxt/ccxt/pull/15115) that should fix your specific issue. If you run into any more issues regarding this topic please let me know and I can try to solve them. 

Using `decimal.Decimal` will not work on every exchange yet. There are a number of PR's that need to be merged before that will be possible.

- [ ] coinbase #15020
- [ ] bitstamp #15019
- [ ] currencycom #15017
- [ ] independentreserve #15016
- [ ] btcalpha #15015
- [ ] liquid #15007
- [ ] exmo #15003
- [ ] therock #15002
- [ ] ndax #15001
- [ ] bitfinex2 #15000
- [ ] lbank2 #14980
- [ ] phemex #14976
- [ ] okx #14966
- [ ] mexc #14931
- [ ] huobi #14930
- [ ] bybit #14915
- [ ] bl3p #14904
- [ ] bitvavo #14903
- [ ] bittrex #14901
- [ ] bitmart #14895
- [ ] bit2c #14893
- [ ] binance #14892
- [ ] huobijp #14875
- [ ] upbit #14873
- [ ] luno #14860
- [ ] cex #14858
- [ ] wavesexchange #14717
- [ ] exchange.calculate_fee #15028

**Comment by samgermain** [comment]
> @samgermain can you please address the question?

The fix to your problem was merged, so you should be able to use the `Decimal` type with `okcoin`. Using the Decimal type will not be completely possible for all exchanges however until the PRs listed above get merged.

**Comment by samgermain** [comment]
PRs related to this issue are linked in https://github.com/orgs/ccxt/projects/52

Once all PRs in that project are merged, bugs related to this issue will be intermittant, and solved as they are discovered, but string math should be universally available

**Comment by samgermain** [comment]
> @damian123 you can use `exchange.number = str` or `exchange.number = decimal.Decimal` it is almost finished

Whats the exact way to do it? When I do  

`exchange.number = str;`

I get

`ReferenceError: str is not defined`

--------------

I'm using JS

**Comment by Bomper** [comment]
For those returning to CCXT after 7 years, what is the status of this? Is there an example somewhere to use Coinbase with arbitrary precision arithmetic?

**Comment by Bomper** [comment]
For those returning to CCXT after 7 years, what is the status of this? Is there an example somewhere to use Coinbase with arbitrary precision arithmetic? Or are the changes transparent to the end user?

For example, the [Trade structure](https://docs.ccxt.com/#/?id=trade-structure) has an `amount` field with an example value that seems like a `number` but in the TypeScript client, its type is `Num`. What is this type?

**Comment by ttodua** [comment]
@Bomper 
you can override the behavior by
```
ex = new ccxt.binance();
ex.number = String;  // or Number
```
It might not be in docs, i'll check and try to add it (if it's not there)

**Comment by Bomper** [comment]
@ttodua where I'd expect to see this documented is at the top of each exchange documentation page, along with any instantiation peculiarities. See #23771.

**Comment by ttodua** [comment]
@Bomper here is doc paragraph: https://docs.ccxt.com/#/README?id=string-math
thought this won't go to each exchange docs.

**Comment by Bomper** [comment]
@ttodua Thanks that works but I get a TypeScript warning for the assignment `coinbase.number = String;`:

> Deno: Type 'StringConstructor' is not assignable to type '(numberString: string) => number'.
  Type 'string' is not assignable to type 'number'.

**Comment by ttodua** [comment]
@carlosmiei ^
