### ISSUE TITLE
possible Binance coin mapping issue (IOTA -> MIOTA)

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5220]
The info in the balance response looks like this:

```
{ makerCommission: 10,
  takerCommission: 10,
  buyerCommission: 0,
  sellerCommission: 0,
  canTrade: true,
  canWithdraw: true,
  canDeposit: true,
  updateTime: 1536193392194,
  accountType: 'MARGIN',
  balances:
   [ { asset: 'BTC', free: '0.00023580', locked: '0.00000000' },
...
     { asset: 'IOTA', free: '7794.19900000', locked: '0.00000000' },
```

CMC uses MIOT (which I guess is _milli_ ITOA?).

```
{
id: 1720,
name: "IOTA",
symbol: "MIOTA",
slug: "iota",
is_active: 1,
first_historical_data: "2017-06-13T14:30:09.000Z",
last_historical_data: "2019-05-30T14:34:01.000Z",
platform: null,
}
```

https://info.binance.com/en/currencies/miota
https://coinmarketcap.com/currencies/iota/

**Comment by kroitor** [comment]
Related:

- https://github.com/ccxt/ccxt/pull/3567
- https://github.com/ccxt/ccxt/pull/2732

**Comment by kroitor** [comment]
> CMC uses MIOT (which I guess is milli ITOA?).

<img width="572" alt="Screen Shot 2019-05-30 at 18 09 03" src="https://user-images.githubusercontent.com/1294454/58642448-0943ee00-8306-11e9-875a-2f49cc2b7a03.png">

**Comment by npomfret** [comment]
The cmc symbol is MIOTA, so the Binance symbol should be mapped to MIOTA on the way out shouldn't it?

**Comment by frosty00** [comment]
it doesn't matter an iota :>

**Comment by kroitor** [comment]
@npomfret the prices are the same on binance and cmc, so, if it's IOTA, then it's IOTA everywhere, otherwise MIOTA. Or am I missing something?

**Comment by npomfret** [comment]
CMC doesn't use the symbol IOTA, it uses MIOTA.  I checked the top 5000 symbols in CMC to see if IOTA was used but it isn't.  The name is IOTA, but the symbol isn't:

```
{
        id: 1720,
        name: "IOTA",
        symbol: "MIOTA",
        slug: "iota",
        circulating_supply: 2779530283,
        total_supply: 2779530283,
        max_supply: 2779530283,
        date_added: "2017-06-13T00:00:00.000Z",
        num_market_pairs: 41,
        tags: [ ],
        platform: null,
        cmc_rank: 15,
        last_updated: "2019-05-30T15:10:04.000Z",
        quote: {
            USD: {
                price: 0.519050730323,
                volume_24h: 106787674.41208,
                percent_change_1h: -1.18438,
                percent_change_24h: -0.322656,
                percent_change_7d: 36.4115,
                market_cap: 1442717223.3460448,
                last_updated: "2019-05-30T15:10:04.000Z",
            }
        },
    },
```

I was under the impression that we used the CMC symbols (where there wasn't a conflict).

**Comment by kroitor** [comment]
@npomfret you're looking at the raw CMC response, which is not a unified CCXT response, and if you check for the markets on CMC, it should show id = iota, symbol = IOTA:

```JavaScript
coinmarketcap.market (IOTA/USD)
{     limits: { amount: { min: undefined, max: undefined },
                 price: { min: undefined, max: undefined },
                  cost: { min: undefined, max: undefined }  },
   precision: {  },
   tierBased:    undefined,
  percentage:    undefined,
       taker:    undefined,
       maker:    undefined,
          id:   "iota/usd",  // ←-----------------
      symbol:   "IOTA/USD",  // ←-----------------
        base:   "IOTA",
       quote:   "USD",
      baseId:   "iota",
     quoteId:   "usd",
        info: {                 id: "iota",
                              name: "IOTA",
                            symbol: "MIOTA",
                              rank: "15",
                         price_usd: "0.4767678086",
                         price_btc: "0.00005752",
                  '24h_volume_usd': "66078972.8639",
                    market_cap_usd: "1325190562.0",
                  available_supply: "2779530283.0",
                      total_supply: "2779530283.0",
                        max_supply: "2779530283.0",
                 percent_change_1h: "0.88",
                percent_change_24h: "-11.45",
                 percent_change_7d: "21.55",
                      last_updated: "1559293562"     }         }
mbp:ccxt igorkroitor$
```

That happens due to the substitution in CMC https://github.com/ccxt/ccxt/blob/master/js/coinmarketcap.js#L127

So, there may be exceptions for historical reasons, if practically all other exchanges use IOTA to designate it, then changing it everywhere to MIOTA just to keep it in line with CMC makes less sense than just altering the CMC code to match the rest of the world. We could switch back to MIOTA, if we find more than one exchange that trades whole IOTAs instead of milliIOTAs.

Let us know if that doesn't answer the question.
