### ISSUE TITLE
ccxt_WEBPACK_IMPORTED_MODULE_8__default.a[exchangeId]

### ISSUE THREAD

**Issue by ivanjeremic** [ccxt/ccxt#5221]
My original lines that worked was this:

```JavaScript
    exchanges.map(
          exchangeId =>
            new Promise(async (resolve, reject) => {
              const exchange = new ccxt[exchangeId]({
                enableRateLimit: true,
                proxy: proxy
              });
              const ticker = await exchange.fetchTicker(symbol);
              tickers[exchangeId] = ticker;
              });
            })
        )
```
But now I get in debugger this error messege:
```
**LINE Debugger:**
 `exchange = new ccxt__WEBPACK_IMPORTED_MODULE_8___default.a[exchangeId]({
                                enableRateLimit: true,
                                proxy: proxy
                              });`
**ERROR:** `Uncaught (in promise) TypeError: ccxt__WEBPACK_IMPORTED_MODULE_8___default.a[exchangeId] is not a constructor`
```
- OS: Node
- Programming Language version: JS
- CCXT version: ^1.18.309
- Exchange: Any
- Method:

I hope someone has expirienced same issue so I can find the probblem here.

**Edit** Type error in Headline corrected

**Comment by kroitor** [comment]
1. Does this happen with the most recent version 1.18.594?
2. How do you import ccxt?
3. Does this work:

```JavaScript
const ccxt = require ('ccxt')
const exchanges = [ 'bitfinex', 'binance', 'bittrex' ]
const tickers = {}
const symbol = 'ETH/BTC'
const promises = exchanges.map (exchangeId =>
    new Promise(async (resolve, reject) => {
        const exchange = new ccxt[exchangeId] ({
            enableRateLimit: true,
        });
        const ticker = await exchange.fetchTicker(symbol)
        tickers[exchangeId] = ticker
    })
)
console.log (tickers)
```

?

Plz use [markdown](https://guides.github.com/features/mastering-markdown/) for readability.

**Comment by crudfunc** [comment]
I import it with, `import ccxt from 'ccxt';`

Yes I use the most recent version in an react app, your snippet is also working but the error in the console is still there. Maybe I'm missing some Webpack/Babel configuration. (I'm still very new to this transpiling/ packaging)

**Comment by kroitor** [comment]
@crudfunc there's a strange typo `ccct_WEBPACK_IMPORTED_MODULE_8__default` should probably start with `ccxt`, check your configs for the typos, and let us know if that doesn't help.

**Comment by ttodua** [comment]
Seems issue was a typo, and there was no longer any follow-up. Closing the issue for now.
