### ISSUE TITLE
How to get historical and current daily "closing" prices?

### ISSUE THREAD

**Issue by lgomez** [ccxt/ccxt#5227]
Question...

I've been reading the manual so this is likely to be me not understanding what I should be looking for. I'm trying to get the "closing" prices for one or more assets either historical or current. I'm using midnight UTC as the closing time. Not sure if there is a recommended way.

I tried using `fetch_ohlcv` for a small window but it seems convoluted and I'm not entirely sure I'm actually getting what I should be getting. Is there a recommended way or perhaps an example in the examples folder that is close to what I should be looking at? I don't mind doing the work but any help narrowing down my search or an example would be great.

Thank you!

- OS: OSX and Ubuntu
- Programming Language version: Python 3 or JavaScript
- CCXT version: 1.18.603
- Exchange: Kraken
- Method: fetch_ohlcv?

**Comment by kroitor** [comment]
@lgomez You indeed need to `fetch_ohlcv` with a `symbol` and `1d` timeframe, for each symbol separately, in a loop, while keeping in mind the [rate-limit](https://github.com/ccxt/ccxt/wiki/Manual#rate-limit)

See here:

- https://github.com/ccxt/ccxt/blob/master/examples/py/fetch-ohlcv-kraken.py
- https://github.com/ccxt/ccxt/blob/master/examples/js/fetch-ohlcv-cex.js

In Python:

```Python
import ccxt
exchange = ccxt.kraken ({ 'enableRateLimit': True })
symbols = [ 'ETH/BTC', 'LTC/BTC' ]
for symbol in symbols:
    # kraken will return approx 720 elements (720 days of history for two years)
    # each element will contain the timestamp, the ohlc prices and the volume
    # kraken flips calendar days at 00:00 midnight UTC
    candles = exchange.fetch_ohlcv(symbol, '1d')
```

In JS:

```shell
#     date ↓                                  closing price ↓

mbp:ccxt igorkroitor$ node examples/js/cli kraken fetchOHLCV ETH/BTC 1d --iso8601

kraken.fetchOHLCV (ETH/BTC, 1d)
2017-06-13T00:00:00.000Z | 0.14834 | 0.15199 |   0.132 | 0.14286 | 108086.53719693
2017-06-14T00:00:00.000Z | 0.14289 | 0.14368 |  0.1356 | 0.14014 |  57245.43073348
2017-06-15T00:00:00.000Z | 0.14014 | 0.14297 | 0.12902 | 0.14269 |  92311.67220067
2017-06-16T00:00:00.000Z | 0.14269 | 0.14519 | 0.13668 | 0.14298 |  38849.38329726
2017-06-17T00:00:00.000Z | 0.14274 |   0.143 |  0.1372 | 0.13935 |  19634.32654135
2017-06-18T00:00:00.000Z | 0.13935 |  0.1442 |   0.139 | 0.14008 |  26131.65632789
2017-06-19T00:00:00.000Z | 0.14008 | 0.14101 | 0.13776 | 0.13776 |  23950.58654504
2017-06-20T00:00:00.000Z | 0.13776 | 0.14099 | 0.11503 |   0.129 |  84523.30584304
...
```

**Comment by lgomez** [comment]
Wow @kroitor ... that was probably the fastest response I've ever gotten from any Github issue. I was literally tipping a follow up question asking if I could do what you just described. So thank you very much for the response. I'll go ahead and try that.

**Comment by garik-code** [comment]
Thx! I last time 
        0:51, 3 июня 2019 г., "Luis G. Gómez" <notifications@github.com>:Wow @kroitor ... that was probably the fastest response I've ever gotten from any Github issue. I was literally tipping a follow up question asking if I could do what you just described. So thank you very much for the response. I'll go ahead and try that.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by lsheynova** [comment]
Using the Binance API I can fetch the klines data with a time range, in exchange.fetch_ohlcv(symbol, '1d'), there is no timerange, so how do I select time range?

**Comment by kroitor** [comment]
@lsheynova the `1d` string – is the timeframe: 
- https://github.com/ccxt/ccxt/issues/10148
- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts

**Comment by johnpip** [comment]
You add a pram to the call. 
fetch_ohlcv('ETH/USDT', '1d', timestamp).  

Timestamp is in millisecond and is the start date of the data range.  Example 1641565197193.  Which is equal to a date and time from the date you want data.  You can get this conversion at https://www.epochconverter.com/
