### ISSUE TITLE
suggestion: new category field for transactions

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5230]
I was thinking that it would be helpful to have a little more information in transactions.  Going through mine I have not just deposits and withdrawals, but from memory:

 * forked coins
 * air drops
 * refunds
 * adhoc balance  corrections

Perhaps we could either have these as top level types along side _deposit_ and _withdrawal_, or maybe add an optional `category` field?

**Comment by kroitor** [comment]
Basically, most of it is either already documented as a part of `fetchLedger` or is going to be a part of it ) 

- https://github.com/ccxt/ccxt/wiki/Manual#ledger
- https://github.com/ccxt/ccxt/wiki/Manual#ledger-entry-structure

Transactions are for onchain transfers mostly, whereas ledger entries is a superset of transactions+transfers+all other types balance changes...

Let me know if that doesn't answer it )

**Comment by npomfret** [comment]
Right.  So ledger will also have trades in it?  If so, is a trade effectively 3 entries in a ledger (amount bought, amount sold and a fee)?

**Comment by kroitor** [comment]
> So ledger will also have trades in it? 

Yep )

> If so, is a trade effectively 3 entries in a ledger (amount bought, amount sold and a fee)?

In most cases – yes. 

Some exchanges include the fee info for transfers and transactions into the ledger entry itself. The ledger structure also has a dedicated `fee` field for that reason and a transaction ledger entry is very similar to a transaction structure.

**Comment by npomfret** [comment]
And is there a way to _link_ together things in the ledger that are related (like the 3 entires for a trade)?

**Comment by kroitor** [comment]
> And is there a way to link together things in the ledger that are related (like the 3 entires for a trade)?

Yes, `referenceId` + `type`.
