### ISSUE TITLE
coinbasepro / gdax error in fetchDepositAddress

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5233]
```
     TypeError: this.privateGetCoinbaseAccountsIdAddresses is not a function
      at coinbasepro.fetchDepositAddress [as fetch_deposit_address] (node_modules/ccxt/js/gdax.js:781:37)

```

**Comment by steveklebanoff** [comment]
@kroitor `fetchDepositAddress` still seems broken for me. does it work for you?

```
(node:61281) UnhandledPromiseRejectionWarning: Error: coinbasepro GET https://api.pro.coinbase.com/coinbase-accounts/<my_account_number>/addresses 403 Forbidden {"message":"Forbidden"} (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)
 ```

**Comment by steveklebanoff** [comment]
It looks like we should be using `privatePostCoinbaseAccountsIdAddresses`

**Comment by kroitor** [comment]
@steveklebanoff unfortunately, it does not accept signups from Russia, so, I can't test it on my side directly, however from your response message it looks like it may be related to some kind of permissions.  Have you checked the permissions on the key?

> It looks like we should be using privatePostCoinbaseAccountsIdAddresses

Nope ) See here: 

- https://github.com/ccxt/ccxt/issues/5183
- https://developers.coinbase.com/api/v2#address-resource

**Comment by steveklebanoff** [comment]
I'll put up a PR for a fix

**Comment by kroitor** [comment]
@steveklebanoff ok, thx!

**Comment by steveklebanoff** [comment]
https://github.com/ccxt/ccxt/pull/5239

**Comment by kroitor** [comment]
@steveklebanoff have you checked this:

- #5183
- https://developers.coinbase.com/api/v2#address-resource
- https://github.com/ccxt/ccxt/issues/5233#issuecomment-498852342

? )

**Comment by steveklebanoff** [comment]
@kroitor See PR: https://github.com/ccxt/ccxt/pull/5239 .  The request should be a POST, not a GET.  I confirmed this works locally.  This is documented here: https://github.com/coinbase/coinbase-pro-node/issues/91#issuecomment-352441654

**Comment by kroitor** [comment]
@steveklebanoff your fix is a bit wrong, you actually create a new address by sending a `POST`, which corresponds to `createDepositAddress`, not `fetchDepositAddress`:

<img width="718" alt="Screen Shot 2019-06-05 at 00 37 28" src="https://user-images.githubusercontent.com/1294454/58915733-57a02500-872a-11e9-83d8-68ddccb3fdb5.png">

So, despite that it _"seems"_ to return a proper address and _"seems to work"_ on your side – it actually doesn't work the way it should if done with a `POST`.

Please, read very carefully: #5183.

**Comment by kroitor** [comment]
@steveklebanoff Most likely coinbase now completely restricts reusing the deposit addresses, or this may be account-specific or key-specific. If you have an account there, can you plz try reaching out to their tech support on this issue? We will be very happy if you report back, anyways. If they switched that functionality off, then we will set `fetchDepositAddress` in the `has` metadata to `false`.

**Comment by steveklebanoff** [comment]
@kroitor that makes sense - thanks for the clarification!  I'm not sure if support will get back to me as they have been unresponsive about other API questions.  

If anyone else has the same issue (`fetchDepositAddress` not working), please comment here and I can put a PR to remove `fetchDepositAddress` and have everyone use `createDepositAddress`

**Comment by npomfret** [comment]
What's the current state of fetchDepositAddress in gads?  Happy to test if it helps.

**Comment by kroitor** [comment]
@npomfret current status is unknown, it is implemented according to their docs, but users report that it doesn't work. If you can try `fetchDepositAddress` with the most recent version of CCXT on your side and confirm the above, that could help us clarify its status.

**Comment by npomfret** [comment]
I'm still getting the error I reported.  Don't understand why though.

**Comment by kroitor** [comment]
@npomfret what's the size of your gdax.js ? Should be 33188 bytes with the most recent version of CCXT.

**Comment by npomfret** [comment]
Yep:

```
ls -al shared-code/node_modules/ccxt/js/gdax.js
-rw-r--r--  1 npomfret  staff  33188 Jun  5 09:16 shared-code/node_modules/ccxt/js/gdax.js
```

**Comment by npomfret** [comment]
Sorry, ignore that.

**Comment by kroitor** [comment]
@npomfret wrong version?

**Comment by npomfret** [comment]
Ok, sorry - I have a weird setup.  So the true error now is:

`GET https://api.pro.coinbase.com/coinbase-accounts/2743d969-8393-5647-95ba-32aa5230db28/addresses 403 Forbidden `

Maybe I need to fix my API Key.

**Comment by kroitor** [comment]
> Maybe I need to fix my API Key.

It looks like you're not the only user having the same issue – @steveklebanoff reported the same above. Apparently, coinbase doesn't want their users to have non-onetime reusable addresses. So, I think they've switched the endpoint off or have restricted the access to it to approved clients only.

**Comment by kroitor** [comment]
@npomfret it would be great if you could reach out to their tech support with this question – the more questions they receive, the higher the chance we will get an answer here...

**Comment by npomfret** [comment]
I'm struggling with our implementation now.  How is the user supposed to set `this.options['coinbaseAccounts']` and `this.options['coinbaseAccountsByCurrencyId']`?

**Comment by npomfret** [comment]
I wanted to set it prior to calling this method (so I don't have any _hidden_ api calls going on).  Is that possible?  It would be nice to just pass the account parameter through (I think that's how it used to work).

**Comment by npomfret** [comment]
... anyway - I've revised a ticket with their support.

**Comment by kroitor** [comment]
> I wanted to set it prior to calling this method (so I don't have any hidden api calls going on). Is that possible? It would be nice to just pass the account parameter through (I think that's how it used to work).

You will have to know the correspondence of currency ids to your account data:

```JavaScript
accounts = [
    { 'currency': 'BTC', 'id': 'coinbase-btc-account-id' },
    { 'currency': 'ETH', 'id': 'coinbase-eth-account-id' },
]

exchange = new ccxt.coinbasepro ({
    enableRateLimit: true,
    options: {
        'coinbaseAccounts': accounts,
        'coinbaseAccountsByCurrencyId': ccxt.indexBy (accounts, 'currency'),
    },
})
```

↑ Something like this should work.
