### ISSUE TITLE
[Deribit] fetchBalance()

### ISSUE THREAD

**Issue by alexeymarunin** [ccxt/ccxt#5235]
OS: macOS 10.14.5
Programming Language version: Node.js v.9.10.1
CCXT version: 1.18.598
Exchange: Deribit
Method: fetchBalance()

I use [Deribit testnet](https://test.deribit.com)

I created limit-order for sell 1.0 BTC

I fetch balance
```json
{
    "BTC": {
        "free": 9.98647528,
        "used": 0,
        "total": 9.996525289
    }
}
```

And order
```json
{
    "info": {
        "orderId": "2423719978",
        "type": "limit",
        "instrument": "BTC-PERPETUAL",
        "direction": "sell",
        "price": 9000,
        "label": "",
        "amount": 9000,
        "quantity": 900,
        "filledQuantity": 0,
        "filledAmount": 0,
        "avgPrice": 0,
        "commission": 0,
        "created": 1559568296501,
        "lastUpdate": 1559568296501,
        "state": "open",
        "postOnly": false,
        "reduceOnly": false,
        "api": false,
        "max_show": 900,
        "maxShow": 900,
        "maxShowAmount": 9000,
        "adv": false
    },
    "id": "2423719978",
    "timestamp": 1559568296501,
    "datetime": "2019-06-03T13:24:56.501Z",
    "symbol": "BTC-PERPETUAL",
    "type": "limit",
    "side": "sell",
    "price": 9000,
    "amount": 900,
    "cost": 0,
    "average": 0,
    "filled": 0,
    "remaining": 900,
    "status": "open",
    "fee": {
        "cost": 0,
        "currency": "BTC"
    }
}
```

Is this correct?
Why `used` is 0?
And why `amount` is 900?

**Comment by bigcountrysc** [comment]
It is not filled that is why used is 0 and amount is 900 as you placed an order for 900 contracts.

**Comment by kroitor** [comment]
@alexeymarunin Let us know if the answer by @bigcountrysc doesn't help. `used` is zero because deribit fetchBalance does not report it (you can see that in [`verbose` mode](https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting), and the amount is 900 because that is the amount of contracts you're buying with deribit.
