### ISSUE TITLE
how  to  use  fetch_order in huobi pro ?

### ISSUE THREAD

**Issue by runrun88** [ccxt/ccxt#5237]
- OS: windows 10
- Programming Language version: py
----ccxt    ：        1.18.562
- Exchange:  houbi 
- Method: fetch_order
How can I use this function?
I use like this ::: 
   while  self.huobi.fetch_order( self,order_result.id ) \
                not in [2, 3, 6, "partial-canceled", "filled", "canceled"]:    
    
but it turns out  wrong.

How  can I do  it ?

**Comment by kroitor** [comment]
> How can I do it ?

You can do it as described in the Manual, here: https://github.com/ccxt/ccxt/wiki/Manual#by-order-id, just as you do it with any other exchange:

```Python
import ccxt
from pprint import pprint

exchange = ccxt.huobipro ({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})

exchange.load_markets()

order_id = YOUR_ORDER_ID

order = exchange.fetch_order (order_id)

pprint(order)
```

Hope that answers the question )
