### ISSUE TITLE
ccex does not have market symbol BTC/USD

### ISSUE THREAD

**Issue by phil-steve** [ccxt/ccxt#524]
According to https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids the market symbols are standardized to e.g. BTC/USD across exchanges.

Yet for ccex this does not seem to work despite them supporting this pair. I currently receive: „ccex does not have market symbol BTC/USD“ when doing exchange.fetchTicker(currencyPair). All other exchanges work fine.

ccex USD depositing: https://c-cex.com/?id=usdworks
ccex API docs https://c-cex.com/?id=api

**Comment by kroitor** [comment]
Hi, @phil-steve !

If you take a careful look at their price here: https://c-cex.com/t/usd-btc.json, you will immediately notice, that it is a USD/BTC price, not BTC/USD. 

```
>>> ccxt.ccex({'verbose':True}).fetch_ticker('USD/BTC')
{'info': {u'sell': 0.0001365, u'updated': 1510250896, u'buy': 0.0001355, u'lastprice': 0.00013661, u'lastbuy': 0.00013463, u'buysupport': 8.5735704, u'lastsell': 0.00013661, u'high': 0.00014186, u'low': 0.00012861, u'avg': 0.00013523}, 'last': 0.00013661, 'timestamp': 1510250896000, 'symbol': u'USD/BTC', 'vwap': None, 'datetime': '2017-11-09T18:08:16.000Z', 'high': 0.00014186, 'average': 0.00013523, 'low': 0.00012861, 'quoteVolume': 8.5735704, 'ask': 0.0001365, 'close': None, 'percentage': None, 'baseVolume': None, 'open': None, 'bid': 0.0001355, 'change': None, 'first': None}
```

Their pairing is reversed, as is the price. 

```
1 / 0.00013661 ≈ $7k+
```

We don't change their markets, what we get from their endpoint here: https://c-cex.com/t/api_pub.html?a=getmarkets, you'll see that that particular pair has USD as base currency (before the slash), BTC as quote currency.

You can get the full list of markets by running the `symbols` example in your preferred language. Hope it answers your question. Cheers!

**Comment by phil-steve** [comment]
What an amazing answer! Thanks so much for taking the time to reply & building such an incredible tool! Saves me literally weeks of coding&headache! Cheers!
