### ISSUE TITLE
[coinfloor] api gives wrong fee data for transfers

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5244]
The transfers we get from coinfloor incorrectly show a zero fee:

```
{
    "id": 70419,
    "fee": "0.0000",
    "usd": "0",
    "xbt": "-0.1000",
    "type": 1,
    "xbt_usd": null,
    "datetime": "2017-03-27 09:25:30",
    "order_id": null
  }
```

We should ignore these as a fee is actually charged (https://www.coinfloor.co.uk/fees), in this case it's 0.0005BTC which I can confirm is what was received (in tx 6eb04790927a57de90b3d650d30a6ec7fc78d6e29df085744fa74cde0e6cd2ea).

The fee hasn't changed in years, at least for BTC.  Perhaps we could take the same approach as in other exchanges and hard code the fee into the transaction object?

**Comment by ttodua** [comment]
Exchange was renamed to CoinCorner, and is no longer a part of CCXT. Closing the issue.
