### ISSUE TITLE
suggestion: add parseMyTrade method

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5250]
There are a number of places where the shape of the data for `fetchMyTrades` differs sufficiently from the result of `fetchTrades`.  We could consider adding `parseMyTrade(s)` which in the base class could just delegate to the existing method(s).

**Comment by frosty00** [comment]
Not sure how we could do this, since in the base class the methods are defined as stubs that throw `NotImplemented`. We could do a try, catch in the base class but that is kinda ugly. Ideally exchanges should have a single trade object...

**Comment by npomfret** [comment]
Where are the stubs defined?

**Comment by kroitor** [comment]
> Ideally exchanges should have a single trade object...

I agree with this.

> We could consider adding parseMyTrade(s) which in the base class could just delegate to the existing method(s).

Tbh, I don't think that adding parseMyTrade is good in the long-term. I think if we keep it the way it is, the exchanges will ultimately have to normalize their response types... I don't think we should relax the standard, because that boils down to no standard. 

Lmk your thoughts.

**Comment by npomfret** [comment]
It's a subtle one. If we were doing this with objects I'd maybe have a `Trade` object which is extended by a `MyTrade` object (containing order id, fee etc).  They are related of course, but they are definitely different.  No exchange (I think) publishes the order id associated to a trade in their public trade feed.  But every exchange (I think), does provide the order id in the private trade feed. And occasionally, exchanges have, for no obvious reason, a completely different set of fields for these two objects that more or less represent the same thing.

**Comment by kroitor** [comment]
>No exchange (I think) publishes the order id associated to a trade in their public trade feed. 

> But every exchange (I think), does provide the order id in the private trade feed.

I think you're wrong on both claims ) At least, I know of many exchanges who actually do the former and the latter, and in a distributed environment most of the info is public, so in general I would rather encourage unification of the structure.

> If we were doing this with objects I'd maybe have a Trade object which is extended by a MyTrade object (containing order id, fee etc).

I am approaching this from the opposite direction, in other words, suppose there is already a Trade class (that is our unified structure) and that trade class contains all the commonly used fields of a personal trade. However for public trades those fields are empty or null. That is basically the same story, one abstraction wraps another, but thinking in terms of plain json structures makes everything a lot more portable. Ideally, the code that would work with those structures will be a lot easier to write and manage. 

> And occasionally, exchanges have, for no obvious reason, a completely different set of fields for these two objects that more or less represent the same thing.

We're far from the ideal now, of course, therefore we have to keep some workarounds there, but in this case i think encouraging unification and standardization is better than relaxing the rules in the long-term. It may be a bit more convenient now to code parseTrade and parseMyTrade separately, but this short-term convenience can cost us more time on coding the entire zoo of parsers in the long run.

Nothing really forbids what you say, and, in fact, as you know, we already have parseTrade and parseMyTrade in the master branch with some exchanges, but this is probably not the best design direction strategically.
