### ISSUE TITLE
EXMO problems

### ISSUE THREAD

**Issue by WoK-E** [ccxt/ccxt#5257]
- OS: Linux
- Programming Language version: PHP 7.2
- CCXT version: 1.18.643
- Exchange: EXMO
- Method: fetchOrderTrades(), cancelOrder(), fetchClosedOrders()

I have the following strange(?) problem: fetch_open_orders() returns all the open orders correctly. When I call fetchOrderStatus() for the orders returned by fetch_open_orders(), the statuses are returned correctly. When I call fetchOrderTrades() for the orders returned by fetch_open_orders() I get and OrderNotFound exception. cancelOrder() also fails.
Furthermore, fetchClosedOrders() returns an empty array.

Not sure if it is a ccxt problem or an EXMO problem. Any help would be much appreciated.

**Comment by kroitor** [comment]
@WoK-E hi! 

Exmo `fetchClosedOrders` is emulated: 

```PHP
mbp:ccxt igorkroitor$ php -f examples/php/cli.php exmo has
exmo->has ()
Array
(
    [cancelAllOrders] =>
    [cancelOrder] => 1
    [cancelOrders] =>
    [CORS] =>
    [createDepositAddress] =>
    [createLimitOrder] => 1
    [createMarketOrder] => 1
    [createOrder] => 1
    [deposit] =>
    [fetchBalance] => 1
    [fetchClosedOrders] => emulated  // ←------------ HERE
    [fetchCurrencies] => 1
    [fetchDepositAddress] => 1
    [fetchDeposits] =>
    [fetchFundingFees] => 1
    [fetchL2OrderBook] => 1
    [fetchLedger] =>
    [fetchMarkets] => 1
    [fetchMyTrades] => 1
    [fetchOHLCV] => emulated
    [fetchOpenOrders] => 1
    [fetchOrder] => emulated
    [fetchOrderBook] => 1
    [fetchOrderBooks] => 1
    [fetchOrders] => emulated
    [fetchTicker] => 1
    [fetchTickers] => 1
    [fetchTrades] => 1
    [fetchTradingFee] => 1
    [fetchTradingFees] => 1
    [fetchTradingLimits] =>
    [fetchTransactions] => 1
    [fetchWithdrawals] =>
    [privateAPI] => 1
    [publicAPI] => 1
    [withdraw] => 1
    [fetchOrderTrades] => 1
)
```

The emulation works via the `.orders` cache. Please, read about how it works here: https://github.com/ccxt/ccxt/wiki/Manual#orders-cache

If you're recreating the exchange instance and not serializing the orders cache, an emulated fetchClosedOrders will not be able too see the previous orders created with another instance, unless you reload the `.orders` cache upon restart from your storage.

Let us know if the `.orders` cache section does not answer your question.

**Comment by WoK-E** [comment]
OK, after reading through the code, I think I cannot do what I want

First I create an instance of the exchange.
Then, for other exchanges (e.g. poloniex), I create an order and then check 'status' and 'trades' of the returned array. Later on, if the order is not closed, I call fetchOrderStatus, and fetchOrderTrades or fetchMyTrades to get an updated status and any further trades made. If no trade has been made for this order, I cancel the order.

Do I understand correctly that I cannot use this scenario with exmo? 
I can only get closed orders for orders made using ccxt (because of the api provided by exmo and the emulation). Also, fetchOrderTrades() seems to work with closed orders only, and cancelOrder does not seem to work.

Many thanks for your help.

**Comment by kroitor** [comment]
> Do I understand correctly that I cannot use this scenario with exmo?

It can be used if you change it a bit:

> First I create an instance of the exchange. Then, for other exchanges (e.g. poloniex), I create an order and then check 'status' and 'trades' of the returned array. 

↑ between the above and the following ↓ there should be no restart or no recreation of exchange instance. If you're recreating the exchange instance, then save `exchange.orders` to a json-file and reload it upon recreating the exchange later.

> Later on, if the order is not closed, I call fetchOrderStatus, and fetchOrderTrades or fetchMyTrades to get an updated status and any further trades made. If no trade has been made for this order, I cancel the order.

> Also, fetchOrderTrades() seems to work with closed orders only, and cancelOrder does not seem to work.

Those are the limitations on the exchange side, we can't really workaround those, because we can't invent the missing info or the missing endpoints, unfortunately.

**Comment by WoK-E** [comment]
Yes, I understand that it is because of the limitations of the exchange. The second part (kind of) works, or to be more accurate I "make" it work since fetchMyTrades returns the trades correctly.

What I forgot to mention is that the array returned by create_order() is always incorrect with regards to the order status and trades made. I have the feeling that exmo does not link an order with its trades, unless the order has been closed or cancelled. Again, a limitation of the exmo API.

Once more, many thanks for your support.
