### ISSUE TITLE
Coinone: incorrect side of trade

### ISSUE THREAD

**Issue by alinaKava** [ccxt/ccxt#5258]
I created two trades (two market orders) - the first one is sell and the second one is buy. Empirically "is_ask" : "0" means sell order. Have a look on attachment (these trades are mine). Also you can check by price and date - with minimal time difference sell price should be less than buy price.
https://github.com/ccxt/ccxt/blob/master/python/ccxt/coinone.py#L227
![image](https://user-images.githubusercontent.com/6782165/59119565-d29c5200-895b-11e9-8b14-7f882984eacf.png)

**Comment by kroitor** [comment]
Hi! I suggest to move this discussion here: https://github.com/ccxt/ccxt/pull/4312 ← this has been addressed previously, and, apparently, Coinone docs claim 1 = sell, 0 = buy. 

https://doc.coinone.co.kr/#operation/public_api_trades

<img width="473" alt="Screen Shot 2019-06-08 at 01 54 09" src="https://user-images.githubusercontent.com/1294454/59137404-55d79b00-8990-11e9-9933-514b32843c89.png">

It sounds like you're confusing the side of the trade as seen from you point of view with the side of the public trade (the taker side) as seen by Coinone. The Coinone exchange will not post your side in public trades – it will post the taker side there.

Let us know if that doesn't answer the question.
