### ISSUE TITLE
withdraw tokens that need memo/memo id

### ISSUE THREAD

**Issue by chiajoe** [ccxt/ccxt#526]
Some of the coins need extra information beside the wallet address like memo id as withdraw parameter, how to withdraw/deposit that type of coins ?

**Comment by kroitor** [comment]
@chiajoe all methods support the extra `params` argument (https://github.com/ccxt/ccxt/wiki). You can pass your additional values in it. Does this answer your question?

**Comment by chiajoe** [comment]
Hi,

Thx for the fast response. I already tried that way. Can’t find any information about withdrawal through api to a address that need that additional memo parameter on the exchanges website it self.

Thought maybe you guys know a way to do that.

**Comment by kroitor** [comment]
@chiajoe it's hard to help without even knowing which exchange it is, and what you are trying to achieve... Can you show some code or describe it in more detail?

**Comment by chiajoe** [comment]
first of all thank you for this super library. 

I want just withdraw a pair, but some of the coins like XRP or SBD have extra fields like ‘memo’  or ’tag’  additional to there deposit addresses.
I can withdraw through ccxd lib all coins that has just a normal wallet deposit address.

The code works and there are no problems , just wan’t to know how to add the extra 'memo’ parameter.

The exchanges i try to accomplish this is  BINANCE, POLONIEX, BITTREX.

I want for example withdraw SBD from BITTREX to POLONIEX.

to withdraw SBD from BITTREX directly in the backoffice of BITTREX , i need to fill in the address field  ‘poloniex' and memo something like ‘dSRe7egHYT786’
to withdraw XRP is the same there is a address and there is a tag.

what i already read in forms is that  POLONIEX uses ‘paymentId' as extra parameter that is reserved for the extra tag.

so my code looks like :


let depositaddress = ‘rPHMhWBsfF9iZXYj3aAzJVkYDTDNSyLdKc'; 
let param = {‘paymentId’: ‘676344753’ } // the tag that XRP needs put here ?? and what key name use here ?
exchange.withdraw(’XRP/BTC', parseFloat(amount).toFixed(8), despositaddress, param).then(res => {
    if (res.id != undefined) {
        callback(null, res);
    }
}).catch(err => {
    callback(err, null);
});

**Comment by kroitor** [comment]
@chiajoe your code looks absolutely fine, but you cannot withdraw XRP/BTC. You can only withdraw either XRP or BTC. You basically withdraw one currency, not a pair of currencies. Also, in your code I see a backtick (&#96;) symbol instead of quotes (\') in several places. Apart from that your code should work fine.

Try this (assuming your `exchange` instance has properly set up keys):

```
let depositaddress = 'rPHMhWBsfF9iZXYj3aAzJVkYDTDNSyLdKc';
let param = {'paymentId': '676344753' } // this is the correct key for poloniex
exchange.withdraw('XRP/BTC', parseFloat(amount).toFixed(8), depositaddress, param).then(res => {
    if (typeof res.id != 'undefined') { // typeof is a much better way to check if it is defined
        callback(null, res);
    }
}).catch(err => {
    callback(err, null);
});
```

The above code should work. Do you have any problems with it?

The code for other exchanges should work in the same manner, but parameter name can differ, see their docs for details, should be straightforward as it is with Poloniex. Does this answer your question?

**Comment by chiajoe** [comment]
This answered my question. Thank you very much.
