### ISSUE TITLE
Possible bug in commonCurrencies

### ISSUE THREAD

**Issue by jdieks** [ccxt/ccxt#5260]
- OS: *
- Programming Language version: python
- CCXT version: 1.18.593-643
- Exchange: bitfinex
- Method: commonCurrencies

Hi, I'm using the commonCurrencies in my code for margin trading on bitfinex. It think this has been broken in a recent release. You can see this the following way:

if I do:
```Python
print(str(ccxt.bitfinex.commonCurrencies.items()))
```
I get:
```
dict_items([('XBT', 'BTC'), ('BCC', 'BCH'), ('DRK', 'DASH'), ('BCHABC', 'BCH'), ('BCHSV', 'BSV')])
```

While this is not the list found in the bitfinex.py.. My guess is that this is Kraken (?)

Or am I making a mistake somewhere?

**Comment by kroitor** [comment]
> Or am I making a mistake somewhere?

Yes, the `commonCurrencies` is not a list of currencies for the exchange, it's a list of substitutions for for all the exchanges, which is inherited from the Exchange base class.

If you want to get a list of currencies, you should check `.currencies` instead of `.commonCurrencies`:

```Python
from pprint import pprint
import ccxt
exchange = ccxt.bitfinex({ 'enableRateLimit': True })
exchange.load_markets()
pprint(exchange.currencies)
```

Let us know if that doesn't answer the question )

**Comment by jdieks** [comment]
Hi Kroitor,

Thanks for the reply. Yes, I see how it works now.
In an older version I used the ccxt.bitfinex.commonCurrencies.items() list to convert the ccxt commoncurrencies back to the ones that the api of bitfinex wants to see (e.g. BCH:BAB).

But I see that I can indeed do exactly the same thing with the currencies command. Thanks for the help.

Have a good night.
