### ISSUE TITLE
okex v3 invalid sign issue.

### ISSUE THREAD

**Issue by billwang1990** [ccxt/ccxt#5265]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it
