### ISSUE TITLE
GRIN coin not showing in load_markets()

### ISSUE THREAD

**Issue by asafravid** [ccxt/ccxt#5266]
OS: `Windows`
`Python 3.7`
CCXT version: `ccxt-1.18.643`
method: `load_markets()`

`bit2c` Exchange has `GRIN` coin in markets (`GRIN/NIS`), but `load_markets()` fails to show it.
This might be related to currencies... I'm still investigating and will update this issue if I find more information. However perhaps you can fix/check in the meanwhile:

Code:

    markets = exchange.load_markets()
    print('markets = {}'.format(markets))

Result:

    markets = {'BTC/NIS': {'percentage': True, 'maker': 0.005, 'taker': 0.005, 'precision': {}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'id': 'BtcNis', 'symbol': 'BTC/NIS', 'base': 'BTC', 'quote': 'NIS'}, 'ETH/NIS': {'percentage': True, 'maker': 0.005, 'taker': 0.005, 'precision': {}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'id': 'EthNis', 'symbol': 'ETH/NIS', 'base': 'ETH', 'quote': 'NIS'}, 'BCH/NIS': {'percentage': True, 'maker': 0.005, 'taker': 0.005, 'precision': {}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'id': 'BchAbcNis', 'symbol': 'BCH/NIS', 'base': 'BCH', 'quote': 'NIS'}, 'LTC/NIS': {'percentage': True, 'maker': 0.005, 'taker': 0.005, 'precision': {}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'id': 'LtcNis', 'symbol': 'LTC/NIS', 'base': 'LTC', 'quote': 'NIS'}, 'ETC/NIS': {'percentage': True, 'maker': 0.005, 'taker': 0.005, 'precision': {}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'id': 'EtcNis', 'symbol': 'ETC/NIS', 'base': 'ETC', 'quote': 'NIS'}, 'BTG/NIS': {'percentage': True, 'maker': 0.005, 'taker': 0.005, 'precision': {}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'id': 'BtgNis', 'symbol': 'BTG/NIS', 'base': 'BTG', 'quote': 'NIS'}, 'BSV/NIS': {'percentage': True, 'maker': 0.005, 'taker': 0.005, 'precision': {}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'id': 'BchSvNis', 'symbol': 'BSV/NIS', 'base': 'BSV', 'quote': 'NIS'}}

**Comment by asafravid** [comment]
Investigating within `def load_market()` shows that for these debug print outs:

    def load_markets(self, reload=False, params={}):
        print('[load_markets] reload={}'.format(reload))
        if not reload:
            print('[load_markets] self.markets={}'.format(self.markets))
            if self.markets:
                print('[load_markets] self.markets_by_id={}'.format(self.markets_by_id))
                if not self.markets_by_id:
                    return self.set_markets(self.markets)
                return self.markets


The problem already exists in `self.markets` and `self.markets_by_ids`:

    [load_markets] reload=False
    [load_markets] self.markets={'BTC/NIS': {'percentage': True, 'maker': 0.005, 'taker': 0.005, 'precision': {}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'id': 'BtcNis', 'symbol': 'BTC/NIS', 'base': 'BTC', 'quote': 'NIS'}, 'ETH/NIS': {'percentage': True, 'maker': 0.005, 'taker': 0.005, 'precision': {}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'id': 'EthNis', 'symbol': 'ETH/NIS', 'base': 'ETH', 'quote': 'NIS'}, 'BCH/NIS': {'percentage': True, 'maker': 0.005, 'taker': 0.005, 'precision': {}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'id': 'BchAbcNis', 'symbol': 'BCH/NIS', 'base': 'BCH', 'quote': 'NIS'}, 'LTC/NIS': {'percentage': True, 'maker': 0.005, 'taker': 0.005, 'precision': {}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'id': 'LtcNis', 'symbol': 'LTC/NIS', 'base': 'LTC', 'quote': 'NIS'}, 'ETC/NIS': {'percentage': True, 'maker': 0.005, 'taker': 0.005, 'precision': {}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'id': 'EtcNis', 'symbol': 'ETC/NIS', 'base': 'ETC', 'quote': 'NIS'}, 'BTG/NIS': {'percentage': True, 'maker': 0.005, 'taker': 0.005, 'precision': {}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'id': 'BtgNis', 'symbol': 'BTG/NIS', 'base': 'BTG', 'quote': 'NIS'}, 'BSV/NIS': {'percentage': True, 'maker': 0.005, 'taker': 0.005, 'precision': {}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'id': 'BchSvNis', 'symbol': 'BSV/NIS', 'base': 'BSV', 'quote': 'NIS'}}
    [load_markets] self.markets_by_id={'BtcNis': {'percentage': True, 'maker': 0.005, 'taker': 0.005, 'precision': {}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'id': 'BtcNis', 'symbol': 'BTC/NIS', 'base': 'BTC', 'quote': 'NIS'}, 'EthNis': {'percentage': True, 'maker': 0.005, 'taker': 0.005, 'precision': {}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'id': 'EthNis', 'symbol': 'ETH/NIS', 'base': 'ETH', 'quote': 'NIS'}, 'BchAbcNis': {'percentage': True, 'maker': 0.005, 'taker': 0.005, 'precision': {}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'id': 'BchAbcNis', 'symbol': 'BCH/NIS', 'base': 'BCH', 'quote': 'NIS'}, 'LtcNis': {'percentage': True, 'maker': 0.005, 'taker': 0.005, 'precision': {}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'id': 'LtcNis', 'symbol': 'LTC/NIS', 'base': 'LTC', 'quote': 'NIS'}, 'EtcNis': {'percentage': True, 'maker': 0.005, 'taker': 0.005, 'precision': {}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'id': 'EtcNis', 'symbol': 'ETC/NIS', 'base': 'ETC', 'quote': 'NIS'}, 'BtgNis': {'percentage': True, 'maker': 0.005, 'taker': 0.005, 'precision': {}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'id': 'BtgNis', 'symbol': 'BTG/NIS', 'base': 'BTG', 'quote': 'NIS'}, 'BchSvNis': {'percentage': True, 'maker': 0.005, 'taker': 0.005, 'precision': {}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}, 'id': 'BchSvNis', 'symbol': 'BSV/NIS', 'base': 'BSV', 'quote': 'NIS'}}

**Comment by kroitor** [comment]
The markets for `bi2tc` are hardcoded here (not loaded from the exchange, because the exchange does not expose them over the API) https://github.com/ccxt/ccxt/blob/master/js/bit2c.js#L66

You can append more markets to it upon the initialization of the exchange class, or just submit a pull request with new markets added there, we welcome all contributions! )

**Comment by kroitor** [comment]
I've added it in v. 1.18.661 (it will arrive in 10 minutes), so, if you update your version of CCXT the GRIN/NIS market should be there. Let us know if that does not help.

**Comment by asafravid** [comment]
Ok, just know that you can get the following supported coins with this API:
`https://bit2c.co.il/Exchanges/{}/orderbook.json` where `{}` can be: PAIRS = ['BtcNis', 'EthNis', 'BchabcNis', 'LtcNis', 'EtcNis', 'BtgNis', 'BchsvNis', 'GrinNis']

**Comment by asafravid** [comment]
I will upgrade `ccxt` and let you know, thanks for the quick response!

**Comment by kroitor** [comment]
> Ok, just know that you can get the following supported coins with this API:

The problem is to get the full list of pairs from bit2c endpoint to avoid hardcoding. I could substitute any pair from the list into the `https://bit2c.co.il/Exchanges/{}/orderbook.json` instead of `{}`, but to do that, I need to know the full list of pairs (all possible substitutions) in the first place – and users don't want to have a hardcoded list, they want the `bit2c` API to provide the up-date info, because it can change over time (new pairs can be added, like in this case).

**Comment by asafravid** [comment]
Yes, I understand, they publish the API as follows:

    GET https://bit2c.co.il/Exchanges/[BtcNis/EthNis/BchabcNis/LtcNis/EtcNis/BtgNis/BchsvNis/GrinNis]/orderbook.json

**Comment by kroitor** [comment]
> Yes, I understand, they publish the API as follows:

No they don't, because in order to access it, you have to know the list beforehand. So, they don't publish the list of pairs from the API.

**Comment by asafravid** [comment]
Theoretically you can scrape the website (`https://bit2c.co.il/home/api#orderb`) and have the pairs but this is a little dirty...

**Comment by kroitor** [comment]
> Theoretically you can scrape the website (https://bit2c.co.il/home/api#orderb) and have the pairs but this is a little dirty...

Right, we have some web scrapers in other exchanges, but it easily breaks down if they change their markup... Which is a pain to fix. But anyways, we will look into some ways to avoid hardcoding. Thx for reporting and for your involvement!

**Comment by asafravid** [comment]
Upgrading to `ccxt-1.18.661` fixes the issue, `Grin` shows up in the markets list.

**Comment by asafravid** [comment]
BTW I messaged their devs to have a look at this issue so they can hopefully add an API exposing the supported ist

**Comment by kroitor** [comment]
@asafravid awesome, thx again for your help!
