### ISSUE TITLE
Okex: method createOrder returns error 10007

### ISSUE THREAD

**Issue by DmitryVil** [ccxt/ccxt#5272]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10
- Programming Language version: python 
- CCXT version: 1.18.633
- Exchange: okex
- Method: createOrder

After update from version ~ 1.18.550 to method 1.18.633,  exchange okex returns error 10007

**Comment by kroitor** [comment]
@DmitryVil need you verbose request and response, as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by kroitor** [comment]
Also, does it happen with the most recent version 1.18.662?

**Comment by DmitryVil** [comment]
I have put this exchange off.
I will try to check it.


вс, 9 июн. 2019 г. в 23:28, Igor Kroitor <notifications@github.com>:

**Comment by kroitor** [comment]
@DmitryVil I suggest switching to a newer `okex3` version. Let us know if that does not help. Closing this for now. Thx!
