### ISSUE TITLE
Can't fetch data from Bitmex (1m or 5min) 

### ISSUE THREAD

**Issue by Kalelv45** [ccxt/ccxt#5278]
After some time that I'm fetching the historic data (OHLCV). 
I get this error: 
  File "bitmex.py", line 67, in scrape_candles_to_csv
    ohlcv = scrape_ohlcv(exchange, max_retries, symbol, timeframe, since, limit)
  File "bitmex.py", line 39, in scrape_ohlcv
    if ohlcv[0][0] >= earliest_timestamp:
TypeError: 'NoneType' object is not subscriptable

There is a way save till the point it has arrived? 
What are the best practice to make sure this won't happen. Some times it reaches 2018 and then it just close and I stay empty handed, since it won't save the 1m candles. 
- OS: MacOS
- Programming Language version: python 3.7
- CCXT version:(last, just update my machine) 
- Exchange: Bitmex 
- Method: binance-fetch-ohlcv-to-csv.py 
I changed the binance at the end with bitmex.

**Comment by kroitor** [comment]
@Kalelv45 add `'verbose': True` here: https://github.com/ccxt/ccxt/blob/master/examples/py/binance-fetch-ohlcv-to-csv.py#L59 and when you catch that error – post the last verbose request/response pair (we need both the request and the response that triggered the error).

**Comment by kroitor** [comment]
Closing this for now, let us know if you have further questions on it.
