### ISSUE TITLE
Binance price_to_precision() Invalid format specifier

### ISSUE THREAD

**Issue by oswaldonfire** [ccxt/ccxt#528]
Hi, 
with this code:

`exch = ccxt.binance({
                      'apiKey' : 'xxx',
                      'secret' : 'xxx',
                      })
buyOrder = exch.create_limit_buy_order('ETH/BTC', 0.027, 0.042, {})`

I am seeing this ValueError:

`Traceback (most recent call last):
  File "C:\dev\crypto-accumulator\ccxtTest.py", line 72, in <module>
    main()
  File "C:\dev\crypto-accumulator\ccxtTest.py", line 67, in main
    buyOrder = exch.create_limit_buy_order('ETH/BTC', 0.027, 0.042, {})
  File "C:\Miniconda3\lib\site-packages\ccxt\base\exchange.py", line 882, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', *args)
  File "C:\Miniconda3\lib\site-packages\ccxt\binance.py", line 430, in create_order
    'price': self.price_to_precision(symbol, price),
  File "C:\Miniconda3\lib\site-packages\ccxt\base\exchange.py", line 703, in price_to_precision
    return ('{:.' + str(self.markets[symbol]['precision']['price']) + 'f}').format(float(price))
ValueError: Invalid format specifier`

I know this may not be optimal, but I have been able to get it working on my end by changing line 703 in ccxt/base/exchange.py from

`return ('{:.' + str(self.markets[symbol]['precision']['price']) + 'f}').format(float(price))`
to 
`return str(round(float(price), ndigits = int(self.markets[symbol]['precision']['price'])))`.

**Comment by kroitor** [comment]
@oswaldonfire thank you for reporting this! Will look into it and will fix it for Python asap!

**Comment by kroitor** [comment]
This issue was fixed in version 1.10.51. Thx again for reporting this, appreciate your feedback!
