### ISSUE TITLE
Is it possible for symbols to automatically change?

### ISSUE THREAD

**Issue by aurecchia** [ccxt/ccxt#5280]
Hello, this is just a question, not a bug/feature request. Sorry if this was already explained in the documentation, I could not find anything addressing that exactly.

Are the symbols ever expected to change *automatically* based on capitalization, or can we rely on always listing the same crypto with the same symbol?
For example, currently `HOT` is used for `Holo` (as per the documentation on [naming consistency](https://github.com/ccxt/ccxt/wiki/Manual#notes-on-naming-consistency)). If a new coin with the same symbol and a higher capitalization were to appear on some of the markets, could we still rely on CCXT to refer to `Holo` as `HOT`? (and potentially with a new symbol for this new coin?)

Thank you in advance!

**Comment by kroitor** [comment]
Hi! )

I've added the answers to the Manual, here: https://github.com/ccxt/ccxt/blob/master/wiki/Manual.md#questions-on-naming-consistency

The update will be available on the main wiki in 10 minutes )

In regard of token/symbolic unification, we're also looking up to projects for onchain standards, like http://www.truset.com, for example.

Let us know if that doesn't answer the questions )

**Comment by aurecchia** [comment]
Hey,
Thank you for your quick reply.
Yes, that clarifies things.
Thanks a lot :D
