### ISSUE TITLE
How to implement token bucket in python?

### ISSUE THREAD

**Issue by IgorMBorushek** [ccxt/ccxt#5282]
There are no clear instructions in the docs. It's mentioned in various comments that there is an implementation in JS and PY available but I haven't found any instructions on how to apply it. Can someone give some pointers? Thanks.

**Comment by kroitor** [comment]
Hi @IgorMBorushek !

Pardon for the delay with the answer, I will try to add a usage example as soon as I can.

Unfortunately, tokenBucket is not documented yet, the code and some explanations can be found here:

- https://github.com/ccxt/ccxt/blob/master/js/base/functions/throttle.js
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/base/throttle.py
- https://en.wikipedia.org/wiki/Token_bucket

**Comment by ttodua** [comment]
this issue has become too old, if anyone has any input, feel free to raise this topic up again.
