### ISSUE TITLE
Can not fetch OKEX K Line in V1/V2

### ISSUE THREAD

**Issue by helldragonx** [ccxt/ccxt#5287]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
   MAC
- Programming Language version:
  Python
- CCXT version:
  Latest
- Exchange:
  OKEX
- Method:
  fetch_ohlcv

current version returns 20006, miss a necessary parameter 'type',  I had added it in okcoinusd.py / create_request, just put the type in the return dictionary, and it works

**Comment by helldragonx** [comment]
and surely shall judge whether it has 'type' before add it to return dictional

**Comment by kroitor** [comment]
This should be fixed in 1.18.679, the new build will arrive in 10 minutes! Let us know if you still have difficulties with it after upgrading to the most recent version 1.18.679. Thx for reporting!
