### ISSUE TITLE
python transpile: undefined name 'null'

### ISSUE THREAD

**Issue by PolozovT** [ccxt/ccxt#5289]
Hi! I have this error in line:
            'high': parseFloat (ticker['high'])

ticker['high'] is not empty!
What does it mean?

**Comment by kroitor** [comment]
Hi! You can check the verbose response with `exchange.verbose = true` before or inside the `fetchTicker` call to see what's going on with that value. If that doesn't help, please paste the verbose output here. Thx!

**Comment by kroitor** [comment]
Alternatively, use `safeFloat` as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#sanitizing-input-with-safe-methods

**Comment by PolozovT** [comment]
it doesn't help me

**Comment by kroitor** [comment]
@PolozovT let's discuss this within the code in the PR itself: https://github.com/ccxt/ccxt/pull/5276, can you point out there in the code comments which particular line does not work?

**Comment by PolozovT** [comment]
all happened, thank you)
