### ISSUE TITLE
OKEX fetch trades failed

### ISSUE THREAD

**Issue by helldragonx** [ccxt/ccxt#5291]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
   Mac
- Programming Language version:
   Python
- CCXT version:
   Latest 
- Exchange:
   OKEX
- Method:
   fetch_trades
OKEX now changed the response string of load_markets, the symbol of each future market has the additional due date string in the tail. so fetch_trades failed when check the market use former symbol format

**Comment by kroitor** [comment]
@helldragonx I suggest to switch to `okex3`, because `okex` v1 will not be maintained further. Let us know if that does not help.

**Comment by helldragonx** [comment]
hi dear, I keep V1 is reasonable, you know, in some rush hour, only V1 works...

**Comment by kroitor** [comment]
@helldragonx can you post the verbose request/response for it?

**Comment by helldragonx** [comment]
Hi, I'm fixing this issue by adapting the symbol to markets, 
so that's ok, thanks.
