### ISSUE TITLE
fetchTrades does not handle since parameter

### ISSUE THREAD

**Issue by kyjak** [ccxt/ccxt#5293]
- OS: win10
- Programming Language version: nodeJS, latest
- CCXT version: 1.18.685
- Exchange: kraken
- Method: fetchTrades

If I supply a since microtimestamp of 2018-01-01 and limit of 1,to get only 1 trade, I get the latest value as follows and not 2018 one. When I use a browser to try the kraken API, it works ok (https://api.kraken.com/0/public/Trades?pair=xbtusd&since=0)

```
{
  "since": 1560415023540,
  "value": [
    [
      {
        "info": [
          "229.89000",
          "1.03544657",
          1560415023.5403,
          "b",
          "l",
          ""
        ],
        "timestamp": 1560415023540,
        "datetime": "2019-06-13T08:37:03.540Z",
        "symbol": "ETH/EUR",
        "type": "limit",
        "side": "buy",
        "price": 229.89,
        "amount": 1.03544657,
        "cost": 238.0388119773
      }
    ]
  ]
}
```

**Comment by kroitor** [comment]
> If I supply a since microtimestamp of 2018-01-01 and limit of 1,to get only 1 trade, I get the latest value as follows and not 2018 one.

Kraken does not support date-based pagination, and the `since` should contain a trade `id`, not a timestamp. This is how Kraken API works, not an issue in CCXT.

https://www.kraken.com/en-us/features/api#get-recent-trades 

In order to pass that parameter to the exchange with overrided `params`: https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

So the correct usage is:

```JavaScript
'use strict';
const ccxt = require ('ccxt')
const exchange = new ccxt.kraken ({
   'enableRateLimit': true, // required by the Manual https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})
;(async () => {
    const symbol = 'ETH/EUR'
    const since = 1560430233878703138 // ←--------------------- this goes here ↓
    const trades = await exchange.fetchTrades (symbol, undefined, undefined, { since })
}) ()
```

However, it won't help you get the trades history since year 2018, because that entire endpoint is specialized for *recent trades*, so it will allow queries within a very limited range of `since` ids, and which id corresponds to which date – you don't know. Most exchanges will limit historical data and it's documented in the Manual.

Let us know if that does not answer the question.

**Comment by kyjak** [comment]
> 
> 
> > If I supply a since microtimestamp of 2018-01-01 and limit of 1,to get only 1 trade, I get the latest value as follows and not 2018 one.
> 
> Kraken does not support date-based pagination, and the `since` should contain a trade `id`, not a timestamp. This is how Kraken API works, not an issue in CCXT.
> 
> https://www.kraken.com/en-us/features/api#get-recent-trades
> 
> In order to pass that parameter to the exchange with overrided `params`: https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
> 
> So the correct usage is:
> 
> ```js
> 'use strict';
> const ccxt = require ('ccxt')
> const exchange = new ccxt.kraken ({
>    'enableRateLimit': true, // required by the Manual https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
> })
> ;(async () => {
>     const symbol = 'ETH/EUR'
>     const since = 1560430233878703138 // ←--------------------- this goes here ↓
>     const trades = await exchange.fetchTrades (symbol, undefined, undefined, { since })
> }) ()
> ```
> 
> However, it won't help you get the trades history since year 2018, because that entire endpoint is specialized for _recent trades_, so it will allow queries within a very limited range of `since` ids, and which id corresponds to which date – you don't know. Most exchanges will limit historical data and it's documented in the Manual.
> 
> Let us know if that does not answer the question.

not entirely true, the response of that endpoint is structured as "{"error":[],"result":{"XETHZEUR":[["20.00000","4.50000000",1438945790.9098,"b","l",""],["20.00000","0.48000000",1438945791.2365,"b","l",""],["20.00000","3.37215150",1438945954.1212,"s","l",""],
where there is no tradaId as you say. This is the public endpoint, not private.
When you try this in the browser, with since = 0, it goes well beyond year 2018.
Will try to use your approach and reply.

**Comment by kroitor** [comment]
> This is the public endpoint, not private.

That's right.

> When you try this in the browser, with since = 0, it goes well beyond year 2018.

Then you should be able to pass 0 like shown in the example above )

> Will try to use your approach and reply.

Ok ) We will be happy if you let us know whether it helped resolve the issue or not. Thx! )

**Comment by kroitor** [comment]
Here's the CCXT-equivalent of what you opened in the browser:

```JavaScript
'use strict';
const ccxt = require ('ccxt')
const exchange = new ccxt.kraken ({
   'enableRateLimit': true, // required by the Manual https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})
;(async () => {
    const symbol = 'ETH/EUR'
    const since = 0 // ←----------------------------------------- this goes here ↓
    const trades = await exchange.fetchTrades (symbol, undefined, undefined, { since })
}) ()
```

It returns trades since 2015 indeed.

```
                id | order |     timestamp |                 datetime |  symbol |   type | side |   price |        amount |                  cost | fee
--------------------------------------------------------------------------------------------------------------------------------------------------------
                    |       | 1438945790909 | 2015-08-07T11:09:50.909Z | ETH/EUR |  limit |  buy |      20 |           4.5 |                    90 |
                    |       | 1438945791236 | 2015-08-07T11:09:51.236Z | ETH/EUR |  limit |  buy |      20 |          0.48 |                   9.6 |
                    |       | 1438945954121 | 2015-08-07T11:12:34.121Z | ETH/EUR |  limit | sell |      20 |     3.3721515 |     67.44303000000001 |
...
```

**Comment by kyjak** [comment]
I redid the code to work with raw kraken api and they return a "last" property along the trade data to be used as "since" in the next request. Do not see this returned in ccxt version of the call.
"...["0.73684","21.93726000",1439315345.8462,"s","l",""]]
**,"last":"1439315345846191902"**}}"

**Comment by kroitor** [comment]
@kyjak 

```
node examples/js/cli kraken fetchTrades ETH/EUR undefined undefined '{"since":0}' --verbose
```

Starts like this:

<img width="1262" alt="Screen Shot 2019-06-13 at 18 06 13" src="https://user-images.githubusercontent.com/1294454/59444183-1385e200-8e06-11e9-8f65-4e2a35a46915.png">

Then outputs lots of verbose data...

Then it gets to the actual fetchTrades call:

<img width="1262" alt="Screen Shot 2019-06-13 at 18 06 46" src="https://user-images.githubusercontent.com/1294454/59444226-28fb0c00-8e06-11e9-9446-1c29ab6adfbd.png">

And in the end it outputs the set of trades in a table, which looks like so:

<img width="1262" alt="Screen Shot 2019-06-13 at 18 08 31" src="https://user-images.githubusercontent.com/1294454/59444278-47610780-8e06-11e9-89b8-f4892d81cc5f.png">


If you look at the last trade – you'll see that it has an id, that's the last trade id, reported by Kraken.

<img width="1262" alt="Screen Shot 2019-06-13 at 18 06 54" src="https://user-images.githubusercontent.com/1294454/59444349-619ae580-8e06-11e9-91d9-3bc3097acca0.png">

Here's the id:

```
                    |       | 1439314147187 | 2015-08-11T17:29:07.187Z | ETH/EUR |  limit |  buy |    0.79 |      155.9148 |    123.17269200000001 |
                    |       | 1439314148147 | 2015-08-11T17:29:08.147Z | ETH/EUR |  limit |  buy |    0.79 |  798.62480473 |        630.9135957367 |
                    |       | 1439314606890 | 2015-08-11T17:36:46.890Z | ETH/EUR |  limit | sell |     0.8 |         68.65 |     54.92000000000001 |
                    |       | 1439314732350 | 2015-08-11T17:38:52.350Z | ETH/EUR |  limit | sell |   0.789 |         83.85 |              66.15765 |
                    |       | 1439314732700 | 2015-08-11T17:38:52.700Z | ETH/EUR |  limit | sell |   0.789 |   84.23584283 |        66.46207999287 |
                    |       | 1439314860839 | 2015-08-11T17:41:00.839Z | ETH/EUR |  limit | sell |    0.78 |       0.00077 |             0.0006006 |
                    |       | 1439314860848 | 2015-08-11T17:41:00.848Z | ETH/EUR |  limit | sell |    0.78 |   14.33305128 |    11.179779998399999 |
                    |       | 1439314860875 | 2015-08-11T17:41:00.875Z | ETH/EUR |  limit | sell |    0.78 |    0.00021794 |          0.0001699932 |
                    |       | 1439314892486 | 2015-08-11T17:41:32.486Z | ETH/EUR |  limit | sell |    0.78 |   56.19273078 |         43.8303300084 |
                    |       | 1439315085629 | 2015-08-11T17:44:45.629Z | ETH/EUR |  limit |  buy | 0.81973 |            10 |                8.1973 |
                    |       | 1439315345816 | 2015-08-11T17:49:05.816Z | ETH/EUR |  limit | sell |    0.75 |        33.565 |              25.17375 |
1439315345846191902 |       | 1439315345846 | 2015-08-11T17:49:05.846Z | ETH/EUR |  limit | sell | 0.73684 |      21.93726 |         16.1642506584 |
↑ here it is, and only the last trade in the result set has it
```

You can use `cli` to check your results.

In code that would look like so:

```JavaScript
'use strict';
const ccxt = require ('ccxt')
const exchange = new ccxt.kraken ({
   'enableRateLimit': true, // required by the Manual https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})
;(async () => {
    const symbol = 'ETH/EUR'
    const since = 0 // ←----------------------------------------- this goes here ↓
    const trades = await exchange.fetchTrades (symbol, undefined, undefined, { since })
    const numTrades = trades.length
    if (trades.length > 0) {
        const lastId = trades[trades.length - 1]['id']
        console.log ('Last trade id for iteration purposes: ' + lastId)
    }
}) ()
```
