### ISSUE TITLE
New Exchange: HollaEx

### ISSUE THREAD

**Issue by brandonkimmmm** [ccxt/ccxt#5296]
All endpoints added and tested. Failed test for Python, unsure why.

```
<type 'exceptions.KeyError'> 'hollaex' 

          File "python/test/test.py", line 403, in <module>
            main()

          File "python/test/test.py", line 380, in main
            exchange = exchanges[argv.exchange] (explain @ run-tests.js:173)


FAIL ["hollaex"] (run-tests.js:251)
```

**Comment by kroitor** [comment]
You can run that test with Python to see more details:

```shell
# in the ccxt folder
$ npm run build
$ python python/test/test.py hollaex
```

**Comment by brandonkimmmm** [comment]
Thanks for the reply. Unfortunately, I'm still getting the same error messages...

```
root@1b73c2b29588:/ccxt# python python/test/test.py hollaex --verbose
<type 'exceptions.KeyError'> 'hollaex' 

  File "python/test/test.py", line 403, in <module>
    main()

  File "python/test/test.py", line 380, in main
    exchange = exchanges[argv.exchange]

<type 'exceptions.KeyError'> 'hollaex' 

  File "python/test/test.py", line 403, in <module>
    main()

  File "python/test/test.py", line 380, in main
    exchange = exchanges[argv.exchange]
```

**Comment by kroitor** [comment]
@brandonkimmmm do you see that after running `npm run build`?

**Comment by brandonkimmmm** [comment]
JS and PHP are passing the tests. The only one not passing is Python.

**Comment by kroitor** [comment]
@brandonkimmmm do you have a ccxt installed with pip globally?

**Comment by kroitor** [comment]
If a global `ccxt` is not installed on your system and you still get the error, but you can't run `npm run build` because you don't have `pandoc`, you can skip the build phase and just `npm run export-exchanges` – that should populate the local ccxt package-folder with hollaex and that should fix the KeyError.

**Comment by brandonkimmmm** [comment]
@kroitor I'm running everything through the docker container and dont have ccxt installed globally

**Comment by kroitor** [comment]
@brandonkimmmm then this should work:

```
# in ccxt repo folder
npm run export-exchanges
python python/test/test.py hollaex
```

Let us know if that doesn't help.

**Comment by kroitor** [comment]
Also, before you run the tests`, in order to test the private APIs, I suggest you to create a local `keys.local.json` file in the repo folder with your private key for testing the `fetchBalance`, `fetchOrder`, etc:

`keys.local.json` in the repo root folder:

```
{
    "hollaex": {
        "apiKey": "YOUR_API_KEY",
        "secret": "YOUR_SECRET"
    }
}
```

↑ and then run the tests after adding that file. That will make sure that all tests are fine indeed. No worries, it will not change or alter you balance in any way, all tests are non-intrusive.

**Comment by brandonkimmmm** [comment]
@kroitor Hmmm, I followed the steps but am still getting the same error messages. 

```
root@1b73c2b29588:/ccxt# python python/test/test.py hollaex --verbose
<type 'exceptions.KeyError'> 'hollaex' 

  File "python/test/test.py", line 403, in <module>
    main()

  File "python/test/test.py", line 380, in main
    exchange = exchanges[argv.exchange]

<type 'exceptions.KeyError'> 'hollaex' 

  File "python/test/test.py", line 403, in <module>
    main()

  File "python/test/test.py", line 380, in main
    exchange = exchanges[argv.exchange]
```

I'm working on a fork of the repo that is `246 commits ahead, 371 commits behind ccxt:master.` Could this be a problem? Also, I had to `pip install tox` while inside the docker container. Not sure if that would affect anything.

**Comment by kroitor** [comment]
@brandonkimmmm are you sure that you did `npm run export-exchanges` before trying the tests?

**Comment by brandonkimmmm** [comment]
@kroitor I found the problem. I didn't have ccxt installed as a local package but it was present in the docker container. I'm getting the proper error messages now.

**Comment by kroitor** [comment]
> I didn't have ccxt installed as a local package but it was present in the docker container.

Yep, that's what I was asking about – if it was installed as a local package inside the environment (inside the docker container). Glad you've figured it out! Thx for the feedback!

**Comment by brandonkimmmm** [comment]
@kroitor Now all the tests are passing except for `--python3` tests. Not really getting any useful info either. 

```
root@e46c60995e4e:/ccxt# python3 python/test/test.py hollaex --verbose
<class 'KeyError'> 'hollaex' 

  File "python/test/test.py", line 403, in <module>
    main()

  File "python/test/test.py", line 380, in main
    exchange = exchanges[argv.exchange]

<class 'KeyError'> 'hollaex' 

  File "python/test/test.py", line 403, in <module>
    main()

  File "python/test/test.py", line 380, in main
    exchange = exchanges[argv.exchange]
```
```
root@e46c60995e4e:/ccxt# python3 -V
Python 3.6.7
```

**Comment by kroitor** [comment]
@brandonkimmmm check if you have `pip3 list ccxt` as well, `python` and `python3` may be different as well as `pip` and `pip3`.

**Comment by brandonkimmmm** [comment]
@kroitor Awesome yeah that was the issue. Thanks a lot!

**Comment by lacksfish** [comment]
@kroitor @brandonkimmmm could you elaborate further what a mortal human has to-do inside the docker container to get rid of the KeyError? All I really want to do is run the tests ...

```
FAILED exchangeName (Python): (explain @ run-tests.js:187)

        <type 'exceptions.KeyError'> 'exchangeName' 
        
          File "python/test/test.py", line 409, in <module>
            main()
        
          File "python/test/test.py", line 386, in main
            exchange = exchanges[argv.exchange] (explain @ run-tests.js:190)

FAILED exchangeName (Python 2): (explain @ run-tests.js:187)

        <type 'exceptions.KeyError'> 'exchangeName' 
        
          File "python/test/test.py", line 409, in <module>
            main()
        
          File "python/test/test.py", line 386, in main
            exchange = exchanges[argv.exchange] (explain @ run-tests.js:190)

FAILED exchangeName (Python 3): (explain @ run-tests.js:187)

         (explain @ run-tests.js:190)

WARN exchangeName (PHP): (explain @ run-tests.js:188)

        string(11) "./keys.json"
        PHP Notice:  Undefined index: exchangeName in /ccxt/php/test/test.php on line 230
        PHP Warning:  A non-numeric value encountered in /ccxt/php/test/test.php on line 243
        PHP Warning:  A non-numeric value encountered in /ccxt/php/test/test.php on line 243
        0 (explain @ run-tests.js:190)
FAIL ["exchangeName"] (run-tests.js:268)
All done, 1 failed (run-tests.js:273)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ccxt@1.18.941 test: `npm run build && node run-tests "exchangeName"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ccxt@1.18.941 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by lacksfish** [comment]
From what I gathered, the docker is provided for ease of use, but what's the benefit if it does not work out of the box? I had to copy some commands from the travis script, and source the rest of the tricks and fixes from various issue threads... 

So far I'm doing:

```
sudo -H pip3 install --upgrade setuptools pip wheel requests pyopenssl six tox twine setuptools web3 aiohttp requests cryptography pyopenssl
pip uninstall ccxt
```

to get the tests to work half-way, then I get this error message:

```
FAILED exchangeName (Python): (explain @ run-tests.js:187)

        Traceback (most recent call last):
          File "python/test/test.py", line 21, in <module>
            import ccxt  # noqa: E402
          File "/ccxt/python/ccxt/__init__.py", line 129, in <module>
            from ccxt.exchangeName import exchangeName                          # noqa: F401
        ImportError: No module named exchangeName (explain @ run-tests.js:190)

FAILED exchangeName (Python 2): (explain @ run-tests.js:187)

        Traceback (most recent call last):
          File "python/test/test.py", line 21, in <module>
            import ccxt  # noqa: E402
          File "/ccxt/python/ccxt/__init__.py", line 129, in <module>
            from ccxt.exchangeName import exchangeName                          # noqa: F401
        ImportError: No module named exchangeName (explain @ run-tests.js:190)

FAILED exchangeName (Python 3): (explain @ run-tests.js:187)

         (explain @ run-tests.js:190)

WARN exchangeName (PHP): (explain @ run-tests.js:188)

        string(11) "./keys.json"
        PHP Notice:  Undefined index: exchangeName in /ccxt/php/test/test.php on line 230
        PHP Warning:  A non-numeric value encountered in /ccxt/php/test/test.php on line 243
        PHP Warning:  A non-numeric value encountered in /ccxt/php/test/test.php on line 243
        0 (explain @ run-tests.js:190)
FAIL ["exchangeName"] (run-tests.js:268)
All done, 1 failed (run-tests.js:273)
```

It's crushing to debug all through this when initially it said "here's a docker, so that you don't have to worry about the setup"

**Comment by kroitor** [comment]
@lacksfish 

> could you elaborate further what a mortal human has to do inside the docker container to get rid of the KeyError?

You're running a wrong command. There's no exchange called `exchangeName`. The `exchangeName` is supposed to be substituted for a real exchange id by you, if you want to run the public tests.

**Comment by lacksfish** [comment]
I substituted the exchange I'm working on for "exchangeName". It is a placeholder only.

**Comment by kroitor** [comment]
@lacksfish then you need to make sure that the `npm run export-exchanges` stage was properly executed upon `npm run build`.

**Comment by kroitor** [comment]
HollaEx has been listed in CCXT 1.23.61+! Thank you for your help and patience!
