### ISSUE TITLE
Feature Request: __str__ and / or __repr__ implementation for exchanges

### ISSUE THREAD

**Issue by nazariyv** [ccxt/ccxt#5297]
Hi Igor & the team,

Thanks a lot for your hard work, this repo kicks ass!

I was wondering if it would be too difficult to implement either __repr__ or __str__ dunder methods for cleaner logging purposes mainly?

Currently, if you use the exchanges as keys in the dict or simply print their repr, you get something like:

`<ccxt.async_support.binance.binance object at 0x117166da0>`

It would be much nicer if we could have something like:

`BinanceConnector()` 

or 

`
{
"exchange": "binance",
"rateLimit: xxx,
...
}
`

You get an idea. Thank you!

**Comment by kroitor** [comment]
Hey @nazariyv )

Good to hear from you again )

> I was wondering if it would be too difficult to implement either repr or str dunder methods for cleaner logging purposes mainly?

It wouldn't be difficult at all, we will add those serializing overrides for sure! Thank you for pointing that out ) I totally agree with you, so, this feature will be added as soon as possible. This is considered moderate priority, however, so, it can take some time among other tasks, hopefully, not very long. We will keep you updated here. Thx!

**Comment by frosty00** [comment]
Yeah this is easily done.

ideally `eval(repr(obj)) == obj`

so an implementation that i would like to see is

```
def __repr__(self):
    return 'ccxt.' + ('async_support.' if self.asyncio_loop else '') + self.id + '()'

def __str__(self):
    return self.name
```

**Comment by kroitor** [comment]
Added in 1.18.707! Thx @frosty00, @nazariyv !
