### ISSUE TITLE
bittrex fetch_open_orders returning incorrect None on retry after DDoSProtection error

### ISSUE THREAD

**Issue by IgorMBorushek** [ccxt/ccxt#5300]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Windows 10
- Programming Language version: Python 3.6.3
- CCXT version: '1.18.458'
- Exchange: bittrex
- Method: fetch_open_orders

I had two processes running side by side that got throttled. I have them on a 60 second sleep before restart. Other requests such as cancel_order, request_order have no problems restarting. However, fetch_open_orders somehow always retrieves None on the retry call. Meanwhile, I have other trades open so the result should not be None(I get this bug repeatedly). Here is the output:

Placing an order on PART/BTC for these parameters: sell, closing, 166.0 units at price 0.00037268

```
bittrex.fetch_open_orders failed with exception DDoSProtection:  bittrex {"success":false,"message":"Call to GetOpenOrders was throttled. Try again in 60 seconds.","result":null}
Traceback (most recent call last):
...
  File "C:\Users\nt\Documents\Bots\RobotZai2-2c.py", line 311, in run_fighter
    self.create_order(trade, current_best_entry)
  File "C:\Users\nt\Documents\Bots\RobotZai2-2c.py", line 281, in create_order
    trade.trade_update('id')
  File "C:\Users\nt\Documents\Bots\RobotZai2-2c.py", line 522, in trade_update
    open_orders.reverse()
AttributeError: 'NoneType' object has no attribute 'reverse'
```

Here is the code

```Python

def api_call(message, *args):
    response = eval(message)(*args)
    except ccxt.OrderNotFound as e:     #Typically get this one when order was filled on exchange side between calls
        print(message + ' failed with exception OrderNotFound: ', str(e))
        return 'OrderNotFound'
    except ccxt.RequestTimeout as e:
        print(message + ' failed with exception RequestTimeout: ', str(e))
        time.sleep(1)
        bittrex.rateLimit = (bittrex.rateLimit * 2)
        api_call(message, *args)
    except ccxt.DDoSProtection as e:
        print(message + ' failed with exception DDoSProtection: ', str(e))
        time.sleep(bittrex.throttleDelay)
        bittrex.rateLimit = (bittrex.rateLimit * 2)
        api_call(message, *args)
    except Exception as e:
        print(message + ' failed with exception General: ', str(e))
        sys.exit()
    else:
        return response      

#Called from here when getting the order_id for a new order
open_orders = api_call('bittrex.fetch_open_orders')
open_orders.reverse()
```

I'm sorry, I can't figure out how to properly indent here...I added a photo of the code in case it is unclear. I would appreciate help with this issue, thank you.
![image](https://user-images.githubusercontent.com/3073810/59530243-1c7fbd80-8eb1-11e9-9680-5e6cbc074732.png)

**Comment by kroitor** [comment]
From this message it looks like you're not respecting the bittrex rate-limit.

> bittrex.fetch_open_orders failed with exception DDoSProtection:  bittrex {"success":false,"message":"Call to GetOpenOrders was throttled. Try again in 60 seconds.","result":null}

Do you have the rate-limiting enabled? It's required by the Manual: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

If your request was denied due to violating rate-limits, calling `.reverse()` on a None-response will not work. The error happens a lot earlier than that, upon fetching the orders, so, we need to make sure that your rate-limiting is enabled. Can you confirm?

**Comment by kroitor** [comment]
@IgorMBorushek also, from this section it looks like you may be recursively calling the `fetchOpenOrders` without a delay:

```Python
    except ccxt.DDoSProtection as e:
        print(message + ' failed with exception DDoSProtection: ', str(e))
        time.sleep(bittrex.throttleDelay)
        bittrex.rateLimit = (bittrex.rateLimit * 2)
        api_call(message, *args) # ←----- recursive call here
```

I suggest that you break it down into a simpler form.

**Comment by IgorMBorushek** [comment]
Firstly, thanks for the response. The problem isn't that I'm getting a DDoSProtection. I was getting this because I was testing the rate limiting on Bittrex on purpose. The problem is why is fetch_open_orders giving me a None response after calling it after this error though it works perfectly fine otherwise? Cancel_order and create_order retry fine after a DDoSProtection. 

I understand that if I turn on rate limiting, I will mostly avoid that. However, I want to know how I can correctly handle this error because it may come up sporadically due to load changes at the exchange side. Is the problem in the ccxt code or is bittrex/cloudfare sending me a None response for some reason?

bittrex.throttleDelay is a 60 second long delay which is exactly what Bittrex asks for in the response. Furhter insight would be appreciated, thanks again.

**Comment by kroitor** [comment]
@IgorMBorushek I suggest this:

```Python
def api_call(message, *args):
    try:    # ←----------- add try here
        response = eval(message)(*args)
        return response   # ←----------- add return here
    except ccxt.OrderNotFound as e:     #Typically get this one when order was filled on exchange side between calls
        print(message + ' failed with exception OrderNotFound: ', str(e))
        return 'OrderNotFound'
    except ccxt.RequestTimeout as e:
        print(message + ' failed with exception RequestTimeout: ', str(e))
        time.sleep(1)
        bittrex.rateLimit = (bittrex.rateLimit * 2)
        return api_call(message, *args)  # ←----------- add return here
    except ccxt.DDoSProtection as e:
        print(message + ' failed with exception DDoSProtection: ', str(e))
        time.sleep(bittrex.throttleDelay)
        bittrex.rateLimit = (bittrex.rateLimit * 2)
        return api_call(message, *args)  # ←----------- add return here
    except Exception as e:
        print(message + ' failed with exception General: ', str(e))
        sys.exit()
    else:
        return response
```

↑ Does that help?

**Comment by IgorMBorushek** [comment]
I see what my problem was, fixed it, thank you very much!

**Comment by IgorMBorushek** [comment]
By the way, I think binding response to the result is a no go because unless I'm mistaken, if there is an exception in the recursive call, response won't be bound. So I implemented it like this:

    def api_call(self, message, *args):
        '''for performance checking
        global now
        print('cpu work time between last api call and current call of: ' + str(message) + ' is ' + str(time.perf_counter() - now))
        now = time.perf_counter()
        '''
        try:
            response = eval(message)(*args)
        except ccxt.OrderNotFound as e:     #Typically get this one when order was filled on exchange side between calls
            print(message + ' failed with exception OrderNotFound: ', str(e))
            return 'OrderNotFound'
        except ccxt.RequestTimeout as e:
            print(message + ' failed with exception RequestTimeout: ', str(e))
            time.sleep(1)
            bittrex.rateLimit = (bittrex.rateLimit * 2)
            return self.api_call(message, *args)
        except ccxt.DDoSProtection as e:
            print(message + ' failed with exception DDoSProtection: ', str(e))
            time.sleep(bittrex.throttleDelay)
            bittrex.rateLimit = (bittrex.rateLimit * 2)
            return self.api_call(message, *args)
        except ccxt.NetworkError as e:
            print(message + ' failed with exception NetworkError, possible VPN disconnect: ', str(e))
            time.sleep(60)
            return api_call(message, *args)
        except ccxt.InsufficientFunds as e: #Can get this if during a move, between a trade_update('quantity_remaining') and create_order, the order was partially or fully filled
            print(message + ' failed with exception InsufficientFunds: ', str(e))
            return 'InsufficientFunds'
        except Exception as e:
            print(message + ' failed with exception General: ', str(e))
            import sys
            sys.exit()
        else:
            return response

**Comment by kroitor** [comment]
> By the way, I think binding response to the result is a no go because unless I'm mistaken, if there is an exception in the recursive call, response won't be bound. So I implemented it like this:

That was exactly the version i posted here initially, but then I edited it for your case with `response` )) You're absolutely right )
