### ISSUE TITLE
Kraken issue - privatePostRetrieveExport - corrupted zip

### ISSUE THREAD

**Issue by icehacker33** [ccxt/ccxt#5302]
- OS: Raspbian Stretch
- Programming Language version: NodeJS
- CCXT version: 1.18.697
- Exchange: Kraken
- Method: privatePostRetrieveExport

Hello there,
I am trying to export my Kraken account's stats with the RetrieveExport private method which only needs a report ID to work.

However, I found that although it's retrieving the binary stream from Kraken, for some reason it seems to be missing a few bytes. Resulting in a corrupt zip file. The code I use to export the report I need is as follows:

```
const kraken = new ccxt.kraken({
  apiKey: flow.get('krakenAPIkey'),
  secret: flow.get('krakenAPIsecret')
})

kraken.privatePostRetrieveExport({
    'id':'MFRK'
    })
    .then((data) => {
        var buf = new Buffer(data, 'binary');
        fs.writeFile('/tmp/test.zip',buf,'binary',function(err) {
            if(err) {
                console.log(err);
            } else {
            console.log("The file was saved!");
            msg.payload = "The file was saved!";
            node.send([msg]);
            }
        });
    })
    .catch((err) => {
        console.error(err);
});
```
The following output shows an example of the file downloaded from Kraken's GUI with a browser and the same report retrieved with the CCXT library and the code posted above.

The beginning of the file seems to be the same, but after a few bytes, they are different.
```
-rw-r--r-- 1 user user 487 Jun 14 15:51 good.zip <--- Downloaded with a browser [good]
-rw-r--r-- 1 user  user  467 Jun 14 21:40 test.zip <--- Created with the code above [bad]
```
Of course, trying to uncompress the file, results in an error.
```
$> unzip test.zip
Archive:  test.zip
error [test.zip]:  missing 120 bytes in zipfile
  (attempting to process anyway)
error [test.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```
I have tried to get to the bottom of this error and find whether or not it has anything to do with the CCXT library perse, but I haven´t been able to prove that it is not related with the library implementation and that's why I´m posting this.

It is not clear enough for me if CCXT would allow users to retrieve binary files without affecting its content.

Any pointers or help would be strongly appreciated, I´m not a developer and I could be forgetting or ignoring something important.

Thanks in advance

**Comment by galvanizze** [comment]
Same in python. The reason is that result (zip data) from api should be retrieved from **response.content**, not response.text.

**Comment by galvanizze** [comment]
#5730 - storing raw content should solve this issue

**Comment by icehacker33** [comment]
Many thanks for your help with this! much appreciated.
