### ISSUE TITLE
dx fetch_open_orders returns empty

### ISSUE THREAD

**Issue by blaaaaaaa** [ccxt/ccxt#5303]
dx fetch_open_orders returns empty where I have open orders

Request: POST https://acl.dx.exchange {'Content-Type': 'application/json-rpc', 'Authorization': 'XXX', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} {"jsonrpc":"2.0","id":XXX,"method":"OrderManagement.OpenOrders","params":[{"pagination":{"limit":null,"offset":0},"instrumentId":1045}]}

Response: POST https://acl.dx.exchange 200 {'Date': 'Sat, 15 Jun 2019 01:39:50 GMT', 'Content-Type': 'application/json-rpc', 'Content-Length': '84', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS', XXX {"id":"XXX+12","result":{"orders":[],"total":{"count":0}},"error":null}

[]

- OS:win10
- Programming Language version:py3.6.6
- CCXT version:1.18.698
- Exchange:dx
- Method:fetch_open_orders

**Comment by kroitor** [comment]
@blaaaaaaa can you plz provide more clues? 1045 = ETH/USDT, but they also have ETH/USD – are you sure there's no confusion?

**Comment by blaaaaaaa** [comment]
Hi, strangely enough the 2+ days old order I wasnt able to get. 
With new orders it worked but it has an error here:
line   345 in dx.py      symbol = self.markets_by_id[order['instrumentId']]['symbol']
fails since order["instrument"] id will be an integer and wont work as an key, monkeypatched it to a string and it works.
so in python I think this works: symbol = self.markets_by_id[str(order['instrumentId'])]['symbol']
bit as it is generated somehow it has to be changed somewhere else.

**Comment by kroitor** [comment]
@blaaaaaaa 

> strangely enough the 2+ days old order I wasnt able to get.

This may be a limitation on the exchange side. I'd ask @brandsimon about it, hope he can clarify it a bit.

> bit as it is generated somehow it has to be changed somewhere else.

Thx for the clues, i've added the necessary fixes, and it should work without a monkey patch as of 1.18.709 (it will arrive in 15 minutes). Let us know if you have any issues with it.

**Comment by brandsimon** [comment]
@blaaaaaaa @kroitor 
Yes, sadly this is a limitation on the exchange side.
I think, they do this because there is no `get_order` method.
