### ISSUE TITLE
New exchange: WCX

### ISSUE THREAD

**Issue by Nitrooo** [ccxt/ccxt#5309]
Site: https://wcex.com/
API: https://github.com/wcxofficial/api-docs

**Comment by An-Net** [comment]
This exchange changed name and address to https://trade8.to/ (Trade8):

> WCX - What's now?
Note that WCX has been acquired by Trade8, a bitcoin-based FX and stock trading platform.
If you're a WCX user, you can continue trading on Trade8 as usual.

Scam allegations:

- https://www.hedgewithcrypto.com/wcx-review/

- https://bitcointalk.org/index.php?topic=5233783.0

- https://bitcointalk.org/index.php?topic=5129289.msg53724100#msg53724100
