### ISSUE TITLE
Okex3 fetch margin balance

### ISSUE THREAD

**Issue by VadimSFedin** [ccxt/ccxt#5311]
- OS: Windows 10
- Programming Language version: Python
- CCXT version: 1.18.721
- Exchange: Okex3
- Method: okex.fetch_balance(params={'type': 'margin'}))

The method okex.fetch_balance(params={'type': 'margin'})) returns:
ccxt.base.errors.NotSupported: okex3 margin balance response format has changednot

**Comment by kroitor** [comment]
@VadimSFedin can you plz paste your verbose request + response?https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

```Python
okex.load_markets()
okex.verbose = True
okex = okex.fetch_balance(params={'type': 'margin'})
```
