### ISSUE TITLE
bitstamp balances error: unhashable type dict

### ISSUE THREAD

**Issue by firepol** [ccxt/ccxt#5313]
Version: 1.18.724
Exchange: bitstamp
Lang: python (async) -( python 3.7)
Method: fetch_balance

This method worked until a few days ago, now I get this error

Error:   File "/myhome/site-packages/ccxt/async_support/bitstamp.py", line 505, in fetch_balance
    result[currency] = account
TypeError: unhashable type: 'dict'

To reproduce, in python (import `async_support`)

```
balances = await exchange.fetch_balance()
```

Expected: no such error. Balances should be returned as in any other exchange (e.g. binance works fine).

**Comment by kroitor** [comment]
The fix will arrive in 15 minutes. Thx for reporting it!
