### ISSUE TITLE
Crex24 rounds price rate to zero

### ISSUE THREAD

**Issue by dotai2012** [ccxt/ccxt#5314]
- OS:
- Programming Language version: Node v10
- CCXT version: 1.18.707
- Exchange: Crex24
- Method: createOrder

I was trying to create a Buy order on pair UCUL (which has very low rate) and ccxt drops the price rate to 0 (zero)

Possible fix:

Go to crex24.js and find:

`request['price'] = this.priceToPrecision (symbol, price);`

replace with

`request['price'] = price;`

**Comment by kroitor** [comment]
@dotai2012 can you please paste your verbose request and response? https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
