### ISSUE TITLE
Fetch order method in Bibox not working

### ISSUE THREAD

**Issue by mkang1234** [ccxt/ccxt#5317]
- OS: Windows
- Programming Language version: Python
-  CCXT version: Latest version
- Exchange: Bibox
- Method: fetch_order

When I call fetch_order method, the exchange returns the following message:

{"result":[{"error":{"code":"3000","msg":"请求参数错误"},"cmd":"orderpending/order"}],"error":{"code":"3000","msg":"请求参数错误"},"cmd":"orderpending/order"}

Code 3000 refers to invalid parameter. 

I am able to submit an order fine and returns an order ID. I then use the order ID to get order details by calling fetch_order method below and I get that error message from the exchange. Would greatly appreciate it if someone look into this. Thank you. 

order_data = self.api.fetch_order(11221615815381299)

**Comment by kroitor** [comment]
@mkang1234 can you please post your verbose request/response for the fetch_order call?

```Python
self.api.load_markets ()
self.api.verbose = True  # set verbose = True after load_markets ()

# your fetch_order code...
order_data = self.api.fetch_order(... 
```

**Comment by mkang1234** [comment]
Request: POST https://api.bibox.com/v1/orderpending {'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.20.0', 'Accept-Encoding': 'gzip, deflate'} {"cmds":"[{\"cmd\":\"orderpending/order\",\"body\":{\"id\":11221615815381211}}]","apikey":"XXXXXXXXXXXXXXXXXXXXXXXXX","sign":"XXXXXXXXXXXXXXXXX"}

Response: POST https://api.bibox.com/v1/orderpending 200 {'Server': 'Tengine', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '170', 'Access-Control-Allow-Origin': 'undefined', 'Access-Control-Allow-Methods': 'POST, GET, OPTIONS', 'Access-Control-Allow-Headers': 'Content-Type, Accept, x-access-token, X-Requested-With', 'Access-Control-Max-Age': '172800', 'X-Ca-Request-Id': 'EC7502EC-7C5E-46AD-826B-D3405263B25F', 'X-Powered-By': 'Express', 'Access-Control-Allow-Credentials': 'true', 'ETag': 'W/"aa-jJY5VkM9le2A4HGqdY89mH3DOvI"', 'Date': 'Wed, 19 Jun 2019 00:16:13 GMT', 'Connection': 'keep-alive'} {"result":[{"error":{"code":"3000","msg":"请求参数错误"},"cmd":"or
derpending/order"}],"error":{"code":"3000","msg":"请求参数错误"},"cmd":"orderpending/order"}

**Comment by kroitor** [comment]
@mkang1234 it's been broken since they changed their API: https://github.com/ccxt/ccxt/issues/5164

Does this work on your side:

```Python
order_id = '11221615815381299'  # as string
symbol = None
params = {
    'account_type': 0,
}
order_data = self.api.fetch_order(order_id, symbol, params)
```

?

**Comment by mkang1234** [comment]
Yes that works!! Thank you

**Comment by kroitor** [comment]
@mkang1234 i will add that to the main branch, and if you update to version 1.18.734 in 15 minutes – your code will work without edits:

```Python
order_data = self.api.fetch_order(11221615815381299)  # no need for params
```

Let us know if you have further difficulties after that. Thx for reporting!

**Comment by mkang1234** [comment]
ok thanks!

**Comment by kroitor** [comment]
@mkang1234 any issue with it?

**Comment by mkang1234** [comment]
The new version doesn't appear to solve the issue but I'm able to run with the following parameter. 

symbol = None
params = {
    'account_type': 0,
}

**Comment by kroitor** [comment]
@mkang1234 make sure you have indeed updated the version, and when the program runs your ccxt version is up date. To check for the runtime version:

```Python
print('CCXT version:' + ccxt.__version__)
order_data = self.api.fetch_order(11221615815381299)  # no need for params
```

Is it >= 1.18.734 ?

**Comment by mkang1234** [comment]
CCXT version:1.18.55
bibox {"result":[{"error":{"code":"3000","msg":"请求参数错误"},"cmd":"orderpending/order"}],"error":{"code":"3000","msg":"请求参数错误"},"cmd":"orderpending/order"}

Thought I was running the latest version.  Let me download latest version again.

**Comment by kroitor** [comment]
> Thought I was running the latest version. Let me download latest version again.

Pay attention to which pip you're using to install and upgrade it. Because, if you're on Windows, then you most likely run anacoda python, and conda is known for its `pip`-related issues:

- https://github.com/ccxt/ccxt/issues/3317
- https://github.com/ccxt/ccxt/issues/2824
- https://github.com/ccxt/ccxt/issues/2747
- ...

**Comment by mkang1234** [comment]
I had to do pip uninstall ccxt and then pip install ccxt to upgrade to latest version. 
Had to convert order_id to string and looks like it works now. Thank you!
