### ISSUE TITLE
OKEX getBalance() add support for future accounts

### ISSUE THREAD

**Issue by tandazhi** [ccxt/ccxt#532]
Seems that the method getBalance() of calss OKcoinUSD can get the balance of spot account correctly, but 
can't get that of future account. Is there any special method for okex future account? 

Thanks a lot!

**Comment by kroitor** [comment]
@tandazhi I'll take a look into it and will probably add support for futures-accounts very soon!

**Comment by kroitor** [comment]
@tandazhi after taking a deeper look into it, I see that they return position trading balances for the futures account, and unifying the positional, margin or leveraged trading is currently beyond our scope. But you can fetch the futures balances with ccxt already, anyway, like so:

```Python
import ccxt
print(ccxt.okex({'apiKey': 'XXXXX', 'secret': 'YYYYY'}).private_post_future_userinfo())
```

Does this answer your question?

**Comment by kroitor** [comment]
I hope I did answer your question, and I would close this issue for now, if you don't mind. Feel free to reopen it or ask questions if you still have difficulties with it. Thx!

**Comment by tandazhi** [comment]
Thanks Kroitor, to use private_post_future_userinfo() to access the balance is ok for me.

**Comment by an-dutra** [comment]
Hi, when i try to run this command i get {"result":false,"error_code":20024}

My code is only this:
key = 'myapikey'
sec= 'myapisec'
print(ccxt.okex({'apiKey': key, 'secret': sec}).private_post_future_userinfo())
