### ISSUE TITLE
bignumber ethereumjs-abi ethereumjs-util web3 dependencies not work

### ISSUE THREAD

**Issue by jsgpdevelop** [ccxt/ccxt#5322]
- OS: Windows 7 x64
Programming Language version: Javascript/typescript
- CCXT version: latest

i just installed the latest version of  ccxt and it throws these errors when compiling:

WARNING in ./node_modules/ccxt/js/base/Exchange.js
Module not found: Error: Can't resolve 'bignumber.js' in 'C:\Ordphy\ordphy-frontend\node_modules\ccxt\js\base'

WARNING in ./node_modules/ccxt/js/base/Exchange.js
Module not found: Error: Can't resolve 'ethereumjs-abi' in 'C:\Ordphy\ordphy-frontend\node_modules\ccxt\js\base'

WARNING in ./node_modules/ccxt/js/base/Exchange.js
Module not found: Error: Can't resolve 'ethereumjs-util' in 'C:\Ordphy\ordphy-frontend\node_modules\ccxt\js\base'

WARNING in ./node_modules/ccxt/js/base/Exchange.js
Module not found: Error: Can't resolve 'web3' in 'C:\Ordphy\ordphy-frontend\node_modules\ccxt\js\base'

**Comment by kroitor** [comment]
> i just installed the latest version of ccxt and it throws these errors when compiling:

Can you plz clarify what exactly (which commands) you mean under "compiling" ? The deps in the header of this issue are "external" to our code. Do you have those deps installed in your `ordphy-frontend` project? Also, what's your node version?

**Comment by jsgpdevelop** [comment]
```
node -v
v10.15.3

```
I just installed ccxt and imported it and used it in my code in this way :
`import * as ccxt from 'ccxt';`  
`this.api = new ccxt.binance({ enableRateLimit: true, ...options });` 

I'm using Angular. To execute the code, Angular compiles (translates) the code from typescript to javascript. 

The problems with dependencies arises when I'm  using ccxt. Those are dependecies of ccxt.
Should not these be automatically installed with ccxt?.

**Comment by kroitor** [comment]
> To execute the code, Angular compiles (translates) the code from typescript to javascript.

The base code of CCXT is not typescript, it's JavaScript, mostly.

> The problems with dependencies arises when I'm using ccxt.

> Those are dependecies of ccxt.

Not really, because CCXT does not require those deps unconditionally. It only requires them if you instantiate all exchanges, including the ones that need web3:

- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L60
- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L1341

> Should not these be automatically installed with ccxt?.

Nope, because we can't guarantee the security of the deps of the deps.

> I'm using Angular. To execute the code, Angular compiles (translates) the code from typescript to javascript.

In this case, we need a lot more detail, on how exactly you're using it with Angular, because it depends on how your package is configured and how the translation of the deps is configured in the project. However, this is somewhat beyond the scope of the library.

**Comment by kroitor** [comment]
@jsgpdevelop basically, if you don't use web3, then exclude those files from your angular project.
Something like this should help:

- https://www.google.com/search?q=angular+webpack+exclude+file
- https://www.google.com/search?q=webpack+angular+exclude+require

```
...
exclude: [
    'node_modules/bignumber',
    'node_modules/ethereumjs-abi',
    'node_modules/ethereumjs-util',
    'node_modules/web3',
] 
...
```

In other words, this is webpack + Angular + node issue, not a CCXT issue. Let us know if the above does not help.

**Comment by jsgpdevelop** [comment]
It works fine. Thank you a lot.

**Comment by kroitor** [comment]
@jsgpdevelop thx for reporting back!
