### ISSUE TITLE
poloniex fetch_trades default behavior

### ISSUE THREAD

**Issue by stonemonk** [ccxt/ccxt#534]
fetch_trades on poloniex has special code to have it return 50,000 trades by default which makes it imposible to access poloniex's default behavior of returning only the last 200 trades.

Perhaps if limit is defined and less than 200, you can exclude the "end" param as to get the default behavior.

**Comment by kroitor** [comment]
Thx for posting this issue! Will fix for that shortly!

**Comment by kroitor** [comment]
This is fixed now, please don't forget to update to most recent version of ccxt. Thx!
