### ISSUE TITLE
[therock] dealing with delisted currency

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5345]
I'm getting this error when requesting withdrawals: `therock does not have currency code USD`.

That currency used to be supported.  Is there a recommended way to deal with this?  I'm thinking to just pass the `currency` directly.

**Comment by kroitor** [comment]
```Python
exchange.currencies['USD'] = {
    'id': 'USD',
    'code': 'USD',
}
exchange.withdraw ('USD' ...
```

Does this help?

**Comment by kroitor** [comment]
Alternatively, we could add some switch or option across all exchanges, something like "useCurrencyCodesAsIs", that would skip the lookup in `this.currency()`.

**Comment by npomfret** [comment]
thanks, your first suggestion worked.
