### ISSUE TITLE
Bibox: fetchTickers() returns 'vol24H' as baseVolume

### ISSUE THREAD

**Issue by WoK-E** [ccxt/ccxt#5347]
- OS: Linux
- Programming Language version: PHP 7.2
- CCXT version: 1.18.796
- Exchange: Bibox
- Method: fetchTickers()

fetchTickers() for bibox returns 'vol24H' as baseVolume, instead of the actual volume

**Comment by kroitor** [comment]
> fetchTickers() for bibox returns 'vol24H' as baseVolume, instead of the actual volume

The purpose of the ticker is to return 24h stats, some exchanges also report the current volume of topmost orders in the orderbooks, but that info goes into different fields, namely `bidVolume` and `askVolume`. The ticker does not report current total volume in the orderbooks. See the Manual on ticker structure here: 

- https://github.com/ccxt/ccxt/wiki/Manual#price-tickers

If you want to get the current total volume in an orderbook, you will have to call the `fetchOrderBook()` method and sum up the order amounts.

- https://github.com/ccxt/ccxt/wiki/Manual#order-book

Let us know if that does not resolve the issue.

**Comment by WoK-E** [comment]
My point was that the baseVolume returned is not a float, as it should be (and as stated in the manual), but the string 'vol24H'
