### ISSUE TITLE
Loss of precision with bittrex timestamps

### ISSUE THREAD

**Issue by stonemonk** [ccxt/ccxt#535]
bittrex timestamps are being parsed with `parse8601()` which calls `dt.utctimetuple()` which throws away the ms precision, effectively flooring it to seconds.  

While this is okay for most purposes, some data such as tickers have sub-second precision and since there can be more than one ticker update per second, its sometimes very useful to be able to distinguish between them by their timestamp.

Note this would mean changing the returned `timestamp` fields from ints to floats.  If you don't want to do this, I could use the `datetime` field which you provide and parse it myself. However, since you create the `datetime` field from the timestamp it also suffers this loss of precision.

**Comment by kroitor** [comment]
@stonemonk 

> which throws away the ms precision, effectively flooring it to seconds

it should not behave that way, i'll take a look into it and will fix it...

> Note this would mean changing the returned timestamp fields from ints to floats.

Actually, I don't think so, because our timestamps are documented milliseconds ints. If you see them  rounded to seconds (thousands), it's probably due to a bug in the parsing code, but the integer type for the timestamp should be ok.

**Comment by stonemonk** [comment]
Ahh right, you are returning as millisecond ints, thats good.

I have no idea why the built in dt.utctimetuple() throws away ms, but it does and easy to see that in datetime source code.  :(

**Comment by kroitor** [comment]
This is fixed in 1.10.55. Thx once again for reporting!
