### ISSUE TITLE
Where are the privatePostOrder and self.extend methods defined?

### ISSUE THREAD

**Issue by nazariyv** [ccxt/ccxt#5352]
Hi again Igor!

This is a question.

I wanted to ask about this line:

`response = getattr(self, method)(self.extend(request, params))`
This is line `700` of the binance exchange code. I am trying to understand where the `privatePostOrder` method is and where is this `self.extend` method defined.

I am trying to think if I need to reattempt the rest async get on fail. But not quite understanding that line of code.

Thank you for your lib and for your continued hard work!

**Comment by kroitor** [comment]
Hi @nazariyv !

> I am trying to understand where the privatePostOrder method is

Nowhere ) That method does not exist in the code, it is generated in runtime, when you launch your script. For each exchange endpoint defined in `describe() → api` CCXT creates an implicit method corresponding to that endpoint. Explained here:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#implicit-api-methods
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods 

> where is this self.extend method defined.

Here: https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L675

Let us know if that doesn't answer the questions )

**Comment by kroitor** [comment]
An example of a retry-sequence (might need adjustments for your needs):

```Python
# -*- coding: utf-8 -*-

from pprint import pprint
import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402


def try_to_create_order(exchange, symbol, type, side, amount, price, params):
    try:
        order = exchange.create_order(symbol, type, side, amount, price, params)
        return order
    except ccxt.NetworkError as e:
        # retry on networking errors
        print(type(e).__name__)
        print(e.args)
        return False
    except Exception as e:
        print(type(e).__name__)
        print(e.args)
        raise e  # break on all other errors


exchange = ccxt.bitmex({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True
})

symbol = 'BTC/USD'  # ←--- edit here
type = 'limit'  # ←--- edit here
side = 'buy'  # ←--- edit here
amount = 0.12345  # ←--- edit here
price = 5.4321  # ←--- edit here
params = {}  # ←--- edit here

order = False

while True:
    order = try_to_create_order(exchange, symbol, type, side, amount, price, params)
    if order:
        break

pprint(order)
```

**Comment by nazariyv** [comment]
Thank you very much! I will study the resources mentioned carefully :)
