### ISSUE TITLE
Bittrex cancelOrder TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by denarioresearch** [ccxt/ccxt#5354]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS: Ubuntu
- Programming Language version: js
- CCXT version: 1.18.787
- Exchange: bittrex
- Method: cancelOrder
```
const order =  await bittrex.fetchOpenOrders('PAY/BTC')
await bittrex.cancelOrder(order.id, 'PAY/BTC')
```

This error does not happen all the time. I tried to replicate it but did not appear again. But it is frequently observed on bittrex.

**Comment by kroitor** [comment]
@denarioresearch we need some way of replicating it, though. Can you try to catch it with verbose mode on and paste your verbose request + response here along with the complete error call stack? We could localize the issue then. Please, see here:https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by kroitor** [comment]
More about it here: https://github.com/ccxt/ccxt/blob/master/js/bittrex.js#L1338

**Comment by denarioresearch** [comment]
I've set verbose mode and trying to replicate error. Order gets cancelled successfully. I looked through cancelOrder code and it seems there is something in parseOrder that causes this error. 'INVALID_ORDER' order appears when I try to cancel an order that does not exist or id is wrong.

**Comment by frosty00** [comment]
```
const order =  await bittrex.fetchOpenOrders('PAY/BTC')
await bittrex.cancelOrder(order.id, 'PAY/BTC')
```

Your `order.id` here will be undefined since `fetchOpenOrders` returns a list of orders. Can you confirm this bug still exists with a valid orderId?

**Comment by denarioresearch** [comment]
I know, I tried to simplify code but did this incorrectly. Consider order.id a valid order id. This error does not happen all the time and I did not catch it on the test environment yet. Order gets canceled successfully so I think this error is related to parseOrder function. Today this error was observed on prod environment where I can not enable verbose mode at the moment.

**Comment by kroitor** [comment]
@denarioresearch can you add an catch-clause on the production, something like:

```JavaScript
try {

    // assuming correct code here instead of this incorrect code
    const order =  await bittrex.fetchOpenOrders('PAY/BTC')
    await bittrex.cancelOrder(order.id, 'PAY/BTC')

} catch (e) {
    if (e instanceof ccxt.BaseError) {
        console.log (e.constructor.name, e.message)
        console.log (bittrex.last_http_response)
        console.log (bittrex.last_json_response)
        console.log (bittrex.last_response_headers)
    }
}
```

?  

We ask this because we need something to work with, either a complete short code snippet to reproduce it or a verbose output, otherwise we will be mostly guessing, hope for your understanding )

**Comment by denarioresearch** [comment]
done... will post output here once catch this error

**Comment by denarioresearch** [comment]
Here is some more info on this issue:
```
TypeError: Cannot read property 'split' of undefined
    at bittrex.parseSymbol (/node_modules/ccxt/js/bittrex.js:817:40)
    at bittrex.parseOrderV3 (/node_modules/ccxt/js/bittrex.js:868:27)
    at bittrex.parseOrder (/node_modules/ccxt/js/bittrex.js:827:25)
    at bittrex.cancelOrder (/node_modules/ccxt/js/bittrex.js:637:34)
 ```

It seems error is not an inatance of ccxt.BaseError

**Comment by kroitor** [comment]
@frosty00 can you rework the  incorrect`parseSymbol` section there for a proper `marketId` code as here: https://github.com/ccxt/ccxt/blob/master/js/bittrex.js#L990 ?

**Comment by frosty00** [comment]
What version of ccxt are you using. I am looking at the bittrex code on the current release and there is no parseSymbol in parseOrderV3 (the trace that you are outputting)

```
parseOrderV3 (order, market = undefined) {
        //
        //     {
        //         id: '1be35109-b763-44ce-b6ea-05b6b0735c0c',
        //         marketSymbol: 'LTC-ETH',
        //         direction: 'BUY',
        //         type: 'LIMIT',
        //         quantity: '0.50000000',
        //         limit: '0.17846699',
        //         timeInForce: 'GOOD_TIL_CANCELLED',
        //         fillQuantity: '0.50000000',
        //         commission: '0.00022286',
        //         proceeds: '0.08914915',
        //         status: 'CLOSED',
        //         createdAt: '2018-06-23T13:14:28.613Z',
        //         updatedAt: '2018-06-23T13:14:30.19Z',
        //         closedAt: '2018-06-23T13:14:30.19Z'
        //     }
        //
        const marketSymbol = this.safeString (order, 'marketSymbol');
        let symbol = undefined;
        let feeCurrency = undefined;
        if (marketSymbol !== undefined) {
            const [ baseId, quoteId ] = marketSymbol.split ('-');
            const base = this.commonCurrencyCode (baseId);
            const quote = this.commonCurrencyCode (quoteId);
            symbol = base + '/' + quote;
            feeCurrency = quote;
        }
        const direction = this.safeString (order, 'direction');
        const createdAt = this.safeString (order, 'createdAt');
        const updatedAt = this.safeString (order, 'updatedAt');
        const closedAt = this.safeString (order, 'closedAt');
        let lastTradeTimestamp = undefined;
        if (closedAt !== undefined) {
            lastTradeTimestamp = this.parse8601 (closedAt);
        } else if (updatedAt) {
            lastTradeTimestamp = this.parse8601 (updatedAt);
        }
        const timestamp = this.parse8601 (createdAt);
        const type = this.safeString (order, 'type');
        const quantity = this.safeFloat (order, 'quantity');
        const limit = this.safeFloat (order, 'limit');
        const fillQuantity = this.safeFloat (order, 'fillQuantity');
        const commission = this.safeFloat (order, 'commission');
        const proceeds = this.safeFloat (order, 'proceeds');
        const status = this.safeString (order, 'status');
        let average = undefined;
        let remaining = undefined;
        if (fillQuantity !== undefined) {
            if (proceeds !== undefined) {
                if (fillQuantity > 0) {
                    average = proceeds / fillQuantity;
                } else if (proceeds === 0) {
                    average = 0;
                }
            }
            if (quantity !== undefined) {
                remaining = quantity - fillQuantity;
            }
        }
        return {
            'id': this.safeString (order, 'id'),
            'timestamp': timestamp,
            'datetime': this.iso8601 (timestamp),
            'lastTradeTimestamp': lastTradeTimestamp,
            'symbol': symbol,
            'type': type.toLowerCase (),
            'side': direction.toLowerCase (),
            'price': limit,
            'cost': proceeds,
            'average': average,
            'amount': quantity,
            'filled': fillQuantity,
            'remaining': remaining,
            'status': status.toLowerCase (),
            'fee': {
                'cost': commission,
                'currency': feeCurrency,
            },
            'info': order,
        };
    }
```

**Comment by kroitor** [comment]
@frosty00 you're right, my sources were not up to date )

@denarioresearch looks like your version is outdated too...

**Comment by denarioresearch** [comment]
1.18.787 should I update to the most recent?

**Comment by kroitor** [comment]
@denarioresearch yes, let us know if upgrading to the most recent version does not help. We're still in active development, so we ask our users to update frequently. In general we should only open the issue if your version is more or less fresh. Version 1.18.787 is too old, though.
