### ISSUE TITLE
bitfinex не приходят все данные

### ISSUE THREAD

**Issue by AndrewOzarko** [ccxt/ccxt#5355]
Здраствуйте, не приходит все данные для криптобиржы bitfinex. например в binance при fetch_ticker приходит изменение и изменение в процентах, в bitifnex эти значения null. Как можна добыть эти данные ?

**Comment by kroitor** [comment]
Здравствуйте!

Обычно, мы не добавляем "от себя" то, чего не предоставляет биржа, поэтому, если какие-то значения не передаются самой биржей — мы не дописываем их, в этом случае отсутствие этих значений допустимо. Чаще всего это означает, что эти величины (изменения в процентах) можно рассчитать на клиентской стороне на основании объёмов и цен закрытия и открытия, а также на основании исторической информации из fetch_ohlcv: https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts.
