### ISSUE TITLE
Poloniex - please update trading fees

### ISSUE THREAD

**Issue by wiktorglowacki** [ccxt/ccxt#5356]
- OS: MacOS
- Programming Language version: Javascript
- CCXT version:  1.18.815
- Exchange: Poloniex
- Method:

https://github.com/ccxt/ccxt/blob/master/js/poloniex.js#L114

Can you please update Poloniex Trading Fees? They were changed recently to:

'maker': 0.0015
'taker': 0.0025

**Comment by npomfret** [comment]
https://github.com/ccxt/ccxt/pull/5358
