### ISSUE TITLE
Occasional crash in bittrex parse_trades()

### ISSUE THREAD

**Issue by stonemonk** [ccxt/ccxt#536]
bittrex `fetch_trades()` sometimes triggers a crash from `parse_trades()` because `trades` is None and it raises a TypeError because NoneType is not iterable.  In other words the `response['result']` is sometimes None in the following line and should be checked:

`return self.parse_trades(response['result'], market)`

To be exact, bittrex returned this:

`response == {
'message': '', 
'result': None, 
'success': True
}`

This is some degenerate case that I had observed with Bittrex service prior to using CCXT so its definitely something on the bittrex end.  My solution prior to using CCXT was to check but the `success` flag and that `result` is not None for this and some other request types, although as far as I can remember trade history was the only endpoint which I had actually observed this with.

**Comment by kroitor** [comment]
Thank your feedback, @stonemonk ! I'll put that check for bittrex as well, will upload soon.

**Comment by stonemonk** [comment]
Ahh I just got this again but this time on fetch_ohlcv() / parse_ohlcv() for symbol 'BTCD/BTC' and interval '1m'.

Maybe all bittrex calls should check that `response['result'] is not None` if you plan to dereference it to get data out of it.

**Comment by kroitor** [comment]
@stonemonk I'll do the same for all methods of bittrex then... Will be fixed soon.

**Comment by stonemonk** [comment]
I am still getting this issue fairly regularly with latest CCXT. Still getting it on fetch_ohlcv():

```
return self.parse_ohlcvs(response['result'], market, timeframe, since, limit)
```

calls:

```
    def parse_ohlcvs(self, ohlcvs, market=None, timeframe='1m', since=None, limit=None):
        ohlcvs = self.to_array(ohlcvs)
        num_ohlcvs = len(ohlcvs)
```

last like there crashes:

```
TypeError: object of type 'NoneType' has no len()
```

**Comment by kroitor** [comment]
@stonemonk can you please show verbose output of the exception?

**Comment by stonemonk** [comment]
<img width="754" alt="screen shot 2017-12-12 at 9 36 03 pm" src="https://user-images.githubusercontent.com/5236934/33893837-8bc61b86-df84-11e7-9423-d6a6febc4470.png">
<img width="742" alt="screen shot 2017-12-12 at 9 35 01 pm" src="https://user-images.githubusercontent.com/5236934/33893839-8c193bae-df84-11e7-8ced-40ce38be98dc.png">

**Comment by stonemonk** [comment]
I think its because Bittrex servers are struggling right now with the ETH surge.. I am also having trouble loading some of the website pages right now.  But in any case, it should not cause my program to crash.

**Comment by kroitor** [comment]
@stonemonk got it, will add a workaround for `None`-response...
