### ISSUE TITLE
How to start fetching ohlcv starting from the oldest available data ongoing

### ISSUE THREAD

**Issue by soerenmartius** [ccxt/ccxt#5362]
ATTENTION!!!

- OS: MacOS 18.6.0
- Programming Language version: Python 3.7x
- CCXT version: ~1.18
- Exchange: various
- Method: fetch_ohlcv()

Is there any build variable or method to what's the earliest available timestamp of markets OHLCV data? If I pull all markets from Bitmex using a resolution of 1m, the API's won't return data for most of the assets. If I align the timestamps towards a date where data is actually available ( move forward in time ) it works as i wanted it to be. 

Is there such functionality and of not, how would you solve this?

Thank You!

**Comment by frosty00** [comment]
Hi @soerenmartius,

> Is there any build variable or method to what's the earliest available timestamp of markets OHLCV data? If I pull all markets from Bitmex using a resolution of 1m

You can send a request to bifinex and get the `OHLCV` that it has available to supply to you. Some APIs provide different results based upon the since parameter you provide to the ccxt request. If you want the earliest OHCLV data for bitfinex you would have to use `await bitfinex.fetchOHLCV ('ETH/BTC', '1m')[0]`.

> Is there such functionality and of not, how would you solve this?

CCXT does not provide the functionality to automatically poll the crypto-exchange data for you, so you would have to implement this yourself. If the data doesn't exist in an exchange reply we do not fabricate it out of thin air. 

```
historical = {}
while true:
    data = bitfinex.fetchOHLCV ('ETH/BTC', '1m')
    index_by_timestamp = {i[0]: i for i in data}
    historical.update(index_by_timestamp)
```

you could do something like this or use a database server to store historical data. Let me know if this helps you ;o

**Comment by kroitor** [comment]
@soerenmartius another way to get the earliest date is to fetch the earliest OHLCV timestamp from BitMEX using a high timeframe:

```Python
import ccxt
exchange = ccxt.bitmex({'enableRateLimit': True})
print('Timeframes:')
print(exchange.timeframes)
symbol = 'BTC/USD'
timeframe = '1d'
since = None
limit = 1
ohlcvs = exchange.fetch_ohlcv(symbol, timeframe, since, limit)
print('Earliest date:')
print(exchange.ymd(ohlcvs[0][0]))
timeframe = '1h'
ohlcvs = exchange.fetch_ohlcv(symbol, timeframe, since, limit)
print('Earliest hour:')
print(exchange.iso8601(ohlcvs[0][0]))
```

- https://github.com/ccxt/ccxt/wiki/Manual#pagination

Let us know if that does not help.

**Comment by frosty00** [comment]
Also there is a secret param in the docs for bitmex (i got confused and replied about bitfinex above, sorry!)

```
b.fetchOHLCV('.XBT', params={'start': 0})
```

this should give you the earliest timestamp OHLCV, unfortunately it you will have to convert the starting index to a timestamp by doing some maths.

**Comment by soerenmartius** [comment]
Hi guys,

Thanks for the detailed answers - I am aware of how to pull the data and also how to paginate. Some exchanges are just giving me a hard time when it comes to starting date for historical data. For some exchanges, if one passes a date previous to the starting date of the time series, the exchanges would not return you anything at all. Using the highest timeframe and resolving through the first timestamp of the initial data point of the time serious will work but rather looks hacky to me, that's the reason why i came up with the question also.

Also, are you sure that if you paginate the data it's a good idea to take the timestamp of the currents batches last element? If we use that timestamp to query the next batch by nature it will return the element of the used timestamp as the first element of the new batch - no?

At the moment we're using ```since = ohlcv_ts[:- 1]['timestamp'] + resolution_ms``` which seems to work and deliver data without any duplicates.

**Comment by soerenmartius** [comment]
I've tested the pagination approach mentioned in: https://github.com/ccxt/ccxt/wiki/Manual#pagination

Indeed, running `since = orders[len(orders) - 1]['timestamp']` will end up in fetching one duplicate data point per time series.

**Comment by kroitor** [comment]
@soerenmartius you're right on the duplication, that is just a simplified example if the Manual, we will alter it for the above.
