### ISSUE TITLE
Poloniex withdrawal id change suggestion

### ISSUE THREAD

**Issue by denarioresearch** [ccxt/ccxt#5364]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange: poloniex
- Method: withdraw

Here is an example of withdraw from Poloniex function output 
`{"info":{"response":"Withdrew 266.65869102 GNT.",  "email2FA":false, "withdrawalNumber":12674916}, "id":"Withdrew 266.65869102 GNT."}`

Suggest it would be more informative to use info.withdrawalNumber instead of info.response

**Comment by frosty00** [comment]
@denarioresearch, thank you for the suggestion, we appreciate your contribution to CCXT.

I've added this change in https://github.com/ccxt/ccxt/pull/5373
