### ISSUE TITLE
Issue #3594 reopen

### ISSUE THREAD

**Issue by gRittyKitty** [ccxt/ccxt#5365]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by gRittyKitty** [comment]
Wow I'm bad at this.

[Issue #3594](https://github.com/ccxt/ccxt/issues/3594) has become a problem again. As a refresher, itbit.js is not signing properly. 
I've tested out the same fix as before and it now works for me.

@trentduncan had the fix and also noted that the sign may need to integrate into it the body (right now it is hardwired to "").

I'm going to try a pull request with the fix. I'll also see if I can figure out best way to handle the "" vs the body. Right now I'm very tired so please check my work.

**Comment by gRittyKitty** [comment]
I've put in the pull request with the fixed code. However, it may be that the entire fix that I've put in is not necessary. I suspect the problem is that in the line:
`const auth = [ method, url, body, nonce, timestamp ];`
that the body param is causing the issue. And doing the following:
`let auth = [ method, url, '', nonce, timestamp ];
if (method === 'POST') {
   [ method, url, body, nonce, timestamp ]; 
}`
may solve the problem. I have not tried it, though.

**Comment by gRittyKitty** [comment]
Ok. I tried it (doing the if statement as above) and that works.
I'd recommend rejecting my pull request and doing the following:
`let auth = [ method, url, '', nonce, timestamp ];`
`if (method === 'POST') {`
 `auth = [ method, url, body, nonce, timestamp ];`
`}`

**Comment by gRittyKitty** [comment]
ok. new pull request made.
for some reason it is not passing a check.
i'm cooked. lmk if i've submitted in a reasonable fashion. i'll be back in (my) morning

**Comment by kroitor** [comment]
@gRittyKitty can you tell which particular endpoint is failing in this case plz?

**Comment by gRittyKitty** [comment]
Hi - I'm not sure there is more than one for itbit. At any rate, I use the
following:

new ccxt[exch](security[exch]);

Where exch='itbit' and the security[exch] is the private key data.
