### ISSUE TITLE
huobipro fetchOpenOrders returns closed orders

### ISSUE THREAD

**Issue by ngocpn57** [ccxt/ccxt#5376]
- OS: MacOS 10.14.5
- Programming Language version: Nodejs 10.15.3
- CCXT version: 1.18.828
- Exchange: huobipro
- Method: fetchOpenOrders

It looks like that the endpoint `https://api.huobi.pro/v1/order/history` is being called with a query parameter `status=pre-submitted,submitted,partial-filled` when using `fetchOpenOrders` method. I believe `https://api.huobi.pro/v1/order/openOrders` should be used instead

**Comment by kroitor** [comment]
We have reverted the defaults and the called endpoints to how they were before adding this change and we have added two options:

```Python
exchange = ccxt.huobipro ({
    
    # this option is for open orders only
    'fetchOpenOrdersMethod': 'fetch_open_orders_v1',  # or 'fetch_open_orders_v2'
    
    # this option is for all v1 orders
    'fetchOrdersByStatedMethod': 'private_get_order_orders',  # or 'private_get_order_history'
})
```

The `fetchOpenOrdersV1` method is the default and it will use the `privateGetOrderOrders` endpoint by default.
