### ISSUE TITLE
bitmex markets precision

### ISSUE THREAD

**Issue by KoenBal** [ccxt/ccxt#5382]
- OS: Windows 10
- Programming Language version: Python 
- CCXT version:1.18.807
- Exchange: bitmex
- Method: fetch_markets 

Hello,

bitmex BTC/USD market precision is
price: 0.5
amount: 1

If it should follow the logic as for example for Bitstamp.
trade details:
kraken BTC/USD 
price 13353.56 gives a precision of 2
amount: 0.49707233 gives a precision of 8

shouldn't it be
trade details:
bitmex BTC/USD
price: 12206.5 should give a precision of 1
amount: 2563 should give a precision of 0?

The manual also states:
>     'precision': {        // number of decimal digits "after the dot"
>         'price': 8,       // integer, might be missing if not supplied by the exchange
>         'amount': 8,      // integer, might be missing if not supplied by the exchange
>         'cost': 8,        // integer, very few exchanges actually have it
>     },

Shouldn't something like 
"minimum_price_increment" (0.5 in this case) and
"minimum_amount_increment" which I got from the bitmex contract specification exist?

Or does something similar already exist in the library?

For bitstamp this would be
minimum_price_increment: 1
minimum_amount_increment: 1

For bitmex:
minimum_price_increment: 5 (that is 5 times the price precision)
minimum_amount_increment: 1

If minimum_price_increment and minimum_amount_increment would not be available for a market you could assume that minimum_price_increment=1 and minimum_amount_increment=1.
Which is likely 99% of the cases.

,Thx for the great work so far

**Comment by brandsimon** [comment]
@KoenBal 
I am not sure I understand your question.
Bitmex uses TICK_SIZE precision mode and kraken uses DECIMAL_PLACES precision mode (which are totally different).

`number of decimal digits "after the dot"`
This is only true for DECIMAL_PLACES.

```
bitmex BTC/USD market precision is
price: 0.5
amount: 1
```
`minimum_price_increment: 5 (that is 5 times the price precision)`
I really dont get it. `5 * 0.5 = 2.5`
If this does not solve your issue, can you please be more specific about the issue you have? What are you trying to do and what result do you get and what have you expected to get?

**Comment by brandsimon** [comment]
The TICK_SIZE precision mode works like this. A precision of 0.5 for the price states, that all prices needs to be a multiple of 0.5. (0.5, 1, 1.5, 2.0, ...)

**Comment by kroitor** [comment]
@KoenBal let us know if the above answer by @brandsimon does not help!
More about handling precision with different rounding modes here: https://github.com/ccxt/ccxt/wiki/Manual#methods-for-formatting-decimals

**Comment by KoenBal** [comment]
Thanks for the replies. I think I got it now. The usage of the exchange.precisionMode property is what I was missing I guess.

Extra lessons learned:
Note that exchange.precisionMode returns an integer. A matching mode can subsequently be found in the decimal_to_precision file. These are:

# rounding mode
TRUNCATE = 0
ROUND = 1

# digits counting mode
DECIMAL_PLACES = 2
SIGNIFICANT_DIGITS = 3
TICK_SIZE = 4

# padding mode
NO_PADDING = 5
PAD_WITH_ZERO = 6

**Comment by kroitor** [comment]
@KoenBal thx for reporting back! Good to know you've figured it out!
