### ISSUE TITLE
okex3 fetch_order 

### ISSUE THREAD

**Issue by hucs2542** [ccxt/ccxt#5384]
>>ok3.fetch_order(order_id, symbol)

Traceback (most recent call last):
  File "/Users/apple/PycharmProjects/cxt/t.py", line 22, in <module>
    s = ok3.fetch_order_status(order_id, symbol)
  File "/Users/apple/miniconda3/lib/python3.7/site-packages/ccxt/base/exchange.py", line 1205, in fetch_order_status
    order = self.fetch_order(id, symbol, params)
  File "/Users/apple/miniconda3/lib/python3.7/site-packages/ccxt/okex3.py", line 1755, in fetch_order
    response = getattr(self, method)(self.extend(request, query))
AttributeError: 'okex3' object has no attribute 'spotGetOrdersInstrumentIdOrderId'

**Comment by kroitor** [comment]
@hucs2542 which symbol is it?

**Comment by hucs2542** [comment]
@kroitor EOS-USD-190927

**Comment by kroitor** [comment]
@hucs2542 use one of the following:

---------------------------------------

Option 1

```Python
exchange = ccxt.okex3 ({
    'options': {
        'fetchOrder': 'futures',
    },
})
order = exchange.fetch_order(id, symbol, params)
```

-----------------------------------------

Option 2

```Python
exchange = ccxt.okex3 ({
    'options': {
        'defaultType': 'futures',
    },
})
order = exchange.fetch_order(id, symbol, params)
```

-----------------------------------------

Option 3

```Python
params = {
    'type': 'futures',
}
order = exchange.fetch_order(id, symbol, params)
```

-----------------------------------------

Option 4

Wait 15 minutes for the new build to arrive, then update CCXT to version 1.18.838, then your code should work without edits:

```Python
order = exchange.fetch_order(id, symbol, params)
```

**Comment by hucs2542** [comment]
@kroitor Thank you
