### ISSUE TITLE
huobipro fetchOpenOrders: consider using different endpoints depends on whether symbol param is present

### ISSUE THREAD

**Issue by ngocpn57** [ccxt/ccxt#5388]
- OS: MacOS 10.14.5
- Programming Language version: Nodejs 10.15.3
- CCXT version: 1.18.829
- Exchange: huobipro
- Method: fetchOpenOrders

Suggestion:

- Use `v1/order/openOrders` if `symbol` parameter is present.
- If not, there's a way to get open orders of all symbols using `v1/order/orders?states=submitted,partial-filled,created`. The documentation says the endpoint will be deprecated, but their website is currently using it anyway

This is the request URL comes from their website querying for open orders
`https://www.hbg.com/-/x/pro/v1/order/orders?states=submitted,partial-filled,created&size=11` (I guess the APIs they're using are the same except the `https://www.hbg.com/-/x/pro/v1/` part)

**Comment by kroitor** [comment]
@ngocpn57 can you plz shed some light on it? Is there an issue with `openOrders` ?

**Comment by ngocpn57** [comment]
`openOrders` requires `symbol` param. By using `order/orders` we can obtain all open orders for all symbols

**Comment by frosty00** [comment]
Hi there @ngocpn57,

Currently, AFAIK, we don't support endpoint switching within a unified ccxt method. Ideally we would have a 1 -> 1 mapping of requests to unified ccxt methods. Moreover that endpoint is depreciated. Therefore I am not sure if we would want to support this feature, and if you need to get open orders for all symbols in the same manner as the website you can use:

```
this.fetchOrdersByStates ('submitted,partial-filled,created', symbol, since, limit, params);
```

**Comment by kroitor** [comment]
We have reverted the defaults and the called endpoints to how they were before adding this change and we have added two options:

```Python
exchange = ccxt.huobipro ({
    
    # this option is for open orders only
    'fetchOpenOrdersMethod': 'fetch_open_orders_v1',  # or 'fetch_open_orders_v2'
    
    # this option is for all v1 orders
    'fetchOrdersByStatedMethod': 'private_get_order_orders',  # or 'private_get_order_hustory'
})
```

The `fetchOpenOrdersV1` method is the default and it will use the `privateGetOrderOrders` endpoint by default.

Related: #5376.

**Comment by ianmere** [comment]
I think as of today they deprecated: v1/order/orders?

**Comment by kroitor** [comment]
@ianmere i don't think they're deprectaed, the last update in changelog related to those methods are as of February this year:

- https://huobiapi.github.io/docs/spot/v1/en/#change-log

![Screen-Shot-2020-02-07-at-22 13 10](https://user-images.githubusercontent.com/1294454/74066391-4b761100-49f7-11ea-8b94-117ed52eed0c.jpg)

**Comment by ianmere** [comment]
@kroitor Sorry your right, more accurately it seems now the symbol parameter is mandatory for this endpoint. Can others confirm?

**Comment by lostless13** [comment]
The "fetchOpenOrdersV1" method in the huobipro class that calls is the "order/orders" api endpoint is returning the following error from huobi for me when no symbol is provided:
```
ExchangeError: huobipro {"status":"error","err-code":"require-symbol","err-msg":"Parameter `symbol` is required.","data":null}
```

Looking through the docs they too seem to reflect requiring the symbol field too on the order/orders endpoint now.
![image](https://user-images.githubusercontent.com/24193723/74704622-491d6f00-51ce-11ea-9728-f8b8652bec06.png)

Unless I'm missing something in the docs, there is not a method that returns all open orders as far as I can tell.

**Comment by lostless13** [comment]
Created issue to track: https://github.com/ccxt/ccxt/issues/6498
