### ISSUE TITLE
Why can't I find the implementation of this method marginPostOrders in the code?

### ISSUE THREAD

**Issue by xiaoqge** [ccxt/ccxt#5390]
I am using okex3, I intend to refer to the original code to achieve the function of batch creation of orders, I see the following code in the line 1492-1493, why can't I find the implementation of the `marginPostOrders` method in the code file? Thank you.

https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/okex3.py 

`            method = 'marginPostOrders' if (marginTrading == '2') else 'spotPostOrders'`
`response = await getattr(self, method)(self.extend(request, params))`

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/5352#issuecomment-505179100
