### ISSUE TITLE
Binance fetchOpenOrders returns nothing

### ISSUE THREAD

**Issue by jzay** [ccxt/ccxt#5393]
- OS: MacOS 10.14.5
- Programming Language version: Python 3.6.4
- CCXT version: 19.1.1
- Exchange: Binance
- Method: fetchOpenOrders

Here is a code snippet. No matter how many open orders I have in Binance I keep getting nothing returned from the function. 

```Python
#fetch all the open orders of the user, get their order id and put them in a list
openorderids = []
orders = binance.fetchOpenOrders(pair)
print("Orders: ", orders)
for each in orders:
     openorderids.append(each['info']['orderId'])
#Cancelling all open orders
for id in openorderids:
     binance.cancelOrder(id, pair)
```

**Comment by frosty00** [comment]
Hi there @jzay. Binance `fetchOpenOrders` is working well, i just tested it. 

Are you sure you are using the right apiKeys? What is the output of `binance.fetchBalance`. Can you create an order using `binance.createOrder`? Is your library updated to the latest version?

**Comment by jzay** [comment]
I'm positive I'm using the right API keys and I am able to create orders on the correct account but when I try to cancel them with the code above I only receive empty dictionaries as a response when I have open order that need to be canceled. This code used to work for me so I don't know why it wouldn't now. Maybe you could run my function and see if it works for you?

 `def executeorder(binance):
    for j in range(3):
        try:
            asset = 'BTC'
            pair = 'BTC/USDT'
            usdt_valuee = binance.fetchBalance()['USDT']
            amount = usdt_valuee['total']
            orderbookprev = binance.fetch_order_book(pair)
            #LIMIT ORDER
            for i in range(30):
                prevorderprice = orderbookprev['bids'][0][0] if len (orderbookprev['bids']) > 0 else None
                assetamount = amount/prevorderprice
                assetbalance = (binance.fetch_free_balance()[asset])

                if (assetamount-assetbalance)*prevorderprice < 10:
                    break
                else:
                    orderbookcurrent = binance.fetch_order_book(pair)
                    orderprice = orderbookcurrent['bids'][0][0] if len (orderbookcurrent['bids']) > 0 else None
                    if(orderprice != prevorderprice or i ==0):
                        '''fetchOpenOrders not working'''
                        #fetch all the open orders of the user, get their order id and put them in a list
                        openorderids = []
                        orders = binance.fetchOpenOrders(pair)
                        print("Orders: ", orders)
                        for each in orders:
                            print("Each: ", each)
                            openorderids.append(each['info']['orderId'])
                        #Cancelling all open orders
                        for id in openorderids:
                            print("ID: ", id)
                            binance.cancelOrder(id, pair)
                        orderprice = orderbookcurrent['bids'][0][0] if len (orderbookcurrent['bids']) > 0 else None
                        limit_balance = assetamount-assetbalance
                        if asset == 'BTC':
                            limitbalance = float("%.6f" % (int(limit_balance*1000000)/float(1000000)))
                        elif asset == 'BCHABC' or 'BCHSV' or 'ETH' or 'LTC':
                            limitbalance = float("%.5f" % (int(limit_balance*100000)/float(100000)))
                        elif asset == 'NEO' or 'QTUM':
                            limitbalance = float("%.3f" % (int(limit_balance*1000)/float(1000)))
                        elif asset == 'NULS' or 'ONT' or 'EOS' or 'ETC' or 'ICX' or 'IOTA':
                            limitbalance = float("%.2f" % (int(limit_balance*100)/float(100)))
                        elif asset == 'TRX' or 'ADA' or 'XLM' or 'XRP':
                            limitbalance = float("%.1f" % (int(limit_balance*10)/float(10)))
                        max_order_amt = 2000/orderprice
                        order_size = min(max_order_amt, limitbalance)
                        order = binance.createLimitBuyOrder(pair, order_size, orderprice-200)
                orderbookprev = orderbookcurrent
                time.sleep(30)

            #fetch all the open orders of the user, get their order id and put them in a list
            openorderids = []
            orders = binance.fetchOpenOrders(pair)
            for each in orders:
                openorderids.append(each['info']['orderId'])
                #print(openorderids)
            #Cancelling all open orders
            for id in openorderids:
              binance.cancelOrder(id, pair)

            assetbalance = (binance.fetch_free_balance()[asset])
            if (assetamount-assetbalance)*prevorderprice > 10:
                #MARKET ORDER:
                orderbookcurrent = binance.fetch_order_book(pair)
                orderprice = orderbookcurrent['bids'][0][0] if len (orderbookcurrent['bids']) > 0 else None
                limitbalance = assetamount-assetbalance
                order = binance.createLimitBuyOrder(pair, limitbalance, orderprice+(orderprice*.01))
            break
        except (ccxt.ExchangeError, ccxt.NetworkError) as error:
            print('Got an error (executeorder): ', type(error).__name__, error.args)`

**Comment by kroitor** [comment]
@jzay what's your version of CCXT?

**Comment by jzay** [comment]
Ok so it started working for me again today. Thanks for the help I'm really unsure why it stopped working because I didn't make any changes to the code but luckily it seems to be returning my open orders now

**Comment by rori4** [comment]
I came across the same issue. I can create orders but after that when I try to fetch them the fetchOpenOrders returns nothing. My guess is that is related to some rate limit or smth. Any ideas?

**Comment by kroitor** [comment]
@rori4 we need a lot more info in order to be able to help you on that: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by rori4** [comment]
@kroitor Thanks for the info on how to get help. Unfortunately as time has passed the issue is not present anymore. This is why I think is a rate limit from Binance or something like that. If I come across it again I will log the verbose response and create an issue with a sample code.

**Comment by kroitor** [comment]
@rori4 sometimes, the order is not returned on your first attempt, but returned immediately afterwards on a retry – i think this is related to the messaging queue pipe on the Binance side. So, your order is accepted, but due to a mooning BTC, the number of requests and the overall load in general is so high that it takes time to process the order, and your fetchOpenOrders request does not see it on first attempt. Also, you may want to check this: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit, i'm assuming you have enabled it.

**Comment by rori4** [comment]
Yes, I have tried it but for my purpose it seems too limiting. Binance can handle a lot more requests then what this option restricts. Anyway it seems to be fixed now. I think you might be right that this can be because of Binance's load and the mooning BTC. Thanks for the response and thoughts 👍

**Comment by magnitis** [comment]
I came across the same issue the last couple of weeks and after a few retries the responses were coming as expected. However I know this is not ideal when developing or trading in real-time.
After looking into it the only thing I found out (after discussing it with a Binance dev too) was due to the markets being so busy and requests piling up.

**Comment by bedroomlab** [comment]
I've just encountered this. Specifically with MATICUSDT on Binance Futures. The order was there on screen, visible in the browser. I queried: all, open, closed. Says 0 for all of them. Then the order got stopped out and it's still showing 0  when I query it. Ten or so other symbols I was fetching at the same time worked ok except ATOMUSDT. I tried waiting and just fetching MATICUSDT again and again. Eventually after about 10 minutes. it returned all(2), open(0), closed(1) which suggests one is missing from closed. This is far from ideal.

**Comment by andy3520** [comment]
Suffer the same problem with SHIB/USDT today, it's can create order (I checked the binance app) but when I fetchOpenOrders it return nothing...

**Comment by kroitor** [comment]
@andy3520 please, paste the details: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by magnitis** [comment]
@andy3520 after talking several times with the Binance devs, they confirmed that this is a known REST API issue from their side during volatile markets. I ended creating something bespoke using Websockets and caching the updates using the a queue system.
