### ISSUE TITLE
How to install node package of CCXT??

### ISSUE THREAD

**Issue by Pushprajsinh** [ccxt/ccxt#5395]
ATTENTION!!!

MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- OS:Windows 10
- Programming Language version: VS 2017
- CCXT version:
- Exchange:
- Method:

**Comment by frosty00** [comment]
```
npm install ccxt
```

@kroitor close

**Comment by Pushprajsinh** [comment]
In Docker I have installed the package but did not have any idea to execute it please guide me sir.

**Comment by frosty00** [comment]
```
node
ccxt = require ('ccxt')
```

**Comment by frosty00** [comment]
please read the wiki before making an issue

https://github.com/ccxt/ccxt/wiki/Install

**Comment by Pushprajsinh** [comment]
![image](https://user-images.githubusercontent.com/52342972/60380728-eb35ee80-9a67-11e9-97a3-18f529937131.png)

i want to call the methods of some basic Exchanges of CCXT From Postman but i don't know the IP & PORT for it.(In CCXT-REST it is easily to run any method from POSTMAN) but in CCXT it is not working so let me guide

**Comment by kroitor** [comment]
@Pushprajsinh let us know if you have any issues with after reading through the manual from top to bottom: https://github.com/ccxt/ccxt/wiki .

**Comment by frosty00** [comment]
you have to attach to the container by using `docker run -it ccxt` but in this case the name of the container you need to connect to is the hex column under "name".

it is all in the wiki under https://github.com/ccxt/ccxt/wiki/Install#docker

**Comment by Pushprajsinh** [comment]
Yes i read this document but still i don't get any idea.

**Comment by frosty00** [comment]
did you try `docker run -it d043...`

**Comment by Pushprajsinh** [comment]
![image](https://user-images.githubusercontent.com/52342972/60380785-bfffcf00-9a68-11e9-94ee-46f8af1bb63e.png)

**Comment by frosty00** [comment]
okay, now you are connected to a installed ccxt. Type:

```
node
> ccxt = require ('ccxt')
```

**Comment by Pushprajsinh** [comment]
can i call the method from Postman or Web Browse? with using IP & PORT

**Comment by frosty00** [comment]
you can call the method from a web browser by using the `ccxt.browser.js` file in the ccxt directory.

**Comment by kroitor** [comment]
@Pushprajsinh see these examples on how to use CCXT within your browser: https://github.com/ccxt/ccxt/tree/master/examples/html

**Comment by Pushprajsinh** [comment]
Ok But What is the IP Address? What is the PORT?

**Comment by kroitor** [comment]
@Pushprajsinh there is no address nor port for using ccxt in the browser. Those settings are relevant to `ccxt-rest` only. Please read the Manual carefully on how to use CCXT and see the examples here:

- https://github.com/ccxt/ccxt/tree/master/examples/html
- https://github.com/ccxt/ccxt/wiki/Manual

**Comment by Pushprajsinh** [comment]
Ok CCXT-REST was Easily working.but IN CCXT Some method not working.
OKEX3 is updated in CCXT-REST??

**Comment by kroitor** [comment]
@Pushprajsinh we're not responsible for CCXT-REST, it's a standalone project by @aloysius-pgast , so, you might want to address the questions on CCXT-REST to @aloysius-pgast . We're responsible for CCXT, which is the library used in CCXT-REST, and the library is intended to be used by developers to develop their bots and applications on top of it. In the CCXT library the OKEX v3 implementation is up to date.

**Comment by Pushprajsinh** [comment]
Ok CCXT-REST was Easily working.but IN CCXT Some method not working.
OKEX3 is updated in CCXT-REST??

**Comment by kroitor** [comment]
@Pushprajsinh if you have an issue with a particular method of CCXT, then you need to paste here a complete code snippet to reproduce (10-20 lines including the exchange instantiation code) and your verbose request and response **precisely** as described here (we need **both** the request and the response parts):

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
