### ISSUE TITLE
Bitsane exchange exit scam

### ISSUE THREAD

**Issue by aleksraiden** [ccxt/ccxt#5396]
Maybe remove code and definition? 

Proof: 
RU - https://forklog.com/eshhe-odin-ekzit-skam-rukovodstvo-kriptovalyutnoj-birzhi-bitsane-ischezlo-so-sredstvami-klientov/

EN: https://www.forbes.com/sites/hanktucker/2019/06/27/crypto-exchange-and-xrp-refuge-bitsane-vanishes-scamming-as-many-as-246000-users/#2a6e66c177fa

**Comment by kroitor** [comment]
@aleksraiden thx! We've been tracking the news, so, yes, `bitsane` is going to be delisted shortly.

**Comment by aleksraiden** [comment]
Lot of thanks!
