### ISSUE TITLE
Questions on websocket

### ISSUE THREAD

**Issue by andrewlin0410** [ccxt/ccxt#5397]
Hi I wonder if websockets are implemented for Binance and Upbit. If so, is the update realtime/instant. I was using a Java library and it seems the websocket on that only updates once every second.

**Comment by andrewlin0410** [comment]
I heard Binance only update its websocket once every second. Is that true? Thanks in advance

**Comment by kroitor** [comment]
Hi!

> I wonder if websockets are implemented for Binance and Upbit.

The WS is not added to CCXT yet. We will post an update specifically on that next week, see here for more details: https://github.com/ccxt/ccxt/issues/56#issuecomment-505848697

> I heard Binance only update its websocket once every second. Is that true? Thanks in advance

We cannot answer on the WS until issue #56 is closed, unfortunately.

Hope the above answers your questions.
