### ISSUE TITLE
aiohttp_trust_env variable is not working on Python. 

### ISSUE THREAD

**Issue by synchronizing** [ccxt/ccxt#5403]
Hey guys. As it would seem, the flag `aiohttp_trust_env` variable does not seem to work within `ccxt.async_support`. The script below gives a better sense; we are loading non-functional proxy and expecting errors to be thrown on every function due to connectivity issue. Unfortunately, on the last step where `async_ccxt` is called no error is thrown (in contrast to `async_aiohttp`). 

```python
import asyncio
import aiohttp
import inspect
import os

import ccxt.async_support as ccxt_async
import ccxt as ccxt

# Setting env proxy var to random numbers (to fail).
os.environ["http_proxy"] = "http://0.0.0.0:0000"
os.environ["https_proxy"] = "http://0.0.0.0:0000"

# Printing the env aiohttp will load.
print("aiohttp loaded proxy settings :", aiohttp.helpers.proxies_from_env(), "\n")

def sync_ccxt():
    ex = ccxt.binance({"trust_env": True})
    return ex.fetch_ohlcv("ETH/BTC", "1m", 1514764800000)

async def async_aiohttp():
    async with aiohttp.ClientSession(trust_env=True) as session:
        async with session.get("https://api.ipify.org?format=json") as response:
            return await response.read()

async def async_ccxt():
    ex = ccxt_async.binance({"aiohttp_trust_env": True})
    print("async_ccxt : aiohttp_trust_env = ", ex.aiohttp_trust_env)
    resp = await ex.fetch_ohlcv("ETH/BTC", "1m", 1514764800000)
    await ex.close()
    return resp

# Function handling for pretty print.
async def handle(func):
    try:
        if inspect.iscoroutinefunction(func):
            await func()
        else:
            func()
    except Exception:
        print(func.__name__, ": has thrown error.")
        return

    print(func.__name__, ": did NOT throw error.")

loop = asyncio.get_event_loop()
for function in (sync_ccxt, async_aiohttp, async_ccxt):
    loop.run_until_complete(handle(function))
```

Outputs the following:

```bash
aiohttp loaded proxy settings :  {'http': ProxyInfo(proxy=URL('http://0.0.0.0'), proxy_auth=None), 'https': ProxyInfo(proxy=URL('http://0.0.0.0'), proxy_auth=None)}

sync_ccxt : has thrown error.
async_aiohttp : has thrown error.
async_ccxt : aiohttp_trust_env =  True
async_ccxt : did NOT throw error.
```

As you can see `aiohttp_trust_env` is not getting trusted, despite being recognized as being set to `True` after the async exchange is initialized. Let me also ask while at it: why did you guys choose to use `aiohttp_trust_env` as oppose to expand support for `trust_env` for the async library? Intuitively it makes more sense to have one flag for the entire `ccxt` program, imo.

I navigated a bit within `ccxt` to see if I could spot the bug, but frankly, I don't know enough about the architecture of the project to find it.

**Comment by kroitor** [comment]
Related: https://github.com/ccxt/ccxt/issues/3854#issuecomment-429644563

**Comment by synchronizing** [comment]
Opened PR using logic from the debug you rolled last night @kroitor, #5406. Tested and seems to be working fine.
