### ISSUE TITLE
bittrex fetch_closed_orders() returns error

### ISSUE THREAD

**Issue by WoK-E** [ccxt/ccxt#5407]
- OS: Linux
- Programming Language version: PHP 7.2
- CCXT version: 1.18.858
- Exchange: bittrex
- Method: fetch_closed_orders()

fetch_closed_orders(null, null, null, array()) returns the following:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request</h2>
<hr><p>HTTP Error 400. The request is badly formed.</p>
</BODY></HTML>

**Comment by frosty00** [comment]
Hi, there @Wok-E,

I could not reproduce your error. My output in php is: 

```
array(100) {
  [0] =>
  array(16) {
    'id' =>
    string(36) "5725a88d-3f10-4bf6-97dd-d567af392285"
    'timestamp' =>
    int(1523298048830)
    'datetime' =>
    string(24) "2018-04-09T18:20:48.830Z"
    'lastTradeTimestamp' =>
    int(1523298048957)
    'symbol' =>
    string(9) "WAVES/ETH"
    'type' =>
    string(5) "limit"
    'side' =>
    string(4) "sell"
    'price' =>
    double(0.00863973)
    'cost' =>
    double(0.11519991)
    'average' =>
    double(0.008639729738243)
    'amount' =>
    double(13.33374)
    'filled' =>
    double(13.33374)
    'remaining' =>
    double(0)
    'status' =>
    string(6) "closed"
    'fee' =>
    array(2) {
      'cost' =>
      double(0.00028799)
      'currency' =>
      string(3) "ETH"
    }
    'info' =>
    array(14) {
      'id' =>
      string(36) "5725a88d-3f10-4bf6-97dd-d567af392285"
      'marketSymbol' =>
      string(9) "WAVES-ETH"
      'direction' =>
      string(4) "SELL"
      'type' =>
      string(5) "LIMIT"
      'quantity' =>
      string(11) "13.33374000"
      'limit' =>
      string(10) "0.00863973"
      'timeInForce' =>
      string(18) "GOOD_TIL_CANCELLED"
      'fillQuantity' =>
      string(11) "13.33374000"
      'commission' =>
      string(10) "0.00028799"
      'proceeds' =>
      string(10) "0.11519991"
      'status' =>
      string(6) "CLOSED"
      'createdAt' =>
      string(23) "2018-04-09T18:20:48.83Z"
      'updatedAt' =>
      string(24) "2018-04-09T18:20:48.957Z"
      'closedAt' =>
      string(24) "2018-04-09T18:20:48.957Z"
    }
  }
...
```

What code did you use to instantiate the bittrex object? What version of CCXT are you using?

**Comment by WoK-E** [comment]
Well, it seemed pretty strange to me too, as it was working fine until some days ago (maybe a month?), but I found the problem:
If I pass a $since parameter, I get the error, regardless of whether I have set the $limit parameter. Passing null for $since, produces no errors and returns all (or up to bittrex's page size) closed orders.

**Comment by frosty00** [comment]
The issue is because there is a space in the query string. i.e.  https://api.bittrex.com/v3/orders/closed?startDate=1970-01-01 works where https://api.bittrex.com/v3/orders/closed?startDate=1970-01-01 00:00:00Z is broken. Will investigate further...

**Comment by kroitor** [comment]
@frosty00 should be `T` instead of a space there... I think this is a PHP-only bug with ISO formatting. We have an argument for that in `iso8601()`, `ymdhms()` and `ymd()`.

**Comment by frosty00** [comment]
yep was a simple fix
