### ISSUE TITLE
New Exchange: CryTrEx.com

### ISSUE THREAD

**Issue by CryTrExcom** [ccxt/ccxt#5417]
https://trade.crytrex.com

API endpoint is on this page under API link

Only public method available.

Thabks for help adding our exchange.

**Comment by CryTrExcom** [comment]
How many time to add it? For our service is urgent:)
Thank you in advance

**Comment by frosty00** [comment]
Hi there @CryTrExcom,

We would love to code up your API.

Please get in touch via info@ccxt.trade

**Comment by CryTrExcom** [comment]
Ok, can contact soon

**Comment by CryTrExcom** [comment]
> Hi there @CryTrExcom,
> 
> We would love to code up your API.
> 
> Please get in touch via [info@ccxt.trade](mailto:info@ccxt.trade)

Any info? we have sent email, thank you

**Comment by kroitor** [comment]
@CryTrExcom can you please retry again with a copy to igor@ccxt.trade and peter@ccxt.trade? We have not received it yet. Or alternatively, let us know your contacts, we will reach out to you asap.

**Comment by CryTrExcom** [comment]
E-Mail sent

**Comment by CryTrExcom** [comment]
anyone can help?
or where to add Crytrex to available exchange to test php code

thank you

**Comment by kroitor** [comment]
@CryTrExcom we will reply to your email ASAP.

**Comment by CryTrExcom** [comment]
ok Thanks

**Comment by An-Net** [comment]
Shutdown 1 September 2020
https://www.cryptowisser.com/exchange/crytrex/?lang=ru
<img width="1440" alt="Снимок экрана 2021-05-21 в 17 12 32" src="https://user-images.githubusercontent.com/51840849/119151124-bfef8a80-ba57-11eb-8f53-6afafc9da3e5.png">
