### ISSUE TITLE
ccxt should be put on Packagist (PHP)

### ISSUE THREAD

**Issue by takutaku947** [ccxt/ccxt#542]
Hi,
I think this project should be register to Packagist, because many developers who are using PHP is using Composer to maintain libraries.

If your project is register to Packagist, I think it's more easier to use this.

(Currently I don't have enough time to register to Packagist due to examination, so I'm just registering this issue. If I get more time, I'll try to do that.)

**Comment by kroitor** [comment]
https://packagist.org/packages/ccxt/ccxt

**Comment by takutaku947** [comment]
Nice, thank you for your fastest work.
