### ISSUE TITLE
Password protected proxy.

### ISSUE THREAD

**Issue by dmitriano** [ccxt/ccxt#5425]
OS: ubuntu 16.04
Programming Language version: nodejs v8.12.0
CCXT version: ccxt@1.18.395
Exchange: binance
Method: exchange.proxy

Is it possible to create an exchange with a password protected proxy in JavaScript?

I [tried ](https://github.com/ccxt/ccxt/issues/3900)

```
user:password@https://domain.com:3129
user:password@domain.com:3129:HTTPS
```
but with no success.

Also it is not clear enough what does "The absolute exchange endpoint URL is appended to this string before sending the HTTP request." mean in [docs](https://github.com/ccxt/ccxt/wiki/Manual)? Why is the  endpoint URL should be appended to the proxy URL?

**Comment by kroitor** [comment]
Hi @dmitriano !

> Also it is not clear enough what does "The absolute exchange endpoint URL is appended to this string before sending the HTTP request." mean in docs? Why is the endpoint URL should be appended to the proxy URL?

It is about CORS proxies, the `.proxy` property is for CORS only. 

If you want to use HTTP(S) proxies or SOCKS proxies, then you need to configure a proxy agent as described here:

- https://github.com/ccxt/ccxt/wiki/Install#javascript-proxies

Hope that answers the question.
