### ISSUE TITLE
Huobi fetchDepositAddress doesn't work any more

### ISSUE THREAD

**Issue by Kosteg** [ccxt/ccxt#5426]
- OS: OSX 10.14.4, Ubuntu 19
- Programming Language version: Node JS (v12)
- CCXT version: 1.18.869
- Exchange: Huobi
- Method: fetchDepositAddress

The exchange returns the error code "login-required". The method worked fine until a few weeks ago. The other private requests like fetchBalance work fine.

**Comment by frosty00** [comment]
We have decided to remove the endpoint since it was always undocumented and huobi now checks the request cookies to see if you are logged in. In other words it is impractical to use alongside the rest of the ccxt API.
