### ISSUE TITLE
Question about manual - Notes On Order Book Structure

### ISSUE THREAD

**Issue by KoenBal** [ccxt/ccxt#5433]
Hello,

I've a question about [notes on order book structure](https://github.com/ccxt/ccxt/wiki/Manual#notes-on-order-book-structure)
Currently it says:

> exchange.last_response_headers['Date'] is the date-time string of the last HTTP response received (from HTTP headers). The 'Date' parser should respect the timezone designated there. The precision of the date-time is 1 second, 1000 milliseconds. This date should be set by the exchange server when the message originated according to the following standards:

Is it correct to say?

> orderbook['datetime'] is the date-time string of the last HTTP response received which is the parsed datetime of exchange.last_response_headers['Date'].  The precision of the date-time is 1 second, 1000 milliseconds. This HTTP response 'Date' should be set by the exchange server when the message originated according to the following standards:
...
>

> The 'Date' parser should respect the timezone designated there. 
>
The 'Date' parser. Where should this last_response_headers['Date'] parser be defined? In fetch_order_book? 
"there": Where is there? The location of the exchange's servers?

, Thx for clarifying

PS; Should I ask this kind of questions via an Issue or is there a way to directly discuss on the manual similar to Medium responses?

**Comment by frosty00** [comment]
Hi there @KoenBal,

`exchange.last_response_headers ` is currently depreciated, I will update the manual to reflect this change.

Instead we recommend to use

```
orderbook = exchange.fetch_order_book('ETH/BTC')
print(orderbook['timestamp'])
```

> PS; Should I ask this kind of questions via an Issue or is there a way to directly discuss on the manual similar to Medium responses?

You will get the fastest replies by asking in ccxt issues.

**Comment by KoenBal** [comment]
@frosty00
Should orderbook['datetime'] = exchange.iso8601(orderbook['timestamp'] )
or will orderbook['datetime'] be removed in the future?

**Comment by frosty00** [comment]
Nope, `orderbook['datetime]` is part of the unified API. Let us know if you have any further questions )

**Comment by kroitor** [comment]
@KoenBal this should always be true: `orderbook['datetime'] === exchange.iso8601(orderbook['timestamp'])`

**Comment by KoenBal** [comment]
Oke, thanks for confirming. That ll be all :)
