### ISSUE TITLE
Bitfinex market parsing issue for new symbols (futures?)

### ISSUE THREAD

**Issue by nbouscal** [ccxt/ccxt#5437]
- OS: MacOS 10.13.6 and Ubuntu 18.04
- Programming Language version: Python 3.7.3
- CCXT version: 1.18.877
- Exchange: Bitfinex
- Method: `load_markets`

If you call `public_get_symbols` on bitfinex, there are two new symbols that have been added, `btcf0:ustf0` and `ethf0:ustf0`. This violates the expected format (e.g. `btcusd`) and results in markets called `BTC/F0:` and `ETH/F0:`. I'm not sure what these two symbols are meant to represent, possibly futures, but in any case these market symbols are incorrect. (They wreaked havoc in a bit of my code that foolishly assumed tickers wouldn't have colons in them :P)

**Comment by frosty00** [comment]
I'm not sure what these symbols are supposed to represent either. Something interesting is that they have the margin flag set to true, so maybe the strange symbol is supposed to represent that margin is allowed?
