### ISSUE TITLE
Binance New coins fetch ticker not working

### ISSUE THREAD

**Issue by rahulkumarbudhwani1** [ccxt/ccxt#544]

**Comment by kroitor** [comment]
Sorry, can you elaborate please?

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by kroitor** [comment]
Without a proper indication of that exactly isn't working, we can't help resolve this issue, sorry, but I'm closing this down, if you don't mind. Feel free to reopen it if you can provide more info on the problem. It's really hard to guess it from you vague description.
