### ISSUE TITLE
How to fetch more than 100 tickers with CoinMarketCap in PHP?

### ISSUE THREAD

**Issue by Modrx** [ccxt/ccxt#5441]
Can you please provide the code in PHP to fetch and paginate to get all the Price Tickers instead of just 100 for CoinMarketCap

if ($exchange->has['fetchTickers']) {
    var_dump ($exchange->fetch_tickers ()); // all tickers indexed by their symbols
}

**Comment by kroitor** [comment]
Dupe: #5490
