### ISSUE TITLE
Shrink Repository size

### ISSUE THREAD

**Issue by sips4711** [ccxt/ccxt#5442]
Hi all,
I use ccxt as a submdule in my project by "git clone --recurse-submodules ...". Is it possible to wipe this huge file here?

du -sh .git/modules/lib/ccxt/objects/pack/pack-ab5d9ae607fe24147c73c6cde5a91a534d297a7d.pack 
768M	.git/modules/lib/ccxt/objects/pack/pack-ab5d9ae607fe24147c73c6cde5a91a534d297a7d.pack

**Comment by frosty00** [comment]
not really since it contains the entire git history of the repo.

if you want just the latest commit please use `git clone --depth 1`

**Comment by kroitor** [comment]
@sips4711 can you suggest a non-breaking way to reduce it? We've tried looking, but have not found a suitable solution that would not break the forks, most of those solutions prune unreferenced pieces of git history by rewriting it, which does not work very well with the existing GitHub forks...

**Comment by sips4711** [comment]
Hi Igor.
I don't know how to do it. Maybe somebody else can help. Sorry.

Igor Kroitor <notifications@github.com> schrieb am Do., 4. Juli 2019, 18:20:

**Comment by brandsimon** [comment]
This is not possible due to how git works. (Every hash depending on the previous stuff)
Changing it will break every fork and every developer clone at every developer machine.
I understand the request, I'd also like to have a faster checkout, but rewriting (the) history is always a bad idea.

**Comment by kroitor** [comment]
@sips4711 i'd close this for now, until we find a good way to address this. Feel free to reopen it or just ask further questions if you have more. Let us know if you find a good solution, we would want to reduce the size of the repo, of course.
