### ISSUE TITLE
Bleutrade delisting some coins...

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5445]
Dear Bleutradians,

We are undergoing some changes and this new phase requires more protection criteria for and from our users. This review analyzed the commitment of development teams, source code quality, blockchain stability, communications to the public, contributions to the crypto world and other adaptations to Maltese legislation.

Follow below the list of projects that will have their trades cut off and markets will be removed by 2019-07-15 15:00 (UTC).

ADC (Audiocoin)
BBK (Bitblocks)
BC (Bitcoin Confidential)
BIFD (Biffy Diamond)
BITB (BitBean)
BOON (BoonCoin)
BTG (Bitcoin Gold)
CDN (Canada eCoin)
CRM (Cream)
DART (DarexTravel)
DCR (Decred)
DIVI (Divi)
DIVX (Divi Exch Token)
DNA (EncrypGen)
DOGE (Dogecoin)
EEE (Elementh)
EJOB (Ejob)
FJC (FujiCoin)
FREE (Free Coin)
GB (Goldblocks)
GODZ (Godzillion)
HBZ (Helbiz)
HTML (Htmlcoin)
IFT (InvestFeed)
IOP (Internet of People)
IOST (IOSToken)
KNT (Knekted)
KOLIN (Kolin)
LEND (ETHLend)
LGS (LogisCoin)
MAG (CrypticMAG)
MONA (Monacoin)
NMC (Namecoin)
OK (OKCash)
PCN (PeepCoin)
PENG (Peng)
QTUM (Qtum)
RDD (Reddcoin)
ROY (Roy)
RSTR (Ondori)
SICA (SignatureChain)
SLC (Slice)
SMART (SmartCash)
SWFTC (SwftCoin)
TASK (Taskeva)
TEEN (MyTeenCoin)
UNO (Unobtanium)
VRC (VeriCoin)
VSF (VeriSafe)
VTC (Vertcoin)
WAVES (Waves)
XOLA (XOLA)
XP (ExperiencePoints)
ZAI (Zaigar)
ZEUS (ZeusNetwork)

Withdraws will be possible until 2019-09-31 15:00 (UTC).

We appreciate your patience and understanding as we continue to build a better crypto world together. We are always improving to give you a better experience.

Bleutrade Team.

**Comment by kroitor** [comment]
@npomfret thx for the updates! Really appreciate your help with maintaining it! Though, they seem to react as soon as we merge your PRs ) Should we merge less just to keep the economy stable for a while? )))
