### ISSUE TITLE
Shrink Docker Image 

### ISSUE THREAD

**Issue by sips4711** [ccxt/ccxt#5446]
Hi all,
Docker Image size and complexity can be reduced. This would be nice in combination with: [https://github.com/ccxt/ccxt/issues/5442](https://github.com/ccxt/ccxt/issues/5442)

To reproduce:
docker build -t ccxt/old .
docker build -f ./Dockerfile.new -t ccxt/new .

Images:
REPOSITORY  TAG     IMAGE ID        CREATED         SIZE
ccxt/new    latest  76c4e0b787fa    13 hours ago    856MB
ccxt/old      latest  bdd8f29c4f75    13 hours ago    892MB

"docker image inspect bdd8f29c4f75"  says that 21 Layers are created
"docker image inspect 76c4e0b787fa" says that 10 Layers are created
Count: 
...
 "RootFS": {
            "Type": "layers",
            "Layers": [               
          "sha256:762d8e1a60542b83df67c13ec0d75517e5104dee84d8aa7fe5401113f89854d9",
          ...

I did that by reducing the "RUN" commands in this Dockerfile. Each "RUN" Command creates a new Layer (and complexity as well).

New Dockerfile:
```
FROM ubuntu:18.04

# Supresses unwanted user interaction (like "Please select the geographic area" when installing tzdata)
ENV DEBIAN_FRONTEND=noninteractive

ADD . /ccxt
WORKDIR /ccxt

# Update packages (use us.archive.ubuntu.com instead of archive.ubuntu.com — solves the painfully slow apt-get update)
RUN sed -i 's/archive\.ubuntu\.com/us\.archive\.ubuntu\.com/' /etc/apt/sources.list \
    && apt-get update \
# Miscellaneous deps
    && apt-get -y install curl gnupg git pandoc \
# PHP
    && apt-get install -y php php-curl php-iconv php-mbstring php-bcmath \
# Node
    && curl -sL https://deb.nodesource.com/setup_11.x | bash - \
    && apt-get -y install nodejs \
# Python 2
    && apt-get install -y python-pip \
    && pip2 install --upgrade setuptools \
# Python 3
    && apt-get install -y python3 python3-pip \
    && pip3 install --upgrade setuptools \
# Copy files to workdir to && install scripts against it (will be replaced with a live-mounted volume at startup)
&& mkdir -p /ccxt \
&& rm -rf /ccxt/node_modules \
# Installs as a local Node & Python module, so that `require ('ccxt')` and `import ccxt` should work after that
    && npm install \
    && ln -s /ccxt /usr/lib/node_modules/ \
    && echo "export NODE_PATH=/usr/lib/node_modules" >> $HOME/.bashrc \
    && cd python && python3 setup.py install && python setup.py install && cd .. \
## Remove apt sources
    && apt-get -y autoremove && apt-get clean && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

**Comment by frosty00** [comment]
Hi please make a pull request with any changes you would like to see in the docker file, we cannot easily make edits from an issue.

**Comment by sips4711** [comment]
Pull Request created here: [https://github.com/ccxt/ccxt/pull/5447](https://github.com/ccxt/ccxt/pull/5447)
