### ISSUE TITLE
Exchange.php safe_currency_code & safeCurrencyCode method signature mismatch

### ISSUE THREAD

**Issue by JulienNadon** [ccxt/ccxt#5454]
- OS: OSX 10.13.6
- Programming Language version: PHP 7.2.13
- CCXT version: 1.18.888
- Exchange: PHP - All exchanges (Exchange.php) *tested using Bitstamp
- Method: safeCurrencyCode()

Recent changes to exchange.js modified the method signature for safeCurrencyCode()
subsequently safe_currency_code() in the php base class, exchange.php, was modified, but the corresponding camelCase method, safeCurrencyCode() was not modified.

https://github.com/ccxt/ccxt/blob/master/php/Exchange.php#L1713
https://github.com/ccxt/ccxt/blob/master/php/Exchange.php#L1713

As a result, an exception is thrown.
```Too few arguments to function ccxt\Exchange::safeCurrencyCode(), 1 passed in /var/www/vendor/ccxt/ccxt/php/bitstamp.php on line 183 and at least 2 expected```

From PR: https://github.com/ccxt/ccxt/pull/5422/files?file-filters%5B%5D=.php#diff-d087d122b9d18390abb24d8b2cb6160f

**Comment by kroitor** [comment]
@JulienNadon thx for reporting! Fixed it.
