### ISSUE TITLE
Market Cap Data

### ISSUE THREAD

**Issue by nettemNvest** [ccxt/ccxt#5459]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by nettemNvest** [comment]
is there any posibiltiy to get the market cap data from ccxt if not can u suggest another way to get it..
and if it needs to be calculted how to calculate .....
and how can i get the values to calculate

**Comment by kroitor** [comment]
Please, read here, all about fetching market data:

- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/tree/master/examples

Let us know if that does not help.

**Comment by nettemNvest** [comment]
i did but i cant able to find any where to get the market cap data

**Comment by kroitor** [comment]
@nettemNvest you can fetch it from CoinMarketCap. Which language do you use?

**Comment by nettemNvest** [comment]
Nodejs sir....

**Comment by nettemNvest** [comment]
market cap is calculated using price and circulating supply  but how can i get the circulating supply of a currecny

**Comment by kroitor** [comment]
See here:

https://github.com/ccxt/ccxt/blob/master/examples/js/cli.js

+ see all other examples with the word `ticker` here: https://github.com/ccxt/ccxt/tree/master/examples/js/

```
mbp:ccxt igorkroitor$ node examples/js/cli coinmarketcap fetchTicker BTC/USD
coinmarketcap.fetchTicker (BTC/USD)
{        symbol:   "BTC/USD",
      timestamp:    1562319089000,
       datetime:   "2019-07-05T09:31:29.000Z",
           high:    undefined,
            low:    undefined,
            bid:    undefined,
      bidVolume:    undefined,
            ask:    undefined,
      askVolume:    undefined,
           vwap:    undefined,
           open:    undefined,
          close:    11160.3349796,
           last:    11160.3349796,
  previousClose:    undefined,
         change:    undefined,
     percentage:    -4.49,
        average:    undefined,
     baseVolume:    undefined,
    quoteVolume:    24959129734.9,
           info: {                 id: "bitcoin",
                                 name: "Bitcoin",
                               symbol: "BTC",
                                 rank: "1",
                            price_usd: "11160.3349796",
                            price_btc: "1.0",
                     '24h_volume_usd': "24959129734.9",
                       market_cap_usd: "198647824453", // ←-------------- HERE IT IS
                     available_supply: "17799450.0",
                         total_supply: "17799450.0",
                           max_supply: "21000000.0",
                    percent_change_1h: "1.79",
                   percent_change_24h: "-4.49",
                    percent_change_7d: "-3.66",
                         last_updated: "1562319089"     } }
mbp:ccxt igorkroitor$
```

Save to file and run with node:

```JavaScript
const ccxt = require ('ccxt')
const exchange = new ccxt.coinmarketcap ({ enableRateLimit: true })

;(async () => {
    const base = 'BTC'
    const ticker = await exchange.fetchTicker (base + '/USD');
    console.log (base, 'market cap in USD is', ticker['info']['market_cap_usd']);
}) ()
```

↑ It can take some time due to market caching and reasons [explained in the Manual](https://github.com/ccxt/ccxt/wiki/Manual#loading-markets), I will not duplicate those explanations here. 

You can also `fetchTickers` to get them all in one go. The total supply of each currency is the blockchain info and you will have to set up your access to the underlying blockchain to get it.

Hope that helps.

**Comment by nettemNvest** [comment]
well thank you... sir....

**Comment by mklosi** [comment]
@kroitor   do you know if marketcap data is available only through the coinmarketcap client?

**Comment by kroitor** [comment]
@mklosi some exchanges and other services like coingecko provide that info as well, but unfortunately, i don't have a list of those.

**Comment by mklosi** [comment]
hi @kroitor   sorry to bug again about the same issue, but I'm been struggling for a week to be able to get a list of symbols for a market (specifically for BTC market in Binance) sorted by marketcap, as it is apparently possible by looking at this page: 

<img width="1289" alt="Screen Shot 2020-11-22 at 11 08 42" src="https://user-images.githubusercontent.com/3664558/99914579-27986900-2cb3-11eb-8bc9-d13ffa7dee9f.png">

I don't even need the specific marketcap for each symbol. I just need a list of symbols sorted by marketcap, desc.

Is there a way to currently get that with ccxt? "coinmarketcap" exchange through ccxt seems to be busted: 

`print(ccxt.coinmarketcap().fetch_ticker("ETH/BTC"))` -> `ccxt.base.errors.ExchangeNotAvailable: coinmarketcap GET https://api.coinmarketcap.com/v1/ticker/?limit=0 404 Not Found <html>`

**Comment by kroitor** [comment]
@mklosi i've posted your image and asked on Binance API group in Telegram, and they said they don't support it in their public API right now:

> Igor Kroitor, [23.11.20 01:46] A quick question: is there a way to fetch the market cap data (as shown on the Binance website) via the Binance API?
> Jeremy, [23.11.20 01:48] not available as I know

**Comment by mklosi** [comment]
thank you kroitor, for such a quick response. I guess for now I'll be drag and dropping text cuts by hand :)

**Comment by tmlee** [comment]
@mklosi do check out the coingecko API at https://www.coingecko.com/en/api
endpoints you might be interested in would be https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd
