### ISSUE TITLE
Make exceptions less noisy

### ISSUE THREAD

**Issue by hroff-1902** [ccxt/ccxt#5461]
In the meantime all the details of the http- and exchange- errors are included in the exception string:

```
    def raise_error(self, exception_type, url=None, method=None, error=None, details=None):
        if error:
            error = str(error)
        output = ' '.join([self.id] + [var for var in (url, method, error, details) if var is not None])
        raise exception_type(output)
```
-- the `details` here includes the http-response came from exchange...

When we handle such exception in the app, this often results in long sheets of html data, even if the logging value is less than DEBUG and the user did not requested this high level of detalization.

The suggestion is to include the value of the `details` param into the exception string only when the DEBUG logging level is set for ccxt.

**Comment by frosty00** [comment]
yep this is something we are going to change - #5399

and we will move to a new `raise_error`

just waiting on @kroitor to merge my PR 😠

**Comment by frosty00** [comment]
our plan is to only set the error message in the error like 

```
error = Error(message)
error.body = body
error.httpCode = httpCode
error.requestHeaders = requestHeaders
etc...
raise error
```

**Comment by hroff-1902** [comment]
Fine if this is addressed in #5399. Waiting for it merged...

**Comment by kroitor** [comment]
@hroff-1902 it's not really addressed there yet, #5399 is just a preliminary work that would help us address the main issue, but we will roll out the main solution for generalized exceptions soon after. So, it's on the way )

**Comment by hroff-1902** [comment]
Actually, I don't think that all the details, including html responses should be added into the exception at all -- in the ccxt code base there are usually `logger.debug()` calls just before raising the exception so the user could simply switch on the debug logging level for ccxt in order to see all the html texts. No need to put in into the exception itself. Please review the behaviour here... Now the detailization level we obtain in the exceptions is too high and noisy...

**Comment by ahmedbodi** [comment]
i disagree. I personally use the exception messages to detect any errors. E.G. some exchanges have DDOS errors which arent handled by the exchange classes so i have to resort to parsing the actual HTML in the exception message to detect it and throttle my app

**Comment by ahmedbodi** [comment]
if we update all the exchange classes to actually contain high quality exception handling then it wouldnt be needed. but until then its pretty essential

**Comment by brandsimon** [comment]
@ahmedbodi 
Is there a reason to handle the ddos exceptions in your code instead of adding them to the exchanges in ccxt?

**Comment by ahmedbodi** [comment]
ideally they'd be handled in CCXT but many exchanges right now arent handled in CCXT

**Comment by frosty00** [comment]
> ideally they'd be handled in CCXT but many exchanges right now arent handled in CCXT

yep some exchanges are missing `handleErrors` we are working on this but won't give a timeframe.

> i disagree. I personally use the exception messages to detect any errors. 

that is why we will move to better error handling soon. tbh the actual `raise_errors` i have in mind will not take very long at all to write. Maybe it will be added tomorrow.

**Comment by ahmedbodi** [comment]
yep, ofc. thats my point. until they are, the HTML actually is useful for many people

**Comment by hroff-1902** [comment]
> i disagree. I personally use the exception messages to detect any errors. E.G. some exchanges have DDOS errors which arent handled by the exchange classes so i have to resort to parsing the actual HTML in the exception message to detect it and throttle my app

Yes, but, first of all, this content is duplicated in the logging messages (and this is controllable by setting the logging level for ccxt) and, second, if you have a requirement to be able to use this info, other users in the same time have a requirement to avoid spamming with exceptions that fill several screens. What can you suggest for us -- do not print the content of the exception at all, even if it's not noisy? How can we select in the application now between noisy ccxt exceptions and the rest of them? As I said, these both requirements are achievable if the info added to the exception depend on the logging level set to ccxt. Or by adding an additional field to the exception which can contain the detailed info if you really need it. Current "detailed" exceptions raised by ccxt are really annoying and frustrating, especially for the novice users that do not expect the complete sheets of the html texts on the screens...


> i disagree. I personally use the exception messages to detect any errors. E.G. some exchanges have DDOS errors which arent handled by the exchange classes so i have to resort to parsing the actual HTML in the exception message to detect it and throttle my app

Yes, but, first of all, this content is duplicated in the logging messages (and this is controllable by setting the logging level for ccxt) and, second, if you have a requirement to be able to use this info, other users in the same time have a requirement to avoid spamming with exceptions that fill several screens. What can you suggest for us -- do not print the content of the exception at all, even if it's not noisy? How can we select in the application now between noisy ccxt exceptions and the rest of them? As I said, these both requirements are achievable if the info added to the exception depend on the logging level set to ccxt. Or by adding an additional field to the exception which can contain the detailed info if you really need it. Current "detailed" exceptions raised by ccxt are really annoying and frustrating, especially for the novice users that do not expect the complete sheets of the html texts on the screens...

**Comment by ahmedbodi** [comment]
You cant parse the logging messages to react on it. all that does is fill it up in the logs for informational purposes. Once the new exception handling is in place and the rest of the exchanges actually throw exceptions properly instead of generic exceptions then there wont be a need for HTML errors. but until then that HTML is the only way to catch some errors

**Comment by ahmedbodi** [comment]
It's literally a case of laying the ground work to get to the point you want. without pissing off every other user. once its at that point then embedding the HTML in the exception isnt neccesary

**Comment by hroff-1902** [comment]
> You cant parse the logging messages to react on it. all that does is fill it up in the logs for informational purposes. Once the new exception handling is in place and the rest of the exchanges actually throw exceptions properly instead of generic exceptions then there wont be a need for HTML errors. but until then that HTML is the only way to catch some errors

First of all you can -- with an external tool/script/bunch of scripts logs are easily parsed. In principle. Second, if you need this detailed info -- okay, but we need an ability to hide it. You will switch it on if you need it, and many other people will switch it off. That' so easy. The problem now is that we are not able to hide all those noisy sheets of html texts if we don't need them and/or don't wish them be printed as a content of the exception raised by ccxt.

**Comment by ahmedbodi** [comment]
Okay so explain how to do this? 
(Only a sample)
```
try:
    api = ccxt.binance();
    api.fetchTicker()
except Exception as exc:
    if 'DDOS' in str(exc):
        api.rateLimit /= 10
time.sleep(api.rateLimit)
```

**Comment by kroitor** [comment]
@ahmedbodi the correct approach is:

```Python
try:
    api = ccxt.binance();
    api.fetchTicker()
except ccxt.DDoSProtection as exc:
    api.rateLimit /= 10
time.sleep(api.rateLimit)
```

However, your argument on incomplete handlers is also absolutely true, the error handling is not completely unified yet across all exchanges. The purpose of the edits linked above – is to get us closer to unification, that includes all `handleErrors` done properly within each derived exchange class. Some exchanges have unclear docs on errors and non-documented error formats, so, it's not trivial and requires some reverse-engineering, however, we will do our best to migrate to the 100%-unified error handling this month.

**Comment by ahmedbodi** [comment]
yep my code does that, but my point is for those exchanges where the error handling is not yet unified.

**Comment by ahmedbodi** [comment]
until it is unified, the HTML errors are essential to be able to detect which error it is.

**Comment by kroitor** [comment]
> my point is for those exchanges where the error handling is not yet unified

Your point is clear from the very start, and, of course, we would never leave it like that – it's in progress, hope for your understanding. Until it is unified you have to add workarounds in userland, that's right. We hope to unify it completely soon.

**Comment by hroff-1902** [comment]
@kroitor Will I be able (after mentioned unification) to log a less detailed exception string (say, with maximum one-string http response, without full html data) in the application if it's unwanted (for example, if the verbosity level in the application is not set to debug)? You answered several times to @ahmedbodi above that you understand him and that his points are clear, but I did not completely got yet if you understand why I'm asking for this detalization level be controllable (or at least all the detalization be separated in a field in the exception so that we could use a less noisy exception description if we need so)...

**Comment by hroff-1902** [comment]
> Okay so explain how to do this?
> (Only a sample)
> 
> ```
> try:
>     api = ccxt.binance();
>     api.fetchTicker()
> except Exception as exc:
>     if 'DDOS' in str(exc):
>         api.rateLimit /= 10
> time.sleep(api.rateLimit)
> ```

It's also quite simple with an external log parser: implement an IPC mechanism in your app that accepts the 'ratelimit' command (reducing the value of the rateLimit var, as you wrote), then run the app and an external parser for its log, the parser will run that 'ratelimit' command when it detects the 'DDOS' string in the logs... It's just a matter of the design of the whole app, which in this case will include an external log parser running in parallel with the main app...

As I said, I don't mind if in some conditions all those data will still be placed in the exceptions, if you and other users need it for some reasons, at all. Simply provide the users an ability to see less noisy exceptions if they do not need to see all this stuff...

**Comment by kroitor** [comment]
@hroff-1902 

> Will I be able (after mentioned unification) to log a less detailed exception string (say, with maximum one-string http response, without full html data) in the application if it's unwanted (for example, if the verbosity level in the application is not set to debug)?

No, never. We will not do anything convenient. Forget about it. Over @frosty00's body only. 

But, seriously, yes, of course ) The default level will be quite verbose, but you will have at least a few ways of setting the verbosity, either with an exchange property/option, or with a description override, as you noted below.

> I'm asking for this detalization level be controllable (or at least all the detalization be separated in a field in the exception so that we could use a less noisy exception description if we need so)...

This is exactly one of the purposes of the unification process that is going on, so, yes, you're right as well. Both of you are right ) I'm sure @ahmedbodi would be happy to rely on ccxt DDoS exceptions, if they were completely unified – in that case he would not need a long description either. I guess, he doesn't like to read too much meaningless markup either )

To me there's no argument above at all. CCXT is not ideal because it's a work in progress, but we will make it closer to an ideal soon. No worries, everyone will be happier.

**Comment by ahmedbodi** [comment]
yep. agreed. all in good time :) CCXT is awesome, but as with all software we can always improve it

**Comment by frosty00** [comment]
#5467

**Comment by hroff-1902** [comment]
How is it goes?  #5467 was closed, is there other new PRs related to this issue?

**Comment by kroitor** [comment]
@hroff-1902

> How is it goes?

@frosty00 helped make significant progress in that direction, so, we're doing great, we're very close to resolving this issue. 

> is there other new PRs related to this issue?

Yep: 

- https://github.com/ccxt/ccxt/pull/5470
- https://github.com/ccxt/ccxt/pull/5494
- ...

**Comment by frosty00** [comment]
#5494

**Comment by hroff-1902** [comment]
closing it, seems to be resolved long time ago, we do not see the sheets of noisy messages in the app for long time.

thanks
