### ISSUE TITLE
Is the gate interface now supported？

### ISSUE THREAD

**Issue by lfzCarlosC** [ccxt/ccxt#5466]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

using "gateio" to fetch data(e.g. ohlcv) throws error:

Using the following exchange(s): ['gateio']
gateio interface does not support timeframe queries! We are unable to fetch data!
Something went wrong fetching data for BTC/USDT, skipping

**Comment by kroitor** [comment]
@lfzCarlosC Which language are you using, what's your version of CCXT?

**Comment by frosty00** [comment]
working for me, @lfzCarlosC can you post the code so we can reproduce the error?

**Comment by lfzCarlosC** [comment]
version:

ccxt: 1.17.416
Python3

I think when runnig `get_historical_data` function it throws that error.

**Comment by lfzCarlosC** [comment]
version:

ccxt: 1.17.416
Python3

I think the root reason is that  I use `getattr(ccxt, 'gateio')({"enableRateLimit": True}).timeframes` and it throws exception
'gateio' object has no attribute 'timeframes'

**Comment by lfzCarlosC** [comment]
not sure if it is the right way to get data

**Comment by kroitor** [comment]
@lfzCarlosC it works for me:

```Python
mbp:python igorkroitor$ python3
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.


>>> import ccxt
>>> getattr(ccxt, 'gateio')({"enableRateLimit": True}).timeframes
{'1m': '60', '5m': '300', '10m': '600', '15m': '900', '30m': '1800', '1h': '3600', '2h': '7200', '4h': '14400', '6h': '21600', '12h': '43200', '1d': '86400', '1w': '604800'}
```

Also, your CCXT version is very old, can you update to the most recent version and check that again?

```Python
mbp:python igorkroitor$ python3
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.


>>> import ccxt

>>> print(ccxt.__version__)  # ←-------------- add this
1.18.894

>>> getattr(ccxt, 'gateio')({"enableRateLimit": True}).timeframes
{'1m': '60', '5m': '300', '10m': '600', '15m': '900', '30m': '1800', '1h': '3600', '2h': '7200', '4h': '14400', '6h': '21600', '12h': '43200', '1d': '86400', '1w': '604800'}
```

Let us know if the above does not help.

**Comment by lfzCarlosC** [comment]
thanks
