### ISSUE TITLE
fetch_ohlcv returns incorrect data given a start date

### ISSUE THREAD

**Issue by lfzCarlosC** [ccxt/ccxt#5468]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: linux
- Programming Language version:  python3.7.2
- CCXT version: 1.18.897
- Exchange: okex, gateio
- Method:

I am running fetch_ohlcv to retrieve data at a given time: 

`getattr(ccxt, 'okex')({"enableRateLimit": True}).fetch_ohlcv('BTC/USDT',timeframe='1d', since=1553776549591)`

`1553776549591` is on March 28, 2019. But the result only has one day data(only today's). 
This issue also happens on `gateio`.
This issue doesn't happen on some other exchage. e.g. binance, huobipro
This issue didn't happen in the old version 1.17.416

**Comment by kroitor** [comment]
@lfzCarlosC there was a bug in okex v1 fetchOHLCV. We recommend to switch to `okex3` (v3), because okex v1 is now deprecated. However, we fixed it and the plan is:

1. wait 15 minutes for the new version 1.18.899 to arrive.
2. update to the most recent version
3. try again:

```Python
candles = getattr(ccxt, 'okex')({"enableRateLimit": True}).fetch_ohlcv('BTC/USDT',timeframe='1d', since=1553776549591)
for candle in candles:
    print('Timestamp: ' + ccxt.Exchange.iso8601 (candle[0]))
```

or, better:

```Python
candles = getattr(ccxt, 'okex3')({"enableRateLimit": True}).fetch_ohlcv('BTC/USDT',timeframe='1d', since=1553776549591)
for candle in candles:
    print('Timestamp: ' + ccxt.Exchange.iso8601 (candle[0]))
```

Let us know if that does not help.

**Comment by lfzCarlosC** [comment]
Thanks, @kroitor. 👍

**Comment by lfzCarlosC** [comment]
Oh, @kroitor, `gateio` also has this issue.

**Comment by kroitor** [comment]
> Oh, @kroitor, `gateio` also has this issue.

Yes, but that one has always been there – it's a limitation on their side, you can easily see which URL it is querying and which response it is getting:

```Python
# add verbose =True
candles = getattr(ccxt, 'gateio')({"enableRateLimit": True, "verbose": True}).fetch_ohlcv('BTC/USDT',timeframe='1d', since=1553776549591)
for candle in candles:
    print('Timestamp: ' + ccxt.Exchange.iso8601 (candle[0]))
```

```
handleRestResponse:
 gateio GET https://data.gate.io/api2/1/candlestick2/btc_usdt?group_sec=86400 200 OK
Response:
 {
  Connection: 'close',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json',
  Date: 'Sat, 06 Jul 2019 10:59:32 GMT',
  Server: 'openresty/1.13.6.1',
  'Transfer-Encoding': 'chunked'
}
 {"elapsed":"5ms","result":"true","data":[["1562284800000","2985.4062239202","10985.25","11386","10812.42","11155.56"],["1562371200000","1290.0222880615","11320.3","11520","10968.35","10985.25"]]}
```

If you open this URL: https://data.gate.io/api2/1/candlestick2/btc_usdt?group_sec=86400 you will see that gateio does not return more than two candles for the `1d` timeframe.

**Comment by kroitor** [comment]
@lfzCarlosC the limitation with `gateio` is explained in the Manual here: 

- https://github.com/ccxt/ccxt/wiki/Manual#pagination
- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts
