### ISSUE TITLE
How to filter CCXT messages only with Python logging?

### ISSUE THREAD

**Issue by qwasko1212** [ccxt/ccxt#5471]
Hello. I have several modules which are using logging feature. However I would like to see log messages from CCXT only. How can i do it?

 I tried this code and it does not work.
`import logging`
`logger = logging.getLogger('ccxt')`
`logger.setLevel(level=logging.DEBUG)`

Following code shows all logging msg from other modules.
`import logging`
`logging.basicConfig(level=logging.DEBUG)`

- OS: Linux
- Programming Language version: Python 3.6
- CCXT version: 1.18.824
- Exchange: Bitmex
- Method: logging

**Comment by frosty00** [comment]
you need to pass a logger to the exchange class like so:

```
logger = logging.getLogger('ccxt')
exchange = exchange({'logger': logger})
```

**Comment by qwasko1212** [comment]
> ```
> logger = logging.getLogger('ccxt')
> exchange = exchange({'logger': logger})
> ```

Unfortunately it does not work. Maybe because I am using ccxt.async_support?

My code:
`import ccxt.async_support as ccxt`
`import logging`
`logger = logging.getLogger('ccxt')`
`logger.setLevel(level=logging.DEBUG) ` - I have tried also without this line

`exchange = ccxt.bitmex({'apiKey': api_key,  'secret': api_secret,  'logger': logger})`

**Comment by frosty00** [comment]
add this piece of code:

`logger.addHandler(logging.StreamHandler(sys.stdout))`

**Comment by frosty00** [comment]
(you could also add a fileHandler)
