### ISSUE TITLE
Does Bitmex Bulk order require different parameters? 

### ISSUE THREAD

**Issue by qwasko1212** [ccxt/ccxt#5475]
I have successfully placed all necessary orders via exchange.create_order. Now i would like to optimize work with exchange and place one bulk order instead of sending orders separately.  

Example of code for separate Stop order placement. It works
```
parameters = {'stopPx': stop_loss, 'execInst': 'Close'}
await ccxt.bitmex.create_order(symbol, 'Stop', side, amount_per_trade, None, parameters)
``` 

Code which i am trying to use for bulk order placement (Stop)

```
orders = list()
parameters = {'stopPx': stop_loss, 'execInst': 'Close'}
orders.append({"symbol": native_exchange_symbol, "type": "Stop", "side": order_side,
               "orderQty": amount_per_trade, "price": None, "parameters": parameters})

await ccxt.bitmex.private_post_order_bulk({'orders': json.dumps(orders)})
```

Data in orders list.
`<class 'dict'>: {'symbol': 'ETHUSD', 'type': 'Stop', 'side': 'Sell', 'orderQty': 111.0, 'price': None, 'parameters': {'stopPx': 199, 'execInst': 'Close'}}`

**returns error -->{"error":{"message":"Invalid stopPx for ordType","name":"HTTPError"}}**

It seams that I am doing something wrong with parameters...

- OS: Linux
- Programming Language version: Python 3.6
- CCXT version: 1.18.824
- Exchange: Bitmex
- Method: private_post_order_bulk

**Comment by frosty00** [comment]
it seems to me that the issue is with `"price": None` - you are sending an undefined price is the parameters. for market orders you may want to avoid sending any price at all.

it is probably trying to validate the price as a number, which fails since the price you sent was `undefined`.

**Comment by qwasko1212** [comment]
I have removed price but it returns same error. 

I have tried to send bulk order for LimitIfTouched orders, but it returns same mistake as for simple Stop. However it works with single order placement. Maybe this information can help.

_Example of code for single placement LimitIfTouched order:_
```
parameters = {'stopPx': price, 'execInst': 'Close'}
ccxt.bitmex.create_order(symbol, 'LimitIfTouched', order_side, amount, price, parameters)
```
**It works well.**

_Example of code for bulk LimitIfTouched order:_
 ```
parameters = {'stopPx': price, 'execInst': 'Close'}
orders.append({"symbol": native_exchange_symbol, "type": "LimitIfTouched", "side": order_side,
                "orderQty": amount, "price": price, "parameters": parameters})
await self.ccxt.bitmex.private_post_order_bulk({'orders': json.dumps(orders)})
```
**returns error -->{"error":{"message":"Invalid stopPx for ordType","name":"HTTPError"}}**

_Example of data in orders list:_
`<class 'dict'>: {'symbol': 'ETHUSD', 'type': 'LimitIfTouched', 'side': 'Sell', 'orderQty': 22.0, 'price': 600.0, 'parameters': {'stopPx': 600.0, 'execInst': 'Close'}}`

**Comment by kroitor** [comment]
@qwasko1212 why do you send `parameters` to bitmex? Their endpoint for placing orders does not support a parameter called `parameters` inside an order. Each order should be a plain dict without nested dicts, and the `stopPx` should be on the same level with `price`.

order = {
    "symbol": native_exchange_symbol,
    "type": "LimitIfTouched",
    "side": order_side,
    "orderQty": amount,"price": price, "parameters": parameters}
}
orders.append()

**Comment by kroitor** [comment]
@qwasko1212 let us know if the above does not answer the question.

**Comment by brandsimon** [comment]
Also, bitmex doesnt support bulk market orders.
https://blog.bitmex.com/api_announcement/update-to-bulk-order-request-functionality/
