### ISSUE TITLE
Bibox fetch_balance returning 0 instead of balance

### ISSUE THREAD

**Issue by MrCelticFox** [ccxt/ccxt#5476]
- OS: Arch Linux
- Programming Language version: Python
- CCXT version: latest
- Exchange: bibox
- Method: fetch_balance

I went back to a project I started last year and wanted to check balances on my accounts, when I came to Bibox I noticed I was getting nothing, even though the other 3 were returning balances just fine. I logged on manually to check funds are still there (and they are) and reset API key too just in case, but still all I get are 0 balances back:

```{'info': {'total_btc': '0.00000000', 'total_cny': '0.00', 'total_usd': '0.00', 'assets_list': []}, 'free': {}, 'used': {}, 'total': {}}```

Is this a bug or is there a parameter I need to add in since the bibox API update?

**Comment by kroitor** [comment]
@MrCelticFox it has been switched from Main wallet to Trading wallet recently (for the purpose of unification with the other exchanges), so what you see is your trading balance, which might be zero when your main balance is above zero.

Related issue: https://github.com/ccxt/ccxt/pull/5325

Let us know if that doesn't answer the question.
