### ISSUE TITLE
i need 24hr volume data for a currency pair from an exchange which method should i use to get it 

### ISSUE THREAD

**Issue by nettemNvest** [ccxt/ccxt#5478]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by nettemNvest** [comment]
when i use fetchTicker its giving me 
   info: {
      symbol: 'BCPTUSDC',
      priceChange: '0.00000000',
      priceChangePercent: '0.000',
      weightedAvgPrice: '0.05348000',
      prevClosePrice: '0.05292000',
      lastPrice: '0.05348000',
      lastQty: '330.70000000',
      bidPrice: '0.05391000',
      bidQty: '59577.40000000',
      askPrice: '0.05798000',
      askQty: '939.90000000',
      openPrice: '0.05348000',
      highPrice: '0.05348000',
      lowPrice: '0.05348000',
      volume: '330.70000000',
      quoteVolume: '17.68583600',
      openTime: 1562484484867,
      closeTime: 1562570884867,
      firstId: 1029,
      lastId: 1029,
      count: 1
    }

the volume here is the 24hr volume ???

**Comment by frosty00** [comment]
Yes it is 24hr volume,

the `volume` is here is the _base_ volume, and the `quoteVolume` is the quote volume.

so the 24hr USDC  (quote) volume here is 17.6 USDC or approximately $17

use the unified fields to access volume of many exchanges

**Comment by kroitor** [comment]
> the volume here is the 24hr volume ???

No. You're looking at the `info` raw substructure of the ticker – it is there for development purposes. If you want to use the ticker info – you don't have to bury into `info`, you should look outside of `info`. The ticker structure is as follows:

```JavaScript
{
    'info': {
        // raw unparsed data, you're looking here
    }
    // the parsed data outside of `info` – you should be looking here ↓
    bid: ...,
    ask: ...,
    ...,
    baseVolume: ...,  // ←------------------------- YOUR WANT THIS
    quoteVolume: ...,
}
```

The ticker structure is described in the Manual here: https://github.com/ccxt/ccxt/wiki/Manual#ticker-structure

The difference between base and quote currencies is described here: 

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
- https://github.com/ccxt/ccxt/wiki/Manual#consistency-of-base-and-quote-currencies

Let us know if the above does not answer your question.
