### ISSUE TITLE
Exmo: feth_order not implemented. Possible solution

### ISSUE THREAD

**Issue by rubobaquero** [ccxt/ccxt#548]
When i try to fetch an order of Exmo, it says that it isn't implemented:

`PHP Fatal error:  Uncaught ccxt\NotSupported: exmo fetch_order() not implemented yet`

Is it possible to implement it using the function `order_trades ` from their Authenticated API?

Thanks in advance!

**Comment by kroitor** [comment]
@rubobaquero they have methods for fetching open orders, which is enough to emulate all other fetch\*order\* methods, so, the answer to your question is: yes, it is possible. We already did the same for Liqui, Poloniex and a few other exchanges by keeping the order cache in memory.
The fetchOrder for EXMO will be implemented, hopefully soon, your contributions and PRs are welcome, we will be happy and thankful for any help. This is the part of the work going on this issue https://github.com/ccxt/ccxt/issues/71.

See [liqui.php](https://github.com/ccxt/ccxt/blob/master/php/liqui.php) and [poloniex.php](https://github.com/ccxt/ccxt/blob/master/php/poloniex.php) implementations, the fetchOrder is emulated there via fetchOpenOrders + inmem cache without having a specific endpoint for that. 

Trades don't always fit that format, so we usually emulate missing order API endpoints with other available order endpoints.

I'm closing this for now as being a duplicate somewhat, we will add EXMO implementation asap, with your help, hopefully. Will update you on that. Feel free to reopen this or ask questions.

**Comment by kroitor** [comment]
Poloniex only has fetchOpenOrders, and other order API methods like fetchOrder, fetchOrders, fetchClosedOrders are emulated:

```PHP

public function fetch_orders ($symbol = null, $since = null, $limit = null, $params = array ()) {
    $this->load_markets();
    $market = null;
    if ($symbol)
        $market = $this->market ($symbol);
    $pair = $market ? $market['id'] : 'all';
    $response = $this->privatePostReturnOpenOrders (array_merge (array (
        'currencyPair' => $pair,
    )));
    $openOrders = array ();
    if ($market) {
        $openOrders = $this->parse_open_orders ($response, $market, $openOrders);
    } else {
        $marketIds = array_keys ($response);
        for ($i = 0; $i < count ($marketIds); $i++) {
            $marketId = $marketIds[$i];
            $orders = $response[$marketId];
            $m = $this->markets_by_id[$marketId];
            $openOrders = $this->parse_open_orders ($orders, $m, $openOrders);
        }
    }
    for ($j = 0; $j < count ($openOrders); $j++) {
        $this->orders[$openOrders[$j]['id']] = $openOrders[$j];
    }
    $openOrdersIndexedById = $this->index_by($openOrders, 'id');
    $cachedOrderIds = array_keys ($this->orders);
    $result = array ();
    for ($k = 0; $k < count ($cachedOrderIds); $k++) {
        $id = $cachedOrderIds[$k];
        if (array_key_exists ($id, $openOrdersIndexedById)) {
            $this->orders[$id] = array_merge ($this->orders[$id], $openOrdersIndexedById[$id]);
        } else {
            $order = $this->orders[$id];
            if ($order['status'] == 'open') {
                $this->orders[$id] = array_merge ($order, array (
                    'status' => 'closed',
                    'cost' => $order['amount'] * $order['price'],
                    'filled' => $order['amount'],
                    'remaining' => 0.0,
                ));
            }
        }
        $order = $this->orders[$id];
        if ($market) {
            if ($order['symbol'] == $symbol)
                $result[] = $order;
        } else {
            $result[] = $order;
        }
    }
    return $result;
}

public function fetch_order ($id, $symbol = null, $params = array ()) {
    $orders = $this->fetch_orders($symbol, $params);
    for ($i = 0; $i < count ($orders); $i++) {
        if ($orders[$i]['id'] == $id)
            return $orders[$i];
    }
    throw OrderNotCached ($this->id . ' order $id ' . (string) $id . ' not found in cache');
}

public function fetch_open_orders ($symbol = null, $since = null, $limit = null, $params = array ()) {
    $orders = $this->fetch_orders($symbol, $params);
    return $this->filter_orders_by_status ($orders, 'open');
}

public function fetch_closed_orders ($symbol = null, $since = null, $limit = null, $params = array ()) {
    $orders = $this->fetch_orders($symbol, $params);
    return $this->filter_orders_by_status ($orders, 'closed');
}
```

**Comment by rubobaquero** [comment]
Hi kroitor. After reading the CONTRIBUTING doc, i am not sure how i should proceed to contribute if i am a PHP developer, as the main language is Javascript. I understand that Javascript is the master language and it is transpilated to Python/PHP. How is it done in the slave -> master way? What syntax rules should i follow in PHP? Should I submit a PHP version and you translate it to Javascript or should I try to translate to Javascript even if i really not a good Javascript programmer? (I suppose that looking to the examples i will archieve it).

Thanks in advance!

**Comment by kroitor** [comment]
@rubobaquero hi! Yep, the CONTRIBUTING doc is a little outdated, we will update it asap.
My advice is to open poloniex.js and compare it to poloniex.php. You will immediately notice that there's very little difference in their code. They are mirroring each other line-to-line. So, answering your question, it would be easier to merge for me, if you did it in JS from the start, but if you have any difficulty with it, feel free to submit PHP code, I'll convert it to JS.
As for the coding style, you can copy that from other existing implementations, should be very straightforward. Let me know if you have any difficulties with it. And thanks a lot!
