### ISSUE TITLE
I need to develop an API where i need to get the volume of the pair ( BTC/USD ) form al the available exchanges

### ISSUE THREAD

**Issue by nettemNvest** [ccxt/ccxt#5480]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by nettemNvest** [comment]
exchange_volume : async (req,res,next)=>{

           // let pair =  `${base}/${quote}` ;
            let pair = 'BTC/USD'
            let existing_exchanges = ['kraken','bitmex'] ;
            async function getVolume(exchangeId, pair){
              
                let exchangeClass = ccxt[exchangeId]
                let exchange = new exchangeClass({ enableRateLimit: true })
                if( exchange.has['fetchTicker'] ){
                    console.log('fetching one by one')
                    try {
                        let ticker_data = await exchange.fetchTicker (pair)
                        console.log( ticker_data.symbol )
                        return {
                            Ticker : true ,
                            exchange : exchangeId ,
                            symbol : ticker_data.symbol ,
                            volume24h : ticker_data.baseVolume ,
                            volume24hTo : ticker_data.quoteVolume
                        }
                    } catch (error) {
                        console.log('error man.......')
                        throw error
                    }
                }else{
                    return {
                        Ticker : false
                    }
                }

            }

            Promise.all( existing_exchanges.map(async exchangeId=>{
                console.log( exchangeId )
                return await getVolume(exchangeId, pair)
            })).then(final_result=>{
                console.log( final_result ) ;
                res.json({
                    success : true ,
                    Data : final_result
                })
            }).catch(error=>{
                console.log( 'error came man..' )
                res.json({
                    success : false ,
                    message : toString( error.message )
                })
            })

        }

**Comment by kroitor** [comment]
@nettemNvest please, see this example: https://github.com/ccxt/ccxt/blob/master/examples/js/exchanges-by-volume.js

Let us know if that does not answer the question.

Duplicate: https://github.com/ccxt/ccxt/issues/5462

**Comment by nettemNvest** [comment]
i did sir....when they get the result they are logging the result and resolving  but what if we get the error they are not rejecting.... they are jsut loging the error ....
I am developing an API sir.....not just the code for logging

**Comment by kroitor** [comment]
```JavaScript
"use strict";

const ccxt = require ('../../ccxt.js')

;(async () => {

    //     const exchanges = [
    //         'bittrex',
    //         'poloniex',
    //         'bitfinex'
    //     ]

    const exchanges = ccxt.exchanges

    const symbol = 'BTC/USDT'
    const tickers = {}
    const volumeField = 'baseVolume'

    console.log ('-----------------------------------------------------------')

    await Promise.all (exchanges.map (exchangeId =>

        new Promise (async (resolve, reject) => {

            try {

                const exchange = new ccxt[exchangeId] ({ enableRateLimit: true })

                const ticker = await exchange.fetchTicker (symbol)

                if (ticker[volumeField] !== undefined) {
                    tickers[exchangeId] = ticker
                }

            } catch (e) {

                // console.log (exchangeId, e.message.slice (0, 100))

                reject () // ←------- ADD THIS HERE IF YOU WANT IT TO REJECT
            }

            resolve ()

        })

    ))

   // DO YOUR NOTLOGGING HERE ↓ INSTEAD OF console.log

    console.log (Object
        .keys (tickers)
        .sort ((a, b) =>
            ((tickers[a][volumeField] > tickers[b][volumeField]) ? 1 : ((tickers[a][volumeField] < tickers[b][volumeField]) ? -1 : 0)))
        .reverse ()
        .map (id => ({
            id,
            symbol,
            'volume': tickers[id][volumeField],
        }))
    )

}) ()

**Comment by nettemNvest** [comment]
npm install web3 ethereumjs-util ethereumjs-abi bignumber.js --no-save
 sometimes iam geting this error

**Comment by kroitor** [comment]
> npm install web3 ethereumjs-util ethereumjs-abi bignumber.js --no-save

That's not the only info in that error, it says:

```
throw new ExchangeError ("Required dependencies missing: \nnpm i web3 ethereumjs-util ethereumjs-abi bignumber.js --no-save");
```

You're instantiating `theocean` exchange (by instantiating all exchanges from CCXT). However, `theocean` is a DEX and it requires web3 code to run. If you don't want to have that exception, then:

1. either don't instantiate `theocean` if you're not using it
2. or add those dependencies if you want to fetch info from `theocean`

**Comment by nettemNvest** [comment]
const ccxt = require('ccxt');


(async () => {

    //     const exchanges = [
    //         'bittrex',
    //         'poloniex',
    //         'bitfinex'
    //     ]

    const exchanges = ccxt.exchanges

    const symbol = 'BTC/USDT'
    const tickers = {}
    const volumeField = 'baseVolume'

    console.log ('-----------------------------------------------------------')

    await Promise.all (exchanges.map (exchangeId =>

        new Promise (async (resolve, reject) => {

            try {

                const exchange = new ccxt[exchangeId] ({ enableRateLimit: true })

                const ticker = await exchange.fetchTicker (symbol)

                if (ticker[volumeField] !== undefined) {
                    tickers[exchangeId] = ticker
                }

            } catch (e) {

                // console.log (exchangeId, e.message.slice (0, 100))

                // THIS WILL BREAK THE ENTIRE SCRIPT, IF ONE EXCHANGE FAILS:
                reject () // ←------- ADD THIS HERE IF YOU WANT IT TO REJECT
            }

            resolve ()

        })

    ))

   // DO YOUR NOTLOGGING HERE ↓ INSTEAD OF console.log

    console.log (Object
        .keys (tickers)
        .sort ((a, b) =>
            ((tickers[a][volumeField] > tickers[b][volumeField]) ? 1 : ((tickers[a][volumeField] < tickers[b][volumeField]) ? -1 : 0)))
        .reverse ()
        .map (id => ({
            id,
            symbol,
            'volume': tickers[id][volumeField],
        }))
    )

}) ()


i jsut copied the same code whcih u gave me iam geting unhandled promise rejection

**Comment by nettemNvest** [comment]
(node:19761) UnhandledPromiseRejectionWarning: undefined
(node:19761) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)

**Comment by kroitor** [comment]
@nettemNvest of course, because you wanted it to reject, right? And if it rejects, then you have to catch it, in other words, that example posted above says:

```
// DO YOUR NOTLOGGING HERE ↓ INSTEAD OF console.log
```

↑ That line means you have to edit everything below that line. Otherwise it will reject → and you're not catching the rejection → you will get an unhandled rejected promise on your side.

**Comment by kroitor** [comment]
@nettemNvest 

```JavaScript
"use strict";

const ccxt = require ('../../ccxt.js')

;(async () => {

    //     const exchanges = [
    //         'bittrex',
    //         'poloniex',
    //         'bitfinex'
    //     ]

    const exchanges = ccxt.exchanges

    const symbol = 'BTC/USDT'
    const tickers = {}
    const volumeField = 'baseVolume'

    console.log ('-----------------------------------------------------------')

    try {
        await Promise.all (exchanges.map (exchangeId =>

            new Promise (async (resolve, reject) => {

                try {

                    const exchange = new ccxt[exchangeId] ({ enableRateLimit: true })

                    const ticker = await exchange.fetchTicker (symbol)

                    if (ticker[volumeField] !== undefined) {
                        tickers[exchangeId] = ticker
                    }

                } catch (e) {

                    // console.log (exchangeId, e.message.slice (0, 100))

                    // THIS WILL BREAK THE ENTIRE SCRIPT, IF ONE EXCHANGE FAILS:
                    reject () // ←------- ADD THIS HERE IF YOU WANT IT TO REJECT
                }

                resolve ()

            })

        ))
    
    } catch (e) {

        // HANDLE THE REJECTED EXCEPTION HERE
    }

    // OR HANDLE THE RESULTS HERE

}) ()
```
