### ISSUE TITLE
geting quote volume as undefined in bitfinex

### ISSUE THREAD

**Issue by nettemNvest** [ccxt/ccxt#5485]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by nettemNvest** [comment]
{
  symbol: 'BTC/USD',
  timestamp: 1562656257886.8206,
  datetime: '2019-07-09T07:10:57.886Z',
  high: 12814.64784556,
  low: 11435,
  bid: 12645,
  bidVolume: undefined,
  ask: 12649,
  askVolume: undefined,
  vwap: undefined,
  open: undefined,
  close: 12645,
  last: 12645,
  previousClose: undefined,
  change: undefined,
  percentage: undefined,
  average: 12647,
  baseVolume: 22227.17077089514,
  quoteVolume: undefined,
  info: {
    mid: '12647.0',
    bid: '12645.0',
    ask: '12649.0',
    last_price: '12645.0',
    low: '11435.0',
    high: '12814.64784556',
    volume: '22227.170770895138986',
    timestamp: '1562656257.8868206'
  }
}

aim geting quote volume as undedfined in in bitfinex

**Comment by kroitor** [comment]
> aim geting quote volume as undedfined in in bitfinex

That's right – we don't invent it, if the underlying exchanges does not provide it. If you look into the `info` structure which contains the raw unparsed response from the exchange – you will notice that there is no value for quote volume there.
