### ISSUE TITLE
Exception class not found

### ISSUE THREAD

**Issue by jackyxie** [ccxt/ccxt#5487]
- OS: Linux
- Programming Language version: PHP
- CCXT version: 1.18.916
- Exchange: All Exchange
- Method: Exception Class not found

class AuthenticationError not found in file ccxt/php/Exchange.php on line 1314

**Comment by kroitor** [comment]
@jackyxie can you please paste a bit more info about it? Or your code to reproduce it? Also, need to know your version of PHP.

**Comment by jackyxie** [comment]
@kroitor my PHP version 7.2.1. and below is a snapshot of my code.

![code](https://user-images.githubusercontent.com/3347704/60882852-4f805b80-a27b-11e9-9639-c548761f2d85.png)

**Comment by kroitor** [comment]
@jackyxie can you make a minimal but a complete snippet in PHP with the bug? 10-20 lines so that I could copy it and test it on my side? Unfortunately, the screenshot above does not really help determine the cause of it.

**Comment by jackyxie** [comment]
@kroitor here is the complete snippet.

`php
<?php

require_once __DIR__ .'/vendor/autoload.php';

$url = 'https://www.mxc.com/open/api/v1/private/order';
$method = 'POST';
$headers = array (
    'Content-Type' => 'application/json',
);

$options = [
    'enableRateLimit' => false,
    'timeout' => '10000',
    'curl_options' => [
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_SSL_VERIFYHOST => false,
    ],
];

//debug
$apikey = 'aaaaaa';
$seckey = 'bbbbbccc';

$params = [
    'api_key' => $apikey,
    'market' => 'XLM_USDT',
    'price' => 0.05187,
    'quantity' => 100,
    'req_time' => time(),
    'trade_type' => 1, //1:买,2:卖
];
$body = http_build_query($params);
parse_str($body, $body_arr);

ksort($body_arr);
$query_str = http_build_query($body_arr);
$auth_str = $query_str .'&api_secret='. $seckey;
$sign = strtoupper(hash('md5', $auth_str, false));
$body .= '&sign='. $sign;

$market_class = new \ccxt\Exchange($options);
try {
    $result = $market_class->fetch($url, $method, $headers, $body);
}catch (\ccxt\ExchangeNotAvailable $e) {
}catch (\ccxt\ExchangeError $e) {
}catch (\ccxt\DDoSProtection $e) {
}catch (\ccxt\RequestTimeout $e) {
}
`

**Comment by kroitor** [comment]
@jackyxie thx! Fixed it, should be ok as of 1.18.917. Let us know if that does not help.
