### ISSUE TITLE
Get a full name of coin

### ISSUE THREAD

**Issue by Mitrovic** [ccxt/ccxt#549]
Hi,
Can we get a full name for the coin ?
For example  coin with base XMR on exchange server have name Monero, but I can't get that name.

**Comment by kroitor** [comment]
Hi, @Mitrovic !

Currently we don't unify coin names (it's on our roadmap, however).
But you should still be able to obtain the coin name where available, from the `info` field of the market in question.

```
bittrex.loadMarkets ()
bittrex.markets['BTC/USD']['info']['MarketCurrencyLong']
bittrex.markets['BTC/USD']['info']['BaseCurrencyLong']
...
```

That is, until we unify their names in the library (it is under active development, as you may know).
Does this answer your question?

**Comment by Mitrovic** [comment]
Hi,
I checked, but only bittrex has a name.
Is there a way to get other names?
Maybe a list of all the coins  where I can take the names according to the symbol.

Thank's

**Comment by kroitor** [comment]
@Mitrovic , hi!

The CoinMarketCap may be of some help for more or less unified crypto names:

```
const markets = await coinmarketcap.loadMarkets ()
```

But you will still have to code for a few fiats: 

```
'currencies': [
                'AUD',
                'BRL',
                'CAD',
                'CHF',
                'CNY',
                'EUR',
                'GBP',
                'HKD',
                'IDR',
                'INR',
                'JPY',
                'KRW',
                'MXN',
                'RUB',
                'USD',
            ],
```

We are going to unify human-readable coin names inside ccxt as well (it's on our roadmap).

**Comment by kroitor** [comment]
@Mitrovic for fiat currencies, see ISO4217 standard 3-letter codes: http://www.xe.com/iso4217.php

**Comment by kroitor** [comment]
@Mitrovic I am closing this for now until we implement currency names in ccxt (hopefully, soon). Feel free to ask questions if you have them. Thx!

**Comment by bradbesserman** [comment]
Any progress on this feature?

**Comment by kroitor** [comment]
@bradbesserman yeah, we now have `.currencies` indexed by code having the following structure:

<img width="1352" alt="screen shot 2018-07-14 at 23 04 15" src="https://user-images.githubusercontent.com/1294454/42728050-4442a674-87ba-11e8-8db2-e5e5824160cf.png">

```
mbp:ccxt igorkroitor$ node examples/js/cli bittrex currencies --load-markets
{       BTC: {        id:   "BTC",
                    code:   "BTC",
                 address:   "1N52wHoVR79PMDishab2XmRHsbekCdGquK",
                    info: {        Currency: "BTC",
                               CurrencyLong: "Bitcoin",
                            MinConfirmation:  2,
                                      TxFee:  0.0005,
                                   IsActive:  true,
                                   CoinType: "BITCOIN",
                                BaseAddress: "1N52wHoVR79PMDishab2XmRHsbekCdGquK",
                                     Notice:  null                                 },
                    type:   "BITCOIN",
                    name:   "Bitcoin",
                  active:    true,
                     fee:    0.0005,
               precision:    8,
                  limits: {   amount: { min: 1e-8, max: 100000000 },
                               price: { min: 1e-8, max: 100000000 },
                                cost: { min: undefined, max: undefined },
                            withdraw: { min: 0.0005, max: 100000000 }     }           },
        LTC: {        id:   "LTC",
                    code:   "LTC",
                 address:   "LhyLNfBkoKshT7R8Pce6vkB9T2cP2o84hx",
                    info: {        Currency: "LTC",
                               CurrencyLong: "Litecoin",
                            MinConfirmation:  6,
                                      TxFee:  0.01,
                                   IsActive:  true,
                                   CoinType: "BITCOIN",
                                BaseAddress: "LhyLNfBkoKshT7R8Pce6vkB9T2cP2o84hx",
                                     Notice:  null                                 },
                    type:   "BITCOIN",
                    name:   "Litecoin",
                  active:    true,
                     fee:    0.01,
               precision:    8,
                  limits: {   amount: { min: 1e-8, max: 100000000 },
                               price: { min: 1e-8, max: 100000000 },
                                cost: { min: undefined, max: undefined },
                            withdraw: { min: 0.01, max: 100000000 }       }           },
       DOGE: {        id:   "DOGE",
                    code:   "DOGE",
                 address:   "D9GqmkGCpgtnXP7xMD78v9xfqeDkqBZBMT",
                    info: {        Currency: "DOGE",
                               CurrencyLong: "Dogecoin",
                            MinConfirmation:  6,
                                      TxFee:  2,
                                   IsActive:  true,
                                   CoinType: "BITCOIN",
                                BaseAddress: "D9GqmkGCpgtnXP7xMD78v9xfqeDkqBZBMT",
                                     Notice:  null                                 },
                    type:   "BITCOIN",
                    name:   "Dogecoin",
                  active:    true,
                     fee:    2,
               precision:    8,
                  limits: {   amount: { min: 1e-8, max: 100000000 },
                               price: { min: 1e-8, max: 100000000 },
                                cost: { min: undefined, max: undefined },
                            withdraw: { min: 2, max: 100000000 }          }           },
...
```

**Comment by bradbesserman** [comment]
thanks!

**Comment by fccoelho** [comment]
> @bradbesserman yeah, we now have `.currencies` indexed by code having the following structure (that includes a `name` field if available from the exchange API):
> 
> <img alt="screen shot 2018-07-14 at 23 04 15" width="1352" src="https://user-images.githubusercontent.com/1294454/42728050-4442a674-87ba-11e8-8db2-e5e5824160cf.png">
> 
> ```
> mbp:ccxt igorkroitor$ node examples/js/cli bittrex currencies --load-markets
> {       BTC: {        id:   "BTC",
>                     code:   "BTC",
>                  address:   "1N52wHoVR79PMDishab2XmRHsbekCdGquK",
>                     info: {        Currency: "BTC",
>                                CurrencyLong: "Bitcoin",
>                             MinConfirmation:  2,
>                                       TxFee:  0.0005,
>                                    IsActive:  true,
>                                    CoinType: "BITCOIN",
>                                 BaseAddress: "1N52wHoVR79PMDishab2XmRHsbekCdGquK",
>                                      Notice:  null                                 },
>                     type:   "BITCOIN",
>                     name:   "Bitcoin",
>                   active:    true,
>                      fee:    0.0005,
>                precision:    8,
>                   limits: {   amount: { min: 1e-8, max: 100000000 },
>                                price: { min: 1e-8, max: 100000000 },
>                                 cost: { min: undefined, max: undefined },
>                             withdraw: { min: 0.0005, max: 100000000 }     }           },
>         LTC: {        id:   "LTC",
>                     code:   "LTC",
>                  address:   "LhyLNfBkoKshT7R8Pce6vkB9T2cP2o84hx",
>                     info: {        Currency: "LTC",
>                                CurrencyLong: "Litecoin",
>                             MinConfirmation:  6,
>                                       TxFee:  0.01,
>                                    IsActive:  true,
>                                    CoinType: "BITCOIN",
>                                 BaseAddress: "LhyLNfBkoKshT7R8Pce6vkB9T2cP2o84hx",
>                                      Notice:  null                                 },
>                     type:   "BITCOIN",
>                     name:   "Litecoin",
>                   active:    true,
>                      fee:    0.01,
>                precision:    8,
>                   limits: {   amount: { min: 1e-8, max: 100000000 },
>                                price: { min: 1e-8, max: 100000000 },
>                                 cost: { min: undefined, max: undefined },
>                             withdraw: { min: 0.01, max: 100000000 }       }           },
>        DOGE: {        id:   "DOGE",
>                     code:   "DOGE",
>                  address:   "D9GqmkGCpgtnXP7xMD78v9xfqeDkqBZBMT",
>                     info: {        Currency: "DOGE",
>                                CurrencyLong: "Dogecoin",
>                             MinConfirmation:  6,
>                                       TxFee:  2,
>                                    IsActive:  true,
>                                    CoinType: "BITCOIN",
>                                 BaseAddress: "D9GqmkGCpgtnXP7xMD78v9xfqeDkqBZBMT",
>                                      Notice:  null                                 },
>                     type:   "BITCOIN",
>                     name:   "Dogecoin",
>                   active:    true,
>                      fee:    2,
>                precision:    8,
>                   limits: {   amount: { min: 1e-8, max: 100000000 },
>                                price: { min: 1e-8, max: 100000000 },
>                                 cost: { min: undefined, max: undefined },
>                             withdraw: { min: 2, max: 100000000 }          }           },
> ...
> ```

Checked on latest version as of today. and currencies only returns this:
```python
bf.currencies['BTC']
Out[19]: {'id': 'fBTC', 'numericId': None, 'code': 'BTC', 'precision': 5}
```
bf is the exchange instance.

**Comment by kroitor** [comment]
> bf is the exchange instance.

Which exchange?

**Comment by fccoelho** [comment]
yes, `bitfinex2`

**Comment by fccoelho** [comment]
> > bf is the exchange instance.
> 
> @fccoelho Which exchange? Bitfinex? They don't have an endpoint with currencies info, so in some cases the currencies are derived from whatever market info is available (from trading symbols, basically).

Ah... ok. thanks I'll try to pull from some other exchange, then.

**Comment by weerdenburg** [comment]
Is there already some sort of alternative to retrieve unified coin names?
In above example, there was told to use the coinmarketcap exchange, but since V1 is offline, what could be used as alternative?  
#6580

Will coinpaprika or another general API be integrated into ccxt?

**Comment by kroitor** [comment]
@weerdenburg 

> what could be used as alternative?

check this example https://github.com/ccxt/ccxt/tree/master/examples/js/search-all-exchanges.js – you can derive some unified crypto names from there

> Will coinpaprika or another general API be integrated into ccxt?

We will probably integrate coingecko, will look into coinpaprika as well.

**Comment by weerdenburg** [comment]
Thanks for the example, that could be a helpful work-around for now.

Is there any idea when the implementation of coingecko / coinpaprika will be ready?
And how can I know (get an update) when it's implemented?

**Comment by kroitor** [comment]
@weerdenburg 

> Is there any idea when the implementation of coingecko / coinpaprika will be ready?

We can't tell you the ETA yet, but we will do it as soon as we can.

> And how can I know (get an update) when it's implemented?

You can click the "watch" button on any of these three issues, and you will get notified when it's merged:

- https://github.com/ccxt/ccxt/pull/6610
- https://github.com/ccxt/ccxt/pull/3565
- https://github.com/ccxt/ccxt/issues/3543

**Comment by jefferson-fidencio** [comment]
Hi guys! Trying to get currencies name from Binance but it seems like nothing returns from .currencies or fetch_currencies.. can u help me with that?
