### ISSUE TITLE
fetch_closed_orders since startTime

### ISSUE THREAD

**Issue by selfrefresh** [ccxt/ccxt#5496]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Linux
- Programming Language version: php
- CCXT version: 1.18.915
- Exchange: binance
- Method: fetch_closed_orders

https://api.binance.com/api/v3/allOrders?timestamp=1562832524123&recvWindow=5000&symbol=BNBUSDT&startTime=1562828924000&limit=1&signature=xxxx GET 28 Operation timed out after 5000 milliseconds with 0 bytes received

When startTime is entered in seconds, no problem，
When startTime is entered in milliseconds, the above problem appears

**Comment by selfrefresh** [comment]
@kroitor

**Comment by selfrefresh** [comment]
The same goes for python

**Comment by frosty00** [comment]
It is working for me in js/py, what version of ccxt are you using?

> Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of ccxt.version to https://github.com/ccxt/ccxt/blob/master/package.json#L3
