### ISSUE TITLE
how to get list of all exchanges which provides fetchOrberBook data

### ISSUE THREAD

**Issue by nettemsarath** [ccxt/ccxt#5498]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by nettemsarath** [comment]
let existing_exchanges = ccxt.exchanges ;

  let orderBook_list = existing_exchanges.filter( async(exchangeid)=>{
           
             let id = exchangeid ;
             const exchange =await new ccxt[id] ({ enableRateLimit: true })
             if( exchange.has['fetchOrderBook'] ){
                  return exchangeid
             }   
          })
          console.log( existing_exchanges ) 


iam geting error install web3 etherium bignumber.js

**Comment by kroitor** [comment]
@nettemsarath you don't have to await for the constructor – that's technically a mistake.
Also, see this answer: https://github.com/ccxt/ccxt/issues/5480#issuecomment-509198840

1. in your project folder: `npm i web3 ethereumjs-util ethereumjs-abi bignumber.js --no-save`
2. change your code:

```JavaScript
let orderBook_list = ccxt.exchanges.filter (exchangeid => {       
    const exchange = new ccxt[exchangeid] ({ enableRateLimit: true })
    return exchange.has['fetchOrderBook']
})
```

Or, alternatively, if you don't want `theocean` with web3 deps, then do this:

1. change your code:

```JavaScript
let orderBook_list = ccxt.exchanges.filter (exchangeid => {
    if (exchangeId === 'theocean') {
        return false
    }
    const exchange = new ccxt[exchangeid] ({ enableRateLimit: true })
    return exchange.has['fetchOrderBook']
})
```

Let us know if the above does not answer the question.

**Comment by nettemsarath** [comment]
well thank you sir...
