### ISSUE TITLE
GDAX ExchangeError instead of ExchangeNotAvailable?

### ISSUE THREAD

**Issue by davidpodrebarac** [ccxt/ccxt#550]
Hi again,
when executing given code below:
```
import asyncio
loop = asyncio.get_event_loop()
import ccxt.async as ccxt
gdax = ccxt.gdax({
    "apiKey": <<my_api>>,
    "password": <<my_pw>>,
    "secret": <<my_secret>>,
})
loop.run_until_complete(gdax.create_limit_buy_order('LTC/BTC', 0.1, 0.00000000000010101020212101202102102))
```
I get: 
`ExchangeNotAvailable: gdax POST https://api.gdax.com/orders 400 {"message":"price too small (0.00000000000010101020212101202)"}`

Following ccxt's wiki page on error hangling, shouldn't this be treated as ExchangeError instead of ExchangeNotAvailable?

**Comment by kroitor** [comment]
Hi! Thanks for your feedback, it should be ExchangeError, of course, will fix for that very soon!

**Comment by davidpodrebarac** [comment]
While you are at it, could you also change this from bitfinex?
`ExchangeNotAvailable: bitfinex POST https://api.bitfinex.com/v1/order/new 400 {"message":"Invalid order: minimum size for LTC/BTC is 0.2"}`

**Comment by kroitor** [comment]
Sure, will upload the fixes shortly!

**Comment by kroitor** [comment]
This is fixed in 1.10.81+. We will be happy if you report back whether it works as expected for you or not. Thx again!

**Comment by davidpodrebarac** [comment]
None of these work. Could you try it yourself if you have an account on Bitfinex/GDAX?

**Comment by kroitor** [comment]
@davidpodrebarac ok, now this should be fixed completely. Tested it on our side as well, both of them should work. Thx again!

**Comment by davidpodrebarac** [comment]
These are fixed and work great!
Sorry If I am bothering you with this, but I have a few more that are not parsed correctly. I will just put them here:
* hitbtc2 -> Insufficient funds
```
ccxt.base.errors.ExchangeNotAvailable: hitbtc2 POST https://api.hitbtc.com/api/2/order?clientOrderId=1510655090650&symbol=BCHBTC&side=sell&quantity=2.601&type=limit&price=0.2016102000 400 {"error":{"code":20001,"message":"Insufficient funds","description":"Check that the funds are sufficient, given commissions"}}
```
* poloniex -> min size error as InvalidOrder
```
 ccxt.base.errors.ExchangeNotAvailable: poloniex POST https://poloniex.com/tradingApi 422 {"error":"Total must be at least 0.0001."}
```
I know these are very "boring" bugs, but they should be fixed eventually. Maybe we can put ExchangeError as default instead of ExchangeNotAvailable?
