### ISSUE TITLE
New Exchange - Eterbase

### ISSUE THREAD

**Issue by turbojenks** [ccxt/ccxt#5501]
Hi is there any scope to getting this one on the list?

Eterbase is a European exchange that offers 100% negative trading fees for maker orders.

API reference= https://developers.eterbase.exchange/

- Programming Language version: Python
- CCXT version: 1.18.923
- Exchange: Eterbase
- Method: Rest    API/Sockets

**Comment by icom333** [comment]
This will be a great add, one of the most promising exchanges out there

**Comment by tamara4489** [comment]
Really great project

**Comment by j-codex-ops** [comment]
Eterbase is a top class exchange, will definitely be dominating the space soon. Will be an awesome addition

**Comment by asebaby** [comment]
Eterbase is one top exchange coming up,stay tuned.

**Comment by cod3gen** [comment]
lol

**Comment by turbojenks** [comment]
Hi there,

Jagged Soft has released an API on node JS if this helps at all?

https://github.com/jaggedsoft/eterbase-api

**Comment by kroitor** [comment]
Eterbase has been added and certified in CCXT as of version 1.27.80+

- https://twitter.com/AuxtRobert/status/1261382257794846720
- https://twitter.com/ETERBASE/status/1261379477793202176
- https://medium.com/@ETERBASE/eterbase-exchange-is-now-supported-and-certified-in-ccxt-520cfcbd2356
