### ISSUE TITLE
[coinfloor] cancel order doesn't work

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5508]
See: https://github.com/coinfloor/API/blob/master/BIST.md#cancel-order

The url generated is something like: `https://webapi.coinfloor.co.uk/bist/233123443/cancel_order/ `, where it should be `https://webapi.coinfloor.co.uk/bist/XBT/GBP/cancel_order/`.  And the body should contain the order id.

**Comment by frosty00** [comment]
yep, most of coinfloor is broken (including fetchBalance). We are working on fixing this...
