### ISSUE TITLE
Transpiling leaves removed exchanges in php/python pile

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#5512]
- OS: not relevant
- Programming Language version: n/a
- CCXT version: 1.18.939
- Exchange: huobi*

Unless i misunderstand how ccxt transpiling works, i think it leaves deleted / renamed files behind.

for JS (the transpiling source) - there are 2 files for Huobi, `huobipro.js` and `huobiru.js`.

![2019-07-14-140201_1214x147_scrot](https://user-images.githubusercontent.com/5024695/61183297-fda35100-a63f-11e9-9815-8a2415a3ceae.png)

For Python (and php) on the other hand, there are 4, with 2 not beeing updated since at least 10 months.

![2019-07-14-135936_1061x134_scrot](https://user-images.githubusercontent.com/5024695/61183305-14e23e80-a640-11e9-87fc-ffbc4b053210.png)

I don't think this is intentional for backwards compatibility (then they would remain for js as well).

This may impact other exchanges too - but i honestly did not check for that.

**Comment by kroitor** [comment]
@xmatthias yep, looks like you're right, there are some stale files, we don't have a delete rule in the building sequence, so we `git rm` those files manually for now and we've missed a couple apparently. However, we are going to automate that as well.
