### ISSUE TITLE
YoBit fetchTickers() & fetchOrderBooks() returning "empty pair list"

### ISSUE THREAD

**Issue by WoK-E** [ccxt/ccxt#5519]
- CCXT version: 1.18.941
- Exchange: YoBit
- Method: fetchOrderBooks

YoBit accepts multiple pairs when accessing the depth endpoint, but the number of pairs accepted seems undefined. When calling fetchOrderBooks with up to 40 pairs, YoBit returns the orderbook with no problems. If requesting the orderbook for more than 40 pairs, the return is {"success":0,"error":"Empty pair list"} -- I've had success responses with up to 48 pairs, but 40 seems to be a safe number.
The URL length plays no role, i.e. the error fires up with a URL length far below the max URL length.

This is probably a YoBit issue, nit a ccxt one

**Comment by Djusk8** [comment]
I have the same problem with the fetch_tickers() method.
I'm using custom MyYoBit class and it should work for fetchOrderBooks() too.

Maybe it can be implemented in ccxt library to improve unification.

```
from ccxt import yobit

class MyYoBit(yobit):

    def __init__(self):
        yobit.__init__(self)

    def fetch_tickers(self, pairs):
        tickers = dict()
        print("Fetching tickers ", end="")
        for i in range(0, int(math.ceil(len(pairs) / 40))):
            pairs = pairs[i * 40:(i + 1) * 40]
            tickers.update(super().fetch_tickers(pairs))
            print(".", end="")  # Yobit has a lot of pairs, so I use it to check it's working
            # time.sleep(1)  # Use it to avoid DDOS ban from YoBit
        print(" Done")
        return tickers

exchange = MyYoBit()
all_tickers = exchange.fetch_tickers(any_number_of_pairs)

```

**Comment by ttodua** [comment]
Exchange is no longer a part of CCXT. Closing the issue for now.

**Comment by ttodua** [comment]
sorry, i had a mistake. yobit is still there, re-opening the topic
