### ISSUE TITLE
Gemini web scraping transpilation issue in PHP

### ISSUE THREAD

**Issue by Blobbus** [ccxt/ccxt#5524]
- OS: Windows
- Programming Language version: PHP 7
- CCXT version: 1.18.941
- Exchange: Gemini
- Method: fetchBalance, fetchMarkets (possibly others as well)

Several methods 
When fetching balance from Gemini with valid API keys,
Running this code, using known good API keys that work fine elsewhere:

```
$ex = new \ccxt\gemini([
    'apiKey' => $apiKey,
    'secret' => $secret,
]);
$ex->fetchBalance();
```

It throws an ExchangeNotAvailable exception as follows:

```
Fatal error:  Uncaught ccxt\ExchangeNotAvailable: https://docs.gemini.com/rest-api GET 200 not accessible from this location at the moment (possible reasons: exchange is down or offline, on maintenance, DDoS protection, rate-limiting in effect) in C:\Bitnami\wampstack-7.3.2-0\apache2\htdocs\balances\vendor\ccxt\ccxt\php\Exchange.php:1334
Stack trace:
#0 C:\Bitnami\wampstack-7.3.2-0\apache2\htdocs\balances\vendor\ccxt\ccxt\php\Exchange.php(1087): ccxt\Exchange->fetch('https://docs.ge...', 'GET', Array, NULL)
#1 C:\Bitnami\wampstack-7.3.2-0\apache2\htdocs\balances\vendor\ccxt\ccxt\php\Exchange.php(1091): ccxt\Exchange->fetch2('rest-api', 'web', 'GET', Array, NULL, NULL)
#2 [internal function]: ccxt\Exchange->request('rest-api', 'web', 'GET', Array)
#3 C:\Bitnami\wampstack-7.3.2-0\apache2\htdocs\balances\vendor\ccxt\ccxt\php\Exchange.php(2270): call_user_func_array(Array, Array)
#4 C:\Bitnami\wampstack-7.3.2-0\apache2\htdocs\balances\vendor\ccxt\ccxt\php\gemini.php(154): ccxt\Exchange->__call('webGetRestApi', Array)
#5 C:\Bit in C:\Bitnami\wampstack-7.3.2-0\apache2\htdocs\balances\vendor\ccxt\ccxt\php\Exchange.php on line 1334
```

From digging into the code, it appears that the code is attempting to web-scrape the data out of the table at this link:

https://docs.gemini.com/rest-api/#symbols-and-minimums

Looking at where the error is generated from, in the main Exchange.php file's Exchange class's fetch() method, and doing a little debugging, it looks like it's fetching the page's contents just fine, identifying that it's not JSON, and then applying this particular check to it, which is part of the mechanism it uses to throw the exception:

```
if (preg_match('#offline|busy|retry|wait|unavailable|maintain|maintenance|maintenancing#i', $result)) {
	$error_class = 'ExchangeNotAvailable';
}
```

Based on the context, it appears that the code is designed to look for when the API/Website is down and report that in the form of an exception. What appears to be actually happening, however, is that since the webpage that it's scraping the data from is a document about how the API works, it is finding the words "maintain" and "maintenance" in the documentation and effectively triggering a false-positive for the exchange being down. The words that trigger it can be found roughly in the following parts of the document:

https://docs.gemini.com/rest-api/#use-websocket-apis
https://docs.gemini.com/rest-api/#http-error-codes
https://docs.gemini.com/rest-api/#error-payload

Because the fetch() method is typically expecting a JSON payload, that check is a reasonable precaution in that circumstance. Unfortunately, when web scraping data, it can lead to false-positives triggering the exception.

To resolve this, the simplest way to I can think of to handle it would be to add a method to disable this check in certain instances of web scraping, though I definitely recommend something with a bit more thought put into it than my naive recommendation.

**Comment by Blobbus** [comment]
Hoping to come up with a temporary hack to get around the problem, while waiting for a proper solution to be pushed to the repository in the meantime, I implemented a rather simple hack:

```
if (preg_match('#offline|busy|retry|wait|unavailable|maintain|maintenance|maintenancing#i', $result)) {
	if ($url !== 'https://docs.gemini.com/rest-api') {
		$error_class = 'ExchangeNotAvailable';
	}
}
```

It's dirty and doesn't truly solve the underlying problem, but it will work well enough in the meantime and shouldn't break anything else, and will allow me to move on while I wait for a proper solution to come along.

Unfortunately, I found another issue tangentally related to this one that prevents it from working properly as well. The web scraping parser for Gemini appears to be a little broken, likely from a "search and replace all" gone wrong. In the gemini.php file's gemini class's fetch_markets_from_web() method, it's doing this:

`$sections = explode('<h1 $id="$symbols-and-minimums">Symbols and minimums</h1>', $response);`

It appears it should probably be changed to this:

`$sections = explode('<h1 id="symbols-and-minimums">Symbols and minimums</h1>', $response);`

Additionally, after I fixed that locally, this caused a problem as well:

`$rows = explode("{tr}\n", $tables[1]); // eslint-disable-line quotes`

It appears it should probably be changed to this:

`$rows = explode("<tr>\n", $tables[1]); // eslint-disable-line quotes`

Fixing those two issues seems to have corrected its behavior, and it appears to be working correctly now. While it doesn't truly solve the original bug, it does show that implementing a proper non-hackish solution to fix the original bug, as well as making these two corrections to fix this secondary bug, should get it working properly again.

**Comment by Blobbus** [comment]
Spoke too soon. After testing fetchBalance, I moved on to testing fetchMarkets and noticed that the data had other problems, and there was more to that second bug that I missed on my first pass:

```
$id = str_replace('{td}', '', $cells[0]);
$id = str_replace('<code class="prettyprint">', '', $id);
$id = str_replace('</code>', '', $id);
$baseId = str_replace('{td}', '', $cells[2]);
$quoteId = str_replace('{td}', '', $cells[1]);
$minAmountAsString = str_replace('{td}', '', $cells[3]);
$amountTickSizeAsString = str_replace('{td}', '', $cells[4]);
$priceTickSizeAsString = str_replace('{td}', '', $cells[5]);
```

Should also be changed to:

```
$id = str_replace('<td>', '', $cells[0]);
$id = str_replace('<code class="prettyprint">', '', $id);
$id = str_replace('</code>', '', $id);
$baseId = str_replace('<td>', '', $cells[2]);
$quoteId = str_replace('<td>', '', $cells[1]);
$minAmountAsString = str_replace('<td>', '', $cells[3]);
$amountTickSizeAsString = str_replace('<td>', '', $cells[4]);
$priceTickSizeAsString = str_replace('<td>', '', $cells[5]);
```

Also, though it's not really important and doesn't break anything, this comment seems to have been hit by the same search and replace all process:

```
//
//     array (
//         '{td}<code class="prettyprint">btcusd</code>',
//         '{td}USD', // $quote
//         '{td}BTC', // $base
//         '{td}0.00001 BTC (1e-5)', // min amount
//         '{td}0.00000001 BTC (1e-8)', // amount min tick size
//         '{td}0.01 USD', // price min tick size
//         '</tr>\n'
//     )
//
```

It should probably be corrected to this:

```
//
//     array (
//         '<td><code class="prettyprint">btcusd</code>',
//         '<td>USD', // $quote
//         '<td>BTC', // $base
//         '<td>0.00001 BTC (1e-5)', // min amount
//         '<td>0.00000001 BTC (1e-8)', // amount min tick size
//         '<td>0.01 USD', // price min tick size
//         '</tr>\n'
//     )
//
```

Hopefully that's the last of it. If I find anything else, I'll let you know.

**Comment by kroitor** [comment]
@Blobbus thx so much for a thorough report! We will fix the issues you mentioned and will get back to you asap.
