### ISSUE TITLE
[Vaultoro] Wrong symbol

### ISSUE THREAD

**Issue by aleksraiden** [ccxt/ccxt#5527]
- OS: Debian GNU/Linux 9 (stretch) x64
- Programming Language version: JS
- CCXT version: 1.18.942
- Exchange: Vaultoro
- Method: fetchTicker 

This exchange use Gold as base currency (and this hardcoded at vaultoro.js) but if I fetchTiker for BTC/USD symbol, I fetched wrong quote ( in fact, we fetch BTC/GLD, but obtain it as BTC/USD). 

For example:  
let vaultoro    = new ccxt.vaultoro ();  
vaultoro.fetchTicker('BTC/USD'); 

We obtain: 
{
    symbol: 'BTC/USD',
    timestamp: 1563269195253,
    datetime: '2019-07-16T09:26:35.253Z',
    high: 0.00439699,
    low: 0.00380114,
    bid: 0.0039,
    ask: 0.00419999,
    close: 0.0042,
    last: 0.0042,
    quoteVolume: 1303.866,
    info: {
      MarketCurrency: 'GLD',
      BaseCurrency: 'BTC',
      MarketCurrencyLong: 'Gold',
      BaseCurrencyLong: 'Bitcoin',
      MinTradeSize: 1e-8,
      MarketName: 'BTC-GLD',
      IsActive: true,
      MinUnitQty: 0.0002,
      MinPrice: 0.000002,
      LastPrice: '0.00420000',
      '24hLow': '0.00380114',
      '24hHigh': '0.00439699',
      '24hVolume': '1303.866'
    }

**Comment by kroitor** [comment]
We're going to remove `fetchTicker` for `vaultoro`, because the exchange API does not really have a corresponding endpoint: https://github.com/ccxt/ccxt/pull/5575
