### ISSUE TITLE
RightBTC API changed

### ISSUE THREAD

**Issue by SergeBirri** [ccxt/ccxt#5529]
due to recent update of RightBTC API, almost all of the methods and fields have changed, therefore ccxt/js/rightbtc.js file needs to be adjusted.

do you have planned the adaption to the new RightBTC API in the near future?

thank you so much and best regards
Serge

**Comment by frosty00** [comment]
Hi there @SergeBirri,

Thanks for letting us know that the rightbtc API has changed. Unfortunately we are extremely occupied with other aspects of CCXT coding. So I would suggest to @kroitor remove the rightbtc file if it is completely broken.

We currently do not have any plans to write the rightbtc api code. If you'd like to contribute please feel free to make a PR.

**Comment by silert** [comment]
Folks, please be careful with RightBTC exchange. They often block accounts for API trading (especially for HFT) without any explanation and don't allow to withdraw money. You can find multiple complains on bitcointalk forum and their telegram chat.
I would suggest to remove RightBTC completely from the ccxt library, otherwise new users will lose money.

**Comment by frosty00** [comment]
@silert @kroitor I think CCXT should take more responsibility for the shady behavior of exchanges, including adding "scam warning" badges that link to a github issue reporting a scam.

In this way CCXT can be more than just an API trading library but also a community that looks out for each other. If this is something you approve, I will look into adding this code after I finish with the code I am currently writing.

**Comment by Matoran** [comment]
From https://docs.rightbtc.com/news/

> API Compatibility
RightBTC 3.0 still provides PUBLIC API calls of RightBTC 2.0:
RightBTC 3.0 DOES NOT provide TRADE API calls of RightBTC 2.0 any more:

The new API doc: https://docs.rightbtc.com/api/rest_pub.html

Currently endpoints of the new API do not work for me. I will wait some time before coding anything for this exchange.

**Comment by ttodua** [comment]
Exchange is no longer available.
