### ISSUE TITLE
How to create margin orders on Binance?

### ISSUE THREAD

**Issue by aronfelipe** [ccxt/ccxt#5535]
Binance launch margin operations, how to create margin orders with ccxt in Binance?

**Comment by frosty00** [comment]
Hi there @aronfelipe, we have not yet implemented the code for margin trading in binance since it was only released a few days ago, and we are not robots. We also like need to eat, sleep, and well, poop...

**Comment by frosty00** [comment]
We will definitely implement it soon!

**Comment by kroitor** [comment]
Related duplicates:
- #5225 
- https://github.com/ccxt/ccxt/pull/5465

@aronfelipe the above links point to existing requests for Binance DEX. As @frosty00 said, we will get that functionality asap. Hope that answers the question. Let us know if not.

**Comment by kulievvitaly** [comment]
What is approximate time of implementation? 
Thank you for your job.

**Comment by fbport** [comment]
Hi, i'm also interested about Binance margin implementation. I'm checking the api documentation of margin trading and it seems that is just another direction that we must send the order like:

`Post  /sapi/v1/margin/order`

**Comment by fbport** [comment]
https://github.com/binance-exchange/binance-official-api-docs/blob/master/margin-api.md

**Comment by kroitor** [comment]
Binance margin API (sapi) has been added in CCXT version 1.18.1187: https://github.com/ccxt/ccxt/issues/5842
