### ISSUE TITLE
Exmo fetch_transaction method limitations

### ISSUE THREAD

**Issue by bnossn** [ccxt/ccxt#5536]
Hello,

I noticed that whenever we fetch transactions on Exmo the fetch_transactions method is only capable of returning transactions from the day you passed to the 'since' parameter and not from that day onwards as it's returned by most exchanges.
I know this due to the way WalletHistory works on Exmo. The only solution for I came up with is to do a fetch on every single day from 'since' up to today, taking into account the limitation on requests on that method which is 10 per minute. 

Is that a known issue? Are there plans to fix that on the near future?

- OS: Windows 7
- Programming Language version: Python 3.7.3
- CCXT version: 1.18.921
- Exchange: Exmo
- Method: fetch_transactions

**Comment by kroitor** [comment]
> The only solution for I came up with is to do a fetch on every single day from 'since' up to today, taking into account the limitation on requests on that method which is 10 per minute.

Unfortunately, that's the only possible solution with the EXMO API.

> Is that a known issue?

Yep.

> Are there plans to fix that on the near future?

No. Because this issue is on the exchange side – we can't work around it with just one http request per call. EXMO trades have to be traversed day by day, because the exchange leaves no other way to do this.

Let us know if the above does not answer the question.

**Comment by npomfret** [comment]
@bnossn I feel your pain, the Exmo api is bad.  You could try raising a ticket with the exchange, or tweeting them.  If no one asks they might not bother to improve it.

**Comment by bnossn** [comment]
Hi @npomfret. 
It definetely is pretty bad.
I'll raise a ticket and see what happens.
