### ISSUE TITLE
examples/js/cli - can't understand behavior

### ISSUE THREAD

**Issue by mkutny** [ccxt/ccxt#554]
I'm a bit lost.

I read the source code a dozen of times but still can't find what I'm missing.

This snippet works as I expect:

```
> const ccxt = require('ccxt')
> const bitmex = new ccxt['bitmex']
> const markets = bitmex.loadMarkets()
> bitmex.markets['BTC/USD'].active
true
```

But the `cli` can't find 'BTC/USD':
```
:air:~/src/ccxt max$ node examples/js/cli bitmex fetchMarkets | grep BTC/USD
:air:~/src/ccxt max$ 
```

Why it can't?

**Comment by kroitor** [comment]
Try it without grep ;)

**Comment by kroitor** [comment]
I don't really understand why grep does not catch the BTC/USD, but it's definitely there...

<img width="283" alt="screen shot 2017-11-14 at 01 54 46" src="https://user-images.githubusercontent.com/1294454/32753671-d297e8b2-c8de-11e7-98a8-f1ea0934ecbf.png">

**Comment by kroitor** [comment]
This one works, however:

```
mbp:ccxt igorkroitor$ node examples/js/symbols bitmex | grep BTC/USD
bitmex has 61 symbols: .BVOL, .BVOL10M, .BVOL1H, .BVOL24H, .BVOL30M, .BVOL7D, .BXBT, .BXBT30M, .BXBTJPY, .BXBTJPY30M, .DASHXBT, .DASHXBT30M, .ETCXBT, .ETCXBT30M, .ETHBON, .ETHBON2H, .ETHBON8H, .ETHXBT, .ETHXBT30M, .EVOL7D, .JPYBON, .JPYBON2H, .JPYBON8H, .LTCXBT, .LTCXBT30M, .USDBON, .USDBON2H, .USDBON8H, .XBT, .XBT30M, .XBTBON, .XBTBON2H, .XBTBON8H, .XBTJPY, .XBTJPY30M, .XBTJPYPI, .XBTJPYPI2H, .XBTJPYPI8H, .XBTUSDPI, .XBTUSDPI2H, .XBTUSDPI8H, .XMRXBT, .XMRXBT30M, .XRPXBT, .XRPXBT30M, .XTZXBT, .XTZXBT30M, .ZECXBT, .ZECXBT30M, BTC/USD, B_BLOCKSZ17, DASHZ17, ETC7D, ETHZ17, LTCZ17, XBJZ17, XBTZ17, XMRZ17, XRPZ17, XTZZ17, ZECZ17 (printSymbols @ symbols.js:37)
  symbol:   "BTC/USD",
XBTUSD      | BTC/USD     | BTC  | USD   | [object Object] | true  
mbp:ccxt igorkroitor$ 
```

**Comment by mkutny** [comment]
Thanks for the prompt reply!

First, I ran it without `grep`, of course...
Then I grepped the result just for brevity.

Still, don't have 'BTC/USD' reported it in my setup... But since you have it I'm sure it should be something trivial.

**Comment by kroitor** [comment]
```
node examples/js/cli bitmex fetchMarkets | grep BTC
```

This also works, but does not match the `symbol: 'BTC/USD'` line for some reason...

**Comment by mkutny** [comment]
The latter one (`examples/js/symbols`) works for me too.

**Comment by kroitor** [comment]
Found it... That process.exit () was interrupting the previous console.log (which is async in node). 

<img width="251" alt="screen shot 2017-11-14 at 02 06 50" src="https://user-images.githubusercontent.com/1294454/32754161-b43eb83a-c8e0-11e7-9e2e-411c9a0691ca.png">

Fixed it now, thank a lot!

**Comment by mkutny** [comment]
How did you discovered that???? I was staring at the code for few hours before I decided to open the issue :)

Was sure won't fall asleep due to this.

Thanks!!!

**Comment by kroitor** [comment]
@mkutny I had some issues with lagging console.log previously... but in this case initially I thought node is misunderstanding the arguments in the command line, but then it came to me out of memory, that when your main function is async, node usually hangs for a sec or two in order to flush the output buffers before exiting the process, so I thought, if the output does not make it to grep, something must be interrupting it on the way... But, I agree, this is totally unintuitive.

**Comment by kroitor** [comment]
Oh, and btw, if you are wondering why I put the process.exit there in the first place – I just didn't want to wait 1-2 seconds before it exits )))

**Comment by mkutny** [comment]
I also always wondered why it's handing for few secs even after all promises had been resolved.

That's a good catch, I would never figure it out myself.
