### ISSUE TITLE
Transpiler bug: semicolon in string disappears when transpiled to Python

### ISSUE THREAD

**Issue by xCuri0** [ccxt/ccxt#5543]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Arch
- Programming Language version: Python 3.7
- CCXT version: latest
- Exchange: 
- Method:
```
'Cookie': 'PHPSESSID=' + this.apiKey + '; REMEMBERME=' + this.secret,
```
becomes
```
'Cookie': 'PHPSESSID=' + self.apiKey + ' REMEMBERME=' + self.secret,
```
when transpiling to Python. The semicolon disappears which breaks the code

**Comment by kroitor** [comment]
I guess, this line:

https://github.com/ccxt/ccxt/blob/master/build/transpile.js#L202

should be

```
    [ /;$/g, '' ],
```

?

**Comment by xCuri0** [comment]
@kroitor thanks that worked

**Comment by xCuri0** [comment]
@kroitor fixes that problem but makes it not remove semicolons at the end so it breaks python ```E703 statement ends with a semicolon```

**Comment by kroitor** [comment]
@xCuri0 let me know if `[ /;$/gm, '' ],` does the trick. Your help is very much appreciated.

**Comment by xCuri0** [comment]
@kroitor still same error

**Comment by kroitor** [comment]
@xCuri0 will look into it and will get back to you asap.

**Comment by kroitor** [comment]
Changed to this and it seems to work:

```JavaScript
    [ /\;(\s+?\/\/.+?)/g, '$1' ],
    [ /\;$/gm, '' ],
```

Will arrive in version 1.18.963 in 15 minutes. @xCuri0 let us know if that resolves the issue for you.
