### ISSUE TITLE
question: coinfloor ledger parse

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5550]
The Coinfloor transactions api returns trades and transactions.  When parsing a trade I'm facing with the following:

         {
             "datetime": "2017-07-25 06:41:24",
             "id": 1500964884381265,
             "type": 2,
             "xbt": "0.1000",
             "xbt_eur": "2322.00",
             "eur": "-232.20",
             "fee": "0.00",
             "order_id": 84696745
         }

Should this result in 2 rows in the ledger (0.1BTC in and 232.2EUR out)?  If so, how do I implement that in `parseLedgerEntry`?

**Comment by kroitor** [comment]
> Should this result in 2 rows in the ledger (0.1BTC in and 232.2EUR out)?

Ideally – it should yield two rows. However that comes at a cost of breaking `limit` in the edge cases with date-based pagination.

> If so, how do I implement that in parseLedgerEntry?

There is more than one way to approach this, all of them ugly, but reliable:

1. You could duplicate the entries and append a flag before passing them to parseLedger.
2. You could return an array of entries from `parseLedgerEntry` and redefine `parseLedger` that would flatten the returned arrays into a single array.
3. You could combine 1+2

I'm more for 2, that would make the code more robust.

**Comment by npomfret** [comment]
thanks.  returning an array of items feels like the better solution to me.

**Comment by npomfret** [comment]
@kroitor does this make sense:

```
    parseLedger (data, currency = undefined, since = undefined, limit = undefined, params = {}) {
        let result = [];
        const array = Object.values (data || []);
        for (let i = 0; i < array.length; i++) {
            const itemOrItems = this.extend (this.parseLedgerEntry (array[i], currency), params);
            if (Array.isArray (itemOrItems)) {
                for (let i = 0; i < itemOrItems.length; i++) {
                    result.push (itemOrItems[i]);
                }
            } else {
                result.push (itemOrItems);
            }
        }

```

**Comment by kroitor** [comment]
@npomfret we could also try to unify the flattening logic in the base methods, because that may be handy for implementing further enhancements. As you know, the exchanges are very inconsistent with how they call and structure various things...

**Comment by npomfret** [comment]
>  we could also try to unify the flattening logic in the base methods

Yes, but I won't do that as a part of this change.
