### ISSUE TITLE
Kraken cctx broken

### ISSUE THREAD

**Issue by krmeljalen** [ccxt/ccxt#5553]
- OS: Linux Debian
- Programming Language version: Python
- CCXT version: Latest
- Exchange: Kraken
- Method: Balance

I see kraken's cctx doesn't work at all... I tried to get balance with:

E = cctx.kraken(apikey, secret)
E.fetch_total_balance()

And all i'm getting back is cloudflare ray a d error: kraken fetchBalance failed due to a malformed response.

Anyone even tried it and can verify this?

Best,
Alen

**Comment by kroitor** [comment]
```Python
E = cctx.kraken(apikey, secret)
E.fetch_total_balance()
```

First of, it's CCXT not CCTX )

Second, you're not using it correctly, as if you haven't read the Manual at all: https://github.com/ccxt/ccxt/wiki/Manual#api-keys-setup

This will work:

```Python
import ccxt
exchange = ccxt.kraken ({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
})
print(exchange.fetch_total_balance())
```

This will also work:

```Python
import ccxt
exchange = ccxt.kraken ()
exchange.apiKey = 'YOUR_API_KEY'
exchange.secret = 'YOUR_SECRET'
exchange.enableRateLimit = True
print(exchange.fetch_total_balance())
```

Also, see examples here: https://github.com/ccxt/ccxt/tree/master/examples/py

Let us know if that does not help.

**Comment by krmeljalen** [comment]
```
class TE():
    def __init__(self, exchanges):
        self.connections = {}
        for exchange in exchanges:
                self.connections[exchange] = getattr(sys.modules[__name__], "%s" % exchange)({
                    'apiKey': api_data[exchange]["api_key"],
                    'secret': api_data[exchange]["api_secret"],
                    'enableRateLimit': True
                })

    def get_balance(self, exchange):
        data = { "USD": None, "EUR": None, "BTC": None}
        response = self.connections[exchange].fetch_total_balance()
        data["EUR"] = response["EUR"]
        data["BTC"] = response["BTC"]
        return data

```
This is part of my code and it works perfectly for other exchanges, kraken throws exception:

  File "TE.py", line 50, in get_balance
    response = self.connections[exchange].fetch_total_balance()
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 1332, in fetch_total_balance
    return self.fetch_partial_balance('total', params)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 1322, in fetch_partial_balance
    balance = self.fetch_balance(params)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/kraken.py", line 769, in fetch_balance
    raise ExchangeNotAvailable(self.id + ' fetchBalance failed due to a malformed response ' + self.json(response))
ccxt.base.errors.ExchangeNotAvailable: kraken fetchBalance failed due to a malformed response {"error":[]}

Verbose:

Request: POST https://api.kraken.com/0/private/Balance {'API-Key': 'AjO........n6/r8oCPn59', 'API-Sign': 'eFMVUATJZKqD..............OQ==', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} nonce=1563466343090

Response: POST https://api.kraken.com/0/private/Balance 200 {'Date': 'Thu, 18 Jul 2019 16:12:23 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d8a1e9456a676ef79a34374f7d4c778551563466343; expires=Fri, 17-Jul-20 16:12:23 GMT; path=/; domain=.kraken.com; HttpOnly', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Strict-Transport-Security': 'max-age=15768000', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '4f85bca47b4197d8-FRA'} {"error":[]}
Traceback (most recent call last):
  File "TE.py", line 91, in <module>
    print(te.get_balance(exchange))
  File "TE.py", line 51, in get_balance
    response = self.connections[exchange].fetch_total_balance()
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 1332, in fetch_total_balance
    return self.fetch_partial_balance('total', params)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 1322, in fetch_partial_balance
    balance = self.fetch_balance(params)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/kraken.py", line 769, in fetch_balance
    raise ExchangeNotAvailable(self.id + ' fetchBalance failed due to a malformed response ' + self.json(response))
ccxt.base.errors.ExchangeNotAvailable: kraken fetchBalance failed due to a malformed response {"error":[]}

**Comment by kroitor** [comment]
@krmeljalen ok, I see... Does that happen with an empty balance? If you confirm this, we will add a workaround shortly. Thx!

**Comment by krmeljalen** [comment]
Oh you think it's connected with empty balance? Yes I have empty balance currently. I'll deposit some BTC and see if this problem persists. Thanks a lot for a suggestion.

**Comment by kroitor** [comment]
> Oh you think it's connected with empty balance? Yes I have empty balance currently. I'll deposit some BTC and see if this problem persists. Thanks a lot for a suggestion.

Yep, I can't reproduce it on my side with the above snippet. If that is the case, it's easy to add a workaround, though. Let me know if you can confirm, we'll upload the fix asap.

**Comment by krmeljalen** [comment]
It works! Depositing BTC to kraken solved the issue and now i'm getting proper response. Thanks a lot for guidance.

**Comment by kroitor** [comment]
@krmeljalen ok, thx for the followup! We will add the workaround for empty balances shortly!

**Comment by mkcisse** [comment]
- OS: Ubuntu 18.04 LTS
- Programming Language version: Python
- CCXT version: Latest
- Exchange: Kraken
- Method: LoadMarkets

I have the same issue :

`import ccxt`
`exchange = ccxt.kraken({`
`    'apiKey': kraken_api_key,`
`    'secret': kraken_api_secret`
`})`
`exchange.load_markets()`


File "/home/mkcisse/algorithmic_trading/.venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 388, in fetch
    response.raise_for_status()
  File "/home/mkcisse/algorithmic_trading/.venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mkcisse/algorithmic_trading/test_ccxt.py", line 31, in <module>
    exchange.load_markets()
  File "/home/mkcisse/algorithmic_trading/.venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 977, in load_markets
    markets = self.fetch_markets()
