### ISSUE TITLE
fetchOpenOrders() Filter

### ISSUE THREAD

**Issue by Tezeug** [ccxt/ccxt#5557]
- OS: Kubuntu 19.04 64-bit
- Programming Language version: Python 3.7.3
- CCXT version: 1.18.963
- Exchange: Deribit
- Method: fetchOpenOrders(), privateGetGetopenorders()

Hello. I have been trying to filter the result of open orders CCXT "command" but unsuccessfully. I have tried these methods:

fetchOpenOrders(symbol="BTC-PERPETUAL", params=("filter":{"side":"sell"}})

Shows just ccxt.base.errors.AuthenticationError: deribit {... "message":"authorization_required" ... "error":10000} However, the keys are correct and every other method works.

privateGetGetopenorders({"instrument":"BTC-PERPETUAL", "side":"sell"})

Works but does not filter.
Any idea on how to do that? Can be even just in Python. I have searched over the internet like "python filter lists" but have not found such a working solution. By the way, this argument unfortunately is not listed in the Deribit documentation so I think it is not possible to do it this way.

Thanks.

**Comment by kroitor** [comment]
Hi!

It is done like so:

```Python
import ccxt
from pprint import pprint
exchange = ccxt.deribit({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
balance = exchange.fetch_balance()
pprint('Balance:')
pprint(balance)
orders = exchange.fetch_open_orders('BTC-PERPETUAL')
sell_orders = [order for order in orders if order['side'] === 'sell']  # ←--- filtering
pprint('Sell orders:')
pprint(sell_orders)
```

> By the way, this argument unfortunately is not listed in the Deribit documentation so I think it is not possible to do it this way.

You can't pass random parameters to an exchange and hope that it works. There's no indication anywhere that `deribit` would support the `filter` parameter to filter orders on the exchange side.
You have to do the filtering by `side` on your end in userland, using Python list comprehensions, as shown above. In general, all userland filtering in Python is mostly done with list comprehensions: 

- https://stackoverflow.com/questions/29051573/python-filter-list-of-dictionaries-based-on-key-value

Let us know if that does not answer the question.

**Comment by Tezeug** [comment]
Thank you so much. It helped me.
