### ISSUE TITLE
Adding demo mode to DSX

### ISSUE THREAD

**Issue by JustStas** [ccxt/ccxt#5566]
Would it be possible to add Demo mode support for DSX?
Per the API manual (https://dsx.uk/developers/publicApiV2#tag/Before-you-start), it should be a pretty simple addition:

By default all requests return LIVE marketdata but you can specify marketdata type by using query parameter "mode". Possible values: ["LIVE", "DEMO"].For example:https://dsx.uk/mapi/depth/btcusd?mode=DEMO

I would love to contribute, but unfortunately am new to programming a can't yet understand, where the changes should happen.

Stan

**Comment by kroitor** [comment]
@JustStas the DSX implementation is currently being reworked right now, we hope to add the missing functionality soon!

> I would love to contribute, but unfortunately am new to programming a can't yet understand, where the changes should happen.

You'd want to start from here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md )

**Comment by kroitor** [comment]
@JustStas in order to use the demo mode with the existing DSX implementation you would simply override the endpoint params a bit:

```Python
from pprint import pprint
import ccxt
exchange = ccxt.dsx({
    'enableRateLimit': True,
})

params = {
    'mode': 'DEMO',
}
symbol = 'BTC/USD'
limit = None

orderbook = exchange.fetch_order_book(symbol, limit, params)
pprint(orderbook)
```

The above is explained in the Manual here: https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

Let us know if the above does not answer the question.
