### ISSUE TITLE
Conceptual question about trades type

### ISSUE THREAD

**Issue by KoenBal** [ccxt/ccxt#5567]
Hello,

A trade from the public api can have a type "limit" or "market". But what does this exactly mean?
Isn't a trade always a market trade? Or does this mean that the second order of the 2 matching orders was a limit order? If this is the case. What information does this give you?

,Thanks for your advice

**Comment by frosty00** [comment]
Hi @KoenBal,

Please see the manual for information about [market orders](https://github.com/ccxt/ccxt/wiki/Manual#market-orders) and [limit orders](https://github.com/ccxt/ccxt/wiki/Manual#limit-orders).

In short a market buy is executed at the price lowest price available in the exchange's orderbooks, whereas a limit order will only execute at the price specified in the order or better.

**Comment by kroitor** [comment]
> But what does this exactly mean?

It is the type of the user's order associated with that trade. If the user ordered a `limit` order and that yielded a trade – that trade would be a `limit` trade. If the order was a `market` order, then the corresponding trade would also have the `market` type.

> Isn't a trade always a market trade? Or does this mean that the second order of the 2 matching orders was a limit order? If this is the case. What information does this give you?

For public trades this does not really carry any meaningful info. For a private trade that could help restore historical information about the order. So, you're right, in general, the use of the `type` of the trade is very limited.

Let us know if that does not answer your question.
