### ISSUE TITLE
Gemini candlestick data

### ISSUE THREAD

**Issue by michalfalat** [ccxt/ccxt#5576]
There was new version of API for Gemini exchange released. Now they offer endpoint for candlestick chart. Is this feature in your rodmap soon ?
 
Reference:
https://docs.gemini.com/rest-api/#candles

Thanks.

- OS: WIN
- Programming Language version: javascript
- CCXT version: 1.18.846
- Exchange: Gemini
- Method: fetchOHLCV()

**Comment by frosty00** [comment]
Hi there @michalfalat,

We will add support for `gemini.fetchOHLCV` asap, thanks for your patience.

**Comment by frosty00** [comment]
I've added it, btw I like your the hair fade @michalfalat

**Comment by michalfalat** [comment]
Thanks man ! You are doing really good job guys.
