### ISSUE TITLE
Error Handling (Question)

### ISSUE THREAD

**Issue by Tezeug** [ccxt/ccxt#5577]
- OS: Kubuntu 19.04 64-bit
- Programming Language version: Python 3.7.3
- CCXT version: 1.18.965
- Exchange: Deribit, BitMEX
- Method: none, error handling

Hello.
This is not an issue, rather a question about the error handling. I have checked the manual and "set the code" according to it but sometimes it still fails in some rare cases.

I have the whole code in one big cycle and a lot of another cycles in it but basically it looks like this.

```python
while True:
   try: 
        code...
   except ccxt.ExchangeNotAvailable:
        continue
   except ccxt.RequestTimeout:
        continue
```

And other similar exceptions. But e. g. the bot is running for 1 hour and then some request timeouts and the bot crashes, even though there is the exception to keep running. How to fix that? Is there something wrong?

**Comment by frosty00** [comment]
Hi there @Tezeug,

`except ccxt.RequestTimeout` will catch all `RequestTimeout` errors and any error that is more specific and subclasses `RequestTimeout`.

Your code does not handle `ExchangeError` or `NetworkErrors` which may be why the bot crashes. If you want to catch all errors you can also use `except BaseError`. You can see the python error hierarchy [here](https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/errors.py)

**Comment by Tezeug** [comment]
Hello!
I have implemented the ccxt.BaseError solution based on your recommendation and will see whether it works or not. I did not know about such a nice hierarchy with all the possible exceptions, thank you very much. I will be testing it just right now and let you know then how it goes. Meanwhile the problem I have reported before has happened again several times. By the way, I have had implemented these exceptions even before (ExchangeError, ExchangeNotAvailable).
Have a lovely day.

**Comment by kroitor** [comment]
@Tezeug let us know if implementing the _"catch-all"_ solution with `BaseError` as proposed by @frosty00 does not resolve the issue. We will be happy if you report back, whether it helped or not. If you still get an uncaught exception after implementing `except BaseError` then we will need you to copypaste the error callstack and the verbose request/response (without your keys) as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
Closing this for now, if you don't mind. Feel free to reopen it if needed or just ask further questions if any.

**Comment by Tezeug** [comment]
Hello.
Unfortunately, it has not fixed the problem. I am posting the error traceback down below. Check it out and let me know if you need anything else. I would have to run the bot for a few hours again on the testnet with the verbose set to get the result. By the way, this is how I have implemented it.

```Python
while True:
      try:
             #Code...
      except ccxt.BaseError as Error:
             print ("[ERROR]", Error)
             continue

**Comment by Tezeug** [comment]
```Python
[ERROR] GET https://testnet.bitmex.com/api/v1/position?symbol=BTC%2FUSD 
Traceback (most recent call last):
 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request 
   six.raise_from(e, None) 
 File "<string>", line 3, in raise_from 
 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request 
   httplib_response = conn.getresponse() 
 File "/usr/lib/python3.7/http/client.py", line 1321, in getresponse 
   response.begin() 
 File "/usr/lib/python3.7/http/client.py", line 296, in begin 
   version, status, reason = self._read_status() 
 File "/usr/lib/python3.7/http/client.py", line 257, in _read_status 
   line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1") 
 File "/usr/lib/python3.7/socket.py", line 589, in readinto 
   return self._sock.recv_into(b) 
 File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into 
   return self.read(nbytes, buffer) 
 File "/usr/lib/python3.7/ssl.py", line 911, in read 
   return self._sslobj.read(len, buffer) 
socket.timeout: The read operation timed out 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last):
 File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send 
   timeout=timeout 
 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen 
   _stacktrace=sys.exc_info()[2]) 
 File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 367, in increment 
   raise six.reraise(type(error), error, _stacktrace) 
 File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise 
   raise value 
 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen 
   chunked=chunked) 
 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 386, in _make_request 
   self._raise_timeout(err=e, url=url, timeout_value=read_timeout) 
 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 306, in _raise_timeout 
   raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value) 
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='test.deribit.com', port=443): Read timed out. (read timeout=10) 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last):
 File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 518, in fetch 
   verify=self.verify 
 File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request 
   resp = self.send(prep, **send_kwargs) 
 File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send 
   r = adapter.send(request, **kwargs) 
 File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send 
   raise ReadTimeout(e, request=request) 
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='test.deribit.com', port=443): Read timed out. (read timeout=10) 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last):
 File "T1.py", line 141, in <module> 
   E2OPAM = BITMEX.privateGetPosition({"symbol":"BTC/USD"})[0] 
 File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 432, in inner 
   return entry(_self, **inner_kwargs) 
 File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 455, in request 
   return self.fetch2(path, api, method, params, headers, body) 
 File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 451, in fetch2 
   return self.fetch(request['url'], request['method'], request['headers'], request['body']) 
 File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 538, in fetch 
   raise RequestTimeout(method + ' ' + url) 
ccxt.base.errors.RequestTimeout: GET https://test.deribit.com/api/v1/private/positions?instrument=BTC-PERPETUAL
```

**Comment by Tezeug** [comment]
As I said, everything was working for a few hours before this happened. I am sure the internet connection was fine but even though it should keep running.

**Comment by kroitor** [comment]
@Tezeug looks like a bug to me, but we will get this sorted asap. Thx for the followup! Will get back to you shortly.

**Comment by Tezeug** [comment]
Thank you so much. Meanwhile it has happened again. I guess the problem is just the handling of the RequestTimeout error. Every other exception has worked so far. I would have reported if otherwise.

**Comment by frosty00** [comment]
@kroitor I don't think this is a bug.

The last line of the trace is `ccxt.base.errors.RequestTimeout: GET https://test.deribit.com/api/v1/private/positions?instrument=BTC-PERPETUAL`, that means a unified error was thrown and not handled correctly by @Tezeug.

Are you sure that all your code is wrapped like:

```
while True:
   try: 
        code...
    except ccxt.BaseError:
        pass
```

maybe you had some part of your bot that called a ccxt method in a not wrapped context?

**Comment by Tezeug** [comment]
![220CA55B-FA2E-420A-8406-7610868F586F](https://user-images.githubusercontent.com/48736723/61789218-6777e380-ae14-11e9-9ede-8e24b1799374.jpeg)

I think it is fine. Just an update. It has now been running all day without any error yet.

**Comment by Tezeug** [comment]
Until now, it has not happened again so I'll close the issue temporarily. Maybe it was just some error on the BitMEX's side, I am not really sure. I would let you know if it happened again.
Thank you.
