### ISSUE TITLE
okcoin v3

### ISSUE THREAD

**Issue by tealcake2** [ccxt/ccxt#5583]
hello will you make okcoin v3 api ? thx

**Comment by frosty00** [comment]
Hi there @tealcake2,

Please check out https://github.com/ccxt/ccxt/blob/master/js/okex3.js

and update ccxt to get the latest bugfixes. Thank you for using ccxt )

**Comment by kroitor** [comment]
Hello, @tealcake2 ! We will look into adding support for OKCoin V3 asap. In the meantime, you can use OKCoin v3, by configuring the OKEX v3 which is interchangeable with OKCoin v3. That means you can use OKCoin v3 by using OKEX v3 with a different API base URL as shown below:

--------------

```JavaScript
'use strict';

// JavaScript

const ccxt = require ('ccxt')
const exchange = new ccxt.okex3 ({
    "urls": {
        "api": "https://www.okcoin.com"
    },
    "options": {
        "fetchMarkets": [ "spot" ]
    },
})

;(async () => {
    console.log (await exchange.fetchTicker ('BTC/USD'))
}) ()
```

--------------

```Python
# Python

import ccxt
from pprint import pprint
exchange = ccxt.okex3({
    "urls": {
        "api": "https://www.okcoin.com"
    },
    "options": {
        "fetchMarkets": ["spot"]
    },
})

pprint(exchange.fetch_ticker('BTC/USD'))
```

--------------

```PHP
// PHP

$id = 'okex3';
$exchange_class = '\\ccxt\\' . $id;
$exchange = new $exchange_class(array(
    "urls" => array(
        "api" => "https://www.okcoin.com"
    ),
    "options" => array(
        "fetchMarkets" => array("spot"),
    ),
})

print_r(exchange->fetch_ticker('BTC/USD'));
```

Let us know if that does not answer the question.
