### ISSUE TITLE
How to use CCXT in a react native project?

### ISSUE THREAD

**Issue by Bill-Niz** [ccxt/ccxt#5589]
- OS:Mac OS X
- Programming Language version:React Native
- CCXT version: 1.18.977
- Exchange: n/a
- Method: n/a

Cannot use ccxt with my react native project.
I got this error 
`Module stream does not exist in the Haste module map`
Located at /js/static_dependencies/node-fetch/index.js#L136
[https://github.com/ccxt/ccxt/blob/master/js/static_dependencies/node-fetch/index.js#L136](url)

**Comment by kroitor** [comment]
Hi!

In general, you're required to configure the Babel transpilation for your react project in a way that would exclude non-portable parts from your build. The node/browser version of CCXT uses the `node-fetch` or `window.fetch` to issue networking calls. However, in a react environment that should be substituted with a react-specific code. So, to make CCXT work you have to configure the transpilation on your side and add the necessary exceptions there.

See also:

- https://github.com/ccxt/ccxt/issues/299
- https://github.com/ccxt/ccxt/issues/1916
- https://github.com/ccxt/ccxt/issues/2955#issuecomment-392230458
- https://github.com/ccxt/ccxt/issues/3711
- \+ other linked issues ...

Let us know if that does not answer the question.

**Comment by qasimmehdi** [comment]
If anyone is still having a problem with this I got working in just a few steps,
Make sure you have not installed buffer or http or any library that you see in the errors. Then install this library
`yarn add node-libs-react-native` or `npm install node-libs-react-native`
Then you just have to modify your **metro.config.js**
In module.exports add this property
```
resolver: {
    extraNodeModules: require("node-libs-react-native")
 }
```
Then your **metro.config.js** may look like this
```
module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
  resolver: {
    extraNodeModules: require("node-libs-react-native")
  },
};
```
Now you just need to import the library in the very first line of **index.js**
`import 'node-libs-react-native/globals';`
After this your app should work with ccxt.

**Comment by kroitor** [comment]
@qasimmehdi thx for your feedback, much appreciated!

**Comment by theocerutti** [comment]
Hello! I tried your solution, it fixed the "stream" error but then I have the "BigInt" error...
```
 ERROR  ReferenceError: Property 'BigInt' doesn't exist, js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
```

It seems BigInt is not natively supported so...
I don't know if anyone had the same issue!

thanks!
