### ISSUE TITLE
how to get 30 days in fetchTicker 

### ISSUE THREAD

**Issue by ockang** [ccxt/ccxt#5592]
Hi, I need to get results for 30 days or 1 month on fetchTicker, thanks

**Comment by kroitor** [comment]
@ockang check out the manual on OHLCV candles: https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts. OHLCV is basically statistical _"ticker"_ info over a period of time.

**Comment by kroitor** [comment]
P.S. Also, see OHLCV examples here: https://github.com/ccxt/ccxt/tree/master/examples

**Comment by ockang** [comment]
it's possible?:  await kucoin.fetchTicker('RIF/BTC', '1M'),

**Comment by kroitor** [comment]
@ockang it's not possible with `fetchTicker`, it's possible with `fetchOHLCV`.

**Comment by ockang** [comment]
await kucoin.fetchOHLCV('RIF/BTC', '1M'); it doesn't work that way

**Comment by ockang** [comment]
the idea is to get Monthly Performance
