### ISSUE TITLE
how to get 30 days in fetchOHLCV

### ISSUE THREAD

**Issue by ockang** [ccxt/ccxt#5593]
Hello community does not work fetchOHLCV for 1 month, await kucoin.fetchOHLCV ('RIF / BTC', '1M'),

**Comment by kroitor** [comment]
@ockang plz do not open multiple issues on the same topic. 

> does not work fetchOHLCV for 1 month

You can't just swap the method name for another method name and hope that it will work. You should read the Manual, and, more importantly, understand it, as was linked here: https://github.com/ccxt/ccxt/issues/5592#issuecomment-514689632. 

We support 3 languages and you haven't even mentioned which language you're using. You haven't posted the short snippet of code you've tried. So we can't guess it out of thin air. And you haven't pasted the verbose output as required here:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

If you follow those guides literally, your question will be answered even before you ask it.

In JavaScript you would do this:

```JavaScript
const ccxt = require ('ccxt')
const exchange = new ccxt.kucoin ({
    enableRateLimit: true,
})

;(async () => {
    const symbol = 'RIF/BTC'
    const timeframe = '1d' // one day
    const since = undefined
    const limit = 30 // 30 days = 1 month
    const oneMonthOfData = await fetchOHLCV ('RIF/BTC', '1d', undefined, limit)
    console.log (oneMonthOfData)
}) ()
```

The above is covered in the Manual and in the examples. Hope that helps.

**Comment by kroitor** [comment]
Examples:

- https://github.com/ccxt/ccxt/blob/master/examples/js/binance-fetch-ohlcv.js
- https://github.com/ccxt/ccxt/blob/master/examples/js/fetch-ohlcv-cex.js
- https://github.com/ccxt/ccxt/blob/master/examples/js/okex-fetch-ohlcv-since-limit.js
