### ISSUE TITLE
HitBTC (2) failing to parseOrder

### ISSUE THREAD

**Issue by devsi** [ccxt/ccxt#5594]
- CCXT version: 1.18.982
- Exchange: hitbtc2
- Method: parseOrder

I am getting strange results on this one. Sometimes it is successful, sometimes it fails.

I ran the following command:

```
$hitbtc2->createOrder('DCN/BTC', 'limit', 'buy', $quantity, $price);
```

where `$quantity = 1910000` and `$price = '0.00000000394'`.

and got:

```
A non well formed numeric value encountered :: #0 /var/www/html/vendor/ccxt/ccxt/php/hitbtc2.php(1181): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'A non well form...', '/var/www/html/v...', 1181, Array)
#1 /var/www/html/vendor/ccxt/ccxt/php/hitbtc2.php(1051): ccxt\hitbtc2->parse_order(Array)
#2 /var/www/html/vendor/ccxt/ccxt/php/Exchange.php(2074): ccxt\hitbtc2->create_order('DCN/BTC', 'limit', 'buy', 1910000, 3.94E-9, Array)
#3 [internal function]: ccxt\Exchange->createOrder('DCN/BTC', 'limit', 'buy', 1910000, 3.94E-9)
```

Originally I thought it was the fact the price was wrapped in a string, but tested again with a float and the error still happened.

Looking at the error I can see `3.94E-9` but I wonder if that's just PHP trying to truncate the output, or whether THAT is what the malformation is. 

Line 1181 on my current version of hitbtc2 is: `$average = $cost / $filled`.

https://github.com/ccxt/ccxt/blob/7bf11a03a32240b49b6315269252b638f3a94493/php/hitbtc2.php#L1195

As I can't reliably replicate I don't know whats happening, however I get the feeling it's related to `tradesReport` somehow.

Any ideas?

**Comment by kroitor** [comment]
@devsi what's your version of PHP?

**Comment by simonw-** [comment]
PHP 7.2.

**Comment by kroitor** [comment]
@simonw- it was a transpilation bug directly related to this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#adding-numbers-and-concatenating-strings, I've uploaded the fix, it will arrive in 15 minutes in version 1.18.983. Thx for reporting!
