### ISSUE TITLE
How to get the logos of crypto currencies

### ISSUE THREAD

**Issue by nettemsarath** [ccxt/ccxt#5595]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

**Comment by kroitor** [comment]
@nettemsarath CCXT does not store or serve coin logos, this particular aspect is beyond the algorithmic trading purpose of this lib. If you want coin logos, you will have to scrape some websites. Hope that answers the question.

**Comment by npomfret** [comment]
@nettemsarath try https://www.npmjs.com/package/cryptocurrency-icons
