### ISSUE TITLE
why base class exchange do not contains fetch_ticker definition ?

### ISSUE THREAD

**Issue by Matoran** [ccxt/ccxt#5598]
Hi, everything is in the title :). Do we have a reason to not include `fetch_ticker` in base classes?

**Comment by frosty00** [comment]
Hi @Matoran, it depends on what you mean by support `fetch_ticker` in the base class. We could add a stub method that would throw a `NotSupported` error if someone tried to call `fetch_ticker` on a derived class where it doesn't exist.

On the other hand we could emulate it in the base class by doing a `fetch_order_book` followed by a `fetch_ohlcv`. However we would have to decide on whether to support it asynchronously or call one method after the other.

**Comment by kroitor** [comment]
@frosty00 i guess, @Matoran is asking about the the stub that would throw a `NotSupported` exception in this case.

@Matoran we will add it to the base definitions asap, your help with that is really welcome! )

**Comment by Matoran** [comment]
@frosty00 @kroitor yes it's just the stub with `NotSupported`. I will do a pull request :).
