### ISSUE TITLE
fetch Ticker bitfinex does not return the open level percentage

### ISSUE THREAD

**Issue by ockang** [ccxt/ccxt#5599]
Hello community, I am using await bitfinex.fetchTicker ('RIF / USD') to bring the open or percentage, but the returning json did not find it:

`{"ticker_day": {
"symbol": "RIF/USD",
"timestamp": 1564159845884.2126,
"datetime": "2019-07-26T16:50:45.884Z",
"high": 0.11235,
"low": 0.11235,
"bid": 0.10011,
"ask": 0.13496,
"close": 0.11235,
"last": 0.11235,
"average": 0.117535,
"baseVolume": 58,
"info": {
"mid": "0.117535",
"bid": "0.10011",
"ask": "0.13496",
"last_price": "0.11235",
"low": "0.11235",
"high": "0.11235",
"volume": "58.0",
"timestamp": "1564159845.8842127"
}
}`

**Comment by kroitor** [comment]
@ockang hi! Some fields of the `ticker` structure may be missing, if the underlying exchange does not provide them:

```
mbp:ccxt igorkroitor$ node examples/js/cli bitfinex fetchTicker RIF/USD
bitfinex.fetchTicker (RIF/USD)
{        symbol:   "RIF/USD",
      timestamp:    1564160459656.7617,
       datetime:   "2019-07-26T17:00:59.656Z",
           high:    0.11235,
            low:    0.11235,
            bid:    0.10011,
      bidVolume:    undefined,
            ask:    0.13496,
      askVolume:    undefined,
           vwap:    undefined,
           open:    undefined,
          close:    0.11235,
           last:    0.11235,
  previousClose:    undefined,
         change:    undefined,
     percentage:    undefined,
        average:    0.117535,
     baseVolume:    58,
    quoteVolume:    undefined,
           info: {        mid: "0.117535",
                          bid: "0.10011",
                          ask: "0.13496",
                   last_price: "0.11235",
                          low: "0.11235",
                         high: "0.11235",
                       volume: "58.0",
                    timestamp: "1564160459.6567616" } }
mbp:ccxt igorkroitor$
```

↑ As you see from the raw response contained in the `info` inside the ticker – Bitfinex does not provide enough information to calculate the percentage or the change of price with that ticker. You can only do that with `fetchOHLCV` or by doing subsequent calls to `fetchTicker` and calculating the difference between the `last` price to get the actual change.
