### ISSUE TITLE
Backtesting [Question]

### ISSUE THREAD

**Issue by Tezeug** [ccxt/ccxt#5600]
- OS: Kubuntu 19.04 64-bit
- Programming Language version: Python 3.7.3
- CCXT version: 1.19.983
- Exchange: x
- Method: x

Hello. Just wanted to ask. Is there any plan on adding the backtesting feature natively and directly into the CCXT? I have searched over the issues here on the official GitHub page and there were not many information on that, although someone has wanted to post a bounty for it. Thanks.

**Comment by frosty00** [comment]
Hi @Tezeug,

We do not have any plans to add support for backtesting to the CCXT library. Frankly we believe that this code should exist in userland.

https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar

**Comment by Tezeug** [comment]
Hello. I have read it and I totally understand. Thank you.

**Comment by kroitor** [comment]
@Tezeug you might want to check this tutorial by backtest rookies: https://backtest-rookies.com/2018/03/08/download-cryptocurrency-data-with-ccxt/
