### ISSUE TITLE
Yobit createLimitOrder 

### ISSUE THREAD

**Issue by jurgenmela28** [ccxt/ccxt#5610]
const price = undefined
		const params = {}
		const order = await exchange.createLimitOrder(
			'BTC/USD',
			'limit',
			'sell',
			data.BTCAmount,
			price,
			params
		)
		return order
brings me this kind of error
 Error: sell: invalid number (contains an illegal character 's')

**Comment by jurgenmela28** [comment]
Additional info:

	        const price = undefined
		const params = {}
		const order = await exchange.createLimitSellOrder(
			'BTC/USD',
			'market',
			'sell',
			0.005,
			price,
			params
		)

Error: Error: market: invalid number (contains an illegal character 'm')

ps: when put string limit insted of market brings:
Error: limit: invalid number (contains an illegal character 'l')

**Comment by kroitor** [comment]
@jurgenmela28 you're not using it correctly... When you call `createLimitSellOrder` you should omit the `type` and the `side`. Compare these two calls:

```JavaScript
createOrder ('BTC/USD', 'limit', 'sell', amount, price) // type and side in the args here
createLimitSellOrder ('BTC/USD', amount, price) // no type and side in the args here
```

Pay attention to the arguments, as described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#limit-orders
- https://github.com/ccxt/ccxt/wiki/Manual#other-order-types

Let us know if that does not answer the question.

**Comment by jurgenmela28** [comment]
ok thank you this one works:

	const order = await exchange.createOrder(
			'BTC/USD',
			'limit',
			'sell',
			data.BTCAmount,
			data.price
		)

**Comment by kroitor** [comment]
@jurgenmela28 this one will also work:

```
        const order = await exchange.createLimitOrder(
		'BTC/USD',
		'sell',
		data.BTCAmount,
		price,
		params
	)
```
