### ISSUE TITLE
Proxy parameter naively impelemented

### ISSUE THREAD

**Issue by eabrouwer3** [ccxt/ccxt#5616]
- OS: Ubuntu 19.04
- Programming Language version: Python 3.6
- CCXT version: 1.18.983
- Exchange: Bitfinex
- Method: `fetchMyTrades`

I've looked at the manual, and at a couple other issues about proxy things such as https://github.com/ccxt/ccxt/issues/95. Why don't we just use the `proxies` dictionary on the session object? I'm happy to create a PR for this, I just would like to know if there's a reason we're just appending the URL to the end of the proxy URL instead of using request's built in `proxies` handling.

i.e. Instead of doing this
```
url = self.proxy + url
```
We do this
```
self.session.proxies = self.proxies
```
Just for reference, I'm using [Luminati](https://luminati.io) to proxy my requests.

**Comment by kroitor** [comment]
> Why don't we just use the proxies dictionary on the session object?

You're late to the party ))

- https://github.com/ccxt/ccxt/issues/906
- https://github.com/ccxt/ccxt/wiki/Install#python-proxies

We do support both `.proxy` (for CORS) and `.proxies` (for SOCKS/HTTPS proxies).

Let me know if that does not answer the question )

**Comment by eabrouwer3** [comment]
Oh good! I feel like I saw that, and then totally forgot about it. Thanks for the link!
