### ISSUE TITLE
async php with swoole

### ISSUE THREAD

**Issue by rspadim** [ccxt/ccxt#5618]
hi folks, could be possible use swoole extension and php with ccxt? or maybe with curl select

**Comment by frosty00** [comment]
Hi @rspadim,

We have looked at different async php frameworks and if we have to support one it would probably be https://reactphp.org/. This is what we are using in our unreleased websocket framework, and so it would make sense to use the same code everywhere.

For now I think it is possible to make php async by using threads or processes using [`pctnl_fork`](https://www.php.net/manual/en/function.pcntl-fork.php)

**Comment by rspadim** [comment]
hi @frosty00 , i work with php since php3, swoole seens a better implementation of async, it's a extension based (c/c++ low level language). I could agree with you if the option is do something that don't need .dll/.so files, but others async solutions are not optimal. we can use websocket client here: https://www.php.net/manual/en/swoole-http-client.push.php

**Comment by frosty00** [comment]
It's more a question of whether swoole has support for promises, because currently the transpiler relies on them in react php, + futures in python + promises in js to make the ws work seemlessly. 

IMO supporting async php is kinda out of the scope of ccxt, and should be left to the user.
