### ISSUE TITLE
CoinEX endpoint for markets info 

### ISSUE THREAD

**Issue by buyongji** [ccxt/ccxt#5620]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:all
- Programming Language version:all
- CCXT version:
- Exchange:CoinEx
- Method:

use https://api.coinex.com/v1/market/info instead of https://www.coinex.com/res/market/info
and the CoinEx support Margin Trading. When can support it?

**Comment by kroitor** [comment]
> use https://api.coinex.com/v1/market/info instead of https://www.coinex.com/res/market/info

This has been added in CCXT 1.18.1011+.

> and the CoinEx support Margin Trading. When can support it?

We have added the endpoints for margin and futures trading to CoinEx implementation in CCXT 1.18.1011+ as well.

Please, note that margin trading and derivatives are not unified in CCXT yet. However, you can use all the endpoints and params with implicit methods, as described here:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

Let us know if anything. Thanks!
