### ISSUE TITLE
BITFINEX ERR_RATE_LIMIT

### ISSUE THREAD

**Issue by ockang** [ccxt/ccxt#5621]
Hello community I have the following problem  bitfinex {"error":"ERR_RATE_LIMIT"}

**Comment by kroitor** [comment]
Please read the Manual and search on how to use the rate-limiter:

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties
- https://github.com/ccxt/ccxt/search?q=ERR_RATE_LIMIT&type=Issues
- https://github.com/ccxt/ccxt/issues/5043
- https://github.com/ccxt/ccxt/issues/2166
- https://github.com/ccxt/ccxt/issues/2700

Let us know if that does not answer the question.
