### ISSUE TITLE
bit-z.com error -102

### ISSUE THREAD

**Issue by vxnuke** [ccxt/ccxt#5622]
When i try to pull balance i get this error
`ccxt.base.errors.ExchangeError: bitz {"status":-102,"msg":"","data":"","time":1564670255,"microtime":"0.02929000 1564670255","source":"api"}`
Error -102 is parameter error i read there api parameters for balance can't see anything wrong not sure what the issue is.

Update:
I tried pulling closed orders got same issue maybe it has something to do with auth request
`Pull_closed_orders error: ccxt.base.errors.ExchangeError: bitz {"status":-102,"msg":"","data":"","time":1564672374,"microtime":"0.20707900 1564672374","source":"api"}`

**Comment by kroitor** [comment]
@vxnuke is this a new API key, or did you use it before with another software?

**Comment by vxnuke** [comment]
new api key

**Comment by kroitor** [comment]
@vxnuke have you tested it with `cli.py` or with `cli.js` ? (It requires `keys.json` or `keys.local.json` containing `{"bitz":{"apiKey":"YOUR_API_KEY","secret":"YOUR_API_SECRET","password":"YOUR_API_PASSWORD"}}`.

It does work in my case:

```
mbp:ccxt igorkroitor$ node examples/js/cli bitz fetchBalance
bitz.fetchBalance ()
{  info: {    status:    200,
                 msg:   "",
                data: { cny: 0, usd: 0, btc_total: 0, info: [] },
                time:    1564672476,
           microtime:   "0.99443700 1564672476",
              source:   "api"                                     },
   free: {  },
   used: {  },
  total: {  }                                                        }
```
```
mbp:ccxt igorkroitor$ python examples/py/cli.py bitz fetch_balance
{'free': {},
 'info': {u'data': {u'btc_total': 0, u'cny': 0, u'info': [], u'usd': 0},
          u'microtime': u'0.54034000 1564672604',
          u'msg': u'',
          u'source': u'api',
          u'status': 200,
          u'time': 1564672604},
 'total': {},
 'used': {}}
mbp:ccxt igorkroitor$
```

I can't reproduce the issue without the code from the info you've provided. What's your version of CCXT?

**Comment by vxnuke** [comment]
@kroitor I am using ccxt version is about 1 month old
`
import os
import sys
import ccxt  # noqa: E402
id = sys.argv[1]  # get exchange id from command line arguments
# check if the exchange is supported by ccxt
exchange_found = id in ccxt.exchanges

exchange = getattr(ccxt, id)({
         #'proxy':'https://crossorigin.me/',
    })
exchange.apiKey = '',
exchange.secret = ''
balances = exchange.fetch_balance()
print(balances)
exit(0)
`

**Comment by kroitor** [comment]
@vxnuke you should enable the rate-limiter as required by the Manual: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

```
mbp:python igorkroitor$ python3 test-bitz-vxnuke.py bitz
```

```shell
{'info': {'status': 200, 'msg': '', 'data': {'cny': 0, 'usd': 0, 'btc_total': 0, 'info': []}, 'time': 1564673501, 'microtime': '0.97431900 1564673501', 'source': 'api'}, 'free': {}, 'used': {}, 'total': {}}
```

```
mbp:python igorkroitor$ cat test-bitz-vxnuke.py
```

```Python
import sys
import ccxt  # noqa: E402
id = sys.argv[1]  # get exchange id from command line arguments
# check if the exchange is supported by ccxt
exchange_found = id in ccxt.exchanges

exchange = getattr(ccxt, id)()
exchange.enableRateLimit = True
exchange.apiKey = '64f41d9a370acaef71110b96ed0e2fa8'
exchange.secret = 'T852ZETTEstkBbPAOaeHXzADXcMFCpfn5EsmjVYNdHg5xpfDJTNftOWCj24trbGm'
balances = exchange.fetch_balance()
print(balances)
```

If it doesn't work for you with my key and without a proxy, then this could be caused by your system clock. Let me know if it works or not this way. If it does work, then you might want to check your keys.

**Comment by kroitor** [comment]
> I am using python with ccxt version is about 1 month old.

@vxnuke that vague description does not really tell me too much, a `major.minor.patch` number would help ))

**Comment by vxnuke** [comment]
Version was 1.18.84 I updated to the latest version and it works sorry to waist your time.
