### ISSUE TITLE
[question] Bittrex restricted markets

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#5624]
- OS: linux
- Programming Language version: python 3.7.3
- CCXT version: NXT/BTC
- Exchange: bittrex
- Method: load_markets

When using load_markets with bittrex, the result contains a info section about "isRestricted".

Is this field a information, so this market may be restricted, or does this mean it's restricted for me? (depending on my IP or api keys)?

```python
import ccxt
ct = ccxt.bittrex()
lm = ct.load_markets()
res_list = [k for k,l in lm.items() if l['info']['IsRestricted']]
```

In my case, i get for example 'NXT/BTC' as one of the results.

When checking on the bittrex site (international - https://international.bittrex.com/Market/Index?MarketName=BTC-NXT) - i get the following at the bottom of the page:
`NXT can only be traded by non-US customers.`

I'm no US customer, so i guess the restriction does not apply to me - but is there a way to find this out through ccxt based on my API keys or similar?

**Comment by kroitor** [comment]
> Is this field a information, so this market may be restricted, or does this mean it's restricted for me? (depending on my IP or api keys)?

This is for information purposes, it is not about account restrictions, but about market restrictions.

> I'm no US customer, so i guess the restriction does not apply to me - but is there a way to find this out through ccxt based on my API keys or similar?

Your guess is correct. There is no way to restrict you from trading based on your API keys, that flag is fetched from a public endpoint (API keys are not involved at `loadMarkets` stage), so all users see the same `isRestricted` value.

However, Bittrex may restrict you from placing orders (`createOrder` will fail), if your IP or your country specified in your user account settings falls under their restriction.

Let us know if that does not answer the question.

**Comment by xmatthias** [comment]
It kind of confirms my suspicions.

Is there an additional (private?) endpoint for bittrex where "my" restrictions can be queried before trying to place an order, or is the only way to place an order and have it fail?

**Comment by kroitor** [comment]
> Is there an additional (private?) endpoint for bittrex where "my" restrictions can be queried before trying to place an order, 

Not that I know of.

> or is the only way to place an order and have it fail?

If you want to do this automatically – then, this is probably the only way currently.

See also:

- https://bittrex.zendesk.com/hc/en-us/articles/360001319332-Update-New-Terms-of-Service-Restricted-Locations-Section
- https://www.reddit.com/r/Bittrex/comments/ay1xqr/whats_up_with_bittrex_restricted_markets/
