### ISSUE TITLE
Question on using code PHP

### ISSUE THREAD

**Issue by StasToken** [ccxt/ccxt#5625]
Hello, I wildly apologize for my stupid question, I look at examples in the php language and I can’t find a method that unloads Japanese candles - im use _fetch_ohlcv_ - In the first case, I get something very similar to a candle, but the numbers that I see on the exchange on the chart in the last candle and the numbers that I get on api are different 

Tell me what method is needed to download a chart with Japanese candles? or is it not yet realized?

**Comment by kroitor** [comment]
@StasToken hey) Guess you've figured it out? )

**Comment by StasToken** [comment]
Yes, I just didn’t see right away that there’s a date for today yet he passed me the old quotes so it didn’t fit

**Comment by kroitor** [comment]
@StasToken ok, glad to know you've got it sorted out. Thx!
