### ISSUE TITLE
Fcoin unified transfer method

### ISSUE THREAD

**Issue by ibesora** [ccxt/ccxt#5626]
The [FCoin API](https://developer.fcoin.com/en.htm) shows methods to transfer to/from the [OTC account](https://developer.fcoin.com/en.html?javascript#otc) and from the [margin account](https://developer.fcoin.com/en.html?javascript#margin) but those are missing from the [exchange methods](https://github.com/ccxt/ccxt/blob/master/js/fcoin.js) in CCXT.
Do you plan on implement them or they are out of scope of the library?
Thanks!

**Comment by kroitor** [comment]
> Do you plan on implement them or they are out of scope of the library?

They are within the scope of the library. I've added the missing endpoints in version 1.18.1001\+:

- https://github.com/ccxt/ccxt/blob/master/js/fcoin.js#L92

We have plans on unifying the `transfer` method for moving funds within exchanges that support multiple accounts:

- https://github.com/ccxt/ccxt/pull/4806

Hope to add that feature very soon. In the meantime, you can still use the above endpoints by calling implicit API methods as described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

For example:

```Python
amount = YOUR_AMOUNT_HERE  # 1.23...
code = YOUR_CURRENCY_CODE  # BTC, ETH, ...
exchange.load_markets()
currency = exchange.currency(code)
exchange.private_post_broker_otc_assets_transfer_in({
    'amount': amount,
    'currency': currency['id'],
    'source_account_type': 'exchange',
    'target_account_type': 'otc',
})
```

Let us know if that does not help.
