### ISSUE TITLE
How to call implicit method without param key?

### ISSUE THREAD

**Issue by Jay54520** [ccxt/ccxt#5628]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version: Python
- CCXT version: 1.18.901
- Exchange: okex3
- Method: spot_post_batch_orders

> An implicit method takes a dictionary of parameters -- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

But this method's param is a json list without key. 

> End Certificate Request Sample
Limit Order: 2018-09-14T09:51:24.959ZPOST/api/spot/v3/batch_orders[{"client_oid":"ww20180728","instrument_id":"btc-usdt","side":"sell","type":"limit","size":"0.001","price":"10001","margin_trading ":"1"},{"client_oid":"w20180728","instrument_id":"btc-usdt","side":"sell","type":"limit","size":"0.001","price":"10002","margin_trading ":"1"}]

-- https://www.okex.com/docs/en/#spot-batch

**Comment by kroitor** [comment]
@Jay54520 we will add the support for arrays in `params` to `okex3` shortly.

**Comment by Jay54520** [comment]
@kroitor What can I do if I want to use the spot_post_batch_orders now?

**Comment by kroitor** [comment]
@Jay54520 we've added the support for arrays in `params`, so you should be able to pass the array to `params` and use the `spot_post_batch_orders` implicit call. This feature will be available as of CCXT 1.18.1019+ (the new build will arrive in 15 minutes or so). It will only work with spot markets (futures and swaps are not supported yet). 
Let us know if that does not help.
