### ISSUE TITLE
New fiat exchange emx.com

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5630]
https://docs.emx.com/?utm_source=share&utm_medium=ios_app#introduction

**Comment by jc-emx** [comment]
@kroitor  here is the github link: https://github.com/evermarkets/emx-python

if you have any question please email me: jchen@emx.com 
I will be the one who take care of EMX

**Comment by itxtoledo** [comment]
waiting for this

**Comment by ttodua** [comment]
Exchange is no longer available.
