### ISSUE TITLE
Load markets in bibox given timed out error

### ISSUE THREAD

**Issue by anbukarasi1** [ccxt/ccxt#5631]
const ccxt = require ('ccxt');
let bibox = new ccxt.bibox ({
  apiKey: '********',
  secret: '*******',
})
bibox.loadMarkets().then(() => {
 
}).catch((err) => {
 
 
});

Result:
1.Some times it given this issue,

TypeError: Cannot read property 'length' of undefined
    at bibox.fetchMarkets (/var/www/html/tradenbotnew/backend/node_modules/ccxt/js/bibox.js:149:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)

2.Some times it given,
timed out error.

Please respond this issue as soon as possible.

Thank you.

**Comment by anbukarasi1** [comment]
could you explain why added this issue as duplicate.

**Comment by kroitor** [comment]
@anbukarasi1

1. Add the necessary error handling: 

- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

2. Make sure you go through the troubleshooting section: 

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

3. Try a CORS proxy:

```
# https://github.com/ccxt/ccxt/wiki/Install#proxy
exchange.proxy = "https://cors-anywhere.herokuapp.com/"
exchange.origin = "bibox"
exchange.load_markets()
```

4. Make sure https://api.bibox.com/v1/mdata?cmd=marketAll is accessible

> could you explain why added this issue as duplicate.

Handling request timeouts and accessibility issues has been answered in the Manual and in the existing closed issues already. It does not depend on which exchange it is. Troubleshooting these things goes through the same procedures with practically any exchange.

Let us know if the above does not help.

**Comment by anbukarasi1** [comment]
In my location this link  https://api.bibox.com/v1/mdata?cmd=marketAll  is accessible.

I added this 'ccxt.exchange ({ 'verbose': true })'. but it does not given any response (success or failure).

**Comment by kroitor** [comment]
@anbukarasi1 try option 3:

```JavaScript
'use strict';
const ccxt = require ('ccxt')
const exchange = new ccxt.bibox ({
    apiKey: '********',
    secret: '*******',
    'proxy': 'https://cors-anywhere.herokuapp.com/',
    'origin': 'bibox',
    'verbose': true,
})
;(async () => {
    try {
        await bibox.loadMarkets()
        console.log ('Loaded markets succesfully')
    } catch (e) {
        console.log ('Failed to load markets')
    }
}) ()
```

> I added this 'ccxt.exchange ({ 'verbose': true })'. but it does not given any response (success or failure).

This is because your code above does not do anything in case of success or failure, both cases are handled silently.

Let us know if that does not help.

**Comment by anbukarasi1** [comment]
I tried this way,
'use strict';
const ccxt = require ('ccxt')

const bibox = new ccxt.bibox ({
    apiKey: '******',
    secret: '*****',
    proxy: 'https://cors-anywhere.herokuapp.com/',
    origin: 'bibox',
    verbose: true,
})
;(async () => {
    try {
        await bibox.loadMarkets()
        console.log ('Loaded markets succesfully')
    } catch (e) {
      console.log(e)
        console.log ('Failed to load markets:', e.constructor.name)
    }
}) ()

But it given this issue,
TypeError: Cannot read property 'length' of undefined
    at bibox.fetchMarkets (/.../node_modules/ccxt/js/bibox.js:149:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Failed to load markets: TypeError

**Comment by anbukarasi1** [comment]
Thank you so much for your reply.  it worked for me. thank you.

**Comment by anbukarasi1** [comment]
I tried this way,


'use strict';
const ccxt = require ('ccxt')

const bibox = new ccxt.bibox ({
    apiKey: '47a20c02d97c88bc7ac64956753edb50d27718f2',
    secret: 'ef6d4a20b1a7e3c7bd7612babb18977b5b1b8e2f',
    proxy: 'https://cors-anywhere.herokuapp.com/',
    origin: 'bibox',
    verbose: true,
})
;(async () => {
    try {
        await bibox.loadMarkets()
        console.log ('Loaded markets succesfully')
    } catch (e) {
      console.log(e)
        console.log ('Failed to load markets:', e.constructor.name)
    }
}) ()

But it throwing this error,

{ RequestTimeout: bibox POST https://cors-anywhere.herokuapp.com/https://api.bibox.com/v1/transfer request timed out (10000 ms)
    at timeout.catch (/var/www/html/tradenbotnew/backend/node_modules/ccxt/js/base/Exchange.js:419:27)
  constructor: [Function: RequestTimeout],
  name: 'RequestTimeout' }
Failed to load markets: RequestTimeout

**Comment by kroitor** [comment]
@anbukarasi1 you're not using the rate-limiter, so, you should also enable it according to the Manual: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

```JavaScript
const bibox = new ccxt.bibox ({
    apiKey: '',
    secret: '',
    proxy: 'https://cors-anywhere.herokuapp.com/',
    origin: 'bibox',
    verbose: true,
    enableRateLimit: true, // ←--------- add this
})
```
