### ISSUE TITLE
Binance create_order() timeInForce is overriden

### ISSUE THREAD

**Issue by WoK-E** [ccxt/ccxt#5632]
- OS: Any
- Programming Language version: Any
- CCXT version: 1.18.1008
- Exchange: Binance
- Method: create_order()

Binance accepts new orders with the parameter timeInForce set to IOC, FOK, or GTC.
create_order() correctly checks if the timeInForce parameter is required, but incorrectly sets it to defaultTimeInForce (that is set in the options), even if timeInForce is passed to create_order() in the params array.
Furthermore, if timeInForce is not required, the value passed in the params array is ignored.

A modification is needed in order to take into account the value passed in params.

**Comment by frosty00** [comment]
```
        const response = await this[method] (this.extend (request, params));
```

Not sure what you mean, it seems to be extending the request with the params correctly here. Are you sure you provided a `timeInForce` argument to `createOrder` correctly?

**Comment by WoK-E** [comment]
@frosty you're right. Something was not working for me, check the code and somehow chose to misread the line you mention.
Closing the issue - Sorry
