### ISSUE TITLE
Deribit number of contracts

### ISSUE THREAD

**Issue by orikalinski** [ccxt/ccxt#5633]
- OS: 
- Programming Language version: Python3
- CCXT version: 1.18.846
- Exchange: Deribit
- Method: amount_to_precision

Hi,

Amount of contracts in Deribit should be multiple of 10 for BTC-X pairs while in fact the amount_to_precision return rounded 1 digit after the floating point.

**Comment by orikalinski** [comment]
```
                'precision': {
                    'amount': market['minTradeSize'],
                    'price': market['tickSize'],
                },
```

Should be changed to 

```
                'precision': {
                    'amount': market['minTradeAmount'],
                    'price': market['tickSize'],
                },
```

**Comment by kroitor** [comment]
@orikalinski we can only do this if we change the precisionMode to TICK_SIZE as was described here: https://github.com/ccxt/ccxt/issues/5642

**Comment by orikalinski** [comment]
Ofc, 
I should've mention the other ticket here.

**Comment by kroitor** [comment]
@orikalinski actually, on a second thought, we can't do that...

```
{           kind: "future",
                 baseCurrency: "BTC",
                     currency: "USD",
                 minTradeSize:  1,
               minTradeAmount:  10,
               instrumentName: "BTC-PERPETUAL",
                     isActive:  true,
                   settlement: "perpetual",
                      created: "2018-08-14 10:24:47 GMT",
                     tickSize:  0.5,
               pricePrecision:  1,
                   expiration: "3000-01-01 08:00:00 GMT",
                 contractSize:  10                        },
```

The problem is that precision is not related to min limits at all. We can't deduce one from another.

Both of the snippets above: https://github.com/ccxt/ccxt/issues/5633#issuecomment-518893163 would be an error in this case.

**Comment by orikalinski** [comment]
`contractSize:  10` at least it looks like this one appears on the important pairs
I'm not sure what the solution you're going to implement but at least we can use that attribute when it exists.

**Comment by orikalinski** [comment]
Maybe I'm the one missing here, but looks like the Deribit have some logic issues.
In my opinion it's make more sense to send the "amount" instead of the "quantity"
quantity gets multiply by the exchange (by 10) which is in my opinion not the desired behaviour.
I believe that the common usage is to choose how much USD you want to invest on this position.
in this case you should send amount. that's by the way the reason for all the issues I mentioned above. sending quantity instead of amount "helps" avoiding precision issues (basically hide the issue with the amount precision and therefore the TICK_SIZE also missed out, although the price to precision didn't work at any case).

What do you think? @kroitor

**Comment by kroitor** [comment]
> In my opinion it's make more sense to send the "amount" instead of the "quantity"

In unified terms, the createOrder `amount` argument is the amount of `base` asset you want to buy or sell. If you're buying or selling derivatives or contracts, you're specifying the number of contracts you want to buy or sell. This is how `amount` works (or _should work_) everywhere throughout CCXT.

**Comment by orikalinski** [comment]
I understand what you're saying about the unification, but yet, in my opinion, it has no sense to purchase contract of BTC/USD (BTC-PERPETUAL) which worth 10$ which by the way is not the cost in ccxt, or if you want to look at that as the price is 10$ per contract which is even more odd. I'm not saying we shouldn't keep it unified, but it's simply not straight forward and make it even more complex unification wise compare to other leverage exchanges.
I personally changed it to "deribit amount" in order to really unify that to other exchanges. I made it transparent to the programmer, kept it simple by saying that each "contract" worth 1 USD and in this case the cost is now turned to be indeed base amount * price which wasn't correct before.

**Comment by kroitor** [comment]
@orikalinski tbh, I'm not sure that I understand the issue from your description...
In general, the `amount` in `createOrder` is the amount of base asset you want to buy, right? If the base asset is a contract – then you're buying `amount` contracts. This is how `amount` works with `createOrder` with practically all exchanges in CCXT. It does not matter how much that contract is worth in this case (in other words, how the exchange defines the contract does not change the logic of `amount`). Plz, elaborate...

**Comment by kroitor** [comment]
I think most of the confusion comes from the fact that we mix the `amount` unified argument vs the `amount` request field interchangeably. We need to be very precise and specific on which `amount` we're talking about. Under `amount` above I mean argument of `createOrder`, not the value of the field that gets sent to the exchange.

**Comment by orikalinski** [comment]
Let's make it more simple. we'll take a use case.
Let's say I want to set 200$ of BTC-PERPETUAL in the exchange.
first, at the moment, I will have to set 20 contracts which is odd to someone that is not familiar with the exchange specifics (if we're trying to unify that). In addition to the fact that Deribit shows the 200$ in the exchange and not the number of contracts that you have.

I see no usage at all at using the `contract`, especially if you want to get the logic unified with other exchanges such as bitmex for example. just want to mention that you can choose whether you want to set `deribit amount ($ equivalent)` or `deribit quantity (number of contracts)`.

I hope I made my point clear enough.

**Comment by orikalinski** [comment]
![Screenshot from 2019-08-07 17-00-34](https://user-images.githubusercontent.com/18344939/62628937-e735a000-b934-11e9-9821-3ee58f64379e.png)

**Comment by kroitor** [comment]
@orikalinski technically, they do allow you to switch to BTC on the screenshot above ) But anyways, your point is clear now. Regarding the unification, I still think the `createOrder` `amount` argument should be a value in base assets. But, obviously, that is less convenient when it comes to trading contracts with Deribit, therefore we will add support for specifying `amount` via `params` that would cancel the `quantity` if specified. So, in general, you should be able to choose it in base or in quote. Hope to add that feature to Deribit shortly, will let you know when it's there.
