### ISSUE TITLE
[question] fetch_my_trades - type of "since" argument

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#5636]
- OS:  not relevant
- Programming Language version: python 3.7
- CCXT version: 1.18.1008
- Exchange: multiple
- Method: `fetch_my_trades`

What's the correct type for the "since" argument of fetch_my_trades? 
i don't see the type documented for most function arguments, and ccxt does not use typehints for python (i guess that would not work due to the transpiling).

``` python
from datetime import datetime, timedelta
since = (datetime.now() - timedelta(days=1)).timestamp() - 1000

> 1564981010.641477
```

Also, can this type depend on the exchange? (we've had this working with floats on Binance / Bittrex for months, but it seems to fail with KuCoin).

**Comment by kroitor** [comment]
@xmatthias it's an integer timestamp in milliseconds everywhere throughout the library:

- https://github.com/ccxt/ccxt/wiki/Manual#pagination

<img width="882" alt="Screen Shot 2019-08-06 at 08 39 20" src="https://user-images.githubusercontent.com/1294454/62513804-e95d0900-b825-11e9-956e-127ff717ea9e.png">

- https://github.com/ccxt/ccxt/wiki/Manual#date-based-pagination

<img width="921" alt="Screen Shot 2019-08-06 at 08 39 38" src="https://user-images.githubusercontent.com/1294454/62513786-dc401a00-b825-11e9-9a2b-925acb9d0977.png">

> Also, can this type depend on the exchange?

No, it should work with integer timestamp in milliseconds. If any other type works – that's a coincidence. The unified API expects all timestamps in milliseconds.

Let us know if that does not answer it.

**Comment by xmatthias** [comment]
Perfect, thanks for the quick response (somehow i did not find this in the documentation - sorry for that).
