### ISSUE TITLE
Bittrex fetchDeposits without currency returns pending

### ISSUE THREAD

**Issue by JSRossiter** [ccxt/ccxt#5639]
Thanks for quick Kraken fix, got another similar one.

`fetchDeposits` for Bittrex returns all statuses 'pending' unless you use a currency param.

**Comment by kroitor** [comment]
@JSRossiter can you plz post the **verbose** output? https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
