### ISSUE TITLE
Bitstamp requires destination tag for XRP. This is wrong and breaks withdrawals.

### ISSUE THREAD

**Issue by devsi** [ccxt/ccxt#5640]
- Programming Language version: All
- CCXT version: 1.18.1014
- Exchange: Bitstamp
- Method: withdraw

XRP only needs a destination tag if the user is withdrawing to an institution or custodial wallet. non-custodial wallets do not require it, and this check stops users withdrawing XRP to their own personal wallets.

Can this be skipped by just passing in a random value or something?

https://github.com/ccxt/ccxt/blob/master/js/bitstamp.js#L1014

```
        if (code === 'XRP') {
            if (tag !== undefined) {
                request['destination_tag'] = tag;
                query = this.omit (params, 'destination_tag');
            } else {
                throw new ExchangeError (this.id + ' withdraw() requires a destination_tag param for ' + code);
            }
        }
```

Thanks

**Comment by kroitor** [comment]
@devsi do you mean that we can completely omit `destination_tag`? Or should we submit it regardless, and use a random tag? Your help debugging it would be really appreciated!

**Comment by devsi** [comment]
My previous experience with Bitstamp directly is that you can entirely omit the destination tag if you wish. You have to be sure to provide one if you are withdrawing XRP to Binance for example. But I do not even need to include one when withdrawing to my Guarda Wallet.

**Comment by devsi** [comment]
Also confirmed that I can work around it by supplying an arbitrary value. Although probably not recommended. I use "1" as my tag and I can get it to work. Ideally though the tag is optional for XRP :)

**Comment by kroitor** [comment]
@devsi does it work without `destination_tag` ?

**Comment by devsi** [comment]
@kroitor yes, it does.

**Comment by kroitor** [comment]
@devsi will add a fix shortly, thx!
