### ISSUE TITLE
BitMEX fetchOHLCV timestamps close → open in CCXT 1.18.1015+

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#5641]
Hello dear CCXT users!

This issue is to announce that we have switched BitMEX `fetchOHLCV` from returning the `closed` timestamps to returning the `open` timestamps for each OHLCV candle.

This is in effect since CCXT version **1.18.1015+**

Related issue: https://github.com/ccxt/ccxt/issues/4446

Related PR: https://github.com/ccxt/ccxt/pull/5520

This is a breaking change. BitMEX will now return `open` timestamps by default. If you want to switch back to the `close` timestamps, please use the following option:

```Python
import ccxt
exchange = ccxt.bitmex({
    'options': {
        'fetchOHLCVOpenTimestamp': False,  # True by default
    }
})
```

Let us know if you have any questions!

**Comment by MedAymenF** [comment]
Thanks so much. My code will look much cleaner now!

**Comment by belzebalex** [comment]
Hello,

Can we consider that unified? Does the "timestamp" field refers to the open timestamp for all exchanges?

Thank you!

**Comment by kroitor** [comment]
@belzebalex hi!

> Can we consider that unified?

Yes.

> Does the "timestamp" field refers to the open timestamp for all exchanges?

Yes.
