### ISSUE TITLE
New Exchange: Bitpanda Exchange

### ISSUE THREAD

**Issue by cod3gen** [ccxt/ccxt#5645]
Just a notice, Bitpanda's Global Exchange is online

API Docs; https://developers.bitpanda.com/exchange/

**Comment by christiantrummer** [comment]
@cod3gen are you already actively working on this? otherwise bitpanda devs would also like to contribute

**Comment by cod3gen** [comment]
I am not working on this at least. Feel free to contribute :-)

**Comment by frosty00** [comment]
> @kroitor are you already actively working on this? otherwise bitpanda devs would also like to contribute

It is likely that @kroitor is busy building other things atm. If you would like the ccxt dev team to write the bitpanda API client implementation for you then please contact info@ccxt.trade )

**Comment by SqueezedLight** [comment]
Hi guys, anyone working on this one? Maybe @christiantrummer? Otherwise we are thinking about implementing it... Would be nice to have Bitpanda support ;)

**Comment by christiantrummer** [comment]
we forked the repo to implement our connector here: https://github.com/bitpanda-labs/ccxt
the python part is tested but the php part not
there is also one pull request waiting: https://github.com/bitpanda-labs/ccxt/pull/1

**Comment by SqueezedLight** [comment]
Thanks @christiantrummer for the quick info. We will definitely try that out ;)

**Comment by SqueezedLight** [comment]
@christiantrummer finally we found time for some tests. Unfortunately it seems we can't get pagination to work. A request of the form `https://api.exchange.bitpanda.com/public/v1/account/trades?from=2019-12-30T12%3A25%3A20.863Z&max_page_size=100` comes back with an error `INVALID_ACCOUNT_HISTORY_TO_TIME`
Are we missing something or did we run into a bug? The error is not documented, at least we couldn't find anything about it. If we omit the `from` parameter everything works fine.
We are a little lost here - can you help us out?

Thanks in advance

**Comment by sirinn** [comment]
Hi @SqueezedLight 

You are missing the `to` query parameter. The query logic is either none of them or both of them (from & to). We will update the documentation to better explain this logic.

Thanks for reaching out.

**Comment by sirinn** [comment]
Hey @SqueezedLight, where are you standing ? Is there something we can help you with ? Could we get a PR out from you soon so that we can collaborate or help out ? We will continue with the fork, so please if you found and bugs or issues make them public here or on the fork.

Thanks in advance.

**Comment by SqueezedLight** [comment]
@sirinn sorry for the late reply. We got everything working, thank you very much! I will definitely report back if i find any issues.

**Comment by sirinn** [comment]
@SqueezedLight could you please publish changes you made if you made some ? I have identified several issues (pagination, query parameters logic you pointed out and minor mappings). Which I will be working on next week and if you already fixed those it would help us make this available for everyone faster.

**Comment by Hubberthus** [comment]
Hi!
There is an undocumented error 'CANDLESTICKS_TIME_RANGE_TOO_BIG' when requesting candlestick data.
For '1m' timeframe I see the time range overflows after around 1 days, so as a workaround I've modified fetchOHLCV to download data per day in a loop, until it reaches the 'to' param.
Something similar could maybe implemented in a more sophisticated way.

I'm using it with freqtrade, and for the backtest the data downloading kind of tried to fetch loads of candlestick data in one call. :)

**Comment by sebnyc** [comment]
Hi team,
Congrats on the good work !

Any update regarding Bitpanda support ?

**Comment by kroitor** [comment]
@sebnyc hi! Bitpanda is already supported in CCXT!

**Comment by sebnyc** [comment]
@kroitor It looks to me that what is currently supported is "Bitpanda Pro". There is also a "Bitpanda platform" that seems to have a different set of APIs [here](https://developers.bitpanda.com/platform/).
I initially thought this issue was about this other platform, I might have misread it.
Anyway, are there any plans to support the other Bitpanda platform ?

**Comment by kroitor** [comment]
@sebnyc the Bitpanda platform is not an exchange API though, it is more like Coinbase (wallet) and Coinbase Pro (exchange) but we will look into adding the support for Bitpanda's platform as well.
