### ISSUE TITLE
New Exchange: Huobi DM

### ISSUE THREAD

**Issue by joyser** [ccxt/ccxt#5646]
According to the global volume monitor: https://ftx.com/volume-monitor, Huobi derivatives is now the second largest exchange in the world by trade volume. Maybe we should try to get it added soon? would be a great help.
thanks.

**Comment by joyser** [comment]
Hi guys, just wondering if there's any schedule or idea when Huobi DM might be added to ccxt? Its currently overtaken bitmex as the biggest volume traded of any exchange! Would be great to trade it, thanks for everything!

**Comment by STOpandthink** [comment]
Strongly second this request. My team has been using CCXT successfully for our Bitmex connection, but we've always been wondering if at some point we'll hit CCXT's limitations. Looks like that time is now, which is unfortunate.

**Comment by kroitor** [comment]
@STOpandthink you may want to check this out:

- https://github.com/ccxt/ccxt/issues/6332
- https://github.com/ccxt/ccxt/issues/6332#issuecomment-586626802

Also: https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar

We will get to the Huobi DM integration very soon.

**Comment by frosty00** [comment]
@STOpandthink 

No need to worry - we are releasing CCXT PRO soon also with Bitmex ws connections #56

**Comment by Kinzowa** [comment]
> @STOpandthink
> 
> No need to worry - we are releasing CCXT PRO soon also with Bitmex ws connections #56

Hello team, does it mean Huobi future and swap methods are available with CCXT Pro?
thanks!

**Comment by kroitor** [comment]
@Kinzowa not yet, we are working on it. It will be available in both CCXT and CCXT Pro.

**Comment by kroitor** [comment]
@Kinzowa Huobi Global is already available, though. However, it's a different API (different exchange from Huobi DM).

**Comment by ChenLi0830** [comment]
Hey @kroitor - any updates on this?

**Comment by sjyMystery** [comment]
Any Updates? I purchased the ccxt pro.

**Comment by kroitor** [comment]
@sjyMystery we hope to get it listed this month.

**Comment by sjyMystery** [comment]
> @sjyMystery we hope to get it listed this month.

This month is going to be ended, hoping that you are prepared to list it ;).

**Comment by warproxxx** [comment]
The reason for not adding this seems to be political. Huobi is the biggest and the most liquid derivatives exchange. It is a no brainer move to add support for it. 

And, adding support for trading in an exchange in python is not time-consuming. I was able to code one by looking at [this](https://github.com/huobiapi/Futures-Python-demo) in a couple of hours. For a team that is earning very well from subscriptions, the exchange can actually be added in the time the owner has spent responding and looking at posts like this.

And before you attack me, yes I have open-sourced what I have done [here](https://github.com/warproxxx/Huobi-Python). And no, I won't add support for it inside CCXT because CCXT is getting paid very well by their subscribers and it is the owner's duty/team's duty to add support for #1 liquid and heavily demanded exchange. My paid subscribers aren't requesting it. CCXT's are.

**Comment by kroitor** [comment]
@warproxxx CCXT is open-source and free for the users. No subscription is required to use it.

**Comment by gebrits** [comment]
Friendly ping: any schedule for Huobi DM?

**Comment by adamwirski** [comment]
Would also like to know if's scheduled for release soon.

**Comment by frosty00** [comment]
@adamwirski it is one of our priorities right now.

**Comment by shunjizhan** [comment]
Any estimated date for  Huobi DM to be out? Need it so bad!! Appreciate all the efforts : )

**Comment by kroitor** [comment]
@shunjizhan i'm already working on it, and hope to deliver it before the end of this month.

**Comment by 524119574** [comment]
Any update on this? Thanks!

**Comment by quantnik** [comment]
Hi guys.  Appreciate an update - huobi is huge, so its omission is painful.  Thanks also for your hard work.

**Comment by zlex7** [comment]
Any chance someone could update on the progress of this? Need to know whether to develop a standalone client - thanks!

**Comment by kroitor** [comment]
We had a delay due to OKEX v5 update, will get back to Huobi DM and will hopefully get it added in two weeks or so.

**Comment by X-Mars** [comment]
@kroitor  
Hi, 
Today is 13th day,  do you have good news about Huobi DM.
Thx for your work.

**Comment by zlex7** [comment]
any update on this? it's been about three weeks and this is a time sensitive project

**Comment by ShakesB33r** [comment]
Hi ccxt team. We understand you are very busy, and you can't get to everything ASAP. Do you have any updated estimates for this project? Is it looking more like 1 month, 6 months, or unkown?

**Comment by kroitor** [comment]
@ShakesB33r we hope it's within 1 month.

**Comment by jornx** [comment]
Any update on  Huobi DM?

**Comment by kroitor** [comment]
Still working on it, Huobi DM, Bybit and Deribit are on our list of topmost priorities for RESTful/WS integrations right now. Pardon for the long wait.

**Comment by rianbowgift** [comment]
Are you done with huobi dm?

**Comment by 1key** [comment]
+1 for Huobi (pro) Derivates.
Any update on the ETA?

**Comment by kroitor** [comment]
@1key @rianbowgift we hope to deliver the support for Huobi derivatives within a week or so. Thanks for your patience!

**Comment by kroitor** [comment]
The support for Huobi Derivatives was added in CCXT 1.66.16+.
