### ISSUE TITLE
Fcoin missing method

### ISSUE THREAD

**Issue by ibesora** [ccxt/ccxt#5648]
The chinese version of the FCoin documentation talks about an [endpoint](https://developer.fcoin.com/zh.html#a266e284f4) that's not in the english version.

CCXT is using the https://api.fcoin.com/v2/public/symbols endpoint instead of the recommended https://www.fcoin.com/openapi/v2/symbols that gives a lot more information on the symbols.

Can you please change it?
Thanks!

**Comment by kroitor** [comment]
This feature was added as of CCXT 1.18.1036.

Both `fcoin` and `fcoinjp` will now use https://www.fcoin.com/openapi/v2/symbols by default. However, this is made optional and users who want the old behavior can switch back like so:

```Python
exchange = ccxt.fcoin({
    'options': {
        # use https://api.fcoin.com/v2/public/symbols
        'fetchMarketsMethod': 'fetch_markets_from_api',
        # use https://www.fcoin.com/openapi/v2/symbols (default)
        # 'fetchMarketsMethod': 'fetch_markets_from_open_api'
    },
})
```
