### ISSUE TITLE
FCoin (more) missing methods

### ISSUE THREAD

**Issue by ibesora** [ccxt/ccxt#5649]
Sorry for the double issues but I'm finding some problems as I go.
There are two missing methods related to the transfer of funds between accounts: 
* [assets/accounts/assets-to-spot](https://developer.fcoin.com/zh.html#a716ef8f2b) : To transfer funds from the wallet to the trading account
* [accounts/spot-to-assets](https://developer.fcoin.com/zh.html#6dceb6c8bc) : To transfer funds from the trading account to the wallet

Notice that the second endpoint is missing the *assets* path. I don't know if that's a problem with the documentation or if it's really like this.

**Comment by cod3gen** [comment]
CCXT needs unification of this function which it does not have currently. I know @kroitor is working on something there.

I do *think* you can use manual overrides in order to access these end points..... 

Related to #4806

**Comment by cod3gen** [comment]
Similiar issue was issued a couple days ago too: #5626

**Comment by ibesora** [comment]
Correct me if I'm wrong but as I understand, in order to use the implicit methods, those should be defined on the api property of the exchange but those are not there. 
Issue #5626, which I also opened, was closed after adding the missing endpoints to the api property.

**Comment by kroitor** [comment]
@cod3gen 

> I know @kroitor is working on something there.

Yep, we hope to add that feature shortly.

@ibesora 

> those should be defined on the api property of the exchange but those are not there.

You're absolutely right, we will add the missing endpoints asap. Your PRs are welcome, btw: 


- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes
