### ISSUE TITLE
"Filter" Errors

### ISSUE THREAD

**Issue by Tezeug** [ccxt/ccxt#5651]
- OS: Kubuntu 19.04 64-bit
- Programming Language version: Python 3.7.3
- CCXT version: 1.18.1035
- Exchange: Deribit
- Method: error handling

Hello. This is not an issue but a question and maybe a bit about just the Python itself. I would like to "filter" the error and print messages according to it. I have tried several "options" but I has not been successful. It has usually printed a traceback saying TypeError: 'some error code' object is not iterable and such. Can you help me? Thanks.

I have tried e. g.:

```Python
try:
...
except ccxt.BaseError as Error:
    for code in Error:
        if (code == 10004): 
            print (...)
```

**Comment by frosty00** [comment]
This feature is coming soon:

https://github.com/ccxt/ccxt/pull/5494

**Comment by Tezeug** [comment]
Nice. Let me know then down below. Thank you.

**Comment by kroitor** [comment]
@Tezeug please "Subscribe" to #5494 in order to get the merge notification.

**Comment by Tezeug** [comment]
I should have been subscribed.
