### ISSUE TITLE
ItBit auth error with signature (Python)

### ISSUE THREAD

**Issue by evgen-y2k** [ccxt/ccxt#5653]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: ubuntu 18.04
- Programming Language version: Python 3.6
- CCXT version: 1.18.1036
- Exchange: ItBit
- Method: fetch_balance()

Hello.
I try do this:

mk = ccxt.itbit(
                {
                    "apiKey": API_KEY['ITBIT']['KEY'],
                    "secret": API_KEY['ITBIT']['SECRET'],
                    "uid": API_KEY['ITBIT']['USER_ID'],
                    "verbose": True,
                    "timeout": 30000
                }
            )
mk.enableRateLimit = True
mk.load_markets()
res = mk.fetch_balance()
print(res)

In the result I see error:

Traceback (most recent call last):
  File "/home/jo/uwork/arbitrage/bot/bot.py", line 135, in <module>
    print(itbit.get_balance())
  File "/home/jo/uwork/arbitrage/bot/bot.py", line 35, in get_balance
    res = self.mk.fetch_balance()
  File "/usr/local/lib/python3.6/dist-packages/ccxt/itbit.py", line 370, in fetch_balance
    response = self.fetch_wallets(params)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/itbit.py", line 389, in fetch_wallets
    return self.privateGetWallets(self.extend(request, params))
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 432, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/itbit.py", line 528, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 450, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/itbit.py", line 519, in sign
    'Authorization': self.apiKey + ':' + signature,
TypeError: must be str, not bytes

What I made not correct? Help me please

**Comment by frosty00** [comment]
what is the output of `API_KEY['ITBIT']['KEY']`?

**Comment by evgen-y2k** [comment]
API_KEY = {'ITBIT': {'KEY': '', 'SECRET': '', 'USER_ID': ''}, 'BX': {'KEY': '', 'SECRET': ''}}

**Comment by kroitor** [comment]
@evgen-y2k what is the `type(API_KEY['ITBIT']['KEY'])` ?

**Comment by kroitor** [comment]
@evgen-y2k let us know if you still have the same issue with 1.18.1037 (it will arrive in 15 minutes). Thx!

**Comment by evgen-y2k** [comment]
> what is the type(API_KEY['ITBIT']['KEY']) ? Is it string or bytes ?
String

**Comment by kroitor** [comment]
@evgen-y2k ok, thx, we will be happy if you report back whether 1.18.1037 solves the issue for you or not.

**Comment by evgen-y2k** [comment]
Thank you! Updated CCXT works correctly.
