### ISSUE TITLE
how to get the list of exchanges names along with logos 

### ISSUE THREAD

**Issue by nettemsarath** [ccxt/ccxt#5657]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

i dont want to do web scraping or something ... , it will be very good if ccxt implements exchange names along with logos url's

**Comment by nettemsarath** [comment]
how to get the list of exchanges names along with logos , i dont want to do web scraping or something ... , it will be very good if ccxt implements exchange names along with image url's

**Comment by kroitor** [comment]
@nettemsarath this is already supported here: 

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

```JavaScript
const ccxt = require ('ccxt')
const exchangeIds = ccxt.exchanges
console.log (exchangeIds) ←------------ print a list of exchange ids

const id = 'binance' // ←-------- or instantiate them in a loop
const exchange = new ccxt[id] ()
console.log (id)
console.log (exchange.urls) // ←------------ print the URLs to the logos
console.log (exchange.name) // ←---------- print the exchange name
```
