### ISSUE TITLE
About cancellation of orders

### ISSUE THREAD

**Issue by gavin369** [ccxt/ccxt#566]
How to find the hang order? How else to cancel the order?

**Comment by gavin369** [comment]
How to write code?

**Comment by gavin369** [comment]
await huobipro.******？  Can you give me an example? Thanks！

**Comment by kroitor** [comment]
@gavin369 can you put your question in a few more words, please? Which langua

> How to find the hang order?

If your order request failed with unknown order status, you can check your open / closed orders (where implemented) like so:

```
await exchange.fetchOrders (symbol, params)
// or
await exchange.fetchClosedOrders (symbol, params)
await exchange.fetchOpenOrders (symbol, params)
```

But for now, the above method is not implemented for HuobiPro (it will be soon, see more about it here: #71). In the meantime you can use their custom API for fetching orders:

```
await exchange.loadMarkets ()
await exchange.privateGetOrderOrders ({
    'symbol': exchange.markets['ETH/BTC'].id
    'states': [
        'pre-submitted',
        'submitted',
        'partial-filled',
        'partial-canceled',
        'filled',
        'canceled',
    ].join (',')
})
```

> How else to cancel the order?

```
await exchange.cancelOrder (orderId)
```

> How to write code?

Uhm... Sorry?

**Comment by gavin369** [comment]
Okay，i know

**Comment by kroitor** [comment]
Okay ) I would close this for now if you don't mind.
