### ISSUE TITLE
What is the reasoning behind ccxt fetching exchange info before fetchOrderBook?

### ISSUE THREAD

**Issue by karlandoh** [ccxt/ccxt#5661]
- OS: Linux
- Programming Language version: Python 3.7.0
- CCXT version: 1.18.1039
- Exchange: All (Using binance as an example)
- Method: fetchOrderBook
```
ccxt.binance({'verbose': True}).fetchOrderBook('ETH/BTC')

(It submits this request before the depth page!)

Request: GET https://api.binance.com/api/v1/exchangeInfo {'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} None
Response: GET https://api.binance.com/api/v1/exchangeInfo 200 ... **full response intentionally omitted by me.**

(My desired information)

Request: GET https://api.binance.com/api/v1/depth?symbol=ETHBTC {'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} None
Response: GET https://api.binance.com/api/v1/depth?symbol=ETHBTC 200 ... **full response intentionally omitted by me.**
```

It seems as if the **exchange info page is obtained before the order book.** Is there a reasoning behind this?

**NOTE**: I have also noticed that subsequent requests do NOT access the exchanges info page prior. Is this to establish a session or for cookie purposes?

**REASONING:** I would like to find a way to prevent the exchange from executing "LOAD_MARKETS()" before any type of request. I would like to add market info at my own discretion.

Thanks!

**Comment by kroitor** [comment]
@karlandoh as documented in the Manual, you can call `loadMarkets` at your discretion once, prior to doing other calls, and it will only load the markets once, without reloading them upon each call to `fetchOrderBook`.

- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
