### ISSUE TITLE
i am sorry, can you make indodax java netbeans API?

### ISSUE THREAD

**Issue by TheDhafi** [ccxt/ccxt#5662]
[OTT] can you change the PHP code on Indodax API to java netbeans code, iam need it to make a bot and combine with another exchange,I have searched everywhere and always get error, the php using curl_setopt to connect on indodax, but how to connect on java, can you explain me, thank you

**Comment by kroitor** [comment]
@TheDhafi sorry, but this repository currently does not support Java, we support JavaScript, Python and PHP: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
