### ISSUE TITLE
ImportError: No module named 'ccxt.base'; 'ccxt' is not a package

### ISSUE THREAD

**Issue by esteban2006** [ccxt/ccxt#5663]
I have two files Main.py and fetchdata.py

fetchdata.py contains all the methods that ccxt provides for the exchange, when I when  I run the script in fetchdata, the script runs successfully, allowing me access to my account within the exchange, but when I am run the Main.py script and  import fetchdata then the python interpreter throws the following error:  

from ccxt.base.exchange import Exchange
ImportError: No module named 'ccxt.base'; 'ccxt' is not a package

I have tried to manually append the sys path to the dir, but still the same error, 

Could you please give me any advice ?

- OS:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

- Programming Language version:
python 3.5.2
- CCXT version: 1.18.87
- Exchange:
Binance
- Method:
import ccx.base

**Comment by frosty00** [comment]
`import ccx.base`

it should be `ccxt.base`?

try:

```
Exchange = ccxt.Exchange()
```

**Comment by frosty00** [comment]
you have to run the code from inside the `ccxt/python` directory for ccxt.base to exist

**Comment by esteban2006** [comment]
thank you for the answer, @frosty00 

when you mention that I should run my code from inside the `ccxt/python` is this means that I should copy my project directory into `.../dist -packages/ccxt` ?

**Comment by kroitor** [comment]
@esteban2006 

> is this means that I should copy my project directory into `.../dist -packages/ccxt` ?

That means that you should not `import ccxt.base` at all. If you're not developing CCXT itself, and you develop a project that uses CCXT, then you should just `import ccxt` or `from ccxt import Exchange` instead.

**Comment by esteban2006** [comment]
thank you 

this is how i am importing the module 

```
import ccxt
binance = ccxt.binance()
```
I have also export the python path to ccxt this way:

`export PYTHONPATH=$PYTHONPATH:.../ccxt`

but it does not seem to work

**Comment by esteban2006** [comment]
Thank you for the answers, there is absolute nothing wrong with ccxt path or importing the module, I had created a copy of the exchange file from the ccxt module and NAMED it ccxt.py for study purposes (I forgot to remove it or rename it from the current directory), so python interpreter was reading this file instead of the correct ccxt module, I appreciate your time and effort.
