### ISSUE TITLE
Trouble Getting 'Token' for BitMex

### ISSUE THREAD

**Issue by hanyoonLDA** [ccxt/ccxt#5665]
- OS: Ubuntu 16
- Programming Language version: Python
- CCXT version: Latest
- Exchange: BitMex
- Method: user/confirmWithdrawal

Hi there! I'm having some difficulties trying to get confirmWithdrawal to work. The withdraw function to initiate the withdrawal works flawlessly, but I am getting stuck at confirmWithdrawal so I wouldn't have to confirm manually by email. I know that a 'token' string is required, so I assumed it meant a signature, which I generated by:

```
def generate_signature(secret, verb, url, expires, data):
    path = url

    if isinstance(data, (bytes, bytearray)):
        data = data.decode('utf8')

    print("Computing HMAC: %s" % verb + path + str(expires) + data)
    message = verb + path + str(expires) + data

    signature = hmac.new(bytes(secret, 'utf8'), bytes(message, 'utf8'), digestmod=hashlib.sha256).hexdigest()
    return signature
expires = int(round(time.time()) + 25)
token = generate_signature('<myprivatekey>', 'POST', '/api/v1/user/confirmWithdrawal', expires, '')
```
I receive a signature back, but I keep getting a 404 error, which I thought was a weird error to get back. Can someone please confirm that by 'token' they mean a signature? I have a pretty large affiliate account and would like to automate my affiliate payouts every morning automatically.

`confirm = bitmex.privatePostUserConfirmwithdrawal(params={'token' : token})`

Thanks!

**Comment by kroitor** [comment]
@hanyoonLDA 

> Can someone please confirm that by 'token' they mean a signature?

I think they mean a 2FA one-time password (OTP) under `token` here, not the signature.

**Comment by hanyoonLDA** [comment]
@kroitor The OTP token is already handled when initiating the withdrawal... Not sure why they would suddenly change from `otp-token` to just `token` -- And there is no token value sent to the email AFAIK, it's a link to a confirmation page. Hmm..

**Comment by kroitor** [comment]
>  And there is no token value sent to the email AFAIK, it's a link to a confirmation page. Hmm..

Yes, however, that link does contain the token you're looking for, as far as I understand:

![Screen-Shot-2019-08-12-at-16 00 08](https://user-images.githubusercontent.com/1294454/62866837-8a622d00-bd1a-11e9-870d-9f9792902c77.jpg)

**Comment by hanyoonLDA** [comment]
@kroitor ah, gotcha. So there's no way to automate this process strictly with CCXT. We'd have to go into email parsing, correct?

**Comment by kroitor** [comment]
@hanyoonLDA yep, for now reading the emails is beyond the CCXT (there are better packages for working with email). Thus you will need to combine CCXT with an email client (SMTP or POP) to automate it completely. Let us know if that does not help.
