### ISSUE TITLE
Do you have sample order/bulk

### ISSUE THREAD

**Issue by update123** [ccxt/ccxt#5666]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version: PHP
- CCXT version:1.18.1042
- Exchange:Bitmex
- Method:create_order

Hi Can you show an example of sending and editing bulk orders
`<?php

include "./ccxt/ccxt.php";

$bitmex = new \ccxt\bitmex(
    array (
        'apiKey' => 'xxxxxxxxxxxxxxxxxxxxx',
        'secret' => 'yyyyyyyyyyyyyyyyyyyyy',
        'enableRateLimit'=> True,
    )
);

$orders=[
    array (
        'symbol' => 'BTC/USD',
        'side' => 'buy',
        'orderQty' => 100,
        'ordType' => 'limit',
        'price'=>10000

    ),
    array (
        'symbol' => 'BTC/USD',
        'side' => 'buy',
        'orderQty' => 100,
        'ordType' => 'limit',
        'price'=>9500

    ),
    array (
        'symbol' => 'BTC/USD',
        'side' => 'buy',
        'orderQty' => 100,
        'ordType' => 'limit',
        'price'=>9000
    )
];

$result=$bitmex->create_order('BTC/USD', 'limit', 'buy', 100, 10000);

echo "<pre>";
var_dump($result);
echo "<pre>";
`

**Comment by kroitor** [comment]
Hi! See here: https://github.com/ccxt/ccxt/issues/4411#issuecomment-450711552

**Comment by update123** [comment]
ı dont see this function (private_post_order_bulk and private_put_order_bulk)
<img width="658" alt="Ekran Resmi 2019-08-11 17 11 02" src="https://user-images.githubusercontent.com/2678134/62834972-da2def00-bc5b-11e9-85ef-b922ebf51a3c.png">

**Comment by kroitor** [comment]
@update123 plz read the manual: 

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#implicit-api-methods

**Comment by update123** [comment]
Perfect working thanks. I will make a small donation for you.
