### ISSUE TITLE
ccxt hangs when liqui times out

### ISSUE THREAD

**Issue by kvz** [ccxt/ccxt#567]
Hi, I've seen the following behavior in Node.js:

- Normal execution when exchanges are swift
- Failure to execute callbacks when exchanges time out. Example:

```
Wallet: Error during Liqui/fetchBalance: Error: liqui POST https://api.liqui.io/tapi request timed out (10000 ms)
(node:16154) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error during Liqui/fetchBalance: Error: liqui POST https://api.liqui.io/tapi request timed out (10000 ms)
(node:16154) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[ ... callback never called ..., my program now hangs indefinitely with no more actions performed (i let it running for minutes before aborting) ]
```

**Comment by kroitor** [comment]
@kvz seems that you're not catching / not handling the exceptions (UnhandledPromiseRejectionWarning), therefore your code hangs. Can you post a shortened snippet of how you issue your calls ?

**Comment by kvz** [comment]
This is the full methods that handles it:

```
  async fetchBalance (cb) {
    this._info(`fetchBalance ...`)

    try {
      let res = await this._client.fetchBalance()

      // filter to only match useful coin combinations
      this.balance = _.pickBy(res, (coinBalance, key) => {
        coinBalance.symbol = key
        coinBalance.exchange = this.constructor.name
        return coinBalance.total > 0
      })

      this._info(`fetchBalance ... done`)
      return cb(null, this.balance)
    } catch (err) {
      this._info(`fetchBalance ... done`)
      return cb(err)
    }
  }
```

async await is a bit new to me, and i'm plugging it into a 'legacy' app that still uses callbacks. but i thought this should cover everything?

**Comment by kroitor** [comment]
@kvz it depends on how you call the above method, can you show the code that wraps the call to your fetchBalance (cb) ?

**Comment by kvz** [comment]
That looks like so:

```
  _allExchangesFetchBalance (cb) {
    let mainErr = null
    let resultSets = {}
    let q = async.queue((name, next) => {
      this._exchanges[name].fetchBalance((err, result) => {
        if (err && !mainErr) {
          mainErr = `Error during ${name}/fetchBalance: ${err}`
          return next()
        }

        if (result && (Object.keys(result).length > 0 || result.constructor !== Object)) {
          resultSets[name] = result
        }

        next()
      })
    }, 8)

    q.drain = () => {
      return cb(mainErr, resultSets)
    }

    q.push(Object.keys(this._exchanges))
  }
```

Although I was under the impression that the `try/catch` should have caught any error and now I'm free to bubble it up using callbacks? In this case, I only care about the first error, save that in `mainError`, and bubble that up.

**Comment by kroitor** [comment]
@kvz 

You're not awaiting your async fetchBalance call here:

```
    let q = async.queue((name, next) => {
      this._exchanges[name].fetchBalance((err, result) => {
```

I believe this should be:

```
    let q = async.queue(async (name, next) => {
      await this._exchanges[name].fetchBalance((err, result) => {
```

Does it still fail with those two lines edited that way?

**Comment by kvz** [comment]
Then the program stops very quickly. I think it's because no promise is returned by `fetchBalance` so it can't be awaited. But i'd think that since i 'terminate' via try & await inside `fetchBalance`, and then use old fashioned callbacks upwards, i should not need any awaits higher up. The transaction is done still inside fetchBalance. Is it possible an error isn't caught upon timeout deeper down the rabbit hole?

**Comment by kroitor** [comment]
@kvz the error is actually caught and reported from your callback, as it should, it is present in your output:

```
Wallet: Error during Liqui/fetchBalance: Error: liqui POST https://api.liqui.io/tapi request timed out (10000 ms)
```

↑ that line is output by your callback ↓
```
mainErr = `Error during ${name}/fetchBalance: ${err}`
```

So, from the above answer, you can see that the exception is actually tried and thrown properly from ccxt, catched and then passed into your callback, and then it is output from there. But for some reason your fetchBalance wrapper catches the same error. It does not look like a ccxt-internal issue. The error comes from a messy async framework wrapping and from the way async-framework handles errors (in a very specific fashion). From their docs:

![screen-shot-2017-11-14-at-13 47 13](https://user-images.githubusercontent.com/1294454/32776120-9ca67778-c942-11e7-9c55-0846aeef9637.jpg)

From the above I can carry that this is likely an async-framework-usage-specific issue.

There's a much easier way to fetch all balances at once with Promises, I'd recommend switching to a modern syntax.

**Comment by kvz** [comment]
Okay I'll do more digging. Thanks for the thoroughness!

**Comment by kroitor** [comment]
@kvz try this:

```
_allExchangesFetchBalance (cb) {
    let mainErr = null
    let resultSets = {}
    let q = async.queue((name, next) => {
      this._exchanges[name].fetchBalance((err, result) => {
        if (err && !mainErr) {
          mainErr = `Error during ${name}/fetchBalance: ${err}`
          return next()
        }

        if (result && (Object.keys(result).length > 0 || result.constructor !== Object)) {
          resultSets[name] = result
        }

        next()
      })
    }, 8)

    q.drain = () => {
      return cb(mainErr, resultSets)
    }

    q.push(Object.keys(this._exchanges), 1, (err) => {
        console.log ('This method is called when the task of fetching balance fails with an error: ', err)
    })
  }
```

**Comment by kvz** [comment]
Hey I didn't know about push supporting callbacks too, thanks a lot! 💯

**Comment by kvz** [comment]
Was able to fix all the issues here thanks to your help. cctx was not to blame! 🥇
