### ISSUE TITLE
bleutrade create_order broken

### ISSUE THREAD

**Issue by alexsith** [ccxt/ccxt#5670]
After update bittrex api, bleutrade create_order was broken:

    ret = await self._ccxtexchange.create_order(symbol, type, side, amount, price, params)
  File "/Users/user/Documents/Bitcoin/ccxt/async_support/bittrex.py", line 615, in create_order
    orderId = self.safe_string(response['result'], orderIdField)

TypeError: string indices must be integers

- Programming Language version: python
- CCXT version: 1.18.1043
- Exchange: bleutrade
- Method: create_order

**Comment by kroitor** [comment]
@alexsith can you plz paste the verbose request/response?

```Python
self._ccxtexchange.verbose = True
ret = await self._ccxtexchange.create_order(symbol, type, side, amount, price, params)
```

?

**Comment by alexsith** [comment]
Request: GET https://bleutrade.com/api/v2/market/getbuylimit?market=BTC_USDT&quantity=0.00498753&rate=1000 None None

Response: GET https://bleutrade.com/api/v2/market/getbuylimit?market=BTC_USDT&quantity=0.00498753&rate=1000 200 <CIMultiDictProxy('Date': 'Mon, 12 Aug 2019 11:06:35 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'X-Powered-By': 'PHP/7.2.13', 'X-UA-Compatible': 'IE=edge', 'Link': '<https://bleutrade.com/wp-json/>; rel="https://api.w.org/", <https://bleutrade.com/>; rel=shortlink', 'X-Frame-Options': 'SAMEORIGIN', 'X-Mod-Pagespeed': '1.13.35.2-0', 'Vary': 'Accept-Encoding', 'Cache-Control': 'max-age=0, no-cache, s-maxage=10', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '5051fb0e9e0d97d2-FRA', 'Content-Encoding': 'gzip')> <!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="UTF-8">
<title>Bleutrade Cryptocurrency Exchange | Bleutrade. Your Cryptoplace to Trade</title>
<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="description" content="Bleutrade is Your Cryptoplace to Trade | Bleutrade is the ideal cryptoplace where you buy and sell cryptocurrency in a reliable, intuitive and easy way." />
.....

**Comment by kroitor** [comment]
@alexsith thx! We will rework bleutrade to will untie it from bittrex and will get back to you asap.
