### ISSUE TITLE
OKex3 SWAP contract fetchOrderBook not working.

### ISSUE THREAD

**Issue by joyser** [ccxt/ccxt#5672]
I'm receiving an error when trying to pull the order book for OKex SWAP contracts. The same Okex3 exchange object works for futures and spot.

I'm running the following code in javacsript:

```javascript
okex3 = new ccxt.okex3({proxy:'https://cors-anywhere.herokuapp.com/'})
				
orderBook = okex3.fetchOrderBook('BTC-USD-SWAP',1000)
```

And receive this error

> Uncaught (in promise) TypeError: this[method] is not a function

I guess it comes from here:
https://github.com/ccxt/ccxt/blob/a1d4770c7d4020c824127b6aa09c51daff3cc8c3/js/okex3.js#L716

But I can't seem to find where this function might be defined.

**Comment by kroitor** [comment]
@joyser thx for reporting! This is fixed in CCXT 1.18.1045+ (the new build will arrive in 15 minutes). We will be happy if you report back whether it did solve the issue for you or not.
