### ISSUE TITLE
avoiding dust attacks

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5676]
I've recently been a victim of several [dust attacks](https://cryptodaily.co.uk/2019/03/what-are-bitcoin-dust-attacks).  

I imagine that they have found my wallet addresses in the ccxt code base (as comments for example responses).  I wonder if we could start purging real address from code (and the git history) and replacing them with fake ones?

**Comment by kroitor** [comment]
> I wonder if we could start purging real address from code (and the git history) and replacing them with fake ones?

Sure! Will start cleaning it up.

**Comment by npomfret** [comment]
@kroitor thanks.

Would it be helpful if we create GitHub issues if we find one?

**Comment by kroitor** [comment]
@npomfret sure! And thx! Also, I could merge these edits very quickly (almost immediately) if you submit PRs via GitHub ;) Because most of them are one-liner edits, you don't even have to bother with syncing the repos, you can add those edits in a couple of clicks with GitHub's web editor.

**Comment by npomfret** [comment]
Sure, but I can't purge the history.

**Comment by kroitor** [comment]
@npomfret we can't really purge history on a public repo either, otherwise it will break all forks... so, i suggest that we remove the mentions from the existing codebase at the very least.

**Comment by npomfret** [comment]
The [BGF](https://help.github.com/en/articles/removing-sensitive-data-from-a-repository) tool allows you to replace text in files in the history.  Would that affect other forks?

**Comment by kroitor** [comment]
@npomfret yes, i'm afraid it will break the forks:

> the BFG Repo-Cleaner rewrite your repository's history, which changes the SHAs for existing commits that you alter and any dependent commits.
