### ISSUE TITLE
Kraken - fetch_trades not correctly passing "since" parameter

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#5677]
- OS: linux
- Programming Language version: python
- CCXT version:  ccxt-1.18.1046
- Exchange: kraken
- Method: fetch_trades

The below script shoudl get trades starting with June 1st.
It is working correctly for binance (for example) ... but not for kraken.

``` python
import ccxt
ct = ccxt.kraken()
ct.fetch_trades('ETH/BTC', since=1559347200000)
```

The trades gotten don't correspond to the passed "since" parameter.
according to [the kraken support page](https://support.kraken.com/hc/en-us/articles/218198197-How-to-pull-all-trade-data-using-the-Kraken-REST-API), the 

expected call should be: 
`https://api.kraken.com/0/public/Trades?pair=xbtusd&since=1559347200000000000`

Using `ct.verbose = True`, it's visible that it's not passed to the get parameters:
(response abbreviated for brevity)

```
Request: GET https://api.kraken.com/0/public/Trades?pair=XETHXXBT {'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.kraken.com/0/public/Trades?pair=XETHXXBT 200 {'Date': 'Tue, 13 Aug 2019 17:30:37 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d9a111226dbb686ca84c4f73a189586591565717436; expires=Wed, 12-Aug-20 17:30:36 GMT; path=/; domain=.kraken.com; HttpOnly', 'Cache-Control': 'public,max-age=1,smaxage=1', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Strict-Transport-Security': 'max-age=15768000', 'CF-Cache-Status': 'EXPIRED', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '505c6afb498bd608-MXP'} {"error":[],"result":{"XETHXXBT":[["0.018710","0.02700000",1565693821.4784,"s","l",""],["0.018720","3.32407204",1565693910.3449,"s","m",""],["0.018720","0.00663487",1565693910.3674,"s","m",""],["0.018720","0.00001324",1565693910.3703,"s","m",""],["0.018740","1.58709956",1565694028.6405,"b","l",""],["0.018740","2.75385044",1565694028.6487,"b","l",""],["0.018740","4.85345248",1565694103.1473,"b","m",""],["0.018750","4.25000000",1565694103.1541,"b","m",""],["0.018750","0.05600000",1565694103.1581,"b","m",""],["0.018750","10.00000000",1565694103.1614,"b","m",""],["0.018760","0.84054752",1565694103.1646,"b","m",""],["0.018760","2.00000000",1565694103.1781,"b","m",""],["0.018740","0.18700000",1565694117.2144,"s","l",""],["0.018740","0.02997495",1565694180.7045,"s","l",""],["0.018740","2.00000000",1565694187.1261,"s","m",""],["0.018730","0.19600000",1565694256.5765,"s","m",""],["0.018740","1.00000000",1565694428.146
...
```

**Comment by kroitor** [comment]
@xmatthias this is very interesting because here in their API docs we see that `since` is expected to be a trade id:

https://www.kraken.com/en-us/features/api#get-recent-trades

That id corresponds to `last id` (for id-based pagination, as explained here: )

This URL does work, however: https://api.kraken.com/0/public/Trades?pair=xbtusd&since=1559347200000000000. So, we will add the support for `since` to Kraken `fetchTrades` shortly.

**Comment by xmatthias** [comment]
Yes, i noticed the api documentation too ... - but the support page explains it quite extensively i think

https://support.kraken.com/hc/en-us/articles/218198197-How-to-pull-all-trade-data-using-the-Kraken-REST-API

however the id-based pagination did help me find a (temporary) workaround ... :+1:

**Comment by kroitor** [comment]
@xmatthias no worries, this has been added in 1.18.1047, it will arrive in 15 minutes or so.
