### ISSUE TITLE
fetch_open_orders not working in Bibox

### ISSUE THREAD

**Issue by mkang1234** [ccxt/ccxt#5679]
- OS: Windows
- Programming Language version: Python 
- CCXT version: 1.18.745
- Exchange: Bibox
- Method: fetch_open_orders

When I run the fetch_open_orders function, it craps out. I noticed that the api ping returns data but craps out when this line of code is called: 
return self.parse_orders(orders, market, since, limit)

In the parse_order function,  the following line of code is causing it to crap out. 
array = [self.extend(self.parse_order(order, market), params) for order in array]

Please help. Thanks.

**Comment by kroitor** [comment]
@mkang1234 

Can you please post the verbose request/response and the code to reproduce the issue (without your keys) ? Also, does this happen with the most recent version of CCXT?

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by mkang1234** [comment]
Here is my code and output. I tried using latest version and still didn't work. Thanks

def get_all_open_orders(self):
"""This function is used to get list of all open orders in the exchange"""
        try:
            raw_data = self.api.fetch_open_orders()
            print('Bibox open order raw data:', raw_data)
        except:
            print('Could not get all open orders from Binance exchange!!!!!!!!!!')

bib = Bibox(API_DATA.BIBOX_API_KEY, API_DATA.BIBOX_SECRET) 
print('CCXT version:' + ccxt.__version__)
bib.get_all_open_orders()
print(data)

Output:
CCXT version:1.18.1051
Could not get all open orders from Binance exchange!!!!!!!!!!

**Comment by mkang1234** [comment]
In function, fetch_open_orders,  I do see a response returning open orders as shown below. 
I noticed that it craps out in the parse_orders function in this line: 
array = [self.extend(self.parse_order(order, market), params) for order in array]


        response = self.privatePostOrderpending(request)
        print('response:', response)

response: {'result': {'count': 1, 'page': 1, 'items': [{'id': '12226569351192560', 'createdAt': 1565770627000, 'account_type': 0, 'pair': 'EOS_BTC', 'coin_symbol': 'EOS', 'currency_symbol': 'BTC', 'order_side': 2, 'order_type': 2, 'price': '0.00044400', 'deal_price': '0.00000000', 'amount': '2.9919', 'money': '0.00132840', 'deal_amount': '0.0000', 'deal_percent': '0.00%', 'deal_money': '0.00000000', 'status': 1, 'unexecuted': '2.9919',
'order_from': 1}]}, 'cmd': 'orderpending/orderPendingList'}

**Comment by kroitor** [comment]
Can you add proper error handling as described in the Manual?

- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

Unfortunately, when you say _"craps out"_ it's not clear what exactly is wrong.

I suggest the following test snippet:

```Python
import ccxt
exchange = ccxt.bibox ({
    "apiKey": "YOUR_API_KEY",
    "secret": "YOUR_API_SECRET,
    "password": "YOUR_API_PASSWORD",
})

try:
    exchange.load_markets()  # ←--------------- load markets first
    exchange.verbose = True  # ←--------------- add this after load_markets()
    orders = exchange.fetch_open_orders()  # ←----- fetch the orders and print verbose output
    print('Bibox open order raw data:', orders)
except Exception as e:
    print(type(e).__name__, e.args)  # ←------- print the exception details instead of "craps out"
```

↑ Can you check if the above snippet works (with your API credentials) ? If not, it would be great if you could post the entire output of that script, including the verbose info (without your keys) and the exception info, if any.

**Comment by mkang1234** [comment]
It seems to work now. Noticed that I need to call load_markets first.  Do I have to call load_markets() every time before calling fetch_open_orders()?  Thank you!

**Comment by kroitor** [comment]
> Do I have to call load_markets() every time before calling fetch_open_orders()?

No, it should be called for you upon your first call to a unified method, like `fetch_open_orders()`. However, it was missing in the bibox implementation, so i fixed it and your snippet should work normally after upgrading to 1.18.1052 (without having to load them manually). We will be happy if you report back whether it does solve the issue for you or not. Thx!

**Comment by mkang1234** [comment]
I upgraded to 1.18.1052 and works now. Thank you!!

**Comment by kroitor** [comment]
@mkang1234 awesome, thx for reporting! Let us know if you have any other difficulties with it.
