### ISSUE TITLE
while loop doesn't transpile correctly

### ISSUE THREAD

**Issue by xCuri0** [ccxt/ccxt#5680]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Arch
- Programming Language version: Python 3.7
- CCXT version: latest from git
- Exchange:
- Method:

Trying to add support for downloading full historical data on binance and doing that requires a while loop which the transpiler doesnt transpile correctly

**Comment by kroitor** [comment]
@xCuri0 we don't really need a while loop, we've been able to get away using `for` instead ) Can you post a snippet of code you're working on?

**Comment by xCuri0** [comment]
@kroitor 
```
        while (true) {
            const response = await this.publicGetKlines (this.extend (request, params));
            const rl = response.length;
            finalresponse.extend (response);
            if (limit !== undefined) {
                if (rl !== limit) {
                    break;
                }
            } else {
                if (rl !== 500) {
                    break;
                }
            }
            request['startTime'] = response[-1][0] + 1;
        }
```
i can probably just use ```for (;;)``` instead

**Comment by kroitor** [comment]
@xCuri0 we should not issue more than one HTTP request per unified call, really. If you want to load all candles by issuing one request after another, then you should probably do this in userland. 

> i can probably just use for (;;) instead

Nope, unfortunately. We don't really support infinite loops due to design considerations.

In this case, the loop has to be rewritten to make it transpileable:

```JavaScript
 // calculate (milliseconds() - since) and divide by the value result of parseTimeframe()
const howManyIterationsThereShouldBe = YOUR_VALUE;

for (let i = 0; i < howManyIterationsThereShouldBe; i++) {
const response = await this.publicGetKlines (this.extend (request, params));
    const rl = response.length;
    finalresponse.extend (response);
    if (limit !== undefined) {
        if (rl !== limit) {
            break;
        }
    } else {
        if (rl !== 500) {
            break;
        }
    }
    request['startTime'] = response[-1][0] + 1;
}
```

Let us know if that does not answer the question.
