### ISSUE TITLE
Poloniex order fees

### ISSUE THREAD

**Issue by stonemonk** [ccxt/ccxt#569]
fetch_order() on the poloniex service returns `'fee': None` and doesn't otherwise account for the fees.

Thus doing a buy/then sell gives an insufficient funds error from the exchange. Basically what I am doing is something like this:

```
uuid = polo.create_limit_buy_order("BCH/BTC", 0.00303204, rate)['id']
time.sleep(10)
order = polo.fetch_order(uuid)

# later on, sell it:
amount = order['filled']   # equals 0.00303204 as all was filled
polo.create_limit_sell_order("BCH/BTC", amount, rate)
```

When I sell, I get an insufficient funds error because I don't have that much because Polo deducts the fees in BCH after buying it.

I would need to sell `amount - fee`, but don't have access to fee.  Could you include it?

Really in addition to returning the fees, to me it would make more sense to directly include fields in the Order Structure that tell you how much you have as a result of the order. In the above example, I don't really have 0.00303204 units of BCH, I only have 0.00302446 as a result of the buy and thats all I care about. It would be nice if CCXT did the `filled - fee` calculation already otherwise I have to check fee structure and only deduct fee from filled if the fee currency is the destination one.  In other words, the only thing I really care about is **exactly** how much more BCH is in my account and **exactly** how much less BTC is in my account.

**Comment by kroitor** [comment]
@stonemonk it is included, you can calculate the fee before issuing the order:

```Python
polo.loadMarkets ()
type = 'limit'
side = 'sell'
takerOrMaker = 'taker' # or 'maker' if you are creating a market-making order
print(polo.calculate_fee (symbol, type, side, amount, price, takerOrMaker))
```

Does this help?

**Comment by stonemonk** [comment]
That doesn't really help because you don't know in advance if you are a maker or taker, things can change by the time your order reaches the exchange. It would also be pretty cumbersome to try to guess it in advance like that.

I really just want to know the fee I paid after the fact.  The manual says it returns a fee structure (https://github.com/ccxt/ccxt/wiki/Manual#order-structure), but it returns None.

**Comment by kroitor** [comment]
@stonemonk in other words, after you place the order, ccxt doesn't know if it's a maker or a taker, when it is closed. So you will HAVE TO manage maker-taker in userland.

**Comment by stonemonk** [comment]
returnOrderTrades tells you the fees per trade yes, but so you can figure out the full Order Structure from that aggregate information.

Its pretty ugly if my userland code has to have special casing and logic for working with ccxt only when the service is polo.

**Comment by kroitor** [comment]
> returnOrderTrades tells you the fees per trade yes, but so you can figure out the full Order Structure from that aggregate information.

No I can't, really, because I can't decide for the user when to send those requests. And the user doesn't want me to send multiple long-lasting request sequences blocking for more than one request per library call.

> Its pretty ugly if my userland code has to have special casing and logic for working with ccxt only when the service is polo.

Maybe, this will help: https://github.com/ccxt/ccxt/pull/102

**Comment by stonemonk** [comment]
> No I can't, really, because I can't decide for the user when to send those requests. And the user doesn't want me to send multiple long-lasting request sequences blocking for more than one request per library call, interfering with the rate limits for private calls, etc...

I don't understand this at all.  The user is calling ccxt's fetch_order(order_id) method, that should translate to poloniex's returnOrderTrades, not returnOpenOrders.  The user is asking for all info on a specific order, not about more vague info about all open orders.  You replace a single polo API call for another one.  Thats not any more long lasting nor blocking than returnOpenOrders is.

**Comment by kroitor** [comment]
> that should translate to poloniex's returnOrderTrades, not returnOpenOrders

not really, that should translate to the closest method of the order API

> you replace a single polo API call for another one

But, If we do that, we won't be able to return the total order volume of an open or partially filled order...

**Comment by kroitor** [comment]
@stonemonk what you say actually does make sense. I'm just having hard time figuring out a way of implementing it with a single REST call. Unless we rework the order cache for Poloniex into something different.

**Comment by stonemonk** [comment]
> But, If we do that, we won't be able to return the total order volume of an open or partially filled order...

You could just cache it from when the order was placed.

**Comment by kroitor** [comment]
@stonemonk in fact, we are caching the orders already. But the cache invalidation is currently based on fetchOpenOrders, as you noted previously. We can try implementing it the other way around, based on fetchOrderTrades... By the way, your help would also be really appreciated, we welcome your PRs and contributions if you feel like you want to give it a try.

**Comment by stonemonk** [comment]
I will be offline for next 2 weeks and then very busy the following 2 weeks, but if you haven't make progress on this issue by then,  maybe I can help.  I was just a bit hesitant because I haven't worked with JS in about 10 years so I am very rusty with it.

I just pulled up my old Polo code I wrote prior to using CCXT.  Indeed I was caching the total quantity from the original buy/sell request by returning it as part of the ID (My ID was a tuple to encode quantity and orderID, etc so I didn't have to cache it internally by the my Exchange class).

Additionally, I had found the only proper way to calculate the fee was to iterate each trade in the order, callulate the fee and **round it down to 8 decimal places**, then add them together. Example:

```
    def get_order(self, uuid):
        order_id = uuid[0]
        trades = self.service.returnOrderTrades(order_id)
        if trades:
            symbol = uuid[1]
            kind = uuid[2]
            quantity = uuid[3]
            total_price = Decimal(0)
            filled = Decimal(0)
            fee = Decimal(0)

            for trade in trades:
                assert trade["type"] == kind
                assert trade["currencyPair"] == symbol

                amount = Decimal(trade["amount"])
                total = Decimal(trade["total"])
                fee_percent = Decimal(trade["fee"])
                if kind == "buy":
                    fee += (fee_percent * amount).quantize(Decimal('.00000001'), rounding=ROUND_DOWN)
                else:
                    fee += (fee_percent * total).quantize(Decimal('.00000001'), rounding=ROUND_DOWN)
                total_price += total
                filled += amount

            info = {
                "unit_price": total_price / filled,
                "total_price": total_price,
                "total_quantity": quantity,
                "filled_quantity": filled,
                "resultant_quantity": filled - fee,
                "remaining_quantity": quantity - filled
            }
            
            return info
        return None
```

**Comment by kroitor** [comment]
Hello, @stonemonk ! Thx for the code snippet and for the hints on precision as well! We had the same difficulties with aligning precision for Kraken. We hope to rework this part of functionality for Poloniex asap.

**Comment by stonemonk** [comment]
Just to mention, on buy/sell, I was also rounding down the requested quantity to 8 decimals since this is what Polo does.  By doing so on my side, I can ensure that my `total_quantity` is the same that Poloniex's returnOpenOrder returns and also ensures that a successfully completed order's `filled_quantity == total_quantity` and that `remaining_quantity == 0`.

**Comment by kroitor** [comment]
> Also my reasoning for including quantity and other info in a tuple type uuid was not just to avoid an internal cache but also to allow the user to save this uuid tuple and use it after restarting my program (where an internal cache would have been lost and would need rebuilding). I dunno if something similar would be useful for CCXT.

We expose the order cache in `.orders` property of the exchange, so the user could save and reload the cache, if necessary. 

Thx for the feedback, we hope to update this functionality asap.

**Comment by nmiculinic** [comment]
I agree with @stonemonk; use two API calls if needed, but first, try to hit a cache via other calls (for open orders/trade history/etc.)

**Comment by kroitor** [comment]
@nmiculinic we are going to rework the cache to include trades as well, hopefully, very soon.

**Comment by nmiculinic** [comment]
As for multiple API  call, you may add option (in unified API for example), full/short which would tell you should you only make the most basic API call, or multiple API calls as needed.

**Comment by nkeilar** [comment]
+1 this is an issue for me.

**Comment by rubobaquero** [comment]
Hi kroitor. Also experienced the same problem.

After creating an order, i got the id 96878923218. If i wait 10 seconds and then try to fetch that order, I got this error: `order $id 96878923218 not found in cache`

Example code:
```
$order_made = $exchange->create_order("XRP/BTC", "limit", "buy", 50, 0.00001700);
sleep(10);
$order_loaded = $exchange->fetch_order($order_made["id"]);
```

Request made:
```
Array
(
    [0] => POST
    [1] => https://poloniex.com/tradingApi
    [2] => Array
        (
            [0] => Content-Type: application/x-www-form-urlencoded
            [1] => Key: XXXX
            [2] => Sign: XXXX
            [User-Agent] => ccxt/1.9.282 (+https://github.com/ccxt/ccxt) PHP/7.0.14
        )

    [3] => command=returnOpenOrders&currencyPair=all&nonce=1512909730730
)
```

**Comment by stonemonk** [comment]
@rubobaquero:  I've never seen that error so I don't think it's the issue I was reporting on this thread. Maybe you should make a separate ticket for it.

**Comment by stonemonk** [comment]
For the moment, I have worked around the fee issue by adapting my sample code above to my CCXT usage:

```
            order = service.fetch_order(orderId, symbol)
            if isinstance(service, poloniex):
                trades = service.fetch_order_trades(orderId)
                fee = Decimal("0")
                for trade in trades:
                    trade = trade["info"]
                    kind = trade["type"]

                    if kind == "buy":
                        amount = Decimal(trade["amount"])
                        fee_percent = Decimal(trade["fee"])
                        fee += (fee_percent * amount).quantize(Decimal('.00000001'), rounding=ROUND_DOWN)

                if fee > Decimal("0"):
                    order["fee"] = {
                        "currency": symbol.split("/")[0],
                        "cost": str(fee)
                    }
```

**Comment by rubobaquero** [comment]
@stonemonk , I have posted it here because you were talking about orders cache and calling the `returnOpenOrders` endpoint. So i suppose that it is related in some way.

**Comment by kroitor** [comment]
@rubobaquero your particular issue is explained here: https://github.com/ccxt/ccxt/issues/798#issuecomment-350416520... However, these issues are related, because both of them boil down to the underlying cache, which is being reworked right now to account for all of the above.
