### ISSUE TITLE
Binance withdraw() amount precision

### ISSUE THREAD

**Issue by devsi** [ccxt/ccxt#5690]
Hi @kroitor, so this is not something specifically to do with any exchange, but I found this particularly prominent with Binance. It's probably not considered an issue so go ahead and delete this if not.

I find that some exchanges don't give us any information on precision when it comes to withdrawal. They supply `amount`/`price` precision which directly relates to buying and the price you buy for.

Here is an example of Binance

**STEEM**
`amountprecision === 0`
`withdrawprecision === 3`

So it can only accept a whole number to buy, but it allows you to withdraw up to **3** decimal places. But no more than 3. Most of the time, after you factor in trade fees, the value you are left with is > 8 decimal places.

```
Buy -> 1650
After fees -> 1648.35981929
Withdraw -> ...1648.359......
```

So now I'm left with 0.00081929 that I'm unable to withdraw, and worse still my application throws an error because it does not know how to truncate it to **3** decimal places.

Any solution to this, or is it really a case of hard-coding the value for every single coin?

**Comment by devsi** [comment]
To make matters worse, every coin has it's own withdrawal precision

EOS buys to 2 decimals, withdraws to 4 decimals.
XLM buys to 0 decimals, withdraws to 7 decimals.

etc

**Comment by kroitor** [comment]
Hi @devsi ! Good to hear from you )

We've had a proposal on adding `wapiGetAssetDetail` endpoint, here: https://github.com/ccxt/ccxt/issues/5104... The two issues seem to be related. However, you're right, no information on withdrawal precision. So... it has to be reversed manually, by trial and error. Yet that trial and error code is not something we'd want to have in the lib, otherwise it will quickly turn into a mess, hope for your understanding.

**Comment by devsi** [comment]
Hi! Thanks :) I understand, we definitely shouldn't be writing code in to CCXT to handle a specific case like this. Especially as it requires a failed withdrawal to fetch the real fee.

So is this really only for Binance? Does this happen on other exchanges too? I would suspect it does as I've never seen an endpoint for withdrawal precision in CCXT. Most exchanges probably use the same precision as `amount` I would guess.

Maybe i'll try and contact Binance devs for a fix. There's nothing CCXT can do to fix it as if they don't supply the precision to us, there's no way to do it.

**Comment by kroitor** [comment]
> So is this really only for Binance? Does this happen on other exchanges too? I would suspect it does as I've never seen an endpoint for withdrawal precision in CCXT. Most exchanges probably use the same precision as amount I would guess.

Actually, many of them return that info from a standalone `currencies` endpoint:

- https://github.com/ccxt/ccxt/blob/master/js/kucoin.js#L279
- https://github.com/ccxt/ccxt/blob/master/js/anxpro.js#L558
- https://github.com/ccxt/ccxt/blob/master/js/braziliex.js#L159
- https://github.com/ccxt/ccxt/blob/master/js/buda.js#L217
- ...

Other exchanges either default to precision 8 or to token-specific precision rules, using `decimals` from underlying tokens and ERC contracts:

- https://eosio.stackexchange.com/questions/4305/what-is-the-smallest-unit-of-eos
- https://medium.com/@nuuneoi/knows-token-decimals-when-1-million-tokens-does-not-always-mean-there-is-only-1-million-tokens-d89c1a8c27ee

> Maybe i'll try and contact Binance devs for a fix. There's nothing CCXT can do to fix it as if they don't supply the precision to us, there's no way to do it.

Thx for your involvement! Feel free to reopen it or just ask further questions if you have more...

**Comment by devsi** [comment]
Amazing. At least some of them do give that info! Okay maybe I'll try and get that info from fetchCurrencies.

One of my fellow devs just did a little snooping at the API Binance itself uses on the withdraw page... it's undocumented and could be unstable, BUT:

https://www.binance.com/gateway-api/v1/public/asset/asset/get?asset=XLM
https://www.binance.com/gateway-api/v1/public/asset/asset/get?asset=STEEM
https://www.binance.com/gateway-api/v1/public/asset/asset/get?asset=EOS

That endpoint gives me the information in the `withdrawIntegerMultiple` key.

weird!

**Comment by kroitor** [comment]
> I'll try and get that info from fetchCurrencies.

Yep, note that currencies are preloaded with markets upon `loadMarkets` or upon your first call to the unified API (any `fetch*` method) – you should be able to access them via the `exchange.currencies` property. Let me know if anything.

**Comment by dmatora** [comment]
Calling fetchDepositWithdrawFee allows seeing withdraw precision for some exchanges (at least with kucoin and huobi)
Unfortunately I haven't found a way to get this for binance
