### ISSUE TITLE
Error Deploy JElastic

### ISSUE THREAD

**Issue by EmerF** [ccxt/ccxt#5692]
I getting some libs error when deploy a project with ccxt in JElastic NodeJS Server.
The server log is attached.
[nodejs.log](https://github.com/ccxt/ccxt/files/3507709/nodejs.log)

- OS: Ubuntu 
- Programming Language version: Typescript
- CCXT version: 1.18.1059
- Exchange: the app does not starts...
- Method:

**Comment by kroitor** [comment]
@EmerF how exactly do you deploy it, and which particular commands do you run?

**Comment by EmerF** [comment]
I do it automatically from my bitbucket repo. It don't need any specif commands. The JElastic Paas automatically runs the deploy.  NodeJS 10.0.0-npm enviroment.

**Comment by kroitor** [comment]
@EmerF unfortunately, i can't reproduce this on my system if I run `npm install ccxt` on my side... Here's the log with Node v10.0.0:

```
mbp:~ igorkroitor$ mkdir new_project
mbp:~ igorkroitor$ cd new_project/
mbp:new_project igorkroitor$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (new_project)
version: (1.0.0)
description:
entry point: (index.js)
test command:
git repository:
keywords:
author:
license: (ISC)
About to write to /Users/igorkroitor/new_project/package.json:

{
  "name": "new_project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this ok? (yes) y
mbp:new_project igorkroitor$ npm install ccxt

> ccxt@1.18.1059 postinstall /Users/igorkroitor/new_project/node_modules/ccxt
> node postinstall


                         :Siiiiiiiiiiir    rSiiiiiiiiiiS:
                         r&9hh&&&&&&&A5    SG99h&&&&&&GHr
                         ;hX32;::::::;,    i9X9S:;:::::;,
                         ;hX9S             ihXhr
                         ;hX32::::::,:,    i9X9i::::::,:.
                         rG999GGGGGGGAS    iG99hGGGGGGGAr
                         ;2S55SSSSSSS2r    r2555SSSSSSS2;
                         ;2S5s    ;2S2r    r2SS555555SS2;
                         rAh&2    sAhAS    SAGGh9999GGGAr
                         .:,::rrrs::::,    ,:,,;9X3X:,,:.
                              &A&H,            ,hX33
                         ,;:;;;;;r;;:;,        ,hX3X.
                         rHGAX    sAGA5        :&9h9.
                         :Ssir    ;isir        ,Siii

                                  Stars: 11,723
                                  Forks: 3,257
                                Contributors: 343
                                  Size: 0.80MB

                          Thanks for installing ccxt 🙏
                 Please consider donating to our open collective
                        to help us maintain this package.
              👉 Donate: https://opencollective.com/ccxt/donate 🎉
     Thanks to our 35 backers we are operating on an annual budget of $6,408

              ---------------------------------------------------

                     You can contribute in crypto directly:

                 ETH 0x26a3CB49578F07000575405a57888681249c35Fd
                 BTC 33RmVRfhK2WZVQR1R83h2e9yXoqRNDvJva
                 BCH 1GN9p233TvNcNQFthCgfiHUnj5JRKEc2Ze
                 LTC LbT8mkAqQBphc4yxLXEDgYDfEax74et3bP

              ---------------------------------------------------

                                   Thank you!

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN new_project@1.0.0 No description
npm WARN new_project@1.0.0 No repository field.

+ ccxt@1.18.1059
added 1 package in 3.184s
mbp:new_project igorkroitor$ npm list
new_project@1.0.0 /Users/igorkroitor/new_project
└── ccxt@1.18.1059

mbp:new_project igorkroitor$ node --version
v10.0.0
```

Can you provide any more details? Have you tried reaching out to Jelastic tech support on this issue?

**Comment by EmerF** [comment]
Hi Igor,

I asked the jeslatic team for some help.
I'm waiting for some response.

Anyway, I will get more details to pass it for you.



Emerson Fonseca

Em qui, 15 de ago de 2019 23:08, Igor Kroitor <notifications@github.com>
escreveu:

**Comment by EmerF** [comment]
* Versions
Node v 10.16.3
"ccxt": "^1.18.1063",

@angular-devkit/architect            0.802.2
@angular-devkit/build-angular     0.802.2
@angular-devkit/build-optimizer   0.802.2
@angular-devkit/build-webpack    0.802.2
@angular-devkit/core                    8.2.2
@angular-devkit/schematics         8.2.2
@angular/cdk                                8.1.3
@angular/material                         8.1.3
@ngtools/webpack                        8.2.2
@schematics/angular                   8.2.2
@schematics/update                    0.802.2

********** Log Produced by ng build --prod************

WARNING in ./node_modules/web3-eth-accounts/src/scrypt.js 17:50-60
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/asn1.js/lib/asn1/api.js
Module not found: Error: Can't resolve 'vm' in '/home/emerson/app/robotrade/node_modules/asn1.js/lib/asn1'

ERROR in ./node_modules/ccxt/js/static_dependencies/node-rsa/schemes/pkcs1.js
Module not found: Error: Can't resolve 'constants' in '/home/emerson/app/robotrade/node_modules/ccxt/js/static_dependencies/node-rsa/schemes'
ERROR in ./node_modules/scryptsy/lib/scrypt.js
Module not found: Error: Can't resolve 'crypto' in '/home/emerson/app/robotrade/node_modules/scryptsy/lib'
ERROR in ./node_modules/scryptsy/lib/scryptSync.js
Module not found: Error: Can't resolve 'crypto' in '/home/emerson/app/robotrade/node_modules/scryptsy/lib'
ERROR in ./node_modules/scryptsy/lib/utils.js
Module not found: Error: Can't resolve 'crypto' in '/home/emerson/app/robotrade/node_modules/scryptsy/lib'
ERROR in ./node_modules/swarm-js/node_modules/eth-lib/lib/bytes.js
Module not found: Error: Can't resolve 'crypto' in '/home/emerson/app/robotrade/node_modules/swarm-js/node_modules/eth-lib/lib'
ERROR in ./node_modules/web3-eth-accounts/node_modules/eth-lib/lib/bytes.js
Module not found: Error: Can't resolve 'crypto' in '/home/emerson/app/robotrade/node_modules/web3-eth-accounts/node_modules/eth-lib/lib'
ERROR in ./node_modules/web3-eth-accounts/src/scrypt.js
Module not found: Error: Can't resolve 'crypto' in '/home/emerson/app/robotrade/node_modules/web3-eth-accounts/src'
ERROR in ./node_modules/web3-eth-accounts/src/index.js
Module not found: Error: Can't resolve 'crypto' in '/home/emerson/app/robotrade/node_modules/web3-eth-accounts/src'
ERROR in ./node_modules/ccxt/js/static_dependencies/node-fetch/index.js
Module not found: Error: Can't resolve 'http' in '/home/emerson/app/robotrade/node_modules/ccxt/js/static_dependencies/node-fetch'
ERROR in ./node_modules/web3-providers-http/src/index.js
Module not found: Error: Can't resolve 'http' in '/home/emerson/app/robotrade/node_modules/web3-providers-http/src'm
ERROR in ./node_modules/xhr2-cookies/dist/xml-http-request.js
Module not found: Error: Can't resolve 'http' in '/home/emerson/app/robotrade/node_modules/xhr2-cookies/dist'
ERROR in ./node_modules/ccxt/js/static_dependencies/node-fetch/index.js
Module not found: Error: Can't resolve 'https' in '/home/emerson/app/robotrade/node_modules/ccxt/js/static_dependencies/node-fetch'
ERROR in ./node_modules/web3-providers-http/src/index.js
Module not found: Error: Can't resolve 'https' in '/home/emerson/app/robotrade/node_modules/web3-providers-http/src'
ERROR in ./node_modules/xhr2-cookies/dist/xml-http-request.js
Module not found: Error: Can't resolve 'https' in '/home/emerson/app/robotrade/node_modules/xhr2-cookies/dist'
ERROR in ./node_modules/xhr2-cookies/dist/xml-http-request.js
Module not found: Error: Can't resolve 'os' in '/home/emerson/app/robotrade/node_modules/xhr2-cookies/dist'
ERROR in ./node_modules/browserify-sign/browser/index.js
Module not found: Error: Can't resolve 'stream' in '/home/emerson/app/robotrade/node_modules/browserify-sign/browser'
ERROR in ./node_modules/ccxt/js/static_dependencies/node-fetch/index.js
Module not found: Error: Can't resolve 'stream' in '/home/emerson/app/robotrade/node_modules/ccxt/js/static_dependencies/node-fetch'
ERROR in ./node_modules/cipher-base/index.js
Module not found: Error: Can't resolve 'stream' in '/home/emerson/app/robotrade/node_modules/cipher-base'
ERROR in ./node_modules/hash-base/index.js

**Comment by EmerF** [comment]
Changed to heroku.
