### ISSUE TITLE
Add support for Binance distribution history (Airdrops, Distributions, Rewards, etc...)

### ISSUE THREAD

**Issue by rlkc112358** [ccxt/ccxt#5693]
Binance has recently upgraded its API, which now supports [Distribution History](https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#asset-dividend-record-user_data)  
  
The endpoint is `GET /sapi/v1/asset/assetDividend`  
  
It'd be great to be able to fetch distribution history through API as compared to the alternative:  
1. Notice an unexplained position break  
2. Log into Binance  
3. Check the distribution history for airdrops  
4. Manually book the airdrop into the Position Management System I am using

**Comment by kroitor** [comment]
Related: https://github.com/ccxt/ccxt/pull/5725
