### ISSUE TITLE
cancel_order() response unification

### ISSUE THREAD

**Issue by WoK-E** [ccxt/ccxt#5696]
- OS: All
- Programming Language version: All
- CCXT version: 1.18.1060
- Exchange: Most
- Method: cancel_order()

For most exchanges, cancel_order() returns the response that the exchange API returns, whereas for at least one that I've checked (Binance) the response is parsed via parse_order().
In order to check if the cancellation of the order actually happened, one has to either check the order by calling the API again, or check the response of the order cancellation API endpoint, that can be success==1, or result==true, or ... probably many more statuses depending on the exchange. The response of the order cancellation API endpoint of Binance (which is parsed) returns a status equal to 'canceled'.

I think that parsing the exchange responses instead of returning the actual exchange response would be useful :)

**Comment by kroitor** [comment]
In short, we totally agree ) See this issue for more details: https://github.com/ccxt/ccxt/issues/2983
