### ISSUE TITLE
kraken fetchTrades limit breaks pagination

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#5698]
- OS: linux
- Programming Language version: python
- CCXT version: 1.18.1060
- Exchange: kraken
- Method: fetchTrades

When using `fetchTrades()` with `limit=1000`, then the ID for pagination is in the last element.

When using the same function with a lower limit (999 or 50) - then the id is missing, breaking pagination.

``` python
import ccxt
from datetime import datetime, timedelta, timezone
ct = ccxt.kraken()
since = datetime.now(tz=timezone.utc) - timedelta(hours=10)
t = ct.fetch_trades(pair, since=int(since.timestamp() * 1000), limit=1000)
from_id = t[-1]['id']
print(f"id: {from_id}")
t = ct.fetch_trades(pair, since=int(since.timestamp() * 1000), limit=50)
from_id = t[-1]['id']
print(f"id2: {from_id}")
```
output:
``` output
id: 1565944335967223338
id2: None
```

I suspect the problem to be that kraken always returns 1000 trades - and ccxt assigns the ID to the last element **before** removing the non-requested trades.

Debug log:
```
Request: GET https://api.kraken.com/0/public/Trades?pair=XETHXXBT&since=1565930532224000000 {'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.kraken.com/0/public/Trades?pair=XETHXXBT&since=1565930532224000000 200 {'Date': 'Fri, 16 Aug 2019 14:42:13 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d83269543fa0ee5931ee64f354de626681565966532; expires=Sat, 15-Aug-20 14:42:12 GMT; path=/; domain=.kraken.com; HttpOnly', 'Cache-Control': 'public,max-age=1,smaxage=1', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Strict-Transport-Security': 'max-age=15768000', 'CF-Cache-Status': 'MISS', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '50742c6a9f2a3d81-MXP'} {"error":[],"result":{"XETHXXBT":[["0.018170","10.40000000",1565930683.0413,"s","m",""],["0.018170","8.11498012",1565930683.0498,"s","m",""],["0.018170","11.88501988",1565930683.0527,"s","m",""],["0.018200","0.71854156",1565930711.2243,"b","m",""],["0.018200","2.00000000",1565930844.838,"s","l",""],["0.018210","0.10322095",1565931205.4743,"s","l",""],["0.018220","0.11274252",1565931307.5558,"b","l",""],["0.018220","0.00018010",1565931307.5609,"b","l",""],["0.018220","0.00000029",1565931307.5627,"b","l",""],["0.018220","0.12031032",1565931307.5654,"b","l",""],["0.018220","0.15116868",1565931328.0606,"b","l",""],["0.018250","1.00000000",1565931349.1971,"b","m",""],["0.018250","1.00000000",1565931349.2028,"b","m",""],["0.018250","0.07500000",1565931349.206,"b","m",""],["0.018260","7.92500000",1565931349.2088,"b","m",""],["0.018260","0.50000000",1565931349.2222,"b","m",""],
...
...
["0.018440","0.41776282",1565944343.2934,"b","l",""],["0.018430","0.94571263",1565944344.2028,"s","l",""]],"last":"1565944344202795891"}}
```

**Comment by kroitor** [comment]
> I suspect the problem to be that kraken always returns 1000 trades

That's true

> and ccxt assigns the ID to the last element before removing the non-requested trades.

It's a bit deeper, unfortunately. Kraken returns the id of the last element only, so, it will always be the 1000th's trade id, regardless of the `limit` (this argument is not supported by the exchange API). Because we don't have the ids of all the trades, but just the `"last id"`, we can't really workaround this issue, unless you always paginate in thousands. 

- https://www.kraken.com/en-us/features/api#get-recent-trades
- https://support.kraken.com/hc/en-us/articles/218198197-How-to-pull-all-trade-data-using-the-Kraken-REST-API

@xmatthias what would you suggest in this case?

**Comment by xmatthias** [comment]
hm good point, didn't dig into the original result of the API.

how about printing (logging - maybe even raising) a warning if `limit` is set to something else - so users are aware of this limitation without raising an issue here ... ?

**Comment by ManuelSchneid3r** [comment]
Just for sake of completeness: Its not an trade id kraken ships in the `last` field. Its a nano second timestamp.

>The Trades endpoint takes an optional parameter named since, which specifies the starting date/time of the data. The since value is a UNIX timestamp at nanosecond resolution (a standard UNIX timestamp in seconds with 9 additional digits).

[src]( https://support.kraken.com/hc/en-us/articles/218198197-How-to-pull-all-trade-data-using-the-Kraken-REST-API)

**Comment by kroitor** [comment]
@ManuelSchneid3r thx for this note!

**Comment by ttodua** [comment]
@xmatthias this PR update should affect this issue too - https://github.com/ccxt/ccxt/pull/20780 
kraken now supports `count` param, so unified `limit` can be used well with kraken. let me know if you face that old issue anymore

**Comment by xmatthias** [comment]
i'm ... not convinced this was a problem in the last months, anyway (it's been fixed years ago in my opinion, but was reopened for some reason) - though i did lack the time to actually re-test this.
