### ISSUE TITLE
Use in angular 8

### ISSUE THREAD

**Issue by machine1104** [ccxt/ccxt#5703]
Hi
how do i import and use this package in Angular 8 ?
i installed it using npm command

**Comment by frosty00** [comment]
currently we only support node and browser runtimes, if you know how to run either of these with angular the library should work. At least in node you can do:

```
ccxt = require ('ccxt')
```
---
for the browser you may do:
```
<html>
  <script src='file://{PATH}/ccxt/dist/ccxt.browser.js'></script>
</html>
```

**Comment by Alex-DA** [comment]
Worked for me on Angular 11 (note: maybe exist a better and clean way, but didn't found it, yet):

1. `npm install ccxt --save`

2. on `angular.json` add:
```
...
"build": {
         ...
            "scripts": [
              "node_modules/ccxt/dist/ccxt.browser.js"
            ]
          ...
```

Now you will have loaded as <script> the ccxt library, and you can call it as an external JS library (the same way as you use a jQuery library loaded by the browser and not by Angular).

3. create file `/src/typings.d.ts` with this content:
```
declare var ccxt: any;
```

This is required to Angular compiler or your IDE don't complain.

**Comment by kroitor** [comment]
@Alex-DA appreciate your feedback!

**Comment by Alex-DA** [comment]
Also, this can be important, from https://angular.io/guide/using-libraries

```
Once you import a library using the "scripts" array, you should not import it using an import statement in your TypeScript code (such as import * as $ from 'jquery';). If you do, you'll end up with two different copies of the library: one imported as a global library, and one imported as a module. This is especially bad for libraries with plugins, like JQuery, because each copy will have different plugins.
```

So, don't use `import * as ccxt from 'ccxt';` on your Angular code.

**Comment by Mursaat** [comment]
> Worked for me on Angular 11 (note: maybe exist a better and clean way, but didn't found it, yet):
> 
> 1. `npm install ccxt --save`
> 2. on `angular.json` add:
> 
> ```
> ...
> "build": {
>          ...
>             "scripts": [
>               "node_modules/ccxt/dist/ccxt.browser.js"
>             ]
>           ...
> ```
> 
> Now you will have loaded as <script> the ccxt library, and you can call it as an external JS library (the same way as you use a jQuery library loaded by the browser and not by Angular).
> 
> 1. create file `/src/typings.d.ts` with this content:
> 
> ```
> declare var ccxt: any;
> ```
> 
> This is required to Angular compiler or your IDE don't complain.

I think we can use the types declared in `ccxt.d.ts` by doing this :

```typescript
declare var ccxt: typeof import('ccxt');
```

And I'm pretty sure it won't re-import the module in the build

**Comment by kroitor** [comment]
@Mursaat thank you for the feedback, we really appreciate it!

Closing this for now, feel free to reopen it or just ask further questions if any.

**Comment by Alex-DA** [comment]
> > Worked for me on Angular 11 (note: maybe exist a better and clean way, but didn't found it, yet):
> > 
> > 1. `npm install ccxt --save`
> > 2. on `angular.json` add:
> > 
> > ```
> > ...
> > "build": {
> >          ...
> >             "scripts": [
> >               "node_modules/ccxt/dist/ccxt.browser.js"
> >             ]
> >           ...
> > ```
> > 
> > 
> > Now you will have loaded as <script> the ccxt library, and you can call it as an external JS library (the same way as you use a jQuery library loaded by the browser and not by Angular).
> > 
> > 1. create file `/src/typings.d.ts` with this content:
> > 
> > ```
> > declare var ccxt: any;
> > ```
> > 
> > 
> > This is required to Angular compiler or your IDE don't complain.
> 
> I think we can use the types declared in `ccxt.d.ts` by doing this :
> 
> ```ts
> declare var ccxt: typeof import('ccxt');
> ```
> 
> And I'm pretty sure it won't re-import the module in the build

Great, I can confirm that works perfect.

@kroitor you think that can be interesting update the install instructions with this information?, I can prepare a PR.

**Comment by kroitor** [comment]
@Mursaat all contributions are welcome! If you can make it a clean edit – sure, why not add it to the install doc. Thank you so much!
