### ISSUE TITLE
minor: git-ignore-generated files skips a file

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#5705]
- OS: linux / docker
- Programming Language version: git (?)
- CCXT version: 1.18.1063
- Method: `npm run git-ignore-generated-files`

`npm run git-ignore-generated-files` ignores most files (but skips `wiki/Exchange-Markets-By-Country.md`).

This is shown as a diff afterwards, even though it was not modified manually

## steps to repro

* check out repo
* run docker-container :
  * run `npm run build`
  * run `npm run git-ignore-generated-files`
  * `git status`

output:
```
Badges updated successfully. (<anonymous> @ update-badges.js:80)
root@ff35d93a20b3:/ccxt# git statu
git: 'statu' is not a git command. See 'git --help'.

The most similar commands are
	status
	stage
	stash
root@ff35d93a20b3:/ccxt# git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   doc/FAQ.rst
	modified:   doc/README.rst
	modified:   doc/exchanges-by-country.rst
	modified:   doc/exchanges.rst
	modified:   doc/install.rst
	modified:   doc/manual.rst
	modified:   python/README.rst
	modified:   wiki/Exchange-Markets-By-Country.md

no changes added to commit (use "git add" and/or "git commit -a")
root@ff35d93a20b3:/ccxt# npm run git-ignore-generated-files

> ccxt@1.18.1063 git-ignore-generated-files /ccxt
> node build/git-ignore-generated-files

Disabling the git changes tracking for 385 generated files... (<anonymous> @ git-ignore-generated-files.js:83)
root@ff35d93a20b3:/ccxt# git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   wiki/Exchange-Markets-By-Country.md

no changes added to commit (use "git add" and/or "git commit -a")

```

**Comment by kroitor** [comment]
@xmatthias the `git-ignore-generated-files` is not supposed to be run by humans (actually, not supposed to be run at all). It was added as a build step on Travis in order to forbid pushing edits to transpiled files, but still allow them to be in the repo. However, that didn't work, and users can still force-push those edits anyway. So we are not triggering that step anywhere during the build process. Can you tell why would you need to run it?

**Comment by xmatthias** [comment]
Well, i don't really need to run it - but [Contributing.md - section committing](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#committing-changes-to-the-repository) tells developers to use it (or at least proposes to use it ...).

It does make finding the correct files easier, since it really hides the transpiled files (well, most of them anyway).

Side note:
(yes - i did actually read the Contributing document ...)

**Comment by kroitor** [comment]
> tells developers to use it 

That's was probably left over after our experiments with git ignore... I will update those guidelines and will look into the script asap. Your help with it is welcome )

> (yes - i did actually read the Contributing document ...)

Thx for that! )) Reading the docs is so rare nowadays, well, you know )
