### ISSUE TITLE
Binance Jersey API

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5707]
Has anyone yet tried to see if the new binance jersey authenticated api (https://github.com/binance-jersey/binance-official-api-docs/blob/master/rest-api.md#account-endpoints) works in ccxt?

**Comment by kroitor** [comment]
@npomfret we have `binanceje` integrated and it should work, because it's the same API. At least, it does work for me. Have you tried instantiating it from CCXT?

**Comment by npomfret** [comment]
I've not tried the account api yet.  Sorry, was being lazy.  I'm using the market data api, but when I started the account API wasn't available, it's a new(ish) thing.
