### ISSUE TITLE
Binance sending broken OHLCV constantly

### ISSUE THREAD

**Issue by poiseis** [ccxt/ccxt#5708]
OS: Windows
Python: 3.5
Ccxt:'1.18.1063'
Exchange: Binance
Method:fetchOHLCV

A while ago a realized that most coin Data that I downloaded have missing values. It is not an ordinary downtime issue. Every fetchOHLCV returns with missing 8hours on 5-minute charts. 

```
a=e.fetchOHLCV("BTC/USDT", timeframe="5m", limit=1000)
df=pd.DataFrame(a,  columns=("time","Open","High","Low","Close","Volume"))
df["DeltaTimes"] = df.time.diff()
print(df["DeltaTimes"].median())  #300000.0  5m
print(df["DeltaTimes"].max()) #29100000.0 ~8hours
```
tried with many different Symbols, they all return with same issue.

**Comment by xmatthias** [comment]
well honestly: https://www.binance.com/en/support/articles/360032315391

They had a downtime on August 15th, between 2am for 5-6 hours, which is confirmed by your data (kindof)

Modified script:
```python 
import ccxt
import pandas as pd
e = ccxt.binance()
a=e.fetchOHLCV("BTC/USDT", timeframe=f"{interval}m", limit=1000)
df=pd.DataFrame(a,  columns=("time","Open","High","Low","Close","Volume"))
df["DeltaTimes"] = df.time.diff()
df['date'] = pd.to_datetime(df['time'], unit='ms', utc=True)
df = df.set_index('date')

print(df["DeltaTimes"].median())  #300000.0  5m
print(df["DeltaTimes"].max()) #29100000.0 ~8hours

df['2019-08-15']  # This outputs the below screenshot at this moment - will be gone in 2 days unless "since=" is specified.
```

![2019-08-17-193658_856x327_scrot](https://user-images.githubusercontent.com/5024695/63215421-65a8f380-c126-11e9-86c4-9bbd6a91ff4d.png)

**Comment by kroitor** [comment]
Thx @xmatthias !

@poiseis let us know if the above does not answer the question...

Similar issues:

- https://github.com/ccxt/ccxt/issues/5026
- https://github.com/ccxt/ccxt/issues/4170

**Comment by poiseis** [comment]
I have a pooling system, Errors occurred every time I use fetch OHLCV,  not only in that hour, like if I fetch 10 times got the same problem in all of them. So I didn't think that it was a downtime issue.
  
![Figure_1](https://user-images.githubusercontent.com/35081126/63215756-09e56700-c134-11e9-9e1c-1519c10a7340.png)

But finally found the bug. I was getting delta-time on the first fetch so I can calculate ```since``` argument for pooling data. If there is a downtime, obviously calculated delta-time is longer than it should be, so pooling system created gaps between data.

Thank you for fast response. Ma-mistake... I wish there was a built-in pooling method in ccxt by the way.

**Comment by xmatthias** [comment]
define "pooling system" ... ?

**Comment by poiseis** [comment]
it's polling.. okeey :F
```
There's a limit on how far back in time your requests can go. Most of exchanges will not allow to query detailed candlestick history (like those for 1-minute and 5-minute timeframes) too far in the past. They usually keep a reasonable amount of most recent candles, like 1000 last candles for any timeframe is more than enough for most of needs. You can work around that limitation by continuously fetching (aka REST **polling**) latest OHLCVs and storing them in a CSV file or in a database.```

Sorry for English, I'm not a native. Guess I have to change also Pooling_Data() functions name also...  🤒 . By the way, I was using this function over a year.

**Comment by xmatthias** [comment]
binance goes back to ~october 2017 iirc ... i think that's when the exchange started (depends on the pair, obviously)
