### ISSUE TITLE
Implement WCX exchange 

### ISSUE THREAD

**Issue by Dante2333** [ccxt/ccxt#5714]
https://github.com/wcxofficial/api-docs, which allows trading forex pairs, stocks and other markets using BTC and leverage. Would it be possible to have this implemented by ccxt?

**Comment by kroitor** [comment]
> Would it be possible to have this implemented by ccxt?

Yes: 

- https://github.com/ccxt/ccxt/wiki/FAQ#when-will-you-add-feature-foo-for-exchange-bar--whats-the-estimated-time-when-should-we-expect-this

Duplicate: https://github.com/ccxt/ccxt/issues/5309
