### ISSUE TITLE
I want to use gateio's transaction history

### ISSUE THREAD

**Issue by xiaoqge** [ccxt/ccxt#5715]
- OS:
centos 7
- Programming Language version:
python
- CCXT version:
1.18.727
- Exchange:
gateio
- Method:
fetch_trades

I want to use gateio's transaction history, but the method is'tradeHistory /{ID}/{TID}'. I get the transaction after the specified ID. How can I pass in the parameter? Please help me. Thank you.

https://gateio.org/api2#history

**Comment by kroitor** [comment]
@xiaoqge why not use `fetchTrades` ? 

- https://github.com/ccxt/ccxt/wiki/Manual#trades-executions-transactions

**Comment by xiaoqge** [comment]
I tried to modify the method of the file in gateio. py. The problem was solved. Thank you for your help.

`    def fetch_trades(self, symbol, since=None,before=None,limit=None, params={}):
        self.load_markets()
        market = self.market(symbol)
        if before == None:
            request = {
                'id': market['id'],
            }
            response = self.publicGetTradeHistoryId(self.extend(request, params))
        else:
            request = {
                'id': market['id'],
                'tid':before
            }
            response = self.publicGetTradeHistoryIdTid(self.extend(request, params))
        return self.parse_trades(response['data'], market, since, limit)`

**Comment by kroitor** [comment]
```Python
exchange.load_markets()
symbol = 'ETH/BTC'
params = {
    'id': exchange.markets[symbol]['id'],
    'tid': YOUR_TRADE_ID,  # ←------------------------ ↓ 
}
const raw_trades = exchange.publicGetTradeHistoryId(params)
const parsed_trades = exchange.parse_trades(raw_trades, exchange.markets[symbol])
```

Or we've added it as an option since CCXT 1.18.1078

```Python
exchange = ccxt.gateio ({
    'options': {
        'fetchTradesMethod': 'public_get_tradehistory_id_tid',  # or 'public_get_tradehistory_id'
    }
})
exchange.fetchTrades (symbol, since, limit, { 'tid': YOUR_TRADE_ID })
```

@xiaoqge the new build supporting that feature will arrive in 15 minutes. Let us know if that does not help.

**Comment by xiaoqge** [comment]
The problem has been solved. Thank you for your help. Your answer has reduced my trouble.

**Comment by xiaoqge** [comment]
@kroitor  There is a problem. I need to modify the response = self. publicGetTradeHistoryId (self. extend (request, params) in the fetch_trades method in the gateio. py file according to the method you provided. I can change this line to response = self. publicGetTradeHistoryIdTid (self. extend (request, params)) to work properly. 。

**Comment by kroitor** [comment]
@xiaoqge 

1. upgrade to version 1.18.1078+
2. use this snippet:

```Python
exchange = ccxt.gateio ({
    'options': {
        'fetchTradesMethod': 'public_get_tradehistory_id_tid',  # or 'public_get_tradehistory_id'
    }
})
exchange.fetch_trades (symbol, since, limit, { 'tid': YOUR_TRADE_ID })
```

Let us know if that does not resolve the issue for you.

**Comment by xiaoqge** [comment]
Thank you. I'll try.
