### ISSUE TITLE
okex error on None price

### ISSUE THREAD

**Issue by kristofjuhasz** [ccxt/ccxt#5716]
https://github.com/ccxt/ccxt/blob/be3d0a47b779d6978a57b880be79b2d7c9d567da/python/ccxt/okex3.py#L1451

Will throw error when calling decimal_to_precision if price=None  (which is default).

**Comment by kroitor** [comment]
@kristofjuhasz can you please paste the code you use to reproduce it? Because with limit orders the price is required, as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#placing-orders

**Comment by kristofjuhasz** [comment]
@kroitor for okex futures, such as "BTC-USD-190927", to define a market order you must specify extra parameters, such as "match_price": 1, (correct me If I am wrong) and set type=1 for open long orders. Find the following code snippet for the reproduced error:

import ccxt
okex_exchange = ccxt.okex3()
okex.create_order(symbol="BTC-USD-190927", type=1, side="buy", amount=1, price=None, params={})
okex_exchange.create_order(symbol="BTC-USD-190927", type=1, side="buy", amount=1, price=None, params={})
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "----", line 1450, in create_order
    'price': self.price_to_precision(symbol, price),
  File "---", line 1124, in price_to_precision
    return self.decimal_to_precision(price, ROUND, self.markets[symbol]['precision']['price'], self.precisionMode)
  File "---, line 51, in decimal_to_precision
    dec = decimal.Decimal(str(n))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

**Comment by kroitor** [comment]
@kristofjuhasz i think the price is required for all futures orders:

- https://www.okex.com/docs/en/#futures-orders

![Screen-Shot-2019-08-21-at-23 34 22](https://user-images.githubusercontent.com/1294454/63466698-7c27b580-c46c-11e9-8a1c-cc5d76b55be6.jpg)

Let me know if the above does not answer the question.
