### ISSUE TITLE
How to use bitmex testnet?

### ISSUE THREAD

**Issue by heckad** [ccxt/ccxt#5717]
I want to test my strategy in `https://testnet.bitmex.com` but didn't find how to do it in readme and faq. How to do it?

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/issues/2096#issuecomment-370186689
- https://github.com/ccxt/ccxt/issues/3960
- https://github.com/ccxt/ccxt/issues/2684#issuecomment-386692088


```Python
import ccxt
exchange = ccxt.bitmex({
    'apiKey': 'YOUR_TESTNET_KEY',
    'secret': 'YOUR_TESTNET_SECRET',
})
if 'test' in exchange.urls:
    exchange.urls['api'] = exchange.urls['test'] # ←----- switch the base URL to testnet
print(exchange.fetch_balance())
```

Let us know if the above does not help.

**Comment by heckad** [comment]
I found `set_sandbox_mode` method, but it doesn't call at all and not describe in the documentation. Also seems that it can't be enabled through the config. It's a bug?

**Comment by kroitor** [comment]
> Also seems that it can't be enabled through the config. It's a bug?

Nope:

```Python
exchange = getattr(ccxt, "bitmex") ({
    'urls':{
        'api':'https://testnet.bitmex.com'
    },
    'apiKey': 'uZ3vb_...',
    'secret': 'S0cPup3...',
    'verbose': False
})
```

**Comment by heckad** [comment]
So there is a method that does this perfectly. It would be logical if `use_sandbox_mode` with a value of `true` or `false` were passed to the config, and if it was added to the config, that method would be called.
