### ISSUE TITLE
Binance balances for BCHABC/BCHSV not mapping to ids

### ISSUE THREAD

**Issue by soliveira-vouga** [ccxt/ccxt#5720]
When I fetch balances for my binance account I get positive balances for BCHABC and BCHSV and nothing for BCH / BSV.

However, shouldn't CCXT automatically map BCHABC to BCH and BCHSV to BSV? 

The same should go for BAB => BCH on Bitfinex

**Comment by kroitor** [comment]
@soliveira-vouga can you post your code to reproduce it (without your keys) and your verbose request/response, as described here: 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

> However, shouldn't CCXT automatically map BCHABC to BCH and BCHSV to BSV?

It should, yes.

**Comment by kroitor** [comment]
See this issue for more details: https://github.com/ccxt/ccxt/issues/5736
