### ISSUE TITLE
How does one properly use CryptoJS so the python transpiler is happy

### ISSUE THREAD

**Issue by Joe-mcgee** [ccxt/ccxt#5723]
Hi, I'm busying myself creating an exchange for www.oex.com
This particular exchange likes putting paramets into a string and turning it into an MD5 hash.  the library on the js side works great. However when i run the ```npm run build``` in the docker instance i get this 
```Transpiled successfully. (<anonymous> @ transpile.js:994)

> ccxt@1.18.1080 qa /ccxt
> npm run check-python-syntax && npm run check-php-syntax


> ccxt@1.18.1080 check-python-syntax /ccxt
> cd python && tox -e qa && cd ..

qa installed: aiodns==1.1.1,aiohttp==3.5.4,asn1crypto==0.24.0,async-timeout==3.0.1,attrs==19.1.0,ccxt==1.18.766,certifi==2019.6.16,cffi==1.12.3,chardet==3.0.4,cryptography==2.7,flake8==3.5.0,idna==2.8,idna-ssl==1.1.0,mccabe==0.6.1,multidict==4.5.2,pycares==3.0.0,pycodestyle==2.3.1,pycparser==2.19,pyflakes==1.6.0,requests==2.22.0,six==1.12.0,typing-extensions==3.7.4,urllib3==1.25.3,yarl==1.1.0
qa run-test-pre: PYTHONHASHSEED='1553072598'
qa run-test: commands[0] | flake8 --exclude static_dependencies,.tox
./ccxt/__init__.py:68:11: E999 SyntaxError: invalid syntax
./ccxt/oex.py:72:19: F821 undefined name 'CryptoJS'
./ccxt/oex.py:72:49: F821 undefined name 'CryptoJS'
./ccxt/async_support/__init__.py:49:25: E999 SyntaxError: invalid syntax
./ccxt/async_support/oex.py:72:19: F821 undefined name 'CryptoJS'
./ccxt/async_support/oex.py:72:49: F821 undefined name 'CryptoJS'
ERROR: InvocationError for command /ccxt/python/.tox/qa/bin/flake8 --exclude static_dependencies,.tox (exited with code 1)
```
Something tells me I'm overlooking a pattern/rail here.  Is there a formalized way to get cryptoJS to play nice with the python transpiler?

- OS: Ubuntu 19
- Programming Language version: python
- CCXT version: 1.18.1080
- Exchange: oex.js
- Method: sign with cryptojs functions

link to [oex.js](https://github.com/Joe-mcgee/ccxt/blob/new-exchange/oex/js/oex.js)

**Comment by kroitor** [comment]
> Something tells me I'm overlooking a pattern/rail here. Is there a formalized way to get cryptoJS to play nice with the python transpiler?

Yep, exactly! ) The general idea is: we only transpile syntax in pure language and cannot transpile external modules. In fact we don't even transpile all the code, the base classes are not transpiled, only the derived exchange classes language-agnostic and are transpiled, while base code is language-specific.

This is covered here:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#transpiled-generated-files

So, in general, if you can do this or that with pure language constructs within a derived exchange file – that should be transpiled, and if you're trying to do something complex like cryptography, that should be utilized from a base class. 

The base Exchange class has several methods that are key to practically all cryptography in this lib:

- `hash (message, hash = 'md5', digest = 'hex')`
- `hmac (message, secretKey, hash = 'sha256', digest = 'hex')` HMAC authentication
- `jwt (message, secretKey, hash = 'HS256')` JSON Web Token Authentication
- `rsa (request, secretKey, alg = 'RS256')` RSA asymmetric cryptography
- `ecdsa (request, secretKey, algorithm = 'p256', hash = undefined)` Ellyptic Curve Cryptography
- `totp (secretKey)` OTP / 2FA authentication
- `stringToBase64()`, `base64ToBinary()`, `binaryToBase64()`...
- \+ a few other helper methods...

Most of those methods use hashing which is implemented with the `hash()` method.

The `hash()` method supports the following `hash` algorithms:

- `'md5'`
- `'sha1'`
- `'sha3'`
- `'sha256'`
- `'sha384'`
- `'sha512'`
- `'keccak'`

The `digest` argument accepts the following values:

- `'hex'`
- `'binary'`
- `'base64'`

Let us know if the above does not answer the question.

**Comment by Joe-mcgee** [comment]
Yup this is exactly what i was looking for, thanks!
