### ISSUE TITLE
Kraken load markets error

### ISSUE THREAD

**Issue by AurelReb** [ccxt/ccxt#5727]
- OS: Ubuntu 16.04
- Programming Language version: Python 3.6
- CCXT version: 1.18.1083
- Exchange: Kraken
- Method: fetch_min_order_amounts

EDIT: the issue happens on the `load_markets` call but seems to be caused by `fetch_min_order_amounts` method.

Here is the issue: ccxt fetch all data from kraken articles: https://github.com/ccxt/ccxt/blob/master/python/ccxt/kraken.py line 255-256

Kraken recently changed some articles, and now, ccxt can't fetch min order amount (and maybe other things).
Here is the error: `ccxt.base.errors.ExchangeError: GET https://support.kraken.com/hc/en-us/articles//205893708-What-is-the-minimum-order-size-`
Maybe fetching data from an api could avoid this issue in the future

Thank you very much

**Comment by kroitor** [comment]
> Maybe fetching data from an api could avoid this issue in the future

The problem is that Kraken API does not serve min limits for orders.

> Here is the error: ccxt.base.errors.ExchangeError: GET https://support.kraken.com/hc/en-us/articles//205893708-What-is-the-minimum-order-size-

This is a python-only bug and it was introduced here: https://github.com/ccxt/ccxt/pull/5711/files#diff-4ca611a196a4dc7a1e1f1170b47c5537R579

I have reverted this change in Python and it should work normally as of version 1.18.1084. We will be happy if you report back, whether it did solve the issue for you or not.

**Comment by belzebalex** [comment]
If I may suggest that, maybe would it be a good idea to have a test running every day and testing that kind of features (public market access at least) on all supported exchanges. It would avoid issues like this one.

**Comment by kroitor** [comment]
@belzebalex 

> If I may suggest that, maybe would it be a good idea to have a test running every day and testing that kind of features (public market access at least) on all supported exchanges. It would avoid issues like this one.

We run tests more than once every day, however, the tests don't cover all new edits, unfortunately. This is not the exchange-side error, this is a bug in the code introduced within CCXT during the intermediate refactoring of the base code, so it has nothing to do with Kraken in particular, really.

**Comment by AurelReb** [comment]
@kroitor Your fix works well! thank you.
I sent a message to the kraken's support and in the next api release, they should add the min_order_amount in the fetchAssets api.

**Comment by kroitor** [comment]
@AurelReb awesome! Thx for the followup!
