### ISSUE TITLE
The exchange I use is not supported. Can I use ccxt to expand my support for this exchange? Do you have relevant documents?

### ISSUE THREAD

**Issue by xiaoqge** [ccxt/ccxt#5729]
The exchange I use is not supported. Can I use ccxt to expand my support for this exchange? Do you have relevant documents?

**Comment by kroitor** [comment]
> Can I use ccxt to expand my support for this exchange?

Yes, of course.

> Do you have relevant documents?

We recommend to start from here: 

- https://github.com/ccxt/ccxt/wiki/Manual 
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md
- https://github.com/ccxt/ccxt/wiki/Requirements

Let us know if that does not help.
