### ISSUE TITLE
Unified ccxt method with the implicit exchange specific method

### ISSUE THREAD

**Issue by RuChiang** [ccxt/ccxt#5732]
Currently I'm working on an exchange integration into the ccxt library. I notice that developers should all use the implicit methods for exchange specific methods.

However, I got stuck with the implicit method invocation. Here I am attaching an example that have problem with.

so here I have an exchange api endpoint like this

```api.example.com/futures/{id}/candles```

I have followed the manual to write this endpoint up in the describe() function in the exchange class I created, something like

```
api:{
  public:{
    get:[
      'futures/{id}/candles'
    ]
  }
}
```

and In the unified methods I simply called the function

```publicGetFuturesIdCandles (this.extend({id:'some_id'}, params))```

From the response returned by the exchange API, seems like that id was not replaced at all, and therefore the url of the issued request looks like

```api.example.com/futures/ID/candles```

Appreciate a lot if someone can help out!!

**Comment by kroitor** [comment]
Does your `sign()` method implementation have a call to `implodeParams()`, as shown, for example, here:

- https://github.com/ccxt/ccxt/blob/master/js/kucoin.js#L1508
- https://github.com/ccxt/ccxt/blob/master/js/bittrex.js#L1251
- ...

?

**Comment by RuChiang** [comment]
Thanks for the guide!! Extremely useful!!
