### ISSUE TITLE
Gemini private failing

### ISSUE THREAD

**Issue by gRittyKitty** [ccxt/ccxt#5734]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Max and linux
- Programming Language version: nodejs
- CCXT version: 1.18.1092
- Exchange: Gemini
- Method: fetchBalance

I have been using ccxt & Gemini for a while. Have also been using these api keys for some time. All of a sudden I seem to be having issues using the Gemini API. 

A reasonable approximation of my code is:
```
let keystuff = {
    "apiKey" : "key for api",
    "secret" : "shh secret",
  };
const exchange = await new ccxt[exch](keystuff);
d = await exchange.fetchBalance();
console.log(d);
```

I'm getting a huge dump from Gemini which I believe is literally the Gemini API docs page. 
At the end I get:
`offline, on maintenance, or unreachable from this location at the moment (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)
    at gemini.defaultErrorHandler (/Users/ari/dev/exchGateway/node_modules/ccxt/js/base/Exchange.js:586:19)
    at response.text.then (/Users/ari/dev/exchGateway/node_modules/ccxt/js/base/Exchange.js:629:18)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:6206) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6206) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

I thought that perhaps my key had a problem. So I've created a new API key (actually did this twice). Like I said, this has been operational for months and used many times.
In addition, I have an instance of the same code running on a machine with an older version of ccxt ("^1.18.847", from package.json) which works fine. So this appears to be an issue between these two versions.

**Comment by kroitor** [comment]
This is fixed in 1.18.1093 (the new build will arrive in 15 minutes). Thank you for reporting!
