### ISSUE TITLE
Discrepancy between BCH and BCHABC symbols on Binance

### ISSUE THREAD

**Issue by topchatz** [ccxt/ccxt#5736]
- OS: Windows
- Programming Language version: Python 3.7
- CCXT version: 1.18.892
- Exchange: Binance

Hi guys, it looks like someone else might have noticed this as well, as there is a similar question to mine. But on Binance, the symbol for Bitcoin Cash is listed as 'BCH/BTC' when getting symbols from the load markets function. However, if I want to get my Bitcoin Cash balance I have to use 'BCHABC'. 

For example:

`df = pd.DataFrame(binance.fetch_ohlcv('BCH/BTC'))`

Gives me my kline data for Bitcoin Cash, but when I want to check my balance I have to use:

```
for i in binance.fetch_balance()['info']['balances']:
    if i['asset'] == 'BCHABC':
        print(i)
```
As I'm sure your'e aware BCH split in to BCHABC and BCHSV, however BCHSV is now no longer listed on Binance, but I think the symbol for the original Bitcoin Cash should remain as BCHABC so as to distinguish it from the other. I initially thought this was a problem at Binance's end but they say it isn't so I think it may be a problem in CCXT?

Many thanks

**Comment by kroitor** [comment]
> I initially thought this was a problem at Binance's end but they say it isn't so I think it may be a problem in CCXT?

Hi! As documented in the Manual, each response from a unified method will contain the raw `info` field that will be exchange-specific, and also will contain the unified part of information, that will be cross-compatible. It looks like you're confusing the unified response with the `info` raw field in it.

```
{  info: {  makerCommission:    10,
            takerCommission:    10,
            buyerCommission:    0,
           sellerCommission:    0,
                   canTrade:    true,
                canWithdraw:    true,
                 canDeposit:    true,
                 updateTime:    1566877942093,
                accountType:   "MARGIN",
                   balances: [ {  asset: "BTC",
                                   free: "0.00300169",
                                 locked: "0.00000000"  },
                                 ...
                               {  asset: "BCHABC", ←---------- YOU'RE LOOKING HERE
                                   free: "0.00000000",
                                 locked: "0.00000000"  },
                                 ...

                               {  asset: "TOMO",
                                   free: "0.00000000",
                                 locked: "0.00000000"  }    ] },
    BTC: { free: 0.00300169, used: 0, total: 0.00300169 },
...
    BCH: { free: 0, used: 0, total: 0 }, ←----- YOU SHOULD BE LOOKING HERE
   free: {   BTC: 0.00300169,
            ...
             BCH: 0, ←----- YOU SHOULD BE LOOKING HERE
             ...
            TOMO: 0             },
   used: {   BTC: 0,
            ...
             BCH: 0, ←----- OR HERE
             ...
            TOMO: 0  },
  total: {   BTC: 0.00300169,
            ...
             BCH: 0, ←----- OR HERE
             ...
            TOMO: 0             }                                }

```

```
mbp:ccxt igorkroitor$ node examples/js/cli binance currencies --table
    id | numericId |  code | precision
--------------------------------------
...
BCHABC |           |   BCH |         8
...
   ZRX |           |   ZRX |         8
184 objects
```

Let us know if the above does not answer the question.

**Comment by kroitor** [comment]
P.S. The unified fetchBalance response structure is documented here: https://github.com/ccxt/ccxt/wiki/Manual#balance-structure

**Comment by topchatz** [comment]
Hi mate, thanks for the response. My problem basically is my automated system gets all symbols from the .load_markets() function, which lists BCH/BTC for example as a symbol, but not BCHABC/BTC. So my system starts getting historical data using BCH/BTC, but then crashes when it tries to look up my BCH balance using .fetch_balance() as it's not listed amongst the assets.

It looks like what you mention above might solve this for me , how do I get this info though sorry?

Many thanks

**Comment by topchatz** [comment]
Oh sorry ignore me, I missed your second message. Thanks a lot
