### ISSUE TITLE
Possible bug with currency Capricoin vs CapriCoin and Gold vs GOLD vs GLD

### ISSUE THREAD

**Issue by wagok** [ccxt/ccxt#5740]
- OS: Linux
- Programming Language version: js
- CCXT version: "1.18.1094"
- Exchange: YoBit, Vaultoro
- Method: custom

There are two possible bugs with currency code:
1. Exchange YoBit provide Capricoin (Capricoin/BTC), but LiveCoin exchange provide CapriCoin (CapriCoin/BTC). Is it the same CAPRICOIN or different.

2. Exchange Vaultoro provide (Gold/BTC), but crex24 exchange provide GOLD. In the same time Vaultoro has id GLD-BTC and crex24 has id GOLD-BTC and exchanges dx and nova use GLD as base currency. So Gold vs GOLD vs GLD are different currencies or are the same some two of it?

**Comment by kroitor** [comment]
1. will fix this shortly
2. Vaultoro trades real gold (Au on your periodic table), whereas crex24 trades Gold Token (https://coinmarketcap.com/currencies/golden-token/), those are two different assets, therefore two different codes (Gold vs GOLD).
