### ISSUE TITLE
Huobi not accessible from China without a proxy

### ISSUE THREAD

**Issue by bitProfessor** [ccxt/ccxt#5742]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:mac os
- Programming Language version:python
- CCXT version:1.18.940
- Exchange:huobipro
- Method:fetch_markets()
![屏幕快照 2019-08-28 下午12 05 05](https://user-images.githubusercontent.com/48040328/63825208-76f6c900-c98c-11e9-90b2-154cdf8a5d2e.png)

**Comment by bitProfessor** [comment]
hb = ccxt.huobipro({
            # 'enableRateLimit': True,
            'apiKey': Access_Key,
            'secret': Secret_Key,
            'verbose': True,
        })
hb.fetch_markets()

**Comment by kroitor** [comment]
@bitProfessor i can't reproduce it on my side (works for me)... Have you tried the troubleshooting as described in the Manual?

```Python
import ccxt
exchange = ccxt.huobipro({
    'enableRateLimit': True,
    'proxy': 'https://cors-anywhere.herokuapp.com/',
    'origin': 'huobipro'
})
exchange.load_markets()
print(exchange.markets)
```

?
```

**Comment by o3o3o** [comment]
I think the problem is your network environment in China.  I can reproduce it in China network too.

You should use a proxy if you want to request huobipro API from china. @bitProfessor

**Comment by bitProfessor** [comment]
> ```python
> import ccxt
> exchange = ccxt.huobipro({
>     'enableRateLimit': True,
>     'proxy': 'https://cors-anywhere.herokuapp.com/',
>     'origin': 'huobipro'
> })
> exchange.load_markets()
> print(exchange.markets)
> ```
thank it works
