### ISSUE TITLE
php version: Illegal characters found in parameter 'quantity'; legal range is '^([0-9]{1,20})(\\.[0-9]{1,20})?$'

### ISSUE THREAD

**Issue by StasToken** [ccxt/ccxt#5744]
- OS: Ubuntu 18
- Programming Language version: PHP 7.2.2
- CCXT version: 1.18.1094
- Exchange: binance
- Method: create_order

I know this question was asked earlier, but the problem has not yet been resolved in the php version anyway.

when running, execute create_order I get an error: 

> In binance.php line 1336:
                                                                                                                                       

>   binance {"code":-1100,"msg":"Illegal characters found in parameter 'quantity'; legal range is '^([0-9]{1,20})(\\.[0-9]{1,20})?$'."} 

I already realized that this is due to the moronic property of PHP converting small numbers to scientific notation 1.0E-8 ... 

I looked at the code below, it seems like such a record should be converted to a normal string type, but this does not seem to happen, then I tried to do it manually

`$binance->create_order($this->symbol, 'MARKET', 'SELL', $binance->number_to_string($value))`

This allowed to remove the error.

But it looks like a crutch, I think it's worth adding a check for a scientific record inside create_order - because now it does not work very correctly, what do you think?

**Comment by kroitor** [comment]
@StasToken hi! What's your `symbol` and `$value` ?

**Comment by kroitor** [comment]
@StasToken in general, CCXT expects a `float` type in the `amount` argument, and if you pass a float to it (not a string) it will properly format it for you. However, if you're pre-formatting the value on the user side, and that yields scientific notation, then you're not doing it right, and you should not pass strings for the `amount` argument. 

Let us know if this issue does not help: https://github.com/ccxt/ccxt/issues/1054

**Comment by StasToken** [comment]
This is a joke, that if I pass float for example 0.00000001 for BTC/USDT then I get an error

**Comment by kroitor** [comment]
@StasToken it depends on the type of the error. Can you answer the questions above or provide a verbose output as described here?

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by kroitor** [comment]
Nevermind, I think I've reproduced it on my side... Will fix it shortly.

**Comment by kroitor** [comment]
@StasToken it should work properly as of version 1.18.1102. Let us know if that does not help. Thx!

**Comment by MrSalazer** [comment]
i using javascript and im having the exact error as the title of this page, can you help it suggest anything
