### ISSUE TITLE
[cex.io] prices rounded incorrectly

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5745]
The cex.io BTC/GBP market allows 1 decimal place on the price.  The metadata in the cex call for that market has a zero for price precision:

```
"BTC/GBP": {
      "limits": {
        "amount": {
          "min": 0.002
        },
        "price": {
          "min": 1300,
          "max": 30000
        },
        "cost": {
          "min": 20
        }
      },
      "precision": {
        "price": 0, <-- this looks wrong
        "amount": 3
      },
```

I think the error comes from this:

```
  'precision': {
    'price': this.precisionFromString (this.safeString (market, 'minPrice')), <-- this looks wrong
    'amount': this.precisionFromString (this.safeString (market, 'minLotSize')),
  },
```

The source data (https://cex.io/api/currency_limits) has:

```
{
"symbol1": "BTC",
"symbol2": "GBP",
"minLotSize": 0.002,
"minLotSizeS2": 20,
"maxLotSize": null,
"minPrice": "1300", <-- these don't show the precision
"maxPrice": "30000"
}
```

Which doesn't show the precision as a field, and the _minPrice_ and _maxPrice_ fields aren't shown with the max precision.

@kroitor do you have a suggestion for a fix?  I'm happy to implement.

**Comment by kroitor** [comment]
>@kroitor do you have a suggestion for a fix? I'm happy to implement.

@npomfret it would be awesome if you could help debug it and establish if they impose any limits on price precision at all. Will they accept 1300.00000001 ? 1300.000000000000001? etc... The workaround depends on those results of a random walk over markets and currencies...

**Comment by npomfret** [comment]
**Test 1**: _adding an unnecessary amount of training zeros to the price_:

```
fetch:
 cex POST https://cex.io/api/place_order/BTC/GBP/ 
Request:
 { 'Content-Type': 'application/json' } 
 {"key":"ggg","signature":"hhh","nonce":"1567005933319","type":"sell","amount":"0.002","price":"9094.0000"} 

handleRestResponse:
 cex POST https://cex.io/api/place_order/BTC/GBP/ 200 OK 
Response:
 { 'Cf-Ray': '50d74c6b7cadce4f-LHR',
  Connection: 'close',
  'Content-Security-Policy-Report-Only':
   'default-src \'self\';connect-src \'self\' https://maps.googleapis.com https://cex.io wss://ws.cex.io/ws;frame-src \'self\' * ext.cex.io;font-src \'self\' data: \'unsafe-inline\' https://fonts.googleapis.com https://fonts.gstatic.com;img-src \'self\' data:;style-src \'self\' \'unsafe-inline\' https://*.googleapis.com https://code.jquery.com;script-src \'self\' \'unsafe-inline\' \'unsafe-eval\';report-uri https://cex.io/cspr;',
  'Content-Type': 'text/json',
  Date: 'Wed, 28 Aug 2019 15:25:33 GMT',
  'Expect-Ct':
   'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Set-Cookie':
   '__cfduid=jjj; expires=Thu, 27-Aug-20 15:25:33 GMT; path=/; domain=.cex.io; HttpOnly; Secure',
  'Transfer-Encoding': 'chunked',
  Vary: 'Accept-Encoding',
  'X-Frame-Options': 'DENY' } 
 {"complete":false,"id":"9998765350","time":1567005933399,"pending":"0.00200000","amount":"0.00200000","type":"sell","price":"9094"} 
```
Passed

**Test 2**: _adding a valid order priced at what I think is the correct allowed precision_:

```
fetch:
 cex POST https://cex.io/api/place_order/BTC/GBP/ 
Request:
 { 'Content-Type': 'application/json' } 
 {"key":"ggg","signature":"hhh","nonce":"1567005990061","type":"sell","amount":"0.002","price":"9094.1"} 

handleRestResponse:
 cex POST https://cex.io/api/place_order/BTC/GBP/ 200 OK 
Response:
 { 'Cf-Ray': '50d74dce18fece8b-LHR',
  Connection: 'close',
  'Content-Security-Policy-Report-Only':
   'default-src \'self\';connect-src \'self\' https://maps.googleapis.com https://cex.io wss://ws.cex.io/ws;frame-src \'self\' * ext.cex.io;font-src \'self\' data: \'unsafe-inline\' https://fonts.googleapis.com https://fonts.gstatic.com;img-src \'self\' data:;style-src \'self\' \'unsafe-inline\' https://*.googleapis.com https://code.jquery.com;script-src \'self\' \'unsafe-inline\' \'unsafe-eval\';report-uri https://cex.io/cspr;',
  'Content-Type': 'text/json',
  Date: 'Wed, 28 Aug 2019 15:26:30 GMT',
  'Expect-Ct':
   'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Set-Cookie':
   '__cfduid=jjj; expires=Thu, 27-Aug-20 15:26:30 GMT; path=/; domain=.cex.io; HttpOnly; Secure',
  'Transfer-Encoding': 'chunked',
  Vary: 'Accept-Encoding',
  'X-Frame-Options': 'DENY' } 
 {"complete":false,"id":"9998773066","time":1567005990197,"pending":"0.00200000","amount":"0.00200000","type":"sell","price":"9094.1"} 
```
Passed

**Test 3**: _adding an order priced with at an excessive precision_:

```
fetch:
 cex POST https://cex.io/api/place_order/BTC/GBP/ 
Request:
 { 'Content-Type': 'application/json' } 
 {"key":"ggg","signature":"hhh","nonce":"1567006071834","type":"sell","amount":"0.002","price":"9098.01"} 

handleRestResponse:
 cex POST https://cex.io/api/place_order/BTC/GBP/ 200 OK 
Response:
 { 'Cf-Ray': '50d74fcd1ecdce6f-LHR',
  Connection: 'close',
  'Content-Security-Policy-Report-Only':
   'default-src \'self\';connect-src \'self\' https://maps.googleapis.com https://cex.io wss://ws.cex.io/ws;frame-src \'self\' * ext.cex.io;font-src \'self\' data: \'unsafe-inline\' https://fonts.googleapis.com https://fonts.gstatic.com;img-src \'self\' data:;style-src \'self\' \'unsafe-inline\' https://*.googleapis.com https://code.jquery.com;script-src \'self\' \'unsafe-inline\' \'unsafe-eval\';report-uri https://cex.io/cspr;',
  'Content-Type': 'text/json',
  Date: 'Wed, 28 Aug 2019 15:27:51 GMT',
  'Expect-Ct':
   'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Set-Cookie':
   '__cfduid=jjj; expires=Thu, 27-Aug-20 15:27:51 GMT; path=/; domain=.cex.io; HttpOnly; Secure',
  'Transfer-Encoding': 'chunked',
  Vary: 'Accept-Encoding',
  'X-Frame-Options': 'DENY' } 
 {"error":"There was an error while placing your order: Invalid price","safe":true} 
```
Failed

**Comment by kroitor** [comment]
@npomfret it will be very hard to guess those limits, even i we derive them from orderbooks, that doesn't really guarantee from a mistake, especially with inactive markets... Have you tried reaching out to CEX.io on this issue? Maybe, they can provide an endpoint for that. Or maybe you can shed some light in why you think precision = 1 is correct in this case, and if it would work in other cases...

**Comment by npomfret** [comment]
>  Or maybe you can shed some light in why you think precision = 1 is correct in this case, and whether you think it will work in other cases...

I just noticed the difference between the ccxt rounded price and the prices in the order book for this market.

I will contact the exchange to see if there's another api call, or something similar we can use.

I think we should consider removing the current values though as they are incorrect.

**Comment by npomfret** [comment]
I found this in my browser's debugger: https://cex.io/scripts/currencyProfile/1564741298124-v901400

Looks like is has the data we need, only it's embedded in a javascript variable.  What do you think?

**Comment by kroitor** [comment]
The only part of the URL that confuses me is `1564741298124-v901400`... Since it suggests that they will frequently change the trading rules, and, effectively, the page url as well...

**Comment by npomfret** [comment]
Could we make a copy and periodically update it when people notice that the data is wrong?

**Comment by kroitor** [comment]
> Could we make a copy and periodically update it when people notice that the data is wrong?

Tbh, hardcoding market properties is not the best idea, since it's hard to maintain.

Also:

- https://blog.cex.io/news/price-precision-16718

**Comment by npomfret** [comment]
We can get it on the fly maybe, try this:

`curl -v --silent https://cex.io 2>&1 | grep currencyProfile`

**Comment by kroitor** [comment]
@npomfret we'd rather scrape it than hardcode it, really. But I'm looking into a documented way to get the information we need, preferably... What if we first get an answer or some reaction from their tech support (if you can reach out to them) ? They could solve our questions here, easily.

**Comment by npomfret** [comment]
I've raised a request, but their support is pretty terrible.

**Comment by npomfret** [comment]
They appear to have deleted my support request :(

**Comment by kroitor** [comment]
@npomfret i see... we will look into adding a scraper for that link you posted above and will make the link itself configurable, in case they migrate...

**Comment by npomfret** [comment]
Ok, I opened another ticket and got an answer. Sadly it is to scrape from here: https://blog.cex.io/news/engine-updates-16956

**Comment by kroitor** [comment]
@npomfret thx for the followup! I will get to writing that scraper then, hope to add it this week.

**Comment by npomfret** [comment]
I've also requested that they add this to the API.  However, I've been asking them for stuff for years, including really simply things like documenting the field in the API. Nothing has ever changed.

**Comment by npomfret** [comment]
@kroitor  Stooooop!  Found it: https://cex.io/api/currency_profile

**Comment by kroitor** [comment]
@npomfret great, thanks for the update! Do you have an idea of what `scale` means there?

**Comment by npomfret** [comment]
I don't no.  But I will ask.

**Comment by npomfret** [comment]
@kroitor did you make any progress?  I can take a look if you don't have time.

**Comment by kroitor** [comment]
@npomfret tbh, i haven't approached it yet, the task at hand is pretty straightforward, though. I just need a few free hours to work on it... I would be happy if you could help with it. The main goal is to implement `fetchCurrencies` for CEX, however, in order to avoid loading the same resource twice in both `fetchCurrencies` and `fetchMarkets` for precision info, we should cache the `fetchCurrencies` as done here, for example:

- https://github.com/ccxt/ccxt/blob/master/js/braziliex.js#L79
- https://github.com/ccxt/ccxt/blob/master/js/mandala.js#L275

The comment there says:

```JavaScript
// this method is now redundant
// currencies are now fetched before markets
```

... but it's not entirely true. This migration is not completed yet, therefore we have to keep `fetchCurrenciesFromCache` there for a while, until we resolve this in the base code implementations of `loadMarkets`.

So, if you can help with any part of the work described above, or if you can implement `fetchCurrencies` for it at the very least – that would help speed things up. Your PRs and contributions are always welcome! Thx!

**Comment by npomfret** [comment]
The issue was with fetch markets, not currencies though.

**Comment by kroitor** [comment]
> The issue was with fetch markets, not currencies though.

@npomfret yes, however, we'd want to fix it right, and in order to get precision values for the market, we will need to look for the info that is available in currencies, thus, we will need `fetchCurrencies`... but, no worries, I'll add that in a few hours, I hope.

**Comment by kroitor** [comment]
@npomfret 

> The correct price precision in this case is 4 apparently.

Can you elaborate a bit on how you got `4` for `ETH/EUR` ?
