### ISSUE TITLE
Leftover "self"

### ISSUE THREAD

**Issue by amigus** [ccxt/ccxt#5747]
https://github.com/ccxt/ccxt/blob/ab2844264fe93f7b5c6976e3a09077a183bb7b06/python/ccxt/base/exchange.py#L760

@staticmethod with first argument 'self'

**Comment by kroitor** [comment]
@amigus good catch, thx!

**Comment by kroitor** [comment]
Fixed in 1.18.1103 (it will be available for downloading in 15 minutes).
