### ISSUE TITLE
Error handling function reports: "TypeError: Cannot read property 'indexOf' of undefined"

### ISSUE THREAD

**Issue by agreatfool** [ccxt/ccxt#5749]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: OSX 10.14.6
- Programming Language version: js
- CCXT version: 1.18.1093
- Exchange: Livecoin
- Method: createOrder

Call `createOrder` with not enough funds. Platform returns error, but ccxt throws it own error: "TypeError: Cannot read property 'indexOf' of undefined".

```
TypeError: Cannot read property 'indexOf' of undefined
    at livecoin.findBroadlyMatchedKey (/.../node_modules/ccxt/js/base/Exchange.js:545:24)
    at livecoin.handleErrors (/.../node_modules/ccxt/js/livecoin.js:905:33)
    at response.text.then (/.../node_modules/ccxt/js/base/Exchange.js:629:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Go to code `node_modules/ccxt/js/base/Exchange.js:545`:

```
if (string.indexOf (key) >= 0)
```

That means `string` is undefined.

Fix it:
```
if (string && string.indexOf (key) >= 0)
```

Now It's OK with correct error message `insufficient funds`:

```
{ ExchangeError: livecoin {"success":false,"added":false,"orderId":null,"exception":"insufficient funds"}
    at livecoin.handleErrors (/.../node_modules/ccxt/js/livecoin.js:914:19)
    at response.text.then (/.../node_modules/ccxt/js/base/Exchange.js:629:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  constructor: [Function: ExchangeError],
  name: 'ExchangeError' }
```

**Comment by fan-tom** [comment]
Seems that it is the same issue as #5746

**Comment by kroitor** [comment]
@fan-tom yes, looks like it... Will fix it shortly. The fix described in the OP, is wrong, however, since it will not throw InsufficientFunds exception type, and will throw ExchangeError instead. I will add a proper fix to it, since it has nothing to do with `findBroadlyMatchedKey` at all – the error happens long before outside of it, in the `handleErrors` method when parsing the error response for livecoin.
