### ISSUE TITLE
New Exchange: NSE/BSE

### ISSUE THREAD

**Issue by ravirajlondhepatil** [ccxt/ccxt#5752]
Hello,
How can we include these stock exchanges to ccxt?

**Comment by kroitor** [comment]
Hi!

See the guidelines here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

**Comment by ravirajlondhepatil** [comment]
Hi, 
many thanks for your comment.
I am sorry, I was not clear in my request. 
can we add NSE/BSE Indian Stock exchanges to ccxt?

thanks in advance.

with best regards,
Ravi

**Comment by kroitor** [comment]
@ravirajlondhepatil in general, the exchanges are either added by our contributors, or by the CCXT Dev Team. If the exchange has a complete API, we don't see why it could not be added to CCXT. If you want us to do the integration job for you, you can reach out to us at info@ccxt.trade. Thx!

**Comment by hiteshbhatia3559** [comment]
Dont think this is possible - the NSE and BSE APIs are provided to clearing members and CTCL ids - which are paid.

**Comment by frosty00** [comment]
not a crypto exchange api
