### ISSUE TITLE
PHP fetchBalance has no parameters.

### ISSUE THREAD

**Issue by devsi** [ccxt/ccxt#5753]
- Programming Language version: PHP
- CCXT version:  1.18.1107
- Exchange: N/A
- Method: fetchBalance

One of our devs has spotted this. The Exchange.php base class contains camel case `fetchBalance()` but it doesn't accept any parameters. If calling `$exchange->fetchBalance($params);` in PHP then the params just get ignored or it would throw an error. It only works if you call snake case `fetch_balance($params)`. 

https://github.com/ccxt/ccxt/blob/master/php/Exchange.php#L1986

**Comment by devsi** [comment]
Discovered because Kucoin fetchBalance defaults to 'trade' account. Which I think is another problem. Why would it default to trade? Main account would make much more sense.

https://github.com/ccxt/ccxt/blob/master/js/kucoin.js#L1333

Tested when trying to call PHP `fetchBalance(['type' => 'main'])`

**Comment by kroitor** [comment]
Will fix the PHP issue, thx for reporting!

> Worth opening another issue for this?

Nope )

> Why would it default to trade?

This is done for historical reasons, it will always default to the trading balance, the actual balance from where funds are used for trading. The logic behind it is that subsequent calls to `fetchBalance () , createOrder (), fetchBalance ()` should show the difference in assets. The same is true for all exchanges throughout the lib. Most often it defaults to the spot trading account.
