### ISSUE TITLE
Bitfinex USD does not get converted to USDT

### ISSUE THREAD

**Issue by JimothyHemingway** [ccxt/ccxt#5754]
The lastest version of CCXT doesn't perform the USD -> USDT conversion.

Here is an example payload:
```
>>> b.fetch_balance()['free']
{....'REP': 0.14358233, 'USD': 204.54503243, ...}
```

I think the proper response should be:
```
>>> b.fetch_balance()['free']
{....'REP': 0.14358233, 'USDT': 204.54503243, ...}
```

This is the relevant section of the manual:
USD → USDT: Some exchanges, like Bitfinex, HitBTC and a few other name the currency as USD in their listings, but those markets are actually trading USDT. The confusion can come from a 3-letter limitation on symbol names or may be due to other reasons. In cases where the traded currency is actually USDT and is not USD – the CCXT library will perform USD → USDT conversion. Note, however, that some exchanges have both USD and USDT symbols, for example, Kraken has a USDT/USD trading pair.

- OS: Ubuntu
- Programming Language version: Python 3.7.2
- CCXT version: ccxt-1.18.1107
- Exchange: Bitfinex
- Method: fetch_balance

**Comment by kroitor** [comment]
@JimothyHemingway plz see this announcement

- https://github.com/ccxt/ccxt/issues/4285

Those codes have been switched long ago, since they introduced a USDT/USD pair.

Let us know if that does not answer the question.

**Comment by JimothyHemingway** [comment]
My bad! Thanks for the info.

**Comment by brunohaetinger** [comment]
@kroitor , so, if I have something like this on my `bitfinex.fetchBalance()` response:
```
{
    free:{
        USD: 500.0
    }
}
```

Actually I have 500 USD or it would be the USDT?
