### ISSUE TITLE
Kucoin v2 API missing essential parameters? 

### ISSUE THREAD

**Issue by karlandoh** [ccxt/ccxt#5755]
- OS: Linux
- Programming Language version: Python3
- CCXT version: Latest
- Exchange: kucoin2
- Method: ```createLimitOrder```

I will list the JSONs of both binance (with all parameters) vs kucoin (which prints some parameters). Using 1000 TRX/BTC (buyorder) as an example.

Binance (everything is fine).

```
{'amount': 1000.0,
 'average': None,
 'cost': 0.0,
 'datetime': '2019-08-29T22:34:37.822Z',
 'fee': None,
 'filled': 0.0,
 'id': PERSONALLY OMITTED,
 'info': {'clientOrderId': PERSONALLY OMITTED,
          'cummulativeQuoteQty': '0.00000000',
          'executedQty': '0.00000000',
          'orderId': 135738359,
          'orderListId': -1,
          'origQty': '1000.00000000',
          'price': '0.00000100',
          'side': 'BUY',
          'status': 'NEW',
          'symbol': 'TRXBTC',
          'timeInForce': 'GTC',
          'transactTime': 1567118077822,
          'type': 'LIMIT'},
 'lastTradeTimestamp': None,
 'price': 1e-06,
 'remaining': 1000.0,
 'side': 'buy',
 'status': 'open',
 'symbol': 'TRX/BTC',
 'timestamp': 1567118077822,
 'trades': None,
 'type': 'limit'}
```
Kucoin

```
{'clientOid': PERSONALLY OMITTED,
 'id': PERSONALLY OMITTED,
 'info': {'orderId':PERSONALLY OMITTED},
 'side': 'buy',
 'status': 'open',
 'symbol': 'TRX/BTC',
 'type': 'limit'}
```

Would love some professional insight, and recommendations. **I GREATLY need the amount and price parameters on my exchange orders.**

Thanks for viewing.

**Comment by kroitor** [comment]
Thank you! Going to add the rest of the fields to the createOrder response shortly.

**Comment by kroitor** [comment]
@karlandoh sorry for the long wait on this one, going to get to it and will resolve it asap.
