### ISSUE TITLE
Kucoin constructed symbol doesn't match API symbol

### ISSUE THREAD

**Issue by benoist** [ccxt/ccxt#5756]
KuCoin has renamed a market DADI to EDGE but has decided not to change the symbol

This now causes a symbol mismatch as the fetch_markets constructs the symbol from the base and the quote

REST API symbol: DADI/ETH
CCXT symbol: EDGE/ETH

The same is true for BTC and USDT

CCXT version: 1.18.1108

**Comment by kroitor** [comment]
> This now causes a symbol mismatch as the fetch_markets constructs the symbol from the base and the quote

Sorry, can you elaborate plz? What kind of mismatch do you mean?

Also, are you familiar with:

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

?

**Comment by benoist** [comment]
```json
{
"symbol": "DADI-ETH",
"quoteMaxSize": "99999999",
"enableTrading": true,
"priceIncrement": "0.0000001",
"feeCurrency": "ETH",
"baseMaxSize": "10000000000",
"baseCurrency": "EDGE",
"quoteCurrency": "ETH",
"market": "ETH",
"quoteIncrement": "0.0000001",
"baseMinSize": "1",
"quoteMinSize": "0.0001",
"name": "EDGE-ETH",
"baseIncrement": "0.0001"
},
```

If thats the case, then market id should not use the name field, but the symbol field right?

**Comment by kroitor** [comment]
@benoist thx! This should be fixed in 1.18.1109 and it will arrive in 15 minutes. I've tested it on my side and it should work. We will be happy if you let us know, whether it does solve the issue for you or not.

**Comment by benoist** [comment]
FYI the php version has the same issue

**Comment by kroitor** [comment]
@benoist 

- https://github.com/ccxt/ccxt/wiki/FAQ#hey-the-fix-youve-uploaded-is-in-js-would-you-fix-python--php-as-well-please

;))

**Comment by kroitor** [comment]
More about it here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support )

**Comment by benoist** [comment]
That is pretty cool, did not know that :)

**Comment by kroitor** [comment]
@benoist in the meantime, this issue should already be fixed by now, let us know if have any other difficulties with it) Thx again for reporting!

**Comment by benoist** [comment]
@kroitor I just tested it and I can confirm this fixed the issue. Thanks for the fast responses as always!!
