### ISSUE TITLE
safeTimestamp should not decrease resolution

### ISSUE THREAD

**Issue by brandsimon** [ccxt/ccxt#5758]
As I see it, in every language safeTimestamp is parsing the value as int, then multiplying with 1000. I think it should be the other way around to not reduce the resolution of the timestamp.
Parsing as float, multiplying, parsing as int.
```
int(12512515.123) * 1000 = 12512515000
int(12512515.123 * 1000) = 12512515123
```

**Comment by brandsimon** [comment]
Any thoughts on this? I would write a PR when I have time.

**Comment by kroitor** [comment]
@brandsimon totally agree with you! Your help is much appreciated!

**Comment by brandsimon** [comment]
@kroitor Great, thank you for your work!
