### ISSUE TITLE
BTCAlpha order amount showing 0.0, despite successful fetch.

### ISSUE THREAD

**Issue by karlandoh** [ccxt/ccxt#5760]
- OS: Linux
- Programming Language version: Python3
- CCXT version: Latest
- Exchange: btcalpha
- Method: ```createLimitOrder```

Managed to find a bug in creating orders for btcalpha. Notice how the **amount**  gives **0.0**, but the **trades->amount parameter** shows a successful fetch. A small, and easily fixable bug, but nonetheless there.

Ive noticed that usually, the info parameter contains the original fetched JSON. It also has blank information. Maybe that could help?

As usual, thanks so much for viewing.

```
{'amount': 0.0,
 'cost': None,
 'datetime': '2019-08-31T01:06:13.000Z',
 'fee': None,
 'filled': None,
 'id': '95397214',
 'info': {'amount': 0.0,
          'date': 1567213573.123048,
          'oid': 95397214,
          'price': 1.64e-06,
          'success': True,
          'trades': [{'amount': 219.51219512,
                      'o_id': 95374386,
                      'price': 1.64e-06,
                      'tid': 37564716,
                      'type': 'buy'}],
          'type': 'sell'},
 'price': 1.64e-06,
 'remaining': None,
 'side': 'sell',
 'status': None,
 'symbol': 'TRX/BTC',
 'timestamp': 1567213573000,
 'trades': [{'amount': 219.51219512,
             'cost': 0.00036,
             'datetime': None,
             'fee': None,
             'id': '37564716',
             'info': {'amount': 219.51219512,
                      'o_id': 95374386,
                      'price': 1.64e-06,
                      'tid': 37564716,
                      'type': 'buy'},
             'order': '95374386',
             'price': 1.64e-06,
             'side': None,
             'symbol': 'TRX/BTC',
             'takerOrMaker': None,
             'timestamp': None,
             'type': 'limit'}],
 'type': 'limit'}
```

**Comment by kroitor** [comment]
> Ive noticed that usually, the info parameter contains the original fetched JSON. It also has blank information. Maybe that could help?

It will always contain the original fetched JSON. CCXT takes that info and populates the fields outside of `info` according to the unified order structure.

- https://github.com/ccxt/ccxt/wiki/Manual#order-structure

And, as you noted precisely in the original response from the exchange the amount is 0.0...

What was the original `amount` submitted to `createLimitOrder`?

We could resolve this faster if you could always follow these guidelines precisely (to a word) and include your **verbose request and response** when submitting issues:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by kroitor** [comment]
@karlandoh can you plz tell the original `amount` submitted to `createLimitOrder` ?
