### ISSUE TITLE
Question: How to pass parameters in a bitmex function private_get_position

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#5769]
How to pass a filter parameter in the bitmex function self.exchange.private_get_position ?

I want to get a list of open positions for XBTUSD

The sample below doesn't work 
self.exchange.private_get_position(filter={"isOpen":"true", "symbol":"XBTUSD"})

Links 
https://www.bitmex.com/api/explorer/#!/Position/Position_get
https://github.com/ccxt/ccxt/issues/250

- OS:
Windows 10
- Programming Language version:
Python 3.7
- CCXT version:
1.18.1115
- Exchange:
bitmex
- Method:
private_get_position

**Comment by kroitor** [comment]
You do that like it is described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods

```Python
self.exchange.private_get_position({
    'filter': {"isOpen":"true", "symbol":"XBTUSD"}
})
```

Let us know if that does not help.

**Comment by YuriyTigiev** [comment]
I don't have any open position 

I have modified the code how you supposed 

```
for position in self.exchange.private_get_position({'filter': self.exchange.json({"isOpen":"true", "symbol":self.pair})}):
    print(position)
```

but the loop still returns records. 
I'm using the https://testnet.bitmex.com


{'account': 241535, 'symbol': 'XBTUSD', 'currency': 'XBt', 'underlying': 'XBT', 'quoteCurrency': 'USD', 'commission': 0.00075, 'initMarginReq': 0.1, 'maintMarginReq': 0.005, 'riskLimit': 20000000000, 'leverage': 10, 'crossMargin': False, 'deleveragePercentile': None, 'rebalancedPnl': -399423, 'prevRealisedPnl': -1084, 'prevUnrealisedPnl': 0, 'prevClosePrice': 10433.48, 'openingTimestamp': '2019-09-03T18:00:00.000Z', 'openingQty': 0, 'openingCost': -407928, 'openingComm': 8505, 'openOrderBuyQty': 0, 'openOrderBuyCost': 0, 'openOrderBuyPremium': 0, 'openOrderSellQty': 0, 'openOrderSellCost': 0, 'openOrderSellPremium': 0, 'execBuyQty': 0, 'execBuyCost': 0, 'execSellQty': 0, 'execSellCost': 0, 'execQty': 0, 'execCost': 0, 'execComm': 0, 'currentTimestamp': '2019-09-03T18:00:00.280Z', 'currentQty': 0, 'currentCost': -407928, 'currentComm': 8505, 'realisedCost': -407928, 'unrealisedCost': 0, 'grossOpenCost': 0, 'grossOpenPremium': 0, 'grossExecCost': 0, 'isOpen': False, 'markPrice': None, 'markValue': 0, 'riskValue': 0, 'homeNotional': 0, 'foreignNotional': 0, 'posState': '', 'posCost': 0, 'posCost2': 0, 'posCross': 0, 'posInit': 0, 'posComm': 0, 'posLoss': 0, 'posMargin': 0, 'posMaint': 0, 'posAllowance': 0, 'taxableMargin': 0, 'initMargin': 0, 'maintMargin': 0, 'sessionMargin': 0, 'targetExcessMargin': 0, 'varMargin': 0, 'realisedGrossPnl': 407928, 'realisedTax': 0, 'realisedPnl': 399423, 'unrealisedGrossPnl': 0, 'longBankrupt': 0, 'shortBankrupt': 0, 'taxBase': 407928, 'indicativeTaxRate': 0, 'indicativeTax': 0, 'unrealisedTax': 0, 'unrealisedPnl': 0, 'unrealisedPnlPcnt': 0, 'unrealisedRoePcnt': 0, 'simpleQty': None, 'simpleCost': None, 'simpleValue': None, 'simplePnl': None, 'simplePnlPcnt': None, 'avgCostPrice': None, 'avgEntryPrice': None, 'breakEvenPrice': None, 'marginCallPrice': None, 'liquidationPrice': None, 'bankruptPrice': None, 'timestamp': '2019-09-03T18:00:00.280Z', 'lastPrice': None, 'lastValue': 0}

**Comment by kroitor** [comment]
@YuriyTigiev there is a typo there, BitMEX expects isOpen to be a boolean value (`True/False`), not a string (`"true"/"false"`).

```Python
self.exchange.private_get_position({  #     ↓ HERE
    'filter': self.exchange.json({"isOpen":True, "symbol":"XBTUSD"})
})
```

**Comment by YuriyTigiev** [comment]
Now everything works

Thank you!
