### ISSUE TITLE
How Can I Use Huobi Contract API with ccxt

### ISSUE THREAD

**Issue by mubaizhou** [ccxt/ccxt#5772]
How Can I Use Huobi Contract API with ccxt,please?

**Comment by kroitor** [comment]
Hi! We currently don't have the Huobi endpoints for derivatives, just the spot markets, however, we will look into adding the support for derivatives with Huobi asap. Let us know if that does not answer the question.

**Comment by kroitor** [comment]
The support for Huobi Derivatives was added in CCXT 1.66.16+.
