### ISSUE TITLE
Can't open limit order on lykre

### ISSUE THREAD

**Issue by Arrmlet** [ccxt/ccxt#5775]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- Ubuntu :
- Python 3.6:
- newest:
- Lykke:
- create_order:

Hello everyone:
From something reason I can't place a limit order on lykke exchange:

Example of code:
```
order = self.exchange.create_order(
                    symbol = 'BTC/USD', type = 'Limit', side = 'sell',
                    amount = 0.003, price = 11500)

```

When I'm trying to run this code I get this error:
```
    raise error(' '.join([method, url, string_code, http_status_text, body]))
ccxt.base.errors.ExchangeNotAvailable: POST https://hft-api.lykke.com/api/Orders/limit 400 Bad Request {"Price":["Price must be more than zero."]}
```

Regards,
Volodymyr

**Comment by kroitor** [comment]
@Arrmlet 

> `type = 'Limit'`

↑ should be `type='limit'` in lowercase

If that does not help, please post your **verbose request and response** as described here:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
