### ISSUE TITLE
Kraken fetch_balance missing free amounts

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#5776]
- OS: linux
- Programming Language version: python
- CCXT version: 1.18.1119
- Exchange: kraken
- Method: fetchBalance, fetchFreeBalance

When using kraken's fetch_balance, only "total" is populated, while "free" and "used" are None.

``` python
import ccxt
ct = ccxt.kraken({'apiKey':'', 'secret':''} # login info here

ct.fetchBalance()
```

```
{'info': {'ZEUR': '20.3343',
  'KFEE': '5000.00',
  'XXRP': '111',},
 'EUR': {'free': None, 'used': None, 'total': 20.3343},
 'KFEE': {'free': None, 'used': None, 'total': 5000.0},
 'XRP': {'free': None, 'used': None, 'total': 111},
 'free': {'EUR': None,
  'KFEE': None,
  'XRP': None,
},
 'used': {'EUR': None,
  'KFEE': None,
  'XRP': None,
},
 'total': {'EUR': 20.3343,
  'KFEE': 5000.0,
  'XRP': 111,
}}
```

at least "free" used to be populated in older versions (i tested with 1.18.900) - but i'm not sure when this was changed.

Since Kraken is a certified exchange, i would expect that this function is working correctly and is also showing how much balance is free (available) to trade, and how much is used (tied up in orders).

The Kraken API documentation does not seem to mention that this is part of the output, which makes me wonder how this exchange can be certified, if such basic information is not available. 
Before opening a trade you should know how much is still available for trading - otherwise errors like "not enough balance" are guaranteed when calling `create_trade()`. 

Honestly, from certified exchanges i would expect unified / the same behaviour for such common methods (i can understand that this cannot be the case 100% for all methods).

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/issues/5587#issuecomment-514520057
- https://github.com/ccxt/ccxt/issues/5292
- https://github.com/ccxt/ccxt/pull/5290

Let us know if that does not answer the question.

**Comment by xmatthias** [comment]
Hi @kroitor,

Can you then please specify what the exact criteria for a certified exchange are?

As mentioned above, i can understand that kraken does not return this value (and ccxt should not invent it) - but i  think a certified exchange should return this - or loose the certification status, unless ccxt certification is based on money, and not on functionality.

**Comment by kroitor** [comment]
> Can you then please specify what the exact criteria for a certified exchange are?

- https://github.com/ccxt/ccxt/wiki/Requirements

↑ These requirements say that the exchange must have certain methods, and the response coming from those methods should be unified as documented in the Manual. Kraken has `fetchBalance`, and if we look into the documentation for `fetchBalance` it says that some values may be missing. So, technically speaking, Kraken does satisfy the requirements and it is unified.

Technically, retrieving the balance used in orders with `fetchOpenOrders` is possible, so, the info is not missing, it's provided in a different endpoint. 

Certification means that the code of the integration is done with respect to all the rules and has as few bugs as possible, and it is maintained by the CCXT Dev Team. And yet it doesn't necessarily mean that CCXT guarantees that an exchange will have this or that field in the API. It tends to guarantee that if the field in question is present – it will be properly parsed and unified. Which is true (mostly). 

We do understand that this adds certain complexities on the user side when working with balances, however. So, we will consider adding more clarifications to the certification process and will also revise the certification requirements.

**Comment by xmatthias** [comment]
The [link](https://github.com/ccxt/ccxt/wiki/Requirements) does list the requirements for the integration - not for the certification (i assume the bar is higher for that, otherwise a lot more exchanges should be certified).

> Getting integrated and certified requires the exchange to implement a quality API.
source: https://github.com/ccxt/ccxt/wiki/Certification

This suggests that the API should be of a certain quality - providing simple access to balance data should be one of these quality criteria (and the *quality* criteria are unclear, since they are not documented anywhere i could find them).

> Certification means that the code of the integration is done with respect to all the rules and has as few bugs as possible

Honestly, i would expect this to be true for every integration, not only for certified ones.
My understanding of certification was that the exchange meets a certain quality criteria (in regards of both stability and providing data).

Especially with kraken, the `fetchOpenOrders()` approach seems unfeasible since they rate-limit very aggressive, making acquiring balances and free balances within a certain timeframe (say 1s) impossible.

**Comment by kroitor** [comment]
> The link does list the requirements for the integration not for the certification

I will add more clarifications to that page on the certification specifically and will also clarify the criteria as well.
