### ISSUE TITLE
ZB load_accounts() error

### ISSUE THREAD

**Issue by bitProfessor** [ccxt/ccxt#5780]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

OS:mac os
Programming Language version:python
CCXT version:1.18.940
Exchange:zb
Method:load_accounts()
get_account 124  : 'zb' object has no attribute 'fetch_accounts'

ps:i just want to fetch my account name

**Comment by kroitor** [comment]
@bitProfessor sorry, but you should check the `has` metadata for `fetchAccounts` before trying to access that data.

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties
- https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata

Alternatively, you can use the implicit API methods to call their endpoints:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#implicit-api-methods

Let us know if that does not answer the question.
