### ISSUE TITLE
BITMEX: How to determine maximum leverage for a symbol?

### ISSUE THREAD

**Issue by azharuniverse** [ccxt/ccxt#5781]
I have gone through all the api's of bitmex but not able to understand how to find maximium available leverage for a particular symbol for eg. **XRPU19 is 20X** where to find this data for all the symbols.

**Comment by kroitor** [comment]
@azharuniverse does this help https://www.bitmex.com/app/faq#How-much-leverage-does-BitMEX-offer ?

**Comment by azharuniverse** [comment]
They have mentioned 

> Leverage is determined by the Initial Margin and Maintenance Margin levels

But I can't find or formulate relationship between Initial Margin, Maintenance Margin and Maximum Leverage.
Is there a formula to calculate Maximum Leverage?

**Comment by azharuniverse** [comment]
After studying all the data. I came up with a formula which is not mentioned anywhere on Bitmex documentation.

`Currently allowed leverage = Max Leverage * Base Risk Limit / Current Risk Limit`
Eg: Symbol XBTUSDT, Current Risk Limit = 500
Currently allowed leverage = 100 * 200 / 500 = 40

But still, I have to hard code Max Leverage for Base Risk Limit because this data is not available in any API. I wonder why they omitted the most important data and return a lot of unnecessary data which developer don't need.

**Comment by kroitor** [comment]
@azharuniverse well, you're right, BitMEX does not define the value of `Max Leverage` anywhere in the API or in the docs, so, I guess you probably want to ask their tech support about it. Let us know if there's anything we can do to help you with this.
