### ISSUE TITLE
Lykke can't see side of order.

### ISSUE THREAD

**Issue by Arrmlet** [ccxt/ccxt#5783]
- Ubuntu:
- Python3:
- newest:
- Lykke:
- Fetch open orders:

Hello, from something reason I can't see the side of order:
i.e
I run the command:
`pprint(lykke.load_open_orders('WAX/BTC'))`

And I got the following output:
```
{'amount': 10.0,
  'average': None,
  'cost': 0.0,
  'datetime': '2019-09-07T16:01:35.612Z',
  'fee': None,
  'filled': 0.0,
  'id': '7a3b3cfb-251d-4023-9d59-39e9079fd7b4',
  'info': {'AssetPairId': 'WAXBTC',
           'CreatedAt': '2019-09-07T16:01:35.612+00:00',
           'Id': '7a3b3cfb-251d-4023-9d59-39e9079fd7b4',
           'LastMatchTime': None,
           'LowerLimitPrice': None,
           'LowerPrice': None,
           'Price': 3e-06,
           'RemainingVolume': 10.0,
           'Status': 'Placed',
           'Type': 'Limit',
           'UpperLimitPrice': None,
           'UpperPrice': None,
           'Volume': 10.0},
  'lastTradeTimestamp': None,
  'price': 3e-06,
  'remaining': 10.0,
  'side': None,
  'status': 'Placed',
  'symbol': 'WAX/BTC',
  'timestamp': 1567872095612,
  'type': None}]

```
Why I 'side' is None??

**Comment by kroitor** [comment]
Hi!

In the response you get from a unified `fetch*` call (any fetch call) – you see the `info` that corresponds to the original raw response from the exchange, untouched, as documented in the Manual. In that response you see no designation of the side of the order. Therefore the `side` cannot be determined from the exchange response in that case. So, in short, this is a limitation on the exchange side, and you probably want to question their tech support on this.

Let us know if that does not answer the question.

**Comment by Arrmlet** [comment]
Thanks
