### ISSUE TITLE
Mandala Certified

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#5787]
Hello dear CCXT users! )

We are pleased to announce that the [**Mandala Exchange**](https://mandalaex.com) has joined the list of exchanges certified with CCXT and this is official! )

Please, see this special announcement: **[Mandala is Now CCXT Certified](https://medium.com/mandalaex/mandala-is-now-ccxt-certified-9155768f8181)**

--------------

|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;logo&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                                                             | id       | name                                                         | ver | doc                                                                                          | certified                                                                                                                  |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------|--------------------------------------------------------------|:---:|:--------------------------------------------------------------------------------------------:|----------------------------------------------------------------------------------------------------------------------------|
|[![mandala](https://user-images.githubusercontent.com/1294454/54686665-df629400-4b2a-11e9-84d3-d88856367dd7.jpg)](https://trade.mandalaex.com/?ref=564377)                   | mandala  | [Mandala](https://trade.mandalaex.com/?ref=564377)                   | 2   | [API](https://apidocs.mandalaex.com)                                                         | [![CCXT Certified](https://img.shields.io/badge/CCXT-certified-green.svg)](https://github.com/ccxt/ccxt/wiki/Certification) | Malta                 |

https://github.com/ccxt/ccxt#certified-cryptocurrency-exchanges

We have added the most recent updates including the v2 API to the Mandala API implementation, with new endpoints and unified methods.

Let us know if you have any questions, will be happy to answer!

Thanks for using Mandala with CCXT! )

**Comment by P3DBackUp** [comment]
Mandala not answering communications
