### ISSUE TITLE
[cex] amount not rounded correctly

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5796]
Am investigating the following:

Placed order: 

`{"pair":"ETH/EUR","type":"sell","amount":"0.55961212","price":"161.91"}`

Got response:

 `{"info":{"complete":true,"id":"10169373833","time":1568277950466,"pending":"0.00000000","amount":"0.55961200","type":"sell","price":"161.91"},"id":"10169373833"}`

The amount requested was _0.55961212_, but the order on the exchange is for _0.55961200_ (same precision, but a lower accuracy).

The API (https://cex.io/api/currency_profile) shows:

```
{
"symbol1": "ETH",
"symbol2": "EUR",
"pricePrecision": 2,
"priceScale": "/10000",
"minLotSize": 0.1,
"minLotSizeS2": 20
}
```

and

```
{
"code": "ETH",
"contract": false,
"commodity": false,
"fiat": false,
"description": "",
"precision": 8,
"scale": 2,
"minimumCurrencyAmount": "0.00000100",
"minimalWithdrawalAmount": 0.01
},
{
"code": "EUR",
"contract": false,
"commodity": false,
"fiat": true,
"description": "",
"precision": 2,
"scale": 0,
"minimumCurrencyAmount": "0.01",
"minimalWithdrawalAmount": -1
}
```
My ccxt markets have:

```
"ETH/EUR": {
"limits": {
"amount": {
"min": 0.1
},
"price": {
"min": 15,
"max": 4096
},
"cost": {
"min": 20
}
},
"precision": {
"amount": 8,
"price": 2
},
"id": "ETH/EUR",
"info": {
"symbol1": "ETH",
"symbol2": "EUR",
"minLotSize": 0.1,
"minLotSizeS2": 20,
"maxLotSize": null,
"minPrice": "15",
"maxPrice": "4096"
},
...
}
```

**Comment by npomfret** [comment]
Did we ever get to the bottom of the crazy complicated CEX logic?   I'm still getting errors:

For example: the following order `{"side":"buy","marketSymbol":"BCH/BTC","amount":"0.09849298","price":"0.028713"}`

Results in: `"InvalidOrder: cex {\"error\":\"There was an error while placing your order: Invalid amount\"`

**Comment by kroitor** [comment]
@npomfret with your verbose output we could resolve this quicker, if you can post it, plz do.

**Comment by npomfret** [comment]
Hmm, sorry pls ignore for now.  When I place the order from my desktop it goes through ok...  investigating.
