### ISSUE TITLE
New HitBTC v2 API

### ISSUE THREAD

**Issue by flesler** [ccxt/ccxt#580]
Here are the docs: https://api.hitbtc.com/#candles

**Comment by kroitor** [comment]
Hi, @flesler !

Thanks, we know, of course, of their new API, we are updating the sources to match it now. Thx again!

**Comment by flesler** [comment]
Than you for the hard work

**Comment by kroitor** [comment]
FetchOHLCV has been added to HitBTC v2 in 1.10.150. Thx for the feedback!
