### ISSUE TITLE
Error using ccxt for testnet.bitmex.com private functions.

### ISSUE THREAD

**Issue by xinglong717** [ccxt/ccxt#5810]
I've tried to use following code. 

import ccxt
exchanges = {'bitmex': ccxt.bitmex()}
btmx = ccxt.bitmex({
    'apiKey': 'bzHFktf887ap1OCtmAHPADGV',
    'secret':'9rzLlTMjirx_Gh6OwaCDcpKFaxWJ3aEQiYuvUT4Z8LpHe_qB',
})
if 'test' in btmx.urls:
    btmx.urls['api']=btmx.urls['test']
    exchanges['bitmex'].urls['api'] = exchanges['bitmex'].urls['test']
print(btmx.fetch_balance())

But got following errors.

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\ccxt\base\exchange.py", line 539, in fetch
    response.raise_for_status()
  File "C:\Python37\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://testnet.bitmex.com/api/v1/instrument/activeAndIndices

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python_work\bitmex\__init__.py", line 11, in <module>
    print(btmx.fetch_balance())
  File "C:\Python37\lib\site-packages\ccxt\bitmex.py", line 251, in fetch_balance
    self.load_markets()
  File "C:\Python37\lib\site-packages\ccxt\base\exchange.py", line 1234, in load_markets
    markets = self.fetch_markets(params)
  File "C:\Python37\lib\site-packages\ccxt\bitmex.py", line 171, in fetch_markets
    response = self.publicGetInstrumentActiveAndIndices(params)
  File "C:\Python37\lib\site-packages\ccxt\base\exchange.py", line 435, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Python37\lib\site-packages\ccxt\base\exchange.py", line 458, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Python37\lib\site-packages\ccxt\base\exchange.py", line 454, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Python37\lib\site-packages\ccxt\base\exchange.py", line 551, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Python37\lib\site-packages\ccxt\bitmex.py", line 1154, in handle_errors
    raise BadRequest(feedback)
ccxt.base.errors.BadRequest: bitmex {"error":{"message":"This request has expired - `expires` is in the past. Current time: 1568479326","name":"HTTPError"}}

- OS: windows 10
- Programming Language version: python 3.7.3
- CCXT version: installed just now
- Exchange: bitmex
- Method: fetch_balance()

**Comment by kroitor** [comment]
@xinglong717 have you tried anything from here:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

If you have, which particular steps have you tried already?

**Comment by xinglong717** [comment]
All the same.
Current using key created in testnet. And this key need not to use in realnet.
And this key is working now in C# code.
And of course timezone is UTC.
I ca'nt resolve this problem.

**Comment by kroitor** [comment]
@xinglong717 it works on my side:

```Python
import ccxt
btmx = ccxt.bitmex({
   'apiKey': 'bzHFktf887ap1OCtmAHPADGV',
   'secret':'9rzLlTMjirx_Gh6OwaCDcpKFaxWJ3aEQiYuvUT4Z8LpHe_qB',
   'enableRateLimit': True,
})

if 'test' in btmx.urls:
    btmx.urls['api']=btmx.urls['test']
    btmx.urls['api'] = btmx.urls['test']

print(btmx.fetch_balance())
```

<img width="1124" alt="Screen Shot 2019-09-14 at 20 22 27" src="https://user-images.githubusercontent.com/1294454/64911662-6769d500-d72d-11e9-9cf9-df00dc0fcb9b.png">

What's your version of CCXT?

**Comment by xinglong717** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/32957829/64911745-f6481300-d768-11e9-9d50-df38d4299d3f.png)

**Comment by xinglong717** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/32957829/64911756-1bd51c80-d769-11e9-9c95-b6309cc8f388.png)

**Comment by xinglong717** [comment]
On my side , this key is working with C#.
But do'nt work with python.
When using ccxt, must config python for ccxt?

**Comment by kroitor** [comment]
@xinglong717 is this URL accessible from your browser:

https://testnet.bitmex.com/api/v1/instrument/activeAndIndices 

?

**Comment by xinglong717** [comment]
yes, just connected.
![image](https://user-images.githubusercontent.com/32957829/64911910-1c6eb280-d76b-11e9-9c44-fed9c382844c.png)

**Comment by kroitor** [comment]
@xinglong717 can you verify it against a non-windows system to make sure that everything is ok?
Also, are you sure that

> And of course timezone is UTC.

?

Can you post your verbose request/response output, as described here:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

?

```Python
import ccxt
btmx = ccxt.bitmex({
   'apiKey': 'bzHFktf887ap1OCtmAHPADGV',
   'secret':'9rzLlTMjirx_Gh6OwaCDcpKFaxWJ3aEQiYuvUT4Z8LpHe_qB',
   'enableRateLimit': True,
   'verbose': True,
})

if 'test' in btmx.urls:
    btmx.urls['api']=btmx.urls['test']
    btmx.urls['api'] = btmx.urls['test']

print('Current time:', btmx.iso8601(btmx.milliseconds())
print(btmx.fetch_balance())
print('Current time:', btmx.iso8601(btmx.milliseconds())
```

- Are you located in China?
- Have you tried with a proxy or a CORS proxy?

**Comment by kroitor** [comment]
@xinglong717 does this work:

```Python
import ccxt
btmx = ccxt.bitmex({
   'apiKey': 'bzHFktf887ap1OCtmAHPADGV',
   'secret':'9rzLlTMjirx_Gh6OwaCDcpKFaxWJ3aEQiYuvUT4Z8LpHe_qB',
   'enableRateLimit': True,
   'proxy': 'https://cors-anywhere.herokuapp.com/',
   'origin': 'bitmex',
})

if 'test' in btmx.urls:
    btmx.urls['api']=btmx.urls['test']
    btmx.urls['api'] = btmx.urls['test']

print(btmx.fetch_balance())
```

?

**Comment by xinglong717** [comment]
How can I use proxy for python ccxt request ?

**Comment by kroitor** [comment]
> How can I use proxy for python ccxt request ?

Yep, you need to use `exchange.proxy` with a CORS type proxy or `exchange.proxies` if you use a HTTPS proxy or SOCKS, as described here:

- https://github.com/ccxt/ccxt/wiki/Install#python-proxies

```Python
import ccxt
exchange = ccxt.bitmex({
    'proxies': {
        'http': 'http://10.10.1.10:3128',  # these proxies won't work for you, they are here for example
        'https': 'https://10.10.1.10:1080',
    },
    'enableRateLimit': True,
    # other properties and options...
})
```

Let me know if that does not help.

**Comment by xinglong717** [comment]
Thanks for your help.
following error occured.
ccxt.base.errors.RequestTimeout: GET https://cors-anywhere.herokuapp.com/https://testnet.bitmex.com/api/v1/instrument/activeAndIndices

**Comment by kroitor** [comment]
@xinglong717 

> following error occured.

The error occurred because you've copypasted the code blindly without reading it – you can't copypaste it wiithout editing, you should use your own set of proxies there, and you should not mix CORS `proxy` with HTTPS/SOCKS `proxies`. This is documented in the Manual. Also, in the comments in the code snippet I've posted above it's noted that those proxies won't work – they're just an example of how you should fill up your proxy settings for a HTTPS/SOCKS proxy, but you should put the IP addresses and ports of your own proxy there.

> I've used C# raw code or java xChange library for bitmex private api connect.
> There is no any problem till now.

Can you post a short snippet of your c# code or your code that uses xChange, for comparison?

**Comment by xinglong717** [comment]
private string BuildQueryData(Dictionary<string, string> param)
        {
            if (param == null)                return "";
            StringBuilder b = new StringBuilder();
            foreach (var item in param)
                b.Append(string.Format("&{0}={1}", item.Key, WebUtility.UrlEncode(item.Value)));
            try { return b.ToString().Substring(1); }
            catch (Exception) { return ""; }
        }
        private string BuildJSON(Dictionary<string, string> param)
        {
            if (param == null)                return "";
            var entries = new List<string>();
            foreach (var item in param)
                entries.Add(string.Format("\"{0}\":\"{1}\"", item.Key, item.Value));

            return "{" + string.Join(",", entries) + "}";
        }
        public static string ByteArrayToString(byte[] ba)        {
            StringBuilder hex = new StringBuilder(ba.Length * 2);
            foreach (byte b in ba)
                hex.AppendFormat("{0:x2}", b);
            return hex.ToString();
        }
        private long GetExpires()        {
            return DateTimeOffset.UtcNow.ToUnixTimeSeconds() + 3600; // set expires one hour in the future
        }       
 private string Query(string method, string function, Dictionary<string, string> param = null, bool auth = false, bool json = false)
        {
            string paramData = json ? BuildJSON(param) : BuildQueryData(param);
            string url = "/api/v1" + function + ((method == "GET" && paramData != "") ? "?" + paramData : "");
            string postData = (method != "GET") ? paramData : "";
            HttpWebRequest webRequest = (HttpWebRequest)WebRequest.Create(domain + url);
            webRequest.Method = method;
            if (auth)
            {
                string expires = GetExpires().ToString();
                string message = method + url + expires + postData;
                byte[] signatureBytes = hmacsha256(Encoding.UTF8.GetBytes(apiSecret), Encoding.UTF8.GetBytes(message));
                string signatureString = ByteArrayToString(signatureBytes);
                webRequest.Headers.Add("api-expires", expires);
                webRequest.Headers.Add("api-key", apiKey);
                webRequest.Headers.Add("api-signature", signatureString);
            }
            try
            {
                if (postData != "")
                {
                    webRequest.ContentType = json ? "application/json" : "application/x-www-form-urlencoded";
                    var data = Encoding.UTF8.GetBytes(postData);
                    using (var stream = webRequest.GetRequestStream())
                    {
                        stream.Write(data, 0, data.Length);
                    }
                }
                using (WebResponse webResponse = webRequest.GetResponse())
                using (Stream str = webResponse.GetResponseStream())
                using (StreamReader sr = new StreamReader(str))
                {
                    return sr.ReadToEnd();
                }
            }
            catch (WebException wex)
            {
                using (HttpWebResponse response = (HttpWebResponse)wex.Response)
                {
                    if (response == null)
                        throw;
                    using (Stream str = response.GetResponseStream())
                    {
                        using (StreamReader sr = new StreamReader(str))
                        {
                            return sr.ReadToEnd();
                        }
                    }
                }
            }
        }
        public string GetXBTWalletBallance()
        {
            var param = new Dictionary<string, string>();
            string json = Query("GET", "/user/margin", param, true);
            List<string> items = json.Split(',').ToList<string>();
            string result = items[29];
            return "0."+result.Split(':').ToList<string>()[1];
        }

This is currently working C# code.
Bitmex private api request working well.
If I have proxy problem, how can this c# code working?
I hope you can check this code an help me to make python code.

**Comment by kroitor** [comment]
> If I have proxy problem, how can this c# code working?

That C# code is working, because it has nothing to do with the problem that you have in Python. 

It's a problem accessing a different resource, not the `/user/margin` endpoint. You've posted it initially in your code, however, you've removed it later for some reason, but anyways ))

When you create an exchange instance, and then call any unified method, CCXT will load markets first and will cache those. The process is explained here:

- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

That means it will first issue a different request to a different endpoint, different from the one you're comparing to. That makes the comparison to the above C# code a bit irrelevant to the actual cause of the problem.

From **your own** output above you can see that when you call `fetch_balance` the first time – CCXT will first load those markets from this endpoint:

- https://www.bitmex.com/api/explorer/#!/Instrument/Instrument_getActiveAndIndices
- https://testnet.bitmex.com/api/v1/instrument/activeAndIndices

BitMEX replies with a 400 Bad Request, despite that it does open ok in your browser.

```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://testnet.bitmex.com/api/v1/instrument/activeAndIndices
```

And the details are:

```
ccxt.base.errors.BadRequest: bitmex {"error":{"message":"This request has expired - expires is in the past. Current time: 1568479326","name":"HTTPError"}}
```

In general, CCXT should not send that `api-expires` header for public requests, and this is an issue in CCXT that I'm going to fix shortly. However, that issue would not have caused this specific problen, if your eclipse/python environment was in timesync with BitMEX. Because, it's obviously not, since BitMEX message says "This request has expired - expires is in the past. Current time: 1568479326". This is explained here:

- https://github.com/ccxt/ccxt/issues/4789

If BitMEX says the api-expires header has expired, then it really means it. Your keys do work on my side with bitmex testnet and with the code I posted above. So, it's something system-specific or configuration-specific. And this is very hard to debug, especially, not having the access to your system. In order to find the cause and to fix it we should take smallest steps possible, one at a time. So, I will upload a fix to BitMEX so that public requests get sent without a signature. However, the expectation is that it will not fully resolve the problem, because the `api-expires` issue will still come up later upon a subsequent call to the private balance endpoint. After that we will need you to update your version of CCXT and report back or confirm the expectation. If the error persists as expected, we will continue narrowing it down. I will get back to you shortly on this matter.

**Comment by xinglong717** [comment]
I've updated pre posted code. This code well working with all bitmex private api.
But ccxt not working with any bitmex private api.
Please explain about this problem.

**Comment by kroitor** [comment]
@xinglong717 

```Python
# EXPLANATION

import ccxt
exchange = ccxt.bitmex({
    'apiKey': 'YOUR_API_KEY',
    'secret':'YOUR_SECRET',
    'enableRateLimit': True,
})

if 'test' in exchange.urls:
    exchange.urls['api'] = exchange.urls['test']

try:
    exchange.load_markets ()
except Exception as e:
    error_message = str(e)
    print(error_message)
    if 'This request has expired' in error_message:
        bitmex_timestamp = int(''.join([s for s in error_message if s.isdigit()]))
        local_timestamp = exchange.seconds()
        print('BitMEX exchange time UTC: ', exchange.iso8601(bitmex_timestamp * 1000))
        print('Your Python time UTC: ', exchange.iso8601(local_timestamp * 1000))
        print('Your local time differs from BitMEX by ', local_timestamp - bitmex_timestamp, 'seconds')
```

↑ What does it say?

**Comment by xinglong717** [comment]
bitmex {"error":{"message":"This request has expired - `expires` is in the past. Current time: 1568574652","name":"HTTPError"}}
BitMEX exchange time UTC:  2019-09-15T19:10:52.000Z
Your Python time UTC:  2019-09-15T19:10:31.000Z
Your local time differs from BitMEX by  -21 seconds

**Comment by kroitor** [comment]
@xinglong717 

> Your local time differs from BitMEX by -21 seconds

↑ This is self-explanatory.

Please read this: https://github.com/ccxt/ccxt/issues/4789

This should work:

```Python
import ccxt
exchange = ccxt.bitmex({
    'apiKey': 'YOUR_API_KEY',  # ←------------- EDIT HERE FOR YOUR KEYS
    'secret':'YOUR_SECRET',
    'enableRateLimit': True,
    'options': {
        'api-expires': 60, # ←------ ADD THIS OPTION OR SYNCHRONIZE YOUR TIME
    },
})

if 'test' in exchange.urls:
    exchange.urls['api'] = exchange.urls['test']

print(exchange.fetch_balance())
```

↑ Does it work now?

**Comment by xinglong717** [comment]
Thanks very much. I've fixed my problem. My local time was different 21s from standward time.
I've fixed my local time. All is working well.
Thanks very much for your patient efforts.
And I'm very sorry. Hope the glorious to ccxt team.

**Comment by kroitor** [comment]
@xinglong717 ok, cool! Thx for reporting back! Cheers!

**Comment by SpenTappy** [comment]
This fix worked for me too: server's timezone was already UTC but system time was just 8 seconds slow.
Thanks
