### ISSUE TITLE
Need type definition file (for Typescript support)

### ISSUE THREAD

**Issue by realharry** [ccxt/ccxt#5811]
I just started experimenting with ccxt, and I think it is a great library. Thanks very much for the contribution. One thing I miss is that it does not seem to have type definitions. It would be great if somebody familiar with the codebase create type definition files so that ccxt can be used in Typescript apps. Thanks!

- OS: MacOS
- Programming Language version: Node v10.15.3
- CCXT version: 1.18.1145
- Exchange: N/A
- Method: N/A

**Comment by kroitor** [comment]
@realharry let us know if this does not help: https://github.com/ccxt/ccxt/blob/master/ccxt.d.ts

**Comment by realharry** [comment]
BTW, can we publish it to npm repository?

**Comment by kroitor** [comment]
@realharry it should be there already )

**Comment by realharry** [comment]
Ah cool. thanks. I'll try it in a typescript project. Thanks!

**Comment by iBobb** [comment]
For anyone who might be struggling like me when using TypeScript, instead of using "const ccxt = require('ccxt');" I did
`import { Trade, binance } from 'ccxt';`
`binanceClient: binance;`
`        if (!this.binanceClient && apiKey && apiSecret) {
            this.binanceClient = new binance({
                apiKey: apiKey,
                secret: apiSecret,
            });
        }`
