### ISSUE TITLE
CCXT support realtime orderbook using websocket?

### ISSUE THREAD

**Issue by xinglong717** [ccxt/ccxt#5820]
I'm going to develop real time orderbook for coinbase and bitfinex.
I have tried to use fetch_order_book(), but upgrade speed very slow.
I want to know that ccxt can provide real time orderbook using web socket.
I want it for bitmex, bitfinex, coinbase.

**Comment by kroitor** [comment]
@xinglong717 plz see here: https://github.com/ccxt/ccxt/issues/56

**Comment by xinglong717** [comment]
Hello, there are too many complex contents, I ca'nt understand.
Only I want to know onething.
CCXT provide real time orderbook using web socket for bitmex, bitfinex, coinbase?
If okay, how can I use that function?

**Comment by kroitor** [comment]
@xinglong717 in short, CCXT currently does not implement WS, but we have plans to add it in several weeks with the release of CCXT Pro. The release date will be announced very soon.

**Comment by xinglong717** [comment]
If I can believe that release in 2~3 weeks?
