### ISSUE TITLE
NPM REGISTRY NOT FOUND

### ISSUE THREAD

**Issue by anwar-github** [ccxt/ccxt#5828]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/ccxt/-/ccxt-1.18.1150.tgz
npm ERR! 404
npm ERR! 404  'ccxt@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'mnbegeneral'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

- mac
- npm i ccxt (latest)
- node js

**Comment by kroitor** [comment]
Doing a `npm set registry https://registry.npmjs.org/` should solve the problem. Let us know if that does not help: https://github.com/storybookjs/storybook/issues/15#issuecomment-204621740

**Comment by anwar-github** [comment]
@kroitor its work, ok thanks . . .
