### ISSUE TITLE
ccxt ca'nt install on mac

### ISSUE THREAD

**Issue by xinglong717** [ccxt/ccxt#5834]
I'm going to use ccxt python library on mac 10.14.6.
sudo pip install ccxt
Got following error.
Please help me.

ERROR: Could not install packages due to an EnvironmentError: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', '/private/tmp/pip-uninstall-MheO4y/markers.pyc', "[Errno 1] Operation not permitted: '/private/tmp/pip-uninstall-MheO4y/markers.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', '/private/tmp/pip-uninstall-MheO4y/__init__.py', "[Errno 1] Operation not permitted: '/private/tmp/pip-uninstall-MheO4y/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', '/private/tmp/pip-uninstall-MheO4y/markers.py', "[Errno 1] Operation not permitted: '/private/tmp/pip-uninstall-MheO4y/markers.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', '/private/tmp/pip-uninstall-MheO4y/__init__.pyc', "[Errno 1] Operation not permitted: '/private/tmp/pip-uninstall-MheO4y/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', '/private/tmp/pip-uninstall-MheO4y', "[Errno 1] Operation not permitted: '/private/tmp/pip-uninstall-MheO4y'")]

**Comment by kroitor** [comment]
Sorry, this is not related to this library.

See the solutions here: https://marcelog.github.io/articles/mac_osx_python_pip_install_operation_not_permitted.html

**Comment by xinglong717** [comment]
Hello. I've fixed above problem.
I've installed homebrew and reinstalled python and ccxt
Installation done well.
Then ccxt not working in python.

import ccxt
print("hello")

Above code made following error.

Traceback (most recent call last):
  File "/Users/sergey/Documents/python_work/test/test1.py", line 6, in <module>
    import ccxt
ImportError: No module named ccxt

**Comment by kroitor** [comment]
@xinglong717 you should install `pip` as well, and then restart the term to make sure that you use the proper `pip`, the one that comes with homebrew's python.

**Comment by xinglong717** [comment]
I've reinstalled mac 10.14
And installed brew, python, pip , ccxt.
But same error occured.
 
![image](https://user-images.githubusercontent.com/32957829/65262948-c3c65d80-db4e-11e9-9fd7-1b092895de1e.png)

**Comment by xinglong717** [comment]
ERROR: Could not install packages due to an EnvironmentError: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', '/private/var/folders/_t/33j0l4s55rq8ghq7t13g0sz40000gn/T/pip-uninstall-srcr1j/markers.pyc', "[Errno 1] Operation not permitted: '/private/var/folders/_t/33j0l4s55rq8ghq7t13g0sz40000gn/T/pip-uninstall-srcr1j/markers.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', '/private/var/folders/_t/33j0l4s55rq8ghq7t13g0sz40000gn/T/pip-uninstall-srcr1j/__init__.py', "[Errno 1] Operation not permitted: '/private/var/folders/_t/33j0l4s55rq8ghq7t13g0sz40000gn/T/pip-uninstall-srcr1j/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', '/private/var/folders/_t/33j0l4s55rq8ghq7t13g0sz40000gn/T/pip-uninstall-srcr1j/markers.py', "[Errno 1] Operation not permitted: '/private/var/folders/_t/33j0l4s55rq8ghq7t13g0sz40000gn/T/pip-uninstall-srcr1j/markers.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', '/private/var/folders/_t/33j0l4s55rq8ghq7t13g0sz40000gn/T/pip-uninstall-srcr1j/__init__.pyc', "[Errno 1] Operation not permitted: '/private/var/folders/_t/33j0l4s55rq8ghq7t13g0sz40000gn/T/pip-uninstall-srcr1j/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', '/private/var/folders/_t/33j0l4s55rq8ghq7t13g0sz40000gn/T/pip-uninstall-srcr1j', "[Errno 1] Operation not permitted: '/private/var/folders/_t/33j0l4s55rq8ghq7t13g0sz40000gn/T/pip-uninstall-srcr1j'")]

**Comment by kroitor** [comment]
@xinglong717 

> But same error occured.
> `impory ccxt`

↑ There's a syntax error there, should be `import ccxt`, instead of `imporY ccxt`.

**Comment by xinglong717** [comment]
![image](https://user-images.githubusercontent.com/32957829/65287376-57ffe700-db86-11e9-8f64-2f2075cc1adc.png)

**Comment by kroitor** [comment]
@xinglong717 Does your `site-packages` folder contain the `ccxt` module? Have you checked your Python module lookup paths? Try `pip install aiohttp`, `import aiohttp` – does that work? If that does not work, then this issue is not related to CCXT and it's a problem with your environment configuration.

**Comment by xinglong717** [comment]
Excuse me,but other modules ca'nt work.too.
On mac, pip, pip3, which i shpuld use?
Would you please let me know the environment configuration on mac?
Now I know that this issue is'nt ccxt problem.
Would you please help me?

**Comment by xinglong717** [comment]
![image](https://user-images.githubusercontent.com/32957829/65368778-bb723d80-dc88-11e9-81d4-7223d4fd3a98.png)

**Comment by xinglong717** [comment]
Thanks very much for your help.

**Comment by kroitor** [comment]
@xinglong717 ok, good to know you've figured it out! It should be `pip3`, if you're using `python3` installed with `homebrew` as the interpreter on mac.
