### ISSUE TITLE
Incorrect 'inline conditional' transpilation to python

### ISSUE THREAD

**Issue by furmanOFF** [ccxt/ccxt#5837]
- Programming Language version: Python
- CCXT version: Latest
- Exchanges: anxpro, binance, coinfloor, idex, okcoinusd

There are at least 16 cases (across 10 exchanges) of incorrectly transpiled 'inline if' in Python version. For example: 
https://github.com/ccxt/ccxt/blob/301a37161c84440887f4503b48f6c36ead53be57/python/ccxt/binance.py#L383
https://github.com/ccxt/ccxt/blob/301a37161c84440887f4503b48f6c36ead53be57/python/ccxt/idex.py#L710
https://github.com/ccxt/ccxt/blob/301a37161c84440887f4503b48f6c36ead53be57/python/ccxt/anxpro.py#L936

**Comment by kroitor** [comment]
This bug is fixed in 1.18.1169. Thx for reporting! Let us know if you find any further issues. Cheers!
