### ISSUE TITLE
New Exchange: tradecoinx.ca

### ISSUE THREAD

**Issue by shenki3** [ccxt/ccxt#5839]
Please add the following exchange to ccxt. Thanks in advance it would Mean the world to us.

API Doc: https://tradecoinx.ca/api/
URL: https://tradecoinx.ca/
Fee: .05%
Volume: .01 BTC
Address: Canada
Company Info: http://tradecoin.team
TNC: In Progress
Registration: In Progress
Based Country: Canada
Whitepaper: http://tradecoin.team/whitepaper.html
Priority: normal
Github group: https://github.com/tradecointeam/tradecoin
Note: ranked top : NA
Type: Centrailzed Ex
Discussion: https://discord.gg/SA8MHmH

**Comment by frosty00** [comment]
If you would like to speed up the progress of the tradecoin integration please contact info@ccxt.trade. Otherwise we are not able to guarantee a timeframe - https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar

**Comment by shenki3** [comment]
Thank you for the quick reply

Appricate it.

Kind regards

Op do 19 sep. 2019 21:59 schreef Carlo Revelli <notifications@github.com>:

**Comment by shenki3** [comment]
Thanks guys , send An email. Asked the devs of our exchange if they can look into it. For me it's al a mystery that's why i posted a  request. Would be awesome if someone here can also look into it or do it for us. We would like to do it the right way however we need to spend our money wise. As tradecoin was An old project that was taken over by us as a community. The tradecoinx idea was the usecase. However we are not as smart as the People that are on git. Thanks in advance kind regards shenki3. Feel free to join our discord

**Comment by kroitor** [comment]
The exchange website is inaccessible.
