### ISSUE TITLE
Support for margin borrow on Binance (using implicit functions)

### ISSUE THREAD

**Issue by vincekwok** [ccxt/ccxt#5842]
Could you please expose the implicit functions for borrowing coins on Binance for margin trading? The api docs are here:

https://github.com/binance-exchange/binance-official-api-docs/blob/master/margin-api.md

At the moment they don't seem to be supported in the latest version of ccxt (1.18.1173)

- OS: Windows
- CCXT version: 1.18.1173
- Exchange: Binance
- Method: margin functions, such as /sapi/v1/margin/loan , 

Thanks!

**Comment by kroitor** [comment]
@vincekwok will add them shortly.

**Comment by StasToken** [comment]
Where can I see an example of how to use it? where I can not find!

**Comment by kroitor** [comment]
> Where can I see an example of how to use it?

@StasToken it's in the Manual, here:

- https://github.com/ccxt/ccxt/wiki/Manual#api-methods--endpoints
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
