### ISSUE TITLE
cancel_order deribit does not work

### ISSUE THREAD

**Issue by Maximilian10** [ccxt/ccxt#5848]
- OS: MAC
- Programming Language version: Python 3.6
- CCXT version: 1.18.786
- Exchange: deribit
- Method: cancel_order

deribit {"usDiff":0,"testnet":false,"success":false,"message":"authorization_required","error":10000}

**Comment by kroitor** [comment]
@Maximilian10 does `fetchBalance` work with the same key?

**Comment by Maximilian10** [comment]
That is correct. And also placing orders works fine.

**Comment by kroitor** [comment]
@Maximilian10 do you have the rate-limiter enabled? Have you tried any of the troubleshooting steps?

**Comment by kroitor** [comment]
Check out the new deribit v2 implementation that has been added in CCXT 1.23.88+: https://github.com/ccxt/ccxt/issues/6602. Let us know if it does not help.
