### ISSUE TITLE
adara: active flag wrong?

### ISSUE THREAD

**Issue by brandsimon** [ccxt/ccxt#5853]
In adara is the following in fetch_markets:
`'active': (active and allowDeposit and allowWithdraw),`
Is this what we want? I would think, active means, it is possible to trade.
There are exchanges with active markets that dont support deposit/whitdrawal at all.

**Comment by kroitor** [comment]
> In adara is the following in fetch_markets:

Nope, that's in `fetchCurrencies` ;)

`fetchMarkets`:

- https://github.com/ccxt/ccxt/blob/master/js/adara.js#L231

`fetchCurrencies`:

- https://github.com/ccxt/ccxt/blob/master/js/adara.js#L318

**Comment by brandsimon** [comment]
Usch, my bad, thanks very much @kroitor
