### ISSUE TITLE
add notice to manual on tradehistory pagination

### ISSUE THREAD

**Issue by ghost** [ccxt/ccxt#5861]
your manual pagination by `since` is broken, tested with bittrex since it will fetch the latest trade over and over again not `break`ing, thus this is better example:
```
    def paginate_history(self, ex) -> List:
       tradess = []
        since = ex.milliseconds() - 1000*60*60*24*14 # 1d *x
        while True:
            trades = ex.fetch_my_trades(None, since, limit=5)
            if trades:
                known_ids = [x['id'] for x in tradess]
                new_trades = [x for x in trades if x['id'] not in known_ids]
                if new_trades:
                    tradess += new_trades
                    since = trades[-1]['timestamp']
                    continue
            break
        return tradess[::-1] # latest first
```

i also discourage using since AND limit, i experienced empty fetch yet there where more trades up to  `since`. might be due bad pruning, crosscompared to xchange java lib

**Comment by kroitor** [comment]
@hivemall 

> `orders = ex.fetch_my_trades(None, since, limit=5)`

You seem to be confusing trades with orders here, no?

- https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades

>  i experienced empty fetch yet there where more trades up to `since`.

But when you use the `since` argument, you should get trades **AFTER** `since`, not up to `since`, right?

**Comment by hivemall** [comment]
dang, yes, but its just the naming.

trades after AND including `since` up to now, which does include the last seen one `orders[-1]['timestamp']` thus never empty -> thus never `break`; in the example above it does. 
Furthermore:  `    while (since < exchange.milliseconds ()) ` is always `True` unless you could fetch a trade from the future (which i would be interested  in to buy)

**Comment by lobatt** [comment]
with the observation above, I would also like to raise it to your awareness that some exchanges limit how many history trades you can retrieve, e.g,
for gateio it is 100 trades
for huobipro it is 500 trades
So if you need to go through more than that, it simply won't work.

**Comment by caiusCitiriga** [comment]
As @lobatt said there's even a worse scenario on ByBit, where you can't fetch more than 60 trades using the API directly. You'll have to use the provided public csv files, and wait for the publish of the current day trades file if you want to look back more than 60 trades for the current day.

**Comment by ttodua** [comment]
in recent past, ccxt introduced an automatic pagination, users can take a look into: https://docs.ccxt.com/#/README?id=automatic-pagination

closing this issue for now. further feedbacks are welcome from users.

**Comment by Kiilu-web** [comment]
how to resize websites to suit different gadgets?
