### ISSUE TITLE
is there a way to fetch all symbols orderbook or ohlcv in one exchange for one call?

### ISSUE THREAD

**Issue by finaluzi** [ccxt/ccxt#5867]
Hello,

Could anyone help, is there a way to fetch all symbols orderbook or ohlcv in one exchange for one call, or in a very short time then loop this with in 1 minute.
For ohlcv, I just need current 5 minutes volume and price.
What I have tried was fetch_tickers, but inaccurate, and async fetch ohlcv with 5m limit=2, get baned quickly.
I use python 3

thanks

**Comment by kroitor** [comment]
@finaluzi Hi!

Some exchanges support the `fetchOrderBooks` call, however, i don't think any of them support fetching OHLCVs for all symbols at once. You may want to check the exchange metainfo, as described in the Manual.

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata
- https://github.com/ccxt/ccxt/blob/master/examples/js/exchange-capabilities.js

Let us know if the above does not answer the question.
