### ISSUE TITLE
Wrong url exmo api PHP

### ISSUE THREAD

**Issue by StasToken** [ccxt/ccxt#5869]
Am I a turkey or is [this function](https://github.com/ccxt/ccxt/blob/master/php/exmo.php#L989) accessing the wrong URL? 

`$exmo->fetch_closed_orders()`

curl debug inquiries 

> string(37) "https://api.exmo.com/v1/pair_settings"
> string(40) "https://api.exmo.com/v1/user_open_orders"

If you believe the [documentation](https://exmo.me/ru/api#/authenticated_api) there should be a different URL
Or something I do not understand in this life?

**Comment by kroitor** [comment]
> If you believe the documentation there should be a different URL

Which one?

> Or something I do not understand in this life?

Looks like you're missing the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#orders-cache

Let me know if the above does not answer the question.

**Comment by StasToken** [comment]
Actually, it seems to me that the whole problem is on [this line](https://github.com/ccxt/ccxt/blob/master/php/exmo.php#L967), apparently it breaks the logic, because the order and the open order are given in different URLs - that is, it’s necessary to essentially make two requests again, if I understood correctly

**Comment by StasToken** [comment]
I don’t even know what to say, exchange developers need to wrest their hands and prohibit computer use until the end of their lives ...

Thank you, you answered my question, we will think about how to live with it further.
