### ISSUE TITLE
New Exchange: Bitcoin.com Exchange

### ISSUE THREAD

**Issue by nilswx** [ccxt/ccxt#5870]
[Bitcoin.com Exchange](https://exchange.bitcoin.com) has finally released their API.

**Docs:** [api.exchange.bitcoin.com](https://api.exchange.bitcoin.com)

This exchange appears to be powered by the same tech that is behind HitBTC, using the V2 API.

Adding `ccxt` support for Bitcoin.com Exchange would involve adding a new `bitcoincom` subclass of [hitbtc2](https://github.com/ccxt/ccxt/blob/master/js/hitbtc2.js), configuring the base URLs and setting exchange-specific metadata. (fees etc)

**Comment by nilswx** [comment]
@kroitor: I just made a stub. It works well enough for my purposes. How to proceed?

https://github.com/nilswx/ccxt/tree/bitcoincom

**Comment by kroitor** [comment]
Bitcoin.com is available in CCXT as of version 1.36.95+
