### ISSUE TITLE
New Exchange: Binance Futures

### ISSUE THREAD

**Issue by ftuyama** [ccxt/ccxt#5872]
Any plans to add Binance Futures exchange? 
https://www.binance.com/en/futures/BTCUSDT
https://binanceapitest.github.io/Binance-Futures-API-doc/

**Comment by frosty00** [comment]
yes we have seen it, and will work on getting it done as soon as we have the time. we are really busy people!

https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar

thanks for the suggestion )

**Comment by StanleyDing** [comment]
@kroitor 

I might be able to help with this issue since I am planning to use Binance future API in my project. 

Binance has different endpoint (https://fapi.binance.com/fapi/v1) for future trading. On top of that, there's also private and public APIs to consider. I'm thinking adding `fapiPrivate` and `fapiPublic` to `this.urls.api` so I can determine whether to sign the request in `sign()` method. But I don't know if this is how ccxt normally does when distinguishing public and private APIs.

**Comment by cwse89** [comment]
Hey awesome CCXT team!

Any update on incorporating Binance Futures into CCXT? :-)

Cheers!

**Comment by cwse89** [comment]
Eg. how to query open positions? Eg. BitMex was "bitmex.private_get_position()"

Thanks!

**Comment by kroitor** [comment]
@cwse89 

> Any update on incorporating Binance Futures into CCXT? :-)

Please, see this PR: https://github.com/ccxt/ccxt/pull/5907, thx to @StanleyDing , it's on the way, hope to merge it soon!

> Eg. how to query open positions? Eg. BitMex was "bitmex.private_get_position()"

This was answered here: https://github.com/ccxt/ccxt/issues/2499#issuecomment-379829876 ;)

**Comment by cwse89** [comment]
> @cwse89
> 
> > Any update on incorporating Binance Futures into CCXT? :-)
> 
> Please, see this PR: #5907, thx to @StanleyDing , it's on the way, hope to merge it soon!
> 
> > Eg. how to query open positions? Eg. BitMex was "bitmex.private_get_position()"
> 
> This was answered here: [#2499 (comment)](https://github.com/ccxt/ccxt/issues/2499#issuecomment-379829876) ;)

Awesome thanks!

Re the Binance equivalent of "private_get_position", what is it for Binance Futures? The link provided relates to BitMex, not Binance Futures.

Thanks!

**Comment by kroitor** [comment]
> Re the Binance equivalent of "private_get_position", what is it for Binance Futures? The link provided relates to BitMex, not Binance Futures.

It's a bit different for Binance Futures, see the code submitted in the linked PR here: https://github.com/ccxt/ccxt/pull/5907/files, it is controlled with a standalone option, however, we may add some edits to it before merging in order to have a unified interface to futures across exchanges, like we do with the spot trading. Hope to add that soon.

**Comment by cwse89** [comment]
legend!

**Comment by cwse89** [comment]
FYI, I worked it out. To query the open positions, use this code:

`binance.fapiPrivateGetUserTrades({'symbol':'btcusdt'})`

**Comment by kroitor** [comment]
@cwse89 awesome, thx for your feedback! )

**Comment by cwse89** [comment]
no worries. I can't seem to send orders though?
The following code:
```
binance.fapiPrivatePostOrder({'symbol':'BTC/USDT',
                                       'type':"MARKET",
                                       'side':"BUY",
                                       'quantity':"0.003",})
```
Gets this error:
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 540, in fetch
    response.raise_for_status()
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Google Drive/Capriole Production/Python Production/crypto_trader/bitbot.py", line 469, in binance_order
    'quantity':str(amount)})
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 436, in inner
    return entry(_self, **inner_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\binance.py", line 1295, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 455, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 553, in fetch
    self.handle_rest_errors(http_status_code, http_status_text, http_response, url, method)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 578, in handle_rest_errors
    raise error(' '.join([method, url, string_code, http_status_text, body]))
ccxt.base.errors.ExchangeNotAvailable: POST https://fapi.binance.com/fapi/v1/order 400 Bad Request {
  "error" : null
```

Any ideas?

**Comment by kroitor** [comment]
@cwse89 can you post these errors in the linked PR #5907? That way, @StanleyDing will receive these comments and we will be able to fix it before merging ) Thx again! )

**Comment by C0DK** [comment]
Currently you have issues when trying to get balances for both, as you need to fetch first from one then the other (via the `defaultType` arg. This might not be the primary focus and i get that you are busy, however it would be nice in this regard.

**Comment by kroitor** [comment]
@C0DK we are actually going to remove the need for the defaultType, however, that requires more unification for contract trading, which is a work in progress. In the meantime, i would suggest to have two or more parallel instances of Binance, one for each defaultType of your interest.

**Comment by C0DK** [comment]
alright. Thank you.

Currently it seems that i am only able to use, what they call, "USDT-Futures" not "COIN-Futures". not sure if i am wrong, but it is two different apis, it seems, and works in different ways. https://binance-docs.github.io/apidocs/delivery/en/#account-information-user_data

**Comment by kroitor** [comment]
@C0DK you can use any defaultType with the most recent version of CCXT to fetch the corresponding balance, namely, `spot`, `margin`, `futures` (usdt-margined), `delivery` (coin-margined).
