### ISSUE TITLE
Fcoin exchange : signature is empty

### ISSUE THREAD

**Issue by bli920370** [ccxt/ccxt#5887]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: win2008 server
- Programming Language version: python
- CCXT version:1.18.1205
- Exchange: Fcoin
- Method:

Dear All:
        I'm a beginner of ccxt. In recent days, I can use ccxt on fcoin, though sometimes got errors as below. But till yesterday, I can't use it on the same computer for the same reason. I don't know why? Has anyone encountered this situation?
        Thanks！

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py in fetch(self, url, method, headers, body)
    539             self.logger.debug("%s %s, Response: %s %s %s", method, url, http_status_code, headers, http_response)
--> 540             response.raise_for_status()
    541 

C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py in raise_for_status(self)
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 

HTTPError: 400 Client Error: Bad Request for url: https://api.fcoin.com/v2/accounts/balance
During handling of the above exception, another exception occurred:

InvalidNonce                              Traceback (most recent call last)
<ipython-input-11-abd208c401aa> in <module>
----> 1 exchange.fetchBalance()

C:\ProgramData\Anaconda3\lib\site-packages\ccxt\fcoin.py in fetch_balance(self, params)
    311     def fetch_balance(self, params={}):
    312         self.load_markets()
--> 313         response = self.privateGetAccountsBalance(params)
    314         result = {'info': response}
    315         balances = self.safe_value(response, 'data')

C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py in inner(_self, params)
    434                             if params is not None:
    435                                 inner_kwargs['params'] = params
--> 436                             return entry(_self, **inner_kwargs)
    437                         return inner
    438                     to_bind = partialer()

C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py in request(self, path, api, method, params, headers, body)
    457     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):
    458         """Exchange.request is the entry point for all generated methods"""
--> 459         return self.fetch2(path, api, method, params, headers, body)
    460 
    461     @staticmethod

C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py in fetch2(self, path, api, method, params, headers, body)
    453         self.lastRestRequestTimestamp = self.milliseconds()
    454         request = self.sign(path, api, method, params, headers, body)
--> 455         return self.fetch(request['url'], request['method'], request['headers'], request['body'])
    456 
    457     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):

C:\ProgramData\Anaconda3\lib\site-packages\ccxt\base\exchange.py in fetch(self, url, method, headers, body)
    550 
    551         except HTTPError as e:
--> 552             self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
    553             self.handle_rest_errors(http_status_code, http_status_text, http_response, url, method)
    554             raise ExchangeError(method + ' ' + url)

C:\ProgramData\Anaconda3\lib\site-packages\ccxt\fcoin.py in handle_errors(self, code, reason, url, method, headers, body, response, requestHeaders, requestBody)
    649             if status in self.exceptions:
    650                 exceptions = self.exceptions
--> 651                 raise exceptions[status](feedback)
    652             raise ExchangeError(feedback)

InvalidNonce: fcoin {"status":6004,"msg":"timestamp is out of range"}

url: https://api.fcoin.com/v2/accounts/balance   links to a webpage:
{"status":6001,"msg":"signature is empty"}

**Comment by kroitor** [comment]
@bli920370 hi! Can you post the code to reproduce it? Looks like you're having an InvalidNonce exception, which may indicate that you're not doing the proper rate limiting. More about here:

- https://github.com/ccxt/ccxt/issues/3596
- https://github.com/ccxt/ccxt/wiki/Manual#error-handling 
- https://github.com/ccxt/ccxt/wiki/Manual#invalidnonce
