### ISSUE TITLE
Question: How can we get the liquidation price of an order for bitmex?

### ISSUE THREAD

**Issue by tosti911** [ccxt/ccxt#5892]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10 1903
- Programming Language version: Python 3
- CCXT version: Latest
- Exchange: Bitmex
- Method: How can we get the liquidation price of an order for bitmex?

Sorry if this was asked before, I tried searching for it, but didn't find anything. So the question stands, is there a way to get the liquidation price of an order on bitmex? If not, what options do we have?

**Comment by StanleyDing** [comment]
As far as I know, you cannot get liquidation price of "an order". However, you can get your current liquidation price from `/position` API.

**Comment by kroitor** [comment]
Thx @StanleyDing !

@tosti911 see also:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://github.com/ccxt/ccxt/issues/5769
- https://github.com/ccxt/ccxt/issues/5391
- https://github.com/ccxt/ccxt/issues/3596

Let us know if the above does not answer the question.
