### ISSUE TITLE
Date.toUTCString() function missing

### ISSUE THREAD

**Issue by prgmtx** [ccxt/ccxt#5894]
Hi there. Is there a way to use Date.toUTCString() function in the exchange-specific sign() function?
Thanks
Jan

**Comment by kroitor** [comment]
@prgmtx please see here on how to work with UTC timestrings and timestamps in terms of CCXT:

- https://github.com/ccxt/ccxt/wiki/Manual#working-with-datetimes-and-timestamps

Let us know if the above does not help.

**Comment by prgmtx** [comment]
I have read the manual already. What I am looking for is an approach to format a timestamp according to the RFC 2616 as required by the HTTP standard. 

I would like to add following functions to the lib:

const rfc2616_now = () => {
    return new Date ().toUTCString ();
}

public static function rfc2616_now() {
    return gmdate('D, d M Y H:i:s T');
}

@staticmethod
def rfc2616_now():
    now = datetime.datetime.utcnow()
    stamp = mktime(now.timetuple())
    return format_date_time(stamp)

What do yo think?

**Comment by kroitor** [comment]
@prgmtx I'd suggest that we don't call it `rfc2616_now()` and instead call it `rfc2616(timestamp)`, where `timestamp` is equal to `this.milliseconds ()` by default. However, we need to check which particular exchange is in question. Can you elaborate on the exchange specifics, plz?

**Comment by prgmtx** [comment]
@kroitor I've submitted [PR](https://github.com/ccxt/ccxt/pull/5904) integrating Eterbase Exchange together with the required `rfc2616()` functions. Thanks for your support.
