### ISSUE TITLE
怎么使用okex3的冰山订单

### ISSUE THREAD

**Issue by 317459062** [ccxt/ccxt#5898]
OS: windows
Programming Language version:python3
CCXT version: 1.18.1171
Exchange: okex3
Method: creat_order

怎么使用okex3的冰山订单  没找到相关的使用方法

**Comment by frosty00** [comment]
need more information, can you post the verbose output?

**Comment by kroitor** [comment]
@317459062 closing this for now until we have a followup from you.

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ

```Python
exchange.load_markets()
exchange.verbose = True
exchange.create_order(...
```
