### ISSUE TITLE
is there binance margin trading api docs available?

### ISSUE THREAD

**Issue by frndxyz** [ccxt/ccxt#5900]
i want to implement binance margin trading with ccxt . is there margin trading api docs available?

**Comment by kroitor** [comment]
@frndxyz let us know if this does not help: 

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L84
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#implicit-api-methods
