### ISSUE TITLE
Implementation issue : Signature & Implicit API method generation related

### ISSUE THREAD

**Issue by abhishekr700** [ccxt/ccxt#5903]
I'm trying to implement a new exchange into CCXT.

For orderBooks, the exchange's API requires a signed GET request on  <exchange api url>/getSellOrderBook/<symbol>

CCXT auto generates methods for API calls, but what do I do in this case, it is infeasible to develop methods for each of the symbols.
Also, I'm unable to understand how to add a signature to the API call as I'm not in control of the functions. The signature needs to be added into the header

**Comment by StanleyDing** [comment]
> I'm unable to understand how to add a signature to the API call as I'm not in control of the functions. The signature needs to be added into the header

Check other exchange implementation of `sign` function. You should add your signature in this function.

**Comment by dblue** [comment]
> I'm trying to implement a new exchange into CCXT.

Post a link to the exchange API documentation; it will help us understand what you're trying to do.

> For orderBooks, the exchange's API requires a signed GET request on /getSellOrderBook/
> 
> CCXT auto generates methods for API calls, but what do I do in this case, it is infeasible to develop methods for each of the symbols.

It sounds like you're trying to define private API calls that use the GET method. Look at the API declaration and implementation of ```sign``` in ```gdax.js``` You'll see that there are private GET calls that are appropriately signed and use a dynamic id (instead of a dynamic symbol).

> Also, I'm unable to understand how to add a signature to the API call as I'm not in control of the functions. The signature needs to be added into the header

Look at the ```sign``` method in ```gdax.js``` for an example of how to add a signature to the header for a private API call.

**Comment by abhishekr700** [comment]
Hi, somehow the formatting got lost, my second question (about the sign) was answered, thank you for that.
Let me clarify my first question,
suppose there's a api call on `baseURL/getOrderBook/BTC` i.e. the symbol is part of the URL itself, in this case how do I pass the symbol name as a parameter.The api call methods are generated automatically by ccxt.
It'd be better if there's some reference on the automatically generated api call methods.
Also, what is the role of `this.extend()` which is used at various places in the exchange implementations I've seen.

**Comment by dblue** [comment]
> Let me clarify my first question,
> suppose there's a api call on baseURL/getOrderBook/BTC i.e. the symbol is part of the URL itself, in this case how do I pass the symbol name as a parameter.The api call methods are generated automatically by ccxd.
> t'd be better if there's some reference on the automatically generated api call methods.

The reference is here: https://github.com/ccxt/ccxt/wiki/Manual#api-methods--endpoints

You would use: ```baseURL/getOrderBook/{symbol}``` in the API declaration and you would pass ```symbol``` as a parameter. So, assuming the API call is declared under ```private``` (to include the signature), your call would be: 

```.privateGetOrderBook({ symbol: 'BTC'})```.

> Also, what is the role of this.extend() which is used at various places in the exchange implementations I've seen.

```this.extend``` is used to combine a set of dictionaries/hashes. So, ```this.extend(defaults, new_options)``` adds the parameters from ```new_options``` to ```defaults```, allowing you to use the ```defaults``` but substituting the new parameters in ```new_options```. That way, you don't have to specify all of the parameters in ```new_options```, only the ones you want to override.

**Comment by kroitor** [comment]
@dblue thanks so much for your involvement! Really appreciate it!

@abhishekr700 let us know if the above does help! )

**Comment by abhishekr700** [comment]
Yup, implemented the signing now and it is working so far.
Thank you so much to all of you !
