### ISSUE TITLE
[okex3] my trade fee issues

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5909]
The fee object obtained from calling `fetchOrderTrades` 

 * contains a fee object that has a negative cost
 * contains a fee object that has no currency 

Here is a pair as an example.  The BTC fee is 0.15%.

```
{
"item1":{
"fee":"-0.00000051"
"side":"buy"
"size":"0.000335"
"price":"0.0067"
"order_id":"3627836574017536"
"exec_type":"T"
"ledger_id":"7374219830"
"liquidity":"T"
"timestamp":"2019-10-03T08:46:33.000Z"
"created_at":"2019-10-03T08:46:33.000Z"
"product_id":"XMR-BTC"
"instrument_id":"XMR-BTC"
}
"item2":{
"fee":"0"
"side":"sell"
"size":"0.05"
"price":"0.0067"
"order_id":"3627836574017536"
"exec_type":"T"
"ledger_id":"7374219829"
"liquidity":"T"
"timestamp":"2019-10-03T08:46:33.000Z"
"created_at":"2019-10-03T08:46:33.000Z"
"product_id":"XMR-BTC"
"instrument_id":"XMR-BTC"
}
```

**Comment by npomfret** [comment]
Actually, according to the docs:

> New status for spot trading transaction details: fee is either a positive number (invitation rebate) or a negative number (transaction fee deduction).

So I think we need to _invert_ the fee.

**Comment by npomfret** [comment]
We still need to do the fee currency, something like...

                    const feeCcy = side === 'buy' ? baseCcy : quoteCcy;

**Comment by kroitor** [comment]
@npomfret you're right, will get to it.

**Comment by npomfret** [comment]
I've got the above in my codebase, seems to work.  Will submit a PR if you don't beat me to it.
