### ISSUE TITLE
Adding a new exchange without API endpoints

### ISSUE THREAD

**Issue by heavenchains** [ccxt/ccxt#5911]
Hello CCXT community,
I have read your requirements to become a CCXT compliant exchange. Now I was wondering if it is possible to become CCXT compliant if the exchange operates via an intermediary SDK, instead of a direct server API.
The exchange I am working on is https://tex.liquidity.network, a non-custodial off-chain exchange, and you can find the SDK I am referring to under https://docs.liquidity.network.
I would appreciate any input from your side, and am happy to adapt whatever is necessary to become CCXT compliant.
Thanks

**Comment by frosty00** [comment]
> Now I was wondering if it is possible to become CCXT compliant if the exchange operates via an intermediary SDK

No we do not allow the use of intermediary SDK, or any other dependencies for that matter. All the code used to interact with your exchange must live inside the js file.

> I would appreciate any input from your side, and am happy to adapt whatever is necessary to become CCXT compliant.

You could publish the API spec for the REST endpoints as a start.
