### ISSUE TITLE
Cookies: An easy 2 line solution to get ccxt (and curl) to handle cookies in PHP

### ISSUE THREAD

**Issue by nightowl77** [ccxt/ccxt#5914]
Hi Guys

I've noticed that the PHP version of Exchange.php allows "curl_options" to be set after the exchange object was initialized. 

According to the PHP Curl manual, I can set CURLOPT_COOKIEFILE and CURLOPT_COOKIEJAR which would allow Exchange.php (and descendants) to correctly send back any cookies the exchange and the cloud providers sets. 

So something simple like this should work

```php
$cookiejar = "/var/www/yoursite/storage/cookies.txt";

$exchange = new \ccxt\binance ();
$exchange->curl_options = array(CURLOPT_COOKIEFILE => $cookiejar, CURLOPT_COOKIEJAR => $cookiejar);
```
But this didn't work. No cookies were saved. 

On closer inspection of the Exchange.php file, I've found the problem. For CURLOPT_COOKIEFILE to be saved, curl_close() MUST be called. It is the curl_close function that looks for cookies in the header and then save it. Exchange.php never calls curl_close(), and it is impossible to call curl_close() outside the $exhange object, because line 1341 of Exchange.php calls curl_reset($this->curl); Because of this "curl_reset", the library programmer's call to curl_close doesn't do anything, because it simply closes an already reset $this->curl. 

The solution is to only remove 1 line of code from Exchange.php and to add 2 lines of code after that. 

Here's an extract of the code from line 1338 of Exchange.php 

```php
       $http_status_code = curl_getinfo($this->curl, CURLINFO_HTTP_CODE);

        // Reset curl opts
        //curl_reset($this->curl); // This was removed because it kills cookies 
        curl_close($this->curl); // We properly close the curl channel here to save cookies
        $this->curl = curl_init(); // We need a "clean" curl object for additional calls, so we initialize curl again
        
```
Since curl_reset effectively just gives us a clean $curl object, the code above mimics the exiting behavior, while we gain the ability to save cookies. I believe this will be a huge help for people using the CCTX lib, since this would allow people so save cookies immediately by simply adding the following to their code. 123, easy. 

```php
$exchange->curl_options = array(CURLOPT_COOKIEFILE => $cookiejar, CURLOPT_COOKIEJAR => $cookiejar);
```

Sorry if this is not a pull request. I'm not that advanced and when I tried to do a pull request many years back, I screwed up Laravel's Former's repo because I did a rebase wrong. I don't want to do that again. 

For such a tiny change, may I please ask for one of the senior developers here who are already familiar with the Pull Request workflow to have a look at this.

**Comment by kroitor** [comment]
@nightowl77 thx for your report, and pardon for the delays on our side, we will get to it asap.

**Comment by nightowl77** [comment]
Hi Igor

No need to apologize, all in good time. The work you guys have done on CCXT saved thousands of programmers countless hours of programming, so it isn't an issue to wait at all. All my CCXT calls work fine to API's behind Cloudflare and other cloud providers, I just have to give it a generous timeout/sleep, as cloudflare sometimes still block you, even if you follow the exchange's set limits.  It seems that providers like Cloudflare do look a more favorably on connections that send back their own _cf_ cookie hashes.  

The changing of the curl_close commands would make CCXT more versitile, but for now, all is good.

**Comment by kroitor** [comment]
@nightowl77 an update on this issue, thx to @frosty00 for his involvement fixing it, basically, the exchange instance the with underlying cURL handle will now behave in the same way you would expect from the plain cURL.

We've commented out the call to `curl_reset`, let us know if you notice any side-effects from this. That allows passing cookie options and cookies transparently back and forth.

In-memory:

```PHP
include_once ('./ccxt.php');
$cookiejar = '';
$exchange = new \ccxt\kucoin(array(
    'curl_options' => array(CURLOPT_COOKIEJAR => $cookiejar),
));
$response = $exchange->load_markets();
$response = $exchange->fetch_ticker('ETH/BTC');
print_r (curl_getinfo($exchange->curl, CURLINFO_COOKIELIST));
```

In files:

```PHP
include_once ('./ccxt.php');
$cookiejar = './php-cookie.txt';
$exchange = new \ccxt\kucoin(array(
    'curl_options' => array(CURLOPT_COOKIEJAR => $cookiejar),
));
$response = $exchange->load_markets();
// ...
$response = $exchange->fetch_ticker('ETH/BTC');
// when you're done...
unset($exchange); // calls curl_close
// the cookiejar should now be on disk and should be reusable in the future
```

↑ This should work as of version 1.18.1357. Let us know if this does solve the issue for you or if you have any difficulties with it. Thx!

**Comment by mmilojevic** [comment]
Hi guys, @kroitor  you added method in base/Exchange.php:

```
public function __destruct() {
    curl_close ($this->curl);
}
```
Which gave me a problem because destructor is called when we explicitly unset the object, when it goes out of scope, and when the script ends. But I am actually with same exchange object doing multiple curl requests. And then I get error like:

```{"error":"Signature blablabla is incorrect."}  ```

So when instead of destructor place I put the curl_close line at the place @nightowl77  said everything works fine. Could you please check this?

**Comment by kroitor** [comment]
@mmilojevic the problem with closing the curl session in between requests is that it takes too much time to initialize a new session, so if we close it after each request – the entire php implementation will slow down significantly.

Can you post a short, but a complete program (a snippet of 10-30 lines) to reproduce the issue, including the instantiation code (but without your keys) ?

> And then I get error like:
> {"error":"Signature blablabla is incorrect."}

In most cases these types of errors can be worked around by synching the nonce between your exchange objects, as explained here:

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-the-nonce

Let us know if that does not help.

**Comment by kroitor** [comment]
This issue was refixed as was suggested by @nightowl77 initially, due to related issues with cf cookies: https://github.com/ccxt/ccxt/issues/6196

We have added the `curl_close` call to each `fetch` call. And it should work in CCXT version 1.20.17. Thank you for the feedback! Let us know if you have any further difficulties with it.

**Comment by riaworks** [comment]
But I started having delay issues between requests, and after much comparing the versions I found that with this change with each new request a new CURL connection was made and this in PHP makes it very slow, quadrupling the time of the whole process.

I provisionally did this:
if ($ this-> curl) {
             // curl_close ($ this-> curl); // we properly close the curl channel here to save cookies
} else {
             $ this-> curl = curl_init (); // we need a "clean" curl object for additional calls, so we initialize curl again
         }

But we should have something as optional example like this.
if ($ this-> curl && $ this-> curl_close_allways) {
             curl_close ($ this-> curl);
         }
         if (! $ this-> curl) {
             $ this-> curl = curl_init ();
         }

Thanks
Jean

**Comment by riaworks** [comment]
Firends, 
I updated my version of CCXT on Php today via composer 1.16.89 -> 1.21.6.

But I started having delay issues between requests, and after much comparing the versions I found that with this change with each new request a new CURL connection was made and this in PHP makes it very slow, quadrupling the time of the whole process.

I provisionally did this:
if ($ this-> curl) {
             // curl_close ($ this-> curl); // we properly close the curl channel here to save cookies
} else {
             $ this-> curl = curl_init (); // we need a "clean" curl object for additional calls, so we initialize curl again
         }

But we should have something as optional example like this.
if ($ this-> curl && $ this-> curl_close_allways) {
             curl_close ($ this-> curl);
         }
         if (! $ this-> curl) {
             $ this-> curl = curl_init ();
         }

Thanks
Jean

**Comment by riaworks** [comment]
Firends,
I updated my version of CCXT on Php today via composer 1.16.89 -> 1.21.6.

But I started having delay issues between requests, and after much comparing the versions I found that with this change with each new request a new CURL connection was made and this in PHP makes it very slow, quadrupling the time of the whole process.

I provisionally did this:
if ($ this-> curl) {
             // curl_close ($ this-> curl); // we properly close the curl channel here to save cookies
} else {
             $ this-> curl = curl_init (); // we need a "clean" curl object for additional calls, so we initialize curl again
         }

But we should have something as optional example like this.    
    if ($this->curl && $this->curl_close_allways) {
            curl_close($this->curl);
            $this->curl = null;
        }
        if (is_null($this->curl)){
            $this->curl = curl_init(); 
        }

**Comment by kroitor** [comment]
@riaworks 

> I updated my version of CCXT on Php today via composer 1.16.89 -> 1.21.6.

Wow ) Sounds like you haven't updated it for more than a year ) We recommend to update more frequently.

> But I started having delay issues between requests, and after much comparing the versions I found that with this change with each new request a new CURL connection was made and this in PHP makes it very slow, quadrupling the time of the whole process.

Unfortunately, the above solution will not work with Binance: https://github.com/ccxt/ccxt/issues/6196#issuecomment-559829165 ← it would be really helpful if you could test that issue and compare 1.20.16 vs 1.20.17 on your side and report back whether you have the same problems with Binance or not. Thx!

**Comment by kroitor** [comment]
@riaworks can you provide a small but complete minimal reproducible example code that you use to profile the difference between the two versions? 

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://stackoverflow.com/help/minimal-reproducible-example

**Comment by kroitor** [comment]
Ok, after reviewing this issue one more time, we decided to make the `curl_close()` and `curl_reset()` calls fully-controllable by the user, and starting from CCXT version 1.21.8 we have introduced 2 new exchange options:

```PHP
        $this->curl_reset = true; // reset by default
        $this->curl_close = false; // don't close by default
```

See the implementation here:

- https://github.com/ccxt/ccxt/blob/master/php/base/Exchange.php#L1253

So, the default behavior is to reset the curl session quickly, without a full reinitialization, however, that doesn't work with cookies, so, in order to get those cookies and close the session the user can now override those two properties like any other exchange property:

```PHP
$exchange = new $exchange_class(array(
    'curl_close' => true,
    'curl_reset' => false,
));
```

Hope that satisfies all use cases. Let us know if you have any issues with it.
