### ISSUE TITLE
Question - Volume of a pair in last 5 minutes

### ISSUE THREAD

**Issue by Gennttii** [ccxt/ccxt#5916]
Hi guys, maybe its in the manual , but I looked and didn't find it. How to get the volume of  the last 5 minutes of a pair?

I can get last 24 h volume, but not last 5 minutes volume..

Thanks in advance ..
Regards

**Comment by kroitor** [comment]
@Gennttii you want 5m OHLCV: 

- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts

It will return an array of structures, each representing a 5m span of time, consequently, containing the prices for the designated period and the traded volume.

The OHLCV structure is described here:

- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-structure

Hope that helps)

**Comment by Gennttii** [comment]
Thanks so much, this is what I was looking for..
