### ISSUE TITLE
need huobipro contract api

### ISSUE THREAD

**Issue by southwhale** [ccxt/ccxt#5923]
- OS: windows
- Programming Language version: js
- CCXT version: 1.18.1223
- Exchange: huobipro
- Method: all of the contract api
I can not find contract api of huobipro.Is there any plan to add them. Thank you.

权限类型 | 接口数据类型 | 请求方法 | 类型 | 描述 | 需要验签
-- | -- | -- | -- | -- | --
读取 | 基础信息接口 | api/v1/contract_contract_info | GET | 获取合约信息 | 否
读取 | 基础信息接口 | api/v1/contract_index | GET | 获取合约指数信息 | 否
读取 | 基础信息接口 | api /v1/contract_price_limit | GET | 获取合约最高限价和最低限价 | 否
读取 | 基础信息接口 | api/v1/contract_open_interest | GET | 获取当前可用合约总持仓量 | 否
读取 | 基础信息接口 | api/v1/contract_delivery_price | GET | 获取预估交割价 | 否
读取 | 基础信息接口 | https://www.hbdm.com/heartbeat | GET | 查询系统是否可用 | 否
读取 | 市场行情接口 | /market/depth | GET | 获取行情深度数据 | 否
读取 | 市场行情接口 | /market/history/kline | GET | 获取K线数据 | 否
读取 | 市场行情接口 | /market/detail/merged | GET | 获取聚合行情 | 否
读取 | 市场行情接口 | /market/trade | GET | 获取市场最近成交记录 | 否
读取 | 市场行情接口 | /market/history/trade | GET | 批量获取最近的交易记录 | 否
读取 | 市场行情接口 | api/v1/contract_risk_info | GET | 查询合约风险准备金余额和预估分摊比例 | 否
读取 | 市场行情接口 | api/v1/contract_insurance_fund | GET | 查询合约风险准备金余额历史数据 | 否
读取 | 市场行情接口 | api/v1/contract_adjustfactor | GET | 查询平台阶梯调整系数 | 否
读取 | 市场行情接口 | api/v1/contract_his_open_interest | GET | 平台持仓量的查询 | 否
读取 | 资产接口 | api/v1/contract_account_info | POST | 获取用户账户信息 | 是
读取 | 资产接口 | api/v1/contract_position_info | POST | 获取用户持仓信息 | 是
读取 | 账户接口 | api/v1/contract_sub_account_list | POST | 币查询母账户下所有子账户资产信息 | 是
读取 | 账户接口 | api/v1/contract_sub_account_info | POST | 查询单个子账户资产信息 | 是
读取 | 账户接口 | api/v1/contract_sub_position_info | POST | 查询单个子账户持仓信息的 | 是
读取 | 账户接口 | api/v1/contract_financial_record | POST | 查询用户财务记录 | 是
读取 | 账户接口 | api/v1/contract_order_limit | POST | 查询用户当前的下单量限制 | 是
读取 | 账户接口 | api/v1/contract_fee | POST | 查询用户当前的手续费费率 | 是
读取 | 账户接口 | api/v1/contract_transfer_limit | POST | 查询用户当前的划转限制 | 是
读取 | 账户接口 | api/v1/contract_position_limit | POST | 用户持仓量限制的查询 | 是
交易 | 交易接口 | api/v1/contract_order | POST | 合约下单 | 是
交易 | 交易接口 | api/v1/contract_batchorder | POST | 合约批量下单 | 是
交易 | 交易接口 | api/v1/contract_cancel | POST | 撤销订单 | 是
交易 | 交易接口 | api/v1/contract_cancelall | POST | 全部撤单 | 是
读取 | 交易接口 | api/v1/contract_order_info | POST | 获取合约订单信息 | 是
读取 | 交易接口 | api/v1/contract_order_detail | POST | 获取订单明细信息 | 是
读取 | 交易接口 | api/v1/contract_openorders | POST | 获取合约当前未成交委托 | 是
读取 | 交易接口 | api/v1/contract_hisorders | POST | 获取合约历史委托 | 是
读取 | 交易接口 | api/v1/contract_matchresults | POST | 获取历史成交记录 | 是
交易 | 账户接口 | v1/futures/transfer | POST | 币币账户和合约账户间进行资金的划转 | 是
交易 | 账户接口 | api/v1/lightning_close_position | POST | 闪电平仓下单 | 是

**Comment by kroitor** [comment]
@iamweilee

> Is there any plan to add them.

Yes, we are going to add those endpoint and will unify contract trading asap. Will update you here. Thx!

**Comment by icytrader** [comment]
Hi Kroitor，

I have been a long time user of CCXT and much looking forward to the release of paid version. Would you consider further prioritizing those popular exchanges？ For example, huobi is among the top 3 derivatives market and I have been using it heavily. Would be great if we can put more resources to the top exchanges so we can have full functionality, rather than expanding support to smaller exchanges where there is little volume and not many users. 

Thank you very much.

**Comment by kroitor** [comment]
Hi @icytrader !

> Would you consider further prioritizing those popular exchanges？

Yes, that's exactly what we're going to focus on immediately after the release.

**Comment by icytrader** [comment]
> @iamweilee
> 
> > Is there any plan to add them.
> 
> Yes, we are going to add those endpoint and will unify contract trading asap. Will update you here. Thx!

for the unification, would you use Okex contract trading as the template? the contracts specification and trading rules on Okex and Huobipro are very similar.

**Comment by joyser** [comment]
Any updates on adding huobi DM contract trading to ccxt?
thanks.

**Comment by kroitor** [comment]
@joyser : https://github.com/ccxt/ccxt/issues/6697

**Comment by kroitor** [comment]
@qqmastercom we are working on it right now and will hopefully deliver huobi's contract api this month!

**Comment by kroitor** [comment]
The support for Huobi Derivatives was added in CCXT 1.66.16+.

**Comment by as-poldo** [comment]
Hi Kroitor，

I still can't manage to fetch my balance of derivatives contracts on huobi. which defaultType should i use?

**Comment by kroitor** [comment]
@as-poldo hi! Which contracts-balance do you want specifically? 

- Linear perpetual swaps?
- Inverse perpetual swaps?
- Linear futures?
- Inverse futures?
- Other?

Have you checked these examples? ↓

- https://github.com/ccxt/ccxt/blob/master/examples/js/huobi-swaps.js
- https://github.com/ccxt/ccxt/blob/master/examples/js/huobi-futures.js
- https://github.com/ccxt/ccxt/blob/master/examples/py/huobi-swaps.py
- https://github.com/ccxt/ccxt/blob/master/examples/py/huobi-futures.py
- https://github.com/ccxt/ccxt/blob/master/examples/php/huobi-swaps.php
- https://github.com/ccxt/ccxt/blob/master/examples/php/huobi-futures.php

**Comment by as-poldo** [comment]
Thank you for the quick response. For the balance that i was looking for i had to add 'defaultSubType': 'linear'. Now it works. 
Thank you for your great work!

**Comment by QGB** [comment]
@rocco-piovani @southwhale  ccxt 如何限定下单金额，而不是代币数量？
