### ISSUE TITLE
Get max returns for fetch_ohlcv

### ISSUE THREAD

**Issue by AlgoQ** [ccxt/ccxt#5924]
Hello!

I'm using the "fetch_ohlcv" function and I want to know if it is possible to know the max results of a return. I've found that the max results for binance is 1000 for example. But I like to know it of most of the exchanges how has the "fetch_ohlcv" function. Is it possible to find out this with the ccxt library or do I need to look it up for every exchange.

Greats,
Kobe Janssens

- OS: Ubuntu 18.04.3
- Programming Language version: Python 3.6.8
- CCXT version: 1.18.1223
- Exchange: All
- Method: fetch_ohlcv()

**Comment by kroitor** [comment]
@JanssensKobe at this point, those limits are mostly coded within the method implementations themselves, as the exchange APIs don't serve limit values from the API. Unfortunately, this is hard to unify without actually making 1000s of deposits, withdrawals, trades and orders with each exchange, which, of course, requires burning some funds for the tests. So, at this time, there's no way to get those limits without looking into the code – we have to add them in userland for each exchange in question. However, we are going to unify those maximums as exchange properties and will let you know asap.

**Comment by ttodua** [comment]
as said above, the parameter will be incorporated once [.Features functionality](https://github.com/ccxt/ccxt/issues/6772) is done. Monitor for that topic for more info.
