### ISSUE TITLE
fetchMyTrades - since parameter is not working

### ISSUE THREAD

**Issue by cyberwizgeek** [ccxt/ccxt#5926]
OS: Windows
Programming Language version: Node JS v10.15.3
CCXT version: 1.18.1223
Exchange: Binance
Method: fetchMyTrades

Tried the code below. It looks like the 'since' parameter is not working.  I initially use a limit of 100 which retrieved all of my 86 trades. However, when I changed the limit to 40, the function retrieves the most recent 40 trades and not the trades from the value of 'since' (1514725200000).

```
// JavaScript
if (exchange.has['fetchTrades']) {
    let since = 1514725200000 /

    let allTrades = []
    while (since < exchange.milliseconds ()) {
        const symbol = 'BTC/USDT'
        const limit = 40 // change for your limit
        const trades = await exchange.fetchTrades (symbol, since, limit)
        if (trades.length) {
            since = trades[trades.length - 1]['timestamp']
            allTrades = allTrades.concat (trades)
        } else {
            break
        }
    }
}
```

**Comment by kroitor** [comment]
@cyberwizgeek plz see the following options:

- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L222
- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L613

Let us know if the above does not help.

**Comment by kroitor** [comment]
@cyberwizgeek uhm, pardon, looks like you were asking of private trades, and the since argument there is not supported yet. We will do our best to add it ASAP. Will let you know when it arrives. Your contributions are welcome: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
