### ISSUE TITLE
Have problem with 'ReduceOnly' param{}

### ISSUE THREAD

**Issue by Kalelv45** [ccxt/ccxt#5927]
- OS: MacOS Mojave
- Programming Language version: Python 
- CCXT version: 1.18.1213
- Exchange: Bitmex 
- Method: create_order

bitmex.create_order(symbol='BTC/USD', type='limit', side='buy', amount= abs(btc_current_position), price=price-0.5, params={
        'post': 'ReduceOnly'
        })

I have two boob questions: Why’ won't this work. 
and where and how can I look for all the various params. 
Where can I find the list of the various params I can use for the various methods.

Thanks in advance

**Comment by kroitor** [comment]
@Kalelv45 pardon for the delays with our answer, it appears that you have resolved the issue already. Let us know if you still have a difficulty with it. You may want to read this entire Manual: 

- https://github.com/ccxt/ccxt/wiki/Manual
