### ISSUE TITLE
cancelOrders: this.privatePostCancelOrder is not a function

### ISSUE THREAD

**Issue by onanying** [ccxt/ccxt#5936]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: win10
- Programming Language version: nodejs v10.16.3
- CCXT version: 1.18.1124
- Exchange: digifinex
- Method: cancelOrders https://github.com/ccxt/ccxt/blob/master/js/digifinex.js#L731

has:

```
'cancelOrders': true
```

https://github.com/ccxt/ccxt/blob/master/js/digifinex.js#L19

code:

```
exchange.cancelOrders(['ee2532b4d304e70ef00f28b765f3c0f7'],'DFT/USDT');
```

error:

```
TypeError: this.privatePostCancelOrder is not a function
```

**Comment by szmcdull** [comment]
privatePostCancelOrder  => privatePostMarketOrderCancel

**Comment by kroitor** [comment]
@szmcdull thank you for answering the question!

@onanying let us know if the above does not help!
