### ISSUE TITLE
RightBTC update

### ISSUE THREAD

**Issue by marcuswin** [ccxt/ccxt#5942]
Looks like they change API too
Proof:https://rightbtc.zendesk.com/hc/en-us/articles/360034136611-Old-Site-Closure-Annoucement

**Comment by gr936** [comment]
```
...
                //'api': 'https://www.rightbtc.com/api',
                'api': 'https://www.rightbtc.com/v1',
...
                        //'trading_pairs',
                        'markets',
...
                        //'depth/{trading_pair}',
                        //'depth/{trading_pair}/{count}',
                        'depth/',
                        'depth/',
...
                        //'trading_pairs'
                        'markets'
...
        //let url = this.urls['api'] + '/' + api + '/' + this.implodeParams (path, params);
        let url = this.urls['api'] + '/' + api.substring(0, 3) + '/' + this.implodeParams (path, params);
...
```

but getting a "TypeError: this.publicGetTradingPairs is not a function at rightbtc.fetchMarkets" error for now.  Error appears with the correction of trading_pairs.

**Comment by kroitor** [comment]
@gr936 more details on the structure of the lib here:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#implicit-api-methods
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

**Comment by enzesi** [comment]
now I have
AttributeError: 'rightbtc' object has no attribute 'publicGetTradingPairs'
trying to reimplement it, so what exactly is a trading pair?

ccxt/rightbtc.py", line 148, in fetch_markets
    markets = self.publicGetTradingPairs(params)

**Comment by kroitor** [comment]
> so what exactly is a trading pair?

If you're asking, then I'd highly recommend to read the entire Manual from top to bottom: https://github.com/ccxt/ccxt/wiki/Manual, most of these questions are already answered there ) Then plz read this: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md. Let me know if you have further questions after that ;)

**Comment by kroitor** [comment]
@enzesi https://github.com/ccxt/ccxt/wiki/Manual#markets

**Comment by frosty00** [comment]
delisted
