### ISSUE TITLE
Indodax support for market orders

### ISSUE THREAD

**Issue by azharuniverse** [ccxt/ccxt#5944]
Indodax now support market and stop orders. 
I wish to execute market orders on indodax using ccxt

- OS: ALL
- Programming Language version: ALL
- CCXT version: 1.18.1157
- Exchange: Indodax
- Method: createOrder

**Comment by azharuniverse** [comment]
Hi @kroitor , This is not a question but a feature request. Indodax has released support for market order but ccxt doesn't yet support it.

**Comment by azharuniverse** [comment]
You can close this ticket. I just checked everything in more detail and found that although they support Market and Stop orders on selected pair on exchange. There is no way it can be done via API. 
Looks like they haven't updated their API since long time.

**Comment by kroitor** [comment]
@azharuniverse ok, thanks for the followup, really appreciate the feedback from you! Closing this for now.
