### ISSUE TITLE
Okex V3 Market-Close All implementation

### ISSUE THREAD

**Issue by TwenTy47** [ccxt/ccxt#5946]
- OS: Ubuntu 18.04
- Programming Language version: Python 3.7.3
- CCXT version: 1.18.861
- Exchange: Okex
- Method: [Market-Close All](https://www.okex.com/docs/en/#futures-close_all) (POST /api/futures/v3/close_position)

Hi! Is there an implementation of ```Market-Close All``` of okex V3? I didn't find any in my current ccxt version(1.18.861) or latest version(1.18.1234).

**Comment by kroitor** [comment]
@TwenTy47 hi! We've added those missing endpoints to the okex3 futures API implementation, and you should be able to call those endpoints using [implicit API methods](), as described in the Manual, as of CCXT 1.18.1236 (it will arrive in 15 minutes). Let us know if you anything. Thx!
