### ISSUE TITLE
Hitbtc error  createOrder

### ISSUE THREAD

**Issue by julesGoullee** [ccxt/ccxt#5955]
- CCXT version:1.18.1241
- Exchange: Hitbtc2
- Method:createOrder
After market order sucessfully on  hitbtc the parsing for the response throw at https://github.com/ccxt/ccxt/blob/master/js/hitbtc2.js#L1205 
``` TypeError: Cannot read property 'cost' of undefined ```

**Comment by kroitor** [comment]
@julesGoullee can you plz post your verbose request/response?

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ#i-am-calling-a-method-and-i-get-an-error-what-am-i-doing-wrong

**Comment by bazya-8** [comment]
Something similar started to happen since yesterday - errors during parsing response from market orders 

ccxt\hitbtc2.py", line 1105, in parse_order
    feeCost += trades[i]['fee']['cost']
TypeError: 'NoneType' object is not subscriptable

**Comment by kroitor** [comment]
@bazya-8 can you plz post your verbose request/response? ((

**Comment by kroitor** [comment]
@julesGoullee , @bazya-8 we need a sample of verbose request/response in order to resolve this.

```Python
exchange.load_markets()
exchange.verbose = True
exchange.create_order (...
```

**Comment by kroitor** [comment]
@Norfolc thank you! This should be fixed in 1.18.1245 (will arrive in 10-15 minutes).

**Comment by julesGoullee** [comment]
Hey guys, thanks @nohtaray  thx for the verbose request & @kroitor awsome for the fix

**Comment by bazya-8** [comment]
Many thanks, guys!
