### ISSUE TITLE
How to use binance future api by ccxt

### ISSUE THREAD

**Issue by JeremyChiaYilin** [ccxt/ccxt#5959]
How to use binance future api by ccxt?

**Comment by szdong** [comment]
I want to know too...

**Comment by JeremyChiaYilin** [comment]
exchange_class = getattr(ccxt, 'binance')
binance = exchange_class({
		....
		....
		'urls': {
                'logo': 'https://user-images.githubusercontent.com/1294454/29604020-d5483cdc-87ee-11e7-94c7-d1a8d9169293.jpg',
                'api': {
                    'public': 'https://fapi.binance.com/fapi/v1',
                    'private': 'https://fapi.binance.com/fapi/v1',
                },}
                ....
			})


You could set this params in python.

**Comment by kroitor** [comment]
See this Pull Request for details on the support for Binance futures API in CCXT:

- https://github.com/ccxt/ccxt/pull/5907

This is going to be merged soon. Let us know if the above does not answer your question.
