### ISSUE TITLE
this.priceToPrecision() is unreliable at least in Bitso BTC/MXN

### ISSUE THREAD

**Issue by auterium** [ccxt/ccxt#5960]
Bitso uses `this.pticeToPrecision()` as many other exchange implementations do. This can be found [here](https://github.com/ccxt/ccxt/blob/master/js/bitso.js#L306) which usually works OK.

In the specific case of BTC/MXN, the minimum price for an order is 500.00, which makes `this.priceToPrecision()` to determine that the currency precision is without decimal places, however for this market (as well as any other MXN market in Bitso) the precision is 2 decimal places. This results in sending to the exchange a price different than the requested.

I'm happy to do the PR for the adjustments in Bitso for the BTC/MXN market, however I'm not certain of the impact in the other exchanges where it could have a similar error, hence this issue report.

**Comment by kroitor** [comment]
Thx for reporting, @auterium! Your help would on a proper fix would be very much appreciated. We need to find a way to load the precision information from their API.

**Comment by auterium** [comment]
Hi @kroitor, my pleasure. Unfortunately Bitso doesn't have a standard way of providing such info through their API. Here's an example of how CCXT returns market info for BTC/MXN:
```js
{
  "id": "btc_mxn",
  "symbol": "BTC/MXN",
  "base": "BTC",
  "quote": "MXN",
  "info": {
    "book": "btc_mxn",
    "minimum_price": "500.00",
    "maximum_price": "16000000.00",
    "minimum_amount": "0.000075",
    "maximum_amount": "500.00000000",
    "minimum_value": "5",
    "maximum_value": "10000000.00"
  },
  "limits": {
    "amount": {
      "min": 0.000075,
      "max": 500
    },
    "price": {
      "min": 500,
      "max": 16000000
    },
    "cost": {
      "min": 5,
      "max": 10000000
    }
  },
  "precision": {
    "amount": 6,
    "price": 0
  }
}
```

Although the parser implies that the precision is of 6 in the amount and 0 on the price, in practice these should be 8 (BTC) and 2 (MXN).

Looking at the source code, I fount the first issue being that `precisionFromString()` [removes any trailing zeros](https://github.com/ccxt/ccxt/blob/7464decd0508d76b3e49047500dffa3d82c5776c/js/base/functions/number.js#L83), which Bitso normally uses to provide precision. The only excueption I've seen so far for such precision not being correct if based on the trailing zeros is in XRP/MXN where for some reason (legacy, maybe?) they provide more trailing zeros than those actually supported.

I can open a PR for the necessary changes on Bitso, but I'm a bit skeptical on the trailing zeros removal to determine precision. On the other hand, would it make sense to make the `priceToPrecision()` usage an opt out? We already deal ourselves with such precision on our system, so this is redundant in our case as well as dangerous (prices were not opening at the expected price, so our limit orders that should have been takers were sitting a few cents away).

**Comment by kroitor** [comment]
> The only excueption I've seen so far for such precision not being correct if based on the trailing zeros is in XRP/MXN where for some reason (legacy, maybe?) they provide more trailing zeros than those actually supported.

I'd suggest a bitso-specific fix, something like the following in `fetchMarkets()`:

```JavaScript
const precisionOptions = this.safeValue (this.options, 'precision', {});
// a workaround for XRP/MXN, https://github.com/ccxt/ccxt/issues/5960
// should be defined in `describe() under the 'options':'precision' key)
if (symbol in this.options['precision']) {
    precision = {
        'amount': this.safeInteger (this.options['precision'][symbol], 'amount')
        'price': this.safeInteger (this.options['precision'][symbol], 'price'),
    };
} else {
    const amountPrecisionString = this.safeString (market, 'maximum_amount');
    if (amountPrecisionString !== undefined) {
        const amountPrecisionLength = amountPrecisionString.length;
        amountPrecisionString[amountPrecisionLength - 1] = '1'; // hacky, but will work
    }
    const pricePrecisionString = this.safeString (market, 'maximum_price');
    if (pricePrecisionString !== undefined) {
        const pricePrecisionLength = pricePrecisionString.length;
        pricePrecisionString[pricePrecisionLength - 1] = '1'; // hacky, but will work
    }
    precision = {
        'amount': this.precisionFromString (amountPrecisionString),
        'price': this.precisionFromString (pricePrecisionString),
    };
}
```

What do you think?

**Comment by auterium** [comment]
I like the idea of having the workaround that you describe, as XRP/MXN is not the only case where the precision cannot be accurately inferred from the market data (TUSD/BTC would also yield wrong results). However, I think the `this.precisionFromString()` could still be used with an override in Bitso class to not remove the trailing zeros and on top of that doing from both the maximums and minimums and get the biggest precision from both:

```js
    async fetchMarkets (params = {}) {
        const response = await this.publicGetAvailableBooks (params);
        const markets = this.safeValue (response, 'payload');
        const result = [];
        for (let i = 0; i < markets.length; i++) {
            // ... reduced for the example
            const precisionOptions = this.safeValue (this.options, 'precision', {});
            // a workaround for XRP/MXN, https://github.com/ccxt/ccxt/issues/5960
            // should be defined in `describe() under the 'options':'precision' key)
            if (symbol in this.options['precision']) {
                precision = {
                    'amount': this.safeInteger (this.options['precision'][symbol], 'amount')
                    'price': this.safeInteger (this.options['precision'][symbol], 'price'),
                };
            } else {
                precision = {
                    'amount': Math.max(
                        this.precisionFromString (market['minimum_amount']),
                        this.precisionFromString (market['maximum_amount'])
                    ),
                    'price': Math.max(
                        this.precisionFromString (market['minimum_price']),
                        this.precisionFromString (market['maximum_price'])
                    ),
                };
            }
            // ...
        }
        return result;
    }

    precisionFromString (string) {
        const split = string.split ('.');
        return (split.length > 1) ? (split[1].length) : 0;
    }
```

What do you think?

As mentioned before, I would suggest also to be able to opt-out of the automatic rounding (intended more for advanced users)

**Comment by kroitor** [comment]
> However, I think the this.precisionFromString() could still be used with an override in Bitso class to not remove the trailing zeros 

The problem with this approach is that we change `precisionFromString` behavior, and some user may rely on it, so, if a user wants his bitso markets to work well, but also wants to have a handy helper like `precisionFromString` on the exchange instance for whatever reason it could be – we are kinda breaking it for the user. So, as a user, i'd prefer the workaround logic to live inside bitso-specific `fetchMarkets`, rather than inside bitso-specific `precisionFromString`. Let me know if that makes sense.

> and on top of that doing from both the maximums and minimums and get the biggest precision from both:

To that – I totally agree, that's a good idea, we should get the maximums, indeed, however, the actual solution is a bit more complicated, since we support 3 languages. There are certain implication from –we have to design the code to be portable:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#accessing-dictionary-keys
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#sanitizing-input-with-safe-methods

**Comment by auterium** [comment]
> The problem with this approach is that we change precisionFromString behavior, and some user may rely on it, so, if a user wants his bitso markets to work well, but also wants to have a handy helper like precisionFromString on the exchange instance for whatever reason it could be – we are kinda breaking it for the user. So, as a user, i'd prefer the workaround logic to live inside bitso-specific fetchMarkets, rather than inside bitso-specific precisionFromString. Let me know if that makes sense.

It makes total sense, I think we can build up something that is 100% specific to Bitso's `fetchMarkets`.

While looking at Bitso's markets, they pair up everything either to MXN or BTC (these are the only 2 quotes they use) in which all MXN markets are 2 decimals and BTC markets are 8. As for the `base` currencies, they all have 8 decimals except for 2:
- XRP: 6 decimals
- tUSD: 2 decimals

Since the precision cannot be accurately determined just by looking at their markets list API, does it makes sense to do it based on a dictionary containing the above mentioned rules? I was looking into using a "global" key like `this.options`, but I can't find any existing one that could be used, which means a new one must be defined in a way that makes sense for all other exchanges. Otherwise it would be 100% specific to the `Bitso::fetchMarkets()` and have the aforementioned rules "hardcoded" into it.

**Comment by kroitor** [comment]
> Since the precision cannot be accurately determined just by looking at their markets list API, does it makes sense to do it based on a dictionary containing the above mentioned rules?

Yes, I suggest that we "hardcode" those under `this.options['precision'][symbol]['amount/price']` or under `this.options['precision'][marketId]['amount/price']`, or under `this.options['precision'][currencyCode]['base']` + `this.options['precision'][currencyCode]['quote']`.

> I was looking into using a "global" key like this.options, but I can't find any existing one that could be used, which means a new one must be defined in a way that makes sense for all other exchanges.

I think we should place that in `this.options['precision']` anyway. In most cases the `options` property contains exchange-specific overrides and options, so, i'd use the existing dict, otherwise we will have to add the new property to all base classes. In this case, however, it's more preferable to change just the bitso file. I would refrain from hardcoding all the markets, though, because that may quickly become outdated. Unfortunately, the exchanges edit their trading rules too often to maintain the info manually.

**Comment by auterium** [comment]
> I think we should place that in this.options['precision'] anyway. In most cases the options property contains exchange-specific overrides and options, so, i'd use the existing dict, otherwise we will have to add the new property to all base classes. In this case, however, it's more preferable to change just the bitso file.

I agree, that's why I was looking for a reasonable existing place to place them instead of adding a new one.

I'll do a PR later today. I'll try to do one that includes also Python and PHP, although my skills sin those are not as up to date as JS. I'll tag this issue and at-mention you on the PR if that's OK with you

**Comment by kroitor** [comment]
@auterium thank you! Appreciate your involvement very much! ) Looking forward to it!
