### ISSUE TITLE
How to place oco order on Binance?

### ISSUE THREAD

**Issue by artbred** [ccxt/ccxt#5966]
Hello! I am having troubles with placing oco order on binance. Could please send me an example using javascript? Also I do not quite understand how to calculate the max amount of coin that i could sell. Thank you very much for your work!

**Comment by kentenzer** [comment]
According to gitter dev chat, Binance OCO order's support has been included in ccxt since version 1.18.1162 through implicit API methods (https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods). That said, I still don't know how to use it :)

**Comment by kentenzer** [comment]
I am trying to make the API implicit call following Binance API documentation: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-oco-trade

My Python code: 
`exchange.private_post_order_oco({ "symbol": "BTCUSDT", "side": "buy", "quantity": 0.005, "price": 7000, "stopPrice": 10000})`

This is my output: 
`ccxt.base.errors.InvalidOrder: binance {"code":-1013,"msg":"Stop loss orders are not supported for this symbol."}`

Any hint on what is wrong?

**Comment by kroitor** [comment]
@kentenzer this is very interesting... Try switching the stop-limit preference here: https://www.binance.com/en/usercenter/settings/preference

Your params look ok, and if you do:

```
import ccxt
from pprint import pprint
exchange = ccxt.binance()
exchange.load_markets()
pprint(exchange.market('BTC/USDT'))
```

You should see something like this:

```JavaScript
// mbp:ccxt igorkroitor$ node examples/js/cli binance market BTC/USDT
binance.market (BTC/USDT)
{     limits: { amount: { min: 0.000001, max: 9000 },
                 price: { min: 0.01, max: 1000000 },
                  cost: { min: 10, max: undefined }   },
   precision: { base: 8, quote: 8, amount: 6, price: 2 },
   tierBased:    false,
  percentage:    true,
       taker:    0.001,
       maker:    0.001,
          id:   "BTCUSDT",
      symbol:   "BTC/USDT",
        base:   "BTC",
       quote:   "USDT",
      baseId:   "BTC",
     quoteId:   "USDT",
        info: {                 symbol:   "BTCUSDT",
                                status:   "TRADING",
                             baseAsset:   "BTC",
                    baseAssetPrecision:    8,
                            quoteAsset:   "USDT",
                        quotePrecision:    8,
                            orderTypes: [ "LIMIT",
                                          "LIMIT_MAKER",
                                          "MARKET",
                                          "STOP_LOSS_LIMIT",  // ←---------- INTERESTING...
                                          "TAKE_PROFIT_LIMIT" ],
                        icebergAllowed:    true,
                            ocoAllowed:    true, // ←------------------ INTERESTING...
                  isSpotTradingAllowed:    true,
                isMarginTradingAllowed:    true,
                               filters: [ { filterType: "PRICE_FILTER",
                                              minPrice: "0.01000000",
                                              maxPrice: "1000000.00000000",
                                              tickSize: "0.01000000"        },
                                          {     filterType: "PERCENT_PRICE",
                                              multiplierUp: "5",
                                            multiplierDown: "0.2",
                                              avgPriceMins:  5               },
                                          { filterType: "LOT_SIZE",
                                                minQty: "0.00000100",
                                                maxQty: "9000.00000000",
                                              stepSize: "0.00000100"     },
                                          {    filterType: "MIN_NOTIONAL",
                                              minNotional: "10.00000000",
                                            applyToMarket:  true,
                                             avgPriceMins:  5              },
                                          { filterType: "ICEBERG_PARTS", limit: 10 },
                                          { filterType: "MARKET_LOT_SIZE",
                                                minQty: "0.00000000",
                                                maxQty: "3200.00000000",
                                              stepSize: "0.00000000"       },
                                          {       filterType: "MAX_NUM_ALGO_ORDERS",
                                            maxNumAlgoOrders:  5                     } ] },
      active:    true                                                                       }
```

Have you tried reaching out to Binance tech support on this issue?

**Comment by kentenzer** [comment]
Just switched off the "Order Confirmation Preference" for "Stop-Limit Order" which made no difference. I even created a new API key after the setting change. 

Also checked market data for 'BTC/USDT' and my orderTypes contains STOP_LOSS_LIMIT and ocoAllowed is True (same as yours).

Were you able to create an OCO order with these parameters?

**Comment by kentenzer** [comment]
Strange... this works:
`order = exchange.private_post_order_oco({ "symbol": "BTCUSDT", "side": "buy", "quantity": 0.002, "price": 7000, "stopPrice": 10000})`

And this doesn't"
`# order = exchange.private_post_order_oco({ "symbol": "BTCUSDT", "side": "buy", "quantity": 0.002, "price": 7000, "stopPrice": 10000, "stopLimitPrice": 10000, "stopLimitTimeInForce": "GTC"})`

But parameters "stopLimitPrice" (and "stopLimitTimeInForce") are optional, I raised a ticket in Binance for them to check as well.

**Comment by kentenzer** [comment]
Binance confirmed they will update their documentation.
In order to create an OCO order, the following parameters are required:
 symbol
 quantity
 side
 price
 stopPrice
 stopLimitPrice
 stopLimitTimeInForce

My issue can be closed, I believe this also replies @artbred question.

**Comment by kroitor** [comment]
@kentenzer thank you for the followup on this!

**Comment by fuvser** [comment]
Hello, how can I buy at the market price instead of choosing a price to buy manually?
