### ISSUE TITLE
CoinEx IOC Order question

### ISSUE THREAD

**Issue by mkang1234** [ccxt/ccxt#5969]
- OS: Windows  10
- Programming Language version: Python
- CCXT version: 1.18.1243
- Exchange: CoinEx
- Method: create_order

If I wanted to submit an IOC order, what do I need to pass to function create_order to submit an IOC instead of a normal limit order in CoinEx?  Thank you.

**Comment by kroitor** [comment]
Open https://github.com/ccxt/ccxt#supported-cryptocurrency-exchange-markets
Scroll down to coinex and click the API doc link

<img width="1283" alt="Screen Shot 2019-10-13 at 11 25 17" src="https://user-images.githubusercontent.com/1294454/66712882-29071a80-edac-11e9-8af5-2e21b85ee84d.png">

Find the IOC order there and click it

<img width="1283" alt="Screen Shot 2019-10-13 at 11 26 07" src="https://user-images.githubusercontent.com/1294454/66712887-46d47f80-edac-11e9-9cbe-610e72c02c9b.png">

See the required params here: https://github.com/coinexcom/coinex_exchange_api/wiki/033IOC_order

<img width="1281" alt="Screen Shot 2019-10-13 at 11 27 48" src="https://user-images.githubusercontent.com/1294454/66712903-8307e000-edac-11e9-866c-f4195f40de90.png">

Check CCXT code for create_order here: https://github.com/ccxt/ccxt/blob/master/python/ccxt/coinex.py#L470

The authentication params `access_id` and `tonce` are handled for you by the CCXT, so you don't have to worry about that.

You need to supply the following:

```Python
exchange.load_markets()
symbol = 'ETH/BTC'
amount = 123
price = 0.022
# with the previous versions of CCXT
# you have to format the price and pass it in params
params = {'price': exchange.price_to_precision(symbol, price)}
exchange.create_order(symbol, 'ioc', 'sell', amount, price, params) 
```

If you update CCXT to version 1.18.1252 you will be able to do it even easier, like so:

```Python
# with CCXT 1.18.1252+ 
exchange.create_order('ETH/BTC', 'ioc', 'sell', amount=123, price=0.022) 

Version 1.18.1252 will be available for downloading in 20-30 minutes.

Let us know if the above does not help.

**Comment by mkang1234** [comment]
Thank you. In my version of create_order function, I only saw type == 'limit' so wasn't sure.  

        if type == 'limit':
            price = float(price)  # self line is deprecated
            request['price'] = self.price_to_precision(symbol, price)
