### ISSUE TITLE
Feature request: create market order with fund

### ISSUE THREAD

**Issue by RenKelvin** [ccxt/ccxt#597]
I'd like to have a method like this: `createMarketBuyOrder(fund: 100.00)`, where `fund` means the total money you're going to spend.
It's equal to an order with `price = market_price`, `amount = fund / market_price`.

**Comment by kroitor** [comment]
Hello, @RenKelvin ! Thx for feedback! Unfortunately, the majority of exchanges do not support that, so, you will have to precalculate the price and amount in userland for now (multiply by hand before submitting the order). We will think on adding a specific method for that. In the meantime, I would close this issue if you don't mind. Feel free to reopen it or ask your questions, if you have any. We will update you on the progress as well. Thx again!
