### ISSUE TITLE
Huobi HBPOINTs

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#5971]
- Exchange: Huobi Pro
- Method: parseTrade

Now we have:
```
if (filledPoints !== undefined) {
            if ((feeCost === undefined) || (feeCost === 0.0)) {
                feeCost = filledPoints;
                feeCurrency = this.safeCurrencyCode ('HBPOINT');
            }
        }
```

But exchange give:
```
 { symbol: 'bhtbtc',
       'filled-amount': '2313.49',
       'filled-points': '0.048353085787075596',
       'fee-deduct-currency': 'ht',
       source: 'spot-api',
       role: 'maker',
       'match-id': 100008593285,
       'created-at': 1570977039624,
       'order-id': 51733055975,
       price: '0.00000474',
       'filled-fees': '0',
       id: 7950463553,
       type: 'sell-limit' },
```

So fee charged from HT (Huobi Token) and there are no any HBPoints. May be it is something outdated and we need to set HT as fee currency?

**Comment by kroitor** [comment]
Hi @ndubel ! 

> So fee charged from HT (Huobi Token)

Are you sure about this? The `fee-deduct-currency` does not necessarily define the fee currency that was actually used for paying the fees, it shows your default setting afaik, so it allows to deduce those fees from either HT or from Huobi Points (HBPOINT).

More about it and on how Huobi points work here:

https://huobiglobal.zendesk.com/hc/en-us/articles/360000190591

Let me know if we are missing something.

**Comment by ndubel** [comment]
yes, in my case fee was taken in HT due this fee discount program - https://www.hbg.com/en-us/fee/, please look at screenshot of this transaction.
![2019-10-14_11h15_22](https://user-images.githubusercontent.com/38309641/66737175-ec065b00-ee73-11e9-9e6e-6e1c35691908.png)

**Comment by kroitor** [comment]
@ndubel ok, thx! We will add proper fee currency handling to the fee parsing section there.

**Comment by ndubel** [comment]
https://huobiapi.github.io/docs/spot/v1/en/#get-the-match-result-of-an-order

> fee-deduct-currency: if blank, the transaction fee is based on original currency; if showing value as "ht", the transaction fee is deducted by HT; if showing value as "hbpoint", the transaction fee is deducted by HB point.

So there are two options if we use fee deduct currency
