### ISSUE TITLE
Bitfinex Nonce too small

### ISSUE THREAD

**Issue by NescienceSoftware** [ccxt/ccxt#5972]
This is a known issue with the V1 bitfinex API, you need to set the nonce to an absurdly high number or you just get a "nonce too small" error upon client authorization. 

The known fix with the bitfinex RESTAPI's is to just set the nonce to a value over 100 million,
However I tried to do a few of my own workarounds with the bitfinex v1 script in ccxt and had no luck.

That said, the bitfinex V2 API is not fully supported and currently you cannot place orders, so hopefully someone can help before too long, any assistance is appreciated.

**Comment by kroitor** [comment]
> This is a known issue with the V1 bitfinex API, you need to set the nonce to an absurdly high number or you just get a "nonce too small" error upon client authorization.

Sounds like you've been using the API key with some other software previously, and reusing the same key again. This is not really an issue with the Bitfinex API, it is an issue with the software you've been using that key with. That software will screw your nonce too high, and then you can't use other software with lower nonces and with that same key (will get an error from bitfinex). You should be able to verify that by creating a fresh new API key and trying it with CCXT (which will use a nonce in milliseconds and will not screw it). Can you confirm?

- https://github.com/ccxt/ccxt/wiki/Manual#authentication
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-the-nonce

**Comment by NescienceSoftware** [comment]
Much appreciated, sorry for the duplicate

**Comment by kroitor** [comment]
@NescienceSoftware no worries, can we consider this issue resolved? )
