### ISSUE TITLE
[tidex] ticker timestamps look wrong

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#5973]
{
  "low": 0,
  "high": 0,
  "isOk": false,
  "last": 0,
  "close": 0,
  "symbol": "GNT/WAVES",
  "average": 0,
  "datetime": "2042-07-14T01:04:00.000Z",
  "problems": {
    "GNT": "inactive",
    "GNT/WAVES": "inactive"
  },
  "timestamp": 2288912640000,
  "baseVolume": 0,
  "quoteVolume": 0
}

**Comment by kroitor** [comment]
@npomfret the timestamp is wrong indeed, however, this is what tidex itself serves for that market... We could probably add a workaround to set timestamp to `undefined` for `inactive` markets, what do you think?
