### ISSUE TITLE
Milliseconds timestamps truncated on Raspbian / 32-bit systems in PHP

### ISSUE THREAD

**Issue by F22Raptor775** [ccxt/ccxt#5978]
- OS: Raspbian
- Programming Language version: PHP 7.2
- CCXT version: 1.18.1262
- Exchange: Binance
- Method: fetch_my_trades / fetchClosedOrders

Hi all, let me start by telling you, you guys do a terrific job and I love working with your library. Unfortunately I am facing an issue when trying to implement my second exchange - binance. When running fetch_my_trades (or any historical request) and sending the "since" portion, I get weird or no output:

`$since = $binance->milliseconds () - 86400000;
echo round($since);
var_dump($binance->fetch_my_trades("IOTA/BTC",$since));`

Output:

> 1570994909467array(0) { }

means no trades since 24h, which is wrong.

When cutting the millisecondspart (which is supposed to be wrong, I know), I get at least some output, however it is weird:

`$since = $binance->seconds () - 86400;
echo round($since);
var_dump($binance->fetch_my_trades("IOTA/BTC",$since));`

> 1570995056array(165) { [0]=> array(13) { ["info"]=> array(13) { ["symbol"]=> string(7) "IOTABTC" ["id"]=> int(19699359) ["orderId"]=> int(122191566) ["orderListId"]=> int(-1) ["price"]=> string(10) "0.00002886" ["qty"]=> string(11) "79.00000000" ["quoteQty"]=> string(10) "0.00227994" ["commission"]=> string(10) "0.07900000" ["commissionAsset"]=> string(4) "IOTA" ["time"]=> float(1569235787047) ["isBuyer"]=> bool(true) ["isMaker"]=> bool(false) ["isBestMatch"]=> bool(true) } ["timestamp"]=> int(1572724007) ["datetime"]=> string(24) "1970-01-19T04:52:04.007Z" ["symbol"]=> string(8) "IOTA/BTC" ["id"]=> string(8) "19699359" ["order"]=> string(9) "122191566" ["type"]=> NULL ["takerOrMaker"]=> string(5) "taker" ["side"]=> string(3) "buy" ["price"]=> float(2.886E-5) ["amount"]=> float(79) ["cost"]=> float(0.00227994) ["fee"]=> array(2) { ["cost"]=> float(0.079) ["currency"]=> string(4) "IOTA" } 
*** snip ***

I assume the timestamp etc (see the year 1970) got mutilated because of the missing *1000.

I activated the verbose mode and apparently received some data, which somehow does not get validated properly:

`***snip***
Request: Array ( [0] => GET [1] => https://api.binance.com/api/v3/myTrades?timestamp=1571081628533&recvWindow=5000&symbol=IOTABTC&signature=4e9e32f11c9a8cab2320d22e8161017ad5d969eaedbf4f00c827d6f65736aa69 [2] => Array ( [0] => X-MBX-APIKEY: e3F34vqKGU5sxL1rrM7DDDmESe7r2ODAd3v4wjJF0EdJdnB1bJxwDdvQlqR4QjXI ) [3] => ) Response: Array ( [0] => GET [1] => https://api.binance.com/api/v3/myTrades?timestamp=1571081628533&recvWindow=5000&symbol=IOTABTC&signature=4e9e32f11c9a8cab2320d22e8161017ad5d969eaedbf4f00c827d6f65736aa69 [2] => 200 [3] => [4] => Array ( [content-type] => Array ( [0] => application/json;charset=utf-8 ) [date] => Array ( [0] => Mon, 14 Oct 2019 19:33:48 GMT ) [server] => Array ( [0] => nginx ) [x-mbx-uuid] => Array ( [0] => f5a41db7-ef75-4eae-83ab-e0ea70c0a9cc ) [x-mbx-used-weight] => Array ( [0] => 107 ) [x-mbx-used-weight-1m] => Array ( [0] => 107 ) [content-encoding] => Array ( [0] => gzip ) [strict-transport-security] => Array ( [0] => max-age=31536000; includeSubdomains ) [x-frame-options] => Array ( [0] => SAMEORIGIN ) [x-xss-protection] => Array ( [0] => 1; mode=block ) [x-content-type-options] => Array ( [0] => nosniff ) [content-security-policy] => Array ( [0] => default-src 'self' ) [x-content-security-policy] => Array ( [0] => default-src 'self' ) [x-webkit-csp] => Array ( [0] => default-src 'self' ) [cache-control] => Array ( [0] => no-cache, no-store, must-revalidate ) [pragma] => Array ( [0] => no-cache ) [expires] => Array ( [0] => 0 ) [x-cache] => Array ( [0] => Miss from cloudfront ) ***snip***
sMaker":true,"isBestMatch":true},{"symbol":"IOTABTC","id":19880950,"orderId":124226798,"orderListId":-1,"price":"0.00003367","qty":"40.00000000","quoteQty":"0.00134680","commission":"0.00000135","commissionAsset":"BTC","time":1571079626047,"isBuyer":false,"isMaker":true,"isBestMatch":true},{"symbol":"IOTABTC","id":19880954,"orderId":124226851,"orderListId":-1,"price":"0.00003358","qty":"41.00000000","quoteQty":"0.00137678","commission":"0.04100000","commissionAsset":"IOTA","time":1571079692518,"isBuyer":true,"isMaker":true,"isBestMatch":true},{"symbol":"IOTABTC","id":19880958,"orderId":124226962,"orderListId":-1,"price":"0.00003359","qty":"25.00000000","quoteQty":"0.00083975","commission":"0.02500000","commissionAsset":"IOTA","time":1571079938789,"isBuyer":true,"isMaker":true,"isBestMatch":true}] )
***snip***`

The last one is translated to 14.10.2019 - 21:05:38 (35 minutes ago). I am sure I am missing something but I can't get my head around it and I am really thankful for your assistance.

**Comment by kroitor** [comment]
@F22Raptor775 hey) Unfortunately, the `since` argument was not supported for Binance `fetchMyTrades` in the previous versions of CCXT. We've added it in the most recent version 1.18.1263+ and the new build will arrive in 15 minutes. Let us know if you have any difficulties with it after upgrading! Cheers!

**Comment by F22Raptor775** [comment]
hi and thanks for all the hard work and prompt response! i've updated to the most recent version, but either something went wrong or the behaviour is still the same. this is true for fetch_my_trades and fetch_closed_orders. again with the code above i receive no output directly, however verbose is very talkative. I dont wanna flood this thread with all the verbose output (shall I?). could you let me know what data I can provide?

**Comment by kroitor** [comment]
@F22Raptor775  

> this is true for fetch_my_trades and fetch_closed_orders. again with the code above i receive no output directly, however verbose is very talkative. I dont wanna flood this thread with all the verbose output (shall I?). could you let me know what data I can provide?

We still need a full verbose request/response, however, I'd recommend to enable the verbose output only after loading the markets, to reduce the size of it:

```PHP

// instantiate $exchange here


// let's verify that you have the most recent version of it
echo "CCXT v." . \ccxt\Exchange::VERSION . "\n";

$exchange->load_markets();
$exchange->verbose = true;
$exchange->fetch_my_trades(...
```

↑ When pasting the verbose request/response, please use code formatting for readability – that way you won't flood anything ) 

Surround your copypasted snippet with triple backtiks, as described here:

Follow the guides from here:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://guides.github.com/features/mastering-markdown/

Will get this resolved.

**Comment by F22Raptor775** [comment]
thanks for guiding me like this, although I am very interested, I am still new to this and highly appreciate your help with me, a newb :-)

my code:

`$binance  = new \ccxt\binance (array (
	'apiKey' => 'ABC',
	'secret' => 'XYZ',
	//'verbose' => true
));	
$binance->load_markets();
echo "CCXT v." . \ccxt\Exchange::VERSION . "\n";
$since = $binance->milliseconds () - 86400000;
echo round($since). "\n";
$binance->verbose = true;
var_dump($binance->fetch_my_trades("IOTA/BTC",$since,5));`

the output
´´´ CCXT v.1.18.1264 1571033106241 Request: Array ( [0] => GET [1] => https://api.binance.com/api/v3/myTrades?timestamp=1571119506241&recvWindow=5000&symbol=IOTABTC&startTime=1571033106241&limit=5&signature=a28fcc8e7f30622b6a6baa54100581aec657b892b07d8a7183feabbc11975165 [2] => Array ( [0] => X-MBX-APIKEY: XYZ ) [3] => ) Response: Array ( [0] => GET [1] => https://api.binance.com/api/v3/myTrades?timestamp=1571119506241&recvWindow=5000&symbol=IOTABTC&startTime=1571033106241&limit=5&signature=a28fcc8e7f30622b6a6baa54100581aec657b892b07d8a7183feabbc11975165 [2] => 200 [3] => [4] => Array ( [content-type] => Array ( [0] => application/json;charset=utf-8 ) [date] => Array ( [0] => Tue, 15 Oct 2019 06:05:06 GMT ) [server] => Array ( [0] => nginx ) [x-mbx-uuid] => Array ( [0] => 1dd1875f-1fa4-4c73-9aef-38f3646335fb ) [x-mbx-used-weight] => Array ( [0] => 28 ) [x-mbx-used-weight-1m] => Array ( [0] => 28 ) [content-encoding] => Array ( [0] => gzip ) [strict-transport-security] => Array ( [0] => max-age=31536000; includeSubdomains ) [x-frame-options] => Array ( [0] => SAMEORIGIN ) [x-xss-protection] => Array ( [0] => 1; mode=block ) [x-content-type-options] => Array ( [0] => nosniff ) [content-security-policy] => Array ( [0] => default-src 'self' ) [x-content-security-policy] => Array ( [0] => default-src 'self' ) [x-webkit-csp] => Array ( [0] => default-src 'self' ) [cache-control] => Array ( [0] => no-cache, no-store, must-revalidate ) [pragma] => Array ( [0] => no-cache ) [expires] => Array ( [0] => 0 ) [x-cache] => Array ( [0] => Miss from cloudfront ) [via] => Array ( [0] => 1.1 c7f7b4cf7fd5efe64bac95586db3f62b.cloudfront.net (CloudFront) ) [x-amz-cf-pop] => Array ( [0] => FRA2-C1 ) [x-amz-cf-id] => Array ( [0] => BosnLjj_X1sg7lFHfDo_G-8ybaNNUmQEm2h_YxLQElTXnKg_JZmJuQ== ) ) [5] => [{"symbol":"IOTABTC","id":19880450,"orderId":124218385,"orderListId":-1,"price":"0.00003355","qty":"31.00000000","quoteQty":"0.00104005","commission":"0.03100000","commissionAsset":"IOTA","time":1571074561890,"isBuyer":true,"isMaker":true,"isBestMatch":true},{"symbol":"IOTABTC","id":19880452,"orderId":124218433,"orderListId":-1,"price":"0.00003352","qty":"32.00000000","quoteQty":"0.00107264","commission":"0.03200000","commissionAsset":"IOTA","time":1571074567343,"isBuyer":true,"isMaker":true,"isBestMatch":true},{"symbol":"IOTABTC","id":19880454,"orderId":124218457,"orderListId":-1,"price":"0.00003349","qty":"31.00000000","quoteQty":"0.00103819","commission":"0.00000104","commissionAsset":"BTC","time":1571074568752,"isBuyer":false,"isMaker":false,"isBestMatch":true},{"symbol":"IOTABTC","id":19880457,"orderId":124218501,"orderListId":-1,"price":"0.00003349","qty":"32.00000000","quoteQty":"0.00107168","commission":"0.00000107","commissionAsset":"BTC","time":1571074579447,"isBuyer":false,"isMaker":false,"isBestMatch":true},{"symbol":"IOTABTC","id":19880461,"orderId":124218564,"orderListId":-1,"price":"0.00003352","qty":"32.00000000","quoteQty":"0.00107264","commission":"0.03200000","commissionAsset":"IOTA","time":1571074594352,"isBuyer":true,"isMaker":true,"isBestMatch":true}] ) array(0) { }´´´

again, thank you very much for your help!

**Comment by kroitor** [comment]
> I am still new to this and highly appreciate your help with me, a newb :-)

My best advice to all newcomers – start reading and paying attention to every single word literally, don't skip anything, single backtiks don't really work for multiple lines, triple backtiks do the job well, and this is mentioned in the contributing doc on how to report an issue – you should also read all links very carefully – that way you will get help as fast as possible ) No offense, it's just a friendly advice ) I know it can be hard at first, but you'll climb the learning curve much faster if you are pedantic in all the details )

---------------------------------------------------

&#096;
bad php code
&#096;

&#096;
bad verbose output
&#096;

---------------------------------------------------

&#096;&#096;&#096;PHP
// good php code
&#096;&#096;&#096;

&#096;&#096;&#096;
good verbose output
&#096;&#096;&#096;

---------------------------------------------------

Now, back to the issue – in your output we see that the version is updated properly and the `since` = `startTime` is getting correctly sent to the exchange, along with your `limit` of 5 trades, and the exchange replies with 5 trades, after the requested `since` timestamp, 2019-10-14T06:05:06.241Z (since one day ago), just as we expect it to. However, as far as I understand, you're having issues with printing the output.

So, in order to verify that `fetchMyTrades` returns 5 trades to you, I suggest trying this snippet:

```PHP
$binance  = new \ccxt\binance (array (
	'apiKey' => 'ABC',
	'secret' => 'XYZ',
));	

$binance->load_markets();
echo "CCXT v." . \ccxt\Exchange::VERSION . "\n";

$since = $binance->milliseconds () - 86400000;

// no need for verbose flag here anymore

$trades = $binance->fetch_my_trades("IOTA/BTC",$since,5);

// print out results

echo "-------------------------------------------------\n";
echo "Fetched " . count($trades) . " trades\n";
echo "-------------------------------------------------\n";
echo json_encode ($trades) . "\n";
if (count($trades) > 0) {
    echo "-------------------------------------------------\n";
    echo "First trade:\n"
    print_r ($trades[0]);
    echo "\n";
}
```

↑ What does it say?

**Comment by F22Raptor775** [comment]
thank you so much for the very good advice! i will try to live by it!

regarding your code, it says missing ";" in line 51. :-P jk, happy to see we all make the same mistakes ;-)

here is the output 
``` ------------------------------------------------- Fetched 0 trades ```

my rookie asumption is that there is an issue with the internal caching? interestingly I am able to fetch trades via hardcoding:

``` $trades = $binance->fetch_my_trades("IOTA/BTC",1,5);```

-->

``` ------------------------------------------------- Fetched 5 trades ------------------------------------------------- First trade: Array ( [info] => Array ( [symbol] => IOTABTC [id] => 11383110 [orderId] => 44960229 [orderListId] => -1 [price] => 0.00016809 [qty] => 10.00000000 [quoteQty] => 0.00168090 [commission] => 0.00038001 [commissionAsset] => BNB [time] => 1530535649240 [isBuyer] => 1 [isMaker] => [isBestMatch] => 1 ) [timestamp] => 1527291864 [datetime] => 1970-01-18T16:14:51.864Z [symbol] => IOTA/BTC [id] => 11383110 [order] => 44960229 [type] => [takerOrMaker] => taker [side] => buy [price] => 0.00016809 [amount] => 10 [cost] => 0.0016809 [fee] => Array ( [cost] => 0.00038001 [currency] => BNB ) ) ```

**Comment by kroitor** [comment]
> happy to see we all make the same mistakes ;-)

Yeah, pardon for the typos, I'm learning together with you )

> my rookie asumption is that there is an issue with the internal caching?

No, there is no caching whatsoever.

But from your last printout I think I can see the bug already. Binance returns `time` in milliseconds there, but it gets converted to seconds (divided by a thousand) for some reason. And then it cannot pass the $since = yesterday filter, but it can pass the $since = 1 (the beginning of time). 

I will fix this shortly, and, I believe, this will fix the issue on your side. Will update you here asap.

**Comment by kroitor** [comment]
@F22Raptor775 ok, the cause of your bug is related to Raspbian, I believe. It cannot process integer values in milliseconds, since it's a 32bit system and it requires 64 bits to store the timestamp in milliseconds. Therefore you get an overflow on a 32-bit system and that truncates the parsed timestamps. In order to verify and rule this out – can you please try the same code on a bigger PC?

**Comment by F22Raptor775** [comment]
Wow that feels like a good hint and would also explains why it seems I am the only one running into this. Unfortunately I am currently on travel hence I won't be able to recreate until the weekend. Maybe I can tweak the Raspy and will let you know asap. Once again, I appreciate your insights!

**Comment by F22Raptor775** [comment]
@kroitor : You are a genius! Absolutely correct. On my bigger PC the result was as expected and I could fetch my trades successfully. Unfortunately it is not easy to install a new system to the raspberry, but I will check this out at the weekend. Any chance you see a workaround for 32bit systems overall? I found hints towards using pack() / unpack() or converting to float, which however might result in loss of precision. I don't understand enough of your library to comment on how hard this would be. Of course I would be very grateful, but I also understand that 32bit systems are a very limited use case. :-) Anyways, thank you so much for pointing me into the right direction and teach me a lesson!

**Comment by F22Raptor775** [comment]
@kroitor : fixed it quick and dirty... binance.php. line 561 was changed to 

```        $timestamp = $this->safe_float_2($trade, 'T', 'time');  ```

I don't see any imminent dangers, do you?

**Comment by kroitor** [comment]
@F22Raptor775 

> fixed it quick and dirty... binance.php. line 561 was changed to

Can you elaborate a bit, please? I don't really see how changing the timestamp from integer to float there can fix the issue without losing the timestamp precision, tbh. I'll spend more time debugging this issue based on your comments.

**Comment by F22Raptor775** [comment]
@kroitor As float can grow higher than integer on 32bit systems and the issue seems with how we work with the data received, we "just" need to make sure we can at least work with the received data. If we would filter with an 32bit overflown / bad integer it gives us the results seen -> weird timestamps which can not be properly filtered. float is by no means the safest and most precise way here, however it gets the job done so far. this does not have to go into official code of course, but it is a dirty workaround for everyone who faces my issue until I can reinstall my raspbian :-)

Again thanks for your great work which brought me here!

**Comment by delaji-san** [comment]
For anyone else facing this problem if the code below comes back with 32Bit you'll have an issue. I rolled back and previous versions seem to work. 
`php -r 'echo (PHP_INT_SIZE===8)?"64 bit ":"32 bit ";'`
Could you not set timestamp type through the above conditional?

**Comment by kroitor** [comment]
> Could you not set timestamp type through the above conditional?

In many cases the exchanges require 64 bit integer timestamp as JSON, so the 32-bit limitation is not very easy to workaround.

**Comment by delaji-san** [comment]
If I get time I'll diff what's changed as this was definitely working last year. I'm assuming you haven't upgraded from 32Bit to 64Bit  since March 2019 or is this Binance that's made those changes?

**Comment by kroitor** [comment]
@delaji-san this is hard to tell without debugging, your help is very welcome!

**Comment by delaji-san** [comment]
Found it. :sunglasses: Broke on version **1.21.57**. From the diffs it looks like a function in _Exchange.php_ is the culprit. Below is the good version from **1.21.56**:
```PHP
    public function milliseconds() {
        list($msec, $sec) = explode(' ', microtime());
        return $sec . substr($msec, 2, 3);
    }
```
Difference in the new versions was the return is type cast to int. Pulled latest version changed just this function and it's all working again.
