### ISSUE TITLE
Any updates / progress about supporting WebSocket ?

### ISSUE THREAD

**Issue by frodoe7** [ccxt/ccxt#5981]
My application make too many requests within a single minute
in a time , the requests blocks with this error code : 

> You exceeded the limit , use WebSocket for performance.

now , I need to use WebSocket in my working project , instead of the current implementation

After searching inside CCXT manual , I could not find any tutorials for WebSocket

is there any progress / updates ? , and I hope so

or I have to re-implement all this work again from scratch
by removing CCXT and implement each exchange separately

I hope to not re-implement all the work again , as the project is very big , this will be a big delay

**Comment by kroitor** [comment]
Yes, there's many news, and it's too hard to re-type all of them, please, follow and read from here: https://github.com/ccxt/ccxt/issues/56#issuecomment-507290536
