### ISSUE TITLE
Idex API-Key integration 

### ISSUE THREAD

**Issue by mustapha1509** [ccxt/ccxt#5982]
Hello CCXT Community 

    OS: Windows / Ubuntu
    Programming Language version: Javascript
    CCXT version: 1.18.1270 / master branch
    Exchange: Idex
    Method: createOrder/ cancelOrder

I developed a trading bot on idex, everything works well on idex's public API. but on private API I do not find how to integrate my API-Key in the headers of the post request for createOrder () for example.
![Capture Ecran](https://www.zupimages.net/up/19/42/ha55.jpg)
Can you help me please.

**Comment by frosty00** [comment]
Hi @mustapha1509, thanks for using ccxt!

You need to specify your `walletAddress`, `privateKey`, and `apiKey` for `createOrder` to work.

```
let idex = new ccxt.idex ({'walletAddress': 'your ethereum address', 'privateKey': 'your ethereum private key', 'apiKey': 'your idex apikey'})
```

Please let us know if you still have any issues.

**Comment by mustapha1509** [comment]
I did as you mentioned in your answer, but nothing changed, always the same error

**Comment by kroitor** [comment]
@mustapha1509 this is explained in the Manual here:

- https://github.com/ccxt/ccxt/wiki/Manual#authentication
- https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin

Let us know if the above does not help.

**Comment by mustapha1509** [comment]
Thank you @kroitor, now it's working fine with proxy

**Comment by kroitor** [comment]
@mustapha1509 thx for reporting back, really appreciate that! Let us know if anything! Cheers!
