### ISSUE TITLE
PHP kornrunner\Solidity not found

### ISSUE THREAD

**Issue by mustapha1509** [ccxt/ccxt#5988]
I have made this issue #5986
And when i updated the CCXT version to this commit  8e47030, i have this error
`Class 'kornrunner\Solidity' not found`

OS: Windows/linux
Programming Language version: PHP
CCXT version: 1.18.1283
Exchange: Idex
Method: create_order

**Comment by kroitor** [comment]
@mustapha1509 are you sure that you have the entire repository up to date (not just a single file or a single folder) ? Can you confirm? 

Also, what's your version of PHP ?

**Comment by mustapha1509** [comment]
Yes, I uninstalled and reinstalled it with composer.
PHP version: 7.2.19
I used it with a namespace in laravel framework. and when i use fetch_balance, for example, it works fine
`
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use ccxt\ccxt;
use ccxt\idex;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //$this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $idex = new idex(array (
            'walletAddress' => 'xxxx',
            'privateKey' => 'xxxx',
            'apiKey' => 'xxx',
            'timeout' => 30000,
            'enableRateLimit' => true,
        ));
        $idex->create_order('PCL/ETH','limit', 'buy', 40000, 0.000025, '');
    }
}
`

**Comment by kroitor** [comment]
@mustapha1509 thx for reporting back, we have reproduced it on our side and will fix this asap.

**Comment by kroitor** [comment]
@mustapha1509 can you plz retry it again with the most recent version 1.12.1289 (or higher) and report back if this issue is still present on your side?

**Comment by kroitor** [comment]
@mustapha1509 looks like the uploaded fix [breaks the other functionality in PHP](#5991), so I had to revert it. Will debug and will upload another fix, hopefully soon.

**Comment by mustapha1509** [comment]
Thank you, Now it is good. It works with laravel perfectly.
