### ISSUE TITLE
got an error when using indodax create_order method in php

### ISSUE THREAD

**Issue by rienaldis** [ccxt/ccxt#5991]
- OS: Windows 10 64bit
- Programming Language version: PHP
- CCXT version: 1.18.1290
- Exchange: Indodax
- Method: create_order

i dont understand about this error
is my parameter input is wrong or is a bug?
can you help me?
sorry for my bad english

![image](https://user-images.githubusercontent.com/56689912/67022424-6b718400-f12b-11e9-97aa-f7c029b791dd.png)

**Comment by kroitor** [comment]
@rienaldis what's you version of PHP ?

**Comment by kroitor** [comment]
Also, from your code it looks like you're confusing market ids with symbols, as explained in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

Let us know if you still have the same issue with 1.18.1291.

**Comment by rienaldis** [comment]
okay ill try ccxt newest version first

**Comment by rienaldis** [comment]
hello, can you help me?
whats mean with this error?

![image](https://user-images.githubusercontent.com/56689912/67162687-9577b000-f390-11e9-80d1-fe52e340709d.png)
