### ISSUE TITLE
Bitstamp Close data Incorrect

### ISSUE THREAD

**Issue by jzay** [ccxt/ccxt#5994]
I am using CCXT to return the recent hour of historical trading data and the close data is sometimes different than other sources. I've checked against Tradingview and Cryptowatch and have even contacted tradingview support to confirm their data is correct. Here is an example the close is showing as the high price in the data I pulled from CCXT.

<img width="1009" alt="Screen Shot 2019-10-18 at 9 46 54 AM" src="https://user-images.githubusercontent.com/16840393/67099599-43fed380-f18c-11e9-82e7-880a95a54c31.png">

**Comment by kroitor** [comment]
@jzay thx for reporting, we will look into it asap!

**Comment by kroitor** [comment]
@jzay what's your version of CCXT btw?

**Comment by kroitor** [comment]
Unfortunately, the images posted above don't really help to determine your issue. What would really help to quickly resolve it, is your code to reproduce it and your verbose request/response, as described here:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

We don't change the data when it comes from the exchange, so what you see is what you get from the exchange directly, and you can verify that easily in verbose mode.

If you look at the row of numbers highlighted on the image you posted, there's four values:

- 8042.3
- 8050.18 (must be the High price and it cannot be the Close price, since High must be >= Close)
- 8040.59 (must be the Low price and it cannot be anything else, since it's the lowest value)
- 8044.35

Let us know if the above does not help.

**Comment by jzay** [comment]
@kroitor I don't think it has anything to do with my particular setup of CCXT. The data is simply different that other source such as TradingView and Cryptowatch. The Bitstamp data is only fetch able up to one hour historically so the particular issue can only be fetched from CCXT for an hour after it occured. I can find another disrepancy today

**Comment by kroitor** [comment]
@jzay ok, let me know if you find one, however, it would be great if you could comment on this:

```
8042.3
8050.18 (must be the High price and it cannot be the Close price, since High must be >= Close)
8040.59 (must be the Low price and it cannot be anything else, since it's the lowest value)
8044.35
```

**Comment by jzay** [comment]
You are correct that is the returned Open, High, Low, Close data in that order from CCXT but in the corresponding minute candle on Tradingview the High & Close values are showing up as the same.

**Comment by kroitor** [comment]
@jzay 

> You are correct that is the returned Open, High, Low, Close data in that order from CCXT but in the corresponding minute candle on Tradingview the High & Close values are showing up as the same.

In that case you should take the data you received from Bitstamp using CCXT within that request (you can get it in verbose mode) and ask TradingView why their "close" differs from what Bitstamp actually served for that period.

**Comment by jzay** [comment]
Tradinview told me the exact same thing you just said and Cryptowatch and other websites backup the Tradingview data. I can pull another screenshot from there one sec

**Comment by kroitor** [comment]
> I can pull another screenshot from there one sec

Please, don't ) Those screenshots don't help. Also, we can't really do anything with those screenshots. We need plaintext verbose output + your code to reproduce the issue.

**Comment by jzay** [comment]
Here is the data return by CCXT in a CSV. Waiting on the code that returned this data.
<img width="1440" alt="Screen Shot 2019-10-18 at 9 40 55 AM-2" src="https://user-images.githubusercontent.com/16840393/67165757-f1254780-f356-11e9-9587-0be08ed23ef8.png">
![Screen Shot 2019-10-20 at 4 30 48 PM](https://user-images.githubusercontent.com/16840393/67165764-fc787300-f356-11e9-86c0-8b8e07ccb0a9.png)


[downloaded_last_hour_bitstampdata.csv.zip](https://github.com/ccxt/ccxt/files/3748308/downloaded_last_hour_bitstampdata.csv.zip)

**Comment by kroitor** [comment]
@jzay which language do you use?

**Comment by jzay** [comment]
This was in Python will provide the code shortly..

**Comment by kroitor** [comment]
@jzay thx, plz make it a short snippet of 10-20 lines, use markdown for readability: https://guides.github.com/features/mastering-markdown/

**Comment by kroitor** [comment]
@jzay actually, even without the code itself, check out this explanation on how OHLCV emulation works: https://github.com/ccxt/ccxt/issues/3178. Bitstamp has ['fetchOHLCV'] === 'emulated' (from trades), so that could explain the discrepancy.
