### ISSUE TITLE
Bitfinex2 fetching old OHLCV 1m-history

### ISSUE THREAD

**Issue by werewere** [ccxt/ccxt#600]
Bitfinex2 is returning a wrong Timestamp, always in the recent time, not the one specified. For instance, if we ask for 100 candles from "2016-08-17 00:00:00" using this call:

`    data = bitfinex2.fetch_ohlcv("ETH/USD", "1m", 1471392000000, 50)`

It returns:

```
[[1510749300000, 331.24, 331.48, 331.01, 331.2, 89.61641044],
[1510749240000, 330.98, 331.46, 330.6, 331.46, 137.87685401], 
[1510749180000, 330.91, 331, 330.69, 330.95, 97.53257886], 
[1510749120000, 331, 331, 330.91, 330.91, 92.99920519],
etc
```

Also the prices are wrong, they should be around 11$, and it is returning the current prices. It seems that always returns recent data, not the time specified.

**Comment by kroitor** [comment]
Hello, @werewere ! 

Did you try this:

https://github.com/ccxt/ccxt/blob/master/examples/py/fetch-bitfinex-ohlcv-history.py

?

**Comment by werewere** [comment]
Something seems wrong with Bitfinex. I just copied+pasted the code here https://github.com/ccxt/ccxt/blob/master/examples/py/fetch-bitfinex-ohlcv-history.py 
and it is using a wrong timestamp. Look at the result, the string is correct, but the unix time that the script is taking as "from" is today.

```
$ python fetch_bitfinex.py 
(1510754590107, 'Fetching candles starting from', '2017-01-01T00:00:00.000Z')
(1510754602890, 'Fetched', 120, 'candles')
('First candle epoch', 1510754400000, '2017-11-15T14:00:00.000Z')
('Last candle epoch', 1510718700000, '2017-11-15T04:05:00.000Z')
(1510754602890, 'Fetching candles starting from', '2017-01-01T02:00:00.000Z')
(1510754613934, 'Fetched', 120, 'candles')
('First candle epoch', 1510754400000, '2017-11-15T14:00:00.000Z')
('Last candle epoch', 1510718700000, '2017-11-15T04:05:00.000Z')
etc.
```

Also, I think it is not because of my installation, because all the other exchanges that I've tested (gdax, poloniex, kraken and bittrex) are working normally. For instance, if in gdax I run exactly the same query, it works perfectly:

data = gdax.fetch_ohlcv("ETH/USD", "1m", 1471392000000, 50)

Result:
`
[[1471395540000, 11.18, 11.18, 11.18, 11.18, 3.12041], [1471395480000, 11.18, 11.18, 11.18, 11.18, 10], [1471395120000, 11.18, 11.18, 11.18, 11.18, 50], [1471394760000, 11.18, 11.18, 11.18, 11.18, 13.18018], [1471394700000, 11.18, 11.18, 11.18, 11.18, 0.43525], [1471394340000, 11.18, 11.18, 11.18, 11.18, 0.0108], [1471394220000, 11.18, 11.18, 11.18, 11.18, 3.38202], [1471394100000, 11.18, 11.18, 11.18, 11.18, 22.3036], `

**Comment by kroitor** [comment]
@werewere can you post your current code and verbose output of it?

**Comment by kroitor** [comment]
Nothing wrong with Bitfinex, actually... Did you read this: https://github.com/ccxt/ccxt/pull/218#issuecomment-332542559 ?

```
mbp:ccxt igorkroitor$ python examples/py/fetch-bitfinex-ohlcv-history.py 
(1510756871195, 'Fetching candles starting from', '2017-01-01T00:00:00.000Z')
``

We asked **5m timeframes** from Bitfinex, and they will not serve the full history (explained in the linked comment)

```
(1510756881523, 'Fetched', 120, 'candles')
('First candle epoch', 1510756800000, '2017-11-15T14:40:00.000Z')
('Last candle epoch', 1510721100000, '2017-11-15T04:45:00.000Z')
```

They returned 120 candles (120 is their maximum). The history starts at 04:45 and ends at 14:40, that is 120 candles of 5m-history.

If we fetch **1d timeframe** then it can go further back in history:

```
mbp:ccxt igorkroitor$ python examples/py/fetch-bitfinex-ohlcv-history.py 
(1510756942018, 'Fetching candles starting from', '2017-01-01T00:00:00.000Z')
(1510756952337, 'Fetched', 120, 'candles')
('First candle epoch', 1510704000000, '2017-11-15T00:00:00.000Z')
('Last candle epoch', 1500422400000, '2017-07-19T00:00:00.000Z')
```

We asked candles starting from 2017-01-01, but they can only return last 120 candles (120 days for this timeframe).

So, it's obvious, that whatever timeframe you choose, they will not return more than 120 candles of history for it.

Does this help?

**Comment by kroitor** [comment]
To clarify: whatever `from` you choose, they will limit it to a range within last 120 periods.

**Comment by werewere** [comment]
I see :( OK, understood. Thanks for your help as always, you can close the ticket :)

**Comment by kroitor** [comment]
@werewere I guess, 120 is their max limit. Sorry, but we can't really workaround it, unless you collect their 1m timeframe continuously (poll and save to db in regular fashion).
