### ISSUE TITLE
Include Bybit - CCXT  Fork

### ISSUE THREAD

**Issue by Gennttii** [ccxt/ccxt#6003]
Hi, 
I was looking about Bybit exchange here but I saw u didn't include it, but then I saw that they have forked the CCXT library and and added their API there. Can you include that fork to the original CCXT library?

This is the link  [https://github.com/bybit-exchange/ccxt](url)

Regards

**Comment by kroitor** [comment]
Hi! 

> Can you include that fork to the original CCXT library?

Yes, see this PR: #5985. Dupe: #5070

**Comment by kroitor** [comment]
Bybit is now available in CCXT 1.24.4+ https://github.com/ccxt/ccxt/issues/6612
