### ISSUE TITLE
I got an auth error when using Indodax api for trade

### ISSUE THREAD

**Issue by rienaldis** [ccxt/ccxt#6007]
- OS: Windows 10 64bit
- Programming Language version: PHP
- CCXT version: 1.18.1305
- Exchange: Indodax
- Method: create_order

i tried to trade using api in indodax, but this error showing up
can you help me?
sorry for my bad english
![image](https://user-images.githubusercontent.com/56689912/67162763-98bf6b80-f391-11e9-90cb-99a628fb07a2.png)

**Comment by kroitor** [comment]
@rienaldis are you sure that you have the above with the most recent version of CCXT? Have you tried reinstalling it?

**Comment by rienaldis** [comment]
yes im sure. i can use fetch_balance and work very well. but when i try to trade, the error is showing off.
am i wrong when inputing parameter or its a bug?
please help me

**Comment by kroitor** [comment]
@rienaldis 

- does it happen with version 1.18.1308?
- are you using the rate-limiter as [required in the Manual](https://github.com/ccxt/ccxt/wiki/Manual#rate-limit)?

**Comment by rienaldis** [comment]
- im still using 1.18.1308 version, ill try most recent version very soon

- yes i am using rate limiter 
![image](https://user-images.githubusercontent.com/56689912/67201177-e5f21a80-f42f-11e9-8692-6dca8c60a377.png)

**Comment by rienaldis** [comment]
i already try the most recent version, but same problem
![image](https://user-images.githubusercontent.com/56689912/67201377-5ac55480-f430-11e9-8edb-aa7d99f433a0.png)

**Comment by kroitor** [comment]
@rienaldis what's your version of PHP?

**Comment by kroitor** [comment]
@rienaldis also, can you paste the code you use to reproduce it? How do you include the lib into your project? Do you use `composer` with autoload?

**Comment by rienaldis** [comment]
im using PHP Version 7.2.14

and this my code for trade, im save may api secret and api key in database
`

$key = mysqli_query($kon, 'Select * from api where admin_id = "'.$id.'" and market = "indodax" order by api_id Desc"
            ');
        $key = mysqli_fetch_assoc($key);
        $api_key    = $key['api_key'];
        $secret_key = $key['secret_key'];
        $exchange = new indodax (array (
                      'apiKey' => "$api_key",
                      'secret' => "$secret_key",
                      'enableRateLimit' => true,
                      ));
        $symbol = 'BTC/IDR'; // bitcoin contract according to bitmex futures coding
        $typee = 'limit';
        $side = 'buy'; // or 'buy'
        $amount = 50000; //50000 idr 
        $price = $prices; // or None
        // extra params and overrides if necessary
        $params = array (
            
        );

 $exchange->create_order ($symbol, $typee, $side, $amount, $price, $params);


`

**Comment by rienaldis** [comment]
i read the indodax api documentation and the pair symbol is btc_idr, i try BTC/IDR like in example file.
but when i try btc_idr it get error 

> Fatal error: Uncaught Error: Class 'BadSymbol' not found in C:\xampp\htdocs\rzbcrypto\pages\user\exchange\Exchange.php:2322 Stack trace: #0 C:\xampp\htdocs\rzbcrypto\pages\user\exchange\indodax.php(416): Exchange->market('btc_idr') #1 C:\xampp\htdocs\rzbcrypto\pages\user\exchange\indodax_exchange.php(174): indodax->create_order('btc_idr', 'limit', 'buy', '50000', '117003000', Array) #2 

this is from indodax dcoumentation
![image](https://user-images.githubusercontent.com/56689912/67210868-03c97a80-f444-11e9-9c10-a7d2a559e10e.png)

i hope it can help

**Comment by kroitor** [comment]
@rienaldis actually, your code also has some strange errors, as if you have not read the Manual on the differences between `amount`, `price` and `cost` (cost = price * amount). For some reason, you're specifying the amount = 50000 which means 50000 BTC (not IDR, as in your comments). The `amount` is always in base currency, and the `price` is always in quote currency, as explained in the Manual here:

- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders 
- https://github.com/ccxt/ccxt/wiki/Manual#consistency-of-base-and-quote-currencies

```
base currency ↓
             BTC / IDR
                    ↑ quote currency
```

**Comment by rienaldis** [comment]
ohh i see. i try your explanation and it works. i thinks when i buy, i use idr to buy btc. thats my mistake
thanks a lot man. this lib is so helping. Cheers!
