### ISSUE TITLE
Unified Margin Balances

### ISSUE THREAD

**Issue by PolybitSol** [ccxt/ccxt#601]
Hey,

Glad to see this project is still going on strong, I just had some queries about the unified balances. Exchanges such as Bitfinex and Poloniex both divide their users' balances into seperate accounts - for example trading, lending & margin on Poloniex. Funds are required in specific accounts depending on the type of trade being made. 

Is it planned to incorporate this in to the unified balance? I'm unaware how many of the supported exchanges on CCXT utilise this kind of setup for funds, but a default 'exchange' or 'trading' account index could be used for those who only have a single balance account. 

Thanks!

**Comment by kroitor** [comment]
Hi, @PolybitSol 

See the answers here:

- [How i can fetch Poloniex margin balance and made margin order?](https://github.com/ccxt/ccxt/issues/318) #318
- [is it possible to create "margin sell" order with bitfinex?](https://github.com/ccxt/ccxt/issues/157) #157

**Comment by kroitor** [comment]
In short, we don't have margin trading on our immediate plans, but we may unify it in future as well. For now you will have to use custom methods (available from ccxt) for margin trading like it is shown in the above examples. Let me know if does answer your question. Thx!

**Comment by PolybitSol** [comment]
Hey, 

Thanks for the quick reply. I am aware the POLO & BFX endpoints have been implemented, I was just inquiring into the output of the unified balance, not so much margin trading. For example, the current output looks something like this:

`BCH: { free: null, used: 0, total: 0.00432805 },`
`BTC: { free: null, used: 0, total: 0.54191671 },`
`BTG: { free: null, used: 0, total: 0.00001671 },`
`DASH: { free: null, used: 0, total: 0.00106497 },`
`ETC: { free: null, used: 0, total: 0.00091715 },`

What I was after was a unified output that takes into account the exchange's accounts, as seen in Poloniex's `returnAvailableAccountBalances`, so an output like this:

`exchange: `
`{    BCH: 0.00432805,`
`     BTC: 0.54191671,`
`     BTG: 0.00001671 ,`
`     DASH: 0.00106497 }.`
`margin: `
`{    ETC: 0.00432805,`
`     ETH: 0.54191671,`
`     XMR: 0.00001671 },`

**Comment by kroitor** [comment]
@PolybitSol oh, I see, we will add support for margin accounts to fetchBalance soon.

**Comment by PolybitSol** [comment]
That's good to hear @kroitor, thanks again for the quick response, and keep up the great work!

**Comment by kroitor** [comment]
We added support for margin accounts to Bitfinex and Poloniex:

```JavaScript
// JavaScript
;(async () => {

    await bitfinex.fetchBalance ()
    await bitfinex.fetchBalance ({ type: 'exchange' }) // default
    await bitfinex.fetchBalance ({ type: 'margin' })
    await bitfinex.fetchBalance ({ type: 'funding' })

    await poloniex.fetchBalance ()
    await poloniex.fetchBalance ({ account: 'all' }) // default
    await poloniex.fetchBalance ({ account: 'exchange' })
    await poloniex.fetchBalance ({ account: 'margin' })
    await poloniex.fetchBalance ({ account: 'lending' })
}) ()
```

The extra param names are not unified yet, we are still working on a proper naming schema for them, but you can fetch margin, lending and exchange balances for Bitfinex and Poloniex like shown above as of version 1.10.174. Let us know here if you find other exchanges supporting the same functionality. I'm closing this in the meantime, if you don't mind.

**Comment by dbzalpha** [comment]
Kroitor & al, it seems that in CCXT 1.17.223, 
for margin balance on Bitfinex, via Python3, the correct params is: {'type': 'trading'}

**Comment by kroitor** [comment]
@dbzalpha 

> it seems that in CCXT 1.17.223, for margin balance on Bitfinex, via Python3, the correct params is: {'type': 'trading'}

That's right:

- https://github.com/ccxt/ccxt/issues/1207#issuecomment-357154252
- https://github.com/ccxt/ccxt/issues/879#issuecomment-352297127
- ...
