### ISSUE TITLE
Body field not populated in POST

### ISSUE THREAD

**Issue by abhishekr700** [ccxt/ccxt#6014]
Hi,
I'm trying to implement createOrder which requires a POST request to be sent to the exchange,On checking the logs I found that the `body` field is not being populated. I'm calling my api as `await this.privatePostOrders (this.extend (request, params));` . But if I check the fields passed to `sign method, the `body` is undefined here. The object needed to pass to body is my `request` object which I'm passing to API call.

**Comment by kroitor** [comment]
@abhishekr700 hi! We need more details:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- Which exchange is it?
- Have you checked the verbose output?
- Can you post the code to reproduce the issue, including the instantiation code, please, make it a short snippet of 10-20 lines, but without your keys, of course.

**Comment by kroitor** [comment]
> But if I check the fields passed to sign method, the bodyis undefined here. The object needed to pass to body is myrequest` object which I'm passing to API call.

The request is coming into the `sign` in the `params` argument, not in the `body` argument, and the `sign()` method has to fill the `body` from `params`. Let us know if that does not answer the question.
