### ISSUE TITLE
Bitstamp "Parse Error" using node v12 (works in node v10)

### ISSUE THREAD

**Issue by BigSteel** [ccxt/ccxt#6016]
UnhandledPromiseRejectionWarning: ExchangeNotAvailable: bitstamp GET https://www.bitstamp.net/api/v2/trading-pairs-info/ system request to https://www.bitstamp.net/api/v2/trading-pairs-info/ failed, reason: Parse Error
    at /Users/xxx/code/study/node_modules/ccxt/js/base/Exchange.js:410:35
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:15903) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15903) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

- OS: mac
- Programming Language version: node v12.6.0
- CCXT version: 1.18.1315
- Exchange: bistamp
- Method: getchOrderBook

**Comment by BigSteel** [comment]
it's ok  using  node v10

**Comment by kroitor** [comment]
Related: https://github.com/ccxt/ccxt/issues/5149

**Comment by frosty00** [comment]
it looks like bitstamp fixed the issue:

```
carlorevelli:/Users/carlorevelli/.../ccxt$ /usr/local/bin/node --version
v12.12.0
```
---
```
let x = new ccxt.bitstamp ()

x.verbose = true

;(async () => {
    await x.loadMarkets ()
    await x.fetchOrderBook ('ETH/BTC')
}) ();
```
