### ISSUE TITLE
How to get personal trade history in PHP?

### ISSUE THREAD

**Issue by rienaldis** [ccxt/ccxt#6019]
- OS: Windows 10
- Programming Language version: PHP
- CCXT version: 1.18.1308
- Exchange: Indodax
- Method: parse_trade and parse_order

its just a question, cause i confuse

>  public function parse_trade ($trade, $market = null) {
        $timestamp = $this->safe_timestamp($trade, 'date');
        $id = $this->safe_string($trade, 'tid');
        $symbol = null;
        if ($market !== null) {
            $symbol = $market['symbol'];
        }
        $type = null;
        $side = $this->safe_string($trade, 'type');
        $price = $this->safe_float($trade, 'price');
        $amount = $this->safe_float($trade, 'amount');
        $cost = null;
        if ($price !== null) {
            if ($amount !== null) {
                $cost = $price * $amount;
            }

>  public function parse_order ($order, $market = null) {
        $side = null;
        if (is_array($order) && array_key_exists('type', $order)) {
            $side = $order['type'];
        }
        $status = $this->safe_string($order, 'status', 'open');
        if ($status === 'filled') {
            $status = 'closed';
        } else if ($status === 'calcelled') {
            $status = 'canceled';
        }
        $symbol = null;

what should i fill for $trade in parse_trade ?
and what should i fill for $order in parse_order ?

**Comment by kroitor** [comment]
> what should i fill for $trade in parse_trade ?
> and what should i fill for $order in parse_order ?

First of all, you don't have to use those methods, since they are called from within the library itself when parsing the exchange response, so you only want to use them if you're implementing a new exchange API. So, in general, those two methods are not for calling from the outside. Why would you want to call them, though?

**Comment by rienaldis** [comment]
i want to show my trade history, is it possible?
