### ISSUE TITLE
Kuсoin Support - https://www.kucoin.com

### ISSUE THREAD

**Issue by arenstar** [ccxt/ccxt#602]
Would like support added for KuCOIN

https://kucoinapidocs.docs.apiary.io

**Comment by kroitor** [comment]
Started the work on it, will be available very soon in one of the upcoming releases.

**Comment by kornrunner** [comment]
I'm looking forward to this one. Can I help with it somehow? Thanks!

**Comment by kroitor** [comment]
@kornrunner in fact, yes you can... I have the public API mostly working, however, the private part is not unified yet. I can upload it as it is and, maybe you could pick up from there? I'm overloaded with our current tasks (trying to deliver WS and much more alltogether at once). Your help would be really appreciated! However, it may require some edits in JS code (as designed in ccxt, it is still a line-to-line portable syntax that is compatible with most web languages)... Let me know if you would give it a try?

**Comment by kroitor** [comment]
@kornrunner an alternative way would be upload the public API, and you could then submit PHP-implementations for private API which I would then port back to JS for transpilation to all other languages... However, if you could edit the same `js/kucoin.js` file like you do with any other `php/anyexchange.php` file, that would be translated to other languages automatically.
More about it in this doc (I guess, you've already read it): https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

**Comment by kornrunner** [comment]
Sure, that's fine by me. I can give it a try with writing JS (and following syntax/style/impl of existing exchanges) and then translate it to PHP. 

I'd appreciate it if you could merge in whatever you've done so far (if that's acceptable). Thanks!

**Comment by kroitor** [comment]
@kornrunner ok, just give me some short time to clean it up and commit it, I'll get back to you on this asap.

**Comment by kroitor** [comment]
Ok, I've uploaded it.

Important notes:

1. fetchOHLCV doesn't work whatever I try (see comments in code). They have two methods in the API – one returns ccxt-like format (`[[t,o,h,l,c,v],[...],...]`) the other returns TradeView-format (`{t:[],o:[],h:[],l:[],c:[],v:[]}`). However, both of them don't seem to work. This may be my mistake, and I may be missing something. If we don't succeed to make them work, then we can switch to their web api endpoint, here: https://kitchen.kucoin.com/v1/open/chart/history?symbol=ETH-BTC&resolution=480&from=1471799606&to=1513271666. But it also returns the TradeView format. So, maybe we should integrate it? This way we could implement OHLCV for most of exchanges with their web interfaces! However, this may me a topic for a separate request/code branch in itself... Let me know what you think of it.

2. Need to finish and test sign(), fetchBalance(), createOrder() and cancelOrder(). This is the basic trading API.

3. Then we can move on to fetchOrders, fetchOrders, fetchMyTrades, etc...

Questions are welcome! And thank you once again for your help!

**Comment by kornrunner** [comment]
Thank you!

As far as I've seen, OHLCV - it seems that it's not implemented or not working at all in Kucoin production (https://api.kucoin.com/v1/open/kline). The web api endpoint you've mentioned seems okay, so I guess I'll go with that - but since it's in TradeView format, I'll see to implement `build_ohlcv` in PHP first, and submit that before anything else.
