### ISSUE TITLE
Kraken Minimums

### ISSUE THREAD

**Issue by NescienceSoftware** [ccxt/ccxt#6021]
Im unsure if this is an issue or if I am just looking in the wrong place, however when using Kraken, I am attempting to ensure my orders are above the minimum amount for a given pair.

import ccxt

client = ccxt.kraken({'apiKey': '', 'secret': ''})

hmm = client.fetch_markets()
for h in hmm:
    if h['symbol'] == 'BAT/USD':
        minimum = h['limits']['amount']['min']
        print(minimum)

However, this returns a minimum of 1e-08, which is obviously incorrect as shown https://support.kraken.com/hc/en-us/articles/205893708-Minimum-order-size-volume-

Is there a different api call which I should be using to access the minimums? Or is this just an issue with ccxt grabbing the correct minimums?

Any help is appreciated as always!

**Comment by kroitor** [comment]
@NescienceSoftware what's your version of CCXT? Upon your call to `fetch_markets`, it should call and parse that page linked above to recognize the minimums properly... Can you show your verbose request/response sequence?

```Python
import ccxt

client = ccxt.kraken({'verbose': True})
client.load_markets()
```

↑ **please**, use [GitHub markdown](https://guides.github.com/features/mastering-markdown/) precisely as described here, to keep it readable:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by NescienceSoftware** [comment]
Well before getting too far into it, I checked and was on a pretty old version of 18.0, tried updating the library, and it appears that that did the trick. 

Appreciate the wildly quick responses again Mr. K
