### ISSUE TITLE
Fetch Transaction Limited to Deposit

### ISSUE THREAD

**Issue by bigcountry-scav** [ccxt/ccxt#6022]
Requesting the ability to specify the limitor of the filter array in fetch_transaction specifically in regards to Bitmex. By filtering this data we are missing our on some valued information like Realised PNL, Transfers, and Affiliate Payouts

line 546 in bitmex.py
transactions = self.filter_by_array(response, 'transactType', ['Withdrawal', 'Deposit', ], False)

Could read as follows or replace the transact type for specification by the user.

transactions = self.filter_by_array(response, 'transactType', ['Withdrawal', 'Deposit', 'RealisedPNL', 'Transfer', 'AffiliatePayout'], False)

**Comment by kroitor** [comment]
@bigcountry-scav

> Requesting the ability to specify the limitor of the filter array in fetch_transaction specifically in regards to Bitmex.

Can you elaborate on the question plz? What exactly do you mean under `limitor` ? Check this out, just in case:

- https://github.com/ccxt/ccxt/wiki/Manual#pagination
- https://github.com/ccxt/ccxt/wiki/Manual#all-transactions
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

**Comment by bigcountry-scav** [comment]
Sorry was further specifying as I accidentally submitted prematurely.

**Comment by kroitor** [comment]
@bigcountry-scav so, what you're looking for is `fetchLedger`, apparently. `fetchTransactions` is designed to return just the incoming deposits and the outgoing withdrawals, but not the internal transfers or referral payouts (this depends on the underlying API). So, if you want the history of all your movements, then you should use `fetchLedger` if the exchange in question `has['fetchLedger'] === true`. Let me know if that does not help.

**Comment by bigcountry-scav** [comment]
Yes thanks for the clarification as was not aware of the presence of fetchLedger and will adjust my code accordingly.
