### ISSUE TITLE
Liquid are introducing withdrawal fees for cryptos

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6023]
Starting 12 PM JST (3 AM UTC) on October 30, we are introducing fees for withdrawals of cryptocurrency from Liquid.

Liquid’s crypto withdrawal fees are competitively priced and in line with industry standards, but we know that this marks a change in our fee structure. 

Why are we doing this?

Our customers have told us that timely and accurate crypto withdrawals are highly desirable. So we built a secure, proprietary Crypto Asset Security Platform harnessing multi-party computation technology.

We will use this small fee to offset the cost of this superior solution and offer our customers the highest possible level of service for fast, secure withdrawals. Today, almost 90% of Bitcoin and XRP withdrawals and 75% of ETH withdrawals are processed in less than 10 minutes.

We continue to enhance the Liquid user experience with innovations like:

Automated no-touch withdrawals (forthcoming). 
Zero-block-confirmation Bitcoin deposits.
The Liquid Vision dashboard.
A small service cost for withdrawals helps us be able to keep bringing our customers sector-leading products and features. 

You can view the full withdrawal fee structure in our Help Center.

**Comment by JosephWN** [comment]
Unfortunately, I found that there are still no withdraw requests can be approved in night and weekends. I do not know where the improvment is except introducing withdraw fee.
