### ISSUE TITLE
JS poloniex nonce problem

### ISSUE THREAD

**Issue by siamaksalman** [ccxt/ccxt#6024]
- OS: Fedora 29
- Programming Language version: Javascript (Node JS)
- CCXT version: 1.18.1308 ( NPM installed )
- Exchange: poloniex
- Method: *

Using Valid ApiKey And Secret I get Nonce Error :

```{"error":"poloniex {\"error\":\"Nonce must be greater than 1548366998594000. You provided 1571859791519.\"}"}```

**Comment by kroitor** [comment]
@siamaksalman see the answer here:

- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

1. Create a new key first and foremost and try with a new fresh unused key.
2. Make sure you follow the Manual literally and enable the rate limiter.

Let us know if that does not help.

Dupe:

- https://github.com/ccxt/ccxt/issues/2564
