### ISSUE TITLE
Sending custom headers with requests to define sub account for FTX

### ISSUE THREAD

**Issue by pkaske** [ccxt/ccxt#6038]
Hi,

I'm currently experimenting with the PR for FTX (https://github.com/ccxt/ccxt/pull/5807) and I was wondering how I would set the custom request header `FTX-SUBACCOUNT` to define the sub account for the API key? I can't find anything about this in the PR or in the docs.

- OS: Linux
- Programming Language version: Javascript
- CCXT version: master + https://github.com/ccxt/ccxt/pull/5807
- Exchange: FTX
- Method: Any private

**Comment by kroitor** [comment]
Hey)

In JS it would look like so:

```
const exchange = new ccxt.ftx({
    'headers': {
        'FTX-SUBACCOUNT': 'YOUR_SUBACCOUNT_HERE',
    },
    // other settings...
})
```

Let us know if that does not answer the question or does not help.

**Comment by pkaske** [comment]
Works perfectly. Thank you very much!

**Comment by Jay54520** [comment]
Doesn't work for  ccxt==1.9.21 of python. The `outer_kwargs` doesn't include `self.headers`.
ccxt/base/exchange.py:422
```
                    def partialer():
                        outer_kwargs = {'path': url, 'api': api_type, 'method': uppercase_method}

                        @functools.wraps(entry)
                        def inner(_self, params=None):
                            """
                            Inner is called when a generated method (publicGetX) is called.
                            _self is a reference to self created by function.__get__(exchange, type(exchange))
                            https://en.wikipedia.org/wiki/Closure_(computer_programming) equivalent to functools.partial
                            """
                            inner_kwargs = dict(outer_kwargs)  # avoid mutation
                            if params is not None:
                                inner_kwargs['params'] = params
                            return entry(_self, **inner_kwargs)
                        return inner
```

**Comment by kroitor** [comment]
@Jay54520 the headers are applied at a different stage, see the implementation of `fetch()` and `request()`.

**Comment by Jay54520** [comment]
@kroitor I see it will add headers in `fetch()`, but private methods such as `privateGetOrders()` in `fetch_open_orders()` doesn't call `fetch()`, so the headers is not set.

**Comment by kroitor** [comment]
@Jay54520 

> but private methods such as privateGetOrders() in fetch_open_orders() doesn't call fetch(), so the headers is not set

All methods call `fetch()`, so the headers are always set for all private and public methods )

Here, in particular: https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L482

**Comment by Jay54520** [comment]
@kroitor Yes, I saw it just now.

**Comment by kroitor** [comment]
@Jay54520 

> Doesn't work for ccxt==1.9.21 of python.

So, it does work, right? Or, can you elaborate a bit on what you mean exactly when you say _doesn't work_ ? Maybe paste a code snippet of 5-20 lines, including instantiation (but without your keys), as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue ?

**Comment by Dante2333** [comment]
I can confirm this is still not working on python3.

**Comment by kroitor** [comment]
> and it wont work

↑ Can you please elaborate how exactly it wont work?

- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

**Comment by kroitor** [comment]
@Dante2333

> trying to use "FTX-SUBACCOUNT' along with 'key' and 'secret' and it wont work

The [comment above](https://github.com/ccxt/ccxt/issues/6038#issuecomment-546129700) shows that the FTX-SUBACCOUNT should be placed **not along** with `key` and `secret`, but **inside the `headers` subsection**.

**Comment by Dante2333** [comment]
Ok it worked. Thanks!
