### ISSUE TITLE
Kraken: loss of time precision in timestamps

### ISSUE THREAD

**Issue by Bomper** [ccxt/ccxt#6039]
Kraken returns millisecond-precision timestamps, e.g. `"time":1571869971.9908` (taken from the verbose output). CCXT seems to truncate the timestamp to the nearest second, as seen in the screenshot below. This creates problems because many executions are broken into smaller trades until the order fills completely, and all those trades appear to have the same timestamp.

Here is an example of trades obtained with `fetchMyTrades`.

![image](https://user-images.githubusercontent.com/34669048/67534047-a2680c80-f6cc-11e9-85e6-7bb26ad4bcaf.png)

- OS: Linux
- Programming Language version: Nodejs v12.11.1
- CCXT version: 1.18.1331
- Exchange: Kraken
- Method: GET

**Comment by kroitor** [comment]
@Bomper are you sure you have the most recent version of CCXT? This issue has been addressed here: https://github.com/ccxt/ccxt/issues/5758 two months ago...

**Comment by Bomper** [comment]
Thanks for the quick response. Unfortunately, yes. `ccxt.version` returns `1.18.1331`, and package-lock.json contains this:

```
    "ccxt": {
      "version": "1.18.1331",
      "resolved": "https://registry.npmjs.org/ccxt/-/ccxt-1.18.1331.tgz",
      "integrity": "sha512-sqRjEkAUKGOUudbmR1f4uD7en5mS8FjUwgG17KeXI9x91q7t02IK3GFpIS1EYRPRiNwneXxtoggdh6Cpj4oXVA=="
    },
```

The code is
```js
import ccxt from 'ccxt';
const kraken = new ccxt.kraken(apiKey: '...', secret: '...');
console.log(ccxt.version);
...
const [lastTrade] = await kraken.fetchMyTrades(undefined, Date.now() - 86400 * 1000, 1);
console.log(lastTrade);
```

The last 3 digits of `lastTrade.timestamp` are '000', while `lastTrade.info.time` has the correct timetamp:

```
{
  info: {
    time: 1571894600.7487,
  ...
  },
  timestamp: 1571894600000,
  datetime: '2019-10-24T05:23:20.000Z',
  ...
}
```

**Comment by kroitor** [comment]
@Bomper should be ok in 1.18.1333, tested on my side and it now does not cut off milliseconds. The new build will arrive in 15 minutes.
