### ISSUE TITLE
OKEx spot trading orders

### ISSUE THREAD

**Issue by Burpre** [ccxt/ccxt#6043]
I am battling to place spot orders. The code keeps on trying to execute futures
I using this line to execute:

symbol = 'my_symbol'
type = 'limit'  
side = 'buy'
amount = 'my_amount'
price = 'my_price'
params = {
                'order_id': 'my_order_id'],
                'trading_agreement': 'agree'
                }
exchange.createOrder (symbol, type, side, amount[ price[ params]])

with this traceback error:
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\base\exchange.py", line 540, in fetch
    response.raise_for_status()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.okex.com/api/futures/v3/orders/BTC-USD-191101?state=6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\USER\Documents\Trading\OKEx API\tempCodeRunnerFile.py", line 471, in <module>
    if i in exchange.fetch_open_orders(i):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\okex3.py", line 1903, in fetch_open_orders
    return self.fetch_orders_by_state('6', symbol, since, limit, params)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\okex3.py", line 1815, in fetch_orders_by_state
    response = getattr(self, method)(self.extend(request, query))
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\base\exchange.py", line 436, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\base\exchange.py", line 459, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\base\exchange.py", line 455, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\base\exchange.py", line 552, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\ccxt\okex3.py", line 2589, in handle_errors
    raise exact[errorCode](feedback)
ccxt.base.errors.PermissionDenied: okex3 {"code":32002,"message":"To activate you must read and accept the Futures Trading User Agreement"}

**Comment by kroitor** [comment]
@Burpre `BTC-USD-191101` is not a spot market, it is a futures market. You can't place a spot order on the futures market. If you want a spot order, you might want to look into the spot market that has symbol `BTC/USD`. Let us know if that does not help.

Also, it won't work, because you have to go to the okex website, then read and agree to the futures trading agreement on the website, as this exception says:

> ccxt.base.errors.PermissionDenied: okex3 {"code":32002,"message":"To activate you must read and accept the Futures Trading User Agreement"}

So, adding `'trading_agreement': 'agree'` to your params is a mistake – do not do this.

Your code should be:

```Python
symbol = 'BTC/USD'
type = 'limit'
side = 'buy'
amount = YOUR_AMOUNT
price = YOUR_PRICE
order = exchange.createOrder (symbol, type, side, amount, price)
```

Please, for the future, use proper [markdown](https://guides.github.com/features/mastering-markdown/) as explained [here](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue) to keep it readable.

**Comment by Burpre** [comment]
Hi,

Firstly, thank you so much for your help, I would not have been able to attempt this without this massive help. Hopefully this is my last hurdle.

I made the changes, but have been having some problems with the order id

When I use this {'order_id': 1001}
This is the error:
{"client_oid":"","error_code":"30024","error_message":"Parameter value filling error","order_id":"-1","result":false}

When I use this {'client_oid': 1001}
This is the error:
{"code":30024,"message":"{client_oid}Parameter value filling error"}

When I use this {'client_id': 1001}
This is the error:
{"client_oid":"","error_code":"30024","error_message":"Parameter value filling error","order_id":"-1","result":false}

If I don't have the paramater it gives this error
{"client_oid":"","error_code":"30024","error_message":"Parameter value filling error","order_id":"-1","result":false}

It also doesn't work with strings
When I use this {'client_oid': 'BTC1001'}
This is the error:
{"client_oid":"BTC1001","error_code":"30024","error_message":"Parameter value filling error","order_id":"-1","result":false}

I would really appreciate help, I am so close, but would have been nowhere without this library. Thank you so much for those working on it.

**Comment by kroitor** [comment]
@Burpre please read my previous answer, it has been edited and mentioned there that you should not set the `order_id` either.
