### ISSUE TITLE
Implementing CCXT in PyPy

### ISSUE THREAD

**Issue by icytrader** [ccxt/ccxt#6045]
Hi,

I know PyPy is not explicitly supported by ccxt but wonder if anyone manages to use CCXT with pypy interpretator? How painful (or is it painful) to solve the compatibility issues with PyPy? Would be interested to get an more efficient ccxt  with PyPy if that is feasible at all.

Thank you.

**Comment by Defqon51** [comment]
I am wondering the same, has anyone tried it yet?

**Comment by ttodua** [comment]
i tried and ccxt works within PyPy. closing this issue.

**Comment by ttodua** [comment]
the only thing that might need to be done at this moment (we will fix that soon) on Windows OS you might need:
```
import sys
import asyncio
if sys.platform == 'win32':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```
