### ISSUE TITLE
Bitmex testnet authentification required

### ISSUE THREAD

**Issue by tosti911** [ccxt/ccxt#6053]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10
- Programming Language version: Python 3.7
- CCXT version: 1.18.1208
- Exchange: Bitmex
- Method: Authentification error when trying bitmex testnet

Hi,

So my problem is that I keep getting authentification error on bitmex testnet, probably I did something wrong, but I've checked other issues and literally copy pasted the code and I still get that error.

```bitmex {"error":{"message":"Authorization Required","name":"HTTPError"}}```

Is the error, and the code I'm using is:

```
bitmex3 = ccxt.bitmex({
    'urls':
        {
            'api':'https://testnet.bitmex.com'
        },
    'apikey': 'x',
    'secret': 'x',
    'enableRateLimit': True,
    'verbose': False,
    'rateLimit': 1500
})

if 'test' in bitmex3.urls:
    bitmex3.urls['api'] = bitmex3.urls['test']

print(bitmex3.urls)

print(bitmex3.fetch_balance()['BTC'])
```

I've created new keys with the order permission but this error seems to be no matter what.
I can acces the link mentioned here #5810  but I have no idea what else to try, can you point me in the right direction or tell me what my mistake was?

Thanks!

**Comment by kroitor** [comment]
> can you point me in the right direction or tell me what my mistake was?

You can't use mainnet API keys for testnet and vice versa, those aren't interchangeable. You should use testnet keys with testnet, mainnet keys with the mainnet. In order to create testnet keys, you should go and signup here for testnet keys: https://testnet.bitmex.com

- https://github.com/ccxt/ccxt/issues/3960#issuecomment-427708607
- https://github.com/ccxt/ccxt/issues/2649#issuecomment-418241249

Let us know if that does not help.

**Comment by tosti911** [comment]
As mentioned, I did create multiple keys in the testnet. The keys for main net work, but the ones from testnet always result in the authentification error.

**Comment by kroitor** [comment]
@tosti911 apart from the above, you have a typo in the code:

```Python
    'apikey': 'x',  # should be apiKey, not apikey
```

Does it make a difference?

**Comment by tosti911** [comment]
God, can't believe I missed that ...
Yes it worked now, I've tried for a few hours different things from other issues and couldn't figure out. Excuse my incompetence and thank you for the fast fix.
@kroitor

**Comment by kroitor** [comment]
@tosti911 thx for reporting back! ) Cheers )
