### ISSUE TITLE
okex v3  {"code":30015,"message":"Invalid OK_ACCESS_PASSPHRASE"}

### ISSUE THREAD

**Issue by JiaMingYu** [ccxt/ccxt#6059]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:linux
- Programming Language version:
- CCXT version:1.18.1071
- Exchange:okex v3
- Method:    ccxt.okex3({
                            'apiKey': account['apiKey'],
                            'secret': account['accKey'],
                            'password': account['passphrase'],
                       })
error  {"code":30015,"message":"Invalid OK_ACCESS_PASSPHRASE"}
本地mac环境没出现这种情况。到底需要设置什么？时区吗？

**Comment by kroitor** [comment]
@JiaMingYu let us know if this does not help: https://github.com/ccxt/ccxt/issues/5976

**Comment by JiaMingYu** [comment]
我非常确信我的apikey是正确的。
exchange_id = 'okex3'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
       'apiKey': account['apiKey'],
       'secret': account['accKey'],
       'password': account['passphrase'],
        'timeout': 30000,
         'enableRateLimit': True,
          'rateLimit': 10000,
          'options': {
            'adjustForTimeDifference': True,
}
  })
 balance = exchange.fetch_balance()
tickers = exchange.fetch_tickers()
我非常需要你的帮助，还是出这个错误

**Comment by kroitor** [comment]
> 我非常确信我的apikey是正确的。

This is not a problem with your API, this is a wrong password, please read this issue **VERY CAREFULLY** for the answer: https://github.com/ccxt/ccxt/issues/5976#issuecomment-542412190

> the password required was the passphrase linked to the api. Not the login password nor the trading password

Hope this helps.
