### ISSUE TITLE
Transpiling with Webpack/Babel under Node v6

### ISSUE THREAD

**Issue by jla415** [ccxt/ccxt#606]
Hello

I am transpiling ccxt with webpack/babel to run on amazon lambda (node v6.10) and having problems with this code in fetch.js:

// using module.require to prevent Webpack / React Native from trying to include it
const nodeFetch = isNode && module.require ('node-fetch')

which results in the following error when executed:

TypeError: module.require is not a function

I am currently working around this by simply changing module.require() to require() in my own fork but would appreciate it if this workaround was not needed when using ccxt when transpiling ccxt with babel.  

Is there a way to change fetch.js to not throw the error in this configuration and still retain the original behavior intended by that line of code?

Thank you

**Comment by xpl** [comment]
I think it can be done, if upgrading to Node to 8.9.1 LTS (which is the <a href="https://nodejs.org/en/">current officially recommended Node version</a>) is somehow undesirable for you...

Also, I don't sure if I understand the purpose of Webpack in your setup (seems that you're running it in Node, and not in a browser, right?)... Have you tried [`babel-register`](https://babeljs.io/docs/usage/babel-register/)?

**Comment by jla415** [comment]
Hello,

Unfortunately the latest version of node provided by amazon web services lambda is node v6.10.3 or I would gladly run this project under v8.x

http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

In my setup webpack is used to load the typescript loader, the babel loader to transpile any newer language feature packages in node_modules such as ccxt and also keep the resulting deployment archive as small as possible by not including unused code

It all works great by changing module.require() to require() for my use case. 
 
Using webpack with node is a valid use case for many users, so maybe a different workaround might be better for whatever use cases you are trying to avoid including the node-fetch package in...

**Comment by xpl** [comment]
Can you please upload somewhere a minimal project demonstrating the error you experience (with instructions on how to reproduce it)? A GitHub repo would be fine.

**Comment by jla415** [comment]
[test.zip](https://github.com/ccxt/ccxt/files/1478120/test.zip)

nvm use v6
npm install
npm run test

**Comment by jla415** [comment]
https://github.com/ccxt/ccxt/commit/f3c145b570a12db8e848f79b6e0beaaff24578cf

This change fixes it in my case.  Unsure about your other use cases...

**Comment by xpl** [comment]
We'll see what can be done, thanks!

Basically, that workaround with `module.require` was needed to prevent Webpack from inlining that module in browsers / React Native builds — without the need to explicitly adding that file to the ignore list in a webpack config, because there are frameworks that don't even allow user to change that config...

**Comment by jla415** [comment]
Hello

Just fyi - your browserified output is actually larger with module.require():
-rw-r--r--  1 xd  staff  2951599 Nov 16 10:23 build/ccxt.browser.js

with plain require():
-rw-r--r--  1 xd  staff  2952075 Nov 16 10:23 build/ccxt.browser.js


If saving space was the goal the workaround is a failure...

**Comment by jla415** [comment]
Hello

The size difference is less than 500 bytes.  You could configure browserify to ignore this module I'm sure but is it worth the time and effort for 500 bytes in a 300k file?

with module.require():
-rw-r--r--  1 xd  staff  2951599 Nov 16 10:28 build/ccxt.browser.js

with plain require():
-rw-r--r--  1 xd  staff  2952075 Nov 16 10:31 build/ccxt.browser.js

**Comment by jla415** [comment]
I don't have a react native project to test with but if the problem was related to checking for node-fetch before window.fetch you could simply check for window.fetch first?

https://github.com/ccxt/ccxt/compare/master...jla415:master#diff-5d1c0fcd9de6ef79c4b7cf83f6213ee1

**Comment by xpl** [comment]
@jla415 nope, the order of checking does not matter in this expression `nodeFetch || windowFetch || xhrFetch`, because the `nodeFetch` variable is `false` in non-Node environments. The problem was caused by the React Native toolchain being unable to compile the project if we `require`d a non-Node module. This was a some time ago, and I do not have a React native setup now, so it will take some time to check it again.

**Comment by kroitor** [comment]
@jla415 thx so much for assistance! Really appreciate it!
