### ISSUE TITLE
Incorrect market.limits.amount.min for "BTC/USDT" on OceanEx

### ISSUE THREAD

**Issue by OliverNChalk** [ccxt/ccxt#6067]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

===

Sorry for the poor formatting, I'm in a rush. If this is not self explanatory I will re-format this issue later.

The problem is that the OceanEx BTC/USDT market returns "10.0" as the minmum quantity and "10" as the minimum cost. Whilst the minimum cost is correct, a minimum quantity of 10 btc is incorrect. I am not entirely sure what the correct value is.

**Comment by kroitor** [comment]
@OliverNChalk what is your version of CCXT? Do you have the same issue with the most recent version?

**Comment by kroitor** [comment]
@OliverNChalk nevermind, reproduced it on my side, will fix shortly.
