### ISSUE TITLE
Open a limit and a stop-limit order in one request on the Bitmex (bulk order)

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#6072]
Hello, 

How to correctly create a limit and a stop-limit order in the one request on the Bitmex on the python. 

It is not clear how to combine two solutions from the links below. 
https://github.com/ccxt/ccxt/issues/2649
https://github.com/ccxt/ccxt/blob/master/examples/py/bitmex-create-order.py

**Comment by ttodua** [comment]
for future readers: bitmex removed support for bulk endpoint several years ago
