### ISSUE TITLE
Bitmex filter "symbol"

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#6074]
What is correct a symbol for filtering in the fetchOpenOrders for bitmex?

orders = self.exchange.fetchOpenOrders(({'filter': self.exchange.json({"symbol":"XBTUSD"})}))

I have tried "XBTUSD", "BTCUSD", "BTC/USD" and it doesn't work.

**Comment by kroitor** [comment]
```Python
self.exchange.fetch_open_orders(symbol)
```

If you want to override the unified API params, you might want to do this:

```Python
symbol = 'BTC/USD'
since = None
limit = None
params = {
    'filter': self.exchange.json({"symbol":"XBTUSD"})
}
self.exchange.fetch_open_orders(symbol, since, limit params)
```

See also:

- https://github.com/ccxt/ccxt/issues/5769

The above is explained in the Manual here:

- https://github.com/ccxt/ccxt/wiki/Manual#querying-orders
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

Let us know if that does not help.

**Comment by YuriyTigiev** [comment]
orders = self.exchange.fetchOpenOrders(symbol = pair) - works 
where pair = "BTC/USD"

Thank you!
