### ISSUE TITLE
TCPConnector loop unexpected keyword argument, aiohttp 4.0.0a1 vs 3.6.2

### ISSUE THREAD

**Issue by abhishekr700** [ccxt/ccxt#6075]
Environment: ccxt Docker Image
Exchange: Bitbns (New exchange I'm working on)

All my tests except for python3 were passing with only these logs

```sh
root@553fab6a317d:/ccxt# node run-tests.js 
Testing { exchanges: ["bitbns"], symbol: "all", keys: { '--js': false, '--php': false, '--python': false, '--python2': false, '--python3': false }, maxConcurrency: 5 } (run-tests.js:252)
[100%] Testing bitbns FAIL (testExchange @ run-tests.js:169)

FAILED bitbns (Python 3): (explain @ run-tests.js:187)

	bitbns using proxy `` (explain @ run-tests.js:190)

```

I could not get any idea from above, so after a little digging, I realised I'll have to run the probably `python3 python/tests/test_async.py`.
On running it I got this output, please have a look.

```sh
root@553fab6a317d:/ccxt# python3 python/test/test_async.py 
bitbns using proxy ``
<class 'TypeError'> __init__() got an unexpected keyword argument 'loop' 

  File "python/test/test_async.py", line 448, in <module>
    asyncio.get_event_loop().run_until_complete(main())

  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()

  File "python/test/test_async.py", line 442, in main
    await try_all_proxies(exchange, proxies)

  File "python/test/test_async.py", line 373, in try_all_proxies
    await load_exchange(exchange)

  File "python/test/test_async.py", line 279, in load_exchange
    await exchange.load_markets()

  File "/ccxt/python/ccxt/async_support/base/exchange.py", line 185, in load_markets
    markets = await self.fetch_markets(params)

  File "/ccxt/python/ccxt/async_support/bitbns.py", line 162, in fetch_markets
    data = await self.publicGetFetchMarkets()

  File "/ccxt/python/ccxt/async_support/base/exchange.py", line 116, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File "/ccxt/python/ccxt/async_support/base/exchange.py", line 129, in fetch
    self.open()

  File "/ccxt/python/ccxt/async_support/base/exchange.py", line 81, in open
    connector = aiohttp.TCPConnector(ssl=context, loop=self.asyncio_loop)

<class 'TypeError'> __init__() got an unexpected keyword argument 'loop' 

  File "python/test/test_async.py", line 448, in <module>
    asyncio.get_event_loop().run_until_complete(main())

  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()

  File "python/test/test_async.py", line 442, in main
    await try_all_proxies(exchange, proxies)

  File "python/test/test_async.py", line 373, in try_all_proxies
    await load_exchange(exchange)

  File "python/test/test_async.py", line 279, in load_exchange
    await exchange.load_markets()

  File "/ccxt/python/ccxt/async_support/base/exchange.py", line 185, in load_markets
    markets = await self.fetch_markets(params)

  File "/ccxt/python/ccxt/async_support/bitbns.py", line 162, in fetch_markets
    data = await self.publicGetFetchMarkets()

  File "/ccxt/python/ccxt/async_support/base/exchange.py", line 116, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])

  File "/ccxt/python/ccxt/async_support/base/exchange.py", line 129, in fetch
    self.open()

  File "/ccxt/python/ccxt/async_support/base/exchange.py", line 81, in open
    connector = aiohttp.TCPConnector(ssl=context, loop=self.asyncio_loop)

root@553fab6a317d:/ccxt# 

```

**Comment by kroitor** [comment]
@abhishekr700 what's your version of aiohttp? Can you retry again after updating it?

**Comment by kroitor** [comment]
@abhishekr700 the sync version should work, though:

```
python3 python/test/test.py bitbns
```

**Comment by abhishekr700** [comment]
@kroitor 
My version is
`aiohttp==4.0.0a1`
Yup the sync version works and passes.
Also, pip3 search aiohttp gives this
```
aiohttp (3.6.2)                        - Async http client/server framework (asyncio)
  INSTALLED: 4.0.0a1
  LATEST:    3.6.2
aiohttp-sse-client (0.1.6)             - A Server-Sent Event python client base on aiohttp
```

**Comment by kroitor** [comment]
@abhishekr700 i'll test with `aiohttp==4.0.0a1` and will get back to you on this shortly.

**Comment by kroitor** [comment]
@abhishekr700 how did you install aiohttp btw? ) Did you run any specific commands? For some reason, I can't find 4.0.0a1 in PyPI, but I can see it here: https://docs.aiohttp.org/en/latest/

**Comment by kroitor** [comment]
@abhishekr700 ok, I've reproduced the issue with aiohttp 4.0.0a1 and fixed it, however, with that version of aiohttp there's another warning that happens inside the code of aiohttp, as reported here: https://github.com/aio-libs/aiohttp/issues/4282#issuecomment-549032887.

I believe, this is caused by the differences introduced in latest aiohttp 4.0.0a1 compared to 3.6.x. So, most of these issues are caused by the alpha-version of aiohttp. I would suggest to downgrade back to a more stable 3.6.x, until aiohttp releases a beta or a stable 4.x.x branch. We will force the version by specifying it in the dockerfile till then. What do you say?

**Comment by abhishekr700** [comment]
So should I rebuild the docker image ?

**Comment by kroitor** [comment]
@abhishekr700 yep, it should work with the most recent version of this repo, i've set the dep version to 3.6.2 explicitly. Let me know if that does not solve the issue. Thx!

**Comment by malcolm1232** [comment]
hi @kroitor , sorry to trouble again!

Somehow i keep getting the message:

connector = aiohttp.TCPConnector(ssl=context, loop=self.asyncio_loop)
TypeError: __init__() got an unexpected keyword argument 'ssl'

What would u suggest? Ive tried finding different solutions but still to no avail!

**Comment by kroitor** [comment]
@malcolm1232 try updating your aiohttp version.

**Comment by abhishekr700** [comment]
@malcolm1232 If you rebuild the docker image, you should get the appropriate version of aiohttp.

**Comment by malcolm1232** [comment]
@kroitor Hi, already tried upgrading aiohttp/asyncio version. via
pip3 install --upgrade aiohttp
pip3 install --upgrade asyncio 

@abhishekr700 sorry pardon me but what do u mean by "rebuild dovker image"

**Comment by malcolm1232** [comment]
pardon the super late reply ): been so hectic recently..

**Comment by kroitor** [comment]
@malcolm1232 if I understand correctly, you've tried reinstalling aiohttp, and it didn't help. If that is the case, paste your `pip3 list` here.

**Comment by malcolm1232** [comment]
@kroitor oh! i think i may have found the problem.. i was using python3.5... maybe not compatible. Hang on please!

**Comment by malcolm1232** [comment]
@kroitor  oh yes!! ive managed to already! probably cos its python3 V<= 3.5 

Thank you so very much @kroitor

**Comment by malcolm1232** [comment]
@kroitor oh! was wondering where could i get message books? Instead of order books. 
In particular, im trying to find cancellation of bid/ask orders

**Comment by kroitor** [comment]
@malcolm1232 hi! Can you plz clarify a bit which specific information you mean? 

Most of the concepts are outlined in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual

I'd highly recommend to read the above doc from top to bottom at least once – it will save your time, really. We need to use common terms to avoid a misunderstanding.
