### ISSUE TITLE
This pair is not available in the USA region.

### ISSUE THREAD

**Issue by mustapha1509** [ccxt/ccxt#6078]
Hello CCXT Community

OS: Windows / Ubuntu
Programming Language version: Javascript
CCXT version: 1.18.1270 / master branch
Exchange: Idex
Method: create order

When i made on order with idex i show this message 
`Error: idex {"error":"This pair is not available in the USA region."}`
How I can change the region from USA to Global

**Comment by kroitor** [comment]
> How I can change the region from USA to Global

If you're located in the US, then you can configure and use a proxy as described here: 

- https://github.com/ccxt/ccxt/wiki/Install#proxy

Alternatively, you can try a VPN with exit nodes outside of US. However, the legal aspects of doing so are all up to you.

Let us know if that does not answer the question.
