### ISSUE TITLE
OceanEx Market Constraints Endpoint

### ISSUE THREAD

**Issue by OliverNChalk** [ccxt/ccxt#6079]
Hey CCXT team, just found an endpoint for OceanEx you guys might find useful:

"https://api.oceanex.pro/v1/markets?show_details=true"

`curl -X POST -g "https://api.oceanex.pro/v1/markets?show_details=true"`

This will return a lot of the data you need to populate the market constraints info and will hopefully prevent ccxt from returning incorrect data (#6067).

**Comment by kroitor** [comment]
@OliverNChalk hi! We are already using that endpoint in the `fetchMarkets` call, and you can verify that in verbose mode:

```JavaScript
;(async () => {
    const ccxt = require ('ccxt')
    const exchange = new ccxt.oceanex ({ enableRateLimit: true, verbose: true })
    await exchange.loadMarkets ()
}) ()
```

or

```
node examples/js/cli oceanex markets --verbose --table
```

You should see something like:

```
mbp:ccxt igorkroitor$ node examples/js/cli oceanex markets --verbose --table
fetch:
 oceanex GET https://api.oceanex.cc/v1/markets?show_details=true
Request:
 { 'Content-Type': 'application/json' }
 undefined

handleRestResponse:
 oceanex GET https://api.oceanex.cc/v1/markets?show_details=true 200 OK
Response:
...
...
```

Let us know if the above does not answer the question.
