### ISSUE TITLE
'type' value of BitMEX's markets info has typo: `future` should be set as `futures`

### ISSUE THREAD

**Issue by lyn716** [ccxt/ccxt#6080]
- CCXT version: v.1.19.4
- Exchange: BitMEX
- Method: `fetch_markets()`

related: https://github.com/ccxt/ccxt/blob/ebd2618e04b43d36501af1087fc7fa0d40833494/python/ccxt/bitmex.py#L200

`future` should be set as `futures`

**Comment by kroitor** [comment]
This is not really a typo, it's there mostly for historical reasons. It is exchange-specific at this point, thus the `type` field is not completely unified yet. Some exchanges explicitly call that type `'future'`, others call it `'futures'`, so it's hard to fully unify it. 

- https://github.com/ccxt/ccxt/search?q=future&unscoped_q=future
- https://github.com/ccxt/ccxt/search?q=futures&unscoped_q=futures

Some exchanges use both words:

- https://github.com/ccxt/ccxt/blob/954cb28f5bd09c7dfe5b8b6c110407570e85a8d4/js/deribit.js#L93
https://github.com/ccxt/ccxt/blob/954cb28f5bd09c7dfe5b8b6c110407570e85a8d4/js/deribit.js#L150

- https://github.com/ccxt/ccxt/blob/9e8a4bf097201dc0b4f40e504265335ae8b7d854/js/ftx.js#L64
- https://github.com/ccxt/ccxt/blob/9e8a4bf097201dc0b4f40e504265335ae8b7d854/js/ftx.js#L227

There are also exchanges who changed that string during their lifetime, like okex, which had `future` in v1, now has `futures` in v3.

- https://github.com/ccxt/ccxt/issues/5142

We are going to unify those values at some point as `futures`, apparently. However, this will be a breaking change (backward-incompatible). What would you suggest?

**Comment by lyn716** [comment]
@kroitor Thanks a lot! I had not known for these historical reasons. I will be handle this situation at my app-level codes.  I have not suggestion for this now. It sounds like a tricky problem for maintainers.
