### ISSUE TITLE
Errors with trading on CREX24 

### ISSUE THREAD

**Issue by HotSwapp** [ccxt/ccxt#6089]
Hello! Has anyone been able to get this working on crex24? I am able to do simulated trades with Octobot but when I switch to real trading I get these two errors below. 

RESTExchange[crex24] 	Failed to get_price_ticker crex24 {"errorDescription":"Parameter 'instrument' contains invalid value."}

Trader[crex24] 	Error when initializing portfolio: 'NoneType' object is not subscriptable. crex24 trader disabled.

- OS: Ubuntu 18.04
- Programming Language version: Python 3.7.5
- CCXT version: '1.19.13'
- Exchange: CREX24
- Method: REST

**Comment by kroitor** [comment]
@HotSwapp you may want to ask that question here: https://github.com/Drakkar-Software/OctoBot, or, if you don't find any luck there, then, we will need the following info from you: https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it. Let us know if anything.
