### ISSUE TITLE
Entire Upbit Exchange Library Inactive?

### ISSUE THREAD

**Issue by karlandoh** [ccxt/ccxt#6094]
- OS: Linux
- Programming Language version: Python3
- CCXT version: Latest
- Exchange: ccxt.upbit
- Method: All functions, will use ```fetchBalance``` as example. 
```
Request: GET https://api.upbit.com/v1/accounts {'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3Nfa2V5IjoiVzRsSVg2eTdqMnhzYTQzYUhreGtjNWowZDE3bDJFYlJERTF6SVJaRiIsIm5vbmNlIjoxNTczMDQyNzc2Mjk3fQ.s-MXekInuDt7pjxLF0AZY6ToTv0uTDlzX_2uTYBWgUg', 'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.upbit.com/v1/accounts 401 {'Date': 'Wed, 06 Nov 2019 12:19:35 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Remaining-Req': 'group=default; min=897; sec=29', 'Content-Language': 'ko', 'Cache-Control': 'no-cache', 'X-Request-Id': '36440085-c65a-4ddb-8ae6-b718f17499a2', 'Vary': 'Origin'} {"error":{"message":"잘못된 엑세스 키입니다.","name":"invalid_access_key"}}
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 539, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.upbit.com/v1/accounts

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/ccxt/upbit.py", line 402, in fetch_balance
    response = self.privateGetAccounts(params)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 435, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 458, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 454, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 551, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/usr/local/lib/python3.7/site-packages/ccxt/upbit.py", line 1439, in handle_errors
    raise broad[broadKey](feedback)
ccxt.base.errors.AuthenticationError: upbit {"error":{"message":"\uc798\ubabb\ub41c \uc5d1\uc138\uc2a4 \ud0a4\uc785\ub2c8\ub2e4.","name":"invalid_access_key"}}
```
Api Keys and secrets have been validated. All functions return the same error. Thanks for viewing.

**Comment by kroitor** [comment]
@karlandoh have you tried a new api key?

**Comment by karlandoh** [comment]
Yes, I've tried two so far. Same issue

**Comment by kroitor** [comment]
@karlandoh are you sure that you haven't misplaced the `apiKey` with the `secret`? Unfortunately, both are 40-character `[a-zA-Z0-9]` strings, so it's easy to confuse them. Sorry for asking this, but we need to rule out everything. Also did it work for you at any point in the past?

**Comment by karlandoh** [comment]
I've also switched the parameters, with no avail. It has never worked for me, unfortunately.

**Comment by karlandoh** [comment]
is it possible that there are more parameters to enter? I currently have parameters for ```apiKey``` and ```secret```.

**Comment by kroitor** [comment]
> is it possible that there are more parameters to enter?

I don't think so... In fact, this may be related: https://sg.upbit.com/service_center/notice?id=2295

**Comment by kroitor** [comment]
@karlandoh unfortunately, the Upbit Global website does not accept signups from my location atm, can you share an API keypair (to my email address, no balance needed) so that i could debug this on my side quickly?

**Comment by karlandoh** [comment]
Hi! Can you please post your email so that I can send?

Thanks.

**Comment by karlandoh** [comment]
It will be pretty tough as I will need KYC verification to open one. In the meantime I will try and move my balance out so that I can send a temporary one. 

Thanks.

**Comment by kroitor** [comment]
@karlandoh no worries, I got the key, will debug this and will get back to you shortly.

**Comment by kroitor** [comment]
@karlandoh ok, I think i've found the cause of the issue.

Upbit has two engines:

1. Upbit SG (global), uses the API base url `sg-api.upbit.com`
2. Upbit Korea (local), uses the API base url `api.upbit.com` (and this is the default in CCXT).

I believe, you're trying to use the global (1) API keys with the local API (2). Those keys are not interchangeable. Upbit Korea will not be able to find your SG key, and Upbit global will not be able to find your Korean keys.

We have added a `hostname` config option to Upbit in order to handle this in CCXT 1.18.49.

So, if you're using the Upbit Korea website for generating your API keys, you can use the Upbit implementation from CCXT as is:

```Python
import ccxt
exchange = ccxt.upbit({
    'apiKey': 'KOREAN_LOCAL_API_KEY',
    'secret': 'KOREAN_LOCAL_SECRET',
    'enableRateLimit': True,
})
print(exchange.fetch_balance())
```

However, if you're using Upbit SG, you should change the base hostname, like so:

```Python
import ccxt
exchange = ccxt.upbit({
    'apiKey': 'KOREAN_LOCAL_API_KEY',
    'secret': 'KOREAN_LOCAL_SECRET',
    'enableRateLimit': True,
    'hostname': 'sg-api.upbit.com',  # ←----------------- HERE
})
print(exchange.fetch_balance())
```

Let us know if you have issues with it after updating to the most recent version and changing the hostname. Thx for reporting!

**Comment by karlandoh** [comment]
Looks good, thanks so much.
