### ISSUE TITLE
digifinex fetch_order raise KeyError

### ISSUE THREAD

**Issue by NadiaSama** [ccxt/ccxt#6097]
- OS:  Ubuntu 18.04.2 LTS 
- Programming Language version: Python3.8.0
- CCXT version: 1.19.17
- Exchange: digifinex
- Method: fetch_order

```Request: GET https://openapi.digifinex.vip/v3/spot/order?order_id=af4db5b17e9c4b305383313efe56f0c7 {'ACCESS-KEY': '15dc2a26586dd5', 'ACCESS-SIGN': '00dbc1279a9172d8a1dbc34e77c34a85f7345991d468e73ce115a1d4a41e9d68', 'ACCESS-TIMESTAMP': '1573137801', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} None```

```Response: GET https://openapi.digifinex.vip/v3/spot/order?order_id=af4db5b17e9c4b305383313efe56f0c7 200 {'Server': 'waf', 'Date': 'Thu, 07 Nov 2019 14:43:21 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'Expires': 'Thu, 14 Nov 2019 14:43:21 GMT', 'Cache-Control': 'max-age=604800', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS', 'Access-Control-Allow-Headers': 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type', 'Content-Encoding': 'gzip'} {"data":[{"finished_date":1573038753,"created_date":1573038753,"status":2,"kind":"spot","cash_amount":0,"type":"buy","avg_price":0.6165,"symbol":"DFT_USDT","amount":4,"order_id":"af4db5b17e9c4b305383313efe56f0c7","executed_amount":4,"price":0.6175}],"code":0}```

this is my code
```
#!/usr/bin/python

import ccxt

exchange = ccxt.digifinex({"apiKey": "15dc2a26586dd5", "secret": ""})

exchange.load_markets()

exchange.verbose = True

print(exchange.fetch_order("af4db5b17e9c4b305383313efe56f0c7"))
```

```
Traceback (most recent call last):
  File "bug.py", line 11, in <module>
    print(exchange.fetch_order("af4db5b17e9c4b305383313efe56f0c7"))
  File "/home/nadia/.pyenv3.8/lib/python3.8/site-packages/ccxt/digifinex.py", line 932, in fetch_order
    return self.parse_order(response)
  File "/home/nadia/.pyenv3.8/lib/python3.8/site-packages/ccxt/digifinex.py", line 779, in parse_order
    exchange = order['symbol'].upper()
KeyError: 'symbol'
```

hi my english not very well, it seems `parse_order` should extract order info at first. like this
```
    def parse_order(self, order, market=None):
        #
        # createOrder
        #
        #     {
        #         "code": 0,
        #         "order_id": "198361cecdc65f9c8c9bb2fa68faec40"
        #     }
        #
        # fetchOrder, fetchOpenOrders, fetchOrders
        #
        #     {
        #         "symbol": "BTC_USDT",
        #         "order_id": "dd3164b333a4afa9d5730bb87f6db8b3",
        #         "created_date": 1562303547,
        #         "finished_date": 0,
        #         "price": 0.1,
        #         "amount": 1,
        #         "cash_amount": 1,
        #         "executed_amount": 0,
        #         "avg_price": 0,
        #         "status": 1,
        #         "type": "buy",
        #         "kind": "margin"
        #     }
        #
        order = order["data"][0]
        id = self.safe_string(order, 'order_id')
```

**Comment by kroitor** [comment]
Hi @NadiaSama ! Thank you for a thorough report! This issue should be fixed in 1.19.18, the new build will arrive in 15 minutes.
