### ISSUE TITLE
Coinbase Pro - fetch_my_trades() order "price" summing "price" value of each trade, instead of averaging

### ISSUE THREAD

**Issue by drothroc** [ccxt/ccxt#6098]
- OS: Windows 10 Pro
- Programming Language version: Python 3.6
- CCXT version:ccxt==1.18.1315
- Exchange: Coinbase Pro
- Method: fetch_my_trades()

Overall price for an order is summing the individual prices of each trade instead of averaging them.

See below:

Overall price:  'price': 45974.55,
E.g. trade price:          'price': '9194.91000000', 
There are 5 trades, (5 * 9194.91 = 45,974.55)

`{
    'id': '8070cc0d-8616-47d9-a199-cbb49b48edc1',
    'fee': {
        'cost': 42.1819105765458,
        'rate': 0.005,
        'currency': 'USD'
    },
    'cost': 21090.9552882729,
    'info': {},
    'side': 'buy',
    'type': 'market',
    'source_executed_qty': executed_
    'price': 45974.55,
    'amount': 2.29376419,
    'filled': 2.29376419,
    'status': 'closed',
    'symbol': 'BTC/USD',
    'average': 0,
    'datetime': '2019-11-08T00:35:09.447Z',
    'remaining': 0.0,
    'timestamp': 1573173309447,
    'lastTradeTimestamp': None,
    'trades': [{
        'id': '6512762',
        'order': '8070cc0d-8616-47d9-a199-cbb49b48edc1',
        'info': {
            'created_at': '2019-11-08T00:35:09.447Z',
            'trade_id': 6512762,
            'product_id': 'BTC-USD',
            'order_id': '8070cc0d-8616-47d9-a199-cbb49b48edc1',
            'user_id': '59b3204cb6c70500fc23f35a',
            'profile_id': '59fc7c44-9272-4994-a52d-3a2b5d4b1708',
            'liquidity': 'T',
            'price': '9194.91000000',
            'size': '1.36436419',
            'fee': '25.0904118685458000',
            'side': 'buy',
            'settled': True,
            'usd_volume': '12545.2059342729000000'
        },
        'timestamp': 1573173309447,
        'datetime': '2019-11-08T00:35:09.447Z',
        'symbol': 'BTC/USD',
        'type': None,
        'takerOrMaker': 'taker',
        'side': 'buy',
        'price': 9194.91,
        'amount': 1.36436419,
        'fee': {
            'cost': 25.0904118685458,
            'currency': 'USD',
            'rate': 0.005
        },
        'cost': 12545.2059342729
    }, {
        'id': '6512761',
        'order': '8070cc0d-8616-47d9-a199-cbb49b48edc1',
        'info': {
            'created_at': '2019-11-08T00:35:09.447Z',
            'trade_id': 6512761,
            'product_id': 'BTC-USD',
            'order_id': '8070cc0d-8616-47d9-a199-cbb49b48edc1',
            'user_id': '59b3204cb6c70500fc23f35a',
            'profile_id': '59fc7c44-9272-4994-a52d-3a2b5d4b1708',
            'liquidity': 'T',
            'price': '9194.91000000',
            'size': '0.14460000',
            'fee': '2.6591679720000000',
            'side': 'buy',
            'settled': True,
            'usd_volume': '1329.5839860000000000'
        },
        'timestamp': 1573173309447,
        'datetime': '2019-11-08T00:35:09.447Z',
        'symbol': 'BTC/USD',
        'type': None,
        'takerOrMaker': 'taker',
        'side': 'buy',
        'price': 9194.91,
        'amount': 0.1446,
        'fee': {
            'cost': 2.659167972,
            'currency': 'USD',
            'rate': 0.005
        },
        'cost': 1329.583986
    }, {
        'id': '6512760',
        'order': '8070cc0d-8616-47d9-a199-cbb49b48edc1',
        'info': {
            'created_at': '2019-11-08T00:35:09.447Z',
            'trade_id': 6512760,
            'product_id': 'BTC-USD',
            'order_id': '8070cc0d-8616-47d9-a199-cbb49b48edc1',
            'user_id': '59b3204cb6c70500fc23f35a',
            'profile_id': '59fc7c44-9272-4994-a52d-3a2b5d4b1708',
            'liquidity': 'T',
            'price': '9194.91000000',
            'size': '0.19170000',
            'fee': '3.5253284940000000',
            'side': 'buy',
            'settled': True,
            'usd_volume': '1762.6642470000000000'
        },
        'timestamp': 1573173309447,
        'datetime': '2019-11-08T00:35:09.447Z',
        'symbol': 'BTC/USD',
        'type': None,
        'takerOrMaker': 'taker',
        'side': 'buy',
        'price': 9194.91,
        'amount': 0.1917,
        'fee': {
            'cost': 3.525328494,
            'currency': 'USD',
            'rate': 0.005
        },
        'cost': 1762.6642470000002
    }, {
        'id': '6512759',
        'order': '8070cc0d-8616-47d9-a199-cbb49b48edc1',
        'info': {
            'created_at': '2019-11-08T00:35:09.447Z',
            'trade_id': 6512759,
            'product_id': 'BTC-USD',
            'order_id': '8070cc0d-8616-47d9-a199-cbb49b48edc1',
            'user_id': '59b3204cb6c70500fc23f35a',
            'profile_id': '59fc7c44-9272-4994-a52d-3a2b5d4b1708',
            'liquidity': 'T',
            'price': '9194.91000000',
            'size': '0.22330000',
            'fee': '4.1064468060000000',
            'side': 'buy',
            'settled': True,
            'usd_volume': '2053.2234030000000000'
        },
        'timestamp': 1573173309447,
        'datetime': '2019-11-08T00:35:09.447Z',
        'symbol': 'BTC/USD',
        'type': None,
        'takerOrMaker': 'taker',
        'side': 'buy',
        'price': 9194.91,
        'amount': 0.2233,
        'fee': {
            'cost': 4.106446806,
            'currency': 'USD',
            'rate': 0.005
        },
        'cost': 2053.223403
    }, {
        'id': '6512758',
        'order': '8070cc0d-8616-47d9-a199-cbb49b48edc1',
        'info': {
            'created_at': '2019-11-08T00:35:09.447Z',
            'trade_id': 6512758,
            'product_id': 'BTC-USD',
            'order_id': '8070cc0d-8616-47d9-a199-cbb49b48edc1',
            'user_id': '59b3204cb6c70500fc23f35a',
            'profile_id': '59fc7c44-9272-4994-a52d-3a2b5d4b1708',
            'liquidity': 'T',
            'price': '9194.91000000',
            'size': '0.36980000',
            'fee': '6.8005554360000000',
            'side': 'buy',
            'settled': True,
            'usd_volume': '3400.2777180000000000'
        },
        'timestamp': 1573173309447,
        'datetime': '2019-11-08T00:35:09.447Z',
        'symbol': 'BTC/USD',
        'type': None,
        'takerOrMaker': 'taker',
        'side': 'buy',
        'price': 9194.91,
        'amount': 0.3698,
        'fee': {
            'cost': 6.800555436,
            'currency': 'USD',
            'rate': 0.005
        },
        'cost': 3400.2777180000003
    }]
}`

**Comment by kroitor** [comment]
Hi!

First, of `fetchMyTrades` is not supposed to return orders, just an array of trades, therefore it cannot sum the prices of those trades.

However, `fetchOrder` can include filling trades, but with Coinbase Pro it does not do that.

So, the questions to you:

1. Which particular exchange and which method is in question?
2. Are you sure that your version of CCXT is 1.18.1315?
3. Can you post **your code to reproduce the issue**, including the instantiation, but without your keys, using markdown for readability exactly as described here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue. We need you to be pedantic in order to resolve this issue quickly, those guidelines have to be followed literally to a word.
4. Can you post your **complete verbose request/response** for the above code?

Something like this is expected:

Code:

```
import ccxt
exchange = ccxt.coinbasepro({
    'apiKey': 'xxx',  # leave blank
    'secret': 'xxx',  # leave blank
    'password': 'xxx',  # leave blank
    # your constructor arguments, without keys
    # ...
})
exchange.load_markets()
exchange.verbose = True
exchange.YOUR_METHOD_CALL(ARGUMENTS)  # edit here
```

↓

Verbose request/response (this is just an example of a `fetchTicker` call):

```
mbp:ccxt igorkroitor$ python3 examples/py/cli.py coinbasepro fetchTicker ETH/BTC --verbose

Request: GET https://api.pro.coinbase.com/products/ETH-BTC/ticker {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.pro.coinbase.com/products/ETH-BTC/ticker 200 {'Date': 'Fri, 08 Nov 2019 10:19:27 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=de3eb06461207f7f558c7370fd8fcb79d1573208367; expires=Sat, 07-Nov-20 10:19:27 GMT; path=/; domain=.pro.coinbase.com; HttpOnly', 'Access-Control-Allow-Headers': 'Content-Type, Accept, cb-session, cb-fp, cb-form-factor', 'Access-Control-Allow-Methods': 'GET,POST,DELETE,PUT', 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'cb-before, cb-after, cb-gdpr', 'Access-Control-Max-Age': '7200', 'Cache-Control': 'public, max-age=1, must-revalidate', 'ETag': 'W/"95-t+11j9NNdZOk+uYXSjOX3cSFBBw"', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'X-DNS-Prefetch-Control': 'off', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-XSS-Protection': '1; mode=block', 'CF-Cache-Status': 'HIT', 'Age': '1', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '5326cf060fc79724-FRA', 'Content-Encoding': 'gzip'} {"trade_id":8522717,"price":"0.02046","size":"0.04056842","time":"2019-11-08T10:17:46.678Z","bid":"0.02045","ask":"0.02046","volume":"6812.46386222"}
```

**Comment by drothroc** [comment]
We can close this, I was using fetch_my_trades as an alternative to fetchOrder, as you stated CoinbasePro does not have fetchOrder. Therefore, I was using fetch_my_trades, then gathering all trades identified for a specific order and mocking a fetchOrder payload... The error was that I was summing... and not averaging, sorry for the inconvenience!

**Comment by kroitor** [comment]
@drothroc thx for reporting back! Let us know if anything!
