### ISSUE TITLE
fcoin fetch_ohlcv's  from_timestamp parameter not work 

### ISSUE THREAD

**Issue by a5601564** [ccxt/ccxt#6102]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:win10
- Programming Language version:
- CCXT version: 1.19.20
- Exchange: focin
- Method:fetch_ohlcv

ohlcvs = exchange.fetch_ohlcv(symbol, interval, from_timestamp,limit=500)

it can't get history datas ,but get the lastest data.
it dosen't correct .

**Comment by frosty00** [comment]
can you please post the verbose output as described here - https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by kroitor** [comment]
@frosty00 it is not passed to the exchange atm

@a5601564 we will fix this shortly

**Comment by kroitor** [comment]
@a5601564 this should be fixed in version 1.19.21, the new build will arrive in 15 minutes. Let us know if anything!
