### ISSUE TITLE
Wrong precision for FTX

### ISSUE THREAD

**Issue by Jay54520** [ccxt/ccxt#6103]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version: Python
- CCXT version: .19.21
- Exchange: FTX
- Method: create_order

For example, the price precision of `'TRXDOOM/USD'` is 0, but current its price is about `0.00001271`, so `price_to_precision` will return 0.

**Comment by Jay54520** [comment]
It's `priceIncrement` and `priceIncrement` in https://docs.ftx.com/#markets.

**Comment by Jay54520** [comment]
These values will update dynamically.

**Comment by kroitor** [comment]
@Jay54520 i've set them to `precisionFromString` which will return decimal precision, meaning 8 for `priceIncrement` and 0 for `sizeIncrement`, so it will work for `amountToPrecision`, `priceToPrecision`, etc, however, we may switch it to `TICK_SIZE` precision mode as in BitMEX implementation somewhat later.

**Comment by Jay54520** [comment]
Still wrong for `sizeIncrement`. The `sizeIncrement ` is `10000.0` for 'TRXDOOM/USD' now, but `precision_from_string('10000')` will return 0.

**Comment by kroitor** [comment]
@Jay54520 uhm... i've just explained this... ok, if that explanation wasn't clear, I will switch it to `TICK_SIZE` precisionMode for less confusion ))

**Comment by kroitor** [comment]
@Jay54520 should be ok in 1.19.23 (it will arrive in 15 minutes or so) Let us know if you find any other bugs! Thx for reporting! )
