### ISSUE TITLE
Deribit - Stop Limit orders Pyhton

### ISSUE THREAD

**Issue by mattou78400** [ccxt/ccxt#6106]
Hi all,

I'm currently trying to have ccxt open stop_limit orders in Deribit, from python.

I tried the bellow, but no luck:
```
            params = {
                    "stop_price": price,
                    "type":"stop_limit",
                    "trigger": "last_price",
                    }
                self.connection.create_order('BTC-PERPETUAL,"stop_limit", "buy", size, price, params)
```

That gets me:

ccxt.base.errors.NotSupported: deribit {"testnet":true,"message":"not_implemented","error":10033,"usOut":1573494728964015,"usIn":1573494728963999,"usDiff":16,"success":false}

Though given the Deribit.py "create_order" function, I don't see any reason that wouldn't work.

Please help! Thanks!

edit: stop price and buy price should be equal

**Comment by kroitor** [comment]
@mattou78400 i don't think that functionality is implemented with Deribit testnet. The message in the error you're getting says that this request is not implemented on the exchange side. Let us know if that does not answer the question.
