### ISSUE TITLE
Access to Braziliex via a CORS proxy has been blocked

### ISSUE THREAD

**Issue by EmerF** [ccxt/ccxt#6120]
I'm repeating the fetchOrderStatus and after some time, the api returns the below error: 
 
`Access to fetch at 'https://cors-anywhere.herokuapp.com/https://braziliex.com/api/v1/private' from origin 'https://w2robot.herokuapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled`

This is the way that i create the exchage object:
`timeOut = 50000;
 proxy = 'https://cors-anywhere.herokuapp.com/';

  init() {
    this.bra = new braziliex({
      apiKey: this.key,
      secret: this.secret,
      enableRateLimit: true,
      rateLimit: 25000,
      timeout: this.timeOut,
      proxy: this.proxy,
      origin: 'https://braziliex.com/'
    });`

- OS: Ubuntu 18.04.2
- Programming Language version: Javascript
- CCXT version:"^1.18.1120",
- Exchange: Braziliex
- Method:  fetchOrderStatus

** My app is hosted on heroku

**Comment by kroitor** [comment]
I'd suggest to try running your own CORS proxy instead of using the public one, as described here: https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin. Let us know if that does not help.

**Comment by EmerF** [comment]
How do I configure my own proxy to deploy the app in a remote sever like heroku? It's just to create and add the cors.js file?

**Comment by kroitor** [comment]
@EmerF in most cases, you simply deploy the cors.js to heroku, just like any other app... More about it here: https://elements.heroku.com/buttons/marcus2vinicius/cors-anywhere

**Comment by EmerF** [comment]
when i add cors. js  and then run node cors [port], open the page locahost:4200 it shows the page
https://cors-anywhere.herokuapp.com/. Do i have to achange something in my package? Express?

**Comment by kroitor** [comment]
> open the page locahost:4200

You should open it from the same host, where the CORS is running.

> Do i have to achange something in my package? Express?

No, if you're running the CORS on your localhost, then you can easily access it with https://localhost:4200/. If you're running it on a remote machine, then you should be able to access it via https://addresss-of-your-remote-heroku-cors:4200. From there you can add the URL of your CORS to your CCXT exchange config.
