### ISSUE TITLE
Anyone using Lykke?  Is it safe

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6128]
Their private API doesn't use a private key (or nonce) so the sign method in ccxt doesn't actually sign anything.  The API Key just goes across the wire as a clear text header.

**Comment by KonstantinRyazantsev** [comment]
1. API key transmitted over HTTPS and the user can rotate key as often as needed. This is the same as Bearer token authentication.
2. This API doesn't allow withdrawals. Withdrawals are possible only trading account using 2FA.

So seems all safe here.

**Comment by kroitor** [comment]
@npomfret there are other exchanges that do the same thing as well:
- bitlish
- cobinhood
- rightbtc
- virwox

These exchanges are relying on HTTPS. So, if your key leaks, you should change it immediately. Let me know if that does not answer the question.

**Comment by npomfret** [comment]
Thanks for the feedback.
