### ISSUE TITLE
isJsonEncodedObject fails with whitespace padded strings

### ISSUE THREAD

**Issue by fl4p** [ccxt/ccxt#6133]
Also see https://github.com/ccxt/ccxt/issues/5721

Is`isJsonEncodedObject` fails to detect JSON that is padded with whitespaces:

```
isJsonEncodedObject("   []") // false, expected true
```

**Comment by kroitor** [comment]
@fl4p do you have an issue with it with some particular exchange?

**Comment by kroitor** [comment]
@fl4p let me know if you have an issue with some specific exchange breaking down on it. Closing this for now, feel free to reopen it if needed or just ask further questions if any. Thx!
