### ISSUE TITLE
[Poloniex] Create only limit orders

### ISSUE THREAD

**Issue by alexeymarunin** [ccxt/ccxt#6136]
- OS: MacOS Catalina 10.15
- Programming Language version: Node.js 12.7.0
- CCXT version: 1.19.43 
- Exchange: Poloniex
- Method: createOrder

According [official documentation](https://docs.poloniex.com/#buy) I can create only limit orders (see #2889). And also [raw request](https://github.com/ccxt/ccxt/blob/master/js/poloniex.js#L904) has no any order type specified. So, may be change condition in the begining of `createOrder`:

```js
if (type !== 'limit') {
    throw new ExchangeError (this.id + ' allows limit orders only');
}
```

**Comment by albertord84** [comment]
it's not a god idea because Poloniex has margins orders and forcing limit cut it!
