### ISSUE TITLE
How to get the position of okex3 future?

### ISSUE THREAD

**Issue by zhang-jizheng** [ccxt/ccxt#6142]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
  MAC
- Programming Language version:
   Python
- CCXT version:
   Latest
- Exchange:
  Okex3
- Method:
   get the position of future

How to get the position of OKEX3 future? Dear?

**Comment by StanleyDing** [comment]
In Javascript,`futuresGetPosition` method can be used to fetch all positions. Just use the equivalent method in python to get your position.

**Comment by kroitor** [comment]
Thx @StanleyDing !

@zhang-jizheng see the Manual on how to call implicit api methods: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

Let us know if the above does not answer the question.
