### ISSUE TITLE
OKEX3 load_markets miss futures in Win10 

### ISSUE THREAD

**Issue by zhang-jizheng** [ccxt/ccxt#6143]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
  Windows 10
- Programming Language version:
   Python
- CCXT version:
  Latest
- Exchange:
  Okex3
- Method:
  load_markets()
  
  It's very strange, this function can load 449 instruments including futures in MAC Pro, but it only loads 428 instruments without futures 

codes:

            self.exchange = ccxt.okex3({
                'apiKey': self.apiKey,
                'secret': self.secret,
                'enableRateLimit': True,
            })

            self.exchange.proxies = self.proxies
            self.markets = self.exchange.load_markets()

**Comment by kroitor** [comment]
@zhang-jizheng what's your version of CCXT with Win10?

```Python
        self.exchange = ccxt.okex3({
            'apiKey': self.apiKey,
            'secret': self.secret,
            'enableRateLimit': True,
        })

        self.exchange.proxies = self.proxies
        self.markets = self.exchange.load_markets()

        print('CCXT version:', ccxt.__version__)
```

Which Python/version do you use with Win10?

**Comment by zhang-jizheng** [comment]
Python3.7 , seems something wrong in okex3.py->parse_markets, this function judge a future based on whether has the value "quote_currency",

**Comment by kroitor** [comment]
@zhang-jizheng what's the version of CCXT with windows 10?

```Python
import ccxt
print('CCXT version:', ccxt.__version__)
```

?

**Comment by kroitor** [comment]
@zhang-jizheng this issue was fixed a few weeks ago here: https://github.com/ccxt/ccxt/pull/6069
Closing this for now. Let us know if updating to the most recent version on your Windows 10 system does not help.
