### ISSUE TITLE
Common indicators

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#6144]
Hello, 

Could you add to ccxt library the following common indicators: sma, ema, vwma, rsi, stochastic rsi, stochastic?

**Comment by kroitor** [comment]
Hi! At this point we don't have the plans to add indicators or analysis functionality to the core of CCXT. We may add this as an addon in the remote future. CCXT is a lib that is used to interact with the exchanges, but if you want technical analysis and indicators, there are packages implementing the analysis functionality that you can use with CCXT (with some code added on your side). Just google for _"technical analysis python"_ or [search pypi](https://pypi.org/search/?q=ta) for _"tech analysis", "technical analysis", "stocks indicators", you will tons of that... Hope that answers the question.
