### ISSUE TITLE
Can't use create order in FTX (Question)

### ISSUE THREAD

**Issue by stephencostiniano** [ccxt/ccxt#6146]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10
- Programming Language version: Python 3.7.4
- CCXT version: 1.19.44
- Exchange: FTX
- Method: create_order

Hello I'm having a hard time debugging the error when I create an order in FTX Exchange since I haven't encountered any problem Using create order in Binance these are the following Errors
AssertionError

Code Line
ftx.buy_limit_order('ETH/USD', 0.002, 100.00)
order = self.ftx.create_order(symbol, type, side, amount, price)

Return Error:
line 1189, in amount_to_precision
    return self.decimal_to_precision(amount, TRUNCATE, self.markets[symbol]['precision']['amount'], self.precisionMode)

line 41, in decimal_to_precision
    assert(isinstance(precision, numbers.Integral))
AssertionError

**Comment by kroitor** [comment]
@stephencostiniano thx for reporting! This issue is fixed in 1.19.48 (the new build will arrive in 15 minutes). Let us know if you still have difficulties with it. Cheers!

**Comment by stephencostiniano** [comment]
Thank you so much @kroitor
