### ISSUE TITLE
CCXT python can't support bitmex 'XBTZ19' symbol.

### ISSUE THREAD

**Issue by JoshColeen** [ccxt/ccxt#6147]
I'm using windows 10, python3.7.4 .
I'm going to get 'XBTZ19' trade data from bitmex.
ccxt can provide this function?
I want to get result of following request.
https://testnet.bitmex.com/api/v1/trade?symbol=XBTZ19&count=1&reverse=true

**Comment by kroitor** [comment]
> ccxt can provide this function?

Yes, please read the Manual from top to bottom: https://github.com/ccxt/ccxt/wiki. Let us know if that does not help.
