### ISSUE TITLE
no name module gdax() in ccxt 

### ISSUE THREAD

**Issue by BahadirSoybakis** [ccxt/ccxt#6148]
import ccxt  # noqa: E402

kraken = ccxt.kraken()
gdax = gdax().ccxt

I'd like work with this code part. Compiler cannot find function name as gdax(). Also I controlled the file, there is no function in the ccxt  master file. Has the function lost its continuity? How can I continue?

**Comment by frosty00** [comment]
`gdax` is depreciated, please use `coinbasepro` instead )

let me know if you have any other issues

**Comment by BahadirSoybakis** [comment]
gdax = ccxt.coinbasepro()
thanks for your support.
