### ISSUE TITLE
ccxt有添加gateio交易所的WebSocket API吗？

### ISSUE THREAD

**Issue by yazhoushi** [ccxt/ccxt#6151]
gateio的v2版本的API请求次数有限制，而且网络也速度不行！ccxt可以添加gtaeio的WebSocket API吗？谢谢了

**Comment by kroitor** [comment]
@yazhoushi yes, we are working on the WS support right now. More about it here: https://github.com/ccxt/ccxt/issues/56#issuecomment-507290536. We will add that as soon as possible. Hope that answers your question.

**Comment by yazhoushi** [comment]
Good! How long will it take?

**Comment by kroitor** [comment]
@yazhoushi please, follow the link above and read the comments, it's all explained there ;)

**Comment by yazhoushi** [comment]
ok！Thanks
