### ISSUE TITLE
Binance Create Order InvalidNonce

### ISSUE THREAD

**Issue by stephencostiniano** [ccxt/ccxt#6152]
- OS: Windows 10
- Programming Language version: Python 3.7.4
- CCXT version: 1.19.54
- Exchange: Binance
- Method: create_order()

Hi I've tried executing trade yesterday in Binance and it went well but I tried executing trades again then a TimeStamp Error appeared I don't know if Binance has a new update or my time clock is not properly sync with the server. but I manage to create order in Huobi, Okex & FTX

Error Return:
line 1286, in handle_errors
    raise exceptions[error](self.id + ' ' + body)
ccxt.base.errors.InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}

**Comment by kroitor** [comment]
@stephencostiniano Hi! 

This is documented and answered in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#invalidnonce

Do you have the rate-limiter enabled? Do you use those keys with any other software?

**Comment by kroitor** [comment]
@stephencostiniano ah, pardon, i didn't read the error message carefully, it's a bit different issue, see the answers here: 

- https://github.com/ccxt/ccxt/issues/773
- https://github.com/ccxt/ccxt/issues/850

Let me know if the above does not help.

**Comment by stephencostiniano** [comment]
Hello @kroitor #773 works for me I've try to synchronize my internet time thanks a lot
