### ISSUE TITLE
Bad Symbol For Bittrex SAI vs DAI (DAI No Longer Exists)

### ISSUE THREAD

**Issue by R-K-H** [ccxt/ccxt#6155]
- OS: Linux / Mac
- Programming Language version: Node v10.11.0
- CCXT version: 1.19.57
- Exchange: Bittrex
- Method: FetchClosedOrders

Bittrex Updated Their DAI to SAI. Now I'm getting a bad symbol, and market does not exist with DAI vs SAI.

**Comment by R-K-H** [comment]
Seems that https://bittrex.zendesk.com/hc/en-us/articles/360035866431-Support-for-the-Dai-DAI-Multi-Collateral-Dai-Upgrade they will be adding SAI and then will be converting back to DAI on Dec 2nd.

**Comment by kroitor** [comment]
This is a common thing:

- https://bittrex.zendesk.com/hc/en-us/articles/360035866431-Support-for-the-Dai-DAI-Multi-Collateral-Dai-Upgrade
- https://medium.com/switcheo/migration-to-multi-collateral-dai-d811959be7c0
- https://www.kucoin.com/news/en-dai-will-be-renamed-as-sai/

@R-K-H the actual mapping should be updated automatically, if you're loading unified markets as described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

Let us know if the above does not help.
