### ISSUE TITLE
Format for selling e. g. 0.001 XBTUSD on Bitmex

### ISSUE THREAD

**Issue by bitcoinmeetups** [ccxt/ccxt#6157]
Format for selling e. g. 0.001 XBTUSD on Bitmex

Hi,

I want to automate selling futures on Bitmex. For example selling 0.001 XBTUSD at 8000 USD.

I'm looking for a simple format as similar to this as possible:

node examples/js/cli bitfinex createOrder ETH/BTC limit sell 1 0.02 

BM

OS: Linux
CCXT: latest

**Comment by kroitor** [comment]
Hi! Can you please elaborate what exactly you mean under _"format"_ ?

> node examples/js/cli bitfinex createOrder ETH/BTC limit sell 1 0.02

↑ If that works, why doesn't this work:

```
node examples/js/cli bitmex createOrder BTC/USD limit sell 0.001 8000
```

?

**Comment by kroitor** [comment]
@bitcoinmeetups you might want to get familiar with this:

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

```
node examples/js/symbols bitmex
```

```
node examples/js/cli bitmex market BTC/USD
```

```
node examples/js/cli bitmex markets --table
```

```
node examples/js/cli bitmex symbols
```

```
node examples/js/cli bitmex findMarket XBTUSD
```

**Comment by kroitor** [comment]
@bitcoinmeetups let us know if the above does not help.

**Comment by bitcoinmeetups** [comment]
Hi,

I don't think futures and crypto have the same format. That input you suggested would just generate an error message. The syntax is different too. And the futures are called XBTUSD on Bitmex, not BTC or USD. So in essence I'm looking for the right syntax.

**Comment by kroitor** [comment]
@bitcoinmeetups plz read the Manual, that will explain everything, in particular:

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

However, I'd suggest to read the entire Manual from top to bottom to be able to work with this lib efficiently.

> And the futures are called XBTUSD on Bitmex, not BTC or USD.

In CCXT that particular market with BitMEX is called BTC/USD, and that is explained in the Manual.

**Comment by kroitor** [comment]
@bitcoinmeetups P.S. also try running these examples: https://github.com/ccxt/ccxt/issues/6157#issuecomment-555878180 and reading through the output carefully

**Comment by bitcoinmeetups** [comment]
Hi,

I will try to see if I can get this running and report output later:

node examples/js/cli bitmex createOrder BTC/USD limit sell 0.001 8000

**Comment by kroitor** [comment]
@bitcoinmeetups ok, let us know if you have any difficulties with it.

**Comment by bitcoinmeetups** [comment]
Input:
node cli.js bitmex createOrder BTC/USD limit sell 0.001 8000 

Output (error message):
[BadRequest] bitmex {"error":{"message":"This request has expired - `expires` is in the past. Current time: 1574237395","name":"HTTPError"}}                                              
    at handleErrors   …ome/blahblah/ccxt/ccxt/js/bitmex.js:1272  throw new BadRequest (feedback);                                                                                              at then           /ccxt/ccxt/js/base/Exchange.js:624  this.handleErrors (response.status, response.statusText, url, method, responseH…                                              at _tickCallback  internal/process/next_tick.js:68                                       

bitmex {"error":{"message":"This request has expired - `expires` is in the past. Current time: 1574237395","name":"HTTPError"}}

**Comment by kroitor** [comment]
@bitcoinmeetups you need to syncrhonize your system clock with UTC online time server as described here, for example: 

- https://github.com/ccxt/ccxt/issues/850#issuecomment-353774447
- https://github.com/ccxt/ccxt/issues/773#issuecomment-349827065

**Comment by kroitor** [comment]
@bitcoinmeetups you can see which time is being sent to BitMEX by adding the `--verbose` flag:

```
node cli.js bitmex createOrder BTC/USD limit sell 0.001 8000 --verbose
```

But anyways, in order to fix that error you need to synch your system clock. BitMEX will not accept your private requests otherwise.

**Comment by kroitor** [comment]
@bitcoinmeetups if you're on linux, installing and configuring `ntpd` should resolve the issue, let us know if that does not help.

**Comment by bitcoinmeetups** [comment]
Ok, I will try that. At the moment the time issue seems to have been resolved through some basic actions I took.

So now the input almost works. But there is one more thing, I get a "invalid quantity" error. This test account has 0.0006 XBT on it. So this should work:

node cli.js bitmex createOrder BTC/USD limit sell 0.0001 8082

It doesn't matter how low I put the quantity, I still get a quantity error message.

**Comment by kroitor** [comment]
@bitcoinmeetups can you plz show the verbose output of it?

```
node cli.js bitmex createOrder BTC/USD limit sell 0.0001 8082 --verbose
```

?

**Comment by kroitor** [comment]
The request should look close to this:

```
bitmex.createOrder (BTC/USD, limit, sell, 0.0001, 8082)
private
fetch:
 bitmex POST https://www.bitmex.com/api/v1/order
Request:
 {
  'Content-Type': 'application/json',
  'api-key': 'TLJ6TYVOjN5qf9duGCnEX0fs',
  'api-expires': '1574239957',
  'api-signature': '4da6b793d9912a79c76006b8827f1dc55443fcb8a21531b1fd3fa158730d5985'
}
 {"symbol":"XBTUSD","side":"Sell","orderQty":0.0001,"ordType":"Limit","price":8082}
```

↑ Do you see the same on your side?

**Comment by bitcoinmeetups** [comment]
bitmex.createOrder (BTC/USD, limit, sell, 0.0001, 8082)                                      fetch:                                                                                        bitmex POST https://www.bitmex.com/api/v1/order                                             Request:                                                                                      { 'Content-Type': 'application/json',                                                                                                     'd3db6e32b73dd80dd1235434665ac13453647c468daba44db5af3581da09ccef'{"symbol":"XBTUSD","side":"Sell","orderQty":0.0001,"ordType":"Limit","price":8082}                                                                                                       handleRestResponse:                                                                           bitmex POST https://www.bitmex.com/api/v1/order 400 Bad Request                             Response:                                                                                     { Connection: 'close',                                                                        'Content-Length': '62',                                                                      'Content-Type': 'application/json; charset=utf-8',                                           Date: 'Wed, 20 Nov 2019 08:49:55 GMT',                                                       Etag: 'W/"3e-pTLJxR1SshmWX4CsUr6HwNWjqd8"',                                                  'Set-Cookie':                                                                                 'AWSALB=408jVg6lwF1BEb6H7qXGYNBTl/7dAArEfbcVmmflIatvwpLxk1cq
'Content-Type': 'application/json; charset=utf-8',                                           Date: 'Wed, 20 Nov 2019 08:49:55 GMT',                                                       Etag: 'W/"3e-pTLJxR1SshmWX4CsUr6HwNWjqd8"',                                                  'Set-Cookie':                                                                                 'AWSALB=408jVg6lwF1BEb6H7qXGYNBTl/7dAArEfbcVmmflIatvwpLxk1cqUJfhCerKIu70Y0Do32XofF5z7KF2uRz23v8P538bJc36LtuBB12Ek9/CSorb34d1G281jPzp; Expires=Wed, 27 Nov 2019 08:49:55 GMT; Path=/',    'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',                          'X-Powered-By': 'Profit',                                                                    'X-Ratelimit-Limit': '60',                                                                   'X-Ratelimit-Remaining': '59',                                                               'X-Ratelimit-Reset': '1574239796' }                                                         {"error":{"message":"orderQty is invalid","name":"HTTPError"}}                                                                                                                           InvalidOrder bitmex {"error":{"message":"orderQty is invalid","name":"HTTPError"}}           ---------------------------------------------------                                          [InvalidOrder] bitmex {"error":{"message":"orderQty is invalid","name":"HTTPError"}}                                                                                                          at handleErrors   …ome/qerterqtwwrt/ccxt/ccxt/js/bitmex.js:1264  throw new exact[message] (feedback);                                                                                          at then           …ivera/ccxt/ccxt/js/base/Exchange.js:624  this.handleErrors (response.status, response.statusText, url, method, responseH…                                              at _tickCallback  internal/process/next_tick.js:68                                                                                                                                                                                                                                 bitmex {"error":{"message":"orderQty is invalid","na

**Comment by bitcoinmeetups** [comment]
Hope I got everything there

**Comment by kroitor** [comment]
@bitcoinmeetups I'll check for that and will get back to you.

You might want to check this out in the meantime:

- https://www.bitmex.com/app/restAPI#Order-Minimum-Size-Limits

-----

- https://www.bitmex.com/api/explorer/#!/Order/Order_new

↑ This says that orderQty should be

> Order quantity in units of the instrument (i.e. contracts).

**Comment by bitcoinmeetups** [comment]
Thank you Igor. That worked. The quantity refers to the contracts, not to the BTC value.

This is fun and fantastic. 

So if I want to automatically sell at best current price instead of inputting a price manually, which flag would I use?

**Comment by bitcoinmeetups** [comment]
Ah, I guess it's createMarketSellOrder. I will try that.

**Comment by kroitor** [comment]
@bitcoinmeetups what you're using is not the CCXT itself, it's just a thin example wrapper that allows running CCXT methods from console. However, that tiny example wrapper is not designed to be a sophisticated trading system, it's just a thin wrapper. The CCXT itself allows you to do whatever automation you want, including "best current price" and whatever other trading strategy you want, however, if you want to use it, you will need to add some scripting with one of the languages supported by CCXT, as described in the Manual. CCXT itself is not a terminal, it's a programmatic toolkit that allows developers create whatever trading algorithms or applications they want. Hope that helps.
