### ISSUE TITLE
Easiest way to get open positions from Bitmex?

### ISSUE THREAD

**Issue by bitcoinmeetups** [ccxt/ccxt#6158]
Hi,

I'm looking for the easiest way to get my open positions from Bitmex.

"You should call private_get_position. Read the Manual for more info about how to use it."

I have spent a good while today reading the manual but I haven't found an easy example for this yet.

Anyone know of a good way, preferably a one-liner?

BM

**Comment by kroitor** [comment]
Read this:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://www.bitmex.com/api/explorer/#!/Position/Position_get

```
node examples/js/cli bitmex private_get_position '{"filter":"{\"isOpen\":true, \"symbol\":\"XBTUSD\"}"}'
```

```JavaScript
// JavaScript

const ccxt = require ('ccxt')
exchange = new ccxt.bitmex ({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': true,
})
;(async () => {
    await exchange.loadMarkets ()
    const positions = exchange.private_get_position({ 
        'filter': exchange.json({"isOpen":True, "symbol":"XBTUSD"})
    })
    console.log (positions)
}) ()
```

Let us know if the above does not answer the question.

**Comment by bitcoinmeetups** [comment]
It might work but I cannot read the output from the first example. I tried to pipe it to jq but that also didn't work. Is there a way to get a readable output?

**Comment by kroitor** [comment]
> Is there a way to get a readable output?

Yes, start learning a bit of programming )

1. Make a folder for your project:

```
mkdir my-ccxt-folder
cd my-ccxt-folder
```

2. Then initialize it with npm:

```
npm init  # hit enter for all defaults until it exits
```

3. Install CCXT:

```
npm install ccxt
```

4. Save the contents of the [JavaScript above](https://github.com/ccxt/ccxt/issues/6158#issuecomment-555994708) to a file in that folder `my-ccxt-folder`, name the file how you like (`my-ccxt-folder/my-ccxt-program.js` for example).

5. Edit `YOUR_API_KEY` and `YOUR_SECRET` in that file for your keys

6. Run it:

```
# in my-ccxt-folder:
node my-ccxt-program.js
```

**Comment by bitcoinmeetups** [comment]
Yes, I am making a lot of notes and trying to learn everything I need to know to do the stuff I want to do. I prefer the one-liners but if I have to learn some additional programming I will consider doing it. I am kind of using CCXT to save time instead of learning the API or code scripts for every exchange so the more one-liners I can find, the better.

By the way I think it should be "true" instead of "True" in the example above if anyone is reading this.

And also the script worked, thank you for your useful feedback.

**Comment by JavierRSobrino** [comment]
> ```js
> // JavaScript
> 
> const ccxt = require ('ccxt')
> exchange = new ccxt.bitmex ({
>     'apiKey': 'YOUR_API_KEY',
>     'secret': 'YOUR_SECRET',
>     'enableRateLimit': true,
> })
> ;(async () => {
>     await exchange.loadMarkets ()
>     const positions = await exchange.private_get_position({ 
>         'filter': exchange.json({"isOpen":true, "symbol":"XBTUSD"})
>     })
>     console.log (positions)  // print out here, how you like
> }) ()
> ```

Would you please tell me if there is a way to translate symbols automatically to something the exchange can understand?
I'm using ccxt provided symbols, so if I put `BTC/USD` there, it doesn't work.
Thanks.

**Comment by kroitor** [comment]
> Would you please tell me if there is a way to translate symbols automatically to something the exchange can understand?

Of course! This is documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#methods-for-markets-and-currencies

```JavaScript
    await exchange.loadMarkets ()  // required before accessing markets, obviously
    const ccxtUnifiedSymbol = 'BTC/USD'
    const market = this.market (ccxtUnifiedSymbol)
    const exchangeSpecificMarketId = market['id'] // ←-------------+
    const positions = await exchange.private_get_position({ //     ↓ 
        'filter': exchange.json({"isOpen":true, "symbol":exchangeSpecificMarketId})
    })
```

**Comment by JavierRSobrino** [comment]
Thank you. Great support.
Is planned to integrate `private_get_position` into something more universal?

**Comment by kroitor** [comment]
> Is planned to integrate private_get_position into something more universal?

Yes: https://github.com/ccxt/ccxt/issues/6697
