### ISSUE TITLE
npm run build error (foreach)

### ISSUE THREAD

**Issue by caoshitong369** [ccxt/ccxt#6162]
Fatal error: Uncaught ErrorException: Invalid argument supplied for foreach() in /Users/a1/ccxt/ccxt/php/base/Exchange.php on line 1044 in /Users/a1/ccxt/ccxt/php/test/syntax.php:12
Stack trace:
#0 /Users/a1/ccxt/ccxt/php/base/Exchange.php(1044): on_error(2, 'Invalid argumen...', '/Users/a1/ccxt/...', 1044, Array)
#1 /Users/a1/ccxt/ccxt/php/base/Exchange.php(1019): ccxt\Exchange->define_rest_api(Array, 'request')
#2 /Users/a1/ccxt/ccxt/php/test/syntax.php(21): ccxt\Exchange->__construct(Array)
#3 {main}
  thrown in /Users/a1/ccxt/ccxt/php/test/syntax.php on line 12

**Comment by urvishp80** [comment]
How did you fix this?

**Comment by kroitor** [comment]
@urvishp80 i'm not sure how exactly the author resolved it, but I think it most likely was a typo or a wrong format in one of the `describe()` fields.

**Comment by caoshitong369** [comment]
@kroitor Sorry, let me fix it
