### ISSUE TITLE
[coinbasepro] market order not 100% filled - is this normal?

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6165]
I found this market order that is closed but not 100% filled.  Is this expected?  Or are we parsing incorrectly?

```
// the order
{
  "id": "x7",
  "info": {
    "id": "x",
    "size": "0.00181765",
    "product_id": "BTC-USDC",
    "side": "buy",
    "funds": "15.9706678100000000",
    "type": "market",
    "post_only": false,
    "created_at": "2019-11-08T13:39:56.882321Z",
    "done_at": "2019-11-08T13:39:56.888Z",
    "done_reason": "filled",
    "fill_fees": "0.0798529641920000",
    "filled_size": "0.00181306",
    "executed_value": "15.9705928384000000",
    "status": "done",
    "settled": true
  },
  "timestamp": 1573220396882,
  "datetime": "2019-11-08T13:39:56.882Z",
  "status": "closed",
  "symbol": "BTC/USDC",
  "type": "market",
  "side": "buy",
  "cost": 15.9705928384,
  "amount": 0.00181765,
  "filled": 0.00181306,
  "remaining": 0.000004590000000000063,
  "fee": {
    "cost": 0.079852964192,
    "currency": "USDC"
  }
}
```

```
// the trade
{ id: '845193',
  order: 'x',
  info:
   { created_at: '2019-11-08T13:39:56.888Z',
     trade_id: 845193,
     product_id: 'BTC-USDC',
     order_id: 'x',
     user_id: 'x',
     profile_id: 'x',
     liquidity: 'T',
     price: '8808.64000000',
     size: '0.00181306',
     fee: '0.0798529641920000',
     side: 'buy',
     settled: true,
     usd_volume: '15.9705928384000000' },
  timestamp: 1573220396888,
  datetime: '2019-11-08T13:39:56.888Z',
  symbol: 'BTC/USDC',
  type: undefined,
  takerOrMaker: 'taker',
  side: 'buy',
  price: 8808.64,
  amount: 0.00181306,
  fee: { cost: 0.079852964192, currency: 'USDC', rate: 0.005 },
  cost: 15.9705928384 }
```

**Comment by kroitor** [comment]
@npomfret 

> I found this market order that is closed but not 100% filled.

That's pretty much expected with many of your orders. In most cases the exchange engine can't guarantee to fill up 100% of the ordered amount. 

```
    "status": "done",
```

↑ We're using this status.

> Or are we parsing incorrectly?

That is correctly parsed )

**Comment by kroitor** [comment]
@npomfret let me know if the above does not answer the question.

**Comment by npomfret** [comment]
@kroitor but this is a market order.  I've executed an awful lot of them and this is the first I've seen that isn't 100% filled.

**Comment by kroitor** [comment]
@npomfret if a market order is almost-fully-matched with an existing limit order from the orderbook, there may be an outstanding residue that is less than the dust threshold or min amount required to generate another match. Thus, a market order can remain "almost filled" in certain cases, depending on how exactly it crossed the orderbook, on the market conditions at that time and on the exchange rules, that can also change over time. You might want to fetch the trade history and match the trades with the order in question to investigate further.

**Comment by brandsimon** [comment]
This can also happen if there is not enough volume at the exchange at all.
That is why exchanges usually dont promise to execute stop-loss orders.
