### ISSUE TITLE
[cex] orders don't have a type, but we can figure it out

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6171]
order type (limit/market) is missing in the cex responses.  We can infer it from the presence of a price field.

**Comment by npomfret** [comment]
https://github.com/ccxt/ccxt/pull/6172

**Comment by kroitor** [comment]
@npomfret it may be easier to push the PRs directly in the future, some edits don't really require a new issue, just in case that helps save you some time. Thx, as always!
