### ISSUE TITLE
binance create_order python

### ISSUE THREAD

**Issue by macordalfy** [ccxt/ccxt#6177]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

- OS: linux
- Programming Language version: python
- CCXT version: latest (installed today)
- Exchange: Binance
- Method: create_order

I keep getting this error using binance create_order:

binance {"code":-1106,"msg":"Parameter 'quantity' sent when not required."}

Please help

**Comment by kroitor** [comment]
@macordalfy i

Plz read this: https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

In order to be able to help you we need:

1. your code to reproduce the issue, including the instantiation
2. your verbose request/response

**Comment by kroitor** [comment]
@macordalfy let us know if you have a followup on this, closing this issue for now, if you don't mind. Feel free to reopen it if needed or just ask further questions, if any.
