### ISSUE TITLE
Bittrex exchange.withdraw "SyntaxError: invalid syntax"

### ISSUE THREAD

**Issue by ELHARAKA** [ccxt/ccxt#6180]
I can't perform withdraw option, tried many times but keep getting error "SyntaxError: invalid syntax""

`>>> bittrex = ccxt.bittrex({
... 'apiKey': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
... 'secret': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
... })
>>> exchange_id = 'bittrex'
>>> exchange_class = getattr(ccxt, exchange_id)
>>> exchange = exchange_class({
... 'apiKey': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
... 'secret': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
... 'timeout': 30000,
... 'enableRateLimit': True,
... })
>>> exchange.withdraw(BTC, 0.03, 18xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxF, tag=None, params={})
  File "<stdin>", line 1
    exchange.withdraw(BTC, 0.03, 18xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxF, tag=None, params={})
                                                                                                                ^
SyntaxError: invalid syntax`

- OS: WIN10 64bit
- Programming Language version: Python37
- CCXT version: Latest Updated today.
- Exchange: Bittrex
- Method: exchange.withdraw(code, amount, address, tag=None, params={})

**Comment by kroitor** [comment]
@ELHARAKA you have Python syntax errors in your code: 

```Python
exchange.withdraw(BTC, 0.03, 18xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxF, tag=None, params={})
```

↑ The currency code and the address argument to that call should be strings, as explained in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#withdraw

I suggest that you read the entire Manual from top to bottom and then check out the examples here:

- https://github.com/ccxt/ccxt/tree/master/examples/py

Hope that answers your question.

**Comment by ELHARAKA** [comment]
Got it, Fixed, Thank you :)
