### ISSUE TITLE
What is the Code for USDT-ERC20 

### ISSUE THREAD

**Issue by stephencostiniano** [ccxt/ccxt#6184]
- OS: Windows 10
- Programming Language version: Python 3.7.4
- CCXT version: 1.19.54
- Exchange: Okex
- Method: fetchDeposit()

Hello can I ask what would be the currency code when I will withdraw USDT-ERC20 in Okex because If I try to use the normal 'USDT' I get an OMNI USDT Address, on the other hand, Binance automatically displays ERC-20 Token address using the same 'USDT' currency code

**Comment by kroitor** [comment]
@stephencostiniano hi! First of all, is this a question about fetching a deposit address or a question about withdrawing? Have you tried withdrawing USDT to an ETH address (ERC20) ? (I'd recommend to test with a small amount).

**Comment by stephencostiniano** [comment]
for fetching a deposit address since I can only view my Omni Address. In Regards to withdrawing, I'll try using an ERC20

**Comment by stephencostiniano** [comment]
@kroitor I tried withdrawing in Binance to my Okex USDT-ERC20 I got an error 

Error:
ccxt.base.errors.ExchangeError: binance {"msg":"You don't have permission.","success":false}

Code:
def request_withdrawal(self, currency, amount, deposit_address):
self.binance.withdraw(currency, amount, deposit_address, tag=None, params={})

**Comment by kroitor** [comment]
@stephencostiniano first of all, it was not clear from the initial description which exchange is in question. You've mentioned OKEX, but now you're trying Binance. I thought, you're trying to withdraw from OKEX initially.

Anyways, the error you see with Binance says that you don't have the permission to withdraw with that key:

```
{"msg":"You don't have permission.","success":false}
```

You should check your permissions for that API key pair with Binance website.

After you fix your permission issue, please, read the following:

- https://binance-docs.github.io/apidocs/spot/en/#all-coins-39-information-user_data

↑ Binance requires a `network` extra param, if you want to specify which network to withdraw-to, otherwise it will use the default network for the currency you specified.

After that, you should also read the Manual on [overriding API params](https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params).

Thus, to withdraw to a USDT-ERC20 address from Binance (having keys with proper permissions), you do the following:

```Python
exchange_id = 'binance'
exchange_class = getattr(ccxt, self.exchange_id)
exchange = self.exchange_class({
    'apiKey': KEYS.public_key_binance,
    'secret': KEYS.private_key_binance,
    'timeout': 1000,
    'enableRateLimit': True,
    'verbose': True,
})

currency = 'USDT'
amount = YOUR_AMOUNT
address = 'YOUR_ADDRESS'
tag = None
params = {
    'network': 'ETH',  # ERC20
}

exchange.withdraw(currency, amount, address, tag, params)
```

Let me know if the above does not help, or does not answer the question.

**Comment by stephencostiniano** [comment]
Hello sorry for the confusion still having a problem with the permission I'm using a new key pair that enables the withdrawal function maybe there is a problem in Binance

**Comment by kroitor** [comment]
@stephencostiniano have you checked your daily withdrawal limit? 

See this duplicate issue: https://github.com/ccxt/ccxt/issues/6017#issuecomment-545419547

↑ It does work for other users...

So, this is most likely an issue with permissions on your key, or some restrictions related to IP addresses bound to that key, or a withdrawal limit or some other kind of limit on your account. Unfortunately, without accessing your account, we can't really help you much with resolving the permission issue – I suggest that you browser Binance's website for clues, or, alternatively, you can open a ticket with their tech support if you are confident that the permission should be granted in your case.

If you manage to resolve this, please post your solution here, we will be happy for all feedback.

**Comment by stephencostiniano** [comment]
@kroitor  It's kinda weird I tried writing a withdraw function and using the same keys and It went thru.

`def withdraw():
    PATH = '/sapi/v1/capital/withdraw/apply'
    timestamp = int(time.time() * 1000)
    params = {
        'coin':'USDT',
        'network': 'TRX',
        'address': 'My_Address',
        'amount': 1.0,
        'timestamp':timestamp
    }

    query_string = urlencode(params)
    params['signature'] = hmac.new(SECRET_KEY.encode('utf-8'), query_string.encode('utf-8'), hashlib.sha256).hexdigest()

    # Execute
    url = urljoin(BASE_URL, PATH)
    r = requests.post(url, headers=headers, params=params)

    if r.status_code == 200:
        data = r.json()
        print(json.dumps(data, indent=2))
    else:
        raise BinanceException(status_code=r.status_code, data=r.json())`

**Comment by kroitor** [comment]
@stephencostiniano does it still fail with the CCXT's withdraw? If it does, can you plz paste your verbose request/response for the failing call? We don't need your keys, but it would be great if you could check that you're indeed using the proper keys with CCXT (that should be clear from the verbose output). We need to see the verbose output format (you can hide the credentials, but we can't use them anyways).

```
exchange_id = 'binance'
exchange_class = getattr(ccxt, self.exchange_id)
exchange = self.exchange_class({
    'apiKey': KEYS.public_key_binance,
    'secret': KEYS.private_key_binance,
    'timeout': 1000,
    'enableRateLimit': True,
})

exchange.load_markets()  # preload markets first
exchange.verbose = True  # set verbose mode before issuing the request

currency = 'USDT'
amount = YOUR_AMOUNT
address = 'YOUR_ADDRESS'
tag = None
params = {
    'network': 'ETH',  # ERC20
}

exchange.withdraw(currency, amount, address, tag, params)
```

**Comment by stephencostiniano** [comment]
@kroitor I found the culprit one of my imports is redirecting on my old set of keys I'm so sorry I saw in the verbose that it was publishing a different key. Thank you so much!

**Comment by kroitor** [comment]
@stephencostiniano happy to know that you have it resolved ) Cheers! )
