### ISSUE TITLE
DAI vs SAI

### ISSUE THREAD

**Issue by pauletoshi** [ccxt/ccxt#6185]
- CCXT version: latest
- Exchange: All exchanges

Hi, since the rebranding of DAI to SAI of MakerDao most exchanges have done the rebranding. I think ccxt should change the naming of DAI 1.0 to SAI and leave DAI to the new asset, otherwise it will get very confusing in the future. thoughts?

**Comment by kroitor** [comment]
Hi! We usually do not hardcode those symbols, they are taken from the exchanges, as explained in the Manual here: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids. So, if the exchange has updated the symbol for DAI to SAI – that should be automatically updated with the exchanges that do serve that info from the API directly in real time. Hope that answers your question. Let us know if you have any difficulties with it or with some particular exchange.
