### ISSUE TITLE
SouthXchange cancel_order not returning content-type header

### ISSUE THREAD

**Issue by inuitwallet** [ccxt/ccxt#6186]
Hi,

First off thank you for creating ccxt, it really is very useful.
I've hit an issue using the python version on SouthXchange.
I'm using ccxt 1.19.89 (latest at time of writing).
The issue comes from the Header check in the `is_text_response()` method on line `608` of [base/exchange.py](https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L608).
The check looks to see if the Content-Type header starts with '/text'.
Unfortunately the response from SouthXchange (via CloudFlare) doesn't seem to contain a Content-Type header.
This is the header response I am getting:
```
{'Date': 'Mon, 25 Nov 2019 22:51:07 GMT', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=xxxxxxx; expires=Wed, 25-Dec-19 22:51:07 GMT; path=/; domain=.southxchange.com; HttpOnly', 'Cache-Control': 'no-cache', 'Pragma': 
'no-cache', 'Expires': '-1', 'X-AspNet-Version': '4.0.30319', 'X-Powered-By': 'ASP.NET', 'X-Frame-Options': 'sameorigin', 'X-XSS-P
rotection': '1; mode=block', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Content-Type-Options': 'nosnif
f', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expec
t-ct"', 'Server': 'cloudflare', 'CF-RAY': 'xxxxxxx'}
```
The check in the `is_text_response()` method does this:
`return headers['Content-Type'].startswith('text/')` 
which blows up as the Content-Type key doesn't exist in the header dict.

I've changed this locally to:
`return headers.get('Content-Type', '').startswith('text/')` 
and that seems to work fine and allows me to cancel orders.
I haven't tested other methods fully though so I'm unsure if this will have bad, knock-on effects for other methods or exchanges? 

Is this a known issue with Cloudflare fronted exchanges? 
Is my change safe? If it is, I'm happy to submit a PR (I'll have to read up on the Contribution guide though).

**Comment by kroitor** [comment]
Hi!

Thx for a thorough report!

> Is this a known issue with Cloudflare fronted exchanges?

Not really, it was unknown until you reported it ) But now it's a known one )

> Is my change safe? 

Yes, if I understood the question correctly.

> If it is, I'm happy to submit a PR (I'll have to read up on the Contribution guide though).

I've already added a fix to it, and the new build will arrive in 15 minutes. Let us know if you have any difficulties with version 1.19.

We will be happy to see PRs and contributions from you in the future, though! ) Thank you!

**Comment by inuitwallet** [comment]
Thank you for such a prompt response. I'll give the new build a thorough test and report back.
