### ISSUE TITLE
Bitfinex: parse_trade bug

### ISSUE THREAD

**Issue by nmiculinic** [ccxt/ccxt#619]
This is example bitfinex trade:
```
 {'amount': '0.xxx',
  'fee_amount': '-0.xxxx',
  'fee_currency': 'BCH',
  'order_id': <redacted>,
  'price': '3.14xxxx',
  'tid': <redacted>,
  'timestamp': '15108xxxx.0',
  'type': 'Buy'}]
```

This issue in parse_trade function as assuming some things are floats, and not strings:

Instead of:
```python
    def parse_trade(self, trade, market):
        timestamp = trade['timestamp'] * 1000
        return {
            'id': str(trade['tid']),
            'info': trade,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'symbol': market['symbol'],
            'type': None,
            'side': trade['type'],
            'price': float(trade['price']),
            'amount': float(trade['amount']),
        }
```

have:
```python
    def parse_trade(self, trade, market):
        timestamp = float(trade['timestamp']) * 1000
        return {
            'id': str(trade['tid']),
            'info': trade,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),  # I'm not sure how you handle this miliseconds/etc;
            'symbol': market['symbol'],
            'type': None,
            'side': trade['type'].lower(),
            'price': float(trade['price']),
            'amount': float(trade['amount']),
        }
```

Because you get ugly bug:
```
  File "/home/lpp/Desktop/fino/.venv/lib/python3.6/site-packages/ccxt/base/exchange.py", line 575, in iso8601
    utc = datetime.datetime.utcfromtimestamp(int(round(timestamp / 1000)))
```

**Comment by nmiculinic** [comment]
Also this change should handle None type, which is missing for no good reason

**Comment by nmiculinic** [comment]
Also side should be lowercase as per unified documentation

**Comment by nmiculinic** [comment]
Don't have parseInt, since it's a float with .0 at the end.

**Comment by kroitor** [comment]
@nmiculinic it converts to int in JS, same as int(...) in Python.

**Comment by nmiculinic** [comment]
ValueError: invalid literal for int() with base 10: '1222.1'
>>> int("1222.1")


I know....but the timestamps is float as a string, that's why it's going to fail

**Comment by kroitor** [comment]
Ah... forgot about Python. Somehow, I thought it does work, sorry.

**Comment by nmiculinic** [comment]
Everything works in JS. https://www.youtube.com/watch?v=et8xNAc2ic8  have fun :)

**Comment by kroitor** [comment]
@nmiculinic 

Btw, https://github.com/brianleroux doesn't expose any significant code (as far as I see)... He has a lot of dummy projects, one-liner utils and very basic examples. That corresponds exactly to what he is talking about, and I guess, because of that, he is very good in writing small snippets or editing other small snippets. It may be easy to find ugliness in other peoples' code. He may be a good talker, he may be able to hold the audience's attention, he may have the necessary charisma, but most of the time those guys fail to actually deliver. I also wonder if he could make laughs of his own 5-10-year old code.

**Comment by nmiculinic** [comment]
Interesting, I never thought of that. Since I'm mostly removed from front-end/JS ecosystem I'm not familiar with who's who. 

True, writing big stable code base is hard, many things can go wrong when you're reaching enough complexity scale --> programming language design included. Lately, I've been adding type hinting in all my code and making classes (fancy C plain-old-data structs) instead of dictionaries, thus making my autocompleter happier and static code analysis better.
