### ISSUE TITLE
Filter methods on tickers objects

### ISSUE THREAD

**Issue by christiandbf** [ccxt/ccxt#620]
This is a proposal to add this method to the object received using:

```
exchange.fetchTickers()
```

So by that way you can make things like this:

```
let tickers = exchange.fetchTickers()
tickersVolumeAbove50 = tickers.filter((ticker) => ticker.quoteVolume > 50 )
```

It could be a custom method, similar to the Array.filter method on JavaScript.

**Comment by kroitor** [comment]
Hi! 

Sorry, but we don't think this should be in the library. Note the library is in three languages, not just JS, so we can't add methods anywhere as we want, each change is syntactically critical for 3 languages, whereas your proposal only accounts for one single language of JavaScript. The other concern on this is that we mostly want to return flat JSON types. Yet still you can always do that in userland code. 

You might also want to read the following:
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

Thank you anyway for your involvement and participation! We really appreciate it and we would love to receive more proposals from you in future.
