### ISSUE TITLE
[binance]  BCHABC -> BCH change

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6201]
> Binance has successfully updated the Bitcoin Cash ticker from BCHABC to BCH. All previous BCHABC trading pairs have been removed and trading for BCH/BTC, BCH/USDT, BCH/USDC, BCH/TUSD, BCH/PAX, and BCH/BUSD is now open.

**Comment by MaticConradi** [comment]
Looking forward to using `BCH` and `BSV` instead of `BCHABC` and `BCHBSV`

**Comment by kroitor** [comment]
@MaticConradi those symbols have been mapped to BCH and BSV in CCXT a long time ago ) So you can already use BCH and BSV with Binance and CCXT )

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
