### ISSUE TITLE
PHP create_order - Rounds the price instead of cutting

### ISSUE THREAD

**Issue by StasToken** [ccxt/ccxt#6206]
OS: Ubuntu 18.04
Programming Language version: php 7.2
CCXT version: LAST (27.11.2019 download master)
Exchange: binance
Method: create_order

```
<?php
include 'ccxt.php';

date_default_timezone_set('UTC');

$id = 'binance'; // edit this line

// ----------------------------------------------------------------------------

// instantiate the exchange by id
$exchange_class = '\\ccxt\\' . $id;
$exchange = new $exchange_class(array(
    'apiKey' => '', // edit this line
    'secret' => '', // edit this line
    'enableRateLimit' => true,


));
$exchange->create_order('BTC/USDT', 'LIMIT', 'SELL', 0.00299999,9999.9999);
```
Hello why variable price **rounded off** and not trimmed as is done in the case of quantity (which is essentially correct) - in my opinion the price should be cut off and not rounded ?!
Is this a mistake or should it be so?
[img](https://ibb.co/nnDJKDj)

**Comment by kroitor** [comment]
> Is this a mistake or should it be so?

That is by design. The price gets rounded to the closest acceptable precision, the amount gets truncated. This is common with most of exchanges. Hope that answers the question.

**Comment by StasToken** [comment]
Thanks I had to clarify this!
