### ISSUE TITLE
okex3.py :: parse_trade transpilation issue

### ISSUE THREAD

**Issue by furmanOFF** [ccxt/ccxt#6207]
- Programming Language version: python 2.7
- CCXT version: 1.20.15
- Exchange: OKEx
- Method: parse_trade

https://github.com/ccxt/ccxt/blob/e6f94f592add95f7c45f18ce6e9e77b70212f2c6/python/ccxt/okex3.py#L938 Returns `False`, definitely incorrect transpilation from
https://github.com/ccxt/ccxt/blob/e6f94f592add95f7c45f18ce6e9e77b70212f2c6/js/okex3.js#L942

**Comment by kroitor** [comment]
@furmanOFF thx for reporting! Fixed in 1.20.16, the new build will arrive in 15 minutes. Let us know if you have any other difficulties with it.
