### ISSUE TITLE
ZB exchange fee error

### ISSUE THREAD

**Issue by hunsnowboarder** [ccxt/ccxt#622]
First of all, of course, as always thanks so much for putting a lot of effort into this exceptional, tremendously helping tool! Thank you so much!

Issue: 
When I try to call the calculatefee in case of ZB I get a keyerror: 'taker'

Code:
```
zb.loadMarkets()
takerOrMaker = 'taker' # or 'maker' if you are creating a market-making order
print(zb.calculate_fee ("BTC/USDT", "limit", "sell", 12, 0.06917684, takerOrMaker))
```

Error:
--> 857             'quote': self.markets[symbol][fee],
KeyError: 'taker'

Also when I call zb.fees I get empty dictinaries.
Thank you!

**Comment by kroitor** [comment]
The calculate_fee is currently in experimental state, therefore we didn't document it just yet. The ZB exchange was added a few days ago, some things may still be missing here and there, but we will implement those as well. Please, standby for more updates on this. Thx for reporting!

**Comment by kroitor** [comment]
This issue is fixed in current up to date version of ccxt. Cheers!
