### ISSUE TITLE
How to get all private endpoints to Binance Futures API

### ISSUE THREAD

**Issue by Gennttii** [ccxt/ccxt#6222]
Hi, 

I need to know the entry price of my position.

I have this endpoint 
`await binance.privateGetAccount ( )`
It shows symbol, initialMargin, maintMargin, unrealizedProfit, initialMargin, positionInitialMargin, openOrderInitialMargin but no Entry Price of the position..

Where can I find all private endpoints , and the exact endpoint that shows the EntryPrice of the position..

Thanks

**Comment by kroitor** [comment]
> Where can I find all private endpoints , and the exact endpoint that shows the EntryPrice of the position..

```
node examples/js/cli binance api
```

- https://github.com/ccxt/ccxt/wiki/Manual#api-methods--endpoints

> For a full list of accepted method parameters for each exchange, please consult [API docs](https://github.com/ccxt/ccxt/wiki/Manual#exchanges).

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

> `api`: An associative array containing a definition of all API endpoints exposed by a crypto exchange. The API definition is used by ccxt to automatically construct callable instance methods for each available endpoint.

- https://binance-docs.github.io/apidocs/futures/en/#change-log

Let me know if the above does not answer the question )

**Comment by Gennttii** [comment]
I looked at binance APi,  I need to get this endpoint `/fapi/v1/positionRisk`

**Comment by Gennttii** [comment]
`await binance.privateGetAccount ( )`  connects to /fapi/v1/account but,
`await binance.privateGetpositionRisk ( )`  doesn't connect to /fapi/v1/positionRisk

**Comment by kroitor** [comment]
@Gennttii you want to call `binance.privateGetPositionRisk` with the most recent version of CCXT, make sure you update it to 1.20.36 or later.

**Comment by Gennttii** [comment]
Hi, thanks for the reply but I updated and still the same error:

`TypeError: binance.privateGetPositionRisk is not a function`

**Comment by kroitor** [comment]
@Gennttii pardon, there's a typo in my previous answer, should be `binance.fapiGetPositionRisk ()`

**Comment by Gennttii** [comment]
@kroitor That gives the same error , not a function, but I tried this: 
`await binance.fapiPrivateGetPositionRisk ( )`

And this gives me 
`binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}`

But my API keys are okay, I can access `await binance.privateGetAccount ( )` with the same configuration

**Comment by kroitor** [comment]
@Gennttii yes, you're right `fapiPrivateGetPositionRisk()`. The error you get means that you have to  do one of the following:
1. either create a futures trading account with Binance website if you haven't created it yet
2. or create a new api key, because futures will be disabled by Binance for all api keys that were created before the futures account

**Comment by Gennttii** [comment]
My configuration is for binance futures testnet :
```
const binance  = new ccxt.binance ({ 
    options: { defaultMarket: 'futures' }, 
    apiKey: apiKeys[2], 
    secret: apiSecret[2],
    'timeout': 30000, 
    'enableRateLimit': true, 
    'urls': {
        'api': {
           // 'public': 'https://fapi.binance.com/fapi/v1',
            'public': 'https://testnet.binancefuture.com/fapi/v1',
            'private': 'https://testnet.binancefuture.com/fapi/v1'
        }
    } 
});
```

And it works with other endpoints except this one `fapiPrivateGetPositionRisk()` , idk if it works for this one with real futures ..
I can't change API keys in testnet !

**Comment by kroitor** [comment]
@Gennttii the config should be a bit different in this case:

```JavaScript
const binance  = new ccxt.binance ({ 
    options: { defaultMarket: 'futures' }, 
    apiKey: apiKeys[2], 
    secret: apiSecret[2],
    'timeout': 30000, 
    'enableRateLimit': true, 
    'urls': {
        'api': {
           // 'public': 'https://fapi.binance.com/fapi/v1',
            'fapiPublic': 'https://testnet.binancefuture.com/fapi/v1', // ←------  fapi prefix here
            'fapiPrivate': 'https://testnet.binancefuture.com/fapi/v1', // ←------  fapi prefix here
        }
    } 
});
```

Let me know if that works for you.

**Comment by Gennttii** [comment]
Thanksss man soo much , you are a lifesaver !

**Comment by fabriciomirandabr** [comment]
Thank you, finally I found the configuration for Binance futures that works!

**Comment by Gennttii** [comment]
Hi @kroitor , did you change anything in this configuration? Cause I am getting error when trying to get `fapiPrivateGetPositionRisk ` 
`binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
`

**Comment by kroitor** [comment]
@Gennttii hi! Nope, everything is the same as it was before in that regard. You might want to check your credentials in verbose mode.

**Comment by Gennttii** [comment]
Its working now sorry
Now I need to change leverage , is there any way? I have this endpoint for Bitmex `privatePostPositionLeverage({symbol: 'BTCUSDT', leverage: 30})` but its not working with Binance Futures..

**Comment by kroitor** [comment]
@Gennttii 

> Now I need to change leverage , is there any way?

Yep, it was answered here: 

- https://github.com/ccxt/ccxt/pull/5907#issuecomment-548153010
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
