### ISSUE TITLE
CoinTiger delisting

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#6223]
We will be delisting CoinTiger from the CCXT library within the next 24 hours. If you wish to keep using CoinTiger via the CCXT library, you can do so by keeping the current version of CCXT.

CCXT has received reports from multiple users that CoinTiger has been freezing funds and not allowing withdrawals. Explanations from CoinTiger have varied, including too many withdrawals, too many order cancellations, or to quote their support chat directly 

> It is suspected of improper arbitrage, and a large number of withdrawal behavior, constitute a false trading fact. According to the relevant regulations of the exchange, the transaction and withdrawal of your account will be frozen.

When asked for an explanation of the _"relevant regulations_", CoinTiger has not responded. When pushed, CoinTiger has allowed some customers to withdraw their initial deposits, but not any trading profits generated while the exchange was used. A quote from an email sent by business@cointiger.com that was shown to CCXT makes their position clear: 

> You’re not allowed to take the left profit, and your account is permanently frozen. This part is clearly stated in our user agreement. No further negotiation.

When reviewing this case, we noticed that CoinTiger updated their API document on October 17, 2019. [This GitHub revision page](https://github.com/CoinTiger/api-docs-en/wiki/HOME/0d936b2967adbaf3980139eb27de70f062a5f0d2) shows the documents until the October 17 revision. [This GitHub revision page](https://github.com/CoinTiger/api-docs-en/wiki/HOME/92d88bfcc43c87719e7cfe4ba5af8db8c4306b64) shows the text that CoinTiger added on October 17. The relevant changes were as follows. You can also see them directly using GitHub’s own compare feature. Both the English and Chinese versions of the API docs were updated on the same day in the same way.

> **API Trading Restriction:**
> 1. If a user has a huge amount of order cancellations(≥300 orders per day) detected by CoinTiger system, CoinTiger will restrict the user's API orders.
> 2. Your assets will be frozen by CoinTiger if your account has malicious actions.
> 3. CoinTiger reserves the right to freeze suspicious users' account at all times and to pursue their legal responsibility.

No announcement was made of these changes and no changes were made to the Terms and Conditions, but CoinTiger appears to be using these changes to the API docs as an excuse to freeze users' funds. We will also note that CoinTiger did not restrict API access until it froze the accounts.

Until CoinTiger makes its regulations clear and informs its users about changes before they are made, we cannot in good faith include them in our library. We look forward to them restoring access to users' funds and to clarifying their business practices. Until then we cannot support CoinTiger and caution our users about the safety of any funds on the CoinTiger exchange.

**Comment by jepoy07** [comment]
Yeah my account frozen 1500$   accusing of arbitrage even not use manual trade    must do action cointiger exchange tey doing sabotage if they froze account must delete it in data base not to hold there in exchange very wise cointiger

**Comment by kroitor** [comment]
- https://www.publish0x.com/crypto-project/cointiger-exchange-big-revelation-about-frozen-accounts-sad-xokjlm

**Comment by 1709co** [comment]
https://supportproton.zendesk.com/hc/en-us/articles/360032429192--Aug-21-An-Official-WARNING-on-the-recent-of-Illegal-Stealing-at-CoinTiger-Exchange

**Comment by 1709co** [comment]
Here's a quote from the business@cointiger.com email address to me.

> Your total deposit is only 0.964ETH, and your total withdrawal which is completed is 0.944ETH plus 1.133BTC, that means we have already approved your withdrawal of your principal and part of your profit. You’re not allowed to take the left profit, and your account is permanently frozen. This part is clearly stated in our user agreement. No further negotiation. 

Our reply was to show them screenshots from their own website that showed us depositing 75 LTC. We also pointed out that we actually only deposited 0.919 ETH, not the amount they said. We also pointed out that we had several hundred USD in referral credits as well. This was their response:

> Yes, your deposit was 74.997LTC + 0.964ETH in total, but your total withdrawal is 1.1336BTC + 0.944ETH, which already exceeded your original deposit. So there is nothing we owe to you. 

It is clear that they are just making things up as they go along. Nobody should deposit anything there and everyone should ask to get their money out now.

**Comment by JackDaniels45** [comment]
Wow this sounds exactly like Mandala Exchange and they are ccxt certified!!

**Comment by kroitor** [comment]
@JackDaniels45 we are investigating all such cases and a corresponding action will be taken, so if you have more details on a similar misconduct from other exchanges, i'd suggest to post your info in the matching issues, for example: https://github.com/ccxt/ccxt/issues/5787. Thx for the feedback in advance!

**Comment by kroitor** [comment]
CoinTiger is now officially delisted as of version 1.20.39, until we see a resolution of this issue.

- https://twitter.com/ccxt_official/status/1202800398664445952

**Comment by 1709co** [comment]
Isn't certification about API quality, not company quality?

**Comment by kroitor** [comment]
@1709co

> Isn't certification about API quality, not company quality?

That's correct: https://github.com/ccxt/ccxt/wiki/Certification

**Comment by jepoy07** [comment]
Thanks for help hope to solve this and widraw my funds in cointiger

**Comment by ndubel** [comment]
I also was robbed by Cointiger, good idea to delist them

**Comment by frosty00** [comment]
> users' funds

impressive )

**Comment by jepoy07** [comment]
Put them in jail sir

**Comment by PP150924** [comment]
> @1709co
> 
> > Isn't certification about API quality, not company quality?
> 
> That's correct: https://github.com/ccxt/ccxt/wiki/Certification

คุณไม่รู้กันหรือแกล้งโงมันคือไอ้ชั่วจอมเลวทรามแฮกเกอร์กระจอกๆถ้าแค่นี้ฝ่ายสนับสนุนยังกันไม่ได้ฉันว่าพวกคุณปิดบริษัทไปสะ

**Comment by bobbytaxbit** [comment]
I appreciate the willingness to take a stand against what appears to be criminal behavior.

However, we need to pull transactions via API for our user's to file their taxes. Is there anyway you would consider relisting CoinTiger but restricting available endpoints to READ/Trading History only? Thanks!

**Comment by kroitor** [comment]
@bobbytaxbit you can still use the old implementation if you restore it for yourself using a simple one-liner git command from the commit history of this repository, as shown by @frosty00 above, but we cannot relist CoinTiger at this time, sorry.

**Comment by jepoy07** [comment]
Cointiger scam many account froze
