### ISSUE TITLE
[poloniex] fetchOrders is misleading

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6227]
Poloniex Api only has a method for getting open orders (`privatePostReturnOpenOrders`, see: https://docs.poloniex.com/#private-http-api-methods).  

I think the ccxt implementation for `fetchOrders` and `fetchClosedOrders` should be removed and only `fetchOpenOrders` can be implemented.

**Comment by kroitor** [comment]
@npomfret i would agree on this one, emulating fetchOrders for it is an outdated approach. The proper approach is to have the methods mapped directly onto the list of API endpoints and provide enough metainfo for the user to decide. We will look into stripping it out.

**Comment by npomfret** [comment]
Ok.  And regarding fetchOrder (which currently uses the cache), this can be implemented using https://docs.poloniex.com/#returnorderstatus and https://docs.poloniex.com/#returnordertrades

**Comment by kroitor** [comment]
@npomfret unfortunately, fetchOrder cannot really be implemented without issuing two http calls or using the cache. But I still think that we need to remove it for consistency.

**Comment by kroitor** [comment]
@npomfret it was one of the biggest first issues and one of the biggest issues since the beginning of CCXT: https://github.com/ccxt/ccxt/pull/102

**Comment by npomfret** [comment]
Is it ok to issue two api calls?

**Comment by kroitor** [comment]
> Is it ok to issue two api calls?

Not really, we do as much as we can to avoid that throughout the lib. Only if we absolutely have to (for loading the markets, for example, or other _"cacheable"_ info). Two calls – is the last thing we would do, tbh, because that breaks rate limiting.

**Comment by npomfret** [comment]
Ok, so we just remove `fetchOrder` for now along with the others and keep `fetchOpenOrders` only?

**Comment by kroitor** [comment]
@npomfret i'd say we remove the emulation part from it, leaving just the true part. I need to review the docs once again to make sure that we can't implement fetchOrder otherwise somehow. Hope to get to it this weekend.

**Comment by npomfret** [comment]
I just noticed this as well: `'fetchOrderStatus': 'emulated'`.  What is the method `fetchOrderStatus` supposed to do?

**Comment by kroitor** [comment]
@npomfret some exchanges return the order status for an order id, but this is very rare. In many cases the status of the order (whether it's still open, closed, ever existed or whatever) – can be deduced from one of the endpoints. At this time it is emulated in the base class via a `fetchOrder()['status']` construct (put simply).

**Comment by npomfret** [comment]
I was doing some testing and I can't get `privatePostReturnOrderStatus` to return anything, have you used it?

**Comment by kroitor** [comment]
> I was doing some testing and I can't get privatePostReturnOrderStatus to return anything, have you used it?

The Polo API will only return the order info as long as it is not archived, and it gets archived really quickly. So, put simply, returnOrderStatus will return the order as long as it is open and maybe a bit longer, but then it will return "Order not found" afterwards as an indication that:
- the order is no longer open
- the order is probably archived, if it was seen in the open state previously

> (Also, shouldn't this result in an exception being thrown?)

Depends on how you look at it. If you consider how the the `.orders` cache works, like it is implemented now, then you can't just throw an exception in this case – you need to intercept it and make sure to update the cached order status accordingly and then return the corresponding updated order to the user. However, if you're cutting out the `.order` cache, then we could probably just throw an `OrderNotFound` from there (definitely not an `InvalidOrder`).

**Comment by npomfret** [comment]
Ok, so we can implement fetch order assuming it's not been archived, the docs say all the fields we need get returned:

            { result:
               { '6071071':
                  { status: 'Open',
                    rate: '0.40000000',
                    amount: '1.00000000',
                    currencyPair: 'BTC_ETH',
                    date: '2018-10-17 17:04:50',
                    total: '0.40000000',
                    type: 'buy',
                    startingAmount: '1.00000' } },
              success: 1 }

**Comment by npomfret** [comment]
To be clear - will you accept a PR that removes the cache from Poloniex and also remove the fetchOrder(s) methods?

**Comment by kroitor** [comment]
@npomfret yep! It would be great to save `fetchOrder` by implementing it with the returnOrderStatus endpoint, if possible.

**Comment by npomfret** [comment]
We can, but it'll only work for open orders.  I did some testing today and it looks like the exchange archives closed orders pretty much immediately.  Is it worth it?

**Comment by kroitor** [comment]
@npomfret in some cases we add `fetchOpenOrder` or `fetchClosedOrder` for that reason, but if you don't want to spend the time on it – nw, i'll add it if necessary. You're right on `fetchOpenOrders` – we can almost always get it from there.

**Comment by kroitor** [comment]
Continued here: https://github.com/ccxt/ccxt/pull/6239
