### ISSUE TITLE
fetchMyTrades() alternative

### ISSUE THREAD

**Issue by Fcl69** [ccxt/ccxt#623]
It looks like fetchMyTrades() is not a universal tool since quite a few of mine exchanges returns "fetch_my_trades() not implemented yet". I got it working for poloniex only.  Is there an alternative way to get my most recent trades and/or open&closed orders?

Sub-question:
>Recent Trades
>exchange.fetchMyTrades (symbol = undefined, since = undefined, limit = undefined, params = {})
What does "limit" mean here? Seems like it has no effect at all for me.

**Comment by xpl** [comment]
CCXT is still under active development and some methods for some exchanges may not have been implemented yet on our side... Regarding the `limit`, it limits the output to last N trades. Unfortunately, not all exchanges implement it.

**Comment by kroitor** [comment]
@Fcl69 as you may know, the private order API is not completely unified yet, therefore we don't have all fetchMyTrades implemented yet, that is currently available with several exchanges that expose `.hasFetchMyTrades = true`.

Until then you will need to use their custom methods for fetching the trade history, most of exchanges have that in their API, so you can call those methods just like you did with other custom methods already.

Current overview: 

<img width="1636" alt="screen shot 2017-11-18 at 00 22 30" src="https://user-images.githubusercontent.com/1294454/32982165-1b49d4d4-cc91-11e7-9ab9-39e0b526eca7.png">

We will be happy if you could help us implement the missing / remaining methods, your PRs and contributions are welcome! Hope it answers your question, in the meantime, I'm closing this issue, if you don't mind. Feel free to reopen it if necessary or ask questions.
