### ISSUE TITLE
Can't find reference in Python IDE

### ISSUE THREAD

**Issue by Jay54520** [ccxt/ccxt#6230]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version: Python
- CCXT version: 1.19.86
- Exchange:
- Method:

Can't find reference in Python IDE because the errors are generated by factory in `ccxt/base/errors.py`. 

Codes can still work because the errors exist but want this to be fixed.

![image](https://user-images.githubusercontent.com/13315364/70366612-967a8780-18d3-11ea-974a-fb799c2cee8e.png)

**Comment by kroitor** [comment]
Should be ok as of version 1.20.45 (it will arrive in 15 minutes). Thx to @frosty00 for fixing this.
@Jay54520 let us know if you have any other difficulties with it.
