### ISSUE TITLE
[binance] support the new `quoteOrderQty` option for orders

### ISSUE THREAD

**Issue by gpip** [ccxt/ccxt#6233]
Recently binance added a new option called "quoteOrderQty" as mentioned at https://github.com/binance-exchange/binance-official-api-docs/blob/master/CHANGELOG.md

Would be nice to have it here, for now I'm running a custom ccxt that allows me to override the `quantity` param with `quoteOrderQty` as they're mutually exclusive. The `amount_to_precision` can't be called as is because on BUY orders you would be on the other side of the book with `quoteOrderQty`

**Comment by kroitor** [comment]
Hi!

Does the following work for you:

```JavaScript
const symbol = 'ETH/BTC' // your symbol here
    , type = 'limit'
    , side = 'buy'
    , amount = 0 // will get overrided
    , price = 0.02 // your price here
    // overrides
    , quoteOrderQty = 1.2345 // your value here
    , params = {
        'amount': undefined,
        'quoteOrderQty': exchange.costToPrecision(symbol, quoteOrderQty),
    }

await binance.loadMarkets()
binance.verbose = true
const order = await binance.createOrder(symbol, type, side, amount, price, params)
console.log (order)
```

?

**Comment by kroitor** [comment]
Hi!

The support for `quoteOrderQty` has been added here: https://github.com/ccxt/ccxt/issues/6391

Thanks for your patience!
