### ISSUE TITLE
we need bybit

### ISSUE THREAD

**Issue by xiandong79** [ccxt/ccxt#6245]
- Exchange: Bybit

It has been 6 months since the first discussion about "add bybit into CCXT"!

**Comment by kroitor** [comment]
@xiandong79 

It would help if you could build this PR, test it and report bugs:

- https://github.com/ccxt/ccxt/pull/5985#issuecomment-557872822

**Comment by kroitor** [comment]
Bybit is now available in CCXT 1.24.4+ https://github.com/ccxt/ccxt/issues/6612
