### ISSUE TITLE
[kucoin] fetchOrder errors not being handled correctly

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6250]
I'm seeing this, despite this error (`order not exist`) being in the exceptions list.

```
BadRequest: order not exist.
    at kucoin.throwExactlyMatchedException (/usr/src/app/node_modules/ccxt/js/base/Exchange.js:515:19)
    at kucoin.handleErrors (/usr/src/app/node_modules/ccxt/js/kucoin.js:1599:14)
```

Perhaps it's the full stop at the end?

**Comment by kroitor** [comment]
@npomfret 

> Perhaps it's the full stop at the end?

100%

**Comment by npomfret** [comment]
Let's try adding a '.' first, and improve later?

**Comment by kroitor** [comment]
@npomfret i agree, just let me know if you wish to submit a PR for this

**Comment by npomfret** [comment]
https://github.com/ccxt/ccxt/pull/6251
