### ISSUE TITLE
[bitstamp] why is fetchOrder 'emulated'

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6252]
`fetchOrder` in bitstamp It looks like a proper implementation, why is it market as 'emulated'?

**Comment by kroitor** [comment]
I think this is a leftover from an earlier version.

**Comment by npomfret** [comment]
Or perhaps the order isn't fully formed?  Does that count as 'emulated'?

**Comment by kroitor** [comment]
> Does that count as 'emulated'?

Nope.

**Comment by npomfret** [comment]
ok, will do a PR now, thanks.

**Comment by kroitor** [comment]
> ok, will do a PR now, thanks.

No worries, I've already uploaded a fix ) The `'emulated'` value is only used in cased where one call is emulated via another endpoint for another call, if the endpoint in question is missing.

**Comment by npomfret** [comment]
Thanks!

Any objection to adding:

```
    async fetchOrderTrades (id, symbol = undefined, since = undefined, limit = undefined, params = {}) {
        const order = await this.fetchOrder (id, symbol, params);
        return order['trades'];
    }
```

?

**Comment by kroitor** [comment]
@npomfret thx to you for pointing it out!

No objections whatsoever ) We already have a `fetchOrderStatus` wrapper in the base class anyway.
