### ISSUE TITLE
Rightbtc API 404 Not Found 

### ISSUE THREAD

**Issue by enzesi** [ccxt/ccxt#6254]
Hi,

I am using latestest CCXT version and there is some error with rightbtc api urls.
Api should be 'api': 'https://api.rightbtc.com',
and here is the documentation: https://docs.rightbtc.com/api/rest_pub.html
and when I change to the correct api
the following error occurs.
![Screen Shot 2019-12-11 at 4 26 07 PM](https://user-images.githubusercontent.com/32287882/70661927-45e88e80-1c33-11ea-8386-7246b7479bb9.png)
 Unable to initialize markets. Reason: GET https://api.rightbtc.com/public/trading_pairs 404 Not Found

**Comment by kroitor** [comment]
@enzesi they have changed their API and just changing the base URL won't fix it, it has to be reimplemented: https://github.com/ccxt/ccxt/issues/5942 ← let us know if that does not answer the question.
