### ISSUE TITLE
bitmex fetch_ticker 'last' returns None

### ISSUE THREAD

**Issue by xgdgsc** [ccxt/ccxt#626]
Now `exchange.fetch_ticker('XBTZ17')` would return:
```
{'ask': 7840.0,
 'average': None,
 'baseVolume': 5292.645949190008,
 'bid': 7839.5,
 'change': None,
 'close': 7839.5,
 'datetime': '2017-11-18T08:15:29.232Z',
 'first': None,
 'high': 7855.0,
 'info': {'close': 7839.5,
  'foreignNotional': 40633463,
  'high': 7855,
  'homeNotional': 5292.645949190008,
  'lastSize': 999,
  'low': 7527.5,
  'open': 7781.5,
  'symbol': 'XBTZ17',
  'timestamp': '2017-11-19T00:00:00.000Z',
  'trades': 17589,
  'turnover': 529264594919,
  'volume': 40633463,
  'vwap': 7677.5432},
 'last': None,
 'low': 7527.5,
 'open': None,
 'percentage': None,
 'quoteVolume': 40633463.0,
 'symbol': 'XBTZ17',
 'timestamp': 1510992929232,
 'vwap': 7677.5432}
```

last field is None, is there a way to make it show last trade price?

**Comment by kroitor** [comment]
Hi! You can see BitMEX's own response, this section in your copied output:
```
 'info': {'close': 7839.5,
  'foreignNotional': 40633463,
  'high': 7855,
  'homeNotional': 5292.645949190008,
  'lastSize': 999,
  'low': 7527.5,
  'open': 7781.5,
  'symbol': 'XBTZ17',
  'timestamp': '2017-11-19T00:00:00.000Z',
  'trades': 17589,
  'turnover': 529264594919,
  'volume': 40633463,
  'vwap': 7677.5432}
```

That is a reply from BitMEX as is, non-edited. So, from it, you can see, that they only return lastSize, and do not return the lastPrice. Therefore I don't see a way to get the last traded price into a BitMEX ticker, unless you fetchTrades yourself and take the last price from there. Does this answer your question?

**Comment by kroitor** [comment]
If `close` == `last` for BitMEX we can set last = close. Would it solve the issue, what do you think?

**Comment by xgdgsc** [comment]
Maybe keep the current behavior to let users know the issue would be better.

**Comment by kroitor** [comment]
Ok, thx anyway for the feedback!
