### ISSUE TITLE
Btifinex fetchBalance not parsed correctly and issues with createOrder

### ISSUE THREAD

**Issue by brandonkimmmm** [ccxt/ccxt#6268]
The response for `fetchBalance` on both bitfinex and bitfinex2 are not parsed correctly and only returning the info data. When I call `createOrder`, it is telling me that I don't have enough balance to create the order even though I have enough funds.

I think it has to do with line 506 in `bitfinex.js`. The balanceType should be `deposit` instead of `exchange` since the response from bitfinex has type `deposit`. 

- OS: macOS Mojave 10.14.6
- Programming Language version: Javascript
- CCXT version: 1.20.75
- Exchange: Bitfinex
- Method: fetchBalance, createOrder

**Comment by kroitor** [comment]
> The response for fetchBalance on both bitfinex and bitfinex2 are not parsed correctly and only returning the info data.

We allow overrides, and by default we fetch the spot trading balance, as documented in the Manual.

Duplicates:

- https://github.com/ccxt/ccxt/issues/1207#issuecomment-357154252
- https://github.com/ccxt/ccxt/issues/601#issuecomment-345545702
- https://github.com/ccxt/ccxt/issues/879

↑ Let us know if the above does not answer the question.

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
