### ISSUE TITLE
Bit-z mistake

### ISSUE THREAD

**Issue by stdt99** [ccxt/ccxt#6271]
Hi, use python lib
ccxt 1.20.78

method: 
fetch_balance, create_limit_buy_order...

error: 
ccxt.base.errors.ExchangeError: GET https://apiv2.bit-z.pro/Market/symbolList

**Comment by kroitor** [comment]
Hi!

Thx for reporting!

I've uploaded a fix to it, and it should work with a new base url in version 1.20.79. Let me know if not.

Their base urls are listed out here:

- https://apidoc.bit-z.com/en/

> ```
> https://apiv2.bitz.com/Market/symbolList
> https://apiv2.bit-z.pro/Market/symbolList
> https://api.bitzapi.com/Market/symbolList
> https://api.bitzoverseas.com/Market/symbolList
> https://api.bitzspeed.com/Market/symbolList
> ```

Having version 1.20.79 (don't forget to update), for the future, if one of those urls goes down, you can change it like so:

```Python
import ccxt
exchange = ccxt.bitz({
    'hostname': 'apiv2.bitz.com',
    # 'hostname': 'apiv2.bit-z.pro',
    # 'hostname': 'api.bitzapi.com',
    # 'hostname': 'api.bitzoverseas.com',
    # 'hostname': 'api.bitzspeed.com',
})
```

The new build 1.20.79 will arrive in 15 minutes.

**Comment by stdt99** [comment]
it OK now
thanks a lot
