### ISSUE TITLE
Error while using Proxy Agent JS

### ISSUE THREAD

**Issue by cenyG** [ccxt/ccxt#6272]
- OS: darwin/mac
- Programming Language version: node.js 12.12.0
- CCXT version: 1.20.79
- Exchange: binance (any)
- Method: any

Hi, I'm trying to use proxy but have an error,

```
 ExchangeNotAvailable: binance GET https://api.binance.com/api/v3/exchangeInfo  The "options.agent" property must be one of type Agent-like Object, undefined, or false. Received type object
    at /Users/user/Projects/reports/node_modules/ccxt/js/base/Exchange.js:382:35
    at async timeout (/Users/user/Projects/reports/node_modules/ccxt/js/base/functions/time.js:178:24) {
  constructor: [Function: ExchangeNotAvailable],
  name: 'ExchangeNotAvailable'
```

code:
```
      const proxy = 'https://my_proxy'
      const agent = new HttpsProxyAgent(proxy)
      options = { ...options, agent }
      this.client = new ccxt.binance({ apiKey, secret, ...options })
```
- "https-proxy-agent": "^4.0.0",

**Comment by kroitor** [comment]
`agent` is not a part of `options` it's a js-specific property of the exchange itself, correct code:

```JavaScript
      const proxy = 'https://my_proxy'
      const agent = new HttpsProxyAgent(proxy)
      this.client = new ccxt.binance({ apiKey, secret, agent, options })
```

**Comment by kroitor** [comment]
@cenyG let me know if the above helps or not.

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/4928

**Comment by cenyG** [comment]
@kroitor Why it's duplicate ? I know how it should work but it's not working for me and I can't figure out why. 
Yeap, `agent` is not part of `options`, it is destruct operator there `...`. 
I think it's not close yet.

**Comment by kroitor** [comment]
@cenyG pardon, I missed the destructuring operator, my bad.

**Comment by cenyG** [comment]
@kroitor yeap, I think it could be reduce to simple
```js
'use strict';
(async () => {
    const ccxt = require ('ccxt')
        , HttpsProxyAgent = require ('https-proxy-agent')
        , exchange = new ccxt.binance ({
            agent: new HttpsProxyAgent ('http://sheltered-forest-37035.herokuapp.com/')
        })
    console.log (await exchange.fetchMarkets ())
}) ()
```

**Comment by kroitor** [comment]
@cenyG yep, i've reproduced it on my side, apparently, https-proxy-agent stopped being compatible with node fetch, because it doesn't return an instance of Agent anymore, which is weird, because: 

- https://github.com/TooTallNate/node-https-proxy-agent/blob/master/index.js#L63
- https://nodejs.org/docs/latest/api/util.html#util_util_inherits_constructor_superconstructor

> Usage of util.inherits() is discouraged. Please use the ES6 class and extends keywords to get language level inheritance support. Also note that the two styles are semantically incompatible.

...

This works for me, just to prove the above theory:

```JavaScript
'use strict';
(async () => {
    const ccxt = require ('ccxt')
        , HttpsProxyAgent = require ('https-proxy-agent')
        , http = require('https')
        , agent = new https.Agent()
        // a workaround to force Agent-type on the https-proxy-agent
        , _ = Object.assign (agent, new HttpsProxyAgent ('http://sheltered-forest-37035.herokuapp.com/'))
        , exchange = new ccxt.binance ({
            agent: agent
        })
    console.log (await exchange.fetchMarkets ())
}) ()
```

↑ So, basically, this is not an issue with the CCXT, this is an issue with another npm package, `https-proxy-agent`, and you might want to address this to that repo https://github.com/TooTallNate/node-https-proxy-agent/issues or use a different agent, or make one... We will also look into adding the above quickfix or a more elegant solution for this issue to the CCXT codebase.

**Comment by ngocpn57** [comment]
For a temporary solution, just use 3.x version of `https-proxy-agent`

**Comment by ttodua** [comment]
A late update to this topic, but proxies has been unified across ccxt, and you might refer to : https://docs.ccxt.com/#/?id=proxy
if any problems, feel free to open an issue.
