### ISSUE TITLE
fetchorder not working

### ISSUE THREAD

**Issue by rmis7170** [ccxt/ccxt#6279]
**>>> exchange.fetchOrder (id**='954a6694-5643-738c-5ca3-e19e3e478309')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/ccxt/bitmex.py", line 311, in fetch_order
    raise OrderNotFound(self.id + ': The order ' + id + ' not found.')
ccxt.base.errors.**OrderNotFound**: bitmex: The order 954a6694-5643-738c-5ca3-e19e3e478309 not found.

**while with swagger api, this order is found!**
client2.Order.Order_getOrders(symbol='XBTUSD', filter=json.dumps({"orderID": '954a6694-5643-738c-5ca3-e19e3e478309'})).result()
([{'orderID': '954a6694-5643-738c-5ca3-e19e3e478309', 'clOrdID': '', 'clOrdLinkID': '', 'account': 850853, 'symbol': 'XBTUSD', 'side': 'Sell', 'simpleOrderQty': None, 'orderQty': 21, 'price': 7073.0, 'displayQty': None, 'stopPx': None, 'pegOffsetValue': None, 'pegPriceType': '', 'currency': 'USD', 'settlCurrency': 'XBt', 'ordType': 'Limit', 'timeInForce': 'GoodTillCancel', 'execInst': 'ParticipateDoNotInitiate', 'contingencyType': '', 'exDestination': 'XBME', 'ordStatus': 'New', 'triggered': '', 'workingIndicator': True, 'ordRejReason': '', 'simpleLeavesQty': None, 'leavesQty': 21, 'simpleCumQty': None, 'cumQty': 0, 'avgPx': None, 'multiLegReportingType': 'SingleSecurity', 'text': 'Submitted via API.', 'transactTime': datetime.datetime(2019, 12, 16, 3, 44, 38, 783000, tzinfo=tzutc()), 'timestamp': datetime.datetime(2019, 12, 16, 3, 44, 38, 783000, tzinfo=tzutc())}], <bravado.requests_client.RequestsResponseAdapter object at 0x7f64702d3f90>)

- OS: fedora 30
- Programming Language version: python 2.7
- CCXT version: latest
- Exchange: bitmex
- Method: fetchOrder

**Comment by dblue** [comment]
Try it with the symbol.

**Comment by rmis7170** [comment]
after recreating client, it works.
