### ISSUE TITLE
php - function iso8601() always returns null on some platforms

### ISSUE THREAD

**Issue by oppure** [ccxt/ccxt#6280]
https://github.com/ccxt/ccxt/blob/484b831b0154c08f8c90e90f3d958704ee096b43/php/base/Exchange.php#L643

casting a large double to int with intdiv() or (int) returns an inconsistent value on some platforms (I've seen this on windows 10 and php 7.1 or 7.0 and on raspbian with php 7.0), possibly because of problems with the biggest int number supported by these platforms, therefore the condition on line 643 is always false.

Dividing $timestamp by 1000 at the beginning of the function fixes the problem for me. If this change doesn't introduces other issues it may be considered for incorporation in next releases.
`public static function iso8601($timestamp = null) {
        if (!isset($timestamp)) {
            return null;
        }
        $timestamp = $timestamp / 1000;
        if (!is_numeric($timestamp)/* || intval($timestamp) != $timestamp*/) {
            return null;
        }
        $timestamp = (int) $timestamp;
        if ($timestamp < 0) {
            return null;
        }
        $result = gmdate('c', (int) floor($timestamp));
        $msec = (int) $timestamp % 1000;
        $result = str_replace('+00:00', sprintf('.%03dZ', $msec), $result);
        return $result;
    }`

**Comment by kroitor** [comment]
> Dividing $timestamp by 1000 at the beginning of the function fixes the problem for me. If this change doesn't introduces other issues it may be considered for incorporation in next releases.

Unfortunately, dividing by a thousand means losing precision. We hope to get this resolved, however, it may be tricky to live-trade with a 32bit-system, since it may also lose precision in other values as well.

Duplicate: https://github.com/ccxt/ccxt/issues/5978 ← I suggest to move this discussion there.

**Comment by oppure** [comment]
Ok thanks. Anyway I think it is equally dangerous that this function quietly returns null, this behaviour can cause serious issues as well. E.g. fetch_ohlcv for coinbasepro will always return the most recent values even when I request past values, without any warnings, so a strategy based on those values will be completely screwed up.
Thanks again for this work.

**Comment by kroitor** [comment]
@oppure we will try to add a workaround for this, in particular, OHLCV does not require a milliseconds-precision, so we could probably fix it by division for fetchOHLCV. However, this won't work with other methods that may really depend on milliseconds and values above 32 bits... I will most likely also add a warning for 32 bits, so to make the user aware of the overflows. Will get to resolving this matter asap.
