### ISSUE TITLE
close position on binance future example

### ISSUE THREAD

**Issue by medozero** [ccxt/ccxt#6286]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

please post an example of closing a binance future position.

Thanks

**Comment by kroitor** [comment]
@medozero in order to close a position with Binance you just need to place an opposite order of the same size as your initial order, when you _"entered that position"_. It would be a bit easier if you could tell which language you are using, and, also describe which particular steps from the Manual you have tried already.

**Comment by medozero** [comment]
aha . ok i got it i will try it . i am using py. i didnot tried yet , thought there is a private command like on bitmex . but i will try what you said . for now you may close this. Thanks

**Comment by kroitor** [comment]
@medozero ok, let us know if you have difficulties with it. Closing it for now. Feel free to reopen it if needed or just ask further questions if any.

**Comment by ralcr** [comment]
Do you know how is done in the hedge mode? Seems to me the combination of options don't allow me to close a position. For example the reduceOnly is not available in hedge mode but from their website when i create a close position order that parameter is set to true. If i just do an opposite order it will be added to the existing order.

**Comment by kroitor** [comment]
@ralcr let us know if this does not help: https://github.com/ccxt/ccxt/issues/7534

**Comment by ralcr** [comment]
It was related to positionSide indeed but not to the problem in the issue.
So what i deed was to create a close order and read from api to see how it looks:

`{\"orderId\":2539404857,\"symbol\":\"BTCUSDT\",\"status\":\"NEW\",\"clientOrderId\":\"web_XQLE2OmdPepdoJbWAmpk\",\"price\":\"11800\",\"avgPrice\":\"0.00000\",\"origQty\":\"0.100\",\"executedQty\":\"0\",\"cumQuote\":\"0\",\"timeInForce\":\"GTC\",\"type\":\"LIMIT\",\"reduceOnly\":true,\"closePosition\":false,\"side\":\"SELL\",\"positionSide\":\"LONG\",\"stopPrice\":\"0\",\"workingType\":\"CONTRACT_PRICE\",\"priceProtect\":\"false\",\"origType\":\"LIMIT\",\"time\":1598797704887,\"updateTime\":1598798059729}`

I used the same settings to create this from api but i get {\"code\":-1106,\"msg\":\"Parameter \'reduceOnly\' sent when not required.\"}

The documentation indeed says i cannot use it "Cannot be sent in Hedge Mode; cannot be sent with closePosition=true"

My problem was that i didn't understood what the positionSide is, i was trying to close a positionSide=long with a positionSide=short. PositionSide should be the same with the order i want to close but the 'side' should be opposite.

**Comment by kroitor** [comment]
@ralcr thx your helpful feedback, appreciate it!

**Comment by flolege** [comment]
@ralcr so you send this options in Hedge Mode? Hos is this possible as the documentation says reduceOnly "Cannot be sent in Hedge Mode;" ?

**Comment by ralcr** [comment]
@flolege  Yes, yo cannot send reduceOnly but creating an opposite order will be created as reduceOnly=true, if i remember well.
