### ISSUE TITLE
Developer Suggestion: use file.endsWith instead of file.includes in build/export-exchanges.js?

### ISSUE THREAD

**Issue by lobatt** [ccxt/ccxt#6288]
Hi,

Thanks for creating this great tool!

I am currently trying to contribute by adding some new exchange integration. There is one small issue I have encountered during coding:

I am using VIM so there will be swap files generated in the js/ folder, e.g. if I am working on `new_ex.js`, there will be file named `.new_ex.js.swp` generated under the same folder.

The problem is that `build/export-exchanges.js` has the following code for retrieving all exchanges:

```
function getIncludedExchangeIds () {

    const includedIds = fs.readFileSync ('exchanges.cfg')
        .toString () // Buffer → String
        .split ('\n') // String → Array
        .map (line => line.split ('#')[0].trim ()) // trim comments
        .filter (exchange => exchange); // filter empty lines

    const isIncluded = (id) => ((includedIds.length === 0) || includedIds.includes (id))

    const ids = fs.readdirSync ('./js/')
        .filter (file => file.includes ('.js'))
        .map (file => file.slice (0, -3))
        .filter (isIncluded);

    return ids
}
```
And this will ends up giving out build error like:

```
Error: Cannot find module './js/.new_ex.js..js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/ccxt/ccxt.js:45:32)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
```

**Could we switch ` .filter (file => file.includes ('.js'))` to somethin like ` .filter (file => file.endsWith ('.js'))` so that VIM users like me could build our code without having to close all .js files?**

- OS: MacOS 
- Programming Language version: JS
- CCXT version: 1.20.98
- Exchange: N/A
- Method: N/A

**Comment by kroitor** [comment]
Hi @lobatt !

Thx for reporting this issue! I've uploaded a fix for it, and it should work without vim-conflicts in 1.21.1 (the new build will arrive in 15 minutes). Let us know if you have further issues with it.

**Comment by lobatt** [comment]
> Hi @lobatt !
> 
> Thx for reporting this issue! I've uploaded a fix for it, and it should work without vim-conflicts in 1.21.1 (the new build will arrive in 15 minutes). Let us know if you have further issues with it.

Wow, that was FAST!

Thanks @kroitor !
