### ISSUE TITLE
how to remove version in url

### ISSUE THREAD

**Issue by jyj545** [ccxt/ccxt#6291]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:linux mint
- Programming Language version:js
- CCXT version:latest
- Exchange:
- Method:init exchange

i want to add a new exchange but i found that the url doesnt need any version number,so i an asking u to help with it.
module.exports = class xx extends Exchange {
    describe () {
        return this.deepExtend (super.describe (), {
            'id': 'xx',
            'name': 'xx',
            'countries': [ 'CN' ],
            'rateLimit': 2000,
            'userAgent': this.userAgents['chrome39'],
            'version': 'v1',
------------------------------------------------------
my  real request url, without version number in it.                  
https://ejia348ffbda04.jccdex.cn/exchange/balances/j4d2J1zNmyAzrmgxGXGxbyfPM7vtmbzHiX

**Comment by kroitor** [comment]
@jyj545 the version is appended to the url in the `sign()` method. When implementing a new exchange, you must also implement the `sign()` method. So, it is up to you whether you want to append the version to the url or not. See how  the `sign()` method is implemented in various existing exchanges. Let us know if that does not answer the question.

**Comment by jyj545** [comment]
thanks for your help,it works for me.
