### ISSUE TITLE
can i add some third-part modules when i add a new exchange?

### ISSUE THREAD

**Issue by jyj545** [ccxt/ccxt#6292]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:linux mint 
- Programming Language version:js
- CCXT version:latest
- Exchange:
- Method:

const Exchange = require ('./base/Exchange');
const third-part-exchange=require('third-part-exchange'),
for example:the third-part-exchange is used for localsign.
after that,can i submit pr?

**Comment by kroitor** [comment]
> can i add some third-part modules when i add a new exchange?

In short, the answer is: no. That's for security reasons mostly. You have to do the signing with the existing crypto base methods primitives as described in the CONTRIBUTING doc:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#using-base-class-cryptography-methods-for-authentication

Also, see how `sign()` is implemented in all other exchanges that may be similar to the one that you're working on.

Let us know if that does not answer the question.

**Comment by kroitor** [comment]
P.S. Another reason for not using 3rd-party code and external dependencies is that CCXT is a multilanguage lib, as explained is the same CONTRIBUTING doc:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

So, a 3rd-party module written in one language won't work in other languages. You may also want to read the entire CONTRIBUTING doc – most of the answers are already there.

**Comment by jyj545** [comment]
thanks for your response,i will reconsider for the problem.
