### ISSUE TITLE
Performance tips?

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6294]
In order to avoid an extra http call (to `loadMarkets`), I was looking for advice on a sensible pattern for storing and sharing the _internals_ of an exchange object.  Basically, I wanted to call `loadMarkets` once, on each exchange I use, then take all that public metadata and _inject_ it into my private ccxt instances.  Does anyone have a good suggestion on a sensible way to do this?  Or is it as simple as say:

```
const sharedInstance = new ccxt[someId]();
await sharedInstance.loadMarkets();

...

function loadAuthenticatedExchange(id, credentials) {
    const stuff = Object.assign({}, sharedInstance);
    
    const privateInstance = new ccxt[id](Object.assign(stuff, credentials));

    return privateInstance;    
}

```

**Comment by kroitor** [comment]
> Does anyone have a good suggestion on a sensible way to do this? Or is it as simple as say:

I'd say it's as simple as you do, however, i would add a filter for functions, since you probably want just the values:

```JavaScript
function loadAuthenticatedExchange(id, credentials) {
    const stuff = Object.assign({}, sharedInstance).filter(x => (typeof x !== 'function'));
    return new ccxt[id](Object.assign(stuff, credentials));
}
```

Let me know if that does not work for you or if you have any issues with that – we will look into it.

**Comment by npomfret** [comment]
const serializable = {};
        for(let key in exchange) {
            const value = exchange[key];
            if(typeof value !== 'function')
                serializable[key] = value;
        }

**Comment by npomfret** [comment]
Actually, it feels like it's a bit more complicated.  I decided it's best to delete anything that is, or contains a function (so it handles the `exceptions` and `httpsAgent` for example).

```
function hasFunctions(obj) {
    if(typeof obj == 'function')
        return true;
    if(typeof obj !== 'object')
        return false;

    for(let prop in obj) {
        const value = obj[prop];
        if (typeof value === 'function')
            return true;
        else if (typeof value === 'object') {
            const hasFuncs = hasFunctions(value);
            if(hasFuncs)
                return true;
        }
    }
}

function makeSeriazable(obj) {
    for(let prop in obj) {
        const value = obj[prop];
        if(hasFunctions(value))
            delete obj[prop]
    }
}

...

        makeSeriazable(exchange);

        const json = JSON.stringify(exchange);
```
