### ISSUE TITLE
New Exchange: NLexch

### ISSUE THREAD

**Issue by Mantas779** [ccxt/ccxt#6298]
Can you add https://www.nlexch.com/

Greetings Mantas , you guys do a great job THX

**Comment by An-Net** [comment]
Shutdown since 31 July 2020

![Снимок экрана 2020-07-23 в 15 56 56](https://user-images.githubusercontent.com/51840849/88289017-44b92d00-ccfd-11ea-8071-2ed20adba0db.png)
