### ISSUE TITLE
Get Binance Future position  info

### ISSUE THREAD

**Issue by medozero** [ccxt/ccxt#6299]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:
- Exchange:
- Method:

Can you give example how to get Binance Future  position info for example the entry Price , liq price , PNL etc 

Thanks

**Comment by kroitor** [comment]
```Python
import ccxt
from pprint import pprint
exchange = ccxt.binance({
    'options': { 'defaultType': 'future' },
    'apiKey': 'YOUR_API_KEY',  # edit for your keys
    'secret': 'YOUR_SECREY',
    'enableRateLimit': True,   # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})

result = exchange.fech_balance()
pprint(result)  # ←-- read ALL of the output VERY carefully
```

Hope it helps. Next time plz don't forget about this: https://github.com/ccxt/ccxt/wiki/FAQ, your programming language, the code snippets you have tried, etc...
