### ISSUE TITLE
Bittrex authentication: invalid signature

### ISSUE THREAD

**Issue by hunsnowboarder** [ccxt/ccxt#630]
As always, thank you so much for this incredible tool and all your efforts put into this!

I am having problems authenticating. 

I try:

```
bittrex =ccxt.bittrex()
bittrex.apiKey = "apikey"
bittrex.secret = "secret_key"
bittrex.account_get_balances()
```
But I get an "INVALID_SIGNATURE" error.

When I try using another tool:

```
from bittrex import Bittrex

my_bittrex = Bittrex("apikey", "secret_key")
my_bittrex.get_balances()
```
This works without any problems, returning my balances.

Thank you again for your help and support!

**Comment by kroitor** [comment]
Hi! Can you please post verbose output? 

https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by kroitor** [comment]
1. Can you try a new keypair? If it works, if means that the "other" software has screwed nonce numbers. Nonce numbers are in seconds by default. You can either use the new keypair, or override the nonce to use milliseconds, if you use the keys with the "other" software that computes nonce values differently.

2. With the same old keypair try:

```Python
import ccxt
bittrex = ccxt.bittrex()
bittrex.apiKey = "apikey"
bittrex.secret = "secret_key"
bittrex.nonce = bittrex.milliseconds  # redefine the nonce to milliseconds
bittrex.account_get_balances()
```

Does this help?

**Comment by kroitor** [comment]
My advice: **NEVER** use the same keypair with different software.

**Comment by kroitor** [comment]
Let us know if the above answer doesn't solve the issue for you. Thx!
