### ISSUE TITLE
'Error' 'Backlog is over max capacity of 1000'

### ISSUE THREAD

**Issue by Gennttii** [ccxt/ccxt#6300]
Hi,

I am having this error:
`'Error' 'Backlog is over max capacity of 1000'`

I am not exceeding any rate limit..
How to fix?

**Comment by kroitor** [comment]
@Gennttii we need more info in order to be able to help you, your versions, your code to reproduce it, etc:

- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by kroitor** [comment]
@Gennttii let us know if you have a followup on this. Feel free to reopen it if needed or just ask further questions. Closing it for now.
