### ISSUE TITLE
How to fetch canceled orders?

### ISSUE THREAD

**Issue by dmitriano** [ccxt/ccxt#6301]
- OS: Windows 10
- Programming Language version: JavaScript v8.12.0
- CCXT version: 1.18.1353
- Exchange: binance
- Method: exchange.fetchClosedOrders(symbol)

If I call exchange.fetchClosedOrders('XRP/USDT') on binance I get closed orders, but not canceled orders. 

Is this by design?

What methods to user to fetch both closed and canceled orders?

**Comment by kroitor** [comment]
> Is this by design?

Yes, in many cases fetchClosedOrders will return just the closed orders only.

> What methods to user to fetch both closed and canceled orders?

Use `fetchOrders()`.

```JavaScript
        const orders = await exchange.fetchOrders (symbol, since, limit, params);
        return exchange.filterByArray (orders, 'status', [ 'closed', 'canceled' ]);
```

Let us know if that does not answer the question.

**Comment by articobandurini** [comment]
According to the docs: 

> fetchClosedOrders() – fetches a list of closed (or canceled) orders.

It would be nice if this method actually return canceled orders as well, probably doing fetchOrders and filtering under the hood.
