### ISSUE TITLE
Python async example of same server but miltiple accounts?

### ISSUE THREAD

**Issue by geeklingo** [ccxt/ccxt#6304]
I was reading through https://github.com/ccxt/ccxt/blob/master/examples/py/async-balances.py

Just wondering if there is also an example of where you may only be dealing with one exchange but multiple accounts?

**Comment by kroitor** [comment]
@geeklingo 

- https://github.com/ccxt/ccxt/blob/master/examples/py/async-multiple-accounts.py

Let us know if that does not answer the question.
