### ISSUE TITLE
Place orders on Binance's futures with PHP

### ISSUE THREAD

**Issue by Skowiz** [ccxt/ccxt#6315]
I would like to place orders on Binance's futures with PHP but it doesnt work :

```
date_default_timezone_set('UTC');
include 'ccxt.php';
$exchange_id = 'binance';
$exchange_class = "\\ccxt\\$exchange_id";
$binance = new $exchange_class(array(
    'apiKey' => "apiKey",
    'secret' => "secret",
    'timeout' => 30000,
    'enableRateLimit' => true,
    'options' => array('defaultType' => "future")
));


$symbol = "BTC/USDT";
$quantity = 0.002;
$price = 5000;

var_dump ($binance->id, $binance->createOrder($symbol,"LIMIT","BUY",$quantity));
```

**Comment by kroitor** [comment]
> but it doesnt work

We need you to elaborate, which particular output do you get? Can you plz paste your verbose request/response (without the keys) ?

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it


```PHP
date_default_timezone_set('UTC');
include 'ccxt.php';
$exchange_id = 'binance';
$exchange_class = "\\ccxt\\$exchange_id";
$binance = new $exchange_class(array(
    'apiKey' => "apiKey",
    'secret' => "secret",
    'timeout' => 30000,
    'enableRateLimit' => true,
    'options' => array('defaultType' => "future")
));


$symbol = "BTC/USDT";
$quantity = 0.002;
$price = 5000;

// add this ↓
$binance->load_markets();
$binance->verbose = true; // ←------ verbose mode on

var_dump ($binance->id, $binance->createOrder($symbol,"LIMIT","BUY",$quantity));
```

**Comment by kroitor** [comment]
@Skowiz also, for some reason, you're sending uppercase order type (LIMIT) and side (BUY) – those should be lowercase, as shown in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders

And you have to specify the price of the limit order, for some reason you're missing the price argument in the createOrder call:

```PHP
//                                          lowercase here ↓↓↓↓↓     $price here ↓
var_dump ($binance->id, $binance->createOrder($symbol,"limit","buy",$quantity, $price));

```

**Comment by kroitor** [comment]
@Skowiz so, your code should look like:

```PHP
date_default_timezone_set('UTC');
include 'ccxt.php';
$exchange_id = 'binance';
$exchange_class = "\\ccxt\\$exchange_id";
$binance = new $exchange_class(array(
    'apiKey' => "apiKey",
    'secret' => "secret",
    'timeout' => 30000,
    'enableRateLimit' => true,
    'options' => array('defaultType' => "future")
));


$symbol = "BTC/USDT";
$quantity = 0.002;
$price = 5000;

// add this ↓
$binance->load_markets();
$binance->verbose = true; // ←------ verbose mode on

var_dump ($binance->id, $binance->createOrder($symbol,"limit","buy",$quantity, $price));
```

Let us know if that does not help.

**Comment by Skowiz** [comment]
The answer I have is

`Request: Array ( [0] => POST [1] => https://fapi.binance.com/fapi/v1/order [2] => Array ( [0] => X-MBX-APIKEY: apikey [1] => Content-Type: application/x-www-form-urlencoded ) [3] => timestamp=1577305511040&recvWindow=5000&symbol=BTCUSDT&quantity=0.002&type=LIMIT&side=BUY&price=5000&timeInForce=GTC&signature=xxx ) Response: Array ( [0] => POST [1] => https://fapi.binance.com/fapi/v1/order [2] => 401 [3] => [4] => Array ( [content-type] => Array ( [0] => application/json ) [content-length] => Array ( [0] => 70 ) [date] => Array ( [0] => Wed, 25 Dec 2019 20:25:11 GMT ) [server] => Array ( [0] => Tengine ) [x-mbx-used-weight-1m] => Array ( [0] => 1 ) [x-response-time] => Array ( [0] => 0ms ) [access-control-allow-origin] => Array ( [0] => * ) [access-control-allow-methods] => Array ( [0] => GET, POST, PUT, DELETE, OPTIONS ) [x-cache] => Array ( [0] => Error from cloudfront ) [via] => Array ( [0] => 1.1 5e95d2e6aebe43cabd9dcdad89ad0a42.cloudfront.net (CloudFront) ) [x-amz-cf-pop] => Array ( [0] => AMS54-C1 ) [x-amz-cf-id] => Array ( [0] => xxx== ) ) [5] => {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."} )`

**Comment by kroitor** [comment]
@Skowiz it says: `{"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}`. Which steps from this troubleshooting sequence from the Manual have you tried?

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Have you tried a fresh new keypair? Have you checked the API credentials themselves? Any other troubleshooting steps?

**Comment by Skowiz** [comment]
I have last version of CCXT, I tried a new keypair ...
But if I make the code run in default market, it works 
```
date_default_timezone_set('UTC');
include 'ccxt.php';
$exchange_id = 'binance';
$exchange_class = "\\ccxt\\$exchange_id";
$binance = new $exchange_class(array(
    'apiKey' => "apiKey",
    'secret' => "secret",
    'timeout' => 30000,
    'enableRateLimit' => true,
    // 'options' => array('defaultType' => "future")
));


$symbol = "BTC/USDT";
$quantity = 0.002;
$price = 5000;

$binance->load_markets();
$binance->verbose = true;

var_dump ($binance->id, $binance->createOrder($symbol,"limit","buy",$quantity, $price));
```
This code place an order

**Comment by kroitor** [comment]
@Skowiz have you enabled the futures account with Binance? Tried placing any future orders on their website? 

> I think it is really a problem with future market

It's hard to tell without getting your answers to all of the above questions here: https://github.com/ccxt/ccxt/issues/6315#issuecomment-568950611

**Comment by kroitor** [comment]
@Skowiz can you plz post the runtime version of CCXT, as shown below?

```PHP
date_default_timezone_set('UTC');
include 'ccxt.php';

echo "CCXT version: " . \ccxt\Exchange::VERSION . "\n"; // ←----------------------- add this
```

This looks like an issue that has been resolved here: https://github.com/ccxt/ccxt/issues/6196

**Comment by kroitor** [comment]
@Skowiz check if the futures account had been activated for you in the futures section of Binance's website. It won't work for API keys created before activating the futures account, so the API keys have to be recreated after creating the futures account with Binance's website. Let us know here if the above does not help.

**Comment by Skowiz** [comment]
My version is : CCXT version: 1.21.15 7229.03
Yes I have already placed orders with Binance Future website. And I created new keypair 1 hour ago, then I dont know what is the problem.

**Comment by kroitor** [comment]
@Skowiz have you tried reaching out to Binance tech support on this issue? Also, it's worth checking if your IP is whitelisted with that keypair, just in case.

**Comment by Skowiz** [comment]
Yes `$binance->fetch_balance();` works, then my IP is OK and my API's ID too.
Then I do not know what is the problem.
I sent a message to Binance support but I dont have any answer now.

**Comment by Skowiz** [comment]
Binance is asking me to send them the full CURL of my request, how can I have access to ?

**Comment by kroitor** [comment]
@Skowiz send them your complete verbose request+response pair that you can see in verbose mode, which you can enable as shown above: https://github.com/ccxt/ccxt/issues/6315#issuecomment-568923704

**Comment by Skowiz** [comment]
The answer they gave me is :
```
We had a quick test on the API interface 'fapi/v1/order', it returns the correct result. The curl string I was using is https://fapi.binance.com/fapi/v1/order?side=SELL&recvWindow=60000&type=LIMIT&price=8400&timeInForce=GTC&quantity=10&symbol=BTCUSDT&timestamp=1577600903345&signature=xxxxxxxxxxx 

You can try to use Postman to send an order request directly for testing purposes, it can narrow down the curse of the problem quickly.  if there is no problem with making orders via Postman, it means there something wrong with your codes, please optimize your codes. As we do not support programming on ticket, please try to follow below steps to join our API Telegram Channel, there are programming professionals there, they will help you.


Copy the link: https://t.me/binance_api_english

Open your Telegram App

Paste the link in the search box

Join the Group


If it doesn't work via Postman as well, please provide your query string and message returned, so that we can troubleshoot further. Thanks for your support and understanding, if you have any questions, please feel free to let us know, we are very happy to help.
```

Then I do not know what is wrong because with verbose mode I have this message

Request: Array ( [0] => POST [1] => https://fapi.binance.com/fapi/v1/order [2] => Array ( [0] => X-MBX-APIKEY: KEY [1] => Content-Type: application/x-www-form-urlencoded ) [3] => timestamp=1577621294544&recvWindow=5000&symbol=BTCUSDT&quantity=0.002&type=LIMIT&side=BUY&price=5000&timeInForce=GTC&signature=033105bdb2a5629a62afd5b214557e4fdea674fb91b546437c693ab71b3d13dd ) Response: Array ( [0] => POST [1] => https://fapi.binance.com/fapi/v1/order [2] => 401 [3] => [4] => Array ( [content-type] => Array ( [0] => application/json ) [content-length] => Array ( [0] => 70 ) [date] => Array ( [0] => Sun, 29 Dec 2019 12:08:15 GMT ) [server] => Array ( [0] => Tengine ) [x-mbx-used-weight-1m] => Array ( [0] => 2 ) [x-response-time] => Array ( [0] => 0ms ) [access-control-allow-origin] => Array ( [0] => * ) [access-control-allow-methods] => Array ( [0] => GET, POST, PUT, DELETE, OPTIONS ) [x-cache] => Array ( [0] => Error from cloudfront ) [via] => Array ( [0] => 1.1 6642832e0f3e501fb9fdc5f35d4351d8.cloudfront.net (CloudFront) ) [x-amz-cf-pop] => Array ( [0] => AMS54-C1 ) [x-amz-cf-id] => Array ( [0] => 55Hl8ONQtU_Q-MMffy0ojAyhJVTHF3j1f5vIRV2PhY4XSbic_NFtug== ) ) [5] => {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."} )

**Comment by kroitor** [comment]
@Skowiz have you tried the values they suggest (price=8400, side='sell'), somewhat closer to the market price) ?

You see, the values you use are price=5000 and side=buy, which are beyond limits for BTC/USDT:

```JavaScript
binance.market (BTC/USDT)
{     limits: { amount: { min: 0.001, max: 1000 },
                 price: { min: 0.01, max: 100000 },
                  cost: { min: -0.9030899869919435, max: undefined } },
   precision: { base: 8, quote: 8, amount: 3, price: 2 },
   tierBased:    false,
  percentage:    true,
       taker:    0.001,
       maker:    0.001,
          id:   "BTCUSDT",
      symbol:   "BTC/USDT",
        base:   "BTC",
       quote:   "USDT",
      baseId:   "BTC",
     quoteId:   "USDT",
        info: {                symbol:   "BTCUSDT",
                               status:   "TRADING",
                   maintMarginPercent:   "2.5000",
                requiredMarginPercent:   "5.0000",
                            baseAsset:   "BTC",
                           quoteAsset:   "USDT",
                       pricePrecision:    2,
                    quantityPrecision:    3,
                   baseAssetPrecision:    8,
                       quotePrecision:    8,
                              filters: [ {   minPrice: "0.01",
                                             maxPrice: "100000",
                                           filterType: "PRICE_FILTER",
                                             tickSize: "0.01"          },
                                         {   stepSize: "0.001",
                                           filterType: "LOT_SIZE",
                                               maxQty: "1000",
                                               minQty: "0.001"     },
                                         {   stepSize: "0.001",
                                           filterType: "MARKET_LOT_SIZE",
                                               maxQty: "1000",
                                               minQty: "0.001"            },
                                         { limit: 200, filterType: "MAX_NUM_ORDERS" },
                                         {    multiplierDown: "0.8500",
                                                multiplierUp: "1.1500",
                                           multiplierDecimal: "4",
                                                  filterType: "PERCENT_PRICE" }        ],
                           orderTypes: [ "LIMIT",
                                         "MARKET",
                                         "STOP",
                                         "STOP_MARKET",
                                         "TAKE_PROFIT",
                                         "TAKE_PROFIT_MARKET" ],
                          timeInForce: ["GTC", "IOC", "FOK", "GTX"]                       },
        type:   "future",
        spot:    false,
      future:    true,
      active:    true                                                                        }
```

See the `filters` field above and also check out the following:

- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits
- https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#price_filter
- https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#percent_price

↑ Your value for the price does not satisfy the requirements. If the PERCENT_PRICE multiplierDown is 0.85 and the market price is ~7200, then the minimal price you can submit is roughly 7200 * 0.85 ~= 6120. And all other filters on that market should be satisfied as well.

Let me know if that does not help.

**Comment by Skowiz** [comment]
Even if i but a price as they did 8400 and side "sell", it is correct with the market price (7400), it is not working.
Maybe the issue come from the recvWindow param wich is equal to 5000 in my request but it should be 60000 I think.
How can I change this value ?

**Comment by kroitor** [comment]
```PHP
date_default_timezone_set('UTC');
include 'ccxt.php';
$exchange_id = 'binance';
$exchange_class = "\\ccxt\\$exchange_id";
$binance = new $exchange_class(array(
    'apiKey' => "apiKey",
    'secret' => "secret",
    'timeout' => 30000,
    'enableRateLimit' => true,
    'options' => array(
        'defaultType' => "future",
        'recvWindow' => 60000,
    )
));
```

**Comment by Skowiz** [comment]
I tryied this but it does not change anything, the param recvWindow do not change in the CURL request and still equal to 5000. How is it possible ?

**Comment by Skowiz** [comment]
Thank you very much, every is working now
