### ISSUE TITLE
[HitBTC2] error mapping

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6325]
If you send an invalid amount to `createOrder` (such as `1.2e+22`), the exchange blows up with a timeout:

> ExchangeNotAvailable: hitbtc2 {\"error\":{\"code\":504,\"message\":\"Gateway Timeout\"}

It looks like this is mapped to `ExchangeNotAvailable`, should this be `RequestTimeout` instead?

**Comment by kroitor** [comment]
> It looks like this is mapped to ExchangeNotAvailable, should this be RequestTimeout instead?

Yep, I think so.

**Comment by npomfret** [comment]
Is this a hitbtc issue, or a more general one?

**Comment by kroitor** [comment]
@npomfret i think this particular error is hitbtc-specific, however, in some cases other exchanges also report a timeout under high load.
