### ISSUE TITLE
React-native (expo) support

### ISSUE THREAD

**Issue by guillaumeLamanda** [ccxt/ccxt#6327]
Hello ccxt, 

I am working on old react-native (expo) project, and I first tried to upgrade dependencies.  
The ccxt upgrade break on react-native plateform. The latest working version for the plateform is `1.18.523`.  

On the latest version, I get this error :  
```
The package at "node_modules/ccxt/js/base/Exchange.js" attempted to import the Node standard library module "http". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo
Failed building JavaScript bundle.
```

Indeed, the file `js/base/Exchange.js` import `http` and `https` node libraries.

I checked this issue ; #5589, but the expo environment seems different from ejected react-native.

Minimal reproduction : https://github.com/guillaumeLamanda/expo-ccxt

Thank's for the work here. 👍

- OS: MacOS 10.15.1
- Programming Language version: Javascript
- CCXT version: 1.18.523
- File: `js/base/Exchange.js`

**Comment by kroitor** [comment]
@guillaumeLamanda hi! Thank you for reporting this issue! We have uploaded a workaround for it, plz update to version 1.21.24 in 15 minutes and let us know if you still have difficulties. We will be happy if you report back whether the issue is resolved or not. Thx again!

**Comment by guillaumeLamanda** [comment]
Hi @kroitor ! I upgraded ccxt, but now I ran into this issue : 
```
The package at "node_modules/ccxt/js/static_dependencies/BN/bn.js" attempted to import the Node standard library module "buffer". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo
Failed building JavaScript bundle.
```

I upgraded ccxt to `1.21.24` on the minimal reproduction. The minimal reproduction is powered by [expo](https://expo.io/) so you can test it easily 😉

**Comment by kroitor** [comment]
@guillaumeLamanda ah, ok this is a different issue now, but will resolve it as well asap and will follow up here.

**Comment by guillaumeLamanda** [comment]
I think it is in the scope of this issue.  

Thank's for you're work !

**Comment by kaminskypavel** [comment]
still not working...

 **"ccxt": "^1.23.9"**

```
The package at "node_modules\ccxt\js\static_dependencies\node-fetch\index.js" attempted to import the Node standard library module "stream". It failed b
ecause React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-pac
kages-with-expo
Failed building JavaScript bundle.
The package at "node_modules\ccxt\js\static_dependencies\BN\bn.js" attempted to import the Node standard library module "buffer". It failed because Reac
t Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-
expo
Failed building JavaScript bundle.

```

**Comment by peyotll** [comment]
https://github.com/parshap/node-libs-react-native is easy to use and working well for using node modules in React Native ;) Tested with the last version of CCXT and RN 0.62. I just needed to add `var Buffer = require('buffer/').Buffer` in global.js
