### ISSUE TITLE
Cannot figure out the failed test

### ISSUE THREAD

**Issue by abhishekr700** [ccxt/ccxt#6329]
Environment: Docker Container

On running test with `--python3` . I get FAILED test but there is no output to let me understand what the problem is. Verbose is set to true.
Please help me
```
root@28cddc60ca50:/ccxt# node run-tests.js --python --js --python2 --python3 bitbns
Testing { exchanges: ["bitbns"], symbol: "all", keys: { '--js': true, '--php': false, '--python': true, '--python2': true, '--python3': true }, maxConcurrency: 5 } (run-tests.js:252)
[100%] Testing bitbns FAIL (testExchange @ run-tests.js:169)

FAILED bitbns (Python 3): (explain @ run-tests.js:187)

	bitbns using proxy `https://cors-anywhere.herokuapp.com/` (explain @ run-tests.js:190)
FAIL ["bitbns"] (run-tests.js:268)
All done, 1 failed (run-tests.js:273)
root@28cddc60ca50:/ccxt#
```

**Comment by kroitor** [comment]
Try running a standalone python3 test:

```
python3 python/test/test.py bitbns
```

What does it say?

**Comment by abhishekr700** [comment]
@kroitor  I get this, no errors
```
root@28cddc60ca50:/ccxt# python3 python/test/test.py bitbns
bitbns using proxy `https://cors-anywhere.herokuapp.com/`
EXCHANGE: bitbns
SYMBOL: BTC/USDT
bitbns BTC/USDT ticker None high: 7334.19 low: 7222.8422 bid: 7236.15 ask: 7251.58 volume: None
bitbns BTC/USDT order book 2019-12-31T10:24:17.089Z bid: 7236.15 bidVolume: 0.214432 ask: 7251.58 askVolume: 0.326149
bitbns BTC/USDT fetched 20 trades
bitbns fetched all 91 tickers
bitbns fetched 1 OHLCVs
root@28cddc60ca50:/ccxt#
```

**Comment by kroitor** [comment]
@kroitor does the default sync (py2) test work for you as well?

```
python --version
python python/test/test.py bitbns
```

?

**Comment by abhishekr700** [comment]
@kroitor YES !
```
root@28cddc60ca50:/ccxt# python --version
Python 2.7.15+
root@28cddc60ca50:/ccxt# python python/test/test.py bitbns
bitbns using proxy `https://cors-anywhere.herokuapp.com/`
EXCHANGE: bitbns
SYMBOL: BTC/USDT
bitbns BTC/USDT ticker None high: 7334.19 low: 7222.8422 bid: 7240.41 ask: 7255.56 volume: None
bitbns BTC/USDT order book 2019-12-31T10:36:07.066Z bid: 7240.41 bidVolume: 0.175578 ask: 7255.56 askVolume: 0.351858
bitbns BTC/USDT fetched 20 trades
bitbns fetched all 91 tickers
bitbns fetched 1 OHLCVs
root@28cddc60ca50:/ccxt#
```

**Comment by kroitor** [comment]
@abhishekr700 ok, i will need some time to debug it on my side and will get back to you asap.

**Comment by kroitor** [comment]
@abhishekr700 what's your version of Python3, btw? `python3 --version` ?

**Comment by kroitor** [comment]
@abhishekr700 does it work this way:

```
node run-tests.js bitbns --python --js --python2 --python3 
```

?

**Comment by abhishekr700** [comment]
@kroitor  Using the docker container provided in ccxt, so version and all is what you guys built into the docker.
Anyways, here it is 
```
root@28cddc60ca50:/ccxt# python3 --version
Python 3.6.8
root@28cddc60ca50:/ccxt#
```

**Comment by abhishekr700** [comment]
@kroitor  Changing arguments order does not affect the result.

**Comment by kroitor** [comment]
@abhishekr700 got it, will be back to you with my results soon.

**Comment by abhishekr700** [comment]
@kroitor Any update on this?

**Comment by kroitor** [comment]
@abhishekr700 pardon for the delay, didn't have a chance to tackle it yet, but will do my best to address this issue asap.

**Comment by gthedifferentone** [comment]
@kroitor Looking forward

**Comment by ttodua** [comment]
Does anyone still experience the issue, or it is now gone away?

**Comment by jeansouza** [comment]
> Does anyone still experience the issue, or it is now gone away?

@ttodua I'm having the same problem, Python 3.10.4.

**Comment by ttodua** [comment]
A late reply to this topic, but tests have been unified & updated, and if you update ccxt to latest version, you should no longer experience it. but if you have any problems, feel free to post a comment or open a new issue.
