### ISSUE TITLE
Convert PHP to PSR-4 (autoload in Composer)

### ISSUE THREAD

**Issue by kiwina** [ccxt/ccxt#633]
Hi it be nice to have something more usable on the php side to use with common package managers.
Been fiddling around and its actually easy just wander if you generate the Exchange file as well or is it static?
Else i have the transpiler edited for psr-4, i guess all the docs would have to be updated

**Comment by kroitor** [comment]
> Hi it be nice to have something more usable on the php side to use with common package managers.

For PHP we have a Packagist integration: https://packagist.org/packages/ccxt/ccxt

> Been fiddling around and its actually easy just wander if you generate the Exchange file as well or is it static?

The `static $exchanges` member (a list of exchanges' ids) is generated, everything else is static.

> Else i have the transpiler edited for psr-4, i guess all the docs would have to be updated.

Would be awesome if you could propose a PR or a way for ccxt to transition to psr-4 seamlessly. We  just have to be careful not to break anything, our current build process is very fine-tuned. More about it here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md.

Let me know if the above answers your questions and thanks for the feedback!

**Comment by kiwina** [comment]
Well to make it auto-load in composer and obey to standards a few things have to change.
with the start that it should all files should be with the first letter uppercased.
Not sure you want to venture there?

**Comment by kroitor** [comment]
> Not sure you want to venture there?

I think, yes, we do want to be autoloadable in Composer, so we are going to do that anyway. The only obstacle is that we are under very active development, as you may know, and we currently have a lack of time... We mostly focus on support and bugfixes, while also implementing the remaining (missing) functionality. Our topmost priorities are unit-test coverage and switching to arbitrary precision math, as well as developing a few other aspects of the library. So, we hope to do the PSR-4 transition after that. Basically, the task is very clear, we just have to change the build process slightly and resolve several naming issues...

**Comment by kiwina** [comment]
not really its pretty straight forward i think
so far what i do
`
   function ucFirst(str) {
		return str.charAt(0).toUpperCase() + str.slice(1)
	}
    function createPHPClass (className, baseClass, body, methods) {

        const baseFolder = 'use Ccxt\\'
        const baseFile =  baseFolder + baseClass
		className = ucFirst(className)
        const header = [
            "<?php\n",
            "namespace Ccxt;\n",
            baseFile + ";\n",
            'class ' + className + ' extends ' + baseClass + ' {'    ,
        ]

        let bodyAsString = body.join ("\n")

        for (let method of methods) {
            const regex = new RegExp ('this->(' + method + ')\\s*\\(', 'g')
            bodyAsString = bodyAsString.replace (regex,
                (match, p1) => ('this->' + convertMethodNameToUnderscoreNotation (p1) + ' ('))
        }

        const footer =[
            "}\n",
            '?>',
        ]

        const result = header.join ("\n") + "\n" + bodyAsString + "\n" + footer.join ('\n')
        return result
    }
`
than change the forlder.
and change all calls in the exchange file to reflect the changes

**Comment by kroitor** [comment]
> and change all calls in the exchange file to reflect the changes

Everything is clear except this last one is, which calls do you mean and how should we change them?

**Comment by kiwina** [comment]
Everything like this
`
 $exception = '\\Ccxt\\' . $exception_type;
`

**Comment by kiwina** [comment]
Actually few more things can be improved on the Exchange file.
Let me work on it today as i use it and i'm dooing it anyways test it and i'll upload it.

**Comment by kroitor** [comment]
BTW, are you sure we really need to capitalize classnames? We would rather keep the ids and classnames consistent (lowercase) in all languages, unless we have absolutely no other way of solving it...

<img width="826" alt="screen shot 2017-11-20 at 09 38 00" src="https://user-images.githubusercontent.com/1294454/33005372-92b55426-cdd6-11e7-9733-509592793717.png">

https://stackoverflow.com/a/20276719/5055465

What do you think of the above?

**Comment by kiwina** [comment]
well we don't have to but it is pretty much the standard

**Comment by kroitor** [comment]
@kiwina ok, and which changes do you think we should introduce to become autoloadable yet still retain lowercase ids+classnames?

**Comment by kiwina** [comment]
is it ok to reorganize a little bit the errors?

**Comment by kroitor** [comment]
@kiwina I guess so, depends on what you mean under "a little bit" ) I'd suggest, go for it, and we will carry on from there. Our goal is to remain consistent in naming and overall structure of the library across all languages. If you don't really expect impossible difficulties, why not.

**Comment by kroitor** [comment]
@kiwina, so, what shall we do about it? We'd prefer to keep lowercase names if possible, as long as it doesn't go against the standard. Let us know if you are going to contribute to this or we should fix it on our own in order to make it autoloadable. Thx!

**Comment by irazasyed** [comment]
Good discussion!

Can you also maybe consider splitting the repo into multiple repos for each language or at least PHP? I just tried to install using composer and the installation was very slow and I noticed it's because of too many files. It has become quite heavy and probably loading all files that are not needed.

I think a few changes to the build process will help fix this issue by automatically compiling and pushing the latest version to GitHub to its own repo.

**Comment by kroitor** [comment]
Thanks for the suggestion, @irazasyed! We will consider it carefully, currently it's more convenient to have everything in one place, we will optimize and speed up the installation procedure, will skip unnecessary files all that, if that does not help we may split it as well.

**Comment by kroitor** [comment]
@irazasyed, more on your post: here's a [PHP7-only-clone of CCXT on Packagist](https://packagist.org/packages/kornrunner/ccxt), everything else except PHP7-version was stripped out by @kornrunner. We're not affiliated, however, so, we are not responsible for updating that branch. Check it out and see if installation time meets your expectations ;)

**Comment by irazasyed** [comment]
@kroitor Sounds good. I'll check the other project and also keep an eye on this if it gets updated, thanks 👍

**Comment by irazasyed** [comment]
@kroitor FYI, I just tested @kornrunner's repo and it installed quickly + works without errors that I had come across before (noticed his last commit fixes the issue, so that's good). I'm on 7.1-7.2rc. So it's good. Thanks!

**Comment by kroitor** [comment]
@irazasyed thanks for reporting! Cheers!

**Comment by kroitor** [comment]
Ok, PHP autoload was added here: #673 by @silberbaum! Let us know if you have any difficulties with it! Cheers!

**Comment by Moongazer** [comment]
Is your discussion here about the PSR-4 using lowercase classnames maybe related with the following output during the installation with Composer?

```
Writing lock file
Generating optimized autoload files
Deprecation Notice: Class ccxt\Exchange located in ./vendor/ccxt/ccxt/php/base/Exchange.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class ccxt\BaseError located in ./vendor/ccxt/ccxt/php/base/errors.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class ccxt\ExchangeError located in ./vendor/ccxt/ccxt/php/base/errors.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
[...] many more
```

If so, we should concider to reopen this issue to make it compatible with the new Composer version.

**System Information:**
PHP: 7.4
Composer: 1.10.1

**Comment by kroitor** [comment]
@Moongazer yeah, we've seen that warning before... I'll do my best to get to it asap. Suggestions and contributions are welcome!

**Comment by erfansahaf** [comment]
Any update on this?

**Comment by kroitor** [comment]
@erfansahaf we are working on a major PHP enhancement right now, that includes an upgrade to Composer 2.0, so we believe it will arrive pretty soon. Can't tell the exact date, but the ETA is within a couple of weeks, I hope.
