### ISSUE TITLE
Place an order with takeprofit and stoploss

### ISSUE THREAD

**Issue by Skowiz** [ccxt/ccxt#6331]
Hello I would like to place an order on Binance Future market with a stoploss and a take profit.
How can I specify theses params ?
What is the correct writing ?
Now I have :
`$binance->createOrder($symbol,"limit","buy",$quantity,$price)`

**Comment by kroitor** [comment]
Hi!

That's explained here:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

```PHP
// edit for your params and values, mind the types of the values according to Binance docs:
// https://binance-docs.github.io/apidocs/futures/en/#new-order-trade

$params = array(
    'paramName1' => 'paramValue1',
    'paramName2' => paramValue2,
    'paramName3' => 123,
); // ----------------------------------------------------------- ↓

$binance->createOrder($symbol,"limit","buy",$quantity,$price, $params);
```

Let me know if the above does not help.

**Comment by mortezafouladi** [comment]
Hello, I have the same issue

I am trying to place an order on Binance future market with stop loss and take profit.

This is what I do:

`//Main Order
                $params = [
                    'newClientOrderId'=> 'testing',
                ];
                $exchange->create_order($data['symbol'], 'MARKET', $data['market_side'], $amount, $price, $params);
                // Change Market Side
                if ($data['market_side'] == "sell") {
                    $market_side = "buy";
                } else {
                    $market_side = "sell";
                }

                // Take Profit Market
                $params = [
                    'stopPrice'=> $data['take_profit_market'],
                ];
                $stopPrice = $data['take_profit_market'];
                $exchange->create_order($data['symbol'], 'TAKE_PROFIT_MARKET', $market_side, $amount,$stopPrice, $params);

                // Stop Loss Market
                $params = [
                    'stopPrice'=> $data['stop_loss_market'],
                ];
                $stopPrice = $data['stop_loss_market'];
                $exchange->create_order($data['symbol'], 'STOP_MARKET', $market_side, $amount,$stopPrice, $params);`

I am not sure I am doing it in the correct way. Do I need to achieve these through one order with take-profit and stop-loss parameters defined? and what parameters do I need to set in params to specify the take profit market and stop market values?

**Comment by kroitor** [comment]
@mortezafouladi let us know if you have difficulties with this example:

- https://github.com/ccxt/ccxt/blob/master/examples/php/binance-create-order-stop-loss-take-profit.php

```PHP
<?php

$root = dirname(dirname(dirname(__FILE__)));

include $root . '/ccxt.php';

date_default_timezone_set('UTC');

echo 'PHP v' . PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION . '.' . PHP_RELEASE_VERSION . "\n";
echo 'CCXT v' . \ccxt\Exchange::VERSION . "\n";

$id = 'binanceusdm'; // edit this line

// ----------------------------------------------------------------------------

// instantiate the exchange by id
$exchange_class = '\\ccxt\\' . $id;
$exchange = new $exchange_class(array(
    // some exchanges may require additional API credentials
    'apiKey' => 'YOUR_API_KEY', // edit this line
    'secret' => 'YOUR_SECRET', // edit this line
));

$exchange->load_markets();
// $exchange->verbose = True; // uncomment for debugging purposes

$symbol = 'BTC/USDT';
$side = 'buy';
$amount = 0.01;
$price = 30000;
$stopPrice = 25000;
$takeProfitPrice = 35000;

try {

    $order = $exchange->create_order($symbol, 'MARKET', $side, $amount);
    print_r($order);

    $inverted_side = ($side == 'buy') ? 'sell' : 'buy';

    $stopLossParams = array('stopPrice' => $stopLossPrice);
    $stopLossOrder = $exchange->create_order($symbol, 'STOP_MARKET', $inverted_side, $amount, null, $stopLossParams);
    print_r($stopLossOrder);

    $takeProfitParams = array('stopPrice' => $takeProfitPrice);
    $takeProfitOrder = $exchange->create_order($symbol, 'TAKE_PROFIT_MARKET', $inverted_side , $amount, null, $takeProfitParams);
    print_r($takeProfitOrder);

} catch (Exception $e) {
    echo get_class($e) . ': ' . $e->getMessage() . "\n";
}
```

**Comment by mortezafouladi** [comment]
@kroitor Thank you, it's working very well now.

**Comment by zdytch** [comment]
As I understand the code right, here you just create 3 independent orders: $order, $stopLossOrder, $takeProfitOrder. 

But this is not what actually stoploss and takeprofit are intended to be. First, those orders have to stay inactive until parent order gets filled. Second, they have to belong to one OCO group, so when, e.g. stop loss gets filled, take profit automatically cancels.

So, how to achieve the real stoploss and takeprofit behavior?

**Comment by zdytch** [comment]
Ok, it's not implemented on Binance side. You need to track everything in your code, e.g:
https://dev.binance.vision/t/how-to-implement-otoco-tp-sl-orders-using-api/1622
