### ISSUE TITLE
Happy 2020! Q1 roadmap

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#6332]
Hello dear CCXT users!

We in our small CCXT team wish you all a Happy New Year 2020! )
Thank you for being a part of the global professional crypto-trading community!

Below is a quick update on our plans for Q1 and the future work.

[As you know](https://github.com/ccxt/ccxt/issues/56#issuecomment-507290536) our priority at this point is to release the CCXT Pro to public. We would like to give you some technical insights on our progress towards that goal. We currently have the topmost exchanges, all of them with functional transpileable orderbook feeds. Some of them also have trade feeds, ticker feeds, OHLCVs, heartbeats, as well as examples of handling private feeds, like account/balance updates, order updates, private fills and other events. In other words, the CCXT Pro codebase includes a fully-functional unified base WS implementation (async) in JS/Python/PHP, though some remaining code for derived exchange methods still has to be wrapped-up (as we usually do).

We don't have a fully-unified SignalR implementation in all languages yet, but we are working on it as well and it does not really stop us from releasing the majority of the code that we already have. 

Our plan for January 2020:

- Perform private beta-testing of CCXT Pro, during these opening weeks of 2020. First thing, we will invite topmost contributors who have the experience with our codebase, in private. We look up to contributors, because that's a good way to collect reliable feedback from the expert users of CCXT in a more or less organized way. As promised, we will give free CCXT Pro (Bro) licenses to our topmost contributors.

- We will post the final pricing grid and commercial terms after the tests.

- Release CCXT Pro to public – the date is still open, because it's pretty much "any minute now", figuratively speaking. We are doing our best to announce the final date and release a stable working product as soon as possible. 

Also, we are well aware of the accumulated backlog of new exchange PRs – we'd like to say thank you to all respective contributors, appreciate your patience! Going to resolve the backlog shortly after releasing CCXT Pro. We will focus our work in that direction immediately after CCXT Pro and will integrate most of those pending exchanges in expedite fashion. That's our plan for February-March 2020, since most of our time in January will probably be eaten by the WebSockets release. That does not mean that we will not integrate any exchanges sooner – we are going to maintain that work as much as we can no matter what, a breakthrough in that direction is planned as well.

Happy New Year!

**Comment by lookis** [comment]
I would be happy to know that do we have a *pre certified* exchange list for pro version?
and what other features is been considering besides websocket streaming? 
(just want a glance, not promise)

**Comment by kroitor** [comment]
> I would be happy to know that do we have a pre certified exchange list for pro version?

The initial release of CCXT Pro version will contain the top exchanges, that is, most of the names from our existing [certified list](https://github.com/ccxt/ccxt#certified-cryptocurrency-exchanges) and several popular non-certified exchanges as well. In other words, the initial version will have 10-15 stable working exchanges. We already have the following names from the list:

- binance + regional partners
- coinbasepro + coinbaseprime
- kucoin
- bitfinex
- bitmex
- huobipro (hbg)
- kraken
- poloniex
- ftx
- idex
- upbit

After the release we are going to add more exchanges at a very quick rate (a few every week). One of the reasons why we are spending more time on the initial codebase now – is to make it possible to extend the library further very quickly.

> and what other features is been considering besides websocket streaming?

Streaming itself is basically the key feature and the core of CCXT Pro. Apart from that we have plans for adding FIX-protocol adapters, the support for compiled modules and languages and integrations with 3rd-party providers of historical data and aggregators.

**Comment by hroff-1902** [comment]
>  We already have the following names from the list:

What about bittrex?

**Comment by kroitor** [comment]
@hroff-1902 

> We don't have a fully-unified SignalR implementation in all languages yet, but we are working on it as well and it does not really stop us from releasing the majority of the code that we already have.

**Comment by kroitor** [comment]
@hroff-1902 actually, we've added bittrex as well, so it will be on the initial release.

- https://youtu.be/rkknRynjMQE
- https://youtu.be/h-aOCCQHd2A

<img width="734" alt="Screen Shot 2020-01-21 at 09 21 46" src="https://user-images.githubusercontent.com/1294454/72780269-7c9cc600-3c2f-11ea-94b7-9f6af0179062.png">

<img width="742" alt="Screen Shot 2020-01-21 at 09 23 56" src="https://user-images.githubusercontent.com/1294454/72780381-c685ac00-3c2f-11ea-9f6e-612e86564913.png">

**Comment by n01ukn0w** [comment]
Do we have any idea of a release date for CCXT Pro?  I really want to put it the hands of my developer.

**Comment by kroitor** [comment]
@n01ukn0w we had a bit of a delay adding signalr, and some minor things. At this point we're finishing the tests and we think that we will be able to announce the actual release date next week, hopefully. The release itself will follow shortly after.

**Comment by hroff-1902** [comment]
How will CCXT Pro be licensed?

**Comment by kroitor** [comment]
@hroff-1902 it's a commercial (paid) license, monthly or yearly subscription (with discounts), offering several plans (prices) to choose from depending your scale. Top contributors will have free licenses.

**Comment by hroff-1902** [comment]
* For the paid version: who should pay if the library is used in a third-party app, the end-user of the app or the creators of the app?
* For free version: will base ccxt be further licensed under MIT?

**Comment by kroitor** [comment]
> For the paid version: who should pay if the library is used in a third-party app, the end-user of the app or the creators of the app?

It depends on the business model and the nature of the App – whether it is open-source or not, whether it's a commercial SaaS or not, etc... In other words, the place of the App in question within the crypto/software space matters. 

In general, a team behind a public open-source project can have its license, and users can buy their own licenses in their turn. On the other hand, if it's a SaaS or a fully-commercial model, you will need a corporate license with a right to redistribute it, choosing among our paid plans.

**Comment by kroitor** [comment]
> For free version: will base ccxt be further licensed under MIT?

Yes, CCXT remains under the MIT license.

**Comment by thomas-leeee** [comment]
Hi kroitor, I would like to help text ccxt pro (WS support). I have some experience with ccxt.async_support and binance WS.

**Comment by kroitor** [comment]
Hi, @thomas-leeee ! Thank you so much for your kind offer! We appreciate it a lot! However, we already have most of the methods of the exchanges listed above, unified and working in all languages. At this time the testing is meant among the top contributors to CCXT. We're doing the finishing work, including the docs, and other things, but I will let you know if we need additional manpower in the nearest future. Thanks again!

**Comment by lookis** [comment]
Any news? :)

**Comment by kroitor** [comment]
@lookis we are almost all set and we will post the release date within a couple of days. Thx for your patience. Plz stand by for new announcements that will follow shortly.

**Comment by n01ukn0w** [comment]
Release???

**Comment by hroff-1902** [comment]
I guess in February... (*)

(*) February happens every year, so it's almost impossible to miss this deadline.

**Comment by kroitor** [comment]
We will release CCXT Pro on the 1st of March 2020.

**Comment by omidkrad** [comment]
Great news! I want to include some of my wish list for CCXT here:
- Convert the project to TypeScript (makes life easier for all developers, especially the CCXT team)
- Provide an official CCXT docker micro-service. There is [ccxt-rest](https://ccxt-rest.io) but I don't know how much up-to-date it is with latest CCXT.
- Support Interactive Brokers API (not a crypto exchange, but many strategies also work on stocks, forex, etc)
- Integration with QuantConnect Lean https://github.com/QuantConnect/Lean/issues/3793, a popular automated trading platform with backtesting.

**Comment by kroitor** [comment]
@omidkrad 

> Convert the project to TypeScript (makes life easier for all developers, especially the CCXT team)

This is in the works: https://github.com/ccxt/ccxt/pull/5000
We need a transpileable version for [obvious reasons](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support).

> Provide an official CCXT docker micro-service. There is ccxt-rest but I don't know how much up-to-date it is with latest CCXT.

Great idea! Will get to it as soon as possible. Community help is welcome )

> Support Interactive Brokers API (not a crypto exchange, but many strategies also work on stocks, forex, etc)
> Integration with QuantConnect Lean QuantConnect/Lean#3793, a popular automated trading platform with backtesting.

Need to do some homework for these two, but yeah, why not.

**Comment by RomainBlindy** [comment]
Hello,
Is there a manual where i can see how websocket can be used using the future ccxt pro to come ? 
I have never used websockets before so i want to have a look before launch.
Thanks a lot,
Romain

**Comment by kroitor** [comment]
@RomainBlindy we will open the website soon, including the docs, in the meantime, the very basic examples of real-time websocket order books feeds would look like:

### JavaScript

```JavaScript
'use strict';
const ccxtpro = require ('ccxt.pro');
(async () => {
    const exchange = new ccxtpro.binance ({ enableRateLimit: true })
    while (true) {
        const orderbook = await exchange.watchOrderBook ('ETH/BTC')
        console.log (new Date (), orderbook['asks'][0], orderbook['bids'][0])
    }
}) ()
```

### Python

```Python
import ccxtpro
import asyncio

async def main():
    exchange = ccxtpro.poloniex({'enableRateLimit': True})
    while True:
        orderbook = await exchange.watch_order_book('ETH/BTC')
        print(orderbook['asks'][0], orderbook['bids'][0])

asyncio.get_event_loop().run_until_complete(main())
```

### PHP

```PHP
require_once 'vendor/autoload.php';

$loop = \React\EventLoop\Factory::create();
$exchange = new \ccxtpro\bitfinex(array('enableRateLimit' => true, 'loop' => $loop));

$main = function () use (&$exchange, &$main) {
  $exchange->watch_order_book('ETH/BTC')->then(function($ob) use (&$main) {
    echo date('c '), json_encode(array($ob['asks'][0], $ob['bids'][0])), "\n";
    $main();
  });
};

$loop->futureTick($main);
$loop->run ();
```

From the above you can carry that the usage of CCXT Pro is in many ways similar to CCXT.

**Comment by MohammadrezaNargesi** [comment]
Hi kroitor,
I use pip3 install ccxtpro to get the package. 
but after importing ccxtpro, there is no way to access the exchange name by 
using the following command : 
exchange = ccxtpro.poloniex({'enableRateLimit': True})
and the following error pops up:
module 'ccxtpro' has no attribute 'poloniex'
Would appreciate if you help me with the solution.
Sincerely

**Comment by kroitor** [comment]
@MohammadrezaNargesi you're a bit too soon ) We are going to release it within a few hours along with the installation instructions. The `pip3 install ccxtpro` will install an empty stub module that does not have anything inside it. The actual correct installation instructions will be published shortly. Also, in order to install it one has to obtain a license first, which will be available on CCXT Pro's website soon. We will announce the news soon.

**Comment by kroitor** [comment]
Hello again, everyone!

We have released [CCXT Pro](https://ccxt.pro): 

- https://github.com/ccxt/ccxt/issues/6543 )

Thank you to all who have been waiting for it!
As always, your feedback is appreciated a lot!
