### ISSUE TITLE
Bitmex URL Index Issue

### ISSUE THREAD

**Issue by bigcountry-scav** [ccxt/ccxt#6333]
- OS: Windows 10
- Programming Language version: Python
- CCXT version: 1.21.25
- Exchange: Bitmex
- Method: All

There appears to be an index issue on line 1199 

current - url = self.urls['api'][api] + query

I believe it should read

url = self.urls['api'] + query

**Comment by kroitor** [comment]
> I believe it should read
> url = self.urls['api'] + query

No, because `self.urls['api']` is a dict now as of 1.21.25: 

- https://github.com/ccxt/ccxt/commit/72c6fdae7b0ef5bc482b4ef321e5b16c0a257a70#diff-c23b6c3f281ff38df587025321e40445R42
- https://github.com/ccxt/ccxt/blob/master/js/bitmex.js#L42

Let me know if that does not answer the question.

**Comment by bigcountry-scav** [comment]
That would make sense except it is not a dict from the pip update I just ran.

self.urls

`{'api': 'https://testnet.bitmex.com',
 'doc': ['https://www.bitmex.com/app/apiOverview',
         'https://github.com/BitMEX/api-connectors/tree/master/official-http'],
 'fees': 'https://www.bitmex.com/app/fees',
 'logo': 'https://user-images.githubusercontent.com/1294454/27766319-f653c6e6-5ed4-11e7-933d-f0bc3699ae8f.jpg',
 'referral': 'https://www.bitmex.com/register/rm3C16',
 'test': 'https://testnet.bitmex.com',
 'www': 'https://www.bitmex.com'}
`
error on run

`
 url = self.urls['api'][api] + query
TypeError: string indices must be integers
`

**Comment by kroitor** [comment]
It's a dict in the most recent version 1.21.25: https://github.com/ccxt/ccxt/blob/master/python/ccxt/bitmex.py#L51

I suggest you to check your CCXT version in runtime first:

```
import ccxt
print ccxt.__version__
```

**Comment by kroitor** [comment]
@bigcountry-scav sorry, it looks like you're using the testnet, in that case you need to change your instantiation config a bit:

```Python
exchange = ccxt.bitmex({
    'urls': {
        'api': 'https://testnet.bitmex.com',
    },
})
```

↓

```Python
exchange = ccxt.bitmex({
    'urls': {
        'api': {
            'public': 'https://testnet.bitmex.com',
            'private': 'https://testnet.bitmex.com', 
        },
    },
})
```

Let me know if that does not help.

**Comment by kroitor** [comment]
@bigcountry-scav i've added a fix for that to the bitmex `describe()` method and it should work normally (as it did before) as of 1.21.26. We will be happy if you report back whether it does resolve the issue for you or not. Thx!

**Comment by bigcountry-scav** [comment]
Thanks yes that resolves the issue from quick testing.
