### ISSUE TITLE
Poloniex returns "Nonce must be greater than ..."

### ISSUE THREAD

**Issue by jkjin7** [ccxt/ccxt#6335]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Ubuntu 18.04
- Programming Language version: nodejs
- CCXT version: 1.20.x ~ 1.21.27
- Exchange: Poloniex
- Method: createOrder and fetchOrder

When I use createOrder or fetchOrder or some other method on Poloniex, sometimes I get this message from poloniex
`poloniex {"error":"Nonce must be greater than 1578016987567. You provided 1578016987442."}`

This happens with about 5~10% chance, I have seen this error for several months.
Today I noticed there are some updates on ccxt.js.poloniex, updated and tested for a while and then report the problem here.

**Comment by kroitor** [comment]
@jkjin7 sounds like you're not using the rate-limiter properly:

- https://github.com/ccxt/ccxt/search?q=Nonce+must+be+greater+than&type=Issues
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/issues/6024

Hope that answers the question.

**Comment by jkjin7** [comment]
> @jkjin7 sounds like you're not using the rate-limiter properly:
> 
> * https://github.com/ccxt/ccxt/search?q=Nonce+must+be+greater+than&type=Issues
> * https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
> * #6024
> 
> Hope that answers the question.

I will look into that on next monday with your advice, sorry that I’ve not searched enough. Thank you!

**Comment by kroitor** [comment]
@jkjin7 in short you should add the `'enableRateLimit': true` option to your exchange constructor params, like shown below:

```JavaScript
const exchange = new ccxt.poloniex ({ enableRateLimit: true })
```

That should resolve the issue. Let us know if you have difficulties with it.
