### ISSUE TITLE
respect Set-Cookie header in Node.js (could help w/cloudflare, incapsula etc)

### ISSUE THREAD

**Issue by wizzard0** [ccxt/ccxt#6338]
- OS:
`Microsoft Windows [Version 10.0.18362.535]`
- Programming Language version:
`Node.js v10.15.3`
- CCXT version:
`v1.21.30`
- Exchange:
`(cloudflare-protected exchange)`
- Method:
`(all methods)`

Examining the outgoing HTTP traffic with Fiddler, I see that on every request to cloudflare-protected exchange, cloudflare tries to Set-Cookie which then gets ignored when run from Node. 

With ccxt loaded in the browser, the browser keeps the cookie and sends it. Maybe it's better to send this cookie with next requests and it will make situation with ddos protection better?

(if it actually makes it worse - then let's document it here, bc I havent found anything relevant in the docs)

**Comment by kroitor** [comment]
> and it will make situation with ddos protection better?

Do you have DDOSProtection exceptions with some particular exchange?

> (if it actually makes it worse - then let's document it here, bc I havent found anything relevant in the docs)

It appears to be making things worse with some exchanges (at least in PHP): https://github.com/ccxt/ccxt/issues/6196#issuecomment-559829165

In general, we don't intercept exchange-specific or provider-specific cookies, but we allow the user to control cookies if needed: 

```JavaScript
'use strict'
;(async () => {
    const ccxt = require('./ccxt')
        , exchange = new ccxt.binance ({ enableRateLimit: true })
    console.log (exchange.iso8601 (await exchange.fetchTime ()))
    exchange.headers['Cookie'] = exchange.last_response_headers['Set-Cookie']

    // your code to test here

}) ()
```

Related: https://github.com/node-fetch/node-fetch/issues/146.

Let us know if that does not resolve the issue.
