### ISSUE TITLE
[bleutrade] isn't working anymore... needs updating

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6341]
> {"success":false,"message":"Version 2 has become obsolete and can no longer be used. You must migrate to version 3 (https://app.swaggerhub.com/apis/bleu/white-label/3.1.0).","result":"OBSOLETE"}

Last time I tried v3 it simply didn't work :(

**Comment by npomfret** [comment]
@kroitor I'm making some progress with a rewrite of bleutrade, although it's still pretty bad.  Are you ok with me removing the inheritance (`... extends bittrex`)?  I don't think it's helping, the APIs have some similarity in terms of response json, but not that much.

**Comment by kroitor** [comment]
@npomfret 

> Are you ok with me removing the inheritance (... extends bittrex)? I don't think it's helping, the APIs have some similarity in terms of response json, but not that much (the tickers and orderbooks are the same I think except for the urls)

Absolutely!

**Comment by npomfret** [comment]
https://github.com/ccxt/ccxt/pull/6371
