### ISSUE TITLE
find_symbol deprecated, analog?

### ISSUE THREAD

**Issue by CooleRnax** [ccxt/ccxt#6342]
I need to convert local (bitfinex) symbol to ccxt symbol.
Before I used find_symbol, now it is not available.
How can I do it now?

**Comment by frosty00** [comment]
Hi @CooleRnax,

You can use the following code

```
if (marketId in this.markets_by_id) {
    market = this.markets_by_id[marketId];
    symbol = market['symbol'];
```

**Comment by CooleRnax** [comment]
thanks!

**Comment by kroitor** [comment]
@CooleRnax more about it here (see examples below): https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
