### ISSUE TITLE
fcoinjp fetch_ticker() error

### ISSUE THREAD

**Issue by StnadardUsre** [ccxt/ccxt#6347]
- OS: Win 10
- Programming Language version: Python 3.8.1 x64
- CCXT version: 1.21.37
- Exchange: fcoinjp 
- Method: fetch_ticker()

The following code:
```
f = ccxt.fcoinjp()
f.fetch_ticker('MONA/USDT')
```
returns the following exception:

> Traceback (most recent call last):
>   File "file.py", line 35, in <module>
>     f.fetch_ticker('MONA/USDT')
>   File "C:\Python\lib\site-packages\ccxt\fcoin.py", line 366, in fetch_ticker
>     return self.parse_ticker(ticker['data'], market)
>   File "C:\Python\lib\site-packages\ccxt\fcoin.py", line 388, in parse_ticker
>     'bid': float(values[2]),
> **TypeError: float() argument must be a string or a number, not 'NoneType'**

I think it's related to USD/USDT naming inconsistency, but not sure, how to fix it.

**Comment by kroitor** [comment]
Fixed in 1.21.38. Thank you for reporting!
