### ISSUE TITLE
okex3 didnt response real assets

### ISSUE THREAD

**Issue by jyj545** [ccxt/ccxt#6350]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:linux
- Programming Language version:js
- CCXT version:1.21.14
- Exchange:okex
- Method:fetchBalance

it doesnt response real asset number,it return an empty objects with four attributes, etc:   
    okex3.fetchBalance().then(balance => {console.log(balance)})
    free:Object {}
info:Array(0) []
total:Object {}
used:Object {}
buy my real assets is 200 usdt and 1000 trx.

**Comment by kroitor** [comment]
> it doesnt response real asset number

It does, but by default it will return your spot trading balance. That's explained here: https://github.com/ccxt/ccxt/issues/5849#issuecomment-533844167

Check out the code around these lines:

- https://github.com/ccxt/ccxt/blob/master/js/okex3.js#L449
- https://github.com/ccxt/ccxt/blob/master/js/okex3.js#L1344

```JavaScript
'use strict';
const ccxt = require('ccxt')
;(async () => {
    const enableRateLimit = true
    const apiKey = 'YOUR_API_KEY'
    const secret = 'YOUR_API_SECRET'
    const okex3 = new ccxt.okex3 ({ 
        enableRateLimit,
        apiKey,
        secret,
        options: {
            'defaultType': 'spot' // 'account', 'spot', 'margin', 'futures', 'swap'
        } 
    })

    // ----------------------------------------------------------
    let params = {}
    let balance = await okex3.fetchBalance(params)
    console.log ('Default spot trading balance:', balance)

    // ----------------------------------------------------------
    params = {
        type: 'account',
    }
    balance = await okex3.fetchBalance(params)
    console.log ('Main account balance:', balance)
}) ()
```

Let us know if that does not answer the question.

**Comment by jyj545** [comment]
thx for your account　help.it works.
