### ISSUE TITLE
OCO order on binance has type=='limit_maker' and status=='expired'.

### ISSUE THREAD

**Issue by dmitriano** [ccxt/ccxt#6352]
OS: Windows 10
Programming Language version: JavaScript v8.12.0
CCXT version: 1.18.1353
Exchange: binance
Method: exchange.fetchClosedOrders(symbol)

If I create OCO order on binance as described [here](https://github.com/ccxt/ccxt/issues/6192) or manually in binance web interface and then call exchange.fetchClosedOrders(symbol) after the order was closed or cancelled I get order objects that may have type=='limit_maker' or status=='expired'.

1) Does CCXT imply some restrictions on `type` and `status` values?

2) What `type` and `status` values could be in possible implementations of OCO order? I'll use them for a workaround in my code. Currently I use 'limit' and 'canceled' respectively with a code like this:

`
            if (order.type === 'limit_maker')
            {
                order.type = 'limit';
            }

            if (order.status === 'expired')
            {
                order.status = 'canceled';
            }

`

As I can see from [docs](https://github.com/ccxt/ccxt/wiki/Manual#order-structure), the possible values of `status` and `type` are:
`
     'status':  'open', 'closed', 'canceled',
    'type':   'market', 'limit'
`

**Comment by kroitor** [comment]
> Does CCXT imply some restrictions on type and status values?

Yes, however, the process of unifying all the statuses is still going on. We usually support `limit` and `market` orders in general, but some exchanges may have other specific types of orders, with Binance in particular there are two types (`LIMIT` and `LIMIT_MAKER`), and the difference is that LIMIT can be a taker in case if you cross the price spread.

Check out these lines for example https://github.com/ccxt/ccxt/blob/4dcca48f3c3341ea5f621a359b1eb8bde7a8af75/js/binance.js#L907

However, you're right, in most cases LIMIT_MAKER can be treated as a LIMIT order and the EXPIRED status basically means that the order is canceled, so I added a few edits there:

And it should work without the userland overrides as of version 1.21.39 (will be available for downloading in 15 minutes). Let us know if you still have difficulties with it after the update.
