### ISSUE TITLE
COSS is not reachable

### ISSUE THREAD

**Issue by brandsimon** [ccxt/ccxt#6354]
The COSS API is not reachable since a few days.
Fetching `https://trade.coss.io/c/coins/getinfo/all` results in
```
ExchangeNotAvailable: coss GET https://trade.coss.io/c/coins/getinfo/all 502 Bad Gateway 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
 (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)
```

CCXT Version: 1.21.39
Am I the only one with this issue? Their API docs dont seam to be updated lately:
https://api.coss.io/v1/spec

**Comment by kroitor** [comment]
> Am I the only one with this issue? 

Nope:

- https://www.reddit.com/r/CryptoCurrency/comments/elddl8/coss_exchange_has_suspended_all_withdrawals/
- https://decrypt.co/16119/coss-exchange-unexpectedly-locks-its-users-out-for-up-to-a-month
- https://medium.com/coss-official/coss-is-upgrading-to-a-more-advanced-platform-deade877a0ac

**Comment by brandsimon** [comment]
Ah, thank you very much, I just search in the issues, should have used a global search engine.
