### ISSUE TITLE
FTX timeframe for 1d is hardcoded as 24hr, issues then when using bots that rely on ccxt to query the 1d timeframes

### ISSUE THREAD

**Issue by Dante2333** [ccxt/ccxt#6358]
As stated, ftx timeframes are hardcoded as 24hr instead of 1d, this is not the same for other exchanges, say binance where 24hr is 1d https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L53

- OS: Ubuntu 
- Programming Language version: python
- CCXT version: latest
- Exchange: ftx
- Method: https://github.com/ccxt/ccxt/blob/master/python/ccxt/ftx.py#L53

**Comment by kroitor** [comment]
Should be ok as of 1.21.44. Thx for reporting!
