### ISSUE TITLE
(Okex) How to see min and max withdrawal fee

### ISSUE THREAD

**Issue by stephencostiniano** [ccxt/ccxt#6359]
OS: Windows 10
Programming Language version: Python 3.7.4
CCXT version: 1.19.54
Exchange: Okex
Method: fetchCurrencies()

Hello I'm trying to get the min withdrawal fee for Okex I'm trying to use fetchCurrencies() but the fee section is None 

How could I replicate the Okex API response 
`{
        "currency":"BTC",
        "max_fee":0.02,
        "min_fee":0.0005
    },
    {
        "currency":"LTC",
        "max_fee":0.2,
        "min_fee":0.001
    },
    {
        "currency":"ETH",
        "max_fee":0.2,
        "min_fee":0.01
    }`

this response using ccxt 
Thank you so much

**Comment by kroitor** [comment]
You want to use the [implicit API methods](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods), `accountGetWithdrawalFee()` or `account_get_withdrawal_fee` in particular:

```Python
import ccxt
exchange = ccxt.okex3({
    # YOUR_API_CREDENTIALS_HERE
})

print(exchange.account_get_withdrawal_fee())
```

Hope that helps, let us know if not.

**Comment by stephencostiniano** [comment]
Thankyou  @kroitor it works perfectly helped me a lot
