### ISSUE TITLE
Incorrect "Side" parameter in Foxbit (Blinktrade)

### ISSUE THREAD

**Issue by leogariba** [ccxt/ccxt#636]
The API is setting this order parameter Side = "Buy"

The correct value for a buy order is Side = "1"
The correct value for a sell order is Side = "2"

Nice work btw!

**Comment by kroitor** [comment]
Hi! Can you please post your code and verbose output? You didn't even say which endpoint you're using. If you mean the output of fetchTrades – for the `side` received from the Unified API the correct values are "buy" or "sell".

https://github.com/ccxt/ccxt/wiki/Manual#returned-json-objects
https://github.com/ccxt/ccxt/wiki/Manual#trades-orders-executions-transactions
https://github.com/ccxt/ccxt/wiki/Manual#api-methods--endpoints

I'm closing this, if you don't mind, until we have a follow up. Feel free to reopen it if the above does not make it clear.
