### ISSUE TITLE
[kucoin] error mapping for 'DDoSProtection' could be 'RateLimitExceeded'

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6361]
The exchange emits the text `Exceeded the access frequency` when rate limits are exceeded.

Excuse the formatting...

`{ DDoSProtection: kucoin DELETE https://openapi-v2.kucoin.com/api/v1/orders/foo 418 I'm a Teapot Too Many Bad Auth - Exceeded the access frequency.\n\n    at kucoin.defaultErrorHandler ...
`

**Comment by kroitor** [comment]
Added it in 1.21.45, thx!
