### ISSUE TITLE
FTX - Futures

### ISSUE THREAD

**Issue by interenet** [ccxt/ccxt#6362]
Hello

Does not show futures positions. 
How to look?

fetchBalance gives information only on coins

- Python 3.6.9
- ccxt (1.21.17)
- https://ftx.com/

thanks

**Comment by kroitor** [comment]
@interenet you want to use [implicit API methods](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods) as described in the Manual:

```Python
import ccxt
from pprint import pprint

exchange = ccxt.ftx({
    'enableRateLimit': True,  # required by the Manual https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

pprint(exchange.private_get_positions())
```

In general, we recommend to read the entire Manual from top to bottom at least once – it has most of the answers in it already. Hope that answers your question, let us know if not.
