### ISSUE TITLE
FTX has precision wrong in load_markets dict

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#6364]
- OS: Linux
- Programming Language version: python
- CCXT version:  1.21.49
- Exchange: FTX
- Method: load_markets

When using load_markets with FTX, the "precision" and "price" values are not aligned to other exchanges.

``` python
import ccxt
ct = ccxt.ftx()
lm = ct.load_markets()
print(lm['BTC/USD']['precision'])
```
```
{'amount': 0.0001, 'price': 0.5}
```

I would expect to get output similar to binance, which would be something around
`{'amount': 4, 'price': 1}`.

``` python
import ccxt
ct = ccxt.binance()
lm = ct.load_markets()
print(lm['BTC/USDT']['precision'])
```
```
{'base': 8, 'quote': 8, 'amount': 6, 'price': 2}
```

Now maybe this is expected behaviour - however the [documentation](https://github.com/ccxt/ccxt/wiki/Manual#market-structure) states differently:

> `precision`. The amounts of decimal digits accepted in order values by exchanges upon order placement for price, amount and cost.

based on `The amounts of decimal digits accepted` above, i assume FTX should use  4 as well - not 0.0001.

**Comment by kroitor** [comment]
@xmatthias Hi! Please, see the explanation of precisionMode TICK_SIZE here: 

- https://github.com/ccxt/ccxt/pull/5256
- https://github.com/ccxt/ccxt/pull/5055

In general we have several families of precisionMode – SIGNIFICANT_DIGITS, DECIMAL_DIGITS, TICK_SIZE. FTX implements TICK_SIZE precision mode:

- https://github.com/ccxt/ccxt/blob/master/js/ftx.js#L155

WIth that precision mode the values in `market['precision']` will be minimal float fractions, not the numbers of decimal digits.

Some other exchanges like BitMEX do have this precision mode as well.

Let me know if that does not answer the question.

**Comment by hroff-1902** [comment]
> `Curiouser and curiouser!' cried Alice
😄

**Comment by kroitor** [comment]
Added more clarifications to the Manual on this:

- https://github.com/ccxt/ccxt/wiki/Manual#market-structure
- https://github.com/ccxt/ccxt/wiki/Manual#methods-for-formatting-decimals

Hope it helps.
