### ISSUE TITLE
Preflight request for request with keepalive specified is currently not supported

### ISSUE THREAD

**Issue by bongkook** [ccxt/ccxt#6368]
I am using CCXT in a Chrome browser via a proxy server.
When using the latest version of ccxt, the following error occurred:
"Preflight request for request with keepalive specified is currently not supported"
What is the cause?

**Comment by kroitor** [comment]
@bongkook what's your version of CCXT?

**Comment by bongkook** [comment]
@kroitor I was using version 1.19.90 without a problem
The error occurred when I was using 1.21.55.

**Comment by kroitor** [comment]
@bongkook this appears to be a bug in Chrome:

- https://bugs.chromium.org/p/chromium/issues/detail?id=810466
- https://bugs.chromium.org/p/chromium/issues/detail?id=835821

So, i've commented it out and it should work fine in Chrome as of 1.21.56. The new build will arrive in 15 minutes. We will be happy if you report back whether it does resolve the issue for you or not. Thank you!
