### ISSUE TITLE
Emulate OHLCV with transactions

### ISSUE THREAD

**Issue by flesler** [ccxt/ccxt#637]
In some exchanges, at least Bitstamp, you could request the last day of transactions and generate the OHLCV from it, it's not ideal but could allow many exchanges to have support for fetchOHLCV when they don't.

**Comment by kroitor** [comment]
Hi! Thanks for the hint and or the feedback! We will add fetchOHLCV for Bitstamp. BTW, we will be happy if you submit a PR on this, your contributions are welcome!

**Comment by flesler** [comment]
When you say you will add it, you mean if I provide a PR or in some other way?

I could make a PR, thing is I can do it easily with Node.js, but your source for all is Python or PHP no?

**Comment by kroitor** [comment]
@flesler 

> When you say you will add it, you mean if I provide a PR or in some other way?

I mean, we will add it anyway. We will implement it ourselves hopefully soon if you don't submit a PR before that. Yet we will be happy if you do submit a contribution. If we knew that you are working on implementing the fetchOHLCV for Bitstamp, we would then focus our attention on other aspects of the library to distribute the workload, of course.

> I could make a PR, thing is I can do it easily with Node.js, but your source for all is Python or PHP no?

The master language is JS, we convert to PHP and Python from JS automatically by a custom transpiler script. More about it here:
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

Thanks!

**Comment by kroitor** [comment]
The work on this has been started by @mkutny [here](https://github.com/ccxt/ccxt/pull/695). We will merge it soon.
