### ISSUE TITLE
How to Withdraw USDT-TRC20 in Okex

### ISSUE THREAD

**Issue by stephencostiniano** [ccxt/ccxt#6374]
- OS: Windows 10
- Programming Language version: Python 3.7.4
- CCXT version: 1.21.45
- Exchange: Okex
- Method: withdraw

Hello Can I ask the right parameter to be used when I execute a USDT withdrawal using TRX Network

I've tried using these parameters 
`params = {
            'fee': 0,
            'network': 'TRX'}`
`çurrency = 'USDT'`

but I still receive
ccxt.base.errors.InvalidAddress: okex3 {"code":34002,"message":"Withdrawal address does not exist"}

Many Thanks,
Stephen

**Comment by kroitor** [comment]
Hi!

As far as I see from the OKEX website, at this time the only supported protocol for USDT withdrawals is TRC-20, therefore I suppose you just specify USDT and that's it.

<img width="565" alt="Screen Shot 2020-01-14 at 13 34 32" src="https://user-images.githubusercontent.com/1294454/72337768-2c27e480-36d4-11ea-8f6f-c241fd424346.png">

So, in case of OKEX v3 (`okex3`), you don't have to specify the network argument, since OKEX does not support it anyway (it's Binance specific). And your call would look close to:

```Python
exchange = ccxt.okex3 ({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'password': 'YOUR_TRADE_PASSWORD',
    'enableRateLimit': True,
}}

code = 'USDT'
amount = YOUR_AMOUNT
address = 'DESTINATION_TRX_ADDRESS'
tag = None
params = {
    'fee': YOUR_FEE_SETTING,  # should be greater than zero I guess
}

exchange.withdraw (code, amount, address, tag, params)
```

Let us know if that does not help.

**Comment by stephencostiniano** [comment]
Hello, I tried removing the network in the parameters I still receive the error.

**Comment by kroitor** [comment]
@stephencostiniano have you added the TRC20 address you're trying to withdraw to – to your address book using the okex website first? Because they require all addresses to be preconfigured with the website. Can you check that out?

**Comment by stephencostiniano** [comment]
I got a new error after adding the address
ccxt.base.errors.AuthenticationError: okex3 {"code":34018,"message":"Wrong fund password"}
Do I need an extra parameter for this one ?

**Comment by kroitor** [comment]
@stephencostiniano 

> I got a new error after adding the address

Alright, making progress towards the goal.

> Do I need an extra parameter for this one ?

You can add that parameter alongside your credentials, as shown in the snippet above (and below), or, as you said, you can also specify it as an extra parameter in `params`. Both ways are equivalent. In your case, however, the password seems to be already there, but the OKEX system says that it's wrong. So you may want to check if that password is correct, one of the common pitfalls here is confusing the fund password with the login password.

```Python
exchange = ccxt.okex3 ({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'password': 'YOUR_FUND_PASSWORD',  # ←---------- HERE
    'enableRateLimit': True,
}}

code = 'USDT'
amount = YOUR_AMOUNT
address = 'DESTINATION_TRX_ADDRESS'
tag = None
params = {
    # 'password': 'YOUR_FUND_PASSWORD',  # ←------------ or HERE
    'fee': YOUR_FEE_SETTING,  # should be greater than zero I guess
}

exchange.withdraw (code, amount, address, tag, params)
```

Let me know if that does not work.

**Comment by stephencostiniano** [comment]
I tried changing the password upon for Okex but I got this error 
ccxt.base.errors.AuthenticationError: okex3 {"code":30015,"message":"Invalid OK_ACCESS_PASSPHRASE"}

I also tried adding a new parameter in the fund password then I get the previous error again with the wrong fund password

**Comment by kroitor** [comment]
@stephencostiniano does that same password work for you if you copypaste it directly from your code into the okex website withdrawal form and try a manual withdrawal with that fund password?

**Comment by stephencostiniano** [comment]
Yes it worked perfectly fine when I copy-paste the fund password from my code

**Comment by stephencostiniano** [comment]
I tried directly switching the code of withdraw to 

`        if 'password' in params:
            request['trade_pwd'] = params['password']`
`          elif self.password:
            request['trade_pwd'] = self.password`
previous code was 
`        if self.password:
            request['trade_pwd'] = self.password`
`        elif 'password' in params:
            request['trade_pwd'] = params['password']`

since self password is declared upon instantiation I think the code does not proceed to the elif statements

**Comment by kroitor** [comment]
@stephencostiniano i will look into it and will add a fix there, thx for pointing that out!

**Comment by kroitor** [comment]
@stephencostiniano 

Actually, the current code in withdraw is this:

```
        if self.password:
            request['trade_pwd'] = self.password
        elif 'password' in params:
            request['trade_pwd'] = params['password']
        elif 'trade_pwd' in params:
            request['trade_pwd'] = params['trade_pwd']
```

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/okex3.py#L2004

Are you sure that you have a new version of CCXT? Do you have the same bug with the most recent version of it?

I'd recommend to check your runtime version with this short snippet:

```Python
import ccxt
print(ccxt.__version__)
```

Let me know if this is version-related thing.

**Comment by stephencostiniano** [comment]
Yes I switched it into 
`        if 'password' in params:
            request['trade_pwd'] = params['password']`
`          elif self.password:
            request['trade_pwd'] = self.password`

**Comment by kroitor** [comment]
@stephencostiniano ok, i've uploaded that edit and it will arrive in version 1.21.59 in 15 minutes. Hope that helps. Thank you!

**Comment by stephencostiniano** [comment]
Thank you @kroitor  I'll wait for the new version to test it out

**Comment by drewUCL** [comment]
- OS: Windows 10
- Programming Language version: Python 3.7.5
- CCXT version: 1.48.25
- Exchange: Okex
- Method: withdraw

Seem to be getting the same issue as previously reported.

**Code:**
```
exchange = ccxt.okex({
    'apiKey': '__PUBLIC__', 
    'secret': '__PRIVATE__',
    'password': '__PWD__',
    'enableRateLimit': True
})

code = 'USDT'
amount = '10'
address = '__EXTERNAL_ADDRESS__'
tag = None
params = {'fee': '1'}

exchange.withdraw (code, amount, address, tag, params)
``` 

**Error**
```
AuthenticationError: okex {"error_message":"Invalid OK_ACCESS_PASSPHRASE","code":30015,"error_code":"30015","message":"Invalid OK_ACCESS_PASSPHRASE"}
```

Any thoughts on this? Seems like the proposed changes were implemented in-line with the above investigation.
