### ISSUE TITLE
Binance api inconsistency in combination with defaultType 

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#6376]
- OS: linux
- Programming Language version: python
- CCXT version:  1.21.59
- Exchange: binance
- Method: all / several

Binance supports "easy" switching to the futures api by initializing with `ccxt.binance({'defaultType': 'future'}` - which will then internally swaps some/most endpoints to use the FAPI endpoints.

I think this same approach should be applied to the margin API with `ccxt.binance({'defaultType': 'margin'}` - using the sapi endpoints.

Currently, specifying `'defaultType': 'margin'` will have ccxt use the futures API, as it'll end up in the "else" tree within all methods. 

https://github.com/ccxt/ccxt/blob/a7cb7d65fc1d5d8acbb8ae290a7107b4ddae1fbd/python/ccxt/binance.py#L495

**Comment by kroitor** [comment]
Will do our best to address this shortly. Thx for reporting!
