### ISSUE TITLE
Question: getting a commission on binance ( php ) 

### ISSUE THREAD

**Issue by StasToken** [ccxt/ccxt#6377]
Hi - I was a little poking around in the documentation but still could not find the answer to my question, something was mentioned there about _FetchFundingFees_ But I did not find the methods themselves, I'm interested in how to upload information on commission fees for trade? 
I think the information I need is [here](https://binance-docs.github.io/apidocs/spot/en/#trade-fee-user_data) apparently - but how can I get it through ccxt to PHP?

**Comment by kroitor** [comment]
Hi!

1. Update to version 1.21.60
2. Try this code:

```PHP
$exchange = new \ccxt\binance(array(
    'apiKey' => 'YOUR_API_KEY',
    'secret' => 'YOUR_API_SECRET',
    'enableRateLimit' => true,
));

var_dump($exchange->fetch_trading_fee('ETH/BTC')); // fetch by one symbol
var_dump($exchange->fetch_trading_fees()); // fetch all symbols
var_dump($exchange->wapi_get_tradefee()); // fetch using implicit endpoints
```

> but how can I get it through ccxt to PHP?

You can call those endpoints using implicit API methods as described here:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

However, we suggest to use the unified `fetchTradingFee` and `fetchTradingFees` as shown above. The fee unification is a work in progress atm, therefore some structures may change and are not documented yet.

Let us know if the above does not help.

**Comment by StasToken** [comment]
Listen - does he definitely unload commissions? I have a commission of 0.001 for "maker" - although for some reason it seems to me that this is not so 
```
array:4 [
  "info" => array:3 [
    "symbol" => "BTCUSDT"
    "maker" => 0.001
    "taker" => 0.001
  ]
  "symbol" => "BTC/USDT"
  "maker" => 0.001
  "taker" => 0.001
]

```
[img](http://zalil.su/9974388)

**Comment by StasToken** [comment]
Checked right now - the valid gives 0.001 strange

**Comment by kroitor** [comment]
@StasToken yes, i'm pretty sure those numbers are the ones you get from Binance (we don't change them on the fly, and you can see the raw structure received from Binance in the `info` field in that same snippet above).

- https://www.binance.com/en/fee/schedule

Make sure you don't confuse accounts and their corresponding API keys.
