### ISSUE TITLE
fetchOrders error for okex

### ISSUE THREAD

**Issue by tandazhi** [ccxt/ccxt#639]
`import ccxt
p=ccxt.okex()
p.apiKey='api_key'
p.secret='sec_token'
p.fetchOrders('LTC/BTC',{'status':'open'})
`
fetchOrders raised below errors, did I call the fetchOrders function not correctly? 
> Traceback (most recent call last):
>   File "multispots-hedge.py", line 258, in <module>
>     orders=trade.exchanges[2].exchange.fetchOrders('LTC/BTC',{'status':'open'})
>   File "C:\Python36\lib\site-packages\ccxt\okcoinusd.py", line 458, in fetch_orders
>     raise ExchangeError(self.id + ' fetchOrders() requires type param or status param for spot market ' + symbol + '(0 or "open" for unfilled orders, 1 or "closed" for filled orders)')
> ccxt.base.errors.ExchangeError: okex fetchOrders() requires type param or status param for spot market LTC/BTC(0 or "open" for unfilled orders, 1 or "closed" for filled orders)

**Comment by kroitor** [comment]
> did I call the fetchOrders function not 

Not really... The correct signature is:

```
exchange.fetchOrders (symbol = undefined, since = undefined, limit = undefined, params = {})
```

So, you should call it like this:

```Python
limit = None
since = None
p.fetch_orders('LTC/BTC',since,limit,{'status':'open'})
```

Let us know if doesn't work for you, plz.

**Comment by tandazhi** [comment]
yeah, it works now. Thanks very much, Kroitor.

**Comment by kroitor** [comment]
@tandazhi I forgot to mention, it was changed here: https://github.com/ccxt/ccxt/issues/470
