### ISSUE TITLE
Market Order Amount [Binance]

### ISSUE THREAD

**Issue by ElanJM** [ccxt/ccxt#6391]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10
- Programming Language version: Python 3
- CCXT version: 1.21.64
- Exchange: Binance
- Method: Create Market Order

i need help. I don't have problem with creating market order type, but what i do have is with the amount we put in to create market order.

this is my code:

`exchange.create_order(Pairs, 'market', 'buy', Amount)`

now what i'm asking is how am i able to use the Amount with quote currency instead of the base, because what error i got recently is that, i created a code to calculate how much would i get if i put in for example $10,000 to buy BTC with market order, now from that calculation is what i put in to the 'Amount' in the create order code. but then if the market price move up, then my code would throw a Binance has insufficient balance error.

So my question is, how can i use $10,000 (or whatever is in my balance) as the 'Amount' instead of how much the quote/opposite coin i would get if i buy with $10,000 using Market Order Type.

The exchange i use at the moment is Binance, but maybe i would use my code in to Bitfinex too.

Thankyou.

**Comment by kroitor** [comment]
Hi!

1. Update to CCXT version 1.21.77 (the new build will arrive in 15 minutes)

2. Try this code:

```Python
import ccxt 
exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
    'enableRateLimit': True,
})

amount = 1
price = 10000
cost = amount * price

# this line will use the amount * price to calculate the total cost-to-spend (10000)
exchange.create_order(symbol, 'market', 'buy', amount, price)
```

```Python
import ccxt 
exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
    'enableRateLimit': True,
})

# this line does the same, but you override the cost via extra params
params = {
    'quoteOrderQty': 10000,  # binance-specific
}
amount = None
price = None
exchange.create_order(symbol, 'market', 'buy', amount, price, params)
```

You might also want to check out these issues:

- https://github.com/ccxt/ccxt/issues/5464
- https://github.com/ccxt/ccxt/issues/2707
- https://github.com/ccxt/ccxt/issues/2547
- https://github.com/ccxt/ccxt/issues/847

Apart from that we highly recommend to check out these sections of the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

Let us know if the above does not help.

**Comment by linklee** [comment]
does it work for binance only or for ftx too?

**Comment by frosty00** [comment]
@linklee, yes it is the same for all the exchanges

**Comment by linklee** [comment]
does it work only for market order or for limits as well?

**Comment by kroitor** [comment]
@linklee it depends on the exchange, most of the time it's for market orders only, and the names of the `params` overrides are exchange-specific. Binance, does not accept limit orders with quoteOrderQty, they only allow that for market orders.

**Comment by linklee** [comment]
and what about ftx?

**Comment by kroitor** [comment]
@linklee you can't do that with the FTX API afaik: https://docs.ftx.com/#place-order

**Comment by linklee** [comment]
@kroiter
hello, I am trying to do FTX market order with params like this:
   
 coin='LINK/USDT' 
	  amount = None
	  price  = None
	  o_type = 'market'
	  #market order
	  params = {
    	  'quoteOrderQty': 10, 
	  }
	  ccxt_bot.create_order(coin, o_type, 'buy', amount, price,params)
```



And get this error:
Traceback (most recent call last):


  File "C:\Users\morning\Documents\code\xxx.py", line 81, in start
    ccxt_bot.create_order(coin, o_type, 'buy', amount, price,params)
  File "C:\Program Files\Python39\lib\site-packages\ccxt\ftx.py", line 1057, in create_order
    'size': float(self.amount_to_precision(symbol, amount)),
  File "C:\Program Files\Python39\lib\site-packages\ccxt\base\exchange.py", line 1293, in amount_to_precision
    return self.decimal_to_precision(amount, TRUNCATE, self.markets[symbol]['precision']['amount'], self.precisionMode, self.paddingMode)
  File "C:\Program Files\Python39\lib\site-packages\ccxt\base\decimal_to_precision.py", line 55, in decimal_to_precision
    dec = decimal.Decimal(str(n))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

**Comment by linklee** [comment]
What do I do?

**Comment by kroitor** [comment]
@linklee you should only specify the params supported by the exchange in `params`. FTX does not support the `quoteOrderQty`, since that is Binance-specific. In general, FTX does not support quote orders, you have to specify the amount for a market order: https://docs.ftx.com/#place-order. Let me know if that does not answer your question.

**Comment by linklee** [comment]
So there is no way for ftx to specify currency in usdt and not in Link in usdt/link pair for example?

**Comment by kroitor** [comment]
@linklee No.

There's no such pair as USDT/LINK with FTX. 
FTX has only LINK/USDT. And the CCXT Manual explains that here:

- https://github.com/ccxt/ccxt/wiki/Manual#consistency-of-base-and-quote-currencies

Order amounts in general are always in the base currency (LINK), and not all exchanges support amounts in quote currency (USDT).

**Comment by unster** [comment]
Hi there,

@kroitor question about your first answer:

how to solve the problem with buying expensive tokens while having small budget to spend? I.e. how to calculate the amount to buy for a token price of 41.237 with 50 USD? Math is simple, but how to define correct number of digits after the comma to provide to the function?

I.e. if you can buy min. 0,0001 pieces of given token, how can I determine that I need to round up/down if my calculations deliver 0,000123456789? 

In the app and web version there is a easy way to create order with USDT amount instead of token size. Is it supported by CCXT now?

**Comment by kroitor** [comment]
@unster hi!

> I.e. if you can buy min. 0,0001 pieces of given token, how can I determine that I need to round up/down if my calculations deliver 0,000123456789?

You can do that with basic arithmetic division, while applying precision from the markets:

- https://github.com/ccxt/ccxt/wiki/Manual#markets
- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits
- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders

> In the app and web version there is a easy way to create order with USDT amount instead of token size. Is it supported by CCXT now?

Some exchange support that:

- https://github.com/ccxt/ccxt/wiki/Manual#market-buys
- https://github.com/ccxt/ccxt/issues/9246#issuecomment-847091544
- https://github.com/ccxt/ccxt/search?q=quoteOrderQty&type=issues

**Comment by gambitov** [comment]
Hello @kroitor, if I make a market order using:
`exchange.create_order(symbol, 'market', 'buy', amount, price)`
doesn't price matter? I mean, the order is selled at market price, isn't it?

**Comment by kroitor** [comment]
@gambitov hi! Binance supports quote currency amounts for "how much to spend for buying or selling", and that can be calculated from amount and price (if you submit a price with a market order), that is explained in-depth here: https://github.com/ccxt/ccxt/wiki/Manual#market-buys

**Comment by kroitor** [comment]
@gambitov also, if you don't submit a price it will be a regular market order.
