### ISSUE TITLE
[hitbtc] fetchClosedOrders issue

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6392]
I notice that the hitbtc2 implementation of `fetchClosedOrders` does some internal filtering (to remove _open_ orders).  This of course breaks pagination.  To work around this I use `exchange.last_json_response.length` to get the correct size of the results.

Is my solution considered the _correct_ thing to do?

**Comment by kroitor** [comment]
> Is my solution considered the correct thing to do?

Can you post your verbose output or your last_json_response ? The filtering there will only filter by closed and canceled orders, but, to my understanding, that particular endpoint should not return any other orders and the filtering should not break the pagination, if the pagination is date-based. Need some sample output that breaks it in order to fix this.

**Comment by npomfret** [comment]
> that particular endpoint should not return any other orders 

Ah, interesting. So what is the (first bit of) filtering for, perhaps it can be removed?...

        const orders = [];
        for (let i = 0; i < parsedOrders.length; i++) {
            const order = parsedOrders[i];
            const status = order['status'];
            if ((status === 'closed') || (status === 'canceled')) { // <-- why??
                orders.push (order);
            }
        }
        return this.filterBySinceLimit (orders, since, limit);

The following output is taken at a time when I have one open order in ETH/BTC:

```
    handleRestResponse:
        hitbtc2 GET https://api.hitbtc.com/api/2/history/order?limit=3&offset=0 200 OK 
        Response:
        { Connection: 'keep-alive',
            'Content-Length': '883',
            'Content-Type': 'application/json; charset=utf-8',
            Date: 'Mon, 20 Jan 2020 14:14:23 GMT',
            'Referrer-Policy': 'strict-origin-when-cross-origin',
            'Request-Id': '6c57262886c9cce06f8b256ba0f2943b',
            Server: 'nginx' }
    [
        {"id":196864730766,"clientOrderId":"fa67d286284648058aacc48d834a706d","symbol":"XTZBTC","side":"sell","status":"filled","type":"limit","timeInForce":"GTC","quantity":"10.0","price":"0.00014900","cumQuantity":"10.0","createdAt":"2020-01-17T11:25:32.897Z","updatedAt":"2020-01-17T15:44:40.840Z"},
        {"id":196843936917,"clientOrderId":"132568b3d91e479a9ba97554596f1cc6","symbol":"XTZBTC","side":"sell","status":"canceled","type":"limit","timeInForce":"GTC","quantity":"10.0","price":"0.00014654","cumQuantity":"4.7","createdAt":"2020-01-17T10:10:04.775Z","updatedAt":"2020-01-17T11:10:46.154Z"},
        {"id":196595995374,"clientOrderId":"0c9f7797ef184d65b4f58f5b6f1bc32b","symbol":"XTZBTC","side":"buy","status":"filled","type":"limit","timeInForce":"GTC","quantity":"10.0","price":"0.00014439","cumQuantity":"10.0","createdAt":"2020-01-16T18:22:34.206Z","updatedAt":"2020-01-16T18:22:34.262Z"}
    ]
```

... no open order

**Comment by kroitor** [comment]
> ... no open order

Uhm... you can't get open orders with a call to `fetchClosedOrders` at all, since the purpose of `fetchClosedOrders` is to return just the closed/canceled orders. So, you probably want `fetchOpenOrders` instead.

**Comment by npomfret** [comment]
Sorry, you misunderstand.  I don't want open orders.  I saw the filtering in the code and assumed that it would break pagination.  But if there are no open orders, then no filtering is required (because it doesn't do anything).  Right?

**Comment by kroitor** [comment]
Check this out:

- https://github.com/ccxt/ccxt/issues/2023

![Screen-Shot-2020-01-20-at-17 38 45](https://user-images.githubusercontent.com/1294454/72735025-10c54980-3bac-11ea-948f-a6ca22f8c19e.jpg)

In theory, that filtering would not be necessary. However, with HitBTC v2 in particular, there are no "open" or "closed" orders. Instead they have "active" and "historical" orders (depending on how old they are, or how long ago they were last updated). HitBTC v2 can return open orders and closed orders from both the "active" and the "historical" endpoints, so in this particular case to match the semantics of `fetchOpenOrders` and `fetchClosedOrders` we had to add the filtering. Your suggestions are welcome.

**Comment by npomfret** [comment]
I'm not sure I fully understand, but does this explain why I can no longer see my older LTC/EUR trades and my old BCH/BTC trades?

The current code in fetchClosedOrders returns no open orders as far as I can see (from my test today).  Are you saying that it might return an open order if that order was opened a VERY long time ago?

**Comment by kroitor** [comment]
> but does this explain why I can no longer see my older LTC/EUR trades and my old BCH/BTC trades?

I'm not sure I understand this question, it depends on the status of the order.

> Are you saying that it might return an open order if that order was opened a VERY long time ago?

Yes, exactly. Let me know if you have further questions.

**Comment by npomfret** [comment]
Thanks.

To clarify 

>  I can no longer see my older LTC/EUR trades and my old BCH/BTC trades

When I call `fetchClosedOrders` I no longer see BCHBTC trades that were executes more than x months ago (not sure exactly what the cutoff is).  I can see them on the hitbct website in the trade report (as _BCHOLD/xxx_ trades), but not in API results (which is why I was looking at the filtering).  It looks like the API isn't returning these trades any more.  Additionally, I have some much older EUR trades, and I can't see these in the either API or the website.  It seems that when hitbtc delists a market they delete your trade history.. which is very unhelpful.

**Comment by kroitor** [comment]
>  It looks like the API isn't returning these trades any more. 

To me this sounds like you're trying to fetch some data with a symbol, while that data has a different symbol, so you may want to override the market id in the request via `params` (for BCHOLD). In other words, this sounds like the effects of filtering by symbol on the exchange side and probably has nothing to do with the filtering in CCXT.

> It seems that when hitbtc delists a market they delete your trade history.. which is very unhelpful.

Yes, that also complicates things a lot.

**Comment by npomfret** [comment]
I wasn't using a symbol - just trying to get my entire history.  And it's not all coming back.  I've raised some tickets with the exchange and hope to get clarification.  But I imagine they've just deleted the data.
