### ISSUE TITLE
How to know wich exchanges support a given function?

### ISSUE THREAD

**Issue by fedecaccia** [ccxt/ccxt#6395]
Im trying to undertand if there is a list of exchanges that support each function. For example, I'm intereted to know which exchanges allow to use the withdraw function

**Comment by kroitor** [comment]
See the docs here:

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata

Also, check out this example:

- https://github.com/ccxt/ccxt/tree/master/examples/js/exchange-capabilities.js

<img width="2045" alt="Screen Shot 2020-01-20 at 21 40 09" src="https://user-images.githubusercontent.com/1294454/72750275-75dd6700-3bcd-11ea-98eb-776ef2dc4ac1.png">

If I recall correctly, you're using python3, so you can use the `ccxt.exchanges` array to instantiate the exchanges and then filter those with `.has['withdraw'] == True`:

Something like:

```Python
import ccxt
all_exchanges = [ccxt[id]() for id in ccxt.exchanges]
exchanges_with_withdraw = [exchange['id'] for exchange in all_exchanges if exchange.has['withdraw']]
```

Hope that helps.

**Comment by fedecaccia** [comment]
@kroitor Thanks a lot!!

**Comment by fedecaccia** [comment]
Code updated to check exchanges with withdraw functionality. I fitler theocean because it requires web3.py installed (why?).

```
import ccxt
all_exchanges = [id for id in ccxt.exchanges if id not in ['theocean']]
exchanges_with_withdraw = [exchange for exchange in all_exchanges if getattr(ccxt, exchange)().has['withdraw']]

print("All exchanges with withraw functionality")
for exchange in exchanges_with_withdraw:
    print (exchange)
```

**Comment by kroitor** [comment]
> (why?).

Because it is a DEX that requires web3/ETH functionality to operate. At this point it seems not operating.

**Comment by fedecaccia** [comment]
ok thanks!
