### ISSUE TITLE
How to perform a Sell Limit Close in Bitmex ?

### ISSUE THREAD

**Issue by space4tech** [ccxt/ccxt#6399]
- OS: Ubuntu 18.x
- Programming Language version: PHP 7.3.13
- CCXT version:  1.21.76
- Exchange: BitMex
- Method: create_order

Hi, I tried lots of things before writing here sorry I don't know where else to look for this answer.
I managed to create orders with leverage in my bitmex account and I want to put at the same time my take profit order or "Sell Limit Close" how its called when you press button "Close" next to the open position.

So far I tried to create my first initial long order at $8000 and then I created a second sell order (with MarketIfTouched, LimitIfTouched, StopLimit or Stop) at $9000, but they are not linked, I mean my initial order is bought at 8k and when price touch 9k it execute the second order but it not close my initial position (where my profit is).

Also tried $bitmex->create_limit_sell_order and also it creates a separate order.

Please I need your help and advice.

This is what I want to have in my account if I create an order via CCXT apis:
In the "Positions" tab there is my actual position open and I select a price to define my take-profit sell point, and before I click button "Close" it looks like this:
![Before click](https://i.imgur.com/UzaGDCe.png)
After I clicked the button it shows this confirmation window:
![After click](https://i.imgur.com/dtqEKhL.png)
And the result is this:
![Result](https://i.imgur.com/kcCIY8K.png)
With this way the order is successfully executed and it give me the returns I am looking for.

Help is much appreciated !!
Thank you in advance.

**Comment by kroitor** [comment]
Hi!

You're looking for this information:

- https://www.bitmex.com/api/explorer/#!/Order/Order_closePosition

![Screen-Shot-2020-01-22-at-20 28 14](https://user-images.githubusercontent.com/1294454/72918411-a8669b80-3d56-11ea-819c-4fd10736a937.jpg)

- https://www.bitmex.com/api/explorer/#!/Order/Order_new

![Screen-Shot-2020-01-22-at-20 33 41](https://user-images.githubusercontent.com/1294454/72918522-da77fd80-3d56-11ea-9882-034b9f63a09b.jpg)

↑ From there you can carry that there's two ways to limit close your position:

1. Using the `closePosition` endpoint with a call to the `privatePostOrderClosePosition ()` [implicit API method](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods). However, BitMEX says that this endpoint is deprecated. In PHP it would look close to:

```PHP
$exchange = new \ccxt\bitmex(array(
    'enableRateLimit' => true,
    'apiKey' => 'YOUR_API_KEY',
    'secret' => 'YOUR_SECRET',
));
$exchange->load_markets();
$symbol = 'BTC/USD';
$market = $exchange->market($symbol);
$params = array( // exchange-specific endpoint-specific params
    'symbol': $market['id'], 
    'price': 9000, // ←----------- YOUR LIMIT PRICE HERE
);
$response = $exchange->privatePostOrderClosePosition($params);
var_dump($response);
```

----

2. Making a counter-order for the amount you have in your position, by passing the `execInst` [param override](https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params) to your `createOrder()` call:

```PHP
$exchange = new \ccxt\bitmex(array(
    'enableRateLimit' => true,
    'apiKey' => 'YOUR_API_KEY',
    'secret' => 'YOUR_SECRET',
));
$exchange->load_markets();
$symbol = 'BTC/USD';
$market = $exchange->market($symbol);
$params = array( // exchange-specific endpoint-specific params
    'execInst' => 'Close',
    // YOUR OTHER PARAMS HERE...
);
$amount = 50; // the size of your position
$price = 9000;
$response = $exchange->createOrder($symbol, 'limit', 'sell', $amount, $price, $params);
var_dump($response);
```

Hope that helps. I didn't have the time to test it, so, if anything, check for typos. Don't hesitate if you have any further difficulties. Feel free to reopen this if needed or just ask more questions if any.
