### ISSUE TITLE
Ddos protection error

### ISSUE THREAD

**Issue by Arrmlet** [ccxt/ccxt#6401]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

-  Ubuntu:
- 3.7:
- Newest:
- Binance:
- fetch_tickers:

Hello everyone, 
I run in fetch_tickers method in a loop. I enabled a rate limit and make some sleepers but I'm still getting a DdosProtection Error
My code:
```
`
def exchange_object(exchange_id):
    settings_data = yaml_loader('settings.yaml')
    api_key = settings_data['Exchange']['api']
    secret_key = settings_data['Exchange']['secret']
    exchange_class = getattr(ccxt, exchange_id)
    exchange = exchange_class({
        'apiKey': api_key,
        'secret': secret_key,
        'enableRateLimit': True,
    })

    return exchange


def antiddos(func):
	def inner(*args, **kwargs):
		try:
			result = func(*args, **kwargs)
			return result
			time.sleep(random.uniform(0.01, 0.03))
		except Exception as error:
			print('ddos')
			time.sleep(random.uniform(3,5))
	return inner

@antiddos
def fetch_tickers(exchange):
    return exchange.fetch_tickers()

def main():
	binance = exchange_object('binance')
	maker, taker = load_maker_taker(binance)
	while True:
		ticker = fetch_tickers(binance)
                #Do some logics

`
```
Regards, 
Arrmlet

**Comment by kroitor** [comment]
Hi!

Please, see these duplicate issues for the explanation:

- https://github.com/ccxt/ccxt/issues/1855
- https://github.com/ccxt/ccxt/issues/1365
- https://github.com/ccxt/ccxt/issues/1027
- https://github.com/ccxt/ccxt/issues/3120
- https://github.com/ccxt/ccxt/search?q=binance+fetchtickers&type=Issues

In Binance the rate limit depends on which call it is. If you are fetching a single ticker – that is cheap. If you fetch all tickers at once – that is heavy on the exchange, that request _"weighs"_ a lot.
The `weight` of fetching all tickers is 40 according to Binance API docs:

- https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#ip-limits

Hope that helps, let me know if not.

```Python
exchange = exchange_class({
        'apiKey': api_key,
        'secret': secret_key,
        'enableRateLimit': True,
        'rateLimit': 60000,  # ←--------- set your rate limit higher for all tickers at once (once a minute)
    })
```
