### ISSUE TITLE
BadSymbol: kraken does not have market symbol LTCEUR

### ISSUE THREAD

**Issue by JDJoe** [ccxt/ccxt#6402]
This is from the log: 

```
ccxt/kraken.py", line 795, in create_order
 market = self.market(symbol)
ccxt/base/exchange.py", line 1690, in market
raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
BadSymbol: kraken does not have market symbol LTCEUR

```

I replaced LTCEUR on my side with XLTCZEUR but the error is same BadSymbol: kraken does not have market symbol XLTCZEUR

https://api.kraken.com/0/public/Ticker?pair=LTCEUR

**Comment by kroitor** [comment]
@JDJoe you are confusing market ids with the unified symbols:

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

```Python
import ccxt
from pprint import pprint

exchange = ccxt.kraken ({
    'enabelRateLimit': True,
})
exchange.load_markets()
market = exchange.markets['LTC/EUR']
pprint(market)
```

Let me know if that does not answer the question.

**Comment by JDJoe** [comment]
Yes, thank you.
