### ISSUE TITLE
Force reload markets returns instruments that isn't listed anymore

### ISSUE THREAD

**Issue by GDR** [ccxt/ccxt#6404]
I have a program that works several months I've just noticed that even if I force reload markets for OKEX exchange, it caches the old markets which are no more listed on this exchange. 

Seems like it occurs because of how is setMarkets works:

```
setMarkets (markets, currencies = undefined) {
    ...
    this.markets = deepExtend (this.markets, indexBy (values, 'symbol'))
    ...
}
```

Seems like it deeply extends current markets map and it doesn't mark that exchange doesn't anymore have this market (active field for the market that returns CCXT is still active).

**Comment by kroitor** [comment]
@GDR thx for reporting, will add a fix for this shortly!

**Comment by GDR** [comment]
@kroitor I'm currently preparing two proposal fixes for this problem.

**Comment by kroitor** [comment]
@GDR that is really helpful, thx a lot! I was thinking of propagating the `reload` flag to `setMarkets()` and adding something like the following to `setMarkets()`:

```JavaScript
if (reload) {
    this.markets = {}
}
```

However, in some cases we have hardcoded markets, because some exchanges' APIs don't serve that info. There may be some caveats with that.

**Comment by GDR** [comment]
There is proposals.

https://github.com/ccxt/ccxt/pull/6405
https://github.com/ccxt/ccxt/pull/6406

**Comment by kroitor** [comment]
@GDR thanks so much! To me #6406 (proposal 2) looks cleaner without `deepExtend()`.
