### ISSUE TITLE
New Exchange: Bitvavo

### ISSUE THREAD

**Issue by VoxPopulus** [ccxt/ccxt#6408]
Can you add bitvavo.com?

Bitvavo is an Amsterdam based fiat exchange with 2.5m EUR volume today. All 50+ assets have both a EUR and BTC pair.
Please check https://coinmarketcap.com/exchanges/bitvavo/ or https://account.bitvavo.com/markets/BTC-EUR, or https://docs.bitvavo.com/ for more information.

**Comment by An-Net** [comment]
The exchange is already added available in CCXT.
