### ISSUE TITLE
Since argument should accept datetime in python

### ISSUE THREAD

**Issue by nmiculinic** [ccxt/ccxt#641]
Many python functions have since argument. They should accept datetime object. If you want to support both, I recommend using the arrow library. 

For example:
```python
arrow.get(since).timestamp
```
will get you UNIX timestamp in seconds, whether   since is arrow.Arrow, datetime or int timestamp
or
```python
arrow.get(since).isoformat()
```
will get you properly formatted string.

Right now, I think you're using milliseconds UNIX timestamp? Not sure, I see a lot of */1000 so I guess so.

**Comment by kroitor** [comment]
Thanks for the proposal! We will consider this, this will require wrapping all time-related procedures with something portable, but it doesn't look very hard, apart from the editing routine.

> Right now, I think you're using milliseconds UNIX timestamp? Not sure, I see a lot of */1000 so I guess so.

For method arguments we use milliseconds, that's right.

**Comment by nmiculinic** [comment]
> wrapping all time-related procedures

Decorator perhaps?

**Comment by kroitor** [comment]
@nmiculinic, yep, most likely.

**Comment by kroitor** [comment]
@frosty00, personally, I would agree, timestamps most often are enough, yet, the border between userland code and library code is always somewhat blurred. Some users might want that just for convenience (shorthand syntax).

**Comment by nmiculinic** [comment]
Yes, it's trivial. It's also undocumented what does the function accept (at least I couldn't find documentation easily...I figured looking the code is good enough). 

From a type perspective is explicit --> Datetime is surely a datetime object, not an int posing as unix timestamp in milliseconds (which isn't standard timestamp in python, it's float in seconds). So now the user has to remember exact variant to put, instead of a standard pythonic way of supplying time data.

Python zen..Explicit is better than implicit

**Comment by kroitor** [comment]
> Python zen..Explicit is better than implicit

https://stackoverflow.com/questions/11875770/how-to-overcome-datetime-datetime-not-json-serializable

**Comment by xgdgsc** [comment]
Now different exchanges seem to support different types of since argument. Unifying with datetime can be great.

**Comment by kroitor** [comment]
@xgdgsc the since is in milliseconds, but it gets converted to a format that is required by the exchange, so it does not relate to the unification, because it is unified already. This issue is a feature request for convenience (if you don't want to wrap your timestamps with Python datetime by hand). But it doesn't affect the unification itself. We hope to enable datetime very soon after adding websockets and arbitrary precision. Thx!

**Comment by samgermain** [comment]
I don't believe we'll be accepting multiple types for the `since` argument. We plan to transpile CCXT to some statically typed languages, and accepting multiple types would complicate the process
