### ISSUE TITLE
What is the correct way to set ccxt to use a certain version of an exchange API?

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [ccxt/ccxt#6410]
The url for bitfinex v2 does not match the real url defined at the exchange because ccxt is not using the correct subdomain similar as metioned at https://github.com/ccxt/ccxt/issues/5109

- OS: Windows 10 Home
- Programming Language version: λ javascript node -v v8.11.4
- CCXT version: "ccxt": "^1.21.82"
- Exchange: Bitfinex
- Method: fetchTrades()

1. Without overriding the public URL at exchange instantiation happens this:
```
    const exchange = new exchangeClass({
            'timeout': 30000,
            'enableRateLimit': true,
            verbose: true,
            version: "v2"
    })
```
Logs:
```
Debugger listening on ws://127.0.0.1:3341/fa099701-6a48-4e35-b341-53af051781be
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
(node:8884) [DEP0062] DeprecationWarning: `node --inspect --debug-brk` is deprecated. Please use `node --inspect-brk` instead.
exchange.milliseconds() 1579940323551
(node:8884) [DEP0016] DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
(node:8884) [DEP0016] DeprecationWarning: 'root' is deprecated, use 'global'
fetch:
 bitfinex GET https://api.bitfinex.com/v2/symbols
Request:
 {}
 undefined

handleRestResponse:
 bitfinex GET https://api.bitfinex.com/v2/symbols 404 Not Found
Response:
 { 'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '55a8d16b8f4fd3ff-BUD',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Security-Policy': 'default-src \'none\'',
  'Content-Type': 'text/html; charset=utf-8',
  Date: 'Sat, 25 Jan 2020 08:18:43 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Set-Cookie': '__cfduid=df2918043e721bfbe94741afd87f7d7541579940323; expires=Mon, 24-Feb-20 08:18:43 GMT; path=/; domain=.bitfinex.com; HttpOnly; SameSite=Lax',
  'Strict-Transport-Security': 'max-age=31536000; includeSubdomains;',
  'Transfer-Encoding': 'chunked',
  'X-Content-Type-Options': 'nosniff',
  'X-Download-Options': 'noopen',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Permitted-Cross-Domain-Policies': 'none',
  'X-Xss-Protection': '1; mode=block' }
 <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/v2/symbols</pre>
</body>
</html>


ExchangeNotAvailable: bitfinex GET https://api.bitfinex.com/v2/symbols 404 Not Found <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/v2/symbols</pre>
</body>
</html>
 (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)
    at bitfinex.defaultErrorHandler (C:\Users\Luis\source\repos\TestCCXT\TestCCXT\node_modules\ccxt\js\base\Exchange.js:592:19)
    at response.text.then (C:\Users\Luis\source\repos\TestCCXT\TestCCXT\node_modules\ccxt\js\base\Exchange.js:629:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:8884) UnhandledPromiseRejectionWarning: ReferenceError: error is not defined
    at getTrades (C:\Users\Luis\source\repos\TestCCXT\TestCCXT\app.js:88:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:8884) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8884) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Waiting for the debugger to disconnect...

``` 

2. Overriding the URL happens this:

```
    const exchange = new exchangeClass({
            'timeout': 30000,
            'enableRateLimit': true,
            verbose: true,
            version: "v2",
            urls: {
                public: "https://api-pub.bitfinex.com"
            }
    })
```
Logs:
```
Debugger listening on ws://127.0.0.1:36066/48565bc9-203d-420a-b465-21f70db93ffa
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
(node:23964) [DEP0062] DeprecationWarning: `node --inspect --debug-brk` is deprecated. Please use `node --inspect-brk` instead.
exchange.milliseconds() 1579940491725
fetch:
 bitfinex GET https://api.bitfinex.com/v2/symbols
Request:
 {}
 undefined

handleRestResponse:
 bitfinex GET https://api.bitfinex.com/v2/symbols 404 Not Found
Response:
 { 'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '55a8d5868a63d43b-BUD',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Security-Policy': 'default-src \'none\'',
  'Content-Type': 'text/html; charset=utf-8',
  Date: 'Sat, 25 Jan 2020 08:21:31 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Set-Cookie': '__cfduid=d0dc9bf45eb03c0faea12d35096917bda1579940491; expires=Mon, 24-Feb-20 08:21:31 GMT; path=/; domain=.bitfinex.com; HttpOnly; SameSite=Lax',
  'Strict-Transport-Security': 'max-age=31536000; includeSubdomains;',
  'Transfer-Encoding': 'chunked',
  'X-Content-Type-Options': 'nosniff',
  'X-Download-Options': 'noopen',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Permitted-Cross-Domain-Policies': 'none',
  'X-Xss-Protection': '1; mode=block' }
 <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/v2/symbols</pre>
</body>
</html>


    const exchange = new exchangeClass({
            'timeout': 30000,
            'enableRateLimit': true,
            verbose: true,
            version: "v2",
            urls: {
                public: "https://api-pub.bitfinex.com"
            }
    })



ExchangeNotAvailable: bitfinex GET https://api.bitfinex.com/v2/symbols 404 Not Found <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/v2/symbols</pre>
</body>
</html>
 (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)
    at bitfinex.defaultErrorHandler (C:\Users\Luis\source\repos\TestCCXT\TestCCXT\node_modules\ccxt\js\base\Exchange.js:592:19)
    at response.text.then (C:\Users\Luis\source\repos\TestCCXT\TestCCXT\node_modules\ccxt\js\base\Exchange.js:629:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:23964) UnhandledPromiseRejectionWarning: ReferenceError: error is not defined
    at getTrades (C:\Users\Luis\source\repos\TestCCXT\TestCCXT\app.js:91:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:23964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Waiting for the debugger to disconnect...

```

3- Question: At the User Manual, the definition of version says:

> version: A string literal containing version identifier for current exchange API. The ccxt library will append this version string to the API Base URL upon each request. You don't have to modify it, unless you are implementing a new exchange API. The version identifier is a usually a numeric string starting with a letter 'v' in some cases, like v1.1. Do not override it unless you are implementing your own new crypto exchange class.

> **Do not override it unless you are implementing your own new crypto exchange class.**

which makes me wonder what is the correct way to use version 2 of an API for a certain exchange. Is it correct the way I tried?:

```
    const exchange = new exchangeClass({
            'timeout': 30000,
            'enableRateLimit': true,
            verbose: true,
            version: "v2"
    })
```

It seems that version property is only for using its value at the URL, but not for switching to the version 2 of the exchange API.

**Comment by kroitor** [comment]
Hi!

First, of

```JavaScript
    const exchange = new exchangeClass({
            'timeout': 30000,
            'enableRateLimit': true,
            verbose: true,
            version: "v2"
    })
```

↑ If you're instantiating `bitfinex` from CCXT – adding `version` will break the URLs, because, as you noted precisely

> It seems that version property is only for using its value at the URL, but not for switching to the version 2 of the exchange API.

So, you can't switch to one version or another by changing the value of that particular `version` property. It is for internal needs mostly.

For that same reason, you should not override the URL to switch to a different version, since if you instantiate `bitfinex` from CCXT all the code there will expect `v1` formats and endpoints and therefore it will break down like you see on your side.

> Is it correct the way I tried?

Nope, for the reasons explained above.

> what is the correct way to use version 2 of an API for a certain exchange.

In short – instantiate `bitfinex2` instead of `bitfinex` and don't touch the `version` and the `urls`.

In general, there's no such thing in CCXT as supporting multiple versions. There is usually just the current version, which can change over time from v1 → v2 → v3. 

However, in some cases, we have implementations of two versions of the same exchange API in parallel. One of such cases is `bitfinex` and `bitfinex2`. We have both in CCXT and you can instantiate one or another, depending on your needs. Before you do, though, please, make sure to type in `bitfinex` and `bitfinex2` in the search box on top of this page – it will show you all the currently known issues and pull requests, for example: https://github.com/ccxt/ccxt/pull/6369. 

From there you can carry that bitfinex will eventually be switched to v2 and will replace v1, thus the only remaining name in CCXT will be just `bitfinex` (for v2, which will be the current version at that time). 

We've had other examples like that, `hitbtc` and `hitbtc2`, `bitstamp1` and `bitstamp`. Also, earlier, KuCoin has changed the API version and we had `kucoin` with `kucoin2` for some migration period, and [`kucoin2` replaced `kucoin` later](https://github.com/ccxt/ccxt/issues/4579).

So, what you should do is replace this:

```JavaScript
const exchangeClass = ccxt.bitfinex // ←-------------------- THIS
const exchange = new exchangeClass({
            'timeout': 30000,
            'enableRateLimit': true,
            verbose: true,
            version: "v2"
    })
```

↓

```JavaScript
const exchangeClass = ccxt.bitfinex2 // ←-------------------- THIS
const exchange = new exchangeClass({
            'timeout': 30000,
            'enableRateLimit': true,
            verbose: true,
            // ←---------------------------- NO NEED TO OVERRIDE THE VERSION HERE
    })
```

Hope that answers the question.

**Comment by Luis-Fernando-Molina** [comment]
Thanks for the detailed explanation. May I suggest you to add these details at the User Manual for future users.

**Comment by kroitor** [comment]
> May I suggest you to add these details at the User Manual for future users.

Will do, thanks for the feedback!

**Comment by kroitor** [comment]
@Luis-Fernando-Molina JFYI, at this time the implementation in bitfinex2 is quite limited, but many of the missing methods will be added upon merging #6369.

<img width="2045" alt="Screen Shot 2020-01-20 at 21 40 09" src="https://user-images.githubusercontent.com/1294454/72750275-75dd6700-3bcd-11ea-98eb-776ef2dc4ac1.png">

**Comment by Luis-Fernando-Molina** [comment]
> @Luis-Fernando-Molina JFYI, at this time the implementation in bitfinex2 is quite limited, but many of the missing methods will be added upon merging #6369.

Thanks clarifying this. In my case I need historic trades which are only available on v2. I might need to use v1 for other methods. 

By the way, even though you have only one method to fetch trades, mapping what most exchanges are providing, It might be useful for users of ccxt to have 2:

1. For recent trades (could be the current one)
2. One for historic trades (which includes recent trades too depending on the _since_ you use)

Today there is no programmatic way to know if an exchange supports or not historic trades, which implies testing each one of them, plus reading their documentation to see, like in the case of Bitfinex, that they support only recent trades at v1, **but** historic trades on v2, which is not the default but is available.

Suggestion: You could avoid this work of your users by having a second historic trades method only at the exchanges that support it.

NOTE: Maybe there is a way to know this programatically (without testing with a query and I just dont know about it. )

**Comment by kroitor** [comment]
> Suggestion: You could avoid this work of your users by having a second historic trades method only at the exchanges that support it.

Totally agree with you on this. The only reason why we haven't done it yet – is because we haven't done it yet, even now this library is a work in progress (and will be so for long), so, we will get there eventually. It's not that easy to unify all the aspects and specifics at once, but we'll add the requested feature (some property that would store the exchange capabilities in a detailed way) at some point, hopefully soon.

**Comment by Luis-Fernando-Molina** [comment]
You are doing a great job so far. Having done a system connecting to only one exchange so far, I know the intricacies you are dealing with. Unifying hundreds of exchanges APIs is a monumental task that will benefit a whole ecosystem of layer 2 apps on top of exchanges.
