### ISSUE TITLE
print is blank for fetch_balance of OKEX

### ISSUE THREAD

**Issue by Archie0422** [ccxt/ccxt#6411]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:WIN 10
- Programming Language version:Python
- CCXT version:1.21.89
- Exchange:OKEX
- Method:fetch_balance

Hi,
After I set up the apiKey, secret and password of ccxt.okex3.
I trying to process fetch_balance function, but the return is {'info': [], 'free': {}, 'used': {}, 'total': {}}...

Do anyone know why it happen?

Thanks.

**Comment by kroitor** [comment]
> Do anyone know why it happen?

By default, it will return your spot trading balance (this is the most probably cause why you see an empty balance), as explained here:

- https://github.com/ccxt/ccxt/issues/6350#issuecomment-572175882
- https://github.com/ccxt/ccxt/issues/4029#issuecomment-431703921

You can work with any OKEX account, futures, spot, margin, wallet, etc. When you deposit to OKEX the money usually lands to the OKEX wallet account first.

Let us know if that does not answer the question.
