### ISSUE TITLE
Binance Badsymbol

### ISSUE THREAD

**Issue by rienaldis** [ccxt/ccxt#6413]
- OS: Windows 10
- Programming Language version: 1.21.89
- CCXT version:
- Exchange: Binance
- Method: create_order

i got InvalidOrder error when run this
`$exchange->create_order ('BTC/USDT', $typee, $side, $amount);`

so i read the binance api repository
![image](https://user-images.githubusercontent.com/56689912/73141309-4fc83300-40b5-11ea-8729-fbceed8937fc.png)
 Pair symbol is 'BTCUSDT'

so i tried this
`$exchange->create_order ('BTCUSDT', $typee, $side, $amount);`
but i got BadSymbol error

so what should i do? thanks

**Comment by kroitor** [comment]
> so i tried this `$exchange->create_order ('BTCUSDT', $typee, $side, $amount);` but i got BadSymbol error

Your code has errors that are explained in the Manual. You are confusing market ids with the unified symbols:

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

Change your code to this:

```JavaScript
//                          ↓
$exchange->create_order('BTC/USDT', $type, $side, $amount);
```

> so what should i do? 

Always read the entire Manual from top to bottom first:

- https://github.com/ccxt/ccxt/wiki/

Also, check this:

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/issues/6402

Hope it helps.
