### ISSUE TITLE
not able to push updates to repo

### ISSUE THREAD

**Issue by RohitChangediya** [ccxt/ccxt#6415]
remote: Permission to ccxt/ccxt.git denied to RohitChangediya.
fatal: unable to access 'https://github.com/ccxt/ccxt.git/': The requested URL returned error: 403

getting above error when tried to push using

git push origin

**Comment by kroitor** [comment]
> getting above error when tried to push using

You can't push to the CCXT repository, if you're not a member of the CCXT Dev Team, due to permissions. Please, read how GitHub.com works: https://help.github.com/en/github. This question is beyond the scope of this library, unfortunately.

**Comment by RohitChangediya** [comment]
Thanks for your reply
I want to contribute to the library, but not aware of how should it be done. Can you please guide me?

**Comment by kroitor** [comment]
@RohitChangediya sure, I'd recommend to start with these guides:

- https://help.github.com/en/desktop/contributing-to-projects
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

**Comment by kroitor** [comment]
@RohitChangediya most often, contributions to the CCXT repo are received in the form of pull requests: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-forks
