### ISSUE TITLE
Bibox (js): "fetchMarkets" method doesn't return exchange's symbol on baseId/quoteId.

### ISSUE THREAD

**Issue by fbadiola** [ccxt/ccxt#6416]
- OS: Mac Os X
- Programming Language version: javascript
- CCXT version: 1.21.92
- Exchange: Bibox
- Method: fetchMarkets

Hello,

I read the [market structure doc](https://github.com/ccxt/ccxt/wiki/Manual#market-structure) and on `baseId` / `quoteId` should be returned the exchange's specific symbol but when I invoked `fetchMarkets` method on `bibox` exchange it return the unified symbol (ccxt id).

Example:
```javascript
const ccxt = require('ccxt');

const exchange = new ccxt.bibox();

async function main() {
  const result = await exchange.fetchMarkets()
  for (const x of result) {
    if (x.base === 'MTC Mesh Network') {
      console.log(x);
    }
  }
}

main();
```

Result:
```javascript
{
  id: 'MTC_BTC',
  numericId: 185,
  symbol: 'MTC Mesh Network/BTC',
  base: 'MTC Mesh Network',
  quote: 'BTC',
  baseId: 'MTC Mesh Network',
  quoteId: 'BTC',
  active: true,
  info: {
    is_hide: 1,
    high_cny: '0.0132',
    amount: '0.30',
    coin_symbol: 'MTC',
    last: '0.00000021',
    currency_symbol: 'BTC',
    change: '+0.00000001',
    low_cny: '0.0108',
    base_last_cny: '0.01259977',
    area_id: 7,
    percent: '+5.00%',
    last_cny: '0.0126',
    high: '0.00000022',
    low: '0.00000018',
    pair_type: 0,
    last_usd: '0.0018',
    vol24H: '1479306',
    id: 185,
    high_usd: '0.0019',
    low_usd: '0.0016'
  },
  precision: { amount: 4, price: 8 },
  limits: {
    amount: { min: 0.00009999999999999999, max: undefined },
    price: { min: 1e-8, max: undefined }
  }
}
// ...
```

I think `baseId` should be `info.coin_symbol`. Is it correct?

Thanks for your attention ;)

**Comment by kroitor** [comment]
> I think `baseId` should be `info.coin_symbol`. Is it correct?

Nope, because:

- https://github.com/ccxt/ccxt/blob/master/js/bibox.js#L112
- https://github.com/ccxt/ccxt/issues/6081
- https://github.com/ccxt/ccxt/issues/3025
- https://github.com/ccxt/ccxt/search?q=MTC&type=Issues

Also from the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#notes-on-naming-consistency

Hope that answers the question.

**Comment by kroitor** [comment]
@fbadiola actually, yes, you're right, looks like a bug in `baseId`, will fix shortly.

**Comment by kroitor** [comment]
@fbadiola I've uploaded a fix for it, thx for reporting it! It should work fine as of 1.21.93 (the new build will arrive in 15 minutes). Pardon, didn't see the mistake at first. But it should be fixed now. Let me know if you have further difficulties with it after upgrading.

**Comment by fbadiola** [comment]
Thanks for fix it. I upgraded and all it's fine.
