### ISSUE TITLE
CCXT does not allow to fetch deposit address on HITBTC

### ISSUE THREAD

**Issue by fedecaccia** [ccxt/ccxt#6419]
- OS: WINDOWS 10
- Programming Language version: python
- CCXT version: last
- Exchange: hitbtc
- Method: fetchDepositAddress/createDepositAddress

Simple code to test if hitbtc has 'createDepositAddress' or 'fetchDepositAddress' reveals false, but checking excghange DOCs it seems they allow to both get current address and create a new one.

Link: https://api.hitbtc.com/#deposit-crypto-address

**Comment by kroitor** [comment]
Use `hitbtc2` instead of `hitbtc`.

**Comment by fedecaccia** [comment]
@kroitor Using hitbtc2 when I ask for balances in exchange, it only retrieves the "trading balances" but not the "main account" balances.... how should we proceed?

**Comment by kroitor** [comment]
@fedecaccia 

> how should we proceed?

- https://github.com/ccxt/ccxt/issues/4108#issuecomment-435660346
- https://github.com/ccxt/ccxt/issues/5596
- https://github.com/ccxt/ccxt/issues/406#issuecomment-347582951
- https://github.com/ccxt/ccxt/search?q=hitbtc2+main+balance&unscoped_q=hitbtc2+main+balance&type=Issues

**Comment by fedecaccia** [comment]
@kroitor thanks a lot!
