### ISSUE TITLE
Allow custom timeframe/granularity values

### ISSUE THREAD

**Issue by MeetM** [ccxt/ccxt#642]
Some exchanges, like GDAX, do support custom duration based granularity, like 7 seconds or 3 minutes for OHLC. I can send a PR to enable that

**Comment by kroitor** [comment]
Thanks, @MeetM ! If you want to give it a try, go for it, just make sure to read this first: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md. We welcome all contributions.

**Comment by kroitor** [comment]
I would close this for now until we have a followup on this, if you don't mind. Feel free to reopen it if needed, or just ask questions if any. Still hope to hear from you. Thx!
