### ISSUE TITLE
Binance create_order method error MIN_NOTIONAL

### ISSUE THREAD

**Issue by rienaldis** [ccxt/ccxt#6420]
OS: Windows 10
    Programming Language version: 1.21.89
    CCXT version:
    Exchange: Binance
    Method: create_order

i try to trade on pair BTC/USDT, and this my code:
`$exchange->create_order ('BTC/USDT', 'limit', 'buy', 0.0011628089813294‬);`

and i error result is :
`{"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}`

so i read all issues answer and try to calculate the cost. for 'buy' i have  10.21023031 USDT. so:

amount = 10.21023031 / price ( 8780.66 )
amount = 0.0011628089813294‬ BTC

is this correct for buy? and its more than 0.001BTC but still got the error.

**Comment by kroitor** [comment]
> so i read all issues answer and try to calculate the cost. for 'buy' i have 10.21023031 USDT. so:

You don't need to do that for `limit` orders. You only need to calculate the cost for `market` orders in some cases. A `limit` order always requires the amount and the price:

```PHP
$amount = 10.21023031;
$price = 8780.66; // ------------------------------------------- ↓
$exchange->create_order ('BTC/USDT', 'limit', 'buy', $amount, $price);
```

Also, for `BTC/USDT` with Binance, the limits are:

```PHP
$exchange = new \ccxt\binance(array('enableRateLimit' => true));
$exchange->load_markets();
var_dump($exchange->markets['BTC/USDT']['limits']);
```

↓

```
            [cost] => Array
                (
                    [min] => 10
                    [max] =>
                )

            [price] => Array
                (
                    [min] => 0.01
                    [max] => 1000000
                )

            [amount] => Array
                (
                    [min] => 1.0E-6
                    [max] => 9000
                )
```

Minimal cost (MIN_NOTIONAL) should be above 10 USDT for any order (`limit` or `market`), min price is 0.01 USDT, min amount is 0.000001 BTC.

Let me know if that does not answer the question.

**Comment by kroitor** [comment]
In fact, there is a guard in Binance implementation here:

- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L1079

Which should throw a warning at you, when you forget to specify the `price` for a `limit` order, and it looks like so:

```
mbp:ccxt igorkroitor$ php -a
Interactive shell

php > include_once 'ccxt.php';
php > $exchange = new \ccxt\binance(array('enableRateLimit' => true));
php > $exchange->create_order('BTC/USDT', 'limit', 'buy', 123.45);

PHP Warning:  Uncaught ccxt\InvalidOrder: binance createOrder $method requires a $price argument for a limit order in /Users/igorkroitor/ccxt/php/binance.php:1085
```

However, in your case, you don't get that exception, so you may want to check your runtime version of the lib.

**Comment by rienaldis** [comment]
`$amount = 10.21023031; // ←- i'm not sure if you want to buy 10 BTC here, edit this according to your needs

$price = 8780.66; // ------------------------------------------- ↓ price goes here
$exchange->create_order ('BTC/USDT', 'limit', 'buy', $amount, $price);`

my balance is not 10 BTC, its USDT. i calculate it first to BTC, so my balance 10.21023031 USDT / price which is 8780.66
`$amount = 10.21023031 / 8780.66;
$amount = 0.0011628089813294; // ←-so this BTC `

its more than this
`
            [amount] => Array
                (
                    [min] => 1.0E-6
                    [max] => 9000
                )`


i already add $price to but still same error.

is it need more balance?

**Comment by kroitor** [comment]
> i already add $price to but still same error.

The short answer is documented in the Manual: for a `limit` order the `amount` is always in base currency (`BTC` in your case) and the `price` is always in quote currency.

So, you should check both the `amount` and the `price`:

```PHP
$amount = 0.0011628089813294;
$price = 8780.66;
$order = $exchange->create_order('BTC/USDT', 'limit', 'buy', $amount, $price);
```

If your intent is to spend all your USDT balance, for the best price available on the exchange (the market price) – you don't really want a `limit` order – instead you want a `market` order with or an order with `quoteOrderQty` set to your USDT balance:

```PHP
$amount = 0.0011628089813294;
$price = 8780.66;
//                            market type here ↓
$order = $exchange->create_order('BTC/USDT', 'market', 'buy', $amount, $price);
```

or

```PHP
$amount = null;
$price = null;
$params = array(
    'quoteOrderQty' => '10.21023031',
);
//                            market type here ↓                      params here ↓
$order = $exchange->create_order('BTC/USDT', 'market', 'buy', $amount, $price, $params);
```

The last two snippets will only work with the most recent version (added a couple of days ago),

Let me know if that does not help.

**Comment by rienaldis** [comment]
Nicee, its working now. The main problem is in the limit and market. i have to understand both first. thanks man.

**Comment by spacewalkingninja** [comment]
Ok guys, thanks big lots. I was having the same problem and with documentation constantly changing I had overlooked that quoteOrderQty is in USDT and amount is how much of the currency I'm trying to buy!

**Comment by rienaldis** [comment]
> 
> 
> > i already add $price to but still same error.
> 
> The short answer is documented in the Manual: for a `limit` order the `amount` is always in base currency (`BTC` in your case) and the `price` is always in quote currency.
> 
> So, you should check both the `amount` and the `price`:
> 
> ```
> $amount = 0.0011628089813294;
> $price = 8780.66;
> $order = $exchange->create_order('BTC/USDT', 'limit', 'buy', $amount, $price);
> ```
> 
> If your intent is to spend all your USDT balance, for the best price available on the exchange (the market price) – you don't really want a `limit` order – instead you want a `market` order or an order with `quoteOrderQty` set to your USDT balance:
> 
> ```
> $amount = 0.0011628089813294;
> $price = 8780.66;
> //                            market type here ↓
> $order = $exchange->create_order('BTC/USDT', 'market', 'buy', $amount, $price);
> ```
> 
> or
> 
> ```
> $amount = null;
> $price = null;
> $params = array(
>     'quoteOrderQty' => '10.21023031',
> );
> //                            market type here ↓                      params here ↓
> $order = $exchange->create_order('BTC/USDT', 'market', 'buy', $amount, $price, $params);
> ```
> 
> The last two snippets will only work with the most recent version (added a couple of days ago),
> 
> Let me know if that does not help.

hello, its working last week, but today when i try it again its return an error:
`{"code":-1013,"msg":"Quote order qty market orders are not support for this symbol."} )`

**Comment by kroitor** [comment]
@rienaldis you might want to reach out to Binance's tech support with this, since this message:

```
{"code":-1013,"msg":"Quote order qty market orders are not support for this symbol."}
```

is coming from the exchange itself, so Binance says that market orders are not supported for BTC/USDT now (despite that they were working previously), unless you have changed something else in your code or account settings.

**Comment by kroitor** [comment]
@rienaldis in general, Binance can change the status of some markets on the fly back and forth, so you should also check market infos, as explained in this comment: https://github.com/ccxt/ccxt/issues/5966#issuecomment-545972823

You might also want to reload your markets from time to time to update their statuses:

- https://github.com/ccxt/ccxt/wiki/Manual#market-cache-force-reload

Hope it answers the question, let me know if not.

**Comment by thebilll** [comment]
I'm having the same issue and the parameter quoteOrderQtyMarketAllowed is returning as FALSE for the currency pair BTC/USDT both through CCXT as well as Binance's API Exchange Info site (https://api.binance.com/api/v1/exchangeInfo).

I've submitted a ticket to Binance as the only documentation I can find on this feature is the 2019-11-22 API update stating that this feature has been enable for all currency pairs.  Does anyone have any documentation from Binance about this being disabled again for all pairs?

I'll update if I hear anything constructive back from them.

**Comment by thebilll** [comment]
Update: Binance has confirmed it was a decision from their end and has not provided a specific time for when the feature could be expected to be enabled.

____________________________

Thanks for reaching out.

Regarding your questions, our tech team still adjusts this parameter. So it has not allowed using yet. We will update the log when it finished. 

Sorry for the inconvenience. For now, please use the quantity instead of this.

Thank you for your understanding.

Best Regards,
Binance Support Team

**Comment by kroitor** [comment]
@thebilll thanks so much for the feedback, this is very helpful!
