### ISSUE TITLE
Coinbase Ticker returns OHL as undefine

### ISSUE THREAD

**Issue by crossx4real** [ccxt/ccxt#6421]
Just a recommendation. it will be very helpful if the ticker from coinbasepro displayed the open, high and low. it currently only displays close and last which are the same value--useless.

i looked at coinbasepros api documentation and it looks like they do not provide this information in the ticker--DUMB!

but i think it will be a great thing if ccxt can some how implement this data by going back in time.

for example: if a user runs exchange.fetchTicker() for timeframe '1m' and fetchTicker() return  OHLC as undefined, ccxt will go back to the last minute and compile the OHLC and add it to the data. like emulating. i think this is better than undefined.

Pros: this will help with the overhead instead of calling 'fetchOHLCV' and getting 1000+ other candles that will be discarded. The 'fetchOHLCV' data is also late by 20+ mins and in some currencies hours making it impossible to do good trend analysis.

in my case i just want the latest OHLCV of the last time period. nothing more. see bottom for output. thank you.

- OS: windows 10
- Programming Language version: node js
- CCXT version: 1.21.95
- Exchange: coinbase
- Method: exchange.fetchTicker()

Log____________________________
ticker:  { symbol: 'DAI/USDC',
  timestamp: 1580174661715,
  datetime: '2020-01-28T01:24:21.715Z',
  high: undefined,
  low: undefined,
  bid: 0.996513,
  bidVolume: undefined,
  ask: 0.997937,
  askVolume: undefined,
  vwap: undefined,
  open: undefined,
  close: 0.99648,
  last: 0.99648,
  previousClose: undefined,
  change: undefined,
  percentage: undefined,
  average: undefined,
  baseVolume: 1978558.16712,
  quoteVolume: undefined,
  info:
   { trade_id: 843270,
     price: '0.99648',
     size: '4.03413',
     time: '2020-01-28T01:24:21.715986Z',
     bid: '0.996513',
     ask: '0.997937',
     volume: '1978558.16712000' } }

**Comment by kroitor** [comment]
> ccxt will go back to the last minute and compile the OHLC and add it to the data. like emulating

The problem is that `coinbase` API does not offer an endpoint for OHLC (not in their docs, https://developers.coinbase.com/api/v2). From your question it looks like you're actually using `coinbasepro`, not `coinbase`.

The rule of thumb throughout the library is: one HTTP request per unified method call. If we don't follow that rule – we might break rate limiting for other people.

> in my case i just want the latest OHLCV of the last time period. nothing more. see bottom for output. thank you.

I guess, what you really want is to grab that info from `coinbasepro`, since the `coinbase` wallet service takes the pricing info from its own exchange `coinbasepro`. 

In general, you want to call `fetchOHLCV` for that.

> Pros: this will help with the overhead instead of calling 'fetchOHLCV' and getting 1000+ other candles that will be discarded.

You don't have to get 1000+ candles, if you specify a low `limit` argument to `fetchOHLCV`. For example:

- https://github.com/ccxt/ccxt/blob/master/examples/js/cli.js

```
mbp:ccxt igorkroitor$ node examples/js/cli coinbasepro fetchOHLCV DAI/USDC 1m undefined 1 --iso8601
coinbasepro.fetchOHLCV (DAI/USDC, 1m, , 1)
2020-01-28T01:59:00.000Z | 0.997088 | 0.997088 | 0.997078 | 0.997078 | 113.40854
1 objects
```

```
mbp:ccxt igorkroitor$ node examples/js/cli coinbasepro fetchOHLCV DAI/USDC 1m undefined 10 --iso8601
coinbasepro.fetchOHLCV (DAI/USDC, 1m, , 10)
2020-01-28T01:50:00.000Z | 0.997083 | 0.997999 | 0.997083 | 0.997088 | 254.63433
2020-01-28T01:51:00.000Z | 0.997088 |    0.998 | 0.997088 | 0.997999 | 158.14529
2020-01-28T01:52:00.000Z | 0.997123 | 0.997191 | 0.997123 | 0.997191 |  510.2439
2020-01-28T01:53:00.000Z | 0.997217 | 0.997999 | 0.997215 | 0.997237 | 459.37666
2020-01-28T01:54:00.000Z | 0.997999 |    0.998 | 0.997999 |    0.998 |  543.5682
2020-01-28T01:55:00.000Z |    0.998 |    0.998 | 0.997999 | 0.997999 |  81.98024
2020-01-28T01:56:00.000Z | 0.997999 | 0.997999 | 0.997999 | 0.997999 |  12.82994
2020-01-28T01:57:00.000Z | 0.997999 | 0.997999 | 0.997999 | 0.997999 |     1.002
2020-01-28T01:58:00.000Z | 0.997999 | 0.997999 | 0.997999 | 0.997999 | 999.15614
2020-01-28T01:59:00.000Z | 0.997088 | 0.997088 | 0.997078 | 0.997078 | 113.40854
10 objects
```

If you don't want to `fetchOHLCV`, then the only remaining source of info that can be used for recent stats is the `fetchTrades` endpoint + the `buildOHLCVC` method:

```JavaScript
        const trades = await exchange.fetchTrades (symbol, since, limit, params)
        const ohlcvc = exchange.buildOHLCVC (trades, timeframe, since, limit)
```

If you just need the 24-hour OHLCV, you can also use the [implicit methods](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods), publicGetProductsIdStats method:

```JavaScript
const ccxt = require ('./ccxt')
const exchange = new ccxt.coinbasepro({ enableRateLimit: true })
;(async () => {
    await exchange.loadMarkets()
    const market = exchange.market ('DAI/USDC')
    const response = await exchange.publicGetProductsIdStats({ 'id': market['id'] })
    console.log (response)
}) ()
```

Let me know if that does not answer the question. Feel free to reopen it if needed, or just ask further questions, if you have more.

**Comment by kroitor** [comment]
I've uploaded a quick update to the `coinbasepro` implementation, so you can now switch between the endpoints using the `fetchTickerMethod` option, if you update to CCXT version 1.21.96:

```JavaScript
const ccxt = require ('./ccxt')
const exchange = new ccxt.coinbasepro ({ enableRateLimit: true })
;(async () => {
    console.log (await exchange.fetchTicker ('DAI/USDC')) // publicGetProductsIdTicker by default
    exchange.options['fetchTickerMethod'] = 'publicGetProductsIdStats'
    console.log (await exchange.fetchTicker ('DAI/USDC')) // publicGetProductsIdStats
}) ()
```

**Comment by crossx4real** [comment]
kroitor, thanks for the quick reply and update.

i updated to 1.21.96 and tested the new implementation. it does pull the OHLC and V but it looks like timestamp is being dropped. shows 'undefined'

ticker:  { symbol: 'DAI/USDC',
  timestamp: undefined,
  datetime: undefined,
  high: 1.00122,
  low: 0.995,
  bid: undefined,
  bidVolume: undefined,
  ask: undefined,
  askVolume: undefined,
  vwap: undefined,
  open: 1.000352,
  close: undefined,
  last: undefined,
  previousClose: undefined,
  change: undefined,
  percentage: undefined,
  average: undefined,
  baseVolume: 1910473.71541,
  quoteVolume: undefined,
  info:
   { open: '1.00035200',
     high: '1.00122000',
     low: '0.99500000',
     volume: '1910473.71541000',
     last: '0.99698700',
     volume_30day: '31346388.32835' } }

**Comment by crossx4real** [comment]
is this because its 24hr timeframe?

**Comment by kroitor** [comment]
> it looks like timestamp is being dropped. shows 'undefined'

It is not really dropped – we just don't invent it out of thin air if the underlying exchange endpoint does not serve it. So, you can assume `timestamp = exchange.milliseconds()`.

**Comment by crossx4real** [comment]
ok thanks this helps a lot, you're the best bro.

when i make it big, ccxt will also be very happy ;)
