### ISSUE TITLE
Options data from Okex

### ISSUE THREAD

**Issue by VadimSFedin** [ccxt/ccxt#6423]
Hello,

I am trying to get information about options from Okex.com: tickers, bids, asks. But fetch_markets() shows everything except options. Could you please add information about options or let me know how I can parse this data? 

- OS: Windows 10
- Programming Language version: Python 3.6
- CCXT version: 1.21.96
- Exchange: Okex3
- Method: fetch_markets()

Thank you!

**Comment by kroitor** [comment]
OKEX has launched the options API a month ago (https://www.coindesk.com/crypto-exchange-okex-launching-options-trading-later-this-month). At this time we support `spot`, `future`, `margin` and `swap` APIs from OKEX. 

> Could you please add information about options

We will add the  `option` API endpoints asap.

**Comment by VadimSFedin** [comment]
Thanks.

**Comment by kroitor** [comment]
The support for OKEX v3 options markets has been added in CCXT 1.24.16+. Thank you!
