### ISSUE TITLE
AttributeError: 'bitfinex2' object has no attribute 'privatePostHistoryMovements'

### ISSUE THREAD

**Issue by eabrouwer3** [ccxt/ccxt#6427]
- OS: Ubuntu 19.04
- Programming Language version: Python 3.7
- CCXT version: 1.22.2
- Exchange: Bitfinex (`bitfinex2`)
- Method: `fetchTransactions`

I'm just trying to call fetch_transactions like this:
```python
client = ccxt.bitfinex2({'enableRateLimit': True})
resp = list()
for currency in client.currencies:
    resp += client.fetch_transactions(currency)
```
And it gives me this error:
```
File "~/.virtualenvs/project/lib/python3.7/site-packages/ccxt/bitfinex.py", line 927, in fetch_transactions
  response = self.privatePostHistoryMovements(self.extend(request, params))
AttributeError: 'bitfinex2' object has no attribute 'privatePostHistoryMovements'
```
It looks like `bitfinex2` inherits from `bitfinex`, but for some reason it is messing up it's inheritance stuff. Any ideas?

**Comment by kroitor** [comment]
> It looks like bitfinex2 inherits from bitfinex, but for some reason it is messing up it's inheritance stuff. 

It is inherited from bitfinex, and bitfinex had `fetchTransactions` defined in exchange metainfo, however, bitfinex2 does not have the implementation of that method yet (see this PR for more info: https://github.com/ccxt/ccxt/pull/6369) and the corresponding flag was inherited with a wrong value.

> Any ideas?

Please, update to CCXT version 1.22.3 (i've fixed that [metadata flag](https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata)):

- https://github.com/ccxt/ccxt/blob/master/js/bitfinex2.js#L36

I suggest to use `bitfinex` (v1) for `fetchTransactions` until we add it to `bitfinex2` (v2).

Let us know if that does not answer the question.
