### ISSUE TITLE
Support Binance futures

### ISSUE THREAD

**Issue by thanhnguyennguyen** [ccxt/ccxt#6428]
Binance launched Binance Futures.
The price of Binance Futures are a little bit different from the price of Binance exchange market.
Could you please consider to add new pairs for future contracts ? 
p/s: Tradingview also supports both exchange and future contract pairs as below:
![image](https://user-images.githubusercontent.com/17243442/73342705-b023c400-42b1-11ea-8be8-e3747e72beff.png)

**Comment by kroitor** [comment]
It has been added already, see how to enable the '`defaultType': 'future'` option here:

- https://github.com/ccxt/ccxt/issues/6222#issuecomment-562536133
- https://github.com/ccxt/ccxt/pull/5907

**Comment by thanhnguyennguyen** [comment]
Thank you!
