### ISSUE TITLE
Bitfinex exception issue - missing NetworkError

### ISSUE THREAD

**Issue by ivanzhelyazkov** [ccxt/ccxt#6429]
- OS: MacOs Mojave 10.14.6
- Programming Language version: Python 3.7.4
- CCXT version: 1.21.85
- Exchange: Bitfinex
- Method: Exception Network error

except self.ccxt.NetworkError as e: 

the code above should work in Python, but it triggers the following exception :
AttributeError: 'bitfinex' object has no attribute 'NetworkError'

The entire code :

try:
                    result = self.ccxt.cancel_order(self.last_order, self.last_order_symbol)
except self.ccxt.NetworkError as e:
                    self.logger.error(e)
                    while True:
                        try:
                            #sleep(0.1)
                            result = self.ccxt.cancel_order(self.last_order, self.last_order_symbol)
                            self.last_order = None
                            self.last_order_symbol = None
                            self.logger.info(f'closed last order on: {self.name}')
                        except Exception as e:
                            self.logger.error(e)

The entire result with traceback :

ccxt.base.errors.NetworkError: bitfinex {"message":"Nonce is too small."}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 353, in <module>
    main()
  File "main.py", line 300, in main
    thread = threading.Thread(target=provider.cancelOrders())
  File "/.../exchange.py", line 417, in cancelOrders
    except self.ccxt.NetworkError as e:
AttributeError: 'bitfinex' object has no attribute 'NetworkError'

**Comment by kroitor** [comment]
In here:

```Python
except self.ccxt.NetworkError as e:  # ←-------- HERE
```

You're trying to reference a NetworkError property on `self.ccxt` which is an instance of an exchange that you saved under `self.ccxt`. The Exchange class does not have that property, though. What you want is `NetworkError` from the `ccxt` lib itself, not a `NetworkError` from a `ccxt` exchange instance. In other words, this is a very easy mistake in the code, and you can fix it like so:

```Python
# somewhere at the top of the file, far far away...
import ccxt

# ...

try:
                    result = self.ccxt.cancel_order(self.last_order, self.last_order_symbol)
except ccxt.NetworkError as e:
                    self.logger.error(e)
                    while True:
                        try:
                            #sleep(0.1)
                            result = self.ccxt.cancel_order(self.last_order, self.last_order_symbol)
                            self.last_order = None
                            self.last_order_symbol = None
                            self.logger.info(f'closed last order on: {self.name}')
                        except Exception as e:
                            self.logger.error(e)
```

↑ This will work. Let us know if not.
