### ISSUE TITLE
fetchTickers() Percent Change

### ISSUE THREAD

**Issue by PolybitSol** [ccxt/ccxt#643]
Hey,

~~I just noticed some irregularities with the unified fetchTickers() method for Poloniex and Bitfiniex, and the percent change field. It is labeled as `change` for Poloniex and `percentage` for Bitfinex.~~ 

Edit: Made a mistake here, `change` is in both; though it is labelled in the wiki as percent change, however under Bitfinex `percent` is valid, but different to `change` - any clarification on this? Thanks.

Also, it may be worth pointing out that percent change can also be calculated for Bittrex - they provide the PrevDay which, using the % increase formula below, can be used to determine the percent change.

`percentChange = (last - prevDay) / prevDay * 100`

Thanks for reading.

**Comment by kroitor** [comment]
Hi, @PolybitSol !

Those two fields are not completely unified yet, but, in general, the `change` should reflect the  delta, and the percentage is there for convenience to show ratio as well. We will fix these fields for Bitfinex and Poloniex. Let us know if you find any other inconsistencies, please. In the meantime, I would close this issue if you don't mind, will update you on progress. Thx for your feedback, really appreciate it!
