### ISSUE TITLE
Kraken Create Stop Order

### ISSUE THREAD

**Issue by moader808** [ccxt/ccxt#6435]
- OS: Linux 16
- Programming Language version: Python ver.3.5 with conda (gpu-tensor execution)
- CCXT version: 1.22.7
- Exchange: Kraken
- Method: create_order()

Thank you in advance Kroitor, I would have a completely different life without ccxt I would assume! Great work in keeping the simplicity of many exchanges in one unified template. Thank you in advance for even reading my question. Any advice would be helpful.

**Objective**: Use python to create stop-loss order (of any kind, market/limit/etc) on exchange Kraken and return the order ID (stop order awaiting execution - exchange side)

references reviewed beforehand: 
[1489](https://github.com/ccxt/ccxt/issues/1489)
[4972](https://github.com/ccxt/ccxt/issues/4972)
[Manual](https://github.com/ccxt/ccxt/wiki/Manual)
```
symbol = 'ETH/BTC'
type = 'limit'  # or 'market', other types aren't unified yet
side = 'sell'
amount = 123.45  # your amount
price = 54.321  # your price
# overrides
params = {
    'stopPrice': 123.45,  # your stop price
    'type': 'stopLimit',
}
order = exchange.create_order(symbol, type, side, amount, price, params)
```
The code that I am trying to execute in python_script.py
```
api_key_0 = '<24characters>'
api_secret_0 = '<40characters>'
exchange_rate_limiter = 1000

ccxt_broker_api_handler = ccxt.kraken({
		'apiKey': api_key_0,
		'secret': api_secret_0,
		'enableRateLimit': True,
		'rateLimit': exchange_rate_limiter,
		})

order_type='stop-loss'
#order_type='limit'
side = 'sell'
bquantity = 0.002
sell_price = 8500.0
#sell_price = None
params = {}
params['trading_agreement'] = 'agree'
params['validate'] = True
#params['ordertype']='stop-loss'
#params['price2'] = 8500.0
ccxt_broker_api_handler.load_markets()
ccxt_broker_api_handler.verbose=True
sell_stop_loss_order = ccxt_broker_api_handler.create_order('BTC/USD', order_type, side, bquantity, price=sell_price, params=params)
print('sell_stop_loss_order',sell_stop_loss_order)			

```

>>

`Request: POST https://api.kraken.com/0/private/AddOrder {'API-Key': '24chars', 'API-Sign': '40chars', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.21.0', 'Accept-Encoding': 'gzip, deflate'} nonce=1580449535750&pair=XXBTZUSD&type=sell&ordertype=stop-loss&volume=0.002&price=8500&trading_agreement=agree&validate=true

Response: POST https://api.kraken.com/0/private/AddOrder 200 {'Date': 'Fri, 31 Jan 2020 05:45:35 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d4779d2edf9c9b57a4795c5c045fe48111580449534; expires=Sun, 01-Mar-20 05:45:34 GMT; path=/; domain=.kraken.com; HttpOnly; SameSite=Lax', 'content-encoding': 'gzip', 'vary': 'Accept-Encoding', 'strict-transport-security': 'max-age=15768000', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '55d9615979cc3ad0-YVR'} {"error":[],"result":{"descr":{"order":"sell 0.00200000 XBTUSD @ stop loss 8500.0"}}}
sell_stop_loss_order {'id': None, 'info': {'error': [], 'result': {'descr': {'order': 'sell 0.00200000 XBTUSD @ stop loss 8500.0'}}}, 'timestamp': None, 'datetime': None, 'lastTradeTimestamp': None, 'symbol': 'BTC/USD', 'type': 'stop-loss', 'side': 'sell', 'price': 8500.0, 'amount': 0.002, 'cost': None, 'average': None, 'filled': None, 'remaining': None, 'status': None, 'fee': None, 'trades': None}`

Note that current exchange last full and intra-OHLCV candle is greater than 8500.0 USD, and the api key is enabled for everything regarding trading (4 fields included). The order itself is equal to the exact minimum BTC or XBT required by Kraken (even changed it to 0.0021 with no different results).
The commented out code above is other methods I tried implementing to be able to get Kraken to register an order on there end. The most I have gotten in return from Kraken is posted above.

**Comment by kroitor** [comment]
Hi!

First of, a quick question on these two lines:

```Python
params['trading_agreement'] = 'agree'
params['validate'] = True
```

↑ Can you tell the reasons:

- why would you have the `validate` option there
- and why would you add the `trading_agreement`

In particular, as Kraken docs say here:

- https://www.kraken.com/features/api#add-standard-order

the `validate` options means _"check my order but don't place it, since I don't need the actual order id"_. Therefore sending that option will never return any order id – the orders are not created, just check for validity.

**Comment by moader808** [comment]
Hey Kroitor,

For `trading_agreement` parameter, I assumed it was needed from [4972](https://github.com/ccxt/ccxt/issues/4972) and preparing fields for leverage/margin parameters even if leverage=1 (no leverage used on Kraken). Then leverage > 1, the` trading_agreement` parameter is invoked. Additionally checking over the link you just provided in the notes section, it is a way to avoid 1 error "_[EOrder:Trading agreement required](https://www.kraken.com/features/api#add-standard-order)_". Or is this parameter outdated of sorts?
I had actually read some of your link prior, but I guess I did not catch the part about the `validate `parameter. I guess I should use the text find feature more. I apologize for not catching that, seriously. It is very useful to now know that is Kraken's specific order testing parameter though. 

On a side note, I have been going through CoinEx's documentation with regards to [ccxt](https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/coinex.py) and [CoinEx](https://github.com/coinexcom/coinex_exchange_api/wiki/039user_deals) as well. There isn't a valid way to execute a stop-order of any kind through their API is there? Or has my google foo be fallen me again hah! I have actually text filtered through ccxt/coinex documention for "stop" with no actual useful hits. I have combed through their [perpetual ](https://github.com/coinexcom/coinex_perpetual_api/blob/master/demo/python/lib/api.py) documentation and do get hits but its partly in chinese (what id assume is mandarin) as well hah.

**Comment by kroitor** [comment]
> For trading_agreement parameter, I assumed it was needed from 4972 and preparing fields for leverage/margin parameters even if leverage=1 (no leverage used on Kraken). Then leverage > 1, the trading_agreement parameter is invoked. Additionally checking over the link you just provided in the notes section, it is a way to avoid 1 error "EOrder:Trading agreement required". Or is this parameter outdated of sorts?

The `trading_agreement` param is only needed if you encounter a trading agreement issue. If you don't encounter any issues without it (you should try without it in the first place) – then you don't need it, it's that easy ) 

> On a side note, I have been going through CoinEx's documentation with regards to ccxt and CoinEx as well. There isn't a valid way to execute a stop-order of any kind through their API is there? Or has my google foo be fallen me again hah! I have actually text filtered through ccxt/coinex documention for "stop" with no actual useful hits. I have combed through their perpetual documentation and do get hits but its partly in chinese (what id assume is mandarin) as well hah.

CoinEx does have a perpetual API, but it was added in October 2019, long after CoinEx REST API was integrated in CCXT. So, what you have in CCXT is CoinEx without a perpetual API (yet). We will add the support for it as soon as we can. You can try emulating their public perpetual API by just changing the API urls upon instantiation:

```Python
exchange = ccxt.coinex({
    'urls': {
        'api': 'https://api.coinex.com/perpetual', # ←--- add this inside under the `urls` → `api` section
    },
    # other properties
    # ...
    'enableRateLimit': True,
    # ...
})
```

In theory that will let you use CoinEx's public endpoints for perpetual market data. That won't work with all the private endpoints though, since the set of perpetual private endpoints differs from spot private endpoints. That has to be coded into CCXT for 100% support.

Hope that you have the initial kraken order issue resolved.

**Comment by moader808** [comment]
> > For trading_agreement parameter, I assumed it was needed from 4972 and preparing fields for leverage/margin parameters even if leverage=1 (no leverage used on Kraken). Then leverage > 1, the trading_agreement parameter is invoked. Additionally checking over the link you just provided in the notes section, it is a way to avoid 1 error "EOrder:Trading agreement required". Or is this parameter outdated of sorts?
> 
> The `trading_agreement` param is only needed if you encounter a trading agreement issue. If you don't encounter any issues without it (you should try without it in the first place) – then you don't need it, it's that easy ) A rule of thumb is – don't add `params` overrides _"just in case"_ – only add them if you really need them and if you know what you're doing (what they are meant for).

I guess, is the best practice to just error catch it with a try/except block then?

> > On a side note, I have been going through CoinEx's documentation with regards to ccxt and CoinEx as well. There isn't a valid way to execute a stop-order of any kind through their API is there? Or has my google foo be fallen me again hah! I have actually text filtered through ccxt/coinex documention for "stop" with no actual useful hits. I have combed through their perpetual documentation and do get hits but its partly in chinese (what id assume is mandarin) as well hah.
> 
> CoinEx does have a perpetual API, but it was added in October 2019, long after CoinEx REST API was integrated in CCXT. So, what you have in CCXT is CoinEx without a perpetual API (yet). We will add the support for it as soon as we can. You can try emulating their public perpetual API by just changing the API urls upon instantiation:
> 
> ```python
> exchange = ccxt.coinex({
>     'urls': {
>         'api': 'https://api.coinex.com/perpetual', # ←--- add this inside under the `urls` → `api` section
>     },
>     # other properties
>     # ...
>     'enableRateLimit': True,
>     # ...
> })
> ```
> 
> In theory that will let you use CoinEx's public endpoints for perpetual market data. That won't work with all the private endpoints though, since the set of perpetual private endpoints differs from spot private endpoints. That has to be coded into CCXT for 100% support.

Interesting technique, ill try poke around with changing the install api url after implementing a work-around for CoinEx. As with stop-orders, is CoinEx's margin/leverage also fall under the same circumstance then?
I appreciate the continue support for the massive trove of exchange/brokers definitely, as always.

> Hope that you have the initial kraken order issue resolved.

Oh definitely, can still confirm as with [4972](https://github.com/ccxt/ccxt/issues/4972), any stop-order with a 2nd hyphen will throw ordertype errors still.

**Comment by kroitor** [comment]
> I guess, is the best practice to just error catch it with a try/except block then?

I'd say, it's more than just the best practice, it's _a must_ for a quality program ;)

> As with stop-orders, is CoinEx's margin/leverage also fall under the same circumstance then(it being spot)?

Yes, on general, placing perpetual orders with CoinEx won't work without adding the support for that to CCXT.

> Oh definitely, can still confirm as with 4972, any stop-order with a 2nd hyphen will throw ordertype errors still.

Have you tried reaching out to Kraken support on this issue, regarding the advanced order types? The more users request that – the sooner they will enable those order types back again. My last info is as of Aug 2019 (advanced orders didn't work last summer according to first-hand info from Kraken support). Something may have changed though.

**Comment by moader808** [comment]
> > I guess, is the best practice to just error catch it with a try/except block then?
> 
> I'd say, it's more than just the best practice, it's _a must_ for a quality program ;) In fact, your program is not even guaranteed to work without exception handling. And on average devs spend more time handling the errors than adding new code. In a real-world environment your program will encounter dozens of exceptions even when everything works fine – exceptions are an integral part of a regular application flow.
> 
I've never actually ran into a broker error in production yet that was not initially caught by ccxt to some extent. Some clarification might be needed for the `trading_agreement` parameter in terms of catching it, since ccxt with regards to kraken is not covered.

	try:
		buy_order = await ccxt_broker_api_handler.create_order(symbol='BTC/USD', type=order_type, side=side, amount=bquantity, price=buy_price, params=params)
	except Exception as e:
		print('Broker Error Recieved:{}'.format(e))
		if (e=='EOrder:Trading agreement required'):
			params['trading_agreement'] = 'agree'
		continue

> * https://github.com/ccxt/ccxt/wiki/Manual#error-handling
> 
> > As with stop-orders, is CoinEx's margin/leverage also fall under the same circumstance then(it being spot)?
> 
> Yes, placing perpetual orders with CoinEx won't work without adding the support for that to CCXT.
> 
> > Oh definitely, can still confirm as with 4972, any stop-order with a 2nd hyphen will throw ordertype errors still.
> 
> Have you tried reaching out to Kraken support on this issue, regarding the advanced order types? The more users request that – the sooner they will enable those order types back again. My most recent info is as of Aug 2019 (advanced orders didn't work last summer according to first-hand info from Kraken support). Something may have changed since then, though.

I did actually email there advanced support team 2 days ago, but will query them and add the their heap of requests to bring back the much more advanced (but handy) orders.

**Comment by kroitor** [comment]
@moader808 

> Some clarification might be needed for the trading_agreement parameter in terms of catching it, since ccxt with regards to kraken is not covered.

In general, you can catch it as an ExchangeError: 

- https://github.com/ccxt/ccxt/wiki/Manual#error-handling
- https://github.com/ccxt/ccxt/wiki/Manual#exchangeerror

```Python
try:
	buy_order = await ccxt_broker_api_handler.create_order(symbol='BTC/USD', type=order_type, side=side, amount=bquantity, price=buy_price, params=params)
except ccxt.ExchangeError as e:
        error_message = e.args[0]
	print('Broker Error Recieved', error_message)
	if ('Trading agreement' in error_message):
	        params['trading_agreement'] = 'agree'
                # retry
	continue
```

> I did actually email there advanced support team 2 days ago, but will query them and add the their heap of requests to bring back the much more advanced (but handy) orders.

It would really help a lot if you could also report back here when you have the answer from their tech team. Thx!

**Comment by moader808** [comment]
> @moader808
> 
> > Some clarification might be needed for the trading_agreement parameter in terms of catching it, since ccxt with regards to kraken is not covered.
> 
> In general, you can catch it as an ExchangeError:
> 
> * https://github.com/ccxt/ccxt/wiki/Manual#error-handling
> * https://github.com/ccxt/ccxt/wiki/Manual#exchangeerror
> 
> ```python
> try:
> 	buy_order = await ccxt_broker_api_handler.create_order(symbol='BTC/USD', type=order_type, side=side, amount=bquantity, price=buy_price, params=params)
> except ccxt.ExchangeError as e:
>         error_message = e.args[0]
> 	print('Broker Error Recieved', error_message)
> 	if ('Trading agreement' in error_message):
> 	        params['trading_agreement'] = 'agree'
>                 # retry
> 	continue
> ```
> 
So you can catch any generic exchange error that ccxt does not explicitly cover with ccxt.ExchangeError? I also did not know this prior, thank you for point this out.

> > I did actually email there advanced support team 2 days ago, but will query them and add the their heap of requests to bring back the much more advanced (but handy) orders.
> 
> It would really help a lot if you could also report back here when you have the answer from their tech team. Thx!
Email output with advanced support team 2/2/2020.
Unfortunately, the advanced order types (such as stop-loss-profit, etc.) are not currently available (via the API, Kraken Pro, or any of our trading platforms).

Our developers are working on enabling the advanced order types, and we hope to release the additional order types soon, but we do not yet have an expected date for this release. An announcement will be made on our [official blog](https://blog.kraken.com/) shortly in advance of the advanced order types being released

**Comment by kroitor** [comment]
> So you can catch any generic exchange error that ccxt does not explicitly cover with ccxt.ExchangeError? I also did not know this prior, thank you for point this out.

Yep, see the exception hierarchy here:

- https://github.com/ccxt/ccxt/wiki/Manual#exception-hierarchy

In general, most of oop languages have exceptions derived from one another, so, you can catch an entire branch of exceptions by catching just the root exception type you want.

Thanks for the feedback! As we thought, this is not a problem on the user side, it's just the lack of support of those order types on the exchange side (despite that they're documented). We have nothing left to do but wait for Kraken to add it back.
