### ISSUE TITLE
How do you place a Kraken margin order?  

### ISSUE THREAD

**Issue by JDJoe** [ccxt/ccxt#6438]
_"Warning! I am learning Python and I am a clueless beginner"_ 

I am attempting to get this script https://github.com/Robswc/tradingview-webhooks-bot send out a margin order to Kraken. 

in actions.py file, I have: 
`    order = exchange.create_order(data['symbol'], data['type'], data['side'], data['amount'], calc_price(data['price']))
`
So, I thought adding 
'leverage_buy': [data['leverage'] to this line will do the trick but it's not so. 
Using only "leverage" did not help. 
Leverage level is in the webhook message, sent to the script and it looks like: 
`{"type": "limit", "side": "buy", "amount": "1", "symbol": "LTCEUR", "price": "1", "leverage" : "2", "key": "mykeyhere"}`

Thank you for your help.

**Comment by kroitor** [comment]
> So, I thought adding 'leverage_buy': [data['leverage'] to this line will do the trick but it's not so.

Can you post your code with those options added?

**Comment by JDJoe** [comment]
I have had several "versions" of this. 
Latest one look like : 
`    order = exchange.create_order(data['symbol'], data['type'], data['side'], data['amount'], calc_price(data['price']),"leverage:" data['leverage'])`
but this returns an error of course. 

`    order = exchange.create_order(data['symbol'], data['type'], data['side'], data['amount'], calc_price(data['price']), data['leverage'])` ans so is this.

**Comment by kroitor** [comment]
Ok, this question has been answered here:

- https://github.com/ccxt/ccxt/issues/255#issuecomment-333358568

And it is also documented in the Manual here:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

In general, what you need to do, is to read and follow the Manual carefully, because it says _"read the FAQ"_ which in its turn says _"use the search, Luke"_. If you just type _kraken leverage"_ in the search box on the top of this page – you will immediately find the correct answer among the top results. When you're learning – you're not the first one to have the same question or problem, so there's practically always a readily-available answer to your question, you just have to scratch the surface a little bit to find it. This is really easy if you just follow the written word literally ) You can make it harder for yourself if you skip reading, though.

So, if you want to learn programming python you should be prepared to spend 95% of your time on the docs and tutorials, mostly reading, and 5% actually coding (typing your code). 

So, if you follow the guidelines from the Manual precisely, your code should look like:

```Python
order = exchange.create_order(data['symbol'], data['type'], data['side'], data['amount'], calc_price(data['price']), { 'leverage': YOUR_LEVERAGE_VALUE_HERE })
```

or, which is the same

```Python
params = { 'leverage': YOUR_LEVERAGE_VALUE_HERE }
order = exchange kraken.create_order(data['symbol'], data['type'], data['side'], data['amount'], calc_price(data['price']), params)
```

See the `params` override there (the last argument to the `create_order()` call). It should be a dictionary, as required by the Manual again.

One of the above snippets will work, assuming that the other values are all correct. I'm specifically showing how to use `params` overrides, but i can't check the values in your `data`, of course. 

Hope that helps.

**Comment by JDJoe** [comment]
` { 'leverage': data["leverage"] }`
did the trick. I have no idea, why it never worked before.  
Thanks

**Comment by kroitor** [comment]
> I have no idea, why it never worked before.

You were submitting `data["leverage"]` (a value) instead of `{'leverage': data["leverage"]}` (a dictionary of values).

**Comment by gelinger777** [comment]
@kroitor  to be honest I tried many things but can't make kraken to close the position. I am initiating it with 
```
  const ccxtClient = (this.ccxtClient = new ccxt.kraken({
      apiKey: config.key,
      secret: config.secret,
      enableRateLimit: true,
      options: {
        defaultType: 'margin', 
    }
    }));
```

and   i am passing leverage:5 in options 


```
Order {
  id: 1580101594386,
  symbol: 'BTC/EUR',
  side: 'long',
  price: '30141.40000',
  amount: 56.39313,
  type: 'limit',
  options:
   { close: true, adjust_price: true, post_only: true, leverage: 5 } }
false 'buy' { close: true, adjust_price: true, post_only: true, leverage: 5 }
{"message":"Order create canceled:{\"id\":1580101594386,\"symbol\":\"BTC/EUR\",\"side\":\"long\",\"price\":\"30141.40000\",\"amount\":56.39313,\"type\":\"limit\",\"options\":{\"close\":true,\"adjust_price\":true,\"post_only\":true,\"leverage\":5}} - \"InsufficientFunds: kraken {\\\"error\\\":[\\\"EOrder:Insufficient funds\\\"]}\"","level":"error","timestamp":"2021-01-17T03:16:49.771Z"}
```

**Comment by kroitor** [comment]
@gelinger777 i'll post a proper example here shortly.

**Comment by gelinger777** [comment]
@kroitor  Thank you Igor for your efforts.

**Comment by gelinger777** [comment]
@kroitor  could you share the example, please ..

**Comment by kroitor** [comment]
@gelinger777 pardon for the long wait, I got sidetracked a bit, I'll write one today and will post here immediately, plz, hold on.

**Comment by gelinger777** [comment]
@kroitor  i understand friend. No problem. Just waiting for it to finish one small thing i am doing..

**Comment by gelinger777** [comment]
@kroitor I see you are too buisy :( could you do it today?

**Comment by kroitor** [comment]
@gelinger777 writing it now, will upload today, plz hold on, thx for your patience!

**Comment by kroitor** [comment]
@gelinger777 once again, pardon for the delays – i have upload the long-awaited example, please check it out. You will need to upgrade to CCXT version 1.40.98 or higher to run it. Also, you will need around 40 USDT to run this live test and see the position get open and closed (make sure you have enough balance to settle your positions). Let me know if that does not help.

- https://github.com/ccxt/ccxt/blob/master/examples/js/kraken-margin-trading.js

```JavaScript
"use strict";

const ccxt = require ('ccxt');

console.log ('CCXT Version:', ccxt.version)

async function main () {

    const exchange = new ccxt.kraken ({
        'enableRateLimit': true,
        "apiKey": "YOUR_API_KEY",
        "secret": "YOUR_SECRET",
    })

    console.log ('-----------------------------------------------------------')

    console.log ('Loading markets...')
    const markets = await exchange.loadMarkets ()
    console.log ('Markets loaded')

    // exchange.verbose = true // uncomment for debugging purposes

    try {

        const symbol = 'ETH/USDT'
            , market = exchange.market (symbol)
            , { base, quote } = market
            , type = 'market'
            , amount = market['limits']['amount']['min']
            , price = undefined
            , params = {
                'leverage': 2,
            }

        console.log ('-----------------------------------------------------------')

        // https://www.kraken.com/en-us/features/api#add-standard-order

        console.log ('Placing order...')
        let order = await exchange.createOrder (symbol, type, 'buy', amount, price, params)
        console.log ('Order placed:')
        console.log (order)

        console.log ('-----------------------------------------------------------')

        // https://www.kraken.com/en-us/features/api#get-open-positions

        console.log ('Fetching open positions...')
        const positionsParams = { 'docalcs': true }
        let openPositions = await exchange.fetchPositions (positionsParams)
        console.log ('Current positions:')
        console.log (openPositions)

        console.log ('-----------------------------------------------------------')

        console.log ('Fetching balance...')
        let balance = await exchange.fetchTotalBalance ()
        console.log ('Fetched balance:')
        console.log (base, balance[base], '(base)')
        console.log (quote, balance[quote], '(quote)')

        console.log ('-----------------------------------------------------------')

        console.log ('Closing the position...')
        order = await exchange.createOrder (symbol, type, 'sell', amount, price, params)
        console.log ('Got a response:')
        console.log (order)

        console.log ('-----------------------------------------------------------')

        console.log ('Fetching open positions again...')
        openPositions = await exchange.fetchPositions (positionsParams)
        console.log ('Current positions:')
        console.log (openPositions)

        console.log ('-----------------------------------------------------------')

        console.log ('Fetching balance...')
        balance = await exchange.fetchTotalBalance ()
        console.log ('Fetched balance:')
        console.log (base, balance[base], '(base)')
        console.log (quote, balance[quote], '(quote)')

    } catch (e) {

        console.log (e.constructor.name, e.message)
    }
}

main ()
```

**Comment by gelinger777** [comment]
thank you very much @kroitor
