### ISSUE TITLE
GDAX cancel orders broken (Invalid Signature)

### ISSUE THREAD

**Issue by anandanand84** [ccxt/ccxt#644]
Not sure starting which version it is broken, Cancel order with 1.10.186 return error "Invalid signature" while it works fine in 1.10.15

**Comment by kroitor** [comment]
A few changes to it were recently added here: https://github.com/ccxt/ccxt/issues/615. This is most likely related... Can you confirm that it's a keypair you're not using with any other software?

**Comment by anandanand84** [comment]
@kroitor  yes I am using javascript and the issue is not with key pairs.

**Comment by kroitor** [comment]
This should be fixed as of 1.10.192. Let us know if you still have difficulties with it.
