### ISSUE TITLE
Help on Binanace marging data

### ISSUE THREAD

**Issue by esteban2006** [ccxt/ccxt#6442]
Hello @kroitor  I have created my class (class FetchDataBinance ) with methods such 

```
def __init__(self):
        self.instance = ccxt.binance()
        self.instance.apiKey = api_key
        self.instance.secret = api_secret

def get_balance(self, symbol):
        time.sleep(0.5)
        balance = 0
        asset = symbol.split('/')[0]
        data = None
        for i in range(0, 5):
            try:
               data = self.instance.fetch_balance()['info']['balances']
               # print (data[asset])
               for _data in data:
                   if _data['asset'] == asset:
                       balance = float(_data['free'])
               break
            except Exception as e:
                print(e)
                time.sleep(5)
                continue
        return balance
```
so this was before the margin updates on ccxt and binance api, but now i am trying to call the margin implicit methods, but no matter what I do with this, I can't get the info from the margin account, would you please show me how to modify  data = self.instance.fetch_balance()['info']['balances'] to get the info from my margin account 

best regards,

- OS: linux, ubuntu dist
- Programming Language version: python 3.65
- CCXT version: lates
- Exchange: binance
- Method: all marginal in general

**Comment by kroitor** [comment]
Hi @esteban2006 !

FIrst of, the margin trading with Binance is not completely unified in CCXT yet.

In general, CCXT has two modes of operation:

- Unified API (you call a unified CCXT method which invokes the endpoints of the exchange)
- Implicit API methods (you call an implicit CCXT method which invokes those endpoints directly)

CCXT has the following parts of Binance API:

- Spot API (both implicit and unified)
- Futures API (both implicit and unified)
- Margin API (implicit, but not unified yet)
- WS (will be [released in CCXT Pro soon](https://github.com/ccxt/ccxt/issues/6332))

The difference between Unified and Implicit methods is explained in the Manual, here:

- https://github.com/ccxt/ccxt/wiki/Manual#unified-api
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

Also, see these relates issues:

- https://github.com/ccxt/ccxt/issues/6376
- https://github.com/ccxt/ccxt/issues/4834

Because `fetch_balance` is a method of the unified API family, you can't use it for fetching Binance margin balance just yet. That is, until we finish the unification of Binance margin trading API.

What you can do, however, is querying the implicit margin endpoints which are all included and supported in CCXT. This can be done like shown below:

```Python
def __init__(self):
        self.instance = ccxt.binance({
            'apiKey': api_key,
            'secret': api_secret,
            'enableRateLimit': True,  # required by the Manual https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
            # uncomment the lines below if you're trading Binance futures
            # 'options': {
            #     'defaultType': 'future',
            # },
        })

def get_balance(self, symbol):
        self.instance.load_markets()
        market = self.instance.market(symbol)
        try:
            response = self.instance.sapi_get_margin_account()
            assets = self.instance.safe_value(response, 'userAssets', [])
            accounts = self.instance.index_by(assets, 'asset')
            account = self.instance.safe_float(accounts, market['baseId'])
            if account:
                return self.instance.safe_float(account, 'free')
        except Exception as e:
            print(e)
        return 0
```

I haven't tested it (don't have the time), but it should work with very few edits for typos or whatever.

Hope it helps, let us know if not.

**Comment by esteban2006** [comment]
@kroitor thank you for response

I did try you method, the system response is the same I am getting, my problem is the same try to figure out the implicit method


```
'binance' object has no attribute 'sapi_get_margin_account'
0
```

**Comment by kroitor** [comment]
It has something to do with your class. If you remove everything but CCXT code, it will work:

```Python
# theprogram.py
import ccxt
exchange = ccxt.binance({
            'apiKey': api_key,
            'secret': api_secret,
            'enableRateLimit': True,  # required by the Manual https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
            # uncomment the lines below if you're trading Binance futures
            # 'options': {
            #     'defaultType': 'future',
            # },
        })
print('CCXT version:', ccxt.__version__)
exchange.load_markets()
market = exchange.market(symbol)
try:
    # enable verbose output for debugging
    exchange.verbose = True
    response = exchange.sapi_get_margin_account()
    assets = exchange.safe_value(response, 'userAssets', [])
    accounts = exchange.index_by(assets, 'asset')
    account = exchange.safe_float(accounts, market['baseId'])
    if account:
        print(market['base'], 'balance:', exchange.safe_float(account, 'free'))
except Exception as e:
        print(e)
print('Done.')
```

↑ This is a complete program that should work (with your keys), when you run it with a standard python in command line:

```shell
python theprogram.py
```

If it does not work – please, paste the output here (without your keys).

**Comment by kroitor** [comment]
The same stuff done with a class:

```Python
import ccxt

class MyBinance:
    def __init__(self):
        self.instance = ccxt.binance({
            'apiKey': api_key,
            'secret': api_secret,
            'enableRateLimit': True,  # required by the Manual https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
            # uncomment the lines below if you're trading Binance futures
            # 'options': {
            #     'defaultType': 'future',
            # },
        })

    def get_balance(self, symbol):
        self.instance.load_markets()
        market = self.instance.market(symbol)
        try:
            response = self.instance.sapi_get_margin_account()
            assets = self.instance.safe_value(response, 'userAssets', [])
            accounts = self.instance.index_by(assets, 'asset')
            account = self.instance.safe_float(accounts, market['baseId'])
            if account:
                return self.instance.safe_float(account, 'free')
        except Exception as e:
            print(e)
        return 0


symbol = 'YOUR_SYMBOL_HERE'
exchange = MyBinance()
print(exchange.get_balance(symbol))
```

**Comment by esteban2006** [comment]
@kroitor  thank you very much for your help, the bot file helped me figure out the problem on my code.

**Comment by kroitor** [comment]
@esteban2006 cheers! )

**Comment by Princeton007** [comment]
@kroitor 

I have 2 issues related to Magin Trading on Binance: 

1) I'm still struggling to use the implicit API to 
Get Margin Positions (current active trades)  I tried different things but no success so far.

Maybe you or someone who's done it before can post a short example?! 

And 
2) while trying different things out I tried your exmple which results in  **float() argument must be a string or a number, not 'dict**

As follows

CCXT version: 1.23.86

Request: GET https://api.binance.com/sapi/v1/margin/account?timestamp=1583961949926&recvWindow=5000&signature=***{'X-MBX-APIKEY': '***', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.binance.com/sapi/v1/margin/account?timestamp=1583961949926&recvWindow=5000&signature=8c2a45920fab6e21934c7f0ed017afbc59c0c13a0f78ebdc9e01626f2a4918e7 200 {'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Wed, 11 Mar 2020 21:25:50 GMT', 'Server': 'nginx', 'Vary': 'Accept-Encoding', 'X-Application-Context': 'sapi:bnb-prod:9056', 'X-MBX-USED-WEIGHT-60S': '1', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 d11ab7cc015083593a9e8e8e2dac0692.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'AMS50-C1', 'X-Amz-Cf-Id': '-PwqpaE2ATMV_FIHrFbpEP9gfpYgR-aEPeF3lV-Y0uYkmiVO5kVztw=='} {"borrowEnabled":true,"marginLevel":"999.00000000","totalAssetOfBtc":"0.00496910","totalLiabilityOfBtc":"0.00000000","totalNetAssetOfBtc":"0.00496910","tradeEnabled":true,"transferEnabled":true,"userAssets":
*deleted some lines here*
"}]}
**Error:  float() argument must be a string or a number, not 'dict'**
Done.

**Comment by kroitor** [comment]
@Princeton007 pardon, there was a minor typo in the example code, `safe_float` → `safe_value`. That was more like a snippet to play with, assuming you know Python well to resolve minor things like accessing dictionary keys. 

But, anyways, here's the corrected snippet, i hope no other typos left %))


```Python
import ccxt

class MyBinance:
    def __init__(self):
        self.instance = ccxt.binance({
            'apiKey': api_key,
            'secret': api_secret,
            'enableRateLimit': True,  # required by the Manual https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
            # uncomment the lines below if you're trading Binance futures
            # 'options': {
            #     'defaultType': 'future',
            # },
        })

    def get_balance(self, symbol):
        self.instance.load_markets()
        market = self.instance.market(symbol)
        try:
            response = self.instance.sapi_get_margin_account()
            assets = self.instance.safe_value(response, 'userAssets', [])
            accounts = self.instance.index_by(assets, 'asset')
            account = self.instance.safe_value(accounts, market['baseId'])  # ←--------  HERE
            if account:
                return self.instance.safe_float(account, 'free')
        except Exception as e:
            print(e)
        return 0


symbol = 'YOUR_SYMBOL_HERE'
exchange = MyBinance()
print(exchange.get_balance(symbol))
```

Let us know if you still have issues with it.

**Comment by Princeton007** [comment]
I have 2 issues related to Magin Trading on Binance:

I'm still struggling to use the implicit API to
Get Margin Positions (current active trades) I tried different things but no success so far.
Maybe you or someone who's done it before can post a short example?! Or maybe this above is already the example!? I have no open positions right now which could be shown but in any case I get the following error:

 **float() argument must be a string or a number, not 'dict**

As follows (I shortened the output and exchanged some values by ***):

CCXT version: 1.23.86

Request: GET https://api.binance.com/sapi/v1/margin/account?timestamp=1583961949926&recvWindow=5000&signature=***{'X-MBX-APIKEY': '***', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.binance.com/sapi/v1/margin/account?timestamp=1583961949926&recvWindow=5000&signature=***200 {'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Wed, 11 Mar 2020 21:25:50 GMT', 'Server': 'nginx', 'Vary': 'Accept-Encoding', 'X-Application-Context': 'sapi:bnb-prod:9056', 'X-MBX-USED-WEIGHT-60S': '1', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 d11ab7cc015083593a9e8e8e2dac0692.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'AMS50-C1', 'X-Amz-Cf-Id': '-PwqpaE2ATMV_FIHrFbpEP9gfpYgR-aEPeF3lV-Y0uYkmiVO5kVztw=='} {"borrowEnabled":true,"marginLevel":"999.00000000","totalAssetOfBtc":"0.00496910","totalLiabilityOfBtc":"0.00000000","totalNetAssetOfBtc":"***","tradeEnabled":true,"transferEnabled":true,"userAssets":
deleted some lines here
"}]}
Error: float() argument must be a string or a number, not 'dict'
Done.

**Comment by kroitor** [comment]
@Princeton007 see the answer one post above: https://github.com/ccxt/ccxt/issues/6442#issuecomment-597892766

**Comment by Princeton007** [comment]
@kroitor I'm still quite new, learning a lot and improving my Python knowledge, your excellent support is highly appreciated! And it works now :-)

**Comment by kroitor** [comment]
@Princeton007 awesome, thx for reporting back! )
