### ISSUE TITLE
Bitfinex margin and exchange market order issue

### ISSUE THREAD

**Issue by CooleRnax** [ccxt/ccxt#6445]
I can't use both exchange market and margin market orders at the same time.

This is how it can be fixed:
`if type == 'market':`
to
`if 'market' in type:`

- OS: Windows
- Programming Language version: python
- CCXT version: 1.21.77
- Exchange: bitfinex
- Method: create_order

**Comment by kroitor** [comment]
This has been answered here:

- https://github.com/ccxt/ccxt/issues/130#issuecomment-323608343
- https://github.com/ccxt/ccxt/issues/1207#issuecomment-357154252
- https://github.com/ccxt/ccxt/issues/157#issuecomment-325179246

> I can't use both exchange market and margin market orders at the same time.

Oh, yes you can! )

Market Order

```Python
result = bitfinex.create_order(symbol="XRP/BTC", type = "market", side = "sell", amount = 100, params)
```

Market/Margin Order

```Python
params = { 'type': 'market' }  # 'market' without the 'exchange ' prefix means a margin order type
result = bitfinex.create_order(symbol="XRP/BTC", type = "market", side = "sell", amount = 100, params)
```

Let us know if that does not answer the question.

**Comment by benwaldner** [comment]
> This has been answered here:
> 
>     * [#130 (comment)](https://github.com/ccxt/ccxt/issues/130#issuecomment-323608343)
> 
>     * [#1207 (comment)](https://github.com/ccxt/ccxt/issues/1207#issuecomment-357154252)
> 
>     * [#157 (comment)](https://github.com/ccxt/ccxt/issues/157#issuecomment-325179246)
> 
> 
> > I can't use both exchange market and margin market orders at the same time.
> 
> Oh, yes you can! )
> 
> Market Order
> 
> ```python
> result = bitfinex.create_order(symbol="XRP/BTC", type = "market", side = "sell", amount = 100, params)
> ```
> 
> Market/Margin Order
> 
> ```python
> params = { 'type': 'market' }  # 'market' without the 'exchange ' prefix means a margin order type
> result = bitfinex.create_order(symbol="XRP/BTC", type = "market", side = "sell", amount = 100, params)
> ```
> 
> Let us know if that does not answer the question.

How would a margin order look like for Bitfinex?

return bitfinex.create_order("TESTBTCF0/TESTUSDTF0", "margin market", "buy", 100) ?
And params I didnt understood that part. Could I just leave it empty.
Or what should I fill into params to successfully place a margin trade on Bitfinex using CCXT?

**Comment by kroitor** [comment]
> How would a margin order look like for Bitfinex?

It has been answered in this issue a few comments above:

```Python
import ccxt
from pprint import pprint

exchange = ccxt.bitfinex({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
})

exchange.load_markets()

# exchange.verbose = True  # uncomment for debug output

symbol = 'XRP/BTC'
type = 'market'
side = 'sell'
amount = 100
price = None
params = { 'type': type }  # 'market' without the 'exchange ' prefix means a margin order type

result = exchange.create_order(symbol, type, side, amount, price, params)

pprint(result)
```

**Comment by kroitor** [comment]
@CooleRnax i would highly recommend to read the entire Manual from top to bottom, it will save your time: 

- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/Manual
