### ISSUE TITLE
Bitstamp v2 authentication method

### ISSUE THREAD

**Issue by vr-fox** [ccxt/ccxt#6456]
V2 AUTHENTICATION METHOD
We introduced a new authentication method that allows for easier nonce handling and is much safer since all relevant content is signed.

Since we strive for simplicity and better security, we encourage you to use this new authentication method.

For a successful authentication you need to provide the following authorization headers in your request:

This is available only for API V2 endpoints.

Please note that you do not need to set key, signature and nonce request parameters using this authentication method. You also do not need to set Content-Type header if there is no body.

Request headers
--
X-Auth | "BITSTAMP" + " " + api_key
X-Auth-Signature | sha256.hmac(string_to_sign, api_secret)
X-Auth-Nonce | Client generated random nonce:- lowercase,- 36 char string,- each nonce can be used only once within a timeframe of 150 seconds.Example: "f93c979d-b00d-43a9-9b9c-fd4cd9547fa6"
X-Auth-Timestamp | Request departure timestamp UTC in milliseconds. If timestamp is more than 150 seconds from current server time, it will not allow to make the request.Example: "1567755304968"
X-Auth-Version | "v2"
Content-Type | "application/x-www-form-urlencoded"

https://www.bitstamp.net/api/

- OS: N/A
- Programming Language version: Javascript
- CCXT version: newest
- Exchange: bitstamp
- Method: sign (authentication)

**Comment by frosty00** [comment]
> For a successful authentication you need to provide the following authorization headers in your request:

which ones, hehe

**Comment by vr-fox** [comment]
https://www.bitstamp.net/api/

**Comment by kroitor** [comment]
@vr-fox thank you! We will add this feature shortly.

**Comment by vr-fox** [comment]
@kroitor thank you for the update status

**Comment by vr-fox** [comment]
@kroitor any news on this request?? if not much to ask... eta?

**Comment by kroitor** [comment]
@vr-fox i'll do my best to resolve it this week.

**Comment by kroitor** [comment]
@vr-fox good news, we've added the necessary edits and now default to auth method v2 for Bitstamp! Thank you for your patience and help!

**Comment by CMcGoldrick** [comment]
hello, I keep getting the following error "X-Auth-Timestamp header is out of boundaries" - however, I confirmed I am getting the current UTC timestamp (at time of writing: 1666054262)
