### ISSUE TITLE
Bittrex - BCH not included in balances

### ISSUE THREAD

**Issue by janeCMD** [ccxt/ccxt#646]
BCH shows always zeros on Bittrex, its likely because Bittrex uses 'BCC' code for BCH. Creating orders works with BCH symbol, but fetching balance doesn't.

**Comment by kroitor** [comment]
@janeCMD how do you access the BCH amount in the returned balance structure?

**Comment by janeCMD** [comment]
I checked the api response, bch shows 0 in all arrays - total, available,pending and [bch]. Only [info] contains information about bch balance under key [BCC]

**Comment by kroitor** [comment]
@janeCMD got it, thx, will fix it shortly.

**Comment by kroitor** [comment]
Does this work for you?

```PHP
<?php

include 'ccxt.php';

$id = 'bittrex';
$exchange = '\\ccxt\\' . $id;
$exchange = new $exchange (array (
    "apiKey" => "471b47a06c384e81b24072e9a8739064",
    "secret" => "694025686e9445589787e8ca212b4cff",
    "verbose" => true,
));
$response = $exchange->fetch_balance();

echo "--------------------------------------------------------\n";
echo "Total balance:\n";
print_r ($response);
echo "\n";
echo "--------------------------------------------------------\n";
echo "BCH balance:";
var_dump ($response['BCH']);

?>
```

**Comment by kroitor** [comment]
Let us know if it works for you or not, please. I'm closing this for now, feel free to reopen it if necessary or ask questions. Thanks!
