### ISSUE TITLE
Binance MARKET_LOT_SIZE

### ISSUE THREAD

**Issue by hroff-1902** [ccxt/ccxt#6460]
Binance has both LOT_SIZE and MARKET_LOT_SIZE 'filterType's and MARKET_LOT_SIZE differs from LOT_SIZE for some markets.

ccxt only provide us LOT_SIZE in ['limits']['amount']

We would like to correctly check amounts of market orders against MARKET_LOT_SIZE.

Possible structure (just as an example):
```
    limits
        cost # MIN_NOTIONAL
        amount # LOT_SIZE
        market_amount # MARKET_LOT_SIZE
```
or
```
    limit # for limit orders
        limits
            cost # MIN_NOTIONAL
            amount # LOT_SIZE
    market # for market orders
        limits
            cost # MIN_NOTIONAL
            amount # MARKET_LOT_SIZE
```
or
```
    limits
        limit # for limit orders
            cost # MIN_NOTIONAL
            amount # LOT_SIZE
        market # for market orders
            cost # MIN_NOTIONAL
            amount # MARKET_LOT_SIZE
```
or something like that

**Comment by kroitor** [comment]
@hroff-1902 i will get to this within a few days, thx!

**Comment by hroff-1902** [comment]
revoking my 'hooray' reaction emoji I set at the previous post...

**Comment by kroitor** [comment]
@hroff-1902 pardon for the delay, i'll do my best to resolve this as soon as I can.

**Comment by hroff-1902** [comment]
Have not seen that post with deadline for CCXT Pro set as 1st of March 2020 before wrote the above, sorry.
👍

**Comment by hroff-1902** [comment]
Thanks, will test it 👍 

Can you mention this new item of the market structure in the Unified interface manual? So that we could rely in the app that this will be used same way for other exchanges (where it's applicable)

**Comment by kroitor** [comment]
> Can you mention this new item of the market structure in the Unified interface manual?

Yep, will add that shortly, thx for the feedback!

**Comment by fievelk** [comment]
Hi, I've seen that the `stepSize` has been added for the `LOT_SIZE` filter (see two lines below), but not for the `MARKET_LOT_SIZE` one:

https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L781-L782

Is this going to be added, or is there a different way to fix issues with MARKET_LOT_SIZE?

**Comment by kroitor** [comment]
> Hi, I've seen that the stepSize has been added for the LOT_SIZE filter (see two lines below), but not for the MARKET_LOT_SIZE one:
> https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L781-L782
> Is this going to be added,

If you check this endpoint from Binance API that serves those filters, all MARKET_LOT_SIZE's stepSize values are either zeroed or missing:

- https://api.binance.com/api/v3/exchangeInfo

<img width="1379" alt="Screen Shot 2020-09-17 at 04 18 14" src="https://user-images.githubusercontent.com/1294454/93408278-daf07600-f89c-11ea-88d6-a4bc15e63d3f.png">

So, it's not entirely clear how adding those zeroes could help.

> or is there a different way to fix issues with MARKET_LOT_SIZE?

Yes, please, report the issue precisely as described here: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help. Namely, we need your versions, your code to reproduce it, including the instantiation, but without your keys, of course, and your verbose request+response output (see the FAQ for details).

**Comment by fievelk** [comment]
@kroitor Thank you. Does it mean that Binance does not enforce a step size on market orders?

**Comment by kroitor** [comment]
@fievelk 

> Does it mean that Binance does not enforce a step size on market orders?

Nope, it means that Binance enforces a step size of zero, which is a nonsense (it makes no sense, since the step has to be a positive non-zero number). In other words, Binance does enforce a step size, but it does not define a non-zero step, which makes it practically impossible to adjust to the market-order precision. Therefore, if you have some difficulties with it, let us know and we will help resolve it. Please, make sure to provide all the info mentioned above.

**Comment by sammosna** [comment]
Hi, I have a similar problem. When i place an order it gives me back a MARKET_LOT_SIZE error.
For example with this order: SELL CKB/BTC with 31682.286 CKB it says `InvalidOrder binance order amount should be evenly divisible by lot size {"code":-2010,"msg":"Filter failure: MARKET_LOT_SIZE"}`. Could you help me somehow? Thanks

**Comment by kenchambers** [comment]
@kroitor any updates on this issue?

**Comment by kroitor** [comment]
@kenchambers it is supposed to be resolved, if you have this issue with a new version of the lib, please, paste your versions, your code and your verbose output (enable verbose mode before the failing call, after loading the markets):

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
- https://docs.ccxt.com/en/latest/manual.html#troubleshooting

**Comment by kenchambers** [comment]
> @kenchambers it is supposed to be resolved. Ff you have this issue with a new version of the lib, please, paste your versions, your code and your verbose output (enable verbose mode before the failing call, after loading the markets):
> 
> * https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
> * https://docs.ccxt.com/en/latest/manual.html#troubleshooting

I will post here if I run into the issue on the latest version of the library, I do not have it installed.

**Comment by Rhistak** [comment]
Sorry why this was closed? There is no solucion already for this issue?

**Comment by Rhistak** [comment]
I'm trying to do a trade with the python-binance library and I'm getting 
'binance.exceptions.BinanceAPIException: APIError(code=-1013): Filter failure: MARKET_LOT_SIZE'
