### ISSUE TITLE
Bitlish my trade history metod?

### ISSUE THREAD

**Issue by goga1978** [ccxt/ccxt#6464]
Hi. Tell me how to view your history of executed orders?
print(bitlish_api,bitlish_api.fetch_closed_orders(symbol='DOGE/BTC')) not

print(bitlish_api,bitlish_api.fetch_trades(symbol='DOGE/BTC')) all orders - not 

my trade history ?

**Comment by kroitor** [comment]
Hi!

The unified API method for fetching the history of your trades is called `fetchMyTrades`. The `fetchTrades` method is for public (not your) trades only. However, the `fetchMyTrades` for bitlish is not imlemented yet (we hope to get to it asap). In the meantime, you can also query those trades using Implicit API methods from CCXT:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

```Python
import ccxt
exchange = ccxt.bitlish({
    'apiKey': 'YOUR_API_KEY', 
})
response = exchange.private_post_list_my_trades()
```

You can see the list of all supported endpoints here:

- https://github.com/ccxt/ccxt/blob/master/js/bitlish.js#L70

Let us know if that does not answer the question.

**Comment by goga1978** [comment]
Спасибо :)
