### ISSUE TITLE
orderQty is invalid although it looks fine to me @ Bitmex

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [ccxt/ccxt#6466]
The way to reproduce the issue is straight fordward, here is more or less the code used:

```
    let exchangeId
    let options = {}
    let exchange

    const ccxt = require('ccxt')

...............
        exchangeId = bot.exchange.toLowerCase()

        let key = process.env.KEY
        let secret = process.env.SECRET

        if (key === "undefined") { key = undefined }
        if (secret === "undefined") { secret = undefined }
...............
        const exchangeClass = ccxt[exchangeId]
        const exchangeConstructorParams = {
            'apiKey': key,
            'secret': secret,
            'timeout': 30000,
            'enableRateLimit': true,
            verbose: true,
            options: options
        }

        exchange = new exchangeClass(exchangeConstructorParams)

order = await(exchange.createOrder(symbol, type, side, amount))
```

- OS: Windows 10 Home
- Programming Language version: λ javascript node -v v8.11.4
- CCXT version: "ccxt": "^1.22.39"
- Exchange: Bitmex
- Method: exchange.createOrder()

The API DOCS says:

> orderQty   Order quantity in units of the instrument (i.e. contracts).  formData  double

The value sent was: 0.003
Thinking the amount might be too low I also tried with 0.01 and 0.001 with the same results.

```
fetch:
 bitmex POST https://www.bitmex.com/api/v1/order
Request:
 { 'Content-Type': 'application/json',
  'api-key': 'MY API KEY REMOVED',
  'api-expires': '1581260549',
  'api-signature': 'SIGNATURE REMOVED' }
 {"symbol":"XBTUSD","side":"Sell","orderQty":0.003,"ordType":"Market"}

handleRestResponse:
 bitmex POST https://www.bitmex.com/api/v1/order 400 Bad Request
Response:
 { Connection: 'keep-alive',
  'Content-Length': '62',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Sun, 09 Feb 2020 15:02:23 GMT',
  Etag: 'W/"3e-pTLJxR1SshmWX4CsUr6HwNWjqd8"',
  'Set-Cookie': 'AWSALB=oI6zvmURfNnd8WSDUm4cDfbgJ0uYnloDWhejkF2nHi7l+WDDz/mDjX8IEFQ/9w1/x/mv2qa1mdcsxWfZxe/DAz46CH9nI0sF/gDjIzB5mg8q2n53BHsIZQOKBF7M; Expires=Sun, 16 Feb 2020 15:02:23 GMT; Path=/, AWSALBCORS=oI6zvmURfNnd8WSDUm4cDfbgJ0uYnloDWhejkF2nHi7l+WDDz/mDjX8IEFQ/9w1/x/mv2qa1mdcsxWfZxe/DAz46CH9nI0sF/gDjIzB5mg8q2n53BHsIZQOKBF7M; Expires=Sun, 16 Feb 2020 15:02:23 GMT; Path=/; SameSite=None; Secure',
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
  'X-Powered-By': 'Profit',
  'X-Ratelimit-Limit': '60',
  'X-Ratelimit-Remaining': '58',
  'X-Ratelimit-Reset': '1581260544' }
 {"error":{"message":"orderQty is invalid","name":"HTTPError"}}
```

**Comment by kroitor** [comment]
@Luis-Fernando-Molina hi!

For BitMEX the orderQty should be the number of contracts you want to buy or sell (integer, not a rational/float number). Let us know if that does not help or does not answer the question.

**Comment by kroitor** [comment]
More about it here:

- https://github.com/ccxt/ccxt/issues/6157
- https://github.com/ccxt/ccxt/issues/5193

**Comment by Luis-Fernando-Molina** [comment]
hey @kroitor !

> For BitMEX the orderQty should be the number of contracts you want to buy or sell (integer, not a rational/float number). Let us know if that does not help or does not answer the question.

Not really. Would you mind defining **contract**?

**Comment by Luis-Fernando-Molina** [comment]
I am working with spot markets, not futures. I haven't seen the concept of market in this context.

**Comment by kroitor** [comment]
@Luis-Fernando-Molina it is defined by BitMEX itself here:

- https://www.bitmex.com/app/perpetualContractsGuide
- https://www.bitmex.com/app/contract/XBTUSD

> I am working with spot markets, not futures. I haven't seen the concept of market in this context.

BitMEX is all about non-spot markets (futures trading / perpetual contracts). Each *contract* is basically the same thing as a *spot trading pair* with a few differences on the quantities and settlement.

Let me know if anything. Don't hesitate to reopen this issue or just ask further questions, if any.
