### ISSUE TITLE
Binance, How to Obtain Current Account Positions of Futures Contracts

### ISSUE THREAD

**Issue by supersausage007** [ccxt/ccxt#6469]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10
- Programming Language version: Python 3.6
- CCXT version: 2.26
- Exchange: binance
- Method: fetchBalance

******************************************************************************
Hi Team,

Could you please point me in the direction, how to retrieve the current position (the equivalent of the "Size" column you would see on their Futures Market web console) of a Futures contract in my Binance Futures Account (spot works absolutely fine). I have successfully pointed towards the fapi endpoint, it is just that the method .FetchBalance() does not seem to contain any information about the quantity of how many Futures the account owns (e.g.: for Bitmex, this is solved by using the method call ".private_get_position()"). 

Could you please point me in the right direction (I am not sure this is an actual issue)?

Thank you very much in advance!

**Comment by kroitor** [comment]
@supersausage007 hi! Try this:

```Python
import ccxt
from pprint import pprint
exchange = ccxt.binance({
    'enableRateLimit': True,  # required by the Manual https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
    'options': {  # exchange-specific options
        'defaultType': 'future',  # switch to a futures API/account
    },
})
pprint(exchange.fetchBalance())
```

↑ This should generate the output you need. Let me know if that does not help. Feel free to reopen this issue if needed, or just ask further questions, if any.

**Comment by supersausage007** [comment]
@kroitor Thank you for coming back to me!

Unfortunately, `.fetchBalance()` does not do the trick for Binance _Futures_, as it misses the crucial element "amount" or "quantity" of the contract (see my org. question ;)    ).

Since then we have found that the call `GET /fapi/v1/positionRisk` has the actual entry 'positionAmt', which depicts the (fractionally denoted) contract quantity. 

At the moment, we created a private method call to 'positionAmt', in order to manage this. We are still wondering how to merge the two information sets efficiently, since many people will most likely like to see position as well as margin information for their Binance Futures trading.

Let me know what you think of the following as an idea: it may make sense to implement an option to  `.fetchBalance()` looking something like '(option={ get_positionAmt : true })', where user would have the choice to get full position info (margin, risk, contract quantity) at the cost of 2 requests for the entire account update.

Thank you again!

**Comment by kroitor** [comment]
@supersausage007 the futures trading is not completely unified in CCXT yet (it is currently a work in progress). However, you can still use it with CCXT's implicit API methods as described in the Manual: 

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

So, the CCXT code for that endpoint would look like:

```Python
import ccxt
from pprint import pprint
exchange = ccxt.binance({
    'enableRateLimit': True,  # required by the Manual https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
    'options': {  # exchange-specific options
        'defaultType': 'future',  # switch to a futures API/account
    },
})
pprint(exchange.fapiPrivatePositionrisk())  # or fapiPrivate_get_positionrisk()
```

Let me knof if that does not help.

**Comment by kroitor** [comment]
@h-keskin 

```PHP
$id = 'binance';
// instantiate the exchange by id
$exchange = '\\ccxt\\' . $id;
$exchange = new $exchange(array(
    'enableRateLimit' => true,
    'apiKey' => 'YOUR_API_KEY',
    'secret' => 'YOUR_SECRET',
    'options' => array(
        'defaultType' => future,
    ),
));
$result = $exchange->fapiPrivate_get_positionrisk();
var_dump($result);
```

It's basically a line-to-line equvalent.

**Comment by h-keskin** [comment]
This query returns **response**, **result** (json) and **array** together. Which command should we use if we want to output **only as array** or **only as json?**

**Comment by kroitor** [comment]
@h-keskin sorry, 

> This query returns response, result (json) and array together. 

It's not entirely clear what you mean. Can you clarify?

- `var_dump($result)` will simply print the `$result` as a variable as explained in the PHP Manual: https://www.php.net/var_dump
- `print_r($result);` will print a human-readable contents of `$result` as explained in the PHP Manual: https://www.php.net/print_r
- `echo(json_encode($result) ."\n";` will print `$result` as JSON using the echo, as explained in the PHP Manual: https://www.php.net/echo + https://www.php.net/json_encode

You question isn't really about CCXT, but more like on how to use PHP.

**Comment by markoarnauto** [comment]
Is it intended to support `fetchBalance` for binance futures natively? I get that it's possible to fetch the positions with implicit methods or to checkout the `info` property of the response. 

But I would expect it to be available in the form of the [Balance Structure](https://ccxt.readthedocs.io/en/latest/manual.html#balance-structure) from the docs where current positions are in the `"used"` property.  Is this expectation valid?

**Comment by kroitor** [comment]
@markoarnauto please, use `exchange.fetchPositions()` for that. Let us know if that does not help.

**Comment by frosty00** [comment]
you need to use 

```
new ccxt.binanceusdm ().fetchPositions ()
```
or
```
new ccxt.binancecoinm ().fetchPositions ()
```

**Comment by markoarnauto** [comment]
@kroitor @frosty00 thanks for your fast response. My questions whether this is intended to be unified is already discussed [here](https://github.com/ccxt/ccxt/issues/4834) 🙈

**Comment by kroitor** [comment]
@markoarnauto yes, we are working on unifying contract-trading positions, it's a work in progress.

**Comment by barresoft** [comment]
On CCXT 1.89.99/binance you can view your open positions with:

`pprint(exchange.fetch_positions(['SAND/BUSD']))`

This will show only the open positions for this pair
