### ISSUE TITLE
How can use margin trading in binance?

### ISSUE THREAD

**Issue by coincoin1** [ccxt/ccxt#6470]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Window 10
- Programming Language version: Python 3.7
- CCXT version: Last
- Exchange: Binance
- Method: Use fetch_balance, create_order in Binance Margin pair

I want to trade at margin but only spot.

Also, only spot trading orders can be created using create_order.

ex) binance.create_order('BNB/USDT, 'limit', 'sell', 0.5, 24.75)  <----- Spot trading

**Comment by kroitor** [comment]
Please, see these duplicate issues on margin trading with Binance for more info:

- https://github.com/ccxt/ccxt/search?q=binance+margin+trading&type=Issues
