### ISSUE TITLE
[ftx] fetch_order() for market order not containing price

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#6479]
- OS: - 
- Programming Language version: python 3.8 - probably js and python too
- CCXT version: 
- Exchange: FTX
- Method: fetch_order()

When running fetch-order for a market order, the ccxt response does not contain price (it's None).

ccxt debug output:
```
Response: GET https://ftx.com/api/orders/3109208514 200 
{'Date': 'Wed, 12 Feb 2020 19:03:07 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'Cache-Control': 'private, max-age=0, no-cache', 'account-id': '2102922', 'ETag': 'W/"bec9b7068fb2a1a17ab91680cb44411e"', 'Content-Encoding': 'gzip', 'CF-Cache-Status': 'BYPASS', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Alt-Svc': 'h3-24=":443"; ma=86400, h3-23=":443"; ma=86400', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '5640d220aed5f8cb-NRT'} 
{
    "result": {
        "avgFillPrice": 2666.0,
        "clientId": null,
        "createdAt": "2020-02-12T00:53:49.009726+00:00",
        "filledSize": 0.0007,
        "future": null,
        "id": 3109208514,
        "ioc": true,
        "market": "BNBBULL/USD",
        "postOnly": false,
        "price": null,
        "reduceOnly": false,
        "remainingSize": 0.0,
        "side": "buy",
        "size": 0.0007,
        "status": "closed",
        "type": "market"
    },
    "success": true
}
```

ccxt return value
``` json
{
    "info": {
        "avgFillPrice": 2666.0,
        "clientId": None,
        "createdAt": "2020-02-12T00: 53: 49.009726+00: 00",
        "filledSize": 0.0007,
        "future": None,
        "id": 3109208514,
        "ioc": True,
        "market": "BNBBULL/USD",
        "postOnly": False,
        "price": None,
        "reduceOnly": False,
        "remainingSize": 0.0,
        "side": "buy",
        "size": 0.0007,
        "status": "closed",
        "type": "market"
    },
    "id": "3109208514",
    "timestamp": 1581468829009,
    "datetime": "2020-02-12T00: 53: 49.009Z",
    "lastTradeTimestamp": None,
    "symbol": "BNBBULL/USD",
    "type": "market",
    "side": "buy",
    "price": None,
    "amount": 0.0007,
    "cost": 4.9e-07,
    "average": None,
    "filled": 0.0007,
    "remaining": 0.0,
    "status": "closed",
    "fee": None,
    "trades": None
}
```

While the exchange itself does not return a price in the price field for market orders, i think ccxt should use the `avgFillPrice` in that case - which is the correct price for a market order.

Alternatively, a calculation similar to the one for binance could/should be applied - using amount / cost. (see below for a problem with the cost calculation

https://github.com/ccxt/ccxt/blob/e9aafdd6e75c0bc9946ded8a563b1a4d3415a2c4/python/ccxt/binance.py#L933-L939

-------
### Broken cost calculation

In addition to the above - the calculation of `cost` is broken.

I assume this should be `filled * price` ... but it's `filled` * `amount` - which is definitely wrong. 

Relevant code snippet: 

https://github.com/ccxt/ccxt/blob/e9aafdd6e75c0bc9946ded8a563b1a4d3415a2c4/python/ccxt/ftx.py#L787-L788

**Comment by kroitor** [comment]
> i think ccxt should use the avgFillPrice in that case - which is the correct price for a market order.

I agree, however, in this case we can't fill in the exact `price` – we can only fill the `average` price of the order – would that help you resolve this issue?

> Alternatively, a calculation similar to the one for binance could/should be applied - using amount / cost.

We can't really use the `cost` to derive the price, since `cost` itself is derived from the filling price and the amount. And yes, you're right – the `cost` is currently wrong, because of the bug you've pointed out.

**Comment by kroitor** [comment]
@xmatthias hey! I've uploaded some fixes, let me know if this works for you. Thx again!

**Comment by xmatthias** [comment]
Hi @kroitor 
using average price is perfectly fine (binance / other exchanges will give you an average too for market orders, as there is no one price - so i think this aligns it to most other exchanges).

From purely looking at the code, i think the fixes you pushed will work (it now looks kinda the way i expected).

We'll test with this version and let you know if it isn't fixed (but i belive it is!).

Thanks for the quick response (as always)! much apreciated

**Comment by xmatthias** [comment]
Hi @kroitor,

while having fixed the problem for fetch_order() - there seems to be a problem with `create_order()` now.

```
File "/home/dante/.local/lib/python3.7/site-packages/ccxt/ftx.py", line 917, in create_order return self.parse_order(result, market) File "/home/dante/.local/lib/python3.7/site-packages/ccxt/ftx.py", line 811, in parse_order cost = filled * price TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

```

A quick look at the commit tells me that probably, the comparison of amount  !== undefined should point to price now (?) 

``` js
        if (filled !== undefined && amount !== undefined) {
            cost = filled * amount;	            cost = filled * price;
        }	       
```

should be: 
``` js
        if (filled !== undefined && price !== undefined) {
            cost = filled * amount;	            cost = filled * price;
        }	       
```

**Comment by kroitor** [comment]
@xmatthias pardon, missed it, will add the edit now.

**Comment by kroitor** [comment]
@xmatthias should be ok now in 1.22.45. Let me know if anything. Your help is much appreciated!
