### ISSUE TITLE
Python: BitMEX url encoding produces json objects with single quoted strings, which is not valid JSON

### ISSUE THREAD

**Issue by andersea** [ccxt/ccxt#648]
The BitMEX api expects the [filter parameter](https://www.bitmex.com/app/restAPI#Filtering) to a json object, however in the python implementation, if you supply a dict or and object to the filter parameter, like this:

```Python
    def get_position(self, symbol):
        """Returns any current positions for the given symbol."""
        args = {
            'filter': {
                "isOpen": True,
                "symbol": symbol
            },
            'columns': [
                'homeNotional',
                'foreignNotional',
                'markPrice'
            ]
        }
        return self.__api.private_get_position(args)
```

Then the sign method of the BitMEX class will use urllib.parse.urlencode to convert the dict to url, where all strings are single quoted.

```
https://testnet.bitmex.com/api/v1/position?columns=['homeNotional', 'foreignNotional', 'markPrice']&filter={'isOpen': True, 'symbol': 'XBTUSD'}
```

This is not valid JSON, so BitMEX api throws the following error:

```
ccxt.base.errors.ExchangeError, bitmex {"error":{"message":"Invalid value for argument 'filter' of type 'object'. Received type was string. Error: Unexpected token ' in JSON at position 1","name":"HTTPError"}}
```
Required info:
* Language: Python 3.5.2, ccxt 1.10.176
* Exchange: BitMEX, API: GET /position

**Comment by andersea** [comment]
It is possible to work around the issue by using `json.dumps()` like this:
```python
    def get_position(self, symbol):
        """Returns any current positions for the given symbol."""
        args = {
            'filter': json.dumps({
                "isOpen": True,
                "symbol": symbol
            }),
            'columns': 'homeNotional,foreignNotional,markPrice'
        }
        return self.__api.private_get_position(args)
```

**Comment by kroitor** [comment]
@andersea thx for the info, but... do you have a problem with a specific unified API method?

**Comment by andersea** [comment]
It just caught me off guard probably. I guess this api works ok, as long as you know what you are doing.

**Comment by kroitor** [comment]
@andersea ok, feel free to ask if you have any other difficulties or questions. Thx!
