### ISSUE TITLE
Upbit create_deposit_address Error

### ISSUE THREAD

**Issue by coincoin1** [ccxt/ccxt#6480]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version: Python 3.7
- CCXT version: 1.21.89
- Exchange: Upbit
- Method:

![image](https://user-images.githubusercontent.com/55371640/74404815-e3984e00-4e6e-11ea-88c5-ed4a8a8bdaca.png)

I want to get the Litecoin address, but there is an error.

The content of the error 
 ccxt.base.errors.ExchangeError: upbit {"error":{"message":"암호화폐 지갑정보를 찾지 못했습니다.","name":"coin_address_not_found"}}

please help me.

```
import ccxt

upbit = ccxt.upbit({
    'apiKey': 'My Upbit apiKey',
    'secret': 'My Upbit secret apiKey',
})

Deposit = upbit.create_deposit_address('LTC')  # Make Litecoin deposit address

print(Deposit)
```

**Comment by kroitor** [comment]
I suggest to move this discussion to this duplicate issue:

- https://github.com/ccxt/ccxt/issues/6452
