### ISSUE TITLE
Incorrect amount/size can be passed to exchange

### ISSUE THREAD

**Issue by andersalm** [ccxt/ccxt#6483]
Whenever I'm making a market buy order with amount/size 0.0006 BTC to FTX->BTC-PERP, the order on the exchange ends up being 0.0005.

After doing this dirty fix I have not yet managed to reproduce the issue.

```
            // 'size' => floatval ($this->amount_to_precision($symbol, $amount)),
            'size' => $amount,
```

So it seems to me there is an issue with amount_to_precision where the input amount and output amount does not match. 

https://github.com/ccxt/ccxt/blob/5f940b206f4a23e2755ac09a0b3ecc770560e0ab/php/ftx.php#L874

**Comment by kroitor** [comment]
@andersalm thank you for reporting! Will fix shortly!
