### ISSUE TITLE
[docs] exchange-specific documentation

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#6488]
While ccxt does a great job unifying most functions / settings, not everything is or can be unified.
I think it would be good to provide a separate wiki/documentation page which documents exchange-specific properties.

The behavior is there now and all is working well - but to find it users need to search through issues (which are not easy to navigate) to find certain exchange-specifics - and often will raise issues asking the same question again because re-discovering the already answered issue is difficult and does require the correct search-term.

I've tried to outline what i mean below ... but it is just a very small and quick example - i'm sure there is MUCH more knowledge hidden in issues - waiting for documentation.

-----

### Binance
To use binance futures endpoints, initialize  the Exchange as follows:

``` python
import ccxt
ct.binance({'defaultType': 'future'})
```

### FTX

To use FTX subaccounts, use the following parameter to initialize the exchange object

``` python
import ccxt
ftx = ccxt.ftx({
    'headers': {
        'FTX-SUBACCOUNT': 'YOUR_SUBACCOUNT_HERE',
    },
    # other settings...
})

# or later after instantiation:
exchange.headers = {
    'FTX-SUBACCOUNT': 'YOUR_SUBACCOUNT_HERE',
}
```
``` js
const exchange = new ccxt.ftx ({
    'headers': {
        'FTX-SUBACCOUNT': 'YOUR_SUBACCOUNT_HERE',
    },
    // other settings...
})

// or later after instantiation:

exchange.headers = {
    'FTX-SUBACCOUNT': 'YOUR_SUBACCOUNT_HERE',
}

// your calls here
```
(from #6038)

**Comment by Fradulentus** [comment]
Если настроить глубину проникновения запрашиваемых величин  на высшую степень качества выходящих из общего  потока движение кадров, присвоят всем изначально приследуемым единицам данных,характер метода элементарного перебора вариантов.Получить можно золото,даже невероятный в жизни шанс,получить можно многое,но только не знания.К истине всех вещей и к  природам вращающейхся сутей,каждый должен прийти сам.Придача боту  ощущений вызванных путем простого имитирования процесса добывания знаний,возможно пагубно отразиться на самой структуре цифровой личности в пределах достигнутого существования
(Возможно текст требует стилистических вправок,если возникли  трудности с переводом)

**Comment by LimitedInfo** [comment]
Hello, I'm new to github, what would be the steps to contribute to this issue? Also is there a discord or forum where we can discuss our projects that use ccxt?

**Comment by kroitor** [comment]
@LimitedInfo hi!

> what would be the steps to contribute to this issue?

Thanks for your involvement! First of, i'd recommend to start with this doc: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

Let us know if you have further questions or difficulties after that – we will reply as soon as we can.

> Also is there a discord or forum where we can discuss our projects that use ccxt?

You're welcome: 

[![Discord](https://img.shields.io/discord/690203284119617602?logo=discord&logoColor=white)](https://discord.gg/dhzSKYU)

**Comment by Fradulentus** [comment]
Привет Andrew,русский язык поддается твоему пониманию?Какой переводчик используешь, для общения с иноко язычными людьми?Чем увлекаешься в жизни?Что тебя не устраивает в мире?И что ты хочешь поменять в смыслах существований?Я располагаю мощными инструментами, которые позволяют достичь нам  практических всех целей,если конечно верить что Windows это прежде двери.Жду ответа,с уважением Microsoft.
Windows 9

От: Andrew Marotta<mailto:notifications@github.com>
Отправлено: 11 мая 2020 г. в 21:35
Кому: ccxt/ccxt<mailto:ccxt@noreply.github.com>
Копия: Fradulentus<mailto:Fradulentus@outlook.com>; Comment<mailto:comment@noreply.github.com>
Тема: Re: [ccxt/ccxt] [docs] exchange-specific documentation (#6488)


Hello, I'm new to github, what would be the steps to contribute to this issue? Also is there a discord or forum where we can discuss our projects that use ccxt?

**Comment by ttodua** [comment]
Side-note: specifically related to FTX subaccounts, you can now [directly set subaccount](https://github.com/ccxt/ccxt/issues/6985#issuecomment-989127719) in method params, no requirement to set that initialization.
