### ISSUE TITLE
Livecoin fetch_balance() bug

### ISSUE THREAD

**Issue by dexter369** [ccxt/ccxt#649]
https://github.com/ccxt/ccxt/blob/master/php/livecoin.php

Line 96 : 
for ($b = 0; $b < count ($this->currencies); $b++) {

Should be : 
for ($b = 0; $b < count ($balances); $b++) {

Otherwise it misses balances of some currencies.

**Comment by kroitor** [comment]
This is fixed in 1.10.192. Thx for reporting!
