### ISSUE TITLE
FTX - fetch_ohlcv pagination not working

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#6490]
- OS: linux
- Programming Language version: python (any, really)
- CCXT version: latest
- Exchange: FTX
- Method: fetch_ohlcv

running `fetch_ohlcv()` for FTX with "since" to get some historic data is not working as expected.

Based on testing (and a quick comment from the FTX developer here: https://github.com/freqtrade/freqtrade/issues/2916#issuecomment-586262654) the behavior is as follows

end_time is optional - but defaults to `now()` if not set.
start_time is optional - but only to limit results (as an alternative to `limit=`).

With this - using something like the below will not work correctly and will always return the latest 20 candles.

``` python
import ccxt
from datetime import datetime, timedelta
ct = ccxt.ftx()
_ = ct.load_markets()
since = datetime.utcnow() - timedelta(days=100)
since_ms = int(since.timestamp()) * 1000
res = ct.fetch_ohlcv('BTC/USD', '5m', since=since_ms, limit=20)
print(res)

## What would work but is very clumsy
params = {'end_time': (since_ms + 10000000) // 1000}
ohlcv = ct.fetch_ohlcv(pair, '15m', since=since_ms, limit=20, params=params)
```

I've also included the workaround above ... but i think it's very clumsy and i would hope that ccxt can simplify this (similar to the poloniex approach, maybe - which looks to be a similar approach than what i'd hope for here)

https://github.com/ccxt/ccxt/blob/9a45a75626f1480761043df804af6045377ca4c3/python/ccxt/poloniex.py#L230-L249

Ps: i hope it's ok if my examples  and deep-ref links are python ... i know the implementation needs to be in JS - but i'm more at home in python than in js ...

**Comment by kroitor** [comment]
@xmatthias i've uploaded a fix for it, so it will work as expected as of 1.22.55. Please, reach out to me at igor@ccxt.trade or igor.kroitor@gmail.com when you have the time – we have some related things to discuss.

**Comment by xmatthias** [comment]
Thanks a lot! :+1: 
will test but looks good!

**Comment by wiljohnston** [comment]
I'm having the same issue now – has this bug re-emerged?

**Comment by jmoz** [comment]
Here's some code to fetch all candles by fixing the start and end time params https://gist.github.com/jmoz/567163be72712cdf6d4913a40ebd6256

`fetch_candles` is a simple proxy method so just use the regular library `fetch_ohlcv`
