### ISSUE TITLE
Crashes on Bitmex overload?

### ISSUE THREAD

**Issue by geeklingo** [ccxt/ccxt#6491]
- OS: Centos 7
- Programming Language version: Python
- CCXT version: 1.22.52
- Exchange: BitMEX
- Method: order create or ammend

Are there any working examples with Python on handling the typical BitMEX overload scenario which happens more often than not?

`Unexpected error occurred with Last Hope: bitmex {"error":{"message":"The system is currently overloaded. Please try again later.","name":"HTTPError"}}`

**Comment by kroitor** [comment]
> Are there any working examples with Python on handling the typical BitMEX overload scenario which happens more often than not?

Just use the native Python exception handling as described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

```Python
exchange = ccxt.bitmex({
    'enableRateLimit': True,
})

done = False

while not done:
    try:
        exchange.create_order(...)
        done = True
    except ccxt.BaseError as e:
        print(e)
        pass
```

Let us know if the above does not answer the question.
