### ISSUE TITLE
empty binance deposit history

### ISSUE THREAD

**Issue by NansSimpson** [ccxt/ccxt#6495]
Hi there,
I'm trying to fetch my binance deposit hitsory with "deposits = binance.fetch_deposits()" but I only get : [].
Withdrawal history works perfectly though. 
I definitely have a deposit history when I go directly to Binance.com site.
Thanks for your help.

**Comment by npomfret** [comment]
When I run it using my account I only get one deposit (I have lots more).  Have you checked the docs? Many exchanges limit the history that your can get access to via the API.  It's very annoying.

**Comment by NansSimpson** [comment]
Thank you for your reply.
Maybe they only let us access the most recent deposits. It is annoying!
Thanks again!

**Comment by kroitor** [comment]
@NansSimpson can you plz post your verbose request/response? Add `.verbose = true` before fetching the deposits and paste your output here.

@npomfret 

> When I run it using my account I only get one deposit (I have lots more).

This is weird, I'm getting more deposits in my history, but only the deposits from the past 3 months.

**Comment by NansSimpson** [comment]
![image](https://user-images.githubusercontent.com/24104411/74662152-a4813a00-5199-11ea-93d2-849aa8a8a7de.png)

this my verbose response to this code line : `deposits = binance.fetch_deposits()`

**Comment by kroitor** [comment]
@NansSimpson yep, in your case Binance returns an empty list as you can see from the verbose output. Now, what if you add the `since` argument to that call?

```Python
code = None  # currency code is optional
# put some date within 3 months of your actual deposits here ↓
since = binance.parse8601 ('2019-01-01T00:00:00Z')
binance.verbose = True
deposits = binance.fetch_deposits(code, since)
```

↑ Do you have the same empty response with date-based pagination as shown above?

**Comment by NansSimpson** [comment]
So, I think you got the answer.
I don't have any deposits within the last 3 months, they were from before. (I'm trying to get my whole history)
But when I put a date before 3 months : 
```
since = binance.parse8601('2019-10-01T00:00:00Z')
binance.verbose = True
deposits = binance.fetch_deposits(code=None, since=since)
```
I got this verbose response: 
![image](https://user-images.githubusercontent.com/24104411/74663171-93d1c380-519b-11ea-9512-48144cb02403.png)

**Comment by kroitor** [comment]
@NansSimpson ok... apparently, Binance requires both the `startTime` which you can specify via `since` argument or via `params` overrides. And it also requires `endTime` which can be specified via `params` as well, and it has to be within 3 months of `startTime`. Unfortunately, this is not fully documented in Binance's API docs. But I think this is actually the case.

Just to make sure that our thinking is correct: 

```Python
since = binance.parse8601('2019-10-01T00:00:00Z')
binance.verbose = True
params = {
    'endTime': binance.parse8601('2019-12-01T00:00:00Z')
}
deposits = binance.fetch_deposits(code=None, since=since, limit=None, params=params)
```

or

```Python
binance.verbose = True
params = {
    'startTime': binance.parse8601('2019-10-01T00:00:00Z')
    'endTime': binance.parse8601('2019-12-01T00:00:00Z')
}
deposits = binance.fetch_deposits(code=None, since=since, limit=None, params=params)
```

↑ Does any of the above snippets produce a meaningful result?

**Comment by npomfret** [comment]
Do we know if these rules apply to withdrawals as well as deposits?

**Comment by kroitor** [comment]
> Do we know if these rules apply to withdrawals as well as deposits?

We are not 100% sure, but from my experience with the other exchanges, the date-based pagination works the same for deposits and withdrawals.

**Comment by kroitor** [comment]
@npomfret after some testing on my side I can confirm that it works the same with withdrawals as well.

@NansSimpson , @npomfret I've uploaded a fix to it, so, if you specify `since` it will put the endTime within 3 months (90 days actually) from the startTime automatically. Thus, if you upgrade to the version 1.22.63 (it will arrive in 15 minutes) – the date-based pagination will work for Binance deposits and withdrawals as documented in the CCXT manual:

- https://github.com/ccxt/ccxt/wiki/Manual#date-based-pagination

```Python
import ccxt
print(ccxt.__version__)
exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
})
since = exchange.parse8601('2019-01-1T00:00:00Z')  # any date now
print(exchange.fetch_deposits(code=None, since=since)
```

Let me know if that does not help.

**Comment by npomfret** [comment]
... with one caveat.  If you have a 91 day gap in your data you will see no data being returned in the subsequent api call.  In _nornal_ pagination this indicates that there is no more data to be returned. But in the case of binance that is not necessarily the case.

**Comment by kroitor** [comment]
@npomfret unfortunately – yes, the user has to paginate quarter by quarter or monthly, over the entire time range of interest. This is very hard to workaround with the underlying API limitations. Hope for your understanding – we can't guess the user's history individually and Binance's API does not help in that at all.

**Comment by kroitor** [comment]
We will look into adding a human-friendly exception warning to make sure that the user is aware of the possible "gap" problem.

**Comment by NansSimpson** [comment]
Okay at least we have a solution! Thanks for helping me!
My aim is to store this deposit history in a database, so the user will only have to do this whole process of quarter by quarter once.

**Comment by kroitor** [comment]
@NansSimpson thx for reporting! Let us know if anything!

**Comment by ulrickpsp** [comment]
I can't retrieve data older than 3 months despite iterating. Is there any change that only allows to retrieve transactions within the last 3 months?

**Comment by ashwinikatur** [comment]
> I can't retrieve data older than 3 months despite iterating. Is there any change that only allows to retrieve transactions within the last 3 months?

I can retrieve it either. Has anything changed?

**Comment by kroitor** [comment]
> I can't retrieve data older than 3 months despite iterating. Is there any change that only allows to retrieve transactions within the last 3 months?

> I can retrieve it either. Has anything changed?

@ulrickpsp  @ashwinikatur , please, read these guidelines and follow very carefully, we need your code, your library versions, and your verbose mode output (enable verbose mode) :

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
