### ISSUE TITLE
does okex v3 don't support 'Futures Account of a Currency'

### ISSUE THREAD

**Issue by stocktest** [ccxt/ccxt#6497]
refercence :
  https://www.okex.com/docs/en/#futures-singleness

![image](https://user-images.githubusercontent.com/22346851/74696329-22911f80-5232-11ea-893f-46af55deb8c7.png)

 I use  exchange.futures_get_accounts({'underlying': 'LTC-USDT'}), but it still returns all currency

- OS: windows 10
- Programming Language version: python
- CCXT version: 1.22.63
- Exchange: okex v3
- Method: futures_get_accounts

**Comment by kroitor** [comment]
> I use exchange.futures_get_accounts({'underlying': 'LTC-USDT'}), but it still returns all currency

Please read the Manual on Implicit API methods carefully and the FAQ:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

You are using this call:

- https://github.com/ccxt/ccxt/blob/master/js/okex3.js#L142

... while the proper call is this one:

- https://github.com/ccxt/ccxt/blob/master/js/okex3.js#L143

So your code should be:

```Python
exchange.futures_get_accounts_currency({'currency': 'LTC-USDT'})
```

Let us know if the above does not answer the question.

**Comment by codemonkeyno1** [comment]
@kroitor your line of code gives the error:
AttributeError: 'okex' object has no attribute 'futures_get_accounts_currency'

**Comment by kroitor** [comment]
@codemonkeyno1 what's your version of CCXT?

**Comment by codemonkeyno1** [comment]
The latest version.  Just did an git upgrade with the same results.  On Python 3

**Comment by kroitor** [comment]
@codemonkeyno1 it was renamed to `futures_get_accounts / futures_get_accounts_underlying`, you can find a list of all methods as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

```Python
exchange.futures_get_accounts({'currency':'USDT'})
exchange.futures_get_accounts_underlying({'underlying':'LTC-USDT'})
```

Let me know if that does not work for you.
