### ISSUE TITLE
fetchOpenOrdersV1 returns and exchange error when no sybmol.

### ISSUE THREAD

**Issue by lostless13** [ccxt/ccxt#6498]
- OS: Windows
- Programming Language version: JS - node 10.15.3
- CCXT version: 1.22.61
- Exchange: Huobipro
- Method: fetchOpenOrdersV1

It appears that Huobi now requires a symbol be provided for this endpoint and does not return all open orders:
```
ExchangeError: huobipro {"status":"error","err-code":"require-symbol","err-msg":"Parameter `symbol` is required.","data":null}
```

To reproduce call fetchOpenOrdersV1 method with no parameters.
```
let data = await ccxt.fetchOpenOrdersV1()
```
Expected result:
Throws error - ExchangeError: huobipro {"status":"error","err-code":"require-symbol","err-msg":"Parameter `symbol` is required.","data":null}

**Comment by lostless13** [comment]
Note I also tried passing in "*" (to represent all symbols in the huobi websocket api) as the symbol parameter using the fetch2 method to bypass the symbol check but it failed signature verification.

**Comment by kroitor** [comment]
Thx for reporting!
