### ISSUE TITLE
how to make a stoploss in binance?

### ISSUE THREAD

**Issue by doongzzi** [ccxt/ccxt#6499]
how can i make a stoplimit order in both futures and spot?
first i fetch orderId and call 
binance.fapiPrivate_post_order({type:"STOP_MARKET/TAKE_PROFIT_MARKET" }) 
is it right?? but don't i need orderId to match quantity for the exact order?
and what about the spot trade stoplimit?

thanks

**Comment by lookis** [comment]
there is no stop market order in spot, only in futures.
and stop order doesn't stop some particular order, so you don't need any orderid to "stop"
just build the parameters with stop price and quantity in "params" manually, stop order isn't an unified order type in ccxt

**Comment by doongzzi** [comment]
thanks..stupid me

**Comment by kroitor** [comment]
@doongzzi we will look into unifying this aspect soon, let us know if you have further difficulties. Feel free to reopen this issue or just ask questions if any. Closing this for now, if you don't mind,
