### ISSUE TITLE
query position question

### ISSUE THREAD

**Issue by xgdgsc** [ccxt/ccxt#650]
Is there a unified API for querying position by symbol? Or do I have to use `private_get_position`?

**Comment by kroitor** [comment]
Hi! Currently, margin / leveraged / position trading is not unified, but the work on this has been started, more on that here: https://github.com/ccxt/ccxt/search?q=position+margin+trading. Does this answer your question?

**Comment by xgdgsc** [comment]
OK. Thanks.
