### ISSUE TITLE
Binance some implicit Future API mothods returns base error when requested correctly

### ISSUE THREAD

**Issue by 0xkardux** [ccxt/ccxt#6501]
- OS: Windows 
- Programming Language version: Python 3.8.1
- CCXT version: 1.22.64
- Exchange: Binance
- Method: fapiPrivateDeleteAllOpenOrders, fapiPrivatePostMarginType

When i tried above methods, it returns base error even though all things going correct, like this.
```
import ccxt
binance = ccxt.binance{
             'apiKey': api_key,
             'secret': api_secret,
             'enableRateLimit': False,
             })
param = {'symbol': 'BTCUSDT'}
binance.fapiPrivateDeleteAllOpenOrders(param)
```
returns 

> binance {"code": 200,"msg": "The operation of cancel all open order is done."}

 as a base error message, and
```
param = {'symbol': 'BTCUSDT,
        'marginType': 'ISOLATED',
        }
binance.fapiPrivatePostMarginType(param)

```
also returns

> binance {"code": 200,"msg": "success"}

 as a base error message.

Is there any way to fix this problem? It makes me hard to manage error.

**Comment by kroitor** [comment]
Please update to version 1.22.65 in 15 minutes and let us know if you still have the same problem. Thx!

**Comment by 0xkardux** [comment]
Fixed! THANK YOU!!!!!
