### ISSUE TITLE
Close all positions and orders

### ISSUE THREAD

**Issue by geeklingo** [ccxt/ccxt#6502]
- OS: CentOS
- Programming Language version: Python
- CCXT version: 1.22.57
- Exchange: BitMEX
- Method: close

I am looking for examples of a quick way to close all open orders and positions for a symbol. I'm currently using the get orders function and using a for order in orders loop to close any order but am stuck on position close. I found https://github.com/ccxt/ccxt/issues/3850 but can't get the example to work correctly. Are there any other more recent examples of this in action?

This is my current code to close positions (doesn't work)
```
    _filter = {'symbol': 'ethusd', 'isOpen': True}
    closedpostions = client.private_post_order_closeposition({filter: client.json(_filter)})
```

**Comment by kroitor** [comment]
Hi!

Please, see the examples here:

- https://github.com/ccxt/ccxt/issues/6399#issuecomment-577304202
- https://github.com/ccxt/ccxt/issues/2096
- https://github.com/ccxt/ccxt/issues/4302#issuecomment-445540690

Let us know if the above does not help, or if you have any remaining questions afterwards.
