### ISSUE TITLE
binance and bitmex cancel order use origClientOrderId 

### ISSUE THREAD

**Issue by Mr-six** [ccxt/ccxt#6507]
- OS: ubuntu 16.04
- Programming Language version: Python3.8
- CCXT version: 1.20.39
- Exchange: binance, bitmex
- Method: cancel_order

`orderId` not mandatory for cancel order from Binance and bitmex.
Binance spot: https://binance-docs.github.io/apidocs/spot/en/#cancel-order-trade
Binance futures: https://binance-docs.github.io/apidocs/futures/en/#cancel-order-trade

bitmex: https://www.bitmex.com/api/explorer/#!/Order/Order_cancel

So how I can use origClientOrderId instead orderId in cancel_order method?

**Comment by kroitor** [comment]
> So how I can use origClientOrderId instead orderId in cancel_order method?

We are going to unify this aspect very soon. Until then, please, update to CCXT version 1.22.74+ (the new build will arrive in 15 minutes), this should work:

```Python
# binance
exchange.cancel_order(None, symbol, { 'origClientOrderId': YOUR_VALUE_HERE })
```

```Python
# bitmex
exchange.cancel_order(None, symbol, { 'clOrdID': YOUR_VALUE_HERE })
```

Let us know if that helps or not.

**Comment by Mr-six** [comment]
> > So how I can use origClientOrderId instead orderId in cancel_order method?
> 
> We are going to unify this aspect very soon. Until then, please, update to CCXT version 1.22.74+ (the new build will arrive in 15 minutes), this should work:
> 
> ```python
> # binance
> exchange.cancel_order(None, symbol, {'origClientOrderId': YOUR_VALUE_HERE})
> ```
> 
> ```python
> # bitmex
> exchange.cancel_order(None, None, {'clOrdID': YOUR_VALUE_HERE})
> ```
> 
> Let us know if that helps or not.

Thx!

**Comment by danieltorscho** [comment]
> > ```python
> > # binance
> > exchange.cancel_order(None, symbol, {'origClientOrderId': YOUR_VALUE_HERE})
> > ```
> >

So is this same for `javascript` ?

**Comment by danieltorscho** [comment]
I'm stil having issue in javascript:

```javascript
await exchange.cancelOrder(null, orderPending.info.symbol, {
    'origClientOrderId': orderPending.id
})
```

it doesn't work, bails out with an error: `{"code":-2011,"msg":"Unknown order sent."}`
