### ISSUE TITLE
Assigning generic Exception to specific exception types causes linting errors

### ISSUE THREAD

**Issue by chpmrc** [ccxt/ccxt#6511]
**UPDATE**: at runtime exceptions are still correctly defined according to the hierarchy but statically the `= Exception` assignment causes linting issues.

Hello, not sure how it happened but at some point between 1.19 and 1.22 ccxt's exceptions in https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/errors.py stopped extending the base class (via the factory) and were all flattened to the [generic `Exception` class](https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/errors.py#L42).

This way one is unable to programmatically understand what the reason behind the exception is and trying to catch any of those will raise linting errors such as Pylint's "Catching too general exception Exception (broad-except)".

If this was intentional would you mind explaining the rationale behind it? Thank you and have a good day!

**Comment by kroitor** [comment]
Can you please provide a complete snippet of code to reproduce it?

Here's an example that demonstrates error types:

```Python
# -*- coding: utf-8 -*-

import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.bitfinex()
try:
    exchange.fetch_balance()
except ccxt.AuthenticationError as e:
    print(isinstance(e, ccxt.ExchangeError))
    print(isinstance(e, ccxt.BaseError))
    print(e)
```

Output:

```
mbp:python igorkroitor$ python3
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> # -*- coding: utf-8 -*-
...
>>> import ccxt
>>> print('CCXT Version:', ccxt.__version__)
CCXT Version: 1.22.75
>>> exchange = ccxt.bitfinex()
>>> try:
...     exchange.fetch_balance()
... except ccxt.AuthenticationError as e:
...     print(isinstance(e, ccxt.ExchangeError))
...     print(isinstance(e, ccxt.BaseError))
...     print(e)
...
True
True
requires `apiKey`
>>>
```

↑ This shows that error types are correctly derived from the hierarchy. Do you have different results with the same version?

**Comment by chpmrc** [comment]
Right! I believe dynamically those exceptions are recreated using the proper hierarchy but statically the linter doesn't know that. I trusted Pylint's output without verifying at runtime:

![image](https://user-images.githubusercontent.com/1369747/74935102-59ad2f80-53f0-11ea-8a9c-e2c5093ed9fd.png)

Snippet I used:
```python
import ccxt

try:
    pass
except ccxt.AuthenticationError:
    pass
```

**Comment by kroitor** [comment]
>  I trusted Pylint's output without verifying at runtime:

We will address the linting aspect soon. In the meantime, I believe, this issue is resolved and there is a programmatic way of detecting the error type, right?

**Comment by chpmrc** [comment]
Yes, I'll make the title more clear but feel free to close the issue. Thank you!

**Comment by kroitor** [comment]
@chpmrc let's keep it open until we resolve the intellisense issue. Hope to get to it ASAP.
