### ISSUE TITLE
FTX sub accounts sign

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#6513]
- CCXT version: Latest
- Exchange: FTX
- Method: sign()

When I try to trade from sub account I got error:
`Can only use this key for for subaccount subaccount_name`

https://docs.ftx.com/#authentication

So in this case we need to send optional header `FTX-SUBACCOUNT`
Can you help to integrate it in the right way?

**Comment by kroitor** [comment]
Hi! )

Let me know if this does not help:

- https://github.com/ccxt/ccxt/issues/6038#issuecomment-546129700
- https://github.com/ccxt/ccxt/issues/6488#issue-565370810

**Comment by kroitor** [comment]
Closing this for now, feel free to reopen it or just ask further questions if any )

**Comment by zinwayz** [comment]
#8186

**Comment by mactone** [comment]
Not working. Code is as follow
```

import ccxt
# from variable id
exchange_id = 'ftx'
exchange_class = getattr(ccxt, exchange_id)
exchange.headers={
    'FTX-SUBACCOUNT':'**SUB ACCOUNT NAME**'
}
exchange = exchange_class({
    'apiKey': '**My API KEY**',
    'secret': '**MY SECRET KEY**',
   })

exchange.fetchDeposits()
```

Returns
`PermissionDenied: ftx {"success":false,"error":"Only have permissions for subaccount **SUB ACCOUNT NAME**"}`

**Comment by kroitor** [comment]
@mactone you have an error in your code, you must set the headers after or during the initialization, but not before...

This will work:

```Python

import ccxt
from pprint import pprint

exchange_id = 'ftx'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
    'apiKey': '**My API KEY**',
    'secret': '**MY SECRET KEY**',
    'headers': {
        'FTX-SUBACCOUNT': '**SUB ACCOUNT NAME**'
    }
})

deposits = exchange.fetch_deposits()
pprint(deposits)
```

**Comment by mactone** [comment]
It's working. Great appreciated.

**Comment by Peter416** [comment]
I am trying to do the same for Digifinex subaccounts but it isn't working. I'm also a little confused on what is meant by "SUB ACCOUNT NAME". Is that the name of the trading pair? i.e. "BTCUSDT"? 
Any guidance is appreciated
