### ISSUE TITLE
Calculating Lot Size on Bitmex

### ISSUE THREAD

**Issue by geeklingo** [ccxt/ccxt#6520]
- OS: CentOS
- Programming Language version: Python 3.8
- CCXT version: 1.22.52
- Exchange: BitMEX
- Method: amount_to_lots

I am trying to work out how I can calculate the max number of contracts to buy on BitMEX given free balance. Working on previous examples for Binance here (e.g. [716](https://github.com/ccxt/ccxt/issues/716)) I came up with:

```
       balance = client.fetch_balance()
        freeBalance = balance['BTC']['free']
        max_contracts = client.amount_to_lots(symbol, freeBalance)

```

But it doesn't like amount_to_lots? How can I work this out? Below is the error i get:
```
error occurred 'bitmex' object has no attribute 'amount_to_lots'
Traceback (most recent call last):
  File "/Users/gl/PycharmProjects/LearningtoMex/bitmex.py", line 446, in CreateOrder
    max_contracts = client.amount_to_lots(symbol, freeBalance)
AttributeError: 'bitmex' object has no attribute 'amount_to_lots'

```

**Comment by geeklingo** [comment]
Anyone able to help please?

**Comment by kroitor** [comment]
@geeklingo the amount_to_lots methods is not supposed to be used for calculating the lot sizes, it's for rounding purposes mostly. The lot_size for BitMEX is always 1.

> how I can calculate the max number of contracts to buy on BitMEX given free balance

What you want to do is:

1. take the contract size for the contract in question
2. take your balance in the same currency
3. divide your balance by the contract size – you will get the number of contracts you can buy

Do you have an issue with performing that calculation?

**Comment by kroitor** [comment]
@geeklingo check out the contract size here: https://www.bitmex.com/app/contract/XBTUSD – for BTC it is equal to 1 USD. So you can buy as many contracts as many USD you have.

**Comment by geeklingo** [comment]
> Do you have an issue with performing that calculation?

I wasn’t sure how to factor in leverage

**Comment by kroitor** [comment]
@geeklingo leverage is not directly related to the size of the contract though. In general, it depends on how much margin you want to put in your position.

Let me know if these docs don't help:

- https://www.bitmex.com/app/seriesGuide/XBT
- https://www.bitmex.com/app/perpetualContractsGuide

**Comment by kroitor** [comment]
@geeklingo feel free to reopen this or just ask further questions, if any.
