### ISSUE TITLE
[cex.io] cancel order response bug

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6522]
A successful `cancelOrder` on cex results in `NullResponse: cex returned undefined`.  But looking at the verbose output, it actually returns `true`.

```
handleRestResponse:
 cex POST https://cex.io/api/cancel_order/ 200 OK 
Response:
 { 'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '56aa739e59ee344a-LHR',
  Connection: 'keep-alive',
  'Content-Type': 'text/json',
  Date: 'Tue, 25 Feb 2020 14:43:27 GMT',
  'Expect-Ct':
   'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Set-Cookie':
   '__cfduid=foo; expires=Thu, 26-Mar-20 14:43:27 GMT; path=/; domain=.cex.io; HttpOnly; SameSite=Lax; Secure',
  'Transfer-Encoding': 'chunked',
  Vary: 'Accept-Encoding',
  'X-Frame-Options': 'DENY' } 
 true 
```

**Comment by npomfret** [comment]
From my debugger I can see that in `handleErrors (code, reason, url, method, headers, body, response, requestHeaders, requestBody) {...` the `response` param is `undefined`, and the `body` param is `true`.

**Comment by kroitor** [comment]
Thx for reporting! Fixed in 1.22.97 (15 minutes to build on Travis).

**Comment by npomfret** [comment]
You fix stuff faster than I can make a branch!

**Comment by kroitor** [comment]
@npomfret well, it was an easy fix, https://github.com/ccxt/ccxt/commit/e5938108289dc617c9b05a3416f7fb12b5370afc
you can do them very quickly if you click the edit pencil on github on `cex.js` – that will create a branch and will submit a PR with your edits to that file automatically )
