### ISSUE TITLE
kucoin private api

### ISSUE THREAD

**Issue by davidinsuomi** [ccxt/ccxt#6523]
the kucoin developer said /api/v1/accounts/inner-transfer is deprecated，they change to  /api/v2/accounts/inner-transfer
reference
[https://docs.kucoin.com/#inner-transfer](url)

So now the inner-transfer endpoint is v2 while the rest of the API is still at v1.  I could not use the private for the inner-transfer in ccxt as I could not able to define the version path
` 'post': [
                        'accounts',
                        'accounts/inner-transfer',
                        'deposit-addresses',
                        'withdrawals',
                        'orders',
                        'bullet-private',
                    ],`

Is there any workaround for that?

**Comment by kroitor** [comment]
Hi! Thx for reporting!

Despite that there is a way to use KuCoin's v2 endpoints, we've added better support for configuring those versions in CCXT 1.22.98 (it will arrive in 15 minutes after the build).

> Is there any workaround for that?

-------

Before CCXT 1.22.98:

```JavaScript
exchange.options['version'] = 'v2' // set version exchange-wide for this one call
const params = { /* your params here */ }
await exchange.privatePostAccountsInnerTransfer (params)
exchange.options['version'] = 'v1' // set it back after the call

```

or

```JavaScript
const params = {
    'version': 'v2', // passing the version in params for this call
    /* your params here */
}
await exchange.privatePostAccountsInnerTransfer (params)
// no need to switch it back
```

-------

After CCXT 1.22.98+:

All of the above still works, and, also, this has been added:

```JavaScript
exchange.options['versions']['POST']['accounts/inner-transfer'] = 'v2'
// ...
await exchange.privatePostAccountsInnerTransfer (params)
```

Let us know if that does not help.
