### ISSUE TITLE
[liquid] fetchOrders not returning any results

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6524]
Is anyone else seeing problems with Liquid `fetchOrders`?  I'm not getting any data back.

**Comment by frankhubrepo** [comment]
I'm getting: [Exchange Error] okex {"code":0, (and a bunch of other data) in my website where i fetch crypto prices from various exchanges. I removed  'okex' from the exchanges list and everything is ok now. Seems like some of their services are down or something

**Comment by kroitor** [comment]
@frankhubrepo you might want to move to `okex3` (v3) instead of `okex`, since v1 is deprecated.

**Comment by kroitor** [comment]
@npomfret not getting the data even after placing a new order?

**Comment by npomfret** [comment]
Not tried a new order yet.  The website seems to show my full history and it appears to the use API.

**Comment by frankhubrepo** [comment]
@kroitor Thank you. That did it.

**Comment by kroitor** [comment]
@npomfret we would be very thankful if you post a followup from them here, thx!

**Comment by kroitor** [comment]
@npomfret do you still have this issue?

**Comment by ttodua** [comment]
I've tested myself and it's working fine.
Also, there have not been any follow-ups above, even though of @kroitor asked, so closing the issue.
