### ISSUE TITLE
Deribit - fetch_balance() only BTC of main account - no subaccounts or ETH

### ISSUE THREAD

**Issue by tesaho** [ccxt/ccxt#6533]
Hello,

The output of deribit.fetch_balance() seems to only display the BTC balance of the main account.  It does not include any ETH balance of the main account and does not include any sub-account balances.  Is there a way to get all balances (main account, sub-accounts and all currencies)?

- OS: Ubuntu 18.04
- Programming Language version: Python 3.7
- CCXT version: 1.22.37
- Exchange: Deribit testnet
- Method: fetch_balance()

Main balance:  5.9922 BTC 3.0 ETH
Sub account balance:  3.9150 BTC

dbit.fetch_balance()
Request: GET https://test.deribit.com/api/v1/private/account {'x-deribit-sig': 'REMOVED=', 'Accept-Encoding': 'gzip, deflate'} None
Response: GET https://test.deribit.com/api/v1/private/account 200 {'Server': 'nginx/1.17.5', 'Date': 'Thu, 27 Feb 2020 19:25:47 GMT', 'Content-Type': 'application/json', 'Content-Length': '311', 'Connection': 'keep-alive', 'content-encoding': 'gzip', 'Strict-Transport-Security': 'max-age=15768000', 'X-Frame-Options': 'SAMEORIGIN'} {"usOut":1582831547810915,"usIn":1582831547810420,"usDiff":495,"testnet":true,"success":true,"result":{"equity":5.992152948,"maintenanceMargin":0.0,"initialMargin":0.0,"availableFunds":5.99215294,"balance":5.99215294,"marginBalance":5.99215294,"SUPL":0.0,"SRPL":0.0,"PNL":0.0,"optionsPNL":0.0,"optionsSUPL":0.0,"optionsSRPL":0.0,"optionsD":0.0,"optionsG":0.0,"optionsV":0.0,"optionsTh":0.0,"futuresPNL":0.0,"futuresSUPL":0.0,"futuresSRPL":0.0,"deltaTotal":0.0,"sessionFunding":0.00007711,"depositAddress":"REMOVED","currency":"BTC"},"message":""}
{'info': {'usOut': 1582831547810915, 'usIn': 1582831547810420, 'usDiff': 495, 'testnet': True, 'success': True, 'result': {'equity': 5.992152948, 'maintenanceMargin': 0.0, 'initialMargin': 0.0, 'availableFunds': 5.99215294, 'balance': 5.99215294, 'marginBalance': 5.99215294, 'SUPL': 0.0, 'SRPL': 0.0, 'PNL': 0.0, 'optionsPNL': 0.0, 'optionsSUPL': 0.0, 'optionsSRPL': 0.0, 'optionsD': 0.0, 'optionsG': 0.0, 'optionsV': 0.0, 'optionsTh': 0.0, 'futuresPNL': 0.0, 'futuresSUPL': 0.0, 'futuresSRPL': 0.0, 'deltaTotal': 0.0, 'sessionFunding': 7.711e-05, 'depositAddress': 'REMOVED', 'currency': 'BTC'}, 'message': ''}, 'BTC': {'free': 5.99215294, 'used': 0.0, 'total': 5.992152948}, 'free': {'BTC': 5.99215294}, 'used': {'BTC': 0.0}, 'total': {'BTC': 5.992152948}}

**Comment by kroitor** [comment]
> Is there a way to get all balances (main account, sub-accounts and all currencies)?

Unfortunately, Deribit API does not allow to fetch them all at once. They will only allow fetching single accounts by currency ids. And the default currency is BTC. If you want to override it, you can do that as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

```Python
deribit = ccxt.deribit({'enableRateLimit': True})
deribit.load_markets()
# ...
params = {'currency': deribit.currencies['ETH']['id']}
print(deribit.fetch_balance(params))
# ...
params = {'currency': deribit.currencies['ETH']['id'], 'ext' True}
print(deribit.fetch_balance(params))
# ...
params = {'currency': deribit.currencies['USD']['id']}
print(deribit.fetch_balance(params))
```

Hope that answers the question. Let us know if not.

**Comment by kroitor** [comment]
P.S. All of the above is related to Deribit's v1 API, which was superseded by the v2 API. The support for Deribit's API v2 in CCXT is in the works atm:

- https://github.com/ccxt/ccxt/search?q=deribit&type=Issues
- https://github.com/ccxt/ccxt/issues/4833
- https://github.com/ccxt/ccxt/pull/5546

**Comment by tesaho** [comment]
I was just about to ask about v2 support since v2 has private/get_subaccounts.  Unfortunately, the solutions you mentioned worked only for the main account.  Is there a way for me to write my own get_subaccounts function using exchange.fetch2 command? I tried the following and failed.

dbit.fetch2("get_subaccounts?with_portfolio=true", api="private", method="GET")

Request: GET https://test.deribit.com/api/v2/private/get_subaccounts?with_portfolio=true 
{'x-deribit-sig': 'REMOVED.1582833572897.F4o8/Q0dwKB70tiWU0VdS9n0tVGqQAN7TbliT2PYCBI=', 'Accept-Encoding': 'gzip, deflate'} None
Response: GET https://test.deribit.com/api/v2/private/get_subaccounts?with_portfolio=true 401 {'Server': 'nginx/1.17.5', 'Date': 'Thu, 27 Feb 2020 19:59:33 GMT', 'Content-Type': 'application/json', 'Content-Length': '141', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS', 'Access-Control-Allow-Headers': 'Authorization,User-Agent,Range,X-Requested-With,Content-Type,Partner'} {"jsonrpc":"2.0","error":{"message":"unauthorized","code":13009},"testnet":true,"usIn":1582833573629929,"usOut":1582833573629989,"usDiff":60}
Traceback (most recent call last):
  File "/home/tesa/anaconda3/envs/fund-notebooks-dev/lib/python3.7/site-packages/ccxt/base/exchange.py", line 553, in fetch
    response.raise_for_status()
  File "/home/tesa/anaconda3/envs/fund-notebooks-dev/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://test.deribit.com/api/v2/private/get_subaccounts?with_portfolio=true
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/tesa/anaconda3/envs/fund-notebooks-dev/lib/python3.7/site-packages/ccxt/base/exchange.py", line 459, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/tesa/anaconda3/envs/fund-notebooks-dev/lib/python3.7/site-packages/ccxt/base/exchange.py", line 565, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/tesa/anaconda3/envs/fund-notebooks-dev/lib/python3.7/site-packages/ccxt/deribit.py", line 718, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: deribit {"jsonrpc":"2.0","error":{"message":"unauthorized","code":13009},"testnet":true,"usIn":1582833573629929,"usOut":1582833573629989,"usDiff":60}

**Comment by kroitor** [comment]
@tesaho you can help

>  Is there a way for me to write my own get_subaccounts function using exchange.fetch2 command? I tried the following and failed.
> `dbit.fetch2("get_subaccounts?with_portfolio=true", api="private", method="GET")`

The `fetch2` method has nothing to do with Deribit v2 API or versions at all. It won't work this way.

Instead, you can try to download this PR for Deribit v2 and help us test it / add the missing endpoints to it – it should work if you build it on your side: https://github.com/ccxt/ccxt/pull/5546

We will be happy if you report back in #5546.

**Comment by tesaho** [comment]
I will do my best to break and hopefully fix things. Thanks!
