### ISSUE TITLE
New exchange: AAX

### ISSUE THREAD

**Issue by JacobustcZhi** [ccxt/ccxt#6534]
AAX API Doc：
https://www.aax.com/apidoc/index.html#introduction

AAX Exchange includes spot and futures API。

Spot API： https://www.aax.com/apidoc/index.html#rest-authenticated-endpoints-spot-trading
Futures API： https://www.aax.com/apidoc/index.html#rest-authenticated-endpoints-futures-trading

**Comment by kroitor** [comment]
The AAX exchange API is available in CCXT 1.41.53+!
