### ISSUE TITLE
binance fapi fundingRate

### ISSUE THREAD

**Issue by mingrui** [ccxt/ccxt#6535]
- OS: ubuntu 16.04
- Programming Language version: Python3.8
- CCXT version: 1.20.39
- Exchange: binance
- Method: getFundingRate

Hi, is it possible to add `fundingRate` to binance `fapiPublic`?
Thank you!

**Comment by kroitor** [comment]
Hi! Added in CCXT 1.23.8 (the new build will arrive in 15 minutes). Thx for reporting!

**Comment by mingrui** [comment]
I think there is a misunderstanding, I meant the funding rate history api:
https://binance-docs.github.io/apidocs/futures/en/#get-funding-rate-history-market_data

like this:
![image](https://user-images.githubusercontent.com/699276/75516411-5f7dc300-5a37-11ea-8fa2-906b6d94debf.png)

**Comment by mingrui** [comment]
but `openOrder` is needed too, so 😄

**Comment by kroitor** [comment]
@mingrui yep, missed to commit fundingRate as well, thx for your attention.

**Comment by thisisloze** [comment]
How does one use this? I cant use it?

**Comment by kroitor** [comment]
@thisisloze answered here: https://github.com/ccxt/ccxt/issues/8028#issuecomment-773422589
