### ISSUE TITLE
"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."

### ISSUE THREAD

**Issue by delaji-san** [ccxt/ccxt#6537]
- OS: Rasbian Buster
- Programming Language version: PHP  7.3.14-1~deb10u1
- CCXT version: 1.23.8
- Exchange: binance
- Method: fetch_balance()

First off thank you for this library it's a beast and a time saver. Kudos!

Yes I have seen this before and doing a time sync fixes the issue but not this time. Tried as per previous posts:
```
'adjustForTimeDifference' => true,
'recvWindow' => 50000,
```
and still nada.

Verbose shows time lookup seems correct from binance:
```
    [0] => GET
    [1] => https://api.binance.com/api/v3/time
    [2] => 200
    [3] =>
    [4] => Array
        (
            [content-type] => Array
                (
                    [0] => application/json;charset=utf-8
                )

            [date] => Array
                (
                    [0] => Fri, 28 Feb 2020 07:22:02 GMT
                )
```
However the get request uses some strange timestamp which I'm assuming produces the error:
```
Request:
Array
(
    [0] => GET
    [1] => https://api.binance.com/api/v3/account?timestamp=2326558065&recvWindow=50000&signature=SSSHHHH
    [2] => Array
        (
            [0] => X-MBX-APIKEY: SUPERSECRET
        )

    [3] =>
)
```

**2326558065** is 09/22/2043 @ 6:07pm (UTC) that's out by quite a bit. 

Ok finally rolled back to my previous version of CCXT from 03/2019 and it works without issues so definitely something wrong with the library and not the environment.

**Comment by kroitor** [comment]
Hi! This was answered here:

- https://github.com/ccxt/ccxt/issues/5978 (I suggest to move this discussion here)
- https://github.com/ccxt/ccxt/issues/4413#issuecomment-450838709

Let us know if that does not help resolve this.
