### ISSUE TITLE
[Liquid] missing currencies of function 'fetch_balance' 

### ISSUE THREAD

**Issue by JosephWN** [ccxt/ccxt#6540]
- OS: Ubuntu 18.04
- Programming Language version: Python 3.7
- CCXT version: 1.23.1
- Exchange: Liquid
- Method: fetch_balance

When I call function 'fetch_balance', I can only get currency information of BCH, BTC, ETH, JPY, QASH, SGD, USD, XRP. But there are more currencies available in Liquid, such as AUD (Australian Dollar).

Could you please fix this problem?

Thanks!

**Comment by kroitor** [comment]
Hi!

What does this snippet say?

```Python
liquid = ccxt.liquid({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
print(liquid.private_get_fiat_accounts())
```

?

**Comment by JosephWN** [comment]
> Hi!
> 
> What does this snippet say?
> 
> ```python
> import ccxt
> exchange = ccxt.liquid({
>     'apiKey': 'YOUR_API_KEY',
>     'secret': 'YOUR_SECRET',
> })
> print(exchange.private_get_fiat_accounts())
> ```
> 
> ?

Thanks for your quick response, but I just tried private_get_fiat_accounts(), the response only contain JPY, SGD, USD. But AUD is still missing.

**Comment by kroitor** [comment]
@JosephWN 

> Thanks for your quick response, but I just tried private_get_fiat_accounts(), the response only contain JPY, SGD, USD. But AUD is still missing, AUD is available in Liquid.

That call returns the info from the exchange first-hand (not from CCXT), so what you see is what you get from Liquid itself. If you don't see AUD there and you are sure that it absolutely should be there (you have done everything that is required by Liquid for the AUD to be there) – then you should probably forward this question to Liquid tech support.

Have you added you SWIFT details on the Liquid website for the AUD?

**Comment by JosephWN** [comment]
> @JosephWN
> 
> > Thanks for your quick response, but I just tried private_get_fiat_accounts(), the response only contain JPY, SGD, USD. But AUD is still missing, AUD is available in Liquid.
> 
> That call returns the info from the exchange first-hand (not from CCXT), so what you see is what you get from Liquid itself. If you don't see AUD there and you are sure that it absolutely should be there (you have done everything that is required by Liquid for the AUD to be there) – then you should probably forward this question to Liquid tech support.
> 
> Have you added you SWIFT details on the Liquid website for the AUD?

I will contact Liquid support team about this question, thx!

**Comment by kroitor** [comment]
@JosephWN it will be great if you follow up here whether you have a solution to it or not. Thx for the feedback!

**Comment by ttodua** [comment]
I've tested myself and our unified fetchBalance returns response correctly. 
For future readers - if you have any issue with specific currency, at first note, that if you have zero balance in that currency, it might not show up in response. Additionally with `liquid` exchange, you can also try such method in addition to the above snippet:
```
print( exchange.private_get_accounts_currency_reserved_balance_details ({currency:'AUD'}) )
```
