### ISSUE TITLE
CCXT Pro Released!

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#6543]
Ladies and gentlemen,

Today we are proud to announce the release of CCXT Pro. 

[![ccxt-pro-banner-black](https://user-images.githubusercontent.com/1294454/75621967-18650e80-5bac-11ea-9340-55746cab1e31.png)](https://ccxt.pro)

We are certain that it will be useful to any and every high frequency trader, and to all parties and services that need WebSockets for real-time updates.

A lot of work over months has gone into what is now the release version of the product. We will continue to develop both CCXT and CCXT Pro in the coming future adding more exchanges and unifying WebSocket methods.

With CCXT Pro you can utilize WebSockets like a pro. Visit https://ccxt.pro to be part of the future of cryptocurrency exchange trading.

[![ccxt-pro-exchanges-and-methods](https://user-images.githubusercontent.com/1294454/76688028-331e9500-663a-11ea-812a-d879ce058b17.png)](https://ccxt.pro)

**Comment by zsyh** [comment]
It continiously removes my access and reinvites me.

**Comment by kroitor** [comment]
@zsyh yep, i'm watching it, and it's resolved now, it will invite you one more time. Pardon for the inconvenience and thank you for using CCXT Pro! Let me know if anything.

**Comment by binares** [comment]
Is there a table that shows which exchanges each plan contains?

**Comment by kroitor** [comment]
@binares it's up to you to decide which exchanges you want to use, since it's a formal requirement, because the CCXT Pro does not have any intermediary code for tracking – it's direct communication between you and the exchange – and you can access the source code repository with all exchanges in it. Therefore this is not technical, but more like formal.

**Comment by binares** [comment]
What exactly does the "number of exchanges" displayed below each plan represent then?

**Comment by kroitor** [comment]
@binares _"how many exchanges at once a user is expected to use under this plan, though not enforced technically"_

**Comment by lookis** [comment]
@kroitor I think it's cool to have a free account with no exchange/fake exchange (may be with rest api backend?) would be helpful for integrating the new api, after that paid account with full exchanges could be used in production directly.

**Comment by kroitor** [comment]
@lookis this is a great idea, it was also mentioned here: https://github.com/ccxt/ccxt/issues/6506. And we are going to focus on that soon. Also, we have plans on resolving the integrations backlog in CCXT and add a lot more to CCXT Pro very soon )

**Comment by 1key** [comment]
I've just installed and and would like to compliment you.
Nice work! Exciting times to come!
Just hoping you'll have a lot of paying customers to keep supporting this project.

**Comment by kroitor** [comment]
@1key thank you so much! We're excited as well! ) Don't hesitate if anything!

**Comment by athenawisdoms** [comment]
Will there be credit card payment option? It will certainly help with recurring monthly payments.

**Comment by kroitor** [comment]
@athenawisdoms it is somewhat more complicated to process fiat across legislations globally, but we are looking into all possible options.

**Comment by RomainBlindy** [comment]
> @binares _"how many exchanges at once a user is expected to use simultaneously under this plan, though not enforced technically"_

Sorry I still can't understand. 
If it's not enforced technically, how can you block an user from using more than the number of exchanges he is able to use ?
Also, when you say 1 seat for the first plan for example, it's one IP at once ?

**Comment by RomainBlindy** [comment]
@kroitor are the -20% included in the prices displayed ?

**Comment by kroitor** [comment]
> If it's not enforced technically, how can you block an user from using more than the number of exchanges he is able to use ?

We cannot, and we never wanted to block anyone. CCXT is not an intermediary system, it does not decide who passes and who not. Any user can install it after getting a license and can use CCXT Pro software on the user side to talk to the exchanges directly, with no intermediaries. So we are not a part of the connection. Therefore we will not block anyone. 

Again, this is more like a formal limitation – obviously we cannot track you down and this is not the intent of the licensing. The philosophy of this open-source commercial model is not to hunt down individuals, but to deal in fair way with bigger corporate clients. If you use more exchanges than you're expected to use – you should punish yourself, say, stay away from fair trading for a week ) 

We believe that you can be reasonably fair to us and can still appreciate the open-source nature of CCXT Pro ) Also we are well aware that there is more than one poor guy who would rather die than pay in all such cases – so, darksiders will always be there, and we are aware of that. We believe you're on our side, though. That would be great )

> @kroitor are the -20% included in the prices displayed ?

If you're signed in you can click on `[ + month ]` and `[- month ] in the cart to see how 20% is recalculated everytime you click. And it is output in the total in the cart. The pricing you see as a guest is without all discounts (the actual price with discounts will be lower).

**Comment by binares** [comment]
Obviously you must have thought about it, but I have to ask about the security: how do you prevent malicious commits to your private ccxt.pro repo? As each member becomes a collaborator, and thus has the push access.

**Comment by alex-lucid** [comment]
Can we have a comparison table of plans?

**Comment by kroitor** [comment]
@binares try to push – [you will see](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) )

**Comment by kroitor** [comment]
@alex-lucid it is basically outlined on the [pricing](https://ccxt.pro/pricing), or do I misunderstand your question?

**Comment by binares** [comment]
> @binares try to push – [you will see](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) )

Well, this message soothes my nerves:
```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "Travis CI - Pull Request" is expected. Waiting on code owner review from kroitor.
```
Nor will I be able to merge pull requests, or create a new branch and switch it with the master?

**Comment by kroitor** [comment]
> Nor will I be able to merge pull requests, or create a new branch and switch it with the master?

Nothing should pass without a review. And, yes, we also have watchdog robots who never sleep. This is in fact done in the best interest of the end-user, there's another side to this story. You see, otherwise we would have to make the license more costly to compensate for GitHub subscription (per user per month), which is obviously not what we want and not what the users want, it's the opposite – we tried to make it affordable and comparable to software "subscription prices" in general.

**Comment by alex-lucid** [comment]
> @alex-lucid it is basically outlined on the [pricing](https://ccxt.pro/pricing) page, or do I misunderstand your question?

I may ask wrong:) what is swag then? If I want to use library in my mobile application, that can handle almost any number of supported exchanges, which option I should choose?

**Comment by kroitor** [comment]
If you're going to sell your mobile application – your users are responsible for obtaining their individual licenses for using CCXT Pro. Your license works as long as you are developing the app. The license allows you to use, copy and modify it, but forbids you from redistributing it (this is subject to separate conditions).

**Comment by cod3gen** [comment]
Congratulation on the release, @kroitor and the rest of the team :-)

**Comment by delaji-san** [comment]
Not gonna lie that's a bit of a steep price point. ~10 USD 1 seat 1 exchange for the poor people here? I think you would hit gold with this one. Make it no tech support at that level and I'm sold.

**Comment by kroitor** [comment]
@delaji-san we can't promise that we'll add it, but we will consider a plan close to what you suggested, thanks for the feedback!

**Comment by delaji-san** [comment]
Glad to hear you got it launched though. Kudos on the whole project to you and the team!

**Comment by AadaEa** [comment]
I would like to have clarifications on the words redistributing/reselling, are we talking about CCXT Pro itself, or the software developed using CCXT Pro, or both?
For instance, if I make an hosted commercial trading interface that allows users to execute trades or automated trades thanks to their API keys, and that interface needs 3 servers to work decently (3 IP addresses), with potentially separated databases but synced code (or copy pasted source files), does that means redistributing? Such users wouldn't have any access to CCXT Pro directly, they would just use an UI that is using CCXT Pro.
Would I need to purchase monthly 1 licence per server? 1 licence per user? 1 licence per platform/project I've made using CCXT Pro?

Thank you and congrats for the work of everyone involved, really liking this premium version of CCXT, which I'm sure will allow updates and exchange/broker integration to be continuously implemented basically forever, for a well deserved financial incentive, while the base version also keeps improving over time.

**Comment by kroitor** [comment]
> I would like to have clarifications on the words redistributing/reselling, are we talking about CCXT Pro itself, or the software developed using CCXT Pro, or both?

The CCXT Pro itself.

> For instance, if I make an hosted commercial trading interface that allows users to execute trades or automated trades thanks to their API keys, and that interface needs 3 servers to work decently (3 IP addresses), with potentially separated databases but synced code (or copy pasted source files), does that means redistributing?

If your users can somehow see or access the source code of CCXT Pro from you or from your resources – that is redistributing. If you are hiding it completely behind your walls – that is not redistributing the source code of CCXT Pro. Which is what the license protects.

> Such users wouldn't have any access to CCXT Pro directly, they would just use an UI that is using CCXT Pro.

We have to be precise with words here – if they don't access CCXT Pro **source code** from your resources and they would just use an UI that is not exposing the CCXT Pro source code to the user – it's not redistributing.

> Would I need to purchase monthly 1 licence per server? 1 licence per user? 1 licence per platform/project I've made using CCXT Pro?

You will need 1 license per project.

Thanks for using our software! )

**Comment by lostless13** [comment]
What do you define as a seat in your license model?

**Comment by kroitor** [comment]
@lostless13 the number of GitHub users on your team or company who can also get access to the repository using their own GitHub accounts, you add them to your plan.

**Comment by lfern** [comment]
@kroitor I don't know if this is the right place to make this question, but I would like to know about binance websockets. I need to listen to all symbols of binance in the same machine, and add new markets in this listen process when it come from binance (invoking load markets periodically). I see how to listen to one symbol in ccxt.pro simple example:
```` javascript
'use strict';

const ccxtpro = require ('ccxt.pro');

(async () => {

    const exchange = new ccxtpro.binance ({ enableRateLimit: true })
    while (true) {
        const orderbook = await exchange.watchOrderBook ('ETH/BTC')
        console.log (new Date (), orderbook['asks'][0], orderbook['bids'][0])
    }

}) ()
```
But can I implement my multi-symbol listen process this way (creating a new connection to binance websockets per symbol) or can I listen to multiple symbols in the same watchOrderBook method (so I can reuse same connection to get a small set of symbols)? 
(Don't know if Binance would accept so many websocket connections from a single IP)

**Comment by kroitor** [comment]
@lfern in the example above the same connection is reused, even if you watch for multiple symbols in parallel – they will all boil down to a single connection. Binance has limitations on the number of subscriptions, but i guess you're not going to reach anywhere close to it. The answer to your question is – if the exchange allows reusing the connection – CCXT Pro will reuse it. 

We know that Binance docs say that each new connection requires a new URL, but in fact it's not the case – the WS client manages a single connection in CCXT and handles all subscriptions on that same connection. I hope that Binance will not ban you for one connection from one IP )

**Comment by teneon** [comment]
Hi Kroitor ;) Congrats on the release! I will be signing up for the pro version in the next few days. And I am also interested in more details regarding Ifern's question. Can you add example in the docs how to listen to multiple symbols or even all pairs on e.g. USDT or BNB base? As far as i know in their official websocket lib for JS, it is also possible to provide array of symbols upon connection. Instead of replying here, perhaps just add an example or two into the docs and post a link here! Thanks ;)

**Comment by kroitor** [comment]
@teneon thank you! ) Sure, we will add the examples on how to listen to multiple symbols in parallel.

**Comment by firepol** [comment]
Hi @kroitor first of all congrats on this,

little feedback about ccxt.pro support page, the link to slack (I wanted to ask a few questions in chat), once clicked, shows me this error:

> Already accepted
> It looks like someone else has already accepted this invitation.
> Note: Currently, channels can only be shared between two organizations. Learn more

How dos it work when one clicks "sign up"? I see that I have to authorize @kroitor to get access to my code etc. is it possible to have a few more details, maybe in the FAQ page? Would be nice to see some screenshots or a video showing the sign up process. E.g. one can choose the exchanges he wants, e.g. if choosing professional, he can choose 5, or the code will limit access to 5 at the same time, so it's possible during one session to use 5 exchanges, then stop the session and test 5 different exchanges?

Thanks for clarifying and fixing the slack link, cheers

**Comment by kroitor** [comment]
Hey, @firepol!

Thank you!

> the link to slack (I wanted to ask a few questions in chat), once clicked, shows me this error:
> Already accepted
> It looks like someone else has already accepted this invitation.
> Note: Currently, channels can only be shared between two organizations. Learn more

Will get this resolved shortly, thx for the notice.

> How dos it work when one clicks "sign up"? I see that I have to authorize @kroitor to get access to my code etc. is it possible to have a few more details, maybe in the FAQ page? 

Basically, it's the GitHub OAuth, when you click "Sign Up" it redirects you to GitHub and you're asked if you agree to share some of your data with me. And that same page shows which particular data will be shared. And there you can see that we don't ask anything else, but your email. So it's asking if you agree to share your personal data with us, just your email only. If you agree – it then redirects you to the CCXT Pro website, and you're signed in from there. This costs nothing to you, at all. We ask for the user email to notify the corresponding users about successful payments and expiring licenses, nothing more. We do not send out hot news and other spam, just the rare, but still important notifications about your account.

> Would be nice to see some screenshots or a video showing the sign up process. 

Will make one asap, thank you!

> E.g. one can choose the exchanges he wants, 

We don't ask you to specify the exchanges. You should simply decide for yourself which exchanges from the full list of available exchanges you want, and just use those, still having all other exchanges available to you. In the CCXT Pro code there is no built-in technical limitation on the number of exchanges, and the limit on the number of exchanges is formal. Nothing stops you from switching one exchange for another anytime, and you don't have to do anything for that but change the used exchange ids in your code on your side, without telling us.

> e.g. if choosing professional, he can choose 5, 

Yep.

> or the code will limit access to 5 at the same time, 

Nope, the code won't limit you technically, since you are still talking to the exchanges directly.

> so it's possible during one session to use 5 exchanges, then stop the session and test 5 different exchanges?

Yep – that's exactly what _"using CCXT Pro"_ means formally and legally.

Going to resolve the slack link issue, taking it down for a little while.

**Comment by kroitor** [comment]
To @firepol all users who want a bit more details on the License, we have this summary

---

> ```diff
> - It is illegal to publish, distribute or sell the CCXT Pro source code without a separate permission from us.
> - Violation of the licensing terms will trigger a ban followed by a legal pursuit.
> ```
>
> The CCXT Pro is hosted in a private repository on GitHub. The access to the repository is licensed and granted by invitation only on a paid basis. In order to access the repository, the users must obtain prepaid subscription plans at https://ccxt.pro. The users pay for the continued access to the repository, including updates, support and maintenance (new exchanges, improvements, bugfixes and so on).
>
> CCXT Pro does not enforce technical restrictions that would affect the efficiency of direct communications between the users and the exchanges. The protection is not technical but legal. We do not impose unnecessary limitations or intermediary code. If your CCXT Pro license expires, your software or system will not break down and will keep working fine with your most recent version by that time. However, if you discontinue your paid license you will lose the updates that will follow.
>
> Any licensed user, developer, team, or company, having obtained paid access to the CCXT repository from us, can use CCXT Pro as a dependency, subject to the terms and limitations of the CCXT Pro paid subscription plans.
>
> Licensees can use, copy, and modify CCXT Pro as long as they<br />**DO NOT VENDOR, PUBLISH, SELL OR REDISTRIBUTE THE SOURCE CODE OF CCXT PRO**.
>
> It is allowed to specify CCXT Pro as a dependency of your software as long as you<br />**DO NOT INCLUDE A COPY OF THE CCXT PRO SOURCE CODE IN YOUR SOFTWARE**.
>
> If you are a software developer you should specify CCXT Pro as your requirement. The end-user of your software is responsible for obtaining his own individual CCXT Pro license. The best practice is to make it clear in your docs or on your website. Since CCXT and CCXT Pro are interchangeable, auto-detection can be factored-in to let the end-user choose between the free CCXT and the paid CCXT Pro.
>
> Thank you for using CCXT Pro legally!

**Comment by firepol** [comment]
Thanks for the answers, @kroitor another couple of questions.

Did I understand correctly, that the source code granted by the beginner license is the same as the professional one, without any technical limitation? Meaning you rely on people honesty to use the ccxt pro?

Another question, the price I see now in the website (eg 55 usdt for the professional license or 35 for the beginner license) is including already the 20% discount before April, or if I get a license now I'll get the discount at the checkout page?

Thank you and cheers

**Comment by kroitor** [comment]
> Did I understand correctly, that the source code granted by the beginner license is the same as the professional one, without any technical limitation? 

In short, yes, but it's a bit more complicated than that. For example, you can't apply for a redistribution license without a corporate plan.

> Meaning you rely on people honesty to use the ccxt pro?

Some people can afford having legal risks, but most of bigger trading companies cannot, because the license costs significantly less than the possible expenses and losses.

> Another question, the price I see now in the website (eg 55 usdt for the professional license or 35 for the beginner license) is including already the 20% discount before April, or if I get a license now I'll get the discount at the checkout page?

This was already answered in this thread ) When you're a guest – you see the prices without a discount. When you sign in, the discount will be applied and you will see that immediately in your cart even before the checkout. Signing in and clicking the buttons to see what will happen – is free. You can also switch your chosen plan to another one, etc. )

**Comment by teneon** [comment]
Hi @kroitor ,
i can see that beginner licence price is 1.53 ETH. What is the price really based on? E.g. on March 1st lowest price for 1 ETH was 191.19 EUR, but on March 2nd highest price for 1 ETH 210.29. That makes quite a huge difference when you convert prices to FIAT. What happens, if price for one ETH goes up to 300, 400, 500, 1000 or even more? I think you should base prices on FIAT and then daily adjust price in ETH and other cryptos ?? Because this price swinging in crypto can really kill the payment model. What do u think?
Kind regards!

**Comment by kroitor** [comment]
@teneon all prices you see there are fixed in USD, and the crypto prices are constantly recalculated based on their actual rates to USD. So what you ask is already there. )

**Comment by teneon** [comment]
Thank you for your answers! ;)
I am planning to signup now. One more question, for us "early birds" 20% discount applies. Since we are "early birds" will the discount apply after a year as well, if we continue with our subscription?

**Comment by kroitor** [comment]
> will the discount apply after a year as well, if we continue with our subscription?

Nope, the early bird discount only applies to orders made before April. So you can buy 1 month now and it will be a -20% discount. When you buy the next month in April, that discount won't be relevant anymore. On the other hand, you can preorder 12 months into the future in March and all of those months will come at a -20% discount (if you take them before April), and, also, you will have 2 free months on top of that.

**Comment by teneon** [comment]
Hi @kroitor ,
i've signed up for CCXT pro earlier and testing it now :P I am using Typescript. How can i install types for ccxt pro? I know they do exist for the original ccxt... but i am not sure about ccxt pro? Are types not ready yet? Do u plan to add them?

npm install @types/ccxt.pro
404  '@types/ccxt.pro@latest' is not in the npm registry.

Kind regards!

**Comment by kroitor** [comment]
@teneon at this time there is no TypeScript mapping yet, we are really investigating into moving the entire codebase to TypeScript as the main source language for all other languages, including JavaScript itself, Python, PHP. But at this time JS is the source for the transpiler to make the code in other languages. More about the migration to TypeScript here:

- https://github.com/ccxt/ccxt/pull/6510

The migration to TypeScript will allow us to move on to supporting compiled typed languages like C++, Java and so on, which is really cool. This is something we hope to get done as soon as possible. In the meantime CCXT Pro is JS, Py and PHP. We will most likely add the hardcoded TypeScript mappings in CCXT Pro similar to the ones in CCXT along the way, until we have fully migrated. Will let you know, of course.

**Comment by teneon** [comment]
> We will most likely add the hardcoded TypeScript mappings in CCXT Pro similar to the ones in CCXT along the way

That would be excellent and since apart from the standard CCXT properties, the CCXT Pro instance includes just some additional properties, hopefully that shouldn't be too much work for you to complete? I think all typescript users will be greatful ;) Where should i watch for the announcement in that #6510 topic or will u write it here?

**Comment by kroitor** [comment]
@teneon i'll post everywhere to make sure you know ) Yes, we will add TS mappings for Pro and this should not be too hard.

**Comment by teneon** [comment]
@kroitor Thank you so much, can u give me an ETA for this?

**Comment by kroitor** [comment]
@teneon i'll do my best to add that this week. Unknown unknowns often pop up immediately after the launch, so let's not consider that a hard deadline, because I don't like failing on deadlines, this isn't a promise, but more like one of the goals. It may require a bit more time or a bit less time, depending on how we do.

**Comment by zsyh** [comment]
How to submit ccxt.pro's issue? I can't find it at ccxt.pro's repository.

**Comment by shakks** [comment]
hi @kroitor , congrats on the launch to you and your team.

I had a few questions regarding the CCXT Pro.

-If I am using CCXT, how much more rework do I need to upgrade to CCXT Pro. I was wishing there was a $10 plan with one exchange to test the code before upgrading and am thinking of CCXT as an alternative.

-I had problem before with Binance Websocket were for some reason, the data used to go missing in between and candle value thru use to be incorrect and I had to fall back to RestAPI. Is there any method to make sure that the WebSocket thru CCXT Pro avoids or overcomes this issue.

-What kind of data will be streaming through the Websockets OHLC candle values, real-time price or order book data? 
When I am plotting a candle chart should I depend on RestAPI for the candle data and Websocket for the real-time? or will I be able to get both complete candle and in-progress candle through the WebSockets?

-I am planning to use the app for a customer-facing app think (Blockfolio), so is there any way CCXT Pro effect the data uptime.

**Comment by frosty00** [comment]
@zsyh 

> How to submit **ccxt.pro**'s issue? I can't find it at **ccxt.pro**'s repository. Should I submit it at **ccxt**'s repository? Thank you!

please submit it to this repository - https://github.com/ccxt/ccxt/labels/ccxt.pro

**Comment by frosty00** [comment]
@shakks 

> -If I am using CCXT, how much more rework do I need to upgrade to CCXT Pro. I was wishing there was a $10 plan with one exchange to test the code before upgrading and am thinking of CCXT as an alternative.

They are very similar. Instead of writing `await binance.fetchOrderBook (symbol)` you would write `await binance.watchOrderBook (symbol)` and the returned data structure is the same.

> -What kind of data will be streaming through the Websockets OHLC candle values, real-time price or order book data?

Please read the [docs](https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual#public-methods)

> -I am planning to use the app for a customer-facing app think (Blockfolio), so is there any way CCXT Pro effect the data uptime.

Yes, if the exchange is not connectable for some reason (think maintenance) then the client will not be able to connect directly to them

**Comment by icytrader** [comment]
Thanks for your efforts! I have subscribed ccxt pro on the first day of release and much looking to use it in my project.  However I see that Huobi and Okex do not have pro version yet.  They are consistenly in top 3 globally in both spot and derivaitives trading volume（https://ftx.com/volume-monitor）. Would be great to implement these two popular exchanges in pro.

**Comment by kroitor** [comment]
@icytrader thank you for using CCXT Pro and for sharing! ) We will add Huobi and OKEX soon, stay tuned for more updates ;) We are also working on FTX as well ) The plan is to release several new integrations every month.

**Comment by kroitor** [comment]
@icytrader we have added Huobi Global (`huobipro`) to CCXT Pro. It includes the unified public API, the private methods will soon become available as well.

**Comment by fredfortier** [comment]
@kroitor What's the process of applying for access to the repo? I want to add some exchanges.

**Comment by kroitor** [comment]
@fredfortier the access to the repository and to the source code comes together with the license and can be obtained at http://ccxt.pro.

**Comment by LFoglietti** [comment]
Hi,
 I am building a commercial web based app which will allow my clients to automate their trade.
Only 3 Exchanges will be connected. ( 3 exchanges).
Only 1 developer will get access to the repository using his own GitHub (1 Seat) .
My clients just use an UI. They will not get acces to CCXT Pro source code (not redistributing).

1) Can I do the above with a Beginner license?
when you say:

> 


> @alex-lucid
> 
> If you're going to sell your mobile application – your users are responsible for obtaining their individual licenses for using CCXT Pro with your application. Your license works as long as you are developing the app. The license allows you to use, copy and modify CCXT Pro, but forbids you from redistributing or reselling CCXT Pro (redistribution or vendoring is subject to separate conditions).


2) you are referring to a mobile application which gives acces to CCXT Pro code. this is the reason why final user will have to pay for a licence. Is that correct?

**Comment by kroitor** [comment]
> Only 3 Exchanges will be connected. ( 3 exchanges).
> Only 1 developer will get access to the repository using his own GitHub (1 Seat) .
> My clients just use an UI. They will not get acces to CCXT Pro source code (not redistributing).
> Can I do the above with a Beginner license?

It depends on how your app works, it could be:
a. client → UI → app logic → your backend server → CCXT → exchanges
b. client → UI → app logic → CCXT Pro → exchanges

In case (a), the CCXT Pro is hidden behind your server backend and you are not redistributing it inside your client app. That is not redistribution and you can do that with the Beginner plan.

In case (b), the CCXT Pro or parts of it are included into your APP, and if the users can use it from your app – that is redistributing CCXT Pro. In that case the user has to obtain a license first, if the developer does not have a right to redistribute CCXT Pro. In many cases the mobile app stores are made such that makes it very easy to decompile and access the source code. So, a lot depends on whether your users can access or somehow see the CCXT Pro or parts of its source code in your app (say, after disassembling it). 

> > you are referring to a mobile application which gives acces to CCXT Pro code. this is the reason why final user will have to pay for a licence. Is that correct?

Yes, CCXT Pro is a paid addon to the freeware CCXT. So, in most cases there's a choice of either using the free MIT version of CCXT or the paid commercial version of CCXT Pro.

**Comment by kroitor** [comment]
Good news @teneon! ) We've added the initial TS declarations to CCXT Pro, thanks for your patience! We will be working further on them, so your feedback is welcome )

**Comment by lookis** [comment]
Hi @kroitor , what's the best practice for ccxtpro, should I use fetchXXX with origin ccxt and watchXXX with pro, or both fetchXXX and watchXXX with pro?

**Comment by kroitor** [comment]
Hi @lookis ! CCXT Pro is a superset (a wrapper) over CCXT, so it also has inside it everything that CCXT has. So, if you have pro – you can use `fetch` and `watch` from pro.

**Comment by kroitor** [comment]
Hey guys, just to let you all know – we have added OKEX and OKCoin to CCXT Pro: https://github.com/ccxt/ccxt/issues/6638 ) All feedback is welcome! )

**Comment by lookis** [comment]
> Hey guys, just to let you all know – we have added OKEX and OKCoin to CCXT Pro: #6638 ) All feedback is welcome! )

are you considering add margin trade of binance? It's nearly the same with spot trade. 

currently, I am hacking ccxt/pro like this to use margin trade:

```python
binance = ccxtpro.binance({
    "urls": {"api": {"private": "https://api.binance.com/sapi/v1/margin"}}
})

if conf['margin_trade']:
    binance.publicPostUserDataStream = binance.sapiPostUserDataStream
```
It's totally ok with unified api, only a small difference in non unified api

at least, I have already test ```fetch/watch_ohlcv``` ```fetch/watch_orders``` ```create_order``` ```cancel_order``` ```fetch/watch_balance```

**Comment by kroitor** [comment]
Hi @lookis! Yep, we are about to unify it all, check this issue: https://github.com/ccxt/ccxt/issues/6376, hope to get it resolved before the end of this month.

**Comment by fogflute** [comment]
Can i fetch 1 second interval OHLCV candle stick for one specific symbol via watchOHLCV?

**Comment by frosty00** [comment]
if the exchange supports that, but the majority don't (i haven't see a case where that is supported). You would be better off subscribing to `watchTrades` and calculating your own OHLCV based on that data.

**Comment by moodmosaic** [comment]
How's the CCXT Pro license works? Say I buy the beginner license, for one month. What happens after one month? I guess I can no longer pull the latest updates from the repo?

**Comment by kroitor** [comment]
@moodmosaic that's right, your software will keep working with the most recent version you have by the time your license expires, however, you won't be able to get newer updates and the following versions.

**Comment by moodmosaic** [comment]
@kroitor, sounds great, thank you.
