### ISSUE TITLE
Limited L2 orderbook does not produce consistent amount of results - CCXT PRO

### ISSUE THREAD

**Issue by 1key** [ccxt/ccxt#6546]
- OS: Win10
- Programming Language version: Python 3.8
- CCXT version: 0.0.47
- Exchange: Binance, WS

```
import ccxtpro
import asyncio

async def main():
    exchange = ccxtpro.binance({'enableRateLimit': True})
    while True:
        orderbook = await exchange.watch_order_book('ETH/BTC', 10) #INCONSISTENT, see below
        print(len(orderbook['asks']), len(orderbook['bids']))

asyncio.get_event_loop().run_until_complete(main())

```

Results:

```
10 10
10 10
10 9
9 10
10 10
10 10
10 10
10 9
10 10
```

and:
```
        orderbook = await exchange.watch_order_book('ETH/BTC', 1)
        print(orderbook['asks'][0]), (orderbook['bids'][0])
```
Produces (after some correct results):
```
    print(orderbook['asks'][0]), (orderbook['bids'][0])
IndexError: list index out of range
```

**Comment by kroitor** [comment]
Technically, this is not fully a bug. What happens is that when you limit the orders in real-time mode by supplying the `limit` argument CCXT will only store up to `limit` orders. In some cases an order may be deleted from the order (when matched), so the exchange sends a zero delta and it is removed from the orderbook leaving just the 9 orders of 10 (until another one fills the gap). The responsibility of CCXT Pro in this case is to return immediately after receiving a "delete" command from the exchange.

So, from here, you have two options:

- either expect the number of bids/asks to be less than or equal to `limit` in the result 
- or don't send `limit` (CCXT will keep the entire orderbook in memory) and just use python's array slicing [0:5]

Also, Binance does support limited WS feeds for 5, 10 or 20 bidasks, however, when `limit` is sent to the exchange – it will rate-limit the feed by 100ms or 1000ms which is not good for real-time apps, therefore the `limit` is not sent to Binance in particular at this time, and all the limiting is done on the client.

We will add this to the documentation shortly to avoid confusion.

Let me know if that does not answer the question.

**Comment by 1key** [comment]
Clear and fast answer!
Will work around it then.

**Comment by kroitor** [comment]
@1key we will look into adding an option that would still store the entire orderbook and always serve a number of bidasks a close as possible to `limit` , but in the general case an exchange orderbook may have less than any number of bid/asks (just like with fetchOrderBook over REST). So if the exchange is inactive, there may be very few or even zero orders on either side of the book. 

Feel free to reopen this if anything or just ask further questions if you have more. Thanks for the feedback!
