### ISSUE TITLE
GDAX fee data is missing in trades

### ISSUE THREAD

**Issue by nmiculinic** [ccxt/ccxt#655]
```
                        'fill_fees': '0.0000035913586272',
                        'filled_size': '0.02701082',
```

GDAX has this data available in the reply, but fee field is None. Could you please use it in returning fees info?

**Comment by kroitor** [comment]
@nmiculinic sure! It would be awesome if you could submit a PR as well, we will be happy for all contributions! Thx!

**Comment by nmiculinic** [comment]
I guess this entails changing js files? 

Is there a guide how to build (transpile) your lib and everything that's needed for that?

**Comment by kroitor** [comment]
If you compare the JS code to the Python code (where fee aspects are implemented), you will immediately notice, that it is a line-to-line mapping, so it's very straightforward, just copy the code  from some other place where the same functionality is already present and it will most likely run and transpile to other languages smoothly. 

More on how to submit contributions: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

Let us know if you need any help and feel free to ask questions. Thanks!
