### ISSUE TITLE
Error on okcoinusd.fetchMarkets

### ISSUE THREAD

**Issue by fbadiola** [ccxt/ccxt#6551]
- OS: Linux
- Programming Language version: JavaScript
- CCXT version: 1.23.30
- Exchange: okcoinusd
- Method: fetchMarkets

When I invoke `fetchMarkets` on `okcoinusd` exchanges it throws an error:

```
 ExchangeError: okcoinusd {"code":0,"data":[{"baseCurrency":0,"brokerId":0,"callAuctionOrCallNoCancelAuction":false,"callNoCancelSwitchTime":1569397477000,"collect":"0","continuousSwitchTime":{},"entityMarginStatus":0,"entitySpotStatus":0,"envType":4,"groupId":1,"id":3,"isMarginOpen":true,"listDisplay":0,"marginRiskPreRatio":1.2,"marginRiskRatio":1.1,"marketFrom":0,"matcherId":100,"maxLeverRate":10.0000000000000000,"maxMarginLeverage":3,"maxPrice........
````

You can reproduce it with this code:
```javascript
const ccxt = require('ccxt');

const exchange = new ccxt.okcoinusd();

async function main() {
  const markets = await exchange.fetchMarkets();

  console.log(markets);
}

main();
```

**Comment by kroitor** [comment]
Thank you for reporting! Fixed in 1.23.31.

**Comment by zsyh** [comment]
Notice: okcoinusd/okex will terminate v1 api service at 06:00 Mar 25, 2020 (UTC)
https://okexsupport.zendesk.com/hc/en-us/articles/360039669551

**Comment by kroitor** [comment]
@zsyh thank you for the notice! It is very old indeed. We suggest `okex3` instead of `okex`.
