### ISSUE TITLE
An unconditional exception in okcoinusd handle_errors.

### ISSUE THREAD

**Issue by alexander-irbis** [ccxt/ccxt#6561]
- OS: MacOS/Linux
- Programming Language version: Python 3.7.5
- CCXT version: 1.23.48
- Exchange: okcoin
- Method: fetchTicker (, something else?).

In the `handle_errors` method, the call 
```
error = self.safe_string(response, 'error_code', 'code')
``` 
and consequent check for 
```
if (error is not None) and (error != '0'):
```
leads to the unconditionally raised exception, while `error` is always has a value (`'code'` for instance).

This breaks at least fetchTicker.

**Comment by alexander-irbis** [comment]
Removing `'code'` from arguments fixes things.

**Comment by alexander-irbis** [comment]
Extremely fast bugfixing ever! :-)

**Comment by kroitor** [comment]
@alexander-irbis thx for reporting it! ) We appreciate all feedback!
