### ISSUE TITLE
Sending a take_profit order on Binance futures

### ISSUE THREAD

**Issue by kaiserex** [ccxt/ccxt#6566]
Hi Guys,
I am having trouble sending a take_profit order to Binance futures platform. Does anyone have any sample code?

**Comment by kroitor** [comment]
Hi! Can you elaborate plz? 

- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

**Comment by kaiserex** [comment]
My current Binance config:

```
    binance_keys = {
        'options': {'defaultType': 'future'},
        'apiKey': key,
        'secret': secret,
        'enableRateLimit': True,
        'verbose': True,
        'urls': {
            'api': {
                'public': 'https://fapi.binance.com/fapi/v1',
                'private': 'https://fapi.binance.com/fapi/v1'
            }}
    }
```
Line i am running(tried with and without price):
```
ccxt.binance(keys).create_order(symbol=ticker, type='take_profit', side=order_side,
                                                       amount=order_size, price = stop_price, params={'stopPrice':stop_price})
```
Response i am getting:

`Request: POST https://fapi.binance.com/fapi/v1/order {'X-MBX-APIKEY': 'KEY', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.21.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1583334438968&recvWindow=5000&symbol=BTCUSDT&type=TAKE_PROFIT&side=BUY&quantity=0.001&stopPrice=8600&signature=SIGNATURE`

`Response: POST https://fapi.binance.com/fapi/v1/order 400 {'Content-Type': 'application/json', 'Content-Length': '88', 'Connection': 'keep-alive', 'Date': 'Wed, 04 Mar 2020 15:07:19 GMT', 'Server': 'Tengine', 'X-MBX-USED-WEIGHT-1M': '1', 'X-MBX-ORDER-COUNT-1M': '1', 'x-response-time': '1ms', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'origin-when-cross-origin', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 51b6f8f9e6a4ed138b0c486aecbc264c.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'HEL50-C1', 'X-Amz-Cf-Id': 'Gx-U6P4KTBpy7IJ1m1YBmKAM_cQSEDRmgN9xkLx-vBWTltN_zJZt6A=='} {"code":-1102,"msg":"A mandatory parameter was not sent, was empty/null, or malformed."}`

**Comment by kroitor** [comment]
@kaiserex it appears that TAKE_PROFIT with Binance futures requires price:

https://binance-docs.github.io/apidocs/futures/en/#new-order-trade

![Screen-Shot-2020-03-05-at-10 20 14](https://user-images.githubusercontent.com/1294454/75957508-35ab1d00-5ecb-11ea-9ff8-c391232e65f7.jpg)

As opposed to spot markets TAKE_PROFIT (or one of the docs is not consistent):

https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-order--trade 

![Screen-Shot-2020-03-05-at-10 20 44](https://user-images.githubusercontent.com/1294454/75957542-4f4c6480-5ecb-11ea-949f-37675395b849.jpg)

So, if you add the price to your params – it should work:

```Python
params={
    'price': YOUR_PRICE_HERE,  # ←------------------ here
    'stopPrice': stop_price,
}
ccxt.binance(keys).create_order(symbol=ticker, type='take_profit', side=order_side,
                                                       amount=order_size, price = stop_price, params=params)
```

↑ This should work.

Also, if you update your version to 1.23.65+ – it will work as is, without having to override the `'price'` in params. Let us know if that does not help. We will be happy if you report back whether it does solve your issue or not. Thx for the feedback!

**Comment by kaiserex** [comment]
Thanks kroitor, it works after adding an extra param of price.

**Comment by kroitor** [comment]
@kaiserex thx for reporting back! Btw, with the updated version of CCXT it should work even without setting the price.
