### ISSUE TITLE
How do I place a contract on the bibox exchange through ccxt?

### ISSUE THREAD

**Issue by xkyykx** [ccxt/ccxt#6574]
I want to trade contracts on the bibox exchange, but I didn't find the corresponding method. I added a method to ccxt \ bibox.py:

```Python
def create_swap_order(self, symbol, type, side, contract, price=None, leverage=2, params={}):
        self.load_markets()
        market = self.market(symbol)
        orderType = 2 if (type == 'limit') else 1
        orderSide = 1 if (side == 'buy') else 2
        request = {
            'cmd': 'order/open',
            'body': self.extend({
                'pair': market['id'],
                'order_type': orderType,
                'order_side': orderSide,
                'price': price,
                'contract': contract,
                'order_from': 6,
                'leverage': leverage,
            }, params),
        }
        response = self.privatePostCtrade(request)
        return {
            'info': response,
            'id': self.safe_string(response, 'result'),
        }
```

Call this method with the following code:

```Python
import ccxt

bibox = ccxt.bibox()
bibox.apiKey = '******'
bibox.secret = '******'
bibox.timeout = 30000

order_info = bibox.create_swap_order('4LTC/USDT', 'limit', 'buy', 10, 50, 2)`
```

returned messages:

```
AttributeError: 'bibox' object has no attribute 'privatePostCtrade'
```

How can I solve this problem, and perform related operations such as placing orders, canceling orders, and checking orders on the bibox exchange?

api:https://biboxcom.github.io/zh-hans/rest_api_c.html#合约下单

Thank you!

**Comment by kroitor** [comment]
The bibox's `cquery` API has been added not so long ago, so it was missing in CCXT. I've uploaded the definitions for it, so it should work if you upgrade your CCXT version to 1.23.59 (the new build will arrive in 15 minutes). Let us know if that does not help. We will be thankful if you report back whether it helped or not. Thx again!

**Comment by xkyykx** [comment]
I have updated ccxt to version 1.23.59, but I do n’t know how to place a contract order. Can you give me an example of contract order, I am using Python 3. 谢谢！
&nbsp;

请订阅（更多资源）：http://www.zjclw.net/get &nbsp; &nbsp; &nbsp;


&nbsp;

**Comment by kroitor** [comment]
@xkyykx with the updated version, the code that you posted above should work. If it does not work, enable verbose mode:

- https://github.com/ccxt/ccxt/wiki/Manual#notes

... and post your output here (without your keys).

**Comment by kroitor** [comment]
@xkyykx you also want to enable the rate-limiter since it is required, as explained in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

In general we really recommend reading the Manual very carefully to a word at least once from top to bottom – that will help save your time, really.

**Comment by xkyykx** [comment]
I have updated to version 1.23.59, but this issue is not resolved.
I still added a method to ccxt \ bibox.py:

def create_swap_order(self, symbol, type, side, contract, price=None, leverage=2, params={}):
        self.load_markets()
        market = self.market(symbol)
        orderType = 2 if (type == 'limit') else 1
        orderSide = 1 if (side == 'buy') else 2
        request = {
            'cmd': 'order/open',
            'body': self.extend({
                'pair': market['id'],
                'order_type': orderType,
                'order_side': orderSide,
                'price': price,
                'contract': contract,
                'order_from': 6,
                'leverage': leverage,
            }, params),
        }
        response = self.privatePostCtrade(request)
        return {
            'info': response,
            'id': self.safe_string(response, 'result'),
        }



Call this method with the following code:
import ccxt


bibox = ccxt.bibox()
bibox.apiKey = '******'
bibox.secret = '******'
bibox.timeout = 30000 bibox.enableRateLimit = True

order_info = bibox.create_swap_order('4LTC/USDT', 'limit', 'buy', 10, 50, 2)

returned messages:
C:\Users\Administrator\AppData\Local\Programs\Python\Python38\python.exe C:/Users/Administrator/PycharmProjects/demo1/program/bibox.py
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/demo1/program/bibox.py", line 24, in <module&gt;
    order_info = bibox.create_swap_order('4LTC/USDT', 'limit', 'buy', 10, 50, 2)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\ccxt\bibox.py", line 915, in create_swap_order
    response = self.privatePostCtrade(request)
AttributeError: 'bibox' object has no attribute 'privatePostCtrade'

Process finished with exit code 1

Please give pointers, is my thinking correct? If it is correct, which step of my method is wrong? Thank you!

**Comment by kroitor** [comment]
> Please give pointers, is my thinking correct?

You're not following what I am saying in this comment: 

- https://github.com/ccxt/ccxt/issues/6574#issuecomment-595018475

> If it does not work, enable verbose mode:
>
> - https://github.com/ccxt/ccxt/wiki/Manual#notes
>
> ... and post your output here (without your keys).

So, we need more info from you to resolve this:

```Python
bibox = ccxt.bibox({'enableRateLimit': True})  # ←---------------------- 
bibox.apiKey = '******'
bibox.secret = '******'
bibox.timeout = 30000 

bibox.load_markets()  # ←--------------------
bibox.verbose = True  # ←--------------------

order_info = bibox.create_swap_order('4LTC/USDT', 'limit', 'buy', 10, 50, 2)
```

Post your output from the above snippet ↑ here, plz.

----

P.S. For the future, please, use [github markdown](https://guides.github.com/features/mastering-markdown/) for readability when posting code or text. Follow the steps from [here](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue) precisely. In general, it is a good rule to follow what's written literally. Surround your code with triple backticks. Don't confuse one backtick (&#096;) with three backticks (&#096;&#096;&#096;). The proper way to post code is shown below:

&#096;&#096;&#096;Python

Your code here...

&#096;&#096;&#096;

Or, to post console output:

&#096;&#096;&#096;

Text here

&#096;&#096;&#096;

**Comment by kroitor** [comment]
@xkyykx actually, the error is here:

```
AttributeError: 'bibox' object has no attribute 'privatePostCtrade'
```

↑ Your method should call `privatePostCquery` instead of `privatePostCtrade`.

**Comment by kroitor** [comment]
@xkyykx i've uploaded another fix to it, pardon for the inconvenience, I missed the ctrade endpoints, my bad. Added them now, so it should work fine as of 1.23.63+ (the new build will arrive in 15 minutes). Let me know if the issue is fixed or not on your side. Thx for your help debugging this.

**Comment by xkyykx** [comment]
问题解决。谢谢！
因为我不是程序员，在 github 提交的信息不规范，对问题的描述不精准，给您带来不便，深感抱歉！


problem solved. Thank you! Because I am not a programmer, the information submitted on github is not standardized, the description of the problem is not accurate, and I am sorry for the inconvenience!

**Comment by kroitor** [comment]
@xkyykx no worries, you're welcome, thx for reporting back!
