### ISSUE TITLE
About USDT(trc-20) Withdrawal from HuobiPro

### ISSUE THREAD

**Issue by coincoin1** [ccxt/ccxt#6576]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: window 10
- Programming Language version: python 3.7
- CCXT version: 1.23.50
- Exchange: HuobiPro
- Method: withdraw

https://huobiapi.github.io/docs/spot/v1/en/#create-a-withdraw-request

I want to withdraw USDT(trc-20) from Huobi. But an error occurs when trying to withdraw.

Also, it does not work if the chain is set to trc20usdt as shown in the huobipro api document.

error : ccxt.base.errors.ExchangeError: huobipro {"status":"error","err-code":"api-not-support-temp-addr","err-msg":"API withdrawal does not support temporary addresses","data":null}

```
import ccxt

huobi = ccxt.huobipro({
    'apiKey': 'input apiKey',
    'secret': 'input secret apikey', 
})

huobi.withdraw("USDT", 10.12, "TBEBaRrYnwwYim5EjEgwHsuT2DTesdzbEd", params = {
    'chain':'trc20usdt',
})

```

**Comment by kroitor** [comment]
> But an error occurs when trying to withdraw.

Always describe the error or show your verbose output (without your keys, of course) as shown [here](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue) and [here](https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it) when reporting an error ) Otherwise it's very hard to help you )

```Python
import ccxt

huobi = ccxt.huobipro({
    'apiKey': 'input apiKey',
    'secret': 'input secret apikey', 
})

huobi.load_markets()  # load them first

# enable verbose mode after loading the markets to avoid too much output
huobi.verbose = True  

huobi.withdraw("USDT", 10.12, "TBEBaRrYnwwYim5EjEgwHsuT2DTesdzbEd", params = {
    'chain':'trc20usdt',
})
```

↑ Post your output here, plz.

**Comment by kroitor** [comment]
@coincoin1 in fact, you can actually see it from the message you've posted:

> error : ccxt.base.errors.ExchangeError: huobipro {"status":"error","err-code":"api-not-support-temp-addr","err-msg":"API withdrawal does not support temporary addresses","data":null}

This message in particular:

> API withdrawal does not support temporary addresses

Says, you should first create that withdrawal address in your address book in your account on the Huobi website, I think.

Let me know if that does not help. Feel free to reopen this issue or just ask further questions, if any.

**Comment by coincoin1** [comment]
When I registered the USDT address in address book, it was successfully sent. Thank you very much.

**Comment by kroitor** [comment]
@coincoin1 thx for reporting back, appreciate it!
