### ISSUE TITLE
CoinMarketCap v1 API deprecated / shutdown

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#6580]
```
{"statusCode":410,"error":"Gone","message":"WARNING: This API is now offline. Please switch to the new CoinMarketCap API. (https://pro.coinmarketcap.com/migrate/)"}
```

Now it's just the paid v2 API, since the free plan does not have the access to historical data. We will look into adding the support for CMC v2. It may be reasonable to also consider the  alternatives like CoinGecko and other aggregators as well.

Related:

- https://github.com/ccxt/ccxt/issues/3899

**Comment by tmlee** [comment]
Co-founder at CoinGecko here, I would love to help how we can get https://github.com/ccxt/ccxt/pull/3565 merged in, some of our API users have been asking for CCXT integration. It would be great to see it supported!

**Comment by fonzmeister** [comment]
For some projects I have used coinpaprika. Probably also a good option to consider. Api is free to use

**Comment by peachteaboba** [comment]
Appreciate all the hard work put into this amazing library! Is it possible to get a ballpark estimate of when the new (pro-api.coinmarketcap.com) integrations will be available? Just noticed that the old implementations no longer work in my app and am currently searching for potential solutions..

**Comment by kroitor** [comment]
@peachteaboba we are not entirely sure yet, if we should add the support for CMC v2 and we are looking into the alternatives as well. Can't promise an ETA, but will do what we can to get this resolved asap.
