### ISSUE TITLE
binance.fapiPrivateGetPositionRisk ( {  symbol : 'IOSTUSDT' } )

### ISSUE THREAD

**Issue by Gennttii** [ccxt/ccxt#6582]
binance.fapiPrivateGetPositionRisk ( {  symbol : 'IOSTUSDT' } ) is not working
It works only with  'BTCUSDT' and 'ETHUSDT'  pairs. 
I have latest version of ccxt ..!

**Comment by kroitor** [comment]
>  is not working

Can you elaborate please? 

- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it

**Comment by Gennttii** [comment]
It doesn't show any data, it shows data for BTC and ETH only, not other pairs, there are 24 pairs in Binance futures, but `binance.fapiPrivateGetPositionRisk` works for 2 pairs only, BTC and ETH

**Comment by kroitor** [comment]
@Gennttii can you post your verbose output?

**Comment by kroitor** [comment]
@Gennttii actually, you're right, it does not return them to me either. Do you have an open position with IOSTUSDT or have you traded the IOST/USDT futures market previously?

**Comment by Gennttii** [comment]
I was testing, this is in testnet, maybe its the same in real futures.  I have open position but it doesn't show it, it shows only Btc and Eth positions

**Comment by kroitor** [comment]
@Gennttii in this case you might want to reach out to Binance for explanations. Basically, what you get from `fapiPrivateGetPositionRisk` is what the exchange returns (not CCXT), so if something is missing there – you might want to address to Binance tech support. Alternatively, you can also check if it does return your open positions in the unified fetchBalance method (as far as I remember, you're using JS):

```JavaScript
const ccxt = require ('ccxt')
const exchange = new ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': true,
    'options': {
        'defaultType': 'future',
    },
})
;(async () => {
    const response = await exchange.fetchBalance ()
    // console.log (response) // dump the entire unified and parsed structure
    console.log (response['info']) // dump just the raw response from the exchange as is
}) ()
```

↑ The `info` field will contain the positions as well. If you don't see your position there – please, open a ticket with Binance. We will be happy if you report back whether you have a followup on this issue or not. Hope this helps, let me know if you still have difficulties with it.

**Comment by neurocreepto** [comment]
> @Gennttii in this case you might want to reach out to Binance for explanations. Basically, what you get from `fapiPrivateGetPositionRisk` is what the exchange returns (not CCXT), so if something is missing there – you might want to address to Binance tech support. Alternatively, you can also check if it does return your open positions in the unified fetchBalance method (as far as I remember, you're using JS):
> 
> ```js
> const ccxt = require ('ccxt')
> const exchange = new ccxt.binance({
>     'apiKey': 'YOUR_API_KEY',
>     'secret': 'YOUR_SECRET',
>     'enableRateLimit': true,
>     'options': {
>         'defaultType': 'future',
>     },
> })
> ;(async () => {
>     const response = await exchange.fetchBalance ()
>     // console.log (response) // dump the entire unified and parsed structure
>     console.log (response['info']) // dump just the raw response from the exchange as is
> }) ()
> ```
> 
> ↑ The `info` field will contain the positions as well. If you don't see your position there – please, open a ticket with Binance. We will be happy if you report back whether you have a followup on this issue or not. Hope this helps, let me know if you still have difficulties with it. Feel free to reopen it or just ask further questions, if any.

This solution is not working in javascript. I'm trying to get open positions on Binance (futures) and is returning a lot of records that aren't open positions/trades.  I have been trying to solve it for days but I can't get a solution. 
Any other idea?

CCXT: 1.91.4
LANGUAGE: Javascript
Method: fetchBalance / fetchMyTrades
