### ISSUE TITLE
Kraken watchOrderBook only returns 10 bids/asks

### ISSUE THREAD

**Issue by 1key** [ccxt/ccxt#6583]
- OS: Win10
- Programming Language version: Python 3.8
- CCXT version: 0.0.58
- Exchange: Kraken
- Method: watchOrderBook(market, 100)

I only receive 10 bids and 10 asks on each symbol.
Either with no limit set or when a limit set above 10.
Can't find this limitation in the Websocket documentation of Kraken itself, so it might be in the code of CCXTpro?

**Comment by frosty00** [comment]
Hi @1key,

The issue was indeed with ccxt.pro, I've fixed it in https://github.com/kroitor/ccxt.pro/pull/12

Probably igor will merge it as soon as he gets online.

Thank you for using ccxt pro!

**Comment by frosty00** [comment]
if you want it to work now you can just delete the 

```self.orderbooks[symbol] = this.order_book ({}, 10)```

10 argument from this line

**Comment by kroitor** [comment]
Thank you for reporting @1key! This is now fixed in CCXT Pro 0.0.60+
