### ISSUE TITLE
ccxt.poloniex.markets is limited to 100

### ISSUE THREAD

**Issue by 1key** [ccxt/ccxt#6587]
- OS: Win10
- Programming Language version: Python 3.8
- CCXT version: PRO 0.0.60
- Exchange: Poloniex
- Method: loadMarkets()

There are only 100 markets shown while they have almost twice that much.

PS Kroitor: Compliments on the mega fast fixes!

**Comment by kroitor** [comment]
@1key yesterday polo was on maintenance and they have limited the number of tickers returned to 100, but haven't provided any other means of fetching the list of all pairs. So, we will look into handling this limit somehow. This is actually in CCXT, not in Pro, and it probably affects all API users of Poloniex, not just us. We'll get this resolved.

**Comment by kroitor** [comment]
We've sent a request to Poloniex to resolve this, will follow up with updates.

**Comment by 1key** [comment]
Great, thnx!

**Comment by kroitor** [comment]
Here's the answer from Poloniex: 

> Cooper (Poloniex)Mar 12, 9:49 AM UTC
>
> Hi, Thanks for your patience with this case.
> The reason your results displayed only 100 entries, is because our entire list of markets is a total of 100.
>
> Please let us know if you have any other questions.
>
>Cooper - Poloniex

Let us know if that does not help.
