### ISSUE TITLE
https://github.com/ccxt/ccxt/wiki/Manual#exchangenotavailable

### ISSUE THREAD

**Issue by oppure** [ccxt/ccxt#6589]
Hi
as far as I can see exchangenotavailable is returned also when the exchange is not reachable (e.g. no network connection) this information could be added to the documentation. thanks. Regards.

**Comment by kroitor** [comment]
Hi! It is already in the Manual here: https://github.com/ccxt/ccxt/wiki/Manual#error-handling. Let us know if that does not help.

**Comment by oppure** [comment]
Sorry I will check the manual better. All I found so far is:
ExchangeNotAvailable
The ccxt library throws this error if it detects any of the following keywords in response:
    offline
    unavailable
    busy
    retry
    wait
    maintain
    maintenance
    maintenancing

which doesn't state that ExchangeNotAvailable is thrown when the exchange is not reachable.

**Comment by kroitor** [comment]
@oppure ah, ok will add a mention of that specifically.
