### ISSUE TITLE
Bitfinex2 Missing Position Method

### ISSUE THREAD

**Issue by PolybitSol** [ccxt/ccxt#659]
Hey,

Bitfinex2 is missing the API method to retrieve active positions. Ref doc can be [found here](https://docs.bitfinex.com/v2/reference#rest-auth-positions). Method name would be of the format `privatePostAuthRPositions`.

**Comment by kroitor** [comment]
@PolybitSol thx for your feedback, as always! We added that endpoint, it is available in current version of ccxt. Cheers!

**Comment by alexzaporozhets** [comment]
@kroitor can you add an example how to use it?
