### ISSUE TITLE
Questions about the calculate_fee function when buying and selling

### ISSUE THREAD

**Issue by Hororohoruru** [ccxt/ccxt#6592]
- OS: Ubuntu 18
- Programming Language version: Python 3.7
- CCXT version: 1.22.76
- Exchange: Poloniex / Hitbtc
- Method: calculate_fee

Hello, I am trying to automatically buy and sell currencies on the symbol BTC/USDT in Poloniex and HitBTC when certain conditions are met. Now I am trying to figure out the maximum amount I can buy/sell taking fees into account. For this I have:

* only BTC in Poloniex
* only USDT in Hitbtc

I am trying to place a buy order in HitBTC, so I calculate my fees like this:

    symbol = 'BTC/USDT'
    type = 'limit'
    side = 'buy'
    quote = 92.05
    price = 8337.285
    amount = quote / ask_price
    
    hitbtc.calculate_fee(symbol=symbol, type=type, side=side, 
                         amount=amount_div, price=price) 

And I get

    {'rate': 0.002, 'type': 'taker', 'currency': 'USDT', 'cost': 0.18}

So I could do amount - cost to get an amount I can place the buy order for accounting for fees. The problem is that when I do the same with the selling currency I get this:

    side = 'sell'
    base = 0.01
    price = 8339.057

    polo.calculate_fee(symbol=symbol, type='limit', 
                       side=type, amount=base, price=price)

I get:

    {'type': 'taker', 'currency': 'USDT', 'rate': 0.0009, 'cost': 0.08222311}

Why are the fees for a sell order in BTC expressed in USDT? The fees for a sell order should be paid in BTC, so I don't understand why the function returns the amount in USDT instead of BTC

**Comment by kroitor** [comment]
> Why are the fees for a sell order in BTC expressed in USDT?

Poloniex uses _base_ currency fees for buys and _quote_ currency fees for sells. This corresponds to the fee amount returned in the trades history from the Polo's API itself. All of this is covered in the Manual, though. And this is common with many exchanges to switch fee sides depending on the order side. Btw, in some cases the actual price (and fee) may be lower, so `calculate_fee` is mostly for internal purposes. But in your particular case, I think it returns the data corresponding to the _financial facts_ from Polo. Let us know if you think this is still wrong or we are missing something, or if this does not answer the question.

**Comment by kroitor** [comment]
Also related to this question:

- https://github.com/ccxt/ccxt/issues/4506

**Comment by Hororohoruru** [comment]
Do you mean that the currency returned by calculate_fee is always in the currency that the exchange wants for that type of trade (buy or sell)? For example, does the return of the fee un USDT for selling in Poloniex mean that the amount specified for selling in this symbol must also be in USDT?

**Comment by kroitor** [comment]
> Do you mean that the currency returned by calculate_fee is always in the currency that the exchange wants for that type of trade (buy or sell)?

Yes.

> For example, does the return of the fee un USDT for selling in Poloniex mean that the amount specified for selling in this symbol must also be in USDT?

No. The amount is always in _base_ currency and the price is always in _quote_ currency. In fact, the fee currency is not tied to the currencies you're buying or selling and can be a third currency even. Like, with Binance you can pay fees in BNB while trading BTC/USDT. So the fee currency really depends on the trading rules of the exchange in question.

**Comment by Hororohoruru** [comment]
> No. The amount is always in _base_ currency and the price is always in _quote_ currency. In fact, the fee currency is not tied to the currencies you're buying or selling and can be a third currency even. Like, with Binance you can pay fees in BNB while trading BTC/USDT. So the fee currency really depends on the trading rules of the exchange in question and can be user-specific in some cases, depending on your account settings. This is one of the reasons why `calculate_fee` is not meant to be used directly, since it can lead newcoming users into a confusion.

I understand. Then, the amount is always in base and the price always in quote for all exchanges? Otherwise, my question is answered. Thank you very much!

**Comment by kroitor** [comment]
> I understand. Then, the amount is always in base and the price always in quote for all exchanges?

In terms of CCXT the amount is always in base and the price is always in quote for all exchanges. However, some exchanges also allow you to specify amounts in quote for market buys (the logic is to _"spend that much quote USD to buy as much base BTC as possible for quote USD"_). This should not affect the fee calculation though. In short the answer to your question is – because Poloniex wants the sell fees in quote.

**Comment by Hororohoruru** [comment]
Sounds good to me. I think that is much simpler from the user POV to have consistency in the units used for quantity and price. Thanks!
