### ISSUE TITLE
[bitbay] error parse

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6594]
When placing a bitbay order with a postOnly flag, I sometimes get this error is it's priced so that it would fill immediately (excuse the formatting):

`"ExchangeError (bitbay {\"status\":\"Fail\",\"errors\": [\"OFFER_WOULD_HAVE_BEEN_PARTIALLY_FILLED\"]})\"`

Is there a better error category that could be used in this case?

**Comment by kroitor** [comment]
> Is there a better error category that could be used in this case?

- [`OrderImmediatelyFillable`](https://github.com/ccxt/ccxt/blob/master/js/base/errorHierarchy.js#L25) ?

If you don't see a good category there, we could add one... like `OrderPartiallyFillable`, though, this usually isn't considered an exceptional situation with regular trading. In other words, for an order to be partially fillable – should be absolutely ok, what do you think?

**Comment by npomfret** [comment]
OrderImmediatelyFillable sounds perfect actually
