### ISSUE TITLE
Binance Futures - Fetch Open Positions

### ISSUE THREAD

**Issue by azharuniverse** [ccxt/ccxt#6595]
- OS: ALL
- Programming Language version: ALL
- CCXT version: ^1.23.22
- Exchange: Binance Futures
- Method: fetchMyTrades

Is there any api endpoint which can give me open positions. or a way to find open positions from all trades api like binance show only open positions in positions tabs
![image](https://user-images.githubusercontent.com/4450261/76230014-1acd0580-6249-11ea-80f9-89b5b4344fab.png)

`fapiPrivateGetUserTrades` returns all past orders also. There is no way to identify which position is still open.
![image](https://user-images.githubusercontent.com/4450261/76229882-e6594980-6248-11ea-92d3-2befec5c5a11.png)

**Comment by kroitor** [comment]
@azharuniverse you can get the list of your positions with Binance futures like so:

```JavaSript
const ccxt = require ('ccxt')
const exchange = new ccxt.binance ({
    enableRateLimit: true,
    'options': { defaultType: 'future' }
})
;(async () => {
    const balance = await exchange.fetchBalance ()
    console.log (balance['info']) // will contain your positions
}) ()
```

Duplicate:

- https://github.com/ccxt/ccxt/issues/6582

Let us know if that does not help.
