### ISSUE TITLE
Cryptopia createOrder "bad OrderId" error

### ISSUE THREAD

**Issue by Yoyae** [ccxt/ccxt#660]
When creating an order that is immediatly filled, cryptopia API doesn't return the OrderId field which raise the following error : 
Error: cryptopia createOrder returned bad OrderId: {"Success":true,"Error":null,"Data":{"OrderId":null,"FilledOrders":[xxxxxx]}.

Note that xxxxx is the order that have been filled.

**Comment by kroitor** [comment]
Thx for reporting! Will fix this soon.

**Comment by kroitor** [comment]
@Yoyae are you sure that xxxxxx is the order that was filled, not the list of filling trades' ids ? I'm asking this, because if I submit a single order, why would that be a list of ids? The only reasonable explanation is that those are trade ids, not order ids. This is not documented on their site or anywhere else, so if you can check your trades' ids against xxxxxx and report on that, it would be awesome. I would then add proper handling to it. Our main question/concern is whether xxxxxx stands for order ids or trade ids. We asked Cryptopia about it, but received no answer from them.

**Comment by kroitor** [comment]
I guess,  xxxx means "opposite" filled orders. But I don't see any use of them. Should we just return an undefined order id in that particular case? How do you know if it made it or not then? The actual fill price/cost? Their API is very non-intuitive.

**Comment by Yoyae** [comment]
You're right, I didn't double check. There is a different between order id and trade id, and xxxx is trade ( = filled order) id. Undefined order without throwing an error sound the right behaviour. You know it made it cause API doesn't return an error. Afterward you can't know which trade its related to.

Anyway, thanks for fixing it.

**Comment by Pmant** [comment]
I understand that if the order is filled instantly we get undefined as id. But if that is not the case and an id is given, this id still does not work for fetchOrder(id).  The returned id is just a 9-digit number.

**Comment by kroitor** [comment]
> But if that is not the case and an id is given, this id still does not work for fetchOrder(id).

Can you, please, paste your code and verbose output?

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by Pmant** [comment]
Thanks for looking into this, here is a small code sample (Node.js):
```javascript
'use strict';
const ccxt = require ('ccxt');
const cryptopia  = new ccxt.cryptopia({
    verbose: true,
    apiKey: '123',
    secret: '456',
});

async function test() {
    let orderResult = await cryptopia.createLimitSellOrder('LBC/BTC', 29, 0.00003538);
    console.log('orderResult: ' + orderResult);
    if (orderResult.id !== undefined) {
        let order = await cryptopia.fetchOrder(orderResult.id, 'LBC/BTC');
        console.log('order: ' + order);
    }
}

test().then(()=>{console.log('done')});
```
And the corresponding log:
```
cryptopia POST https://www.cryptopia.co.nz/api/SubmitTrade
Request:
 { 'Content-Type': 'application/json',
  Authorization: '123' } {"TradePairId":4165,"Type":"Sell","Rate":"0.00003538","Amount":29}
cryptopia POST https://www.cryptopia.co.nz/api/SubmitTrade 200 OK
Response:
{"Success":true,"Error":null,"Data":{"OrderId":197453270,"FilledOrders":[]}}
orderResult: [object Object]
cryptopia POST https://www.cryptopia.co.nz/api/GetOpenOrders
Request:
 { 'Content-Type': 'application/json',
  Authorization: '123' } {"TradePairId":4165}
cryptopia POST https://www.cryptopia.co.nz/api/GetOpenOrders 200 OK
Response:
{"Success":true,"Error":null,"Data":[{"OrderId":197453270,"TradePairId":4165,"Market":"LBC/BTC","Type":"Sell","Rate":0.00003538,"Amount":29.00000000,"Total":0.00102602,"Remaining":29.00000000,"TimeStamp":"2017-12-13T15:25:55.5430888"}]}
(node:6092) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cryptopia order 197453270 not found in cached .orders, fetchOrder requires .orders (de)serialization implemented for this method to work properly
(node:6092) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kroitor** [comment]
@Pmant thanks for the report, we will fix it very soon. I'll keep you updated on this.

**Comment by ericvrp** [comment]
This is closed but was it fixed? When I create a limit buy order like this
`const buyResult = await this.exchange.createLimitBuyOrder(symbol, amount, price)`
and after one minute do 
`await this.exchange.fetchOrder(buyResult.id, symbol)`
I get
`(node:32533) UnhandledPromiseRejectionWarning: Error: cryptopia order 248825909 not found in cached .orders, fetchOrder requires .orders (de)serialization implemented for this method to work properly`

**Comment by kroitor** [comment]
> When I create a limit buy order like this
> and after one minute do

Do you stop your program between step one and step two? I mean, is it running all the time, or do you relaunch it a minute later?

**Comment by Pmant** [comment]
according to #951 the order id gets lost at some point when calling fetch_orders.

**Comment by kroitor** [comment]
@ericvrp , @Pmant this is an effect of Cryptopia not having any means of fetching order history, therefore we have to cache them upon creation so that you could access them, but if you shudown your program, you have to save that data and reload (deserialize it literally as the exception tells you to do), so that orders don't get lost and will be reloaded from disk upon next restart to keep it all up to date. This is also partially explained here:
- https://github.com/ccxt/ccxt/issues/569
- https://github.com/ccxt/ccxt/issues/548#issuecomment-343909543
- https://github.com/ccxt/ccxt/issues/304#issuecomment-335508927
- https://github.com/ccxt/ccxt/pull/102
↑ same reasoning there

Let us know if the above answers the question.

**Comment by ericvrp** [comment]
I'll have a look at those issues tomorrow. The program keeps running in between the two calls. P.S. It could be that a fetchOrders is called in between I think.

**Comment by Pmant** [comment]
> but if you shudown your program, you have to save that data

Its not only after a shutdown, it doesn't even work right after the trade. Look at my code [above](https://github.com/ccxt/ccxt/issues/660#issuecomment-351428262).

Btw. what id is cached for orders which don't return an id, as pointed out [here](https://github.com/ccxt/ccxt/issues/660#issue-276433250)?

**Comment by ericvrp** [comment]
Indeed, I do get an order.id (248825909 in my example above) but when using that (without exiting the nodejs script) I get the error message 
`(node:32533) UnhandledPromiseRejectionWarning: Error: cryptopia order 248825909 not found in cached .orders, fetchOrder requires .orders (de)serialization implemented for this method to work properly`
which I should only get (if I understand you correctly) when I would exit the program and do a fetchOrder with that id without the cache being serialized and deserialzed.

**Comment by kroitor** [comment]
@ericvrp, @Pmant  looking into it now, will let you know when this is fixed, thx for reporting!

**Comment by kroitor** [comment]
@Pmant 

> Btw. what id is cached for orders which don't return an id, as pointed out here? Are these orders cached at all?

Cryptopia does not return an order id at all in that case, so you can't fetch that order later by an undefined id.

**Comment by kroitor** [comment]
@ericvrp can you please paste a minimal but a complete script to reproduce your problem?
