### ISSUE TITLE
Gemini (Roles) Master Account / Subaccount API Integration

### ISSUE THREAD

**Issue by drothroc** [ccxt/ccxt#6600]
Gemini incorporated master / subaccount infrastructure into their APIs. Any chance this could be incorporated into CCXT?

It includes the ability to create subaccounts from a master account. Create API keys with various roles (Trader, Fund Manager, Auditor) with different permissions for individual subaccounts. Utilize existing endpoints with new params to perform actions on specified subaccounts.
 
Info: 
[https://gemini.com/blog/introducing-subaccounts-for-institutions](url)

[https://docs.gemini.com/rest-api/#roles](url)

**Comment by kroitor** [comment]
Yes, in short, we are going to unify this aspect (the subaccounts and the transfers) as soon as we can. This is going to be one of our topmost priorities along from the unification of derivatives and margin/leveraged/positional trading.

**Comment by drothroc** [comment]
Awesome to hear @kroitor! Thanks for your hard work always! I'm diving into a lot of it now, but not sure I'm capable to help directly in the CCXT library, I'm really only somewhat decent w/ python. But if you have questions or want help with anything, I'll try to support the best I can. My alternative is to subclass gemini exchange and making the changes directly in python. 

No pressure, but was curious on the timeline you think you will be able to tackle this workload?

**Comment by kroitor** [comment]
@drothroc i can't provide an ETA on it, due to reasons explained [here](https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar), but I'll do my best to start the work on it asap, and, hopefully, have something feasible in April.

**Comment by pk8189** [comment]
@kroitor I would like to contribute and work on this issue, I was wondering if you have any scoping/requirements for this? if not no worries, just want to avoid duplicate work.
