### ISSUE TITLE
Deribit v2 added in CCXT 1.23.88+

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#6602]
Hi everyone!

Good news, Deribit v2 API is now supported in CCXT 1.23.88+!

A note on this implementation:

Deribit wants a currency code or a symbol for most private methods, even for `fetchBalance()`. It will default to `BTC`.

This is made configurable, and you can fetch the balances and other private data by setting various options:

```Python
ccxt = import ccxt
exchange = ccxt.deribit({
    'enableRateLimit': True,
    'options': {
        'code': 'ETH',  # set default currency exchange-wide
        'fetchBalance': {'code': 'ETH'},  # set currency per method
        # default quote if no symbol is specified
        'fetchOpenOrders': {'code': 'ETH'},
        'fetchMyTrades': {'code': 'ETH'},
        # ...
    },
})
```

Or you can also override it with params, of course:

```Python
balance = exchange.fetch_balance ({'currency': 'ETH'})
```

Thank you for using CCXT!

We are also going to list it in CCXT Pro soon! )

**Comment by alexeymarunin** [comment]
> Good news, Deribit v2 API is not supported in CCXT 1.23.88+!

Not supported? :)

**Comment by kroitor** [comment]
Sorry ) **noW**, of course ))

**Comment by etiennez0r** [comment]
Awesome ! thanks a lot :) gonna test it this week!

**Comment by mostar** [comment]
I'm trying to use this new API (ccxt 1.25.6) on Deribit test site. 
It fail on invalid_credentials. It seems that the private method don't work.

maybe because on v2 Deribit has changed the signature to hmac-sha256.
https://github.com/ccxt/ccxt/issues/4833#issuecomment-473725566

**Comment by kroitor** [comment]
@mostar it works for me right now, are you sure that your credentials are correct?

If you are sure that your credentials are ok and your CCXT version is up to date, please paste your code (without your keys) and your output as explained here: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

My code for testing:

```Python
import ccxt
exchange = ccxt.deribit ({
    'enableRateLimit: True,
    'apiKey': 'XXXXX',
    'secret': 'YYYYY',
})
print(exchange.fetch_balance())
```

**Comment by mostar** [comment]
When I test it on Python it work fine for me also. But I need it in PHP.
Here is the code and the verbose output

```
<?php

$ccxtroot = "/home2/ccxt2/ccxt1.25.6/php/";
include $ccxtroot . '/ccxt.php';

echo "CCXT v." . \ccxt\Exchange::VERSION . "\n";
$DeribitExchange = new \ccxt\deribit (array (
    'apiKey' => 'L....', // testnet 
    'secret' => 'J.....',
    'enableRateLimit' => true,
    'verbose' => true,
    'timeout' => 60000,
));
$DeribitExchange->urls["api"]  = $DeribitExchange->urls["test"]; 

$result = $DeribitExchange->fetch_balance ();
print_r ($result);
?>
```


Output:

```
Request:
Array
(
    [0] => GET
    [1] => https://test.deribit.com/api/v2/private/get_account_summary?currency=B
    [2] => Array
        (
            [0] => Authorization: deri-hmac-sha256 id=LY5wd4WLivjr,ts=1585235436958,sig=bd6e29eb0a1b072f4f50049b62179b2ed378067cfe95ee5de9e86ce08ec054e3,$nonce=1585235436958
        )

    [3] => 
)

CCXT v.1.25.6

PHP Fatal error:  Uncaught exception 'ccxt\AuthenticationError' with message 'deribit {"jsonrpc":"2.0","error":{"message":"invalid_credentials","code":13004},"testnet":true,"usIn":1585234780362028,"usOut":1585234780362055,"usDiff":27}' in /home2/ccxt2/ccxt1.25.6/php/base/Exchange.php:1172
Stack trace:
#0 /home2/ccxt2/ccxt1.25.6/php/deribit.php(1713): ccxt\Exchange->throw_exactly_matched_exception(Array, '13004', 'deribit {"jsonr...')
#1 /home2/ccxt2/ccxt1.25.6/php/base/Exchange.php(1382): ccxt\deribit->handle_errors(400, '', 'https://test.de...', 'GET', Array, '{"jsonrpc":"2.0...', Array, Array, NULL)
#2 /home2/ccxt2/ccxt1.25.6/php/base/Exchange.php(1159): ccxt\Exchange->fetch('https://test.de...', 'GET', Array, NULL)
#3 /home2/ccxt2/ccxt1.25.6/php/base/Exchange.php(1163): ccxt\Exchange->fetch2('get_account_sum...', 'private', 'GET', Array, NULL, NULL)
#4 [internal function]: ccxt\Exchange->request('get_account_sum...', 'private', 'GET', Array)
#5 /home2/ccxt2/ccxt1.25.6/php/base/Exchange.php(2365): call_user_func_array(Array, in /home2/ccxt2/ccxt1.25.6/php/base/Exchange.php on line 1172
```

Python verbose output:

```
...
Request: GET https://test.deribit.com/api/v2/private/get_account_summary?currency=BTC {'Authorization': 'deri-hmac-sha256 id=LY5wd4WLivjr,ts=1585235577523,sig=13ec000ba09ff7fb9d986ff2bd990b540236b6350a208b
4f53793afebbc8a03d,nonce=1585235577523', 'Accept-Encoding': 'gzip, deflate'} None
```

I thing there is other problem beside credentials. Please nore that in PHP the URL is truncated:

```
    [1] => https://test.deribit.com/api/v2/private/get_account_summary?currency=B
```
currency=B instead of currency=BTC

Thank you

**Comment by kroitor** [comment]
@mostar yep, found that bug, fixed it in CCXT v1.25.19. The new build will arrive in 15 minutes. I've tested it on my side and it works fine now. Please let me know if it works on your side or not. Thx for your feedback!

**Comment by gshpychka** [comment]
@kroitor deribit still not supported in pro?

**Comment by kroitor** [comment]
@gshpychka not yet, but we are doing whatever we can do get it listed this month, along with Huobi DM.

**Comment by gshpychka** [comment]
@kroitor Any updates on deribit support?

**Comment by kroitor** [comment]
@gshpychka pardon for the delay, it's in the works.

**Comment by gshpychka** [comment]
@kroitor is there an ETA on deribit support in CCXT Pro? Thanks.

**Comment by kroitor** [comment]
@gshpychka we are now working on Huobi DM and Bybit, Deribit is the next in line.

**Comment by gshpychka** [comment]
Thanks - is there a rough timeline for that?

**Comment by kroitor** [comment]
@gshpychka I'm a bit hesitant giving the ETAs, since I'm already late on the previous ETA. Will push it as soon as I can.

**Comment by gshpychka** [comment]
Appreciate that.

**Comment by gshpychka** [comment]
@kroitor is deribit pro still being worked on?

**Comment by kroitor** [comment]
@gshpychka yes, we are going to push OKEX v5 to CCXT Pro within a few hours, and will follow up with Huobi derivatives.

**Comment by gshpychka** [comment]
@kroitor Can you shed some light on why the project is so much behind? If I'm not mistaken, Huobi DM was supposed to be added to CCXT Pro in Q2 2020. Missing a deadline by over a year - something has got to be massively wrong here?

**Comment by kroitor** [comment]
@gshpychka we got too few people submitting quality integrations and PRs and too many requests, but we are looking to expand the team and will hopefully resolve the backlog.

**Comment by gshpychka** [comment]
@kroitor but surely you can take this into account when producing time estimates like that Q2 2020 figure? This is a paid product we're talking about, after all. Any updates on Deribit?

**Comment by kroitor** [comment]
@gshpychka you are right, my bad. We will probably refrain from estimates in the future. I'm working on Deribit rn, it's one of our topmost priorities.

**Comment by gshpychka** [comment]
It's disappointing that your solution to the underlying issue is to avoid estimates.

**Comment by gshpychka** [comment]
Hi, is Deribit Pro still being worked on?

**Comment by gshpychka** [comment]
@kroitor has Deribit Pro been abandoned?

**Comment by gshpychka** [comment]
@kroitor are you still working on ccxt?

**Comment by kroitor** [comment]
@gshpychka yes, I still work on it. We had to resolve a few things on our side to reorganize the work, and now that we have more people on the team we can finally cover the integration backlog. We will be focusing on that in the coming future.

**Comment by gshpychka** [comment]
@Kroitor great to hear! To make sure I understand it right - you're not focusing on that right now? I was under the impression that deribit pro was one of your topmost priorities four months ago.

**Comment by kroitor** [comment]
@gshpychka we are now in the process of unifying contract trading across the lib, will hopefully add Deribit Pro in Jan 2022:

- https://github.com/ccxt/ccxt/issues/10931

**Comment by gshpychka** [comment]
@kroitor checking in - are you on still on track for a Jan release? Unrelated: are there plans to support Bybit with ccxt pro?

**Comment by gshpychka** [comment]
@kroitor any progress?

**Comment by gshpychka** [comment]
@kroitor is Deribit Pro still planned at all? What went wrong?
