### ISSUE TITLE
Bittrex v3 API supports market order

### ISSUE THREAD

**Issue by azharuniverse** [ccxt/ccxt#6611]
Bittrex  v3 API supports looks incomplete. Are you going to release a seperate id bittrex3 or you will update methods in existing bittrex class. Please release support for market order.

- OS: ALL
- Programming Language version: ALL
- CCXT version:1.23.22
- Exchange:bittrex
- Method:createMarketOrder

**Comment by kroitor** [comment]
@azharuniverse the Bittrex v3 is currently in beta, and they say it's not for production use:

<img width="772" alt="Screen Shot 2020-03-12 at 19 40 08" src="https://user-images.githubusercontent.com/1294454/76544622-6a097500-6499-11ea-9a84-d4d55abdfcaa.png">

In general, we will switch bittrex v1.1 → bittrex v3, and the users will not have to change their code, however, we don't know when v3 goes stable yet. In the meantime we will probably add the support for Bittrex v3 market orders to the existing implementation in the coming days.

**Comment by azharuniverse** [comment]
Thanks @kroitor  for the quick response. 
Sounds reasonable.

**Comment by hivemall** [comment]
is bittrex market orders in yet, really looking foward to it?

**Comment by kroitor** [comment]
@azharuniverse , @hippylover Bittrex v3 market orders are now available in CCXT 1.24.47+
