### ISSUE TITLE
can't see the result of fetchDepositAddress and createDepositAddress

### ISSUE THREAD

**Issue by lcpsd** [ccxt/ccxt#6613]
I want to create or fetch my addresses but i'm not receive a response from server. what i'm doing wrong ?

```
async depositWithDrawAdresses(symbol){
            //symbol ex: BNB/BTC
            symbol = symbol.split('/')

            let addresses = new Object
            if(this.client.has['createDepositAddress']){
                addresses['depositAdress'] = await this.client.createDepositAddress(symbol[0])
            }else{
                addresses['depositAdress'] = await this.client.fetchDepositAddress(symbol[0])  
            }
            
            console.log(addresses)
        }
```

**Comment by kroitor** [comment]
> what i'm doing wrong ?

- https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it
- https://github.com/ccxt/ccxt/wiki/FAQ#i-am-calling-a-method-and-i-get-an-error-what-am-i-doing-wrong

**Comment by kroitor** [comment]
@lcpsd plz provide the info as described above, otherwise it's very hard to help you. Closing this for now, feel free to reopen it or just ask further questions, if any.
