### ISSUE TITLE
How to use ccxt with composer's autoload.php ??

### ISSUE THREAD

**Issue by Avalonalan** [ccxt/ccxt#662]
Hi, I am trying to use ccxt with my php work. After using composer to require ccxt, I have tried several times to use ccxt with autoload.php but I still cannot figure out how to import new object without including ccxt.php. Some codes like below ( p.s. my php version is 5.6.31  ) :

```
require "vendor/autoload.php";
$bitmex = new ccxt\bitmex();
```

The result is always "the class cannot be found". Could you help me how to let this work??
Thanks for your answer.

**Comment by kroitor** [comment]
Hi, @Avalonalan!

PHP's autoload functionality is not unified yet, but the work on it has been started, and is in progress: https://github.com/ccxt/ccxt/issues/633

You may want to try what this comment suggests: https://github.com/ccxt/ccxt/issues/633#issuecomment-346614117

We will be happy if you report back whether it answers your question and solves your problem or not.

**Comment by Avalonalan** [comment]
Hi, @kroitor !

Thanks for your kind help.

I have read the comments you told me. I have tested it with php >7.1 and it really works.
However, kornrunner/ccxt repo needs php version > 7.1 but my work is only with 5.6.31 since I use another repos for working with my current php ver. 
 **Do you know whether it can work properly with php 5.631 or not??? **

Well, I just took a look at files under the directory vendor/composer. I noticed that there is not any file including  default namespace setting to direct path for using ccxt.php. I think maybe this is the main reason that I cannot do something like what I just mentioned.

Thanks for your help.

**Comment by kroitor** [comment]
@Avalonalan we hope to add autoloading to current ccxt with PHP 5.3+ soon. In the meantime, I suggest, let's continue in that post, I would close this issue for now, if you don't mind, because these posts are mostly duplicate. Will notify you there on the progress of it.

**Comment by Avalonalan** [comment]
Hi, @kroitor  
It's fine. Thank you.
I really appreciate and look forward to your great work.
