### ISSUE TITLE
OKex createOrders 'type' field for futures contracts.

### ISSUE THREAD

**Issue by joyser** [ccxt/ccxt#6620]
When using createOrder for a futures contract on OKex, the 'type' field passed is matched to the OKex order type (1,2,3,4 for open long, open short, close long, close short respectively). Seems like it would be easier and more unified if this could instead be 'limit', and type supplied in the params argument?  Example:

Currently I create an order like this:

`
exchange.createOrder('BTC-USD-200626', 1, 1, 10, 5400);
`

Would it be better to have this: ?

`
exchange.createOrder('BTC-USD-200626', 'limit', 1, 10, 5400, {type:1});
`

**Comment by kroitor** [comment]
> Would it be better to have this: ?

To my mind, you should already have this. Have you tried doing that?

**Comment by joyser** [comment]
I tried exchange.createOrder('BTC-USD-200626', 'limit', 1, 10, 5400) and get an error.. 

never tried the second way listed above but brb will try now...  maybe just answered my own question 😅

**Comment by joyser** [comment]
yup i'm a fool

**Comment by kroitor** [comment]
@joyser thx anyways, it may help other users in the future.
