### ISSUE TITLE
load_markets and fetch_markets rise exception --> string indices must be integers

### ISSUE THREAD

**Issue by qwasko1212** [ccxt/ccxt#6623]
I have updated ccxt and I have problems with previously working code. 

```
 try:
     bitmex_rest = ccxt.bitmex({'urls': {'api': 'https://testnet.bitmex.com'}})
     self.markets = await bitmex_rest.load_markets(reload=True)
     await bitmex_rest.close()
 except Exception as exp:
     print(f'Markets init Exception: {exp}')
```

await bitmex_rest.load_markets(reload=True) rises string indices must be integers

- OS: Linux Mint 19
- Programming Language version: Python 3.6
- CCXT version:  1.24.25
- Exchange: Bitmex
- Method:  load_markets()

**Comment by kroitor** [comment]
@qwasko1212 this is not the correct way to switch to the testnet:

```Python
     bitmex_rest = ccxt.bitmex({'urls': {'api': 'https://testnet.bitmex.com'}})
```

The `api` definition for BitMEX is a dictionary of strings, not a string. The proper way to switch to testnet is:

```Python
try:
    bitmex_rest = ccxt.bitmex({'enableRateLimit':True})
    bitmex_rest.urls['api'] = bitmex_rest.urls['test']  # ←-------- BECAUSE IT'S A DICTIONARY
    self.markets = await bitmex_rest.load_markets(reload=True)
    await bitmex_rest.close()
except Exception as exp:
    print(f'Markets init Exception: {exp}')
```

Let us know if the above does not work.
