### ISSUE TITLE
OKEX/OKCoin WebSocket API added to CCXT Pro 0.0.80+

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#6638]
Hi everyone!

Good news) We have added the support for OKEX and OKCoin in [CCXT Pro](https://ccxt.pro) version 0.0.80+.

[![ccxt-pro-banner-black](https://user-images.githubusercontent.com/1294454/75621967-18650e80-5bac-11ea-9340-55746cab1e31.png)](https://ccxt.pro)

------

A note on the private WS API in this implementation:

Depending on the type of the trading account (spot/margin/future/swap/etc), OKEX WS API wants a currency code or an instrument symbol or id for the `watchBalance()`. It will default to `spot` account just like the `okex` implementation in CCXT.

This is made configurable, and you can watch the balance by setting various options:

```Python
ccxtpro = import ccxtpro
exchange = ccxtpro.okex({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'password': 'YOUR_PASSWORD',  # apiKey password
    'options': {
        'watchBalance': 'spot', # spot, margin, futures, swap
    },
})
```

Or you can also override it with params, of course:

```Python
# unified currency code
balance = await exchange.watch_balance ({'code': 'ETH'})  
```

```Python
# exchange-specific currency id
balance = await exchange.watch_balance ({'currency': 'ETH'})  
```

```Python
# exchange-specific instrument id
balance = await exchange.watch_balance ({'instrument_id': 'ETH-BTC'})  
```

```Python
# unified market symbol
balance = await exchange.watch_balance ({'symbol': 'ETH/BTC'})  
```

------

Thank you for using CCXT Pro!

[![CCXT Pro](https://user-images.githubusercontent.com/1294454/76917393-51072680-68d4-11ea-88df-6bff2cae6cb0.png)](https://ccxt.pro)

**Comment by icytrader** [comment]
will you add their real-time tick by tick orderbook channel please?
the channel is:  {"op": "subscribe", "args": ["futures/depth_l2_tbt:BTC-USD-200327"]}

**Comment by kroitor** [comment]
@icytrader yes, will add that shortly.

**Comment by kroitor** [comment]
@icytrader added the support for `depth_l2_tbt` and this is actually the default for OKEX/OKCoin as of version 0.1.7+. Thx for using CCXT Pro! Your feedback is welcome!
