### ISSUE TITLE
[ByBit] TypeError when parsing trades of fetch_my_trades

### ISSUE THREAD

**Issue by Herklos** [ccxt/ccxt#6644]
- OS: Linux / Ubuntu 19
- Programming Language version: python 3.7
- CCXT version: 1.24.4
- Exchange: ByBit
- Method: venv/lib/python3.7/site-packages/ccxt/base/exchange.py", line 829, in sort_by
    return sorted(array, key=lambda k: k[key] if k[key] is not None else "", reverse=descending)
TypeError: '<' not supported between instances of 'int' and 'str'

ByBit can't parse `fetch_my_trade` trades result even if it succeed to parse `fetch_trades` trades.

The reason is :
```
timestamp = self.parse8601(self.safe_string(trade, 'time'))
if timestamp is None:
        timestamp = self.safe_timestamp(trade, 'exec_time')
```

Returns `None` at the first try. Seems logic because a trade dict doesn't contains 'time'. But `self.safe_timestamp(trade, 'exec_time')` returns `None` even if the timestamp is correct, like `"exec_time": "1571676941.70682"`. 

I am currently trying to fix this...

**Comment by kroitor** [comment]
I can confirm this bug on my side:

```
$ python examples/py/cli.py bybit safe_timestamp '{"exec_time":"1571676941.70682"}' exec_time
None

$ python examples/py/cli.py bybit safe_timestamp '{"exec_time":"1571676941.706"}' exec_time
None

$ python examples/py/cli.py bybit safe_timestamp '{"exec_time":"1571676941"}' exec_time
1571676941000

$ python examples/py/cli.py bybit safe_timestamp '{"exec_time":"1571676941.0"}' exec_time
None
```

----

```
mbp:ccxt igorkroitor$ python3
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> "1571676941.70682".isnumeric()
False
```

This is the cause  ↑

**Comment by kroitor** [comment]
@Herklos i will add a workaround for it shortly, thx for reporting it!

**Comment by Herklos** [comment]
> @Herklos i will add a workaround for it shortly, thx for reporting it!

Thanks !

**Comment by kroitor** [comment]
@Herklos thx to you for the feedback! The new build is on the way on Travis CI and will arrive in 15 minutes. So it should work fine in CCXT version 1.24.58+. Let us know if you have any further questions or difficulties with it.
