### ISSUE TITLE
How to properly stop ccxt.pro

### ISSUE THREAD

**Issue by davidmasin** [ccxt/ccxt#6647]
Hi,

When I use websockets in ccxt pro and return from function where I instantiated ccxt.pro, code remains running, probably due to some async function (open websocket connection?) in macro-task event loop. 

This did not happen in basic ccxt, where calling all functions with await guaranteed that once the results are back, there is no remaining macro-task running. 

What is proper way to close all connections and exit the code?

Thanks

**Comment by kroitor** [comment]
Hi!

> This did not happen in basic ccxt, where calling all functions with await guaranteed that once the results are back, there is no remaining macro-task running.

Right, this is explained in the Pro Manual: https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual#streaming-specifics

In general this is one of the key differences between WS and REST – with WS you have greater speeds, but you have to maintain the connection. With REST the connection is reestablished and closed upon every request, which makes it harder

You can simply use

```JavaScript
    await exchange.close ()
```

when you don't need the instance and the underlying connection anymore.

```
'use strict';

const ccxtpro = require ('ccxt.pro');

(async () => {

    const exchange = new ccxtpro.binance ({ enableRateLimit: true })

    await exchange.loadMarkets ()

    exchange.verbose = true

    const symbol = 'BTC/USDT'

    for (let i = 0; i < 10; i++) {
        try {
            const orderbook = await exchange.watchOrderBook (symbol)
            console.log (new Date (), symbol, orderbook['asks'][0], orderbook['bids'][0])
        } catch (e) {
            console.log (symbol, e)
            // do nothing and retry on next loop iteration
            // throw e // uncomment to break all loops in case of an error in any one of them
            // break // you can also break just this one loop if it fails
        }
    }

    await exchange.close ()

    console.log ('Done.')
    process.exit ()

}) ()
```

We are also going to unify a subset of methods for unsubscribing, though, not all exchanges have it. There will be `unwatchOrderBook`, `unwatchTicker`, etc, soon. Will keep you updated on our progress.

Let us know if the above does not help.

**Comment by davidmasin** [comment]
Great, thanks, this is what I needed. Regards
