### ISSUE TITLE
After recent upgrade, cryptopia gives `Cannot read property 'symbol' of undefined` 

### ISSUE THREAD

**Issue by kvz** [ccxt/ccxt#665]
```
Nov 24 09:04:22 cryptal bash[26140]: Tickfetcher: TypeError: Cannot read property 'symbol' of undefined
Nov 24 09:04:22 cryptal bash[26140]:     at cryptopia.fetchTickers (/srv/cryptal/releases/20171123131420Z/node_modules/ccxt/js/cryptopia.js:198:32)
Nov 24 09:04:22 cryptal bash[26140]:     at <anonymous>
Nov 24 09:04:22 cryptal bash[26140]:     at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by kroitor** [comment]
Hi! Which pair is it?

**Comment by kvz** [comment]
I’m fetching all ticks for all pairs here

**Comment by kroitor** [comment]
@kvz, oh, yes, sorry, my bad. I'll take a look into it.

**Comment by kroitor** [comment]
@kvz are you sure that this issue is repeatable? I just tried fetching all tickers and it worked with current JS version.

**Comment by kroitor** [comment]
I added an assertion for that error, please update to version 1.10.202. We will keep a close eye on it to see if and why it reappears. Thx!

**Comment by kvz** [comment]
That fixed it, thanks!

--
Kevin van Zonneveld (kvz.io)
Co-founder at Transloadit (transloadit.com)
Core-author of tus (tus.io)
