### ISSUE TITLE
okex private API URL override TypeError: string indices must be integers

### ISSUE THREAD

**Issue by homily** [ccxt/ccxt#6651]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the link, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Please make sure your local version of ccxt is up to date with this repo. You can check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:Windows 10
- Programming Language version: Python 3.8
- CCXT version: 1.24.64
- Exchange: OKEX
- Method: BTC-USD-200626

when i use the private api

exchange.futures_get_accounts_underlying({'underlying':currency})

return error

File "C:\Users\homily\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\okex.py", line 2847, in sign
    url = self.implode_params(self.urls['api']['rest'], {'hostname': self.hostname}) + request
TypeError: string indices must be integers

![image](https://user-images.githubusercontent.com/22285236/77133810-6a100300-6a9f-11ea-81b6-b90a301c0737.png)

**Comment by kroitor** [comment]
@homily are you overriding the api url in your constructor arguments?

**Comment by kroitor** [comment]
@homily Can you paste your code used to initialize the exchange (without your keys, of course) ?

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/FAQ

**Comment by kroitor** [comment]
@homily if you do this in your code ↓

```
exchange = ccxt.okex({
    'urls': {
        'api': '...',
    },
})
```

↑ change this to this ↓

```
exchange = ccxt.okex({
    'urls': {
        'api': {
            'rest': '...',
        },
    },
})
```

Let us know if that does not help or does not answer the question.

**Comment by homily** [comment]
> @homily if you do this in your code ↓
> 
> ```
> exchange = ccxt.okex({
>     'urls': {
>         'api': '...',
>     },
> })
> ```
> 
> ↑ change this to this ↓
> 
> ```
> exchange = ccxt.okex({
>     'urls': {
>         'api': {
>             'rest': '...',
>         },
>     },
> })
> ```
> 
> Let us know if that does not help or does not answer the question.
> 
> P.S. in general you dont' really want to hardcode the URL override.



hi ,   i'm try use   'api': '...',

now   i change it

`def GETEXCHANGE(config):
    exchange = ccxt.okex3({
        'apiKey': config['USER-INFO']['APIKEY'],
        'secret': config['USER-INFO']['SECRET'],
        'password': config['USER-INFO']['PASSWORD'],
        'enableRateLimit': True,

        'urls': {
            'api': {
                'rest':"https://www.okex.me",
                }
            },
        #"options": {"fetchMarkets": ["spot"]},
        #'verbose': True,#了解更多细节
        })
    return(exchange)

but ,   return 


File "C:\Users\homilychen\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\base\exchange.py", line 483, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: okex3 {"error_message":"OK-ACCESS-KEY header is required","code":30001,"error_code":"30001","message":"OK-ACCESS-KEY header is required"}

thanks,

**Comment by kroitor** [comment]
@homily ok, got it, please, update to the most recent version 1.24.66 (it will arrive in 15 minutes when the automatic build is finished) and then let me know if you still have the same issue or if it s resolved on your side now. Standing by for a followup from you.

**Comment by homily** [comment]
> @homily ok, got it, thank you! I've uploaded a fix for it. Please, update to the most recent version 1.24.66 (it will arrive in 15 minutes when the automatic build is finished) and then let me know if you still have the same issue or if it is resolved on your side now. Standing by for a followup from you.

wow. thanks ,     so so  fast.   very thanks.

**Comment by kroitor** [comment]
@homily the new version 1.24.66 has arrived, we will be happy if you let us know whether this issue is resolved for you now.

**Comment by kroitor** [comment]
Feel free to reopen this if needed or just ask further questions if any.

Two **very important** things to note for you:

1. You don't really want to change the URL that way. It is easier to just override the `hostname` as shown below:

```Python
exchange = ccxt.okex({
    'hostname': 'okex.me',
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'password': 'YOUR_PASSWORD,
    # ...
})
```

↑ This will work **much-much** better, especially if you later decide to switch to using [OKEX WebSocket API with CCXT Pro]().

2. For the future – feel free to open issues, your feedback is welcome, but when posting the issue, please always paste your code to reproduce the issue without your keys and also your **verbose output**. Read this very-very carefully: https://github.com/ccxt/ccxt/wiki/FAQ#im-trying-to-run-the-code-but-its-not-working-how-do-i-fix-it. There is a few simple rules – if you follow them, we will be able to resolve most of the issues very quickly. If you don't follow them – then solving a problem will simply take a lot more of your own time. Always use [GitHub markdon]() to format the code and output for readability. Surround your code and output with triple backticks (&#096;&#096;&#096;) like shown below:

&#096;&#096;&#096;Python
YOUR CODE
&#096;&#096;&#096;

---

&#096;&#096;&#096;
YOUR OUTPUT
&#096;&#096;&#096;

**Comment by homily** [comment]
ok ,   i got it. i'm changed hostname and updated Ver , now ccxt work very well. thanks.!
