### ISSUE TITLE
Binance `quoteOrderQty` should use `amount_to_precision` instead of `cost_to_precision`?

### ISSUE THREAD

**Issue by vakker** [ccxt/ccxt#6654]
- OS: N/A
- Programming Language version: Python 3.7
- CCXT version: 1.24.37

Let's say I have 29.98600029 USDT on my account and I want to buy BTC and I'm using the `quoteOrderQty` param:
```python
binance.create_market_buy_order('BTC/USDT', amount=None, params={'quoteOrderQty': 29.98600029})
```

Then I get:
```python
InsufficientFunds: binance Account has insufficient balance for requested action.
```

In the code after [this](https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L1046) it uses `cost_to_precision` instead of `amount_to_precision` (in two places), which I think should be `cost_to_precision` as in my case it rounds it up, which is not correct.

**Comment by kroitor** [comment]
@vakker thx for reporting! I've uploaded the fix, please try updating to version 1.24.70 in 15 minutes when the build arrives. We will be happy if you let us know whether the issue is resolved on your side or not.

**Comment by vakker** [comment]
@kroitor thanks for the quick fix
Now it gives me:
```
File "/home/vince/miniconda3/envs/trading/lib/python3.7/site-packages/ccxt/binance.py", line 1047, in create_order
    precision = market['price']['precision']
KeyError: 'price'
```

Shouldn't it be:
```python
precision = market['precision']['price']
```

**Comment by kroitor** [comment]
@vakker yes, sorry, my bad, i've added one more fix for it. Thank to you and to @eburnette for reporting!
