### ISSUE TITLE
Binance 0ms orderbook error  - out of order nonce

### ISSUE THREAD

**Issue by icytrader** [ccxt/ccxt#6658]
When I start watch binance futures orderbook at 0ms rate( real-time), I frequently get an out-of-order nonce error from time to time. It rarely happens with 100ms rate.

I attached the verbose for one the the occurance in the attachment for your review. Thanks.

- OS: Windows
- Programming Language version: NodeJS
- CCXT version: Pro

```
bnPro.verbose = true;
bnPro.options['defaultType'] = 'future';
bnPro.options['watchOrderBookRate'] = 0;


(async()=>{
    let ob = undefined
    while(true){
        ob = await bnPro.watchOrderBook('BTC/USDT')
        console.log(ob.limit(1))
    }
```

```
YOUR OUTPUT / ERROR / EXCEPTION IN TEXT, NO SCREENSHOTS
```
[verbose.txt](https://github.com/ccxt/ccxt/files/4363164/verbose.txt)

**Comment by kroitor** [comment]
@icytrader a quick question to you – does it happen upon your first call to `watchOrderBook` or in do you also see this later on after the subscribing?

**Comment by frosty00** [comment]
i mean the error is straight forward `TypeError: Cannot read property 'cache' of undefined`

**Comment by frosty00** [comment]
i think the error is happening because the first ws message is coming back before the spawn method returns

**Comment by kroitor** [comment]
@frosty00 

> i mean the error is straight forward TypeError: Cannot read property 'cache' of undefined

it isn't that straightforward, though, because the `cache` error is a consequence of the actual error with the nonce

> i think the error is happening because the first ws message is coming back before the spawn method returns

It should have received the subscription confirmation first, though. The actual nonce error is a bit difficult to catch, because it does not occur all the time, just occasionally.

**Comment by kroitor** [comment]
@frosty00 also, what's interesting, neither of BInance official sources has the implementation of their u/U/pu nonce logic, described in their spot WS api doc and in their futures WS api doc.

**Comment by kroitor** [comment]
In other words, Binance's own samples don't check the nonce. At all.

**Comment by kroitor** [comment]
You won't find this:

- https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#how-to-manage-a-local-order-book-correctly
- https://binance-docs.github.io/apidocs/futures/en/#how-to-manage-a-local-order-book-correctly

anywhere here:

- https://github.com/Binance-docs/Binance_Futures_python
- https://github.com/Binance-docs/Binance_Futures_Java
- https://github.com/binance-exchange

**Comment by icytrader** [comment]
> @icytrader a quick question to you – does it happen upon your first call to `watchOrderBook` or do you also see this later on after subscribing?

@kroitor  HI! It is usually the first call. I think the problem occurs at processing the first delta after the compelete snapshot.

**Comment by kroitor** [comment]
@icytrader thank you, i was just uploading the fixes, please try CCXT Pro 0.0.101 in 20 minutes – this should be resolved. We haven't seen it after adding those edits. Will be happy if you report back, whether this is resolved. Thx again for your feedback, appreciate your involvement!

**Comment by icytrader** [comment]
i&nbsp;have updated the Pro version and I can confirm that it wors well now. Thanks!




------------------&nbsp;Original&nbsp;------------------

**Comment by kroitor** [comment]
@icytrader it's too early, that build will arrive in 20 minutes or so ) But thanks for reporting )

**Comment by nelso0** [comment]
hi! after getting subscribed for 1-2 days non-stop (and doing exchange.close() frequently to re-subscribe), my program gets this error. Would it work if I just catch the error as Exception, close, and just break the loop to do the next one?
