### ISSUE TITLE
[coinmate] fees enhancement

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6663]
The connate fees page (https://coinmate.io/fees) is driven by this url: https://coinmate.io/guirest/fees/tradeFeeValues.  Can we incorporate just eh basic fee info it into ccxt?

```
[
   {
      "feeZones":[
         {
            "makerFeeValue":0.12,
            "takerFeeValue":0.25,
            "tradingVolume":10000,
            "applyMakerReferral":true,
            "applyTakerReferral":true
         },
         {
            "makerFeeValue":0.11,
            "takerFeeValue":0.23,
            "tradingVolume":100000,
            "applyMakerReferral":true,
            "applyTakerReferral":true
         },
         {
            "makerFeeValue":0.1,
            "takerFeeValue":0.21,
            "tradingVolume":250000,
            "applyMakerReferral":true,
            "applyTakerReferral":true
         },
         {
            "makerFeeValue":0.08,
            "takerFeeValue":0.2,
            "tradingVolume":500000,
            "applyMakerReferral":true,
            "applyTakerReferral":true
         },
         {
            "makerFeeValue":0.05,
            "takerFeeValue":0.15,
            "tradingVolume":1000000,
            "applyMakerReferral":true,
            "applyTakerReferral":true
         },
         {
            "makerFeeValue":0.03,
            "takerFeeValue":0.13,
            "tradingVolume":3000000,
            "applyMakerReferral":true,
            "applyTakerReferral":true
         },
         {
            "makerFeeValue":0.02,
            "takerFeeValue":0.1,
            "tradingVolume":15000000,
            "applyMakerReferral":true,
            "applyTakerReferral":true
         },
         {
            "makerFeeValue":0,
            "takerFeeValue":0.05,
            "tradingVolume":null,
            "applyMakerReferral":true,
            "applyTakerReferral":true
         }
      ],
      "name":"Standard",
      "currencyPairs":[
         {
            "id":1,
            "name":"BTC/EUR"
         },
         {
            "id":2,
            "name":"BTC/CZK"
         },
         {
            "id":5,
            "name":"LTC/EUR"
         },
         {
            "id":6,
            "name":"LTC/CZK"
         },
         {
            "id":3,
            "name":"LTC/BTC"
         },
         {
            "id":18,
            "name":"BTC/$DAI"
         },
         {
            "id":19,
            "name":"$DAI/EUR"
         },
         {
            "id":20,
            "name":"ETH/$DAI"
         }
      ]
   },
   {
      "feeZones":[
         {
            "makerFeeValue":0.05,
            "takerFeeValue":0.15,
            "tradingVolume":10000,
            "applyMakerReferral":true,
            "applyTakerReferral":true
         },
         {
            "makerFeeValue":0.04,
            "takerFeeValue":0.14,
            "tradingVolume":100000,
            "applyMakerReferral":true,
            "applyTakerReferral":true
         },
         {
            "makerFeeValue":0.03,
            "takerFeeValue":0.13,
            "tradingVolume":250000,
            "applyMakerReferral":true,
            "applyTakerReferral":true
         },
         {
            "makerFeeValue":0.02,
            "takerFeeValue":0.12,
            "tradingVolume":500000,
            "applyMakerReferral":true,
            "applyTakerReferral":true
         },
         {
            "makerFeeValue":0,
            "takerFeeValue":0.11,
            "tradingVolume":1000000,
            "applyMakerReferral":true,
            "applyTakerReferral":true
         },
         {
            "makerFeeValue":0,
            "takerFeeValue":0.1,
            "tradingVolume":3000000,
            "applyMakerReferral":true,
            "applyTakerReferral":true
         },
         {
            "makerFeeValue":0,
            "takerFeeValue":0.08,
            "tradingVolume":15000000,
            "applyMakerReferral":true,
            "applyTakerReferral":true
         },
         {
            "makerFeeValue":0,
            "takerFeeValue":0.05,
            "tradingVolume":null,
            "applyMakerReferral":true,
            "applyTakerReferral":true
         }
      ],
      "name":"Promotional",
      "currencyPairs":[
         {
            "id":9,
            "name":"ETH/EUR"
         },
         {
            "id":10,
            "name":"ETH/CZK"
         },
         {
            "id":11,
            "name":"ETH/BTC"
         },
         {
            "id":12,
            "name":"XRP/EUR"
         },
         {
            "id":13,
            "name":"XRP/CZK"
         },
         {
            "id":14,
            "name":"XRP/BTC"
         },
         {
            "id":15,
            "name":"DASH/EUR"
         },
         {
            "id":16,
            "name":"DASH/CZK"
         },
         {
            "id":17,
            "name":"DASH/BTC"
         },
         {
            "id":7,
            "name":"BCH/EUR"
         },
         {
            "id":8,
            "name":"BCH/CZK"
         },
         {
            "id":4,
            "name":"BCH/BTC"
         }
      ]
   }
]
```

**Comment by kroitor** [comment]
> Can we incorporate just eh basic fee info it into ccxt?

Every time we do this, they change their website engine, and the endpoint breaks down since it's not a documented API, thus not guaranteed to work... But we can try.

**Comment by npomfret** [comment]
I'll try and do this today.  Do I need to define a whole new api section as it's url is different?

**Comment by kroitor** [comment]
> Do I need to define a whole new api section as it's url is different?

Yep, otherwise it will get messy really quick

**Comment by npomfret** [comment]
Could get it to work, the page is protected for some reason.

**Comment by npomfret** [comment]
@kroitor however, the hard coded fees are wrong.  Would you accept a PR that had correct hard coded values?

**Comment by kroitor** [comment]
@npomfret yep, see how that's done with the `'fees'` in `describe()` for the other exchanges.

**Comment by npomfret** [comment]
So Zaif and bitflyer have some per-market settings for trade fees, is that the recommended approach?

It might be nice in this case to be able to supply _categories_.  Such as:

```
            'fees': {
                'default': {
                    'trading': {
                        'maker': 0.12 / 100,
                        'taker': 0.25 / 100,
                    },
                },
                'promotional': {
                    'trading': {
                        'maker': 0.05 / 100,
                        'taker': 0.15 / 100,
                    },
                },
            },

```

... and then some way to specify which markets are in the _promotional_ category.

**Comment by npomfret** [comment]
@kroitor what do you think to this:
            'fees': {
                'tierBased': true,
                'percentage': true,
                'default': {
                    'trading': {
                        'maker': 0.12 / 100,
                        'taker': 0.25 / 100,
                        'tiers': {
                            'taker': [
                                [0, 0.25 / 100],
                                [10000, 0.23 / 100],
                                [100000, 0.21 / 100],
                                [250000, 0.20 / 100],
                                [500000, 0.15 / 100],
                                [1000000, 0.13 / 100],
                                [3000000, 0.10 / 100],
                                [15000000, 0.05 / 100],
                            ],
                            'maker': [
                                [0, 0.12 / 100],
                                [10000, 0.11 / 100],
                                [1000000, 0.10 / 100],
                                [250000, 0.08 / 100],
                                [500000, 0.05 / 100],
                                [1000000, 0.03 / 100],
                                [3000000, 0.02 / 100],
                                [15000000, 0],
                            ],
                        },
                    },
                },
                'promotional': {
                    'trading': {
                        'maker': 0.05 / 100,
                        'taker': 0.15 / 100,
                        'tiers': {
                            'taker': [
                                [0, 0.15 / 100],
                                [10000, 0.14 / 100],
                                [100000, 0.13 / 100],
                                [250000, 0.12 / 100],
                                [500000, 0.11 / 100],
                                [1000000, 0.1 / 100],
                                [3000000, 0.08 / 100],
                                [15000000, 0.05 / 100],
                            ],
                            'maker': [
                                [0, 0.05 / 100],
                                [10000, 0.04 / 100],
                                [1000000, 0.03 / 100],
                                [250000, 0.02 / 100],
                                [500000, 0],
                                [1000000, 0],
                                [3000000, 0],
                                [15000000, 0],
                            ],
                        },
                    },
                },
            },

**Comment by kroitor** [comment]
@npomfret i would rather not support temporary things, so i would remove `promotional` and the subdivision there, leaving just the `default` (`fees → trading` instead of `fees → default → trading` like we have everywhere else).

**Comment by npomfret** [comment]
So where would I put the promotional stuff?

**Comment by kroitor** [comment]
If we absolutely need it, I'd suggest 

- fees → trading (equals the default) – for compatibility
- fees → default → trading
- fees → promotional → trading

However, to my mind PR #6684 is very fine.

**Comment by npomfret** [comment]
Ok, thanks.  So I added `fees → promotional → trading`.  And where do you think I should put the market list for the promotional markets?

**Comment by kroitor** [comment]
@npomfret i would put that list under options, and inside fetchMarkets I would look up the market in that list inside options and would substitute default maker/taker fees with promotional fees upon parsing the market if the market is found on that list.

**Comment by npomfret** [comment]
@kroitor ok - pls take a look? #6684
