### ISSUE TITLE
Add Kucoin Margin support

### ISSUE THREAD

**Issue by willoughby** [ccxt/ccxt#6665]
API Docs: https://docs.kucoin.com/#margin-info

**Comment by pavitrakumar78** [comment]
Any update on this? Is margin trade fetching for kucoin now available via ccxt?

**Comment by ttodua** [comment]
in addition to above referenced PR, kucoin at this moment has different margin functionalities available. Please check it and if you miss any specific unified functionality, feel free to re/open the issue, mentioning the specific endpoint/functionality you have issues with.

**Comment by Kgauza** [comment]
How do I buy/sell short orders from margin account using ccxt in kucoin?
