### ISSUE TITLE
New Exchange: Kumex (KuCoin Futures)

### ISSUE THREAD

**Issue by willoughby** [ccxt/ccxt#6666]
API Docs: https://docs.kumex.com/#general

**Comment by qmzik** [comment]
Wait for it too

**Comment by zsyh** [comment]
KuMEX already renamed to KuCoin Futures.  See  https://www.kucoin.com/news/en-kucoin-futures-brand-upgrade

**Comment by kroitor** [comment]
Kucoin Futures has been added in CCXT 1.65.30+.
