### ISSUE TITLE
FetchMyTrades show old data.

### ISSUE THREAD

**Issue by Arrmlet** [ccxt/ccxt#6667]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- Windows 10:
- Python 3.8.2:
- newest:

Hello there,
I have issue with FetchMyTrades() method on bitmex exchange, it returns me old data. 
When I tried a use "since" attribute program returns error.
How to get data for one last day? I tried reformat data into unix and iso608 time, but without results.
```
YOUR CODE TO REPRODUCE THE ISSUE WITHOUT YOUR KEYS
```
def fills(exchange, symbol):
    d = datetime.now() - timedelta(days=1)
    d = (time.mktime(d.timetuple()))
    print(d, [...])
    fills = exchange.fetchMyTrades(symbol = symbol, since = d)

if __name__ == '__main__':
    e = load_exchange('real')
    fills(e, 'BTC/USD')
```
ccxt.base.errors.BadRequest: bitmex {"error":{"message":"startTime is invalid","name":"HTTPError"}}
```

**Comment by kroitor** [comment]
Hi!

> How to get data for one last day?
> I tried reformat data into unix and iso608 time, but without results.

This is described here:

- https://github.com/ccxt/ccxt/wiki/Manual#date-based-pagination

The `since` argument should be an integer timestamp in milliseconds, which you can obtain in many ways:

1. multiply a unix timestamp by 1000
    ```
    exchange.fetchMyTrades (symbol, unix_timestamp_in_seconds * 1000)
    ```
2. subtract 86400000 from the current timestamp in milliseconds
    ```
    second = 1000  # milliseconds
    minute = 60 * second
    hour = 60 * minute
    day = 24 * hour
    now = exchange.milliseconds ()
    exchange.fetchMyTrades (symbol, now - day)
    ```
3. parse an iso8601 date:
    ```
    exchange.fetchMyTrades (symbol, exchange.parse8601 ('2020-03-23T19:00:00Z'))
4. ...

Also:

- https://github.com/ccxt/ccxt/wiki/Manual#working-with-datetimes-and-timestamps

Let us know if that does not answer the question.

**Comment by Arrmlet** [comment]
@kroitor 
Thanks a lot dude.
