### ISSUE TITLE
binance.createMarketBuyOrder fails with message 'Cannot read property 'precision' of undefined'.

### ISSUE THREAD

**Issue by dmitriano** [ccxt/ccxt#6668]
OS: Windows 10
Programming Language version: JavaScript v8.12.0
CCXT version: 1.24.70
Exchange: binance
Method: exchange.createMarketBuyOrder

My code where the error occurs:

exchange.createMarketBuyOrder('ETH/USD', 0.5);

The exceptions is thrown at 'binance.js' line 1104 because `market['price']` is undefined.
Error message is: 'Cannot read property 'precision' of undefined '

**Comment by kroitor** [comment]
Please update to the most recent version and let us know if that helps.
This issue has been addressed here: https://github.com/ccxt/ccxt/issues/6654
