### ISSUE TITLE
FTX - conditional orders fetch_orders

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#6669]
- OS: linux
- Programming Language version: python
- CCXT version: 1.23.81
- exchange: FTX

I can easily create a "triggered order" by providing "stop" as type.

``` python
import ccxt
ct = ccxt.ftx()
order = ct.create_order('BNB/USD, 'stop', 'sell', amount=0.4, price=11)
order
```

CCXT abstracts this wonderfully away, so i basically don't have to do anything.
However, getting this order back does not work.

``` python
ct.fetch_order(order_id) 

> Error: ftx {"error":"Order not found","success":false}
```

According to the [docs](https://docs.ftx.com/#get-open-trigger-orders) - this should go to the endpoint 'conditional_orders' - however it's not, and the ccxt code does not suggest how to get this order "back".

are there any parameters which can be provided to `fetch_order()` to get the order just created "back"?

Thanks in advance

**Comment by kroitor** [comment]
> are there any parameters which can be provided to fetch_order() to get the order just created "back"?

We will add a user control for that aspect shortly, thx for pointing it out.

**Comment by kroitor** [comment]
Alright, this has been added in CCXT 1.24.93+.

There is now several supported methods for overriding that endpoint:

1. With exchange-wide options (though this is less convenient, since you often have to manage both regular orders and conditional orders):

    ```Python
    import ccxt
    exchange = ccxt.ftx({
        'enableRateLimit': True,
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_API_SECRET',
        'options': {
            'cancelOrder': {
                # 'method': 'privateDeleteOrdersOrderId',  # limit orders, default
                'method': 'privateDeleteConditionalOrdersOrderId',  # conditional orders
            },
        },
    })

2. [Overriding the method in `params`](https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params):

    ```Python
    result = exchange.cancel_order(order_id, None, {'method': 'privateDeleteConditionalOrdersOrderId'})
    ```

3. If you have the unified order structure at hand, you can also use the order's `type` to help CCXT decide which endpoint to use:

    ```Python
    result = exchange.cancel_order(order['id'], None {'type': order['type']})
    ````

I would recommend to stick to (3), since this is the most portable and most convenient way to use it, and it allows you to control the action precisely.

Let me know if that does not help or if you have any issues or difficulties with it. Thanks for your feedback!

**Comment by xmatthias** [comment]
the fix applies to `cancel_order` only (where it's needed too for sure - i just didn't get to that yet).
 
but it seems to be missing from `fetch_order()` - so before cancelling an order i'd like to know if it did trigger in the meantime ... :smile:

**Comment by kroitor** [comment]
@xmatthias sorry missed that spot, will upload it shortly.

**Comment by kroitor** [comment]
@xmatthias one thing to clarify – there is no endpoint for fetching a single conditional order by id – did you mean `fetch_orders()` ?

**Comment by xmatthias** [comment]
I'm not 100% sure - but ["Get trigger order triggers"](https://docs.ftx.com/#get-trigger-order-triggers) seem to suggest that it is possible to get a conditional order's status by id:

```
GET /conditional_orders/<conditional_order_id>/triggers
```

Now the example and documentation don't really align  (documentation suggests a field is "orderSize", while the samle shows "size" as fieldname ... ) - but that's a different problem alltogether.


Now to be honest, my main method to communicate to exchange API's (especially for ones that require authentication) is through ccxt - so i might be wrong since i didn't really try this call just yet.

**Comment by kroitor** [comment]
> I'm not 100% sure - but ["Get trigger order triggers"](https://docs.ftx.com/#get-trigger-order-triggers) seem to suggest that it is possible to get a conditional order's status by id:
> 
> ```
> GET /conditional_orders/<conditional_order_id>/triggers
> ```

This is the cause of the confusion – that endpoint does not return the conditional orders themselves. Instead for a conditional id that endpoint returns the list of events (prices, timestamps and values) that triggered that conditional order _"to fire"_. 

Those events are called _"triggers"_ and they are related to conditional orders in a way similar to how trades relate to regular orders. In other words, those triggers make some internal part of the order info, but not the entire conditional order itself... 

Unfortunately, FTX does not have an endpoint for a specific conditional order by id that would correspond to `fetchOrder`. I've tried `/conditional_orders/<conditional_order_id>` but that does not work. 

Let me know if that does not answer the question. Thx!

**Comment by xmatthias** [comment]
ah thanks, that explains this part, thanks

then it's however still missing in `fetch_open_orders()` - unless i've overlooked a `fetch_open_trigger_orders()` method - but i don't think that would align to ccxt methodology...

```
ct.request('conditional_orders?market={market}', api='private', method='GET', params={'market': 'BNB/USD'})


> {'result': [{'avgFillPrice': None,
   'cancelReason': None,
   'cancelledAt': None,
   'createdAt': '2020-03-25T08:14:56.635508+00:00',
   'error': None,
   'filledSize': 0.0,
   'future': None,
   'id': 972250,
   'market': 'BNB/USD',
   'orderId': None,
   'orderPrice': None,
   'orderType': 'market',
   'reduceOnly': False,
   'retryUntilFilled': False,
   'side': 'sell',
   'size': 0.4,
   'status': 'open',
   'trailStart': None,
   'trailValue': None,
   'triggerPrice': 11.0,
   'triggeredAt': None,
   'type': 'stop'}],
 'success': True}
```

(sorry for beeing a pain)

**Comment by kroitor** [comment]
> then it's however still missing in `fetch_open_orders()`

Yes, will add that shortly and `fetch_orders` as well.

**Comment by kroitor** [comment]
Added it for fetch_orders and fetch_open_orders in 1.24.95+. Thank you again!

**Comment by xmatthias** [comment]
Something seems not right (although i've been looking at the code now for a few minutes and can't figure out what).

to my understanding, using `ct.fetch_orders('BNB/USD')` should show `orders/history` (it seems to to that by looking at the code, but not when actually running it) - and `ct.fetch_open_orders('BNB/USD')` should got to the "non-history" endpoint.

My setup does not modify anything on the internals of ccxt (i know i can break anything if i start overwriting stuff ...)

```
import ccxt
ct = ccxt.ftx({<mykeys>})
ct.load_markets()
ct.verbose=True
ct.fetch_orders('BNB/USD')
> Request: GET https://ftx.com/api/orders?market=BNB%2FUSD {'FTX-KEY': 'XXXXX', 'FTX-TS': '1585132188883', 'FTX-SIGN': 'YYYYY', 'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate'} None

ct.fetch_open_orders('BNB/USD')

> Request: GET https://ftx.com/api/orders?market=BNB%2FUSD {'FTX-KEY': 'XXXXX', 'FTX-TS': '1585132227185', 'FTX-SIGN': 'YYYYYY', 'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate'} None

ct.options
> {'cancelOrder': {'method': 'privateDeleteOrdersOrderId'},
 'fetchOpenOrders': {'method': 'privateGetOrders'},
 'fetchOrders': {'method': 'privateGetOrdersHistory'}}

ccxt.__version__
'1.24.95'
```

**Comment by kroitor** [comment]
@xmatthias plz try again with 1.24.96 (It's already available, a minor typo, my bad, pardon for the inconvenience.

**Comment by xmatthias** [comment]
Works now - i've updated half an hour ago ... it's been fixed 17 minutes ago ... didn't expect a fix that quickly ... :(

**Comment by kroitor** [comment]
@xmatthias yep, sorry, i'll try to pay more attention.

**Comment by xmatthias** [comment]
no worries :+1:

**Comment by ProStrike-hub** [comment]
> 

Hello @xmatthias !

I think I'm having the same issue you had a while back! 
You're trying to fetch order (conditional / trigger ones) to detect when a TP/SL has been filled and canceled the opposite awaiting TP/SL order... 

I didn't quite get your last EDIT. 
Does this code did the work? assuming we're trying to reach the same goal
I can see you're calling FTX API in the middle of CCXT lib, but I'm not sure what's the point... 

Apparently, you found a turn around. I'll appreciate if you can clarify how. 
Thanks in advance!

**Comment by xmatthias** [comment]
@ProStrike-hub i'm not quite sure i get your point.

this issue was about fetching and cancelling conditional orders - from 2 years ago.
as far as i know, it's still working as expected (i use this pretty regularily).

**Comment by ProStrike-hub** [comment]
@xmatthias were trying to do the same thing. 

But I didn’t understand your code. Could you please explain it a little bit?

**Comment by xmatthias** [comment]
All code i provided in this issue is single line examples only. 
There's nothing to explain, really.

**Comment by ProStrike-hub** [comment]
I'm asking cause I tried your code (I also want to fetch & cancel conditional orders) but it doesn't work. _Please see screenshot attached._ 
![Untitled](https://user-images.githubusercontent.com/76970433/197165285-6bbbdcda-04a6-4545-a1a2-ab792bc7505f.png)

**Comment by ProStrike-hub** [comment]
@xmatthias I'm asking cause I tried your code (I also want to fetch & cancel conditional orders) but it doesn't work. _Please see screenshot attached._ 
![Untitled](https://user-images.githubusercontent.com/76970433/197165497-4dd7e837-cba3-4918-ad16-afcded9714d4.png)

**Comment by xmatthias** [comment]
every line starting with `>` is output - running this will clearly not work as it's simply invalid syntax.
