### ISSUE TITLE
HitBTC clientOrderID

### ISSUE THREAD

**Issue by nmiculinic** [ccxt/ccxt#667]
I've seen in the code clientOrderID is in milliseconds. Per documentation, it's a string. Could you change it to UUID?

Python code:

```python
>>> import uuid
>>> str(uuid.uuid4())
'fb076e7f-0e06-4a0e-ba24-e284ac68619a'
```

**Comment by kroitor** [comment]
@nmiculinic it's currently a milliseconds string, does switching it to UUID make any difference?

**Comment by nmiculinic** [comment]
Yes; since UUID is by definition universally unique identifier. When cross matching orders, I'd rather prefer UUIDs, then having to check for rare condition where two order from different exchanges is executed into the same millisecond. (or some other objects; uuid's are cool).

**Comment by kroitor** [comment]
Switched to UUIDs in 1.10.205. Thx!
