### ISSUE TITLE
Separate HTTPS verbose and WSS verbose modes

### ISSUE THREAD

**Issue by icytrader** [ccxt/ccxt#6673]
I think it would be good to be able to seperately configure the verbose for http request and wss streaming data. Often I only intend to debug the http request behaviour, like order placement. however the output from real-time streaming data can be tremendous. 

Can we add seperate configuration at the base exchange class so we can do sth like

```
let binance  = ccxt.binance({ rest_verbose: true, wss_verbose: false}) 
```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

**Comment by kroitor** [comment]
@icytrader they in fact already allow you to do this, with the following syntax (will document it in the Manual soon):

```Python
binance = new ccxt.binance({
    'verbose': True,
    'options': {
        'ws': { 'verbose': False },
    },
})
```

Let us know if that does not help or if you wanted something different. Thx for your feedback!
