### ISSUE TITLE
amount limits for okex futures contracts

### ISSUE THREAD

**Issue by icytrader** [ccxt/ccxt#6675]
Hi,

Please correct me if I am wrong in understanding the amount limits.  I think we should have limits - amount -  min field for okex futures and swap contracts -- currently undefined. For futures it should equal to be trade_increment field in the raw info returned by exchange, for swap that should be the size_increment field. 

This field is more important for their USDT denominated future contracts ,where the amount limit is arbitrary set for different contracts and not equal to 1 lot. 

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

**Comment by ttodua** [comment]
okx is already filled with those fields at this moment. Closing the issue.
