### ISSUE TITLE
[coinmate] looks like its shutting down

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6680]
> Dear Coinmates,
>  
> 
> We regret to inform you that our company has been notified by FIO Bank of the cancellation of our company’s bank accounts effective March 30, 2020.
> 
> Important information about forthcoming operations:
> 
> The coinmate.io website will remain operational and client funds available for withdrawal.
>  
> Crypto and FIAT (EUR, CZK) client funds are 100% backed and the company is ready to settle all user balances in full.
>  
> We will stop accepting new bank deposits on 27.3.2020
>  
> Please withdraw your FIAT balance (EUR, CZK) until 30.3.2020 at the latest. All FIAT withdrawals will be limited after this date.
>  
> Trading on the exchange will remain operational but please be aware of the price, which on Coinmate trading pairs may become significantly different compared to the market price.
> We made tremendous efforts in recent months to establish a relationship with another banking institution in the Czech Republic and abroad but also due to the ongoing pandemic of coronavirus and recent Brexit, it is impossible for a British crypto exchange to open bank accounts within the EU under such circumstances.
> 
> Also due to the size of our exchange and current situation, we are unable to switch to a different business model under a non-UK company. This situation is all the more painful for us because COINMATE is one of the most reliable and best-rated crypto exchanges in the world. Our focus on security and user-friendliness paid off. We always preferred quality over quantity and our services have been based on honesty and fair dealing.
> 
> We are currently negotiating several options to establish a new banking partnership. If we are successful, we will recover our services in full.
> 
> Thank you for your support.
> 
> The Coinmate.io Team

**Comment by kroitor** [comment]
@npomfret i think, in short, it says _"no fiat anymore"_, but they will still operate and trade with crypto... or am I missing something?

**Comment by npomfret** [comment]
No, you are right.  It doesn't look great but they look they they are doing pure crypto markets still.
