### ISSUE TITLE
[DSX] new api

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6683]
https://api.dsxglobal.com

**Comment by npomfret** [comment]
Looks like the old API is completely dead and they won't turn it back on so we need a complete rewrite.  I have a glance at the new docs, and the shape of the data looked similar at least.  Maybe, if we're lucky, it's a case of redoing the urls and the auth (only basic auth is supported not) but not the parsers.

**Comment by kroitor** [comment]
Added in 1.28.12+.
