### ISSUE TITLE
How to use fetchCurrencies in fetchMarkets?

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6691]
If my `fetchMarkets` implementation relies on `fetchCurrenies` how do I access the currencies info (as it's not been set yet by `loadMarketsHelper` & `setMarkets`)

**Comment by kroitor** [comment]
To workaround this issue we add a helper that caches the currencies and invalidates the cache on a timeout to avoid fetching them twice in a short period of time:

CEX:

- https://github.com/ccxt/ccxt/blob/master/js/cex.js#L148
- https://github.com/ccxt/ccxt/blob/master/js/cex.js#L273
- https://github.com/ccxt/ccxt/blob/master/js/cex.js#L166

Coinbase:

- https://github.com/ccxt/ccxt/blob/master/js/coinbase.js#L506
- https://github.com/ccxt/ccxt/blob/master/js/coinbase.js#L560
- https://github.com/ccxt/ccxt/blob/master/js/coinbase.js#L578

In general we need to redesign the loadMarketsHelper a little bit to pass the loaded currencies to fetchMarkets().

**Comment by kroitor** [comment]
__

**Comment by npomfret** [comment]
Thanks, I think I understand.  Could you pls check https://github.com/ccxt/ccxt/pull/6689 to see if I've done it right?  ... no need to merge yet, more to do.

**Comment by kroitor** [comment]
@npomfret yep, it looks fine to me. Though, i don't see a reference to it in fetchMarkets, i suppose that you will add that later.
