### ISSUE TITLE
Order amend bitmex

### ISSUE THREAD

**Issue by Arrmlet** [ccxt/ccxt#6692]
- Windows:
- Python 3.8.2:
- newest:

Hello everyone.
How to amend the price of order on bitmex?
https://www.bitmex.com/api/explorer/#!/Order/Order_amend

**Comment by kroitor** [comment]
Hi!

Use the `editOrder` unified method:

- https://github.com/ccxt/ccxt/search?q=bitmex+editOrder&type=Issues

Let us know if that does not help.

**Comment by Arrmlet** [comment]
Thanks a lot!
