### ISSUE TITLE
Is it possible to only return the markets that are currently available on the exchange?

### ISSUE THREAD

**Issue by JanssensKobe** [ccxt/ccxt#6703]
Hello,
When I'm loading all markets from Binance with the function "load_markets" in python, I get also some markets that aren't available anymore (example: BTT/BTC). Is it possible to only return the markets that are currently available on the exchange?

- OS: Manjaro 5.4.27
- Programming Language version: Python
- CCXT version: ccxt-1.25.41

My code:
```python
print(list(binance.load_markets().keys()))
```

**Comment by kroitor** [comment]
Hi!

This is covered in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#market-structure

See the `active` field in each market.

```Python
import ccxt
exchange = ccxt.binance({'enableRateLimit': True})
exchange.load_markets()

active_symbols = [market['symbol'] for symbol, market in exchange.markets.items() if market['active']]

inactive_symbols = [market['symbol'] for symbol, market in exchange.markets.items() if not market['active']]

print('Active symbols:', active_symbols)
print('Inactive symbols:', inactive_symbols)
```

Let us know if that does not help.
