### ISSUE TITLE
ccxt-python: 'deribit' object has no attribute 'private_get_positions'

### ISSUE THREAD

**Issue by mycase** [ccxt/ccxt#6708]
- OS: Linux Fedora 31 
- Programming Language version:Python 3.8.1
- CCXT version: 1.25.41

```
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.deribit ({
    'enableRateLimit': True,
    'apiKey': 'XXXXX',
    'secret': 'YYYYY',
})
print(exchange.private_get_position())
```
Output:
```
CCXT Version: 1.25.41
Traceback (most recent call last):
  File "dev/deribit/Deribit6.py", line 10, in <module>
    print(exchange.private_get_position())
AttributeError: 'deribit' object has no attribute 'private_get_position'
```
- Same absence of attribute `private_get_positions`
- Note that the `fetch_balance` method mentioned [here](https://github.com/ccxt/ccxt/issues/6602#issuecomment-604432698) works without problems.
- Also note that the method used to be supported in v1, and no longer seems to be present in v2.
- From the [source](https://github.com/ccxt/ccxt/blob/master/python/ccxt/deribit.py) I was under the impression that this method is still meant to exist.

**Comment by kroitor** [comment]
Since deribit has changed their API version, all the method names for implicit API methods are changed as well, so it is now called:

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.deribit ({
    'enableRateLimit': True,
    'apiKey': 'XXXXX',
    'secret': 'YYYYY',
})
exchange.load_markets()
symbol = 'BTC/USD'
print(exchange.private_get_get_position({
    'instrument_name': 'BTC-PERPETUAL',
}))
```

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.deribit ({
    'enableRateLimit': True,
    'apiKey': 'XXXXX',
    'secret': 'YYYYY',
})
print(exchange.private_get_get_positions({
    'currency': 'BTC'
}))
```

> From the source I was under the impression that this method is still meant to exist.

Yes, but it has changed the name to `private_get_get_position` and also has changed the semantics (behavior). And another one called `private_get_get_positions` was added.

Let us know if that does not answer the question.

**Comment by mycase** [comment]
Thank you! Yes that works perfectly fine :-)
