### ISSUE TITLE
no problem, thank you Igor Kroitor

### ISSUE THREAD

**Issue by gemini100** [ccxt/ccxt#671]
I would thank's Igor Kroitor
so professionnal quality, docs in pdf with linked summary, no errors on calls of function
i see that there no way yet to open a wallet adress,
and for over 90 exchange platform

WWWWHHHAAAT WORK, genial, simply true

**Comment by gemini100** [comment]
i would contribute, but your dimension, igor, scarry me,i m afrraid by the dimension you give to the project,
i think what it rest to do isn't like what passed and what is ready right now
i m constructing a trading tiny bot,
if it work i ll  send you a fee, my man

**Comment by kroitor** [comment]
Thanks a lot for all your kind words! Let us know if you have any difficulty with the library. By the way, this isn't entirely a work of mine, it would be much more difficult without the joint effort of our small team and, of course, without the help of our community, we are very thankful to all contributors and users who test it, submit code and send feedback. Thank you all very much! )

**Comment by gemini100** [comment]
i know coding basics under python 3.5, i forget fortran 77, c++, c
i have'nt your level IGOR, you must be at a level greater than an ingeneer,
what quality, i'm impressed,
i can give feedback, and if i see any trajectory to add a serious block to
the wall, it will be done.
i haven't get any problem, i try on poloniex, on bittrex,
may be i can help for creating an adress wallet for deposit section....
thank you again, your re our boss.
