### ISSUE TITLE
print('Supported exchanges:', ccxtpro.exchanges) throws

### ISSUE THREAD

**Issue by 123wowow123** [ccxt/ccxt#6712]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: mac os 10.15.3
- Programming Language version: Python
- CCXT version: CCXT Pro version 0.1.21

The following line of code throws error of `module 'ccxtpro' has no attribute 'exchanges'`
print('Supported exchanges:', ccxtpro.exchanges)

**Comment by kroitor** [comment]
Fixed in CCXT Pro 0.1.24, thank you for reporting!
