### ISSUE TITLE
[QUESTION] Pushing OHLCV Candles from binance

### ISSUE THREAD

**Issue by xcvb74** [ccxt/ccxt#6717]
Hi,
I was wondering what would be the best solution to receive live OHLCV Candles data for a given timeframe & Ticker? By live I mean each time, for the timeframe, a candle is complete, it is pushed/pulled to me.
I can do this with a while loop tweaking the examples, but I'm guessing there is a much more efficient way?

Thanks

**Comment by kroitor** [comment]
Hi!

With CCXT you can do REST polling (send a request and receive response) as frequently as the exchanges' rateLimits allow you to – that is explained in the CCXT Manual: https://github.com/ccxt/ccxt/wiki/

With [CCXT Pro](https://ccxt.pro) – you can subscribe to OHLCV updates over WS, and the exchange will push them to you as soon as they become available. That is described in the CCXT Pro Manual: https://github.com/ccxt/ccxt/wiki/ccxt.pro

CCXT is REST-only, while CCXT Pro is REST + WS.

Closing this for now. Let us know if that does not answer the question. Feel free to reopen it or just ask further questions, if you have more.

**Comment by xcvb74** [comment]
Thanks for you answer and your amazing work ;-)
