### ISSUE TITLE
watch_balance() doesn't work, okex, ccxtpro  

### ISSUE THREAD

**Issue by VadimSFedin** [ccxt/ccxt#6719]
Hello,
Could you please help me to understand why the code is not working? 

- OS: Windows 10
- Programming Language version: Python 3.6
- CCXT version: 1.25.57
- CCXTPRO version: 0.1.26

```
import ccxtpro
exchange = ccxtpro.okex({
    'enableRateLimit': True,
    'apiKey': apiKey,
    'secret': secret,
    'password': password,
    'options': {
        'watchBalance': 'futures',
    },
})


async def balance():
    while True:
        balance = await exchange.watch_balance({'code': 'BTC'})
        print(balance)
asyncio.get_event_loop().run_until_complete(balance())
```

```
The program is running without any response. 
```

**Comment by kroitor** [comment]
@VadimSFedin you should change your futures balance (trade or transfer funds) to see the balance updates. Let us know if that does not answer the question.

**Comment by VadimSFedin** [comment]
I got it. Yeah, it works in this way. thanks for the explanation.  
If I want to see the current balance, which method should I use?

**Comment by kroitor** [comment]
@VadimSFedin `fetchBalance()` – https://github.com/ccxt/ccxt/wiki/Manual#querying-account-balance

**Comment by VadimSFedin** [comment]
thanks. 

But if I use fetch_balance for spot market it works without any mistake, but if I add params={'type': 'futures'} I have an error:
ccxt.base.errors.DDoSProtection: okex {"error_message":"Too Many Requests","code":30014,"error_code":"30014","message":"Too Many Requests"}
okex requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add exchange.close() to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x122D2510>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x122D5848>, 264915.109)]']
connector: <aiohttp.connector.TCPConnector object at 0x122D24B0>

The code is:
async def balance():
    while True:
        balance = await exchange.fetch_balance(params={'type': 'futures'})
        print(balance)
asyncio.get_event_loop().run_until_complete(balance())

How to solve this issue for futures account?

**Comment by kroitor** [comment]
> How to solve this issue for futures account?

Do you have the rate-limiting enabled as required in the Manual?

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

**Comment by VadimSFedin** [comment]
Yes, I do have:

import ccxtpro
exchange = ccxtpro.okex({
    'enableRateLimit': True,
    'apiKey': apiKey,
    'secret': secret,
    'password': password,
    'options': {
        'watchBalance': 'futures',
    },
})

**Comment by kroitor** [comment]
@VadimSFedin i'll look into it and will get back to you shortly.

**Comment by kroitor** [comment]
@VadimSFedin apparently, OKEX requires a higher rate limit on futures balances: https://www.okex.com/docs/en/#futures-singleness

So, this should work:

```Python
import ccxtpro
import asyncio

exchange = ccxtpro.okex({
    'enableRateLimit': True,
    "apiKey": "a24364b3-2c7d-43c1-bd04-c247f911a6c4",
    "secret": "836FDD5F03BF3C97EA9EDD8156642FC7",
    "password": "7KUcc8YzQhnxBE3K",
    "options": {
        "watchBalance": "futures",
    },
})


async def balance():
    await exchange.load_markets()
    exchange.rateLimit = 10000  # ←------------------- 10 seconds
    # exchange.verbose = True  # uncomment to debug
    while True:
        try:
            balance = await exchange.fetch_balance(params={'type': 'futures'})
            print(balance)
        except Exception as e:
            print(type(e).__name__, str(e))
            await exchange.close()
            break


asyncio.get_event_loop().run_until_complete(balance())
```

@VadimSFedin in general, you're not supposed to poll the account balance too frequently, instead you should fetch the snapshot once, and then receive the updates via WS. That way you won't be rate limited. Let me know if that does not help or does not work.

P.S. Plz use [GitHub markdown](https://guides.github.com/features/mastering-markdown/) when pasting code and output, surround it with triple backticks (&#096;&#096;&#096;) as explained here:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help 
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

&#096;&#096;&#096;Python

YOUR_CODE_HERE

&#096;&#096;&#096;

&#096;&#096;&#096;

YOUR_VERBOSE_OUTPUT_HERE

&#096;&#096;&#096;

**Comment by VadimSFedin** [comment]
Thanks for suggestion: "in general, you're not supposed to poll the account balance too frequently, instead you should fetch the snapshot once, and then receive the updates via WS." It might work for me. 
Even with 10 seconds limit rate I still have this error : "DDoSProtection okex {"error_message":"Too Many Requests","code":30014,"error_code":"30014","message":"Too Many Requests"}"

**Comment by kroitor** [comment]
@VadimSFedin 

> Even with 10 seconds rate limit I still have this error : "DDoSProtection okex {"error_message":"Too Many Requests","code":30014,"error_code":"30014","message":"Too Many Requests"}"

Yeah, actually, i've tried with 10 seconds as well – it breaks. But if I put 20 seconds there – it works. So the truth is somewhere between those boundaries, and OKEX docs are very confusing in that regard. The actual rate limit is higher than the documented rate-limit in this case.
