### ISSUE TITLE
Okex createOrder working weirdly

### ISSUE THREAD

**Issue by Eriz11** [ccxt/ccxt#6725]
- OS: Linux (Ubuntu 18.04)
- Programming Language version:  Python 3.7
- CCXT version: 1.25.41

Hi, 

I'm facing issues on the order sending with `okex` exchange. The behaviour is certainly rare (surely due to something I'm doing wrong, but I'm not able to further debug); when I place an order (let's say to buy `XLM/ETH`), I see that the `spot` balance in the `okex` account increases and I receive a return to the `create_order` request. 

Actually, I receive the return message that the trade is correct in my exception handler (just removed it to show the traceback), which is weird.

This is the traceback:

```
Traceback (most recent call last):
  File "/home/zmlaptop/Desktop/magiccryptoproject/MagicCryptoFramework/MagicCryptoTradingIntra/MagicCryptoTradingIntraClass.py", line 716, in <module>
    EXCH._receiveMessageFromNeo4jGraphInstance(msg, topic)
  File "/home/zmlaptop/Desktop/magiccryptoproject/MagicCryptoFramework/MagicCryptoTradingIntra/MagicCryptoTradingIntraClass.py", line 252, in _receiveMessageFromNeo4jGraphInstance
    self._tradingAgent(message['TRADES'], topic)
  File "/home/zmlaptop/Desktop/magiccryptoproject/MagicCryptoFramework/MagicCryptoTradingIntra/MagicCryptoTradingIntraClass.py", line 298, in _tradingAgent
    amount=TRADING_AMOUNT)
  File "/home/zmlaptop/Desktop/magiccryptoproject/MagicCryptoFramework/MagicCryptoTradingIntra/BaseExchangePackage/BaseExchangeClass.py", line 378, in placeMarketOrder
    orderObject = self.exchangeObject.createOrder(symbol=symbol, type='market', side=sellOrBuy.lower(), amount=amount, price=MARKET_RATE)
  File "/home/zmlaptop/miniconda3/envs/ccxtenv/lib/python3.7/site-packages/ccxt/okex.py", line 1796, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/home/zmlaptop/miniconda3/envs/ccxtenv/lib/python3.7/site-packages/ccxt/base/exchange.py", line 450, in inner
    return entry(_self, **inner_kwargs)
  File "/home/zmlaptop/miniconda3/envs/ccxtenv/lib/python3.7/site-packages/ccxt/base/exchange.py", line 473, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/zmlaptop/miniconda3/envs/ccxtenv/lib/python3.7/site-packages/ccxt/base/exchange.py", line 469, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/zmlaptop/miniconda3/envs/ccxtenv/lib/python3.7/site-packages/ccxt/base/exchange.py", line 592, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/zmlaptop/miniconda3/envs/ccxtenv/lib/python3.7/site-packages/ccxt/okex.py", line 3081, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: okex {"client_oid":"","code":"0","error_code":"0","error_message":"","message":"","order_id":"4660309135990784","result":true}
```
I don't quite understand why a "succesfull order" that modifies the balance (I see the `XLM` balance increased) returns this message BUT generates an error.

¿Could you please help in further debugging this?

Many thanks in advance,

**Comment by kroitor** [comment]
@Eriz11 Hi!Tthe problem was caused by the lack of error format specifications in the OKEX's API docs... I've added a fix and it should work fine as of 1.25.64. Let us know if that does not help. Thx for your feedback!

**Comment by Eriz11** [comment]
Hey @kroitor!

Many thanks for the quick fix; it works without a problem now. 

I take advantage of this issue to also ask one more thing to understand more of CCXT.

In terms of the different exchanges and the trading executed on the spot accounts of them, is CCXT doing background work for returning a standard dictionary when orders are created (i.e. the returned JSON with `'info'`, `'amount'`, `'id'` and etc)?

My question is related to checking the fills and making it on a "generalized way" between exchanges, but I guess that this is very exchange specific and I will need to make work to reconvene everything. Am I right in my assumptions?

Many thanks in advance,

**Comment by kroitor** [comment]
> In terms of the different exchanges and the trading executed on the spot accounts of them, is CCXT doing background work for returning a standard dictionary when orders are created (i.e. the returned JSON with 'info', 'amount', 'id' and etc)?

Yes. This is called the Unified CCXT API, and it's described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#unified-api

The orders returned from `createOrder` will look like so: https://github.com/ccxt/ccxt/wiki/Manual#order-structure

And the trades returned from `fetchMyTrades` will look like so:
https://github.com/ccxt/ccxt/wiki/Manual#trade-structure

The same is true for all unified methods as opposed to exchange-specific [implicit api endpoints](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods).

Most of your questions are explained in the [CCXT Manual](https://github.com/ccxt/ccxt/wiki/), so I'd recommend to read it at least once from top to bottom – it will save you a ton of time, really )

> My question is related to checking the fills and making it on a "generalized way" between exchanges, but I guess that this is very exchange specific and I will need to make work to reconvene everything. Am I right in my assumptions?

Nope, the assumption is wrong, because CCXT is designed for the unification across exchanges. However, there may be some-exchange-specific aspects that are not completely unified yet, this is a continuous work in progress. If you encounter any difficulties.

**Comment by Eriz11** [comment]
Thanks for the follow up.

What I meant is that it is true that the structure is the same, but sometimes for example the `timestamp` key is not available but the `datetime` yes and that is not generalized on the different exchanges (or even on those keys the information is different; I guess depending on how exchanges represent that internally).

However, it is just a matter of on the first instance matching everything once understood the structure.

Thanks again for the work!
