### ISSUE TITLE
[okex] place order bug

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6727]
I had a strange order execute in my system last night.  On investigation I found this in my logs (excuse the formatting):

                "stack": "ExchangeError: okex {\"client_oid\":\"\",\"code\":\"0\",\"error_code\":\"0\",\"error_message\":\"\",\"message\":\"\",\"order_id\":\"4662118510635008\",\"result\":true}\n at okex.handleErrors (/home/nodeapp/apps/crypto-trader-prototype/shared-code/node_modules/ccxt/js/okex.js:3203:19)\n at /home/nodeapp/apps/crypto-trader-prototype/shared-code/node_modules/ccxt/js/base/Exchange.js:627:18\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:97:5)\n at async timeout (/home/nodeapp/apps/crypto-trader-prototype/shared-code/node_modules/ccxt/js/base/functions/time.js:178:24)\n at async okex.exchange.fetch2 (/home/nodeapp/apps/crypto-trader-prototype/shared-code/src/shared/exchange-operations/exchange-operations-factory.js:93:37)\n at async okex.createOrder (/home/nodeapp/apps/crypto-trader-prototype/shared-code/node_modules/ccxt/js/okex.js:1834:26)\n at async ExchangeCommandHandler._executePlaceOrderCommand (/home/nodeapp/apps/crypto-trader-prototype/shared-code/src/shared/exchange-command-handler.js:170:24)\n at async ExchangeCommandHandler.executeCommand (/home/nodeapp/apps/crypto-trader-prototype/shared-code/src/shared/exchange-command-handler.js:46:13)",

It looks like the order was placed correctly, but ccxt blew up with an ExchangeError.

**Comment by kroitor** [comment]
Fixed here: https://github.com/ccxt/ccxt/issues/6725
