### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jkessous** [ccxt/ccxt#6728]
Looking for the syntax for python in getting the trade history for a specific coin in coinex. i have seen in the api i get get it via market deals but couldnt find the syntax in the py.
thanks for the help

**Comment by kroitor** [comment]
Use `fetchTrades` or `fetchMyTrades` as described in the [Manual](https://github.com/ccxt/ccxt/wiki):

- https://github.com/ccxt/ccxt/wiki/Manual#trades-executions-transactions
- https://github.com/ccxt/ccxt/wiki/Manual#personal-trades-1

In general, we suggest to read the Manual from top to bottom at least once – it has all the answers and will save you a ton of time.
