### ISSUE TITLE
ccxt.huobipro().fetchTickers([…]) returns all tickers  

### ISSUE THREAD

**Issue by leye195** [ccxt/ccxt#6733]
OS: MacOS
Programming Language version: nodejs
CCXT version:"1.25.55",
Exchange: HuobiPro
Method: fetchTickers
fetchTickers returns all instead of the given tickers.

**Comment by kroitor** [comment]
Thank you for reporting! This is fixed in 1.25.70 and the new build will arrive in 15 minutes. Let us know if that does not help.
