### ISSUE TITLE
New Exchange: Slicex

### ISSUE THREAD

**Issue by slicecoincore** [ccxt/ccxt#6737]
### Issue for addition of Slicex exchange

**API Doc:** https://slicex.cc/api.html
**URL:** https://slicex.cc
**Fee:** Maker 0.1%, Taker 0.2%
**Volume**: NA
**Address:** North Macedonia
**Company Info:** Slicex
**Company Disclaimer:** https://slicex.cc/disclaimer.html
**Registration:** NA
**Based Country:** North Macedonia
**Country ISO code:** MK
**Priority:** normal
**Github group:** NA
**Note:** ranked top : NA
**Type:** Centrailzed Ex
**Discussion:** https://t.me/slicexcc

![Logo-Slicex-85x25](https://user-images.githubusercontent.com/48226195/78469961-e48a8500-7725-11ea-9881-048c63d11803.png)

![Slicex-logo](https://user-images.githubusercontent.com/48226195/78469147-adfd3c00-771e-11ea-97a6-82e710ed24aa.png)

**Comment by slicecoincore** [comment]
https://github.com/ccxt/ccxt/pull/6850

**Comment by kroitor** [comment]
The exchange is inactive or has not volume.

**Comment by slicecoincore** [comment]
Of course is inactive waiting for you more then a year to check the code
and implement it.

**Comment by slicecoincore** [comment]
The exchange is not active, true, but we could use this library to make some connections, so we can develop further. All checks are good more then a year ago, so it would be good if implemented. I did some movement on exchange, so you can check. Thanks.

**Comment by ttodua** [comment]
Exchange had ceased the operations and [was shutdown](https://twitter.com/slicexcc/status/1498644653628964872).
