### ISSUE TITLE
Binance GET /sapi/v1/margin/myTrades not working

### ISSUE THREAD

**Issue by 123wowow123** [ccxt/ccxt#6739]
- OS: Mac OS 10.15.3
- Programming Language version: Python Version: 3.8.2
- CCXT version: CCXT Pro version 0.1.39

Hi, I am trying to get the Trade List from Binance use the below 2 variation but getting the below respective errors. Is there a proper way of using these endpoints? Thanks

'binance' object has no attribute 'sapi_get_margin_myTrades'
'binance' object has no attribute 'private_get_myTrades'

Seems like in ccxt > binance.py file there are entries for:
line 122:  sapi > get > margin/myTrades
line 277:  private > get > myTrades

payload = {
    'symbol': exchange.market('BTC/USDT')['id']
     'fromId': 1742966777
}
orderRes = await exchange.sapi_get_margin_myTrades(payload)
orderRes = await exchange.private_get_myTrades(payload)

**Comment by kroitor** [comment]
Hi!

It should be `sapi_get_margin_myTrades()`, however,

>  but getting the below respective errors. 

you haven't pasted the errors, can you show your verbose output (without your keys) ?

```Python
await exchange.load_markets()
exchange.verbose = True
payload = {
    'symbol': exchange.market('BTC/USDT')['id']
    'fromId': 1742966777
}
orderRes = await exchange.sapi_get_margin_myTrades(payload)
```

----

P.S. Use the GitHub's [markdown](https://guides.github.com/features/mastering-markdown/) to format your output for readability and padding, surround your code and/or output with triple backticks (&#096;&#096;&#096;), like shown below:

&#096;&#096;&#096;JavaScript

your code here

&#096;&#096;&#096;

---

&#096;&#096;&#096;

your output here

&#096;&#096;&#096;

**Comment by 123wowow123** [comment]
Hi, please see the bellow error output and code. Thank you

```Python
async def main(exchange):
    await exchange.loadMarkets()

    try:
        BTCUSDTSymbol = exchange.market('BTC/USDT')['id']
        payload = {
            'symbol': BTCUSDTSymbol,
            'fromId': 1742966777
        }

        orderRes = await exchange.sapi_get_margin_myTrades(payload)
        print(orderRes, '\n')

        return orderRes
    except Exception as e:
        raise
    finally:
        await exchange.close()

if __name__ == "__main__":
    loop = asyncio.get_event_loop()

    try:
        exchange = getattr(ccxtpro, 'binance')({
            "apiKey": 'abc',
            "secret": 'abc',
            "enableRateLimit": True,
            'asyncio_loop': loop,
            'verbose': True
        })

        loop.run_until_complete(main(exchange))
    except Exception as e:
        print(traceback.format_exc())
    finally:
        loop.close()
        sys.exit(0)
```

Error (I removed the output from  'await exchange.loadMarkets()' as that is huge and did not offer any relevant information fore below issue):
```
'binance' object has no attribute 'sapi_get_margin_myTrades'
Traceback (most recent call last):
  File "/Users/Ian/Code/crypto-signal/debug.py", line 138, in <module>
    loop.run_until_complete(main(exchange))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/Ian/Code/crypto-signal/debug.py", line 114, in main
    orderRes = await exchange.sapi_get_margin_myTrades(payload)
AttributeError: 'binance' object has no attribute 'sapi_get_margin_myTrades'

```

**Comment by kroitor** [comment]
Sorry, it should be `sapi_get_margin_mytrades`, it's a typo in my snippet above.
Should be the following:

```Python
await exchange.load_markets()
exchange.verbose = True
payload = {
    'symbol': exchange.market('BTC/USDT')['id']
    'fromId': 1742966777
}
orderRes = await exchange.sapi_get_margin_mytrades(payload)
```

Let me know if that helps or not.

**Comment by 123wowow123** [comment]
Gotcha, that worked! Thank you
