### ISSUE TITLE
Unable To create Limit orders on FTX

### ISSUE THREAD

**Issue by 8ball030** [ccxt/ccxt#6740]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
Python 3.6.9

- CCXT version:
Version 1.25.81

Hi I am trying to set a limit order on FTX.com

I am able to set market orders, but for some reason, I am unable to set limit orders!

Every time i set a limit order, the IOC paramater is ignored, so the order is immediate killed as it is out of the the money.

Hoping you can point me in the direction of where the "ioc" parameter default is set.

in my debugging, I have tried to crate a subclass and the monkey patch in an override to force IOC to be false;

import ccxt
from ccxt import InvalidOrder

class ftx(ccxt.ftx):

    def create_order_custom(self, symbol, type, side, amount, price=None, params={}):
        self.load_markets()
        market = self.market(symbol)
        request = {
            'market': market['id'],
            'side': side,  # buy or sell
            # 'price': 0.306525,  # send null for market orders
            'type': type,  # limit, market, stop, trailingStop, or takeProfit
            'size': float(self.amount_to_precision(symbol, amount)),
            # 'reduceOnly': False,  # optional, default is False
            'ioc': False,  # optional, default is False, limit or market orders only
            # 'postOnly': False,  # optional, default is False, limit or market orders only
            # 'clientId': 'abcdef0123456789',  # string, optional, client order id, limit or market orders only
        }
        priceToPrecision = None
        if price is not None:
            priceToPrecision = float(self.price_to_precision(symbol, price))
        method = 'privatePostConditionalOrders'
        if type == 'limit':
            method = 'privatePostOrders'
            request['price'] = priceToPrecision
        elif type == 'market':
            method = 'privatePostOrders'
            request['price'] = None
        elif (type == 'stop') or (type == 'takeProfit'):
            request['triggerPrice'] = priceToPrecision
            # request['orderPrice'] = number  # optional, order type is limit if self is specified, otherwise market
        elif type == 'trailingStop':
            request['trailValue'] = priceToPrecision  # negative for sell, positive for buy
        else:
            raise InvalidOrder(self.id + ' createOrder() does not support order type ' + type + ', only limit, market, stop, trailingStop, or takeProfit orders are supported')
        print("Extra Paras!", params)
        response = getattr(self, method)(self.extend(request, params))
        #
        # orders
        #
        #     {
        #         success: True,
        #         result: [
        #             {
        #                 createdAt: 2019-03-05T09:56:55.728933+00:00,
        #                 filledSize: 0,
        #                 future: XRP-PERP,
        #                 id: 9596912,
        #                 market: XRP-PERP,
        #                 price: 0.306525,
        #                 remainingSize: 31431,
        #                 side: sell,
        #                 size: 31431,
        #                 status: open,
        #                 type: limit,
        #                 reduceOnly: False,
        #                 ioc: False,
        #                 postOnly: False,
        #                 clientId: null,
        #             }
        #         ]
        #     }
        #
        # conditional orders
        #
        #     {
        #         success: True,
        #         result: [
        #             {
        #                 createdAt: 2019-03-05T09:56:55.728933+00:00,
        #                 future: XRP-PERP,
        #                 id: 9596912,
        #                 market: XRP-PERP,
        #                 triggerPrice: 0.306525,
        #                 orderId: null,
        #                 side: sell,
        #                 size: 31431,
        #                 status: open,
        #                 type: stop,
        #                 orderPrice: null,
        #                 error: null,
        #                 triggeredAt: null,
        #                 reduceOnly: False
        #             }
        #         ]
        #     }
        #
        #
        result = self.safe_value(response, 'result', [])
        return self.parse_order(result, market)

However, the returned order object will have "ioc" = True

Thanks
```


import ccxt

exchange  ccxt.fxt({"apiKey":xxx, "secret"})
packet=packet= {'symbol': 'BTC-PERP', 'amount': 0.0001, 'type': 'limit', 'side': 'sell', 'price': 7145.137999999999}
order = exchange.create_order(self.market,
                                        "limit",
                                         packet['side'],
                                         packet['amount'],
                                         packet['price'],
                                         {"ioc": False}
                                        )
("Made order ",market, order)



```

```

***************************************************************************8
output;
Made order  BTC-PERP {'info': {'avgFillPrice': None, 'clientId': None, 'createdAt': '2020-04-06T12:03:45.636364+00:00', 'filledSize': 0.0, 'future': 'BTC-PERP', 'id': 4475899457, 'ioc': True, 'market': 'BTC-PERP', 'postOnly': False, 'price': 7145.0, 'reduceOnly': False, 'remainingSize': 0.0001, 'side': 'sell', 'size': 0.0001, 'status': 'new', 'type': 'limit'}, 'id': '4475899457', 'clientOrderId': None, 'timestamp': 1586174625636, 'datetime': '2020-04-06T12:03:45.636Z', 'lastTradeTimestamp': None, 'symbol': 'BTC-PERP', 'type': 'limit', 'side': 'sell', 'price': 7145.0, 'amount': 0.0001, 'cost': 0.0, 'average': None, 'filled': 0.0, 'remaining': 0.0001, 'status': 'open', 'fee': None, 'trades': None}
```

**Comment by kroitor** [comment]
Hi!

> Hoping you can point me in the direction of where the "ioc" parameter default is set.
> in my debugging, I have tried to crate a subclass and the monkey patch in an override to force IOC to be false;

First of, you don't have to override an entire method. In the Manual it is explained how to properly override the unified params values:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

So, in order to submit that param, you can simply do this (without redefining the entire method):

```Python
import ccxt

exchange  ccxt.ftx({
    'apiKey': 'YOUR_API_KEY',
    'secrey': 'YOUR_SECRET',
})

order = exchange.create_order('BTC-PERP', 'limit', 'sell', 0.0001, 7145.137999999999, {'ioc': True})
```

↑However, the above is only required if you want `ioc: True`. If you want to have it `False` as by default – just omit it entirely.

According to FTX docs the `ioc` parameter is `False` by default, so the next step towards the correct solution if you want the order to be a default non-IOC order, you simply do not specify that parameter:


```Python
import ccxt

exchange  ccxt.ftx({
    'apiKey': 'YOUR_API_KEY',
    'secrey': 'YOUR_SECRET',
})

order = exchange.create_order('BTC-PERP', 'limit', 'sell', 0.0001, 7145.137999999999)
```

↑ This should place your order.

> Every time i set a limit order, the IOC paramater is ignored, so the order is immediate killed as it is out of the the money.

In the output above, you posted this response:

```
{'amount': 0.0001,
 'average': None,
 'clientOrderId': None,
 'cost': 0.0,
 'datetime': '2020-04-06T12:03:45.636Z',
 'fee': None,
 'filled': 0.0,
 'id': '4475899457',
 'info': {'avgFillPrice': None,
          'clientId': None,
          'createdAt': '2020-04-06T12:03:45.636364+00:00',
          'filledSize': 0.0,
          'future': 'BTC-PERP',
          'id': 4475899457,
          'ioc': True,
          'market': 'BTC-PERP',
          'postOnly': False,
          'price': 7145.0,
          'reduceOnly': False,
          'remainingSize': 0.0001,
          'side': 'sell',
          'size': 0.0001,
          'status': 'new',
          'type': 'limit'},
 'lastTradeTimestamp': None,
 'price': 7145.0,
 'remaining': 0.0001,
 'side': 'sell',
 'status': 'open',
 'symbol': 'BTC-PERP',
 'timestamp': 1586174625636,
 'trades': None,
 'type': 'limit'}
```

↑ In this output the order status says "open", which means that your order has been successfully placed as a regular order. It stays open and it was not filled immediately and it was not canceled.

> Every time i set a limit order, the IOC paramater is ignored, so the order is immediate killed as it is out of the the money.

I cannot see that from your comments above – you have posted a perfectly-fine order which isn't killed. Please, clarify how exactly you determine this: _"the IOC paramater is ignored, so the order is immediate killed as it is out of the the money"_.

**Comment by 8ball030** [comment]
HI, Kroiter,

Thanks for all of the help!

I have got that covered and additionaly I have been able get a nice example for placing the coditional trailing stop loss orders as well;
```
        import ccxt

        exchange =ccxt.ftx({
        'apiKey': os.environ["api_key"],
        'secret': os.environ["secret"],
        })
        initial_order = exchange.create_order('BTC-PERP', # market
                                      'limit', # type
                                      'buy', # side
                                      0.0001, # amount
                                      5145.137999999999, # price
                                      )
        print("Placed initial Order!")

        order = exchange.create_order('BTC-PERP', # market
                                      'trailingStop', # type
                                      'sell', # side
                                      0.0001, # amount
                                      17145.137999999999, # price
                                      {
                                       "trailValue": -1000.05,
                                       "retryUntilFilled": True,
                                       "reduceOnly":True}
                                       )
        # now we check on the orders

        time.sleep(10)
        print(order['id']))
        print(intial_order["id"]
        # exchange.check_order_status(order['id']))
```

You can close this issue now,

My apologies! Thanks again for taking the time to help :)

**Comment by kroitor** [comment]
@8ball030 thanks for reporting back and for the snippet!

**Comment by 8ball030** [comment]
No Worries,
I just need to implement a way to store them on my side, and I will be laughing.
Tried to tip you in BAT as well, but for some reason couldnt do it... :(

**Comment by stokak** [comment]
Hi @8ball030 ,

I'm having the same issue to create a limit order on ftx... can you please tell me how you managed to sell a normal limit order without ioc being set as "True?"

Thanks!

**Comment by OlivierMedor** [comment]
> Hi @8ball030 ,
> 
> I'm having the same issue to create a limit order on ftx... can you please tell me how you managed to sell a normal limit order without ioc being set as "True?"
> 
> Every time I send one, it is automatically cancelled and doesn't remain open...
> 
> Thanks!

Hi, I was having the same issue with BTC orders on FTX. Turns out that if you order a size smaller then the "minProvideSize", the order is automatically turned into a IOC order. You can find more info here [https://help.ftx.com/hc/en-us/articles/360027946651-Order-Limits-and-Price-Bands](url)

**Comment by kroitor** [comment]
@OlivierMedor thx for your feedback!

**Comment by PlatyPulse** [comment]
@OlivierMedor has the exact answer for this, if you're just testing, try puttin an order above 0.001 for BTC, it will work instnatly
