### ISSUE TITLE
Question: Binance futures account balance history

### ISSUE THREAD

**Issue by Gennttii** [ccxt/ccxt#6745]
Hi,

I need Binance futures account balance history.

I am fetching closed positions and I need to find what balance I had when each position was closed. 
Is there any endpoint or other way to find it?

Regards

**Comment by kroitor** [comment]
Hi!

> Is there any endpoint 

No, there's no endpoint for balance history. 

> or other way to find it?

You have to collect the balance history on your own, or build it from zero using your history of withdrawals, deposits, trades, transfers, rebates and other money movements. Basically, if you add all your money movements to zero – you should arrive at your current balance and maintain your actual view of it from there.

Let me know if that does not answer the question.

**Comment by dorienh** [comment]
Did you ever write some code for this? I am interested in this too.
