### ISSUE TITLE
New Exchange: YingEX

### ISSUE THREAD

**Issue by MaxLee1980** [ccxt/ccxt#6747]
Issue for addition of YingEX exchange

API Doc: https://yingex.coding.net/p/yingex_openapi/git
URL: https://yingex.com
Volume: NA
Address: Singapore
Company Info: MISSION FOUNDATION LTD.
Registration: NA
Based Country: Singapore
Github group: NA
Note: ranked top : NA
Type: Centrailzed Ex

**Comment by kroitor** [comment]
The exchange website is inaccessible.
