### ISSUE TITLE
[okex] response to createOrder is wrong

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6753]
The types are wrong (strings where I expect numbers for price / amount etc).  The timestamp is assumed.

I think it would be better to only return  {id, info}

**Comment by kroitor** [comment]
> The types are wrong (strings where I expect numbers for price / amount etc)

It means, you're supplying strings to `createOrder`, because `price` and `amount` are returned as is.

> The timestamp is assumed.

Will set to undefined, thx.

**Comment by npomfret** [comment]
@kroitor I have a similar problem with the exmo `createOrder` return value.  Some fields of the order are populated even though the exchange doesn't return them. I think this is an anti-pattern.  We're assuming the exchange has accepted the order instruction as-is, and not changed the values in any way  (which I know some exchanges do (coinfloor / cex?)).

Can we only return explicit values that the exchange provides, and leave it to the user to fill in any missing values as they see fit?

**Comment by kroitor** [comment]
> Can we only return explicit values that the exchange provides, and leave it to the user to fill in any missing values as they see fit?

Probably, yes.
