### ISSUE TITLE
Adding a line to the README.md

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [ccxt/ccxt#6754]
Hey man! hope you are doing well. We have just released the Beta version of Superalgos, and I wanted to send you a PR to add it on the list here:

![image](https://user-images.githubusercontent.com/9479367/78801759-5b8d7b00-79bd-11ea-8e16-733e1c9a5c32.png)

I read at CONTRIBUTING.md that the README file is generated, so can you add it please? 

I have kept the dependencies of our project to the minimum; and I am happy to be building over your project seeing how much work and effort you guys have put into it.

Hopefully someday in the future, once we have a token, we can support you financially with some kind of sponsorship. In the meantime while bootstrapping I just can say thank you for your hard work and the support you gave me during the last months.

Cheers!

PD: here is our logo:

<img width="360" alt="superalgos-logo" src="https://user-images.githubusercontent.com/9479367/78802972-b7a4cf00-79be-11ea-9647-39d70d9ea4f0.png">

And text: "Superalgos: Free  and Open Source Crypto Trading Tools."

LinkTo: https://superalgos.org/

**Comment by kroitor** [comment]
Hi @Luis-Fernando-Molina !

That section of the page is for paid sponsored promotions only. It helps this project go on. If you are interested in sponsored ads, please reach out to us at info@ccxt.trade. 

Thank you!

**Comment by kroitor** [comment]
@Luis-Fernando-Molina we can add you here though, in the examples: https://github.com/ccxt/ccxt/tree/master/examples#see-also

**Comment by Luis-Fernando-Molina** [comment]
> That section of the page is for paid sponsored promotions only. It helps this project go on. If you are interested in sponsored ads, please reach out to us at info@ccxt.trade.

I will once we get ourselves funded.

> @Luis-Fernando-Molina we can add you here though, in the examples: https://github.com/ccxt/ccxt/tree/master/examples#see-also

That would be fine, thanks!

**Comment by Luis-Fernando-Molina** [comment]
Hey! 

Hope you are doing great!

Since the last time we talked, we have grown our platform to be among the first in GitHub, but still we have no mention at your README even though we are based on CCXT.

Please check this out:

https://github.com/search?q=trading+bots



During the last months we have created our own token used to govern the project. We believe that CCXT even if it was not made explicitly for Superegos can still be considered a contribution. If you would like to, you could apply to get SA tokens once the governance system is ready (1 month) and I am quite sure the community will vote for your claims and get in this way get SA tokens at every new release of Superalgos (that happens every 2 months more or less).

Sent from Mail for Windows 10
