### ISSUE TITLE
Are we dropping python2 support?

### ISSUE THREAD

**Issue by lobatt** [ccxt/ccxt#6758]
I recently found that all tests are failing when I run the following in the docker env:

    npm run test

After some digging, I found that the following line uses python3 syntax hence would not compile with python2:

https://github.com/ccxt/ccxt/blob/84c73adb0474ce03566adbb86b8d725a90c6f91c/python/ccxt/base/exchange.py#L515

I tried 
    
    npm run fast-test

and 

     node run-tests.js --python3

both worked without problem.

Or should this be a bug in the `build/transpile.js`?

**Comment by kroitor** [comment]
> Are we dropping python2 support?

Yes: https://python3statement.org

We're not dropping the support for sync python version though.

> Or should this be a bug in the build/transpile.js?

Nope, it does not transpile baseclass code (only derived class files are transpiled), so, `build/transpile.js` has nothing to do with that `print()` statement. 

Let me know if that does not answer the question.

**Comment by lobatt** [comment]
Hi @kroitor, 
This is good to know, maybe we can update the CCXT docker image to run python3 for tests by default?

**Comment by kroitor** [comment]
@lobatt hi! I'll try to get to it asap.
