### ISSUE TITLE
kucoin order book stream: top bid matches top ask

### ISSUE THREAD

**Issue by jaseisen105** [ccxt/ccxt#6762]
- OS: `ubuntu 16.04.5 LTS`
- Programming Language version: `python 3.6.5`
- CCXT version: `0.1.45`

Hi - I'm trying to run a standard order book stream with `limit=20` from kucoin.  I've noticed that occasionally the order book looks wrong.  Providing a sample where the top bid matches the top ask.  This was for the pair `NEO/USDT` but seen it happen on other pairs as well.  Once this happens the book seems "stuck" and the issue does not resolve itself

Is there a good way to "reset" an order book stream?  Something like:

```
if ccxt_symbol in exchange.orderbooks:
    del exchange.orderbooks[ccxt_symbol]
```

```
{
  "bids": [
    [
      8.0229,
      60.99
    ],
    [
      8.0227,
      21.155718
    ],
    [
      8.0175,
      0.837539
    ],
    [
      8.0101,
      60.99
    ],
    [
      8.01,
      52.002495
    ],
    [
      8.003,
      42.142484
    ],
    [
      8.0,
      5.05
    ],
    [
      7.9756,
      16.8
    ],
    [
      7.9755,
      59.052932
    ],
    [
      7.9754,
      56.9
    ],
    [
      7.9753,
      0.00941
    ],
    [
      7.9544,
      169.0
    ],
    [
      7.9501,
      577.9
    ],
    [
      7.95,
      2.0
    ],
    [
      7.9486,
      14.136971
    ],
    [
      7.9275,
      0.00941
    ],
    [
      7.9,
      1.765853
    ],
    [
      7.8797,
      0.00941
    ],
    [
      7.8768,
      87.979244
    ],
    [
      7.8501,
      5.0
    ]
  ],
  "asks": [
    [
      8.0229,
      21.589581
    ],
    [
      8.023,
      239.249799
    ],
    [
      8.0317,
      0.075007
    ],
    [
      8.04,
      5.6422
    ],
    [
      8.0401,
      16.7
    ],
    [
      8.0402,
      2.342353
    ],
    [
      8.0624,
      56.8
    ],
    [
      8.0625,
      5.0
    ],
    [
      8.0636,
      36.057584
    ],
    [
      8.0708,
      577.8
    ],
    [
      8.0709,
      0.00941
    ],
    [
      8.0823,
      10.959775
    ],
    [
      8.1,
      32.268401
    ],
    [
      8.1188,
      0.00941
    ],
    [
      8.1348,
      12.81646
    ],
    [
      8.1376,
      168.9
    ],
    [
      8.15,
      3.0
    ],
    [
      8.1666,
      0.00941
    ],
    [
      8.2,
      1.0
    ],
    [
      8.2036,
      0.388148
    ]
  ]
}
```

```
limit = 20
while True:
    ccxt_orderbook = await ccxtpro_kucoin.watch_order_book(
        ccxt_symbol,
        limit=limit,
        params={}
    )
```

**Comment by kroitor** [comment]
Hi! Thanks for reporting! We will debug it and will get back to you with a fix or more info asap.

**Comment by jaseisen105** [comment]
Great, thank you!

**Comment by kroitor** [comment]
@jaseisen105 i think i've managed to reproduce it, though it does not happen all the time, but anyways... will upload a fix soon.

**Comment by jaseisen105** [comment]
Agreed it seems to happen around 2-5% of the time for me, thanks for looking into it!

**Comment by kroitor** [comment]
@jaseisen105 this bug should be fixed in CCXT Pro 0.1.66. We've added some workarounds, so it should synchronize properly. Let us know if you still experience issues with it. Thx for reporting!

**Comment by codemonkeyno1** [comment]
This seems to be happening in the Kraken watch orderbook stream too (bid>=ask).  For example, on ticker "BTC/USDT", it sometimes happens within 10 minutes or so.

**Comment by kroitor** [comment]
@codemonkeyno1 can you post the code you use to reproduce it?

**Comment by codemonkeyno1** [comment]
kraken = ccxtpro.kraken({'apiKey':apikey,'secret':apisecret,'enableRateLimit':True})
await kraken.load_markets()

symbols = ['BTC/USD','BTC/USDT','ETH/USD','ETH/USDT','XRP/USD','XRP/USDT']
for symbol in symbols:
    await kraken.watch_order_book(symbol,10)
	await asyncio.sleep(0.2)
	
while True:
	await asyncio.sleep(1)
	for symbol in symbols:
		ob = kraken.orderbooks[symbol].limit(10)
		bid = ob['bids'][0][0]
		ask = ob['asks'][0][0]
		print(symbol + ' : ' + str(bid) + ' ' + str(ask))

**Comment by kroitor** [comment]
@codemonkeyno1 thx! I'll debug it on my side and will get back to you asap.
