### ISSUE TITLE
paymium params not applied

### ISSUE THREAD

**Issue by RetGal** [ccxt/ccxt#6763]
Params needed to get a specific order are beeing ignored. 

- OS: Linux (Debian)
- Programming Language version: Python (3.7)
- CCXT version: 1.25.93

Code:
```
`order = EXCHANGE.private_get_user_orders({'uuid': order_id})`
or
`result = EXCHANGE.private_get_user_orders(params={'active': True})`
```

Result:
```
actual:
`Request: GET https://paymium.com/api/v1/user/orders `
expected:
`Request: GET https://paymium.com/api/v1/user/orders/a99e9acd-37e0-4974-8636-02fb31ba46f5`
or
`Request: GET https://paymium.com/api/v1/user/orders?active=true`
```

**Comment by Droppix** [comment]
@RetGal 

Hi,

I'm trying to authenticate on Paymium, with my token, but it's not working! 
Does it work for you? If so, would you have an example?

Thanks

**Comment by kroitor** [comment]
@Droppix make sure that you have configured the credentials correctly:

- https://github.com/ccxt/ccxt/wiki/Manual#api-keys-setup

If that does not help, please paste your code that you use and your verbose request/response as described here:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

We don't need your keys (don't paste those), but we need to see a complete snippet on how you initialize and use the exchange instance, as well as the full verbose output.

**Comment by Droppix** [comment]
I use CCXT api on Binance, Kraken, ... and it works fine, but not on Paymium.
Paymium use "Token" (not pair apikey/secret)...

My code is 
```
        const exchangeClass = ccxt['paymium']
        let exchange = new exchangeClass ({
            'apiKey': 'MyToken',
            'secret': 'MyToken', // or Empty
            'timeout': 30000,
            'enableRateLimit': true,            
        })     
  
        let balances
        try {
            let result = await exchange.fetchBalance()        
            return result != null ? true : false
        } catch(err) {
            // error Authorization 401
            return null
        }
```

**Comment by kroitor** [comment]
> Paymium use "Token" (not pair apikey/secret)...

Not really. CCXT uses the documented apiKey and secret and those should not be the same string, as described in the Paymium docs here:

- https://paymium.github.io/api-documentation/#section/Authentication

So, you should use a keypair for it, not a single token.

**Comment by Droppix** [comment]
Paymium does not provide an keypair, only a "token".
Maybe I didn't get it, but it does say APIKEY = Token ??

"Api-key is the token that is displayed when listing your currently active tokens must be used with Api-Signature and Api-Nonce."

**Comment by kroitor** [comment]
@Droppix when we tested it on our side, it had a 64-symbol hex-string for the apiKey and a 64-symbol hex string for the secret.

**Comment by Droppix** [comment]
I'll contact them, but obviously their API has evolved...

In their documentation, it is specified:

```
The Paymium API allows developers to extend the capabilities of the Paymium platform, from reading the latest ticker to automating trades with bots.

It is possible to, among other things:

Access public data (ticker, asks, bids, trades, etc...)
Authenticate users with their permission using OAuth2 *
Access authenticated user balances, trades, and other data *
Automate trading *
* Authenticating users is only available to developers that have a fully verified and approved Paymium account. On the other hand, public data is available to everyone.
```

**Comment by kroitor** [comment]
> I'll contact them

It will be awesome if you post a followup here with your results, we will add the edits on our side asap.

> obviously their API has evolved...

Yep, that may be the case.

**Comment by Droppix** [comment]
Okay, I'll let you know...

I also have another problem on Coinbase with CCXT, which was working with the version (1.21.34) but not anymore (fetchTransactionsWithMethod("privateGetAccountsAccountIdTransactions", fetchDeposits/fetchWithdrawals -> some fields are "undefined", but I'll open another issue...

**Comment by kroitor** [comment]
> but I'll open another issue...

Sure, we will do our best to look into it asap. Please, mind https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help. Thx for your feeback!

**Comment by RetGal** [comment]
@Droppix Hi, 
paymium api key and secret im my configuration look like this (not actual key and secret):
`api_key = "ec8687bb630f8907e3865c933a0e27c7e5d41baed3b4dca3ad182fcf381ddef4"
api_secret = "ada5f02c4fe4c3585dca470e3c589b53cdfb37effa57fde4ffff1590635cb008"`
maybe it helps..

**Comment by Droppix** [comment]
@RetGal 
Okay, thanks, I found...
The problem was in the display of the secret key (it didn't appear in the browser), but now it appears well...

**Comment by Droppix** [comment]
@kroitor 
Hello,
Can you possible, that you add  'user/withdrawals' entry, in the paymium.js file?
```
                'private': {
                    'get': [
                          ...
                    ],
                    'post': [
                        ...
                        'user/price_alerts',
                        'user/withdrawals',
                    ],
```

**Comment by kroitor** [comment]
@Droppix sure! will add that shortly! Thx!
