### ISSUE TITLE
Closing position on Bybit?

### ISSUE THREAD

**Issue by antebw** [ccxt/ccxt#6765]
Hello, how to close open position using ccxt in bybit

**Comment by kroitor** [comment]
To close an open position you should simply place an opposite basic order or a conditional order that will trigger your stop condition. So, if you have opened a position by buying some number of contracts – then your should sell the same number of contracts. Let us know if that does not answer the question.

**Comment by antebw** [comment]
Thank you for fast response, yes this is working for me. Thx one more time.
