### ISSUE TITLE
Gemini updated https://docs.gemini.com/rest-api which breaks fetchMarkets function

### ISSUE THREAD

**Issue by toant13** [ccxt/ccxt#6766]
`CCXT version: 1.25.95`

`https://docs.gemini.com/rest-api/#symbols-and-minimums` has been updated as of today 4/9/2020

`fetchMarketsFromWeb` calls `https://docs.gemini.com/rest-api/#symbols-and-minimums` and then parses the table, but Gemini updated the table today to only include currency rather than symbols.  This means the `loadMarkets()` is loaded incorrectly as a result.

broken function: https://github.com/ccxt/ccxt/blob/master/js/gemini.js#L170
Here is proof the site has changed (archive from march): https://web.archive.org/web/20200329112807/https://docs.gemini.com/rest-api/

**Comment by kroitor** [comment]
The problem is that Gemini API does not serve the minimums from the API or from anywhere else, but their docs... And they can change the docs anytime... Why wouldn't they just serve a plain JSON with those minimums and limits from their API just like most other exchanges do...

**Comment by toant13** [comment]
> The problem is that Gemini API does not serve the minimums from the API or from anywhere else, but their docs... And they can change the docs anytime... Why wouldn't they just serve a plain JSON with those minimums and limits from their API just like most other exchanges do...

I completely agree.  It's a pain point that I've raise to them to no avail unfortunately :/

**Comment by kroitor** [comment]
@toant13 i'll add the new parser soon, thx!
