### ISSUE TITLE
Kucoin fetchClosedOrders not returning all orders

### ISSUE THREAD

**Issue by jeee** [ccxt/ccxt#6769]
Kucoin does only seem to return the orders in a specific period and not all since the supplied date. What is the best way to go around that?

- OS: ubuntu 18.04
- Programming Language version: Python 3.6.9
- CCXT version: 1.25.97

```
import ccxt
exchanges = [{ 'id': 'kucoin',
    'timeout': 30000,
    'enableRateLimit': True}
]

exchange_class = getattr(ccxt, 'kucoin')
kx = exchange_class(exchanges[0])

## returns order
k_orders = kx.fetch_closed_orders('CV/BTC', since = kx.milliseconds() - 1000*86400*10, limit = 20)
## does not return order
k_orders = kx.fetch_closed_orders('CV/BTC', since = 1514764800000, limit = 20)
```

Also I tried to pagination example from the manual but it gets stuck in a  loop: since remains the amount of the last order and is aways smaller then the exchange time and since it is the last order it will always return the order so the length will always be 1.
```
# Python
if exchange.has['fetchOrders']:
    since = exchange.milliseconds () - 86400000  # -1 day from now
    # alternatively, fetch from a certain starting datetime
    # since = exchange.parse8601('2018-01-01T00:00:00Z')
    all_orders = []
    while since < exchange.milliseconds ():
        symbol = None  # change for your symbol
        limit = 20  # change for your limit
        orders = await exchange.fetch_orders(symbol, since, limit)
        if len(orders):
            since = orders[len(orders) - 1]['timestamp']
            all_orders += orders
        else:
            break
```

Please let me know what I am doing wrong here. thx!

**Comment by kroitor** [comment]
I suggest to get this issue resolved step by step.

First:

```Python
## does not return order
k_orders = kx.fetch_closed_orders('CV/BTC', since = 1514764800000, limit = 20)
```

↑ This specific timestamp will not work, "2018-01-01T00:00:00.000Z" is too old, because [KuCoin updated API version v1 → v2 since then](https://github.com/ccxt/ccxt/issues/4579), and you I think you can't retrieve the old orders with v2.

So the first question to you is: does it work for you with a timestamp that is closer to today? 

```Python
## does it work?
since = kx.parse8601('2020-01-01T00:00:00Z')
k_orders = kx.fetch_closed_orders('CV/BTC', since = since, limit = 20)
```

**Comment by jeee** [comment]
Wow, thank you for your fast reply.
```
k_orders = kx.fetch_closed_orders('CV/BTC', since = kx.milliseconds() - 1000*86400*20, limit = 20)
print(len(k_orders))
k_orders = kx.fetch_closed_orders('CV/BTC', since = kx.milliseconds() - 1000*86400*10, limit = 20)
print(len(k_orders))​
0
3
```
From the site:
"However, when you query orders in done status, the start and end time range cannot exceed 7* 24 hours. An error will occur if the specified time window exceeds the range. If you specify the end time only, the system will automatically calculate the start time as end time minus 7*24 hours, and vice versa."

Do we have to loop over it week by week and then a subloop for the limit? This need to be done manually of by ccxt?

**Comment by kroitor** [comment]
> "However, when you query orders in done status, the start and end time range cannot exceed 7* 24 hours. An error will occur if the specified time window exceeds the range. If you specify the end time only, the system will automatically calculate the start time as end time minus 7*24 hours, and vice versa."

Yes, but that does not explain why their API does not return the orders for 20 days back. If you think of it, 

> This need to be done manually of by ccxt?

It has to be done manually.

See this example for details: https://github.com/ccxt/ccxt/blob/master/examples/py/kucoin-fetch-closed-orders-pagination.py

Related:

- https://github.com/ccxt/ccxt/issues/5443
- https://github.com/ccxt/ccxt/issues/4949

If the example above does not help – do you see those historical orders on the KuCoin website?

**Comment by jeee** [comment]
Ok. makes sense. I don't think there are orders between 20 and 10 days ago. Just did not expect it to return empty then. Don't understand why Kucoin does it like that since now I have to do 52 requests for a year where one might be sufficient otherwise.

Thanks a lot

**Comment by jeee** [comment]
Using that pagination example it gets stuck in a loop as mentioned in the original issue as well. What is the best way to solve that? (can check if the current entry is 1 and equal to previous but then you always get an extra request. add 1 ms maybe?) Maybe nice to update the examples as well if they don't work properly.

'''
2020-03-09T00:00:00.000Z - 2020-03-16T00:00:00.000Z 0 orders
2020-03-16T00:00:00.000Z - 2020-03-23T00:00:00.000Z 0 orders
2020-03-23T00:00:00.000Z - 2020-03-30T00:00:00.000Z 0 orders
2020-03-30T00:00:00.000Z - 2020-04-06T00:00:00.000Z 3 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
2020-04-02T15:16:56.000Z - 2020-04-09T15:16:56.000Z 1 orders
"""

**Comment by kroitor** [comment]
> What is the best way to solve that?

You can try switching to paginating by `currentPage` instead of date.

> can check if the current entry is 1 and equal to previous but then you always get an extra request

That is one way to do it. Checking if there were more orders after the last one will yield an extra request anyway.

> add 1 ms maybe?

This is bad, since some orders may be closed on the same second, and if you add +1, you may miss those when paginating.

> Maybe nice to update the examples as well if they don't work properly.

Yes, will think of a better solution to it, and will update the examples.

**Comment by jeee** [comment]
what about:

```python
since = kx.parse8601('2020-03-26T00:00:00Z')
to = kx.parse8601('2020-04-10T00:00:00Z')

if to == None:
    to = exchange.milliseconds()
all_orders = []
day = 24 * 3600 * 1000
week = 7 * day
limit = 20

while since < to:
    end = since + week
    if end > to:
        end = to
    params = {'endAt': end}
    orders = exchange.fetch_closed_orders(symbol, since, limit, params)
    print(exchange.iso8601(since), '-', exchange.iso8601(end), len(orders), 'orders')
    if len(orders) == limit:
        since = orders[-1]['timestamp']
    else:
        since += week
    all_orders.extend(orders)```

**Comment by kroitor** [comment]
@jeee yep, something like that, thx!

**Comment by jeee** [comment]
that different for each exchange? on binance I get:
ExchangeError: binance {"code":-1101,"msg":"Too many parameters; expected '4' and received '5'."}

**Comment by kroitor** [comment]
@jeee params-overrides are exchange-specific: https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

If you switch to binance, you don't need to supply `params = {'endAt': end}` overrides, because their pagination works without that limitation, i think.

**Comment by Matoran** [comment]
Even with 7 days limit, it fails sometimes (even with 6 days). I fetch each day individually to avoid any issue.
