### ISSUE TITLE
CoinFalcon Exchange

### ISSUE THREAD

**Issue by jordansteeves** [ccxt/ccxt#677]
Hi! Please add our exchange API from here https://docs.coinfalcon.com/

**Comment by Deathamns** [comment]
Started working on it.

**Comment by jordansteeves** [comment]
Status?

**Comment by Deathamns** [comment]
@jordansteeves Someone needs to review/test it.

**Comment by jordansteeves** [comment]
Would love to get this added soon!

**Comment by kroitor** [comment]
Merged in #1127. Thx for your patience.
