### ISSUE TITLE
Replace 'has' with a 'features' structure?

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6772]
Could we consider replacing the 'has' properties with something like:

OKEX

        'features': {
            'fetchMarkets': {
                'supported': true,
                'emulated': false,
                'authenticated': false,
                'requiredParams': [],
            },
            'fetchCurrencies': {
                'supported': true,
                'emulated': false,
                'authenticated': true,
                'requiredParams': [],
            },
            'fetchClosedOrders': {
                'supported': true,
                'emulated': false,
                'authenticated': true,
                'requiredParams': ['symbol'],
            }
        }

**Comment by kroitor** [comment]
> Could we consider replacing the 'has' properties with something like:

Yep. In the end it should also support rate limit costs per endpoint / per unified method. So, we will most likely extend the 'api' definitions as well. Need to think on what would be the best structure for the extended metainfo...

**Comment by binares** [comment]
What I often find myself doing is deciding between whether to fetch (all)ticker(s) or orderbook, depending on whether the ticker has "bid(Volume)" and "ask(Volume)". Further more, it'd be convenient to have this has/has_not info for all dict keys, 
```
{
    'fetchTrades': {
        'contents': {
            'id': true,
            'order': false,
            'amount: true,
            'fee': false',
            ....
        },
    ....
}       
```
Granted, this is quite an extensive task.

**Comment by kroitor** [comment]
@binares we were thinking of adding a swagger-like JSON spec parser, since it is designed for the task, however, the specs themselves are often far from ideal. Anyways, we're going to start adding this feature soon, to cover most of it this year, hopefully.

**Comment by binares** [comment]
@kroitor Interesting idea. I assume parsing the fetch results, e.g. when the travis conducts tests after each commit, or from the user side?

**Comment by kroitor** [comment]
@binares yeah, we can try and read the spec upon every build.

**Comment by TensorTom** [comment]
Had posted in other issue:

"I'm looking for a property to know how far back of OHLCV data I can request for a given symbol. Is there one?"

Maybe for now I can find this info by coinmarketcap or coingecko

**Comment by untoreh** [comment]
another problem with `has`  is that some functions are set as supported (`true`), but only work on some markets. To avoid errors when expecting a function to work either one of these must be done:
- Only set it to true if it supports all markets
- Introduce a third value `partial` that implies the function doesn't work on all markets
- Specify for each market which functions are supported, but this is probably too expensive

**Comment by ttodua** [comment]
> another problem with `has` is that some functions are set as supported (`true`), but only work on some markets. To avoid errors when expecting a function to work either one of these must be done:
> 
> * Only set it to true if it supports all markets
> * Introduce a third value `partial` that implies the function doesn't work on all markets
> * Specify for each market which functions are supported, but this is probably too expensive

yes, that's right, and we have been talking to add the accurate/detailed metadata, to make it reliable. we will post an update in this  thread.

**Comment by ttodua** [comment]
Late update to this, but there is a PR to address this functionality, you can keep an eye on #6772 or announcement channels (https://t.me/ccxt_announcements or https://discord.com/channels/690203284119617602/1057748769690619984)
