### ISSUE TITLE
Composer Deprecation Notice

### ISSUE THREAD

**Issue by gioacchinopoletto** [ccxt/ccxt#6777]
For first time, installing thought Composer in a fresh project I receive these warnings (see below).
In other packages was caused by a `folder` being lower case while the source file was title case. 

`Deprecation Notice: Class ccxt\RequestTimeout located in ./vendor/ccxt/ccxt/php/base/errors.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201`

`Deprecation Notice: Class ccxt\Exchange located in ./vendor/ccxt/ccxt/php/base/Exchange.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201`

**Comment by rin4ik** [comment]
I get this warning as well. when it will be resolved @kroitor ?

**Comment by kroitor** [comment]
@rin4ik @gioacchinopoletto we're working on it right now, hope to upload the edits soon.

**Comment by joostvanhoof** [comment]
I'm on v1.41.96 and composer v2 and get `... does not comply with psr-4 autoloading standard. Skipping.` for multiple classes. If I read through the issues linked above I think you've been looking into this and it's related to converting the JS into PHP right? If you need more info please let me know.

**Comment by gioacchinopoletto** [comment]
> @rin4ik @gioacchinopoletto we're working on it right now, hope to upload the edits soon.

Good :-)

**Comment by gioacchinopoletto** [comment]
@kroitor many thanks!

**Comment by ttodua** [comment]
as of now, I don't get any such warning. if anyone will get any composer issue, feel free to open the issue.
