### ISSUE TITLE
Example request for ccxtpro

### ISSUE THREAD

**Issue by Hororohoruru** [ccxt/ccxt#6785]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Ubuntu 18
- Programming Language version: Python 3.7
- CCXT version: ccxtpro 0.1.51

I just started migrating an arbitrage bot from ccxt to ccxt pro. I am interested in watching tickers and performing an operation every time any of the tickers gets an update. I was checking the examples and found this:

https://github.com/ccxt/ccxt/blob/52a47d93f28cec731995c4fd56d39b2b3334689e/examples/ccxt.pro/py/one-exchange-many-streams.py#L20

It indeed serves to print the asks and bids from every symbol as soon as they get updated. How can one expand on this to run a particular function as soon as any of the functions running returns a new value?

**Comment by kroitor** [comment]
Hi!

> How can one expand on this to run a particular function as soon as any of the functions running returns a new value?

Just add your code to react to the update as soon as you receive it:

```
# -*- coding: utf-8 -*-
```
import asyncio
import ccxtpro

async def loop(exchange, symbol):
    while True:
        try:
            ticker = await exchange.watch_ticker(symbol)
            now = exchange.milliseconds()
            print(exchange.iso8601(now), symbol, ticker)

            # ADD YOUR REACTION TO THE UPDATE HERE
            # COULD BE ANYTHING INSTEAD OF PRINTING
            # USE DATABASES, DO CALCULATIONS, ETC...

        except Exception as e:
            print(str(e))
            # raise e  # uncomment to break all loops in case of an error in any one of them
            # break  # you can also break just this one loop if it fails

async def main():
    exchange = ccxtpro.poloniex({'enableRateLimit': True})
    symbols = ['BTC/USDT', 'ETH/USDT', 'ETH/BTC']
    await asyncio.gather(*[loop(exchange, symbol) for symbol in symbols])
    await exchange.close()

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

↑ Let me know if that does not help.

Feel free to reopen it or just ask further questions if any.

**Comment by Hororohoruru** [comment]
Hi Kroitor, thank you for your response. Maybe I did not explain what I intend to do correctly. My idea is not to do something in reaction to each update. 

Rather, I would need to gather 3 prices (one from each symbol, in the example), and then do something (say print). Then, do this action every time any of the symbols update with a new price, but always using the latest values from the 3 symbols. Does that make sense?

**Comment by kroitor** [comment]
@Hororohoruru hi!

> Does that make sense?

Yes, however, this is not a question about how to use CCXT Pro, this is more a question about how to use the asyncio to solve this task – i would highly recommend you to get more practice with the modern Python's async/await syntax. It can be done in multiple different ways, but to keep things clear, here's an example that does what you've described. 

From the example below you can see that the CCXT Pro code is not changed compared to the previous example, the only thing that did change – is the reaction to the updates, which is outside of CCXT Pro (you react how you want – it's your code).

```Python
# -*- coding: utf-8 -*-
import asyncio
import ccxtpro
from pprint import pprint

symbols = ['BTC/USDT', 'ETH/BTC']
all_tickers_by_symbol = {}

def react_to_ticker_update(exchange, all_tickers_by_symbol):
    # this method is called upon an update to any of the tickers
    # but only after all three of them have been received previously
    now = exchange.milliseconds()
    print('-------------------------------------------------------------------')
    print(exchange.iso8601(now), 'All tickers up to the moment:')
    for symbol in symbols:
        print('...............................................................')
        ticker = all_tickers_by_symbol[symbol]
        print(ticker['symbol'])
        pprint(exchange.omit(ticker, 'info'))

async def loop(exchange, symbol):
    while True:
        try:
            ticker = await exchange.watch_ticker(symbol)
            all_tickers_by_symbol[symbol] = ticker
            if len(all_tickers_by_symbol.keys()) == len(symbols):
                react_to_ticker_update(exchange, all_tickers_by_symbol)

        except Exception as e:
            print(str(e))
            # raise e  # uncomment to break all loops in case of an error in any one of them
            # break  # you can also break just this one loop if it fails

async def main():
    exchange = ccxtpro.poloniex({'enableRateLimit': True})
    await exchange.load_markets()
    await asyncio.gather(*[loop(exchange, symbol) for symbol in symbols])
    await exchange.close()

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

**Comment by Hororohoruru** [comment]
Indeed, I will follow your advice! Anyway, thank you very much for helping me out.
