### ISSUE TITLE
await bitmex.fetchMyTrades ()  -- Testnet

### ISSUE THREAD

**Issue by Gennttii** [ccxt/ccxt#6786]
Hi, 

Does this endpoint `await bitmex.fetchMyTrades ()`  work for bitmex testnet, because its not giving my trades, its giving public trades..

How do I get my closed trades in bitmex testnet?

Regards

**Comment by kroitor** [comment]
Hi! 

> Does this endpoint await bitmex.fetchMyTrades () work for bitmex testnet, because its not giving my trades, its giving public trades..

It should work, however, that depends on your instantiation code, how you switch to the testnet in particular. Can you elaborate a bit? We need some code to reproduce it.

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by Gennttii** [comment]
This is my exchange configuration code:

`const bitmex = new ccxt.bitmex ({ 
    apiKey: xx 
    secret: xx,
    'enableRateLimit': true ,
    'urls':
        {
            'api': {
                'public': 'https://testnet.bitmex.com',
                'private': 'https://testnet.bitmex.com',
            },
        }
});`

And this is the code to get trades but its not giving my trades..!:


` console.log(  await bitmex.fetchMyTrades  (  'BTC/USD' , since = undefined, limit = 499, params = {})  )
`

I use the same endpoint `fetchMyTrades  ` in real bitmex and it works, but its not working in testnet..

**Comment by kroitor** [comment]
@Gennttii can you post your verbose output? ↓

```JavaScript
const bitmex = new ccxt.bitmex ({ 
    apiKey: xx 
    secret: xx,
    'enableRateLimit': true,
});
bitmex.urls['api'] = bitmex.urls['test']
;(async () => {
    await bitmex.loadMarkets ();
    bitmex.verbose = true
    console.log (await bitmex.fetchMyTrades ('BTC/USD', undefined, 499))
}) ()
```
