### ISSUE TITLE
Ques: Margin trading unification ?

### ISSUE THREAD

**Issue by abhishekr700** [ccxt/ccxt#6790]
Hi,
I see margin trading is a pending task for Q2 as mentioned in the roadmap. I'm working on integrating a exchange and was wondering if there were any documentation on the future unified functions on margin trading so that I could implement them ? 
Or would it be better if I wait for the unification before going on to implement those in my exchange file ?

**Comment by kroitor** [comment]
Hi!

I suggest to wait until we upload the first documented specifications of the unified derivatives API to the Manual (currently working on those). We will also provide example implementations for some of the exchanges that have it, to make it easier to follow. Let me know if that does not answer the question. Thank you!
