### ISSUE TITLE
binance futures api watch_balance not working

### ISSUE THREAD

**Issue by codemonkeyno1** [ccxt/ccxt#6791]
- OS: Ubuntu 16.04.3
- Programming Language version: Python 3.7
- CCXT version: pro 0.1.52

Just subscribed to ccxtpro to hook up with the Binance futures api, but it seems none of the private "watch" methods are working.

exchange.fetchBalance from standard ccxt works perfectly, but calling exchange.watch_balance would give an error 1000 (message {"error":{"code":2,"msg":"Invalid request: streams must have non-zero length"},"id":1})

Has this feature already been built?  Binance futures has much more volume than the spot exchange, so it should be in much higher demand.

Thank you.

**Comment by kroitor** [comment]
> Has this feature already been built?

The derivatives unification is a work in progress, as well as the private streaming APIs. The  `watchBalance` method for Binance currently works with spot markets, but does not work with futures markets yet. The support for Binance futures watchBalance will be added before the end this month.

**Comment by kroitor** [comment]
More about it here: https://github.com/ccxt/ccxt/issues/6697

Let us know if that does not answer the question. Feel free to reopen this issue, or just ask further questions, if any.

**Comment by codemonkeyno1** [comment]
Igor, thank you for the quick reply.  Great to hear that it's being worked on.

I'm sure you are very busy currently with many differing priorities on this project, but if I may offer an opinion from an algo trading perspective, for websockets there are really only two critical private methods: open orders and open positions.  Everything else including checking balance, sending/canceling orders could be done using Rest without much impact on the functioning of the algo, but open orders and open positions need to be available in websocket properly before any minimal performance algo can be built.  I hope this could be taken into account for future ccxt pro development.

**Comment by kroitor** [comment]
@codemonkeyno1 thank you for the feedback!

> for websockets there are really only two critical private methods: open orders and open positions

Yep, we do understand and we agree – that functionality it is very important – and it is one of our topmost priorities.

> I hope this could be taken into account for future ccxt pro development.

Of course! Will keep you updated on our progress, stay tuned! Thx again!

**Comment by codemonkeyno1** [comment]
> The support for Binance futures watchBalance will be added before the end this month.

Igor, the watchBalance still seems to be giving an error 1000 when trying on Binance using 'options':{'defaultType':'future'}

Is this still to be expected, or is the issue on my end?

**Comment by kroitor** [comment]
@codemonkeyno1 it is not working for the futures yet, but the work on it is in progress and we will add that shortly.

**Comment by interzonez** [comment]
Hi @kroitor 

This is my next challenge - to convert my current python Binance rest script to watch and keep the connection active. Where's the best place to start for Binance watch_trades watch_orders watch_balance and how to convert from REST to WS? (assuming I need a WS connection for watch functions..)

Thank you.

**Comment by kroitor** [comment]
@interzonez Hi!

On WS – I'd recommend starting from here:

- https://ccxt.pro
- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual
- https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual#exchanges

**Comment by interzonez** [comment]
Thanks @kroitor Should I need to use ccxt.pro?

I had a bash here. Does this fulfill the ability to monitor my balance and positions and run the program indefinitely? It ***seems*** to work.. at least, it loops.. 


```
import asyncio
import os
import sys
import ccxt
import decimal
from decimal import *
from pprint import pprint
#import asyncio
#import ccxt.async_support as ccxt
from ccxt.base.decimal_to_precision import ROUND_DOWN, ROUND_UP

print('CCXT version:', ccxt.__version__)

import ccxt.async_support as ccxt

async def main(asyncio_loop):
    exchange = ccxt.binance({
        'asyncio_loop': asyncio_loop,
        'enableRateLimit': True,
        'apiKey': 'xxx',
        'secret': 'xxx',
        'options': {
            'defaultType': 'future',
            'fetch_balance': 'margin',
            'fetchPositions': 'positions',
        },
        'verbose': False,
    })
    while True:
        try:
#exchange.options['createMarketBuyOrderRequiresPrice'] = false

            #exchange.verbose = False
            #symbols = exchange.symbols
#symbol = [], since = [], limit = [], params = {}
            markets = await exchange.load_markets()
            balance = await exchange.fetch_balance()
            all_positions = balance['info']['positions']
#current_positions = [position for position in all_positions if float(position['unrealizedProfit']) >= -10 and float(position['unrealizedProfit']) <= -0.01]
#current_positions = [position for position in all_positions if float(position['unrealizedProfit']) <= -0.01]
            current_positions = [position for position in all_positions if float(position['unrealizedProfit']) <= -10.00 and float(position['positionAmt']) >= 0.01
            or float(position['unrealizedProfit']) <= -10.00 and float(position['positionAmt']) <= -0.01 ]
            current_amount = [amount for amount in current_positions if float(amount['positionAmt']) >= 0.01 or float(position['positionAmt']) <= -0.01] #and float(position['positionAmt']) >= 0.01]

            print(current_positions)
            print('=================================================')


            for position in current_positions:
                market_id = position['symbol']                             # added this
                market = exchange.markets_by_id[market_id]                 # added this
                symbol = market['symbol']                                  # added this
                print('--------------------------------------------------------------------')
                print('Market id:', market_id, 'symbol:', symbol)
                my_orders = exchange.fetch_open_orders(symbol)
                print(my_orders)
                #print('done')
# current_positions = [position for position in all_positions if float(position['unrealizedProfit']) <= -0.01 and float(position['positionAmt']) >= 0.01]
# current_amount = [amount for amount in all_positions if float(amount['positionAmt']) >= 0.01]

            print('=================================================')

            for amount in current_amount:
                amt = amount['positionAmt']
                if amt <= -0.01:
                    my_buys = exchange.createMarketBuyOrder(symbol = symbol, amount = abs(float(amount['positionAmt'])))
                    print(my_buys)
                elif amt >= 0.01:
                    my_sells = exchange.createMarketSellOrder(symbol = symbol, amount = abs(float(amount['positionAmt'])))
                    print(my_sells)

                    print('=================================================')

        except Exception as e:
            print('failed')
            #print(e)
            break
    await exchange.close()

if __name__ == '__main__':
    asyncio_loop = asyncio.get_event_loop()
    asyncio_loop.run_until_complete(main(asyncio_loop))
#print(current_amount)

```

**Comment by kroitor** [comment]
@interzonez 

> Should I need to use ccxt.pro?

It depends on your purposes. 
I'd say, you should only use ccxt.pro if you understand precisely whether you need it or not for your automated trading.
If you are not 100% sure – do not switch to ccxt.pro, since it's a paid subscription. Stick to the free CCXT up to a point where you get the expertise to understand the difference between RESTful APIs (CCXT) and WS APIs (CCXT Pro). You can use both CCXT and CCXT Pro, and you can think of CCXT Pro as of _"CCXT on steroids"_.
In general, you can do what you want with CCXT and CCXT Pro, however, with CCXT Pro your application will be more reactive. Whether you need the extra speed of CCXT Pro or not – is up to you. The loop you posted would be enough to track your balances and positions, and this type of loops in general is enough to do these things:

- day-to-day automated trading strategies
- rebalance strategies
- speculation strategies
- even some arbitrage

However, if you're after HFT (high-frequency trading), you might benefit from CCXT Pro if you're doing these things:

- market-making strategies
- scalping strategies
- other high-frequency trading

If you're not involved with HFT, just use CCXT until you get to the need of adding CCXT Pro naturally.

**Comment by interzonez** [comment]
Thanks @kroitor

That's a very helpful run down of different aspects of CCXT and CCXT Pro. For now I will be able to accomplish everything with CCXT and if needed later move to CCXT Pro.
