### ISSUE TITLE
Binance test url invalid

### ISSUE THREAD

**Issue by julesGoullee** [ccxt/ccxt#6792]
Binance test endpoint use Binance future, (https://testnet.binancefuture.com), which is not suitable for Binance exchange test environment

- CCXT version:  1.26.16

**Comment by kroitor** [comment]
> which is not suitable for Binance exchange test environment

They don't have a documented sandbox for spot markets. So, we can only support the futures testnet, until Binance adds a spot testnet. Let me know if that does not answer the question.

**Comment by julesGoullee** [comment]
Ok got it. But most of the endpoint for finance trading exclude future is not available, so until they have all ccxt requirement implemented, should we keep it there?

**Comment by kroitor** [comment]
> should we keep it there?

It was added to satisfy this request: https://github.com/ccxt/ccxt/issues/6779#issuecomment-612577577

We don't have hard requirements on the exchange testnets – if a testnet is available we do support it. At the same time, some of the testnet endpoints may not work. Let me know if I'm missing something.
