### ISSUE TITLE
how can i create contract order in huobipro

### ISSUE THREAD

**Issue by hanfeng1982** [ccxt/ccxt#6796]
- OS:all
- Programming Language version:python3.7.6
- CCXT version:1.26.18

how can i create contract order in huobipro?
exemple: 
   symbol :BTC 
   contract_type:next_week
   contract_code: BTC180914

**Comment by kroitor** [comment]
Duplicate: 

- https://github.com/ccxt/ccxt/issues/5923
- https://github.com/ccxt/ccxt/issues/6697

Let us know if that does not answer the question.
