### ISSUE TITLE
Kraken

### ISSUE THREAD

**Issue by kimasplund** [ccxt/ccxt#6797]
So since a few h ago i keep getting a error connecting to kraken. Worked fine in the morning but now its broken.

I guess this issue goes here :) 

> `  <hr>
>       </div>
>       <p>
>         Completing a CAPTCHA proves you are a human and gives you temporary access to this page.
>         <br>
>         Make sure your home and work devices are regularly scanned for malware to reduce the need to complete the CAPTCHA.
>         <hr>
>         RayID: 583e6192df92xxxx
>         <br>
>         IP: 46.xx.xx.xx
>       </p>
>     </div>
> 
>     <div class="l-v-padded">
>       <div lang="pt-br" class="err__additional-translation">
>         <h3>
>           Conclua essa verificação de segurança para acessar essa página
>         </h3>
>         <p class="l-top-padded">
>           Completar o CAPTCHA comprova que você é humano e fornece acesso temporário à página. Verifique regularmente seus dispositivos domésticos e comerciais quanto a infecções de malware para reduzir a necessidade de conclusão do CAPTCHA.
> `
> 
(tried to paste that in code but when its just in html it reformats it here :D .. 

But i contacted kranen about this and they blame ccxt...

> Hello Kim,
> 
> Thank you for your replies, and for providing the additional information about your issue.
> 
> It seems that the CCXT library is trying to retrieve some data (possibly the minimum order sizes) from our support pages, and that due to the Zendesk security settings, a captcha page is returned instead of the actual support page.
> 
> A similar issue occurred two weeks ago, but was resolved very quickly when CCXT updated their code to make retrieving the minimum order sizes optional instead of required. At that time, updating the CCXT library to the most recent version resolved the issue, but it appears that a subsequent version has reverted back to requiring some data from our support pages (this has not been confirmed with CCXT though).
> 
> We would be happy to provide any data that is needed from our support pages in another format (such as the minimum order sizes in CSV format), or alternatively, if you reach out to CCXT support, they should be able to assist you in resolving the issue successfully.
> 
> I hope that this helps. Please let us know if we can assist you further with this issue.

**Comment by kroitor** [comment]
Duplicates:

- https://github.com/ccxt/ccxt/issues/6795#issuecomment-613451098
- https://github.com/ccxt/ccxt/issues/6700
- https://github.com/ccxt/ccxt/issues/6701

Kraken's official answer: 

> we are aware of the recent issue that CCXT experienced when a security change to our support pages prevented the minimum order sizes from being retrieved via our support pages. Our REST API developers are in the process of adding the minimum order sizes to the REST API AssetPairs endpoint, which would make the minimum order sizes available more efficiently (and more reliably). We do not yet have an expected availability date for this update, but I will keep track of the progress, and let you know when more information is available.

In the meantime, you can workaround the issue, by setting `fetchMinOrderAmounts` option to `false`. 

```Python
exchange = ccxt.kraken({
    'enableRateLimit': True,
    'options': {  # ←--------------------- inside 'options' subkey
        'fetchMinOrderAmounts': False,  # ←---------- set to False 
    }
})
```

That way you will effectively lose the information about the minimal limits, but the other functionality will keep working.

Let me know if that does not answer the question.

**Comment by kroitor** [comment]
@kimasplund i've set that option to `false` by default until Kraken adds the info on min limits to their API. This is in effect as of CCXT version 1.26.20+. It will arrive in 15 minutes.

**Comment by kimasplund** [comment]
Aah ok great :)

Chers m8!
