### ISSUE TITLE
Bitmex invalid stopPx for ordType for Stop orders

### ISSUE THREAD

**Issue by JavierRSobrino** [ccxt/ccxt#6802]
- OS: OSX
- Programming Language version: node 13
- CCXT version: ccxt@1.26.26

When I try to use `Stop`, `StopLimit`, `MarketIfTouched`, `LimitIfTouched` orders with Bitmex, and the price is above (when longing) or below (when shorting) I always get this error:

```
InvalidOrder: bitmex {"error":{"message":"Invalid stopPx for ordType","name":"HTTPError"}}

```
For example with:

```
exchange.createOrder('BTC/USD', 'LimitIfTouched', 'buy', 1000, 8500);
```

The expected behavior is that the exchange should let me place the order, as it supports it. For some reason, ccxt doesn't pass the price correctly for those types of orders. These orders are similar to the old "take profit" concept. More info here https://www.bitmex.com/api/explorer/#!/Order/Order_new

**Comment by kroitor** [comment]
@JavierRSobrino can you plz post your verbose output?

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

In short, this message

> Invalid stopPx for ordType

says that you're not supplying the `stopPx` param which is required for that exchange. In order to supply it, see https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

```JavaScript
const params = { 'stopPx': YOUR_VALUE_HERE }  // ←-------- ↓
exchange.createOrder (symbol, type, side, price, amount, params)
```

**Comment by JavierRSobrino** [comment]
Thank you, I placed the parameter, and I got another error:
```
BadRequest: bitmex {"error":{"message":"Invalid stopPx tickSize","name":"HTTPError"}}
```
Verbose is on btw.

Code was:
```
exchange.createOrder('BTC/USD', 'Stop', 'buy', 1000, undefined, {'stopPx': 8500.3423});
```

`price` had to be `undefined` or I get an error.

So I used `Math.round` and now it works.

```
exchange.createOrder('BTC/USD', 'Stop', 'buy', 1000, undefined, {'stopPx': Math.round (8500.3423)});
```
Thanks.

**Comment by kroitor** [comment]
@JavierRSobrino thx for reporting back! Just in case, you may also want to look into this: https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits
Let us know if you have further questions.

**Comment by JavierRSobrino** [comment]
Thank you for the support.
I have another question if you don't mind: **is there an universal way to place stop orders?**
I ask because I plan to use my bot on multiple exchanges, so it would be nice to have the same createOrder parameters for all.

**Comment by kroitor** [comment]
>  is there an universal way to place stop orders?

Placing conditional orders is actually one of the aspects that we are working on right now very actively. It is not unified yet, but hopefully, will be unified soon. More about it here: https://github.com/ccxt/ccxt/issues/6697

> so it would be nice to have the same createOrder parameters for all

Sure, we know, and this is the whole purpose of the unification, so we will have it eventually. In the meantime, some exchange-specific code may be required for this or that exchange.

**Comment by JavierRSobrino** [comment]
> @JavierRSobrino thx for reporting back! Just in case, you may also want to look into this: https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits
> Let us know if you have further questions.

Sorry to bother you, but it seems that precision property doesn't work, I haver this code:

```
operation.entryPrice = this.ccxt.decimalToPrecision(
	operation.entryPrice,
	this.ccxt.ROUND,
	this.markets[symbol.id].precision,
	this.ccxt.DECIMAL_PLACES
);

```
Being `symbol.id='BTC/USD'` and the returned value is  `operation.entryPrice=6797.967918052531`, but Bitmex only accepts 1 digit for that pair, so the same error is returned when trying to open the position using custom stop order:
```
BadRequest: bitmex {"error":{"message":"Invalid stopPx tickSize","name":"HTTPError"}}

```
Is this a bug or am I doing something wrong?

I placed the question here instead of opening an issue because it is not clear if I did something wrong.

**Comment by kroitor** [comment]
@JavierRSobrino i hope that you have the precision question resolved.
