### ISSUE TITLE
Is it possible to Place Multiple Orders Binance

### ISSUE THREAD

**Issue by albatarnik** [ccxt/ccxt#6805]
Hi 

In Binance futures there an [endpoint](https://binance-docs.github.io/apidocs/futures/en/#new-order-trade) to place multiple orders in one request.  Is there a method to do that? I am using Python. 

If not exist, what's the best way to add a custom method for it?

**Comment by kroitor** [comment]
>  Is there a method to do that? I am using Python.

Nope, at this time we don't have a unified method for placing orders in bulk, but will add that asap.

In the meantime, you can still use that endpoint in an exchange-specific way using the implicit API methods, as explained in the Manual here: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods. You can call any endpoint this way.

Let us know if that does not answer the question. Feel free to reopen it or just ask further questions if any. Will do our best to unify aspect asap, stay tuned for new announcements and updates.

**Comment by albatarnik** [comment]
@kroitor  Thank you for your fast reply.
Implicit API seems like a great solution for me. 
I try it and I am getting this error 
```AttributeError: 'binance' object has no attribute 'fapiPrivatePostBatchOrders'```

I went `define_rest_api` method to check the code
I print this line
`camelcase = api_type + camelcase_method + Exchange.capitalize(camelcase_suffix)`

I don't see my method `fapiPrivatePostBatchOrders` but I find other similar ones like `fapiPrivateGetPositionRisk` which works for me. 

Should I add it somewhere to make it work? it seems the code check my method against the available Binance endpoints, it doesn't find it and then throw an error.

**Comment by kroitor** [comment]
> Should I add it somewhere to make it work?

Nope, sorry, it was introduced not so long ago, so it wasn't available in the previous CCXT versions. However, I've uploaded the necessary definitions now, and if you update to the most recent CCXT version 1.26.42+ – you will see that method there. Pardon for not mentioning this. Let me know if you still have issues after upgrading. Thx for reporting!

**Comment by albatarnik** [comment]
@kroitor I really appreciate your fast response. I pulled the latest version, and I see `batchOrders` in binance.py

It was added to `get` array, I think it should be added to `post` and `delete` instead. 
I did that and it worked. 
Thanks again.

**Comment by kroitor** [comment]
@albatarnik yes, you're right, i should've paid more attention, fixed it in 1.26.43, the new build will arrive in 15 minutes. Thx again for your involvement!

**Comment by albatarnik** [comment]
@kroitor 

Do you have any idea why I am getting this error ? 
`{'code': -1130, 'msg': "Data sent for parameter 'batchOrders:[{'symbol': 'BTCUSDT', 'side': 'BUY
', 'positionSide': 'LONG', 'type': 'MARKET', 'quantity': 0.005}]' is not valid."}`

```
params =  {'batchOrders' : 
            [{
                "symbol" : "BTCUSDT",
                "side" : "BUY",
                "positionSide" : "LONG",
                "type" : "MARKET",
                "quantity": float(0.005)
            }]  
    }
    return ccxt.binance(keys).fapiPrivatePostBatchOrders(params)
   
```
I use the same exact order parameter for post single order and it works. 
```
 return ccxt.binance(keys).fapiPrivatePostOrder( {
                "symbol" : "BTCUSDT",
                "side" : "BUY",
                "positionSide" : "LONG",
                "type" : "MARKET",
                "quantity": float(0.005)
            })
```
`batchOrder` should be a list according to binance docs, am I passing something wrong ?

**Comment by kroitor** [comment]
@albatarnik i think it has to be JSON-encoded. If you could follow the Manual precisely and use the *verbose* mode, you can see what exactly is being sent to the exchange and whether or not it matches the format expected by the exchange:

```Python
exchange = ccxt.binance(keys)
exchange.verbose = True
params = {
    'batchOrders' : exchange.json ([{
        "symbol" : "BTCUSDT",
        "side" : "BUY",
        "positionSide" : "LONG",
        "type" : "MARKET",
        "quantity": float(0.005)
    }])
}
exchange.fapiPrivatePostOrder(params)
```

Apart from that, the above error may be returned by the exchange if you're missing a required field somewhere, or if the values in those fields don't match the exchange specification. Let me know if that does not help.

**Comment by albatarnik** [comment]
@kroitor I am sure there is no missing parameter, do you think I need to encode batchOrders to JSON   to pass it as a list?

**Comment by kroitor** [comment]
> do you think I need to encode batchOrders to JSON to pass it as a list?

Nope, the params probably have to be urlencoded with array repeat. However, it's hard to tell the exact cause without the verbose output from you. Can you share it?

**Comment by albatarnik** [comment]
@kroitor 

Does that help ? 
```
Request: POST https://testnet.binancefuture.com/fapi/v1/batchOrders {'X-MBX-APIKEY': '', 'Content-Type': 'application/x-www-form
-urlencoded', 'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate'} timest
amp=1587060926204&recvWindow=5000&batchOrders=%5B%7B%27symbol%27%3A+%27BTCUSDT%27%2C+%27side%27%
3A+%27BUY%27%2C+%27positionSide%27%3A+%27LONG%27%2C+%27type%27%3A+%27MARKET%27%2C+%27quantity%27
%3A+0.005%7D%5D&signature=d389df8d64b7d098fb8d16aa300c2e85b06810e41da3e6049135366c4af9d8f1

Response: POST https://testnet.binancefuture.com/fapi/v1/batchOrders 400 {'Content-Type': 'appli
cation/json', 'Content-Length': '174', 'Connection': 'keep-alive', 'Date': 'Thu, 16 Apr 2020 18:
15:27 GMT', 'Server': 'Tengine', 'X-MBX-USED-WEIGHT-1M': '10', 'x-response-time': '2ms', 'X-Fram
e-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosnif
f', 'Referrer-Policy': 'origin-when-cross-origin', 'Strict-Transport-Security': 'max-age=3153600
0; includeSubdomains', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 14eb24c973f72cd7fdce7ebf5
a06b76e.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'GRU50', 'X-Amz-Cf-Id': '48fMpwrr4pkJJvDBU
L1AJO5W3acqqUv5vH-LiLJcmnaj3IiXQpRyEw=='} {"code":-1130,"msg":"Data sent for parameter 'batchOrders:[{'symbol': 'BTCUSDT', 'side': 'BUY', 'positionSide': 'LONG', 'type': 'MARKET', 'quantity': 0.005}]' is not valid."}

```

**Comment by kroitor** [comment]
Actually, yes, from Binance docs it looks like the orders have to be JSON-encoded:

<img width="787" alt="Screen Shot 2020-04-16 at 21 18 10" src="https://user-images.githubusercontent.com/1294454/79491896-ce36d000-8027-11ea-8569-124e63c6fbe4.png">

So my previous answer turns out to be correct, and the following should work:

```Python
exchange = ccxt.binance(keys)
exchange.verbose = True
params = {
    'batchOrders' : exchange.json([{
        "symbol" : "BTCUSDT",
        "side" : "BUY",
        "positionSide" : "LONG",
        "type" : "MARKET",
        "quantity": float(0.005)
    }])
}
exchange.fapiPrivatePostOrder(params)
```

Let me know if not.

**Comment by kroitor** [comment]
Also, you seem to be using a wrong endpoint for batch orders.

```Python
exchange.fapiPrivatePostOrder(params)
```

↓

```Python
exchange.fapiPrivatePostBatchOrders(params)
```

↓

```Python
exchange = ccxt.binance(keys)
exchange.verbose = True
params = {
    'batchOrders' : exchange.json([{
        "symbol" : "BTCUSDT",
        "side" : "BUY",
        "positionSide" : "LONG",
        "type" : "MARKET",
        "quantity": float(0.005)
    }])
}
exchange.fapiPrivatePostBatchOrders(params)
```

**Comment by albatarnik** [comment]
Now, I am getting 400 error

```
Request: POST https://testnet.binancefuture.com/fapi/v1/batchOrders {'X-MBX-APIKEY': '', 'Content-Type': 'application/x-www-form
-urlencoded', 'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate'} timest
amp=1587061424110&recvWindow=5000&batchOrders=%5B%7B%22symbol%22%3A%22BTCUSDT%22%2C%22side%22%3A
%22BUY%22%2C%22positionSide%22%3A%22LONG%22%2C%22type%22%3A%22MARKET%22%2C%22quantity%22%3A0.005
%7D%5D&signature=43d4a60211f775d9c4fd4a52e83775e473d369d2cef1ccba47940e2294367fef

Response: POST https://testnet.binancefuture.com/fapi/v1/batchOrders 200 {'Content-Type': 'appli
cation/json', 'Content-Length': '38', 'Connection': 'keep-alive', 'Date': 'Thu, 16 Apr 2020 18:2
3:44 GMT', 'Server': 'Tengine', 'X-MBX-USED-WEIGHT-1M': '10', 'x-response-time': '2ms', 'X-Frame
-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff
', 'Referrer-Policy': 'origin-when-cross-origin', 'Strict-Transport-Security': 'max-age=31536000
; includeSubdomains', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 15a4ef612eb4a403e8f2af31a48
09e22.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'GRU1-C1', 'X-Amz-Cf-Id': 'McbMj-fDcD694vj0k
cqiIei8gNxs_m0bXMnca2T3iYSEA3CTZ2EJgQ=='} [ {
  "code" : 400,
  "msg" : null
} ]
```

**Comment by kroitor** [comment]
@albatarnik to me the above request looks correct, I mean it matches the exchange-specs. I'm not entirely sure if you should specify the positionSide, since it's optional. You might want to send the above verbose output to Binance tech support for comments.

**Comment by kroitor** [comment]
@albatarnik actually, after looking more carefully into it – the apiKey is empty in the request, which is not normal.

**Comment by albatarnik** [comment]
@kroitor I just removed, it's actually there. Do you know where can I contact the binance support team ?

**Comment by kroitor** [comment]
@albatarnik yep, you can find Binance's support form here: https://binance.zendesk.com/hc/en-us/requests/new

**Comment by kroitor** [comment]
@albatarnik we will be happy if you report back whether you have a resolution on it or not. Thx for for your involvement!

**Comment by albatarnik** [comment]
@kroitor 

I got a response from binance, it seems like the encoding we are sending isn't correct. 

```
import requests
url = "https://testnet.binancefuture.com/fapi/v1/batchOrders?batchOrders=[%7B%22symbol%22:%22BNBUSDT%22,%22side%22:%22BUY%22,%22type%22:%22MARKET%22,%22quantity%22:%221%22%7D,%7B%22symbol%22:%22BTCUSDT%22,%22side%22:%22BUY%22,%22type%22:%22MARKET%22,%22quantity%22:%221%22%7D]&timestamp=1587121469865&signature=x"

payload = {}
headers = {
  'X-MBX-APIKEY': 'x'
}

response = requests.request("POST", url, headers=headers, data = payload)

print(response.text.encode('utf8'))
===
```
_Please make sure in the parameter, you have encoded the {, } and "
Please kindly click this link https://dev.binance.vision/t/how-to-place-batch-orders-for-tutures/86 to get more details._

I noticed that we're encoding: `[ :` to `%5B %3A` and they are not in their example


http://snpy.in/qPMBHD

**Comment by kroitor** [comment]
@albatarnik i'll try to add a workaround, this is really a very non-standard format...

**Comment by kroitor** [comment]
Hi @albatarnik !


I've added the workaround to support the above custom format.
First of, please update to the most recent version of CCXT 1.26.48+.

After that you should be able to place batch orders with Binance as shown in the example below:

- https://github.com/ccxt/ccxt/blob/master/examples/py/binance-batch-orders.py

```Python
# -*- coding: utf-8 -*-

import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402


exchange = ccxt.binance({
    "apiKey": "YOUR_API_KEY",
    "secret": "YOUR_SECRET",
    'enableRateLimit': True,
})


orders = [
    {
        "symbol" : "BTCUSDT",
        "side" : "BUY",
        "positionSide" : "LONG",
        "type" : "MARKET",
        "quantity": float(0.005)
    }
]

orders = [exchange.encode_uri_component(exchange.json(order), safe=",") for order in orders]
response = exchange.fapiPrivatePostBatchOrders({
    'batchOrders': '[' + ','.join(orders) + ']'
})

print(response)

```

Let me know if you still have issues or difficulties with the above.
Your feedback and involvement is really appreciated! Thx for reporting!

**Comment by albatarnik** [comment]
@kroitor Thanks for your response. I tried your code above and it didn't work. I pulled your latest changes. Here is the request and response: 

```
Request: POST https://testnet.binancefuture.com/fapi/v1/batchOrders {'X-MBX-APIKEY': 'e86f09b85a
7f79e45c331fe84be1688a50e6ca449dbfc60bd2f842192a1f4ddf', 'Content-Type': 'application/x-www-form
-urlencoded', 'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate'} timest
amp=1587223783494&recvWindow=5000&batchOrders=[%7B%22symbol%22%3A%22BTCUSDT%22,%22side%22%3A%22B
UY%22,%22positionSide%22%3A%22LONG%22,%22type%22%3A%22MARKET%22,%22quantity%22%3A0.005%7D]&signa
ture=910e0614b6303a209662c5bfe94371fec09bbf3acd2c09995d23a352964500b9

Response: POST https://testnet.binancefuture.com/fapi/v1/batchOrders 200 {'Content-Type': 'appli
cation/json', 'Content-Length': '38', 'Connection': 'keep-alive', 'Date': 'Sat, 18 Apr 2020 15:2
9:44 GMT', 'Server': 'Tengine', 'X-MBX-USED-WEIGHT-1M': '5', 'x-response-time': '2ms', 'X-Frame-
Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff'
, 'Referrer-Policy': 'origin-when-cross-origin', 'Strict-Transport-Security': 'max-age=31536000;
 includeSubdomains', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 50ce56bec268bf575e1bbaec13e9
9609.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'GRU1-C1', 'X-Amz-Cf-Id': 'wgti_DxuXC4Xb1jL2A
XfVvZMQm3roHAwrZYc0e4asE7uNx3NTmtJVQ=='} [ {
  "code" : 400,
  "msg" : null
} ]
```

**Comment by albatarnik** [comment]
It worked, thank you. I really appreciate your fast response!

**Comment by mickeyahs** [comment]
Hi,

I have the same error when trying to post 5 orders using fapiPrivatePostBatchOrders:
`
exchange = open_exchange_connection(my_api, my_secret)
side = 'BUY'

orders = [
        {'symbol': 'BTCUSDT', 'type': 'LIMIT', 'price': 7000, 'timeInForce': 'GTC', 'side': side, 'reduceOnly': False, 'quantity': 0.001},
        {'symbol': 'BTCUSDT', 'type': 'LIMIT', 'price': 6000, 'timeInForce': 'GTC', 'side': side, 'reduceOnly': False, 'quantity': 0.002},
        {'symbol': 'BTCUSDT', 'type': 'LIMIT', 'price': 5000, 'timeInForce': 'GTC', 'side': side, 'reduceOnly': False, 'quantity': 0.003},
        {'symbol': 'BTCUSDT', 'type': 'LIMIT', 'price': 4000, 'timeInForce': 'GTC', 'side': side, 'reduceOnly': False, 'quantity': 0.004},
        {'symbol': 'BTCUSDT', 'type': 'LIMIT', 'price': 3000, 'timeInForce': 'GTC', 'side': side, 'reduceOnly': False, 'quantity': 0.005}
    ]

    orders = [exchange.encode_uri_component(exchange.json(order), safe=",") for order in orders]

    print(orders)

    response = exchange.fapiPrivatePostBatchOrders({
        'batchOrders': '[' + ','.join(orders) + ']'
    })

    print(response)
`

And here is what I get:
`
['%7B%22symbol%22%3A%22BTCUSDT%22,%22type%22%3A%22LIMIT%22,%22price%22%3A7000,%22timeInForce%22%3A%22GTC%22,%22side%22%3A%22BUY%22,%22reduceOnly%22%3Afalse,%22quantity%22%3A0.001%7D', '%7B%22symbol%22%3A%22BTCUSDT%22,%22type%22%3A%22LIMIT%22,%22price%22%3A6000,%22timeInForce%22%3A%22GTC%22,%22side%22%3A%22BUY%22,%22reduceOnly%22%3Afalse,%22quantity%22%3A0.002%7D', '%7B%22symbol%22%3A%22BTCUSDT%22,%22type%22%3A%22LIMIT%22,%22price%22%3A5000,%22timeInForce%22%3A%22GTC%22,%22side%22%3A%22BUY%22,%22reduceOnly%22%3Afalse,%22quantity%22%3A0.003%7D', '%7B%22symbol%22%3A%22BTCUSDT%22,%22type%22%3A%22LIMIT%22,%22price%22%3A4000,%22timeInForce%22%3A%22GTC%22,%22side%22%3A%22BUY%22,%22reduceOnly%22%3Afalse,%22quantity%22%3A0.004%7D', '%7B%22symbol%22%3A%22BTCUSDT%22,%22type%22%3A%22LIMIT%22,%22price%22%3A3000,%22timeInForce%22%3A%22GTC%22,%22side%22%3A%22BUY%22,%22reduceOnly%22%3Afalse,%22quantity%22%3A0.005%7D']
[{'code': 400, 'msg': None}, {'code': 400, 'msg': None}, {'code': 400, 'msg': None}, {'code': 400, 'msg': None}, {'code': 400, 'msg': None}]
`

Can someone please help?

**Comment by kroitor** [comment]
@mickeyahs hi! how do you initialize the exchange? what's your version of CCXT ?

**Comment by mickeyahs** [comment]
hi @kroitor,

```
def open_exchange_connection(api='', secret=''):
    exchange = ccxt.binance(dict(apiKey=api, secret=secret, timeout=30000, enableRateLimit=True,
                                 urls={
                                     'api': {
                                         'public': 'https://fapi.binance.com/fapi/v1'
                                     }
                                 },
                                 options={
                                     'defaultType': 'future',
                                     'adjustForTimeDifference': True
                                 }
                                 ))
    return exchange
```

import ccxt
ccxt.__version__
'1.27.1'

**Comment by kroitor** [comment]
@mickeyahs do you have the same issue with the most recent version 1.33.97?

**Comment by mickeyahs** [comment]
@kroitor 
Yes, just updated to 1.33.97,
same issue

**Comment by kroitor** [comment]
Let's try one order first:

```Python
import ccxt
from pprint import pprint


print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future',
        'adjustForTimeDifference': True,
    },
})

markets = exchange.load_markets()

exchange.verbose = True  # for debugging purposes

symbol = 'BTC/USDT'
type = 'limit'
side = 'buy'  # or 'sell'
amount = YOUR_AMOUNT_HERE
price = YOUR_PRICE_HERE

order = exchange.create_order(symbol, type, side, amount, price)
pprint(order)
```

↑ Edit this snippet for your values and run it, then copypaste the verbose request+response output here.

**Comment by mickeyahs** [comment]
the code above works for me:

```
CCXT Version: 1.33.97

Request: POST https://fapi.binance.com/fapi/v1/order {'X-MBX-APIKEY': 'XXX', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1599212777156&recvWindow=5000&symbol=BTCUSDT&type=LIMIT&side=BUY&quantity=0.001&price=5000&timeInForce=GTC&signature=215be7f38393b1318b92962c2bce503c2c306706e0ca039627f07f1deb41c6eb

Response: POST https://fapi.binance.com/fapi/v1/order 200 {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Fri, 04 Sep 2020 09:46:17 GMT', 'Server': 'Tengine', 'Vary': 'Accept-Encoding', 'X-MBX-USED-WEIGHT-1M': '121', 'X-MBX-ORDER-COUNT-1M': '1', 'x-response-time': '5ms', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'origin-when-cross-origin', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 5e71ebbd3e768e1e564c88b3632039d8.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'WAW50-C1', 'X-Amz-Cf-Id': 'tRmufuxl6BAeCTEPhlBOSz0rwS9v2N5As8AsAyEOmK7Sw7zJ5rhrpw=='} {"orderId":7121690026,"symbol":"BTCUSDT","status":"NEW","clientOrderId":"iNfanfAWwGugmpELqzWOCx","price":"5000","avgPrice":"0.00000","origQty":"0.001","executedQty":"0","cumQty":"0","cumQuote":"0","timeInForce":"GTC","type":"LIMIT","reduceOnly":false,"closePosition":false,"side":"BUY","positionSide":"BOTH","stopPrice":"0","workingType":"CONTRACT_PRICE","priceProtect":"false","origType":"LIMIT","updateTime":1599212777448}
{'amount': 0.001,
 'average': None,
 'clientOrderId': 'iNfanfAWwGugmpELqzWOCx',
 'cost': 0.0,
 'datetime': None,
 'fee': None,
 'filled': 0.0,
 'id': '7121690026',
 'info': {'avgPrice': '0.00000',
          'clientOrderId': 'iNfanfAWwGugmpELqzWOCx',
          'closePosition': False,
          'cumQty': '0',
          'cumQuote': '0',
          'executedQty': '0',
          'orderId': 7121690026,
          'origQty': '0.001',
          'origType': 'LIMIT',
          'positionSide': 'BOTH',
          'price': '5000',
          'priceProtect': 'false',
          'reduceOnly': False,
          'side': 'BUY',
          'status': 'NEW',
          'stopPrice': '0',
          'symbol': 'BTCUSDT',
          'timeInForce': 'GTC',
          'type': 'LIMIT',
          'updateTime': 1599212777448,
          'workingType': 'CONTRACT_PRICE'},
 'lastTradeTimestamp': None,
 'price': 5000.0,
 'remaining': 0.001,
 'side': 'buy',
 'status': 'open',
 'symbol': 'BTC/USDT',
 'timestamp': None,
 'trades': None,
 'type': 'limit'}

Process finished with exit code 0
```

**Comment by mickeyahs** [comment]
@kroitor do you experience the same issue?

**Comment by kroitor** [comment]
@mickeyahs i'll debug it and will get back to you asap.

**Comment by mickeyahs** [comment]
@kroitor thanks a lot

**Comment by mickeyahs** [comment]
@kroitor hi,
any news about this issue?

**Comment by kroitor** [comment]
@mickeyahs i'll do my best to get it resolved as soon as I can, within a few hours, hopefully. Thx for your patience!

**Comment by mickeyahs** [comment]
@kroitor hi,

did you manage to debug it?

**Comment by kroitor** [comment]
@mickeyahs working on it rn

**Comment by kroitor** [comment]
@mickeyahs ok, please, try this snippet now:

```Python
import ccxt
from pprint import pprint


print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    "apiKey": 'YOUR_API_KEY',
    "secret": 'YOUR_SECRET',
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future',
        'adjustForTimeDifference': True,
    },
})

markets = exchange.load_markets()

balance = exchange.fetch_balance()
pprint(balance)

symbol = 'BTC/USDT'
type = 'limit'
side = 'buy'  # or 'sell'
amount = 0.01
price = 5000

market = exchange.market(symbol)

orders = [
    {
        'symbol' : market['id'],
        'side' : side.upper(),
        'type' : type.upper(),
        'quantity': exchange.amount_to_precision(symbol, amount),
        'price': exchange.price_to_precision(symbol, price),
        'timeInForce': 'GTC',
    }
]

orders = [exchange.encode_uri_component(exchange.json(order), safe=",") for order in orders]

exchange.verbose = True  # for debugging purposes

response = exchange.fapiPrivatePostBatchOrders({
    'batchOrders': '[' + ','.join(orders) + ']'
})

pprint(response)
```

↑ Please, paste your verbose output here.

**Comment by mickeyahs** [comment]
Looks like it worked:

```
Request: POST https://fapi.binance.com/fapi/v1/batchOrders {'X-MBX-APIKEY': 'UWHhjjxIJ3bSe3qQ6ybxO12Y4yRqBXBqHc4i2LIKBpKMF6xJvi4DcfSmhNV4XtVM', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1599920654294&recvWindow=5000&batchOrders=[%7B%22symbol%22%3A%22BTCUSDT%22,%22side%22%3A%22BUY%22,%22type%22%3A%22LIMIT%22,%22quantity%22%3A%220.01%22,%22price%22%3A%225000%22,%22timeInForce%22%3A%22GTC%22%7D]&signature=1a8dd99abc5e5b8ffa79b77fafb260d3370df0eacc0fe722e8ebab9f7d4b74c8

Response: POST https://fapi.binance.com/fapi/v1/batchOrders 200 {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Sat, 12 Sep 2020 14:24:14 GMT', 'Server': 'Tengine', 'Vary': 'Accept-Encoding', 'X-MBX-USED-WEIGHT-1M': '50', 'X-MBX-ORDER-COUNT-1M': '1', 'x-response-time': '5ms', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'origin-when-cross-origin', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 f62050e21268ac5026b6ccb68a1f0a2b.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'WAW50-C1', 'X-Amz-Cf-Id': 'TrgNODlG0CifD9SYndFkGCde3i4ODTzkQytXcbh6WSV_wKlTC7veJw=='} [ {
  "orderId" : 7383208635,
  "symbol" : "BTCUSDT",
  "status" : "NEW",
  "clientOrderId" : "DNSB5JCFI6gvt8CoRPvqWa0",
  "price" : "5000",
  "avgPrice" : "0.00000",
  "origQty" : "0.010",
  "executedQty" : "0",
  "cumQty" : "0",
  "cumQuote" : "0",
  "timeInForce" : "GTC",
  "type" : "LIMIT",
  "reduceOnly" : false,
  "closePosition" : false,
  "side" : "BUY",
  "positionSide" : "BOTH",
  "stopPrice" : "0",
  "workingType" : "CONTRACT_PRICE",
  "priceProtect" : "false",
  "origType" : "LIMIT",
  "updateTime" : 1599920654604
} ]
[{'avgPrice': '0.00000',
  'clientOrderId': 'DNSB5JCFI6gvt8CoRPvqWa0',
  'closePosition': False,
  'cumQty': '0',
  'cumQuote': '0',
  'executedQty': '0',
  'orderId': 7383208635,
  'origQty': '0.010',
  'origType': 'LIMIT',
  'positionSide': 'BOTH',
  'price': '5000',
  'priceProtect': 'false',
  'reduceOnly': False,
  'side': 'BUY',
  'status': 'NEW',
  'stopPrice': '0',
  'symbol': 'BTCUSDT',
  'timeInForce': 'GTC',
  'type': 'LIMIT',
  'updateTime': 1599920654604,
  'workingType': 'CONTRACT_PRICE'}]

Process finished with exit code 0
```

**Comment by kroitor** [comment]
@mickeyahs alright, so, from there you just add up to 5 orders to the array in the same manner. Make sure to cancel the temporary debugging orders ) Let me know if you have further questions or difficulties.

**Comment by mickeyahs** [comment]
yes, it works fine with 5. thanks a lot for investigation and help!
have a nice weekend 👍

**Comment by AkshaySapra** [comment]
@kroitor Are there any prospects of working on batch orders for other exchanges as well? Thank so much.

**Comment by kroitor** [comment]
@AkshaySapra we'll add that as soon as we can, though it might take some time, since it's not super-easy to unify.

**Comment by AkshaySapra** [comment]
> @AkshaySapra we'll add that as soon as we can, though it might take some time, since it's not super-easy to unify.

Ahh, makes sense. I just realized that even with Binance, this functionality only allows for 5 orders at a time. Looks like I'll just have to use exchange-specific endpoints. Thanks!

**Comment by josipbudzaki** [comment]
I had the same troubles with `{'code': 400, 'msg': None}` - In the end, I just had to convert all `int` and `float` params to `str`.

**Comment by KhalidOuaz** [comment]
Hi, the requests are launched synchronously ?
Must an order to be respected?
Thank!

**Comment by minhnhat-dev** [comment]
batchOrders: JSON.stringify([{
                "side": "BUY",
                "positionSide": "BOTH",
                "symbol": "TRXUSDT",
                "type": "STOP_MARKET",
                "quantity": '125',
                "stopPrice": "0.07777",
                "workingType": "CONTRACT_PRICE",
                "reduceOnly": "false",
            }])
            It's work for me,use JSON.stringify()
