### ISSUE TITLE
Kraken `fetch` methods raising ExchangeNotAvailable

### ISSUE THREAD

**Issue by ethanbrown3** [ccxt/ccxt#6809]
- OS: Mac OS 10.15.4
- Programming Language version: 3.7.4
- CCXT version:  1.25.75   

```[python]
config = { 'apiKey' : KEY, 'secret': SECRET, 'enableRateLimit': True}
k = ccxt.kraken(config)
k.fetch_my_trades()
```

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    k.fetch_my_trades()
  File "/usr/local/lib/python3.7/site-packages/ccxt/kraken.py", line 993, in fetch_my_trades
    self.load_markets()
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 1286, in load_markets
    markets = self.fetch_markets(params)
  File "/usr/local/lib/python3.7/site-packages/ccxt/kraken.py", line 285, in fetch_markets
    limits = self.fetch_min_order_amounts()
  File "/usr/local/lib/python3.7/site-packages/ccxt/kraken.py", line 260, in fetch_min_order_amounts
    html = self.zendeskGet205893708WhatIsTheMinimumOrderSize()
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 446, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 469, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 465, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 575, in fetch
    self.handle_rest_errors(http_status_code, http_status_text, http_response, url, method)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 602, in handle_rest_errors
    raise error(' '.join([method, url, string_code, http_status_text, body]))
ccxt.base.errors.ExchangeNotAvailable: GET https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size- 403 Forbidden <!DOCTYPE html>
<html lang="en">
...
(omitted html code with captchas)
```

This happens with any `fetch` method. `fetch_deposits` `fetch_my_trades` etc.
I am using a fresh api key.

**Comment by kroitor** [comment]
This is a duplicate issue (use the search plz https://github.com/ccxt/ccxt/issues?q=kraken+is%3Aissue+is%3Aclosed+).

See the explanation and the workaround below:

- https://github.com/ccxt/ccxt/issues/6797
- https://github.com/ccxt/ccxt/issues/6795#issuecomment-613451098
- https://github.com/ccxt/ccxt/issues/6700
- https://github.com/ccxt/ccxt/issues/6701

Kraken's official answer: 

> we are aware of the recent issue that CCXT experienced when a security change to our support pages prevented the minimum order sizes from being retrieved via our support pages. Our REST API developers are in the process of adding the minimum order sizes to the REST API AssetPairs endpoint, which would make the minimum order sizes available more efficiently (and more reliably). We do not yet have an expected availability date for this update, but I will keep track of the progress, and let you know when more information is available.

In the meantime, you can workaround the issue, by setting `fetchMinOrderAmounts` option to `false`. 

```Python
exchange = ccxt.kraken({
    'enableRateLimit': True,
    'options': {  # ←--------------------- inside 'options' subkey
        'fetchMinOrderAmounts': False,  # ←---------- set to False 
    }
})
```

That way you will effectively lose the information about the minimal limits, but the other functionality will keep working.

Upgrading to the most recent version of CCXT also applies the above workaround automatically.

Let me know if that does not answer the question.

**Comment by ethanbrown3** [comment]
@kroitor Sorry about the duplicate. Thanks for the response!
