### ISSUE TITLE
OKEX API and manual trade minimum limits not matching

### ISSUE THREAD

**Issue by Eriz11** [ccxt/ccxt#6812]
- OS: (Ubuntu 18.04)
- Programming Language version: Python 3.7
- CCXT version: 1.25.65

Hi, 

I'm experiencing a hard time with tackling the limit amounts and cost for market orders in ```OKEX```.

Firstly, they have the neccesity of putting market buy orders in ```Quote``` currency (```createMarketBuyOrderRequiresPrice``` is ```True```). Once understood that, for example if I want to ```BUY MKT``` on ```LINK/BTC```, I need to specify the amount in ```Quote``` amount (i.e. understood as ```cost``` == ```BTC```).

NOTE: Previously to sending the order, I do so that I'm able to put the cost as a whole:
```
EXCHANGE.exchangeObject.options['createMarketBuyOrderRequiresPrice'] = False
```

On that sense, my example is to buy ```0.02 BTC```. However, when I try to do that via the API, my limitsChecker method firewalls me from doing it, due to the following limits in the exchange for that specific pair:

```
"LINK/BTC": {
            "amount": {
                "max": null,
                "min": 1.0
            },
            "cost": {
                "max": null,
                "min": 0.999997697417558
            }
        }
```

But here comes the catch; although the neccesity of buying a whole ```BTC``` as minimum (```0.999997697417558``` exactly) sounds really confusing because it as a big amount, when I go the manual trading webapp and I go the ```LINK/BTC``` pair, I can without problems submit a ```BUY MKT``` for ```0.02 BTC``` which gets filled inmediately.

So, maybe I'm misunderstanding something in terms of that the manual and API trading is different or this is something ```OKEX``` is doing wrong on their side or other comprehension confusion mixture.

**_My sense is that structuring limits of order amounts/costs is a really exhausting process. Hopefully I'm not the only one._**

¿Could somebody shed some light?

Thanks in advance,

**Comment by kroitor** [comment]
It looks like a wrong value in the cost limits to me, I will try to fix it and will get back to you asap.

**Comment by Eriz11** [comment]
Sure, thanks @kroitor!

**Comment by Eriz11** [comment]
Hey @kroitor, 

Just a quick update, I have just checked the new commit (version 1.26.49) and it seems correct (I saw that you changed the way it was entered in the dict). Many thanks again!

```
"LINK/BTC": {
            "amount": {
                "max": null,
                "min": 1.0
            },
            "cost": {
                "max": null,
                "min": 1e-06
            }
```

**Comment by kroitor** [comment]
@Eriz11 awesome! Thank you very much for your feedback! Let us know if anything.
