### ISSUE TITLE
Error Binance API: "Timestamp for this request is outside of the recvWindow"

### ISSUE THREAD

**Issue by lRninG9977** [ccxt/ccxt#6813]
I'm trying to perform a GET request to the Binance's API using Postman.
I read all the post about the time sync (I'm using Windows and I tried "net stop w32time, w32tm /unregister, w32tm /register, net start w32time, w32tm /resync"), I tried another Windows machine, and I tried to set every value of timestamp or recWindow but I still cannot perform this request.
Could you help me out? Thanks

GET request:
```
https://api.binance.com/api/v3/allOrders?timestamp=2326558065&signature=SECRETKEY&recvWindow=50000
```
And as a header X-MBX-APIKEY=APIKEY
But i get:

```
{
    "code": -1021,
    "msg": "Timestamp for this request is outside of the recvWindow."
}
```

**Comment by kroitor** [comment]
> ?timestamp=2326558065

↑ This does not look like a correct timestamp in milliseconds:

```
mbp:ccxt.pro igorkroitor$ node
Welcome to Node.js v12.2.0.
Type ".help" for more information.
> new Date (2326558065)
1970-01-27T22:15:58.065Z ←--------------------- WRONG
```

The current timestamp in milliseconds is 

```
> new Date ().getTime ()
1587048771817  ←------------------------- CORRECT
> new Date (1587048771817)
2020-04-16T14:52:51.817Z 
```

The timestamp must be a UNIX timestamp in milliseconds. You should put the "current timestamp" there, the moment you send the request. Let us know if that does not answer the question.

**Comment by lRninG9977** [comment]
Thank you so much. This work! Could I ask you just a last question?
What do you think about "python-binance" library? It's safe to use this and pass the secretKey to do the requests? Thank you so much!

**Comment by kroitor** [comment]
@lRninG9977 

> What do you think about "python-binance" library?

Tbh, I don't really think about it, since I am not responsible for developing or maintaining that software.

> It's safe to use this and pass the secretKey to do the requests?

In general, it is a well-known project, so it doesn't steal your credentials. It is open-source and you can review the source code to see what exactly it is doing with your keys. CCXT does the same, otherwise nobody would trust it and nobody would use it. I would recommend you to use CCXT, of course.

**Comment by lRninG9977** [comment]
Thank you very much for your answer. Ok I will check CCXT. Thank you again!

**Comment by kroitor** [comment]
@lRninG9977 you're welcome ) I'd highly recommend to start from here: 

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
