### ISSUE TITLE
Kraken: How to fetch current positions

### ISSUE THREAD

**Issue by Princeton007** [ccxt/ccxt#6815]
- Windows10
- Python 3.7.6
- CCXT version: 1.26.45

Hello, I'm stuck again, now with the integration of Kraken, I want to fetch the current positions. I tried hard but couldn't figure out how.
For example for Bitfinex I use the unified method
```
exchange.private_post_positions()
```

For Kraken I found:
```
'private': {
                    'post': [
                       ...
                        'Balance',
                        ...
                        'OpenOrders',
                        'OpenPositions',
                        ...
                    ],

```
But none of these work. For example: 
```
positions = exchange.private_post_open_positions()
```
throws me the error

```
positions = exchange.private_post_open_positions()
AttributeError: 'kraken' object has no attribute 'private_post_open_positions'
```
What am I doing wrong? Please help...

**Comment by kroitor** [comment]
Hi!

Change this:

```Python
positions = exchange.private_post_open_positions()
```

To this ↓

```Python
positions = exchange.private_post_openPositions()
# same as
# positions = exchange.privatePostOpenPositions()
```

> What am I doing wrong?

You are not doing this to see which methods are available – that is wrong )

```Python
import ccxt
print(dir(ccxt.kraken())  # as documented in the Manual, to see which methods are there
```

↑ If you do that, you will obtain the answer to your question rather quickly )

Let me know if that does not help.
