### ISSUE TITLE
Issue with getting history ohlcv from example

### ISSUE THREAD

**Issue by SpinningSlash** [ccxt/ccxt#6822]
- OS: Win10 64x
- Programming Language version: python 3.8.2
- CCXT version: 1.26.54

Hi. I'm stuck here almost for 2 days and couldn't find a solution. It is possible example is too outdated

My goal is to fetch data to csv. But when i try to just bluntly use an example to give it a test, it gets me wrong data.

you see, in the example  @kroitor wants to get ohlcv from _016-01-01T00:00:00Z_ with _limit = 100_ days
But instead data passed to csv  _from 2017-12-22T00:00:00.000Z to 2020-04-20T00:00:00.000Z_

I posted the last line. Whole code is available here:
ccxt/examples/py/binance-fetch-ohlcv-to-csv.py
```
scrape_candles_to_csv('binance.csv', 'binance', 3, 'NEBL/ETH', '1d', '2016-01-01T00:00:00Z', 100)
```

```
"C:\Program Files\Python38\python.exe" C:/Users/Leo/PycharmProjects/NewProject/get_currs_history_fuck.py
100 candles in total from 2020-01-12T00:00:00.000Z to 2020-04-20T00:00:00.000Z
200 candles in total from 2019-10-04T00:00:00.000Z to 2020-04-20T00:00:00.000Z
...
800 candles in total from 2018-02-11T00:00:00.000Z to 2020-04-20T00:00:00.000Z
900 candles in total from 2017-12-22T00:00:00.000Z to 2020-04-20T00:00:00.000Z
Saved 900 candles from 2017-12-22T00:00:00.000Z to 2020-04-20T00:00:00.000Z to binance.csv

Process finished with exit code 0
```

**Comment by kroitor** [comment]
@SpinningSlash Binance did not exist in 2016. The exchange was launched in July 2017. Therefore you can't get the history of candles from Binance from year 2016 – there was no history back then.
Let me know if that does not answer the question.

**Comment by SpinningSlash** [comment]
@kroitor  No, it does not

Here I'm trying to fetch XRP/USDT 1d 100 bars starting with 2019-01-01T00:00:00Z
I checked it on their website, Binance sure has this data 

```
scrape_candles_to_csv('binance.csv', 'binance', 3, 'XRP/USDT', '1d', '2019-01-01T00:00:00Z', 100)
```
and that is what i've got

```
"C:\Program Files\Python38\python.exe" C:/Users/Leo/PycharmProjects/NewProject/get_currs_history_fuck.py

Request: GET https://api.binance.com/api/v3/exchangeInfo {'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.binance.com/api/v3/exchangeInfo 200 {'Content-Type': 'application/json;charset=utf-8', 'Transfer-Encoding': 'chunked',
...
500 candles in total from 2018-12-09T00:00:00.000Z to 2020-04-21T00:00:00.000Z
Saved 500 candles from 2018-12-09T00:00:00.000Z to 2020-04-21T00:00:00.000Z to binance.csv
```
Yes, added verbose this time

**Comment by kroitor** [comment]
@SpinningSlash ok, in order to help we need:

- your code to reproduce it
- your version numbers (Python, CCXT, etc)
- your full verbose request/response as explained here: 

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by SpinningSlash** [comment]
Could you possibly check it?
I've found

_**earliest_timestamp = exchange.milliseconds()**_

as far as i can believe to debugging _**exchange.milliseconds()**_ returns us current datetime in ms, but the name of  _**earliest_timestamp**_  doesn't imply that

**Comment by SpinningSlash** [comment]
- OS: Win10 64x
- Programming Language version: python 3.8.2
- CCXT version: 1.26.54
full verbose doesn't feet here.  Gonna attach txt


[verbose.txt](https://github.com/ccxt/ccxt/files/4508857/verbose.txt)

**Comment by kroitor** [comment]
@SpinningSlash by default, that example will fetch OHLCV in batches by 100 candles (100 days) backwards in time, starting from today – into the past. That is why it returned slightly more candles, starting earlier than your since date. If you want the starting date to be exactly at your `since` value – just filter your candles accordingly.

Change line 47 here:

```Python
return all_ohlcv
```

↓

```Python
    return exchange.filter_by_since_limit(all_ohlcv, since, None, key=0)
```

In short, those examples are examples showing the concepts of how to use the CCXT code, but they're not supposed to be used as is for your production needs. In other words, you're expected to read the example and understand what it does to be able to change it and manage it how you want.

I've uploaded the edited example:

- https://github.com/ccxt/ccxt/blob/master/examples/py/binance-fetch-ohlcv-to-csv.py

**Comment by kroitor** [comment]
@SpinningSlash let me know if the above does not resolve the issue.
