### ISSUE TITLE
EXMO API updated to v1.1

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#6825]
https://exmo.com/en/news_view?id=3155
Some new and improved old endpoints.

I also noticed that it's needed to recreate API keys to use new version in other cases we catch an error:
`{"result":false,"error":"Error 40032: Access is denied for this API key"}`

**Comment by kroitor** [comment]
@ndubel their API docs list out all public URLs except candles as "POST" which is an error in the API docs:

- https://api.exmo.com/v1.1/trades?pair=BTC_USD
