### ISSUE TITLE
Enhance fetchOrder/cancelOrder handling

### ISSUE THREAD

**Issue by brandsimon** [ccxt/ccxt#6838]
Usually for fetchOrder/cancelOrder there is only the orderID needed, but sometimes there is also the symbol and/or the side needed to cancel/fetch the order.
It is easy to provide the symbol, since there is an extra parameter in the function call and the symbol is ignored if not needed.
The side parameter is more annoying, because passing `params={'side': 'sell'}` can break other exchanges, because they will include this and the exchange does not want this. so there is a check needed, which exchanges need the side and which dont.

An easy solution for this would be to have an api like this:
```
order = exchange.createOrder(...)
order = exchange.fetchOrder(order)
exchange.cancelOrder(order)
```

Create Order would always add properties needed for a fetch/cancel and the specific exchange methods could then pick the properties needed.
I know, that this would break every code out there and people using databases to safe orderIDs and use them later would need to change a lot of code.

So probably a solution like an additional function: `fetchOrderFromOrder / cancelOrderFromOrder`.
They would just call `fetchOrder/cancelOrder` with the needed parameters.
These could be implemented in the base classes and only overwritten in the specific exchange classes if needed.

Any ideas on that?

**Comment by kroitor** [comment]
I agree with almost everything, except the naming for base methods – i'd think on some better names, something like `fetchUnifiedOrder`, `cancelUnifiedOrder`, though, those aren't ideal either. However, the naming is not too important, so if you can submit those implementations – I'd edit upon merging where necessary. Thank you!

**Comment by kroitor** [comment]
We actually have slightly different approach implemented in some exchanges, like [`fetchOrderTrades` for Kraken](https://github.com/ccxt/ccxt/pull/6804#discussion_r408733299):

```JavaScript
const order = await fetchOrder (id);
// the entire unified order passed as params
const trades = await fetchOrderTrades (order['id'], since, limit, order);  
```

We could probably do the same for the other methods:

- `fetchOrder (order['id'], order['symbol'], order)` 
- `cancelOrder (order['id'], order['symbol'], order)`

I would stick to that, since it is closer to the existing unified API.

Let me know your thoughts on the above.

**Comment by brandsimon** [comment]
@kroitor 
Yes, I was also not comfortable with the naming.
In your second idea you forgot the params parameter.
To not change existing behavior, we would need
`fetchOrder (order['id'], order['symbol'], params, order)`
A problem I see with this approach is, that there is no slow progress possible, because all exchange implementations will need to be migrated and there will be a lot of duplicate code.
Every method needs to look for order['id'] and use it, if id is not provided and so on.

If we reached a final API, I will create a pull request.

**Comment by kroitor** [comment]
> In your second idea you forgot the params parameter.

Not really, the order is passed **as** `params`.

> A problem I see with this approach is, that there is no slow progress possible

Also not really – we only need to do this for the exchanges that require anything else but id and symbol. And, if you consider a standalone base method  – it won't work as a base method, since we will have to pass the side only for the exchanges that require it (also, in various cases the side field sent to the exchange API has to be named differently)  – so in that regard it's almost an identical amount of work (need to change just some of all exchanges).

Lmk if that makes sense or not.

**Comment by kroitor** [comment]
To clarify, the method implementations will have to be augmented with this kind of code (only for the exchanges that require more than just the id and the symbol):

```JavaScript
async cancelOrder (id, symbol, params = {}) {
    if ('info' in params ) {
        // a unified order is passed, take the side from it
    } else {
        // treat them as regular extension params
       request = this.extend (request, params);
   }
   ...
}

**Comment by brandsimon** [comment]
> we only need to do this for the exchanges that require anything else but id and symbol
If the order is passed as params, every exchange implemenation now needs to ignore params, if it is an order. I dont think, it is a clean approach to overload a parameter like this and will probably lead to unexpected behavior for some people using it.
If we use this way and migrate gradually, if I use now the new method, I get an error for every exchange, which does not support extending the request with all of the order properties.

My initial thought was, we add the unified method in the base classes:
```
async cancelUnifiedOrder (order, params) {
    await this.cancelOrder(order['id'], order['symbol'], params);
}
```
And then only overwrite this function in exchanges, which need it, e.g. bithumb:
```
async cancelUnifiedOrder (order, params) {
    await this.cancelOrder(order['id'], order['symbol'], this.extend ({'side': order['side'], params));
}
```
So this way, only exchanges which need it need to be adapted.
If we use such a approach with a gradually migration, I only get an error for exchanges, where the side is not added in an exchange specific method, so I would only get errors for exchanges which require the side parameter, so the behavior is basically the same.

**Comment by brandsimon** [comment]
@kroitor 
Great, I will create a pull request later today.
