### ISSUE TITLE
AuthenticationError: KC-API-KEY not exists

### ISSUE THREAD

**Issue by jaydevvaghela943** [ccxt/ccxt#6853]
Hello Sir,

I am new user to use CCXT on my project. I have a issue on some of functions like fetch my orders and Fills from Kucoin. When I these functions it throw error like "AuthenticationError: KC-API-KEY not exists".

My code is as below please provide solution....

`var kucoinData = new ccxt.kucoin({
	apiKey: 'mykey',
	secret: 'secret',
	password:'password'
});

var Data  = await kucoinData.fetchMyTrades();		
console.log(Data);` 

Please see above code and provide solution where I wrong in code....

Thanks & Regards,
Jay

**Comment by kroitor** [comment]
Hello!

> AuthenticationError: KC-API-KEY not exists

↑ That is the message you get from the KuCoin exchange directly. So, you want to check if your keys are correct. If you are 100% sure that the keys are correct – you may want to address this question to the KuCoin tech support.

The `apiKey` should be a string like '5e90...9925' (24 symbols without dashes).
The `secret` should be a string '5ce8a082-01ee-...-bc8d-ccb0dbfc0f85' (36 symbols with dashes).
The `password` is your API key password with KuCoin.

Let us know if that does not help.

**Comment by jaydevvaghela943** [comment]
Thanks for replay,

I have create new keypair on sandbox for test api. But I am facing same issue. Please provide script How I can fetch my fills list.

My code is as below.
var kucoinData = new ccxt.kucoin({
apiKey: 'mykey',
secret: 'secret',
password:'api_passphrase'
});

var Data = await kucoinData.fetchMyTrades();
console.log(Data);

I am getting same issue as old one....

Please help.....
![image](https://user-images.githubusercontent.com/43085597/80510701-b997f780-8998-11ea-8290-a8e41a27b469.png)

**Comment by kroitor** [comment]
@jaydevvaghela943 if you are using testnet keys – you should switch to the testnet as well.

```JavaScript
var kucoinData = new ccxt.kucoin({
    apiKey: 'mykey',
    secret: 'secret',
    password:'api_passphrase'
});
kucoinData.urls['api'] = kucoinData.urls['test']
var Data = await kucoinData.fetchMyTrades();
console.log(Data);
```

-----

P.S. For the future, please, use [github markdown](https://guides.github.com/features/mastering-markdown/) for readability when pasting code or text. Don't confuse triple backticks (&#096;&#096;&#096;) with a single backtick (&#096;). Wrap your code or text with triple backticks as shown below (this is also shown in any issue template upon opening it – you should really follow what's written in the template):

&#096;&#096;&#096;JavaScript
YOUR_CODE_HERE
&#096;&#096;&#096;

&#096;&#096;&#096;
YOUR OUTPUT HERE
&#096;&#096;&#096;

P.P.S. No need to duplicate the question in multiple issues – we always read everything, so your question will not be missed.

**Comment by jaydevvaghela943** [comment]
Hi Sir,
Thank you very much.... For quick reply.

I got your point.

Thanks & Regards,
Jay
