### ISSUE TITLE
bybit limit order with stop loss , how to do it

### ISSUE THREAD

**Issue by antebw** [ccxt/ccxt#6855]
how to create proper active limit order with stop loss, was ruining it like below but its throwing me error

order = exchange.create_order('BTC/USD', 'Limit', 'Buy', 2, price=7300, params={})

**Comment by kroitor** [comment]
Hello @antebw !

When using CCXT or CCXT Pro we recommend to strictly follow the Manual, in particular, these sections precisely: 

- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

This code should work:

```Python
symbol = 'BTC/USD'
type = 'limit'
side = 'buy'
amount = 2
price = 7300
params = {
    'stop_px': 123.45,  # your stop price here
    'base_price': 123.45,  # your base price here 
}
order = exchange.create_order(symbol, type, side, amount, price, params)
```

Let us know if the above does not help. If you get an error with the above, please, provide your verbose output and version numbers as explained here:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
exchange.load_markets ()
exchange.verbose = True  # enable verbose mode after loading the markets
# ...
order = exchange.create_order(symbol, type, side, amount, price, params)
```

It would be awesome if you report back whether this does resolve the issue for you or not.

**Comment by antebw** [comment]
Everything is working perfectly now, thank you for help!

**Comment by antebw** [comment]
ok , maybe am wrong but like this it creates a conditional order and if i lets say put limit price = 8000 and base_price=8000 and stopx = 7500  limit order is placed on 7500 area and can be triggered same thing also if for base price same price as for stop. Question is how to create active order with stop .

i can create it like this 
`order = await exchange.privatePostOrderCreate({"symbol": 'BTCUSD', "side": "Buy", "order_type": "Limit","price": price,"qty": 1, "time_in_force": "GoodTillCancel",'stop_loss': stop})`

and this is working for active order

**Comment by kroitor** [comment]
@antebw you might want to address your question to ByBit – they would help you with the exact parameters that would fit your requirements. 

Also, check ByBit API docs:

Inverse (BTC/USD):
- https://bybit-exchange.github.io/docs/inverse/#t-activeorders
- https://bybit-exchange.github.io/docs/inverse/#t-conditionalorders

Linear (BTC/USDT):
- https://bybit-exchange.github.io/docs/linear/#t-activeorders
- https://bybit-exchange.github.io/docs/linear/#t-conditionalorders

Unfortunately, we cannot consult on various aspects of trading with specific markets on particular exchanges. We can only help if you need assistance on the technical usage of CCXT. Technically – the ByBit integration in CCXT works. You can use it to send requests and receive responses from the exchange. 

Which params you need in your case to make this or that order – you decide. The ByBit API doc lists all supported params and their meaning. With CCXT you can send pretty much any of those params. 

So, I would highly recommend to check ByBit's resources first. You may find the answers to your questions there. And from there placing such an order in with CCXT using those params should be straightforward. Let us know if you get stuck.

**Comment by antebw** [comment]
yea i know am just saying that when i do it like this in code below limit order is placed on stop price. Sorry maybe i get it wrong but this was my point 

`symbol = 'BTC/USD'
type = 'limit'
side = 'buy'
amount = 2
price = 7500
params = {
    'stop_px': 7000,  # your stop price here
    'base_price': 7000,  # your base price here 
}
order = exchange.create_order(symbol, type, side, amount, price, params)`

**Comment by antebw** [comment]
Anyway Thank you for  help i appreciate it and all work you guys do here

**Comment by kroitor** [comment]
@antebw your question...

> Question is how to create active order with stop .

... may be answered in their API docs:

![Screen-Shot-2020-04-27-at-15 11 07](https://user-images.githubusercontent.com/1294454/80370889-a8b48c80-8899-11ea-9e1b-2f600f73a6dd.jpg)

**Comment by antebw** [comment]
Thank you mate one more time, will check everything about it. Sorry for trouble

**Comment by Princeton007** [comment]
Hello, 
I tried the example values from https://bybit-exchange.github.io/docs/linear/#t-conditionalorders 
I get the error 10004 | invalid sign

CCXT Version 1.33.39

```
exchange = getattr(ccxt, "bybit")({

    'apiKey': '***',
    'secret': '***',
    'timeout': 50000,
    'enableRateLimit': True,
    'verbose': True,
    'options': {'adjustForTimeDifference': True,
                'code': 'USDT',  # set default currency exchange-wide
                'fetchBalance': {'code': 'BTC'},  # set currency per method
                'marketType': 'linear'
                }})

exchange.set_sandbox_mode(True)

params = {
    'stop_px': 8150,
    'base_price': 8300
    }
order = exchange.create_order("BTC/USDT", "limit", "buy", "0.001", 8100)                 <- this places a limit order correctly
order = exchange.create_order("BTC/USDT", "limit", "buy", "0.001", 8100, params)   <- throws error below
```

Can you point me to the error, is it me using the wrong params? I can place simple limit orders 
 
This is the output: 
File "C:\Users\rolf\Anaconda3\envs\Pycharm-RTB\lib\site-packages\ccxt\bybit.py", line 2121, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: bybit {"ret_code":10004,"ret_msg":"error sign! origin_string[api_key=***\u0026base_price=8300.0\u0026close_on_trigger=false\u0026order_type=Limit\u0026qty=0.001\u0026recv_window=5000\u0026reduce_only=false\u0026side=Buy\u0026stop_px=8150.0\u0026symbol=BTCUSDT\u0026time_in_force=GoodTillCancel\u0026timestamp=1609366592966]","ext_code":"","ext_info":"","result":null,"time_now":"1609366593.157586"}

Response: POST https://api-testnet.bybit.com/private/linear/stop-order/create 200 {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '407', 'Expires': 'Wed, 30 Dec 2020 22:16:33 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Wed, 30 Dec 2020 22:16:33 GMT', 'Connection': 'keep-alive'} {"ret_code":10004,"ret_msg":"error sign! origin_string[api_key=***I\u0026base_price=8300.0\u0026close_on_trigger=false\u0026order_type=Limit\u0026qty=0.001\u0026recv_window=5000\u0026reduce_only=false\u0026side=Buy\u0026stop_px=8150.0\u0026symbol=BTCUSDT\u0026time_in_force=GoodTillCancel\u0026timestamp=1609366592966]","ext_code":"","ext_info":"","result":null,"time_now":"1609366593.157586"}

**Comment by Princeton007** [comment]
Similar issue when I try to get the open Orders CCXT returns only the linear limit orders, not the LinearConditional orders
In order to retrieve them I use the Bybit API this way. Not sure if this is the best way, at least it works. 
```
orders = (client.LinearOrder.LinearOrder_getOrders(symbol="BTCUSDT").result()[0])['result']['data']
orders = (client.LinearConditional.LinearConditional_getOrders(symbol="BTCUSDT").result()[0])['result']['data']
```
