### ISSUE TITLE
Feature request: Binance Hedge Mode

### ISSUE THREAD

**Issue by arenddeboer** [ccxt/ccxt#6859]
First of all, thanks for this awesome trading API!

I wonder if you would be open to add Binance Hedge Mode support.
This allows you to open a long and a short at the same time, giving you the option to hedge.
The createOrder needs to have a parameter for this option: `positionSide` which can be 'LONG' 'SHORT' and  'BOTH' for both sides (default).
https://binance-docs.github.io/apidocs/testnet/en/#new-order-trade

I tried this out by simply adding a 7th optional parameter to createOrder and this seems to work fine. Of course I understand this will require more work to officially implement.

My test implementation: [https://github.com/arenddeboer/ccxt/blob/d0184dcde3a3506ae49993d9038aa7f40fce3fe0/js/binance.js#L1136](https://github.com/arenddeboer/ccxt/blob/d0184dcde3a3506ae49993d9038aa7f40fce3fe0/js/binance.js#L1136)

Regards, Arend

**Comment by kroitor** [comment]
Hi Arend!

CCXT already does support that, without having to edit the code at all.
If you look into the Manual, here it shows you how to append or override any number of parameters to your request, including `positionSide`:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

So, in JS your call would look like:

```JavaScript
const ccxt = require ('ccxt');

(async () => {
    const exchange = new ccxt.binance({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET',
        'enableRateLimit': True,
    })

    symbol = 'BTC/USDT'
    type = 'limit'  // market, ...
    side = 'buy' // or sell
    amount = 123.45 // your amount here
    price = 543.21 // your price or undefined here

    // you can send any additional params like that
    params = {
        'positionSide': 'LONG', // or 'SHORT' or 'BOTH'
    }

    await exchange.createOrder (symbol, type, side, amount, price, params)
    
}) ()
```

↑ Let us know if that helps or not. Looking forward to hearing from you!

**Comment by arenddeboer** [comment]
Ahh, perfect. Thanks!

**Comment by Gennttii** [comment]
Does this work the same to close an order?

**Comment by kroitor** [comment]
@Gennttii can you clarify the question a bit? Have you tried some code?

**Comment by Gennttii** [comment]
I just started with hedge, have the same code to create order.
If I have two positions ( long and short ) with the same pair, and I do `sell`, which position is affected, the long or short one?

**Comment by kroitor** [comment]
@Gennttii I think it depends on your positionSide param. Let me know if you have issues with it (don't forget your code / verbose output).

**Comment by ProStrike-hub** [comment]
> Hi Arend!
> 
> CCXT already does support that, without having to edit the code at all. If you look into the Manual, here it shows you how to append or override any number of parameters to your request, including `positionSide`:
> 
> * https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
> 
> So, in JS your call would look like:
> 
> ```js
> const ccxt = require ('ccxt');
> 
> (async () => {
>     const exchange = new ccxt.binance({
>         'apiKey': 'YOUR_API_KEY',
>         'secret': 'YOUR_SECRET',
>         'enableRateLimit': true,
>         // 'verbose': true,  // for debugging
>     })
> 
>     symbol = 'BTC/USDT'
>     type = 'limit'  // market, ...
>     side = 'buy' // or sell
>     amount = 123.45 // your amount here
>     price = 543.21 // your price or undefined here
> 
>     // you can send any additional params like that
>     params = {
>         'positionSide': 'LONG', // or 'SHORT' or 'BOTH'
>     }
> 
>     const order = await exchange.createOrder (symbol, type, side, amount, price, params)
>     console.log (order)
>     
> }) ()
> ```
> 
> ↑ Let us know if that helps or not. Looking forward to hearing from you!

Hi @kroitor,

I'd like to implement 'hedge mode' in my existing CCXT bot. 
You state CCXT supports it but I couldn't find documentation on this feature and how to enable it in my code. 
Your code sample above sets a side, okay. But I do not see where it activates the 'hedge mode' in the settings?
