### ISSUE TITLE
How to get current positions on FTX 

### ISSUE THREAD

**Issue by Thjdid** [ccxt/ccxt#6860]
Hi, 
Despite searching in all the CCXT ftx documentation, I can not figure out how to fetch my open positions. Is there actually a way to do it ? 

ccxt ftx doc: https://github.com/ccxt/ccxt/blob/master/python/ccxt/ftx.py

**Comment by Thjdid** [comment]
Ok, it actually seems doable through the function privateGetAccount()!

**Comment by kroitor** [comment]
Hi!

Yep, you can call any endpoint this way. Feel free to reopen this or just ask further questions, if you have more, will be happy to help asap.

Duplicate:

- https://github.com/ccxt/ccxt/issues/6362#issuecomment-573367512

**Comment by sofomryu** [comment]
Hi! I am struggling to find a way to fetch an amount of a position of a specific coin.
As it is described in the similar issue, I could fetch current positions from the below _code.
`exchange.privateGetPositions()`
Then, I looked for a manual to find a way to fetch the amount of position of a specific coin, for example, 'XRP-PERP'
I tried,
`exchange.privateGetPositions('XRP-PERP')`
`exchange.privateGetPositions(future='XRP-PERP')`
`exchange.privateGetPositions()['XRP-PERP']`
`exchange.privateGetPositions(symbol='XRP-PERP')`

Sadly, none of them worked, how can I fetch the amount of the current position that I specifically want?

**Comment by kroitor** [comment]
@sofomryu hi! If your version of CCXT is up to date, you can just use `exchange.fetch_positions` like so:

```Python
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.ftx({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',    
})

markets = exchange.load_markets()
positions = exchange.fetch_positions()

symbol = 'XRP-PERP'
market = exchange.market(symbol)
indexed = exchange.index_by(positions, 'future')
position = exchange.safe_value(indexed, market['id'])

pprint(position)
```
