### ISSUE TITLE
binance use defaultLimitOrderType in create_limit_buy_order 

### ISSUE THREAD

**Issue by jaseisen105** [ccxt/ccxt#6861]
Binance has 2 limit order types: `limit`, `limit_maker`

When using `create_limit_buy_order` or `create_limit_sell_order` it seems to only use `limit` even if setting the `defaultLimitOrderType=limit_maker`

```
client = ccxt.binance({
  "options": {"defaultLimitOrderType": "limit_maker" }
}
client.create_limit_buy_order("BTC/USDT", 10, 1)
```

```
```

**Comment by kroitor** [comment]
Hi!

The `defaultLimitOrderType` option is deprecated, since Binance has added many more order types.

You can place a LIMIT_MAKER order like so:

```
client.create_order ('BTC/USDT', 'limit_maker', 'buy', 10, 1)
```

or

```
client.create_order ('BTC/USDT', 'LIMIT_MAKER', 'buy', 10, 1)
```

Let us know if that does not help. Feel free to reopen this issue or just ask further questions if any.
