### ISSUE TITLE
New Exchange: bitget.com

### ISSUE THREAD

**Issue by BitgetLimited** [ccxt/ccxt#6862]
Dear CCXT Team,

Bitget exchange supports spot and contract trading. 
We have a lot of users have strong demand to do API trading, so we hope to get kind support from CCXT and we are looking forward to join. 

Site:
https://www.bitget.com

Contract_api:
https://github.com/BitgetLimited/API_Docs_en/blob/master/README_contract_rest_api.md

Contract_websocket_api:
https://github.com/BitgetLimited/API_Docs_en/blob/master/README_contract_websocket_api.md

Thank you. 

Best regards,
Bitget team

**Comment by BitgetLimited** [comment]
Hi @kroitor ,

Please kindly assist to merge this integration for the Bitget exchange.
Since the exchange is working on providing algorithm trading for users, the integration is needed quite urgently, it'll be much appreciated if you can help look into this one.

Let me know if you have any issues!
Many thanks!

**Comment by binares** [comment]
@BitgetLimited I made some fixes to your latest PR so that it would transpile nicely (well a at least tested python fetchTickers and fetchOHLCV), if it helps. But the rest is up to you (as these are the only two methods I am personally interested in). https://github.com/binares/ccxt/tree/bitget

**Comment by BitgetLimited** [comment]
@binares  Thank you for your suggestion, I have completed the modification and submitted a new PR
