### ISSUE TITLE
How to identify/distinguish spot orders from futures orders?

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#6864]
How to identify are orders from a spot or a future market for the methods below?

fetchOrder (id[, symbol[, params]])
fetchOrders ([symbol[, since[, limit[, params]]]])
fetchOpenOrders ([symbol[, since, limit, params]]]])
fetchClosedOrders ([symbol[, since[, limit[, params]]]])
fetchMyTrades ([symbol[, since[, limit[, params]]]])

I would like to separate data from two markets

**Comment by kroitor** [comment]
> How to identify are orders from a spot or a future market for the methods below?

1. By symbol – _spot or future_ – is a property of a market, not a property of an order.
2. For some exchanges, like Binance Futures – by the order type that you request in the first place.

Let us know if that answers your question or not.

**Comment by YuriyTigiev** [comment]
I opened orders manually on both markets (binance). I fetching the orders data through API and I can't find a difference between spot and futures orders.

**Comment by kroitor** [comment]
If you use CCXT for fetching the orders, then you know by default which orders you are fetching – spot or futures. However, if you fetched the orders using the raw implicit endpoints, or using some other implementations of Binance API – then this is mostly up to you how to distinguish them. In general, they are not supposed to be distiguishable. Or, in other words, if you want them separately – don't mix them in the first place. If you can paste some code that we could run on our side without editing it too much (don't paste your keys of course) – we can try to help.

If you want to distinguish the orders returned from CCXT you can lookup in the `info` field of each order – and distinguish them by the presence of this or that subfield in the `info` of each order, how you like.

Compare the formats of (that's what you get in the `info` from CCXT if you use CCXT):

- https://binance-docs.github.io/apidocs/spot/en/#all-orders-user_data
- https://binance-docs.github.io/apidocs/futures/en/#all-orders-user_data

From there it is pretty obvious how orders can be distinguished if you mix them up.

**Comment by YuriyTigiev** [comment]
The code is simple. I'm using CCXT.

	async def Run(self):

		allBalances = await self.exchange.fetchBalance()
		NoneZeroBalancesTotal = dict( filter(lambda x:  x[0] not in ('info', 'free', 'total', 'used') and x[1]['total'] > 0 , allBalances.items()) )

		Orders = await self.exchange.fetchOrders('BNB/BTC')
		print(Orders)
		
		OpenOrders = await self.exchange.fetchOpenOrders('BNB/BTC')
		print(OpenOrders)

		ClosedOrders  = await self.exchange.fetchClosedOrders('BNB/BTC')
		print(ClosedOrders)

		myTrades = await self.exchange.fetchMyTrades('BNB/BTC')
		print(myTrades)

		await self.exchange.close()



Orders
![image](https://user-images.githubusercontent.com/22752322/80521863-c3235e80-899c-11ea-9af2-02cd64189903.png)

OpenOrders
![image](https://user-images.githubusercontent.com/22752322/80521993-eea64900-899c-11ea-8509-af5829a5d776.png)

ClosedOrders
![image](https://user-images.githubusercontent.com/22752322/80522282-5e1c3880-899d-11ea-8409-b3eddc4202fe.png)

myTrades
![image](https://user-images.githubusercontent.com/22752322/80522220-43e25a80-899d-11ea-8fc7-70419bde2979.png)

**Comment by kroitor** [comment]
@YuriyTigiev can you show your exchange instantiation code that you use for the futures orders? I mean a complete snippet, without the keys.

**Comment by YuriyTigiev** [comment]
I didn't use API for creating futures orders.  All last orders were created through Web Interface.   I would like to know the order type (spot or futures) because I will use this information in my business logic.

**Comment by kroitor** [comment]
@YuriyTigiev please, see this example snippet and let me know if you have further questions:

- https://github.com/ccxt/ccxt/blob/master/examples/py/async-binance-futures-vs-spot.py

```Python
# -*- coding: utf-8 -*-

import asyncio
import os
import sys
from pprint import pprint

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt.async_support as ccxt  # noqa: E402


async def load(exchange, symbol, type='spot'):
    exchange.options['defaultType'] = type
    await exchange.load_markets(True)
    try:
        return {
            'balance': await exchange.fetch_balance(),
            # you actually want pagination here
            # https://github.com/ccxt/ccxt/wiki/Manual#pagination
            # but this will do as an example, tweak it for your needs
            'orders': await exchange.fetch_orders(symbol),
            'open orders': await exchange.fetch_open_orders(symbol),
            'closed orders': await exchange.fetch_closed_orders(symbol),
            'my trades': await exchange.fetch_my_trades(symbol),
        }
    except Exception as e:
        print('\n\nError in load() with type =', type, '-', e)
        raise e


async def run():
    exchange = ccxt.binance({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET',
        'enableRateLimit': True
    })
    symbol = 'BTC/USDT'
    everything = {
        'spot': await load(exchange, symbol, 'spot'),
        'future': await load(exchange, symbol, 'future'),
    }
    await exchange.close()
    return everything


if __name__ == '__main__':
    pprint(asyncio.get_event_loop().run_until_complete(run()))
```

**Comment by YuriyTigiev** [comment]
Key parameter for me ->  exchange.options['defaultType'] = type

**Comment by robzer** [comment]
hello @kroitor , dream team,

fapiPrivateV2_get_positionrisk

is this not available in ccxt async?

```

async def swap_position(symbol):
    swap_position = await bfut.fapiPrivateV2_get_positionrisk({'symbol':symbol})
    swap_position = swap_position[0]['positionAmt']
    return swap_position
    await bfut.close()

# i get the below error

AttributeError("'binance' object has no attribute 'fapiPrivateV2_get_positionrisk'")

i instantiate per below

    bfut = ccxt.binance({
        'apiKey': 'xxxxx',
        'secret': 'xxxxx',
        'enableRateLimit': False,
        'options': {
            'defaultType': 'future',  
            },
        })

```

**Comment by kroitor** [comment]
@robzer please read this section of the Manual and make sure your version of CCXT is up to date: 

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

```Python
mbp:python igorkroitor$ python3
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt.async_support as ccxt
>>> print(ccxt.__version__)
1.39.48
>>> from pprint import pprint
>>> exchange = ccxt.binance()
>>> pprint(dir(exchange))
[
    ...

    'fapiPrivateV2GetPositionRisk',
    'fapiPrivateV2GetPositionrisk',

    ...

    'fapiPrivateV2_get_positionrisk',

    ...

    'fapiPrivate_get_positionrisk',

    ...
]
```

Let us know if that does not answer your question.

**Comment by robzer** [comment]
@kroitor many thanks for your reactivity im amazed by how quickly you always revert.
right -  I hadn't updraded ccxt in a while. Apologies.
