### ISSUE TITLE
[exmo] trade fee missing currency

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6867]
We can use 'commission_currency'...

```
{
            "id": "163922663",
            "fee": {"cost": 0.00018014},
            "cost": 0.00296498,
            "info": {"date": 1587031580, "pair": "BCH_BTC", "type": "buy", "price": "0.03291778", "amount": "0.00296498", "order_id": 6148412684, "quantity": "0.09007254", "trade_id": 163922663, "exec_type": "maker", "commission_amount": "0.00018014", "commission_percent": "0.2", "commission_currency": "BCH"},
            "side": "buy",
            "order": "6148412684",
            "price": 0.03291778,
            "amount": 0.09007254,
            "symbol": "BCH/BTC",
            "_source": "restapi",
            "datetime": "2020-04-16T10:06:20.000Z",
            "timestamp": 1587031580000,
            "takerOrMaker": "maker"
        }
```

**Comment by npomfret** [comment]
@kroitor regarding this fix.  It looks like the fee data goes missing after a while.  In my records I have the following examples:

```
{
  "date": 1586189100,
  "pair": "BCH_BTC",
  "type": "sell",
  "price": "0.03486422",
  "amount": "0.00285721",
  "order_id": 6011015596,
  "quantity": "0.08195276",
  "trade_id": 161687198,
  "exec_type": "",
  "commission_amount": "",
  "commission_percent": "",
  "commission_currency": ""
}
```

```
{
  "date": 1585864525,
  "pair": "XRP_BTC",
  "type": "buy",
  "price": "0.0000262",
  "amount": "0.0000262",
  "order_id": 5959682647,
  "quantity": "1",
  "trade_id": 160875165
}
```

Should we re-introduce the old logic of defaulting the fee if none is present?

**Comment by kroitor** [comment]
> Should we re-introduce the old logic of defaulting the fee if none is present?

Probably, but i would try to report it to EXMO first to see if they react and fix it on their side, because this behavior is not documented = bug. Have you tried reporting it to their tech support? If they don't react properly, we can fallback to the old logic conditionally (depending on the value of some exchange option, for example).

**Comment by kroitor** [comment]
@npomfret the datetime of that trades looks "fresh" to me, I thought it could be an old trade with unfilled data (before their API updates), however, since it's a new trade, those empty fields in the EXMO exchange response really look like a bug on the exchange side.

**Comment by npomfret** [comment]
I'll try and find an example in the future where I can show the exchange changing the data
