### ISSUE TITLE
[exmo] new pricing rule

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6868]
> Starting from May 13th 2020, the EXMO exchange will have a new pricing rule for orders placedfor some pairs with Bitcoin: BTC / USD, BTC / EUR, BTC / RUB, BTC / UAH, BTC / PLN, BTC / KZT, BTC / USDT. Traders can now use no more than 2 decimal places in the price.To test the update, we have already introduced a restriction on 2 pairs: BTC/GBP and BTC/TRY. The following update is essential for users who work with the exchange through the API. While placing an order with more than 2 characters, an error will be displayed:
>
> ```
> Error 50381: More than 2 decimal places are not permitted for pair BTC_USD
> ```

**Comment by kroitor** [comment]
It's been 2 weeks, and there are still no "twos" here: https://api.exmo.com/v1.1/pair_settings
In any case, it should self resolve as soon as they update their API. Closing this for now. Thx!
