### ISSUE TITLE
How to get Fills list from Kucoin

### ISSUE THREAD

**Issue by jaydevvaghela943** [ccxt/ccxt#6869]
Hello sir,
I am new in CCXT. I want to get fills data. I am using testnet api. I call function "fetchMyTrades" to get fills list but it always return blank data.

Here is my code....

var kucoinData = new ccxt.kucoin({
	apiKey: 'key',
	secret: 'secret',
	password:'password'
});

// set Test API URL
kucoinData.urls['api'] = kucoinData.urls['test'];
var markerData = await kucoinData.loadMarkets();
var kdata = await kucoinData.fetchMyTrades('KCS/BTC');
console.log(kdata);

Please help me.....

![image](https://user-images.githubusercontent.com/43085597/80630367-b886c900-8a71-11ea-80ad-8b2e2e0b0486.png)

**Comment by kroitor** [comment]
Hi!

> I am new in CCXT.

We recommend to start with reading the Manual from top to bottom. If you read it – you will find the troubleshooting section there. If you follow the steps from there – you will find that we need your verbose output as well.

- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/Manual#notes

Add the verbose switch after loading the markets:

```JavaScript
var kucoinData = new ccxt.kucoin({
    apiKey: 'key',
    secret: 'secret',
   password:'password'
});

// set Test API URL
kucoinData.urls['api'] = kucoinData.urls['test'];
var markerData = await kucoinData.loadMarkets();

kucoinData.verbose = true // ←---------- add this

var kdata = await kucoinData.fetchMyTrades('KCS/BTC');
console.log(kdata);
```

↑ Paste your output here (without the keys).

----------

Is this an image of your testnet trade or an image of your real exchange trade? ↓

![image](https://user-images.githubusercontent.com/43085597/80630367-b886c900-8a71-11ea-80ad-8b2e2e0b0486.png)

----------

### PLEASE READ THIS VERY CAREFULLY:

P.S. For the future, please, use [github markdown](https://guides.github.com/features/mastering-markdown/) for readability when pasting code or text. Don't confuse triple backticks (&#096;&#096;&#096;) with a single backtick (&#096;). Wrap your code or text with triple backticks as shown below (this is also shown in any issue template upon opening it – you should really follow what's written in the template):

&#096;&#096;&#096;JavaScript
YOUR_CODE_HERE
&#096;&#096;&#096;

&#096;&#096;&#096;
YOUR OUTPUT HERE
&#096;&#096;&#096;

**Comment by kroitor** [comment]
Closing this for now until we have a followup from you. Let us know if you're still having difficulties with it. Feel free to reopen it or just ask further questions if any.
