### ISSUE TITLE
Bug in bitfinex v1: field in the payload that matches the URL path at https://api.bitfinex.com/v1/history

### ISSUE THREAD

**Issue by Veniamin** [ccxt/ccxt#687]
In commit 
https://github.com/ccxt/ccxt/commit/25f41122bc197703dab3da70cbcfb196e90ef62f#diff-a3a69516c164ff60bece197030b75589
was changed (path == 'orders/hist')) to  (path.indexOf ('hist') >= 0)  but https://api.bitfinex.com/v1/history muches "hist" too. Now when I try to get balance history I get 'field in the payload that matches the URL path'.

**Comment by kroitor** [comment]
Thx for reporting this, will fix right away!

**Comment by kroitor** [comment]
Fixed in 1.10.230. Thx again!

**Comment by Veniamin** [comment]
No problem, thanks for fast fix!
