### ISSUE TITLE
binance createOrder returns Invalid orderType (-1116)

### ISSUE THREAD

**Issue by tradercgt** [ccxt/ccxt#6883]
The following code tries to create a market order at binance futures, but receives the `Invalid orderType` error. I tried to change some inputs, but couldn't make it run. How can I make it run successfully?

- OS: Ubuntu 18.04
- Programming Language version: JS, node v12.16.1
- CCXT version: 1.27.18

Code:

```
'use strict'

const ccxt = require('ccxt')

;(async () => {
  const exchangeId = 'binance'
  const exchange = new ccxt[exchangeId]({
    apiKey: 'AAA',
    secret: 'sss',
    verbose: false, // set to true to see more debugging output
    timeout: 60000,
    enableRateLimit: true,
    type: 'future'
  })

  const params = { type: 'future' }
  while (true) {
    try {
      await exchange.loadMarkets(true, params)
      break
    } catch (e) {
      if (e instanceof ccxt.RequestTimeout) { console.log(exchange.iso8601(Date.now()), e.constructor.name, e.message) }
    }
  }

  const symbol = 'BTC/USDT'
  const orderType = 'market'
  const side = 'buy'
  const amount = 0.001
  const price = 6666

  try {
    const response = await exchange.createOrder(symbol, orderType, side, amount, price, params)
    console.log(response)
    console.log('Finished.')
  } catch (e) {
    console.log(exchange.iso8601(Date.now()), e.constructor.name, e.message)
    console.log('Failed')
  }
})()
```
Output:

```
ExchangeError binance {"code":-1116,"msg":"Invalid orderType."}
Failed
```

**Comment by kroitor** [comment]
@tradercgt 

Your snippet has a few mistakes:

--------

```JavaScript
'use strict'

const ccxt = require('ccxt')

;(async () => {
  const exchangeId = 'binance'
  const exchange = new ccxt[exchangeId]({
    apiKey: 'AAA',
    secret: 'sss',
    verbose: false, // set to true to see more debugging output
    timeout: 60000,
    enableRateLimit: true,
    type: 'future', // ←--------------------- there should be no such thing here
  })

  const params = { type: 'future' } // ←--------- this should not be passed to createOrder below
  while (true) {
    try {
      await exchange.loadMarkets(true, params)
      break
    } catch (e) {
      if (e instanceof ccxt.RequestTimeout) { console.log(exchange.iso8601(Date.now()), e.constructor.name, e.message) }
    }
  }

  const symbol = 'BTC/USDT'
  const orderType = 'market'
  const side = 'buy'
  const amount = 0.001
  const price = 6666

  try {
    const response = await exchange.createOrder(symbol, orderType, side, amount, price, params)
    console.log(response)
    console.log('Finished.')
  } catch (e) {
    console.log(exchange.iso8601(Date.now()), e.constructor.name, e.message)
    console.log('Failed')
  }
})()
```

--------

Try this instead:

```JavaScript
'use strict'

const ccxt = require('ccxt')

;(async () => {
  const exchangeId = 'binance'
  const exchange = new ccxt[exchangeId]({
    apiKey: 'AAA',
    secret: 'sss',
    verbose: false, // set to true to see more debugging output
    timeout: 60000,
    enableRateLimit: true,
    options: { // ←----------------- inside exchange-specific 'options'
        defaultType: 'future', // ←---- a proper way to set defaultType
    }
  })

  while (true) {
    try {
      await exchange.loadMarkets(true)
      break
    } catch (e) {
      if (e instanceof ccxt.RequestTimeout) { console.log(exchange.iso8601(Date.now()), e.constructor.name, e.message) }
    }
  }

  const symbol = 'BTC/USDT'
  const orderType = 'market'
  const side = 'buy'
  const amount = 0.001
  const price = 6666

  try {
    const response = await exchange.createOrder(symbol, orderType, side, amount, price)
    console.log(response)
    console.log('Finished.')
  } catch (e) {
    console.log(exchange.iso8601(Date.now()), e.constructor.name, e.message)
    console.log('Failed')
  }
})()
```

↑ Let us know if the above helps or not.

**Comment by tradercgt** [comment]
@kroitor thank you for the corrections! The Invalid orderType was eliminated by your code.

Binance then returned the following error:

```
ExchangeError binance {"code":-1102,"msg":"A mandatory parameter was not sent, was empty/null, or malformed."}
```
I noticed that ccxt sends `quoteOrderQty` as part of the HTTP Form Data, but not the `quantity` which is mandatory according to the [binance API](https://binance-docs.github.io/apidocs/#account-trades-endpoints). Also I could not find `quoteOrderQty` the binance API docs.

I made this change to the code `const price = undefined` and I was able to send the market order successfully. Doesn't it make sense in the binance implementation of `createOrder` to set the price to undefined if it is a market order, or just to make sure that market order are processed no matter what price is given?

**Comment by kroitor** [comment]
> Doesn't it make sense in the binance implementation of createOrder to set the price to undefined if it is a market order, or just to make sure that market order are processed no matter what price is given?

In some cases the users want to send the amount in quote currency for market buys (this is about market buys only). In that case, if they supply the price – the total cost will be calculated as amount * price (to the required precision). The `quoteOrderQty` for spot orders is a side effect of this behavior (leading to a bug with futures that we will fix shortly).

The reason why this bug is there – because futures are not unified in CCXT yet (discussed here: https://github.com/ccxt/ccxt/issues/6697). It is a work in progress and we hope to unify it soon and fix these issues. Your feedback is really appreciated! Thank you!

**Comment by tradercgt** [comment]
Thank you for your detailed explanation!
