### ISSUE TITLE
New Exchange: ViteX (x.vite.net)

### ISSUE THREAD

**Issue by trampliu** [ccxt/ccxt#6884]
ViteX: a decentralized exchange built on the Vite public chain. The world's first DAG-based decentralized exchange.

ViteX link: https://x.vite.net/
ViteX API : https://vite.wiki/dex/api/dex-apis.html#overview
Vite introduction : https://vite.org/

**Comment by hrokling** [comment]
This is solved with Issue #7433 , which is currently a waiting Pull request.
