### ISSUE TITLE
CCXT Bybit timeframes(missing - 4h, invalid - 3h) don't correspond origin bybit api.

### ISSUE THREAD

**Issue by garry-1990** [ccxt/ccxt#6885]
**Actual result:** When I do request for download historical data with timeframe 4h error shown: 
      <<File "/home/ivan/.local/lib/python3.6/site-packages/ccxt/bybit.py", line 677, in fetch_ohlcv
           'interval': self.timeframes[timeframe],
      KeyError: '4h'>>

**Expected result:** When I do request for download historical data with timeframe 4h error must be missing and download successful.

**Comment by kroitor** [comment]
@garry-1990 thank you, we appreciate the feedback! Fixed in 1.27.21+
