### ISSUE TITLE
Binance endpoint not accepting timestamp

### ISSUE THREAD

**Issue by tongnk** [ccxt/ccxt#6889]
OS: MacOS Catalina 10.15.4
Programming Language: Javascript

I've implemented with binance already but I seem to be having an issue for this particular endpoint for the startTime param. If I comment it out then it works fine but once I reintroduce it then there are problems. I have the exact same implementation for fapiPublicGetFundingRate which seems to work perfectly.

```
let start = new Date('2018-11-01');

 const results = await binance.publicGetAggTrades({
            symbol,
            startTime: start.getTime(),
            limit: 1000
            // endTime: end.getTime()
        })

```

Error message
```
(node:70991) UnhandledPromiseRejectionWarning: ExchangeError: binance {"code":-1128,"msg":"Combination of optional parameters invalid."}
    at binance.throwExactlyMatchedException (/Users/nicholastong/Development/arbie-new/node_modules/ccxt/js/base/Exchange.js:531:19)
    at binance.handleErrors (/Users/nicholastong/Development/arbie-new/node_modules/ccxt/js/binance.js:1955:26)
    at /Users/nicholastong/Development/arbie-new/node_modules/ccxt/js/base/Exchange.js:627:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async timeout (/Users/nicholastong/Development/arbie-new/node_modules/ccxt/js/base/functions/time.js:178:24)
    at async binance.request (/Users/nicholastong/Development/arbie-new/node_modules/ccxt/js/binance.js:1966:26)
    at async getBinanceHistoricalTrades (/Users/nicholastong/Development/arbie-new/dataloggers/historical-data.js:74:25)
warning.js:32
(node:70991) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
warning.js:32
(node:70991) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kroitor** [comment]
> ```
> ExchangeError: binance {"code":-1128,"msg":"Combination of optional parameters invalid."}
> ```

Since you're using the implicit API instead of the unified API, you're operating with the exchange directly and this error is coming from the exchange API itself. It says that you're sending a combination of arguments to the aggTrades endpoint that Binance does not like.

https://binance-docs.github.io/apidocs/spot/en/#compressed-aggregate-trades-list

![Screen-Shot-2020-05-05-at-04 41 19](https://user-images.githubusercontent.com/1294454/81028645-0133ed00-8e8b-11ea-8ee5-92cf102430c4.jpg)


Make sure that your implicit request satisfies their criteria ↑
Let me know if that does not help, or does not answer your question. Feel free to reopen it or just ask further questions if any.

**Comment by kroitor** [comment]
@tongnk you can see what is being sent to the exchange, if you enable verbose mode like so:

```JavaScript
let start = new Date('2018-11-01');

binance.verbose = true // ←------------- add this to see the debug verbose output

const results = await binance.publicGetAggTrades({
    symbol,
    startTime: start.getTime(),
    limit: 1000
    // endTime: end.getTime()
)
```

**Comment by tongnk** [comment]
Great thanks
