### ISSUE TITLE
Can a separate credential verification method be added in the future?

### ISSUE THREAD

**Issue by PrefixEt** [ccxt/ccxt#6894]
Hello CCXT team. 
Now I validate credentials using a private exchange method, example get_balance().
I think you need to add a new universal method that will verify credentials for all exchanges.
Now I have to handle so many exceptions. For example, coinbasepro behaves too unpredictably.
Please add this feature to the new version.

**Comment by kroitor** [comment]
Hello @PrefixEt !

> I think you need to add a new universal method that will verify credentials for all exchanges.

It is already there, use `exchange.checkRequiredCredentials()` or `exchange.check_required_credentials()`:

- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L331
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L1174
- https://github.com/ccxt/ccxt/blob/master/php/base/Exchange.php#L747

Let us know if that does not answer the question.

**Comment by kroitor** [comment]
P.S. you can also see which credentials are required, if you look into `exchange.requiredCredentials`.

**Comment by heckad** [comment]
Please, improve doc.

**Comment by heckad** [comment]
`check_required_credentials` miss in https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/base/exchange.py

**Comment by kroitor** [comment]
@heckad 

> `check_required_credentials` miss in https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/base/exchange.py

`ccxt/async_support/base/exchange.py` is inherited from `ccxt/base/exchange.py`, no need to duplicate it there.

**Comment by heckad** [comment]
```
from ccxt.async_support.coinbasepro import coinbasepro

exchange = coinbasepro({
    "apiKey": "1",
    "password": "2",
    "secret": "3"
})

exchange.set_sandbox_mode(True)

exchange.check_required_credentials()
```
It doesn't validate credentials. It validates only exist of keys, not values.

**Comment by kroitor** [comment]
@heckad that kind of validation is not unified yet, your contributions are welcome:

- https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

We could start adding some overrides for specific exchanges to also check for the lengths and formats. However, this is a work in progress.

In the meantime, we have added the docs for `checkRequiredCredentials` and `requiredCredentials` to the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#credential-validation
