### ISSUE TITLE
Poloniex create_order (ccxtpro) problem

### ISSUE THREAD

**Issue by Hororohoruru** [ccxt/ccxt#6895]
- OS: Ubuntu 18
- Programming Language version: Python 3.7.6
- CCXT version: 0.1.61 (ccxtpro)

While testing a simple script to automatically place orders in poloniex, I found a problem with the create_order function in ccxtpro. Apparently it returns a coroutine in my code.

```
buy_amount = 1  # Some amount
price = 9000 # Some price


def place_order():
    buy_order = poloniex.create_order(symbol='BTC/USDT'l, type='limit', side='buy',
                                      amount=buy_amount, price=price)

    order_complete = False
    print(f"Order ID is: {buy_order['id']}")

    while True:
        buy_status = poloniex.fetch_order_status(id=buy_order['id'])
        if buy_status == 'closed':
            order_complete = True
        if order_complete:
            print("Order completed!")
            break
        else:
            time.sleep(5)
```

And I get the following error:

```   
    329
    330         order_complete = False
--> 331         print(f"Buy order ID is: {buy_order['id']}")
    333        
    334         while True:

TypeError: 'coroutine' object is not subscriptable
```

I am using the base ccxt function, and this code works fine using regular ccxt, since the function returns a dictionary with the order info, what happens here?

**Comment by kroitor** [comment]
> I am using the base ccxt function, and this code works fine using regular ccxt, since the function returns a dictionary with the order info, what happens here?

CCXT Pro is meant to be used in async environments only. Just like the [async version of CCXT](https://github.com/ccxt/ccxt/wiki/Manual#synchronous-vs-asynchronous-calls).

So, CCXT Pro = async only.
CCXT = sync and async.

In general, it is not recommended to mix sync networking with async networking (attempting to do so leads to other unexpected results later down the road). Though, if you really want to force sync calls and use them in an async environment – you can import ccxt alongside ccxtpro and instantiate another exchange instance from sync CCXT for sync RESTful operations like createOrder.

Let us know if that does not answer the question.

**Comment by Hororohoruru** [comment]
Sounds good.

In my case, the place_order function is called by an async function watching for tickers inside an event loop. So, following your suggestion, all I have to do is to make place_order async and then await create_order?

The problem is that, if I do that, the event loop will continue before the order is checked closed, and that could create problems in the flow, so I should probably call it from the REST API

**Comment by kroitor** [comment]
> So, following your suggestion, all I have to do is to make place_order async and then await create_order?

Yes, exactly.

> the event loop will continue before the order is checked closed, and that could create problems in the flow, so I should probably call it from the REST API

If you `await exchange.create_order()` – that specific "branch of execution" will hold till the response from `create_order` is received. However if you're running other concurrent async calls in other contexts at the same time in parallel – those will keep working separately.

**Comment by Hororohoruru** [comment]
Ok, thank you for your explanation!

I think I will just pass a flag to the object managing everything so no duplicate orders get placed by other routines.
