### ISSUE TITLE
Kraken Price Error, Captcha request on order size check

### ISSUE THREAD

**Issue by JTraversa** [ccxt/ccxt#6898]
Looks like kraken is having issues? When sending price requests you are met by a captcha request: 

HTTP Error: requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-
 
CCXT Error: ccxt.base.errors.ExchangeNotAvailable: GET https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size- 403 Forbidden

Text body in the response includes : 
"Complete the security check to access this page"

"Completing a CAPTCHA proves you are a human and gives you temporary access to this page."

"Make sure your home and work devices are regularly scanned for malware to reduce the need to complete the CAPTCHA."

So looks like there might have been backend changes to kraken?

**Comment by kroitor** [comment]
@JTraversa i hope that you have found the duplicates and the solution, let us know if not. Updating to the most recent version also fixes this.

**Comment by JTraversa** [comment]
Yup no problem! My issue was a depreciated pip version that was preventing CCXT from updating properly.
