### ISSUE TITLE
ccxt pro - huobi futures/swaps

### ISSUE THREAD

**Issue by codemonkeyno1** [ccxt/ccxt#6901]
What are the parameters to use for listening to huobi futures/swaps feeds?  I know in binance, there is an options: 'options':{'defaultType':'future'} 

Is something similar necessary for huobi swaps/futures?

Thank you

**Comment by kroitor** [comment]
Hi! Unfortunately, Huobi DM (for derivatives) is an API that is completely different from the Huobi spot (huobipro), and they have different base urls, so it's basically an entirely new exchange, which is the same story as Kraken futures – both are in the works now, and we are going to add them soon, as outlined in the roadmap for Q2 here: 

- https://github.com/ccxt/ccxt/issues/6697

Related to Huobi DM:

- https://github.com/ccxt/ccxt/issues/5923
- https://github.com/ccxt/ccxt/issues/5646

Let us know if the above does not answer the question.
