### ISSUE TITLE
{ ExchangeError: binanceus {"code":-1102,"msg":"Mandatory parameter 'quantity' was not sent, was empty/null, or malformed."}

### ISSUE THREAD

**Issue by crossx4real** [ccxt/ccxt#6903]
- OS: Windows 10
- Programming Language version: Node Js
- CCXT version: 6.14.4

Hello Igor,

i am trying to edit an order initially placed as limit order to change it from limit to market order. I am receiving the error below:
{ ExchangeError: binanceus {"code":-1102,"msg":"Mandatory parameter 'quantity' was not sent, was empty/null, or malformed."}

here's my code snippet below:

try { myOrder = await exchange.editOrder(orderId, tradingPair, type, side, amount, price, {}); }
	catch(err) {...}

Thanks in advance.

**Comment by kroitor** [comment]
Hi!

Try removing the price from there, as follows:

```JavaScript
// if it doesn't work uncomment the next line and paste your verbose request+response
// exchange.verbose = true 
try { myOrder = await exchange.editOrder(orderId, tradingPair, type, side, amount); }
catch(err) {...}
```

**Comment by crossx4real** [comment]
ok thank will do that. I hope you are enjoying the big swings on BTC this bull season.

**Comment by crossx4real** [comment]
worked like a charm. sent you 100 BAT. just say.... you got 90 days to claim it i think.
