### ISSUE TITLE
Bigone Market Order

### ISSUE THREAD

**Issue by fabiel-leon** [ccxt/ccxt#6907]
Market orders are posible on bigone api v3 see type attribute on table
https://open.big.one/docs/spot_orders.html#create-order

Name | Type | Require | Description | Example
-- | -- | -- | -- | --
asset_pair_name | string | true | asset pair name | BTC-USDT
side | string | true | order side, one of "ASK"/"BID" |  
price | string | true | order price |  
amount | string | true | must larger than 0 |  
type | string | true | order type, one of LIMIT/MARKET/STOP_LIMIT/STOP_MARKET |  
stop_price | string | false | must larger than 0, only for stop order. in BID side, price cannot be higher than 110% of the stop_price; in ASK side, price cannot be lower than 90% of the stop_price |  
operator | string | false | operator, one of GTE/LTE, only for stop order, gte – greater than and equal (>=), lte – less than and equal (<=) |  
immediate_or_cancel | bool | false | only use in limit type

**Comment by ndubel** [comment]
After this update I get an error: `BadRequest bigone {"code":10007,"message":"Price's scale must greater than AssetPair's quote scale"}`

**Comment by kroitor** [comment]
@ndubel can you paste the code to reproduce it?

**Comment by ndubel** [comment]
sorry for late reply, it's all ok now after your fix
