### ISSUE TITLE
[bitfinex] unmapped order status

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6915]
`"status":"INSUFFICIENT BALANCE (U1)"`

`{"info":[44922553069,null,1589070215681,"tBABUSD",1589070216000,1589070216000,0.14486264,0.14486264,"EXCHANGE LIMIT",null,null,null,"0","INSUFFICIENT BALANCE (U1)",null,null,229.7,0,0,0,null,null,null,0,0,null,null,null,"API>BFX",null,null,null],"id":"44922553069","clientOrderId":"1589070215681","timestamp":1589070216000,"datetime":"2020-05-10T00:23:36.000Z","symbol":"BCH/USD","type":"limit","side":"buy","price":229.7,"amount":0.14486264,"cost":0,"average":0,"filled":0,"remaining":0.14486264,"status":"INSUFFICIENT BALANCE (U1)"}`

**Comment by kroitor** [comment]
@npomfret is that a response to createOrder or does it come from another method? (Just to make sure if it's a historical order, of a new one).

**Comment by npomfret** [comment]
https://gist.github.com/npomfret/b1e835364aa8b6a079e12375f29cadaa

No order history query

**Comment by npomfret** [comment]
Guess it should be mapped to 'canceled'?
