### ISSUE TITLE
Docs: Fee field in the currency structure

### ISSUE THREAD

**Issue by hroff-1902** [ccxt/ccxt#6917]
Please add some (short) explanation for the `fee` field in the currency structure: https://github.com/ccxt/ccxt/wiki/Manual#currency-structure

How shall we treat it? It's completely missing in the meantime in the manual.

**Comment by kroitor** [comment]
@hroff-1902 thx for the feedback! I've added it to the Manual. It is a fixed flat withdrawal fee amount in the same currency. However, we think it is a bit too generic, so, we are going to enhance the fee info (and the currency structure itself) in the coming future. It will have to account for specifics like percentage fees, variable fees depending on the underlying subnets for currencies like USDT (omni vs erc20), wire transfers and much more. In other words, it is a work in progress, as always, just like the rest of the lib.

**Comment by hroff-1902** [comment]
Thanks for brilliant quick response, 👍 

I have not thought (have not looked at the code, though) that this is the withdrawal fee, it's not clear from the name of this field...

Maybe this field should be renamed to `withdrawal_fee` to have it cleaner for perception (and another one, `deposit_fee`, be added in this case to the currency structure in the future, as some exchanges can also apply (and report via API) deposit fees)...

**Comment by kroitor** [comment]
Yep, we will add some new fields into the `currency` structure to avoid breaking the older code and will migrate to a better definition of funding fees + will add some more info also related to how the fees can be applied. Thx again!
