### ISSUE TITLE
Token blockchain information 

### ISSUE THREAD

**Issue by arielorvits** [ccxt/ccxt#6918]
Hi, 

is there any way to find by CCXT the blockchain(s) supported in exchange for specific token (for example ERC20/ binance chain / Klaytn mainnet etc. ?
I guess it's not something that every exchange reveals in their API, but maybe some are

thanks!

**Comment by kroitor** [comment]
Hi!

At this time that specific aspect is not unified, so if the exchange provides it – you can access it with CCXT in an exchange-specific way, one of the following usually works:

```JavaScript
if (exchange.has['fetchCurrencies']) {
    await exchange.loadMarkets()
    const currency = exchange.currency ('USDT')
    // check `info` field in the currency as shown in the Manual: 
    // https://github.com/ccxt/ccxt/wiki/Manual#currency-structure
    console.log(currency['info'])
}
```

```JavaScript
const balance = await exchange.fetchBalance()
// check `info` field inside the balance response as shown in the Manual:
// https://github.com/ccxt/ccxt/wiki/Manual#balance-structure
console.log(balance['info']) 
```

```JavaScript
if (exchange.has['fetchDepositAddress']) {
    const address = await exchange.fetchDepositAddress ('USDT')
    // check `info` field inside the address response as shown in the Manual:
    // https://github.com/ccxt/ccxt/wiki/Manual#address-structure
    console.log (address['info'])
}
```

Sometimes you can also get that information from a standalone endpoint via CCXT's [implicit API methods](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods).

We are working on unifying that aspect and we hope to get that covered asap.

Let me know if the above does not answer the question. Feel free to reopen it or just ask further questions, if any.
