### ISSUE TITLE
how to set leverage on bybit?

### ISSUE THREAD

**Issue by adajung** [ccxt/ccxt#6919]
- OS: win10
- Programming Language version: python 3.7
- CCXT version: 1.27.46

Hi,
im just trying to use another exchange from bitmex to bybit. the code below works on bitmex but not on bybit. when i run this code, i get an error which is

AttributeError 'bybit' object has no attribute 'privatePostPositionLeverage'

so how can i change leverage level on bybit? please help me :<
----------------------------------------------------------------------------------------------

import os
import sys
import ccxt

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
            sys.path.append(root + '/python')

bybit = ccxt.bybit({
    'apiKey': '',
    'secret': '',
    'enableRateLimit': True})

leverage = 3
bybit.privatePostPositionLeverage({"symbol": "BTCUSD", "leverage": leverage})

-----------------------------------------------------------------------------------------------

**Comment by kroitor** [comment]
Hi!

> when i run this code, i get an error which is
> AttributeError 'bybit' object has no attribute 'privatePostPositionLeverage'

That is because you're using an [implicit API method]() – all implicit methods are exchange-specific.

We are working on the unification of positional trading, in the meantime you can do that with CCXT in exchange-specific way.

More about the unification of margin/positional/leveraged trading here: https://github.com/ccxt/ccxt/issues/6697

The difference between the unified API and the implicit methods is explained here: https://github.com/ccxt/ccxt/wiki/Manual#api-methods--endpoints

For ByBit the leverage is set with a method that has a different name:

```Python
import ccxt

exchange = ccxt.bybit({
    'apiKey': '',
    'secret': '',
    'enableRateLimit': True
})

exchange.load_markets()
market = exchange.market('BTC/USD')
response = bybit.user_post_leverage_save({
    "symbol": market['id'],  # https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
    "leverage": 3
})
print(response)
```

You can see all available methods for each exchange like so:

```Python
import ccxt
from pprint import pprint
pprint(dir(ccxt.bybit()))
```

Let us know if the above does not answer your question.

**Comment by adajung** [comment]
it works !! thx so much :))

**Comment by kroitor** [comment]
@adajung great, thx for reporting back! I highly recommend you to read the docs linked above and the CCXT Manual. It will save you a ton of time, really.

**Comment by adajung** [comment]
Thats true. I read all the links. It helps me alot. That dir() function is awesome. Im just trying every endpoints in dir(ccxt.bybit()) and guessing why some codes work and some doesn't. Now im trying to get bids and asks and it doesn't work. Maybe somedays later i will ask you about it unless i found the reason. Thx rly for this amazing libarary :))

**Comment by gghhuser** [comment]
OS: macOS 10.15.3
Programming Language version: python 3.7.6
CCXT version: 1.29.61

Hi, I would like to add on to this question regarding USDT Perpetual trading.
I get the below error when trying to set leverage.

> ccxt.base.errors.ExchangeNotAvailable: GET https://api-testnet.bybit.com/private/linear/position/set-leverage?api_key=####&buy_leverage=1&recv_window=5000&sell_leverage=1&symbol=BTCUSDT&timestamp=1592107678013&sign=88793eb06d5791b7dd5bd6b86996309e923c3230bcbed78831643811447253e8 404 Not Found 404 page not found

This is my code:

```
import ccxt

def bybit():
   bybit = ccxt.bybit({
       'apiKey': '####',
       'secret': '####',
       'enableRateLimit': True
        })
   bybit.urls['api'] = bybit.urls['test']

   return bybit

bybit().privateLinear_get_position_set_leverage({
    "symbol": "BTCUSDT",
    "buy_leverage": "1",
    "sell_leverage": "1"
})
```

Running just
`bybit().privateLinear_get_position_set_leverage()`
returns this error.
> ccxt.base.errors.ExchangeNotAvailable: GET https://api-testnet.bybit.com/private/linear/position/set-leverage?api_key=####&recv_window=5000&timestamp=1592108247454&sign=f7825987a9fcde0d2b0ea07e4b0c68a5f61e6fdd248763826b90cceede7f6e0a 404 Not Found 404 page not found

This is the documentation page for setting leverage.
https://bybit-exchange.github.io/docs/linear/#t-setleverage

Sorry if I am doing anything wrong.
Thanks for any help.

**Comment by kroitor** [comment]
@gghhuser that was a bug caused by the API doc inconsistencies. We have uploaded the necessary fixes.

1. Update your version to 1.29.98

2. Change `get` → `post` in your code:

```Python
import ccxt

def bybit():
   bybit = ccxt.bybit({
       'apiKey': '####',
       'secret': '####',
       'enableRateLimit': True
        })
   bybit.urls['api'] = bybit.urls['test']

   return bybit

bybit().privateLinear_post_position_set_leverage({
    "symbol": "BTCUSDT",
    "buy_leverage": "1",
    "sell_leverage": "1"
})
```

3. Let us know if you have further difficulties with it.

Thx!

**Comment by gghhuser** [comment]
Works great, thanks!

**Comment by Kamkuczpol** [comment]
Hello.

Are there methods above still working?

I got this error:
`AttributeError: 'bybit' object has no attribute 'privateLinear_get_position_set_leverage'
`

**Comment by carlosmiei** [comment]
Hello @Kamkuczpol, you should now use the unified method `set_leverage`, bybit has been completely updated since then.

Example: 
```Python 
exchange = ccxt.bybit({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET_KEY',
}
symbol = "BTC/USDT:USDT"
leverage = 5
await exchange.set_leverage(5, symbol)
```

**Comment by Astraioss** [comment]
> Hello @Kamkuczpol, you should now use the unified method `set_leverage`, bybit has been completely updated since then.
> 
> Example:
> 
> ```python
> exchange = ccxt.bybit({
>     'apiKey': 'YOUR_API_KEY',
>     'secret': 'YOUR_SECRET_KEY',
> }
> symbol = "BTC/USDT:USDT"
> leverage = 5
> await exchange.set_leverage(5, symbol)
> ```

this method doesn't seem to be working? I am trying to set leverage for my conditional order but it keeps placing the order at 1x lev. Any idea?

**Comment by Jan-Fryblik** [comment]
> > Hello @Kamkuczpol, you should now use the unified method `set_leverage`, bybit has been completely updated since then.
> > Example:
> > ```python
> > exchange = ccxt.bybit({
> >     'apiKey': 'YOUR_API_KEY',
> >     'secret': 'YOUR_SECRET_KEY',
> > }
> > symbol = "BTC/USDT:USDT"
> > leverage = 5
> > await exchange.set_leverage(5, symbol)
> > ```
> 
> Can't seem to get this method to work, I am trying to set leverage for my conditional order but it keeps placing the order at 1x lev. Any idea? (BadRequest: bybit {"ret_code":34036,"ret_msg":"leverage not modified")

Error 34036 means, that leverage is already set at this value. So basically, it isn't error.

**Comment by Astraioss** [comment]
> > > Hello @Kamkuczpol, you should now use the unified method `set_leverage`, bybit has been completely updated since then.
> > > Example:
> > > ```python
> > > exchange = ccxt.bybit({
> > >     'apiKey': 'YOUR_API_KEY',
> > >     'secret': 'YOUR_SECRET_KEY',
> > > }
> > > symbol = "BTC/USDT:USDT"
> > > leverage = 5
> > > await exchange.set_leverage(5, symbol)
> > > ```
> > 
> > Can't seem to get this method to work, I am trying to set leverage for my conditional order but it keeps placing the order at 1x lev. Any idea? (BadRequest: bybit {"ret_code":34036,"ret_msg":"leverage not modified")
> 
> Error 34036 means, that leverage is already set at this value. So basically, it isn't error.

Oh okay fair enough, it didn't seem to be changing the amount traded

**Comment by carlosmiei** [comment]
Hello @verystrongjoe, what's your ccxt version and which code are you running exactly?

**Comment by kdmmanapul** [comment]
yeah same problem, is there a way to fetch the leverage already set? so that we can add a condition in our script that if leverage is the same, don't run set_leverage?

**Comment by daoleen** [comment]
I'm also looking for a endpoint to get leverage info for the symbol for Bybit.
Without checking the leverage I'm getting an error each time when opening a new order and ignoring that error.
Seems there is not such method even in official bybit api docs.

**Comment by Giits254** [comment]
import ccxt
from ccxt.base.errors import BadRequest  
from config import bybit_secret, bybit_key

exchange = ccxt.bybit({
    'enableRateLimit': True,
    'apiKey': bybit_key,  
    'secret': bybit_secret,  
    'options': {
        'defaultType': 'swap',
    },
})

exchange.set_sandbox_mode(True)
params = {'takeProfit': 68000, 'stopLoss': 64000}
symbol = "BTCUSDT"

try:
    exchange.set_leverage(20, symbol)
except BadRequest as e:
    if "Set leverage not modified" in str(e):
        print("Leverage is already set to 20.")
    else:
        raise e

order = exchange.create_order(
    symbol=symbol,
    side="buy",
    type="market",
    amount=0.005,
    params=params,
)

this will work without an error

**Comment by seeyoul8r** [comment]
If I got it right, you are only possible to set leverage for each symbol? Is there posibility to set commom leverage for all future orders?
