### ISSUE TITLE
Bitfinex order price gets rounded

### ISSUE THREAD

**Issue by robkaandorp** [ccxt/ccxt#692]
When I create a sell order on Bitfinex for XRP with a price of 0.00002566, the price appears on the exchange as 0.00003000.

I noticed that the precision for `price` is 5 on bitfinex (`this.markets['XRP/BTC'].precision.price`). I think that ccxt gets the precision wrong, because 0.00002566 with a precision 5 is actually 0.000025660 and not 0.00003.

**Comment by kroitor** [comment]
> because 0.00002566 with a precision 5 is actually 0.000025660 and not 0.00003

Sorry? Precision 5 means 5 decimal digits *"after the dot"*. So, 0.000025660 boils down to:
- 0.00003 ← 5 digits (correct)
- 0.000025660 ← 9 digits (?) Biftinex will not like it. (wrong)

Does this make sense?

**Comment by robkaandorp** [comment]
Sorry, got price and amount a bit mixed up. Fixed the text of the issue.

Are you saying that I should not be able to put in a sell price on Bitfinex that is an actual price in the orderbook? Because that would be rather weird.

Have a look at [.toPrecision(p)](https://www.w3schools.com/jsref/jsref_toprecision.asp), maybe that will make it clear.

**Comment by kroitor** [comment]
https://bitfinex.readme.io/v1/docs/readme#section-price-precision

**Comment by kroitor** [comment]
The same is true for v2 as well:

<img width="1081" alt="screen shot 2017-11-27 at 18 34 26" src="https://user-images.githubusercontent.com/1294454/33274635-a5f05bbe-d3a1-11e7-8235-7dc59e7f8cb5.png">

**Comment by kroitor** [comment]
Does the above answer your question?

**Comment by robkaandorp** [comment]
Yes, that is exactly my point: `For all pairs on Bitfinex we use 5 significant digits. Examples of five significant digits would be 12.123, 1.1234, 123.43, and 1234.5.`

To take this further: 0.12345, 0.012345 and 0.0012345 also have 5 significant digits.

Precision is not taking into account the leading 0's, while ccxt is truncating it to digits after the dot, which is clearly wrong! Please use .toPrecision(p) for that, and not .toFixed(p). Thank you.

**Comment by kroitor** [comment]
```
> parseFloat ('0.0000000000000000000000000025660').toPrecision (5)
'2.5660e-27'
```

Does that number also have precision of 5 according to your logic?

**Comment by robkaandorp** [comment]
Yes, it has.

**Comment by robkaandorp** [comment]
Let me ask you; How am I supposed to sell 1 XRP for a price of 2566 satoshis on Bitfinex with ccxt? I sure can do that on the site and I think I also can do that if I go directly through their API.

**Comment by kroitor** [comment]
We will remove the precision truncation from there, can't use toPrecision right away, it's JS-only.

**Comment by robkaandorp** [comment]
Thank you, that will be helpful!
Regards, Rob

**Comment by kroitor** [comment]
Ok, the rounding is switched off temporarily until we come up with a portable solution to it. Bitfinex seems to be the only exchange that does treat precision that way.

**Comment by mkutny** [comment]
@kroitor , how do you feel about adding smth like `precisionMode` to bfx `market`s?
If we set it to something like 'sd' (for significant digits) then its presence would notify clients that they need to address this market with different rounding logic.

Right now I hardcoded bitfinex `id` in the client but having some flag in the `market` would be a more elegant solution.

**Comment by kroitor** [comment]
@mkutny the solution you propose might indeed do the trick for us, but let's not call it `sd` )) We would prefer a more explicit name, something like `significantDigitsPrecision = true`... Also, do you think this should be a property of a market of an exchange-wide property?

**Comment by mkutny** [comment]
`significantDigitsPrecision = true` is fine but if you foresee that in the future we might discover some more approaches to rounding then we'll end up with something like:

```
significantDigitsPrecision = false
anotherWayOfRounding = true
yetAnotherWayOfRounding = false
....
```
`precisionMode = [one|two|three]` would handle that in a more natural way.

I just don't know if some more modes are approaching us so rely totally on your intuition )


> Also, do you think this should be a property of a market or an exchange-wide property?

I'd say that having it at a market level (somewhere near existing `precision`) is more logical. But I guess as you asked you want to set it at an exchange level...

**Comment by quorak** [comment]
hey guys, is there actually  some code, that makes the significantDigits rounding work?

**Comment by quorak** [comment]
Ah, found it of course. Would be worth implementing. Took me some while to figure out why my logic was faulty.
`    
    priceToPrecision (symbol, price) {
            return parseFloat (price).toPrecision (this.markets[symbol].precision.price)
    }
`

**Comment by mkutny** [comment]
Beware that Number.toPrecision() rounds up but you might be fine with that.

**Comment by npomfret** [comment]
Did you get to the bottom this?  If I want to format a price for bitfinex, what's the recommended approach?

**Comment by Jay54520** [comment]
Return 61.173 with `bitfinex.amount_to_precision('IOST/USDT', 61.174)`.

**Comment by kroitor** [comment]
@Jay54520 what's your version of ccxt?

**Comment by Jay54520** [comment]
`ccxt==1.17.222`. I installed it at 2018/9/2.

**Comment by kroitor** [comment]
@Jay54520 you should update to most recent version as we've targeted that specific bug and fixed it a couple of days ago. Let us know if it persists with the most recent version 1.17.260

- https://github.com/ccxt/ccxt/pull/3663
- https://github.com/ccxt/ccxt/pull/3803

**Comment by Jay54520** [comment]
No problem with `1.17.260`.

**Comment by Jay54520** [comment]
The logic of decimal precision in https://github.com/ccxt/ccxt/pull/3803/files is sophisticated for me, can you recommend some relevant references?

And in `ccxt==1.17.222`, it is ok if the `amount` param of `amount_to_precision` is `str`. Why didn't you just convert the `amount` to `str` in the implementation
?

**Comment by kroitor** [comment]
> Why didn't you just convert the amount to str in the implementation?

The `decimal_to_precision` method will convert it, be it a string or number. You just continue using `amount_to_precision` as you did earlier, but the bug should be gone. In other words, you don't have to switch to different methods or change your code – but with the new version the bug should be resolved now. Let us know if it's not.
