### ISSUE TITLE
[bitbay] error category question

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6920]
I occasionally get this error from bitbay:

`ExchangeError: bitbay {\"status\":\"Fail\",\"errors\":[\"REQUEST_TIMESTAMP_TOO_OLD\"]}`

I guess it happens if there is a delay in my system between making and executing the request, or there is some clock screw between my machine and the exchange. Either way, I think I can treat it in the same way as a nonce error (ie just try again).  Do we have a category for this type of error?

**Comment by kroitor** [comment]
> Either way, I think I can treat it in the same way as a nonce error (ie just try again). 

Yep.

> Do we have a category for this type of error?

Nope, we can make a new one, but I would simply throw `InvalidNonce` to avoid bloating the error hierarchy, because the handling for it would be pretty much the same. What do you say?

**Comment by npomfret** [comment]
Yes, in this case it's effectively a nonce error.
