### ISSUE TITLE
4H timeframe missing from ByBit

### ISSUE THREAD

**Issue by willoughby** [ccxt/ccxt#6927]
It appears the 4h timeframe has been missed in bybit js.
https://bybit-exchange.github.io/docs/inverse/#t-querykline

MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version: Node 13.0
- CCXT version: 1.27.6

```
this.ccxt.fetchOHLCV('BTC/USD', '4h', undefined, 200);
```

```
BadRequest: bybit {"ret_code":10001,"ret_msg":"Param validation for 'interval' failed on the 'required' tag","ext_code":"","ext_info":"","result":null,"time_now":"1589201782.995792","token":null}
```

**Comment by kroitor** [comment]
> It appears the 4h timeframe has been missed in bybit js.

It is not missed, though – your CCXT version is old, updating your version will fix it.

- https://github.com/ccxt/ccxt/blob/master/js/bybit.js#L51
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/bybit.py#L62
- https://github.com/ccxt/ccxt/blob/master/php/bybit.php#L54

It has been addressed in this duplicate issue here:

- https://github.com/ccxt/ccxt/issues/6885

We recommend to follow the Manual literally – it has a [troubleshooting](https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting) section and the first step there is to make sure that your version is up to date.

Let us know if the above does not help or does not answer your question.
