### ISSUE TITLE
Plans for typescript definition files?

### ISSUE THREAD

**Issue by andersea** [ccxt/ccxt#693]
Hi. There seems to be the beginnings of a typescript definition file for ccxt. As far as I can see it is rather rudimentary at the moment. For instance it looks like it is missing a constructor for the Exchange class.

I have published a definition for another js library to DefinitelyTyped. I may be able to provide assistance in this area. Where would be a good place to start?

**Comment by kroitor** [comment]
Hi! 

> As far as I can see it is rather rudimentary at the moment.

Yep, it was added for integration with the GDAX Trading Toolkit. It is currently in its most basic form and does not cover the whole entirety of our unified API.

> I have published a definition for another js library to DefinitelyTyped. I may be able to provide assistance in this area. 

That would be awesome! Thanks for the offer!

> Where would be a good place to start?

Currently, we have the two main sources of info:
- The User Manual: https://github.com/ccxt/ccxt/wiki
- Contributing Guidelines: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

Those may be somewhat outdated, so, from there feel free to ask any questions. We will assist as far as we can.

**Comment by donaldinho** [comment]
Likewise happy to help with this. The lack of a constructor definition on the exchange class is causing my typescript to not compile.
Would it be possible to get a line added quickly to the ccxt.d.ts file that would fix this.
Something like
```constructor(options?: {});```

I can do a PR if required

**Comment by kroitor** [comment]
> I can do a PR if required

That would be awesome! Go ahead, please, we welcome all PRs and contributions!

**Comment by donaldinho** [comment]
@kroitor made a small pr to add that line in but forgot to add you as a reviewer and I can't see a way to edit the PR to correct that.

@andersea I'm sure there's more to be done with the typescript definitions and I'm happy for you to take the lead on that. I just needed this one line added at the moment so my code will compile

**Comment by kroitor** [comment]
@donaldinho no worries, I'll review and merge it anyway, thanks a lot!

**Comment by kroitor** [comment]
In fact, I've merged it already.

@donaldinho , @andersea , if you don't mind I will close this issue for now, feel free to submit PRs and contributions, we will be very happy for any help! Let us know if you need any assistance. Thx!

**Comment by donaldinho** [comment]
cool. nice one.

@andersea any help I can provide on further typescript improvements just let me know

**Comment by andersea** [comment]
@donaldinho Great! I am by no means an expert on typescript, but the first thing I am wondering is if the overall structure of the definition file is correct.

We are exporting a global, it looks like, with `module.export = Object.assign(...)`.

So shouldn't we be following this template -

https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html

And use `export as namespace ccxt;` at top instead of `declare module 'ccxt'`?

Then all other exports are just on the root level.

**Comment by munrocket** [comment]
@donaldinho thanks for this PR! I am needed this typescript constructor too.
Anyway I think this issue not fully closed and we need more type definition for different exchanges.
I would like to add some type defenition too.

Also I agree with @andersea. It's seems that we have little issue with declaration.

**Comment by kroitor** [comment]
@munrocket the work on this merge is started here: https://github.com/ccxt/ccxt/pull/705

**Comment by munrocket** [comment]
We need this header in the top of ccxt.d.ts
`
export as namespace ccxt;

export const version: string;
export const exchanges: string[];

**here all exports in the root**
`
but this will conflict with #705

**Comment by kroitor** [comment]
@munrocket I'd wait for other participants to comment on this, because I'm not very familiar with Typescript, but, wouldn't `export as namespace ccxt;` *expose* the namespace and thus contradict the principle of encapsulation? Sorry, if I'm making a stupid assumption.

**Comment by munrocket** [comment]
You know that i am not familiar with Typescript too. But it's just work perfectly. Here example of usage with this fix:
```
import ccxt from 'ccxt';
let version = new ccxt.version;
let cmc = new ccxt.coinmarketcap();
```
or we can import only one class of library
```
import { coinmarketcap } from 'ccxt';
let cmc = new coinmarketcap();
```

**Comment by andersea** [comment]
@kroitor  and @munrocket I agree with the example of munrocket above. (But I am also not an expert on this subject, by any means.) From the documentation @munrocket linked, which I also read earlier it looks correct. This is one of the more confusing aspects of typescript though.

As far as I understand it, if it is actually wrong, what will happen is that you can get code that compiles fine, but will fail at runtime because it won't be able to sort out the dependencies correctly in javascript. It should be tested somehow.

I am not quite sure how the autogeneration of exchange specific api's can play into this, if it should be split up so template-based api's is in a separate file maybe.

**Comment by kroitor** [comment]
@andersea currently, we do it with [Travis CI](https://travis-ci.org/ccxt/ccxt/builds) and we upload the JS source that gets transpiled, then gets tested and then the distributions get packaged to various repositories. I don't see a big problem with adding one more language for testing, because we already have `./run-tests.js` that checks JS, Python and PHP for us. So, throwing Typescript into this build chain should be trivial if we generate it properly and write the tests, of course. We can take existing JS tests for reference.

**Comment by munrocket** [comment]
Ok new fix `declare module 'ccxt' {` works well too. Thanks.

> I am not quite sure how the autogeneration of exchange specific api's can play into this, if it should be split up so template-based api's is in a separate file maybe.

This will be really cool.

**Comment by dang1412** [comment]
I am developing this for realtime api and typescript. It is still in very early stage now and just a few exchanges supported. Let me know what would fit your need and i will improve, love to see your feedback
https://github.com/dang1412/ccex-api
