### ISSUE TITLE
DeriBit Subscribe

### ISSUE THREAD

**Issue by T9309** [ccxt/ccxt#6931]
- OS: Kubuntu 20.10 64-bit
- Programming Language version: Python 3.8.2
- CCXT version: 1.27.54

```python
import ccxt.async_support as ccxt
import asyncio

deri = ccxt.deribit()

async def subs():
   print ((await deri.public_get_subscribe({"channels": ["trades.BTC-PERPETUAL.raw"]})))

asyncio.get_event_loop().run_until_complete(subs())
```

```python
ccxt.base.errors.BadRequest: deribit {"jsonrpc":"2.0","error":{"message":"Invalid params","data":{"reason":"value must be a list","param":"channels"},"code":-32602},"testnet":false,"usIn":1589288990523561,"usOut":1589288990524197,"usDiff":636}
```

**Comment by kroitor** [comment]
@T9309 those endpoints are only available via ws: https://docs.deribit.com/#public-subscribe. Deribit has not been added to [CCXT Pro](https://ccxt.pro/) with WS yet, but, hopefully, will be there soon. Let us know if that does not answer the question.

**Comment by T9309** [comment]
This will therefore be only available in CCXT Pro if I understand correctly?
