### ISSUE TITLE
Can you buy/sell using a relative percentage amount instead of a fixed amount?

### ISSUE THREAD

**Issue by artwebb** [ccxt/ccxt#6933]
My apologies if this was asked a million times, as I've searched for several hours now with no hope (aside from possibly incorporating "fetch balance"???)

I basically want to buy and sell using a percentage amount instead of a static amount!

Thanks and blessings!

**Comment by kroitor** [comment]
@artwebb 

> I basically want to buy and sell using a percentage amount instead of a static amount!

A percentage amount is mathematically the same as a fixed part of a static amount. So, any percentage of a static total will be static anyway.

If your balance is 100 BTC and you want to buy or sell 50% of your balance then multiply 100 BTC * 0.5 = 50 BTC and buy or sell a static amount of 50 BTC depending on what you need.

Does that answer your question?

**Comment by artwebb** [comment]
Thanks for the quick response! It would still need to be relative, because it’s going to be a bot that needs to trade 100% regardless of the size of the portfolio. I am doing this now with Zignaly and TradingView alerts set to trade 98% always so regardless of portfolio size I’m getting the entire amount into the trade as it compounds.

I basically wanna be on the beach not trading ;P

Is it possible?? Thanks so much for your time! Am willing to hire a coder so long as I am aware that it’s possible with CCXT (or python?)

—
Art Webb Design
art@artwebbdesign.com
http://artwebbdesign.com

**Comment by kroitor** [comment]
> I basically wanna be on the beach not trading ;P

Ok, you can be trading on the beach as well ))

> It would still need to be relative, because it’s going to be a bot that needs to trade 100% regardless of the size of the portfolio. I am doing this now with Zignaly and TradingView alerts set to trade 98% always so regardless of portfolio size I’m getting the entire amount into the trade as it compounds.

CCXT does not operate with the size of your portfolio – it does not manage the portfolio. CCXT is a constructor of building blocks. It provides a set of methods, that the developer can combine to operate with the portfolio. Including calculating the 50% size of the position, etc. But CCXT does not manage the portfolio for the developer. In other words, with CCXT the developer can reproduce the logic used by Zignaly or TradingView, however, it requires adding code on the user side. CCXT operates with amounts, prices and costs as explained in the Manual. So it's up your hired dev to calculate how much is 50% of your portfolio.

Let me know if that does not help.

**Comment by artwebb** [comment]
Excellent, that's what I figured. Would I use fetch balance? That was what I imagined would work. I'll gladly post the code here for others to use because I could see this being incredibly valuable!

**Comment by kroitor** [comment]
> Would I use fetch balance?

To fetch your actual value of assets you would use fetchBalance in most cases, yes. However, a position is not just the balance. It also involves the orders you've opened. So you will need to combine `fetchBalance` + `fetchOrders / fetchOpenOrders / fetchClosedOrders` to calculate the real size of your position how you want.

**Comment by artwebb** [comment]
Ok fantastic, thanks so much! I'll be back soon with some python code. 

BTW I really appreciate you helping everyone on here for all these years. Was a pleasure searching on here because I can sense that you genuinely love this project and it really comes through in your patience and positive responses. :)

**Comment by muenze8** [comment]
> Ok fantastic, thanks so much! I'll be back soon with some python code.
> 
> BTW I really appreciate you helping everyone on here for all these years. Was a pleasure searching on here because I can sense that you genuinely love this project and it really comes through in your patience and positive responses. :)

Hi bro,

did u manage to write this code?
I am also looking into it.
