### ISSUE TITLE
[lykke] api url looks wrong

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6935]
The swagger docs (https://hft-api.lykke.com/api/OrderBooks/ETCBTC ) are pointing to `https://public-api.lykke.com/api/OrderBook/ETCBTC` (not `https://hft-api.lykke.com/api...`)

**Comment by kroitor** [comment]
To me it looks like the API has been changed / broken. The endpoints don't match anymore. I would consider the Lykke implementation broken until we fix it.

**Comment by npomfret** [comment]
looks like they changed it back

**Comment by kroitor** [comment]
@npomfret thx!
