### ISSUE TITLE
binance getAllAsset, dont work

### ISSUE THREAD

**Issue by renatoclt** [ccxt/ccxt#6938]
Hello, I try to get data from this service:

https://www.binance.com/assetWithdraw/getAllAsset.html

and the result is

{"msg": "Update the application version", "success": "false"}

what is the correct version?  or what should I do?

**Comment by kroitor** [comment]
Hi! 

> what is the correct version? 

Paste your output here:

```Python
import ccxt
print(ccxt.__version__)
```

> or what should I do?

You should follow the guidelines literally: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

Can you plz paste your code snippet to reproduce the issue + your verbose request/response ?

**Comment by kroitor** [comment]
Looks like that endpoint is deprecated, if that is the case we will remove it shortly.
