### ISSUE TITLE
HTTPError-Bitmex

### ISSUE THREAD

**Issue by antebw** [ccxt/ccxt#6939]
I keep getting this error like 1 or 2 time per hour, my rate limit is enabled and set to 2000ms, also my local time differs from BitMEX by  0 seconds. Any thoughts , thx.

- OS: Ubuntu 18.04
- Programming Language version: Python
- CCXT version: Last

```
columnname = ['OpenTime', 'Open', 'High', 'Low', 'Close', 'Volume']

def OHLC():
    since = int((time.time()*1000)-24*60*60*1000)
    ohlc = exchange.fetch_ohlcv('BTC/USD', '1h', since)
    df = pd.DataFrame(ohlc, columns=columnname, dtype='float')
```

```
bitmex {"error":{"message":"This request has expired - `expires` is in the past. Current time: 1589426170","name":"HTTPError"}}
BitMEX exchange time UTC:  2020-05-14T03:16:10.000Z
Your Python time UTC:  2020-05-14T03:16:10.000Z
Your local time differs from BitMEX by  0 seconds

```

**Comment by kroitor** [comment]
How do you initialize the exchange instance?
We need you to follow this precisely (literally to a word) – need a complete snippet to reproduce it and your verbose request+response, as described here:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.bitmex({
    'enableRateLimit': True,
})
exchange.load_markets()
exchange.vebose = True  # enable verbose mode after loading the markets
exchange.fetch_ohlcv('BTC/USD', '1h')
```

↑ This is the look of code that we will expect from you (but without your API keys, of course). Please, paste your actual code including instantiation and your output here.

**Comment by kroitor** [comment]
Closing this for now, feel free to reopen it or just ask further questions, if any.

Related: 

- https://github.com/ccxt/ccxt/issues/4307
- https://github.com/ccxt/ccxt/pull/6178
