### ISSUE TITLE
"ExchangeError: binanceus {"code":-1102...}"

### ISSUE THREAD

**Issue by crossx4real** [ccxt/ccxt#6948]
- OS: Windows 10
- Programming Language version: Node Js
- CCXT version: 6.14.4
- Exchange: Binanceus

igor: how you doing man?

hey i know i am doing something wrong here but i can't seem to pinpoint. 

I am trying to send a market order but i am getting error code: "ExchangeError: binanceus {"code":-1102,"msg":"Mandatory parameter 'quantity' was not sent, was empty/null, or malformed."}"

see my code below:

orderOBJ =  { tradingPair: 'BTC/USD',
  tradeType: 'buy',
  orderType: 'market',
  price: 9775.39,
  amount: 0.00223 
}

try{
        myOrder = await exchange.createOrder(
			orderOBJ.tradingPair, orderOBJ.orderType, 
                       orderOBJ.tradeType, orderOBJ.amount, orderOBJ.price, {});
}
catch(err) {...}

lastly you should setup brave publisher account for on your github get some of these tips no?

**Comment by kroitor** [comment]
Hi @crossx4real ! For binance.us the market type does not require a price.
In general, you don't need to set the price, except for market buys for the exchanges that have `.options['createMarketBuyRequiresPrice']`.

```JavaScript
orderOBJ =  { tradingPair: 'BTC/USD',
  tradeType: 'buy',
  orderType: 'market',
  price: 9775.39,
  amount: 0.00223 
}

try{
        myOrder = await exchange.createOrder(
			orderOBJ.tradingPair, orderOBJ.orderType, 
                       orderOBJ.tradeType, orderOBJ.amount);
}
catch(err) {...}
```

↑ Let us know if the above does not help.

> lastly you should setup brave publisher account for on your github get some of these tips no?

Brave browser requires too much personal info, i'm not that brave, tbh.
```

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/6903#issuecomment-625265404
