### ISSUE TITLE
CoinEx withdraw transfer_method "1 is not a valid choice"

### ISSUE THREAD

**Issue by adam-co** [ccxt/ccxt#6951]
Hi!
Really appreciate the CCXT library, it's been extremely helpful for me.
But as a heads up, I came across an issue with CoinEx withdraws.  The default CCXT transfer_method param of '1' did not work for me.  Eventually I figured out that setting transfer_method to 'onchain' allowed my withdraw order to go through.  I don't know if this is an issue for everyone, but if anyone else does encounter the same error, try adding this line as a workaround:

```params['transfer_method'] = 'onchain';```

Also, I had to add the address to the CoinEx API withdraw whitelist, via CoinEx website/app.  This is not a CCXT problem, just want to mention it in case it stumps anyone else.

- OS: Windows 10
- Programming Language version: JS 8.1.307.32
- CCXT version: 1.27.80

Partial reproduction code (Uncomment the params[] line to workaround the issue)
```
var withdrawAddress = 'XXXXYYYYZZZZ';
var params = {};
//params['transfer_method'] = 'onchain';
var transaction = await exchange.withdraw('NEO', 10, withdrawAddress, '', params);
```

Here's the error that I received, when '1' is used as the transfer_method, instead of 'onchain'.
```
ExchangeNotAvailable: coinex POST http://localhost:8080/https://api.coinex.com/v1/balance/coin/withdraw 400 Bad Request {"message": {"transfer_method": "1 is not a valid choice"}}
 (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)
```

**Comment by kroitor** [comment]
Hi! Thank you for reporting it, we appreciate the feedback. The above looks like a bug caused by an outdated implementation, they might have changed their API specification – anyways, we will add a fix shortly. Thx again!
