### ISSUE TITLE
ccxt.okex().fetchTickers([…]) returns all tickers

### ISSUE THREAD

**Issue by FishEmperor** [ccxt/ccxt#6956]
OS: MacOS
Programming Language version: nodejs
CCXT version:"1.27.85",
Exchange: okex
Method: fetchTickers
fetchTickers returns all instead of the given tickers.

**Comment by FishEmperor** [comment]
Programming Language version: python

**Comment by kroitor** [comment]
Thanks for reporting! I've added the filtering by symbols to it, so it should work as expected as of 1.27.86+, the new build will arrive in 10-15 minutes. Let us know if that helps or not.
