### ISSUE TITLE
Error while running tests

### ISSUE THREAD

**Issue by abhishekr700** [ccxt/ccxt#6958]
- OS: MacOS
- CCXT version: Latest

Hi, I was testing private endpoints. My tests pass with js, but report errors in python
This is the line causing trouble

```
data = {
                'symbol': '/' + path + '/' + self.safe_string(params, 'symbol'),
                'timeStamp_nonce': timeStamp_nonce,
                'body': body,
}
payload = base64.b64encode(self.json(data))
```

Error is 

```
	<class 'TypeError'> a bytes-like object is required, not 'str'
```

**Comment by kroitor** [comment]
Hi @abhishekr700 !

The string has to be wrapped in `this.encode()` before converting it to base64 (see other exchanges, in particular, how data is encoded with `this.encode()` in JS before base64ing in almost all implementations of the `sign()` function – ctrl+f _"this.encode"_ throughout the repository).

Let me know if that does not help. Feel free to reopen it, or just ask further questions, if any.
