### ISSUE TITLE
Position Open Date

### ISSUE THREAD

**Issue by Thjdid** [ccxt/ccxt#6961]
Hi guys, 
On deribit, I would like to know the date (timestamp) a position has been opened at. 
I am aware I can get timestamp for trades, but is there any way to do the same for a position ?
Thanks in advance for any insight!

**Comment by kroitor** [comment]
> I am aware I can get timestamp for trades, but is there any way to do the same for a position ?

Your position is a cumulative result all your buy/sell orders. The position exists at zero if you haven't placed any orders. When you place an order your position grows from zero up, when you place an opposite order your position shrinks down to zero. It exists regardless of the size of the position (a zero position is also called a neutral position). Therefore a position is not supposed to have a timestamp, really. So, the opening timestamp of your position is the timestamp of your first order that changed your position.

Let us know if that does not answer your question.

**Comment by Thjdid** [comment]
Hi Kroitor, 
Thanks for the explanation, it totally makes sense. That's what I thought but I am always happy to get you point of view for confirmation :).
