### ISSUE TITLE
Why does php tests print balance ?

### ISSUE THREAD

**Issue by abhishekr700** [ccxt/ccxt#6962]
Hi,
I was testing my exchange implementation (both public & private tests).
I was able to get success with js & python but php was giving warnings continuously. On checking the test.php file, I came across this line
[Line](https://github.com/ccxt/ccxt/blob/4e279314b5a9cec22e5a83e37370b9e83ea1ee21/php/test/test.php#L210)
If I comment it out, my php tests pass successfully. Is there a reason for this line to be here ? Because this output is in my guess bein interpreted as warnings.

**Comment by kroitor** [comment]
It's a `print_r`, meaning that it is a debug output, so it should not yield any issues, because print_r should be able to print any value. 

> but php was giving warnings continuously

Can you post the warnings or the verbose log?

**Comment by abhishekr700** [comment]
@kroitor  Kindly have a look here https://hastebin.com/palipamusi.php

**Comment by abhishekr700** [comment]
I can say for sure that just turning off that output leads to a Success !

**Comment by kroitor** [comment]
@abhishekr700 alright, it's a side-effect of detecting `[smth]` in the output coming from the tests, anything with square brackets is considered the exception output by `run-tests.js` now. I will fix that spot shortly, in the meantime, you can safely ignore those warnings.

**Comment by abhishekr700** [comment]
Thank you !
