### ISSUE TITLE
[bitfinex1] Cann't request transactions for old symbols

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6968]
I would like to get my old transfers for BCH from bitfinex1.  The current implementation will translate the `code` argument for _BCH_ to _BAB_ because of the rename.  But pre-fork deposits are only accessible vis the old symbol _BCH_.  

If I call:

    await exchange.fetchTransactions(undefined, 0, limit, {
                    currency: currencyId,
    });

I get an error, because ccxt expected a currency code param.  Can we make a change so that if a `currency` param is supplied, then the first parameter can be undefined?  IMO this should be a general pattern.

**Comment by kroitor** [comment]
> Can we make a change so that if a currency param is supplied, then the first parameter can be undefined?

We will look into that, in the meantime, you can workaround this by supplying at least some non-empty currency code to `fetchTransactions()`.

```JavaScript
await exchange.fetchTransactions('BTC', 0, limit, { currency: currencyId });
```

**Comment by npomfret** [comment]
Hmm, if I supply BTC, but put BCH in the currency param nothing comes back.  I guess it's getting filtered in ccxt?

**Comment by kroitor** [comment]
@npomfret yes, pardon, you are 100% right, will address that asap.

**Comment by npomfret** [comment]
@kroitor thank you again for looking at this so quickly - much appreciated
