### ISSUE TITLE
I'm struggling to pass parameters to Binance's margin trading functions in ccxt. Are there examples/is there a resource which explains?

### ISSUE THREAD

**Issue by pheonixlife** [ccxt/ccxt#6969]
- OS: Windows 10 
- Programming Language version: Python 3.8
- CCXT version: 1.27.89

```
data = {"symbol":"BTC/USDT",
"marginType": "ISOLATED",
"type":"MARKET",
"side":"BUY",
"amount":"0.03"}

print(exchange.fapiPrivate_post_margintype(data))
```

```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/marginType
ccxt.base.errors.ExchangeError: binance {"code":-1121,"msg":"Invalid symbol."}
```

**Comment by kroitor** [comment]
This is explained here: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

```Python
exchange.load_markets()  # preload markets first
market = exchange.markets['BTC/USDT']  # get the market by a unified symbol
data = {
    "symbol":market['id'],  # send the exchange-specific market id
    "marginType": "ISOLATED",
    "type":"MARKET",
    "side":"BUY",
    "amount":"0.03"
}
print(exchange.fapiPrivate_post_margintype(data))
```

Let us know if the above does not help.

**Comment by pheonixlife** [comment]
getting: ccxt.base.errors.ExchangeError: binance {"code":-4046,"msg":"No need to change margin type."}

**Comment by kroitor** [comment]
@pheonixlife what exactly are you trying to do with that implicit endpoint? You don't want to send the `side`, the `amount` and the `type`.

See the params required for that endpoint here: 

- https://binance-docs.github.io/apidocs/futures/en/#change-margin-type-trade

Also, this section of CCXT Manual explains how to call any endpoint and how to pass the params: 

- https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods

So, the steps to do what you want are easy: find a margin-specific endpoint that you want to call, see the docs for which params are requires (no need for auth params like `timestamp` and `recvWindow` – those are handled by CCXT for you), and then pass the required params and the optional params to that endpoint, according to the exchange API docs.

This message from Binance `binance {"code":-4046,"msg":"No need to change margin type."}` says that your margin is already ISOLATED, so you don't need to change it to ISOLATED.

Let us know if that does not answer your question.

**Comment by meteyalciner** [comment]
info = exchange.fapiprivatev2_get_positionrisk(
            {"symbol": market["id"]
             })[0]

        if info["marginType"] != 'isolated':
            exchange.fapiPrivatePostMarginType({
                "symbol": market["id"],
                "marginType": "ISOLATED",
            })

        if int(info['leverage']) != leverage:
            exchange.fapiprivate_post_leverage({
                "symbol": market['id'],
                "leverage": int(leverage),
            })

**Comment by carlosmiei** [comment]
@meteyalciner Those methods are not unified, so you don't need to use the implicit API directly
