### ISSUE TITLE
Check Trading Pairs on Individual Exchanges

### ISSUE THREAD

**Issue by noahwoodin** [ccxt/ccxt#6972]
Hi,

Wondering if there is a way to check or list all trading pairs for each exchange indvidually, ie
Binance:
BTC/USDT
XRP/USDT
etc
Bittrex:
BTC/USDT
XRP/USDT
etc

This might already exist however I cant find it and if it doesnt exist I think it would be very useful.
Thanks

**Comment by kroitor** [comment]
Hi!

Please, see the Manual and the examples:

- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/tree/master/examples
