### ISSUE TITLE
Binance Futures - Change Leverage (Python)

### ISSUE THREAD

**Issue by JanssensKobe** [ccxt/ccxt#6978]
I'm not able to change the leverage with the "fapiPrivate_post_leverage" function. Can someone help me?

- OS: Windows 10 x64
- Programming Language version: Python 3.8.2
- CCXT version: 1.28.3

Code:
```
import ccxt

binance = ccxt.binance({
    "options": {"defaultType": "future"},
    "timeout": 30000,
    "apiKey":"xxx",
    "secret": "xxx",
    "enableRateLimit": True,
})

binance.fapiPrivate_post_leverage("BTC/USDT", 10)
```

Error message:
```
TypeError: inner() takes from 1 to 2 positional arguments but 3 were given
```

**Comment by kroitor** [comment]
Hi! 

Please, see:

1. how unified ccxt symbols differ from exchange-specific market ids: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
2. how implicit API endpoints are called: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

You should pass an object containing the params, instead of supplying the params as arguments:

```Python
import ccxt

binance = ccxt.binance({
    "options": {"defaultType": "future"},
    "timeout": 30000,
    "apiKey":"xxx",
    "secret": "xxx",
    "enableRateLimit": True,
})

binance.load_markets()  # load markets to get the market id from a unified symbol
market = binance.markets['BTC/USDT']
binance.fapiPrivate_post_leverage({
    "symbol": market['id'],  # convert a unified CCXT symbol to an exchange-specific market id
    "leverage": 10,
})
```

Let us know if the above does not help.

**Comment by kroitor** [comment]
Related: https://github.com/ccxt/ccxt/issues/6357

**Comment by bluesme519** [comment]
```
binance.fapiPrivate_post_leverage({
    "symbol": market['id'],  # convert a unified CCXT symbol to an exchange-specific market id
    # "symbol": "BTCUSDT",  # same thing, note there's no slash in the exchange-specific id
    "leverage": 10,
})
```
the code worked fine got timestamp issue with the code above
`InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}`

tried to fix this with
`    binance = ccxt.binance(config={
        'apiKey': api_key,
        'secret': secret,
        'enableRateLimit': True, 
        'options': {
            'defaultType': 'future',  # ←-------------- quotes and 'future'
            "adjustForTimeDifference": True
        }
    })`
but still didn't get through it. anyone got same problem?

**Comment by kroitor** [comment]
@bluesme519 try syncing the system clock: #850

**Comment by bluesme519** [comment]
> @bluesme519 try syncing the system clock: #850, though, adjustForTimeDifference should have had the effect.

and I'm curious why fapiPrivate_post_leverage is causing the timestamp server time problem. without it, it works perfect...

**Comment by kroitor** [comment]
@bluesme519 it's hard to tell the exact cause without your verbose output for the request+response in question: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by bluesme519** [comment]
you know what? this is wierd

```
    binance.fapiPrivate_post_leverage({
        "symbol": "BTCUSDT",  # convert a unified CCXT symbol to an exchange-specific market id
        # "symbol": "BTCUSDT",  # same thing, note there's no slash in the exchange-specific id
        "leverage": 3,
    })
```
the code above occurs timestamp error

Strangely, the code below works well
```
    binance.load_markets()  # load markets to get the market id from a unified symbol
    market = binance.markets['BTC/USDT']
    binance.fapiPrivate_post_leverage({
        "symbol": market['id'],  # convert a unified CCXT symbol to an exchange-specific market id
        # "symbol": "BTCUSDT",  # same thing, note there's no slash in the exchange-specific id
        "leverage": 3,
    })
```
it is strange because, market['id'] is "BTCUSDT"........

**Comment by kroitor** [comment]
@bluesme519 what is your version of CCXT?

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
```

If it's older than 1.43, please upgrade.

**Comment by bluesme519** [comment]
> @bluesme519 what is your version of CCXT?
> 
> ```python
> import ccxt
> print('CCXT Version:', ccxt.__version__)
> ```
> 
> If it's older than 1.43.xx, please upgrade.

mine is

`CCXT Version: 1.43.40`

**Comment by kroitor** [comment]
@bluesme519 interesting... can you catch this with verbose mode on, though? Ideally, this request+response, and the one that was before it.

**Comment by kroitor** [comment]
@bluesme519 if anything, increading the recvWindow value might help (one more option for binance).

**Comment by bluesme519** [comment]
I'm on Mac OS Big Sur 11.2.3, the latest version
One more thing that I didn't mention...The first code worked but after I while looped it for a day(there is time.sleep(300) in it), the error suddenly appeared.

Sorry about being noob but, I've been on Mac for a week, and new to programming either...so Can you please explain me how to catch this with verbose mode on?

**Comment by kroitor** [comment]
@bluesme519 no problem, we have Big Sur also, but it's hard to reproduce the problem, cause we don't see the same behaviour on our side. If you could catch the exception in verbose mode as documented here: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help, that will help speed things up, and we might resolve this faster.

**Comment by bluesme519** [comment]
> @bluesme519 no problem, we have Big Sur also, but it's hard to reproduce the bug, cause we don't see the same behaviour on our side. If you could catch the exception in verbose mode as documented here: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help, that will help speed things up, and we might resolve this faster.

I'm not sure if I'm doing it right, but this is what I got after i put verbose_mode=True

`Request: POST https://fapi.binance.com/fapi/v1/leverage {'X-MBX-APIKEY': 'JlYFtrLJmvO12RdWJMNi4Ncuc2p6FBXG8POQOZs7h9Inw6AcD4lOWh9SWqX0jBWs', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} timestamp=1616432517307&recvWindow=5000&symbol=BTCUSDT&leverage=3&signature=b05381f90cb85d91eacc4d8ead15604bdd797801d5d26f8eb493b1a06aaaff9a

Response: POST https://fapi.binance.com/fapi/v1/leverage 400 {'Content-Type': 'application/json', 'Content-Length': '88', 'Connection': 'keep-alive', 'Date': 'Mon, 22 Mar 2021 17:01:54 GMT', 'Server': 'Tengine', 'X-MBX-USED-WEIGHT-1M': '2', 'x-response-time': '0ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 f872ea854cda487277bd77eed683ad7d.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ICN54-C1', 'X-Amz-Cf-Id': '1k_z0I9qs_b4wPy0ER8iDfDoIYL_l2hzvSCbK8WoCNgH3XICrOqoiQ=='} {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 594, in fetch
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/leverage

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/test/Desktop/python projects/binance_cctx.py", line 39, in <module>
    binance_object_creation()
  File "/Users/test/Desktop/python projects/binance_cctx.py", line 22, in binance_object_creation
    binance.fapiPrivate_post_leverage({
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 468, in inner
    return entry(_self, **inner_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/binance.py", line 2749, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 489, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 610, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/binance.py", line 2743, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 507, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}`

**Comment by kroitor** [comment]
@bluesme519 if one call to set the leverage works, and then the other call fails, then please, post the request+response for both calls:

```
    binance.load_markets()  # load markets to get the market id from a unified symbol
    
    binance.verbose = True
    
    market = binance.markets['BTC/USDT']
    
    binance.fapiPrivate_post_leverage({
        "symbol": market['id'],  # convert a unified CCXT symbol to an exchange-specific market id
        # "symbol": "BTCUSDT",  # same thing, note there's no slash in the exchange-specific id
        "leverage": 3,
    })
    
    binance.fapiPrivate_post_leverage({
        # "symbol": market['id'],  # convert a unified CCXT symbol to an exchange-specific market id
        "symbol": "BTCUSDT",  # same thing, note there's no slash in the exchange-specific id
        "leverage": 3,
    })
```

If the above works, that means you're violating this part of the Manual: https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter

If every call to set the leverage fails for you, i'd recommend contacting Binance tech support, since it may be that Cloudflare flagged your IP (try from a different location to rule that out) or it could be related to a flag on your account. In both cases only Binance can really help resolve it.

**Comment by bluesme519** [comment]
> @bluesme519 if one call to set the leverage works, and then the other call fails, then please, post the request+response for both calls:
> 
> ```python
>     binance.enableRateLimit = True
> 
>     binance.load_markets()  # load markets to get the market id from a unified symbol
>     
>     binance.verbose = True
>     
>     market = binance.markets['BTC/USDT']
>     
>     binance.fapiPrivate_post_leverage({
>         "symbol": market['id'],  # convert a unified CCXT symbol to an exchange-specific market id
>         # "symbol": "BTCUSDT",  # same thing, note there's no slash in the exchange-specific id
>         "leverage": 3,
>     })
>     
>     binance.fapiPrivate_post_leverage({
>         # "symbol": market['id'],  # convert a unified CCXT symbol to an exchange-specific market id
>         "symbol": "BTCUSDT",  # same thing, note there's no slash in the exchange-specific id
>         "leverage": 3,
>     })
> ```
> 
> If the above works, that means you're violating this part of the Manual: https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter
> 
> If every call to set the leverage fails for you, i'd recommend contacting Binance tech support, since it may be that Cloudflare flagged your IP (try from a different location to rule that out) or it could be related to a flag on your account. In both those cases only Binance can really help resolve it.

The code I made was reusing the same instance over and over again. I need to change it to reduce burdens of binance api server. Thank you so much for your guidance for all bunch of stuffs!!
