### ISSUE TITLE
Binance → v3

### ISSUE THREAD

**Issue by Deathamns** [ccxt/ccxt#698]
At [Binance](https://www.binance.com/restapipub.html) some API endpoints are in version `v1` and some are in `v3`, however in ccxt the version is always set to `v1`. Creating a new `binance3.js` wouldn't make sense, because as I said some basic features are available only via `v1`.
How should I approach this (to stay compatible with the current architecture) if I want to add other features that are available via `v3`?

**Comment by kroitor** [comment]
Here's an answer of the lead dev from Binance: https://github.com/ccxt/ccxt/issues/320#issuecomment-341877217

I think we should switch current implementation to v3 seamlessly. No need to keep them both. I've already added the v3 signing method, so this should be straightforward (mostly). Didn't have time to finish the migration yet.

<img width="638" alt="screen shot 2017-11-28 at 16 05 50" src="https://user-images.githubusercontent.com/1294454/33321241-0c639e60-d456-11e7-90c4-f2ea0bef09b6.png">

Thx!

**Comment by Deathamns** [comment]
Yeah, but there's no orderbook endpoint for [`v3`](https://api.binance.com/api/v3/depth?symbol=BCCBTC&limit=100), only for [`v1`](https://api.binance.com/api/v1/depth?symbol=BCCBTC&limit=100), so we still have to use both versions in the URLs. And this was my problem.
I could simply remove the `version` property and change the API urls to the followings, but is that okey with you?

```js
'api': {
    'web': 'https://www.binance.com',
    'wapi': 'https://www.binance.com/wapi/v3',
    'public': 'https://api.binance.com/api/v1',
    'private': 'https://api.binance.com/api/v3',
},
```
Because these are the valid endpoints listed in the API:
```
GET /api/v1/ping
GET /api/v1/time
GET /api/v1/depth
GET /api/v1/aggTrades
GET /api/v1/klines
GET /api/v1/ticker/24hr
GET /api/v1/ticker/allPrices
GET /api/v1/ticker/allBookTickers

POST /api/v3/order
POST /api/v3/order/test
GET /api/v3/order
DELETE /api/v3/order
GET /api/v3/openOrders
GET /api/v3/allOrders
GET /api/v3/account
GET /api/v3/myTrades

POST /wapi/v3/withdraw.html
GET /wapi/v3/depositHistory.html
GET /wapi/v3/withdrawHistory.html
GET /wapi/v3/depositAddress.html
```

**Comment by kroitor** [comment]
> I could simply remove the version property and change the API urls to the followings, but is that okey with you?

Absolutely. It will do exactly what we want, the version of Binance in our docs will be `*` (this will indeed reflect the truth) and those API base URLs will work as well. But note that you will have to edit the `sign()` method (delete a few lines from it). In its current code it appends the `this.version` to the compiled URL.
