### ISSUE TITLE
Problem with Coinbase (Transactions)

### ISSUE THREAD

**Issue by Droppix** [ccxt/ccxt#6981]
Hi,

CCXT version 1.21.34, works with Coinbase (fetchTransanctions --> privateGetAccountsAccountIdTransactions)
CCXT latest versions, don't works correctly :

1/ Why fetchTransactions -> hasFetchTransactions = false ?
2/ method parseTransaction (transaction, market = undefined) : Problem decoding object

Latest version : 
'subtotal' don't exist (in my all transactions BTC/LTC/XRP/XLM/...)
```
const subtotalObject = this.safeValue (transaction, 'subtotal', {});
....
const amount = this.safeFloat (subtotalObject, 'amount');
const currencyId = this.safeString (subtotalObject, 'currency');
```
Before version : Works with all my transactions
```
const amountObject = this.safeValue (transaction, 'amount', {});
...
const amount = this.safeFloat (amountObject, 'amount');
const currencyId = this.safeString (amountObject, 'currency');
```

3/ Other remark (concern all versions):
For me 'txid' cannot be equal to 'id', it confuses, because txid should match transaction id on the blockchain. I think it would be best if he stayed at 'undefined'
```
     	return {
            'info': transaction,
            'id': id,
            'txid': id, // 'txid': undefined,
            'timestamp': timestamp,
            ...
        };
```

it's possible to correct this?
Thanks

**Comment by kroitor** [comment]
Hi!

> 1/ Why fetchTransactions -> hasFetchTransactions = false ?

Coinbase doesn't have a method for fetching transactions at once in their API. Despite that their endpoint is called `privateGetAccountsAccountIdTransactions` – that endpoint does not return transactions, instead it returns ledger entries. That `transactions` word is what confuses you in this case. The exchanges call their endpoints how they want. The difference between a transaction and a ledger entry is explained in the Manual. So, Coinbase has `fetchDeposits`, `fetchWithdrawals` and `fetchLedger` instead. All of those methods are described in the Manual.

That was also covered here:

- https://github.com/ccxt/ccxt/pull/4179
- https://github.com/ccxt/ccxt/pull/5436
- https://github.com/ccxt/ccxt/issues/4886
- https://github.com/ccxt/ccxt/search?q=coinbase+fetchLedger&type=Issues

I hope that answers your first question.

> 2/ method parseTransaction (transaction, market = undefined) : Problem decoding object

We need to see:
a) your verbose request/response
b) your code to reproduce it, including the exchange instantiation (without your keys, of course). Can you plz post a+b here? It could be partially explained by the answer to your first question as well.

> 3/ Other remark (concern all versions):
> it's possible to correct this?

If it's an error – we will correct it, however, we need your verbose request+response and your code (make it as short as possible, remove everything irrelevant from it, but include the exchange instantiation code to make it short complete snippet).

**Comment by Droppix** [comment]
Thanks, for your response.

Same as for BTC/LTC/XLM/XRP/... (I tested...)
```
await ccxt.fetchTransactionsWithMethod("privateGetAccountsAccountIdTransactions", "BTC")                    
```

Request:
```
{
  "url": "https://api.coinbase.com/v2/accounts/XXXXX/transactions",
  "method": "GET",
  "headers": {
    "CB-ACCESS-KEY": "xxxxx",
    "CB-ACCESS-SIGN": "xxxx",
    "CB-ACCESS-TIMESTAMP": "1589974997",
    "Content-Type": "application/json"
  }
}
```
Response result catched : **parseTransaction(transaction, market = undefined)**
As you can see, "subtotal" doesn't exist but only "amount".
```
transaction = {
  "id": "XXXX",
  "type": "trade",
  "status": "completed",
  "amount": {
    "amount": "0.07071920",
    "currency": "BTC"
  },
  "native_amount": {
    "amount": "569.90",
    "currency": "EUR"
  },
  "description": null,
  "created_at": "2020-05-11T07:10:16Z",
  "updated_at": "2020-05-11T07:10:18Z",
  "resource": "transaction",
  "resource_path": "/v2/accounts/XXXX/transactions/YYYYY",
  "instant_exchange": false,
  "trade": {
    "id": "XXXX",
    "resource": "trade",
    "resource_path": "/v2/accounts/XXXX/trades/XXXX"
  },
  "details": {
    "title": "Converted to Bitcoin",
    "subtitle": "Using Portefeuille en LTC",
    "payment_method_name": "Portefeuille en LTC"
  }
}
```
It's enough for you?

**Comment by kroitor** [comment]
> Same as for BTC/LTC/XLM/XRP/... (I tested...)
> await ccxt.fetchTransactionsWithMethod("privateGetAccountsAccountIdTransactions", "BTC") 

You're not supposed to call `fetchTransactionsWithMethod` with `privateGetAccountsAccountIdTransactions` because that method is supposed to work with `privateGetAccountsAccountIdDeposits` or `privateGetAccountsAccountIdWithdrawals` (therefore it is not a unified method, it's for internal purposed implementing the fetchWithdrawals and fetchDeposits).

If you want to call the `privateGetAccountsAccountIdTransactions` endpoint – you should call `fetchLedger` instead. Does that answer your question?

**Comment by kroitor** [comment]
In other words, this will work:

```Python
exchange.fetchLedger ()
```

```Python
exchange.privateGetAccountsAccountIdTransactions({
    'account_id': YOUR_ACCOUNT_ID,
})
```

Let us know if that does not help.

**Comment by Droppix** [comment]
Great!
Thanks
