### ISSUE TITLE
[hitbtc] trade fee missing currency

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#6982]
{
            "info": {"id": 849899156, "clientOrderId": "c6349c2ef7734447a106cd3ac982c23b", "orderId": 245637799183, "symbol": "IOSTBTC", "side": "sell", "quantity": "6920", "price": "0.0000003764", "fee": "0.000001823282", "timestamp": "2020-05-20T02:21:55.024Z"},
            "id": "849899156",
            "order": "c6349c2ef7734447a106cd3ac982c23b",
            "timestamp": 1589941315024,
            "datetime": "2020-05-20T02:21:55.024Z",
            "symbol": "IOST/BTC",
            "side": "sell",
            "price": 3.764e-7,
            "amount": 6920,
            "cost": 0.002604688,
            "fee": {"cost": 0.000001823282}
        }

**Comment by kroitor** [comment]
Do you have CCXT updated? Because I'm seeing this from parseTrade (i've added the edits to HitBTC for the feeCurrency specified in markets) with your trade posted above:

```
mbp:ccxt igorkroitor$ node examples/js/cli hitbtc fetchMyTrades --details
hitbtc.fetchMyTrades ()
-------------------------------------------
{         info: {            id:  849899156,
                  clientOrderId: "c6349c2ef7734447a106cd3ac982c23b",
                        orderId:  245637799183,
                         symbol: "IOSTBTC",
                           side: "sell",
                       quantity: "6920",
                          price: "0.0000003764",
                            fee: "0.000001823282",
                      timestamp: "2020-05-20T02:21:55.024Z"          },
            id:   "849899156",
         order:   "c6349c2ef7734447a106cd3ac982c23b",
     timestamp:    1589941315024,
      datetime:   "2020-05-20T02:21:55.024Z",
        symbol:   "IOST/BTC",
          type:    undefined,
          side:   "sell",
  takerOrMaker:    undefined,
         price:    3.764e-7,
        amount:    6920,
          cost:    0.002604688,
           fee: { cost: 0.000001823282, currency: "BTC" }               }
```

↑ The fee currency is there in the most recent version of CCXT. You may have an outdated HitBTC file.

**Comment by npomfret** [comment]
Maybe thanks.
