### ISSUE TITLE
FTX Endpoint POST subaccounts error "Not logged in"

### ISSUE THREAD

**Issue by Fenix135** [ccxt/ccxt#6985]
- OS: Win 10
- Programming Language version: PHP
- CCXT version:  1.28.11

```
<?php

include "ccxt/ccxt.php";

date_default_timezone_set('UTC');

$api_key  = 'XXXXXXX';
$api_secret = 'YYYYYYY';
$exchange = new \ccxt\ftx();
$exchange->apiKey = $api_key;
$exchange->secret = $api_secret;

$param = array ('nickname' =>  'aaa');

echo "<pre>";
var_dump($exchange->private_post_subaccounts($param));
echo "</pre>";

?>```

```
Fatal error:  Uncaught ccxt\ExchangeError: ftx {"error":"Not logged in","success":false}
 in C:\xampp\htdocs\ftx\ccxt\php\ftx.php:1437
Stack trace:
#0 C:\xampp\htdocs\ftx\ccxt\php\base\Exchange.php(1429): ccxt\ftx->handle_errors(401, '', 'https://ftx.com...', 'POST', Array, '{"error":"Not l...', Array, Array, '{"nickname":"aa...')
#1 C:\xampp\htdocs\ftx\ccxt\php\base\Exchange.php(1195): ccxt\Exchange->fetch('https://ftx.com...', 'POST', Array, '{"nickname":"aa...')
#2 C:\xampp\htdocs\ftx\ccxt\php\base\Exchange.php(1199): ccxt\Exchange->fetch2('subaccounts', 'private', 'POST', Array, NULL, NULL)
#3 [internal function]: ccxt\Exchange->request('subaccounts', 'private', 'POST', Array)
#4 C:\xampp\htdocs\ftx\ccxt\php\base\Exchange.php(2428): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\ftx\main.php(20): ccxt\Exchange->__call('private_post_su...', Array)
#6 {main}
  thrown in C:\xampp\htdocs\ftx\ccxt\php\ftx.php on line 1437```

Cuando hago la llamada al endpoint de FTX "POST /subaccounts" me da un error como el que se muestra arriba. Sin embargo si llamo al endpoint "POST /subaccounts/update_name" funciona perfectamente.

**Comment by juandediosar** [comment]
Subaccounts not work. However, subaccounts/update_name it works fine

**Comment by Fenix135** [comment]
Hi, any progress?

**Comment by kroitor** [comment]
@Fenix135

1. update your CCXT to the most recent version
2. enable the rate limiter as documented in the Manual
3. enable verbose mode
4. add the FTX-SUBACCOUNT header

Paste your verbose request/response here:

```PHP
include "ccxt/ccxt.php";

date_default_timezone_set('UTC');

$subaccount = 'aaa';

$exchange = new \ccxt\ftx(array(
    'apiKey' => 'YOUR_API_KEY',
    'secret' => 'YOUR_SECRET',
    'enableRateLimit' => true,
    'headers' => array(
        'FTX-SUBACCOUNT' => $subaccount,   
    ),
));

$exchange->load_markets();

$exchange->verbose = true;

$params = array ('nickname' =>  $subaccount);

echo "<pre>";
var_dump($exchange->private_post_subaccounts($params));
echo "</pre>";
```

↑ Paste your verbose request/response here, plz.

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by kroitor** [comment]
https://blog.ftx.com/blog/api-authentication/#not-logged-in

> Not logged in error
> If you ever encounter a Not logged in error it is most likely a timestamp error. In this case please check your timestamp against our server’s timestamp using this endpoint https://otc.ftx.com/api/time

Let us know if the above does not answer your question. Feel free to reopen it or just ask further questions if any.

**Comment by Fenix135** [comment]
with that code the output is:
`Request: POST https://ftx.com/api/subaccounts [
    "FTX-SUBACCOUNT: aaa",
    "FTX-KEY: p2iL6NVsSdB0QGK7svz4d29ZPvzsBifTBi57ZyjC",
    "FTX-TS: 1590956113965",
    "Content-Type: application\/json",
    "FTX-SIGN: e1122cd1a5df4d4e349feeb78f603176b44e602a14fbce92230eb35b753930b9"
] {"nickname":"aaa"}
Response: POST https://ftx.com/api/subaccounts 401  {
    "date": [
        "Sun, 31 May 2020 20:15:14 GMT"
    ],
    "content-type": [
        "application\/json"
    ],
    "content-length": [
        "47"
    ],
    "set-cookie": [
        "__cfduid=d5a0ddae7361336f4464794308777dd7d1590956114; expires=Tue, 30-Jun-20 20:15:14 GMT; path=\/; domain=.ftx.com; HttpOnly; SameSite=Lax; Secure"
    ],
    "cache-control": [
        "private, max-age=0, no-cache"
    ],
    "account-id": [
        "None"
    ],
    "cf-cache-status": [
        "DYNAMIC"
    ],
    "cf-request-id": [
        "030df8d9b60000d67125999200000001"
    ],
    "expect-ct": [
        "max-age=604800, report-uri=\"https:\/\/report-uri.cloudflare.com\/cdn-cgi\/beacon\/expect-ct\""
    ],
    "strict-transport-security": [
        "max-age=31536000; includeSubDomains; preload"
    ],
    "x-content-type-options": [
        "nosniff"
    ],
    "server": [
        "cloudflare"
    ],
    "cf-ray": [
        "59c35da2be74d671-MAD"
    ],
    "alt-svc": [
        "h3-27=\":443\"; ma=86400"
    ]
} {"error":"No such subaccount","success":false}



Fatal error:  Uncaught ccxt\ExchangeError: ftx {"error":"No such subaccount","success":false}
 in C:\xampp\htdocs\ftx\ccxt\php\ftx.php:1470
Stack trace:
#0 C:\xampp\htdocs\ftx\ccxt\php\base\Exchange.php(1431): ccxt\ftx->handle_errors(401, '', 'https://ftx.com...', 'POST', Array, '{"error":"No su...', Array, Array, '{"nickname":"aa...')
#1 C:\xampp\htdocs\ftx\ccxt\php\base\Exchange.php(1197): ccxt\Exchange->fetch('https://ftx.com...', 'POST', Array, '{"nickname":"aa...')
#2 C:\xampp\htdocs\ftx\ccxt\php\base\Exchange.php(1201): ccxt\Exchange->fetch2('subaccounts', 'private', 'POST', Array, NULL, NULL)
#3 [internal function]: ccxt\Exchange->request('subaccounts', 'private', 'POST', Array)
#4 C:\xampp\htdocs\ftx\ccxt\php\base\Exchange.php(2428): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\ftx\subcuenta.php(24): ccxt\Exchange->__call('private_post_su...', Array)
#6 {main}
  thrown in C:\xampp\htdocs\ftx\ccxt\php\ftx.php on line 1470
`

BUT, with this other code:
`<?php
include "ccxt/ccxt.php";

date_default_timezone_set('UTC');

$subaccount = 'aaa';

$exchange = new \ccxt\ftx(array(
    'apiKey' => 'YOUR_API_KEY',
    'secret' => 'YOUR_SECRET',
    'enableRateLimit' => true,
));

$exchange->load_markets();

$exchange->verbose = true;

$params = array ('nickname' =>  $subaccount);

echo "<pre>";
var_dump($exchange->private_post_subaccounts($params));
echo "</pre>";

?>`

Work!!! The key was:
`'enableRateLimit' => true,`

Thk

**Comment by kroitor** [comment]
@Fenix135 thx for reporting back, appreciate it!

For the future, in general, the rate-limiter is required and it is documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

We recommend to follow the Manual literally to a word.

**Comment by Fenix135** [comment]
It seems that it was not "enableRateLimit", it has been when updating the library.

**Comment by kroitor** [comment]
@Fenix135 that may be the case, however, updating the library is the first step in the troubleshooting sequence that is also documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting, therefore we still recommend to follow the Manual precisely.

**Comment by Gennttii** [comment]
I am having the same error "Not logged in" with main account !

**Comment by kroitor** [comment]
@Gennttii https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by ttodua** [comment]
Update: from now, you can now directly add the parameter in any method (without need to set the headers in exchange initialization properties), like:

`createOrder/FerchBalance( ..., ...,  params:{ "FTX-SUBACCOUNT":"mySubAcc"} ) `   

Note: `FTXUS-SUBACCOUNT` for ftx.us users.
