### ISSUE TITLE
Trying to use method get_option_instruments_summary/okex

### ISSUE THREAD

**Issue by MilicaMedic** [ccxt/ccxt#6988]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: MacOS High Sierra 
- Programming Language version: Python 3.7.3
- CCXT version: ccxt-1.28.13
- Exchange: okex
- Method: get_option_instruments_summary

I'm trying to call an implicit method:

Public- Option Instrument Market Data
Retrieve market data summary of a single instrument.
HTTP Request

GET/api/option/v3/instruments/<underlying>/summary/<instrument_id>

Example Request

GET/api/option/v3/instruments/BTC-USD/summary/BTC-USD-190927-12500-C
Using the following code:
```
json = okex.get_option_instruments_summary({'underlying':'BTC-USD'},{'instrument_id':'BTC-USD-200522-10000-C'}) 
```
But still get the attribute error
```
AttributeError: 'okex' object has no attribute 'get_option_instruments_summary'
```
Thanks

**Comment by kroitor** [comment]
```Python
response = okex.option_get_instruments_underlying_summary({
    'underlying':'BTC-USD'
})
``` 

Let us know if that does not help.

**Comment by kroitor** [comment]
P.S. To see all available methods:

```
import ccxt
print(dir(ccxt.okex()))
```

**Comment by MilicaMedic** [comment]
I needed a method for a specific instrument, this works:
```
response = okex.option_get_instruments_underlying_summary_instrument_id({
    'underlying':'BTC-USD', 'instrument_id':'BTC-USD-200522-10000-C'
})
```
Thank you!

**Comment by kroitor** [comment]
@MilicaMedic thx for the feedback!

**Comment by hfsam** [comment]
> 在提交问题之前，必须先阅读以下内容（阅读链接，然后在提交前删除此消息）：
> 
> [https://github.com/ccxt/ccxt/blob/master/FAQ ](https://github.com/ccxt/ccxt/blob/master/FAQ)
> https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
> 
> 确保您的CCXT本地版本是最新的。通过比较的输出`ccxt.version`与https://github.com/ccxt/ccxt/blob/master/package.json#L3进行检查[](https://github.com/ccxt/ccxt/blob/master/package.json#L3)
> 
> * 操作系统：MacOS High Sierra
> * 编程语言版本：Python 3.7.3
> * CCXT版本：ccxt-1.28.13
> * 交易所：okex
> * 方法：get_option_instruments_summary
> 
> 我试图调用一个隐式方法：
> 
> 公用期权工具市场数据
> 检索单个工具的市场数据摘要。
> HTTP请求
> 
> GET / api / option / v3 / instruments // summary / <instrument_id>
> 
> 示例请求
> 
> GET / api / option / v3 / instruments / BTC-USD / summary / BTC-USD-190927-12500-C
> 使用以下代码：
> 
> ```
> json = okex.get_option_instruments_summary({'underlying':'BTC-USD'},{'instrument_id':'BTC-USD-200522-10000-C'}) 
> ```
> 
> 但是仍然出现属性错误
> 
> ```
> AttributeError: 'okex' object has no attribute 'get_option_instruments_summary'
> ```
> 
> 谢谢
