### ISSUE TITLE
Close Position using Hedge Mode [Binance]

### ISSUE THREAD

**Issue by falihgoz** [ccxt/ccxt#6990]
Hi, I have a problem to close position using binance exchange. Could you please give me an example me how to close position when we are using Hedge Mode on future trading?

- OS: Windows: 10
- Programming Language version: Python 3.8.3
- CCXT version: 1.27.54

**Comment by h-keskin** [comment]
I'm having the same problem. The last api update included a change that could help, as detailed below:

https://binance-docs.github.io/apidocs/futures/en/#change-log

> **2020-05-18**
> New parameter closePosition for endpoint POST /fapi/v1/order:
> If a STOP_MARKET or TAKE_PROFIT_MARKET order with closePosition=true is triggered，all of the current long position( if SELL order) or current short position( if BUY order) will be closed.
> 
> New field closePosition in response to endpoints:
> 
> POST /fapi/v1/order
> POST /fapi/v1/batchOrders
> GET /fapi/v1/order
> DELETE /fapi/v1/order
> DELETE /fapi/v1/batchOrders
> GET /fapi/v1/openOrder
> GET /fapi/v1/openOrders
> GET /fapi/v1/allOrders

**Comment by kroitor** [comment]
@h-keskin yep, but what is the problem exactly? CCXT supports passing all/any params to unified methods as described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

**Comment by h-keskin** [comment]
For example, what should be the query (php) to be written to close all LONG positions in the ETH / USDT pair?

**Comment by kroitor** [comment]
@h-keskin it should look like so, assuming that you have switched to :

```PHP
include 'ccxt.php';
date_default_timezone_set ('UTC');

$exchange = new \ccxt\binance (array (
    'apiKey' => 'YOUR_API_KEY', // ←------------ replace with your keys
    'secret' => 'YOUR_SECRET',
    'enableRateLimit' => true, // as required by the Manual
    // 'verbose' => true, // uncomment for debug output
    'options': array(
        'defaultType' => 'future',
    ),
));

try {

    $symbol = 'ETH/USDT'; // ←--------- replace with your symbol
    $type = YOUR_ORDER_TYPE; // as explained in the API docs
    $side = 'BUY'; // or SELL
    $amount = YOUR_AMOUNT; // if required by the exchange, or null
    $price = YOUR_PRICE; // if required by the exchange, or null
    $params = array(
        'closePosition' => true,
        // other requires params here, if necessary
    );
    $response = $exchange->createOrder ($symbol, $type, $side, $amount, $price, $params);
    print_r($response);

} catch (Exception $e) {

    echo '[Error] ' . $e->getMessage () . "\n";
}
```

Let us know if that does not help.

**Comment by h-keskin** [comment]
This process, which can be done in one command with **Bitmex api**, is currently not possible with **binance futures** api. Or I couldn't find a way.

The **_type_** value for **_closePosition_** should be **_STOP_MARKET_** or **_TAKE_PROFIT_MARKET_**. 

![image](https://user-images.githubusercontent.com/66672103/84198036-9e49fd00-aaab-11ea-8bdd-d10b3833eaa8.png)


For this, it is necessary to specify **_stopPrice_**. 

![image](https://user-images.githubusercontent.com/66672103/84198164-d05b5f00-aaab-11ea-8ff7-0b48a8110b4b.png)


![image](https://user-images.githubusercontent.com/66672103/84198346-14e6fa80-aaac-11ea-9297-9d350b5668a5.png)

As I understand it, closePosition is not used to close all open positions of the specified pair by market order. It has a slightly more complex structure. I want to be able to close all open LONG or SHORT positions in the specified pair (hedge mode). If there is an easy way, I would like to learn.

If we can not do this way, it will be useful to learn the size of a specified pair in an open position. In this way, we can give market order to close open positions.

**Comment by kroitor** [comment]
@h-keskin sorry, i'm not sure I fully understand the question or which specific problem you have, in my previous response i've pasted a snippet of code that does what you want (make sure you have the latest version of CCXT 1.29.58+). You can use it to specify any type of the order as well as the stopPrice, closePosition and any other additional params. Let me know if you have difficulties with, ideally – paste a snippet of your code with verbose request/response as explained here:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by koradiyakaushal** [comment]
@h-keskin while placing exit order with inversed positionSide and side. you can check in below python code to close 1 BTC Buy Position.

```
symbol = 'BTCUSDT'
type = 'market'
side = 'sell'
amount = 1
price = None
params = {
    'positionSide': 'LONG',
    'test': True
}
data = exchange.create_order(symbol, type, side, amount, price=None, params=params)
```
![image](https://user-images.githubusercontent.com/36811899/98275885-30065980-1fbb-11eb-9285-327e56e8d99d.png)

**Comment by interzonez** [comment]
Hi @kroitor 

I'm trying to do the same in Python (perhaps wrong thread should move to Python section?). How can I use the Try statement above in Python. I also want to utilize the 'hedge' mode to account for BUY and SELL open futures positions.

`CCXT version: 1.40.34`

I have already gathered the open positions as you know ;) See below code. My understanding is I can build something like the try statement above in Python close my open position, that full-fills my parameters, with a market order. 

```
exchange.verbose = False
symbols = exchange.symbols
#symbol = [], since = [], limit = [], params = {}
markets = exchange.load_markets()
balance = exchange.fetch_balance()
all_positions = balance['info']['positions']
#current_positions = [position for position in all_positions if float(position['unrealizedProfit']) >= -10 and float(position['unrealizedProfit']) <= -0.01]
#current_positions = [position for position in all_positions if float(position['unrealizedProfit']) <= -0.01]
current_positions = [position for position in all_positions if float(position['unrealizedProfit']) <= -0.01 and float(position['positionAmt']) <= -0.01]
current_amount = [amount for amount in all_positions if float(amount['positionAmt']) <= -0.01]


print(current_positions)
print('=================================================')

for position in current_positions:
    market_id = position['symbol']                             # added this
    market = exchange.markets_by_id[market_id]                 # added this
    symbol = market['symbol']                                  # added this
    print('--------------------------------------------------------------------')
    print('Market id:', market_id, 'symbol:', symbol)
    my_orders = exchange.fetch_open_orders(symbol)
    print(my_orders)
    #print('done')

print('=================================================')

# def order
#
#     symbol = 'symbol'; // ←--------- replace with your symbol
#     type = market; // as explained in the API docs
#     side = 'BOTH'; // or SELL
#     amount = null; // if required by the exchange, or null
#     price = null; // if required by the exchange, or null
#     params = array(
#         'closePosition' => true,
#         // other requires params here, if necessary
#     );
#     $response = $exchange->createOrder ($symbol, $type, $side, $amount, $price, $params);
#     print_r($response);
#
# } catch (Exception $e) {
#
#     echo '[Error] ' . $e->getMessage () . "\n";
# }

```

I recently tried this using this code. But of course there is trouble with the negative orders or decimals.

```
for amount in current_amount:
    amt = amount['positionAmt']
    my_sells = exchange.createMarketBuyOrder(symbol = symbol, amount = amt)
    my_sells
    print(my_sells)
```
Error:

`ccxt.base.errors.BadRequest: binance {"code":-1102,"msg":"Mandatory parameter '-57' was not sent, was empty/null, or malformed."}`

**Comment by interzonez** [comment]
I may have figured it out here: 

```
for amount in current_amount:
    amt = amount['positionAmt']
    my_sells = exchange.createMarketBuyOrder(symbol = symbol, amount = abs(float(amount['positionAmt'])))
    print(my_sells)
```

**Comment by ttodua** [comment]
@kroitor's comment answered the question, also the last comment confirms that user got it working. If anyone has any problem, feel free to open the issue.
