### ISSUE TITLE
How not to output at runtime:“Request: GET ...”

### ISSUE THREAD

**Issue by xkyykx** [ccxt/ccxt#6991]
How not to output at runtime: “ Request: GET ... ”. 
like this： ‘’ Request: GET https://api.bibox.pro/v1/mdata?cmd=ticker&pair=4EOS_USDT {'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} None“  .  Because i don't need it.

**Comment by kroitor** [comment]
@xkyykx how do you initialize the exchange instance?

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by kroitor** [comment]
In short – you should disable the verbose mode. Let us know if it does not help. If you're still having difficulties with it, feel free to reopen this issue or just ask further questions, if any.

Always paste your source code here using [GitHub markdown](https://guides.github.com/features/mastering-markdown/) for readability and padding, surround your code and/or output with triple backticks (&#096;&#096;&#096;), like shown below:

    &#096;&#096;&#096;Python
    put your code here – something we can copypaste and launch
    don't paste one line of code, paste your full short complete code snippet to reproduce it
    it has to be short but complete including exchange instantiation, but without your keys of course
    &#096;&#096;&#096;

    &#096;&#096;&#096;
    your output here
    &#096;&#096;&#096;

**Comment by xkyykx** [comment]
The problem is solved, I commented out a line of code: bibox.verbose = True
Sorry because the work failed to debug and reply in time
Thank you very much for your guidance.
