### ISSUE TITLE
How to use this.hmac for signature generation?

### ISSUE THREAD

**Issue by ericoacguedes** [ccxt/ccxt#6993]
Hi,

I'm trying to write the sign method to an exchange, yet without success.
The problem happens in the signature generation.

In javascript: 

function generateSignature(key, secret, nonce) {
   var message = nonce + key; 
   var hash = CryptoJS.HmacSHA256(message, secret);
   var hashInBase64 = CryptoJS.enc.Base64.stringify(hash);
   return hashInBase64;
}

it works, but I'm in doubt how to write it with ccxt syntax. 
Based on the signature of other exchanges(I read binance, kraken, etc), I'm trying hash and hmac:

         } else {
             this.checkRequiredCredentials ();
             const nonce = this.nonce ().toString ();
             url += path;
             const message = nonce + this.apiKey;
             const hash = this.hash (this.encode (message), 'sha256', 'base64');
             const signature = this.hmac (hash, this.encode (this.secret), 'sha256', 'base64');
             headers = {
                 'Content-Type': 'application/x-www-form-urlencoded',
                 'key': this.apiKey,
                 'nonce': nonce,
                 'signature': signature,
             };

I'm getting: ccxt.base.errors.ExchangeNotAvailable: POST ...... 400 Bad Request {"error":true,"data":{"message":"Invalid signature. Verify key and signature."}}

Can anyone help me to translate the above generateSignature to the ccxt syntax?

Thank you.

Erico.

**Comment by kroitor** [comment]
Non-CCXT:

```JavaScript
function generateSignature(key, secret, nonce) {
   var message = nonce + key; 
   var hash = CryptoJS.HmacSHA256(message, secret);
   var hashInBase64 = CryptoJS.enc.Base64.stringify(hash);
   return hashInBase64;
}
```

↓

CCXT:

```JavaScript
    const message = nonce + this.apiKey;
    const signature = this.hmac (this.encode (message), this.encode (this.secret), 'sha256', 'base64');
    headers = {
        'Content-Type': 'application/x-www-form-urlencoded',
        'key': this.apiKey,
        'nonce': nonce,
        'signature': signature,
    };
```

Let me know if that does not help.

**Comment by kroitor** [comment]
@ericoacguedes in other words, you don't need to `hash()` it in CCXT, just do `hmac`. It would be great if you report back whether it solves the issue for you or not.

**Comment by kroitor** [comment]
I hope the above helped. Closing this for now, feel free to reopen it or just ask further questions if any.

**Comment by ericoacguedes** [comment]
Yes. It works. Thank you.
