### ISSUE TITLE
Binance watchOrders / watchBalance not working

### ISSUE THREAD

**Issue by dsbaars** [ccxt/ccxt#6995]
I try to use `watchOrders()` and `watchBalance()` but both with node.js and in the browser, after connecting to the websocket for private methods, there does not seem to be any communication. When I change below method from `watchBalance()` to `fetchBalance()` it does work fine.

- OS: macOS 10.15.4
- Programming Language version: NodeJS v12.16.3
- CCXT version: pro 0.2.13

```JavaScript
'use strict';

const ccxtpro = require('.');

(async () => {

    const exchange = new ccxtpro.binance({ enableRateLimit: true })

    exchange.apiKey = 'x';
    exchange.secret = 'x';


    (async () => {

        while (true) {
            try {
                const balance = await exchange.watchBalance()
                console.log(balance)
            } catch (e) {
                console.log(e)
            }
        }

    })()
})()

```

**Comment by kroitor** [comment]
> there does not seem to be any communication.

The `watch*` methods only return a value when an update from the exchange comes in. When your balance changes – you will see a `watchBalance` response. This is how WebSocket feeds work – you get the updates in real-time, not the most recent historical state.

Try launching a `watchBalance()` loop and change your balance by placing an order or by depositing/withdrawing/transferring (to change your balance) – you will see the update returned from `watchBalance()`.

Let us know if that does not answer your question.

**Comment by dsbaars** [comment]
Thanks, this explains a lot although this behaviour is different from the other exchanges I used with WebSockets.
After subscribing with Kraken for example the first message is the current state, after that you will get updates. I think this is the same with BitMEX as well. 
I'll try to solve this by doing a single fetch call first.

**Comment by kroitor** [comment]
@dsbaars yep, Binance does not send-in a snapshot of balance upon connecting, while some other exchanges like Kraken, BitMEX do. Let me know if you have further issues or difficulties with it. Thx!

**Comment by kroitor** [comment]
P.S. We will look into adding the balance snapshot to Binance, however, last time we've checked – there was no possibility to synchronize the RESTful balance response with the WS updates, because their RESTful endpoint for balance does not return a nonce value that could be used for synchronization. So, it's up to the user to synchronize it, depending on the users' current state.
