### ISSUE TITLE
Past Balances For Bitfinex

### ISSUE THREAD

**Issue by nagabrahmam-mantha** [ccxt/ccxt#6998]
Hi,

Just a general question. For Bitfinex, is it possible to get the balances at a particular time in the past. For example, is there any code which I can use to get the balance for December 20th 2019, for example? I was looking at this from their API:

https://docs.bitfinex.com/reference#rest-auth-ledgers

Is this implemented in the CCXT? Can I use "fetchLedger"? I see that the Bitfinex returns false for "has fetchLedger". Is there any other way I can fetch the previous balances?

OS: Windows 10
CCXT version: 1.27.88

Thanks!

**Comment by kroitor** [comment]
> For Bitfinex, is it possible to get the balances at a particular time in the past. For example, is there any code which I can use to get the balance for December 20th 2019, for example?

In general, no. The exchanges will not return historical balance snapshots.

However, as you noted, there's a `fetchLedger` method which you can use to restore your balance history. The problem is that this method has not been unified for Bitfinex yet. We will add it shortly.

In the meantime, you can call that method directly using the [implicit API endpoints](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods) from CCXT as described in the Manual.

```Python
exchange.private_post_auth_r_ledgers_hist({
    # your params here according to https://docs.bitfinex.com/reference#rest-auth-ledgers
    # 'param': 'VALUE',
})

exchange.load_markets()
currency = exchange.currency('ETH')
exchange.private_post_auth_r_ledgers_currency_hist({
    'currency': currency['id'],
    # your params here according to https://docs.bitfinex.com/reference#rest-auth-ledgers
    # 'param': 'VALUE',
})
```

Let us know if that does not answer the question. Feel free to reopen it or just ask further questions if any.

**Comment by nagabrahmam-mantha** [comment]
I tested it and its working for now! Thanks again!!!!

**Comment by r4zZ-90** [comment]
This isn't working for me unfortunately and `dir(ccxt.hitbtc())` shows no `private_post_auth_r_ledgers_currency_hist` as option...

I simply want to pull the ledgers table from Bitfinex report. Shouldn't that be easily possible?

**Comment by kroitor** [comment]
@r4zZ-90 

> This isn't working for me unfortunately and `dir(ccxt.hitbtc())`

↑ You can't get a list of Bitfinex endpoints from HitBTC – those are two different exchanges, mind the typos in your code.

**Comment by r4zZ-90** [comment]
I just copy pasted it from the github manual. In my code I actually used bitfinex instead of hitbtc.

Did you check `dir(ccxt.bitfinex())`? Cause it seems you didn't.

**Comment by kroitor** [comment]
@r4zZ-90 

> Did you check dir(ccxt.bitfinex())? 

Yes, I did. There's two versions of Bitfinex API (v1 and v2):

```
mbp:python igorkroitor$ python3
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> from pprint import pprint
>>> pprint(dir(ccxt.bitfinex2()))
```

**Comment by kroitor** [comment]
@r4zZ-90 to get a list of all exchanges:

```
pprint(ccxt.exchanges)
```

**Comment by r4zZ-90** [comment]
Ah! 
Great, this one worked. Thanks!
