### ISSUE TITLE
Question - CCXT Websockets

### ISSUE THREAD

**Issue by Corfucinas** [ccxt/ccxt#6999]
I been reading at the documentation at [CCXT Pro](https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual) 📖  to consider upgrading to pro to include the use of websockets in a project I've been working on. 

My question is if "fetchTickers" -> "watchTickers" returns the same object in Python (Dict) ❓ . With the following keys
- Symbol
- Timestamp
- Datetime
- High
- Low
- Bid
- BidVolume
- Ask
- AskVolume
- Vwap
- Opan
- Close
- Last
- PreviousClose
- Change
- Average
- Percentage
- BaseVolume
- QuoteVolume
- Info

**Comment by kroitor** [comment]
> My question is if "fetchTickers" -> "watchTickers" returns the same object in Python (Dict)?

Yep, the formats of the returned structures are unified and correspond to CCXT (the same structures). Hope it helps.

**Comment by kroitor** [comment]
One more thing, the `watchTickers` method is not implemented yet, however, `watchTicker` is. Both methods should return the unified ticker structure by design. We will add `watchTickers` where applicable.

**Comment by Corfucinas** [comment]
> P.S. One more thing, the `watchTickers` method is not implemented yet, however, `watchTicker` is. Both methods should return the unified ticker structures by design. Most of the exchanges require a symbol for subscribing to a ticker, though, therefore `watchTickers` may be missing in the exchange WebSocket API. We will add `watchTickers` where it is available.

Do you have a list of exchanges that offer a subscription to `all` tickers? I have a list of about ~34 exchanges where you may get a `dict` offering the keys mentioned above. 🥇 

<details><summary> Exchanges with `FetchTickers` method </summary><br>
- acx
- bequant
- bigone
- binance
- bitfinex
- bitkk
- zb
- bitmart
- bittrex
- bitz
- bleutrade
- braziliex 
- bw
- cex
- coinex 
- crex24 
- exmo
- exx
- gateio
- hitbtc
- idex
- kraken
- kucoin
- kuna
- lakebtc
- liquid
- livecoin
- luno
- oceanex
- okcoin
- okex
- poliniex
- rightbtc
- southexchange
- therock
</br>
</details>

I'm developing on more than one of them and I want to avoid having to backtrack or refactor major parts of my code if I decide to include websockets `without` having the need to specify the `symbol`.

**Comment by kroitor** [comment]
> Do you have a list of exchanges that offer a subscription to all tickers?

At this time the `watchTickers` is not available in CCXT Pro, yet you can subscribe to multiple tickers at once, one by one, with `watchTicker`. The only difference is that with `watchTicker` it will subscribe to each ticker separately, but you can still watch many of them or even all of them. Though, it will still require a `symbol`.

However, if you're asking about the exchanges that support subscribing to multiple tickers at once – some of them do, like Kraken, Poloniex and a few others. I don't have a full list at hand right now, but we will do our best to add `watchTickers` (where available form the exchange) as soon as possible. We do understand that you don't want to specify the `symbol`, because it may require changes in the code on the user side, so, we will try to add  `watchTickers` to make it a smooth transition in the nearest future.

**Comment by mirkogd** [comment]
hi i am starting now to use ccxt pro and i would like to run watchTrades by subscribing many symbols. I have a long array of symbols and inside a loop I execute "await exchange.watchTrades (symbol, since, limit)" but it works correctly for the first 3 or 4 elements of the array but then the program stops and does not proceed without however report errors.
Can you give an example of how I should go about subscribing to watchTrades for a long list of symbols?
i am currently testing with binance.

**Comment by kroitor** [comment]
@mirkogd please, check the examples here: https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro/

**Comment by kroitor** [comment]
@mirkogd here: https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/many-exchanges-many-symbols-watch-trades.py

**Comment by mirkogd** [comment]
thank you,
Is it normal that it can take a second or two to subscribe to a symbol? to subscribe for 100 symbols my code takes more than 2 minutes.

**Comment by Corfucinas** [comment]
Man @kroitor you're fast, thanks for keeping this great library

Any interest in expanding it to Rust?

**Comment by mirkogd** [comment]
For the moment I'm not interesed in Rust, I'm actually starting now with javascript
Thanks again

**Comment by kroitor** [comment]
@Corfucinas we'd love to! Porting it to compiled langs requires some extreme pedantry from the devs to do it right, we're making progress towards that. All thoughts, suggestions, code contributions, PRs – everything is very welcome!

**Comment by Corfucinas** [comment]
> @Corfucinas we'd love to! Porting it to compiled langs requires some extreme pedantry from the devs to do it right, we're making progress towards that. All thoughts, suggestions, code contributions, PRs – everything is very welcome!

I can definitely help here and there, I ported one of my python packages to rust as an exercise [check it out](https://crates.io/crates/crypto-candlesticks-rust).

If there's any official discussion you can add me in

**Comment by dimoff66** [comment]
> > Do you have a list of exchanges that offer a subscription to all tickers?
> 
> At this time the `watchTickers` is not available in CCXT Pro, yet you can subscribe to multiple tickers at once, one by one, with `watchTicker`. The only difference is that with `watchTicker` it will subscribe to each ticker separately, but you can still watch many of them or even all of them. Though, it will still require a `symbol`.
> 
> However, if you're asking about the exchanges that support subscribing to multiple tickers at once – some of them do, like Kraken, Poloniex and a few others. I don't have a full list at hand right now, but we will do our best to add `watchTickers` (where available form the exchange) as soon as possible. We do understand that you don't want to specify the `symbol`, because it may require changes in the code on the user side, so, we will try to add `watchTickers` to make it a smooth transition in the nearest future.

Is it possible to use watchTicker in the throttling mode? I see an example with watchOrderBook, it has orderbooks property to read changes from time to time, but can't find the same for tickers

**Comment by kroitor** [comment]
@dimoff66 

> Is it possible to use watchTicker in the throttling mode? I see an example with watchOrderBook, it has orderbooks property to read changes from time to time, but can't find the same for tickers

Yes, see `exchange.tickers`.

**Comment by dimoff66** [comment]
> @dimoff66
> 
> > Is it possible to use watchTicker in the throttling mode? I see an example with watchOrderBook, it has orderbooks property to read changes from time to time, but can't find the same for tickers
> 
> Yes, see `exchange.tickers`.

Strange, missing. Is it some new feature? May be i should update library? I downloaded it this april

**Comment by kroitor** [comment]
@dimoff66 yes, plz make sure your versions of CCXT and CCXT Pro are up to date.
