### ISSUE TITLE
Question - regarding create_market_sell_order()

### ISSUE THREAD

**Issue by Corfucinas** [ccxt/ccxt#7002]
- Language: Python 

My question is regarding handling exceptions using the `create_market_sell_order()` function.
Let's suppose I have a `Queue` of orders ready to be sent. This `Queue` is structured in a **specific sequence that must be executed in the order they we're `enqueued`**.

**two scenarios**

##### 1) Order get's submitted successfully. ✔️ 
- Do I get a response that I can parse from the exchange? 
- Would I need to make a separate call to confirm the order was executed?

##### 2) Order get's rejected by any reason. ❌ 
- I could in theory amend the order depending on the response to make it executable. 
- Do I also get a response from `create_market_sell_order()` that I can catch in order to be able to handle this?
- Would I need to handle that in a separate call to the exchange?

The logic of the execution is that once a _signal_  has been found  **while True:**  , it will take an _action_ to submit the order to the exchange. I need to make sure that the sequence knows how to handle an exception and does not proceeds to execute the following order on the **Queue** IF the 1st sequence submission is not successful.

**Comment by Corfucinas** [comment]
I kinda figured this one out a while ago, using Retry and just catch the status code on the CCXT base

**Comment by kroitor** [comment]
@Corfucinas thx for reporting back!

**Comment by Corfucinas** [comment]
This is useful when you want to try once again with some sort of modification to the request (ie. wait a certain amount of time before an API call or modify an order amount etc).

https://pypi.org/project/retry/

**Comment by Corfucinas** [comment]
Sidenote @kroitor 

I made a pypi package for downloading candlestick data and saving it into .csv and .sqlite for analysis

https://github.com/Corfucinas/crypto-candlesticks
