### ISSUE TITLE
How change Leverage and Margin Mode(cross, isolated) in Binance futures

### ISSUE THREAD

**Issue by asaltrader** [ccxt/ccxt#7004]
Hi
I want to change Leverage and Margin Mode(cross, isolated) from code in Binance futures
how can i do that ?

**Comment by kroitor** [comment]
Please, see the answers here:

- https://github.com/ccxt/ccxt/issues/6357#issuecomment-572828671
- https://github.com/ccxt/ccxt/issues/6969
- https://github.com/ccxt/ccxt/search?q=binance+isolated&type=Issues ← most often, if you have a question, someone else might have already asked it, the search is your friend and it will save you a ton of time, really )

**Comment by yongguncodework** [comment]
In Phemex, how do I change the leverage type? Is it not supported?
It seems like only isolated is the only option. I wonder if I can do cross for phemex.
Plus, I see the example for contract limit order, but the "amount =5" I wonder what is the unit for this?
Nowdays, they have like either USD or Cont option. Can you please specify how to find the amount I want?
For example, if I want cross leverage 100 with 1000 cont (which is like 10 dollar worth). How do I code this through ccxt?
