### ISSUE TITLE
error when trying to place an order with decimal on ftx.

### ISSUE THREAD

**Issue by Thjdid** [ccxt/ccxt#7010]
Hi guys, 
I have no problem placing orders with integers, but when I try posting with a size like 0.01 , I get this error message from the ccxt file decimal_to_precision.py
Any idea what could be wrong ? 

Thanks a lot

File "/usr/local/lib/python3.7/site-packages/ccxt/ftx.py", line 873, in create_order
    priceToPrecision = float(self.price_to_precision(symbol, price))
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 1225, in price_to_precision
    return self.decimal_to_precision(price, ROUND, self.markets[symbol]['precision']['price'], self.precisionMode)
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/decimal_to_precision.py", line 55, in decimal_to_precision
    dec = decimal.Decimal(str(n))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

**Comment by kroitor** [comment]
Hi! 

We need some more info from you to be able to resolve this issue, as explained here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

- What's your version of CCXT?
- Which symbol is it?
- Can you paste the code to reproduce it (with the actual values) ?

**Comment by kroitor** [comment]
Please, use [github markdown](https://guides.github.com/features/mastering-markdown/) for readability when pasting code or text. Don't confuse triple backticks (&#096;&#096;&#096;) with a single backtick (&#096;). Wrap your code or text with triple backticks as shown below (this is also shown in any issue template upon opening it – you should really follow what's written in the template):

&#096;&#096;&#096;Python
YOUR_CODE_HERE
&#096;&#096;&#096;

&#096;&#096;&#096;
YOUR OUTPUT HERE
&#096;&#096;&#096;

**Comment by Thjdid** [comment]
Sorry I posted too fast ... 
it was actually coming from a problem in my own code, I was not specifying the price well. 
Got it for post format for next time. 
Thank you for your time and efficiency Kroitor as usual :)

**Comment by kroitor** [comment]
@Thjdid thx for reporting back! )
