### ISSUE TITLE
lakeBTC sellOrder throws  "error": "Failed to submit order: invalid symbol"

### ISSUE THREAD

**Issue by Temesgen123** [ccxt/ccxt#7019]
Hello,

When i try to send a post request using the sellorder method on LakeBTC echange i get the following error message:
 "error": "Failed to submit order: invalid symbol"
params="100,0.001,btcusd"

OS: Windows 10
Programming Language version: C#
Exchange: LakeBTC
Method:sellorder

Thanks in advance!

**Comment by kroitor** [comment]
Hi! In your programming language you've specified C#, however, the original CCXT does not support C# yet. Can you clarify which version is it?

**Comment by Temesgen123** [comment]
Sorry, i am not using CCXT but i am using lakeBTC API i am asking because i saw that CCXT supports lakeBTC exchange.

**Comment by kroitor** [comment]
@Temesgen123 unfortunately, we can't really support you beyond CCXT on the code that we're not responsible for – you might want to forward this question to the author of the code that you're using. In this case i'd recommend to send it to the exchange tech support itself. Hope for your understanding, we can't physically fix all the code in the world that is made by other people. 

We would be happy to help on CCXT, however, we need the following info: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help. 

Closing this for now, if you don't mind. Feel free to reopen it or just ask further questions if you have more.
