### ISSUE TITLE
DSX rolls back to its previous API version

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#7022]
Unbelievable...

> Following the March upgrade, we’ve been receiving a lot of feedback from our customers to restore the previous design and Exchange functionality. After lengthy discussions (held via video conferencing of course) we’ve come to the conclusion that we agree. Your opinion and comfort is, after all, always our top priority.
> Hence, we are restoring the design and Exchange functionality you’re used to. Along with that, we have to return to our trading platform while keeping all newly added cryptoassets. Multiple order types will be restored in the coming months. We’ll be also bringing back our iOS mobile app where you can monitor your portfolio and exchange your crypto.
> Here’s what will happen:
> On May 27 at 7.00 am GMT we’ll stop the exchange. All active orders will be cancelled, API trading will be stopped as well.
> We’ll start the upgrading process that should take us 3 hours to make sure everything works fine.
> On May 27 at 10.00 am GMT we’ll get back online. You’ll be able to access your account.
> You will receive an email with the link to confirm your account. (Don’t forget to check the Spam folder if you don’t see our email in your Inbox.)
> You’ll be assigned new deposit addresses. Please use these to receive your crypto in a timely manner. If for some reason you cannot change it, please let us know. We’ll fix it for you.
> Our API will be changed back to the old one. Documentation can be found here so you can prepare in advance.
> That’s it! We apologise for any inconvenience this may cause. If you have any questions or concerns, please let us know. We’ll be happy to help you.

The docs: https://dsxglobal.com/developers/publicApiV3?__s=fuh3cog91ozfswqv0gbk

**Comment by kroitor** [comment]
We don't have an _"old exchange"_ label for this kind of events ))) We can revert to our previous implementation, however, it takes time and I don't see why they would only give their users 24 hours to react to such breaking changes. They could just keep both APIs.

**Comment by npomfret** [comment]
I agree.  They didn't give any warning when they switch the last one off.  At least now they gave 1 day.  I don't think they appreciate the impact this has on their users

**Comment by kroitor** [comment]
@npomfret i think the DSX team is still working on it, the API is not accessible yet.

**Comment by npomfret** [comment]
Yeah, I contacted them about it.  Sounds like it's not gone very well.  They hope to be functional tomorrow.

**Comment by npomfret** [comment]
@kroitor i just got an email from them saying the downgrade was finished.  Except they call it an upgrade.
