### ISSUE TITLE
[exmo] parseTransaction error

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#7025]
```
TypeError: Cannot read property 'deposit' of undefined
    at exmo.parseTransaction (node_modules/ccxt/js/exmo.js:1504:70)
```

`{"dt":"1590465521","type":"deposit","curr":"LTC","status":"transferred","provider":"CashBack","amount":"0.00075277","account":"20990732","txid":""}`

This type of transfer is a deposit but it's from the exchange (cash back)

**Comment by npomfret** [comment]
Ah, I think I need to call fetchFundingFees

**Comment by kroitor** [comment]
But anyway, it should not crash, though... regardless of the funding fees...
i will get to it shortly, thx for reporting!

**Comment by npomfret** [comment]
My bad. I cache the internals (markets and currencies) so that I don't have to go to the exchange every time I need a new instance of ccxt.  But I wasn't caching the funding fees.

Do you know of any other fields (other than markets, currencies, fundingFees) that get populated as a result of calling loadMarkets on any exchange?

**Comment by kroitor** [comment]
> Do you know of any other fields (other than markets, currencies, fundingFees) that get populated as a result of calling loadMarkets on any exchange?

Sometimes you also need to `loadAccounts()`, but that is usually handled inside CCXT. I don't think we have other dirty structures in the codebase atm. Tbh, we would prefer to not have them at all, but the exchanges' APIs rarily allow to load everything dynamically.

**Comment by npomfret** [comment]
I don't need private data, just the public stuff for getting market data in this case
