### ISSUE TITLE
CCXT poloniex - fetchClosedOrders always give empty array responce.

### ISSUE THREAD

**Issue by storyofcoder** [ccxt/ccxt#7028]
I am using ccxt library with latest version  in js language 

in poloniex - fetchClosedOrder always respond with empty array, because in fetchClosedOrder order ccxt use 

 async fetchClosedOrders (symbol = undefined, since = undefined, limit = undefined, params = {}) {
        const orders = await this.fetchOrders (symbol, since, limit, params);
        return this.filterOrdersByStatus (orders, 'closed');
    }

and in fetchOrders ccxt call API  -- this.privatePostReturnOpenOrders

it always return open order that's why during filter we receive only empty array.

kindly update it.

**Comment by kroitor** [comment]
Hi! 

Please, read this:

- https://github.com/ccxt/ccxt/wiki/Manual#orders-cache
- https://github.com/ccxt/ccxt/issues/6227#issuecomment-562598831
- https://github.com/ccxt/ccxt/issues/2275
- https://github.com/ccxt/ccxt/pull/102

Let us know if that does not answer your question.
