### ISSUE TITLE
How to obtain historical data on expired contract on FTX MOVE-2019Q4?

### ISSUE THREAD

**Issue by arnaudcisse44** [ccxt/ccxt#7029]
Hi, I am using MAC and planning to get historical data of FTX MOVE expired contracts.

I am using python.

`cftx = ccxt.ftx({"apiKey":api_key,"secret":api_secret})
markets=cftx.load_markets()
cftx.fetchOHLCV('BTC-MOVE-2019Q4','1h',since=window_beginning,limit=window_length,params={})`
I get the error message : `ftx does not have market symbol BTC-MOVE-2019Q4` (which makes sense because if I run `cftx.symbol`, i cannot see BTC-MOVE-2019Q4.

Though I know it should be possible to retrieve this data, maybe fetchOHLCV is not the correct method ?

Many thanks

**Comment by kroitor** [comment]
> Though I know it should be possible to retrieve this data

Can you elaborate a bit on why you think it should be possible? 
The exchange API does not serve the data for that market in this case.

**Comment by kroitor** [comment]
Here's how you can retrieve the OHLCV for the delisted/expired FTX contracts, though:

```Python
import ccxt
from pprint import pprint
exchange = ccxt.ftx({'enableRateLimit': True})
since = exchange.parse8601('2019-10-01T00:00:00Z')
params = {'market_name': 'BTC-MOVE-2019Q4'}
limit = None
# specify any existing symbol here ↓ (it does not matter, because it is overrided in params)
ohlcv = exchange.fetch_ohlcv('BTC-MOVE-2020Q4', '1h', since, limit, params)
pprint(ohlcv)
```

Let us know if that does not help.

**Comment by arnaudcisse44** [comment]
Hi Igor, yes that's perfect ! Many thanks !!
