### ISSUE TITLE
Gateio trades all V4 version APIs，Support futures and leveraged trading!

### ISSUE THREAD

**Issue by yazhoushi** [ccxt/ccxt#7030]
Can CCXT be added to the gateio V4 version of the API?

**Comment by kroitor** [comment]
We will do our best to add that functionality to Gateio API implementation asap, more about it here: https://github.com/ccxt/ccxt/issues/6697. Let us know if that does not answer your question.

**Comment by yazhoushi** [comment]
The V4 version of gateio also supports spot api! Now ccxt supports the spot V2 version of gateio, can it also support V4, and the V4 version supports the spot API more comprehensively!

**Comment by kroitor** [comment]
@yazhoushi yes, we will get there asap.

**Comment by yazhoushi** [comment]
Ok! Thanks, and look forward to realizing it soon!
