### ISSUE TITLE
Why can't I download total data from BITSTAMP?

### ISSUE THREAD

**Issue by Dope-K** [ccxt/ccxt#7031]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: WIN10
- Programming Language version: python 3.7.4
- CCXT version: recent

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
import ccxt
from datetime import datetime
symbol = 'BTC/USD'
timeframe = '1h'
since = datetime(2011,1,1,0)
limit = datetime(2020,5,1,0)

origin = datetime(1970,1,1,0)
since_origin = (since - origin)
limit_origin = (limit - origin)
since_timestamp = since_origin.days*(24*60*60) - (9*60*60)
limit_timestamp = limit_origin.days*(24*60*60) - (9*60*60)

bitstamp = ccxt.bitstamp()
ohlcv = bitstamp.fetch_ohlcv(symbol, timeframe, since_timestamp, limit_timestamp)
print(ohlcv)

```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
[[1590663600000, 9236.36, 9288.11, 9236.35, 9265.92, 288.3060260299999], [1590667200000, 9265.92, 9430.0, 9250.84, 9395.57, 1108.6885849599955]]

Process finished with exit code 0

```

I want to download OHLCV data from bitstamp for specific period. 
However, ccxt shows only recent OHLCV data(such as 1 or 2 hours) different with other trading market websites
How can I fix this problem?

**Comment by kroitor** [comment]
This question has been answered here: 

- https://github.com/ccxt/ccxt/issues/3178

Please read the entire thread ↑
Let us know if you have further questions after that.
