### ISSUE TITLE
Bitfinex v2 lack period param for funding candles

### ISSUE THREAD

**Issue by Jay54520** [ccxt/ccxt#7032]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: all
- Programming Language version: all
- CCXT version: 1.28.82

`Period` param is required for fetching funding candles in Bitfinex v2 
> Period* string
> Funding period. Only required for funding candles. Enter after the symbol (trade:1m:fUSD:p30/hist).
https://docs.bitfinex.com/reference#rest-public-candles 

For example https://api-pub.bitfinex.com/v2/candles/trade:5m:fUSD:p2/hist

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
