### ISSUE TITLE
Bybit testnet

### ISSUE THREAD

**Issue by wallneradam** [ccxt/ccxt#7034]
- OS: MacOS and Linux
- Programming Language version: Python 3.8
- CCXT version: 1.28.82

According to chat on Bybit telegram:

> You're right our testnet response has changed slightly, but it shouldn't effect any users. BTCUSD hasn't been changed to TESTUSD — rather, we've just added TESTUSD as an additional symbol for testing purposes.

This unfortunately causes error in CCXT, because id is replaced in BTCUSD market to TESTUSD.

I could debug that this occurs in file `ccxt/base/exchange.py` in `set_markets` function on line `self.markets = self.index_by(values, 'symbol')`

**Comment by dotai2012** [comment]
Hi there, can this one be fixed? It keeps showing the error:

bybit {"ret_code":10001,"ret_msg":"params error!","ext_code":"","ext_info":"","result":null,"time_now":"1590904959.283108"}

**Comment by kroitor** [comment]
A workaround for TESTUSD has been added in CCXT version 1.28.92+
