### ISSUE TITLE
historical data from ftx with expired symbols

### ISSUE THREAD

**Issue by r4VP4** [ccxt/ccxt#7037]
- OS: Windows 10
- Programming Language version: Python 3.7.6
- CCXT version: 12.28.84

If i want to get historical data from ftx, i cannot get the data from expired contracts. (e.g. there are move contracts that expire every day), because the symbol is no longer included in the market data. Is there a way to inject old symbols into the market data or bypass this problem in another way?

```
exchange = ccxt.ftx()
result = exchange.fetchOHLCV('BTC-MOVE-0526', timeframe = '1m')
```

```
ccxt.base.errors.BadSymbol: ftx does not have market symbol BTC-MOVE-0526
```

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/7029
