### ISSUE TITLE
CCXTPRO - generators for websockets

### ISSUE THREAD

**Issue by Corfucinas** [ccxt/ccxt#7038]
`language: python`

Hi @kroitor 
So I've been going about implementing the usage of WS from CCXTPRO on my codebase. What I was wondering....is it possible to generate a whole list of connections of websockets using a list comprehension?

For example, Kucoin allows to load 444 markets.  In pseudocode something like
`for tickers in ccxt.kucoin().load_markets():
        await exchange.watchTicker(tickers)`

Now, I'm not that familiar with the use of WS, it would be quite helpful to undestand if I can generate the WS or I would have to manually code 444 of them 😭

**Comment by kroitor** [comment]
Hi! Have you looked into examples? They show exactly what you're asking about:

- https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/many-exchanges-many-streams.py
- https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/one-exchange-many-streams.py
- https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/many-exchanges.py

Let us know if that does not answer your question.

**Comment by Corfucinas** [comment]
@kroitor 
The classic `missed opening every folder bug`. Thanks a lot! Sent you a tip with Brave Rewards.
I'll look into it immediately.

**Comment by Corfucinas** [comment]
Damn, missed the `asyncio.gather(*` syntax...usually I multithread, asyncio caught me off guard.
Specially with the new syntax that changed from 3.6 to 3.8 from
`asyncio.get_event_loop().run_until_complete(main())`
to
`asyncio.run(main())`

**Comment by kroitor** [comment]
> Sent you a tip with Brave Rewards.

Thanks, appreciate that! Unfortunately, I can't receive it because Brave requires too much personal info. If you wish to support the dev team, please check here: https://github.com/ccxt/ccxt#support-developer-team

**Comment by Corfucinas** [comment]
Will do 👓

**Comment by Corfucinas** [comment]
Hi @kroitor 

I looked at the examples (thanks a lot for them). I have a question regarding `one-exchange-many-streams.py` example (mostly due to lack of sharpness in the asyncio methods). 

When I call `exchange.fetch_tickers()` method, I get a Dict in Python with a len of 444 _(in the case of Kucoin, this is the len)_. Using the example syntax, the function `async def loop(exchange, symbol):` will generate a single object Dict comprise of a len of 20 for each **individual pair**.

Is it possible to return a `single` object comprised of the entire `exchange.watch_ticker()`? Similar to the structure of `exchange.fetch_tickers()`? This is crucial for my code since I use a generator to iterate on the entire array comprised of total len and Yield from it for data processing. 

A simple example
======
```
def  function(tickers: dict) -> Generator
    for ticker in tickers.items():
    ---------
    ---------
    ---------
    yield (something)

def main() -> None:
     all_data = ccxt.exchange().fetch_tickers()
     function(all_data)
```

This works fine, since the argument `tickers` is comprised of a Dict of all `tickers` available for the exchange. However, using `orderbook = await exchange.watch_ticker(symbol)` I would only get a single pair.  I tried to workaround this (using simply a list.append()) or various `yield` expressions, but I can't managed to get the entire array of `orderbook` for processing at once.

Any ideas how that can be archive?
🥇  Really appreciated 🥇

**Comment by kroitor** [comment]
@Corfucinas you want to look into async-generators in Python. I will upload an example for that soon.

**Comment by Corfucinas** [comment]
@kroitor 

Kindly tag me!

**Comment by Corfucinas** [comment]
@kroitor 

Looking forward!

**Comment by Corfucinas** [comment]
@kroitor 

Did you managed to include the example you mentioned? 💯

**Comment by kroitor** [comment]
@Corfucinas pardon for the delay, will add it as soon as I can and will let you know.

**Comment by Corfucinas** [comment]
@kroitor Any updates? 😄

**Comment by kroitor** [comment]
@Corfucinas pardon for the delay, i'll upload the examples asap.

**Comment by Corfucinas** [comment]
@kroitor 

Sorry to bother man, I'm kinda waiting for the async generators of websockets in order to get the same object as fetch_tickers()...I paid for ccxt-pro with that intent.

I appreciate your work and contribution...do you want me to open another issue in order for you to keep track? Just wanting to close this and continue coding 😄

**Comment by kroitor** [comment]
@Corfucinas yes, plz open a new one, I'll get to it within 24hrs and will provide the snippet you've requested. Thx for your patience!

**Comment by kroitor** [comment]
@Corfucinas actually, no need to open a new issue for it. I'll post the example anyway. However, practically all exchanges have a limit on the number of subscriptions, and not all of the have a method for subscribing to all tickers at once. KuCoin in particular has a method for watching all tickers. However, not all exchanges have it. So, here there question to you is what you prefer:

1. up to N specific pairs/tickers with individual subscriptions which is more universal across the exchanges
2. all pairs/tickers with a single subscription which is more exchange-specific

Do you prefer (1) or (2)?

**Comment by Corfucinas** [comment]
Hi @kroitor , sorry for the delay, I was busy these past few days.

I would need option #2, since my current code needs to parse an object containing a list of all tickers info (bid/ask is fine)

**Comment by kroitor** [comment]
@Corfucinas please, check this example, let us know if it does not help.

- https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/many-exchanges-many-different-streams.py

```Python
# -*- coding: utf-8 -*-

import ccxtpro
from asyncio import gather, get_event_loop


async def symbol_loop(exchange, method, symbol):
    print('Starting', exchange.id, method, symbol)
    while True:
        try:
            response = await getattr(exchange, method)(symbol)
            now = exchange.milliseconds()
            iso8601 = exchange.iso8601(now)
            if method == 'watchOrderBook':
                print(iso8601, exchange.id, method, symbol, response['asks'][0], response['bids'][0])
            elif method == 'watchTicker':
                print(iso8601, exchange.id, method, symbol, response['high'], response['low'], response['bid'], response['ask'])
            elif method == 'watchTrades':
                print(iso8601, exchange.id, method, symbol, len(response), 'trades')

        except Exception as e:
            print(str(e))
            # raise e  # uncomment to break all loops in case of an error in any one of them
            break  # you can break just this one loop if it fails


async def method_loop(exchange, method, symbols):
    print('Starting', exchange.id, method, symbols)
    loops = [symbol_loop(exchange, method, symbol) for symbol in symbols]
    await gather(*loops)


async def exchange_loop(asyncio_loop, exchange_id, methods):
    print('Starting', exchange_id, methods)
    exchange = getattr(ccxtpro, exchange_id)({
        'enableRateLimit': True,
        'asyncio_loop': asyncio_loop,
    })
    loops = [method_loop(exchange, method, symbols) for method, symbols in methods.items()]
    await gather(*loops)
    await exchange.close()


async def main(asyncio_loop):
    exchanges = {
        'okex': {
            'watchOrderBook': ['BTC/USDT', 'ETH/BTC', 'ETH/USDT'],
            'watchTicker': ['BTC/USDT'],
        },
        'binance': {
            'watchOrderBook': ['BTC/USDT', 'ETH/BTC'],
            'watchTrades': [ 'ETH/BTC' ],
        },
    }
    loops = [exchange_loop(asyncio_loop, exchange_id, methods) for exchange_id, methods in exchanges.items()]
    await gather(*loops)


if __name__ == '__main__':
    asyncio_loop = get_event_loop()
    asyncio_loop.run_until_complete(main(asyncio_loop))

```

**Comment by Corfucinas** [comment]
@kroitor 

Will try tomorrow! Thanks a lot, good memory
