### ISSUE TITLE
Set my headers?

### ISSUE THREAD

**Issue by anotherfriend** [ccxt/ccxt#7039]
Good day! I want to set my own **headers for working** with the exchange using this library in php. How can I do this?

**Comment by kroitor** [comment]
Hi! You can do that using the `$exchange→headers` property as documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

```PHP
        // instantiate the exchange by id
        $id = 'binance';
        $exchange = '\\ccxt\\' . $id;
        $exchange = new $exchange (array (
            'headers' => array(
                'YOUR_HEADER' => 'YOUR_VALUE',
            ),
        ));
```

You can also set the headers later after initialization – using the `$exchange->headers =` syntax.
Let us know if that does not answer your question.
