### ISSUE TITLE
Binance Futures Error -4061 "Order's position side does not match user's setting"

### ISSUE THREAD

**Issue by azharuniverse** [ccxt/ccxt#7040]
All the trades via api using ccxt is having this issue **for selected accounts only**.
Using same trade configuration 

```
ExchangeError binance {"code":-4061,"msg":"Order's position side does not match user's setting."}
```

**Its a critical issue. Please help with this.**

- Exchange - Binance Futures
- OS: Ubuntu
- Programming Language version: NODE - v8.11.2
- CCXT version: ^1.27.8

**Comment by kroitor** [comment]
Please, follow https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting precisely

1. Do you have the same issue with the most recent version?
2. Can you provide your verbose request/response and the code to reproduce it? https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by kroitor** [comment]
https://github.com/jaggedsoft/node-binance-api/issues/411

↑ Let us know if that does not answer your question.

**Comment by azharuniverse** [comment]
I have forwarded this instruction to my user to disable hedge mode and check. Will keep posted here.

**Comment by kroitor** [comment]
@azharuniverse thank you! Don't hesitate if anything.

**Comment by azharuniverse** [comment]
This solution worked. Thanks

**Comment by Daanish283** [comment]
@kroitor  please solve my code below, i am stuck since 2 days now...
https://stackoverflow.com/questions/72684256/not-able-to-place-a-hedge-order-on-binance-using-ccxt

**Comment by kroitor** [comment]
@Daanish283 i've posted a reply here: https://stackoverflow.com/a/72705491/5055465

**Comment by Daanish283** [comment]
@kroitor please help me with this, i am not able to move ahead without solving this, my hedge order would just never execute, i am not able to get help from anywhere
https://stackoverflow.com/questions/72684256/not-able-to-place-a-hedge-order-on-binance-using-ccxt

                symbol = 'BTC/USDT'
                
                exchange.set_position_mode(hedged=True, symbol=symbol)
                
                typee = 'market'  # or 'market', other types aren't unified yet
                side1 = 'buy'
                side2 = 'sell'
                amount = 0.1# your amount
                marginMode = 'cross'
                hedged: True
                #price = 0.21  # your price
                # overrides
                params = {
                    #'hedged': True,
                    #'stopPrice': ,# your stop price
                }  
                margin_mode = exchange.setMarginMode(marginMode, symbol, params)
                buy_market_order = exchange.create_order(symbol, typee, side1, amount, params) #INCLUDE PRICE IF NEEDED
                sell_market_order = exchange.create_order(symbol, typee, side2, amount, params)
                print(sell_market_order)

the above is my code and below is the error i get

                 binance {"code":-4059,"msg":"No need to change position side."}

**Comment by Daanish283** [comment]
@kroitor I tried all the possibile combinations and everything else to remove the error, but i still end up with errors like this

https://stackoverflow.com/questions/72684256/not-able-to-place-a-hedge-order-on-binance-using-ccxt

**Comment by Daanish283** [comment]
@kroitor I can't even find anyone over the internet having the same error as me
                  binance {"code":-4059,"msg":"No need to change position side."}
https://stackoverflow.com/questions/72684256/not-able-to-place-a-hedge-order-on-binance-using-ccxt

**Comment by p-i-** [comment]
@Daanish283 You should just trap that error, I think, and bulldoze over it.
```
    try:
        :
    except ccxt.errors.MarginModeAlreadySet as e:
        pass
```

**Comment by SeanQuant** [comment]
I find something helpful in <https://dev.binance.vision/t/error-orders-position-side-does-not-match-users-setting/5970>.

When `hedged=True`, you need to manully set positionSide, which should be LONG when buy or SHORT when sell.

```
order = exchange.create_market_buy_order(symbol=symbol, amount=10, params={'positionSide': 'LONG'})
````
@Daanish283
