### ISSUE TITLE
NaN timestamp when creating order on Binance Futures Testnet

### ISSUE THREAD

**Issue by davidchieregato** [ccxt/ccxt#7042]
- OS: Windows 10
- Programming Language version: NodeJS
- CCXT version: 1.28.85

When I create an order on Binance Futures Testnet the timestamp of the request is NaN.
```
this.exchange = new ccxt.binance ({ 
            'apiKey': this.apikey,
            'secret': this.secret,
            'timeout': 30000,
            'enableRateLimit': true,
            'verbose': true,
            'urls': {
                'api': {
                    'fapiPublic': 'https://testnet.binancefuture.com/fapi/v1', 
                    'fapiPrivate': 'https://testnet.binancefuture.com/fapi/v1',
                }
            }
        })

this.exchange.createOrder('BTC/USDT', 'limit', 'sell', 0.015,10000)
```

```
fetch:
 binance POST https://testnet.binancefuture.com/fapi/v1/order
Request:
 {
  'X-MBX-APIKEY': 'xxxxxxx',
  'Content-Type': 'application/x-www-form-urlencoded'
}
 timestamp=NaN&symbol=BTCUSDT&type=LIMIT&side=SELL&quantity=0.015&price=10000&signature=xxxxxxx

{"code":-1102,"msg":"Mandatory parameter 'timestamp' was not sent, was empty/null, or malformed."}
```

**Comment by kroitor** [comment]
Please, try this snippet (change for your api keys) and post your verbose here again please.

```JavaScript
const ccxt = require ('ccxt');

const exchange = new ccxt.binance ({
    'timeout': 30000,
    'enableRateLimit': true,
    'verbose': true,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'urls': {
        'api': {
            'fapiPublic': 'https://testnet.binancefuture.com/fapi/v1',
            'fapiPrivate': 'https://testnet.binancefuture.com/fapi/v1',
        }
    }
})

;

(async () => {

    const order = await exchange.createOrder('BTC/USDT', 'limit', 'sell', 0.015, 10000)

}) ()
```

↑ I just tested it on my side, and it works for me, though, this isn't a correct way to set the testnet, but the timestamp in the request is ok.

Note, that this code does not use any other or "external" things in it, it's a pure complete snippet (no `this.exchange`, `this.exchange.createOrder` in it). 

In this specific snippet I've removed all referenced to other objects (like `this.`) that might have some additional logic and might interfere and break the code. Unfortunately, you haven't pasted all of the code or a complete snippet – so, it's hard to tell from your snippet if something else breaks it or not.

If a pure version works, and the timestamp is ok – that means your logic that you haven't pasted is breaking something somewhere. For example, it may override the `.milliseconds()` or the `.nonce()` methods accidentally somewhere else outside of the part that you've pasted here.

So, I suggest to try this pure version first to rule out other code.

**Comment by kroitor** [comment]
The correct way to set the sandbox is like so:

```JavaScript
const ccxt = require ('ccxt');

const exchange = new ccxt.binance ({
    'enableRateLimit': true,
    'verbose': true,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'options': { 'defaultType': 'future' }, // ←--- switch to futures
});

exchange.setSandboxMode (); // set testnet URLs

(async () => {

    const order = await exchange.createOrder('BTC/USDT', 'limit', 'sell', 0.015, 10000)
    console.log (order)

}) ()
```

Let us know if the above does not answer your question. Feel free to reopen it or just ask further questions, if any.
