### ISSUE TITLE
How to fetchTrades for a specific date?

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#7043]
Hello, 

How to correctly fetch trades for the specific period? For example for 1 Jan 2020 (whole day)
fetchTrades has parameter only one parameter since

**Comment by kroitor** [comment]
Hi! Have you read the pagination section from the Manual? https://github.com/ccxt/ccxt/wiki/Manual#pagination
It explains, how that could be done (when supported by the underlying exchange).

**Comment by kroitor** [comment]
Let us know if the above does not answer your question. Feel free to reopen it or ask further questions, if any.
