### ISSUE TITLE
How to transfer crypto between exchanges?

### ISSUE THREAD

**Issue by yordanoweb** [ccxt/ccxt#7044]
I transfered BTC from my **bitfinex** to my **binance**. After that, when I check balance at binance, I never saw an increasement of BTC. php code is below. **is this the right way to transfer crypto between exchanges?**

```php

require_once __DIR__ . '/exchanges.php';
require_once __DIR__ . '/../vendor/ccxt/ccxt.php';

$pipe = function() {
    $args = func_get_args();
    return function($value) use ($args) {
        return array_reduce($args, function($new_value, $func) {
            return $func($new_value);
        }, $value);
    };
};

$prepare_transfer = function($data) {
    $from_name = current(array_keys($data['from']));
    $from_class = "\\ccxt\\$from_name";
    $from_instance = new $from_class(array(
        'apiKey' => $data['from'][$from_name]['apikey'],
        'secret' => $data['from'][$from_name]['secret'],
    ));
    $to_name = current(array_keys($data['to']));
    return array(
        'exchange' => $from_instance,
        'wallet' => $data['to'][$to_name]['wallet'],
        'amount' => $data['amount'],
    );
};

$dump = function($data) {
    if (is_string($data)) {
        echo $data;
    } else var_dump($data);
};

$make_transfer = function($data) {
    $exchange = $data['exchange'];
    $response = $exchange->withdraw('BTC', $data['amount'], $data['wallet']);
    return json_encode($response, JSON_PRETTY_PRINT);
};

$transfer = $pipe(
    $prepare_transfer,
    $make_transfer,
    $dump
);

$transfer(array(
    'from' => array('bitfinex' => $exchanges['bitfinex']),
    'to'   => array('binance'  => $exchanges['binance']),
    'amount' => 0.00050,
));
```

**Comment by kroitor** [comment]
The exchanges do not have a method for transferring between the exchanges. Instead, an exchange can have a method for withdrawing (sending) money from one exchange to another (as you did in your code). Withdrawals take time until the transaction is confirmed. Apart from that, the exchanges have different types of accounts (funding, spot, margin, futures, etc), and you usually get the notification from the exchange upon receiving the deposit. 

Unfortunately, in your code you don't show how you initialize the exchanges. If you can paste it (without your keys of course) – that could help resolve the issue. In general, we need your **verbose request+response and a complete code snippet**, as explained here:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

If you send money from bitfinex to binance, and binance did not receive it – go to bitfinex website and open your withdrawal history to check the status of your withdrawal. You can also get the history of your withdrawals from bitfinex with the `fetch_withdrawals()` method.

Another aspect is that you're not using the rate-limiter when you :

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

You should also add exception handling around critical methods:

- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

Let us know if the above does not help or does not answer your question. Feel free to reopen it if needed or just ask further questions, if any.

**Comment by yordanoweb** [comment]
i bypassed sensitive information in the code like **apikeys** and **secrets**. here is the transfer response:
```json
[
  {
    "info": {
      "wallettype": "exchange",
      "method": "bitcoin",
      "address": "********************************",
      "invoice": null,
      "payment_id": null,
      "amount": "0.001",
      "status": "success",
      "message": "Your withdrawal request has been successfully submitted.",
      "withdrawal_id": 9999999999999,
      "fees": "0.0004"
    },
    "id": "14040667"
  },
  {
    "info": {
      "wallettype": "exchange",
      "method": "bitcoin",
      "address": "*************************",
      "invoice": null,
      "payment_id": null,
      "amount": "0.0005",
      "status": "success",
      "message": "Your withdrawal request has been successfully submitted.",
      "withdrawal_id": 666666666666666,
      "fees": "0.0004"
    },
    "id": "8888888888888"
  }
]
```
so, the trasfer was executed...

**Comment by kroitor** [comment]
@yordanoweb it says, that the withdrawal has been successfully submitted (not executed). When you go to bitfinex's website it should show up in your list of withdrawals. What do you see there?

**Comment by kroitor** [comment]
If Bitfinex has processed it and has sent it out (that may take time) – you should be able to see it on the blockchain under the destination address: https://blockchair.com/bitcoin/address/YOUR_BINANCE_DESTINATION_ADDRESS_HERE

**Comment by yordanoweb** [comment]
i think i found it. i could not see it at **blockchair.com**. then i called the **fetchTransactions** method of **bitfinex** exchange instance, and i received this:
```json
{ info:
     { id: 999999999999999,
       currency: 'BTC',
       method: 'BITCOIN',
       type: 'WITHDRAWAL',
       amount: '0.0005',
       description: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, expired',
       address: 'xxxxxxxxxxxxxxxxxxxxxxxxx',
       status: 'CANCELED',
       timestamp: '1590753143.0',
       timestamp_created: '1590709868.0',
       txid: null,
       fee: '-0.0004' },
    id: '14040724',
    txid: undefined,
    timestamp: 1590709868000,
    datetime: '2020-05-28T23:51:08.000Z',
    address: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    tag: undefined,
    type: 'withdrawal',
    amount: 0.0005,
    currency: 'BTC',
    status: 'canceled',
    updated: 1590753143000,
    fee: { currency: 'BTC', cost: 0.0004, rate: undefined }
}
```
maybe it was cancelled by the missing of rate parameter. please, could you explain me more about it? thanks anyway.

**Comment by kroitor** [comment]
@yordanoweb It is explained here: https://support.bitfinex.com/hc/en-us/articles/115003284089-Why-was-my-withdrawal-canceled-

**Comment by kroitor** [comment]
@yordanoweb let us know if the above does not help.

**Comment by albertord84** [comment]
Hi I'am following your debate cause I'm missing it from CCXT API (transference between Exchanges). Whether we success automate transference we could include it to the CCXT API @kroitor what do you think about it?  

@yordanoweb I did send you a request to work together on it if you want, I work with PHP to but I can help with e Python or NodeJs example!

**Comment by kroitor** [comment]
@albertord84 the CCXT already has the necessary functionality to check the status of the withdrawal after submitting it. We highly recommend to read the entire Manual from top to bottom (`fetchTransactions`, `fetchDeposits`, `fetchWithdrawals`) to avoid duplication of work.

- https://github.com/ccxt/ccxt/wiki/Manual#funding-your-account

If you'd like to take part in the development of the lib, please, make sure to read the entire [CONTRIBUTING](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md) doc. We appreciate all help. Thx!
