### ISSUE TITLE
Proxy use: binance Timestamp for this request is outside of the recvWindow.

### ISSUE THREAD

**Issue by viniciussvl** [ccxt/ccxt#7045]
Hello,
I synchronized my server's time using NTP, did some tests and managed to use the Binance API normally. I went to use a proxy (https://luminati.io) from the United States to connect to Binance and it even works, but every now and then it looks like that famous "recvWindow" error. What can I do to correct this problem that only happens using a proxy?

- OS: Ubuntu 18.04
- Programming Language version: Javascript
- CCXT version: 1.18.968

```
this.binance = new ccxt.binance({
            // options: {
            //   'adjustForTimeDifference': true,
            //   // 'recvWindow': 10000000, // not really needed
            // },
            apiKey: params.api_key,
            secret: params.api_secret,
            timeout: 60000,
            agent: proxy,
        })
```

```
binance Timestamp for this request is outside of the recvWindow.
```

**Comment by kroitor** [comment]
Hi!

Do you use the rate-limiter? It is required, but you don't seem to be using it.

If you have the rate limiter enabled, try uncommenting `'adjustForTimeDifference': true,`. If that doesn't help either, set a value of `recvWindow` between 10000 and 60000 (max). 

If that doesn't help – it may be a delay lag introduced by the extra-hop (luminati.io). In that case you want to forward this question to the proxy service.

Let us know if the above does not answer your question.

**Comment by kroitor** [comment]
P.S. make sure that the NTP is configured to synchronize the time frequently enough (every 10-15 minutes). A one-time synchronization won't help.

**Comment by viniciussvl** [comment]
Hello,
I'm not using the rate limiter, do you recommend using it? What about the proxy region, should I choose a datacenter near the API https://api.binance.com or does that not interfere much with the delay?

Yes NTP is often synchronized.

**Comment by kroitor** [comment]
> I'm not using the rate limiter, do you recommend using it?

The CCXT Manual states clearly, that you must use at least some rate-limiting, either the built-in rate limiter or your custom rate-limiting mechanism, if you have it. It's not a recommendation, but a requirement. https://github.com/ccxt/ccxt/wiki/Manual#rate-limit I recommend to always follow the Manual literally to a word.

> choose a datacenter near the API https://api.binance.com or does that not interfere much with the delay?

Being close to the exchange can help mitigate the problem, but it depends, for example, if your source system is close to Binance, but the proxy isn't.

**Comment by kroitor** [comment]
P.P.S. I also recommend to update your CCXT version to the most recent one. Your version is too old.

**Comment by kroitor** [comment]
P.P.P.S. If you run into any problem – always go through the troubleshooting sequence step-by-step precisely: https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by viniciussvl** [comment]
Okay, I will make these changes and update the library thanks!
