### ISSUE TITLE
I don't seem to have found a way to just cancel bitmex XBTUSD

### ISSUE THREAD

**Issue by fengok** [ccxt/ccxt#7048]

**Comment by fengok** [comment]
Only cancel all orders for XBTUSD

**Comment by kroitor** [comment]
@fengok sorry, can you elaborate?

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

- You can not cancel the exchange (bitmex) – that is impossible by definition.
- You can not cancel exchange markets like BTC/USD, ETH/USD – that is also physically impossible.

- You can cancel a single order by id or by clientOrderId with the unified `cancelOrder` method, as documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#canceling-orders. I recommend to always read the docs at least once from top to bottom – that will save you a ton of time, really.
- You can call BitMEX endpoints directly using the [implicit API methods](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods)

If you can explain what you want to do in terms explained in the Manual – we would be happy to help. Unfortunately, it's very hard to understand what exactly you mean.

**Comment by fengok** [comment]
There are some problems with my description, I want to cancel the order of XBTUSD at one time, I have done it now, thank you for your reply
