### ISSUE TITLE
Binance watchOrders not handling order updates for Futures

### ISSUE THREAD

**Issue by dsbaars** [ccxt/ccxt#7050]
The watchOrder messages from Binance Futures are not processed by the handleOrder method. When I turn on verbose logging I do see the message coming in, but the format looks a bit different from the normal Binance updates so that could cause this issue.

- OS: macOS 10.15.4
- Programming Language version: JavaScript / NodeJS v12.17.0
- CCXT version: 1.29.3 / pro 0.2.42

```js
'use strict';
const ccxtpro = require('ccxt.pro');

(async () => {

    const exchange = new ccxtpro.binance({ 
        enableRateLimit: true,
        defaultType: 'future',
        verbose: true,
        options: { 
            defaultType: 'future' ,
            defaultLimitOrderType: 'future'
        }
    })

    exchange.apiKey = 'x';
    exchange.secret = 'x';

    exchange.urls['api'] = exchange.urls['test'];
    exchange.urls['api']['ws'] = exchange.urls['test']['ws'];

    //exchange.setSandboxMode();
    
    (async () => {

        while (true) {
            try {
                const balance = await exchange.watchOrders()
                console.log(balance)
            } catch (e) {
                console.log(e)
            }
        }

    })()
})()
```

**Comment by kroitor** [comment]
The futures mode is not supported yet, but will be added shortly: https://github.com/ccxt/ccxt/issues/6697

**Comment by kroitor** [comment]
If you can paste your verbose output – that would help speed up the process:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by dsbaars** [comment]
Here you go:
````
2020-06-01T09:41:28.788Z connecting to wss://stream.binancefuture.com/ws/<snap>
2020-06-01T09:41:29.841Z onUpgrade
2020-06-01T09:41:29.843Z onOpen
2020-06-01T09:42:00.104Z onPong
2020-06-01T09:42:30.105Z onPong
2020-06-01T09:42:41.584Z onMessage {
  e: 'ORDER_TRADE_UPDATE',
  T: 1591004561441,
  E: 1591004561442,
  o: {
    s: 'BTCUSDT',
    c: '31JPCbgC6M1SvZLUWN1Xvc',
    S: 'BUY',
    o: 'LIMIT',
    f: 'GTC',
    q: '1',
    p: '1',
    ap: '0',
    sp: '0',
    x: 'NEW',
    X: 'NEW',
    i: 2421412836,
    l: '0',
    z: '0',
    L: '0',
    T: 1591004561441,
    t: 0,
    b: '1',
    a: '0',
    m: false,
    R: false,
    wt: 'CONTRACT_PRICE',
    ot: 'LIMIT',
    ps: 'BOTH',
    cp: false
  }
}
````

**Comment by kroitor** [comment]
@dsbaars thx, appreciate your involvement! Will get back to you with a working watchOrders+futures asap.

**Comment by qgpmarkets** [comment]
@kroitor 
Is `watchOrders` supposed to be working with Binance futures?  I'm experiencing a similar issue with the latest ccxt.pro.

**Comment by kroitor** [comment]
@qgpmarkets it supports just the spot orders for now, but we are going to add the support for swaps and futures in a few days, the work on it is going on here as well: https://github.com/kroitor/ccxt.pro/pull/58

**Comment by kroitor** [comment]
We have implemented Binance's future/delivery private APIs (watchBalance, watchOrders, watchMyTrades), please upgrade to CCXT Pro 0.5.48+ and let us know if you have issues with it. Thank you!
