### ISSUE TITLE
is dry run available in ccxt ( like freqtrade)?

### ISSUE THREAD

**Issue by AronWater** [ccxt/ccxt#7051]
After reading the documentation, I wonder if it has any function like dry run? 

- OS: win10
- Programming Language version:python

**Comment by cj4c0b1** [comment]
Hi @AronWater 
As far as I can remember there is no explicit dry_run, but you can simulate it in some ways like :
1 - run without api keys. you can test public parts of the code.
2 - inform optional parameter to cause erros when sending orders, like wrong order parameters.

In my case I implemented the dryrun option in my strategies, like you have on freqtrade.
I believe that this is the recommended approach

**Comment by kroitor** [comment]
@AronWater CCXT does support testnet/sandbox environments (for the exchanges having that functionality). You can switch to the exchange's testnet like so:

```Python
import ccxt
exchange = ccxt.okex({
    'enableRateLimit': True,
})
exchange.set_sandbox_mode(True)
```

↑ Let us know if that does not answer your question. Feel free to reopen it, or just ask further questions if any.
