### ISSUE TITLE
Binance positionSide endpoint

### ISSUE THREAD

**Issue by rs-g** [ccxt/ccxt#7053]
Hi guys,

Is this endpoint from Binance futures implemented?
"New endpoint GET /fapi/v1/positionSide/dual to get current position mode."

I can only see the post one "fapiPrivate_post_positionSide/dual"

**Comment by kroitor** [comment]
Hi! Thx for reporting it, added in CCXT 1.29.7 and the new automatic build will arrive in 15 minutes.
