### ISSUE TITLE
Using 'params' from 'fetch_ticker' as condition for follow action - Binance

### ISSUE THREAD

**Issue by eugjr** [ccxt/ccxt#7055]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 7 64bits
- Programming Language version: Python 3.8
- CCXT version: 1.28.82

Hello guys, congrats on this great work. I'm new on ccxt, and starting to think on my first bot to use on binance futures.

I've been able to properly print the data from fetch_ticker('BTC/USDT') command. I need to store the params readed from this command as variables. I.E., store on every script run, for BTC/USDT pair, the value of the params 'vwap' and  'bidVolume' on variables btcusdt_vwap and btcusdt_bidVolume to be used on the conditions for placing orders.

It would be the same for fetch_balance params. How can I pick only "unrealizedProfit" exclusively from "symbol" 'BTCUSDT'?

Thank you

**Comment by kroitor** [comment]
Hi!

Your questions are less about CCXT and more about using Python in general. I'd recommend to get more practice with it (tutorials, youtube videos, etc).

> I need to store the params readed from this command as variables. I.E., store on every script run, for BTC/USDT pair, the value of the params 'vwap' and 'bidVolume' on variables btcusdt_vwap and btcusdt_bidVolume to be used on the conditions for placing orders.

```Python
import ccxt
exchange = ccxt.binance({
    'enableRateLimit': True,
    'options': { 'defaultType': 'future' },
})

symbol = 'BTC/USDT'

ticker = exchange.fetch_ticker(symbol)
btcusdt_vwap = ticker['vwap']

orderbook = exchange.fetch_order_book(symbol)
btcusdt_bidVolume = orderbook['bids'][0][1]

print(symbol, 'vwap', btcusdt_vwap, 'bidVolume', btcusdt_bidVolume)
```

> It would be the same for fetch_balance params. How can I pick only "unrealizedProfit" exclusively from "symbol" 'BTCUSDT'?

```Python
import ccxt
exchange = ccxt.binance({
    'enableRateLimit': True,
    'options': { 'defaultType': 'future' },
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

symbol = 'BTC/USDT'

exchange.load_markets()

balance = exchange.fetch_balance()
positions = balance['info']['positions']
positions_by_id = exchange.index_by(positions, 'symbol')
market = exchange.market(symbol)
position = exchange.safe_value(positions_by_id, market['id'])
unrealizedProfit = position['unrealizedProfit']
print(symbol, 'unrealizedProfit', unrealizedProfit)
```

Let us know if the above does not answer your questions. Feel free to reopen it or just ask further questions, if any.
