### ISSUE TITLE
[yobit] weird order with no status

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#7057]
I just got this from yobit - I assume from `fetchOrder`.  There is no status field.

    {
                "id": "201186103",
                "fee": {"cost": 0.09124979, "rate": 0.002, "type": "maker", "currency": "WAVES"},
                "cost": 0.005223594163290699,
                "info": {"pair": "waves_btc", "rate": 0.00011449, "type": "buy", "amount": 45.62489443, "order_id": "1400062796052405", "trade_id": "201186103", "timestamp": "1591121482", "is_your_order": 1},
                "side": "buy",
                "type": "limit",
                "order": "1400062796052405",
                "price": 0.00011449,
                "amount": 45.62489443,
                "symbol": "WAVES/BTC",
                "datetime": "2020-06-02T18:11:22.000Z",
                "timestamp": 1591121482000,
                "takerOrMaker": "maker"
            }

**Comment by npomfret** [comment]
Sorry, ignore me!

**Comment by kroitor** [comment]
@npomfret yep, that's a trade, but anyways, i appreciate your feedback, don't hesitate if anything
