### ISSUE TITLE
gateio fetch_orders() can only get 50 orders for one trading pair

### ISSUE THREAD

**Issue by yazhoushi** [ccxt/ccxt#7061]
Gateio exchange fetch_orders() can only get 50 orders for one trading pair, and fetch_orders() can get pending orders of other trading pairs! Obtaining 50 pending orders is the V2 version of the exchange interface. This is the case. V4 can obtain all pending orders of trading pairs, and will not obtain trading orders of other trading pairs!

**Comment by yazhoushi** [comment]
下面这个地址是官方接口最新的V4版本接口文档，在官网是找不到的，我是找客服，客服给的！也许开发没有及时的替换官网的接口文档https://www.gatecn.io/docs/apiv4/zh_CN/index.html#gate-api-v4希望对你有用！

**Comment by yazhoushi** [comment]
fetch_open_orders ()can only get 50 orders for one trading pair too。

**Comment by samgermain** [comment]
We have updated gateio to use this [v4 endpoint](https://www.gate.io/docs/developers/apiv4/en/#list-all-open-orders)

![](https://i.imgur.com/ih0ORMv.png)

The correct response should be returned when [this PR](https://github.com/ccxt/ccxt/pull/13227) gets merged

I believe this should fix the issue

**Comment by ttodua** [comment]
as noted by @samgermain , gateio has been updated to V4.
if you face other issues in v4, let us know.
