### ISSUE TITLE
Any way to use credit card API to purchase bitcoin in ccxt?

### ISSUE THREAD

**Issue by benlvovsky** [ccxt/ccxt#7063]
Do you have API to use credit card processing to buy bitcoin?
I am writing online service for my client to charge credit cards (currently I use Stripe), put into his bank account, transfer to binance (maybe other exchange is better?), then buy bitcoin via exchange, then send this bitcoin to specified wallet.
Can I simplify it with some credit API to buy via credit card?

**Comment by kroitor** [comment]
We don't have a unified processing for card payments yet, CCXT is focused on crypto for the most part. However, many exchanges allow you to deposit fiat directly, and do the conversion in-place, not involving a 3rd-party card payment processor like Stripe. Adding a unified fiat/cc processing is not our topmost priority right now, but we will look into the options and will let you know. Sending and receiving fiat globally in a unified way is generally harder in legal terms.

**Comment by benlvovsky** [comment]
Any suggestions which exchange provides CC API out of box?

**Comment by kroitor** [comment]
@benlvovsky i think most of the exchanges certified in CCXT allow you to receive fiat/cc deposits, except the DEXes. I'd suggest to try the biggest and the most trusted ones, like Binance for example.
