### ISSUE TITLE
Withdrawal without approval

### ISSUE THREAD

**Issue by yordanoweb** [ccxt/ccxt#7070]
Does any one knows which are the exchanges that does not require approval to withdraw funds to a wallet address? Because I have not much money to buy enough BTC to test one by one in the exchanges list of the API. Any clue about this?

Thanks anyway

**Comment by kroitor** [comment]
@yordanoweb actually, a lot of the exchanges allow that, the only additional thing they may require – is supplying the 2fa code in the params overrides for the `withdraw` method. The main point of the automation with the API is to avoid the need for manual action. Most of the certified exchanges will allow that, and the majority of the integrated exchanges will work as well. I don't have the exact list for you right away, unfortunately.
