### ISSUE TITLE
Binance started throwing 'Not all sent parameters were read'

### ISSUE THREAD

**Issue by radiant-alex** [ccxt/ccxt#7082]
- OS: macOS Catalina
- Programming Language version: TypeScript/JavaScript node v13
- CCXT version: 1.29.50

```
import * as ccxtpro from 'ccxt.pro';
const b = new ccxtpro.binance();
b.enableRateLimit = true;
await b.createOrder('ETH/USDT’, ‘limit’, ‘sell’, 5.3, 244.94, {
  "type": "LIMIT”,
  "timeInForce": "GTC",
  "reduceOnly": true,
});

// Body of request: timestamp=XXXX&recvWindow=5000&symbol=ETHUSDT&type=LIMIT&side=SELL&quantity=5.3&price=244.94&timeInForce=GTC&reduceOnly=true&signature=XXXX
```

Throws error
```
{"code":-1104,"msg":"Not all sent parameters were read; read '9' parameter(s) but was sent '10'."}
```

Started happening just today.
Same for another pair, just 'Market' type

```
arguments for create order: 'EOS/USDT' , 'market', 'buy', 409.9, null, {
  "type": "STOP_MARKET",
  "stopPrice": 2.772,
  "quantity": 409.9,
  "closePosition": true
}

-> {"code":-1104,"msg":"Not all sent parameters were read; read '8' parameter(s) but was sent '9'."}
```

**Comment by kroitor** [comment]
@radiant-alex can you please paste your full verbose request/response for the failing call? (you can strip the values, but don't strip the params and other relevant info).

**Comment by kroitor** [comment]
```
'ETH/USDT’, ‘limit’, ‘sell’,
↑        ↑  ↑     ↑  ↑    ↑ weird unpaired quotes, should be ' everywhere, not ’ nor ‘
```

↑ That makes me think that the actual code is different.

**Comment by kroitor** [comment]
Nevermind, I've reproduced it on my side. Tbh, it looks like a bug on the exchange side to me.

**Comment by radiant-alex** [comment]
Yeah, same here. Seems an issue on exchange. The body I sent above is full - GET call.

**Comment by kroitor** [comment]
@radiant-alex looks like you should not send reduceOnly with spot markets.

**Comment by kroitor** [comment]
@radiant-alex in both cases you're sending unexpected params to spot markets (reduceOnly, closePosition) let us know if that does not answer your question.

**Comment by kroitor** [comment]
P.S.

@radiant-alex you might want to switch to futures to use those params.

**Comment by kroitor** [comment]
```JavaScript
import * as ccxtpro from 'ccxt.pro';
const b = new ccxtpro.binance({
    'enableRateLimit': true,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'options': {                 // options
        'defaultType': 'future', // the defaultType inside options
    },
});
await b.createOrder('ETH/USDT’, ‘limit’, ‘sell’, 5.3, 244.94, {
  "type": "LIMIT”,
  "timeInForce": "GTC",
  "reduceOnly": true,
});
```

Hope it helps. Let us know if not.

**Comment by radiant-alex** [comment]
Ah, seems during refactoring I removed “future” type!  Thanks a lot for your time! Issue is resolved now!

**Comment by radiant-alex** [comment]
I am sorry, but I must re-open this issue.

There is code in Binance.js

```
 async createOrder (symbol, type, side, amount, price = undefined, params = {}) {
        await this.loadMarkets ();
        const market = this.market (symbol);
        const defaultType = this.safeString2 (this.options, 'createOrder', 'defaultType', market['type']);
        const orderType = this.safeString (params, 'type', defaultType);
        const clientOrderId = this.safeString2 (params, 'newClientOrderId', 'clientOrderId');
        params = this.omit (params, [ 'type', 'newClientOrderId', 'clientOrderId' ]);
        let method = 'privatePostOrder';
        if (orderType === 'future') {
            method = 'fapiPrivatePostOrder';
        } else if (orderType === 'margin') {
            method = 'sapiPostMarginOrder';
        }
...
```
In particular: 

`const orderType = this.safeString (params, 'type', defaultType);`

Then IF below

` if (orderType === 'future') {`

I started having FAPI calls redirected to API for orders creation because of these lines.
Seems it must check the defaultType, instead of orderType...

**Comment by kroitor** [comment]
@radiant-alex can you please paste the code to reproduce it?

**Comment by radiant-alex** [comment]
> ```js
> import * as ccxtpro from 'ccxt.pro';
> const b = new ccxtpro.binance({
>     'enableRateLimit': true,
>     'apiKey': 'YOUR_API_KEY',
>     'secret': 'YOUR_SECRET',
>     'options': {                 // options
>         'defaultType': 'future', // the defaultType inside options
>     },
> });
> await b.createOrder('ETH/USDT', 'limit', 'sell', 5.3, 244.94, {
>   "type": "LIMIT",
>   "timeInForce": "GTC",
>   "reduceOnly": true,
> });
> ```

This fails for me on createOrder - it calls spot API. When I change at Binance.js, the lines in my previous post: remove orderType and use defaultType, all works fine .

**Comment by kroitor** [comment]
@radiant-alex 

Yes, you should remove the `'type': 'LIMIT'` override – it is already passed in the second argument to `createOrder ('ETH/USDT', 'limit'` ← here

```JavaScript
import * as ccxtpro from 'ccxt.pro';
const b = new ccxtpro.binance({
    'enableRateLimit': true,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'options': {                 // options
        'defaultType': 'future', // the defaultType inside options
    },
});
await b.createOrder('ETH/USDT', 'limit', 'sell', 5.3, 244.94, {
  // "type": "LIMIT", // ← remove this param, since the order type is passed in the second argument
  "timeInForce": "GTC",
  "reduceOnly": true,
});
```

↑ Let us know if that does not answer your question.

**Comment by radiant-alex** [comment]
I need to send 'STOP_MARKET' order type :( with it, it fails. Though for Limit orders it works if I removed the 'type' from params

**Comment by kroitor** [comment]
> I need to send 'STOP_MARKET' order type :( with it, it fails. 

That's a different story then, I mean, I was writing the above for limit orders. For stop_market orders you just pass `stop_market` or `STOP_MARKET` in the order type:

```JavaScript
const type = 'stop_market' // or STOP_MARKET
const price = undefined // market orders have no price
await b.createOrder ('ETH/USDT', type, 'sell', 5.3, price, {
    'stopPrice': YOUR_STOP_PRICE_HERE, // required by stop_market type
})
```

↑ That should work with the most recent version of CCXT / CCXT Pro:

- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L1273

Let me know if that does not help. If it fails – please, paste your full verbose request/response:

```JavaScript
await b.loadMarkets()
b.verbose = true
const type = 'stop_market' // or STOP_MARKET
const price = undefined // market orders have no price
await b.createOrder ('ETH/USDT', type, 'sell', 5.3, price, {
    'stopPrice': YOUR_STOP_PRICE_HERE, // required by stop_market type
})
```

 ↑ The params for LIMIT and STOP_MARKET orders are not interchangeable, so the set of arguments and params depends on the order type.

**Comment by radiant-alex** [comment]
I think TypeScript def should be updated then:

```
 export interface Order {
        id: string;
        datetime: string;
        timestamp: number;
        lastTradeTimestamp: number;
        status: 'open' | 'closed' | 'canceled';
        symbol: string;
        **type: 'market' | 'limit';** <-- should have other types as well or just 'any'
        side: 'buy' | 'sell';
        price: number;
        average?: number;
        amount: number;
        filled: number;
        remaining: number;
        cost: number;
        trades: Trade[];
        fee: Fee;
        info: any;
    }
```
with type='stop_market' as:

`const type: any = 'stop_market'; // then just call createOrder with this parameter as type-arg`

all works then. Thanks a lot!

**Comment by kroitor** [comment]
@radiant-alex thx for pointing out the typescript defs, i've uploaded a fix, should accept any string as of CCXT Pro 0.2.49+ / CCXT 1.29.53+. Let us know if anything.
