### ISSUE TITLE
Cancel Order based on clientOrderID parameter

### ISSUE THREAD

**Issue by eugjr** [ccxt/ccxt#7086]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 7
- Programming Language version: Python 3.6
- CCXT version: 1.29.10

Hello, first of all, great job on the project, really helped me to setup a basic trading bot. 

It's possible to cancel an order based on clientOrderID parameter?? For testing purposes, I'm using Binance Futures, and I've made a custom code that places a long and a short order with custom client ID for each one ('long_entry' and 'long_short'. It worked fine, as it shows, using the command `orders = exchange.fapiPrivateGetOpenOrders()
    print('Open Orders:', orders)` we got the info for the 2 opened orders: 

```
Open Orders: [{'orderId': 4879539763, 'symbol': 'BTCUSDT', 'status': 'NEW', 'clientOrderId': 'long_entry', 'price':
'8500', 'avgPrice': '0.00000', 'origQty': '0.019', 'executedQty': '0', 'cumQuote': '0', 'timeInForce': 'GTC', 'type': 'L
IMIT', 'reduceOnly': False, 'closePosition': False, 'side': 'BUY', 'positionSide': 'BOTH', 'stopPrice': '0', 'workingTyp
e': 'CONTRACT_PRICE', 'origType': 'LIMIT', 'time': 1591639101103, 'updateTime': 1591639814113}, {'orderId': 4879538322,
'symbol': 'BTCUSDT', 'status': 'NEW', 'clientOrderId': 'short_entry', 'price': '9900', 'avgPrice': '0.00000', 'origQty
': '0.019', 'executedQty': '0', 'cumQuote': '0', 'timeInForce': 'GTC', 'type': 'LIMIT', 'reduceOnly': False, 'closePosit
ion': False, 'side': 'SELL', 'positionSide': 'BOTH', 'stopPrice': '0', 'workingType': 'CONTRACT_PRICE', 'origType': 'LIM
IT', 'time': 1591639099807, 'updateTime': 1591639814113}]'

```
For next step on the algo, I need to cancel a specific order, if some conditions are met.

I've tryied to cancel the short order using the following code: 
`'
symbol = 'USDT/BTC'
exchange.cancelOrder(symbol, params = {'BTC/USDT', params = {'origClientORderId' : 'short_entry'}',` but get as response:

```
  File "teste.py", line 262, in <module>
    corretora.cancelOrder(symbol, params = {'origClientORderId' : 'short_entry'})
  File "C:\Users\Sulamericana\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\binance.py", line 1329, in cancel_order    raise ArgumentsRequired(self.id + ' cancelOrder requires a symbol argument')
ccxt.base.errors.ArgumentsRequired: binance cancelOrder requires a symbol argument

```
I've been able only to cancel the orders using cancel all funcion, but it's risky as it would cancel also the stop limit order.

**Comment by kroitor** [comment]
Hi!

If you update to the most recent version 1.29.54+, you should be able to cancel it like so:

```Python
import ccxt
exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'apiKey': 'YOUR_SECRET',
    'enableRateLimit': True,
    'options': {
        # 'defaultType': 'future',  # uncomment if you want futures
    },
})
id = None
params = {'origClientOrderId': YOUR_CLIENT_ORDER_ID}
exchange.cancel_order(id, 'BTC/USDT', params)
```

or 

```Python
# ...
params = {'clientOrderId': YOUR_CLIENT_ORDER_ID}
exchange.cancel_order(id, 'BTC/USDT', params)
```

Both ways are equivalent. Hope it answers your question, let us know if not.

**Comment by kroitor** [comment]
There was a minor issue with it, i've uploaded a workaround, and with 1.29.55+ it should work ok (the new build will arrive within 15 minutes).

**Comment by eugjr** [comment]
Hi, thanks for the reply, and sorry for reopen the issue.

I've updated to the 1.29.55 version, and also changed the code to:

`id = None
 params = { 'ClientOrderId' : 'entry_short' }
 exchange.cancelOrder(id, 'BTC/USDT', params)`

But got the followin error:

`  File "teste.py", line 264, in <module>
    exchange.cancelOrder(id, 'BTC/USDT', params)
  File "C:\Users\Sulamericana\AppData\Local\Programs\Python\Python38\lib\site-packages\ccxt\binance.py", line 1365, in cancel_order
    request['orderId'] = int(id)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

**Comment by kroitor** [comment]
@eugjr pay attention to every character, compare your code to the example pasted above:

```
ClientOrderId # your code
clientOrderId # example
```

**Comment by eugjr** [comment]
Thank you for the help. Feel sorry for the last question, as I really dind't saw the typo error.
The code worked now, canceled only the short order, Thanks!

**Comment by kroitor** [comment]
@eugjr thx for reporting back! Cheers! )
