### ISSUE TITLE
How can I force fetchTrades method to properly download historical trades?

### ISSUE THREAD

**Issue by roko772** [ccxt/ccxt#7087]
Hello, I have problem with fetchTrades method. When I call it second and further times, it returns the same data, as at first time - I need to get full historical data of trades. It happens at every exchange. How can I solve that?

My note - code I written returns earliest timestamp from just downloaded dataframe to ensure it's working correctly, I want to store that information in CSV file.

- OS: Kubuntu 20.04
- Programming Language version: Python 3.8 with PyCharm CE 2020.1 IDE
- CCXT version: latest

```
import ccxt
import pandas as pd
import time

i = 0
symbol = 'BTC/USDT'
while True:
    exchange = ccxt.poloniex({'enableRateLimit': True})
    exchange.load_markets()
    i = i+1
    try:
        if i==1 :
            transaction_data = exchange.fetch_trades(symbol, limit=None)
            timestamp = 0
        else :
            transaction_data = exchange.fetch_trades(symbol, since=timestamp, limit=None)
    except ccxt.DDoSProtection:
        print("Błąd DDoSProtection, czekam 3 minuty.")
        time.sleep(180)
        continue
    except ccxt.RateLimitExceeded:
        print("Błąd RateLimitExceeded, czekam 1 minutę.")
        time.sleep(60)
        continue
    for pos in range(len(transaction_data)):
        for column in ['id','fee', 'info', 'order', 'takerOrMaker', 'type']:
            del transaction_data[pos][column]
    df = pd.DataFrame(transaction_data)
    timestamp = df['timestamp'].min()
    prev_timestamp = timestamp
    if len(transaction_data) == 0 :
        break
    print(timestamp)
df.to_csv('/mnt/dev_ramdisk/kraken.csv', index=None, header=True)
```

```
/home/roko/PycharmProjects/trading_adviser/venv/bin/python /snap/pycharm-community/197/plugins/python-ce/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 44287 --file /home/roko/PycharmProjects/trading_adviser/trades_get.py
pydev debugger: process 25966 is connecting

Connected to pydev debugger (build 201.7846.77)
1591642257000
1591642257000
1591642257000
1591642257000
Traceback (most recent call last):
  File "/home/roko/PycharmProjects/trading_adviser/trades_get.py", line 30, in <module>
    prev_timestamp = timestamp
KeyboardInterrupt

Process finished with exit code 130 (interrupted by signal 2: SIGINT)
```

**Comment by kroitor** [comment]
> I need to get full historical data of trades
> How can I solve that?

In general:
- attempting to fetch all trades will yield hundreds of millions of trades (if not billions of trades)
- it will require gigabytes of RAM if you do this within a single script run
- it will require gigabytes of storage space (nobody stores that in a single CSV for production purposes, really)
- it will definitely take a very long time

You might want to reconsider the approach to your task, and break it down into robust smaller tasks, with detached storage, fetching code and other sub-systems. I'd really recommend to apply more practical approaches to your systems architecture, that in itself is not easy to do the right way. We cannot design the entire aggregation system for you in a small snippet. Other companies spend thousands of dollars to solve tasks like this.

In short, here's a script that will attempt to download all of them from Poloniex for one pair using the pagination as described in CCXT's Manual. 

```Python
# -*- coding: utf-8 -*-

import os
import sys
import pandas as pd

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402

exchange = ccxt.poloniex({'enableRateLimit': True})
exchange.load_markets()

# Poloniex will only serve one year of data into the past

symbol = 'BTC/USDT'
before = exchange.milliseconds()
previous_length = 0
all_trades = {}

while True:
    try:
        print('---------------------------------------------------------------')
        print('Fetching trades before', exchange.iso8601(before))
        params = {
            'end': int(before / 1000)  # end param must be in seconds
        }
        trades = exchange.fetch_trades(symbol, None, None, params)
        trades_by_id = exchange.index_by(trades, 'id')
        before = trades[0]['timestamp']
        all_trades = exchange.extend(all_trades, trades_by_id)
        total_length = len(all_trades.keys())
        print('Fetched', total_length, 'trades in total')
        if total_length == previous_length:
            break
        previous_length = total_length
    except ccxt.NetworkError as e:
        print(e)  # retry on next iteration
    except ccxt.ExchangeError as e:
        print(e)
        sys.exit()

all_trades = exchange.sort_by(all_trades.values(), 'id')
print('Fetched', len(all_trades), 'trades since', all_trades[0]['datetime'], 'till', all_trades[-1]['datetime'])

# omitted_keys = ['fee', 'info']
# all_trades = [exchange.omit(trade, omitted_keys) for trade in all_trades]
# path_to_your_csv_file = 'trades.csv'  # change for your path here
# df = pd.DataFrame(all_trades)
# df.to_csv(path_to_your_csv_file, index=None, header=True)
```

Let us know if that does not answer your question.

**Comment by roko772** [comment]
Hello, thank you very much for help!
Sorry for late response, but actually I have some questions:
1. I actually wanted use fetchTrades method as all-exchanges method. Poloniex exchange was coded by as reference only - I trade on Kraken and Binance, maybe I will use another exchanges. Maybe it will be better for me, as inexperienced, to do a research myself. At least for one of these :)
2. I understand, that downloading one-year trades history can eat every RAM amount in my PC. When running, I needed to plug in... I don't remember... something like 15-20 GB of swap space to my system with 16 GB of regular RAM. That's why I wanted to save dataframe to my storage before fetching next one. When saved to disk as CSV it consumes almost 1 GB uncleaned. But maybe it will be better to use MongoDB as carlos8f/DeviaVir in their Zenbot? But again, it's my problem, but it will be nice to hear some advice :)
Thank you again for help!

**Comment by kroitor** [comment]
@roko772 

> I actually wanted use fetchTrades method as all-exchanges method. Poloniex exchange was coded by as reference only - I trade on Kraken and Binance, maybe I will use another exchanges. Maybe it will be better for me, as inexperienced, to do a research myself. At least for one of these :)

One of the pagination methods should work: https://github.com/ccxt/ccxt/wiki/Manual#pagination
Let us know if you have difficulties with that. However, very few exchanges will serve the entire public history.

> I understand, that downloading one-year trades history can eat every RAM amount in my PC. When running, I needed to plug in... I don't remember... something like 15-20 GB of swap space to my system with 16 GB of regular RAM. That's why I wanted to save dataframe to my storage before fetching next one. When saved to disk as CSV it consumes almost 1 GB uncleaned. But maybe it will be better to use MongoDB as carlos8f/DeviaVir in their Zenbot? But again, it's my problem, but it will be nice to hear some advice :)

You definitely want to do that in batches and process the results page by page using dbms. However, it is hard to write out a good all-in-one short-snippet example that would do that for you, basically, it requires the entire program architecture to be implemented properly.
