### ISSUE TITLE
okex simulation trading pair support

### ISSUE THREAD

**Issue by ablewolf** [ccxt/ccxt#7088]
The name of the simulated trading pairs and the contracts is preceded by MN, for example, MNBTC-MNUSDT (spot/margin), MNBTC-USD-180213 (futures contract), MNBTC-MNUSDT-SWAP (perpetual contract ), MNBTC-USD-190927-5000-C (option contract)

**Comment by meetmangukiya** [comment]
This can be achieved by simply adding the header 
```ts
  const exchange = new okex({
    verbose: true,
    apiKey: "xxx",
    secret: "xxx",
    password: "xxx",
    timeout: 50000,
    headers: {
      "x-simulated-trading": 1
    },
    // @ts-ignore
    options: {
      defaultType: "futures"
    }
  });
```

**Comment by kroitor** [comment]
@meetmangukiya thx a lot for the feedback!
@ablewolf let us know if @meetmangukiya's answer does not solve this issue for you. Feel free to reopen it if needed or just ask further questions, if any.

**Comment by ttodua** [comment]
In future you might use (if smth like [this ](https://github.com/ccxt/ccxt/pull/10912) PR will be implemenetd ) :

```
const exchange = new ccxt.okex();
exchange.isDemoAccount(true);
```

However, don't forget you need the demo api keys to be generated from demo-trading account.
