### ISSUE TITLE
Hi! I want donate some Crypto~ Is that address correct?

### ISSUE THREAD

**Issue by kingwithsword** [ccxt/ccxt#7089]
I am a CCXT user,  I want to donate some Crypto.

I will transfer to your address as follows:

ETH 0x26a3CB49578F07000575405a57888681249c35Fd (ETH only)
BTC 33RmVRfhK2WZVQR1R83h2e9yXoqRNDvJva
BCH 1GN9p233TvNcNQFthCgfiHUnj5JRKEc2Ze
LTC LbT8mkAqQBphc4yxLXEDgYDfEax74et3bP

Is that correct? Is that OK?

Hope to your reply~

                                                                                                     Wang

**Comment by kroitor** [comment]
Hi! 

Yes, those addresses are correct! Thank you for your support, we appreciate it!
