### ISSUE TITLE
Erro update-badges.js:30

### ISSUE THREAD

**Issue by Alisonsilva47** [ccxt/ccxt#7090]
When I give the "npm run build" I get the following error:

./python/README.rst (<anonymous> @ update-badges.js:18)
/ccxt/build/update-badges.js:30
let rstExchangeTableLines = match[2].split ("\n")
                                 ^

TypeError: Cannot read property '2' of null
    at Object.<anonymous> (/ccxt/build/update-badges.js:30:34)

**Comment by kroitor** [comment]
This is a known issue with pandoc 2+... Unfortunately, the docker image is currently broken due to this bug. If you deinstall pandoc 2 and install pandoc 1.19 that should fix it. We will do our best to fix the docker image asap.

**Comment by kroitor** [comment]
P.S. the build itself is fine, it is complaining about the docs, so you can ignore it, and proceed to further steps.

**Comment by Alisonsilva47** [comment]
OK, thank you
