### ISSUE TITLE
New Exchange: 58coin (58ex.com)

### ISSUE THREAD

**Issue by wonder-all** [ccxt/ccxt#7093]
我看了下那么多交易所都有，可是没有找到58coin交易所的  想问下有打算添加么？

**Comment by kroitor** [comment]
Hi! 

Please, see the FAQ and the CONTRIBUTING guidelines:

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

**Comment by binares** [comment]
If anyone intends to complete it you can use this: https://github.com/binares/ccxt/tree/58coin

**Comment by frosty00** [comment]
not loading for me
