### ISSUE TITLE
Leverage order on Binance 

### ISSUE THREAD

**Issue by gambitov** [ccxt/ccxt#7098]
How could I change leverage to make a new order?

**Comment by kroitor** [comment]
Duplicate: 

- https://github.com/ccxt/ccxt/issues/6978
- https://github.com/ccxt/ccxt/issues/7004#issuecomment-633182718

**Comment by gambitov** [comment]
Thank you. Could you help me how can change isolated or cross?

**Comment by kroitor** [comment]
@gambitov use the search, Luke: https://github.com/ccxt/ccxt/search?q=binance+cross+isolated&type=Issues )

- https://github.com/ccxt/ccxt/issues/6357#issuecomment-572828671
