### ISSUE TITLE
Error handling outside a loop?

### ISSUE THREAD

**Issue by Hororohoruru** [ccxt/ccxt#7099]
- OS: Ubuntu 18
- Programming Language version: Python 3.7
- CCXT version: 1.27.49

Hello, I am building an arbitrage bot and I have a piece of code that places orders in two exchanges. Sometimes I get connextion errors (HTTP error, DDos protection, etc.) when placing the orders. If this part of the code was inside a loop, I could handle it just retrying, but they are not. Moreover, in the case that one order gets placed but the other doesn't, it could be a problem. Here an example where I got it last time:

```
# Place the orders
try:  # This is for HitBTC
    buy_order = buy_client.create_order(symbol=self.symbol, type='limit', side='buy',
                                        amount=buy_amount, price=buy_price)
    self._log_msg(f"Placed buy order for amount {buy_amount} "
                  f"and price {buy_price}")
except ccxtpro.ExchangeError:  # The amount does not comprise to lots sometimes, so...
    self._log_msg(f"Buy order failed for {buy_client.id} with amount {buy_amount}...")

    # Get market lot
    buy_market = buy_client.markets[self.symbol]  # Got DDos error here
    buy_lot = buy_market['limits']['amount']['min']

    # Get correct amount
    buy_correct = self._correct_amount(buy_amount, buy_lot)
    self._log_msg(f"Corrected amount to {buy_correct}, retrying order...")
    buy_order = buy_client.create_order(symbol=self.symbol, type='limit', side='buy',
                                       amount=buy_correct, price=buy_price)
    self._log_msg(f"Placed buy order for amount {buy_correct} and price {buy_price}")
```

It has only happened once, but I am afraid it is quite the critical part of the code to get one of these errors, so what could be done?

**Comment by kroitor** [comment]
Hi! Do you have the rate-limiter enabled?

**Comment by Hororohoruru** [comment]
Hello! I think so! I have both ccxtpro and regular ccxt instances of the exchanges, instantiated like this:

CCXTpro:
```
exchange_class = getattr(ccxtpro, exchange_name)
client = exchange_class({'apiKey': key_pair['api_key'],
                         'secret': key_pair['api_secret'],
                         'timeout': 30000,
                         'enableRateLimit': True,
                         'asyncio_loop': loop})
```

CCXT:
```
exchange_class = getattr(ccxt, exchange_name)
client = exchange_class({'apiKey': key_pair['api_key'],
                         'secret': key_pair['api_secret'],
                         'timeout': 30000,
                         'enableRateLimit': True,
                         })
```

**Comment by kroitor** [comment]
In general a single HTTPError or DDoSProtection error may be normal, and is usually handled with a retry. The set of possible exceptions is described here: https://github.com/ccxt/ccxt/wiki/Manual#error-handling

However, if it does repeat consistently, then it may indicate a bug or a rate-limiter issue. If you get it too often – please paste a short but complete code snippet to reproduce it (with exchange instantiation code, but without your keys) + your verbose request/response sequence for that failure. 

Let us know if that does not answer the question. Feel free to reopen it or just ask further questions, if any.

**Comment by Hororohoruru** [comment]
Ok, I see. I will add a manual retry and see what happens. Thank you very much!
