### ISSUE TITLE
Unified API: orders

### ISSUE THREAD

**Issue by incompletude** [ccxt/ccxt#71]
Is there any plans to add returnOpenOrders to the Unified API? It would give the Unified API a more complete set of methods to manage all your accounts.

**Comment by kroitor** [comment]
Yes, it's actually one of the big milestones, that is the most difficult part to unify, but we will, of course ) Otherwise the API would not be completely unified, and you're right, we want to have a subset of common methods and formats for all our common needs. The unified API should (and will) cover all that entirely. We also have plans for unifying fees, as you may know from #40 , and several other data structures.

**Comment by incompletude** [comment]
That is amazing. Quite impressed with ccxt.

**Comment by kroitor** [comment]
Yep, we will update you on the progress, keep in touch )

**Comment by Nilotaviano** [comment]
Reposting from #96:

fetchOrder was implemented for chbtc on #74. I was trying to implement it for liqui, poloniex and bittrex, but there's nothing like "getOrder" on poloniex, so I don't think it's possible without ugly "workarounds", like emulating it using "returnOpenOrders", "returnOrderTrades" and/or "returnTradeHistory". This might be the same for some other exchanges, I'm not sure.

**Comment by kroitor** [comment]
Also, check out this: https://github.com/kroitor/ccxt/pull/102
The work on orders/trades unification is going on! )

**Comment by imcoddy** [comment]
I just digging into ccxt and looks like zaif doesn't have this feature yet. Looking forward to it

**Comment by kroitor** [comment]
@imcoddy we're working on it ) order unification for zaif is in progress ) Hope to deliver soon

**Comment by kroitor** [comment]
@imcoddy We have added an experimental order API to zaif: fetchOpenOrders, fetchClosedOrders. Please update to latest version 1.5.33+ in a couple of minutes and try it. We will be happy if you help us test it thoroughly. Thx!

**Comment by kroitor** [comment]
Added fetchOpenOrders() to CEX.io in #293 as well as many other implementations for reference and further development, as described here: https://github.com/ccxt-dev/ccxt/issues/275#issuecomment-334788455

**Comment by kroitor** [comment]
https://github.com/ccxt-dev/ccxt/search?utf8=%E2%9C%93&q=fetchOrder&type=Commits
https://github.com/ccxt-dev/ccxt/search?utf8=%E2%9C%93&q=fetchOrders&type=Commits
https://github.com/ccxt-dev/ccxt/search?utf8=%E2%9C%93&q=fetchOpenOrders&type=Commits
https://github.com/ccxt-dev/ccxt/search?utf8=%E2%9C%93&q=fetchClosedOrders&type=Commits

<img width="1106" alt="screen shot 2017-10-10 at 00 54 06" src="https://user-images.githubusercontent.com/1294454/31360111-8cc56318-ad55-11e7-8ad3-8f1d2df68c6b.png">

**Comment by dservais** [comment]
Good evening, any chance to have the fetchorder familly functions for GDAX soon ?
Best regards

**Comment by kroitor** [comment]
@dservais hi! Yep, should be available in a day or two, hopefully.

**Comment by kroitor** [comment]
@dservais we uploaded fetchOrder + fetchOpenOrders for GDAX, should be available in approx 5 minutes in version 1.9.111+. Let us know if you have any questions or difficulties.

**Comment by dservais** [comment]
Many thanks ! your 1 or 2 days reduced to 3 hours ! impressive as usual. 
Best regards

**Comment by dservais** [comment]
I have a problem : it works fine for some keys like 'price', 'side', or 'id' but there is an error with 'size', 'product_id' or some others

pair='ETH/BTC'
myorder = gdax.fetchOpenOrders()
print (len(myorder))
print(myorder)
print (myorder[0]['price'])
print (myorder[0]['side'])
print (myorder[0]['id'])
print (myorder[0]['size'])

Results:
42
[{'id': 'cc43f1aa-6991-42a1-9f20-f2f3e4373d85', 'info': {'id': 'cc43f1aa-6991-42a1-9f20-f2f3e4373d85', 'price': '0.06310000', 'size': '0.05000000', 'product_id': 'ETH-BTC', 'side': 'sell', 'stp': '.......
0.0631
sell
cc43f1aa-6991-42a1-9f20-f2f3e4373d85
Traceback (most recent call last):
  File "C:/Users/Didier/Google Drive/Crypto/CCXT/gdaxorders.py", line 19, in <module>
    print (myorder[0]['size'])
KeyError: 'size'

**Comment by kroitor** [comment]
@dservais the unified order structure is [described here](https://github.com/ccxt-dev/ccxt/wiki/Manual#order-structure). There's no `size` field in it ;)

**Comment by dservais** [comment]
Good evening Igor, many thanks again for the GDAX orders familly. It is very usefull.
On the fetchClosedOrders function, it seems that only the last 100 orders are coming back, is there a way to get all Closed Orders ?

Best regards

**Comment by kroitor** [comment]
@dservais I guess, this is their default behaviour. Actually, no exchange will give you full history "for all time since the beginning", because this is against their DDoS Protection. So, all of them will limit their output to a reasonably-small amount of orders. If you want to have older history – you will have to maintain it on your end. Does this answer your question?

**Comment by kroitor** [comment]
Current overview:

<img width="1163" alt="screen shot 2017-10-14 at 21 39 20" src="https://user-images.githubusercontent.com/1294454/31578351-2cf3b1e8-b128-11e7-9f60-a20263ce34e7.png">

**Comment by dservais** [comment]
Yes it answers to my question. Many thanks.

**Comment by tandazhi** [comment]
Hello Kroitor,

is there any plan to add fetchOrders() and fetchOpenOrders methods for huobipro?

Best Regards

**Comment by kroitor** [comment]
Hello, @tandazhi! We are going to add them all eventually, but if you can go ahead and submit a PR on that, it would be awesome! We appreciate all help! Thx )

**Comment by tandazhi** [comment]
That is great!

**Comment by kroitor** [comment]
@tandazhi your PR isn't merged yet, but will be soon! Thx!

**Comment by ugozanchi** [comment]
How can I see this image status updated? https://user-images.githubusercontent.com/1294454/32969545-9a3e0f30-cbf6-11e7-8c71-2ef54d4b889f.png

**Comment by kroitor** [comment]
@ugozanchi I've updated the [image above ↑](#issuecomment-336655046)

- https://github.com/ccxt/ccxt/blob/master/examples/
- https://github.com/ccxt/ccxt/blob/master/examples/js/exchange-capabilities.js

To get it on your screen you will need a very small font and a very wide terminal window:

```
node examples/js/exchange-capabilities.js
```

**Comment by ugozanchi** [comment]
Thank you so much. So fast =D , you don't sleep?? Lol .

**Comment by orkenstein** [comment]
@kroitor, I've noticed, that some exchanges have a mandatory `symbol` field for `fetchOpenOrders`. What's the plan? Maybe it worth to have some function like `ordersRequireSymbol`, to know before you get an exception?

**Comment by kroitor** [comment]
@orkenstein https://github.com/ccxt/ccxt/issues/1058

**Comment by kroitor** [comment]
<img width="1638" alt="screen shot 2018-01-27 at 20 14 43" src="https://user-images.githubusercontent.com/1294454/35474395-c5340232-039e-11e8-9efc-73ca95fd0e87.png">

**Comment by orkenstein** [comment]
@kroitor, is this exchanges coverage?
Hm, livecoin definitely has 'fetchOrders' and variants.

**Comment by kroitor** [comment]
@orkenstein yep, but some of `.has = { ... }` properties are missing there. Would be happy if you help fill them up to get an even more updated coverage overview ;)

**Comment by orkenstein** [comment]
@kroitor, you beat me!

**Comment by kroitor** [comment]
An updated overview as of 2018-02-26:

<img width="1718" alt="screen shot 2018-02-26 at 04 29 14" src="https://user-images.githubusercontent.com/1294454/36649372-a4d32b32-1aad-11e8-9502-6b3fe9236f6a.png">

**Comment by gaardiolor** [comment]
Question; Is someone working on / any ETA on the availability of the following methods for exchange Gatecoin:
```
fetch_open_orders
cancel_order
create_limit_buy_order
create_limit_sell_order
```
If not, no problem, I know you're working hard!

**Comment by kroitor** [comment]
@gaardiolor i'm mostly focused on fixing existing methods before adding new ones. The help of community would be really appreciated! Thx!

**Comment by kroitor** [comment]
@gaardiolor 

> create_limit_buy_order
> create_limit_sell_order

These two are already there. They are wrapping create_order, which is already done for Gatecoin.

> fetch_open_orders

This one is missing

> cancel_order

This one is also already available.

**Comment by gaardiolor** [comment]
Ah sorry, my bad! fetch_open_orders , any eta on that one ? Or are you busy with other things at the moment ?

**Comment by ugozanchi** [comment]
Could you update with a new picture?

**Comment by kroitor** [comment]
Sure, here you go:

<img width="1508" alt="screen shot 2018-07-17 at 23 59 40" src="https://user-images.githubusercontent.com/1294454/42845068-8398507a-8a1d-11e8-9745-ac2facfd19ff.png">

You can generate it yourself as well with this example: https://github.com/ccxt/ccxt/tree/master/examples/js/exchange-capabilities.js
