### ISSUE TITLE
Bittrex API v2

### ISSUE THREAD

**Issue by hroff-1902** [ccxt/ccxt#7104]
One of our (freqtrade app based on ccxt) users refused in support from Bittrex:

> "Unfortunately, we cannot advise you on API v2.0 since this version of our API is not officially supported. At this time, we can only provide support for API v1.1 and v3."

Bittrex has the ccxt.certified badge.

ccxt implementation for Bittrex uses v2 and v3 of Bittrex API.

So we (and you) have a situation when users of apps based on ccxt are refused in support.

Can you 1) manage this situation with Bittrex 2) move ccxt implementation for Bittrex to v1.1 and v3?

**Comment by kroitor** [comment]
@hroff-1902 the current implementation of Bittrex in CCXT is exactly v1.1 and v3. Let us know if that does not answer your question.

**Comment by hroff-1902** [comment]
It does not answer my question:

https://github.com/ccxt/ccxt/blob/2544c537510b399b1ffef05f2504c2dff469fe5f/python/ccxt/bittrex.py#L73-L74

**Comment by kroitor** [comment]
@hroff-1902

This is v1:

- https://github.com/ccxt/ccxt/blob/master/js/bittrex.js#L49
- https://github.com/ccxt/ccxt/blob/master/js/bittrex.js#L50
- https://github.com/ccxt/ccxt/blob/master/js/bittrex.js#L51

This is v3:

- https://github.com/ccxt/ccxt/blob/master/js/bittrex.js#L53
- https://github.com/ccxt/ccxt/blob/master/js/bittrex.js#L54

**Comment by hroff-1902** [comment]
https://github.com/ccxt/ccxt/blob/2544c537510b399b1ffef05f2504c2dff469fe5f/js/bittrex.js#L656

**Comment by kroitor** [comment]
@hroff-1902 yeah, that's the only v2 method left, rewriting it to v3 right now. Should be ok in 1.29.80, it will arrive in 15-30 minutes.

**Comment by hroff-1902** [comment]
since v2 is not supported by Bittrex, I think it would also be nice if you remove any appearances of it in the comments and the code for ccxt implementation for Bittrex...

**Comment by kroitor** [comment]
@hroff-1902 it's 1.29.81+, on its way.

**Comment by hroff-1902** [comment]
> @hroff-1902 it's 1.29.81+, on its way.

thanks for prompt reaction!

**Comment by kroitor** [comment]
@hroff-1902 appreciate your feedback!

**Comment by kroitor** [comment]
@hroff-1902 should work fine now, let us know if you have any difficulties with it. Thx again!
