### ISSUE TITLE
Authentication failure when writing a new exchange implementation

### ISSUE THREAD

**Issue by ericoacguedes** [ccxt/ccxt#7107]
Hi,

I'm writing a sign method for an exchange. 
The example presented by this exchange, for authentication, is written in curl:

```
curl --request POST \
--url https://exchange-utl \
--header 'Content-Type: application / json' \
--date '{\
"cmd": "balance", \
"auth_token": "ABg3M ………… .UREJGD" \
} '
```
The correspondent code for nodejs is:
```
body: JSON.stringify({ 'cmd': params['cmd'], 'auto_token': this.secret + this.apiKey })
```
However, there is a build error:
```
qa run-test: commands[0] | flake8 --exclude static_dependencies,.tox
./ccxt/bitpreco.py:425:20: F821 undefined name 'json'
./ccxt/async_support/bitpreco.py:425:20: F821 undefined name 'json'
ERROR: InvocationError for command /ccxt/python/.tox/qa/bin/flake8 --exclude static_dependencies,.tox (exited with code 1)
```
I'm developing in the docker container, as recommended. I tried
```
pip3 install simplejson
```
at docker container, but the error persists.

So, how to correctly translate the curl message to ccxt nodejs, so that it builds successfully?

Thanks in advance,

Erico.

**Comment by kroitor** [comment]
Hi @ericoacguedes !

First of all, a developer has to follow the CONTRIBUTING guidelines literally to a word.

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#new-exchange-integrations

If you look into the guidelines, it is mentioned there, that you should always do this by example.
If you open any other exchange in CCXT – you won't find a `JSON.stringify` clause there. 

Instead we use `this.json (...)` which is a base-class wrapper.

Apart from that, the implementation file has to follow a set of very specific syntax rules, namely:

```
this.json({ 'foo': 'bar' }) // wrong
this.json ({ 'foo': 'bar' }) // correct
```

```
// wrong
this.json ({ 'a': 'b', 'foo': 'bar' + 'qux' }) 

// correct
const foo = 'bar' + 'qux';
this.json ({
    'a': 'b',
    'foo': foo,
})
```

Hope it helps. Let us know if not. Feel free to reopen this issue or just ask further questions, if any.

**Comment by ericoacguedes** [comment]
Hello again,

> Hi @ericoacguedes !
> 
> First of all, a developer has to follow the CONTRIBUTING guidelines literally to a word.
> 
> * https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes
> * https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#new-exchange-integrations
> 
> If you look into the guidelines, it is mentioned there, that you should always do this by example.
We did...

> If you open any other exchange in CCXT – you won't find a `JSON.stringify` clause there.
Yes, we always look inside the other exchanges when we are in doubt regarding some issues.
We found the JSON.stringify inside js/base/functions/crypto.js.

> 
> Instead we use `this.json (...)` which is a base-class wrapper.
And we had used this.json. Indeed, at the end of the day, the issue was a typo: instead of auth_token we typed auto_token... we made the correction. 

Thank you.

> 
> Apart from that, the implementation file has to follow a set of very specific syntax rules, namely:
> 
> ```
> this.json({ 'foo': 'bar' }) // wrong
> this.json ({ 'foo': 'bar' }) // correct
> ```
> 
> ```
> // wrong
> body = this.json ({ 'a': 'b', 'foo': 'bar' + 'qux' }) 
> 
> // correct
> const foo = 'bar' + 'qux';
> body = this.json ({
>     'a': 'b',
>     'foo': foo,
> })
> ```
> 
> Hope it helps. Let us know if not. Feel free to reopen this issue or just ask further questions, if any.

**Comment by kroitor** [comment]
> Yes, we always look inside the other exchanges when we are in doubt regarding some issues.
> We found the JSON.stringify inside js/base/functions/crypto.js.

Just to clarify – `js/base/functions/crypto.js` is not an exchange implementation. It is the base functionality. _"By example"_ means other exchange implementations, the files inside `js/HERE.js`, not in `js/base/.../HERE.js`.
