### ISSUE TITLE
Binance margin unified api

### ISSUE THREAD

**Issue by azharuniverse** [ccxt/ccxt#7109]
Is there a timeline on when binance margin unified api will be integrated? 

I have been waiting for this since fairly long time and I see ccxt has been integrating new not so popular exchange but has not worked on the margin trading of most popular crypto exchange which is binance. 

Purpose of asking this question is to evaluate wheather I should write my own unified api calls for binance margin or wait for ccxt to complete.

**Comment by azharuniverse** [comment]
And doing implicit api calls is not a solutions. We use ccxt for unified exchange api. doing http calls can be easily done without ccxt dependency.

**Comment by kroitor** [comment]
@azharuniverse hi!

> Is there a timeline on when binance margin unified api will be integrated?

Basically, asking the "when" question does not help speed up solving it, as explained in our FAQ here:

- https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar
- https://github.com/ccxt/ccxt/wiki/FAQ#when-will-you-add-feature-foo-for-exchange-bar--whats-the-estimated-time-when-should-we-expect-this

In other words, we receive lots of questions on when it will be added, however, asking those questions really eats the time. Very few people actually take part in the open discussion on the margin/leveraged/positional trading unification issue here:

- https://github.com/ccxt/ccxt/issues/4834
- https://github.com/ccxt/ccxt/issues/6790
- https://github.com/ccxt/ccxt/issues/6697

> I have been waiting for this since fairly long time 

That's exactly my point – lots of people are waiting, and very few people are helping. The CCXT project is free for the users and it is intended to be developed by users like you. Some of your effective assistance would really help.

> Purpose of asking this question is to evaluate wheather I should write my own unified api calls for binance margin or wait for ccxt to complete.

You should not wait in any case. Waiting is a wrong approach. Suggest technical details instead. That would help speed it up. If you can do the unified implementation for yourself – you can also help CCXT do the unified implementation as well. Note, however, that there is no "unified implementation for Binance". If it is unified – it has to account for other exchanges as well, in other words, it has to be truly unified, not exchange-specific (not one exchange, but all exchanges – that is "unified").

If you could actively participate in this discussion, that would really help:

- https://github.com/ccxt/ccxt/issues/4834

↑ Your suggestions on the unified margin order structures and methods, unified leverage, risk, positions and other aspects are welcome! We hope that upon suggesting, you do at least some research on the details across other exchanges, in other words, make sure you fully understand the details and implications (we've already had a ton of lame and shitty suggestions and it's really hard to explain to everyone why this or that would not work as a good unification schema if you don't spend the time on investigating the subject thoroughly). If you don't want to participate there – you always have the alternative option of doing a custom implementation and keeping it to yourself.

I hope that answers your question, and we would be very thankful for your participation in the above public discussions.

**Comment by azharuniverse** [comment]
Your answer is logical and understandable thanks for taking time to explain. I will follow what you said.

**Comment by azharuniverse** [comment]
I think my feature request doesn't need further discussion in other threads. My request was not unification of all the endpoints but few necessary onces as it is done by ccxt in case of binance futures. where we pass options.type=futures and then I can fetch balance and place trade on futures. 

I understand your point since its open source and not a paid private project so someone from the community has to do the work. I agree with that.

**Comment by kroitor** [comment]
@azharuniverse you can use the `'options': { 'defaultType': 'margin' }` with Binance at this time. However, that is exchange-specific. You can also provide `'type': 'margin'` in params-overrides, that will also work with the other exchanges.

**Comment by azharuniverse** [comment]
wow! great. thats what I was looking for. I can do additional actions using implicit calls. I wanted the basic function like balance and trade via existing functions. I will update ccxt and read binance.js Thanks for your quick response. you are awesome.
