### ISSUE TITLE
On bitcoincoid.py - 'XLM/IDR' is missing from the table. 

### ISSUE THREAD

**Issue by izjenie** [ccxt/ccxt#711]
You can open python/ccxt/bitcoincoid.py and added this after line #48:

Line #49:                 'XLM/IDR': {'id': 'str_idr', 'symbol': 'XLM/IDR', 'base': 'XLM', 'quote': 'IDR', 'baseId': 'str', 'quoteId': 'idr'},

Thanks.
-izak

**Comment by kroitor** [comment]
Thank you, this is available in 1.10.256. Cheers!
