### ISSUE TITLE
How to use test api?

### ISSUE THREAD

**Issue by monk-after-90s** [ccxt/ccxt#7110]
Hi, I notice that many exchanges have test accounts or apis such as Bitmex, thus their ccxt exchange instance have test url too. So is there a way for ccxt to use the test api automatically, instead of any error of bad Apikey or something else?

**Comment by kroitor** [comment]
```Python
import ccxt
exchange = ccxt.bitmex({
    'enableRateLimit': True,
})
exchange.set_sandbox_mode(True)
```

Let us know if that does not answer your question.

**Comment by monk-after-90s** [comment]
Thank you @kroitor
