### ISSUE TITLE
Bitmex contract parsed badly

### ISSUE THREAD

**Issue by monk-after-90s** [ccxt/ccxt#7111]
Hello, I notice that a bitmex contract order information is parsed like this:
```Python
{
  'info': {
    'orderID': 'e806c200-deda-679a-451b-ac44ad9fa541',
    'clOrdID': '',
    'clOrdLinkID': '',
    'account': 308110,
    'symbol': 'XBTUSD',
    'side': 'Sell',
    'simpleOrderQty': None,
    'orderQty': 1,
    'price': 9459.5,
    'displayQty': None,
    'stopPx': None,
    'pegOffsetValue': None,
    'pegPriceType': '',
    'currency': 'USD',
    'settlCurrency': 'XBt',
    'ordType': 'Limit',
    'timeInForce': 'GoodTillCancel',
    'execInst': '',
    'contingencyType': '',
    'exDestination': 'XBME',
    'ordStatus': 'Filled',
    'triggered': '',
    'workingIndicator': False,
    'ordRejReason': '',
    'simpleLeavesQty': None,
    'leavesQty': 0,
    'simpleCumQty': None,
    'cumQty': 1,
    'avgPx': 9460,
    'multiLegReportingType': 'SingleSecurity',
    'text': 'Submission from testnet.bitmex.com',
    'transactTime': '2020-06-13T05:47:03.837Z',
    'timestamp': '2020-06-13T05:47:03.837Z',
  },
  'id': 'e806c200-deda-679a-451b-ac44ad9fa541',
  'clientOrderId': '',
  'timestamp': 1592027223837,
  'datetime': '2020-06-13T05:47:03.837Z',
  'lastTradeTimestamp': 1592027223837,
  'symbol': 'BTC/USD',
  'type': 'limit',
  'side': 'sell',
  'price': 9459.5,
  'amount': 1.0,
  'cost': 9460.0,
  'average': 9460.0,
  'filled': 1.0,
  'remaining': 0.0,
  'status': 'closed',
  'fee': None,
  'trades': None,
}
```
However, as I know, the orderQty of this order means how many USD of this contract as the contract of BTC/USD is 1USD per one, which is described on https://testnet.bitmex.com/app/trade/XBTUSD .So maybe the orderQty should be transfered as 'cost'.

**Comment by kroitor** [comment]
Hi!

Let us know if these similar issues don't answer your question:

- https://github.com/ccxt/ccxt/issues/6866
- https://github.com/ccxt/ccxt/issues/4834
- https://github.com/ccxt/ccxt/issues/3540
- https://github.com/ccxt/ccxt/issues/2499
- ...

Closing this for now, feel free to reopen it or just ask further questions, if any.

**Comment by monk-after-90s** [comment]
> Hi!
> 
> Let us know if these similar issues don't answer your question:
> 
>     * #6866
> 
>     * #4834
> 
>     * #3540
> 
>     * #2499
> 
>     * ...
> 
> 
> Closing this for now, feel free to reopen it or just ask further questions, if any.

@kroitor I've carefully researched this comment https://github.com/ccxt/ccxt/issues/6866#issuecomment-621091146 . As you write, this may be a rule for contacts across exchanges. But, to be compatible with spots the ccxt unified order information of which the 'cost','average' and 'filled' are defined according to 'cost=filled*average', maybe it would be better for contracts to obey this 'unification rule'.

**Comment by kroitor** [comment]
@monk-after-90s i'd say, that depends on whether the contract is linear or inverse. 

In other words, a better way of doing this is to unify the contract orders and treat a contract order as a standalone type of order, where the rules are different from spot orders (where `cost`, `amount` and other fields will depend on the "underlying" and the contract specification). 

In general, when you are trading contracts, the `amount` is the number of contracts. So, if you buying a BTC/USD contract, you're not buying BTC nor USD. You're in fact buying a BTC/USD "contracts". Despite that it looks like a pair of things, it's actually one thing called "BTC/USD". In other words, a BTC/USD contract is not a pair of currencies. It's a contract symbol. 1 BTC/USD = one "contract". The cost of the contract can be either expressed in BTC (linear) or USD (inverse). For that matter the `cost` calculation depends on the specification of the contract and can also be expressed in BTC or USD, as opposed to spot orders, where `cost` is always in quote currency.

The unification of contract orders is a work in progress now.

**Comment by monk-after-90s** [comment]
> @monk-after-90s i'd say, that depends on whether the contract is linear or inverse.
> 
> In other words, a better way of doing this is to unify the contract orders and treat a contract order as a standalone type of order, where the rules are different from spot orders (where `cost`, `amount` and other fields will depend on the "underlying" and the contract specification).
> 
> In general, when you are trading contracts, the `amount` is the number of contracts. So, if you are buying a BTC/USD contract, you're not buying BTC nor USD. You're in fact buying a BTC/USD "contract". For example, depending on the exchange rules one BTC/USD contract can cost, , 0.001BTC or 10USD (depending on the contract specification). Despite that it looks like a pair of things, it's actually one thing called "BTC/USD". You can think of it as of a single entity. In other words, a BTC/USD contract is not a pair of currencies. It's a contract symbol. 1 BTC/USD = one "contract".
> 
> The value of the contract can be either expressed in BTC (linear) or USD (inverse). For that matter the `cost` calculation depends on the specification of the contract and can also be expressed in BTC or USD, as opposed to spot orders, where `cost` is always in quote currency.
> 
> The unification of contract trading is a work in progress now.

@kroitor  Thanks a lot. It is a greate work.
