### ISSUE TITLE
Kucoin fetchBalance method returning empty data

### ISSUE THREAD

**Issue by viniciussvl** [ccxt/ccxt#7116]
Hello,
I have 2 accounts at Kucoin, when trying to call the fetchBalance method in one of them, the API returns the balance to me normally, but when calling this same method in another account, it returns me a json with empty data, why does this happen? I checked the Key / Secret / Phrase API and it is correct, because I am getting the status 200000

- OS: CentOS 7
- Programming Language version: JavaScript
- CCXT version: 1.28.95

```
async getBalance() {
        let balance = []
        try {
            balance = await this.kucoin.fetchBalance()
        } catch (e) {
            let error = {
                error: this.extractErrorMessage(e.message)
            }
            return error
        }
        return balance
    }
```

```
{ info: { code: '200000', data: [] },
  free: {},
  used: {},
  total: {} }
```

**Comment by kroitor** [comment]
Hi! Have you deposited to the "empty" account?

**Comment by viniciussvl** [comment]
Wonderful, that was it! What a silly mistake, I apologize. You can close this issue, if someone "gets it wrong" like me, you will find this topic haha
