### ISSUE TITLE
Binance watch_order_book not updated in throttling mode

### ISSUE THREAD

**Issue by noel45** [ccxt/ccxt#7119]
Hi,

I noticed that Binance order book seems never updated after calling the first await watch_order_book.

exchange.orderbooks[mh.market]['bids'] => always showing the same result.

Digging into the code, i added the following debug lines :

```
    def handle_order_book_message(self, client, message, orderbook):
        u = self.safe_integer(message, 'u')
        self.handle_deltas(orderbook['asks'], self.safe_value(message, 'a', []))
        self.handle_deltas(orderbook['bids'], self.safe_value(message, 'b', []))
        orderbook['nonce'] = u
        timestamp = self.safe_integer(message, 'E')
        orderbook['timestamp'] = timestamp
        orderbook['datetime'] = self.iso8601(timestamp)

        print("#########################################################")
        print("Message (Bids update)")
        print(list(reversed(self.safe_value(message, 'b', []))))
        print("BIDS After updates")
        print(orderbook['bids']._index)
        print(orderbook['bids'])
```

The result of  `print(orderbook['bids']._index)` is correct. 
But the result of `print(orderbook['bids'])` is always equal to the first call, never being updated.

Here is an example :

#########################################################
Message received on WS (Bids update)

[**['9409.69', '6.909']**, ['9408.87', '0.056'], ['9408.82', '0.855'], ['9408.73', '0.100'], ['9408.70', '0.000'], ['9408.69', '0.000'], ['9408.59', '0.000'], ['9408.25', '0.419'], ['9404.50', '0.000'], ['9399.61', '1.000']]

BIDS After updates

{**9409.69: 6.909**, 9408.87: 0.056, 9408.5 .....   => **orderbook['bids']._index OK Qty matching 9409.09 is 6.909, as reflected in the bids update received on the WS**

[**[9409.69, 1.609]**, [9409.01, 0.999], [9408.87, 0.056], [9408.74, 0.5] ...  => **orderbook['bids'] KO : Qty matching 9409.69 is still 1.609, as it was set originally when receiving the first snapshot**

I can work around calling the "._index" but that does not seems expected ?

Thanks for your advice,
Noel

**Comment by kroitor** [comment]
@noel45 hi! Can you please paste your full verbose output to https://gist.github.com/ ? We will get this resolved.

**Comment by noel45** [comment]
Here :

https://gist.github.com/noel45/7f06e9906a47dcaf6ef3eaa4a0c9744a

**Comment by kroitor** [comment]
@noel45 there's a synchronization procedure that will not update the orderbook, until it is in sync. When the snapshot is received – the messages get rolled over the snapshot, taking the nonce into the account.

> Here: https://gist.github.com/noel45/7f06e9906a47dcaf6ef3eaa4a0c9744a

↑ That is not verbose output, please read this very carefully: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by kroitor** [comment]
@noel45 your awaiting-watching code (without edits to CCXT / CCXT Pro) would also help speed up resolving the issue.

**Comment by kroitor** [comment]
@noel45 your code should look like this:

```Python
# -*- coding: utf-8 -*-

import asyncio
import ccxtpro


async def loop(exchange, symbol):
    while True:
        try:
            orderbook = await exchange.watch_order_book(symbol)
            now = exchange.milliseconds()
            print(exchange.iso8601(now), symbol, orderbook['asks'][0], orderbook['bids'][0])
        except Exception as e:
            print(str(e))
            # raise e  # uncomment to break all loops in case of an error in any one of them
            # break  # you can also break just this one loop if it fails


async def main():
    exchange = ccxtpro.binance({'enableRateLimit': True})
    await exchange.load_markets()
    exchange.verbose = True  # ←--------------- after loading the markets
    symbol = 'YOUR_SYMBOL_HERE'  # ←------- change for your symbol
    await loop(exchange, symbol)
    await exchange.close()


if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

**Comment by noel45** [comment]
My current code :

```
import ccxtpro
import asyncio


class TestIssueBinance:

    async def run(self, loop):

        exchange_class = getattr(ccxtpro, "binance")
        exchange = exchange_class({'enableRateLimit': True, 'options': {'defaultType': 'future'}, 'asyncio_loop': loop})
        await exchange.watch_order_book("BTC/USDT")

        while True:
            print(exchange.orderbooks["BTC/USDT"]['bids'])
            await asyncio.sleep(1)


if __name__ == '__main__':
    p = TestIssueBinance()
    main_loop = asyncio.new_event_loop()
    main_loop.run_until_complete(p.run(main_loop))
```

**Comment by kroitor** [comment]
@noel45 you forgot to `limit` the orderbook on each iteration, this is why _index is fine, but not the offloaded orderbook. This is documented in the CCXT Pro Manual:

- https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual#real-time-vs-throttling

**Comment by kroitor** [comment]
@noel45 try this:

```Python
import ccxtpro
import asyncio


class TestIssueBinance:

    async def run(self, loop):

        exchange_class = getattr(ccxtpro, "binance")
        exchange = exchange_class({'enableRateLimit': True, 'options': {'defaultType': 'future'}, 'asyncio_loop': loop})
        await exchange.watch_order_book("BTC/USDT")

        while True:
            orderbook = exchange.orderbooks["BTC/USDT"].limit(1000)
            print(orderbook['bids'])
            await asyncio.sleep(1)


if __name__ == '__main__':
    p = TestIssueBinance()
    main_loop = asyncio.new_event_loop()
    main_loop.run_until_complete(p.run(main_loop))
```

**Comment by noel45** [comment]
Working like a charm.

Many Thanks !

**Comment by kroitor** [comment]
@noel45 cheers!

**Comment by kroitor** [comment]
@noel45 

P.S. for that reason we always ask for your code + your verbose output (make sure to post that if you have further difficulties).

**Comment by noel45** [comment]
Noted, sure
