### ISSUE TITLE
About `symbol` of futures markets

### ISSUE THREAD

**Issue by lyn716** [ccxt/ccxt#7122]
> Symbols are common across exchanges which makes them suitable for arbitrage and many other things.

In the [Docs](https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids), I found the difference between `symbol` and `id` of `market`. But in my experience, many ccxt exchange's futures `market` have the same `symbol` as `id` in code base, and do not have a standard form like `BTC-USD-200925`. Does ccxt have a plan to unify them ? Or some background history I missed. Thanks.

**Comment by kroitor** [comment]
> Does ccxt have a plan to unify them ? Or some background history I missed.

In short, yes. See these issues for details:

- https://github.com/ccxt/ccxt/issues/6697
- https://github.com/ccxt/ccxt/issues/3540
- https://github.com/ccxt/ccxt/issues/4834

Let us know if that does not answer your question.
