### ISSUE TITLE
binance STOP_LOSS_MARKET is not a valid order type in spot market BTC/USDT

### ISSUE THREAD

**Issue by cadmufasa** [ccxt/ccxt#7128]
Hi,

I made a small modification to the code: 
https://github.com/ccxt/ccxt/blob/master/examples/py/binance-test-order.py

Changes are below.

When running with a type of **STOP_LOSS_LIMIT**, it **works**

When running with a type of **STOP_LOSS_MARKET**, I **get the error** listed above.

Why is this the case?

TIA

```
exchange = ccxt.binance({
    'apiKey': LD_API_KEY,
    'secret': LD_API_SECRET,
    'enableRateLimit': True,
})
```

```
symbol = 'BTC/USDT'
type   = 'STOP_LOSS_MARKET'    # or 'market'
side   = 'sell'         # or 'buy'
amount = .0015
price  =  9400 # the price I want to buy at

# extra params and overrides if needed
params = {
    'test': True,       # test if it's valid, but don't actually place it
    'timeInForce': 'GTC',
    'stopPrice': 9500,    # if price gets to this point, then just get rid of it
}

try:
    order = exchange.createOrder(symbol, type, side, amount, price, params)
    print(order)

except Exception as e:
    print ( " exception just occurred" )
    print ( e.args )


```

**Comment by kroitor** [comment]
Hi!

This was answered here:

- https://github.com/ccxt/ccxt/issues/7121
- https://github.com/ccxt/ccxt/issues/7121#issuecomment-643811037

Let us know if it does not answer your questions.

**Comment by cadmufasa** [comment]
Hi Kroitor and thanks for the response.

Forgive me if my questions seem "basic" below as I am new to the mechanics of proper trade execution ...

The only "markets" I am looking to work with are SPOT and MARGIN.

For **STOP_LOSS_LIMIT**, when Price gets to (or reaches) the stopPrice, a LIMIT order is issued (this is my understanding).



**=> QUESTION 1**

From what I have seen,
-> For POST /fapi/v1/order (HMAC SHA256), this endpoint is associated with the SPOT market

When one is creating an order, how can they tell if the ENDPOINT being used during the creation process is for the SPOT market, the MARGIN market or the FUTURE market (I have seen "exchange.createOrder" and "exchange.create_order" when placing a new order on an exchange?

**=> QUESTION 2**

For the code above, I changed the type from **STOP_LOSS_LIMIT** to: **STOP_LOSS** (my wish was to have a **MARKET** order execute **when the stopPrice is reached** )

**STOP_LOSS** is mentioned in this documentation: https://binance-docs.github.io/apidocs/spot/en/#new-order-trade

When doing so, I got the following message: "**binance STOP_LOSS is not a valid order type in spot market BTC/USDT**"

Is there something that I am missing?

TIA

**Comment by kroitor** [comment]
Hi @cadmufasa !

Answering your questions separately below:

> **=> QUESTION 1**
> 
> From what I have seen,
> -> For POST /fapi/v1/order (HMAC SHA256), this endpoint is associated with the SPOT market

That is a wrong assumption on your side. In `/fapi/v1/order` – the `fapi` stands for Futures API. That is for the futures markets, not for spot/margin orders.

> When one is creating an order, how can they tell if the ENDPOINT being used during the creation process is for the SPOT market, the MARGIN market or the FUTURE market (I have seen "exchange.createOrder" and "exchange.create_order" when placing a new order on an exchange?

They can tell that from the endpoint that is being used to submit an order:

----

**SPOT**

- https://binance-docs.github.io/apidocs/spot/en/#new-order-trade

![Screen-Shot-2020-06-16-at-07 04 00](https://user-images.githubusercontent.com/1294454/84730724-ad471880-af9f-11ea-824b-cb965cdfe5ad.jpg)

```Python
import ccxt
from pprint import pprint
exchange = ccxt.binance({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
exchange.load_markets()
symbol = 'BTC/USDT'
market = exchange.market(symbol)
print('Order types support by the', symbol, 'spot market:')
pprint(market['info']['orderTypes'])
```

----

**MARGIN**

- https://binance-docs.github.io/apidocs/spot/en/#margin-account-new-order-trade

![Screen-Shot-2020-06-16-at-07 02 06](https://user-images.githubusercontent.com/1294454/84730650-74a73f00-af9f-11ea-84fe-e76637ca5fba.jpg)

```Python
import ccxt
from pprint import pprint
exchange = ccxt.binance({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'options': {
        'defaultType': 'margin',
    }
})
exchange.load_markets()
symbol = 'BTC/USDT'
market = exchange.market(symbol)
print('Order types support by the', symbol, 'margin market:')
pprint(market['info']['orderTypes'])
```

----

**FUTURES**

- https://binance-docs.github.io/apidocs/futures/en/#new-order-trade

![Screen-Shot-2020-06-16-at-06 58 18](https://user-images.githubusercontent.com/1294454/84730556-1da16a00-af9f-11ea-91bb-430184fb364c.jpg)

```Python
import ccxt
from pprint import pprint
exchange = ccxt.binance({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'options': {
        'defaultType': 'future',
    }
})
exchange.load_markets()
symbol = 'BTC/USDT'
market = exchange.market(symbol)
print('Order types support by the', symbol, 'futures market:')
pprint(market['info']['orderTypes'])
```

**Comment by kroitor** [comment]
> **=> QUESTION 2**
> 
> For the code above, I changed the type from **STOP_LOSS_LIMIT** to: **STOP_LOSS** (my wish was to have a **MARKET** order execute **when the stopPrice is reached** )
> 
> **STOP_LOSS** is mentioned in this documentation: https://binance-docs.github.io/apidocs/spot/en/#new-order-trade
> 
> When doing so, I got the following message: "**binance STOP_LOSS is not a valid order type in spot market BTC/USDT**"
> 
> Is there something that I am missing?

Yes, you're missing the fact that some markets might not support all types of orders, and to see which order types are supported for spot BTC/USDT, you can run this code:

```Python
import ccxt
from pprint import pprint
exchange = ccxt.binance({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
markets = exchange.load_markets()
symbol = 'BTC/USDT'
market = exchange.market(symbol)
print('Order types support by the', symbol, 'spot market:')
pprint(market['info']['orderTypes'])
```

Output:

```
mbp:python igorkroitor$ python3
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> from pprint import pprint
>>> exchange = ccxt.binance({
...     'enableRateLimit': True,
...     'apiKey': 'YOUR_API_KEY',
...     'secret': 'YOUR_SECRET',
... })
>>> markets = exchange.load_markets()
>>> symbol = 'BTC/USDT'
>>> market = exchange.market(symbol)
>>> print('Order types support by the', symbol, 'spot market:')
Order types support by the BTC/USDT spot market:
>>> pprint(market['info']['orderTypes'])
['LIMIT', 'LIMIT_MAKER', 'MARKET', 'STOP_LOSS_LIMIT', 'TAKE_PROFIT_LIMIT']
>>>
```

**Comment by kroitor** [comment]
@cadmufasa The above is the data coming from Binance itself. Hope it answers your questions, let us know if not. If you think that STOP_LOSS should be there for spot BTC/USDT – i'd recommend to reach out to Binance tech support with this question.

**Comment by kroitor** [comment]
@cadmufasa 

P.S.

You can control which order (futures, margin or spot) will be created by createOrder as follows:

```Python
import ccxt
from pprint import pprint
exchange = ccxt.binance({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
exchange.load_markets()
symbol = 'BTC/USDT'
type = 'YOUR_TYPE_HERE',
side = 'buy'  # or sell, or whatever is supported
amount = 123.45
price = 54.321  # or None in case of market orders
params = {
    # 'stopPrice': 123.45  # if any
}
order = exchange.create_order(symbol, type, side, amount, price, params)
```

**Comment by cadmufasa** [comment]
Hi kroitor,

Thanks for the info!

Regards.
