### ISSUE TITLE
Contract unification suggestion

### ISSUE THREAD

**Issue by monk-after-90s** [ccxt/ccxt#7129]
Thanks for guiding me to regard a 'BTC/USD' contract as one thing called "BTC/USD" instead of a pair of something. I have something ideas about unification about the unification of contracts orders, which maybe could be extended to the scope of leverage.

For simplification, lets say such a kind of contract, 'BTCUSD', whose value is expressed as 'BTC', which means that one contract could be compared to one BTC, while the profit is calculated in USD. To talk about the margin, I prefer it to be freed back to the wallet after the position is closed then the profit of the position is transfered across the wallet which is mostly be no more than the margin because of the burst mechanism. So I think the margin is always in the account. 

As when a contract is just opened, the price of the market is just the price where the contract is targeted lets say 9000, I prefer the 'price' or 'average' to be  0, the 'filled' 1 for buy contract and -1 for sell contract, for simplification, then 'cost' 0. Please note, I am not talking about the position but the order. 

The previous order produced one asset which valued 0, the only influence is that some currencies in your wallet is freezed for margin, but not gone. When the asset is exchanged in the market(position or contract closed ), lets say it is targeted at price 8000, the result is processed by another order, a new order will do this and this order which closes positions has a 'average' different from 0! This order will has a 'filled' of 1 for buy contract and -1 for sell contract, 'average' of 8000-9000=-1000, so the cost will be -1000 for buy contract and 1000 for sell contract.

To be simple, the closed order to open contract positions values 0 while the closed order to close contract position values positive or negative or 0 if any. 

Wish for reply.

**Comment by kroitor** [comment]
@monk-after-90s I suggest to move this discussion to [this issue](https://github.com/ccxt/ccxt/issues/4834) just to keep things sorted. I've copied your post to it.
