### ISSUE TITLE
Quick Questions from post #7128 ( binance STOP_LOSS_MARKET is not a valid order type in spot market BTC/USDT)

### ISSUE THREAD

**Issue by cadmufasa** [ccxt/ccxt#7130]
Hi Kroitor and thanks for the response.

Forgive me if my questions seem "basic" below as I am new to the mechanics of proper trade execution ...

The only "markets" I am looking to work with are SPOT and MARGIN.

For **STOP_LOSS_LIMIT**, when Price gets to (or reaches) the stopPrice, a LIMIT order is issued (this is my understanding).

**=> QUESTION 1**

From what I have seen,
-> For POST /fapi/v1/order (HMAC SHA256), this endpoint is associated with the SPOT market

When one is creating an order, how can they tell if the ENDPOINT being used during the creation process is for the SPOT market, the MARGIN market or the FUTURE market (I have seen "exchange.createOrder" and "exchange.create_order" when placing a new order on an exchange?

**=> QUESTION 2**

For the code above, I changed the type from **STOP_LOSS_LIMIT** to: **STOP_LOSS** (my wish was to have a **MARKET** order execute **when the stopPrice is reached** )

**STOP_LOSS** is mentioned in this documentation: https://binance-docs.github.io/apidocs/spot/en/#new-order-trade

When doing so, I got the following message: "**binance STOP_LOSS is not a valid order type in spot market BTC/USDT**"

Is there something that I am missing?

TIA

_Originally posted by @cadmufasa in https://github.com/ccxt/ccxt/issues/7128#issuecomment-644515200_

**Comment by cadmufasa** [comment]
**EDITED TO ADD:**

Hi again, 

I found this information here:
https://github.com/ccxt/ccxt/wiki/Manual#api-methods--endpoints

I am thinking it may work. Wish me luck!

Regards.

**Comment by kroitor** [comment]
@cadmufasa plz don't duplicate issues, I've provided the answers in your original issue here: https://github.com/ccxt/ccxt/issues/7128
