### ISSUE TITLE
Can you post my icon in CCXT page  after receiving my Crypto donation?

### ISSUE THREAD

**Issue by kingwithsword** [ccxt/ccxt#7135]
Hi! 

Yes, those addresses are correct! Thank you for your support, we appreciate it!

_Originally posted by @kroitor in https://github.com/ccxt/ccxt/issues/7089#issuecomment-641326069_

I see the icons of whom made donation by USD in CCXT page.

I don't want to donate USD or  to use credit card.

I want to make Crypto donation . Can you post my icon in CCXT page  after receiving my Crypto donation?  If you can ,I  will greatly appreciate it!

Hope for your reply!
Thank you!

**Comment by kroitor** [comment]
Hi! Unfortunately, that section is only for the opencollective sponsors (we don't control the contents of that section, it is driven by opencollective). Hope for your understanding. Thx!

**Comment by kingwithsword** [comment]
> Hi! Unfortunately, that section is only for the opencollective sponsors (we don't control the contents of that section, it is driven by opencollective). Hope for your understanding. Thx!

I know that you use the API of opencollective (USD donator).
But , I mean you can create a section(<div>) where the Crypto donators will be listed (if they want).

To make a new section ( <div>) is not difficult, you can operate it manually.

Hope for your reply!
Thank you!

**Comment by kroitor** [comment]
@kingwithsword sorry, but this is not a voluntary donation, if you want to get a link back to you. Ethically, a donation is when you support the project and the developer team – in that case you don't ask anything in return and the donations are anonymous. However, if you wish to get a link back to you in return for your crypto – that is not a donation anymore. That is a commercial relationship, or a sponsorship, and if you wish to have sponsored links the CCXT project, you can reach out to us at info@ccxt.trade.

**Comment by kingwithsword** [comment]
> @kingwithsword sorry, but this is not a voluntary donation, if you want to get a link back to you. Ethically, a donation is when you support the project and the developer team – in that case you don't ask anything in return and the donations are anonymous. However, if you wish to get a link back to you in return for your crypto – that is not a donation anymore. That is a commercial relationship, or a sponsorship, and if you wish to have sponsored links with the CCXT project, you can reach out to us at [info@ccxt.trade](mailto:info@ccxt.trade).

Unfortunately, you mistake my meaning.
Donation can be anonymous or real named (Charity ,University foundation)

I don't request link back. I just want my icon(not commercial brand) listed.
I think it's honor.It is like Medal.
I like honor. Is that right?

Hope for your reply!
Thank you!
