### ISSUE TITLE
Kucoin API AuthenticationError: KC-API-KEY not exists

### ISSUE THREAD

**Issue by tumjiradet** [ccxt/ccxt#7139]
Hi, please help me to understand and fix it.

- OS: Window 
- Programming Language version: python 3.7
- CCXT version: 1.30.11

```
!pip install ccxt
!pip install pandas
import ccxt
import json
import pandas as pd
apiKey = " xxxx  "
secret = " xxxx "
passWord = "xxxx"
kucoin1 = ccxt.kucoin({
    'apiKey': apiKey ,
    'secret': secret ,
    'password' : passWord , 'enableRateLimit': True })
print("Port balance =",kucoin1.fetch_balance())
response = kucoin1.create_order('XRP/USDT' ,'limit' , 'buy' , 1 , 0.1800)
```

```
print("Port balance =",kucoin1.fetch_balance())
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-bf0fe0972098> in <module>()
      1 # ตรวจเช๊ค Balance ของ port
----> 2 print("Port balance =",kucoin1.fetch_balance())

NameError: name 'kucoin1' is not defined

response = kucoin1.create_order('XRP/USDT' ,'limit' , 'buy' , 1 , 0.1800)
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py in fetch(self, url, method, headers, body)
    579             self.logger.debug("%s %s, Response: %s %s %s", method, url, http_status_code, headers, http_response)
--> 580             response.raise_for_status()
    581 

8 frames
HTTPError: 401 Client Error:  for url: https://openapi-v2.kucoin.com/api/v1/orders

During handling of the above exception, another exception occurred:

AuthenticationError                       Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py in throw_exactly_matched_exception(self, exact, string, message)
    497     def throw_exactly_matched_exception(self, exact, string, message):
    498         if string in exact:
--> 499             raise exact[string](message)
    500 
    501     def throw_broadly_matched_exception(self, broad, string, message):

AuthenticationError: KC-API-KEY not exists
```

**Comment by kroitor** [comment]
> AuthenticationError: KC-API-KEY not exists

That exception means, that you're using a wrong API key. 

All exceptions are described here:

- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

Check your API keypair against KuCoin's website or make a new API keypair. Make sure you don't confuse the API Key with the API secret (sometimes people can misplace the two settings). Also, make sure that you don't have any typos and all symbols are there. The `apiKey` must be a string of 24 symbols and the `secret` must be a string of 36 symbols. Check the password as well. Make sure you don't confuse a sandbox/testnet API keypair with the actual trading API keypair. If you want to use a sandbox/testnet API keypair, you also have to set the sandbox mode on the exchange class instance.

Try this short snippet (make sure there's no other code, and edit for your keys below)

```Python
!pip install ccxt
import ccxt
from pprint import pprint
exchange = ccxt.kucoin({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
    'password': 'YOUR_API_PASSPHRASE',
    'enableRateLimit': True,
})
#  exchange.set_sandbox_mode(True)  # uncomment if you're using a sandbox keypair
balance = exchange.fetch_balance()
pprint(balance)
```

Let us know if that does not help or does not answer your question.

If you're still having difficulties after trying the above short snippet, please, enable verbose mode and paste the following information (your complete code snippet, your verbose request+response and the full error stack):

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by tumjiradet** [comment]
Done, Thank you kroitor.
