### ISSUE TITLE
Liquid private_put_trades not working

### ISSUE THREAD

**Issue by RetGal** [ccxt/ccxt#7140]
Calling liquids endpoint ```PUT /trades/:id``` results in an ```AttributeError```

- OS: Linux
- Programming Language version: Python 3.7
- CCXT version: 1.30.6

```
EXCHANGE.private_put_trades({'stop_loss': stop_loss_price})[id]
```

```
AttributeError: 'liquid' object has no attribute 'private_put_trades'
```

**Comment by kroitor** [comment]
There's no such method as private_put_trades in Liquid:

- https://github.com/ccxt/ccxt/wiki/Manual#api-method-naming-conventions

To see all methods:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

```Python
import ccxt
from pprint import pprint
pprint(dir(ccxt.liquid()))
```

```Python
EXCHANGE.private_put_trades_id({
    'id': 'YOUR_TRADE_ID_HERE',
    # other params...
})
```

Let us know if that does not answer your question.

**Comment by RetGal** [comment]
Oops, sorry & thanks!
