### ISSUE TITLE
ccxtpro watch_order_book from asyncio create_task

### ISSUE THREAD

**Issue by neuro777** [ccxt/ccxt#7141]
- macOS:
- python 3.6:
- CCXT version: ccxtpro 0.2.58 / ccxt 1.30.5

The python example works for me here: https://ccxt.pro.

However, I am just getting a feel for how to use/integrate it into my work, but when I slightly modify it by spawning it as a task rather than running it within the main loop it doesn't work. I'm not a highly experienced programmer so I'm probably doing something very wrong but just wanted to check in with the experts to see if this should/shouldn't work.  I've structured other parts of my programs launching tasks like this, so I'm unclear why it's behaving like this. I expect it to work more or less exactly the same as the python example on the ccx.pro website. No order book data is output, the loop prematurely terminates.

```
import ccxtpro
import asyncio

async def spawnExchange():
    exchange = ccxtpro.bittrex({'enableRateLimit': True})
    exchange.verbose = True
    while True:
        orderbook = await exchange.watch_order_book('ETH/BTC')
        print(orderbook['asks'][0], orderbook['bids'][0])
        
async def main():
    loop = asyncio.get_event_loop()
    loop.create_task(spawnExchange())

asyncio.get_event_loop().run_until_complete(main())
```

```
Process finished with exit code 0
```

**Comment by kroitor** [comment]
This is not really a question about CCXT Pro, but more like a question on how to use Python and asyncio tasks. You simply forgot to await for your task...

```Python
import ccxtpro
import asyncio

async def spawnExchange(loop):
    exchange = ccxtpro.bittrex({
        'enableRateLimit': True,
        'asyncio_loop': loop,
    })
    # exchange.verbose = True
    while True:
        orderbook = await exchange.watch_order_book('ETH/BTC')
        print(orderbook['asks'][0], orderbook['bids'][0])

async def main(loop):
    await loop.create_task(spawnExchange(loop))

loop = asyncio.get_event_loop()
loop.run_until_complete(main(loop))
```

↑ Let us know if that does not answer your question.

**Comment by kroitor** [comment]
P.S. Alternatively, you can use `wait()` to await for multiple tasks at once as shown, for example, here: https://github.com/ccxt/ccxt/blob/master/examples/py/async-gather-concurrency.py

**Comment by neuro777** [comment]
I don't typically await the create_tasks as I want the program to continue uninterrupted and run them in parallel. This has worked well, but its possible it's a bad practice the way I've been structuring it. There are times where I do want to await and specify as such by adding await. It wasn't forgetting, more accurately perhaps it's a misunderstanding of how it works. I want to 'await' exchange.watch_order_book, not the entire spawnExchange(), so while this may work it will conflict with how I am doing things presently. I'll study this more. Thank you for your insight.

**Comment by kroitor** [comment]
@neuro777 in general, if you're running multiple parallel tasks you can use `asyncio.gather()` or `asyncio.wait()`, but again, it's more up to you how you want to structure your code, CCXT Pro basically allows you to do it any way you would do this with any other task or a set of tasks.
