### ISSUE TITLE
node ccxt 

### ISSUE THREAD

**Issue by avcilar73** [ccxt/ccxt#7142]
node ccxt btctürk api error

**Comment by kroitor** [comment]
They have changed their API.

For the future: 

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by kroitor** [comment]
P.S. btcturk v2 API is available for testing here: https://github.com/ccxt/ccxt/pull/6945

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/6598
