### ISSUE TITLE
Unable to resolve buffer in react-native

### ISSUE THREAD

**Issue by marcelcure** [ccxt/ccxt#7145]
- OS: Debian
- Programming Language version: react-native 0.62.2
- CCXT version: 1.30.12

```
All you need to do is to initialise a new react-native project e.g. react-native init dummy and then include "ccxt": "^1.30.12" as a dependency in package.json, add these lines to App.js 


const ccxt = require('ccxt');

const {
  numberToString,
  decimalToPrecision,
  ROUND,
  TRUNCATE,
  DECIMAL_PLACES,
  TICK_SIZE,
  PAD_WITH_ZERO,
  SIGNIFICANT_DIGITS,
} = require('ccxt');

and then npm update and react-native run-android.

```

```
Message:-  "node_modules/ccxt/js/static_dependencies/BN/bn.js", "targetModuleName": "buffer".... "buffer" could not be found within the project.

```
Same problem if I npm install buffer

```

```
Message:-  "node_modules/ccxt/js/static_dependencies/BN/bn.js", "targetModuleName": "buffer".... "buffer" could not be found within the project.

```
Same problem if I npm install buffer

**Comment by marcelcure** [comment]
![ccxt_1 30 12_unable_to_resolve_buffer](https://user-images.githubusercontent.com/3610374/84949171-b988be00-b0e4-11ea-9b17-21170b9821cf.png)

**Comment by marcelcure** [comment]
![ccxt_1 30 12_unable_to_resolve_buffer](https://user-images.githubusercontent.com/3610374/84949294-e8069900-b0e4-11ea-811d-4fb71621ca8f.png)

**Comment by kroitor** [comment]
@marcelcure this is not a question about CCXT usage, but more like a question on how to configure your react-native package. Make sure you properly configure your react-native packaging to transpile the `buffer` module and polyfill any other node-specific modules, that might be missing on the browser-side:

- https://www.google.com/search?q=react-native+unable+to+resolve+buffer

Duplicates:

- https://github.com/ccxt/ccxt/issues/5589
- https://github.com/ccxt/ccxt/issues/3711
- https://github.com/ccxt/ccxt/issues/3679
- https://github.com/ccxt/ccxt/issues/606

Let us know if the above does not help.

**Comment by marcelcure** [comment]
Thank you. I had simply forgotten to import my shim - I had in fact made these steps before but it slipped my mind. Sorry to bother you.
