### ISSUE TITLE
Custom RateLimiter for BitMEX

### ISSUE THREAD

**Issue by enriquepiatti** [ccxt/ccxt#7150]
BitMEX has a rate limit of 60 requests per minute, but this is not the same as 1 request per second, it allows you to make 60 requests in just 1 second (not so sure about this, I think it has a limit also of 500ms for every consecutive request). 

Is there any way to configure a correct RateLimiter for BitMEX without extra code?
What I want to do:
1) Every request must be delayed at least 500ms from previous request (I think this is possible just adding rateLimit = 500)
2) If in the previous 60 seconds there were 60 (maybe 59) requests, then the next request must be delayed 1000ms (not 500).

If it's not possible to configura that, can you point me in the best direction to do it myself?
Thanks !!

**Comment by kroitor** [comment]
Please, check out the following issues:

- https://github.com/ccxt/ccxt/issues/5152
- https://github.com/ccxt/ccxt/issues/1399#issuecomment-359233015
- https://github.com/ccxt/ccxt/issues/5565#issuecomment-513635562

Let us know if the above does not answer your question.

**Comment by enriquepiatti** [comment]
I've read all that but is not clear to me, maybe is possible to do it with tokenBucket? but i couldn't find any documentation about it, not sure how to use it.   
I was thinking in overriding the throttle function, but maybe is better if CCXT supports that natively.
Do you think is possible to configure Bitmex RateLimits properly with CCXT?
This is probably a very common requirement so could be useful to leave here some example as a reference.

**Comment by kroitor** [comment]
> I've read all that but is not clear to me, maybe is possible to do it with tokenBucket?

Yes, it is possible to do it with the existing tokenBucket implementation in CCXT.

> but i couldn't find any documentation about it, not sure how to use it.

It is not documented yet (for advanced users only) – you will have to read the source code of the `throttle()` function and pass the proper config to it via exchange properties.

> I was thinking in overriding the throttle function, but maybe is better if CCXT supports that natively.

It already does support it natively, and you can also create your own override as well.

> Do you think is possible to configure Bitmex RateLimits properly with CCXT?

Yes, but that will require some investigation on your side.

> This is probably a very common requirement so could be useful to leave here some example as a reference.

It's not very easy to do it in a unified way for all exchanges, but for your specific case it shouldn't be a big problem.

**Comment by enriquepiatti** [comment]
OK, I will check the code later if I have more time, because was a bit confusing for me at first sight.
Until then I will use this override just in case is useful for someone else:

```
    let lastRequestTime = Date.now();
    const requestsPerMinute = 60;
    const requestTimesHistory = [];
    const throttle = async function(rateLimit){
        let now = Date.now();

        if(requestTimesHistory.length > requestsPerMinute){
            const prevMinute = now - 60*1000;
            while( requestTimesHistory.length && requestTimesHistory[0] < prevMinute ){
                requestTimesHistory.shift();                
            }
            if(requestTimesHistory.length > requestsPerMinute){
                rateLimit = 1000;
            }
        }
        
        const dif = (now - lastRequestTime);
        if(dif < rateLimit){
            await sleep(rateLimit-dif);
            now = Date.now();
        }
        
        lastRequestTime = Date.now();
        requestTimesHistory.push(lastRequestTime);
    };
    exchange.throttle = throttle;
```
