### ISSUE TITLE
[bittrex] v3 api officially released

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#7151]
https://github.com/Bittrex/bittrex.github.io/issues/114#issuecomment-646221261

**Comment by npomfret** [comment]
Is anyone working on a bittrex-v3 rest rewrite?

@otschek @azharuniverse  @hroff-1902 @Corfucinas  @dmnode  @TheSkynet1337

**Comment by BlueSkyTrading** [comment]
Here is the error message I get when I try to download 1d data:
`WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair DGB/BTC due to ExchangeNotAvailable. Message: GET https://api.bittrex.com/v3/markets/DGB-BTC/candles/DAY_1/historical/2020/5/20 400 Bad Request {"code":"INVALID_DATE"}"`

**Comment by kroitor** [comment]
@BlueSkyTrading yeah, what's interesting is that some timeframes+dates work, but not the others

- https://global.bittrex.com/v3/markets/DGB-BTC/candles/HOUR_1/historical/2020/05
- https://global.bittrex.com/v3/markets/DGB-BTC/candles/DAY_1/historical/2020/05
- https://global.bittrex.com/v3/markets/DGB-BTC/candles/DAY_1/historical/2020
- https://global.bittrex.com/v3/markets/DGB-BTC/candles/DAY_1/historical/2019
- https://global.bittrex.com/v3/markets/DGB-BTC/candles/DAY_1/recent

**Comment by kroitor** [comment]
@npomfret they could've documented the API properly at least before releasing it %)

**Comment by kroitor** [comment]
@BlueSkyTrading we will add the workarounds for that as soon as we can

**Comment by BlueSkyTrading** [comment]
@kroitor , perfect, thank you!

**Comment by noahfigueras** [comment]
Hi there,

Is this issue already solved ? I keep getting the same INVALID_DATE error.

Thanks!

**Comment by kroitor** [comment]
@noahfigueras hi! If you mean fetchOHLCV – that's a different issue: https://github.com/ccxt/ccxt/issues/7317
We will fix it within a day or two.

**Comment by amalcaraz** [comment]
It seams that bittrex is going to stop supporting the v1.1 API in September. Are you going to migrate the current implementation to fully support v3?

**Comment by kroitor** [comment]
@amalcaraz yes

**Comment by carloconnor** [comment]
Hi,

I was wondering if you still planned to migrate the current bittrex implementation to v3 before v1.1 gets deprecated on Sep 30th?

Thanks!

**Comment by amalcaraz** [comment]
There is a pull request waiting to be reviewed and merged
https://github.com/ccxt/ccxt/pull/7519

I would like to know too if this is going to be ready before they deprecate the version 1.1 please
