### ISSUE TITLE
Binance exchange header missing

### ISSUE THREAD

**Issue by canerd7u** [ccxt/ccxt#7159]
Listening key is taken to receive user instant notifications in **UserDataStream** method in binance exchange. Then we can get notifications by connecting to the socket with the key. When used with ccxt, it is insufficient to receive return key notifications. According to my researches, **X-MBX-APIKEY** key should be added to the ccxt header. When I test with the codes below, this value does not appear in the header section.

```
var exchange = new ccxt.binance({
    'apiKey': 'xxxxxxxxxxxxx',
    'secret': 'xxxxxxxxxx'
});

exchange.headers = {
    'X-MBX-APIKEY' : 'xxxxxxx'
};

exchange.sapiPostUserDataStream().then(r => {

    console.log("listen key " , r.listenKey);

    console.log("last_response_headers" , exchange.last_response_headers);

});
```

Response

```
listen key  xxxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx
last_response_headers {
  'Access-Control-Allow-Methods': 'GET, HEAD, OPTIONS',
  'Access-Control-Allow-Origin': '*',
  'Cache-Control': 'no-cache, no-store, must-revalidate',
  Connection: 'keep-alive',
  'Content-Length': '76',
  'Content-Security-Policy': "default-src 'self'",
  'Content-Type': 'application/json;charset=UTF-8',
  Date: 'Fri, 19 Jun 2020 20:28:45 GMT',
  Expires: '0',
  Pragma: 'no-cache',
  Server: 'nginx',
  'Strict-Transport-Security': 'max-age=31536000; includeSubdomains',
  Via: '1.1 5317564e96c9dceb46123f6c5f149a03.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'L9CjbvRnXtNhWlvy1pWXz5MIY5WyJQdapVGVUFxu1xZ-mnXl8O_Eg==',
  'X-Amz-Cf-Pop': 'FRA50-C1',
  'X-Cache': 'Miss from cloudfront',
  'X-Content-Security-Policy': "default-src 'self'",
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Webkit-Csp': "default-src 'self'",
  'X-Xss-Protection': '1; mode=block'
}
```

- OS: Windows 10
- Programming Language version: Javascript
- CCXT version: 1.25.89

**Comment by kroitor** [comment]
@canerd7u 

1. You're confusing HTTPS request headers (from you to Binance) with HTTPS response headers (from Binance to you).
2. CCXT does handle the headers properly.
3. The `X-MBX-APIKEY` header is a part of request headers, not response headers.
4. You can use the verbose mode to verify which headers are sent from you towards the exchange, this is documented in the Manual.
5. If you print out `last_response_headers` – you're printing the response headers from Binance to you – that is not how you verify that.
6. CCXT already does handle the authentication and headers for you as described in the Manual.

Proper code to see your desired headers:

```JavaScript
var exchange = new ccxt.binance ({
    'apiKey': 'xxxxxxxxxxxxx',
    'secret': 'xxxxxxxxxx'
    'enableRateLimit': true, // required by the Manual
    'verbose': true, // to see all requests and responses
});

exchange.sapiPostUserDataStream().then(r => {
    console.log("listen key " , r.listenKey);
});
```

I'd highly recommend to carefully read the Manual from top to bottom at least once – it will save you a ton of time.

Let us know if the above does not answer your question.
