### ISSUE TITLE
calculating lot size

### ISSUE THREAD

**Issue by speggos** [ccxt/ccxt#716]
Hello,

I'm getting the following error when trying to place a binance sell order:
raise InvalidOrder(self.id + ' order amount should be evenly divisible by lot size, use self.amount_to_lots(symbol, amount) ' + body)
ccxt.base.errors.InvalidOrder: binance order amount should be evenly divisible by lot size, use self.amount_to_lots(symbol, amount) {"code":-1013,"msg":"Filter failure: LOT_SIZE"}

However, I am unable to use the self.amount_to_lots() function. How do I access this?

Thank you!

**Comment by kroitor** [comment]
Hi!

> However, I am unable to use the self.amount_to_lots() function. How do I access this?

What do you mean, *unable*? Is there an invisible hand holding you off from calling that method? )

**Comment by speggos** [comment]
I'm unaware how to access the method. Since it is defined in the same file as createLimitSellOrder, I don't know why I'm getting this error:

AttributeError: 'binance' object has no attribute 'mount_to_lots'

when trying to call it like this:

binanceCcxt.mount_to_lots("ADA/ETH", quantity)

**Comment by kroitor** [comment]
The method is called `amount_to_lots`, not `mount_to_lots`...

**Comment by speggos** [comment]
Wow, I am unworthy. You're right there.

I'm slightly confused on how to use this method, is my problem

**Comment by kroitor** [comment]
> I'm slightly confused on how to use this method, is my problem

It returns a value truncated to lot sizes of Binance, so the value that you get from amount_to_lots should be passed further to createOrder in the amount argument.

**Comment by speggos** [comment]
Alright, so assuming I calculated quantity corectly, I'd simply call:

binanceCcxt.amount_to_lots("ADA/ETH", quantity)

which would return the quantity which I should place into creatLimitSellOrder?

**Comment by kroitor** [comment]
Yep, exactly)

**Comment by speggos** [comment]
Thank you! You are a gentleman and a scholar

**Comment by DaneJC** [comment]
Hi, 
is the amountToLots() method still active? When I try to use the method I get the follow error:

(rejection id: 1): TypeError: Cannot read property 'TRX/ETH' of undefined 

code:

let freeBalance = await getAvailibleBalanceETH();
let quantity = binance.amountToLots('TRXETH', freeBalance);
binance.createMarketBuyOrder(pairChar, quantity);

async function getAvailibleBalanceETH() 
{ 
	let balance = await binance.fetchBalance();
	let freeBalance = balance.ETH.free;
	return freeBalance;
}

If I'm missing something and you could steer me in the right direction to get my orders firing it would be great.. everything else works fine, sell orders execute.. I'm just having trouble with the buy orders quantity.

**Comment by kroitor** [comment]
> `binance.amountToLots('TRXETH', freeBalance);`

↑ But Binance does not have symbol `TRXETH` ) The correct symbol is `TRX/ETH`. The difference is [explained here](https://github.com/ccxt-dev/ccxt/wiki/Manual#symbols-and-market-ids). Does this help?

**Comment by kroitor** [comment]
@DaneJC check this out: `node examples/js/symbols binance`:

```
mbp:ccxt igorkroitor$ node examples/js/symbols binance
Instantiating binance exchange

Symbols:

limits          | precision       | tierBased | percentage | taker | maker | id       | symbol    | base  | quote | baseId | quoteId | info            | lot      | active
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
...
[object Object] | [object Object] | false     | true       | 0.001 | 0.001 | TRXBTC   | TRX/BTC   | TRX   | BTC   | TRX    | BTC     | [object Object] | 1        | true  
[object Object] | [object Object] | false     | true       | 0.001 | 0.001 | TRXETH   | TRX/ETH   | TRX   | ETH   | TRX    | ETH     | [object Object] | 1        | true  
...
---------------------------------------------------------------
```

**Comment by DaneJC** [comment]
wow quick response...
Oh that is a typeo wile writing that comment I normally have it in the params as a variable but retyped the symbol not to confuse you.

var pair='TRX/ETH';

 binance.amountToLots(pair, freeBalance)

Is the method still working?

How would you go about making a market buy order with binance?

**Comment by kroitor** [comment]
> Is the method still working?

If you have markets loaded, yes. In your case this is done implicitly in the `await binance.fetchBalance();` call, so everything should be ok. Let us know if not (however, please paste verbose output [as described here](https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue) for us to be able to help you).

> How would you go about making a market buy order with binance?

Well, I think, if I were to make a market order, I would read the [Manual: Market Orders](https://github.com/ccxt/ccxt/wiki/Manual#market-orders) first, of course (I always do that when I approach a task, you know ;)).
Then I would use `.createMarketBuyOrder (symbol, amount)`.
Let me know if you have any other questions )

**Comment by DaneJC** [comment]
After a break from the screen I have resolved the issue.
Thanks very much for you help.

**Comment by mortezae** [comment]
For current versions, for Binance you should use  amount_to_precision() instead.
(I use Javascript)
