### ISSUE TITLE
binance order cost = amount * price is zero or less {"code":-1013,"msg":"Price * QTY is zero or less."}

### ISSUE THREAD

**Issue by medozero** [ccxt/ccxt#7168]
- OS: WINDOWS 10 - 64
- Programming Language version:python
- CCXT version: 1.30.28

symbol:ETH-BTC   >> spot 

binance.createOrder(symbol,'limit','Sell',0.00013715435110890858,0.024752145000000003)

DEBUG:
Request: GET https://api.binance.com/api/v3/account?timestamp=1592764435100&recvWindow=50000&signature=XXXX{'X-MBX-APIKEY': 'XXXX', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} None
 POST https://api.binance.com/api/v3/order {'X-MBX-APIKEY': 'XXXX', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1592764435100&recvWindow=50000&symbol=ETHBTC&type=LIMIT&side=SELL&newOrderRespType=RESULT&quantity=0&price=0.024752&timeInForce=GTC&signature=XXXX

i don't know why the amount is always 0 even though i am hard coded the price 0.00013715435110890858

**Comment by kroitor** [comment]
> i don't know why the amount is always 0 even though i am hard coded the price 0.00013715435110890858

That is documented in the Manual, here:

- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

If you look into the ETH/BTC market, the amount precision is up to 3 decimal places:

```
mbp:ccxt igorkroitor$ python3 examples/py/cli.py binance market ETH/BTC
{'active': True,
 'base': 'ETH',
 'baseId': 'ETH',
 'future': False,
 'id': 'ETHBTC',
 'info': {'baseAsset': 'ETH',
          'baseAssetPrecision': 8,
          'baseCommissionPrecision': 8,
          'filters': [{'filterType': 'PRICE_FILTER',
                       'maxPrice': '100000.00000000',
                       'minPrice': '0.00000100',
                       'tickSize': '0.00000100'},
                      {'avgPriceMins': 5,
                       'filterType': 'PERCENT_PRICE',
                       'multiplierDown': '0.2',
                       'multiplierUp': '5'},
                      {'filterType': 'LOT_SIZE',
                       'maxQty': '100000.00000000',
                       'minQty': '0.00100000',
                       'stepSize': '0.00100000'},
                      {'applyToMarket': True,
                       'avgPriceMins': 5,
                       'filterType': 'MIN_NOTIONAL',
                       'minNotional': '0.00010000'},
                      {'filterType': 'ICEBERG_PARTS', 'limit': 10},
                      {'filterType': 'MARKET_LOT_SIZE',
                       'maxQty': '10326.05382802',
                       'minQty': '0.00000000',
                       'stepSize': '0.00000000'},
                      {'filterType': 'MAX_NUM_ALGO_ORDERS',
                       'maxNumAlgoOrders': 5},
                      {'filterType': 'MAX_NUM_ORDERS', 'maxNumOrders': 200}],
          'icebergAllowed': True,
          'isMarginTradingAllowed': True,
          'isSpotTradingAllowed': True,
          'ocoAllowed': True,
          'orderTypes': ['LIMIT',
                         'LIMIT_MAKER',
                         'MARKET',
                         'STOP_LOSS_LIMIT',
                         'TAKE_PROFIT_LIMIT'],
          'permissions': ['SPOT', 'MARGIN'],
          'quoteAsset': 'BTC',
          'quoteAssetPrecision': 8,
          'quoteCommissionPrecision': 8,
          'quoteOrderQtyMarketAllowed': True,
          'quotePrecision': 8,
          'status': 'TRADING',
          'symbol': 'ETHBTC'},
 'limits': {'amount': {'max': 100000.0, 'min': 0.001},
            'cost': {'max': None, 'min': 0.0001},
            'market': {'max': 10326.05382802, 'min': 0.0},
            'price': {'max': 100000.0, 'min': 1e-06}},
 'lowercaseId': 'ethbtc',
 'maker': 0.001,
 'margin': True,
 'percentage': True,
 'precision': {'amount': 3, 'base': 8, 'price': 6, 'quote': 8}, ←---------------- HERE
 'quote': 'BTC',
 'quoteId': 'BTC',
 'spot': True,
 'symbol': 'ETH/BTC',
 'taker': 0.001,
 'tierBased': False,
 'type': 'spot'}
mbp:ccxt igorkroitor$
```

```Python
import ccxt
from pprint import pprint
exchange = ccxt.binance({
    'enableRateLimit': True
})
markets = exchange.load_markets()
symbol = 'ETH/BTC'
market = exchange.market(symbol)
pprint(market['precision'])
pprint(exchange.amountToPrecision(symbol, 0.00013715435110890858))
```

With 3 decimal places the smallest amount it can accept is 0.001, you're passing a value that is lower than the minimal amount according to exchange precision (0.000137... < 0.001).

Let us know if the above does not answer your question.

**Comment by kroitor** [comment]
I'd highly recommend to read the Manual from top to bottom very carefully – it will save your time, really.

Also, for the future, always paste a complete but short code snippet to reproduce it (including exchange instantiation) and your verbose/output as explained here:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

Always paste your source code here using [GitHub markdown](https://guides.github.com/features/mastering-markdown/) for readability and padding, surround your code and/or output with triple backticks (&#096;&#096;&#096;), like shown below:

&#096;&#096;&#096;Python
put your code here – something we can copypaste and launch
don't paste one line of code, paste your full short complete code snippet to reproduce it
it has to be short but complete including exchange instantiation, but without your keys of course
&#096;&#096;&#096;

&#096;&#096;&#096;
your verbose request/response and output here
&#096;&#096;&#096;

-----------------

For example:

```Python
import ccxt
from pprint import pprint
exchange = ccxt.binance({
    'enableRateLimit': True
})
markets = exchange.load_markets()
exchange.verbose = True  # ←------------------ enable verbose mode after loading the markets
symbol = 'ETH/BTC'
binance.create_order(symbol, 'limit', 'sell', 0.00013715435110890858, 0.024752145000000003)
```

**Comment by medozero** [comment]
Ok Thanks a lot for your help. i will follow your advice in the future
