### ISSUE TITLE
zb.com market missing

### ISSUE THREAD

**Issue by blaaaaaaa** [ccxt/ccxt#7169]
win10 python 3.8 1.30.31

ccxt zb says as an example, ccxt.base.errors.BadSymbol: zb does not have market symbol BAT/USDT
but it should be there: https://www.zb.com/trade/bat_usdt
related to the error may be, that it is not searchable using the exchange(pro) tab from the trade dropdown menu, which leads to these urls: https://www.zb.com/en/web/kline/bat_usdt , which actually works. but the search for bat usdt doesn't work.

only findable in the exchange(basic) tab. 
either zb changed something, or ccxt, as this market was found earlier. same thing for GNT/BTC market and I suspect many more.

**Comment by kroitor** [comment]
If you enable verbose mode, you can see that the markets for zb are fetched from this endpoint:

- http://api.zb.cn/data/v1/markets

That endpoint does not return BAT/USDT nor GNT/BTC.

CCXT loads those markets from the exchange directly. So, if the exchange does not return those markets – we cannot invent that info out of thin air. If it used to have those markets, but does not have them anymore – that means something has changed on the exchange side (either they delisted those markets, or they have changed their API).

Let us know if that does not answer your question.
