### ISSUE TITLE
[coinbasepro] error handling question

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#7171]
When placing on order on CBP in a valid market, but a market that I do not have access to ( BTC/USD in this case), I get the following error: `ExchangeError: coinbasepro Trading pair not available`.  Is there a better class of error we could use for this scenario?

**Comment by kroitor** [comment]
@npomfret i'd suggest `PermissionDenied`, if that is the case, however, it's very hard to distinguish the cause of that message from other possible causes, like `BadSymbol`. Can you share the details on why you don't have the access to it? What would you suggest?

**Comment by npomfret** [comment]
CBP limits access to fiat markets based on your location. I'm in the UK, and they don't appear to allow UK customers to trade in USD markets.

**Comment by kroitor** [comment]
@npomfret then I think `PermissionDenied` should satisfy this criteria, i'll do my best to add the handling for it asap.

**Comment by npomfret** [comment]
If I bodge the code and try to force a completely invalid market I get: `ExchangeError: coinbasepro Product not found`

**Comment by kroitor** [comment]
@npomfret thanks, that helps a lot, i'll add a mapping for `Trading pair not available` shortly.

**Comment by bonetjoshua** [comment]
I am having a similar error when it tries to get the ticker for WLUNA:
ccxt.base.errors.ExchangeError: coinbasepro Not allowed for delisted products 

Any suggestions?

**Comment by Phionx** [comment]
Is there any way to tell if a trading pair is not available albeit being a valid market on CBP? 

I am, for example, unable to trade "USDT/GBP" and this is what my market info looks like from load_markets

```
{'id': 'USDT-GBP',
 'symbol': 'USDT/GBP',
 'base': 'USDT',
 'quote': 'GBP',
 'baseId': 'USDT',
 'quoteId': 'GBP',
 'active': True,
 'type': 'spot',
 'linear': None,
 'inverse': None,
 'spot': True,
 'swap': False,
 'future': False,
 'option': False,
 'margin': False,
 'contract': False,
 'contractSize': None,
 'expiry': None,
 'expiryDatetime': None,
 'optionType': None,
 'strike': None,
 'settle': None,
 'settleId': None,
 'precision': {'amount': 0.01, 'price': 0.0001},
 'limits': {'amount': {'min': None, 'max': None},
  'price': {'min': None, 'max': None},
  'cost': {'min': 0.72, 'max': None},
  'leverage': {'min': None, 'max': None}},
 'info': {'id': 'USDT-GBP',
  'base_currency': 'USDT',
  'quote_currency': 'GBP',
  'quote_increment': '0.0001',
  'base_increment': '0.01',
  'display_name': 'USDT/GBP',
  'min_market_funds': '0.72',
  'margin_enabled': False,
  'post_only': False,
  'limit_only': False,
  'cancel_only': False,
  'status': 'online',
  'status_message': '',
  'trading_disabled': False,
  'fx_stablecoin': True,
  'max_slippage_percentage': '0.01000000',
  'auction_mode': False,
  'high_bid_limit_percentage': '0.03000000'},
 'percentage': True,
 'tierBased': True,
 'maker': 0.004,
 'taker': 0.006}
```

I would think that `trading_disabled` would be True, but it is not. 

Any help would be greatly appreciated, thank you!

**Comment by carlosmiei** [comment]
@Phionx 
The problem is that the API reports it as a tradable market:
```
  'status': 'online',
  'status_message': '',
  'trading_disabled': False,
```

**Comment by Phionx** [comment]
Thanks for your response @carlosmiei !

Is there any chance that ccxt is not pinging the Coinbasepro API properly to get this information or missing some logic in how tradable markets are determined?

**Comment by npomfret** [comment]
I think (but am not 100% sure) is the Coinbase markets are closed to customers depending on their locality.  An unauthenticed api call won't know who you are, and so won't know which markets are available to you. If you're in the UK for example, it's possible that trading a USD pair isn't allowed, even though the market is operating correctly for other users.
