### ISSUE TITLE
Custom binance  method

### ISSUE THREAD

**Issue by xiaoqge** [ccxt/ccxt#7173]
os version: centos 7
ccxt version: 1.30.14

I tried to define a method to get the liquidated order in the contract, but this method does not exist by default，I added a method in binance.py

```
#test 
    def forces_order(self, symbol, since=None, limit=None, params={}):
        self.load_markets()
        market = self.market(symbol)
        request = {
            'symbol': market['id'],
        }
        if since is not None:
            request['startTime'] = since
            # https://github.com/ccxt/ccxt/issues/6400
            # https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#compressedaggregate-trades-list
            request['endTime'] = self.sum(since, 3600000)
        if limit is not None:
            request['limit'] = limit  # default == max == 500
        method = 'fapiPublicGetallForceOrders'
        response = getattr(self, method)(self.extend(request, params))
```

Error cannot find this attribute
```
Traceback (most recent call last):
  File "get_duokong.py", line 45, in <module>
    get_duokong()
  File "get_duokong.py", line 41, in get_duokong
    print(binance.forces_order(symbol))
AttributeError: 'binance' object has no attribute 'forces_order
```

Do I need to define a method in exchange.py? thank you very much

**Comment by kroitor** [comment]
@xiaoqge 

> Do I need to define a method in exchange.py?

Nope. That endpoint was missing in the API definitions, I've added it, and it will be available in the new CCXT version. You should do the following:

1. Wait 15 minutes till new CCXT version 1.30.33 arrives. Update your CCXT version then.
2. Change the name of the implicit method in your code:
```Python
        method = 'fapiPublicGetallForceOrders'
        #                ↓      ↓
        method = 'fapiPrivateGetAllForceOrders'
```

From there it should work. If it does not work, paste the complete code (how you import it and how you initialize the exchange, as required here: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help)

Let us know if that does not help.

**Comment by xiaoqge** [comment]
Thank you very much. I mainly want to understand why my custom method is not available. I defined the `def forces_order` method in binance.py. Why does it prompt `AttributeError:'binance' object has no attribute'forces_order'`

**Comment by kroitor** [comment]
@xiaoqge it depends on two things:
- where you have added your custom method
- how you import the class that you've changed

However, you don't have to change CCXT code for that at all. Extending the functionality does not require changing the library code. Instead, you should apply an architecturally-proper approach to writing your code, for example, one of:

- functional/procedural approach
- object-oriented approach with inheritance

That is not a question about CCXT, though, that is more about how to use Python in general. For that you have to know the Python well, not just the very basics, but also some further concepts.

What you should do instead is:

### Functional/procedural approach

```Python
import ccxt
from pprint import pprint

pprint(ccxt.__version__)  # make sure your CCXT version is the most recent one

def forces_order(exchange, symbol, since=None, limit=None, params={}):
    exchange.load_markets()
    market = exchange.market(symbol)
    request = {
        'symbol': market['id'],
    }
    if since is not None:
        request['startTime'] = since
        request['endTime'] = exchange.sum(since, 3600000)
    if limit is not None:
        request['limit'] = limit  # default == max == 500
    return exchange.fapiPrivate_get_allforceorders(request)

exchange = ccxt.binance({
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future',
    },
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
})

your_orders = forces_order(exchange, symbol)
```

### Object-oriented approach with inheritance

```Python
import ccxt
from pprint import pprint

pprint(ccxt.__version__)  # make sure your CCXT version is the most recent one


class MyBinance(ccxt.binance):

    def forces_order(symbol, since=None, limit=None, params={}):
        self.load_markets()
        market = self.market(symbol)
        request = {
            'symbol': market['id'],
        }
        if since is not None:
            request['startTime'] = since
            request['endTime'] = self.sum(since, 3600000)
        if limit is not None:
            request['limit'] = limit  # default == max == 500
        return self.fapiPrivate_get_allforceorders(request)

exchange = MyBinance({
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future',
    },
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
})

your_orders = exchange.forces_order(symbol)
```

**Comment by xiaoqge** [comment]
Thank you very much for your help, a great project depends on the developer, CCXT is a great project

**Comment by avatar-lavventura** [comment]
@kroitor  I am getting `ExchangeError: binanceusdm {"code":400,"msg":"The endpoint has been out of maintenance"}
` error. The way use is as follows:

```
exchange = ccxt.binanceusdm(
    {
        "apiKey": api_key,
        "secret": api_secret,
        "enableRateLimit": True,
        "options": {"defaultType": "future",},
    }
)

your_orders = forces_order(exchange, "ETC/USDT")

```

**Comment by kroitor** [comment]
@avatar-lavventura https://binance-docs.github.io/apidocs/futures/en/#change-log

> Changelog

> 2021-04-27
> REST
> The endpoint `GET /fapi/v1/allForceOrders` stop being maintained and no longer accepts request.

<img width="1019" alt="Screenshot 2021-07-06 at 11 57 15" src="https://user-images.githubusercontent.com/1294454/124572503-5c77bb80-de51-11eb-9ec4-413555c8326c.png">

**Comment by avatar-lavventura** [comment]
Ah they blocked our access :-( Do you think could there be any other approach to fetch the liquadation data, maybe from different exchanges or sites?

**Comment by kroitor** [comment]
@avatar-lavventura the binance liquidation data can be available only from binance. You can still fetch that data using the fapi `forceOrders` endpoint https://binance-docs.github.io/apidocs/futures/en/#user-39-s-force-orders-user_data with CCXT implicit methods: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api
Replace `fapiPrivate_get_allforceorders` with `fapiPrivate_get_forceorders` after upgrading to CCXT 1.52.45 in ~ 20 minutes when the new build arrives.

**Comment by avatar-lavventura** [comment]
@kroitor I have updated the code as follows, but all the pairs return empty list, is it normal?

```
def forces_order(exchange, symbol, since=None, limit=None, params={}):
    exchange.load_markets()
    market = exchange.market(symbol)
    request = {
        "symbol": market["id"],
    }
    if since is not None:
        request["startTime"] = since
        request["endTime"] = exchange.sum(since, 3600000)
    if limit is not None:
        request["limit"] = limit  # default == max == 500
    return exchange.fapiPrivate_get_forceorders(request)


exchange = ccxt.binanceusdm(
    {
        "apiKey": api_key,
        "secret": api_secret,
        "enableRateLimit": True,
        "options": {"defaultType": "future",},
    }
)

output = forces_order(exchange, "ETC/USDT")
print(output)
```

**Comment by kroitor** [comment]
@avatar-lavventura did you actually have liquidations recently?

**Comment by avatar-lavventura** [comment]
@kroitor Ah I thought I can fetch the public data related to liquadations my bad, like the ones on this graps: https://coinalyze.net/waves/usdt/binance/liquidation-chart/wavesusdt_perp_lq/ and https://www.cryptometer.io/binance-rekt.

Sadly, last time I get liquadated was 19 May, when binance shutdown their system and drop all the coins 50% more than their original price.

**Comment by avatar-lavventura** [comment]
@kroitor No I haven't force liquidated. To be clear. using `exchange.fapiPrivate_get_forceorders()` we could only obtain out own liquidation data right, hence we cannot fetch public liquidation data from other users, right?
