### ISSUE TITLE
Binance fetch_balance for isolated margin

### ISSUE THREAD

**Issue by codemonkeyno1** [ccxt/ccxt#7175]
The default fetch_balance using the defaultType='margin' shows the balances in the cross margin wallet.  Is it possible in CCXT to get the isolated margin balances instead?  Thank you.

**Comment by kroitor** [comment]
> Is it possible in CCXT to get the isolated margin balances instead?

As far as I understand, technically, there's no such thing as isolated margin balances.
The difference between CROSS and ISOLATED margin is explained here:

- https://github.com/ccxt/ccxt/issues/4834#issuecomment-644968264

> "Isolated" and "cross" are terms that define your margin-trading mode. They're related to the way your own+borrowed funds are risk-managed.

> When you margin-trade in isolated mode, your margin is defined per each position separately (your positions are isolated from one another). Thus, if you get an isolated margin-call on one position, that position may be liquidated, but that does not affect your other positions.

> When you margin-trade in cross mode, your margin is defined for all positions at once. In other words, your margin is "shared" across all positions that you might have. A margin-call in cross mode means that all your positions might be liquidated, if you run out of margin.

↑ From there you can carry, that there's no "cross" balance and no "isolated" balance. There's just one margin balance. If you're trading in isolated mode, then each position gets its own margin. The balance remains the single same thing in any case.

Let me know if that does not answer your question.

**Comment by codemonkeyno1** [comment]
In Binance, there does seem to be a difference.  Isolated margin applies to amount of margin set aside for one trading pair.  Fetching the balance by default only shows the cross margin balances, but not the isolated ones.  Some instruments are only available to be traded in isolated margin mode, and not cross.

**Comment by kroitor** [comment]
@codemonkeyno1 

>  Isolated margin applies to amount of margin set aside for one trading pair.

That is correct. That's the same as one position. However, there's no such thing as "a balance" for the position. If you want to get that info, you just get your positions – this is how you get the isolated margin, but that is not called "a balance".

**Comment by codemonkeyno1** [comment]
In Binance, there seems to be separate wallets for each symbol using isolated margin balances.  

Is there a method for getting margin positions in ccxt?

**Comment by kroitor** [comment]
> Is there a method for getting margin positions in ccxt?

Yes:

```Python
import ccxt
from pprint import pprint
exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future',
    },
})

balance = exchange.fetch_balance()
pprint(balance['info']['positions'])
```

Let us know if that does not answer your question.

**Comment by codemonkeyno1** [comment]
FYI, in case there was any misunderstanding, I am not speaking about isolated margin in the context of futures api. I mean in the margin api.

The pprint(balance['info']['positions'])  when used with 'defaultType':'margin', only shows cross margin instruments.  As an example, it wouldn't even have an entry for 'ZIL' which is only available for trading in isolated margin, but not cross margin.

**Comment by kroitor** [comment]
@codemonkeyno1 afaik, you can't find anything related to "Isolated" or "Cross" here: https://binance-docs.github.io/apidocs/spot/en/#margin-account-trade. 

However, you can find "Isolated" and "Cross" here: https://binance-docs.github.io/apidocs/futures/en/

**Comment by kroitor** [comment]
@codemonkeyno1 you can call any of those API methods with implicit API endpoints, as described here:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

Some of that info is also available via unified methods in the `info` of a corresponding structure.

**Comment by codemonkeyno1** [comment]
I see.  It's a relatively new feature, so maybe Binance hasn't integrated it in the API/docs yet.  Thanks for looking into it.

**Comment by hivemall** [comment]
@codemonkeyno1 you have four ways to get balances: @kroitor there is isolated account balance:
```
spot = exchange.fetch_balance()
margin_cross = exchange.fetch_balance({'type':'margin'})
margin_iso = exchange.sapi_get_margin_isolated_account() # not uniform, see dir(exchange)
future = exchange.fetch_balance({'type':'future'})
```
