### ISSUE TITLE
Add support for header functions / Dynamic header values

### ISSUE THREAD

**Issue by Ekliptor** [ccxt/ccxt#7176]
Could you add support to specify a header value as a function instead of a constant value?
This is needed as some exchanges require custom signatures with time-value in headers.

JavaScript example:

```
const exchange = new ccxt.binance ({
    'headers': {
        'YOUR_CUSTOM_HTTP_HEADER': 'YOUR_CUSTOM_VALUE',
        'YOUR_DYNAMIC_HEADER'() {
                return Date.now() + "12345..";
        }
    }
})
```

And then before each HTTP request:
```
        const sendHeaders = {}
        for (let key in headers)
        {
            if (typeof headers[key] === "function")
                sendHeaders[key] = headers[key](); // get the function value
            else
                sendHeaders[key] = headers[key];
        }
```

**Comment by kroitor** [comment]
@Ekliptor most likely, we will not add a per-header function, since that will be harder to unify across languages, but we will add an overrideable `exchange.setHeaders()` base method, which you would be able to use to achieve the same result. Hope to get to is asap.

**Comment by Ekliptor** [comment]
is there any progress on this?

**Comment by kroitor** [comment]
@Ekliptor added the overrideable `setHeaders` in CCXT 1.35.78+
