### ISSUE TITLE
FTX fetch_order does not fetch "conditional" orders

### ISSUE THREAD

**Issue by r4VP4** [ccxt/ccxt#7178]
- OS:Windows 10
- Programming Language version:Python 3.7.6
- CCXT version:1.30.37

```
result = ccxtinstance.fetch_order(id='123456789')
pprint.pprint(result)
```

```
ccxt.base.errors.OrderNotFound: ftx {"error":"Order not found","success":false}
```

If i try to get a so called (from FTX) "conditional" order via the method fetch_order i get an OrderNotFound error. Maybe the cause are the two different api-calls needed for the two ordertypes: 
GET /conditional_orders?market={market}
and
GET /orders?market={market}

**Comment by xmatthias** [comment]
Your best bet is to fetch all conditional orders for this pair and filter locally.

``` python
orders = ct.fetch_orders(pair, None, params={'type': 'stop'})

[order for order in orders if order['id'] == order_id]
```


FTX conditional_orders endpoint does not allow you to filter on order_id ... 
Unfortunately, you MUST know what type the trigger-order was ...

I had the same problem a while ago ... #6669 (see the comments further down ..).

**Comment by kroitor** [comment]
@xmatthias thanks for your involvement!

@r4VP4 let us know if the above answer does not help. Feel free to reopen this issue or just ask further questions, if any.
