### ISSUE TITLE
Getting more than 10 IDEX open orders

### ISSUE THREAD

**Issue by presence35** [ccxt/ccxt#7181]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: linux
- Programming Language version: php
- CCXT version: 1.30.34

How exactly do I set the 'count' param for IDEX?
I've tried :

$orders = $exchange->fetchOpenOrders(null, null, 100);

as well as:

$exchange = new $ex (array (
			'limit' => 100,
			'count' => 100,
		));

Thanks.

**Comment by kroitor** [comment]
@presence35 it was missing in the IDEX API implementation before, if you update to version 1.30.40, it should work as in your first line. The new build will arrive in 15-20 minutes.

```PHP
$orders = $exchange->fetchOpenOrders(null, null, 100);
```

Let us know if you still have issues with it after upgrading to the most recent version.
