### ISSUE TITLE
pip install versioned ccxt.pro on existing working docker build throws errors

### ISSUE THREAD

**Issue by 123wowow123** [ccxt/ccxt#7183]
Running below command on existing working docker build throws errors as underlying ccxt lib is not version locked.

RUN pip install git+https://user:password@github.com/kroitor/ccxt.pro.git@0.2.55#subdirectory=python

File "/usr/local/lib/python3.8/site-packages/ccxtpro/__init__.py", line 149, in <module>
from ccxt.async_support.theocean import theocean # noqa: F401
ModuleNotFoundError: No module named 'ccxt.async_support.theocean'

**Comment by kroitor** [comment]
@123wowow123 upon delisting an exchange, we update the version numbers, so if you try a higher version of CCXT Pro – it should work:

- https://github.com/kroitor/ccxt.pro/blob/master/package.json#L37
- https://github.com/kroitor/ccxt.pro/blob/master/python/setup.py#L80

You can simply uninstall ccxt and reinstall it again, that will also resolve this issue.

Let us know if that does not help.
