### ISSUE TITLE
Bitmax fetch_open_orders() method fails with partially filled orders

### ISSUE THREAD

**Issue by JovianMoon** [ccxt/ccxt#7187]
- OS: Linux Mint
- Programming Language version: 3.5.2
- CCXT version: 1.30.37

```
exchange = ccxt.bitmax({'verbose': False, 'apiKey': api_key, 'secret': secret, 'enableRateLimit': True, 'nonce': ccxt.Exchange.milliseconds, 'timeout': timeout})
exchange.fetch_open_orders()
```

```
Traceback (most recent call last):
...
    self.exchange.fetch_open_orders()
  File "/usr/local/lib/python3.5/dist-packages/ccxt/bitmax.py", line 1176, in fetch_open_orders
    return self.parse_orders(data, market, since, limit)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 1676, in parse_orders
    array = self.sort_by(array, 'timestamp')
  File "/usr/local/lib/python3.5/dist-packages/ccxt/base/exchange.py", line 855, in sort_by
    return sorted(array, key=lambda k: k[key] if k[key] is not None else "", reverse=descending)
TypeError: unorderable types: int() < str()
```

It seems that the timestamp is not handled correctly in parse_order() -method in lines 970-982 when the order is partially filled. Line 970 looks suspicious, as there doesn't seem be 'timestamp' key in the order dictionary:

```
timestamp = self.safe_integer_2(order, 'timestamp', 'sendingTime')
```

Furthermore, timestamp variable is not overwritten below line 977 in case of partially filled order. Not sure if it should be this way.

**Comment by kroitor** [comment]
@JovianMoon 

> timestamp = self.safe_integer_2(order, 'timestamp', 'sendingTime')

The `safe_integer_2` will look up for two keys. Can you please paste the verbose request/response for it?

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by kroitor** [comment]
```
exchange = ccxt.bitmax({'verbose': False, 'apiKey': api_key, 'secret': secret, 'enableRateLimit': True, 'nonce': ccxt.Exchange.milliseconds, 'timeout': timeout})
exchange.load_markets()
exchange.verbose = True
exchange.fetch_open_orders()
```

↑ Can you paste that output?

**Comment by JovianMoon** [comment]
@kroitor Sorry, too late, I don't have partially filled orders at the moment as I already fixed this manually. Can this be figured out without this info?

**Comment by kroitor** [comment]
> Can this be figured out without this info?

That's complicated, this is why we always ask for code to reproduce + verbose request/response.

**Comment by JovianMoon** [comment]
Ok, I will update when I can make the problem occur again.

**Comment by kroitor** [comment]
I think it's caused by the fact that Bitmax spot orders don't have a timestamp, nor the sending time either, so there's no way to get the original order timestamp from the open orders endpoint...

- https://github.com/ccxt/ccxt/blob/master/js/bitmax.js#L939
- https://bitmax-exchange.github.io/bitmax-pro-api/#list-open-orders
- https://github.com/ccxt/ccxt/blob/master/js/bitmax.js#L974 (futures-orders do have it)

I'll try to add a workaround for that.

**Comment by JovianMoon** [comment]
This was a limit order and there was only 'lastExecTime' timestamp available in the order structure.

**Comment by kroitor** [comment]
> This was a limit order and there was only 'lastExecTime' timestamp available in the order structure.

Yep, however, `lastExecTime` is unified to `lastTradeTimestamp`, idk why bitmax wouldn't include the order placing timestamp for the open orders, that's just weird. But anyways, i'll fix that shortly.
