### ISSUE TITLE
Bybit edit_order "unknown order_status [Untriggered]"

### ISSUE THREAD

**Issue by Serendepon** [ccxt/ccxt#7192]
- OS: Windows
- Programming Language version: Python
- CCXT version: 1.30.47
- Exchange: Bybit testnet
- Method: edit_order

Hello! Have a problem with bybit.edit_order
Trying to modify stop order, but it didn't work with any conditional either

So, after that on existing sl order :

edit_order('711c143e-4c25-4f32-bd52-6a924daf7891', 'BTC/USD', 'Market', 'Buy', None, 9150)

i got that:

Got an error ExchangeError ('bybit {"ret_code":-1,"ret_msg":"unknown order_status [Untriggered]","ext_code":"","result":null,"ext_info":null,"time_now":"15932797
90.370218","rate_limit_status":99,"rate_limit_reset_ms":1593279790378,"rate_limi
t":100}',) , retrying in 30 seconds...

**Comment by kroitor** [comment]
For conditional orders you should specify a `stop_order_id` in the `params` argument, as explained in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

```Python
params = {
    'stop_order_id': '711c143e-4c25-4f32-bd52-6a924daf7891';
}
exchange.edit_order(order_id, symbol, type, side, about, price, params)
```

Let us know if that does not answer your question. If you still have difficulties with it, please, paste your verbose request/response precisely as explained here:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

Feel free to reopen it or just ask further questions if any.

**Comment by Serendepon** [comment]
Thanks, Igor!

It worked, but i have to override it all to params, 'symbol' and 'p_r_trigger_price' too.

**Comment by kroitor** [comment]
@Serendepon i'll try to figure out the `symbol` requirement, however, i'm afraid the `p_r_trigger_price` will still be required along with the `stop_order_id`. Unfortunately, there's no quick and easy way around it. We hope to roll out a better generalization for conditional orders asap.
