### ISSUE TITLE
Feature Request: Multi-Subscriptions

### ISSUE THREAD

**Issue by athenawisdoms** [ccxt/ccxt#7201]
- OS: Ubuntu 20.04
- Programming Language version: Node v14.4.0
- CCXT version: ccxtpro 0.1.35

Hi CCXT team!

It will be extremely advantageous to have multi-subscriptions in CCXT Pro when listening to a large number of markets for an exchange. If the number of WS calls can be reduced to 2-3, our systems will not be missing a considerable amount of market data due to following rate limits, such as when we re-subscribe to all the large number of markets again right after a network error.

Hope this feature will eventually be implemented into CCXT pro to make it even more amazing! Thank you!

**Comment by binares** [comment]
An easy approach would be passing a list of symbols to a watch{X}, which would reduce the number of subscriptions the number of different X types you subscribe to (some exchanges do indeed support this). However this doesn't solve the rate limit problem for exchanges that don't send snapshots, but require manual fetchOrderBook / fetchOpenOrders(symbol) etc.

**Comment by kroitor** [comment]
@binares that's right. We are working on a subscription manager base class to cover this. We will most likely start with watchTickers implementations first (for many tickers at once). And will eventually add watchOrderBooks where available. Apart from that we're now working on the private API implementations.

**Comment by athenawisdoms** [comment]
@kroitor Checking in to see how far ahead is the subscription manager feature in your pipeline. Thank again :grinning:

**Comment by kroitor** [comment]
@athenawisdoms pardon, i got sidetracked and had to delay it due to the number of requests, but will do my best to resume it and finish it asap.

**Comment by zsyh** [comment]
If I use ccxtpro's internal rate limiter, does it work?

**Comment by kroitor** [comment]
@zsyh yes, if you subscribe to each feed separately one by one. This issue is more about subscribing to many feeds simultaneously in one call.

**Comment by SnShine** [comment]
What is the status of this feature request? For binance it's just passing multiple feeds' names like "btcusdt@trades/ethusde@trades" and I guess it's pretty easy to implement. Is it same for all other exchanges?

Adding this feature in ccxt pro is really helpful, tbh.
