### ISSUE TITLE
Huobi ccxt's fetch_deposit_address not working

### ISSUE THREAD

**Issue by coincoin1** [ccxt/ccxt#7202]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS : Window 10
- Programming Language version : Python 3.7 
- CCXT version : 1.30.3

```
import ccxt

huobi = ccxt.huobipro({
    'apiKey': 'My api key',
    'secret': 'My secret key',
})

symbol = "DAC"
deposit_update = huobi.fetch_deposit_address()
print(deposit_update)

```

```
Traceback (most recent call last):
  File "C:/Users/Home/PycharmProjects/untitled/Huobi_test.py", line 9, in <module>
    deposit_update = huobi.fetch_deposit_address()
AttributeError: 'huobipro' object has no attribute 'fetch_deposit_address'
```

The function to retrieve Huobi's wallet address does not work.

**Comment by kroitor** [comment]
Please, follow the Manual precisely. I'd highly recommend to carefully read the entire Manual from top to bottom at least once – it will save your time, really.

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit 
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.huobipro({
    'apiKey': 'My api key',
    'secret': 'My secret key',
    'enableRateLimit': True,
})

exchange.load_markets()

exchange.verbose = True

code = 'DAC'
deposit_address = exchange.fetch_deposit_address(code)
pprint(deposit_address)
```

↑ Paste your entire output here (including the runtime version and the verbose request+response).

**Comment by kroitor** [comment]
It could be a PyCharm installation/configuration issue. We've had similar reports before, most of the time this is either:

- due to PyCharm itself not seeing the properly defined methods
- due to wrong installation paths
- due to misconfiguration of the runtime environment

As you can see from here, the `fetch_deposit_address` method is defined in the corresponding Python files and most of the people are using it successfully:

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/huobipro.py#L1114
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/huobipro.py#L1114

**Comment by coincoin1** [comment]
```
C:\Users\Home\PycharmProjects\untitled\venv\Scripts\python.exe "C:/Users/Home/PycharmProjects/untitled/Huobi_test.py"
CCXT Version: 1.22.52
Traceback (most recent call last):
  File "C:/Users/Home/PycharmProjects/untitled/Huobi_test.py", line 18, in <module>
    deposit_address = exchange.fetch_deposit_address(code)
AttributeError: 'huobipro' object has no attribute 'fetch_deposit_address'

Process finished with exit code 1
```

I did it again with the code I told you, but the problem still occurs.

Also, fetch_address from other exchanges works fine and only Huobi ccxt has errors.

**Comment by coincoin1** [comment]
Sorry I reinstall ccxt and run pycharm again, it works fine again Sorry for taking up valuable time.

**Comment by kroitor** [comment]
@coincoin1 thx for reporting back!
