### ISSUE TITLE
Bitflyer us availability

### ISSUE THREAD

**Issue by crossx4real** [ccxt/ccxt#7209]
is bitflyer us available for ccxt?

**Comment by kroitor** [comment]
@crossx4real can you plz share the links?

**Comment by crossx4real** [comment]
https://bitflyer.com/en-us/login?backurl=%2fen-us%2fex%2fUploadDocument#

sorry i had typo in the name earlier.

**Comment by kroitor** [comment]
@crossx4real try this and let us know if it does not help:

```JavaScript
const ccxt = require ('ccxt')
const exchange = new ccxt.bitflyer({
    'enableRateLimit': true,
    'urls': {
        'api': 'https://api.bitflyer.com',
    },
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

// ... use it as if it was bitflyer.jp...
```

Closing this for now if you don't mind. Feel free to reopen it or just ask further questions if any.
