### ISSUE TITLE
quadrigacx withdrawal function

### ISSUE THREAD

**Issue by pciavald** [ccxt/ccxt#721]
Hi, 
First of all, thank you very much for your work.

I'm trying to withdraw from quadrigacx, but `quadrigacx.withdraw is not a function` and printing the exchange shows `hasWithdraw: false`. However the documentation shows that withdrawals are supported, and I see some private methods in the class... 

Can you help ?
Thank you

**Comment by kroitor** [comment]
Hi!

Thanks for your feedback!

> However the documentation shows that withdrawals are supported, and I see some private methods in the class...

The withdraw API has been started not very long ago and we don't have all `withdraw()` methods implemented yet. But we will add the implementation for QuadrigaCX withdraw very soon, or, you may as well help us implement it, if you submit a PR, we welcome all contributions. More about it here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md. If you feel like you want to give it a try, go ahead, please, I'll assist where needed. The easiest way to implement it is to copy an existing implementation for another exchange and alter it for QuadrigaCX.

Let me know if the above answers your question or not. Thx!

**Comment by pciavald** [comment]
thank you, i'll try to submit a PR then :)

**Comment by kroitor** [comment]
@pciavald that would be awesome! That should be pretty much straightforward. Just take a look at other `withdraw()` implementations and you'll get it very quickly. Let us know if you have any questions. Thx!

**Comment by kroitor** [comment]
This was added in version 1.10.282. Thx!

**Comment by pciavald** [comment]
damn, you're too fast. Thank you ! Next time for the PR

**Comment by kroitor** [comment]
@pciavald feel free to submit contributions, we will be looking forward to hear from you! Let us know if you have any difficulty with it! Thx!
