### ISSUE TITLE
how to get remaining time to make another request when enableRateLimit is true in javascript

### ISSUE THREAD

**Issue by fabiel-leon** [ccxt/ccxt#7212]
sample
```javascript
const ex = new ccxt.binance({
        enableRateLimit: true,
});
const orderBook = await ex.fetchOrderBook(symbol, 10);

const time = ex.getNextRequestRemainingTime();

```

**Comment by kroitor** [comment]
In general, you don't have to that. When `enableRateLimit` is true, the next request will be sent out as soon as there's space in the token bucket implementation of the built-in rate limiter. However, you can measure the time before the request and the time after the request and then compare to the `exchange.rateLimit`, if you want.

Please, read more about the built-in rate limiter here:

-

```JavaScript
const ccxt = require ('./ccxt')
const exchange = new ccxt.binance({
        enableRateLimit: true,
});
const symbol = 'ETH/BTC'
(async () => {
    await exchange.loadMarkets ()
    while (true) {
        const before = exchange.milliseconds ()
        console.log ('Fetching the orderbook on', exchange.iso8601 (before))
        const orderBook = await exchange.fetchOrderBook(symbol, 10);
        const after = exchange.milliseconds ()
        console.log ('Fetched the orderbook on', exchange.iso8601 (after))
        const difference = after - before
        const remaining = exchange.rateLimit - difference
        console.log ('Remaining wait-time is', remaining, 'milliseconds')
    }
}) ()
```

Read here on how the rate-limiter works:

- https://github.com/ccxt/ccxt/issues/1399#issuecomment-359233015

Let us know if that does not answer your question. Feel free to reopen it or just ask further questions if any.
