### ISSUE TITLE
ccxt for trading on margin in Binance

### ISSUE THREAD

**Issue by cadmufasa** [ccxt/ccxt#7217]
Hello,

I have seen in this message: https://github.com/ccxt/ccxt/pull/5907

that the following code:
`let binance_futures = new ccxt.binance({ options: { defaultMarket: 'future' } })`
could be used as a way to initiate a connection to the proper back-end (on Binance) for processing orders on Margin. 

If this is true,  I had a few questions:

 I have code working for creating orders (limit and market) on the  Binance SPOT exchange. Will this same code work when accessing the servers on the Binance FUTURE exchange? If so, what functions can I use to:
-> Create a Margin order
-> Make changes on the Margin order
-> See what kind of leverage is being applied to the Margin order
-> See how much money has been made (and lost) **after** the order has been filled

I am using **Python 3.x** on a **Linux** system
TIA

**Comment by kroitor** [comment]
> I have seen in this message: #5907
> 
> that the following code:
> `let binance_futures = new ccxt.binance({ options: { defaultMarket: 'future' } })`

↑ This is wrong (it's not `defaultMarket`, it's `defaultType`).

And you must enable the rate limiter. This is explained in the Manual. You have to read the entire Manual very carefully from top to bottom at least once – that will save your time, really.

The correct way is this:

```Python
import ccxt
exchange = ccxt.binance({
    'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    'options': {
        'defaultType': 'future',  # or 'margin'
    }
})

If you set `defaultType` to `future` – you will trade perpetual futures (swaps) in margin mode.
If you set `defaultType` to `margin` – you will trade regular spot markets in margin mode.

Duplicates:

- https://github.com/ccxt/ccxt/issues/6376
- https://github.com/ccxt/ccxt/issues/6273#issuecomment-565563176

> Will this same code work when accessing the servers on the Binance FUTURE exchange?

Yes, with maybe a few little differences.

> If so, what functions can I use to:
-> Create a Margin order

`createOrder()` + optional [param overrides](https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params) as explained in the Manual.

-> Make changes on the Margin order

That is done by placing more buy/sell orders with the same position.

-> See what kind of leverage is being applied to the Margin order

See `fetchBalance()` + `info` in the response to get your positions. Leverage is not a property of an order, it's a property of a margin position.

-> See how much money has been made (and lost) after the order has been filled

See `fetchBalance()` + `info` in the response.

Hope that answers your questions.

**Comment by cadmufasa** [comment]
Thanks for the response!

Have added a few more questions for clarification purposes.

**=> ADJUSTING LEVERAGE
--------------------------------------------------**

**I was running the following Python code (for Binance):**

```
	import ccxt
	from pprint import pprint
	exchange = ccxt.binance({
    		'enableRateLimit': True,
    		'apiKey': 'YOUR_API_KEY',
    		'secret': 'YOUR_SECRET',
    		#    'options': {
    		#    'defaultType': 'future',  # or 'margin'
    		#}
		})

	exchange.load_markets()
	symbol = 'BTC/USDT'
	market = exchange.market(symbol)
	print('Order types supported by the', symbol, 'spot market:')
	pprint(market['info']['orderTypes'])
```



For the SPOT Markets, I got: 
`['LIMIT', 'LIMIT_MAKER', 'MARKET', 'STOP_LOSS_LIMIT', 'TAKE_PROFIT_LIMIT']`

I uncommented the "options" area (to look for the FUTURES Markets) above, I got the following: 
```
['LIMIT',
 'MARKET',
 'STOP',
 'STOP_MARKET',
 'TAKE_PROFIT',
 'TAKE_PROFIT_MARKET',
 'TRAILING_STOP_MARKET']

```
So - it looks as though the FUTURES market has more options than the SPOT market - thankfully - but I am not seeing a way whereby I can enter/adjust the leverage. **How can one enter leverage on the Binance exchange using the API?**

My understanding is pretty much expressed in this video: https://youtu.be/VytoTXKbfkg?t=663

For example, say I want to use 10X leverage or 20X leverage. I do not see a way that I can set this using the API. Am I missing something? Do I need to go through the UI on the exchange and set it there?



**=> FINDING CURRENT PROFFIT & LOSS on BINANCE
--------------------------------------------------**
**How can I find the Current Profit and Loss for a working Position?** My sense is that I could use "fetch_balance" to track the Current Profit and Loss of **all combined trades**? If so, is there any way of tracking the individual trade - like menioned here:https://youtu.be/VytoTXKbfkg?t=545



**=> FINDING LIQUIDATION LEVEL on BINANCE
--------------------------------------------------**
**Finally, how can one find the Liquidation price (as it would be nice to set up a STOP-MARKET order to keep from being liquidated)?**
From the message: https://github.com/ccxt/ccxt/issues/5769
And this info here: https://www.reddit.com/r/BitMEX/comments/dil0qm/using_ccxt_to_combine_get_position_with/
```

self.exchange.private_get_position({  #     ↓ HERE
    'filter': self.exchange.json({"isOpen":True, "symbol":"XBTUSD"})
})

```
But it was for Bitmex. Not sure if it would work on Binance.
**Question: does private_get_position work with the Binance exchange? If not, what is the equivalent?**

Thanks again for the inputs (and sorry for the length)

**Comment by cadmufasa** [comment]
Hi, thought the Original Message had been closed because this is what I was seeing on my side.

![image](https://user-images.githubusercontent.com/66542549/86546941-b5d6a300-befc-11ea-8ae1-3095e52508a6.png)

**Comment by kroitor** [comment]
@cadmufasa a closed status of the original issue does not prevent you from asking further questions for clarifications, which is what you did, so I will reply to your questions in the original issue, just to keep things in one place. In short – we don't miss and we don't forget about your questions, it just takes time to give you the answers. The answers are actually documented in the Manual, but I will provide clarifications anyway. Sometimes it can take a longer time to answer the questions (as we get a lot of them), but we often answer within 24 hours anyway.

**Comment by cadmufasa** [comment]
OK and understood. I  misunderstood the workflow. Will await a response.

**Comment by kroitor** [comment]
@cadmufasa answering your questions below one by one:

> How can one enter leverage on the Binance exchange using the API?

This is documented here:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://binance-docs.github.io/apidocs/futures/en/#change-initial-leverage-trade

```Python
import ccxt
exchange = ccxt.binance({
    'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    'options': {
        'defaultType': 'future',  # or 'margin'
    },
    'apiKey': 'YOUR_API_KEY',  # https://github.com/ccxt/ccxt/wiki/Manual#authentication
    'secret': 'YOUR_SECRET',
})

markets = exchange.load_markets()  # https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
symbol = 'BTC/USDT'
market = exchange.market(symbol)  # https://github.com/ccxt/ccxt/wiki/Manual#methods-for-markets-and-currencies

# https://binance-docs.github.io/apidocs/futures/en/#change-initial-leverage-trade

exchange.fapiPrivate_post_leverage({  # https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
    'symbol': market['id'],  # https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
    'leverage': 10,  # target initial leverage, int from 1 to 125
})
```

↑ Your work with CCXT depends on how careful you were when you read the CCXT Manual, which I would recommend to read very carefully from top to bottom:

- https://github.com/ccxt/ccxt/wiki

**Comment by kroitor** [comment]
> How can I find the Current Profit and Loss for a working Position? My sense is that I could use "fetch_balance" to track the Current Profit and Loss of all combined trades? If so, is there any way of tracking the individual trade

First, profit&loss is not a property of a trade. It's a property of a position. Make sure you understand that clearly. You can't find profit&loss for one trade or for many trades. However, you can find the profit&loss per position. The answers you get depend on how precise you are with terms like _"position"_, _"order"_, _"trade"_ and how those terms and entities relate to each other. Make sure you use the terms precisely to get precise answers to your questions. In many cases, if you understand those terms and their relationships – you won't even have any questions in the first place.

To get the P&L of your positions:

```Python
import ccxt
from pprint import pprint
exchange = ccxt.binance({
    'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    'options': {
        'defaultType': 'future',
    },
    'apiKey': 'YOUR_API_KEY',  # https://github.com/ccxt/ccxt/wiki/Manual#authentication
    'secret': 'YOUR_SECRET',
})

markets = exchange.load_markets()  # https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
symbol = 'BTC/USDT'
market = exchange.market(symbol)  # https://github.com/ccxt/ccxt/wiki/Manual#methods-for-markets-and-currencies

balance = exchange.fetch_balance()  # https://github.com/ccxt/ccxt/wiki/Manual#querying-account-balance

# https://github.com/ccxt/ccxt/wiki/Manual#balance-structure
# https://binance-docs.github.io/apidocs/futures/en/#account-information-user_data

positions = balance['info]['positions']
positions_by_ids = exchange.index_by(positions, 'symbol')
position = exchange.safe_value(positions_by_ids, market['id'])

print('-----------------------------------------')
pprint(position)
print('-----------------------------------------')
print('Your profit and loss for your', symbol', 'position is', position['unrealizedProfit'])
```

**Comment by kroitor** [comment]
> Finally, how can one find the Liquidation price (as it would be nice to set up a STOP-MARKET order to keep from being liquidated)?

```Python
import ccxt
from pprint import pprint
exchange = ccxt.binance({
    'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    'options': {
        'defaultType': 'future',
    },
    'apiKey': 'YOUR_API_KEY',  # https://github.com/ccxt/ccxt/wiki/Manual#authentication
    'secret': 'YOUR_SECRET',
})

markets = exchange.load_markets()  # https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
symbol = 'BTC/USDT'
market = exchange.market(symbol)  # https://github.com/ccxt/ccxt/wiki/Manual#methods-for-markets-and-currencies

# https://binance-docs.github.io/apidocs/futures/en/#position-information-user_data

positions = fapiPrivate_get_positionrisk()  # https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
positions_by_ids = exchange.index_by(positions, 'symbol')  # binance's symbol == ccxt's id
position = exchange.safe_value(positions_by_ids, market['id'])

print('-----------------------------------------')
pprint(position)
print('-----------------------------------------')
print('Your liquidation price for your', symbol', 'position is', position['liquidationPrice'])
```

**Comment by kroitor** [comment]
@cadmufasa let me know if the above does not answer your questions. I'd recommend to read through all the links mentioned above. It is even easier to just read through the entire Manual – most of the info is already there.

**Comment by cadmufasa** [comment]
Thanks for the information. I will read through the links and implement.

Regards.

**Comment by Damon1002** [comment]
> @cadmufasa answering your questions below one by one:
> 
> > How can one enter leverage on the Binance exchange using the API?
> 
> This is documented here:
> 
> * https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
> * https://binance-docs.github.io/apidocs/futures/en/#change-initial-leverage-trade
> 
> ```python
> import ccxt
> exchange = ccxt.binance({
>     'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
>     'options': {
>         'defaultType': 'future',
>     },
>     'apiKey': 'YOUR_API_KEY',  # https://github.com/ccxt/ccxt/wiki/Manual#authentication
>     'secret': 'YOUR_SECRET',
> })
> 
> markets = exchange.load_markets()  # https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
> symbol = 'BTC/USDT'
> market = exchange.market(symbol)  # https://github.com/ccxt/ccxt/wiki/Manual#methods-for-markets-and-currencies
> 
> # https://binance-docs.github.io/apidocs/futures/en/#change-initial-leverage-trade
> 
> exchange.fapiPrivate_post_leverage({  # https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
>     'symbol': market['id'],  # https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
>     'leverage': 10,  # target initial leverage, int from 1 to 125
> })
> ```
> 
> ↑ Your work with CCXT depends on how careful you were when you read the CCXT Manual, which I would recommend to read very carefully from top to bottom:
> 
> * https://github.com/ccxt/ccxt/wiki

Thanks for your answer. 
When i use the defaultType as future and place the order thereafter, it still executes the spot order instead of future order. What is the reason for this?  Thanks

```
import ccxt
exchange = ccxt.binance({
    'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    'options': {
        'defaultType': 'future',
    },
    'apiKey': '',  # https://github.com/ccxt/ccxt/wiki/Manual#authentication
    'secret': '',
})

markets = exchange.load_markets()  # https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
symbol = 'BTC/USDT'
market = exchange.market(symbol)  # https://github.com/ccxt/ccxt/wiki/Manual#methods-for-markets-and-currencies

exchange.create_limit_buy_order("XRP/USDT",50, 0.20)
```

**Comment by kroitor** [comment]
@Damon1002 
> When i use the defaultType as future and place the order thereafter, it still executes the spot order instead of future order. What is the reason for this? Thanks

- What's your version of CCXT?
- Can you post the verbose output precisely as explained here https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help?

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    'options': {
        'defaultType': 'future',
    },
    'apiKey': '',  # https://github.com/ccxt/ccxt/wiki/Manual#authentication
    'secret': '',
})

markets = exchange.load_markets()  # https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

exchange.verbose = True  # ←---------- add this after loading the markets

symbol = 'BTC/USDT'
market = exchange.market(symbol)  # https://github.com/ccxt/ccxt/wiki/Manual#methods-for-markets-and-currencies

exchange.create_limit_buy_order("XRP/USDT",50, 0.20)
```

**Comment by Damon1002** [comment]
> @Damon1002
> 
> > When i use the defaultType as future and place the order thereafter, it still executes the spot order instead of future order. What is the reason for this? Thanks
> 
> * What's your version of CCXT?
> * Can you post the verbose output precisely as explained here https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help?
> 
> ```python
> import ccxt
> 
> print('CCXT Version:', ccxt.__version__)  # ←------------ add this to print your runtime CCXT version
> 
> exchange = ccxt.binance({
>     'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
>     'options': {
>         'defaultType': 'future',
>     },
>     'apiKey': '',  # https://github.com/ccxt/ccxt/wiki/Manual#authentication
>     'secret': '',
> })
> 
> markets = exchange.load_markets()  # https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
> 
> exchange.verbose = True  # ←---------- add this after loading the markets
> 
> symbol = 'BTC/USDT'
> market = exchange.market(symbol)  # https://github.com/ccxt/ccxt/wiki/Manual#methods-for-markets-and-currencies
> 
> exchange.create_limit_buy_order("XRP/USDT",50, 0.20)
> ```

My ccxt version is CCXT Version: 1.18.985

And the output after I run the code of `exchange.create_limit_buy_order("XRP/USDT",50, 0.20)` :

```
{'info': {'symbol': 'XRPUSDT',
  'orderId': 994580495,
  'orderListId': -1,
  'clientOrderId': 'BUa4mys3x4AyNKcKdqsUwu',
  'transactTime': 1605004285281,
  'price': '0.20000000',
  'origQty': '50.00000000',
  'executedQty': '0.00000000',
  'cummulativeQuoteQty': '0.00000000',
  'status': 'NEW',
  'timeInForce': 'GTC',
  'type': 'LIMIT',
  'side': 'BUY'},
 'id': '994580495',
 'timestamp': 1605004285281,
 'datetime': '2020-11-10T10:31:25.281Z',
 'lastTradeTimestamp': None,
 'symbol': 'XRP/USDT',
 'type': 'limit',
 'side': 'buy',
 'price': 0.2,
 'amount': 50.0,
 'cost': 0.0,
 'average': None,
 'filled': 0.0,
 'remaining': 50.0,
 'status': 'open',
 'fee': None,
 'trades': None}
In [13]:

```

I am not sure how to post the verbose. So just post here now. Appreciate for your response.
<img width="1480" alt="Screen Shot 2020-11-10 at 9 31 30 pm" src="https://user-images.githubusercontent.com/33125087/98662885-8220f380-239c-11eb-94e2-58b6b031adc3.png">

**Comment by kroitor** [comment]
@Damon1002 your version is too old, you have to update it to 1.37.50+, this is step 1 in the troubleshooting sequence as described here: https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting. Let us know if that solves your problem or not. Thx!

**Comment by kroitor** [comment]
@Damon1002 in fact, i'd recommend to upgrade to the most recent version 1.37.51+, since Binance has updated their API recently.

**Comment by Damon1002** [comment]
> @Damon1002 your version is too old, you have to update it to 1.37.50+, this is step 1 in the troubleshooting sequence as described here: https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting. Let us know if that solves your problem or not. Thx!

I have tried to upgrade the ccxt to the newest version but after the installation , when i print out the version, it still showed the old version. So confused.
<img width="1149" alt="Screen Shot 2020-11-10 at 10 28 35 pm" src="https://user-images.githubusercontent.com/33125087/98668677-56097080-23a4-11eb-97a9-88ebdb363982.png">

**Comment by kroitor** [comment]
@Damon1002 The python you run does not correspond to the python where your pip packages are installed. This is usually the case on MacOS where you might have pip, python, pip3 and python3. Basically, you should configure your system properly.

**Comment by Damon1002** [comment]
> The python you run does not correspond to t

Thanks. I will try to work it out.

**Comment by farizkyyacob** [comment]
thanks a lot
