### ISSUE TITLE
bittrex v3 create order does not fill Price for market order

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#7218]
- OS: linux
- Programming Language version: python 
- CCXT version: 1.30.58

Bittrex v3 resposne does not fill Price (at least not on createOrder) - however as shown in #7213 - `fetch_order()` does.

What seems strange: fetch_order() seems to use API V2 (or v1 - not sure) - while create-order uses v3 (based on the URL).
My understanding of #7104 was that ccxt now does not use v2 of the API anymore.

Either way  i think the below result should have "price" filled (average is known - so price should be the same? )

``` python
import ccxt
ct = ccxt.bittrex({'apiKey': '<yourkey>', 'secret': '<yoursecret>')
_ = ct.load_markets()
amount = 1250.0
ct.verbose = True
o = ct.create_order('SC/USD', 'market', 'buy', amount, None)
print(o)
```

``` python

...
'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} {"marketSymbol":"SC-USD","direction":"BUY","type":"MARKET","quantity":"1250","timeInForce":"IMMEDIATE_OR_CANCEL"}

Response: POST https://api.bittrex.com/v3/orders 201 {'Date': 'Sun, 05 Jul 2020 08:27:32 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '369', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=xxxx; expires=Tue, 04-Aug-20 08:27:32 GMT; path=/; domain=.bittrex.com; HttpOnly; SameSite=Lax; Secure', 'Location': 'https://api.bittrex.com/v3/orders/313b098e-c094-4dc0-a3f8-cc521cef84a3', 'Request-Id': 'xxxx', 'Strict-Transport-Security': 'max-age=15768000', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'X-Download-Options': 'noopen', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': 'xxxx', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': 'xxx'} {"id":"313b098e-c094-4dc0-a3f8-cc521cef84a3","marketSymbol":"SC-USD","direction":"BUY","type":"MARKET","quantity":"1250","timeInForce":"IMMEDIATE_OR_CANCEL","fillQuantity":"1250.00000000","commission":"0.00767500","proceeds":"3.83750000","status":"CLOSED","createdAt":"2020-07-05T08:27:32.49Z","updatedAt":"2020-07-05T08:27:32.49Z","closedAt":"2020-07-05T08:27:32.49Z"}


------


{
    "id": "313b098e-c094-4dc0-a3f8-cc521cef84a3",
    "clientOrderId": None,
    "timestamp": 1593937652490,
    "datetime": "2020-07-05T08:27:32.490Z",
    "lastTradeTimestamp": 1593937652490,
    "symbol": "SC/USD",
    "type": "market",
    "side": "buy",
    "price": None,
    "cost": 3.8375,
    "average": 0.00307,
    "amount": 1250.0,
    "filled": 1250.0,
    "remaining": 0.0,
    "status": "closed",
    "fee": {
        "cost": 0.007675,
        "currency": "USD"
    },
    "info": {
        "id": "313b098e-c094-4dc0-a3f8-cc521cef84a3",
        "marketSymbol": "SC-USD",
        "direction": "BUY",
        "type": "MARKET",
        "quantity": "1250",
        "timeInForce": "IMMEDIATE_OR_CANCEL",
        "fillQuantity": "1250.00000000",
        "commission": "0.00767500",
        "proceeds": "3.83750000",
        "status": "CLOSED",
        "createdAt": "2020-07-05T08:27:32.49Z",
        "updatedAt": "2020-07-05T08:27:32.49Z",
        "closedAt": "2020-07-05T08:27:32.49Z"
    },
    "trades": None
}
```

**Comment by kroitor** [comment]
@xmatthias the problem is that market-type orders can't have a price by definition. They might have a filling price or an average price, but that is not known upon placing an order. I think adding a price for market orders would be against the theory. Lmk your thoughts.

**Comment by xmatthias** [comment]
Well its not known when placing the order, but the response does (also by definition) include avg or fill price, as a market order does fill immediately upon placement.

If not returning price for market orders is how it should work its no problem, and we can adapt to that.

If i were seeing this with other exchanges, i'd have long used another field ... But the bittrex case is the inconsistency (at least looking at 2 other examples).
For example for binance, market orders do get a price in the return field, and so does ftx.
Also kraken seems to work, but i think there price is in the order response directly(also for market orders).

https://github.com/ccxt/ccxt/blob/9c17fdffd95be978b380ec5daafb14beed4fc7a3/python/ccxt/binance.py#L1092-L1098

https://github.com/ccxt/ccxt/blob/9c17fdffd95be978b380ec5daafb14beed4fc7a3/python/ccxt/ftx.py#L858

**Comment by kroitor** [comment]
> If not returning price for market orders is how it should work its no problem, and we can adapt to that.

I'd say, the general approach for market orders should be to parse the average price or the filling price, if the order was filled or partially filled. Filling the `price` field for it would be wrong, if the order has not been fully-filled with a single trade. I'd agree that it should be brought to consistency, though. But in case of Bittrex we don't know if it was filled by one or more trades, so we can assign the `average` value, but we can't assign a value to the `price` field. We could probably change the other exchanges to match the common standard... What would you suggest in this case?

**Comment by xmatthias** [comment]
I don't necessarly disagree with your point - however:

[CCXT wiki's order structure](https://github.com/ccxt/ccxt/wiki/Manual#order-structure) does not contain average - so it's not a field that is unified (or the documentation is missing this ...).

If you're saying market orders should have no price, then they should never have a price, not for `createOrder()`, but also not for `fetchOrder()` (or any other variant returning order info).

For bittrex, price is currently `None` for `createOrder()` - but it's filled with average price for `fetchOrder()` (using the same order-id, obviously).

for binance, it's as pointed out above (filled as average for market orders) - and for other exchanges that's the case too.

---

#### Limit orders

Now comming back to the content of price for a limit order via an example:

Let's assume the following orderbook:

```
...
103
102
101  # ask
-------------Current spread
99   # bid
98
97
...
```

Now i place a limit buy order - and i'm willing to pay up to 102, so this is my limit price.
So (assuming a low volume pair / high enough amount) my average fill price might be 101.5 - or something between 101 and 102.

based on what you say above, i would expect ccxt to return 102 as "price" - but 101.5 as "average".

---

This becomes more interresting the more i look at it.
Looking at a kraken stoploss order (looked at that as part of something else this morning - but it's a good example here).
this order has 2 prices, a stop-price - and the actual fill price.

Now in theory, i'd expect "price" here to be filled with either None or the stopprice (not sure how you'd do that yet).
However, at least in krakens case, it's filled with the average (which would be wrong based on the above assumption - as this is in fact a market order).

The stop was placed at 61.294 - while the actual fill price was 61.041.

```
{'info': {'id': 'OJBSOM-ENYTP-XB526X',
  'refid': None,
  'userref': None,
  'status': 'closed',
  'reason': None,
  'opentm': 1594052219.8745,
  'closetm': 1594066853.1134,
  'starttm': 0,
  'expiretm': 0,
  'descr': {'pair': 'DASHEUR',
   'type': 'sell',
   'ordertype': 'stop-loss',
   'price': '61.294',
   'price2': '0',
   'leverage': 'none',
   'order': 'sell 0.33737053 DASHEUR @ stop loss 61.294',
   'close': ''},
  'vol': '0.33737053',
  'vol_exec': '0.33737053',
  'cost': '20.593',
  'fee': '0.053',
  'price': '61.041',
  'stopprice': '61.041',
  'limitprice': '0.000000',
  'misc': 'stopped',
  'oflags': 'fciq',
  'trades': ['TUQETM-PB3EZ-N6PZNY']},
 'id': 'OJBSOM-ENYTP-XB526X',
 'clientOrderId': None,
 'timestamp': 1594052219874,
 'datetime': '2020-07-06T16:16:59.874Z',
 'lastTradeTimestamp': None,
 'status': 'closed',
 'symbol': 'DASH/EUR',
 'type': 'stop-loss',
 'side': 'sell',
 'price': 61.294,
 'cost': 20.593,
 'amount': 0.33737053,
 'filled': 0.33737053,
 'average': 61.041,
 'remaining': 0.0,
 'fee': {'cost': 0.053, 'rate': None, 'currency': 'EUR'},
 'trades': [{'id': 'TUQETM-PB3EZ-N6PZNY',
   'order': 'OJBSOM-ENYTP-XB526X',
   'info': 'TUQETM-PB3EZ-N6PZNY',
   'timestamp': None,
   'datetime': None,
   'symbol': 'DASH/EUR',
   'type': None,
   'side': None,
   'takerOrMaker': None,
   'price': None,
   'amount': None,
   'cost': None,
   'fee': None}]}
```


---

Now while it's not "really" my problem (freqtrade can adjust to this) - i think removing price from all market-order return types (which i guess should also include stoploss-market, take-profit-market, ...) would break a lot of peoples code (mainly because average is not documented so far, so i doubt many people use it).

**Comment by xmatthias** [comment]
So just to summarize - is 'average' the unified parameter where users can expect the price to be there for all exchanges?

I'm asking this a bit provokative, because a quick search showed that it doesn't seem to be the case for all exchanges, and that several (not just the below) do have this field as "undefined" by default.

https://github.com/ccxt/ccxt/blob/4f2531e6217c02c300851e1c7dfbb352de570ba4/js/livecoin.js#L641
https://github.com/ccxt/ccxt/blob/4f2531e6217c02c300851e1c7dfbb352de570ba4/js/bitmart.js#L792
https://github.com/ccxt/ccxt/blob/4f2531e6217c02c300851e1c7dfbb352de570ba4/js/lykke.js#L517

If i understood your above explanation correctly, it should be either "filled price" - or "price" ?

**Comment by kroitor** [comment]
> So just to summarize - is 'average' the unified parameter where users can expect the price to be there for all exchanges?

I'd say – it's in the process of unification (not completely unified yet, but will be unified, eventually).

> I'm asking this a bit provokative, because a quick search showed that it doesn't seem to be the case for all exchanges, and that several (not just the below) do have this field as "undefined" by default.

That's right, this lib is a work in progress. Your contributions are welcome ;)

> If i understood your above explanation correctly, it should be either "filled price" - or "price" ?

- The `price` is for `limit` orders. It should show the price that was initially submitted with the order.
- The `average` price is for all orders (`limit`, `market`, etc...) – it should show the average actual filling price of the order.

Let me know if that does not answer your question.
