### ISSUE TITLE
Implement Bitstamp native OHLC endpoint into ccxt bitstamp fetchOHLCV function

### ISSUE THREAD

**Issue by lostless13** [ccxt/ccxt#7220]
- OS: Windows
- Programming Language version: Nodejs
- CCXT version: 1.30.59

Current, bitstamp implementation emulates the OHLCV endpoint but the v2 api now has a native OHLCV endpoint.
Endpoint: https://www.bitstamp.net/api/v2/ohlc/btcusd/?limit=1000&step=60
Docs: https://www.bitstamp.net/api/#ohlc_data

**Comment by kroitor** [comment]
@lostless13 will add that shortly, thank you!

**Comment by lostless13** [comment]
Found a minor implementation issue. Parameter should be 'step' not 'interval'. Submitted pull request with fix: https://github.com/ccxt/ccxt/pull/7225
