### ISSUE TITLE
Adjusting Leverage on Binance

### ISSUE THREAD

**Issue by cadmufasa** [ccxt/ccxt#7221]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

=> ADJUSTING LEVERAGE
--------------------------------------------------
Hello,

I was running the following Python code (for Binance):

	import ccxt
	from pprint import pprint
	exchange = ccxt.binance({
    		'enableRateLimit': True,
    		'apiKey': 'YOUR_API_KEY',
    		'secret': 'YOUR_SECRET',
    		#    'options': {
    		#    'defaultType': 'future',  # or 'margin'
    		#}
		})

	exchange.load_markets()
	symbol = 'BTC/USDT'
	market = exchange.market(symbol)
	print('Order types supported by the', symbol, 'spot market:')
	pprint(market['info']['orderTypes'])
For the SPOT Markets, I got:
['LIMIT', 'LIMIT_MAKER', 'MARKET', 'STOP_LOSS_LIMIT', 'TAKE_PROFIT_LIMIT']

I un- commented the "options" area (to look for the FUTURES Markets) above, I got the following:

['LIMIT',
 'MARKET',
 'STOP',
 'STOP_MARKET',
 'TAKE_PROFIT',
 'TAKE_PROFIT_MARKET',
 'TRAILING_STOP_MARKET']

So - it looks as though the FUTURES market has more options than the SPOT market - thankfully - but I am not seeing a way whereby I can enter/adjust the leverage. How can one enter leverage on the Binance exchange using the API?

My understanding is pretty much expressed in this video: https://youtu.be/VytoTXKbfkg?t=663

For example, say I want to use 10X leverage or 20X leverage. I do not see a way that I can set this using the API. Am I missing something? Do I need to go through the UI on the exchange and set it there?

**Comment by kroitor** [comment]
@cadmufasa hi! Plz don't duplicate issues, I will reply in your original post here as soon as I can: https://github.com/ccxt/ccxt/issues/7217#issuecomment-653925456. Duplicating questions does not speed up getting the answer.

**Comment by cadmufasa** [comment]
Hi there, I thought that the Original Message had been closed because this is what I was seeing on my side. I did not know how to "reopen" it and was not sure that anyone else would see it (since it was marked as "Closed")

![image](https://user-images.githubusercontent.com/66542549/86546988-ec142280-befc-11ea-9f9e-6e1c9612cfe6.png)

**Comment by kroitor** [comment]
Answered here: https://github.com/ccxt/ccxt/issues/7217#issuecomment-653973403
