### ISSUE TITLE
Finding the current Profit and Loss on Binance using Python

### ISSUE THREAD

**Issue by cadmufasa** [ccxt/ccxt#7222]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Hello,

I had another message in play; however, it was closed before I could ask another question. I copied the text and  placed it below.

How can I find the Current Profit and Loss for a working Position? My sense is that I could use "fetch_balance" to track the Current Profit and Loss of all combined trades? If so, is there any way of tracking the individual trade - like mentioned here:https://youtu.be/VytoTXKbfkg?t=545

TIA

**Comment by kroitor** [comment]
Duplicate, see my reply here: https://github.com/ccxt/ccxt/issues/7221#issuecomment-653966328

**Comment by kroitor** [comment]
Answered here: https://github.com/ccxt/ccxt/issues/7217#issuecomment-653975599
