### ISSUE TITLE
Finding the Liquidation Level on Binance using Python

### ISSUE THREAD

**Issue by cadmufasa** [ccxt/ccxt#7223]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

Hello,

I had another issue open; however, I had follow up questions. The message was closed before I could update it.  I copied and pasted the text below.

How can one find the Liquidation Price (as it would be nice to set up a STOP-MARKET order to keep from being liquidated)?
From the message: #5769
And this info here: https://www.reddit.com/r/BitMEX/comments/dil0qm/using_ccxt_to_combine_get_position_with/

self.exchange.private_get_position({  #     ↓ HERE
    'filter': self.exchange.json({"isOpen":True, "symbol":"XBTUSD"})
})

But it was for Bitmex. Not sure if it would work on Binance.
Question: does private_get_position work with the Binance exchange? If not, what is the equivalent?

TIA

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/7221#issuecomment-653966328

**Comment by cadmufasa** [comment]
Hi again, I thought the Original Message (7221) had been closed because of the "Closed" label I was seeing on my side.  I took a screen shot and inserted it below. If there is something else I should have done, let me know. Regards.
![image](https://user-images.githubusercontent.com/66542549/86547067-47deab80-befd-11ea-8f87-f20255b41731.png)

**Comment by kroitor** [comment]
Answered here: https://github.com/ccxt/ccxt/issues/7217#issuecomment-653977660
