### ISSUE TITLE
Can not seem to get the TRAILING_STOP_MARKET order on Binance Futures working

### ISSUE THREAD

**Issue by marcoismobile** [ccxt/ccxt#7224]
- OS: Linux
- Programming Language version: Python 3.8.3
- CCXT version: 1.30.45

According to the exchange data directly from the Binance API and also from the return data from CCXT the following order types should be possible:

'type': ['LIMIT', 'MARKET', 'STOP', 'STOP_MARKET', 'TAKE_PROFIT', 'TAKE_PROFIT_MARKET', '**TRAILING_STOP_MARKET**']

And according to the Binance Futures API documentation the following extra params are possible:

**activationPrice** | DECIMAL | NO | Used with TRAILING_STOP_MARKET orders, default as the latest price(supporting different workingType)
**callbackRate** | DECIMAL | NO | Used with TRAILING_STOP_MARKET orders, min 0.1, max 5 where 1 for 1%

But when I try to create a **TRAILING_STOP_MARKET** order I get a error message back from the Binance Futures API:

_binance {"code":-1102,"msg":"A mandatory parameter was not sent, was empty/null, or malformed."}_

So the question:
Is TRAILING_STOP_MARKET already supported by CCXT, or am I missing some (undocumented) parameter?
The other order types I am using like LIMIT, STOP_MARKET and TAKE_PROFIT are working perfectly fine.

```
        params = {
            'newClientOrderId': 'testing',
            'activationPrice': 9500,
            'callbackRate': 0.2,
            'workingType': 'CONTRACT_PRICE',
            'reduceOnly': True
        }
        await exchange.createOrder('BTCUSDT', 'TRAILING_STOP_MARKET', 'sell', 0.001, 9500, params)
```

```
binance {"code":-1102,"msg":"A mandatory parameter was not sent, was empty/null, or malformed."}
```

**Comment by kroitor** [comment]
1. How do you initialize the exchange instance?
2. Please paste your verbose request/response. Use GitHub markdown for posting the output.

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

3. This looks wrong:

```
await exchange.createOrder('BTCUSDT', 'TRAILING_STOP_MARKET', 'sell', 0.001, 9500, params)
```

↑ Should be `BTC/USDT`.

4. These values should be strings:

```Python
        params = {
            'newClientOrderId': 'testing',
            'activationPrice': '9500',  # ←---------------------
            'callbackRate': '0.2',  # ←---------------------
            'workingType': 'CONTRACT_PRICE',
            'reduceOnly': "true",  # ←---------------------
        }
```

**Comment by marcoismobile** [comment]
I have tested both BTCUSDT and BTC/USDT, but I was already using the BTCUSDT for the other order types and that worked perfectly fine. The same for the string values or not in the params (which I tested both) where also working fine for the other order types.

```

**Comment by marcoismobile** [comment]
Exchange init:

```

**Comment by marcoismobile** [comment]
@kroitor I have found the problem:

It seems the quantity is also mandatory, so when I added the following in the params dict it was posted successfully:

'quantity': '0.001',

**Comment by kroitor** [comment]
@marcoismobile alright, thx for reporting back, we will add the necessary edits on our side.

**Comment by marcoismobile** [comment]
@kroitor So to confirm, CCXT should convert the amount to the quantity argument automatically for Binance Futures with the TRAILING_STOP_MARKET order type? Would that be the edits from your side?

Thanks in advance for the quick support!

**Comment by kroitor** [comment]
@marcoismobile 

> @kroitor So to confirm, CCXT should convert the amount to the quantity argument automatically for Binance Futures with the TRAILING_STOP_MARKET order type? Would that be the edits from your side?

Yep, that's correct, we will add that within a couple of hours and it should work fine a new version of CCXT from there (there will be no need to send the `quantity` in `params`).

**Comment by kroitor** [comment]
@marcoismobile we've added the edits discussed above, should be ok in CCXT version 1.30.63+. Thanks again for your feedback!

**Comment by marcoismobile** [comment]
@kroitor I can confirm it is now working flawless!
Thanks again for the (super) fast fix :+1:

**Comment by loitd** [comment]
Thanks @marcoismobile , I have same problem with Trailing type and fixed using your comment.
