### ISSUE TITLE
eterbase. HMAC signature cannot be verified

### ISSUE THREAD

**Issue by yen-a** [ccxt/ccxt#7226]
- OS: Ubuntu 20.04 LTS (GNU/Linux 5.4.0-37-generic x86_64)
- Programming Language version: PHP 7.4.3
- CCXT version: ccxt-1.30.65

```

    $uid    = "";
    $apiKey = "";
    $secret = "";
    $name   = "eterbase";
    
    $exchange_class = "\\ccxt\\$name";
    $exchange = new $exchange_class(array(
        'uid'    => $uid,
        'apiKey' => $apiKey,
        'secret' => $secret,
        'enableRateLimit' => true
    ));

    try {
        $balance = $exchange->fetch_balance();
    } catch (Exception $E) {
        var_dump($E->getMessage());
    };
```

```
"eterbase {"message":"HMAC signature cannot be verified"}"
```
I can’t figure out what the problem is. I wrote to the Eterbase support team, they answered 'HMAC error means that the security headers of request was not prepared according to API definition. The problem can be wrong accountid (uid), apikey or apisecret or some problem with ccxt library (wrong calculation of security headers) '.

**Comment by kroitor** [comment]
@yen-a i'll check for that, will be back to you shortly.

**Comment by kroitor** [comment]
@yen-a found a minor bug in PHP (it was ok in JS and Python, but in PHP we had a minor transpilation issue). If you update your PHP CCXT package to version 1.30.67+ it will work fine. Thank you for reporting! Let us know if you still have difficulties with it after upgrading your version.
