### ISSUE TITLE
Binance quote order qty rounding issue

### ISSUE THREAD

**Issue by willoughby** [ccxt/ccxt#7227]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows
- Programming Language version: Node JS
- CCXT version: 1.30.63

```
const order = await this.exchange.createOrder(
                'ZRX/BTC',
                'market,
                'buy',
                3,
                null,{}
);
```

There is an issue with the rounding/conversion, some orders are not meeting the full quantity due to the latest market order changes, how do i disable this change as its causing big problems! I also do not understand why this is the default behaviour as binance is the only exchange to support this reverse method it should of been opted into rather than forced upon as its a breaking change.

```
"info" : {
				"symbol" : "ZRXBTC",
				"orderId" : NumberInt(130843631),
				"orderListId" : NumberInt(-1),
				"clientOrderId" : "x-KL068UUMe5WJpuLZu7vXQP6RdrhMKu",
				"transactTime" : 1594052510310,
				"price" : "0.00000000",
				"origQty" : "2.00000000",
				"executedQty" : "2.00000000",
				"cummulativeQuoteQty" : "0.00008504",
				"status" : "FILLED",
				"timeInForce" : "GTC",
				"type" : "MARKET",
				"side" : "BUY",
				"fills" : [
					{
						"price" : "0.00004252",
						"qty" : "2.00000000",
						"commission" : "0.00003765",
						"commissionAsset" : "BNB",
						"tradeId" : NumberInt(16636098)
					}
				]
			},
			"id" : "130843631",
			"clientOrderId" : "x-KL068UUMe5WJpuLZu7vXQP6RdrhMKu",
			"timestamp" : 1594052510310,
			"datetime" : "2020-07-06T16:21:50.310Z",
			"lastTradeTimestamp" : null,
			"symbol" : "ZRX/BTC",
			"type" : "market",
			"side" : "buy",
			"price" : 0.00004252,
			"amount" : NumberInt(2),
			"cost" : 0.00008504,
			"average" : 0.00004252,
			"filled" : NumberInt(2),
			"remaining" : NumberInt(0),
			"status" : "closed",
			"fee" : {
				"cost" : 0.00003765,
				"currency" : "BNB"
			},```

**Comment by kroitor** [comment]
@willoughby hi! Can you plz clarify a bit? Namely, which field is in question, what you expect, what you get, etc? Ideally, just post your full verbose request + response, as explained here:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

↑ We always ask for it regardless of the issue.

**Comment by willoughby** [comment]
I see what the problem is, when you post a price with a market order ccxt recalculates the qty, thats not something we would of expected

**Comment by kroitor** [comment]
@willoughby you should set the price to `undefined` instead of `null`. This is documented in the Manual.

**Comment by willoughby** [comment]
For example if i made a market order of 4 ZRX and passed in price it would enter the new quote order quantity code and would convert my order

**Comment by willoughby** [comment]
thats fine, :) lets close up
