### ISSUE TITLE
CoinGecko

### ISSUE THREAD

**Issue by Modrx** [ccxt/ccxt#7229]
Hello,

When can we use CoinGecko data with CCXT?

Thank you!

**Comment by kroitor** [comment]
Duplicate: 

- https://github.com/ccxt/ccxt/issues/3543
- https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar
- https://github.com/ccxt/ccxt/wiki/FAQ#when-will-you-add-the-support-for-an-exchange-requested-in-the-issues
- https://github.com/ccxt/ccxt/wiki/FAQ#whats-your-progress-on-adding-the-feature-foo-that-was-requested-earlier-how-do-you-do-implementing-exchange-bar

You can try these PRs and help test them:

- https://github.com/ccxt/ccxt/pull/3565
- https://github.com/ccxt/ccxt/pull/6610
