### ISSUE TITLE
fetchTickers() methods for Bybit returns an array with missing \ between base and quote currencies of the symbol

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#7232]
- OS: Ubuntu 18.04.4 LTS
- Programming Language version: Python 3.6.9
- CCXT version: 1.27.54

```
import ccxt
t = ccxt.bybit()
t = t.fetchTickers()
t.keys()
```

```
dict_keys(['BTCUSD', 'ETHUSD', 'EOSUSD', 'XRPUSD', 'BTCUSDT'])
```

Hello, I don't know if it's a bug or not but I notice that the `fetchTickers()` method for Bybit returns a dictionary in which keys don't have the standard symbol name with `/` between the base and the quote for the market.

**Comment by kroitor** [comment]
Hi! This is mostly because those symbols actually stand for contracts (not spot pairs), and we're working on the unification for contract symbols to get it delivered as soon as we can. We hope to get this aspect resolved asap.

**Comment by Kinzowa** [comment]
Thanks for the answer Igor, keep up the good work.
