### ISSUE TITLE
fetchOpenOrder function isn't working on Finance

### ISSUE THREAD

**Issue by nlakshman** [ccxt/ccxt#7236]
- OS: macOS Catalina 10.15.5
- Programming Language version: Python 2.7.16
- CCXT version: 1.30.69 (pip installed it yesterday)

```
import ccxt
import datetime
import time
import random
from pprint import pprint

def run():
    binance = ccxt.binance({
        'apiKey': XXX,
        'secret': XXX,
        'enableRateLimit': True,
        'timeout': 30000
    })
    print(binance)
    if binance.has['fetchOrders']:
       binance.load_markets()
       depth = binance.fetch_order_book(symbol='ETH/BTC')
       print(" ASK:", depth['asks'][0], depth['asks'][len(depth['asks']) - 1])
       print(" BID:", depth['bids'][0], depth['bids'][len(depth['bids']) - 1])
       lowestAsk = depth['asks'][0][0]
       highestAsk = depth['asks'][len(depth['asks']) - 1][0]
       highestBid = depth['bids'][0][0]
       lowestBid = depth['bids'][len(depth['bids']) - 1][0]
       print("Current Diff:", highestBid - lowestAsk)
       print("Possible Diff:", highestBid, lowestBid, highestAsk, lowestAsk)
    if binance.has['fetchOpenOrders']:
       depth = binance.fetchOpenOrders('ETH/BTC')
       print("Open Order Book: ", depth)
    if binance.has['fetchClosedOrders']:
       depth = binance.fetchClosedOrders(symbol='ETH/BTC')
       print("Closed Order Book: ", depth)

run()

```

```
Binance
 ASK: [0.025778, 0.334] [0.025895, 0.239]
 BID: [0.025777, 160.417] [0.025659, 603.018]
Current Diff: -9.999999999975306e-07
Possible Diff: 0.025777 0.025659 0.025895 0.025778
Open Order Book:  []
Closed Order Book:  []
```

Hello!

The code I attached is just a test of the fetchOpenOrders function on Binance, but my actual codebase, which uses CCXT Pro, has the same persistence issue. As you can see in the terminal output, the fetch_order_book function works correctly, but the fetchOpenOrders and fetchClosedOrders return empty lists. Binance does in fact support fetchOpenOrders and fetchClosedOrders based on what binance.has returned, so is there anything I must to do fix this issue?

Thanks for your time!

**Comment by kroitor** [comment]
Hi! Have you created any limit orders with Binance to actually see them with fetchOpenOrders? The `fetchOrderBook` is a method of a public API that shows the public orderbook. In contrary, the `fetchOpenOrders` and `fetchClosedOrders` return the orders you've placed on that orderbook with `createOrder` or via the website. Namely, `fetchOpenOrders` returns your private open orders (if any), and `fetchClosedOrders` returns your private closed (filled) orders, if any. The difference is explained in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual

I would highly recommend to read the entire Manual from top to bottom to understand how exchanges work – it will save you a ton of time.

Let us know if that does not answer your quesiton.

**Comment by nlakshman** [comment]
Thanks! Makes sense.
