### ISSUE TITLE
Authentication with Coinbase Pro fails with "Invalid Passphrase"

### ISSUE THREAD

**Issue by rueiwoqp** [ccxt/ccxt#7237]
Requests to Coinbase Pro fail with 401 and "Invalid Passphrase". I verified the password is the same that I used to log in to teh website.  I even tried changing my password to only alphanumeric [A-Za-z0-9] characters.

**NOTE**: I see the correct password in the request headers `CB-ACCESS-PASSPHRASE`

- OS: `Mac OSX`
- Programming Language version: `node v14.5.0`
- CCXT version: `^1.30.71`

```
'use strict';
const ccxt = require ('ccxt');
const cTable = require('console.table');

(async function () {
  let exchange = new ccxt.coinbasepro({
      password: '',
      apiKey: '',
      secret: '',
      enableRateLimit: true,
      proxy: 'http://localhost:8080/',
      timeout: 30000,
    });

  let balances = await exchange.fetchBalance();
  balances = balances && balances.total;

  if (balances) {
    console.table(
      Object.keys(balances).map((coin) => {
        return { coin: coin, balance: balances[coin] }
      })
    );
  }
}) ();
```

**Coinbase Pro output:**
```
(node:52581) UnhandledPromiseRejectionWarning: AuthenticationError: coinbasepro GET http://localhost:8080/https://api.pro.coinbase.com/accounts 401 Unauthorized {"message":"Invalid Passphrase"}
```

**Comment by kroitor** [comment]
@rueiwoqp please, read this:

- https://help.coinbase.com/en/pro/other-topics/api/how-do-i-create-an-api-key-for-coinbase-pro

In short, your Coinbase Pro API passphrase is not your login password. It's a passphrase specifically assigned when you're creating an API keypair with the Coinbase Pro website.

Let us know if that does not answer your question.

**Comment by rueiwoqp** [comment]
Thanks! I looked through the github issues but didn't find anything.  I guess the next person will find it here and not feel dumb. 😆
