### ISSUE TITLE
Use CCXT to invest in top 10 cryptos and rebalance each week

### ISSUE THREAD

**Issue by vikaskedia** [ccxt/ccxt#724]
I want to invest in top 10 cryptos and rebalance each week. Is using ccxt for this a good idea. I am a programmer so I can add features etc.. if needed.

Or should I be using some other library.

**Comment by kroitor** [comment]
Hi!

> Is using ccxt for this a good idea. 

Yes )

> I am a programmer so I can add features etc...

That may be needed as well ) We appreciate all help. 
I'd recommend to start from here:
- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/tree/master/examples
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

More about your particular task:
- https://github.com/ccxt/ccxt/issues/71
- https://github.com/ccxt/ccxt/issues/721
- https://github.com/ccxt/ccxt/search?q=withdraw&type=Issues
- https://github.com/ccxt/ccxt/search?q=withdraw&type=Commits
- https://github.com/ccxt/ccxt/search?q=deposit&type=Issues
- https://github.com/ccxt/ccxt/search?q=deposit&type=Commits
- https://github.com/ccxt/ccxt/search?q=fetchDepositAddress&type=Commits

> Or should I be using some other library.

I'd recommend reading all of the above, then comparing against other libraries, if you find any ;)

**Comment by vikaskedia** [comment]
places like https://www.bitwiseinvestments.com/fund charge 2.5% annually and then 3% at withdrawal .. to do something a script can do .. for a 100K investment over 5 years they will take away $15,500 in fees.

that sounds crazy high fees for a little bit of programming.

Am I missing something here?

**Comment by kroitor** [comment]
@vikaskedia would you sell your lifetime reputation for $15500 / year ? How about risk? I don't think this whole thing boils down to just a little bit of programming, I believe, there's more to it, there's a ton of economic reasons that should be factored into this to understand their percentages. 

However, I'm not familiar with their structure, this might be their arbitrary choice as well. In this case, I guess, it could go like this:

– Hey, man, why don't we set 3% on withdrawals?
– Sounds good! Let's do it!

**Comment by vikaskedia** [comment]
> How about risk?

Can you please enumerate some of the risks for which they are charging 15.5% of the amount invested.

Since its 15,500 for a 100K investment. What is the investment is 1 million ?

**Comment by kroitor** [comment]
> Can you please enumerate some of the risks for which they are charging 15.5% of the amount invested.

- A risk of being hacked
– A risk of making wrong investment decisions
– A risk of not managing to run it properly
– A risk of altcoin/shitcoin crash

A typical fund makes hundreds and thousand of related decisions daily. Do you think it's hard to make a mistake in these circumstances with complex systems and transactions? Haven't you heard of other funds and banks crashing before?

Basically, when you say something is not worth 3%/year, you can only prove your claims by making a better alternative with lower fees. So, I don't really see any point in paying too much attention to their schedule, 3% isn't something all that surprising to me.

**Comment by vikaskedia** [comment]
>  A risk of making wrong investment decisions
its an index fund .. so they are not making investment decisions and 

>  A risk of altcoin/shitcoin crash
there are no risk of altcoin/shitcoin crashing since the investment is in top 10 coins ..

> A risk of being hacked
Yes. But if all I have api access to poloniex for the client I am shifting the risk to poloniex getting hacked.

> A risk of not managing to run it properly

I think most of us can write bug free 100 lines of code. And if there is a bug the worse that happens is that the rebalance for the week is not accurate.

>3% isn't something all that surprising to me.
the cost is closer to 15.5% when held for an average of 5 years.

Just seems too high to me ..

**Comment by kroitor** [comment]
> I think most of us can write bug free 100 lines of code. And if there is a bug the worse that happens is that the rebalance for the week is not accurate.

Just do it then ) You are missing millions, because other guys are taking 3% for that, so, if you will write 100 lines of code that will do the same, say, today, or, in a week or a month, then you can run your own fund, right? So, if you're not running your own fund yet, I guess you haven't tried creating and running one ) It's that simple to me.

> Just seems too high to me ..

No big deal, really. Many exchanges have high fiat withdrawal fees, up to 5%, depends on the method, the amount, multiple factors... Welcome to economy )

**Comment by vikaskedia** [comment]
> Welcome to economy )

Thanks 👍 

You are right i have a lot to learn about the economy.
