### ISSUE TITLE
Id in orderbook

### ISSUE THREAD

**Issue by Alisonsilva47** [ccxt/ccxt#7241]
Hello, I'm trying to develop an exchange application. In it, the "order book" shows the amount, the price and the "id", so I haven't found similar examples from other brokers. Is there any way to change this, using parseOrderBook or another method? (I apologize for any errors, I don't speak English and I'm using a translator)

**Comment by kroitor** [comment]
Hi! Your question is a bit vague, can you elaborate more? Which specific exchange is it? Ideally, paste some code that we could see what you're trying to do (make it short but complete), or, alternatively, use more words to clarify the question or difficulty you're having.

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by npomfret** [comment]
I'm also not sure I understand the question, but here is some information:

ccxt has a method called `fetchOrderBook` (and sometimes `fetchOrderBooks`) which typically return what is called a *level-2 orderbook*.  An orderbook takes the following form:

```
{
  bids: [
    [// the first entry represents the 'best' bid
      8888.93, // price
      7.0 // amount
    ],
    [
      8888.92, // price
      3.3 // amount
    ],
    [
      8888.90, // price
      19.1 // amount
    ],
    ... // and so on
  ],
  asks: [
    [// the first entry represents the 'best' ask
      8888.99, // price
      1.0 // amount
    ],
   [
      8889.2, // price
      1.1 // amount
   ],
   [
      8889.8, // price
      18.7 // amount
   ],
   ... // and so on
  ],
} 

```
A *level-2 orderbook* is one where each entry in the bids / asks array contains a `[price, amount]` pair.  Each row in the array represents all orders that share the same price.  *Level-2 orderbooks* **do not** contain orders or order-ids.  If there are multiple orders at the same price level, the exchange adds up all the amounts for all the orders and returns them as a single row in the bids/asks array.  If there are no orders at a particular price, then there is no entry in the array for that price (so you never see for example an entry like this: `[8888.99, 0]` ).

A *level-3 orderbook* is one that contains individual orders and so will have orderIds.  I believe the coinfloor websocket-api (and possibly the coinbasepro restapi) have methods that return level-3 order books.  But they are generally uncommon. 

There is no real need to write a *parser* for `fetchOrderbook` data as ccxt does this for you.

**Comment by Alisonsilva47** [comment]
Here is the code snippet from the Orderbook. In the case of this exchange, it returns within the bids and asks, the "amount, the" price ", and also the" id ", the" id "I can't return on ccxt, and that's my problem. whether there is a possibility that I will return the three.


Below is the code snippet ( js ):

    async fetchOrderBook (symbol, limit = undefined, params = {}) {
        await this.loadMarkets ();
        const market = this.market (symbol);
        const request = {
            'coin': market['base'],
        };
        const response = await this.publicGetCoinOrderbook (this.extend (request, params));
        const timestamp = this.safeTimestamp (response, 'timestamp');
        return this.parseOrderBook (response, 'id', 'bids', 'asks', 'price', 'amount');
    }

. E ele retorna valores como este:

{'bids': [[50790.0, 0.21460918], [50708.0, 0.06686457], [50708.0, 0.15495152], [50675.0, 0.10118619], [50670.0, 0.5], [50658.0, 0.06434892], [50650.0, 0.41861019], [50650.0, 0.21063713]]......    'asks': [[50852.13, 0.06776883], [50852.74, 0.075], [50855.79, 0.07531], [50861.45, 0.00306582], [50876.98, 0.00621106] .......

**Comment by kroitor** [comment]
@Alisonsilva47 make sure to understand the difference between L2 and L3 orderbooks. Let us know if the above post kindly provided by @npomfret does not answer your question. Closing this for now, feel free to reopen it or just ask further questions, if any.
