### ISSUE TITLE
[FTX] How  to fetch current positions on FTX Futures?

### ISSUE THREAD

**Issue by Ravisut** [ccxt/ccxt#7242]
![12333](https://user-images.githubusercontent.com/33305346/86951562-e7a96d00-c17b-11ea-8e12-13ffa05a5d57.png)

For example
i want to get Notional size Value in current position and return 0.04

```
   value = exchange.private_get_position()
AttributeError: 'ftx' object has no attribute 'private_get_position'
```

Thanks for any help

**Comment by kroitor** [comment]
For FTX the correct implicit method name is `private_get_positions` (not `private_get_position`).

Duplicates:

- https://github.com/ccxt/ccxt/issues/6860#issuecomment-620414108
- https://github.com/ccxt/ccxt/issues/6362#issuecomment-573367512
- https://github.com/ccxt/ccxt/search?q=ftx+position&type=Issues
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

I highly recommend to read the Manual from top to bottom – it will really save your time. Also, if you have an issue, try using the search first. If you have an issue or question, then, most likely, someone already had the same issue or question, and you can find it if you use a proper search query.

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

Let us know if the above does not help.
