### ISSUE TITLE
Documentation modification suggestion about precision price for Bitmex

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#7243]
Hello,

I noticed that `market['precision']['price']` returned for BitMEX exchange is 0.5 (XBTUSD) and 0.05 (ETHUSD) and that these values are the nearest $0.5 whereas the documentation state it's the maximum number of decimal digits. This is not an issue nor a question but a suggestion to update the documentation.

Thanks for the good work in providing such great API!

**Comment by kroitor** [comment]
@Kinzowa the type of that value depends on `exchange.precisionMode`. When `exchange.precisionMode` is equal to the `DECIMAL_DIGITS` constant – then precision means integers (decimal digits after the dot). When `exchange.precisionMode` is equal to `TICK_SIZE` – it's a float (minimal step between two `price` values). So, it depends on which `exchange.precisionMode` is used for the exchange in question. More precisionModes have been added after that was documented. And the Manual is missing the explanation on `exchange.precisionMode`, you're 100% right. The documentation is a bit outdated indeed, I will do my best to update it asap to explain it properly in the Manual. Thank you for the suggestion!

**Comment by Kinzowa** [comment]
Hi Igor, thanks for your answer.
