### ISSUE TITLE
[poloniex] weird fee on trade

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#7246]
This trade has a (approximately) 15% fee (should be much less https://poloniex.com/fee-schedule - 0.125%). I thing the fee cost needs to be the fee rate * the order cost.  So in this case:

0.00809837 * 0.00125 = 0.00001012BTC

```
{
  "id": "474525558",
  "fee": {
    "cost": 0.00125,
    "rate": 0.00125,
    "currency": "BTC"
  },
  "cost": 0.00809837,
  "info": {
    "fee": "0.00125000",
    "date": "2020-07-09 16:14:54",
    "rate": "0.000270860000",
    "type": "sell",
    "total": "0.00809837",
    "amount": "29.89873335",
    "tradeID": "8980",
    "category": "exchange",
    "feeDisplay": "0.00125000 BTC (0.125%)",
    "orderNumber": "12427578259",
    "globalTradeID": 474525558
  },
  "side": "sell",
  "type": "limit",
  "order": "12427578259",
  "price": 0.00027086,
  "amount": 29.89873335,
  "symbol": "XTZ/BTC",
  "datetime": "2020-07-09T16:14:54.000Z",
  "timestamp": 1594311294000
}
```

**Comment by npomfret** [comment]
... it looks like the fees are being reported correctly for 'buy' trades, but not for 'sell' trades.  I have lots of examples.

**Comment by npomfret** [comment]
```
{
  "id": "472742941",
  "fee": {
    "cost": 0.00125,
    "rate": 0.00125,
    "currency": "BTC"
  },
  "cost": 0.00273563,
  "info": {
    "fee": "0.00125000",
    "date": "2020-06-27 19:27:19",
    "rate": "0.000260990000",
    "type": "sell",
    "total": "0.00273563",
    "amount": "10.48176374",
    "tradeID": "8506",
    "category": "exchange",
    "feeDisplay": "0.00125000 BTC (0.125%)",
    "orderNumber": "11224918123",
    "globalTradeID": 472742941
  },
  "side": "sell",
  "type": "limit",
  "order": "11224918123",
  "price": 0.00026099,
  "amount": 10.48176374,
  "symbol": "XTZ/BTC",
  "datetime": "2020-06-27T19:27:19.000Z",
  "timestamp": 1593286039000
}
```

**Comment by kroitor** [comment]
@npomfret thx for reporting, will get this fixed shortly!

**Comment by npomfret** [comment]
The fee here is 46%

```
{
  "id": "471755316",
  "fee": {
    "cost": 0.00125,
    "rate": 0.00125,
    "currency": "BTC"
  },
  "cost": 0.00268608,
  "info": {
    "fee": "0.00125000",
    "date": "2020-06-21 05:32:49",
    "rate": "0.000279320000",
    "type": "sell",
    "total": "0.00268608",
    "amount": "9.61652594",
    "tradeID": "8138",
    "category": "exchange",
    "feeDisplay": "0.00125000 BTC (0.125%)",
    "orderNumber": "10414788064",
    "globalTradeID": 471755316
  },
  "side": "sell",
  "type": "limit",
  "order": "10414788064",
  "price": 0.00027932,
  "amount": 9.61652594,
  "symbol": "XTZ/BTC",
  "datetime": "2020-06-21T05:32:49.000Z",
  "timestamp": 1592717569000
}
```

**Comment by kroitor** [comment]
@npomfret actually, this looks like a bug on Polo's side. If you check the feeDisplay, it's always 0.00125 BTC, which is obviously wrong. Have you tried sending these outputs to their tech support?

**Comment by npomfret** [comment]
The fee here is 0.01%

```
{
  "id": "464597750",
  "fee": {
    "cost": 0.0009,
    "rate": 0.0009,
    "currency": "USDC"
  },
  "cost": 62.15206177,
  "info": {
    "fee": "0.00090000",
    "date": "2020-05-11 21:58:39",
    "rate": "8572.816421360000",
    "type": "sell",
    "total": "62.15206177",
    "amount": "0.00724990",
    "tradeID": "3901812",
    "category": "exchange",
    "feeDisplay": "0.00090000 USDC (0.09%)",
    "orderNumber": "192402299330",
    "globalTradeID": 464597750
  },
  "side": "sell",
  "type": "limit",
  "order": "192402299330",
  "price": 8572.81642136,
  "amount": 0.0072499,
  "symbol": "BTC/USDC",
  "datetime": "2020-05-11T21:58:39.000Z",
  "timestamp": 1589234319000
}
```

**Comment by npomfret** [comment]
> @npomfret actually, this looks like a bug on Polo's side. If you check the feeDisplay, it's always 0.00125 BTC, which is obviously wrong. Have you tried sending these outputs to their tech support?

No, but I will do.

**Comment by kroitor** [comment]
@npomfret alright, thanks! Please report back, if/when they reply.

**Comment by npomfret** [comment]
Until this is fixed in the exchange, here's the bodge I've put into my codebase:

                if(trade.fee.cost === trade.fee.rate) {
                    const {baseCcy, quoteCcy} = Util.splitSymbol(trade.symbol);
                    let feeCurrency = quoteCcy;
                    if(trade.info.feeDisplay.indexOf(baseCcy) >= 0) {
                        feeCurrency = baseCcy;
                    }

                    let feeCost;
                    if(feeCurrency === quoteCcy) {
                        feeCost = trade.cost * trade.fee.rate;
                    } else {
                        feeCost = trade.amount * trade.fee.rate;
                    }

                    trade.fee.cost = feeCost;
                    trade.fee.currency = feeCurrency;
                }

**Comment by kroitor** [comment]
@npomfret have you received a reply from Polo's team?

**Comment by npomfret** [comment]
No.  I raised a ticket and contacted them on twitter also, but no real response yet.

**Comment by npomfret** [comment]
From Poloniex support:

> Thank you for brining this to our attention. 
> 
> This is a display issue that we are working to fix, this has been brought up to our engineering team for rectification. Currently the display is showing the fee rate as opposed to the actual fee amount collected. 
> 
> We will be fixing this as soon as possible. If you have any further questions related to your Poloniex account, please feel free to contact us again.

**Comment by kroitor** [comment]
@npomfret thank you very much for the feedback!

**Comment by Showgofar** [comment]
as i can notice here is some more problem with fee when it was collected it TRX please check info and final return

  {
        "id": "475262662",
        "info": {
            "globalTradeID": 475262662,
            "tradeID": "4487648",
            "date": "2020-07-14 14:20:28",
            "rate": "0.000063540000",
            "amount": "0.83352287",
            "total": "0.00005296",
            "fee": "0.00095000",
            **"feeDisplay": "0.01578947 TRX (0.07125%)",**
            "orderNumber": "86597556941",
            "type": "buy",
            "category": "exchange"
        },
        "timestamp": 1594750828000,
        "datetime": "2020-07-14T18:20:28.000Z",
        "symbol": "STRAT\/BTC",
        "order": "86597556941",
        "type": "limit",
        "side": "buy",
        "takerOrMaker": null,
        "price": 6.35400000000000048962223164750184878357686102390289306640625e-5,
        "amount": 0.83352287000000002681332489373744465410709381103515625,
        "cost": 5.29600000000000011609983807669976840770686976611614227294921875e-5,
        **"fee": {
            "type": null,
            "rate": 0.000949999999999999998091804176425512196146883070468902587890625,
            "cost": 0.0007918467265000000455954509703815347165800631046295166015625,
            "currency": "STRAT"**
        }
    }

**Comment by kroitor** [comment]
@Showgofar what's your version of CCXT?

**Comment by Showgofar** [comment]
latest

**Comment by kroitor** [comment]
@Showgofar plz print your output of the **runtime version** here:

```Python
import ccxt
print('CCXT version:', ccxt.__version__)
```

**Comment by Showgofar** [comment]
yes it was problem - that files were updated - but service wast restarted
sorry

**Comment by kroitor** [comment]
@Showgofar for that matter we always ask for your actual runtime version number, and it is the step #1 in the troubleshooting section here:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by npomfret** [comment]
From Poloniex support

> I am happy to report that the fee readout should be back to normal. Please let me know if there is anything else that I can be of assistance with. 


... I have not tested it yet

**Comment by kroitor** [comment]
@npomfret thank you again! I'll try to test it with my account, let me know if you still have issues with it on your side.

**Comment by npomfret** [comment]
Here is the same trade I posted above, taken from the API today.  The fee above was `0.00125000 BTC` and is now `0.00000335 BTC`.

```
{
  "id": "471755316",
  "info": {
    "globalTradeID": 471755316,
    "tradeID": "8138",
    "date": "2020-06-21 05:32:49",
    "rate": "0.000279320000",
    "amount": "9.61652594",
    "total": "0.00268608",
    "fee": "0.00125000",
    "feeDisplay": "0.00000335 BTC (0.125%)",
    "orderNumber": "10414788064",
    "type": "sell",
    "category": "exchange"
  },
  "timestamp": 1592717569000,
  "datetime": "2020-06-21T05:32:49.000Z",
  "symbol": "XTZ/BTC",
  "order": "10414788064",
  "type": "limit",
  "side": "sell",
  "price": 0.00027932,
  "amount": 9.61652594,
  "cost": 0.00268608,
  "fee": {
    "cost": 0.00000335,
    "currency": "BTC",
    "rate": 0.00125
  }
}
```

**Comment by kroitor** [comment]
@npomfret awesome! Thank you for your feedback!
