### ISSUE TITLE
wavesexchange The request has an invalid signature

### ISSUE THREAD

**Issue by blaaaaaaa** [ccxt/ccxt#7247]
win10, python 3.8 ccxt-1.30.77 (but it didn't work with versions before that as well, at least not with 1.30.71)

Hi, sometimes I get errors when canceling orders. 
ccxt.base.errors.AuthenticationError: wavesexchange The request has an invalid signature. 

Some other orders I can cancel and it works. But if I can't cancel a order, it never works. It is not bound to a specific symbol, as I can create new orders in the same symbol and cancel them and it works. At the moment I have the errors on BSV/BTC DASH/ETH ZEC/ETH and LTC/ETH, but some cancellations may work with this symbols in general.

2020-07-10 08:50:56,632 [MainThread  ] [DEBUG]  POST http://matcher.waves.exchange/matcher/orderbook/xxx/xxx/cancel, Request: {'content-type': 'application/json', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} {"sender":"xxx","orderId":"xxx","signature":"xxx"}
2020-07-10 08:50:56,660 [MainThread  ] [DEBUG]  POST http://matcher.waves.exchange/matcher/orderbook/xxx/xxx/cancel, Response: 400 {'Server': 'nginx', 'Date': 'Fri, 10 Jul 2020 06:50:56 GMT', 'Content-Type': 'application/json', 'Content-Length': '174', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS, PUT, DELETE', 'Access-Control-Allow-Headers': 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,signature,timestamp', 'Access-Control-Expose-Headers': 'Content-Length,Content-Range', 'Backend': 'fr-2'} {"result":null,"template":"The request has an invalid signature","success":false,"error":1051904,"message":"The request has an invalid signature","status":"InvalidSignature"}

Also I encountered that fetch_open_orders sometimes doesn't get an open order we have.

**Comment by kroitor** [comment]
@blaaaaaaa hi!

On the `cancel_order` call – can you share the symbol you're having trouble with? Does that happen with any other symbols?

On `fetch_open_orders` –  when `fetch_open_orders` fails – does `fetch_orders` return it?

We will investigate and will try to fix it asap.

**Comment by kroitor** [comment]
@blaaaaaaa actually, nevermind my first question, saw the answer in your report. However, please provide as much details as you can on `fetch_open_orders`. We will try to fix both.

**Comment by kroitor** [comment]
@blaaaaaaa also, to clarify, do you have other parallel execution paths running with the same key, when `cancel_order` starts to fail?

**Comment by blaaaaaaa** [comment]
can't reproduce the fetch_open_order issue, so it might be from an older version. so lets skip it for now and if I will encounter it again I'll check with fetch_orders. 

This is the code for the cancellations, so it is synchronous and not parallel, if I get the question right.
symbols = ["BSV/BTC","DASH/ETH","ZEC/ETH","LTC/ETH","XMR/BTC"]
    for symbol in symbols:
         try:
             a = wavesexchange_maker_bot.mkr_ex.fetch_open_orders(symbol)
             print(symbol,len(a),a)
             b = wavesexchange_maker_bot.mkr_ex.cancel_order(id=a[0]["id"],symbol=symbol)
             print(b)
         ....

**Comment by kroitor** [comment]
@blaaaaaaa i just meant to make sure there's no other parallel instances of wavesexchange running at the same time, since a DEX depends on sequence numbers associated with your keys.

**Comment by blaaaaaaa** [comment]
I tried to keep the cancen as minimal as possible and it didn't work, but in trying to proof the keys are right I tried to create a new order which actually seems broken in 1.30.77. worked in 1.30.71 I think.

Traceback (most recent call last):
  File "C:/Users/admin/IdeaProjects/py/ccxt_trading_bot/playground2.py", line 18, in <module>
    b = w.create_order(symbol="ZEC/ETH",type="limit",side="buy",amount=2,price=0.0002)
  File "C:\Users\admin\IdeaProjects\py\ccxt_trading_bot\venv2\lib\site-packages\ccxt\wavesexchange.py", line 824, in create_order
    if balance > rates[assetId] * wavesMatcherFee:
TypeError: '>' not supported between instances of 'NoneType' and 'float'

**Comment by kroitor** [comment]
@blaaaaaaa does cancel_order work with 1.30.71 for you?

**Comment by blaaaaaaa** [comment]
So I created a couple of orders by hand and I could cancel them. My bot might create some orders in threads close to parallel, might this be an issue? But at the moment at least for me create order is broken, so I can test that when create order works again.

**Comment by kroitor** [comment]
> My bot might create some orders in threads close to parallel, might this be an issue?

Yes, since the sequential numbers associated with your keypair are incremented, that might yield issues if you're running parallel instances of a DEX with the same keypair. To workaround that you might want to use different keys, one keypair for each instance of your bot (for example, per pair, or depending on your setup).

> But at the moment at least for me create order is broken, so I can test that when create order works again.

We will get it fixed asap and will update you here. Thx!

**Comment by kroitor** [comment]
@blaaaaaaa one more thing, if you can post a complete verbose request/response (with symbol info, but without your keys) for the failing create_order – that would help speed up the fix. It does a balance query inside, so we need to see which assoc keys are there... Namely:

```Python
exchange.load_markets()
exchange.verbose = True
exchange.create_order(...)
```

↑ If you can paste the output here – it would help a lot. Thx again!

**Comment by blaaaaaaa** [comment]
Hi, sorry to get rid of the private info is a bit of a hassle so I did some digging to avoid that.
eg for USDT, my balance is 0, and fetch_balance() doesnt have the "USDT" key then (is that supposed to be the case?). in wavesexchange.py this will lead to balance = self.safe_value(self.safe_value(balances, code, {}), 'free') being None (instead of 0?)  and this check fails. if balance > rates[assetId] * wavesMatcherFee:
Hope this helps.

**Comment by kroitor** [comment]
@blaaaaaaa basically, that's the asset used for the fees. If you have 0 USDT, then you won't be able to pay the fees for the order and it will eventually fail. A quick question just to clarify: do you have WAVES on your account, or is it also 0?

**Comment by blaaaaaaa** [comment]
I have waves, but this loop (for i in range(0, len(priceAssets)):) 
will check these symbols: [['USDT'], ['BSV'], ['LTC'], ['BTC'], ['WEST'], ['ETH'], ['USDN'], ['DASH'], ['BCH'], ['XMR'], ['WAVES'], ['ZEC']]
If any of these symbols is not in balances, this will fail. safe_value should default to 0 instead of None I guess.

**Comment by blaaaaaaa** [comment]
Monkeypathc like this works and I can create order.

if balance is not None:
                if balance > rates[assetId] * wavesMatcherFee:
                    matcherFeeAssetId = assetId

**Comment by blaaaaaaa** [comment]
about the sequential numbers. if I put a lock on my thread when I create or cancel orders, so everything will happen one after the other, with one wavesexchange instance, will that work?

**Comment by kroitor** [comment]
@blaaaaaaa if you use the same keypair with another instance running in a parallel thread – it won't work smoothly (might cause a failure occasionally). It's not a matter of locking a single thread with a mutex or something like that – it's a matter of making sure that your keypair isn't used in parallel. Practically very few exchanges will like that, especially so for DEXs.

For example, if you do a `create_order` with one exchange, and at the same time you do `cancel_order` with the same keypair in another instance – that will almost certainly lead to problems.

**Comment by blaaaaaaa** [comment]
I use one ccxt.exchangeabc() instance in general. This instance creates/cancels orders in multiple threads, one thread per symbol). Thought it worked fine so far. I#ll test a little bit again for wavesexchange. thx for the help.

**Comment by kroitor** [comment]
> This instance creates/cancels orders in multiple threads, one thread per symbol). 

I would not recommend that, since it will most likely cause problems, really. That's due to the fact that the sequential incremental numbers are associated with your keypair (not the instance itself). The general approach (if you want to trade with multiple pairs with the same exchange) is to use different keypairs, one keypair per symbol. Otherwise it might lead to all sorts of unexpected behaviour (that's purely from my experience). Hope it helps.

P.S. We will, of course, fix the `create_order` shortly.
