### ISSUE TITLE
Add Crypto.com exchange

### ISSUE THREAD

**Issue by Pandasto** [ccxt/ccxt#7254]
API Doc: https://exchange-docs.crypto.com/
URL: https://crypto.com/exchange/
Fee: https://help.crypto.com/en/articles/3511276-fees-on-the-exchange
Volume: $11 562 647
Address: Unit 1506-07, 15/F, Pacific Plaza 418 Des Voeux Rd W, Hong Kong.
Company Info: Centralized Exchange, https://coinpaprika.com/exchanges/cryptocom-exchange/
TNC: --
Registration: https://crypto.com/en/index.html
Based Country: Hong Kong
Whitepaper: https://crypto.com/images/chain_whitepaper.pdf
Priority: High
Github group: https://github.com/crypto-com
Note: Growing very rapidly, having API competition right now https://blog.crypto.com/crypto-com-exchange-launches-the-trading-api-race-with-1m-prize-pool/
Type: Centrailzed Ex
Discussion: https://bitcointalk.org/index.php?topic=5079246.20

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/6817
