### ISSUE TITLE
transferring funds from SPOT to FUTURES (and vice-versa)

### ISSUE THREAD

**Issue by cadmufasa** [ccxt/ccxt#7266]
Hello,

I am trying to put code togehter to transfer funds from the SPOT wallet to the FUTURES wallet (and vice-versa).

I saw this message:
https://github.com/ccxt/ccxt/issues/6496

I saw this code here:
```
const transfer = await exchange.sapi_post_futures_transfer({
    'asset': 'USDT',
    'amount': '10',
    'type': 1,
})
```

but I could not locate what the variable TYPE is and what is its purpose.

Also, this seem sto send money from SPOT to FUTURES.

How would one get from FUTURES back to SPOT

TIA

**this is what i have found**
```
        # Reference: https://github.com/ccxt/ccxt/issues/6496
        # https://binance-docs.github.io/apidocs/spot/en/#change-log
        # POST /sapi/v1/sub-account/futures/transfer to transfer between futures and spot accout of sub-account.
```

**Comment by kroitor** [comment]
Hi!

> but I could not locate what the variable TYPE is and what is its purpose.

It is documented in Binance's API docs here: https://binance-docs.github.io/apidocs/spot/en/#new-future-account-transfer-futures. CCXT Manual says _"consult the exchanges' API docs"_.

Let us know if that does not answer your question.

**Comment by cadmufasa** [comment]
Hi kroitor,

Yes, this answers the questions. Thanks for the response. 

Regards.
