### ISSUE TITLE
how to listen to websocket in background?

### ISSUE THREAD

**Issue by hamedbaftam** [ccxt/ccxt#7268]
how to listen to websocket in background?

**Comment by kroitor** [comment]
@hamedbaftam you can do this with CCXT Pro: https://ccxt.pro
See the examples here: https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro/
And the CCXT Pro Manual here: https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual

Let us know if that does not answer your question.
