### ISSUE TITLE
Get deposits and withdrawals?

### ISSUE THREAD

**Issue by exzib** [ccxt/ccxt#727]
How come we cant pull out our withdrawal and deposit history?

**Comment by kroitor** [comment]
@exzib I guess, nobody has unified it yet ) CCXT allows fetching deposit and withdrawal history with custom methods right away out of the box (where supported by the exchange), but that part of the API was not unified in a cross-exchange-compatible-way yet. So, if you feel like you want to give it a try, i'd recommend to start here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md
Does this answer your question?

**Comment by Bomper** [comment]
+1 for a unified method for fetching transfers (deposits and withdrawals). A particular case is airdrops, which for Kraken for example, appear as a ledger entry with `type` = `transfer`.

**Comment by sebastianhaberey** [comment]
+1 it would be great to have a unified method for deposits and withdrawals. 

Would this involve writing API-specific mappings / strategies for each of the 100+ exchanges supported by ccxt? Or is there an easier way?

**Comment by kroitor** [comment]
@sebastianhaberey 

- https://github.com/ccxt/ccxt/issues/1896
- https://github.com/ccxt/ccxt/pull/2526
- https://github.com/ccxt/ccxt/pull/2355
- https://github.com/ccxt/ccxt/pull/2610
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code ;)
