### ISSUE TITLE
PHP 5.6 print()-function problem

### ISSUE THREAD

**Issue by Showgofar** [ccxt/ccxt#7270]
hello
on latest version at php 5.6 there is an error
as i can see 

print()  is reserved function
but at PHP 7 it works fine

Parse error: syntax error, unexpected 'print' (T_PRINT), expecting identifier (T_STRING) in /home/httpd/trade/ccxt/php/base/Exchange.php on line 1262 

at least at $version = '1.22.9'; it was OK

**Comment by kroitor** [comment]
@Showgofar will fix it shortly, thanks for reporting.
