### ISSUE TITLE
Bittrex symbol USDC/BTC is reversed

### ISSUE THREAD

**Issue by clocasto** [ccxt/ccxt#7281]
- **OS:** Ubuntu 18.04
- **Programming Language version:** Node.js 12.18.2
- **CCXT version:** 1.31.32

The `USDC/BTC` symbol on `bittrex` seems to have the reverse base and quote order from other exchanges which have this pair. Although I haven't exhaustively checked other exchanges, `cex`, `hitbtc`, and `coinbasepro` all list the pair with `BTC/USDC` as the symbol.

CoinMarketCap only lists a single coin with the name `USDC`, so I think that `bittrex` is actually reversed here. I verified the above using the CLI:

```sh
node examples/js/cli bittrex markets --table | grep USDC/BTC
> # Row found with USDC/BTC

node examples/js/cli bittrex markets --table | grep BTC/USDC
> # No rows found


node examples/js/cli cex markets --table | grep BTC/USDC
> # Row found with BTC/USDC

node examples/js/cli coinbasepro markets --table | grep BTC/USDC
> # Row found with BTC/USDC

node examples/js/cli hitbtc markets --table | grep BTC/USDC
> # Row found with BTC/USDC
```

**Comment by kroitor** [comment]
This is documented in the Manual and it has been answered a lot of times in the issues:



- https://github.com/ccxt/ccxt/issues/3143
- https://github.com/ccxt/ccxt/wiki/Manual#consistency-of-base-and-quote-currencies
- https://github.com/ccxt/ccxt/issues/252

> The answer is thoroughly described in [the Manual](https://github.com/ccxt-dev/ccxt/wiki). I would recommend reading it very carefully letter by letter prior to coding. Most of non-obvious details are explained there. 

> Namely: 

> - the market structures are described here: https://github.com/ccxt-dev/ccxt/wiki/Manual#market-structure.
> - ids and symbols are described here: https://github.com/ccxt-dev/ccxt/wiki/Manual#market-ids-and-symbols
> - the naming consistency is described here: https://github.com/ccxt-dev/ccxt/wiki/Manual#naming-consistency

> The `info` substructure is confusing you there, but you should not actually pay a lot of attention to it, if you're not extending the code. The `info` contains an original **unparsed** reply from the exchange. If you want to know real base and quote currencies, use the `base` and `quote` fields disregarding the contents of `info`.

> Now depending on which exchange you are using, some of them have a reversed (inconsistent) pair naming, where they actually misplaced base and quote. For those the ccxt will do a correction, switching sides `base` and `quote` currencies when parsing exchange replies. This logic is financially and terminologically correct.

-----------------------------------------

Let us know if the above does not answer your question. Feel free to reopen it or just ask further questions, if any.
