### ISSUE TITLE
liqui parse_order is returning None when order remaining size is zero

### ISSUE THREAD

**Issue by dimitar-petrov** [ccxt/ccxt#729]
Hello Guys,

order['remaining'] is None instead of 0 for liqui.py

Comparision of liqui.py
```
        remaining = self.safe_float(order, 'amount')
```

versus bittrex.py
```
 remaining = self.safe_float(order, 'QuantityRemaining', 0.0)
```

BR,
Dimitar

**Comment by kroitor** [comment]
Hi! We can't set it to 0 by default, because that would mean that the order is filled and closed. Liqui does not return that particular field consistently, so we have to set it to None to indicate the undefined remaining value. Does this answer your question ?

**Comment by dimitar-petrov** [comment]
Hi krotor,

Alright, I got you.

I am actually trying to work with ccxt.yobit, but it is inheriting parse_order from liqui.
Does same inconsistency apply to yobit ordering?

Thanks.

**Comment by kroitor** [comment]
@dimitar-petrov yep, all BTC-e clones have that API, they can only report remaining volumes on open orders, and if the order is closed, they don't report that at all, making it impossible to deduce from their data.

**Comment by dimitar-petrov** [comment]
Thanks @kroitor !
