### ISSUE TITLE
Trading Pair Markets hardcoded for Indodax

### ISSUE THREAD

**Issue by adrian-rublix** [ccxt/ccxt#7290]
Trading Pair Markets hardcoded for Indodax and the ccxt package doesn't support api requets for markets just recently added
(Note: HEDG/IDR trading pair was just recently added to the exchange a few days ago)

- OS: Ubuntu
- Programming Language version: Python
- CCXT version: 1.26.99

code:
```
print (ccxt.indodax().fetch_order_book('HEDG/IDR'))
```

error message:
```
BadSymbol: indodax does not have market symbol HEDG/IDR
```

**Comment by kroitor** [comment]
@adrian-rublix hi! First of, thx for your involvement and for the PR!

However, please, see the following, we're moving away from hardcoding:

- https://github.com/ccxt/ccxt/pull/7182
- https://github.com/ccxt/ccxt/issues/4183#issuecomment-649878390

We will get #7182 that merged asap.
Thanks again!
