### ISSUE TITLE
[probit] accessToken expired, call signIn() method

### ISSUE THREAD

**Issue by firepol** [ccxt/ccxt#7295]
Trying the method "fetch_balances" as I do with many other exchanges and I get this error:

```
  File "/myproject/venv/lib/python3.7/site-packages/ccxt/probit.py", line 1165, in sign
    raise AuthenticationError(self.id + ' accessToken expired, call signIn() method')
ccxt.base.errors.AuthenticationError: probit accessToken expired, call signIn() method
```

- OS: Ubuntu Linux
- Programming Language version: Python 3.7
- CCXT version: 1.31.45

I created and verified the api key/secret (read-only access)a few miutes ago. I don't think I copied/pasted it wrongly...
As sanity check I tried to create a new api key and give also trade and withdrawal access and I get the same error.

As the error suggests, I think the API should be adjusted to call signIn() or so...
@kroitor hope you can figure it out, thanks and cheers.

**Comment by kroitor** [comment]
@firepol that is a message that's returned by CCXT to you, meaning that you are the one to call `signIn()`. The token is valid for 15 minutes (that' how Probit works).

Let me know if that does not answer your question.

**Comment by c0dehunter** [comment]
Answered here:

https://github.com/ccxt/ccxt/issues/7406#issuecomment-668519691
