### ISSUE TITLE
[liquid] fees are changing

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#7296]
<img width="569" alt="Screenshot 2020-07-17 at 16 37 24" src="https://user-images.githubusercontent.com/5489469/87804546-ee0aa980-c84b-11ea-9a74-fef488165a36.png">

**Comment by kroitor** [comment]
@npomfret this table still shows the old fees however: https://www.liquid.com/fees/
Can you share the link to the source of the info?

**Comment by npomfret** [comment]
They sent me an email

**Comment by npomfret** [comment]
Their website looks a bit strange, why are maker fees lowest (05) for users with no trading volume?

**Comment by kroitor** [comment]
@npomfret can you ask them about it? 

Because it contradicts to their own webpage on fees...

> why are maker fees lowest (0%) for users with no trading volume?

Yes, I also found that very weird...

**Comment by npomfret** [comment]
will do

**Comment by npomfret** [comment]
From liquid:

> Hi Nick, yes, the lowest level has zero maker fees to make it easier to get started with Liquid. 

Don't have an answer on the fees changing.
