### ISSUE TITLE
How to get all exchanges, markets and pairs?

### ISSUE THREAD

**Issue by exzib** [ccxt/ccxt#730]
Is there anyway to grab all exchanges markets and pairs in PHP?

I've been trying to loop through the $exchanges with no success like so:

https://i.imgur.com/3r9mJaF.png

**Comment by kroitor** [comment]
Learn to catch and work with exceptions. I made an example for you here:

https://github.com/ccxt/ccxt/blob/master/examples/php/load-all-at-once.php

More about it here:
- https://github.com/ccxt/ccxt/wiki/Manual#error-handling
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
