### ISSUE TITLE
finding SUM of LONG and SHORT positions for the SPOT markets

### ISSUE THREAD

**Issue by cadmufasa** [ccxt/ccxt#7300]
Hello,

I am trying to get **sum(SHORT)** and **sum(LONG)** positions for the **SPOT market**.

I saw this message here:
https://github.com/ccxt/ccxt/issues/6469

It is my understandng that the FUTURES market can use :
        positions   = exchange.fapiPrivate_get_positionrisk( )
to get the POSITIONS

and use 
	`balance = exchange.fetch_balance( )`
to get the balances for BNB and USDT 

With the 
	`positions   = exchange.fapiPrivate_get_positionrisk( )`
option, one can see the sum of LONGs and SHORTs by following the positionSide field/column.

Example:
```
[... snip ...]
 {'symbol': 'BTCUSDT', 'positionAmt': '0.000', 'entryPrice': '0.00000', 'markPrice': '9167.31054468', 'unRealizedProfit': '0.00000000', 'liquidationPrice': '0', 'leverage': '3', 'maxNotionalValue': '200000000', 'marginType': 'cross', 'isolatedMargin': '0.00000000', 'isAutoAddMargin': 'false', 'positionSide': 'BOTH'}
```

**QUESTION**: is there an equivalent of 
	`positions   = exchange.fapiPrivate_get_positionrisk( )`
for the **SPOT** market?

TIA

**Comment by cadmufasa** [comment]
Hi again,

When executing the following command:


I got the following items returned
     **wallets            = exchange.fetch_balance('BTC/USDT')**


```
[... snip ...]

        ITEM NUMBER : 0
        {'asset': 'BTC', 'free': '0.00000065', 'locked': '0.00000000'}
        -------------------------------------------------------------------------

        ITEM NUMBER : 1
        {'asset': 'BTCB', 'free': '0.00000000', 'locked': '0.00000000'}
        -------------------------------------------------------------------------

        ITEM NUMBER : 2
        {'asset': 'BTCUP', 'free': '0.00000000', 'locked': '0.00000000'}
        -------------------------------------------------------------------------

        ITEM NUMBER : 3
        {'asset': 'BTCDOWN', 'free': '0.00000000', 'locked': '0.00000000'}
        -------------------------------------------------------------------------
[..snip ...]_
```

QUESTION:  In the example above, does the Asset Name of **BTCUP** and BTCDOWN represent the **LONGs and SHORTs for BTC**?

**Comment by cadmufasa** [comment]
Found the answer

**Comment by kroitor** [comment]
@cadmufasa thx for reporting back! If you have the answer – it would be great if you can post here in a bit more details, so that other users could find it as well, it would be very helpful and the community will be thankful to you. Thanks again!
