### ISSUE TITLE
IDEX partial fills showing wrong cost

### ISSUE THREAD

**Issue by presence35** [ccxt/ccxt#7303]
- OS: linux
- Programming Language version: php
- CCXT version: 1.30.41

```
$order = $exchange->fetchOrder($orderID,$o['symbol'],array("type" => strtoupper($o['side'])));

if ($order['remaining'] > 0) {	
   $filled = (number_format($filled,2) == number_format($order['filled'],2) ? 0 : $order['filled']);
   $of = " of " . ($order['amount'] < 100 ? number_format($order['amount'],3) : intval($order['amount']));
 $this->writeLog("Partial: " . $order['filled'] . $of);		
}

I think the fetchOrder() function is not grabbing the remaining field properly. When a partial order is triggered it's returning a cost of the remainder, not what was just filled.
```

**Comment by kroitor** [comment]
@presence35 can you plz post your verbose output for it?

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help (we always ask for it)

```PHP
$exchange->load_markets();
$exchange->verbose();
$order = $exchange->fetchOrder($orderID,$o['symbol'],array("type" => strtoupper($o['side'])));
```

**Comment by presence35** [comment]
Hopefully this helps.

Request: POST https://api.idex.market/returnOrderStatus [ "Content-Type: application\/json", "Accept: application\/json" ] {"orderHash":"","type":"SELL"} Response: POST https://api.idex.market/returnOrderStatus 200 { "date": [ "Sun, 19 Jul 2020 11:27:09 GMT" ], "content-type": [ "application\/json" ], "set-cookie": [ "__cfduid=; expires=Tue, 18-Aug-20 11:27:09 GMT; path=\/; domain=.idex.market; HttpOnly; SameSite=Lax; Secure" ], "content-encoding": [ "gzip" ], "cf-cache-status": [ "DYNAMIC" ], "cf-request-id": [ "04086cfc080000c2ea758f6200000001" ], "expect-ct": [ "max-age=604800, report-uri=\"https:\/\/report-uri.cloudflare.com\/cdn-cgi\/beacon\/expect-ct\"" ], "strict-transport-security": [ "max-age=15552000; preload" ], "x-content-type-options": [ "nosniff" ], "server": [ "cloudflare" ], "cf-ray": [ "5b5417734a68c2ea-FRA" ] } {"filled":"1722.976765674608276691","initialAmount":"3002.690786677066843376","timestamp":1587900367,"orderHash":"","orderNumber":5026041571,"market":"ETH_BLT","type":"sell","params":{"tokenBuy":"0x0000000000000000000000000000000000000000","buySymbol":"ETH","buyPrecision":18,"amountBuy":"900807236003120053","tokenSell":"0x107c4504cd79c5d2696ea0030a8dd4e92601b82e","sellSymbol":"BLT","sellPrecision":18,"amountSell":"3002690786677066843376","expires":190000,"nonce":228,"user":""},"price":"0.0003","amount":"1279.714021002458566685","status":"open","total":"0.38391420630073757"} 



And the order array below. The remaining field is empty. I think it should be initialAmount-filled from above.

Array ( [info] => Array ( [timestamp] => 1587900367 [orderHash] => [orderNumber] => 5026041571 [market] => ETH_BLT [type] => sell [params] => Array ( [tokenBuy] => 0x0000000000000000000000000000000000000000 [buySymbol] => ETH [buyPrecision] => 18 [amountBuy] => 900807236003120053 [tokenSell] => 0x107c4504cd79c5d2696ea0030a8dd4e92601b82e [sellSymbol] => BLT [sellPrecision] => 18 [amountSell] => 3002690786677066843376 [expires] => 190000 [nonce] => 228 [user] => ) [price] => 0.0003 [amount] => 1279.714021002458566685 [status] => open [total] => 0.38391420630073757 ) [id] => [clientOrderId] => [symbol] => BLT/ETH [timestamp] => 1587900367000 [datetime] => 2020-04-26T11:26:07.000Z [side] => sell [amount] => 1279.7140210025 [price] => 0.0003 [type] => limit [filled] => [remaining] => [cost] => 0.38391420630074 [status] => open [lastTradeTimestamp] => [average] => [trades] => [fee] => )

**Comment by kroitor** [comment]
@presence35 when you get an order from CCXT it has an `info` field.

In your `info` we see this:

```
[info] => Array (
    [timestamp] => 1587900367
    [orderHash] => 
    [orderNumber] => 5026041571
    [market] => ETH_BLT
    [type] => sell
    [params] => Array ( 
        [tokenBuy] => 0x0000000000000000000000000000000000000000
        [buySymbol] => ETH
        [buyPrecision] => 18
        [amountBuy] => 900807236003120053
        [tokenSell] => 0x107c4504cd79c5d2696ea0030a8dd4e92601b82e
        [sellSymbol] => BLT
        [sellPrecision] => 18
        [amountSell] => 3002690786677066843376
        [expires] => 190000
        [nonce] => 228
        [user] => 
    )
    [price] => 0.0003
    [amount] => 1279.714021002458566685
    [status] => open
    [total] => 0.38391420630073757
)
```

↑ As you can see from the above `info`, it's different from your verbose response, so this must be a response from a different call. And, from the `info` it follows that we can't deduce the filled / remaining amount, because the structure returned by IDEX does not contain it in the `info`. 

Are you sure that you did this? ↓

```PHP
$exchange->load_markets();
$exchange->verbose = true;  // ←------------ADD THIS
$order = $exchange->fetchOrder($orderID,$o['symbol'],array("type" => strtoupper($o['side'])));
print_r($order);  // ←-------------- ADD THIS
exit (); // ←-------- ADD THIS
```

Let try once again ↑ can you post the above verbose output and make sure there are no other calls around? Please, don't break the output formatting (do not edit it, except for the orderHash if you want to hide it).

Also, please, always use [GitHub markdown](https://guides.github.com/features/mastering-markdown/) for readability and padding, surround your code and/or output with triple backticks (&#096;&#096;&#096;), like shown below:

&#096;&#096;&#096;PHP
put your code here, don't paste one line of code, paste your full short complete code snippet
&#096;&#096;&#096;

&#096;&#096;&#096;
your output here
&#096;&#096;&#096;

**Comment by kroitor** [comment]
@presence35 to clarify, the `info` from the second part of your response does not correspond to the verbose output from the first part of your response...

**Comment by kroitor** [comment]
@presence35 

```PHP

$id = 'idex';
$exchange_class = '\\ccxt\\' . $id;
$exchange = new $exchange_class(array(
    'apiKey' => 'YOUR_API_KEY',
    'secret' => 'YOUR_SECRET',
    'enableRateLimit' => true, // required by the Manual
));

$exchange->load_markets();

$exchange->verbose = true;

$orderID = 'YOUR_ORDER_ID';  // ←---------- EDIT HERE
$symbol = 'BLT/ETH';
$side = 'YOUR_VALUE';  // ←---------- EDIT HERE
$params = array(
    'type' => strtoupper($side),
);
$order = $exchange->fetchOrder($orderID, $symbol, $params);
print_r($order);
exit();
```

↑ Let us know if that does not answer your question. (That is a complete program, to make sure there's no other calls around and no confusion). Feel free to reopen it or just ask further questions, if any.
