### ISSUE TITLE
Defunct Trading Pairs

### ISSUE THREAD

**Issue by saarahrasheed** [ccxt/ccxt#7304]
There are some de-listed pairs in that the API returns when retrieving symbols. I use the following code to get all symbols from binance exchange, and then fetch their historical data.

````
exchange = 'binance'
exchange_instance = getattr(ccxt, exchange)()
markets = exchange_instance.load_markets()
symbols = exchange_instance.symbols
#### code to do some stuff 
#### then fetch prices for each symbol as:
exchange_instance.fetch_ohlcv(symbol, timeframe='1h', limit=200)
````

Some of the de-listed BTC pairs that are no longer on binance include:
1. BSV/BTC
2. SALT/BTC
3. BTT/BTC
4. BTCB/BTC

Despite being de-listed, the API is able to retrieve its latest data somehow. I think they should be removed or the fetch_ohlcv() method should return NaN or None for attempting to retrieve data for defunct symbols.

- OS: Windows
- Programming Language version: Python
- CCXT version: 1.30.93

**Comment by kroitor** [comment]
Just look into the `active` flag of the corresponding pairs. What you see is the actual set of pairs returned from Binance itself. You can verify that in verbose mode as documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/Manual#market-structure

```Python
import ccxt
exchange = ccxt.binance({
    'enableRateLimit': True,
})
markets = exchange.load_markets()
for symbol in exchange.symbols:
   market = exchange.market(symbol)
   print(symbol, 'is', 'active' if market['active'] else 'inactive or delisted')
```

> I think they should be removed or the fetch_ohlcv() method should return NaN or None for attempting to retrieve data for defunct symbols.

Nope, you should skip inactive pairs, and don't attempt to fetch them.

Let us know if that does not answer your question.

**Comment by kroitor** [comment]
P.S. we can't remove or change the list of pairs returned from Binance – they're kept there to allow fetching historical private data and for other purposes. In other words, CCXT will return the pairs as you see from the exchange API itself:

- https://api.binance.com/api/v3/exchangeInfo (you can find those pairs here returned from Binance first-hand, flagged as inactive pairs)

**Comment by saarahrasheed** [comment]
Hi @kroitor thanks a lot for the prompt response. Yes that's helpful. 

On a side note, could you tell how is it able to retreive data from the exchange if the exchange itself doesn't have it de-listed? Is it because the coin is active elsewhere and the data thereby is available?

**Comment by kroitor** [comment]
@saarahrasheed 

> On a side note, could you tell how is it able to retreive data from the exchange if the exchange itself doesn't have it de-listed? 

If you read the Manual from top to bottom and use the verbose mode or click the link from my previous response – you will see that it is able to retrieve data from the exchange, because the exchange itself still returns that data, despite that those symbols are delisted. CCXT does not decide which symbols to load and it does not filter them. What you see is what the exchange sends in response to your requests.
