### ISSUE TITLE
KeyError for new market

### ISSUE THREAD

**Issue by melnikovsa** [ccxt/ccxt#7309]
Hello!

We get KeyError 'USDT_MTA' when Poloniex add new market but it doesn't cache into ccxt markets

We use aiohttp as websever and ccxt as connector to different exchanges. Our server runs always and we need to restart him when erorr happens.

Can you add try/except block and ignore new exchange markets?

- OS: Ubuntu 18.04 LTS
- Programming Language version: Python 3.8
- CCXT version: 1.31.45

```
await poloniex.fetch_open_orders()
```

**ccxt/async_support/poloniex.py in fetch_orders at line 874**
```
        else:
            marketIds = list(response.keys())
            for i in range(0, len(marketIds)):
                marketId = marketIds[i]
                orders = response[marketId]
                m = self.markets_by_id[marketId]
                openOrders = self.parse_open_orders(orders, m, openOrders)
        for j in range(0, len(openOrders)):
            self.orders[openOrders[j]['id']] = openOrders[j]
        openOrdersIndexedById = self.index_by(openOrders, 'id')
        cachedOrderIds = list(self.orders.keys())
```

**Comment by kroitor** [comment]
Hi! 

You may want to reload the markets as explained in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#market-cache-force-reload

We will add a workaround for this issue.

**Comment by kroitor** [comment]
@melnikovsa It should work fine in CCXT as of version 1.35.60+. Let us know if you have further difficulties with it after updating to the most recent version. Thx for the feedback!

**Comment by melnikovsa** [comment]
Can you add this logic for all exchanges? 
Thanks!

**Comment by kroitor** [comment]
@melnikovsa it's a work in progress, let us know the exchange in question if you experience anything similar further down the road.
