### ISSUE TITLE
Setting up STOP_LOSS orders AFTER Order is filled

### ISSUE THREAD

**Issue by cadmufasa** [ccxt/ccxt#7313]
Hi,

I am using **PYTHON** to access the **BINANCE** servers.

I was wondering if there was a way to get a message from the server that an order is filled (completely).

Reason: the idea was that upon gettng the message that an order was filled, one can then create a **STOP_LOSS order.**

My understanding is that each ORDER can produce 1 or more TRADES.

So, in order to track when an order is filled, is one supposed to use **asyncio** to receive the message?

TIA

**Comment by fonzmeister** [comment]
It is better to just create a stoploss order straight away and use the param 'reduce only' and use the full amount you are willing to trade.

What you are asking is technically possible, but pretty cumbersome. A 'reduce only' stop will decrease your current postion.

So if you want to open a position of 2.5 ETH but only 2 ETH is filled your stoploss will close your trade of 2 ETH and will not open a new postion of 0.5 ETH in the opposite direction

**Comment by kroitor** [comment]
@fonzmeister thanks for your help!

@cadmufasa let us know if the above does not answer your question!
