### ISSUE TITLE
Proper Error Handling

### ISSUE THREAD

**Issue by cadmufasa** [ccxt/ccxt#7315]
Hi,

I am using **PYTHON** to access the **BINANCE** servers.

Just wondering how one is to properly do the Error Handling. For example, I get the following error:

I get this error for example:
Traceback (most recent call last):
  File "/root/trade_exchange/api_work/trade_binance/bin_ask_bid.py", line 405, in transfer_margin_to_spot
    'type': 2,
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 452, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/binance.py", line 1954, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 471, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 580, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/binance.py", line 1949, in handle_errors
    raise ExchangeError(feedback)
ccxt.base.errors.ExchangeError: binance {"code":-3005,"msg":"Transferring out not allowed. Transfer out amount exceeds max amount."}

**The ERROR is:**
`
ccxt.base.errors.ExchangeError: binance {"code":-3005,"msg":"Transferring out not allowed. Transfer out amount exceeds max amount."}`

It is a  **ccxt.EXCHANGE** error.

I saw this information here: https://github.com/ccxt/ccxt/wiki/Manual#exception-hierarchy

And tried the following:

```
   except (ccxt.AuthenticationError, ccxt.PermissionDenied, ccxt.InsufficientFunds,  [.. snip ..]) as e:
	print(" recoverable message " + str(e.args) )
	return

   except ccxt.ExchangeError as e:
	[... snip ...]
	print(" UN recoverable message " + str(e.args) )
	[... snip ...]
	exit()
```

The EXCHANGE error was not caught by any of the Exceptions above

I had to resort to: 

```
   except ccxt.ExchangeError as e:
        if ( search('exceeds', str(e.args[0])) and search('amount', str(e.args[0])) ):
            order   = { 'message': 'Exchange Error on ' + exchange.id + ' exchange. ' + str(e.args) }
            results     = {
                'return_code': t_api.KDC_TR_API_INPUT_ERROR,
                'data' : order,
                }
            return( results )
```

**I know this is not a good way. What can I do?**

TIA

**Comment by frosty00** [comment]
Right because the exchangeError is a super class of the errors you specified - ```ccxt.AuthenticationError, ccxt.PermissionDenied, ccxt.InsufficientFunds```

You can catch a more specific error (subclass) but not a more general error (superclass)

**Comment by cadmufasa** [comment]
Thanks for the response. 

There are a number of errors like:
**ccxt.base.errors.ExchangeError: binance {"code":-3005,"msg":"Transferring out not allowed. Transfer out amount exceeds max amount."}**

above (they fall under **ccxt.ExchangeError**). I was using the **ccxt.ExchangeError** as a type of catch all for errors that one could not recover from. 

I was hoping that there was a way to handle errors (similar to the  T**ransfer out amount exceeds max amount error**) without using if statements under **ccxt.ExchangeError**)

**Comment by frosty00** [comment]
Yeah we would need to add the proper error handling for those errors

**Comment by kroitor** [comment]
@cadmufasa can you please always follow the guidelines precisely, namely, paste your verbose request/response as described here:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
import ccxt
exchange = ccxt.binance ({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
exchange.load_markets()

exchange.verbose = True  # ←---- ADD THIS as documented in the FAQ

# your call here that triggers the error
```

↑ This snippet with the `exchange.verbose` flag will output two pieces at the very least:
- the verbose request
- the verbose response

Regardless of the issue you might have we always need both pieces (no need for your API keys). Please paste both the verbose request + verbose request using [GitHub markdown](https://guides.github.com/features/mastering-markdown/), always surround your code and output with triple backticks (&#096;&#096;&#096;), like shown below:

&#096;&#096;&#096;Python
your code here
&#096;&#096;&#096;

&#096;&#096;&#096;
your output here
&#096;&#096;&#096;

**Comment by cadmufasa** [comment]
OK, will follow guidelines
