### ISSUE TITLE
Creating limit orders on Bybit fails

### ISSUE THREAD

**Issue by scoriiu** [ccxt/ccxt#7316]
- OS: OSX
- Programming Language version:
- CCXT version: 1.31.61

```
self.exchange.create_order(symbol='BTC/USD', type='limit', side='Buy', amount=45, price=9057.5)
```

```
{ExchangeError}bybit {"ret_code":10001,"ret_msg":"bind error:json: cannot unmarshal string into Go struct field CreateOrderReq.qty of type int64","ext_code":"","ext_info":"","result":null,"time_now":"1595267748.038732","rate_limit_status":99,"rate_limit_reset_ms":1595267748036,"rate_limit":100}
```

According to docs, `qty` must be integer and 'price' a number. But the rounding functions `price_to_precision` and `amount_to_precision` return str. In case of the latter, the returned value is casted to int, but only for the `linear` order type (why not for the `inverse` as well?). See [here](https://github.com/ccxt/ccxt/blob/41c8470a6a418c18282762db991948ce87a76f2d/python/ccxt/bybit.py#L1155)

Bellow a working sample:
```
request={'side': 'Buy', 'symbol': 'BTCUSD', 'order_type': 'Limit', 'qty': 45, 'time_in_force': 'GoodTillCancel', 'price': 9057.5}
response = getattr(self, method)(self.extend(request, params))
```

**Comment by kroitor** [comment]
@scoriiu what's your **runtime version** of CCXT?

```Python
import ccxt
print(ccxt.__version__)
```

?

It has been addressed here: https://github.com/ccxt/ccxt/issues/7285

**Comment by scoriiu** [comment]
1.31.61

**Comment by kroitor** [comment]
@scoriiu must be a bug, hold on, the fix is coming.

**Comment by scoriiu** [comment]
Cool. The fix would be to cast `qty` to `int` and `price` to `float`

**Comment by scoriiu** [comment]
@kroitor Your fix above doesn't suffice. `price` needs to be casted as well.

**Comment by kroitor** [comment]
@scoriiu yep, i know, it's just a bit more involved with linear vs inverse bybit futures. I've uploaded the second commit, should be ok as of version 1.31.62+, let me know if you still have difficulties with it after upgrading. Thx for reporting it!

**Comment by kroitor** [comment]
@scoriiu P.S. the new build will arrive in ~15 minutes.

**Comment by scoriiu** [comment]
@kroitor Thanks a lot, that was quick. Great work!
