### ISSUE TITLE
Is it possible to see the release of a specific market? (question)

### ISSUE THREAD

**Issue by JanssensKobe** [ccxt/ccxt#7320]
Is it possible to see the release of a specific market?

Example:
```python
binance = ccxt.binance()

print(binance.fetch_markets())
```
Expected response:
```
[{
'id': 'ETHBTC',
'lowercaseId': 'ethbtc',
...
'release': 1595342522382, # Release in millis
...
},...]
```

**Comment by kroitor** [comment]
If the exchange provides it, you can get that from the `info`:

- https://github.com/ccxt/ccxt/wiki/Manual#market-structure

However, this is not unified yet.
Let us know if that does not answer your question.

**Comment by JanssensKobe** [comment]
@kroitor Does binance provides it?

**Comment by kroitor** [comment]
@JanssensKobe you can look into the market structure to find that out, afaik, Binance does not provide it.

```JavaScript
const ccxt = require ('ccxt')
const exchange = new ccxt.binance ({
    'enableRateLimit': true,  // required by the Manual: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})
;(async () => {

    await exchange.loadMarkets ()
    const market = exchange.market ('BTC/USDT')
    console.log (market)

}) ()
```
