### ISSUE TITLE
Incorrect precious -   Binance (ETH/BTC)

### ISSUE THREAD

**Issue by YuriyTigiev** [ccxt/ccxt#7330]
Hello, 

The function await exchange.fetchTrades(symbol = 'ETH/BTC', params={'fromId': '160063816'}, limit = 1) returns incorrect precision (9 digits instead of 8) for the field cost for the pair ['ETH/BTC'] 

CCXT 1.31.49
OS Windows 10 
Visual Studio 2019 + Python 3.8

![image](https://user-images.githubusercontent.com/22752322/88187539-b33bb380-cc47-11ea-822b-589f6d2fc396.png)

**Comment by kroitor** [comment]
What does the Binance website say about the cost of that trade?

I mean, 0.024 = 0.024939 = 0.000598536 ← mathematically it's correct.

**Comment by kroitor** [comment]
(Also, please always post test as text, don't post screenshots of text, always follow the guidelines from the FAQ as closely as you possibly can: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help)

**Comment by kroitor** [comment]
The `cost` of a trade is just a product of the `price` and `amount`. It is calculated on the client side, unless the exchange specified it for the trade (and they rarely specify it for public trades). There's no indication on the precision of the cost in Binance API docs, so that value looks arithmetically correct.

Let me know if that does not answer your question.

**Comment by YuriyTigiev** [comment]
You are not rounding the cost. Right?

```
import ccxt.async_support as ccxt
import timeit
import asyncio


async def Main():

	API_KEY = ''
	SECRET_KEY = ''

	exchange_class = getattr(ccxt, 'binance')
	exchange = exchange_class({
			'apiKey': API_KEY,
			'secret': SECRET_KEY,
			'timeout': 30000,
			'defaultType': 'spot',
			'rateLimit': 50,
			'enableRateLimit': False
	})

	pair = 'ETH/USDT'



	fromId = 132893698

	f0 = await exchange.fetch_trades(pair, params={'fromId':f'{fromId}'}, limit=1)
	f1 = await exchange.fetch_trades(pair, params={'fromId':f'{fromId-1}'}, limit=1)
	f2 = await exchange.fetch_trades(pair, params={'fromId':f'{fromId+1}'}, limit=1)


	print(f"found:\t\t{f0[0]['datetime']}, {f0[0]['timestamp']}, {f0[0]['price']}, {f0[0]['amount']}, {f0[0]['cost']}")
	print(f"found-1:\t{f1[0]['datetime']}, {f1[0]['timestamp']}, {f1[0]['price']}, {f1[0]['amount']}, {f1[0]['cost']}")
	print(f"found+1:\t{f2[0]['datetime']}, {f2[0]['timestamp']}, {f2[0]['price']}, {f2[0]['amount']}, {f2[0]['cost']}")

	await exchange.close()
	pass

```

```

found:	2020-06-07T00:00:00.454Z, 1591488000454, 241.94, 0.1146, 27.726323999999998
found-1:	2020-06-06T23:59:55.848Z, 1591487995848, 241.94, 0.04583, 11.088110200000001
found+1:	2020-06-07T00:00:00.505Z, 1591488000505, 241.94, 0.4995, 120.84903




```

**Comment by kroitor** [comment]
> You are not rounding the cost. Right?

That's right:

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/binance.py#L961
